### PR TITLE
[profiler] move _enable_dynamo_cache_lookup_profiler

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #107720

_enable_dynamo_cache_lookup_profiler used to get turned on when running `__enter__` or `__exit__` with the profiler. But it's possible to turn the profiler on and off without the context manager (e.g. with a schedule and calling `.step()`). Instead, we should put these calls (which are supposed to be executed when the profiler turns on/off) where `_enable_profiler()` and `_disable_profiler()` are called.

This puts `_enable_dynamo_cache_lookup_profiler` and `_set_is_profiler_enabled` into `_run_on_profiler_(start|stop)` and calls that on the 3 places where `_(enable|disable)_profiler` get called.

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

Differential Revision: [D48619818](https://our.internmc.facebook.com/intern/diff/D48619818)

### CODE REVIEW

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48619818).

**Review by wconstab — APPROVED** [review]
looks good to me. i don't remember why i put the dynamo enable call in a separate place than the set_is_profile_enabled call, though.

**Comment by davidberard98** [comment]
@wconstab you added the dynamo enable call before the set_is_profiler_enabled call was added. I initially put set_is_profiler_enabled next to `_enable_dynamo_cache_lookup_profiler` but realized that it would sometimes get bypassed (e.g. in traces collected internally)

**Pull request closed without merging**
