### PR TITLE
[inductor] realize_into should not alias src and dst

### LINKED ISSUE #107995: torch.compile Raises "NameError: name 'buf0' is not defined" for LeakyReLU with Empty Input Tensor
### 🐛 Describe the bug

🐛 Bug Description
When using torch.compile on a model that includes a LeakyReLU layer and providing an empty input tensor (shape [0, 0]), a NameError is triggered: "name 'buf0' is not defined."

To Reproduce
Here's a stand-alone script that reproduces the error:
```python
import torch
import torch.nn as nn

class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.layer1 = nn.LeakyReLU(negative_slope=5.2955089, inplace=True)

    def forward(self, inputs):
        return self.layer1(inputs)

ip_size = [0]
input_tensor = torch.randn(ip_size)
cuda_inputs = input_tensor.clone().to('cuda')

mymodel = CustomModel()
no_op_info = mymodel(input_tensor)

torch._dynamo.reset()
mymodel.to('cuda')
op_info = torch.compile(mymodel.forward, mode='reduce-overhead')(cuda_inputs)

print(op_info)
```
Expected Behavior
The code should run without any errors.
If this behavior is intended or part of a known issue, please feel free to close this. If you need additional information to address this, don't hesitate to ask.

Thank you!

### Versions

PyTorch version: 2.1.0.dev20230825+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.11.0 (main, Mar  1 2023, 18:26:19) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-79-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2070
GPU 1: NVIDIA GeForce RTX 2070
GPU 2: NVIDIA GeForce RTX 2070
GPU 3: NVIDIA GeForce RTX 2070

Nvidia driver version: 535.86.10
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
CPU family:                      6
Model:                           63
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       2
Stepping:                        2
CPU max MHz:                     3200.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        4794.42
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts md_clear flush_l1d
Virtualization:                  VT-x
L1d cache:                       512 KiB (16 instances)
L1i cache:                       512 KiB (16 instances)
L2 cache:                        4 MiB (16 instances)
L3 cache:                        40 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30
NUMA node1 CPU(s):               1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.1.0.dev20230825+cu118
[pip3] torchaudio==2.1.0.dev20230825+cu118
[pip3] torchvision==0.16.0.dev20230825+cu118
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+e6216047b8          pypi_0    pypi
[conda] torch                     2.1.0.dev20230825+cu118          pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230825+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230825+cu118          pypi_0    pypi

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108126

Fixes #107995

In the reproducer we have the fx graph:
```python
class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: f32[1]):
        # File: <ipython-input-1-5f62cb746ad5>:10, code: return self.layer1(inputs)
        gt: b8[1] = torch.ops.aten.gt.Scalar(arg0_1, 0)
        mul: f32[1] = torch.ops.aten.mul.Tensor(arg0_1, 5.2955089)
        where: f32[1] = torch.ops.aten.where.self(gt, arg0_1, mul);  gt = mul = None

        # No stacktrace found for following nodes
        copy_: f32[1] = torch.ops.aten.copy_.default(arg0_1, where);  arg0_1 = None
        return (where,)
```

The `where` node is both copied into `arg0_1` and returned as the output of the
function. Currently `realize_into` converts the where's storage into a
`MutationLayout` of `arg0_1`, for which no tensor named `buf0` is allocated.

This is incorrect as `where` and `arg0_1` shouldn't share storage. It also
breaks the wrapper code generation which references `buf0` directly in the
return, but never allocates a `buf0`.

This issue only appears for size zero tensors, because otherwise the `src`
buffer becomes a user of `arg0_1` which forces this copy to happen anyway.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Comment by jansel** [comment]
Is there any perf impact from this?

**Comment by peterbell10** [comment]
Running the benchmarks now

**Comment by peterbell10** [comment]
Here are the benchmark results:
https://hud.pytorch.org/benchmark/compilers?startTime=Thu%2C%2007%20Sep%202023%2021%3A03%3A42%20GMT&stopTime=Thu%2C%2014%20Sep%202023%2021%3A03%3A42%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=gh/peterbell10/602/orig&lCommit=6f21c974425a67351642159332b76096271e0229&rBranch=main&rCommit=47be61e12bd51df27182343d312dc3df485d5559

Some random download failures mean the geomeans can't be trusted but I see 1 slowdown in `MobileBertForQuestionAnswering` which I can't reproduce locally, so may just be noise. I also see several speedups including a bunch in the timm benchmarks, but again this looks like noise to me.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
