### PR TITLE
[lint] Move shellcheck to its own step

### PR DESCRIPTION
**Pull request by driazati**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#58623 [lint] Move shellcheck to its own step**

This splits out everything shellcheck related into its own job that generates and checks GHA workflows, then shellchecks those + jenkins scripts. This PR also integrates shellcheck into the changed-only stuff in `actions_local_runner.py` so that shellcheck won't do anything unless someone edits a shell script in their local checkout. This is the final piece to clean up the output of `make quicklint` and speeds it up by a good bit (before it was shellchecking everything which took a few seconds):

```
$ make quicklint -j $(nproc)
✓ quick-checks: Ensure no unqualified noqa
✓ quick-checks: Ensure canonical include
✓ quick-checks: Ensure no unqualified type ignore
✓ quick-checks: Ensure no direct cub include
✓ quick-checks: Ensure no tabs
✓ quick-checks: Ensure no non-breaking spaces
✓ shellcheck: Regenerate workflows
✓ quick-checks: Ensure no versionless Python shebangs
✓ quick-checks: Ensure correct trailing newlines
✓ shellcheck: Assert that regenerating the workflows didn't change them
✓ mypy (skipped typestub generation)
✓ cmakelint: Run cmakelint
✓ quick-checks: Ensure no trailing spaces
✓ flake8
✓ shellcheck: Extract scripts from GitHub Actions workflows
✓ shellcheck: Run Shellcheck
real 0.92
user 6.12
sys 2.45
```

Differential Revision: [D28617293](https://our.internmc.facebook.com/intern/diff/D28617293)

### CODE REVIEW

**Comment by samestep** [comment]
One thing to note: `tools/extract_scripts.py` also extracts other types of scripts from our GitHub Actions workflows (not just shell scripts), so e.g. if someone adds a GitHub Actions `${{ <expression> }}` in a JavaScript or PowerShell script, the `shellcheck` job will (correctly) fail. I'm not saying this necessarily warrants renaming the `shellcheck` lint job to something else, but it's something to consider.

**Review by samestep — APPROVED** [review]
lgtm, thanks!

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28617293).

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28617293).

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28617293).

**Pull request closed without merging**
