### PR TITLE
Fix S367052 to unblock ICVR MC3

### PR DESCRIPTION
**Pull request by ge0405**
Summary: Somehow "getitem" started to get Tensor starting from ads_ranking:996 and broke SDD pipelining FX-transformer. We need to skip the Tensor node in annotation.

Test Plan:
N4326037

# Before
 {F1099052907}

# With this diff

 {F1099052270}

Differential Revision: D49528046

### CODE REVIEW

**Review by jackiexu1992 — APPROVED** [review]

**Comment by lanza** [comment]
Accepting to help unblock ge0405. This was approved internally.

**Review by lanza — APPROVED** [review]

**Review by xush6528 — APPROVED** [review]

**Comment by ge0405** [comment]
correct the if "Tensor": continue position

**Pull request closed without merging**
