### PR TITLE
Fix the parameter error in test_device_mesh.py

### PR DESCRIPTION
**Pull request by humingxue**
Fix the parameter error in test_device_mesh.py

### CODE REVIEW

**Review by awgu — APPROVED** [review]
This looks good to me.
https://github.com/pytorch/pytorch/blob/b193f295b6e0dfbebd56bb154ce0473778a89b94/torch/distributed/_functional_collectives.py#L178-L184

I wonder though why we are not consistent in our lower camel case vs. underscores (`reduceOp` vs. `scatter_dim`). I would have expected the Python API to use underscores, while the C++ like ProcessGroupNCCL could use lower camel case, but we should not mix the two if possible since it can lead to mistakes like this.
cc: @kumpera @wanchaol

**Comment by wanchaol** [comment]
> This looks good to me.
> 
> https://github.com/pytorch/pytorch/blob/b193f295b6e0dfbebd56bb154ce0473778a89b94/torch/distributed/_functional_collectives.py#L178-L184
> 
> I wonder though why we are not consistent in our lower camel case vs. underscores (`reduceOp` vs. `scatter_dim`). I would have expected the Python API to use underscores, while the C++ like ProcessGroupNCCL could use lower camel case, but we should not mix the two if possible since it can lead to mistakes like this. cc: @kumpera @wanchaol

I agree, we should use `reduce_op` for all apis in functional collectives.

**Comment by wanchaol** [comment]
@awgu created a issue to track this https://github.com/pytorch/pytorch/issues/108900

**Pull request closed without merging**
