### PR TITLE
Update the version of ninja and scipy

### PR DESCRIPTION
**Pull request by peterjc123**
Update scipy to 1.15 and ninja to 1.10.

### CODE REVIEW

**Comment by ezyang** [comment]
Instead of unpinning them, can you just update the pins to the latest version? That way we can avoid being silently broken again if ninja does another broken release.

**Review by malfet — CHANGES_REQUESTED** [review]
Please just update the version to the one you need. Also, please consider submitting change the improves error handling on Windows as separate PR (or at least mention that in PR description)

**Comment by peterjc123** [comment]
@malfet @ezyang Done.

**Comment by malfet** [comment]
@peterjc123 thank you for the update. Can you please update PR description as well.

**Comment by peterjc123** [comment]
@malfet Done.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
