### PR TITLE
ROCm triton commit pin update

### PR DESCRIPTION
**Pull request by jataylo**
Small bump in rocm triton commit pin to resolve reported issue on 7900XTX 
> RuntimeError: Triton Error [HIP]: Code: 719, Messsage: unspecified launch failure
https://github.com/ROCmSoftwarePlatform/triton/issues/396

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang

### CODE REVIEW

**Comment by jataylo** [comment]
@jithunnair-amd @pruthvistony do we know whats going on with these rocm job failures?
https://ossci-raw-job-status.s3.amazonaws.com/log/18928921517

Seeing a lot of messages like this
`tar: conformance/conformance_test_runner.cc: Cannot change ownership to uid 576694, gid 89939: Invalid argument`

**Comment by jataylo** [comment]
Hi @malfet @kit1980 small bump in our ROCm triton commit to help us with some reported issues on Navi31.

cc: @jithunnair-amd @pruthvistony

**Review by jeffdaily — APPROVED** [review]

**Pull request closed without merging**
