### PR TITLE
Re-land: Add callgrind collection to Timer #44717

### PR DESCRIPTION
**Pull request by robieta**
Test plan: The unit test has been softened to be less platform sensitive.

### CODE REVIEW

**Comment by robieta** [comment]
CC @ngimel @ezyang

**Comment by ezyang** [comment]
Huh, did we miss this last PR because slow tests aren't run by default? @seemethere do target specifiers work yet? O/W you can just push a synthetic PR to `ci-all/ASDFAsdf` branch to trigger all tests.

**Comment by xkszltl** [comment]
Want to bring up an issue with this PR:
The sourceware.org repo is extremely slow when accessing from China, almost unusable.
I have a local git mirror so it won't be too bad for me after the initial setup, but could be an terrible experience for others.

Should we ask for pre-built binary from distro, instead of having it as a submodule?

**Comment by ezyang** [comment]
cc @malfet we should just go back to vendoring the headers directly

**Comment by robieta** [comment]
I need to do a follow up PR to address a couple papercuts anyway, which I was going to do today. Do we have a preference between vendoring the headers vs. a mirror repo?

**Comment by ezyang** [comment]
Header vendor seems much better to me

**Comment by malfet** [comment]
Following PR should embed the headers: https://github.com/pytorch/pytorch/pull/45914

**Pull request closed without merging**
