### PR TITLE
Support Scalar[] type

### PR DESCRIPTION
**Pull request by smessmer**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#19589 Support Scalar[] type**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D15038962/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #19592 Add test cases for optional of list&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D15039888/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #19593 Simplify argument test cases&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D15039887/)

This adds the functionality for kernels to take `Scalar[]` (i.e. list of scalars) attributes and return them.
Before, kernels were able to take and return `Scalar`, but not `Scalar[]`, which was inconsistent when compared with `int`, `float` or any of our other data types.

cc @zdevito for the changes to IValue

Differential Revision: [D15038962](https://our.internmc.facebook.com/intern/diff/D15038962/)

### CODE REVIEW

**Review by dzhulgakov — CHANGES_REQUESTED** [review]
Wait a sec, what are you trying to do?

Scalar is just a wrapper for int/double that is used as an argument in some math functions (I imagine for proper type casting). IValue should NOT store Scalar (which is already as tagged union itself) and instead store raw constituents. Similarly logic for ScalarList.

But where do we need ScalarList in the first place?

**Comment by smessmer** [comment]
The old JIT custom op API accepts `Scalar[]` as an argument (i.e. `std::vector<Scalar>`), but not as a return type. I want to fix the inconsistency. I'm not sure if this is the best approach either, open to suggestions.

**Comment by dzhulgakov** [comment]
Do we actually have at least one use case for it or example usage? Imho, it doesn't really make sense to have a vector of scalars.

**Comment by smessmer** [comment]
we decided to go the different route of disallowing `Scalar[]` entirely, also in arguments.

**Pull request closed without merging**
