### PR TITLE
remove dead code

### PR DESCRIPTION
**Pull request by ernest-lu**
Fixes issue-138673: [issue](https://github.com/pytorch/pytorch/issues/138673)

### CODE REVIEW

**Review by Aidyn-A — CHANGES_REQUESTED** [review]
This PR introduces changes to `third_party/cpuinfo` and `third_party/kineto` that are out of scope. Please remove those diffs and keep only `test/test_proxy_tensor.py`.

**Review by colesbury — APPROVED** [review]

**Review by Aidyn-A — APPROVED** [review]
Looks good now. Thanks!

**Pull request closed without merging**
