### PR TITLE
Allow users to build in DEBUG=1 mode without getting:

### PR DESCRIPTION
**Pull request by dlibenzi**
lib/libcaffe2.so: undefined reference to `c10::Half::from_bits'

### CODE REVIEW

**Comment by ezyang** [comment]
Misspelling aside, this seems highly unlikely to be the right fix to the problem.

**Comment by ezyang** [comment]
Can you apply this diff and see if it solves your problem:

```
diff --git a/c10/util/Half.h b/c10/util/Half.h
index e3ba80419..ec10a2bdb 100644
--- a/c10/util/Half.h
+++ b/c10/util/Half.h
@@ -321,7 +321,7 @@ namespace detail {
 
 } // namespace detail
 
-struct alignas(2) Half {
+struct alignas(2) C10_API Half {
   unsigned short x;
 
   struct from_bits_t {};
```

**Comment by dlibenzi** [comment]
> C10_API

Not even need to try. It sure is:

#define C10_EXPORT __attribute__((__visibility__("default")))

Changing PR to use the above.

**Comment by dlibenzi** [comment]
> Can you apply this diff and see if it solves your problem:
> 
> ```
> diff --git a/c10/util/Half.h b/c10/util/Half.h
> index e3ba80419..ec10a2bdb 100644
> --- a/c10/util/Half.h
> +++ b/c10/util/Half.h
> @@ -321,7 +321,7 @@ namespace detail {
>  
>  } // namespace detail
>  
> -struct alignas(2) Half {
> +struct alignas(2) C10_API Half {
>    unsigned short x;
>  
>    struct from_bits_t {};
> ```

That did not work. But we are on the right track.

**Comment by dlibenzi** [comment]
This is OK:

```
diff --git a/c10/util/Half.h b/c10/util/Half.h
index e3ba80419..ec10a2bdb 100644
--- a/c10/util/Half.h
+++ b/c10/util/Half.h
@@ -321,7 +321,7 @@ namespace detail {
 
 } // namespace detail
 
-struct alignas(2) Half {
+struct C10_API alignas(2) Half {
   unsigned short x;
 
   struct from_bits_t {};
```

**Review by soumith — APPROVED** [review]

**Review by soumith — CHANGES_REQUESTED** [review]
looks like legit build failures:

```
Mar 01 17:55:32 In file included from /pytorch/c10/util/typeid.h:21:0,
Mar 01 17:55:32                  from /pytorch/c10/core/CPUAllocator.cpp:2:
Mar 01 17:55:32 /pytorch/c10/util/Half.h:324:16: error: expected identifier before ‘alignas’
Mar 01 17:55:32  struct C10_API alignas(2) Half {
Mar 01 17:55:32                 ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:324:32: error: invalid type in declaration before ‘{’ token
Mar 01 17:55:32  struct C10_API alignas(2) Half {
Mar 01 17:55:32                                 ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:324:16: warning: attribute ignored [-Wattributes]
Mar 01 17:55:32  struct C10_API alignas(2) Half {
Mar 01 17:55:32                 ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:324:16: note: an attribute that appertains to a type-specifier is ignored
Mar 01 17:55:32 /pytorch/c10/util/Half.h:325:3: error: expected primary-expression before ‘unsigned’
Mar 01 17:55:32    unsigned short x;
Mar 01 17:55:32    ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:325:3: error: expected ‘}’ before ‘unsigned’
Mar 01 17:55:32 /pytorch/c10/util/Half.h:325:3: error: expected ‘,’ or ‘;’ before ‘unsigned’
Mar 01 17:55:32 /pytorch/c10/util/Half.h:334:10: error: expected constructor, destructor, or type conversion before ‘=’ token
Mar 01 17:55:32    Half() = default;
Mar 01 17:55:32           ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:337:66: error: ISO C++ forbids declaration of ‘Half’ with no type [-fpermissive]
Mar 01 17:55:32    constexpr C10_HOST_DEVICE Half(unsigned short bits, from_bits_t) : x(bits){};
Mar 01 17:55:32                                                                   ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h: In function ‘constexpr int c10::Half(short unsigned int, c10::from_bits_t)’:
Mar 01 17:55:32 /pytorch/c10/util/Half.h:337:66: error: ‘constexpr int c10::Half(short unsigned int, c10::from_bits_t)’ redeclared as different kind of symbol
Mar 01 17:55:32 /pytorch/c10/util/Half.h:324:27: note: previous declaration ‘int c10::Half’
Mar 01 17:55:32  struct C10_API alignas(2) Half {
Mar 01 17:55:32                            ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:337:70: error: only constructors take member initializers
Mar 01 17:55:32    constexpr C10_HOST_DEVICE Half(unsigned short bits, from_bits_t) : x(bits){};
Mar 01 17:55:32                                                                       ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:337:78: error: body of constexpr function ‘constexpr int c10::Half(short unsigned int, c10::from_bits_t)’ not a return-statement
Mar 01 17:55:32    constexpr C10_HOST_DEVICE Half(unsigned short bits, from_bits_t) : x(bits){};
Mar 01 17:55:32                                                                               ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:337:78: warning: no return statement in function returning non-void [-Wreturn-type]
Mar 01 17:55:32 /pytorch/c10/util/Half.h: At global scope:
Mar 01 17:55:32 /pytorch/c10/util/Half.h:338:42: error: ISO C++ forbids declaration of ‘Half’ with no type [-fpermissive]
Mar 01 17:55:32    inline C10_HOST_DEVICE Half(float value);
Mar 01 17:55:32                                           ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:338:42: error: ‘int c10::Half(float)’ redeclared as different kind of symbol
Mar 01 17:55:32 /pytorch/c10/util/Half.h:324:27: note: previous declaration ‘int c10::Half’
Mar 01 17:55:32  struct C10_API alignas(2) Half {
Mar 01 17:55:32                            ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:339:43: error: non-member function ‘c10::operator float()’ cannot have cv-qualifier
Mar 01 17:55:32    inline C10_HOST_DEVICE operator float() const;
Mar 01 17:55:32                                            ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:339:43: error: ‘c10::operator float()’ must be a nonstatic member function
Mar 01 17:55:32 /pytorch/c10/util/Half.h:350:3: error: ‘Half’ does not name a type
Mar 01 17:55:32    Half real_;
Mar 01 17:55:32    ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:351:3: error: ‘Half’ does not name a type
Mar 01 17:55:32    Half imag_;
Mar 01 17:55:32    ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:353:3: error: ‘Half’ does not name a type
Mar 01 17:55:32    Half real() const {
Mar 01 17:55:32    ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:356:3: error: ‘Half’ does not name a type
Mar 01 17:55:32    Half imag() const {
Mar 01 17:55:32    ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h: In constructor ‘ComplexHalf::ComplexHalf(std::complex<float>)’:
Mar 01 17:55:32 /pytorch/c10/util/Half.h:360:9: error: class ‘ComplexHalf’ does not have any field named ‘real_’
Mar 01 17:55:32        : real_(value.real()), imag_(value.imag()) {}
Mar 01 17:55:32          ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:360:30: error: class ‘ComplexHalf’ does not have any field named ‘imag_’
Mar 01 17:55:32        : real_(value.real()), imag_(value.imag()) {}
Mar 01 17:55:32                               ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h: In member function ‘ComplexHalf::operator std::complex<float>() const’:
Mar 01 17:55:32 /pytorch/c10/util/Half.h:362:13: error: ‘real_’ was not declared in this scope
Mar 01 17:55:32      return {real_, imag_};
Mar 01 17:55:32              ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:362:20: error: ‘imag_’ was not declared in this scope
Mar 01 17:55:32      return {real_, imag_};
Mar 01 17:55:32                     ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:362:25: error: could not convert ‘{<expression error>, <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘std::complex<float>’
Mar 01 17:55:32      return {real_, imag_};
Mar 01 17:55:32                          ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h: At global scope:
Mar 01 17:55:32 /pytorch/c10/util/Half.h:387:16: error: ‘Half’ does not name a type
Mar 01 17:55:32    using type = Half;
Mar 01 17:55:32                 ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:490:59: error: ‘Half’ does not name a type
Mar 01 17:55:32  C10_API std::ostream& operator<<(std::ostream& out, const Half& value);
Mar 01 17:55:32                                                            ^
Mar 01 17:55:32 /pytorch/c10/util/Half.h:492:1: error: expected declaration before ‘}’ token
Mar 01 17:55:32  } // namespace c10
Mar 01 17:55:32  ^
Mar 0
```

**Comment by dlibenzi** [comment]
Strange, it worked on my workstation.
I think it might be an issue with multiple __attribute__

**Comment by dlibenzi** [comment]
Yes, CLANG 7 works:

https://gcc.godbolt.org/z/KpVfEt

GCC doesn't (attr before align):

https://gcc.godbolt.org/z/-GIIhs

And align before attr:

https://gcc.godbolt.org/z/1-6mqq

**Comment by soumith** [comment]
damn gcc. is there any semblance of a workaround? cc: @smessmer @ezyang

**Comment by dlibenzi** [comment]
> damn gcc. is there any semblance of a workaround? cc: @smessmer @ezyang

This is OK, but it is not using the C++ alignas, so for Windows might require extra macros:

https://gcc.godbolt.org/z/F0iYrb

**Comment by dlibenzi** [comment]
> > damn gcc. is there any semblance of a workaround? cc: @smessmer @ezyang
> 
> This is OK, but it is not using the C++ alignas, so for Windows might require extra macros:
> 
> https://gcc.godbolt.org/z/F0iYrb

Gave it a shot with the extra macros.

**Review by soumith — APPROVED** [review]
waiting for CI to pass and then will land

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
```
02:53:32 C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build\c10/util/Half.h(328): error: member "c10::Half::from_bits" may not be initialized
02:53:32 
```

**Pull request closed without merging**
