### PR TITLE
fix bash math for pr-sanity-check?

### PR DESCRIPTION
**Pull request by albanD**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #100736
* __->__ #100735

The current version fails with `.github/scripts/pr-sanity-check.sh: line 44: "0" + "5": syntax error: operand expected (error token is ""0" + "5"")`.

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]
stamp

**Review by malfet — APPROVED** [review]
This is weird...

**Comment by albanD** [comment]
FYI this is failing with ".github/scripts/pr-sanity-check.sh: line 44: "0" + "5": syntax error: operand expected (error token is ""0" + "5"")" today.

**Comment by albanD** [comment]
> I understand why it fails (and actually, can guess what's caused a regression), but referencing variables this way is a bit unusual.

Ho I would be curious to hear more?
Also if you think there is a better way to do that, I'm happy to update this (or do a follow up if it gets merged).

**Pull request closed without merging**
