### PR TITLE
[ONNX] Add 0d-tensor test case in runtime check

### PR DESCRIPTION
**Pull request by titaiwangms**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #87212

### CODE REVIEW

**Comment by BowenBao** [comment]
Why no_runtime, does ort fail?

**Comment by AllenTiTaiWang** [comment]
> Why no_runtime, does ort fail?

Good point, and moved. 

=> In the original issue, that was an exporter issue, and didn't even hit ORT, and I thought 0d output might break verification (thank God it's not). Though I checked the prediction result, I didn't put it in runtime.

**Comment by AllenTiTaiWang** [comment]
@BowenBao PTAL

**Review by BowenBao — APPROVED** [review]

**Pull request closed without merging**
