### PR TITLE
Add release matrix for 2.5

### PR DESCRIPTION
**Pull request by kit1980**

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
Just curious, now that 12.4 is marked as stable, do you know when 11.8 is going away?

**Comment by kit1980** [comment]
> Just curious, now that 12.4 is marked as stable, do you know when 11.8 is going away?

In 2.6 release CUDA 11.8 will go away, and and that time we also update NCCL (we can not update it now as we want CUDA 11.8).

**Pull request closed without merging**
