### PR TITLE
Use OrderedSet in ufunc codegen

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #82567

Follow up from https://github.com/pytorch/pytorch/pull/82536#discussion_r934000916

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
don't forget to add typing

**Comment by peterbell10** [comment]
Am I doing something wrong with `lintrunner`? I've tried `lintrunner`, `lintrunner torchgen/utils.py` `lintrunner -m upstream/master` and none of them showed any failures yet the `lintrunner` in CI fails instantly.

**Comment by ezyang** [comment]
one common problem is you need to `lintrunner init`

**Comment by peterbell10** [comment]
Using `lintrunner -vv` I noticed lintrunner isn't actually setup to run mypy on the `torchgen` folder:
https://github.com/pytorch/pytorch/blob/d08157d5168015c3de0a6d182d08a77a38e5c207/.lintrunner.toml#L82-L98

I don't understand how it runs in CI though?

**Comment by peterbell10** [comment]
Ah your right, when I try `lintrunner --all-files` it does pick up the failures.

**Pull request closed without merging**
