### PR TITLE
[DataLoader] Select available CUDA or 3rd devices automatically to pin memory

### LINKED ISSUE #124908: DataLoader's pin_memory is default to CUDA if parameter pin_memory_device is not set
### 🚀 The feature, motivation and pitch

Currently, when using pin memory in DataLoader, the default behaviour is CUDA device if `pin_memory_device` is not set(see [dataloader.py#L587](https://github.com/pytorch/pytorch/blob/main/torch/utils/data/dataloader.py#L587) ), which is kind of CUDA-centric. A special scenario is that you want to use pin memory(thus `pin_memory` is set as True) but forget to set `pin_memory_device`, in which case the pin memory behaviour only takes effect when CUDA is available. And pin memory would be switched to False when CUDA is unavailable even if other devices are available! You might think pin memory is set successfully but actually not, and no warning are throw.

I believe this case exists, cause `pin_memory_device` isn't in old API's parameters. And some users may be used to doing this.

cc @SsnL @VitalyFedyunin @ejguan @dzhulgakov @ssnl @NivekT @ezyang  

### Alternatives

A reasonable solution is that when `pin_memory` is True, check whether CUDA is available first. And if not, get privateuse1 backend automatically to pin memory to. Otherwise, throw some warnings that pin memory doesn't take effect.

And I can pull a PR to follow up if above is acceptable.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wizzniu**
This PR improves the behavior for DataLoader when ``pin_memory`` is ``True`` and ``pin_memory_device`` is not set. Instead of only checking whether CUDA is available or not, a more reasonable approach is that first check available CUDA device, and if not, get privateuse1 backend automatically to pin memory to. Otherwise, throw some warnings that pin memory doesn't take effect.

Fixes #124908 

cc @ssnl @VitalyFedyunin @ejguan @dzhulgakov @ezyang

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Would it be better to explicitly accept a `pin_memory_device` to a DataLoader constructor? and fix things light PyTorch Lightning / HF Trainer to pass it in (instead of mixing in the data loader device detection)?

**Comment by wizzniu** [comment]
> Would it be better to explicitly accept a `pin_memory_device` to a DataLoader constructor? and fix things light PyTorch Lightning / HF Trainer to pass it in (instead of mixing in the data loader device detection)?

This PR maintains BC in the parameters `pin_memory` and `pin_memory_device` of API. You still can explicitly pass in a `pin_memory_device` to it.

**Comment by wizzniu** [comment]
@ezyang @albanD @ejguan Can you help to review this PR?

**Comment by ezyang** [comment]
I'm deferring to @albanD for custom backend stuff

**Comment by wizzniu** [comment]
> I'm deferring to @albanD for custom backend stuff

Thanks for your reply. Could you give some suggestions, @albanD ?

**Comment by albanD** [comment]
Yes sorry, I wanted to give a longer answer on this but here is the short version:
- We do not want for every API that takes pin_memory: bool flag to grow a pin_memory_device argument.
- We want to use the newly introduced concept of accelerator at https://github.com/pytorch/pytorch/blob/196a0b1722d9e6c77e6e999b59c169551749c3cb/aten/src/ATen/DeviceAccelerator.h#L25 to redefine pin memory as: "Pin memory is always pinned for the current accelerator device".
- This will allow us to have all the other factory function APIs work without the need for new arguments.

What it means for this PR is a bit more subtle:
- Long term, we most likely just want to drop the pin_memory_device argument altogether
- This will require updating the implementation of the pin memory concept for low level APIs
- If you have time, it would be best to fix the low level constructs directly. If you do not, I'm happy to have a quick fix here that consists of binding the "getAccelerator()" API to python and use that here to set the default value of pin_memory_device. This is not perfect but a step in the direction where we want to go.

WDYT?

**Comment by mengpenghui** [comment]
@albanD 
I am working on IPC-related interfaces to support third-party devices. The suggestions you gave in this PR are very helpful for modifying IPC. Now I have a new plan:
1. The share_cuda_ interface is changed to share_device_
2. The backend uses getAccelerator to determine the device and distribute different devices.
3. Add the share_device implementation of third-party devices to PrivateUse1HooksInterface

I plan to modify the new solution on this PR: https://github.com/pytorch/pytorch/pull/125122
Do you think this is feasible? Looking forward to your reply.

**Comment by wizzniu** [comment]
> Yes sorry, I wanted to give a longer answer on this but here is the short version:
> 
> * We do not want for every API that takes pin_memory: bool flag to grow a pin_memory_device argument.
> * We want to use the newly introduced concept of accelerator at https://github.com/pytorch/pytorch/blob/196a0b1722d9e6c77e6e999b59c169551749c3cb/aten/src/ATen/DeviceAccelerator.h#L25
>    to redefine pin memory as: "Pin memory is always pinned for the current accelerator device".
> * This will allow us to have all the other factory function APIs work without the need for new arguments.
> 
> What it means for this PR is a bit more subtle:
> 
> * Long term, we most likely just want to drop the pin_memory_device argument altogether
> * This will require updating the implementation of the pin memory concept for low level APIs
> * If you have time, it would be best to fix the low level constructs directly. If you do not, I'm happy to have a quick fix here that consists of binding the "getAccelerator()" API to python and use that here to set the default value of pin_memory_device. This is not perfect but a step in the direction where we want to go.
> 
> WDYT?

I agree with you that additional `device` argument is unnecessary when using pin_memory related APIs, which requires updating the implementation of the pin memory concept for low level APIs. And I am happy to fix the low level constructs directly. 
So here I want to confirm whether our goal is to get rid of `device` argument of all pin_memory related APIs(e.g. `Tensor.pin_memory()`)? And if it is, I will take time to work on this.

**Comment by albanD** [comment]
> So here I want to confirm whether our goal is to get rid of device argument of all pin_memory related APIs(e.g. Tensor.pin_memory())?

Yes! But also note that most of these APIs do NOT have a device argument today. So not much to remove for most of them haha
The main thing is that we want to enable any accelerator pinned memory but we don't want to introduce this device argument everywhere. So changing the low level constructs to leverage the Accelerator concept is the way to go.
Let me know if you think this needs more clarification!

**Comment by wizzniu** [comment]
@albanD hi, I have updated the implement of pin memory in a new PR, please see https://github.com/pytorch/pytorch/pull/126376

**Pull request closed without merging**
