### PR TITLE
Renaming CAFFE2_API to TORCH_API

### PR DESCRIPTION
**Pull request by janeyx99**
Since caffe2 and torch have been consolidated, CAFFE2_API should be merged with TORCH_API. Addresses a TODO.

Manually edited some references of the removed `CAFFE2_API`:
* `CONTRIBUTING.md`
* `caffe2/proto/CMakeLists.txt`
* `cmake/ProtoBuf.cmake`
* `c10/macros/Export.h`
* `torch/csrc/WindowsTorchApiMacro.h`

### CODE REVIEW

**Comment by samestep** [comment]
Impressive... in the PR description, could you list which files were manually edited (as opposed to an automatic search-and-replace)? For instance, I see that `CONTRIBUTING.md` seems to have manual edits

**Comment by walterddr** [comment]
> Impressive... in the PR description, could you list which files were manually edited (as opposed to an automatic search-and-replace)? For instance, I see that `CONTRIBUTING.md` seems to have manual edits

+1. This could iterative multiple times due to build test failures. Good to keep track on every commit

**Review by samestep — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by janeyx99** [comment]
abandoning this PR as I'll be pushing one out internally with the same contents (and not the error I accidentally pushed onto this one)

**Comment by janeyx99** [comment]
Whoops I didn't realize it'd export to the same PR 😅

**Pull request closed without merging**
