### PR TITLE
[FSDP] Return original module when fsdp wrapped model call .module

### LINKED ISSUE #78607: Return original module when fsdp wrapped model call .module
### 🚀 The feature, motivation and pitch

Right now if users want to access the original module from a fsdp wrapped model, users need to call it like this "fsdp_model.module.module".
To be consistent with the ddp wrapped model, change FSDP codes to return the original module by calling "fsdp_model.module".

### Alternatives

_No response_

### Additional context

_No response_

cc @zhaojuanmao @mrshenli @rohan-varma

### PR DESCRIPTION
**Pull request by LinjianMa**
Fixes #78607

### CODE REVIEW

**Review by awgu — APPROVED** [review]
Thanks for the quick PR! It looks like all the CI tests are passing, so all of the necessary occurrences of `.module` have been replaced with `._fsdp_wrapped_module`.

I also want to mention that I personally like this change:
- For FSDP developers: `self._fsdp_wrapped_module.flat_param` is clearer than `self.module.flat_param` since the flattened parameter is logically associated with the `FlattenParamsWrapper` and not the original module itself. 
- For users: `fsdp_model.module` now accesses the original module, which is intuitive.

**Review by rohan-varma — APPROVED** [review]
Nice work!

**Pull request closed without merging**
