### PR TITLE
[CUDA] [CI]: Enable CUDA 12.4 CI

### PR DESCRIPTION
**Pull request by nWEIdia**
Reference PR: https://github.com/pytorch/pytorch/pull/93406

cc @atalman @malfet @ptrblck @eqy

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
Hmm, I think it needs some discussion, because if we are to stop building/testing CUDA-11.8, it means we are loosing Keplers, don't we?
@atalman is there a doc whether this is intended

**Comment by johnnynunez** [comment]
> Hmm, I think it needs some discussion, because if we are to stop building/testing CUDA-11.8, it means we are loosing Keplers, don't we? @atalman is there a doc whether this is intended

why not mantain 11.8 as cuda 11 and 12.4 as cuda 12? And skip 12.1

**Comment by nWEIdia** [comment]
We discussed for a short term, we would have 11.8, 12.1, and 12.4. I will need to refactor this PR to add back 11.8.

**Comment by johnnynunez** [comment]
when will be merged? 😋

**Comment by nWEIdia** [comment]
12.4 workflows are failing. Still working on coming up with a fix.

**Comment by johnnynunez** [comment]
12.4 update is out:
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/

**Comment by johnnynunez** [comment]
@ptrblck @nWEIdia nvidia cudnn9 now is available nvidia-cudnn-cu12 9.0.0.312
https://pypi.org/project/nvidia-cudnn-cu12/

**Comment by ptrblck** [comment]
@johnnynunez Yes, it is! We will focus on 12.4 in this PR and follow up with the cuDNN update separately to avoid creating confusing issues pointing to the CUDA *and* cuDNN update.

**Comment by atalman** [comment]
@nWEIdia some errors on the PR, are due to missing docker image. We need to add new docker image build here:
https://github.com/pytorch/pytorch/blob/main/.github/workflows/docker-builds.yml
Similar to this PR: https://github.com/pytorch/pytorch/pull/98832

Please post new PR for building new Docker images.

**Comment by nWEIdia** [comment]
@malfet Could you please help take another look? 
I am composing torchinductor 12.4 issues in [here](https://github.com/pytorch/pytorch/issues/126692). 
Thanks!

**Comment by atalman** [comment]
Hi @nWEIdia  please disable the failing tests. We will follow up on this in the issue you opened

**Review by atalman — APPROVED** [review]

**Pull request closed without merging**
