### PR TITLE
Add numerically stable BCELoss which takes logits as input

### PR DESCRIPTION
**Pull request by alykhantejani**
Add numerically stable BCELoss which takes logits as input and combines the `sigmoid` and `BCELoss` in one layer. This is in response to issue #751

### CODE REVIEW

**Comment by alykhantejani** [comment]
broken test - fixing now

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
thanks man!

**Comment by esube** [comment]
@alykhantejani @soumith 
I just saw this commit. Thanks for implementing this tf like BCE with logits!

I noticed that the function repeats the weight vector to match target if it is provided. However, when the weight vector is the same shape as the target vector to begin with (as is the case in multi-label classification), the check line fails as it tries to expand the weight vector. So, it would be nice to check if the weight is already the same shape as the target before trying to expand it. This will solve some issues related to mult-label sample by sample weighting rather than class-based weighting.

**Comment by alykhantejani** [comment]
@esube can you provide an example of the failure case (in code)?

This worked fine for me:
```python
output = torch.autograd.Variable(torch.Tensor(2, 10).uniform_())
target = torch.autograd.Variable(torch.Tensor(2, 10).uniform_())
weigth = torch.Tensor(10).uniform_()
loss_fn = nn.BCEWithLogitsLoss(weight)
loss = loss_fn(output, target)
```

**Comment by esube** [comment]
@alykhantejani 
The following:
`
output = torch.autograd.Variable(torch.Tensor(2, 10).uniform_())
target = torch.autograd.Variable(torch.Tensor(2, 10).uniform_())
weight = torch.Tensor(2,10).uniform_()
loss_fn = nn.BCEWithLogitsLoss(weight)
loss = loss_fn(output, target)
`

fails with error code:

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "python2.7/site-packages/torch/nn/modules/loss.py", line 232, in forward
    return F.binary_cross_entropy_with_logits(input, target, Variable(self.weight), self.size_average)
  File "python2.7/site-packages/torch/nn/functional.py", line 659, in binary_cross_entropy_with_logits
    weight = weight.view(1, target.size(1)).expand_as(target)
  File "python2.7/site-packages/torch/autograd/variable.py", line 479, in view
    return View.apply(self, sizes)
  File "python2.7/site-packages/torch/autograd/_functions/tensor.py", line 96, in forward
    result = i.view(*sizes)
RuntimeError: size '[1 x 10]' is invalid for input of with 20 elements at pytorch/torch/lib/TH/THStorage.c:41
`

**Comment by alykhantejani** [comment]
@esube Ah ok, gotcha. ok I can add support for this. Out of interest, how are you currently doing this with the normal `BCELoss` + `Sigmoid`?

**Comment by esube** [comment]
Sorry for the edited response above. I have changed the class and the function so that the forward accepts three inputs as I described above and I have it working locally. It would be nice to have this either in your PR as correction or on a separate PR if you think it is completely different. 

```python
class WBCELoss(nn.Module):
    def __init__(self, size_average=True):
        super(WBCELoss, self).__init__()
        self.size_average = size_average

    def forward(self, input, target, weight=None):
        return binary_cross_entropy_with_logits(input, target, weight, self.size_average)
```

```python
def binary_cross_entropy_with_logits(input, target, weight=None, size_average=True):
   
    if weight is not None and weight.dim() != target.dim() and target.dim() != 1:
        weight = weight.view(1, target.size(1)).expand_as(target)

    neg_abs = - input.abs()
    loss = input.clamp(min=0) - input * target + (1 + neg_abs.exp()).log()

    if weight is not None:
        weight = weight.float()
        loss = loss * weight

    if size_average:
        return loss.mean()
    else:
        return loss.sum()
```
Note: this expects the dataset loader to supply a minibatch of input, target and weight tensors to the loss function.

**Comment by alykhantejani** [comment]
Should be fairly easy to amend the `binary_cross_entropy_with_logits` to do this (I can do this tomorrow). I was just curious how you achieve this behaviour with the old `BCELoss` + `Sigmoid` (not the new `BCELossWithLogits`), because that too does the same resize, see here: https://github.com/pytorch/pytorch/blob/master/torch/nn/_functions/thnn/loss.py#L15

**Comment by esube** [comment]
@alykhantejani Thanks for updating it to accommodate this. I had to do these modifications with the regular `BCELoss + Sigmoid` as well. In short most losses are written without multi-label weighting in mind.

**Comment by esube** [comment]
@alykhantejani any updates on this?

**Comment by alykhantejani** [comment]
@esube sorry - didn't get a chance to get to it. 
I'm happy to send a PR to add this for both `BCELoss` and `BCEWithLogitsLoss` if this is something we want to support @soumith?

**Comment by alykhantejani** [comment]
@esube sorry for the delay on this. Now that we have broadcasting, this is really easy to do. I will send a PR today/tomorrow for this. 

cc @fmassa - just to confirm this is as easy as I think it is now with broadcasting?

**Comment by fmassa** [comment]
@alykhantejani yes, as we discussed offline, I think removing the `weight` viewing/expansion will be enough, and let the broadcasting do the work for us.
Note that we could possibly do the same thing for `bce_loss`, but we would need to use some internal functions to perform the broadcasting (as the tensors are used in a C function)

**Comment by alykhantejani** [comment]
@fmassa sounds good - will add it for `bce_loss` too

**Comment by fmassa** [comment]
@alykhantejani about the internal function to perform the broadcasting, you can use [`_infer_size`](https://github.com/pytorch/pytorch/blob/master/torch/functional.py#L214) from python. I think this is the easiest route.

**Comment by Jiaming-Liu** [comment]
The result seems to be wrong when logit = 0.0 and target = 0.

**Comment by alykhantejani** [comment]
@Jiaming-Liu Thanks for the bug report - this indeed looks wrong. Taking a look now

**Comment by alykhantejani** [comment]
@Jiaming-Liu ok I found the issue, its because in PyTorch the gradient of `abs` is `0` at `0`. I will push a patch for this today, re-formulating this to not use `abs`. Thanks for reporting!

**Comment by alykhantejani** [comment]
@Jiaming-Liu this should be fixed in https://github.com/pytorch/pytorch/pull/2195

**Comment by F0REacH** [comment]
@alykhantejani Fix from #2195 gives some unexpected behavior:
`
input, target = torch.Tensor([-100.0]), torch.Tensor([0])
print(F.binary_cross_entropy(torch.sigmoid(input), torch.Tensor(target)))
`
>Variable containing:
1.00000e-12 *
 -1.0001
[torch.FloatTensor of size 1]



`
print(F.binary_cross_entropy_with_logits(input, torch.Tensor(target)))
`
> inf

`
neg_abs = - input.abs()
loss = input.clamp(min=0) - input * target + (1 + neg_abs.exp()).log()
print(loss)
`
> 0
[torch.FloatTensor of size 1]

**Comment by Jiaming-Liu** [comment]
https://github.com/Jiaming-Liu/pytorch-misc/blob/master/sigmoid_with_binary_cross_entropy.py

This might be helpful for debugging the loss.

**Comment by Jiaming-Liu** [comment]
https://github.com/Jiaming-Liu/pytorch-misc/blob/master/test_binary_cross_entropy.ipynb

This might be helpful for debugging the loss.

**Comment by alykhantejani** [comment]
@F0REacH thanks for reporting. This is a subtle bug that only occurs with large values that cause the `exp` to overflow. It's a very easy fix, but I will also add a test, because this is just a plain bug. Sending a PR in a min.

**Comment by alykhantejani** [comment]
@Jiaming-Liu Thanks. I found the issue, I forgot to do `(-input).clamp(min=0)` i.e. I forgot the `-` sign. 

This only shows a error when exp(x) overflows, and the tests were run with DoubleTensors so this didn't happen. Sending a PR now

**Pull request merged**
