### PR TITLE
Properly detect nested torch function args

### LINKED ISSUE #127174: dynamo doesn't support `__torch_function__` on non-tensor classes
### 🐛 Describe the bug

Extending pytorch with tensor-like classes isn't supported by Dynamo. Additionally, the error message is not very informative for users who don't know much about dynamo.

(I guess this is known and on someone's roadmap, I'm opening an issue to keep track of this for tensordict integration)

To reproduce:
```python
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
import functools
from typing import Callable, Any

import torch

HANDLED_FUNCTIONS = {}

class MyClass:
    def __init__(self, foo):
        self.foo = foo

    @classmethod
    def __torch_function__(
        cls,
        func: Callable,
        types: tuple[type, ...],
        args: tuple[Any, ...] = (),
        kwargs: dict[str, Any] | None = None,
    ) -> Callable:

        if kwargs is None:
            kwargs = {}
        if func not in HANDLED_FUNCTIONS or not all(
            issubclass(t, (torch.Tensor, MyClass)) for t in types
        ):
            return NotImplemented
        return HANDLED_FUNCTIONS[func](*args, **kwargs)

    def __repr__(self):
        return "MyClass({})".format(self.foo)

def implements_for(torch_function: Callable) -> Callable[[Callable], Callable]:
    """Register a torch function override for TensorDict."""

    @functools.wraps(torch_function)
    def decorator(func: Callable) -> Callable:
        HANDLED_FUNCTIONS[torch_function] = func
        return func

    return decorator


@implements_for(torch.stack)
def _stack(input, dim=0, *, out=None):
    return MyClass(sum([x.foo for x in input]))

v0 = MyClass(1)
v1 = MyClass(1)
print(torch.stack([v0, v1]))

@torch.compile(fullgraph=True)
def func(v0, v1):
    return torch.stack([v0, v1])

print(func(v0, v1))
```
The last call fails with 
```
  File "/Users/vmoens/venv/rl/lib/python3.11/site-packages/torch/_dynamo/variables/base.py", line 253, in as_proxy
    raise NotImplementedError(str(self))
NotImplementedError: UserDefinedObjectVariable(MyClass)

[...]
  File "/Users/vmoens/venv/rl/lib/python3.11/site-packages/torch/_dynamo/exc.py", line 215, in unimplemented
    raise Unsupported(msg) from from_exc
torch._dynamo.exc.Unsupported: call_function args: ListVariable(length=2) 

from user code:
   File "/Users/vmoens/Library/Application Support/JetBrains/PyCharm2023.3/scratches/compile_mini_errors.py", line 57, in func
    return torch.stack([v0, v1])

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

### Versions

nightly

cc @hameerabbasi @rgommers @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @zou3519

### PR DESCRIPTION
**Pull request by mlazos**
Dynamo was not detecting nested torch function classes in containers. This was due to pytree compatibility for variable trackers being removed.
Fixes https://github.com/pytorch/pytorch/issues/127174

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]

**Review by vmoens — COMMENTED** [review]
Thanks @mlazos!
There are still a bunch of tests failing though

**Comment by mlazos** [comment]
> Thanks @mlazos! There are still a bunch of tests failing though

Yeah, these look like they're a result of changing the arg ordering a bit to torch ops. Fixing now.

**Pull request closed without merging**
