### PR TITLE
Solve bug of DistributedDataParallel

### PR DESCRIPTION
**Pull request by unlimblue**
Fixed bug [https://github.com/facebookresearch/maskrcnn-benchmark/issues/52](https://github.com/facebookresearch/maskrcnn-benchmark/issues/52)

### CODE REVIEW

**Comment by pietern** [comment]
@unlimblue Thanks for the fix!

We have existing tests for the distributed package in `test_distributed.py`. Please integrate this test in that file. No need for spawning processes since that's all taken care of there. You can look at the existing distributed data parallel tests for an example how to use them.

**Comment by teng-li** [comment]
Thanks for the fix, please also add this test to test_distributed_thd as well now that we haven't fully removed the old `torch.distributed` yet.

**Comment by unlimblue** [comment]
The tests haven't finished, but I think the DistributedDataParallelCPU also have some bugs on this test case.

**Comment by unlimblue** [comment]
I think there is a lot of work to do of the test code at this test case. Before it test my code, there are some other errors occur. I need more time to fix them.

**Comment by unlimblue** [comment]
I think the final commit will pass all of the tests.

**Comment by teng-li** [comment]
@unlimblue Taking a closer look at the change you applied, I am not sure why this would a real "fix" instead of a workaround to make the DDP code check less things to bypass this check.

Can you explain why you would like each bucket map to store the size, which is supposed to be the index itself.

**Comment by teng-li** [comment]
@unlimblue  Actually, never mind, I read the other post.

**Pull request closed without merging**
