### PR TITLE
Add sanity checks for NCCL detection.

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#22819 Add sanity checks for NCCL detection.**
* #22818 Let CMake handle NCCL detection instead of our handcrafted Python script.

Check whether NCCL header files and libraries have the same NCCL version number.

Differential Revision: [D16283037](https://our.internmc.facebook.com/intern/diff/D16283037)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Thank you, this is lovely.

**Comment by yf225** [comment]
This is breaking master CUDA builds with 
```
Jul 16 20:03:50 CMake Error at /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Jul 16 20:03:50   Could NOT find NCCL (missing: NCCL_INCLUDE_DIRS NCCL_LIBRARIES)
```
I am reverting it.

**Comment by xuhdev** [comment]
I think this should be merged only after #22818 is merged.

**Comment by xuhdev** [comment]
It looks like the issue is actually caused by  #22818 not this one, but the CI in #22818 shows that it did not cause this issue. What could have changed in between?

**Pull request closed without merging**
