### PR TITLE
Add RpcAgent::getWorkerInfos()

### PR DESCRIPTION
**Pull request by xush6528**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#30241 Add RpcAgent::getWorkerInfos()**

We need an API to get all worker names. This will be used by backend-agnostic `rpc.wait_all_workers()` API.

Differential Revision: [D5693412](https://our.internmc.facebook.com/intern/diff/D5693412/)

### CODE REVIEW

**Comment by zhaojuanmao** [comment]
why not just use getAllWorkInfo()? they look duplicated in some way

**Comment by xush6528** [comment]
@zhaojuanmao I didn't see `getAllWorkInfo()` available, there is only `getWorkerInfo(..)`.

**Comment by zhaojuanmao** [comment]
@xush6528 Oh I see, then that is good to add one

**Comment by satgera** [comment]
> @zhaojuanmao I didn't see `getAllWorkInfo()` available, there is only `getWorkerInfo(..)`.

Yes I its better to add getAllWorkerInfo instead of names.

**Comment by xush6528** [comment]
@satgera Updated to `::getWorkerInfos()`

**Review by satgera — APPROVED** [review]
Please wait for the tests to pass.

**Pull request closed without merging**
