### PR TITLE
refactor multi_head_attention_forward

### PR DESCRIPTION
**Pull request by bhosmer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#56674 refactor multi_head_attention_forward**

`torch.nn.functional.multi_head_attention_forward` supports a long tail of options and variations of the multihead attention computation. Its complexity is mostly due to arbitrating among options, preparing values in multiple ways, and so on - the attention computation itself is a small fraction of the implementation logic, which is relatively simple but can be hard to pick out.

The goal of this PR is to 
- make the internal logic of `multi_head_attention_forward` less entangled and more readable, with the attention computation steps easily discernible from their surroundings.
- factor out simple helpers to perform the actual attention steps, with the aim of making them available to other attention-computing contexts.

Note that these changes should leave the signature and output of `multi_head_attention_forward` completely unchanged, so not BC-breaking. Later PRs should present new multihead attention entry points, but deprecating this one is out of scope for now.

Changes are in two parts: 
- the implementation of `multi_head_attention_forward` has been extensively resequenced, which makes the rewrite look more total than it actually is. Changes to argument-processing logic are largely confined to a) minor perf tweaks/control flow tightening, b) error message improvements, and c) argument prep changes due to helper function factoring (e.g. merging `key_padding_mask` with `attn_mask` rather than applying them separately)
- factored helper functions are defined just above `multi_head_attention_forward`, with names prefixed with `_`. (A future PR may pair them with corresponding modules, but for now they're private.)

Differential Revision: [D28344707](https://our.internmc.facebook.com/intern/diff/D28344707)

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]
Tremendous

**Review by jbschlosser — APPROVED** [review]
Really awesome work! Thanks for tackling this :)

One minor thing: it seems the C++ / python parity tests are not currently validating implementation parity for MHA (see https://github.com/pytorch/pytorch/blob/master/test/cpp_api_parity/parity-tracker.md). Not sure why this is, but it would be good to get some extra verification of the refactoring by validating against the (transliterated) C++ implementation.

That said, it looks like the functional MHA tests in `test/test_nn.py` compare against a reference for a pretty solid set of cases, so I'm fairly confident that if those tests pass, we can assume functional equivalence.

Stamping now; feel free to land while I'm out!

**Comment by bhosmer** [comment]
@bhosmer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28344707).

**Comment by bhosmer** [comment]
Thanks for reviewing Joel!

> One minor thing: it seems the C++ / python parity tests are not currently validating implementation parity for MHA (see [`master`/test/cpp_api_parity/parity-tracker.md](https://github.com/pytorch/pytorch/blob/master/test/cpp_api_parity/parity-tracker.md)). Not sure why this is, but it would be good to get some extra verification of the refactoring by validating against the (transliterated) C++ implementation.
> 
> That said, it looks like the functional MHA tests in `test/test_nn.py` compare against a reference for a pretty solid set of cases, so I'm fairly confident that if those tests pass, we can assume functional equivalence.

I agree, it would be nice have (or reenable?) a test that explicitly checks equality between the results of the python implementation and the C++ port. In the meantime, I *think* the [reference on the C++ side](https://github.com/pytorch/pytorch/blob/master/test/cpp/api/modules.cpp#L3584) mimics [the one on the Python side](https://github.com/pytorch/pytorch/blob/master/test/test_nn.py#L4145), both of which pass - Python with the new code, C++ with the old - giving us a de facto equality check. Maybe the right time to do the explicit one is when the C++ version is updated with these changes.

**Pull request closed without merging**
