### PR TITLE
Optim foreach cleanup for Rmsprop

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70953
* #70484
* #70483
* __->__ #70482
* #70481
* #70295

Add foreach flag to RMSProp

Differential Revision: [D33767862](https://our.internmc.facebook.com/intern/diff/D33767862)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
LGTM

**Comment by mikaylagawarecki** [comment]
@mikaylagawarecki has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33767862).

**Comment by mikaylagawarecki** [comment]
@mikaylagawarecki has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33767862).

**Comment by mikaylagawarecki** [comment]
@mikaylagawarecki has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33767862).

**Pull request closed without merging**
