### PR TITLE
[pytorch][PR] Add ability for a mobile::Module to save as flatbuffer

### PR DESCRIPTION
**Pull request by qihqi**
Summary:
Included functions:

save_mobile_module -> saves a mobile::Module to flatbuffer
load_mobile_module_from_file -> loads a flatbuffer into mobile::Module
parse_mobile_module -> parses from bytes or deserialized flatbuffer
Module object

Test Plan: unittests

Differential Revision: D32806835

### CODE REVIEW

**Comment by qihqi** [comment]
linux-bionic-cuda10.2-py3.9-gcc7 / test gives
2021-12-03T23:14:11.5642476Z build/bin/test_api: error while loading shared libraries: libtorch_cpu.so: cannot open shared object file: No such file or directory

seems unrelated...

**Review by gmagogsfm — APPROVED** [review]

**Pull request closed without merging**
