### PR TITLE
Add missing -inf order for linalg.norm OpInfo

### PR DESCRIPTION
**Pull request by kurtamohler**
Follow up to #50746

I accidentally missed the `ord=-inf` case in the OpInfo for `torch.linalg.norm` when I wrote it.

### CODE REVIEW

**Comment by imaginary-person** [comment]
Hello @kurtamohler, thanks for your advice regarding writing an OpInfo!

BTW, I tried implementing `pow()` on CPU for `Float16` & `BFloat16` via #50999,
but `test_variant_consistency_jit_linalg_norm_cpu_float16` &  `test_variant_consistency_jit_linalg_norm_cpu_bfloat16` failed. However, both of them pass on CUDA. Also, their `eager` counterparts pass on both CPU & CUDA.

I added the changes made in this PR locally, but those tests are still failing with the same cause:
https://github.com/pytorch/pytorch/blob/1f40f2a1723fd3b9302bea3829f2570c8e0e7e94/torch/testing/_internal/common_jit.py#L108

Please let me know if you have any advice on how I can verify if the failure is due to an erroneous implementation of `pow()` for CPU. The test is a black-box for me right now. Thank you!

**Review by anjali411 — APPROVED** [review]
@kurtamohler good catch and thanks for the follow up! LGTM

**Comment by kurtamohler** [comment]
Hey @imaginary-person, I'll reply to your question in your PR

**Comment by anjali411** [comment]
@kurtamohler can you please rebase?

**Pull request closed without merging**
