### PR TITLE
Add RISC-V CI support

### PR DESCRIPTION
**Pull request by jysh1214**
cc @seemethere @malfet @pytorch/pytorch-dev-infra

### CODE REVIEW

**Comment by cpuhrsch** [comment]
I think we'd want to first see an issue opened that discusses this. Is there a relevant issue for this?

**Review by malfet — CHANGES_REQUESTED** [review]
This PR builds around the premise that `runs-on: linux.riscv64` is available. Can you please point to either GitHub or AWS EC2 runner that meets those requirements?

**Comment by seemethere** [comment]
Based on the conversation in https://github.com/actions/runner/issues/2157 I have reason to believe that this is would be a non-trivial task on enabling this.

Appreciate the PR but unfortunately doesn't seem like RISC-V support across the ecosystem is ready yet to support PyTorch being built for it in CI.

**Comment by jysh1214** [comment]
I have initiated a discussion on this topic.
https://github.com/pytorch/pytorch/issues/141550

**Pull request closed without merging**
