### PR TITLE
[jit] math module support: gcd, copysign, erf, erfc, expm1, fabs, gamma, lgamma

### PR DESCRIPTION
**Pull request by eugenekoran**
@eellison @driazati Refer to issue #19026

### CODE REVIEW

**Comment by eugenekoran** [comment]
Ok, I see tests fail in python 2 because there is no gcd method in math module. 

Seems like `_builtin_table` is used for generating documentation only. I am not sure how to find a work-around for it.
```
16:28:12 + python -c 'import torch; print(torch.__config__.show())'
16:28:21 Traceback (most recent call last):
16:28:21   File "<string>", line 1, in <module>
16:28:21   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/torch/__init__.py", line 291, in <module>
16:28:21     import torch.jit
16:28:21   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/torch/jit/__init__.py", line 1762, in <module>
16:28:21     _register_builtin(len, 'aten::len')
16:28:21   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/torch/jit/__init__.py", line 1755, in _register_builtin
16:28:21     _get_builtin_table()[id(fn)] = op
16:28:21   File "/var/lib/jenkins/.local/lib/python2.7/site-packages/torch/jit/__init__.py", line 1732, in _get_builtin_table
16:28:21     _builtin_table[id(math.gcd)] = "aten::gcd"
16:28:21 AttributeError: 'module' object has no attribute 'gcd'
```

**Comment by eellison** [comment]
@eugenekoran you can guard `math.gcd` with a `if not PY2` check

**Comment by eugenekoran** [comment]
@eellison Would you mind taking a look?

**Review by eellison — APPROVED** [review]
Looks great thanks for doing this! 

I added a couple comments to the tests, but they're nits since it's test code

**Comment by eellison** [comment]
Looks like you have a lint failure: 
`./test/test_jit.py:5860:100: E241 multiple spaces after ','`

This one's pretty easy to fix. For future reference: https://github.com/pytorch/pytorch/wiki/Lint-as-you-type

**Review by driazati — APPROVED** [review]

**Pull request closed without merging**
