### PR TITLE
Add SmallVector from llvm

### PR DESCRIPTION
**Pull request by colesbury**
Adds at::SmallVector and supporting AlignOf class to ATen from LLVM.

http://llvm.org/doxygen/SmallVector_8h_source.html

### CODE REVIEW

**Comment by apaszke** [comment]
What's the plan for `SmallVector`? Where do you want to use it?

**Comment by cpuhrsch** [comment]
@apaszke one example would be storing sizes, counters and strides for the cpu apply utils with std::vector semantics.

**Comment by colesbury** [comment]
I'd like to replace the uses of `std::vector<int64_t>` for storing sizes and strides, particularly in performance critical pieces of code. I think it'll eventually be useful for the actual tensor implementation. More immediately, it'll be useful for @cpuhrsch's work on the apply macros and for saving tensors sizes in autograd for backwards.

I'm thinking of defining an alias in ATen like:

```
using ShapeVec = SmallVector<int64_t, 6>;
```

Where `6` is chosen because I thin the vast majority of tensors have six or fewer dimensions. Things like at::infer_size would become:

```
AT_API ShapeVec infer_size(IntList a, IntList b);
```

**Comment by apaszke** [comment]
@cpuhrsch true, that's a reasonable case, although I think that the fastest way would be to depend on `alloca`, which should be relatively safe to use in this case.

I'm just asking because last summer I actually wrote and evaluated a patch that replaced the critical places that depend on `std::vector` in autograd with a `SmallVector`-like struct, and found that there was no significant difference on the workloads I tested. It's possible that the allocator overhead gets replaced by an additional cost of copying memory because the objects are generally larger.

**Comment by cpuhrsch** [comment]
@apaszke even if this ends up being true, given the speed difference you can see in a place like apply utils, I think it's worth the time to look into it again. Maybe it'll be different in this case.

**Review by zdevito — APPROVED** [review]
It makes sense to add SmallVector, especially for these intermediates in the CPU utilities. Furthermore, once Tensor size gets really small, the number of allocations to make a new tensor dominates runtime and having small vector will eventually allow us to replace sizes/strides with it.

**Comment by apaszke** [comment]
Just to be clear, I don't have any issues with merging this. I was asking because I was curious if we've actually seen any benefits so far (great to hear that we have in apply code!).

**Comment by colesbury** [comment]
It's saves about 50ns compared to std::vector<int64_t> for sizes that can be stored inline.

**Comment by ezyang** [comment]
@cpuhrsch ignore me on that other PR, we've already merged this haha.

@smessmer Let's make sure we use this one when in C10

**Pull request merged**
