### PR TITLE
CUDA BFloat16 i0 support

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Test error is real

**Comment by zasdfgbnm** [comment]
@ngimel Yeah, I actually need https://github.com/pytorch/pytorch/pull/44748 so that the test for `ne` does not `assertRaise`

**Comment by zasdfgbnm** [comment]
Rebased, should be working

**Comment by zasdfgbnm** [comment]
ROCm failure is unrelated:

```
19:18:41 test_conv_transposed_large_cpu (__main__.TestNNDeviceTypeCPU) ... Traceback (most recent call last):
19:19:13   File "test/run_test.py", line 741, in <module>
19:19:13     main()
19:19:13   File "test/run_test.py", line 724, in main
19:19:13     raise RuntimeError(err_message)
19:19:13 RuntimeError: test_nn failed! Received signal: SIGBUS
```

**Pull request closed without merging**
