### PR TITLE
[Ready] Limit docs line length

### LINKED ISSUE #1883: Limit docstring length
Some docstrings are too long and it produces ugly formatting in Jupyter:
image
Their length should be restricted to 80 characters (or according to [the standard](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) only to 72  characters, [Numpy](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) uses 75 characters limit). The first step could be adding such reminder to `CONTRIBUTING.md`.

### PR DESCRIPTION
**Pull request by vlasenkov**
Resolves #1883.

### CODE REVIEW

**Comment by vlasenkov** [comment]
I've prepared an example. If it is ok, I'll continue refactoring.

**Comment by apaszke** [comment]
Looks good 👍

**Comment by vlasenkov** [comment]
I've fixed a part of docs. It's better to merge now. I won't be able to work on this PR for a month, and it is inclined to accumulate merge conflicts.

**Review by soumith — APPROVED** [review]
this is great. thanks a lot!

**Pull request merged**
