### PR TITLE
Quantization 1 3 doc

### PR DESCRIPTION
**Pull request by gottbrath**
This is a kinda ugly pr to land our quantization branch. I will try to clean this up, rebase it, or cancel it if I can find a cleaner way to land this.

### CODE REVIEW

**Comment by gottbrath** [comment]
ok so some self commentary on this

1. I think we should have a separate pull request for all the changes that construct quantization.rst

2. I don't know if the changes to conf.py are necessary

3. the changes to the other rst files (nn and torch) should be a second PR

4. the changes to fake_quantize, observer and quantize should already be landed in https://github.com/pytorch/pytorch/pull/27415

**Comment by gottbrath** [comment]
hey @jlin27  .. is the change here to conf.py a necessary part of this PR?

**Comment by gottbrath** [comment]
Ok .. i am trying to break this PR into several. 

Just created https://github.com/pytorch/pytorch/pull/27559 focused specifically on quantization.rst

**Comment by gottbrath** [comment]
ok in case it isn't clear. Don't land this. I'm breaking it up into independent pieces.

**Comment by jlin27** [comment]
> hey @jlin27 .. is the change here to conf.py a necessary part of this PR?

Yep, please keep the `sphinx.ext.autosectionlabel` extension in conf.py. We use it to reference the Quantization doc by it's title in nn.rst.

**Comment by gottbrath** [comment]
just created https://github.com/pytorch/pytorch/pull/27603 with the changes to the docs/source directory that go along with quantization.rst

**Comment by gottbrath** [comment]
ok .. I have split this up into three PRs. 
the docstrings one has already landed
then there is one on the quantization.rst file
then there is one for the other rst file changes needed. 

closing this because it isn't necessary.

**Pull request closed without merging**
