### PR TITLE
Reenable `torch._int_mm` testing on newer CUDAs

### PR DESCRIPTION
**Pull request by malfet**
Looks like "it just works" on SM80+ on CUDA-12

### CODE REVIEW

**Comment by vkuzo** [comment]
not an expert on this, but lgtm and thanks for fixing this!

**Review by vkuzo — APPROVED** [review]

**Comment by ptrblck** [comment]
Heads-up: we are observing a lot of failures on V100, A100, H100.
Some error messages in no particular order:
```python
Mismatched elements: 269 / 272 (98.9%)
Greatest absolute difference: 7575552.0 at index (1, 4) (up to 1e-05 allowed)
Greatest relative difference: 18432.0 at index (0, 0) (up to 1.3e-06 allowed)
```
```python
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling cublasLtMatmul with transpose_mat1 0 transpose_mat2 0 m 16 n 17 k 16 mat1_ld 16 mat2_ld 16 result_ld 16 abType 3 cType 10 computeType 72 scaleType 10
```
```python
AssertionError: RuntimeError not raised
```
Thanks @xwang233 for raising these internally!

**Comment by malfet** [comment]
@ptrblck , @xwang233 what cuda version have you tested it on? I run tests with CUDA-12.1 on A100 and with 12.0 on H100 and all tests were passing

**Comment by xwang233** [comment]
ok, this is weird

The test__int_mm tests int8 matmul through cublasLtMatmul (https://docs.nvidia.com/cuda/cublas/index.html#cublasltmatmul) with a leading dimension of 17, e.g.
https://github.com/pytorch/pytorch/blob/22f5889753d38661aefeb8ea7110ff5787a1b5e9/test/test_linalg.py#L5681-L5688

The cublasLt document, as of cuda 12.2 update 1, suggested that
> Leading dimensions of matrices A, B, C must be multiples of 4.
  Dimensions m and k must be multiples of 4.

cuda 11.7.1 doc suggested similar requirements https://docs.nvidia.com/cuda/archive/11.7.1/cublas/index.html#cublasLtMatmul

There are some size checks but still look weird to me https://github.com/pytorch/pytorch/blob/22f5889753d38661aefeb8ea7110ff5787a1b5e9/aten/src/ATen/native/cuda/Blas.cpp#L669-L672

Some cublasLtMatmul matrix input handlings are also different for "Ampere or Turing (but not Hopper) architecture" (per doc). I'll have to revisit the int8_mm implementation for more details. This doesn't look like a one-line fix failure.

Related https://github.com/pytorch/pytorch/pull/96685

**Comment by albanD** [comment]
@xwang233 given that this is going to be a bit of work to fix, should we open a brand new issue to track these observations and next steps?

**Comment by xwang233** [comment]
I’ll open a new issue on those failures.

**Pull request closed without merging**
