### PR TITLE
Python/C++ API Parity: Add impl and tests for ParameterDict

### PR DESCRIPTION
**Pull request by arktrail**
Summary: This diff contains the implementation of C++ api for ParameterDict from #25883, refer to  #36904 and #28652 

Test Plan: Add unit test in this diff

Reviewers:

Subscribers:

Tasks: #25883

Tags:

### CODE REVIEW

**Comment by glaringlee** [comment]
This is the same PR as #40014. Since #40014 is hard to rebase correctly, so we opened this with latest pytorch master.

**Comment by glaringlee** [comment]
@yyn19951228 Thanks a lot for your help!. This PR is good to go.
There is currently an internal problem with facebook system, I can not land your code in at this point, will approve this as soon as I can land it.

**Comment by yyn19951228** [comment]
Hi @glaringlee , thank you very much! And I understand that the system is not quite stable when I interned at Facebook months before. I am currently working on `ParameterList`, and will create a new PR when I finished that.

**Review by glaringlee — APPROVED** [review]
LGTM

**Pull request closed without merging**
