### PR TITLE
[docs][ao] add missing torch.choose_qparams_optimized documentation

### PR DESCRIPTION
**Pull request by supriyar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #63263
* #63258
* #63242
* #63240

Summary:
The op is part of the torch.namespace and uses greedy approach to find the optimal min/max values to minimize the quantization error

Test Plan:
CI

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D30318456](https://our.internmc.facebook.com/intern/diff/D30318456)

### CODE REVIEW

**Comment by supriyar** [comment]
@supriyar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30318456).

**Comment by supriyar** [comment]
I am not sure why this fails with `AttributeError: module 'torch' has no attribute 'quantized_lstm'` in one of the tests. @raghuramank100 do you have an idea?

**Review by jerryzh168 — APPROVED** [review]

**Comment by supriyar** [comment]
@supriyar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30318456).

**Comment by supriyar** [comment]
Discussed offline with @raghuramank100  that we won't document quantized_lstm at this point because 
1. it has been removed from native_functions.yaml (even though it is still present in torch namespace for BC)
2. existing floating point lstm ops don't have documentation either.

Updated the PR to document another op instead :)

**Comment by supriyar** [comment]
@supriyar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30318456).

**Pull request closed without merging**
