### PR TITLE
Update planner.py

### LINKED ISSUE #107997: RenamePlanner documentation incorrect
### 📚 The doc issue

The following code snippet [here](https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.LoadPlanner) is wrong because self.original_state_dict will not point to the original state dict after calling super()
```
class RenamePlanner(DefaultLoadPlanner):
    def set_up_planner(self, state_dict, metadata, is_coordinator):
        self.original_state_dict = state_dict
        super().set_up_planner(self, {"foo_" + k: v for k, v in state_dict.items()}, is_coordinator)
    def load_bytes(self, read_item, value):
        # Remove the "foo_" prefix
        self.original_state_dict[read_item.dest_index.fqn[4:]] = torch.load(value)
```

### Suggest a potential alternative/fix

```
    >>> class RenamePlanner(DefaultLoadPlanner):
    >>>     def set_up_planner(self, state_dict, metadata, is_coordinator):
    >>>         self.original_state_dict = state_dict
    >>>         state_dict = {"foo_" + k: v for k, v in state_dict.items()}
    >>>
    >>>         if self.flatten_sharded_tensors:
    >>>             state_dict = _flatten_sharded_tensors(state_dict)
    >>>
    >>>         if self.flatten_state_dict:
    >>>             state_dict, self.mappings = flatten_state_dict(state_dict)
    >>>
    >>>         self.state_dict = state_dict
    >>>         self.metadata = metadata
    >>>         self.is_coordinator = is_coordinator
    >>>
    >>>     def load_bytes(self, read_item, value):
    >>>         # Remove the "foo_" prefix
    >>>         self.original_state_dict[read_item.dest_index.fqn[4:]] = torch.load(value)
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu

### PR DESCRIPTION
**Pull request by b-chu**
Fixes #107997

### CODE REVIEW

**Review by wz337 — APPROVED** [review]
@b-chu Looks good to me. Great catch! Thanks for your contribution.

**Comment by b-chu** [comment]
I think I need a `topic: not user facing` before merging

**Pull request closed without merging**
