### PR TITLE
Fix to use upsample_bicubic2d.vec decomp for dynamic shape support

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #92854

For the `crossvit_9_240` model - it works now with dynamo.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by malfet** [comment]
Not sure if it is related, but two commits in the row after this one failed with SIGIOT in test_jit_fuser, see https://hud.pytorch.org/pytorch/pytorch/commit/d49187bf8882dabfb307de4f3f6a9031426e677a

**Comment by malfet** [comment]
Will reland by the EOD if flakiness does not subside (sorry, might be a misattribution)

**Pull request closed without merging**
