### PR TITLE
Add getStreamFromPool to DeviceGuardImplInterface

### PR DESCRIPTION
**Pull request by lw**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #57052 Merge CUDAFuture into ivalue::Future
* #57051 Make CUDAFuture handle any kind of device type
* #57050 Use only generic helpers in CUDAFuture
* #57049 Introduce generic MultiStreamGuard
* #57048 Simplify CUDAMultiStreamGuard
* #57047 Add recordDataPtrOnStream to DeviceGuardImplInterface
* **#57046 Add getStreamFromPool to DeviceGuardImplInterface**

We intend to merge CUDAFuture into ivalue::Future by using DeviceGuardImplInterface to avoid explicitly referring to CUDA. For that we need to add two methods to DeviceGuardImplInterface. In this PR, we add a method to get a stream from the global ATen pool.

Differential Revision: [D28029159](https://our.internmc.facebook.com/intern/diff/D28029159/)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by lw** [comment]
@ezyang There's an issue which this (which only emerges when it is used): `getStreamFromPool` is a token that gets HIPified, hence any callsite of this method will be affected.

https://github.com/pytorch/pytorch/blob/0df574017d8f0eb1527e973defb9c65a5befe966/torch/utils/hipify/cuda_to_hip_mappings.py#L7947

Two options: we rename this method (e.g., `getStreamFromGlobalPool`), or we rename the the current `getStreamFromPool` function to `getCUDAStreamFromPool` and update the HIP mappings (this also increases consistency with the `getCurrentCUDAStream` and `getDefaultCUDAStream`). I'd prefer the latter, but my concern is that this might be a public API and thus it might break some users. What do you think?

**Comment by ezyang** [comment]
I'd rename this method so that it doesn't conflict with the hipify token. It's private API anyway.

**Comment by lw** [comment]
Actually it seems the issue disappears once we merge CUDAFuture into ivalue::Future, hence from aten/cuda to c10/core. I guess the two directories are HIPified differently? This means we can leave this as is for now and worry about renaming it later if it ever causes real problems (since, as you said, this API is private).

**Comment by ezyang** [comment]
Yes. c10 gets hipified in the way you'd expect (CUDA to HIP), but ATen gets hipified weirdly (CUDA to HIPMasqueradingAsCUDA).

**Pull request closed without merging**
