### PR TITLE
Update pybind11 submodule to 2.11.0

### PR DESCRIPTION
**Pull request by Skylion007**
Update pybind11 submodule to 2.11.0 with better python 3.12 support, bugfixes, a few new features, and more.

### CODE REVIEW

**Comment by albanD** [comment]
The libstdc++.so.6 failure is a CI outage. Let's wait a bit and rebase.

**Review by albanD — APPROVED** [review]
SGTM if CI is green!

**Comment by Skylion007** [comment]
Updating this dependency has uncoverred a GIL error.

**Comment by Lalaland** [comment]
As the pybind11 author of that error message in question, it's probably easiest for me to fix this. I'll assign myself to this issue and see what is going on.

**Comment by Lalaland** [comment]
Hmm. I am unable to reproduce this locally so I unfortunately cannot help fix this.

**Comment by albanD** [comment]
Thanks for looking into this!
Unfortunately there is a single build of PyTorch that works for both. So we can't have different compile args for deploy builds vs regular builds.

Let me try to debug this on the ci machine to know which objects are problematic. We can then see what to do with this.

**Comment by albanD** [comment]
Ho I need to be the author of the PR haha

**Comment by EthanSteinberg** [comment]
@albanD I think you might want to consider the other option of simply disabling that check. https://github.com/pytorch/multipy/pull/325 is how you would do that.

Note that the error is only with multipy, not main PyTorch so it only needs to be disabled there.

Multipy already has a bunch of GIL checks disabled

**Comment by albanD** [comment]
The question is if these decref errors comes from multipy code or pytorch code?
If it is multipy own code, then disabling these checks when we build multipy is a good fix I agree.
But if the check is from pytorch code (that is only badly exercised in a multipy environment), then it will not be enough as pytorch code is still build with these checks.

Do you know which one it is given the current signal?

**Comment by EthanSteinberg** [comment]
https://github.com/pytorch/pytorch/pull/105283 is the main experiment I ran to try to understand this. Note how the checks are still active in the PyTorch extension, they are only disabled in multipy and the tests pass.

**Comment by albanD** [comment]
Ho that is great news!
So the next steps are the following right?:
- fix multipy in their repo
- upgrade multipy here
- merge this pr

**Comment by EthanSteinberg** [comment]
> So the next steps are the following right?:

Almost, but not quite, since we only added that disable flag in pybind11 2.11.1

So the next steps are the following:

- fix multipy in their repo
- upgrade multipy here
- upgrade pybind11 here to 2.11.1
- merge this pr

**Comment by albanD** [comment]
> Almost, but not quite, since we only added that disable flag in pybind11 2.11.1

Ho I though that flag already existed :thinking: but maybe I was looking at a too recent pybind haha
Working on the multipy merge.

**Comment by albanD** [comment]
Step 1 done, step 2 is here: https://github.com/pytorch/pytorch/pull/105344

**Comment by EthanSteinberg** [comment]
@Skylion007 can you update this PR to pybind 2.11.1? We should be good to go.

**Review by albanD — APPROVED** [review]
All green! :tada:

**Pull request closed without merging**
