### PR TITLE
Rename trtrs to triangular_solve

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:
- Renames `trtrs` to `triangular_solve` to remain consistent with `cholesky_solve` and `solve`.
- Rename all tests, fix callsites
- Create a tentative alias for `triangular_solve` under the name `trtrs`, and add a deprecation warning to not promote usage.
- Move `isnan` to _torch_docs.py
- Remove unnecessary imports

Test Plan:
- All tests should pass to confirm that the patch is correct.

Stack:
1. #18025 - Add batched version of trtrs
2. #18213 - Rename trtrs to triangular_solve

### CODE REVIEW

**Review by soumith — APPROVED** [review]
lgtm

**Comment by vishwakftw** [comment]
All build/test failures are spurious

**Pull request closed without merging**
