### PR TITLE
[nnc] Don't fuse intrinsics on cpu if they are slower

### PR DESCRIPTION
**Pull request by bertmaher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#51252 [nnc] Don't fuse intrinsics on cpu if they are slower**
* #51246 [nnc] Don't use sleef where it's slower
* #51190 [nnc] Expose vectorized math functions to jit fuser.
* #51187 [nnc] Use sleef if its symbols are available
* #51186 [nnc][trivial] Refactor llvm_jit so the wrapper class doesn't depend on ifdefs
* #51125 [nnc] Refactor generation of intrinsics to reduce the amount of macro-hell

A number of intrinsics are slower when generated by the fuser
(probably because VML is faster than sleef in these cases?).  At some point we
could try to get the fuser to either (1) use VML directly or (2) directly
implement our own fast vectorized approximation but those are both hard to do.

For now, let's just not translate those ops.

Differential Revision: [D26115354](https://our.internmc.facebook.com/intern/diff/D26115354/)

### CODE REVIEW

**Review by ZolotukhinM — APPROVED** [review]
👍

**Review by eellison — COMMENTED** [review]
What's the perf numbers on these ? Whenever we're fusing these, there will be at least one fusion going on - our minimum fusion size is 2. I think the more accurate comparison is what are the perf numbers when one fusion occurs.

I would guess with the saved memory bandwidth & read/write we might be ahead. Could we check ? Another thing to check would be fusion of size 3. We could consider setting a different minimum fusion size for cpu / cuda.

**Comment by bertmaher** [comment]
> What's the perf numbers on these ? Whenever we're fusing these, there will be at least one fusion going on - our minimum fusion size is 2. I think the more accurate comparison is what are the perf numbers when one fusion occurs.
> 
> I would guess with the saved memory bandwidth & read/write we might be ahead. Could we check ? Another thing to check would be fusion of size 3. We could consider setting a different minimum fusion size for cpu / cuda.

Yeah, so this is a good question.  I ran a few benchmarks fusing something simple into the op (like `+ 1.0`) and it's generally not enough to make up for the slowness of the intrinsics.  (I think many of these have enough compute that they're actually compute bound rather than BW bound, but I'm not certain of that).

Here's some raw data.  This is probably "best case": I'm benching `op(x + 0.125) + 1.0`, which yields the biggest bandwidth saving from fusion (3r+3w -> 1r+1w).

Before this diff:
```
op                        eager        nnc    speedup
acos                      0.212      0.402       0.53
asin                      0.201      0.279       0.72
atan                      0.329      0.352       0.94
cos                       0.207      0.254       0.81
erf                       0.231      0.850       0.27
erfc                      0.261      1.076       0.24
exp                       0.144      0.130       1.11
log                       0.169      0.279       0.60
log10                     0.235      0.292       0.80
log1p                     0.279      0.271       1.03
log2                      0.226      0.282       0.80
round                     0.117      0.094       1.25
sin                       0.212      0.232       0.91
sinh                      0.476      0.400       1.19
sqrt                      0.120      0.069       1.75
tan                       0.346      0.394       0.88
tanh                      0.378      0.567       0.67
```

After this diff:
```
op                        eager        nnc    speedup
acos                      0.211      0.207       1.02
asin                      0.204      0.204       1.00
atan                      0.315      0.318       0.99
cos                       0.201      0.196       1.03
erf                       0.220      0.229       0.96
erfc                      0.258      0.253       1.02
exp                       0.429      0.424       1.01
log                       0.155      0.153       1.02
log10                     0.213      0.216       0.99
log1p                     0.262      0.266       0.98
log2                      0.216      0.230       0.94
round                     0.115      0.109       1.05
sin                       0.205      0.202       1.01
sinh                      0.472      0.400       1.18
sqrt                      0.120      0.118       1.02
tan                       0.340      0.337       1.01
tanh                      0.381      0.376       1.01
```

Based on this I could see a case for leaving `sqrt` in, but the others look like losses.  I guess on *really* small tensors getting rid of the op overhead is worth something?

**Comment by eellison** [comment]
I guess I'd be curious to see what the other speedups of the other ops not shown here are - if they're a decent speed up (> 1.2 ?) and we only emit them if they are in a fusion group, they will be in fusion groups less often if we disable these intrinsics, then it might be worth including some of the ops here on the boundary. 

I think this is fine for landing, I think in the short term itd be worth finding some real world models and benchmarking the fusion groups w/without some of these ops included. Personally i'd draw the line at ops where nnc is >= 90% of eager speed. 

Also - you have `exp` `sinh` `sqrt` `round` and `log1p` included in this even though they are faster in NNC - why's that ?

**Comment by eellison** [comment]
We should make sure to revisit this if/when multithreading is enabled, I would guess that with fusion groups there's less threading overhead of starting/stopping and it would be profitable to fuse these ops again...

**Comment by bertmaher** [comment]
> Also - you have `exp` `sinh` `sqrt` `round` and `log1p` included in this even though they are faster in NNC - why's that ?

I should re-benchmark those, I kind of think the speedup in the above paste was noise, but maybe they're actually on par, in which case it'd be fine to keep them.

**Comment by bertmaher** [comment]
Just going to comment for posterity -- I'm holding off on landing this PR to do a bit more benchmarking of these with fusion.  As @eellison notes, It's quite likely that even if we don't want to generate a single-op kernel with NNC but a fused kernel could still make sense.

**Pull request closed without merging**
