### PR TITLE
[wip] Port TH math to ATen/Parallel

### PR DESCRIPTION
**Pull request by ilia-cher**
Summary:
Removing explicit dependency on OpenMP from TH math

Test Plan:
pytest -s -v test/test_torch.py::TestTorch

### CODE REVIEW

**Comment by ilia-cher** [comment]
(in progress)

**Comment by cpuhrsch** [comment]
As a general guideline, albeit unlikely and not seen on the PR yet, try to avoid adding references of TH to ATen. Treat TH as marked for removal and this as a further step towards migrating existing code.

**Comment by ilia-cher** [comment]
I'm going to resend and update this as part of ghstack on top of 
https://github.com/pytorch/pytorch/pull/19058

**Comment by ilia-cher** [comment]
resent and updated in https://github.com/pytorch/pytorch/pull/19105/commits

**Pull request closed without merging**
