### PR TITLE
Add `lazy_clone_storage` to create COW storages

### PR DESCRIPTION
**Pull request by kurtamohler**
This PR relands #110022 but accounts for the changes in #110191. Also, the function for creating COW storages is called `lazy_clone_storage` in this PR, instead of `try_ensure`

NOTE: COW storages do not actually copy on write yet, they just have the COW deleter and deleter context applied to them

Part of #109833

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #110192

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

### CODE REVIEW

**Comment by kurtamohler** [comment]
To fix the memory leak that caused #110022 to be reverted, I modified the `different_context` test to delete the `new std::byte[5]`. It wasn't being deleted before, which was likely the reason for the memory leak.

I wasn't able to find out why the other failure happened though, where the `try_ensure` call (now called `lazy_clone_storage`) returned a null storage in the `no_context` test. Apparently, the StorageImpl that gets created for that test can in some cases is given a context that does not equal the data pointer, when it's run in the internal CI. I'm not sure why that would happen. But I added an assert to that test to check the context before the `lazy_clone_storage` call

**Comment by ezyang** [comment]
Did you just delete the try ensure tests from this PR? Do you want to land it as is or try to diagnose the problem?

**Comment by ezyang** [comment]
fwiw, with your PR, I get this failure:

```
✗ Fail: fbsource//xplat/caffe2/c10:c10_test - lazy_clone_storage_test.no_context (0.0s)
xplat/caffe2/c10/test/core/impl/cow_test.cpp:92
Value of: original_storage.data_ptr().get()
Expected: is equal to 0x605000000010
  Actual: 0x605000000020 (of type void*)

stdout: Running main() from third-party/googletest/1.11.0/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = lazy_clone_storage_test.no_context
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from lazy_clone_storage_test
[ RUN      ] lazy_clone_storage_test.no_context
xplat/caffe2/c10/test/core/impl/cow_test.cpp:92: Failure
Value of: original_storage.data_ptr().get()
Expected: is equal to 0x605000000010
  Actual: 0x605000000020 (of type void*)
[  FAILED  ] lazy_clone_storage_test.no_context (0 ms)
[----------] 1 test from lazy_clone_storage_test (0 ms total)
      
[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] lazy_clone_storage_test.no_context

```

**Comment by kurtamohler** [comment]
> Did you just delete the try ensure tests from this PR? Do you want to land it as is or try to diagnose the problem?

No, I didn't delete the tests, I renamed them from `try_ensure` to `lazy_clone_storage`. I would like to try to fix the problem

**Comment by ezyang** [comment]
oh I see. OK, so then it's the `no_context` test which is still failing. How do you want to tackle this? Is the new error enough?

**Comment by kurtamohler** [comment]
The new error comes from the check that I added to the `no_context` test which checks that `original_storage`'s data pointer and context are equal to each other:

```cpp
  StorageImpl original_storage(
      {}, /*size_bytes=*/7, GetCPUAllocator(), /*resizable=*/false);
  ASSERT_THAT(original_storage, testing::Not(is_copy_on_write()));
  ASSERT_THAT(
      original_storage.data_ptr().get(),
      testing::Eq(original_storage.data_ptr().get_context()));
```

My guess is that something in the Meta-internal test suite must be changing the allocator that `GetCPUAllocator()` returns, probably by calling `SetCPUAllocator`. This allocator sets the context to something that does not equal the data pointer, which COW does not support.

I think the fix is just to use `GetDefaultCPUAllocator()` instead, since that does not change when `SetCPUAllocator` is called

**Comment by kurtamohler** [comment]
@ezyang, I'm guessing that the test will pass internally now after I changed it to use `GetDefaultCPUAllocator()` instead of `GetCPUAllocator()`

**Comment by ezyang** [comment]
testing it rn

**Comment by ezyang** [comment]
no cigar 

```
xplat/caffe2/c10/test/core/impl/cow_test.cpp:93
Value of: original_storage.data_ptr().get()
Expected: is equal to 0x605000000010
  Actual: 0x605000000020 (of type void*)

stdout: Running main() from third-party/googletest/1.11.0/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = lazy_clone_storage_test.no_context
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from lazy_clone_storage_test
[ RUN      ] lazy_clone_storage_test.no_context
xplat/caffe2/c10/test/core/impl/cow_test.cpp:93: Failure
Value of: original_storage.data_ptr().get()
Expected: is equal to 0x605000000010
  Actual: 0x605000000020 (of type void*)
```

**Comment by kurtamohler** [comment]
From the error message, the data pointer is 0x10 (16) bytes greater than the context pointer.

I noticed that on mobile builds: 

https://github.com/pytorch/pytorch/blob/5183760ca52ea7dbd892ebc88cabdd43ebc81cbe/c10/core/CPUAllocator.cpp#L166-L176

https://github.com/pytorch/pytorch/blob/5183760ca52ea7dbd892ebc88cabdd43ebc81cbe/c10/core/alignment.h#L7-L11

https://github.com/pytorch/pytorch/blob/5183760ca52ea7dbd892ebc88cabdd43ebc81cbe/c10/core/CPUAllocator.cpp#L71-L72

https://github.com/pytorch/pytorch/blob/5183760ca52ea7dbd892ebc88cabdd43ebc81cbe/c10/core/CPUAllocator.cpp#L134-L139


So it seems like that is probably what is happening here. Could you confirm if the internal CI is using a mobile build?

To fix this, we should be able to just change all `data_ptr.get() == data_ptr.get_context()` checks to add in the `c10::gAlignment` in the `C10_MOBILE` case.

**Comment by ezyang** [comment]
yup, it's a mobile build

**Comment by kurtamohler** [comment]
Well, adding a `storage.allocator() == c10::GetDefaultMobileCPUAllocator()` check to `c10/core/impl/cow/COW.cpp` made the bazel build fail because `CPUAllocator` is its own bazel library that is not included in `base`. So I guess we'll have to separate COW into its own library after all

**Comment by kurtamohler** [comment]
This is ready for another internal CI run

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D50265134).

**Review by ezyang — APPROVED** [review]
internal tests are clear

**Comment by kit1980** [comment]
I'm going to revert this and immediately re-merge to work around some importing issues.

**Comment by kurtamohler** [comment]
@jeanschmidt or @ezyang, let me know what the error was and I can work on fixing it

**Comment by ezyang** [comment]
```
Running main() from third-party/googletest/1.11.0/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = lazy_clone_storage_test.no_context
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from lazy_clone_storage_test
[ RUN      ] lazy_clone_storage_test.no_context

stderr:
terminate called after throwing an instance of 'c10::Error'
  what():  original_ctx.get() == data_ptr.get() INTERNAL ASSERT FAILED at "xplat/caffe2/c10/core/impl/cow/COW.cpp":83, please report a bug to PyTorch. 
Exception raised from lazy_clone_storage at xplat/caffe2/c10/core/impl/cow/COW.cpp:83 (most recent call first):
(no backtrace available)
```

**Comment by kurtamohler** [comment]
Oh I see what's wrong. I'll submit a fixed PR shortly

**Pull request closed without merging**
