### PR TITLE
Do not build cpuinfo if NNPACK is found

### PR DESCRIPTION
**Pull request by ebetica**
Since NNPACK has a copy of cpuinfo, this will error with duplicate symbols. Solves #6068

### CODE REVIEW

**Comment by ebetica** [comment]
As an aside, is it possible that none of the contbuilds have NNPACK? Otherwise this error should have been caught.

**Comment by Maratyszcza** [comment]
LGTM

**Comment by goldsborough** [comment]
@ebetica yeah I don't think we build with NNPACK in CI.

**Review by goldsborough — APPROVED** [review]

**Comment by apaszke** [comment]
Is this really a good solution? This kind of `B-> A, C -> A, C -> B` relationship between libraries is very common, even in PyTorch (think `A = TH, B = THC, C = ATen`), and it usually ends just fine without linking errors.

**Comment by ezyang** [comment]
The root cause of the problem is our implementation of `FindNNPACK`:

```
find_library(NNPACK_LIBRARY nnpack
    PATHS ${NNPACK_ROOT_DIR}
    PATH_SUFFIXES lib lib64)

find_library(CPUINFO_LIBRARY cpuinfo
    PATHS ${NNPACK_ROOT_DIR}
    PATH_SUFFIXES lib lib64)

find_library(PTHREADPOOL_LIBRARY pthreadpool
    PATHS ${NNPACK_ROOT_DIR}
    PATH_SUFFIXES lib lib64)

# ... later ...

if (NNPACK_FOUND)
  target_link_libraries(ATen ${NNPACK_LIBRARIES})
endif(NNPACK_FOUND)
```

This means that when nnpack is enabled, we statically link in the cpuinfo that is installed alongside NNPACK.  But then, we turn around and unconditionally link it again:

```
# ---[ Configure cpuinfo
IF(NOT TARGET cpuinfo)
  SET(CPUINFO_BUILD_TOOLS OFF CACHE BOOL "")
  SET(CPUINFO_BUILD_UNIT_TESTS OFF CACHE BOOL "")
  SET(CPUINFO_BUILD_MOCK_TESTS OFF CACHE BOOL "")
  SET(CPUINFO_BUILD_BENCHMARKS OFF CACHE BOOL "")
  ADD_SUBDIRECTORY("cpu/cpuinfo")
ENDIF()
TARGET_LINK_LIBRARIES(ATen cpuinfo)
```

So nnpack shows up twice in the library list for ATen, and obviously that is not going to work.

**Comment by ebetica** [comment]
@apaszke Could land this as a hotfix, and then work on fixing it properly?

**Comment by ezyang** [comment]
@ebetica: @cpuhrsch (channeling @Maratyszcza) and I discussed this, and now that mkldnn landed, there isn't any utility to building against NNPACK on x86. So we are going to just remove the NNPACK dependency altogether. For your workaround, can you just disable NNPACK? (And if you need fast CPU convolutions, turn on mkldnn)

**Comment by soumith** [comment]
nnpack is now deleted in master

**Pull request closed without merging**
