### PR TITLE
Implement torch.isnan

### PR DESCRIPTION
**Pull request by tunz**
Hello,
Please take a look.

I implemented `torch.isnan` in C/C++. You can use this function as following:
```
>>> torch.isnan(torch.Tensor([1,2,3,float('nan'),5]))

 0
 0
 0
 1
 0
[torch.ByteTensor of size 5]
```

Since it's my first contribution to your project, I'm not familiar with testing or coding style, so please let me know if something's wrong.

Ref: https://github.com/pytorch/pytorch/issues/4767

### CODE REVIEW

**Comment by apaszke** [comment]
Thanks for the PR, but can't this be implemented like this (for floating point tensor types):
```python
def isnan(x):
    return x != x
```

**Comment by tunz** [comment]
Of course, we can implement like that. uploaded a new patch.

**Review by soumith — APPROVED** [review]

**Review by apaszke — APPROVED** [review]

**Comment by soumith** [comment]
thanks @tunz !

**Pull request merged**
