### PR TITLE
Disable test_torchinductor multi-gpu in test_distributed on ROCm

### PR DESCRIPTION
**Pull request by jataylo**
Disables running multi_gpu test_torchinductor tests on ROCm until the regular test_torchinductor UTs are enabled via https://github.com/pytorch/pytorch/pull/97988.

This will be re-enabled in a future PR to enable the distributed inductor UTs on ROCm.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Comment by jataylo** [comment]
The cuda fails are not related to this change.

The ROCm failure is a new failure which is now being skipped
https://github.com/pytorch/pytorch/issues/100539

**Review by jithunnair-amd — APPROVED** [review]
LGTM. We plan to re-enable test_torchinductor multi-gpu UTs in a later PR, once test_torchinductor single-GPU UTs have been enabled.

**Comment by jithunnair-amd** [comment]
@malfet Ping, this should be a straightforward one to merge. CI failures are unrelated.

**Review by malfet — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
Closing this PR as multigpu tests were moved to test_inductor_distributed as of this commit: https://github.com/pytorch/pytorch/commit/32c9e7d377d17b534b856363ebc0b198123949b8

**Pull request closed without merging**
