### PR TITLE
[RELAND] [cuDNN] Add a new optimized cuDNN RNN algorithm for small RNN hidden_size

### PR DESCRIPTION
**Pull request by mcarilli**
https://github.com/pytorch/pytorch/pull/62143 was reverted (https://github.com/pytorch/pytorch/pull/72089) because, when running native tests internally with cudnn and GPUs such that `CUDNN_RNN_ALGO_PERSIST_STATIC_SMALL_H` was used, we hit some `CUDNN_STATUS_NOT_SUPPORTED` errors.

Based on https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#features-of-rnn-functions and experiments, I strongly suspect the errors were because `CUDNN_RNN_ALGO_PERSIST_STATIC_SMALL_H` doesn't support variable sequence lengths in the batch.

This PR restores https://github.com/pytorch/pytorch/pull/62143 and adds a bailout condition if the input is a packed batch that might have different sequence lengths per element.

Question for review: Do we also need to add a bailout condition if the input is double precision?

### CODE REVIEW

**Comment by ngimel** [comment]
What about regular persistent algorithm? Should it bail out when inputs are packed? Does it do it (if so, where? It's not in the algo selection function)? 
Also, for regular persistent algo I see a bunch of checks in the sizes in use_persist_common_heuristics, should small_h also perform these checks?

**Comment by xwang233** [comment]
`CUDNN_RNN_ALGO_PERSIST_STATIC_SMALL_H` is not supported for double precision and we shouldn't use it. It was causing lots of `RNN_float64` unit test failures.

**Comment by mcarilli** [comment]
The other persistent algo already bails out if the input is packed https://github.com/pytorch/pytorch/pull/73211/files#diff-937039ea7623bab4ebb608bb2198115113ee934f64a6e21fa067dc317a956623R800 (and it only triggers for fp16 data).

**Comment by mcarilli** [comment]
I reworked the checks to avoid `CUDNN_RNN_ALGO_PERSIST_STATIC_SMALL_H` for fp64 inputs.

**Comment by ngimel** [comment]
Does PERSIST_STATIC_SMALL_H support arbitrary hidden and input sizes? For regular persist algorithm there are checks that those are multiples of 128 or 64 or something.

**Comment by mcarilli** [comment]
>Does PERSIST_STATIC_SMALL_H support arbitrary hidden and input sizes? For regular persist algorithm there are checks that those are multiples of 128 or 64 or something.

No idea. @xwang233 did you discuss this at all with cudnn people during the original PR?

**Comment by xwang233** [comment]
Only small hidden sizes are supported and those are already in the PR code. All input sizes should be supported.

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
