### PR TITLE
Nvfuser opt in for decomposition

### PR DESCRIPTION
**Pull request by jjsjann123**
Regarding issues reported in #79246, we notice that bias decomposition from conv/linear could actually hurt perf, due to the overhead of compilation. This PR changes it to make decomposition an explicit opt-in from user to avoid these regressions.

### CODE REVIEW

**Comment by davidberard98** [comment]
@jjsjann123 do you know if you have permissions to push branches to the pytorch/pytorch repo? I believe this is the requirement to be able to run torchbench CI

**Review by davidberard98 — APPROVED** [review]
looks good to me!

Opened a PR to run torchbench (#81292) just to see if it affects any other models, but I'm guessing that the microbenchmarks won't be affected because they are collected after the decomposition...

Also, it might be worth documenting these in the readme?

**Comment by jjsjann123** [comment]
> looks good to me!
> 
> Opened a PR to run torchbench (#81292) just to see if it affects any other models, but I'm guessing that the microbenchmarks won't be affected because they are collected after the decomposition...
> 
> Also, it might be worth documenting these in the readme?

I think I have access to push to pytorch repo directly. I'll try that next time~~
Looks like my doc update wasn't checked-in :cry: Will update that~

**Comment by davidberard98** [comment]
@jjsjann123 fyi, the failing xla test is flaky so if it fails again we can just re-run the test and hope it passes.

**Pull request closed without merging**
