### PR TITLE
Python Operator Authoring w/ NNC Prototype

### PR DESCRIPTION
**Pull request by jansel**

### CODE REVIEW

**Review by bertmaher — APPROVED** [review]
I say we land this (maybe with the private module name`_te` for the time being, since this is kind of a pre-alpha feature) so we can iterate.

@ezyang @ZolotukhinM @gchanan @suo any concerns?

**Comment by ZolotukhinM** [comment]
I think it needs to be cleaned up and split into smaller PRs before landing. For instance:
* `call_fast` seems like a hack - we should instead be able to generate an LLVM code for computing block/thread indices.
* relying on `sympy` is sus - is it how we want to deal with gradients long term? If not, the implementation might have to be changed
* CompileCache/CompileCache2/CompileCache3 need better names 😃

Also, a couple high-level questions:
* Do we plan to support any kind of reductions with this? If so, how do we achieve reasonable performance there?
* How does this cache relates to profiling executor and caching used in SR? Can we use a single composable component that's usable in those places too? "No" is a valid answer too provided it has a justification🙂
* Do we plan to integrate other backends, such as NVFuser/Triton? If so, how?

**Comment by ezyang** [comment]
As an alternative (since we've been talking about how difficult it is to land stuff recently), most of the pieces of this PR seem pretty decoupled from NNC proper, and so you could probably iterate faster by having this live as an out of tree `cpp_extension`. I guess this mostly depends on how much you think the prototype here is "final" as opposed to "maybe we have to rewrite it". If most of everything might get rewritten shortly it seems better to do that somewhere where you can do it more quickly first.

**Comment by bertmaher** [comment]
> As an alternative (since we've been talking about how difficult it is to land stuff recently), most of the pieces of this PR seem pretty decoupled from NNC proper, and so you could probably iterate faster by having this live as an out of tree `cpp_extension`.

I was thinking about this too.  It's nice to piggyback on the repo setup of pytorch and not do a bunch of CI setup, etc. but I'd be okay with out-of-tree.  @jansel do you have a preference?

**Comment by jansel** [comment]
The python bits would be pretty easy to put out of tree, though the C++ parts would be harder because of build issues.  That could lead to issues though as the two parts are tightly coupled.

**Comment by jansel** [comment]
Cleaned up diff stack based on this
https://github.com/pytorch/pytorch/pull/65204

**Pull request closed without merging**
