### PR TITLE
tf32 context fixes for various tests

### PR DESCRIPTION
**Pull request by Fuzzkatt**
Addresses tf32 context related failures from NVIDIA internal testing for following unit tests:

H100:

- functorch/test_vmap.py: test_op_has_batch_rule

A100:

- test_expanded_weights.py: test_cnn_model_sum
- nn/test_convolution.py: test_conv2d_same_padding_backward

cc: @ptrblck

### CODE REVIEW

**Comment by zou3519** [comment]
@Fuzzkatt could you rebase this PR please? It looks like some tests are failing but those might be pre-existing

**Comment by Fuzzkatt** [comment]
Ready for review

**Review by zou3519 — APPROVED** [review]
LGTM

**Pull request closed without merging**
