### PR TITLE
remove some internal only starlark files from OSS

### PR DESCRIPTION
**Pull request by dagitses**
Summary:
This is to make it easier to refactor these files since it greater
constrains their availability.

This is the final step of a three part migration:

1) remove from configerator
2) remove from master branch
3) remove from fbsync

Test Plan: Should be a no-op: rely on CI.

Reviewers: jonjanzen

### CODE REVIEW

**Review by bigfootjon — APPROVED** [review]
LGTM, ping me after D39212550 lands internally and I'll merge

**Review by malfet — CHANGES_REQUESTED** [review]
This is probably fine, but I'm curious why we had to reverse the decision we made less than a month ago of opensourcing all those .bzl files and not having a complex configs

@bigfootjon , @dagitses can you elaborate why we want to maintain complex exclusion lists again?

**Comment by bigfootjon** [comment]
@malfet I'm just walking @dagitses through the process, I'll let him explain

**Comment by dagitses** [comment]
> This is probably fine, but I'm curious why we had to reverse the decision we made less than a month ago of opensourcing all those .bzl files and not having a complex configs
> 
> @bigfootjon , @dagitses can you elaborate why we want to maintain complex exclusion lists again?

What was the rationale for that decision? I think the priority should be simplifying the OSS world for a minor increase in complexity in the private internal world.

**Comment by dagitses** [comment]
> > This is probably fine, but I'm curious why we had to reverse the decision we made less than a month ago of opensourcing all those .bzl files and not having a complex configs
> > @bigfootjon , @dagitses can you elaborate why we want to maintain complex exclusion lists again?
> 
> What was the rationale for that decision? I think the priority should be simplifying the OSS world for a minor increase in complexity in the private internal world.

I'm going to withdraw this. I think it's cleaner to move these to an fb/ subfolder. It shouldn't cause a problem since they are not used across different repo roots.

**Pull request closed without merging**
