### PR TITLE
dbr quant: do not crash on unsupported qconfig_dict keys if they are empty

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #71551 dbr quant: record dag of non-quantizeable ops
* #71324 dbr quant: refactor first_call hooks to be standalone
* #71312 dbr quant: rename seen_op_info to seen_q_op_info
* #71267 dbr quant: make SeenOpInfo a dataclass
* #71253 dbr quant: split observer insertion to a separate pass
* #71245 dbr quant: make QTensorInfo a dataclass and add orig_dtype
* **#71233 dbr quant: do not crash on unsupported qconfig_dict keys if they are empty**

Summary:

Some keys in qconfig_dict are not implemented yet for DBR quant.
However, FX graph mode quantization modifies qconfig_dict inplace,
so if users use the same dict for DBR and FX they may hit errors.

This PR reduces the chance of these errors by only throwing an
exception in DBR quant if the unsupported keys have nonempty values.

Test plan:

```
python test/test_quantization.py TestQuantizeDBR.test_qconfig_dict_unsupported_only_crashes_when_nonempty
```

Differential Revision: [D33552398](https://our.internmc.facebook.com/intern/diff/D33552398)

### CODE REVIEW

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33552398).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33552398).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33552398).

**Review by HDCharles — APPROVED** [review]
looks good

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33552398).

**Pull request closed without merging**
