### PR TITLE
Avoid changing FTZ/DAZ flags in CPP builder

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136466

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

Fixes https://github.com/pytorch/pytorch/issues/136273

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
```
2024-09-24T01:55:51.2380570Z Output:
2024-09-24T01:55:51.2381000Z clang: error: optimization flag '-fexcess-precision=fast' is not supported [-Werror,-Wignored-optimization-argument]
2024-09-24T01:55:51.2381000Z 
```

**Comment by Valentine233** [comment]
@isuruf @ezyang Hi, this commit causes the perf regression for several models on CPU. For example, the perf drops to 30% on `hrnet_w18`  with fp32. More regressions are recorded in https://github.com/pytorch/pytorch/pull/133842. cc @jgong5 @leslie-fang-intel

**Comment by isuruf** [comment]
@Valentine233 thanks for the report. Does the regression go away if you enable `torch._inductor.config.enable_unsafe_math_opt_flag` ?

**Comment by Valentine233** [comment]
> @Valentine233 thanks for the report. Does the regression go away if you enable `torch._inductor.config.enable_unsafe_math_opt_flag` ?

Yes, the regression goes away. I suppose the reason is that the `unsafe_math_opt_flag` also does the FTZ/DAZ changes.
However, the regression would still exist, as the `unsafe_math_opt_flag` turns off by default due to the functional issue (https://github.com/pytorch/pytorch/pull/113347).

**Pull request closed without merging**
