### PR TITLE
Port `all` kernel to structured kernels.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #60364 Port `argmin` kernel to structured kernels.
* #60363 Port `argmax` to structured kernels.
* #60362 Using meta checks for unary `torch.all` and `torch.any`.
* #60361 Port `any` kernel to structured kernels.
* **#60360 Port `all` kernel to structured kernels.**

Tracking issue: #55070

This PR was openned so as to solve the CI failures in main when merging: #59371 #59372 #59373 #59937 #59938.

Differential Revision: [D29265856](https://our.internmc.facebook.com/intern/diff/D29265856)

### CODE REVIEW

**Comment by ezyang** [comment]
BTW, since we've reviewed the individual pieces, you should feel free to squash these PRs if you would prefer it. Would help save on CI costs. (You can also keep doing what you've done, that's fine too)

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29265856).

**Comment by ezyang** [comment]
The failures on any look real, so I'm trigger ci/master on all to help narrow down if this PR by itself is sufficient to cause problems.

**Comment by ysiraichi** [comment]
1. I think the problem was that I wasn't really calling `maybe_wrap_dim` at some execution paths (which I have fixed). Let's wait and see if there are any CI failures
2. After discussing with @bdhirsh, I think we can inherit from `TensorIteratorBase` for these reduction kernels. Then, instead of calling `set_output`, we would call `declare_static_shape`!

That said, since these bunch is already reviewed, I think I will fix (2) in another PR.

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29265856).

**Comment by ezyang** [comment]
results look good

**Comment by ezyang** [comment]
You're not the first person to run into this type of bug, see https://github.com/pytorch/pytorch/issues/55526

**Pull request closed without merging**
