### PR TITLE
Add cherry-pick workflow

### PR DESCRIPTION
**Pull request by huydhn**
After https://github.com/pytorch/test-infra/pull/4758, we can create a new workflow on PyTorch to receive `try-cherry-pick` dispatch event from the bot, and create the cherry pick PR.

* [x] Cherry pick a PR after it has been landed and create a cherry pick PR to the target release branch.
* [ ] The second part after this is to update the release tracker with the info.  This will be done in a subsequent PR.
* [ ] ghstack is not yet supported
* [ ] Cherry pick a reverted commit is not yet supported (from @kit1980 comment)

### Testing

The script can be used locally:

```
python cherry_pick.py --onto release/2.2 --classification release --github-actor huydhn 118907
The cherry pick PR is at https://github.com/pytorch/pytorch/pull/119351
```

The test cherry pick PR is created at https://github.com/pytorch/pytorch/pull/119351

Unit testing this on CI is tricky, so I test this out on canary instead.

* https://github.com/pytorch/pytorch-canary/pull/193#issuecomment-1933162707 creates the PR at https://github.com/pytorch/pytorch-canary/pull/201
  * One more test on canary with the new token https://github.com/pytorch/pytorch-canary/pull/193#issuecomment-1933229483.  The minimum required permission from what I see is `workflow` 
* Cherry picking conflicts could happen and needs to be handled manually https://github.com/pytorch/pytorch-canary/pull/194#issuecomment-1933142975
* ~Require a linked issue when cherry picking regressions, critical fixes, or fixing new features https://github.com/pytorch/pytorch-canary/pull/193#issuecomment-1933174520~ Relax this requirement to a suggestion

### CODE REVIEW

**Review by kit1980 — COMMENTED** [review]
Sometimes a revert commit needs to be cherry-picked, not a PR (I had to do it).
Is this going to be supported?

**Comment by malfet** [comment]
> Sometimes a revert commit needs to be cherry-picked, not a PR (I had to do it). Is this going to be supported?

I don't think this is a frequent case, and therefore can probably be done using traditional process

**Comment by huydhn** [comment]
> Sometimes a revert commit needs to be cherry-picked, not a PR (I had to do it). Is this going to be supported?

Yeah, this is not supported for now.  This is pretty rare, so we could add it in later if needed.

**Comment by atalman** [comment]
Looks good. I don't think, we really need this hard restriction, I think this could make tool harder to use:
- Require a linked issue when cherry picking regressions, critical fixes, or fixing new features

We will still be reviewing the cherry pick manually anyways and deciding if this is critical issue or not.

**Comment by huydhn** [comment]
> 2\. Would be nice to build some kind of error checking for this param: --onto release/2.2 to make sure we only allow cherry pick latest two branches release 2.2 or release 2.1 . I guess this could be done when: The second part after this is to update the release tracker with the info. This will be done in a subsequent PR.

Noted.  This could be done by checking the status of the cherry picking tracker issue I think.  Basically, if the issue tracking for 2.2.1 is open (and pinned), we accept `release/2.2` as the target branch.  Otherwise, the script will warn against cherry picking against older or future (non-existing) release branches.

**Comment by huydhn** [comment]
> 1. Looks good. I don't think, we really need this hard restriction, I think this could make tool harder to use.

I have relaxed this into a suggestion and tested it out on canary https://github.com/pytorch/pytorch-canary/pull/193#issuecomment-1935002555

**Review by atalman — APPROVED** [review]

**Pull request closed without merging**
