### PR TITLE
fix type error in hipify_python.py

### PR DESCRIPTION
**Pull request by arpancodes**
- [x] Fixed the Pyre type checking errors in `torch/utils/hipify/hipify_python.py`:
```
torch/utils/hipify/hipify_python.py:196:8 Incompatible variable type [9]: clean_ctx is declared to have type `GeneratedFileCleaner` but is used as type `None`.
torch/utils/hipify/hipify_python.py:944:4 Incompatible variable type [9]: clean_ctx is declared to have type `GeneratedFileCleaner` but is used as type `None`.
```

Fixing the issue: https://github.com/MLH-Fellowship/pyre-check/issues/78

### CODE REVIEW

**Comment by pradeep90** [comment]
Thanks for working on this, @arpancodes .

In general, when adding types, we want to avoid changing the code as far as possible. The only thing we should change is the type.

Here, we are changing both the order of the function parameters and the default value, which can cause unintended breakages. For example, Mypy fails on this PR: https://github.com/pytorch/pytorch/pull/66164/checks?check_run_id=3807933965

We just want to do the following in all the cases:

```python
def foo(x: int = None) -> None:
  ...


# should become

from typing import Optional
def foo(x: Optional[int] = None) -> None:  
    ...
```

**Comment by arpancodes** [comment]
@pradeep90 Got it... will work on it and push again.

**Comment by ngimel** [comment]
@0xedward, can you take care of landing it?

**Comment by 0xedward** [comment]
> can you take care of landing it?

@ngimel - yeah, definitely! :)

**Pull request closed without merging**
