### PR TITLE
Enable TensorPipe's SHM transport

### PR DESCRIPTION
**Pull request by lw**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#50760 Enable TensorPipe's SHM transport**

The SHM transport uses shared-memory-backed ringbuffers to transfer small payloads between processes on the same machine.

It was disabled in v1.6 due to a CMake mishap but we've since realized that it also doesn't work that well in docker and other setups. Enabling it here to see whether CircleCI fails.

Differential Revision: [D23814828](https://our.internmc.facebook.com/intern/diff/D23814828/)

### CODE REVIEW

**Review by mrshenli — COMMENTED** [review]
Do we need to add tests for this? E.g., by disabling higher priority channels?

**Comment by lw** [comment]
That's a good question, and a point I don't yet have a good idea about. It would be nice if we could run the entire PyTorch RPC suite with every transport and/or channel from TensorPipe (it would give us lots of coverage) but I don't think it's feasible to do so in the CI, since each new "configuration" of the TP agent would add ~25-30 minutes to the CI (for each pull request, by every developer).

In an ideal world we wouldn't need to do that, however, if we had a comprehensive and reliable per-backend test suite in TensorPipe's CI. Unfortunately we're not there yet. (And I don't think we'll ever be able to guarantee that it covers all the patterns and scenarios that could happen in PyTorch's RPC suite).

Hence... I don't know. Do you have any suggestions?

**Comment by lw** [comment]
BTW, I had re-pushed this PR today in order to finally debug the failure I had consistently seen last time, but now it seems to be gone. I didn't do anything to help fix it, so I'm a bit worried that it's just a lucky run and it will come out again... I'll maybe try to rerun some tests to see if that changes anything.

**Comment by mrshenli** [comment]
> Hence... I don't know. Do you have any suggestions?

One temporary solution might be adding tests to SLOW_TESTS for now, it won't block most PRs and only runs on master.

**Review by mrshenli — APPROVED** [review]
Do you wanna launch a ci-all for this PR?

**Pull request closed without merging**
