### PR TITLE
Use official NVML Python bindings

### PR DESCRIPTION
**Pull request by XuehaiPan**
Use the official NVML Python binding package [`nvidia-ml-py`](https://pypi.org/project/nvidia-ml-py), which is maintained by the NVIDIA NVML team.

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
All tests pass, so LGTM!

**Review by ZainRizvi — APPROVED** [review]

**Comment by malfet** [comment]
@ptrblck  can you please confirm which one is maintained by NVIDIA, as both packages lists nvidia.com as their official web-site, see  https://pypi.org/project/nvidia-ml-py/ vs https://pypi.org/project/pynvml/

Though, this change only affects CI, we are not using pynvml bindings in production by default (because I think package is not available on Anaconda)

**Review by ptrblck — APPROVED** [review]

**Pull request closed without merging**
