### PR TITLE
Fix `_make_wrapper_subclass`'s storage_offset handling

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #65819 CompositeImplicitAutograd compliance testing
* **#68268 Fix `_make_wrapper_subclass`'s storage_offset handling**

Previously, `_make_wrapper_subclass` ignored the storage offset it was
passed. This PR fixes that by updating TensorMaker::computeStorageSize()
and TensorMaker::make_tensor() to take into account storage_offset.

Test Plan:
- added test

Differential Revision: [D32396330](https://our.internmc.facebook.com/intern/diff/D32396330)

### CODE REVIEW

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32396330).

**Review by bdhirsh — APPROVED** [review]
Whoops, thanks for fixing!

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32396330).

**Review by albanD — APPROVED** [review]
Thanks!

**Pull request closed without merging**
