### PR TITLE
Show deprecation warning when stateful lambdas are used as kernels

### PR DESCRIPTION
**Pull request by smessmer**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#21885 Show deprecation warning when stateful lambdas are used as kernels**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D15867089/)

If a kernel is defined as a stateful lambda

```cpp
static auto registry = torch::RegisterOperators().op("my::op",
    [some_closure] (Tensor a) {...});
```

this can have very unexpected behavior when kernels are instantiated. There is no guarantee that the state is kept.

In the options based API, state is already disallowed:

```cpp
// this is already a compiler error with a nice message before this PR
static auto registry = torch::RegisterOperators().op("my::op", torch::RegisterOperators::options()
    .kernel([some_closure] (Tensor a) {...}));
```

but we can't disallow it in the non-options-based API for backwards compatibility reasons.

We can, however, show a deprecation warning. This is what this diff introduces.

Differential Revision: [D15867089](https://our.internmc.facebook.com/intern/diff/D15867089/)

### CODE REVIEW

**Comment by zdevito** [comment]
What uses of this API already exist that prevent us from removing it?

**Comment by smessmer** [comment]
@zdevito Nothing internally, but it's part of the public PyTorch 1.1 release.

**Comment by zdevito** [comment]
It think this is safe to break in 1.2. I doubt that someone has actually used this. I don't want to fill our library with functionality that just causes deprecation warnings.

**Comment by smessmer** [comment]
@zdevito I'm going to remove it in master right after 1.2 is released, it won't live for long.

But even though this is a corner case, I can imagine people doing things like


    int my_constant = 4;

    static auto registry = torch::RegisterOperators().op([&] (int64_t a) { return a + my_constant; });

and I don't want to break it without giving them a warning first. Migrating a project from PyTorch x that doesn't have deprecation warnings to PyTorch x+1 should (ideally) be absolutely safe.

**Review by zdevito — APPROVED** [review]

**Pull request closed without merging**
