### PR TITLE
Adds mruberry as superuser

### PR DESCRIPTION
**Pull request by mruberry**
(so PRs I approve can be merged)

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Comment by soumith** [comment]
this works at the moment, but SuperUser sounds like Core Maintainer -- i don't know what this practically entails.

We need to eventually discuss this to somehow reflect https://pytorch.org/docs/stable/community/persons_of_interest.html

**Comment by janeyx99** [comment]
I think we should rename superusers to "core reviewers" + introduce the idea of a reviewer who we trust to review code but do not necessarily have to be maintainers. Metamates would fall in this bucket naturally.

**Pull request closed without merging**
