### PR TITLE
Increase tolerance for test_adadelta

### LINKED ISSUE #69698: test_adadelta from test_optim.py fails on about 1/3 of seeds from exceeding the error threshold
### 🐛 Describe the bug

In the test_adadelta test we see the following failure:
```
FAIL: test_adadelta (__main__.TestOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 508, in wrapper
    fn(*args, **kwargs)
  File "test_optim.py", line 518, in test_adadelta
    self._test_basic_cases(
  File "test_optim.py", line 204, in _test_basic_cases
    self._test_state_dict(
  File "test_optim.py", line 192, in _test_state_dict
    self.assertEqual(weight, weight_cuda)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1611, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 5 element(s) (out of 50) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 4.1604042053222656e-05 (-0.7925148606300354 vs. -0.7925564646720886), which occurred at index (9, 1).
```

but only on about 1/3 of seeds. I determined this by looping over the test with a range of `torch.manual_seed`

To run the test:
`python test_adadelta.py -v -k test_adadelta`

[test_adadelta.zip](https://github.com/pytorch/pytorch/files/7687451/test_adadelta.zip)
I have confirmed this occurs on the public nightly pytorch wheel on a volta gpu as well as our latest 1.12 build.
`pip3 install torch -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html`

the errors that exceed the tolerance range from 1e-5 to 4e-3 so I am suggesting an increase of threshold to 4e-3, but wanted to discuss the issue and see if this issue or similar ones have been previously detected

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: glibc-2.31

Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-4.15.0-124-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.5.50
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] nvidia-dlprof-pytorch-nvtx==1.8.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.10.0 (nightly wheel)

cc @ezyang @gchanan @zou3519 @bdhirsh @vincentqb @jbschlosser @albanD @mruberry

### PR DESCRIPTION
**Pull request by puririshi98**
Fixes #69698

### CODE REVIEW

**Comment by puririshi98** [comment]
found on a 3080 4e-3 required to pass

**Comment by puririshi98** [comment]
interestingly dgx1 node w/ P100 gpus only requires tol of 3e-3

**Review by jbschlosser — CHANGES_REQUESTED** [review]
Thanks for the update! Note that our `TestCase` class handles precision and tolerance internally and can be configured for `test_adadelta` via the `@toleranceOverride` and `@precisionOverride` decorators. I think we'd prefer this solution as it avoids hard-coding the optimizer name before the checks. Some examples of using the decorators can be found in `test/test_linalg.py` and `test/test_modules.py`.

**Review by jbschlosser — APPROVED** [review]
LGTM! Thanks for the fix :)

**Comment by jbschlosser** [comment]
@puririshi98 To fix the failing checks, an import is needed in `test/test_optim.py`:
```
from torch.testing._internal.common_device_type import toleranceOverride
```

**Review by albanD — APPROVED** [review]
import needs fixing, good otherwise

**Review by jbschlosser — COMMENTED** [review]
@puririshi98 Also need to import `tol` and fix a couple lint issues (I think whitespace-related based on the checks) then good to go!

**Pull request closed without merging**
