### PR TITLE
Remove use of `.data` from optimizers

### PR DESCRIPTION
**Pull request by Enealor**
Removes all uses of `.data` from optimizers.

Or tries to.

### CODE REVIEW

**Comment by Enealor** [comment]
Failed tests are likely due to `backward` calls in the `closure` function, which is a use-case I didn't anticipate. (Should have checked the tests first.) I'll correct this with better placement of `torch.no_grad`.

**Comment by Enealor** [comment]
Current failing test is test_tensor_sharing (jit.test_data_parallel.TestDataParallel) with 
```
RuntimeError: Output 0 of BroadcastBackward is a view and its base or another view of its
base has been modified inplace. This view is the output of a function that returns multiple 
views. Such functions do not allow the output views to be modified inplace. You should 
replace the inplace operation by an out-of-place one.
```

The [test](https://github.com/pytorch/pytorch/blob/master/test/jit/test_data_parallel.py#L106) appears to be failing when the `forward` method is used on a shallow copy of an optimized model.  While this error makes some sense (the parameters have been modified in place), they should also not result after optimization.

**Comment by albanD** [comment]
Yes, the user-defined closure function should run in grad-mode.
If you want to decorate the full step function. You can also put the closure call into a `with torch.enable_grad():`.
But it looks ok like it is now.

You can check the discission in this PR: https://github.com/pytorch/pytorch/pull/30258 that I tried to do.
This should be better now. It is interesting though that this error is triggered. Because it should only happen when things are modified inplace, but I can't see the inplace operation in the test at first glance.

**Comment by Enealor** [comment]
That's a fair point about `torch.enable_grad`, and I think I prefer that solution. After reviewing the discussion, I think I'm running into the same issue as this is failing the same tests. As you mentioned before closing the PR, a modification is probably needed for distributed.

As for the inplace modification, I believe that it is happening during `optim.step`. As I speculated above, I believe the error is occurring as the weights are updated here, and the history is not tracked on that thread because of the `torch.no_grad`. However, this is causing an issue in the distributed version. 

I think I can test this by reverting to `p.data` for updating parameters while leaving the rest of the code unchanged.

**Comment by albanD** [comment]
Ho right !

Thinking out loud here:

Yes, this is exactly what happens:
- the weight is the base
- Broadcast make multiple views of it in a single Node 
- the optimizer modifies the base inplace
- if we try to use one of the outputs of Broadcast in a differentiable manner, the above error occurs.

So my new question, is why do we try to access the output of the original Broadcast multiple times?
It happens because we call `replicate` (that uses the Broadcast Function) only once. And then re-use the result of it multiple times.
In the "real" DataParallel module, the replicate is called at every forward pass and so the replicated module is not re-used.

cc @suo You seem to be the last one to touch this test. Is there a reason here why the replica is re-used and not re-recreated after the optimizer step? Does that match a special use that the jit is doing or it was just to speed up the test by calling replicate only once and we can just change the test to re-replicate for each forward?

**Comment by Enealor** [comment]
In order to move forward, I updated towards an incremental goal. I re-added uses of `.data` that are currently necessary due to version tracking. All other uses have been removed. The current form wraps `step` in a `no_grad` with `closure` wrapped in `enable_grad` to avoid other gradients from being tracked.

A future change could remove `.data` by either changing the test (if suitable) or using a new functionality to avoid the version tracking.

**Comment by albanD** [comment]
Thanks for the update!
It is a bit unsatisfying to leave them but it is a good idea to move it to another issue/PR

Let's wait for all the tests to run.

**Comment by Enealor** [comment]
I agree that it's a bit disappointing. I went with the current solution to justify my work thus far and reduce the effort needed for the next person.

I have considered implementing the feature needed, but I don't yet understand the internals of the `autograd` engine well enough to move forward on that.

**Review by albanD — APPROVED** [review]
This looks good.
Nothing special for the BC-breaking change here.
The main issue with parameter update is postponed to a later PR.

**Comment by vincentqb** [comment]
for reference: #30232

**Pull request closed without merging**
