### PR TITLE
Fix the Slice changes in ONNX

### PR DESCRIPTION
**Pull request by houseroad**
Address https://github.com/onnx/onnx/pull/63

Now, we don't need to describe every dimensions. :-)

### CODE REVIEW

**Comment by ezyang** [comment]
Hey, so reading your diff, I just realized that we don't actually need the C++ version of slice conversion anymore: we can just edit the Python symbolic directly. Do you want to merge this first, or port it back to Python?

**Comment by apaszke** [comment]
I moved it to the export pass a long time ago, because this allowed us to keep the complete indexing (including advanced) supported in PyTorch as a single op. If you move this to Python symbolic, it's going to appear as 10 different variants that you will have to support.

**Comment by ezyang** [comment]
@apaszke Maybe I'm misunderstanding something, but I thought that the plan we agreed on last week was that we would port the optimizer to work on ATen ops rather than ONNX ops, so the vagaries of the ONNX representation would no longer be relevant.

**Comment by apaszke** [comment]
Actually nvm. I think it would work if we moved it to symbolic after latest changes

**Comment by ezyang** [comment]
OK good. :)

**Comment by houseroad** [comment]
@ezyang I will update this PR, and move the logic to the python symbolic.

**Comment by houseroad** [comment]
As we discussed, the Index op logic is moved to python symbolic.

**Pull request merged**
