### PR TITLE
[inductor] Move loop ordering after fusion

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #108755
* __->__ #100331
* #108193

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang @soumith @anijain2305 @Xia-Weiwen

### CODE REVIEW

**Comment by shunting314** [comment]
Some updates on this:
1. I've added more detailed unit tests in `test_loop_ordering.py` for myself to understand in more depth how loop order, loop simplification, tiling, fusion etc works.
2. I've done a dashboard run and picked 3 HF models that get relatively large slow down (ElectraForCausalLM, XLNetLMHeadModel, AllenaiLongformerBase ).  Plan to dig more on those models to figure out what's the source of slowdown. E.g. for ElectraForCausalLM the speedup change from 1.995x -> 1.768x on my devgpu by applying the current PR. From the log we see number of fused nodes change from [342, 595] to [341, 592]  (item 1 for fwd graph, item 2 for bwd graph). For this model looks like we are not changing fusion a lot but cause large slow down. I'm suspecting we are currently picking worse loop order than baseline. Will spend more time on this to figure out.

**Comment by lezcano** [comment]
what's the state of this PR? It'd be fantastic to have this sort of change landed, as it would enable a fair amount of fusions

**Comment by shunting314** [comment]
> what's the state of this PR? It'd be fantastic to have this sort of change landed, as it would enable a fair amount of fusions

So we found some extra fusions added by this PR actually can cause slow down. We are working on adding the ability to benchmark a fusion decision so we can
- verify the gain from each of the existing fusion. A small portion of existing fusions may also cause slow down and we can skip them
- verify what kind of extra fusions bring by this PR can cause speedup/slowdown.

The fusion benchmark work is almost ready. Hopefully with that info, we can update this PR in a way that we can see overall perf wins.

**Comment by shunting314** [comment]
I changed the logic in `TritonScheduling.combine_reduction_hint` a bit. Previously if the schedule contains any non-contiguous pointwise node, we will use ReducitonHint.DEFAULT hint even if all the reduction nodes are inner reductions. Some kernel previously being codegened as persistent reduction may now be codegened as non-persistent reduction since ReductionHint.DEFAULT has stricter threshold compared to ReductionHint.INNER.

Take XLNetLMHeadModel as an example.

- With the PR, speedup is 1.814294x , absolute latency is 145.789030ms
- with the PR, speedup is 1.651361x, absolute latency is 161.760025ms

Dive a bit, I found kernel [triton_per_fused__softmax_backward_data__to_copy_index_add_mul_native_dropout_backward_new_zeros_20](https://gist.github.com/shunting314/cc5fc99a911fc2c7370f4d2dda853c40)  becomes a reduction kernel, and total latency increases from 25.5ms to 34ms . 

I change the code so that we fall back to ReductionHint.DEFAULT only if there are many enough non-contiguous pointwise nodes in the schedule.

Tested manually on a few models and will run a perf test.
- XLNetLMHeadModel
  - baseline 1.814294x
  - with the PR using the old heuristic: 1.651361x
  - with the PR using the new heuristic: 1.812906x
- fbnetv3_b
  - baseline 2.259274x
  - with the PR using the old heuristic: 2.223380x
  - with the PR using the new heuristic: 2.266071x

**Comment by lezcano** [comment]
What is the state of this PR @shunting314

**Comment by shunting314** [comment]
@lezcano we tried the following experiments
1. enable benchmark fusion to skip fusion that slow down things. Run perf test and record the speedup
2. upon 1, enable this PR. Run perf test and record the speedup
3. Compared 2 with 1, we don't see extra speedup so far.

We are not actively working on this right now. Keep this PR open since we will revisit later. Let us know if you have some thoughts that worth trying out.

**Pull request closed without merging**
