### PR TITLE
Add back cudaHostRegister to cudart API.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#34665 Add back cudaHostRegister to cudart API.**

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D20493861](https://our.internmc.facebook.com/intern/diff/D20493861)

### CODE REVIEW

**Comment by ezyang** [comment]
cc @adamlerer 

Dunno if this actually builds, if it doesn't I'll need to add some conversions for the raw pointer argument

**Review by albanD — APPROVED** [review]
Just an oversight when we converted to pybind?

**Comment by ezyang** [comment]
No, not an oversight; it's just that the CDLL surface API is technically larger than the surface we used in our library.

**Comment by albanD** [comment]
Interesting. Do you know who is using them? Should we add a small test to make sure we don't loose it again?

**Comment by ezyang** [comment]
@adamlerer let me know that his stuff broke due to lacking this. Not sure if we should actually test; if we do test we should make some commitment about how much of the CUDA api we will surface this way.

**Comment by albanD** [comment]
Ok, sounds good.

**Pull request closed without merging**
