### PR TITLE
[CI/CD] Disable split build

### PR DESCRIPTION
**Pull request by malfet**
See https://github.com/pytorch/pytorch/issues/138750

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Review by seemethere — CHANGES_REQUESTED** [review]
Were the submodule updates intentional?

**Review by kit1980 — APPROVED** [review]

**Comment by malfet** [comment]
> Were the submodule updates intentional?

If my linters still in place, mergebot would not allow me to do that unless I mention submodule in PR name

**Review by huydhn — APPROVED** [review]
LGTM!  Also cc @wdvr as I think we want to see how much this saves

**Comment by malfet** [comment]
Adding trunk and periodic, to make sure they are scheduled, and afterwards landing the change..

**Pull request closed without merging**
