### PR TITLE
[ROCm] Enable skipped ROCm unit tests

### LINKED ISSUE #51303: [ROCm] test_linalg.py failures after hipMAGMA integration
As requested by @malfet in https://github.com/pytorch/pytorch/pull/51238, this issue captures the newly failing tests after integrating hipMAGMA into the ROCm PyTorch build.  These tests were decorated with `@skipCUDAIfRocm` to proceed with the PR.  Debugging these skipped tests is the next step, and captured here with this issue.

Attached is full log.  Copied here is the summary.
[test_linalg.log](https://github.com/pytorch/pytorch/files/5890132/test_linalg.log)

```
ERROR: test_lobpcg_basic_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_addbmm_cuda_bfloat16 (__main__.TestLinalgCUDA)
FAIL: test_addmv_cuda_float16 (__main__.TestLinalgCUDA)
FAIL: test_baddbmm_cuda_bfloat16 (__main__.TestLinalgCUDA)
FAIL: test_bmm_cuda_bfloat16 (__main__.TestLinalgCUDA)
FAIL: test_cond_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_cond_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_cond_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_cond_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_det_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_det_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_det_logdet_slogdet_batched_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_inverse_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_inverse_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_inverse_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_inverse_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_lobpcg_ortho_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_lu_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_lu_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_lu_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_broadcasting_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_broadcasting_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_broadcasting_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_broadcasting_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_non_contiguous_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_non_contiguous_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_non_contiguous_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_lu_solve_batched_non_contiguous_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_lu_unpack_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_norm_dtype_cuda (__main__.TestLinalgCUDA)
FAIL: test_norm_fro_2_equivalence_old_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_broadcasting_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_broadcasting_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_broadcasting_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_broadcasting_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_non_contiguous_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_non_contiguous_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_non_contiguous_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_old_solve_batched_non_contiguous_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_solve_batched_non_contiguous_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_solve_batched_non_contiguous_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_solve_batched_non_contiguous_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_solve_batched_non_contiguous_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_solve_cuda_complex128 (__main__.TestLinalgCUDA)
FAIL: test_solve_cuda_complex64 (__main__.TestLinalgCUDA)
FAIL: test_solve_cuda_float32 (__main__.TestLinalgCUDA)
FAIL: test_solve_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_svd_lowrank_cuda_float64 (__main__.TestLinalgCUDA)
FAIL: test_tensorinv_non_contiguous_cuda_float32 (__main__.TestLinalgCUDA)
```

cc @jeffdaily @sunway513

### PR DESCRIPTION
**Pull request by dllehr-amd**
A number of ROCm tests were skipped via the skipCUDAIfRocm flag.
A majority of the testcases are now supported on the ROCm platform. This fix enabled all of the test_ops tests for ROCm and enables most Operators in  common_methods_invocations.py minus the SpectralFuncInfo class which still has some fft issues.

Partially Fixes #51303

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @amathews-amd

### CODE REVIEW

**Review by jeffdaily — COMMENTED** [review]
Would be self-documenting if we had a variable `BFLOAT16_ENABLED` instead of `(CUDA11OrLater or TEST_WITH_ROCM)`.  But perhaps that is for another PR.

**Comment by dllehr-amd** [comment]
@jeffdaily I agree... @amathews-amd  and I were debating a way to encapsulate this so we don't have to have this cumbersome approach.  I think the original intent would be that `CUDA11OrLater` would enable more types, hence it being a list, but from what I see it's entirely just `torch.bfloat16`

One issue I'd see with a generic `BFLOAT16_ENABLED` is something like https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_methods_invocations.py#L7308
where one case it's `CUDA11OrLater` when another (backwards dtype) it's `SM53OrLater`

I think we could do 
`BFLOAT16_ENABLED` for default dtypes, which would compare the values of `CUDA11OrLater` and `TEST_WITH_ROCM` and have a `BFLOAT16_BACKWARD_ENABLED` which would compare the `SM53OrLater` and `TEST_WITH_ROCM`

What do you think?  It would make it easier in the future if we decide to replace `TEST_WITH_ROCM` with a more version based approach.

**Comment by jeffdaily** [comment]
I do not expect the ROCm CI to pass here until #67225 is merged.  It blocks this PR.

**Comment by dllehr-amd** [comment]
The test1 job was failing with `HSA_STATUS_ERROR_OUT_OF_RESOURCES` which is exactly what @jeffdaily eluded to with #67225.  This PR enables more unit tests, which lend us to be more exposed to the resource issues.

**Comment by jeffdaily** [comment]
@dllehr-amd if you fix the newly conflicting file, your next commit should kick off a CI run with the new magma image.

**Review by jeffdaily — APPROVED** [review]
LGTM

**Comment by dllehr-amd** [comment]
Hey Folks, I have been trying to keep this PR up to date with the latest changes to `common_methods_invocations.py`  Is there a timeline when I'd be able to get this PR merged?  I'm trying to get a feel for when I should resolve the next batch of conflicts.   Thanks!

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Rebased the change, let's see what will happen

**Pull request closed without merging**
