### PR TITLE
Enable fp8 rowwise scaling kernel on cuda, TAKE 2: #125204 

### PR DESCRIPTION
**Pull request by drisspg**
# Summary
First PR got reverted and needed a redo

This pull request introduces an fp8 row-scaling kernel as an optional implementation for `scaled_mm`. The kernel selection is based on the scaling tensors of the inputs. For inputs `x` and `y` of shape `[M, K]` and `[K, N]` respectively, the following conditions must be met:
- `x`'s scale should be a 1-dimensional tensor of length `M`.
- `y`'s scale should be a 1-dimensional tensor of length `N`.

It's important to note that this kernel is not called "rowwise, columnwise" scaling because, although the scales for `y` are semantically along its columns, this implementation only supports the TN format. This means the scaling is along the faster-moving dimension, or the "row".

The following two PRs were required to enable local builds:
- [PR #126185](https://github.com/pytorch/pytorch/pull/126185)
- [PR #125523](https://github.com/pytorch/pytorch/pull/125523)

### Todo
We still do not build our Python wheels with this architecture.

@ptrblck @malfet, should we replace `sm_90` with `sm_90a`?

The NVRTC TMA shadowing feels wrong, but I a not sure the right way to spoof the symbol for this compilation unit:
https://github.com/pytorch/pytorch/pull/125204/files#r1586986954

#### ifdef

I tried to use : `#if !defined(USE_ROCM) && defined(CUDA_VERSION) && CUDA_VERSION >= 12000 && \
    defined(__CUDA_ARCH__) && __CUDA_ARCH__ > 900` to gate the building of the kernel. I was having a hell of a time with this.. so I am not really sure the right way to do this
    

Kernel Credit:
@jwfromm 

cc @yanbing-j @vkuzo @albanD @kadeng

### CODE REVIEW

**Review by yangsiyu007 — APPROVED** [review]

**Review by vkuzo — APPROVED** [review]

**Comment by xuzhao9** [comment]
This PR seems to break FBGEMM runtime: https://github.com/pytorch/benchmark/actions/runs/9704891003/job/26785961181

**Comment by drisspg** [comment]
@xuzhao9  this is interesting and I imagine it has to do with: https://github.com/pytorch/pytorch/pull/128989/files#diff-ac10d47f44dcf2fc2ec547d3dcdf796dea0498b4c3461e820152afb4cbdfae75R16-R58

**Comment by malfet** [comment]
@xuzhao9 following fixes the linker error for PyTorch, due to cutlass using driver API:
https://github.com/pytorch/pytorch/blob/0ffb17547efb3bd0bc553ff28a673fd5721c855a/aten/src/ATen/native/cuda/RowwiseScaledMM.cu#L14-L44

Perhaps fbgemm needs to add something similar? But we can not link PyTorch with libcuda

**Pull request closed without merging**
