### PR TITLE
[WIP] Cleanup arg{min, max}, with dim=None support

### PR DESCRIPTION
**Pull request by zasdfgbnm**
See also: https://github.com/pytorch/pytorch/pull/17103

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Looks legit. Unfortunately CI is busted today; will need a retest when things settle down.

**Comment by zasdfgbnm** [comment]
@ezyang Please don't land right now! the shape analysis is broken!

**Comment by ezyang** [comment]
Don't worry, it's just importing, not landing :)

**Comment by zasdfgbnm** [comment]
close in favor of https://github.com/pytorch/pytorch/pull/17103

**Pull request closed without merging**
