### PR TITLE
[foreach][Adamax] Minimize intermediates=1 to decrease peak memory

### PR DESCRIPTION
**Pull request by janeyx99**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104991
* #104988
* #104983

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Ok!

**Review by Skylion007 — APPROVED** [review]

**Comment by janeyx99** [comment]
@pytorchbot merge -f

other merge seems to be hanging and timing out even tho this PR has all green CI

**Pull request closed without merging**
