### PR TITLE
Avoid checking NoneType for cuda/cpu in MHA (abandon)

### PR DESCRIPTION
**Pull request by mikekgfb**
Summary: Avoid checking NoneType for cuda/cpu in MHA

Test Plan: sandcastle/ github ci/cd

Reviewed By: cpuhrsch

Differential Revision: D41191055

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]

**Review by HamidShojanazeri — APPROVED** [review]

**Comment by atalman** [comment]
removing from milestones since abandoned

**Pull request closed without merging**
