### PR TITLE
[sparse] Fix semi-structured sparse shape mismatch bug

### PR DESCRIPTION
**Pull request by jcaip**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #110583
* __->__ #110420

Summary:

Fixes: https://github.com/pytorch/pytorch/issues/110664

Currently, PyTorch incorrectly calculates the size of the returned
matrix when we pass a non-contiguous batched (>2d) input to the
semi-structured sparse subclass.

This is most common in MLP layers, where we have 2 linear layers back to back.

This will lead to an error like the following:
```
RuntimeError: shape '[20, 64, 64, 3072]' is invalid for input of size
62914560

```
Where the size of the sparse matmul result is off because we infer the
output shape with the wrong tensor shape.

This happens because of a bug where we did not update the subclass
tensor shape when doing transpose.
For semi-structured sparsity, transposing is a no-op where we just set
the boolean flag, but we forgot to also update the tensor shape.

Note that this error goes away in inference mode, since we avoid
decomposing the aten.linear op and handle shape folding ourselves,
which changes the execution path.

An alternative way to fix this issue is to set
TORCH_FLATTEN_LINEAR_3D=True, which will also fix this error.

Test Plan:
```
python test/test_sparse_semi_structured.py -k test_mlp

```

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Comment by cpuhrsch** [comment]
cc @albanD since I think this is a curious Tensor subclass "edge case"

**Comment by alexsamardzic** [comment]
LGTM (aside for test failing at the moment because of an import).

**Review by alexsamardzic — APPROVED** [review]

**Comment by albanD** [comment]
I'm confused. Is this just a big in the at::linear op? Why not just fix that instead of doing this?

**Comment by jcaip** [comment]
cc @albanD I can create an issue to triage this more precisely and fix it but this issue only arises for semi-structured sparse tensors and I'm not sure if it's a bug or a special case that needs to be handled. This fix seemed easier.

**Review by cpuhrsch — APPROVED** [review]

**Comment by jcaip** [comment]
cc @cpuhrsch @alexsamardzic 

Just FYI: Found the actual root cause of the bug, which was not in linear implementation but rather because we did not transpose our shapes in the tensor subclass.

**Pull request closed without merging**
