### PR TITLE
[CI] Fix runner determinator for ciflow

### PR DESCRIPTION
**Pull request by afrittoli**
In case of ciflow, runs are triggered by a tag which is created by @pytorchbot, which breaks the logic of the runner determinator.

In case of tag triggers, extract the pr number from the tag name, fetch the pr and extract the user login from it.

Both the inline and standalone python scripts have been updated for consistency.

### CODE REVIEW

**Comment by afrittoli** [comment]
Not sure what happened with the third_party modules, I need to remove those from the PR

**Review by malfet — APPROVED** [review]
Looks good to me, thank you for the fix.
@ZainRizvi do we have a task for removing the embedded script (or at the very least creating a lint rule that validates they are one and the same?)

**Comment by afrittoli** [comment]
> Looks good to me, thank you for the fix. @ZainRizvi do we have a task for removing the embedded script (or at the very least creating a lint rule that validates they are one and the same?)

Thanks @malfet, the script is [hitting a 404](https://github.com/pytorch/pytorch/actions/runs/9679701343/job/26706249267?pr=129500):

```
Output: '{"label_type": "", "message": "Failed to get issue. Falling back to meta runners. Exception: 404 {\"message\": \"Not Found\", \"documentation_url\": \"https://docs.github.com/rest/pulls/pulls#get-a-pull-request\", \"status\": \"404\"}"}'
```

so I need to understand what's going wrong. Unfortunately the exception does not say what returned 404, but I guess it must be the PR get.

**Comment by afrittoli** [comment]
Improved the error handling in `get_user` to get a bit more context on the issue.

**Comment by afrittoli** [comment]
I rebased the PR on top of @jeanschmidt changes, fixed the logic and it works nicely now.
In case of a CI job triggered by a tag, where the triggering actor is pytorch-bot, it now uses the correct username for the look-up:

```
  curr_branch="ciflow/trunk/129500"
  curr_ref_type="tag"
  echo "Current branch is '$curr_branch'"
  
  output="$(python[3](https://github.com/pytorch/pytorch/actions/runs/9682191770/job/26714666842?pr=129500#step:4:3) get_workflow_type.py \
    --github-token "$GITHUB_TOKEN" \
    --github-issue "$ISSUE_NUMBER" \
    --github-branch "$curr_branch" \
    --github-actor "$TRIGGERING_ACTOR" \
    --github-issue-owner "$ISSUE_OWNER" \
    --github-ref-type "$curr_ref_type" \
    --github-repo "$GITHUB_REPOSITORY")"
  
  echo "Output: '${output}'"
  
  LABEL_TYPE=$(echo "${output}" | jq -r '.label_type')
  echo "label-type=$LABEL_TYPE" >> "$GITHUB_OUTPUT"
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
    ISSUE_NUMBER: [5](https://github.com/pytorch/pytorch/actions/runs/9682191770/job/26714666842?pr=129500#step:4:5)132
    TRIGGERING_ACTOR: pytorch-bot[bot]
    ISSUE_OWNER: 
Current branch is 'ciflow/trunk/129500'
Output: '{"label_type": "", "message": "LF Workflows are disabled for , afrittoli. Using meta runners."}'
```

**Review by zxiiro — APPROVED** [review]

**Comment by zxiiro** [comment]
The test failures are unrelated to the runner determinator.

**Pull request closed without merging**
