### PR TITLE
[quant] Equalization Observer modifications

### PR DESCRIPTION
**Pull request by angelayi**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#59953 [quant] Equalization Observer modifications**
* #59747 [quant] Input Weight Equalization - prepare modifications
* #59739 [quant] EqualizationQConfig to distinguish input/output activations

Summary: Originally we structured the Input/WeightEqualizationObservers to function both as an equalization observer (recording the ranges of the input/weight columns), and quantization observer (recording the range of the input, range of the weight columns, and calculating the qparams). The graph would look something like: `x -> InpEqObs -> linear1`.

However, we have decided to split the functionality of the Input/WeightEqualizationObservers to serve just as an equalization observer and will insert it after the quantization observer: `x -> InpQuantObs -> InpEqObs -> linear1`. So now, we will no longer need the observers to calculate the qparams and store extra information as the input quantization observers will be able to take care of that.

During `convert`, after calculating the equalization scale, we will then update the input quantization observer's min/max values with the scaled min/max values calculated in the input equalization observer (by calling `calculate_scaled_minmax`). We will also manually scale the weight values by the equalization scale.

The following modifications were made to the equalization observers due to design changes:
- [InputEqualizationObserver] Replaced `calculate_qparams()` with `calculate_scaled_minmax()` since we will need to return the scaled min/max values to update the following input quantization observer
- [WeightEqualizationObserver] We no longer need a row observer since this will be taken care of by the following weight quantization observer
- [WeightEqualizationObserver] Following the previous comment, we no longer need to calculate the scaled qparam values. Instead, we will use the equalization scale to later scale the weights and the qparams will be taken care of by the weight quantization observer.

Test Plan: `python test/test_quantization.py
TestEqualizeFx.test_input_weight_eq_observer`

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D29135332](https://our.internmc.facebook.com/intern/diff/D29135332)

### CODE REVIEW

**Comment by angelayi** [comment]
@angelayi has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29135332).

**Comment by supriyar** [comment]
Looks good. Will we have a follow-up PR to add support for MinMaxObserver for weights (in addition to PerChannelMinMax)?

**Review by supriyar — APPROVED** [review]

**Comment by jerryzh168** [comment]
could we include more details about design changes (i.e. what the overall flow looks like after the change)? looking at the code it looks like we are removing some of the responsibilities from Input/Weight Equalization Observer so that it's dedicated to do scaling.

**Comment by angelayi** [comment]
@angelayi has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29135332).

**Comment by angelayi** [comment]
@angelayi has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29135332).

**Pull request closed without merging**
