### PR TITLE
Avoid direct reference to at::native::tensor from TensorDataContainer

### PR DESCRIPTION
**Pull request by iseeyuan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#47567 Avoid direct reference to at::native::tensor from TensorDataContainer**

The symbols under `aten::native` are native functions which are referenced by dispatcher at runtime. This guidance could help to decouple the native codes from the rest of pytorch. A direct benefit of this decoupling is mobile, where the native symbols can be selective compiled and linked, independent of the rest of pytorch codes. By doing this, we could have different flavors of native libs for different apps, while they share the same basic pytorch lib. The effort of this per-app selective build is blocked by pytorch lib directly referencing to native symbols. I'm trying to decouple this reference in mobile while keeping the original functionalities. 

An example of this decoupling is #46469, where we decouple the direct reference of aten::native symbols from ATen/ScalarOps. 

This PR is to decouple the native reference in TensorDataContainer. TensorDataContainer is a pytorch c++ api located in torch/csrc/api. For some reason the constructor is calling at::native::tensor() through at::tensor(). We keep the apis of at::native::tensor(), but pull the actual implementation to the ATen lib (in ATen/utils). Both TensorDataContainer and at::native::tensor() reference the same implementation. 

By doing this, it's possible to build Facebook internal apps in Android, with ATen/native selectively built to save the mobile size.

Differential Revision: [D24822517](https://our.internmc.facebook.com/intern/diff/D24822517)

### CODE REVIEW

**Review by glaringlee — COMMENTED** [review]
@iseeyuan 
Can I ask what is the motivation to this change?

**Comment by iseeyuan** [comment]
> @iseeyuan
> Can I ask what is the motivation to this change?

I was just about to update the PR summary after internal build test. Please refer to the summary for details.

**Comment by ezyang** [comment]
I must admit that I'm a bit perplexed by this PR. In torch/csrc/api/include/torch/detail/TensorDataContainer.h you have replaced a reference to `at::tensor` with `at::detail::tensor`. But this change should not have been necessary in the first place; `at::tensor` is not in the `native` namespace, so it should be safe to call anywhere in our library.

The end result probably looks the same: you move the implementation bits of `at::tensor` into ATen (rather than ATen_cpu), but shouldn't the call sites be preserved as `at::tensor`?

**Comment by iseeyuan** [comment]
> I must admit that I'm a bit perplexed by this PR. In torch/csrc/api/include/torch/detail/TensorDataContainer.h you have replaced a reference to `at::tensor` with `at::detail::tensor`. But this change should not have been necessary in the first place; `at::tensor` is not in the `native` namespace, so it should be safe to call anywhere in our library.
> 
> The end result probably looks the same: you move the implementation bits of `at::tensor` into ATen (rather than ATen_cpu), but shouldn't the call sites be preserved as `at::tensor`?

Good question! `at::tensor` in TensorDataContainer.h actually goes to at::native::tensor. I debugged the master code and the calling stack shows:
`
at::native::tensor(c10::ArrayRef<double>, c10::TensorOptions const&) TensorFactories.cpp:1099
torch::detail::TensorDataContainer::TensorDataContainer(c10::ArrayRef<double>) TensorDataContainer.h:147
...
`
in test_api. It verifies the linking error of undefined symbol of `at::native::tensor...` referenced from TensorDataContainer.h. 

I don't know exactly why `at::tensor` goes to `at::native::tensor`. Probably I missed some `using namespace` or some code-gen linkage?

**Comment by smessmer** [comment]
@ezyang just found that `at::tensor` and `at::native::tensor` are the same:

```
# git grep "using native::"
aten/src/ATen/templates/Functions.cpp:using native::tensor;
aten/src/ATen/templates/Functions.h:using native::tensor;
```

**Comment by ezyang** [comment]
This is really close. But there is still one more step to go. You moved the implementation to `at::detail`, and then reworked `at::native` to forward to the `at::detail` implementation. But that means that `at::tensor` still goes through `ATen_cpu`, so you had to rewrite call sites to `at::detail::tensor`. But just go to that `using at::native::tensor` and change it to `using at::detail::tensor` and then the call site doesn't have to be changed. Better yet, don't put this implementation in `at::detail` at all; put it in `at::` since that's where it's going to be public from.

**Comment by iseeyuan** [comment]
> This is really close. But there is still one more step to go. You moved the implementation to `at::detail`, and then reworked `at::native` to forward to the `at::detail` implementation. But that means that `at::tensor` still goes through `ATen_cpu`, so you had to rewrite call sites to `at::detail::tensor`. But just go to that `using at::native::tensor` and change it to `using at::detail::tensor` and then the call site doesn't have to be changed. Better yet, don't put this implementation in `at::detail` at all; put it in `at::` since that's where it's going to be public from.

Good point! I'll put it in `at::`, and remove
`
aten/src/ATen/templates/Functions.cpp:using native::tensor;
aten/src/ATen/templates/Functions.h:using native::tensor;
`

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
