### PR TITLE
Delete THNN direct binding code entirely

### PR DESCRIPTION
**Pull request by yifuwang**
Addresses #14895 and #20704.

This pull request removes nn's dependence on THNN direct binding and the binding itself, which is comprised of the logic for generating THNN/THCUNN wrapper and the logic for dispatching to the wrapper (type2backend).

test_nn passes locally.

### CODE REVIEW

**Comment by yifuwang** [comment]
@yf225 @ezyang the pull request is breaking a backward compatibility test. I'm not sure if I should remove the test because the change is considered BC-breaking in nature, or I should somehow keep the test happy. Could you please provide some suggestions?
```
May 30 19:17:45 ======================================================================
May 30 19:17:45 ERROR: test_module_backcompat (__main__.TestNN)
May 30 19:17:45 ----------------------------------------------------------------------
May 30 19:17:45 Traceback (most recent call last):
May 30 19:17:45   File "test_nn.py", line 577, in test_module_backcompat
May 30 19:17:45     m = torch.load(path)
May 30 19:17:45   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/serialization.py", line 387, in load
May 30 19:17:45     return _load(f, map_location, pickle_module, **pickle_load_args)
May 30 19:17:45   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/serialization.py", line 574, in _load
May 30 19:17:45     result = unpickler.load()
May 30 19:17:45 ImportError: No module named backends.thnn
```

**Comment by ezyang** [comment]
The crux of the matter is whether or not we deprecated the feature that no longer works. If we didn't we should deprecate it first, and remove later. It doesn't seem like there's any deprecation notice, so we might have to figure out how to fix this. I don't know how involved it is though. Can you do some basic investigation to start and post the results here?

**Comment by yifuwang** [comment]
Appreciate the input @ezyang! Just to clarify that this pull request is meant to be backward compatible in the sense that no public APIs are affected. The potential BC-breaking part is the implementation details that have trickled into pickled modules (e.g. `nn.backends.thnn._get_thnn_function_backend` in https://download.pytorch.org/test_data/linear.pt).

We should be able to maintain backward compatibility for pickled modules by keeping the skeleton of `nn.backends.thnn`. Just wanted to check whether we bother to do so.

**Comment by ezyang** [comment]
It's hard for me to say, but if it is not too much work, the
conservative thing is to make sure this BC keeps working.  Perhaps
@soumith or @colesbury would know better.

Excerpts from Yifu Wang's message of 2019-05-31 19:21:32 +0000:
> Appreciate the input @ezyang! Just to clarify that this pull request is meant to be backward compatible in the sense that no public APIs are affected. The potential BC-breaking part is the implementation details that have trickled into pickled modules (e.g. `nn.backends.thnn._get_thnn_function_backend` in https://download.pytorch.org/test_data/linear.pt).
> 
> We should be able to maintain backward compatibility for pickled modules by keeping the skeleton of `nn.backends.thnn`. Just wanted to check whether we bother to do so.
>

**Comment by yifuwang** [comment]
54fc5cb is my attempt to address the backward compatibility issue for modules pickled with older versions of PyTorch. All pickled modules that were working prior to this pull request will still be working with one exception: if a module directly calls into functions provided by `THNNFunctionBackend` at the time it was pickled, the module will not be usable if a user applies a patch dumped from the pickled module to their local PyTorch installation.

@ezyang @colesbury @soumith can you please comment on whether this level of backward compatibility is acceptable? Thanks!

**Comment by soumith** [comment]
@yifuwang this looks fine to me

**Review by tanyongseng — APPROVED** [review]

**Pull request closed without merging**
