### PR TITLE
[quant][embedding qat] Add benchmarks for QAT Embedding+EmbeddingBag

### LINKED ISSUE #61865: [quant] Support QAT for Embedding/EmbeddingBag
Currently we only support PTQ for embedding modules https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/embedding_ops.py

This issue tracks the support to 
1. add QAT modules for Embedding/EmbeddingBag modules
2. Do the module swap in eager mode to use these modules
3. Update FX quantization flow to support the new modules

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

### PR DESCRIPTION
**Pull request by b-koopman**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #67945
* #66985
* #68296
* #68390
* __->__ #66560

Summary:

Add benchmarks for QAT Embedding+EmbeddingBag ops to better understand performance implication of QAT for the entire embedding weight.
Also add benchmark for fp32 Embedding in order to get comparison point for QAT Embedding vs. FP32 Embedding.

Test Plan:

Collected benchmarks for comparison of forward and gradient tests for min and max test data sizes.
Collected on: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz

EmbeddingBag

```
\# Benchmarking PyTorch: embeddingbag
\# Mode: Eager
\# Name: embeddingbag_embeddingbags2300_dim64_modesum_input_size64_offset0_sparseFalse_include_last_offsetFalse_cpu
\# Input: embeddingbags: 2300, dim: 64, mode: sum, input_size: 64, offset: 0, sparse: False, include_last_offset: False, device: cpu
Forward Execution Time (us) : 61.031

\# Benchmarking PyTorch: embeddingbag
\# Mode: Eager
\# Name: embeddingbag_embeddingbags2300_dim64_modesum_input_size64_offset0_sparseFalse_include_last_offsetFalse_cpu
\# Input: embeddingbags: 2300, dim: 64, mode: sum, input_size: 64, offset: 0, sparse: False, include_last_offset: False, device: cpu
Backward Execution Time (us) : 167.128

\# Benchmarking PyTorch: qatEmbeddingBag
\# Mode: Eager
\# Name: qatEmbeddingBag_embeddingbags2300_dim64_modesum_input_size64_offset0_sparseFalse_include_last_offsetFalse_cpu
\# Input: embeddingbags: 2300, dim: 64, mode: sum, input_size: 64, offset: 0, sparse: False, include_last_offset: False, device: cpu
Forward Execution Time (us) : 1160.651

\# Benchmarking PyTorch: qatEmbeddingBag
\# Mode: Eager
\# Name: qatEmbeddingBag_embeddingbags2300_dim64_modesum_input_size64_offset0_sparseFalse_include_last_offsetFalse_cpu
\# Input: embeddingbags: 2300, dim: 64, mode: sum, input_size: 64, offset: 0, sparse: False, include_last_offset: False, device: cpu
Backward Execution Time (us) : 537.876

```

Embedding

```
\# Benchmarking PyTorch: embedding
\# Mode: Eager
\# Name: embedding_num_embeddings2300_embedding_dim64_input_size64_cpu
\# Input: num_embeddings: 2300, embedding_dim: 64, input_size: 64, device: cpu
Forward Execution Time (us) : 20.819

\# Benchmarking PyTorch: embedding
\# Mode: Eager
\# Name: embedding_num_embeddings2300_embedding_dim64_input_size64_cpu
\# Input: num_embeddings: 2300, embedding_dim: 64, input_size: 64, device: cpu
Backward Execution Time (us) : 173.123

\# Benchmarking PyTorch: qatEmbedding
\# Mode: Eager
\# Name: qatEmbedding_num_embeddings2300_embedding_dim64_input_size64_cpu
\# Input: num_embeddings: 2300, embedding_dim: 64, input_size: 64, device: cpu
Forward Execution Time (us) : 1104.410

\# Benchmarking PyTorch: qatEmbedding
\# Mode: Eager
\# Name: qatEmbedding_num_embeddings2300_embedding_dim64_input_size64_cpu
\# Input: num_embeddings: 2300, embedding_dim: 64, input_size: 64, device: cpu
Backward Execution Time (us) : 556.563

```

Additional benchmarks can be run like (as per `operator_benchmark/README.md`):
`python -m pt.embeddingbag_test --test_name <test name> # fp32 embedding/embedding_bag benchmarks`
`python -m pt.qatembedding_ops_test.py --test_name <test name> # QAT embedding/embedding_bag benchmarks`

rebase

fix linter error

Fix embedding bench

Differential Revision: [D31618282](https://our.internmc.facebook.com/intern/diff/D31618282)

### CODE REVIEW

**Review by HDCharles — APPROVED** [review]
looks good outside of the lint errors.

**Review by supriyar — APPROVED** [review]
lg, could you also update the testplan to show how you ran the benchmarks and the numbers you see? Might be useful for the future

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31618282).

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31618282).

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31618282).

**Pull request closed without merging**
