### PR TITLE
[fx] Make Tracer._autowrap_search a list of module names

### PR DESCRIPTION
**Pull request by SplitInfinity**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #57221 [package] (Un)package GraphModules using corresponding Tracer
* **#57220 [fx] Make Tracer._autowrap_search a list of module names**

**Summary**
This commit makes `Tracer._autowrap_search` a list of module names
instead of module objects so that `Tracer` instances can be pickled and
stored into packages along with the `GraphModules` that they helped
generate.

**Test Plan**
Existing FX tests?

Differential Revision: [D28164470](https://our.internmc.facebook.com/intern/diff/D28164470)

### CODE REVIEW

**Review by jamesr66a — COMMENTED** [review]
This is BC-breaking. Can you leave in support for `autowrap_modules` to also accept a list of Modules and convert those to the module names before passing into the `importlib` stuff?

**Comment by SplitInfinity** [comment]
> This is BC-breaking. Can you leave in support for `autowrap_modules` to also accept a list of Modules and convert those to the module names before passing into the `importlib` stuff?

I left the constructor unchanged (since that change is not actually necessary to achieve my goal) but converted the internal state to a list of module names (obtained via `.__name__` from the list of modules passed to `__init__`). How does that sound?

**Review by jamesr66a — APPROVED** [review]
Great, thanks!

**Comment by SplitInfinity** [comment]
@splitinfinity has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28164470).

**Pull request closed without merging**
