### PR TITLE
[MPS] Handle output shape for empty input in binary ops

### PR DESCRIPTION
**Pull request by abhudev**
Output of input shape [0,1,2] should be [0,1,2], not [0] i.e. delay returning from empty input condition to resize/reshape the output accordingly

### CODE REVIEW

**Review by DenisVieriu97 — APPROVED** [review]
looks good - please take a look over the lint issues

**Comment by kulinseth** [comment]
@abhudev , can you fix the lint issues.

**Comment by abhudev** [comment]
Removed the trailing spaces

**Review by kulinseth — APPROVED** [review]
Looks good.

**Pull request closed without merging**
