### PR TITLE
DilatedMaxPool: expand incomplete kernel_size for the C++ API

### LINKED ISSUE #22032: max_pool2d_with_indices: internal error
I get an internal error while running examples/cpp/mnist/

```
$ ./mnist
CUDA available! Training on GPU.
terminate called after throwing an instance of 'c10::Error'
  what():  max_pool2d_with_indices: internal error: all IntArrayRef sizes must be 2 (max_pool2d_with_indices_out_cuda_template at /home/mahmood/cactus/pt/pytorch/aten/src/ATen/native/cuda/DilatedMaxPool2d.cu:155)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6c (0x7f5276e692cc in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: at::native::(anonymous namespace)::max_pool2d_with_indices_out_cuda_template(at::Tensor&, at::Tensor&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool) + 0x163d (0x7f527bfa666d in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #2: at::native::max_pool2d_with_indices_cuda(at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool) + 0x660 (0x7f527bfa8590 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x368b894 (0x7f527a708894 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #4: torch::autograd::VariableType::max_pool2d_with_indices(at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool) const + 0x4a8 (0x7f527a0a3e08 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #5: at::native::max_pool2d(at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool) + 0xbd (0x7f52783bddad in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #6: at::TypeDefault::max_pool2d(at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool) const + 0xb4 (0x7f5278834bc4 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #7: torch::autograd::VariableType::max_pool2d(at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool) const + 0x375 (0x7f527a1b0ed5 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x8f1af (0x5584dd1eb1af in ./mnist)
frame #9: Net::forward(at::Tensor) + 0x102 (0x5584dd1f04ea in ./mnist)
frame #10: void train<torch::data::StatelessDataLoader<torch::data::datasets::MapDataset<torch::data::datasets::MapDataset<torch::data::datasets::MNIST, torch::data::transforms::Normalize<at::Tensor> >, torch::data::transforms::Stack<torch::data::Example<at::Tensor, at::Tensor> > >, torch::data::samplers::SequentialSampler> >(int, Net&, c10::Device, torch::data::StatelessDataLoader<torch::data::datasets::MapDataset<torch::data::datasets::MapDataset<torch::data::datasets::MNIST, torch::data::transforms::Normalize<at::Tensor> >, torch::data::transforms::Stack<torch::data::Example<at::Tensor, at::Tensor> > >, torch::data::samplers::SequentialSampler>&, torch::optim::Optimizer&, unsigned long) + 0x1b9 (0x5584dd1f56ac in ./mnist)
frame #11: main + 0x608 (0x5584dd1eb942 in ./mnist)
frame #12: __libc_start_main + 0xe7 (0x7f52762adb97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #13: _start + 0x2a (0x5584dd1e9a8a in ./mnist)

Aborted (core dumped)
```
gcc and nvcc versions are

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

### PR DESCRIPTION
**Pull request by skrah**
Fixes #22032.

### CODE REVIEW

**Review by mrshenli — APPROVED** [review]
Shall we add a test to cover the case  where `max_pool2d` and `max_pool3d` passes an integer as the kernel size?

**Review by mrshenli — APPROVED** [review]
Thanks for fixing!

**Comment by skrah** [comment]
I guess we should add tests if this is the official C++ API (I'm not sure if it is documented in this level of detail).

Looking at #20866, the JIT does extra work to expand single integer arguments into lists, see e.g.:

```
 @weak_script
def _max_pool2d(input, kernel_size, stride=None, padding=0, dilation=1,
                ceil_mode=False, return_indices=False):
    # type: (Tensor, BroadcastingList2[int], Optional[BroadcastingList2[int]], BroadcastingList2[int], BroadcastingList2[int], bool, bool) -> Tensor  # noqa
    if stride is None:
        stride = torch.jit.annotate(List[int], [])
    return torch.max_pool2d(
        input, kernel_size, stride, padding, dilation, ceil_mode)
```

So the JIT takes care not to pass single integers to `torch::max_pool2d`.  The question I have is whether it does so for internal convenience or because the C++ API was originally intended that way.

[I think it is reasonable to permit single integers in the C++ API, but it would be nice to sync behavior with the JIT.]

**Comment by mrshenli** [comment]
> I guess we should add tests if this is the official C++ API.

Good point! I am inclined to think C++ should have the same behavior as Python, i.e., auto-expanding kernel_size, but I am not sure either. @gchanan has this been discussed before?

**Comment by skrah** [comment]
Agreed, I also think that C++ should have the same behavior as Python, mostly because a lot of other Python idioms work on the C++ level.

**Comment by gchanan** [comment]
I think ideally it would work the same way in C++.

**Comment by soumith** [comment]
I'm landing the PR. if you want to send tests, please do so in a follow-up PR

**Comment by skrah** [comment]
Yes, tests will be part of #22277 (more functions need to be changed in ATen).

**Pull request closed without merging**
