### PR TITLE
improve LayerNorm bfloat16 performance on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74410
* #69067
* #73844
* __->__ #71376

Differential Revision: [D33775542](https://our.internmc.facebook.com/intern/diff/D33775542)

### CODE REVIEW

**Comment by mingfeima** [comment]
Now `LayerNorm` uses welford algorithm to calculate mean and rstd per input slice, which introduces more arithmetic operations. This patch caches the input slice in float and do welford updated in float which will improve performance by (reduce dtype conversion) and reduce rounding error as well.

Note: this patch uses a template specification for \<BFloat16\>, for the ease of future mixed dtype enabling.

Below shows benchmark data on both avx512 and avx2 machine.

#### avx512 single core run
```bash
(before)
LayerNorm((1024,), eps=1e-05, elementwise_affine=True) : 32x128x1024: fp32: 7.366 ms; bf16: 40.683 ms

(after)
LayerNorm((1024,), eps=1e-05, elementwise_affine=True) : 32x128x1024: fp32: 7.383 ms; bf16: 6.587 ms
```

#### avx2 single core run
```bash
(before)
LayerNorm((1024,), eps=1e-05, elementwise_affine=True) : 32x128x1024: fp32: 11.349 ms; bf16: 55.042 ms

(after)
LayerNorm((1024,), eps=1e-05, elementwise_affine=True) : 32x128x1024: fp32: 11.307 ms; bf16: 10.265 ms
```

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33775542).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33775542).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33775542).

**Review by VitalyFedyunin — COMMENTED** [review]
Code looks good, but it would be nice to have correctness tests.

**Comment by mingfeima** [comment]
> Code looks good, but it would be nice to have correctness tests.

@VitalyFedyunin, correctness test already exists in test_nn.py:
```python
    def test_LayerNorm_general(self, device):
        self._test_LayerNorm_general(device)

        if self.device_type == 'cuda' or self.device_type == 'cpu':
            self._test_LayerNorm_general(device, dtype=torch.bfloat16)

        if self.device_type == 'cuda':
            self._test_LayerNorm_cuda_half(device)
```

**Comment by mingfeima** [comment]
> Code looks good, but it would be nice to have correctness tests.

@VitalyFedyunin, correctness test already exists in test_nn.py:
```python
    def test_LayerNorm_general(self, device):
        self._test_LayerNorm_general(device)

        if self.device_type == 'cuda' or self.device_type == 'cpu':
            self._test_LayerNorm_general(device, dtype=torch.bfloat16)

        if self.device_type == 'cuda':
            self._test_LayerNorm_cuda_half(device)
```

**Comment by mingfeima** [comment]
this stack is newly rebased.

to ease the process of review, i moved #73953 to another stack (which is about improving performance of Softmax and LogSoftmax).

**Comment by mingfeima** [comment]
this stack is newly rebased.

to ease the process of review, i moved #73953 to another stack (which is about improving performance of Softmax and LogSoftmax).

**Review by frank-wei — APPROVED** [review]
looks good to me.

**Pull request closed without merging**
