### PR TITLE
[ROCm] Increase hipBLASLt default workspace size

### PR DESCRIPTION
**Pull request by naromero77amd**
This PR increases hipBLASLt default workspace size to 76 MB which is the recommended default. This PR does not contain any bug fixes. 

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by jeffdaily — APPROVED** [review]

**Review by eqy — APPROVED** [review]
Approving but note that historically this setting is sticky as it would break e.g., Meta internal workloads that are on the edge of memory usage.

**Review by jeffdaily — APPROVED** [review]

**Comment by jeffdaily** [comment]
> Approving but note that historically this setting is sticky as it would break e.g., Meta internal workloads that are on the edge of memory usage.

Going from 32MB to 76MB for the tunableop case is too much?  For the non-tunable path, the 8MB default was too small for adequate performance.  Should have also been at least 32MB.  76MB is necessary for highest-performing algorithms.

**Comment by eqy** [comment]
We've had the 31MiB increase (1 -> 32 MiB) get reverted on the cuBLASLt side a few times, see e.g., #120925

**Comment by naromero77amd** [comment]
> We've had the 31MiB increase (1 -> 32 MiB) get reverted on the cuBLASLt side a few times, see e.g., #120925

Is there some Meta workload that can be run before this is merged in? I was planning on merging in once the CI checks out.

**Pull request closed without merging**
