### PR TITLE
[pytorch] blas gemm fix for k=0

### PR DESCRIPTION
**Pull request by ggoossen**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#33419 [pytorch] blas gemm fix for k=0**

These conditions are for the specific implementation, the fallback implementation works without these checks. So use that if any of these checks isn't true.

Differential Revision: [D19941103](https://our.internmc.facebook.com/intern/diff/D19941103/)

### CODE REVIEW

**Review by VitalyFedyunin — COMMENTED** [review]
Looks good, but could you please add tests to make sure we can run with this values (instead of erroring out)

**Comment by ggoossen** [comment]
@VitalyFedyunin I couldn't find the place where this is explicitly tests, where should I add the test?

**Comment by VitalyFedyunin** [comment]
blas mm called from the `addmm` operator. So you can probably take `test_addmm` test as example and place yours nearby.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by ezyang** [comment]
This seems to have broken XLA.

**Pull request closed without merging**
