### PR TITLE
modify ipex backend

### PR DESCRIPTION
**Pull request by jiayisunx**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99499

The ipex backend of torch.compile calls ipex.compile instead of torch.jit.trace and torch.jit.freeze. ipex.compile will handle the compilation process for IPEX internally. 

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @desertfire

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
Can you add the motivation of this PR in the description? Also, is the new API available publicly? We need to make sure the ipex backend works publicly.

**Comment by jiayisunx** [comment]
@jansel, can you please review this PR? thanks!

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
