### PR TITLE
Add MaskedTensor support to *_like API

### PR DESCRIPTION
**Pull request by nowtryz**

### CODE REVIEW

**Comment by nowtryz** [comment]
Hi @soulitzer or @cpuhrsch,

The PR is ready to merge.

**Review by cpuhrsch — DISMISSED** [review]

**Comment by nowtryz** [comment]
I am not sure if I can use this command but as the change were approved:
@pytorchbot merge

**Comment by nowtryz** [comment]
Guessed right, I cannot!
@cpuhrsch I fixed the linting/docs issued, it should be correct when the ci finishes. Could you retry merging please?

**Comment by nowtryz** [comment]
Wow ok that's very difficult to fix the linting issues when I cannot run the linters in my environment... Anyway, that should be good now @cpuhrsch .

**Comment by cpuhrsch** [comment]
@nowtryz - Hm, you should be able to use lintrunner, see https://github.com/pytorch/pytorch/blob/main/CONTRIBUTING.md#local-linting and https://github.com/pytorch/pytorch/wiki/lintrunner . Let me know if this doesn't work.

**Comment by jeanschmidt** [comment]
Seems that this PR introduced:

```
FAILED [6.0509s] test_public_bindings.py::TestPublicBindings::test_correct_module_names - AssertionError: False is not true : All the APIs below do not meet our guidelines for public API from https://github.com/pytorch/pytorch/wiki/Public-API-definition-and-documentation.
Make sure that everything that is public is expected (in particular that the module has a properly populated `__all__` attribute) and that everything that is supposed to be public does look public (it does not start with `_` and has a `__module__` that is properly populated).
```

**Comment by nowtryz** [comment]
Thank you @jeanschmidt,
Fixed the binding, can you merge again?

**Review by cpuhrsch — DISMISSED** [review]

**Pull request closed without merging**
