### PR TITLE
[chalf] relax tolerance : conv_transpose2d

### LINKED ISSUE #87332: DISABLED test_complex_half_reference_testing_nn_functional_conv_transpose2d_cuda_complex32 (__main__.TestCommonCUDA)
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/FAILED%20test_ops.py%3A%3ATestCommonCUDA%3A%3Atest_complex_half_reference_testing_nn_functional_conv_transpose2d_cuda_complex32)).

Fails flakily but not within the same run

### PR DESCRIPTION
**Pull request by kshitij12345**
Fixes https://github.com/pytorch/pytorch/issues/87332

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
Change looks fine, but do we have a test for this in CI? I didn't manage to find the relevant skip.

**Comment by kshitij12345** [comment]
Following test was marked as flaky. This should work post the PR.
https://github.com/pytorch/pytorch/blob/314e7c37c32d381124036fcb64bde5e9bd7f3bf7/test/test_ops.py#L1064-L1068

**Review by lezcano — APPROVED** [review]
Flakiness is tricky. Let's then merge this and hope for the best.
If this keeps coming up, then our best bet may be to ssh into one of the CI runners and test this properly there changing the seed.

**Pull request closed without merging**
