### PR TITLE
[Reland] fix building errors on FreeBSD

### PR DESCRIPTION
**Pull request by cyyever**
PR #105897 was reverted because we may have a function name conflict. This PR  renames the function.

cc @kit1980 @PaliC

### CODE REVIEW

**Comment by kit1980** [comment]
I really don't think that was a name conflict.

**Comment by cyyever** [comment]
> I really don't think that was a name conflict.

Two possibles, one is name conflict, the other is usages of __FreeBSD__ macro somewhere in META code.

**Comment by cyyever** [comment]
Because I have no access to META code, need your kind help

**Comment by kit1980** [comment]
The error was a value 9 in some test expecting 5, I don't think it's related to the PR.
We'll figure it out.

**Review by Skylion007 — APPROVED** [review]

**Review by Skylion007 — CHANGES_REQUESTED** [review]
Accidental approval on reading the comments that the initial issue was not correct and it's some other issue in meta code.

**Comment by cyyever** [comment]
@Skylion007 wait until further results.

**Review by malfet — APPROVED** [review]
Looks good to me, but please do not land the PR until we figure out what is wrong with it internally

**Pull request closed without merging**
