### PR TITLE
Refactoring quantized op tests to combine test classes

### PR DESCRIPTION
**Pull request by HDCharles**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #68282
* #68176

Summary: Combined 3 Dynamic quantized op test classes into 1

Test Plan: python test/test_quantization.py TestDynamicQuantizedOps

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D32402163](https://our.internmc.facebook.com/intern/diff/D32402163)

### CODE REVIEW

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32402163).

**Review by jerryzh168 — APPROVED** [review]
great, thanks!

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32402163).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32402163).

**Pull request closed without merging**
