### PR TITLE
Treat layout / pin_memory consistently across creation refs

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #85333

### CODE REVIEW

**Review by mruberry — APPROVED** [review]
Cool! Ship it!

**Comment by lezcano** [comment]
@ngimel could you approve this one?

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
@lezcano is dynamo test error pre-existing?

**Pull request closed without merging**
