### PR TITLE
Add guard_size_oblivious to vector_norm

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #126772
* #126771

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by lezcano — APPROVED** [review]

**Review by Skylion007 — APPROVED** [review]

**Comment by andife** [comment]
was it merged?

**Comment by ezyang** [comment]
yup

**Pull request closed without merging**
