### PR TITLE
fix torch::deploy OSS CI: previous the tests for torch::deploy will be skipped

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #67286

We match build environment with linux-xenial-cuda11.3 in .jenkins/pytorch/build.sh but match against linux-xenial-cuda11.1 in .jenkins/pytorch/test.sh.

I suspect this mismatch may cause the torch::deploy tests not being run.  Send this PR out and I will verify in CI.

Differential Revision: [D31939631](https://our.internmc.facebook.com/intern/diff/D31939631)

### CODE REVIEW

**Review by suo — APPROVED** [review]
pre-emptively accepting, but please address lints before landing

**Comment by shunting314** [comment]
The  torch::deploy test is still not running in CI.

I found that in test.sh we have code like:
```
elif [[ "${BUILD_ENVIRONMENT}" == *-test1 || "${JOB_BASE_NAME}" == *-test1 || ("${SHARD_NUMBER}" == 1 && $NUM_TEST_SHARDS -gt 1) ]]; then
  if [[ "${BUILD_ENVIRONMENT}" == *linux-xenial-cuda11.3*-test1* ]]; then
    test_torch_deploy
  fi
```

I found there is only one CI job that runs with BUILD_ENVIRONMENT matches *linux-xenial-cuda11.3* , the job is named linux-xenial-cuda11.3-py3.6-gcc7 and it's BUILD_ENVIRONMENT is named linux-xenial-cuda11.3-py3.6-gcc7 . 

Note that the BUILD_ENVIRONMENT for this job does not contains the 'test1' sub string, so the condition check surrounding test_torch_deploy will never be true.

I'll loose the check a bit to make the tests run. cc @suo

**Comment by shunting314** [comment]
@shunting314 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31939631).

**Comment by shunting314** [comment]
I'm able to let torch::deploy unit test being run in the CI now. However there is a broken unit tests.

TorchpyTest.FxModule causes segfault. I verified that the test cause can pass in FB build. (revision 8cb146b2f ). Not sure what specific about OSS build that causes segfault.

**Comment by shunting314** [comment]
@suo  in case you knows, is there anything specific about FX that cause different behavior on FB build and OSS build?

**Comment by suo** [comment]
fx should be exactly the same, it seems like it might be a latent bug in
deploy. Worth investigating!

**Pull request closed without merging**
