### PR TITLE
[PyTorch] IValue(const c10::Scalar&) improvements

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #76266
* __->__ #72551

Don't delegate to `operator=` for construction. Catch hypothetical addition of a new Scalar type via debug assertion rather than checking in prod.

Differential Revision: [D34090560](https://our.internmc.facebook.com/intern/diff/D34090560/)

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by swolchok** [comment]
@pytorchbot merge -f

forcing because the "new" failure is BC test spuriously failing

**Pull request closed without merging**
