### PR TITLE
support non-contiguous tensor in bilinear

### PR DESCRIPTION
**Pull request by joerg-de**

### CODE REVIEW

**Comment by joerg-de** [comment]
test code

import torch
import torch.nn as nn
torch.manual_seed(1)
m = nn.Bilinear(10, 11, 5)
input1 = torch.randn(2, 10,4,3)
input2 = torch.randn(2, 11,4,3)
input1 = input1.transpose(1,3)
input2 = input2.transpose(1,3)
print(input1.size())
print(input2.size())
output = m(input1, input2)
print(output)

**Comment by joerg-de** [comment]
any updates? @jerryzh168 @t-vi

**Comment by VitalyFedyunin** [comment]
Please include update tests code page to cover this option. Please include me back as reviewer if you are still interested to land this PR.

**Comment by joerg-de** [comment]
I have added the test Code. @VitalyFedyunin

**Review by t-vi — APPROVED** [review]
Looks good to merge. Thank you @joerg-de .

**Comment by t-vi** [comment]
@jerryzh168 Do you want to try to land? Seems good & low risk & with test & good on CI.

**Comment by joerg-de** [comment]
any updates? @t-vi @jerryzh168

**Comment by t-vi** [comment]
Thank you for the prod. Let's see if the PyTorch bot still works.

**Review by albanD — APPROVED** [review]
LGTM

**Comment by albanD** [comment]
@joerg-de could you rebase this on top of master please to make sure all tests pass?

**Pull request closed without merging**
