### PR TITLE
Enable UFMT on test/test_jit_fuser_te.py

### PR DESCRIPTION
**Pull request by huniu20**
Part of #123062 
cc @ezyang

### CODE REVIEW

**Comment by ezyang** [comment]
clean but looks like you have to fix it more

```
diff --git b/test/test_jit_fuser_te.py a/test/test_jit_fuser_te.py
index cf7fb7d77e3..83e52907a8a 100644
--- b/test/test_jit_fuser_te.py
+++ a/test/test_jit_fuser_te.py
@@ -1442,8 +1442,14 @@ class TestTEFuser(JitTestCase):
             except Exception as e:
                 raise RuntimeError(
                     " ".join(
-                        ["Failed:", str(self_dtype), op.__name__, device, str(size)]
-                    )  # noqa: F821
+                        [
+                            "Failed:",
+                            str(self_dtype),
+                            op.__name__,
+                            device,
+                            str(size),
+                        ]  # noqa: F821
+                    )
                 ) from e
 
     def test_isnan(self):
```

**Comment by huniu20** [comment]
Hi, @ezyang , I've fix the lint issue, thanks for your review:grinning:

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
