### PR TITLE
Enable fake_crossref unit tests on rocm

### PR DESCRIPTION
**Pull request by BLOrange-AMD**
This PR should enable 900+ fake_crossref unit tests for ROCm.
cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Comment by BLOrange-AMD** [comment]
@jithunnair-amd Both ROCm distributed tests runs OK after jobs re-triggered.

**Review by jeffdaily — APPROVED** [review]
Approved. This is known work from one of our pytorch engineers to enable a large number of tests by skipping just the small subset of failing tests.  We will continue to work on the known failures while enabling the remaining tests in this fake_crossref suite.  Green CI status confirms.

**Comment by jeffdaily** [comment]
@soulitzer we require approval from a maintainer before merge is allowed.  The 1 failing unit test job is not related to our changes here.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
