### PR TITLE
pytorch quantization ao migration phase 2: torch/jit

### PR DESCRIPTION
**Pull request by vkuzo**
Summary:
Renames `torch.quantization` to `torch.ao.quantization` in `torch/jit` folder.

```
find caffe2/torch/jit/ -type f -name "*.py" -print0 | xargs -0 sed -i "s/torch\.quantization/torch.ao.quantization/g"
```

Test Plan: CI

Differential Revision: D31273365

### CODE REVIEW

**Comment by suo** [comment]
@vkuzo: This diff was landed with failing mypy signal and broke trunk. Please be more careful next time. https://github.com/pytorch/pytorch/pull/66003 restored master with a suppression, can you follow up with a PR that removes the suppression?

**Comment by vkuzo** [comment]
> @vkuzo: This diff was landed with failing mypy signal and broke trunk. Please be more careful next time. #66003 restored master with a suppression, can you follow up with a PR that removes the suppression?

so sorry, I saw some flaky failures but missed the mypy failure.  Will fix asap.

**Comment by suo** [comment]
Thanks!

**Comment by vkuzo** [comment]
https://github.com/pytorch/pytorch/pull/66035 by @z-a-f  fixes the root cause, I'll follow up with a PR to clean up the annotations in torch/jit/_recursive.py after that lands.  Sorry again.

**Pull request closed without merging**
