### PR TITLE
Reland: "[TensorExpr] Fix handling of 0-dim tensors."

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#59508 Reland: "[TensorExpr] Fix handling of 0-dim tensors."**
* #59507 Reland: "[TensorExpr] Fix printing of Bool dtype."
* #59506 Reland: "[TensorExpr] Improve debug messages."

An assert that was triggering in a previous version is now relaxed to
take 0-dim tensors into account.

Differential Revision: [D28918342](https://our.internmc.facebook.com/intern/diff/D28918342)

### CODE REVIEW

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28918342).

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28918342).

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28918342).

**Review by bertmaher — APPROVED** [review]

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28918342).

**Pull request closed without merging**
