### PR TITLE
Small Adamax fix

### PR DESCRIPTION
**Pull request by mlazos**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #123469
* #123619
* #123406
* #124309
* #123405
* #123404
* #123324
* #123323
* #123322
* __->__ #123498

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
Why is this necessary? In compile, state_steps should also be a list of singleton tensors.

**Review by janeyx99 — COMMENTED** [review]
I'm approving because I see we set a precedent for this, but I don't know why we set such a precedent in the first place.

**Review by janeyx99 — APPROVED** [review]

**Comment by mlazos** [comment]
> I'm approving because I see we set a precedent for this, but I don't know why we set such a precedent in the first place.

It's because it can be slow to trace, I happened to notice this so just popped in the fix. In general this was also a BC thing from years ago too right? but this is fine.

**Pull request closed without merging**
