### PR TITLE
Update matmul decomp to match eager

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105850

The decomposition was not updated after https://github.com/pytorch/pytorch/pull/95261

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Comment by lezcano** [comment]
To test this, I run all the `brute_force` tests in
https://github.com/pytorch/pytorch/blob/3045e84e679a23ba3d5a5071b79593724098f389/test/test_linalg.py#L4351-L4377
using `torch.compile(torch.matmul)`. They all passed but one (`test_matmul_small_brute_force_1d_Nd_cpu_complex64`). The test that did not pass failed on an unrelated issue (see https://github.com/pytorch/pytorch/issues/105853)

**Review by Chillee — APPROVED** [review]

**Pull request closed without merging**
