### PR TITLE
[inductor] Support storage resizing

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #119749
* #119671
* #119647

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by yf225 — APPROVED** [review]

**Comment by wconstab** [comment]
looks like fully general support for compiling storage resize, which is nice.

but how do we reason about this in the inductor optimizations?  Are we attempting to preserve the eager FSDP's indication of when to drop/restore memory allocations, or are we free to reorder/fuse/skip them?

**Comment by jansel** [comment]
> looks like fully general support for compiling storage resize, which is nice.
> 
> but how do we reason about this in the inductor optimizations? Are we attempting to preserve the eager FSDP's indication of when to drop/restore memory allocations, or are we free to reorder/fuse/skip them?

It is treated as muation op, so inductor can't reorder the storage resize with respect to other uses.

What optimization are you thinking about there?

**Comment by wconstab** [comment]
> What optimization are you thinking about there?

well, for fsdp tracing the different schools of thought could be (a) ignore everything eager did except that it asked for allgathers/reducescatters.  Then rely on the partitioner and communication optimization passes to figure out good balance between communication overlap and peak memory.  and (b) being to actually respect what eager did, but that means you're locked into checkpointing, bucketing, and comm overlap decisions early on.

For per-param fsdp at least, we wanted inductor to help with bucketing optimizations, though i'm not sure if that's really happening.  cc @awgu

**Comment by jansel** [comment]
If we want to ignore these ops, we can just write a compiler pass to delete them.  This PR just tries to capture the program as written.

**Pull request closed without merging**
