### PR TITLE
Minor build clean ups

### PR DESCRIPTION
**Pull request by zdevito**
* Fixes some warnings
* Removes source files include in both _C.so and libtorch.so
* Removes dead flags from the build script.
* Deletes unused THConfig.cmake.in file.

This is going to fail CI until master is fixed.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by peterjc123** [comment]
The ci build failure implies that there are some missing symbol annotations in `torch\csrc\cuda\comm.h`,

**Comment by zdevito** [comment]
Yeah, this isn't finished yet and needs a big rebase.

**Comment by zdevito** [comment]
way out of date, closing...

**Pull request closed without merging**
