### PR TITLE
Kill capture_pre_autograd_graph API

### PR DESCRIPTION
**Pull request by yushangdi**
Summary:
Delete the following API:

- capture_pre_autograd_graph()
- capture_pre_autograd_graph_using_training_ir()
- gm_using_training_ir()

There's no more call sites to `capture_pre_autograd_graph`.

Except
1) two test cases in coreml, PR to remove: https://github.com/apple/coremltools/pull/2400
2) XLA: one test case in pytorch/xla, PR to remove: https://github.com/pytorch/xla/pull/8398
3) a few call sites guarded by version guard (< 2.5.0)

Test Plan: CI

Reviewed By: tugsbayasgalan

Differential Revision: D64056353

### CODE REVIEW

**Review by tugsbayasgalan — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but the XLA failure is legit' -c ignoredsignal

The failure from the log is:

```
2024-12-17T00:19:01.7317067Z + python3 /var/lib/jenkins/workspace/xla/test/stablehlo/test_pt2e_qdq.py
2024-12-17T00:19:04.7979656Z Traceback (most recent call last):
2024-12-17T00:19:04.7980307Z   File "/var/lib/jenkins/workspace/xla/test/stablehlo/test_pt2e_qdq.py", line 9, in <module>
2024-12-17T00:19:04.7980967Z     from torch._export import capture_pre_autograd_graph
2024-12-17T00:19:04.7981788Z ImportError: cannot import name 'capture_pre_autograd_graph' from 'torch._export' (/opt/conda/lib/python3.10/site-packages/torch/_export/__init__.py)
```

**Comment by yushangdi** [comment]
> @pytorchbot revert -m 'Sorry for reverting your change but the XLA failure is legit' -c ignoredsignal
> 
> The failure from the log is:
> 
> ```
> 2024-12-17T00:19:01.7317067Z + python3 /var/lib/jenkins/workspace/xla/test/stablehlo/test_pt2e_qdq.py
> 2024-12-17T00:19:04.7979656Z Traceback (most recent call last):
> 2024-12-17T00:19:04.7980307Z   File "/var/lib/jenkins/workspace/xla/test/stablehlo/test_pt2e_qdq.py", line 9, in <module>
> 2024-12-17T00:19:04.7980967Z     from torch._export import capture_pre_autograd_graph
> 2024-12-17T00:19:04.7981788Z ImportError: cannot import name 'capture_pre_autograd_graph' from 'torch._export' (/opt/conda/lib/python3.10/site-packages/torch/_export/__init__.py)
> ```

@huydhn  Hi Huy, thanks for flagging this.

The xla test is using deprecated API and we are deleting this API now. Can we disable this test `python3 /var/lib/jenkins/workspace/xla/test/stablehlo/test_pt2e_qdq.py`? I have a PR telling them to migrate for a month, but got no review/reply.... (https://github.com/pytorch/xla/pull/8398)

**Comment by miladm** [comment]
cc @lsy323 to help look into this PR from the TorchXLA side.
(cc @tengyifei for viz)

**Comment by yushangdi** [comment]
> @yushangdi The bot went crazy and tried to land this. I could give you a stamp on [pytorch/xla#8398](https://github.com/pytorch/xla/pull/8398), but I guess we need a review from folks there just to be sure?

@huydhn The PR on the xla side is merged. Can we merge this PR again? (do we need to update any xla pin? I tried to search for it but didn't find one.)

**Comment by yushangdi** [comment]
reland in https://github.com/pytorch/pytorch/pull/143426

**Pull request closed without merging**
