### PR TITLE
cherry-pick "Unify flags and environmental variable when building LibTorch/PyTorch"

### PR DESCRIPTION
**Pull request by zou3519**
Cherry-picked the following two PRs:
#14976
#15868

I am not sure how to test this; this PR on 1.0.1 builds locally for me on my machine.

cc @soumith

### CODE REVIEW

**Review by soumith — APPROVED** [review]
i'll merge it. since it's non master branch, i'll merge directly instead of import + merge

**Comment by soumith** [comment]
@zou3519 also failing on one of those docker image bump things:

```
Error: Cannot install moreutils because conflicting formulae are installed.
  parallel: because Both install a `parallel` executable.
```

**Comment by zou3519** [comment]
@soumith that's a bug with our Mac CI that Simon fixed in a recent PR, should I cherry-pick that as well?

**Comment by soumith** [comment]
yes please

**Pull request merged**
