### PR TITLE
Not run inductor test in trunk

### PR DESCRIPTION
**Pull request by huydhn**
Trying to not run in inductor tests in trunk at the moment because of CUDA issue with G5 runner:

* CUDA GPU not found https://github.com/pytorch/pytorch/actions/runs/3379516207/jobs/5611539300
* NVIDIA driver installation fails https://github.com/pytorch/pytorch/actions/runs/3379922198/jobs/5612458360
* Docker fails to start https://github.com/pytorch/pytorch/actions/runs/3381276196/jobs/5615513348

### CODE REVIEW

**Review by desertfire — APPROVED** [review]
Thanks for taking care of this. We would still run this for most of the dynamo/inductor related PRs because of the auto-labeler rule.

**Comment by huydhn** [comment]
> Thanks for taking care of this. We would still run this for most of the dynamo/inductor related PRs because of the auto-labeler rule.

Yeah, the auto-labeler rule is a life saver in this case indeed.  Note that we can re-enable this later after root causing the issue with CUDA and G5 runners

**Comment by malfet** [comment]
Should we revert the changes now?

**Pull request closed without merging**
