### PR TITLE
Adam/AdamW implementation minor fix

### PR DESCRIPTION
**Pull request by farhadrgh**
I have noticed a small discrepancy between theory and the implementation of AdamW and in general Adam. The epsilon in the denominator of the following Adam update should not be scaled by the bias correction [(Algorithm 2, L9-12)](https://arxiv.org/pdf/1711.05101.pdf). Only the running average of the gradient (_m_) and squared gradients (_v_) should be scaled by their corresponding bias corrections.

adam_update

In the current implementation, the epsilon is scaled by the square root of `bias_correction2`.  I have plotted this ratio as a function of step given `beta2 = 0.999` and `eps = 1e-8`. In the early steps of optimization, this ratio slightly deviates from theory (denoted by the horizontal red line).

plot

### CODE REVIEW

**Comment by vincentqb** [comment]
Good catch! I've updated the name to highlight this indeed affects both Adam and AdamW.

**Comment by vincentqb** [comment]
This change looks good to me. I'll run a few tests before merging.

**Comment by farhadrgh** [comment]
> Good catch! I've updated the name to emphasize that both Adam and AdamW are affected. For reference, see also papers cited in documentation, [here](https://arxiv.org/pdf/1412.6980.pdf) also.

Great, thanks!

**Comment by fl2o** [comment]
Has the same modification been done to the cpp implementation of Adam?

**Comment by farhadrgh** [comment]
> Has the same modification been done to the cpp implementation of Adam?

I had forgotten about that. I have just addressed it in a new PR: #23737

**Review by vincentqb — APPROVED** [review]

**Comment by azcohen14** [comment]
Would it make sense to have the same modification in the implementation of SparseAdam?

**Comment by farhadrgh** [comment]
Yes indeed! I looked into it, but apparently forgot to update it, I can go ahead and fix it in a separate PR.

**Pull request closed without merging**
