### PR TITLE
Fix symbolic nested int printing

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #132414
* #130292
* #131803
* __->__ #131916

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

Differential Revision: [D60406775](https://our.internmc.facebook.com/intern/diff/D60406775)

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by YuqingJ** [comment]
@yuqingj has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60406775).

**Review by jbschlosser — APPROVED** [review]
Thanks! :D test failures might be real though?

**Comment by YuqingJ** [comment]
> ## Merge failed
> **Reason**: This PR has internal changes and must be landed via Phabricator! Please try reimporting/rexporting the PR!
> 
> Details for Dev Infra team

I abandoned the internal diff and unlinked the PR. Please feel free to merge it again if it is ready.

**Pull request closed without merging**
