### PR TITLE
[Dynamo] Fix guards for code objects

### LINKED ISSUE #120647: 2 Dynamo test are failing with "invalid syntax (<unknown".
2 Dynamo test are failing with "invalid syntax (<unknown".

## Repro

`PYTORCH_TEST_WITH_DYNAMO=1 pytest test_quantization.py -v -k test_quantization_doc_fx`

You will need to remove the skip or expectedFailure before running the repro command.
This may be deleting a file in https://github.com/pytorch/pytorch/tree/main/test/dynamo_skips or https://github.com/pytorch/pytorch/tree/main/test/dynamo_expected_failures 

## Failing tests

Here's a comprehensive list of tests that fail (as of this issue) with the above message:
<details>
<summary>Click me</summary>
```
test_quantization.py::TestQuantizationDocs.test_quantization_doc_fx
test_quantization.py::TestQuantizationDocs.test_quantization_doc_qat
```
</details>

cc @ezyang @msaroufim @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### PR DESCRIPTION
**Pull request by malfet**
By comparing them only by id, and raising an assert if someone calls into `EQUALS_MATCH`
Which render following example compileable:
```python
import torch

@torch.compile()
def foo(x, y):
    code = compile(y, "foo", "exec")
    exec(y)
    return x

print(foo(torch.rand(3), "print('Hello World')"))
```

Fixes https://github.com/pytorch/pytorch/issues/120647

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by malfet** [comment]
I wonder if I should add a unittest for it, or having an integration test of sorts is fine?

**Comment by ezyang** [comment]
I guess my big uncertainty with this PR is whether or not it was intended that we actually should be doing EQUALS_MATCH on code objects. Like, if I am repeatedly regenerating a code object every time before I call into Dynamo, I don't really feel like I expect Dynamo to be able to tell "oh ho, the bytecode is exactly the same this time around, let me reuse the old product", I expect to just recompile each time because WHAT DID YOU EXPECT. So like... should this issued guard have been an ID_MATCH instead?

**Review by jansel — APPROVED** [review]
cc @anijain2305   

I think you submitted a similar fix for this.

**Pull request closed without merging**
