### PR TITLE
[NCCL] Helper Function to Abort All outstanding NCCL Communicators

### PR DESCRIPTION
**Pull request by osalpekar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #41265 [Gloo] Tests for Gloo Async Work Wait-level Timeouts
* #40948 [Gloo] Support work-level timeouts in ProcessGroupGloo
* #40947 [NCCL] Tests for WorkNCCL::wait with Timeouts
* #40946 [NCCL] Support Wait Timeout in ProcessGroupNCCL
* **#40945 [NCCL] Helper Function to Abort All outstanding NCCL Communicators**
* #40944 [NCCL] Add timeout to ProcessGroup Work Wait

This adds a helper function to abort all NCCL Communicators associated with a WorkNCCL object

Differential Revision: [D22127899](https://our.internmc.facebook.com/intern/diff/D22127899/)

### CODE REVIEW

**Comment by jiayisuse** [comment]
Wondering if this helper function is being used in this stack

**Comment by osalpekar** [comment]
> Wondering if this helper function is being used in this stack

It was used in a prior version of #40946, but not anymore. Previously, we weren't overwriting the `opTimeout_` with the user-supplied `waitTimeout`, so there was some separate logic to detect timed out WorkNCCL objects and abort associated communicators. Now that logic is simplified by just overwriting `opTimeout_`, though it still might be a good helper func to have.

**Comment by mrshenli** [comment]
If this is not used, shall we move this PR out of this stack and only land it when necessary?

**Comment by osalpekar** [comment]
Closing this PR since aborting NCCL Comms from the WorkNCCL-level is no longer necessary given the updated design for work timeouts

**Pull request closed without merging**
