### PR TITLE
Remove Deprecated Copy Constructor

### PR DESCRIPTION
**Pull request by skrobchik**
Summary: Fix the following compilation error https://www.internalfb.com/diffs/browse?start=0&phabricator_diff_id=379911240743608&selected_signal=c2xwOjE1NjA3NjQxMDc2MzQ0Nzk%3D&selected_signal_verification_phase=1&dst_version_fbid=746884619882827

Test Plan:
1. `maui install workvc`

2. `pull / linux-xenial-cuda11_3-py3_7-gcc7-deploy / build`
signal should pass

Differential Revision: D38433489

### CODE REVIEW

**Review by dvchang — APPROVED** [review]
LGTM

**Review by zengk95 — APPROVED** [review]
LGTM. Approving on behalf of David Chang

**Comment by skrobchik** [comment]
https://github.com/pytorch/pytorch/pull/83030

**Pull request closed without merging**
