### PR TITLE
Actually pass dilation to the underlying operators.

### PR DESCRIPTION
**Pull request by ezyang**
No tests for now; we'll need some sort of shape DSL to concisely
represent them.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by ngimel** [comment]
@ezyang tests are failing for me with a fresh build that includes this PR: 
```
FAIL: test_ConvTranspose2d_dilated_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 2331, in <lambda>
    setattr(TestNN, cuda_test_name, lambda self, test=test: test.test_cuda(self))
  File "/opt/pytorch/test/common_nn.py", line 643, in test_cuda
    test_case.assertEqual(cpu_output, gpu_output, 2e-4)
  File "/opt/pytorch/test/common.py", line 158, in assertEqual
    assertTensorsEqual(x, y)
  File "/opt/pytorch/test/common.py", line 138, in assertTensorsEqual
    super(TestCase, self).assertEqual(a.size(), b.size())
AssertionError: torch.Size([1, 4, 12, 20]) != torch.Size([1, 4, 14, 22])

======================================================================
FAIL: test_ConvTranspose3d_dilated_cuda (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 2331, in <lambda>
    setattr(TestNN, cuda_test_name, lambda self, test=test: test.test_cuda(self))
  File "/opt/pytorch/test/common_nn.py", line 643, in test_cuda
    test_case.assertEqual(cpu_output, gpu_output, 2e-4)
  File "/opt/pytorch/test/common.py", line 158, in assertEqual
    assertTensorsEqual(x, y)
  File "/opt/pytorch/test/common.py", line 138, in assertTensorsEqual
    super(TestCase, self).assertEqual(a.size(), b.size())
AssertionError: torch.Size([1, 3, 5, 7, 5]) != torch.Size([1, 3, 6, 9, 6])

----------------------------------------------------------------------
Ran 372 tests in 69.860s
```

**Comment by hojonathanho** [comment]
The dilation is not being passed into `ConvTranspose1d.forward`.

**Comment by ezyang** [comment]
@hojonathanho You're right, embarrassing.

@ngimel If @hojonathanho is correct, it kind of looks like either (1) the test suite is wrong for dilation or (2) the underlying implementation of dilation is wrong. I wonder why CI didn't catch that; maybe it is skipping these tests for some reason.

**Comment by soumith** [comment]
The CI is on CuDNN v5. That's the reason. Time to upgrade.

**Pull request merged**
