### PR TITLE
UFMT formatting on test/autograd test/ao test/cpp test/backends

### PR DESCRIPTION
**Pull request by arunppsg**
Partially addresses #123062

Ran lintrunner on
- test/_test_bazel.py
- test/ao
- test/autograd test/backends test/benchmark_uitls test/conftest.py test/bottleneck_test test/cpp

cc @albanD

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Comment by ezyang** [comment]
Confirmed no changes with lintcheck.sh

**Pull request closed without merging**
