### PR TITLE
Verify types in custom op schemas

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #124520

Before this PR, we didn't check that types in a schema were valid. This
is because TorchScript treats unknown types as type variables.

This PR checks types in a schema for the TORCH_LIBRARY APIs. To do this,
we add an `allow_typevars` flag to parseSchema so that TorchScript can
use allow_typevars=True. We also add some error messages for common
mistakes (e.g. using int64_t or double in schema).

Test Plan:
- new tests

Differential Revision: [D56432690](https://our.internmc.facebook.com/intern/diff/D56432690)

cc @ezyang @gchanan

### CODE REVIEW

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D56432690).

**Comment by zou3519** [comment]
This is technically BC-breaking. If you want the old behavior, use `torch::schema(<schema_str>, allow_typevars=True)` when defining an operator.

**Review by williamwen42 — COMMENTED** [review]
lgtm - will defer due to BC breaking change.

**Review by albanD — APPROVED** [review]
This doesn't change TORCH_LIBRARY so I'm good :)

**Comment by zou3519** [comment]
landed in https://github.com/pytorch/pytorch/pull/126861

**Pull request closed without merging**
