### PR TITLE
REDO of dropout support for mem eff #102038

### PR DESCRIPTION
**Pull request by drisspg**
THIS IS A new PR with the changes from #102038 + #103201 +  plus namespacing changes to fix bug.

# Summary
This PR builds off of:
- https://github.com/pytorch/pytorch/pull/101847
- https://github.com/pytorch/pytorch/pull/100583

It specifically adds dropout support to the memory efficient attention kernel. In the process of doing so roughly 3 changes were made:
- Update sdpa dispatching to allow for inputs requiring grad to be sent to efficient attention
- Update how memory efficient attention handles passing the rng state from forward to backward in order to enable cuda_graph support
- Fix a bug in the kernel that was causing incorrect gradients to be produced for num_keys > 64 with dropout and causal masking set. https://github.com/facebookresearch/xformers/pull/755

cc @albanD @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @anijain2305 @aakhundov @bertmaher

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]

**Comment by davidberard98** [comment]
I bisected a 4% slowdown on huggingface to this PR (specifically using ElectraForQuestionAnswering). @drisspg any ideas what could cause this?

**Comment by drisspg** [comment]
@davidberard98 This is likely because the model question is using dropout. Previously Memory effiecient attention would have not been dispatched to and this PR allows this now. A good way to verify this would be to select which kernel: https://pytorch.org/tutorials/intermediate/scaled_dot_product_attention_tutorial.html#explicit-dispatcher-control

https://github.com/pytorch/pytorch/blob/a66107a30c6ed7f2392293d6beb59ddc6fee4be7/aten/src/ATen/native/transformers/cuda/sdp_utils.cpp#L44

This defines the kernel ordering. I have one more PR to add attn_bias support to mem_eff and then was going see if any updates are needed to the priority order

**Comment by eellison** [comment]
@drisspg do we expect the other pr to recover perf ?  5% performance regression is significant. FWIW the memory compression stayed stable with this pr. I guess potentially our heuristics on which backend to select here didn't work great here ?

**Comment by drisspg** [comment]
@eellison I do not think the other PR will recover the PERF. I suspect the heurisitic is choosing the new mem_eff + dropout path now that it exists when  the more performant path is FlashAttn. 

I am planning though to create a 3rd pr once the mem_eff attn PR to re run the perf sweep and see if there are more modifications to be made to the heuristic

**Comment by davidberard98** [comment]
@drisspg you mentioned selecting the kernel using the tutorial you linked - do you recommend this or do you think it's better to rely on the heuristics (and wait for your updates to see if the heuristics)

**Comment by eellison** [comment]
Where are the current heuristics ?

**Comment by drisspg** [comment]
> Where are the current heuristics ? 

Linked up above in my response to David

**Comment by eellison** [comment]
cc @Chillee who updated the heuristics recently

**Pull request closed without merging**
