### PR TITLE
Fix fx tracing for OpOverload

### PR DESCRIPTION
**Pull request by anjali411**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #73940

Differential Revision: [D34727831](https://our.internmc.facebook.com/intern/diff/D34727831)

### CODE REVIEW

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34727831).

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34727831).

**Review by Chillee — APPROVED** [review]
LGTM!

**Review by ezyang — APPROVED** [review]
lol

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34727831).

**Pull request closed without merging**
