### PR TITLE
[PyTorch] Use SmallVector for FunctionSchema Arguments

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #64691

Heap allocation profiling seemed to show that this path
allocates on the heap a bunch, but the typical function has a small
number of arguments, with 1 being very common and the count of
functions with each number of arguments decreasing after that. I
picked 3 as a guess for what would provide a good tradeoff between
wasted inline space and not allocating on the heap.

Differential Revision: [D30816470](https://our.internmc.facebook.com/intern/diff/D30816470/)

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
for external users of schema/arguments this would be bc-breaking.. how much perf did this save ?

**Comment by swolchok** [comment]
> for external users of schema/arguments this would be bc-breaking

@eellison are those public APIs with bc guarantees? I don't see `TORCH_API` or `C10_API` on FunctionSchema.

**Comment by swolchok** [comment]
for future reference, here's the test falure:

```
Sep 10 22:13:23 ======================================================================
Sep 10 22:13:23 ERROR [0.060s]: test_multiline_annot_ast_py3_fn (__main__.TestScript)
Sep 10 22:13:23 ----------------------------------------------------------------------
Sep 10 22:13:23 Traceback (most recent call last):
Sep 10 22:13:23   File "test_jit.py", line 12742, in test_multiline_annot_ast_py3_fn
Sep 10 22:13:23     args = fn.schema.arguments
Sep 10 22:13:23 TypeError: Unable to convert function return value to a Python type! The signature was
Sep 10 22:13:23 	(arg0: torch._C.FunctionSchema) -> c10::SmallVector<c10::Argument, 3u>
```

Looks like at least one of the affected functions is exposed to Python. guess I'll have to find out how we were exposing `std::vector<Argument>` to Python and do the same for SmallVector. (pointer appreciated; I have no idea how this works offhand but I imagine pybind is involved)

**Comment by swolchok** [comment]
ping

**Comment by eellison** [comment]
@swolchok please "re-request review" when you want another look
image

**Comment by swolchok** [comment]
build issues aren't major; fixed locally but can't ghexport because it would interfere with a land lower in the stack

**Comment by swolchok** [comment]
ping

**Comment by swolchok** [comment]
was actuallly a perf regression

**Pull request closed without merging**
