### PR TITLE
Add memory format argument to the `clone` operator

### PR DESCRIPTION
**Pull request by VitalyFedyunin**
Adds memory_format option to the `clone` operator.

Introduce new `clone` behavior if used with `input_t.clone(memory_format=torch.preserve_format)`:
1) If tensor is non-overlapping and dense - output tensor will have the same strides as input tensor.
2) If not (1) and tensor is stored in the channels last format, output tensor going to have channels last format.
3) Output tensor is going to be contiguous in all other cases.

---
Dense tensor is the tensor that store values in a contiguous block of memory.
Non-overlapping tensor is the tensor in which elements occupy individual non-repetitive memory.

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
Please do not land.

**Comment by VitalyFedyunin** [comment]
@ailzhang breaks XLA

**Comment by ailzhang** [comment]
Btw what's difference between `c10::MemoryFormat` and `at::MemoryFormat`? I'm seeing both in xla code and not sure whether I should fix them. Thanks!

**Comment by VitalyFedyunin** [comment]
> Btw what's difference between `c10::MemoryFormat` and `at::MemoryFormat`? I'm seeing both in xla code and not sure whether I should fix them. Thanks!

No difference, for some unknown to me reasons `at` namespace is renamed to `c10` in some includes.

**Comment by VitalyFedyunin** [comment]
Code is ready to review, inline docs will be added shortly.

**Comment by VitalyFedyunin** [comment]
Moved to stack #27106

**Pull request closed without merging**
