### PR TITLE
Fix typos under torch/nn directory

### PR DESCRIPTION
**Pull request by kiszk**
This PR fixes typos in comments of `.py` files under `torch/nn` directory

### CODE REVIEW

**Review by dagitses — APPROVED** [review]
@pytorchbot merge

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
@kiszk Can you resolve the conflict?

**Comment by kiszk** [comment]
sure, resolved

**Comment by kit1980** [comment]
> sure, resolved

Thanks. Just to be clear, you can post the merge comment yourself after an approving review, no need to wait.

**Pull request closed without merging**
