### PR TITLE
Added ModuleInfos for {*}LU modules

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #97704
* __->__ #97375

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!

**Review by jbschlosser — APPROVED** [review]
Thanks for adding these!

For posterity, leaving a comment here saying I'm okay with us getting rid of the old-style testing dict entries as you do in this PR and #97291. All of the coverage those old-style tests were providing is covered by the new tests as well EXCEPT FOR C++ / Python API parity testing, and those provided questionable value as-is. We can revisit those tests if we find we need them in the future.

**Pull request closed without merging**
