### PR TITLE
Enable correct supported activities for kineto on rocm

### PR DESCRIPTION
**Pull request by mwootton**
A compile time guard was preventing ActivityType::CUDA from being available on rocm.  This caused both the GPU_FALLBACK and CUDA modes to be active at the same time.  So operators were being charged gpu time for the hipEventRecord ranges and the actual kernel execution times.  This caused incorrect (and often negative) cuda times, in e.g. table(). 

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM

**Review by malfet — CHANGES_REQUESTED** [review]
Hmm, I think according to this logic if code is build with GPU support, either `NOROCTRACER` or `NOCUPTI` would be deinfed:
https://github.com/pytorch/pytorch/blob/6e6f929b2c5308b8de2c82884b8fa70bd4778842/cmake/Dependencies.cmake#L1908-L2000

**Comment by mwootton** [comment]
> Hmm, I think according to this logic if code is build with GPU support, either `NOROCTRACER` or `NOCUPTI` would be deinfed:
> 


Correct:
for cuda: USE_KINETO and LIBKINETO_NOROCTRACER will be set
for rocm: USE_KINETO and LIBKINETO_NOCUPTI will be set
for CPU only or a configuration error (e.g. no cupti headers detected): USE_KINETO, LIBKINETO_NOROCTRACER, and LIBKINETO_NOCUPTI will all be set

We need to enable ActivityType::CUDA (which means GPU in this case) whenever direct kernel measurements are available, i.e. cupti or roctracer are present.  So we need that activity enabled unless BOTH are missing.

An observation:  It would probably be better to query the compiled libkineto at runtime for its actual capabilities than guessing it's capabilities based on CMAKE variables we passed to its build.  Also, the negative define variables seem like a bad choice as you immediately end up with double negatives.  LIBKINETO_USE_CUPTI and !LIBKINETO_USE_CUPTI speak to me more clearly.  Also, you then wouldn't need to use DeMorgan's law make sense of, e.g., this patch.  Which may have been done on purpose. :)

**Review by malfet — APPROVED** [review]
It looks very confusing, but if CI is green (assuming we are testing kineto in CI), looks good to me.

**Comment by mwootton** [comment]
```
#if defined(USE_KINETO) && \
    (!defined(LIBKINETO_NOCUPTI) || !defined(LIBKINETO_NOROCTRACER))
    if (at::getNumGPUs() > 0) {
      activities.insert(ActivityType::CUDA);
```
So the second line is the same as:
`!(defined(LIBKINETO_NOCUPTI) && defined(LIBKINETO_NOROCTRACER))`

Overall, if:

1. We are using kineto
2. We don't have both profiling libraries disabled
3. We have a gpu present

...then we want to use the gpu profiling library.

And no argument that it is confusing.  I was just dealing with what was there to begin with.

**Review by jeffdaily — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@mwootton Can you please double-check this CI failure: https://github.com/pytorch/pytorch/actions/runs/3463699947/jobs/5784908770
```
2022-11-14T18:28:24.1445685Z     test_kineto failed - num_retries_left: 1
2022-11-14T18:28:24.1446220Z Traceback (most recent call last):
2022-11-14T18:28:24.1447242Z   File "C:\actions-runner\_work\pytorch\pytorch\test\profiler\test_profiler.py", line 581, in test_kineto
2022-11-14T18:28:24.1448082Z     self.assertTrue(found_gemm)
2022-11-14T18:28:24.1448732Z AssertionError: False is not true
2022-11-14T18:28:24.1449038Z 
2022-11-14T18:28:24.1449196Z FAIL (0.012s)
```

**Pull request closed without merging**
