### PR TITLE
Merge On Green Bot

### PR DESCRIPTION
**Pull request by zengk95**
Closed the last one because I accidentally rebased on main and tagged 300 people. 

This implements the merge on green bot by continuously calling trymerge for 6 hours with 1 minute in between attempts. 

Examples of it working (Stopping when lint fails):

image

Merging while busy waiting in GHA

image

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
test plan?

**Comment by seemethere** [comment]
> Closed the last one because I accidentally rebased on main and tagged 300 people.
> 
> This implements the merge on green bot by continuously calling trymerge for 6 hours with 1 minute in between attempts.

Are we sure holding a runner for 6 hours is the right approach for this? We have a limited number of concurrent runners and I think using one continuously for 6 hours is probably not the best idea.

**Comment by janeyx99** [comment]
> > Closed the last one because I accidentally rebased on main and tagged 300 people.
> > This implements the merge on green bot by continuously calling trymerge for 6 hours with 1 minute in between attempts.
> 
> Are we sure holding a runner for 6 hours is the right approach for this? We have a limited number of concurrent runners and I think using one, or multiple, continuously for 6 hours is probably not the best idea.

For now, it shouldn't take longer than however long Lint takes, usually, so it's not a terrible first step. For future iterations, an option could be exploring triggering trymerge.py every time a workflow job is done, and editing trymerge so that it can be triggered multiple times. Another (perhaps better) long-term option is abstracting the trymerge validation logic outside of trymerge entirely.

**Comment by suo** [comment]
What is the upper limit on our ability provision linux.2xlarge? Aren't they like infinite?

6 hours is an upper-bound of 20 concurrent runners occupied based on the last few days of merge traffic, which doesn't seem that bad to be honest. And we'll need to tighten the actul runtime of the workflow to like 2h if we want to actually want to use this for landcastle.

**Comment by suo** [comment]
Can we make "merge on green" the default behavior? Seems like there's not really a case where you want to merge but also fail immediately.

(of course, force merging should always be an option)

**Comment by janeyx99** [comment]
@suo merge on green is intended to be the default behavior, but we wanna test it before forcing it on everyone, hence the separate command. @zengk95 If testing is taking very long + not worth investing more time in, we can go the route you suggested with gatekeeping + tell people they can use it + report bugs.

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
