### PR TITLE
[DataLoader] Removing DataLoader2 related code

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #88848

Removing these lines of code as `DataLoader2` has been added to [TorchData](https://github.com/pytorch/data). I'm importing this to confirm it will not impact internal codes.

Differential Revision: [D41201578](https://our.internmc.facebook.com/intern/diff/D41201578)

### CODE REVIEW

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41201578).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41201578).

**Review by ejguan — APPROVED** [review]

**Comment by ejguan** [comment]
@NivekT For safety, do you mind validating the torchdata's tests in your local environment with this change?

**Comment by NivekT** [comment]
> @NivekT For safety, do you mind validating the torchdata's tests in your local environment with this change?

I ran the a few TorchData test and checked for imports. It seems to be fine. Merging now.

**Pull request closed without merging**
