### PR TITLE
Add assert_async

### LINKED ISSUE #36853: torch.assert operator / async assertion for cuda tensors
## 🚀 Feature

Launch a non-blocking "assert" op for cpu/cuda tensors.

## Motivation
It's common to use assertion to check pre-conditions or unexpected inputs in code, as a form of defensive programming. For example, sometimes we want to assert that all elements of a tensor is all positive, or finite.

However, doing assert in python has the following problems in pytorch:
* when dealing with cuda tensors, using python's `assert (t>0).all()` or `assert torch.isfinite(t).all()` will wait for results of the cuda kernel and most if not all its preceding kernel launches, thus potentially cause significantly slow down.
It would be good to have a way to execute an assert as an async call.
* it does not work nicely with tracing or FX, because it is considered as control logic

## Pitch
```
x = some_tensor()
(x>0).all().assert("I got a bad data x")
y = torch.log(x)
torch.Assert(y.all(), "message")
```
(assert is a reserved keyword. Tensorflow uses tf.Assert. we can also use `torch.assert_` since the op can be used with in-place style: `y.all().assert_()`)

cc @ngimel

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#53086 Add assert_async**

Fixes #36853

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D26744062](https://our.internmc.facebook.com/intern/diff/D26744062)

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Thanks! I wonder how should this interact with https://github.com/pytorch/pytorch/blob/521e1e83ea70400854e64eddb5fc97aeb73b4230/torch/__init__.py#L604-L613 ? Should both exist? Should `_assert` call `torch.assert_async` when inputs are tensors so it has both async support and non-tensor support?

**Comment by ezyang** [comment]
@ppwwyyxx Unfortunately the semantics are different. `_assert` guarantees that the assert is delivered synchronously; `assert_async`, as its name suggests, may deliver the assert asynchronously later. So I don't think one can call the other, or vice versa.

**Comment by ppwwyyxx** [comment]
Users can decide whether it's synchronous or not by `_assert(tensor.item()) vs. _assert(tensor)`. But yeah, that's still not nice and I'm not sure if it's worse to do this or to have two different assert features.

**Review by ppwwyyxx — APPROVED** [review]

**Comment by ezyang** [comment]
> Users can decide whether it's synchronous or not by _assert(tensor.item()) vs. _assert(tensor). But yeah, that's still not nice and I'm not sure if it's worse to do this or to have two different assert features.

That would break the invariant that `_assert(x)` is defined to be equivalent to `assert x`, but just TorchScript friendly. The built-in Python assert is never async, because it converts the input to boolean and tests it (and tensor to boolean conversion always syncs).

**Comment by mruberry** [comment]
Unlanding. This broke pytorch-linux-bionic-rocm4.0.1-py3.6-test1, relevant failures:

```
20:17:51 ======================================================================
20:17:51 FAIL [0.000s]: test_cuda_assert_async (__main__.TestCuda) (stmt="torch.assert_async(torch.tensor(0, device='cuda'))")
20:17:51 ----------------------------------------------------------------------
20:17:51 Traceback (most recent call last):
20:17:51   File "test_cuda.py", line 1856, in test_cuda_assert_async
20:17:51     self.assertTrue(r != 0)
20:17:51 AssertionError: False is not true
20:17:51 
20:17:51 ======================================================================
20:17:51 FAIL [0.000s]: test_cuda_assert_async (__main__.TestCuda) (stmt="torch.assert_async(torch.tensor(0.0, device='cuda'))")
20:17:51 ----------------------------------------------------------------------
20:17:51 Traceback (most recent call last):
20:17:51   File "test_cuda.py", line 1856, in test_cuda_assert_async
20:17:51     self.assertTrue(r != 0)
20:17:51 AssertionError: False is not true
20:17:51 
20:17:51 ======================================================================
20:17:51 FAIL [5.412s]: test_cuda_assert_async (__main__.TestCuda) (stmt="torch.assert_async(torch.tensor(False, device='cuda'))")
20:17:51 ----------------------------------------------------------------------
20:17:51 Traceback (most recent call last):
20:17:51   File "test_cuda.py", line 1856, in test_cuda_assert_async
20:17:51     self.assertTrue(r != 0)
20:17:51 AssertionError: False is not true
```

These failures also appear on the PR CI.

**Comment by jeffdaily** [comment]
This PR is breaking ROCm builds.  Causing an internal compiler error?

**Comment by mruberry** [comment]
> This PR is breaking ROCm builds. Causing an internal compiler error?

It's been unlanded. But we are still seeing flaky ROCm builds. cc @malfet

**Comment by jeffdaily** [comment]
Please let us know what we can do to help.

**Comment by ezyang** [comment]
Sure, let's revert it. @jeffdaily, btw, it doesn't seem like asserts work on ROCm XD

**Comment by malfet** [comment]
Hmm, but the crash I'm seeing is while compiling `test/cpp/api/integration.cpp`, which does not include a single file from this PR, is it?

**Comment by malfet** [comment]
Reduced the problem just to the combination of 3 flags:
```
/usr/bin/c++ -fopenmp -O2 -faligned-new  -c CMakeFiles/test_api.dir/integration.E.cpp
```
Not sure if any of the API tests really need to be compiled with openmp support

**Comment by jeffdaily** [comment]
> Sure, let's revert it. @jeffdaily, btw, it doesn't seem like asserts work on ROCm XD

yes, kernel asserts for rocm pytorch builds are currently disabled.  
https://github.com/pytorch/pytorch/blob/56f8379802960b6cbd9973a02cb03efba14dfb7e/c10/macros/Macros.h#L260-L265

Kernel asserts and debug builds are still work in progress for rocm pytorch.  The situation is improved for our upcoming ROCm 4.1 release, according to early internal QA reports.  

I have a draft PR to enable kernel asserts, but CI was failing and I haven't tracked down all the failures yet.  #49624

**Pull request closed without merging**
