### PR TITLE
Optimize topk performance for tensor with a large dimension size

### LINKED ISSUE #38475: TopK implementation slower than a custom divide and conquer implementation
## 🐛 Bug

TopK is slower than a divide and conquer implementation with k=100 and dimension of the input 2_000_000

## To Reproduce

```python
def gpu_time(f, reps=100):
    start_event = torch.cuda.Event(enable_timing=True)
    end_event = torch.cuda.Event(enable_timing=True)
    start_event.record()

    for i in range(reps):
        y = f()

    end_event.record()
    torch.cuda.synchronize()  # Wait for the events to be recorded!
    elapsed_time_ms = start_event.elapsed_time(end_event)
    print("{} ms".format(elapsed_time_ms / reps))
    return y

def divide_and_conquer_topk(x, divide, k):
    num_outputs = x.shape[1]
    batch_size = x.shape[0]
    assert num_outputs % divide == 0
    partial = torch.topk(x.view(-1, divide, num_outputs // divide), k=k, dim=-1)
    indices_view = torch.arange(num_outputs, device='cuda').view(1, divide, num_outputs // divide)
    indices_view_2 = indices_view.expand((batch_size, divide, num_outputs // divide)).gather(index=partial.indices, dim=2).view(batch_size, -1)
    values_2d = partial.values.view(batch_size, -1)
    topk_2 = torch.topk(values_2d, k=k, dim=-1)
    return indices_view_2.gather(index=topk_2.indices, dim=-1), topk_2.values

b = 512
n = 2000000
k = 100

cuda = torch.device('cuda')
```

```python
gpu_time(lambda: torch.topk(x, k, dim=-1));
```
Took 104.4182421875 ms,
while
```python
gpu_time(lambda: divide_and_conquer_topk(x, 100, k));
```
took 86.761689453125 ms

On the CPU
```python
x = torch.rand(b,n,device='cpu')
```
The output of this is
```python
%%time
torch.topk(x, k, dim=-1)
```
CPU times: user 10.3 s, sys: 11.9 ms, total: 10.3 s

while the following
```python
%%time
divide_and_conquer_topk(x, 100, k)
```
outputs CPU times: user 7.19 s, sys: 88.8 ms, total: 7.28 s.

## Expected behavior
I did not expect such a simple implementation of topk outperforming pytorch native one.
I wonder if there is something suboptimal in topk. It might be specific for this case and so not very interesting but I thought it was surprising enough to report.

## Environment

Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Amazon Linux AMI 2018.03
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 3.13.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.15.4
[pip3] numpydoc==0.8.0
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2018.0.3                      1  
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] mkl_fft                   1.0.6            py36h7dd41cf_0  
[conda] mkl_random                1.0.1            py36h629b387_0  
[conda] numpy                     1.15.4           py36h1d66e8a_0  
[conda] numpy-base                1.15.4           py36h81de0dd_0  
[conda] numpydoc                  0.8.0                    py36_0  
[conda] pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py36_cu101    pytorch

### PR DESCRIPTION
**Pull request by xwang233**
Close #38475.

Optimize topk performance using a divide and conquer technique originally proposed in #38475.

I profiled topk performance before and after this PR for about 1000 shapes, "regular" and "irregular". The profiling script is https://github.com/xwang233/code-snippet/blob/master/topk/a.py. The performance plot is https://github.com/xwang233/code-snippet/blob/master/topk/b.ipynb. 

Most regular shapes, e.g. with a dimension size of 10**x, get improvements for about 10 times or more. Only a few "irregular" shapes got around <1.2 times slow down.

### CODE REVIEW

**Comment by xwang233** [comment]
Performance plot from the jupyter notebook

image

**Comment by xwang233** [comment]
cc @csarofeen @ptrblck

**Comment by nikitaved** [comment]
@xwang233 , the performance of `topk` is slower because of the limited reduction (dim_apply), it does not use TensorIterator. Once [#39744](https://github.com/pytorch/pytorch/pull/39744/files) is landed, this part can be easily fixed.

**Comment by xwang233** [comment]
@nikitaved , thanks for the amazing work! I'd be glad to profile the performance of `topk` and `sort` after your PR is landed. Using TensorIterator could be very helpful on sorting. We can try combine it with this PR and see if the performance gets better.

**Comment by ezyang** [comment]
This is pretty interesting. However, we can't take the PR as is, as you need to be modifying `topk_out` and not just `topk`; otherwise your performance optimization won't apply when users call topk with the `out=` argument.

Does it make sense to wait for @nikitaved's stuff and try again here?

**Comment by xwang233** [comment]
Umm, didn't realize the `topk_out` problem. I can try to add another wrapper to `topk_out` and make sure the optimization work for both `topk` and `topk_out`. 

Sure! I'll wait for their PR landed and check if this PR still improves the performance.

**Comment by robieta** [comment]
I'm observing failures when testing this PR. I've distilled down to a minimal example:

```
import torch

sizes = [
    # These will succeed.
    10000,
    100000,
    6042451,
    6042453,
    7000000,

    # This will fail.
    6042452,
]


for n in sizes:
    print(f"n = {n}")
    x = torch.rand((n,), dtype=torch.float64, device="cuda")
    for i in range(100):
        torch.topk(x, k=1, dim=0)
        print(f"\r  {i}", end="")
    print()
```


```
n = 10000
  99
n = 100000
  99
n = 6042451
  99
n = 6042453
  99
n = 7000000
  99
n = 6042452
  34THCudaCheck FAIL file=/var/svcscm/pytorch/aten/src/THC/generic/THCTensorSort.cu line=151 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "examples/test.py", line 20, in <module>
    torch.topk(x, k=1, dim=0)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /var/svcscm/pytorch/aten/src/THC/generic/THCTensorSort.cu:151
/var/svcscm/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:86: operator(): block: [0,0,0], thread: [32,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/var/svcscm/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:86: operator(): block: [0,0,0], thread: [33,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/var/svcscm/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:86: operator(): block: [0,0,0], thread: [34,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/var/svcscm/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:86: operator(): block: [0,0,0], thread: [35,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
...
```

This is built with this PR patched on top of 07e581d639961e0d460111bcd8164f303e16ca9b with GCC 7.3.0, and run on a P100.

**Comment by xwang233** [comment]
@robieta Thanks for the comment. I tried your script on my PR branch at the latest commit 11dfd1f42931ee067af3efc817579425cb5df5de, and everything seems fine. Then I rebased my PR branch on master 314d645e05074e491e24d1cc64123884e6346e20, I see the same error message as yours. I'm testing on rtx 2070. 

Probably there are changes to THCTensorSort that crashed the old topk?

**Comment by robieta** [comment]
> @robieta Thanks for the comment. I tried your script on my PR branch at the latest commit [11dfd1f](https://github.com/pytorch/pytorch/commit/11dfd1f42931ee067af3efc817579425cb5df5de), and everything seems fine. Then I rebased my PR branch on master [314d645](https://github.com/pytorch/pytorch/commit/314d645e05074e491e24d1cc64123884e6346e20), I see the same error message as yours. I'm testing on rtx 2070.
> 
> Probably there are changes to THCTensorSort that crashed the old topk?

Interesting. I don't see the crash on master without this PR, but I don't know if that's because of an issue with this PR, or because it is exposing an underlying issue with a kernel that is being called inside of the divide-and-conquer path.

**Comment by ngimel** [comment]
see #40349, topk for 4d+ tensors is busted on master.

**Comment by robieta** [comment]
I've been doing some testing (I'm trying to make testing and reviewing these sort of kernel improvement PRs easier), and I've found that this method can both significantly improve and significantly regress performance. The following code assumes that https://github.com/pytorch/pytorch/pull/38338 and https://github.com/pytorch/pytorch/pull/40349 are patched into a reference environment (base commit: `ac8c3c0ad11beba80fe02d2a988a15e3b4dcf361`), and a second environment with those two plus this PR. I haven't tested with https://github.com/pytorch/pytorch/pull/39744, but it's on the docket.

```
import torch
from utils import Timer

torch.manual_seed(0)

experiments = (
    (1, 10000, lambda: torch.rand(size=(39, 222075), device="cuda")),
    (1, 10000, lambda: torch.rand(size=(32, 262144), device="cuda")),
    (1, 4,     lambda: torch.rand(size=(39, 222075), device="cuda")),
    (1, 4,     lambda: torch.rand(size=(32, 262144), device="cuda")),

    (0, 10000, lambda: torch.rand(size=(786842, 25), device="cuda")),
    (0, 10000, lambda: torch.rand(size=(1048576, 16), device="cuda")),
    (0, 4,     lambda: torch.rand(size=(786842, 25), device="cuda")),
    (0, 4,     lambda: torch.rand(size=(1048576, 16), device="cuda")),
)

for dim, k, tensor_constructor in experiments:
    x = tensor_constructor()
    timer = Timer(
        stmt="torch.topk(x, dim=dim, k=k)",
        globals={"x": x, "dim": dim, "k": k},
        label=f"k:{k:>6}, dim:{dim}, size:{list(x.shape)}",
    )
    measurement = timer.blocked_autorange(min_run_time=5)
    print(f"{measurement.median * 1e6:>10.0f} us{'':>10}{measurement.label}")
```

Reference:
```
      3246 us          k: 10000, dim:1, size:[39, 222075]
      3423 us          k: 10000, dim:1, size:[32, 262144]
      2635 us          k:     4, dim:1, size:[39, 222075]
      3019 us          k:     4, dim:1, size:[32, 262144]
     13072 us          k: 10000, dim:0, size:[786842, 25]
     16693 us          k: 10000, dim:0, size:[1048576, 16]
     12017 us          k:     4, dim:0, size:[786842, 25]
     15999 us          k:     4, dim:0, size:[1048576, 16]
```

This PR:
```
     20131 us          k: 10000, dim:1, size:[39, 222075]
      4588 us          k: 10000, dim:1, size:[32, 262144]
       785 us          k:     4, dim:1, size:[39, 222075]
      1489 us          k:     4, dim:1, size:[32, 262144]
     31275 us          k: 10000, dim:0, size:[786842, 25]
     13675 us          k: 10000, dim:0, size:[1048576, 16]
      3975 us          k:     4, dim:0, size:[786842, 25]
      4628 us          k:     4, dim:0, size:[1048576, 16]
```

General observations:
  * This method is much more sensitive to exact power-of-two sizes than the current kernel, and can have very bad performance if sizes are not powers of two.
  * Performance tends to be much better for small `k`, and much worse for large `k`.

I'm still cleaning up the fuzzing script that I used for testing, but when I do I'll link it here. One thing that is very clear from testing is that there is definitely room for improvement in topk, so thanks for pushing on this.

**Comment by xwang233** [comment]
Thanks for the amazing work! That tests look very helpful to me. 

The current divide and conquer method chooses a "heuristic" divider in the order of 
```cpp
const int _dividers[] = {100, 50, 25, 20, 15, 12, 10, 13, 11, 7, 5, 3, 2};
```

Only when size of the dim can be divided by a divider, and k is greater than the division results, the divide and conquer method will be used. 

Now I am thinking of the bad performance for large k. This is probably because, for example, with dim size = 222075 and k = 10000, the divide and conquer method will transform that to (15, 14085). Calculating topk 15 times with k = 10000, dim size = 14085 (and a topk merge later) probably doesn't give many performance benefits. We need to find a better heuristic for large k, or simply disable that for large k. I'll do some tests on it.

**Pull request closed without merging**
