### PR TITLE
only enable cudnn persistent RNN when batchsize % 8 == 0

### PR DESCRIPTION
**Pull request by xwang233**
On A100, cuDNN persistent RNN algo doesn't work quite well when batch size is not a multiple of 8, so we need to disable it.

Related: https://github.com/pytorch/pytorch/pull/43165

### CODE REVIEW

**Comment by xwang233** [comment]
cc @ptrblck

**Comment by mcarilli** [comment]
Lgtm, thanks!

**Review by mcarilli — APPROVED** [review]

**Comment by ngimel** [comment]
Is it on A100 only? Why is it disabled everywhere then?

**Comment by xwang233** [comment]
@ngimel Is this ready to go?

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
