### PR TITLE
Install MKL library for ROCm CI builds and enable MKL tests

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@ezyang: I'm trying to enable MKL support for CI ROCm builds in this PR. I enabled the following line for ROCm builds: `pip install mkl mkl-devel`

It's giving a permission denied error when trying to install MKL:
```
os.makedirs(path)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/intel_openmp-2020.0.133.dist-info'
```
Any reason this would happen only for ROCm builds?

**Comment by ezyang** [comment]
> Any reason this would happen only for ROCm builds?

Well, ROCm is still using the Caffe2 images, which are setup differently, so that would at least "explain" why it's different. The best thing to do is just directly install mkl inside of the docker image so you don't have to do it (hint hint nudge nudge). Second best is probably to use 'sudo' here.

**Comment by jithunnair-amd** [comment]
@jeffdaily to comment on installing mkl inside docker image.

**Comment by jithunnair-amd** [comment]
Shelving this effort for now. cc @jeffdaily

**Pull request closed without merging**
