### PR TITLE
Add labeler with dynamo/inductor paths to start

### PR DESCRIPTION
**Pull request by ezyang**
The other missing ingredient is getting CC bot to work on labels on PRs

### CODE REVIEW

**Review by soumith — APPROVED** [review]
awesomesauce

**Review by jansel — APPROVED** [review]
Yay!  Thanks!

**Comment by janeyx99** [comment]
Porting and consolidating this with https://github.com/pytorch/test-infra/blob/main/torchci/lib/bot/autoLabelBot.ts would be good. cc’ing @ZainRizvi

**Comment by ezyang** [comment]
FWIW path mappings in an external repo requiring extra deploy step guarantees that no one outside of dev infra will be able to update it.

**Pull request closed without merging**
