### PR TITLE
[TorchElastic] make libuv TCPStore as default in torch elastic rendezvous

### PR DESCRIPTION
**Pull request by XilunWu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128168

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @penguinwu @tianyu-l @yf225 @chauhang

Differential Revision: [D58259590](https://our.internmc.facebook.com/intern/diff/D58259590)

### CODE REVIEW

**Comment by XilunWu** [comment]
@XilunWu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D58259590).

**Review by kurman — COMMENTED** [review]
We need to make change to https://github.com/pytorch/pytorch/blob/main/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py#L65C27-L65C35 as well

**Comment by XilunWu** [comment]
@XilunWu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D58259590).

**Comment by XilunWu** [comment]
@XilunWu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D58259590).

**Review by kurman — APPROVED** [review]

**Comment by XilunWu** [comment]
note: check internal CI. Seems we need give `use_libuv` argument a default.

**Comment by XilunWu** [comment]
@XilunWu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D58259590).

**Comment by XilunWu** [comment]
@XilunWu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D58259590).

**Comment by XilunWu** [comment]
@XilunWu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D58259590).

**Comment by XilunWu** [comment]
closing this PR as we will land through internal

**Comment by XilunWu** [comment]
merged in https://github.com/pytorch/pytorch/pull/134882

**Pull request closed without merging**
