### PR TITLE
Deprecate and set a date for removing NO_* and WITH_* (user) build options

### PR DESCRIPTION
**Pull request by xuhdev**
Currently specifying different build options in respect to the "USE_"
series is in quite a disarray. There are a lot of build options that
accept three variants: USE_OPTION, WITH_OPTION, and NO_OPTION. Some
build options only accept USE_ and NO_ variant. Some accept only USE_.
This inconsistency is quite confusing and hard to maintain.

To resolve this inconsistency, we can either let all these build options
support all three variants, or we only support the USE_ variant.

This commit makes a step to the latter choice, i.e., deprecates and sets
a date for removing the NO_ and WITH_ variants and keeps only the
USE_ variant. This is likely better than the former solution because:

- NO_ and WITH_ variants are not documented.
- CMakeLists.txt only has the USE_ variants for relevant build options
  defined. It would be a surprise that when user pass these variables to
  CMake during rebuild and find them ineffective.
- Multiple variants are difficult to maintain.
- The behavior is confusing if more than one variant is passed. For
  example, what to be expected if one sets "NO_CUDA=1 USE_CUDA=1"?

The downside is that this will break backward compatibility for existing
build scripts in the future (if they used the undocumented build
options).

### CODE REVIEW

**Comment by xuhdev** [comment]
The test is expected to fail because the current change is seminal. I will complete this PR (e.g., fixing various spots in CI) if it is agreed that breaking BC is acceptable.

**Comment by pjh5** [comment]
There's no technical reason we can't do this, only issue is how many of our users will be tripped up by this. cc @soumith for context.

With these changes NO_ and WITH_ variants will now have no effect and be silently ignored. In the meantime we could still detect these and error out instead.

**Comment by ezyang** [comment]
Yeah, I'd definitely feel better if we deprecated first, and then
removed them later.

Excerpts from Paul Jesse Hellemn's message of 2019-07-03 08:37:17 -0700:
> There's no technical reason we can't do this, only issue is how many of our users will be tripped up by this. cc @soumith for context.
> 
> With these changes NO_ and WITH_ variants will now have no effect and be silently ignored. In the meantime we could still detect these and error out instead.
>

**Comment by xuhdev** [comment]
OK, I'll change this to deprecation for now. How about also setting a date for removal? How about Feb 1, 2020?

**Comment by ezyang** [comment]
SGTM.  I'd also be OK with a shorter time window.

Excerpts from Hong Xu's message of 2019-07-03 13:43:54 -0700:
> OK, I'll change this to deprecation for now. How about also setting a date for removal? How about Feb 1, 2020?
>

**Comment by xuhdev** [comment]
Updated

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
