### PR TITLE
[ROCm] install_miopen.sh exit for ROCm >= 6.3

### PR DESCRIPTION
**Pull request by jeffdaily**
Follow up to #132555.

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@jeffdaily Should/would this not be part of the set of changes for ROCm6.3 upgrade in the future? Trying to understand the motivation for making this ROCm6.3-specific change now.

**Review by jithunnair-amd — APPROVED** [review]
LGTM otherwise

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
> @jeffdaily Should/would this not be part of the set of changes for ROCm6.3 upgrade in the future? Trying to understand the motivation for making this ROCm6.3-specific change now.

@jithunnair-amd , 
Internal dev builds of ROCm 6.3 are breaking on upstream main branch. So we need to handle this case.

**Review by atalman — APPROVED** [review]
lgtm. What is the ETA for Rocm 6.3 CD builds ?

**Comment by jeffdaily** [comment]
> lgtm. What is the ETA for Rocm 6.3 CD builds ?

November.

**Pull request closed without merging**
