### PR TITLE
Batching rules matrix exp

### LINKED ISSUE #115992: Please implement the batching rule for torch.matrix_exp.
### 🚀 The feature, motivation and pitch

Matrix exponentials are extremely expensive to compute, yet very important in many computing and ML problems . It would be great if such computational expensive functions can support batch implementations. Many thanks in advance for those who can help with this issue!

### Alternatives

_No response_

### Additional context

This below is the warning message from pytorch kernel: <ipython-input-13-6cfa90bb24a5>:3: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::matrix_exp. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\functorch\BatchedFallback.cpp:84.)

### PR DESCRIPTION
**Pull request by Xiao215**
Fixes #115992

This is a follow up on PR #116377

Added matrix_exp to BatchRulesDecomposition.

cc @zou3519 @Chillee @samdow @kshitij12345 @janeyx99

### CODE REVIEW

**Comment by Xiao215** [comment]
Anyone knows why I got an `Error: Process completed with exit code 128.`?

**Review by zou3519 — APPROVED** [review]

**Comment by zou3519** [comment]
> Anyone knows why I got an `Error: Process completed with exit code 128.`?

That one is unrelated, we can ignore it.

**Comment by zou3519** [comment]
Please shout in three days if I haven't merged this yet

**Review by zou3519 — CHANGES_REQUESTED** [review]
test failures look real

**Comment by ZelboK** [comment]
@zou3519

Curious to know why you think this is failling? Locally I get this, 

```
File "/home/ksm/pytorch/test/functorch/test_vmap_registrations.py", line 308, in test_unimplemented_batched_registrations
    assert registration in FuncTorchBatchedDecompositionRegistrations, (
AssertionError: Please check that there is an OpInfo that covers the operator aten::matrix_exp and add a registration in BatchedRulesDecompositions.cpp. If your operator isn't user facing, please add it to the xfail list
```
which is different from what the pipeline describes.

**Pull request closed without merging**
