### PR TITLE
DeviceMesh use dispatchable PG to support custom backend

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #102336
* #102470

This PR switches DeviceMesh to use dispatchable process group instead,
this could enable easier backend integration as user only need to
integrate with c10d process group custom backend, without needing to
change DeviceMesh to plug in the backend

### CODE REVIEW

**Comment by XilunWu** [comment]
hey Wanchao, quick question. Does this PR enable object-based collective calls to use `cpu` by default?

**Review by fduwjj — APPROVED** [review]
LGTM, just few nits.

**Comment by wanchaol** [comment]
> hey Wanchao, quick question. Does this PR enable object-based collective calls to use `cpu` by default?

idk tbh, why do we care about it though?

**Pull request closed without merging**
