### PR TITLE
[1/N] Fix clang-tidy warnings in jit

### PR DESCRIPTION
**Pull request by cyyever**
Some some tidy warnings

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
I'm surprised clang-tidy is persnickety about throw(...), I definitely did not have the impression that parentheses here was idiomatic.

**Comment by ezyang** [comment]
Please be careful when switching from int to size_t, the latter is unsigned so negative comparisons will no longer work

**Comment by cyyever** [comment]
> I'm surprised clang-tidy is persnickety about throw(...), I definitely did not have the impression that parentheses here was idiomatic.

There was some operator priority problem here, and it warned about not throwing a temporary object. Just adding () to make tidy happy.

**Comment by cyyever** [comment]
> Please be careful when switching from int to size_t, the latter is unsigned so negative comparisons will no longer work

In this case size_t is used solely for array indexing so the changes should be safe.

**Comment by ezyang** [comment]
Yes, I spot checked a few. Just mentioning.

**Pull request closed without merging**
