### PR TITLE
Re-enable py3.12 nightly wheel builds and add triton dependency for ROCm 

### PR DESCRIPTION
**Pull request by jithunnair-amd**
The llnl-hatchet developers have published the py3.12 binaries on [PyPI](https://pypi.org/project/llnl-hatchet/#files). In fact, looking [here](https://download.pytorch.org/whl/nightly/llnl-hatchet), it seems we already have the py3.12 wheels mirrored. This should allow us to re-enable py3.12 binaries for ROCm.

This PR reverts commit 9d849d4312cd1e62d97b9e9d58979ec78d36c95f.

It also adds the pytorch-triton-rocm dependency for torch wheels on ROCm since pytorch-triton-rocm py3.12 wheels are available now

Fixes #ISSUE_NUMBER

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
https://github.com/pytorch/pytorch/actions/runs/9554056555/job/26338950966#step:10:400 shows:
1. pytorch-triton-rocm is now a dependency of the py3.12 torch wheels for ROCm
2. all the dependencies of pytorch-triton-rocm (including llnl-hatchet and its further dependencies) are available in download.pytorch.org.

@atalman I think this PR is ready for merge.

**Comment by jithunnair-amd** [comment]
@atalman @malfet Please review and approve.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
