### PR TITLE
Explicitly import functional into the torch.nn namespace

### PR DESCRIPTION
**Pull request by willfrey**
The `torch.nn.functional` module is not currently imported into the `torch.nn` namespace. This causes Pylance, at a minimum, to complain about it not being a known member.

This should not add any overhead because `torch.nn.functional` is being imported implicitly in these two common scenarios, at least.

```py3
import torch

assert "functional" in dir(torch.nn)
```

```py3
from torch import nn

assert "functional" in dir(nn)
```

This change adds an explicit import.

### CODE REVIEW

**Comment by willfrey** [comment]
It looks like binary_macos_libtorch_3_7_cpu_nightly_build, binary_windows_conda_3_8_cu102_nightly_build, and binary_windows_wheel_3_9_cu102_nightly_build either errored or failed.

Is there anything I can do to re-run these? I don't think it's due to my simple change here.

**Comment by jbschlosser** [comment]
@willfrey Try rebasing on master- maybe those failures will go away. If not, no big deal as long as they're unrelated

**Comment by willfrey** [comment]
I think this is good to go

**Comment by willfrey** [comment]
@jbschlosser Let me know if this needs anything else. Everything seems to be passing 😄 and I would hope so, given that it's only a single-line change!

**Review by jbschlosser — APPROVED** [review]
I think this is good! Thanks :)

**Pull request closed without merging**
