### PR TITLE
[ROCm] Enable python ref executor UTs for ROCm

### PR DESCRIPTION
**Pull request by pruthvistony**
cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### CODE REVIEW

**Comment by mruberry** [comment]
Hey @pruthvistony -- how does this test work when run on ROCm? Does test try to use ATen and nvFuser as executors still?

**Comment by pruthvistony** [comment]
> Hey @pruthvistony -- how does this test work when run on ROCm? Does test try to use ATen and nvFuser as executors still?
From the test execution logs I see many aten operators are executing fine. Eg: - add, abs, atan, etc... Any specific operator you want me to check?
Regarding the NVFuser, it is enabled for ROCm and for the ref_executors see float32 and int32 data types executed for few operators similar to CUDA.
[link1] (https://github.com/pytorch/pytorch/actions/runs/3459181591/jobs/5774552385)
[link2] (https://pipelines.actions.githubusercontent.com/serviceHosts/7d146c05-69c3-4c20-a0e7-818111670117/_apis/pipelines/1/runs/2388164/signedlogcontent/335?urlExpires=2022-11-14T20%3A55%3A55.1676130Z&urlSigningMethod=HMACV1&urlSignature=KaEHB%2FWQeabdoua99Thy3y1dK8z%2FVkeC%2F3qXr3WeH8c%3D)

**Comment by pruthvistony** [comment]
> Hey @pruthvistony -- how does this test work when run on ROCm? Does test try to use ATen and nvFuser as executors still?

From the test execution logs I see many aten operators are executing fine. Eg: - add, abs, atan, etc... Any specific operator you want me to check?
Regarding the NVFuser, it is enabled for ROCm and for the ref_executors see float32 and int32 data types executed for few operators similar to CUDA.
[link1](https://github.com/pytorch/pytorch/actions/runs/3459181591/jobs/5774552385)
[link2](https://pipelines.actions.githubusercontent.com/serviceHosts/7d146c05-69c3-4c20-a0e7-818111670117/_apis/pipelines/1/runs/2388164/signedlogcontent/335?urlExpires=2022-11-14T20%3A55%3A55.1676130Z&urlSigningMethod=HMACV1&urlSignature=KaEHB%2FWQeabdoua99Thy3y1dK8z%2FVkeC%2F3qXr3WeH8c%3D)

**Review by mruberry — APPROVED** [review]
Cool

**Pull request closed without merging**
