### PR TITLE
Support defaultdict with enum tuple keys

### LINKED ISSUE #107595: torch._dynamo.exc.Unsupported: call_method UserDefinedObjectVariable(defaultdict) items [] {}
### 🐛 Describe the bug

occurs in torchrec FusedEmbeddingBagCollection

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

### PR DESCRIPTION
**Pull request by Fidget-Spinner**
Fixes https://github.com/pytorch/pytorch/issues/107595

This fix is so big because it's actually two things: adding `defaultdict.items()` support, and also adding the ability for dictionaries to have tuples of enum values as keys.

Reproducer credits to [Animesh Jain](https://github.com/anijain2305).

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by Fidget-Spinner** [comment]
This will need a huge amount of touch up...

**Comment by lezcano** [comment]
I am in the process of doing a fairly large update to how dicts are internally implemented, fixing plenty of bugs along the way. Can I take over this one as well, not to step on each others toes?

**Comment by lezcano** [comment]
Missclicked "close" rather than comment, sorry!

**Comment by Fidget-Spinner** [comment]
@lezcano sorry for the late reply, yeah sure go ahead!

**Comment by lezcano** [comment]
For further reference, the PR is a thttps://github.com/pytorch/pytorch/pull/111196

**Pull request closed without merging**
