### PR TITLE
use other dll paths

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Review by peterjc123 — CHANGES_REQUESTED** [review]
I think you've misunderstood the usage of `os.add_dll_directory`. It is used to add the dll directories that may be used in finding the DLLs. The API is initially inspired by the idea that some other DLLs may be loaded because of the misconfiguration of `PATH`. e.g. If you have a DLL in `SystemRoot` that is named `torch.dll`, then it will be picked which leads to a failing import.

In your PR, you tries to load all the directories in PATH, which is against the aforementioned idea to add fewer directories for DLL search as possible. What's worse is that the directory added through the underlying API `AddDllDirectory` doesn't have an order. Details: https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-adddlldirectory#remarks

As for the release version of PyTorch, I think the existing DLL search paths should be enough. If you build PyTorch by yourself, then maybe you should install or add the paths of `intel-openmp` manually. Otherwise should work fine.

**Comment by cyyever** [comment]
> 
> 
> I think you've misunderstood the usage of `os.add_dll_directory`. It is used to add the dll directories that may be used in finding the DLLs. The API is initially inspired by the idea that some other DLLs may be loaded because of the misconfiguration of `PATH`. e.g. If you have a DLL in `SystemRoot` that is named `torch.dll`, then it will be picked which leads to a failing import.
> 
> In your PR, you tries to load all the directories in PATH, which is against the aforementioned idea to add fewer directories for DLL search as possible. What's worse is that the directory added through the underlying API `AddDllDirectory` doesn't have an order. Details: https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-adddlldirectory#remarks
> 
> As for the release version of PyTorch, I think the existing DLL search paths should be enough. If you build PyTorch by yourself, then maybe you should install or add the paths of `intel-openmp` manually. Otherwise should work fine.

No, It loads the directories containing the needed dlls.

**Comment by peterjc123** [comment]
> > I think you've misunderstood the usage of `os.add_dll_directory`. It is used to add the dll directories that may be used in finding the DLLs. The API is initially inspired by the idea that some other DLLs may be loaded because of the misconfiguration of `PATH`. e.g. If you have a DLL in `SystemRoot` that is named `torch.dll`, then it will be picked which leads to a failing import.
> > In your PR, you tries to load all the directories in PATH, which is against the aforementioned idea to add fewer directories for DLL search as possible. What's worse is that the directory added through the underlying API `AddDllDirectory` doesn't have an order. Details: https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-adddlldirectory#remarks
> > As for the release version of PyTorch, I think the existing DLL search paths should be enough. If you build PyTorch by yourself, then maybe you should install or add the paths of `intel-openmp` manually. Otherwise should work fine.
> 
> No, It loads the directories containing the needed dlls.

Could you please elaborate a bit more? What issue does this PR solve? If there's a dll loading issue without this change, could you please attach the logs with Process Monitor?

**Comment by cyyever** [comment]
@peterjc123 I need it now to load mkl dll.

**Comment by peterjc123** [comment]
> @peterjc123 I need it now to load mkl dll.

I don't think this is a good change. But if you could tell me where your MKL DLLs are, then I can accept the PR to find them.

**Comment by cyyever** [comment]
> 
> 
> > @peterjc123 I need it now to load mkl dll.
> 
> I don't think this is a good change. But if you could tell me where your MKL DLLs are, then I can accept the PR to find them.

My MKL DLLs are in ~/opt/ now. And I think that the current behavior prohibits other dependencies such as glog on Windows. It breaks easily if I install CUDA on D:\CUDA.

**Comment by peterjc123** [comment]
> And I think that the current behavior prohibits other dependencies such as glog on Windows.

Yes, that's correct. But I think it can be resolved by installing the DLLs to the corresponding directory. (e.g. `lib` for PyTorch)



> It breaks easily if I install CUDA on D:\CUDA.

It shouldn't be. We read from `CUDA_PATH`.

**Pull request closed without merging**
