### PR TITLE
Fix compiler error in swapBytes64 for rare architectures

### PR DESCRIPTION
**Pull request by BRevolution**
swapBytes64 used to use SwapByteOrder_32 and value, both of which dont exist. This commit rewrites that part from scratch.
This happened on Debugbuild on Microsoft compiler. For that case " && !defined(_DEBUG)" is also removed, because _byteswap_uint64 works fine in debug mode (if it is necessary it should me commented why).

### CODE REVIEW

**Comment by peterjc123** [comment]
@BRevolution So what is the motivation to rewrite the code in the `else` part?

**Comment by BRevolution** [comment]
Well, it was dead code, the function it called doesn't exist. I rewrote it just so that it works. It's implemented now similar to the function above for the 32 bit variant

**Comment by peterjc123** [comment]
cc @resistor @soumith

**Comment by resistor** [comment]
The "!defined(_DEBUG)"" came from the corresponding implementation in LLVM.  That particular bit dates from at least 2010, and it isn't clear from the commit message what it's intended for.  I would guess it was working around a bug in some ancient MSVC version that we don't care about.

**Review by ezyang — APPROVED** [review]
Seems reasonable enough

**Pull request closed without merging**
