### PR TITLE
Impl for ParameterList

### PR DESCRIPTION
**Pull request by arktrail**
Summary: 
This diff contains the implementation of C++ API for ParameterList from #25883. 
Refer to the Python API: https://github.com/pytorch/pytorch/blob/bc9e8af21875dafafe9bbd25c8f542b20b2e660f/torch/nn/modules/container.py#L376
Not sure about some naming difference between C++ API and Python API, like `append`, should it be called `push_back`

Test Plan: Add unit tests in this diff

Reviewers: @glaringlee 

Subscribers:

Tasks: #25883

Tags:

### CODE REVIEW

**Review by glaringlee — CHANGES_REQUESTED** [review]
@yyn19951228 Thanks a lot for your help!!!
There are some tests failure and caused seg fault, let's fix that first. You'd better rebase your code to pickup the latest master branch as well.

ExtendPushesParametersFromOtherParameterList
PrettyPrintParameterList
These two tests can not pass, and the first one caused segment fault.

Can you run the test locally after compiling? The test executable is build/bin/test_api, this is a standard gtest executable, you can use --gtest_filter to run parameterList tests only.

**Comment by yyn19951228** [comment]
@glaringlee Thanks for your review! Sure, I will work on fixing this failed tests.

**Comment by yyn19951228** [comment]
Sorry I made a wrong rebase. I will abandon this diff and create a new one.

**Comment by glaringlee** [comment]
This one has rebase issue, #40987 is created instead. Close this one now.

**Pull request closed without merging**
