### PR TITLE
[TEST] Skip test_schema_correctness for float8 dtype

### PR DESCRIPTION
**Pull request by Aidyn-A**
According to the https://github.com/pytorch/pytorch/issues/107256#issuecomment-1705341870 the ops tested in `test_schema_correctness` are not supported with `torch.float8_e4m3fn` yet. Until they are not supported, it is best to skip the test.

cc @mruberry @ZainRizvi @yanbing-j @vkuzo @albanD @kadeng

### CODE REVIEW

**Comment by albanD** [comment]
I'm confused, why would we skip tests that pass?

**Comment by Aidyn-A** [comment]
> I'm confused, why would we skip tests that pass?

@albanD, it does not skip that pass, as they all fail. I can make make skips in each individual `OpInfo`, if that is what you imply.

**Comment by albanD** [comment]
But CI is green? :D

**Comment by Aidyn-A** [comment]
> But CI is green? :D

Right, it is green because there aren't `float8` capable devices. We found this failure on H100 machine.

**Comment by drisspg** [comment]
Yeah we don't currently have any machines capable of testing fp8 in CI/CD. I think this makes sense, and just to confirm this failed for you while running these tests on H100?

**Review by drisspg — APPROVED** [review]

**Comment by Aidyn-A** [comment]
> this failed for you while running these tests on H100?

That is right. We are seeing this failure on H100:
```
=================================== FAILURES ===================================
_ TestSchemaCheckModeOpInfoCUDA.test_schema_correctness_torch__scaled_mm_cuda_float8_e4m3fn _
Traceback (most recent call last):
  File "/home/user/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/user/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/home/user/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/user/python/dist-packages/torch/testing/_internal/common_utils.py", line 2536, in wrapper
    method(*args, **kwargs)
  File "/home/user/python/dist-packages/torch/testing/_internal/common_utils.py", line 2536, in wrapper
    method(*args, **kwargs)
  File "/home/user/python/dist-packages/torch/testing/_internal/common_device_type.py", line 428, in instantiated_test
    raise rte
  File "/home/user/python/dist-packages/torch/testing/_internal/common_device_type.py", line 415, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/user/python/dist-packages/torch/testing/_internal/common_device_type.py", line 945, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/home/user/python/dist-packages/torch/testing/_internal/common_device_type.py", line 908, in test_wrapper
    return test(*args, **kwargs)
  File "/home/user/git/pytorch/test/test_schema_check.py", line 502, in test_schema_correctness
    op(sample.input, *sample.args, **sample.kwargs)
  File "/home/user/python/dist-packages/torch/testing/_internal/opinfo/core.py", line 1105, in __call__
    return self.op(*args, **kwargs)
  File "/home/user/python/dist-packages/torch/_subclasses/schema_check_mode.py", line 172, in __torch_dispatch__
    if any(
  File "/home/user/python/dist-packages/torch/_subclasses/schema_check_mode.py", line 173, in <genexpr>
    has_mutated(a, b, c)
  File "/home/user/python/dist-packages/torch/_subclasses/schema_check_mode.py", line 63, in has_mutated
    and bitwise_equal(before, after)
  File "/home/user/python/dist-packages/torch/_subclasses/schema_check_mode.py", line 52, in bitwise_equal
    return torch.allclose(lhs, rhs, equal_nan=True)
RuntimeError: "mul_cuda" not implemented for 'Float8_e4m3fn'

To execute this test, run the following from the base repo dir:
     python test/test_schema_check.py -k test_schema_correctness_torch__scaled_mm_cuda_float8_e4m3fn
```

**Review by drisspg — APPROVED** [review]
Thanks!

**Pull request closed without merging**
