### PR TITLE
parallel_apply should forward current streams to worker threads

### PR DESCRIPTION
**Pull request by jeffdaily**
#71033 moved test_data_parallel_module et al under `instantiate_device_type_tests`.  This had the side effect of now running the tests on a non-default stream.  The parallel_apply creates new threads, one per device, but does not forward the thread local current streams from the parent thread.  This defaults the new per-device threads to use the null stream.  The null stream will not sync with the non-default non-blocking streams, resulting in errors when these tests assert tensors are equal.

CC @janeyx99

### CODE REVIEW

**Comment by jeffdaily** [comment]
The 1 CI failure is not related to this PR's changes.  Flaky test.

**Comment by jeffdaily** [comment]
Can we please get a review for this?

**Review by pruthvistony — APPROVED** [review]

**Comment by jeffdaily** [comment]
@janeyx99 we really need this merged.

**Comment by jithunnair-amd** [comment]
cc @malfet Please review and merge this long-standing PR

**Review by janeyx99 — APPROVED** [review]

**Comment by janeyx99** [comment]
@jeffdaily sorry about not seeing these pings! Just approved

**Comment by janeyx99** [comment]
hey @jeffdaily--can you rebase this PR and then merge with

`@pytorchbot merge -g`?

**Pull request closed without merging**
