### PR TITLE
Update pinverse doc for recent commit

### PR DESCRIPTION
**Pull request by albanD**

### CODE REVIEW

**Review by vishwakftw — APPROVED** [review]
Thanks @albanD. Sorry I missed doing this earlier.

**Comment by albanD** [comment]
No problem, glad it made it to 1.3 !

**Review by ezyang — APPROVED** [review]

**Comment by albanD** [comment]
I wasn't considering this as critical. Especially because most people look at the master doc anyway.
But if you have a strong opinion about this, I'm open to discussion.

**Comment by vishwakftw** [comment]
I thought it would be nice to have an updated documentation, that's why I thought if you'd like to cherry-pick the commit.

**Pull request closed without merging**
