### PR TITLE
torch.Package reverse dependencies printer

### PR DESCRIPTION
**Pull request by lobstergrindset**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#52355 torch.Package reverse dependencies printer**

Debugging tool to print out the reverse dependencies for a module (the modules which require the inquired about module to be included). 

```
e.print_reverse_dependencies("torch")
```

output:
```
Modules which depend on 'torch':
│ [bar.model_1.pkl] -> [torch]
│ [bar.model_1.pkl] -> [torchvision.models.resnet] -> [torch]
│ [foo.model_2.pkl] -> [torchvision.models.resnet] -> [torch]
│ [foo.model_2.pkl] -> [torch]
└
```

If no dependencies are found: 
```
Modules which depend on 'torchvision/models/resnet':
│ None
└
```

### CODE REVIEW

**Comment by Lilyjjo** [comment]
I'm not sure what the best way to display this data is, this listing of chained dependencies made sense to me, but I can rewrite the output to be in a different form

**Comment by zdevito** [comment]
Can you say more about how this intended to be used? `_write_dep_graph` already produces a visualization of module dependencies that contains this information. I've found that in practice I can easily find where to fix-up dependencies when seeing a graph, but I feel less capable just seeing a text printout. For instance if `sys` is required, it is probably not because it is directly required in many places, but because one library that was not intended to be included was accidentally included.

**Comment by suo** [comment]
The graph is sadly too big to be informative on some of the giant internal
recommendation models. Haven’t looked at this yet but the idea is to
provide a more programmatic interface for inspecting the graph as a
supplement.

**Comment by Lilyjjo** [comment]
I can look into just providing filtering to the _write_dep_graph so users can control what is fed to that viewing mechanism. Having to go click on the URL and view it in a different window isn't my preferred user experience. I'd rather stay in my terminal (but that's personal preference)

**Comment by zdevito** [comment]
I feel like printing all the paths is going to be strictly more information to display than a graph form since things along the paths have to printed multiple times (see torchvision.models.resnet). 

What happens if you just display the parts of the graph that eventually reach the target module, similar to the print out?

When I tried to do a bunch of packaging simply relying on text wasn't cutting it, which is why I wrote the graph viewer in the first place. Text hides 'choke-point' modules where the removal of that dep can eliminate the actual dependency. Having done this for the benchmark models, my experience is most of the things that need to be mocked are these intermediate models, which are easy to spot with the graph.

**Comment by Lilyjjo** [comment]
I can rewrite the output to be more graph like! I'm going to add 'ascii artist' to my list of skills

**Review by suo — CHANGES_REQUESTED** [review]
Discussed offline about this: I think, similar to the file structure PR, it's good to provide users with a basic dependency graph data structure that they can do their own thing on. That way they can do whatever they want in terms of querying/visualization and we don't have to impose any particular scheme on them.

To reproduce the current functionality, this depedency graph class should provide a method: `to_graphviz(format: str)`. The arguments to format can be `"visual"` and `"dot"`. "visual" returns a link to the website as it currently does. "dot" just returns the `.dot` string so that users can use their own graphviz thingy on it.

**Pull request closed without merging**
