### PR TITLE
[New Feature] Parallel Module Map

### PR DESCRIPTION
**Pull request by DhruvSrikanth**
## Feature Description
The new feature (function) i.e. `torch.nn.parallel.parallel_module_map` enables the following:

> - Enables devs to map an input to various model pipelines (each defined as an `nn.Module`). This includes providing different *input kwargs* to each model pipeline to be computed in parallel. The hope is that this will help scientists in model design.

> - Provides devs with more fine-grained control templates to distributed training through model-based parallelism. This can contributes functionality that enables distributed batching of tensors. The hope is that this will help engineers in model deployment/testing/inference/scaling.

## Note
The **new feature** is similar to the `torch.nn.parallel.parallel_apply` function.

## Motivation

My reasoning for implementing this function was two-fold, each touching on the points mentioned above. I had 4 different feature extraction models that I was using. Each was better than the rest in different scenarios. So I needed a function that mapped each model (which was an instance of `nn.Module`) to the input (some string). However, I needed one that allowed me to pass different *kwargs* with the common input across each of the models. I was then able to take the weighted average of these feature vectors produced to achieve a small improvement in OOD performance. However, I needed a way to deploy this effectively. Coincidently, I had access to exactly 4 GPU's, so it made sense to distributed the forward pass of each model over an entire GPU. 

Hope this helps!

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### CODE REVIEW

**Comment by albanD** [comment]
Will let @wconstab comment if we want such a feature.

@DhruvSrikanth note that we usually discuss new features on an issue before doing a PR to make sure there is interest for adding the feature before you go through the trouble of writing the PR.

**Comment by DhruvSrikanth** [comment]
Sure thing! I'll keep that in mind 👍🏽

**Comment by DhruvSrikanth** [comment]
Would it be okay to implement a feature mentioned in the issues even if I am not the author of the issue? @albanD

**Comment by albanD** [comment]
You can comment on the issue saying you're working on it.

**Comment by DhruvSrikanth** [comment]
I wanted to follow up on the PR @wconstab

**Comment by DhruvSrikanth** [comment]
following up on this @albanD @wconstab @jbschlosser @mikaylagawarecki

**Comment by albanD** [comment]
cc @wconstab if that is something that you want on the distributed side?

**Comment by wconstab** [comment]
I'm not sure. It sounds well motivated but I haven't written a model like that. Cc @wanchaol @xw285cornell for more input

**Comment by kwen2501** [comment]
Curious, does this sound like expert parallel?

**Comment by DhruvSrikanth** [comment]
Could you elaborate on what you mean by ***expert parallel***? @kwen2501

**Comment by DhruvSrikanth** [comment]
CCing @wconstab @wanchaol @xw285cornell for more input and reopening the PR.

**Pull request closed without merging**
