### PR TITLE
Make Tensor.unfold CompositeImplicit

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #85548

This function is just a clever call to `as_strided`. As such, it should
be CompositeImplicit.

Tests are failing now because `as_strided` does not have correct
backward implementation (as per the OpInfo). I'll investigate that

### CODE REVIEW

**Comment by lezcano** [comment]
I also need to fix that functionalisation function as well.

**Comment by zou3519** [comment]
@lezcano -- as_strided isn't supported by all backends or dispatcher features. E.g., vmap will work with Tensor.unfold unconditionally, but it doesn't work very well with as_strided.  So we shouldn't make Tensor.unfold CompositeImplicit and call as_strided. This is one of the reasons why all of PyTorch's view operations (aside from as_strided) aren't CompositeImplicit

**Comment by lezcano** [comment]
I don't undestand the part
> This is one of the reasons why all of PyTorch's view operations (aside from as_strided) aren't CompositeImplicit

`as_strided` is not `CompositeImplicit`.

**Comment by zou3519** [comment]
> I don't undestand the part
> 
> > This is one of the reasons why all of PyTorch's view operations (aside from as_strided) aren't CompositeImplicit
> 
> `as_strided` is not `CompositeImplicit`.

We could have written all of PyTorch's view operations (like slice, select, narrow, diag, ...) to be CompositeImplicitAutograd and have them directly call as_strided. One of the reasons why we did not is because as_strided doesn't work with all dispatcher functionalities.

**Comment by zou3519** [comment]
> `as_strided` is not `CompositeImplicit`.

You're right, that's my bad

**Comment by nikitaved** [comment]
I think we could do it with a combination of `reshape` and `slice`. Both seem to be suitable for autograd.

**Pull request closed without merging**
