### PR TITLE
Update cpuinfo to the latest commit

### LINKED ISSUE #83594: third_party/cpuinfo commit needs to be updated
### 🐛 Describe the bug

cpuinfo is not able to detect aarch64 bf16 devices because the cpuinfo commit is more than 1 year old and the aarch64 bf16 detection has been added recently.

### Versions

current commit:
~~~
commit 5916273f79a21551890fd3d56fc5375a78d1598d (grafted, HEAD)
Author: Nikita Shulga <nshulga@fb.com>
Date:   Thu Dec 17 12:05:37 2020 -0800
~~~

The minimum required commit:
~~~
commit 6288930068efc8dff4f3c0b95f062fc5ddceba04
Author: snadampal <87143774+snadampal@users.noreply.github.com>
Date:   Mon Feb 28 08:42:57 2022 -0600
~~~

cc @seemethere @malfet @pytorch/pytorch-dev-infra

### PR DESCRIPTION
**Pull request by huydhn**
This hasn't been updated for a while, so pulling the latest commit from https://github.com/pytorch/cpuinfo. I wonder if it breaks anything

Fixes #83594

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM(but why the change is still a draft)

**Comment by huydhn** [comment]
> LGTM(but why the change is still a draft)

Oh, I'm just waiting for the tests to pass before un-draft it :)

**Pull request closed without merging**
