### PR TITLE
[quant][fx][graphmode] Fix a bug for sub

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #65109

Summary:
Previously for sub we set the dtype for sub with qconfig since it's matched with a QuantizeHandler,
however this is incorrect, the dtype for sub is decided by whether the output is quantized or not,
so we added a check of is_output_quantized while deciding the dtype for the output of sub.

Later: is_output_quantized now depends on is_reference, which is pretty confusing and it may cause problems down the road, we should remove this dependency in the future.

Test Plan:
python test/test_quantization.py TestQuantizeFx.test_sub_scalar

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D30977826](https://our.internmc.facebook.com/intern/diff/D30977826)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30977826).

**Comment by vkuzo** [comment]
> the dtype for sub is decided by whether the output is quantized or not,

sorry, what does this mean?  Does this mean we need to look ahead in the graph to get the dtype?  Or should it be "dtype for sub is decided by dtype of input"?

**Comment by jerryzh168** [comment]
> > the dtype for sub is decided by whether the output is quantized or not,
> 
> sorry, what does this mean? Does this mean we need to look ahead in the graph to get the dtype? Or should it be "dtype for sub is decided by dtype of input"?

oh, no we don't need to look ahead, this is confusing, the output dtype for sub is decided by the output of `quantize_handler.is_output_quantized`, this is the function we use to show whether the output is quantized or not, if the output is quantized, then it means it's quantized to the dtype of qconfig, if it's not quantized, then it is fp32.

I think we'll need a refactor for these logic, hope to make it easier to understand when we gradually separate out the fbgemm specific path and the reference path

**Review by vkuzo — APPROVED** [review]
sure

> Later: is_output_quantized now depends on is_reference, which is pretty confusing and it may cause problems down the road, we should remove this dependency in the future.

my 5c, ideally this would be done soon

**Comment by jerryzh168** [comment]
> sure
> 
> > Later: is_output_quantized now depends on is_reference, which is pretty confusing and it may cause problems down the road, we should remove this dependency in the future.
> 
> my 5c, ideally this would be done soon

yeah agree

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30977826).

**Pull request closed without merging**
