### PR TITLE
Update Release.md with release day steps

### PR DESCRIPTION
**Pull request by atalman**
Update Release.md with release day steps. This PR is self explanatory

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Comment by suo** [comment]
Broke lint sadly

**Comment by atalman** [comment]
@suo @malfet This looks like possible issue in our tooling, when creating PR directly by modifying the *.md files . Looks like the lint jobs are not started at all. I think something we will have to fix. I will submit another PR from fork for this issue.

**Comment by suo** [comment]
> This I suspect the workflows have not started at all due to Github outage today. My guess is that this issue was approved and merged fast before github actions started .

I think it was due to the GHA outage earlier today. No jobs were being scheduled for a while—I guess they just got dropped eventually.

**Comment by suo** [comment]
> This I suspect the workflows have not started at all due to Github outage today. My guess is that this issue was approved and merged fast before github actions started .

I think it was due to the GHA outage earlier today. No jobs were being scheduled for a while—I guess they just got dropped eventually. Not much to be done about it

**Pull request closed without merging**
