### PR TITLE
Add new keys for Ascend NPU

### PR DESCRIPTION
**Pull request by lichao0613**
We need a key to register our out of tree backend: https://github.com/Ascend/pytorch,
and the RFC is #76039 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

### CODE REVIEW

**Comment by ileixe** [comment]
@bdhirsh  Sorry for hijacking, but I am insterested the 'custom device object' concept since our company as a new NPU accelarator vendor is also looking for the right way to integrate pytorch eco. Is there any reference or design doc for the feature?

**Comment by bdhirsh** [comment]
Hi @ileixe! At some point in the near-mid term, we'll want to add some public docs + a more in-depth example. In the mean-time, I wrote a PR that adds a basic "open device registration" test using cpp extension, that should be complete enough for you to use as an example. Take a look and let me know if you have any questions! https://github.com/pytorch/pytorch/pull/80477

**Comment by lichao0613** [comment]
> Hi @ileixe! At some point in the near-mid term, we'll want to add some public docs + a more in-depth example. In the mean-time, I wrote a PR that adds a basic "open device registration" test using cpp extension, that should be complete enough for you to use as an example. Take a look and let me know if you have any questions! #80477

Thanks for the reply! @bdhirsh 
Sorry to bother you, there are some questions that puzzle us and need your help to comfirm. 

1. What is the explicit long-term plan for device registering？
    Should all the following accelarator vendors use PrivateUse1 to register their kernels? Or it is 
    just a temporary solution, and there will be new ones in the future.

As far as we know, there may be the following risks in using this solution：
2. Registration confusion caused by mixed plug-in of different devices, which use the same key(PrivateUse1) to register their kernels.
3. Poor performance. https://github.com/pytorch/pytorch/pull/77208 shows that PrivateUse1 has the lowest priority currently.

Thank you and we are looking forward to cooperating with PyTorch community.

**Comment by albanD** [comment]
Hey!

My understanding is as follows:
1. PrivateUse key and device is the long term plan. yes all the vendors can use that same key.
2. Registration confusion is not something that we're especially concerned right now as most of these hardware are mutually exclusive. And it is in general unlikely that you would want to use them together. If that happens to be a problem in the future, we can relatively easily extend this by providing an API for your extension to get the key/device it should use (that will get associated to PrivateUseX keys). And that will increment automatically under the hood to ensure that extensions don't use the same key. Upgrading from using the current key to this API will be very simple.
3. Not sure what performance problem there is there? The order of the keys has no impact on performance as the dispatcher is able to call into the kernels directly and never does linear traversal.

**Comment by lichao0613** [comment]
hey! @albanD, thanks!

- Referring to our PR about NPU key, PrivateUse key can not meet all our demands/functions currently, such as shallow copy judgement. Can we submit some PRs to supplement these functions for our NPU device?

- We have verified on torch 1.5 that the performance of operator dispatching is degraded due to device keys priority, and a more accurate data will be verified on the latest version of torch. We will share the data with you, just explain the "poor performance".

**Comment by bdhirsh** [comment]
Hi @lichao0613,

> Referring to our PR about NPU key, PrivateUse key can not meet all our demands/functions currently, such as shallow copy judgement. Can we submit some PRs to supplement these functions for our NPU device?

What sort of functionality is missing? The idea of the PrivateUse dispatch key + device is that it should function just like any other backend dispatch key + device, so it should have the same feature set (except in a small number of places).

If this is referring to `shallow_copy_and_detach()`, you can override that directly on your TensorImpl subclass.

> We have verified on torch 1.5 that the performance of operator dispatching is degraded due to device keys priority, and a more accurate data will be verified on the latest version of torch. We will share the data with you, just explain the "poor performance".

Hmm, are you saying that if you move the `PrivateUse1` dispatch key higher up in the enum and change nothing else, you see very different performance? Or is there something else that you're changing.

**Pull request closed without merging**
