### PR TITLE
Always execute parse_set_seed_once to ensure tests are properly seeded.

### PR DESCRIPTION
**Pull request by gchanan**

### CODE REVIEW

**Comment by gchanan** [comment]
See https://github.com/pytorch/pytorch/pull/1970#issuecomment-313421264 for motivation.

**Comment by gchanan** [comment]
hmm, looks like this is now always hitting a bad seed.  Should the tests in jenkins pick a random seed (I'm assuming they don't already)?

**Comment by soumith** [comment]
yea i think the jenkins tests should pick a random seed.

**Comment by gchanan** [comment]
is there a way to see what jenkins is running?  I'm assuming just calling test/run_test.sh?

**Comment by soumith** [comment]
https://github.com/pytorch/builder/blob/master/jenkins/pytorch/build_nimbix.sh#L199

**Pull request closed without merging**
