### PR TITLE
Update triton commit pin for ROCm

### PR DESCRIPTION
**Pull request by jataylo**
Updates ROCm triton pinned commit

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78

### CODE REVIEW

**Comment by jataylo** [comment]
PR to move triton commit forward, @ngimel once merged I will attempt to remove the fallback for tl.reduce in lowering.py to enable https://github.com/pytorch/pytorch/pull/102444#issuecomment-1570385849

**Comment by jataylo** [comment]
Failures in win/ios/cuda are unrelated as we are only touching the rocm triton commit pin.

**Review by jithunnair-amd — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@kit1980 @malfet Please approve. Just moving the triton commit.

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
