### PR TITLE
[1/N] Fix clang-tidy warnings in inductor

### PR DESCRIPTION
**Pull request by cyyever**
Fixes clang-tidy warnings in inductor.

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by ColinPeppler** [comment]
Hi @cyyever, we had to revert this diff because we discovered `aoti_torch_index_put_out` broke ABI-compatibility between two binaries. It's okay to land the rest of the changes except this one, and I'm figuring out how to do a better job in keeping the binaries in-sync.

**Comment by cyyever** [comment]
@ColinPeppler Should I submit a new PR excluding aoti_torch_index_put_out changes?

**Comment by ColinPeppler** [comment]
yes, a separate PR would be great! I will circle back later when it's okay to add aoti_torch_index_put_out changes.

**Comment by ezyang** [comment]
@cyyever you can't change the signature on things that are part of the stable ABI. If you really want to you could make a v2 api with the alternate signature but it's not clear the juice is worth the squeeze. (I have not reviewed this PR yet)

**Comment by cyyever** [comment]
@ezyang Sorry about that. Most changes are in .cpp files which are about implementation. The changes in headers shouldn't change ABI semantics after re-check.

**Pull request closed without merging**
