### PR TITLE
[shard] Add deepcopy for ShardedTensor

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #76758

This PR adding deep copy support a ShardedTensor. Sometimes user might want to deep copy a ShardedTensor param for comparision purpose.

Differential Revision: [D36306710](https://our.internmc.facebook.com/intern/diff/D36306710)

### CODE REVIEW

**Review by fduwjj — COMMENTED** [review]
Do we also want to enable the clone and detach op?

**Comment by wanchaol** [comment]
> Do we also want to enable the clone and detach op?

yes I'm enabling detach op in a separate PR, I could add clone as well in this PR

**Review by pritamdamania87 — APPROVED** [review]
Looks good! Although I'm wondering if we can land this without depending on https://github.com/pytorch/pytorch/pull/76758 since that one might take some work to reland?

**Review by fduwjj — APPROVED** [review]

**Comment by wanchaol** [comment]
@wanchaol has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36306710).

**Pull request closed without merging**
