### PR TITLE
[Easy] Eagerly propagate guards for functools partial

### PR DESCRIPTION
**Pull request by voznesenskym**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #110802

cc @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
This seems like a hacky workaround, not a true fix.

Can you explain the error being fixed more clearly?  I'm not suring I understand it.

Based on the PR I believe we may be installing guards on the wrong object.

**Comment by voznesenskym** [comment]
> This seems like a hacky workaround, not a true fix.
> 
> Can you explain the error being fixed more clearly? I'm not suring I understand it.
> 
> Based on the PR I believe we may be installing guards on the wrong object.

Error is described in the PR description here:

https://github.com/pytorch/pytorch/pull/110772

**Comment by voznesenskym** [comment]
> > This seems like a hacky workaround, not a true fix.
> > Can you explain the error being fixed more clearly? I'm not suring I understand it.
> > Based on the PR I believe we may be installing guards on the wrong object.
> 
> Error is described in the PR description here:
> 
> #110772

I'll copy it here:

There is a rare state we can get into - wherein we produce leaf guards for objects without properly protecting the path to them via checks.

For a pathological example found by @Fidget-Spinner - a functools.partial created on one side of a graph break with an integer value in its keywords does not have its guards installed until an invocation on the other side of the graph break. However, due to how we handle scalars, that keyword arguments value was lifted as an input. This means that the first graph has a guard for value like:

op.keywords['dim']

This is sound unless the functools partial, op, does not match the same state on future invocations. The guards won't just fail, they will crash.

**Comment by jansel** [comment]
I think the fundamental bug then is when we lift values to inputs we aren't guarding them properly.  Specifically we should guard on:
- TYPE_MATCH `op` (for the existence and type of `op.keywords`)
- DICT_KEYS `op.keywords`
- TYPE_MATCH `op.keywords['dim']`

So normally, when you access a value through a dict/attr the returned object has both the guards of the returned value *and* the guards of the container.  Perhaps when we do the constant-value lifting we are not capturing the guards of the containing objects.

Some possible fixes:
1) When we lift a scalar to an input, add the guards of all parent VariableBuilders that contain that scalar
2) Don't lift scalars to inputs until they are used (and thus have gotten the needed guards)
3) Refactor guard code to just eagerly install all guards on `tx.output.guards`, and remove the per-VariableBuilder guard structure.  This will result on guarding on unused variables (bad), but will be simpler to reason about and also will likely reduce compile times slightly. 

Perhaps this is the same root cause as:
https://github.com/pytorch/pytorch/blob/36e6b0cfa20ec2376194445e9d7e6bba7a9ccd77/torch/_dynamo/symbolic_convert.py#L2070

**Comment by voznesenskym** [comment]
> I think the fundamental bug then is when we lift values to inputs we aren't guarding them properly. Specifically we should guard on:
> 
> * TYPE_MATCH `op` (for the existence and type of `op.keywords`)
> * DICT_KEYS `op.keywords`
> * TYPE_MATCH `op.keywords['dim']`

Yes - accumulating these guards automatically would be the best fix. Anything short of that is a bandaid. 

> So normally, when you access a value through a dict/attr the returned object has both the guards of the returned value _and_ the guards of the container. Perhaps when we do the constant-value lifting we are not capturing the guards of the containing objects.
> 
> Some possible fixes:
> 
> 1. When we lift a scalar to an input, add the guards of all parent VariableBuilders that contain that scalar

Sure - we can do that, but the "parent" notion is not one we have. VariableTrackers (Which is what I assume you meant) don't have that, right? Source's with a ChainedSource is the best we have. We could, of course, refactor a bunch to get something like this, but that sounds brittle.

> 2. Don't lift scalars to inputs until they are used (and thus have gotten the needed guards).

Potentially - I think the problem here is we don't have a good "when its used" for scalars (or any constant) - I assume wrap_unspecialized_primitive is called eagerly because it's difficult to tell when a scalar value is actually used. I suppose we could intercede into every call_function, call_method, and graph write to see if the value is a scalar and invoke the lazy  grapharg lifting, but that sounds even more brittle and complicated.

> 3. Refactor guard code to just eagerly install all guards on `tx.output.guards`, and remove the per-VariableBuilder guard structure.  This will result on guarding on unused variables (bad), but will be simpler to reason about and also will likely reduce compile times slightly.

Yeah this seems like a worse direction :( 

> Perhaps this is the same root cause as:

Maybe, have't looked.

**Comment by jansel** [comment]
> > Some possible fixes:
> > 
> > 1. When we lift a scalar to an input, add the guards of all parent VariableBuilders that contain that scalar
> 
> Sure - we can do that, but the "parent" notion is not one we have. VariableTrackers (Which is what I assume you meant) don't have that, right? Source's with a ChainedSource is the best we have. We could, of course, refactor a bunch to get something like this, but that sounds brittle.

We could use our replace_all/apply infra to walk all VariableTrackers and collect the needed guards.

> > 2. Don't lift scalars to inputs until they are used (and thus have gotten the needed guards).
> 
> Potentially - I think the problem here is we don't have a good "when its used" for scalars (or any constant) - I assume wrap_unspecialized_primitive is called eagerly because it's difficult to tell when a scalar value is actually used. I suppose we could intercede into every call_function, call_method, and graph write to see if the value is a scalar and invoke the lazy grapharg lifting, but that sounds even more brittle and complicated.

Why not just do it in `as_proxy()`?

> > 3. Refactor guard code to just eagerly install all guards on `tx.output.guards`, and remove the per-VariableBuilder guard structure.  This will result on guarding on unused variables (bad), but will be simpler to reason about and also will likely reduce compile times slightly.
> 
> Yeah this seems like a worse direction :(

I'm not totally convinced this is that bad.  Unused args shouldn't be that common, and in this example we are promoting unused args to inputs (which seems even worse than guarding on them).

**Comment by Fidget-Spinner** [comment]
This has been fixed by the stack of PRs at https://github.com/pytorch/pytorch/pull/111306. I added a test at https://github.com/pytorch/pytorch/pull/109427

Hence, I'm closing this PR. Hope you don't mind!

**Pull request closed without merging**
