### PR TITLE
Update Multipy CI pin

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #100640

picks up a change that adds testing for multipy importing functional collectives.

### CODE REVIEW

**Comment by wconstab** [comment]
@r-barnes can you comment on whether it is safe to advance the multipy pinned hash?  I saw you were involved in reverting a recent change to the pinned version, so I suspect until the c++17 thing is worked out we may not be able to safely advance the multipy hash.

https://github.com/pytorch/pytorch/commit/2ec6eb3d09817bab0b5bd574fb794b132b20be67

**Review by PaliC — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@wconstab pin affects only OSS CI, so why not

**Comment by wconstab** [comment]
@malfet thanks!

**Pull request closed without merging**
