### PR TITLE
Adds debug postfix

### PR DESCRIPTION
**Pull request by fmder**
This helps having both debug and release library installed simultaneously.

### CODE REVIEW

**Comment by ezyang** [comment]
@pytorchbot test this please

Although, I am not sure CI is sufficient, I don't think we build in `DEBUG` mode in CI atm.

**Comment by fmder** [comment]
This can also be done from the commandd line. I guess it is not a big issue.

**Comment by zou3519** [comment]
@ezyang should we land this?

**Comment by ezyang** [comment]
I think we need to check that this actually works, manually or by adding more CI for it.

**Review by ifedan — APPROVED** [review]

**Review by soumith — CHANGES_REQUESTED** [review]
i think this has to be guarded for WIN32 only. It's not normal in Linux os OSX to have debug shared objects postfixed with `d`

**Pull request closed without merging**
