### PR TITLE
Set USE_KINETO=1

### PR DESCRIPTION
**Pull request by ilia-cher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#49201 Set USE_KINETO=1**

Summary:
This unblocks kineto profiler for 1.8 release.
This PR supercedes https://github.com/pytorch/pytorch/pull/48391
Note: this will somewhat increase the size of linux server binaries, bc
we add libkineto.a and libcupti_static.a:
-rw-r--r-- 1 jenkins jenkins 1107502 Dec 10 21:16 build/lib/libkineto.a
-rw-r--r-- 1 root root 13699658 Nov 13  2019 /usr/local/cuda/lib64/libcupti_static.a

Test Plan:
CI
https://github.com/pytorch/pytorch/pull/48391

TORCH_CUDA_ARCH_LIST="6.0;7.0" USE_CUDA=1 USE_MKLDNN=1
BUILD_BINARY=1 python setup.py develop install --cmake
python test/test_profiler.py
python test/test_autograd.py -k test_profile
python test/test_autograd.py -k test_record

Reviewers:ngimel, robieta, nshulga

Subscribers:

Tasks:

Tags:

Differential Revision: [D25480770](https://our.internmc.facebook.com/intern/diff/D25480770)

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM, but please do not merge this change unless CI is green after rebasing this PR against `viable/strict`

**Comment by ilia-cher** [comment]
rebased on https://github.com/pytorch/pytorch/commit/cbeb4c25e53e90b179f0ded89cafb4cbe140f236 (viable/strict)

**Comment by ilia-cher** [comment]
"89 successful checks", CI's all green

**Comment by mrshenli** [comment]
Looks like this PR breaks DDP tests on master?

**Comment by ilia-cher** [comment]
had to revert because of ddp test failure, will resend

**Comment by ilia-cher** [comment]
resending in https://github.com/pytorch/pytorch/pull/49897

**Pull request closed without merging**
