### PR TITLE
Revert "[Resubmit] Migrate AT_DISPATCH_ALL_TYPES_AND_COMPLEX_AND3 to c10::complex (#38144)"

### PR DESCRIPTION
**Pull request by jeffdaily**
This reverts commit 5077518c91562fbc5f52ef165fa8e30ceb6d4077.  (#38144)

The commit causes significant regressions for ROCm.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Can you provide more detail on the regression? Which op is regressed?

**Comment by zasdfgbnm** [comment]
We don't have the performance to benchmark on ROCm, so please help.

**Comment by jeffdaily** [comment]
The compilation and linking appear to succeed.  At runtime, a device memory access fault occurs to address 0xdeadbeef, a poison value indicating a failed global symbol load.  This runtime failure happens during the first test in test_nn.py, but is widespread across the test suite for any GPU-based test.

**Comment by zasdfgbnm** [comment]
@jeffdaily Thanks, could you help with providing a minimum repro for the issue? This helps me to understand the problem better.

**Comment by jeffdaily** [comment]
CC @xw285cornell @ezyang

**Comment by zasdfgbnm** [comment]
@jeffdaily I walked through the ROCm CI of recent PRs, some of them fail with unable to find docker, and I see one success. Do you have a link to a CI build that is failing?

**Comment by xw285cornell** [comment]
It seems rocm has been failing on master. Here is a sample log: 
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test1/31194//console

I agreed that it's not very informative. @jeffdaily how did you debug this? Can you provide more information?

**Comment by zasdfgbnm** [comment]
@xw285cornell Thanks for the log! And yeah, it looks hard to see how is this related to this PR, let's see if ROCm test succeeds in this PR. But I will definitely need more information before resubmitting.

**Comment by jeffdaily** [comment]
jenkins had been down since Thursday, came back up Monday.  During that period, this commit was merged without verifying against ROCm CI.  I did a git bisect to find this commit.  A git revert of this commit got my local build and test running again.  I have not been able to root cause further yet.

**Comment by jeffdaily** [comment]
I've been selectively reverting files from the original commit, trying to isolate the change.  I believe I have narrowed it down to the file `aten/src/ATen/native/cuda/UnarySignKernels.cu`.  @zasdfgbnm How important are the changes in this file?

I created another PR to test whether the partial revert is another option.  https://github.com/pytorch/pytorch/pull/38363

May I propose a few options to unblock ROCm CI as soon as possible:
1) Revert and re-submit #38144 (merge this current PR), or
2) Revert only the file `aten/src/ATen/native/cuda/UnarySignKernels.cu` if #38363 succeeds.

In the meantime, we are actively trying to root cause.

**Comment by zasdfgbnm** [comment]
@jeffdaily Either one works for me, you can take whichever is more convenient. But this failure is beyond what I can debug (because it looks like a driver/compiler issue), so I might have to write some `#ifdef` to switch the behavior on CUDA and ROCm, and open an issue for this behavior.

**Comment by zasdfgbnm** [comment]
And also @jeffdaily Thank you for narrowing it down to a single file.

**Comment by jeffdaily** [comment]
The partial revert PR has (mostly) passed.  A handful of bfloat16 tests failed for ROCm, but not related.  Separate PR to follow.  Closing this PR in favor of the partial revert.

**Pull request closed without merging**
