### PR TITLE
Add zoneout

### PR DESCRIPTION
**Pull request by tomekkorbak**
This PR adds a new module for regularizing LSTMs and GRUs implementing zoneout, a technique recently pushing state-of-the-art in language modelling. It was requested in #561.

A naive code snippet for using it with `RNNCellBase` subclasses is provided in the docstring. Ideally,  more convenient and faster utilities for using zoneout could be implemented, including a wrapper around `RNNCellBase` ([what they did in seq2seq.pytorch](https://github.com/eladhoffer/seq2seq.pytorch/blob/master/seq2seq/models/modules/recurrent.py#L210-L237) looks like a good design) and argument-level support in `nn.LSTM` and `nn.GRU`. This is not straightforward since current RNN API is poorly extensible (as pointed out in #711) and zoneout could only work with autograd RNN backend (as opposed to cudnn). Considering that, I decided integrating zoneout with RNN API deserves its own PR and should be discussed in the meantime. Suggestions are most welcome.

### CODE REVIEW

**Comment by rafaelvalle** [comment]
I assume in the eval case there's no need to compare previous and current input sizes or types. Shouldn't we check for train before the assertions?

**Comment by tomekkorbak** [comment]
@rafaelvalle I guess you're right. I've changed the order of these assertions.

**Comment by rafaelvalle** [comment]
Should we have the Zoneout class handling saving previous states?

**Comment by rafaelvalle** [comment]
Also please confirm this implementation is compatible with recent versions of pytorch. I recently got this error message:

```
  File "run.py", line 256, in trainval
    loss.backward()
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/autograd/variable.py", line 128, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/autograd/__init__.py", line 83, in backward
    variables, grad_variables, retain_graph, create_graph)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/autograd/function.py", line 78, in apply
    return self._forward_cls.backward(self, *args)
  File "/workspace/zoneout_wrapper.py", line 75, in backward
    return grad_output * Variable(ctx.current_mask), \
RuntimeError: Variable data has to be a tensor, but got Variable
```

**Comment by rafaelvalle** [comment]
@tomekkorbak Do you have any thoughts on generalizing this to work with LSTM as wells instead of just LSTMCells?

**Comment by tomekkorbak** [comment]
@rafaelvalle  sorry for lack of replies, let me think about it and write back here next week.

**Comment by yusufziyaisik** [comment]
Hi,

The inplace function Zoneout() in dropout.py expects current_input, previous_input in this order. But the zoneout() function in functional.py sends previous_input first. Is this an error?

Also, I think in the documentation of Zoneout module, when wrapping GRUCell, the line

h, h_prev = rnn(input[i], h_prev), h

should be:

h, h_prev = rnn(input[i], h), h

**Comment by weiyangfb** [comment]
@tomekkorbak this needs a rebase now. Also any update on this PR?

**Comment by rafaelvalle** [comment]
For the restless, a Zoneout implementation with dropout is rather simple:
https://github.com/teganmaharaj/zoneout/blob/master/zoneout_tensorflow.py#L50

**Comment by hadaev8** [comment]
Any progress?

**Comment by soumith** [comment]
the method is a bit more niche, and we were waiting for it to pick up in popularity.
Considering it didn't, I'm going to close this Feature Request as `wontfix`, we dont want to increase the maintenance surface of core,

**Comment by shaktikshri** [comment]
i would really love this to see in pytorch core, awaiting for the pytorch team to reassess its popularity,

**Comment by shaktikshri** [comment]
i would really love to see zoneout in pytorch core, awaiting for the pytorch team to reassess its popularity,

**Comment by bratao** [comment]
+1 for zoneout! @soumith

**Pull request closed without merging**
