### PR TITLE
[FSDP][BE] Split state_dict related hooks to a separate file to reduce development conflicts 

### PR DESCRIPTION
**Pull request by fegin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #87486
* __->__ #87421

This PR does following two things to improve the code quality.
1. Split state_dict related hooks to a separate file to reduce development conflicts.
2. Remove unused APIs.

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Thanks for improving the dev productivity!

**Comment by awgu** [comment]
Very nice! I have a stream of local commits for splitting other parts of FSDP out into their own files too that I started for functional-like that are exactly in line with what this PR does.

**Pull request closed without merging**
