### PR TITLE
Fix fake tensor for private use backends

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #103090

Fix for https://github.com/pytorch/pytorch/issues/101244 

We need meta to be higher priority than PrivateUse1 (as it is for cpu and cuda) so that when meta is in tls we hit meta kernel.

### CODE REVIEW

**Comment by eellison** [comment]
Hmm getting this error on mobile builds:

```
  what():  Tried to register multiple backend fallbacks for the same dispatch key AutogradOther; previous registration registered at /var/lib/jenkins/workspace/aten/src/ATen/core/VariableFallbackKernel.cpp:30, new registration registered at /var/lib/jenkins/workspace/aten/src/ATen/core/VariableFallbackKernel.cpp:58
Exception raised from registerFallback at /var/lib/jenkins/workspace/aten/src/ATen/core/dispatch/Dispatcher.cpp:326 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x55dc87aead7c in ./Predictor)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xfa (0x55dc84f498bc in ./Predictor)
frame #2: c10::Dispatcher::registerFallback(c10::DispatchKey, c10::KernelFunction, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xe3b (0x55dc851d1ecb in ./Predictor)
frame #3: torch::Library::_fallback(torch::CppFunction&&) & + 0x23c (0x55dc8520f32c in ./Predictor)
frame #4: <unknown function> + 0x955ae3 (0x55dc851b5ae3 in ./Predictor)
frame #5: <unknown function> + 0x72b9de (0x55dc84f8b9de in ./Predictor)
frame #6: <unknown function> + 0x6f3feb (0x55dc84f53feb in ./Predictor)
frame #7: __libc_csu_init + 0x4d (0x55dc87baa35d in ./Predictor)
frame #8: __libc_start_main + 0x80 (0x7f3c6e18d010 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: _start + 0x2e (0x55dc84f83f3e in ./Predictor)
```

**Review by bdhirsh — APPROVED** [review]
Add a test? I think it would be good to have one in the extension test here: https://github.com/pytorch/pytorch/blob/fbbde8df69577fa52a6e354b930a2fe4e921ae92/test/test_cpp_extensions_open_device_registration.py#L160

**Comment by eellison** [comment]
WIll do. @bdhirsh any idea on the mobile failure ?

**Comment by bdhirsh** [comment]
oof. So looking at the error...it looks like the dispatcher things that `AutogradOther` and `AutogradMeta` map to the same enum value in the `DispatchKey` enum.

There are a few ifdefs somewhere for mobile, that they added a few years ago to shrink the dispatcher memory footprint. My guess is that they're the culprit, and they're breaking an assumption somewhere. Offhand, I'm not sure what it is though: https://github.com/pytorch/pytorch/blob/a867e6db85309d988cd8a0305c5c323df2737f9b/c10/core/DispatchKeySet.h#L431

**Comment by yangxiaorun** [comment]
When will this pr be merged? My work depends on this modification.

**Comment by yangxiaorun** [comment]
hi, I work on PrivateUse1 and i want to use torch.compile，so I ran into this problem. At the same time, I tried to fix my problem with a change in PR and it worked. So I want to ask when this PR can be merged. @eellison @bdhirsh

**Comment by eellison** [comment]
i'll merge in next few days

**Pull request closed without merging**
