### PR TITLE
Stop updating hints

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #129893

Some profiling suggests that the repeated maybe evaluate static calls are expensive.

Ref: https://github.com/pytorch/pytorch/issues/123964

With test script:

```
import torch
import torch._dynamo.config

torch._dynamo.config.capture_scalar_outputs = True

@torch.compile(fullgraph=True)
def f(a, b):
    xs = b.tolist()
    for x in xs:
        torch._check_is_size(x)
        torch._check(x <= 20)
    return a.split(xs)

N = 20

splits = torch.randint(10, (N,))
sz = splits.sum().item()

f(torch.randn(sz), splits)
```

Before:

```
real    0m18.526s
user    0m16.555s
sys     0m11.031s
```

After:

```
real    0m13.831s
user    0m12.152s
sys     0m10.941s
```

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
It can also be done via an `_UNDEFINED` sentinel and just update it if it's that value. This way we get the best of both worlds I guess.

**Comment by ezyang** [comment]
No, the problem here specifically is that it keeps being undefined sentinel (None), and every time we query the hint we keep trying to update it (uselessly)

**Comment by lezcano** [comment]
No, my point is that it should be set to `self._hint = _UNDEFINED` with `_UNDEFINED = object()` during initialisation, and then just update it if `self._hint == _UNDEFINED` (i.e. the first time)

**Comment by ezyang** [comment]
I just unconditionally attempt to compute the hint if it is not provided in the constructor now! I don't think making it lazy would help all that much.

**Comment by ezyang** [comment]
Is green!

**Review by lezcano — APPROVED** [review]
Even better!

**Pull request closed without merging**
