### PR TITLE
[dynamo] Simplify creation of VariableTrackers

### PR DESCRIPTION
**Pull request by rec**
### The problem

In the current code, creating a `VariableTracker` involves choosing one of two `Builder` classes and either calling a method, or calling a constructor that creates an object that you immediately call, [like this](https://github.com/pytorch/pytorch/blob/083c9149b75cd918b6fb2795050d7173923a3629/torch/_dynamo/variables/functions.py#L761-L768). 

Variations on this code are repeated in many places.

More, the `Builder` classes have a lot of dependencies, so they have to be loaded late in the whole import process to avoid circular imports, so they end up being repeatedly imported at local scope.

### The solution

In this commit, the import from `builder` and the logic of choosing and calling the Builder class are hidden in a single static factory method, `VariableTracker.build()`, easier to reason about and to import.

This commit net lowers the total lines of code by over 150 lines by removing repetitive logic and unnecessary local imports.

**CHANGES:** Originally the name of the static method was `VariableTracker.create()` but a static method on a derived class, `LazyVariableTracker.create()` now exists with a different signature that's irreconcilable, so the new static method was renamed to `VariableTracker.build()`.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135714

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by wdvr** [comment]
@pytorchmergebot revert -m 'reverting since it fails internal tests - investigating why they didn't run or fail on OSS' -c ghfirst

failing test: test_repros.py
```
        # Picked "square_avg" arbitrarily to check that
        # optimizer state tensors are deallocated
        state_ref = weakref.ref(
            optimizer.state[optimizer.param_groups[0]["params"][0]]["square_avg"]
        )
        optimizer = None
    
>       self.assertIsNone(state_ref())
E       AssertionError: tensor([[0.1000, 0.1000, 0.1000,  ..., 0.1000, 0.1000, 0.1000],
E               [0.1000, 0.1000, 0.1000,  ..., 0.1000, 0.1000, 0.1000],
E               [0.1000, 0.1000, 0.1000,  ..., 0.1000, 0.1000, 0.1000],
E               ...,
E               [0.1000, 0.1000, 0.1000,  ..., 0.1000, 0.1000, 0.1000],
E               [0.1000, 0.1000, 0.1000,  ..., 0.1000, 0.1000, 0.1000],
E               [0.1000, 0.1000, 0.1000,  ..., 0.1000, 0.1000, 0.1000]]) is not None

```

**Pull request closed without merging**
