### PR TITLE
Enable py3.13 wheels for ROCm

### PR DESCRIPTION
**Pull request by jithunnair-amd**
cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@atalman ROCm py3.13 binary wheel jobs passed. Please approve and merge. I would like to Cherry pick this for PyTorch 2.6 so that we can enable 3.13 wheels for rockin for the latest release.

**Review by huydhn — APPROVED** [review]
LGTM!

**Comment by huydhn** [comment]
@pytochbot merge -i

**Pull request closed without merging**
