### PR TITLE
[ProcessGroup] Make watchdog check work queue more frequently

### PR DESCRIPTION
**Pull request by kwen2501**
Today watchdog's sleep interval is 1s. That's a bit long compared to modern GPU link's (or network link's) speed.

Take DDP and Ampere for example:

DDP's bucket size = 25 MB
Ampere's NVLink speed = 250 GB/s

25 MB / 250 GB/s = 100 ms. 
So we are updating the interval to 100 ms.

Update: 
25 MB / 250 GB/s = 0.1 ms
But let's see how it goes so far between making the checking more aggressive.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Review by fduwjj — APPROVED** [review]

**Comment by awgu** [comment]
@kwen2501 For my learning, where do you get the network bandwidth numbers?

> With 12 links for an [Ampere](https://en.wikipedia.org/wiki/Ampere_(microarchitecture))-based A100 GPU this brings the total bandwidth to 600 GB/s.

I saw this on Wikipedia (perhaps not reliable?): https://en.wikipedia.org/wiki/NVLink

**Comment by kwen2501** [comment]
@awgu 600 GB/s is the aggregated NVLink speed (aggregated = two directions added together, i.e. same link counted once on send side and once on recv side).
So if we only consider the link's flow capacity, it is 300 GB/s.
NCCL maximally achieve 250 GB/s out of the 300 GB/s hardware spec.

**Comment by wconstab** [comment]
guessing this is a good change.  Slight chance its gonna cause more CPU overhead due to the product of PGs x 2 threads per PG x 10x more wake activity.

(Future idea: have one thread per all-PGs instead of per-PG)

**Comment by kwen2501** [comment]
> PGs x 2 threads per PG
I think there is only one watchdog per PG.

> Future idea: have one thread per all-PGs instead of per-PG
I think that's doable. Will need to take watchdog out of the PG class.

**Comment by kwen2501** [comment]
Sorry my math is bad..
25 MB / 250 GB/s = 0.1 ms, not 100 ms.
So we are still pretty far away.
But let's see how it goes before making more aggressive changes.
Cc @fduwjj @wconstab @awgu

**Comment by kwen2501** [comment]
@pytorch merge -f "The failures seem unrelated and present in trunk (memory leak)"

**Pull request closed without merging**
