### PR TITLE
Fix docstring in Unflatten

### PR DESCRIPTION
**Pull request by alvgaona**
I'd like to amend the docstring introduced in #41564. It's not rendering correctly on the web, and this should fix it.

cc @albanD

### CODE REVIEW

**Comment by albanD** [comment]
Thanks for the update. Did you try these changes locally to make sure they render as expected?

**Comment by alvgaona** [comment]
Hi, Alban. 

Yes. Here it is.

image

**Comment by alvgaona** [comment]
pr/pytorch-linux-xenial-rocm3.5.1-py3.6

**Review by albanD — APPROVED** [review]
Awesome,
Thanks!

**Comment by alvgaona** [comment]
@albanD how can I rerun `pr/pytorch-linux-xenial-rocm3.5.1-py3.6`?

**Comment by albanD** [comment]
You just ask :D

**Comment by alvgaona** [comment]
Thanks!

**Comment by alvgaona** [comment]
Does this PR need the `merged` label to update the [pytorch.org](https://pytorch.org)?

**Comment by albanD** [comment]
No it was merged properly.
But I think we only update the doc [here](https://pytorch.org/docs/master/) every night. So it should be up tomorrow morning.

**Pull request closed without merging**
