### PR TITLE
[Easy][FSDP] (Reland) Doc fixes

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74912 [FSDP] Add re-key btw param names/IDs for optim state dict
* #74879 [FSDP] Optim state chkpt: key by param name, not ID
* #74215 [FSDP] Add full optim state dict
* **#74834 [Easy][FSDP] (Reland) Doc fixes**

Reland of https://github.com/pytorch/pytorch/pull/74214.
Includes fixing https://github.com/pytorch/pytorch/issues/74694.

Differential Revision: [D35188146](https://our.internmc.facebook.com/intern/diff/D35188146)

### CODE REVIEW

**Review by kumpera — APPROVED** [review]
Docs improvements are the best. :)

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35188146).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35188146).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35188146).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35188146).

**Pull request closed without merging**
