### PR TITLE
Cast grad_input to half when input_dtype is half in _softmax_backward_data aten decomposition

### LINKED ISSUE #85504: [PrimTorch] `expected scalar type Float but found Half` error with AMP
### 🐛 Describe the bug

`_softmax_backward_data` and `_log_softmax_backward_data` cast `grad_input` to half when the `input_dtype` is half.
When running with amp without the cast, consumer ops can trigger `RuntimeError: expected scalar type Float but found Half`.

https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/SoftMax.cpp#L70-L83
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/SoftMax.cpp#L102-L113

Reproducer:
`python benchmarks/timm_models.py --training --amp -d cuda --performance --nvprims-nvfuser --only botnet26t_256`

```python
ERROR:root:unhandled error
Traceback (most recent call last):
  File "/opt/pytorch/torchdynamo/benchmarks/common.py", line 1193, in run_one_model
    new_result = optimized_model_iter_fn(model, example_inputs)
  File "/opt/pytorch/torchdynamo/torchdynamo/eval_frame.py", line 156, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/timm_models.py", line 308, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/timm_models.py", line 308, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/timm_models.py", line 308, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/timm_models.py", line 316, in forward_and_backward_pass
    self.grad_scaler.scale(loss).backward()
  File "/opt/pytorch/pytorch/functorch/functorch/_src/monkey_patching.py", line 77, in _backward
    return _old_backward(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_tensor.py", line 484, in backward
    torch.autograd.backward(
  File "/opt/pytorch/pytorch/torch/autograd/__init__.py", line 191, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/pytorch/pytorch/torch/autograd/function.py", line 267, in apply
    return user_fn(self, *args)
  File "/opt/pytorch/torchdynamo/torchdynamo/eval_frame.py", line 156, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/functorch/functorch/_src/aot_autograd.py", line 367, in backward
    CompiledFunction.compiled_bw = aot_config.bw_compiler(
  File "/opt/pytorch/torchdynamo/torchdynamo/optimizations/backends.py", line 542, in _wrapped_bw_compiler
    return torchdynamo.disable(bw_compiler(*args, **kwargs))
  File "/opt/pytorch/torchdynamo/torchdynamo/optimizations/training.py", line 277, in prims_executor
    prim_gm = make_fx(gm.__call__)(*inputs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 621, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/opt/pytorch/torchdynamo/torchdynamo/eval_frame.py", line 156, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 391, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/opt/pytorch/torchdynamo/torchdynamo/eval_frame.py", line 156, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 405, in wrapped
    out = f(*tensors)
  File "<string>", line 1, in <lambda>
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 658, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/opt/pytorch/pytorch/torch/fx/_symbolic_trace.py", line 717, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 357, in call_module
    return forward(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/_symbolic_trace.py", line 710, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.6", line 155, in forward
    bmm_8 = torch.ops.aten.bmm.default(transpose_24, _reshape_alias_58);  transpose_24 = None
  File "/opt/pytorch/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/overrides.py", line 1778, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_prims/context.py", line 246, in __torch_function__
    return super().__torch_function__(orig_func, types, args, kwargs)
  File "/opt/pytorch/pytorch/torch/overrides.py", line 1778, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_prims/context.py", line 192, in __torch_function__
    return orig_func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 424, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 443, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 295, in proxy_call
    out = func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 60, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: expected scalar type Float but found Half
```

### Versions

ToT master commit:
e34297690787dc89e98989b977b845cb1fa86d1e

TorchDynamo commit:
c537639f9712621dc04ca09908796dbbe86c354b

https://github.com/IvanYashchuk/torchdynamo/tree/nvprims-backend
9a5db9a8a58b199e214ed5fe8090278611e0a0f1

### PR DESCRIPTION
**Pull request by rdspring1**
Fixes #85504

`_softmax_backward_data` and `_log_softmax_backward_data` cast `grad_input` to half when the `input_dtype` is half.
When running with amp without the cast, consumer ops can trigger `RuntimeError: expected scalar type Float but found Half`.

https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/SoftMax.cpp#L70-L83
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/SoftMax.cpp#L102-L113

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by rdspring1** [comment]
@ngimel To fix some failing tests, I modified the `type_casts` function to promote the reference's input arguments but not its output. Then, I'd manually cast the output to the `input_dtype` in `_softmax_backward_data`. Let me know if those changes are acceptable.

**Comment by ngimel** [comment]
I don't understand why it fixes the tests (the same computation should have been performed before?) but looks fine.

**Comment by rdspring1** [comment]
In the initial commit, I dropped the `pw_cast_for_opmath` decorator, so the inputs weren't being promoted to the `computation_dtype`. e.g., bfloat16 => float32

**Pull request closed without merging**
