### PR TITLE
Unconditionally assign symbolic shapes as locals

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #127486

Internal xref: https://fb.workplace.com/groups/1405155842844877/posts/8493858177307906

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by albanD — APPROVED** [review]

**Comment by ezyang** [comment]
I'm a little ambivalent about this change, because it's mostly just bandaiding up other problems like https://github.com/pytorch/pytorch/pull/127543 . @eellison any take here?

**Comment by albanD** [comment]
What is the downside of what is done here? We might define some locals that will get simplified later? From the error message it does seem that even when that happens, this variable is still observable at some stage of compilation.

**Comment by ezyang** [comment]
I think the downside is mostly (1) we are making it harder to discover downstream bugs, which is not a big deal if those bugs never matter, but is bad if those bugs still need to get fixed but we've just made them more rare, and (2) we are assigning a bunch of extra variables that are unnecessary (this one doesn't matter so much.)

**Comment by eellison** [comment]
Sorry I missed this on friday. This seems fine as a config option but not great in the long term. I think it will also make it harder to discover if add new logic that regresses our previous symbolic shape assignment. 

If it's unbacked symint, whatever happened to trying the higher order approach to avoid regeneration of symint ?

**Comment by ezyang** [comment]
This PR only applies for backed symints

**Comment by eellison** [comment]
Same thing applies for backed symints. Does this make the code to detect symint usage dead code ?

**Pull request closed without merging**
