### PR TITLE
Remove duck sizing for all but 0 and 1

### PR DESCRIPTION
**Pull request by voznesenskym**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #94881

### CODE REVIEW

**Comment by ezyang** [comment]
cc @jansel @Chillee

**Review by jansel — CHANGES_REQUESTED** [review]
I worry this will break things in inductor.  We should both correctness and perf test this on larger benchmarks before landing.

**Comment by ezyang** [comment]
For the record, this breaks several models in the inductor CI: https://hud.pytorch.org/pytorch/pytorch/pull/94881?sha=c336bcb861fe4129bd7b472049240dc82319abc2

**Comment by voznesenskym** [comment]
> I worry this will break things in inductor. We should both correctness and perf test this on larger benchmarks before landing.

There was no perf impact I saw in a local sweep - however, I did see these two timeouts...

**Pull request closed without merging**
