### PR TITLE
Preserve submodule with __set_state__ in freezing

### PR DESCRIPTION
**Pull request by bzinodev**
This PR does the following:

-  fail freezing if input module has __set_state__ method
-  preserves attributes of  submodules with __set_state__ method.

Fixes #{issue number}

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
Why are we allowing a submodule with `__set_state__`, but not a top-level module ?

**Comment by bzinodev** [comment]
> Why are we allowing a submodule with `__set_state__`, but not a top-level module ?

Any module that has __set_state , conservatively, we assume that all its attributes are mutable. In the future we could analyze __set_state__ and identify the mutable attributes. We can do this if you think it is useful in practice. Based on this conservative assumption, the behavior is defined as below:

1) Fail to freeze a module that has __set_state__ (not typical in practice).

2) in case a model has submodule with __set_state__, preserve it and freeze  the rest of the model.This is a typical scenario, e.g., handling custom classes that need settings when loaded.

**Comment by eellison** [comment]
This looks like it breaks some tests.

**Comment by eellison** [comment]
I would like to see an example of what this is fixing concretely. The example you have posted in the test would still save and load fine without this patch.

**Review by eellison — APPROVED** [review]
LGTM. It would be nice if we could reuse the preserve methods  approach, but that currently only works on the top-level module, not submodules, as is this use case

**Pull request closed without merging**
