### PR TITLE
[dynamo] Graph break on rng get/set state - remove GeneratorStateSource

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #109452
* __->__ #109410
* #109411

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by ezyang** [comment]
This is a bit disappointing, because I think models could validly get/set generator state and expect it to compile through. Was the old code just completely wrong?

**Comment by anijain2305** [comment]
> This is a bit disappointing, because I think models could validly get/set generator state and expect it to compile through.

We can't really use `set` state. `set` will be ignored by AOT Autograd, producing incorrect graph. Do you agree with this? Previous code also did a graph break on set.

For get, its mostly the payoff. `get_rng_state` gives a tensor w/o any source. Either we assign a source to it and make it eval'able (at `main` we have a source but not eval`able). Or we put the getter in the fx graph, which brings up some new issues in the fx graph codebase. Since `set_rng_state` is a graph break, I don't see how putting `get_rng_state` will be useful (as they are used in combination). As a result, I graph break on `get_rng_state`.

**Review by ezyang — APPROVED** [review]
well, you're the functional rng expert, I'll defer to you. (it still feels to me like, in principle, we should support tracing through set/get rng state, it just seems like a useful thing to be able to do)

**Comment by anijain2305** [comment]
> well, you're the functional rng expert, I'll defer to you. (it still feels to me like, in principle, we should support tracing through set/get rng state, it just seems like a useful thing to be able to do)

I agree its a useful thing to be able to do. Unfortunately, the stack is not ready today.

**Pull request closed without merging**
