### PR TITLE
[jit][script][easy] Change empty list literal compiler error to match actual builtin name

### PR DESCRIPTION
**Pull request by suo**
I changed the name of this builtin to match Python's native style, but forgot to change the compiler error to match.

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]
Should that be lowercase foo? i.e., `_construct_empty_int_list` instead of `_construct_empty_INT_list`

**Comment by michaelsuo** [comment]
mm yeah, I was just trying to make clearer that `FOO` should be replaced with an actual type. I'll change

**Review by zdevito — APPROVED** [review]

**Pull request closed without merging**
