### PR TITLE
Rename dist_autograd_context and dist_autograd_container.

### PR DESCRIPTION
**Pull request by pritamdamania87**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#29696 Rename dist_autograd_context and dist_autograd_container.**

The paths distributed/autograd/context/dist_autograd_context.h and
distributed/autograd/context/dist_autograd_container.h were repetitive.

Therefore renaming these to distributed/autograd/context/context.h and
distributed/autograd/context/container.h

Differential Revision: [D18467624](https://our.internmc.facebook.com/intern/diff/D18467624/)

### CODE REVIEW

**Review by pietern — COMMENTED** [review]
The tests must pass before we can merge this, even if they look like transient errors.

LGTM otherwise. Thanks, @pritamdamania87!

**Comment by mrshenli** [comment]
@yf225 @ezyang 

It seems pythonbot does not trigger rerun on "/ Build Failed (pull_request)" and "/ Build Failed (push) ". I tried to rerun them manually on the following page, but still hit the same error: "- Workflows can't be executed on this repository. Please check your payment method or billing status."

https://github.com/pytorch/pytorch/pull/29696/checks?check_run_id=301851237

Is submitting a new commit the only way to trigger those two ci tests, or can we ignore them?

**Comment by ezyang** [comment]
Just rebase to master. Or ignore them.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
