### PR TITLE
Back out "Revert D34524207: [pytorch][PR] remove _s_where"

### PR DESCRIPTION
**Pull request by ngimel**
Summary:
Original commit changeset: 87b1220d851c

Original Phabricator Diff: D34524207 (https://github.com/pytorch/pytorch/commit/4eb248256801103b08726bf5d85496641cebcdbb)

Test Plan: OSS tests

Differential Revision: D34554432

### CODE REVIEW

**Comment by ngimel** [comment]
@JackCaoG, can you please prepare xla patch for this? The failure on original PR: https://ossci-raw-job-status.s3.amazonaws.com/log/5371985105
```
2022-03-01T08:17:39.5711444Z Traceback (most recent call last):
2022-03-01T08:17:39.5711979Z   File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2022-03-01T08:17:39.5712305Z     "__main__", mod_spec)
2022-03-01T08:17:39.5712611Z   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
2022-03-01T08:17:39.5713059Z     exec(code, run_globals)
2022-03-01T08:17:39.5713391Z   File "/var/lib/jenkins/workspace/tools/codegen/gen_backend_stubs.py", line 318, in <module>
2022-03-01T08:17:39.5713697Z     main()
2022-03-01T08:17:39.5714038Z   File "/var/lib/jenkins/workspace/tools/codegen/gen_backend_stubs.py", line 201, in main
2022-03-01T08:17:39.5714819Z     run(options.source_yaml, options.output_dir, options.dry_run, options.impl_path)
2022-03-01T08:17:39.5715301Z   File "/var/lib/jenkins/workspace/tools/codegen/gen_backend_stubs.py", line 292, in run
2022-03-01T08:17:39.5716046Z     parsed_backend_yaml = parse_backend_yaml(source_yaml, grouped_native_functions, backend_indices)
2022-03-01T08:17:39.5716650Z   File "/var/lib/jenkins/workspace/tools/codegen/gen_backend_stubs.py", line 100, in parse_backend_yaml
2022-03-01T08:17:39.5717000Z     supported, backend_key, use_out_as_primary=use_out_as_primary, use_device_guard=use_device_guard)
2022-03-01T08:17:39.5717350Z   File "/var/lib/jenkins/workspace/tools/codegen/gen_backend_stubs.py", line 81, in create_backend_index
2022-03-01T08:17:39.5717670Z     assert op_name in native_functions_map, f"Found an invalid operator name: {op_name}"
2022-03-01T08:17:39.5717959Z AssertionError: Found an invalid operator name: _s_where
2022-03-01T08:17:39.6227504Z Failed to generate ATEN bindings: ['/var/lib/jenkins/workspace/xla/scripts/generate_code.sh']
```
This PR removes `_s_where` function, `where` is used instead where needed.

**Comment by JackCaoG** [comment]
@ngimel Will do. Any chance we can merge https://github.com/pytorch/pytorch/pull/62084 first? I have a pending xla pr to update `where` for pytorch/xla and that will likely cause some merge conflict for me.

**Comment by ngimel** [comment]
Looks like #62084 is stalled and won't be landed any time soon.

**Comment by JackCaoG** [comment]
@ngimel OK I can work on this fix now then

**Comment by ngimel** [comment]
Thanks @JackCaoG, I'll try to land this PR tomorrow, I'll let you know when it lands

**Comment by ngimel** [comment]
Thanks, let me know if you want to wait till Monday.

**Comment by JackCaoG** [comment]
@ngimel Finding some additional bug regarding `where` broadcasting, can we push the merge to Monday?

**Comment by JackCaoG** [comment]
is there any difference between `_s_where` and `where.self`? I pretty much just rename the op and now find some unexpected test failure.

**Comment by ngimel** [comment]
Ah ok, it just landed but I'll revert. No, there is no difference between `_s_where` and `where.self`, what is the error you are getting?

**Comment by JackCaoG** [comment]
I got some xla error 
```
non_scalar_shape.value().dimensions() == shape->dimensions() Unimplemented implicit broadcast.
```

Pytorch/XLA where under the hood calls `xla::Select` which seems like doesn't support broadcasting(at least not the case that where supported). Let me look at the test case and see if I can add the broadcasting logic in the pytorch/xla layer.

**Comment by JackCaoG** [comment]
@ngimel Where can I find the where broadcasting logic? I run into issues like
```
condition: [8] self: [8, 8] other: [8, 8]
```
which is easy to fix but from things like

```
where([10,1, 10], [10, 10], [10, 10, 1]) -> [10, 10, 10]
``` 

are more confusing

**Comment by ngimel** [comment]
Broadcasting semantics is described in https://pytorch.org/docs/stable/notes/broadcasting.html?highlight=broadcasting, you line up tensors at the last dimension, and expand dimensions of size 1 starting from there. Previously all the tensors were sent to `expand_outplace` to make sure they are expanded to the same size according to these rules https://github.com/pytorch/pytorch/pull/73579/files#diff-586c0d10a44eaff10f3ef1ccf8e647ee60cc962ef73c549889f12de27600ccebL339, and then expanded tensors were sent to _s_where.

**Comment by JackCaoG** [comment]
I was trying to reverse engineering `expand_outplace` but then I realized I should just call it in pt/xla code. test is passing locally, I will submit and let CI verify.

**Comment by JackCaoG** [comment]
@ngimel xla pr is ready, I think we are ready to merge.

**Comment by ngimel** [comment]
@JackCaoG diff is landing

**Pull request closed without merging**
