### PR TITLE
LOG(INFO) -> VLOG(2) in ProcessGroupNCCL

### PR DESCRIPTION
**Pull request by ppwwyyxx**
In the same spirit as https://github.com/pytorch/pytorch/pull/105695

Initialization and error handling logs are mostly kept. Routine logs are changed to VLOG.

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Comment by wconstab** [comment]
Need to check 2 things

1 for our internal jobs will this change hide nccl logs given what log levels are configured for internal jobs? We may not be able to do that

2 @fduwjj was proposing to change to the C10 log macros anyway- maybe you should combine forces

**Comment by fduwjj** [comment]
I also have questions around this, we also use `TORCH_CPP_LOG_LEVEL=INFO` to control the logging information. Why do we prefer VLOG in this case? I mean I am not against it but do we know why `VLOG` is better in this case?

**Comment by ppwwyyxx** [comment]
The change is proposed for the same reason why "log level" is helpful: user could have more control on what granularity of logs they would like to see. 

Here, I kept some logs (ProcessGroup initialization, dumping debug info, error handling, etc) unchanged, but turned some logs (creating nccl comm, creating/exiting threads, or other fine-grained steps in the process) into VLOG as they are more about internal implementation that's meaningful for developers of the ProcessGroup. Of course the classification is quite subjective.

In addition, VLOG supports per-module control of log level, which also helps control granularity of logs.

**Comment by wconstab** [comment]
@ppwwyyxx can you more clearly state in the PR description what the differences are?

(What is VLOG(2) - relative to LOG(INFO) - is it more or less verbose? Are there docs about VLOG macro somewhere?

**Comment by kwen2501** [comment]
It is a bit sad that LOG does not have more verbose levels than INFO:
https://github.com/pytorch/pytorch/blob/f3c54ccf8f6139807f4623037c0174964a286652/c10/util/Logging.cpp#L541-L545

Thus, an option is to attach a V before LOG (I guess the V stands for verbose):
https://github.com/pytorch/pytorch/blob/f3c54ccf8f6139807f4623037c0174964a286652/c10/util/Logging.cpp#L466-L472
The higher the number, the more verbose it is.

**Review by kwen2501 — APPROVED** [review]

**Pull request closed without merging**
