### PR TITLE
Check for boolean values as argument on pow function. 

### LINKED ISSUE #113198: Different behaviour of pow(tensor, bool) for CPU vs CUDA
### 🐛 Describe the bug

```python
In [52]: torch.pow(torch.tensor([1, 2]), True)
Out[52]: tensor([1, 2])

In [53]: torch.pow(torch.tensor([1, 2], device='cuda'), True)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[53], line 1
----> 1 torch.pow(torch.tensor([1, 2], device='cuda'), True)

RuntimeError: false INTERNAL ASSERT FAILED at "/home/isuruf/git/pytorch/aten/src/ATen/native/cuda/PowKernel.cu":199, please report a bug to PyTorch. invalid combination of type in Pow function, common dtype:Longexp is integral?0
```

### Versions

```
Collecting environment information...
PyTorch version: 2.2.0a0+git2ef35a0
Is debug build: False
CUDA used to build PyTorch: 12.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (conda-forge gcc 12.3.0-2) 12.3.0
Clang version: Could not collect
CMake version: version 3.27.6
Libc version: glibc-2.35

Python version: 3.8.18 | packaged by conda-forge | (default, Oct 10 2023, 15:44:36)  [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 12.0.76
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2060
GPU 1: NVIDIA GeForce RTX 2060

Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/local/cuda-11.7.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.7.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.7.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.7.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.7.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.7.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.7.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          64
On-line CPU(s) list:             0-63
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen Threadripper 3970X 32-Core Processor
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       1
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     3700.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        7400.28
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es
Virtualization:                  AMD-V
L1d cache:                       1 MiB (32 instances)
L1i cache:                       1 MiB (32 instances)
L2 cache:                        16 MiB (32 instances)
L3 cache:                        128 MiB (8 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.6.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] optree==0.9.1
[pip3] torch==2.2.0a0+git3d53105
[conda] libmagma                  2.7.2                h173bb3b_0    conda-forge
[conda] libmagma_sparse           2.7.2                h173bb3b_0    conda-forge
[conda] libopenvino-pytorch-frontend 2023.1.0             h59595ed_1    conda-forge
[conda] magma                     2.7.2                h51420fd_0    conda-forge
[conda] mkl                       2023.2.0         h84fe81f_50495    conda-forge
[conda] mkl-include               2023.2.0         h84fe81f_50495    conda-forge
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] optree                    0.9.1                    pypi_0    pypi
[conda] torch                     2.2.0a0+git3d53105           dev_0    <develop>
```

cc @ptrblck @malfet

### PR DESCRIPTION
**Pull request by pdrocaldeira**
Hello everyone! 😄 
Also @lezcano , nice to meet you! :)

Sorry if I miss anything, this is my first time around here. 🙃 

This PR basically makes the same behaviour for cuda when using `torch.pow`. Basically Python considers True as 1 and False as 0. I just added this check into `pow` function. From what I understood, when I do `.equal` for `Scalar` that is boolean, I'm sure that types match so that won't cause more trouble.

I know that the issue suggest to disable this case but that could be a little more complicated, in my humble opinion. And that can create some compability problems too, I guess.

My argument is that code below is correct for native language, so I guess it does makes sense sending booleans as Scalar.

```
$ x = True
$ x + x
2
```

This was my first test:
```
Python 3.12.0 | packaged by Anaconda, Inc. | (main, Oct  2 2023, 17:29:18) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.pow(torch.tensor([1, 2], device='cuda'), True)
tensor([1, 2], device='cuda:0')
>>> torch.pow(torch.tensor([1, 2]), True)
tensor([1, 2])
>>> torch.pow(torch.tensor([1, 2]), False)
tensor([1, 1])
>>> torch.pow(torch.tensor([1, 2], device='cuda'), False)
tensor([1, 1], device='cuda:0')
```

I've run `test_torch.py` and got following results, so my guess is that I didn't break anything. I was just looking for a test that uses linear regression, as suggested.

```
Ran 1619 tests in 52.363s

OK (skipped=111)
[TORCH_VITAL] Dataloader.enabled		 True
[TORCH_VITAL] Dataloader.basic_unit_test		 TEST_VALUE_STRING
[TORCH_VITAL] CUDA.used		 true

```
(I can paste whole log, if necessary)

If this is a bad idea overall, dont worry about it. It's not a big deal, it's actually a two line change 😅  so can we talk of how do things in a different strategy.

For the record I've signed the agreement already. And I didn't run linter because it's not working 😞 . Looks like PyYaml 6.0 is broken and there's a 6.0.1 fix already but I have no idea how to update that 😅 

Fixes #113198

### CODE REVIEW

**Comment by lezcano** [comment]
This PR needs tests

The tests you want to run are in `test/test_ops.py`. Some will fail, you'll need to change those. Those tests are autogenerated. You may want to grep for `OpInfo` to find how they are autogenerated. If nothing fails, you'll need to add a sample to the relevant OpInfo that fails without this PR and passes with this PR.

**Comment by pdrocaldeira** [comment]
> Also note that this PR is doing **the opposite** of what we proposed to do in the issue, which is always fail on `x ** bool`...

Yeah, you're *absolutely correct*. I did try to do what you asked but it was way more complicated but I wanted to bring this to the table because it was an easy change that creates a standard behaviour between everything considering standard Python behaviour. 

But, of course, if you don't think this is a good idea I won't mind just closing this and moving forward with your suggestion. You just got to say the words :) [I know that you might have said that already but I'm not sure]

____________________________________________________________________________________________________


If I understood code correctly to disable bool I would have to change `native_functions.yaml` to instead of having a `Scalar` argument I would need to overload to every other case that isn't bool. Because from what I'm seeing, `Scalar` can be bool.  And the consequence is that when we run  `torch.pow(torch.tensor([1, 2], device='cuda'), True)` this function won't even exist, right?

_____________________________________________________________________________________________________

>The tests you want to run are in test/test_ops.py. Some will fail, you'll need to change those. Those tests are autogenerated. You may want to grep for OpInfo to find how they are autogenerated. If nothing fails, you'll need to add a sample to the relevant OpInfo that fails without this PR and passes with this PR.

*Noted!* Regardless of any strategy I think that's a good test, thank you!

____________________________________________________________________________________________________

Thanks for such fast response, I really appreciate your input! 😄

**Comment by lezcano** [comment]
You just need to TORCH_CHECK that the input is not boolean, no?

At any rate, I'm fine with making the behaviour equal to the current behaviour of CPU or CUDA, whatever works as long as it's tested.

**Comment by pdrocaldeira** [comment]
```
======================================================================
ERROR: test_python_ref_meta__refs_linalg_svd_cpu_complex128 (__main__.TestCommonCPU.test_python_ref_meta__refs_linalg_svd_cpu_complex128)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 428, in instantiated_test
    raise rte
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 415, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 908, in test_wrapper
    return test(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 1120, in only_fn
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 1299, in wrapper
    fn(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/test/test_ops.py", line 347, in test_python_ref_meta
    prims.utils.compare_tensor_meta(a, b)
  File "/home/pedro/workspace/pytorch/torch/_prims_common/__init__.py", line 166, in compare_tensor_meta
    raise RuntimeError(
RuntimeError: Conj mismatch! is_conj is set to False and True

To execute this test, run the following from the base repo dir:
     python test/test_ops.py -k test_python_ref_meta__refs_linalg_svd_cpu_complex128

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

======================================================================
ERROR: test_python_ref_meta__refs_linalg_svd_cpu_complex64 (__main__.TestCommonCPU.test_python_ref_meta__refs_linalg_svd_cpu_complex64)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 428, in instantiated_test
    raise rte
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 415, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 908, in test_wrapper
    return test(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 1120, in only_fn
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 1299, in wrapper
    fn(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/test/test_ops.py", line 347, in test_python_ref_meta
    prims.utils.compare_tensor_meta(a, b)
  File "/home/pedro/workspace/pytorch/torch/_prims_common/__init__.py", line 166, in compare_tensor_meta
    raise RuntimeError(
RuntimeError: Conj mismatch! is_conj is set to False and True

To execute this test, run the following from the base repo dir:
     python test/test_ops.py -k test_python_ref_meta__refs_linalg_svd_cpu_complex64

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

======================================================================
FAIL: test_complex_half_reference_testing_fft_hfft2_cuda_complex32 (__main__.TestCommonCUDA.test_complex_half_reference_testing_fft_hfft2_cuda_complex32)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 415, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 945, in dep_fn
    return fn(slf, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 908, in test_wrapper
    return test(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/test/test_ops.py", line 1232, in test_complex_half_reference_testing
    self.assertEqual(actual, expected, exact_dtype=False)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 3478, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 256 (0.4%)
Greatest absolute difference: 0.07051944732666016 at index (0, 4, 10) (up to 0.04 allowed)
Greatest relative difference: 0.36067742109298706 at index (0, 4, 10) (up to 0.04 allowed)

To execute this test, run the following from the base repo dir:
     python test/test_ops.py -k test_complex_half_reference_testing_fft_hfft2_cuda_complex32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 60396 tests in 6626.686s

FAILED (failures=1, errors=2, skipped=10863, expected failures=831)
```

I tested both my branch and `main` and both have these three failing errors for `test/test_ops.py`

Three questions?

* Do I need to rebase?
* What should I write for `release notes`?
* Is there something else to test?

Thanks a lot, see you around!

(It took me a while because I didnt have scipy and there were more failing because of that [and also because my cpu is slow 😅 ])

**Comment by lezcano** [comment]
You need to add a sample to the op info that tests this case. One that fails in main and passes with this PR

**Comment by pdrocaldeira** [comment]
>You need to add a sample to the op info that tests this case. One that fails in main and passes with this PR

Duh! That was obvious, sorry about that 😅 

Yes, about OpInfo I went ahead and read the comments/instructions about it to understand how they work. But I knew there should be something written already and then I found it 😄 

But it was good info to look for OpInfo, only after that I could find about `binary_ufunc` 😉 

I just changed `test/test_binary_ufuncs.py` and its already existing `pow` test and added both `True` and  `False` on the list of testing exponents.

Then, when I run the main branch I will have:

```
======================================================================
ERROR: test_pow_cuda_int16 (__main__.TestBinaryUfuncsCUDA.test_pow_cuda_int16)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 428, in instantiated_test
    raise rte
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 415, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/test/test_binary_ufuncs.py", line 1362, in test_pow
    self._do_pow_for_exponents(m1, exponents, math.pow, None)
  File "/home/pedro/workspace/pytorch/test/test_binary_ufuncs.py", line 1310, in _do_pow_for_exponents
    res1 = torch.pow(m1[4], num)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: false INTERNAL ASSERT FAILED at "/home/pedro/workspace/pytorch/aten/src/ATen/native/cuda/PowKernel.cu":199, please report a bug to PyTorch. invalid combination of type in Pow function, common dtype:Shortexp is integral?0

To execute this test, run the following from the base repo dir:
     python test/test_binary_ufuncs.py -k test_pow_cuda_int16

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

======================================================================
ERROR: test_pow_cuda_int32 (__main__.TestBinaryUfuncsCUDA.test_pow_cuda_int32)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 428, in instantiated_test
    raise rte
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 415, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/test/test_binary_ufuncs.py", line 1362, in test_pow
    self._do_pow_for_exponents(m1, exponents, math.pow, None)
  File "/home/pedro/workspace/pytorch/test/test_binary_ufuncs.py", line 1310, in _do_pow_for_exponents
    res1 = torch.pow(m1[4], num)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: false INTERNAL ASSERT FAILED at "/home/pedro/workspace/pytorch/aten/src/ATen/native/cuda/PowKernel.cu":199, please report a bug to PyTorch. invalid combination of type in Pow function, common dtype:Intexp is integral?0

To execute this test, run the following from the base repo dir:
     python test/test_binary_ufuncs.py -k test_pow_cuda_int32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

======================================================================
ERROR: test_pow_cuda_int64 (__main__.TestBinaryUfuncsCUDA.test_pow_cuda_int64)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 428, in instantiated_test
    raise rte
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 415, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/test/test_binary_ufuncs.py", line 1362, in test_pow
    self._do_pow_for_exponents(m1, exponents, math.pow, None)
  File "/home/pedro/workspace/pytorch/test/test_binary_ufuncs.py", line 1310, in _do_pow_for_exponents
    res1 = torch.pow(m1[4], num)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: false INTERNAL ASSERT FAILED at "/home/pedro/workspace/pytorch/aten/src/ATen/native/cuda/PowKernel.cu":199, please report a bug to PyTorch. invalid combination of type in Pow function, common dtype:Longexp is integral?0

To execute this test, run the following from the base repo dir:
     python test/test_binary_ufuncs.py -k test_pow_cuda_int64

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

======================================================================
ERROR: test_pow_cuda_int8 (__main__.TestBinaryUfuncsCUDA.test_pow_cuda_int8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 428, in instantiated_test
    raise rte
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 415, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/test/test_binary_ufuncs.py", line 1362, in test_pow
    self._do_pow_for_exponents(m1, exponents, math.pow, None)
  File "/home/pedro/workspace/pytorch/test/test_binary_ufuncs.py", line 1310, in _do_pow_for_exponents
    res1 = torch.pow(m1[4], num)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: false INTERNAL ASSERT FAILED at "/home/pedro/workspace/pytorch/aten/src/ATen/native/cuda/PowKernel.cu":199, please report a bug to PyTorch. invalid combination of type in Pow function, common dtype:Charexp is integral?0

To execute this test, run the following from the base repo dir:
     python test/test_binary_ufuncs.py -k test_pow_cuda_int8

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

======================================================================
ERROR: test_pow_cuda_uint8 (__main__.TestBinaryUfuncsCUDA.test_pow_cuda_uint8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_utils.py", line 2554, in wrapper
    method(*args, **kwargs)
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 428, in instantiated_test
    raise rte
  File "/home/pedro/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 415, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pedro/workspace/pytorch/test/test_binary_ufuncs.py", line 1362, in test_pow
    self._do_pow_for_exponents(m1, exponents, math.pow, None)
  File "/home/pedro/workspace/pytorch/test/test_binary_ufuncs.py", line 1310, in _do_pow_for_exponents
    res1 = torch.pow(m1[4], num)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: false INTERNAL ASSERT FAILED at "/home/pedro/workspace/pytorch/aten/src/ATen/native/cuda/PowKernel.cu":199, please report a bug to PyTorch. invalid combination of type in Pow function, common dtype:Byteexp is integral?0

To execute this test, run the following from the base repo dir:
     python test/test_binary_ufuncs.py -k test_pow_cuda_uint8

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 25675 tests in 180.119s

FAILED (errors=5, skipped=1679, expected failures=66)

```

But for this branch it runs fine:

```
Ran 25675 tests in 180.793s

OK (skipped=1679, expected failures=66)

```
___________________________________________________________________________________________________
I added @garyyaoresearch as co author as he gave me the courtesy to mention that he was working on that too. We been changing mails since then :)

**Review by lezcano — APPROVED** [review]
fair enough

**Pull request closed without merging**
