### PR TITLE
[BE] [MPS] Use validation helper for input tensors

### PR DESCRIPTION
**Pull request by hvaara**
Small refactor to use already existing helper with equivalent behavior.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

### CODE REVIEW

**Comment by hvaara** [comment]
@malfet @kulinseth is this something you want or should I close thise?

**Comment by hvaara** [comment]
@malfet @kulinseth could either of you please review this? Thanks!

**Review by malfet — APPROVED** [review]
LGTM, thank you for the fix

**Pull request closed without merging**
