### PR TITLE
[CI] Fix xpu ci test with s3 cache

### PR DESCRIPTION
**Pull request by chuanqi129**
Fix a regression caused by https://github.com/pytorch/pytorch/pull/121323
Works for #114850

### CODE REVIEW

**Review by atalman — APPROVED** [review]
lgtm. @chuanqi129 please add details of the failure (why this fix is needed) in the PR description: https://github.com/pytorch/pytorch/actions/runs/11658848522/job/32459872663#step:14:997

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Thank you for the fix, and agree with what @atalman have said: explain why this change is needed (likely to fix a regression caused by https://github.com/pytorch/pytorch/pull/121323

**Comment by chuanqi129** [comment]
> lgtm. @chuanqi129 please add details of the failure (why this fix is needed) in the PR description: https://github.com/pytorch/pytorch/actions/runs/11658848522/job/32459872663#step:14:997

Updated description. And will merge it directly to unblock XPU other PRs test

**Pull request closed without merging**
