### PR TITLE
bump up add_loop_inductor_gpu expected instruction count.

### PR DESCRIPTION
**Pull request by laithsakka**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137672

diff https://github.com/pytorch/pytorch/pull/137117/files increased instruction count for add_loop_inductor_gpu
but not enough to fail in that diff, but now its kind of flaky test .

it failed on recent merge:
Screenshot 2024-10-09 at 5 25 57 PM

and here is the history 
Screenshot 2024-10-09 at 5 26 07 PM
Screenshot 2024-10-09 at 5 30 19 PM

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by masnesral — COMMENTED** [review]
lg

**Review by masnesral — APPROVED** [review]

**Comment by laithsakka** [comment]
@pytrochbot merge

**Comment by laithsakka** [comment]
landing this might fail due to https://github.com/pytorch/pytorch/pull/137672
thats annoying i shall find a better way for comparing results

**Comment by laithsakka** [comment]
@pytrochbot merge

**Pull request closed without merging**
