### PR TITLE
Enable custom device support in fsdp checkpoint

### LINKED ISSUE #104390: fsdp checkpoint wants to support custom device
### 🐛 Describe the bug

As for fsdp checkpoint, there are some hard-code only for `cuda`, for custom device (privateuse1 backend, cuda-like device), we also want to support it.

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

### PR DESCRIPTION
**Pull request by dilililiwhy**
Fixes https://github.com/pytorch/pytorch/issues/104390
Enable custom device(privateuse1 backend) support in checkpointing by a dynamic abstract device module.

### CODE REVIEW

**Comment by dilililiwhy** [comment]
@mrshenli
Sorry to bother you. I would appreciate it if you could review this PR.

**Comment by dilililiwhy** [comment]
@mrshenli @awgu @fegin 
Sorry to bother you. I would appreciate it if you could review this PR.

**Comment by fegin** [comment]
@wz337 Can you review this PR? This is closer to DCP instead of FSDP.

**Comment by dilililiwhy** [comment]
Could you have a look at this PR @wz337?

**Comment by dilililiwhy** [comment]
Could you have a look at this PR @wz337 ? Thanks.

**Comment by wz337** [comment]
> Could you have a look at this PR @wz337 ? Thanks.

Planning to review today. Quick question: is this more or less the same change in this PR? https://github.com/pytorch/pytorch/pull/104140#issuecomment-1660344061

**Comment by dilililiwhy** [comment]
> > Could you have a look at this PR @wz337 ? Thanks.
> 
> Planning to review today. Quick question: is this more or less the same change in this PR? [#104140 (comment)](https://github.com/pytorch/pytorch/pull/104140#issuecomment-1660344061)

This PR does same change in #104140, which is approved by @heidongxianhua

**Comment by dilililiwhy** [comment]
> > Could you have a look at this PR @wz337 ? Thanks.
> 
> Planning to review today. Quick question: is this more or less the same change in this PR? [#104140 (comment)](https://github.com/pytorch/pytorch/pull/104140#issuecomment-1660344061)

This PR does same change but optimizes the device info normalization, which is approved by onwer of #104140 @heidongxianhua

**Comment by dilililiwhy** [comment]
> > > Could you have a look at this PR @wz337 ? Thanks.
> > 
> > 
> > Planning to review today. Quick question: is this more or less the same change in this PR? [#104140 (comment)](https://github.com/pytorch/pytorch/pull/104140#issuecomment-1660344061)
> 
> This PR does same change but optimizes the device info normalization, which is approved by onwer of #104140 @heidongxianhua

@wz337 I find there is a milestone today, hope for your review. Thanks

**Comment by wz337** [comment]
Looks good to me. Thanks for contributing to enabling custom device support. 
I am assuming you have tested this on your custom device?

**Comment by wz337** [comment]
Looks good to me. Thanks for contributing on enabling custom device support.

**Review by wz337 — APPROVED** [review]
LGTM

**Comment by dilililiwhy** [comment]
> Looks good to me. Thanks for contributing to enabling custom device support. I am assuming you have tested this on your custom device?

Yes, we have ut cases on our device

**Pull request closed without merging**
