### PR TITLE
Add xpu_cmake_macros.h to xpu build

### PR DESCRIPTION
**Pull request by guangyey**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #132847

# Motivation

fix https://github.com/pytorch/pytorch/issues/132971

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by EikanWang** [comment]
Overall, it looks good to me. But I think the PR description is not the motivation. We need to describe what the changes serve for. If it is an issue to support extension mechanism, I'd prefer to submit an issue and link to the issue number.

**Comment by guangyey** [comment]
cc @min-jean-cho

**Review by EikanWang — APPROVED** [review]

**Pull request closed without merging**
