### PR TITLE
Cleanup buck_setup.sh a bit

### PR DESCRIPTION
**Pull request by malfet**
Use `curl -L |tar xf` to extract downloadable file right into the folder one wants to use

### CODE REVIEW

**Review by linbinyu — APPROVED** [review]
looking good, thanks! I will rewrite the rest

**Comment by linbinyu** [comment]
or there's no better way for zip files?

**Comment by malfet** [comment]
> or there's no better way for zip files?

`unzip` has much more limited option to control the extraction process. In a sense it's much less Unix-y tool than `tar`

**Pull request closed without merging**
