### PR TITLE
Let CMake handle NCCL detection instead of our handcrafted Python script.

### PR DESCRIPTION
**Pull request by xuhdev**
- USE_NCCL, USE_SYSTEM_NCCL, USE_STATIC_NCCL are made proper CMake build
  options that depend on other options.
- Detections using folders such as lib64, lib64/<arch> are automatically
  handled in find_library in CMake.
- NCCL_ROOT_DIR in findNCCL.cmake is changed to NCCL_ROOT, which is the
  standard CMake variable that specifies the root dir of a library (and
  therefore supports a wide range of automatic detection). E.g., see
  https://cmake.org/cmake/help/latest/envvar/PackageName_ROOT.html

---

How does the current code subsume all detections in the deleted `nccl.py`?

- The dependency of `USE_NCCL` on the OS and `USE_CUDA` is handled as dependency options in `CMakeLists.txt`.

- The main NCCL detection happens in [FindNCCL.cmake](https://github.com/pytorch/pytorch/blob/8377d4b32c12206a0f9401e81a5e5796c8fc01a8/cmake/Modules/FindNCCL.cmake), which is called by [nccl.cmake](https://github.com/pytorch/pytorch/blob/8377d4b32c12206a0f9401e81a5e5796c8fc01a8/cmake/External/nccl.cmake). When `USE_SYSTEM_NCCL` is false, the previous Python code defer the detection to `find_package(NCCL)`. The change in `nccl.cmake` retains this.

- `USE_STATIC_NCCL` in the previous Python code simply changes the name of the detected library. This is done in `IF (USE_STATIC_NCCL)`.

- Now we only need to look at how the lines below line 20 in `nccl.cmake` are subsumed. These lines list paths to header and library directories that NCCL headers and libraries may reside in and try to search these directories for the key header and library files in turn. These are done by `find_path` for headers and `find_library` for the library files in `FindNCCL.cmake`.
  * The call of [find_path](https://cmake.org/cmake/help/v3.8/command/find_path.html) (Search for `NO_DEFAULT_PATH` in the link) by default searches for headers in `<prefix>/include` for each `<prefix>` in `CMAKE_PREFIX_PATH` and `CMAKE_SYSTEM_PREFIX_PATH`. Like the Python code, this commit sets `CMAKE_PREFIX_PATH` to search for `<prefix>` in `NCCL_ROOT_DIR` and home to CUDA.  `CMAKE_SYSTEM_PREFIX_PATH` includes the standard directories such as `/usr/local` and `/usr`. `NCCL_INCLUDE_DIR` is also specifically handled.

  * Similarly, the call of [find_library](https://cmake.org/cmake/help/v3.8/command/find_library.html) (Search for `NO_DEFAULT_PATH` in the link) by default searches for libraries in directories including `<prefix>/lib` for each `<prefix>` in `CMAKE_PREFIX_PATH` and `CMAKE_SYSTEM_PREFIX_PATH`. But it also handles the edge cases intended to be solved in the Python code more properly:
     - It only searches for `<prefix>/lib64` (and `<prefix>/lib32`) if it is appropriate on the system.
     - It only searches for `<prefix>/lib/<arch>` for the right `<arch>`, unlike the Python code searches for `lib/<arch>` in a generic way (e.g., the Python code searches for `/usr/lib/x86_64-linux-gnu` but in reality systems have `/usr/lib/x86_64-some-customized-name-linux-gnu`, see https://unix.stackexchange.com/a/226180/38242 ).

---

Regarding for relevant issues:

- #12063 and #2877: These are properly handled, as explained in the updated comment.
- #2941 does not changes NCCL detection specifically for Windows (it changed CUDA detection).
- b7e258f81ef61d19b884194cdbcd6c7089636d46 A versioned library detection is added, but the order is reversed: The unversioned library becomes preferred. This is because normally unversioned libraries are linked to versioned libraries and preferred by users, and local installation by users are often unversioned. Like the document of [find_library](https://cmake.org/cmake/help/v3.8/command/find_library.html) suggests:

> When using this to specify names with and without a version suffix, we recommend specifying the unversioned name first so that locally-built packages can be found before those provided by distributions.

### CODE REVIEW

**Comment by ezyang** [comment]
Thanks @xuhdev, these patches are much appreciated. Could you provide some evidence that the built-in NCCL detection in cmake fully subsumes the previous Python code? Notable bug fixes we accreted in the Python finder in the past are #12063 (this is probably OK), #2941, b7e258f81ef61d19b884194cdbcd6c7089636d46 and #2877

Also, it is doubtful that CI exercises the static nccl linking case, so it would be very helpful to test that manually and make sure it still works.

**Comment by xuhdev** [comment]
@ezyang Sure. I've added explanation to the top comment below the horizontal bar, so they would be included in the commit (if merged).

I tested `USE_STATIC_NCCL=1` for both system and non-system NCCL, and both worked for me.

**Review by ezyang — APPROVED** [review]
Waiting on CI

**Comment by soumith** [comment]
@xuhdev @ezyang I am not excited about this patch because it starts to use advanced CMake stuff, and none of us know enough about cmake like Hong Xu does. It would mean that if we ever have to tweak this stuff, it'll be much harder.

**Comment by ezyang** [comment]
@soumith which features are you referring to specifically? Is it the built-in NCCL detection in cmake?

**Comment by xuhdev** [comment]
@soumith I won't worry too much about this, because:

- What was written in nccl.py (accumulated by a stack of commits) was largely trying to mimic what a standard call to `find_library` and `find_path` (which are usually called by `find_package`). Still, as I commented, these functions do more reasonable jobs, offer more flexibility to users and handle more edge cases than nccl.py. If we are comfortable with using CMake to detect other libraries, I do not see a reason to not do it for NCCL.
- This PR has made the code in CMake less complicated than before. No feature more advanced than anything else in the modified CMake files is used: All added lines use functions that are extensively used in PyTorch.

**Comment by soumith** [comment]
okay.

my particular concern is in the bugs users reported around having a `nccl.h` that is not actually aligned with the corresponding `nccl.so.xx`.
So, we spent some time fixing the detection to always find a common prefix between nccl.h and libnccl.so, instead of for example finding nccl.h in `/usr/include` and `libnccl.so` in `/usr/local/lib`.
If it cant find a common prefix that looks reasonable, it needs to error out, rather than continuing with these.

Is it still the case?

**Comment by xuhdev** [comment]
@soumith Currently the modified code does not do common prefix detection.

I looked into the common prefix code again, but I failed to see how it would solve the issue you suggested. Assuming nccl.h was found in `/usr/local/include` and libnccl.so was found in `/usr/lib`, their common prefix would be `/usr/`, and `NCCL_ROOT_DIR` is passed down to CMake. However, this won't change anything because `find_path` and `find_library` will search for both `/usr/local/` and `/usr/` no matter what `NCCL_ROOT_DIR` was forced to be, because they are default system prefixes. Situations where headers are in `/usr/include` and libraries are in `/usr/lib/x86_64-unknown-linux-gnu` (or other archs), and where headers are in `/usr/include/nccl` and libraries are in `/usr/lib[/<arch>]/nccl`, are pretty common in distributional and user installation and would further complicate the detection.

I suspect that it was actually something else that caused the issue. Perhaps you can point me to the reported issue so I can better understand what happened?

I would say the modified code works well practically. Let's assume that the user has a correct NCCL installation (i.e., no missing files). If the user follows an ordinary NCCL installation scheme (e.g., one does not install headers in `/usr/local/include` and libraries in `/usr/lib`, although this is technically possible and often supported by many software packages), as long as we follow a detection order that is the same for headers and libraries, the detected header file and library file should always be aligned.

But if the user has a broken NCCL installation, or they follow a non-ordinary scheme.... I would say we simply let the user know where the headers and libraries are detected, and the user should set `NCCL_LIB_DIR` and `NCCL_INCLUDE_DIR` by themselves instead of us second-guessing.

**Comment by ezyang** [comment]
I think the relevant PR soumith is referring to is #2853

I am sympathetic to your argument, but I do think this sort of situation happens to users (and because it is indeed usually a user error on their part, the users who are most likely to be afflicted by this problem, are also the users who are least well equipped to debug the issue.) A particularly severe and very common version of this problem happens with protobuf, because you need protoc and the found proto.h header to agree, and it is very easy for PATH to be setup in a way that these do not agree. (I do agree that the problem is less acute for nccl.h, since there isn't also a binary involved.)

To keep this patch moving along, I'm willing to merge it as is, but I think it would be pretty useful to add some sort of sanity checking to cmake "after the fact" (basically, something like, look at the computed includes and libraries, and see if they share a prefix, and error if they don't, and the user hadn't explicitly asked for it.) I don't know how hard this is to do, but in the past I did something similar for CUDA detection in cmake/public/cuda.cmake:

```
  set(file "${PROJECT_BINARY_DIR}/detect_cuda_version.cc")
  file(WRITE ${file} ""
    "#include <cuda.h>\n"
    "#include <cstdio>\n"
    "int main() {\n"
    "  printf(\"%d.%d\", CUDA_VERSION / 1000, (CUDA_VERSION / 10) % 100);\n"
    "  return 0;\n"
    "}\n"
    )
  try_run(run_result compile_result ${PROJECT_RANDOM_BINARY_DIR} ${file}
    CMAKE_FLAGS "-DINCLUDE_DIRECTORIES=${CUDA_INCLUDE_DIRS}"
    LINK_LIBRARIES ${CUDA_LIBRARIES}
    RUN_OUTPUT_VARIABLE cuda_version_from_header
    COMPILE_OUTPUT_VARIABLE output_var
    )
  if(NOT compile_result)
    message(FATAL_ERROR "Caffe2: Couldn't determine version from header: " ${output_var})
  endif()
  message(STATUS "Caffe2: Header version is: " ${cuda_version_from_header})
  if(NOT ${cuda_version_from_header} STREQUAL ${CUDA_VERSION_STRING})
    # Force CUDA to be processed for again next time
    # TODO: I'm not sure if this counts as an implementation detail of
    # FindCUDA
    set(${cuda_version_from_findcuda} ${CUDA_VERSION_STRING})
    unset(CUDA_TOOLKIT_ROOT_DIR_INTERNAL CACHE)
    # Not strictly necessary, but for good luck.
    unset(CUDA_VERSION CACHE)
    # Error out
    message(FATAL_ERROR "FindCUDA says CUDA version is ${cuda_version_from_findcuda} (usually determined by nvcc), "
      "but the CUDA headers say the version is ${cuda_version_from_header}.  This often occurs "
      "when you set both CUDA_HOME and CUDA_NVCC_EXECUTABLE to "
      "non-standard locations, without also setting PATH to point to the correct nvcc.  "
      "Perhaps, try re-running this command again with PATH=${CUDA_TOOLKIT_ROOT_DIR}/bin:$PATH.  "
      "See above log messages for more diagnostics, and see https://github.com/pytorch/pytorch/issues/8092 for more details.")
  endif()
```

Every once in a while, this check prevents me from doing something stupid.

@soumith Let me know what you think about this plan.

**Review by zou3519 — CHANGES_REQUESTED** [review]
blocking until @soumith comments

**Comment by soumith** [comment]
yes that's the patch i was referring to (thanks ezyang for finding it).
At some point someone refactored that file and it's possibly not doing what it intended. But my argument holds that fixing subtle user build issues like these are much easier with a python helper rather than with cmake.

**Comment by xuhdev** [comment]
@ezyang Thanks for the CUDA code and I agree with you that it is a good idea to compare the version set in the library and header as a safeguard.

@soumith @ezyang Would you be OK if I add such a comparison as a safeguard? This should be more rigorous than the prefix checking. In particular, I'll add a `try_run` block in `findNCCL` to make sure [ncclGetVersion](https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/api/comms.html#c.ncclGetVersion) in the found library and `NCCL_VERSION_CODE` in the found header match.

**Comment by xuhdev** [comment]
I think what @soumith pointed out in his last comment is a bigger question.

@soumith I agree with you that, in the long run, in many situations some subtle workaround is easier to do in a Python script (while not for NCCL this time if the solution above is adequate), but I also think it is important to eradicate many issues that the discrepancy caused by the current dual build system, such as duplicated (but not equivalent) system environment checking, inconsistent build options processed by the Python part and CMake part, etc.

What I think is that we should strike a balance, and the core issue is where the balance should be. The best thing I can think of for now is to propose a loose guideline with respect to what should go CMake and what should go Python, and we can discuss from there and further delineate the guideline as we progress to polish the build system. Are you OK with this big direction? I'll open an issue if you feel it's worth discussion.

**Comment by soumith** [comment]
> @soumith @ezyang Would you be OK if I add such a comparison as a safeguard? This should be more rigorous than the prefix checking. In particular, I'll add a try_run block in findNCCL to make sure ncclGetVersion in the found library and NCCL_VERSION_CODE in the found header match.

Sounds good.

> Are you OK with this big direction? 

That sounds fine. And also, you are now around to maintain some of the build scripts ;-)

**Comment by ezyang** [comment]
Yes, this sounds good to me.  And this doesn't have to all happen
overnight, we can land these things partially.  Do you want to go ahead
and land this PR for now?

Excerpts from Soumith Chintala's message of 2019-07-08 23:24:35 -0700:
> > @soumith @ezyang Would you be OK if I add such a comparison as a safeguard? This should be more rigorous than the prefix checking. In particular, I'll add a try_run block in findNCCL to make sure ncclGetVersion in the found library and NCCL_VERSION_CODE in the found header match.
> 
> Sounds good.
> 
> > Are you OK with this big direction? 
> 
> That sounds fine. And also, you are now around to maintain some of the build scripts ;-)
>

**Comment by xuhdev** [comment]
@ezyang I'm OK with either way.

Do we have a minimum supported NCCL version? In PyTorch master, the NCCL version detection seems to be based on the assumption that NCCL >= 3.4.5-5 ([where](https://github.com/NVIDIA/nccl/commit/f93fe9bfd94884cec2ba711897222e0df5569a53#diff-9a2ec58069ebdfb8c304f3a9a9fea6fb) the macro `NCCL_MAJOR` is introduced; of course, version detection would be easier for NCCL later than 3.4.5-5). Is that intended?

**Comment by ezyang** [comment]
You'll have to ask distributed folks.  @mrshenli @pietern might know?
We're generally OK with dropping support for old versions of deps
though.

Excerpts from Hong Xu's message of 2019-07-10 11:32:23 -0700:
> @ezyang I'm OK with either way.
> 
> Do we have a minimum supported NCCL version? In PyTorch master, the NCCL version detection seems to be based on the assumption that NCCL >= 3.4.5-5 ([where](https://github.com/NVIDIA/nccl/commit/f93fe9bfd94884cec2ba711897222e0df5569a53#diff-9a2ec58069ebdfb8c304f3a9a9fea6fb) the macro `NCCL_MAJOR` is introduced; of course, version detection would be easier for NCCL later than 3.4.5-5). Is that intended?
>

**Comment by xuhdev** [comment]
For now, I'll assume NCCL >= 3.4.5-5 for sanity check but will also let it pass if NCCL is older than that.

**Comment by mrshenli** [comment]
Hi @xuhdev, I haven't gone through the full discussion yet, but isn't 2.4 the latest NCCL version? 
https://developer.nvidia.com/nccl

@pietern

**Comment by xuhdev** [comment]
> Hi @xuhdev, I haven't gone through the full discussion yet, but isn't 2.4 the latest NCCL version?
> https://developer.nvidia.com/nccl
> 
> @pietern

Oops, sorry, I meant 2.3.5-5.

**Comment by xuhdev** [comment]
I moved this change to #22818 , and added sanity checks to #22819 , to ease review. Closing this now

**Pull request closed without merging**
