### PR TITLE
[vulkan] Remove unnecessary include in vulkan_api_test

### PR DESCRIPTION
**Pull request by SS-JIA**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74700 Add binary to benchmark model load speed
* #74769 [vulkan] Add option to trigger Vulkan context to load on application start
* **#74699 [vulkan] Remove unnecessary include in vulkan_api_test**

Differential Revision: [D35124882](https://our.internmc.facebook.com/intern/diff/D35124882)

Do not include any files from the Vulkan backend in `vulkan_api_test`, since those headers are not visible to it.

### CODE REVIEW

**Comment by SS-JIA** [comment]
@SS-JIA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35124882).

**Review by beback4u — APPROVED** [review]
I forgot to remove this. Thanks!

**Comment by SS-JIA** [comment]
@SS-JIA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35124882).

**Comment by SS-JIA** [comment]
@SS-JIA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35124882).

**Comment by SS-JIA** [comment]
@SS-JIA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35124882).

**Comment by SS-JIA** [comment]
@SS-JIA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35124882).

**Comment by SS-JIA** [comment]
@SS-JIA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35124882).

**Pull request closed without merging**
