### PR TITLE
[CI] Bump up torchbench version to fix dynamo graph breaks in transformers

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #98003

Summary: When we bump up the torchbench version pin last time, we found
there were new graph breaks introduced with the trasformers version
upgrade, see https://github.com/pytorch/pytorch/pull/96782. Turns out
they are already fixed upstream, see
https://github.com/huggingface/transformers/pull/21648 and https://github.com/pytorch/benchmark/pull/1511

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by desertfire** [comment]
@xuzhao9 , a few new models failed with `ImportError: 'NeighborSampler' requires either 'pyg-lib' or 'torch-sparse'`. Should those lib dependency be added to torchbench?

**Comment by xuzhao9** [comment]
> @xuzhao9 , a few new models failed with `ImportError: 'NeighborSampler' requires either 'pyg-lib' or 'torch-sparse'`. Should those lib dependency be added to torchbench?

Yes, they are the new models added by Intel in https://github.com/pytorch/benchmark/pull/1422. They require users to install the pyg-lib and torch-sparse packages located at https://data.pyg.org/whl/torch-2.0.0+cpu.html.

**Pull request closed without merging**
