### PR TITLE
glu: port cpu forward implementation to ATen

### PR DESCRIPTION
**Pull request by gchanan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #26687 Port GatedLinearUnit forward to TensorIterator.
* **#26410 glu: port cpu forward implementation to ATen**

I only ported the CPU forward implementation for now to try a CPU-only benchmark.

Differential Revision: [D17454519](https://our.internmc.facebook.com/intern/diff/D17454519)

### CODE REVIEW

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Wait, it is exactly same code for CUDA as well, could you please migrate both CPU and CUDA. This was you can probably nuke part of nn.yaml as well.

**Comment by gchanan** [comment]
I think you probably need to move the backward as well before you can get rid of the nn.yaml stuff.

We should probably disconnect those things so you can make incremental PRs, though.

**Comment by gchanan** [comment]
also the CUDA code fuses the sigmoid/mul via parallel_apply.

**Comment by VitalyFedyunin** [comment]
Depends how popular glu is, we can have separate (good as first issue) task to fuse them for CPU.

**Comment by gchanan** [comment]
ya, I think that's a good idea; I just don't want to gait ports on the ideal.

**Review by ezyang — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Merge as is, we have #26418 now

**Pull request closed without merging**
