### PR TITLE
fix tensor_repr(at::Tensor)  (#134762)

### LINKED ISSUE #134762: After using "torch-tensor-repr Tensor"，The "Tensor" variable becomes UndefinedTensor
### 🐛 Describe the bug

```python
# test_scaled_dot_product_attention.py   

import torch
import torch.nn.functional as F
from torch.nn.attention import sdpa_kernel, SDPBackend
from torch import inf

device='cuda'
q = torch.tensor([[[[-0.3313,  0.5768],
          [ 0.1334,  0.6123],
          [-0.6594, -0.1936],
          [-0.4009, -1.1215]],

         [[-0.2542,  0.2620],
          [-0.1803, -0.7368],
          [ 0.4471,  0.2735],
          [ 0.1007, -0.2059]],

         [[-0.3820,  0.4473],
          [-0.3855,  0.5480],
          [-0.5695,  0.0879],
          [-0.8565, -0.8578]],

         [[ 0.1422,  0.4125],
          [ 0.2482, -0.2683],
          [ 0.1945, -0.8867],
          [ 1.1332, -0.1735]]],


        [[[ 0.5657,  0.2606],
          [ 0.8316, -0.1097],
          [ 0.1557,  1.1108],
          [-0.3531,  0.4189]],

         [[ 0.3400,  0.3829],
          [-0.2595,  0.2666],
          [-1.3184, -0.0565],
          [ 0.3332,  0.1775]],

         [[ 0.4977,  0.2799],
          [ 0.3651, -0.1559],
          [ 1.0253, -1.3255],
          [ 0.0642, -1.4244]],

         [[-0.6632, -0.2317],
          [-0.0400,  0.2458],
          [-0.4907, -0.7546],
          [-0.2615, -2.0718]]]], device=device)
k = torch.tensor([[[[ 1.0370,  0.4798],
          [ 0.7290, -0.1673],
          [-0.4613, -0.5825],
          [ 0.1058,  0.1304]],

         [[ 0.5682,  0.2530],
          [ 0.0241,  0.2535],
          [ 0.1805, -0.2237],
          [-0.2210,  0.6242]],

         [[ 0.0327, -0.3588],
          [ 0.4650, -0.4627],
          [ 0.1244,  0.4913],
          [ 0.3758,  0.4677]],

         [[-0.2546,  0.9355],
          [ 0.2496,  0.6018],
          [ 1.0947, -1.1829],
          [ 1.0116, -0.8344]]],


        [[[-0.4283, -0.5132],
          [-0.0276, -0.2733],
          [ 0.2496,  0.1805],
          [-0.0715, -0.2410]],

         [[ 0.0696, -0.5883],
          [-0.0755, -0.3164],
          [-0.7018, -0.2908],
          [-0.3276, -0.2789]],

         [[-0.0737,  0.4240],
          [ 0.4368,  1.0251],
          [ 0.4959,  0.2148],
          [ 0.1271,  0.0966]],

         [[-0.4718, -0.0114],
          [-0.1748,  0.0177],
          [ 0.8074, -0.8456],
          [ 1.2021, -1.6366]]]], device=device)

v = torch.tensor([[[[ 1.1711e-01,  9.7816e-01],
          [-1.4553e-01,  2.7810e-01],
          [-1.4165e-01, -4.4159e-01],
          [-5.4208e-01,  1.0320e+00]],

         [[-8.0137e-01, -1.2661e+00],
          [-1.0142e+00, -4.0317e-01],
          [ 9.1506e-01,  5.2039e-01],
          [ 9.2211e-02, -1.8883e-01]],

         [[ 2.5000e-01, -8.7749e-01],
          [-7.5105e-01, -4.7226e-04],
          [ 3.9992e-01,  9.7360e-01],
          [ 6.6191e-01, -6.1057e-01]],

         [[-1.2200e+00,  4.3458e-01],
          [-1.4780e-02,  2.6286e-01],
          [ 4.1772e-01,  2.5125e-01],
          [-8.6761e-01,  6.2330e-02]]],


        [[[ 3.4582e-01, -8.6573e-01],
          [-9.4426e-02, -1.3522e-01],
          [-3.0205e-01, -6.8622e-02],
          [ 5.6740e-02,  7.6430e-02]],

         [[ 5.4049e-01,  4.0496e-01],
          [-1.0218e-01,  3.0620e-02],
          [-3.2552e-01,  1.7594e-01],
          [ 1.0315e+00,  1.7801e-01]],

         [[ 3.0589e-01,  3.6384e-01],
          [ 1.1659e+00, -8.6477e-01],
          [-1.0766e+00, -1.0674e+00],
          [-1.0885e+00, -1.8474e-01]],

         [[ 2.6526e-01,  6.1404e-02],
          [-1.2641e+00,  5.9070e-01],
          [-1.2353e+00,  1.3355e+00],
          [-4.0602e-01,  7.4847e-01]]]], device=device)

attn_mask = torch.tensor([[[[-inf, -inf, 0., -inf],
          [0., 0., 0., -inf],
          [-inf, -inf, -inf, -inf],
          [0., 0., -inf, 0.]]]], device=device)  

dropout_p = 0.0  
is_causal = False  
with sdpa_kernel([SDPBackend.MATH]):
    attn_output = F.scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
print(attn_output)  
```    
Use gdb to debug the above code， gdb --args python Prac/test_scaled_dot_product_attention.py 
image

Note: gdb version
**GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2**

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-glibc2.31
Is CUDA available: N/A
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4

Nvidia driver version: 525.85.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          80
On-line CPU(s) list:             0-79
Thread(s) per core:              2
Core(s) per socket:              20
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz
Stepping:                        7
CPU MHz:                         2100.000
BogoMIPS:                        4200.00
Virtualization:                  VT-x
L1d cache:                       1.3 MiB
L1i cache:                       1.3 MiB
L2 cache:                        40 MiB
L3 cache:                        55 MiB
NUMA node0 CPU(s):               0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78
NUMA node1 CPU(s):               1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; Load fences, __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] pytorch-triton==3.0.0+dedb7bdf33
[pip3] torch==2.4.0a0+git481a3f9
[pip3] torchaudio==2.1.0
[pip3] torchelastic==0.2.2
[pip3] torchvision==0.19.0.dev20240428+cu118
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46343  
[conda] mkl-include               2024.2.1                 pypi_0    pypi
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl-static                2024.2.1                 pypi_0    pypi
[conda] mkl_fft                   1.3.8           py310h5eee18b_0  
[conda] mkl_random                1.2.4           py310hdb19cb5_0  
[conda] numpy                     1.26.0          py310h5f9d8c6_0  
[conda] numpy-base                1.26.0          py310hb5e798b_0  
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-triton            3.0.0+dedb7bdf33          pypi_0    pypi
[conda] torch                     2.4.0a0+git8ff85b4          pypi_0    pypi
[conda] torchaudio                2.1.0               py310_cu118    pytorch
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchvision               0.19.0a0+61d97f4          pypi_0    pypi

cc @albanD @drisspg @mikaylagawarecki

### PR DESCRIPTION
**Pull request by 1274085042**
Fixes #134762
@ezyang @antocuni

### CODE REVIEW

**Comment by ezyang** [comment]
Can you put a comment explaining why the tensor cannot be moved out of? Naively, looking at the code as is, it seems that moving out of it should not have any effect, as to call this function a copy must have been made of the tensor anyway.

**Comment by 1274085042** [comment]
> Can you put a comment explaining why the tensor cannot be moved out of? Naively, looking at the code as is, it seems that moving out of it should not have any effect, as to call this function a copy must have been made of the tensor anyway.
```c++
char* tensor_repr(at::Tensor tensor) {
  std::cout<<&(tensor.getIntrusivePtr())<<std::endl;
  PyGILState_STATE gil = PyGILState_Ensure();
... ...
```
I printed the address of `tensor`'s intrusive_ptr in `tensor_repr` and found that it is the same as the address of `query_`
image

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
