### PR TITLE
inductor: fix guard_equals

### PR DESCRIPTION
**Pull request by chunyuan-w**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #94506

Fixes https://github.com/pytorch/pytorch/issues/94268.

In the code before https://github.com/pytorch/pytorch/pull/92609, there was an assertion in the `guard_equals` function.
```python
assert self.size_hint(expr) == 0, (expr, self.size_hint(expr))
```

In https://github.com/pytorch/pytorch/pull/92609, `guard_equals` has been changed to
```python
def guard_equals(self, left: Expr, right: Expr) -> Expr:
    self.shape_env.evaluate_expr(sympy.Eq(left, right))
    return left
```
Considering the case where `left` and `right` are both concrete values for example, `left = 10` and `right = 20`. In the current code, `self.shape_env.evaluate_expr(sympy.Eq(left, right))` will directly return `False`:
https://github.com/pytorch/pytorch/blob/a81cf49d9733b04a2931c85a154ab0bb698650b3/torch/fx/experimental/symbolic_shapes.py#L1380-L1385

This returned value is not used anywhere and the `guard_equals` function will still `return left` in this case even though `left != right`.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Review by EikanWang — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by desertfire** [comment]
Thanks for the fix. This brings a general question, when can we have the CPU inference check on CI (since you mentioned hf_BigBird in the test code)?

**Review by Chillee — APPROVED** [review]

**Comment by EikanWang** [comment]
> Thanks for the fix. This brings a general question, when can we have the CPU inference check on CI (since you mentioned hf_BigBird in the test code)?

Hi @desertfire , my previous understanding was just to enable the CPU accuracy test in the CI but did not require additional PR. May I know what I should do to enable the accuracy test?

**Comment by desertfire** [comment]
> > Thanks for the fix. This brings a general question, when can we have the CPU inference check on CI (since you mentioned hf_BigBird in the test code)?
> 
> Hi @desertfire , my previous understanding was just to enable the CPU accuracy test in the CI but did not require additional PR. May I know what I should do to enable the accuracy test?

Currently the inference 
accuracy test is only done for CUDA ( https://github.com/pytorch/pytorch/blob/963d8f547e9494250817ab070177fdb7b2c8d95f/.ci/pytorch/test.sh#L286). You can add separate shards in https://github.com/pytorch/pytorch/blob/master/.github/workflows/inductor.yml and add corresponding tests command in https://github.com/pytorch/pytorch/blob/master/.ci/pytorch/test.sh.

**Comment by EikanWang** [comment]
> Currently the inference accuracy test is only done for CUDA (
> 
> https://github.com/pytorch/pytorch/blob/963d8f547e9494250817ab070177fdb7b2c8d95f/.ci/pytorch/test.sh#L286
> 
> ). You can add separate shards in https://github.com/pytorch/pytorch/blob/master/.github/workflows/inductor.yml and add corresponding tests command in https://github.com/pytorch/pytorch/blob/master/.ci/pytorch/test.sh.

Thanks for your information. Will finish it ASAP.

**Pull request closed without merging**
