### PR TITLE
Part 1: UFMT partial files in torch/optim due to the pr-sanity-checks

### PR DESCRIPTION
**Pull request by fffrog**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #124055
* #124054
* __->__ #124053
* #124048

### CODE REVIEW

**Comment by ezyang** [comment]
Note for future, you do not have to split your PRs for sanity checks, it makes my work harder

**Comment by ezyang** [comment]
diff

```
diff --git b/torch/optim/lr_scheduler.py a/torch/optim/lr_scheduler.py
index 7857adfb0b8..a77bb378d83 100644
--- b/torch/optim/lr_scheduler.py
+++ a/torch/optim/lr_scheduler.py
@@ -1781,8 +1781,9 @@ class OneCycleLR(LRScheduler):
         step_num = self.last_epoch
 
         if step_num > self.total_steps:
-            raise ValueError("Tried to step {} times. The specified number of total steps is {}"
-                             .format(step_num, self.total_steps))
+            raise ValueError(
+                f"Tried to step {step_num} times. The specified number of total steps is {self.total_steps}"  # noqa: UP032
+            )
 
         for group in self.optimizer.param_groups:
             start_step = 0
```

**Review by ezyang — APPROVED** [review]

**Comment by FFFrog** [comment]
> Note for future, you do not have to split your PRs for sanity checks, it makes my work harder

Got it.

**Pull request closed without merging**
