### PR TITLE
move batch_first transposing outside PackPadded.forward()

### PR DESCRIPTION
**Pull request by anderspapitto**
batch_first is a bool, which means it breaks tracing when it is an
argument to a forward() function. Move it outside

### CODE REVIEW

**Comment by apaszke** [comment]
If the problem is with non-Tensor arguments, then don't you have to do the same with `padding_value`?

To be honest I'm really worried about what's happening to this rnn code. In its current form it will be impossible to ever do any reasonable refactors, because it's so deeply entangled with ONNX, and this dependencies are completely invisible 😕

**Comment by anderspapitto** [comment]
yes, updated to handle padding_value as well.

I see your point. At the moment it's the only way though, due to how the tracer is implemented, so we would have to find another implementation strategy or discard the tracer.

Also, in general I feel that "arguments to forward() must be Variables" seems to be a decent principle independent of ONNX, and makes the code cleaner/simpler on its own. For example in this diff, notice that now once the transpose() is moved outside of forward(), it's no longer necessary to manually reverse it in backward().

**Comment by ezyang** [comment]
@anderspapitto I don't think you have to discard the tracer to fix this problem.

The root problem is that the current symbolic override tracing hack is implemented via Python-level autograd Function, which imposes the "arguments to forward must be Variable"s restriction. But there is no fundamental reason for ONNX export that this must be the case, and indeed, for the ATen exports you can see many operations which take non-Variable inputs and use those for export. And *changing* the implementation of a PyTorch autograd function (being used to actually compute backwards) is absolutely a case of tail wagging the dog. In this particular case it doesn't matter (because he net compute is the same) but in some cases it could be very important for an operation to not be hoisted out of forward/backward, because the automatically computed backwards is less efficient than a manually imported one.

Now, how to fix this without discarding the tracer? Simple: we need a new API. Recall how we implement tracing in ATen (the most recent description is in 27505e642963bb8b8c18abdcc6dbed4d41ffa0db). There's three steps:

1. We run a `symbolic` on the inputs to the function we want to override
2. Run the function
3. Attach the trace to the returned outputs

(You have to split it this way to handle inplace). So all we need is to be able to do this from Python, and then the symbolic override hack is a lot simpler, and we can use this to implement tracing for Python-level functions. What do you think.

**Comment by anderspapitto** [comment]
probably will be addressing this in a different way

**Comment by apaszke** [comment]
@ezyang Just note that it's not a limitation of the Python autograd function - they can take arbitrary objects as arguments. I think it's the constraint for the logic in the symbolic machinery that is expecting a flat list of tensors (I wrote it when it was used in a single place that had a flat tensor arg list already).

**Pull request closed without merging**
