### PR TITLE
Reduce warning suppression by just disabling pytest warnings plugin

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #86255

Fixes https://github.com/pytorch/pytorch/issues/85626

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
This is acceptable to me :)

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
