### PR TITLE
Update xla image tag

### PR DESCRIPTION
**Pull request by yeounoh**
Follow up, https://github.com/pytorch/xla/pull/4584 to support CUDA 11.7 and sccahe.

cc @bdhirsh

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by yeounoh** [comment]
@malfet can we merge this? Should I rebase?

**Comment by huydhn** [comment]
Just curious, I notice that XLA test time increases by a lot with this change.  It currently takes 80 minutes or so on a 4xlarge runner https://hud.pytorch.org/pytorch/pytorch/commit/fe0e28ab87ddda38a82efe74dd3eaf05e926f117.  On the other hand, the test time on the https://hud.pytorch.org/pr/94377 is 130 minutes.  Is this expected?

**Comment by yeounoh** [comment]
> Just curious, I notice that XLA test time increases by a lot with this change. It currently takes 80 minutes or so on a 4xlarge runner https://hud.pytorch.org/pytorch/pytorch/commit/fe0e28ab87ddda38a82efe74dd3eaf05e926f117 (or [HUD TTS](https://hud.pytorch.org/tts/pytorch/pytorch/master?jobName=pull%20%2F%20linux-bionic-py3_8-clang8-xla%20%2F%20test%20(xla%2C%201%2C%201%2C%20linux.4xlarge))). On the other hand, the test time on the https://hud.pytorch.org/pr/94377 is 130 minutes. Is this expected?

@huydhn It's not expected, is it possible to toggle the sccache feature on/off to compare? We can also try to compare with v0.9 and v1.0 images with a fixed XLA pin.

**Comment by yeounoh** [comment]
@huydhn @malfet  I will block some time to look at the regression.

**Comment by yeounoh** [comment]
@huydhn I think I know what's happening. The previous runs were building XLA much fast <20min, since it was using the cached objects. Now with the recent TF pin update and the image possibly, I think the newer one just runs slow due to the increased build time ~50min. To verify that this is the case, and the follow up runs would run ~80min, I re-started the job. We expect the non-cached CI build to take ~50 min. And I manually checked the test times, and they all look good.

**Comment by huydhn** [comment]
Thank you for the quick investigation!  I will wait till XLA jobs finish to confirm and merge the change

**Pull request closed without merging**
