### PR TITLE
Split cuda: list cpp files that go in _cu library explicitly

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #67875
* #67874
* #67721
* #66980
* #66979
* __->__ #69082

Differential Revision: [D32723669](https://our.internmc.facebook.com/intern/diff/D32723669)

### CODE REVIEW

**Review by dagitses — APPROVED** [review]
confirmed file does not exist

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32723669).

**Comment by peterbell10** [comment]
@dagitses we're too late, the original PR was reverted :(

@malfet is there any way to avoid reverts when a fix is already known.

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@peterbell10 yes, leaving the comment on PR that introduced the regression is usually the good sign. Or creating a `ci:sev` issue so that everyone looking at the dashboard will be aware of what is going on

**Review by malfet — CHANGES_REQUESTED** [review]
Please keep all filelists in `[tools/build_variables.bzl](https://github.com/pytorch/pytorch/blob/master/tools/build_variables.bzl) (this way that could be shared between CMake and bazel builds)

**Comment by peterbell10** [comment]
Okay, thanks for the info. I understand that revert and re-land is easier to guarantee correctness. It just seems overkill when the fix is so simple.

>Please keep all filelists in `tools/build_variables.bzl (this way that could be shared between CMake and bazel builds)

@malfet bazel doesn't have a split cuda build.

**Comment by peterbell10** [comment]
@malfet I've changed the code to use `build_varables.bzl` and also keep the source lists for `torch_cuda_cpp` and `torch_cuda_cu` separate instead of mixing them together only to split them apart again with regexes that were really just another form of file lists.

**Review by malfet — APPROVED** [review]

**Comment by peterbell10** [comment]
@dagitses PTAL

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32723669).

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32723669).

**Pull request closed without merging**
