### PR TITLE
[ONNX] Update onnx submodule to 1.12

### LINKED ISSUE #79461: Validate ONNX 1.12.0 release candidate
Please help us test ONNX 1.12.0 by running your tests with it installed.
https://test.pypi.org/project/onnx/1.12.0rc4/
https://github.com/onnx/onnx/tree/rel-1.12.0

### PR DESCRIPTION
**Pull request by justinchuby**
Update onnx submodule to the 1.12 release

### CODE REVIEW

**Comment by justinchuby** [comment]
@jcwchen looks like the numpy version used in pytorch does not have `numpy.typing`. Since numpy.typing is only use once in onnx https://github.com/onnx/onnx/blob/529f7cab88eed143fc9f0126147e9732585e4c5e/onnx/numpy_helper.py#L17, should we remove it and keep the max compatibility?

**Comment by justinchuby** [comment]
https://github.com/onnx/onnx/pull/4277

**Comment by jcwchen** [comment]
> @jcwchen looks like the numpy version used in pytorch does not have numpy.typing. Since numpy.typing is only use once in onnx https://github.com/onnx/onnx/blob/529f7cab88eed143fc9f0126147e9732585e4c5e/onnx/numpy_helper.py#L17, should we remove it and keep the max compatibility?

Thank you for catching this and the ONNX PR. Yes, to keep the max compatibility, ONNX should not reply on newer NumPy.

**Review by jcwchen — COMMENTED** [review]
I would like to know more context about the required NumPy version for PyTorch since ONNX will probably upgrade its minimum supported NumPy version in the near future: do you know what the minimum supported NumPy version for PyTorch is right now? Thanks!

**Comment by justinchuby** [comment]
@jcwchen I will need to find out

**Comment by justinchuby** [comment]
https://github.com/pytorch/pytorch/runs/6909270220?check_suite_focus=true

```
/opt/conda/lib/python3.7/site-packages/caffe2/python/onnx/backend.py:713: in prepare
    init_net, predict_net = cls._onnx_model_to_caffe2_net(model, device, opset_version, False)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cls = <class 'caffe2.python.onnx.backend.Caffe2Backend'>
onnx_model = ir_version: 8
producer_name: "backend-test"
graph {
  node {
    input: "x"
    output: "y"
    op_type: "BlackmanWind... dim {
            dim_value: 10
          }
        }
      }
    }
  }
}
opset_import {
  domain: ""
  version: 17
}
device = 'CPU', opset_version = 17, include_initializers = False
    @classmethod
    def _onnx_model_to_caffe2_net(cls, onnx_model, device, opset_version, include_initializers):
        device_option = get_device_option(Device(device))
        # Prior to onnx version update to onnx-1.8.0, errors caused by failures in
        # in the onnx shape inference call were being supressed. Hence a try-catch block
        # is added around the infer_shapes call to avoid these failures and preserve status
        try:
            onnx_model = onnx.utils.polish_model(onnx_model)
        except RuntimeError:
            warnings.warn("ShapeInferenceWarning: Inferred shape and existing shape differ in rank")
        except AttributeError:
            warnings.warn("ShapeInferenceWarning: utils module not found in ONNX version {}".format(onnx.__version__))
        # Optimizer module has been removed in ONNX-1.9 or later, warn caller if that is the case
        try:
            init_model = cls.optimize_onnx(onnx_model, init=True)
            pred_model = cls.optimize_onnx(onnx_model, predict=True)
        except ModuleNotFoundError:
            warnings.warn("OptimizerWarning: onnxoptimizer module not installed. "
                          "init_model and pred_model models will not be splitted, which can cause a runtime error")
            init_model = onnx_model
            pred_model = onnx_model
        init_net = caffe2_pb2.NetDef()
        pred_net = caffe2_pb2.NetDef()
        init_net.name = onnx_model.graph.name + '_init'
        pred_net.name = onnx_model.graph.name + '_predict'
        if include_initializers:
            init_net.op.extend(cls._create_tensor_filling_op(tp) for tp in onnx_model.graph.initializer)
        cls._dummy_name.reset(cls._all_names_in_graph(init_model.graph) | cls._all_names_in_graph(pred_model.graph))
        errors = []
        for net, model in ( (init_net, init_model), (pred_net, pred_model) ):
            net.device_option.CopyFrom(device_option)
            for node in model.graph.node:
                try:
                    c2ops = cls._onnx_node_to_caffe2_op(
                        init_model, pred_model, node, opset_version)
                except Exception as e:
                    msg = 'Error while processing node: {}. Exception: {}'.format(node, e)
                    errors.append(msg)
                    print('ONNX FATAL:', msg, file=sys.stderr)
                    continue
                init_net.op.extend(c2ops.init_ops)
                net.op.extend(c2ops.ops)
                net.external_input.extend(c2ops.interface_blobs)
            net.external_output.extend(
                value_info.name for value_info in model.graph.output)
            net.external_input.extend(
                value_info.name for value_info in model.graph.input)
        if len(errors) > 0:
            raise RuntimeError(
                "ONNX conversion failed, encountered {} errors:\n\n{}".format(
>                   len(errors), "\n\n".join(errors)))
E           RuntimeError: ONNX conversion failed, encountered 2 errors:
E           
E           Error while processing node: input: "x"
E           output: "y"
E           op_type: "BlackmanWindow"
E           . Exception: Don't know how to translate op BlackmanWindow
E           
E           Error while processing node: input: "x"
E           output: "y"
E           op_type: "BlackmanWindow"
E           . Exception: Don't know how to translate op BlackmanWindow
```

**Review by garymm — APPROVED** [review]
Thanks!

**Review by msaroufim — APPROVED** [review]

**Pull request closed without merging**
