### PR TITLE
add checking key for check_fqn function

### PR DESCRIPTION
**Pull request by zhaojuanmao**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96705

### CODE REVIEW

**Review by awgu — COMMENTED** [review]
This looks good to me, but I am wondering if we want to add any unit tests to verify the assertion.

**Review by rohan-varma — APPROVED** [review]
LGTM

**Comment by awgu** [comment]
@zhaojuanmao It looks like this did not merge into master but instead into your own branch?

**Comment by zhaojuanmao** [comment]
yes, it is weird, I used ghstack, so it is merging into my branch, not master, so created a new PR

**Comment by awgu** [comment]
> yes, it is weird, I used ghstack, so it is merging into my branch, not master, just created a new PR

Maybe it was because you did not use the pytorchbot to merge?

**Pull request merged**
