### PR TITLE
Use unodered_map for faster search of signal handlers

### PR DESCRIPTION
**Pull request by cyyever**
This PR accelerates search of signal handlers.

### CODE REVIEW

**Comment by Skylion007** [comment]
Shouldn't we be using the std::signal, std::raise APIs in csignal? I am actually not sure since I do not see it as deprecated like other headers in modernize-headers.

**Comment by Skylion007** [comment]
Have you tested this locally? I am not sure this is covered by our test suite (but I could be wrong).

**Comment by cyyever** [comment]
> Have you tested this locally? I am not sure this is covered by our test suite (but I could be wrong).

I relies on the tests also.

**Pull request closed without merging**
