### PR TITLE
only unspecialize float during eager

### PR DESCRIPTION
**Pull request by bobrenjc93**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #141236
* #140893
* #138922
* __->__ #138915

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Comment by ezyang** [comment]
So I believe some of these failures are because we now have float inputs that are going into the Z3 validator, but the Z3 validator doesn't support float inputs atm. We could try adding float inputs to Z3, but it's probably not worth, because we're not doing any nontrivial simplification on expressions on floats. Better to just directly swap all of the floats with concrete values before sending to Z3.

**Comment by ezyang** [comment]
the new bugs look pretty tame!

**Comment by bobrenjc93** [comment]
Green CI for specialize float eager. This counts as a milestone right @ezyang? I think maybe it's a good idea to check this in to prevent regressions? Will put up review but happy to go either way (land vs no land).

**Comment by ezyang** [comment]
Yeah this is one sweet milestone! I may have some quibbles about this implementation mechanism if we are going to land it though. I do agree it is good to prevent regressions but "this config only defaults true on eager backend" is not a great intermediate state, in particular it will make it harder to debug unrelated problems by switching to eager backend. Could we perhaps do something like turn this on only for the Dynamo CI flavor since IIRC that's where most of your failing tests were found?

**Pull request closed without merging**
