### PR TITLE
explicitly list out caffe2 protos

### PR DESCRIPTION
**Pull request by dagitses**
explicitly list out caffe2 protos

Summary: This will make it easier to split up this library.

Test Plan: Rely on CI.

Reviewers: sahanp

Subscribers:

Tasks:

Tags:

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/pytorch/pull/97334).
* #97337
* #97336
* #97335
* __->__ #97334

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
Can you please add an explanation why? I.e. globs are good as generally all files committed into the folder should be built for the project, aren't they?

**Comment by dagitses** [comment]
> Can you please add an explanation why? I.e. globs are good as generally all files committed into the folder should be built for the project, aren't they?

Globs can be particularly convenient for the Meta internal builds, since they are not visible to many contributors, and not easily checked even by Meta employees.

However, the use of globs does encourage building more than we need. The goal I'm trying to achieve here is to have a minimal caffe2 dependency to build libtorch with. For that goal, I only need two of the protos.

The advantage of globs in my opinion is outweighed by the disadvantages for code like caffe2, which is mostly frozen and fully open sourced. We don't expect much churn, if any, and any issues are expected to be caught by open source CI.

**Review by PaliC — APPROVED** [review]
I agree with Mikey its better to reduce dependencies where its reasonable to do so.

**Comment by malfet** [comment]
@dagitses can you please make sure that CMake behaves in the same way then?

**Comment by malfet** [comment]
> However, the use of globs does encourage building more than we need. The goal I'm trying to achieve here is to have a minimal caffe2 dependency to build libtorch with. For that goal, I only need two of the protos.

How this change achieves it?
There are 7 files in that folder (according to `ls -1 caffe2/proto/*.proto|wc -l`) and this PR lists 7 files explicitly. 

> The advantage of globs in my opinion is outweighed by the disadvantages for code like caffe2, which is mostly frozen and fully open sourced. We don't expect much churn, if any, and any issues are expected to be caught by open source CI.

How being frozen and fully open-sourced is disadvantage for using globs?

**Comment by malfet** [comment]
> I agree with Mikey its better to reduce dependencies where its reasonable to do so.

@PaliC can you please help me understand, how this change reduces dependencies?

**Comment by dagitses** [comment]
> > I agree with Mikey its better to reduce dependencies where its reasonable to do so.
> 
> @PaliC can you please help me understand, how this change reduces dependencies?

This change does not do it alone, it's the two subsequent changes that pull out caffe2.proto and torch.proto respectively that do when combined with a later change that removes the full caffe2 dependency from torch.

**Comment by dagitses** [comment]
> > However, the use of globs does encourage building more than we need. The goal I'm trying to achieve here is to have a minimal caffe2 dependency to build libtorch with. For that goal, I only need two of the protos.
> 
> How this change achieves it? There are 7 files in that folder (according to `ls -1 caffe2/proto/*.proto|wc -l`) and this PR lists 7 files explicitly.
This change does not do it. This change makes it easier to see subsequent changes that show this library shrinking in size by removing each of those explicit listings.
> 
> > The advantage of globs in my opinion is outweighed by the disadvantages for code like caffe2, which is mostly frozen and fully open sourced. We don't expect much churn, if any, and any issues are expected to be caught by open source CI.
> 
> How being frozen and fully open-sourced is disadvantage for using globs?

It's not a disadvantage for the glob. It just suppresses the advantage because it's easy to maintain the list when it's readily visible in the source adjacent to the code that's being modified.

**Pull request closed without merging**
