### PR TITLE
[DeviceMesh] Directly retrieve flattened mesh if already created

### PR DESCRIPTION
**Pull request by wz337**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #133277
* __->__ #133195
* #133193

Add mapping to keep track of root_to_flatten relationship and directly retrieve the flattened mesh if already created (no pg creation). 

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wconstab @d4l3k @c-p-i-o @tianyu-l

### CODE REVIEW

**Review by fegin — APPROVED** [review]
Just want to clarify, we still cannot slice the flattened dimension even with this PR, is that correct? This PR just caches the PG creation.

**Comment by wz337** [comment]
> Just want to clarify, we still cannot slice the flattened dimension even with this PR, is that correct? This PR just caches the PG creation.

Yes. I'll post the slicing one soon.

**Review by wanchaol — APPROVED** [review]

**Pull request closed without merging**
