### PR TITLE
ci: Add credentials to upload_test_statistics

### LINKED ISSUE #72950: MacOS test jobs failing with botocore.exceptions.NoCredentialsError: Unable to locate credentials
> NOTE: Remember to label this issue with "`ci: sev`"

## Current Status
ongoing

## Error looks like
```
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```
In the Display Stats step of MacOS test jobs

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*
- 2/16 8:33am incident began
- 2/16 2:07pm detected by @malfet looking at the HUD
- 2/16 2:58pm fix (#72955) submitted by @seemethere 

## User impact
*How does this affect users of PyTorch CI?*
MacOS tests all red but not their fault

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #72955

Adds credentials to macOS workflows to upload_test_statistics when
needed

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

Differential Revision: [D34287425](https://our.internmc.facebook.com/intern/diff/D34287425)

### CODE REVIEW

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34287425).

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@pytorhbot merge this

**Pull request closed without merging**
