### PR TITLE
[inductor] allow mm template to accumulate with float16 dtype

### LINKED ISSUE #108621: [inductor] Triton matmul templates should use reduced_precision_reduction flags
In eager mode [we have flags](https://pytorch.org/docs/stable/notes/cuda.html#reduced-precision-reduction-in-fp16-gemms) for using fp16 accumulators in matmuls.

Currently, our Triton matmul templates ignore this flag and always accumulate in float32.  This will make them slower, so we may be leaving some perf on the table in max-autotune mode.

The implementation of this just involves updating the `acc_type` function to read the correct flags:
https://github.com/pytorch/pytorch/blob/c8e72a4a5c6398ad38d41ceee9775f8d4544225c/torch/_inductor/kernel/mm_common.py#L134-L137

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### PR DESCRIPTION
**Pull request by hgl71964**
Fixes #108621

replace #108637 and #108982 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang @Xia-Weiwen @ngimel

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
Looks good, though there are lints a test failures.

Most of the test failures seem to be on main, so you might need to rebase as well.

**Comment by jansel** [comment]
Lints can be fixed with `make setup_lint && lintrunner -a`

**Review by jansel — DISMISSED** [review]

**Comment by jansel** [comment]
@hgl71964 looks like there are failures on AMD.  Maybe we need to turn this off if `torch.version.hip` is set.

**Comment by hgl71964** [comment]
Why is the name of the test suite "ROCm" but the failing test name test_uint4x2_mixed_mm_cuda? The appended "cuda" seems to imply it is tested on a NVIDIA GPU. Could it be a bug in the test infra?

I have loosen the precision requirement for test_uint4x2_mixed_mm. Unfortunately I don't have a AMD GPU, so I might need to rely on CI to test.

**Comment by PaliC** [comment]
@pytorchbot revert -m "breaking tests internally" -c "ghfirst"

Getting the following errors
```
: error: invalid element type in packLLEElements. Expected 'f16' but got 'f32'
```

for inductor tests (possibly try running TORCH_LOGS="output_code with test/inductor/test_select_algorithm.py and you might be able to reproduce. 

```
torch/testing/_internal/common_utils.py", line 3565, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Tensor-likes are not close!

Mismatched elements: 98 / 102960 (0.1%)
Greatest absolute difference: 0.03125 at index (12, 6) (up to 1e-05 allowed)
Greatest relative difference: 0.0012273788452148438 at index (391, 108) (up to 0.001 allowed)
```
for one of the models we are teating internally

**Comment by hgl71964** [comment]
hey @PaliC,

 I try to reproduce the error by running TORCH_LOGS="output_code" python test/inductor/test_select_algorithm.py but it passes all test cases. My local environment is an intel CPU and NVIDIA A100 GPU

**Review by jansel — APPROVED** [review]
These changes seem fine, though we should debug the test error.

@PaliC that repo doesn't seem to work, can we open source the failing test?

**Pull request closed without merging**
