### PR TITLE
remove  benchmarks/__init__.py 

### PR DESCRIPTION
**Pull request by laithsakka**
trying to address https://github.com/pytorch/pytorch/issues/133377

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #133390

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Comment by laithsakka** [comment]
this will probably make pr_time_benchmarks fails but testing it for now.

**Review by kit1980 — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Alternatively you can exclude benchmarks at  setup.py level

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
