### PR TITLE
[sparse][semi-structured] add alg_id to _cslt_sparse_mm and _cslt_sparse_mm_search

### PR DESCRIPTION
**Pull request by jcaip**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #115178

Summary:

cuSPARSELt has support for different alg_id, which are set via

`cusparseLTMatmulAlgSetAttribute`, in total there are 4 different
alg_ids, 0 - 3.

Previously we were just using the default alg_id, as from our initial
experiments we found that for most shapes the default alg_id is the
fastest and that they made no difference on numerical correctness, just
performance. From our previous experiments the fastest alg_id seemed to
differ only on small matmul shapes.

danthe3rd found a performance regression when running with
cuSPARSELt v0.4.0 vs v0.5.0, on LLM shapes, which match these
characteristics (activations are small, weights are large).

However it's likely that this is due to the alg_id ordering changing, as
mentioned in the release notes for v0.5.0.
```
cusparseLtMatmulAlgSelectionInit() does not ensure the same ordering of
algorithm id alg as in v0.4.0.
```

This PR adds in the following:
- support for passing in alg_id to _cslt_sparse_mm
- a new op, _cslt_sparse_mm_search, which returns the optimal alg_id for
  a given matmul

_cslt_sparse_mm_search has the same function signature as
_cslt_sparse_mm, minus the alg_id parameter.
We are able to achieve v0.4.0 performance with alg_id=1 on the shapes
that daniel provided.

We will address autoselecting the best alg_id in a future PR, possibly
with torch.compile.

Test Plan:
```
python test/test_sparse_semi_structured -k cslt
```

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Comment by jcaip** [comment]
@danthe3rd here are the benchmark results for alg_id:

```
CuSparseLt v0.5.0 | alg_id: 0
input: [56, 11008] | weight: [4096, 11008]
  gemm@sp24: 152.5 us
  gemm     : 73.36 us
input: [56, 4096] | weight: [12288, 4096]
  gemm@sp24: 68.81 us
  gemm     : 77.14 us
input: [56, 4096] | weight: [22016, 4096]
  gemm@sp24: 87.32 us
  gemm     : 126.61 us
input: [56, 4096] | weight: [4096, 4096]
  gemm@sp24: 65.38 us
  gemm     : 33.78 us
input: [56, 4096] | weight: [65536, 4096]
  gemm@sp24: 240.86 us
  gemm     : 351.88 us
input: [8, 11008] | weight: [4096, 11008]
  gemm@sp24: 157.03 us
  gemm     : 67.24 us
input: [8, 4096] | weight: [12288, 4096]
  gemm@sp24: 68.94 us
  gemm     : 73.67 us
input: [8, 4096] | weight: [22016, 4096]
  gemm@sp24: 83.75 us
  gemm     : 124.03 us
input: [8, 4096] | weight: [4096, 4096]
  gemm@sp24: 66.38 us
  gemm     : 32.23 us
Total time:
  sp24 : 13848us
  dense: 11594us
CuSparseLt v0.5.0 | alg_id: 1
input: [56, 11008] | weight: [4096, 11008]
  gemm@sp24: 75.05 us
  gemm     : 73.8 us
input: [56, 4096] | weight: [12288, 4096]
  gemm@sp24: 50.53 us
  gemm     : 76.34 us
input: [56, 4096] | weight: [22016, 4096]
  gemm@sp24: 80.25 us
  gemm     : 127.66 us
input: [56, 4096] | weight: [4096, 4096]
  gemm@sp24: 32.6 us
  gemm     : 31.03 us
input: [56, 4096] | weight: [65536, 4096]
  gemm@sp24: 220.39 us
  gemm     : 351.28 us
input: [8, 11008] | weight: [4096, 11008]
  gemm@sp24: 78.95 us
  gemm     : 66.2 us
input: [8, 4096] | weight: [12288, 4096]
  gemm@sp24: 47.97 us
  gemm     : 74.33 us
input: [8, 4096] | weight: [22016, 4096]
  gemm@sp24: 76.47 us
  gemm     : 123.22 us
input: [8, 4096] | weight: [4096, 4096]
  gemm@sp24: 33.46 us
  gemm     : 32.25 us
Total time:
  sp24 : 8878us
  dense: 11524us
CuSparseLt v0.5.0 | alg_id: 2
input: [56, 11008] | weight: [4096, 11008]
  gemm@sp24: 151.94 us
  gemm     : 73.13 us
input: [56, 4096] | weight: [12288, 4096]
  gemm@sp24: 66.97 us
  gemm     : 77.27 us
input: [56, 4096] | weight: [22016, 4096]
  gemm@sp24: 83.26 us
  gemm     : 127.09 us
input: [56, 4096] | weight: [4096, 4096]
  gemm@sp24: 65.51 us
  gemm     : 32.5 us
input: [56, 4096] | weight: [65536, 4096]
  gemm@sp24: 238.25 us
  gemm     : 351.15 us
input: [8, 11008] | weight: [4096, 11008]
  gemm@sp24: 154.36 us
  gemm     : 66.91 us
input: [8, 4096] | weight: [12288, 4096]
  gemm@sp24: 67.6 us
  gemm     : 73.87 us
input: [8, 4096] | weight: [22016, 4096]
  gemm@sp24: 80.01 us
  gemm     : 123.83 us
input: [8, 4096] | weight: [4096, 4096]
  gemm@sp24: 65.64 us
  gemm     : 31.91 us
Total time:
  sp24 : 13607us
  dense: 11562us
CuSparseLt v0.5.0 | alg_id: 3
input: [56, 11008] | weight: [4096, 11008]
  gemm@sp24: 112.22 us
  gemm     : 73.72 us
input: [56, 4096] | weight: [12288, 4096]
  gemm@sp24: 58.01 us
  gemm     : 76.66 us
input: [56, 4096] | weight: [22016, 4096]
  gemm@sp24: 85.91 us
  gemm     : 127.74 us
input: [56, 4096] | weight: [4096, 4096]
  gemm@sp24: 44.3 us
  gemm     : 31.89 us
input: [56, 4096] | weight: [65536, 4096]
  gemm@sp24: 245.79 us
  gemm     : 351.2 us
input: [8, 11008] | weight: [4096, 11008]
  gemm@sp24: 112.99 us
  gemm     : 66.6 us
input: [8, 4096] | weight: [12288, 4096]
  gemm@sp24: 54.91 us
  gemm     : 74.37 us
input: [8, 4096] | weight: [22016, 4096]
  gemm@sp24: 84.61 us
  gemm     : 123.4 us
input: [8, 4096] | weight: [4096, 4096]
  gemm@sp24: 43.83 us
  gemm     : 31.9 us
Total time:
  sp24 : 11143us
  dense: 11562us
 ```

**Review by cpuhrsch — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change, but the Window build failure looks legit https://hud.pytorch.org/pytorch/pytorch/commit/1e5636f7915035b09dce22ad1d2170a65f344214' -c ignoredsignal

The failure wasn't captured correctly and the build wrongly returned successfully.  Here are the linker errrors:

```
2023-12-11T16:46:18.4688306Z RegisterCUDA.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) class at::Tensor __cdecl at::native::_cslt_sparse_mm(class at::Tensor const &,class at::Tensor const &,class std::optional<class at::Tensor> const &,class std::optional<class at::Tensor> const &,class std::optional<enum c10::ScalarType>,bool,__int64)" (__imp_?_cslt_sparse_mm@native@at@@YA?AVTensor@2@AEBV32@0AEBV?$optional@VTensor@at@@@std@@1V?$optional@W4ScalarType@c10@@@5@_N_J@Z) referenced in function "class at::Tensor __cdecl at::A0x0848dee0::`anonymous namespace'::wrapper_CUDA___cslt_sparse_mm(class at::Tensor const &,class at::Tensor const &,class std::optional<class at::Tensor> const &,class std::optional<class at::Tensor> const &,class std::optional<enum c10::ScalarType>,bool,__int64)" (?wrapper_CUDA___cslt_sparse_mm@?A0x0848dee0@1at@@YA?AVTensor@2@AEBV32@0AEBV?$optional@VTensor@at@@@std@@1V?$optional@W4ScalarType@c10@@@5@_N_J@Z)
2023-12-11T16:46:18.4697583Z RegisterCUDA.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) __int64 __cdecl at::native::_cslt_sparse_mm_search(class at::Tensor const &,class at::Tensor const &,class std::optional<class at::Tensor> const &,class std::optional<class at::Tensor> const &,class std::optional<enum c10::ScalarType>,bool)" (__imp_?_cslt_sparse_mm_search@native@at@@YA_JAEBVTensor@2@0AEBV?$optional@VTensor@at@@@std@@1V?$optional@W4ScalarType@c10@@@5@_N@Z) referenced in function "__int64 __cdecl at::A0x0848dee0::`anonymous namespace'::wrapper_CUDA___cslt_sparse_mm_search(class at::Tensor const &,class at::Tensor const &,class std::optional<class at::Tensor> const &,class std::optional<class at::Tensor> const &,class std::optional<enum c10::ScalarType>,bool)" (?wrapper_CUDA___cslt_sparse_mm_search@?A0x0848dee0@1at@@YA_JAEBVTensor@2@0AEBV?$optional@VTensor@at@@@std@@1V?$optional@W4ScalarType@c10@@@5@_N@Z)
```

Let me take a look at the Windows build script to see why it didn't fail the build there.

**Comment by jcaip** [comment]
Looks like this was caused by me using `long` instead of `int64_t` in the C++ function signatures. Should be working now.

**Pull request closed without merging**
