### PR TITLE
Simplify the conditionals used for learning rate calculation for `ConstantLR` learning rate scheduler

### PR DESCRIPTION
**Pull request by ancestor-mithril**

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
> revert -m "causing macos errors as per https://hud.pytorch.org/pytorch/pytorch/commit/83283b4f0dc2032a31f9a80c7aa40e3e552ec944"

This PR is logically no-op.
The error on one the link is out of memory and looks like some infra issue.

**Pull request closed without merging**
