### PR TITLE
Make zeros argument of torch.where same dtype as other argument

### PR DESCRIPTION
**Pull request by nairbv**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #30662 Added check for torch.where on CPU that both arguments have same dtype
* **#30661 Make zeros argument of torch.where same dtype as other argument**

Cherry-picked from https://github.com/pytorch/pytorch/pull/29080

Co-authored-by: ifedan

Differential Revision: [D18781870](https://our.internmc.facebook.com/intern/diff/D18781870)

### CODE REVIEW

**Review by zou3519 — COMMENTED** [review]
Is it possible to add a test for this?

**Comment by nairbv** [comment]
> Is it possible to add a test for this?

I'm just cherry-picking two already approved PRs for commits from 1.3.1 that aren't yet on master (nor 1.4). I want to prioritize getting things consistent.

**Comment by zou3519** [comment]
> > Is it possible to add a test for this?
> 
> I'm just cherry-picking two already approved PRs for commits from 1.3.1 that aren't yet on master (nor 1.4). I want to prioritize getting things consistent.

I just looked at #29080 -- it looks like we could just rebase and land that stack instead of opening new PRs, but sure

**Review by zou3519 — APPROVED** [review]

**Comment by nairbv** [comment]
>  it looks like we could just rebase and land that stack instead of opening new PRs, but sure

I tried naively tried a ghstack checkout, rebase, and ghstack of the existing PRs but it couldn't find the /gh/ branches because they're under ifedan. If if you know of some option to make that work let me know for next time.

**Comment by zou3519** [comment]
> > it looks like we could just rebase and land that stack instead of opening new PRs, but sure
> 
> I tried naively tried a ghstack checkout, rebase, and ghstack of the existing PRs but it couldn't find the /gh/ branches because they're under ifedan. If if you know of some option to make that work let me know for next time.

It's possible to commandeer the diffs (internally), rebase, and then ship them.

**Comment by gchanan** [comment]
I think you just have to remove the ghstack metadata from the original commit to restack it.

**Review by gchanan — APPROVED** [review]

**Pull request closed without merging**
