### PR TITLE
add BFloat16 support for BatchNorm2d on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #69067
* #73953
* #73845
* #73844
* #71376
* __->__ #61015
* #58297

Differential Revision: [D30476323](https://our.internmc.facebook.com/intern/diff/D30476323)

### CODE REVIEW

**Comment by mingfeima** [comment]
TODO: add perf data and test cases.

**Comment by mingfeima** [comment]
TODO: add mix precision support for weight and bias, aka. input/output(bf16) + weight/bias(fp32).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30476323).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30476323).

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by mingfeima** [comment]
TODO: update the mixed dtype logic.

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30476323).

**Pull request closed without merging**
