### PR TITLE
[PyTorch] Don't store multiple kernels per key on mobile

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #64447

As the code comment says, we needn't worry about Jupyter notebooks on mobile.

Differential Revision: [D30736094](https://our.internmc.facebook.com/intern/diff/D30736094/)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
aye aye matey

**Review by bhosmer — APPROVED** [review]
AFAIK the multiple-kernel capability was always a forward-looking bit of engineering and isn't in use. Should we consider removing it and letting the whole setup collapse into something simpler?

**Comment by swolchok** [comment]
> isn't in use

isn't it intended to make Jupyter notebooks work correctly?

**Comment by bhosmer** [comment]
> > isn't in use
> 
> isn't it intended to make Jupyter notebooks work correctly?

IIUC it only comes into play if you're interactively loading libraries that step on each other's kernels, and then unloading them in LIFO order. I think the original idea was that the dispatcher state would work properly like a stack in that case - unloading library B would uncover library A's kernels. But I don't know that this behavior manifests usefully in Jupyter today - I don't believe the typical workflow needs it at all, and I don't know if the intended workflow is possible without additional functionality that doesn't yet exist. cc @smessmer if he's willing to drop in and give some historical background 😁

**Comment by smessmer** [comment]
Historical background for jupyter: when you re-execute a jupyter cell, pytorch sees it as a new additional dynamic library being loaded and the previous version of the cell isn't unloaded. If that cell contains a custom op, then you want the new cell to overwrite the previous cell.

If I remember correctly, then for jupyter it would be enough to just overwrite the kernel and delete the old one, but probably makes sense to double check.

**Pull request closed without merging**
