### PR TITLE
Limit number of cores to 16 when benchmarking Inductor on ARM

### PR DESCRIPTION
**Pull request by cfRod**
Sets OMP_NUM_THREADS to 16

cc @malfet @snadampal @milpuz01

### CODE REVIEW

**Review by desertfire — CHANGES_REQUESTED** [review]
Let's separate the freezing change into another PR. If you look at the CUDA result, freezing is evaluated as a separate row, e.g. https://hud.pytorch.org/benchmark/compilers?dashboard=torchinductor&startTime=Tue%2C%2017%20Sep%202024%2012%3A54%3A25%20GMT&stopTime=Tue%2C%2024%20Sep%202024%2012%3A54%3A25%20GMT&granularity=hour&suite=torchbench&mode=inference&dtype=bfloat16&deviceName=cuda%20(a100)&lBranch=main&lCommit=75f141be627fbc010676de76b83def1fc13f357c&rBranch=main&rCommit=e248c1d7ebe437094d42d6cad0acf5ffd0a27cad

**Comment by cfRod** [comment]
> Let's separate the freezing change into another PR. If you look at the CUDA result, freezing is evaluated as a separate row, e.g. https://hud.pytorch.org/benchmark/compilers?dashboard=torchinductor&startTime=Tue%2C%2017%20Sep%202024%2012%3A54%3A25%20GMT&stopTime=Tue%2C%2024%20Sep%202024%2012%3A54%3A25%20GMT&granularity=hour&suite=torchbench&mode=inference&dtype=bfloat16&deviceName=cuda%20(a100)&lBranch=main&lCommit=75f141be627fbc010676de76b83def1fc13f357c&rBranch=main&rCommit=e248c1d7ebe437094d42d6cad0acf5ffd0a27cad

Sure thanks I can do that. Can we have a mode that uses both inductor freezing flag + CPP wrapper? That is how we test downstream at the moment and we would like to replicate that upstream whilst.

**Review by malfet — APPROVED** [review]
Sure, though if you would have created a PR in the PyTorch repo, we could have scheduled the benchmark to see the results right away

**Comment by cfRod** [comment]
> Sure, though if you would have created a PR in the PyTorch repo, we could have scheduled the benchmark to see the results right away

I did create one to launch the dashboard https://github.com/pytorch/pytorch/actions/runs/11030187025

My branch is update_perf_ci_aarch64
https://hud.pytorch.org/benchmark/compilers?dashboard=torchinductor&startTime=Thu%2C%2022%20Aug%202024%2017%3A10%3A11%20GMT&stopTime=Thu%2C%2029%20Aug%202024%2017%3A10%3A11%20GMT&granularity=hour&suite=torchbench&mode=inference&dtype=bfloat16&deviceName=cpu%20(aarch64)&lBranch=main&lCommit=d01a7a9faa5a742a3df7374b97bbc1db1205b6ed&rBranch=main&rCommit=64cfcbd8a318535560b8fc908a0948af8e177329
However, it is comparing the numbers with benchmarks running at 64 threads versus running them at 16 threads (+ freezing flag)

**Pull request closed without merging**
