### PR TITLE
Use `@pytorch//` in bazel build files

### PR DESCRIPTION
**Pull request by vors**
This change aims to make bazel build more embeeding-friendly.
Namely, when PyTorch is included as an external repo in another project, it is usually included like this
```
        native.local_repository(
            name = "pytorch",
            path = ...,
            repo_mapping = repo_mapping,
        )
```
Or
```
        http_archive(
            name = "pytorch",
            urls = ...
            repo_mapping = repo_mapping,
        )
```
In this case, references to `@//` would resolve to the top-level WORKSPACE that includes PyTorch.
That makes upgrades harder because we need to carry around this patch.
Note that under some edge-case circumstances even `//` resolves to the top-level `WORKSPACE`.

This change makes the embedding of the bazel build easier without compromising anything for the main repo, since the `@pytorch//` still refers to the same thing.

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen

### CODE REVIEW

**Comment by vors** [comment]
I didn't add the `cc` -- seems like some automation?

**Comment by kit1980** [comment]
@vors Could you check that the email on your commits matches the email on EasyCLA?

**Comment by vors** [comment]
@kit1980 thank you! I plan to do more contributions as part of my work at Cruise, as well as help my teammates to do the same. Since PyTorch now part of Linux Foundation it seems like CLA also changed? Let me spend a little bit of time sorting out CLA with our legal team.

**Comment by kit1980** [comment]
@vors besides signing the CLA, there is a technical CLA-check related detail: email on the commit (as seen by git) must be listed in your GitHub account, this seems to be not the case currently.

**Comment by vors** [comment]
Oh I see, let me fix it :)

**Comment by vors** [comment]
Ok I worked with our legal, we signed CLA and I'm now CLA manager for Cruise.

This should be ready to merge from the legal point on view :)

@kit1980 can you help with the code review?

**Comment by sanchitintel** [comment]
> @vors besides signing the CLA, there is a technical CLA-check related detail: email on the commit (as seen by git) must be listed in your GitHub account, this seems to be not the case currently.

@vors, this still seems to be an issue

**Comment by vors** [comment]
Gentle ping on this one, can we start getting a review?

**Review by kit1980 — APPROVED** [review]

**Comment by vors** [comment]
Seems unrelated...

**Comment by vors** [comment]
@kit1980 🙇

**Comment by dagitses** [comment]
What are the edge cases under which // resolves to the top-level workspace?

**Comment by vors** [comment]
There are 3 flavors:
- `//...`
- `@//...`
- `@pytorch//...`

From our expirience in Cruise, only the last one provides an unambiguous stable resolution.
The `//...` one always resolves to the top namespace which is not what we want.

**Pull request closed without merging**
