### PR TITLE
Have median reduce over all dims and return just the value if dim is not provided

### PR DESCRIPTION
**Pull request by lantiga**
Solves #1692.

### CODE REVIEW

**Review by apaszke — COMMENTED** [review]
The changes look good but are a bit incomplete. To properly support distributed master-worker you also need to add `medianall` as part of the `Function` enum, register the handler in `master_worker/worker/Dispatch.cpp` and add an RPC stub in `master_worker/master/generic/THDTensor.*` (both in header and the C file).

**Comment by lantiga** [comment]
Thank you @apaszke, admittedly I didn't delve deep enough in distributed. Your pointers are a great start, I'll complete the PR asap.

**Review by apaszke — COMMENTED** [review]
Looks good now! Do you plan to add a THC implementation? For now it can just do:
1. view as a flat vector
2. sort
3. memcpy the scalar

**Comment by lantiga** [comment]
Sure thing

**Comment by lantiga** [comment]
Sorry @apaszke , I could only get to this today.

I'm using `thrust::stable_sort`, but `operator<` is not defined for `f16`. I tried to introduce it with
```
__host__ __device__ inline bool operator<(const half &lhs, const half &rhs) 
{
   return __hlt(lhs, rhs);
}
```
but compilation fails complaining that `__hlt` is not defined (while it's documented).
I can eventually use a CUDA_HALF_TENSOR guard, but do you have any hints for making the above work? Thanks in advance

**Comment by lantiga** [comment]
Probably the answer is: use `THCTensor_(sort)` after viewing it as a 1D tensor. I just wanted to avoid generating indices, as `sort` currently does. We just need the value for medianall.

**Comment by apaszke** [comment]
You can use `THCNumerics`

**Comment by lantiga** [comment]
Doh!

**Comment by lantiga** [comment]
With the last commit I added both median and medianall to THC. In the end I used `_(sort)` for both.

@apaszke where should I move the two functions in terms of location?
Right now they're in `THCTensorMathReduce` just because they're next to `min` and `max`, but that doesn't make a lot of sense. I'd say either `THCTensorMath` or `THCTensorMathCompare`?

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
after this is rebased, this is good to go.

**Comment by lantiga** [comment]
@soumith rebased

**Comment by soumith** [comment]
this is now merged into master. Thanks a lot Luca!

**Pull request closed without merging**
