### PR TITLE
enable exporting bidirectional rnn with fixed seq len from onnx to caffe2

### PR DESCRIPTION
**Pull request by anderspapitto**

### CODE REVIEW

**Comment by anderspapitto** [comment]
test unlocked in https://github.com/onnxbot/onnx-fb-universe/pull/1561

**Review by houseroad — COMMENTED** [review]
LGTM, could you also add cases/new *_opts with sequence_lens input in test_caffe2.py to get this case covered?

**Comment by anderspapitto** [comment]
@houseroad what do you mean by 'cases/new *_opts' ?

**Comment by houseroad** [comment]
https://github.com/onnxbot/onnx-fb-universe/blob/master/test/test_caffe2.py#L703

Looks like the we haven't covered this case, right?

**Comment by houseroad** [comment]
https://github.com/onnxbot/onnx-fb-universe/pull/1561

**Review by houseroad — APPROVED** [review]
Never mind, I saw those

**Pull request merged**
