### PR TITLE
map_nested_tensor

### PR DESCRIPTION
**Pull request by cpuhrsch**
### Description
Example implementation of a slow utility function to make it easier to gain coverage.

### Issue
There's been various user requests for coverage (e.g. conv2d).

### Testing
This is a refactor. Existing tests apply.

### CODE REVIEW

**Review by jbschlosser — COMMENTED** [review]
`map_nested_tensor` looks fine, but do we want to replace the `softmax` and `bmm` implementations? They definitely look nicer using `map_nested_tensor`, but isn't it less efficient to do a mapping followed by a cat compared to directly writing to a pre-allocated output buffer?

Is the idea that those two kernels will be replaced by speedier kernels anyway?

**Comment by cpuhrsch** [comment]
@jbschlosser - It's possible to preallocate the output and also use `map_nested_tensor` by passing the output as an argument to the function.

Also the efficiency of `map_nested_tensor` can be increased by directly using offsets, sizes and strides to index into the constituents instead of unbind.

It can be updated to yield code that's just as performant as what we currently have for bmm, softmax. Having said that, it won't ever be able to replace efficient, optimized kernels.

**Comment by jbschlosser** [comment]
> It can be updated to yield code that's just as performant as what we currently have for bmm, softmax. Having said that, it won't ever be able to replace efficient, optimized kernels.

Right, that makes sense. I think it'd be nice to have the baseline performance with `map_nested_tensor()` be as good as is feasible since getting efficient, optimized kernels in is a lot of work.

> Also the efficiency of `map_nested_tensor` can be increased by directly using offsets, sizes and strides to index into the constituents instead of unbind.

This is nice - easy to do in this PR?

**Review by jbschlosser — APPROVED** [review]
Stamping to get this in - can update for efficiency later (low-pri)

**Pull request closed without merging**
