### PR TITLE
[optim] use lerp whenever possible

### PR DESCRIPTION
**Pull request by janeyx99**
This is a better copy (with fixes) of #104781.

Test plan:
CI will pass once https://github.com/pytorch/pytorch/pull/104784 is landed 

Internal CI (and the newly enabled compiled optim tests) will pass after https://github.com/pytorch/pytorch/pull/104866 is landed.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104796

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Sonuds good

**Comment by DanilBaibak** [comment]
@janeyx99 sorry, I have to revert your PR. It leads to internal failures. Here you can find more details - [D47321721](https://www.internalfb.com/diff/D47321721).

**Comment by imoneoi** [comment]
Hi @janeyx99, I'm also implementing AdamW, can I ask a question about this PR? Why not also use `lerp` for `exp_avg_sq` in https://github.com/pytorch/pytorch/blob/main/torch/optim/adamw.py#L420? Is it because of numerical stability or performance issues?

**Comment by janeyx99** [comment]
@imoneoi The reason to use lerp was to not dispatch as many kernels (2 from an add and mul). For exp_avg_sq, in order to use lerp, we would have to calculate grad^2 first, which ends up being 2 kernels anyway and would require an intermediate of grad^2 to take up memory vs being able to inplace.

**Pull request closed without merging**
