### PR TITLE
Add Pytorch Dafaflow Interface diagram for Wiki

### PR DESCRIPTION
**Pull request by mike9ant**
Summary: Add Dataflow Interface diagram png to caffe2/docs, so that it can be accessed from Wiki.

Differential Revision: D14014017

### CODE REVIEW

**Comment by vadimkantorov** [comment]
@soumith a proposal: removing *.pth, *.tar from the diagram ([pth is a special file extension for python related to handling module search paths](https://github.com/pytorch/pytorch/issues/14864), it would be nice to migrate everything to e.g. `*.pt`) if this is png, probably later would be more difficult to edit them out.

**Comment by ezyang** [comment]
I expressed to @mike7ant in chat that it's better if we don't commit png files to GitHub unless we absolutely must, because they are a permanent tax on repo size. (cc @apaszke who has also said similar things in the past.) I'm not sure we have a good replacement for wiki, however.

**Comment by vadimkantorov** [comment]
@ezyang Maybe an SVG? A quick google search suggests it might be supported in GitHub Markdown, but needs to be tested

**Comment by apaszke** [comment]
Can't we host the images elsewhere and link to that from the wiki? We have S3 buckets and I think FB might have a few servers :)

**Comment by soumith** [comment]
no longer relevant, as we can host it on the wiki itself

**Pull request closed without merging**
