### PR TITLE
change asan test shard to 3

### LINKED ISSUE #68261: CI: Further shard ASAN tests
Following some discussion about time to signal (TTS), ASAN tests are some of the longest CI jobs in PyTorch. Thus, to cut down overall time-to-signal for any pull request, we should focus on cutting down our ASAN test time.

One way to do this is to further shard the ASAN tests. This can be done by changing the num_test_shards variable here https://github.com/pytorch/pytorch/blob/master/.github/scripts/generate_ci_workflows.py#L417.

Currently, the asan tests are split into two jobs and they each take around 2hr4min each. You can try experimenting with 3 shards or 4 shards and document any time improvements. 

One thing to note is that there is currently no "smart" sharding enabled for ASAN as I ran into trouble enabling it, so it will distribute the tests round robin style. If you'd like to try enabling the "smart" sharding based on previous test stats, you can try adding this line to the bottom of https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/build-asan.sh.
```
  # export test times so that potential sharded tests that'll branch off this build will use consistent data
  python test/run_test.py --export-past-test-times
```

cc @seemethere @malfet @pytorch/pytorch-dev-infra

### PR DESCRIPTION
**Pull request by xidachen**
Fixes #68261

This PR changes the number of test shard from 2-->3 for all Asan test, aiming to improve the run time for Asan tests.

### CODE REVIEW

**Comment by xidachen** [comment]
linux-xenial-py3.6-clang7-asan / test (default, 1, 2, linux.2xlarge): 2h 45m 54s
linux-xenial-py3.6-clang7-asan / test (default, 2, 2, linux.2xlarge): 1h 51m 37s

Does that mean we still shard by 2?

**Comment by xidachen** [comment]
@janeyx99 I think I know what's going on, I forgot to run .github/scripts/generate_ci_workflows.py after my change.

I got the following error even if I ran in the above py file on master branch:
Traceback (most recent call last):
  File "/Users/xidachen/pytorch/.github/scripts/generate_ci_workflows.py", line 771, in <module>
    main()
  File "/Users/xidachen/pytorch/.github/scripts/generate_ci_workflows.py", line 743, in main
    (jinja_env.get_template("linux_ci_workflow.yml.j2"), LINUX_WORKFLOWS),
  File "/Users/xidachen/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/xidachen/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/xidachen/opt/anaconda3/lib/python3.9/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/Users/xidachen/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/xidachen/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/xidachen/opt/anaconda3/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/xidachen/pytorch/.github/templates/linux_ci_workflow.yml.j2", line 51, in template
    {% block build +%}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '+

Any thoughts?

**Comment by janeyx99** [comment]
@xidachen You are exactly right! The workflow files needed regeneration. I was able to generate the workflow files just fine with the script, though. Do you have the right version of jinja? Make sure to install jinja2--I have version 3.01

**Comment by seemethere** [comment]
Are we sure this'll do what we expect? Increasing the shard numbers sounds good in theory but are we expecting there to be a change in `.jenkins/pytorch/test.sh` as well?

**Comment by janeyx99** [comment]
> Are we sure this'll do what we expect? Increasing the shard numbers sounds good in theory but are we expecting there to be a change in `.jenkins/pytorch/test.sh` as well?

Right, good catch!--I thought David had merged his refactoring changes to make this more scalable, but it turns out parts of his PR https://github.com/pytorch/pytorch/pull/63641 were not merged. @xidachen Feel free to derive the test.sh changes from this PR--I think specifically this addition https://github.com/pytorch/pytorch/pull/63641/files#diff-4521b160c3140a7941c706ebde596f19bbb38aeec52baddac5dbf195f3aa2e67R519-R521

**Comment by xidachen** [comment]
@janeyx99 Could you take a look at the failures? Seems unrelated to this change?

**Comment by janeyx99** [comment]
@xidachen, yea both those errors were from upstream trunk, so you don't have to worry about those. It looks at if the ASAN tests didn't become too much shorter though :/

**Comment by xidachen** [comment]
Here are the time for shard = 3:
1h 57m 24s, 1h 3m 25s, 52m 0s

And the time for shard = 4:
2h 19m 45s, 45m 30s, 37m 27s, 34m 42s

Do you think we need smart sharding to make it more balanced?

**Comment by janeyx99** [comment]
Smart sharding should help, but my attempt to do so runs into issues that I'm not sure how to fix: https://hud.pytorch.org/pr/pytorch/pytorch/69787 (ci signal page for my PR)

It seems like the first shard is always the largest--maybe something is off there

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
