### PR TITLE
[graphmode] insert_observers use qconfig_dict

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #25370 [refactor] Remove unnecessary checks in InsertQuantDeQuantImpl
* #25281 [quant][graphmode] Skip inserting observers for Tensors inside fused op
* #25217 [quant][graphmode] Integration tests for qconfig_dict
* #25127 [quant][graphmode] insert_quant_dequant work with qconfig_dict
* **#25069 [graphmode] insert_observers use qconfig_dict**

Summary:
This PR changes the API of insert_observers to use qconfig_dict,
full functionality support will come in later PRs

Test Plan:
```
python test/test_quantizer.py
python test/test_jit.py
```
Reviewers:
pt1quant
Subscribers:

Tasks:

Tags:

Differential Revision: [D17001135](https://our.internmc.facebook.com/intern/diff/D17001135)

### CODE REVIEW

**Review by ZolotukhinM — CHANGES_REQUESTED** [review]
Overall looks nice, but some places might benefit from some refactoring. Without it it's difficult to review the logic, so I'll wait for you to address that before approving.

**Review by ZolotukhinM — APPROVED** [review]
Looks good, but please run clang-format before landing.

**Comment by jerryzh168** [comment]
test failure is fixed in next PR

**Comment by jerryzh168** [comment]
> Looks good, but please run clang-format before landing.

planning to run clang-format in one PR after the stack lands

**Comment by ZolotukhinM** [comment]
> test failure is fixed in next PR

Mm, that's bad, if the tests are failing, we shouldn't land. If `fbcode/warm` falls on this revision after it's landed, several people will hit breakages for no reason. Please pull the fix into this PR.

**Comment by jerryzh168** [comment]
> > test failure is fixed in next PR
> 
> Mm, that's bad, if the tests are failing, we shouldn't land. If `fbcode/warm` falls on this revision after it's landed, several people will hit breakages for no reason. Please pull the fix into this PR.

I think the fix is actually just the next PR :), I'll land the stack directly

**Comment by ZolotukhinM** [comment]
> > > test failure is fixed in next PR
> > 
> > 
> > Mm, that's bad, if the tests are failing, we shouldn't land. If `fbcode/warm` falls on this revision after it's landed, several people will hit breakages for no reason. Please pull the fix into this PR.
> 
> I think the fix is actually just the next PR :), I'll land the stack directly

There will still be a broken commit in git. If someone starts working of that commit, they'll have to deal with the breakages. Committing broken stuff is a bad practice, please don't do it.

**Comment by jerryzh168** [comment]
sure, I can turn off the test and turn it back on in next pr

**Pull request closed without merging**
