### PR TITLE
Disable strict-overflow flag to avoid compilation error

### PR DESCRIPTION
**Pull request by gujinghui**
Disable strict-overflow flag to avoid compilation error

### CODE REVIEW

**Comment by gujinghui** [comment]
@yinghai  @soumith 
Please help review

**Review by soumith — APPROVED** [review]

**Comment by toby5box** [comment]
Wouldn't it be better to fix the warnings, not ignore them?

**Comment by gujinghui** [comment]
> Wouldn't it be better to fix the warnings, not ignore them?

Tried. But we cannot reproduce the warning in local env.
So, have to disable it.

**Comment by gujinghui** [comment]
@yinghai 

pls help review

**Comment by yinghai** [comment]
Could you check the test failures first?

**Comment by gujinghui** [comment]
@yinghai 
these two failures are caused by network issue.
failed to download topology.
should be not related to this PR.

> Dec 10 07:05:16 Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /var/lib/jenkins/.torch/models/resnet18-5c106cde.pth
Dec 10 07:05:16 ERROR
Dec 10 07:05:17 test_check_onnx_broadcast (__main__.TestONNXUtils) ... ok
Dec 10 07:05:17 test_prepare_onnx_paddings (__main__.TestONNXUtils) ... ok
Dec 10 07:05:17 
Dec 10 07:05:17 ======================================================================
Dec 10 07:05:17 ERROR: setUpClass (__main__.TestHub)
Dec 10 07:05:17 ----------------------------------------------------------------------
Dec 10 07:05:17 Traceback (most recent call last):
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
Dec 10 07:05:17     (self._dns_host, self.port), self.timeout, **extra_kw)
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
Dec 10 07:05:17     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/socket.py", line 745, in getaddrinfo
Dec 10 07:05:17     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Dec 10 07:05:17 socket.gaierror: [Errno -3] Temporary failure in name resolution
Dec 10 07:05:17 
Dec 10 07:05:17 During handling of the above exception, another exception occurred:
Dec 10 07:05:17 
Dec 10 07:05:17 Traceback (most recent call last):
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
Dec 10 07:05:17     chunked=chunked)
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
Dec 10 07:05:17     self._validate_conn(conn)
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
Dec 10 07:05:17     conn.connect()
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
Dec 10 07:05:17     conn = self._new_conn()
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
Dec 10 07:05:17     self, "Failed to establish a new connection: %s" % e)
Dec 10 07:05:17 urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fd19c030828>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
Dec 10 07:05:17 
Dec 10 07:05:17 During handling of the above exception, another exception occurred:
Dec 10 07:05:17 
Dec 10 07:05:17 Traceback (most recent call last):
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
Dec 10 07:05:17     timeout=timeout
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
Dec 10 07:05:17     _stacktrace=sys.exc_info()[2])
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
Dec 10 07:05:17     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Dec 10 07:05:17 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Max retries exceeded with url: /models/resnet18-5c106cde.pth (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd19c030828>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Dec 10 07:05:17 
Dec 10 07:05:17 During handling of the above exception, another exception occurred:
Dec 10 07:05:17 
Dec 10 07:05:17 Traceback (most recent call last):
Dec 10 07:05:17   File "test_utils.py", line 492, in setUpClass
Dec 10 07:05:17     cls.resnet18_pretrained = models.__dict__['resnet18'](pretrained=True).state_dict()
Dec 10 07:05:17   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torchvision/models/resnet.py", line 175, in resnet18
Dec 10 07:05:17     model.load_state_dict(model_zoo.load_url(model_urls['resnet18']))
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 66, in load_url
Dec 10 07:05:17     _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 72, in _download_url_to_file
Dec 10 07:05:17     u = urlopen(url, stream=True)
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/requests/api.py", line 72, in get
Dec 10 07:05:17     return request('get', url, params=params, **kwargs)
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/requests/api.py", line 58, in request
Dec 10 07:05:17     return session.request(method=method, url=url, **kwargs)
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
Dec 10 07:05:17     resp = self.send(prep, **send_kwargs)
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
Dec 10 07:05:17     r = adapter.send(request, **kwargs)
Dec 10 07:05:17   File "/opt/conda/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
Dec 10 07:05:17     raise ConnectionError(e, request=request)
Dec 10 07:05:17 requests.exceptions.ConnectionError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Max retries exceeded with url: /models/resnet18-5c106cde.pth (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd19c030828>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Dec 10 07:05:17 
D

**Comment by toby5box** [comment]
> > Wouldn't it be better to fix the warnings, not ignore them?
> 
> Tried. But we cannot reproduce the warning in local env.
> So, have to disable it.

There are configurations which produce these warnings and a failed compile every time. The details are in other github issues.

If you cannot repro the warnings then you should not attempt to resolve the issue; by disabling them you've increased the risk of missing a real issue elsewhere.

**Comment by Jianhui-Li** [comment]
This specific warning mostly complains the optimization GCC itself did assuming certain numeric condition hold (like constant folding x+1+1 == x+2 is not TRUE if there is overflow).   Fixing this means to write code which doesn't trigger GCC optimization.

**Comment by toby5box** [comment]
I'm not persuaded disabling warnings is the right fix. Did you try simply rearranging the equations in the asserts? (No, because the issue wasn't even reproduced...)

Also it's interesting that this issue, although it has inspired a patch to disable an entire class of warnings, doesn't even quote the actual warnings involved.

**Comment by gujinghui** [comment]
Confirmed again. There is a miscommunication. The issue was reproduced.  We decided not to fix but  understand that it is ideal to remove all GCC warning.

**Pull request closed without merging**
