### PR TITLE
Dynamically find min log scale

### LINKED ISSUE #3195: PyTorch throws an exception on import when denormals are flushed to zero
This happens, for example, when you import DyNet before importing PyTorch. The code from #3113 tries to take the log(0) which throws an exception.

My guess is that DyNet is setting FTZ or DAZ (or both). See:
https://software.intel.com/en-us/node/523328

### PR DESCRIPTION
**Pull request by ssnl**
Fixes #3195 . Blame #3113 .

Hardcoding -323 won't work since FTZ/DAZ will make `pow(10, -323)` zero, causing division by zero error again.

cc @colesbury

### CODE REVIEW

**Review by colesbury — APPROVED** [review]
lgtm

**Review by apaszke — APPROVED** [review]

**Review by apaszke — COMMENTED** [review]
It would be slightly nicer to compute it only once, but printing is not a perf critical code

**Comment by SsnL** [comment]
I agree with @apaszke . But weird things can happen between importing pytorch and printing, e.g. DyNet changing DAZ/FTZ. So this is probably the best we can do.

**Comment by apaszke** [comment]
Good point

**Comment by SsnL** [comment]
Updated with a slightly more efficient version where the threshold is only computed at each `numbe_format` call.

**Review by apaszke — APPROVED** [review]

**Pull request merged**
