### PR TITLE
[Security] Use github environment for update-commit-hash workflow

### PR DESCRIPTION
**Pull request by atalman**
Similar to: https://github.com/pytorch/pytorch/pull/101718

https://github.com/pytorch/pytorch/actions/runs/5856611801/job/15876722301

Please note since we can't specify environment for a composite workflow. It was needed to move update-commit-hash as action rather then workflow.

Still todo: Move docs and binary builds

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Review by malfet — CHANGES_REQUESTED** [review]
Sorry, I should have read it more carefully: I don't think one can specify the environment for a composite workflow, only for the top level one

**Comment by atalman** [comment]
> Sorry, I should have read it more carefully: I don't think one can specify the environment for a composite workflow, only for the top level one

No Issues I will rewrite _update-commit-hash.yml as reusable action this way it should work with top level workflow similar to this example:
```
jobs:
  publish:
    environment: CI    # <--- /!\ Here is the link to the environment
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v2
    # Some more steps here ...
    - name: Publish to Test PyPI
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        TWINE_REPOSITORY_URL: "https://test.pypi.org/legacy/"
      run: |
        echo KEY: '${TWINE_PASSWORD}'
        twine check dist/*
        twine upload --verbose --skip-existing dist/*
```

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
