### PR TITLE
Fix the missing caffe2 proto files for Windows

### LINKED ISSUE #15156: Windows 1.0.0 binaries fail import caffe2
## 🐛 Bug

Reported by @m3rlin45

```
from caffe2.python import workspace
```

```
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from caffe2.python import workspace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\m3rlin45\Documents\foo\env\lib\site-packages\caffe2\python\__init__.py", line 2, in <module>
    from caffe2.proto import caffe2_pb2
ImportError: cannot import name 'caffe2_pb2'
```

## To Reproduce

Repro on a VM:

- Spin up fresh windows server 2016 VM on azure
- install python 3.6.7 from python.org
- disable path limit during install
- install virtualenv
- install vs15 redist to help virtualenv work
- set up a virtualenv and activated it
- install torch via instructions on pytorch.org, windows, python 3.6, no cuda
- open python
- run: `from caffe2.python import workspace`

### PR DESCRIPTION
**Pull request by peterjc123**
Fixes #15156

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by peterjc123** [comment]
@soumith I think we'll need some more changes like PATH configuration to make caffe2.python on Windows.

**Comment by soumith** [comment]
I'll wait for you to tell me it's good to merge

**Review by soumith — DISMISSED** [review]
making sure it's not merged

**Review by orionr — APPROVED** [review]

**Comment by zdevito** [comment]
While it shouldn't block this PR, the fact that this functionality has absolutely no testing in the CI needs to be addressed. Untested functionality, especially on Windows where not a lot of people have manual testing setups, makes it nearly impossible to improve build times and other issues.

**Comment by orionr** [comment]
Good point @zdevito. IMO this should be addressed when we start running Caffe2 tests on the PyTorch CI. There is work in progress for Linux, but as usual Windows is more difficult. I'll add it to a tracking doc so we don't lose it, though.

**Pull request closed without merging**
