### PR TITLE
Rename DataPipe to Op-er

### PR DESCRIPTION
**Pull request by ejguan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#63325 Rename DataPipe to Op-er**

Rename each DataPipe to an operation name ending with er. Functional API should remain `verb` such as `read_from_tar` , `shuffle`, ... (Discussed in [here](https://github.com/facebookexternal/torchdata/pull/97#discussion_r688553905))
- Batch -> Batcher
- Collate -> Collator
- Concat -> Concater
- GroupByKey - > ByKeyGrouper ?
- ListDirFiles -> FileLister
- LoadFilesFromDisk -> FileLoader
- Map -> Mapper
- ReadFilesFromTar -> TarArchiveReader
- ReadFilesFromZip -> ZipArchiveReader
- ReadLinesFromFile -> LineReader
- Shuffle -> Shuffler
- ToBytes -> StreamReader
- Transforms -> Transformer
- Zip -> Zipper

Let me know if you have better name for each DataPipe

Differential Revision: [D30466950](https://our.internmc.facebook.com/intern/diff/D30466950)

### CODE REVIEW

**Review by VitalyFedyunin — APPROVED** [review]
nit: Maybe small DataPipes naming guide wiki page?

**Comment by ejguan** [comment]
Will land this PR after wrapper up the hackathon with torchtext to prevent blocking development.

**Comment by vadimkantorov** [comment]
"Transformer" name risks to have confusion and googlability problems because of popular transformer architecture

**Comment by ejguan** [comment]
@vadimkantorov 

> "Transformer" name risks to have confusion and googlability problems because of popular transformer architecture

Thanks for providing feedback. It definitely makes sense to me. Do you have any suggestion on the name? Maybe `TransformMapper`?

And, IMO, this DataPipe should be removed at the end since we do have `MapperDataPipe` to support callable function that also applies for the vision transforms.

**Comment by VitalyFedyunin** [comment]
> @vadimkantorov
> 
> > "Transformer" name risks to have confusion and googlability problems because of popular transformer architecture
> 
> Thanks for providing feedback. It definitely makes sense to me. Do you have any suggestion on the name? Maybe `TransformMapper`?
> 
> And, IMO, this DataPipe should be removed at the end since we do have `MapperDataPipe` to support callable function that also applies for the vision transforms.

Feel free to kill Transformer DataPipe, even domains teams not using it =)

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30466950).

**Pull request closed without merging**
