### PR TITLE
Fix docstring inconsistencies: string -> str, boolean -> bool

### PR DESCRIPTION
**Pull request by ProGamerGov**
### Description

Throughout the PyTorch docs and codebase, the `string` type in docstrings is referred to by two separate names. This leads to inconsistent docs, like you can see here: https://pytorch.org/docs/stable/generated/torch.nn.Conv3d.html#torch.nn.Conv3d

This PR fixes this issue by ensuring that all mentions of the string type in docstrings, are using the same format that Sphinx generates hyperlinks for.

### Testing
No testing should be required for this change

### CODE REVIEW

**Review by jbschlosser — COMMENTED** [review]
LGTM if we can get the CI checks passing! Thanks for the update :)

**Comment by ProGamerGov** [comment]
@jbschlosser Do you want me to fix the accidental usage of capitalized list and tuple in the docstrings as well in this PR?

**Comment by ProGamerGov** [comment]
@jbschlosser I found another similar inconsistency with `bool` and `boolean`, so I hope you don't mind that I included it in this PR as well

**Review by jbschlosser — APPROVED** [review]
LGTM! Thanks :)

**Pull request closed without merging**
