### PR TITLE
Jinja2 version pinned to 3.0.*

### LINKED ISSUE #74684: test linux-docs / build-docs (python) is broken
### 🐛 Describe the bug

CI test linux-docs / build-docs (python)  is currently broken:

```
Traceback (most recent call last):
  File "/opt/conda/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/opt/conda/lib/python3.7/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/opt/conda/lib/python3.7/site-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/opt/conda/lib/python3.7/site-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/opt/conda/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/opt/conda/lib/python3.7/site-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/opt/conda/lib/python3.7/site-packages/jinja2/__init__.py)
```

failure: https://github.com/pytorch/pytorch/runs/5678126229?check_suite_focus=true#step:7:1152

### Versions

master

### PR DESCRIPTION
**Pull request by b0noI**
Fixes #74684

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by adamjstewart** [comment]
Instead of hacking `requirements.txt` to continue to support an obsolete version of Sphinx with known issues (#60979), why not use modern Sphinx (#70309)?

**Comment by malfet** [comment]
> Instead of hacking `requirements.txt` to continue to support an obsolete version of Sphinx with known issues (#60979), why not use modern Sphinx (#70309)?

If you can keep `no_grad` option in place, I'm more than ready to move to new version of sphinx

**Pull request closed without merging**
