### PR TITLE
Increase ROCm test shards to 6

### PR DESCRIPTION
**Pull request by jithunnair-amd**
To reduce signal time

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM! I guess this is good as long as there are enough capacity :)

**Review by malfet — APPROVED** [review]

**Comment by pruthvistony** [comment]
Holding on the merge currently since ROCm CI is in unstable now.

**Pull request closed without merging**
