### PR TITLE
unified GlooStore and c10d store API (#55719)

### PR DESCRIPTION
**Pull request by msaroufim**
Summary: Pull Request resolved: https://github.com/pytorch/pytorch/pull/55719

Test Plan: Imported from OSS

Differential Revision: D27785267

Pulled By: msaroufim

### CODE REVIEW

**Comment by msaroufim** [comment]
Kicked off a rebase in phabricator

**Review by rohan-varma — COMMENTED** [review]
Great, overall looks good to me! Will stamp it once the CI clears

**Review by rohan-varma — APPROVED** [review]
CI looks good, let's land this!

**Comment by msaroufim** [comment]
Looks like I"m not authorized to merge this pull request, I'm guessing only file owners can merge?

**Comment by rohan-varma** [comment]
@msaroufim The usual process is actually to land the internal diff, and then it automatically syncs up with github.

**Pull request closed without merging**
