### PR TITLE
Fixing Pytorch RMS norm implementation

### PR DESCRIPTION
**Pull request by kkontny**
Since FP16 has quite small dynamic range it is very easy to overflow while computing `at::pow(input, 2)` , and it happens in real world computation.

I've tried to use `nn.RMSNorm` fused implementation instead of `LlamaRMSNorm` inside `transformers` implementation of Llama (`src/transformers/models/llama/modeling_llama.py`). It started to give wrong answers in Fp16 while still giving good in FP32. I figured out happens due to overflow while computing square of the input tensor.

Original `LLamaRMSNorm` implementation upcasts input to fp32 to prevent this and give better numerical stability.

```
class LlamaRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-6):
        """
        LlamaRMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states):
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)
```

Proposed commit fixed the issue. FP16 in RMSNorm has to be treated in special way, to be usable in real world implementations.

### CODE REVIEW

**Review by mikaylagawarecki — COMMENTED** [review]
Could you sign CLA in https://github.com/pytorch/pytorch/pull/133085#issuecomment-2277598428 please

**Comment by kkontny** [comment]
> Could you sign CLA in [#133085 (comment)](https://github.com/pytorch/pytorch/pull/133085#issuecomment-2277598428) please

I have to process the CLA through the company legal. Unfortunately it will be probably done early next week.

**Comment by mayank31398** [comment]
@kkontny would you mind if I open this PR again instead?
Its blocking me as well, want to get it in as soon as possible

**Comment by kkontny** [comment]
> @kkontny would you mind if I open this PR again instead? Its blocking me as well, want to get it in as soon as possible

@mayank31398 Please go on, I tried to hurry them, but with no effect. It takes much more time than it should...

**Comment by mayank31398** [comment]
@kkontny I think we can close this.
this has been fixed now in https://github.com/pytorch/pytorch/pull/134106

**Comment by kkontny** [comment]
Fixed via #134106

**Pull request closed without merging**
