### PR TITLE
[ONNX][v1.4.0] Cherry-pick Add ONNX Export Support to floor_divide

### PR DESCRIPTION
**Pull request by BowenBao**
Original commit: https://github.com/pytorch/pytorch/commit/79c27ba4ef609c56907c504e15737fbaf8cc8f87
Original PR: https://github.com/pytorch/pytorch/pull/31081
This is needed to unblock onnx export for torchvision models.

### CODE REVIEW

**Review by lara-hdr — APPROVED** [review]

**Comment by eellison** [comment]
@BowenBao what's the motivation here? `floor_divide` isn't included in the 1.4 release.

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit d89a1e8:
* **2/2** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=d89a1e88851ccda70876a120b0f98cce6d00a382).

### :detective: 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/3992864) pytorch_linux_xenial_py3_6_gcc5_4_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=76218401) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=76218401))
<details>
<summary>
<code>Automatic merge failed; fix conflicts and then commit the result.</code>
</summary>

```
CONFLICT (add/add): Merge conflict in .circleci/docker/common/install_cache.sh 
Auto-merging .circleci/docker/common/install_cache.sh 
CONFLICT (add/add): Merge conflict in .circleci/docker/common/install_android.sh 
Auto-merging .circleci/docker/common/install_android.sh 
CONFLICT (add/add): Merge conflict in .circleci/docker/build.sh 
Auto-merging .circleci/docker/build.sh 
CONFLICT (add/add): Merge conflict in .circleci/config.yml 
Auto-merging .circleci/config.yml 
CONFLICT (add/add): Merge conflict in .circleci/cimodel/data/binary_build_definitions.py 
Auto-merging .circleci/cimodel/data/binary_build_definitions.py 
Automatic merge failed; fix conflicts and then commit the result. 
```

</details>

### 1 failure *not* recognized by patterns:
| Job | Step | Status |
| --- | --- | --- |
| CircleCI <sup>pytorch_xla_linux_xenial_py3_6_clang7_build</sup> | <sup>Build</sup> | New in PR |


---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by houseroad** [comment]
More context: the use case of floor_divide in torch vision is introduced in https://github.com/pytorch/vision/pull/1658

**Comment by eellison** [comment]
> More context: the use case of floor_divide in torch vision is introduced in [pytorch/vision#1658](https://github.com/pytorch/vision/pull/1658)

that hasn't been landed, and it won't be landed for the new release. nor was pytorch use of `floor_divide` landed for the new release

**Comment by BowenBao** [comment]
Thanks @eellison 
Closing the PR. Turns out this is not required for 1.4 since floor_divide itself is not included.

**Pull request closed without merging**
