### PR TITLE
add deepcopy support to subclasses

### PR DESCRIPTION
**Pull request by albanD**
Happy to get any feedback on how to make this code cleaner!

This:
- Fix Tensor attribute deepcopy BC-breaking?
- Add a test for Tensor attribute deepcopy
- Fix subclass deepcopy
- Moves the subclass serialization tests into their own class not to interfere with other serialization test logic
- Add a test for subclass deepcopy

cc @ezyang @gchanan

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
This seems fine. Deepcopy on `__dict__` is technically BC-breaking and we'll need to see if it breaks anything.

**Comment by albanD** [comment]
Actually while looking at the serialization code, it does not copy the `__dict__` for plain Tensors.
I think we want both serialization and deepcopy to be consistent here no?

Maybe I should revert the change to plain Tensor `__dict__`? WDYT?

**Comment by ezyang** [comment]
> Actually while looking at the serialization code, it does not copy the __dict__ for plain Tensors.

What do you mean by this?

> Maybe I should revert the change to plain Tensor __dict__? WDYT?

This is certainly less risky, although in the long term it would be good for Tensor and subclasses of Tensor to behave consistently. E.g., I could imagine in the long term serializing Tensor should also serialize `__dict__` and we just need to make sure that this gets ignored by older versions of PyTorch which don't understand it.

**Comment by albanD** [comment]
> What do you mean by this?

```python
import torch

a = torch.rand(2)
a.foo = 3

torch.save(a, "bar")
b = torch.load("bar")
print(hasattr(b, "foo"))
```
Will return
```
False
```

So after this PR serialization and deepcopy won't be consistent anymore.

But I agree that this should be considered a bug of serialization: https://github.com/pytorch/pytorch/issues/65694

**Comment by ezyang** [comment]
can you make an announce post about this

**Pull request closed without merging**
