### PR TITLE
expose torch_python_obj as a static library

### PR DESCRIPTION
**Pull request by PaliC**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #76569

This pr exposes torch_python_static in lib such that we are able to access the object from external projects like pytorch/multipy

Differential Revision: [D36270099](https://our.internmc.facebook.com/intern/diff/D36270099)

### CODE REVIEW

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36270099).

**Review by d4l3k — APPROVED** [review]
LGTM -- there's some build/lint failures that need to be fixed before landing

Might need to hide that install behind a USE_DEPLOY feature flag or something?

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36270099).

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36270099).

**Pull request closed without merging**
