### PR TITLE
Add Conv2dLocal module

### PR DESCRIPTION
**Pull request by 1zb**
Addresses #499 

I don't know how to make the generated function `SpatialConvolutionLocal` to accept `None` argument. So this module must have a bias term.

### CODE REVIEW

**Comment by 1zb** [comment]
Seems we need to mark arguments with `[OPTIONAL]` in `THNN.h` and `THCUNN.h`.

**Comment by apaszke** [comment]
Yes, if you mark arguments with `[OPTIONAL]`, then they will accept `None` in Python too

**Comment by Gwan-Siu** [comment]
Hi, I download your Conv2dLocal modules and run it.
There is a bug:

torch.FloatTensor constructor received an invalid combination of arguments - got (float, float, int, int, int, int), but expected one of:
 * no arguments
 * (int ...)
      didn't match because some of the arguments have invalid types: (!float!, !float!, !int!, !int!, !int!, !int!)
 * (torch.FloatTensor viewed_tensor)
 * (torch.Size size)
 * (torch.FloatStorage data)
 * (Sequence data)

What's the problems?

**Comment by 1zb** [comment]
@Gwan-Siu

Can you give the full code to reproduce the error?

This module works for me.

```python
a = nn.Conv2dLocal(in_channels=256, out_channels=256, in_height=8, in_width=8, kernel_size=3, stride=1, padding=0) 
input = Variable(torch.randn(1, 256, 8, 8)) 
output = a(input)
```

**Comment by Gwan-Siu** [comment]
OK.

I just simple check:

```
a = nn.Conv2dLocal(in_width=8, in_height=8, in_channels=256, out_channels=256, kernel_size=3)
Traceback (most recent call last):

  File "<ipython-input-3-e1224e69fb35>", line 1, in <module>
    a = nn.Conv2dLocal(in_width=8, in_height=8, in_channels=256, out_channels=256, kernel_size=3)

  File "/home/gwan-siu/anaconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 642, in __init__
    out_channels, in_channels, *self.kernel_size))

TypeError: torch.FloatTensor constructor received an invalid combination of arguments - got (float, float, int, int, int, int), but expected one of:
 * no arguments
 * (int ...)
      didn't match because some of the arguments have invalid types: (!float!, !float!, !int!, !int!, !int!, !int!)
 * (torch.FloatTensor viewed_tensor)
 * (torch.Size size)
 * (torch.FloatStorage data)
 * (Sequence data)
```

The code in line 642 is:
```

self.weight = Parameter(torch.Tensor(
            self.out_height, self.out_width,
            out_channels, in_channels, *self.kernel_size))
```

**Comment by Gwan-Siu** [comment]
I check it, may be the problem is ` *self.kernel_size`

**Comment by 1zb** [comment]
Fixed. It should work now.

**Comment by Gwan-Siu** [comment]
OK, let me try.

**Comment by Gwan-Siu** [comment]
Yes, It works. Many thanks. wow~~~
How do you learn to modify the source code. I would like to learn the method, so that I can modify by myself for any operators that I need. That's so cool~~

**Comment by yenicelik** [comment]
So from what I've seen this module is not featured in the documentation; Also, I cannot access it when running `local1 = Conv2dLocal(8, 16, 64, 64)`. So how do I use this, do I have to download a 'nightly' build or is this included already?

**Comment by 1zb** [comment]
@yenicelik 
I can't say for sure when will this PR be merged into master. But you can create a separate python environment with `conda` and install my forked version.

[These lines](https://github.com/1zb/pytorch/blob/27c8cf4bb44b2f4414177ece22f2c8c6dffe720c/torch/nn/modules/conv.py#L658-L659) may help you use Conv2dLocal.

**Comment by zxytim** [comment]
When will it be merged into master?

**Comment by apaszke** [comment]
Looks good to me, but I think it should be renamed to ConvUntied2d. There's nothing more local in this convolution than in regular Conv2d

**Comment by Gwan-Siu** [comment]
could you add a more parameter to control shared weighted size? for
example, shared weight size 4x4, so that weights are shared in this 4x4
region.

2017-07-26 21:24 GMT+08:00 Adam Paszke <notifications@github.com>:

**Comment by Gwan-Siu** [comment]
I think it will be more general for local convolution.

2017-07-26 21:27 GMT+08:00 Jun Xiao <alexjun134@gmail.com>:

**Comment by soumith** [comment]
I dont think it's realistic to add a neighborhood option in this PR. What you ask needs quite a bit of rewrite of the C/CUDA kernels.

**Comment by 1zb** [comment]
I can't get these auto-generated functions to work in latest version (0.2.0+8262920).

The code from #499 will give the error:
`
/home/biao/miniconda2/envs/pth/lib/python3.6/site-packages/torch/nn/_functions/thnn/auto.py in forward(ctx, input, *params)
    152                 args += (None,)
    153             else:
--> 154                 raise ValueError("missing required argument '%s'" % param.name)
    155 
    156         args += tuple(additional_args)

ValueError: missing required argument 'bias'
`

Any suggesstions?

**Comment by halochou** [comment]
@1zb Not sure, but maybe like this (?)
```
import torch
from torch.autograd import Variable

inputs=Variable(torch.randn(1,3,32,32)) # N x inC x inH x inW
weight=Variable(torch.randn(30,30,64,3,3,3)) # outH x outW x outC x inC x kH x kW
bias=Variable(torch.randn(64,30,30)) # outC x outH x outW

local = torch.nn.backends.thnn.backend.SpatialConvolutionLocal.apply
## arguments: input, weight, bias, kH, kW, strideH, strideW, padH, padW, inH, inW, outH, outW
output = local(inputs, weight, bias, 3, 3, 1, 1, 0, 0, 32, 32, 30, 30)
```

**Comment by ywu36** [comment]
Any track on this issue? I can duplicate the error mentioned above.

Believe a quick fix can solve it. Any core developer online?

**Comment by 1zb** [comment]
Auto-generated `SpatialConvolutionLocal` of new style seems not working anymore. It invokes `_updateOutput` in the following way:
```python
SpatialConvolutionLocal_updateOutput(
            state,
            inputs,
            output,
            finput, # <-- 
            fgradInput, # <-- buffer before weight and bias
            weight,
            bias,
            kW, kH,
            dW, dH,
            padW, padH,
            iW, iH,
            oW, oH
        )
```


But the correct declaration is
```python
SpatialConvolutionLocal_updateOutput(
            state,
            inputs,
            output,
            weight, # <-- 
            bias, # <-- weight and bias before buffer
            finput,
            fgradInput,
            kW, kH,
            dW, dH,
            padW, padH,
            iW, iH,
            oW, oH
        )
```

**Comment by 1zb** [comment]
I implemented `Conv2dLocal` with `Im2Col`. And it supports `bias=False` and `dilation=x`. Could you check if it is ready?

**Comment by ywu36** [comment]
I confirm the new pull request is compatible with the current version of Pytorch. The forward and backward works smoothly.

**Comment by crazynwo12** [comment]
Where should this be downloaded?
Conv2dLocal I can not run.

**Comment by guillefix** [comment]
Yeah, this doesn't seem to be available in the current version. As a temporal workaround, I put 1zb's version on a python file, from which you can import `Conv2dLocal`. I tested it and it works.

Here it is: https://gist.github.com/guillefix/23bff068bdc457649b81027942873ce5

**Comment by bwesen** [comment]
A cheer from me too for merging this into pyTorch. It's really useful for experiments and that is what pyTorch is famous for, right? :)

Btw the "local" in Conv2DLocal makes sense in some weird way, as what you're doing is not a full all-to-all weightmap from input to output but rather each output node gets input from a local region.

However you could argue that it's actually not a convolution anymore.

**Comment by bwesen** [comment]
I tested the Im2Col version and it works, and it has an OK batch speedup. I didn't test the non-functional way of using it though. I think you should merge this (there is no other sane way of doing non-shared kernel convolutions currently otherwise).

**Comment by Kyonio** [comment]
I build your code from source(conv-layer branch), but I run into GPU memory leak when add Conv2dLocal layer in network. (During training process and loading batch iterations)  a possible related issue: [#3394](https://github.com/pytorch/pytorch/issues/3394) Do you have some ideas? @1zb

**Comment by bwesen** [comment]
I've tested this as well a bit more, and while functionally the unfold solution works fine, it requires gigantonormous intermediary tensors as unfold has to expand the input tensor into a form that can be directly element-wise multiplied with the weights, and if the input tensor is batched, the intermediaries often don't fit in the GPU even if you have 10 GB of VRAM.

For example, I tried a relatively small 128x128 input with a 13x13 kernel, this requires a weight tensor of 128x128x13x13 which is around 10 MBytes. But as soon as you start batching (which is required for speed), even for a very small batch of 32 this is 0.3 GB, and the unfold solution requires more than one such intermediary.

I'm not saying the proposed solution shouldn't be merged as it's much better than nothing, but it would be super awesome if there could be a more native solution that doesn't require the scratchpad RAM. The operation itself is local so this is theoretically possible at least. I'd be happy to contribute it but I'm a rookie at pyTorch and there seems to be so many different interacting backends that I'm not sure where to actually put such an implementation.

By the way, this is not in cuDNN, but it would be interesting to know if Nvidia has an implementation in the works.

**Comment by Kyonio** [comment]
Yeah, I know that the kernels will be very large cause it don't share weights.. But the problem is that the memory usage keeps increasing when loading batches, that's strange. I think the memory usage should keep at a constant value when training.

**Comment by ddrise** [comment]
Why still not pass review?

**Comment by Blusea** [comment]
```python
import torch,torch.nn as nn,torch.nn.functional as F
from copy import deepcopy
class LocalLinear(nn.Module):
    def __init__(self,in_features,local_features,kernel_size,stride=1,bias=True):
        super(LocalLinear, self).__init__()
        self.kernel_size = kernel_size
        self.stride = stride

        fold_num = (in_features-self.kernel_size)//self.stride+1
        self.lc = nn.ModuleList([deepcopy(nn.Linear(kernel_size,local_features,bias=bias))
                                 for _ in range(fold_num)])

    def forward(self, x:torch.Tensor):
        x = x.unfold(-1,size=self.kernel_size,step=self.stride)
        fold_num = x.shape[1]
        x= torch.cat([self.lc[i](x[:,i,:]) for i in range(fold_num)],1)
        return x

```

**Comment by Blusea** [comment]
```python
import torch,torch.nn as nn,torch.nn.functional as F
from copy import deepcopy
class LocalLinear(nn.Module):
    def __init__(self,in_features,local_features,kernel_size,stride=1,bias=True):
        super(LocalLinear, self).__init__()
        self.kernel_size = kernel_size
        self.stride = stride

        fold_num = (in_features-self.kernel_size)//self.stride+1
        self.lc = nn.ModuleList([deepcopy(nn.Linear(kernel_size,local_features,bias=bias))
                                 for _ in range(fold_num)])

    def forward(self, x:torch.Tensor):
        x = x.unfold(-1,size=self.kernel_size,step=self.stride)
        fold_num = x.shape[1]
        x= torch.cat([self.lc[i](x[:,i,:]) for i in range(fold_num)],1)
        return x

```

**Comment by ParadoxRobotics** [comment]
> ```python
> import torch,torch.nn as nn,torch.nn.functional as F
> from copy import deepcopy
> class LocalLinear(nn.Module):
>     def __init__(self,in_features,local_features,kernel_size,stride=1,bias=True):
>         super(LocalLinear, self).__init__()
>         self.kernel_size = kernel_size
>         self.stride = stride
> 
>         fold_num = (in_features-self.kernel_size)//self.stride+1
>         self.lc = nn.ModuleList([deepcopy(nn.Linear(kernel_size,local_features,bias=bias))
>                                  for _ in range(fold_num)])
> 
>     def forward(self, x:torch.Tensor):
>         x = x.unfold(-1,size=self.kernel_size,step=self.stride)
>         fold_num = x.shape[1]
>         x= torch.cat([self.lc[i](x[:,i,:]) for i in range(fold_num)],1)
>         return x
> ```

Does it work with image or only vector ?

**Comment by covix** [comment]
In the `forward` function in the code snippet provided by @sheljoy, the `fold_num` variable shouldn't be calculated as `x.shape[2]` after the unfolding operation?
When keeping `x.shape[1]` I cannot stack `LocalLinear` layers.

**Comment by yw5aj** [comment]
Any updates on 2023?

**Pull request closed without merging**
