### PR TITLE
Add cache timings info to tlparse

### PR DESCRIPTION
**Pull request by oulgen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #133722
* __->__ #133504

https://interncache-all.fbcdn.net/manifold/tlparse_reports/tree/logs/.tmpLR1T85/rank_1/0_0_0/fx_graph_cache_hash_11.json

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

Differential Revision: [D61422432](https://our.internmc.facebook.com/intern/diff/D61422432)

### CODE REVIEW

**Review by jamesjwu — APPROVED** [review]
Can you add the example tlparse links to the summary? 

Also does time_saved_ns make sense to add to AOTAutogradCache's cache stats too? We're saving a bit more than just compiled_graph._time_taken_ns, but it might be hard to measure.

**Comment by jamesjwu** [comment]
(Nvm we can add AOTAutogradCache calculations later)

**Comment by oulgen** [comment]
@oulgen has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61422432).

**Pull request closed without merging**
