### PR TITLE
[OpInfo][take2] move matmul to OpInfo 

### PR DESCRIPTION
**Pull request by walterddr**
This is a reland of #55543 after fixing bfloat16 issues.

### CODE REVIEW

**Comment by walterddr** [comment]
FYI: @imaginary-person @mruberry @anjali411

**Comment by mruberry** [comment]
What's going on with ci-all/?

**Review by mruberry — APPROVED** [review]
Cool! 

What's going on with all the failing ci-all builds? The failures don't seem related to this PR.

**Comment by imaginary-person** [comment]
> What's going on with ci-all/?

Adding the `ci/all` label results in these many CI checks being run. The label isn't necessary in this case. 
But I wonder why a label with such a name exists, since using a `ci-all/` branch alone apparently leads to a different number of CI checks being run.

**Comment by walterddr** [comment]
`ci/all` label and the `ci-all` branch are actually treated differently based on my experience. and I think only ppl with write access can push to `ci-all` branch. 

@mruberry Those failures seems to be instantly triggered (cancelled) when `ci/all` tags were added. not sure if this is a desired behavior

**Comment by mruberry** [comment]
> `ci/all` label and the `ci-all` branch are actually treated differently based on my experience. and I think only ppl with write access can push to `ci-all` branch.
> 
> @mruberry Those failures seems to be instantly triggered (cancelled) when `ci/all` tags were added. not sure if this is a desired behavior. Filed an internal ticket for investigation

Thanks @walterddr. @anjali411 had a good idea that we should probably update our contribution guide and the developer faq in the wiki for how to use ci-all and/or ci/all and what they do.

**Comment by walterddr** [comment]
sounds good I will get on it

**Comment by walterddr** [comment]
validate in #56088 --> ci/all seems to be something we shouldn't use. and no external contributor can use it anyway. will update internal wiki instead

**Pull request closed without merging**
