### PR TITLE
[JIT] alias analysis speedup

### PR DESCRIPTION
**Pull request by eellison**
1. Lazily build write cache instead of eagerly in `setWildcard`. EDIT: this caused failures, not sure why. taking it out of this PR.

2. Optional & TupleType is the only container type that can contain a refined tensor type in the runtime. We don't need to recursively unshape type any other type but Optional and Tensor in alias analysis. This recursion was shown to add non-trivial overhead in first pass of FairSeq mode (~12%).

### CODE REVIEW

**Comment by eellison** [comment]
Actually turns out quantization breaks this invariant :'(

**Review by Krovatkin — APPROVED** [review]
:shipit: looks gut, why don't we want to move that assert into dict and list constructors and turn it into TORCH_CHECK? Constructing new types vs copying probably happens way less frequent than running AA?

**Comment by eellison** [comment]
@krovatkin actually there's a few places that construct refined `lists / dicts / classes` :'( It might be a good amount of work to remove them & ensure that it isn't introduced again in the future. 

I'm going to try to make this faster by caching the TypePtr -> Mutable Type Ptr instead.

**Comment by eellison** [comment]
Closing in favor of https://github.com/pytorch/pytorch/pull/35437, also the lazily build write cache thing caused errors.

**Pull request closed without merging**
