### PR TITLE
[BE] Add script to keept the runner-determinator scripts in sync

### PR DESCRIPTION
**Pull request by ZainRizvi**
Whenever we update runner_determinator.py it needs to be copied over into _runner-determinator.yml.

This is a quick utility script to make that process less tedious

### CODE REVIEW

**Review by zxiiro — APPROVED** [review]
Nice!

Edit: Looks like we need to fix a lint issue.

**Comment by jeanschmidt** [comment]
NEAT, but we need to get the lint right :)

**Review by jeanschmidt — APPROVED** [review]

**Pull request closed without merging**
