### PR TITLE
[ROCm] Fix test_trace_rule_update.py

### PR DESCRIPTION
**Pull request by petrex**
-Add missing torch API to trace rules and ignore API with manual trace rule.

The PR fix test/dynamo/test_trace_rule_update

maybe related to https://github.com/pytorch/pytorch/pull/121142

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
This seems fine, but looks like CI is failing

**Comment by petrex** [comment]
@jansel the failing tests seems irrelevant to the change here.

see https://github.com/pytorch/pytorch/issues/121708

**Review by jansel — APPROVED** [review]

**Comment by jeffdaily** [comment]
Let's try one more rebase to see if we can get a clean CI signal.  Note no ROCm failures observed.

**Comment by petrex** [comment]
@jeffdaily 
irrelevant failure in CI:
`
Error: Could not assume role with user credentials: User: arn:aws:sts::308535385114:assumed-role/gh-ci-github-action-runners-runner-role/i-0e37c63bcdf5fc9e8 is not authorized to perform: sts:TagSession on resource: arn:aws:iam::391835788720:role/gha-pytorch-ci-artifacts-role`

**Review by pruthvistony — APPROVED** [review]
LGTM, CI failure not related.

**Pull request closed without merging**
