### PR TITLE
Rename getType to getVariableTypeFromBaseType / getVariableType

### PR DESCRIPTION
**Pull request by ezyang**
Rename getType to getVariableTypeFromBaseType / getVariableType

We used getType to mean a lot of things.

- getVariableTypeFromBaseType: given a base Type (non-Variable type)
  compute the Variable Type which corresponds to it.

- getVariableType: like at::getType, but return the Variable type
  rather than the plain type.

This rename makes it clearer at the use-site what things are what,
and will make a subsequent rename of at::getType easier.

Differential Revision: D9583630

Stacked on #11087

### CODE REVIEW

**Comment by cpuhrsch** [comment]
In combination with 11078 and 11077 it looks like we're getting a lot of getXYZType functions. Is there a single source of documentation for this? I'd be confused about which one to use in what circumstance.

**Comment by ezyang** [comment]
Sure, we can get docs on the functions. Note that these are internal functions and not intended to be used externally.

**Review by cpuhrsch — APPROVED** [review]
Ok

**Review by gchanan — APPROVED** [review]
This looks good, although I guess I'm not convinced that it's not better to just have a single getType function (scalar type, device type, is_variable) for all of these things.

**Comment by ezyang** [comment]
I'm going to defer the docs for a later commit so I can keep this stack landing.

**Pull request closed without merging**
