### PR TITLE
Prevent __torch_function__ running a second time in AOTAutograd

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #121468
* #121445
* __->__ #121375
* #121373

If you have a tensor subclass that relies on dispatch into the same op without unwrapping and calling torch._C.DisableTorchFunctionSubclass() the torch function-ness will survive into AOTAutograd (when normally we may expect the torch function to be inlined away during dynamo). If this happens, we should make sure to not run the torch function logic a second time.

Fixes https://github.com/pytorch/pytorch/issues/120654, https://github.com/pytorch/pytorch/issues/120124

cc @bdhirsh 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by soulitzer** [comment]
The failure looks legit, investigating.

**Comment by soulitzer** [comment]
The issue is that we aren't actually inlining torch function in dynamo today! We can fix that by:
- `torch._dynamo.config.traceable_tensor_subclasses.add(NestedTensor)`
- Adding `torch.nested` to `MOD_INLINELIST`

The above is easy to do, but because we haven't been inlining, there are some graph breaks that need to be addressed.

**Comment by jbschlosser** [comment]
> The issue is that we aren't actually inlining torch function in dynamo today! (Instead we are relying on the torch function to run sometime during aot autograd, and that is now broken by this PR).

This certainly explains the symptom we were seeing during AOTAutograd. Perhaps we should clean up the terminology a bit; we have:
* "Traceable wrapper subclasses" - used throughout Dynamo / AOTAutograd; torch_dispatch subclasses that are decomposable into inner tensors. These are defined by implementing the `__tensor_flatten__()` / `__tensor_unflatten__()` APIs appropriately.
* "Traceable tensor subclasses" - separate set of `__torch_function__()` subclasses that Dynamo may or may not trace into. These are defined by membership within the `traceable_tensor_subclasses` set.

**Comment by soulitzer** [comment]
In order to avoid having any temporary state where the behavior of anything is regressed. I'm closing this in PR in favor of a combo PR https://github.com/pytorch/pytorch/pull/121445 that does all of the following at once:
1. disables torch function running a second time in AOTAutograd
2. enables torch function to be inlined in dynamo for NT
3. fixes graph breaks for NT torch function

**Pull request closed without merging**
