### PR TITLE
Remove EXPERIMENTAL_ENUM_SUPPORT feature guard

### LINKED ISSUE #41095: Support Enum in TorchScript
Enum is widely used in Python but not yet supported in TorchScript. Opening this issue to track effort of adding Enum support.

cc @suo @gmagogsfm

### PR DESCRIPTION
**Pull request by gmagogsfm**
Fixes #41095

### CODE REVIEW

**Review by eellison — APPROVED** [review]

**Comment by eellison** [comment]
@gmagogsfm could you try to land this ?

**Comment by gmagogsfm** [comment]
> @gmagogsfm could you try to land this ?

I am still investigating #43577. I am afraid that landing this PR now would introduce a memory issue. Do you have a use case that need this PR now?

**Comment by SplitInfinity** [comment]
I do, @yf225 needs this with medium priority.

**Comment by gmagogsfm** [comment]
Landing now as the investigation shows that dangling issue turns out to be orthogonal.

**Pull request closed without merging**
