### PR TITLE
fix building errors on FreeBSD

### PR DESCRIPTION
**Pull request by cyyever**
Although FreeBSD is not officially supported, this PR fixes some errors on FreeBSD.

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
> revert -m "causing regressions on internal models" -c "ghfirst"

How?

**Comment by cyyever** [comment]
@kit1980 
_torch_assert conflicts with some internal macros?

**Comment by kit1980** [comment]
> @kit1980 _torch_assert conflicts with some internal macros? I can change it to c10 assertion functions

I'm looking at the internal runs and I don't think this PR actually caused the issue.
Need more investigation though.

**Comment by PaliC** [comment]
@cyyever Sorry for being vague about the error, but all it really shows is that the tests are failing. We'll try to give you some more information. For now try using the c10 conflicts to see if it resolves things.

**Comment by cyyever** [comment]
@PaliC Can you test commit e054993224c1f37354e9196f9d9300385a657f49 ?

**Comment by PaliC** [comment]
@cyyever Sorry, I'm horrible at checking github notifications. Feel free to message me on slack if I'm unresponsive. Will test this out now!

**Pull request closed without merging**
