### PR TITLE
Add script to summarize performance from CI performance run

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #97977

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by wconstab — APPROVED** [review]
looks correct to me, but i thought you were going to compare current to baseline.

**Comment by ezyang** [comment]
@wconstab I guess someone else can add that if they want :)

**Pull request closed without merging**
