### PR TITLE
Implement python API for AdaBelief optimizer

### LINKED ISSUE #47571: Add Adabelief optimizer to the C++ API
## 🚀 Feature
Add Adabelief optimizer to the C++ API

## Motivation
I have been using this new optimizer recently with the Python API and found out it worked extremely well (for my use cases at least). I also find the paper and theory behind it pretty neat. I would be ready to work on it (although with no guarantee since this would be done on my free time) if you consider this is worth adding to the API.

Thank you for reading this far. Cheers. :)

Link to the paper: https://arxiv.org/abs/2010.07468

cc @albanD @mruberry @jbschlosser @vincentqb @yf225 @glaringlee

### PR DESCRIPTION
**Pull request by juntang-zhuang**
Fixes #47571 for Python API of AdaBelief optimizer, modified from the official pip implementation.

Implements the AdaBelief optimizer

Implements the _multi_tensor version with the same API as PyTorch 1.8

Fixes the error that amsgrad does not take effect when rectify is set as True

Adds AdaBelief to docs

Adds AdaBelief to test/test_optim.py (tests passed)

### CODE REVIEW

**Comment by glaringlee** [comment]
@juntang-zhuang 
Hi, I am on vocation this week, have limit web access, I will try to take a look at this. If I can not review this within this week, I will do the review 1st thing on next Monday.
In the meantime, please fix several things. 
1. lint error. We use flake8 to check python lint error, please read the CI error message and fix the lint error, here is the direct error link:
https://github.com/pytorch/pytorch/pull/49864/checks?check_run_id=1610529400
2. mypy error, We use mypy to check the syntax error in the python code, please fix the mypy error:
error link (one of them, I think all CI mypy errors are the same):
https://app.circleci.com/pipelines/github/pytorch/pytorch/255193/workflows/4db71622-ac96-45ea-a5c3-53d89e98a432/jobs/9858105
I normally use mypy 0.79 to verify the code.

**Comment by juntang-zhuang** [comment]
@glaringlee Thanks so much! I'll try to fix it as soon as possible.

**Comment by juntang-zhuang** [comment]
@glaringlee Hi, I fixed all the format and indention errors. Now the left error are the following, I suspect they are related to the modified api of torch but not related to my part of code, could you take a look? Thanks a lot. The errors are:
(1) AssertionError: mypy failed: torch/optim/_multi_tensor/adabelief.py:166: error: Incompatible types in assignment (expression has type "Union[Tuple[Tensor, ...], List[Tensor]]", variable has type "List[Any]")  [assignment]. 
Line [166](https://github.com/juntang-zhuang/pytorch/blob/b700f0ca40460fa9f314a440f68ef23f13266560/torch/optim/_multi_tensor/adabelief.py#L166) is modified from the _multi_tensor version of [Adam](https://github.com/pytorch/pytorch/blob/8d7338e820b1296e01b0d3ba1166907a98c26542/torch/optim/_multi_tensor/adam.py#L126)

**Comment by glaringlee** [comment]
> @glaringlee Hi, I fixed all the format and indention errors. Now the left error are the following, I suspect they are related to the modified api of torch, could you take a look? Thanks a lot. The errors are:
> 
> (1) AssertionError: mypy failed: torch/optim/_multi_tensor/adabelief.py:166: error: Incompatible types in assignment (expression has type "Union[Tuple[Tensor, ...], List[Tensor]]", variable has type "List[Any]") [assignment].
> 
> Line 166 of [AdaBelief](https://github.com/juntang-zhuang/pytorch/blob/b700f0ca40460fa9f314a440f68ef23f13266560/torch/optim/_multi_tensor/adabelief.py#L166) is modified from the _multi_tensor version of [Adam](https://github.com/pytorch/pytorch/blob/8d7338e820b1296e01b0d3ba1166907a98c26542/torch/optim/_multi_tensor/adam.py#L126), yet I don't understand why there is a syntax error.
> 
> (2) There are also errors with the "zero_grad" function:
> torch/optim/_multi_tensor/adabelief.py:258: error: Argument 1 of "zero_grad" is incompatible with supertype "Optimizer"; supertype defines the argument type as "Optional[bool]" [override]
> torch/optim/_multi_tensor/adabelief.py:259: error: Need type annotation for 'per_device_and_dtype_grads' [var-annotated]
> 
> the version in [AdaBelief](https://github.com/juntang-zhuang/pytorch/blob/b700f0ca40460fa9f314a440f68ef23f13266560/torch/optim/_multi_tensor/adabelief.py#L254) is directly copied from [Adam](https://github.com/pytorch/pytorch/blob/8d7338e820b1296e01b0d3ba1166907a98c26542/torch/optim/_multi_tensor/adam.py#L145), could you help me check what caused the error?
> 
> (3) Errors with the "quantize" api:
> torch/quantization/fx/quantize.py:224: error: Unsupported right operand type for in ("Union[Tensor, Module]") [operator]
> torch/quantization/fx/quantize.py:556: error: Incompatible types in assignment (expression has type "List[int]", variable has type "Union[Tensor, Module]") [assignment]
> torch/quantization/fx/quantize.py:557: error: Incompatible types in assignment (expression has type "List[int]", variable has type "Union[Tensor, Module]") [assignment]
> torch/quantization/fx/quantize.py:839: error: Argument 1 to "len" has incompatible type "Union[Tensor, Module]"; expected "Sized" [arg-type]
> torch/quantization/fx/quantize.py:840: error: Unsupported right operand type for in ("Union[Tensor, Module]") [operator]
> 
> The "quantize" functions are not modified in this pull request, it's forked from the master branch of pytorch, should I report this error in a new issue, or just ignore the error?
> 
> (4) Running the code "test/test_optim.py" gives error with "AdaDelta", but code for AdaDelta is directly forked from the master branch and never modified. The error messages are:
> 
> ## FAIL: test_adadelta (**main**.TestOptim)
> Traceback (most recent call last):
> File "/home/juntang/Downloads/pytorch_fork/pytorch/torch/testing/_internal/common_utils.py", line 418, in wrapper
> fn(*args, **kwargs)
> File "test_optim.py", line 545, in test_adadelta
> lambda weight, bias: optimizer(
> File "test_optim.py", line 208, in _test_basic_cases
> constructor
> File "test_optim.py", line 192, in _test_state_dict
> self.assertEqual(weight, weight_cuda)
> File "/home/juntang/Downloads/pytorch_fork/pytorch/torch/testing/_internal/common_utils.py", line 1175, in assertEqual
> super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
> AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 5 element(s) (out of 50) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 2.002716064453125e-05 (-0.7925083637237549 vs. -0.7925283908843994), which occurred at index (9, 1).
> 
> The code for AdaDelta is from the master branch and not modified in this pull request, does this imply some errors with the code in master branch?
> 
> (5) It's not an error, but when I compiled PyTorch 1.8 from source code, it seems it's almost twice slower even with Adam optimizer. Is there any option that needs to be set up during compilation? Thanks a lot.
> 
> Thanks so much for help.

@juntang-zhuang 
Back from vocation today, I will take a look at these one by one and comment.
mypy sometimes is a bit overkilled, let me dig a bit see how to handle these mypy errors, some of them we might just use # type ignore, some of them, we might need to annotate the type of original variable. I will comment them one by one.

The assert error seems that the additional logic in Adabelief do make the precision diff bigger, I think that's not a big deal, let me check it a bit and we can loose the  rtol and atol a bit.

**Comment by juntang-zhuang** [comment]
@glaringlee Thanks so much for help! Regarding the assertion error, are you referring to error (4) related to rtol and atol? It’s actually for test AdaDelta rather than AdaBelief, and AdaDelta is unchanged from the master branch. Thanks again for your help with this PR.

**Comment by glaringlee** [comment]
@juntang-zhuang That probably because of the different platform since our online CI test not failed. What system you are using? Windows or linux, version?
You can actually just update your code and see whether the ci tests in this page passed. If any test failed, you can simply click the test link above and see error details in the log.
Here is one of above failed test:
https://app.circleci.com/pipelines/github/pytorch/pytorch/255519/workflows/31752a26-f182-4b96-91e6-6c0a55fe8582/jobs/9878021/steps
And if you click the 'download full output as a file` and search `adaDelta`, you will see the test passed. The name of the test `pytorch_linux_bionic_py3_6_clang9_test` indicates the env it uses. This is ubuntu 18.04 + python 3.6 (or 3.8 but not 3.9) + clang9 wihtout cuda support.

Are you using python 3.9? if so, it might be the cause, 3.9 is a bit problematic to pytorch at this point.

**Comment by juntang-zhuang** [comment]
@glaringlee Thanks for clarification. My environment is Ubuntu16.04+CUDA10.1+CUDNN7.3.1+python 3.7.4. Good to know AdaDelta passed test on CI, I guess my environment might have some configuration error that caused this assertion error. Could this also be the reason that my compilation from source is twice slower compared to the nightly build?

**Comment by glaringlee** [comment]
@juntang-zhuang 
You cudnn version is a bit low. What you can do is to compile pytorch without cuda entirely (add USE_CUDA=0 before python setup.py develop), and test your code again.

**Comment by juntang-zhuang** [comment]
@glaringlee Thanks a lot for suggestion. I tried compiling without cuda, but the same error still exists, is there any documentation on the foreach api in pytorch? Also I noticed the error with zero_grad function has disappeared, just curious how you fixed it? Thanks so much for help.

**Comment by glaringlee** [comment]
@juntang-zhuang 
Your errors are all mypy error, we use mypy to check type annotation, it not really an error though. To bypass those errors, you can add `  # ignore type` on each line that has such error. And then fix them one by one. 

I suggested you to compile without cuda is to let you check whether the performance is still worse in pytorch 1.8, we use cuda and cudnn to optimize operators, earlier version might be a cause of the performance decrease. 

the owner of foreach api is on vocation till next week, i am not sure whether we have a doc now since this is new, but I will check.

**Comment by juntang-zhuang** [comment]
@glaringlee Sure, thanks for letting me know.

**Comment by glaringlee** [comment]
@juntang-zhuang 
We are good on our side, can you rebase your code and try? Thanks.

**Comment by juntang-zhuang** [comment]
@glaringlee Thanks a lot. Just rebased it, but I'm quite unfamiliar with pr and rebase, not sure why there's a automatic review request to so many people. Please just ignore it.

**Comment by glaringlee** [comment]
@juntang-zhuang 
Yep, please create a new PR and close this one.

**Pull request closed without merging**
