### PR TITLE
Migrate uses of THCReduceApplyUtils to cuda_utils::BlockReduce

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #64713

Resubmit of #64442

Differential Revision: [D30825646](https://our.internmc.facebook.com/intern/diff/D30825646)

### CODE REVIEW

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30825646).

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Unfortunately, I cannot trigger win cuda 11.3 build on this PR, but let's hope the change fixes the error.

**Comment by malfet** [comment]
Added Peter to ciflow opt-in and scheduled 11.3 builds

**Pull request closed without merging**
