### PR TITLE
[inductor] Enable CudaWrapperCodeGen for non-AOT mode

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #98264
* #98088

Summary: when _inductor.config.cpp_wrapper is specified, we run a
two-pass wrapper codegen to generate wrapper code in cpp which calls
cuLaunchKernel to launch pre-compiled cuda kernels, and then call
load_inline to load that generated wrapper back into the python world.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your PR, but this is failing in trunk due to a name error fake_mode_from_tensors is not defined, i.e. 
https://hud.pytorch.org/pytorch/pytorch/commit/67d1a77086fb03a6d11612ccf221437bc28b4797.  This is probably a landrace' -c landarace

**Pull request closed without merging**
