### PR TITLE
[jit] More robust mangling

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#31978 [jit] More robust mangling**

Summary:
Currently we keep a `mangleIndex_` that's intenral to compilation unit and
just increment the index when we found the original name is mangled, this doesn't
guarantee the new name is not defined.
This PR fixes the problem by querying whether the new name is defined or not.
fixes: https://github.com/pytorch/pytorch/issues/31268

Test Plan:
fixes the issue

Reviewers:
.

Subscribers:

Tasks:

Tags:

Differential Revision: [D19350535](https://our.internmc.facebook.com/intern/diff/D19350535)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 56e8144d:


**None of the build failures appear to be your fault**.

* **1/1** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=5cc49ed45f571fbc2586f88a025b7b851f4214a4&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base 5cc49ed4 since Jan 08
  <details>
  <summary>
  You may want to rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch origin viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=56e8144d8e3badb1b9b390b6fddceb1bb20efa6b).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [pytorch_macos_10_13_py3_test](https://dr.pytorch.org/build-details.html?build_id=82470096) from Jan 08



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by suo** [comment]
The reason why I wouldn't expect us to have to re-check is because:
1. The CompilationUnit is the one managing all type creation for itself. 
2. Therefore, the mangle index strictly increase as types are created.

Assumption #1 must be wrong—how are we getting a type created in the CU with a higher index than `mangleIndex_` assigned?

**Review by suo — CHANGES_REQUESTED** [review]
tests please! And I had a clarification question; I believe that this change fixes the problem, but I would like to understand why the problem happened in the first place.

**Comment by jerryzh168** [comment]
I think this happens when we 
1. save a ClassType with mangled name(probably from tracing), which has mangled names 0 - 150 in this case
2. load it
3. copy it: we have a new CompilationUnit with `mangledIndex_` == 0 and we'll have a conflict if we create new mangled names with `mangle_0` since 0 - 150 are already taken.

**Review by suo — APPROVED** [review]

**Pull request closed without merging**
