### PR TITLE
add bfloat16 support for kl_div_backward_cuda

### PR DESCRIPTION
**Pull request by Aidyn-A**
This PR adds a feature requested in issue #77375.
`kl_div_backward_cuda` now supports `bfloat16`

cc @ngimel @ptrblck @rosrad

### CODE REVIEW

**Comment by ngimel** [comment]
Test failures are real, please fix supported dtypes in `common_methods_invocations` for the failing ops.

**Comment by Aidyn-A** [comment]
I believe now it is ready for review, the failed tests are not related to the changes in this PR

**Review by jbschlosser — APPROVED** [review]
Confirmed spurious CI failures. LGTM!

**Comment by jbschlosser** [comment]
@Aidyn-A Maybe a rebase will fix the CI failures?

**Comment by Aidyn-A** [comment]
@jbschlosser, rebase definitely worked. Thanks!

**Pull request closed without merging**
