### PR TITLE
Fix typo under torch/csrc/jit/tensorexpr directory 

### PR DESCRIPTION
**Pull request by kiszk**
This PR fixes typo in comments and messages under `torch/csrc/jit/tensorexpr` directory.

cc @EikanWang @jgong5

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]

**Review by jgong5 — APPROVED** [review]

**Review by EikanWang — APPROVED** [review]

**Comment by kiszk** [comment]
Should I rerun the test or can I leave it?

**Comment by davidberard98** [comment]
Can you rebase & we can see whether the test passes after rebasing?

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
