### PR TITLE
Sparse support for division rounding_mode argument

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #50438 Support JIT shape analysis for div with rounding_mode argument
* #55225 grad_fn getter for optional strings
* **#51989 Sparse support for division rounding_mode argument**
* #56893 Update floor_divide behavior in line with NumPy 1.20
* #55380 Vectorize floating point floor_divide

Differential Revision: [D28118114](https://our.internmc.facebook.com/intern/diff/D28118114)

### CODE REVIEW

**Comment by ezyang** [comment]
ACKing native_functions.yaml changes

**Comment by mruberry** [comment]
Looks like the tests need an update

**Comment by peterbell10** [comment]
@mruberry tests are updated and passing.

**Review by mruberry — APPROVED** [review]
Cool!

**Pull request closed without merging**
