### PR TITLE
Fix issue #7209 in DataLoader

### PR DESCRIPTION
**Pull request by vfdev-5**
Addresses the issue #7209

### CODE REVIEW

**Review by apaszke — CHANGES_REQUESTED** [review]
There's no randomness involved. Every time the workers will start, the state of their PRNGs will always be fully determined by `7054 + worker_nr`. Let's just move the `base_seed` out of the `if` statement. I can't see any issue with that.

**Comment by vfdev-5** [comment]
> There's no randomness involved. Every time the workers will start, the state of their PRNGs will always be fully determined by `7054 + worker_nr`

@apaszke sorry I don't get your comment on "no randomness involved". Worker's PRNG is setup by a seed randomly picked between 0 and `7054 + worker_id`, so yes workers seed is determined by current rng state and the interval `[0, 7054 + i]`.

Similarly if `base_seed` were picked randomly (determined by current rng) and then worker's RNG would be setup by `base_seed + worker_id`.

Okay, I can change as you ask...

**Comment by apaszke** [comment]
Hmmm ok I think that could have worked, my bad. However, I still think that my solution is better, because yours assumes that you've forked the workers, and inherited the PRNG state from the main process, while in reality someone might be using the `spawn` start method, and will get a completely different behavior.

**Comment by vfdev-5** [comment]
I see, thanks, for pointing on `spawn` !

**Comment by vfdev-5** [comment]
@apaszke it is OK that it fails only on macosx ?

**Review by apaszke — APPROVED** [review]

**Comment by apaszke** [comment]
Thanks @vfdev-5!

**Pull request merged**
