### PR TITLE
Convert Embedding to new style.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by jekbradbury** [comment]
Any particular reason `_backend.Embedding` isn't wrapped in the functional interface? I just ran into a use case where I needed a functional-style embedding module; maybe `F.embedding(x, W)` should be a synonym of `self._backend.Embedding(-1, None, 2, False, False)(x, W)`?

**Comment by soumith** [comment]
isn't embedding in functional interface just an indexing operation?
```
y = W[x, :]
```

**Comment by fmassa** [comment]
@soumith a bit unrelated: the gradients of indexing operators are dense, while in `Embedding` we can set them to `sparse`. Is that something that we plan to add in the future?

**Comment by apaszke** [comment]
@fmassa it would be great to have that, but we'd need an automatic conversion in case that grad would be used in a function not implemented for sparse tensors. Most backward functions would break if you gave them sparse grad outputs

**Comment by fmassa** [comment]
@apaszke I think whenever we add support for implicit type conversion between functions (do we plan to add that?), we could extend it for sparse-dense tensors as well?

**Comment by apaszke** [comment]
@fmassa can you elaborate? I'm not sure what you mean

**Comment by hughperkins** [comment]
By the way, somewhat related to @jekbradbury 's comment: I've created a PR for Embedding here: https://github.com/pytorch/pytorch/pull/1987

**Pull request merged**
