### PR TITLE
[inductor] Don't clamp on `split` operation.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #141078
* #141077

This PR turns clamping off for the `split` operation. By doing so, we generate less bound
guards and reduce the number of recompilation when varying the input size.

```python
@torch.compile(dynamic=True)
def f(x):
    return x.chunk(4)

>>> f(torch.arange(12))
(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]))

>>> f(torch.arange(11))

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10]))

>>> f(torch.arange(10))
(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([9]))
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ysiraichi** [comment]
I think it's worth mentioning what was going wrong with `test_split_with_sizes_with_unbacked_symints`. To start things of, the relevant parts of the test are:

```python
@torch.compile()
def f(sz, x):
    s0, s1 = sz.tolist()
    r0, r1 = torch.ops.aten.split_with_sizes.default(x, [s0, s1])
    return torch.ops.aten.sort.default(r1)

N = 7312
S0 = 420
S1 = N - S0

result = f(torch.tensor([S0, S1]), torch.randn(N))
```

The error that was being raised was:

```python
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor.py", line 11621, in test_split_with_sizes_with_unbacked_symints
    result = f(torch.tensor([S0, S1]), torch.randn(N))
  ...
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1063, in call_function
    out = lowerings[target](*args, **kwargs)  # type: ignore[index]
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/lowering.py", line 401, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/lowering.py", line 5959, in sort
    return sort_stable(x, stable=False, dim=dim, descending=descending)
  ...
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 6298, in _evaluate_expr
    raise self._make_data_dependent_error(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: GuardOnDataDependentSymNode: Could not guard on data-dependent expression Eq(7312 - u0, 0) (unhinted: Eq(7312 - u0, 0)).  (Size-like symbols: u0)
```

Which likely is due to a size check on `r1`. For some reason, dynamo can't statically decide whether `Eq(7312 - u0, 0)` is true. Observe that:

- Before this PR, the guard was `Eq(u1, 0)`
- I can see a `Eq(u0 + u1, 7312)` runtime assert being added

Therefore, I'd think that if dynamo can statically decide whether `Eq(u1, 0)` is true (0/1 specialization), it should also be able to decide whether `Eq(7312 - u0, 0)` (since it's also the size of a tensor). Not sure the details about why this is not the case. @ezyang is this a known dynamo limitation?

**Comment by ezyang** [comment]
This is probably same root cause as https://github.com/pytorch/pytorch/issues/120288

**Pull request closed without merging**
