### PR TITLE
Fix conda install on distributions with strict POSIX sh

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #91371

See also https://github.com/conda/conda/issues/10431

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by Erotemic** [comment]
There seemed to be only 14 failing tests on the M1.

```
torch/distributed/optim/zero_redundancy_optimizer.py ZeroRedundancyOptimizer:0
torch/distributed/_composable/replicate.py replicate:0
torch/distributed/_composable/_ddp.py DistributedDataParallel.register_comm_hook:0
torch/distributed/_composable/_ddp.py DistributedDataParallel.register_comm_hook:1
torch/distributed/_shard/sharded_tensor/__init__.py custom_sharded_op_impl:0
torch/distributed/_shard/sharding_plan/api.py ShardingPlan:0
torch/testing/_internal/distributed/_tensor/common_dtensor.py skip_unless_torch_gpu:0
torch/ao/nn/quantized/functional.py conv1d:0
torch/ao/nn/quantized/functional.py conv2d:0
torch/ao/nn/quantized/functional.py conv3d:0
torch/ao/nn/quantized/modules/linear.py Linear:0
torch/ao/nn/quantized/modules/conv.py Conv1d:0
torch/ao/nn/quantized/modules/conv.py Conv2d:0
torch/ao/nn/quantized/modules/conv.py Conv3d:0
```

The first 7 of these also failed on macos-12. They seemed to be caused by 2 underlying issues. For the first 7, the `torch._C` module didn't exist, so I added a `# xdoctest: +REQUIRES(module:torch._C)`, which should conditionally skip those tests. For the second m1 only failures, they seem to be due to not having a QEngine, so I tagged those with the exiting `xdoctest: +REQUIRES(env:TORCH_DOCTEST_QENGINE)` condition, which is currently hard coded to be off in run_tests.py. Future work can set this more granularity.

But if these are the only issues, then I think we can keep doctests enabled on M1.

**Review by albanD — APPROVED** [review]

**Comment by kit1980** [comment]
`trunk / cuda11.6-py3.10-gcc7-sm86 / test (slow, 1, 2, linux.g5.4xlarge.nvidia.gpu)` started to fail after this PR with 

```
Test results will be stored in test-reports/python-unittest/test_type_hints
  test_doc_examples (__main__.TestTypeHints)
Run documentation examples through mypy. ... FAIL (7.171s)
  test_doc_examples (__main__.TestTypeHints)
Run documentation examples through mypy. ...     test_doc_examples failed - num_retries_left: 3
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_type_hints.py", line 134, in test_doc_examples
    self.fail(f"mypy failed:\n{stderr}\n{stdout}")
AssertionError: mypy failed:
```

But I don't see how this PR can be possibly related...

**Comment by kit1980** [comment]
I still don't understand what's going on, but with the revert of this PR "trunk / cuda11.6-py3.10-gcc7-sm86 / test (slow, 1, 2, linux.g5.4xlarge.nvidia.gpu)" passed.
Maybe this PR makes it so a different Conda environment used compared to what's expected?

**Comment by kit1980** [comment]
Let's try again after https://github.com/pytorch/pytorch/pull/91410

**Pull request closed without merging**
