### PR TITLE
Remove thrust casting from static_cast_with_inter_type

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
CUDA 9.2 bug is still there, needs to wait until all thrust::complex removed from kernels

**Comment by zou3519** [comment]
@zasdfgbnm when this is ready feel free to tag someone as a reviewer (or ping me and I'll try to review or find someone who can).

**Comment by zasdfgbnm** [comment]
@zou3519 Just rebased, and I believe this should be ready. I have tagged @ngimel has a reviewer she recently reviewed similar changes.

**Comment by zasdfgbnm** [comment]
ping @ngimel

**Review by ngimel — APPROVED** [review]
Waiting on CI

**Pull request closed without merging**
