### PR TITLE
Fixing "naive" `forward`  of `ModuleList` and `ModuleDict`

### PR DESCRIPTION
**Pull request by shaibagon**
Currently, when naively calling `forward` (or implicitly `__call__`) user ends up with the error message:
```python
TypeError: forward() takes 1 positional argument but 2 were given
```
Instead of the [intended][1] `NotImplementedError`.
This minor issue was brought up by @vadimkantorov in issue #37718 [here][2], also by a confused stackoverflow user [here][3].

This _minimal_ pull request makes sure the proper `NotImplementedError` is raised, and the user gets a clearer picture of waht is going on.
 

[1]: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/container.py#L232
[2]: https://github.com/pytorch/pytorch/issues/37718#issuecomment-736333345
[3]: https://stackoverflow.com/q/65096679/1714410

### CODE REVIEW

**Comment by ngimel** [comment]
Please add a test for this.

**Comment by vadimkantorov** [comment]
(the fix looks good to me: it should eat all arguments now and throw respecfully)

**Comment by shaibagon** [comment]
@ngimel working on it.

It seems like this fix breaks things on jit tests. 

I'll update when this PR can be seriously considered.

**Comment by shaibagon** [comment]
I messed this up. removing and re-doing it with tests. soory.

**Pull request closed without merging**
