### PR TITLE
cuDNN convolution try multiple algo

### LINKED ISSUE #31336: cudnn heuristics (cudnnGet*) returns algorithms that cannot be used
## 🐛 Bug

For certain input shapes (it seems not to be related to absolute size in bytes, see examples) Conv2D failes with CUDNN_STATUS_NOT_SUPPORTED

## To Reproduce

1. Code snipped:

Problem can be reproduced with:
```
import torch
x = torch.rand(1, 16, 70000, 100).to('cuda:0')
print('size of tensor: {:,} bytes'.format(x.element_size()*x.nelement()))
conv = torch.nn.Conv2d(in_channels=16, out_channels=32, kernel_size=(3,3), bias=False).to('cuda:0')
out = conv(x)
print(out.shape)
```
Note that the issue does not occur with slightly different shape and similar (slightly larger) sized tensor:

```
x2 = torch.rand(1, 16, 3000, 3000).to('cuda:0')
print('size of tensor: {:,} bytes'.format(x2.element_size()*x2.nelement()))
out2 = conv(x2)
print(out2.shape)
```

2. Google Colab Notebook:

https://colab.research.google.com/drive/1szd95jnY0rkcblIq8n9Zo0BpsWdFhrf3

Output of snipped (also compare Google Colab Notebook:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-872c4a39a547> in <module>()
      3 print('size of tensor: {:,} bytes'.format(x.element_size()*x.nelement()))
      4 conv = torch.nn.Conv2d(in_channels=16, out_channels=32, kernel_size=(3,3), bias=False).to('cuda:0')
----> 5 out = conv(x)
      6 print(out.shape)

2 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py in conv2d_forward(self, input, weight)
    340                             _pair(0), self.dilation, self.groups)
    341         return F.conv2d(input, weight, self.bias, self.stride,
--> 342                         self.padding, self.dilation, self.groups)
    343 
    344     def forward(self, input):

RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```

## Environment

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: TITAN RTX
GPU 5: TITAN RTX

Nvidia driver version: 430.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

GPU:
GeForce GTX 1080 Ti (rev a1)

CUDA:
NVIDIA-SMI 430.26 Driver Version: 430.26 CUDA Version: 10.2

cudnn:

torch.backends.cudnn.version()
7501

 - OS: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-58-generic x86_64)
 - How you installed PyTorch: pip
 - Python version: Python 3.6.8

## Additional context

Problem may be related to:
https://github.com/pytorch/pytorch/issues/4107
https://github.com/pytorch/pytorch/issues/11065

I tried to find out which cuDNN bug is referenced in 11065 but without success.

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fixes: https://github.com/pytorch/pytorch/issues/31336 https://github.com/pytorch/pytorch/issues/1664

Sometimes cuDNN heuristics return algorithms that can not be used. Instead of just using the first algorithm returned, we should try these algorithms one by one until one of them succeed.

Benchmark:
https://github.com/zasdfgbnm/things/blob/master/2020Q1/conv-benchmark.ipynb
```python
i = torch.randn(256, 3, 256, 256).cuda()
c = torch.nn.Conv2d(3, 3, 3, 3).cuda()

%timeit c(i); torch.cuda.synchronize()
```
before vs after = 498 vs 490 µs

The performance is improved I guess because, before this PR, we always call the heuristics to get the algorithm, but after this PR, we only do at the first time.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
cc: @ptrblck @csarofeen

**Comment by zasdfgbnm** [comment]
This also seems to fix https://github.com/pytorch/pytorch/issues/31500

**Comment by zasdfgbnm** [comment]
This would conflict with https://github.com/pytorch/pytorch/pull/33056

**Comment by zasdfgbnm** [comment]
Ahha, this is conflicting

**Review by ngimel — APPROVED** [review]
LGTM

**Pull request closed without merging**
