### PR TITLE
Add metas for randint/rand factory functions out overload

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #122375

Fixes https://github.com/pytorch/pytorch/issues/121897

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by ezyang** [comment]
cc @jansel on the failures here, how puzzling

**Comment by jansel** [comment]
> cc @jansel on the failures here, how puzzling

You could try something like:
```
if isinsance(high, torch.fx.Node):
   high = torch.fx.Proxy(high)
```

Those replacements are expecting low/high to be constants.  There is likely the same issue with the other replacements in that file.

**Review by lezcano — APPROVED** [review]

**Pull request closed without merging**
