### PR TITLE
[JIT] Fix append schema

### PR DESCRIPTION
**Pull request by eellison**
`[].append(1)` returns None in python.  I don't think this will break BC because the return value is always unused. As is, the schema causes confusion.

### CODE REVIEW

**Comment by eellison** [comment]
@BowenBao i'm trying to update the schema for list append here so that the IR doesn't print out a confusingly unused return value in append. 

This breaks https://github.com/pytorch/pytorch/blob/4e5af8d14655a33ea3ecbcf913bf1a602c79a110/test/onnx/test_pytorch_onnx_onnxruntime.py#L2372

The test in question does:

```
class ListLoopModel(torch.jit.ScriptModule):
    @torch.jit.script_method
    def forward(self, x):
        res = []
        res1 = []
        arr = x.split([3, 4, 1, 1, 2, 3, 2], 0)
        res2 = torch.zeros(3, 4, dtype=torch.long)
        for i in range(len(arr)):
            res = res.append(arr[i].sum(0, False))
            res1 = res1.append(arr[-1 - i].sum(0, False))
            res2 += 1
        return torch.stack(res), torch.stack(res1), res2
```

This isn't valid python, and no user would write this. `res = res.append(arr[i].sum(0, False))` would be None in python. I'm not sure how to proceed here. What do you think ?

**Comment by BowenBao** [comment]
@eellison This is the current workaround we have for our users. It generates ir graph in a way that we can proceed with: the append result is captured in loop output, and the operations that consume the list outside the loop is taking new output as input. 

```
graph(%self : __torch__.ListLoopModel,
      %x.1 : Tensor):
...
  %res.1 : Tensor[] = prim::ListConstruct()
  %res1.1 : Tensor[] = prim::ListConstruct()
  %9 : int[] = prim::ListConstruct(%5, %6, %7, %7, %8, %5, %8)
  %arr.1 : Tensor[] = aten::split(%x.1, %9, %10) # repro_append_new.py:8:14
  %14 : int[] = prim::ListConstruct(%5, %6)
  %res2.1 : Tensor = aten::zeros(%14, %6, %15, %15, %15) # repro_append_new.py:9:15
  %20 : int = aten::len(%arr.1) # repro_append_new.py:10:23
  %res : Tensor[], %res1 : Tensor[], %res2 : Tensor = prim::Loop(%20, %23, %res.1, %res1.1, %res2.1) # repro_append_new.py:10:8
    block0(%i.1 : int, %res.7 : Tensor[], %res1.6 : Tensor[], %res2.6 : Tensor):
      %28 : Tensor = aten::__getitem__(%arr.1, %i.1) # repro_append_new.py:11:29
      %31 : int[] = prim::ListConstruct(%10)
      %33 : Tensor = aten::sum(%28, %31, %29, %15) # repro_append_new.py:11:29
      %res.3 : Tensor[] = aten::append(%res.7, %33) # repro_append_new.py:11:18
       = prim::Print(%36, %res.3) # repro_append_new.py:12:12
      %43 : int = aten::sub(%41, %i.1) # repro_append_new.py:13:35
      %44 : Tensor = aten::__getitem__(%arr.1, %43) # repro_append_new.py:13:31
      %47 : int[] = prim::ListConstruct(%10)
      %49 : Tensor = aten::sum(%44, %47, %29, %15) # repro_append_new.py:13:31
      %res1.3 : Tensor[] = aten::append(%res1.6, %49) # repro_append_new.py:13:19
      %res2.3 : Tensor = aten::add_(%res2.6, %7, %7) # repro_append_new.py:14:12
      -> (%23, %res.3, %res1.3, %res2.3)
  %58 : Tensor = aten::stack(%res, %10) # repro_append_new.py:15:15
  %61 : Tensor = aten::stack(%res1, %10) # repro_append_new.py:15:33
  %63 : (Tensor, Tensor, Tensor) = prim::TupleConstruct(%58, %61, %res2)
  return (%63)
```

We thought as well this is not valid python code, but surprisingly it works. The torchscript backend indeed has a return value for `aten::append`. Just curious what is happening behind the scene. Could you point me to the location of source code for `aten::append`? How is just updating the schema/signature enough?

**Comment by eellison** [comment]
When something is not valid python, and surprisingly works, that's usually a bug. It would be helpful in the future if someone would raise an issue in this case. I would suggest to handle the same pattern with something that is actually valid python with:
```
class ListLoopModel(torch.jit.ScriptModule):
    @torch.jit.script_method
    def forward(self, x):
        res = []
        arr = x.split([3, 4, 1, 1, 2, 3, 2], 0)
        for i in range(len(arr)):
            res = res + [arr[i].sum(0, False)]
        return torch.stack(res)
```

Abt updating schema, yea you're right I also need to update the op implementation, good catch. This isn't a high priority PR but the current schema does lead to confusion, such as https://github.com/pytorch/pytorch/issues/39362.

**Comment by eellison** [comment]
What do you think ?

**Pull request closed without merging**
