### PR TITLE
[Inductor][mkldnn] Bug fix: incorrect codegen arg order for qconv

### LINKED ISSUE #133448: [inductor][cpu] densenet121 PT2E/QAT crash in 2024-08-10 nightly release
### 🐛 Describe the bug

densenet121 PT2E/QAT crash
```
/workspace/pytorch/torch/_inductor/mkldnn_lowerings.py:662: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(w_zp_tensor, dtype=torch.int32), name=w_zp.get_name()
Traceback (most recent call last):
  File "/workspace/benchmark/userbenchmark/cpu/run_config.py", line 97, in <module>
    run(args, extra_args)
  File "/workspace/benchmark/userbenchmark/cpu/run_config.py", line 77, in run
    metrics_res = run_config(config, metrics, dryrun=args.dryrun)
  File "/workspace/benchmark/userbenchmark/cpu/run_config.py", line 57, in run_config
    result: TorchBenchModelMetrics = get_model_test_metrics(model, metrics=metrics)
  File "/workspace/benchmark/torchbenchmark/util/experiment/metrics.py", line 127, in get_model_test_metrics
    latencies = get_latencies(model.invoke, device, nwarmup=nwarmup, num_iter=num_iter)
  File "/workspace/benchmark/torchbenchmark/util/experiment/metrics.py", line 30, in get_latencies
    func()
  File "/workspace/benchmark/torchbenchmark/util/model.py", line 278, in invoke
    out = self.eval()
  File "/workspace/benchmark/torchbenchmark/util/framework/vision/model_factory.py", line 98, in eval
    return self.model(*self.example_inputs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 463, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/fx/graph_module.py", line 739, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/workspace/pytorch/torch/fx/graph_module.py", line 317, in __call__
    raise e
  File "/workspace/pytorch/torch/fx/graph_module.py", line 304, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.1008", line 4, in forward
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 630, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 1062, in forward
    return compiled_fn(full_args)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 330, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/utils.py", line 121, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 501, in wrapper
    return compiled_fn(runtime_args)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1221, in wrapper
    return optimized_function(args_new)
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 1415, in __call__
    return self.current_callable(inputs)
  File "/tmp/torchinductor_root/6v/c6vhozovnfcmkjcviht4cxo6wegtczne5kqiqhjw3abnxtr77cjr.py", line 4404, in call
    buf6 = torch.ops.onednn.qconv2d_pointwise.default(buf5, 0, None, _frozen_param921, _frozen_param192, _frozen_param193, 0.002583648543804884, [1, 1], [1, 1], [1, 1], 1, 0.010597636923193932, 119, torch.uint8, 'none', [None], '')
  File "/workspace/pytorch/torch/_ops.py", line 720, in __call__
    return self._op(*args, **kwargs)
RuntimeError: onednn::qconv2d_pointwise() Expected a value of type 'int' for argument 'x_zero_point' but instead found type 'NoneType'.
```

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Branch</th>
      <th>Target commit</th>
      <th>Refer commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>nightly</td>
      <td>22f2d2c</td>
      <td>d6ea1eb</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>chuanqiw/inductor_quant</td>
      <td>ee35d764</td>
      <td>ee35d764</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>nightly</td>
      <td>b3f6f51</td>
      <td>b3f6f51</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>nightly</td>
      <td>b0ebddc</td>
      <td>b0ebddc</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>nightly</td>
      <td>d23a6e1</td>
      <td>d23a6e1</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>nightly</td>
      <td>11bb5b8</td>
      <td>11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>fea73cb</td>
      <td>fea73cb</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
```
git clone -b chuanqiw/inductor_quant https://github.com/pytorch/benchmark.git
cd benchmark
pip install --no-deps -r requirements.txt
pip install --no-cache Jinja2==3.1.2 markupsafe==2.0.1 beartype==0.15.0 && pip install mpmath==1.3.0
python install.py --continue_on_fail
export LD_PRELOAD=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}/lib/libiomp5.so:${CONDA_PREFIX:-"$(dirname $(which conda))/../"}/lib/libjemalloc.so
export MALLOC_CONF="oversize_threshold:1,background_thread:true,metadata_thp:auto,dirty_decay_ms:-1,muzzy_decay_ms:-1"
TORCHINDUCTOR_FREEZING=1 python run_benchmark.py cpu -m densenet121 --torchdynamo inductor --quantize --launcher --launcher-args="--throughput-mode" -b 128 --metrics throughputs
```
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/fd874b799fd43d0f568f783fd6d93f546b3e58f8
[torchbench-densenet121-inference-static-ptq-crash_guilty_commit.log](https://github.com/user-attachments/files/16615064/torchbench-densenet121-inference-static-ptq-crash_guilty_commit.log)
cc @ezyang @chauhang @penguinwu @WeizhuoZhang-intel @chuanqi129

### PR DESCRIPTION
**Pull request by Xia-Weiwen**
Fixes #133448

The arg order for mkldnn qconv IR became incorrect after PR #132367 . This PR fixes the bug.

**Test plan**
`python test/inductor/test_mkldnn_pattern_matcher.py -k qconv`
`python test/inductor/test_cpu_cpp_wrapper.py -k qconv`

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by leslie-fang-intel** [comment]
Thanks for the fix. Please request review when pass the CI and also adding the testcase of qconv without bias.

**Review by leslie-fang-intel — APPROVED** [review]

**Comment by Xia-Weiwen** [comment]
Hi @jgong5 Could you please review? Thanks.

**Review by jgong5 — APPROVED** [review]

**Pull request closed without merging**
