### PR TITLE
Update persons of interest for ONNX

### PR DESCRIPTION
**Pull request by garymm**

### CODE REVIEW

**Comment by soumith** [comment]
I dont think this is acceptable -- emeritus persons of interest is useful and also an appropriate way to credit. It's generally accepted as a way of acknowledgement in open-source. It preserves historical lineage in a respectful / appropriate way.
If it is a question of verbosity, we can move the Emeritus people to a separate Emeritus section on the same page, i.e. give them their own scroll-down.

> I think the utility of the document is to
identify people who are currently involved in a particular area.
Git commit logs and PR history can be used to find who contributed to
something in the past.

This argument is generally not convincing -- you can find current contributors through git commit logs too. Either ways, I've rejected this line of argument above.

**Comment by garymm** [comment]
@malfet restored the emeritus persons. Please import when you have a chance.

**Comment by garymm** [comment]
@msaroufim PTAL

**Comment by msaroufim** [comment]
@garymm I'm not the right person to make changes to this page

**Comment by garymm** [comment]
@msaroufim @malfet I don't see how this change could be at all objectionable. It's just making the file match reality. If you don't feel comfortable importing it, could you please help find someone else?

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Sorry, missed the notification. Looks good to me

**Comment by garymm** [comment]
@malfet please merge

**Comment by malfet** [comment]
@garymm internal CI can be slow, whenever it finishes it'll be landed

**Pull request closed without merging**
