### PR TITLE
[CI][lintrunner] bump `black` version to 24.4.2

### PR DESCRIPTION
**Pull request by XuehaiPan**
This PR bumps `black` to the latest version to enable 2024 style rather than the old 2023 style.

The most significant style enhancement is: Add parentheses around multiline-string, lambda function, `if-else` expressions when in the function argument list or `list` / `dict` literals. This improves the code readability.

2023 style:

```python
func(
    a=long_long_long_long_then_value
    if long_long_long_long_long_condition
    else long_long_long_long_else_value,
    b=other_argument,
    c=lambda x: x.to("cuda")
    if torch.cuda.is_available()
    else: x,
)
```

2024 style:

```python
func(
    a=(
        long_long_long_long_then_value
        if long_long_long_long_long_condition
        else long_long_long_long_else_value
    ),
    b=other_argument,
    c=lambda x: (
        x.to("cuda")
        if torch.cuda.is_available()
        else: x
    ),
)
```

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #129887
* #129873
* #129886
* #129872
* #129420
* #129871
* __->__ #129870

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel @albanD @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @rec @LucasLLC @MeetVadakkanchery @mhorowitz @pradeepfn @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @tianyu-l @peterbell10

### CODE REVIEW

**Comment by Skylion007** [comment]
I wouldn't be too eager about this because we are thinking about migrating to ruff fmt anyway eventually.

**Comment by XuehaiPan** [comment]
Passing on this if it is not going to be accepted.

**Comment by XuehaiPan** [comment]
I found this is still needed by #129887:

- #129887

See https://github.com/pytorch/pytorch/actions/runs/9749853040/job/26907939210

**Review by malfet — CHANGES_REQUESTED** [review]
Is there a doc somewhere outlining which linters we want to use vs which ones we do not and why?

I.e. why this change is formatting style is better than the previous one and why say ruff-XYZ would not try to re-format this differently?

> I wouldn't be too eager about this because we are thinking about migrating to ruff fmt anyway eventually.

@Skylion007 what doc/meeting decision you are referring to, when saying `we are thinking about migrating to ruff`?

**Comment by XuehaiPan** [comment]
> I.e. why this change is formatting style is better than the previous one

I think the new version's formatting improves code readability. See https://github.com/pytorch/pytorch/pull/129870#issue-2383899985.

2023 style:

```python
func(
    a=long_long_long_long_then_value
    if long_long_long_long_long_condition
    else long_long_long_long_else_value,
    b=other_argument,
    c=lambda x: x.to("cuda")
    if torch.cuda.is_available()
    else: x,
)
```

2024 style:

```python
func(
    a=(
        long_long_long_long_then_value
        if long_long_long_long_long_condition
        else long_long_long_long_else_value
    ),
    b=other_argument,
    c=lambda x: (
        x.to("cuda")
        if torch.cuda.is_available()
        else: x
    ),
)
```

------

Refer to `black` documentation [How stable is Black’s style?](https://black.readthedocs.io/en/stable/faq.html#how-stable-is-black-s-style):

> Stable. Black aims to enforce one style and one style only, with some room for pragmatism. See [The Black Code Style](https://black.readthedocs.io/en/stable/the_black_code_style/index.html) for more details.
> 
> _**Starting in 2022, the formatting output is stable for the releases made in the same year (other than unintentional bugs).**_ At the beginning of every year, the first release will make changes to the stable style. It is possible to opt in to the latest formatting styles using the --preview flag.

`black 24.*.*` will produce consistent style.

**Comment by ezyang** [comment]
I think I would rather switch us to ruff format than do the black version update, TBH. Only slightly more files wobbled but we get much faster autoformatting cf https://github.com/pytorch/pytorch/pull/124845

**Pull request closed without merging**
