### PR TITLE
Add missing args to upsample_nearest2d

### PR DESCRIPTION
**Pull request by supriyar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#31933 Add missing args to upsample_nearest2d**

Summary:
PR #28324 introduced new arguments to upsample_nearest operator, but the corresponding call in symbolic_caffe2 was not updated.
Also added a unit test which will catch such issues in the future for non-quantized ops.

Test Plan:
python test/onnx/test_pytorch_onnx_caffe2.py TestCaffe2Backend_opset9.test_upsample_w_scale

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 0b9f0242:


* **1/2** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=74d69e296e71896bbe29b92fd6dae41cbbee21e3&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base 74d69e29 since Jan 07
  <details>
  <summary>
  You may want to rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch origin viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  
* **1/2** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=0b9f0242924f6d60e9a43097fad83e77f3b07748).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [caffe2_onnx_py3_6_clang7_ubuntu16_04_test](https://dr.pytorch.org/build-details.html?build_id=81679377) from Jan 07 until Jan 07



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by houseroad — COMMENTED** [review]
Could you rebase the PR to the master and rerun the test?

**Comment by supriyar** [comment]
> Could you rebase the PR to the master and rerun the test?

@houseroad looks like the expected output file changed. 
```
AssertionError: 'ir_v[108 chars]ut: "9"\n    output: "6"\n    name: "Upsample_[1025 chars]n}\n' != 'ir_v[108 chars]ut: "14"\n    output: "9"\n    name: "Upsample[1043 chars]n}\n'
  ir_version: 6
  producer_name: "pytorch"
  producer_version: "1.4"
  graph {
    node {
      input: "input"
-     input: "9"
?             ^
+     input: "14"
?             ^^
-     output: "6"
?              ^
+     output: "9"
?              ^
      name: "Upsample_0"
      op_type: "Upsample"
      attribute {
        name: "mode"
        s: "nearest"
        type: STRING
      }
    }
    name: "torch-jit-export"
    initializer {
-     dims: 3
?           ^
+     dims: 4
?           ^
      data_type: 1
-     name: "9"
?            ^
+     name: "14"
?            ^^
-     raw_data: "\000\000\200?\000\000\200?\000\000\000@"
+     raw_data: "\000\000\200?\000\000\200?\000\000\000@\000\000\000@"
?                                                       +++++++++++++
    }
    input {
      name: "input"
      type {
        tensor_type {
          elem_type: 1
          shape {
            dim {
              dim_value: 1
            }
            dim {
              dim_value: 2
            }
            dim {
              dim_value: 3
            }
            dim {
              dim_value: 4
            }
          }
        }
      }
    }
    output {
-     name: "6"
?            ^
+     name: "9"
?            ^
      type {
        tensor_type {
          elem_type: 1
          shape {
            dim {
              dim_value: 1
            }
            dim {
              dim_value: 2
            }
            dim {
              dim_value: 6
            }
            dim {
              dim_value: 8
            }
          }
        }
      }
    }
  }
  opset_import {
    version: 9
  }
```

The change is just different input/output names. I think we should re-generate this file?

**Review by houseroad — COMMENTED** [review]
Yes, please regenerate the expect

**Comment by houseroad** [comment]
adding `--accept` option will help you regenerate the expect files.

**Comment by supriyar** [comment]
> adding `--accept` option will help you regenerate the expect files.

@houseroad done, all test pass now. Please review.

**Pull request closed without merging**
