### PR TITLE
Add HIP/ROCm version to collect_env.py

### PR DESCRIPTION
**Pull request by t-vi**
This adds HIP version info to the `collect_env.py` output.

### CODE REVIEW

**Comment by t-vi** [comment]
@jeffdaily Would this still be useful?

**Review by zou3519 — APPROVED** [review]

**Comment by zou3519** [comment]
@t-vi Sorry, this fell off my radar. Could you rebase this so that we could get some CI signal on this again?

Do you have an AMD machine / could you paste some sample output from the script as well please?

**Comment by jeffdaily** [comment]
Yes, still useful.  Thank you.  LGTM.  Verified on my own systems.

**Comment by jeffdaily** [comment]
Sample output from one of my systems:
```
Collecting environment information...
PyTorch version: 1.7.0a0+9ddd3df
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 3.7.20315-077bcfa0

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 11.0.0 (/src/external/llvm-project/clang ee4e4ebbadcc8ea14ce99e34ed31ab31e94827ac)
CMake version: version 3.14.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: N/A
GPU models and configuration: Device 66a1
Nvidia driver version: Could not collect
cuDNN version: N/A
HIP runtime version: 3.18.2
MIOpen runtime version: 2.6.0

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.0a0+a9603c7
[pip3] torchvision==0.8.0a0+a4736ea
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      217
[conda] mkl-include               2020.1                      217
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.1.0            py36h23d657b_0
[conda] mkl_random                1.1.1            py36h0573a6f_0
[conda] numpy                     1.18.5           py36ha1c710e_0
[conda] numpy-base                1.18.5           py36hde5b4d6_0
```

**Comment by t-vi** [comment]
ROCm PyTorch:
```
Collecting environment information...
PyTorch version: 1.7.0a0+98ad5ff
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 3.7.20315-077bcfa0

OS: Debian GNU/Linux bullseye/sid (x86_64)
GCC version: (Debian 10.2.0-6) 10.2.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: N/A
GPU models and configuration: Vega 20 [Radeon VII]
Nvidia driver version: 450.66
cuDNN version: N/A
HIP runtime version: 3.18.2
MIOpen runtime version: 2.6.0

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] pytorch-transformers==1.2.0
[pip3] torch==1.7.0a0+98ad5ff
[pip3] torchvision==0.8.0a0+1aef87d
[conda] Could not collect
```
CUDA PyTorch on the same box (slightly different commit):
```
PyTorch version: 1.7.0a0+6b3f335
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux bullseye/sid (x86_64)
GCC version: (Debian 10.2.0-6) 10.2.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 450.66
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] pytorch-transformers==1.2.0
[pip3] torch==1.7.0a0+98ad5ff
[pip3] torchvision==0.8.0a0+1aef87d
[conda] Could not collect
```

**Pull request closed without merging**
