### PR TITLE
Remove print_test_stats, test_history, s3_stat_parser

### PR DESCRIPTION
**Pull request by clee2000**
Pritam Damania no longer uses it (and is no longer with FB), and I don't know who else has interest in this

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Do you mind deleting associated files as well?
Also, it would probably be good to advertise how to check test time increases using HUD

**Review by huydhn — APPROVED** [review]
This is nice to be able to deprecate this part!  Thank you for following up on this

**Review by ZainRizvi — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
