### PR TITLE
Populate Canonical Aten Ops (Batch 2)

### PR DESCRIPTION
**Pull request by SherlockNoMad**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #90456

acos
argmax
argmin
acosh
asinh
atanh
asin
atan
logical_not
logical_and
logical_or
cos
cosh
empty_strided
full
isnan
sin
sinh
scatter_reduce.two
bitwise_xor.Tensor
sign
fmod.Tensor
remainder.Tensor
pow.Tensor_Tensor
is_inf
ne.Scalar
ne.Tensor
eq.Tensor
ge.Tensor
le.Tensor
gt.Tensor
lt.Tensor

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
@SherlockNoMad, the canonical tag got called out in https://github.com/pytorch/pytorch/pull/90029 as it is not tested at all. How can we ensure that the canonical tag gets kept up to date and is useful going forward? Some sort of test for inclusion is necessary or people will just randomly forget to add the tag.

**Comment by SherlockNoMad** [comment]
> @SherlockNoMad, the canonical tag got called out in #90029 as it is not tested at all. How can we ensure that the canonical tag gets kept up to date and is useful going forward? Some sort of test for inclusion is necessary or people will just randomly forget to add the tag.

I am getting questions from venders asking where to find the complete list of canonical aten opset. We should publish this into an autogen doc via some kind of doc-gen. Any thoughts on this? 

After seeding the first version of the opset, I don't expect to see too drastic change, as we hope this opset to be relative stable. Adding an op to the canonical aten opset would be by demand. So I am not sure what's the "test for inclusion" you had in mind? 

As canonical aten opset will be used for export, I do think we need some test for the BC properties, but we need to settle on the BC requirement first. 

cc @suo

**Comment by ezyang** [comment]
> I am getting questions from venders asking where to find the complete list of canonical aten opset. We should publish this into an autogen doc via some kind of doc-gen. Any thoughts on this?

Sure, that sounds easy enough to do. If you want it to show up in docs.pytorch.org need to add something to that docs build process to generate the rst file you want to compile

> So I am not sure what's the "test for inclusion" you had in mind?

I think this is mostly, the tags.yaml description seems to imply that any op that can be leftover after aten lowering is canonical. But we will choose not to add obscure ops to this set: there is human judgment here.

**Comment by SherlockNoMad** [comment]
@pytorbot merge -g

**Pull request closed without merging**
