### PR TITLE
Add additional tests for view slice tensors

### LINKED ISSUE #83995: RuntimeError: dst.nbytes() >= (dst.storage_offset() * dst.element_size()) INTERNAL ASSERT FAILED at "/Users/davidlaxer/pytorch/aten/src/ATen/native/mps/operations/Copy.mm":130, please report a bug to PyTorch.
### 🐛 Describe the bug

This assertion is being raised:
```
TORCH_INTERNAL_ASSERT(dst.nbytes() >= (dst.storage_offset() * dst.element_size()));
```
in 

~/pytorch/aten/src/ATen/native/mps/operations/Copy.mm
```
import torch

NUM_SAMPLES=60
s = (0,1)

X = torch.rand(8000, 3, dtype=torch.float32, device='mps')
idx = torch.randint(0, X.shape[0], (1,)).repeat(len(s))
pts = torch.randint(0, X.shape[0], (NUM_SAMPLES, X.shape[1]))

pts[:, s] = idx
actual_pts = torch.zeros(NUM_SAMPLES, X.shape[1], dtype=torch.float)

for i in range(NUM_SAMPLES):
    for j in range(X.shape[1]):
        actual_pts[i,j] = X[pts[i,j],j]

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [20], in <cell line: 1>()
      1 for i in range(NUM_SAMPLES):
      2     for j in range(X.shape[1]):
----> 3         actual_pts[i,j] = X[pts[i,j],j]

RuntimeError: dst.nbytes() >= (dst.storage_offset() * dst.element_size()) INTERNAL ASSERT FAILED at "~/pytorch/aten/src/ATen/native/mps/operations/Copy.mm":130, please report a bug to PyTorch. 
```

### Versions

% python collect_env.py 
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 12.5.1 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] torch==1.13.0a0+gitb2ddef2
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.14.0a0+a61e6ef
[conda] blas                      1.0                         mkl    anaconda
[conda] captum                    0.5.0                         0    pytorch
[conda] mkl                       2021.4.0           hecd8cb5_637    anaconda
[conda] mkl-service               2.4.0           py310hca72f7f_0    anaconda
[conda] mkl_fft                   1.3.1           py310hf879493_0    anaconda
[conda] mkl_random                1.2.2           py310hc081a56_0    anaconda
[conda] numpy                     1.22.3          py310hdcd3fac_0    anaconda
[conda] numpy-base                1.22.3          py310hfd2de13_0    anaconda
[conda] pytorch                   1.12.1                 py3.10_0    pytorch
[conda] torch                     1.13.0a0+git09157c7          pypi_0    pypi
[conda] torchmetrics              0.9.3              pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.14.0a0+a61e6ef          pypi_0    pypi

cc @kulinseth @albanD

### PR DESCRIPTION
**Pull request by DenisVieriu97**
Fixes https://github.com/pytorch/pytorch/issues/83995 and https://github.com/pytorch/pytorch/issues/84489

### CODE REVIEW

**Review by kulinseth — APPROVED** [review]

**Comment by kit1980** [comment]
@DenisVieriu97 Are you still interested in merging this? Can you sign the CLA and resolve the merge conflicts?

**Comment by kulinseth** [comment]
> @DenisVieriu97 Are you still interested in merging this? Can you sign the CLA and resolve the merge conflicts?

We are waiting on our CLA to get approved . We will merge it as soon as after that

**Pull request closed without merging**
