### PR TITLE
Add new Macro to count ops and time lazy tracing

### PR DESCRIPTION
**Pull request by JackCaoG**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by albanD** [comment]
I guess this is used outside of core? Why not define it there?
Also not sure who to add as a reviewer for triage purposes.

**Comment by JackCaoG** [comment]
Oh the main reason is that this Macro will be used as part of the codegen for XLA ops(check https://github.com/pytorch/xla/pull/5757/files#diff-67a498f0b113338bc2d470430af2786ee2235b92ba7f587d9cd7e1edad2f0746R118). If I define this macro in a XLA specified file I need to add functionality to lazy tensor codegen(also lives upstream) to include non-upstream header. 

Since I kind of have to change the upstream code I pick the easier one. Jiewen and I maintain the lazy upstream so I think having him as reviewer would be sufficient for triage purposes?

**Review by albanD — COMMENTED** [review]
Ok, leaving as-is then.
I would suggest using this macro in core to reduce the risk of it being broken without realizing until it hits xla CI.

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Review by alanwaketan — COMMENTED** [review]
Actually, why can't we just use TORCH_LAZY_TIMED directly?

**Comment by JackCaoG** [comment]
because I also want to increment the counter. TIMED sounds like it only time the section

**Pull request closed without merging**
