### PR TITLE
SymIntify prod_backward

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #120776

Fixes https://github.com/pytorch/pytorch/issues/120608

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by ezyang** [comment]
I'm not really sure why our preexisting tests didn't catch this, maybe there's no prod opinfo

**Review by albanD — APPROVED** [review]
That was easy :p

**Comment by ezyang** [comment]
This is actually not sufficient to eliminate the specialization

**Pull request closed without merging**
