### PR TITLE
Substitute unbacked symints in expressions

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137020

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

Differential Revision: [D63647095](https://our.internmc.facebook.com/intern/diff/D63647095)

### CODE REVIEW

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D63647095).

**Review by ezyang — APPROVED** [review]
Test would be good. I wonder if we should apply this natively inside size_hint.....

**Review by houseroad — COMMENTED** [review]
Can we add some unittest?

**Comment by eellison** [comment]
Yes, will add test.

cc @ezyang  - I think that could make sense. If someone calls with `size_hint(x // 256, 8092)` and x is already bound to 8092, I guess we just ignore the hint on the output ? i'm just going to land this first because is blocking but we could do something like that in follow up.

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D63647095).

**Pull request closed without merging**
