### PR TITLE
Revert "Revert "[Profiler] Move python tracing to unified event type (Part 2)""

### PR DESCRIPTION
**Pull request by robieta**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #79175
* __->__ #79173

This reverts commit 4305f8e9bda34f18eb7aacab51c63651cfc61802.

replace TEST_CUDA with torch.has_cuda

### CODE REVIEW

**Comment by robieta** [comment]
https://github.com/pytorch/pytorch/pull/79131 but in ghstack. (I couldn't see any documentation for ghstack-ifying a PR after the fact.)

**Comment by ezyang** [comment]
why not land these two in one go

**Comment by robieta** [comment]
> why not land these two in one go

Just to make it easier to review. This one is pretty big but the actual change is trivial so I figured I'd keep all that complexity isolated. But I do plan to land them together. (Which is why I wanted to `ghstack` them in the first place.)

**Review by ezyang — APPROVED** [review]

**Comment by robieta** [comment]
The cuda failure is a flake.

**Pull request closed without merging**
