### PR TITLE
[inductor] Fix ops.scan for non-commutative operators

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #126633

`tl.associative_scan` supports non-commutative combine functions but `tl.reduce`
doesn't. This effects non-persistent scans, where we use the reduction from
the previous loop iterations as the base for future iterations.

Here I work around this by taking the last element of the scan output and using
that as the reduced value. This is done using a trick where we create a
mask that is 1 at the desired element and 0 elsewhere, then sum over it.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by Chillee — APPROVED** [review]

**Review by lezcano — APPROVED** [review]
Oh well. We should eventually fix the non-commutativity of `tl.reduce`, should be quite straightforward. With that fixed, we could pick up the last element reducing with
```python
def last(a, b):
  return b
```
Of course, the real fix would be to expose 1-element slices over a dimension in triton.

**Comment by jeffdaily** [comment]
This newly-added test is failing ROCm.  Will attempt to skip it for now.

**Pull request closed without merging**
