### PR TITLE
skip hf_T5_generate in dynamic shape test

### PR DESCRIPTION
**Pull request by jiayisunx**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #121129

As reported in https://github.com/pytorch/pytorch/issues/119434, `hf_T5_generate` failed with dynamic shape testing, we propose to skip the dynamic batch size testing of this model in this PR.

* Error msg is
```
  File "/home/jiayisun/pytorch/torch/_dynamo/guards.py", line 705, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
  File "/home/jiayisun/pytorch/torch/fx/experimental/symbolic_shapes.py", line 3253, in produce_guards
    raise ConstraintViolationError(
torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (L['inputs_tensor'].size()[0])! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of RelaxedUnspecConstraint(L['inputs_tensor'].size()[0]) are valid because L['inputs_tensor'].size()[0] was inferred to be a constant (4).
```

* Root Cause is
This error happens while creating guard for this [model script line](https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L561): `scores += position_bias_masked`
I run it with TORCH_LOGS="+dynamic" and got the key line : `I0305 00:21:00.849974 140376923287424 torch/fx/experimental/symbolic_shapes.py:3963] [6/0_1] eval Eq(s0, 4) [guard added] at miniconda3/envs/pt2/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:561 in forward (_refs/__init__.py:403 in _broadcast_shapes)`
The reason for this error is that the batch dimension of `inputs_tensor` in the dynamic batch size test is marked as dynamic shape `s0`, so the batch dimension of `scores` generated by a series of operations with `inputs_tensor` is also `s0`. However, because the function of creating `attention_mask` is not in Dynamo but in python. The batch dimension of `attention_mask` is the real shape `4`, and the batch dimension of `position_bias_masked` generated by a series of operations with `attention_mask` is also the real shape `4`, not the dynamic shape `s0`. The current line of `scores += position_bias_masked` requires creating a guard and check whether the batch dimension of `scores` is always equal to the batch dimension of `position_bias_masked`, Eq(s0, 4), the error happens.
So the root cause of this error is that the function of creating `attention_mask` not in Dynamo but in python. The reason why the function of `attention_mask` not in Dynamo is that Dynamo has a graph break on this function (happened in the [model script line](https://github.com/huggingface/transformers/blob/main/src/transformers/generation/utils.py#L476): `is_pad_token_in_inputs = (pad_token_id is not None) and (pad_token_id in inputs)`) due to the following error:
`torch._dynamo.exc.Unsupported: Tensor.item`

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by leslie-fang-intel — APPROVED** [review]

**Review by jgong5 — COMMENTED** [review]
Is it a real issue that we should fix instead of changing the test to avoid reporting it? From the code you pointed, the shape of the returned `attention_mask` still depends on the `inputs`, may I know why the batch size is concrete in this case?

**Comment by jiayisunx** [comment]
> Is it a real issue that we should fix instead of changing the test to avoid reporting it? From the code you pointed, the shape of the returned `attention_mask` still depends on the `inputs`, may I know why the batch size is concrete in this case?

because a graph break happened in the function of creating` attention_mask`, and `attention_mask` was not created in Dynamo but in Python, so the batch size of `attention_mask` is the real shape `4`, not the dynamic shape `s0`.

**Comment by jgong5** [comment]
> > Is it a real issue that we should fix instead of changing the test to avoid reporting it? From the code you pointed, the shape of the returned `attention_mask` still depends on the `inputs`, may I know why the batch size is concrete in this case?
> 
> because a graph break happened in the function of creating` attention_mask`, and `attention_mask` was not created in Dynamo but in Python, so the batch size of `attention_mask` is the real shape `4`, not the dynamic shape `s0`.

I understand the cause of the error but why is it an expected failure with dynamic shapes and why we have to change the tests to static shapes to pass them? For this case with dynamic shapes, if there is a guard failure, should we recompile? cc @ezyang for more insights..

**Comment by ezyang** [comment]
The test is testing something a little more stringent: it is requiring that we compile dynamic batch size and failing if it fails to end up being dynamic. The test itself doesn't actually vary shapes, so, e.g., automatic dynamic shape doesn't apply.

So it makes sense that graph breaks can mess things up, because when we graph break we lose information about mark_dynamic, and that can cause specializations.

@eellison has advocated we should just actually vary sizes in the benchmark, and I tend to agree that this is probably the right call. I don't know if I have an opinion about this particular skip for now.

**Comment by jiayisunx** [comment]
> The test is testing something a little more stringent: it is requiring that we compile dynamic batch size and failing if it fails to end up being dynamic. The test itself doesn't actually vary shapes, so, e.g., automatic dynamic shape doesn't apply.
> 
> So it makes sense that graph breaks can mess things up, because when we graph break we lose information about mark_dynamic, and that can cause specializations.
> 
> @eellison has advocated we should just actually vary sizes in the benchmark, and I tend to agree that this is probably the right call. I don't know if I have an opinion about this particular skip for now.

Hi @ezyang , I see that currently the benchmark still uses mark_dynamic way to do dynamic testing. If it will not be changed to use actual dynamic sizes in the short term, maybe we can skip this model first?

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
