### PR TITLE
Remove more of caffe2

### PR DESCRIPTION
**Pull request by r-barnes**
Fixes #ISSUE_NUMBER

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal @albanD

### CODE REVIEW

**Review by malfet — APPROVED** [review]
submodule update sounds like a mistake, but otherwise LGTM

**Comment by DanilBaibak** [comment]
@r-barnes, sorry, I need to revert your PR because it [broke the internal build](https://www.internalfb.com/diff/D57776502). There is also [an issue to re-import the diff](https://www.internalfb.com/sandcastle/workflow/2427440199155657577/artifact/actionlog.2427440199213048130.stdout.1?selectedLines=71-72-1-1). Let's rebase the PR and merge it again.

**Pull request closed without merging**
