### PR TITLE
add whitelisted clang-format checks

### PR DESCRIPTION
**Pull request by suo**
This PR adds clang-format automation:
- It only checks on whitelisted files, so we can enable incrementally without noise
- There is a pre-commit hook provided that will do the same check, plus prompt users to apply the clang-format changes (no change is made without the user agreeing).

My plan is to migrate over whole files at a time, clang-formatting them and then adding them to the whitelist. Doing it this way should avoid too many merge pains (the most you'll have to is run clang-format on the affected file before rebasing).

### CODE REVIEW

**Review by apaszke — COMMENTED** [review]
Y tho. I’d really like to understand what kind of benefits do we expect from enforcing clang format vs the pain it adds.

**Comment by soumith** [comment]
@apaszke maybe context in https://github.com/pytorch/pytorch/pull/15026#issuecomment-446403814 will help?

**Comment by apaszke** [comment]
All your points make sense, but they don't seem to support *enforcing* the lint (as opposed to usage by people who really want to do so):

1. I understand that FB people are familiar with FB style, but not enforcing the lint doesn't mean they can't write code that conforms to it, so I don't see how this is a downside for them. And please don't tell me that FB employees can only read FB-formatted code... I agree that compiler.cpp is a mess, but I'd argue that the bigger problem is not the syntax, but the actual implementation which is an almost infinite spaghetti of methods with unclear semantics. No linter will fix that.
2. This is the argument I head so often, but I can't recall even a single PR that would be blocked from merging because someone was annoyed with formatting. I can recall dozens that were blocked from merge because flake8 (or clang-format if this was to land) was failing. Basically, enforcing lint is the ultimate "annoying reviewer" that nitpicks every single formatting "mistake" you've made.
3. That's fair, but again -- not *enforcing* the lint, doesn't prevent you from using it on the code you write! That's the best part!

About the pains you listed:
- This is simply false. clang-format can terribly mess up some files, and you should be careful about the changes you accept. If you were to run this on a comment [like this](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/tree_views.h#L12-L79), it would remove the leading whitespace, turning this nicely formatted list into a jumbled mess of random characters. It's not a tool you can run without any supervision.
- Everything that needs to be set up before you can make *any* contribution is an annoyance and an unnecessary barrier of entry to the community. You can say that about every tool, but they start to accumulate. Don't extend the environment to use to "most people" because it's unlikely to be true.

**Comment by apaszke** [comment]
And just to be clear - as much as clang-tidy can be annoying, at least it has effect of guarding against some anti-patterns and possible unwanted performance regressions (I've been bugging people about `std::move`s in reviews myself). clang-format is entirely different because it corresponds to exactly rejecting good patches that people write simply because they have one unnecessary space in a funny place...

**Comment by suo** [comment]
Yeah, the only good reason for enforcing the lint is to avoid unrelated autoformatting diffs in PRs. This could be largely addressed if we (by we I mean core contributors) all agreed to use clang-format ourselves.

What do you think about the following: 
- I will put up a PR to clang-format everything (including adding guards in places where it would mess up formatting like tree_views and register_prim_ops).
- We keep the precommit hook and whitelist, but leave it out of CI
- We "encourage" core contributors to install the precommit hook.

I think that gets us the majority of the way there without being a drag on first-time or infrequent contributions.

**Comment by apaszke** [comment]
No, I don't see what you proposed gets us anywhere. You'll still get plenty of unnecessary whitespace changes, after a core dev touches a PR from a non-core dev who hasn't used clang-format. That doesn't buy us anything really.

**Comment by suo** [comment]
I think you're overstating the problem here. Say we clang-format `torch/csrc/jit`. Out of the last [1000 commits](https://gist.github.com/suo/901c059bc26008d89b6597b2d9e6a0ea)*, ~947 were made by "core contributors" (defined as people who work on pytorch or caffe2/FB). An additional 32 were made by "close collaborators" (people we know well and work with, like T-vi and Mike Ruberry), whom I would feel comfortable asking for a quick clang-format run.  

That leaves only 21 commits that could introduce whitespace changes on future PRs, the majority of which look like spelling/whitespace changes anyway. So clang-format + core contributor/collaborator coverage buys us quite a bit.

At a high level, I'd rather be biased toward trying it and see if extra whitespace is really a problem in practice once we're clang-format clean. We can always turn it off, but it's going to be hard to find another time when this change is less disruptive (due to holidays).

[*] Fun aside, the 1000th oldest commit when ran that was ["JIT IR including use-def chains and updated comments"](https://github.com/pytorch/pytorch/commit/1325fa511c997bad925c1f3721a85688c74e6be0).

**Comment by soumith** [comment]
let's go ahead and do this and see how it goes.
If it becomes a big friction / pain in the workflow, we can undo the workflow.

**Review by soumith — APPROVED** [review]

**Pull request closed without merging**
