### PR TITLE
ignore generated caffe2 docs and virtualenvs

### PR DESCRIPTION
**Pull request by JoelMarcey**

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by SsnL** [comment]
Hey sorry guys. Flagging this one. `/doc/caffe2` actually contains commited files! So currently if you do a `setup.py clean` on master (without building) it removes those files.

**Comment by ezyang** [comment]
I'm reverting this diff

**Comment by JoelMarcey** [comment]
Ah - sorry. 

Aren't at least some of those files in `/docs/caffe2` generated though? We should ignore those, right?

**Comment by SsnL** [comment]
I don’t know how to gen caffe2 docs. But please use a pattern (or patterns)
that only matches the generated files, not the existing ones.

We should really have a test on this.

**Comment by JoelMarcey** [comment]
> I don’t know how to gen caffe2 docs. But please use a pattern (or patterns)
that only matches the generated files, not the existing ones.

Yeah, I thought they were all generated looking at how the build works. Must have been my mistake, or the build is incorrect - I assume the former. I would have used a pattern, of course.

**Pull request closed without merging**
