### PR TITLE
Fix conjugate bit discrepancy in composite compliance

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #75805
* __->__ #75830

When testing composite compliance, the conj bit and neg bit are not
propagated to the wrapper tensor. This leads to problems when a
composite operator has two paths depending on whether one of these
bits are set, since the non-conjugated path will always be taken.

For example, `at::real` effectively does
```cpp
view_as_real(tensor.is_conj() ? tensor.conj() : tensor)
```
which will never call `conj()` because the `CompositeCompliantTensor`
never has has the conj bit set. The result is `view_as_real` fails
when `r.elem` does have the conj bit set.

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]
LGTM. We probably want a better long-term way to fix this for wrapper tensor subclasses

**Comment by albanD** [comment]
cc @ezyang this is part of the larger work to virtualize everything (can't find the issue right now).

**Comment by ezyang** [comment]
eyup. Would be better to virtualize this. ok to land this for now but reference to issue would be helpful

**Comment by peterbell10** [comment]
Could someone link the issue your discussing so I can add it to the PR?

**Comment by zou3519** [comment]
I think they're talking about https://github.com/albanD/subclass_zoo/issues/21

**Comment by zou3519** [comment]
Just checking... who is on the hook for merging this? I can help import/merge, I just wasn't sure what the current procedures are

**Pull request closed without merging**
