### PR TITLE
Raise error when perf test result is NaN

### PR DESCRIPTION
**Pull request by yf225**
Currently one of our GPU perf tests `test_gpu_speed_mnist` reports NaN after this commit (https://github.com/pytorch/pytorch/pull/8018), and we didn't have the logic in place to raise error when this happens. This PR fixes the problem and will also update the baseline properly even if its previous value is NaN.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
sure why not

**Comment by yf225** [comment]
When this passes (https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-cuda8-cudnn6-py3-trigger/23209/) we can merge this PR.

**Pull request closed without merging**
