### PR TITLE
Pass tensor object (self) to registered hook

### PR DESCRIPTION
**Pull request by timmeinhardt**
This PR addresses the issue #10683 and passes the tensor object itself to the registered hook function. To ensure backwards compatibility the tensor object is only passed if the signature of the hook function indicates two arguments. Otherwise the old behaviour works as expected.

Currently this PR fails for Python 2. How do you deal with this at the moment?

### CODE REVIEW

**Comment by soumith** [comment]
this looks good. If you could add a test in test_nn.py for this, we should be good to merge. (thank you!)

**Comment by timmeinhardt** [comment]
I just added a test to `test_autograd.py`. I think there it makes more sense.

**Comment by soumith** [comment]
it's failing python 2.7 tests.

```
15:20:40 ======================================================================
15:20:40 ERROR: test_retain_grad_cycle (__main__.TestAutograd)
15:20:40 ----------------------------------------------------------------------
15:20:40 Traceback (most recent call last):
15:20:40   File "test_autograd.py", line 494, in test_retain_grad_cycle
15:20:40     z = run_test()
15:20:40   File "test_autograd.py", line 487, in run_test
15:20:40     y.retain_grad()
15:20:40   File "/opt/python/2.7/lib/python2.7/site-packages/torch/tensor.py", line 210, in retain_grad
15:20:40     self.register_hook(retain_grad_hook)
15:20:40   File "/opt/python/2.7/lib/python2.7/site-packages/torch/tensor.py", line 140, in register_hook
15:20:40     if len(inspect.signature(hook).parameters) == 2:
15:20:40 AttributeError: 'module' object has no attribute 'signature'
```

**Comment by soumith** [comment]
you might have to `if python 2` then use getargspec, `else` use signature: https://stackoverflow.com/questions/847936/how-can-i-find-the-number-of-arguments-of-a-python-function

**Review by apaszke — CHANGES_REQUESTED** [review]
I don't think adding this is worth all the extra complexity with inspecting argument signatures (it's expensive!). Can't you just capture the tensor in a closure you use as a hook if you really need it?

**Comment by timmeinhardt** [comment]
@apaszke I agree that the backwards compatibility introduces quite a bit of extra complexity that seems excessive for such a small feature and indeed, my particular problem could be solved with a closure function. But I think for reasons of consistency (see `Module.register_forward_hook` and `Module.register_backward_hook`) the object that registers the hook (in this case the `Tensor` object) should be passed to the hook itself. And from my understanding, registering and checking the signatures is a one time event which doesn't introduce expensive overhead to the general longterm runtime.

**Pull request closed without merging**
