### PR TITLE
Synchronize before change cuda stream (#82050)

### LINKED ISSUE #82050: Need synchronize when change stream
### 🐛 Describe the bug

I think there should be a synchronize before change cuda stream, otherwise data may not initialized if the kernel(like randn) on the default stream not finished.
https://github.com/pytorch/pytorch/blob/a3fc076f22aa835d54dce423a4ec237bfdc0d704/torch/testing/_internal/common_utils.py#L1345

### Versions

Collecting environment information...
PyTorch version: 1.12.0a0+bd13bc6
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.3
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-92-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.6.124
GPU models and configuration:
GPU 0: NVIDIA A100-SXM-80GB

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] nvidia-dlprof-pytorch-nvtx==1.8.0
[pip3] pytorch-lamb==1.0.0
[pip3] pytorch-lightning==1.5.10
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.12.0a0+bd13bc6
[pip3] torch-tensorrt==1.1.0a0
[pip3] torchmetrics==0.9.2
[pip3] torchtext==0.13.0a0
[pip3] torchvision==0.13.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.22.3           py38h1d589f8_2    conda-forge
[conda] nvidia-dlprof-pytorch-nvtx 1.8.0                    pypi_0    pypi
[conda] pytorch-lamb              1.0.0                    pypi_0    pypi
[conda] pytorch-lightning         1.5.10                   pypi_0    pypi
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.12.0a0+bd13bc6          pypi_0    pypi
[conda] torch-tensorrt            1.1.0a0                  pypi_0    pypi
[conda] torchmetrics              0.9.2                    pypi_0    pypi
[conda] torchtext                 0.13.0a0                 pypi_0    pypi
[conda] torchvision               0.13.0a0                 pypi_0    pypi

cc @ngimel

### PR DESCRIPTION
**Pull request by wchen61**
Summary:
Fixes https://github.com/pytorch/pytorch/issues/82050

Need synchronize before change cuda stream

### CODE REVIEW

**Comment by ngimel** [comment]
This is a context manager for the whole test, and tests should be self-contained. There should be no work performed before the test that we should be waiting for. I don't think this PR is needed.

**Comment by wchen61** [comment]
> This is a context manager for the whole test, and tests should be self-contained. There should be no work performed before the test that we should be waiting for. I don't think this PR is needed.

Hi, @ngimel. I think this [initialize](https://github.com/pytorch/pytorch/blob/db0e121b46a03808f77b718d2bda3bbbffa05d44/test/test_cuda.py#L80) in TestCuda  will happened before cuda stream change, without synchronize will cause the data not ready when use it.

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
