### PR TITLE
[quant][fx] Cleanup unused to_fp16 check code in lowering

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #74969

Summary:
We can remove the check for fp16 ops now since we confirmed that fp16 ops are not
used

Test Plan:
python test/test_quantization.py TestQuantizeFx
python test/test_quantization.py TestQuantizeFxOps

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D35258695](https://our.internmc.facebook.com/intern/diff/D35258695)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35258695).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35258695).

**Review by andrewor14 — APPROVED** [review]

**Comment by malfet** [comment]
Reverting as it broke plethora of tests, for example: https://github.com/pytorch/pytorch/runs/5766517514?check_suite_focus=true

**Comment by jerryzh168** [comment]
I see, it did not show up because there was some problem with the CI...maybe I should test manually first

**Pull request closed without merging**
