### PR TITLE
[jit] Reduce refcounting of Types

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #66286
* #66282
* __->__ #65345

FooType::get() can return a const reference. Inconveniently, converting shared_ptr<FooType> to shared_ptr<Type> requires a copy & refcount bump, so to properly take advantage of this in unshapedType() we need to take a const Type& in isSubtypeOf(), which is good practice anyway -- don't require a shared_ptr if you don't need to take ownership.

Differential Revision: [D31027361](https://our.internmc.facebook.com/intern/diff/D31027361/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D31027361/)!

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

### CODE REVIEW

**Review by suo — APPROVED** [review]

**Comment by albanD** [comment]
Out of curiosity what is the perf implication of this kind of change?

**Review by eellison — COMMENTED** [review]
Should we define a `isSubtypeOfExt(const TypePtr& rhs ) ` on the parent class that invokes `const Type& rhs` ? Not sure if we consider this Bc-breaking or not

**Comment by eellison** [comment]
@swolchok I think you need access of the type to instantiate IValue inputs in C++

**Comment by swolchok** [comment]
> Out of curiosity what is the perf implication of this kind of change?

check out the phabricator version of the diff for more context.

**Pull request closed without merging**
