### PR TITLE
[CI] Enable UCC in CI

### PR DESCRIPTION
**Pull request by Aidyn-A**
UCC was temporarily disabled in #98832. This PR re-enables it with the necessary fix. 

cc @malfet @seemethere @pytorch/pytorch-dev-infra

### CODE REVIEW

**Comment by DuanBoomer** [comment]
Hi can you please elaborate what is a UCC. I don't seem to know about it.

**Comment by Aidyn-A** [comment]
@DuanBoomer UCC is [unified collective communication library](https://github.com/openucx/ucc) for used for parallel distributed training.

**Comment by Aidyn-A** [comment]
cc @atalman

**Review by atalman — APPROVED** [review]
LGTM

**Comment by Aidyn-A** [comment]
Hmm, looks like rocm is broken:
```
./simple-torch-test: error while loading shared libraries: libhipsolver.so.0: cannot open shared object file: No such file or directory
```
Shall I force-merge it?

**Pull request closed without merging**
