### PR TITLE
Add cuda status checks to FA templates

### PR DESCRIPTION
**Pull request by drisspg**
# Summary
cuda status checks were accidentely removed on latest update

cc @cyyever

### CODE REVIEW

**Comment by Skylion007** [comment]
Was the PR that overwrite this fix from an upstream source like Flash Attention or XFormers? If so, you should submit a PR up there too.

**Review by Skylion007 — APPROVED** [review]

**Comment by drisspg** [comment]
@Skylion007 yup great idea going to send PR against flash today

**Pull request closed without merging**
