### PR TITLE
[MPS] Support for median with dim

### LINKED ISSUE #87220: [MPS] Add support for aten::median for MPS backend
### 🐛 Describe the bug

First time contributors are welcome! 🙂
Add support for [aten::median](https://pytorch.org/docs/stable/generated/torch.median.html) for MPS backend. Generic support for adding operations to MPS backend is captured here: https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend

### Versions

N/A

cc @kulinseth @albanD @malfet @razarmehr @abhudev

### PR DESCRIPTION
**Pull request by Raman-Kumar**
## Summary ⚡

**Aim**: Add support for aten::median for MPS backend (Fixes #87220)

This is fresh clean PR from the previous [PR](https://github.com/pytorch/pytorch/pull/88554)

- Implementing the new median function in aten/src/ATen/native/mps/operations/ReduceOps.mm
- Adding it to aten/src/ATen/native/native_functions.yaml
- Adding it to existing test_median

### **this will works like this** 🪶 
median of entire input tensor on MPS 
`torch.median(mps_inputTensor)`
median of along a dim 
`torch.median(mps_inputTensor, dim=[int], keepdim=[Bool])`

### CODE REVIEW

**Comment by Raman-Kumar** [comment]
@kulinseth 
As suggested in previous [PR ](https://github.com/pytorch/pytorch/pull/88554#discussion_r1018733952)review 

now using is_macos_13_or_newer() for query to check macOS 13+ 
also moved interface to [MPSGraphVenturaOps.h](https://github.com/pytorch/pytorch/pull/88807/files#diff-d35c5d4704e7e61fe7ad955dae4f8724e8d64ad505449bbb245c2d0df97e614b)

🧪Added test case for if median at odd place and if at even place in [test_median](https://github.com/pytorch/pytorch/pull/88807/files#diff-fdee6c1352305cfc875c3f14dc43440e2c681f8f229ef8977289bb7fbe389966R2599)

Let me know if there's anything else I should do!

**Comment by Raman-Kumar** [comment]
Hi, @kulinseth 
rebased this branch with master
some workflow waiting for approval

As suggested in previous [PR ](https://github.com/pytorch/pytorch/pull/88554#discussion_r1018733952)review 

now using is_macos_13_or_newer() for query to check macOS 13+ 
also moved interface to [MPSGraphVenturaOps.h](https://github.com/pytorch/pytorch/pull/88807/files#diff-d35c5d4704e7e61fe7ad955dae4f8724e8d64ad505449bbb245c2d0df97e614b)

🧪Added test case for if median at odd place and if at even place in [test_median](https://github.com/pytorch/pytorch/pull/88807/files#diff-fdee6c1352305cfc875c3f14dc43440e2c681f8f229ef8977289bb7fbe389966R2599)

**Review by kulinseth — APPROVED** [review]
Looks good. Thanks

**Pull request closed without merging**
