### PR TITLE
Handle exit signal in run_test.py

### PR DESCRIPTION
**Pull request by goldsborough**
Right now, when a test segfaults, we get zero signal for this. This PR checks the return value of `subprocess.Popen` to figure out the exit signal of the child process.

### CODE REVIEW

**Comment by goldsborough** [comment]
Actually doesn't work as expected yet

**Comment by apaszke** [comment]
Why is it the case that we don't get any indication? Processes that segfaulted exit with a non-zero code, so we should notice

**Comment by goldsborough** [comment]
Yeah they do exit, you just get zero information about why -- i.e. you don't get the usual `Segmentation fault`

**Review by apaszke — APPROVED** [review]

**Comment by SsnL** [comment]
This overwrites the dataloader SIGCHLD handlers, but tests for those are run in a subprocess so I guess it is fine....

**Comment by goldsborough** [comment]
Wait, this version isn't installing any signal handler?

**Comment by goldsborough** [comment]
I haven't updated the description :)

**Comment by SsnL** [comment]
@goldsborough haha I see. It's all fine then. :)

**Pull request merged**
