### PR TITLE
Add tutorial to docs

### PR DESCRIPTION
**Pull request by chsasank**
Hi,

I've used [sphinx-gallery](http://sphinx-gallery.readthedocs.io/en/latest/) to make [notebook styled examples](http://sphinx-gallery.readthedocs.io/en/latest/tutorials/plot_notebook.html#sphx-glr-tutorials-plot-notebook-py) to port ipython tutorial to sphinx documentation. I'm attaching a few screenshots to preview this without building it.

screen shot 2017-02-18 at 2 25 20 pm
screen shot 2017-02-18 at 2 25 36 pm
screen shot 2017-02-18 at 2 25 59 pm

I think this is way more approachable than a notebook. Advantage is that you can still download a notebook with the code and the text! It's also much more maintainable.

If you like it, I can port rest of the tutorials like this. 

Sasank.

### CODE REVIEW

**Comment by soumith** [comment]
wow, this looks super cool!

**Comment by chsasank** [comment]
Just ported `Introduction to PyTorch for former Torchies` to sphinx. Split it into 4 sections to make a easy reading.

screen shot 2017-02-18 at 5 28 37 pm

**Comment by chsasank** [comment]
Adding DQN tutorial is tricky. It has more 'moving parts' like gym rendering. I guess I won't be able to add it without taking off some eye candy. It also talks a lot more time to run than other models.

**Comment by chsasank** [comment]
@soumith Can you please review/have someone review this?

If this PR is to be merged, I'll create a transfer learning tutorial.

Sasank.

**Comment by soumith** [comment]
Sorry for the delay. Among the maintainers, we were hotly debating on whether to merge this or not.
On the upside, tutorials will be with the docs in one place etc.
On the downside, there'll be two sets of tutorials and need double the maintenance and care.

**Comment by chsasank** [comment]
I'll list down pros and cons of the following scenario:

> Merge the tutorials to docs and retire pytorch/tutorials

Pros:
1. Tutorials and docs in one place
3. You can still download the tutorials as notebooks. [Example screenshot](https://cloud.githubusercontent.com/assets/9305875/23466349/d6e63dee-fec0-11e6-940b-82c81340cd7f.png)
2. Eye candy; easy to read.
3. Better indexing and better visibility in search engines
2. Maintenance is much easier as the py files are diffable and ipynb files are not.
3. Outputs of cells in documentation are updated automatically if you modify the py file.

Cons:
1. Existing SEO because of backlinks to ipynb tutorials will be lost. 
2. Downloaded ipynb are not very long because I've broken up the tutorials into pieces. But this can be fixed if need be. I'm not sure if this is really a con.

**Comment by chsasank** [comment]
Only tutorial that is yet to be ported is Q-learning. I think we can port that too without leaving out much.

Only problem I foresee is documentation build environment creating a problem because of [this issue](https://github.com/openai/gym/issues/462) of openai gym. But then they suggest a solution in the issue anyways.

**Pull request closed without merging**
