### PR TITLE
 [ONNX] Allow specifying only a subset of input/output names 

### PR DESCRIPTION
**Pull request by jamesr66a**
Then we can only specify the "real" names while ignoring the names for all the parameters

### CODE REVIEW

**Comment by anderspapitto** [comment]
Isn't the "real inputs" at the end? e.g. in this example https://pytorch.org/docs/master/onnx.html

**Comment by jamesr66a** [comment]
@anderspapitto I've only ever seen the real inputs at the beginning. It seems like there actually isn't a convention here :(

**Comment by jamesr66a** [comment]
```import torch

class SomeModule(torch.nn.Module):
    def __init__(self):
        super(SomeModule, self).__init__()
        self.param = torch.nn.Parameter(torch.zeros(3, 3))

    def forward(self, x):
        return torch.matmul(x, self.param)

sm = torch.jit.trace(torch.zeros(1, 2, 3))(SomeModule())

print(sm.__getattr__('forward').graph)
```

yields

```
graph(%0 : Float(1, 2, 3)
      %1 : Float(3, 3)) {
  %6 : Float(1, 2, 3) = aten::matmul(%0, %1)
  return (%6);
}
```

**Comment by jamesr66a** [comment]
Upon further inspection of the tutorial, it seems like it's incorrect. First we say:
```
dummy_input = Variable(torch.randn(10, 3, 224, 224)).cuda()
```

which makes sense for passing in 3-channel images. But then we say `actual_input_1` is `Float(1000)`, which doesn't make sense. So I think that tutorial needs to be updated and this PR is correct

**Review by anderspapitto — APPROVED** [review]

**Pull request merged**
