### PR TITLE
Implement correction argument in torch.masked.{std,var}

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #55680
* #55679
* __->__ #87118

This makes the signature of `torch.masked.std` and `var` more consistent with the global namespace variant and also updates the sample inputs to repurpose the existing `sample_inputs_std_var` inputs which fully exercise the `correction` argument. 

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]

**Comment by kit1980** [comment]
@peterbell10 should we merge this?

**Comment by peterbell10** [comment]
@kit1980 this will need to merged at the same time as the previous PR in the sack because the tests compare it against the non-masked variant. AFAIK there's no reason they can't both be merged right now though.

**Comment by kit1980** [comment]
> @kit1980 this will need to merged at the same time as the previous PR in the sack because the tests compare it against the non-masked variant. AFAIK there's no reason they can't both be merged right now though.

I see both are approved, feel free to merge when ready.

**Comment by peterbell10** [comment]
@kit1980 this has to be merged by someone from Meta because of  https://github.com/pytorch/pytorch/pull/56398#issuecomment-1287087363.

**Pull request closed without merging**
