### PR TITLE
port `sgn` to structured

### PR DESCRIPTION
**Pull request by eqy**
#55070

### CODE REVIEW

**Comment by ezyang** [comment]
This implementation is not quite correct; in particular, you are redundantly building the TensorIterator twice, once in the meta function, and second in `unary_op_impl_out`. You want your impl to look like this macro

```
#define CREATE_UNARY_TORCH_IMPL_FUNC(func)                                \
TORCH_IMPL_FUNC(func##_out) (const Tensor& self, const Tensor& result) {  \
  func##_stub(device_type(), *this);                                      \
}
```

but instead of calling the stub directly, do the dtype test to decide which stub to go to. Fortunately the TI for sgn and sign are the same so this works out fine.

**Review by ezyang — CHANGES_REQUESTED** [review]
make better

**Review by ezyang — APPROVED** [review]
thx

**Comment by eqy** [comment]
> thx

There were some CI failures complaining about unsupport gradients? not erroring out and I'm not sure if this change addresses that.

**Pull request closed without merging**
