### PR TITLE
Use CUDA DSA in ATen

### PR DESCRIPTION
**Pull request by r-barnes**
Differential Revision: D42977336

### CODE REVIEW

**Comment by xw285cornell** [comment]
qq, i recall DSA requires turning on some flag, did we do that in aten? If we don't turn on that flag, what'll happen (since we're replacing the assert to assert2). Also can you put the outcome (what are the more detailed kernel info) and what's the perf impact comparing with the original assert?

**Review by xw285cornell — APPROVED** [review]

**Comment by xw285cornell** [comment]
cc. @ngimel @ezyang if you want to take a look as well

**Review by ezyang — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
