### PR TITLE
[dynamo] Fix rst syntax for list

### PR DESCRIPTION
**Pull request by silvasean**

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by silvasean** [comment]
I'm still working out how to sign the CLA here (I work at Google -- I think something about the Linux foundation move invalidated my previous CLA or something). It sounds like we have something "in progress" to figure it out.

**Comment by silvasean** [comment]
@soumith sorry for the hold-up on the CLA. We got it figured out on our side and it should be good now. Could you merge this PR?

**Pull request closed without merging**
