### PR TITLE
Fix torch.utils.benchmark API while use privateuse1.

### PR DESCRIPTION
**Pull request by QiuKaida163**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by QiuKaida163** [comment]
@aaronenyeshi Sorry to bother. Can you help to check my pr.

**Review by aaronenyeshi — APPROVED** [review]
LGTM!

**Comment by QiuKaida163** [comment]
@aaronenyeshi Hi, sorry to bother, there is an unrelated failure, can you help me to re-run this PR? Thanks!

**Comment by aaronenyeshi** [comment]
It looks like the lint issue is specific to this PR. Please try running lintrunner, and fixing the issues.
image

**Comment by QiuKaida163** [comment]
@aaronenyeshi Hi, sorry to bother, How can I  re-run lintrunner by myself.

**Comment by colesbury** [comment]
@QiuKaida163, you need to fix the lint issues and push the change fixing those issues to your branch.

**Comment by QiuKaida163** [comment]
@aaronenyeshi @ezyang Hi, sorry to bother. There's a failed check here, However, this problem is likely not caused by my code modification. Can you help me to merge this PR.

**Comment by ezyang** [comment]
I think the lint failure is relevant to you, it arises because this file is MYPYSTRICT but you imported a file that is not strict. Is there a way to implement this change without importing torch._C. Can we perhaps import it inside a function and suppress mypy on it?

**Pull request closed without merging**
