### PR TITLE
Fix optimize_for_inference to support modules that don't have a forward method

### LINKED ISSUE #108662: torch.jit.optimize_for_inference assumes forward method
### 🐛 Describe the bug

`torch.jit.optimize_for_inference` allows to pass `other_methods=["f"]` to specify what methods/attributes to optimize. But there is no way of PREVENTING it from optimizing the `forward` method, which will then error out if the module being optimized doesn't have such method.

```python
import torch
from torch import nn

class Model(nn.Module):
    def __init__(self):
        super().__init__()
    
    def f(self, x):
        return x
    
module = Model()
traced_module = torch.jit.trace_module(module, {"f": torch.randn(3)})
torch.jit.optimize_for_inference(traced_module, other_methods=["f"])
```
Will throw:
```
---> 16 torch.jit.optimize_for_inference(traced_module, other_methods=["f"])
     17 # torch.jit.optimize_for_inference(traced_module)

/opt/conda/envs/lab42/lib/python3.10/site-packages/torch/jit/_freeze.py in optimize_for_inference(mod, other_methods)
    215         mod = freeze(mod.eval(), preserved_attrs=other_methods)
    216 
--> 217     torch._C._jit_pass_optimize_for_inference(mod._c, other_methods)
    218 
    219     return mod

RuntimeError: Method 'forward' is not defined.
```
Solving this would be in the same direction as this improvement: https://github.com/pytorch/pytorch/issues/84873

### Versions

```
Collecting environment information...
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.25.0
Libc version: glibc-2.27

Python version: 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-1088-aws-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  2
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:            7
CPU MHz:             3200.145
BogoMIPS:            4999.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] flake8==3.8.1
[pip3] msgpack-numpy==0.4.4.3
[pip3] mypy==1.1.1
[pip3] mypy-extensions==1.0.0
[pip3] mypy-protobuf==3.4.0
[pip3] numpy==1.22.4
[pip3] numpy-quaternion==2022.4.3
[pip3] numpy-stl==3.0.0
[pip3] pytorch-lightning==2.0.2
[pip3] pytorch3d==0.7.3
[pip3] torch==2.0.1+cu118
[pip3] torch-scatter==2.1.1+pt20cu118
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] efficientnet-pytorch      0.7.1                    pypi_0    pypi
[conda] msgpack-numpy             0.4.4.3                  pypi_0    pypi
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] numpy-quaternion          2022.4.3                 pypi_0    pypi
[conda] numpy-stl                 3.0.0                    pypi_0    pypi
[conda] pytorch-lightning         2.0.2                    pypi_0    pypi
[conda] pytorch3d                 0.7.3                    pypi_0    pypi
[conda] torch                     2.0.1+cu118              pypi_0    pypi
[conda] torch-scatter             2.1.1+pt20cu118          pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchvision               0.15.2+cu118             pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
```

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

### PR DESCRIPTION
**Pull request by sunghyunjun**
Fixes #108662

### CODE REVIEW

**Comment by davidberard98** [comment]
^^ rebasing over failing tests on trunk - you may need to force pull if you want to make other changes

**Comment by sunghyunjun** [comment]
@davidberard98

I have read the contribution guide, but as this is my first time contributing, I am not sure how to approach it at this stage. It would be good if you could give me some advice on how to handle CI failure or how I should proceed. thank you.

**Review by davidberard98 — APPROVED** [review]

**Pull request closed without merging**
