### PR TITLE
[1/N] Fixes clang-tidy warnings in header files

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by Skylion007** [comment]
I don't think you need ciflow/binaries for clang-tidy changes for the most part btw. Otherwise, looks good.

**Review by Skylion007 — APPROVED** [review]

**Comment by cyyever** [comment]
> I don't think you need ciflow/binaries for clang-tidy changes for the most part btw. Otherwise, looks good.

Since the header changes are extensive.

**Review by albanD — COMMENTED** [review]
Should there be some lint update to make sure we don't regress these?

**Comment by cyyever** [comment]
> Should there be some lint update to make sure we don't regress these?

In a follow-up.

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but it is failing with an internal build when -Wpessimizing-move is used' -c ghfirst

I think we should add that compiler flag `-Wpessimizing-move` to PT build and figure out a way to reland this change.  Here is the build error FYI:

```
buck-out/v2/gen/fbcode/24c04fc3eb9063ab/koski/functions_contrib/f6/batched_torchscript/__batched_torchscript__/buck-headers/koski/functions_contrib/f6/batched_torchscript/BatchedTorchScript.h:21:10: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
  return std::move(pytorchPredictor->getPredictor()->get_module());
         ^
buck-out/v2/gen/fbcode/24c04fc3eb9063ab/koski/functions_contrib/f6/batched_torchscript/__batched_torchscript__/buck-headers/koski/functions_contrib/f6/batched_torchscript/BatchedTorchScript.h:21:10: note: remove std::move call here
  return std::move(pytorchPredictor->getPredictor()->get_module());
         ^~~~~~~~~~                                              ~
1 error generated.
```

**Comment by cyyever** [comment]
@huydhn I think the error is unrelated because there is no std::move on returning values in this patch.

**Comment by huydhn** [comment]
If you reopen this one, ping me so I could reimport it.  What made me thing the failure was related because I did the same build job with this change reverted and it passed

**Comment by cyyever** [comment]
@huydhn It is possible that after the add of move operations in torch/csrc/jit/api/object.h, "copy elision" would work in BatchedTorchScript.h. It is an improvement. But I can't find BatchedTorchScript.h in OSS version and I can help change it.

**Pull request closed without merging**
