### PR TITLE
Pinning opencv to < 3.4 in conda builds

### PR DESCRIPTION
**Pull request by pjh5**

### CODE REVIEW

**Comment by pjh5** [comment]
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/conda2-ubuntu16.04-trigger-test/1194
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/conda2-macos10.13-trigger-build/1990/
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/conda3-cuda9.0-cudnn7-ubuntu16.04-trigger-build/1264/

**Comment by ezyang** [comment]
```
17:52:53 Traceback (most recent call last):
17:52:53   File "/var/folders/gp/lzg4k2w528j_4hs5f_ygkx8w00008b/T/anaconda/bin/conda-build", line 11, in <module>
17:52:53     sys.exit(main())
17:52:53   File "/var/folders/gp/lzg4k2w528j_4hs5f_ygkx8w00008b/T/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 388, in main
17:52:53     execute(sys.argv[1:])
17:52:53   File "/var/folders/gp/lzg4k2w528j_4hs5f_ygkx8w00008b/T/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 379, in execute
17:52:53     verify=args.verify)
17:52:53   File "/var/folders/gp/lzg4k2w528j_4hs5f_ygkx8w00008b/T/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 185, in build
17:52:53     need_source_download=need_source_download, config=config, variants=variants)
17:52:53   File "/var/folders/gp/lzg4k2w528j_4hs5f_ygkx8w00008b/T/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1776, in build_tree
17:52:53     notest=notest,
17:52:53   File "/var/folders/gp/lzg4k2w528j_4hs5f_ygkx8w00008b/T/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 882, in build
17:52:53     output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
17:52:53   File "/var/folders/gp/lzg4k2w528j_4hs5f_ygkx8w00008b/T/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 548, in expand_outputs
17:52:53     for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
17:52:53   File "/var/folders/gp/lzg4k2w528j_4hs5f_ygkx8w00008b/T/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 1764, in get_output_metadata_set
17:52:53     permit_unsatisfiable_variants=permit_unsatisfiable_variants)
17:52:53   File "/var/folders/gp/lzg4k2w528j_4hs5f_ygkx8w00008b/T/anaconda/lib/python2.7/site-packages/conda_build/metadata.py", line 640, in finalize_outputs_pass
17:52:53     fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
17:52:53   File "/var/folders/gp/lzg4k2w528j_4hs5f_ygkx8w00008b/T/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 290, in finalize_metadata
17:52:53     permit_unsatisfiable_variants=permit_unsatisfiable_variants)
17:52:53   File "/var/folders/gp/lzg4k2w528j_4hs5f_ygkx8w00008b/T/anaconda/lib/python2.7/site-packages/conda_build/render.py", line 113, in get_env_dependencies
17:52:53     channel_urls=tuple(m.config.channel_urls))
17:52:53   File "/var/folders/gp/lzg4k2w528j_4hs5f_ygkx8w00008b/T/anaconda/lib/python2.7/site-packages/conda_build/environ.py", line 682, in get_install_actions
17:52:53     raise DependencyNeedsBuildingError(exc, subdir=subdir)
17:52:53 conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: ['opencv ==3.1.0']
```

**Comment by pjh5** [comment]
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/conda2-ubuntu16.04-trigger-test/1195/
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/conda2-macos10.13-trigger-build/2499/
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/conda3-cuda9.0-cudnn7-ubuntu16.04-trigger-build/1773/

**Review by orionr — APPROVED** [review]

**Pull request merged**
