### PR TITLE
[2/N] Rename NCCLTraceBuffer to FlightRecorder

### PR DESCRIPTION
**Pull request by kwen2501**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #141737
* __->__ #141712
* #141648

Just name change. No behavior change.

cc @H-Huang @awgu @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by wconstab — APPROVED** [review]
its fine as-is, i was also wondering if we should rename to something like 'FlightRecorderBuffer'

**Comment by kwen2501** [comment]
Good point, how about just `FlightRecorder` then?

**Review by fduwjj — APPROVED** [review]
lgtm. Since FR is also used internally, can you please import it to fbcode and see if it breaks internal or not? Forward fix is not a good idea as I commented in your internal diff.

**Pull request closed without merging**
