### PR TITLE
[ONNX] ONNX dev branch merge 01-06-2021

### PR DESCRIPTION
**Pull request by spandantiwari**
[ONNX] ONNX dev branch merge 01-06-2021
- [ONNX] Support onnx if/loop sequence output in opset 13 - (#49270)
- Symbolic function for torch.square (#49446)
- [ONNX] Add checks in ONNXSetDynamicInputShape (#49783) …
- [ONNX] Enable export af aten::__derive_index (#49514) …
- [ONNX] Update symbolic for unfold (#49378) …
- [ONNX] Update the sequence of initializers in exported graph so that it is as same as inputs. (#49798)
- [ONNX] Enable opset 13 ops (#49612) …
- [ONNX] Improve error message for supported model input types in ONNX export API. (#50119)
- [ONNX] Add a post-pass for If folding (#49410)

### CODE REVIEW

**Comment by SplitInfinity** [comment]
Just a heads up - unless this stack is created with [`ghstack`](https://github.com/ezyang/ghstack), our tooling will squash all these commits into one. The title and body for that commit will be taken from the title of this PR and the contents of your first comment.

**Comment by spandantiwari** [comment]
> Just a heads up - unless this stack is created with [`ghstack`](https://github.com/ezyang/ghstack), our tooling will squash all these commits into one. The title and body for that commit will be taken from the title of this PR and the contents of your first comment.

Hi @SplitInfinity  - Thanks for the heads up. Is there no way to capture the commits separately? At the very least, can we put a commit message which captures the titles of main commits as sub-bullets (manually entered)?

So, a message like this:

[ONNX] ONNX dev branch merge 01-06-2021
* [ONNX] Support onnx if/loop sequence output in opset 13 - (#49270)
* Symbolic function for torch.square (#49446)
* [ONNX] Add checks in ONNXSetDynamicInputShape (#49783) …
* [ONNX] Enable export af aten::__derive_index (#49514) …
* [ONNX] Update symbolic for unfold (#49378) …
* [ONNX] Update the sequence of initializers in exported graph so that it is as same as inputs. (#49798)
* [ONNX] Enable opset 13 ops (#49612) …
* [ONNX] Improve error message for supported model input types in ONNX export API. (#50119)

**Comment by SplitInfinity** [comment]
>  Is there no way to capture the commits separately?

`ghstack` is the way.

> At the very least, can we put a commit message which captures the titles of main commits as sub-bullets (manually entered)?

Yes. Edit the contents of your first comment in this thread to include such a list, and that's what will be included in the commit message by our tooling.

**Comment by SplitInfinity** [comment]
#50237 is attempting to make a similar change to one of the commits in this stack. If that lands first (which it likely will since it's smaller), you'll have to rebase.

**Comment by spandantiwari** [comment]
> #50237 is attempting to make a similar change to one of the commits in this stack. If that lands first (which it likely will since it's smaller), you'll have to rebase.

Thanks @SplitInfinity. Now that https://github.com/pytorch/pytorch/pull/50237 has been merged, I will update this PR.

**Comment by spandantiwari** [comment]
> > #50237 is attempting to make a similar change to one of the commits in this stack. If that lands first (which it likely will since it's smaller), you'll have to rebase.
> 
> Thanks @SplitInfinity. Now that #50237 has been merged, I will update this PR.

Rebased and reconciled with latest master, including https://github.com/pytorch/pytorch/pull/50237.

**Comment by SplitInfinity** [comment]
@spandantiwari `pytorch_linux_xenial_py3_clang7_onnx_ort_test2` appears to have failed. Can you take a look?

**Comment by spandantiwari** [comment]
> @spandantiwari `pytorch_linux_xenial_py3_clang7_onnx_ort_test2` appears to have failed. Can you take a look?

Thanks @SplitInfinity, we are taking a look.

**Comment by spandantiwari** [comment]
> > @spandantiwari `pytorch_linux_xenial_py3_clang7_onnx_ort_test2` appears to have failed. Can you take a look?
> 
> Thanks @SplitInfinity, we are taking a look.
Updated PR with fix for failing test.

**Comment by spandantiwari** [comment]
@SplitInfinity - We have fixed the test failure. In the latest CI, there's a test failing, but it seems unrelated to this PR. In fact we found a couple of other PRs which are seeing the same failure (https://github.com/pytorch/pytorch/pull/50155, https://github.com/pytorch/pytorch/pull/50157), which probably points towards some unrelated issue.
Given that, would it be possible to go ahead with the merge?

**Comment by SplitInfinity** [comment]
> @SplitInfinity - We have fixed the test failure. In the latest CI, there's a test failing, but it seems unrelated to this PR. In fact we found a couple of other PRs which are seeing the same failure (#50155, #50157), which probably points towards some unrelated issue.
> Given that, would it be possible to go ahead with the merge?

Yeah, those tests look unrelated. I imported the diff again, I'll let you know how the internal tests look.

**Comment by spandantiwari** [comment]
> Yeah, those tests look unrelated. I imported the diff again, I'll let you know how the internal tests look.

Thanks @SplitInfinity . :-) 
Let me know if there's anything else needed here.

**Pull request closed without merging**
