### PR TITLE
Construct `c10::Half` from `float16_t` on ARMv8

### PR DESCRIPTION
**Pull request by malfet**
By hiding float32 constructors and exposing float16 ones. This allows compiler do implicit conversions as needed, and in safe cases optimize out unneeded upcasts to fp32, see example [below](https://godbolt.org/z/5TKnY4cos)
```cpp
#include <arm_neon.h>

#ifndef __ARM_FEATURE_FP16_SCALAR_ARITHMETIC
#error Ieeee
#endif

float16_t sum1(float16_t x, float16_t y) {
    return x + y;
}

float16_t sum2(float16_t x, float16_t y) {
    return static_cast<float>(x) + static_cast<float>(y);
}
```
both sum variants are  compiled to scalar fp16 add, if build for the platform that supports fp16 arithmetic
```
sum1(half, half):                            // @sum1(half, half)
        fadd    h0, h0, h1
        ret
sum2(half, half):                            // @sum2(half, half)
        fadd    h0, h0, h1
        ret
```

Fixes build error in some aarch64 configurations after #119483 which are defined as supporting FP16 but don't define _Float16.

cc @snadampal

### CODE REVIEW

**Review by mikekgfb — APPROVED** [review]
LGTM!

**Comment by atalman** [comment]
@malfet Since https://github.com/pytorch/pytorch/pull/119483 was reverted should we merge both PRs, test and land them together ?

**Review by atalman — APPROVED** [review]

**Comment by malfet** [comment]
> @malfet Since https://github.com/pytorch/pytorch/pull/119483 was reverted should we merge both PRs, test and land them together ?

If this can be landed, it potentially achieves the same results as the other PR, but with fewer lines of code

**Comment by malfet** [comment]
@snadampal FYI

**Comment by snadampal** [comment]
Looks good to me! 

If I understand correctly, this is an extension to the fp16<->fp32 acceleration feature added as part of this [PR](https://github.com/pytorch/pytorch/pull/120012).  now it's reusing the same via `Half` operator.  isn't it?

I'm wondering what the major use cases for fp16 (half) datatype kernels are.

**Review by snadampal — APPROVED** [review]

**Pull request closed without merging**
