### PR TITLE
[dtensor][experimental] expose DTensor Context Parallel API

### PR DESCRIPTION
**Pull request by XilunWu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137038

**Summary**
expose experimental Context Parallel API `torch.distributed.tensor.experimental._attention.context_parallel` to module `torch.distributed.tensor.experimental`.

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @tianyu-l

### CODE REVIEW

**Comment by fegin** [comment]
Can we add one disclaimer to the docstring of `context_parallel` to state this is a prototype API?

**Review by wz337 — APPROVED** [review]
LGTM

**Review by fegin — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your changes but the doc build failure looks legit' -c ignoredsignal

[GH job link](https://github.com/pytorch/pytorch/actions/runs/11130603490/job/30931089501) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/e23e766cc089b568aa4c0ebf0747ff9b504b8915)

**Pull request closed without merging**
