### PR TITLE
Introduce Python binding for `Tensor.has_storage`

### PR DESCRIPTION
**Pull request by cbalioglu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #70383

This PR exposes the `has_storage` accessor of `Tensor` to Python along with a minor improvement to `_tensor_str.py` to render opaque tensors correctly.

Differential Revision: [D33304930](https://our.internmc.facebook.com/intern/diff/D33304930/)

### CODE REVIEW

**Comment by albanD** [comment]
cc @zou3519 
Why do you need this check?
To choose if you can use some optimization that Tensor subclas/sparse/etc cannot use, I think we would like to expose the tensor subclass like idea instead: https://github.com/pytorch/pytorch/pull/69534

**Comment by cbalioglu** [comment]
> cc @zou3519 Why do you need this check? To choose if you can use some optimization that Tensor subclas/sparse/etc cannot use, I think we would like to expose the tensor subclass like idea instead: #69534

Thanks for the pointer @albanD! I need this check for similar reasons as in #69534. However in my opinion deviations from the standard logic should be based on the *properties* of a tensor (e.g. `has_storage`, `is_sparse`, `layout`) instead of its *identity* (e.g. `Meta`, `SparseCPU`, `Python`). So I can't say that I particularly liked the `isTensorSubclassLike()` function.

For instance say I am a vendor that has some custom accelerator hardware and I leverage `PrivateUse*` and `AutogradPrivateUse*` dispatch keys for my internal `TensorImpl` that has similar "problems" like the ones listed in `kTensorSubclassLike`. Right now I have to modify `kTensorSubclassLike` and deploy my own version of PyTorch to get the benefits of #69534.

**Comment by albanD** [comment]
We did discuss this quite a bit.
The problem with properties is that there is no one rule that applies to them. Your Tensor might not have a storage_ field, but all ops can be completely fine. Tensors like xla for example do have complex mechanism to work around that.
So there isn't a set of properties that we can check to know if such things are valid or not.

That being said, the main point of #69534 was to have a single concept to encompass whatever complex logic we have to detect such a Tensor (how we detect it is an implementation detail). But I do think that we should expose only this one as it will be the one place where we put that logic (and it won't be duplicated all around the codebase).

Note that `isTensorSubclassLike` is only checking dispatch keys today because that's is where the information we want is. But I don't think we are opposed to having a mechanism to expand this further (boolean flag on the TensorImpl?) to make it easier to use for third parties.

**Comment by zou3519** [comment]
Sorry I am very late to the conversation.

@cbalioglu I'm trying to understand the suggestion for the long term state. Are you suggesting to put `Tensor.has_storage()` checks into the C++ logic of Composite PyTorch operations so that they work better for Opaque Tensors, and are you suggesting to have `has_storage / is_sparse / layout` checks in the C++ logic of Composite PyTorch operations?

The PyTorch dispatcher is designed to prevent long if/then/else statements in the implementation of the operators, but due to FC/BC and performance concerns we decided to use isTensorSubclassLike as a general purpose check for these kind of things. We're open to changes though; I don't particularly like having `isTensorSubclassLike` checks all around the codebase but it does get what we've been trying to do done.

**Comment by cbalioglu** [comment]
> Sorry I am very late to the conversation.
> 
> @cbalioglu I'm trying to understand the suggestion for the long term state. Are you suggesting to put `Tensor.has_storage()` checks into the C++ logic of Composite PyTorch operations so that they work better for Opaque Tensors, and are you suggesting to have `has_storage / is_sparse / layout` checks in the C++ logic of Composite PyTorch operations?
> 
> The PyTorch dispatcher is designed to prevent long if/then/else statements in the implementation of the operators, but due to FC/BC and performance concerns we decided to use isTensorSubclassLike as a general purpose check for these kind of things. We're open to changes though; I don't particularly like having `isTensorSubclassLike` checks all around the codebase but it does get what we've been trying to do done.

Hey @zou3519, no worries! Actually my goal is much simpler than that. Some utility functions in the Python API such as `_tensor_str()` use the `storage()` accessor of a `Tensor` instance without validating it first. For instance if the tensor has the `storage_access_should_throw` field set, calling `storage()` raises an error. I exposed `has_storage` in Python so that we can gracefully handle such situations. As you see in this PR, one particular use case is that if a tensor has no storage (which we check by `has_storage()`), calling `str(tensor)` outputs `tensor(..., size=[x])` instead of raising an error. I believe there are a couple other places similar to `_tensor_str()` where we blindly access `storage()`. I plan to have similar checks for them as well.

**Comment by zou3519** [comment]
Gotcha, thanks for the clarification!

So, my main problem with has_storage is that it no one really sat down and defined its semantics. Tensor Extensions like [SparseTensorImpl](https://github.com/pytorch/pytorch/blob/0fdb90da5e1e7ec8f6becbdeecb84a3d855268ad/aten/src/ATen/SparseTensorImpl.cpp#L78-L83) and [BatchedTensor](https://github.com/pytorch/functorch/blob/0e1793e24d6752561d734ef112085a7927718692/functorch/csrc/BatchedTensorImpl.cpp#L140-L145) have different behavior on accessing has_storage in DEBUG mode or not. If we want has_storage to be an actual public method on torch.Tensor we should probably figure out what the semantics are for the existing tensor extensions.

Next, `_tensor_str` is a pain point that all Tensor Extension writers have. There's currently no way for a C++ based Tensor extension to override `_tensor_str` without modifying it, as you've seen. Adding the `has_storage` check will fix it for most Opaque Tensors but won't solve the problem for e.g. BatchedTensor. We should have an extension point for _tensor_str (e.g. maybe with a _custom_tensor_str aten operator).

What are some of the other places where we blindly access .storage()? I'm wondering if that just points out we need more extension points from C++ for those locations or if has_storage is the right fix for them.

**Comment by cbalioglu** [comment]
Thanks for the feedback @zou3519! Fair enough. I think I can live with having no `repr()`/`str()` support for opaque tensors. Since our plan is to have LMM out-of-core, I can offer a standalone function for printing fake tensors. Considering the recent strategy of offloading more projects to their own repos, these kind of extensibility points will become even more relevant. I would be happy to give feedback in case you keep me in the loop with the relevant discussions.

> What are some of the other places where we blindly access .storage()? I'm wondering if that just points out we need more extension points from C++ for those locations or if has_storage is the right fix for them.

Almost all remaining use cases are in the distributed package (in particular in FSDP), I believe there was one problematic use of `storage()` in `Tensor`'s `deepcopy` though.

**Pull request closed without merging**
