### PR TITLE
Enable ruff in lintrunner

### LINKED ISSUE #94737: [BE]: Add ruff to lintrunner - use for additional plugins like pyupgrade etc.
### 🚀 The feature, motivation and pitch

* The PyTorch codebase is huge. Formatting and linting the repo takes a lot of time. Additionally, adding new linters is a bit of challenge. https://github.com/charliermarsh/ruff is a Rust linter/fixer that implements rules for the most common of flake8 linters (pyupgrade, flake8, isort, popular flake8-plugins etc). Many of our existing linters can be combined here. The only downside is that it does reduce the number of flake8-plugins we can use (since they are all reimplemented in the framework), but it does many of the autofixes. Even if we don't replace flake8 etc with this plugin, we can use it supplement it, by using it only for other modules like pyupgrade (where you can select individual pyupgrade rules etc.). I've been using to implement various PRs and it's pretty reasonable so far. See https://github.com/pytorch/pytorch/issues/94040

### Alternatives

Keep the existing linters

### Additional context

It's also really, really fast!

cc @malfet @seemethere

### PR DESCRIPTION
**Pull request by justinchuby**
This change implements the ruff linter in pytorch lintrunner. It is adapted from https://github.com/justinchuby/lintrunner-adapters/blob/main/lintrunner_adapters/adapters/ruff_linter.py. It does both linting and fixing.

This change also migrated all flake8 configs to the ruff config.

We plan to enable ruff in `torch.onnx`.

Fixes https://github.com/pytorch/pytorch/issues/94737

@huydhn @Skylion007 

### Summary
🧹,🛠️,🚨,

This pull request adds support for the ruff code formatter and linter to the pytorch project. It modifies the `.lintrunner.toml` and `pyproject.toml` files to configure the ruff tool, and adds two new adapter files to the `tools/linter/adapters` directory to run the ruff tool with or without autofix capabilities using the lintrunner tool. The purpose of this pull request is to introduce a new code style and quality standard for the pytorch codebase, and to enable developers to easily check and fix their code using the lintrunner tool.

> _`Ruff` lints and formats_
> _Improving pytorch codebase_
> _Autumn of quality_

### Walkthrough
*  Add ruff formatter and linter to pytorch code quality checks ([link](https://github.com/pytorch/pytorch/pull/99280/files?diff=unified&w=0#diff-253fb40c812d7e8e2ba65b7e8796b74c75bc9ead3abee3cb6fc662043f96a1b9R972-R1013), [link](https://github.com/pytorch/pytorch/pull/99280/files?diff=unified&w=0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R22-R25), [link](https://github.com/pytorch/pytorch/pull/99280/files?diff=unified&w=0#diff-d5924e216fe16f73fd606c54ed38300190d09abd179c2df5c785e96158a9fe71R1-R275), [link](https://github.com/pytorch/pytorch/pull/99280/files?diff=unified&w=0#diff-d2a2b5b817ea6e6e625e993e3a3f8a3825dd846566100de0abb9e791f0b58108R1-R360))
  - Update `.lintrunner.toml` to include RUFF and RUFF-FIX linters with code patterns, commands, and options ([link](https://github.com/pytorch/pytorch/pull/99280/files?diff=unified&w=0#diff-253fb40c812d7e8e2ba65b7e8796b74c75bc9ead3abee3cb6fc662043f96a1b9R972-R1013))
  - Add `tool.ruff` section to `pyproject.toml` to specify target Python version for ruff ([link](https://github.com/pytorch/pytorch/pull/99280/files?diff=unified&w=0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R22-R25))
  - Create `ruff_fix_linter.py` and `ruff_linter.py` in `tools/linter/adapters` to run ruff commands and return lint messages ([link](https://github.com/pytorch/pytorch/pull/99280/files?diff=unified&w=0#diff-d5924e216fe16f73fd606c54ed38300190d09abd179c2df5c785e96158a9fe71R1-R275), [link](https://github.com/pytorch/pytorch/pull/99280/files?diff=unified&w=0#diff-d2a2b5b817ea6e6e625e993e3a3f8a3825dd846566100de0abb9e791f0b58108R1-R360))

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by Skylion007** [comment]
This is fantastic as it would eventually allow adding a lot of autofixes from flake8 fixes and could potentially subsume other lint checks in a faster framework. (It would also allow us to individually enable checks from pyupgrade which would be useful).

> I split ruff into two because I couldn't find a good way to make lintrunner display inline messages and produce a fix at the same time.

Have you opened an issue on ruff? I am sure if there is not this behavior in ruff yet, it could be easily added and would reduce our maintenance, and require 1 fewer run of ruff. Are the `--show-fixes` and ` --show-source` flags insufficient for use case?

**Comment by Skylion007** [comment]
I would actually go as far as trying to enable it globally if possible as we should at least be able to run all the checks we have enabled in our flake8 rules.

**Comment by justinchuby** [comment]
> Have you opened an issue on ruff? I am sure if there is not this behavior in ruff yet, it could be easily added and would reduce our maintenance, and require 1 fewer run of ruff. Are the `--show-fixes` and ` --show-source` flags insufficient for use case?

I think I just haven't figured out how to parse to outputs properly, since the fixed code and the violations will appear together in stdout? I understand lintrunner needs to read the fixed file from a pipe and the fix cannot happen inplace.

**Comment by Skylion007** [comment]
> > Have you opened an issue on ruff? I am sure if there is not this behavior in ruff yet, it could be easily added and would reduce our maintenance, and require 1 fewer run of ruff. Are the `--show-fixes` and ` --show-source` flags insufficient for use case?
> 
> I think I just haven't figured out how to parse to outputs properly, since the fixed code and the violations will appear together in stdout? I understand lintrunner needs to read the fixed file from a pipe and the fix cannot happen inplace.

You can have ruff output it's violations in JSON format, just use that: https://beta.ruff.rs/docs/configuration/#command-line-interface

**Comment by justinchuby** [comment]
I used that. Looks like I need to figure out how to apply the edits from the json properly. Do you have any suggestions?

**Comment by huydhn** [comment]
I quickly look at ruff documentation.  Here are some thoughts:

1. `LintMessage` expects the original and the replacement text https://docs.rs/lintrunner/latest/lintrunner/lint_message/struct.LintMessage.html from the adapter.  It will handle the rest.  So in this case, the `ruff_fix_linter` seems out of place as it actually does the formatting.  I agree that `lintrunner` and `ruff` doesn't fit together well here.
1. `ruff --diff` shows the diff.  Is there a way to take that diff output and apply it to the original text read from the file to get the replacement text?  That could be a work-around

I had a similar issue integrating `lintrunner` with `ufmt` before and needed to use `uftm` Python API to get it working https://github.com/pytorch/pytorch/blob/main/tools/linter/adapters/ufmt_linter.py#L67-L78.  It looks like that people is also asking for the same API from `ruff` here https://github.com/charliermarsh/ruff/issues/659.  That will probably be the solution

**Comment by justinchuby** [comment]
We _could_ run two passes: one using ruff on all file to get the lints (fast), the second using treads to get replacement texts for each file (10x slower but still fast, a few seconds). This way we don't need to manually parse and apply the patches from the json, ensuring accuracy. The total runtime for this will be a few seconds.

Alternatively as @skylion007 pointed out we could run ruff on a files and apply patches manually. This way we only need to use python to read and modified the files with fixes. The challenge would be to ensure correctness of the patch application process. But it will be the fastest way I can see.

**Comment by justinchuby** [comment]
I did the two pass method, and migrated all flake8 configs to the ruff config. It is **very** fast:

```
[2023-04-22T01:35:09Z DEBUG lintrunner] Running linters: ["RUFF"]
[2023-04-22T01:35:09Z DEBUG lintrunner::git] Running paths_cmd: git grep -Il .
[2023-04-22T01:35:10Z DEBUG lintrunner::linter] Running linter RUFF: python3 'tools/linter/adapters/ruff_linter.py' '--config=pyproject.toml' '--show-disable' '--' '@/var/folders/59/5mtp2rns59n7n99ndkm5x6gc0000gn/T/.tmp2yDttl'
[2023-04-22T01:35:11Z DEBUG lintrunner::linter] Linter RUFF took: 1.615648916s
```

**Comment by justinchuby** [comment]
Replaced by https://github.com/pytorch/pytorch/pull/99785

**Comment by justinchuby** [comment]
@Skylion007 enabled in #99785 . Looking good so far! Fixed a few issues flake8 didn't detect

**Pull request closed without merging**
