### PR TITLE
Set caffe2::pthreadpool() size in ParallelOpenMP

### PR DESCRIPTION
**Pull request by dbalchev**
Addresses #45418. 

This is probably not the best solution, but it's a rebase of the solution we're considering until #45418 is solved. If you can outline a better one I'm willing to implement it (:

### CODE REVIEW

**Comment by dbalchev** [comment]
Bump?

**Comment by glaringlee** [comment]
> Bump?

@dbalchev 
Can you rebase this code and monitor the CI tests? There are 2 CI tests failed in dataloader test, I am not sure whether that is related to this change since dataloader's worker do call set_num_threads() in subprocess.
see here:
https://github.com/pytorch/pytorch/blob/gh/glaringlee/34/head/torch/utils/data/_utils/worker.py#L136

**Comment by dbalchev** [comment]
@glaringlee 
Thanks for the suggestion. After I rebase on top of a fresh master it seems all tests pass.

**Comment by glaringlee** [comment]
> @glaringlee
> Thanks for the suggestion. After I rebase on top of a fresh master it seems all tests pass.

I am running this in facebook internal CI tests now. Will approve this after the tests done.

**Comment by glaringlee** [comment]
> @glaringlee
> Thanks for running the internal tests. It seems they're failing and I can't even see what's the reason for this.

No worries, that's not related to this PR, I'll land this today

**Review by glaringlee — APPROVED** [review]
LGTM

**Comment by glaringlee** [comment]
@dbalchev 
Can you sign the CLA if you did not sign them before? This is a new requirement to land opensource code.
https://pytorch.org/blog/a-contributor-license-agreement-for-pytorch/

**Comment by glaringlee** [comment]
@dbalchev 
Can you please check whether you signed the CLA? This is a requirement now before landing your code.https://pytorch.org/blog/a-contributor-license-agreement-for-pytorch/
Please check details in above link. One you signed, please rebase this code. I will then land it. thx

**Comment by dbalchev** [comment]
Thanks!
I've forwarded the CLA to our legal team. I'll comment when they've reviewed it.

**Comment by glaringlee** [comment]
> Thanks!
> I've forwarded the CLA to our legal team. I'll comment when they've reviewed it.

Sure. Sorry for the inconvenience. Please do a rebase once you signed. So I can land the code after.

**Comment by VitalyFedyunin** [comment]
#45418 is closed. Can we close this one too?

**Comment by dbalchev** [comment]
> #45418 is closed. Can we close this one too?

I prefer leaving it open. (: 
I'm still waiting on out legal team to review the CLA. After that is done AFAIK this PR is approved and should be merged.

#45418 was closed, so we can discuss it in the forum. The response from the forum was that it cannot be done ATM.

**Comment by dbalchev** [comment]
> @dbalchev I will keep this open for a while and sync with @VitalyFedyunin.
> Please give an update on ETA for signing CLA once it is available.

I got a green light from our legal team and the CLA will be signed in the next couple of days. 
I've just rebased on top of master.

**Comment by dbalchev** [comment]
@glaringlee the CLA is signed.

**Comment by glaringlee** [comment]
@dbalchev 
Sry, missed your update, can you please rebase the code again? I will try land this tomorrow.

**Pull request closed without merging**
