### PR TITLE
Switch XLA to only override abstract functions (#29438)

### PR DESCRIPTION
**Pull request by ailzhang**
Summary:
This is a followup of li-roy 's work https://github.com/pytorch/pytorch/pull/23282. (I messed up the rebase there :(

After https://github.com/pytorch/xla/issues/1225 is done we are good to move the integration to only override abstract functions.

This PR contains a TODO which I'll remove in next 2 followup PRs.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/29438

Differential Revision: D18445927

Pulled By: ailzhang

### CODE REVIEW

**Comment by ailzhang** [comment]
for reference this is a reland of https://github.com/pytorch/pytorch/pull/29438.

**Comment by ezyang** [comment]
@ailzhang this broke the XLA build: 

```
Nov 13 09:06:21 Traceback (most recent call last):
Nov 13 09:06:21   File "/var/lib/jenkins/workspace/xla/scripts/gen.py", line 1087, in <module>
Nov 13 09:06:21     generate(args)
Nov 13 09:06:21   File "/var/lib/jenkins/workspace/xla/scripts/gen.py", line 1027, in generate
Nov 13 09:06:21     fndefs, errors = extract_functions(args.typedef)
Nov 13 09:06:21   File "/var/lib/jenkins/workspace/xla/scripts/gen.py", line 909, in extract_functions
Nov 13 09:06:21     for line in open(path, 'r'):
Nov 13 09:06:21 FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/jenkins/workspace/xla/scripts/../../build/aten/src/ATen/RegistrationDeclarations.h'
Nov 13 09:06:21 Failed to run '['/var/lib/jenkins/workspace/xla/scripts/generate_code.sh']'
Nov 13 09:06:21 Building torch_xla version: 0.8
```

**Comment by ezyang** [comment]
Are we waiting on a companion diff to land XLA side? It wasn't clear from the PR description here.

**Comment by ailzhang** [comment]
thanks @ezyang! Yea there’s a companion diff on XLA rep that’s running CI. Will be merged soon! :D

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
