### PR TITLE
[PP] Go back to export instead of _export

### PR DESCRIPTION
**Pull request by kwen2501**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134299

Reverts https://github.com/pytorch/pytorch/pull/130998 because FakeTensor + real device suffice to work around the autocast issue in HF.

cc @XilunWu @H-Huang @awgu @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by lessw2020 — APPROVED** [review]
only issue with going back is HF may break now since they still have autocast in their rope embeddings?  That said, probably better if this is fixed in export directly. 
Otherwise, lgtm!

**Comment by kwen2501** [comment]
It is okay if HF still have autocast in their rope embeddings.
Users just need to do this before tracing:
```
# Cast the model to FakeTensor with real device (from meta device) because
# there is autocast code in llama.  Autocast functions based on device of
# tensor. So we'd need to give it a real device instead of meta device.
with fake_mode:
    llama.to_empty(device="cuda")
```

**Comment by kwen2501** [comment]
Okay, I see what you mean @lessw2020 
I will hold the merge till figuring out a preference.

**Pull request closed without merging**
