### PR TITLE
Add PrivateUse1 for dispatching PyTorch Distributed Collectives.

### LINKED ISSUE #97938: Support custom device and custom backend for Dispatching PyTorch Distributed Collectives
### 🚀 The feature, motivation and pitch

Currently, PyTorch supports the extension of third-party libraries for collection communication. However, only CPU and GPU are distributed for collection communication.  When we extend Pytorch, a scenario is using custom device and custom backend e.g. `"cpu:gloo,privateuse1:custom_backend"`.

### Alternatives
To support custom device and backend:

First, add PrivateUse1 for dispatching PyTorch Distributed Collectives. 
Here is a examples:
```c++
c10::intrusive_ptr<c10d::Work> send_privateuse1(
    at::TensorList tensors,
    const c10::intrusive_ptr<c10d::ProcessGroup>& process_group,
    int64_t dstRank,
    int64_t tag) {
  auto tensor_vec = tensors.vec();
  return process_group->getBackend(c10::DeviceType::PrivateUse1)
      ->send(tensor_vec, static_cast<int>(dstRank), static_cast<int>(tag));
}

TORCH_LIBRARY_IMPL(c10d, PrivateUse1, m) {
  m.impl("send", send_privateuse1);
}
```

Second, some collective functions need to be updated to support custom backends, e.g:
```python
# 1 add device parameter
def all_gather_object(object_list, obj, group=None, device=None):
    current_device = device or _get_pg_device(group)
```

```python
# 2 Add judgment for custom backend
def barrier(group=GroupMember.WORLD, async_op=False, device_ids=None):
    if device_ids is not None:
        if (get_backend(group) != Backend.NCCL) or (get_backend(group) in Backend._plugins) :
            raise RuntimeError(
                "Function argument device_ids not supported "
                "for the selected backend {}".format(get_backend(group))
            )
```
```python
# 3 add judgment for custom device
if not torch.cuda.is_available() or not custom_device_is_available:
    raise ValueError("Subgroups can only be created when CUDA or custom device is available")
```

_No response_

### Additional context

_No response_

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

### PR DESCRIPTION
**Pull request by shaoyf42**
Add PrivateUse1 for dispatching PyTorch Distributed Collectives to support custom device. This PR is to fix https://github.com/pytorch/pytorch/issues/97938#issue-1646833919

### CODE REVIEW

**Comment by shaoyf42** [comment]
@H-Huang  could you take a look

**Comment by ezyang** [comment]
It seems like we should accept this PR. But I have a question for the folks who originally wrote this code: why is there so much copy pasting going on here already between the CPU/CUDA c10d wrappers?

**Comment by kumpera** [comment]
> It seems like we should accept this PR. But I have a question for the folks who originally wrote this code: why is there so much copy pasting going on here already between the CPU/CUDA c10d wrappers?

This looks like something that can b cleaned up by using templates to curry the backend to lookup.

**Review by kumpera — APPROVED** [review]
LGTM

**Pull request closed without merging**
