### PR TITLE
no longer coalesce sparse COO tensors before comparison

### PR DESCRIPTION
**Pull request by pmeier**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #72930
* #72508
* __->__ #69751

cc @nikitaved @pearu @cpuhrsch @IvanYashchuk

Differential Revision: [D34262453](https://our.internmc.facebook.com/intern/diff/D34262453)

### CODE REVIEW

**Review by IvanYashchuk — APPROVED** [review]
As long as tests pass I'm happy with the change. Thank you for working on this!

**Review by ezyang — APPROVED** [review]
thanks

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34262453).

**Pull request closed without merging**
