### PR TITLE
[JIT] fix freezing with mkldnn tensors

### PR DESCRIPTION
**Pull request by eellison**
We were accessing their storage which will throw

### CODE REVIEW

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Comment by xsacha** [comment]
Freezing MKL is still not working for me in latest nightly.
I get a different error now:
NotImplementedError: Cannot access storage of OpaqueTensorImpl

**Comment by eellison** [comment]
@xsacha i dont think saving and loading mkldnn tensors work on JIT without freezing, this was just fixing a freezing error. but agreed that it would be nice to fix that. Do you mind opening an issue ?

**Comment by xsacha** [comment]
I can save a JIT mkldnn model without freezing, but when performing the freeze beforehand and then trying to save I get that error.
Prior to this commit I couldn't do the freeze.

**Pull request closed without merging**
