### PR TITLE
Add foxi submodule (ONNXIFI facebook extension)

### PR DESCRIPTION
**Pull request by houseroad**

### CODE REVIEW

**Review by bddppq — APPROVED** [review]
👍 LG!

**Comment by xsacha** [comment]
Is foxi a required component or would it be possible to have a USE_FOXI or similar?

**Comment by houseroad** [comment]
@xsacha what is causing issue here?

**Comment by xsacha** [comment]
Just not sure what it is doing or if it is optional.
Would like to add it as a CMake package if possible but it exports as ONNX so I can't use find_package(ONNX).

**Pull request closed without merging**
