### PR TITLE
[primTorch] Use the same error message as in ATen for canonicalize_dim

### LINKED ISSUE #78252: Discrepancy in the dimension wrapping error message and type
### 🐛 Describe the bug

There's a discrepancy in the error message and error type in `torch._prims.utils.canonicalize_dim` and `at::maybe_wrap_dims_n` :
https://github.com/pytorch/pytorch/blob/87148f2b5921557774a535495d7c77b20aa795b6/torch/_prims/utils.py#L408-L410
https://github.com/pytorch/pytorch/blob/87148f2b5921557774a535495d7c77b20aa795b6/aten/src/ATen/WrapDimUtils.h#L48-L50
`canonicalize_dim` raises a `ValueError` while `at::maybe_wrap_dims_n` raises `IndexError`.

This prevents proper use of error inputs with OpInfo for some operations.

### Versions

On the latest main branch.

cc @ezyang @mruberry @ngimel

### PR DESCRIPTION
**Pull request by IvanYashchuk**
Fixes https://github.com/pytorch/pytorch/issues/78252.

Locally nothing seems to break when changing the error type and the error message meaning there were no tests.
At least one xfailed test from https://github.com/pytorch/pytorch/pull/78080 wouldn't pass with this PR.

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
Please land as soon as tests pass

**Review by mruberry — APPROVED** [review]
Awesome!

**Pull request closed without merging**
