### PR TITLE
[DataPipe] Unifying API - removing unbatch_level from .groupby

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70216
* #70215
* __->__ #70249
* #70214

IMO, the `unbatch_level` argument is not needed here since users can simply can `.unbatch` before calling `.groupby` if needed. One small step closer to an unified API with other libraries.

Note that we may rename the functional name from `.groupby` to `.group` in the future. TBD.

Differential Revision: [D33259104](https://our.internmc.facebook.com/intern/diff/D33259104)

cc @VitalyFedyunin @ejguan @NivekT

### CODE REVIEW

**Review by ejguan — APPROVED** [review]
LGTM thanks. Could you test it with torchvision to verify nothing will break (test in torchdata)? Otherwise, we should let Philip know.

**Comment by NivekT** [comment]
> LGTM thanks. Could you test it with torchvision to verify nothing will break (test in torchdata)? Otherwise, we should let Philip know.

I searched through their repo and their only use case doesn't use `unbatch_level` as an argument.

@pmeier can you confirm?

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33259104).

**Review by ejguan — COMMENTED** [review]
Sorry, I missed one thing you need to do. The API for DataFrame is also needed to be modified https://github.com/pytorch/pytorch/blob/304efd8e9a14438956af462de8e5f67a3ef35ea0/torch/utils/data/datapipes/dataframe/dataframes.py#L96-L110

**Comment by NivekT** [comment]
> Sorry, I missed one thing you need to do. The API for DataFrame is also needed to be modified
> 
> https://github.com/pytorch/pytorch/blob/304efd8e9a14438956af462de8e5f67a3ef35ea0/torch/utils/data/datapipes/dataframe/dataframes.py#L96-L110

Thanks for catching that. I will do that now

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33259104).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33259104).

**Pull request closed without merging**
