### PR TITLE
improve multi-core performance of qupsample_nearest2d

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74999
* #68328
* #72575
* #71903
* #69667
* #69601
* __->__ #69600
* #69599
* #69598
* #69517

Differential Revision: [D33353153](https://our.internmc.facebook.com/intern/diff/D33353153)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33353153).

**Comment by Xia-Weiwen** [comment]
Hi @jerryzh168 We have a few int8-related PRs targeting 1.11. And this is one of them. Could you prioritize to review these PRs? Thanks.

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33353153).

**Comment by mingfeima** [comment]
### Updates of this PR
Overall ideas of #69600 and #69601 are the same: improves `qupsample_nearest2d` and `qupsample_bilinear2d` performance on CPU.

Both `torch.contiguous` and `torch.channels_last` memory format are improved.
Both single core and multi core performance are improved.



### Benchmarking

* **short tag**: `python -m pt.qinterpolate_test`
* **long tag**:  `python -m pt.qinterpolate_test --tag_filter long`

CPU: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, dual sockets, 20 cores per socket.
Unit: us

**Review by dzdang — APPROVED** [review]

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33353153).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33353153).

**Pull request closed without merging**
