### PR TITLE
[nnc] Added an API to shuffle statements in a block

### PR DESCRIPTION
**Pull request by navahgar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #61293
* #61087
* **#61086**
* #61085

Partial fix for #60991 

Differential Revision: [D29506678](https://our.internmc.facebook.com/intern/diff/D29506678)

### CODE REVIEW

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29506678).

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29506678).

**Review by ZolotukhinM — COMMENTED** [review]
Hm, while I see that this API allows to do whatever we want with statements in a block, I imagine it would be not very convenient to use it in practice: figuring our the correct permutation seems very laborious. How about we provide functions like `moveStmtBefore(this_stmt, where_to_move_stmt)` and `moveStmtAfter(this_stmt, where_to_move_stmt)`?

**Comment by navahgar** [comment]
> Hm, while I see that this API allows to do whatever we want with statements in a block, I imagine it would be not very convenient to use it in practice: figuring our the correct permutation seems very laborious. How about we provide functions like `moveStmtBefore(this_stmt, where_to_move_stmt)` and `moveStmtAfter(this_stmt, where_to_move_stmt)`?

Good idea to add APIs to move stmts to a given position. But I still think this would be useful as well. We are already using the permutation for `reorder`. While this API requires the permutation for the entire `Block`, I think that would still be valuable if users want to move multiple stmts in one go.

**Comment by ZolotukhinM** [comment]
> I think that would still be valuable if users want to move multiple stmts in one go.

That's true, but how in practice would you prepare the permutation array in that case? Even if you carefully construct the enumeration for all stmts in the loop, it won't be very readable if we write
```
shuffle([init_stmt, for_i, for_tail, some_other_init, another_for, yet_another_for], [0, 3, 2, 4, 5, 6])
```
as compared to
```
moveAfter(some_other_init, init_stmt)
moveAfter(for_i, another_for)
moveAfter(for_tail, yet_another_for)
```

I somehow feel that in reorder case it actually makes sense to look at all loops at once and thus to use the permutation array to describe the desired outcome. In the case of moving stmts in a block though I feel that there are often stmts that are not relevant to the movement, but which will have to be taken into consideration if we use the permutation approach, and because of that I think the permutation approach is worse in this case.

**Comment by navahgar** [comment]
The `shuffle` API here does not require listing all the statements. It just needs the parent block as input. 

>I somehow feel that in reorder case it actually makes sense to look at all loops at once and thus to use the permutation array to describe the desired outcome. 

The one difference I can think of between this and reordering `for` loops is that we might do more reorders of them because of how our other transformations work. Also, the `reorderAxis` api we have actually "swaps" the positions of the given two loops, and not move one before the other.

I felt that the `shuffle` API could still be useful mostly because the number of statements in our blocks are not large (I dunno this for sure, may be this assumption of mine is wrong).

Anyways, I will delete this PR and add the `moveBefore` / `moveAfter` APIs in another.

**Pull request closed without merging**
