### PR TITLE
Remove cereal submodule

### PR DESCRIPTION
**Pull request by goldsborough**
Cereal is dead!

@soumith @orionr

### CODE REVIEW

**Comment by apaszke** [comment]
Just curious - what do we use for C++ serialization now?

**Comment by goldsborough** [comment]
@apaszke `ScriptModule` as tensor containers, and then `ScriptModule::save` (i.e. Protobuf)

**Review by orionr — APPROVED** [review]
Woohoo!

**Comment by goldsborough** [comment]
@soumith @apaszke can we get code-owner stamp?

**Review by soumith — APPROVED** [review]

**Pull request closed without merging**
