### PR TITLE
Space is missing in __repr___ of conv

### PR DESCRIPTION
**Pull request by vfdev-5**
`Conv2d(3, 64, kernel_size=(3, 3), stride=(2, 2))` -> `Conv2d (3, 64, kernel_size=(3, 3), stride=(2, 2))` as for other layers, e.g
`MaxPool2d (size=(3, 3), stride=(2, 2), dilation=(1, 1)))`

### CODE REVIEW

**Comment by soumith** [comment]
it seems more natural to not have the space. When you write the line of code constructing the layer you dont write it with the space right?

In what context is a space more natural / better?

**Comment by vfdev-5** [comment]
Sure, but other __repr__ has such space : 
- https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/pooling.py#L68
- https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/normalization.py#L18

This fix is minimal to be conform with other. But, I agree, that without space is more natural

**Comment by SsnL** [comment]
Could you update so that the PR removes spaces from other places? Thanks!

**Comment by vfdev-5** [comment]
Could you explain why there is a difference in representations of `kernel_size` [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/pooling.py#L69) and [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/pooling.py#L146):
```
str(self.kernel_size)
```
vs
```
kh, kw = _pair(self.kernel_size)
'size=(' + str(kh) + ', ' + str(kw) + ')'
```
Probably, we can just use the first one

**Comment by SsnL** [comment]
Thanks! Looks good to me. cc @soumith to review.

**Comment by soumith** [comment]
thank you!

**Pull request merged**
