### PR TITLE
disabling unique/unique_consecutive for opinfo nvfuser correctness tests

### LINKED ISSUE #76354: NVFuser failing extremal opinfos
### 🐛 Describe the bug

[failure logs](https://gist.github.com/davidberard98/d6e30e7c888e04cd884397d0e5922139)

- [ ] nn_functional_binary_cross_entropy_with_logits
- [x] nn_functional_conv_transpose3d (#75363)
- [ ] nn_functional_nll_loss
- [ ] nn_functional_prelu
- [ ] unique_consecutive (https://github.com/pytorch/pytorch/issues/76571)
- [ ] unique  (https://github.com/pytorch/pytorch/issues/76571)

### Versions

https://github.com/pytorch/pytorch/runs/6215506399?check_suite_focus=true
CI, https://github.com/pytorch/pytorch/pull/75917

cc @jjsjann123

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #76354

added expected failure for unique/unique_consecutive failures.

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]
LGTM! Thanks!

**Comment by davidberard98** [comment]
@jjsjann123 Actually -- let's wait for CI, we might need to switch this to .skip instead...

It looks like these aren't failing in CI, so I'm assuming that this has some dependence on your setup vs. the CI setup. If they're currently passing in CI, then switching to expectedfailure will probably make the CI run fail.

**Comment by jjsjann123** [comment]
Looks like you are very right about this: https://pipelines.actions.githubusercontent.com/serviceHosts/7d146c05-69c3-4c20-a0e7-818111670117/_apis/pipelines/1/runs/2002517/signedlogcontent/157?urlExpires=2022-05-13T05%3A09%3A03.6335191Z&urlSigningMethod=HMACV1&urlSignature=6RGCuWtAuwfj6H5hktoB0ofGJeoZN4pENoe%2Buez99Rc%3D

Unexpected success hit by CI. I'll switch to skip instead.

**Comment by jjsjann123** [comment]
We don't need this more. IIUC, the failure was patched in https://github.com/NVIDIA/cub/pull/483 and I can verify that it went away in nightlies.

**Pull request closed without merging**
