### PR TITLE
Suppress warnings in tensorpipe.h

### LINKED ISSUE #110974: Error when building PyTorch from source with WERROR=1 and USE_DISTRIBUTED=1
# Summary
When building with the following two settings on Main I am getting the following error:
``` Shell
/pytorch/torch/csrc/distributed/rpc/tensorpipe_agent.cpp
In file included from /home/drisspg/meta/pytorch/torch/csrc/distributed/rpc/tensorpipe_agent.cpp:10:
In file included from /home/drisspg/meta/pytorch/third_party/tensorpipe/tensorpipe/tensorpipe.h:15:
In file included from /home/drisspg/meta/pytorch/third_party/tensorpipe/tensorpipe/core/context.h:18:
In file included from /home/drisspg/meta/pytorch/third_party/tensorpipe/tensorpipe/channel/context.h:16:
/home/drisspg/meta/pytorch/third_party/tensorpipe/tensorpipe/common/buffer.h:27:13: error: definition of implicit copy constructor for 'AbstractBufferWrapper' is deprecated because it has a user-declared destructor [-Werror,-Wdeprecated-copy-with-dtor]
    virtual ~AbstractBufferWrapper() = default;
            ^
/home/drisspg/meta/pytorch/third_party/tensorpipe/tensorpipe/common/buffer.h:31:9: note: in implicit copy constructor for 'tensorpipe::Buffer::AbstractBufferWrapper' first required here
  class BufferWrapper : public AbstractBufferWrapper {
        ^
/home/drisspg/meta/pytorch/third_party/tensorpipe/tensorpipe/common/buffer.h:46:17: note: in implicit copy constructor for 'tensorpipe::Buffer::BufferWrapper<tensorpipe::CpuBuffer>' first required here
      new (ptr) BufferWrapper(*this);
                ^
/home/drisspg/meta/pytorch/third_party/tensorpipe/tensorpipe/common/buffer.h:39:14: note: in instantiation of member function 'tensorpipe::Buffer::BufferWrapper<tensorpipe::CpuBuffer>::copyConstructInto' requested here
    explicit BufferWrapper(TBuffer buffer) : buffer(std::move(buffer)) {}
             ^
/home/drisspg/meta/pytorch/third_party/tensorpipe/tensorpipe/common/buffer.h:62:17: note: in instantiation of member function 'tensorpipe::Buffer::BufferWrapper<tensorpipe::CpuBuffer>::BufferWrapper' requested here
    new (&raw_) BufferWrapper<TBuffer>(std::move(b));
                ^
/home/drisspg/meta/pytorch/third_party/tensorpipe/tensorpipe/common/buffer.h:65:14: note: in instantiation of function template specialization 'tensorpipe::Buffer::Buffer<tensorpipe::CpuBuffer>' requested here
  Buffer() : Buffer(CpuBuffer{}) {}
             ^
1 error generated.
[2271/3099] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/api/src/nn/modules/conv.cpp.o
```

By updating tensorpipe/common/buffer.h to have 

``` C++
  class AbstractBufferWrapper {
   public:
    AbstractBufferWrapper() = default;
    AbstractBufferWrapper(const AbstractBufferWrapper&) = default;
    AbstractBufferWrapper& operator=(const AbstractBufferWrapper&) = default;

    virtual Device device() const = 0;
    virtual void copyConstructInto(void* ptr) const = 0;
    virtual void moveConstructInto(void* ptr) = 0;
    virtual ~AbstractBufferWrapper() = default;
  };
  ```
  I was able to avoid the werror but I am not sure if these default constructors are actually valid

cc @malfet @seemethere @osalpekar @jiayisuse @lw @beauby @pritamdamania87 @mrshenli @jjlilley @gqchen @rohan-varma

### PR DESCRIPTION
**Pull request by malfet**
To fix distributed compilation with clang-15

Fixes https://github.com/pytorch/pytorch/issues/110974

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Review by drisspg — APPROVED** [review]
Awesome, thank you!

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
@cyyever Looks like you missed a spot.

**Comment by cyyever** [comment]
No clang-15 jobs in CI flows

**Comment by malfet** [comment]
> No clang-15 jobs in CI flows

All MacOS jobs should be clang-15 ones, shouldn't they? But also, valid point, let me update cuda+clang to use clang-15

**Pull request closed without merging**
