### PR TITLE
Enable UFMT on `test/test_cuda*.py`

### PR DESCRIPTION
**Pull request by shink**
Part of: #123062 

Ran lintrunner on:

- test/test_cuda.py
- test/test_cuda_expandable_segments.py
- test/test_cuda_multigpu.py
- test/test_cuda_nvml_based_avail.py
- test/test_cuda_primary_ctx.py
- test/test_cuda_sanitizer.py
- test/test_cuda_trace.py

Detail:

```bash
$ lintrunner -a --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```

cc @albanD

### CODE REVIEW

**Comment by ezyang** [comment]
need to resolve merge conflict

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
is clean

**Comment by ezyang** [comment]
seems to be failing lint

**Comment by shink** [comment]
@ezyang fixed, please check it out: https://github.com/pytorch/pytorch/pull/124352/commits/6e0e19df2e7de7bc4ea3b3e3ea696aa01ba0c288

**Comment by ezyang** [comment]
merge conflict now

**Comment by ezyang** [comment]
```
diff --git b/test/test_cuda.py a/test/test_cuda.py
index 27549eb82dd..9e9f6dc8cc1 100644
--- b/test/test_cuda.py
+++ a/test/test_cuda.py
@@ -2650,10 +2650,8 @@ exit(2)
                 # These stat checks are specific to the native allocator.
                 if share_mem != "Don't share":
                     self.assertEqual(
-                        reserved_no_sharing
-                        - torch.cuda.memory_stats()[
-                            "reserved_bytes.all.current"
-                        ],  # noqa: F821
+                        reserved_no_sharing  # noqa: F821
+                        - torch.cuda.memory_stats()["reserved_bytes.all.current"],
                         kSmallBuffer,
                     )
                 else:
```

lg

**Comment by shink** [comment]
@ezyang You are welcome. All conflicts resolved, see https://github.com/pytorch/pytorch/pull/124352/commits/eec97abdaa641367419802ff087ba814dd6bb80b

diff:

```
diff --git a/test/test_cuda.py b/test/test_cuda.py
index fca8039a62..c9b6063322 100644
--- a/test/test_cuda.py
+++ b/test/test_cuda.py
@@ -2658,10 +2658,8 @@ exit(2)
                 # These stat checks are specific to the native allocator.
                 if share_mem != "Don't share":
                     self.assertEqual(
-                        reserved_no_sharing
-                        - torch.cuda.memory_stats()[
-                            "reserved_bytes.all.current"
-                        ],  # noqa: F821
+                        reserved_no_sharing  # noqa: F821
+                        - torch.cuda.memory_stats()["reserved_bytes.all.current"],
                         kSmallBuffer,
                     )
                 else:
```

**Comment by ezyang** [comment]
🤔 still conflicted

**Comment by shink** [comment]
fixed :p

diff:

```diff
diff --git a/test/test_cuda.py b/test/test_cuda.py
index 96c62a408a..24acfb0dc2 100644
--- a/test/test_cuda.py
+++ b/test/test_cuda.py
@@ -2663,10 +2663,8 @@ exit(2)
                 # These stat checks are specific to the native allocator.
                 if share_mem != "Don't share":
                     self.assertEqual(
-                        reserved_no_sharing
-                        - torch.cuda.memory_stats()[
-                            "reserved_bytes.all.current"
-                        ],  # noqa: F821
+                        reserved_no_sharing  # noqa: F821
+                        - torch.cuda.memory_stats()["reserved_bytes.all.current"],
                         kSmallBuffer,
                     )
                 else:
```

**Pull request closed without merging**
