### PR TITLE
Run clang-format on torch/lib/c10d

### PR DESCRIPTION
**Pull request by pietern**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#25382 Run clang-format on torch/lib/c10d**

The formatted code swapped the inclusion order around in
ProcessGroupNCCLTest.cpp, causing a compilation failure in
`ATen/cuda/CUDAMultiStreamGuard.h`.

To fix this, this commit also includes a fix to the include list in
`ATen/cuda/CUDAMultiStreamGuard.h`.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/25382

Differential Revision: [D17152634](https://our.internmc.facebook.com/intern/diff/D17152634)

### CODE REVIEW

**Comment by mrshenli** [comment]
Test failures seem irrelevant, but this one worries me:

```
Aug 29 08:59:04 In file included from /var/lib/jenkins/workspace/torch/lib/c10d/test/ProcessGroupGlooAsyncTest.cpp:3:0:
Aug 29 08:59:04 /var/lib/jenkins/workspace/aten/src/ATen/cuda/CUDAMultiStreamGuard.h:32:30: error: 'CUDAGuard' does not name a type
Aug 29 08:59:04    CUDAMultiStreamGuard(const CUDAGuard&) = delete;
Aug 29 08:59:04                               ^
Aug 29 08:59:04 /var/lib/jenkins/workspace/aten/src/ATen/cuda/CUDAMultiStreamGuard.h:33:41: error: 'CUDAGuard' does not name a type
Aug 29 08:59:04    CUDAMultiStreamGuard& operator=(const CUDAGuard&) = delete;
Aug 29 08:59:04                                          ^
Aug 29 08:59:04 /var/lib/jenkins/workspace/aten/src/ATen/cuda/CUDAMultiStreamGuard.h:36:33: error: expected ')' before '&&' token
Aug 29 08:59:04    CUDAMultiStreamGuard(CUDAGuard&& other) = delete;
Aug 29 08:59:04                                  ^
Aug 29 08:59:04 /var/lib/jenkins/workspace/aten/src/ATen/cuda/CUDAMultiStreamGuard.h:39:35: error: declaration of 'operator=' as non-function
Aug 29 08:59:04    CUDAMultiStreamGuard& operator=(CUDAGuard&& other) = delete;
Aug 29 08:59:04                                    ^
Aug 29 08:59:04 /var/lib/jenkins/workspace/aten/src/ATen/cuda/CUDAMultiStreamGuard.h:39:33: error: expected ';' at end of member declaration
Aug 29 08:59:04    CUDAMultiStreamGuard& operator=(CUDAGuard&& other) = delete;
Aug 29 08:59:04                                  ^
Aug 29 08:59:04 /var/lib/jenkins/workspace/aten/src/ATen/cuda/CUDAMultiStreamGuard.h:39:44: error: expected ')' before '&&' token
Aug 29 08:59:04    CUDAMultiStreamGuard& operator=(CUDAGuard&& other) = delete;
```

**Comment by pietern** [comment]
@mrshenli That is worrying indeed -- taking a look... It could be some include is missing.

**Review by mrshenli — APPROVED** [review]
Format changes LGTM. Please fix test failure before landing.

**Comment by pietern** [comment]
The problem is that `CUDAGuard` is defined under the `c10::cuda` namespace, but is expected in the `at::cuda` namespace. @ezyang do you recall recent changes along these lines recently?

**Comment by pietern** [comment]
Nevermind... the clang-format pass caused the order of the includes in `ProcessGroupGlooAsyncTest` to flip around and `using namespace c10` isn't yet done when including `ATen/cuda/CUDAMultiStreamGuard`. The solution here is to fix `ATen/cuda/CUDAMultiStreamGuard` with proper includes.

**Comment by pietern** [comment]
The failing ONNX build is due to a flaky test (looks to be the same as #24268).

**Pull request closed without merging**
