### PR TITLE
[WIP] Wrap Caffe2 (RowWise)SparseAdagrad fusion operator as a PT op

### PR DESCRIPTION
**Pull request by nqjade**
Summary: Caffe2 (RowWise)SparseAdagrad fusion operator on GPUs is implemented in D20453096. This diff wraps it as a PT op.

Differential Revision: D21511611

### CODE REVIEW

**Comment by jeffdaily** [comment]
Looks like we might need to add a case to the hipify mappings.  The file `caffe2/sgd/adagrad_fused_op_gpu.cu`, when hipified and placed here `caffe2/sgd/hip/adagrad_fused_op_gpu.hip`, does not have its include directive updated.
```
#include "caffe2/sgd/adagrad_fused_op_gpu.cuh"
```
It should instead point to the hipified header `caffe2/sgd/hip/adagrad_fused_op_gpu.cuh`.

**Comment by jeffdaily** [comment]
Try this diff, it should rename the header inclusion similar to other cases we've had in the past.

```
diff --git a/torch/utils/hipify/cuda_to_hip_mappings.py b/torch/utils/hipify/cuda_to_hip_mappings.py
index 6d3f1be..0095458 100644
--- a/torch/utils/hipify/cuda_to_hip_mappings.py
+++ b/torch/utils/hipify/cuda_to_hip_mappings.py
@@ -7995,6 +7995,7 @@ CAFFE2_SPECIFIC_MAPPINGS = collections.OrderedDict(
         ("/GpuBitonicSort", ("/hip/GpuBitonicSort", API_CAFFE2)),
         ("/math/reduce.cuh", ("/math/hip/reduce.cuh", API_CAFFE2)),
         ("/gather_op.cuh", ("/hip/gather_op.cuh", API_CAFFE2)),
+        ("/adagrad_fused_op_gpu.cuh", ("/hip/adagrad_fused_op_gpu.cuh", API_CAFFE2)),
         ("caffe2/core/common_cudnn.h", ("caffe2/core/hip/common_miopen.h", API_CAFFE2)),
         ("REGISTER_CUDA_OPERATOR", ("REGISTER_HIP_OPERATOR", API_CAFFE2)),
         ("CUDA_1D_KERNEL_LOOP", ("HIP_1D_KERNEL_LOOP", API_CAFFE2)),
```

**Comment by xw285cornell** [comment]
Thanks @jeffdaily for the very quick response! Yes I'm sure it'll work :)

**Comment by cpuhrsch** [comment]
This seems to have broken pytorch_linux_xenial_py3_6_gcc5_4_test and pytorch_windows_vs2019_py36_cuda10.1_on_cpu_test1

**Comment by xw285cornell** [comment]
hmm, just wondering, it looks it was green for the two tests mentioned here. What is the error msg?

**Comment by cpuhrsch** [comment]
https://app.circleci.com/pipelines/github/pytorch/pytorch/179766/workflows/590746a3-76cc-4fe4-9e50-a5a05cd7569a/jobs/5798211/steps and https://app.circleci.com/pipelines/github/pytorch/pytorch/179766/workflows/590746a3-76cc-4fe4-9e50-a5a05cd7569a/jobs/5798238/steps

**Comment by cpuhrsch** [comment]
Let's wait for the CI to run clear on the revert and then check again.

**Comment by cpuhrsch** [comment]
In the meantime you can create a PR to attempt to merge this again so we can undo the revert.

**Pull request closed without merging**
