### PR TITLE
Add vision onto the commit pins train

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #79099
* __->__ #79151
* #79150

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by clee2000 — APPROVED** [review]

**Comment by JackCaoG** [comment]
Hey Ed, this is breaking Pytorch/XLA CI build, log in https://app.circleci.com/pipelines/github/pytorch/xla/11801/workflows/a9b3f40f-51c9-40db-b587-991be895ee4e/jobs/25659. Can we either revert or get some help setting up the CI_pin for pytorch/xla?

**Comment by JackCaoG** [comment]
I guess the easiest thing we can do is pytorch/xla also add a `.github/ci_commit_pins/vision.txt`, but I think the right thing to do was using the upstream pin.

I felt like it might be a mistake of running `+ source /tmp/pytorch/.jenkins/pytorch/common_utils.sh` in pytorch/xla ci

**Comment by bdhirsh** [comment]
Yeah, running `source /tmp/pytorch/.jenkins/pytorch/common_utils.sh` feels kinda wrong since we're baking in assumptions about file paths. I took a quick look at the XLA CI scripts and it looks like it's only used to figure out how to install torchvision. So I have a fix here (letting CI run on it to confirm) https://github.com/pytorch/xla/pull/3643

**Pull request closed without merging**
