### PR TITLE
[inductor] don't access cluster_dims for too old version of triton

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #117192

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by masnesral** [comment]
Yup, this works. At least it fixes the specific test failure I saw when using triton 2.1.0. FWIW, the problem also goes away (without this change) when pip installing triton 2.2.0

**Review by masnesral — APPROVED** [review]

**Comment by shunting314** [comment]
yea, triton 2.2.0 should already have the complained attributes added

**Pull request closed without merging**
