### PR TITLE
fix annotation for Demultiplexer

### PR DESCRIPTION
**Pull request by pmeier**
cc @SsnL @VitalyFedyunin @ejguan @NivekT

### CODE REVIEW

**Review by NivekT — APPROVED** [review]
Good catch. LGTM!

**Comment by NivekT** [comment]
Can you look at the mypy linting errors to see if they are related?

**Comment by pmeier** [comment]
> Can you look at the mypy linting errors to see if they are related?

Although they look kinda related, they are most likely not. The same failures also happen on other [recent PRs](https://github.com/pytorch/pytorch/pull/65996/checks?check_run_id=3768110107).

**Comment by ejguan** [comment]
It's not related, I am working on forward fix.

**Review by NivekT — APPROVED** [review]
LGTM. Thanks for fixing it!

**Pull request closed without merging**
