### PR TITLE
Rename caffe2::TypeIdentifier to at::DataType

### PR DESCRIPTION
**Pull request by ezyang**
Summary:
```
codemod -d . --extensions cc,h TypeIdentifier at::DataType
```

plus edits by hand

Differential Revision: D9296116

### CODE REVIEW

**Comment by dzhulgakov** [comment]
Is this diff absolutely necessary atm? The are several PRs in flight that touch actively affected files:
- @jerryzh168's tensor/storage split
- @orionr work on build unification which adds annotations to multiple functions and every rebase is really painful

Maybe minimize the blast-renames for now until unified build lands?

**Comment by ezyang** [comment]
Luckily for you, android-instrumentation flakiness prevented this from landing. I'll land this later. (In my defense: a few weeks ago I renamed CaffeTypeId to TypeIdentifier, and after more discussion I wanted to rename it to its final name before it got stuck in the codebase this way.)

**Comment by ezyang** [comment]
@dzhulgakov @jerryzh168 @orionr I plan on working around this. However, I want to point out that there is one good reason to merge this PR earlier rather than later: `operator<<`. As typeid.h is written today, if you are in a namespace which has an `operator<<` overload defined in it (e.g., `at` namespace), you cannot print TypeIdentifier using `s << x`; it will complain that no overload is eligible. This is because the non-top-level `operator<<` overload will take precedence over the global overload (which is in Caffe2) and prevent C++ from finding the global overloads.

An alternative is to fix this in Caffe2 by moving all of Caffe2's `operator<<` overload definitions into the caffe2 namespace. I'll probably submit a patch to do this.

**Comment by ezyang** [comment]
Abandoning patch. I'll retry after @smessmer's fixes land

**Pull request closed without merging**
