### PR TITLE
upgrade nccl to v2.6.4-1

### LINKED ISSUE #37325: Upgrade NCCL submodule
## Bug

When NCCL tries to use shm, it crashed with `invalid argument`:
```
eee76531b97b4a20b22160453ec02fd100000Z:8602:8602 [7] NCCL INFO Bootstrap : Using [0]eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8601:8601 [6] NCCL INFO Bootstrap : Using [0]eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8596:8596 [1] NCCL INFO Bootstrap : Using [0]eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8600:8600 [5] NCCL INFO Bootstrap : Using [0]eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8595:8595 [0] NCCL INFO Bootstrap : Using [0]eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8599:8599 [4] NCCL INFO Bootstrap : Using [0]eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8600:8600 [5] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
eee76531b97b4a20b22160453ec02fd100000Z:8599:8599 [4] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
eee76531b97b4a20b22160453ec02fd100000Z:8602:8602 [7] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
eee76531b97b4a20b22160453ec02fd100000Z:8598:8598 [3] NCCL INFO Bootstrap : Using [0]eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8597:8597 [2] NCCL INFO Bootstrap : Using [0]eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8601:8601 [6] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
eee76531b97b4a20b22160453ec02fd100000Z:8598:8598 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
eee76531b97b4a20b22160453ec02fd100000Z:8602:8602 [7] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
eee76531b97b4a20b22160453ec02fd100000Z:8598:8598 [3] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
eee76531b97b4a20b22160453ec02fd100000Z:8601:8601 [6] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
eee76531b97b4a20b22160453ec02fd100000Z:8596:8596 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
eee76531b97b4a20b22160453ec02fd100000Z:8595:8595 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
eee76531b97b4a20b22160453ec02fd100000Z:8599:8599 [4] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
eee76531b97b4a20b22160453ec02fd100000Z:8600:8600 [5] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
eee76531b97b4a20b22160453ec02fd100000Z:8597:8597 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
eee76531b97b4a20b22160453ec02fd100000Z:8595:8595 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
eee76531b97b4a20b22160453ec02fd100000Z:8596:8596 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
eee76531b97b4a20b22160453ec02fd100000Z:8597:8597 [2] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
eee76531b97b4a20b22160453ec02fd100000Z:8598:8598 [3] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8602:8602 [7] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8599:8599 [4] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8601:8601 [6] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8595:8595 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8597:8597 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8596:8596 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8600:8600 [5] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB eth0:10.0.0.13<0>
eee76531b97b4a20b22160453ec02fd100000Z:8601:9155 [6] NCCL INFO Setting affinity for GPU 6 to 0fffff
eee76531b97b4a20b22160453ec02fd100000Z:8599:9150 [4] NCCL INFO Setting affinity for GPU 4 to 0fffff
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Setting affinity for GPU 0 to 0fffff
eee76531b97b4a20b22160453ec02fd100000Z:8597:9156 [2] NCCL INFO Setting affinity for GPU 2 to 0fffff
eee76531b97b4a20b22160453ec02fd100000Z:8596:9157 [1] NCCL INFO Setting affinity for GPU 1 to 0fffff
eee76531b97b4a20b22160453ec02fd100000Z:8598:9147 [3] NCCL INFO Setting affinity for GPU 3 to 0fffff
eee76531b97b4a20b22160453ec02fd100000Z:8602:9146 [7] NCCL INFO Setting affinity for GPU 7 to 0fffff
eee76531b97b4a20b22160453ec02fd100000Z:8600:9159 [5] NCCL INFO Setting affinity for GPU 5 to 0fffff
eee76531b97b4a20b22160453ec02fd100000Z:8599:9150 [4] NCCL INFO CUDA Dev 4[2], IB NIC distance :  PXB
eee76531b97b4a20b22160453ec02fd100000Z:8600:9159 [5] NCCL INFO CUDA Dev 5[7], IB NIC distance :  PXB
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO CUDA Dev 0[0], IB NIC distance :  PXB
eee76531b97b4a20b22160453ec02fd100000Z:8596:9157 [1] NCCL INFO CUDA Dev 1[4], IB NIC distance :  PXB
eee76531b97b4a20b22160453ec02fd100000Z:8597:9156 [2] NCCL INFO CUDA Dev 2[1], IB NIC distance :  PXB
eee76531b97b4a20b22160453ec02fd100000Z:8598:9147 [3] NCCL INFO CUDA Dev 3[5], IB NIC distance :  PXB
eee76531b97b4a20b22160453ec02fd100000Z:8602:9146 [7] NCCL INFO CUDA Dev 7[3], IB NIC distance :  PXB
eee76531b97b4a20b22160453ec02fd100000Z:8601:9155 [6] NCCL INFO CUDA Dev 6[6], IB NIC distance :  PXB
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Ring 00 : 31 -> 32 [receive] via NET/IB/0
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Ring 00 : 32[0] -> 33[4] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8596:9157 [1] NCCL INFO Ring 00 : 33[4] -> 35[5] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8600:9159 [5] NCCL INFO Ring 00 : 37[7] -> 34[1] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8598:9147 [3] NCCL INFO Ring 00 : 35[5] -> 38[6] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8599:9150 [4] NCCL INFO Ring 00 : 36[2] -> 39[3] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8597:9156 [2] NCCL INFO Ring 00 : 34[1] -> 36[2] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8601:9155 [6] NCCL INFO Ring 00 : 38[6] -> 37[7] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8602:9146 [7] NCCL INFO Ring 00 : 39[7] -> 88[0] via direct shared memory

eee76531b97b4a20b22160453ec02fd100000Z:8602:9146 [7] include/shm.h:42 NCCL WARN Cuda failure 'invalid argument'
eee76531b97b4a20b22160453ec02fd100000Z:8602:9146 [7] NCCL INFO transport/shm.cc:190 -> 1
eee76531b97b4a20b22160453ec02fd100000Z:8602:9146 [7] NCCL INFO init.cc:669 -> 1
eee76531b97b4a20b22160453ec02fd100000Z:8602:9146 [7] NCCL INFO init.cc:815 -> 1
eee76531b97b4a20b22160453ec02fd100000Z:8602:9146 [7] NCCL INFO init.cc:951 -> 1
eee76531b97b4a20b22160453ec02fd100000Z:8602:9146 [7] NCCL INFO misc/group.cc:69 -> 1 [Async thread]
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Ring 00 : 16 -> 32 [receive] via NET/IB/0
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Ring 00 : 48 -> 32 [receive] via NET/IB/0
eee76531b97b4a20b22160453ec02fd100000Z:8596:9157 [1] NCCL INFO Ring 00 : 33[4] -> 32[0] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8600:9159 [5] NCCL INFO Ring 00 : 37[7] -> 38[6] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8599:9150 [4] NCCL INFO Ring 00 : 36[2] -> 34[1] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8598:9147 [3] NCCL INFO Ring 00 : 35[5] -> 33[4] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8601:9155 [6] NCCL INFO Ring 00 : 38[6] -> 35[5] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8597:9156 [2] NCCL INFO Ring 00 : 34[1] -> 37[7] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Ring 00 : 32 -> 64 [send] via NET/IB/0
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Ring 00 : 64 -> 32 [receive] via NET/IB/0
eee76531b97b4a20b22160453ec02fd100000Z:8596:9157 [1] NCCL INFO Ring 01 : 33[4] -> 35[5] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8600:9159 [5] NCCL INFO Ring 01 : 37[7] -> 34[1] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8598:9147 [3] NCCL INFO Ring 01 : 35[5] -> 38[6] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8597:9156 [2] NCCL INFO Ring 01 : 34[1] -> 36[2] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8601:9155 [6] NCCL INFO Ring 01 : 38[6] -> 37[7] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Ring 00 : 32 -> 16 [send] via NET/IB/0
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Ring 00 : 32 -> 48 [send] via NET/IB/0
eee76531b97b4a20b22160453ec02fd100000Z:8600:9159 [5] NCCL INFO Ring 01 : 37[7] -> 38[6] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8598:9147 [3] NCCL INFO Ring 01 : 35[5] -> 33[4] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8601:9155 [6] NCCL INFO Ring 01 : 38[6] -> 35[5] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8601:9155 [6] NCCL INFO Trees [0] 35->38->37/-1/-1 [1] 35->38->37/-1/-1
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Ring 01 : 31 -> 32 [receive] via NET/IB/0
eee76531b97b4a20b22160453ec02fd100000Z:8601:9155 [6] NCCL INFO comm 0x7f9ff00025f0 rank 38 nranks 104 cudaDev 6 nvmlDev 6 - Init COMPLETE
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Ring 01 : 32[0] -> 33[4] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8598:9147 [3] NCCL INFO Trees [0] 33->35->38/-1/-1 [1] 33->35->38/-1/-1
eee76531b97b4a20b22160453ec02fd100000Z:8598:9147 [3] NCCL INFO comm 0x7f87580025f0 rank 35 nranks 104 cudaDev 3 nvmlDev 5 - Init COMPLETE
eee76531b97b4a20b22160453ec02fd100000Z:8596:9157 [1] NCCL INFO Ring 01 : 33[4] -> 32[0] via P2P/IPC
eee76531b97b4a20b22160453ec02fd100000Z:8596:9157 [1] NCCL INFO Trees [0] 32->33->35/-1/-1 [1] 32->33->35/-1/-1
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Ring 01 : 32 -> 24 [send] via NET/IB/0
eee76531b97b4a20b22160453ec02fd100000Z:8596:9157 [1] NCCL INFO comm 0x7f10b80025f0 rank 33 nranks 104 cudaDev 1 nvmlDev 4 - Init COMPLETE
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Ring 01 : 24 -> 32 [receive] via NET/IB/0
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO Trees [0] 64->32->33/16/48 [1] 24->32->33/-1/-1
eee76531b97b4a20b22160453ec02fd100000Z:8595:9154 [0] NCCL INFO comm 0x7fad980025f0 rank 32 nranks 104 cudaDev 0 nvmlDev 0 - Init COMPLETE
```

We noticed that pytorch has NCCL 2.4.8 embedded.
For now we used `NCCL_SHM_DISABLE=1` as an workaround.
This issue has been fixed in 2.6.4 and we confirmed on our side, so maybe it's time to upgrade.

## Environment
 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake+ninja+gcc-8
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: V100

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

### PR DESCRIPTION
**Pull request by agolynski**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#37506 upgrade nccl to v2.6.4-1**

Closes gh-35363, closes gh-29093

### CODE REVIEW

**Review by mrshenli — CHANGES_REQUESTED** [review]
Thanks a lot for bumping up NCCL version. Looks like there are some test failures in `pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test`.

```
Apr 29 17:05:40   test_shared_allgather_nccl (__main__.ProcessGroupShareTensorTest) ... Process SpawnProcess-5:
Apr 29 17:05:40 Traceback (most recent call last):
Apr 29 17:05:40   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Apr 29 17:05:40     self.run()
Apr 29 17:05:40   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Apr 29 17:05:40     self._target(*self._args, **self._kwargs)
Apr 29 17:05:40   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_spawn.py", line 172, in _test_allgather_process
Apr 29 17:05:40     pg.allgather(ys, xs).wait()
Apr 29 17:05:40 RuntimeError: NCCL error in: /var/lib/jenkins/workspace/torch/lib/c10d/ProcessGroupNCCL.cpp:514, unhandled system error, NCCL version 2.6.4
Apr 29 17:05:40 Process SpawnProcess-6:
Apr 29 17:05:40 Traceback (most recent call last):
Apr 29 17:05:40   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Apr 29 17:05:40     self.run()
Apr 29 17:05:40   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Apr 29 17:05:40     self._target(*self._args, **self._kwargs)
Apr 29 17:05:40   File "/var/lib/jenkins/workspace/test/distributed/test_c10d_spawn.py", line 172, in _test_allgather_process
Apr 29 17:05:40     pg.allgather(ys, xs).wait()
Apr 29 17:05:40 RuntimeError: NCCL error in: /var/lib/jenkins/workspace/torch/lib/c10d/ProcessGroupNCCL.cpp:514, unhandled system error, NCCL version 2.6.4
```

BTW, could you please also import this to phab to see if there are any test failures there. Thx!

**Comment by agolynski** [comment]
Seems like one test failure has been addressed here: https://github.com/pytorch/pytorch/pull/37427

16:41:25 ======================================================================
16:41:25 FAIL: test_tiny_half_norm_ (__main__.TestCuda)
16:41:25 ----------------------------------------------------------------------
16:41:25 Traceback (most recent call last):
16:41:25   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 699, in wrapper
16:41:25     method(*args, **kwargs)
16:41:25   File "test_cuda.py", line 1820, in test_tiny_half_norm_
16:41:25     self.assertGreater(b.norm().item(), 0)
16:41:25 AssertionError: 0.0 not greater than 0
16:41:25

**Comment by mrshenli** [comment]
> Seems like one test failure has been addressed here: #37427

No, it's not the ROCm test, it is the `pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test`. That CI run hasn't finished yet, but you can access the CI page to see on going logs (https://app.circleci.com/pipelines/github/pytorch/pytorch/161827/workflows/5db73e36-ea33-482c-9e0b-2988a990f4a4/jobs/5293879/steps)

**Comment by agolynski** [comment]
> > Seems like one test failure has been addressed here: #37427
> 
> No, it's not the ROCm test, it is the `pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test`. That CI run hasn't finished yet, but you can access the CI page to see on going logs (https://app.circleci.com/pipelines/github/pytorch/pytorch/161827/workflows/5db73e36-ea33-482c-9e0b-2988a990f4a4/jobs/5293879/steps)

Oh, I was just replying to myself since I saw the failure and investigated it. I'll take a look at xenial.

**Comment by mrshenli** [comment]
@agolynski any update on this PR? Will we be able to get this for v1.6?

**Comment by mrshenli** [comment]
NCCL 2.7.3 has been released #40095

**Comment by mrshenli** [comment]
This PR is superseded by #40622

**Comment by malfet** [comment]
Should this one be closed then?

**Pull request closed without merging**
