### PR TITLE
[CI] Fix sccaching of nvcc builds

### LINKED ISSUE #105004: CUDA builds taking ~2x longer
After https://github.com/pytorch/pytorch/pull/104035 the build times of cuda jobs increased a lot.  For example, sm86 went from ~25min to ~45min.  The cpu build time also increased after that commit but decreased to normal afterwards.  Looking at the sccache stats for sm86, it usually got 300+ hits for cuda before that PR but only 4 afterwards, but the PR only updated the triton rocm pin.  A new docker image got built though, so that might be related.

https://hud.pytorch.org/hud/pytorch/pytorch/5364366f8c33f59f89070c7f73cffaef653d8d54/1?per_page=100&name_filter=sm86

cc @seemethere @malfet @pytorch/pytorch-dev-infra

### PR DESCRIPTION
**Pull request by malfet**
In cmake-3.26 or newer, `--options-file` is used, which renders nvcc outputs uncacheable by `sccache`, which were enable for CUDA-11 or newer builds by default by https://github.com/Kitware/CMake/commit/6377a43814bb6f3087b731644bb61302a3fc3c55

Fix it by disabling RESPONSE_FILE use for CUDA compilation.
Test Plan: Check that `multiple input files` stats in `PyTorch Build Statistics` is down to 13 files again, see https://github.com/pytorch/pytorch/actions/runs/5801865789/job/15727069855?pr=106811#step:10:42423

Fixes https://github.com/pytorch/pytorch/issues/105004

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Comment by seemethere** [comment]
I'm curious to see the TTS graph after this change is merged in 👀

**Review by albanD — COMMENTED** [review]
Out of curiosity, how did you find out? Any way we could automatically detect such things?

**Comment by malfet** [comment]
> I'm curious to see the TTS graph after this change is merged in 👀

We should be down from 50 min to 20 min

> I'm also wondering if this could be fixed on the `sccache` side as well

Sure, but it might be a bit more involved and `--options-file` doesn't really give any perf gain

**Comment by malfet** [comment]
> Out of curiosity, how did you find out? Any way we could automatically detect such things?

@clee2000 reported a performance slow down and then today we did a bit of a log-diffing to figure out what had happened (increased number of non-cacheable runs in `multiple input files` category, that eventually could be traced back to change in generated makefile) I've tried to document the process in the issue

**Pull request closed without merging**
