### PR TITLE
[ao][sparsity] Support for embeddings and embedding bags in BaseDataSparsifier

### PR DESCRIPTION
**Pull request by macandro96**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #79535
* #79534
* __->__ #79254
* #79253
* #79427
* #79252
* #79251

Added the embedding and embedding bags in the supported data types. Currently, the base data sparsifier extracts the weight
and stores it as a parameter in the internal module container whose requires_grad=False. The embeddings inside the data sparsifier
are non-trainable

Test Plan:
```python test/test_ao_sparsity.py TestBaseDataSparsifier```

Differential Revision: [D37164118](https://our.internmc.facebook.com/intern/diff/D37164118)

### CODE REVIEW

**Review by HDCharles — CHANGES_REQUESTED** [review]
this has the same problem as the last one, the tests are just getting longer and longer, they need to be broken up logically so that the errors are more meaningful and its easier for a user to look at them and quickly understand what is going on.

**Review by z-a-f — APPROVED** [review]

**Comment by macandro96** [comment]
@macandro96 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37164118).

**Comment by macandro96** [comment]
@macandro96 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37164118).

**Comment by macandro96** [comment]
@macandro96 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37164118).

**Pull request closed without merging**
