### PR TITLE
Migrate nonzero from TH to ATen (CPU)

### LINKED ISSUE #24745: Migrate `nonzero` from the TH to Aten (CPU)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

### PR DESCRIPTION
**Pull request by peterbell10**
Resubmit of #58811, Closes gh-24745

The existing PR (gh-50655) has been stalled because `TensorIterator` doesn't guarantee iteration order in the same way that `TH_TENSOR_APPLY` does. For contiguous test cases this isn't an issue; but it breaks down for example with channels last format. I resolve this by adding a new `TensorIteratorConfig` parameter, `enforce_linear_iteration`, which disables dimension reordering. I've also added a test case for non-contiguous tensors to verify this works.

This PR also significantly improves performance by adding multithreading support to the algorithm.  As part of this, I wrote a custom `count_nonzero` that gives per-thread counts which is necessary to write the outputs in the right location.

|    Shape   |  Before | After (1 thread) | After (8 threads) |
|:----------:|--------:|-----------------:|------------------:|
| 256,128,32 | 2610 us |          2150 us |            551 us |
| 128,128,32 | 1250 us |          1020 us |            197 us |
|  64,128,32 |  581 us |           495 us |             99 us |
|  32,128,32 |  292 us |           255 us |             83 us |
|  16,128,32 |  147 us |           126 us |             75 us |
|  8,128,32  |   75 us |            65 us |             65 us |
|  4,128,32  |   39 us |            33 us |             33 us |
|  2,128,32  |   20 us |            18 us |             18 us |
|  1,128,32  |   11 us |             9 us |              9 us |

### CODE REVIEW

**Comment by peterbell10** [comment]
@JackCaoG any idea why these changes might be triggering XLA to segfault?

**Comment by ngimel** [comment]
If xla's implementation internally used count_nonzero, then changes to its dispatch could affect it, but I'm just guessing.

**Comment by ngimel** [comment]
Funny thing is, in pytorch's indexing implementation, when `nonzero` output is contiguous, then discontiguous slices would be used as indices https://github.com/pytorch/pytorch/blob/5c189946746599d47479c16f097dcc1beeecd7e0/aten/src/ATen/native/IndexingUtils.h#L43, and this PR fixes it and actually makes those slices contiguous. But I don't know what XLA implementation is doing.

**Comment by peterbell10** [comment]
@ngimel would it be reasonable to leave the output as contiguous for now and try to figure out the XLA issues in another PR.

**Comment by ngimel** [comment]
@peterbell10 yes, let's do that. 
@ailzhang, @JackCaoG we need `nonzero` to return a discontiguous tensor so that behavior is consistent with cuda, and indexing and sparse operations that depend on `nonzero` can get contiguous indices after `nonzero` return is chunked on the last dimension. XLA doesn't have strides, so it segfaults on attempts to allocate a discontiguous output tensor. What can we do to achieve the behavior we want on the cpu, while still keeping XLA happy?

**Review by ngimel — APPROVED** [review]

**Comment by ailzhang** [comment]
@peterbell10 Thanks a lot for separating the change! If you send a PR to return non-contiguous output and cc me on it, I can take a look and see if there's anything we can do to unblock. Thanks!!

**Comment by leslie-fang-intel** [comment]
Hi @peterbell10. Thanks for the PR. I have one question, what will happen if I invoke the new nonzero in C++ with openmp.
For example:
```
# pragma omp parallel for simd schedule(static) if (omp_get_max_threads() > 1 && !omp_in_parallel())
for(int i=0;i<bs;i++){
   at::Tensor mask_index = at::nonzero(score > 0.05).squeeze(1);
}
```

**Comment by ngimel** [comment]
You cannot do this, `omp parallel` is the same in spirit as `parallel_for` #56794

**Comment by leslie-fang-intel** [comment]
Thanks for the comment.
Here is the case, I have a customized operations which will use `at::nonzero`
```
void my_customized_op(){
  at::nonzero();
}

at::parallel_for(0, numel, internal::GRAIN_SIZE, [&] (int64_t begin, int64_t end) {
  my_customized_op();
}
```
Openmp can't be nested. So It's expected that `at::nonzero` run with single thread in this case.
But I suspect in current implementation, `at::nonzero` will still create DimVector with unexpected num_threads sizes since it's not judge whether `at::nonzero` is in a nested openmp ENV or not.
https://github.com/pytorch/pytorch/blob/1c502d1f8ec861c31a08d580ae7b73b7fbebebed/aten/src/ATen/native/TensorAdvancedIndexing.cpp#L1549-L1550

And I am not sure: in this case what's the behavior of `at::nonzero`? I suspect I have got a different result but I may need more debug effort.

**Comment by ngimel** [comment]
According to the linked issue you cannot use tensor operations inside `parallel_for`, you example is not valid.

**Comment by leslie-fang-intel** [comment]
Sorry for the confusion. Actually I am using `OPENMP` for `my_customized_op`. 
```
void my_customized_op(){
  at::nonzero();
}

# pragma omp parallel for simd schedule(static) if (omp_get_max_threads() > 1 && !omp_in_parallel())
for(int i=0;i<bs;i++){
   my_customized_op();
}
```
It works previously. And I suspect the results got changed once we use the version of parallelized `at::nonzero`.

**Comment by peterbell10** [comment]
Is your question theoretical, or are you actually getting errors and/or wrong results?

Inside an existing `omp parallel` region, `parallel_for` should run single threaded. The single threaded case is known to work, since that's used for all inputs with fewer than ~32000 elements already. So, in theory I don't think there should be anything wrong here.

As for why, the `DimVector` is zero-initialized so it just sums the list `[num_nonzero, 0, 0, ...]` at the end, and there should be no problem at all.

**Comment by leslie-fang-intel** [comment]
Here are some thoughts for what I see in the UT with 2 threads: since we are using `lazy_init_num_threads`. https://github.com/pytorch/pytorch/blob/59b10036d557cf99df90a25d3a3a04d6312ac4f6/aten/src/ATen/ParallelOpenMP.h#L26
It will init the threads_number at the first time hit `parallel_for` inside a specific thread. So here are the cases:

- For the main thread, tid=0:

  Start running the `parallel_for`  inside the UT  => hit `lazy_init_num_threads` inside `parallel_for` and init the threads number as 2 => running `non_zero` op => create the `thread_begin` with size of 2 =>hit `parallel_for` inside `non_zero` again inside the `non_zero` op, but it will ignore `lazy_init_num_threads` since `init` is a thread_local var
  https://github.com/pytorch/pytorch/blob/59b10036d557cf99df90a25d3a3a04d6312ac4f6/aten/src/ATen/Parallel.h#L32
  So for the main thread, any time you invoke `at::get_num_threads()`, it will returns 2.


- For the second thread, tid=1:
 it will not do what's the main thread doing => Directly enter into `non_zero` op => create the `thread_begin` with size of 2 =>hit `parallel_for` inside `non_zero` again, init `lazy_init_num_threads` but here the `num_threads` is 1 now since we are inside a nested `openmp` region
https://github.com/pytorch/pytorch/blob/59b10036d557cf99df90a25d3a3a04d6312ac4f6/aten/src/ATen/ParallelOpenMP.cpp#L37
=> start running the `non_zero` in the second loop => create the `thread_begin` with size of 1, but the tid of current thread is still 1.

With some tests, if I move `lazy_init_num_threads` after https://github.com/pytorch/pytorch/blob/59b10036d557cf99df90a25d3a3a04d6312ac4f6/aten/src/ATen/ParallelOpenMP.h#L31-L34, it can workaround the issue we see.

CC @jgong5 for the discussion here.

**Pull request closed without merging**
