### PR TITLE
[Update init.py]: Support independent random generator without resetting global seed

### PR DESCRIPTION
**Pull request by zuoxingdong**

### CODE REVIEW

**Comment by soumith** [comment]
i'm supportive of accepting this. needs updating of docstrings, as well as adding tests

**Comment by zuoxingdong** [comment]
I am not sure why there is a file conflicts about `test_nn.py`, I copied the entire file from latest master branch and make corresponding change, it still shows conflicts.

**Review by soumith — CHANGES_REQUESTED** [review]
please request a re-review once CI is in working state

**Comment by zuoxingdong** [comment]
Couldn't find a way to resolve this conflicting file problem, I'm going to close this and resend a fresh PR at #30234

**Pull request closed without merging**
