### PR TITLE
ONNX: Use correct opset version in symbolic_caffe2 operators

### PR DESCRIPTION
**Pull request by take-cheeze**
Due to change to Pad-11 exporting model with symbolic_caffe2 operators cause incorrect output for AveragePool-11.
To avoid it symbolic_caffe2 should use fallback operators with correct opset version.

cc @BowenBao @neginraoof

### CODE REVIEW

**Review by houseroad — CHANGES_REQUESTED** [review]
Please fix the build and tests.

**Review by houseroad — CHANGES_REQUESTED** [review]
Tests still fail

**Comment by garymm** [comment]
@take-cheeze if you'd like to get this merged, please rebase, fix the tests and reply.

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.

**Pull request closed without merging**
