### PR TITLE
[MPS] Add L1 loss test

### PR DESCRIPTION
**Pull request by qqaatw**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by qqaatw** [comment]
Hi @DenisVieriu97,

The impl was removed because l1 loss was made composite implicit autograd recently #79804, which means all the operators in the forward pass have their backward pass defined and work for all backends. Thus, the backward pass of l1 loss is no longer needed as all the operators are differentiable already.

**Review by albanD — APPROVED** [review]
SGTM

**Comment by malfet** [comment]
@albanD you've forgotten to add `ciflow/trunk`, so it might fail when running the tests on M1

**Comment by albanD** [comment]
My bad!
All is good though, it is green in master: https://github.com/pytorch/pytorch/runs/7046235287?check_suite_focus=true

**Pull request closed without merging**
