### PR TITLE
[de-deprecation] De-deprecate some warnings that hurt usability

### PR DESCRIPTION
**Pull request by bwasti**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#21999 [de-deprecation] De-deprecate some warnings that hurt usability**

Differential Revision: [D15925892](https://our.internmc.facebook.com/intern/diff/D15925892)

### CODE REVIEW

**Comment by bwasti** [comment]
I don't think these should be warnings, but rather something that is documented in a guide for users who need the perf.  I understand that there are implicit copies but I think the usability is more important at the moment.

**Review by smessmer — CHANGES_REQUESTED** [review]
How does this hurt usability?

Note that documentation is not enough. Once developers see a `std::unordered_map` based API, they'll choose it and not even know it's slow. They won't read the documentation. This is true for external people but also for internal people. Offering this API without some kind of warning will result in many usages of this API throughout our code base. PyTorch will have bad performance.

Using `torch::List` or `torch::Dict` isn't much harder than using the STL types and is safer. If somebody really wants to use the STL types and is ok with slowness, they're probably willing to be shown a warning for it.

**Comment by ZolotukhinM** [comment]
@smessmer I complained about it here as well: https://github.com/pytorch/pytorch/pull/21712

Reciting my reply here:

> Could we disable these warning until they are fixed? Right now every build spits several screens of such warnings. While I agree that we should migrate from the deprecated API to the new one, I don't see a value in having these warnings enabled until majority of them is fixed - even if I add a new use-case of the deprecated API I would not notice that.

Basically, unless we fix most of them first, they are useless and probably even harmful because nobody is going to read all of them and probably will skip new warnings if they appear.

**Comment by bwasti** [comment]
>Once developers see a std::unordered_map based API, they'll choose it and not even know it's slow.
>PyTorch will have bad performance.

Are there benchmarks to support this?  I agree that we should evaluate the tradeoff between performance and usability.  I think the usability associated with the C++ STL is quite important.

To address this claim directly:
>Using torch::List or torch::Dict isn't much harder than using the STL types and is safer. 

1. Documentation

`std::unordered_map` is well supported by [C++ documentation](https://en.cppreference.com/w/cpp/container/unordered_map) and [stackoverflow](https://www.google.com/search?q=std%3A%3Aunordered_map%20site%3Astackoverflow.com&ved=2ahUKEwjl343y1_biAhWFtp4KHZqIAxcQ2wF6BAgHEAg&ei=i8MKXaXuDoXt-gSakY64AQ).  This may seem small but it quickly adds up.

For one, I can't find torch::Dict anywhere in the codebase.  I'm using https://bddppq.github.io/codebrowser/pytorch/pytorch/ to search for it.  Is it documented somewhere?  I will assume I can refer to `c10::DictPtr` instead. Regardless, I cannot find either documented on pytorch.org, nor in any README in the github repository.

2. Example use cases

Suppose a user doesn't realize initializer lists require curly braces and tries to instantiate a `std::unordered_map`.  They can quickly discover a solution:
https://stackoverflow.com/questions/44641395/initialize-unordered-map-in-the-initializer-list
But if they use DictPtr, that solution not only is hard to search for but also doesn't work.  On top of that, DictPtr requires `make_dict` to instantiate.  Otherwise they get an error that gives no indication of the proper function to use.

```
error: use of deleted function ‘c10::DictPtr<Key, Value>::DictPtr() [with Key = long int; Value = std::__cxx11::basic_string<char>]’
```

Users may want to use a single map container rather than swapping around between two different map containers in their code.  Somewhat surprisingly, DictPtr only handles IValue types, and would require two basically identical APIs to be used next to each other.  Attempting to use a DictPtr on a user defined type results in a hard to read 324 line error on gcc7.3

I'm not claiming these are bad API decisions for DictPtr, but rather saying that they create idiosyncrasies that require folks to learn a new API when they really shouldn't need to.

3. Deprecation warnings

As it stands there are about 80 deprecation warnings while building pytorch.  I don't think any user will read theirs among these.  gcc7.3 doesn't seem to even print the deprecation message suggesting to use a different container.

It seems restrictive to delete these APIs (which is what deprecation implies will happen) for the sake of performance.  It also misdirects the focus of APIs towards restricting the user from making bad performance decisions rather than empowering the user to make good performance decisions.  Performance tools and tutorials can go a long way to helping ensure folks who care about perf get what they're expecting out of Pytorch.

**Comment by suo** [comment]
I agree with @ZolotukhinM. Regardless of whether or not this acceptable performance overhead, we should not put a deprecation warning on this API and pollute everyone's builds without a plan to migrate existing callsites or consensus on what we want the TorchScript C++ API to look like.

I'm going to accept this PR for now to reduce built spew and we can revisit the API design question after.

**Review by suo — APPROVED** [review]

**Comment by smessmer** [comment]
Do we have code in our repository that uses the deprecated APIs and shows the warnings? That should definitely be fixed, I thought I caught these. I agree that just showing warnings to everybody is worse than not showing them at all - we should show them only if it's actually the users mistake.

If these places are hard to fix, we can temporarily de-deprecate these but I want to re-introduce the deprecation before we cut PyTorch 1.2. It's probably easier to keep the deprecation and fix these places. Can you point me to them?

We got a 4-5x speedup of an internal op recently by noticing that it was implemented with `unordered_map` and switching it to `torch::Dict` instead. The perf gains are real. Btw, It was renamed from `torch::DictPtr` to `torch::Dict` in a PR yesterday.

**Comment by smessmer** [comment]
Ah seems the deprecation warnings are only shown in an oss build. I'm working on fixing them now.

**Pull request closed without merging**
