### PR TITLE
Fix a static initialization order fiasco in c10d

### PR DESCRIPTION
**Pull request by ppwwyyxx**
The `TORCH_LIBRARY_IMPL` registrations in `OpsImpl.cpp` needs to happen after `ProcessGroup` is registered as a torch class -- which happens in `Ops.cpp`. However, the order of the registrations is undefined between the two files.

If the registration in `OpsImpl.cpp` runs before `Ops.cpp`, we get a crash at program launch similar to #83255 . This happens in our internal build.

This PR moves `OpsImpl.cpp` to the end of `Oops.cpp`. Because according to the omniscient lord of chatGPT:

### CODE REVIEW

**Review by kwen2501 — APPROVED** [review]
Cc @H-Huang
Thanks @ppwwyyxx for catching this. Looks valid.

**Comment by kwen2501** [comment]
Hi @ppwwyyxx Btw, just to confirm --
If `TORCH_LIBRARY_IMPL` is in an external library (i.e. an extension for PyTorch), there wouldn't be a registration fiasco issue, right?
I am thinking that the registration of `ProcessGroup` would always happen before the external `IMPL` registration, because `import torch` should happen before `import <torch_extension>`.

**Comment by ppwwyyxx** [comment]
As long as extensions live in a separate `.so`, then it's always safe. Because `extension.so` would depend on `libtorch.so` and is guaranteed to be un-loadable before libtorch is loaded. So all libraries will be forced to do the right thing of `import torch` before loading any extension.

**Comment by kwen2501** [comment]
Thanks for the confirmation!

**Review by H-Huang — APPROVED** [review]
Thanks for fixing, LGTM!

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
@ppwwyyxx now we have merge conflicts. Sorry about that but you'll have to fix them and we'll have to give this land process another shot after that.

**Comment by ppwwyyxx** [comment]
Sure, now it's rebased.

**Pull request closed without merging**
