### PR TITLE
Enable channels_last format for FSDP

### PR DESCRIPTION
**Pull request by alexander-zinoviev**
Enable FSDP to deal with channels_last memory formatted tensors. Preserving channels_last memory format makes FSDP compatible with the best kernels CUDNN offers.

Summary of changes:
1) Store strides information along with shapes
2) Replace calls to flatten() with as_strided(size=(param.numel(),), stride=(1,)) for flattening
3) Replace calls to view() with as_strided with the stored sizes and strides for unflattening

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Comment by awgu** [comment]
I think there is some risk here that adding `as_strided` calls on each parameter will regress performance for internal models especially sensitive to CPU overhead.

**Comment by alexander-zinoviev** [comment]
> I think there is some risk here that adding `as_strided` calls on each parameter will regress performance for internal models especially sensitive to CPU overhead.
> 
> It is not as elegant, but it may be better for the existing code path to not be modified (so overhead is only incurred if using channels last).

@awgu thank you for the review.

I am open to have the two separate code paths too. I updated the PR to have the contiguous tensors be still processed with flatten/view pair as before and the channels_last tensors with as_strided/as_strided.

As for the performance measurement the isolated as_strided() pair itself is approximately 10% slower than the isolated flatten()/view() pair itself in my local runs. It is probably still an unnoticeable fraction of the whole FSDP flow.

**Comment by alexander-zinoviev** [comment]
@awgu friendly ping

**Review by awgu — APPROVED** [review]
LGTM! Thanks!

**Comment by alexander-zinoviev** [comment]
@XilunWu @wanchaol

**Pull request closed without merging**
