### PR TITLE
Handle complex optimization in AdamW by treating complex numbers as 2D real numbers

### PR DESCRIPTION
**Pull request by zaxtax**
This commit partially addresses #65711

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Missing test, but LGTM otherwise

**Comment by zaxtax** [comment]
Tests rely on `_test_complex_2d` which is in #80279

**Comment by albanD** [comment]
Ok, so we have to wait for the other one to land before being able to add the test here?

**Comment by zaxtax** [comment]
Yes. Particularly if we want tests.

**Review by albanD — APPROVED** [review]
SGTM

**Pull request closed without merging**
