### PR TITLE
log guard_size_oblivious call sites

### PR DESCRIPTION
**Pull request by bobrenjc93**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #143467

This makes it much easier to know what's going on when we guard on data dependent operations. Currently if we throw on guard on data dependent, we only show the python invocation that caused it (not the underlying leaf c++ call which truly causes it). 

For reviewers: I was torn on whether or not to make this a special thing separate to TORCH_LOGS="dynamic" but decided against it since dynamic is already opt in. The benefit is we now get much more visibility when users run with this flag on, but logs do get a bit more spewy. I'm still open to the idea of moving these logs somewhere else and maybe building a UI on top of it to make it easier to manage the information overload.

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv

### CODE REVIEW

**Comment by ezyang** [comment]
Yeah, I don't think this is a good trade. In particular, you start spewing log lines even when no guards would actually be added.

Can you describe the case you're trying to improve more? In general, GuardOnDataDependent knows (and reports) if it is being done in an oblivious way, and the frame that specified that it is size oblivious should be in the stack.

**Comment by bobrenjc93** [comment]
> Can you describe the case you're trying to improve more? In general, GuardOnDataDependent knows (and reports) if it is being done in an oblivious way, and the frame that specified that it is size oblivious should be in the stack.

Primarily being able to pinpoint the exact line that did the guard on data dependent. We can indeed pinpoint the c++ function that caused threw it, but as discussed a few weeks ago 1) you have to rerun it with a special env var that captures c++ traces 2) often times it doesn't have line level granularity (especially in the OSS checkout).

But to your point, maybe the key is to thread this file/line info to the actual guard on data dependent error so we get the best of both worlds. Will rework!

**Comment by ezyang** [comment]
It's just kind of weird because guard_size_oblivious should be in the stack anyway lol

**Comment by bobrenjc93** [comment]
So let's take the export changevar trick we discussed a few weeks ago: https://docs.google.com/document/d/1srY7J96z2cYA3Fw_eAJIRaN8EKLWyPMhh_mBi8EOjw4/edit?tab=t.0

So in the first run, there is no reference to where the `guard_size_oblivious` was called in c++

A subsequent run with `TORCHDYNAMO_EXTENDED_DEBUG_CPP=1` gives us this

```
  File "??", line 0, in at::detail::empty_strided_symint_generic(c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::Allocator*, c10::DispatchKeySet, c10::ScalarType)
  File "offloadstuff.c", line 0, in at::TensorBase at::detail::_empty_strided_generic<c10::ArrayRef<c10::SymInt> >(c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::Allocator*, c10::DispatchKeySet, c10::ScalarType)
  File "??", line 0, in at::detail::computeStorageNbytes(c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::SymInt const&, c10::SymInt const&)
  File "??", line 0, in c10::SymBool::guard_size_oblivious(char const*, long) const
  File "offloadstuff.c", line 0, in torch::impl::PythonSymNodeImpl::guard_size_oblivious(char const*, long)
```

which isn't bad but as discussed earlier 1) it's hard to find if you don't know what you're looking for since it's in the very middle of the logs 2) missing the line level granularity due to build issues

I think stepping back to my high level goal, I want the error message to evolve from

```
RuntimeError: Failed running call_method narrow(*(FakeTensor(..., size=(1, 4, 512, 64)), 2, u0 + 5, 507 - u0), **{}):
Could not guard on data-dependent expression Eq(507 - u0, 0) (unhinted: Eq(507 - u0, 0)).  (Size-like symbols: u0)
```

to

```
RuntimeError: Failed running call_method narrow(*(FakeTensor(..., size=(1, 4, 512, 64)), 2, u0 + 5, 507 - u0), **{}):
Could not guard on data-dependent expression Eq(507 - u0, 0) (unhinted: Eq(507 - u0, 0)).  (Size-like symbols: u0)
...
File "aten/src/ATen/EmptyTensor.cpp", line 157, in computeStorageNbytes
```

**Pull request closed without merging**
