### PR TITLE
[PT2E Quantization] Fix RecursionError when prepare_pt2e graph with concat of the same node

### LINKED ISSUE #129038: [PT2E Quantization] Graph with concatenation of the same node will raise RecursionError when prepare_pt2e
### 🐛 Describe the bug

Graph with **concatenation of the same node** will raise RecursionError when prepare_pt2e.

```python
import torch
import torch.export._trace
from torch import nn
from torch.ao.quantization.quantize_pt2e import prepare_pt2e
from torch.ao.quantization.quantizer.xnnpack_quantizer import (
    XNNPACKQuantizer,
    get_symmetric_quantization_config,
)

class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(3, 3, 3)

    def forward(self, x):
        x = self.conv(x)  # not neccesary to have a conv to reproduce the bug
        x = torch.cat([x, x])
        return x

model = Net()
quantizer = XNNPACKQuantizer().set_global(get_symmetric_quantization_config())
model = torch.export._trace._export(
    model, (torch.rand(1, 3, 32, 32),), pre_dispatch=True
).module()
model = prepare_pt2e(model, quantizer)
```

Output
```
Traceback (most recent call last):
  File "reproduce_cat_recursion_error_bug.py", line 28, in <module>
    model = prepare_pt2e(model, quantizer)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/quantize_pt2e.py", line 109, in prepare_pt2e
    model = prepare(model, node_name_to_scope, is_qat=False)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 470, in prepare
    edge_or_node_to_group_id = _get_edge_or_node_to_group_id(edge_or_node_to_qspec)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 196, in _get_edge_or_node_to_group_id
    input_edge_root_qspec = _unwrap_shared_qspec(qspec, edge_or_node_to_qspec, shared_with_map)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 83, in _unwrap_shared_qspec
    return _unwrap_shared_qspec(qspec, edge_or_node_to_qspec, shared_with_map)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 83, in _unwrap_shared_qspec
    return _unwrap_shared_qspec(qspec, edge_or_node_to_qspec, shared_with_map)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 83, in _unwrap_shared_qspec
    return _unwrap_shared_qspec(qspec, edge_or_node_to_qspec, shared_with_map)
  [Previous line repeated 991 more times]
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 81, in _unwrap_shared_qspec
    root = _find_root_edge_or_node(sharing_with, shared_with_map)
  File "/home/chensf/git/pytorch-quantization/env/lib/python3.8/site-packages/torch/ao/quantization/pt2e/prepare.py", line 42, in _find_root_edge_or_node
    parent = shared_with_map[edge_or_node]
RecursionError: maximum recursion depth exceeded in comparison
```

Note that `edge_or_node` is `(conv2d, cat)` when fails.

### Versions

`torch==2.3.1`

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @msaroufim @ezyang @anijain2305 @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

### PR DESCRIPTION
**Pull request by siahuat0727**
Fixes #129038

### CODE REVIEW

**Comment by siahuat0727** [comment]
Hi @jerryzh168,

Would you be able to review this PR when you have a chance? Thank you!

**Review by jerryzh168 — APPROVED** [review]
Sorry just saw this, thanks for fixing this @siahuat0727 , can you add a test in https://github.com/pytorch/pytorch/blob/main/test/quantization/pt2e/test_xnnpack_quantizer.py

**Comment by siahuat0727** [comment]
@jerryzh168 Sure

**Comment by siahuat0727** [comment]
@jerryzh168 Done. Please help review the test. Thanks!

**Comment by siahuat0727** [comment]
Hi @jerryzh168, I noticed that the checks have been triggered and have successfully passed. Would appreciate your review and any further actions that may be needed. Thanks!

**Comment by siahuat0727** [comment]
@jerryzh168 Hi, looking forward to your help

**Comment by siahuat0727** [comment]
Hi @jerryzh168, would you mind merging this? It seems that I am not authorized.

**Review by jerryzh168 — APPROVED** [review]
sorry for the delay, I haven't been looking at mentions in my notifications, thanks for the fix!

**Comment by jerryzh168** [comment]
@siahuat0727 could you manually rebase the PR to the latest main?

**Comment by siahuat0727** [comment]
Hi @jerryzh168, I've just rebased the branch onto `viable/strict`. Is it correct?

**Comment by siahuat0727** [comment]
@jerryzh168

**Comment by jerryzh168** [comment]
> Hi @jerryzh168, I've just rebased the branch onto `viable/strict`. Is it correct?

I think just rebase on main would be better

**Comment by siahuat0727** [comment]
Hi @jerryzh168, I've rebased the PR on main.

**Comment by siahuat0727** [comment]
@jerryzh168

**Comment by siahuat0727** [comment]
@jerryzh168

**Comment by jerryzh168** [comment]
sorry for the delay, I think we can merge

**Comment by siahuat0727** [comment]
Hi @jerryzh168, there’s a failing check, but it seems unrelated to this PR. Is there anything I should do to move the merge forward?

**Comment by jerryzh168** [comment]
can you just run `lintrunner -a`

**Comment by siahuat0727** [comment]
> can you just run `lintrunner -a`

Hi @jerryzh168, here is the result
```
➜  pytorch git:(fix-pt2e-concat-same-node) lintrunner -a
Warning: Could not find a lintrunner config at: '.lintrunner.private.toml'. Continuing without using configuration file.
  FLAKE8 success!
  CLANGFORMAT success!
  MYPY success!
  CLANGTIDY success!
  TYPEIGNORE success!
  TYPENOSKIP success!
  NOQA success!
  NATIVEFUNCTIONS success!
  NEWLINE success!
  SPACES success!
  INCLUDE success!
  TABS success!
  ERROR_PRONE_ISINSTANCE success!
  PYBIND11_SPECIALIZATION success!
  PYPIDEP success!
  EXEC success!
  RAWCUDA success!
  RAWCUDADEVICE success!
  ROOT_LOGGING success!
  PYBIND11_INCLUDE success!
  MYPYSTRICT success!
  DEPLOY_DETECTION success!
  ACTIONLINT success!
  TESTOWNERS success!
  TEST_HAS_MAIN success!
  CUBINCLUDE success!
  CMAKE success!
  SHELLCHECK success!
  CALL_ONCE success!
  ONCE_FLAG success!
  CONTEXT_DECORATOR success!
  WORKFLOWSYNC success!
  PYFMT success!
  COPYRIGHT success!
  LINTRUNNER_VERSION success!
  BAZEL_LINTER success!
  RUFF success!
  META_NO_CREATE_UNBACKED success!
  ATEN_CPU_GPU_AGNOSTIC success!
  MERGE_CONFLICTLESS_CSV success!
ok No lint issues.
Successfully applied all patches.
➜  pytorch git:(fix-pt2e-concat-same-node) git status   
On branch fix-pt2e-concat-same-node
Your branch is up to date with 'origin/fix-pt2e-concat-same-node'.

nothing to commit, working tree clean
➜  pytorch git:(fix-pt2e-concat-same-node) git l|head -1
8fbdac1c00a Add test for concatenation the same node
```

**Comment by siahuat0727** [comment]
I got some code modified by `lintrunner -m origin/main -a`, but it is still running. I will update it later.

**Comment by siahuat0727** [comment]
Done. @jerryzh168

**Comment by siahuat0727** [comment]
@jerryzh168

**Comment by siahuat0727** [comment]
@jerryzh168

**Comment by jerryzh168** [comment]
@siahuat0727 it looks like you have to open a PR against main, not viable/strict

**Comment by siahuat0727** [comment]
Got it, sorry, I noticed that a section in Contributing.md suggested merging to viable/strict before. I opened a new PR.

**Pull request closed without merging**
