### PR TITLE
Migrate periodic jobs to use runner determinator

### LINKED ISSUE #261: Migrate periodic.yml to use runner determinator script
Update the jobs in periodic.yml to use the runner determinator script.

### PR DESCRIPTION
**Pull request by zxiiro**
This updates the Linux & Windows jobs in periodic.yml to use the runner determinator script.

Closes: pytorch/ci-infra#261

### CODE REVIEW

**Comment by zxiiro** [comment]
Looks like periodic jobs are triggered by @pytorchbot so would need to be added to the list of allowed users for the target determinator to work.

**Review by ZainRizvi — APPROVED** [review]
Note: We have conflicts incoming with this PR Amazon2023: https://github.com/pytorch/pytorch/pull/133036/files

**Comment by zxiiro** [comment]
> Note: We have conflicts incoming with this PR Amazon2023: https://github.com/pytorch/pytorch/pull/133036/files

Thanks for the heads up. I'll rebase and adjust.

**Pull request closed without merging**
