### PR TITLE
  TunableOp hotfix

### PR DESCRIPTION
**Pull request by jeffdaily**
Fixes.
- PYTORCH_TUNABLEOP_NUMERICAL_CHECK=1 had a memory leak.
- The strided batched gemm size calculation for buffer rotation was incorrect resulting in a mem fault.

### CODE REVIEW

**Review by xw285cornell — APPROVED** [review]
@jeffdaily thanks for the fix! I wonder if we can add unit tests to tunable op?

**Review by eqy — APPROVED** [review]

**Comment by mxz297** [comment]
Still ran into memory access fault at model level. It looks like my previous repo did not fully capture the tensor layout. A new repo has been provided to @jeffdaily

**Comment by mxz297** [comment]
Resolved memory access fault observed for tunable op in internal workload.

**Review by mxz297 — APPROVED** [review]

**Pull request closed without merging**
