### PR TITLE
Enable git long paths checkout on Windows

### PR DESCRIPTION
**Pull request by huydhn**
Checking out PyTorch on Windows starts to fail after ROCm change https://github.com/pytorch/pytorch/pull/131004 in which one of the submodule path, `third_party/composable_kernel`, is getting too long https://hud.pytorch.org/pr/pytorch/pytorch/131004#31778700376

According to https://github.com/actions/checkout/issues/1285, there is no fix in GHA checkout, but we can set `git config --system core.longpaths true` to enable long paths support in Git as a workaround.

### Testing

Windows checkout is ok now https://github.com/pytorch/pytorch/actions/runs/11423112351/job/31781916540

### CODE REVIEW

**Review by wdvr — APPROVED** [review]
I think making it --global instead of --system would also work (just for one user, but doesn't matter), and looks a bit more consistent.

**Comment by huydhn** [comment]
> I think making it --global instead of --system would also work (just for one user, but doesn't matter), and looks a bit more consistent.

Oh yeah, let me update it.  I should have use `--global` instead of copy/paste it from stackoverlow :)

**Pull request closed without merging**
