### PR TITLE
[jiterator] port `erf` to jiterator

### PR DESCRIPTION
**Pull request by khushi-411**
As per title

cc @kshitij12345! :)

### CODE REVIEW

**Comment by kshitij12345** [comment]
@khushi-411 Thanks for the PR. But I am not sure if we want this. `erf` is a frequently used op so I don't think we want to jiterate for floating point path. (cc: @mruberry )

If you are interested in jiterating ops, please look at #74748 (which I see that you've already seen).

**Comment by khushi-411** [comment]
> @khushi-411 Thanks for the PR. But I am not sure if we want this. erf is a frequently used op so I don't think we want to jiterate for floating point path. (cc: @mruberry )

Oops, my bad :( no worries though :)

> If you are interested in jiterating ops, please look at https://github.com/pytorch/pytorch/issues/74748 (which I see that you've already found).

Thanks for the share, @kshitij12345! :)

**Comment by mruberry** [comment]
> @khushi-411 Thanks for the PR. But I am not sure if we want this. `erf` is a frequently used op so I don't think we want to jiterate for floating point path. (cc: @mruberry )
> 
> If you are interested in jiterating ops, please look at #74748 (which I see that you've already found).

Correct -- we're just porting complex variants to the jiterator at this time.

**Comment by khushi-411** [comment]
Closing it! :)

**Pull request closed without merging**
