### PR TITLE
added fix for #4408 and a test

### PR DESCRIPTION
**Pull request by Erotemic**
Fix for #4408, not 100% sure that it is correct, but it does suppress the error. If someone with more knowledge of the system could verify that it is the correct fix or help me understand how to verify it is correct, that would be great.

I added the MWE I provided in the issues as tests. There doesn't seem to be any similar tests of the onnx export functionality, so I added a file. Perhaps there is a better place for it. Let me know.

### CODE REVIEW

**Comment by apaszke** [comment]
Thanks for the PR! We can merge these changes once you remove `test_onnx.py`. Then, please add the tests [in this file](https://github.com/onnxbot/onnx-fb-universe/blob/master/test/test_operators.py) (you'll need to send another PR to that repo).

**Comment by Erotemic** [comment]
Done

**Review by apaszke — APPROVED** [review]

**Comment by soumith** [comment]
thank you!

**Pull request merged**
