### PR TITLE
make Optional argument in mha_forward optional

### PR DESCRIPTION
**Pull request by ZhiyuanChen**
Current `multihead_attention_forward` suffers from incorrect arguments order (optioanl arguments before non-optional arguments) and incorrect typehints.

### CODE REVIEW

**Review by jbschlosser — CHANGES_REQUESTED** [review]
Hey @ZhiyuanChen, unfortunately this change breaks backwards compatibility so we won't be able to accept it. It's not great that the API was written like this in the first place, and we'll make sure optional args are truly optional during the API rework.

**Comment by ZhiyuanChen** [comment]
> Hey @ZhiyuanChen, unfortunately this change breaks backwards compatibility so we won't be able to accept it. It's not great that the API was written like this in the first place, and we'll make sure optional args are truly optional during the API rework.

Thank you for your explanations
Maybe remove the Optional[] as of now?

**Comment by albanD** [comment]
Given how the function looks, maybe simply making `out_proj_weight` "optional" would allow you to do that?
And you can just raise an error if `out_proj_weight` is not provided?

**Comment by ZhiyuanChen** [comment]
> Given how the function looks, maybe simply making `out_proj_weight` "optional" would allow you to do that? And you can just raise an error if `out_proj_weight` is not provided?

@albanD I think that's definitely a workaround. If it still looks good to you, I'll adjust this mr

**Comment by albanD** [comment]
cc @swolchok @cpuhrsch who have been working on mha recently and might have an opinion on this?

**Comment by cpuhrsch** [comment]
@albanD as long as this doesn't break backwards compatibility I'm indifferent to this change.

@ZhiyuanChen - could I kindly ask you to update the PR description to include some more context, e.g. what does this fix and why is it an issue? Just for our reference.

**Comment by ZhiyuanChen** [comment]
> @albanD as long as this doesn't break backwards compatibility I'm indifferent to this change.

Maybe we could have a new function (e.g. multihead_attention_forward_v2) to handle this and leave the original for backward compatibilities?  

> @ZhiyuanChen - could I kindly ask you to update the PR description to include some more context, e.g. what does this fix and why is it an issue? Just for our reference.

Sure thing

**Comment by albanD** [comment]
> Maybe we could have a new function (e.g. multihead_attention_forward_v2) to handle this and leave the original for backward compatibilities?

That is not really a solution no :p Because if we go this way, then by the end of the year, we will have 10 versions of that function and it will be very confusing and hard to maintain.

**Comment by ZhiyuanChen** [comment]
> That is not really a solution no :p Because if we go this way, then by the end of the year, we will have 10 versions of that function and it will be very confusing and hard to maintain.

Ahhhh, that's true.
Damm, the original API is really a pain in the ass......
I find `Transformer` has been rewrited (ahhhh how could I missed this opportunity. 
Can I ask why we don't just integrated `mha_forward` into `MultiheadAttention`? It makes custom Attention design much easier. I mean, people do write custom Attention quite offen

**Comment by cpuhrsch** [comment]
@ZhiyuanChen - what is your take on [xFormers](https://github.com/facebookresearch/xformers/tree/main/xformers)?

**Comment by ZhiyuanChen** [comment]
> @ZhiyuanChen - what is your take on [xFormers](https://github.com/facebookresearch/xformers/tree/main/xformers)?

Transformer is an extremely complex and flexible structure (ok not that complex but it is much complex then most strcture.
I don't think it's a good idea to pass a dict. Even if it is capable of those complex strcuture, it takes more to write the JSON than just inherit and override. 
xFormers looks like too TensorFlow.

**Pull request closed without merging**
