### PR TITLE
Removed unused “device” argument in torch.frombuffer() #118273

### LINKED ISSUE #118273: “TypeError” triggered by unused “device” argument in torch.frombuffer()
### 🐛 Describe the bug

torch.frombuffer() includes a unused "device" argument (in pyi file) which is generated by
https://github.com/pytorch/pytorch/blob/main/tools/pyi/gen_pyi.py#L713

```python
            "frombuffer": [
                "def frombuffer({}) -> Tensor: ...".format(
                    ", ".join(
                        [
                            "buffer: Any",
                            "*",
                            "dtype: _dtype",
                            "count: int = -1",
                            "offset: int = 0",
                            "device: Union[_device, str, None] = None",
                            "requires_grad: _bool = False",
                        ]
                    )
                )
            ],
```

However, this argument is not parsed (Only 5 arguments) in the corresponding C++ implementation found at https://github.com/pytorch/pytorch/blob/main/torch/csrc/autograd/python_torch_functions_manual.cpp#L304

```python
static PyObject* THPVariable_frombuffer(
    PyObject* self_,
    PyObject* args,
    PyObject* kwargs) {

  HANDLE_TH_ERRORS
  static PythonArgParser parser(
      {
          "frombuffer(PyObject* buffer, *, ScalarType dtype, int64_t count=-1, int64_t offset=0, bool requires_grad=False)",
      },
      /*traceable=*/false);

  ParsedArgs<5> parsed_args;
  auto r = parser.parse(args, kwargs, parsed_args);

  if (r.idx == 0) {
    auto buffer = r.pyobject(0);
    auto dtype = r.scalartype(1);
    auto count = r.toInt64(2);
    auto offset = r.toInt64(3);
    auto requires_grad = r.toBool(4);

   # ....
}
```

As a result, attempting to use the device argument in user code will lead to a TypeError: frombuffer() got an unexpected keyword argument 'device'

```python
import torch
import array
torch.frombuffer(buffer=array.array('i', [1, 2, 3]),
                 dtype=torch.int32,
                 count=1,
                 offset=0,
                 device="cuda",
                 requires_grad=False)
```

I've noticed that the “device” parameter is not documented in the official API reference at https://pytorch.org/docs/stable/generated/torch.frombuffer.html. I am wondering whether the “device” parameter will be removed from the Python interface definition at https://github.com/pytorch/pytorch/blob/main/tools/pyi/gen_pyi.py.

Thanks !

### Versions

master
2.1.0 

cc @albanD

### PR DESCRIPTION
**Pull request by evelynmitchell**
Fixes #118273

### CODE REVIEW

**Comment by evelynmitchell** [comment]
I am an individual contributor, and the EasyCLA app will not allow me to complete the authorization.

**Comment by evelynmitchell** [comment]
I have signed the contributor agreement.

**Review by albanD — APPROVED** [review]
Thank you very much for the PR!

**Pull request closed without merging**
