### PR TITLE
Build MacOS binaries with `-Werror`

### PR DESCRIPTION
**Pull request by malfet**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #83049
* #83048

Should prevent proliferating MPS warnings
Fixes https://github.com/pytorch/pytorch/issues/82966

### CODE REVIEW

**Comment by albanD** [comment]
Why is only the x86 macos build failing? Not the arm one and not the linux build? Don't we build linux with WERROR as well?

**Comment by malfet** [comment]
> Why is only the x86 macos build failing? Not the arm one and not the linux build? Don't we build linux with WERROR as well?

We don't/can't build tests while cross-compiling. And MacOS builders have the more recent clang version than Linux ones, which detects more warnings.

**Review by albanD — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Comment by albanD** [comment]
This might trigger a couple master-only build failures for sure. But we can adapt if they are too frequent.

**Comment by malfet** [comment]
MacOS/iOS builds were the sources of frequent reverts in last few weeks anyway, so we either have to enable it on PRs and/or update our Linux clang configs clang-13

**Pull request closed without merging**
