### PR TITLE
[FSDP2] Computed grad divide factors at runtime

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125484
* #125479
* #125431

**Context**
We are interested in supporting the case where HSDP reduce-scatters but does not all-reduce in a microbatch backward. This saves communication while still saving memory. Only on the last microbatch do we need to both reduce-scatter and all-reduce. This is not implemented yet and will hopefully come in a future PR.

There is one notable part of doing this. On the last microbatch, we need to perform an accumulation step after reduce-scatter and before all-reduce. If not, then the preceding microbatch's gradients will not be contributed across the replica group. (In other words, we cannot simply accumulate _after_ all-reduce.)

Consider 32 GPUs with 4-way replication and 8-way sharding and 2 microbatches, and focus on global rank 0.
- After the first microbatch, rank 0 will have its shard of $\frac{1}{8} \sum_{i \in S(0)} g_i^{(1)}$, where we define $S(0) = \{0, 1, \dots, 7\}$ to be the ranks in its shard group and we define the $(1)$ superscript to denote the first microbatch.
- Upon the second microbatch, rank 0 after its reduce-scatter will additionally have its shard of $\frac{1}{8} \sum_{i \in S(0)} g_i^{(2)}$. If we only all-reduce this, then this second microbatch's gradients become $\frac{1}{32} \sum_{i=0, 1, \dots, 31} g_i^{(2)}$, so in total, rank 0 has $\frac{1}{8} \sum_{i \in S(0)} g_i^{(1)} + \frac{1}{32} \sum_{i=0, 1, \dots, 31} g_i^{(2)}$, which is wrong.
- Importantly, we must accumulate $\frac{1}{8} \sum_{i \in S(0)} g_i^{(1)}  + \frac{1}{8} \sum_{i \in S(0)} g_i^{(2)} = \frac{1}{8}\sum_{i \in S(0)} (g_i^{(1)} + g_i^{(2)})$ first before all-reducing to get $\frac{1}{32} \sum_{i=0, 1, \dots, 31} (g_i^{(1)} + g_i^{(2)})$.

Now, note how under this approach, we want a factor of $\frac{1}{8}$ only (i.e. reciprocal of the shard group size), not $\frac{1}{32}$, for the first microbatch's gradients.
- For bf16/fp32, since we use `ReduceOp.AVG` and we only reduce-scatter on the first microbatch, we correctly have a factor of $\frac{1}{8}$ on the first microbatch.
- For fp16, since we precompute the gradient divide factors at init time assuming always reducing over both shard and replica groups, we incorrectly have a factor of $\frac{1}{32}$ on the first microbatch, deviating from the bf16/fp32 case.

We can address this issue by matching the bf16/fp32 vs. fp16 semantics by computing the divide factors at runtime based on which process groups were passed into the reduction function (`foreach_reduce`).

**Additional Notes**
How to implement the HSDP reduce-scatter but no all-reduce is not entirely clear yet. (What is the cleanest way to do this?) We need to store the partial reduce-scatter output and check for it upon the next backward. We should also be sure to error if the set of parameters receiving gradients changes, in which case we cannot support this easily. Anyway, we will implement this in a follow-up.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

### CODE REVIEW

**Comment by awgu** [comment]
We do not have a unit test that can capture the difference between fp32/bf16 vs. fp16 division factors yet. It might be simpler to test this when we do implement reduce-scatter without all-reduce for HSDP.

I think the important thing is that we should be able to see that there _will_ be a difference if we precompute gradient divide factors purely based on whether FSDP or HSDP rather than considering which process groups are actually used for the reduction on a given microbatch.

**Comment by wanchaol** [comment]
> - Upon the second microbatch, rank 0 after its reduce-scatter will additionally have its shard of $\frac{1}{8} \sum_{i \in S(0)} g_i^{(2)}$. If we only all-reduce this, then this second microbatch's gradients become $\frac{1}{32} \sum_{i=0, 1, \dots, 31} g_i^{(2)}$, so in total, rank 0 has $\frac{1}{8} \sum_{i \in S(0)} g_i^{(1)} + \frac{1}{32} \sum_{i=0, 1, \dots, 31} g_i^{(2)}$, which is wrong.

hmm a question on this: shouldn't we also `allreduce` the first microbatch's gradients? So rank0 should also have $\frac{1}{32} \sum_{i=0, 1, \dots, 31} g_i^{(1)}$ by the time it allreduces the second microbatch's gradient?

**Comment by awgu** [comment]
> > * Upon the second microbatch, rank 0 after its reduce-scatter will additionally have its shard of 18∑i∈S(0)gi(2). If we only all-reduce this, then this second microbatch's gradients become 132∑i=0,1,…,31gi(2), so in total, rank 0 has 18∑i∈S(0)gi(1)+132∑i=0,1,…,31gi(2), which is wrong.
> 
> hmm a question on this: shouldn't we also `allreduce` the first microbatch's gradients? So rank0 should also have 132∑i=0,1,…,31gi(1) by the time it allreduces the second microbatch's gradient?

Sorry, the point of what we are trying to do is to _not_ all-reduce the first microbatch's gradients. This is to save communication. Just reduce-scattering is enough to save memory. This is a trick we _want_ to do for HSDP but have not implemented.

**Comment by wanchaol** [comment]
> Sorry, the point of what we are trying to do is to _not_ all-reduce the first microbatch's gradients. This is to save communication. Just reduce-scattering is enough to save memory. This is a trick we _want_ to do for HSDP but have not implemented. This PR is to prepare.

Oh I see, make sense, so the reason we need to do reduce_scatter is to save gradients memory so we have to do it, but we would want to allreduce at the end of all microbatches to save communication?

**Review by wanchaol — APPROVED** [review]
sgtm!

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change, I am trying to restore ROCm distributed failures in trunk https://hud.pytorch.org/pytorch/pytorch/commit/9aa7699185e4ec39077e3046dfd63244dffa9ddb' -c weird

I'm not entirely sure if the failure is related, so I'll reland the change if it's proven to be not the case:

* Add `ciflow/periodic` to run distributed ROCm jobs
* Remove `ci-td-distributed` label as this label enables TD on distributed job, and it could miss that failed test (cc @clee2000)

**Pull request closed without merging**
