### PR TITLE
[CI] add xpu test in periodic workflow

### PR DESCRIPTION
**Pull request by chuanqi129**
Works for https://github.com/pytorch/pytorch/issues/114850

### CODE REVIEW

**Comment by chuanqi129** [comment]
With the most key XPU features for release 2.5 now landed and the `ciflow/xpu` label indicating stable XPU builds/tests, according to the staging plan of XPU CI, we're ready to move to the Stage 1. In this stage, XPU builds will be triggered for every PR, but non-XPU feature PRs will still be allowed to merge even if the PR introduces an issue that breaks the XPU build. We anticipate fixing most of these issues within 2 business days, and any larger issues should be resolved within 5 business days. Hi @malfet @atalman may I have your review and comments about this stage transition of XPU CI?

**Review by EikanWang — DISMISSED** [review]

**Comment by atalman** [comment]
hi @chuanqi129 and @EikanWang  Should we add this to periodic workflow instead ?  
Here: https://github.com/pytorch/pytorch/blob/main/.github/workflows/periodic.yml
This way we can closely monitor the state of the workflow on the HUD.
Periodic builds are executed every few hours. You can take a look [here](https://hud2.pytorch.org/hud/pytorch/pytorch/main/1?per_page=50&name_filter=periodic)

**Comment by chuanqi129** [comment]
Thanks @atalman for your suggestion, may I know your concern about the xpu wheel build for each PR? According @malfet 's suggestions in https://github.com/pytorch/pytorch/issues/114850#issuecomment-1844014788 and original staging plan, the periodic workflow will be enabled in stage 2 with XPU tests.

**Review by atalman — DISMISSED** [review]

**Comment by malfet** [comment]
Hmm, considering that it's been marked unstable (see https://github.com/pytorch/pytorch/issues/127539 ) 3 hours after it was landed, let's revert and rethink the strategy here

**Comment by chuanqi129** [comment]
> Hmm, considering that it's been marked unstable (see #127539 ) 3 hours after it was landed, let's revert and rethink the strategy here

Thanks @malfet. This issue caused by the TD in CI test (both for label `ciflow/xpu` and `ciflow/preiodic`)has been enabled by default, which I mentioned before,  it caused 75% test cases will be skipped in ci tests. And after the periodic PR merged, the scheduled periodic test is not CI test, so the TD disabled and the failure exposed. I have created a PR https://github.com/pytorch/pytorch/pull/127611 to disable the TD for XPU CI test for now.
As for the failure case itself, @etaf submitted a fixing PR https://github.com/pytorch/pytorch/pull/127595 to resolve it. This PR need be landed firstly. The XPU expected failure test case TritonCodeGenTests.test_codegen_config_option_dont_assume_alignment should have been expected passed after the PR [#126261](https://github.com/pytorch/pytorch/pull/126261) merged, but due to the CI TD mechanism, this case was skipped when landing the PR.

Regarding for the staging plan, can we re-land this PR again? Any concerns and suggestions in here? @malfet @atalman

**Pull request closed without merging**
