### PR TITLE
[caffe2] Add flag to ONNXWhile to skip scoping

### PR DESCRIPTION
**Pull request by jamesr66a**
Stacked on top of https://github.com/pytorch/pytorch/pull/6909. Look at the last commit.

This makes it easier to emit from ONNX, where we're guaranteed uniqueness of names due to SSA.

### CODE REVIEW

**Review by zdevito — APPROVED** [review]
Looks good.

**Comment by jamesr66a** [comment]
@onnxbot retest this please

**Comment by jamesr66a** [comment]
@onnxbot retest this please

**Pull request merged**
