### PR TITLE
[Inductor] Record cpp kernel in PyTorch Profiler

### PR DESCRIPTION
**Pull request by jgong5**
Add an option `config.cpp.enable_kernel_profile` to record individual cpp kernel time in PyTorch Profiler.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by jgong5** [comment]
@jansel The failing case is `test_unspec` under test/dynamo but seems not related to my change. I also tested the case locally with and without my patch. Both failed. May I know how to move forward?

**Comment by jgong5** [comment]
> @jansel The failing case is `test_unspec` under test/dynamo but seems not related to my change. I also tested the case locally with and without my patch. Both failed. May I know how to move forward?

Never mind. Flaky tests...

**Pull request closed without merging**
