### PR TITLE
Add onednn quant backend

### PR DESCRIPTION
**Pull request by Xia-Weiwen**
Resolve the conflicts in https://github.com/pytorch/pytorch/pull/69820
@jerryzh168 Please review. Thanks.

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]
thanks! looks like previous error was due to a land time merge conflict, it is pretty rare.

**Comment by Xia-Weiwen** [comment]
Hi @jerryzh168. The bot asks me to add labels to this PR. Is it a must? Looks like I don't have the permission to add labels.

**Comment by jerryzh168** [comment]
oh, this is for release notes, I see, I can add this

**Comment by jerryzh168** [comment]
do we want to advertise this to user now? or maybe announce it later?

**Comment by Xia-Weiwen** [comment]
> do we want to advertise this to user now? or maybe announce it later?

Hi @jerryzh168. Shall we have a discussion on slack?
Anyway, thank you very much for reviewing and landing this PR.

**Pull request closed without merging**
