### PR TITLE
Revert #75195

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #82504

This is a short-term fix for a serious regression in functorch
(https://github.com/pytorch/functorch/issues/989).

Additional things this PR does:
- the out= tests for nn.functional.linear fail after the revert. I added
some xfails. These xfails were present in the original PR (#75195).
- the profiler tests fail on the revert, so I updated the expecttests
for the profiler tests

Test Plan:
- test offline that the functorch regression was fixed

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Review by lezcano — COMMENTED** [review]
I think we should dispatch both the out and the non out version to mm. Otherwise the divergence may bite us in the future

**Review by ezyang — APPROVED** [review]

**Comment by zou3519** [comment]
cc @JackCaoG for the XLA failure. Since this PR is doing a revert, we probably just need to revert https://github.com/pytorch/xla/pull/3154 on the XLA side

**Comment by JackCaoG** [comment]
@wonjoolee95 Can you help revert https://github.com/pytorch/xla/pull/3154 and land with this pr?

**Comment by zou3519** [comment]
> I think we should dispatch both the out and the non out version to mm. Otherwise the divergence may bite us in the future

SGTM, let me do that in this PR

**Comment by wonjoolee95** [comment]
Hey @zou3519, we opened https://github.com/pytorch/xla/pull/3814 on XLA's end. Can we update the XLA pin to `73c64a55fb096f1e132029d3decbb6f4e532cc7b` on this PR?

**Comment by zou3519** [comment]
> 

Yup, let me do that

**Comment by wonjoolee95** [comment]
> @wonjoolee95 -- what is the right order to merging {this pr, the xla-side pr} ?

When the CIs are all green on both ends, we can merge this PR first (since XLA is pinned to the fix commit already) and then the XLA PR.

**Review by atalman — APPROVED** [review]

**Pull request closed without merging**
