### PR TITLE
Disable unwrapping scalar tensors when used as outputs

### PR DESCRIPTION
**Pull request by kundaMwiza**
If the scalar tensor is an output tensor, it shouldn't be unwrapped (i.e. `.item()` called) since `tl.store` requires a pointer type for outputs. This issue only occurs for mutated buffers: the input tensor is also used as an output tensor.

Fixes #ISSUE_NUMBER

@yanboliang @jansel @ngimel 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by kundaMwiza** [comment]
@jansel I've run the halide related test locally and it passes

**Comment by kundaMwiza** [comment]
@jansel The failures look unrelated to the codegen changes.

**Comment by jansel** [comment]
@pytorchbot rebase

Let's see if this fixes things

**Comment by jansel** [comment]
@kundaMwiza can you rebase this onto the viable/strict branch of pytorch (this branch only gets updated when tests pass).

**Comment by kundaMwiza** [comment]
@jansel Looks like there are no failures now.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
