### PR TITLE
[ROCm] [ROCm 2.10+] enable fp16 dot in Caffe2 backend

### PR DESCRIPTION
**Pull request by iotamudelta**
ROCm 2.10 has a hdot implementation, use it.

### CODE REVIEW

**Review by bddppq — CHANGES_REQUESTED** [review]
Thanks for the update.

However we need to hold off this change (same as #30412).

**Comment by iotamudelta** [comment]
@ezyang added version switch, passes CI.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
INternal build failures:

```
stderr: buck-out/dbgo-cov/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/utils/hip/math_gpu.hip/caffe2/utils/hip/math_gpu.hip:1696:19: error: use of undeclared identifier 'rocblas_hdot'
  ROCBLAS_ENFORCE(rocblas_hdot(
                  ^
1 error generated.
buck-out/dbgo-cov/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/utils/hip/math_gpu.hip/caffe2/utils/hip/math_gpu.hip:1696:19: error: use of undeclared identifier 'rocblas_hdot'
```

**Pull request closed without merging**
