### PR TITLE
[ROCm] fix parallel test runners and device visibility

### LINKED ISSUE #90940: ROCM runners timeout
### 🐛 Describe the bug

We are seeing ROCM jobs timing out more frequently https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=rocm.  These jobs stuck while running tests and timeouts after 4+ hours while they normally only take about 3h to finish.  This happens on both the first and second shards and might be due to bad runners or due to a recent change (rocm5.3 migration?).  Here are some examples:

* https://hud.pytorch.org/pytorch/pytorch/commit/9b89ff0923251d2a30ceccf61120d051a687557c (worker-rocm-amd-30)
* https://hud.pytorch.org/pytorch/pytorch/commit/d6fe9838d19a5dee60410b3b9212bf10a43105a4 (worker-rocm-amd-64)
* https://hud.pytorch.org/pytorch/pytorch/commit/cdf4a80cc111b210f9ab9448da5aeea2007a0171 (worker-rocm-amd-42)

### Versions

ROCM

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @seemethere @malfet @pytorch/pytorch-dev-infra

### PR DESCRIPTION
**Pull request by jeffdaily**
Fixes #90940.  This PR revamps how tests are run in parallel as well as device visibility at the docker container and within the run_test.py test runner.

First, running multiple test modules concurrently on the same GPU was causing instability for ROCm runners manifesting as timeouts.  ROCm runners have at least 1 GPU each, but often 2 or more.  This PR allows NUM_PROCS to be set equal to the number of devices available, but also takes care to set HIP_VISIBLE_DEVICES to avoid oversubscribing any GPU.

Second, we had introduced env vars `-e ROCR_VISIBLE_DEVICES` (#91031) to prepare for two GHA runners per CI node, to split up the GPU visibility at the docker level between the two runners.  This effort wasn't fully realized; to date, we haven't had more than one runner per CI host.  We abandon this effort in favor of all GPUs being visible to a single runner and managing GPU resources as stated above.

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Review by huydhn — APPROVED** [review]
LGTM! We can try to revert https://github.com/pytorch/pytorch/commit/2965d7e11ac573e14c6a287caffde9c4b61d24a2 after this

**Comment by jeffdaily** [comment]
> LGTM! We can try to revert [2965d7e](https://github.com/pytorch/pytorch/commit/2965d7e11ac573e14c6a287caffde9c4b61d24a2) after this

No, don't revert that yet.  Distributed tests are hanging for a different reason.  Distributed tests run as part of the "serial" group of tests, with HIP_VISIBLE_DEVICES=0,1.  At this time we do not believe the distributed test hangs are related to the other hangs.

**Review by pruthvistony — APPROVED** [review]
LGTM

**Pull request closed without merging**
