### PR TITLE
Update nan_to_num prims

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #82908

### CODE REVIEW

**Comment by ngimel** [comment]
Can you please also remove type_promotion_wrapper to avoid errors like I've posted in the chat?

**Comment by eellison** [comment]
@ngimel will remove but shouldn't it just be a no-op right now, not introduce errors ?
```
    type_promoting_args=("a,"),
    type_promotion_kind=ELEMENTWISE_TYPE_PROMOTION_KIND.DEFAULT,
```
that won't do anything no ? there's only one arg

**Comment by ngimel** [comment]
Well, it does:
```
In [2]: a=torch.randn(4, device="cuda", dtype=torch.half)

In [3]: a[0]=float('inf')

In [4]: torch.nan_to_num(a)
Out[4]: 
tensor([ 6.5504e+04, -1.2881e+00, -1.2490e+00, -2.6733e-01], device='cuda:0',
       dtype=torch.float16)

In [5]: torch._refs.nan_to_num(a)
Out[5]: 
tensor([    inf, -1.2881, -1.2490, -0.2673], device='cuda:0',
       dtype=torch.float16)
```
it casts `a` to compute_type (which is fp32 for fp16 input), and then replaces `inf` with max fp32 value instead of max fp16.

**Comment by eellison** [comment]
Do you know where / how prims are being tested such that the float16 wrong dtype wasn't caught ? I guess with fake, it's probably worth adding an fp16 dtype test..

**Comment by ngimel** [comment]
Refs are compared against corresponding ops, and also the metadata of the outputs is compared. Here the dtype is correct (output is float16), but the values are not, and it's probably because reference testing is done only for fp32 (I think?), and also the difference is only when there are infs in the inputs

**Review by voznesenskym — APPROVED** [review]

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
