### PR TITLE
Update sampler.py

### PR DESCRIPTION
**Pull request by bes-dev**
Add support of custom Samplers with variate of idx type (for example tuple, list, dict, etc.) without changes in BatchSampler

### CODE REVIEW

**Review by apaszke — CHANGES_REQUESTED** [review]
Thanks, that's a good change. However, there are still a few thing that need to be addresses. This will cause the indices to remain tensors in case of almost all of the builtin samplers we have, which is generally not good for performance reasons. What we need to do before merging this is changing all our samplers to always return integers (by casting the iterator outputs). Thanks!

**Comment by ezyang** [comment]
Also this needs a test.

**Comment by BelBES** [comment]
@ezyang so, which cases should be tested for this change?

**Comment by ezyang** [comment]
You:

> Add support of custom Samplers with variate of idx type (for example tuple, list, dict, etc.)

right? How do I use the new feature? That would be a good test.

**Comment by BelBES** [comment]
@ezyang yes, it seems that such a test can be useful. Is there best practice guideline of test writing for pytorch?

**Comment by ezyang** [comment]
@pytorchbot test this please

Yes, what you should do is find tests that currently exercise torch/utils/data/sampler.py and add your test there, in the same local style. One way to find this out is to make the function purposely fail and then run the test suite to see what fails.

**Pull request closed without merging**
