### PR TITLE
Testing dict flattening

### PR DESCRIPTION
**Pull request by kittipatv**
Summary:
Testing if we need to use C++ version of flatten

Context https://fb.facebook.com/groups/1405155842844877/permalink/2379525015407950/

Differential Revision: D9771744

### CODE REVIEW

**Comment by soumith** [comment]
@kittipatv next time, do consider giving public context (i.e. no internal links).

**Review by apaszke — CHANGES_REQUESTED** [review]
There already is a function that does this in `torch/autograd/function.py`.

The internal context is that it would be nice to allow passing in dicts as inputs to ONNX graphs. The answer to this is that this is hard for now, because our ONNX exporter doesn't support dict types, and dicts are fundamentally unordered containers, so there's no single way we could use to flatten them into an argument list.

**Comment by zdevito** [comment]
I am not sure I understand, what is going to be passed to the graph in ONNX if not a dict?

**Comment by apaszke** [comment]
@zdevito I think the idea is to treat an `OrderedDict` given as input to `export` as a flat list while exporting to ONNX. If that's the only extension then I think I'm ok with adding it.

**Comment by kittipatv** [comment]
@apaszke yeah, that's right. I can workaround with namedtuple though. Closing for now.

**Pull request closed without merging**
