### PR TITLE
vendor packaging.version

### LINKED ISSUE #113940: torch.compile introduces runtime dependency on setuptools or packaging
### 🐛 Describe the bug

```python
# main.py
import torch

@torch.compile()
def fn():
    pass
```

```bash
❯ python -VV
Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32) 
[GCC 12.3.0]
❯ python -Werror main.py
[...]
ModuleNotFoundError: No module named 'packaging.version'
[...]
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```

As seen above, I don't have `packaging` installed in my env and `pkg_resources` is deprecated. Not only that, but starting with Python 3.12, `setuptools` (which supplies `pkg_resources`) will no longer be installed as part of a [`venv`](https://docs.python.org/3/whatsnew/3.12.html). Meaning, users of that will see errors when trying to use `torch.compile`.

The underlying issue, i.e. the non-declared dependency, was already reported in #71280 and highlighted again in https://github.com/pytorch/pytorch/pull/71902#issuecomment-1036250128 but never addressed.

`torch.compile` hits this because it crawls torch modules at startup:

https://github.com/pytorch/pytorch/blob/7731c97e065cffe4efe82698980a2c8297816dbd/torch/_dynamo/allowed_functions.py#L155-L158

And with that it for example hits

https://github.com/pytorch/pytorch/blob/7731c97e065cffe4efe82698980a2c8297816dbd/torch/__init__.py#L35

https://github.com/pytorch/pytorch/blob/7731c97e065cffe4efe82698980a2c8297816dbd/torch/torch_version.py#L89

That by itself would not cause the dependency issue to show up, because we only lazy load either of the packages (#71345). However, during the crawling we also check each obj we find whether it is part of a special case list 

https://github.com/pytorch/pytorch/blob/7731c97e065cffe4efe82698980a2c8297816dbd/torch/_dynamo/allowed_functions.py#L225-L233

and that in turn materializes the version

https://github.com/pytorch/pytorch/blob/7731c97e065cffe4efe82698980a2c8297816dbd/torch/torch_version.py#L86-L87

https://github.com/pytorch/pytorch/blob/7731c97e065cffe4efe82698980a2c8297816dbd/torch/torch_version.py#L75-L77

ultimately triggering the traceback above.

I think we should do one of two things:

1. Add a runtime dependency on `packaging`, i.e. have another go at #113023.
2. Vendor the relevant parts of `packaging.version` as was proposed in https://github.com/pytorch/pytorch/pull/71902#issuecomment-1036250128

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @malfet @rgommers @vfdev-5 @hauntsaninja

### Versions

2.2.0.dev20231116+cpu

### PR DESCRIPTION
**Pull request by pmeier**
Fixes #113940. This vendors the relevant parts of [`packaging==23.2.0`]() to have access to `Version` and `InvalidVersion` without taking a runtime dependency on `setuptools` or `packaging`.

I didn't find any vendoring policy so I put it under `torch._vendor.packaging`. While I have only vendored the files we need, I have not touched or trimmed the files otherwise.

### CODE REVIEW

**Comment by pmeier** [comment]
Test failures come from the fact that `torch.torch_version` publicly exposes `Version` and `InvalidVersion`, but they are defined in the private module `torch._vendor.packaging`:

```
2023-11-20T11:19:15.0771972Z Full list:
2023-11-20T11:19:15.0772362Z # torch.torch_version.InvalidVersion:
2023-11-20T11:19:15.0773438Z   - Is public: it is inside the module's (`torch.torch_version`) `__all__`
2023-11-20T11:19:15.0775547Z   - Does NOT look public: because its `__module__` attribute (`torch._vendor.packaging.version`) is not within the torch library or does not start with the submodule where it is defined (`torch.torch_version`)
2023-11-20T11:19:15.0777555Z   - You can do either of these two things to fix this problem:
2023-11-20T11:19:15.0778686Z     - To make it NOT public: remove it from the modules's (`torch.torch_version`) `__all__`
2023-11-20T11:19:15.0780322Z     - To make it look public: make sure the `__module__` is properly set and points to a submodule of `torch.torch_version`
2023-11-20T11:19:15.0781439Z # torch.torch_version.Version:
2023-11-20T11:19:15.0782250Z   - Is public: it is inside the module's (`torch.torch_version`) `__all__`
2023-11-20T11:19:15.0784470Z   - Does NOT look public: because its `__module__` attribute (`torch._vendor.packaging.version`) is not within the torch library or does not start with the submodule where it is defined (`torch.torch_version`)
2023-11-20T11:19:15.0786385Z   - You can do either of these two things to fix this problem:
2023-11-20T11:19:15.0787530Z     - To make it NOT public: remove it from the modules's (`torch.torch_version`) `__all__`
2023-11-20T11:19:15.0789071Z     - To make it look public: make sure the `__module__` is properly set and points to a submodule of `torch.torch_version`
```

There are a number of ways we can fix this:

- Set `__module__ = "torch.torch_version"` on `Version` and `InvalidVersion`
- Ignore these two attributes or better yet everything that comes from inside `torch._vendor`
- Make `torch._vendor` public, i.e. `torch.vendor`
- ...

Any preferences?

**Comment by albanD** [comment]
Why not just remove `Version` and `InvalidVersion` from the `__all__` entry on this file? There are not public APIs we're trying to expose.

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
> Why not just remove `Version` and `InvalidVersion` from the `__all__` entry on this file? There are not public APIs we're trying to expose.

I think because few compiler components have taken dependencies on those... But I agree, they don't need to be public.
Perhaps we can import then as `_Version_` and `_InvalidVersion` in `torch.version`?

**Review by malfet — APPROVED** [review]
Not sure about `_vendor` subpackage name to be frank, how about `_third_party` or `_external`? Or is `vendor` a common practice?

**Comment by pmeier** [comment]
@albanD 

> Why not just remove `Version` and `InvalidVersion` from the `__all__` entry on this file? There are not public APIs we're trying to expose.

Because that is BC breaking. They are public now. I agree that they shouldn't be public and can deprecate them in a follow-up PR.

> Not sure about `_vendor` subpackage name to be frank, how about `_third_party` or `_external`? Or is `vendor` a common practice?

I haven't done a survey. I know that `pip` uses the `_vendor` namespace: https://github.com/pypa/pip/tree/main/src/pip/_vendor

Happy with either.

**Review by albanD — COMMENTED** [review]
Empty __init__ is not needed if you just don't want to import it by default

**Review by albanD — COMMENTED** [review]
Maybe a small readme in the torch/_vendor folder explaining how this was vendored and how to update it if needed?

> Because that is BC breaking. They are public now. I agree that they shouldn't be public and can deprecate them in a follow-up PR.

I don't suggest removing them from the code, just from the list of public APIs.
Since no one does `import *` (https://github.com/search?q=%2Ffrom+torch%5C.version+import+%5C*%2F&type=code), I don't expect anyone will notice.

**Comment by pmeier** [comment]
@albanD I'll add the README as soon as we are sure that we want to vendor it in the first place. See https://github.com/pytorch/pytorch/issues/113940#issuecomment-1819293407.

**Comment by malfet** [comment]
> Empty **init** is not needed if you just don't want to import it by default

It is needed, so version of cpython would refuse to traverse packages if there are no `__init__` file (or may be I'm wrong and this decision was reverted, would love to have some PEP reference if this is no longer a requirement)

**Comment by pmeier** [comment]
@malfet You are not wrong. See all the failures like https://github.com/pytorch/pytorch/actions/runs/6935501693/job/18866134400

**Comment by malfet** [comment]
> I don't suggest removing them from the code, just from the list of public APIs. Since no one does `import *` (https://github.com/search?q=%2Ffrom+torch%5C.version+import+%5C*%2F&type=code), I don't expect anyone will notice.

+1 on this idea. Package name is a bit misleading, but nobody outside of torch should really import `torch.torch_version` package

**Review by albanD — APPROVED** [review]
Thanks for the update!

**Pull request closed without merging**
