### PR TITLE
[ROCM]: Skiptest_cudnn_convolution_relu

### PR DESCRIPTION
**Pull request by arindamroy-eng**
Fixes #{issue number}
Aten is not compiled with CUDNN support for ROCM. Hence the newly added test in test/test_nn.py, needs to be skipped.
Otherwise ROCM CI is facing test failures:
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.2-py3.6-test1/12474/console

### CODE REVIEW

**Comment by arindamroy-eng** [comment]
@jeffdaily @jithunnair-amd 
All tests passed. Please review.

**Comment by arindamroy-eng** [comment]
@ngimel @malfet

**Comment by malfet** [comment]
@arindamroy-eng can you please explain why `@skipCUDAifNoCudnn` doesn't work here? And wouldn't it be a better fix then adding extra decorator here?

**Comment by arindamroy-eng** [comment]
Hi @malfet , the @skipCUDAifNoCudnn was already there when the test was added:

https://github.com/pytorch/pytorch/pull/62482

Even then the test was getting executed on ROCM, even though ATen is not being built with Cudnn support.

As the current decorator was not working, added the Rocm specific decorator, as done in the other tests.

The test as now been disable by a similar hotfix already it seems:
https://github.com/pytorch/pytorch/commit/3beb65d45df303851c9e5c3a6dfbb206a184674b
Hence closing this PR.

**Comment by ngimel** [comment]
> @arindamroy-eng can you please explain why `@skipCUDAifNoCudnn` doesn't work here? And wouldn't it be a better fix then adding extra decorator here?

Apparently, `torch.backends.cudnn.is_acceptable()` reports `True` on ROCm if compiled with MiOpen (that's the logic used in the decorator). We could probably change that behavior, but I don't know if it would disable tests that currently work and test things for ROCm?

**Pull request closed without merging**
