### PR TITLE
Acquire GIL before THPVariable_wrap

### PR DESCRIPTION
**Pull request by gchanan**

### CODE REVIEW

**Comment by gchanan** [comment]
ok, latest commit removes the mutex.

**Review by soumith — APPROVED** [review]

**Comment by apaszke** [comment]
Is the mutex used for anything else?

**Comment by gchanan** [comment]
that's the only place it's used AFAICT

**Comment by apaszke** [comment]
Then let's remove it

**Comment by gchanan** [comment]
now removed.

**Pull request merged**
