### PR TITLE
[DTensor] Fix view op replicating on tensor dim when the size of the tensor dim = 1

### PR DESCRIPTION
**Pull request by wz337**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135054

We found a corner case that when a tensor dimension is 1, calling `view(1)` would result in an unexpected replication (see case 1 below). When the tensor dimension to shard is not 1, no matter whether the tensor dimension is evenly-shardable across the mesh dimension, it won't cause an implicit replication behind the scenes if view doesn't change the size of the given tensor dimension (see case 2 and 3).  

When the tensor dimension to shard is of size 1, it is not being added to shardable_dims here:
https://github.com/pytorch/pytorch/blob/main/torch/distributed/_tensor/ops/_view_ops.py#L518

```
# uneven case where the size of the tensor dimension to shard is 1
p = torch.randn(1,2)
mesh = init_device_mesh(“cuda”, (2,))
dtensor = distribute_tensor(p, mesh, [Shard(0)])
t = dtensor.view(1, 2) 
# this would result in replication, meaning t is now replicated across all ranks.

# uneven case where the size of the tensor dimension to shard is not 1
p = torch.randn(3, 2)
mesh = init_device_mesh(“cuda”, (2,))
dtensor = distribute_tensor(p, mesh, [Shard(0)])
t = dtensor.view(3, 2) # this would not result in replication.
# this would not result in replication, meaning t stays as sharded.

# even case
p = torch.randn(2,2)
dtensor = distribute_tensor(p, mesh, [Shard(0)])
t = dtensor.view(2, 2)
# this would not result in replication, meaning t stays as sharded.
```

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wconstab @d4l3k @c-p-i-o @tianyu-l

Differential Revision: [D62155606](https://our.internmc.facebook.com/intern/diff/D62155606)

### CODE REVIEW

**Comment by wz337** [comment]
@wz337 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D62155606).

**Comment by wz337** [comment]
@wz337 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D62155606).

**Comment by wz337** [comment]
@wanchaol Sorry to bug you but want to get your thoughts in fixing this corner case. When we have a tensor of shape (1,2,2,2) and view it as (1,2,4), without the change in this PR, we have the following `result_pp` from `view_groups` func:
```
[Singleton(), InputDim(input_dim=1), Flatten(input_dims=(InputDim(input_dim=2), InputDim(input_dim=3)))]
```

After the change, we will instead have:
```
[InputDim(input_dim=0), InputDim(input_dim=1), Flatten(input_dims=(InputDim(input_dim=2), InputDim(input_dim=3)))]
```

My question is that for both tensor dimension 0 and 1, the output dimension both maps directly to the input dimension. However, the only difference is that the size of the tensor dimension 0 is 1 vs the size of tensor dimension 1 is 2 (greater than 1). Just want to learn the context why we need to distinguish these two. From my understanding, flattening a scalar and flattening a single dimension should both be no-op, but maybe I missed some other cases. Asking because although this change fixed the corner case mentioned in the summary, it does break two of the existing tests.

**Review by tianyu-l — APPROVED** [review]
The change sounds OK to me; it seems it won't affect anything else other than allowing `view`/`reshape` to inherit the sharding layout on a size-1 dimension. Feel free to wait for Wanchao's reply.

Curious why we need to do `Shard(0)` on a size 1 dimension -- is it an outcome of FSDP sharding?

**Comment by wz337** [comment]
@wz337 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D62155606).

**Comment by wz337** [comment]
> The change sounds OK to me; it seems it won't affect anything else other than allowing `view`/`reshape` to inherit the sharding layout on a size-1 dimension. Feel free to wait for Wanchao's reply.
> 
> Curious why we need to do `Shard(0)` on a size 1 dimension -- is it an outcome of FSDP sharding?

Yes.

**Review by wanchaol — APPROVED** [review]
sgtm

**Comment by wz337** [comment]
@wz337 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D62155606).

**Pull request closed without merging**
