### PR TITLE
[MPS] Expose mps package in torch

### LINKED ISSUE #98740: torch.mps.manual_seed() attribute error
### 📚 The doc issue

Traceback (most recent call last):
  File "/Users/atatekeli/PycharmProjects/PyTorchFCC/classification.py", line 148, in <module>
    torch.mps.manual_seed(42)
AttributeError: module 'torch' has no attribute 'mps'

Followed PyTorch documentation but I got the attribute error when writing torch.mps.manual_seed()

### Suggest a potential alternative/fix

_No response_

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

### PR DESCRIPTION
**Pull request by qqaatw**
Fixes #98740

cc @albanD @razarmehr

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM

**Review by Neilblaze — APPROVED** [review]

**Pull request closed without merging**
