### PR TITLE
c10::optional -> std::optional

### PR DESCRIPTION
**Pull request by r-barnes**
Fixes issues introduced in https://github.com/pytorch/pytorch/pull/141348 and https://github.com/pytorch/pytorch/pull/139578

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by r-barnes** [comment]
Fixes issues introduced in #141348 and #139578

**Review by malfet — APPROVED** [review]
LGTM, but they will continue to appear until one writes a linter to error out if c10::optional is used

**Pull request closed without merging**
