### PR TITLE
move all external kernels into a class for better compiler error messages

### PR DESCRIPTION
**Pull request by bdhirsh**
Turns external backend kernels into class methods, so they get helpful compiler errors instead of linker errors whenever they're a schema mismatch.

I took a stab at trying to do the same for in-tree kernels, but gave up after a while. It would probably make sense to come back to it with @wenleix 's nice set of regex calls, to automatically pick up all of the native kernels in the `aten/src/ATen/native` folder.

Corresponding xla PR: https://github.com/pytorch/xla/pull/3012

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #60737 detect missing kernels from external backends in codegen
* **#59839 move all external kernels into a class for better compiler error messages**

Differential Revision: [D29047680](https://our.internmc.facebook.com/intern/diff/D29047680)

### CODE REVIEW

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29047680).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29047680).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29047680).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29047680).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29047680).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29047680).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29047680).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29047680).

**Review by ezyang — APPROVED** [review]

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29047680).

**Review by ailzhang — APPROVED** [review]
Thanks @bdhirsh !

**Pull request closed without merging**
