### PR TITLE
Update Kineto Submodule in PyTorch

### PR DESCRIPTION
**Pull request by aaronenyeshi**
Summary: Update the Kineto Submodule in PyTorch third_party/kineto.

Test Plan: GitHub CI

Differential Revision: D55875347

Pulled By: aaronenyeshi

### CODE REVIEW

**Review by sraikund16 — APPROVED** [review]
LTGM

**Comment by aaronenyeshi** [comment]
We are updating the Kineto submodule hash, we've fixed the errors introduced in ROCm builds and Windows builds in this new hash. cc @malfet , @clee2000

**Comment by jithunnair-amd** [comment]
@mwootton This Kineto bump seems to have introduced a flaky failure of the `profiler/test_profiler.py::TestProfilerCUDA::test_mem_leak` unit test. It failed multiple times before it passed in the CI run for this PR itself: https://ossci-raw-job-status.s3.amazonaws.com/log/23637114403

I reopened an issue to skip this UT in CI for ROCm: https://github.com/pytorch/pytorch/issues/110995 while we debug this

**Pull request closed without merging**
