### PR TITLE
Port silu_backward to structured

### PR DESCRIPTION
**Pull request by Freey0**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#58661 Port silu_backward to structured**

Differential Revision: [D28572530](https://our.internmc.facebook.com/intern/diff/D28572530)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28572530).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28572530).

**Comment by Freey0** [comment]
@ezyang  Do you know how structured functions work with CompositeImplicitAutograd? I looked into the code base and there doesn't seem to be any examples of it working together at the moment. Any suggestions are greatly appreciated!

**Comment by ezyang** [comment]
They don't. See https://github.com/pytorch/pytorch/issues/50953 The workaround is to NOT use structured, and just redispatch as necessary.

**Comment by Freey0** [comment]
> They don't. See #50953 The workaround is to NOT use structured, and just redispatch as necessary.

Sorry, I didn't make that clear. I know that currently CompositeImplicitAutograd and Structured Core don't work together.

But I don't know how to handle the following error.

```
May 25 12:42:30   File "/var/lib/jenkins/workspace/tools/codegen/model.py", line 342, in from_yaml
May 25 12:42:30     f"unexpected name for singleton CompositeImplicitAutograd dispatch entry: expected {cpp.name(func)} " \
May 25 12:42:30 AssertionError: unexpected name for singleton CompositeImplicitAutograd dispatch entry: expected silu_backward but got math_silu_backward.  Rename your implementation to the expected name, then delete the dispatch table
May 25 12:42:30   in /var/lib/jenkins/workspace/cmake/../aten/src/ATen/native/native_functions.yaml:3555:
May 25 12:42:30     silu_backward(Tensor grad_output, Tensor self) -> Tensor
May 25 12:42:30
```
How do I preserve the original functionality of math_silu_backward?

Any suggestions are greatly appreciated!

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28572530).

**Comment by ezyang** [comment]
OHHH you're right, this is different, I think you might need a teeny bugfix for this one

**Comment by ezyang** [comment]
```
diff --git a/aten/src/ATen/test/math_kernel_test.cpp b/aten/src/ATen/test/math_kernel_test.cpp
index 005c11cb0ea..cee59d65cbc 100644
--- a/aten/src/ATen/test/math_kernel_test.cpp
+++ b/aten/src/ATen/test/math_kernel_test.cpp
@@ -1,6 +1,7 @@
 #include <gtest/gtest.h>
 
 #include <ATen/ATen.h>
+#include <ATen/CPUFunctions.h>
 
 using namespace at;
 
@@ -105,7 +106,7 @@ TEST(MathKernelTest, Addr) {
 TEST(MathKernelTest, SiluBackward) {
   const auto input = rand({20, 10});
   const auto grad_output = rand({20, 10});
-  auto out = at::native::silu_backward(grad_output, input);
+  auto out = at::cpu::silu_backward(grad_output, input);
   auto math_out = at::native::math_silu_backward(grad_output, input);
   ASSERT_ALLCLOSE_TOLERANCES(out, math_out, 1e-4, 1e-6);
 }
diff --git a/tools/codegen/model.py b/tools/codegen/model.py
index fba3756fab1..f1ff8a19d0f 100644
--- a/tools/codegen/model.py
+++ b/tools/codegen/model.py
@@ -338,7 +338,9 @@ class NativeFunction:
             assert dispatch != {DispatchKey.CompositeImplicitAutograd: cpp.name(func)}, \
                 "unnecessary dispatch table for this function; just delete the dispatch " \
                 "key entirely"
-            assert dispatch.keys() != {DispatchKey.CompositeImplicitAutograd}, \
+            # if a function is a structured delegate, deleting the dispatch
+            # table is NOT semantics preserving
+            assert structured_delegate or dispatch.keys() != {DispatchKey.CompositeImplicitAutograd}, \
                 f"unexpected name for singleton CompositeImplicitAutograd dispatch entry: expected {cpp.name(func)} " \
                 f"but got {dispatch[DispatchKey.CompositeImplicitAutograd]}.  Rename your implementation to the expected " \
                 "name, then delete the dispatch table"
```

but also need #58569

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28572530).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28572530).

**Comment by ezyang** [comment]
it would seem the asan failure are real

**Comment by ezyang** [comment]
successfully reproduced locally

**Comment by ezyang** [comment]
fix coming

**Comment by Freey0** [comment]
Thank you very much!

Can you share your debugging experience?
Whenever I see this error, I have no way to start. (Maybe because I am a novice:smile:)

**Comment by ezyang** [comment]
> Can you share your debugging experience?
> Whenever I see this error, I have no way to start. (Maybe because I am a novice

In this particular case, I spent a day getting a local ASAN build and confirming that it indeed failed. (Mostly by staring at https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/build-asan.sh and https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/test.sh ) With debug info, I could get line numbers for this error in CI:

```
Jun 22 01:03:01 ==79==ERROR: AddressSanitizer: initialization-order-fiasco on address 0x7f7400fcd760 at pc 0x7f73de8343b9 bp 0x7ffdda1bc820 sp 0x7ffdda1bc818
Jun 22 01:03:01 READ of size 8 at 0x7f7400fcd760 thread T0
Jun 22 01:03:03     #0 0x7f73de8343b8 in std::__shared_ptr<c10::OperatorKernel, (__gnu_cxx::_Lock_policy)2>::operator=(std::__shared_ptr<c10::OperatorKernel, (__gnu_cxx::_Lock_policy)2> const&) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0xdbcb3b8)
Jun 22 01:03:03     #1 0x7f73de82609e in c10::impl::OperatorEntry::updateDispatchTableEntry_(c10::Dispatcher const&, c10::DispatchKey) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0xdbbd09e)
Jun 22 01:03:03     #2 0x7f73de8244ea in c10::impl::OperatorEntry::updateDispatchTable_(c10::Dispatcher const&, c10::DispatchKey) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0xdbbb4ea)
Jun 22 01:03:03     #3 0x7f73de8232fd in c10::impl::OperatorEntry::registerKernel(c10::Dispatcher const&, c10::optional<c10::DispatchKey>, c10::KernelFunction, c10::optional<c10::impl::CppSignature>, std::unique_ptr<c10::FunctionSchema, std::default_delete<c10::FunctionSchema> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0xdbba2fd)
Jun 22 01:03:03     #4 0x7f73de80b961 in c10::Dispatcher::registerImpl(c10::OperatorName, c10::optional<c10::DispatchKey>, c10::KernelFunction, c10::optional<c10::impl::CppSignature>, std::unique_ptr<c10::FunctionSchema, std::default_delete<c10::FunctionSchema> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0xdba2961)
Jun 22 01:03:03     #5 0x7f73de7efb3b in torch::Library::_impl(char const*, torch::CppFunction&&) & (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0xdb86b3b)
Jun 22 01:03:03     #6 0x7f73e10da140 in at::(anonymous namespace)::TORCH_LIBRARY_IMPL_init_aten_Meta_2(torch::Library&) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0x10471140)
```

First I had to remind myself what this error message meant. So I looked for the meaning of this error at https://github.com/google/sanitizers/wiki/AddressSanitizerInitializationOrderFiasco#strict-init-order-checking

Then I looked at the code, and tried to figure out what static data `updateDispatchTableEntry_` was using, with the line number in hand, and I could see it was accessing an OperatorEntry static variable. I still wasn't sure why this was not kosher, but I knew turning this into a Meyer singleton would work (from previous experience), so I did it, and confirmed in my local ASAN build that it no longer triggered the SIOF ASAN bug.

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28572530).

**Pull request closed without merging**
