### PR TITLE
Upgrade CI to ROCm 5.4

### PR DESCRIPTION
**Pull request by pruthvistony**
cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### CODE REVIEW

**Comment by pruthvistony** [comment]
Dependent PR #90694 
Will update this PR after #90694 is merged.

**Comment by pruthvistony** [comment]
Have added temporary `--continue-through-error` parameter to test execution script to get the full list of failing UTs.

**Comment by pruthvistony** [comment]
CI is green, will revert the `--continue-through-error' code change.

**Comment by pruthvistony** [comment]
ROCm test have passed -https://github.com/pytorch/pytorch/actions/runs/4021085854/jobs/6909866888
Not sure why the CUDA and CPU related jobs are failing.
Will try a re-trigger of the CI.

**Review by malfet — APPROVED** [review]
If ROCM ci is green, then looks good to me.

**Pull request closed without merging**
