### PR TITLE
Expose linalg.solve_ex

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #80217
* #80074
* __->__ #80073
* #79838
* #79742

This prepares for making `linalg.inv_ex` just a call into this function

### CODE REVIEW

**Comment by IvanYashchuk** [comment]
This is "expert"-only interface. Why do we need this function when we already have `lu_factor_ex`?

**Comment by Lezcano** [comment]
There's two reasons. The main one is that we are already exposing `inv_ex` (I don't know why...) so to make that one composite in terms of `solve` we need to expose this one :(
The second one for why `solve` is superior to `lu_factor`  + `lu_solve` is because it's derivative is **much** faster than the composition of the derivatives of `lu_factor` and `lu_solve`.

**Comment by IvanYashchuk** [comment]
> The main one is that we are already exposing `inv_ex` (I don't know why...)

There was a user's request for that https://github.com/pytorch/pytorch/issues/25095.

**Review by IvanYashchuk — APPROVED** [review]
I agree, this function should be helpful for those who'd like to avoid device synchronizations and avoid raising errors for batched computation.

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
