### PR TITLE
[cpu] vectorize atanh

### PR DESCRIPTION
**Pull request by khushi-411**
Fixes #ISSUE_NUMBER

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by khushi-411** [comment]
#### Performance Benchmarks
#### Before vectorization
```
[---------------- torch.atanh(x) Benchmark ---------------]
                                          |  non-vectorized
1 threads: ------------------------------------------------
      dtype torch.float16 - n : 100       |         3.8    
      dtype torch.float16 - n : 200       |         5.6    
      dtype torch.float16 - n : 500       |        11.2    
      dtype torch.float16 - n : 1000      |        22.2    
      dtype torch.float16 - n : 10000     |       246.5    
      dtype torch.float32 - n : 100       |         3.6    
      dtype torch.float32 - n : 200       |         5.1    
      dtype torch.float32 - n : 500       |        10.1    
      dtype torch.float32 - n : 1000      |        19.5    
      dtype torch.float32 - n : 10000     |       208.1    
      dtype torch.float64 - n : 100       |         3.4    
      dtype torch.float64 - n : 200       |         4.9    
      dtype torch.float64 - n : 500       |         9.6    
      dtype torch.float64 - n : 1000      |        19.4    
      dtype torch.float64 - n : 10000     |       214.2    
      dtype torch.bfloat16 - n : 100      |         3.6    
      dtype torch.bfloat16 - n : 200      |         5.4    
      dtype torch.bfloat16 - n : 500      |        10.7    
      dtype torch.bfloat16 - n : 1000     |        21.1    
      dtype torch.bfloat16 - n : 10000    |       221.9    
      dtype torch.complex64 - n : 100     |         7.9    
      dtype torch.complex64 - n : 200     |        13.9    
      dtype torch.complex64 - n : 500     |        34.4    
      dtype torch.complex64 - n : 1000    |        70.9    
      dtype torch.complex64 - n : 10000   |       716.4    
      dtype torch.complex128 - n : 100    |        14.2    
      dtype torch.complex128 - n : 200    |        25.7    
      dtype torch.complex128 - n : 500    |        57.1    
      dtype torch.complex128 - n : 1000   |       118.5    
      dtype torch.complex128 - n : 10000  |      1143.8    

Times are in microseconds (us).
```

#### After vectorization
```
[-------------- torch.atanh(x) Benchmark -------------]
                                          |  vectorized
1 threads: --------------------------------------------
      dtype torch.float16 - n : 100       |       2.4  
      dtype torch.float16 - n : 200       |       2.8  
      dtype torch.float16 - n : 500       |       3.8  
      dtype torch.float16 - n : 1000      |       5.1  
      dtype torch.float16 - n : 10000     |      30.2  
      dtype torch.float32 - n : 100       |       2.4  
      dtype torch.float32 - n : 200       |       2.7  
      dtype torch.float32 - n : 500       |       3.4  
      dtype torch.float32 - n : 1000      |       4.8  
      dtype torch.float32 - n : 10000     |      27.6  
      dtype torch.float64 - n : 100       |       2.8  
      dtype torch.float64 - n : 200       |       3.5  
      dtype torch.float64 - n : 500       |       5.7  
      dtype torch.float64 - n : 1000      |       9.0  
      dtype torch.float64 - n : 10000     |      72.2  
      dtype torch.bfloat16 - n : 100      |       2.3  
      dtype torch.bfloat16 - n : 200      |       2.7  
      dtype torch.bfloat16 - n : 500      |       3.7  
      dtype torch.bfloat16 - n : 1000     |       5.0  
      dtype torch.bfloat16 - n : 10000    |      30.8  
      dtype torch.complex64 - n : 100     |       7.8  
      dtype torch.complex64 - n : 200     |      13.2  
      dtype torch.complex64 - n : 500     |      30.6  
      dtype torch.complex64 - n : 1000    |      58.8  
      dtype torch.complex64 - n : 10000   |     646.3  
      dtype torch.complex128 - n : 100    |      11.8  
      dtype torch.complex128 - n : 200    |      20.8  
      dtype torch.complex128 - n : 500    |      51.6  
      dtype torch.complex128 - n : 1000   |     103.6  
      dtype torch.complex128 - n : 10000  |    1035.6  

Times are in microseconds (us).
```
<details>
<summary>script</summary>

<p>

```python
import torch
import pickle
from torch.utils import benchmark
from itertools import product

device = 'cpu'
dtypes = (torch.float16, torch.float32, torch.float64, torch.bfloat16, torch.complex64, torch.complex128)
n = (100, 200, 500, 1000, 10000)

result = []

for dtype, num in product(dtypes, n):
    x = torch.rand(num, dtype=dtype, device='cpu')
    torch.atanh(x)
    stmt = 'torch.atanh(x)'
    measurement = benchmark.Timer(
        stmt=stmt,
        globals={'x': x},
        label=stmt + " Benchmark",
        sub_label=f"dtype {dtype} - n : {num}",
        description="non-vectorized",
    ).blocked_autorange()

    result.append(measurement)

fname_prefix = "benchmark_atanh_"

benchmark.Compare(result).print()
with open(fname_prefix+"non-vectorized", "wb") as f:
    pickle.dump(result, f)
```

</p>
</details>

**Comment by khushi-411** [comment]
Hi, @sanchitintel!
This PR is ready by my side. Could you please take a look whenever you are free? Thanks!

**Comment by khushi-411** [comment]
Hi, @sanchitintel! Gentle ping

**Comment by khushi-411** [comment]
Hi, gentle ping :)

**Comment by khushi-411** [comment]
Hi, gentle ping :)

**Review by jgong5 — APPROVED** [review]

**Comment by khushi-411** [comment]
Thanks for reviewing, @jgong5! ;-)

@pytorchbot merge

**Comment by sanchitintel** [comment]
Oops, sorry, I missed the notifications!

Thanks for the PR, @khushi-411!

**Comment by khushi-411** [comment]
Hi @sanchitintel! Thanks for looking into the PR ;-)
No worries about missing notifications; I understand you have a lot of them.

**Comment by khushi-411** [comment]
I think these failures are not related to the PR. Could you please force merge the PR? Thanks!

**Review by sanchitintel — APPROVED** [review]
Thanks again for your patience, @khushi-411!
I'll make it a point to go through my GitHub notifications regularly.

`REGISTER_DISPATCH` now only enables AVX2 dispatch.
For AVX512 dispatch of a kernel, please use the `ALSO_REGISTER_AVX512_DISPATCH` macro.
In one of your subsequent PRs, please consider using `ALSO_REGISTER_AVX512_DISPATCH(atanh_stub, &CPU_CAPABILITY::atanh_kernel);` in `aten/src/ATen/native/cpu/UnaryOpsKernel.cpp` to enable AVX512 dispatch, if this kernel would do well with AVX512.

Please consider doing something similar in your PRs for vectorizing `asinh` & `acosh` as well.
Thanks!

**Comment by sanchitintel** [comment]
Hi @ezyang, one of the files being modified in this PR is `c10/util/BFloat16-math.h`, for which the merge rules seem to require approval from a core-contributor. Can you please help approve this PR? Thanks!

**Comment by khushi-411** [comment]
Thanks for pointing it out, @sanchitintel! I've registered AVX512 dispatch using `ALSO_REGISTER_AVX512_DISPATCH` in my latest commit.

**Review by ezyang — APPROVED** [review]

**Comment by khushi-411** [comment]
Thanks, @ezyang!

**Pull request closed without merging**
