### PR TITLE
[Profiler] Use custom AppendOnlyList for op_events to reduce the number of atomic operations

### LINKED ISSUE #76762: [Profiler] Store correlation_id implicitly
### 🚀 The feature, motivation and pitch

The PyTorch profiler uses unique integers (correlation IDs) to correlate host kernel calls with remote (GPU) functions. Generating these IDs requires and [atomic add](https://github.com/pytorch/pytorch/blob/aca55948187ed01d18342d20aaaee45a54b09547/torch/csrc/autograd/profiler_kineto.cpp#L52) and takes up [8 bytes](https://github.com/pytorch/pytorch/blob/aca55948187ed01d18342d20aaaee45a54b09547/torch/csrc/profiler/collection.h#L41) in the profiling data stored for each op. The profiler uses atomics to guarantee uniqueness, however they provide stronger guarantees than we need. (And thus, higher runtime cost.) Because we store the records in a fixed location, we could instead subclass `AppendOnlyList` to reserve a block of correlation IDs and then use an element's position inside a block to implicitly determine the correlation ID. This would reduce the number of atomic instructions due to profiling from one per kernel to one per k kernels.

### Alternatives

N/A

### Additional context

(Starter task for my intern.)

cc @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git

### PR DESCRIPTION
**Pull request by davidchencsl**
Summary:
- Use atomic counter in Block storage constructor and offset within the block to calculate correlation_id.
- Implicitly deduce correlation id, no need to store it when profiling.

Test Plan:
Added test_profiler_correlation_id() in test_profiler.py to check the uniqueness of correlation id.

To run the test:
python test_profiler.py

Differential Revision: D36793803

Performance improvement:
Overhead for OnFunctionEnter
Original: 2.60%
Modified: 2.49%

Perf command used:
perf record -F 200 -g taskset -c 0-3 /home/davidchencsl/fbsource/fbcode/buck-out/gen/caffe2/caffe2/fb/high_perf_models/pytorch/benchmark_framework_overheads/cpp_benchmark --niter 200 --nrep 100000 --op empty --kinetoInputShapes

### CODE REVIEW

**Review by robieta — APPROVED** [review]
LGTM. (Reviewed internally)

**Comment by davidchencsl** [comment]
Performance improvement:
Overhead for OnFunctionEnter
Original: 2.60%
Modified: 2.49%

Perf command used:
perf record -F 200 -g taskset -c 0-3 /home/davidchencsl/fbsource/fbcode/buck-out/gen/caffe2/caffe2/fb/high_perf_models/pytorch/benchmark_framework_overheads/cpp_benchmark   --niter 200 --nrep 100000 --op empty --kinetoInputShapes

**Pull request closed without merging**
