### PR TITLE
Register xla_mark_sharding_dynamo_custom_op for xla-dynamo

### PR DESCRIPTION
**Pull request by wonjoo-wj**
[Just for testing]

### CODE REVIEW

**Review by wanchaol — CHANGES_REQUESTED** [review]
hmm I think this can be registered in the xla repo directly instead of putting this in functional collective

**Comment by miladm** [comment]
Question: can we clarify how the user experience can/will improve once this support is in. Would be great to build the solution such that it enables mark sharding support at the torch level directly (as opposed to torch_xla). wdyt?

cc @wonjoolee95 @yeounoh @ezyang

**Comment by wonjoolee95** [comment]
> hmm I think this can be registered in the xla repo directly instead of putting this in functional collective

You're absolutely right, I wanted to open this PR as a draft just so I can play around with some code and pin this in my upstream XLA PR.

**Comment by wonjoolee95** [comment]
Closing this PR as it is no longer needed.

**Pull request closed without merging**
