### PR TITLE
Clarify the clarification

### PR DESCRIPTION
**Pull request by mikekgfb**
Summary: Clarify the clarification

Differential Revision: D47941982

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### CODE REVIEW

**Review by mikaylagawarecki — APPROVED** [review]
sgtm! (to check my understanding is the reason why we say better inference performance because for training inputs sequences are regularly batched?)

**Comment by mikekgfb** [comment]
> sgtm! (to check my understanding is the reason why we say better inference performance because for training inputs sequences are regularly batched?)

It's because inference C++ implementation has batch_first hard coded and does not supposed batch in second position (aligns with nested tensor iirc), but sdpa supports both batch in first or second position.

Could be handled with the right transpose (and we had something like that as [#85576](https://github.com/pytorch/pytorch/pull/85576) but it never landed).

**Comment by mikaylagawarecki** [comment]
@mikekgfb Hm it's not immediate to me why this would affect only inference and not training

**Comment by mikekgfb** [comment]
> @mikekgfb Hm it's not immediate to me why this would affect only inference and not training

Thanks for keeping me honest :) 

So, the reason why training works without impact is that we already handle batched and non-batched by converting between the two -- the original MHA is `(not batch_first)` => https://www.internalfb.com/code/fbsource/[060b9facc2a27fc7559045ed75cb68d8cf68c7b3]/fbcode/caffe2/torch/nn/modules/activation.py?lines=1196

Of course MHA actually computed on `(batch_first)` (and that is also the default for `sdpa()`, so F.SDPA is the opposite of F.MHA in layout !!!!), and we convert back to `batch_first` here => https://www.internalfb.com/code/fbsource/[02219cbc7b1d8f57210a1f69c170a75d44452850]/fbcode/caffe2/torch/nn/functional.py?lines=5345%2C5347%2C5356

Lolz... we could totally do with some refactoring, because the number of permutations are just ... mind boggling.

We should just write a new function `F.new_MHA`(need better name) that aligns with SDPA, and call that after the suitable layout flips from `F_(old_)MHA`.  We'd want to align the arguments of `F.new_MHA` more closely with SDPA, and leave all the static_k etc. strictly compatibility in the `F.old_MHA`.

**Pull request closed without merging**
