### PR TITLE
[easy?] Move AsyncCompile to a different file

### PR DESCRIPTION
**Pull request by jamesjwu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #126999
* #126791
* __->__ #127235

By moving AsyncCompile to its own file, we can import codecache without running the side effects of AsyncCompile. This will be important for AOTAutogradCaching, where we want to share some implementation details with codecache.py without spawning new processes. 

To conservatively maintain the same behavior elsewhere, every time we import codecache, I've added an import to torch._inductor.async_compile (except in autograd_cache.py, where the explicit goal is to not do this)

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by aorenste — APPROVED** [review]

**Review by oulgen — APPROVED** [review]

**Comment by masnesral** [comment]
@jamesjwu, two questions:
1) Is the linter not going to want to remove these new imports (since they're not used)? If not for this PR, then in future PRs when someone makes a change and relints?
2) Related: if the import goes away, I'm worried we could add 3-4s compile time. As you noticed, there's this surprising behavior of starting a process pool when this file is imported. But I have to assume that was intentional to start the process pool as early as possible. I noticed in recent testing that I see a 3-4s overhead if I omit that "warmup".

**Comment by jamesjwu** [comment]
@masnesral:
1. Running lintrunner on these files suggests that they're not being automatically removed. I think it's likely because it would only remove `from` style imports that are unused. In my PRs above this one, none of the async_compile imports are linted away. Or maybe it understands that importing async_compile has a side effect? 

2. We will still warm up the async compile pool as early as we did before: codecache has never been in the transitive deps of aot_autograd.py, so it was never imported when you import aot_autograd. The goal of moving this file is that I can import codecache in aot_autograd_cache, then import aot_autograd_cache in aot_autograd without spawning the process pool. But we should be importing and warming up the AsyncCompile pool at exactly the same time after this change. Let me know if there's a way for me to test that easily.

**Comment by masnesral** [comment]
@jamesjwu Thanks! I think you can just @torch.compile the simplest function and you'll immediately see a ~3s difference if the process pool warmup had changed. But I was more worried about it happening in the future (somewhat silently) if the linter removed your import.

**Review by masnesral — APPROVED** [review]

**Comment by jamesjwu** [comment]
Landed in https://github.com/pytorch/pytorch/pull/127691

**Pull request closed without merging**
