### PR TITLE
Hotpatch CXXFLAGS to be the same as CFLAGS if CXXFLAGS is not set.

### PR DESCRIPTION
**Pull request by xuhdev**
This fixes build regression caused by #23528 because we used to let CXXFLAGS equal CFLAGS.

cc @suo

### CODE REVIEW

**Comment by xuhdev** [comment]
@suo Could you reimport please? I made a mistake in the earlier version.

**Comment by xuhdev** [comment]
@ezyang This should fix regression caused by #23528 , but a more fundamental question is whether we should really do this (which is the behavior before this patch). Note that this PR does not include the reversion of #23528 , which means that, with all checks passed, it fixed the regression that #23528 has caused.

**Comment by ezyang** [comment]
Given that it is setuptools that has this (quite weird) behavior, I think we should continue to follow it. We're providing a "setup.py compatible interface" and that means we should respect setuptools interface quirks. This patch looks reasonable to me.

**Review by ezyang — APPROVED** [review]

**Comment by xuhdev** [comment]
I now also include reversion of 3cc7da3a7db35feee9e136d180975fda54827fc6 in this PR

**Comment by xuhdev** [comment]
I also noticed that v1.2.0 branch has #23528 merged in but does not have its reversion. Can we either revert it in v1.2.0 or have this PR merged in v1.2.0?

**Comment by xuhdev** [comment]
Any chance to get this merged :)

**Pull request closed without merging**
