### PR TITLE
[ROCm] [FakeTensorTest] Enable test_fallback_memory_prop

### PR DESCRIPTION
**Pull request by jaglinux**
Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### CODE REVIEW

**Comment by jaglinux** [comment]
cc @jithunnair-amd

**Comment by jaglinux** [comment]
Test passed on ROCm
2022-09-28T22:15:59.5043224Z   test_fallback_memory_prop (__main__.FakeTensorTest) ... ok (0.009s)
cc @jithunnair-amd

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
