### PR TITLE
[tlparse][AOTAutograd] Rename to aot_inference_graph in tlparse output

### PR DESCRIPTION
**Pull request by yf225**
Compiled Autograd uses this AOT inference path, but it shows up as "aot_forward_graph" in tlparse output, which causes it to not be easily differentiable from normal "aot_forward_graph"s that are also in the tlparse output. This PR renames it to "aot_inference_graph" which makes it easier to tell which tlparse graph block is from Compiled Autograd.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137803

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by Microve — APPROVED** [review]

**Review by bdhirsh — APPROVED** [review]

**Review by ezyang — CHANGES_REQUESTED** [review]
You must update tlparse so that it understands the new message type.

**Comment by yf225** [comment]
> Compiled Autograd uses this AOT inference path, but it shows up as "aot_forward_graph" in tlparse output, which causes it to not be easily differentiable from normal "aot_forward_graph"s that are also in the tlparse output. This PR renames it to "aot_inference_graph" which makes it easier to tell which tlparse graph block is from Compiled Autograd.

ah I see - opened a PR to add the `aot_inference_graph` message type: https://github.com/ezyang/tlparse/pull/75

**Comment by yf225** [comment]
@ezyang https://github.com/ezyang/tlparse/pull/75 is merged - would you like to review it again? thanks!

**Review by ezyang — APPROVED** [review]

**Comment by yf225** [comment]
Next step: update tlparse version in fbcode, before merging this PR.

**Comment by yf225** [comment]
> Next step: update tlparse version in fbcode, before merging this PR.

fbcode version is already landed by Ed in D64407461 (thanks Ed!). Proceeding to land this PR.

**Pull request closed without merging**
