### PR TITLE
add channels last support for AvgPool2d on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
replacement of: https://github.com/pytorch/pytorch/pull/48918

enable test case on AvgPool2d channels last for CPU

### CODE REVIEW

**Comment by mingfeima** [comment]
@VitalyFedyunin this one is a replacement of #48918.
I still can't reproduce the build failure on Android, I followed [building-pytorch-android-from-source](https://pytorch.org/mobile/android/#building-pytorch-android-from-source) and it passed.
Could you please provide more advice?

**Comment by Jianhui-Li** [comment]
@vitaly-fedyunin

**Comment by VitalyFedyunin** [comment]
Got it, thanks. I'm going to import it and run internal tests.

**Comment by Jianhui-Li** [comment]
@VitalyFedyunin  Does the android build failure pass now?

**Comment by mingfeima** [comment]
rebased!

**Review by VitalyFedyunin — APPROVED** [review]
Approves as a copy

**Comment by VitalyFedyunin** [comment]
UPD: There is no changes required for this PR, we are trying to fix Android builds/tests now to land this.

**Comment by VitalyFedyunin** [comment]
Android tests are passing now, but you need to rebase to the master

**Comment by mingfeima** [comment]
@VitalyFedyunin thanks for your effort! The PR has been rebased, please check.

**Pull request closed without merging**
