### PR TITLE
fix Type Hinting Annotations

### LINKED ISSUE #100804: Wrong type for `get_lr` inside lr_scheduler.pyi
### 🐛 Describe the bug

`lr_scheduler.pyi` describes `def get_lr(self) -> float: ...` but the implementation returns `List[float]`

https://github.com/pytorch/pytorch/blob/31f311a816c026bbfca622d6121d6a7fab44260d/torch/optim/lr_scheduler.pyi#L19
https://github.com/pytorch/pytorch/blob/31f311a816c026bbfca622d6121d6a7fab44260d/torch/optim/lr_scheduler.py#L394

### Versions

Current master branch

cc @vincentqb @jbschlosser @albanD @janeyx99 @ezyang @malfet @rgommers @xuzhao9 @gramster

### PR DESCRIPTION
**Pull request by wbittles**
Fixes #100804

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
Good point

**Comment by wbittles** [comment]
@janeyx99 I have been given the CLA permissions I needed,  so if you'd be kind enough to issue the 
@pytorchbot rebase again all should go through.

**Comment by janeyx99** [comment]
Oh hm...the CLA is still failing :/

Have you made sure the email you signed the CLA with is the one in your .gitconfig locally?

**Comment by janeyx99** [comment]
Actually, looking more into it, it looks like both implementations of get_last_lr and get_lr return lists of floats. Where do you see get_last_lr returning a float?

**Comment by wbittles** [comment]
> Actually, looking more into it, it looks like both implementations of get_last_lr and get_lr return lists of floats. Where do you see get_last_lr returning a float?

If you look at the commit changes , you can see where I flipped them , see below for the original code 
`  def get_last_lr(self) -> List[float]: ...
    def get_lr(self) -> float: ...`

**Comment by jewelltaylor** [comment]
@janeyx99 any reason this wasn't merged in? Still facing this issue in torch 2.3.0. Happy to put up a unless there is a particular reason this wasn't merged

**Pull request closed without merging**
