### PR TITLE
[CI] handle more dynamo benchmark models that are not expected to be deterministic

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96324

Follow-up to #96245. alexnet, Background_Matting, vision_maskrcnn, and vgg16 all have the same problem; but on float32 they were also failing on the previous day so I missed this. Once the amp jobs became available I could see that these have the same issue (on both float32 and amp).

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Comment by desertfire** [comment]
Locally I am seeing a few more failures, like Background_Matting and vision_maskrcnn. I think we should catch such exception and reset  use_deterministic_algorithms to False if eager run fails. @davidberard98 do you want to give that a try?

**Comment by davidberard98** [comment]
Sure, but first I am bisecting hf_Longformer and some other models that are failing for other reasons

**Review by desertfire — APPROVED** [review]

**Pull request closed without merging**
