### PR TITLE
Move ONNX integration tests from onnx-fb-universe to PyTorch repo

### PR DESCRIPTION
**Pull request by bddppq**
- Tests are put under test/onnx and utility scripts are put under scripts/onnx
- Only operator tests are using expect files

### CODE REVIEW

**Comment by bddppq** [comment]
CI failures unrelated

**Comment by ezyang** [comment]
Cool. I see a bunch of binary pb files; is there a reason they aren't using text format?

**Comment by bddppq** [comment]
@ezyang Those are onnx test cases that @houseroad scraped from existing PyTorch test cases. I think it makes senses to exclude them for now, removed in newest commit.

**Review by ezyang — APPROVED** [review]

**Comment by apaszke** [comment]
Can we switch to torchvision for mode defs? It makes no sense to copy them over, because eg that’s why densenet is currently broken. The model no longer matches the state dict, and while torchvision can patch it up, this code can’t. It’s not used in any CI tests so the failure is not that apparent

**Review by apaszke — APPROVED** [review]

**Pull request merged**
