### PR TITLE
[RELAND] Remove deprecated fbgemm operators

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #104569
* #118526
* #72303
* __->__ #112153

These operators are not used and have been deprecated since #72690
(Feb 2022).

BC-breaking message:

`TorchScript` models that were exported with the deprecated
`torch.jit.quantized` API will no longer be loadable, as the required
internal operators have been removed.
Please re-export your models using the newer `torch.ao.quantization` API
instead.

### CODE REVIEW

**Comment by albanD** [comment]
Why is this a reland?

**Comment by kit1980** [comment]
I'm looking at this now.
For the info, the previously reverted PR is https://github.com/pytorch/pytorch/pull/104535

**Comment by kit1980** [comment]
In the failing test I see specifically `Unknown builtin op: aten::fbgemm_pack_quantized_matrix.`

It looks like the test tries to load a jitted saved model.
I'm not sure we're ready to remove this.

Maybe we can try to land the other removals and leave out `fbgemm_pack_quantized_matrix` for now?

**Comment by jerryzh168** [comment]
@peterbell10 sorry I just saw this, do you want to land this PR?

**Comment by peterbell10** [comment]
@jerryzh168 yes I'd still like this to be merged if possible. I've split this into two PRs, #118406 removing just the python API that's been deprecated for 4 years, and this PR removing the operators used by TorchScript models. Hopefully at least the python API cleanup can go through.

**Comment by jerryzh168** [comment]
@peterbell10 please write a bc-breaking note if it's bc breaking, see "Backward Incompatible Changes" sction in https://github.com/pytorch/pytorch/releases/tag/v2.1.0 for examples

**Review by jerryzh168 — APPROVED** [review]

**Comment by clee2000** [comment]
There are a few internal usages left, @jerryzh168 is currently talking to internal teams to get them removed

**Comment by lezcano** [comment]
ping @jerryzh168

**Pull request closed without merging**
