### PR TITLE
[fp8 rowwise] Clarify dtypes

### PR DESCRIPTION
**Pull request by lw**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134114
* #134113
* #134112
* #134111
* #134110

Disambiguate some of the dtypes (e.g., for the scales), move the "constant" ones out of the function, and use safe casting functions.

### CODE REVIEW

**Review by drisspg — APPROVED** [review]
Awesome clean up!

**Comment by lw** [comment]
The failure seems unrelated: test/profiler/test_cpp_thread.py::CppThreadTest::test_profile_memory is hitting segmentation faults.

**Pull request closed without merging**
