### PR TITLE
Switch calling convention back to real tensors

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99320
* #99317
* #99314

Months ago, in order to get dynamic shapes working through to Dynamo backends, we changed the calling convention to pass fake tensors rather than real tensors as example inputs to backends. The motivation at the time was, well, backends shouldn't really be peeking at the real tensors when they are doing compilation, and so it would make more sense to hide the real tensors from backends. But there were a bunch of problems:

* This interacted poorly with our accuracy minifier design: accuracy minifier needs access to the real inputs in order to run the model and figure out what happens!
* The TensorRT backend required real inputs and we never figured out how to fix it.
* In practice, all the backends needed to detect if they were passed real tensors, and fakeify them anyway (certainly AOTAutograd does this)
* Parameters and inputs are treated non-uniformly: parameters had to be passed as real tensors, because CUDA graphs requires knowing what the actual tensors are

Furthermore, there were some more problems discovered after the fact:

* Backends may want to optimize on aspects of tensors which you cannot tell without having real tensors; e.g., alignment of the data pointer

So, this PR decides that changing the calling convention was a bad idea, and switches back to passing real tensors. There is a problem though: AOTAutograd will perform fakeification, which means that in practice backends are still going to end up with fake tensors in the end anyway. I want to change this, but this will require some work with bdhirsh's upcoming AOTAutograd export refactor.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]

**Comment by wconstab** [comment]
I'm just wondering, for the ultimate goal of having a distcompiler that can work with larger-than-initializable models can we still support a deferred init scheme and  pass fake tensors through dynamo? I think we could arguably diverge 'train_step_compiler' from 'aot_autograd' backends here since they may have different preferences on fake and have already diverged implementations

**Comment by ezyang** [comment]
Deferred init fake should be treated as its own thing and designed separately

**Comment by DanilBaibak** [comment]
@ezyang sorry, I have to revert your PR. It leads to internal failures. Here you can find more details - [D45103307](https://www.internalfb.com/diff/D45103307).

**Comment by ezyang** [comment]
attn oncall, fbcode side changes are at https://www.internalfb.com/diff/D45103307

**Pull request closed without merging**
