### PR TITLE
Make auto_functionalized HOP fallback in inductor

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #117084

It looks like the inductor fallback previously worked with HOPs but no longer
does, so I fixed that:
- all HOPs are exposed under torch.ops.higher_order, so I changed how
  inductor looks them up
- the inductor fallback assumed that an operator's signature was (*args,
  **kwargs). This is true for all the OpOverloads but not HOPs. I
  rewrote the code to not rely on this.

Test Plan:
- existing tests
- new test for auto_functionalized HOP.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by williamwen42 — APPROVED** [review]

**Comment by Microve** [comment]
Thanks for the fix! I wonder whether we could add some logs, making it easier to pinpoint the root cause the issue when they occur again

**Comment by oulgen** [comment]
I applied this locally for my AOTI repro and the fallback does not work in my AOTI repro.
```
generate_c_shim_fallback_kernel
```
function fails handle tuple outputs. This is likely just AOTI missing some functionality but would be good to add a test either way.

**Comment by zou3519** [comment]
Merging this for now; this PR offers Inductor support but not AOTInductor support (we need inductor support to unblock one of the internal use cases). Will add the AOTInductor support via a lowering later.

**Pull request closed without merging**
