### PR TITLE
improve multi-core performance of qavg_pool2d

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74999
* #68328
* #72575
* #71903
* #69667
* #69601
* #69600
* #69599
* #69598
* __->__ #69517

Differential Revision: [D33353158](https://our.internmc.facebook.com/intern/diff/D33353158)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33353158).

**Comment by mingfeima** [comment]
TODO: add benchmarking and update notes.

**Comment by dzdang** [comment]
Please provide a descriptive high level overview of the changes&improvements made in this PR. Are the improvements quantifiable? If so, please describe

**Comment by mingfeima** [comment]
> Please provide a descriptive high level overview of the changes&improvements made in this PR. Are the improvements quantifiable? If so, please describe

sorry for the late response, i got occupied some other task. Will add detailed info & benchmark! Internally we check quantized model performance based on two types of configs: 1-core and 4-core. If you prefer other configs, let me know!

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33353158).

**Comment by mingfeima** [comment]
### Target
This stack is targeting at improving native ATen quantized OP performance on CPU. Most of the original kernels have been optimized on single core, however part of the kernels might not be properly paralleled and this stack is addressing such issues. Some PRs from this stack also provide performance improvement on single core as well, will illustrate clearly on each PR notice.

### Performance benchmarking note
Will use [pytorch/benchmarks](https://github.com/pytorch/pytorch/tree/master/benchmarks/operator_benchmark) as much as possible as long as the OP is covered.



### Updates of this PR
improves `qavg_pool` multi-core performance on channels last memory format.

* **contiguous memory format**: parallels on {N, C}, scalar logic (can't be vectorized). This part is untouched.
* **channels last memory format**: originally parallels on {N} and go sequentially on {H, W}, vectorized on {C}. This problem here is that in case of single batch inference (when N=1), it will go sequentially even on a multi-core CPU. This PR parallels on {N, H, W} and vectorized on {C}. e.g. given an input shape of {1, 64, 112, 112}, the original kernel run sequentially and the new kernel will run parallelly.


### Benchmarking

* **short tag**: `python -m pt.qpool_test`
* **long tag**: `python  -m pt.qpool_test --tag_filter long`

CPU: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, dual sockets, 20 cores per sockets.

#### 1.a) single core run on short tag
this PR has no effect on cases from short tag since they are all `contigTrue` (which means nchw memory format).

name | before | after | speedup
-- | -- | -- | --
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N2_contigTrue_dtypetorch.qint32 | 5.211 | 5.244 | 99.37%
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N2_contigTrue_dtypetorch.qint8 | 5.411 | 5.425 | 99.74%
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N2_contigTrue_dtypetorch.quint8 | 5.452 | 5.451 | 100.02%



#### 1.b) single socket run on short tag
this PR has no effect on cases from short tag since they are all `contigTrue` (which means nchw memory format).

name | before | after | speedup
-- | -- | -- | --
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N2_contigTrue_dtypetorch.qint32 | 8.011 | 8.125 | 98.60%
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N2_contigTrue_dtypetorch.qint8 | 9.201 | 9.308 | 98.85%
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N2_contigTrue_dtypetorch.quint8 | 9.067 | 9.085 | 99.80%


#### 2.a) single core run on long tag
this PR has no effect on single core run

name | before | after | speedup
-- | -- | -- | --
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N1_contigFalse_dtypetorch.quint8 | 5.135 | 5.313 | 96.65%
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N1_contigTrue_dtypetorch.quint8 | 5.082 | 5.216 | 97.43%
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N4_contigFalse_dtypetorch.quint8 | 5.377 | 5.433 | 98.97%
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N4_contigTrue_dtypetorch.quint8 | 5.358 | 5.435 | 98.58%
QAvgPool2dBenchmark_C3_H64_W64_k(3,3)_s(2,2)_p(1,1)_N1_contigFalse_dtypetorch.quint8 | 67.424 | 65.115 | 103.55%
QAvgPool2dBenchmark_C3_H64_W64_k(3,3)_s(2,2)_p(1,1)_N1_contigTrue_dtypetorch.quint8 | 42.838 | 42.213 | 101.48%
QAvgPool2dBenchmark_C3_H64_W64_k(3,3)_s(2,2)_p(1,1)_N4_contigFalse_dtypetorch.quint8 | 253.508 | 259.675 | 97.63%
QAvgPool2dBenchmark_C3_H64_W64_k(3,3)_s(2,2)_p(1,1)_N4_contigTrue_dtypetorch.quint8 | 164.71 | 153.151 | 107.55%
QAvgPool2dBenchmark_C64_H224_W224_k(2,2)_s(2,2)_p(0,0)_N1_contigFalse_dtypetorch.quint8 | 418.02 | 427.158 | 97.86%
QAvgPool2dBenchmark_C64_H224_W224_k(2,2)_s(2,2)_p(0,0)_N1_contigTrue_dtypetorch.quint8 | 7251.185 | 7106.455 | 102.04%
QAvgPool2dBenchmark_C64_H224_W224_k(2,2)_s(2,2)_p(0,0)_N4_contigFalse_dtypetorch.quint8 | 1641.79 | 1656.94 | 99.09%
QAvgPool2dBenchmark_C64_H224_W224_k(2,2)_s(2,2)_p(0,0)_N4_contigTrue_dtypetorch.quint8 | 28919.7 | 29563.08 | 97.82%
QAvgPool2dBenchmark_C256_H56_W56_k(2,2)_s(2,2)_p(0,0)_N1_contigFalse_dtypetorch.quint8 | 77.646 | 74.011 | 104.91%
QAvgPool2dBenchmark_C256_H56_W56_k(2,2)_s(2,2)_p(0,0)_N1_contigTrue_dtypetorch.quint8 | 1867.54 | 1842.921 | 101.34%
QAvgPool2dBenchmark_C256_H56_W56_k(2,2)_s(2,2)_p(0,0)_N4_contigFalse_dtypetorch.quint8 | 269.917 | 257.793 | 104.70%
QAvgPool2dBenchmark_C256_H56_W56_k(2,2)_s(2,2)_p(0,0)_N4_contigTrue_dtypetorch.quint8 | 7417.865 | 7307.09 | 101.52%


#### 2.b) single socket run on long tag
this PR improves `contigFalse` (which means nhwc memory format) on multi-core, for `contigTrue` (nchw), there is no effect.

name | before | after | speedup
-- | -- | -- | --
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N1_contigFalse_dtypetorch.quint8 | 7.145 | 7.305 | 97.81%
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N1_contigTrue_dtypetorch.quint8 | 7.126 | 7.073 | 100.75%
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N4_contigFalse_dtypetorch.quint8 | 9.395 | 9.412 | 99.82%
QAvgPool2dBenchmark_C1_H3_W3_k(3,3)_s(1,1)_p(0,0)_N4_contigTrue_dtypetorch.quint8 | 9.388 | 9.209 | 101.94%
QAvgPool2dBenchmark_C3_H64_W64_k(3,3)_s(2,2)_p(1,1)_N1_contigFalse_dtypetorch.quint8 | 76.842 | 16.206 | 474.16%
QAvgPool2dBenchmark_C3_H64_W64_k(3,3)_s(2,2)_p(1,1)_N1_contigTrue_dtypetorch.quint8 | 22.72 | 22.729 | 99.96%
QAvgPool2dBenchmark_C3_H64_W64_k(3,3)_s(2,2)_p(1,1)_N4_contigFalse_dtypetorch.quint8 | 94.085 | 30.304 | 310.47%
QAvgPool2dBenchmark_C3_H64_W64_k(3,3)_s(2,2)_p(1,1)_N4_contigTrue_dtypetorch.quint8 | 22.98 | 22.827 | 100.67%
QAvgPool2dBenchmark_C64_H224_W224_k(2,2)_s(2,2)_p(0,0)_N1_contigFalse_dtypetorch.quint8 | 497.455 | 40.885 | 1216.72%
QAvgPool2dBenchmark_C64_H224_W224_k(2,2)_s(2,2)_p(0,0)_N1_contigTrue_dtypetorch.quint8 | 534.773 | 530.911 | 100.73%
QAvgPool2dBenchmark_C64_H224_W224_k(2,2)_s(2,2)_p(0,0)_N4_contigFalse_dtypetorch.quint8 | 662.958 | 128.573 | 515.63%
QAvgPool2dBenchmark_C64_H224_W224_k(2,2)_s(2,2)_p(0,0)_N4_contigTrue_dtypetorch.quint8 | 1847.895 | 1848.87 | 99.95%
QAvgPool2dBenchmark_C256_H56_W56_k(2,2)_s(2,2)_p(0,0)_N1_contigFalse_dtypetorch.quint8 | 79.952 | 17.132 | 466.68%
QAvgPool2dBenchmark_C256_H56_W56_k(2,2)_s(2,2)_p(0,0)_N1_contigTrue_dtypetorch.quint8 | 121.136 | 123.529 | 98.06%
QAvgPool2dBenchmark_C256_H56_W56_k(2,2)_s(2,2)_p(0,0)_N4_contigFalse_dtypetorch.quint8 | 114.528 | 30.696 | 373.10%
QAvgPool2dBenchmark_C256_H56_W56_k(2,2)_s(2,2)_p(0,0)_N4_contigTrue_dtypetorch.quint8 | 479.885 | 479.756 | 100.03%

**Comment by mingfeima** [comment]
@dzdang @jerryzh168 performance data and description updated, could you please help review~ i will update other PRs from this stack as well later on.

**Comment by mingfeima** [comment]
This stack has been recently rebased.

**Comment by dzdang** [comment]
Looks good! Sorry for the delay. I'm goign through these rn

**Review by dzdang — APPROVED** [review]

**Comment by mingfeima** [comment]
This stack has been rebased recently!

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33353158).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33353158).

**Pull request closed without merging**
