### PR TITLE
OSS: Capture triton kernel in ET

### PR DESCRIPTION
**Pull request by shengfukevin**
This DIFF is to capture triton kernels in execution trace

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by briancoutinho — APPROVED** [review]
lgtm :)

**Comment by shengfukevin** [comment]
"/easycla"

**Comment by jeanschmidt** [comment]
@pytorch merge

**Review by aaronenyeshi — CHANGES_REQUESTED** [review]
please wait for Brian's PR to land first. We should make sure tests are in a good state, so we can properly catch an ET regressions when this lands. https://github.com/pytorch/pytorch/pull/124856

**Review by aaronenyeshi — APPROVED** [review]

**Pull request closed without merging**
