### PR TITLE
Avoid reference cycle in inner closure

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #127711

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Comment by ezyang** [comment]
@Skylion007 it would be really neat if we could have a lint for this sort of thing lol

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
@ezyang If you are worried about reference cycle and memory leaks, you should investigate the B019 cached lru methods.

**Review by izaitsevfb — APPROVED** [review]

**Pull request closed without merging**
