### PR TITLE
Fix 'get_real_value' on placeholder nodes

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #127698
* #127696
* #127695

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by BowenBao** [comment]
cc @jansel ptal

**Review by jansel — APPROVED** [review]

**Comment by BowenBao** [comment]
@pytorchbot merge

Executorch internal test failure is fixed with https://github.com/pytorch/pytorch/pull/128358

**Pull request closed without merging**
