### PR TITLE
Improve Windows Compatibility(for lib/nccl)

### PR DESCRIPTION
**Pull request by peterjc123**
Win64 support for lib/nccl

### CODE REVIEW

**Comment by fmassa** [comment]
The changes for `nccl` should maybe be sent to https://github.com/NVIDIA/nccl ?

**Comment by peterjc123** [comment]
Okay, so it should be closed here?

**Comment by fmassa** [comment]
@soumith what do you think, is it better to send this PR to the official nccl repo?

**Comment by soumith** [comment]
yes, send it to the official nccl repo here: https://github.com/nvidia/nccl

**Comment by peterjc123** [comment]
Closed.

**Comment by ngimel** [comment]
Official nccl repo is end-of-life, nvidia encourages everyone to move to nccl 2.0 (which, unfortunately, is not built for windows).

**Pull request closed without merging**
