### PR TITLE
Remove cpp/tensorexpr benchmarks

### PR DESCRIPTION
**Pull request by bertmaher**
Summary: These refer to a deprecated backend of torchscript which is no longer built in releases, and require llvm to be built.

Test Plan:
```
python setup.py develop
```

Fixes #ISSUE_NUMBER

cc @albanD

### CODE REVIEW

**Comment by bertmaher** [comment]
@albanD This PR is getting a size-check failure because it's big (3200 lines), but it's pretty trivial, removing some benchmarks which won't compile anymore (since we removed LLVM as a dependence).  Can it be bypassed?

**Review by hl475 — APPROVED** [review]

**Review by chenyang78 — APPROVED** [review]

**Review by eellison — APPROVED** [review]

**Review by mikekgfb — APPROVED** [review]

**Pull request closed without merging**
