### PR TITLE
[rename] quantize_linear -> quantize_per_tensor

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #26576 [rename] _dequantize_linear -> _dequantize_per_tensor
* #26575 [rename] quantize_linear_per_channel -> quantize_per_channel
* **#26574 [rename] quantize_linear -> quantize_per_tensor**

Summary:
Since we also have `quantized::linear`, `quantize_linear` sounds
confusing, so we plan to rename it before the branch cut

Test Plan:
ci

Reviewers:
pt1quant

Subscribers:

Tasks:

Tags:

Differential Revision: [D17514876](https://our.internmc.facebook.com/intern/diff/D17514876)

### CODE REVIEW

**Review by supriyar — APPROVED** [review]
LGTM. Do any docs need to be updated?

**Comment by jerryzh168** [comment]
> LGTM. Do any docs need to be updated?

I did a grep over the whole repo, should be OK

**Comment by jerryzh168** [comment]
> > LGTM. Do any docs need to be updated?
> 
> I did a grep over the whole repo, should be OK

oh, we do need to update the doc for Quantized Tensor, will do it later

**Comment by supriyar** [comment]
@jerryzh168 this change may have broken CI https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test2/842//console
`FAIL: test_equal (__main__.TestQuantizedOps)`

**Pull request closed without merging**
