### PR TITLE
Solves the linking error related to lazy_init for MSVC

### PR DESCRIPTION
**Pull request by peterjc123**
Finally, I tested it using the local build. So it should be okay after this PR. 
@soumith Please review it.

### CODE REVIEW

**Comment by paddyhoran** [comment]
Tested locally and this PR fixes #5372.

As always, thanks for your effort @peterjc123

**Comment by gchanan** [comment]
This doesn't look ideal to me; why do we have to guard call sites on windows but not on linux?

**Comment by gchanan** [comment]
As another data point -- on linux with python I can call torch.cuda._lazy_init() even if I've compiled with NO_CUDA=1.  Given that torch::cuda::lazy_init() is just calling that (if the type is CUDA, which it will never be since cuda isn't enabled) -- the guarded function should be safe to call unconditionally as well.

**Comment by gchanan** [comment]
I think the issue is that lazy_init.cpp is only compiled if cuda is enabled; this makes some sense since that's the usual pattern with things in torch/csrc/cuda/;  To avoid confusion we should just move that to torch/csrc/utils/cuda_lazy_init and unconditionally compile it.

**Comment by peterjc123** [comment]
@gchanan So maybe I should revert this one and make a new PR?

**Comment by gchanan** [comment]
@peterjc123 I think we should get in https://github.com/pytorch/pytorch/pull/5364 first, which will preclude a revert.  Can you make a new PR that moves the files around as above and we'll merge it after https://github.com/pytorch/pytorch/pull/5364?

**Comment by peterjc123** [comment]
@gchanan Sure.

**Comment by peterjc123** [comment]
The new PR is #5375.

**Pull request merged**
