### PR TITLE
Enable EXE001 flake8 check.

### PR DESCRIPTION
**Pull request by xuhdev**
According to #27285 , seems we do not intend to use shebang as an indication of Python version, thus
we enable EXE001 flake8 check.
For violations, we either remove shebang from non-executable Python scripts or grant them executable permission.

### CODE REVIEW

**Review by pietern — COMMENTED** [review]
Thanks, @xuhdev!

Before merging, I want to get an ack from @ezyang as well.

The idea here is: hashbang means you have a main function and mode 755, no hashbang mode 644.

**Comment by ezyang** [comment]
Sorry, there is some hidden back story here, which makes it a little tricky to do this.

In Facebook internally, we have a lint check that essentially complains if you don't have Python 3 compatibility imports. There are a few ways to suppress it, but the one that is suggested by the linter is adding a shebang line to the top that explicitly says python3, even if the intent is never to actually run the file as an executable.

Andres helpfully gave some more tips about the linter though:

* This linter will not complain if it finds a .python3 or .python2 file up the parent dirs. This also affects how flake8 treats your files.
* This linter will not complain if it finds any future import in a file (so you could do from __future__ import print and it'll stop complaining).
* This linter will not complain if it finds a versioned python shebang in a file (e.g. #!/usr/bin/env python2.7, #!/usr/bin/env python2, #!/usr/bin/env python3, basically anything with that matches ^#!.*python[23])
* This linter will not complain if the file has @lint-ignore-evert PYTHON3COMPATIMPORTS.

I landed a PR that puts `.python2` in our top level directory, which should shut this up. But that's the reason why people keep adding these shebangs.

**Review by ezyang — APPROVED** [review]

**Comment by pietern** [comment]
Sweet! Thanks for the context, @ezyang! For future reference, the PR is #27214.

**Comment by xuhdev** [comment]
Thanks for the explanation!

**Pull request closed without merging**
