### PR TITLE
[Reland] fix missing-prototypes warnings in torch_cpu (Part 4)

### PR DESCRIPTION
**Pull request by cyyever**
This PR relands the changes introduced in PR #100849. The old PR turnd  nnc_aten_embedding  into a static function, however, it is actually used in torch/csrc/jit/tensorexpr/operators/misc.cpp.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @EikanWang @izaitsevfb @albanD

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!
Do you know why this didn't fail in our CI? Do we just never build with tensorexpr in CI?

**Comment by cyyever** [comment]
@albanD The missing function may be dynamically loaded via dlopen so that the building process didn't report failures before.

**Comment by izaitsevfb** [comment]
> > May be we can add the failed test inside MeTa to the OSS version.
> 
> @izaitsevfb is that something you can look into on your end?

@albanD, correct me if I'm wrong, but the linker issue seems to be stemming from the way we build things like android and xplat at Meta. It could be theoretically possible to find all PT symbols that use and pin them somehow in OSS, but that's quite a project. For example, it seems that now we're having issue with another symbol, `nnc_prepacked_linear_clamp_run`, see [D46093855](https://www.internalfb.com/diff/D46093855).

We'll try to brainstorm the solution with @osalpekar. 

@cyyever, if this PR gets reverted again, please ping me next time before merge, I'll import it manually to see if it breaks anything.

**Comment by cyyever** [comment]
@izaitsevfb It seems that the changes in external_functions.cpp are the only reason this PR got reverted again. Then a simple solution is to discard them in that file.

**Comment by izaitsevfb** [comment]
> @izaitsevfb It seems that the changes in external_functions.cpp are the only reason this PR got reverted again. Then a simple solution is to discard them in that file.

@cyyever, trying that now, will keep you posted.

**Comment by izaitsevfb** [comment]
@cyyever, the signals looks good after making `nnc_prepacked_linear_clamp_run` non-static. I believe it's safe to reland this PR. v5 seems to be fine as well. Thank you for your patience.

@osalpekar, please see [D46093855](https://www.internalfb.com/diff/D46093855).

**Comment by cyyever** [comment]
@izaitsevfb I have create a new PR #102228 for reland.

**Pull request closed without merging**
