### PR TITLE
[easy] Fix small typo in register_state_dict_pre_hook doc

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Fixed https://github.com/pytorch/pytorch/pull/112674#issuecomment-1912849827

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #118571

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
oofers

**Review by albanD — APPROVED** [review]
Ahhh that explains that. I was quite confused about this the other day :D

**Comment by henrylhtsang** [comment]
thanks for the quick fix!

**Pull request closed without merging**
