### PR TITLE
[opinfo prims] equal

### PR DESCRIPTION
**Pull request by khushi-411**
Follows: #100223

### CODE REVIEW

**Comment by khushi-411** [comment]
Hi, @justinchuby, @kshitij12345, @lezcano, @ngimel !
Could you please review the PR? Thanks for considering my request.

**Review by ezyang — APPROVED** [review]

**Comment by khushi-411** [comment]
Hi, @ezyang! Thanks for reviewing!

Rebasing the PR.

@pytorchbot rebase

**Pull request closed without merging**
