### PR TITLE
When using a third-party device to  test DeviceMesh,the error check for 'test_raises_invalid_device_type' can only prints 'GPU'

### PR DESCRIPTION
**Pull request by SCh-zx**
Fixes #ISSUE_NUMBER

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by kwen2501 — APPROVED** [review]

**Comment by kwen2501** [comment]
Thanks. Can you please sign the CLA so that we can land it?

**Comment by SCh-zx** [comment]
> 谢谢。您能否签署 CLA，以便我们能够落地？



> Thanks. Can you please sign the CLA so that we can land it?

done

**Comment by SCh-zx** [comment]
> Thanks. Can you please sign the CLA so that we can land it?

done

**Pull request closed without merging**
