### PR TITLE
Support only GLog >=0.6.0

### LINKED ISSUE #58054: PyTorch master failed to build with glog 0.5.0.
## Bug

Log:

```
root@164a9000a4ab:/tmp/scratch/pytorch/build# cmake --build . -- -j1
[1/153] : && /usr/bin/g++-8 -fdebug-prefix-map='/tmp/scratch'='/usr/local/src' -g -march=haswell -mtune=generic -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -O3 -DNDEBUG -DNDEBUG -rdynamic c10/cuda/test/CMakeFiles/c10_cuda_CUDATest.dir/impl/CUDATest.cpp.o -o bin/c10_cuda_CUDATest  -Wl,-rpath,/tmp/scratch/pytorch/build/lib:/usr/local/lib:/usr/local/cuda/lib64:  lib/libc10_cuda.so  lib/libgtest_main.a  lib/libc10.so  /usr/local/lib/libglog.so.0.5.0  /usr/local/lib/libgflags.so.2.2.2  -lpthread  /usr/local/cuda/lib64/libcudart.so  lib/libgtest.a  -pthread && :
FAILED: bin/c10_cuda_CUDATest 
: && /usr/bin/g++-8 -fdebug-prefix-map='/tmp/scratch'='/usr/local/src' -g -march=haswell -mtune=generic -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -O3 -DNDEBUG -DNDEBUG -rdynamic c10/cuda/test/CMakeFiles/c10_cuda_CUDATest.dir/impl/CUDATest.cpp.o -o bin/c10_cuda_CUDATest  -Wl,-rpath,/tmp/scratch/pytorch/build/lib:/usr/local/lib:/usr/local/cuda/lib64:  lib/libc10_cuda.so  lib/libgtest_main.a  lib/libc10.so  /usr/local/lib/libglog.so.0.5.0  /usr/local/lib/libgflags.so.2.2.2  -lpthread  /usr/local/cuda/lib64/libcudart.so  lib/libgtest.a  -pthread && :
lib/libc10.so: undefined reference to `google::glog_internal_namespace_::IsGoogleLoggingInitialized()'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

glog 0.5 is released a few days ago.
IIRC pytorch redefined that func to expose it.
Wondering that's related.

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Ubuntu 18.04 / CentOS 7
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake+ninja+gcc
 - Python version: 3.6
 - CUDA/cuDNN version: 11.3

### PR DESCRIPTION
**Pull request by Arfrever**
Fixes #58054

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
Hmm, can you please add a check to CMakeLists to see if the symbol is present and depending on results on the check call one method or another?

**Comment by xkszltl** [comment]
> Hmm, can you please add a check to CMakeLists to see if the symbol is present and depending on results on the check call one method or another?

Would be better if there's compile time checks, like some ifdef or SFINAE tricks.

Only supporting 0.6 is problematic as almost no distro ships it. It's too new and incompatible with existing code.

**Comment by Arfrever** [comment]
> can you please add a check to CMakeLists to see if the symbol is present and depending on results on the check call one method or another?

If you think that it is needed, please add this check yourself.
I think that it is unnecessary to support older versions of GLog, and I am unable to work on it.

> Would be better if there's compile time checks, like some ifdef or SFINAE tricks.

GLog headers define no macros specifying GLog version.

> If you want the bot to never mark this PR stale again, add the no-stale label.

Please add `no-stale` label.

(I do not use PyTorch at all. I am maintainer of GLog package in my distribution. We obviously have GLog 0.6.0 there and I want to drop older versions.)

**Comment by xkszltl** [comment]
(Disclaimer: I'm not a maintainer of pytorch)

> I think that it is unnecessary to support older versions of GLog

FYI almost no major distro have glog > 0.4, and unlikely to have in the near future due to its breaking change.

**Comment by Arfrever** [comment]
> almost no major distro have glog > 0.4

It does not seem to be true:
[Arch Linux](https://archlinux.org/packages/community/x86_64/google-glog/): 0.6.0
Debian: [Bookworm](https://packages.debian.org/source/bookworm/google-glog): 0.6.0; [Sid](https://packages.debian.org/source/sid/libs/google-glog): 0.6.0
[Gentoo](https://packages.gentoo.org/packages/dev-cpp/glog): 0.6.0
[openSUSE](https://software.opensuse.org/package/google-glog): 0.5.0
[Ubuntu](https://packages.ubuntu.com/search?keywords=google-glog): jammy (22.04LTS): 0.5.0; kinetic (22.10) and lunar: 0.6.0
[FreeBSD](https://freebsd.pkgs.org/13/freebsd-amd64/glog-0.6.0.pkg.html): 0.6.0

**Comment by xkszltl** [comment]
> [Arch Linux](https://archlinux.org/packages/community/x86_64/google-glog/): 0.6.0
> [Gentoo](https://packages.gentoo.org/packages/dev-cpp/glog): 0.6.0

Not surprising for Arch, Gentoo keeps 0.4/0.5/0.6.

> Debian: [Bookworm](https://packages.debian.org/source/bookworm/google-glog): 0.6.0; [Sid](https://packages.debian.org/source/sid/libs/google-glog): 0.6.0

None of those are Debian stable releases

> [openSUSE](https://software.opensuse.org/package/google-glog): 0.5.0

That's the rolling release.
Stable one is still on 0.3.5

> [Ubuntu](https://packages.ubuntu.com/search?keywords=google-glog): jammy (22.04LTS): 0.5.0; kinetic (22.10) and lunar: 0.6.0

That's actually a counterexample...

non-LTS doesn't really matter as it's disappearing in 9 month.
For LTS it's called `libgoogle-glog-dev_0.5.0+really0.4.0-2_amd64.deb`.
- https://ubuntu.pkgs.org/22.04/ubuntu-universe-amd64/libgoogle-glog-dev_0.5.0+really0.4.0-2_amd64.deb.html

> 2021-10-13 - Laszlo Boszormenyi (GCS) <gcs@debian.org>
> google-glog (0.5.0+really0.4.0-1) unstable; urgency=medium
> * Revert to 0.4.0 due to upstream ABI break without SONAME change.
>
> 2021-10-13 - Laszlo Boszormenyi (GCS) <gcs@debian.org>
> google-glog (0.5.0-1) unstable; urgency=medium
> * New upstream release.
> * Rework packaging.
> * Update watch file.
> * Update debhelper level to 13 .
> * Update Standards-Version to 4.6.0 .

**Comment by Arfrever** [comment]
Anyway I would not expect that new version of PyTorch will be added to current "stable" release of these distributions which have such distinction.

**Comment by xkszltl** [comment]
Sounds like someone forgot to remove the stale flag?
CC @malfet

**Pull request closed without merging**
