### PR TITLE
add ZeroTensor specialization to div.Tensor

### LINKED ISSUE #70027: [rocm] Memory Exception on virtual address
### 🐛 Describe the bug

```
01:57:20   test_fn_fwgrad_bwgrad_gradient_cuda_complex128 (__main__.TestGradientsCUDA) ... Memory exception on virtual address 0x7f60f5d77000, node id 2 : Page not present
01:57:21 Address does not belong to a known buffer
01:57:21 Memory access fault by GPU node-2 (Agent handle: 0x5603f3f007f0) on address 0x7f60f5d77000. Reason: Page not present or supervisor privilege.
01:57:21 Traceback (most recent call last):
01:57:21   File "test/run_test.py", line 1068, in <module>
01:57:21     main()
01:57:21   File "test/run_test.py", line 1046, in main
01:57:21     raise RuntimeError(err_message)
01:57:21 RuntimeError: test_ops failed! Received signal: SIGIOT
```

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test2/14900/console

### Versions

ROCm CI

cc @ezyang @gchanan @zou3519 @bdhirsh @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @mruberry

### PR DESCRIPTION
**Pull request by jeffdaily**
Completes a task from #69687.

### CODE REVIEW

**Comment by jeffdaily** [comment]
@anjali411 I see you've had to skip some AD tests.  This PR seemed to fix some unit tests for rocm; waiting to take it out of draft mode until CI has confirmed.  Perhaps adding this `div_zerotensor` will fix some of the other unit tests?

**Comment by jeffdaily** [comment]
This solution is incomplete.  Fixes some unit tests but breaks others.

**Comment by anjali411** [comment]
Hmm I am not sure why adding a fallthrough would fix this problem unless the fallback is faulty. My guess is that the issue is being caused because the cuda device on efficient zero tensors is currently not set properly. So, I enabled the rocm tests in my PR https://github.com/pytorch/pytorch/pull/71611 and they don't seem to fail anymore...

**Review by anjali411 — APPROVED** [review]

**Comment by anjali411** [comment]
@jeffdaily The failures on this PR should be fixed by https://github.com/pytorch/pytorch/pull/71901 so this LGTM

**Comment by jeffdaily** [comment]
@anjali411  #71611 was reverted?  Now sure how/if all these PRs are related.  I'll defer to you to take it from here.  I don't want this PR to fix one thing but break another and then end up getting reverted after landing.  Perhaps all these PRs need to be joined together so the CI status remains clean.

**Comment by anjali411** [comment]
@jeffdaily I'll merge this PR after #71611. will probably need a rebase before the merge

**Pull request closed without merging**
