### PR TITLE
[GHA] broaden upload test stats criteria

### PR DESCRIPTION
**Pull request by janeyx99**
Addresses bullet 2 of https://github.com/pytorch/pytorch/issues/78175

### CODE REVIEW

**Comment by suo** [comment]
We should probably exclude skipped workflows, so that we don't run uselessly.

Not sure about cancelled workflows—why is it important to include them? A cancelled workflow almost certainly means something is "wrong" with the commit (e.g. someone pushed a new version to their PR and so the workflow got pre-empted), so I'm not sure why it's valuable to include in the test stats.

**Comment by janeyx99** [comment]
Okay with the skipping skipped (I'll just add back failed or succeeded or cancelled)

For cancelled: I see value having all stats of completed jobs, for tracking and future debugging reasons + I'm not convinced that the only time a workflow is cancelled is when it's pre-empted. Wouldn't flaky GHA infra cause cancellations potentially as well? Regardless, I noticed this when looking at flaky test stats discrepancies between my new query and the old, and I think having more data on flaky instances is better than not.

**Review by suo — APPROVED** [review]
sgtm

**Pull request closed without merging**
