### PR TITLE
[WIP] Updated SGD sparse tests for momentum case

### PR DESCRIPTION
**Pull request by izdeby**

### CODE REVIEW

**Comment by vincentqb** [comment]
Can you provide the code snippet that you are trying to run that makes you believe that SGD with momentum and sparse gradients is not supported?

**Comment by vincentqb** [comment]
Adding a test [here](https://github.com/pytorch/pytorch/blob/master/test/test_optim.py#L287) like the following?

```python
    def test_sgd_sparse(self):
        self._test_rosenbrock_sparse(
            lambda params: optim.SGD(params, lr=5e-3)
        )
        self._test_rosenbrock_sparse(
            lambda params: optim.SGD(params, lr=5e-3, momentum=.8)
        )
        self._test_rosenbrock_sparse(
            lambda params: optim.SGD(params, lr=0.005),
            [lambda opt: StepLR(opt, gamma=0.99999, step_size=300)]
        )
```

**Comment by vincentqb** [comment]
> Adding a test [here](https://github.com/pytorch/pytorch/blob/master/test/test_optim.py#L287) like the following?
> 
> ```python
>     def test_sgd_sparse(self):
>         self._test_rosenbrock_sparse(
>             lambda params: optim.SGD(params, lr=5e-3)
>         )
>         self._test_rosenbrock_sparse(
>             lambda params: optim.SGD(params, lr=5e-3, momentum=.8)
>         )
>         self._test_rosenbrock_sparse(
>             lambda params: optim.SGD(params, lr=0.005),
>             [lambda opt: StepLR(opt, gamma=0.99999, step_size=300)]
>         )
> ```

```
======================================================================
ERROR: test_sgd_sparse (__main__.TestOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_optim.py", line 291, in test_sgd_sparse
    self._test_rosenbrock_sparse(
  File "test/test_optim.py", line 84, in _test_rosenbrock_sparse
    optimizer.step(functools.partial(eval, params, True, w))
  File ".../anaconda3/envs/pytorch-from-source/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File ".../anaconda3/envs/pytorch-from-source/lib/python3.8/site-packages/torch/optim/sgd.py", line 106, in step
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: set_indices_and_values_unsafe is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)

----------------------------------------------------------------------
Ran 102 tests in 21.904s

FAILED (errors=1)
```

**Comment by vincentqb** [comment]
@albanD  -- SGD with momentum has a `.detach()` [here](https://github.com/pytorch/pytorch/blob/master/torch/optim/sgd.py#L103) within a `torch.no_grad` decorator [here](https://github.com/pytorch/pytorch/blob/master/torch/optim/sgd.py#L75). The error [above](https://github.com/pytorch/pytorch/pull/43662#issuecomment-682138860) is being raised if we add a test. After a quick chat with @fmassa, SGD with/without momentum should indeed be supported with sparse gradient. I know the mechanic changed when `.data` is used, can you clarify what happens for `.detach()`?

**Comment by albanD** [comment]
The `.detach()` is indeed not needed here since you're inside the no_grad() block.
Does removing it fixes the issue?

**Comment by izdeby** [comment]
It kinda does. we wont have a crash but an assert fail: 
`AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1.3e-06 and atol=1e-05, found 1 element(s) (out of 2) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 3.25 (2313578.0 vs. 2313574.75), which occurred at index 0.`

But that might be a different issue?

**Comment by albanD** [comment]
This does look unrelated indeed (and looks like a precision issue...)

**Comment by vincentqb** [comment]
> `AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1.3e-06 and atol=1e-05, found 1 element(s) (out of 2) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 3.25 (2313578.0 vs. 2313574.75), which occurred at index 0.`
>
> But that might be a different issue?

The one you describe does indeed look like a different issue, one of precision. Increasing rtol to 1.5e-06 would make it meet that criteria but not the atol=1.3e-06. One way of at least adding a test path for momentum is to add the test we discussed with a higher tolerance.

I reproduce with the test as described above. If I also add the following test,
```python
        self._test_rosenbrock_sparse(                                                                                                                                                             
            lambda params: optim.SGD(params, lr=5e-3, momentum=.8), sparse_only=True                                                                                                              
        ) 
```
I get a different error for this:
```
======================================================================
FAIL: test_sgd_sparse (__main__.TestOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_optim.py", line 291, in test_sgd_sparse
    self._test_rosenbrock_sparse(
  File "test/test_optim.py", line 94, in _test_rosenbrock_sparse
    self.assertLessEqual(params.data.dist(solution), initial_dist)
AssertionError: tensor(nan) not less than or equal to tensor(0.7071)

----------------------------------------------------------------------
```

**Pull request closed without merging**
