### PR TITLE
Functions: conv2d, sum_pool2d for LongTensor

### PR DESCRIPTION
**Pull request by ifedan**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#20370 conv2d implmentation for LongTensor**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D15192353/)

- enable generation of conv2d for LongTensor

Differential Revision: [D15192353](https://our.internmc.facebook.com/intern/diff/D15192353/)

### CODE REVIEW

**Comment by ifedan** [comment]
Comment on CR for https://github.com/pytorch/pytorch/pull/20105:
@gchanan:
testing? It also seems like you don't support a larger number of cases, e.g. depthwise, transposed, dilated convolutions.Maybe similar on the AvgPool / SumPool too, but I'm not sure.
@gchanan:
I don't think this makes sense to implement avg_pool2d for long because of the integer division (i.e. we don't support long on mean). Doesn't it make sense to implement SumPool instead?

**Comment by fmassa** [comment]
About @gchanan comment on AvgPool for Long: I think it should be implemented.  Bilinear / bicubic interpolation on integer types (uint8 for example) are widely used, and I don't think that AvgPool is that different from a bilinear downsampling.

**Comment by gchanan** [comment]
@fmassa do any of those have division on integer dtypes?  From what I can tell, those only have division in backwards, and we don't support backwards on integer dtypes anyway.

My naive interpretation would be AvgPool would actually return a non-integer dtype on integer dtype inputs, but we don't have (many) cross-dtype operations yet.

Thoughts?

**Comment by fmassa** [comment]
@gchanan interpolate multiplies the values of the to be interpolated by a floating point value, so this is the same situation as in here. Note that our interpolate kernels do not support integer types yet, but I think they should. Interpolation for integer types is implemented in opencv and Pillow through, and I can grab some examples once I'm back to my computer

**Comment by fmassa** [comment]
But you do bring valid points though. Im not sure if we should stick with what is currently done in image processing libs, or adopt a more numpy-correct alternative

**Pull request closed without merging**
