### PR TITLE
[WIP][JIT] Create a backward pass for Gelu Function in JIT

### PR DESCRIPTION
**Pull request by kevinstephano**
Making a backward pass for the Gelu function in the symbolic scripting.

What sort of testing is expected for such changes?  I didn't see obvious testing for the other functions in this file.

### CODE REVIEW

**Review by ailzhang — COMMENTED** [review]
IIRC one place to test is in https://github.com/pytorch/pytorch/blob/master/test/test_jit.py#L15742, where you can directly assert what node should appear in the forward/backward graph. And it's defined here https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_methods_invocations.py#L564

**Comment by eellison** [comment]
Hey @kevinstephano, do you mind picking back up this PR ? you just need to add tests [here](https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/jit_metaprogramming_utils.py#L88)

**Comment by kevinstephano** [comment]
@eellison I can pick up the PR and change it slightly to use the composite backward op we discussed in Slack.

**Comment by kevinstephano** [comment]
@ellision, I decided not to add `gelu_backward` because, when testing, I ran into double backward failures.  This meant I was going to need modify other files to get that behavior as there is no entry for `gelu_backward` in `derivatives.yml`.  So, I stuck with enumerating the function in `symbolic_scripts.py`.

I added an explicit test in `test_jit_cuda_fuser.py`.  I did not add anything to `test_jit.py` as I did not see where specific operators are being tested.  Gelu is getting called indirectly via `test_jit.py` through `test_nn.py` that executes a TransformerEncoder layer with Gelu and its backward function which is how I discovered the double backward problem.  Is there an explicit place to test new operators that I am not seeing, off hand?

**Comment by eellison** [comment]
Makes sense, re: double backward. Yes, the best place to add to test an operator is in `OpInfo` like the PR here: https://github.com/pytorch/pytorch/pull/57652/ . That will test backward/double backward etc, and has a way to assert that we are autodiffing in the JIT.

**Comment by kevinstephano** [comment]
Thanks for the example, Elias!  I will add a test in the `OpInfo` manner.

**Review by eellison — APPROVED** [review]
LGTM ! Thanks !

**Comment by eellison** [comment]
Oop looks like there is one failure around dtype, `test_fn_fail_gradgrad_nn_functional_gelu_cpu_float64`. Related issue: https://github.com/pytorch/pytorch/issues/57577.

**Comment by kevinstephano** [comment]
Hmm, I thought I saw a failure with `supports_gradgrad=True`, therefore, I was wondering if I should really include it.  I'll go back and check.

**Comment by kevinstephano** [comment]
I am seeing this error when I turn on `supports_gradgrad=True`. Trying to track it down.

```
======================================================================                                                                                                                    
ERROR: test_variant_consistency_jit_nn_functional_gelu_cuda_float32 (__main__.TestCommonCUDA)
----------------------------------------------------------------------                                                                                                                    
Traceback (most recent call last):
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_utils.py", line 1030, in wrapper                                                                                     
    method(*args, **kwargs)
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_utils.py", line 1030, in wrapper
    method(*args, **kwargs)
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test                                                                      
    raise rte
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test                                                                      
    result = test_fn(self, *args)
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper                                                                           
    return test(*args, **kwargs)
  File "test/test_ops.py", line 424, in test_variant_consistency_jit
    check_alias_annotation(name, (sample.input,) + sample.args, sample.kwargs,
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/jit_metaprogramming_utils.py", line 486, in check_alias_annotation
    torch._C._jit_check_alias_annotation(CU.the_method.graph, tuple(tensors), aten_name)                                                                                                  
RuntimeError: aliasOp != torch::jit::getOperatorAliasMap().end()INTERNAL ASSERT FAILED at "../torch/csrc/jit/passes/utils/check_alias_annotation.cpp":157, please report a bug to PyTorch.
```

**Comment by kevinstephano** [comment]
There seems to be something not quite right in the `OpInfo` wiring when you have an operation not found in the `torch` namespace.  When I have the name defined as `nn.functional.gelu`, it triggers an alias check because the fusion name comparison doesn't find a node with name `nn.functional.gelu`.  It finds `gelu` instead and triggers a lookup in a JIT alias map in `jit/passes/normalize_ops.h`.  It doesn't find the alias there and asserts.  I thought perhaps the proper way was to define the `kwarg` `op` in `OpInfo`.  However, I then get this error so I am not sure what to do.

I get this error when I use `op=torch.nn.functional.gelu`, instead:

```
======================================================================
ERROR: test_variant_consistency_jit_gelu_cuda_float32 (__main__.TestCommonCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_utils.py", line 1030, in wrapper
    method(*args, **kwargs)
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_utils.py", line 1030, in wrapper
    method(*args, **kwargs)
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
    raise rte
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "test/test_ops.py", line 401, in test_variant_consistency_jit
    check_against_reference(self,
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_jit.py", line 84, in check_against_reference
    outputs_test = self.runAndSaveRNG(func, nograd_inputs, kwargs)
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_jit.py", line 154, in runAndSaveRNG
    results = func(*inputs, **kwargs)
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/jit_metaprogramming_utils.py", line 307, in script_fn
    fn, tensors = gen_script_fn_and_args(method_name, func_type, *args, **kwargs)
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/jit_metaprogramming_utils.py", line 298, in gen_script_fn_and_args
    CU = torch.jit.CompilationUnit(script)
RuntimeError: 
object has no attribute gelu:
  File "<string>", line 3

def the_method(i0):
    return torch.gelu(i0)
           ~~~~~~~~~~ <--- HERE
```

```
   OpInfo('gelu',                                                                    
           op=torch.nn.functional.gelu,                                                                    
           supports_autograd=True,                                                     
           assert_autodiffed=True,                                                 
           sample_inputs_func=sample_inputs_gelu,                                          
           dtypesIfCUDA=floating_types_and(torch.half, torch.bfloat16),                             
           supports_gradgrad=True,                                                      
           supports_out=False,                                                                     
           autodiff_fusible_nodes=["aten::gelu"]),
```

**Comment by eellison** [comment]
@kevinstephano huh, weird. I'll try to debug as well.

**Comment by Krovatkin** [comment]
@kevinstephano we should probably land https://github.com/pytorch/pytorch/pull/57828 first, it should remove most issues you are hitting with `OpInfo` testing. @eellison thanks for cc'ing me here.

**Comment by eellison** [comment]
@Krovatkin some of the issues are unrelated there id rather land this.

**Comment by Krovatkin** [comment]
@eellison right, I didn't realize you already included the inlining fix from https://github.com/pytorch/pytorch/pull/57828 . @kevinstephano  We should be good to land then!

**Comment by kevinstephano** [comment]
I still see this error with the diff given above:

```
======================================================================                                                                                                                                                                                                                                                                                                               
ERROR: test_variant_consistency_jit_nn_functional_gelu_cuda_float32 (__main__.TestCommonCUDA)                                                                                                                                                                                                                                                                                        
----------------------------------------------------------------------                                                                                                                                                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                   
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_utils.py", line 1030, in wrapper                                                                                                                                                                                                                                                                                
    method(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                                          
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_utils.py", line 1030, in wrapper                                                                                                                                                                                                                                                                                
    method(*args, **kwargs)                   
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test                                                                      
    raise rte                                                                                                                                                                             
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test                                                                      
    result = test_fn(self, *args)              
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper                                                                           
    return test(*args, **kwargs)                                                            
  File "test/test_ops.py", line 424, in test_variant_consistency_jit                                                                                                                      
    check_alias_annotation(name, (sample.input,) + sample.args, sample.kwargs,
  File "/my_workspace/my_pytorch_fork/torch/testing/_internal/jit_metaprogramming_utils.py", line 487, in check_alias_annotation
    torch._C._jit_check_alias_annotation(CU.the_method.graph, tuple(tensors), aten_name)                                                                                                  
RuntimeError: aliasOp != torch::jit::getOperatorAliasMap().end()INTERNAL ASSERT FAILED at "../torch/csrc/jit/passes/utils/check_alias_annotation.cpp":157, please report a bug to PyTorch.
```
I am pushing the Diff to this PR.

**Comment by Krovatkin** [comment]
@kevinstephano 

I think you might also need to set “aten_name” 
https://github.com/pytorch/pytorch/pull/57828/files#diff-18a0c3e7cd07089b34760028c387d39de1aa393172f1d5f123692106b3a3d144R4788

like so

```
    OpInfo('nn.functional.gelu',
           aten_name="gelu"
```

**Comment by Krovatkin** [comment]
@kevinstephano 

I think you might also need to set “aten_name” 
https://github.com/pytorch/pytorch/pull/57828/files#diff-18a0c3e7cd07089b34760028c387d39de1aa393172f1d5f123692106b3a3d144R4788

like so

```
    OpInfo('nn.functional.gelu',
           aten_name="gelu"
```

**Comment by csarofeen** [comment]
Merged as part of https://github.com/pytorch/pytorch/pull/57753

**Pull request closed without merging**
