### PR TITLE
[distributed][sharded_tensor] Move local_shards check from ShardedTensorBase to ShardedTensor

### PR DESCRIPTION
**Pull request by IvanKobzarev**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #100197

Differential Revision: [D45369211](https://our.internmc.facebook.com/intern/diff/D45369211)

### CODE REVIEW

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45369211).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45369211).

**Review by fduwjj — APPROVED** [review]
Unblock. Overall, this idea of this change looks good but it looks like that we are copying same logic to ShardedTensor, it would be great if we can refactor it a little bit so that we don't have duplicate code and consolidate common logics.

Please also make sure internal tests also all pass. Thanks!

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45369211).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45369211).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45369211).

**Pull request closed without merging**
