### PR TITLE
Build ahead-of-time C++ extensions with ninja on windows

### LINKED ISSUE #33045: Build ahead-of-time C++ extensions with ninja on windows
## 🚀 Feature

Right now, C++ extensions support building with ninja on unix-based systems. This task is to enable that support for windows. See #32495 for the PR that added support for building with ninja on unix-based systems.

cc @yf225 @peterjc123

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Do we have to update the tests or will the tests just "work"?

**Comment by peterjc123** [comment]
Sure, as you can see the test errors in the previous commits, it is already under testing.

**Review by zou3519 — APPROVED** [review]
nice!

**Comment by yf225** [comment]
It seems that this PR causes the `test_cuda_extension (__main__.TestCppExtensionAOT)` test to be flaky:
```
======================================================================
FAIL: test_cuda_extension (__main__.TestCppExtensionAOT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cpp_extensions_aot.py", line 67, in test_cuda_extension
    self.assertEqual(z, torch.ones_like(z))
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 862, in assertEqual
    assertTensorsEqual(x, y)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 832, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(1.) not less than or equal to 1e-05 : 

----------------------------------------------------------------------
```
Instances of the failure:
https://app.circleci.com/jobs/github/pytorch/pytorch/4469204
https://app.circleci.com/jobs/github/pytorch/pytorch/4470030
https://app.circleci.com/jobs/github/pytorch/pytorch/4470035
https://app.circleci.com/jobs/github/pytorch/pytorch/4479604

@peterjc123 Curious do you know why this happens?

**Pull request closed without merging**
