### PR TITLE
Change MKLDNN_THREADING definition from OMP:COMP to OMP

### PR DESCRIPTION
**Pull request by CeadeS**
MKLDNN determines by itself if intel openmp is present or not. Define COMP in advance prevents it from using intel openmp. This results in the behavior described in https://github.com/pytorch/pytorch/issues/29722

### CODE REVIEW

**Review by ilia-cher — APPROVED** [review]

**Comment by ilia-cher** [comment]
I assume you checked that in case of GCC we'd use libgomp

**Comment by ilia-cher** [comment]
for future ref., from https://github.com/intel/mkl-dnn/blob/7d2fd500bc78936d1d648ca713b901012f470dbc/cmake/options.cmake 

    The default option is OMP, which gives a preference to OMP:INTEL, but if
    neither Intel MKL is installed nor Intel MKL-ML is available then fallback
    to OMP:COMP.

**Review by ilia-cher — CHANGES_REQUESTED** [review]
actually, can we get some better understanding first, why the original option didn't work?
OMP:COMP is supposed to use whatever library is supplied by a compiler

**Comment by CeadeS** [comment]
@ilia-cher thank you for your review. 
I guess the right solution needs more than changing this option. It was just a small change that helped with my problem. 
My observation was that the gnu openmp is much slower then the intel one. Therefore, linking it if the intel version is present should be suppressed entierly. PyTorch seems to default to gnu openmp if it is present.

**Comment by cpuhrsch** [comment]
@CeadeS - this is a core change and we'll need to write a detailed study before we do this.

I assume the main question to answer here is
a) What MKL libraries do we currently link against and in what order of preference?
b) Which MKL library is better when and why?
c) Which parts of pytorch are consumers of the MKL library and do they each link to the same and if not, why not?

**Comment by ilia-cher** [comment]
from the docs, as I understand the version of omp library would depend on which compiler you use

**Comment by sai-prasanna** [comment]
This also fixes related issue where forking process with pytorch models creates deadlocks on inference. Intel OMP doesn't cause deadlocks after forks.

**Pull request closed without merging**
