### PR TITLE
Use SEQUENTIAL posix_fadvise on mmapped files

### PR DESCRIPTION
**Pull request by zeux**
In theory this tells the system that we will access the file sequentially which allows prefetching future blocks. In practice it doubles the read-ahead size on Linux (which effectively doubles the read sizes).

Without this, CUDA uploads of files that aren't already in FS cache, using mmapped files (safetensors) as source, run at ~1 GB/s (from an SSD that has ~7 GB/s read speed...).

With this, they run at ~1.5 GB/s which is still bad but better than before!

It is possible to increase the read performance further by touching the pages from multiple threads; in fact, when the tensors loaded from the file are used by the CPU, we get fairly good load performance (~5 GB/s), which appears to be because multiple threads page fault and trigger more concurrent reads which improves SSD read throughput... however, this is not the case for CUDA uploads, and it is difficult to make that change in a generic way because it's unclear what the usage pattern of the input file is going to be.

All of the numbers above are taken on Samsung 990 Pro SSD, on Linux kernel 6.5 with FS cache cleared between every attempt to load a file. The file is loaded via `safetensors.safe_open` which uses UntypedTensor.from_file to load the file into memory, which in turn uses MapAllocator.cpp.

I felt safe doing this change unconditionally but please let me know if you'd like to see a separate allocator flag for this, propagated through to UntypedTensor. Note that the fadvise API is not available on macOS.

### CODE REVIEW

**Comment by cpuhrsch** [comment]
@albanD @mikaylagawarecki - Not sure which label we use for mmap / torch.load related issues.

**Comment by albanD** [comment]
"module: serialization" is a good label.
Taking a look at this!

**Review by mikaylagawarecki — DISMISSED** [review]
Thanks a lot for making this change! Will merge this PR when CI runs green

> It is possible to increase the read performance further by touching the pages from multiple threads; in fact, when the tensors loaded from the file are used by the CPU, we get fairly good load performance (~5 GB/s), which appears to be because multiple threads page fault and trigger more concurrent reads which improves SSD read throughput...

This is an interesting point, out of curiosity, what is the context where you are using multiple threads, is this in the context of serving?

**Comment by zeux** [comment]
> what is the context where you are using multiple threads, is this in the context of serving?

Ah, no, I'm referring to the internal OMP threads that PyTorch CPU backend uses. Essentially if the model loaded from disk uses PyTorch CPU operations on the tensors (which of course is unusual when working with large models) that come from `safetensors` mmapped file then the loading speed is better because PyTorch internally uses multiple threads to read the data, and that automatically increases the read parallelism as far as I can tell. That doesn't happen for CUDA uploads of course.

**Comment by DanilBaibak** [comment]
Hi @zeux! Sorry, I have to revert your PR. It leads to internal failures. To be a little more precise, it broke the android build. @mikaylagawarecki could you please help with it? Here you can find more details [D53122733](https://www.internalfb.com/diff/D53122733).

**Comment by mikaylagawarecki** [comment]
Ah perhaps we need #ifndef __ANDROID__ as well, will take a look!

**Comment by zeux** [comment]
Oops yeah this should probably be `#if !defined(__APPLE__) && !defined(__ANDROID__)`. Android NDK has posix_fadvise but only from a fairly late ABI level:

> fcntl.h:int posix_fadvise(int __fd, off_t __offset, off_t __length, int __advice) __RENAME_IF_FILE_OFFSET64(posix_fadvise64) __INTRODUCED_IN(21);

... and it's unreasonable to expect PyTorch to require this.

I can change the PR to add that - would you like me to do this? Not sure what the process is.

**Comment by zeux** [comment]
Ok I ended up pushing the change to #ifndef - please let me know if I can do anything else here and sorry for the breakage!

**Comment by mikaylagawarecki** [comment]
Thanks for fixing this @zeux, the breakage was not your fault at all as there was no signal in CI :)

I imported the PR and the android builds no longer fail (e.g. [example](https://www.internalfb.com/sandcastle/workflow/4314448443022891060))

Will remerge

**Review by mikaylagawarecki — APPROVED** [review]

**Pull request closed without merging**
