### PR TITLE
Flip default value for mypy disallow_untyped_defs [final]

### PR DESCRIPTION
**Pull request by aorenste**
Not requiring all functions to have types allows a lot of 'Any' types to slip in - which poison types and make mypy unable to properly typecheck the code.  I want to flip the default so that new files are required to have fully typed defs and we can have a burndown list of files that fail to require full types.

The preceding stack of PRs (cut up simply to limit the number of file changes per PR "reasonable") adds `# mypy: allow-untyped-defs` to any file which didn't immediately pass mypy with the flag flipped.  Due to changing files and merge conflicts it will probably be necessary to have several passes through before landing this final PR which turns the option on.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #127836

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel @voznesenskym @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @LucasLLC @MeetVadakkanchery

### CODE REVIEW

**Review by oulgen — APPROVED** [review]

**Comment by Skylion007** [comment]
FYI, you can probably reduce a lot of the churn / pain of this by enabling the ruff ANN rules and it will even auto-deduce types for methods it can safely determine and apply the fixes.

**Comment by aorenste** [comment]
> FYI, you can probably reduce a lot of the churn / pain of this by enabling the ruff ANN rules and it will even auto-deduce types for methods it can safely determine and apply the fixes.

That sounds promising but I'm not sure I completely understand how it helps... Are you suggesting doing that *instead* of this? Or in addition? Also I worry that I don't want to cause people to have extra work just because they touched an existing poorly typed file - this stack turns on "# mypy: allow-untyped-defs" on any file that doesn't currently pass mypy untyped-defs to prevent extra work for bystanders.

**Comment by Skylion007** [comment]
In addition, it will type trivial methods (like __str__) one that CI is complaining about right now. Also will reduce user friction as it will properly type it instead of annoyed user just having it explicitly return Any to silence the typing noise.

**Comment by aorenste** [comment]
> In addition, it will type trivial methods (like **str**) one that CI is complaining about right now. Also will reduce user friction as it will properly type it instead of annoyed user just having it explicitly return Any to silence the typing noise.

I'm not sure what you mean - all I'm doing is flipping the default and marking any file that doesn't pass with "allow-untyped-defs" to retain the old behavior.  I'm not going to land this PR until I've marked every file that has any complaints with "allow-untyped-defs" first - so there should be no new CI complaints - and nobody should have to add "Any".

I understand that RUFF will auto-annotate the "easy" functions, but if I turn on the ruff lints then any time someone touches a file with a non-trivial untyped function won't they have to update it completely to pass CI?

**Comment by Skylion007** [comment]
> I understand that RUFF will auto-annotate the "easy" functions, but if I turn on the ruff lints then any time someone touches a file with a non-trivial untyped function won't they have to update it completely to pass CI?

Hmm, might be a way to configure it to only run the lints on files with the specific mypy comment you are adding, would need to chat with the ruff oflks

**Review by Skylion007 — APPROVED** [review]

**Pull request closed without merging**
