### PR TITLE
Create a sentinel file for each dynamo test skips

### PR DESCRIPTION
**Pull request by oulgen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #120451

cc @albanD

Differential Revision: [D54093191](https://our.internmc.facebook.com/intern/diff/D54093191)

### CODE REVIEW

**Comment by oulgen** [comment]
@oulgen has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54093191).

**Comment by oulgen** [comment]
@oulgen has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54093191).

**Comment by oulgen** [comment]
@oulgen has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54093191).

**Review by yanboliang — APPROVED** [review]
This looks good, but I think probably the downside is we lose the info about it's a py38 or py311 failure. PT developers should be aware of this when trying to reproduce an issue.

**Comment by oulgen** [comment]
@yanboliang we can always write that into the file, the contents of the files are not read

**Comment by oulgen** [comment]
@oulgen has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54093191).

**Comment by oulgen** [comment]
merged in parts

**Pull request closed without merging**
