### PR TITLE
Stopped TORCH_COMPILE_DEBUG from printing out a bunch of logs

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #122689
* #122581
* #121692
* __->__ #122688
* #122686

@ezyang suggests using TORCH_TRACE for dumping out all intermediate logs.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

Differential Revision: [](https://our.internmc.facebook.com/intern/diff/)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Need to update call sites in fbcode to set debug logging ig

**Comment by Chillee** [comment]
@ezyang Don't think there are that many cases.

**Review by mlazos — APPROVED** [review]

**Comment by Chillee** [comment]
@chillee has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/).

**Pull request closed without merging**
