### PR TITLE
[jit] Make ScriptModule.training an attribute instead of a parameter

### PR DESCRIPTION
**Pull request by driazati**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#19587 [jit] Make ScriptModule.training an attribute instead of a parameter**

Remove the hack we had previously where `training` was a buffer

Differential Revision: [D15502768](https://our.internmc.facebook.com/intern/diff/15502768/)

### CODE REVIEW

**Comment by eellison** [comment]
Add test?

**Comment by driazati** [comment]
This is just a refactor, it's already covered in `test_training_param` and others

**Review by eellison — COMMENTED** [review]
Maybe add serialization test? That's that this PR was a response to right

**Comment by suo** [comment]
hey what happened to this guy

**Review by suo — APPROVED** [review]

**Pull request closed without merging**
