### PR TITLE
[DataLoader] Add notebook with DataPipes API example

### PR DESCRIPTION
**Pull request by VitalyFedyunin**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #60840 [WIP] Example of DataPipes and DataFrames integration
* **#60680 [DataLoader] Add notebook with DataPipes API example**

Differential Revision: [D29461079](https://our.internmc.facebook.com/intern/diff/D29461079)

### CODE REVIEW

**Review by ejguan — APPROVED** [review]
Approve as we all agree with the API

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29461079).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29461079).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29461079).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29461079).

**Comment by driazati** [comment]
It seems like these notebooks should probably live in pytorch/tutorials or at least the docs folder instead. is there any reason they need to be in torch/?

**Comment by VitalyFedyunin** [comment]
It is very hard to keep them in sync with changes if they are hosted in a different repo. But as soon as we stabilize API, they are going to be moved into docs/tutorials.

**Pull request closed without merging**
