### PR TITLE
[composite compliance] frobenius norm

### PR DESCRIPTION
**Pull request by kshitij12345**
Ref: https://github.com/pytorch/pytorch/issues/69991

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
Why is `frobenius_norm_impl` necessary? Why not implement the logic directly in `frobenius_norm`? That would fix the current inconsistency of doing a cast to the real numbers in the non-out version, but not doing it in the out version. Now, I don't even know why this cast is necessary in the first place, but that's a story for another day.

**Comment by kshitij12345** [comment]
This is not about the cast but creating an `empty({0})` and resizing it down the line.

Previously, `out` variant used to perform the computation `frobenius_norm_impl` which returns a new Tensor and copy it into resized `out` (Resizing a `CCT` is not valid).

`frobenius_norm_impl` pulls the common logic of actually computing the norm and returns a Tensor which 
* functional variant:  returns after casting
* out variant: copies into out (after resizing).

**Comment by Lezcano** [comment]
I think the comment above still applies.
1. I think that all the logic should just be in `frobenius`, and then `frobenius_out` should call into it. Otherwise you may have a divergence between the out-of-place and the out function, as we do now.
2. I do not see why the cast to the real numbers or the point is necessary as the tensor by that point is already real, but then again, no need to fix this now.

**Comment by Lezcano** [comment]
Yup! This is the pattern we use in many other composite operations.

**Comment by kshitij12345** [comment]
@zou3519 @Lezcano PTAL :)

**Review by zou3519 — APPROVED** [review]
Thanks! I am not sure what the cast @Lezcano mentioned is doing, but it is orthogonal and we should merge this first and file a separate issue for it

**Review by lezcano — APPROVED** [review]
Cool!

**Comment by kshitij12345** [comment]
Requiring the cast was by-product of having implemented `frobenius_norm_impl`. With current approach that is not necessary. I don't think we need to file an issue for the same with the approach as suggested by @Lezcano. We also have asserts to verify that we don't change the expected layout and output dtype

**Pull request closed without merging**
