### PR TITLE
Add test_imports

### PR DESCRIPTION
**Pull request by malfet**
That validates that every PyTorch submodule can be imported

Prevents regressions like the one described in https://github.com/pytorch/pytorch/issues/77441 from happening in the future

### CODE REVIEW

**Comment by malfet** [comment]
@mruberry do you have a preference in the location of this test? (`test_testing.py` sounds like a best location to me, but I can move it to a new file if needed

**Comment by mruberry** [comment]
> @mruberry do you have a preference in the location of this test? (`test_testing.py` sounds like a best location to me, but I can move it to a new file if needed

test_testing.py or test_torch.py both seem fine -- it's nbd as long as it's easy to find for people who want to run it

**Review by seemethere — APPROVED** [review]
<details>
<summary> nice </summary>

nice

</details>

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
