### PR TITLE
split autograd tests into multiple test modules

### PR DESCRIPTION
**Pull request by dagitses**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #63206

Fixes #63205.

This change is almost exclusively moves of test/test_autograd.py into
new files. The only new code is the `__all__` block at the end of
test/autograd/test_device_type.py.

Test plan:
The test plan for this is manual. Test before the split and after the
split and ensure:

* all tests pass
* the number of tests by type is unchanged, e.g. same number of
  passing, skipped, expected, etc.

Also manually verify the diffs are all sensible with:
  `git diff --minimal HEAD~:test/test_autograd.py test/autograd/test_X.py`

Differential Revision: [D30302046](https://our.internmc.facebook.com/intern/diff/D30302046)

### CODE REVIEW

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30302046).

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30302046).

**Review by albanD — COMMENTED** [review]
I cannot comment on empty files :P but the `__init__.py` is not necessary anymore AFAIK
Also could you add a comment in the new files in test/autograd/* stating that these files should NOT be added to `run_test` and they run via the `test/test_autograd.py` file in CI.

Also can you confirm that running `test/test_autograd.py` before and after runs/skip/expect failure for the exact same number of tests?

**Comment by dagitses** [comment]
> I cannot comment on empty files :P but the `__init__.py` is not necessary anymore AFAIK
thanks!
> Also could you add a comment in the new files in test/autograd/* stating that these files should NOT be added to `run_test` and they run via the `test/test_autograd.py` file in CI.
done
> 
> Also can you confirm that running `test/test_autograd.py` before and after runs/skip/expect failure for the exact same number of tests?

I did (see PR description):

```
$ ghstack checkout https://github.com/pytorch/pytorch/pull/63206 && USE_CUDA=0 USE_DISTRIBUTED=0 python setup.py build && python test/test_autograd.py
...
----------------------------------------------------------------------
Ran 480 tests in 15.532s

OK (skipped=70, expected failures=1)

$ git switch master && USE_CUDA=0 USE_DISTRIBUTED=0 python setup.py build && python test/test_autograd.py
...
----------------------------------------------------------------------
Ran 480 tests in 34.797s

OK (skipped=70, expected failures=1)
```

**Review by albanD — APPROVED** [review]
LGTM

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30302046).

**Comment by albanD** [comment]
You might want to do `from .autograd.foo import bah` (notice the extra `.` at the beginning) to make sure the relative imports work properly.

**Comment by dagitses** [comment]
Deleting this. We can do this incrementally instead, which is lower risk.

**Pull request closed without merging**
