### PR TITLE
Fix Index symbolic after slice schema change

### PR DESCRIPTION
**Pull request by jamesr66a**
https://github.com/onnx/onnx/commit/5e2a94bf493b5a0f76e8314bef9333fad0edae0e made the `axis`, `starts`, and `ends` inputs to Slice into arguments rather than input, so this updates the symbolic implementation of Index to match

### CODE REVIEW

**Comment by jamesr66a** [comment]
@ezyang can you take a look?

**Review by houseroad — APPROVED** [review]
LGTM, thanks!

**Comment by ezyang** [comment]
Crossed wires with #3316. @houseroad, @bddppq is there anything from this PR we still need?

**Comment by jamesr66a** [comment]
Only thing left is cosmetic changes which we can do without

**Pull request closed without merging**
