### PR TITLE
[caffe2] Remove import_legacy.cpp

### PR DESCRIPTION
**Pull request by cyyever**
I think they are for Caffe2 and should be deleted.

### CODE REVIEW

**Comment by cyyever** [comment]
@r-barnes Than you so much for the help

**Comment by cyyever** [comment]
@r-barnes Resolved, feel free to continue.

**Comment by cyyever** [comment]
@r-barnes Help push on it since there are some other PRs depending on this?

**Review by r-barnes — APPROVED** [review]

**Comment by cyyever** [comment]
@r-barnes Sorry, I was sleeping then.

**Pull request closed without merging**
