### PR TITLE
support for moving optimizer state to/from GPU

### PR DESCRIPTION
**Pull request by andreh7**
Here is a proposal to add public methods `cpu()` and `cuda()` to `torch.optim.Optimizer`.

This should solve problems with resuming when the optimizer whose state is loaded from a file. These methods recursively run `.cpu()` or `.cuda()` on all tensors found in the optimizer's `state`.

Should solve #1442 and #2830 and is based on code proposed in these issues.

### CODE REVIEW

**Comment by apaszke** [comment]
This will not work. Even if you move the state to CUDA, the parameters held in the optimizer will still point to the old ones on CPU (`module.cuda()` doesn't update it anyhow). In general all device changes require re-creating the optimizer and there's nothing that can be done about it. I have another patch that resolves these issues but I have to finalize it. Thanks for the PR!

**Comment by andreh7** [comment]
Looking forward to seeing your solution.

(At the moment, with PyTorch out of the box, I can't get back the optimizer's state from a file when resuming training on the same GPU because I get `RuntimeError: arguments are located on different GPUs` even when recreating the optimizer and calling `.load_state_dict()`. With this patch I got it to work)

**Comment by yotamfr** [comment]
+1

**Comment by am-khan** [comment]
+1

**Pull request closed without merging**
