### PR TITLE
[WIP] added CPU implementation of torch.flip function

### PR DESCRIPTION
**Pull request by weiyangfb**
Summary:
1. added CPU implementation of torch.flip to flip a tensor
2. added tests at test_torch, test_cuda and test_autograd

Usage:
x = torch.arange(6).view(2, 3)
y = x.flip([0,1])  # flip along the 1st and 2nd dimention

Todo:
1. add a CUDA implementation of torch.flip (currently automatically generated by ATen)

### CODE REVIEW

**Comment by zou3519** [comment]
I'm not sure how you got all the commits in there, but the right way to rebase your branch on top of master is `git pull --rebase origin master` (or upstream)

**Comment by weiyangfb** [comment]
@zou3519 thanks! I don't know why that happened... I will cherry-pick

**Comment by weiyangfb** [comment]
@zou3519 here is the new branch: https://github.com/weiyangfb/pytorch/tree/flip_a_tensor_CPU

**Comment by ezyang** [comment]
OK, why don't you open a new PR with that branch? Alternatively, force push to `Flip_a_tensor` on your repo, which will update this PR (assuming you are checked out on the commit you want to push, `git push -f weiyangfb HEAD:Flip_a_tensor`

**Comment by weiyangfb** [comment]
@ezyang Thanks for the comments! I will adopt this for future PRs. Currently I've already submitted another PR with commits iterated on a new branch..

**Comment by apaszke** [comment]
This is replaced by the new PR, so I'll close it.

**Pull request closed without merging**
