### PR TITLE
Adding vector_norm to the C++ API

### PR DESCRIPTION
**Pull request by heitorschueroff**
## BC Breaking Note
This PR removes the redundant linalg_ prefix from torch::linalg::linalg_det and torch::linalg::linalg_norm C++ API.

### CODE REVIEW

**Review by mruberry — APPROVED** [review]
More accurately the title of this PR might be: "adds vector_norm to the C++ API"?

Too bad we don't have automated tests for C++ API consistency

**Comment by heitorschueroff** [comment]
@mruberry Another fix, removed linalg prefix from some functions in torch::linalg C++ namespace. This is BC breaking for C++ api, should we go for it?

**Comment by mruberry** [comment]
> @mruberry Another fix, removed linalg prefix from some functions in torch::linalg C++ namespace. This is BC breaking for C++ api, should we go for it?

Thanks for pointing that out. Yes I think it's OK to land but add a BC-breaking note and the BC-breaking label to this PR

**Comment by mruberry** [comment]
Unlanding. My mistake on reviewing this; can we update this to not be BC-breaking by not removing the old names, but just adding the new and correct ones for now?

**Pull request closed without merging**
