### PR TITLE
update onnx tests

### LINKED ISSUE #12586: PyTorch ONNX Tests are Outdated.
In short, the pytorch ONNX tests are outdated and need to be updated to the new API.

For example in this [file](https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_caffe2.py), we are still using Variable.

Or [here](https://github.com/pytorch/pytorch/blob/master/test/onnx/model_defs/mnist.py) we use log_softmax without an explicit `dim=1` argument.

I can work on this if permitted.

### PR DESCRIPTION
**Pull request by ArmenAg**
Fixes #12586

### CODE REVIEW

**Comment by ArmenAg** [comment]
@soumith @houseroad How's it look?

**Review by houseroad — COMMENTED** [review]
Looks good, could you also try to enable the tests which were skipped here: https://github.com/pytorch/pytorch/commit/c1d0784dcb562105e7818ab50c685de665a14740

**Comment by ArmenAg** [comment]
@houseroad I fixed the tests. It also seems like the tests that you skip in c1d0784 are still running in this PR and they run without issue.

**Review by houseroad — APPROVED** [review]
LG, thanks

**Pull request closed without merging**
