### PR TITLE
[ONNX] Do not run 'deduplicate_initializers' when 'keep_initializers_as_inputs' is True

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96320

### Proposal
When arg of 'keep_initializers_as_inputs' is True, it's quite possible that parameters are set by initializer of input.
Hence we should disable de-duplicate initializer optimization when 'keep_initializers_as_inputs==True'.

- [x] Update doc related to `keep_initializers_as_inputs`.

### CODE REVIEW

**Review by thiagocrepaldi — COMMENTED** [review]
Maybe [update docstring](https://github.com/pytorch/pytorch/pull/96320/files#diff-849a5778e2dcf7f36587967273cee0bf20642e35bf4c79405111ea3417c3fb3cL447) for `keep_initializers_as_inputs` to let users know of this side effect?

**Review by abock — APPROVED** [review]
@BowenBao can you update the docstring per @thiagocrepaldi's ask and rebase the PR?

**Review by thiagocrepaldi — APPROVED** [review]

**Pull request closed without merging**
