### PR TITLE
[FR] Automatically infer a common filename prefix

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135158
* #135157

Save the annoyance of specifying this on the command line each time

### CODE REVIEW

**Review by fduwjj — APPROVED** [review]
This looks great to me and we should have more support like this down the road, lol. Please make linter happy (which can be lots of work sometimes).

**Review by c-p-i-o — APPROVED** [review]
Might need to fix up some linters.

**Comment by wconstab** [comment]
I fixed the regular linters. But the BC lint is i guess intentional. Do you guys remember how to land with ignored BC lint?

**Comment by wconstab** [comment]
fr script functions are not yet released nor widely used, so making a change should be OK.  We may want to more aggressively move all of these to non-public functions too.  cc @fduwjj @c-p-i-o 

applied suppress bc tag for now to land this PR

**Pull request closed without merging**
