### PR TITLE
Feature/fsdp use orig param rank0 only load osd

### PR DESCRIPTION
**Pull request by ZhongYingMatrix**
Support fsdp load optimizer state dict in rank0_only style (deprecated scatter_full_optim_state_dict) when use_orig_param is True.
Related discuss with @fegin in this PR #99136 
This implementation broadcasts no_tenosr_osd with _PosDimTensorInfo, and call ``_scatter_orig_param_state`` to shard and scatter FSDP parameters' states. ``_scatter_orig_param_state``broadcasts the _shard_param_infos to shard positive-dimension tensor and broadcast back.
The UT related exposed again and passed.

### CODE REVIEW

**Comment by fegin** [comment]
We will focus on landing https://github.com/pytorch/pytorch/pull/99624 that the implementation can eventually be shared with `use_orig_params=False`.

**Comment by fegin** [comment]
As a result, I'll not approve this PR but thank you for the contribution.

**Comment by ZhongYingMatrix** [comment]
> As a result, I'll not approve this PR but thank you for the contribution.

Thanks for ur feedback. I understand your decision and look forward to the landing of #99624

**Comment by fegin** [comment]
https://github.com/pytorch/pytorch/pull/99624 is landed, feel free to try it and leave feedbacks if you encounter any issues.

**Pull request closed without merging**
