### PR TITLE
Remove unused _convolution_nogroup op

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#68829 Remove unused _convolution_nogroup op**

Differential Revision: [D32627578](https://our.internmc.facebook.com/intern/diff/D32627578)

### CODE REVIEW

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32627578).

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32627578).

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32627578).

**Review by zou3519 — APPROVED** [review]

**Review by albanD — APPROVED** [review]
Cleanup!

**Pull request closed without merging**
