### PR TITLE
Cuda half macros cleanup

### PR DESCRIPTION
**Pull request by syed-ahmed**
Summary: This PR removes couple of macros throughout TH* as part of the re-factoring effort for ATen. Removing these macros should avoid confusion among developers who are trying to move things from TH* to ATen. This PR is part of the THCNumerics deprecation that I have been working on following up on @mruberry's https://github.com/pytorch/pytorch/pull/9318. I am separating these two commits to see if removal of these macros doesn't upset the pytorch public CI, as well as internal builds.

- Commit https://github.com/pytorch/pytorch/commit/1248de7baf4e37f69aa871520135bc9779dccfda removes the code paths guarded by `CUDA_HALF_INSTRUCTIONS` macro. Since the macro was removed in commit https://github.com/pytorch/pytorch/commit/2f186df52d029073c1745274e74ce8700aa3f0f0, `ifdef CUDA_HALF_INSTRUCTIONS` would return false and hence the code path that is kept after this change is for the false case of `ifdef CUDA_HALF_INSTRUCTIONS`

- Commit https://github.com/pytorch/pytorch/commit/520c99b057e741ccd4c96653650932902fb8b53e removes the code paths guarded by `CUDA_HALF_TENSOR` macro. Since Pytorch now provides support for only CUDA 8.0 and above, `CUDA_HALF_TENSOR` is always true since CUDA 8.0 satisfies `CUDA_HAS_FP16` and hence, the code path that is kept after this change is for the true case of `ifdef CUDA_HALF_TENSOR`.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
LGTM, but the builds are failing ;)

**Comment by syed-ahmed** [comment]
Looks like I missed some in the torch module. Giving the CI another go at it. :)

**Comment by yf225** [comment]
@syed-ahmed @ezyang Should we move forward with this patch? The `caffe2-py2-cuda9.0-cudnn7-ubuntu16.04-test` CI error is probably just a flaky test.

**Comment by syed-ahmed** [comment]
This PR and and https://github.com/pytorch/pytorch/pull/10301 are good to go.

**Pull request closed without merging**
