### PR TITLE
update triton pin

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #101919

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @anijain2305

### CODE REVIEW

**Comment by shunting314** [comment]
Is the failed check linux-binary-manywheel worth worrying about?

**Comment by desertfire** [comment]
Fwiw, `AlbertForQuestionAnswering` has always been failing accuracy on the dashboard (GCP A100) but pass on AWS A10G. Maybe this pin update just made the behavior consistent between AWS and GCP, so it's ok to xfail `AlbertForQuestionAnswering` in this PR and fix it later. We still need to take care of other failures though.

**Comment by bertmaher** [comment]
I'm going to try to import this to Meta this morning.  Please hold off landing until I can verify it!

**Comment by ngimel** [comment]
Failed manywheel checks are fine, new wheels are pushed only after PR has landed. We could skip Albert I guess but someone should look into why it's failing

**Comment by desertfire** [comment]
> Failed manywheel checks are fine, new wheels are pushed only after PR has landed. We could skip Albert I guess but someone should look into why it's failing

cc @anijain2305

**Comment by Chillee** [comment]
So to clarify, the main test I should look into is the `test_minifier_isolate` test?

**Comment by ngimel** [comment]
Yep, and add skips to Albert

**Comment by ezyang** [comment]
In a pinch, feel free to disable this test and I can look into it.

**Comment by mlazos** [comment]
@Chillee could we update this to https://github.com/openai/triton/commit/fb30d840690cf9f2fd9dff5fdf8863374af3b6ea
, it contains a bugfix I need.

**Review by ngimel — APPROVED** [review]

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
