### PR TITLE
[JIT] consider side effects when trying moves in alias analysis

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#39497 [JIT] consider side effects when trying moves in alias analysis**

Previously, we didn't consider side effects at all when moving nodes in alias analysis. It is never valid to reorder a node with a side effect. This has led to bugs when used with Bailouts. 

Unfortunately this will might cause regressions but it wasn't correct prior :/

Differential Revision: [D21963774](https://our.internmc.facebook.com/intern/diff/D21963774)

### CODE REVIEW

**Review by suo — APPROVED** [review]

**Review by suo — CHANGES_REQUESTED** [review]
Sorry didn't mean to accept. My main comment about this is that we should really be going in the other direction and remove uses of `hasSideEffects()` rather than using them more. We already have an alias annotation language that's supposed to give complete effects information for an operator; we should extend that instead. As is, we now need to check three things (`hasSideEffects`, `isNondeterministic`, and the alias annotations) to query the effects of an operator; it should only be one.

**Comment by eellison** [comment]
@suo I don't think we should delay a correctness change.  @ZolotukhinM has noticed that we give sometimes give incorrect results because nodes are moved across a Bailout,  as has @SplitInfinity with `with` statements. 

What is your concrete suggestion ? There are some nodes which pull in global state and cannot be re-ordered. Whether or not this is expressible in the schema doesn't affect the logic here. This also isn't related to aliasing and mutation - which are a tracked set of set of effects which we know how to reason about.

**Comment by suo** [comment]
Concretely: add a way for the alias annotation language to express side effects (possibly: writes to the world), then fix up the existing operators to use that. Then query that in alias analysis. Ideally we only have one place where we need to express what effects an operator has.

I'm also okay with this PR as a matter of correctness unblocking, although it seems to have build issues.

**Comment by eellison** [comment]
Those change seem good but I think we should land this now, currently this is blocking correctness on a number of things we know about, and possibly others things we don't. It will also likely cause regressions in graph fusion, which will need to be looked into.

**Review by suo — APPROVED** [review]

**Pull request closed without merging**
