### PR TITLE
Add forward AD support for miscellanous operators

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #68629
* #68628
* #67045
* #67041
* __->__ #67820
* #66294
* #66293
* #66292

Original PR here: https://github.com/pytorch/pytorch/pull/67040

Differential Revision: [D32314423](https://our.internmc.facebook.com/intern/diff/D32314423)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
If CI is happy, I'm happy!

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32314423).

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32314423).

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32314423).

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32314423).

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32314423).

**Pull request closed without merging**
