### PR TITLE
Fix dtype mismatch between cpu and meta for layer/batch norm meta tests

### PR DESCRIPTION
**Pull request by kundaMwiza**
Fixes #ISSUE_NUMBER

cc @ezyang @eellison @bdhirsh

### CODE REVIEW

**Comment by kundaMwiza** [comment]
@zou3519  Moving the batch/layer norm fixes here

**Review by ezyang — APPROVED** [review]

**Comment by kundaMwiza** [comment]
Closing as the dtype mismatch is due to the casting difference between CPU and other devices. Matching Meta with CPU will break meta tests between Meta and any other device.

**Pull request closed without merging**
