### PR TITLE
register decomposition for rsub in torch._refs

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #118288
* #118398

### CODE REVIEW

**Comment by isuruf** [comment]
I have no clue why I'm getting a
```
2024-01-25T17:11:09.0227081Z torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx_wrapper' raised:
2024-01-25T17:11:09.0227278Z MissingOperatorWithoutDecomp: missing lowering
2024-01-25T17:11:09.0227417Z   target: prims.mul.default
2024-01-25T17:11:09.0227553Z   args[0]: TensorBox(StorageBox(
2024-01-25T17:11:09.0228060Z     InputBuffer(name='primals_1', layout=FixedLayout('cuda', torch.float32, size=[5, 5], stride=[5, 1]))
2024-01-25T17:11:09.0228254Z   ))
2024-01-25T17:11:09.0228368Z   args[1]: 2
```

**Review by lezcano — APPROVED** [review]
Lovely, thanks!

**Comment by isuruf** [comment]
There's https://github.com/pytorch/pytorch/pull/118398 in this stack which needs review as well.

**Pull request closed without merging**
