### PR TITLE
[JIT] clang-format JIT code

### PR DESCRIPTION
**Pull request by SplitInfinity**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#34701 [JIT] clang-format JIT code**
* #34700 [tools] Replace clang_format.py with clang_format_new.py

Summary:
This commit runs the newly added tools/clang_format.py on the JIT
codebase and includes all of the formatting changes thus produced.

Testing:
Ran the script, CI.

### CODE REVIEW

**Comment by SplitInfinity** [comment]
Welp, looks like `clang-tidy` hates this...

**Comment by suo** [comment]
Today, `clang-tidy` checks diffs but doesn't run on master (similar situation to `clang-format` where the infrastructure to support it being blocking hasn't been built). So safe to ignore in this case.

**Review by suo — APPROVED** [review]
lg assuming it's mechanical. might want to do the locking thing for this one

**Comment by SplitInfinity** [comment]
Closing because something went wrong with `ghstack`.

**Pull request closed without merging**
