### PR TITLE
Adding models to jenkins benchmark script

### PR DESCRIPTION
**Pull request by ajauhri**
Summary:
Adding and editing the jenkins benchmarks script to accommadate both
Renext and Shufflenet models.

Differential Revision: D15515354

### CODE REVIEW

**Comment by bddppq** [comment]
Benchmark runs triggered:
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger-test/31779/
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger-test/24788/

**Comment by bddppq** [comment]
Benchmark runs re-triggered:
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger-test/31819/
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger-test/24827/

**Comment by ajauhri** [comment]
New runs -- 
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger-test/31907/
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger-test/24915/

**Comment by ajauhri** [comment]
Benchmark runs re-triggered with new changes which excludes float16 test -- 

https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger-test/31993/
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger-test/25166/

**Review by bddppq — APPROVED** [review]
LGTM

**Pull request closed without merging**
