### PR TITLE
Hold RRef shared_ptr in to_here/local_value returned future

### LINKED ISSUE #28885: test_graph_for_python_remote_call is flaky
failed: https://circleci.com/gh/pytorch/pytorch/3405647?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

passed: https://circleci.com/gh/pytorch/pytorch/3402730?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#29306 [WIP] Hold RRef shared_ptr in to_here/local_value returned future**

For rpc.remote(...).to_here().wait(), the rref is a temp variable.
It seems it could be deleted before to_here() message gets
processed on the owner. When that happens, wait() call will block
forever, as the owner has been deleted and will not become alive
again.

closes #28885

### CODE REVIEW

**Comment by zhaojuanmao** [comment]
adding userRef will make it a little hard to refactor later on if we want to have a generic pyFuture in our code base soon. 

for rpc.remote(...).to_here().wait(), the temp variable userref shared_ptr is still being used when calling to_here(). is userref expected to be deleted in this case?

**Comment by mrshenli** [comment]
@zhaojuanmao 

> adding userRef to pyFuture will make it a little hard to refactor later on if we want to have a generic pyFuture in our code base soon.

The new future will need to hold the `UserRRef` as well I think, otherwise the same thing could occur.

> for rpc.remote(...).to_here().wait(), the temp variable userref shared_ptr is still being used when calling to_here(). is userref expected to be deleted in this case?

Yes, the `UserRRef` is still used when calling `to_here()` but not so when calling `wait()`. What happens is that:

1. `rpc.remote()` returns an `RRef`
2. `RRef.to_here()` returns a `future`
3. When calling `future.wait()`, the `RRef` is no longer referenced, so it can be deleted. Even though the deletion actually occurs after `RRef.to_here()`, the delete message could be processed at the callee before the `to_here()` message.

**Comment by zhaojuanmao** [comment]
3. When calling `future.wait()`, the `RRef` is no longer referenced, so it can be deleted. Even though the deletion actually occurs after `RRef.to_here()`, the delete message could be processed at the callee before the `to_here()` message.

but I remember you added the rref shared_ptr to pendingUsers_, that will hold rref shared_ptr to be alive until future is done?

**Comment by mrshenli** [comment]
> but I remember you added the rref shared_ptr to pendingUsers_, that will hold rref shared_ptr to be alive until future is done?

Currently, `to_here` does not do that. We only have `_pendingUsers` (for `UserRRef`s not confirmed by the owner) and `_pendingChildren` (for sharing `UserRRef`). In this case, the `UserRRef` could have already been confirmed by the owner, and there is no `RRef` sharing. 

But, that's a good point, maybe we should do it internally in C++ `RRef::toHere()`. Let me think a bit.

**Comment by mrshenli** [comment]
Yes, we could add something like `pendingFutures_` in `RRefContext` which holds the `RRef` alive when `to_here` or `local_value` is called, and then clear them when the future fires. In this way, futures can stay simple. Comments?

@zhaojuanmao  @aazzolini  @pritamdamania87 @gqchen

**Comment by mrshenli** [comment]
I like @zhaojuanmao's proposal more than the current implementation in this PR, as this thing should be addressed in the C++ land instead of in the Python land. Doing it in `PyRRef` won't be a complete solution.

**Comment by mrshenli** [comment]
```
Nov 06 23:46:53 ======================================================================
Nov 06 23:46:53 ERROR: test_nested_rpc (__main__.RpcTestWithFork)
Nov 06 23:46:53 ----------------------------------------------------------------------
Nov 06 23:46:53 Traceback (most recent call last):
Nov 06 23:46:53   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 130, in wrapper
Nov 06 23:46:53     self._join_processes(fn)
Nov 06 23:46:53   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 211, in _join_processes
Nov 06 23:46:53     self._check_return_codes(elapsed_time)
Nov 06 23:46:53   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 230, in _check_return_codes
Nov 06 23:46:53     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Nov 06 23:46:53 RuntimeError: Process 0 terminated or timed out after 300.2640292644501 seconds
```

Still hit flaky tests. Investigating.

**Comment by mrshenli** [comment]
Add #29396 to stop the bleeding while we discuss solution here.

**Comment by pritamdamania87** [comment]
> Yes, we could add something like pendingFutures_ in RRefContext which holds the RRef alive when to_here or local_value is called, and then clear them when the future fires. In this way, futures can stay simple. Comments?

Didn't we discuss a way to resolve a similar situation while discussing the RRef protocol? Isn't this similar to using the RRef in an RPC and then the RRef goes out of scope on the callee but we still need to keep it alive due to an outstanding RPC?

**Comment by pritamdamania87** [comment]
@mrshenli I was wondering if we had any consensus on the approach here?

> For rpc.remote(...).to_here().wait(), the rref is a temp variable.
It seems it could be deleted before to_here() message gets
processed on the owner. When that happens, wait() call will block
forever, as the owner has been deleted and will not become alive
again.

I was reading the PR summary again and didn't follow why the `wait` call would block? If the rref has been deleted, shouldn't `to_here` throw an exception saying the RRef no longer exists?

**Pull request closed without merging**
