### PR TITLE
add support for pin memory on xpu device

### PR DESCRIPTION
**Pull request by leizhenyuan**
add support for pin memory on xpu device

### CODE REVIEW

**Comment by leizhenyuan** [comment]
@ezyang  I would like to add a xpu support for pin_memory, pls check is there and problem in this pr?

**Comment by ezyang** [comment]
Seems alright. Need cla

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Fix ci and i will land

**Comment by ezyang** [comment]
Ci fail is real

**Comment by gujinghui** [comment]
@leizhenyuan  pls fix the CI fail ASAP.

**Comment by leizhenyuan** [comment]
hi, @ezyang  i met this in build test :
Build should have OpenMP enabled, but torch.backends.openmp.is_available() is False
can u give me some advice on how to enable openMP to pass the build test?
thanks a lot

**Comment by ezyang** [comment]
it seems unlikely to be your problem

**Comment by leizhenyuan** [comment]
There are still some build test failed, could u please help me pass these tests? @ezyang 
Thanks a lot.

**Comment by leizhenyuan** [comment]
seems build still failed for some filed cannot be found

**Pull request closed without merging**
