### PR TITLE
optimize index_select performance on CPU with TensorIterator

### PR DESCRIPTION
**Pull request by mingfeima**
This PR aims at improving `index_select` performance on CPU with `TensorIterator`.
The code has equally effective optimization for both contiguous tensor and non-contiguous tensor. 
The code will try to parallel inner loop in case the slice of copy is large enough, otherwise it will parallel on outer loop.
Thus both the user scenarios from DLRM (from `Embedding`) and Fairseq transformer is covered.

1. for contiguous input, single socket: **1.25x** performance speedup
2. for non-contiguous input, single socket: **799x** performance speedup
3. for contiguous input, single core: same performance
4. for non-contiguous input, single core: **31x** performance speedup

### CODE REVIEW

**Comment by mingfeima** [comment]
The current implementation of `index_select` from TH module has two performance drawbacks:
1. when input is contiguous, it does parallelization; but with non-contiguous input it runs in sequential.
2. non-contiguous input relies on `copy_` which requires creating sub tensors for each row to be copied. This is too heavy for `Embedding` since `embedding_dim` is usually not a very big number.

With non-contiguous input, this PR brings **799x** speedup on single socket and **31x** speedup on single core on Xeon Skylake 6148.

Below shows the performance compare between **original** and **this pr**, the benchmark will compare from:
1. a range of input size
2. contiguous tensor and non-contiguous tensor
3. single socket and single core

benchmark code available at this [op_bench-py](https://github.com/mingfeima/op_bench-py), to reproduce, `./run.sh index_select.py`. Test machine is Xeon Skylake 6148 with 2*20 cores @2.40GHz

1. input size is [num_embeddings, embedding_dim]
2. Unit is **index/second** a.k.a the throughput, the higher the better

#### single socket run
input size | index size | contiguous | original | this pr | speedup
-- | -- | -- | -- | -- | --
[10000, 128] | 10000 | TRUE | 406.872 | 506.43 | 1.24
[100000, 128] | 10000 | TRUE | 376.868 | 469.22 | 1.25
[1000000, 128] | 100000 | TRUE | 29.124 | 33.91 | 1.16
[10000000, 128] | 1000000 | TRUE | 34.433 | 37.90 | 1.10
[10000, 128] | 10000 | FALSE | 0.606 | 484.25 | 799.09
[100000, 128] | 10000 | FALSE | 0.609 | 455.83 | 748.49
[1000000, 128] | 100000 | FALSE | 0.543 | 35.02 | 64.49
[10000000, 128] | 1000000 | FALSE | 0.543 | 38.35 | 70.63

#### single core run
input size | index size | contiguous | original | this pr | speedup
-- | -- | -- | -- | -- | --
[10000, 128] | 10000 | TRUE | 21.362 | 21.71 | 1.02
[100000, 128] | 10000 | TRUE | 18.575 | 18.71 | 1.01
[1000000, 128] | 100000 | TRUE | 4.658 | 4.62 | 0.99
[10000000, 128] | 1000000 | TRUE | 4.625 | 4.75 | 1.03
[10000, 128] | 10000 | FALSE | 0.655 | 20.30 | 30.99
[100000, 128] | 10000 | FALSE | 0.66 | 18.68 | 28.31
[1000000, 128] | 100000 | FALSE | 0.585 | 4.69 | 8.01
[10000000, 128] | 1000000 | FALSE | 0.586 | 4.69 | 8.00

attach the original log:
**original**
```bash
### using OMP_NUM_THREADS=20
input size: [10000, 128]; index size: [10000]; contiguous; thoughput: indexs/us = 406.872
input size: [100000, 128]; index size: [10000]; contiguous; thoughput: indexs/us = 376.868
input size: [1000000, 128]; index size: [100000]; contiguous; thoughput: indexs/us = 29.124
input size: [10000000, 128]; index size: [1000000]; contiguous; thoughput: indexs/us = 34.433
input size: [10000, 128]; index size: [10000]; non-contiguous; thoughput: indexs/us = 0.606
input size: [100000, 128]; index size: [10000]; non-contiguous; thoughput: indexs/us = 0.609
input size: [1000000, 128]; index size: [100000]; non-contiguous; thoughput: indexs/us = 0.543
input size: [10000000, 128]; index size: [1000000]; non-contiguous; thoughput: indexs/us = 0.543

### using OMP_NUM_THREADS=1
input size: [10000, 128]; index size: [10000]; contiguous; thoughput: indexs/us = 21.362
input size: [100000, 128]; index size: [10000]; contiguous; thoughput: indexs/us = 18.575
input size: [1000000, 128]; index size: [100000]; contiguous; thoughput: indexs/us = 4.658
input size: [10000000, 128]; index size: [1000000]; contiguous; thoughput: indexs/us = 4.625
input size: [10000, 128]; index size: [10000]; non-contiguous; thoughput: indexs/us = 0.655
input size: [100000, 128]; index size: [10000]; non-contiguous; thoughput: indexs/us = 0.660
input size: [1000000, 128]; index size: [100000]; non-contiguous; thoughput: indexs/us = 0.585
input size: [10000000, 128]; index size: [1000000]; non-contiguous; thoughput: indexs/us = 0.586
```

**this pr**
```bash
### using OMP_NUM_THREADS=20
input size: [10000, 128]; index size: [10000]; contiguous; thoughput: indexs/us = 506.430
input size: [100000, 128]; index size: [10000]; contiguous; thoughput: indexs/us = 469.219
input size: [1000000, 128]; index size: [100000]; contiguous; thoughput: indexs/us = 33.907
input size: [10000000, 128]; index size: [1000000]; contiguous; thoughput: indexs/us = 37.898
input size: [10000, 128]; index size: [10000]; non-contiguous; thoughput: indexs/us = 484.249
input size: [100000, 128]; index size: [10000]; non-contiguous; thoughput: indexs/us = 455.830
input size: [1000000, 128]; index size: [100000]; non-contiguous; thoughput: indexs/us = 35.017
input size: [10000000, 128]; index size: [1000000]; non-contiguous; thoughput: indexs/us = 38.354

### using OMP_NUM_THREADS=1
input size: [10000, 128]; index size: [10000]; contiguous; thoughput: indexs/us = 21.707
input size: [100000, 128]; index size: [10000]; contiguous; thoughput: indexs/us = 18.714
input size: [1000000, 128]; index size: [100000]; contiguous; thoughput: indexs/us = 4.616
input size: [10000000, 128]; index size: [1000000]; contiguous; thoughput: indexs/us = 4.750
input size: [10000, 128]; index size: [10000]; non-contiguous; thoughput: indexs/us = 20.300
input size: [100000, 128]; index size: [10000]; non-contiguous; thoughput: indexs/us = 18.684
input size: [1000000, 128]; index size: [100000]; non-contiguous; thoughput: indexs/us = 4.687
input size: [10000000, 128]; index size: [1000000]; non-contiguous; thoughput: indexs/us = 4.686
```

**Comment by Jianhui-Li** [comment]
@gottbrath @VitalyFedyunin  FYI index_select moved from TH to ATEN

**Comment by VitalyFedyunin** [comment]
Hi! I'm starting review now, meanwhile please remove old TH code.

**Comment by mingfeima** [comment]
old TH code has been removed.

**Comment by mingfeima** [comment]
@VitalyFedyunin please review the code!

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 523f4ba:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=523f4ba9afc5bb3155b57f8eb413a6c1b289177b).

### :detective: 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4029275) pytorch_linux_xenial_py3_6_gcc5_4_ge_config_simple_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=78105521) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=78105521))
<details>
<summary>
<code>Dec 20 06:08:22 RuntimeError: test_jit_simple failed!</code>
</summary>

```
Dec 20 06:08:22 Ran 2307 tests in 81.145s 
Dec 20 06:08:22  
Dec 20 06:08:22 FAILED (errors=4, skipped=76, expected failures=1) 
Dec 20 06:08:22  
Dec 20 06:08:22 Generating XML reports... 
Dec 20 06:08:22 Traceback (most recent call last): 
Dec 20 06:08:22   File "test/run_test.py", line 456, in <module> 
Dec 20 06:08:22     main() 
Dec 20 06:08:22   File "test/run_test.py", line 449, in main 
Dec 20 06:08:22     raise RuntimeError(message) 
Dec 20 06:08:22 RuntimeError: test_jit_simple failed! 
Dec 20 06:08:22 + cleanup 
Dec 20 06:08:22 + retcode=1 
Dec 20 06:08:22 + set +x 
Dec 20 06:08:22 =================== sccache compilation log =================== 
Dec 20 06:08:22 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 20 06:08:22 Compile requests                56 
Dec 20 06:08:22 Compile requests executed        0 
Dec 20 06:08:22 Cache hits                       0 
Dec 20 06:08:22 Cache misses                     0 
Dec 20 06:08:22 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by VitalyFedyunin — APPROVED** [review]

**Pull request closed without merging**
