### PR TITLE
[doc] add pin_memory argument to rand

### PR DESCRIPTION
**Pull request by foram-chandra**
Similar to #85123

cc - @mruberry @kshitij12345

### CODE REVIEW

**Comment by mruberry** [comment]
This and https://github.com/pytorch/pytorch/issues/85123 could be combined into one PR for simplicity in the future, but it's no big deal

**Comment by foram-chandra** [comment]
Sure, will keep that in mind. 
Thank you! :)

**Review by mruberry — APPROVED** [review]
Cool! Thanks @foram-chandra

**Pull request closed without merging**
