### PR TITLE
making sure we don't accept pointers in int64_t c-tor

### PR DESCRIPTION
**Pull request by Krovatkin**
### Description
This PR adds extra checking to make sure we don't accidentally pass a pointer as an int into an int64_t c-tor.

### CODE REVIEW

**Comment by ezyang** [comment]
You've got to convert the necessary sites to used the unchecked constructor. Also, idiomatically, the enum argument comes first.

**Comment by Krovatkin** [comment]
@ezyang 

> Also, idiomatically, the enum argument comes first.

For an implicit c-tor, we can't add the enum argument. Wouldn't it be more confusing that the int argument moves from one position to another in two constructors?


> You've got to convert the necessary sites to used the unchecked constructor. 

👍 ⚡ 💯

**Comment by ezyang** [comment]
> Wouldn't it be more confusing that the int argument moves from one position to another in two constructors?

Nah, the way I think about it is you have non-tagged constructors, and then tagged constructors. So there is optionally a tag at the beginning, and then the rest of the arguments.

**Comment by Krovatkin** [comment]
> Nah, the way I think about it is you have non-tagged constructors, and then tagged constructors. So there is optionally a tag at the beginning, and then the rest of the arguments.

sounds gut.. I'll make a change

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
