### PR TITLE
Avoid calling tensor.data.set_() in DDP

### PR DESCRIPTION
**Pull request by mrshenli**
@pietern @gchanan

### CODE REVIEW

**Comment by mrshenli** [comment]
@pietern do we actually need to merge this before #18953? Otherwise, some DDP tests (e.g., test_gloo_backend and test_nccl_backend) would fail.

**Review by pietern — COMMENTED** [review]
If I understand correctly, the only reason we still need `main_module_{params,buffers}_data` is because we pass them to `_dist_broadcast_coalesced` and need them to be detached from autograd. Is that correct? If so, is there a way we can lift that into `_dist_broadcast_coalesced` itself, removing the need for keeping the separate list?

**Comment by mrshenli** [comment]
@pietern sure, let me make that change. You mean DDP's `_dist_broadcast_coalesced`, not the c++ one, right?

**Comment by mrshenli** [comment]
@pietern I did it a little differently. The `main_module_{params,buffers}_data` lists are removed by wrapping the entire `_sync_params` call with `torch.no_grad(). Does this look OK to you?

**Comment by mrshenli** [comment]
lint failure is not introduced by this PR:

```
47.12s$ flake8
./test/test_namedtuple_return_api.py:8:1: F401 'itertools' imported but unused
The command "flake8" exited with 1.
```

**Comment by mrshenli** [comment]
The failed test (`pr/py2-clang7-rocmdeb-ubuntu16.04`) passes in [rerun](https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger/24039/)

**Review by pietern — APPROVED** [review]
Good to go.

**Pull request closed without merging**
