### PR TITLE
[Doc] Update Intel GPU Support on README

### PR DESCRIPTION
**Pull request by guangyey**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #126001

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Review by albanD — APPROVED** [review]
Sounds good!

**Review by dvrogozh — COMMENTED** [review]
How instruction [1] linked in this readme correlates with the oneAPI setup instruction? For example, see [2] - oneAPI instruction for Ubuntu 22.04.

It seems that [1] suggest alternate approach to setup what's already available thru oneAPI. This gives questions on support policies and update frequencies. Some concerns might be raised on potentially conflicting packages wish user to switch his oneAPI configured system to what is described here at [1].

1: https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpus.html
2: https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&distributions=aptpackagemanager

For the reference, these are packages currently getting installed following [1]:
```
root@4beba528e721:/# apt update
Get:1 https://apt.repos.intel.com/intel-for-pytorch-gpu-dev all InRelease [5620 B]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:6 https://apt.repos.intel.com/intel-for-pytorch-gpu-dev all/main amd64 Packages [22.0 kB]
Get:7 https://apt.repos.intel.com/intel-for-pytorch-gpu-dev all/main all Packages [7686 B]
Fetched 35.3 kB in 1s (49.2 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
root@4beba528e721:/# apt install intel-for-pytorch-gpu-dev intel-pti-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu cpp cpp-11 fontconfig-config fonts-dejavu-core g++ g++-11 gcc gcc-11 gcc-11-base
  intel-for-pytorch-gpu-dev-env-0.5 intel-oneapi-common-licensing intel-oneapi-common-licensing-2024.1 intel-oneapi-common-oneapi-vars
  intel-oneapi-common-oneapi-vars-2024.1 intel-oneapi-common-vars intel-oneapi-compiler-cpp-eclipse-cfg-2024.1 intel-oneapi-compiler-dpcpp-cpp
  intel-oneapi-compiler-dpcpp-cpp-2024.1 intel-oneapi-compiler-dpcpp-cpp-common-2024.1 intel-oneapi-compiler-dpcpp-cpp-runtime-2024.1
  intel-oneapi-compiler-dpcpp-eclipse-cfg-2024.1 intel-oneapi-compiler-shared-2024.1 intel-oneapi-compiler-shared-common-2024.1
  intel-oneapi-compiler-shared-runtime-2024.1 intel-oneapi-dev-utilities-2024.1 intel-oneapi-dev-utilities-eclipse-cfg-2024.1 intel-oneapi-dpcpp-cpp-2024.1
  intel-oneapi-dpcpp-debugger-2024.1 intel-oneapi-icc-eclipse-plugin-cpp-2024.1 intel-oneapi-libdpstd-devel-2022.5 intel-oneapi-mkl-classic-devel-2025.0
  intel-oneapi-mkl-classic-include-2025.0 intel-oneapi-mkl-classic-include-common-2025.0 intel-oneapi-mkl-cluster-2025.0 intel-oneapi-mkl-cluster-devel-2025.0
  intel-oneapi-mkl-cluster-devel-common-2025.0 intel-oneapi-mkl-core-2025.0 intel-oneapi-mkl-core-common-2025.0 intel-oneapi-mkl-core-devel-2025.0
  intel-oneapi-mkl-core-devel-common-2025.0 intel-oneapi-mkl-devel intel-oneapi-mkl-devel-2025.0 intel-oneapi-mkl-sycl-2025.0 intel-oneapi-mkl-sycl-blas-2025.0
  intel-oneapi-mkl-sycl-data-fitting-2025.0 intel-oneapi-mkl-sycl-devel-2025.0 intel-oneapi-mkl-sycl-devel-common-2025.0 intel-oneapi-mkl-sycl-dft-2025.0
  intel-oneapi-mkl-sycl-include-2025.0 intel-oneapi-mkl-sycl-lapack-2025.0 intel-oneapi-mkl-sycl-rng-2025.0 intel-oneapi-mkl-sycl-sparse-2025.0
  intel-oneapi-mkl-sycl-stats-2025.0 intel-oneapi-mkl-sycl-vm-2025.0 intel-oneapi-openmp-2024.1 intel-oneapi-openmp-common-2024.1 intel-oneapi-tbb-2021.12
  intel-oneapi-tbb-common-2021.12 intel-oneapi-tbb-common-devel-2021.12 intel-oneapi-tbb-devel-2021.12 intel-oneapi-tcm-1.0 intel-oneapi-tlt
  intel-oneapi-tlt-2024.1 intel-pti-dev-0.7 libasan6 libatomic1 libbinutils libbrotli1 libbsd0 libc-dev-bin libc-devtools libc6-dev libcc1-0 libcrypt-dev
  libctf-nobfd0 libctf0 libdeflate0 libexpat1 libfontconfig1 libfreetype6 libgcc-11-dev libgd3 libgomp1 libisl23 libitm1 libjbig0 libjpeg-turbo8 libjpeg8 liblsan0
  libmd0 libmpc3 libmpfr6 libnsl-dev libpng16-16 libquadmath0 libstdc++-11-dev libtiff5 libtirpc-dev libtsan0 libubsan1 libwebp7 libx11-6 libx11-data libxau6
  libxcb1 libxdmcp6 libxpm4 linux-libc-dev manpages manpages-dev rpcsvc-proto ucf
```

**Review by gujinghui — APPROVED** [review]

**Review by EikanWang — APPROVED** [review]

**Pull request closed without merging**
