### PR TITLE
added persistent option to buffers and namedbuffers

### LINKED ISSUE #85235: Add `persistent` option to `nn.Module.buffers`.
### 🚀 The feature, motivation and pitch

For convenience, it would be nice if the [`nn.Module.buffers`](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.buffers) could distinguish between persistent and non-persistent buffers.

```python
def buffers(self, recurse: bool = False, persistent: Optional[bool] = None) -> Iterator[Tensor]:
```

Which yields an iterator for either only persistent buffers (`True`), non-persistent buffers (`False`) or both (`None`).

### Alternatives

_No response_

### Additional context

Currently, one either has to make use of the private attribute `nn.Module._non_persistent_buffers_set`, or filter `self.buffers` via the entries of the `state_dict`.

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

### PR DESCRIPTION
**Pull request by randolf-scholz**
Fixes #85235

Alternative to PR https://github.com/pytorch/pytorch/pull/129655, implements 3-valued option (None or bool).

- adds keyword only argument `persistent: Optional[bool] = None` to `nn.Module.buffers`
- updated docstrings slightly.
- added test.

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### CODE REVIEW

**Review by mikaylagawarecki — APPROVED** [review]
Thanks!

**Comment by PaliC** [comment]
@pytorchbot revert -m "breaking internal pyre tests" -c "ghfirst"

@mikaylagawarecki should help reland this

**Comment by mikaylagawarecki** [comment]
Will look into relanding sometime this week (seems the branch is deleted so I can't reopen this PR, will open another PR)

**Comment by randolf-scholz** [comment]
@mikaylagawarecki I restored the branch and re-opened here: #134219

**Pull request closed without merging**
