### PR TITLE
Add `module.training` to docs

### PR DESCRIPTION
**Pull request by ssnl**
A lot of people ask https://discuss.pytorch.org/t/check-if-model-is-eval-or-train/9395/3

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]
LGTM. I didn't actually know what the ivar and vartype does, but the rendered html looks good

image

**Comment by SsnL** [comment]
@zou3519 oh wow, is there a CI build that we can use to preview docs?

**Comment by zou3519** [comment]
@SsnL I just built the docs locally lol. But I think you might be able to pull the docker container of `pytorch_python_doc_push` and grab the html from there (I don't remember if we persist the docs build on success or not). We've been wanting an easy way to preview changes to the docs (#28035) but no one has worked on it

**Comment by SsnL** [comment]
@zou3519 oh great :) thanks for building and previewing the docs.

**Pull request closed without merging**
