### PR TITLE
rename ort to maia

### LINKED ISSUE #123264: Rename ort to maia
### 🚀 The feature, motivation and pitch

Maia is the name of Microsoft's AI accelerator hardware; we want to use this name instead of "ort."

### Alternatives

_No response_

### Additional context

_No response_

cc @bdhirsh

### PR DESCRIPTION
**Pull request by ashari4**
Fixes #123264 

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen

### CODE REVIEW

**Comment by albanD** [comment]
cc @BowenBao @thiagocrepaldi  isn't the ort namespace used by onnx team?

**Comment by ashari4** [comment]
> cc @BowenBao @thiagocrepaldi isn't the ort device used by onnx team?

 i believe onnx isn't using the ort device anymore. adding @souptc to the discussion in case he has any inputs.

**Comment by thiagocrepaldi** [comment]
> cc @BowenBao @thiagocrepaldi isn't the ort device used by onnx team?

this was used by onnxrunitme team, but AFAIK they are not using anymore and maia team will take over

**Comment by albanD** [comment]
Ok, it would be great to have someone from onnxruntime to confirm that yes.
Also curious why maia is not using the out of core device here? That would be most likely simpler compared to having to build a brand new core integration for this key that doesn't really exist right now. Details on that process are here: https://pytorch.org/tutorials/advanced/privateuseone.html

**Comment by souptc** [comment]
Hi, this is Cheng from onnxruntime team. onnxruntime team is not using the "ORT" key

**Comment by ashari4** [comment]
> Also curious why maia is not using the out of core device here? That would be most likely simpler compared to having to build a brand new core integration for this key that doesn't really exist right now. 

We already have a backend implemented (out of tree) for this key. we just want to rename the key from "ort" to "maia"

**Comment by albanD** [comment]
@ashari4 have you tried using the privateuse1 key as I mentioned above? It will actually give you a lot more features from core than the ort key.

**Comment by souptc** [comment]
> @ashari4 have you tried using the privateuse1 key as I mentioned above? It will actually give you a lot more features from core than the ort key.

Hi @albanD , yes it is a great feature, but our market team prefer the experience with a key in main distribution. 
Since we are not adding any new keys, the impact should be limited, right?

**Review by albanD — APPROVED** [review]
Ok then!
I will just mention that we have unfortunately limited bandwidth to review big PRs for core integration of backends and we prioritize supporting privateuse1 that is used by many backends before one-off ones.

**Comment by albanD** [comment]
Can you please rebase to fix all merge conflicts?

**Comment by ashari4** [comment]
@mikaylagawarecki could i please get some help re-queueing this job:  [pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / build (gh)](https://hud.pytorch.org/pr/pytorch/pytorch/123265#23992959798)

it looks like this job timed out when building the codebase, an d this isn't related to my pr change. the other job failures look to be "unrelated" according to the Dr. CI post.

**Comment by albanD** [comment]
> it looks like this job timed out when building the codebase. I don't think the timeout is because of my pr change.

Most likely it is ;) you are changing so many files that our distributed ccache cannot be re-used and the build job end up doing a timeout.

**Comment by ashari4** [comment]
@albanD thanks for clarifying. looks like the ci is good now. could you please help me merge it

**Comment by albanD** [comment]
The test failure is real, you will have to override the backwards_compatibility allow list to allow the renaming of this native op.

**Comment by albanD** [comment]
@pytorchbot merge

:crossed_fingers:

**Pull request closed without merging**
