### PR TITLE
[WIP] Move sort/topk/kthvalue/mode/median to ATen

### PR DESCRIPTION
**Pull request by t-vi**
Also add kthvalue on CUDA. Based on #8406 by Pararth Shah (thank you).

I did try to make it more C++-sy.
- Needs more cleanups/splitting of the .cu.
- I'd like to go over the funny cases and see if they have tests (e.g. try topk with scalar argument and k=0).
- I wonder whether some more of THCNumerics use can be dropped.
- Also needs removal of TH/THC code.

### CODE REVIEW

**Comment by t-vi** [comment]
So I've looked at removing sorting from TH(C):
- `put_` sorts its indices in THC (but not in TH). I'd expect `put_` and `take` to be implementable using tensor iterators similar to `index_put_` and `index`.
- There is a SparseLinear layer in TH(CU)NN. As far as I can tell, it hasn't been a thing in PyTorch, though, and I would expect that now one would instead use a Linear layer with sparse weights. I'm not sure whether we require SparseLinear and would gladly take advice on whether we want that.

**Comment by t-vi** [comment]
So in the spirit of @ezyang 's [porting guide](https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide) (awesome!), I'd not pile on more changes until you absolutely want me to. (I did put in kthvalue/cuda already, ...)

- SparseLinear is dead for now, so I'm removing it. We would likely use sparse matrices to implement sparse linear.
- I still have sort in THC for the `put_` and `take`. Those would be natural next targets.
- There are further C++ improvements possible, but if I read @ezyang's guide correctly, we actually prefer them in a separate PR.

What do you think?

**Comment by ezyang** [comment]
sgtm.

**Comment by ezyang** [comment]
The current intended plan of action with this PR is that it is split into smaller PRs per operator which we will land individually

**Comment by t-vi** [comment]
So this doesn't actually fly as a large PR.

**Pull request closed without merging**
