### PR TITLE
Fix TBB build

### LINKED ISSUE #76953: Building with `USE_TBB=1 ATEN_THREADING=TBB` fails
### 🐛 Describe the bug

As per title. Building master with `USE_TBB=1 ATEN_THREADING=TBB python setup.py develop/install` fails with multitude compile-time error warnings about dependencies on `native_functions.yaml`:

```
...
/home/nik/git/Quansight/pytorch/build/aten/src/ATen/Functions.h:14:2: error: #error This change adds a dependency on all pytorch operators, meaning the file will need to be 
re-compiled every time an operator is changed or added. Consider including a specific operator from <ATen/ops/{my_operator}.h> and see NOTE [TORCH_ASSERT_ONLY_METHOD_OPERATO
RS].                                                                                                                                                                         
   14 | #error This change adds a dependency on all pytorch operators, meaning the     \                                                                                     
      |  ^~~~~                                                                                                                                                               
In file included from /home/nik/git/Quansight/pytorch/aten/src/ATen/TensorIndexing.h:12,                                                                                                      from /home/nik/git/Quansight/pytorch/aten/src/ATen/ATen.h:20,                                                                                               
                 from /home/nik/git/Quansight/pytorch/aten/src/ATen/ParallelNativeTBB.h:2,                                                                                   
                 from /home/nik/git/Quansight/pytorch/aten/src/ATen/Parallel.h:157,                                                                                          
                 from /home/nik/git/Quansight/pytorch/aten/src/ATen/TensorIterator.cpp:9:                                                                                    
/home/nik/git/Quansight/pytorch/build/aten/src/ATen/NativeFunctions.h:14:2: error: #error This change adds a dependency on all pytorch operators, meaning the file will need 
to be re-compiled every time an operator is changed or added. Consider including a specific operator from <ATen/ops/{my_operator}_native.h> and see NOTE [TORCH_ASSERT_ONLY_M
ETHOD_OPERATORS].                                                                                                                                                            
   14 | #error This change adds a dependency on all pytorch operators, meaning the      \                                                                                    
      |  ^~~~~                                                                                                                                                               
In file included from /home/nik/git/Quansight/pytorch/third_party/tbb/include/tbb/tbb.h:42,                                                                                  
                 from /home/nik/git/Quansight/pytorch/aten/src/ATen/ParallelNativeTBB.h:14,                                                                                  
                 from /home/nik/git/Quansight/pytorch/aten/src/ATen/Parallel.h:157,                                                                                          
                 from /home/nik/git/Quansight/pytorch/aten/src/ATen/TensorIterator.cpp:9:             
...
```

### Versions

Current master.

cc @malfet @seemethere @peterbell10

### PR DESCRIPTION
**Pull request by peterbell10**
Fixes #76953

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Change sounds good.

Do we have any CI that test this?
cc @malfet

**Comment by peterbell10** [comment]
There used to be a TBB build, but it was removed when CI migrated over to GitHub actions.

**Comment by albanD** [comment]
Ok!
We can land this for now. And let's see what @malfet thinks about testing and if we want to make this a periodic test.

**Comment by malfet** [comment]
> There used to be a TBB build, but it was removed when CI migrated over to GitHub actions.

No, it was removed because nobody cared about fixing TBB logic, where `at:get_thread_num` returned a non-contiguous values, see https://github.com/pytorch/pytorch/pull/65092

We can enable the build back, but question is: who needs TBB?

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
