### PR TITLE
make magmaLdlHermitian data_ptr-correct

### PR DESCRIPTION
**Pull request by dagitses**
make magmaLdlHermitian data_ptr-correct

Summary:
See
https://icl.utk.edu/projectsfiles/magma/doxygen/group__magma__hetrf.html#ga470ab07a6d12b662e260eceecf552d26
for a description of which pointer parameters are outputs (all of
them).

Test Plan: Rely on CI.

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/pytorch/pull/99361).
* __->__ #99361
* #99358

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
This PR also touches a few more things than what the title says, but they are all correct, as they follow the creation of auxiliary tensors, so all these tensors must be `out` tensors.

**Comment by dagitses** [comment]
> This PR also touches a few more things than what the title says, but they are all correct, as they follow the creation of auxiliary tensors, so all these tensors must be `out` tensors.

Hey did you look at this PR in github rather than review stack? This should only be a one-line change, it's just that using Sapling SCM doesn't set up the branches so that each PR only sees the related commit.

https://github.com/pytorch/pytorch/pull/99361/commits/e457b0ac3e71252430e0f08a26fb446b88255b4f is the relevant commit for this PR.

**Comment by lezcano** [comment]
Oh wow. Why using sapling rather than ghstack, which shows the correct diffs?

**Comment by dagitses** [comment]
> Oh wow. Why using sapling rather than ghstack, which shows the correct diffs?

there are links to reviewstack, which renders it correctly.

**Comment by lezcano** [comment]
>there are links to reviewstack, which renders it correctly.

I saw, but yeah, why this tool over `ghstack`?

**Comment by dagitses** [comment]
> > there are links to reviewstack, which renders it correctly.
> 
> I saw, but yeah, why this tool over `ghstack`?

It's faster. It has a much better user interface, imo, that is based off of Mercurial. I'm managing a large number of diffs, so the improved UX is very valuable. Most of these diffs are not stacked, and thus don't have these issues.

Also, since I have to make Meta internal changes as well, it's easier to be thinking in Mercurial for each side. And I have the benefit of being able to use hg export and hg import as a pair of operations to export from internal to OSS.

Sapling is very nice. I wouldn't recommend it right now for large stacks in PyTorch right now though since it has some performance problems when rebasing. I'm happy to talk about it more if you're interested.

**Comment by lezcano** [comment]
Thank you for the explanation! I think following the "if it ain't broke, don't fix it", I'll keep using `ghstack` for now, but I'll have a look at sapling, see how it compares :)

**Comment by dagitses** [comment]
> 
I really like it, except for the performance problems. I find that Mercurial has a much more expressive interface than Git for the operations that people actually do. Git is rarely used in an environment where clones are equal: there's usually a repository that is primary (e.g. on Github).

Sapling is mostly the user interface of Mercurial, but it can integrate nicely with Git repositories from Github. It also has a similar set of operations to what you would have with ghstack.

Another nice thing is that it handles submodules natively, no special handling is required for that.

If you do decide to give it a try, and you run into the performance problems, just ctrl-c and `sl rebase --continue` should speed it up, but you may have to do that a few times. Basically, what I have encountered is that long chains seem to have serious performance degradation during rebases, and each subsequent PR is much slower than the previous. But the performance resets if the rebase is stopped and resumed. :shrug:

**Pull request closed without merging**
