### PR TITLE
Release the GIL in serialization when it is safe to do so

### PR DESCRIPTION
**Pull request by albanD**
In particular this ensures we release the GIL when serializing:
- PyBytes objects (this is how we get the pickle object)
- Storage objects

Other string-like objects keep the gil which is fine because we only use this for very small strings today (for endianess) and so releasing the GIL is not important there

### CODE REVIEW

**Review by colesbury — APPROVED** [review]
This looks OK to me.

FWIW, it's okay to use the `const char *` [^1]  for `str` as well as `bytes` after the GIL is released. Both objects are immutable and the `const char *` is valid as long as the original object is kept alive.

I think pybind11 will also happily convert a `bytearray` object to a `const char *`, but it's not well documented. That's not as great because the `bytearray` could possibly be resized while the GIL is released. To be honest, it's not really much worse than `Storage`/`Tensor` where the thread-safety relies on the user not resizing it concurrently with accesses.

As a general comment: if we are using C++17 it's probably better to take a `std::string_view` rather than a `const char *` and `size_t` where the user may pass an invalid size that we don't check, but the current change seems fine to me.

[^1]: i.e., the return value for `PyUnicode_AsUTF8()` or `PyBytes_AsString()`

**Review by albanD — COMMENTED** [review]
:+1:

**Comment by vincent-tr** [comment]
It looks like releasing the GIL in `write_end_of_file` would be important:
it can take a significant amount of time to complete and does not seem to use python objects.

**Pull request closed without merging**
