### PR TITLE
Tensorboard Metrics

### PR DESCRIPTION
**Pull request by nataliakliushkina**
Summary:
Collect metrics about Tensorboard usage
- torch/utils/tensorboard/writer.py

### CODE REVIEW

**Review by dzhulgakov — CHANGES_REQUESTED** [review]
I think it might be a but too granular to be useful (remember, we log only first occurrence). Maybe just put a single call if someone create Tensorboard writer?

If you want to get more of a usage volume numbers - I'd instrument the actual implementation for the logging (e.g. FB internal one)

**Comment by natalialunova** [comment]
> I think it might be a but too granular to be useful (remember, we log only first occurrence). Maybe just put a single call if someone create Tensorboard writer?
> 
> If you want to get more of a usage volume numbers - I'd instrument the actual implementation for the logging (e.g. FB internal one)

Yes, I remember that we log only on first occurrence, it is exactly what we want. When training calls multiple times the `add_scalar`, for us would be enough to see if this visualization type used across our users. This would helpful to make decisions to improve or discard some visualizations.

**Comment by dzhulgakov** [comment]
This logging will work only within FB, not for OSS community (obviously). So information you'd collect won't be representative. Also you can't use this information to remove some visualization - if you added them, they are part of public API and we should support it.

I'm not that strongly opposing it - I just don't think it'd be that useful and instead just would spam both code and the dataset.

**Review by dzhulgakov — APPROVED** [review]

**Pull request closed without merging**
