### PR TITLE
Make RpcTest class re-usable by other RPC backends

### PR DESCRIPTION
**Pull request by xush6528**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#27114 Make RpcTest class re-usable by other RPC backends**

# Problem

Number of splits in test_method_name differs in a test class at a different module import path.

# Solution

Make it general to test classes located at any path.

Differential Revision: [D17074897](https://our.internmc.facebook.com/intern/diff/D17074897/)

### CODE REVIEW

**Review by pritamdamania87 — APPROVED** [review]
Were some tests broken without this change?

**Comment by zhaojuanmao** [comment]
#25656 already changed this

**Comment by zhaojuanmao** [comment]
let us land #25656 first

**Comment by zhaojuanmao** [comment]
@xush6528 thanks for improving this, I'm requesting changes mainly for holding the PR to be landed until #27136 is merged, as @pritamdamania87 and @mrshenli's diffs are blocking by it

**Review by zhaojuanmao — CHANGES_REQUESTED** [review]
holding PR to be landed until #27136 is merged to avoid merge conflict. 

also why it is reopened? which part did not work?

**Comment by xush6528** [comment]
Has problem exporting code. Abandon this one. Move to #27208.

**Pull request closed without merging**
