### PR TITLE
Let set_rng_state and get_rng_state accept string parameter

### PR DESCRIPTION
**Pull request by xuhdev**
Currently set_rng_state and get_rng_state do not accept string as their parameters. This commit let them accept strings.

### CODE REVIEW

**Review by syed-ahmed — APPROVED** [review]
Thanks!  I learnt something new about python :) LGTM.

**Comment by ezyang** [comment]
Waiting on CI

**Comment by SsnL** [comment]
Nice. Another (possibly better) way is to make the default argument the “cuda” string. :)

**Comment by xuhdev** [comment]
> Nice. Another (possibly better) way is to make the default argument the “cuda” string. :)

Good point! I've updated the PR so string is now also accommodated.

**Comment by SsnL** [comment]
Wait I’m actually a little bit confused. torch.device(“cuda”) returns a device object with device index None, I.e., it always refers to the current device. Are you sure that the old default values have problems?

**Comment by xuhdev** [comment]
> Wait I’m actually a little bit confused. torch.device(“cuda”) returns a device object with device index None, I.e., it always refers to the current device. Are you sure that the old default values have problems?

I'm not sure whether it **always** refers to the current device, which is not clearly written in [torch.device doc](https://pytorch.org/docs/master/tensor_attributes.html#torch.torch.device). If it is so, I don't think there will be any issue with the default param and I can edit the message of this PR to "set_rng_state and get_rng_state now accept string param". In either case, I'll also send a PR to clarify this in the doc.

**Comment by SsnL** [comment]
Okay, yeah that sounds good to me. :) You can use this function to get the device index:
https://github.com/pytorch/pytorch/blob/f0ebf769de7dcb7909724f0d6364d55301ee6a79/torch/cuda/_utils.py#L5

**Comment by xuhdev** [comment]
@SsnL Updated!

**Comment by SsnL** [comment]
Can we switch to `_get_device_index` please? :) It will be consistent with all other things and avoid code duplication.

**Comment by xuhdev** [comment]
@SsnL Are you talking about this line `idx = device.index`?

**Pull request closed without merging**
