### PR TITLE
Call super().setUp() and super().tearDown() in torchhub tests

### PR DESCRIPTION
**Pull request by NicolasHug**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #74621

### CODE REVIEW

**Comment by NicolasHug** [comment]
Addresses @janeyx99 's https://github.com/pytorch/pytorch/pull/74427#discussion_r833428416

**Review by vmoens — APPROVED** [review]
LGTM thanks!

**Review by janeyx99 — APPROVED** [review]
thanks!

**Review by cpuhrsch — APPROVED** [review]

**Comment by NicolasHug** [comment]
Thanks for approving @cpuhrsch . Any idea how I can re-trigger the bot?

**Comment by cpuhrsch** [comment]
@NicolasHug - I just ping it again

**Pull request closed without merging**
