### PR TITLE
Add a CUDAContext header include

### PR DESCRIPTION
**Pull request by ezyang**

### CODE REVIEW

**Comment by goldsborough** [comment]
Sorry could you actually put #include <ATen/cuda/CUDAContext.h> in the `torch/csrc/functions/comm.h` (the header)? I think otherwise someone using the data_parallel building WITH_CUDA might not get that header included, since it's also not in ATen/ATen.h so I'm not sure how else it would end up in the include path

**Comment by goldsborough** [comment]
I think this also causing the build failure

**Comment by goldsborough** [comment]
I pushed with potential fix

**Comment by ezyang** [comment]
I don't quite understand why the non-ROCm builds pass without it though :/

**Pull request closed without merging**
