### PR TITLE
[PyTorch] Autoformat aten, round 1

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#57963 [PyTorch] Autoformat aten, round 1**

Opt into formatting on GitHub and format everything. Continuing slow rollout of autoformatting. Includes some missing include fixes, clang-format suppressions in templates and TH, etc.

Differential Revision: [D28329523](https://our.internmc.facebook.com/intern/diff/D28329523/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D28329523/)!

### CODE REVIEW

**Comment by mruberry** [comment]
I know I mentioned this previously but losing the ability to use "blame" on Github is a serious productivity hit, and the value of formatting seems negligible, so I suggest we don't pursue this or, at least, get a group to discuss its pros/cons.

**Review by mruberry — CHANGES_REQUESTED** [review]
Such a significant change that affects the community needs to be socialized first.

**Comment by swolchok** [comment]
>  losing the ability to use "blame" on Github is a serious productivity hit

GitHub has a "view blame prior to this change" button that can be used to bypass this change, as with any other large change.

**Comment by swolchok** [comment]
> the value of formatting seems negligible

It completely ends all worrying and discussion about formatting. You run the tool and you're done, and you don't have to think about whether you've remembered to put braces on the proper line for this repo or whatever.

**Comment by swolchok** [comment]
will reclaim if community comes to a consensus that they want this

**Pull request closed without merging**
