### PR TITLE
Refactor caffe2 CI scripts and add benchmark scripts

### PR DESCRIPTION
**Pull request by bddppq**

### CODE REVIEW

**Comment by petrex** [comment]
quick question, what are the criteria for pass/fail?

**Review by houseroad — APPROVED** [review]
LGTM, I guess it uses the return value as the signal.

**Comment by bddppq** [comment]
cc @orionr I think this will cause some merge conflicts with your WIP PR #13733 
What I have done in this PR is to move those environment variables settings to a "common.sh" script, so that I can source it in both test.sh (and laster bench.sh). In bench.sh we will run resnet50 training to log the perf number. Since it adds ~10mins CI time, I want to run it only on each master commit, not each PR.

**Comment by orionr** [comment]
Thanks for the heads up.

**Pull request closed without merging**
