### PR TITLE
PG NCCL cleanup: remove usage of completed_ in WorkNCCL copies

### PR DESCRIPTION
**Pull request by agolynski**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#59899 PG NCCL cleanup: remove usage of completed_ in WorkNCCL copies**

Differential Revision: [D29080299](https://our.internmc.facebook.com/intern/diff/D29080299)

### CODE REVIEW

**Comment by agolynski** [comment]
@agolynski has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29080299).

**Review by rohan-varma — COMMENTED** [review]
Are these flags unused, or is there a reason that we're removing them (i.e. do we check if it's completed via the associated future now)?

**Comment by agolynski** [comment]
> Are these flags unused, or is there a reason that we're removing them (i.e. do we check if it's completed via the associated future now)?

The reason I am doing the cleanup is merging `PG::Work` functionality into `ivalue::Future` so I am trying to understand and resolve all edge usecases of completed, exception handling and callbacks.

I've discussed with @osalpekar and @jiayisuse that in this particular case: seems like completed_ is being inherited and set, however `WorkNCCL` overrides `ProcessGroup::Work::isCompleted` and we never use wait() on duplicate [copies of WorkNCCL](https://github.com/pytorch/pytorch/blob/3529a48ebb3605b9a0578f1392c0a3bdbf3b207b/torch/lib/c10d/ProcessGroupNCCL.cpp#L226) that live in `workMetaList_`

**Review by cbalioglu — APPROVED** [review]

**Review by osalpekar — APPROVED** [review]
Looks good - ran internal flow to confirm. Thanks @agolynski!

**Pull request closed without merging**
