### PR TITLE
Do not create a ncclUniqueId and bcast it when using ncclCommSplit

### PR DESCRIPTION
**Pull request by nvcastet**
Calling `ncclGetUniqueId(...)` will spawn a new thread and open a new port until the NCCL ID is used. If not used, thread is listening to the port for the lifespan of the application.
For ncclCommSplit code paths, we do not need to provide a ncclUniqueId, therefore we do not need to create one and do not need to broadcast it.
This PR moves the code around to only create an ID when `ncclCommInitRank` is used.
CC @wconstab @kwen2501 @eqy 

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @tianyu-l @chauhang

### CODE REVIEW

**Comment by nvcastet** [comment]
@shuqiangzhang in case you have time to review.

**Review by eqy — APPROVED** [review]
LGTM CC @Aidyn-A

**Review by kwen2501 — APPROVED** [review]
LGTM. Good catch

**Review by Aidyn-A — APPROVED** [review]

**Comment by kwen2501** [comment]
@nvcastet would you like to resolve the conflict and merge? Thanks!

**Comment by nvcastet** [comment]
In fact, someone from Meta already merged the same commit meanwhile: https://github.com/pytorch/pytorch/commit/edbadc904bd8023c9974d636a9a1664636ab9e36 
Closing the PR.

**Pull request closed without merging**
