### PR TITLE
[DCP][state_dict] Let _offload_state_dict_to_cpu to return the companion_obj if it exist.

### PR DESCRIPTION
**Pull request by fegin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #121290
* #121276
* __->__ #121273

As title

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @LucasLLC

### CODE REVIEW

**Review by wz337 — APPROVED** [review]
LG

**Review by LucasLLC — APPROVED** [review]
LGTM

**Pull request closed without merging**
