### PR TITLE
Add return_index for torch.unique_consecutive

### LINKED ISSUE #16330: support `unique_indices` option for `unique`
## 🚀 Feature
Requested by @gkioxari, it would bring `unique` api closer to numpy equivalent. Cuda implementation is not hard, but I haven't looked at CPU. 
May be #15804 scope should be widened to also include this. 
cc @ptrblck, @gkioxari, @jcjohnson

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Partially fixes: https://github.com/pytorch/pytorch/issues/16330
For the `unique_dim_consecutive_cpu` it is not implemented, but will be done after rewriting the CPU implementation of `unique_dim` to resolve performance issue https://github.com/pytorch/pytorch/issues/18987.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin @ngimel Please review. CI seems to be broken, but the test passes on my PC. We can wait for the CI to be fixed before merge.  Again, another merge conflicts with https://github.com/pytorch/pytorch/pull/18649... If possible, maybe first merge step2 and step3, since they has already been reviewed and approved.

**Review by VitalyFedyunin — COMMENTED** [review]
Code looks good. I need to check JIT models BC for this change.

**Comment by nikhilaravi** [comment]
@zasdfgbnm are you still working on this? We really need unique_indices for a project. Thanks!

**Comment by zasdfgbnm** [comment]
@nikhilaravi Yes, I am working on this. I think this is delayed because this has some breaking changes that breaks serialized models, and is waiting until a good solution on that issue is resolved.

**Pull request closed without merging**
