### PR TITLE
[distributions] Apply weaker test for `torch.distributions.wishart.Wishart` to match the level in other libraries.

### PR DESCRIPTION
**Pull request by nonconvexopt**
Follow up PR for #76160
- Removed the tests for the Wishart distribution in the unstable region, `ndim - 1 < df < ndim` to `df ~ ndim + 1`.
- Apply same perturbation for the random variables with Postive Semi-definite constraint equally to the Positive Definite constraint.
- Fix seeds in randomized tests.

cc @neerajprad

### CODE REVIEW

**Comment by neerajprad** [comment]
Thanks for putting this up! 

Could you confirm that we raise a warning for the unstable region? 

Could you also add the fix from https://github.com/pytorch/pytorch/pull/76357, i.e. fix the seed so that the sampler generates the same samples deterministically?

**Comment by nonconvexopt** [comment]
@neerajprad
Sorry for the late response, I got exams in graduate school this week.
> Could you confirm that we raise a warning for the unstable region?

Thanks for pointing out. It is currently raising a warning in every unstable region.

> Could you also add the fix from #76357, i.e. fix the seed so that the sampler generates the same samples deterministically?

I will reflect your suggestion today.

**Comment by nonconvexopt** [comment]
I fixed seeds in all wishart tests, since every test is using torch random functions.

**Review by neerajprad — APPROVED** [review]
Thanks for making the tests deterministic, @nonconvexopt. Looks great.

**Pull request closed without merging**
