### PR TITLE
Disable atomic_add fallback for cpu

### PR DESCRIPTION
**Pull request by oulgen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #113655

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by oulgen** [comment]
I don't have access to a ROCm machine, so relying on CI to test this

**Review by eellison — APPROVED** [review]
Nit: add device to `needs_fallback_due_to_atomic_add_limitations` and fix other callsites too ?

**Comment by oulgen** [comment]
@eellison I actually did earlier that but some tests failed on the other callsite, didn't really investigate though. I can dig into it if you want

**Pull request closed without merging**
