### PR TITLE
Add chunk for jagged layout NT

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #115842
* #116111
* #115192

Nice to have for the [SDPA tutorial](https://pytorch.org/tutorials/intermediate/scaled_dot_product_attention_tutorial.html)

### CODE REVIEW

**Review by soulitzer — APPROVED** [review]

**Comment by kit1980** [comment]
@jbschlosser the tests are now failing with "Unexpected success": https://github.com/pytorch/pytorch/actions/runs/7280323643/job/19838903077

Please update the test expectations.

**Pull request closed without merging**
