### PR TITLE
change default grain size in gather scatter kernel to improve CPU performance

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #64726
* #64479
* __->__ #64478

### CODE REVIEW

**Comment by mingfeima** [comment]
This stack targets at fixing some CPU performance issues on [Reformer](https://huggingface.co/transformers/model_doc/reformer.html).

**Comment by mingfeima** [comment]
`gather` and `scatter` will squash `dim` in TensorIterator, so need to change the default grain size to keep the same granularity.

the patch will not change perf on single core run so only provide single socket result:
#### avx512 single socket
```bash
### before
### using OMP_NUM_THREADS=20
### using numactl --physcpubind=0-19 --membind=0
## gather: dim =  1 , size:  torch.Size([16, 4096, 64]) ; dtype:  torch.float32 ; time = 102.233 ms
## gather: dim =  1 , size:  torch.Size([16, 4096, 64]) ; dtype:  torch.bfloat16 ; time = 87.789 ms

### after
### using OMP_NUM_THREADS=20
### using numactl --physcpubind=0-19 --membind=0
## gather: dim =  1 , size:  torch.Size([16, 4096, 64]) ; dtype:  torch.float32 ; time = 15.057 ms
## gather: dim =  1 , size:  torch.Size([16, 4096, 64]) ; dtype:  torch.bfloat16 ; time = 8.730 ms
```

#### avx2 single socket
```bash
### before
### using OMP_NUM_THREADS=12
## gather: dim =  1 , size:  torch.Size([16, 4096, 64]) ; dtype:  torch.float32 ; time = 106.929 ms
## gather: dim =  1 , size:  torch.Size([16, 4096, 64]) ; dtype:  torch.bfloat16 ; time = 97.344 ms

### after
### using OMP_NUM_THREADS=12
## gather: dim =  1 , size:  torch.Size([16, 4096, 64]) ; dtype:  torch.float32 ; time = 10.844 ms
## gather: dim =  1 , size:  torch.Size([16, 4096, 64]) ; dtype:  torch.bfloat16 ; time = 9.034 ms

**Comment by mingfeima** [comment]
update data on pytorch operator benchmark, the result is collected by:
```bash
python -m pt.gather_test --omp_num_threads 1 --mkl_num_threads 1 --tag_filter long
```

#### avx512 single core

Name | before | after | speed up
-- | -- | -- | --
gather_M128_N128_dim0_cpu | 18.417 | 17.535 | 1.05
gather_M128_N128_dim1_cpu | 19.694 | 19.208 | 1.03
gather_M128_N1024_dim0_cpu | 135.741 | 133.209 | 1.02
gather_M128_N1024_dim1_cpu | 138.203 | 139.077 | 0.99
**gather_M1024_N128_dim0_cpu** | **399.691** | **132.11** | **3.03**
gather_M1024_N128_dim1_cpu | 129.668 | 131.054 | 0.99
gather_M1024_N1024_dim0_cpu | 2700.912 | 2628.933 | 1.03
gather_M1024_N1024_dim1_cpu | 1079.446 | 1084.945 | 0.99

#### avx2 single core

Name | before | after | speed up
-- | -- | -- | --
gather_M128_N128_dim0_cpu | 38.872 | 39.344 | 0.99
gather_M128_N128_dim1_cpu | 30.579 | 28.289 | 1.08
gather_M128_N1024_dim0_cpu | 321.358 | 321.974 | 1.00
gather_M128_N1024_dim1_cpu | 181.769 | 177.849 | 1.02
**gather_M1024_N128_dim0_cpu** | **826.168** | **305.662** | **2.70**
gather_M1024_N128_dim1_cpu | 186.608 | 177.523 | 1.05
gather_M1024_N1024_dim0_cpu | 3095.43 | 2991.722 | 1.03
gather_M1024_N1024_dim1_cpu | 1331.188 | 1402.226 | 0.95


[Note]: For the case `gather_M1024_N128_dim0_cpu`, the original code would have non-contiguous memory access, which is fixed in this PR, so this one receives ~3x speedup. The rest cases behave same as before.

**Comment by mingfeima** [comment]
@VitalyFedyunin could you please help review this one?

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by mingfeima** [comment]
rebased!

**Pull request closed without merging**
