### PR TITLE
bugfix: CUDA - reduce risk of implicit promotions with cmath

### PR DESCRIPTION
**Pull request by Skylion007**
Avoid a couple of missed opportunities to avoid implicit promotions in the CUDA grid sampler op.

### CODE REVIEW

**Comment by ngimel** [comment]
Can you show godbolt generating different code in these cases?

**Comment by Skylion007** [comment]
@ngimel My strategy was just going through here and looking for which functions didn't have a float (or half etc.. overload): https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html#group__CUDA__MATH__SINGLE and replacing that. Major one seems to `::round, ::nearbyint, and fabs`

**Comment by ngimel** [comment]
Sorry, but we actively don't want half overload on this functions, we want intermediate computations to be float whenever possible.

**Comment by Skylion007** [comment]
> Sorry, but we actively don't want half overload on this functions, we want intermediate computations to be float whenever possible.

Agreed, but double intermediate computations are unecessarily wasteful, no?

**Comment by ezyang** [comment]
I agree with @Skylion007 we probably never want to do intermediate compute in double

**Comment by ezyang** [comment]
@ngimel also, don't we not actually had half overloads for the std:: functions anyway? Like you have to use the intrinsics regardless

**Comment by ngimel** [comment]
> I agree with @Skylion007 we probably never want to do intermediate compute in double

Good new we aren't, `::` name resolution does the right thing, e.g. ptx generated for `::fabs` and `std::fabs` is exactly the same, and it's `abs.f32`  https://godbolt.org/z/sj89cs44T

**Pull request closed without merging**
