### PR TITLE
Ensure autocast device_type is a string + Unit test

### LINKED ISSUE #124738: `torch.autocast` produces confusing error message when passing `torch.device`
### 🐛 Describe the bug

When using `torch.autocast`, the device argument does not accept instances of `torch.device` (as expected from the documentation). The fact that it errors is expected, as the documentation states that this is unsupported, but the error message produced is not informative/confusing.

```python
import torch

device = torch.device('cuda') # or 'cpu'

# Note that we should have passed device.type here, so the fact that this errors isn't itself a bug.
with torch.autocast(device_type=device):
    pass
```

This code block will return:

```RuntimeError: User specified an unsupported autocast device_type 'cuda'``` (or `'cpu'` if used above)

which is fairly uninformative/confusing, given that 'cuda' is actually an allowed `device_type`. 

Suggestion: perhaps print the type of the `device_type` if it isn't already a string (or complain about the type instead of the `str` representation)? If needed, I can submit a simple PR to do this.

The error arises from this line which just prints the `str` representation of the passed argument: https://github.com/pytorch/pytorch/blob/47330ca13321a42d4f1e75f091e17183227ae073/torch/amp/autocast_mode.py#L241

### Versions

```
Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.2
[pip3] torch_geometric==2.5.2
[pip3] torchaudio==2.2.2
[pip3] torchvision==0.17.2
[pip3] triton==2.2.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.2.2                    pypi_0    pypi
[conda] torch-geometric           2.5.2                    pypi_0    pypi
[conda] torchaudio                2.2.2                    pypi_0    pypi
[conda] torchvision               0.17.2                   pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi
```

(Note that I didn't include my system details since this is system-invariant, but let me know if you do want those).

cc @svekars @brycebortree @mcarilli @ptrblck @leslie-fang-intel @jgong5

### PR DESCRIPTION
**Pull request by alat-rights**
Reviving #124873 (already approved) to resolve CLA issues 

Fixes #124738

(Marked as draft until I get local unit tests to run)

Edit: Tests passing

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Comment by alat-rights** [comment]
Tests are ok. Publishing PR.

Sorry for the CLA trouble.

image

**Comment by alat-rights** [comment]
@soulitzer If you could take a look :)

**Review by mikaylagawarecki — APPROVED** [review]
Thanks!

**Comment by alat-rights** [comment]
I ran `lintrunner -a` locally to fix lint failure, and then pushed a new commit.

Hopefully all is good now.

Sorry about that!

**Review by soulitzer — APPROVED** [review]

**Pull request closed without merging**
