### PR TITLE
Re-disable softmax ops tests in ROCM

### PR DESCRIPTION
**Pull request by bddppq**
They are flaky in master.

@ashishfarmer @petrex 

#12727

### CODE REVIEW

**Review by houseroad — APPROVED** [review]
LG

**Comment by petrex** [comment]
we will look into this test again

**Comment by bddppq** [comment]
@petrex @ashishfarmer Any progress on the softmax tests investigation?

**Comment by ashishfarmer** [comment]
@bddppq, We are looking at all the skipped tests and and getting to the root of all. Will have a PR soon with the changes and enabled tests, and that would include Softmax fixes

**Comment by bddppq** [comment]
@ashishfarmer that's great!

**Comment by bddppq** [comment]
@petrex @ashishfarmer looks like #15069 has run into the similar softmax issue.

**Pull request closed without merging**
