### PR TITLE
adding opinfo for torch.nn.bilinear and torch.nn.glu

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #67478

Differential Revision: [D32027807](https://our.internmc.facebook.com/intern/diff/D32027807)

### CODE REVIEW

**Review by mruberry — COMMENTED** [review]
Looks really good @mikaylagawarecki, just need to resolve the CUDA bfloat16 support (see inline comment for a couple suggestions)

**Comment by mikaylagawarecki** [comment]
@mikaylagawarecki has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32027807).

**Comment by mikaylagawarecki** [comment]
@mikaylagawarecki has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32027807).

**Review by mruberry — APPROVED** [review]
Tests look good now!

Thanks @mikaylagawarecki!

**Comment by mikaylagawarecki** [comment]
@mikaylagawarecki has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32027807).

**Pull request closed without merging**
