### PR TITLE
add testcase for kineto on-demand profiling, check #131020

### PR DESCRIPTION
**Pull request by staugust**
This test script checks #131020  to ensure that kineto on-demand profiling will not abort torch process.

### CODE REVIEW

**Comment by staugust** [comment]
@sraikund16 hi, please take a look at this commit, thanks

**Comment by sraikund16** [comment]
Can we move this to test/profiler/ instead?

Otherwise seems reasonable to me. cc @briancoutinho

**Comment by staugust** [comment]
Ok, this test file is moved under `test/profiler`. By the way, I'm also improved this pr with some naming and comments updates.

**Comment by staugust** [comment]
@aaronenyeshi  please take a look at this pr, thanks. By the way, CLA manager in my organization told me he had already signed my request, but I didn't receive any email related to cla, and this page still shows  EASYCLA not covered,  could you please check my cla status?

**Comment by aaronenyeshi** [comment]
try checking again with /easycla

**Review by aaronenyeshi — APPROVED** [review]
LGTM

**Review by sraikund16 — APPROVED** [review]

**Comment by staugust** [comment]
@briancoutinho   would you please take a few minutes to review this pr?

**Comment by briancoutinho** [comment]
lgtm :)

**Review by briancoutinho — APPROVED** [review]

**Comment by staugust** [comment]
@briancoutinho  Thanks, I checked the failed checks, and they are all due to the new test cases I added, which need to be merged along with the PR #131448 . And I've added the test cases in that pr as well.

**Comment by staugust** [comment]
Close this pr as #131448  is merged into main branch.

**Comment by staugust** [comment]
Close this pr as #131448 is merged into main branch.

**Pull request closed without merging**
