### PR TITLE
Upload failures shouldn't fail a CI that passed tests

### PR DESCRIPTION
**Pull request by ZainRizvi**
This'll reduce some flakiness we've been seeing recently

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Hmm, I'm not sure that `continue-on-error:` will change the overall workflow status from false to true? Mind writing a workflow in pet repo to test this theory?

**Comment by kit1980** [comment]
> Hmm, I'm not sure that `continue-on-error:` will change the overall workflow status from false to true? Mind writing a workflow in pet repo to test this theory?

GitHub docs say "allow a workflow run to pass when this job fail" - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error

**Review by kit1980 — APPROVED** [review]

**Comment by ZainRizvi** [comment]
Yup, and here's proof:
https://github.com/ZainRizvi/workflow-test/actions/runs/4009209172

Same workflow failing without the continue-on-error:
https://github.com/ZainRizvi/workflow-test/actions/runs/4009188344

**Pull request closed without merging**
