### PR TITLE
Fix side effect pruning

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128028

Summary:
The previous side effect pruning algorithm would keep many dead cell
variables alive. For example, in
https://github.com/pytorch/pytorch/issues/125078, the compiled function
has one return but there were three in the Dynamo graph due to two
dead cell variables not being pruned away.

This PR adds a corrected algorithm. "new cell variables" are alive if
they can be reached from one of the following:
1. any of the tx.symbolic_locals or tx.stack (that is, if they are
   involved in a return from the function or intermediate variable
   during a graph break). Example: an alive NestedUserFunctionVariable
2. "mutations to pre-existing objects". Example: appending a
   NestedUserFunctionVariable to a global list

The new algorithm reflects this, but please let me know if there are
more cases to handle.

Test Plan:
- existing tests (afaict, test/dynamo/test_python_autograd is the best
  SideEffects test case we have)
- see in test/dynamo/test_higher_order_ops that the expecttests changed
  -- the functorch dynamo graphs no longer return dead cellvars.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
@zou3519, this PR and https://github.com/pytorch/pytorch/pull/127998 fixes non-live variables being returned in the FX graph (#125078 and #127350)

Reproducers:

```python
import torch


@torch.compile(backend="aot_eager", fullgraph=True)
def f(x):
    y = x.clone()
    def g():
        return y + 1
    return g()


g = f(torch.randn(4))

# class GraphModule(torch.nn.Module):
#    def forward(self, L_x_: "f32[4]"):
#        l_x_ = L_x_
#        # File: /home/guilhermeleobas/git/pytorch/d.py:6 in f, code: y = x.clone()
#        y: "f32[4]" = l_x_.clone();  l_x_ = None
#        # File: /home/guilhermeleobas/git/pytorch/d.py:8 in g, code: return y + 1
#        add: "f32[4]" = y + 1;  y = None
#        return (add,)
```

```python

import torch
from torch._functorch.eager_transforms import grad_increment_nesting
from torch._C._functorch import _wrap_for_grad

@torch.compile(backend='eager')
def f(x):

    with grad_increment_nesting() as level:
        y = _wrap_for_grad(x, level)

    def g():
        z = y + 1
        return z

    return x.sin()

x = torch.randn(3, 4)
f(x)

# class GraphModule(torch.nn.Module):
#    def forward(self, L_x_: "f32[3, 4]"):
#        l_x_ = L_x_

#        # No stacktrace found for following nodes
#        _grad_increment_nesting = torch._C._functorch._grad_increment_nesting()

#        # File: /home/guilhermeleobas/git/pytorch/d.py:23 in f, code: y = _wrap_for_grad(x, level)
#        y = torch._C._functorch._wrap_for_grad(l_x_, 1)

#        # No stacktrace found for following nodes
#        _grad_decrement_nesting = torch._C._functorch._grad_decrement_nesting()

#        # File: /home/guilhermeleobas/git/pytorch/d.py:29 in f, code: return x.sin()
#        sin: "f32[3, 4]" = l_x_.sin();  l_x_ = None
#        return (sin,)


```

**Review by jansel — APPROVED** [review]

**Comment by zou3519** [comment]
Internal signals over at D58292725

**Pull request closed without merging**
