### PR TITLE
[NNC] Handle non literal constant bounds in Unroll.

### LINKED ISSUE #53000: [nnc] unroll/flatten loops with non literal constant bounds
Currently we require a literal constant, but fail on something like (16/4) which is trivially simplified. 

cc @gmagogsfm

### PR DESCRIPTION
**Pull request by navahgar**
Fixes #53000

Also added test to confirm this case works in FlattenLoop as well.

### CODE REVIEW

**Comment by ZolotukhinM** [comment]
I think that if we're gonna simplify something, we should simplify the entire loop, and not just its start/stop expressions. But if we do this, then I'd slightly prefer doing that after the transformation, since we know that we could've generated some simplifiable things (like `16/4` after splits). Does it sound reasonable?

**Comment by navahgar** [comment]
> I think that if we're gonna simplify something, we should simplify the entire loop, and not just its start/stop expressions. But if we do this, then I'd slightly prefer doing that after the transformation, since we know that we could've generated some simplifiable things (like `16/4` after splits). Does it sound reasonable?

We are already simplifying the entire unrolled loop at the end (https://github.com/pytorch/pytorch/pull/53029/files#diff-3b16fb1739ad09132270e2d1df2d17128afbc92df5cbfb1703c343c74ce5cfbfR1484). Simplifying the entire loop at the start seems unnecessary since we might be introducing simplifiable expressions during the transformation. At the start, we only have to simplify start and stop expressions here for this transformation to handle all cases.

**Comment by ZolotukhinM** [comment]
That means that in some other transformation we don't simplify (otherwise, where would these non-simplified bounds come from?), and maybe a better fix would be to simplify there? Otherwise, we'll keep whack-a-moling other transformations inserting `simplify` calls in their beginning.

**Comment by navahgar** [comment]
Sure, that is possible. But it won't work for tests though. Also, if @bertmaher was calling `Flatten` from one of his hand-written c++ benchmarks, that wouldn't work either. I'm not sure what use case led Bert to this issue.

**Comment by navahgar** [comment]
> > ...was calling Flatten from one of his hand-written c++ benchmarks
> 
> Why wouldn't it work if `Flatten` simplified in the end?

I was actually referring to `Unroll`, which I am fixing in this PR. Sorry for the confusion.

A hand-written benchmark is similar to tests. We could generate a Loop and call unroll on it directly. In this case, there is no way simplify could be run before unroll because there were no other transformations before this (unless, of course, we explicitly call simplify). So, the start and stop expressions could fail the constant test, if we don't simplify here.

**Comment by ZolotukhinM** [comment]
Ah, I see your point. But I don't think @bertmaher intentionally wrote `16/4` there - this does look like a product of some of our transformations. If someone really wants to write something like that, I'd say it's reasonable to expect them to also run `Loopnest::simplify` on that before applying other transforms.

It similar to how compilers usually have optimizations like dead-code elimination and constant propagation, but calling them is often not a responsibility of every transformation.

This helps to have some consistency in transformations: we need to either agree to always simplify the incoming stmt (and then don't bother simplifying the output), or we expect input to be simplified and make sure that the output is also simplified. Simplifying both in the beginning and at the end seems like an overkill. And currently I think we've so far tried to simplify at the end, hence my original suggestion.

**Comment by navahgar** [comment]
Good point regarding Bert's example. @bertmaher can you clarify what was your workflow that lead to this issue? Specifically, what was the transformation you were running prior to `unroll` which caused this issue?

While I agree with everything you say, I'm not sure if our codebase is mature enough to warrant such clear points at which we apply `simplify`. I already see a few places like `splitWithMask` which is also doing something similar: (https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/tensorexpr/loopnest.cpp#L1269).

**Comment by ZolotukhinM** [comment]
> While I agree with everything you say, I'm not sure if our codebase is mature enough to warrant such clear points at which we apply simplify. 

This seems like a good opportunity to make it more mature :) Unless we start being disciplined and start introducing and enforcing invariants, it will not happen by itself

**Comment by navahgar** [comment]
I started applying `simplify` after all transformations and just realized that is not straightforward to do. One issue is that a lot of our APIs return `For*` and the result of `simplify` may not be a `For` (if say it has only one iteration to begin with). We might have to change the APIs in order to do it for all our transforms. 

If Bert's use-case has a particular transform before calling `unroll`, that is causing this issue, we can look at fixing that to begin with.

**Comment by ZolotukhinM** [comment]
That's a good point, which is probably related to the long-standing issue of invalidating stmts by different transforms. E.g. if we split by 1 and simplify in the resultant stmt, the split would produce no new loops. If we don't simplify, it would produce an extra loop.
We do not have an obvious plan how we're gonna fix that everywhere yet, so maybe it's ok to land a solution that you proposed earlier for now.

**Comment by bertmaher** [comment]
I don't have the example in a nice reproducible form right now, but what I tried to do was basically:
- take a loop with trip count 32
- split by 16
- vectorize
- unroll

The split by 16 causes the bounds of the outer loop to be `(((32 - 0) + 16) - 1) / 16`

**Comment by navahgar** [comment]
> We do not have an obvious plan how we're gonna fix that everywhere yet, so maybe it's ok to land a solution that you proposed earlier for now. So, what would be you current plan?

Ideally, our compiler flow should look like this:
```
  <transform1>
  <simplify>
  <transform2>
  <simplify>
  ...
```
In this way, we call simplify only on the whole `Stmt` and get around the problem of having `For*` in APIs AFAICT. What do you think?

**Comment by navahgar** [comment]
As per Bert's flow, `vectorize` was the one that was called before `unroll`. That is one clear case where we can `simplify` at the end of the transform, without any trouble. I will add that.

Since we don't have the ideal workflow yet, I am going to keep the `simplify` on `start` and `stop` during `unroll`, as I proposed initially.

**Review by ZolotukhinM — APPROVED** [review]
Looks good!

**Pull request closed without merging**
