### PR TITLE
Update nccl to v2.5.6-1

### PR DESCRIPTION
**Pull request by pietern**

### CODE REVIEW

**Comment by pietern** [comment]
Bumping because NCCL was updated. Didn't test myself yet.

**Review by mrshenli — APPROVED** [review]

**Review by mrshenli — CHANGES_REQUESTED** [review]
Test error looks relevant:

```
Nov 20 16:03:25 RuntimeError: NCCL error in: /var/lib/jenkins/workspace/torch/lib/c10d/ProcessGroupNCCL.cpp:404, unhandled system error, NCCL version 2.5.6
Nov 20 16:04:11 ======================================================================
Nov 20 16:04:11 FAIL [2.643s]: test_backend_full_group (__main__.TestDistBackend)
Nov 20 16:04:11 ----------------------------------------------------------------------
Nov 20 16:04:11 Traceback (most recent call last):
Nov 20 16:04:11   File "test_distributed.py", line 2021, in wrapper
Nov 20 16:04:11     self._join_and_reduce(fn)
Nov 20 16:04:11   File "test_distributed.py", line 2129, in _join_and_reduce
Nov 20 16:04:11     first_process.exitcode == SKIP_IF_SMALL_WORLDSIZE_EXIT_CODE
Nov 20 16:04:11 AssertionError
```

**Comment by pietern** [comment]
Indeed it does... this will require some manual debugging...

**Comment by mrshenli** [comment]
closing this PR as we are already at 2.7.8

**Pull request closed without merging**
