### PR TITLE
Update CMake minimum version to 3.10

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #62550
* #62445
* __->__ #63660

Differential Revision: [](https://our.internmc.facebook.com/intern/diff/)

Differential Revision: [D30543878](https://our.internmc.facebook.com/intern/diff/D30543878)

cc @malfet @seemethere @walterddr

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
LGTM, @ezyang any objections on your end?

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/).

**Comment by ezyang** [comment]
IIRC the main question is if the most recent LTS Ubuntu ships with cmake 3.10... does it?

**Comment by peterbell10** [comment]
The most recent LTS is 20.04, and this command shows CMake `3.16.3` is on `apt`.
```sh
docker run -it ubuntu:20.04 sh -c "apt-get update -y && apt-get install cmake -y && cmake --version"
```

Running the same command with 18.04 install CMake `3.10.2` so we even support the previous LTS release.

**Comment by ezyang** [comment]
Then we're good to go! :)

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30543878).

**Comment by zhouzhuojie** [comment]
Is this change comprehensive to include all the cmake in the codebase? e.g. one I can find is here https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/tbb/CMakeLists.txt#L4

**Pull request closed without merging**
