### PR TITLE
[BE][Eazy] remove `torch.torch.xxx` usages

### PR DESCRIPTION
**Pull request by XuehaiPan**
NB: `torch` is exposed in `torch/__init__.py`. So there can be `torch.torch.torch.xxx`.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by XuehaiPan** [comment]
Maybe add this to `torchfix`. cc @kit1980

**Review by peterbell10 — APPROVED** [review]

**Comment by kit1980** [comment]
Any valid possible usage for `torch.torch`?

> So there can be torch.torch.torch.xxx

:-D

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
Adding even more `torch` works:

```
In [8]: torch.torch.torch.torch.torch.torch.rand(2)
Out[8]: tensor([0.3231, 0.7063])
```

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
