### PR TITLE
[ROCm] define C10_WARP_SIZE to warpSize HIP constant

### PR DESCRIPTION
**Pull request by jeffdaily**
warpSize is defined as a constexpr in HIP headers.  It is incorrect to assume warpSize 64.  This change fixes the C10_WARP_SIZE definition in torch sources similar to [how it was done in caffe2](https://github.com/pytorch/pytorch/blob/master/caffe2/utils/GpuDefs.cuh#L10-L14).

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### CODE REVIEW

**Comment by jeffdaily** [comment]
#64287 was wrong.  This should be the right fix.

**Review by jithunnair-amd — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@malfet Can we please merge this?

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@jithunnair-amd if it will pass build using older version of ROCm (used for internal builds), than yes, LGTM

**Comment by jithunnair-amd** [comment]
@malfet Yes, it should work with older ROCm versions, although, as requested earlier, please let us know the ROCm version being used in internal builds so that we can assess whether any future changes will be compatible with the ROCm version used in internal builds.

**Pull request closed without merging**
