### PR TITLE
Added functionality for all to take Lists as input

### PR DESCRIPTION
**Pull request by ghost**
New pull request after rebase error in pull request #33923

### CODE REVIEW

**Comment by michaelarg** [comment]
Hi @eellison I made an error in my rebase on the previous pull request so closed it off and the fix is now here.

**Review by eellison — APPROVED** [review]
Looks good! previous review in https://github.com/pytorch/pytorch/pull/34520

**Comment by ezyang** [comment]
This broke lint.

**Comment by eellison** [comment]
@ezyang on the HUD the flake run isn't viewable 

https://github.com/pytorch/pytorch/runs/517390966/console

**Comment by mruberry** [comment]
{
    path: 'test/test_jit.py',
    start_line: 8424,
    end_line: 8424,
    start_column: 33,
    end_column: 33,
    annotation_level: 'failure',
    message: '[E999] SyntaxError: invalid syntax'
  }

https://github.com/pytorch/pytorch/blob/1afc5841888ba324a533dde98ba94af637dac512/test/test_jit.py#L8424

**Comment by michaelarg** [comment]
Why does the bot close the branch?

**Comment by michaelarg** [comment]
@eellison, where I am best to change the type hints in the test_jit.py file throwing up the lint errors, in a new pull request as this one has been closed?

**Pull request closed without merging**
