### PR TITLE
[ONNX] Create lint workflow for ONNX exporter

### PR DESCRIPTION
**Pull request by justinchuby**
Create lint workflow for ONNX exporter for additional stricter Python formatting and style checks.

Linters enabled are

- black formatting
- isort
- misspell
- markdownlint
- cpplint

Lintrunner does not report flake8 annotations inline (only mypy). So we are running flake8 as well.

The checks run in a workflow independent of the lintrunner workflow. They are non-blocking. Annotations will display inline in the PR if there are any findings.

Demo: #76317

### CODE REVIEW

**Comment by seemethere** [comment]
cc @osalpekar

**Review by suo — CHANGES_REQUESTED** [review]
I recommend that we use lintrunner for this. The goal of consolidating linters was to reduce fragmentation of our linters so that PyTorch devs didn't have to worry about X special rule in Y folder—they just had to run a single command. Introducing a separate workflow just for a the ONNX module would regress that.

Happy to review or help out with changes to write the necessary lintrunner adapters. I know it's extra work which sucks but I feel that the consistency provides value to the overall project.

> The checks run in a workflow independent of the lintrunner workflow. They are non-blocking.

Our overall policy is to revert if any workflow fails on master. People would have to know that this workflow is special and does not run on master, unlike all our other workflows, which doesn't seem clear from the signal provided at PR time.

> Lintrunner does not report flake8 annotations inline (only mypy).

This is surprising to me, do you have an example? All annotations come in exactly the same format and are rendered the same way, so it's a bug if flake8 isn't working.

**Comment by suo** [comment]
Just as a concrete example of consistency being important—this workflow will run on any PR that touches the files in the pull_request trigger, but it's not clear to me that the *linters* will only run on those files. So, if you did a codemod or just touched a general file like `torch/_C/__init__.pyi.in`, would the linter run on all your other python/cpp changes in the PR and generate a lot of errors? How is the user supposed to know that they can ignore all that and land anyway?

**Comment by justinchuby** [comment]
@suo Thanks for commenting - that makes a lot of sense! I am happy to consolidate the checks into lintrunner. I would appreciate some help getting started.

A few questions:

1. We are looking to use black as the Python formatter (given that there is none stipulated in the project). It is more realistic (I think?) to enforce in a smaller scope (onnx). One option is to configure black to only check (and fail) on the onnx paths. Is this what you see should be path forward?
2. Does lint runner support reporting annotations as warnings? (Somethings should not fail the checks but are good to have as annotations for reviewers. E.g. misspell, markdownlint)
3. What linters do you think should / should not be included?

As an example of the linting findings not reported, please see https://github.com/pytorch/pytorch/pull/76317/files `torch/onnx/utils.py`, `torch/csrc/jit/passes/onnx/helper.h`

In utils.py we see mypy errors, but not flake8 errors reported by lintrunner. Lintrunner did produced logs w/ flake8 messages, but they were not surfaced as annotations. `torch/csrc/jit/passes/onnx/helper.h` shows additional findings by cpplint that should (?) be reported by clangtidy.

**Comment by suo** [comment]
Yeah, honestly I'm happy to implement some of the adapters for you and try to use that process as an opportunity to actually document the process of writing one to make it easier for others.

> 1. We are looking to use black as the Python formatter (given that there is none stipulated in the project). It is more realistic (I think?) to enforce in a smaller scope (onnx). One option is to configure black to only check (and fail) on the onnx paths. Is this what you see should be path forward?

Yeah makes sense to scope the files checked to something more manageable. This is configurable on a per-linter basis ([see](https://github.com/pytorch/pytorch/blob/master/.lintrunner.toml)). I think @ezyang recently black-formatted torchgen (nee tools/codegen) so we can include that as well.

> 2. Does lint runner support reporting annotations as warnings? 

Not today, everything is an error. I sort of think that's nice for keeping things lint-clean, but could be convinced otherwise.

> 3. What linters do you think should / should not be included?

All seem fine—the only two I would cast a skeptical eye on are cpplint (enforces Google code style, which we do not use for PyTorch) and misspell (which feels like overkill to me personally).

Also: thank you for the example where flake8 annotations weren't working! Looks like it's indeed a bug; I'll put up a fix soon

**Comment by ezyang** [comment]
I guess I need to actually finish my black linter adapter lol

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/76352

**Comment by ezyang** [comment]
honestly the process is fine, the annoying thing is all the copy pasting

**Pull request closed without merging**
