### PR TITLE
[Easy][FSDP] Add `zero_grad()` to unit test train loop

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #81243 [FSDP] Move `_post_backward_called` to `_init_param_attributes`
* #80185 [FSDP] Clean up `_lazy_init()`
* **#80087 [Easy][FSDP] Add `zero_grad()` to unit test train loop**
* #80002 [FSDP] Remove `self.numel_padded_per_param` (unused)
* #80000 [FSDP] Move tensor sharding logic to `FlatParamHandle`
* #79984 [FSDP] Deduplicate `_orig_size` and `_unsharded_size`
* #79652 [FSDP] Introduce `FlatParamHandle`

I wanted to add in a `zero_grad()` call into the train step for `test_fsdp_optim_state.py` to make it more reflective of normal use cases instead of exercising gradient accumulation.

Differential Revision: [D37726058](https://our.internmc.facebook.com/intern/diff/D37726058)

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
LGTM, thanks!

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37726058).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37726058).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37726058).

**Pull request closed without merging**
