### PR TITLE
Add missing cstdint includes

### PR DESCRIPTION
**Pull request by omarhogni**

### CODE REVIEW

**Comment by Skylion007** [comment]
You need to sign the CLA.

**Comment by omarhogni** [comment]
@Skylion007 it should be done.

**Comment by Skylion007** [comment]
Could you try to keep the includes sorted as well?

**Review by albanD — COMMENTED** [review]
@Skylion007 is our lint not opinionated enough to enforce a single valid ordering of the includes?

**Comment by Skylion007** [comment]
@albanD clang-format is, but I guess it hasn't been enabled on these files.

**Comment by omarhogni** [comment]
@Skylion007 The includes have been sorted.

**Review by Skylion007 — APPROVED** [review]

**Comment by malfet** [comment]
It would be nice to have a more detailed description of what is being fixed (or what was broken) by adding those includes

**Comment by BillyONeal** [comment]
> It would be nice to have a more detailed description of what is being fixed (or what was broken) by adding those includes

It was a build failure: https://github.com/microsoft/vcpkg/issues/35707

For instance:

```
/opt/vcpkg/buildtrees/libtorch/src/v1.12.1-e1cb316ec6.clean/c10/util/BFloat16.h:17:44: error: ‘uint16_t’ was not declared in this scope
   17 | inline C10_HOST_DEVICE float f32_from_bits(uint16_t src) {
      |                                            ^~~~~~~~
```

**Pull request closed without merging**
