### PR TITLE
[LTC] Refine MetricsArena::Reset

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
After counters are reset, getters' behaviors are inconsistent. To improve that, here I 1) move the validation of CounterData into CounterData::IsValid such that it's better encapsulated, 2) divide getters into two groups: a) MetricsArena::GetCounter() and b) MetricsArena::ForEachCounter(), and route MetricsArena::GetCounterNames() and CreateMetricReport() to use b.

This is paired with pytorch/xla#4217.

Test Plan:
PJRT_DEVICE=CPU python xla/test/test_metrics.py

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Comment by alanwaketan** [comment]
Thanks Jack for approving.

**Pull request closed without merging**
