### PR TITLE
[DDP] Fix broadcast for channels-last tensors

### PR DESCRIPTION
**Pull request by eqy**
#79043

CC @pritamdamania87 @ptrblck

### CODE REVIEW

**Comment by pritamdamania87** [comment]
@eqy Thanks for fixing this! Can we also add unit tests that reproduced the original failure so that there is test coverage for this in the future?

**Comment by pritamdamania87** [comment]
@eqy Also, let me know if you are comfortable also making a patch for our 1.12 release branch: https://github.com/pytorch/pytorch/issues/78005, once this PR lands. If not, I'm happy to make a patch for 1.12 release and request a cherry-pick :)

**Comment by eqy** [comment]
> @eqy Also, let me know if you are comfortable also making a patch for our 1.12 release branch: #78005, once this PR lands. If not, I'm happy to make a patch for 1.12 release and request a cherry-pick :)

Added test and patch is here: https://github.com/pytorch/pytorch/pull/79071/files

**Review by pritamdamania87 — APPROVED** [review]

**Comment by pritamdamania87** [comment]
@eqy Thanks again for the fix! Can you also add a comment to this issue (similar to other ones): https://github.com/pytorch/pytorch/issues/78005, so that this bugfix is picked up in the 1.12 release?

**Pull request closed without merging**
