### PR TITLE
[Traceable FSDP2] Add auto-functionalize support for mutable list[Tensor] (copy from Brian's PR #127347); enable E2E inductor unit test for transformer model

### PR DESCRIPTION
**Pull request by yf225**
Copy of Brian's PR: https://github.com/pytorch/pytorch/pull/127347 with additional changes to support mutable `List[Tensor]` in Inductor. Also enable E2E inductor unit test for Traceable FSDP2 + transformer model.

Test commands:
- `pytest -rA test/distributed/_composable/fsdp/test_fully_shard_compile.py::TestFullyShardCompile::test_trace_fsdp_set_`
- `pytest -rA test/distributed/_composable/fsdp/test_fully_shard_compile.py::TestFullyShardCompile::test_simple_mlp_fullgraph_backend_aot_eager`
- `pytest -rA test/distributed/_composable/fsdp/test_fully_shard_compile.py::TestFullyShardCompile::test_simple_mlp_fullgraph_backend_inductor`
- `pytest -rA test/distributed/_composable/fsdp/test_fully_shard_compile.py::TestFullyShardCompile::test_transformer_fullgraph_backend_aot_eager`
- `pytest -rA test/dynamo/test_misc.py::MiscTests::test_auto_functionalize_tensorlist`
- `pytest -rA  test/inductor/test_torchinductor.py::GPUTests::test_fallback_mutable_op_list_cuda`

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #129611
* #127247
* __->__ #129502

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @chauhang @d4l3k @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Comment by yf225** [comment]
Ok, we found that we can't actually functionalize `fsdp.split_with_sizes_copy` without also functionalizing `fsdp.set_`, and we already know we can't functionalize the latter because we want to avoid AOTAutograd input dedup struggle. So we prefer to also defunctionalize `fsdp.split_with_sizes_copy` instead.

**Comment by yf225** [comment]
Closing in favor of https://github.com/pytorch/pytorch/pull/129422

**Comment by yf225** [comment]
CI shows error in `test_ci_sanity_check_fail.py::TestCISanityCheck::test_env_vars_exist` [macos-py3-arm64 / test (default, 1, 3, macos-m1-stable)](https://github.com/pytorch/pytorch/actions/runs/9690691791/job/26741619874#logs), which I don't believe is related to this PR. I will proceed to land this PR.

**Pull request closed without merging**
