### PR TITLE
Serialize pytree to string

### PR DESCRIPTION
**Pull request by angelayi**
* list --> `L(value1,value2)`
* tuple --> `T(value1,value2)`
* dict --> `D(key1:value1,key2:value2)`
* ordered dict --> `O(key1:value1,key2:value2)`
* namedtuple --> `N(type(key1, key2),value1,value2)`
* leaf --> `*`

Restrictions
* serializing custom types is not supported
* we only support serializing string keys in dictionaries

### CODE REVIEW

**Comment by zhxchen17** [comment]
Why we chose word "type" for N(type(key1, key2),value1,value2)?

**Comment by angelayi** [comment]
> Why we chose word "type" for N(type(key1, key2),value1,value2)?

what's a better word.. 😅

**Comment by zhxchen17** [comment]
> 

Maybe `N(key1=value1, key2=value2, ...)` ?

**Comment by zhxchen17** [comment]
wrong button pressed sorry lol

**Comment by zhxchen17** [comment]
> > Why we chose word "type" for N(type(key1, key2),value1,value2)?
> 
> what's a better word.. 😅

sorry I think I misunderstood. feel free to ignore my previous comment

**Review by avikchaudhuri — APPROVED** [review]
Why not include dataclass support as well, while we're at it? Better than `NamedTuple`.

Do we really need both dict and OrderedDict? Why?

**Comment by angelayi** [comment]
> Why not include dataclass support as well, while we're at it? Better than NamedTuple. Do we really need both dict and OrderedDict? Why?

dataclass isn't pytree-ed right now. I'm just choosing what to pytree based on the exising default types that are pytree-ed.


updates to https://github.com/pytorch/pytorch/pull/102708

**Comment by ezyang** [comment]
Is there any design doc about why we picked this particular format for string serialization (and also why we hand-rolled a string parser?) Single letter signifiers means that downstream pytree implementers are significantly at risk of collisions (you can only support 26 distinct types under this parsing scheme). Additionally, lack of quoting means that dictionary keys with colons can confuse the parser. It almost nearly would have been better to just use JSON instead...

**Pull request closed without merging**
