### PR TITLE
Revert "Stable sort for CPU (#50052)"

### PR DESCRIPTION
**Pull request by glaringlee**
This reverts commit c99f35605105f7366bcf4709df534da3ceab9a15.

### CODE REVIEW

**Comment by glaringlee** [comment]
@JackCaoG 
Hi, I am going to revert this change since it breaks fb internal model integration tests. Can you help to revert the xla change on your side if needed. We will land this code later.

**Review by zou3519 — APPROVED** [review]

**Comment by JackCaoG** [comment]
> @JackCaoG
> Hi, I am going to revert this change since it breaks fb internal model integration tests. Can you help to revert the xla change on your side if needed. We will land this code later.

yea, I will revert too

**Comment by glaringlee** [comment]
@nikitaved I probably need to revert this code today since it breaks our fb internal tests. I will try to put a fix, but if it doesn't work, I will revert the entire stable sort code

**Comment by glaringlee** [comment]
> > @JackCaoG
> > Hi, I am going to revert this change since it breaks fb internal model integration tests. Can you help to revert the xla change on your side if needed. We will land this code later.
> 
> yea, I will revert too

I will try to fix it in next 2 hours, will let you know.

**Comment by glaringlee** [comment]
@JackCaoG 
We start to revert this. Please revert the xla change once this pr is closed.
@nikitaved I am working on a fix, can you reopen a PR so we can add the fix in once I verify the fix works for all the cases? Thanks a lot.

**Pull request closed without merging**
