### PR TITLE
Renaming the relu kernel and adding hypothesis tests

### PR DESCRIPTION
**Pull request by z-a-f**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #20474 Quantized Max Pool op&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D15327923/)
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#20647 Renaming the relu kernel and adding hypothesis tests**&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D15332106/)

The initial assumption was that `qint8` would be unsigned. After introduction of `quint8` and `qint8`, some tests break.

Differential Revision: [D15332106](https://our.internmc.facebook.com/intern/diff/D15332106/)

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]

**Review by soumith — CHANGES_REQUESTED** [review]
adding new files is expensive, mentally.

would it make sense to push the code in hypothesis_utils.py into common_utils.py ?

**Comment by zafartahirov** [comment]
@soumith I could place all that in the `common_utils.py`. But won't the file be bloated? Besides, I would think (hope) that all tests would eventually migrate to hypothesis 😄. If you think that would be better, I will move the stuff in the `common_utils.py`

**Comment by soumith** [comment]
maybe we can refactor it after it feels like it's getting bloated. anyways, just a thought, dont want to bikeshed too much, you can dismiss my review in the UI

**Comment by zafartahirov** [comment]
I agree with you on the future refactoring -- that was initially on my mind. I will go with your suggestion, will let future Zafar think about refactoring 😄

**Review by soumith — APPROVED** [review]

**Comment by zafartahirov** [comment]
@soumith I take it back -- CUDA tests depend on the `common_utils.py`, and don't have `hypothesis` in their deps. This causes cuda tests to fail. I can fix it either by adding hypothesis to all tests that use `common_utils.py`, or by factoring out the hypothesis part. The former part seems like it could open more problems, and would require more future work. I will move back to my previous implementation (with `hypothesis_utils`) or try to reuse the code in `caffe2/python/hypothesis_utils.py` -- need to investigate more

**Pull request closed without merging**
