### PR TITLE
Remove TORCH_ASSERT

### PR DESCRIPTION
**Pull request by goldsborough**
I got some tensor->variable conversion exceptions from `torch/csrc/autograd/variable.h`, which used the `TORCH_ASSERTM` macros instead of `AT_CHECK`, so they didn't have backtraces. This was such a substantial loss for debugability that I decided to update the whole codebase to use the backtrace-enabled ATen macros instead of `TORCH_ASSERT` and `JIT_ASSERT`, the latter having been an alias of the former.

@ezyang @apaszke @zdevito

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by apaszke** [comment]
Can we please wait a bit with this patch? This will conflict with so many JIT changes... Is it really worth the cleanup? We could just `#define` those macros to `AT_*` implementations

**Comment by goldsborough** [comment]
I thought it would just be unnecessary to have `JIT_*` be the same as `AT_*`. Is it a huge pain to do the codemod locally in your PRs (if you globally replace `JIT_ASSERT` WITH `AT_CHECK` before rebasing, you'll have no conflicts)? The JIT is always heavily worked on, so I fear there would never be a "perfect" time for this kind of codemod

**Comment by goldsborough** [comment]
Ok I'll leave `JIT_*` as defines

**Pull request closed without merging**
