### PR TITLE
[profiler] Fix profiling PT2 w/ dynamic shapes & record_shapes

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104320

When using torch.profiler.profile(record_shapes=True), the profiler tries to collect `tensor.sizes()` to put this information into the profile trace.

When dynamic shapes is turned on, sometimes tensors will appear that have symbolic sizes. In that case, `tensor.sizes()` can throw an assertion. This PR checks to see if tensor has symbolic shapes, and doesn't collect shape info in that case.

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78

Differential Revision: [D47082414](https://our.internmc.facebook.com/intern/diff/D47082414)

### CODE REVIEW

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D47082414).

**Comment by davidberard98** [comment]
@Chillee is it safe to check if a tensor has symbolic shapes like this?

**Comment by Chillee** [comment]
@davidberard98 yeah. Seems fine to me, although I'm a bit confused about the overall setting. Is it that we can only capture shapes during compilation?

**Comment by davidberard98** [comment]
@Chillee This profiler code gets executed if you run `with torch.profiler.profile(record_shapes=True,...): ...`. When recording an op getting executed, the profiler tries to record the shapes of the tensors so it can add it in the chrometrace later.

**Review by aaronenyeshi — APPROVED** [review]
LGTM!

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D47082414).

**Pull request closed without merging**
