### PR TITLE
[SPMD] Pull the minimal working distribute API and SPMD module to PyTorch

### PR DESCRIPTION
**Pull request by fegin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #94860
* #94803
* __->__ #94802

Pull the minimal working distribute API and SPMD module to PyTorch. The original code is on https://github.com/pytorch/tau/tree/main/spmd/compiler.

Other main contributors to the original code base: @anj-s, @lessw2020, @wanchaol @aazzolini 

Differential Revision: [D43197230](https://our.internmc.facebook.com/intern/diff/D43197230/)

### CODE REVIEW

**Review by anj-s — APPROVED** [review]

**Review by wanchaol — APPROVED** [review]
LGTM. Looks like there's still lint failure, please fix it before landing :)

**Comment by fegin** [comment]
The two failing tests have the same error message and it does seem to be related to the PR.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: Error in dlopen: /opt/python/cp38-cp38/lib/python3.8/site-packages/torch/lib/libtorch_cuda_linalg.so: undefined symbol: sgebak_
```

@pytorchbot merge -f "The failing tests are not related"

**Pull request closed without merging**
