### PR TITLE
[cpuinfo][submodule] bump cpuinfo to the latest to support amx isa check

### PR DESCRIPTION
**Pull request by jgong5**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #129101
* #127195
* __->__ #127505

Fix https://github.com/pytorch/pytorch/issues/127368

### CODE REVIEW

**Comment by jgong5** [comment]
@malfet @mingfeima Could you please review the PR? Thanks.

**Comment by jgong5** [comment]
@malfet Does the PR look good to you? Thanks.

**Comment by jgong5** [comment]
@malfet @ezyang Can we land this PR? Thanks!

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
