### PR TITLE
OpInfo: Add opinfo for cum{min,max} and minor fixes

### PR DESCRIPTION
**Pull request by kshitij12345**
Reference: #54261

### CODE REVIEW

**Comment by kshitij12345** [comment]
@mruberry While checking the tests, I found that `cumprod` tests take quite long to run (around 2 mins). Worth filing an issue?

```
(pytorch-cuda-dev) kshiteej@qgpu1:~/Pytorch/pytorch_opinfo_cummax_cummin$ pytest test/test_ops.py -k _cumprod --durations=20
======================================================================= test session starts ========================================================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/kshiteej/Pytorch/pytorch_opinfo_cummax_cummin, configfile: pytest.ini
plugins: hypothesis-5.38.1
collected 11038 items / 10953 deselected / 85 selected                                                                                                             

test/test_ops.py .....s...........ssssssssssssssssss.....s...................ssssssss........s..ssss..                                                       [100%]

========================================================================= warnings summary =========================================================================
../../.conda/envs/pytorch-cuda-dev/lib/python3.8/site-packages/torch/backends/cudnn/__init__.py:73
test/test_ops.py::TestOpInfoCUDA::test_duplicate_method_tests_cumprod_cuda_float32
test/test_ops.py::TestGradientsCUDA::test_fn_grad_cumprod_cuda_complex128
test/test_ops.py::TestCommonCUDA::test_out_cumprod_cuda_float32
  /home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.8/site-packages/torch/backends/cudnn/__init__.py:73: UserWarning: PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild PyTorch making sure the library is visible to the build system.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================= slowest 20 durations =======================================================================
31.80s call     test/test_ops.py::TestGradientsCUDA::test_inplace_gradgrad_cumprod_cuda_complex128
29.82s call     test/test_ops.py::TestGradientsCUDA::test_fn_gradgrad_cumprod_cuda_complex128
10.69s call     test/test_ops.py::TestGradientsCPU::test_inplace_gradgrad_cumprod_cpu_complex128
10.61s call     test/test_ops.py::TestGradientsCUDA::test_inplace_gradgrad_cumprod_cuda_float64
10.09s call     test/test_ops.py::TestGradientsCPU::test_fn_gradgrad_cumprod_cpu_complex128
9.75s call     test/test_ops.py::TestGradientsCUDA::test_fn_gradgrad_cumprod_cuda_float64
3.43s call     test/test_ops.py::TestGradientsCPU::test_fn_gradgrad_cumprod_cpu_float64
3.28s call     test/test_ops.py::TestGradientsCPU::test_inplace_gradgrad_cumprod_cpu_float64
2.55s call     test/test_ops.py::TestGradientsCUDA::test_fn_grad_cumprod_cuda_complex128
2.52s call     test/test_ops.py::TestGradientsCUDA::test_inplace_grad_cumprod_cuda_complex128
1.19s call     test/test_ops.py::TestGradientsCUDA::test_inplace_grad_cumprod_cuda_float64
1.15s call     test/test_ops.py::TestGradientsCUDA::test_fn_grad_cumprod_cuda_float64
1.10s call     test/test_ops.py::TestCommonCUDA::test_variant_consistency_jit_cumprod_cuda_float32
1.00s call     test/test_ops.py::TestOpInfoCUDA::test_duplicate_method_tests_cumprod_cuda_float32
0.81s call     test/test_ops.py::TestGradientsCPU::test_inplace_grad_cumprod_cpu_complex128
0.67s call     test/test_ops.py::TestGradientsCPU::test_fn_grad_cumprod_cpu_complex128
0.60s call     test/test_ops.py::TestCommonCPU::test_variant_consistency_jit_cumprod_cpu_float32
0.35s call     test/test_ops.py::TestOpInfoCUDA::test_supported_backward_cumprod_cuda_float32
0.34s call     test/test_ops.py::TestOpInfoCUDA::test_supported_backward_cumprod_cuda_complex128
0.34s call     test/test_ops.py::TestOpInfoCUDA::test_supported_backward_cumprod_cuda_float16
===================================================================== short test summary info ======================================================================

============================================= 52 passed, 33 skipped, 10953 deselected, 4 warnings in 130.81s (0:02:10) =============================================
```

**Comment by mruberry** [comment]
> @mruberry While checking the tests, I found that `cumprod` tests take quite long to run (around 2 mins). Worth filing an issue?

Yes! Thanks for noticing this, please file an issue.

**Review by mruberry — APPROVED** [review]
Cool! Thanks @kshitij12345!

**Comment by kshitij12345** [comment]
@mruberry On latest master, `cumprod` takes around 1 min 10 seconds, while `cumsum` (for reference) takes around 28-30s.

Still worth an issue?

**Comment by mruberry** [comment]
> @mruberry On latest master, `cumprod` takes around 1 min 10 seconds, while `cumsum` (for reference) takes around 28-30s.
> 
> Still worth an issue?

Yep.

**Pull request closed without merging**
