### PR TITLE
`pow`: fix meta function output argument dtype check.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #140287

Tracking issue: #138399

This PR changes the `pow` C++ implementation, making its C++ meta kernel consistent with
its Python ref implementation. The following example shows the inconsistency between the
two:

```python
def run(device):
    S = (5,)
    a = torch.rand(S, device=device, dtype=torch.float32)
    b = 2
    out = torch.empty(S, device=device, dtype=torch.float64)
    return torch.pow(a, b, out=out)

>>> run("cpu")
Traceback (most recent call last):
  File "test.py", line 34, in run
    return torch.pow(a, b, out=out)
RuntimeError: Found dtype Double but expected Float

>>> run("meta")
tensor(..., device='meta', size=(5,), dtype=torch.float64)
```

**~Update:~**

~Note that this happens only for `pow.Tensor_Scalar` overloads. Therefore, this PR needed
further 2 modifications:~

- ~Split the `pow` ref implementation, making `pow.Tensor_Scalar` error on mismatching
output dtypes~
- ~Create a dispatch for `pow` when `_refs.pow()` is called~

**Update:**

Changing the `TensorIteratorConfig` for `pow.Tensor_Scalar` was easier and,
after the discussion below, more correct. The solution was to change the
`TensorIteratorBase::build_output_borrowing_argument_owning_unary_op` function,
setting:

- `cast_common_dtype_to_outputs`; and
- `enforce_safe_casting_to_output`.

### CODE REVIEW

**Comment by ysiraichi** [comment]
While **the old version of this PR** did make the meta implementation of `pow.Tensor_Scalar` overloads consistent with its C++ version, I didn't think that was the right way to go.

According to the [developer FAQ](https://github.com/pytorch/pytorch/wiki/Developer-FAQ#how-does-out-work-in-pytorch):

> For operations that do not participate in type promotion the device and dtype of the source and destination tensors must match. For operations that do participate in type promotion the copy can be to a different dtype, but the destination of the copy cannot be a lower "type kind" than the source.

Which means that: if `pow.Tensor_Scalar` does participate in dtype promotion (it does call `at::result_type(...)`), we can safe copy to an output tensor with a different dtype (not lower kind, though). Which means that the C++ meta function should be changed (current state of this PR).

**Note:** while this implementation works, we are running the whole computation in the output argument dtype, instead of just safe-copying the results. Technically, I think this does not reflect on the [developer FAQ](https://github.com/pytorch/pytorch/wiki/Developer-FAQ#how-does-out-work-in-pytorch) specification. For that, we would need to change the `TensorIterator` a bit.

@ezyang @amjames Any thoughts on this?

**Comment by amjames** [comment]
I agree that the behavior of running the entire op in the wider dtype does not seem to match the spec outlined in the developer FAQ, however I suppose it does preserve the user visible behavior. On the other hand, modifying `TensorIterator` to handle this situation in a more correct way would be a fairly invasive change, and may have lots of side effects. 

I suppose we could try making that modification to `TensorIterator` here and see what happens, but what you have here looks okay to me.

**Review by ezyang — APPROVED** [review]

**Review by ezyang — CHANGES_REQUESTED** [review]
beh looks like this is a semantics change though :P

**Comment by ysiraichi** [comment]
While it does change the semantics, in the sense that we don't expect the output tensor to be of an exact dtype, I think it brings us closer to the `out=` specification.

**Comment by ysiraichi** [comment]
The CI failure is unrelated to this PR.

**Comment by ysiraichi** [comment]
@ezyang Could you take a look at this PR? I have [commented](https://github.com/pytorch/pytorch/pull/140287#issuecomment-2484358529) on the semantic change. I don't think this would break anything, though, since the change only makes `pow` less strict regarding output tensor dtype.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
