### PR TITLE
re-removed python dispatch key from stuff

### PR DESCRIPTION
**Pull request by Chillee**
Reland of https://github.com/pytorch/pytorch/pull/74971

### CODE REVIEW

**Review by atalman — APPROVED** [review]
LGTM

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Looks like it is completely identical to https://github.com/pytorch/pytorch/pull/74971

Let's reopen and re-merge that one

**Comment by malfet** [comment]
Re-landed original change

**Pull request closed without merging**
