### PR TITLE
Remove Flake8 version pin

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#38268 Remove Flake8 version pin**
* #38269 Pin flake8 to 3.7.9

Differential Revision: [D21510092](https://our.internmc.facebook.com/intern/diff/D21510092)

### CODE REVIEW

**Comment by ngimel** [comment]
As discussed, I think it makes sense to pin flake8 version after we fix the lint, so that it does not unexpectedly break next time.

**Comment by mrshenli** [comment]
> As discussed, I think it makes sense to pin flake8 version after we fix the lint, so that it does not unexpectedly break next time.

Will ping to 3.8.0 then. But seems its not compatible with pyi:

```
$ flake8 --version
Traceback (most recent call last):
  File "/private/home/shenli/local/miniconda/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/private/home/shenli/local/miniconda/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/private/home/shenli/local/miniconda/lib/python3.7/site-packages/flake8/main/application.py", line 355, in run
    self._run(argv)
  File "/private/home/shenli/local/miniconda/lib/python3.7/site-packages/flake8/main/application.py", line 342, in _run
    self.initialize(argv)
  File "/private/home/shenli/local/miniconda/lib/python3.7/site-packages/flake8/main/application.py", line 324, in initialize
    self.register_plugin_options()
  File "/private/home/shenli/local/miniconda/lib/python3.7/site-packages/flake8/main/application.py", line 160, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/private/home/shenli/local/miniconda/lib/python3.7/site-packages/flake8/plugins/manager.py", line 494, in register_options
    list(self.manager.map(register_and_enable))
  File "/private/home/shenli/local/miniconda/lib/python3.7/site-packages/flake8/plugins/manager.py", line 302, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/private/home/shenli/local/miniconda/lib/python3.7/site-packages/flake8/plugins/manager.py", line 490, in register_and_enable
    call_register_options(plugin)
  File "/private/home/shenli/local/miniconda/lib/python3.7/site-packages/flake8/plugins/manager.py", line 402, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/private/home/shenli/local/miniconda/lib/python3.7/site-packages/flake8/plugins/manager.py", line 216, in register_options
    add_options(optmanager)
  File "/private/home/shenli/local/miniconda/lib/python3.7/site-packages/pyi.py", line 359, in add_options
    option.to_optparse().default = option.default
  File "/private/home/shenli/local/miniconda/lib/python3.7/site-packages/flake8/options/manager.py", line 332, in to_optparse
    raise AttributeError("to_optparse: flake8 now uses argparse")
AttributeError: to_optparse: flake8 now uses argparse
```

**Comment by ngimel** [comment]
So should we leave it at 3.7.9 for now then?

**Comment by mrshenli** [comment]
Looks like so, seems we need to wait for either a fix from flake8 or flake8-pyi

**Pull request closed without merging**
