### PR TITLE
Add Lazy Tensor codegen infra

### PR DESCRIPTION
**Pull request by wconstab**
Summary: Merges the lazy tensor codegen infra which has already been used on lazy_tensor_staging.

Test Plan: Test via lazy_tensor_staging branch

Differential Revision: D32570613

### CODE REVIEW

**Comment by bdhirsh** [comment]
There's an extra, empty `metrics.h/cpp` file added. Was that by accident?

**Comment by wconstab** [comment]
> There's an extra, empty `metrics.h/cpp` file added. Was that by accident?

yea, i actually have a follow-on diff that fills in those files and i've just updated this PR to not add the empty files.  I plan to land as-is and then add the metrics later.

**Review by bdhirsh — APPROVED** [review]
Ok! I see an xla failure in CI that looks relevant to the codegen. You might need to update gen_backend_stubs

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Pull request closed without merging**
