### PR TITLE
[ROCm] Add AMD devs as owners for hipify code

### PR DESCRIPTION
**Pull request by jithunnair-amd**
cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@malfet Thoughts on this?

**Comment by jithunnair-amd** [comment]
@malfet Also, related question for my understanding: would being code owners allow us to merge PRs that **only** touch the files we own? Or does it only basically ensure that we would get automatically added as reviewers if a PR touches these files?

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
> @malfet Also, related question for my understanding: would being code owners allow us to merge PRs that **only** touch the files we own? Or does it only basically ensure that we would get automatically added as reviewers if a PR touches these files?

Only CCed, merge rules are defined in *drumroll* [merge_rules.yml](https://github.com/pytorch/pytorch/blob/main/.github/merge_rules.yaml#L389) where Jeff is already an owner of everything hip:
https://github.com/pytorch/pytorch/blob/bf46b6653fe41a8cab70f35269f1898f1ebd9544/.github/merge_rules.yaml#L389-L394

**Pull request closed without merging**
