### PR TITLE
[cuDNN][CUDA] Fix for `install_cudnn.sh` following 12.1 CI update

### PR DESCRIPTION
**Pull request by eqy**
Trying out a fix for the path

CC @Aidyn-A @ptrblck

cc @csarofeen @ptrblck @xwang233 @ngimel

### CODE REVIEW

**Comment by eqy** [comment]
CC @malfet

**Comment by eqy** [comment]
CC @clee2000

**Review by ngimel — APPROVED** [review]
hm how did this ever work if the path is wrong?

**Comment by eqy** [comment]
> hm how did this ever work if the path is wrong?

Was the 12.1 build I working previously or only 11.x builds?

**Comment by Aidyn-A** [comment]
> hm how did this ever work if the path is wrong?

Seems like it was ignoring failures in `install_cudnn.sh` relying only on ATen native convolutions. 
Only the slow workflow detected were was an issue:
```
2023-05-02T04:52:07.7784852Z -- Could NOT find CUDNN (missing: CUDNN_LIBRARY_PATH CUDNN_INCLUDE_PATH) 
```
here: https://github.com/pytorch/pytorch/actions/runs/4857693186/jobs/8658411309

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
