### PR TITLE
Add skip models by device in Dynamo Test

### PR DESCRIPTION
**Pull request by WeizhuoZhang-intel**
Fix skip logic in `runner.py`. Add skip list which was defined by device for dynamo benchmark runner `runner.py`.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by WeizhuoZhang-intel** [comment]
@chuanqi129

**Review by chuanqi129 — APPROVED** [review]

**Review by desertfire — APPROVED** [review]

**Review by jgong5 — APPROVED** [review]

**Pull request closed without merging**
