### PR TITLE
Upgrade nightly wheels to rocm6.1

### PR DESCRIPTION
**Pull request by jithunnair-amd**
Follow-up to https://github.com/pytorch/builder/pull/1789

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
[libtorch build failure](https://hud.pytorch.org/pr/pytorch/pytorch/124811#24187571059) blocked on issue with job that should have built and pushed the libtorch docker images to dockerhub: https://github.com/pytorch/builder/actions/runs/8792217021/job/24127939465

**Comment by atalman** [comment]
@jithunnair-amd  this if fixed

**Comment by jithunnair-amd** [comment]
All binary build jobs succeeded now. But retriggering Triton wheel build jobs (https://github.com/pytorch/pytorch/actions/runs/8810600271) because [PR to move to upstream triton AMD backend](https://github.com/pytorch/pytorch/pull/121801) was merged recently.

**Comment by jithunnair-amd** [comment]
@malfet @atalman This PR is ready to merge. Binaries ROCm CI passed.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
