### PR TITLE
error when using _dynamo.optimize_ddp=True and _inductor.keep_output_stride=False together

### PR DESCRIPTION
**Pull request by bdhirsh**
From talking to @wconstab, we agreed that because of the way DDPOptimizer is written, it is (sort of) incompatible with inductor's `keep_output_stride=False` optimizations (and will cause silent correctness problems if you use them ogether). Added an assertion.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #108570
* #108243
* __->__ #108235
* #108081

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by wconstab — APPROVED** [review]

**Comment by ezyang** [comment]
And where is this discussion recorded durably?

**Comment by bdhirsh** [comment]
It’s not- fair point, I’ll add a comment describing why. It’s basically that because DDPOptimizer takes a single dynamo graph, partitioners it and sends each partitioned graph (say graphs 1 and 2, where outputs to 1 become inputs to 2) to AOTAutograd/inductor, then inductor might end up optimizing graph 1 to return an output tensor with a stride *different* from eager, but we will (incorrectly) send inductor a graph 2 with a graph input that  has the wrong stride- it’ll have the “correct” stride from eager mode, instead of the updated strides that inductor will eventually give the output to graph 1.

**Comment by ezyang** [comment]
This doesn't seem fundamentally unfixable though? DDP optimizer would just need to know to look at the updated output stride from inductor no?

**Comment by bdhirsh** [comment]
Yep, agreed. Although cc @wconstab whether or not / when to fix it probably depends on the long term plans for ddp optimizer?

**Comment by ezyang** [comment]
Yes, I'm mostly objecting to

>  because of the way DDPOptimizer is written, it is fundamentally incompatible with inductor's keep_output_stride=False optimizations 

This is fine for now ;)

**Pull request closed without merging**
