### PR TITLE
[GH1] Add builds as required status checks

### PR DESCRIPTION
**Pull request by janeyx99**
Requires builds to now pass before merge.

### CODE REVIEW

**Review by suo — APPROVED** [review]
Hard-coding a list and duplicating it multiple times doesn't seem maintainable. If we remove or temporarily disable one of these jobs, does it block merges?

What are your thoughts for how we handle this in the long run?

**Comment by janeyx99** [comment]
@suo I was thinking about this, especially as @kit1980 is working on replacing xenial with focal, so these will definitely change. 

Some longterm solutions I was thinking about:
1. Having the bot check for regexes instead of exact names --> is less transparent/adds complexity
2. Having one place to define these checks --> only resolves the duplication problem
3. Standardizing job names so updates don't affect these as much --> some updates will still have inconsistencies

All of these have their pros + cons + engineering effort, and I figured we should move ASAP to being able to just specify all of the `pull` workflow as required, and have this hardcoding be an intermediate pain. If we wanted to address this issue, I'd opt for #1 or #2.

**Comment by suo** [comment]
I guess in the long run, we will require that the whole workflow will be successful. So maybe it's fine to hardcode during the migration

**Comment by eellison** [comment]
Can we revert this? it's blocking internal landing

**Pull request closed without merging**
