### PR TITLE
[NNC] Do not optimize conditionals when the corresponding loop is not normalized

### PR DESCRIPTION
**Pull request by navahgar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#57675 [NNC] Do not optimize conditionals when the corresponding loop is not normalized**
* #57674 [NNC] Add a method to check if a loop is normalized
* #57673 [NNC] Optimize conditionals that correspond to the form generated for aten::cat op.

Differential Revision: [D28231375](https://our.internmc.facebook.com/intern/diff/D28231375)

### CODE REVIEW

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28231375).

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28231375).

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28231375).

**Review by bertmaher — APPROVED** [review]

**Comment by bertmaher** [comment]
This looks great.  We should consider turning it on if it passes all the internal tests!

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28231375).

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28231375).

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28231375).

**Pull request closed without merging**
