### PR TITLE
converted tests using 'same' to assertEqual statements

### LINKED ISSUE #93701: Replace same with TestCase assertEqual
In TorchDynamo tests, we use `same` function to check for accuracy. But for many cases, we can rely on TestCase assertEqual which has pre-defined atol/rtol for different dtypes. We should migrate the tests to `assertEqual`  as much as possible. Thanks to @SherlockNoMad for pointing this out.

cc @ezyang @msaroufim @wconstab @bdhirsh @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel @williamwen42 if you are interested.

### PR DESCRIPTION
**Pull request by tpenumatcha**
Fixes #93701 
Migrated tests in TorchDynamo tests to `assertEqual` instead of `same` function

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]
LGTM as long as the tests pass

**Comment by tpenumatcha** [comment]
seems like all the tests passed @zou3519, I don't have permission to merge, can you go ahead and merge?

**Comment by tpenumatcha** [comment]
@zou3519 sorry seems like another approval is needed before merging

**Comment by tpenumatcha** [comment]
@zou3519 sorry, seems like another approval is needed. thanks

**Comment by tpenumatcha** [comment]
all tests are passing ✅ just need to be approved before merging

**Comment by tpenumatcha** [comment]
all the tests/checks have passed ✅, just need to be approved again to merge @zou3519, thanks!

**Comment by tpenumatcha** [comment]
all the tests/checks have passed ✅, just need to be approved again to merge @zou3519, thanks!

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
