### PR TITLE
Make TensorIterator give better error message for symbolic tensors

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #92914

This is one of the more common reasons to see
"RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides"

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM

**Review by bdhirsh — APPROVED** [review]

**Pull request closed without merging**
