### PR TITLE
Fix null pointer dereference on ROCm

### LINKED ISSUE #95808: NanoGPT training crashes on ROCm
### 🐛 Describe the bug

When training nanoGPT on ROCm (MI250x) GPUs, I get a memory access fault:

```
$ python train.py config/train_shakespeare_char.py --compile=False
Overriding config with config/train_shakespeare_char.py:
# train a miniature character-level shakespeare model
# good for debugging and playing on macbooks and such

out_dir = 'out-shakespeare-char'
eval_interval = 250 # keep frequent because we'll overfit
eval_iters = 200
log_interval = 10 # don't print too too often

# we expect to overfit on this small dataset, so only save when val improves
always_save_checkpoint = False

wandb_log = False # override via command line if you like
wandb_project = 'shakespeare-char'
wandb_run_name = 'mini-gpt'

dataset = 'shakespeare_char'
batch_size = 64
block_size = 256 # context of up to 256 previous characters

# baby GPT model :)
n_layer = 6
n_head = 6
n_embd = 384
dropout = 0.2

learning_rate = 1e-3 # with baby networks can afford to go a bit higher
max_iters = 5000
lr_decay_iters = 5000 # make equal to max_iters usually
min_lr = 1e-4 # learning_rate / 10 usually
beta2 = 0.99 # make a bit bigger because number of tokens per iter is small

warmup_iters = 100 # not super necessary potentially

# on macbook also add
# device = 'cpu'  # run on cpu only
# compile = False # do not torch compile the model

Overriding: compile = False
found vocab_size = 65 (inside data/shakespeare_char/meta.pkl)
Initializing a new model from scratch
WARNING: using slow attention. Flash Attention atm needs PyTorch nightly and dropout=0.0
WARNING: using slow attention. Flash Attention atm needs PyTorch nightly and dropout=0.0
WARNING: using slow attention. Flash Attention atm needs PyTorch nightly and dropout=0.0
WARNING: using slow attention. Flash Attention atm needs PyTorch nightly and dropout=0.0
WARNING: using slow attention. Flash Attention atm needs PyTorch nightly and dropout=0.0
WARNING: using slow attention. Flash Attention atm needs PyTorch nightly and dropout=0.0
number of parameters: 10.65M
using fused AdamW: True
step 0: train loss 4.2874, val loss 4.2823
Memory access fault by GPU node-4 (Agent handle: 0x6f9b500) on address (nil). Reason: Unknown.
Aborted
```

### Expected outcome
Training continues

### Versions

Please see the [nanoGPT repository](https://github.com/karpathy/nanoGPT) for how to install the reproducer and dependencies.

In a nutshell:
```
git clone https://github.com/karpathy/nanoGPT.git
cd nanoGPT
python data/shakespeare_char/prepare.py
python train.py config/train_shakespeare_char.py --compile=False
```

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: SUSE Linux Enterprise Server 15 SP3 (x86_64)
GCC version: (SUSE Linux) 7.5.0
Clang version: 14.0.2  (ecfd9ef4dfd5696cd449133c0da0293d503c2f21)
CMake version: version 3.17.0
Libc version: glibc-2.31

Python version: 3.8.16 (default, Jan 17 2023, 23:13:24)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.3.18-150300.59.87_11.0.78-cray_shasta_c-x86_64-with-glibc2.17
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       1
NUMA node(s):                    4
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           48
Model name:                      AMD EPYC 7A53 64-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         3093.761
CPU max MHz:                     2000.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        3992.40
Virtualization:                  AMD-V
L1d cache:                       2 MiB
L1i cache:                       2 MiB
L2 cache:                        32 MiB
L3 cache:                        256 MiB
NUMA node0 CPU(s):               0-15,64-79
NUMA node1 CPU(s):               16-31,80-95
NUMA node2 CPU(s):               32-47,96-111
NUMA node3 CPU(s):               48-63,112-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==1.8.6
[pip3] torch==2.0.0a0+git10a1efb
[pip3] torchmetrics==0.10.3
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-lightning         1.8.6                    pypi_0    pypi
[conda] torch                     2.0.0a0+git10a1efb          pypi_0    pypi
[conda] torchmetrics              0.10.3                   pypi_0    pypi

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### PR DESCRIPTION
**Pull request by jglaser**
The root cause of the crash in training nanoGPT was a null pointer dereference in the layer norm kernel.

While addressing the issue, I also made sure that `__syncthreads()` is simultaneously called by all threads in the block, to avoid unwanted side effects.

Moreover, I changed the kernel launch code to be more clear about the accumulation data type (`T_ACC`) and thread block dimensions, without changing function.

Fixes #95808

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo

### CODE REVIEW

**Comment by cpuhrsch** [comment]
Looks like this is a reasonable PR and only touches code related to ROCm, however please see the current CI failures. You can use the hub for a quick overview: https://hud.pytorch.org/pr/95810

**Comment by jglaser** [comment]
> Looks like this is a reasonable PR and only touches code related to ROCm, however please see the current CI failures. You can use the hub for a quick overview: https://hud.pytorch.org/pr/95810

Thanks .. I only see one unit test failure in the CUDA code path, which doesn't seem related to the present PR as it occurs on NVIDIA hardware rather than AMD/ROCm

**Comment by jithunnair-amd** [comment]
@jglaser Can you please sign the CLA if you haven't already: https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/29311126/65600975/95810/#/?version=2

**Review by ngimel — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@jglaser Can you please sign the CLA if you haven't already: https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/29311126/65600975/95810/#/?version=2

**Comment by stanleyshly** [comment]
Any update to this pr? This issue still exists on ROCm with training nanoGPT.

**Comment by jglaser** [comment]
working out the last steps to get the contributor license agreement signed on our end, hopefully very soon

**Comment by jeffdaily** [comment]
@jglaser any update on the CLA?

**Comment by stanleyshly** [comment]
Same here. To my knowledge, the issue still exists and is creating issues for popuar repos, like nanoGPT.

**Comment by sunway513** [comment]
> working out the last steps to get the contributor license agreement signed on our end, hopefully very soon

Hi @jglaser can you help update the status on your end? We'd like to have this issue fixed for ROCm backend, thank you.

**Comment by kit1980** [comment]
If the CLA is not signed we'll have to close this PR.
Someone else can create a different PR to fix the issue.

**Comment by jglaser** [comment]
I understand... proceed in whichever way you wish. I'm still working with our attorney to enable open source contributions.... especially, future ones - I hope to have it resolved within 1-2 weeks. Is there a way to restrict the corporate CLA to apply only to contributions from a specific github organization, which would host the fork?

**Comment by jglaser** [comment]
> Hi @jglaser I can help resubmiting this pull request on your behalf to pass CLA, if you're comfortable with this approach I would be happy to help and get this merged

Hi @Cemberk  ... thanks.. please note that I just signed the CLA on my own behalf... should be good now

**Comment by kit1980** [comment]
@cpuhrsch do you think we should merge this now?

**Comment by cpuhrsch** [comment]
@kit1980 - Yes, this seems to only touch ROCM code. However, it would be good to have a test that fails without this change. Since this test fixes a null pointer dereference issue it would have been nice to see a failure in our CI. The fact that our CI currently runs green without this change means that we have an important gap in test coverage.

**Comment by cpuhrsch** [comment]
@kit1980 - Yes, this seems to only touch ROCM code. However, it would be good to have a test that fails without this change. Since this test fixes a null pointer dereference issue it would have been nice to see a failure in our CI. The fact that our CI currently runs green without this change means that we have an important gap in test coverage.

**Comment by jglaser** [comment]
OK. Here is a minimal reproducer

```
import torch
import torch.nn.functional as F
from torch import nn

device = 'cuda:0'
dtype = torch.float64 # double for gradcheck
ndim = 128 # test should pass for < 128
a = torch.zeros((ndim, 1), device=device, dtype=dtype)
a.requires_grad=True
ln = nn.LayerNorm(1).to(device).to(dtype)
torch.autograd.gradcheck(ln, a)
torch.cuda.synchronize()
print('gradcheck passed')
torch.autograd.grad(ln(a).sum(), ln.parameters())
torch.cuda.synchronize()
print('total derivative passed')
torch.autograd.grad(ln(a).sum(), ln.weight)
torch.cuda.synchronize()
print('partial derivative passed')
``` 

On ROCm platforms, it crashes the following way (before applying the present PR)
```
gradcheck passed
total derivative passed
Memory access fault by GPU node-4 (Agent handle: 0x78cf2c0) on address (nil). Reason: Unknown.
Aborted
``` 

I added the required unit test enhancements in a separate PR

**Comment by kit1980** [comment]
I see the test failed as expected in https://github.com/pytorch/pytorch/pull/103809
Let's merge this.

**Comment by jglaser** [comment]
> ## Merge failed
> **Reason**: 1 jobs have failed, first few of them are: [trunk / linux-focal-rocm5.4.2-py3.8 / test (default, 1, 3, linux.rocm.gpu)](https://github.com/pytorch/pytorch/actions/runs/5351220573/jobs/9705051361)
> 
> Details for Dev Infra team

Hmm... the test failure on ROCm seems unrelated to this PR as it also occurs in a run from a different PR
https://github.com/pytorch/pytorch/actions/runs/5351124006/jobs/9704876070

**Pull request closed without merging**
