### PR TITLE
[WIP] Migrate put_() from TH to ATen (CPU)  

### LINKED ISSUE #24614: Migrate `put_` from the TH to Aten (CUDA)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

### LINKED ISSUE #24751: Migrate `put_` from the TH to Aten (CPU)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

### PR DESCRIPTION
**Pull request by leonvol**
Move CPU implementation for put_() from TH to ATen. Fixes #24751

### CODE REVIEW

**Comment by leonvol** [comment]
Does anyone have some advice, if I can take a similar approach to `take_out_cpu_template()` to use `at::parallel_for` as the main loop in the migrated function? @VitalyFedyunin

**Comment by nikitaved** [comment]
Hey, @leonvol ! You can restride your input to be efficiently used with TensorIterator. That way you will parallelize over `self.numel()` elements, which will eliminate the need for the serial for-loop over indices. You could have a look at https://github.com/pytorch/pytorch/pull/50578.

**Comment by Lezcano** [comment]
Hi @leonvol 

Is this PR still active? If not, I would not mind taking over it! :)

**Comment by leonvol** [comment]
Hi @Lezcano , feel free to take this PR over. I am currently quite busy :)

**Comment by Lezcano** [comment]
Thanks! I will do so in the next few days :)

**Comment by Lezcano** [comment]
This port was done in https://github.com/pytorch/pytorch/pull/53356

**Pull request closed without merging**
