### PR TITLE
Adding maximize to rprop

### PR DESCRIPTION
**Pull request by zaxtax**
Added the maximize flag #68052 to rprop optimizer and updates the respective tests.

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM

**Comment by albanD** [comment]
@pytorchbot revert -m "Broke rocm and windows test" -c nosignal

See https://github.com/pytorch/pytorch/runs/7248567170?check_suite_focus=true and https://github.com/pytorch/pytorch/runs/7248416606?check_suite_focus=true for example

**Comment by zaxtax** [comment]
@albanD how do I re-run with CI system?

**Comment by albanD** [comment]
Since you re-created the branch, you will have to create a new PR for this.

**Pull request closed without merging**
