### PR TITLE
[3/N] apply clang-tidy in torch/csrc/autograd

### PR DESCRIPTION
**Pull request by cyyever**
This PR applies clang-tidy fixes in torch/csrc/autograd/FunctionsManual.cpp. There are also other fixes.

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
Causes some issues on MacOS arm with an ambiguous call. You will probably need to fix that.

**Comment by cyyever** [comment]
> The maybe_wrap changes causes some issues on MacOS arm with an ambiguous call, unfortunately. :/

fixed

**Pull request closed without merging**
