### PR TITLE
Add lazy shape inference for take op

### PR DESCRIPTION
**Pull request by wonjoo-wj**
Add lazy shape inference for take op

---

Companion PR on XLA's side: https://github.com/pytorch/xla/pull/3818

### CODE REVIEW

**Comment by JackCaoG** [comment]
@Krovatkin Can we get a review for this one?

**Comment by wonjoolee95** [comment]
@Krovatkin A gentle ping 😄

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Review by JackCaoG — APPROVED** [review]

**Review by JackCaoG — APPROVED** [review]

**Review by JackCaoG — APPROVED** [review]

**Pull request closed without merging**
