### PR TITLE
Fix in file position logic: file descriptor and Python-side handle

### PR DESCRIPTION
**Pull request by philippslang**
This addresses #18436 

The logic replicates the essence of closing file descriptors in numpy:
https://github.com/numpy/numpy/blob/bf20e3034085716c4559ec4bf31b23b6016f266c/numpy/core/include/numpy/npy_3kcompat.h#L278

This stores the position of the file descriptor before resetting it to the Python handle offset, then resets to the original position before exit. The Python-side handle is then updated to reflect the new position. Also added somewhat more demanding tests to cover this.

### CODE REVIEW

**Review by soumith — APPROVED** [review]
lgtm, thanks for the fix

**Comment by plang85** [comment]
oh boy, renamed variables after testing

**Comment by soumith** [comment]
thank you!

**Comment by Roffild** [comment]
```
 File "torch\serialization.py", line 581, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
OSError: [Errno 22] Invalid argument
```

**Pull request closed without merging**
