### PR TITLE
[ROCm] Switch to the new profiler infrastructure

### PR DESCRIPTION
**Pull request by iotamudelta**
The ones supported going forward are rocprofiler and roctracer.

### CODE REVIEW

**Comment by iotamudelta** [comment]
@bddppq docker respin would be ideal - but we can also wait w/ that for ROCm 2.8 when/if that lands on the CI.

**Review by bddppq — APPROVED** [review]
Are there going to be some api changes? Or are these packages just command line tools (i.e. not part of pytorch build)?

**Comment by bddppq** [comment]
Rebuilt new docker images with tag 306. Triggered CI jobs with new docker images:
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger-test/43960/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger/50915/

**Comment by bddppq** [comment]
cc @xw285cornell

**Comment by iotamudelta** [comment]
@bddppq thanks for merging! so far, these are just tools.

**Pull request closed without merging**
