### PR TITLE
Add python version and cuda-specific folder to store extensions

### PR DESCRIPTION
**Pull request by andfoy**
See #55267

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
type error is real

**Comment by ezyang** [comment]
Are you sure there isn't a way to fix this without adding a suppression?

**Comment by andfoy** [comment]
I could try using `torch.version.cuda is not None` and see if that fixes the verification?

**Comment by andfoy** [comment]
I think this is a current limitation of MyPy: https://github.com/python/mypy/issues/5392

**Pull request closed without merging**
