### PR TITLE
Enable ufmt format on test files

### PR DESCRIPTION
**Pull request by zeshengzong**
Fixes some files in  #123062 

Run lintrunner on files:

test/test_nnapi.py,
test/test_numba_integration.py,
test/test_numpy_interop.py,
test/test_openmp.py,
test/test_optim.py

```bash
$ lintrunner -a --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```

### CODE REVIEW

**Comment by ezyang** [comment]
diff looks ok

```
diff --git b/test/test_nnapi.py a/test/test_nnapi.py
index 33e3ab3f53f..cea0df251e8 100644
--- b/test/test_nnapi.py
+++ a/test/test_nnapi.py
@@ -28,6 +28,7 @@ def nhwc(t):
     "This Pytorch Build has not been built with or does not support QNNPACK",
 )
 class TestNNAPI(TestCase):
+
     def setUp(self):
         # Avoid saturation in fbgemm
         torch.backends.quantized.engine = "qnnpack"
diff --git b/test/test_numba_integration.py a/test/test_numba_integration.py
index 2fbe1d0bbc4..f5301cfc181 100644
--- b/test/test_numba_integration.py
+++ a/test/test_numba_integration.py
@@ -60,6 +60,7 @@ class TestNumbaIntegration(common.TestCase):
             numpy.uint8,
         ]
         for tp, npt in zip(types, dtypes):
+
             # CPU tensors do not implement the interface.
             cput = tp(10)
 
@@ -120,6 +121,7 @@ class TestNumbaIntegration(common.TestCase):
         ]
 
         for dt in torch_dtypes:
+
             # CPU tensors of all types do not register as cuda arrays,
             # attempts to convert raise a type error.
             cput = torch.arange(10).to(dt)
diff --git b/test/test_optim.py a/test/test_optim.py
index fc72b812cb7..ca6c9757f1b 100644
--- b/test/test_optim.py
+++ a/test/test_optim.py
@@ -891,9 +891,11 @@ class TestOptimRenewed(TestCase):
                     optim_info,
                     "foreach",
                     reduced_precision=default_dtype == torch.float16,
-                    assert_step_dtype=torch.float64
-                    if default_dtype == torch.float64
-                    else torch.float32,
+                    assert_step_dtype=(
+                        torch.float64
+                        if default_dtype == torch.float64
+                        else torch.float32
+                    ),
                 )
             finally:
                 torch.set_default_dtype(old_default_dtype)
```

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
fix lint failures please

**Comment by hippocookie** [comment]
@ezyang I think this time it might be ok, thanks!

**Pull request closed without merging**
