### PR TITLE
Eliminate more manually written copy loops with calls to memcpy.

### PR DESCRIPTION
**Pull request by resistor**

### CODE REVIEW

**Comment by colesbury** [comment]
On, #19198 you write "memcpy is already vectorized on every platform of note."

What platforms are you referring to? Have you measure this? Does it incur the overhead of a function call?

**Comment by resistor** [comment]
> On, #19198 you write "memcpy is already vectorized on every platform of note."
> 
> What platforms are you referring to? Have you measure this? Does it incur the overhead of a function call?

`memcpy` has fancy high performance implementations on (at least) Windows, Darwin (macOS and iOS), and Linux.

Here's an example of the glibc implementation on Linux:  https://github.molgen.mpg.de/git-mirror/glibc/blob/master/sysdeps/x86_64/memcpy.S

Here's an example of MSDN docs referring to the compiler being "optimized to a call to the performance-tuned memcpy function": https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/memcpy-wmemcpy?view=vs-2019

I don't have a public reference for Darwin's `memcpy` being fast except that I used to work with the maintainer, and can confirm that is it vectorized similarly to the glibc version.

**Review by soumith — APPROVED** [review]

**Comment by resistor** [comment]
> On, #19198 you write "memcpy is already vectorized on every platform of note."
> 
> What platforms are you referring to? Have you measure this? Does it incur the overhead of a function call?

Regarding function overhead, all major compilers (GCC, Clang, and MSVC) special case `memcpy` and expand it inline in scenarios where the copy is known to be small, including when that information becomes known after inlining.

**Review by colesbury — CHANGES_REQUESTED** [review]
I'm aware that the most recent glibc has an efficient memcpy implementation. In some cases with large arrays, it's even faster than the loop in PyTorch.

However, we target not only the most recent glibc, but also older glibc versions (2.17+). IIRC, glibc 2.17 does not have an efficient memcpy (it does not use AVX instructions).

I believe GLIBC 2.17 is distributed with CentOS 7/RHEL 7, which is fairly common among our users.

**Comment by colesbury** [comment]
> Regarding function overhead, all major compilers (GCC, Clang, and MSVC) special case memcpy and expand it inline in scenarios where the copy is known to be small

In our calls to `convert`, can the compiler statically determine size of the copy? From looking at the code, I think the answer is no.

Does the function call overhead matter? I suspect that there are cases where the inner loop is small enough that it would matter. (For example, a broadcast-copy of size `[8]` to a tensor of size `[1000000, 8]`

**Comment by resistor** [comment]
> I'm aware that the most recent glibc has an efficient memcpy implementation. In some cases with large arrays, it's even faster than the loop in PyTorch.
> 
> However, we target not only the most recent glibc, but also older glibc versions (2.17+). IIRC, glibc 2.17 does not have an efficient memcpy (it does not use AVX instructions).
> 
> I believe GLIBC 2.17 is distributed with CentOS 7/RHEL 7, which is fairly common among our users.

I just checked the implementation in glibc 2.17. The fast path uses rep movsq, which, while not necessarily optimal, is generally pretty good on all architectures post-Ivy Bridge.

**Comment by soumith** [comment]
> I just checked the implementation in glibc 2.17. The fast path uses rep movsq, which, while not necessarily optimal, is generally pretty good on all architectures post-Ivy Bridge.

Maybe we shouldn't push the PR then, i mean, it's a small PR that's optional that sort of cleans up a trivial amount of code. It makes sense to keep it, rather than worry about where memcpy is and isn't good.

**Comment by resistor** [comment]
More relevant to #19198 (AFAICT the code in this PR has no actually callers) but I made a benchmark for the small copy example:

> import torch
> a = torch.tensor([1,2,3,4,5,6,7,8], dtype=torch.float32)
> b = torch.zeros(1000000, 8)
> import timeit
> timeit.timeit("b.copy_(a)", "from __main__ import a, b", number=10000)

With #19198, I got 166.26 seconds.  With the change reverted, I got 168.57 seconds.

**Pull request closed without merging**
