### PR TITLE
Change whitelist to allow in file test_quantized_op.py

### LINKED ISSUE #41751: Replace blacklist/whitelist in test/quantization/test_quantized_op.py
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `test/quantization/test_quantized_op.py`. See issue #41443 for more information.

### PR DESCRIPTION
**Pull request by kenjihiraoka**
Fixes #41751

### CODE REVIEW

**Review by vkuzo — APPROVED** [review]

**Review by z-a-f — APPROVED** [review]
lgtm

**Comment by kenjihiraoka** [comment]
@SplitInfinity do i need to do something for these failed build/tests?

**Comment by SplitInfinity** [comment]
@kenjihiraoka No. I'll merge this. Thanks for working on it!

**Comment by kenjihiraoka** [comment]
Nice, I appreciate the opportunity to contribute :smile:

**Pull request closed without merging**
