### PR TITLE
[spmd expansion] support torch.ops.aten.sym_numel

### PR DESCRIPTION
**Pull request by yifuwang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #98233
* #98232
* #98231
* #98230
* __->__ #98229

The current logic assumes non-overload ops takes two arguments however torch.ops.aten.sym_numel takes one.

Differential Revision: [D44615037](https://our.internmc.facebook.com/intern/diff/D44615037/)

### CODE REVIEW

**Review by mrshenli — APPROVED** [review]
This one supersedes #98177

**Comment by yifuwang** [comment]
@yifuwang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44615037).

**Comment by yifuwang** [comment]
@yifuwang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44615037).

**Comment by yifuwang** [comment]
@yifuwang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44615037).

**Pull request closed without merging**
