### PR TITLE
Make PyTorch argparser understand complex

### LINKED ISSUE #126837: The problem of `dtype` and `device` parameter of `eye()`
### 🐛 Describe the bug

[The doc](https://pytorch.org/docs/stable/generated/torch.eye.html) of `eye()` explains the type of `dtype` parameter is [torch.dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype) as shown below:

> dtype ([torch.dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype), optional) ...

But `dtype` parameter can also accept [int()](https://docs.python.org/3/library/functions.html#int), [float()](https://docs.python.org/3/library/functions.html#float) and [bool()](https://docs.python.org/3/library/functions.html#bool) but not [complex()](https://docs.python.org/3/library/functions.html#complex) which are [python built-in functions](https://docs.python.org/3/library/functions.html) as shown below:

```python
import torch

torch.eye(n=3, dtype=int)
# tensor([[1, 0, 0],
#         [0, 1, 0],
#         [0, 0, 1]])

torch.eye(n=3, dtype=float)
# tensor([[1., 0., 0.],
#         [0., 1., 0.],
#         [0., 0., 1.]], dtype=torch.float64)

torch.eye(n=3, dtype=bool)
# tensor([[True, False, False],
#         [False, True, False],
#         [False, False, True]])

torch.eye(n=3, dtype=complex) # Error
```

And, [the doc](https://pytorch.org/docs/stable/generated/torch.eye.html) of `eye()` explains the type of `device` parameter is [torch.device](https://pytorch.org/docs/stable/tensor_attributes.html#torch.device) as shown below:

> device ([torch.device](https://pytorch.org/docs/stable/tensor_attributes.html#torch.device), optional) ...

But `dtype` parameter can also accept `str` and `int` as shown below:

```python
import torch

torch.eye(n=3, device='cuda:0')
torch.eye(n=3, device=0)
# tensor([[1., 0., 0.],
#         [0., 1., 0.],
#         [0., 0., 1.]], device='cuda:0')
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

cc @svekars @brycebortree @albanD

### PR DESCRIPTION
**Pull request by malfet**
It understands float and int, so why not `complex`.

Test plan: `python -c "import torch;print(torch.rand(3, dtype=complex))"`

Fixes https://github.com/pytorch/pytorch/issues/126837

cc @albanD

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Sure.

FYI @zou3519 who changes similar default value logic recently

**Review by zou3519 — COMMENTED** [review]
Can you add a test?

**Comment by malfet** [comment]
> Can you add a test?

Sure, but let me do it in a followup PR (as I could not find a good spot for it right now, this feature is not really tested anywhere)

**Pull request closed without merging**
