### PR TITLE
Update XLA pin

### PR DESCRIPTION
**Pull request by malfet**
To https://github.com/pytorch/xla/commit/8078b8f38cadea97d8fee0b88e53ee2c24b35078

Fixes regression caused by https://github.com/pytorch/pytorch/pull/120076

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by aakhundov — APPROVED** [review]

**Review by albanD — APPROVED** [review]
Thanks

**Comment by yeounoh** [comment]
If this fails xla, then we should revert to https://github.com/pytorch/pytorch/pull/121503 cc @malfet

**Pull request closed without merging**
