### PR TITLE
Added generator check for parametrize and ops

### LINKED ISSUE #81234: Guard against reused generators passed to test instantiation decorators
Code like this:

```
ref_ops_names = itertools.chain.from_iterable(
        [f"{path}.{op}" for op in module_all] for path, module_all in module_alls)

...

@parametrize("op", ref_ops_names)
    def test_refs_are_in_python_ref_db(self, op):
        if op in self.skip_ref_ops:
            raise unittest.SkipTest(f"{op} does not have an entry in python_ref_db")
        self.assertIn(op, self.ref_db_names)

@parametrize("op", ref_ops_names)
def test_refs_are_in_decomp_table(self, op):
```

is incorrect because the generator `ref_ops_names` is exhausted by the `@parametrize` decorator, so only one of these tests can be generated properly using it. We should add a test to ensure that generators aren't passed to decorators like `@parametrize` and `@ops`. 

cc @mruberry @jbschlosser

### PR DESCRIPTION
**Pull request by vitrioil**
Fixes #81234

### CODE REVIEW

**Comment by vitrioil** [comment]
FYI @mruberry this breaks functorch. So I created this: https://github.com/pytorch/functorch/pull/971

**Comment by vitrioil** [comment]
Not sure about why mobile check gives exit code 137.

**Review by jbschlosser — CHANGES_REQUESTED** [review]
@vitrioil Thanks for taking this on! I am of the opinion that adding a restriction against all generators is not the right thing to do here. Imo the issue regards invalid usage of generators, as reusing generators is essentially always wrong. We could still guard against this invalid usage by ensuring that the iterable is non-empty at test parametrization time (see my [comment](https://github.com/pytorch/pytorch/issues/81234#issuecomment-1189527630) on the issue). This would prevent breaking functorch and updating all the examples. Wdyt about this?

**Review by jbschlosser — COMMENTED** [review]
Looks pretty solid, just a minor suggestion to improve error message clarity. Thanks for the update!

**Review by jbschlosser — APPROVED** [review]
LGTM!

**Pull request closed without merging**
