### PR TITLE
Pin `sympy < 1.13.0a0`

### PR DESCRIPTION
**Pull request by XuehaiPan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #130140
* #130141
* #130144
* #130139
* __->__ #130836

`sympy` 1.13.0 introduces some breaking changes which break our tests. More specifically:

- Ref [Backwards compatibility breaks and deprecations](https://github.com/sympy/sympy/wiki/release-notes-for-1.13.0#backwards-compatibility-breaks-and-deprecations)

> BREAKING CHANGE: Float and Integer/Rational no longer compare equal with a == b. From now on Float(2.0) != Integer(2). Previously expressions involving Float would compare unequal e.g. x*2.0 != x*2 but an individual Float would compare equal to an Integer. In SymPy 1.7 a Float will always compare unequal to an Integer even if they have the same "value". Use sympy.numbers.int_valued(number) to test if a number is a concrete number with no decimal part. ([#25614](https://github.com/sympy/sympy/pull/25614) by [@smichr](https://github.com/smichr))

With `sympy` 1.12.1:

```python
In [1]: from torch.utils._sympy.functions import FloorDiv

In [2]: FloorDiv(1.0, 1.0)
Out[2]: (1.0//1.0)
```

```console
$ PYTORCH_TEST_WITH_DYNAMO=1 python test/test_sympy_utils.py
.........................................................................................s....................................................................
----------------------------------------------------------------------
Ran 158 tests in 15.362s

OK (skipped=1)
```

With `sympy` 1.13.0:

```python
In [1]: from torch.utils._sympy.functions import FloorDiv

In [2]: FloorDiv(1.0, 1.0)
RecursionError: maximum recursion depth exceeded
```

```console
$ PYTORCH_TEST_WITH_DYNAMO=1 python test/test_sympy_utils.py
.........................................................................................s....EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE....................................................F..........
======================================================================
...

======================================================================
ERROR: test_binary_ref_fn_floordiv_dtype_float (__main__.TestValueRanges.test_binary_ref_fn_floordiv_dtype_float) (a=9223372036854775807., b=9223372036854775807.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/PanXuehai/Projects/pytorch/test/test_sympy_utils.py", line 229, in test_binary_ref
    r = getattr(ValueRangeAnalysis, fn)(a, b)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/PanXuehai/Projects/pytorch/torch/utils/_sympy/value_ranges.py", line 564, in floordiv
    r = FloorDiv(x, y)
...
RecursionError: maximum recursion depth exceeded

======================================================================
FAIL: test_unary_ref_fn_square_dtype_float (__main__.TestValueRanges.test_unary_ref_fn_square_dtype_float) (v=0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/PanXuehai/Projects/pytorch/test/test_sympy_utils.py", line 210, in test_unary_ref
    self.assertEqual(ref_r, r.lower)
  File "/Users/PanXuehai/Projects/pytorch/torch/testing/_internal/common_utils.py", line 3721, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Object comparison failed: 0.0 != 0

----------------------------------------------------------------------
Ran 158 tests in 35.650s

FAILED (failures=1, errors=289, skipped=1)
```

See also:

- #130729

### CODE REVIEW

**Comment by Skylion007** [comment]
I'm pretty sure pinning this version will block Python 3.13 support

**Comment by XuehaiPan** [comment]
> I'm pretty sure pinning this version will block Python 3.13 support

I think we can upgrade the version after all the tests are fixed.

**Comment by XuehaiPan** [comment]
I'm also wondering why our CI does not capture this.

**Comment by albanD** [comment]
Ho yeah I was planning on pin sympy >= 1.13 in https://github.com/pytorch/pytorch/pull/130689 haha

What are the tests that need fixing for this? because the PR above that upgrades sympy does pass all CI.

**Comment by ezyang** [comment]
Yeah, I'd rather just take a PR that gets us working on 1.13

**Comment by XuehaiPan** [comment]
> What are the tests that need fixing for this? because the PR above that upgrades sympy does pass all CI.

See CI result for #130895.

> Yeah, I'd rather just take a PR that gets us working on 1.13

I will try that.

**Comment by XuehaiPan** [comment]
Closing this in favor of #130895.

- #130895

**Pull request closed without merging**
