### PR TITLE
[vmap] symintify : is_same_size and split_with_sizes

### PR DESCRIPTION
**Pull request by kshitij12345**
Partial : https://github.com/pytorch/pytorch/issues/111312

Reference: Point 1 of https://github.com/pytorch/pytorch/issues/111312#issuecomment-1769079147

Should this have a test?

cc @zou3519 @Chillee @samdow @janeyx99

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
I suspect you'll need to remove an xfail from somewhere, if not we might not have coverage of this function which would be unfortuante.

**Review by zou3519 — APPROVED** [review]

**Comment by zou3519** [comment]
> Should this have a test?

Nah it's fine

**Pull request closed without merging**
