### PR TITLE
Minor: fix a typo

### PR DESCRIPTION
**Pull request by FrankTianTT**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by kit1980** [comment]
Looks good, but please sign the CLA.

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
Please sign the CLA and we can merge

**Comment by FrankTianTT** [comment]
@Skylion007 @kit1980 OK!

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
