### PR TITLE
[Test] Add test for only_active flag

### PR DESCRIPTION
**Pull request by c-p-i-o**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #127042
* #128307
* __->__ #128191

Summary:
Add a unit test for the only_active flag to _dump_nccl_trace API call.
With this flag, we only expect active records to be returned.

Test Plan:
Unit test.

Reviewers:

Subscribers:

Tasks:

Tags:

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

### CODE REVIEW

**Review by d4l3k — APPROVED** [review]
LGTM

**Comment by c-p-i-o** [comment]
@pytorchbot merge -i 
The following failure is unrelated to this change. This change is adding a new unit test and the failing test is something different.
[pull / linux-jammy-py3.8-gcc11 / test (default, 1, 3, linux.2xlarge)](https://github.com/pytorch/pytorch/actions/runs/9470093027/job/26090865778)

**Pull request closed without merging**
