### PR TITLE
Update pybind11 to v2.10.1

### PR DESCRIPTION
**Pull request by Skylion007**
I am one of the maintainers of pybind11, and a frequent PyTorch user. We added quite a lot of bugfixes and performance improvements in 2.10.1 (see the changelog for full details) and I wanted to upstream them to PyTorch. 

Our releases is tested throughout Google's codebase including on their global builds of PyTorch so there should be no surprises.

The main new feature is optin in Eigen Tensor to Numpy casters.

### CODE REVIEW

**Review by soumith — APPROVED** [review]
awesome.

**Comment by Skylion007** [comment]
@soumith Looks like a flake during the install process to me.

**Pull request closed without merging**
