### PR TITLE
add `OpInfo` for `torch.nn.pixel_unshuffle`

### PR DESCRIPTION
**Pull request by pmeier**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #65681
* #65680
* #65469
* __->__ #65468
* #65467
* #65460

Differential Revision: [D31111699](https://our.internmc.facebook.com/intern/diff/D31111699)

cc @albanD @mruberry @jbschlosser @walterddr

### CODE REVIEW

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31111699).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31111699).

**Comment by zou3519** [comment]
Also: In the future, please feel free to combine multiple OpInfos that are similar (e.g. pixel_shuffle, pixel_unshuffle) into a single PR. This makes them easier to land and the total LOC count (as long as it's under ~100-200) should make it so that it's still easy to review.

**Comment by pmeier** [comment]
> feel free to combine multiple OpInfos that are similar (e.g. pixel_shuffle, pixel_unshuffle) into a single PR.

I got burned by that a few times, where such a PR started of as quite small, but turned out to be more complicated after the first reviews came in.

> This makes them easier to land

Is that the case? I was under the impression that landing stacks is as "easy" (whatever that means in FB infrastructure) as landing individual PRs. Thus, it should not make a difference if I combine multiple PRs in a stack into one, does it?

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
