### PR TITLE
deprecated datetime.utcnow() fix and _RendezvousJoinOp module initiation bug fix

### PR DESCRIPTION
**Pull request by AminAlam**
Fix to #136140

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Comment by XilunWu** [comment]
LGTM. One thing to note is the below files also contain `datetime.utcfromtimestamp`:
torch/fb/fx/graph_logger.py
benchmarks/operator_benchmark/fb/fetch_ops.py

**Review by kwen2501 — APPROVED** [review]
LGTM. If CI is happy, please go ahead and land it.

**Comment by AminAlam** [comment]
I could use some help with the tests. After applying Flake8 formatting changes to the Python files, a few C++ tests are now timing out and failing. Not sure how they’re related.
@XilunWu @janeyx99 @kwen2501

**Pull request closed without merging**
