### PR TITLE
[DSD] Correctly handle _extra_state (#125336)

### PR DESCRIPTION
**Pull request by mvpatel2000**
Pr for 2.3 cherry-pick

Summary:
distributed_state_dict should not try to use `getattr` to get `_extra_state` as this is not well-defined.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/125336
Approved by: https://github.com/LucasLLC
ghstack dependencies: #125333, #125501, #125334, #125335

Fixes #ISSUE_NUMBER

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @LucasLLC

### CODE REVIEW

**Review by fegin — APPROVED** [review]
Thanks for submitting the cherry pick.

**Review by atalman — APPROVED** [review]

**Comment by PaliC** [comment]
Validated this works for cpu on the 2.3 release branch

**Pull request merged**
