### PR TITLE
replace blackwhite in caffe2/opt/onnxifi_transformer.cc

### LINKED ISSUE #41704: Replace blacklist/whitelist in caffe2/opt/onnxifi_transformer.cc
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `caffe2/opt/onnxifi_transformer.cc`. See issue #41443 for more information.

### PR DESCRIPTION
**Pull request by admud**
Replaced white and black terms in caffe2/opt/onnxifi_transformer.cc

Fixes #41704

### CODE REVIEW

**Review by yinghai — CHANGES_REQUESTED** [review]
Please change the .cc and .h files in one PR

**Comment by muhdmud** [comment]
okay on it!

**Comment by muhdmud** [comment]
okay done! #41766

**Comment by yinghai** [comment]
Looks like you need to rebase and resolve the merge conflict.

**Comment by muhdmud** [comment]
oh this is a new thing for me, correct me if im wrong.

so i do i rebase the master and commit on top of that? 
or do i merge this 2 commits(.h and .cc) that i have here then i commit?

**Pull request closed without merging**
