### PR TITLE
Add Gaussian NLL Loss

### LINKED ISSUE #48520: Gaussian NLL loss
## 🚀 Feature
Gaussian negative log-likelihood loss, similar to issue #1774 (and solution pull #1779) 

## Motivation

The homoscedastic Gaussian loss is described in Equation 1 of this [paper](https://arxiv.org/pdf/1612.01474.pdf). The heteroscedastic version in Equation 2 [here](https://arxiv.org/pdf/2011.02838.pdf)  (ignoring the final anchoring loss term). These are both key to the uncertainty quantification techniques described. 

## Pitch

I'm happy to implement this, using the template of pull #1779. The implementation will allow for both homoscedastic and heteroscedastic losses.  

## Alternatives

An alternative would be to instantiate a Gaussian (https://pytorch.org/docs/stable/distributions.html#normal) and evaluate the log of this. However, this seems wasteful given a new Gaussian would be instantiated for every new function call for the best case (homoscedastic), and for every element of the output-target pairs in the worst case (heteroscedastic). 

## Additional context

Definitions: [homo/heteroscedasticity](https://en.wikipedia.org/wiki/Homoscedasticity) (wiki)

cc @albanD @mruberry

### PR DESCRIPTION
**Pull request by nailimixaM**
Fixes #48520.

cc @albanD (This is a clean retry PR #49807)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Looks great!
Could you just revert the tensorpipe submodule update please? (let me know if you want me to do it)

Will land when the submodule is fixed!

**Comment by nailimixaM** [comment]
> Looks great!
> Could you just revert the tensorpipe submodule update please? (let me know if you want me to do it)
> 
> Will land when the submodule is fixed!

Done, fingers crossed this works!

**Comment by albanD** [comment]
(rocm failures look unrelated)

**Comment by almson** [comment]
This feature is half-baked. Please see https://github.com/pytorch/pytorch/issues/53964

**Comment by nailimixaM** [comment]
@almson Thanks for your points. I've addressed these in #53964.

**Pull request closed without merging**
