### PR TITLE
Re-enable SGD

### PR DESCRIPTION
**Pull request by mlazos**
Re-enables the SGD optimizer now that compile times are more reasonable. [Benchmark run](https://github.com/pytorch/pytorch/actions/runs/7511073761)

cc @albanD @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]

**Comment by mlazos** [comment]
Skipping PR sanity checks because of autogenerated files

**Review by janeyx99 — APPROVED** [review]
woo! could you explain the changes in variables/optimizer.py? Is SGD the first optimizer to start handling lists of non Tensors?

**Review by janeyx99 — APPROVED** [review]
woo! could you explain the changes in variables/optimizer.py? Is SGD the first optimizer to start handling lists of non Tensors?

**Comment by mlazos** [comment]
> woo! could you explain the changes in variables/optimizer.py? Is SGD the first optimizer to start handling lists of non Tensors?

Yeah, weirdly. It was pretty surprising, but in the end we will get rid of that code (in a separate PR), I just wanted to enable SGD asap.

**Comment by lezcano** [comment]
@pytorchbot revert -m "breaks test_profiler.py when run with dynamo" -c nosignal

`PYTORCH_TEST_WITH_DYNAMO=1 pytest test/profiler/test_profiler.py -vk multiple_steppers` is one of the tests that are broken

**Comment by huydhn** [comment]
@mlazos I think there are some XLA tests failing after this change https://hud.pytorch.org/pytorch/pytorch/commit/f302a0d380cf2a6e8c2ae7e67c6859503a038cf7, i.e. `test_put_xla_bfloat16`.  The job has been marked as unstable, so we probably need a forward fix?

**Comment by mlazos** [comment]
> @mlazos I think there are some XLA tests failing after this change [hud.pytorch.org/pytorch/pytorch/commit/f302a0d380cf2a6e8c2ae7e67c6859503a038cf7](https://hud.pytorch.org/pytorch/pytorch/commit/f302a0d380cf2a6e8c2ae7e67c6859503a038cf7), i.e. `test_put_xla_bfloat16`. The job has been marked as unstable, so we probably need a forward fix?

Hmm let me see about this. It passed the XLA CI so maybe we need to update the PyTorch pin.

**Comment by huydhn** [comment]
Oh, the same failure also happens on this PR https://hud.pytorch.org/pr/117434, but the job has already been marked as unstable at that point while waiting for the pinned update, so it's kind of hidden.

**Pull request closed without merging**
