### PR TITLE
add new private operator copy-on-write torch._lazy_clone

### PR DESCRIPTION
**Pull request by dagitses**
add new private operator copy-on-write torch._lazy_clone

Summary:
This is an early access operator with some limitations. It will more
eagerly copy than desired because we haven't completed our audit
partitioning data pointer access between const_data_ptr and
mutable_data_ptr.

The idea is to add some logging when a copy is triggered to help
prioritize which operations will be audited and fixed.

Test Plan: Added a new unit test.

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/pytorch/pull/100821).
* __->__ #100821
* #100820

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

### CODE REVIEW

**Comment by cpuhrsch** [comment]
@dagitses - Great! I'll give this a spin either this or next week to see whether it helps NestedTensor. How do I best confirm that a copy was avoided? I assume within maybe_materialize in StorageImpl.h?

**Comment by dagitses** [comment]
> @dagitses - Great! I'll give this a spin either this or next week to see whether it helps NestedTensor. How do I best confirm that a copy was avoided? I assume within maybe_materialize in StorageImpl.h?
> 
> EDIT: [NestedTensor's backward for linear](https://github.com/pytorch/pytorch/blob/e762cce61ffb4bd53510cfc281d1c523df1c2d9b/aten/src/ATen/native/nested/NestedTensorBackward.cpp#LL60C1-L60C1) is an example where we clone by default and a lazy clone could be used.

I would put it inside materialize itself, since maybe_materialize is inlined. IMO, the ideal thing to do would be to log warning if we copy a tensor because of a call to `at::Tensor::data_ptr` and *also* to include the stack trace there. That would be awkward to do with the current code.

I'm happy to write that PR on top of this one.

Christian: do you or @ezyang know if it's possible to query the runtime/dispatcher if we are currently in an operator and what that operator's name is? If that were the case, we could just log the offending operator and fix it up.

I am quite confident that this will have *zero* benefit right now, but if we can find the offending operators, we could get this in a useful state quickly. Do you have any unit test that will trigger most of the operations you expect to occur on your lazy clone? If that is the case, I could probably iterate quickly on getting it there.

**Review by ezyang — APPROVED** [review]

**Comment by cpuhrsch** [comment]
@dagitses - The [NestedTensor unit tests](https://github.com/pytorch/pytorch/blob/main/test/test_nestedtensor.py) should exercise these clone calls.

I've had the same request about logging operator usage a while ago and ended up building [this construct (with some help)](https://github.com/pytorch/nestedtensor/blob/master/nestedtensor/csrc/nested_tensor_impl.h#L361-L389) out of tree. In core however there should be a way to do this [within the dispatcher itself](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/core/dispatch/Dispatcher.cpp). I'd throw an exception within an operator and look through the stack trace. Some function here has to be called on each dispatch I assume, which could probably be used to log this?

**Comment by dagitses** [comment]
> @dagitses - The [NestedTensor unit tests](https://github.com/pytorch/pytorch/blob/main/test/test_nestedtensor.py) should exercise these clone calls.
> 
> I've had the same request about logging operator usage a while ago and ended up building [this construct (with some help)](https://github.com/pytorch/nestedtensor/blob/master/nestedtensor/csrc/nested_tensor_impl.h#L361-L389) out of tree. In core however there should be a way to do this [within the dispatcher itself](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/core/dispatch/Dispatcher.cpp). I'd throw an exception within an operator and look through the stack trace. Some function here has to be called on each dispatch I assume, which could probably be used to log this?

Well if I can just use the unit tests, I can probably squash these with good old fashioned CHECK. Doing something more sophisticated would be helpful if we want to have detailed logging of this for a longer time horizon.

I think if we can just get the unit tests not cloning and then add a simple log message indicating if we clone unexpectedly in production use-cases we'll know to dive in on demand.

**Comment by ezyang** [comment]
The most reliable way at the moment is to get the cpp trace using https://dev-discuss.pytorch.org/t/fast-combined-c-python-torchscript-inductor-tracebacks/1158/3

**Comment by kurtamohler** [comment]
Replaced by #113397

**Pull request closed without merging**
