### PR TITLE
no ios arm builds on circleci

### PR DESCRIPTION
**Pull request by clee2000**
Get rid of ios arm builds on circleci b/c most people dont have these permissions and they make the job show up as failing/red.

Next step is to see if we can do only builds since they might not require credentials

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
Seems okay if the next step is to add them back without the test part

**Review by malfet — APPROVED** [review]
LGTM, but do you mind just commenting out the section in job definition, rather than deleting it?

**Pull request closed without merging**
