### PR TITLE
[SparseCsr] Remove triton sdpa skip after triton pin update

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #109601

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by davidberard98** [comment]
I just launched nightly perf run for this cc @Chillee

**Comment by amjames** [comment]
@peterbell10 could you also remove [this skip](https://github.com/pytorch/pytorch/blob/ea20db8aa0d0e7d8812868cb75a58494b55abfae/test/test_sparse_csr.py#L3588C17-L3588C17) It was added in the most recent pin update, and a fix has been landed in triton upstream and this PR moves the pin past that point, so it should be removed.

**Review by desertfire — APPROVED** [review]

**Review by davidberard98 — CHANGES_REQUESTED** [review]
can we switch it back to `ed5a53057d39358dc857dcefd73415a6da9a2e25` as I have been running the internal test on this commit?

**Comment by peterbell10** [comment]
@davidberard98 `ed5a53057d39358dc857dcefd73415a6da9a2e25` doesn't include openai/triton#2376 which I need for the rest of this stack. I could split this out from the stack and open a new PR for the newer commit if you prefer though.

**Comment by davidberard98** [comment]
@peterbell10 are you still seeing the accuracy regressions after updating past the fix? I've been seeing accuracy regressions internally, wondering if it's could be the same issue

**Review by amjames — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change, but it is failing in trunk with this error ZeroDivisionError: integer division or modulo by zero' -c weird

An example commit with failures https://hud.pytorch.org/pytorch/pytorch/commit/898554a3a3ee039a2f6eed4113b06fcafee5dc59

**Review by amjames — APPROVED** [review]

**Pull request closed without merging**
