### PR TITLE
[BE][Ez]: Add full half/bfloat16 dtype for `unique` and `isin`

### LINKED ISSUE #136090: Tensor `isin` and `unique` missing bfloat16 support and half support on CPU
### 🚀 The feature, motivation and pitch

Noticed this odd gap in coverage when looking at optests: https://github.com/CaoE/pytorch/blob/a1394be10096b91c0b5528fccf709e6e73078832/torch/testing/_internal/common_methods_invocations.py#L13575C1-L13576C1

Not sure why we don't have kernels build here for bfloat16 (or more types in CPU for that matter).

* This blocked by lack of GPU support for bfloat16 for unique, so I also added that in my fix PR

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Skylion007**
Fixes #136090 

* Add support for isin to tensor half dtypes for CPU (just add a few extra dispatches).
* Seems like the CUDA implementation for bfloat16 was mostly compiled and available all along (it just calls sort internally AND unique). To enable it, we just need to remove an assert to access it (since sort's functionality was updated since the assert was added) and add missing dtype support to unique. 
* This unlocks more GPU functionality with minimal code bloat. I also added CPU kernels for the dtypes for parity.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by Skylion007** [comment]
Looks like we are missing one more kernel (bfloat16 for unique).

**Review by eqy — COMMENTED** [review]
Are we missing instantiations here https://github.com/pytorch/pytorch/blob/d2207c57f717442a67efad8c3fae41a62ad2bac3/aten/src/ATen/cuda/cub-RadixSortKeys.cu#L53 ?

**Pull request closed without merging**
