### PR TITLE
update kineto submodule

### PR DESCRIPTION
**Pull request by jeffdaily**
Rework roctracer shutdown flushing

https://github.com/pytorch/kineto/commit/9365c1aa09225a6419df957093ba282fb935db1c

This fixes flaky unit tests that use kineto to verify certain kernels have executed.

### CODE REVIEW

**Comment by jeffdaily** [comment]
@malfet or @huydhn, this PR should help with any test flakiness for tests that rely on profiler to examine which kernels have run.

**Review by malfet — APPROVED** [review]

**Review by atalman — APPROVED** [review]

**Pull request closed without merging**
