### PR TITLE
Enabled gloo backend in test_distributed unit tests for ROCm

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@mrshenli Could you please review and merge if this looks okay?

**Comment by jeffdaily** [comment]
@mrshenli ping for review.  CI fully passes.

**Comment by jeffdaily** [comment]
@mrshenli ping again for review.  Or @malfet?  Anybody.  Thanks.

**Review by mrshenli — APPROVED** [review]

**Comment by mrshenli** [comment]
sorry about the delay, importing :)

**Pull request closed without merging**
