### PR TITLE
Do not pull in _autocast_* ops into NNC

### PR DESCRIPTION
**Pull request by EikanWang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #85140
* #84402

The AMP inserts `_autocast_to_reduced_precision` and `_autocast_to_full_precision` automatically. The aten implementation provides a fast path to bypass the conversion if the tensor data type has been the reduced/full precision. But NNC always does the conversion which could bring >5% E2E performance regression.

This PR is to address the performance issue like aten. We will not pull `_autocast_to_reduced_precision` and `_autocast_to_full_precision` into NNC fusion group and fallback to aten to trigger its fast path if the tensor data type has been the reduced/full precision.

### CODE REVIEW

**Comment by frank-wei** [comment]
@EikanWang  do you discard this PR?

**Comment by EikanWang** [comment]
@frank-wei , this PR was unexpectedly closed by another colleague. I reopen it.

**Review by frank-wei — APPROVED** [review]
@pytorchbot merge -l

**Pull request closed without merging**
