### PR TITLE
Add type hint to torch.norm and Tensor.norm

### LINKED ISSUE #89727: [typing] torch.norm and Tensor.norm `p` type hint
### 🐛 Describe the bug

`torch.norm` and `Tensor.norm` as `p="fro"` as default argument, thus is considered as `str` by `mypy` and other type checks solutions.
I suggest adding type hints to solve this.

### Versions

master, 1.13

cc @ezyang @malfet @rgommers @xuzhao9 @gramster @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

### PR DESCRIPTION
**Pull request by fd0r**
Fixes #89727

### CODE REVIEW

**Comment by jlukehubbard** [comment]
https://github.com/pytorch/pytorch/blob/1d6a188d08829b1aee28eb1e6255d5bf43a77f16/torch/functional.py#L1390#L1400

Please use one of the functions provided in `torch.linalg`. `torch.norm` is deprecated.

**Comment by kit1980** [comment]
`torch.norm` is deprecated, but still good to fix the types.

**Review by kit1980 — APPROVED** [review]

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
@fd0r can you fix lint issues?

**Comment by fd0r** [comment]
I edited the style using `lintrunner -m master` as per the documentation.

**Pull request closed without merging**
