### PR TITLE
add torch.device to python type

### LINKED ISSUE #107856: dynamo failed to handle "isinstance" builtin function with variable device
### 🐛 Describe the bug

```
import torch
import torch._dynamo

device = torch.device("cpu")

def my_func(target):
    target_device = target.device
    assert isinstance(target_device, torch.device)
    a = torch.zeros(2, 3, device=target_device)
    b = torch.zeros(2, 3, device=target_device)
    c = torch.zeros(2, 3, device=target_device)
    return a + b + c

opt_func = torch._dynamo.optimize("inductor")(my_func)

a = torch.tensor([2, 3], device=device)
res = opt_func(a)
```

Dynamo VariableTracker can't handle device variable in "python_type" method. When I run the above code, it reports error.
image

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git11e3669
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.0
Libc version: glibc-2.27

Python version: 3.8.0 (default, Dec  9 2021, 17:53:27)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           16
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz
Stepping:            7
CPU MHz:             2793.437
BogoMIPS:            5586.87
Virtualization:      VT-x
Hypervisor vendor:   VMware
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            22528K
NUMA node0 CPU(s):   0-15
NUMA node1 CPU(s):   16-31
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xsaves arat pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.1.0a0+git11e3669
[pip3] torch-npu==1.11.0
[pip3] torchvision==0.15.2
[conda] Could not collect

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

### PR DESCRIPTION
**Pull request by Aashishthakur10**
Fixes #107856

This PR adds torch.device instance check in the python_type method for torch variables in dynamo. 

@ezyang 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @anijain2305

### CODE REVIEW

**Review by msaroufim — CHANGES_REQUESTED** [review]
could you also please add a test similar to the user reported error here https://github.com/pytorch/pytorch/issues/107856#issue-1864620320

You can put your test here https://github.com/pytorch/pytorch/tree/main/test/dynamo repro or misc are two good files probably

Holler at me again once you get a test passing!

**Comment by Aashishthakur10** [comment]
@msaroufim Added a test for the changes, worked locally, so hopeful that it will go through. Let me know in case I should add anything else to the test.

**Comment by msaroufim** [comment]
Cool! Thank you!

**Review by msaroufim — APPROVED** [review]

**Comment by msaroufim** [comment]
Hey @BowenBao @thiagocrepaldi this PR is failing some ORT tests, any concerns you have from this PR?

**Comment by BowenBao** [comment]
cc @wschin regarding ort tensor/device

**Comment by Aashishthakur10** [comment]
> Hey @BowenBao @thiagocrepaldi this PR is failing some ORT tests, any concerns you have from this PR?
> 
> FWIW @Aashishthakur10 the error does look legit so worth seeing what's up with the failing tests

Sure, I will take a look into it. ORT is ONNX Runtime? If you have some recommendations regarding documentation for it, please let me know

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
I think this PR is correct but it looks like you are hitting another latent bug with the dynamo CI failures. You have two choices: you can try to investigate what the root cause of these failures is and fix that at the same time; or you could skip those tests under Dynamo config using skipIfTorchDynamo (file an issue for the problem and link it here)

**Comment by Aashishthakur10** [comment]
Investigating the root cause today

**Comment by Aashishthakur10** [comment]
@ezyang @msaroufim 
I am trying to run the test in my local linux machine, but the pytest/python commands for it aren't working
```
PYTORCH_TEST_WITH_DYNAMO=1 python test/test_cpp_extensions_aot.py -k test_zeros
/home/aashish/Desktop/pytorch/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xe (Triggered internally at /home/aashish/Desktop/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Traceback (most recent call last):
  File "/home/aashish/Desktop/pytorch/test/test_cpp_extensions_aot.py", line 26, in <module>
    cpp_extension = pytest.importorskip("torch_test_cpp_extension.cpp")
  File "/home/aashish/anaconda3/lib/python3.9/site-packages/_pytest/outcomes.py", line 296, in importorskip
    raise Skipped(reason, allow_module_level=True) from None
Skipped: could not import 'torch_test_cpp_extension.cpp': No module named 'torch_test_cpp_extension'
```

So, I am running it using 
```
python run_test.py  -i test_cpp_extensions_aot_no_ninja -k test_zeros
```
I am wondering if that's the right way, as it's taking a while to execute. Please let me know in case that's incorrect.

**Comment by Aashishthakur10** [comment]
So, looks like without dynamo, 
`b = torch.empty(5, 5, device='ort')` has a device type of `torch.device('ort', 0)`
But perhaps due to my changes, it has a device type of `torch.device('ort')` now.  Since the tests create object pairs for assertion, it's failing for Dynamo. 
I am looking into how the `torch.empty` is initialized, which I believe happens in c++. 
Locally, it is passing without my changes because the `TorchVariable() has no type` gets suppressed.
@ezyang

**Comment by ezyang** [comment]
This makes sense. I don't know exactly where Dynamo is messing it up, but it is totally believable to me that there is some subtle distinction between index 0 and index unset and Dynamo didn't get the distinction right.

There are probably not that many places where the bug can happen, since you have such a small repro. I would look at the logic for constructing device variable tracker in dynamo, probably it is eagerly setting the index when it shouldn't.

**Comment by Aashishthakur10** [comment]
Great, thanks for the recommendation. I was quite lost as the codebase is massive, so this helps!

**Comment by Aashishthakur10** [comment]
Alright, so after debugging it all the way from the `call_function in torch.py` till the device is set, I found that when the builder calls a fake tensor as show below:
`example_value = get_fake_value(proxy.node, tx)`
it calls 
`lambda: run_node(tx.output, node, args, kwargs, nnmodule)`
Now, this is where it  leads to the cpp methods to get an overloadpacket for `aten::empty` in `_ops.py:757` 
`op, overload_names = torch._C._jit_get_operation(qualified_op_name)`
So, the device is initialized from cpp, which seems like non-dynamo codebase in c++ to me. Do you think I am looking in the wrong direction @ezyang? 
Or should I be looking into the c++ code here?

**Comment by ezyang** [comment]
OK, I agree with your diagnosis. Let's skip these tests for Dynamo.

**Pull request closed without merging**
