### PR TITLE
Disable PIP version check in collect_env

### PR DESCRIPTION
**Pull request by Flamefire**
Disables version check which might require users to reach out to PyPI, reference: https://pip.pypa.io/en/latest/cli/pip/#cmdoption-disable-pip-version-check

Switches pip to be used directly as a python module (`python3 -mpip`) instead of relying on `pip3` or `pip`

### CODE REVIEW

**Comment by janeyx99** [comment]
why this change?

**Comment by Flamefire** [comment]
> why this change?

Without this running the script will involve access to the internet (PyPI) and writing to the users $HOME directory which is not required and easily avoided.

**Review by seemethere — APPROVED** [review]
LGTM

**Pull request closed without merging**
