### PR TITLE
[fix] derandomize hypothesis tests

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#25513 [fix] derandomize hypothesis tests**

Summary:
Randomized tests are flaky, this PR derandomized some of them

Test Plan:
python test/test_fake_quant.py
python test/test_quantized_nn_mods.py

Reviewers:
pt1quant
Subscribers:

Tasks:

Tags:

Differential Revision: [D17221273](https://our.internmc.facebook.com/intern/diff/D17221273)

### CODE REVIEW

**Review by ezyang — CHANGES_REQUESTED** [review]
This is not a sustainable solution, because it requires every user of hypothesis tests to remember to apply this decorator (which they will not). Is there any way to turn on derandomization globally? That would be a better way.

**Comment by jerryzh168** [comment]
I think we'll need to do it in CI settings: https://hypothesis.readthedocs.io/en/latest/settings.html#building-settings-objects

**Comment by jerryzh168** [comment]
@ezyang why can't we import hypothesis in run_test.py?
```
 Sep 03 20:15:29 ModuleNotFoundError: No module named 'hypothesis'
```

**Comment by ezyang** [comment]
The most obvious explanation is hypothesis is not installed in that environment. You can download the Docker image and check.

**Comment by ezyang** [comment]
How did you test that this worked?

**Comment by jerryzh168** [comment]
> How did you test that this worked?

test in ci :) it's a ci change...

**Comment by ezyang** [comment]
But, like, how do I know you didn't just get lucky and none of the flaky tests flaked?

**Comment by jerryzh168** [comment]
@ezyang we can run it multiple times to see if the flaky tests comes up again, or rebase the diff that has flaky tests on this one and see if it solves the problem. but in general I don't see a very easy way to test this.

**Comment by ezyang** [comment]
If it were me, I would run the test by hand multiple times and inspect the passed in inputs and see if they are the same or not.

**Comment by jerryzh168** [comment]
@ezyang I tested locally by running run_test.py and find that the tests are not randomized, I find the in run_test.py every time we are starting a new python process to run the test, and hypothesis setting is a run time object, so I think there is no way we can do this globally. shall we switch back to the decorator?

**Comment by ezyang** [comment]
Can't you turn off randomization in one of our common test files, like `test_common.py`?

Another flaky test: https://circleci.com/gh/pytorch/pytorch/2676674?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jerryzh168** [comment]
Yeah, that is what I plan to do

**Review by ezyang — APPROVED** [review]
Looks reasonable, I guess? Did you test that it worked?

**Comment by jerryzh168** [comment]
Yes, checked numerical_consistency test in test_fake_quant locally with pytorch_ci profile and derandomize is set to True.

**Comment by jerryzh168** [comment]
going to do 'try import' again for hypothesis.

**Pull request closed without merging**
