### PR TITLE
[ROCm] Fix unit test: matmul_offline_mgpu_tunableop

### LINKED ISSUE #141652: DISABLED test_matmul_offline_mgpu_tunableop_cuda_float32 (__main__.TestLinalgCUDA)
Platforms: rocm

This test was disabled because it is failing in CI. See [recent examples](https://hud.pytorch.org/flakytest?name=test_matmul_offline_mgpu_tunableop_cuda_float32&suite=TestLinalgCUDA&limit=100) and the most recent trunk [workflow logs](https://github.com/pytorch/pytorch/runs/33569763876).

Over the past 3 hours, it has been determined flaky in 3 workflow(s) with 10 failures and 3 successes.

**Debugging instructions (after clicking on the recent samples link):**
DO NOT ASSUME THINGS ARE OKAY IF THE CI IS GREEN. We now shield flaky tests from developers so CI will thus be green but it will be harder to parse the logs.
To find relevant log snippets:
1. Click on the workflow logs linked above
2. Click on the Test step of the job so that it is expanded. Otherwise, the grepping will not work.
3. Grep for `test_matmul_offline_mgpu_tunableop_cuda_float32`
4. There should be several instances run (as flaky tests are rerun in CI) from which you can study the logs.

<details><summary>Sample error message</summary>

```
Traceback (most recent call last):
  File "/var/lib/jenkins/pytorch/test/test_linalg.py", line 4730, in test_matmul_offline_mgpu_tunableop
    torch.cuda.tunable.mgpu_tune_gemm_in_file(untuned_filename, total_gpus)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/tunable.py", line 520, in mgpu_tune_gemm_in_file
    _gather_tunableop_results()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/tunable.py", line 355, in _gather_tunableop_results
    shutil.copy(output_file, duplicate_file)
  File "/opt/conda/envs/py_3.10/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/envs/py_3.10/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpj5_9w51v/tunableop_results_full1.csv'
```

</details>

Test file path: `test_linalg.py`

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @clee2000 @wdvr @jianyuh @nikitaved @pearu @mruberry @walterddr @xwang233 @Lezcano

### PR DESCRIPTION
**Pull request by naromero77amd**
Fixes #141652 

This PR contains:

- Fix for `matmul_offline_mgpu_tunableop`
- Modifications to _checking_tuning_assertions to enable TunableOp if it is disabled. Also moved it into the concurrent futures initializer.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by jeffdaily — APPROVED** [review]

**Comment by naromero77amd** [comment]
Confirming that test ran successfully in this shard `linux-focal-rocm6.2-py3.10 / test (distributed, 1, 3, linux.rocm.gpu, module:rocm, oncall:distributed)`
```
Executing ['/opt/conda/envs/py_3.10/bin/python', '-bb', 'test_linalg.py', '--shard-id=1', '--num-shards=1', '-v', '-vv', '-rfEX', '-p', 'no:xdist', '--use-pytest', '-k', 'test_matmul_offline_mgpu_tunable', '-x', '--reruns=2', '--import-slow-tests', '--import-disabled-tests'] ... [2024-12-19 11:41:49.454102]

test_linalg 1/1 was successful, full logs can be found in artifacts with path test/test-reports/test_linalg_1.1_7239d0bf7c166591_.log
Running 1 items in this shard: test/test_linalg.py::TestLinalgCUDA::test_matmul_offline_mgpu_tunableop_cuda_float32
```

Other failures are unrelated, since this test is ROCm only.

**Pull request closed without merging**
