### PR TITLE
Try removing indexing limitation from templates

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #130308
* #130250
* #130227
* #130224
* #130106
* #130160

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by peterbell10 — CHANGES_REQUESTED** [review]
I don't think this will work. Most templates use `tl.program_id` and `tl.arange` directly which return 32-bit ints, whereas our triton codegen explicitly converts these to 64-bit indexing when the `index_dtype` is set to 64-bit.

**Comment by Chillee** [comment]
@peterbell10 Why is this a problem? If it's part of the template code then I consider that just an issue with the template?

Do you think the right thing to do is to expose a "NEEDS_64BIT_INDEXING" kwarg to the template that it can guard on?

**Comment by peterbell10** [comment]
> Why is this a problem? If it's part of the template code then I consider that just an issue with the template?

Technically this is true, but practically it means all the templates we have today are probably broken and need to be fixed.

> Do you think the right thing to do is to expose a "NEEDS_64BIT_INDEXING" kwarg to the template that it can guard on?

I guess the simplest thing would be to add `INDEX_DTYPE` to the template env.

**Comment by peterbell10** [comment]
You could maybe add a parameter `supports_64bit_index=False` and just set it to true on the template you care about.

**Pull request closed without merging**
