### PR TITLE
[LTC] Implement `full_codegen` for ops with overloaded names

### PR DESCRIPTION
**Pull request by ramiro050**
Adds `full_codegen` support for ops that have overloaded names. This PR also adds codegen support for `bitwise_and` (which has overloaded names `bitwise_and.Tensor` and `bitwise_and.Scalar`) to test the implementation.

The main changes to the codegen are in the way dispatch is done in `LazyTsLowering.cpp`. If more than one overloaded function is identified, the dispatch is done using `dynamic_cast`. For example, for `bitwise_and`, the following code is generated in `LazyTsLowering.cpp`.

```cpp
case at::aten::bitwise_and: {
    if (dynamic_cast<const ir::ops::BitwiseAndTensor*>(node)) {
      return LowerBitwiseAndTensor(function, loctx,
          ir::NodeCast<ir::ops::BitwiseAndTensor>(node, ir::OpKind(at::aten::bitwise_and)));
    }
    if (dynamic_cast<const ir::ops::BitwiseAndScalar*>(node)) {
      return LowerBitwiseAndScalar(function, loctx,
          ir::NodeCast<ir::ops::BitwiseAndScalar>(node, ir::OpKind(at::aten::bitwise_and)));
    }
}
```

The `bitwise_and` lowering was verified with the following script:

```python
import torch
import lazy_tensor_core as ltc
from lazy_tensor_core.debug import metrics

ltc._LAZYC._ltc_init_ts_backend()
device = 'lazy'
dtype = torch.int

x = torch.ones((2,3,4), device=device, dtype=dtype)
y = torch.zeros((2,3,4), device=device, dtype=dtype)

def computation(x,y):
    return torch.bitwise_and(x, torch.bitwise_and(y, 1))

print(computation(x, y))
print(metrics.metrics_report())
```

Output:

```
tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]], device='lazy:0', dtype=torch.int32)
Metric: DeviceLockWait
  TotalSamples: 30
  Accumulator: 017.800us
  ValueRate: 539.588us / second
  Rate: 909.417 / second
  Percentiles: 1%=000.430us; 5%=000.466us; 10%=000.478us; 20%=000.503us; 50%=000.564us; 80%=000.626us; 90%=000.694us; 95%=000.735us; 99%=001.503us
Metric: TensorsGraphSize
  TotalSamples: 30
  Accumulator: 276.00
  ValueRate: 10767.63 / second
  Rate: 1170.39 / second
  Percentiles: 1%=9.00; 5%=9.00; 10%=9.00; 20%=9.00; 50%=9.00; 80%=10.00; 90%=10.00; 95%=10.00; 99%=10.00
Counter: CreateLtcTensor
  Value: 69
Counter: DestroyLtcTensor
  Value: 67
Counter: UncachedCompile
  Value: 30
Counter: aten::_local_scalar_dense
  Value: 24
Counter: lazy::_copy_from
  Value: 30
Counter: lazy::bitwise_and
  Value: 2
Counter: lazy::fill_
  Value: 1
Counter: lazy::select
  Value: 32
Counter: lazy::view
  Value: 1
Counter: lazy::zero_
  Value: 1
```

Would love any feedback on this!

### CODE REVIEW

**Comment by ramiro050** [comment]
To put it another way, the issue is that the overloaded ops (`bitwise_and.Tensor` and `bitwise_and.Scalar`, as an example) have to be treated as two independent functions for all the codegen since each needs its own `Lower` function, its own class, etc, except during the dispatch because overloaded ops share the same `aten` op.

Therefore, grouping has to happen at some point, and I found grouping before generating the dispatch code to be the most natural place.

**Comment by wconstab** [comment]
> ... except during the dispatch because overloaded ops share the same aten op.
Therefore, grouping has to happen at some point, and I found grouping before generating the dispatch code to be the most natural place.

I'm trying to check on this part.  Are you referring to functions like these, in the Register{backend}.cpp file?  To make it more concrete, I ran the codegen on the existing pytorch/xla side, which generates the following for bitwise_and:


`m.impl("bitwise_and.Tensor", TORCH_FN(wrapper_Tensor_bitwise_and));`
`m.impl("bitwise_and.Scalar", TORCH_FN(wrapper_Scalar_bitwise_and));`

`at::Tensor bitwise_and(const at::Tensor &self, const at::Tensor &other) {
  return wrapper_Tensor_bitwise_and(self, other);
}`
`at::Tensor bitwise_and(const at::Tensor &self, const at::Scalar &other) {
  return wrapper_Scalar_bitwise_and(self, other);
}`

`at::Tensor wrapper_Tensor_bitwise_and(const at::Tensor &self,
                                      const at::Tensor &other) {
  return torch_xla::XLANativeFunctions::bitwise_and(self, other);
}`
`at::Tensor wrapper_Scalar_bitwise_and(const at::Tensor &self,
                                      const at::Scalar &other) {
  return torch_xla::XLANativeFunctions::bitwise_and(self, other);
}`

It seems to me like every step of the way, the codegen generates a separate version of the function for each overload, and I can't see why it would be necessary to 'group' them, or keep track of state.

Note: it's true that for both the Scalar and Tensor version, it generates some code that comes out looking the same:
`return torch_xla::XLANativeFunctions::bitwise_and(self, other);` - but can't this be achieved just be using functional logic to determine what the 'aten' name (`bitwise_and`) is?

**Review by alanwaketan — COMMENTED** [review]
Overall, LTGM. Thanks for improving the code-gen mechanism!

One more thing to notice:
1. Normally, we would love to have test plan in the commit message, like:
`test/cpp/build/test_ptltc --gtest_filter=AtenLtcTsTensorTest.TestBitwiseAnd*`
AtenLtcTsTensorTest is the ops test that we have for LTC.

**Comment by ramiro050** [comment]
I've rebased, updated the commit message to include a summary and test plan, and I removed the changes to `context.py`. Let me know if anything else is needed!

**Review by alanwaketan — APPROVED** [review]
LGTM. Thanks for contributing to LTC.

**Pull request merged**
