### PR TITLE
Add TorchFix to the CI

### PR DESCRIPTION
**Pull request by kit1980**
Enable flake8 plugin for https://github.com/pytorch/test-infra/tree/main/tools/torchfix - TorchFix 0.1.1.
Disable TorchFix codes that don't make sense for PyTorch itself.
Update deprecated TorchVision APIs to make TorchFix pass.

### CODE REVIEW

**Comment by Skylion007** [comment]
A metapoint, we should consider upstreaming torchfix to ruff at some point. Ruff already has bindings for libcst so it should be pretty straightforward.

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
Doesn't torchfix have limited autofix ability? Should we make it's own wrapper so it can actually apply those autofixes?

**Comment by kit1980** [comment]
> A metapoint, we should consider upstreaming torchfix to ruff at some point. Ruff already has bindings for libcst so it should be pretty straightforward.

Yeah, I was thinking about that. If someone from ruff community wants to port the rules to ruff - that would be great.

TorchFix itself is going to be developed in Python in the foreseeable future: development velocity for the current team, alignment with the PyTorch's language, flake8 compatibility.
Also TorchFix will eventually have more PyTorch-specific parts in the interface.

**Comment by kit1980** [comment]
> Doesn't torchfix have limited autofix ability? Should we make it's own wrapper so it can actually apply those autofixes?

Autofixes parts are a bit rough now. And autofixes only available in a standalone mode, not as flake8-plugin, which has limited configuration options currently so can not be used in CI.

**Review by malfet — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
