### PR TITLE
Use CAFFE2_USE_MSVC_STATIC_RUNTIME to determine when to avoid waiting for global destructors on Windows

### LINKED ISSUE #44470: Hang when compiling static libs on windows
## 🐛 Bug

Currently, there is a hang mentioned [here](https://github.com/pytorch/pytorch/blob/54c05fa34e1fbbb5096746a8ae92e27a08116de4/torch/csrc/autograd/engine.cpp#L228) that can still happen if you build libtorch statically on windows, but then bundle it into a DLL. I think this can be solved by having compiler flag allowing us to link against the DLL runtime, even when compiling statically, though I am no expert here and could be missing something. In fact, there is already a build flag (`CAFFE2_USE_MSVC_STATIC_RUNTIME`) that does that. I made a [PR](https://github.com/pytorch/pytorch/pull/43532) that is not quite right because it doesn't convert the cmake flag into a compiler flag, but no one has responded on the PR. 

## To Reproduce

Run build_libtorch.py with BUILD_SHARED_LIBS=OFF, then link the resulting library into a DLL. A process that runs training will not terminate.

## Expected behavior

Process should terminate. 

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

### PR DESCRIPTION
**Pull request by adampauls**
We are trying to build libtorch statically (BUILD_SHARED_LIBS=OFF) then link it into a DLL. Our setup hits the infinite loop mentioned [here](https://github.com/pytorch/pytorch/blob/54c05fa34e1fbbb5096746a8ae92e27a08116de4/torch/csrc/autograd/engine.cpp#L228) because we build with `BUILD_SHARED_LIBS=OFF` but still link it all into a DLL at the end of the day.

This PR fixes the issue by changing the condition to guard on which windows runtime the build links against using the `CAFFE2_USE_MSVC_STATIC_RUNTIME` flag. `CAFFE2_USE_MSVC_STATIC_RUNTIME` defaults to ON when `BUILD_SHARED_LIBS=OFF`, so backwards compatibility is maintained.

I'm not entirely confident I understand the subtleties of the windows runtime versus linking setup, but this setup works for us and should not affect the existing builds.

Fixes #44470

### CODE REVIEW

**Comment by peterjc123** [comment]
Is `CAFFE2_USE_MSVC_STATIC_RUNTIME` passed as a macro to c++ source files?

**Comment by adampauls** [comment]
I'm very sorry, you're completely right. This is probably only working for us locally because that macro is not defined no matter what, and so the problematic code is never compiled. I will happily make the changes to plumb it through if this solution is indeed the right one.

**Comment by adampauls** [comment]
Following up: what action should I take here? Is there some other path to getting a fix like this in?

**Comment by peterjc123** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019

Actually you don't have to create a new cmake variable for doing that, just use the builtib macros of MSVC.

**Comment by peterjc123** [comment]
In order to expose this flag to the sources, you can refer to https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L295-L299.

**Comment by adampauls** [comment]
Thanks, I was just waiting in confirmation that this was the right way to fix the problem. Happy to finish of the plumbing.

**Comment by peterjc123** [comment]
@adampauls It seems that changes are working. Would you please remove the debugging code?

**Comment by adampauls** [comment]
Sorry for the delay. I have removed the debugging code and verified that the plumbing is working as expected.

**Comment by adampauls** [comment]
Friendly bump, anything else I can do here?

**Comment by albanD** [comment]
The PR looks good.
Can you rebase to make sure the CI is passing fine?

**Comment by adampauls** [comment]
Done

**Comment by albanD** [comment]
@peterjc123 is this ready to merge? The CI failures are due to flaky homebrew connection.

**Review by peterjc123 — APPROVED** [review]
LGTM

**Comment by peterjc123** [comment]
@albanD Let's land this pr.

**Pull request closed without merging**
