### PR TITLE
fix torch.ops.aten.stride.default for dynamic shapes

### PR DESCRIPTION
**Pull request by bdhirsh**
Fixes `torch.ops.aten.stride`, to mirror the way that we handle `torch.ops.aten.size`.

There are actually 3 overloads:

`aten::stride.int -> int` lives in `native_functions.yaml`
`aten::stride.Dimname -> int` lives in `native_functions.yaml`

(**new in the PR**) `aten::stride -> int[]` directly created in `register_prim_ops.cpp`, similar to `aten::size -> int[]`.

This is needed to get `stride()` working with dynamic shapes.

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #81302
* #81301
* #81238
* #81236
* #81300
* __->__ #81237

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM

**Comment by ezyang** [comment]
You should rebase past https://github.com/pytorch/pytorch/pull/82083

**Comment by bdhirsh** [comment]
welp yep, I'll just remove this pR

**Comment by ezyang** [comment]
Your PR may be more complete than mine lol

**Pull request closed without merging**
