### PR TITLE
Use NNPACK for strided convolutions.

### PR DESCRIPTION
**Pull request by AshkanAliabadi**
Use NNPACK for strided convolutions.

ResNet50 on Pixel 3:
- Before: 552.956 ms
- After: 402.947 ms

### CODE REVIEW

**Review by houseroad — COMMENTED** [review]
New function should be backward compatible. Could you fix the CI and trigger the backward_compatible_test?

**Comment by ljk53** [comment]
> New function should be backward compatible. Could you fix the CI and trigger the backward_compatible_test?

Good suggestion. We should run the test to confirm. For this specific PR it only adds an internal op (starting with "_", not exposed to python) so it shouldn't break any external contract if we have done it correctly :)

**Comment by AshkanAliabadi** [comment]
Synced offline with Lu and ran the test locally.  That aside, there seems to be something wrong with the CI.

**Comment by houseroad** [comment]
The whole CI is broken at this moment as well.

**Pull request closed without merging**
