### PR TITLE
Add support for integer dim arg in `torch.linalg.norm`

### PR DESCRIPTION
**Pull request by kurtamohler**
Since PR #43262 is merged, this works now.

Part of #24802

### CODE REVIEW

**Comment by kurtamohler** [comment]
The `pytorch_linux_backward_compatibility_check_test` job failed, but that's unavoidable because I changed `native_functions.yaml`. The only actual BC breaking change is that calling `torch.linalg.norm` with `dim` being an int will now work correctly, instead of throwing an error.

**Comment by mruberry** [comment]
> The `pytorch_linux_backward_compatibility_check_test` job failed, but that's unavoidable because I changed `native_functions.yaml`. The only actual BC breaking change is that calling `torch.linalg.norm` with `dim` being an int will now work correctly, instead of throwing an error.

Breaking BC for torch.linalg.norm is also probably fine because it's so new no one has had a chance to use it. Just add an entry here:

https://github.com/pytorch/pytorch/blob/master/test/backward_compatibility/check_backward_compatibility.py

like for:

https://github.com/pytorch/pytorch/blob/7680d87a768102de63408b178ea836ee0bf19152/test/backward_compatibility/check_backward_compatibility.py#L74

with the operator + a date by which the PR will definitely be landed (I usually just put a month in). This will stop the backcompat build from complaining.

**Comment by kurtamohler** [comment]
Doesn't seem like the `pr/caffe2-pytorch-linux-xenial-rocm3.5.1-py3.6-test ` and `pr/pytorch-linux-xenial-rocm3.5.1-py3.6` are related to my changes.

**Comment by mruberry** [comment]
> Doesn't seem like the `pr/caffe2-pytorch-linux-xenial-rocm3.5.1-py3.6-test ` and `pr/pytorch-linux-xenial-rocm3.5.1-py3.6` are related to my changes.

Sorry about that, @kurtamohler, I agree those failures don't look related.

**Review by mruberry — APPROVED** [review]
Awesome improvement!

**Pull request closed without merging**
