### PR TITLE
Fixed stub for AdamW

### LINKED ISSUE #33757: Mypy cannot find torch.optim.AdamW
## 🐛 Bug

```python
from torch.optim import AdamW
```

Above code raises type error `test.py:1: error: Module 'torch.optim' has no attribute 'AdamW'; maybe "Adam"?`

## To Reproduce

1. Create new file and write this line `from torch.optim import AdamW`
1. Check with mypy

## Expected behavior

This should not raise any errors.

## Environment

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: Python 3.7.4

cc @ezyang

### PR DESCRIPTION
**Pull request by prajjwal1**
Fixes [#33757](https://github.com/pytorch/pytorch/issues/33757)

### CODE REVIEW

**Comment by prajjwal1** [comment]
@ezyang Please see, if this fixes the problem. Otherwise I'll make the suggested changes.

**Comment by yf225** [comment]
Per the original issue https://github.com/pytorch/pytorch/issues/33757, adding @ezyang as reviewer :)

**Review by ezyang — APPROVED** [review]

**Comment by prajjwal1** [comment]
Hi @ezyang , thanks for approving. @facebook-github-bot closed this PR instead of merging it. Could you please see it ?

**Comment by yf225** [comment]
@prajjwal1 No worries about it and it's on master now: https://github.com/pytorch/pytorch/commit/b1bd950a4d3a06b4e105cb77238fb7df01fad4da :D

**Comment by prajjwal1** [comment]
@yf225 Thanks for pointing it out.

**Pull request closed without merging**
