### PR TITLE
nn.linear module weight initialization fix

### LINKED ISSUE #19376: nn.Linear module weight initialization does not match the documentation
## 🐛 Bug

The documentation of the [linear module in python](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/linear.py) states that: 
```latex
weight: the learnable weights of the module of shape
            :math:`(\text{out\_features}, \text{in\_features})`. The values are
            initialized from :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})`, where
            :math:`k = \frac{1}{\text{in\_features}}`
```
but the code instead does
```python
init.kaiming_uniform_(self.weight, a=math.sqrt(5))
```
The [C++ implementation](https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/src/nn/modules/linear.cpp) instead looks ok:
```c
const auto stdv = 1.0 / std::sqrt(weight.size(1));
  NoGradGuard no_grad;
  for (auto& p : this->parameters()) {
    p.uniform_(-stdv, stdv);
  }
```

### PR DESCRIPTION
**Pull request by interesaaat**
This PR fixes the module weight initialization in nn.Linear by matching what state in the module documentation. 

Fixes #19376.

### CODE REVIEW

**Comment by ezyang** [comment]
Thanks for the PR. Can we please get a test for this?

**Comment by interesaaat** [comment]
> Thanks for the PR. Can we please get a test for this?

Let me look into this. (Any hint on where the test should go?)

**Comment by soumith** [comment]
@interesaaat i took a closer look. Mathematically, `init.kaiming_uniform_(self.weight, a=math.sqrt(5))` is doing the same as a uniform with `1.0 / std::sqrt(weight.size(1))`, from what I can tell.

If a is math.sqrt(5), then kaiming init's `bound` becomes: `sqrt(6 / (6 * weight.size(1))` which is `1.0 / sqrt(weight.size(1))`. They are both exactly doing the same thing.

**Comment by interesaaat** [comment]
I still believe that this is sort of confusing (using `kaiming_uniform` for initializing the weight in the linear module, but not the bias, nor the weight in the bilinear module).

**Pull request closed without merging**
