### PR TITLE
[dtensor] remove typing hack of DeviceMesh

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #94526
* #94525

This removes the typing hack, part of https://github.com/pytorch/pytorch/pull/92931

### CODE REVIEW

**Review by XilunWu — APPROVED** [review]
stamped to go!

**Comment by wanchaol** [comment]
> Is #97889 a forward fix?

yeah but looks a bit tricky to get the forward fix internally :(, I will rebase

**Pull request closed without merging**
