### PR TITLE
make autocast cache global instead of thread-local

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #86492

Summary:

There is a memory leak because `torch.clear_autocast_cache()` clears
the autocast cache from the main thread, but autograd can write to
this cache from a background thread, so whatever autograd writes
will leak.

With some offline discussion we decided that a global cache is a
practical way to deal with this, and the performance impact of the
lock should be negligible.

Test Plan:

I don't have a local repro of the original issue, need to look into how to get
that.

A toy example
(https://gist.github.com/vkuzo/0d6318fe7f7cb1c505e370cd5c1a643b)
does cache clearing as expected on forward and backward pass.

local testing:
```
python test/test_cuda.py -k autocast
python test/test_autocast.py
```

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Comment by ezyang** [comment]
Cc @eellison 

Test?

**Comment by ezyang** [comment]
I will approve after auditing all uses of variable on desktop

**Review by ezyang — APPROVED** [review]
needs test

**Comment by vkuzo** [comment]
re: testing - 

* any tips on how to get a local repro of the original memory leak?  I couldn't figure it out how to do it, yet.
* without a local repro, I guess we could expose a binding to query the number of elements in the cache, and test that the number is reasonable - would that be valuable enough to justify the binding? IMO probably not, but I'm flexible, wdyt

**Comment by ezyang** [comment]
@eellison did you have a repro handy?

**Comment by eellison** [comment]
https://github.com/pytorch/pytorch/issues/86059 this test and removing `torch.autograd.set_multithreading_enabled ` here should repro https://github.com/pytorch/pytorch/blob/master/test/test_ops.py#L2006

**Comment by eellison** [comment]
That should repro the cache failure - but sorry we actually need `torch.autograd.set_multithreading_enabled` in that test for other reasons. If you just run that same test without fake tensor that would give you a test.

**Comment by ezyang** [comment]
@eellison fwiw I still think you should use tls

**Comment by vkuzo** [comment]
I still don't have a local repro, so resorted to just verifying the the cache is in fact global.  Lmk if someone has a better test idea.

**Comment by eellison** [comment]
> fwiw I still think you should use tls 

yes i agree - just somewhat low pri at the moment

**Pull request closed without merging**
