### PR TITLE
Rename generate_numeric_debug_handle to numeric_debugger

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #130590

Summary:
att

Test Plan:
CI

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Review by dulinriley — APPROVED** [review]

**Review by tarun292 — APPROVED** [review]

**Comment by jerryzh168** [comment]
this API is not very public since we haven't tested internally, I think we can mark this as not-user-facing

**Pull request closed without merging**
