### PR TITLE
[numpy] `torch.exp{2, m1}`: promote integer inputs to float

### PR DESCRIPTION
**Pull request by kshitij12345**
Reference: #42515

### CODE REVIEW

**Comment by kshitij12345** [comment]
**Reason for skipping for bfloat16**

```python
>>> import torch
>>> torch.tensor(6.75, dtype=torch.bfloat16)
tensor(6.7500, dtype=torch.bfloat16)
>>> t = torch.tensor(6.75, dtype=torch.bfloat16)
>>> torch.expm1(t)
tensor(852., dtype=torch.bfloat16)
>>> torch.expm1(t.to(torch.float32))
tensor(853.0588)
```

There are cases with more difference in tolerance for other values.

**Comment by mruberry** [comment]
> **Reason for skipping for bfloat16**
> 
> ```python
> >>> import torch
> >>> torch.tensor(6.75, dtype=torch.bfloat16)
> tensor(6.7500, dtype=torch.bfloat16)
> >>> t = torch.tensor(6.75, dtype=torch.bfloat16)
> >>> torch.expm1(t)
> tensor(852., dtype=torch.bfloat16)
> >>> torch.expm1(t.to(torch.float32))
> tensor(853.0588)
> ```
> 
> There are cases with more difference in tolerance for other values.

This makes sense. I would really like to start considering ways we can work around NumPy's lack of bfloat16 support. Maybe we can cast the values to float32, then cast them to bfloat16, then nextafter them in the direction of the PyTorch result?

**Review by mruberry — APPROVED** [review]
Awesome! Thanks @kshitij12345!

**Comment by kshitij12345** [comment]
> This makes sense. I would really like to start considering ways we can work around NumPy's lack of bfloat16 support. Maybe we can cast the values to float32, then cast them to bfloat16, then nextafter them in the direction of the PyTorch result?

I think that makes sense since both have same range. Right now the catch is that `nextafter` is not implemented for `bfloat16`.

**Pull request closed without merging**
