### PR TITLE
Remove some uses of torch.is_tensor in favor of isinstance

### PR DESCRIPTION
**Pull request by colesbury**
There's still a lot more uses, but I was worried about conflicting with other PRs

### CODE REVIEW

**Comment by ezyang** [comment]
```
17:16:46 ======================================================================
17:16:46 ERROR: test_new (__main__.TestSparse)
17:16:46 ----------------------------------------------------------------------
17:16:46 Traceback (most recent call last):
17:16:46   File "test_sparse.py", line 843, in test_new
17:16:46     self.assertIs(torch.sparse.uint8, Variable(x).new(dtype=torch.sparse.uint8).dtype)
17:16:46 NameError: name 'Variable' is not defined
17:16:46 
17:16:46 ======================================================================
17:16:46 ERROR: test_new (__main__.TestUncoalescedSparse)
17:16:46 ----------------------------------------------------------------------
17:16:46 Traceback (most recent call last):
17:16:46   File "test_sparse.py", line 843, in test_new
17:16:46     self.assertIs(torch.sparse.uint8, Variable(x).new(dtype=torch.sparse.uint8).dtype)
17:16:46 NameError: name 'Variable' is not defined
```

**Review by gchanan — APPROVED** [review]
lgtm.  I think the test issue was fixed in a different commit.

**Pull request merged**
