### PR TITLE
[FSDP] ufmt FSDP test

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #87837 [FSDP] Fix wrapped module changing after ctor
* **#87812 [FSDP] ufmt FSDP test**
* #87811 [FSDP] ufmt /fsdp

This applies `ufmt` to all of the FSDP test files in the `test/distributed/fsdp/` directory.

**Test Plan**
CI

**Notes**
For VSCode users,
- Install `ufmt`: https://pypi.org/project/ufmt/
- Install VSCode `ufmt` extension: https://marketplace.visualstudio.com/items?itemName=omnilib.ufmt
- Include in `settings.json`:
```
{
    "[python]": {
        "editor.defaultFormatter": "omnilib.ufmt",
        "editor.formatOnSave": true,
    },
}
```

Differential Revision: [D40799963](https://our.internmc.facebook.com/intern/diff/D40799963)

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Stamp as this is just a formatting change. But I am not sure if `ufmt` is hooked up into lintrunner or any pre-commit hooks, what is the plan for enforcing a consistent formatting so we avoid many of these reformatting PRs?

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40799963).

**Pull request closed without merging**
