### PR TITLE
Stop immediately specializing common constants 0/1 for plain int

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128327
* #129983

Fixes https://github.com/pytorch/pytorch/issues/128319

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by ezyang** [comment]
oof dis CI

**Comment by ezyang** [comment]
It looks like this is just grinding recompilation counts though, it seems

**Comment by ezyang** [comment]
@anijain2305 will finish this off. (Animesh, feel free to open a new PR for yourself)

**Review by lezcano — COMMENTED** [review]
Does this mean that we no longer specialize 0 and 1 even with dynamic shapes? Or what do you mean by " 'plain' int"?

**Comment by ezyang** [comment]
We still 0/1 specialize for sizes. But if you have just a plain Python int we no longer specialize.

**Review by lezcano — APPROVED** [review]
Fair enough.

Do we have any place where we could document this behaviour?

The best place I found is https://pytorch.org/docs/main/torch.compiler_dynamo_deepdive.html#symbolic-shapes, but it'd be great to have a dedicated page for symbolic shapes / unbacked symints and all those things. We have [this one](https://pytorch.org/docs/main/torch.compiler_dynamic_shapes.html) but it's not particularly great.

**Comment by ezyang** [comment]
incredibly, this seems to be passing ci now! (inductor failures are trunk, I'll rebase)

**Comment by ezyang** [comment]
> Do we have any place where we could document this behaviour?

I don't. This is just so incredibly inside baseball, I'm not sure what someone is going to do with this information. In practice, you figure this out by looking at the recompiles logs, I think...

**Comment by ezyang** [comment]
To make rollout of this safer, I'm going to split this into bugfixes and then the actually policy change

**Comment by lezcano** [comment]
That being said, putting it in https://pytorch.org/docs/main/torch.compiler_dynamo_deepdive.html#are-always-specialized would be nice.

**Comment by ezyang** [comment]
Done

**Pull request closed without merging**
