### PR TITLE
dbr quant: make QTensorInfo a dataclass and add orig_dtype

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #71551 dbr quant: record dag of non-quantizeable ops
* #71324 dbr quant: refactor first_call hooks to be standalone
* #71312 dbr quant: rename seen_op_info to seen_q_op_info
* #71267 dbr quant: make SeenOpInfo a dataclass
* #71253 dbr quant: split observer insertion to a separate pass
* **#71245 dbr quant: make QTensorInfo a dataclass and add orig_dtype**
* #71233 dbr quant: do not crash on unsupported qconfig_dict keys if they are empty

Summary:

This is a refactor to make a future PR of making observer
insertion be a separate pass easier.
1. adds orig_dtype, so we always record what was seen while tracing
2. switches from namedtuple to dataclass, so we can have more explicit types

Test plan:

CI and mypy

Differential Revision: [D33558281](https://our.internmc.facebook.com/intern/diff/D33558281)

### CODE REVIEW

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33558281).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33558281).

**Review by HDCharles — APPROVED** [review]
looks good

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33558281).

**Pull request closed without merging**
