### PR TITLE
Avoid cuda stubs libraries being RPATHed

### PR DESCRIPTION
**Pull request by Flamefire**
This is a continuation of #68912 from @casparvl

In short I put the code from @casparvl into a function to not duplicate it. The new function `link_cuda_libraries` is a drop-in replacement for `target_link_libraries` which calls the latter and does the check and manual-rpath-setting on the libraries.
I also made it to work on CMake prior to 3.20 by using `get_filename_component` instead of `cmake_path`

Fixes #35418

@kumpera in the other PR you mentioned that some changes should/need to be split off. How would this need to look like? The changes depend on each other: The 3 CMakeLists.txt require the new module/file in the `cmake` folder and the `test_torch.py` will fail without those changes.

### CODE REVIEW

**Comment by Flamefire** [comment]
Rebased and new CLA signed

**Comment by Flamefire** [comment]
This is still relevant!

**Comment by surak** [comment]
Waiting for this

**Comment by Flamefire** [comment]
@kumpera Any updates here?

**Pull request closed without merging**
