### PR TITLE
Migrate trunk workflows to Amazon2023 ami

### PR DESCRIPTION
**Pull request by ZainRizvi**
A continuation of the migration started in 
- https://github.com/pytorch/pytorch/pull/131250

All migrated trunk jobs passed successfully

### CODE REVIEW

**Comment by ZainRizvi** [comment]
All trunk jobs have passed

**Review by malfet — APPROVED** [review]

**Review by malfet — APPROVED** [review]
LGTM, but why can't we use `get-label-type`?

**Comment by ZainRizvi** [comment]
> LGTM, but why can't we use `get-label-type`?

There's def an option we're considering there.  However, this requires updating runner-determinator.py to handle two (or more) potential experiments: The LF migration experiment and the Amazon2023 experiment.  This tooling will def be useful for future upgrades so we're building it out, but it takes some time to get it right and in the meantime I don't want to block the Amazon 2023 upgrade on that.

More details in https://docs.google.com/document/d/1be2ahAm3ksyuT2rpneuUYHpcnrqX87D6y5-LcmKPNT8/edit

**Pull request closed without merging**
