### PR TITLE
Introduce sym_min and sym_max

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #92149
* __->__ #92107

It turns out our old max/min implementation didn't do anything, because `__max__` and `__min__` are not actually magic methods in Python. So I give 'em the `sym_` treatment, similar to the other non-overrideable builtins.

NB: I would like to use `sym_max` when computing contiguous strides but this appears to make `python test/functorch/test_aotdispatch.py -v -k test_aot_autograd_symbolic_exhaustive_nn_functional_max_pool2d_cpu_float32` run extremely slowly. Needs investigating.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen

### CODE REVIEW

**Comment by Skylion007** [comment]
Is there no way to hack this with the `__lt__`/`__gt__`/`__gte__`/`__lte__` magic methods? max / min should call that under the hood.

**Comment by ezyang** [comment]
So the reason lt cannot be used is I need to symbolically represent max in our traced graph, without actually doing the conditional (which would induce a guard)

**Review by albanD — APPROVED** [review]
SGTM

**Review by voznesenskym — APPROVED** [review]

**Review by Skylion007 — APPROVED** [review]

**Comment by ezyang** [comment]
This appears to make test_aot_autograd_symbolic_exhaustive_nn_functional_max_pool2d_cpu_float32 take an extremely long time to run

**Comment by leslie-fang-intel** [comment]
Looks like there is unexpected change in thrid_party/IDeep commit in this PR which brings the oneDNN double checkout issue back. cc @ezyang @yanbing-j @jgong5

**Pull request closed without merging**
