### PR TITLE
[TensorExpr] Nuke `Function` class and directly use `Tensor` instead.

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #45949 [TensorExpr] LoopNest: add a constructor that takes Stmt instead of list of Tensors.
* #45948 [TensorExpr] LoopNest: replace output_tensors_ with output_bufs_.
* #45947 [TensorExpr] Loopnest: unify intermediate_tensors_ and temp_bufs_.
* #45946 [TensorExpr] Add shorthand versions for `splitWith{Mask,Tail}` functions.
* **#45936 [TensorExpr] Nuke `Function` class and directly use `Tensor` instead.**

`Tensor` has been a view into a `Function` that was supposed to be used
for a more general case when we have multiple computations over the same
domain (aka multiple output functions). We have never got to a point
where we need this and now have other ideas in mind on how to support
this case if need be. For now, let's just nuke `Function` to reduce the
overall system complexity.

The change should not affect any existing behavior.

Differential Revision: [D24153214](https://our.internmc.facebook.com/intern/diff/D24153214)

### CODE REVIEW

**Review by bertmaher — APPROVED** [review]
I wish this were phabricator so I could use one of the fine selection of "nuke" macros!

**Comment by ZolotukhinM** [comment]
> I wish this were phabricator so I could use one of the fine selection of "nuke" macros!

@bertmaher, pro-tip: you can paste the image here :)
image

**Comment by bertmaher** [comment]
Handy!

image
image

**Comment by bertmaher** [comment]
awh but strangelovenuke isn't animated!

**Pull request closed without merging**
