### PR TITLE
[WIP] [inductor] Keep minifier going in presence on segfaults

### PR DESCRIPTION
**Pull request by anijain2305**
Related to https://github.com/pytorch/torchdynamo/issues/1681

cc @jansel @lezcano @fdrocha

### CODE REVIEW

**Review by soumith — COMMENTED** [review]
the better fix would be to poll the subprocess aliveness in a thread.

**Comment by Chillee** [comment]
I don't actually understand why this isn't working. I'm pretty sure it used to work (or perhaps still does some work for some segfaults)?

**Comment by anijain2305** [comment]
Turning to WIP. Will debug more. Maybe it's because of parallel compilation.

**Comment by anijain2305** [comment]
Yes, this seems to be due to parallel compilation. For now, I have switched off parallel compilation in the generated repro file. This is just to unblock. We can keep the PR open to find the correct fix.

@zdevito This is the repro - https://www.internalfb.com/phabricator/paste/view/P539809325

If I remove the changes in this PR, there is a deadlock.

**Comment by voznesenskym** [comment]
How does this keep going if it segfaults? This just masks the original problem, actually, if the original segfault was due to multiprocess/multithreading, we now rerun the minifier in a different config.

**Comment by anijain2305** [comment]
> How does this keep going if it segfaults? This just masks the original problem, actually, if the original segfault was due to multiprocess/multithreading, we now rerun the minifier in a different config.

Oh those two are separate, but you do raise a good point.

So this is how minifiers work with segfault. We take the original graph, write that into a file, add some minfier code into that file, and then run that file in a subprocess. If the subprocess segfaults, its ok. The original process is still alive, and we keep on reducing the graph size.

The problem now is that parallel compilation uses `concurrent` package which is causing some incompatibility with our isolation mechanism process. 

@zdevito says - "I don’t think the concurrent package provides any guarentee about what happens if one of the participating processes segfaults.  But a likely scenario is that if one process segfaults the rest will be left in an unknown state."

**Review by zdevito — APPROVED** [review]

**Comment by zdevito** [comment]
We can possibly supersede this with: https://github.com/pytorch/pytorch/pull/87335

**Comment by anijain2305** [comment]
Closing in favor of https://github.com/pytorch/pytorch/pull/87335

**Pull request closed without merging**
