### PR TITLE
Fix meta for meta_fill_

### PR DESCRIPTION
**Pull request by SherlockNoMad**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #87493

Existing meta_fill_ doesn't correctly reflect the aliasing relationship for aten.fill. A new MetaTensor should be return instead.

### CODE REVIEW

**Review by eellison — APPROVED** [review]
nice

**Review by bdhirsh — APPROVED** [review]
nice. To bad op infos didn't catch :(

**Comment by ezyang** [comment]
test?

**Comment by ezyang** [comment]
Since we rely on opinfo tests, it would be better not to have a one off test, and instead think about how we could test it universally; eg using schema

**Comment by ezyang** [comment]
This is an excellent fix, it fixes timm_efficientnet on symbolic-shapes branch

**Pull request closed without merging**
