### PR TITLE
allow 3D attn_mask in multi_head_attention_forward

### PR DESCRIPTION
**Pull request by yqwangustc**
Summary:
multi_head_attention_forward currently only allows a 2D `attn_mask` as an extra score for `attn_output_weights`. This is problematic when it comes to fine control of attention weight, because it is effectively assuming every sequence in the batch get the same additional attention score, which makes implementing relative positional embedding (e.g., in
https://arxiv.org/abs/1901.02860) impossible. This simple diff allows user to
specify a 3D `attn_mask` in shape (`bsz`, `tgt_len`, `scr_len`) to give fine control of
attention.

This diff is a preview -- just send out for feedback, more testing will be added later on once the design is agreed.

Test Plan: TBD

Differential Revision: D17099834

### CODE REVIEW

**Comment by zhangguanheng66** [comment]
@stephenroller @myleott Is there a way to walk around? In general, I don't want to add more complexity to the API.

**Comment by zhangguanheng66** [comment]
LGTM. We still need to add a test in test_nn.py. But before working on it, let me talk with some people next week and see if there is a way to walk around. I still don't quite understand why a 3D attn_mask is necessary for Transformer-XL.

**Comment by yqwangustc** [comment]
@zhangguanheng66 , strictly speaking it is not for the recurrence in transformer XL, it is for the positional embedding at attention level, see the last 6 equations in section 3.3 in https://arxiv.org/pdf/1901.02860.pdf

**Comment by zhangguanheng66** [comment]
@yqwangustc I'm thinking if we could break the multiheadattention into multiple small building blocks. Then you could call those building blocks locally with the 3-D attention mask. In the core library, we don't need to change the API for simplicity.

**Comment by zhangguanheng66** [comment]
landed.

**Pull request closed without merging**
