### PR TITLE
[complex32] triu, tril, diag, trace : `cuda`

### PR DESCRIPTION
**Pull request by khushi-411**
Follows #74537

cc @kshitij12345

### CODE REVIEW

**Comment by khushi-411** [comment]
Hi, I can't find the test failures in these logs ([this](https://github.com/pytorch/pytorch/runs/6544399585?check_suite_focus=true) and [this](https://github.com/pytorch/pytorch/runs/6544399320?check_suite_focus=true)). These failures look irrelevant to me. 

What do you think? Thanks!!

**Comment by kshitij12345** [comment]
First one looks irrelevant as the ddp test failed. In case of second one, few sparse test had unexpected success as you added nonzero support was added. Remove the relevant expectedFailure and the tests should pass. Thanks!

**Comment by khushi-411** [comment]
Hi, @kshitij12345!
Thanks for looking into it! :)

I see `nonzero` support has been added in #79062. Sorry for the delay in updating this PR :(

Also, it looks like the PR is turned small. Shall I add more functions to it? Or this is good to go?

Thanks!

**Review by kshitij12345 — APPROVED** [review]
Looks good @khushi-411. Thanks!

I think it's ok the way it is. Can you please check locally if `trace` is working and enable testing for it if it does (since it uses `diag` and `sum`, I think it should pass for `chalf` now).

**Comment by khushi-411** [comment]
Sure, will do. Thanks, Kshitij!

**Comment by khushi-411** [comment]
Hi, I think this is good to go now.

Gentle ping, @kshitij12345 @anjali411! :)

Thanks in advance! :p

**Review by anjali411 — APPROVED** [review]
Thanks @khushi-411

**Pull request closed without merging**
