### PR TITLE
Update torch-xpu-ops pin (ATen XPU implementation)

### PR DESCRIPTION
**Pull request by fengyuan14**
Release cycle for PyTorch 2.5
1. Fixing runtime error on Windows: Fail to load torch_xpu_ops_unary_binary_kernels.dll as the bin size is large.

cc @frank-wei @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @gujinghui @EikanWang @guangyey

### CODE REVIEW

**Comment by etaf** [comment]
The failed job [xpu / linux-jammy-xpu-py3.9 / test (default, 4, 4, linux.idc.xpu)](https://hud.pytorch.org/pr/pytorch/pytorch/135647#29971112610) ([gh](https://github.com/pytorch/pytorch/actions/runs/10804530441/job/29971112610)) is caused by cuda bias code introduced by https://github.com/pytorch/pytorch/pull/135530

**Comment by fengyuan14** [comment]
https://github.com/pytorch/pytorch/pull/135656

**Review by EikanWang — APPROVED** [review]

**Comment by zejun-chen** [comment]
Hi,

The following failed CI case seems random and not related to XPU profiler. The enabling XPU profiler UT PR has not been landed.
```
Running 3 items in this shard: test/profiler/test_cpp_thread.py::CppThreadTest::test_profile_memory, test/profiler/test_cpp_thread.py::CppThreadTest::test_with_enable_profiler_in_child_thread, test/profiler/test_cpp_thread.py::CppThreadTest::test_without_enable_profiler_in_child_thread

profiler/test_cpp_thread.py::CppThreadTest::test_profile_memory ERROR: External init callback must run in same thread as registerClient (1739282176 != 1212482176)
```
Thank you.

**Pull request closed without merging**
