### PR TITLE
[BE] clang-tidy: concat all core torch namespaces

### PR DESCRIPTION
**Pull request by Skylion007**
#92100 caused issues with my clang-tidy autofixes since clang-tidy kept reverting the changes to the .cpp / .cu files since they weren't changed in the header as well. This PR uses some clang-tidy checks to concat all nested namespaces in the codebase automatically to make it more consistent. After all, if we are going to apply #92100, we should be uniform and concast all relevant nested namespaces. Ping @malfet since due the nested-namespaces. This uses nested-namespaces wherever possible which is syntactic sure introduce in C++17.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel @EikanWang @albanD @soumith @voznesenskym @penguinwu @anijain2305 @Guobing-Chen @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire @mlazos @yanboliang @chunyuan-w

### CODE REVIEW

**Comment by ezyang** [comment]
I don't think we can land this until all the domain libraries are on c++17 too

**Comment by Skylion007** [comment]
So #92100 is fine because it doesn't touch the headers? Seems like all checks are passing minus some transient errors, I can revert just the headers and have only the cpp files changed for consistency.

**Comment by ezyang** [comment]
Exactly

**Comment by Skylion007** [comment]
@ezyang Thinking about this, I am worried we don't have any checks for C++14 compatibility in headers. Otherwise, its' really easy for C++17 only functions etc to rapidly leak into the headers and break downstream projects (if we really want to maintain compatibility with C++14 for now?)

**Comment by ezyang** [comment]
In the terminal state, all our downstream projects should be required to be C++17. But we actually have to get our official downstream projects on C++17 first. It will also be nice to have a grace period where we don't egregiously break C++14 compatibility in our most used headers before downstream projects get there.

**Comment by ezyang** [comment]
@malfet do you have any other opinions lol

**Pull request closed without merging**
