### PR TITLE
Fix the caffe2_gpu linkage with torch on Windows

### LINKED ISSUE #15992: torch is not linked against caffe2_gpu when USE_CUDA is ON
Originally reported in #15858 by @HapeMask. The CUDA functionality won't work if no functionality in caffe2_gpu was used.
Test code:
```cpp
#include <iostream>
#include <torch/torch.h>

int main() {
	if (!torch::cuda::is_available()) {
		std::cerr << "NO CUDA?" << std::endl;
		return 1;
	}
	if (!torch::cuda::cudnn_is_available()) {
		std::cerr << "NO CUDNN?" << std::endl;
		return 1;
	}
	return 0;
}
```
Output using LibTorch:
```
NO CUDA?
```

### PR DESCRIPTION
**Pull request by peterjc123**
Fixes https://github.com/pytorch/pytorch/issues/15992.
Inspired by https://docs.microsoft.com/en-us/cpp/build/reference/optimization-best-practices?view=vs-2017. But this PR needs to be tested.

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by Alex18947** [comment]
Ok, the issue is back again.... After upgrading Pytorch from master and successfully building on Windows, the torch.lib and torch.dll libraries are empty (contain just one placeholder function), and linking against c10.lib, c10_cuda.lib, caffe2.lib and caffe2_gpu.lib works but makes the resulting binary depend only on c10.dll and caffe2.dll. As a result, torch::cuda::is_available() is always false.

Do we have the same problem again or am I missing something?

**Comment by peterjc123** [comment]
@Alex18947 This is not a bug. We have deprecated the old torch library a few weeks ago in https://github.com/pytorch/pytorch/pull/17783 and will rename caffe2 library to torch in https://github.com/pytorch/pytorch/pull/20774. We are sorry for the inconvenience.

**Comment by Alex18947** [comment]
@peterjc123 Yes, I understand that this change is intentional. But does it mean that there is no way now to create a C++ app in Windows so that  torch::cuda::is_available() returns true? If there is way, please suggest...

**Comment by peterjc123** [comment]
@Alex18947 I cannot reproduce this issue.
The result of the following code prints 1.
```
std::cout << torch::cuda::is_available() << std::endl;
```

**Comment by kostmo** [comment]
In the next week or two, I plan to collapse `caffe2` + `caffe2_gpu` (then renamed together as `torch`) into a single library: https://github.com/pytorch/pytorch/pull/20774#pullrequestreview-242963482

**Pull request closed without merging**
