### PR TITLE
Enable XNNPACK on Windows & Update XNNPACK

### LINKED ISSUE #44283: Enable XNNPACK on Windows Libtorch binaries
## 🚀 Feature
Enable XNNPACK on Windows Libtorch binaries

## Motivation
I've confirmed XNNPACK is supported on macOS Libtorch binaries.
However, XNNPACK is not supported on Windows Libtorch binaries including nightly build.
It seems that XNNPack is disabled on build as the `TorchConfig.cmake` in [ibtorch-win-shared-with-deps-latest.zip](https://pytorch.org/get-started/locally/) shows.

```
  if(OFF)
    find_library(XNNPACK_LIBRARY XNNPACK PATHS "${TORCH_INSTALL_PREFIX}/lib")
    list(APPEND TORCH_LIBRARIES ${XNNPACK_LIBRARY})
  endif()
```

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

### PR DESCRIPTION
**Pull request by peterjc123**
Fixes #44283.

### CODE REVIEW

**Comment by peterjc123** [comment]
cc @ezyang @malfet Do you have any idea about the build failures of the Linux jobs?

**Comment by peterjc123** [comment]
@ezyang @malfet Do you know how to update XNNPACK in those dirs like `confu-deps/`?

**Comment by peterjc123** [comment]
@Maratyszcza

**Comment by ezyang** [comment]
Oof, I wonder if this is one of those things that is going off and downloading XNNPACK as part of the build process. @Maratyszcza would know for sure.

Reading over the code, it looks to me like confu-deps is just where we are putting the binary outputs, and is unrelated to the problem The problem is that you have 

```

Oct 07 16:21:05 cc: error: ../third_party/XNNPACK/src/operators/argmax-pooling-nhwc.c../third_party/XNNPACK/src/operators/argmax-pooling-nhwc.cNOT:../third_party/XNNPACK/src/operators/argmax-pooling-nhwc.cCONFIG:Debug: No such file or directory
Oct 07 16:21:05 cc: error: CMakeFiles/XNNPACK.dir/src/operators/argmax-pooling-nhwc.c.o: No such file or directory
```

which kind of looks like to me that some file names got concatted together without spaces. I wonder if this is just being induced by the XNNPACK submodule update. cc @AshkanAliabadi  who updated XNNPACK submodule last time.

**Comment by Maratyszcza** [comment]
To avoid having XNNPACK download its dependencies, set `CLOG_SOURCE_DIR`, `CPUINFO_SOURCE_DIR`, `FP16_SOURCE_DIR`, `FXDIV_SOURCE_DIR`, `PSIMD_SOURCE_DIR`, and `PTHREADPOOL_SOURCE_DIR` before calling `ADD_SUBDIRECTORY` with the XNNPACK source directory.

**Comment by peterjc123** [comment]
> To avoid having XNNPACK download its dependencies, set `CLOG_SOURCE_DIR`, `CPUINFO_SOURCE_DIR`, `FP16_SOURCE_DIR`, `FXDIV_SOURCE_DIR`, `PSIMD_SOURCE_DIR`, and `PTHREADPOOL_SOURCE_DIR` before calling `ADD_SUBDIRECTORY` with the XNNPACK source directory.

This is already done.

**Comment by peterjc123** [comment]
> Oof, I wonder if this is one of those things that is going off and downloading XNNPACK as part of the build process. @Maratyszcza would know for sure.
> 
> Reading over the code, it looks to me like confu-deps is just where we are putting the binary outputs, and is unrelated to the problem The problem is that you have
> 
> ```
> 
> Oct 07 16:21:05 cc: error: ../third_party/XNNPACK/src/operators/argmax-pooling-nhwc.c../third_party/XNNPACK/src/operators/argmax-pooling-nhwc.cNOT:../third_party/XNNPACK/src/operators/argmax-pooling-nhwc.cCONFIG:Debug: No such file or directory
> Oct 07 16:21:05 cc: error: CMakeFiles/XNNPACK.dir/src/operators/argmax-pooling-nhwc.c.o: No such file or directory
> ```
> 
> which kind of looks like to me that some file names got concatted together without spaces. I wonder if this is just being induced by the XNNPACK submodule update. cc @AshkanAliabadi who updated XNNPACK submodule last time.

I guess this is because CMake used in those jobs are too old. That's why the jobs only fails with Ubuntu Xenial, not BIonic.

**Comment by Maratyszcza** [comment]
@peterjc123 It is possible, but I don't have an easy way to verify. If you see CMake errors from XNNPACK, please file an issue in its repo.

**Comment by peterjc123** [comment]
> @peterjc123 It is possible, but I don't have an easy way to verify. If you see CMake errors from XNNPACK, please file an issue in its repo.

https://github.com/google/XNNPACK/issues/1091

**Comment by peterjc123** [comment]
@Maratyszcza It seems that `_kshiftli_mask64` is introduced in GCC 7. You'll need to implement it in https://github.com/google/XNNPACK/blob/master/src/xnnpack/intrinsics-polyfill.h.

**Comment by Maratyszcza** [comment]
@peterjc123 Fix coming in google/XNNPACK#1094

**Comment by peterjc123** [comment]
@Maratyszcza `_kshiftri_mask64` is also missing.

**Comment by Maratyszcza** [comment]
@peterjc123 Should be fixed in google/XNNPACK#1097

**Review by ezyang — APPROVED** [review]
Good show.

**Pull request closed without merging**
