### PR TITLE
Fix `nonlinearity` arg issue in RNN

### LINKED ISSUE #114617: RNN argument order
### 🐛 Describe the bug

The documentation states
```
torch.nn.RNN(self, input_size, hidden_size, num_layers=1, nonlinearity='tanh', bias=True, batch_first=False, dropout=0.0, bidirectional=False, device=None, dtype=None)
```
besides the impossible `self`, I try to send the arguments in the order suggested
```
rnn = nn.RNN(2, 3, 1, 'relu')
x = torch.randn(5, 1, 2)
rnn(x)
```
which complains
```
TypeError: rnn_tanh() received an invalid combination of arguments - got (Tensor, Tensor, list, str, int, float, bool, bool, bool), but expected one of:
 * (Tensor data, Tensor batch_sizes, Tensor hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, !list of [Parameter, Parameter, Parameter, Parameter]!, !str!, !int!, !float!, !bool!, bool, bool)
 * (Tensor input, Tensor hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, !list of [Parameter, Parameter, Parameter, Parameter]!, !str!, int, float, bool, bool, bool)
```

### Versions

Latest.

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### PR DESCRIPTION
**Pull request by yuanx749**
Fixes #114617

This PR fix the the issue with `nonlinearity`, so that it can be passed as arg or kwarg.

Alternatively, if making `nonlinearity` kwarg-only is preferred, I can revert to another commit. cc @mikaylagawarecki

### CODE REVIEW

**Review by mikaylagawarecki — COMMENTED** [review]
Thanks, could you add a small test please

**Comment by yuanx749** [comment]
Sure. I added a test. @mikaylagawarecki

**Review by mikaylagawarecki — APPROVED** [review]
Thanks!

**Pull request closed without merging**
