### PR TITLE
Disable c10 op registration temporarily to reduce code size

### PR DESCRIPTION
**Pull request by dzhulgakov**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#26821 Disable c10 op registration temporarily to reduce code size**

Minimal revert of #26131 necessary to cutdown the codesize pre 1.3 until we figure out how to make templates better. Note the full revert doesn't work as many changes landed on top of it.

On my linux machine libtorch.so (no cuda build) went from 98Mb to 75Mb

Differential Revision: [D17576585](https://our.internmc.facebook.com/intern/diff/D17576585)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Review by smessmer — APPROVED** [review]
Looks good. Let's only land this into the release branch though, not to master.

**Comment by ailzhang** [comment]
Quick question: does this mean the way XLA ops are registered today will be disabled in the release?

**Review by smessmer — CHANGES_REQUESTED** [review]
This PR is probably not necessary anymore because a lot of PRs landed fixing binary size issues. Feel free to override me though if you disagree.

**Comment by gchanan** [comment]
based on @smessmer's comment and a discussion with @dzhulgakov, we are going to not land this.

The stats are this would lower code size by 2 MB (out of ~90), but it's probably better to just keep this code as close as possible to master.

**Pull request closed without merging**
