### PR TITLE
fix upload alerts to rockset

### PR DESCRIPTION
**Pull request by PaliC**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #103995

Testing is the CI of https://github.com/pytorch/pytorch/pull/103996

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Comment by malfet** [comment]
Just a suggestion: instead of adding test on follow-up PR, why not enable testing on pull-requests but constraint it to a specific files, akin to 
https://github.com/pytorch/pytorch/blob/13664bb5356184f88aec7e4affc3c41cc377945f/.github/workflows/build-triton-wheel.yml#L13-L20

**Pull request closed without merging**
