### PR TITLE
Fix caffe2 eigen + cuda9 windows build

### PR DESCRIPTION
**Pull request by bddppq**

### CODE REVIEW

**Comment by bddppq** [comment]
The eigen submodule has been changed to point to my fix at https://github.com/bddppq/eigen-git-mirror-fix-__hadd/commit/c71b3c1e944b363ffc6829033db7995581576064. Will upstream this once it's confirmed.

**Review by yinghai — COMMENTED** [review]
Have we upstreamed your fix to Eigen? Looks like there are some other places that has similar structure.

**Comment by bddppq** [comment]
@yinghai no I haven't yet. I think my commit fixes the issue, although the windows build is timing out. 
What do you mean by "similar structure"?

**Comment by yinghai** [comment]
I saw some similar code like ` __hmul(a, b)` and `__hsub(a, b)` in that file. Do they all need to be patched?

**Comment by bddppq** [comment]
Finally 😬

**Comment by bddppq** [comment]
@BIT-silence please take a look at the transpose and reduce ops changes. Like we chatted offline, msvc doesn’t have good support for partial tenplate specialization.

**Comment by bddppq** [comment]
eigen submodule update is needed to include some (official) fixes to work with msvc

**Comment by BIT-silence** [comment]
For the CUDA ops, we can currently take it as this. Another solution may be use DoRunWithType to remove the typename in the template arguments. I can make that change in the future. Thanks!

**Review by xiaomengy — APPROVED** [review]

**Pull request merged**
