### PR TITLE
Fix typos.

### PR DESCRIPTION
**Pull request by cdluminate**

### CODE REVIEW

**Comment by CDLuminate** [comment]
ping?

**Review by alykhantejani — APPROVED** [review]

**Review by gchanan — APPROVED** [review]

**Comment by gchanan** [comment]
thanks!

**Comment by apaszke** [comment]
I didn't merge it because it had a lot of lib changes so I left it for @soumith

**Comment by apaszke** [comment]
We'll probably have a few conflicts now

**Comment by gchanan** [comment]
ok, it probably makes the most sense to revert and wait for @soumith to do the reverse merge.  The only case I could find where this happened before was in https://github.com/pytorch/pytorch/pull/1563, but it looks like it was force pushed, but I don't want to do that.

**Pull request merged**
