### PR TITLE
WIP Add some tests for 3d channels last

### PR DESCRIPTION
**Pull request by dmenig**
Part of a multi-PR work to fix #59168.

### CODE REVIEW

**Comment by hyperfraise** [comment]
Can I please get approval for my workflows runs ?

**Comment by ezyang** [comment]
If you go to https://github.com/pytorch I think you should see a pending invite for the org

**Comment by hyperfraise** [comment]
> If you go to https://github.com/pytorch I think you should see a pending invite for the org

Sorry, I received an email saying my invitation has been cancelled, not indicating the reason why.

**Comment by ezyang** [comment]
I also sent you a repo invite but apparently that's not enough to enable workflows lol

**Comment by hyperfraise** [comment]
Sorry @ezyang my invite keeps getting canceled directly after you send it to me. Seems like someone somewhere disagrees with me being invited :'( 
Screenshot from 2024-01-23 23-20-46

I hope you can solve this

**Comment by hyperfraise** [comment]
I think I'm supposed to rebuild the file android/pytorch_android/src/androidTest/assets/android_api_module.ptl. I can activate the building of this in the CI, but how can I easily retrieve it to put its modifications on my branch ? I don't think I can easily reproduce the CI building of this file on my local machine :s

**Comment by ezyang** [comment]
@linbinyu, any chance you can help here?

**Comment by hyperfraise** [comment]
Forget that, I found how to build the .ptl file !

**Comment by ezyang** [comment]
So apparently the correct short term resolution is, when you want to make PRs to pytorch, to push your branches to pytorch/pytorch directly (rather than in your fork). I've gone ahead and given you write access to the repo, you're welcome to reopen this PR if necessary.

**Pull request closed without merging**
