### PR TITLE
Use intrinsics for trigonometric functions on CPU

### PR DESCRIPTION
**Pull request by xuhdev**
A little benchmarking shows real improvements.

Benchmarking script:

```python
import timeit

for n, t in [(10_000, 8000),
             (100_000, 800)]:
    for dtype in ('torch.float', 'torch.double'):
        print(f'================ dtype {dtype}, {t} times ================================')
        for op in ('sin', 'sinh', 'cos', 'cosh', 'tan'):
            print(f'a.{op}() (a.numel() == {n}) for {t} times')
            print(timeit.timeit(f'a.{op}()',
                                setup=f'import torch; a = torch.arange({n}, device="cpu", dtype={dtype})',
                                number=t))
```

RHEL 7.7, Debug build, gcc 8.3, turbo off:

Before this commit:

```
================ dtype torch.float, 8000 times ================================
a.sin() (a.numel() == 10000) for 8000 times
2.690067914001702
a.sinh() (a.numel() == 10000) for 8000 times
7.025003784001456
a.cos() (a.numel() == 10000) for 8000 times
2.691191975001857
a.cosh() (a.numel() == 10000) for 8000 times
6.7473940790005145
a.tan() (a.numel() == 10000) for 8000 times
39.14060311800131
================ dtype torch.double, 8000 times ================================
a.sin() (a.numel() == 10000) for 8000 times
5.442704386001424
a.sinh() (a.numel() == 10000) for 8000 times
6.778444146999391
a.cos() (a.numel() == 10000) for 8000 times
5.429267812000035
a.cosh() (a.numel() == 10000) for 8000 times
6.625128638002934
a.tan() (a.numel() == 10000) for 8000 times
6.888564799002779
================ dtype torch.float, 800 times ================================
a.sin() (a.numel() == 100000) for 800 times
2.343601189000765
a.sinh() (a.numel() == 100000) for 800 times
6.4455943499997375
a.cos() (a.numel() == 100000) for 800 times
2.3377084899984766
a.cosh() (a.numel() == 100000) for 800 times
6.357531049001409
a.tan() (a.numel() == 100000) for 800 times
46.93665131099988
================ dtype torch.double, 800 times ================================
a.sin() (a.numel() == 100000) for 800 times
5.122997600999952
a.sinh() (a.numel() == 100000) for 800 times
6.233409892000054
a.cos() (a.numel() == 100000) for 800 times
5.071856587001093
a.cosh() (a.numel() == 100000) for 800 times
6.0974346790026175
a.tan() (a.numel() == 100000) for 800 times
6.5203832980005245
```

After this commit:

```
================ dtype torch.float, 8000 times ================================
a.sin() (a.numel() == 10000) for 8000 times
1.5905082239987678
a.sinh() (a.numel() == 10000) for 8000 times
6.8216283560032025
a.cos() (a.numel() == 10000) for 8000 times
1.630263119997835
a.cosh() (a.numel() == 10000) for 8000 times
6.738510535000387
a.tan() (a.numel() == 10000) for 8000 times
1.7482984089983802
================ dtype torch.double, 8000 times ================================
a.sin() (a.numel() == 10000) for 8000 times
2.0000513029990543
a.sinh() (a.numel() == 10000) for 8000 times
6.876631892999285
a.cos() (a.numel() == 10000) for 8000 times
2.0672772910002095
a.cosh() (a.numel() == 10000) for 8000 times
6.678993797999283
a.tan() (a.numel() == 10000) for 8000 times
2.3625312719996145
================ dtype torch.float, 800 times ================================
a.sin() (a.numel() == 100000) for 800 times
1.2381345620015054
a.sinh() (a.numel() == 100000) for 800 times
6.400261008999223
a.cos() (a.numel() == 100000) for 800 times
1.284327255001699
a.cosh() (a.numel() == 100000) for 800 times
6.332740200999979
a.tan() (a.numel() == 100000) for 800 times
1.392364119998092
================ dtype torch.double, 800 times ================================
a.sin() (a.numel() == 100000) for 800 times
1.6348750549987017
a.sinh() (a.numel() == 100000) for 800 times
6.312609101998532
a.cos() (a.numel() == 100000) for 800 times
1.700102185997821
a.cosh() (a.numel() == 100000) for 800 times
6.141731683001126
a.tan() (a.numel() == 100000) for 800 times
1.9891383869980928
```

RHEL 7.7, Release build, gcc 8.3, turbo off:

Before this commit:

```
================ dtype torch.float, 8000 times ================================
a.sin() (a.numel() == 10000) for 8000 times
1.0220722929989279
a.sinh() (a.numel() == 10000) for 8000 times
0.9413958889999776
a.cos() (a.numel() == 10000) for 8000 times
1.013564700999268
a.cosh() (a.numel() == 10000) for 8000 times
0.9127178879971325
a.tan() (a.numel() == 10000) for 8000 times
25.249723791999713
================ dtype torch.double, 8000 times ================================
a.sin() (a.numel() == 10000) for 8000 times
3.3466339340011473
a.sinh() (a.numel() == 10000) for 8000 times
0.909793314000126
a.cos() (a.numel() == 10000) for 8000 times
3.4019737700000405
a.cosh() (a.numel() == 10000) for 8000 times
0.918371007002861
a.tan() (a.numel() == 10000) for 8000 times
4.902741645997594
================ dtype torch.float, 800 times ================================
a.sin() (a.numel() == 100000) for 800 times
0.9870414770011848
a.sinh() (a.numel() == 100000) for 800 times
0.9038734009991458
a.cos() (a.numel() == 100000) for 800 times
0.9786967349973565
a.cosh() (a.numel() == 100000) for 800 times
0.8774048919985944
a.tan() (a.numel() == 100000) for 800 times
30.299459709000075
================ dtype torch.double, 800 times ================================
a.sin() (a.numel() == 100000) for 800 times
3.3855797659998643
a.sinh() (a.numel() == 100000) for 800 times
0.8303290260009817
a.cos() (a.numel() == 100000) for 800 times
3.3702223940017575
a.cosh() (a.numel() == 100000) for 800 times
0.822016927999357
a.tan() (a.numel() == 100000) for 800 times
4.889868417001708
```

After this commit:

```
================ dtype torch.float, 8000 times ================================
a.sin() (a.numel() == 10000) for 8000 times
0.542676458000642
a.sinh() (a.numel() == 10000) for 8000 times
0.90598970100109
a.cos() (a.numel() == 10000) for 8000 times
0.6119738140005211
a.cosh() (a.numel() == 10000) for 8000 times
0.902145998999913
a.tan() (a.numel() == 10000) for 8000 times
0.7713400800021191
================ dtype torch.double, 8000 times ================================
a.sin() (a.numel() == 10000) for 8000 times
0.609621113002504
a.sinh() (a.numel() == 10000) for 8000 times
0.8993683010012319
a.cos() (a.numel() == 10000) for 8000 times
0.6876834479990066
a.cosh() (a.numel() == 10000) for 8000 times
0.8859291590015346
a.tan() (a.numel() == 10000) for 8000 times
0.9243346840012236
================ dtype torch.float, 800 times ================================
a.sin() (a.numel() == 100000) for 800 times
0.5219837559998268
a.sinh() (a.numel() == 100000) for 800 times
0.8755807839988847
a.cos() (a.numel() == 100000) for 800 times
0.5899826130007568
a.cosh() (a.numel() == 100000) for 800 times
0.8757360769996012
a.tan() (a.numel() == 100000) for 800 times
0.7496912290007458
================ dtype torch.double, 800 times ================================
a.sin() (a.numel() == 100000) for 800 times
0.578619064999657
a.sinh() (a.numel() == 100000) for 800 times
0.7951330530013365
a.cos() (a.numel() == 100000) for 800 times
0.6442456569966453
a.cosh() (a.numel() == 100000) for 800 times
0.7975544330001867
a.tan() (a.numel() == 100000) for 800 times
0.875703464000253
```

### CODE REVIEW

**Comment by vishwakftw** [comment]
Floating point `tan` seemed to have been very slow...

**Comment by resistor** [comment]
> Benchmarking script (on RHEL 7.7, Debug build, with gcc 8.3):

Doesn't the debug build invalidate the benchmark results?  Some compilers recognize and optimize transcendentals in optimized mode.  I strongly suspect this change is still worthwhile, but I'd like to accurate benchmark results first.

**Comment by xuhdev** [comment]
I added benchmark results for release build as well.

When assessing changes from A to B, IMO, in general, merely evaluating Debug builds seems sufficient for me. Assuming that better written code will lead to no worse compiler optimization, the outcome of Debug builds hold the bottom line regardless of the compiler used. If the bottom line has raised (better performance on Debug builds), there shouldn't be any performance related reason to hold it off unless there is an interest in a different dimension, such as readability and so on. In addition, Debug build is more compiler-agnostic in evaluation, when a full-fledged benchmarking is not realistic.

**Comment by resistor** [comment]
> I added benchmark results for release build as well.

Thank you.  As expected, results still look good.

> When assessing changes from A to B, IMO, in general, merely evaluating Debug builds seems sufficient for me. Assuming that better written code will lead to no worse compiler optimization, the outcome of Debug builds hold the bottom line regardless of the compiler used. If the bottom line has raised (better performance on Debug builds), there shouldn't be any performance related reason to hold it off unless there is an interest in a different dimension, such as readability and so on. In addition, Debug build is more compiler-agnostic in evaluation, when a full-fledged benchmarking is not realistic.

I don't agree with this logic, because "assuming that better written code will lead to no worse compiler optimization" is not true in this case.   If the compiler is converting the `std` functions into builtins at `-O3` (which I know that both Clang and GCC do in some cases) then it's entirely possible that the compiler could be choosing a better implementation of those builtins than Sleef.  Another way to think of it is that Sleef always bakes in a good implementation, even in Debug mode, whereas the compiler's builtin lowering will be low quality in `-O0` and higher quality in `-O3`.  Without testing, we don't know that Sleef's version is better than what the compiler gives us when actually let it try.

**Review by resistor — APPROVED** [review]
Change LGTM, and thank you for the additional benchmark results.  I'd like to hear someone else weigh-in (@colesbury ?) on whether there are any concerns about numerics differences between `std` and `Sleef` implementations of these functions.

**Comment by colesbury** [comment]
> ...whether there are any concerns about numerics differences between std and Sleef implementations of these functions

Precision should be good. These are all the "1.0 ulp" versions, which matches or exceeds the precision documented by GNU libm (https://www.gnu.org/software/libc/manual/html_node/Errors-in-Math-Functions.html) for these functions.

**Comment by resistor** [comment]
@xuhdev Can you resolve the macos error?  It looks like a test tolerance needs to be adjusted.  I think this is good to go once that is resolved.

**Comment by xuhdev** [comment]
It doesn't seem like a tolerance issue. The error message says:

> AssertionError: Not within tolerance rtol=0.0001 atol=1e-05 at input[4, 9] (0.0 vs. 0.8731196522712708) and 19 other locations (25.00%)

This means that on the CI it always produces zero. Could you help run the test on a MacOS system? It doesn't seem right to me. Thanks!

**Comment by resistor** [comment]
I can confirm that the test fails for me on macOS with this diff.  I've put the before/after results in this gist: https://gist.github.com/resistor/70e6babc857e09a20e4f87dd8f286c19

**Comment by resistor** [comment]
Here's a minimal example:

```
>>> torch.sin(torch.tensor([1.0000e+10]))
tensor([-0.])
>>> math.sin(1.0000e+10)
-0.4875060250875106
```

**Comment by resistor** [comment]
I believe this is a Sleef bug that was fixed in 3.3.1.  From the release notes, "Trigonometric functions now evaluate correctly with full FP domain."

@colesbury What is our policy on updating to new versions of Sleef?

**Comment by colesbury** [comment]
@resistor we don't have any policy  -- upgrade if it'll fix bugs

**Comment by xuhdev** [comment]
@resistor The CI has passed now

**Comment by vincentqb** [comment]
@resistor -- I'll let you land the diff if you are ready to do so.

**Pull request closed without merging**
