### PR TITLE
BUG: fix np.ndarray.resize under dynamo

### LINKED ISSUE #113539: incorrect results for ndarray.methods under torch.Dynamo
### 🐛 Describe the bug

Compiled invocations of ndarray methods which mutate the array in-place produce wrong, unmodified results. Consider

```
import numpy as np
import torch

from torch._dynamo.testing import CompileCounter

def fn():
    x = np.arange(3)
    x.resize(3, 2, 1)
    return x

counter = CompileCounter()
opt_fn = torch._dynamo.optimize(counter)(fn)

res = opt_fn()

print("eager: ", fn(), fn().shape)
print("compiled:", res, res.shape)
print(counter.frame_count)
```

On eager NumPy, `fn().shape`  is `(3, 2, 1)`, but when compiling it is `(3,)` -- it returns the original unresized `x` array. 

The graph code is fishy:

```
$ TORCH_LOGS="graph_code" python resize.py 
[2023-11-12 17:07:01,445] [0/0] torch._dynamo.output_graph.__graph_code: [DEBUG] TRACED GRAPH
[2023-11-12 17:07:01,445] [0/0] torch._dynamo.output_graph.__graph_code: [DEBUG]  ===== __compiled_fn_0 =====
[2023-11-12 17:07:01,445] [0/0] torch._dynamo.output_graph.__graph_code: [DEBUG]  <eval_with_key>.0 class GraphModule(torch.nn.Module):
[2023-11-12 17:07:01,445] [0/0] torch._dynamo.output_graph.__graph_code: [DEBUG]     def forward(self):
[2023-11-12 17:07:01,445] [0/0] torch._dynamo.output_graph.__graph_code: [DEBUG]         # File: resize.py:9, code: x = np.arange(3)
[2023-11-12 17:07:01,445] [0/0] torch._dynamo.output_graph.__graph_code: [DEBUG]         x = torch__dynamo_utils_wrapped_arange(3)
[2023-11-12 17:07:01,445] [0/0] torch._dynamo.output_graph.__graph_code: [DEBUG]         
[2023-11-12 17:07:01,445] [0/0] torch._dynamo.output_graph.__graph_code: [DEBUG]         # File: resize.py:10, code: x.resize(3, 2, 1)
[2023-11-12 17:07:01,445] [0/0] torch._dynamo.output_graph.__graph_code: [DEBUG]         wrapped_resize = torch__dynamo_utils_wrapped_resize(x, 3, 2, 1)
[2023-11-12 17:07:01,445] [0/0] torch._dynamo.output_graph.__graph_code: [DEBUG]         return (x,)
```

### Versions

main / https://github.com/pytorch/pytorch/pull/112959

### PR DESCRIPTION
**Pull request by ev-br**
Make sure ndarray.resize actually works in-place, so that dynamo does the right thing tracking the result.

Fixes #113539

cc @mruberry @rgommers @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
Is it possible to call `self.tensor.resize_(new_shape)` at least for most cases? That construction is understood by dynamo, while `set_` isn't

**Comment by ev-br** [comment]
When enlarging the array, ndarray.resize fills missing elements with zeros, while tensor.resize_ keeps them unitialized (or float nan / integer maxint, if  using `torch.use_deterministic_algorithms` -- https://pytorch.org/docs/stable/generated/torch.Tensor.resize_.html)

**Comment by lezcano** [comment]
So let's use `resize_` when the size is the same or less.

For the other case, we can implement it as:
```python
n = a.numel() 
a.resize_(new_shape)
assert a.is_contiguous()
b = a.flatten()  # Does not copy
b[n:].zero_()
```

`set_` is too powerful a function, and as such, it doesn't play well with the compiler. Best avoid it if we can.

**Review by lezcano — APPROVED** [review]

**Pull request closed without merging**
