### PR TITLE
When looking for pybind11, do not attempt to get properties from pybind11:pybind11.

### PR DESCRIPTION
**Pull request by xuhdev**
There is no property name "INTERFACE_INCLUDE_DIRECTORIES" for pybind11::pybind11. This will cause cmake error if there exists a system installation of pybind11. In addition, pybind11_INCLUDE_DIRS is already set once "find_package(pybind11 CONFIG)" finds pybind11.

### CODE REVIEW

**Comment by xuhdev** [comment]
The test failure does not seem to be caused by this PR...

**Comment by ezyang** [comment]
@xkszltl, you originally wrote the code that is replaced here. Do you mind reviewing?

**Comment by xkszltl** [comment]
@ezyang Sure! Thanks for letting me know.

I think it's really dependent on how you get the pybind in your system and what's the version of it.

```INTERFACE_INCLUDE_DIRECTORIES``` was added 2 years ago to pybind:

https://github.com/pybind/pybind11/blob/534b756cb3244aca959359c07d44e4fed3498ba8/tools/pybind11Config.cmake.in#L87

@xuhdev Will you be able to provide more detail about your system? Such as what's the OS distribution, which cmake version are you using, and where did you get the pybind and its version?

IMHO it's caused by using a very old pybind version, but in case there's any special OS dist that change the default behavior, it's better to add a fallback path instead of replacement.

**Comment by xuhdev** [comment]
@xkszltl  Thanks for your review. I am on Debian Stretch, cmake 3.9.5, pybind 2.0.1 from distribution package.

Ineed, my pybind version is older and `INTERFACE_INCLUDE_DIRECTORIES` was under a different scope (`pybind11::module`). But anyway, I'm wondering, since `pybind11_INCLUDE_DIRS` is [always set when pybind11 is found](https://github.com/pybind/pybind11/blob/534b756cb3244aca959359c07d44e4fed3498ba8/tools/pybind11Config.cmake.in#L95,L97), is there a specific reason to set it explicitly from `INTERFACE_INCLUDE_DIRECTORIES`? From the [same three lines](https://github.com/pybind/pybind11/blob/534b756cb3244aca959359c07d44e4fed3498ba8/tools/pybind11Config.cmake.in#L95,L97), it looks like `INTERFACE_INCLUDE_DIRECTORIES` is only used for internal purposes and its external use can be unstable...

**Comment by xkszltl** [comment]
@xuhdev Yes it's introduced to pybind11::pybind11 somewhere between 2.0 and 2.1.

AFAIK it's not for internal use.
When `INTERFACE_INCLUDE_DIRECTORIES` is set, you'll get it automatically when do `target_link_library`, which is the desire behavior for modern C++, and `pybind11_INCLUDE_DIRS` is mainly for backward compatibility and can be deprecated in the future.

If possible, would you be able to test your approach against the latest pybind release (v2.2.4)?
If it works I think it's good to check it in.

**Comment by ezyang** [comment]
@xuhdev I'll merge this once you check :)

**Comment by xuhdev** [comment]
Yes, I'll do it, thanks. It may take me a couple more days since I'm buried into other deadlines right now...

**Comment by xuhdev** [comment]
@xkszltl  I found a strange problem. With the latest pybind11 from anaconda, both the old code and the new code produce the following messages on my system:

```
Python 3.6.6 :: Anaconda custom (64-bit)                                                                                                                                                       
-- System pybind11 found                                                                                                                                                                       
-- pybind11l include dirs: /home/hong/anaconda3/include/python3.6m/home/hong/anaconda3/include/python3.6m 
```

In other words, the include directory is repeated twice. I still have no idea why this is happening.

**Comment by ezyang** [comment]
I see you pushed some new commits, and I can no longer see the diff from before. Did that fix the problem?

**Comment by xuhdev** [comment]
No, this is simply a rebase plus the typo fix.

**Comment by ezyang** [comment]
It sounds like a bug in pybind11. I don't see any obvious bugs in the first two pages of commits though.

**Comment by xkszltl** [comment]
`DIRS` is actually the interface inc, which also contains other dirs like python header path.
Take a look at these 3 lines:

https://github.com/pybind/pybind11/blob/534b756cb3244aca959359c07d44e4fed3498ba8/tools/pybind11Config.cmake.in#L87
https://github.com/pybind/pybind11/blob/534b756cb3244aca959359c07d44e4fed3498ba8/tools/pybind11Config.cmake.in#L95
https://github.com/pybind/pybind11/blob/534b756cb3244aca959359c07d44e4fed3498ba8/tools/pybind11Config.cmake.in#L97

**Comment by xuhdev** [comment]
OK, it turns out this is simply not the right way to output that variable. I have updated the PR and now everything should just work fine.

**Comment by ezyang** [comment]
Oh, good catch. Unfortunately tests are failing now.

**Comment by xuhdev** [comment]
@ezyang Shall we merge :)

**Review by soumith — APPROVED** [review]

**Pull request closed without merging**
