### PR TITLE
msvc_fixes

### PR DESCRIPTION
**Pull request by ArutyunovG**
Fixing MSVC errors

```
  D:\pytorch-scripts\caffe2_builders\v141\pytorch\aten\src\THC/THCReduce.cuh(144): error C4002: too many actual paramet
ers for macro 'C10_LAUNCH_BOUNDS_1' [D:\pytorch-scripts\caffe2_builders\v141\pytorch\build\Debug\caffe2\caffe2_gpu.vcxp
roj]
  D:\pytorch-scripts\caffe2_builders\v141\pytorch\aten\src\THC/THCReduce.cuh(259): error C4002: too many actual paramet
ers for macro 'C10_LAUNCH_BOUNDS_1' [D:\pytorch-scripts\caffe2_builders\v141\pytorch\build\Debug\caffe2\caffe2_gpu.vcxp
roj]
  D:/pytorch-scripts/caffe2_builders/v141/pytorch/aten/src/THCUNN/SpatialDilatedMaxPooling.cu(51): error C4002: too man
y actual parameters for macro 'C10_LAUNCH_BOUNDS_1' [D:\pytorch-scripts\caffe2_builders\v141\pytorch\build\Debug\caffe2
\caffe2_gpu.vcxproj]
```

on variadic C10_LAUNCH_BOUNDS as well as Debug linking issues with at::Half in pool_op_cudnn.cc like this one

```
pool_op_cudnn.obj : error LNK2019: unresolved external symbol "public: bool __cdecl caffe2::MaxPoolFunctor<class caff
e2::CUDAContext>::GlobalPoolingBackward<struct c10::Half,2>(int,int,int,struct c10::Half const *,struct c10::Half const
 ,struct c10::Half const ,struct c10::Half ,class caffe2::CUDAContext )const " (??$GlobalPoolingBackward@UHalf@c10@
@$01@?$MaxPoolFunctor@VCUDAContext@caffe2@@@caffe2@@QEBA_NHHHPEBUHalf@c10@@00PEAU23@PEAVCUDAContext@1@@Z) referenced in
 function "public: bool __cdecl caffe2::`anonymous namespace'::CuDNNMaxPoolFunctor::GlobalPoolingBackward<struct c10::H
alf,2>(int,int,int,struct c10::Half const ,struct c10::Half const ,struct c10::Half const ,struct c10::Half ,class
caffe2::CUDAContext *)const " (??$GlobalPoolingBackward@UHalf@c10@@$01@CuDNNMaxPoolFunctor@?A0xb936404a@caffe2@@QEBA_NH
HHPEBUHalf@c10@@00PEAU34@PEAVCUDAContext@2@@Z) [D:\pytorch-scripts\caffe2_builders\v141\pytorch\build\Debug\caffe2\caff
e2_gpu.vcxproj]
```

### CODE REVIEW

**Comment by ArutyunovG** [comment]
@peterjc123 @ezyang @orionr 

This is another msvc build fix. 
Please, consider reviewing it.

1. C10_LAUNCH_BOUNDS is not supported in variadic form by MSVC.

Reference #15461
Thanks to @kolua0901 we tried [different variadic approach](https://stackoverflow.com/questions/3046889/optional-parameters-with-c-macros/28074198#28074198) from the same stackoverflow thead. Although MSVC understands it, the macro fails in case of two arguments and the first argument being in parenthesis. So no good variadic solution was found.

2. Remove c10::Half from pool_op_cudnn.cc 

c10::Half is added in pool_op_cudnn.cc in DispatchHelper, however there is no actual implementation for that type. It causes linking issue in Debug, when compiler optimizations are off. Sample error message is added in the description.

**Comment by peterjc123** [comment]
cc @ezyang @orionr

**Review by peterjc123 — APPROVED** [review]

**Comment by orionr** [comment]
cc @kostmo

**Comment by ezyang** [comment]
This fails internal build for some reason. Errors look like:

```
caffe2/aten/src/THC/generic/THCTensorTopK.cu(30): error: this declaration has no storage class or type specifier
caffe2/aten/src/THC/generic/THCTensorTopK.cu(30): error: variable "THCudaLongTensor_resize" has already been defined
caffe2/aten/src/THC/generic/THCTensorTopK.cu(30): error: expected a ")"
caffe2/aten/src/THC/generic/THCTensorTopK.cu(121): error: expected a declaration
caffe2/aten/src/THC/generic/THCTensorTopK.cu(178): warning: parsing restarts here after previous syntax error
caffe2/aten/src/THC/generic/THCTensorTopK.cu(179): error: this declaration has no storage class or type specifier
caffe2/aten/src/THC/generic/THCTensorTopK.cu(179): error: variable "THCudaLongTensor_freeCopyTo" has already been defined
caffe2/aten/src/THC/generic/THCTensorTopK.cu(179): error: expected a ")"
caffe2/aten/src/THC/generic/THCTensorTopK.cu(180): error: this declaration has no storage class or type specifier
caffe2/aten/src/THC/generic/THCTensorTopK.cu(180): error: variable "THCudaLongTensor_free" has already been defined
caffe2/aten/src/THC/generic/THCTensorTopK.cu(180): error: expected a ")"
caffe2/aten/src/THC/generic/THCTensorTopK.cu(181): error: expected a declaration
caffe2/aten/src/THC/generic/THCTensorTopK.cu(184): warning: parsing restarts here after previous syntax error
caffe2/aten/src/THC/generic/THCTensorTopK.cu(186): error: this declaration has no storage class or type specifier
caffe2/aten/src/THC/generic/THCTensorTopK.cu(186): error: variable "__THCudaCheck" has already been defined
caffe2/aten/src/THC/generic/THCTensorTopK.cu(186): error: expected a ")"
caffe2/aten/src/THC/generic/THCTensorTopK.cu(187): error: expected a declaration
caffe2/aten/src/THC/generic/THCTensorTopK.cu(18): warning: parsing restarts here after previous syntax error
caffe2/aten/src/THC/generic/THCTensorTopK.cu(20): error: variable "sliceSize" has already been defined
caffe2/aten/src/THC/generic/THCTensorTopK.cu(21): error: expected a declaration
caffe2/aten/src/THC/generic/THCTensorTopK.cu(23): error: variable "input" has already been defined
caffe2/aten/src/THC/generic/THCTensorTopK.cu(27): error: variable "topKSize" has already been defined
caffe2/aten/src/THC/generic/THCTensorTopK.cu(28): error: variable "topKSize" has already been defined
caffe2/aten/src/THC/generic/THCTensorTopK.cu(29): error: this declaration has no storage class or type specifier
caffe2/aten/src/THC/generic/THCTensorTopK.cu(29): error: declaration is incompatible with "void THCudaShortTensor_resize(THCState *, c10::TensorImpl *, c10::IntArrayRef, c10::IntArrayRef)"
caffe2/aten/src/THC/generic/THCTensor.hpp(18): here
```

**Comment by ezyang** [comment]
If this error message is insufficient, I can investigate more.

**Comment by ArutyunovG** [comment]
@ezyang 
Thanks for the report.
I see, that need to switch some new C10_LAUNCH_BOUNDS to non-variadic form, which were added these few days. 
For example [here](https://github.com/pytorch/pytorch/blob/237e5438f532418ecb465ca7209e3e2241e32501/aten/src/THC/THCTensorTopK.cuh#L364). 
I'll go over changes in the master to sync it with non-variadic C10_LAUNCH_BOUNDS and write here again. Hopefully tomorrow, or at least at the weekend for sure.
Thanks again for giving this a look.

**Comment by ArutyunovG** [comment]
@ezyang 
Fixed this and rebased again.
Build works on my side with MSVC as well.

**Comment by peterjc123** [comment]
@ezyang ping

**Comment by ezyang** [comment]
@peterjc123 Thanks for the ping. You can get someone pinged about a merge even more quickly using "@pytorchbot merge this please" :)

**Pull request closed without merging**
