### PR TITLE
parallelize operations in THNN module with openmp

### PR DESCRIPTION
**Pull request by zy97140**
This PR optimize some operations in THNN module based on the macros added by #5584.

### CODE REVIEW

**Comment by ezyang** [comment]
Have you run some perf numbers with and without the parallelization?

**Review by zou3519 — CHANGES_REQUESTED** [review]
See @ezyang's comments (perf numbers would be great)

**Comment by ezyang** [comment]
CC @cpuhrsch 

@zy97140 Do you still want to move forward with this PR? It has bitrotted considerably.

**Comment by soumith** [comment]
closing, feel free to reopen after responding to Edward's comments

**Pull request closed without merging**
