### PR TITLE
Use the run_subtests utility instead of self.subTest

### PR DESCRIPTION
**Pull request by spzala**
The use of run_subtests utility is a better test practice.

Related #84071

cc @zhaojuanmao @mrshenli @rohan-varma @awgu

### CODE REVIEW

**Comment by spzala** [comment]
cc @rohan-varma @awgu - hello, this PR is an attempt to address the issue [comment](https://github.com/pytorch/pytorch/pull/83195#discussion_r952931023). I will be covering rest of the fsdp test suits in a couple of different PRs for easier and quicker review. I hope that's OK. Thanks!

**Review by awgu — APPROVED** [review]
LGTM! Thanks :)

**Comment by spzala** [comment]
:) Thank you!! @awgu

**Comment by spzala** [comment]
> It looks like lint is failing. Could you run `lintrunner -a` and update the PR?
> 
> Here is the wiki with some info on how to get `lintrunner` set up: https://github.com/pytorch/pytorch/wiki/lintrunner
> 
> Let me know if you hit any issues there.

@awgu sorry, I missed running linter locally. Yes, sounds good, will update the PR. Thanks!!

**Pull request closed without merging**
