### PR TITLE
fix stride compare failed when size value equal to one in ForeachUtils.h

### PR DESCRIPTION
**Pull request by Shan19900305**
…s.h (#134546)

When size value equal to one, tensor strides value need be skipped to compare. @ezyang
Pull Request resolved: https://github.com/pytorch/pytorch/pull/134546 Approved by: https://github.com/janeyx99

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by Shan19900305** [comment]
@kit1980 @janeyx99

**Comment by flynn-goldenowl** [comment]
Preparing review...

**Comment by janeyx99** [comment]
this would be good to cherry pick yes

**Comment by Shan19900305** [comment]
> this would be good to cherry pick yes

Hi, Xu. Can you approve this pr to merge?

**Comment by janeyx99** [comment]
Someone from the release team will do the approval--they know that I've approved the original PR.

**Review by kit1980 — APPROVED** [review]

**Pull request merged**
