### PR TITLE
[ROCm] Enable few test_prim UTs for ROCm

### PR DESCRIPTION
**Pull request by pruthvistony**
cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### CODE REVIEW

**Review by IvanYashchuk — APPROVED** [review]

**Review by jeffdaily — APPROVED** [review]
All unit tests passing.  1 CUDA failure unrelated to the PR changes.

**Comment by pruthvistony** [comment]
cc @bertmaher @kirklandsign @0x00b1 
Can you please review.

**Comment by pruthvistony** [comment]
@malfet 
Can you please help on this review.

**Comment by pruthvistony** [comment]
The PR is stale, rebasing it.

@pytorchbot rebase

**Comment by pruthvistony** [comment]
Fixed the merge conflicts.

**Review by malfet — APPROVED** [review]

**Comment by pruthvistony** [comment]
The failure of job -` cuda11.6-py3.10-gcc7-sm86 / test (inductor_timm, 1, 2, linux.g5.4xlarge.nvidia.gpu) ` doesnt seem to be related to this PR it is failing in other PR also
ref - https://hud.pytorch.org/pytorch/pytorch/commit/97e47a52b8872873533abc22f93a919222799864

**Pull request closed without merging**
