### PR TITLE
[FSDP2] Added APIs for explicit fwd/bwd prefetching

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128884

This PR adds two APIs `set_modules_to_forward_prefetch` and `set_modules_to_backward_prefetch` to enable explicit forward/backward all-gather prefetching, respectively.

```
def set_modules_to_forward_prefetch(self, modules: List[FSDPModule]): -> None
def set_modules_to_backward_prefetch(self, modules: List[FSDPModule]): -> None
```

**Motivation**
FSDP2 implements _reasonable defaults_ for forward and backward prefetching. In forward, it uses implicit prefetching and allows two all-gather output tensors to be alive at once (so that the current all-gather copy-out can overlap with the next all-gather). In backward, it uses explicit prefetching based on the reverse post-forward order.

However, there may be cases where with expert knowledge, we can reduce communication bubbles by moving all-gathers manually. One way to expose such behavior is to expose _prefetching limits_, i.e. integers that configure how many outstanding all-gathers/all-gather output tensors can be alive at once. IMIHO, this leans toward _easy_, not _simple_ (see [PyTorch design principles](https://pytorch.org/docs/stable/community/design.html#principle-2-simple-over-easy)).

The crux of the problem is that there may be special cases where manual intervention can give better performance. Exposing a prefetching limit and allowing users to pass a value >1 just smooths over the problem since such a limit would generally apply over the entire model even though it possibly should not. Then, expert users will see a specific all-gather that they want to deviate from this limit, and there is little we can do.

Thus, we instead choose to expose the most primitive extension point: namely, every `FSDPModule` gives an opportunity to prefetch other all-gathers in forward and in backward. How to leverage this extension point is fully up to the user. Implementing the prefetch limit can be done using this extension point (e.g. record the post-forward order yourself using forward hooks, iterate over that order, and call the `set_modules_to_forward_prefetch` / `set_modules_to_backward_prefetch` APIs).

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

Differential Revision: [D58700346](https://our.internmc.facebook.com/intern/diff/D58700346)

### CODE REVIEW

**Comment by awgu** [comment]
Example of prefetching 1 FSDP module explicitly in backward:
Screenshot 2024-06-17 at 4 59 33 PM


Example of prefetching 2 FSDP modules explicitly in backward:
Screenshot 2024-06-17 at 4 58 33 PM

**Comment by awgu** [comment]
Example of prefetching 1 FSDP module explicitly in forward:
Screenshot 2024-06-17 at 5 00 02 PM

Example of prefetching 2 FSDP module explicitly in forward:
Screenshot 2024-06-17 at 5 00 31 PM

Example of prefetching 4 FSDP module explicitly in forward:
Screenshot 2024-06-17 at 5 00 48 PM

**Review by ckluk2 — APPROVED** [review]
This is great!

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D58700346).

**Review by weifengpy — APPROVED** [review]

**Review by sanketpurandare — COMMENTED** [review]
Curious to know the use case. This will only help in case of ``FSDPModules`` that have unbalanced compute. So that we can use the compute of a larger ``FSDPModule`` to overlap the prefetch of smaller ones. 

Also, will your extension of wrapping ``List[nn.Module]`` eliminate the need for this?

**Pull request closed without merging**
