### PR TITLE
remove jit from torchbench

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #106394
* __->__ #106071

Need to remove jit arguments after changes in https://github.com/pytorch/benchmark/pull/1787

Also curious, is there is a procedure for updating torchbench version in Pytorch CI?

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

### CODE REVIEW

**Review by xuzhao9 — APPROVED** [review]
LGTM!

**Review by msaroufim — APPROVED** [review]

**Comment by msaroufim** [comment]
Process to update is 
1. Make some change to torchbench and merge it
2. Update this pin with the commit ID of the last merged commit https://github.com/pytorch/pytorch/pull/105222
3. Once you do so there will some expected breakages in CI to add fields to say yes this model will pass and the failure will tell you which command you need to run to make this update

**Review by malfet — APPROVED** [review]

**Review by lezcano — APPROVED** [review]
I was about to post the same fix. It'd be good to get this one merged.

**Comment by msaroufim** [comment]
The failure is because I can't seem to find the right incantation to pass in the HF auth token in CI so my PR would need to be merged first https://github.com/pytorch/pytorch/pull/106009 so if you see an obvious problem @lezcano feel free to comment there I'll be taking a look at this morning

**Comment by msaroufim** [comment]
FYI #106009  was merged so should be able to rebase and merge this @H-Huang

**Comment by H-Huang** [comment]
@msaroufim awesome! thanks, rebasing now

**Pull request closed without merging**
