### PR TITLE
Update torchbench.txt

### PR DESCRIPTION
**Pull request by msaroufim**
Fixes #ISSUE_NUMBER

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

### CODE REVIEW

**Comment by msaroufim** [comment]
Hrrmm seems like background matting already skipped in pt2 dashboard

@pytorbot rebase

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
