### PR TITLE
Fix torch.tensor(...) device-type calculation when used with numpy an…

### PR DESCRIPTION
**Pull request by gchanan**
…d type inference.

### CODE REVIEW

**Comment by gchanan** [comment]
Should fix https://github.com/pytorch/pytorch/issues/6985.

**Comment by zou3519** [comment]
@gchanan The same problem exists for `torch.tensor`:
```

In [6]: import torch

In [7]: x = torch.randn(3, 3, requires_grad=True)

In [8]: torch.tensor(x, device='cuda')
Out[8]:
tensor([[-0.3721,  0.5129,  0.6696],
        [-0.8509,  0.4349,  1.1458],
        [ 0.7075, -3.0103, -0.6825]])

In [9]: torch.tensor(x, device='cuda').device
Out[9]: device(type='cpu')
```
I think this line https://github.com/pytorch/pytorch/blob/2b44c420c8e61501ef04a5e4af2347ecc3c86202/torch/csrc/utils/tensor_new.cpp#L183 might need to be changed too.

**Review by ezyang — APPROVED** [review]

**Comment by gchanan** [comment]
@zou3519 is correct; I'll fix that before merging.

**Comment by karandwivedi42** [comment]
@gchanan Can you please briefly explain how this fixed the problem?
```
type_inference ? type.toScalarType(var.type().scalarType()) : type;
```

**Comment by gchanan** [comment]
Actually, the issue with Variable is more complicated; you want to do type-inference on cuda-ness if device isn't specified, otherwise you don't.

**Pull request merged**
