### PR TITLE
[WIP] Fix torch.tensor not callable

### LINKED ISSUE #24807: Pylint Error `torch.tensor is not callable`
## 🐛 Bug

Pylint returns the error `torch.tensor is not callable`

## To Reproduce

```python
import torch

if __name__ == "__main__":
    t = torch.tensor([1, 2, 3], dtype=torch.float64)
```

```
>>> pipenv run pylint test.py
test.py:4:8: E1102: torch.tensor is not callable (not-callable)
```

## Expected behavior

This shall not raise pylint error

## Environment

```
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.1

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] torch==1.2.0
[conda] Could not collect

Pytorch installed in Pipenv Environment
pylint==2.3.1
```

## Additional context

None

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @bhosmer @smessmer @ljk53 @ailzhang @malfet @rgommers @xuzhao9 @gramster

### PR DESCRIPTION
**Pull request by Microsheep**
This PR resolves #24807

### CODE REVIEW

**Comment by soumith** [comment]
the build failures are legit (atleast some of them)

**Comment by soumith** [comment]
yea build failures are actually legit

**Comment by ucalyptus** [comment]
@Microsheep any updates?

**Comment by Microsheep** [comment]
@ucalyptus I was busy recently and did not have the time to figure out and fix the issues with the tests. If you have ideas on how to solve them, feel free to submit another PR.

**Comment by troiganto** [comment]
Any updates on this? I just started looking into PyTorch and hit this issue almost immediately. Solving this sounds like a pretty good quality-of-life improvement.

**Comment by Bomme** [comment]
Hi all, any updates on this? Seems like this change would be really useful! Any ideas on how I could help with getting this merged?

**Comment by mattpodolak** [comment]
Is this being worked on? I'm encountering this issue in `torch 1.8.1+cu111`

**Comment by troiganto** [comment]
Looks like this PR has been superseded by #53424 and can be closed.

**Pull request closed without merging**
