### PR TITLE
Remove assertEqualIgnoreType from test_pooling

### PR DESCRIPTION
**Pull request by mshuaibii**
Fix TODOs related to https://github.com/pytorch/pytorch/issues/38095 in test_pooling.py.

This PR correctly casts the expected outputs to satisfy the asserts. If you'd prefer feeding `exact_dtype=False` as an argument instead I can update accordingly.

### CODE REVIEW

**Comment by mshuaibii** [comment]
@kit1980

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
Several failures of nn/test_pooling: 
 https://github.com/pytorch/pytorch/actions/runs/3064312432/jobs/4947599351
AssertionError: The values for attribute 'dtype' do not match: torch.float16 != torch.float32.
AssertionError: The values for attribute 'dtype' do not match: torch.float64 != torch.float32.

**Comment by kit1980** [comment]
Looks like the dtype of expected indices needs to be dynamically adjusted.

**Comment by kit1980** [comment]
Not sure why the merge failed...

**Pull request closed without merging**
