### PR TITLE
[Lint] Add FSDP/composable API files to ufmt include

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#90873 [Lint] Add FSDP/composable API files to ufmt include**

This PR adds FSDP and composable API files to `.lintrunner.toml` so that (1) lintrunner enforces that those files are formatted and (2) `lintrunner f` formats those files for you.

There are two requirements here (see https://github.com/pytorch/pytorch/wiki/lintrunner for details):
1. Install lintrunner: 
```
pip install lintrunner
lintrunner init
```
2. `lintrunner f` before you finalize your PR, which would now be enforced by CI after this PR.

The code changes in this PR outside of `.lintrunner.toml` are the result of `lintrunner f`.

---

I only plan to land this PR if all of the composable API developers agree that this is something that makes sense and is not too intrusive to the workflow.

### CODE REVIEW

**Review by yhcharles — APPROVED** [review]
Thanks, LGTM!

**Comment by awgu** [comment]
I will wait for all devs to approve on this one. We can wait until next year to land this when there is slower land velocity.

**Review by mrshenli — APPROVED** [review]
LGTM! Thanks @awgu

**Review by rohan-varma — APPROVED** [review]
Great step in the right direction of enforcing lint!

**Comment by awgu** [comment]
Failure are related to Dynamo and should be unrelated.
```
2023-01-17T17:30:37.5734804Z Traceback (most recent call last):
2023-01-17T17:30:37.5735042Z   File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 440, in _compile
2023-01-17T17:30:37.5735462Z ##[endgroup]
2023-01-17T17:30:37.5735569Z     check_fn = CheckFunctionManager(
2023-01-17T17:30:37.5735804Z   File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 526, in __init__
2023-01-17T17:30:37.5735903Z     local_builder = GuardBuilder(
2023-01-17T17:30:37.5736137Z   File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 109, in __init__
2023-01-17T17:30:37.5736278Z     self.scope["__builtins__"].__dict__[name] = package_module  # type: ignore[index]
2023-01-17T17:30:37.5736452Z AttributeError: 'dict' object has no attribute '__dict__'
```

**Pull request closed without merging**
