### PR TITLE
make RNN export of default hidden state trace correctly

### PR DESCRIPTION
**Pull request by anderspapitto**

### CODE REVIEW

**Comment by anderspapitto** [comment]
ready for review @ezyang @bddppq @apaszke

**Comment by anderspapitto** [comment]
tested by https://github.com/onnxbot/onnx-fb-universe/pull/1352

**Comment by apaszke** [comment]
I'm sorry but when did we decide to go with size-as-tensor operations to implement this? The last discussions I remember were that we're going to do this as a peephole optimization

**Comment by anderspapitto** [comment]
@apaszke replied via another channel, let's discuss there

**Pull request closed without merging**
