### PR TITLE
fix LTC usage of torch.tensor ctr, add test

### PR DESCRIPTION
**Pull request by bdhirsh**
switching the tensor constructor to use `lift_fresh` instead of `lift` silently broken LTC, because we didn't have a test for it. I added one here.

The fix is that LTC now also needs a kernel for `lift_fresh`.

The way this error manifests is that if you call `torch.tensor(..., device='lazy')`, we expect the result to be wrapped up a functional wrapper, and it wasn't - so calling any view ops on the tensor will now break. That wrapping is supposed to happen in `lift_fresh` now.

cc @antoniojkim 

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #81928

### CODE REVIEW

**Review by antoniojkim — APPROVED** [review]
This appears to fix it. Thanks!

**Comment by bdhirsh** [comment]
hmm not sure why CI doesn't like `lift_fresh`...

**Review by wconstab — APPROVED** [review]
cool thanks a lot for fixing @bdhirsh!

**Comment by wconstab** [comment]
cc @JackCaoG, i guess XLA will need lift_fresh too? but it looks like a pretty trivial op to implement.

**Comment by JackCaoG** [comment]
Thanks for the heads up. It seem like pt/xla does not lower `lift`. @bdhirsh Is this one of the ops you added for functionization pass?

**Comment by ezyang** [comment]
Yeah, lift is responsible for taking plain Tensors and turning them into FunctionalTensorWrapper or LazyTensor or whatever is needed in some case.

**Comment by bdhirsh** [comment]
I think XLA can actually get away without implementing `lift` / `lift_fresh` for now - it'll need to implement those two ops once it uses functionalization though.

That's because the tensor constructor today ends up calling:
```
at::empty() // creates buffer on CPU
at::Tensor::to() // moves buffer to the right device (for LTC/XLA, this will also create the XLATensorImpl properly, etc)
at::lift_fresh() // wraps the tensor if necessary, which is needed for functionalization
```

**Pull request closed without merging**
