### PR TITLE
Dispatcher: replace function statics with file statics

### PR DESCRIPTION
**Pull request by nunoplopes**
Function statics are thread-safe and thus there's more overhead than using file statics.
Thread-safety isn't used in this code as python can only call into pytorch in a single-threaded way

After this, I want to try to replace optional+OpHandler with a single function pointer as that's sufficient for dispatching. This would save 3x memory by getting rid of the iterator and the boolean from optional.

### CODE REVIEW

**Comment by ezyang** [comment]
> Thread-safety isn't used in this code as python can only call into pytorch in a single-threaded way

Unfortunately, while this is true in Python, we also support direct calls from C++ where you can't assume that calls to the code are from single thread. So we can't take this patch.

This being said, it *has* always been a stick in my craw that we have to always pay for the thread safe test for the static method. Ideally, we would populate these tables during `init_array` time and then assume that they're well formed; unfortunately (and as it seems like you discovered), this leads to SIOF problems. But maybe the SIOF problem is soluble (e.g., by restructuring registration file structure so that it is guaranteed to be safe to fetch the schema out of the dispatcher) I'd be amenable to looking into it.

**Review by ezyang — CHANGES_REQUESTED** [review]
NACK

**Comment by nunoplopes** [comment]
> > Thread-safety isn't used in this code as python can only call into pytorch in a single-threaded way
> 
> Unfortunately, while this is true in Python, we also support direct calls from C++ where you can't assume that calls to the code are from single thread. So we can't take this patch.

Ah, sorry. I'm very new to PyTorch internals, so still trying to learn the requisites and assumptions.

This initialization code calls `Dispatcher::findSchemaOrThrow()` which uses operatorLookupTable_ without taking any lock, for example.
Can we assume there are no calls to e.g. `Dispatcher::registerDef()` in parallel? Or do you assume all registrations happen during some initialization phase? If that's the case, I find confusing why these `register*` methods return a `RegistrationHandleRAII`, as they should just all be destroyed in batch at the end.
Similarly, the dispatch itself goes to `OperatorEntry` unlocked. Is it ok to assume that that is constant after initialization?

Unrelated question: does PyTorch have a "Python-only" build option where you throw away all/most locks?

FWIW, I'm happy to try a solution where all handlers are initialized after some all of these data-structures are considered immutable. It's possible to work-around the SIOF issues.

**Comment by ezyang** [comment]
> This initialization code calls Dispatcher::findSchemaOrThrow() which uses operatorLookupTable_ without taking any lock, for example.

It's synchronized, just not obviously. Eventually you get to:

```
c10::optional<OperatorHandle> Dispatcher::findOp(const OperatorName& overload_name) {
  return operatorLookupTable_.read([&] (const ska::flat_hash_map<OperatorName, OperatorHandle>& operatorLookupTable) -> c10::optional<OperatorHandle> { 
    auto found = operatorLookupTable.find(overload_name);
    if (found == operatorLookupTable.end()) {
      return c10::nullopt;
    }
    return found->second;
  });
}
```

The `read` is on 

```
  LeftRight<ska::flat_hash_map<OperatorName, OperatorHandle>> operatorLookupTable_;
```

which is a synchronized data structure.

That being said...

>  Or do you assume all registrations happen during some initialization phase? If that's the case, I find confusing why these register* methods return a RegistrationHandleRAII, as they should just all be destroyed in batch at the end.

*Most* registrations do happen in initialization phase (and certainly all the registrations being accessed from the code you've modified here). But the code was written to also support registering operators later (e.g., via a dynamic library load); thus all the RAII safety. (Honestly it probably would be fine to just leak everything at the end, but we did it "properly")

> Unrelated question: does PyTorch have a "Python-only" build option where you throw away all/most locks?

No. And it's also worth noting that *even in Python* multithreaded accesses are possible, because we typically try to release the GIL once we enter into C++.

> FWIW, I'm happy to try a solution where all handlers are initialized after some all of these data-structures are considered immutable. It's possible to work-around the SIOF issues.

I feel like the only way to do this is to actually make sure the dispatcher schema registrations are in the same file as Functions.cpp, since in that case you can assume that static initializers are run in order.

**Comment by swolchok** [comment]
> This being said, it *has* always been a stick in my craw that we have to always pay for the thread safe test for the static.

I'm mobile right now so I can't check (can't even seem to type in Godbolt), but I think the cost is just a load-acquire of an extra flag in steady state, which on x86-64 at least is just a regular load of that flag.

**Comment by nunoplopes** [comment]
> I feel like the only way to do this is to actually make sure the dispatcher schema registrations are in the same file as Functions.cpp, since in that case you can assume that static initializers are run in order.

An easy-ish way would be to do have the global vars register themselves like:
```
static RegisterTypedOperatorHandle<...> op_42;
Tensor foo(..) {
  op_42->Call(args);
}
```

Then:
```
class RegisterTypedOperatorHandle : TypedOperatorHandle {
  RegisterTypedOperatorHandle() {
    Dispatcher::sigleton().registerTypedOH(this);
  }

  // called by Dispatcher after all initializations
  void set(impl::OperatorEntry *entry) {
    // set TypedOperatorHandle 's pointer to entry
  }
}
```

So the dispatcher would have a vector with all the handles that need patching. This list is filled up by the global constructors in some arbitrary order.
When everything is settled, the Dispatcher patches all OperatorHandles and frees up the vector. During run time, it's guaranteed all handles have been patched.

Would something like this work?

**Comment by swolchok** [comment]
> the cost is just a load-acquire of an extra flag in steady state

Yep, it's just a regular `movb` on x86-64: https://godbolt.org/z/Mx8r9s

**Pull request closed without merging**
