### PR TITLE
[inductor] turn on enable_kernel_profile on Windows.

### PR DESCRIPTION
**Pull request by xuhancn**
Enable `TORCHINDUCTOR_CPP_ENABLE_KERNEL_PROFILE` on Windows inductor.

Local tested pass:
image

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jgong5 — DISMISSED** [review]
Can you also turn on the test `test_cpp_kernel_profile` from `test_cpu_repro.py`?

**Comment by xuhancn** [comment]
> Can you also turn on the test `test_cpp_kernel_profile` from `test_cpu_repro.py`?

@jgong5 Done.

**Review by jgong5 — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
