### PR TITLE
Enable ProcessGroupGlooTest in CI

### PR DESCRIPTION
**Pull request by malfet**
Partially addresses https://github.com/pytorch/pytorch/issues/41143

### CODE REVIEW

**Review by rohan-varma — COMMENTED** [review]
I think Dr. CI is getting confused by some of our RPC error-handling tests, those error messages are expected and if one looks at the log, the test actually passed, and it seems that the error comes from here:

```
Jul 24 07:39:19 + build/bin/ProcessGroupNCCLErrorsTest --gtest_output=xml:test/test-reports/cpp-distributed/ProcessGroupNCCLErrorsTest.xml
Jul 24 07:39:19 .jenkins/pytorch/test.sh: line 236: build/bin/ProcessGroupNCCLErrorsTest: No such file or directory
```
@malfet, I'm assuming the above is a legit error caused by this diff? 

We should probably fix our RPC error handling tests so that they don't trip up Dr. CI, though. We have a bunch of tests where we intentionally raise exceptions/errors and ensure that we handle them appropriately/don't crash in the RPC framework.

**Comment by malfet** [comment]
@rohan-varma, no the test should be green, I've just enabled the tests at the wrong configuration (should have been enabled only for CUDA, but I did it other way around)

**Review by rohan-varma — APPROVED** [review]
Thanks for adding this!

**Comment by mrshenli** [comment]
Thanks @malfet for enabling these tests! Our tests fail in some CI envs. We will fix and I created #42073 to track. Reverting this PR to make master clear.

**Pull request closed without merging**
