### PR TITLE
[Inductor Cutlass backend] Move tests to separate file

### PR DESCRIPTION
**Pull request by kadeng**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #121492
* #121734
* #121497
* #121491
* #121490
* __->__ #121489

Move Cutlass backend related tests to test/inductor/test_cutlass_backend.py - no changes to the tests themselves.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by aakhundov** [comment]
@kadeng there are 14 failing jobs, but I don't see as many in the trunk: https://hud.pytorch.org/ . Could you rebase, maybe onto viable/strict?

**Review by jansel — APPROVED** [review]
Assuming this is moving stuff around now changing anything

**Comment by kadeng** [comment]
> @kadeng there are 14 failing jobs, but I don't see as many in the trunk: https://hud.pytorch.org/ . Could you rebase, maybe onto viable/strict?

Did that by cherry-picking on top of a recent clean viable/strict checkout, CI is running again.

**Pull request closed without merging**
