### PR TITLE
[WIP] Refactor distributed code via device-agnostic API

### PR DESCRIPTION
**Pull request by guangyey**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #132371
* #137493
* #138677
* #133572

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Comment by guangyey** [comment]
Closed as duplicated with xccl upstream.

**Comment by kwen2501** [comment]
Curious, is this PR dependent on https://github.com/pytorch/pytorch/pull/132204? 
If not, we may be still interested in this PR if it makes distributed library more device agnostic (or using the more formal torch runtime APIs).

**Comment by guangyey** [comment]
> If not, we may be still interested in this PR if it makes distributed library more device agnostic (or using the more formal torch runtime APIs).

This PR depends on https://github.com/pytorch/pytorch/pull/132204. We will continue to complete and refine  https://github.com/pytorch/pytorch/pull/132204 and make distributed library more generic.

**Comment by kwen2501** [comment]
Sounds good, thanks!

**Comment by guangyey** [comment]
closed as it is duplicated with https://github.com/pytorch/pytorch/pull/137678

**Pull request closed without merging**
