### PR TITLE
Add test tracking operators without decompositions

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #90887

This test inspects the dispatcher directly, so captures operators without
`OpInfo` including internal helper operators and backward operators that might
appear in a trace.

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
I didn't find `linalg_solve_triangular` in the expected list, but that one has explicit CPU and CUDA dispatches. What's going on there?

**Review by ezyang — APPROVED** [review]
This seems... fine, I guess? Automatically updating the expect file works right? Cc @SherlockNoMad

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your PR. We reverted https://github.com/pytorch/pytorch/pull/70988 in https://hud.pytorch.org/pytorch/pytorch/commit/acdd462b1a070790799ce4623ce8ecc83e197e81 and this test starts to fail. 
 There is probably a dependency between the twos.' -c weird

**Comment by huydhn** [comment]
Please do a rebase to master and rerun the tests

**Pull request closed without merging**
