### PR TITLE
Delete tracing_mode argument to export

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99555
* #99554

You can have any color you want, as long as it's tracing_mode="symbolic"

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]

**Comment by DanilBaibak** [comment]
@ezyang sorry, I have to revert your PR. It leads to internal failures. Here you can find more details - [D45216014](https://www.internalfb.com/diff/D45216014).

**Pull request closed without merging**
