### PR TITLE
[DDP] Fix test

### PR DESCRIPTION
**Pull request by rohan-varma**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #103867
* #103866
* __->__ #103629

Now with multi-forward support, non-reentrant checkpoint is supported.

Differential Revision: [D46745049](https://our.internmc.facebook.com/intern/diff/D46745049/)

### CODE REVIEW

**Review by osalpekar — APPROVED** [review]

**Review by fduwjj — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Comment by rohan-varma** [comment]
@huydhn @osalpekar looks like a bunch of CI jobs are broken, but for unrelated reasons (even distributed is failing with some UCC related things, I guess these tests don't run regularly so they are probably flaky). 

I created https://github.com/pytorch/pytorch/issues/103872 to disable the checkpointing test, but maybe we should just revert the entire stack over at https://github.com/pytorch/pytorch/pull/103487.

**Comment by huydhn** [comment]
> I created #103872 to disable the checkpointing test, but maybe we should just revert the entire stack over at #103487.

Agree that reverting would be the easiest mitigation, so there is no pressure to fix this right away.  Let me go ahead with that.

**Comment by huydhn** [comment]
cc @rohan-varma @osalpekar Here is the revert PR https://github.com/pytorch/pytorch/pull/103873.  I create this instead of using the bot because the change was landed last week and I'm not sure if using the bot would mess up diff train

**Comment by rohan-varma** [comment]
> cc @rohan-varma @osalpekar Here is the revert PR https://github.com/pytorch/pytorch/pull/103873.  I create this instead of using the bot because the change was landed last week and I'm not sure if using the bot would mess up diff train

Stamped the revert.

**Pull request closed without merging**
