### PR TITLE
Fix multi output layout error in indexing dtype calculation

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108085

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

Differential Revision: [D48757829](https://our.internmc.facebook.com/intern/diff/D48757829)

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Review by davidberard98 — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48757829).

**Review by peterbell10 — APPROVED** [review]

**Comment by atalman** [comment]
@eellison please cherry pick this change to release/2.1 and post it to 2.1 tracker

**Pull request closed without merging**
