### PR TITLE
Add test to xfail_list only for abi_compatible

### PR DESCRIPTION
**Pull request by chunyuan-w**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128506

https://github.com/pytorch/pytorch/pull/126717 will skip the tests in both ABI compatible and non-ABI compatible mode. 
It's not expected to skip them in non-ABI compatible mode since they can actually run successfully in such mode but only have issues in ABI compatible mode.

We leverage the existing `xfail_list` for those that will only fail in ABI compatible mode.

- `test_qlinear_add` is already in the `xfail_list`.
- `test_linear_packed` doesn't fail either in my local run (running with `TORCHINDUCTOR_ABI_COMPATIBLE=1`) or in the CI of this PR so I didn't add it into `xfail_list`.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Review by desertfire — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but it causes an inductor test to fail in trunk https://hud.pytorch.org/pytorch/pytorch/commit/49366b2640df1cba5a3b40bedd31b57b08529612' -c nosignal

I'll add `ciflow/inductor` to surface the error on your PR.

**Comment by chunyuan-w** [comment]
Hi @huydhn I've rebased the PR to the latest main and the CI has been re-triggered but still shows that no failure is introduced by this PR. Any idea what is missing here?
image

**Comment by huydhn** [comment]
My bet is that this is a landrace that has been resolved somehow after you rebase.  Let me merge and see it run in trunk as your PR is green.

**Comment by chunyuan-w** [comment]
> My bet is that this is a landrace that has been resolved somehow after you rebase. Let me merge and see it run in trunk as your PR is green.

Got it, thanks!

**Comment by huydhn** [comment]
@pytorchbot revert -m 'The failure shows up in trunk https://hud.pytorch.org/pytorch/pytorch/commit/df85f34a14dd30f784418624b05bd52b12ab8b0b' -c weird

I'm seeing the same tests failing on trunk while green on your PR.  Let me revert it now and take a look tomorrow.  In the meantime, could you help rebase your stack to latest commit on PyTorch main?  It's ghstack, so only you can do the rebase.

**Comment by chunyuan-w** [comment]
> @pytorchbot revert -m 'The failure shows up in trunk https://hud.pytorch.org/pytorch/pytorch/commit/df85f34a14dd30f784418624b05bd52b12ab8b0b' -c weird
> 
> I'm seeing the same tests failing on trunk while green on your PR. Let me revert it now and take a look tomorrow. In the meantime, could you help rebase your stack to latest commit on PyTorch main? It's ghstack, so only you can do the rebase.

The error showed up when I rebased it (not sure why no such error in previous tries). I tried to fix it and pushed the changes. The CI is now green (all failures are marked as unrelated to this PR). Let me try to re-land it.

**Pull request closed without merging**
