### PR TITLE
[inductor][ci] Fix torchbench dependency issue with numpy

### LINKED ISSUE #128845: inductor_torchbench_perf jobs are broken due to numpy 2.0 update
## Current Status
*Status could be: ongoing

## Error looks like
Torch Bench testing is broken with errors that look like https://github.com/pytorch/pytorch/actions/runs/9534138639/job/26278709111

## Incident timeline (all times pacific)
Inductor CI has been broken since 5:41 PM PT on June 14, 2024.
It was detected the next day and root caused the morning on June 17th.

## User impact
The affected inductor ci jobs (those related to torchbench perf) shall be marked as unstable until this issue is mitigated.

## Root cause
We suspect it's due to the numpy 2.0 update. (https://numpy.org/devdocs/release/2.0.0-notes.html) 

## Mitigation
Ongoing

Current plan is for [eellison](https://github.com/eellison) to pin numpy for torchbench workflows

## Prevention/followups
TBD

### PR DESCRIPTION
**Pull request by xuzhao9**
For some reason, pip will always upgrade the numpy version even when an older version has been installed.
We have to lock numpy version to the old version to make this constraint explicit.

Torchbench commit: https://github.com/pytorch/benchmark/commit/23512dbebd44a11eb84afbf53c3c071dd105297e

Second attempt to fix #128845

### CODE REVIEW

**Comment by xuzhao9** [comment]
Test dashboard workflow: https://github.com/pytorch/pytorch/actions/runs/9568709257

**Review by eellison — APPROVED** [review]

**Pull request closed without merging**
