### PR TITLE
[inductor] [cpp] use non-temporal tile load for A

### PR DESCRIPTION
**Pull request by chunyuan-w**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #129348
* __->__ #129455

Use non-temporal tile load `_tile_stream_loadd` for A to keep B in L1.
Verified AMP static shapes and dynamic shapes on CPU with AMX support and no obvious performance boost (no regression either) at end-to-end level. We're expecting to get performance gain when adding https://github.com/pytorch/pytorch/pull/129348 (also in this ghstack) on top of this PR.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jgong5 — COMMENTED** [review]
Share perf numbers?

**Comment by chunyuan-w** [comment]
> Share perf numbers?

Updated the performance status in the PR description: 
No obvious performance boost (no regression either) at end-to-end level by only changing to non-temporal load. We're expecting to get more performance gain after tuning the cache blocking (https://github.com/pytorch/pytorch/pull/129348 also in this ghstack) on top of this PR.

**Review by jgong5 — APPROVED** [review]

**Pull request closed without merging**
