### PR TITLE
Raise error when call from_numpy on 0-dim array

### LINKED ISSUE #2055: zero-dimensional numpy arrays should raise exception on from_numpy
It seems that the way how slicing is handled in pytorch is a little bit inconsistent with numpy and with pytorch itself. For example, one can create a tensor with empty dimension like 0x3 matrix (in numpy and pytroch). However, when trying to get a slice that will lead to no dimension tensor "ValueError: result of slicing is an empty tensor" error occurs. Is there any reason for implementing it differently compare to numpy?

### PR DESCRIPTION
**Pull request by lynic**
Fixes: #2055

### CODE REVIEW

**Comment by hughperkins** [comment]
Hmmm. You know, in cltorch, I used to have 0-dimensinoal tensors. I used this to eg store the results of full reductions, to avoid implicit sync points, https://github.com/hughperkins/cltorch#point-tensors-reduce-pipeline-stalls

**Comment by soumith** [comment]
thanks @lynic !

**Comment by soumith** [comment]
@hughperkins the TH / THC libraries weren't designed for zero-dim Tensors, so changing them is a careful thing we'd have to do. We are unlikely to do it anytime soon.

**Comment by hughperkins** [comment]
> @hughperkins the TH / THC libraries weren't designed for zero-dim Tensors, so changing them is a careful thing we'd have to do. We are unlikely to do it anytime soon.

Yes, looks like it took me a couple of days last time :-(

screen shot 2017-07-13 at 3 02 25 pm

screen shot 2017-07-13 at 3 02 32 pm

**Comment by hughperkins** [comment]
(but yeah, it was quite buggy... )

**Comment by apaszke** [comment]
BTW this fix seems incomplete - TH, THC don't support 0-sized dims, but they do support empty tensors (no dims)

**Comment by soumith** [comment]
@apaszke I couldn't find a way to create a 0-dim numpy ndarray without it being a scalar.

**Pull request merged**
