### PR TITLE
[dynamo] Dispatch take_along_axis to take_along_dim

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #107875

Addresses https://github.com/pytorch/pytorch/pull/107711#issuecomment-1691706303

I'll have someone submit a decomposition of `take_along_dim` next week.

cc @mruberry @rgommers @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

### CODE REVIEW

**Review by ev-br — APPROVED** [review]
LGTM

**Review by peterbell10 — APPROVED** [review]

**Review by peterbell10 — CHANGES_REQUESTED** [review]
Looks like this needs a meta implementation.

**Comment by lezcano** [comment]
Done in https://github.com/pytorch/pytorch/pull/108880#pullrequestreview-1618672157

**Pull request closed without merging**
