### PR TITLE
fixed typo in documentation

### PR DESCRIPTION
**Pull request by shazqadeer**
Summary: Fixed typo in documentation. Trying to get familiar with the PR workflow for contributing to PyTorch.

Test Plan: None

Reviewers:

Subscribers:

Tasks:

Tags:

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by ezyang** [comment]
You accidentally updated submodule. https://fb.workplace.com/groups/1144215345733672/posts/2585581408263718 will help

**Comment by shazqadeer** [comment]
> You accidentally updated submodule. https://fb.workplace.com/groups/1144215345733672/posts/2585581408263718 will help

Thanks. I reverted the change.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Check https://github.com/pytorch/pytorch/wiki/Bot-commands#merge for how to merge it yourself

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
