### PR TITLE
Do not print warning if CUDA driver could not be found

### LINKED ISSUE #47038: PyTorch 1.7.0 CUDA driver warning
## 🐛 Bug

The following warning appears only on `torch==1.7.0`

```
../../../virtualenv/python3.8.3/lib/python3.8/site-packages/torch/cuda/__init__.py:52

  /home/travis/virtualenv/python3.8.3/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)

    return torch._C._cuda_getDeviceCount() > 0
```

Looking at the [pull request](https://github.com/pytorch/pytorch/pull/42249) that introduced it, no warning should be raised for "call to device_count()" with "no gpus"

Having to filter this warning every time `device_count` is called is not ideal.

## To Reproduce

`torch.cuda.device_count()`

## Expected behavior

Does not raise a warning.

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @ngimel

### PR DESCRIPTION
**Pull request by malfet**
As result of this change `torch.cuda.get_device_count()` would not print a warning if CUDA driver is not installed on the system, but `torch.cuda.is_available()` will.
Rationale behind that, is that calle of `torch.cuda.is_available()` would probably want to know, why CUDA is not available on the system (if package was compiled with CUDA support), but callee of 'device_count()` just want to know number of available devices, which is 0 if CUDA is not installed.

The warning would still be printed if CUDA driver is too old with the runtime, or if CUDA device discovery fails.

Introduce `c10::cuda::driver_available()` predicate, that returns true, if CUDA driver is installed and prints warning and returns false if it could not be found
Modify `c10::cuda::device_count()` not to print a warning if CUDA driver is not installed
Add Python wrapper for expose `c10::cuda::device_count`

Test Plan: Rename "libcuda.so.1" to "libcuda.so.2" and run `python -c "import torch; torch.randn(3, 3, requires_grad=True).sum().backward()"`

Fixes https://github.com/pytorch/pytorch/issues/47038

### CODE REVIEW

**Comment by dzhulgakov** [comment]
Hm, based on votes on the issue it seems preferred for `is_available` to not produce the warning. Maybe neither of them should produce any warnings for simplicity?

If I were to choice I'd make `device_count` produce a warning but `is_availble` - not.

**Comment by ezyang** [comment]
Yeah I also got the sense that people just wanted the warning to shut up. When is the last time this actually helped someone diagnose a problem?

**Comment by malfet** [comment]
Problem is, `c10::cuda::device_count()` and its Python `torch.cuda.device_count()` counterpart  is used a lot throughout the code(for example, when deciding to start autograd threads, which causes the warning to be printed while calling `.backward()` for the CPU tensor`, while `is_available` is mostly used in tests.

IMO a good litmus test for the change should be: warning is not printed while running CPU only code.

But I'm totally fine with killing the warning when CUDA driver is not installed altogether, see https://github.com/pytorch/pytorch/pull/51806

**Comment by malfet** [comment]
Abandoning in favor of #51806

**Pull request closed without merging**
