### PR TITLE
Ensure tests get passed on Windows

### PR DESCRIPTION
**Pull request by peterjc123**
(1) check error codes after every test command
(2) add missing LibTorch tests mentioned in https://discuss.pytorch.org/t/pre-compiled-tests-failing/54166

### CODE REVIEW

**Comment by peterjc123** [comment]
```
======================================================================
FAIL: test_constructor_with_args (__main__.TestCustomOperators)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_custom_classes.py", line 23, in setUp
    ops.load_library(get_custom_class_library_path())
  File "test_custom_classes.py", line 10, in get_custom_class_library_path
    assert (len(library_filename) == 1)
AssertionError

======================================================================
FAIL: test_function_call_with_args (__main__.TestCustomOperators)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_custom_classes.py", line 23, in setUp
    ops.load_library(get_custom_class_library_path())
  File "test_custom_classes.py", line 10, in get_custom_class_library_path
    assert (len(library_filename) == 1)
AssertionError

======================================================================
FAIL: test_function_method_wrong_type (__main__.TestCustomOperators)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_custom_classes.py", line 23, in setUp
    ops.load_library(get_custom_class_library_path())
  File "test_custom_classes.py", line 10, in get_custom_class_library_path
    assert (len(library_filename) == 1)
AssertionError

======================================================================
FAIL: test_no_return_class (__main__.TestCustomOperators)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_custom_classes.py", line 23, in setUp
    ops.load_library(get_custom_class_library_path())
  File "test_custom_classes.py", line 10, in get_custom_class_library_path
    assert (len(library_filename) == 1)
AssertionError

======================================================================
FAIL: test_stack_push_pop (__main__.TestCustomOperators)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_custom_classes.py", line 23, in setUp
    ops.load_library(get_custom_class_library_path())
  File "test_custom_classes.py", line 10, in get_custom_class_library_path
    assert (len(library_filename) == 1)
AssertionError

======================================================================
FAIL: test_stack_string (__main__.TestCustomOperators)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_custom_classes.py", line 23, in setUp
    ops.load_library(get_custom_class_library_path())
  File "test_custom_classes.py", line 10, in get_custom_class_library_path
    assert (len(library_filename) == 1)
AssertionError

----------------------------------------------------------------------
```

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Let's disable the rotted tests on Windows for now, and file bugs for them. More important to get signal going for the other tests.

**Comment by peterjc123** [comment]
@ezyang Disabled all the failed tests,

**Pull request closed without merging**
