### PR TITLE
fix serialization of nn.Parameter with dill

### LINKED ISSUE #9981: Torch.save with dill
## Issue description

With the release of PyTorch 0.4.1, ``torch.save`` with dill now breaks.

## Code example

```
import torch
import dill
net = torch.nn.LSTM(10, 10)
torch.save(net, 'save.pt') # Works
torch.save(net, 'save.pt', pickle_module=dill) # Recursion error
```
```
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dill/dill.py", line 1015, in save_super
    pickler.save_reduce(super, (obj.__thisclass__, obj.__self__), obj=obj)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dill/dill.py", line 1015, in save_super
    pickler.save_reduce(super, (obj.__thisclass__, obj.__self__), obj=obj)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/site-packages/dill/dill.py", line 1015, in save_super
    pickler.save_reduce(super, (obj.__thisclass__, obj.__self__), obj=obj)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/pickle.py", line 461, in save
    pid = self.persistent_id(obj)
  File "/Users/michaelp/.pyenv/versions/3.6.5/lib/python3.6/site-packages/torch/serialization.py", line 244, in persistent_id
    elif torch.is_storage(obj):
RecursionError: maximum recursion depth exceeded
```

### PR DESCRIPTION
**Pull request by elanmart**
Should resolve #9981.

### CODE REVIEW

**Comment by ezyang** [comment]
This will lose backward hooks, you'll need to serialize (and reconstitute them as well).

**Comment by ezyang** [comment]
See also #10220, where we have a parallel code path specifically for the multiprocessing serialization case.

**Comment by ailzhang** [comment]
@elanmart  Could you update the diff to include backward hooks like here? https://github.com/pytorch/pytorch/pull/10220/files#diff-0d553ed0e9ca41fdac21632b4d503a10R41

**Comment by elanmart** [comment]
@ailzhang please excuse my late response, I was having a few days off. Yes, of course I'll do my best to fix that.

**Comment by SsnL** [comment]
No rush. Just wondering if there is any progress on this?

**Comment by elanmart** [comment]
@SsnL well yeah there's really no excuse, I lost track of this PR, which kept people waiting.

I'm not sure how the multiprocessing codepath should affect the solution here. Is sticking an extra `classmethod` to the `nn.Parameter` an acceptable solution?

**Comment by SsnL** [comment]
@elanmart Adding a classmethod is fine by me, but it seems to break other things (see CI).

**Comment by elanmart** [comment]
@SsnL the CI seems to run fine now, what do you think?

**Review by ssnl — APPROVED** [review]
Thanks! LGTM. I wonder if we should install dill in CI and add a test...

**Review by soumith — APPROVED** [review]

**Comment by tscholak** [comment]
Hi @elanmart
Serialization of my model with dill works with pytorch 0.4.0, but stopped working in 0.4.1.
I just tried to serialize it with torch-nightly 1.0.0.dev20180930, but unsuccessfully so.
I hit the default recursion limit, and increasing it results in a segfault. Any ideas?
Thanks.

**Comment by tscholak** [comment]
Never mind, found this problem raised here: https://github.com/pytorch/pytorch/issues/9981. Will continue the discussion there.

**Comment by tscholak** [comment]
I just had a look at the initial issue, https://github.com/pytorch/pytorch/issues/9981.
The error I'm seeing on torch-nightly 1.0.0.dev20180930 is identical.
Either your patch is not in there, or it doesn't have the desired effect.

**Comment by tscholak** [comment]
Argh, never mind. I was still on torch 0.4.1 because a dependency pulled it in.
It is really unfortunate that the nightly build of torch is not called `torch`, but `torch-nightly`...
that is a headache for package management.

**Pull request closed without merging**
