### PR TITLE
[WIP]change default tensor_adam to multi_tensor_adam

### PR DESCRIPTION
**Pull request by FindHao**
I changed default tensor_adam to mutli_tensor_adam and would like to test its performance.

Test plan: TorchBench CI

RUN_TORCHBENCH: ALL

### CODE REVIEW

**Comment by albanD** [comment]
@ngimel are these ready to be turned on by default?

**Comment by FindHao** [comment]
A related issue https://github.com/pytorch/pytorch/issues/78807

**Comment by ngimel** [comment]
> @ngimel are these ready to be turned on by default?

Not until #78807 is fixed (also ideally we should be able to use #81705 soon

**Comment by FindHao** [comment]
@ngimel Hi Natalia, sorry for the late update. Could you please tell me if `foreach` is ready to turn on by default?

**Comment by albanD** [comment]
I don't think we can do such general enablement as there are many device/dtype that foreach don't support. @janeyx99 will look into this though.

**Pull request closed without merging**
