### PR TITLE
add `OpInfo` for `torch.nn.functional.nll_loss`

### PR DESCRIPTION
**Pull request by pmeier**
Addresses facebookresearch/functorch#78.

cc @albanD @mruberry @jbschlosser @VitalyFedyunin @walterddr

### CODE REVIEW

**Comment by pmeier** [comment]
[Failures](https://app.circleci.com/pipelines/github/pytorch/pytorch/369159/workflows/8963df87-9139-44ec-97fb-cc4b5324acf6/jobs/15575198/tests#failed-test-0) on CUDA look real:

```
torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor(-0.4172, device='cuda:0')
analytical:tensor(-0.3553, device='cuda:0')

The above quantities relating the numerical and analytical jacobians are computed 
in fast mode. See: https://github.com/pytorch/pytorch/issues/53876 for more background 
about fast mode. Below, we recompute numerical and analytical jacobians in slow mode:

Numerical:
 tensor([[ 0.0000],
        [ 0.0000],
        [-0.5000],
        [ 0.0000],
        [ 0.0000],
        [-0.5000]], device='cuda:0')
Analytical:
tensor([[ 0.0000],
        [ 0.0000],
        [-0.5000],
        [ 0.0000],
        [ 0.0000],
        [-0.5000]], device='cuda:0')

The max per-element difference (slow mode) is: 3.62396240234375e-05.
Fast gradcheck failed but element-wise differences are small. This means that the
test might've passed in slow_mode!
```

Failures also happen in slow mode, i.e. setting `gradcheck_fast_mode=False`.

**Comment by zou3519** [comment]
@pmeier what does the error look like with `gradcheck_fast_mode=False`?

**Comment by pmeier** [comment]
The same as the middle part of the message above.

**Comment by pmeier** [comment]
I think the failures are due to non-determinism that stems from reducing the output to a scalar. Setting `reduction="none"` passes the tests without modification.

**Comment by pmeier** [comment]
Closed in favor of #64203.

**Pull request closed without merging**
