### PR TITLE
[Torch] Add more mm kernel choices

### PR DESCRIPTION
**Pull request by henryhu6**
Differential Revision: D56616836

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by htyu** [comment]
Thanks for working on this. 

Can I ask where do you get the new configs and how they move the perf numbers?

BTW, there are already-tuned numbers in the Triton code base : https://github.com/openai/triton/blob/20c912439059a017d099d2e5903caa640bfb1373/python/triton/ops/matmul.py#L57. Do you think it's worth exploring them?

**Comment by henryhu6** [comment]
> Thanks for working on this.
> 
> Can I ask where do you get the new configs and how they move the perf numbers?
> 
> BTW, there are already-tuned numbers in the Triton code base : https://github.com/openai/triton/blob/20c912439059a017d099d2e5903caa640bfb1373/python/triton/ops/matmul.py#L57. Do you think it's worth exploring them?

We have a for loop that tries out all combinations, and landed at these new sets. It yield 5% perf gain.

cc: @mxz297

**Comment by htyu** [comment]
> > Thanks for working on this.
> > Can I ask where do you get the new configs and how they move the perf numbers?
> > BTW, there are already-tuned numbers in the Triton code base : https://github.com/openai/triton/blob/20c912439059a017d099d2e5903caa640bfb1373/python/triton/ops/matmul.py#L57. Do you think it's worth exploring them?
> 
> We have a for loop that tries out all combinations, and landed at these new sets. It yield 5% perf gain.
> 
> cc: @mxz297

5% perf gain is great! How much compile-time increase did you see?

**Comment by henryhu6** [comment]
> 5% perf gain is great! How much compile-time increase did you see?

I did not fully time it, it definitely increased it, but less than double.

**Review by htyu — APPROVED** [review]

**Comment by eellison** [comment]
Less than double what ? can we get a perf run of this before landing.

**Comment by htyu** [comment]
> Less than double what ? can we get a perf run of this before landing.

The mm template is only used in a few OSS models, so I'd expect the general compile-time impact is low. But yeah good to have a perf run before landing.

**Comment by kit1980** [comment]
@eellison @htyu this is already landed in fbcode.
If you have concerns about landing this, revert in fbcode ASAP.

**Comment by eellison** [comment]
> The mm template is only used in a few OSS models, so I'd expect the general compile-time impact is low. But yeah good to have a perf run before landing.

We benchmark all the options, so whether or not they are used the compile-time impact will be the same.

**Comment by eellison** [comment]
These were the perf and compilation time increases from this pr. Since for some reason recent max autotune benchmarking didnt fire, I compared form recent run I did for gh/eellison/630/head. The training numbers were pretty stable but inference increased a lot, I'm not sure why yet. 

image


image


cc @jansel, @Chillee @shunting for thoughts

**Pull request closed without merging**
