### PR TITLE
[JIT][Symbolic Shape Analysis] expose op shape functions

### PR DESCRIPTION
**Pull request by makslevental**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #68748

Differential Revision: [D32598605](https://our.internmc.facebook.com/intern/diff/D32598605)

### CODE REVIEW

**Comment by makslevental** [comment]
@makslevental has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32598605).

**Comment by makslevental** [comment]
@makslevental has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32598605).

**Comment by makslevental** [comment]
@makslevental has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32598605).

**Comment by makslevental** [comment]
@makslevental has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32598605).

**Review by eellison — APPROVED** [review]

**Comment by makslevental** [comment]
@silvasean all set (sorry it took so long - flaky internal tests ...)

**Comment by silvasean** [comment]
> @silvasean all set (sorry it took so long - flaky internal tests ...)

Awesome! Yep, I've had my fair share of internal flaky tests too in a past life :)

**Pull request closed without merging**
