### PR TITLE
Enable distributed autograd tests for >py36

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#27166 Enable distributed autograd tests for >py36**

Differential Revision: [D17694691](https://our.internmc.facebook.com/intern/diff/D17694691)

### CODE REVIEW

**Comment by zhaojuanmao** [comment]
add to this file https://our.internmc.facebook.com/intern/diffusion/FBS/browse/master/fbcode/caffe2/test/run_test.py

if PY36:
    TESTS.append('jit_py3', 'rpc_spawn', 'dist_autograd_spawn')

**Review by zhaojuanmao — APPROVED** [review]
needs to rebase?

**Comment by pietern** [comment]
This was reverted in bb8983e9369eb9d70738363afef0172d8fbfe6bb.

Problem:

```
Oct 01 22:50:21 + python test/run_test.py --include nn --verbose
Oct 01 22:50:22 Traceback (most recent call last):
Oct 01 22:50:22   File "test/run_test.py", line 69, in <module>
Oct 01 22:50:22     TESTS.append('dist_autograd_spawn', 'jit_py3', 'rpc_spawn')
Oct 01 22:50:22 TypeError: append() takes exactly one argument (3 given)
```

Why was this merged without waiting for CI?

**Comment by mrshenli** [comment]
@pietern 

Yes, I reverted it. Master was broken, I was trying to rush in a hotfix. Shouldn't have rushed at all. My bad.

**Pull request closed without merging**
