### PR TITLE
update xla pin

### PR DESCRIPTION
**Pull request by bdhirsh**
https://github.com/pytorch/pytorch/pull/124488 got reverted due to some failures that looked related to the XLA pin update, so I'm putting the pin update into a separate PR

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #124489
* #124840
* __->__ #124839

### CODE REVIEW

**Comment by JackCaoG** [comment]
real error seems to be 
```

2024-04-24T15:37:20.3751083Z + python3 /var/lib/jenkins/workspace/xla/test/test_grad_checkpoint.py
2024-04-24T15:37:22.7356000Z WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
2024-04-24T15:37:22.7356923Z I0000 00:00:1713973042.735060   34465 cpu_client.cc:424] TfrtCpuClient created.
2024-04-24T15:37:33.0258225Z I0000 00:00:1713973053.024780   34465 cpu_client.cc:427] TfrtCpuClient destroyed.
2024-04-24T15:37:33.0398851Z *** Received signal 11 ***
2024-04-24T15:37:33.0399260Z *** BEGIN MANGLED STACK TRACE ***
2024-04-24T15:37:33.0432507Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git62a2b11-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(+0x4d93c76)[0x7f35907bec76]
2024-04-24T15:37:33.0433851Z /lib/x86_64-linux-gnu/libpthread.so.0(+0x13140)[0x7f37c24d5140]
2024-04-24T15:37:33.0434908Z /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(+0xf5e269)[0x7f37b4442269]
2024-04-24T15:37:33.0467060Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git62a2b11-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(__xla_cpu_runtime_ParallelForkJoin+0x330)[0x7f359129bec0]
2024-04-24T15:37:33.0468320Z [0x7f37aebba185]
2024-04-24T15:37:33.0489090Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git62a2b11-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(+0x4dc0a19)[0x7f35907eba19]
2024-04-24T15:37:33.0517076Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git62a2b11-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(+0x4dbf0d3)[0x7f35907ea0d3]
2024-04-24T15:37:33.0555200Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git62a2b11-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(_ZN5Eigen15ThreadPoolTemplIN3tsl6thread16EigenEnvironmentEE10WorkerLoopEi+0x1b1)[0x7f359847e961]
2024-04-24T15:37:33.0590815Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git62a2b11-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(_ZN4absl12lts_2023080222internal_any_invocable13RemoteInvokerILb0EvRZN3tsl6thread16EigenEnvironment12CreateThreadESt8functionIFvvEEEUlvE_JEEET0_PNS1_15TypeErasedStateEDpNS1_18ForwardedParameterIT2_E4typeE+0x48)[0x7f359847cb28]
2024-04-24T15:37:33.0624792Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git62a2b11-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(+0xca3ec11)[0x7f3598469c11]
2024-04-24T15:37:33.0626117Z /lib/x86_64-linux-gnu/libpthread.so.0(+0x7ea7)[0x7f37c24c9ea7]
2024-04-24T15:37:33.0626808Z /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f37c229aa2f]
2024-04-24T15:37:33.0627331Z *** END MANGLED STACK TRACE ***
2024-04-24T15:37:33.0627605Z 
2024-04-24T15:37:33.0856630Z *** Begin stack trace ***
2024-04-24T15:37:33.0857056Z 	tsl::CurrentStackTrace[abi:cxx11]()
2024-04-24T15:37:33.0857445Z 	
2024-04-24T15:37:33.0857671Z 	
2024-04-24T15:37:33.0857889Z 	
2024-04-24T15:37:33.0858141Z 	__xla_cpu_runtime_ParallelForkJoin
2024-04-24T15:37:33.0858513Z 	
2024-04-24T15:37:33.0858734Z 	
2024-04-24T15:37:33.0858940Z 	
2024-04-24T15:37:33.0859375Z 	Eigen::ThreadPoolTempl<tsl::thread::EigenEnvironment>::WorkerLoop(int)
2024-04-24T15:37:33.0860873Z 	void absl::lts_20230802::internal_any_invocable::RemoteInvoker<false, void, tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&>(absl::lts_20230802::internal_any_invocable::TypeErasedState*)
2024-04-24T15:37:33.0862276Z 	
2024-04-24T15:37:33.0862504Z 	
2024-04-24T15:37:33.0862734Z 	clone
2024-04-24T15:37:33.0862980Z *** End stack trace ***
2024-04-24T15:37:33.7840567Z ./test/run_tests.sh: line 48: 34465 Aborted                 (core dumped) python3 "$@"
```
Is this consistently failing? Let me check if XLA side CI.

**Comment by JackCaoG** [comment]
yea on our end this is passing
```
+ run_test /__w/xla/xla/pytorch/xla/test/test_grad_checkpoint.py
+ echo 'Running in PjRt runtime: /__w/xla/xla/pytorch/xla/test/test_grad_checkpoint.py'
Running in PjRt runtime: /__w/xla/xla/pytorch/xla/test/test_grad_checkpoint.py
++ command -v nvidia-smi
+ '[' -x '' ']'
+ PJRT_DEVICE=CPU
+ CPU_NUM_DEVICES=1
+ run_coverage /__w/xla/xla/pytorch/xla/test/test_grad_checkpoint.py
+ '[' 0 '!=' 0 ']'
+ python3 /__w/xla/xla/pytorch/xla/test/test_grad_checkpoint.py
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1713974381.235396    6777 cpu_client.cc:424] TfrtCpuClient created.
I0000 00:00:1713974391.153017    6777 cpu_client.cc:427] TfrtCpuClient destroyed.
```
let's retrigger the test and see if it passes.

**Comment by huydhn** [comment]
Please ignore the flaky classification about XLA on Dr.CI for now while I'm working on a fix.  Please only merge it when XLA job is green.

**Comment by bdhirsh** [comment]
Will do, thanks @huydhn.

@JackCaoG I kicked off the XLA job again: https://github.com/pytorch/pytorch/actions/runs/8817541408/job/24216986968?pr=124839.

I see this in the failure though, which looks different from the previous run?
```
======================================================================
FAIL: test_resnet18 (__main__.DynamoTrainingBasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/xla/test/dynamo/test_dynamo.py", line 494, in test_resnet18
    self.assertEqual(met.metric_data('ExecuteTime')[0], sample_count * 3)
AssertionError: 29 != 30
```

**Comment by JackCaoG** [comment]
yea.. this looks like a real error but I can't think of why.. our head is green.. Is this urgent? If so feel free to submit a pr to pytorch/xla to change the check to `self. assertLessEqual`. I can try to take a look tmr as well.

**Review by ezyang — APPROVED** [review]
preemptively approving

**Comment by bdhirsh** [comment]
Hmm if you’re ok with assertLessEqual to work around, I’ll send out an XLA patch tomorrow

**Comment by bdhirsh** [comment]
Ok, just updated again with the new hash (and we can see what XLA CI shows this time)

**Comment by bdhirsh** [comment]
Hmm @JackCaoG I now see the original `torch.version` error in CI:

```
ModuleNotFoundError: No module named 'torch.version'
```

https://github.com/pytorch/pytorch/actions/runs/8837947394/job/24271425860

**Comment by bdhirsh** [comment]
See this comment https://github.com/pytorch/pytorch/pull/124840#issuecomment-2078223624, but since there are some issues updating the XLA pin that I don't want to block internal on, I changed my PR to gate the config on whether or not we're in fbcode, so it will be off for internal.

**Comment by JackCaoG** [comment]
`ModuleNotFoundError: No module named 'torch.version'` should not be blocking, I saw it in other CI and they still passed. The real error is
```

2024-04-25T20:54:08.1230601Z + PJRT_DEVICE=CPU
2024-04-25T20:54:08.1230890Z + CPU_NUM_DEVICES=1
2024-04-25T20:54:08.1231408Z + run_coverage /var/lib/jenkins/workspace/xla/test/test_grad_checkpoint.py
2024-04-25T20:54:08.1232027Z + '[' 0 '!=' 0 ']'
2024-04-25T20:54:08.1232505Z + python3 /var/lib/jenkins/workspace/xla/test/test_grad_checkpoint.py
2024-04-25T20:54:09.9748774Z refreshing <module 'torch.ops.quantized_decomposed' from 'torch.ops'> quantize_per_tensor
2024-04-25T20:54:09.9749898Z refreshing <module 'torch.ops.quantized_decomposed' from 'torch.ops'> quantize_per_tensor
2024-04-25T20:54:09.9751196Z refreshing <module 'torch.ops.quantized_decomposed' from 'torch.ops'> dequantize_per_tensor
2024-04-25T20:54:09.9752414Z refreshing <module 'torch.ops.quantized_decomposed' from 'torch.ops'> dequantize_per_tensor
2024-04-25T20:54:10.4940403Z WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
2024-04-25T20:54:10.4941367Z I0000 00:00:1714078450.493632   34309 cpu_client.cc:424] TfrtCpuClient created.
2024-04-25T20:54:20.7907879Z I0000 00:00:1714078460.789691   34309 cpu_client.cc:427] TfrtCpuClient destroyed.
2024-04-25T20:54:20.7983164Z *** Received signal 11 ***
2024-04-25T20:54:20.7983591Z *** BEGIN MANGLED STACK TRACE ***
2024-04-25T20:54:20.8015010Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git2a204e9-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(+0x4d9a056)[0x7f993bbd1056]
2024-04-25T20:54:20.8016303Z /lib/x86_64-linux-gnu/libpthread.so.0(+0x13140)[0x7f9b6d8ca140]
2024-04-25T20:54:20.8043378Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git2a204e9-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(__xla_cpu_runtime_ParallelForkJoin+0x286)[0x7f993c6ae1f6]
2024-04-25T20:54:20.8044640Z [0x7f9b595ccf9c]
2024-04-25T20:54:20.8071030Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git2a204e9-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(+0x4dc6df9)[0x7f993bbfddf9]
2024-04-25T20:54:20.8097889Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git2a204e9-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(+0x4dc54b3)[0x7f993bbfc4b3]
2024-04-25T20:54:20.8130030Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git2a204e9-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(_ZN5Eigen15ThreadPoolTemplIN3tsl6thread16EigenEnvironmentEE10WorkerLoopEi+0x1b1)[0x7f9943890761]
2024-04-25T20:54:20.8166874Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git2a204e9-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(_ZN4absl12lts_2023080222internal_any_invocable13RemoteInvokerILb0EvRZN3tsl6thread16EigenEnvironment12CreateThreadESt8functionIFvvEEEUlvE_JEEET0_PNS1_15TypeErasedStateEDpNS1_18ForwardedParameterIT2_E4typeE+0x48)[0x7f994388e928]
2024-04-25T20:54:20.8200010Z /opt/conda/lib/python3.8/site-packages/torch_xla-2.4.0+git2a204e9-py3.8-linux-x86_64.egg/_XLAC.cpython-38-x86_64-linux-gnu.so(+0xca44a11)[0x7f994387ba11]
2024-04-25T20:54:20.8201528Z /lib/x86_64-linux-gnu/libpthread.so.0(+0x7ea7)[0x7f9b6d8beea7]
2024-04-25T20:54:20.8202221Z /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f9b6d68fa2f]
2024-04-25T20:54:20.8202745Z *** END MANGLED STACK TRACE ***
2024-04-25T20:54:20.8203001Z 
2024-04-25T20:54:20.8434801Z *** Begin stack trace ***
2024-04-25T20:54:20.8435237Z 	tsl::CurrentStackTrace[abi:cxx11]()
2024-04-25T20:54:20.8435608Z 	
2024-04-25T20:54:20.8435829Z 	
2024-04-25T20:54:20.8436096Z 	__xla_cpu_runtime_ParallelForkJoin
2024-04-25T20:54:20.8436452Z 	
2024-04-25T20:54:20.8436909Z 	
2024-04-25T20:54:20.8437116Z 	
2024-04-25T20:54:20.8437565Z 	Eigen::ThreadPoolTempl<tsl::thread::EigenEnvironment>::WorkerLoop(int)
2024-04-25T20:54:20.8439067Z 	void absl::lts_20230802::internal_any_invocable::RemoteInvoker<false, void, tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&>(absl::lts_20230802::internal_any_invocable::TypeErasedState*)
2024-04-25T20:54:20.8440430Z 	
2024-04-25T20:54:20.8440637Z 	
2024-04-25T20:54:20.8440863Z 	clone
2024-04-25T20:54:20.8441113Z *** End stack trace ***
2024-04-25T20:54:21.5351737Z ./test/run_tests.sh: line 48: 34309 Aborted                 (core dumped) python3 "$@"
```

**Comment by JackCaoG** [comment]
thanks, stuck in conference this week, let me try to follow up.

**Comment by JackCaoG** [comment]
Ok I am able to repo the failure... I am wondering why our CI does not fail.. let me take a look..

**Comment by JackCaoG** [comment]
https://github.com/pytorch/xla/pull/6976 should worked around this issue.

**Pull request closed without merging**
