### PR TITLE
[Doc] update guide install mkl-static from conda to pip

### PR DESCRIPTION
**Pull request by xuhancn**
image

Conda intel channel is not avaliable now.
Use `pip` install instead of `conda`.

`Windows` and `Linux` are avaliable:
Binary list: https://pypi.org/project/mkl-static/#files

`MacOS` is avaliable for old version:
https://pypi.org/project/mkl-static/2021.3.0/#files

TODO: 
1. cherry-pick to `release/2.4` branch, @atalman .
2. fix it also in `release/2.3` branch: https://github.com/pytorch/pytorch/pull/131853

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by xuhancn** [comment]
@atalman Maybe we need fix in release/2.3 also.

**Review by jgong5 — APPROVED** [review]

**Comment by xuhancn** [comment]
@malfet Could you please review and handle the cherry-pick for this doc change?

**Review by atalman — APPROVED** [review]
lgtm, please make sure lint is green before landing

**Pull request closed without merging**
