### PR TITLE
Minor Fix: Double ";" typo in transformerlayer.h

### PR DESCRIPTION
**Pull request by hebo-yang**
Fix double ";" typo in transformerlayer.h

### CODE REVIEW

**Comment by hebo-yang** [comment]
✨

**Comment by glaringlee** [comment]
@hebo-yang Thank you so much for finding this and fixed it. 
Please sign the Facebook CLA here https://code.facebook.com/cla/individual first.
Once it is get signed, please let me know, I will approve this PR then.

**Comment by hebo-yang** [comment]
> @hebo-yang Thank you so much for finding this and fixed it.
> Please sign the Facebook CLA here https://code.facebook.com/cla/individual first.
> Once it is get signed, please let me know, I will approve this PR then.

Thanks! I have just signed CLA.

**Comment by glaringlee** [comment]
> > @hebo-yang Thank you so much for finding this and fixed it.
> > Please sign the Facebook CLA here https://code.facebook.com/cla/individual first.
> > Once it is get signed, please let me know, I will approve this PR then.
> 
> Thanks! I have just signed CLA.

Thanks. I will approve this after all CI tests passed.

**Review by glaringlee — APPROVED** [review]
LGTM

**Pull request closed without merging**
