### PR TITLE
[NNC] Optimize conditionals that correspond to the form generated for aten::cat op.

### PR DESCRIPTION
**Pull request by navahgar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #57675 [NNC] Do not optimize conditionals when the corresponding loop is not normalized
* #57674 [NNC] Add a method to check if a loop is normalized
* **#57673 [NNC] Optimize conditionals that correspond to the form generated for aten::cat op.**

Differential Revision: [D28231374](https://our.internmc.facebook.com/intern/diff/D28231374)

### CODE REVIEW

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28231374).

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28231374).

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28231374).

**Review by bertmaher — APPROVED** [review]

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28231374).

**Comment by ZolotukhinM** [comment]
I think this optimization might produce incorrect results if `sub_exprs` are not constants:
```
for i in 0..100:
  a[i] = (i < N ? (i < M ? 5 : 7) : 9)
```
IIUC, this will be expanded into
```
for i in 0..N:
  a[i] = 5
for i in N..M:
  a[i] = 7
for i in M..100:
  a[i] = 9
```
If `N` happens to be bigger than `M`, then this would produce incorrect results. We probably cannot get this IR from expanding a concat, but it's still perfectly valid.

**Comment by navahgar** [comment]
> I think this optimization might produce incorrect results if `sub_exprs` are not constants:

Oh yeah, that's a good point. You are referring to the compared values (`comp_values`) being non-constants, right? The `sub_exprs` refer to the expressions used as the result for the true and false cases.

Let me add the constant constraint on the `comp_values` and also ensure that they are ordered. This should have perf benefits unless we have dynamic shapes.

**Comment by ZolotukhinM** [comment]
> You are referring to the compared values (comp_values) being non-constants, right? 
Yeah, probably :)

**Comment by navahgar** [comment]
@ZolotukhinM Actually, for the case you mentioned:
```
for i in N..M:
  a[i] = 7
```
even if `N > M`, the code would be valid because this loop:
```
for (int i = N; i < M; i++) 
  a[i] = 7
```
will never execute. 

I am still going to add the constraint on having ordered constants, just to be safe.

**Comment by ZolotukhinM** [comment]
> @ZolotukhinM Actually, for the case you mentioned:
> 
> ```
> for i in N..M:
>   a[i] = 7
> ```
> 
> even if `N > M`, the code would be valid because this loop:
> 
> ```
> for (int i = N; i < M; i++) 
>   a[i] = 7
> ```
> 
> will never execute.
> 
> I am still going to add the constraint on having ordered constants, just to be safe.

Yes, but the result will be `[5,5,5,5,5,9,9,9,9,9,9]` instead of `[7,7,7,5,5,9,9,9,9,9,9]`, which is still incorrect. To make it correct we need to use `Min(N, M)` as the stop for the first loop and the start of the second and `Max(N, M)` as the stop of the second (and it becomes exponentially harder as we get more than 2 variables).

**Comment by navahgar** [comment]
> Yes, but the result will be `[5,5,5,5,5,9,9,9,9,9,9]` instead of `[7,7,7,5,5,9,9,9,9,9,9]`, which is still incorrect. To make it correct we need to use `Min(N, M)` as the stop for the first loop and the start of the second and `Max(N, M)` as the stop of the second (and it becomes exponentially harder as we get more than 2 variables).

Not really. I just looked at your example more carefully now. For the input:
```
for i in 0..100:
  a[i] = (i < N ? (i < M ? 5 : 7) : 9)
```
the expanded version will be:
```
for i in 0..M:     // loop 1
  a[i] = 5
for i in M..N:    // loop 2
  a[i] = 7
for i in N..100:  // loop 3
  a[i] = 9
```
Note that the inner-most comparison value, `M` here, becomes the first loop. So, the problematic case is when `M > N`. But for this case, the value `7` will never be written out to any location of `a`. 

The only concern is there will be some overlapping writes between loops 1 and 3, but it will still end up with the correct result AFAICT.

**Comment by ZolotukhinM** [comment]
Mm, yeah, probably you're right. If we're coming from (i < N ? (I < M ...)) structure then it's probably correct. I was confused as I was thinking about arbitrary splitting the array with (0, N, M, 100) points, but it seems less restricted than the case we have here.

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28231374).

**Comment by navahgar** [comment]
Added a check to handle only those case where the compared values are constants and are in sorted order. The optimization is correct even without this constraint (as discussed above). So, we can remove this constraint in future if needed.

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28231374).

**Pull request closed without merging**
