### PR TITLE
Unpadded len

### PR DESCRIPTION
**Pull request by dsm-72**
Adds utility function for `torch.nn.rnn` that lets users calculate the length of a padded sequence if they don't want to pass it around all the time. Example of usage (before this PR) is in the [GitHub Gist][Github Gist] shown in [PackedSequences on MPS accelerator][PackedSequences on MPS accelerator].

[Github Gist]: https://gist.github.com/dsm-72/1cea0601145a8b92155d8d08c90bf998
[PackedSequences on MPS accelerator]: https://github.com/pytorch/pytorch/issues/102911

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### CODE REVIEW

**Comment by jbschlosser** [comment]
Hey @dsm-72, is there an associated issue you can link here? In general, we like to discuss whether or not to accept changes before they are merged.

**Comment by dsm-72** [comment]
@jbschlosser  see https://github.com/pytorch/pytorch/issues/102911

As well as other issues and a PR: 
- https://github.com/pytorch/pytorch/issues/97552#issuecomment-1531998792
- https://github.com/pytorch/pytorch/issues/97552
- https://github.com/pytorch/pytorch/issues/96416
- https://github.com/pytorch/pytorch/pull/96601

**Comment by soulitzer** [comment]
Hey @dsm-72 thanks for linking the issue. However It looks like the error being discussed there -`Expected a proper Tensor but got None (or an undefined Tensor in C++) for argument #0 'grad_y'` should be solved by fixing a backward formula in autograd (we'd be happy to review a PR for that).

Could you elaborate more on why this PR can help solve that issue? Or if what is being proposed here is something orthogonal to what is being discussed in that issue, could you open a new issue for discussion? Thanks!

**Comment by dsm-72** [comment]
@soulitzer it is orthogonal. PackedSequence is used with LSTMs and GRUs that caused those issues on MPS.

**Comment by soulitzer** [comment]
Would something like this work for the your use case?
```python
import torch

padded = torch.tensor([
    [[1, 2, 3], [4, 5, 6], [0, 0, 0]],      # ---> len = 2
    [[7, 8, 9], [10, 0, 0], [0, 0, 0]],     # ---> len = 2
    [[11, 12, 13], [14, 15, 0], [16, 0, 0]] # ---> len = 3
])

print(padded.count_nonzero(-1).count_nonzero(-1))  # tensor([2, 2, 3])
```

**Comment by dsm-72** [comment]
@soulitzer that doesn't scale for different sized tensors though...

**Pull request closed without merging**
