### PR TITLE
Prefer flip over index_select

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #125574
* __->__ #126783
* #114471

It's faster and has a lower memory footprint in eager.

### CODE REVIEW

**Comment by lezcano** [comment]
I'll fix the linting in a bit, but otherwise can you PTAL @albanD?

**Review by Skylion007 — APPROVED** [review]
Nice. Bonus points for dedupping code.

**Review by albanD — APPROVED** [review]
Nice

**Pull request closed without merging**
