### PR TITLE
[9/N] Remove ST multiple ops

### PR DESCRIPTION
**Pull request by fduwjj**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96989

Differential Revision: [D44158327](https://our.internmc.facebook.com/intern/diff/D44158327)

### CODE REVIEW

**Review by wz337 — APPROVED** [review]
LGTM! Thanks for cleaning it up!

**Review by wanchaol — APPROVED** [review]
To make sure it's safe to land, can you import the PR and see if internal tests are fine? Thanks!

**Comment by fduwjj** [comment]
@fduwjj has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44158327).

**Comment by fduwjj** [comment]
@fduwjj has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44158327).

**Comment by fduwjj** [comment]
@fduwjj has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44158327).

**Pull request closed without merging**
