### PR TITLE
Add _assert_scalar

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #117378

Peeled off from https://github.com/pytorch/pytorch/pull/114148, because that PR is going to take a while to actually land.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by jansel — APPROVED** [review]
Add tests?

**Comment by ezyang** [comment]
I'm going to let the follow up PR handle that, if you don't mind

**Pull request closed without merging**
