### PR TITLE
[dynamo][compile-time] Collect guard debug stack info only with logs enabled

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #120590
* __->__ #120520

Reduces backend=eager compile time from 33 to 19 seconds for `MobileBertForQuestionAnswering`. This also helps an internal model where guards.add function is taking 124 seconds.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by mlazos — APPROVED** [review]

**Comment by mlazos** [comment]
this is great! I was wondering why guards was taking so long

**Comment by ezyang** [comment]
@zdevito I was expecting CapturedTraceback to be basically free here. Does the overhead @anijain2305 is seeing here seem about right to you?

@anijain2305 do you know how many guards are being added? Also, do you know if it's specifically CapturedTraceback or the user stack that is problematic?

**Comment by ezyang** [comment]
perf run https://github.com/pytorch/pytorch/actions/runs/8033844384

**Comment by anijain2305** [comment]
@ezyang 

Both disabled - 19 seconds
Both enabled - 26 seconds (yesterday it was 33 seconds, maybe something was wrong)
Only CapturedTraceback enabled - 26 seconds
Only UserStack enabled - 20 seconds

So, its mostly coming from CapturedTraceback it seems.

Number of guards = 8710 (this is surprising number, I will check why).

**Comment by anijain2305** [comment]
@ezyang There is not much improvement on compilation latency on average. But for MobileBert, we observe good speedups
image


It is possible that this model (and the internal model) is a pathological case for CapturedTraceback.

**Comment by ezyang** [comment]
Well, I can't argue with pathological cases in internal. But maybe we should (1) add a similarly pathological case to the oss suite and (2) figure out if the internal model actually has too many guards--maybe there is something else wrong.

**Comment by zdevito** [comment]
Recording stacks is normally pretty cheap (like a few microseconds), assuming we are not symbolizing them. If there are _a lot_ of guards, that can still be measurable. It also is a function of stack depth, so if somehow the stacks are very deep, it will take longer.

**Pull request closed without merging**
