### PR TITLE
Don't use cudnn for negative padding or output_padding, check torch.backends.cudnn.enabled

### LINKED ISSUE #964: output_padding argument is ignored in deconvolution, leading to cudnn errors
The following snippet produces an error in deconvolution:
```.py
import torch
import torch.nn as nn
from torch.autograd import Variable

conv = nn.Conv3d(1,8, kernel_size=3, padding=1, stride = 2)
conv = conv.cuda()
deconv = nn.ConvTranspose3d(8,1, kernel_size=3, stride=2, output_padding=-1)
deconv = deconv.cuda()

x = Variable(torch.randn(8,1,64,64,64).cuda(), requires_grad=True)
#ok
for i in range(10):
    out = conv(x)
    err = out.sum()
    err.backward()

print("deconv")

#error
x = Variable(torch.randn(8,8,32,32,32).cuda(), requires_grad=True)

for i in range(10):
    out = deconv(x)
    err = out.sum()
    err.backward()
```
The issue is, in the deconvolution case padding is not passed to convolution descriptor, ltraces for the failing and passing cudnnGetConvolutionBackwardDataAlgorithm below, padding is 1 for passing and 0 for failing. 
```
[pid 21910] _C.cpython-35m-x86_64-linux-gnu.so->cudnnGetConvolutionBackwardDataAlgorithm(0xffff7fffffff, { CUDNN_DATA_FLOAT, 0, [ 5, 8, 1, 3... ], CUDNN_TENSOR_NCHW }, { CUDNN_DATA_FLOAT, 0, 5, [ 2097152, 0, 8, 8... ], [ 0, 0, 262144, 32768... ] }, { CUDNN_CROSS_CORRELATION, CUDNN_DATA_FLOAT, 3, [ 0, 0, 0, 0... ], [ 2, 2, 2, 0... ], [ 1, 1, 1, 0... ] }, { CUDNN_DATA_FLOAT, 0, 5, [ 2097152, 0, 8, 1... ], [ 0, 0, 262144, 262144... ] }, 1, 0, 0 <unfinished ...>
[pid 21917] _C.cpython-35m-x86_64-linux-gnu.so->cudnnGetConvolutionBackwardDataAlgorithm(0xffff7fffffff, { CUDNN_DATA_FLOAT, 0, [ 5, 8, 1, 3... ], CUDNN_TENSOR_NCHW }, { CUDNN_DATA_FLOAT, 0, 5, [ 2097152, 0, 8, 8... ], [ 0, 0, 262144, 32768... ] }, { CUDNN_CROSS_CORRELATION, CUDNN_DATA_FLOAT, 3, [ 1, 1, 1, 0... ], [ 2, 2, 2, 0... ], [ 1, 1, 1, 0... ] }, { CUDNN_DATA_FLOAT, 0, 5, [ 2097152, 0, 8, 1... ], [ 0, 0, 262144, 262144... ] }, 1, 0, 0 <unfinished ...>
```
Also, there seems to be no way of disabling cudnn at runtime, torch.backends.cudnn.enabled is no longer checked for convolutions: https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/functions/convolution.cpp#L108-L110

### PR DESCRIPTION
**Pull request by ngimel**
This fixes #964 (if padding or output_padding is negative, cudnn is not used), however, the test that I've added for negative output_padding fails even when I'm running it on cpu only: 
```
FAIL: test_ConvTranspose2d_neg_output_padding (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 1988, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/opt/pytorch/test/common_nn.py", line 543, in __call__
    self._do_test(test_case, module, input)
  File "test_nn.py", line 69, in _do_test
    test_case.check_jacobian(module, input, self.jacobian_input)
  File "/opt/pytorch/test/common_nn.py", line 431, in check_jacobian
    PRECISION
AssertionError: 8.35154853160465 not less than or equal to 1e-05
```
Not quite sure why. Does pytorch actually support negative output_padding?

### CODE REVIEW

**Comment by colesbury** [comment]
It looks like we don't support negative output_padding. I'm not sure we support negative padding either. Maybe we should just raise an exception in these cases.

**Comment by ngimel** [comment]
Was just about to push the same commit.

**Comment by colesbury** [comment]
Oh, sorry! Soumith wanted to make sure this got into the next release

**Comment by ngimel** [comment]
Thanks!

**Pull request merged**
