### PR TITLE
Turn on USE_DIRECT_NVRTC in fbcode again.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#22685 Turn on USE_DIRECT_NVRTC in fbcode again.**

Differential Revision: [D16182352](https://our.internmc.facebook.com/intern/diff/D16182352/)

### CODE REVIEW

**Comment by ezyang** [comment]
@SsnL so, according to the user, when I switch to `USE_DIRECT_NVRTC` he doesn't see the dynamic library loading error anymore, but he sees:

```
Traceback (most recent call last):
  File "<string>", line 38, in <module>
  File "<string>", line 36, in __run
  File "/usr/local/fbcode/platform007/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/fbcode/platform007/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/users/yunwang/fbsource/fbcode/buck-out/dev/gen/experimental/yunwang/talnet/convert_to_jit#link-tree/experimental/yunwang/talnet/convert_to_jit.py", line 65, in <module>
    main()
  File "/data/users/yunwang/fbsource/fbcode/buck-out/dev/gen/experimental/yunwang/talnet/convert_to_jit#link-tree/experimental/yunwang/talnet/convert_to_jit.py", line 46, in main
    pooling="lin",
  File "/data/users/yunwang/fbsource/fbcode/buck-out/dev/gen/experimental/yunwang/talnet/convert_to_jit#link-tree/langtech/talnet/TALNet.py", line 278, in TALNet
    return TALNet(format=format, device=device, **kwargs)
  File "/data/users/yunwang/fbsource/fbcode/buck-out/dev/gen/experimental/yunwang/talnet/convert_to_jit#link-tree/torch/jit/__init__.py", line 1315, in init_then_register
    original_init(self, *args, **kwargs)
  File "/data/users/yunwang/fbsource/fbcode/buck-out/dev/gen/experimental/yunwang/talnet/convert_to_jit#link-tree/langtech/talnet/TALNet.py", line 155, in __init__
    gru.to(self.device),
  File "/data/users/yunwang/fbsource/fbcode/buck-out/dev/gen/experimental/yunwang/talnet/convert_to_jit#link-tree/torch/nn/modules/module.py", line 424, in to
    return self._apply(convert)
  File "/data/users/yunwang/fbsource/fbcode/buck-out/dev/gen/experimental/yunwang/talnet/convert_to_jit#link-tree/torch/nn/modules/rnn.py", line 124, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "/data/users/yunwang/fbsource/fbcode/buck-out/dev/gen/experimental/yunwang/talnet/convert_to_jit#link-tree/torch/nn/modules/module.py", line 222, in _apply
    param_applied = fn(param)
  File "/data/users/yunwang/fbsource/fbcode/buck-out/dev/gen/experimental/yunwang/talnet/convert_to_jit#link-tree/torch/nn/modules/module.py", line 422, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/data/users/yunwang/fbsource/fbcode/buck-out/dev/gen/experimental/yunwang/talnet/convert_to_jit#link-tree/torch/cuda/__init__.py", line 179, in _lazy_init
    torch._C._cuda_init()
```

Any ideas?

**Comment by SsnL** [comment]
@ezyang is that the full error message? It seems truncated.

It also seems that CUDA init code is broken. Could you ask them to get a gdb trace? I don't remember how easily it is with fbcode build...

**Comment by ezyang** [comment]
@SsnL gdb is so slow for some reason. Here you go:

```
THCudaCheck FAIL file=caffe2/aten/src/THC/THCGeneral.cpp line=50 error=2 : out of memory

Thread 1 "python3.6" hit Catchpoint 1 (exception thrown), 0x00007ffff73b70e0 in __interceptor___cxa_throw ()
   from /data/users/yunwang/fbsource/fbcode/buck-out/dev/gen/experimental/yunwang/talnet/convert_to_jit#link-tree/libtools_build_sanitizers_asan-ubsan-py.so
(gdb) bt 10
#0  0x00007ffff73b70e0 in __interceptor___cxa_throw ()
   from /data/users/yunwang/fbsource/fbcode/buck-out/dev/gen/experimental/yunwang/talnet/convert_to_jit#link-tree/libtools_build_sanitizers_asan-ubsan-py.so
#1  0x00007fff8b938f0f in defaultErrorHandlerFunction (msg=0x7ffff1d48020 "cuda runtime error (2) : out of memory at caffe2/aten/src/THC/THCGeneral.cpp:50", data=0x0)
    at caffe2/aten/src/TH/THGeneral.cpp:26
#2  0x00007fff8b938aa4 in _THError (file=0x7fff9336cdd8 "caffe2/aten/src/THC/THCGeneral.cpp", line=50, fmt=0x7fff935d6b00 <.str.4> "cuda runtime error (%d) : %s")
    at caffe2/aten/src/TH/THGeneral.cpp:52
#3  0x00007fff919524cd in __THCudaCheck (err=cudaErrorMemoryAllocation, file=0x7fff9336cdd8 "caffe2/aten/src/THC/THCGeneral.cpp", line=50)
    at caffe2/aten/src/THC/THCGeneral.cpp:260
#4  0x00007fff91951585 in THCudaInit (state=0x60400038d090) at caffe2/aten/src/THC/THCGeneral.cpp:50
#5  0x00007fff90be13f1 in at::cuda::detail::CUDAHooks::initCUDA (this=0x6020001a1e10) at caffe2/aten/src/ATen/cuda/detail/CUDAHooks.cpp:45
#6  0x00007fffd52fa015 in at::Context::lazyInitCUDA()::{lambda()#1}::operator()() const (this=0x7ffff1735120) at caffe2/aten/src/ATen/Context.h:70
#7  0x00007fffd52f9e8d in std::__invoke_impl<void, at::Context::lazyInitCUDA()::{lambda()#1}>(std::__invoke_other, at::Context::lazyInitCUDA()::{lambda()#1}&&) (__f=...)
    at ./third-party-buck/platform007/build/libgcc/include/c++/7.3.0/bits/invoke.h:60
#8  0x00007fffd52f9e4d in std::__invoke<at::Context::lazyInitCUDA()::{lambda()#1}>(std::__invoke_result&&, (at::Context::lazyInitCUDA()::{lambda()#1}&&)...) (__fn=...)
    at ./third-party-buck/platform007/build/libgcc/include/c++/7.3.0/bits/invoke.h:95
#9  0x00007fffd52f9e25 in std::call_once<at::Context::lazyInitCUDA()::{lambda()#1}>(std::once_flag&, at::Context::lazyInitCUDA()::{lambda()#1}&&)::{lambda()#1}::operator()() const (this=0x7ffff183caa0) at ./third-party-buck/platform007/build/libgcc/include/c++/7.3.0/mutex:672
(More stack frames follow...)
```

**Comment by SsnL** [comment]
@ezyang You probably have already checked this.. but I'm going to ask again. Are they sure that the GPU is not actually OOM?

**Comment by ezyang** [comment]
Yeah, there's no usage. Also, the line that is reporting an OOM is cudaGetDeviceCount which definitely shouldn't OOM.

**Comment by SsnL** [comment]
@ezyang That is rather weird... I don't think that PR changes anything related to CUDA init. `cudaGetDeviceCount` can probably OOM when there isn't even enough memory for the context, but you also said that there is no usage. 

So it seems that the very first CUDA API call OOMs. Usually this sounds to me that the environment is set up wrongly. Can they check if they can run other CUDA-enabled programs in their environment?

**Comment by ezyang** [comment]
Yeah, they told me that when they reverted your diff, their script worked. It's possible they got mixed up with something else, but that seems like a pretty clear indicator here.

I might have time tomorrow to try to make a reproducer.

**Comment by SsnL** [comment]
@ezyang Thank you! If this ends up blocking some critical code, feel free to revert.

**Comment by ezyang** [comment]
@SsnL It's your lucky day; it was in fact user error :) Gonna land this.

**Comment by SsnL** [comment]
@ezyang Thank you!!

**Comment by soumith** [comment]
a spurious CUDA OOM in fbcode is almost always ASAN being stupid

**Pull request closed without merging**
