### PR TITLE
[inductor] calibration inductor windows uts (3/N)

### PR DESCRIPTION
**Pull request by xuhancn**
skip Windows UT of `test/dynamo/test_trace_rules.py`

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
BTW, it'd be better to xfail if windows, so we can easily tell when to stop skipping them

**Comment by xuhancn** [comment]
> BTW, it'd be better to xfail if windows, so we can easily tell when to stop skipping them

@ezyang Thanks for suggestion, I want to review and confirm the skip after catch up release/2.5.

**Pull request closed without merging**
