### PR TITLE
[Dynamo] make bytecode of resume function resemble natural bytecode

### PR DESCRIPTION
**Pull request by youkaichao**
cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

### CODE REVIEW

**Comment by youkaichao** [comment]
When we deal with natural bytecode (Python bytecode that is generated by Python compiler, from source code), we can observe that `co_freevars` seem to be sorted, no matter how they are declared:

```python
def helper_outer_function():
    data_ptr = None
    last_dim_size = None
    last_two_dims_size = None
    shape = None
    stride = None
    qkv_format = None
    def dummy1():
        nonlocal data_ptr, last_dim_size, last_two_dims_size, shape, stride, qkv_format
        # Access variables in the order they were declared
        _ = data_ptr
        _ = last_dim_size
        _ = last_two_dims_size
        _ = shape
        _ = stride
        _ = qkv_format
        print(data_ptr)
        print(last_dim_size)
        print(last_two_dims_size)
        print(shape)
        print(stride)
        print(qkv_format)
    dummy1()

print(helper_outer_function.__code__.co_consts[1].co_freevars)
```

The output is:

```text
('data_ptr',
 'last_dim_size',
 'last_two_dims_size',
 'qkv_format',
 'shape',
 'stride')
```

Note that our declaration order is `data_ptr, last_dim_size, last_two_dims_size, shape, stride, qkv_format` , but Python sorts them. 

If Dynamo generated bytecode does not obey this rule, it means we cannot generate source code that can compile the same bytecode as Dynamo, which makes it impossible to understand Dynamo bytecode by decompiling it into source code.

**Comment by youkaichao** [comment]
Note: we require the new bytecode has exactly the same `co_freevar` as the old one, in order to have faster new frame construction. It is proposed by me in https://github.com/pytorch/pytorch/pull/115062 .

**Comment by youkaichao** [comment]
reference:

https://github.com/python/cpython/blob/caf6064a1bc15ac344afd78b780188e60b9c628e/Python/compile.c#L530-L534

>     /* Sort the keys so that we have a deterministic order on the indexes
>        saved in the returned dictionary.  These indexes are used as indexes
>        into the free and cell var storage.  Therefore if they aren't
>        deterministic, then the generated bytecode is not deterministic.
>     */

indexes of free and cell var storage are sorted.

**Comment by youkaichao** [comment]
TODO: how to add test for this. We need to generate a resume function with freevars.

**Comment by ezyang** [comment]
Trying @williamwen42 as reviewer, but this looks pretty harmless, shout if it gets lost

**Review by williamwen42 — APPROVED** [review]
LGTM - just add a test

**Comment by youkaichao** [comment]
@williamwen42 thanks for the reply. Can you give me some guidance on how to add tests? In particular, I don't know how to manually instruct Dynamo to generate a resume function as I want.

**Comment by williamwen42** [comment]
You can compile a function with a graph break and then search `globals/locals` for the resume function:
```python
import torch

def fn(x):
    x = x + 1
    torch._dynamo.graph_break()
    x = torch.sin(x)
    return x

opt_fn = torch.compile(fn, backend="eager")
opt_fn(torch.randn(10))

for k, v in list(globals().items()):
    if k.startswith("__resume_at"):
        print(k)
        print(v)
```

**Comment by youkaichao** [comment]
This kind of resume function does not have freevars:

`__resume_at_16_3.__code__.co_freevars == ()`

**Comment by williamwen42** [comment]
You can use a different function that has freevars - compile a function with a closure?

**Comment by youkaichao** [comment]
When will resume function contain free vars?

**Comment by williamwen42** [comment]
Looks like resume functions with freevars are not exposed to the global scope, so we'll need to add something like
```python
            # expose code object for debugging purposes!
            self.output.install_global_unsafe(name, new_code)
``` before the `cg.make_function_with_closure(name, new_code, True, stack_len)` line in `def create_call_resume_at` (symbolic_convert.py). 

Then a function like this should work:
```python
import torch

def create():
    cl = 1
    def fn(x):
        x = x + 1
        torch._dynamo.graph_break()
        x = x + cl
        return x
    return fn

fn = create()
opt_fn = torch.compile(fn, backend="eager")
print(opt_fn(torch.randn(10)))

breakpoint()
for k, v in list(globals().items()):
    if k.startswith("__resume_at"):
        print(k)
        print(v)
        print(v.co_freevars)
        print(v.co_cellvars)
```

**Comment by youkaichao** [comment]
@williamwen42 thanks for the guidance! do you know if the test failures in the [commit](https://github.com/pytorch/pytorch/pull/126630/commits/fbe7f037550e6f6889158de6af699420d24d17a8) are related with the changes in this PR?

**Comment by williamwen42** [comment]
They don't look related, but we'll see what CI shows.

**Comment by youkaichao** [comment]
@williamwen42 can you take a look at whether ci test failures are related?

**Comment by youkaichao** [comment]
@williamwen42 then how can we merge this? do we need to wait until the ci team fixes the issue?

**Pull request closed without merging**
