### PR TITLE
Update trunk CUDA-10.2 to CUDA-11.7

### PR DESCRIPTION
**Pull request by malfet**
As CUDA-10.2 is finally disabled

Ref: https://github.com/pytorch/builder/issues/1026

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
Yay, finally! Just a curious question about py3.9 to py3.7, is there any particular reason for that?

**Review by atalman — APPROVED** [review]

**Comment by malfet** [comment]
> Yay, finally! Just a curious question about py3.9 to py3.7, is there any particular reason for that?

It's just a job name that I copied from periodic, but this seems to be a misnomer - it actually runs py3.10 builds/tests, so renaming and landing

**Comment by lezcano** [comment]
will we be able to move to C++17 then?!

**Pull request closed without merging**
