### PR TITLE
Fix out_wrapper, _make_copy_from_view to handle all signatures

### PR DESCRIPTION
**Pull request by rec**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #130937

* See #128416 and #129476
* Simplify xskip lists in test/functorch/test_ops.py
* Add supports_out=True to OpInfos for copy ops

### CODE REVIEW

**Review by peterbell10 — APPROVED** [review]

**Comment by rec** [comment]
@pytorch merge

**Comment by rec** [comment]
topic: not user facing

**Comment by titaiwangms** [comment]
Hi, @rec Feel free to label it with the correct one.

**Pull request closed without merging**
