### PR TITLE
Expose Row2Col and Vol2Col

### PR DESCRIPTION
**Pull request by lantiga**
This PR addresses #3321, which extends #2580 to temporal and volumetric data. Tests have been extended to the 1D and 3D cases.

One thing to note: `fold` now requires that `output_size` is a tuple (it is currently allowed to be an integer in master), as it is impossible to determine what the dimensionality of the output should be just from the `col` tensor. It's always a 2D tensor (batched).

### CODE REVIEW

**Comment by lantiga** [comment]
Something still to fix on cuda for row2col.

**Comment by jbarker-nvidia** [comment]
@lantiga Let me know if there's anything I can do to help on this.

**Comment by lantiga** [comment]
Thanks @jbarker-nvidia !

Actually I think the code works (tests were passing a couple of days ago).
Today I checked back and noticed a failure on `onnx-fb-universe` plus a conflict on a file. I solved the latter, and now I'm seeing `pr/pytorch-win-ws2016-cuda9-cudnn7-py3` failing. Apparently failures are unrelated though (see https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-test/1131/console).

It would really be great if you could take a look at the PR and see if there's anything fishy. Thanks!

**Comment by weiyangfb** [comment]
@lantiga this needs a rebase now. Thoughts on this? cc @zou3519

**Comment by lantiga** [comment]
I’m ok with rebasing, but this was implemented on top of THNN, and now would probably need to be reimplemented as an ATen native operation. Thoughts?

**Pull request closed without merging**
