### PR TITLE
Issue #27441 Fix: Bug in updating ModuleDict & ParameterDict

### PR DESCRIPTION
**Pull request by wangwwno1**
Fix a bug in `nn.ModuleDict.update` and `nn.ParameterDict.update` when passing another same dictionary as input.
Related issue: [Issue #27441](https://github.com/pytorch/pytorch/issues/27441)

### CODE REVIEW

**Comment by pietern** [comment]
@gchanan Could you take a look at this one?

**Comment by ezyang** [comment]
Sorry about the really late review. Would it be possible to get a test for this?

**Comment by wangwwno1** [comment]
All tests passed this time. Could you take a look at this again?
@ezyang

**Comment by ezyang** [comment]
Sorry, I wasn't clear in my original comment. It would be great if you could add a test for the bug you are fixing here. Probably put it in `test/test_nn.py`

**Comment by wangwwno1** [comment]
> Sorry, I wasn't clear in my original comment. It would be great if you could add a test for the bug you are fixing here. Probably put it in `test/test_nn.py`

OK, got it, will add them shortly!

**Comment by wangwwno1** [comment]
Test for `update` has appended.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
