### PR TITLE
lshift and rshift on CUDA should match the behavior on CPU

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #35422 Make intdiv_256 a more generic binary operator template
* **#35339 lshift and rshift on CUDA should match the behavior on CPU**
* #35323 Utilize std::make_unsigned_t instead of wrapping lshift

CPU version converts integers to their unsigned version first. The CUDA
version should also do it.

Also added tests for this.

Differential Revision: [D20826862](https://our.internmc.facebook.com/intern/diff/D20826862)

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
Thanks!

**Comment by gchanan** [comment]
@xuhdev Just to confirm, this doesn't actually change behavior right?  I ran the test against 1.5 (which doesn't have this change) and the test passed.

**Comment by xuhdev** [comment]
@gchanan It would depend on the compiler's implementation -- it may change and may not change. If the test passed without this PR, it means that at least in the CI setup, the compiler treated signed integers as if they were unsigned for bit shifting purposes, in which case this PR would lead to no change.

**Comment by gchanan** [comment]
@xuhdev: oh, just to be clear, I ran it locally against my 1.5 build, I didn't check it against all the compiler variants.

**Pull request closed without merging**
