### PR TITLE
[ROCm] Second attempt to fix unit test: matmul_small_brute_force_tunableop

### LINKED ISSUE #141458: DISABLED test_matmul_small_brute_force_tunableop_cuda_float16 (__main__.TestLinalgCUDA)
Platforms: rocm, linux

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22test_linalg.py%3A%3ATestLinalgCUDA%3A%3Atest_matmul_small_brute_force_tunableop_cuda_float16%22%5D)).

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

### LINKED ISSUE #141635: DISABLED test_matmul_small_brute_force_tunableop_cuda_float32 (__main__.TestLinalgCUDA)
Platforms: linux, slow, rocm

This test was disabled because it is failing in CI. See [recent examples](https://hud.pytorch.org/flakytest?name=test_matmul_small_brute_force_tunableop_cuda_float32&suite=TestLinalgCUDA&limit=100) and the most recent trunk [workflow logs](https://github.com/pytorch/pytorch/runs/33567316956).

Over the past 3 hours, it has been determined flaky in 26 workflow(s) with 52 failures and 26 successes.

**Debugging instructions (after clicking on the recent samples link):**
DO NOT ASSUME THINGS ARE OKAY IF THE CI IS GREEN. We now shield flaky tests from developers so CI will thus be green but it will be harder to parse the logs.
To find relevant log snippets:
1. Click on the workflow logs linked above
2. Click on the Test step of the job so that it is expanded. Otherwise, the grepping will not work.
3. Grep for `test_matmul_small_brute_force_tunableop_cuda_float32`
4. There should be several instances run (as flaky tests are rerun in CI) from which you can study the logs.

Test file path: `test_linalg.py`

ConnectionTimeoutError: Connect timeout for 5000ms, GET https://raw.githubusercontent.com/pytorch/pytorch/main/test/test_linalg.py -2 (connected: false, keepalive socket: false, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @clee2000 @wdvr @jianyuh @nikitaved @pearu @mruberry @walterddr @xwang233 @Lezcano

### LINKED ISSUE #141636: DISABLED test_matmul_small_brute_force_tunableop_cuda_float64 (__main__.TestLinalgCUDA)
Platforms: linux, rocm, slow

This test was disabled because it is failing in CI. See [recent examples](https://hud.pytorch.org/flakytest?name=test_matmul_small_brute_force_tunableop_cuda_float64&suite=TestLinalgCUDA&limit=100) and the most recent trunk [workflow logs](https://github.com/pytorch/pytorch/runs/33562152843).

Over the past 3 hours, it has been determined flaky in 3 workflow(s) with 6 failures and 3 successes.

**Debugging instructions (after clicking on the recent samples link):**
DO NOT ASSUME THINGS ARE OKAY IF THE CI IS GREEN. We now shield flaky tests from developers so CI will thus be green but it will be harder to parse the logs.
To find relevant log snippets:
1. Click on the workflow logs linked above
2. Click on the Test step of the job so that it is expanded. Otherwise, the grepping will not work.
3. Grep for `test_matmul_small_brute_force_tunableop_cuda_float64`
4. There should be several instances run (as flaky tests are rerun in CI) from which you can study the logs.

Test file path: `test_linalg.py`

ConnectionTimeoutError: Connect timeout for 5000ms, GET https://raw.githubusercontent.com/pytorch/pytorch/main/test/test_linalg.py -2 (connected: false, keepalive socket: false, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @clee2000 @wdvr

### PR DESCRIPTION
**Pull request by naromero77amd**
Fixes #141458 
Fixes #141635 
Fixes #141636 

~~Address OOM issue by clearing PyTorch's caching allocator.~~

Disabling this test on NVIDIA since it doesn't do much on NVIDIA hardware at the moment. 

cc @ptrblck @msaroufim @eqy @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by eqy** [comment]
Why would `torch.cuda.empty_cache` be expected to fix an OOM? The caching allocator will already attempt to do this before throwing an OOM: https://github.com/pytorch/pytorch/blob/8d24eb0c944bfaa953406e6282af2bab7d87c1e4/c10/cuda/CUDACachingAllocator.cpp#L1237

**Comment by naromero77amd** [comment]
> Why would `torch.cuda.empty_cache` be expected to fix an OOM? The caching allocator will already attempt to do this before throwing an OOM:
> 
> https://github.com/pytorch/pytorch/blob/8d24eb0c944bfaa953406e6282af2bab7d87c1e4/c10/cuda/CUDACachingAllocator.cpp#L1237

It was just a guess at this point. Trying to resolve this perplexing issue:
```
torch.OutOfMemoryError: CUDA out of memory. 
Tried to allocate 2.00 MiB. GPU 0 has a total capacity of 21.95 GiB of which 10.82 GiB is free. 
Process 79807 has 184.00 MiB memory in use. Process 79827 has 10.45 GiB memory in use. 
Process 80512 has 184.00 MiB memory in use. Process 80590 has 186.00 MiB memory in use. 10.10 GiB allowed;
Of the allocated memory 9.74 GiB is allocated by PyTorch, and 367.50 MiB is reserved by PyTorch but unallocated. 
If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. 
See documentation for Memory
(https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

Seems to happen on NVIDIA sm89 (NVIDIA consumer grade card only). Not sure I have access to one of those. Maybe it makes more sense to skip it for sm89?

**Comment by eqy** [comment]
Do you have a link to the failure? I checked on sm89 and the only failure I observed on `test_linalg.py` was
```
======================================================================
FAIL: test_matmul_offline_tunableop_cuda_float16 (__main__.TestLinalgCUDA.test_matmul_offline_tunableop_cuda_float16)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pytorch/torch/testing/_internal/common_utils.py", line 3108, in wrapper
    method(*args, **kwargs)
  File "/workspace/pytorch/torch/testing/_internal/common_utils.py", line 3108, in wrapper
    method(*args, **kwargs)
  File "/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 460, in instantiated_test
    result = test(self, **param_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 1412, in only_fn
    return fn(slf, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/pytorch/test/test_linalg.py", line 4673, in test_matmul_offline_tunableop
    assert os.path.exists(result_filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

----------------------------------------------------------------------
Ran 772 tests in 539.718s

FAILED (failures=1, skipped=441)
```

**Comment by naromero77amd** [comment]
> Do you have a link to the failure? I checked on sm89 and the only failure I observed on `test_linalg.py` was
> 
> ```
> ======================================================================
> FAIL: test_matmul_offline_tunableop_cuda_float16 (__main__.TestLinalgCUDA.test_matmul_offline_tunableop_cuda_float16)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/workspace/pytorch/torch/testing/_internal/common_utils.py", line 3108, in wrapper
>     method(*args, **kwargs)
>   File "/workspace/pytorch/torch/testing/_internal/common_utils.py", line 3108, in wrapper
>     method(*args, **kwargs)
>   File "/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 460, in instantiated_test
>     result = test(self, **param_kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/workspace/pytorch/torch/testing/_internal/common_device_type.py", line 1412, in only_fn
>     return fn(slf, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/workspace/pytorch/test/test_linalg.py", line 4673, in test_matmul_offline_tunableop
>     assert os.path.exists(result_filename)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AssertionError
> 
> ----------------------------------------------------------------------
> Ran 772 tests in 539.718s
> 
> FAILED (failures=1, skipped=441)
> ```

That's a totally different unit test, have not taken a look at that one yet :)

See https://github.com/pytorch/pytorch/issues/141458
and the most recent failure:
https://github.com/pytorch/pytorch/runs/34100010474 (search for "out of memory" in the test results)

**Review by jeffdaily — APPROVED** [review]

**Review by eqy — CHANGES_REQUESTED** [review]
Rather than gating this on compute capability, would it make sense to just use a `largeTensorTest` decorator instead? Or have we already demonstrated that it's sm89-specific and other GPUs with comparable memory do not go OOM

**Comment by jeffdaily** [comment]
> Rather than gating this on compute capability, would it make sense to just use a `largeTensorTest` decorator instead? Or have we already demonstrated that it's sm89-specific and other GPUs with comparable memory do not go OOM

It's not a largeTensorTest.  I think at most the tensor shapes are 1x4?  Something else is going on.  The OOM error message seems to indicate there is ample memory left but the alloc fails regardless.  In any case, today the TunableOp feature is minimally implemented for CUDA.  We don't lose much by skipping this test for that platform.

**Review by eqy — APPROVED** [review]

**Pull request closed without merging**
