### PR TITLE
Python stack tracing OD flow (part 2)

### PR DESCRIPTION
**Pull request by slgong-fb**
Summary: set flag

Test Plan:
MUST pass CI tests since
1) submodule updated (part 1)
2) flag is set (part 2)

Reviewed By: robieta

Differential Revision: D39177683

### CODE REVIEW

**Review by robieta — APPROVED** [review]
LGTM. I added extra CI since buck build runs in one of them. (Periodic, I think.)

**Comment by kit1980** [comment]
@robieta do we still want to merge this?

**Pull request closed without merging**
