### PR TITLE
Documenting the torch.utils.collect_env.get_pretty_env_info function

### LINKED ISSUE #127888: Document the torch.utils.collect_env.get_pretty_env_info function
Document the `torch.utils.collect_env.get_pretty_env_info` function located in [https://github.com/pytorch/pytorch/blob/main/torch/utils/collect_env.py#L601](https://github.com/pytorch/pytorch/blob/main/torch/utils/collect_env.py#L601).
Follow the [Docstring Guidelines](https://github.com/pytorch/pytorch/wiki/Docstring-Guidelines).

cc @brycebortree

### PR DESCRIPTION
**Pull request by kiszk**
Fixes #127888 

This PR adds docstring to the `torch.utils.collect_env.get_pretty_env_info` function

cc @svekars @brycebortree

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
sure why not

**Comment by ezyang** [comment]
I'll note that this module isn't linked from docs so you can't actually see it besides help()

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
