### PR TITLE
fix typo torch.functional.py

### PR DESCRIPTION
**Pull request by Kelvinthedrugger**
Fixes a typo in torch.functional.py document, which is not an existing issue
Thanks for your time

### CODE REVIEW

**Review by mrshenli — APPROVED** [review]

**Comment by Kelvinthedrugger** [comment]
Sorry for bothering

May I ask why is this merged blocked after passing all the CI tests and reviews by pytorch maintainers?
Is it because I was trying to merge to master branch, if it is, which branch should I merge to, given that each opened branch has it's main goal for developing.

Kindly pointed out which part I'm missing from the Contribution guide would be much appreciated.

Thanks

**Comment by mrshenli** [comment]
Hey @osalpekar, do you know how can I check which merge rule this PR violates? Thanks!

**Comment by osalpekar** [comment]
@mrshenli The job currently doesn't do a good job telling why exactly mergebot failed. I'll find out how we can fix this. Currently you are in the superuser group so your approval should suffice, but let me retry merging this.

**Review by osalpekar — APPROVED** [review]

**Comment by osalpekar** [comment]
@seemethere Do you know why this does not match merge rules despite having approval from superuser?

**Pull request closed without merging**
