### PR TITLE
Add details about ic, broken, flaky, and unstable checks to merge records

### PR DESCRIPTION
**Pull request by huydhn**
At the moment, we only record the list of pending and failed check on Rockset merge records. This is enough to compute the force merge KPI(s), but isn't enough for more in-depth analysis on what happened at the time of the merge:

* If the number of `ok_failed_checks` is less than `ok_failed_checks_threshold`, the list of `failed_checks` would be empty (expectedly).  So Rockset would only record an empty list.
* We support retry in PR, so the classifications on Dr.CI could be different than what dev observed at the time of the merge if retry completed successfully

### Testing

`python .github/scripts/trymerge.py --comment-id 1654010315 106095 --dry-run` (need to comment out some of the code to actually write a test record to Rockset), then manually verify it with

```
SELECT
    *
FROM
    commons.merges
WHERE
    pr_num = 106095
```

to see that `ignore_current_checks`, `broken_trunk_checks`, `flaky_checks`, and `unstable_checks` shows up correctly

### CODE REVIEW

**Comment by huydhn** [comment]
As this touches `find_matching_merge_rule`, I have imported this to run internal tests (if any) just in case.

**Review by clee2000 — APPROVED** [review]
Would it be easier to put a tuple of [job id, classification] for each job into rockset instead of separate lists for each classification?

**Comment by malfet** [comment]
Forward fix in https://github.com/pytorch/pytorch/pull/106203, but I wonder how it escaped testing in the first place

**Comment by huydhn** [comment]
> Forward fix in #106203, but I wonder how it escaped testing in the first place

I should have known.  It was a landrace with my own other change https://github.com/pytorch/pytorch/pull/106095 (ouch)

**Pull request closed without merging**
