### PR TITLE
Add missing error messages for container modules

### PR DESCRIPTION
**Pull request by songyouwei**
Container `Module`s, including `ModuleList`, `ParameterList` and `ParameterDict`, should not be called like a regular `Module`.
This PR add error messages for these special modules.

### CODE REVIEW

**Comment by vadimkantorov** [comment]
I am inheriting from ModuleList module and overriding the `forward` method. If I understand correctly, this scheme will break after this change.

**Comment by songyouwei** [comment]
@vadimkantorov Right. Maybe it is more appropriate that `ModuleList` can be callable, but `ParameterList` and `ParameterDict` are not.

**Comment by vadimkantorov** [comment]
For ModuleList / ModuleDict, maybe you could throw the same error in forward method? Then it would error out if someone does not override forward and still tries to do the __call__.

**Review by ezyang — APPROVED** [review]

**Comment by zou3519** [comment]
I'm not sure if this is actually bc-breaking, I am marking it as so to remember to come back to it.

**Pull request closed without merging**
