### PR TITLE
Run functorch tests in default shards; delete functorch-specific shards

### LINKED ISSUE #96347: Delete functorch-specific CI shards and integrate them into the regular CI configurations
## Motivation

functorch is a part of PyTorch Core and has been for a couple of months. The functorch tests run in [functorch-specific shards](https://github.com/pytorch/pytorch/blob/f5c39b7ba29772c0a40a0b2a12066342b8679aa4/.github/workflows/pull.yml#L30) for CI configurations (instead of the ["default" shards](https://github.com/pytorch/pytorch/blob/master/.github/workflows/pull.yml#L30) that all the other PyTorch Core tests run in).

To make things consistent, we would like the functorch tests to behave just like any other PyTorch Core tests (e.g. autograd, nn) -- they should just go in the "default" shards. This also has the advantage that when new CI configurations are added (e.g. dynamo, other devices), folks won't need to specifically add a functorch shard since functorch tests will be in the default set.

## Things to consider

- Time to signal for PyTorch tests. We don't want to regress this.

## Proposal

For each job configuration (e.g. linux-focal-py3_8-gcc7-build):
1. Delete the functorch shard (if it exists)
2. Make the functorch tests run as a part of the "default" shards
3. Increase the "default" shard count by 1, unless it doesn't make sense.
4. This will make functorch tests run on more configurations than before (e.g. rocm, dynamo). We can either selectively add expected failures and skips to tests or just add one big skip and make it more fine-grained later.

This is almost equivalent to just saying we are turning the functorch shard into a default shard.

Thoughts? If this sounds good, I can start putting up PRs for it. cc @seemethere @malfet @pytorch/pytorch-dev-infra @Chillee @samdow @soumith @kshitij12345 @janeyx99 @huydhn, @pytorch/pytorch-dev-infra

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #96464

Fixes #96347

This PR:

- Makes the functorch tests run as a part of the "default" shards
- Delete the functorch CI shard from all CI job configurations (if it exists)
- Increase the "default" shard count by 1 for each job, unless it was
previously set to 1, to accommodate the new functorch tests and not
regress time-to-signal.
- Adds a bunch of skips for ROCM and torchdynamo configurations. We can
investigate them later.

NB: I might go through some more iterations to figure out what other
skips need to be added, but this iteration of the PR seems to pass most CI.
suite.

Test Plan:
- wait for CI

### CODE REVIEW

**Comment by zou3519** [comment]
Not ready for review yet

**Comment by huydhn** [comment]
FYI, there is one remaining functorch shard for MacOS x86_64 in periodic https://github.com/pytorch/pytorch/blob/master/.github/workflows/periodic.yml#L313

**Review by huydhn — APPROVED** [review]
LGTM! Let's also update the MacOS x86_64 shard and wait if all tests pass

**Pull request closed without merging**
