### PR TITLE
Move VariableInfo into its own file to avoid circular dependency

### PR DESCRIPTION
**Pull request by xmfan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #120681
* __->__ #120732

VariableInfo is used by both `custom_function.h` (in a templated class) and `compiled_autograd.h` (in a class with some templated methods). Another way could have been to make a `compiled_autograd.cpp` and forward declare VariableInfo, but this VariableInfo was also being used in other nodes like PyNode so it felt cleaner to do it this way.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

Differential Revision: [D54287007](https://our.internmc.facebook.com/intern/diff/D54287007)

### CODE REVIEW

**Comment by xmfan** [comment]
@xmfan has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54287007).

**Review by albanD — COMMENTED** [review]
The move sounds fine, CI needs fixing though

**Comment by xmfan** [comment]
@xmfan has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54287007).

**Review by jansel — APPROVED** [review]

**Comment by xmfan** [comment]
@xmfan has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54287007).

**Pull request closed without merging**
