### PR TITLE
Update docstrings for  testing object type

### PR DESCRIPTION
**Pull request by ronrest**
Add docstring for `is_storage()` and `is_tensor()`

### CODE REVIEW

**Comment by fmassa** [comment]
Thanks!
I wonder if there are no docs for those functions yet because they might change in a near future, see https://github.com/pytorch/pytorch/issues/399 .
@apaszke Do you think `is_tensor` and `is_storage` will stick around?

**Comment by apaszke** [comment]
No, we want to make `torch.Tensor` and `torch.Storage` ABCs, so you can use `isinstance(obj, torch.Tensor)` instead of `torch.is_tensor(obj)`. They're a bit of legacy functions, we will probably have to deprecate them in some time.

**Comment by apaszke** [comment]
Sorry but the lint check has failed. Can you fix the PR please?

**Comment by soumith** [comment]
fixed lint and pushed via https://github.com/pytorch/pytorch/commit/34fa5e0dc70a168a3e576fbadbcf9d5e0b72af45

**Pull request closed without merging**
