### PR TITLE
Enhance NCCL watchdog to acitvely abort communicators for timed out ops.

### PR DESCRIPTION
**Pull request by pritamdamania87**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#32338 Enhance NCCL watchdog to acitvely abort communicators for timed out ops.**

Timed out ops could linger around if the user doesn't actually call
`wait()` on that OP. As result, to fix this I've introduced the following
functionality in this PR:

1. Keep track of all outstanding work in ProcessGroupNCCL.
2. Enhance NCCL watchdog to sweep through all outstanding work and perform the
following operations:
  i.   If the work has timed out, abort all communicators for that work and
       remove them from the cache.
  ii.  If the communicators for the work receive an error, abort the
       communicators and remove them from the cache.
  iii. If the work has completed (successfully/unsuccessfully), remove it from
       the list of outstanding work.

Differential Revision: [D19401625](https://our.internmc.facebook.com/intern/diff/D19401625/)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit f8b13c3c:


**None of the build failures appear to be your fault**.

* **1/1** recognized as flaky :snowflake:
    * Re-run these jobs?


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=f8b13c3c214c9d3150837b75fdf2e45038fdc70f).

### :snowflake: 1 failure recognized as flaky
The following build failures have been detected as flaky and **may not be your fault**:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4288279) pytorch_linux_xenial_cuda10_1_cudnn7_py3_multigpu_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=87608716) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=87608716)) :snowflake:
<details>
<summary>
<code>Jan 17 03:44:26 AssertionError: 6 not less than or equal to 1e-05 :</code>
</summary>

```
Jan 17 03:44:26 ---------------------------------------------------------------------- 
Jan 17 03:44:26 Traceback (most recent call last): 
Jan 17 03:44:26   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 130, in wrapper 
Jan 17 03:44:26     self._join_processes(fn) 
Jan 17 03:44:26   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 211, in _join_processes 
Jan 17 03:44:26     self._check_return_codes(elapsed_time) 
Jan 17 03:44:26   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 231, in _check_return_codes 
Jan 17 03:44:26     self.assertEqual(p.exitcode, first_process.exitcode) 
Jan 17 03:44:26   File "/var/lib/jenkins/workspace/test/common_utils.py", line 890, in assertEqual 
Jan 17 03:44:26     super(TestCase, self).assertLessEqual(abs(x - y), prec, message) 
Jan 17 03:44:26 AssertionError: 6 not less than or equal to 1e-05 :  
Jan 17 03:44:26  
Jan 17 03:44:26 ---------------------------------------------------------------------- 
Jan 17 03:44:26 Ran 117 tests in 204.222s 
Jan 17 03:44:26  
Jan 17 03:44:26 FAILED (failures=2, skipped=4) 
Jan 17 03:44:26  
Jan 17 03:44:26 Generating XML reports... 
Jan 17 03:44:27 Traceback (most recent call last): 
Jan 17 03:44:27   File "test/run_test.py", line 456, in <module> 
Jan 17 03:44:27     main() 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by zhaojuanmao** [comment]
the nccl error handling test failures are real

**Comment by pritamdamania87** [comment]
Looks like I didn't rebase on top of https://github.com/pytorch/pytorch/pull/31901 and that caused the errors. Hopefully the rebase fixes the CI issues.

**Review by zhaojuanmao — APPROVED** [review]
lgtm

**Comment by ezyang** [comment]
I think this diff is responsible for `test_broadcast_coalesced_nccl` flakiness on master in ROCm. This test is now failing on over 50% of jobs on master. Failures began two commits after this PR landed on master.  In this build on this PR https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/14009/console a similar error happened.

**Pull request closed without merging**
