### PR TITLE
[ROCm][Caffe2] Enable MIOpen 3D Pooling

### PR DESCRIPTION
**Pull request by lcskrishna**
This PR contains the following updates:
1. MIOpen 3D pooling enabled in Caffe2.
2. Refactored the MIOpen pooling code in caffe2.
3. Enabled unit test cases for 3D pooling.

CC: @ezyang @jeffdaily @ashishfarmer

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by jeffdaily** [comment]
@ezyang any help needed with the failed tests?

**Comment by ezyang** [comment]
Yes, it looks like the FB version of ROCm is too old:

```
Caused by: com.facebook.buck.core.exceptions.HumanReadableException: Command failed with exit code 1.
command: [/dev/shm/paragon/pods/104152727/home/execution/7cd13c0724cf4888955953e47150504a/work/fbcode/tools/build/wrap_hip.py, -_HIP_BIN_, /dev/shm/paragon/pods/104152727/home/execution/7cd13c0724cf4888955953e47150504a/work/fbcode/third-party-buck/platform007/tools/rocm/bin/hcc, -hc, -D__HIPCC__, -Wno-deprecated-register, -fno-...
<truncated>
...
stderr: buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/operators/hip/pool_op_miopen.hip/caffe2/operators/hip/pool_op_miopen.hip:77:20: error: use of undeclared identifier 'miopenSetNdPoolingDescriptor'; did you mean 'miopenPoolingDescriptor'?
    MIOPEN_ENFORCE(miopenSetNdPoolingDescriptor(
                   ^
third-party-buck/platform007/build/rocm/include/miopen/miopen.h:267:23: note: 'miopenPoolingDescriptor' declared here
MIOPEN_DECLARE_OBJECT(miopenPoolingDescriptor);
                      ^
third-party-buck/platform007/build/rocm/include/miopen/miopen.h:67:12: note: expanded from macro 'MIOPEN_DECLARE_OBJECT'
    struct name                     \
           ^
```

So it looks like you're going to have to version guard these appropriately, or maybe cc @xw285cornell to find out who is able to upgrade the FB internal version of ROCm.

**Comment by jeffdaily** [comment]
@ezyang thank you for the detail on the failure. @lcskrishna working on adding version guards.

**Comment by jeffdaily** [comment]
@xw285cornell I would like more information on the internal ROCm upgrade process, timeline, blockers, etc.  Thanks.

**Comment by xw285cornell** [comment]
@jeffdaily yeah it's better to add version guard. I've tried ROCm 3.1 and 3.3 for our internal upgrade, but I have to abort because of multiple clamp device segfaults (as you can see in your ticket system). I think I'll try another one when your 3.5 is released as it switches to hip-clang. It might be a major one for our internal toolchain integration.

**Comment by xw285cornell** [comment]
Also the rocm test failed with SIGIOT. Do you think ROCm can provide more info about it? Just saying access an illegal page isn't very informative and hard to debug.

**Comment by jeffdaily** [comment]
@xw285cornell the mem access fault and SIGIOT is tracked and related to FBA-180.

What is the current ROCm version used internally, so I can know how far back to version protect?

**Comment by xw285cornell** [comment]
@jeffdaily we're stuck with 2.7 unfortuately.

**Comment by lcskrishna** [comment]
@ezyang @jeffdaily  ready for review.

**Comment by jeffdaily** [comment]
@xw285cornell would you like to try landing this PR again now that version guards are in place?

**Review by jeffdaily — APPROVED** [review]
LGTM.  All CI tests pass, as well.

**Comment by ezyang** [comment]
...internal build is failing in an even more delightfully weird way

```
BUILD FAILED
More details at https://our.intern.facebook.com/intern/buck/build/4781ddd3-e459-4207-8315-b36f29294ec3
Command failed with exit code 255.
command: [/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/tools/build/wrap_hip.py, -_HIP_BIN_, /data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/hcc, -hc, -D__HIPCC__, -Wno-deprecated-register, -fno-gpu-rdc, -D__STRICT_ANSI__, -Wno-unused-command-line-argument, -...
<truncated>
...
stderr:  #0 0x00000000018cb73a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/opt+0x18cb73a)
 #1 0x00000000018c97a4 llvm::sys::RunSignalHandlers() (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/opt+0x18c97a4)
 #2 0x00000000018c98d2 SignalHandler(int) (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/opt+0x18c98d2)
 #3 0x00007ff9facf5630 __restore_rt (/lib64/libpthread.so.0+0xf630)
 #4 0x0000000001286840 llvm::ReplaceableMetadataImpl::getIfExists(llvm::Metadata&) (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/opt+0x1286840)
 #5 0x00000000012868a4 llvm::MetadataTracking::untrack(void*, llvm::Metadata&) (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/opt+0x12868a4)
 #6 0x00007ff9f9b10ce9 __run_exit_handlers (/lib64/libc.so.6+0x39ce9)
 #7 0x00007ff9f9b10d37 (/lib64/libc.so.6+0x39d37)
 #8 0x00007ff9f9af955c __libc_start_main (/lib64/libc.so.6+0x2255c)
 #9 0x00000000006eab75 _start (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/opt+0x6eab75)
third-party-buck/platform007/tools/rocm/bin/clamp-device: line 210:  6486 Segmentation fault      (core dumped) $OPT ${KMOPTOPT} -mtriple amdgcn-amd-amdhsa -mcpu=$AMDGPU_TARGET -load $LIB/LLVMSelectAcceleratorCode.so -load $LIB/LLVMPromotePointerKernArgsToGlobal.so -select-accelerator-code -sac-enable-function-calls=$AMDGPU_FUNC_CALLS -promote-pointer-kernargs-to-global -infer-address-spaces -verify -o $2.opt.bc < $2.linked.bc
 #0 0x00000000018cb73a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/opt+0x18cb73a)
 #1 0x00000000018c97a4 llvm::sys::RunSignalHandlers() (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/opt+0x18c97a4)
 #2 0x00000000018c98d2 SignalHandler(int) (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/opt+0x18c98d2)
 #3 0x00007fbfa7ddc630 __restore_rt (/lib64/libpthread.so.0+0xf630)
 #4 0x0000000001286840 llvm::ReplaceableMetadataImpl::getIfExists(llvm::Metadata&) (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/opt+0x1286840)
 #5 0x00000000012868a4 llvm::MetadataTracking::untrack(void*, llvm::Metadata&) (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/opt+0x12868a4)
 #6 0x00007fbfa6bf7ce9 __run_exit_handlers (/lib64/libc.so.6+0x39ce9)
 #7 0x00007fbfa6bf7d37 (/lib64/libc.so.6+0x39d37)
 #8 0x00007fbfa6be055c __libc_start_main (/lib64/libc.so.6+0x2255c)
 #9 0x00000000006eab75 _start (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/third-party-buck/platform007/tools/rocm/bin/opt+0x6eab75)
third-party-buck/platform007/tools/rocm/bin/clamp-device: line 210:  6485 Segmentation fault      (core dumped) $OPT ${KMOPTOPT} -mtriple amdgcn-amd-amdhsa -mcpu=$AMDGPU_TARGET -load $LIB/LLVMSelectAcceleratorCode.so -load $LIB/LLVMPromotePointerKernArgsToGlobal.so -select-accelerator-code -sac-enable-function-calls=$AMDGPU_FUNC_CALLS -promote-pointer-kernargs-to-global -infer-address-spaces -verify -o $2.opt.bc < $2.linked.bc
hcc: error: HC assembler command failed with exit code 255 (use -v to see invocation)
\033[1;33m[WARNING] You're compiling AMD GPU files w/ sanitizer. AMD ROCm hcc compiler doesn't support ASAN or TSAN.
Please switch to unsanitized mode (dev-nosan or opt).
For now we'll skip -fsanitize=address/thread flags to continue building, but your AMD GPU run WILL crash.
\033[0m
    When running <hip preprocess_and_compile>.
    When building rule //caffe2/caffe2:caffe2_gpu_hip#compile-pic-spatial_batch_norm_op_miopen.hip.oc208090f,platform007-clang,v8fcb3a7.
```

**Comment by jeffdaily** [comment]
@ezyang any way to know whether this PR is the root cause of this latest internal build failure?

Ideally, we could try and reproduce in our developer systems.  Any way you could share how your internal build environment works?  From earlier discussion, use ROCm 2.7.  But what command is used to configure and compile?

**Comment by xw285cornell** [comment]
third-party-buck/platform007/tools/rocm/bin/clamp-device: line 210:  6485 Segmentation fault      (core dumped) $OPT ${KMOPTOPT} -mtriple amdgcn-amd-amdhsa -mcpu=$AMDGPU_TARGET -load $LIB/LLVMSelectAcceleratorCode.so -load $LIB/LLVMPromotePointerKernArgsToGlobal.so -select-accelerator-code -sac-enable-function-calls=$AMDGPU_FUNC_CALLS -promote-pointer-kernargs-to-global -infer-address-spaces -verify -o $2.opt.bc < $2.linked.bc

So this is seg faulting from clamp device. I've seen this a few times while upgrading to 3.1 and 3.3.

**Comment by lcskrishna** [comment]
CC: @sunway513

**Comment by gottbrath** [comment]
@ezyang @lcskrishna  -- It seems like we started merging this and encountered trouble. Can either of you post a few words about the next steps that are required to move this forward?

**Comment by xw285cornell** [comment]
Most tests are passing now internally (it's probably flaky before). I'll wait for the rest a few tests to pass and then land it.

**Comment by xw285cornell** [comment]
All tests passed. Landing

**Review by xw285cornell — APPROVED** [review]

**Pull request closed without merging**
