### PR TITLE
dropout update in autodiff

### PR DESCRIPTION
**Pull request by jjsjann123**
1. Unifies dropout op in autodiff
2. Removes dropout inference support in autodiff

### CODE REVIEW

**Comment by jjsjann123** [comment]
symbolic_script.cpp is used by both PE as well as legacy executor. As we guard and bail autodiff for dropout in PE, legacy executor doesn't use `guardDifferentiableGraph`, so we are generating wrong results for dropout with inference mode :cry:

I don't see a clean way to resolve this. Maybe we can try to do a pattern matching to restore the old autodiff graph with control flow for legacy executor.
@eellison Any suggestions?

**Comment by eellison** [comment]
let's just not fuse dropout in autodiff for legacy executor. it's off by default,  we want to delete it soon, and it's not fusing right now anyway. cc @Krovatkin , maintenance burden of legacy executor

**Comment by Krovatkin** [comment]
> let's just not fuse dropout in autodiff for legacy executor. it's off by default, we want to delete it soon, and it's not fusing right now anyway. cc @Krovatkin , maintenance burden of legacy executor

@eellison @jjsjann123 sounds good to me.

**Review by eellison — COMMENTED** [review]
looks good, but we should add a runtime guard instead of bailing with a non-constant `train` parameter

**Review by eellison — APPROVED** [review]
Cool!! LGTM!!

**Comment by ngimel** [comment]
Unlanding, broke a lot of OSS tests

**Comment by jjsjann123** [comment]
Can we get some more context here.

What are OSS tests, how are they broken, any error logs that would give us some idea to fix/patch and reland?
:pray:

**Pull request closed without merging**
