### PR TITLE
error in codegen if vendor provides kernel for a composite op with no derivative formula

### PR DESCRIPTION
**Pull request by bdhirsh**
Error if someone tries to modify the yaml by adding a composite op that would result in losing autograd for that op (because we can no longer use the composite formula).

This fails locally (correctly) on master because `logical_and` is improperly labeled as `CompositeExplicitAutograd` but doesn't have a derivative formula. So I'll merge this after https://github.com/pytorch/pytorch/pull/69169 goes through.

Failure error:
```
AssertionError:
Found an entry for 'logical_not' in the yaml. This operator is composite, which means that by default it will decompose into base operators. If decomposing is fine, then you can simply remove the entry from the yaml file. If you wish to provide an explicit kernel directly for this composite op, you can do so by:
 (a) moving the operator name under the 'autograd' entry in the yaml file
 (b) writing a custom Autograd Function for the operator

Error if someone tries to modify the yaml by adding a composite op that would result in losing autograd for that op (because we can no longer use the composite formula).

This fails locally (correctly) on master because `logical_and` is improperly labeled as `CompositeExplicitAutograd` but doesn't have a derivative formula. So I'll merge this after https://github.com/pytorch/pytorch/pull/69169 goes through.

Failure error:
```
AssertionError:
Found an entry for 'logical_not' in the yaml. This operator is composite, which means that by default it will decompose into base operators. If decomposing is fine, then you can simply remove the entry from the yaml file. If you wish to provide an explicit kernel directly for this composite op, you can do so by:
 (a) moving the operator name under the 'autograd' entry in the yaml file
 (b) writing a custom Autograd Function for the operator
```

Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #69686
* #68531
* #68530
* #68529

Differential Revision: [D33018607](https://our.internmc.facebook.com/intern/diff/D33018607)

### CODE REVIEW

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32988785).

**Comment by bdhirsh** [comment]
@wconstab I remade https://github.com/pytorch/pytorch/pull/69169 against master here. It also fails (correctly) on some improperly labeled composite ops in core, which I'm fixing first at https://github.com/pytorch/pytorch/pull/69169

@guoyejun can you re-check your changes against this stack of PR's? I updated the whole stack and I'll try to land them all soon.

**Review by wconstab — APPROVED** [review]
cool, thanks for updating this!

**Comment by guoyejun** [comment]
> 
> @guoyejun can you re-check your changes against this stack of PR's? I updated the whole stack and I'll try to land them all soon.

sure, I'll update my patches (https://github.com/pytorch/pytorch/pull/69074 and https://github.com/pytorch/pytorch/pull/68562) based on branch gh/bdhirsh/167/head

**Comment by guoyejun** [comment]
> > @guoyejun can you re-check your changes against this stack of PR's? I updated the whole stack and I'll try to land them all soon.
> 
> sure, I'll update my patches (#69074 and #68562) based on branch gh/bdhirsh/167/head

done, thanks

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33018607).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33018607).

**Pull request closed without merging**
