### PR TITLE
Warn users of mkldnn device usage

### PR DESCRIPTION
**Pull request by yanbing-j**
In https://github.com/pytorch/pytorch/issues/136831, user will use mkldnn device to generate tensor, while mkldnn device is no longer used as device type, and only mkldnn layout is used.

We plan to remove mkldnn device related code in the future release. This PR is to warn users not to use mkldnn device.

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @Guobing-Chen @Xia-Weiwen @snadampal

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Comment by cyyever** [comment]
Is it better to replace current 'mkldnn' device code to 'cpu' before landing it?

**Review by ezyang — CHANGES_REQUESTED** [review]
(1) I would prefer to accept PRs that remove the deprecated usage first, (2) this needs to be a warn once, you are going to spam this over and over again as is, and (3) are you actually doing the same logic if you do "mkldnn" versus "cpu"??

**Comment by yanbing-j** [comment]
> (1) I would prefer to accept PRs that remove the deprecated usage first, (2) this needs to be a warn once, you are going to spam this over and over again as is, and (3) are you actually doing the same logic if you do "mkldnn" versus "cpu"??

@ezyang Thanks for the comments!
(1) I update the title and description as this PR is to warn users not to use mkldnn device type. Is this okay?
(2) Updating `TORCH_WARN_ONCE` to be a warn once is done.
(3) Mkldnn device is not helpful in current PyTorch, even in creating tensors. I update the warning to be `Please use other valid device types instead.` to let users use `cpu`, `cuda` or other valid device types. Not specific to `cpu` any more.

cc @jgong5

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
