### PR TITLE
Masked scale meta function registration #119984

### PR DESCRIPTION
**Pull request by satheeshhab**
Fixes #119984

### CODE REVIEW

**Comment by satheeshhab** [comment]
Can CI be triggered for this? Thanks

**Review by cpuhrsch — APPROVED** [review]

**Comment by cpuhrsch** [comment]
This seems unrelated to masking operations (despite it's name), but looks reasonable. The implementation essentially forwards a call to a dropout kernel
https://github.com/pytorch/pytorch/blob/12d6446507df794e5f1f563250bbbd8bbd08044b/aten/src/ATen/native/cuda/Dropout.cu#L410-L414

Interestingly enough it also mentions a PR that is supposed to remove it: https://github.com/pytorch/pytorch/pull/63937

**Comment by satheeshhab** [comment]
I have corrected the lint issue and updated the patch

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
