### PR TITLE
Fix MSVC 14.38 - VS 2022 Build

### LINKED ISSUE #115922: Pytorch build from source fails
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
Pytorch build from source fails
Provide a short description.

## Code example

``
Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:

wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
base) E:\ons_5\ons_py_torch\ons_pytorch_build>python setup.py develop
Building wheel torch-2.3.0a0+gitUnknown
-- Building version 2.3.0a0+gitUnknown
cmake --build . --target install --config Release
[9/5776] Linking CXX static library lib\libprotobuf-lite.lib
FAILED: lib/libprotobuf-lite.lib
cmd.exe /C "cd . && E:\PROGRA~2\MICROS~3\2022\BUILDT~1\VC\Tools\MSVC\1437~1.328\bin\Hostx64\x64\lib.exe /nologo /machine:x64 /ignore:4049 /ignore:4217 /ignore:4099 /ignore:4221 /out:lib\libprotobuf-lite.lib third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\any_lite.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\arena.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\extension_set.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\generated_enum_util.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\generated_message_table_driven_lite.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\generated_message_util.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\implicit_weak_message.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\io\coded_stream.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\io\io_win32.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\io\strtod.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\io\zero_copy_stream.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\io\zero_copy_stream_impl.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\io\zero_copy_stream_impl_lite.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\message_lite.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\parse_context.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\repeated_field.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\stubs\bytestream.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\stubs\common.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\stubs\int128.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\stubs\status.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\stubs\statusor.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\stubs\stringpiece.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\stubs\stringprintf.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\stubs\structurally_valid.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\stubs\strutil.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\stubs\time.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\__\src\google\protobuf\wire_format_lite.cc.obj third_party\protobuf\cmake\CMakeFiles\libprotobuf-lite.dir\version.rc.res  && C:\ProgramData\Anaconda3\Library\bin\cmake.exe -E __run_co_compile --lwyu=lib\libprotobuf-lite.lib && cd ."
Error running 'ldd': The system cannot find the file specified
[14/5776] Building CXX object third_party\protobuf\cmake\C...le\protobuf\compiler\csharp\csharp_reflection_class.cc.obj
ninja: build stopped: subcommand failed.

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source):  python setup.py develop
- OS: win 10
- PyTorch version:  torch version 2.3.0
- Python version: 3.9.7
- CUDA/cuDNN version: not used
- GPU models and configuration: not used
- GCC version (if compiling from source): visual studio build tools
- CMake version:  3.9.6
- Versions of any other relevant libraries:
Kind regards,
Manu

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

### PR DESCRIPTION
**Pull request by ghost**
Fixes #115922

This PR is prepared to separate existing https://github.com/pytorch/pytorch/pull/116926 and to apply suggestions in the review.

`scalar_t` which is defined as `c10::impl::ScalarTypeToCPPType<ScalarType::Half>::t` appears to be causing the issue with `Visual Studio 2022 17.8.4`  (coming with `MSVC 14.38.33130`)

Error message:
```
aten\src\ATen/cpu/vec/vec_base.h(150): fatal error C1001: Internal compiler error.
(compiler file 'D:\a_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\toinil.c', line 910)
```

---

Related line was added for a similar issue before as a workaround (`scalar_t` definition) [Fix compile error for vs2022](https://github.com/pytorch/pytorch/pull/85958)

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by ezyang** [comment]
I admit to being a bit perplexed; why would removing the workaround fix the build?

**Review by ezyang — APPROVED** [review]

**Review by malfet — APPROVED** [review]
This looks fine to me, but also weird, as essentially it backs out previous workaround, so I assume it will break some compilers (cc: @osalpekar to keep an eye on the internal windows builds during the import)

@ozanMSFT is it possible to guard this with `#ifdef` for a particular MSVC version?

**Comment by patrikhuber** [comment]
I've filed this ICE on the Visual Studio team bug tracker in December, see here https://developercommunity.visualstudio.com/t/post/10539393. Microsoft must have updated their compiler, making the old workaround in libtorch redundant - but at the same time they must have introduced this ICE. I personally think this is fine without ifdef as most people should be able to update to the newer minor/patch release of Visual Studio / MSVC and not be stuck on this older minor version.

**Pull request closed without merging**
