### PR TITLE
[mergebot] dont run land checks when trunk label is there

### PR DESCRIPTION
**Pull request by zengk95**
### Description

As we're adding accept2run, we don't want to do the typical land validation if ciflow/trunk is already on the PR. In this case, we default to the on_green checks to make sure all the PR checks and trunk checks are green before merging it in.
### Issue
https://github.com/pytorch/test-infra/issues/448

### Testing

Tested it locally and made sure land checks was false and on_ green was true
```
LANDCHECKS False ONGREEN True
Attempting merge of https://github.com/pytorch/pytorch/pull/82338 (0.003352566560109456 minutes elapsed)
Traceback (most recent call last):
  File "/Users/kerryz/pytorch/.github/scripts/trymerge.py", line 1247, in main
    merge(args.pr_num, repo,
  File "/Users/kerryz/pytorch/.github/scripts/trymerge.py", line 1178, in merge
    find_matching_merge_rule(pr, repo)
  File "/Users/kerryz/pytorch/.github/scripts/trymerge.py", line 979, in find_matching_merge_rule
    raise RuntimeError(reject_reason)
RuntimeError: Matched rule OSS CI, but PR #82338 has not been reviewed yet
(pytorch) kerryz@kerryz-mbp pytorch % 
```

### CODE REVIEW

**Comment by zengk95** [comment]
Merge failed due to Matched rule OSS CI, but PR #82338 has not been reviewed yet

**Comment by zengk95** [comment]
Merge failed due to Matched rule OSS CI, but PR #82338 has not been reviewed yet

**Review by clee2000 — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Pull request closed without merging**
