### PR TITLE
fix(dtensor): fix dtensor expand_as

### LINKED ISSUE #122485: DTensor doesn't support expand_as dispath mode
### 🐛 Describe the bug

```
 def test_expand_with_broadcast(self):
        device_mesh = self.build_device_mesh()
        tensor = torch.randn((4,))
        matrix = torch.randn((2, 3, 4))
        dtensor = distribute_tensor(tensor, device_mesh, [Replicate()])
        dmatrix = distribute_tensor(matrix, device_mesh, [Shard(0)])
        dout = dtensor.expand_as(dmatrix)
        assert dout._spec.placements[0] == Shard(0), f"sharding error {dout._spec}"
```

expand_as dispatch is missing, so the dispatch can't capture expand_as op, so the sharding of dst opeartor is missing

### Versions

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: 11.0.1-2
CMake version: version 3.26.1
Libc version: glibc-2.31

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.4.56.bsk.9-amd64-x86_64-with-glibc2.31
Is CUDA available: N/A
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration:
GPU 0: NVIDIA A10
GPU 1: NVIDIA A10
GPU 2: NVIDIA A10
GPU 3: NVIDIA A10

Nvidia driver version: 535.129.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8336C CPU @ 2.30GHz
Stepping:                        6
CPU MHz:                         2600.000
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4600.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        108 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] byted-torch==2.3.0.dev20240109+cu121
[pip3] flake8==6.1.0
[pip3] mypy==1.7.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] optree==0.10.0
[pip3] pytorch-triton==2.2.0+e28a256d71
[pip3] torch==2.3.0a0+git3811b18
[pip3] torchdistx==0.3.0.dev0+cu118
[pip3] torchvision==0.16.2
[pip3] triton==2.1.0
[conda] Could not collect
```

### PR DESCRIPTION
**Pull request by JsBlueCat**
expand_as is missing dispatch-key, 
we need to handle it that it can be parse to sharding prop
so we add dispatch to expand_as prop

Fixes #122485

### CODE REVIEW

**Comment by malfet** [comment]
Is it possible to add test of some sort?

**Comment by wanchaol** [comment]
please add some tests as @malfet suggested, looks like trunk failures related to the change

**Comment by ezyang** [comment]
The approach in this PR is unlikely to work. I'm not sure what the DTensor problem is, but @wanchaol how were you expecting it to be fixed.

**Comment by JsBlueCat** [comment]
i will add some test to it

**Comment by wanchaol** [comment]
> The approach in this PR is unlikely to work. I'm not sure what the DTensor problem is, but @wanchaol how were you expecting it to be fixed.

I was mainly thinking that it seems `expand_as` does not desugar to some lower level aten op (maybe it actually does?)

@JsBlueCat what are the failures you are facing? wouldn't `expand_as` be de-sugared to `aten.expand.default` under the hood? iirc DTensor have that implemented already https://github.com/pytorch/pytorch/blob/main/torch/distributed/_tensor/ops/view_ops.py#L470

**Comment by JsBlueCat** [comment]
> > The approach in this PR is unlikely to work. I'm not sure what the DTensor problem is, but @wanchaol how were you expecting it to be fixed.
> 
> I was mainly thinking that it seems `expand_as` does not desugar to some lower level aten op (maybe it actually does?)
> 
> @JsBlueCat what are the failures you are facing? wouldn't `expand_as` be de-sugared to `aten.expand.default` under the hood? iirc DTensor have that implemented already https://github.com/pytorch/pytorch/blob/main/torch/distributed/_tensor/ops/view_ops.py#L470

i found that, the expand_as doesn't have dispatch key, which will cause this fail

**Comment by ezyang** [comment]
Oh I see. expand only gets size, expand_as gets the full tensor, and you want to look at the sharding info on the as target to make a sharding decision for the exapnd. This seems reasonable.

**Comment by ezyang** [comment]
Maybe a less invasive change is to remap DTensor's expand_as to some sort of expand_with_sharding which takes in the extra sharding as an explicit argument. Not sure...

**Comment by JsBlueCat** [comment]
i add expand_as backward to support expand_as backward pass
by the way, i don't know how to run the test case. i saw ci run script, it will run many test files. it will be very time-costing.
can everybody teach me how to run single unit test with python and c ?  i want to fully test this change

**Comment by ezyang** [comment]
It's not clear to me that there is actually a way to do this out of the box today. We might talk about this at composability sync tomorrow, not sure, there's a lot of stuff on the docket.

**Comment by wanchaol** [comment]
> Maybe a less invasive change is to remap DTensor's expand_as to some sort of expand_with_sharding which takes in the extra sharding as an explicit argument. Not sure...

@ezyang thinking about this more, I think this is not easy to approach at least from DTensor alone, purely because DTensor would never see the `expand_as` in its torch_dispatch, it only see `expand`.. If we want to do this I guess it would be somewhat invasive to the `torch.expand_as` C++ implementation to check if it's DTensor type and remap to a function 🤔 

This make me feel it is reasonable to make expand_as be not decomposed to expand but rather directly make it a dispatcher function

**Comment by JsBlueCat** [comment]
> To add another datapoint: For NT, we get around this type of issue by using `__torch_function__` to intercept before we decomp at expand_as. Opting into `__torch_function__` opens you up into a different set of issues though that we're still working to resolve.
> 
> (For expand_as specifically though, decompose into expand is fine for NT because the shape passed to expand_as should capture the metadata we need)

the dispatch overhead is very time costing , we need to c -> python -> c -> python ...  i can't tolerant that.

**Pull request closed without merging**
