### PR TITLE
[core aten] Add ops to core aten set

### PR DESCRIPTION
**Pull request by angelayi**
Update the list of core aten ops with the ones we determined [here](https://docs.google.com/spreadsheets/d/1u9jQ-uGlKu-fe9nLy-jS2AIPtpE8sGTmELOFYgKOhXU/edit#gid=1098862752).

```
aten::adaptive_avg_pool1d
aten::_adaptive_avg_pool3d
aten::_cdist_forward
aten::_embedding_bag
aten::_local_scalar_dense
aten::_native_batch_norm_legit_no_training
aten::_native_batch_norm_legit
aten::_pdist_forward
aten::any
aten::any.dim
aten::avg_pool1d
aten::avg_pool3d
aten::bitwise_and.Scalar
aten::bitwise_or.Scalar
aten::bitwise_xor.Scalar
aten::ceil
aten::clamp.Tensor
aten::cumsum
aten::embedding
aten::floor
aten::fmod.Scalar
aten::index_put
aten::index.Tensor
aten::logical_xor
aten::mean
aten::mean.dim
aten::pixel_shuffle
aten::prod
aten::prod.dim_int
aten::rand
aten::randperm
aten::reflection_pad_1d
aten::reflection_pad_2d
aten::reflection_pad_3d
aten::remainder.Scalar
aten::roll
aten::round
aten::scatter.src
aten::scatter.value
aten::select_scatter
aten::sort
aten::split.Tensor
aten::split_with_sizes
aten::squeeze.dims
aten::tan
aten::unsqueeze
aten::var.correction
```

### CODE REVIEW

**Review by kirklandsign — APPROVED** [review]
I reviewed that all the added ops are in the doc.

**Review by SS-JIA — APPROVED** [review]

**Comment by SherlockNoMad** [comment]
`native_batch_norm_legit`
`native_batch_norm_legit_no_training`
`native_batch_norm_legit_functional`
 are the "functionalization-happy" variants of batch norm that show up in inductor / export today
 
 So we need to include all three.

**Review by SherlockNoMad — APPROVED** [review]

**Comment by angelayi** [comment]
Added `native_batch_norm_legit`. I think `native_batch_norm_legit_functional` doesn't exist as a direct function in native_functions.yaml

**Pull request closed without merging**
