### PR TITLE
[AOTI] Support MKL linear ops in cpp wrapper

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #136534
* __->__ #134974

Summary: Similar to https://github.com/pytorch/pytorch/pull/134475, support mkl linear in the ABI-compatible mode for cpp-wrapper Inductor.

Differential Revision: [D63322202](https://our.internmc.facebook.com/intern/diff/D63322202)

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @chauhang

### CODE REVIEW

**Comment by desertfire** [comment]
@jgong5 , the error msg in https://github.com/pytorch/pytorch/actions/runs/10706971866/job/29688092657 is not specific to cpp-wrapper. If I run `python test/inductor/test_cpu_select_algorithm.py -k test_linear_with_pointwise_batch_size_384_in_features_196_out_features_384_bias_False_epilogue_hardsigmoid_cpu_bfloat16` on the same CI node, I got the same error msg,
```
======================================================================
FAIL [5.713s]: test_linear_with_pointwise_batch_size_384_in_features_196_out_features_384_bias_False_epilogue_hardsigmoid_cpu_bfloat16 (__main__.TestSelectAlgorithmCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2979, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 448, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/var/lib/jenkins/workspace/test/inductor/test_cpu_select_algorithm.py", line 76, in wrapped
    return fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/unittest/mock.py", line 1379, in patched
    return func(*newargs, **newkeywargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/py_3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/py_3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/var/lib/jenkins/workspace/test/inductor/test_cpu_select_algorithm.py", line 273, in test_linear_with_pointwise
    self.assertEqual(counters["inductor"]["cpp_epilogue_fusion_counter"], 0)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3885, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Scalars are not equal!

Expected 0 but got 1.
Absolute difference: 1
Relative difference: inf
```
I suspect the error has always been there, but somehow test_linear_with_pointwise_batch_size_384_in_features_196_out_features_384_bias_False_epilogue_hardsigmoid_cpu_bfloat16 was not run on any other CI shards.

**Comment by desertfire** [comment]
@leslie-fang-intel , do you have any insights on this test failure, https://github.com/pytorch/pytorch/actions/runs/10999418222/job/30548129713 ?

**Comment by leslie-fang-intel** [comment]
> test_linear_with_pointwise

From the log, it seems we didn't hint the oneDNN fusion passes and cause the check failure of `cpp_epilogue_fusion_counter`. Will take a further look.

**Comment by leslie-fang-intel** [comment]
From the failure log, it seems the issue occurs when the CI system doesn’t support BF16/FP16. Specifically, `torch.ops.mkldnn._is_mkldnn_bf16_supported()` and `torch.ops.mkldnn._is_mkldnn_fp16_supported()` return False. As a result, the oneDNN fusion passes aren’t triggered, leading to a different number of `cpp_epilogue_fusion_counter` counter. Modified the check for this case and see what the CI thinks.

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D63322202).

**Review by chenyang78 — APPROVED** [review]

**Review by leslie-fang-intel — APPROVED** [review]

**Pull request closed without merging**
