### PR TITLE
Refactor batch sampler

### LINKED ISSUE #8652: Batch Sampler and Dataset indexing too restricted
I was trying to use a Dataloader with a sampler of strings to index my dataset. The default [BatchSampler](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/sampler.py#L104) threw me an error that essentially str cannot be casted to int. The cast in question happens on line 139 (currently):
```
batch.append(int(idx))
```
I copied the source for the Batch Loader from master, removed the cast, and everything worked as expected.

[``torch.utils.data``](https://pytorch.org/docs/stable/data.html) ``DataLoader`` doesn't suggest that samplers should return integers, and the various Samplers just say list of indices. An index set doesn't have to be integers. Now ``Dataset`` *does* say ``__getitem__`` should support **integer** indexing, but why?

Really, the choice of sampler (including choosing by default the default sampler) drives whether a Dataset must be indexable by integers. On the other hand, sometimes it's more sensible to "key" the dataset. For example, the sampler could "request" the a filename be loaded. Or, the actual data could be organized in a dict (like I have in my examples below).

Along the way, I noticed that BatchLoader is now asserting that ``sampler`` is a ``Sampler``. (This isn't the case in 0.4.0, just master). I don't really understand why. Why not duck type that ``sampler`` is iterable? Just a try-except around the for-loop that catches TypeError and returns whatever type of error. It breaks the example if I'm not mistaken, and excludes a very useful way to unittest.

## MWE
```
from string import ascii_lowercase
import torch
from torch._six import int_classes as _int_classes
from torch.utils.data import sampler, DataLoader


# CHANGES to BatchSampler in master: Removing type cast and removing sampler
# explicit type-check, adding iterable duck-type
class BatchSampler(sampler.Sampler):
    r"""Wraps another sampler to yield a mini-batch of indices.
    Args:
        sampler (Sampler): Base sampler.
        batch_size (int): Size of mini-batch.
        drop_last (bool): If ``True``, the sampler will drop the last batch if
            its size would be less than ``batch_size``
    Example:
        >>> list(BatchSampler(range(10), batch_size=3, drop_last=False))
        [[0, 1, 2], [3, 4, 5], [6, 7, 8], [9]]
        >>> list(BatchSampler(range(10), batch_size=3, drop_last=True))
        [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
    """
    def __init__(self, sampler, batch_size, drop_last):
        if not isinstance(batch_size, _int_classes) or isinstance(batch_size, bool) or \
                batch_size <= 0:
            raise ValueError("batch_size should be a positive integeral value, "
                             "but got batch_size={}".format(batch_size))
        if not isinstance(drop_last, bool):
            raise ValueError("drop_last should be a boolean value, but got "
                             "drop_last={}".format(drop_last))
        self.sampler = sampler
        self.batch_size = batch_size
        self.drop_last = drop_last

    def __iter__(self):
        batch = []
        try:
            for idx in self.sampler:
                batch.append(idx)
                if len(batch) == self.batch_size:
                    yield batch
                    batch = []
            if len(batch) > 0 and not self.drop_last:
                yield batch
        except TypeError:
            raise ValueError("sampler should be an iterable, "
                                       "but got sampler={}".format(sampler))

    def __len__(self):
        if self.drop_last:
            return len(self.sampler) // self.batch_size
        else:
            return (len(self.sampler) + self.batch_size - 1) // self.batch_size


dataset_stub = {ascii_lowercase[i]: i for i in range(20)}
sampler = sampler.SubsetRandomSampler(list(dataset_stub.keys()))
loader = DataLoader(dataset_stub, batch_sampler=BatchSampler(sampler, 1, True))

for elem in loader:
    print(elem)
```
## M.should-be-W.E.:
```
from string import ascii_lowercase
import torch
from torch.utils.data import sampler, DataLoader

dataset_stub = {ascii_lowercase[i]: i for i in range(20)}
sampler = sampler.SubsetRandomSampler(list(dataset_stub.keys()))
loader = DataLoader(dataset_stub, sampler=sampler)

for elem in loader:
    print(elem)
```

### LINKED ISSUE #8957: BatchSampler docstring is outdated
## Issue description

The examples in the BatchSampler docstring cause exceptions.

## Code example

Copy pasted from https://github.com/pytorch/pytorch/blob/master/torch/utils/data/sampler.py#L115

```python
In [1]: from torch.utils.data.sampler import BatchSampler
In [2]: list(BatchSampler(range(10), batch_size=3, drop_last=False))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-6b5b38ed53b0> in <module>()
----> 1 list(BatchSampler(range(10), batch_size=3, drop_last=False))

~/miniconda/envs/pytorch4/lib/python3.6/site-packages/torch/utils/data/sampler.py in __init__(self, sampler, batch_size, drop_last)
    122             raise ValueError("sampler should be an instance of "
    123                              "torch.utils.data.Sampler, but got sampler={}"
--> 124                              .format(sampler))
    125         if not isinstance(batch_size, _int_classes) or isinstance(batch_size, bool) or \
    126                 batch_size <= 0:

ValueError: sampler should be an instance of torch.utils.data.Sampler, but got sampler=range(0, 10)
```

## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.5
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.14.2)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] pytorch                   0.4.0           py36_cuda0.0_cudnn0.0_1    pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

### PR DESCRIPTION
**Pull request by dmitriy-serdyuk**
Fixes #8652, fixes #8957

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by alsrgv** [comment]
This change makes `DistributedSampler` very slow.  To repro, take [MNIST example](https://github.com/pytorch/examples/blob/master/mnist/main.py) and add `DistributedSampler`:

```python
    train_dataset = \
        datasets.MNIST('../data', train=True, download=True,
                       transform=transforms.Compose([
                           transforms.ToTensor(),
                           transforms.Normalize((0.1307,), (0.3081,))
                       ]))
    train_loader = torch.utils.data.DataLoader(train_dataset,
        batch_size=args.batch_size, sampler=torch.utils.data.distributed.DistributedSampler(train_dataset, num_replicas=1, rank=0), **kwargs)
```

The reason seems to be that it creates a lot of tensors for each index element.  I was able to make it fast again by adding the cast to int.

cc @dmitriy-serdyuk, @apaszke

**Comment by fmassa** [comment]
Thanks for the message @alsrgv !
The better fix is to [replace this line](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/distributed.py#L41) with something like
```python
indices =torch.randperm(len(self.dataset), generator=g).tolist()
```

as `list(tensor)` returns now a list of 0d tensors, while what we want is to return a list with python numbers (obtained via `tensor.tolist()`).

Can you send a PR fixing this?

**Comment by bearpelican** [comment]
Fixes it for me!

**Comment by alsrgv** [comment]
@fmassa, thanks for the suggestion. Submitted as #10361

**Pull request closed without merging**
