### PR TITLE
Fixing conda test builds

### PR DESCRIPTION
**Pull request by pjh5**

### CODE REVIEW

**Comment by pjh5** [comment]
Aborted tests b/c they don't touch these changes

**Comment by ezyang** [comment]
Is this OK to merge? I see the test timing out now.

Just a friendly reminder that, steady state, the conda installs should live in the docker image, and not be done in the test script. That will improve test times, especially when downloads are big.

**Comment by pjh5** [comment]
I'll move the conda installs to the docker image and overwrite these changes

**Comment by pjh5** [comment]
Canceled tests cause requires new docker images first

**Comment by smessmer** [comment]
Can you stop the docker-trigger build and rerun once you rebased on master? It's going to erase my changes in  https://github.com/pytorch/pytorch/pull/6195 otherwise.

**Comment by smessmer** [comment]
@pjh5

**Comment by ezyang** [comment]
Please un-WIP this when this is ready for review again

**Comment by pjh5** [comment]
Passed docker-trigger https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/99/ (with retries https://ci.pytorch.org/jenkins/job/caffe2-docker/job/py2-centos7/87/ and https://ci.pytorch.org/jenkins/job/caffe2-docker/job/py2-cuda8.0-cudnn7-centos7/80/ and https://ci.pytorch.org/jenkins/job/caffe2-docker/job/py3.5-clang3.9-ubuntu16.04/54/ and https://ci.pytorch.org/jenkins/job/caffe2-docker/job/conda3-cuda8.0-cudnn7-ubuntu16.04/51/).

Passed master https://ci.pytorch.org/jenkins/job/caffe2-master/977/ , except for current failing builds. Don't think those builds should be affected by these conda-only changes anyways.

**Review by ezyang — APPROVED** [review]
Person who merges should make sure DockerVersion is up to date with the Docker changes.

**Comment by pjh5** [comment]
I will merge upon confirmation that conda tests are working as expected

**Comment by pjh5** [comment]
Conda test worked here https://ci.pytorch.org/jenkins/job/caffe2-builds/job/conda2-ubuntu16.04-trigger-test/260/

**Pull request merged**
