### PR TITLE
[FlexAttention] Fix Sparse block multiple to ceildiv instead for floor div

### PR DESCRIPTION
**Pull request by drisspg**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134538
* #134511
* #134507

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Comment by drisspg** [comment]
@Pytorchbot merge

**Pull request closed without merging**
