### PR TITLE
Add caching support for Dataset class

### LINKED ISSUE #35642: Caching Support for class Dataset
## 🚀 Feature

For datasets that fit into memory, but the samples are loaded individually a cache could decrease the time needed to fetch the samples. In each call to the dataset the cache should be checked for the existence of the object to be loaded and if possible return the cached sample.
## Motivation

Loading data from the file system or even worse from network storage can take a considerable amount of time. Since training speed is limited by the time it takes to load the requested data, speed-ups on the data fetching side can lead to improved training time and higher utilization of the computational resources.
## Pitch

A simple function like the following could handle the caching:
```
    def get_item(self, index):
        if index in self.cache.keys():
            return self.cache[index]
        sample = self.load_item(index)
        self.cache[index] = sample
        return sample
```
However, for this sample to work the function `load_item` needs to be implemented by the user just like using `Dataset` directly.

## Additional context

I started defining the required class, however, found that my implementation requires to much action using this as a base class.
I would appreciated any suggestions to reduce the complexity of this proposal:
````
class CachingDataset(Dataset):
    r"""A caching :class:`Dataset`.

    All subclasses should overwrite :meth:`load_item`, supporting fetching a
    data sample from file.
    Subclasses could also optionally overwrite
    :meth:`__len__`, which is expected to return the size of the dataset by many
    :class:`~torch.utils.data.Sampler` implementations and the default options
    of :class:`~torch.utils.data.DataLoader`.
    For datasets that fit into the memory this allows faster data loading from the second batch on
    by caching the loaded data into the `cache`.

    .. note::
      Performance gains will be visible from the second epoch on.

    Example 1: Loading data from cache if available using  :meth:`get_item`::

        >>> class MyCachingDataset(torch.utils.data.CachingDataset):
        ...     def __init__(self):
        ...         super().__init__()
        ...
        ...     def load_item(self, index):
        ...         sample = read_from_file(self.data[index])
        ...         return sample
    """
    def __init__(self):
        self.cache = dict()

    def __getitem__(self, index):
        return self.get_item(index)

    def get_item(self, index):
        if index in self.cache.keys():
            return self.cache[index]
        sample = self.load_item(index)
        self.cache[index] = sample
        return sample

    def load_item(self, index):
        raise NotImplementedError
```

### PR DESCRIPTION
**Pull request by choidongyeon**
Fix https://github.com/pytorch/pytorch/issues/35642.

This is based on the feature request for cache support. In the thread, there is also a suggestion to implement this on the DataLoader-level, but after a few unsuccessful implementation, it's not exactly clear to me how we would do it. If anyone has a suggestion on how to go about it, I'd be more than happy to make modifications.

Thanks!

### CODE REVIEW

**Review by goswamig — APPROVED** [review]
LGTM

**Comment by SsnL** [comment]
Hi, sorry for not commenting on the original issue. The @ mention on that issue didn't work so I didn't get notifications.

I really don't think we should have this functionality in core, because dataset caching is IMO better handled in code specifically written according to use cases. The reasons are the following:
1. Caching `index->data` is often not what you want in DL. Most of the times stochastic augmentations are applied on the read data. While IO can be cached, stochastic augs can not. 
2. Unless the entire dataset is small, the cache won't have effect until the 2nd epoch is reached, at which point the entire dataset is in memory. But if the dataset is such small, the user might as well load it in to memory at the beginning.
3. When `num_workers > 0`, not only this doesn't have effect (unless a sampler that repeatedly samples data is used) (since a dataset object is sent to workers at the beginning of each epoch), this will also "leak" a lot of memory because a separate cache is used for each worker. 
4. Better and more robust caching supports already exist in python core lib (`functools.lru_cache`) and 3rd party libs specialized for this (e.g., `ring`, `methodtools` etc.). I don't think PyTorch should maintain another copy. When worker reusing is implemented, users could just use these existing decorators to add caching to their dataset.

**Comment by byronyi** [comment]
> Hi, sorry for not commenting on the original issue. The @ mention on that issue didn't work so I didn't get notifications.
> 
> I really don't think we should have this functionality in core, because dataset caching is IMO better handled in code specifically written according to use cases. The reasons are the following:
> 
> 1. Caching `index->data` is often not what you want in DL. Most of the times stochastic augmentations are applied on the read data. While IO can be cached, stochastic augs can not.
> 2. Unless the entire dataset is small, the cache won't have effect until the 2nd epoch is reached, at which point the entire dataset is in memory. But if the dataset is such small, the user might as well load it in to memory at the beginning.
> 3. When `num_workers > 0`, not only this doesn't have effect (unless a sampler that repeatedly samples data is used) (since a dataset object is sent to workers at the beginning of each epoch), this will also "leak" a lot of memory because a separate cache is used for each worker.
> 4. Better and more robust caching supports already exist in python core lib (`functools.lru_cache`) and 3rd party libs specialized for this (e.g., `ring`, `methodtools` etc.). I don't think PyTorch should maintain another copy. When worker reusing is implemented, users could just use these existing decorators to add caching to their datasets.

In contrast, a solid on-disk cache might come in handy. It is common if the dataset doesn't fit into memory, especially if it is transmitted over network (database, networked file system, downloaded over web services such as S3/GCS). And it is a little bit harder for regular users to implement themselves correctly than the in-memory cache; certainly more complicated than just loading everything into a Python dict. It will also be useful for (elastic) training in a larger scale cluster, such as those with no persistent local disks across training jobs (Kubernetes, Yarn) etc..

**Comment by SsnL** [comment]
@byronyi Very fair use case.  Although I am still not fully convinced that such support should be added in PyTorch core (because caching specifics for remote loading seems quite use case dependent and seem better implemented by users IMO), maybe we should design a set of advanced dataloading tutorials that cover examples on how users can implement these. Other topics that I think are relevant include bulk loading / transform, using CUDA in data loader workers, etc.

**Comment by SsnL** [comment]
@byronyi Actually after taking a look at the XLA CachedDataset (with file caching) you linked in another issue, it does look quite nice and potentially could be included in core.  One concern is (still) about the separation of deterministic and stochastic part in data loading. 

So far most PyTorch dataset code are not written as "wrappers", where a (e.g.,) a `TransformDataset` could wrap an actual dataset that is just responsible for IO, but as a single class that does transform and IO together at the same time (which is mainly populated by `torchvision` design).  With "wrapper" style, it would be much easier to separate the part where cache is needed, and the part where on-the-fly random augmentation is performed.  So I am a bit worried about the potential confusion from users when they see these two different design logics from PyTorch.

**Comment by chenzhekl** [comment]
Is there any hope for this PR to be merged? I am experiencing pretty slow IO for the cluster in the lab and then found this PR. Being able to cache the dataset incrementally into the memory could be a huge boost for the training speed.

**Pull request closed without merging**
