### PR TITLE
Fixing linting error for NotSupportedError

### PR DESCRIPTION
**Pull request by cjermain**
This PR fixes a linting error introduced in #34563.
@driazati, @tugrulince

https://github.com/pytorch/pytorch/pull/34563/files#diff-78aab5b4217aeaed920efab0c5f5f5c8L33

### CODE REVIEW

**Comment by driazati** [comment]
Looks like this has a lint failure too :(

But this is fine to land once that’s fixed

**Comment by driazati** [comment]
Looks like this fix has a lint failure too :(

But this is fine to land once that is fixed

**Comment by tugrulince** [comment]
Ah, I didn't realize removing code introduced the lint error, I assumed it was already there. My bad. Can't we just remove the import entirely now? I can get a PR if you want.

**Comment by cjermain** [comment]
The backward compatibility test is failing because of changes in #34047.
```
Mar 13 16:15:41 Broken ops: [
Mar 13 16:15:41 	aten::_linear_packed(Tensor packed_weight, Tensor input) -> (Tensor)
Mar 13 16:15:41 	aten::_linear_prepack(Tensor weight, Tensor? bias=None, float? output_min=None, float? output_max=None) -> (Tensor)
Mar 13 16:15:41 	aten::_conv2d_packed(Tensor packed_weight, Tensor input) -> (Tensor)
Mar 13 16:15:41 	aten::_conv2d_prepack(Tensor weight, Tensor? bias=None, int[2] stride=[1, 1], int[2] padding=[0, 0], int[2] dilation=[1, 1], int groups=1, float? output_min=None, float? output_max=None) -> (Tensor)
```
The 4 functions have been removed in:
https://github.com/pytorch/pytorch/pull/34047/files#diff-9fddf4399643791133d551d69123dfccL61

**Comment by tugrulince** [comment]
@cjermain #34778 may be a good alternative to this PR.

**Comment by cjermain** [comment]
Sounds good. Let's resolve it in #34778.

**Pull request closed without merging**
