### PR TITLE
Update torch.lu_unpack docs

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #73878
* #73877
* #74046
* #73806
* #73804
* __->__ #73803
* #72935

As per title

### CODE REVIEW

**Review by IvanYashchuk — APPROVED** [review]

**Review by nikitaved — APPROVED** [review]
Thank you, Mario!

**Review by mruberry — APPROVED** [review]
Stamped!

**Comment by Lezcano** [comment]
Relanding in https://github.com/pytorch/pytorch/pull/77635

**Pull request closed without merging**
