### PR TITLE
[WIP] Add pr sanity check workflow

### PR DESCRIPTION
**Pull request by albanD**

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Comment by huydhn** [comment]
@albanD I just notice that there are a bunch of PRs like this one https://github.com/pytorch/pytorch/pull/83333 that fails this new pr-sanity-checks (https://github.com/pytorch/pytorch/pull/83295). This looks like a bug in the new script, is that PR 83333 that big?

cc @janeyx99 @seemethere @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
> @albanD I just notice that there are a bunch of PRs like this one #83333 that fails this new pr-sanity-checks (#83295). This looks like a bug in the new script, is that PR 83333 that big?

Fixed by https://github.com/pytorch/pytorch/pull/83344

**Pull request closed without merging**
