### PR TITLE
Bf16 matmul

### PR DESCRIPTION
**Pull request by zhuhaozhe**
Re-create PR to fix https://github.com/pytorch/pytorch/pull/61891.

Drop the support for addbmm.

### CODE REVIEW

**Comment by zhuhaozhe** [comment]
Hi, @VitalyFedyunin. This is re-opened PR for #61891

**Comment by ngimel** [comment]
1) This doesn't respect global setting `torch.backends.mkldnn.enabled` - is this intentional? Other operations using mkldnn do
2) It sprinkles way too many AT_MKLDNN_ENABLED and conditional includes around, making code harder to read. Instead, you can have `use_mkldnn_bf16_gemm` in the conditionally compiled region that always returns false if AT_MKLDNN_ENABLED is false. Calling `mkldnn_matmul` even if AT_MKLDNN_ENABLED is false is not a problem, it's still defined and will error out (but this situation should never happen)
3) squeeze/unsqueeze are also better abstracted in mkldnn_matmul rather than in generic code
4) it makes sense to drop support for addbmm, otherwise you are calling it from the cite where cpu/cuda dispatch hasn't happened (which lead to previous error). You are mitigating it with checking device now, but it's still additional code complexity for an extremely rarely used function.

**Comment by zhuhaozhe** [comment]
> 1. This doesn't respect global setting `torch.backends.mkldnn.enabled` - is this intentional? Other operations using mkldnn do
> 2. It sprinkles way too many AT_MKLDNN_ENABLED and conditional includes around, making code harder to read. Instead, you can have `use_mkldnn_bf16_gemm` in the conditionally compiled region that always returns false if AT_MKLDNN_ENABLED is false. Calling `mkldnn_matmul` even if AT_MKLDNN_ENABLED is false is not a problem, it's still defined and will error out (but this situation should never happen)
> 3. squeeze/unsqueeze are also better abstracted in mkldnn_matmul rather than in generic code
> 4. it makes sense to drop support for addbmm, otherwise you are calling it from the cite where cpu/cuda dispatch hasn't happened (which lead to previous error). You are mitigating it with checking device now, but it's still additional code complexity for an extremely rarely used function.

Hi, @ngimel. Thanks to point out, I have modified this PR based on your comment above.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by zhuhaozhe** [comment]
Hi, @VitalyFedyunin @ngimel 
We have some changes for this PR.
- We need to add support for "addbmm" back for performance reasons:
 -- MKLDNN matmul primitive can support input dims > 2 cases and will get better performance compare with use for loop to call addmm.
 -- The overhead for using MKLDNN is constant. Use for loop to call multiple times MKLDNN matmul will get more overhead.
- We need to consider "B" dimension for gemm size

torch.addbmm
| impl |2x16x16x16|10x16x16x16|
|:---:|:---:| :---: |
| aten-bf16 | 31.24us| 146.46us|
| mkldnn-bf16-for-loop |44.646us |200.54us|
| mkldnn-bf16 |28.131us |30.03us|

 - Dispatch to mkldnn matmul more earlier in addmm_impl_cpu, before m1 and m2 may swapped and the computing for gemm size will not be wrong.

**Comment by ngimel** [comment]
`addbmm` is an extremely rarely used function (in all of fb codebase it's used a single time), mkldnn matmul primitive does not support it directly, you had to special case it. Making code more complicated for it is not warranted.

**Comment by zhuhaozhe** [comment]
> `addbmm` is an extremely rarely used function (in all of fb codebase it's used a single time), mkldnn matmul primitive does not support it directly, you had to special case it. Making code more complicated for it is not warranted.

Thanks. I just drop it since it is rarely used.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
We need to freeze at this point, if we want everything merged into 1.10

**Comment by zhuhaozhe** [comment]
> We need to freeze at this point, if we want everything merged into 1.10

OK, thanks

**Pull request closed without merging**
