### PR TITLE
Add BFloat16 support to CPU nansum

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #61083

It's already supported on CUDA, so it seems reasonable to support on CPU as
well. This also changes `test_nansum` to compare against `torch.sum` since numpy
doesn't support BFloat16. Note that `test_nansum_vs_numpy` checks against
NumPy as well, so that's still being tested.

Differential Revision: [D30006227](https://our.internmc.facebook.com/intern/diff/D30006227)

### CODE REVIEW

**Review by heitorschueroff — APPROVED** [review]
LGTM!

**Comment by heitorschueroff** [comment]
@peterbell10 Can you please rebase and fix the lint issues and then I'll import this.

**Comment by peterbell10** [comment]
@heitorschueroff rebased and lint/tests are passing.

**Comment by heitorschueroff** [comment]
@heitorschueroff has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30006227).

**Pull request closed without merging**
