### PR TITLE
Revert "Simplify handle indexing (#105006)"

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #105985
* __->__ #105984

This reverts commit 429d45f91a5b636844954363851be309d8203b56.

Unfortunately, https://github.com/pytorch/pytorch/pull/105006 broke backward prefetching (where backward prefetching working correctly was not captured in our unit tests).

I need more time to dig into this (tomorrow), but I think the issue is related to:
https://github.com/pytorch/pytorch/commit/429d45f91a5b636844954363851be309d8203b56#diff-9a6937168d232432c34c2c4605b96f3147afa2786e287f74b6074b20aa5980e6R143-R146

Follow-ups:
1. Investigate this thoroughly
2. Add unit tests to capture backward prefetch functionality

Differential Revision: [D47816273](https://our.internmc.facebook.com/intern/diff/D47816273)

### CODE REVIEW

**Review by fegin — APPROVED** [review]
Stamped to unblock

**Comment by awgu** [comment]
Failure is unrelated:
[linux-focal-rocm5.6-py3.8 / test (default, 2, 3, linux.rocm.gpu, unstable](https://hud.pytorch.org/pr/pytorch/pytorch/105984#15345545774)

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D47816273).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D47816273).

**Pull request closed without merging**
