### PR TITLE
Improve Windows Compatibility

### PR DESCRIPTION
**Pull request by peterjc123**
Improves Windows Compatibility by modifying the code.
The changes mainly fall into four categories: 
1. data type conversions like long to int64_t
2. Windows-specific scripts like build_all.bat
3. Windows-specific C++ codes or libs like libshm-windows 
4. Windows-specific python codes helps finding DLLs

### CODE REVIEW

**Comment by ezyang** [comment]
If we're serious about Windows support, we should get Appveyor builds going so that we can have Windows support under CI.

**Comment by soumith** [comment]
Yes, that's what I meant by CircleCI. Appveyor / CircleCI, whatever works.

**Comment by apaszke** [comment]
Thanks @peterjc123! However, do you think you could to break down this PR into smaller ones? It's impossible for us to review a 25k line change (which IIRC is nearly 1/3 of the whole library).

**Comment by apaszke** [comment]
It seems you've also merged #1408, while we haven't. Can you remove these commits from your branch?

**Comment by hughperkins** [comment]
So many changed files, it refuses to even list their names :-)

screen shot 2017-07-06 at 9 14 55 am

**Comment by hughperkins** [comment]
[bystander remark] Strong preference to migrate bash scripts to python, rather than forking into cmd.

You can see an example of this approach in Coriander:
- original horrible bash script. Nasty, nasty ... https://github.com/hughperkins/coriander/blob/master/bin/cocl
- python script.  actually shorter, even though more functionality, and easier to read, and more or less portable: https://github.com/hughperkins/coriander/blob/master/bin/cocl.py

Similarly, jenkins/install scripts written in python, and more or less portable:
- https://github.com/hughperkins/coriander/blob/master/install_distro.py
- https://github.com/hughperkins/coriander/blob/master/jenkins/u1604.py

**Comment by peterjc123** [comment]
Since the new PR #2402 is ready, this old one should be closed.

**Pull request closed without merging**
