### PR TITLE
Move typeid.h to ATen/core

### PR DESCRIPTION
**Pull request by ezyang**
Summary:
- Remove dependency on caffe2/core/common.h, reintroducing
  necessary local header includes
- Deduplicate Demangle/DemangleType with their ATen equivalents

Differential Revision: D9132432

### CODE REVIEW

**Comment by ezyang** [comment]
This PR is blocked on unifying at::Error and caffe2::EnforceNotMet

**Comment by varunagrawal** [comment]
@ezyang on compiling the latest master, I get this error:

```
pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `at::Error::Error(at::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
```

Is this related to the `unifying at::Error and caffe2::EnforceNotMet` PR?

**Comment by ezyang** [comment]
Yes, it probably is related. Can you do a clean build and if that doesn't resolve it, file an issue?

**Comment by varunagrawal** [comment]
Did a pull and clean build and it works. Thanks for the input!

**Pull request closed without merging**
