### PR TITLE
torchhub for private repository

### PR DESCRIPTION
**Pull request by corochann**
This PR adds additional functionality to torchhub. Backward compatibility is not broken.

Usage example is as follows:

```
from torch import hub

# 1. we can specify username & password for private repo access
os.environ["GIT_USER"] = "username"
os.environ["GIT_PASSWORD"] = "My github token password here"

# 2. we can specify github.xxx.com (for example github enterprise URL etc) instead of github.com.
# Below code accesses https://github.xxx.com/user/repo_name 's my_resnet method.
model = hub.load('github.xxx.com/user/repo_name', 'my_resnet')

# It keeps original behavior, below code accesses https://github.com/pytorch/vision
model = hub.load('pytorch/vision', 'resnet18', pretrained=True)
```

## 1. Use username/password to download private repository.
If there is github **private** repository with `hubconf.py`, you need to send username & password to download the repository.

In this PR, it checks environment variable `GIT_USER` and `GIT_PASSWORD`, and if it's set username and password are sent using `header` of url request.
If these environment variables are not set, function's behavior is same with previous.

## 2. It enables to use other websites (like github enterprise) instead of `github.com`.

Other use case is to use github enterprise repository, instead of github.com repository.
Now we can additionally set git server's URL, as example shown on top.

If git server url is not set explicitly, it will access `github.com` as default. So backward compatibility is not broken.

### CODE REVIEW

**Review by ailzhang — COMMENTED** [review]
I think it's okay to add support for private repo, although testing might be tricky... without a proper test in `test_utils.py`, this will be easily broken without any notification.

**Comment by corochann** [comment]
Thank you for comment, do you have any suggestion about how to test?

**Comment by ailzhang** [comment]
@corochann We do have hub tests available at https://github.com/pytorch/pytorch/blob/master/test/test_utils.py#L509. 
And it's pulling from an example repo under my github account.... It does get a bit trickier if we want to test against private repos. cc: @soumith @malfet  Do you have any idea what's the best way to test this? Thanks!

**Comment by corochann** [comment]
I see, how about creating an account only for testing torch hub private repo and create access token https://github.com/settings/tokens
and just expose this token in the test_utils.py to test the functionality?

**Comment by corochann** [comment]
ping @ailzhang 
May I create new github account and try creating private repository to test the functionality?

**Comment by ailzhang** [comment]
@corochann Sorry for the late reply! Yea feel free to create one!(We can definitely help maintain the test account once this PR merges) Thanks!

**Comment by corochann** [comment]
I created github account with username "pytorch-hub-test", created private github repository whose content is same with public torchhub test github repo.
I implemented test to download from this private repo, is it okay?

Sorry, this is my first time to send PR to pytorch and I am not sure which test need to be fixed (now 8 tests are failing). Please advise.

**Comment by ailzhang** [comment]
Ah if you have to put password in the test it's not the best way to do it... 
In fact, let's take a step back, since recently hub can support local directories, maybe it's the best to ask users to clone the repo with proper credentials first and then call hub.load()? Wdyt? 
I feel making hub.load() handling authentication might create some security issues as well.

**Comment by corochann** [comment]
Just a comment is that this password is github token and not the log in password.
Only repository access is authorized for this token.
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

However, I understand your suggestion. It might suffice to use local repository feature now. Let me check.

**Comment by mulcyber** [comment]
Any news on this feature ?

**Comment by corochann** [comment]
No updates. 

> It might suffice to use local repository feature now.

So, maybe okay to close this.

**Pull request closed without merging**
