### PR TITLE
update `SequentialLR` signature

### PR DESCRIPTION
**Pull request by rohitgr7**
- ~optimizer isn't required for `SequentialLR` since it's already present in the schedulers. Trying to match the signature of it with `ChainedScheduler`.~
- ~`verbose` isn't really used anywhere so removed it.~

updated missing docs and added a small check

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Hi,
Thanks for the PR, but we won't be able to remove arguments like that, this is not backward compatible (even though it makes sense given the current doc :/ )

But it would be good to check that the `optimizer` argument match what is in the schedulers indeed and indeed the doc is missing the two args which we should add back.

**Comment by rohitgr7** [comment]
> Hi, Thanks for the PR, but we won't be able to remove arguments like that, this is not backward compatible (even though it makes sense given the current doc :/ )
> 
> But it would be good to check that the `optimizer` argument match what is in the schedulers indeed and indeed the doc is missing the two args which we should add back.

hey @albanD 
yeah, I can make these updates. what about `verbose`? should it be kept or removed since it doesn't actually do anything at all?

quick ques:  shouldn't we deprecate and remove it totally? both of these arguments don't add any significance at all. If you think this should be deprecated, can you share some steps on how to go about it? can't find it in the contributing guide.

**Review by albanD — COMMENTED** [review]
I do think they should be deprecated but that would be part of a bigger cleanup of the LR Schedulers.
So to avoid breaking things twice. I think we just want to document both optimizer and verbose for now (even though the second does nothing).
And we will do the deprecation/removal as part of the LR Scheduler cleanup later.

**Review by albanD — APPROVED** [review]
Looks good, thanks!

**Pull request closed without merging**
