### PR TITLE
Added Swish Activation Function

### PR DESCRIPTION
**Pull request by FuriouslyCurious**
An implementation of Swish: a Self-Gated Activation Function which is simply f(x)=x⋅sigmoid(x)

Clearly I spent the entire night coding this massive PR.

### CODE REVIEW

**Comment by Kaixhin** [comment]
Given the simplicity of this activation function, [controversy over prior work](https://www.reddit.com/r/MachineLearning/comments/773epu/r_swish_a_selfgated_activation_function_google/), and [unclear improvements](https://twitter.com/ajmooch/status/921056455045844992), we probably want to hold off from adding this straight away.

**Comment by soumith** [comment]
same concerns as Kai. lets wait this one out for a bit before adding it into the core

**Comment by FuriouslyCurious** [comment]
Sure - I am okay with waiting for the PR a bit till controversy over prior work settles down.

With regards to improvements, Swish gave a pretty impressive bump on our medical-domain (Chest X-Rays) problem.  

https://twitter.com/AiAiHealthcare/status/921048615346458625

**Comment by allenye0119** [comment]
I've recently read this [paper](https://arxiv.org/abs/1901.02671), thought this would provide another aspect.

**Comment by BramVanroy** [comment]
Here's [a comparative study of different activation functions](https://www.aclweb.org/anthology/D18-1472). I think `swish` comes out as a good performer, so adding it to PyTorch _might_ be worth it.

**Pull request closed without merging**
