### PR TITLE
[C++ API] Make torch::Tensor -> at::Tensor

### PR DESCRIPTION
**Pull request by goldsborough**
This PR removes the `using Tensor = autograd::Variable;` alias from `torch/tensor.h`, which means `torch::Tensor` is now `at::Tensor`. This PR fixes up some last uses of `.data()` and tidies up the resulting code. For example, I was able to remove `TensorListView` such that code like

```
auto loss = torch::stack(torch::TensorListView(policy_loss)).sum() +
    torch::stack(torch::TensorListView(value_loss)).sum();
```

is now

```
auto loss = torch::stack(policy_loss).sum() + torch::stack(value_loss).sum();
```

CC @jgehring 

@ebetica

### CODE REVIEW

**Review by ebetica — APPROVED** [review]

**Comment by ezyang** [comment]
CC @gchanan 

What's going on with the `data()` method? We may be making moves towards Tensor/Variable unification C++ side earlier rather than later, to avoid a massive perf slowdown when TH starts using Tensor (and previously nonvirtual calls would have become virtual).

**Comment by goldsborough** [comment]
@ezyang so it's good that this PR gets rid of `.data()` usage, no?

**Comment by ebetica** [comment]
@ezyang afaik this _should_ only affect the C++ API users. The library writers are free to pass around Variables as they wish. The main issue for the users is that Variable.data() and Tensor.data() do different things.

**Comment by gchanan** [comment]
We should rename one of those `data` functions -- it's too confusing as is.

**Pull request closed without merging**
