### PR TITLE
Remove hard numpy dependency from experimental_ops.py

### PR DESCRIPTION
**Pull request by cpuhrsch**
Based on similar code in the codebase

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Review by XilunWu — COMMENTED** [review]
As "numpy" is a prerequisite of PyTorch, is it helpful to add this exception catch?

**Comment by cpuhrsch** [comment]
Oh @XilunWu, my bad! I didn't see that https://github.com/pytorch/pytorch/pull/10771 added numpy as a hard dependency to PyTorch. I'll close this.

**Comment by cpuhrsch** [comment]
@XilunWu - Hm, it seems like we should [update our dependencies to reflect this](https://github.com/pytorch/pytorch/blob/64660b51f68605cfadcc91ed16761012d11a71b3/setup.py#L1088-L1095). Until then I'll reopen this PR just in case.

**Review by albanD — APPROVED** [review]
Thanks Christian!

FYI @malfet we really need this CI config without numpy!

**Pull request closed without merging**
