### PR TITLE
document tf32 on the reproducibility page

### LINKED ISSUE #47287: Add TF32 Information to Reproducibility Page
## 📚 Documentation

PyTorch 1.7 enabled TensorFloat32 computation by default, which may affect the reproducibility of results across hardware. I believe this should be mentioned in the [reproducibility documentation](https://pytorch.org/docs/stable/notes/randomness.html) (so people are aware they should disable it if they want their results to be more consistent across multiple devices):

cc @ngimel @jlin27 @mruberry @zasdfgbnm

### PR DESCRIPTION
**Pull request by n2cholas**
Fixes #47287

### CODE REVIEW

**Comment by mruberry** [comment]
This is a significant section for TF32 that's not directly related to the content in the note.

The reproducibility note opens with:

```
Completely reproducible results are not guaranteed across PyTorch releases, individual commits, or different platforms. Furthermore, results may not be reproducible between CPU and GPU executions, even when using identical seeds.
```

And I think we could elaborate on that idea in a new section, and in that new section there could be examples of why the same program may produce different results even when a user tries to enforce determinism. The key idea is that different algorithms can be used, and that may occur because of different math libraries or different hardware. TF32 is an example of a hardware-driven algorithmic change, but there's no reason to think that the convolutions cuDNN performs on Ampere in float32 are the same as those it performs on Volta architectures, either. Magnifying TF32 so much suggests we think it's a more significant change than usual, but I don't think we have any evidence for that.

**Comment by n2cholas** [comment]
@mruberry makes sense, in that case, should we just close this PR and issue?

**Comment by mruberry** [comment]
> @mruberry makes sense, in that case, should we just close this PR and issue?

I think there are three options to choose from:

1) close them
2) update the issue to reflect the latest thinking
3) update this PR to add the section described in the above comment

**Comment by n2cholas** [comment]
@mruberry got it, I misread your original comment. I'll add those comments and update the PR.

**Comment by n2cholas** [comment]
I think the sentence you pointed out gives users enough of an idea (`Completely reproducible results are not guaranteed across PyTorch releases, individual commits, or different platforms. Furthermore, results may not be reproducible between CPU and GPU executions, even when using identical seeds.`), and I can't think of other good examples/descriptions to illustrate this concern without giving undue attention to TF32. For that reason, I'll close this. Thanks for the feedback.

**Comment by mruberry** [comment]
OK. Thank you for your thoughtfulness, @n2cholas.

**Pull request closed without merging**
