### PR TITLE
Add `baddbmm` meta function

### PR DESCRIPTION
**Pull request by nkaretnikov**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96548

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by nkaretnikov** [comment]
Similar to https://github.com/pytorch/pytorch/pull/78992. See `common_checks_baddbmm_bmm` and `TORCH_META_FUNC(baddbmm)` in core.

Enables `baddbmm` test in inductor with dyn-shapes. The ATen version uses `structured`, which doesn't support `SymInt` (known codegen limitation).

**Review by ezyang — APPROVED** [review]
How come there isn't a test_proxy_tensor xfail removal

**Pull request closed without merging**
