### PR TITLE
Compilation error fix for torch/csrc/distributed/rpc/init.cpp

### PR DESCRIPTION
**Pull request by agolynski**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #57214 Add futures to ProcessGroupMPI work (but not including Send/Recv) and python DDP comm hook testing
* **#57486 Compilation error fix for torch/csrc/distributed/rpc/init.cpp**

Differential Revision: [D28162480](https://our.internmc.facebook.com/intern/diff/D28162480)

### CODE REVIEW

**Review by wayi1 — APPROVED** [review]

**Comment by SciPioneer** [comment]
I think it's better to replace it with `std::unordered_map<c10::Device, c10::Device>` rather than `DeviceMap`. Although they are the same thing, `DeviceMap` seems to be only defined for tensorpipe.

See the method in the parent virtual class `RpcAgent::getDeviceMap`:
https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/rpc_agent.h#L267

**Comment by agolynski** [comment]
> I think it's better to replace it with `std::unordered_map<c10::Device, c10::Device>` rather than `DeviceMap`. Although they are the same thing, `DeviceMap` seems to be only defined for tensorpipe.
> 
> See the method in the parent virtual class `RpcAgent::getDeviceMap`:
> https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/rpc_agent.h#L267

moved def of DeviceMap to rpc_agent

**Comment by SciPioneer** [comment]
> > I think it's better to replace it with `std::unordered_map<c10::Device, c10::Device>` rather than `DeviceMap`. Although they are the same thing, `DeviceMap` seems to be only defined for tensorpipe.
> > See the method in the parent virtual class `RpcAgent::getDeviceMap`:
> > https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/rpc_agent.h#L267
> 
> moved def of DeviceMap to rpc_agent

Thanks for the update! Please do the same for RpcAgent:
https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/rpc_agent.h#L267
and
https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/rpc_agent.cpp#L292

**Comment by SciPioneer** [comment]
Close this one, since the update is in https://github.com/pytorch/pytorch/pull/57500

**Pull request closed without merging**
