### PR TITLE
[optim] use lerp whenever possible

### PR DESCRIPTION
**Pull request by janeyx99**
Why?
- slight perf improvements
- BE for clarity

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104781
* #104780
* #104779
* #104669

### CODE REVIEW

**Comment by vadimkantorov** [comment]
for addcmul/second moment cases, I propose to address it with a new function: sth like `mix3` discussed in https://github.com/pytorch/pytorch/issues/71683#issuecomment-1379058082

**Comment by janeyx99** [comment]
> for addcmul/second moment cases, I propose to address it with a new function: sth like `mix3` discussed in [#71683 (comment)](https://github.com/pytorch/pytorch/issues/71683#issuecomment-1379058082) / [#79352 (comment)](https://github.com/pytorch/pytorch/issues/79352#issuecomment-1152946076)

👍

> maybe inductor can already generate perfect CUDA code for some function like this...

Yes we are working on torch.compiling the default foreach implementations, so the fusion improvements here are for eager.

> also `max_exp_avg_sqs[i].copy_(torch.maximum(max_exp_avg_sqs_i, exp_avg_sq))` could probable be `torch.maximum(max_exp_avg_sqs_i, exp_avg_sq, out = max_exp_avg_sqs[i])` saving an allocation (the exact same thing is actually done a few lines down)

Yea, good catch. I'll make an issue to track similar things like this for the forloop optimizers, as I'm currently going through the more pressing foreach ones.

**Comment by vadimkantorov** [comment]
> Yes we are working on torch.compiling the default foreach implementations, so the fusion improvements here are for eager.

I mean that maybe one could introduce in core an eager function `mix3` (generalization of addcmul)  and have just its impl torch.compile'd

**Review by albanD — APPROVED** [review]
Very nice!

**Comment by janeyx99** [comment]
Closing this in favor of https://github.com/pytorch/pytorch/pull/104796--moving to a new stack to avoid overstacking and to isolate the problems for lerp in this PR.

**Pull request closed without merging**
