### PR TITLE
Add logcumsumexp forward-ad

### PR DESCRIPTION
**Pull request by qqaatw**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #100629

### <samp>🤖 Generated by Copilot at 8bb6158</samp>

This pull request adds forward and backward AD support for the `logcumsumexp` operator in functorch, a library for composable function transformations. It implements a forward-mode formula and a decomposition in `derivatives.yaml`, a C++ function for computing directional derivatives in `FunctionsManual.cpp`, and updates the tests and metadata in `test_ops.py` and `common_methods_invocations.py`.

### CODE REVIEW

**Review by soulitzer — APPROVED** [review]
LGTM, thanks!

**Comment by clee2000** [comment]
Hi, sorry but I think this breaks `test_ops_fwd_gradients.py::TestFwdGradientsCUDA::test_fn_fwgrad_bwgrad_logcumsumexp_cuda_float64` in slow gradcheck

https://hud.pytorch.org/pytorch/pytorch/commit/bf52d570d9be0167501cd6a206b7e262e6d3860c
https://ossci-raw-job-status.s3.amazonaws.com/log/13253665591
```
2023-05-05T07:45:15.0702087Z FAILED [3.8987s] test_ops_fwd_gradients.py::TestFwdGradientsCUDA::test_fn_fwgrad_bwgrad_logcumsumexp_cuda_float64 - torch.autograd.gradcheck.GradcheckError: Jacobian computed with forward mode mismatch for output 0 with respect to input 0,
2023-05-05T07:45:15.0702814Z numerical:tensor([[ 2.9476e-08,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
2023-05-05T07:45:15.0703114Z           0.0000e+00,  0.0000e+00],
2023-05-05T07:45:15.0703482Z         [ 0.0000e+00, -8.7175e-03,  0.0000e+00,  ...,  0.0000e+00,
2023-05-05T07:45:15.0703743Z           0.0000e+00,  0.0000e+00],
2023-05-05T07:45:15.0704104Z         [ 0.0000e+00,  0.0000e+00,  2.1797e-02,  ...,  0.0000e+00,
2023-05-05T07:45:15.0704376Z           0.0000e+00,  0.0000e+00],
2023-05-05T07:45:15.0704591Z         ...,
2023-05-05T07:45:15.0704938Z         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -7.0372e-02,
2023-05-05T07:45:15.0705212Z           0.0000e+00,  0.0000e+00],
2023-05-05T07:45:15.0705474Z         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
2023-05-05T07:45:15.0705795Z          -4.1210e-06,  0.0000e+00],
2023-05-05T07:45:15.0706074Z         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
2023-05-05T07:45:15.0706487Z           0.0000e+00, -6.9035e-02]], device='cuda:0', dtype=torch.float64)
2023-05-05T07:45:15.0707103Z analytical:tensor([[ 5.3294e-06,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
2023-05-05T07:45:15.0707406Z           0.0000e+00,  0.0000e+00],
2023-05-05T07:45:15.0707768Z         [ 0.0000e+00, -8.7175e-03,  0.0000e+00,  ...,  0.0000e+00,
2023-05-05T07:45:15.0708023Z           0.0000e+00,  0.0000e+00],
2023-05-05T07:45:15.0708385Z         [ 0.0000e+00,  0.0000e+00,  2.1797e-02,  ...,  0.0000e+00,
2023-05-05T07:45:15.0708658Z           0.0000e+00,  0.0000e+00],
2023-05-05T07:45:15.0708876Z         ...,
2023-05-05T07:45:15.0709226Z         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -7.0372e-02,
2023-05-05T07:45:15.0709502Z           0.0000e+00,  0.0000e+00],
2023-05-05T07:45:15.0709762Z         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
2023-05-05T07:45:15.0710087Z          -4.1210e-06,  0.0000e+00],
2023-05-05T07:45:15.0710367Z         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
2023-05-05T07:45:15.0710780Z           0.0000e+00, -6.9035e-02]], device='cuda:0', dtype=torch.float64,
2023-05-05T07:45:15.0711077Z        grad_fn=<CopySlices>)
```

could you provide a forward fix or revert?

**Comment by qqaatw** [comment]
@clee2000 can you help revert? I will take a look tomorrow, thanks!

**Pull request closed without merging**
