### PR TITLE
[collect_env] Acquire windows encoding using OEMCP

### LINKED ISSUE #49010: invalid wheel no .dist-info | collect-env script not working
## To Reproduce

1. pip install torch

image

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

Result :
image

```
Collecting environment information...                                                                                   Traceback (most recent call last):                                                                                        File "collect_env.py", line 418, in <module>                                                                              main()                                                                                                                File "collect_env.py", line 413, in main                                                                                  output = get_pretty_env_info()                                                                                        File "collect_env.py", line 408, in get_pretty_env_info                                                                   return pretty_str(get_env_info())                                                                                     File "collect_env.py", line 301, in get_env_info                                                                          os=get_os(run_lambda),                                                                                                File "collect_env.py", line 208, in get_os                                                                                return get_windows_version(run_lambda)                                                                                File "collect_env.py", line 191, in get_windows_version                                                                   return run_and_read_all(run_lambda, '{} os get Caption | {} /v Caption'.format(wmic_cmd, findstr_cmd))                File "collect_env.py", line 54, in run_and_read_all                                                                       rc, out, _ = run_lambda(command)                                                                                      File "collect_env.py", line 47, in run                                                                                    output = raw_output.decode(enc)                                                                                       File "D:\DATA\python\lib\encodings\cp1252.py", line 15, in decode                                                         return codecs.charmap_decode(input,errors,decoding_table)                                                           UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 35: character maps to <undefined> 
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

### PR DESCRIPTION
**Pull request by peterjc123**
Fixes https://github.com/pytorch/pytorch/issues/49010.

### CODE REVIEW

**Review by Escartem — APPROVED** [review]

**Review by janeyx99 — APPROVED** [review]
Looks good!

**Review by walterddr — APPROVED** [review]

**Comment by peterjc123** [comment]
It can be simpilied to the oem codec.

**Review by Escartem — APPROVED** [review]

**Comment by janeyx99** [comment]
I tested on a CircleCI Windows instance and it returned what I would expect, so simplification looks good.
```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows Server 2019 Datacenter
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by peterjc123** [comment]
@malfet @janeyx99 Any difficulty landing this PR?

**Comment by janeyx99** [comment]
Ah, the landing failed from yesterday because of potential merge issues--rebasing and relanding right now.

**Pull request closed without merging**
