### PR TITLE
`docstring_linter` finds long classes and functions without docstrings

### PR DESCRIPTION
**Pull request by rec**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #142314
* __->__ #140426

### CODE REVIEW

**Comment by rec** [comment]
As an example, here are the results of running this linter on `torch/_inductor/**.py` using the default values of `--max-class=100 --max-def=80` (In other words, classes of over 100 lines, or function definitions of over 80 lines).

**Please note** that "protected" functions and classes whose names start with `_` are not reported on by default.  Using `--lint-protected` flag reports on these as well.

Perhaps the default would be better inverted because it's not clear that a "protected" thing is any less deserving than an unprotected one. 🙂 

```
torch/_inductor/async_compile.py:144: No docstring found for class 'AsyncCompile' (190 lines)

  142 |
  143 |
  144 | class AsyncCompile:
          ^
  145 |     def __init__(self) -> None:
  146 |         pass

torch/_inductor/autotune_process.py:618: No docstring found for class 'TritonBenchmarkRequest' (116 lines)

  616 |
  617 |
  618 | class TritonBenchmarkRequest(BenchmarkRequest):
          ^
  619 |     # Important: Instances of this class have to be serializable
  620 |     # across process boundaries. Do not put CUDA Tensors in here!

torch/_inductor/autotune_process.py:644: No docstring found for function 'make_run_fn' (82 lines)

  642 |         self.workspace_arg = workspace_arg
  643 |
  644 |     def make_run_fn(
              ^
  645 |         self, *input_tensors: torch.Tensor, output_tensor: torch.Tensor
  646 |     ) -> Callable[[], None]:

torch/_inductor/autotune_process.py:745: No docstring found for class 'CUDABenchmarkRequest' (113 lines)

  743 |
  744 |
  745 | class CUDABenchmarkRequest(GPUDeviceBenchmarkMixin, BenchmarkRequest):
          ^
  746 |     # Important: Instances of this class have to be serializable
  747 |     # across process boundaries. Do not put CUDA Tensors in here!

torch/_inductor/codecache.py:1846: No docstring found for class 'AotCodeCompiler' (393 lines)

 1844 |
 1845 |
 1846 | class AotCodeCompiler:
          ^
 1847 |     @classmethod
 1848 |     def compile(

torch/_inductor/codecache.py:2362: No docstring found for class 'CppCodeCache' (119 lines)

 2360 |
 2361 | @clear_on_fresh_inductor_cache
 2362 | class CppCodeCache:
          ^
 2363 |     cache: Dict[str, Callable[[], Union[CDLL, ModuleType]]] = {}
 2364 |     cache_clear = staticmethod(cache.clear)

torch/_inductor/codecache.py:2507: No docstring found for class 'CppPythonBindingsCodeCache' (174 lines)

 2505 | # Customized Python binding for cpp kernels
 2506 | @clear_on_fresh_inductor_cache
 2507 | class CppPythonBindingsCodeCache(CppCodeCache):
          ^
 2508 |     cache: Dict[str, Callable[[], Union[CDLL, ModuleType]]] = {}
 2509 |     cache_clear = staticmethod(cache.clear)

torch/_inductor/codecache.py:2746: No docstring found for class 'HalideCodeCache' (349 lines)

 2744 |
 2745 | @clear_on_fresh_inductor_cache
 2746 | class HalideCodeCache(CppPythonBindingsCodeCache):
          ^
 2747 |     cache: Dict[str, Callable[[], Union[ModuleType, CDLL]]] = {}
 2748 |     cache_clear = staticmethod(cache.clear)

torch/_inductor/comm_lowering.py:171: No docstring found for function 'register_comm_lowerings' (179 lines)

  169 |
  170 |
  171 | def register_comm_lowerings():
          ^
  172 |     try:
  173 |         torch.ops._c10d_functional.all_reduce

torch/_inductor/comms.py:537: No docstring found for function 'reinplace_fsdp_all_gather' (110 lines)

  535 |
  536 |
  537 | def reinplace_fsdp_all_gather(graph: torch.fx.Graph) -> None:
          ^
  538 |     try:
  539 |         import torch.distributed._composable.fsdp._fsdp_collectives

torch/_inductor/comms.py:659: No docstring found for function 'enforce_comm_ordering_for_fsdp' (168 lines)

  657 |
  658 |
  659 | def enforce_comm_ordering_for_fsdp(
          ^
  660 |     snodes: List[torch._inductor.scheduler.BaseSchedulerNode],
  661 |     name_to_buf: Dict[str, torch._inductor.scheduler.SchedulerBuffer],

torch/_inductor/compile_fx.py:795: No docstring found for function 'fx_codegen_and_compile' (237 lines)

  793 |
  794 |
  795 | def fx_codegen_and_compile(
          ^
  796 |     gm: GraphModule,
  797 |     example_inputs: Sequence[InputType],

torch/_inductor/compile_fx.py:1293: No docstring found for function 'fw_compiler_freezing' (96 lines)

 1291 |
 1292 |
 1293 | def fw_compiler_freezing(
          ^
 1294 |     aot_autograd_model: GraphModule,
 1295 |     aot_example_inputs: Sequence[InputType],

torch/_inductor/compile_fx.py:1441: No docstring found for function 'compile_fx' (301 lines)

 1439 |
 1440 |
 1441 | def compile_fx(
          ^
 1442 |     model_: GraphModule,
 1443 |     example_inputs_: Sequence[InputType],

torch/_inductor/config.py:803: No docstring found for class 'cpp' (104 lines)

  801 |
  802 | # config specific to codegen/cpp.py
  803 | class cpp:
          ^
  804 |     # set to torch.get_num_threads()
  805 |     threads = -1

torch/_inductor/config.py:909: No docstring found for class 'triton' (142 lines)

  907 |
  908 | # config specific to codegen/triton.py
  909 | class triton:
          ^
  910 |     # Use cudagraphs on output code
  911 |     cudagraphs = os.environ.get("TORCHINDUCTOR_CUDAGRAPHS") == "1"

torch/_inductor/constant_folding.py:63: No docstring found for class 'ConstantFolder' (209 lines)

   61 |
   62 |
   63 | class ConstantFolder(torch.fx.Interpreter):
          ^
   64 |     def __init__(
   65 |         self,

torch/_inductor/constant_folding.py:166: No docstring found for function 'run_node' (85 lines)

  164 |         return last_non_output_use
  165 |
  166 |     def run_node(self, node: torch.fx.Node) -> Any:
              ^
  167 |         if node.target == "output":
  168 |             # because we remove nodes from env on last non output use,

torch/_inductor/cpu_vec_isa.py:34: No docstring found for class 'VecISA' (120 lines)

   32 |
   33 |
   34 | class VecISA:
          ^
   35 |     _bit_width: int
   36 |     _macro: List[str]

torch/_inductor/debug.py:307: No docstring found for class 'DebugContext' (155 lines)

  305 |
  306 |
  307 | class DebugContext:
          ^
  308 |     _counter = itertools.count()
  309 |

torch/_inductor/debug.py:463: No docstring found for class 'DebugFormatter' (173 lines)

  461 |
  462 |
  463 | class DebugFormatter:
          ^
  464 |     def __init__(self, handler: DebugContext) -> None:
  465 |         self.fopen = handler.fopen

torch/_inductor/debug.py:546: No docstring found for function 'log_autotuning_results' (83 lines)

  544 |         shutil.copy(filename, self.filename("output_code.py"))
  545 |
  546 |     def log_autotuning_results(
              ^
  547 |         self,
  548 |         name: str,

torch/_inductor/dependencies.py:75: No docstring found for class 'MemoryDep' (211 lines)

   73 |
   74 | @dataclasses.dataclass(frozen=True)
   75 | class MemoryDep(Dep):
          ^
   76 |     name: str
   77 |     index: sympy.Expr

torch/_inductor/fx_utils.py:87: No docstring found for function 'incremental_update' (101 lines)

   85 |         return (node, node.target, id(node.args), id(node.kwargs))
   86 |
   87 |     def incremental_update(self):
              ^
   88 |         processed = set()
   89 |         existing_storages: DefaultDict[Optional[int], int] = defaultdict(int)

torch/_inductor/graph.py:278: No docstring found for class 'GraphLowering' (1815 lines)

  276 |
  277 |
  278 | class GraphLowering(torch.fx.Interpreter):
          ^
  279 |     graph_outputs: List[ir.IRNode]
  280 |

torch/_inductor/graph.py:1385: No docstring found for function 'run_node' (370 lines)

 1383 |             maybe_propagate(schema_arg, old_arg, new_arg)
 1384 |
 1385 |     def run_node(self, n: torch.fx.Node) -> object:
              ^
 1386 |         def debug(msg: str) -> None:
 1387 |             log.debug("lowering %s %s", LazyString(n.format_node), msg)

torch/_inductor/ir.py:359: No docstring found for class 'IRNode' (243 lines)

  357 |
  358 |
  359 | class IRNode:
          ^
  360 |     _current_origins: ClassVar[OrderedSet[Any]] = OrderedSet()
  361 |

torch/_inductor/ir.py:673: No docstring found for class 'Loops' (127 lines)

  671 |
  672 | @ir_dataclass
  673 | class Loops(IRNode):
          ^
  674 |     device: torch.device
  675 |     dtype: torch.dtype

torch/_inductor/ir.py:964: No docstring found for class 'Reduction' (753 lines)

  962 |
  963 | @ir_dataclass
  964 | class Reduction(Loops):
          ^
  965 |     reduction_ranges: Sequence[_IntLike]
  966 |     reduction_type: str

torch/_inductor/ir.py:1031: No docstring found for function 'num_splits' (219 lines)

 1029 |
 1030 |     @staticmethod
 1031 |     def num_splits(
              ^
 1032 |         device: torch.device,
 1033 |         dst_dtype: torch.dtype,

torch/_inductor/ir.py:1310: No docstring found for function 'create' (135 lines)

 1308 |
 1309 |     @classmethod
 1310 |     def create(
              ^
 1311 |         cls,
 1312 |         device: torch.device,

torch/_inductor/ir.py:1718: No docstring found for class 'WelfordReduction' (271 lines)

 1716 |
 1717 |
 1718 | class WelfordReduction(Reduction):
          ^
 1719 |     output_index: int
 1720 |

torch/_inductor/ir.py:1771: No docstring found for function 'create' (109 lines)

 1769 |
 1770 |     @classmethod
 1771 |     def create(  # type: ignore[override]
              ^
 1772 |         cls,
 1773 |         device: torch.device,

torch/_inductor/ir.py:1991: No docstring found for class 'Scan' (191 lines)

 1989 |
 1990 | @ir_dataclass
 1991 | class Scan(Loops):
          ^
 1992 |     scan_ranges: List[Integer]
 1993 |     size: List[Integer]

torch/_inductor/ir.py:2059: No docstring found for function 'create' (81 lines)

 2057 |
 2058 |     @classmethod
 2059 |     def create(  # type: ignore[override]
              ^
 2060 |         cls,
 2061 |         device: torch.device,

torch/_inductor/ir.py:2189: No docstring found for class 'Sort' (144 lines)

 2187 |
 2188 | @ir_dataclass
 2189 | class Sort(Loops):
          ^
 2190 |     # Sorts a tuple of key, value pairs
 2191 |     sort_ranges: List[Integer]

torch/_inductor/ir.py:2729: No docstring found for class 'View' (146 lines)

 2727 |
 2728 | @ir_dataclass
 2729 | class View(GenericView):
          ^
 2730 |     @staticmethod
 2731 |     def handle_negative_index(idx, size):  # type: ignore[no-untyped-def]

torch/_inductor/ir.py:3156: No docstring found for class 'Layout' (200 lines)

 3154 |
 3155 | @ir_dataclass
 3156 | class Layout(OutputSpec):
          ^
 3157 |     def __init__(
 3158 |         self,

torch/_inductor/ir.py:3692: No docstring found for class 'Buffer' (118 lines)

 3690 |
 3691 | @ir_dataclass(frozen=False)
 3692 | class Buffer(IRNode):
          ^
 3693 |     # Name is sometimes None; e.g., ForceInPlace, where there isn't
 3694 |     # a meaningful name

torch/_inductor/ir.py:3884: No docstring found for class 'ComputedBuffer' (327 lines)

 3882 |
 3883 | @ir_dataclass(frozen=False)
 3884 | class ComputedBuffer(OperationBuffer):
          ^
 3885 |     data: Loops
 3886 |

torch/_inductor/ir.py:4541: No docstring found for function 'create' (89 lines)

 4539 |
 4540 |     @classmethod
 4541 |     def create(cls, inputs, dim):  # type: ignore[no-untyped-def]
              ^
 4542 |         device = inputs[0].get_device()
 4543 |         dtype = inputs[0].get_dtype()

torch/_inductor/ir.py:4700: No docstring found for class 'ExternKernel' (727 lines)

 4698 |
 4699 | @ir_dataclass(frozen=False)
 4700 | class ExternKernel(InputsKernel):
          ^
 4701 |     constant_args: Tuple[Any, ...] = ()
 4702 |     kwargs: Dict[str, Any] = dataclasses.field(default_factory=dict)

torch/_inductor/ir.py:4865: No docstring found for function 'process_kernel' (87 lines)

 4863 |
 4864 |     @classmethod
 4865 |     def process_kernel(  # type: ignore[no-untyped-def]
              ^
 4866 |         cls, kernel, *args, **kwargs
 4867 |     ) -> Tuple[

torch/_inductor/ir.py:5073: No docstring found for function 'require_strides' (118 lines)

 5071 |
 5072 |     @classmethod
 5073 |     def require_strides(  # type: ignore[no-untyped-def]
              ^
 5074 |         cls,
 5075 |         x,

torch/_inductor/ir.py:5642: No docstring found for class 'UserDefinedTritonKernel' (178 lines)

 5640 |
 5641 |
 5642 | class UserDefinedTritonKernel(ExternKernel):
          ^
 5643 |     def get_kernel_and_metadata(self):  # type: ignore[no-untyped-def]
 5644 |         from triton.runtime.autotuner import Autotuner

torch/_inductor/ir.py:6220: No docstring found for class 'FallbackKernel' (472 lines)

 6218 |
 6219 |
 6220 | class FallbackKernel(ExternKernelAlloc):
          ^
 6221 |     def __init__(  # type: ignore[no-untyped-def]
 6222 |         self,

torch/_inductor/ir.py:7130: No docstring found for class 'Conditional' (119 lines)

 7128 |
 7129 | @ir_dataclass(frozen=False)
 7130 | class Conditional(ExternKernel):
          ^
 7131 |     predicate: Optional[IRNode] = None
 7132 |     operands: Optional[List[TensorBox]] = None

torch/_inductor/ir.py:7251: No docstring found for class 'WhileLoop' (125 lines)

 7249 |
 7250 | @ir_dataclass(frozen=False)
 7251 | class WhileLoop(ExternKernel):
          ^
 7252 |     carried_inputs: Optional[List[TensorBox]] = None
 7253 |     additional_inputs: Optional[List[TensorBox]] = None

torch/_inductor/ir.py:7281: No docstring found for function 'create' (85 lines)

 7279 |
 7280 |     @classmethod
 7281 |     def create(  # type: ignore[no-untyped-def]
              ^
 7282 |         cls,
 7283 |         cond_fn: Subgraph,

torch/_inductor/jagged_lowerings.py:112: No docstring found for function 'register_jagged_ops' (156 lines)

  110 |
  111 |
  112 | def register_jagged_ops():
          ^
  113 |     # pyre-ignore[56]
  114 |     @register_lowering(torch.ops.aten._jagged_to_padded_dense_forward.default)

torch/_inductor/loop_body.py:457: No docstring found for class 'CaptureIndexing' (155 lines)

  455 |             )
  456 |
  457 |         class CaptureIndexing(V.WrapperHandler):  # type: ignore[name-defined]
                  ^
  458 |             self.name = "CaptureIndexing"
  459 |

torch/_inductor/lowering.py:509: No docstring found for function 'make_pointwise' (83 lines)

  507 |
  508 |
  509 | def make_pointwise(
          ^
  510 |     fn,
  511 |     override_return_dtype=None,

torch/_inductor/lowering.py:1475: No docstring found for function 'cat' (120 lines)

 1473 |
 1474 | @register_lowering(aten.cat)
 1475 | def cat(inputs, dim=0):
          ^
 1476 |     cpu_device = inputs[0].get_device().type == "cpu"
 1477 |     if cpu_device and all(

torch/_inductor/lowering.py:2133: No docstring found for function 'searchsorted' (84 lines)

 2131 |
 2132 | @register_lowering(aten.searchsorted.Tensor, type_promotion_kind=None)
 2133 | def searchsorted(
          ^
 2134 |     sorted_sequence: TensorBox,
 2135 |     self: TensorBox,

torch/_inductor/lowering.py:3375: No docstring found for function 'index_put_impl_' (89 lines)

 3373 |
 3374 |
 3375 | def index_put_impl_(self, indices, values, accumulate, check):
          ^
 3376 |     # Dispatch to masked fill for single boolean index with single value
 3377 |     if (

torch/_inductor/lowering.py:3596: No docstring found for function 'scatter_reduce_' (111 lines)

 3594 |
 3595 | @register_lowering(aten.scatter_reduce_, type_promotion_kind=None)
 3596 | def scatter_reduce_(self, dim: int, index, src, reduce, *, include_self: bool = True):
          ^
 3597 |     assert reduce in {None, "sum", "prod", "mean", "amax", "amin"}
 3598 |     assert (

torch/_inductor/lowering.py:4106: No docstring found for function 'max_pool2d_with_indices_backward' (140 lines)

 4104 |
 4105 | @register_lowering(aten.max_pool2d_with_indices_backward, type_promotion_kind=None)
 4106 | def max_pool2d_with_indices_backward(
          ^
 4107 |     grad_output, x, kernel_size, stride, padding, dilation, ceil_mode, indices
 4108 | ):

torch/_inductor/lowering.py:4857: No docstring found for function 'avg_pool2d_backward' (153 lines)

 4855 |
 4856 | @register_lowering(aten.avg_pool2d_backward, type_promotion_kind=None)
 4857 | def avg_pool2d_backward(
          ^
 4858 |     grad_output,
 4859 |     x,

torch/_inductor/lowering.py:5026: No docstring found for function 'avg_pool3d_backward' (185 lines)

 5024 |
 5025 | @register_lowering(aten.avg_pool3d_backward, type_promotion_kind=None)
 5026 | def avg_pool3d_backward(
          ^
 5027 |     grad_output,
 5028 |     x,

torch/_inductor/lowering.py:5125: No docstring found for function 'fn' (86 lines)

 5123 |         return divide_factor
 5124 |
 5125 |     def fn(idx):
              ^
 5126 |         *prefix, d, h, w = idx
 5127 |         d, h, w = (v + pad for v, pad in zip([d, h, w], padding))

torch/_inductor/mkldnn_ir.py:540: No docstring found for class 'QConvPointWisePT2E' (102 lines)

  538 |
  539 |
  540 | class QConvPointWisePT2E(ExternKernelAlloc):
          ^
  541 |     def __init__(
  542 |         self,

torch/_inductor/mkldnn_ir.py:643: No docstring found for class 'QConvPointWiseBinaryPT2E' (123 lines)

  641 |
  642 |
  643 | class QConvPointWiseBinaryPT2E(ExternKernelAlloc):
          ^
  644 |     def __init__(
  645 |         self,

torch/_inductor/mkldnn_ir.py:1000: No docstring found for class 'QLinearPointwiseBinaryPT2E' (117 lines)

  998 |
  999 |
 1000 | class QLinearPointwiseBinaryPT2E(ExternKernelAlloc):
          ^
 1001 |     def __init__(
 1002 |         self,

torch/_inductor/mkldnn_ir.py:1118: No docstring found for class 'MkldnnRnnLayer' (113 lines)

 1116 |
 1117 |
 1118 | class MkldnnRnnLayer(ExternKernelAlloc):
          ^
 1119 |     def __init__(
 1120 |         self,

torch/_inductor/mkldnn_lowerings.py:32: No docstring found for function 'register_onednn_fusion_ops' (1078 lines)

   30 |
   31 |
   32 | def register_onednn_fusion_ops():
          ^
   33 |     if torch._C._has_mkldnn:
   34 |         from . import mkldnn_ir

torch/_inductor/mkldnn_lowerings.py:495: No docstring found for function 'qlinear_unary' (234 lines)

  493 |
  494 |         @register_lowering(torch.ops.onednn.qlinear_pointwise, type_promotion_kind=None)
  495 |         def qlinear_unary(
                  ^
  496 |             x: TensorBox,
  497 |             x_scale,

torch/_inductor/mkldnn_lowerings.py:575: No docstring found for function 'epilogue_creator' (115 lines)

  573 |                     )
  574 |
  575 |                     def epilogue_creator(input_buffer):
                              ^
  576 |                         # Epilogue to convert from s32 to f32 for u8s8f32
  577 |                         assert output_dtype in [

torch/_inductor/mkldnn_lowerings.py:751: No docstring found for function 'qlinear_binary' (276 lines)

  749 |             torch.ops.onednn.qlinear_pointwise.binary_tensor, type_promotion_kind=None
  750 |         )
  751 |         def qlinear_binary(
                  ^
  752 |             x: TensorBox,
  753 |             x_scale,

torch/_inductor/mkldnn_lowerings.py:855: No docstring found for function 'epilogue_creator' (132 lines)

  853 |                     )
  854 |
  855 |                     def epilogue_creator(input_buffer):
                              ^
  856 |                         # Epilogue to convert from s32 to f32 for u8s8f32
  857 |                         assert output_dtype in [

torch/_inductor/mock_cache.py:165: No docstring found for class 'PatchCaches' (108 lines)

  163 |
  164 |
  165 | class PatchCaches(contextlib.AbstractContextManager):
          ^
  166 |     @classmethod
  167 |     def setUp(cls):

torch/_inductor/pattern_matcher.py:1050: No docstring found for class 'ReplacementPatternEntry' (163 lines)

 1048 |
 1049 | @dataclasses.dataclass
 1050 | class ReplacementPatternEntry(PatternEntry):
          ^
 1051 |     normalize_args: Callable[..., List[Any]]
 1052 |

torch/_inductor/pattern_matcher.py:1054: No docstring found for function 'replace_with_graph' (144 lines)

 1052 |
 1053 |     @staticmethod
 1054 |     def replace_with_graph(
              ^
 1055 |         match: Match,
 1056 |         graph: torch.fx.Graph,

torch/_inductor/scheduler.py:166: No docstring found for class 'BaseSchedulerNode' (574 lines)

  164 |
  165 |
  166 | class BaseSchedulerNode:
          ^
  167 |     group: Tuple[torch.device, Tuple[Tuple[sympy.Expr, ...], ...]]
  168 |     read_writes: dependencies.ReadWrites

torch/_inductor/scheduler.py:863: No docstring found for class 'SchedulerNode' (223 lines)

  861 |
  862 |
  863 | class SchedulerNode(BaseSchedulerNode):
          ^
  864 |     _sizes: Tuple[Sequence[sympy.Expr], ...]
  865 |     _body: LoopBody

torch/_inductor/scheduler.py:1774: No docstring found for class 'Scheduler' (1877 lines)

 1772 |
 1773 |
 1774 | class Scheduler:
          ^
 1775 |     __dep_size_hint_cache: Dict[Dep, int]
 1776 |

torch/_inductor/scheduler.py:3652: No docstring found for class 'BaseScheduling' (104 lines)

 3650 |
 3651 |
 3652 | class BaseScheduling:
          ^
 3653 |     @classmethod
 3654 |     def get_backend_features(cls, device: torch.device) -> Sequence[BackendFeature]:

torch/_inductor/select_algorithm.py:180: No docstring found for class 'TritonTemplateKernel' (483 lines)

  178 |
  179 |
  180 | class TritonTemplateKernel(TritonKernel):
          ^
  181 |     def __init__(
  182 |         self,

torch/_inductor/select_algorithm.py:676: No docstring found for class 'TritonTemplate' (199 lines)

  674 |
  675 |
  676 | class TritonTemplate(KernelTemplate):
          ^
  677 |     index_counter = itertools.count()
  678 |     all_templates: Dict[str, "TritonTemplate"] = {}

torch/_inductor/select_algorithm.py:1247: No docstring found for class 'AlgorithmSelectorCache' (565 lines)

 1245 |
 1246 |
 1247 | class AlgorithmSelectorCache(PersistentCache):
          ^
 1248 |     def __init__(self, *args, **kwargs) -> None:
 1249 |         super().__init__(*args, **kwargs)

torch/_inductor/select_algorithm.py:1319: No docstring found for function 'precompile' (96 lines)

 1317 |         inputs_key = create_inputs_key(input_nodes)
 1318 |
 1319 |         def precompile(choices) -> Callable[[], None]:
                  ^
 1320 |             def no_op(*args, **kwargs):
 1321 |                 return

torch/_inductor/select_algorithm.py:1506: No docstring found for function 'make_benchmark_fn' (139 lines)

 1504 |
 1505 |     @classmethod
 1506 |     def make_benchmark_fn(
              ^
 1507 |         cls,
 1508 |         choices,

torch/_inductor/select_algorithm.py:1653: No docstring found for function 'log_results' (82 lines)

 1651 |
 1652 |     @staticmethod
 1653 |     def log_results(
              ^
 1654 |         name: str,
 1655 |         input_nodes: List[ir.IRNode],

torch/_inductor/sizevars.py:67: No docstring found for class 'SizeVarAllocator' (772 lines)

   65 | # lifting and in some cases we should be directly passing through to ShapeEnv,
   66 | # but there is some extra inductor logic that needs to be handled here
   67 | class SizeVarAllocator:
          ^
   68 |     def __init__(self, shape_env=None) -> None:
   69 |         super().__init__()

torch/_inductor/utils.py:905: No docstring found for class 'IndentedBuffer' (128 lines)

  903 |
  904 |
  905 | class IndentedBuffer:
          ^
  906 |     tabwidth = 4
  907 |

torch/_inductor/wrapper_benchmark.py:156: No docstring found for function 'parse_profile_event_list' (107 lines)

  154 |
  155 |
  156 | def parse_profile_event_list(
          ^
  157 |     benchmark_name, event_list, wall_time_ms, nruns, device_name
  158 | ):
```

**Review by eellison — APPROVED** [review]
Nice ! What line length were you thinking for inductor ? for classes, and methods/functions ?

**Comment by rec** [comment]
Thanks for the approval, @eellison !

Current, it's 100 lines max for undocumented classes, 80 for function definitions. I informally looked at existing code and asked "must document or not"?

Here are the longest undocumented classes or functions in `_inductor`, taken out of the above report (85 violations): 

```
1877, 1815, 1078, 772, 753, 727, 574, 565, 
483, 472, 393, 370, 349, 327, 301, 276, 271, 243, 237, 234, 223, 219, 211, 209, 200, 
199, 191, 190, 185, 179, 178, 174, 173, 168, 163, 156, 155, 155, 153, 
146, 144, 144, 142, 140, 139, 135, 132, 128, 127, 125, 123, 120, 120, 
119, 119, 118, 118, 117, 116, 115, 113, 113, 111, 110, 109, 108, 107, 104, 104, 102, 101, 
96, 96, 89, 89, 87, 86, 85, 85, 84, 83, 83, 82, 82, 81
```

So how to turn on this checking in a useful way with so many existing violations? 

We could keep a report of existing violations and only flag new ones, and try to bring down the existing violations one at a time. 

But more programming is needed, more mechanism!

----

Simpler is to commit this pull request, turned on for `_inductor`, with a top limit of 1877 (as a flag in the .lintrunner file, not in the code), so everything passes.

Then, one at a time, we document the top classes and functions, and then drop the upper limit. 

Yes, some smaller new undocumented items will sneak in while the levels drop.

----

To that end, I'm going to change the report slightly so that at the end, it lists the top three largest undocumented functions and classes.

**Comment by rec** [comment]
@oytorchbot merge

**Comment by rec** [comment]
Done. It now emits this report at the bottom:

```
Top 3 undocumented classs:
    1894 lines: torch/_inductor/scheduler.py:Scheduler
    1800 lines: torch/_inductor/graph.py:GraphLowering
    772 lines: torch/_inductor/sizevars.py:SizeVarAllocator

Top 3 undocumented functions:
    1078 lines: torch/_inductor/mkldnn_lowerings.py:register_onednn_fusion_ops
    370 lines: torch/_inductor/graph.py:run_node
    301 lines: torch/_inductor/compile_fx.py:fx_codegen_and_compile
```

**Pull request closed without merging**
