### PR TITLE
[Optim][BE] Change str(device) to _get_device_type(device)

### PR DESCRIPTION
**Pull request by qqaatw**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #129984
* #129552

Prevent using vague expressions like `"cuda" in str(device)`

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
yes yes, good change. could you verify that the same tests are run for the file still? Could be done by running one test case that runs on all devices

**Comment by qqaatw** [comment]
> yes yes, good change. could you verify that the same tests are run for the file still? Could be done by running one test case that runs on all devices

yes it works. tested with `test_param_groups_weight_decay`.

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
