### PR TITLE
Monkey patch Variable module to fix FX codegen

### LINKED ISSUE #82: Debug issue with tacotron2
tacotron2 was recently added to torchbench with get_module() support, and it seems it does not work properly.

@anijain2305 reported an error running
```
python torchbench.py --devices=cuda --only=tacotron2
```

I haven't had a chance to look into this one yet, but creating an issue so that it does not get lost.  Feel free to add more details @anijain2305.

### PR DESCRIPTION
**Pull request by anijain2305**
Fixes https://github.com/facebookresearch/torchdynamo/issues/82

There is a `torch.auotgrad.variable` function which conflicts with the module class `torch.autograd.variable.Variable`.

@jansel

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by jansel** [comment]
To expand on the issue for readers:

FX generates a call by roughly doing `f"{fn.__module__}.{fn.__name__}(...)`

Which yields `torch.autograd.variable.Variable(...)` in the output of an FX graph.

Unfortunately the module name `torch.autograd.variable` is shadowed by [this deprecated function](https://github.com/pytorch/pytorch/blob/87e556c91616df87cafc56d0eac29775f1a410bf/torch/autograd/__init__.py#L298), causing the issue https://github.com/facebookresearch/torchdynamo/issues/82

**Review by albanD — COMMENTED** [review]
The CI failure is real!

It is not ok to have `torch.autograd.variable.Variable` have `torch.autograd` as its module per our public API definition: https://github.com/pytorch/pytorch/wiki/Public-API-definition-and-documentation

I think it would be ok to have the `autograd.variable()` function raise an error for 1.12 and then we will be able to remove it in 1.13

**Comment by jansel** [comment]
> The CI failure is real!
> 
> It is not ok to have `torch.autograd.variable.Variable` have `torch.autograd` as its module per our public API definition: https://github.com/pytorch/pytorch/wiki/Public-API-definition-and-documentation
> 
> I think it would be ok to have the `autograd.variable()` function raise an error for 1.12 and then we will be able to remove it in 1.13

@albanD what do you think about this alternate fix:
```
variable.Variable = Variable
```

That would allow `torch.autograd.variable.Variable(...)` to work even though `torch.autograd.variable` doesn't point to a module.

**Comment by albanD** [comment]
You mean putting it as an attribute to the function? Ouch.
That sounds like a good immediate fix while we're in the process of deleting the variable function.

**Comment by jansel** [comment]
Yeah, it is ugly -- but it means we don't need to wait 6+ months for a deprecation cycle.

**Review by albanD — APPROVED** [review]
Could you either make the `variable()` call an error (so that we can remove it soon) or open an issue so that we don't forget to do it? Otherwise we will never be able to remove this hack.

**Comment by anijain2305** [comment]
@albanD Done! Let me know if everything looks good now.

**Review by albanD — APPROVED** [review]
Awesome! Thanks for making the change.

**Pull request closed without merging**
