### PR TITLE
Document the legacy constructor for Tensor

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #122625

Fixes https://github.com/pytorch/pytorch/issues/122408

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Sounds good once CI is fixed!

**Comment by ezyang** [comment]
It turns out it's impossible to post facto add docstring to `__init__`, so you have to make a wrapper function to attach the docstring to. Hopefully this is alright.

**Pull request closed without merging**
