### PR TITLE
Add opmath_gpu_kernel_with_scalars and port add to use it

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #64019 Convert mul to use opmath_gpu_kernel_with_scalars
* **#63884 Add acc_gpu_kernel_with_scalars and port add to use it**

See https://dev-discuss.pytorch.org/t/cuda-loops-case-study-code-generation-vs-templates/302
for explanation of what's going on here. (NB: the discuss post uses `accscalar_t` as the compute type, but we have since split it off into its own type `opmath_t`.)

Benchmark script:

```
import torch
import torch.utils.benchmark as benchmark
        
results = []
for dtype in [torch.half, torch.float]:
    for size in [1000, 1000000, 1000000000]:
        print(f'{dtype} {size}')
        results.append(
            benchmark.Timer(
                stmt='x.add(y)',
                globals={
                    'x': torch.randn(size, dtype=dtype, device='cuda'),
                    'y': torch.randn(size, dtype=dtype, device='cuda')
                },
                label='perf',
                sub_label=str(dtype),
                description=str(size),
            ).blocked_autorange(min_run_time=1)
        )

compare = benchmark.Compare(results)
compare.print()
```

Quadro GP100 Using the old gpu_kernel_with_scalars:
```
                     |  1000  |  1000000  |  1000000000
1 threads: --------------------------------------------
      torch.float16  |  8.7   |    13.3   |   10796.9  
      torch.float32  |  8.5   |    24.1   |   21651.8  
```

Quadro GP100 Using the new gpu_kernel_with_scalars (no acc):

```
                     |  1000  |  1000000  |  1000000000                                                            
1 threads: --------------------------------------------                                                            
      torch.float16  |  8.9   |    13.5   |   10794.7                                                              
      torch.float32  |  8.8   |    24.0   |   21650.5                                                                                                                                                                                 Times are in microseconds (us). 
```

Quadro GP100 Using the new acc_gpu_kernel_with_scalars:

```
                     |  1000  |  1000000  |  1000000000
1 threads: --------------------------------------------
      torch.float16  |  7.7   |    13.4   |   10795.7  
      torch.float32  |  7.8   |    23.9   |   21651.6                                                                                                                                                                 Times are in microseconds (us). 
```

V100 old code:

```
                     |  100   |  100000  |  100000000
1 threads: ------------------------------------------
      torch.int8     |  10.1  |   9.5    |     554.2 
      torch.int32    |   9.4  |   9.3    |    1411.2 
      torch.int64    |   9.4  |   9.7    |    3521.1 
      torch.float16  |   9.5  |   9.5    |     712.1 
      torch.float32  |   9.6  |   9.6    |    1410.7 
```

V100 new code:

```
                     |  100   |  100000  |  100000000
1 threads: ------------------------------------------
      torch.int8     |  10.0  |    9.6   |     554.1 
      torch.int32    |  10.1  |    9.9   |    1411.2 
      torch.int64    |  10.5  |   10.5   |    3520.9 
      torch.float16  |  10.4  |   10.2   |     712.1 
      torch.float32  |  10.1  |   10.0   |    1411.3 
```

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D30545296](https://our.internmc.facebook.com/intern/diff/D30545296)

### CODE REVIEW

**Comment by ngimel** [comment]
dynamic_casting codepath comes with what's close to catastrophic perf penalty (close to 2x). cc @zasdfgbnm

**Comment by zasdfgbnm** [comment]
Yes, vectorization is critical for Pascal and Ampere to achieve high memory bandwidth for small data types like half, bfloat16, etc.

**Comment by ezyang** [comment]
> dynamic_casting codepath comes with what's close to catastrophic perf penalty (close to 2x)

@ngimel I kind of feel like it should be possible to optimize this. We're compute bound right? It shouldn't be *that* expensive to work out the correct cast...

**Comment by ezyang** [comment]
@ngimel @zasdfgbnm I came up with an updated strategy which I think actually works without perf hit. Tomorrow I'll benchmark and make sure for certain; code here has been updated.

**Review by ngimel — APPROVED** [review]

**Comment by ezyang** [comment]
In fact, binary size goes down:

```
# BEFORE
(/scratch/ezyang/pytorch-tmp-env) ezyang@devfair040:/scratch/ezyang/pytorch-tmp$ ls -l ./build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/torch_cuda_generated_BinaryAddSubKernel.cu.o
-rw-rw-r-- 1 ezyang ezyang 1944728 Aug 30 18:57 ./build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/torch_cuda_generated_BinaryAddSubKernel.cu.o
# AFTER
(/scratch/ezyang/pytorch-tmp-env) ezyang@devfair040:/scratch/ezyang/pytorch-tmp$ ls -l ./build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/torch_cuda_generated_BinaryAddSubKernel.cu.o
-rw-rw-r-- 1 ezyang ezyang 1493312 Aug 30 19:07 ./build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/torch_cuda_generated_BinaryAddSubKernel.cu.o
```

**Pull request closed without merging**
