### PR TITLE
Expose Some FunctionsManual Api

### PR DESCRIPTION
**Pull request by Bin1024**
Fixes #ISSUE_NUMBER
Exporse some function api in FunctionsManual.h for custom devices. This can be used in codegen features

### CODE REVIEW

**Comment by soulitzer** [comment]
@Bin1024  Do you have more context about your use case and why you need this? This is exposing a lot of functions as public API which would make things difficult to change later.

**Comment by Bin1024** [comment]
> @Bin1024 Do you have more context about your use case and why you need this? This is exposing a lot of functions as public API which would make things difficult to change later.

Hi @soulitzer , in the auto-generated forward-backward bindings we need some functions like maybe_multiply. Can you tell me which ones you don't want to expose?

**Comment by soulitzer** [comment]
Thanks for the context. Is the code your are generating out of tree generated with torchgen? Why are you doing that? 

Exposing a few utility functions seems fine, but exposing all the formulas would make it more difficult for us doing changes to how we call into our formulas in general if we decide to do that.

Since these are just mathematical formulas, and mostly do not rely on any special internal APIs, they should be mostly standalone and copy-able into your own code. Would that work for your case?

**Comment by Bin1024** [comment]
@soulitzer Thanks for your advice. I made some modifications, is it feasible now.

**Review by soulitzer — CHANGES_REQUESTED** [review]
Sorry I'm going back on what said earlier even if its just utility functions. There's a lot more that we need to do to make these true public APIs, i.e. we need to fully document these.

I'd say that unless there's a really good reason for making these public (e.g. do they rely on a lot of private PyTorch APIs that would prevent these functions from being reimplementable  in user code), we should keep them private.

If users would find these types of APIs useful in general, we think about a better place to put them and document them properly, but in the near term reimplementing them should be the simplest solution for your case.

**Comment by soulitzer** [comment]
@Bin1024 I'd actually still be curious, by the way, what your use case is in more detail, e.g. what are you trying to do out of tree here and how are you planning to do it? Perhaps there are other ways that we can help your use case?

**Pull request closed without merging**
