### PR TITLE
[MPS] Handle reduction of scalars in edge-cases

### PR DESCRIPTION
**Pull request by kulinseth**
The issue was found as part of fixing Test consistency issues.
Test case coming up.

### CODE REVIEW

**Review by razarmehr — APPROVED** [review]
Looks good.

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@pytorchbot merge -f "MPS is green"

The automatic merge failed due to one of the checkruns being cancelled (probably allocation failure)

**Pull request closed without merging**
