### PR TITLE
Use maxint to bound integers.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96121

We don't actually support arbitrary precision integers.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by tugsbayasgalan — APPROVED** [review]

**Review by lezcano — APPROVED** [review]

**Review by eellison — COMMENTED** [review]
What was the issue with the previous code ?

**Comment by eellison** [comment]
Could we remove guards that check for INT_MAX instead ? it's not obvious from the code why we wouldn't be using `ValueRanges.Unknown()`

**Comment by ezyang** [comment]
Yes i plan to do this.

**Comment by ezyang** [comment]
Elias I will post the test case for this; the problem is we have some code testing for int_max

**Comment by ezyang** [comment]
@eellison test case at https://github.com/pytorch/pytorch/pull/96121/files#diff-83343b7ad365ac39feaa074a66ca509cffc0d487f694ee724294c41b5569f321R973

**Pull request closed without merging**
