### PR TITLE
[dynamo] Replace __str__ with __repr__ in some places

### PR DESCRIPTION
**Pull request by rec**
## The problem

In a typical debugger, `repr()` is used to display variables and not `str()`.

Several classes in Dynamo have a `__str__()` method that returns useful information and a  `__repr__()` that does not. Having to call `str(x)` or `[str(i) for i in x]` in the debugger all the time is a chore.

`str()` should be ["informal, nicely printable"](https://docs.python.org/3/library/stdtypes.html#str) and `repr()` should ["attempt to return a string that would yield an object with the same value when passed to eval()](https://docs.python.org/3/library/functions.html#repr)".

## The solution

In the Python object model, if there is no `__str__` method, `__repr__`  is used instead (but not the other way around).

So renaming `__str__` to `__repr__` in a few cases where no `__repr__` method exists now should not change observable behavior, and should make debugging easier.

The specific classes changed were all in `torch._dynamo.variables`:

* `builtin.BuiltinVariable`
* `constant.ConstantVariable`
* `constant.EnumVariable`
* `functions.UserMethodVariable`
* `lazy.LazyVariableTracker`
* `lazy.LazySymNodeFormatString`
* `misc.GetAttrVariable`
* `misc.NullVariable`
* `user_defined.UserDefinedObjectVariable`

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136316

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by amjames — COMMENTED** [review]
+1 for better debug info, can you show a before/after example for context?

**Comment by rec** [comment]
@amjames: I decided to simply set breakpoints at all the constructors of classes changed and then ran every test in `dynamo/test_misc.py` until I got some good examples:

| Before | After |
| ----- | ----- |
| `BuiltinVariable()` | `BuiltinVariable(getattr)` |
| `ConstantVariable()` | `ConstantVariable(str: 'nn')` |
| `UserMethodVariable()` | `UserMethodVariable(<function Sequential.__init__ at 0x7f765c5188b0>, UnspecializedNNModuleVariable(Sequential))` |
| `GetAttrVariable()` | `GetAttrVariable(SuperVariable(), __init__)` |
| `UnspecializedBuiltinNNModuleVariable(Linear)` | `UnspecializedBuiltinNNModuleVariable(Linear)` |
| `LazyVariableTracker()` | `LazyVariableTracker()` |
| `EnumVariable()` | `EnumVariable(<enum 'MyEnum'>) |

**Comment by rec** [comment]
@amjames: ideas for reviewers?

The `VariableTracker.build()` PR has already been merged!

**Review by XuehaiPan — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
