### PR TITLE
remove duplicated process group gloo timeout

### PR DESCRIPTION
**Pull request by zhaojuanmao**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#31342 remove duplicated process group gloo timeout**

Differential Revision: [D19131704](https://our.internmc.facebook.com/intern/diff/D19131704/)

### CODE REVIEW

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit afd4dd4:
* **2/2** broken upstream at merge base 409151e (see [grid view](https://dr.pytorch.org/master-timeline.html?count=1&sha1=409151e1bb90c66546901d372f59930f72242ee9&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35))
    * You may want to rebase on the `viable/strict` branch (see its [recency history](https://dr.pytorch.org/master-viable-commits.html)):
        * If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
          ```
          git fetch viable/strict
          git rebase --onto viable/strict $(git merge-base origin/master HEAD)
          ```
        * If your commit is older than `viable/strict`:
          ```
          git fetch viable/strict
          git rebase viable/strict
          ```
* **0/2** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=afd4dd40b1136a724d321bd772cc3134eb487079).

### 2 upstream failures recognized by patterns:
These builds matched patterns, but were probably caused by upstream breakages:
* [caffe2_onnx_py3_6_clang7_ubuntu16_04_test](https://dr.pytorch.org/build-details.html?build_id=75483226)
* [caffe2_onnx_py2_gcc5_ubuntu16_04_test](https://dr.pytorch.org/build-details.html?build_id=75484024)



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by pietern** [comment]
@zhaojuanmao Can you point to the other instance that this test duplicates?

**Comment by zhaojuanmao** [comment]
@pietern test_barrier_timeout_full_group, test_barrier_timeout_group and test_barrier_timeout_global in test_distributed.py are testing Gloo timeout as well, feel these tests have already covered what the test_timeout_kwarg is trying  to test. 

How do you think?

**Comment by mrshenli** [comment]
It looks like the two test cases are a little different, `test_distributed.py` only runs the test on rank 0, but `test_c10d.py` runs barrier on both.

**Comment by zhaojuanmao** [comment]
@mrshenli you are right! I think we can make test_distributed.py run barriers on all ranks as well, then these tests can be merged.  Does it sound good to you?

If not, for the flakiness of test_timeout_kwargs in test_c10d.py, I think it is possibly because the first barrier().wait() call timed out sometimes, we can remove the first barrier call that seems to be not needed.

**Comment by mrshenli** [comment]
> @mrshenli you are right! I think we can make test_distributed.py run barriers on all ranks as well, then these tests can be merged. Does it sound good to you?

Yes, that sounds good to me! Some day, we need to merge/cleanup the two test files (`test_distributed.py` and `test_c10d.py`)

**Comment by zhaojuanmao** [comment]
@mrshenli  I think we should not run barriers for all ranks in test_c10d.py. for test_timeout_kwargs, other ranks will time out, but rank = 0 could success because all ranks reach at the same point when rank = 0 runs barrier(). 

So what is done in test_barrier_timeout_global() in test_distributed.py looks better. 

How do you think?

**Review by mrshenli — APPROVED** [review]
> for test_timeout_kwargs, other ranks will time out, but rank = 0 could success because all ranks reach at the same point when rank = 0 runs barrier().

Didn't get why rank0 can succeed? All other ranks should have timed out when rank0 reached the second barrier. Or did I miss anything?

But it looks OK to me to remove this test.

**Comment by zhaojuanmao** [comment]
sorry, it is my bad. So if we ran barrier for all ranks, then for ranks!=0, they will have connection error, as rank 0 has already been timed out.

**Pull request closed without merging**
