### PR TITLE
Improve NLLLoss docs

### PR DESCRIPTION
**Pull request by daniellepintz**

### CODE REVIEW

**Comment by daniellepintz** [comment]
question for reviewers: also wondering if we plan to remove `size_average` and `reduce`, since these have been deprecated for a while?

**Review by mikaylagawarecki — APPROVED** [review]
Thanks!

**Comment by daniellepintz** [comment]
thanks for the review @mikaylagawarecki , looks like I dont have permission to merge though - do you mind doing it?

**Pull request closed without merging**
