### PR TITLE
[doc] Add pin_memory and layout to new_{zeros, ones, full}

### LINKED ISSUE #84986: torch.new_zeros doc missing layout or pin_memory fields
### 📚 The doc issue

As title. 

### Suggest a potential alternative/fix

_No response_

cc @svekars @holly1238

### PR DESCRIPTION
**Pull request by foram-chandra**
Fixes #84986

Besides adding `pin_memory` and `layout`, I have also updated the signature to reflect keyword only arguments.

### CODE REVIEW

**Comment by foram-chandra** [comment]
cc- @kshitij12345 @mruberry @SherlockNoMad

**Review by lezcano — COMMENTED** [review]
Could you add this to all the `new_*` functions? There are a couple that are still missing.

**Comment by foram-chandra** [comment]
@lezcano Thank you for the review! I have updated it. :)

**Review by lezcano — APPROVED** [review]
Thank you for these fixes and making the docs more uniform!

**Review by SherlockNoMad — APPROVED** [review]

**Pull request closed without merging**
