### PR TITLE
Add decomps for max_unpool

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #133146

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by amjames — COMMENTED** [review]
Not seeing anything to comment on, but can we see a benchmark sweep?

**Comment by isuruf** [comment]
Benchmark results with out_size being 2 times the shape

```
[------------------------- max_unpool ------------------------]
                                        |  Decomposed  |  Eager
12 threads: ---------------------------------------------------
      {'shape': (3, 5, 2000, 2000)}     |     2472     |   5334
      {'shape': (3, 5, 1000, 1000)}     |      628     |   1350
      {'shape': (3, 5, 200, 200, 200)}  |     8081     |  15360
      {'shape': (3, 5, 100, 100, 100)}  |     1024     |   1768
```

**Review by amjames — APPROVED** [review]

**Review by eellison — APPROVED** [review]

**Pull request closed without merging**
