### PR TITLE
fix test_float_to_int_conversion_nonfinite for NumPy 2

### PR DESCRIPTION
**Pull request by haifeng-jin**
Related to #107302 

We saw `test_float_to_int_conversion_nonfinite` failed as we upgrade to NumPy 2.

It is caused by the undefined behavior of `numpy` casting `inf`, `-inf` and `nan` from `np.float32` to other dtypes.
The test is using NumPy as reference for the ground truth. (see line 1013-1015)
However, these behaviors are undefined in NumPy.
If you do `np.array([float("inf")]).astype(np.uint8, casting="safe")`, it results in an error `TypeError: Cannot cast array data from dtype('float64') to dtype('uint8') according to the rule 'safe'`.
The undefined behaviors are always subject to change.

This PR address this issue by passing concrete values as the ground truth references.
In the future, even NumPy changes its behavior the test would still remain stable.

cc @mruberry @rgommers @kiukchung

### CODE REVIEW

**Comment by haifeng-jin** [comment]
Hi @albanD,
would you mind taking a look at this PR?
Or just reassign it if you are busy?

We are blocked by this to enable the NumPy 2 CI tests.
Thanks!

**Comment by drisspg** [comment]
Looks good

**Review by drisspg — APPROVED** [review]

**Comment by haifeng-jin** [comment]
@drisspg Thank you!
Is this PR ready to merge?

**Comment by haifeng-jin** [comment]
@drisspg friendly ping again : )

**Comment by haifeng-jin** [comment]
Skip macos-arm64 for the test since the torch ops return a different result than other OSs.
It seems to be a long existing issue. We did not catch it just because we did not pass the reference values for the tests.

See more details: https://github.com/pytorch/pytorch/issues/38752

**Comment by izaitsevfb** [comment]
@pytorchbot merge

apologies, this SEV should not be merge blocking

**Pull request closed without merging**
