### PR TITLE
Split out fake_impls from fake_tensor

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #118878

The motivation is fake_tensor is marked as an uninteresting file for the purposes of backtraces, but operator implementations in fake tensor are interesting and I do want them reported.

How did I decide whether or not to move helper functions or not? It was kind of random, but if they weren't used in fake tensor generally I moved them over.

There are no functional code changes, so you only need to review the import changes.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by eellison — APPROVED** [review]

**Review by eellison — COMMENTED** [review]
Why was the fake tensor file deemed uninteresting, just curious ?

**Comment by ezyang** [comment]
Sometimes we would flag in the generic wrapper code so I excluded it so that we'd keep looking for more interesting spots

**Pull request closed without merging**
