### PR TITLE
Logspace dispatch and precision fixes

### PR DESCRIPTION
**Pull request by Enealor**
This PR updates the CPU and CUDA `logspace` function as requested in #31991. The changes are:
* The CPU version has been updated to dispatch to integral types in addition to its previous types. It also has improved precision by computing intermediate results with the `double` type. The error between a pure Python version of `logspace` and the CPU implementation should be zero.
* The CUDA version has been updated to have the expected truncation behavior by removing intermediate rounding. Furthermore, the integral types are cast to `float` to avoid their auto-promotion to `double`. This is done to avoid the performance costs of using `double`. Otherwise, the precision has been left alone to avoid performance changes on GPU. (Note: the auto-promotion behavior is based on the standard behavior of `std::pow` for C++11.)
* Tests have been implemented to verify the functionality and precision with each `dtype` and `device`. As part of this, I moved the `test_logspace` function from the `_TestTorchMixin` class to the `TestTorchDeviceType` class and added the appropriate decorators. (Note to self: I had to rebase to manually address a merge conflict from this move.) Some changes had to be made for the tests to work with devices and dtypes. Only one test needed to be modified in test content, which I describe below.

The test that had to be modified is the in-place assignment to non-contiguous memory. The issue that arises is that the CUDA version of `pow` produces output that is off by just enough to have truncation issues. This can be seen in PyTorch 1.4.0 by running
```
y = torch.logspace(0, 3, 4, device='cuda', dtype=torch.float32).to(torch.int)
# output: tensor([  1,  10,  99, 999], device='cuda:0', dtype=torch.int32)
```
The expected values are `[1, 10, 100, 1000]`, which is returned in the `device='cpu'` case. To remedy the failure, I am changing the base to 2. This is an easier calculation in the floating-point case, and the purpose of the test is to verify that it works as expected for non-contiguous memory.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit accc82aa:


**None of the build failures appear to be your fault**.

* **1/1** recognized as flaky :snowflake:
    * Re-run these jobs?


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=accc82aa0828b96940042dc192594cba54524bea).

### :snowflake: 1 failure recognized as flaky
The following build failures have been detected as flaky and **may not be your fault**:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4344021) pytorch_linux_xenial_cuda10_1_cudnn7_py3_gcc7_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=91062859) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=91062859)) :snowflake:
<details>
<summary>
<code>Jan 26 17:46:20   Error generating file</code>
</summary>

```
Jan 26 17:46:20 /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/RangeFactories.cu(78): error: cannot deduce "auto" type (initializer required) 
Jan 26 17:46:20  
Jan 26 17:46:20 /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/RangeFactories.cu(78): error: expected a ";" 
Jan 26 17:46:20  
Jan 26 17:46:20 /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/RangeFactories.cu(78): error: cannot deduce "auto" type (initializer required) 
Jan 26 17:46:20  
Jan 26 17:46:20 /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/RangeFactories.cu(78): error: expected a ";" 
Jan 26 17:46:20  
Jan 26 17:46:20 10 errors detected in the compilation of "/tmp/tmpxft_00000236_00000000-6_RangeFactories.cpp1.ii". 
Jan 26 17:46:20 CMake Error at torch_cuda_generated_RangeFactories.cu.o.Release.cmake:281 (message): 
Jan 26 17:46:20   Error generating file 
Jan 26 17:46:20   /var/lib/jenkins/workspace/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/./torch_cuda_generated_RangeFactories.cu.o 
Jan 26 17:46:20  
Jan 26 17:46:20  
Jan 26 17:46:20 caffe2/CMakeFiles/torch_cuda.dir/build.make:840: recipe for target 'caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/torch_cuda_generated_RangeFactories.cu.o' failed 
Jan 26 17:46:20 make[2]: *** [caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/torch_cuda_generated_RangeFactories.cu.o] Error 1 
Jan 26 17:46:20 make[2]: *** Waiting for unfinished jobs.... 
Jan 26 17:46:22 /var/lib/jenkins/workspace/c10/util/ArrayRef.h(278): warning: attribute does not apply to any entity 
Jan 26 17:46:22  
Jan 26 17:46:22 /var/lib/jenkins/workspace/c10/util/ArrayRef.h(278): warning: attribute does not apply to any entity 
Jan 26 17:46:22  
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by Enealor** [comment]
As far as I can tell, each of the failing checks is for a different reason unrelated to my changes. The ROCM Debian check failed in `test_broadcast_coalesced_nccl`, which makes no obvious call to `logspace`. The XLA check failed to compile, but I can't discern any reference to a relevant RangeFactories file. The ONNX check failed due to a segmentation fault during `test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_slice_index_exceeds_dim`.

All of this is to say that this code is probably ready for review. Should I rebase to `viable/strict` and run the tests again?

**Comment by ngimel** [comment]
Yeas, try rebasing please, but I agree that test failures look unrelated. Thank you!

**Comment by Enealor** [comment]
Sorry. I did not expect my rebase to add a bunch of review requests. I removed them as I didn't intend for them to be added. If the requests should be there, I won't change them again.

**Pull request closed without merging**
