### PR TITLE
[vulkan] Upgrade vulkan memory allocator to 3.0.1

### PR DESCRIPTION
**Pull request by SS-JIA**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #81472

Upgrades VMA version from `3.0.0-development` to `3.0.1`.

There have been some changes in the API:

1. `VmaAllocatorCreateInfo` interface changed - we now need to provide some function pointers
2. Some `VMA_MEMORY_USAGE_*` flags have been deprecated

Differential Revision: [D37822117](https://our.internmc.facebook.com/intern/diff/D37822117/)

### CODE REVIEW

**Review by kimishpatel — COMMENTED** [review]
Is update process to vulkan memory allocator just copying the header file? Why not use third party dep via https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator?

**Comment by SS-JIA** [comment]
@kimishpatel we could, but that involves a bit more work since we'll have to set up a third party dependency in BUCK as well.

**Comment by SS-JIA** [comment]
> Would it take significant time? Can someone else do it? I am just wondering if that is more clean.

Not too much work, maybe about a week. Although I would prefer to land this diff first considering the changes in the rest of the backend code. We can kick off adding this as a third-party dependency right after this is landed.

**Comment by kimishpatel** [comment]
> > Would it take significant time? Can someone else do it? I am just wondering if that is more clean.
> 
> Not too much work, maybe about a week. Although I would prefer to land this diff first considering the changes in the rest of the backend code. We can kick off adding this as a third-party dependency right after this is landed.

Lets do a follow up not too later in the future.

**Review by kimishpatel — APPROVED** [review]

**Pull request closed without merging**
