### PR TITLE
New feature for issue #85575.

### LINKED ISSUE #85575: Introduce RECORD_OUTPUTS() macro to be used with existing RECORD_FUNCTION() for the purpose of passing an operators output tensors to the profiler
### 🚀 The feature, motivation and pitch

This is related to a previous [feature request 66105](https://github.com/pytorch/pytorch/issues/66105). I'm working on adding profiling support to [nvfuser](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/codegen/cuda/README.md), this feature allows us to track the dataflow of JIT fused operators at runtime.

The [RECORD_FUNCTION()](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/record_function.h#L564) macro is defined in the ATen lib in [record_function.h](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/record_function.h#L564).

Developers can use the macro to enable the logging of profiler events which will show up in the NVTX markers on GPU enabled systems. However, this macro only lets you capture the name, input tensors and sequence_id of the function you're calling. For the purposes of building a network graph it is also important to be able to capture the output tensors.

I would like to add a new macro that lets you record the outputs. The profiler is already configured to manage output tensors if they are recorded.

    #define RECORD_OUTPUTS(outputs) \
        if (guard.needsOutputs()) { \
            guard.setOutputs( \
                std::vector<c10::IValue>(outputs.begin(), outputs.end()));\
        }

This new macro would be used with RECORD_FUNCTION() like this.

    RECORD_FUNCTION("my_fused_kernel",
            std::vector<c10::IValue> (inputs.begin(), inputs.end()), seq_id);
    auto outputs = executor.runFusion(inputs, launch_params, input_id);
    RECORD_OUTPUTS(outputs);

This new macro uses existing profiler features and it allows users to visualize the dataflow across nodes in the network. I have already tested it locally and it works as expected.

### Alternatives

Continue to use the current profiler support in nvfuser which is not connected to the main pytorch profiler via record_function.  This leaves us without the ability to compare the fused network graph to the unfused network graph.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexmsettle**
Introduced RECORD_OUTPUTS() macro that goes with RECORD_FUNCTION(). It is used to capture the output tensors from a kernel launch.  The tensors automatically get passed to the profiler using record_function methods.  This allows the profiler to track the tensors that flow into and out of each op.

Fixes #85575

cc @robieta @chaekit @aaronenyeshi @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb

### CODE REVIEW

**Comment by alexmsettle** [comment]
@zou3519 - can someone please review my changes?

**Comment by zou3519** [comment]
cc profiler folks (I pulled the names from https://github.com/pytorch/pytorch/issues/24422): @robieta @chaekit @aaronenyeshi @ngimel @nbcsm

**Comment by alexmsettle** [comment]
@robieta , @ngimel - can someone please review my changes?

**Review by robieta — APPROVED** [review]
LGTM. Profiler doesn't currently track outputs due to the added overhead, but I'm open to the idea of adding that functionality.

**Comment by alexmsettle** [comment]
Thanks for reviewing @robieta !  I just did a rebase since the CI complained my repo was stale.

**Comment by alexmsettle** [comment]
Hey @robieta - I just synced my repo with main and got CI to pass.  Can you please try the merge again?

**Comment by alexmsettle** [comment]
Oh thanks @ngimel  !

**Pull request closed without merging**
