### PR TITLE
Add full float16/bfloat16 support to MaxUnPool

### PR DESCRIPTION
**Pull request by Skylion007**
It already supported half so might as well add bfloat16 support for parity

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by eqy — APPROVED** [review]
Should the unit test e.g., `common_methods_invocations` entry also be updated for this?

**Comment by ezyang** [comment]
yes, it's weird that it isn't complaining that the supported dtype list isn't accurate, there might be a test gap

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
