### PR TITLE
Rename Canonical Aten IR to Core Aten IR

### PR DESCRIPTION
**Pull request by SherlockNoMad**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #92904

cc @svekars @carljparker

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Shouldn't tags.yaml be updated as well?

**Comment by bdhirsh** [comment]
I tried running `git grep "canonical" tools`, and it looks like there are a few other places where we burn in the "canonical" tag?

Actually I think it's just in `tools/test/test_executorch_gen.py`

**Review by bdhirsh — APPROVED** [review]

**Comment by SherlockNoMad** [comment]
@pytorch merge

**Pull request closed without merging**
