### PR TITLE
Add NestedTensor specific dispatch key to PyTorch

### PR DESCRIPTION
**Pull request by cpuhrsch**
This adds a dedicated dispatch key for the [nestedtensor project](https://github.com/pytorch/nestedtensor).

- [x] Since this isn't a device or a backend, does this need further updates in other places other than DispatchKey.h?

### CODE REVIEW

**Review by ailzhang — COMMENTED** [review]
qq: can nestedtensor keep using PrivateUse key when it's out of tree? That might reduce the maintenance burden. 
(Btw if you want to add a specific dispatch key like this, there're a few other places need to be updated so I just want to make sure it's necessary. Thanks!

**Comment by cpuhrsch** [comment]
nestedtensor, now, is built on top of a fork of PyTorch. If I can't land it here, it'd be good for me to land it within that fork so that I can write NestedTensor-specific changes based on the dispatch key of a Tensor within that fork (e.g. for vmap). What other changes are needed so I can do this in my fork?

**Comment by ailzhang** [comment]
You can probably replicate all appearance of `PrivateUse1/2/3` for these keys in your fork. e.g
```
λ ~/dev-pytorch master ack PrivateUse2
c10/core/DispatchKeySet.h
196:  DispatchKey::AutogradPrivateUse2,

c10/core/DispatchKeySet.cpp
32:  DispatchKey::PrivateUse2,
62:    case DispatchKey::AutogradPrivateUse2:
63:      return DispatchKeySet(DispatchKey::PrivateUse2);

c10/core/DispatchKey.cpp
58:    case DispatchKey::PrivateUse2:
59:      return "PrivateUse2";
76:    case DispatchKey::AutogradPrivateUse2:
77:      return "AutogradPrivateUse2";
127:    case DispatchKey::PrivateUse2:
128:      return DispatchKey::AutogradPrivateUse2;

c10/core/DispatchKey.h
110:  PrivateUse2,
222:  AutogradPrivateUse2,
288:  PrivateUse2_PreAutograd = AutogradPrivateUse2,
```

**Review by ailzhang — APPROVED** [review]
LGTM!Thanks!

**Review by ezyang — APPROVED** [review]
I didn't check for completeness. @ailzhang may also wanna approve first here.

**Pull request closed without merging**
