### PR TITLE
fix numpy1.24 deprecations in unittests

### LINKED ISSUE #91329: Remove deprecated numpy dtype alias to be compatible with numpy1.24
### 🐛 Describe the bug

In numpy 1.24, np.object, np.bool, np.float, np.complex, np.str, and np.int no longer exists. However some of these are still used in PyTorch (though mainly in unittests), for example [these](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/pytorch/pytorch%24+np.float%5B%5E136_%5D+rev:refs/tags/v1.13.1&patternType=regexp&sm=1).

(numpy release notes: https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations )

### Versions

Using torch 1.13.1 but these usage exist in current HEAD.

cc @ezyang @malfet @rgommers @xuzhao9 @gramster @mruberry

### PR DESCRIPTION
**Pull request by ppwwyyxx**
Fixes https://github.com/pytorch/pytorch/issues/91329

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Review by jerryzh168 — APPROVED** [review]

**Comment by schneimo** [comment]
Could this pull request be merged please? Would be nice not to have to suppress warnings and to be able to update numpy to versions above 1.23.5. Thanks!

**Comment by ngimel** [comment]
@ppwwyyxx @schneimo after PR is approved, author can merge it using pytorchbot command

**Pull request closed without merging**
