### PR TITLE
[ONNX] Run ruff pyupgrade to update type annotations

### PR DESCRIPTION
**Pull request by justinchuby**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #130657

Use the newest syntax for type annotations

### CODE REVIEW

**Review by titaiwangms — APPROVED** [review]

**Comment by Skylion007** [comment]
Yeah, there is a reason I didn't upgrade the type annotations, old school torch jit really hates it...

**Comment by justinchuby** [comment]
@Skylion007 does this error

```pytb 
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/utils/_sympy/value_ranges.py", line 386, in coordinatewise_monotone_map
    return ValueRanges(min(products), max(products))
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/sympy/core/decorators.py", line 236, in _func
    return func(self, other)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/sympy/core/expr.py", line 365, in __lt__
    return StrictLessThan(self, other)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/sympy/core/relational.py", line 843, in __new__
    raise TypeError("Invalid NaN comparison")
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fx_wrapper' raised:
TypeError: Invalid NaN comparison

```

look familiar to you? It seems to be caused by the first PR in this stack, but my changes have nothing to do with inductor (just removing beartype in ONNX) so I am very confused.

**Comment by justinchuby** [comment]
Maybe they are just flaky

**Comment by justinchuby** [comment]
This change also does touch any paths jit would see. So it should be fine?

**Comment by justinchuby** [comment]
Likely caused by https://github.com/pytorch/pytorch/pull/130139#issuecomment-2229248447

**Pull request closed without merging**
