### PR TITLE
Remove duplicated AVX512 detection

### PR DESCRIPTION
**Pull request by xuhdev**
`FindAVX.cmake` has already handled these. No need to duplicate the
detection.

Additionally, `/arch:AVX512` is no longer a hidden MSVC option: https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=msvc-160
Following up #61748

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Thank you for the change!
But the failures seems to be relevant, @xuhdev can you please look at them and fix before I can land the change?

**Comment by xuhdev** [comment]
@malfet Sorry for the late response, I was on intermittent vacations.

The failed tests don't seem to be relevant -- in fact, the [full log file](https://circleci.com/api/v1.1/project/github/pytorch/pytorch/15682031/output/106/0?file=true&allocation-id=61288d8262dd7a1afce07d06-0-build%2F18002CF1) shows that the build does not enable AVX512.

Another difficulty in looking into the error is that they seem mostly skipped in other PRs and not run on the master test -- do you have any idea to let it run once on the master branch?

I've rebased once and I'll give you another update once all tests have finished.

**Comment by xuhdev** [comment]
Do you have any idea on how to trigger `linux-xenial-py3.6-gcc5.4` or `linux-xenial-cuda11.3-py3.6-gcc7` on master? they were skipped on master and I checked out a couple of other PRs, they were also skipped.

**Comment by xuhdev** [comment]
@malfet Any chance to look into this :)

**Comment by malfet** [comment]
@xuhdev can you please rebase and add 'ciflow/all' label ( actually let me add the label myself)

**Pull request closed without merging**
