### PR TITLE
Disable some check to get the test pass

### LINKED ISSUE #100340: DISABLED test_equal (__main__.TestTorch)
Platforms: linux

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_torch.py%3A%3ATestTorch%3A%3Atest_equal)).

The cause seems to point to https://github.com/pytorch/pytorch/pull/100024 (or D45282119 as it was landed internally)

cc @mruberry @houseroad @ezyang

### PR DESCRIPTION
**Pull request by houseroad**
Differential Revision: D45437730

Fixes https://github.com/pytorch/pytorch/issues/100340

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!

**Comment by houseroad** [comment]
The test passed: https://github.com/pytorch/pytorch/actions/runs/4852873850/jobs/8648800149?pr=100364

**Review by eellison — COMMENTED** [review]
Can you add a skipifTorchInductor instead ?

**Comment by houseroad** [comment]
@eellison  your comment is addressed in https://github.com/pytorch/pytorch/pull/100435

**Pull request merged**
