### PR TITLE
[opinfo] item

### PR DESCRIPTION
**Pull request by khushi-411**
Follows #100223

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by khushi-411** [comment]
Hi, @justinchuby, @kshitij12345, @lezcano, @ngimel !
Could you please review the PR? Thanks for considering my request.

**Comment by justinchuby** [comment]
Thanks for creating this! I don't have permission to approve so I will leave it to other folks to take a look at.

**Review by ezyang — APPROVED** [review]

**Comment by khushi-411** [comment]
CI is green now. I'm merging the PR. Thanks, @ezyang and @justinchuby :)

@pytorchbot merge

**Pull request closed without merging**
