### PR TITLE
Refactor test_torchinductor_strided_blocks to also support triton CPU

### PR DESCRIPTION
**Pull request by kundaMwiza**
This increases test coverage for triton CPU from just test_torchinductor.py to also testing block pointer lowering. 

Fixes #ISSUE_NUMBER

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by jansel — DISMISSED** [review]

**Comment by kundaMwiza** [comment]
Looks like its due to the addition of a new test case in https://github.com/pytorch/pytorch/commit/5aacfa037b9cb8dcb81c75e6964e2e0425023eb8

**Review by jansel — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by kundaMwiza** [comment]
@jansel I think you'll have to merge?

**Comment by eellison** [comment]
@kundaMwiza are you still using the inductor cpu backend ? It was added a while ago, no one is actively working on it, and it hogs up CI resources / occasionally flakes. If you're not using it might delete it, or at least skip the tests.

**Comment by kundaMwiza** [comment]
@eellison We do use triton cpu, in some cases to validate results when a cuda device is not available. Currently we reuse a lot of the triton lowering path in inductor, for example block ptrs / tensor descriptors, so if triton cpu is removed I worry that we'll have to patch a lot of the code. Perhaps the solution to this is for us to look at changing call sites that query the inductor backend to be more agnostic so we can automatically opt into paths for triton by simply registering
our backend as triton capable. I do understand though that the triton cpu pin hasn't been updated in pytorch for a long time - there is some progress for triton cpu though https://github.com/triton-lang/triton-cpu (recently improved support for tensor descriptors), so perhaps if there is interest in updating the hash and opening issues on the triton cpu repo could be done? However I'm not sure what the plan is for triton cpu itself (e.g. if they'll be receptive to bug reports), minjang suggested its used internally in meta https://github.com/triton-lang/triton-cpu/issues/243#issuecomment-3275760397 last year but I guess not through pytorch?

**Comment by desertfire** [comment]
cc @minjang

**Comment by minjang** [comment]
@eellison meta internally uses triton-cpu, and I recently added some support in the inductor for triton cpu, which was necessary for our internal project. so, yes, triton-cpu is still a thing! I know it will add more burdens. but, I'm actually okay to skip some tests in OSS?

**Pull request closed without merging**
