### PR TITLE
fix view listing in autograd codegen

### PR DESCRIPTION
**Pull request by albanD**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #31990 Make autogen functions correct for multiple outputs and views
* **#32044 fix view listing in autograd codegen**

Fix the list of views in the codegen:
- Move `narrow` out of the autograd functions since it's now implemented with slice.
- Add `split_with_sizes` that was missing from the list.
- Remove assert for multi-output views. Full fix in the next PR in the stack.

Differential Revision: [D19409648](https://our.internmc.facebook.com/intern/diff/D19409648)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 75612e63:


**None of the build failures appear to be your fault**.

* **1/1** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=67c1d930eb51626d282e93818200977acc6945a9&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base 67c1d930 since Jan 09
  <details>
  <summary>
  You may want to rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  Since your merge base is older than `viable/strict`, run these commands:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=75612e6374289ce40af73cc7a8a5a8c886c5e2fb).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [pytorch_linux_xenial_cuda9_cudnn7_py3_build](https://dr.pytorch.org/build-details.html?build_id=83222738) from Jan 09 until Jan 09



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by dlibenzi** [comment]
So there are multiple issues here.
The more immediate is that the split* APIs changed signatures, or became "non leaf" (a leaf function is one a backend can override).
We use this file, which pytorch build generates, to discover leaf functions:

https://github.com/pytorch/xla/blob/705d130d466c8eef2892a24983c953678c5619f0/scripts/generate_code.sh#L14

But the other issue that I gather from comments, is that split* APIs are returning views?!?
That, we do not in XLA, and if that is the case, we have another fix there.

@ailzhang

**Comment by dlibenzi** [comment]
Do you mind to post the content of the `torch/csrc/autograd/generated/RegistrationDeclarations.h` file in your build with this PR patched in?

So, if XLA stops overriding them, we will get the pytorch default implementation which is using slice()?
It might be OK, but OTOH we will have to check performance.

**Comment by albanD** [comment]
You can find the how it changes the `RegistrationDeclarations.h` file [here](https://github.com/pytorch/pytorch/compare/0f0c5e1...albanD:registration_diff).

> So, if XLA stops overriding them, we will get the pytorch default implementation which is using slice()?

I'm not sure exactly how the XLA binding is working. But that was my guess yes. For example you can see that `chunk` which is natively autodiffed has this behavior.
What kind of benchmark would be good you think to test models that use `split*`?

**Comment by dlibenzi** [comment]
OK, so the split* are entirely gone?
I can see them being implemented in terms of narrow() ATM.
Let me do a PR which removes them and see if tests passes.
Going through narrow() means we automatically get "views" behavior ... which might reveal issues.

**Comment by albanD** [comment]
Yes they are entirely gone now.
`narrow` seems to be a weird case as it is not in `RegistrationDeclarations.h` but you seem to reimplement one in `pytorch/xla`. 

> Going through narrow() means we automatically get "views" behavior ... which might reveal issues.

We want to catch these issues and fix them :)

**Comment by dlibenzi** [comment]
I think narrow_copy() is what we override.
But yeah, we need more clarity and explicit testing here ... @ailzhang

**Comment by dlibenzi** [comment]
I created https://github.com/pytorch/xla/pull/1530 to remove the split*() registrations.

**Review by zdevito — APPROVED** [review]
This looks fine from my perspective, but I would feel better if there were some tests added that check the RNN views case described in the PR.

**Comment by albanD** [comment]
@zdevito there are many of them already (checking full lstm and each cell). They were all broken before I made the change to change the version counter in RNN.cpp. Do you have any other test in mind?

**Comment by dlibenzi** [comment]
Is there a full list of ops which should be views?
We better check that, as split*() being views totally escaped us.

**Comment by albanD** [comment]
The full list is [here](https://github.com/pytorch/pytorch/blob/19bbb4fccb15fdd120ff00697887331f5a2394ef/tools/autograd/gen_autograd.py#L32-L68).
The first struct contains the elementary functions (in terms of autograd) that are views.
The second one contains aten native functions that are views (used by the jit).

**Comment by zdevito** [comment]
Were those RNN tests disabled? Or how are they failing if the build is green? I just want to make sure that if this breaks again, we get CI signal.

**Comment by albanD** [comment]
They were not failing because `split_with_sizes` was not registered as a view function. So the autograd inplace checks that we do for views did not run for it.
Once I added `split_with_sizes` to the list of view functions (and that the inplace check runs), all the rnn started failing.
After changing the rnn `chunk` (that uses `split_with_sizes` under the hood) with the version that does not do inplace checks (this is a particular case where we manage all the tensors locally and make sure that all inplace are valid), all the CI is green again.

**Pull request closed without merging**
