### PR TITLE
Eliminate c10::stoi,c10::stod,c10::stoull,c10::stoll

### PR DESCRIPTION
**Pull request by cyyever**
We can remove these functions in favor of std ones.

### CODE REVIEW

**Review by colesbury — APPROVED** [review]

**Comment by pmeier** [comment]
This broke `torchvision`'s video utilities. Forward fix in pytorch/vision#7966. Please stamp that or revert this.

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but this is breaking periodic buck build, so please fix the issue and reland the change https://github.com/pytorch/pytorch/actions/runs/6207458526/job/16852695272' -c nosignal

I'm adding ciflow/periodic to run buck build in your PR

**Comment by huydhn** [comment]
I think it is failing ios build and test job too https://github.com/pytorch/pytorch/actions/runs/6211626622/job/16861007267#step:10:518

**Comment by huydhn** [comment]
Opps, I didn't realize that https://hud.pytorch.org/pytorch/pytorch/commit/5d5990fc49260cfd717df629017720109c89f1d4 forward fix has been landed.  Please help reopen this change, and I will reland it back to trunk

**Pull request closed without merging**
