### PR TITLE
[NNC] add more fusion of elementwise OPs with conv

### PR DESCRIPTION
**Pull request by chunyuan-w**
## Pitch
This PR adds the below elementwise fusion for conv in NNC:

- sigmoid
- tanh
- leaky_relu
- hardtanh
- gelu
- clamp

## Description
Extend the graph rewrite and the fusion attribute map to support the below categories of elementwise OPs:

- OPs that only have the activation tensor as input:
  - `sigmoid(Tensor self) -> Tensor`
  - `tanh(Tensor self) -> Tensor`
- OPs that have activation tensor and scalar inputs:
  - `leaky_relu(Tensor self, Scalar negative_slope=0.01) -> Tensor`
  - `hardtanh(Tensor self, Scalar min_val=-1, Scalar max_val=1) -> Tensor`
- OPs that have activation tensor and string inputs:
  - `gelu(Tensor self, *, str approximate='none') -> Tensor`
- OPs that have activation tensor and optional scalar inputs:
  - `clamp(Tensor self, Scalar? min=None, Scalar? max=None) -> Tensor`
 
### UT
```
test/test_mkldnn_fusion.py
```

## Benchmark
Configuration
- Measured on Ice Lake
- Jemalloc enabled
- batch_size = 1
- Channels Last format

### Single thread:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/chunyuan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/chunyuan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

shape | time (us)_no_fusion | time (us)_fusion | Gain
-- | -- | -- | --
Conv+tanh: kernel=3, N=1, iC=64, H=56,   W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 2407.23 | 1541.44 | 35.97%
Conv+tanh: kernel=1, N=1, iC=256, H=56,   W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 3316.45 | 1759.5 | 46.95%
Conv+tanh: kernel=3, N=1, iC=256, H=56,   W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 5685.67 | 3250.43 | 42.83%
Conv+tanh: kernel=3, N=1, iC=512, H=56,   W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 4181.54 | 2644.02 | 36.77%
Conv+tanh: kernel=1, N=1, iC=64, H=56,   W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 1357.76 | 517.36 | 61.90%
Conv+tanh: kernel=1, N=1, iC=256, H=56,   W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 1768.34 | 915.53 | 48.23%
Conv+tanh: kernel=1, N=1, iC=256, H=56,   W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 6329.62 | 3394.09 | 46.38%
Conv+tanh: kernel=1, N=1, iC=512, H=28,   W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 4412.08 | 2850.87 | 35.38%
Conv+sigmoid: kernel=3, N=1, iC=64, H=56,   W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 1822.93 | 1536.77 | 15.70%
Conv+sigmoid: kernel=1, N=1, iC=256,   H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 2445.69 | 1754.33 | 28.27%
Conv+sigmoid: kernel=3, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 3956.79 | 3342.7 | 15.52%
Conv+sigmoid: kernel=3, N=1, iC=512,   H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 3237.87 | 2654.81 | 18.01%
Conv+sigmoid: kernel=1, N=1, iC=64, H=56,   W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 805.88 | 517.2 | 35.82%
Conv+sigmoid: kernel=1, N=1, iC=256,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 1202.22 | 910.34 | 24.28%
Conv+sigmoid: kernel=1, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 4618.22 | 3377.29 | 26.87%
Conv+sigmoid: kernel=1, N=1, iC=512,   H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 3529.09 | 2862.32 | 18.89%
Conv+LeakyRelu: kernel=3, N=1, iC=64,   H=56, W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 1700.15 | 1459.02 | 14.18%
Conv+LeakyRelu: kernel=1, N=1, iC=256,   H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 2133.19 | 1612.48 | 24.41%
Conv+LeakyRelu: kernel=3, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 3448.26 | 2670.56 | 22.55%
Conv+LeakyRelu: kernel=3, N=1, iC=512,   H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 3000.81 | 2498.86 | 16.73%
Conv+LeakyRelu: kernel=1, N=1, iC=64,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 685.06 | 446.12 | 34.88%
Conv+LeakyRelu: kernel=1, N=1, iC=256,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 1077.33 | 840.69 | 21.97%
Conv+LeakyRelu: kernel=1, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 4064.71 | 3101.89 | 23.69%
Conv+LeakyRelu: kernel=1, N=1, iC=512,   H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 3233.11 | 2711.76 | 16.13%
Conv+hardtanh: kernel=3, N=1, iC=64,   H=56, W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 1701.53 | 1460.08 | 14.19%
Conv+hardtanh: kernel=1, N=1, iC=256,   H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 2137.1 | 1609.5 | 24.69%
Conv+hardtanh: kernel=3, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 3548.07 | 2654.61 | 25.18%
Conv+hardtanh: kernel=3, N=1, iC=512,   H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 2999.23 | 2507.39 | 16.40%
Conv+hardtanh: kernel=1, N=1, iC=64,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 686.75 | 443.09 | 35.48%
Conv+hardtanh: kernel=1, N=1, iC=256,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 1076.85 | 840.71 | 21.93%
Conv+hardtanh: kernel=1, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 4070.51 | 3099.9 | 23.84%
Conv+hardtanh: kernel=1, N=1, iC=512,   H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 3198.08 | 2691.94 | 15.83%
Conv+geluApproximateNone: kernel=3, N=1,   iC=64, H=56, W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 2325.84 | 1565.3 | 32.70%
Conv+geluApproximateNone: kernel=1, N=1,   iC=256, H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 3031.34 | 1811.86 | 40.23%
Conv+geluApproximateNone: kernel=3, N=1,   iC=256, H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 5171.4 | 3483.27 | 32.64%
Conv+geluApproximateNone: kernel=3, N=1,   iC=512, H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 3941.8 | 2716.11 | 31.09%
Conv+geluApproximateNone: kernel=1, N=1,   iC=64, H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 1265.2 | 543.45 | 57.05%
Conv+geluApproximateNone: kernel=1, N=1,   iC=256, H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 1694.72 | 940.23 | 44.52%
Conv+geluApproximateNone: kernel=1, N=1,   iC=256, H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 5830.62 | 3499.1 | 39.99%
Conv+geluApproximateNone: kernel=1, N=1,   iC=512, H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 4103.29 | 2917.37 | 28.90%
Conv+geluApproximateTanh: kernel=3, N=1,   iC=64, H=56, W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 2463.44 | 1565.52 | 36.45%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=256, H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 3515.69 | 1803.82 | 48.69%
Conv+geluApproximateTanh: kernel=3, N=1,   iC=256, H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 6119.11 | 3520.61 | 42.47%
Conv+geluApproximateTanh: kernel=3, N=1,   iC=512, H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 4448.33 | 2803.28 | 36.98%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=64, H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 1430.18 | 545.79 | 61.84%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=256, H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 1842.78 | 943.23 | 48.81%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=256, H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 6753.14 | 3526.2 | 47.78%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=512, H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 4581.45 | 2951.88 | 35.57%

</body>

</html>

### 4 threads:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/chunyuan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/chunyuan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

shape | time (us)_no_fusion | time (us)_fusion | Gain
-- | -- | -- | --
Conv+tanh: kernel=3, N=1, iC=64, H=56,   W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 586.07 | 420.98 | 28.17%
Conv+tanh: kernel=1, N=1, iC=256, H=56,   W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 765.55 | 430.55 | 43.76%
Conv+tanh: kernel=3, N=1, iC=256, H=56,   W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 1273.38 | 789.03 | 38.04%
Conv+tanh: kernel=3, N=1, iC=512, H=56,   W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 1073.27 | 719.35 | 32.98%
Conv+tanh: kernel=1, N=1, iC=64, H=56,   W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 262.88 | 95.37 | 63.72%
Conv+tanh: kernel=1, N=1, iC=256, H=56,   W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 392.27 | 227.78 | 41.93%
Conv+tanh: kernel=1, N=1, iC=256, H=56,   W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 1567.03 | 806.2 | 48.55%
Conv+tanh: kernel=1, N=1, iC=512, H=28,   W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 1079.88 | 747.73 | 30.76%
Conv+sigmoid: kernel=3, N=1, iC=64, H=56,   W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 443.88 | 419.77 | 5.43%
Conv+sigmoid: kernel=1, N=1, iC=256,   H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 468.36 | 427.21 | 8.79%
Conv+sigmoid: kernel=3, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 777.16 | 776.97 | 0.02%
Conv+sigmoid: kernel=3, N=1, iC=512,   H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 773.1 | 732.8 | 5.21%
Conv+sigmoid: kernel=1, N=1, iC=64, H=56,   W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 120.24 | 95.76 | 20.36%
Conv+sigmoid: kernel=1, N=1, iC=256,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 250.95 | 226 | 9.94%
Conv+sigmoid: kernel=1, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 879.55 | 801.58 | 8.86%
Conv+sigmoid: kernel=1, N=1, iC=512,   H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 782.4 | 745.92 | 4.66%
Conv+LeakyRelu: kernel=3, N=1, iC=64,   H=56, W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 407.49 | 396.2 | 2.77%
Conv+LeakyRelu: kernel=1, N=1, iC=256,   H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 406.09 | 384.21 | 5.39%
Conv+LeakyRelu: kernel=3, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 607.71 | 593.08 | 2.41%
Conv+LeakyRelu: kernel=3, N=1, iC=512,   H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 732.3 | 716.45 | 2.16%
Conv+LeakyRelu: kernel=1, N=1, iC=64,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 82.59 | 71.94 | 12.90%
Conv+LeakyRelu: kernel=1, N=1, iC=256,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 216.97 | 204.84 | 5.59%
Conv+LeakyRelu: kernel=1, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 789.29 | 714.72 | 9.45%
Conv+LeakyRelu: kernel=1, N=1, iC=512,   H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 726.41 | 703.36 | 3.17%
Conv+hardtanh: kernel=3, N=1, iC=64,   H=56, W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 407.6 | 396.96 | 2.61%
Conv+hardtanh: kernel=1, N=1, iC=256,   H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 407.28 | 382.26 | 6.14%
Conv+hardtanh: kernel=3, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 603.98 | 590.46 | 2.24%
Conv+hardtanh: kernel=3, N=1, iC=512,   H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 745.39 | 715.81 | 3.97%
Conv+hardtanh: kernel=1, N=1, iC=64,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 84.23 | 72.47 | 13.96%
Conv+hardtanh: kernel=1, N=1, iC=256,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 215.92 | 205.01 | 5.05%
Conv+hardtanh: kernel=1, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 786.32 | 715.2 | 9.04%
Conv+hardtanh: kernel=1, N=1, iC=512,   H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 726.05 | 703.44 | 3.11%
Conv+geluApproximateNone: kernel=3, N=1,   iC=64, H=56, W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 540.83 | 428.36 | 20.80%
Conv+geluApproximateNone: kernel=1, N=1,   iC=256, H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 668.43 | 446.6 | 33.19%
Conv+geluApproximateNone: kernel=3, N=1,   iC=256, H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 1144.99 | 849.36 | 25.82%
Conv+geluApproximateNone: kernel=3, N=1,   iC=512, H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 1001.79 | 755.24 | 24.61%
Conv+geluApproximateNone: kernel=1, N=1,   iC=64, H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 215.58 | 101.46 | 52.94%
Conv+geluApproximateNone: kernel=1, N=1,   iC=256, H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 347.16 | 235.95 | 32.03%
Conv+geluApproximateNone: kernel=1, N=1,   iC=256, H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 1408.63 | 836.89 | 40.59%
Conv+geluApproximateNone: kernel=1, N=1,   iC=512, H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 982.54 | 763.92 | 22.25%
Conv+geluApproximateTanh: kernel=3, N=1,   iC=64, H=56, W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 615.4 | 433.58 | 29.55%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=256, H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 825.42 | 463.36 | 43.86%
Conv+geluApproximateTanh: kernel=3, N=1,   iC=256, H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 1416.24 | 911.38 | 35.65%
Conv+geluApproximateTanh: kernel=3, N=1,   iC=512, H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 1163.87 | 715.14 | 38.55%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=64, H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 293.41 | 108.72 | 62.95%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=256, H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 419.72 | 240.78 | 42.63%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=256, H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 1656.42 | 854.6 | 48.41%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=512, H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 1143.01 | 775.27 | 32.17%

</body>

</html>

### 1 socket (32 cores):

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/chunyuan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/chunyuan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

shape | time (us)_no_fusion | time (us)_fusion | Gain
-- | -- | -- | --
Conv+tanh: kernel=3, N=1, iC=64, H=56,   W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 127.55 | 104.88 | 17.77%
Conv+tanh: kernel=1, N=1, iC=256, H=56,   W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 143.31 | 94.4 | 34.13%
Conv+tanh: kernel=3, N=1, iC=256, H=56,   W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 369.44 | 130.5 | 64.68%
Conv+tanh: kernel=3, N=1, iC=512, H=56,   W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 211.54 | 169.37 | 19.93%
Conv+tanh: kernel=1, N=1, iC=64, H=56,   W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 75.53 | 45.35 | 39.96%
Conv+tanh: kernel=1, N=1, iC=256, H=56,   W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 91.14 | 62.77 | 31.13%
Conv+tanh: kernel=1, N=1, iC=256, H=56,   W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 235.74 | 137.03 | 41.87%
Conv+tanh: kernel=1, N=1, iC=512, H=28,   W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 189.23 | 140.28 | 25.87%
Conv+sigmoid: kernel=3, N=1, iC=64, H=56,   W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 98.24 | 88.93 | 9.48%
Conv+sigmoid: kernel=1, N=1, iC=256,   H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 105.12 | 88 | 16.29%
Conv+sigmoid: kernel=3, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 252.74 | 251.59 | 0.46%
Conv+sigmoid: kernel=3, N=1, iC=512,   H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 223.13 | 180.2 | 19.24%
Conv+sigmoid: kernel=1, N=1, iC=64, H=56,   W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 44.93 | 42.42 | 5.59%
Conv+sigmoid: kernel=1, N=1, iC=256,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 63.61 | 60.25 | 5.28%
Conv+sigmoid: kernel=1, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 158.42 | 135.56 | 14.43%
Conv+sigmoid: kernel=1, N=1, iC=512,   H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 147.82 | 139.43 | 5.68%
Conv+LeakyRelu: kernel=3, N=1, iC=64,   H=56, W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 89.88 | 85.6 | 4.76%
Conv+LeakyRelu: kernel=1, N=1, iC=256,   H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 88.5 | 79.18 | 10.53%
Conv+LeakyRelu: kernel=3, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 198.14 | 100.09 | 49.49%
Conv+LeakyRelu: kernel=3, N=1, iC=512,   H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 159.42 | 145.96 | 8.44%
Conv+LeakyRelu: kernel=1, N=1, iC=64,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 41.86 | 35.36 | 15.53%
Conv+LeakyRelu: kernel=1, N=1, iC=256,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 67.19 | 52.18 | 22.34%
Conv+LeakyRelu: kernel=1, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 166.35 | 124.43 | 25.20%
Conv+LeakyRelu: kernel=1, N=1, iC=512,   H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 139.47 | 130.29 | 6.58%
Conv+hardtanh: kernel=3, N=1, iC=64,   H=56, W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 92.12 | 81.74 | 11.27%
Conv+hardtanh: kernel=1, N=1, iC=256,   H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 87.87 | 80.13 | 8.81%
Conv+hardtanh: kernel=3, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 139.39 | 101.07 | 27.49%
Conv+hardtanh: kernel=3, N=1, iC=512,   H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 174.47 | 146.47 | 16.05%
Conv+hardtanh: kernel=1, N=1, iC=64,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 43.69 | 34.81 | 20.33%
Conv+hardtanh: kernel=1, N=1, iC=256,   H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 67.65 | 53.39 | 21.08%
Conv+hardtanh: kernel=1, N=1, iC=256,   H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 180.4 | 122.88 | 31.88%
Conv+hardtanh: kernel=1, N=1, iC=512,   H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 180.22 | 129.91 | 27.92%
Conv+geluApproximateNone: kernel=3, N=1,   iC=64, H=56, W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 140.1 | 85.07 | 39.28%
Conv+geluApproximateNone: kernel=1, N=1,   iC=256, H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 163.15 | 87.89 | 46.13%
Conv+geluApproximateNone: kernel=3, N=1,   iC=256, H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 390.41 | 132.65 | 66.02%
Conv+geluApproximateNone: kernel=3, N=1,   iC=512, H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 229.57 | 155.16 | 32.41%
Conv+geluApproximateNone: kernel=1, N=1,   iC=64, H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 71.01 | 39.96 | 43.73%
Conv+geluApproximateNone: kernel=1, N=1,   iC=256, H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 95.58 | 55.09 | 42.36%
Conv+geluApproximateNone: kernel=1, N=1,   iC=256, H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 290.14 | 137.89 | 52.47%
Conv+geluApproximateNone: kernel=1, N=1,   iC=512, H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 232.39 | 136.23 | 41.38%
Conv+geluApproximateTanh: kernel=3, N=1,   iC=64, H=56, W=56, oC=64, stride=1, pad=1, dilates=1, g=1 | 151.82 | 89.56 | 41.01%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=256, H=56, W=56, oC=512, stride=2, pad=0, dilates=1, g=1 | 185.89 | 95.09 | 48.85%
Conv+geluApproximateTanh: kernel=3, N=1,   iC=256, H=56, W=56, oC=256, stride=1, pad=1, dilates=1, g=32 | 392.33 | 187.3 | 52.26%
Conv+geluApproximateTanh: kernel=3, N=1,   iC=512, H=56, W=56, oC=512, stride=2, pad=1, dilates=1, g=32 | 238.26 | 156.25 | 34.42%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=64, H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 78.53 | 40.02 | 49.04%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=256, H=56, W=56, oC=64, stride=1, pad=0, dilates=1, g=1 | 102.51 | 56.49 | 44.89%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=256, H=56, W=56, oC=256, stride=1, pad=0, dilates=1, g=1 | 300.9 | 138.6 | 53.94%
Conv+geluApproximateTanh: kernel=1, N=1,   iC=512, H=28, W=28, oC=512, stride=1, pad=0, dilates=1, g=1 | 232.61 | 138.24 | 40.57%

</body>

</html>

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

### CODE REVIEW

**Comment by chunyuan-w** [comment]
To support fusion with elementwise OPs with additional scalar or string inputs:

**Option 1** (the current implementation in the PR):
  Change the `mkldnn_prepack::conv2d_prepack` OP to accept two more arguments `Scalar?[] scalars, str? algorithm` in order to support fusion with elementwise OPs with additional scalar or string inputs.
  - Pros: we only need one single OP to support all these elementwise OPs fusion.
  - Cons: this is a backward incompatible change as marked in the CI. I'm not sure if this is acceptable.

**Option 2**:
  Add a new OP such as `mkldnn_prepacked::conv2d_prepack_with_scalar` which has two more inputs `Scalar?[] scalars, str? algorithm` and keep the `mkldnn_prepack::conv2d_prepack` OP unchanged.
  - Pros: there're no backward incompatible changes on the OP.
  - Cons: can't share the same OP for the elementwise OPs fusion.

Option 3: 
  Based on option 1, I've tried providing default values to the two new arguments but the `parseDefaultValue` function of the function schema parser does not support a List of OptionalType (`Scalar?[] scalars`) to have default values:
  https://github.com/pytorch/pytorch/blob/0e0f8fd03e0967059456d4755c47e8fd4407796d/torch/csrc/jit/frontend/function_schema_parser.cpp#L277-L279
  Currently, I'm not able to implement it via option 3.

**Review by ZolotukhinM — COMMENTED** [review]
This seems to partially overlap with #84419 (and this comments from that PR apply to this one as well). In what order do we plan to land them and how do we deal with the overlap?

**Comment by XiaobingSuper** [comment]
@ZolotukhinM , yes, https://github.com/pytorch/pytorch/pull/84419 has overlaps with this PR, we can firstly land this PR, and then I will solve the conflict after this PR landed. Thanks!

**Comment by EikanWang** [comment]
@ZolotukhinM , do you think it is better to add the PR [#88149](https://github.com/pytorch/pytorch/pull/84419) to this stack?

**Comment by frank-wei** [comment]
> @ZolotukhinM , do you think it is better to add the PR [#88149](https://github.com/pytorch/pytorch/pull/84419) to this stack?

@EikanWang  could you fix the failed tests first. As @ZolotukhinM mentioned, I think we land this PR first, then you rebase https://github.com/pytorch/pytorch/pull/84419

**Comment by EikanWang** [comment]
Got it. Regarding the schema change, it is only for the Post-op fusion but irrelevant for PyTorch operators. @frank-wei @ZolotukhinM

**Comment by EikanWang** [comment]
@chunyuan-w , please double-check the CI failures and make sure only schema-related failures.

**Comment by chunyuan-w** [comment]
Besides the schema-related failure, the other one seems irrelevant with the change in this PR:

image

@frank-wei do you need me to rebase this PR to the recent master?

**Comment by frank-wei** [comment]
> Besides the schema-related failure, the other one seems irrelevant with the change in this PR:
> 
> image
> 
> @frank-wei do you need me to rebase this PR to the recent master?

please rebase and check again.

**Comment by frank-wei** [comment]
> Got it. Regarding the schema change, it is only for the Post-op fusion but irrelevant for PyTorch operators. @frank-wei @ZolotukhinM

Correct but the this implementation will introduce backward compatibility problem. NNC is still in Beta phase so theoretically, API could change. Just make sure the CI test failure is not due to backward compatibility issues.

**Comment by chunyuan-w** [comment]
@frank-wei I've merged the recent master.

There're 2 CI failures, which should be expected:
- backwards_compat
- Meta Internal-Only Changes Check — The Diff and Pull Request are not in sync!

**Comment by chunyuan-w** [comment]
I've merged the recent master to resolve conflicts.

**Comment by frank-wei** [comment]
Calling @malfet  for more opinions. We have imported this PR and looks like ok to internal. Should we allow this interface change?

**Review by bertmaher — APPROVED** [review]

**Comment by bertmaher** [comment]
Just checking here, this PR doesn't depend on anything else (e.g. #84419) right?

**Comment by chunyuan-w** [comment]
> Just checking here, this PR doesn't depend on anything else (e.g. #84419) right?

Correct, this PR doesn't depend on other PRs.

**Comment by bertmaher** [comment]
Ok, cool, I think we can land this.  @frank-wei can you take care of landing?  I think I don't have the right internal privileges.

**Pull request closed without merging**
