### PR TITLE
Add multiprocess option to dynamo benchmarks

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #106394

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

### CODE REVIEW

**Review by XilunWu — APPROVED** [review]
LGTM. I'm curious of the verification of benchmark's correctness after enabling `mp` because I'm not sure if the benchmark is specifically designed for single process testing.

**Comment by ezyang** [comment]
This appears to have caused https://github.com/pytorch/pytorch/issues/107300 as it now induces a device_count call prior to CUDA getting initialized.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/107301

**Pull request closed without merging**
