### PR TITLE
Dynamo size dim kwargs

### PR DESCRIPTION
**Pull request by nima10khodaveisi**
Fix https://github.com/pytorch/pytorch/pull/97098#discussion_r1145157874

@ngimel @voznesenskym 

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by nima10khodaveisi** [comment]
@ezyang Would you please merge this?

**Comment by nima10khodaveisi** [comment]
@ezyang

**Pull request closed without merging**
