### PR TITLE
propagate torch stack trace metadata to copy_() nodes during input mutations

### PR DESCRIPTION
**Pull request by bdhirsh**
Tested by running the below script:
```
import torch
@torch.compile(backend="aot_eager", fullgraph=True)
def f(x):
    y = x.view(-1)
    y.mul_(2)
    return

x = torch.ones(4)
f(x)
```

Which gives me this ATen graph (notice that the copy_() node is bundled under the stacktrace for `mul_(2)`):
```
 ===== Forward graph 0 =====
 <eval_with_key>.2 from /data/users/hirsheybar/e/pytorch/torch/fx/experimental/proxy_tensor.py:521 in wrapped class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: "f32[4]"):
        # File: /data/users/hirsheybar/e/pytorch/tmp5.py:8, code: y = x.view(-1)
        view: "f32[4]" = torch.ops.aten.view.default(arg0_1, [-1])

        # File: /data/users/hirsheybar/e/pytorch/tmp5.py:9, code: y.mul_(2)
        mul: "f32[4]" = torch.ops.aten.mul.Tensor(view, 2);  view = None
        view_1: "f32[4]" = torch.ops.aten.view.default(mul, [4]);  mul = None
        copy_: "f32[4]" = torch.ops.aten.copy_.default(arg0_1, view_1);  arg0_1 = view_1 = None
        return ()

```

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #116874
* __->__ #117587

### CODE REVIEW

**Comment by ezyang** [comment]
This is definitely worth adding a unit test

**Review by eellison — APPROVED** [review]
LGTM but could use test. Also you have test failures because we are not always maintaining the stack_trace. Maybe relax that to land that and it'd be a good follow up issue to check we are always maintaining it.

I tried to construct example with multiple writes to see what would happen but I guess we exclude those from the graph or something ?

```
import torch

def f(x):
    y = x.view(-1)
    y.mul_(2)
    y.mul_(4)
    return y

f_comp = torch.compile(backend="aot_eager", fullgraph=True)(f)

x = torch.ones(4)
y = torch.ones(4)

torch.testing.assert_close(f(x), f_comp(y))
torch.testing.assert_close(x, y)
```

**Comment by bdhirsh** [comment]
yep, will add a test before landing. Still need to dig into the CI failures

**Comment by bdhirsh** [comment]
> I tried to construct example with multiple writes to see what would happen but I guess we exclude those from the graph or something ?

That's right - if there are multiple mutations to a single graph input, we will functionalize them into a single "input_updated" at the end of the graph, and we'll end up with one giant `input.copy_(input_updated)` at the end.

**Comment by bdhirsh** [comment]
Updated + added a test

**Pull request closed without merging**
