### PR TITLE
Give linting steps a unique prefix

### PR DESCRIPTION
**Pull request by ZainRizvi**
Give a unique prefix to all steps in lint.yml which catch valid linter errors. This will let retrybot identify lint.yml steps which should not be retried.

This is a prelude to https://github.com/pytorch/test-infra/pull/1275 which extends the retry-on-failure behavior to all PRs in addition to trunk.  

This hadn't been an issue previously since we would always only linter failures on `master`, where linter failures were always safe to retry since legitimate linter failures there are virtually non-existent

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM! I think we should put a comment on why `Run lint` prefix is needed

**Review by malfet — CHANGES_REQUESTED** [review]
This feels wrong to me: workflow name should be computed as combination of workflow name + job name, as its currently done by the hud, see: 
image

**Comment by ZainRizvi** [comment]
> This feels wrong to me: workflow name should be computed as combination of workflow name + job name, as its currently done by the hud, see: image

@malfet the goal here isn't to determine the workflow name, it's to identify steps in the lint workflow that should not be considered "retryable"

One alternative is to prefix the names with an explicit "[nonretryable]" prefix (which I've just done). A benefit here is that it becomes somewhat self-documenting

**Review by malfet — APPROVED** [review]
LGTM, but I wonder if it could be suffix rather than prefix (as machines do not care about length of the string, but humans do, and sentences written in latin alphabet are usually read from left to right)
Another suggestion: should we use say #nonretryable ? (or explain how we can add other modifiers to the code?)

**Comment by ZainRizvi** [comment]
> LGTM, but I wonder if it could be suffix rather than prefix (as machines do not care about length of the string, but humans do, and sentences written in latin alphabet are usually read from left to right) Another suggestion: should we use say #nonretryable ? (or explain how we can add other modifiers to the code?)

We could move it to the suffix. # would be nice, but that'll get interpreted as a comment and be ignored by the yaml readers

**Comment by malfet** [comment]
> We could move it to the suffix. # would be nice, but that'll get interpreted as a comment and be ignored by the yaml readers

`(nonretiable)` sounds fine as well, as long as its documented, that  tags should always be wrapped by a pair of round brackets, i.e. something like `(nonretriable) (knownflaky)`

**Pull request closed without merging**
