### PR TITLE
Change Variable.cuda to be consistent with Tensor.cuda

### PR DESCRIPTION
**Pull request by ssnl**
Fix for issue #2685 .

### CODE REVIEW

**Comment by ezyang** [comment]
And amazingly, this didn't trip any tests :)

**Comment by SsnL** [comment]
Haha yeah! I was surprised as well. Apparently we didn't test Variable.cuda well enough (at all).

**Comment by gchanan** [comment]
user code could still break, right?  Perhaps we should have the old name as kw-only argument and issue a deprecated warning?

**Comment by SsnL** [comment]
Fair point, I will do that tomorrow.

**Comment by apaszke** [comment]
To be honest I don't think the name of this arg is important enough to warrant adding more deprecations in our code. Let's just merge it. 99.99% of user code doesn't use it (I've never seen it specified as a kwarg)

**Comment by apaszke** [comment]
Thank you!

**Comment by jane42** [comment]
Great

**Pull request merged**
