### PR TITLE
Add OpInfo for _weight_norm_interface.

### PR DESCRIPTION
**Pull request by qihqi**
Follow up for https://github.com/pytorch/pytorch/pull/112193

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by qihqi** [comment]
Hi @lezcano, trying to add OpInfo following examples; not really sure about if I am doing it correctly. LMK of any feedback, thanks!

**Review by lezcano — COMMENTED** [review]
Wow, I didn't realise this function is not even exposed in the Python API and it's not documented. Where is this function even used? Would it be fine to remove it?
If we want to keep it, we should document it and expose it in the Python API
cc @ezyang 

At any rate, this PR looks alright but the failures are real. Also, remove the previous test, as this one supersedes it.

**Comment by ezyang** [comment]
Sometimes I add OpInfo for internal functions because there is no convenient way to test the interface otherwise (this is particular common for backwards). This is fine. Your tests are failing though.

**Comment by lezcano** [comment]
Yes, my point is that this function is not being used by other ATen ops, and it's not exposed to Python through any documented API

**Comment by ezyang** [comment]
oh, well, if it's completely dead, we should remove it lol

**Comment by lezcano** [comment]
Ah, no, this is used within _weight_norm, which is indeed used to implement the parametrization. nvm

**Comment by ezyang** [comment]
deferring review to lezcano

**Comment by lezcano** [comment]
Consider running the failing tests locally (pytest test/test_ops*.py -vk _weight_norm and same for functorch about the other failing tests) and making sure they pass locally before pushing to the branch.

Also, feel free to re-request a review once CI is green.

**Pull request closed without merging**
