### PR TITLE
[export] Fix duplicated params for AOTInductor.

### PR DESCRIPTION
**Pull request by zhxchen17**
Summary:

Test Plan:
python benchmarks/dynamo/huggingface.py --bfloat16 --accuracy
--inference --device cuda --export --only  BertForMaskedLM

python benchmarks/dynamo/huggingface.py --bfloat16 --accuracy --inference --device cuda --export-aot-inductor --only  BertForMaskedLM

Reviewers:

Subscribers:

Tasks:

Tags:

Fixes #ISSUE_NUMBER

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by angelayi — APPROVED** [review]

**Review by desertfire — COMMENTED** [review]
While I will add CI integration tests, can we have a unit test for this specific issue?

**Comment by zhxchen17** [comment]
> While I will add CI integration tests, can we have a unit test for this specific issue?

sure no problem

**Review by desertfire — COMMENTED** [review]
https://github.com/pytorch/pytorch/blob/main/test/inductor/test_aot_inductor.py will be the right place to add a unit test.

**Comment by zhxchen17** [comment]
added one unit test

**Review by desertfire — APPROVED** [review]

**Pull request closed without merging**
