### PR TITLE
C++ API parity: isfinite

### PR DESCRIPTION
**Pull request by pbelevich**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #28783 C++ API parity: BCEWithLogitsLoss
* **#30083 C++ API parity: isfinite**

Differential Revision: [D18594723](https://our.internmc.facebook.com/intern/diff/D18594723)

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Review by yf225 — APPROVED** [review]

**Comment by jjlilley** [comment]
Wondering, I see the following when I run tests on caffe2/tests/...

>   File "/data/users/jeremyl/fbsource/fbcode/buck-out/dev/gen/caffe2/test/rpc_fork#binary,link-tree/torch/_torch_docs.py", line 2415, in <module>
>     add_docstr(torch.isfinite,
> AttributeError: module 'torch' has no attribute 'isfinite'

Is this related?

**Comment by zou3519** [comment]
cc @ailzhang the xla CI was red on this and it seems to be failing on master in the same way, do you know what could be up here?

**Comment by zou3519** [comment]
> Wondering, I see the following when I run tests on caffe2/tests/...
> 
> > File "/data/users/jeremyl/fbsource/fbcode/buck-out/dev/gen/caffe2/test/rpc_fork#binary,link-tree/torch/_torch_docs.py", line 2415, in 
> > add_docstr(torch.isfinite,
> > AttributeError: module 'torch' has no attribute 'isfinite'
> 
> Is this related?

@jjlilley A clean and a rebuild might fix the problem; The python bindings for `isfinite` now gets autogenerated

**Comment by jjlilley** [comment]
Ah, thanks, I should have tried that earlier

**Comment by ailzhang** [comment]
Thanks @zou3519! @mruberry has temporarily disabled this test on XLA side. And we're trying to investigate the root cause. 
@pbelevich Ideally a PR that breaking XLA test should notify us before it's merged ;). The easiest way is to open an issue in `pytorch/xla` and link the broken PR. That way we'll have more time to prepare a fix. Thanks!

**Pull request closed without merging**
