### PR TITLE
[Inductor] Use argument names as the key for the `constants` dict and the `signature` dict

### PR DESCRIPTION
**Pull request by Jokeren**
Referencing how triton constructs these dictionaries

https://github.com/triton-lang/triton/blob/ca3fb5f6fa6365445d2d982d137aa5cb2a80f547/python/triton/runtime/jit.py#L639

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by Jokeren** [comment]
@shunting314 maybe? Or could you help me find someone to review the PR?

**Review by htyu — APPROVED** [review]
LGTM. Thanks for the fix.

**Pull request closed without merging**
