### PR TITLE
Fix resume issue in CosineAnnealingWarmRestarts (#88791)

### LINKED ISSUE #88791: Potential bug in torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
https://github.com/pytorch/pytorch/blob/fb5c6ae61f1f622ec388ae9fa00e7683ce1729ce/torch/optim/lr_scheduler.py#L1407

Should be self.T_cur = self.T_cur % self.T_i, not self.T_cur = self.T_cur - self.T_i.

### PR DESCRIPTION
**Pull request by neverix**
Fixes #88791, see #110493 for context.

This change is similar to #110493, but uses the modulo-based solution mentioned in the original issue.

### CODE REVIEW

**Comment by neverix** [comment]
The change in PyTorch only updates `T_cur` and `T_i` once. #110493 performs the same update in a loop. Here, `T_i` is updated once while `T_cur` is looped. All three produce the same behavior if we don't take `T_i` into account. Something like
```python3
        if epoch is None:
            epoch = self.last_epoch + 1
        if epoch < 0:
            raise ValueError("Expected non-negative epoch, but got {}".format(epoch))
        if epoch >= self.T_0:
            if self.T_mult == 1:
                self.T_cur = epoch % self.T_0
            else:
                n = int(math.log((epoch / self.T_0 * (self.T_mult - 1) + 1), self.T_mult))
                self.T_cur = epoch - self.T_0 * (self.T_mult ** n - 1) / (self.T_mult - 1)
             self.T_i = self.T_0 * self.T_mult ** (n)
        else:
            self.T_i = self.T_0
            self.T_cur = epoch
```
will produce the same behavior, if `T_cur` is not updated from the outside. I changed the implementation to use that version, but it's unclear to me why it wasn't there in the first place.

**Review by janeyx99 — COMMENTED** [review]
I suppose the difference here is that in the original implementation, when epoch is None, T_cur is set with relation to what T_cur used to be whereas in the new implementation, it would depend on epoch.

In the constructor, T_cur is set to last_epoch, so this difference doesn't actually seem to matter since T_cur = T_cur + 1 should be the same as T_cur = epoch.

The other difference is that in the old code, when epoch is None, T_0 is not used at all, whereas T_0 is considered in your current code. Again though, in the constructor, T_i is set to T_0 right off the bat, so checking if T_cur >= T_i again seems equivalent to epoch >= T_0.

Okay, all in all, this seems more robust by eliminating a branch. Is it possible for you to add a test to verify numbers in optim/test_lrschedulers?

**Comment by neverix** [comment]
Yes. I'm having trouble building Torch on my machine for testing the test case, I will try with a VM next

**Comment by janeyx99** [comment]
If you have access to Docker, trying out codespaces could be interesting/faster than VM: 
image

**Pull request closed without merging**
