### PR TITLE
[FX] Move none assignments to same line

### PR DESCRIPTION
**Pull request by jamesr66a**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#49209 [FX] Move none assignments to same line**

* Make none assignments print after a semicolon on each line
* Also remove none assignment after return because people were freaking out about it lol

ResNet 18

Before

```
import torch
def forward(self, x):
    conv1 = self.conv1(x)
    x = None
    bn1 = self.bn1(conv1)
    conv1 = None
    relu_1 = self.relu(bn1)
    bn1 = None
    maxpool = self.maxpool(relu_1)
    relu_1 = None
    layer1_0_conv1 = getattr(self.layer1, "0").conv1(maxpool)
    layer1_0_bn1 = getattr(self.layer1, "0").bn1(layer1_0_conv1)
    layer1_0_conv1 = None
    layer1_0_relu = getattr(self.layer1, "0").relu(layer1_0_bn1)
    layer1_0_bn1 = None
    layer1_0_conv2 = getattr(self.layer1, "0").conv2(layer1_0_relu)
    layer1_0_relu = None
    layer1_0_bn2 = getattr(self.layer1, "0").bn2(layer1_0_conv2)
    layer1_0_conv2 = None
    add_1 = layer1_0_bn2 + maxpool
    layer1_0_bn2 = maxpool = None
    layer1_1 = getattr(self.layer1, "0").relu(add_1)
    add_1 = None
    layer1_1_conv1 = getattr(self.layer1, "1").conv1(layer1_1)
    layer1_1_bn1 = getattr(self.layer1, "1").bn1(layer1_1_conv1)
    layer1_1_conv1 = None
    layer1_1_relu = getattr(self.layer1, "1").relu(layer1_1_bn1)
    layer1_1_bn1 = None
    layer1_1_conv2 = getattr(self.layer1, "1").conv2(layer1_1_relu)
    layer1_1_relu = None
    layer1_1_bn2 = getattr(self.layer1, "1").bn2(layer1_1_conv2)
    layer1_1_conv2 = None
    add_2 = layer1_1_bn2 + layer1_1
    layer1_1_bn2 = layer1_1 = None
    layer1_2 = getattr(self.layer1, "1").relu(add_2)
    add_2 = None
    layer2_0_conv1 = getattr(self.layer2, "0").conv1(layer1_2)
    layer2_0_bn1 = getattr(self.layer2, "0").bn1(layer2_0_conv1)
    layer2_0_conv1 = None
    layer2_0_relu = getattr(self.layer2, "0").relu(layer2_0_bn1)
    layer2_0_bn1 = None
    layer2_0_conv2 = getattr(self.layer2, "0").conv2(layer2_0_relu)
    layer2_0_relu = None
    layer2_0_bn2 = getattr(self.layer2, "0").bn2(layer2_0_conv2)
    layer2_0_conv2 = None
    layer2_0_downsample_0 = getattr(getattr(self.layer2, "0").downsample, "0")(layer1_2)
    layer1_2 = None
    layer2_0_downsample_1 = getattr(getattr(self.layer2, "0").downsample, "1")(layer2_0_downsample_0)
    layer2_0_downsample_0 = None
    add_3 = layer2_0_bn2 + layer2_0_downsample_1
    layer2_0_bn2 = layer2_0_downsample_1 = None
    layer2_1 = getattr(self.layer2, "0").relu(add_3)
    add_3 = None
    layer2_1_conv1 = getattr(self.layer2, "1").conv1(layer2_1)
    layer2_1_bn1 = getattr(self.layer2, "1").bn1(layer2_1_conv1)
    layer2_1_conv1 = None
    layer2_1_relu = getattr(self.layer2, "1").relu(layer2_1_bn1)
    layer2_1_bn1 = None
    layer2_1_conv2 = getattr(self.layer2, "1").conv2(layer2_1_relu)
    layer2_1_relu = None
    layer2_1_bn2 = getattr(self.layer2, "1").bn2(layer2_1_conv2)
    layer2_1_conv2 = None
    add_4 = layer2_1_bn2 + layer2_1
    layer2_1_bn2 = layer2_1 = None
    layer2_2 = getattr(self.layer2, "1").relu(add_4)
    add_4 = None
    layer3_0_conv1 = getattr(self.layer3, "0").conv1(layer2_2)
    layer3_0_bn1 = getattr(self.layer3, "0").bn1(layer3_0_conv1)
    layer3_0_conv1 = None
    layer3_0_relu = getattr(self.layer3, "0").relu(layer3_0_bn1)
    layer3_0_bn1 = None
    layer3_0_conv2 = getattr(self.layer3, "0").conv2(layer3_0_relu)
    layer3_0_relu = None
    layer3_0_bn2 = getattr(self.layer3, "0").bn2(layer3_0_conv2)
    layer3_0_conv2 = None
    layer3_0_downsample_0 = getattr(getattr(self.layer3, "0").downsample, "0")(layer2_2)
    layer2_2 = None
    layer3_0_downsample_1 = getattr(getattr(self.layer3, "0").downsample, "1")(layer3_0_downsample_0)
    layer3_0_downsample_0 = None
    add_5 = layer3_0_bn2 + layer3_0_downsample_1
    layer3_0_bn2 = layer3_0_downsample_1 = None
    layer3_1 = getattr(self.layer3, "0").relu(add_5)
    add_5 = None
    layer3_1_conv1 = getattr(self.layer3, "1").conv1(layer3_1)
    layer3_1_bn1 = getattr(self.layer3, "1").bn1(layer3_1_conv1)
    layer3_1_conv1 = None
    layer3_1_relu = getattr(self.layer3, "1").relu(layer3_1_bn1)
    layer3_1_bn1 = None
    layer3_1_conv2 = getattr(self.layer3, "1").conv2(layer3_1_relu)
    layer3_1_relu = None
    layer3_1_bn2 = getattr(self.layer3, "1").bn2(layer3_1_conv2)
    layer3_1_conv2 = None
    add_6 = layer3_1_bn2 + layer3_1
    layer3_1_bn2 = layer3_1 = None
    layer3_2 = getattr(self.layer3, "1").relu(add_6)
    add_6 = None
    layer4_0_conv1 = getattr(self.layer4, "0").conv1(layer3_2)
    layer4_0_bn1 = getattr(self.layer4, "0").bn1(layer4_0_conv1)
    layer4_0_conv1 = None
    layer4_0_relu = getattr(self.layer4, "0").relu(layer4_0_bn1)
    layer4_0_bn1 = None
    layer4_0_conv2 = getattr(self.layer4, "0").conv2(layer4_0_relu)
    layer4_0_relu = None
    layer4_0_bn2 = getattr(self.layer4, "0").bn2(layer4_0_conv2)
    layer4_0_conv2 = None
    layer4_0_downsample_0 = getattr(getattr(self.layer4, "0").downsample, "0")(layer3_2)
    layer3_2 = None
    layer4_0_downsample_1 = getattr(getattr(self.layer4, "0").downsample, "1")(layer4_0_downsample_0)
    layer4_0_downsample_0 = None
    add_7 = layer4_0_bn2 + layer4_0_downsample_1
    layer4_0_bn2 = layer4_0_downsample_1 = None
    layer4_1 = getattr(self.layer4, "0").relu(add_7)
    add_7 = None
    layer4_1_conv1 = getattr(self.layer4, "1").conv1(layer4_1)
    layer4_1_bn1 = getattr(self.layer4, "1").bn1(layer4_1_conv1)
    layer4_1_conv1 = None
    layer4_1_relu = getattr(self.layer4, "1").relu(layer4_1_bn1)
    layer4_1_bn1 = None
    layer4_1_conv2 = getattr(self.layer4, "1").conv2(layer4_1_relu)
    layer4_1_relu = None
    layer4_1_bn2 = getattr(self.layer4, "1").bn2(layer4_1_conv2)
    layer4_1_conv2 = None
    add_8 = layer4_1_bn2 + layer4_1
    layer4_1_bn2 = layer4_1 = None
    layer4_2 = getattr(self.layer4, "1").relu(add_8)
    add_8 = None
    avgpool = self.avgpool(layer4_2)
    layer4_2 = None
    flatten_1 = torch.flatten(avgpool, 1)
    avgpool = None
    fc = self.fc(flatten_1)
    flatten_1 = None
    return fc
    fc = None
```

After

```
import torch
def forward(self, x):
    
    conv1 = self.conv1(x); x = None
    bn1 = self.bn1(conv1); conv1 = None
    relu_1 = self.relu(bn1); bn1 = None
    maxpool = self.maxpool(relu_1); relu_1 = None
    layer1_0_conv1 = getattr(self.layer1, "0").conv1(maxpool)
    layer1_0_bn1 = getattr(self.layer1, "0").bn1(layer1_0_conv1); layer1_0_conv1 = None
    layer1_0_relu = getattr(self.layer1, "0").relu(layer1_0_bn1); layer1_0_bn1 = None
    layer1_0_conv2 = getattr(self.layer1, "0").conv2(layer1_0_relu); layer1_0_relu = None
    layer1_0_bn2 = getattr(self.layer1, "0").bn2(layer1_0_conv2); layer1_0_conv2 = None
    add_1 = layer1_0_bn2 + maxpool; layer1_0_bn2 = maxpool = None
    layer1_1 = getattr(self.layer1, "0").relu(add_1); add_1 = None
    layer1_1_conv1 = getattr(self.layer1, "1").conv1(layer1_1)
    layer1_1_bn1 = getattr(self.layer1, "1").bn1(layer1_1_conv1); layer1_1_conv1 = None
    layer1_1_relu = getattr(self.layer1, "1").relu(layer1_1_bn1); layer1_1_bn1 = None
    layer1_1_conv2 = getattr(self.layer1, "1").conv2(layer1_1_relu); layer1_1_relu = None
    layer1_1_bn2 = getattr(self.layer1, "1").bn2(layer1_1_conv2); layer1_1_conv2 = None
    add_2 = layer1_1_bn2 + layer1_1; layer1_1_bn2 = layer1_1 = None
    layer1_2 = getattr(self.layer1, "1").relu(add_2); add_2 = None
    layer2_0_conv1 = getattr(self.layer2, "0").conv1(layer1_2)
    layer2_0_bn1 = getattr(self.layer2, "0").bn1(layer2_0_conv1); layer2_0_conv1 = None
    layer2_0_relu = getattr(self.layer2, "0").relu(layer2_0_bn1); layer2_0_bn1 = None
    layer2_0_conv2 = getattr(self.layer2, "0").conv2(layer2_0_relu); layer2_0_relu = None
    layer2_0_bn2 = getattr(self.layer2, "0").bn2(layer2_0_conv2); layer2_0_conv2 = None
    layer2_0_downsample_0 = getattr(getattr(self.layer2, "0").downsample, "0")(layer1_2); layer1_2 = None
    layer2_0_downsample_1 = getattr(getattr(self.layer2, "0").downsample, "1")(layer2_0_downsample_0); layer2_0_downsample_0 = None
    add_3 = layer2_0_bn2 + layer2_0_downsample_1; layer2_0_bn2 = layer2_0_downsample_1 = None
    layer2_1 = getattr(self.layer2, "0").relu(add_3); add_3 = None
    layer2_1_conv1 = getattr(self.layer2, "1").conv1(layer2_1)
    layer2_1_bn1 = getattr(self.layer2, "1").bn1(layer2_1_conv1); layer2_1_conv1 = None
    layer2_1_relu = getattr(self.layer2, "1").relu(layer2_1_bn1); layer2_1_bn1 = None
    layer2_1_conv2 = getattr(self.layer2, "1").conv2(layer2_1_relu); layer2_1_relu = None
    layer2_1_bn2 = getattr(self.layer2, "1").bn2(layer2_1_conv2); layer2_1_conv2 = None
    add_4 = layer2_1_bn2 + layer2_1; layer2_1_bn2 = layer2_1 = None
    layer2_2 = getattr(self.layer2, "1").relu(add_4); add_4 = None
    layer3_0_conv1 = getattr(self.layer3, "0").conv1(layer2_2)
    layer3_0_bn1 = getattr(self.layer3, "0").bn1(layer3_0_conv1); layer3_0_conv1 = None
    layer3_0_relu = getattr(self.layer3, "0").relu(layer3_0_bn1); layer3_0_bn1 = None
    layer3_0_conv2 = getattr(self.layer3, "0").conv2(layer3_0_relu); layer3_0_relu = None
    layer3_0_bn2 = getattr(self.layer3, "0").bn2(layer3_0_conv2); layer3_0_conv2 = None
    layer3_0_downsample_0 = getattr(getattr(self.layer3, "0").downsample, "0")(layer2_2); layer2_2 = None
    layer3_0_downsample_1 = getattr(getattr(self.layer3, "0").downsample, "1")(layer3_0_downsample_0); layer3_0_downsample_0 = None
    add_5 = layer3_0_bn2 + layer3_0_downsample_1; layer3_0_bn2 = layer3_0_downsample_1 = None
    layer3_1 = getattr(self.layer3, "0").relu(add_5); add_5 = None
    layer3_1_conv1 = getattr(self.layer3, "1").conv1(layer3_1)
    layer3_1_bn1 = getattr(self.layer3, "1").bn1(layer3_1_conv1); layer3_1_conv1 = None
    layer3_1_relu = getattr(self.layer3, "1").relu(layer3_1_bn1); layer3_1_bn1 = None
    layer3_1_conv2 = getattr(self.layer3, "1").conv2(layer3_1_relu); layer3_1_relu = None
    layer3_1_bn2 = getattr(self.layer3, "1").bn2(layer3_1_conv2); layer3_1_conv2 = None
    add_6 = layer3_1_bn2 + layer3_1; layer3_1_bn2 = layer3_1 = None
    layer3_2 = getattr(self.layer3, "1").relu(add_6); add_6 = None
    layer4_0_conv1 = getattr(self.layer4, "0").conv1(layer3_2)
    layer4_0_bn1 = getattr(self.layer4, "0").bn1(layer4_0_conv1); layer4_0_conv1 = None
    layer4_0_relu = getattr(self.layer4, "0").relu(layer4_0_bn1); layer4_0_bn1 = None
    layer4_0_conv2 = getattr(self.layer4, "0").conv2(layer4_0_relu); layer4_0_relu = None
    layer4_0_bn2 = getattr(self.layer4, "0").bn2(layer4_0_conv2); layer4_0_conv2 = None
    layer4_0_downsample_0 = getattr(getattr(self.layer4, "0").downsample, "0")(layer3_2); layer3_2 = None
    layer4_0_downsample_1 = getattr(getattr(self.layer4, "0").downsample, "1")(layer4_0_downsample_0); layer4_0_downsample_0 = None
    add_7 = layer4_0_bn2 + layer4_0_downsample_1; layer4_0_bn2 = layer4_0_downsample_1 = None
    layer4_1 = getattr(self.layer4, "0").relu(add_7); add_7 = None
    layer4_1_conv1 = getattr(self.layer4, "1").conv1(layer4_1)
    layer4_1_bn1 = getattr(self.layer4, "1").bn1(layer4_1_conv1); layer4_1_conv1 = None
    layer4_1_relu = getattr(self.layer4, "1").relu(layer4_1_bn1); layer4_1_bn1 = None
    layer4_1_conv2 = getattr(self.layer4, "1").conv2(layer4_1_relu); layer4_1_relu = None
    layer4_1_bn2 = getattr(self.layer4, "1").bn2(layer4_1_conv2); layer4_1_conv2 = None
    add_8 = layer4_1_bn2 + layer4_1; layer4_1_bn2 = layer4_1 = None
    layer4_2 = getattr(self.layer4, "1").relu(add_8); add_8 = None
    avgpool = self.avgpool(layer4_2); layer4_2 = None
    flatten_1 = torch.flatten(avgpool, 1); avgpool = None
    fc = self.fc(flatten_1); flatten_1 = None
    return fc
```

Differential Revision: [D25484975](https://our.internmc.facebook.com/intern/diff/D25484975)

### CODE REVIEW

**Comment by vkuzo** [comment]
thanks! this significantly improves readability

optional request, would it be possible to insert two spaces instead of one after the semicolon?  That will make it quicker to ignore these when debugging

**Review by Chillee — APPROVED** [review]

**Comment by Chillee** [comment]
Related to @vkuzo 's concerns, perhaps it'd be possible to have a flag to determine when to emit this or not? I guess that's the cop-out approach, so it depends on how much we care about the code generation readability.

**Comment by jamesr66a** [comment]
@Chillee Having a flag adds more complexity than it's worth and is cause for confusion when people use the flag with different settings in different scenarios. Would rather keep things consistent here

**Comment by vkuzo** [comment]
fwiw, since it's now on the same line, it will be easy for users to strip out on their own if they want a custom print

**Pull request closed without merging**
