### PR TITLE
[aot_inductor] move CppWrapperCodeGen into a separate file

### PR DESCRIPTION
**Pull request by chenyang78**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #119491

This PR moved CppWrapperCodeGen class into a seperate file,
cpp_wrapper.py, to simplify wrapper.py

cc @albanD @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by desertfire — APPROVED** [review]

**Comment by desertfire** [comment]
cc @albanD , this is a simple refactoring, so exceeding the changed line number limit is fine.

**Review by albanD — APPROVED** [review]
Yep sounds good!

**Pull request closed without merging**
