### PR TITLE
[DTensor] Supported simple replicate strategy for SVD

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #127032
* #127024
* __->__ #127004

This PR adds a simple strategy to always replicate for `torch.linalg.svd()`. This is to help unblock some GaLore exploration.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]
lgtm, would need to fix the lint

**Comment by awgu** [comment]
For some reason the noclang linter does not seem to work for me locally 🤔  (as in, it does not flag any issues)

**Pull request closed without merging**
