### PR TITLE
Reverting https://github.com/pytorch/pytorch/pull/23228 ("sync and async

### PR DESCRIPTION
**Pull request by pritamdamania87**
Differential Revision: D16705291

### CODE REVIEW

**Review by mrshenli — APPROVED** [review]
Thanks for submitting the revert.

**Comment by aazzolini** [comment]
Do we know why the build broke?

**Comment by mrshenli** [comment]
@aazzolini I think it is because of [this](https://github.com/pytorch/pytorch/blob/master/torch/CMakeLists.txt#L228). `rpc.h` cannot find `python_functions` defined in `init.cpp` on MacOS.  I am trying a fix locally, and will push a PR if that works.

**Comment by mrshenli** [comment]
See fix in #23998

**Comment by pietern** [comment]
With #23998 merged, this revert can be closed.

**Comment by pritamdamania87** [comment]
Abandoning in favor of https://github.com/pytorch/pytorch/pull/23998

**Pull request closed without merging**
