### PR TITLE
[nn modules] Make _parameters, _buffers and _modules regular dicts

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #124578
* #124522
* #124627

Regular dicts are completely implemented in C. OrderedDict have some key ordering infra completely in python, and it overrides the `keys` method of regular dicts.

Since regular dicts are in C, TorchDynamo can use a really fast CPP guard relying on PyDict_Next. But with OrderedDict, TorchDynamo has to call OrderedDict `keys` method to get the correct key ordering. Some more details here - https://github.com/pytorch/pytorch/blob/main/torch/csrc/dynamo/guards.cpp#L2304-L2325

This PR Speeds up nn module guards on TorchDynamo for MobileBert model from ~38000 units to ~25000 units, just because it can rely on PyDict_Next.

I am not sure if change is ok wrt BC etc. If this requires more discussion, I can open an issue. Let me know.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
This is risky. https://stackoverflow.com/a/57072435/23845 for slight API incompatibilities. Please take care when deploying.

**Review by mikaylagawarecki — COMMENTED** [review]
From discussion with @albanD, since `dict` is ordered in Python >= 3.7, we are okay with the `dict` --> `OrderedDict` change if it **does not change any user facing typing**.

However, `dict` and `OrderedDict` implementations are optimized for different access patterns so  (e.g. things like `__getattr__` or `.parameters()`) might become slowed down. We should make sure that this doesn't regress eager benchmarks

**Comment by anijain2305** [comment]
> However, dict and OrderedDict implementations are optimized for different access patterns so (e.g. things like __getattr__ or .parameters()) might become slowed down. 

I think `OrderedDict` and `dict` use the same `__getattr__` function. I skimmed through https://github.com/python/cpython/blob/main/Lib/collections/__init__.py#L83 but could not find any override.

**Review by jansel — APPROVED** [review]
Seems generally like a good change.

**Pull request closed without merging**
