### PR TITLE
[quant][fx] Using native backend_config_dict in fusion

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #75521
* #75520
* #75469
* #75389
* #75388
* #75387
* #75386
* __->__ #75378

Summary:
Previously we are still relying on the registration mechnism and get the default fusion patterns that are registered,
now we have moved all registration to backend_config_dict we can get all fusion patterns just from backend_config_dict now.

This PR enables using native backend_config_dict everywhere in fusion when the backend_config_dict is None,
we'll do similar changes for prepare and convert in the future, to fully enable backend_config_dict in
quantization code base.

Test Plan:
python test/test_quantization.py TestQuantizeFx
python test/test_quantization.py TestQuantizeFxOps
python test/test_quantization.py TestFXNumericSuiteCoreAPIs

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D35451962](https://our.internmc.facebook.com/intern/diff/D35451962)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35451962).

**Review by vkuzo — APPROVED** [review]

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35451962).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35451962).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35451962).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35451962).

**Pull request closed without merging**
