### PR TITLE
Move variabletype functions around

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #63878
* #63459
* #63458
* __->__ #63330

 - This is in preparation for templated/boxed autograd-not-implemented fallback
 - Make sure VariableTypeUtils does not depend on generated code
 - Lift `isFwGradDefined` into `autograd/functions/utils.cpp` so it's available to mobile builds
 - Removes `using namespace at` from VariableTypeUtils, previously we needed this for Templated version, but now its not strictly necessary but still a good change to avoid name conflicts if this header is included elsewhere in the future.

Differential Revision: [D30518573](https://our.internmc.facebook.com/intern/diff/D30518573)

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Does that mean that we now have some isFwGradDefined calls in the mobile builds that we didn't had before?

**Comment by soulitzer** [comment]
Maybe? I'm staring at `build_variables.bzl` and don't completely understand how the hierarchy of builds works yet From what I understand mobile builds only support interpreting scripted models, though it looks like `core_trainer_sources` (e.g., `engine.cpp`) is included as part of the mobile build as well. So the question is what is the relationship between libtorch lite and "the mobile build" (are they the same?), i.e., the answer might be yes (there will be new calls to isFwGradDefined from libtorch lite) if people can train the models using libtorch lite.

Alternatively we can place put the file under `libtorch_extra_sources` which presumably means that it would be part of libtorch, but not libtorch_lite.

cc @ezyang

**Comment by ezyang** [comment]
I don't know what either of you are worried about. Why is the bzl relevant here? You're literally moving a one line function around, surely this shouldn't affect binary size?

**Comment by albanD** [comment]
My question was with respect to a comment in the description that was "This is an issue for mobile builds which don't link to the generated code"
I understood that this change was making the mobile build require new functions that were not linked there before.
But I guess that wasn't accurate.

**Review by ezyang — APPROVED** [review]

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30518573).

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30518573).

**Pull request closed without merging**
