### PR TITLE
[SDPA-CUDNN] Make CuDNN Attention Opt in

### PR DESCRIPTION
**Pull request by drisspg**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #138522

# Summary
Currently we have a `cudnn_order` that says on H100 w/ new enough CuDNN backend (we ship a 9.1 version in OSS) try to run CuDNN attention first. We have already encountered a few bugs with the release of 2.5:

1. https://github.com/pytorch/pytorch/issues/138529
2. https://github.com/huggingface/diffusers/issues/9704
3. https://github.com/pytorch/pytorch/pull/138354

In light of the above we are going to make the CuDNN backend Opt-in by default.

This can be done easily with the context manager for choosing backends I.e.:
``` Python
from torch.nn.attention import sdpa_kernel, SDPBackend    

with sdpa_kernel(SDPBackend.CUDNN_ATTENTION):
    out = F.scaled_dot_product_attention(q, k, v)

```

This PR puts the CuDNN backend as the lowest precedence in the backend list, meaning that the Math backend will always be chosen unless disabled (which is done via the context manager). 

Cc @atalman

cc @mikaylagawarecki

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Review by eqy — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by huydhn** [comment]
@drisspg I think this change is failing on Windows https://github.com/pytorch/pytorch/actions/runs/11464507611/job/31902166240#step:15:21915

test_transformers.py::TestSDPACudaOnlyCUDA::test_fused_sdp_choice_type_dense_cuda [GH job link](https://github.com/pytorch/pytorch/actions/runs/11456639995/job/31876540834) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/5a13282c75f8eedc73c5dd27a88619a766ec8797)

Could you help take a look?

**Comment by drisspg** [comment]
@huydhn can I forward fix this, https://github.com/pytorch/pytorch/pull/138641

Should fix but dont have a windows machine to test on

**Pull request closed without merging**
