### PR TITLE
Allow None arguments for elementwise type promotion wrapper and fix clamp with None arguments

### LINKED ISSUE #759: [mobilenet_v3_large][prims+nvfuser] ValueError: Received type <class 'NoneType'> that is neither a tensor or a number!
Reproduce:
```python
# python benchmarks/torchbench.py --training -d cuda --fast --prims-nvfuser --skip-accuracy-check --generate-aot-autograd-stats --isolate -k mobilenet_v3_large
cuda train mobilenet_v3_large                 ERROR:root:unhandled error
Traceback (most recent call last):
  File "/opt/pytorch/torchdynamo/benchmarks/common.py", line 879, in run_one_model
    new_result = model_iter_fn(model, example_inputs)
  File "benchmarks/torchbench.py", line 366, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/torchbench.py", line 366, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/torchbench.py", line 370, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/pytorch/vision/torchvision/models/mobilenetv3.py", line 235, in forward
    def forward(self, x: Tensor) -> Tensor:
  File "/opt/pytorch/torchdynamo/torchdynamo/eval_frame.py", line 94, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/functorch/functorch/_src/aot_autograd.py", line 696, in forward
    return compiled_f(
  File "/opt/pytorch/torchdynamo/torchdynamo/eval_frame.py", line 94, in _fn
    return fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/functorch/functorch/_src/aot_autograd.py", line 246, in forward
    fw_outs = normalize_as_list(compiled_fw(*flat_tensor_args))
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 655, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/opt/pytorch/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.40", line 63, in forward
    fused_28 = self.fused_28(to_dtype)
  File "/opt/pytorch/pytorch/torch/fx/graph_module.py", line 655, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/passes/backends/nvfuser.py", line 251, in lower_to_prims_and_execute
    DecompositionInterpreter(graph_module, prim_graph, decomposition_table=aten2prim_decomp).run(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 496, in run
    return super().run(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 129, in run
    self.env[node] = self.run_node(node)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 166, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/interpreter.py", line 238, in call_function
    return target(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 56, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 307, in __torch_dispatch__
    return func_overload(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_ops.py", line 56, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 404, in __torch_dispatch__
    return proxy_call(self, func_overload, args, kwargs)
  File "/opt/pytorch/pytorch/torch/fx/experimental/proxy_tensor.py", line 147, in proxy_call
    return CURRENT_DECOMPOSITION_TABLE[func_overload](*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_prims_common/wrappers.py", line 206, in _fn
    result = fn(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/_prims_common/wrappers.py", line 108, in _fn
    promoted_args = {
  File "/opt/pytorch/pytorch/torch/_prims_common/wrappers.py", line 109, in <dictcomp>
    x: _maybe_convert_to_dtype(bound.arguments[x], compute_dtype)
  File "/opt/pytorch/pytorch/torch/_prims_common/wrappers.py", line 35, in _maybe_convert_to_dtype
    raise ValueError(
ValueError: Received type <class 'NoneType'> that is neither a tensor or a number!
ERROR
ERROR
cuda               gmean=nanx mean=nanx
mobilenet_v3_large gmean=nanx mean=nanx
0                  gmean=nanx mean=nanx
0.0000             gmean=nanx mean=nanx
```

Env:

- V100, cuda 11.7
- torch_commit: https://github.com/pytorch/pytorch/commit/b4b60c2a2e423f49d81d7d634de6ead5c77d3640
- torchbench_commit: https://github.com/pytorch/benchmark/commit/97393f44bb8ddb9c52e86e982a99abf6d35047f7
- torchdynamo_commit: https://github.com/pytorch/torchdynamo/commit/7b039ccbfdef2f4a50b9155ed5e8e1fd4a882664
- torchvision_commit: https://github.com/pytorch/vision/commit/1d0786b0a35661408388ed4268e382f56bcde627

### PR DESCRIPTION
**Pull request by IvanYashchuk**
Fixes https://github.com/pytorch/torchdynamo/issues/759

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Test failures (or rather, unexpected successes) are real

**Comment by IvanYashchuk** [comment]
XLA fails now:
```
ERROR [0.011s]: test_reference_eager_clamp_xla_float32 (__main__.TestOpInfoXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 814, in test_wrapper
    return test(*args, **kwargs)
  File "/var/lib/jenkins/workspace/xla/test/test_ops.py", line 411, in test_reference_eager
    self.compare_with_eager_reference(op, sample_input)
  File "/var/lib/jenkins/workspace/xla/test/test_ops.py", line 397, in compare_with_eager_reference
    cpu_inp, cpu_args, cpu_kwargs = cpu(sample_input)
  File "/var/lib/jenkins/workspace/xla/test/test_ops.py", line 393, in cpu
    sample.args), to_cpu(sample.kwargs)
  File "/var/lib/jenkins/workspace/xla/test/test_ops.py", line 384, in to_cpu
    return tuple(map(to_cpu, x))
  File "/var/lib/jenkins/workspace/xla/test/test_ops.py", line 390, in to_cpu
    raise ValueError("Unknown type {0}!".format(type(x)))
ValueError: Unknown type <class 'NoneType'>!
```

**Comment by IvanYashchuk** [comment]
@JackCaoG this PR introduces a change to sample inputs of `clamp` that verifies that `clamp` correctly handles None arguments. There's a failure in xla tests try to move `None` object to CPU: https://github.com/pytorch/pytorch/pull/83586#issuecomment-1218347078.

**Comment by JackCaoG** [comment]
@IvanYashchuk Thanks, I will try to take a look!

**Comment by IvanYashchuk** [comment]
@JackCaoG should https://github.com/pytorch/xla/pull/3912 be merged first? Or what's the usual procedure?

**Comment by JackCaoG** [comment]
@IvanYashchuk so it works like this

You rebase and update https://github.com/pytorch/pytorch/blob/master/.github/ci_commit_pins/xla.txt of this pr to `fix_upstream_break_83586` (branch of xla pr that has the fix) and merge this pr.

I will merge the xla pr after this pytorch pr merged.

**Pull request closed without merging**
