### PR TITLE
Refactor structured set_output in Register{DispatchKey}.cpp

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #62188

These parts of the `set_output` code are identical for all operators in the
kernel registration files. So, this moves them from being copied into every
class to two helper functions at the top of the file.

Differential Revision: [D29962045](https://our.internmc.facebook.com/intern/diff/D29962045)

### CODE REVIEW

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29962045).

**Comment by ezyang** [comment]
Just to confirm, the goals of this PR are to:

* Reduce compilation time, by reducing the amount of code in the generated files
* Reduce binary size, by placing common code in single function that doesn't get inlined

I kind of wish that these helpers were just honest to goodness functions that we were calling (there would be some duplication here, but maybe it is mild? Curious what your opinion is). This PR seems to be an improvement, except for the additional complication of more code generation logic.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@albanD are you landing this stack?

**Comment by peterbell10** [comment]
>Can you show the before and after generated code

Here is the before without an `out` argument:

```cpp
    void set_output(int64_t output_idx, IntArrayRef sizes, IntArrayRef strides,
                    TensorOptions options, DimnameList names) override {


        if (strides.empty()) {
            outputs_[output_idx] = at::native::empty_cpu(sizes, optTypeMetaToScalarType(options.dtype_opt()), options.layout_opt(), options.device_opt(), options.pinned_memory_opt(), options.memory_format_opt());
        } else {
            // TODO: assert options.memory_format_opt() is nullopt (debug only?)
            outputs_[output_idx] = at::native::empty_strided_cpu(sizes, strides, optTypeMetaToScalarType(options.dtype_opt()), options.layout_opt(), options.device_opt(), options.pinned_memory_opt());
        }

        if (!names.empty()) {
          namedinference::propagate_names(*outputs_[output_idx], names);
        }
        // super must happen after, so that downstream can use maybe_get_output
        // to retrieve the output
        at::native::structured_add_out::set_output(output_idx, sizes, strides, options, names);
    }
```
and the after
```cpp
    void set_output(int64_t output_idx, IntArrayRef sizes, IntArrayRef strides,
                    TensorOptions options, DimnameList names) override {

        outputs_[output_idx] = create_out(sizes, strides, options);
        if (!names.empty()) {
          namedinference::propagate_names(*outputs_[output_idx], names);
        }
        // super must happen after, so that downstream can use maybe_get_output
        // to retrieve the output
        at::native::structured_add_out::set_output(output_idx, sizes, strides, options, names);
    }
```

Here is the before with an `out` argument
```cpp
    void set_output(int64_t output_idx, IntArrayRef sizes, IntArrayRef strides,
                    TensorOptions options, DimnameList names) override {

        const auto& out = outputs_[output_idx].get();
        TORCH_CHECK(options.dtype() == out.dtype(),
            "Expected out tensor to have dtype ", options.dtype(), ", but got ", out.dtype(), " instead");
        TORCH_CHECK(options.device() == out.device(),
            "Expected out tensor to have device ", options.device(), ", but got ", out.device(), " instead");
        bool resized = at::native::resize_output(outputs_[output_idx], sizes);
        // Only restride if a resize occurred; otherwise we ignore the (advisory)
        // strides from the meta function and directly use the output tensor's
        // preexisting strides
        if (resized) {
            if (!strides.empty()) {
                TORCH_INTERNAL_ASSERT(!options.memory_format_opt().has_value());
                at::native::as_strided_(outputs_[output_idx], sizes, strides);
            } else if (options.memory_format_opt().has_value()) {
                outputs_[output_idx].get().unsafeGetTensorImpl()->empty_tensor_restride(*options.memory_format_opt());
            }
        }

        if (!names.empty()) {
          namedinference::propagate_names(outputs_[output_idx], names);
        }
        // super must happen after, so that downstream can use maybe_get_output
        // to retrieve the output
        at::native::structured_add_out::set_output(output_idx, sizes, strides, options, names);
    }

```
and after
```cpp
    void set_output(int64_t output_idx, IntArrayRef sizes, IntArrayRef strides,
                    TensorOptions options, DimnameList names) override {

        const auto& out = outputs_[output_idx].get();
        resize_out(out, sizes, strides, options);
        if (!names.empty()) {
          namedinference::propagate_names(outputs_[output_idx], names);
        }
        // super must happen after, so that downstream can use maybe_get_output
        // to retrieve the output
        at::native::structured_add_out::set_output(output_idx, sizes, strides, options, names);
    }
```

**Comment by peterbell10** [comment]
The called functions are identical to the before code, they just either accept `out` as an argument for `resize_out` or return the new tensor in the case of `create_out`.

>Just to confirm, the goals of this PR are to:
>
>  - Reduce compilation time, by reducing the amount of code in the generated files
>  - Reduce binary size, by placing common code in single function that doesn't get inlined

Yes, that's the idea. IMO it also makes the generated code a bit more readable, but that's up to taste.

>I kind of wish that these helpers were just honest to goodness functions that we were calling (there would be some duplication here, but maybe it is mild? Curious what your opinion is).

That would be nice, I kept it in codegen as I thought the PR would be easier to review. You can see that the `if-else` chains are exactly the same for example.

**Comment by albanD** [comment]
@ezyang yes I will land this. I was waiting on the reviews.

cc @peterbell10 could you rebase on top of master please?

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29962045).

**Pull request closed without merging**
