### PR TITLE
[functorch] follow-up vmapjvpvjp

### PR DESCRIPTION
**Pull request by kshitij12345**
Ref 1: https://github.com/pytorch/pytorch/pull/83375#discussion_r970046113
Ref 2: https://github.com/pytorch/pytorch/pull/83375#discussion_r970047848

### CODE REVIEW

**Comment by kshitij12345** [comment]
CI Failures look irrelevant.

**Comment by zou3519** [comment]
I don't seem to see a fix for https://github.com/pytorch/pytorch/pull/83375#discussion_r970047848, is this intentional?

**Comment by kshitij12345** [comment]
Sorry. Seems like I forgot to commit that change.

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
