### PR TITLE
Store FakeTensor under real tracing mode for placeholders.

### PR DESCRIPTION
**Pull request by zhxchen17**
Summary:
Storing the original input for tracing the graph has two advantages:
1. It's easier for debugging if the compilation process fail and we want to get the original data generating this graph.
2. Since GraphModule is the main exchange data structure in lowering pipeline, it's easier to restore the original input during retracing.

Test Plan: CI

Differential Revision: D39224822

### CODE REVIEW

**Review by angelayi — APPROVED** [review]

**Review by Chillee — CHANGES_REQUESTED** [review]
This is gonna be problematic. We don't want to store arguments on the graph every time we trace.

Why can't you just use the metadata that's stored on the placeholders?

**Comment by zhxchen17** [comment]
@Chillee 

1. Because under different tracing modes (real/symbolic) we got different type of metadata (FakeTensor vs TensorMeta) which is hard to work with, and we will use both real and symbolic mode for a while. 
2. We got a bunch of passes written in interpreter style with real data, and in the short term using FakeTensor doesn't guarantee to work during retracing.

I don't quite understand, is there memory / performance concern for tracing if we record the trace arguments? How exactly it will be problematic?

**Comment by zhxchen17** [comment]
That being said, suppose placeholder always has FakeTensor metadata regardless of tracing mode (i.e. real), I can do some experiment to test whether that work for our retracing passes. Although I don't have high confidence that will work without out of the box :P

**Comment by Chillee** [comment]
We can just always store tensormeta regardless of how we’re tracing.

The big problem with saving the actual values on the graphs is that this can cause a significant increase in memory usage.

**Comment by Chillee** [comment]
@zhxchen17 hmm... I suppose that might work. Do you want to modify `proxy_tensor.py` to do that?

**Comment by zhxchen17** [comment]
> @zhxchen17 hmm... I suppose that might work. Do you want to modify `proxy_tensor.py` to do that?

@Chillee yep, I can try that in this diff.

**Comment by zhxchen17** [comment]
Close this for now since it's tricky to get it working in all cases.

**Pull request closed without merging**
