### PR TITLE
[benchmark][compile] Limit number of bounding boxes to 5

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #103442
* __->__ #103413

Depends on https://github.com/pytorch/benchmark/pull/1729

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @msaroufim

### CODE REVIEW

**Comment by anijain2305** [comment]
@ezyang Is this acceptable?

**Review by ezyang — APPROVED** [review]
It's a little dodgy but I guess if we don't have any better ideas

**Comment by anijain2305** [comment]
Pending on merge of - https://github.com/pytorch/pytorch/pull/103488 as moco should pass after that

**Pull request closed without merging**
