### PR TITLE
[Profiler][1/N] add profiler support for custom device.

### PR DESCRIPTION
**Pull request by NmomoN**
1. `torch.autograd.profiler` interface parameters changed. (use `self.use_device` instead of `self.use_cuda` facilitates access by other devices and integrate it in subsequent pr)
2. Modify `ProfilerEventStub`(aka `std::shared_ptr<CUevent_st>`) to `ProfilerVoidEventStub`(aka `std::shared_ptr<void>`) so that `ProfilerStubs` can be inherited by any `{device}Methods`. 
In addition, `cuda_event_start_` is renamed to `device_event_start_` , cuda and other devices can use this event pointer if needed.
4. custom device support using legacy profiling(add `ProfilerState::KINETO_PRIVATEUSE1_FALLBACK` option)
5. add `privateuse1Stubs` register
(parse results and test cases are added in subsequent pr)

cc @robieta @chaekit @aaronenyeshi @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

### CODE REVIEW

**Comment by heidongxianhua** [comment]
@albanD @soulitzer  sorry to bother, could you take a look ?

**Review by aaronenyeshi — CHANGES_REQUESTED** [review]
A couple of questions:
1) Since self.use_cuda is a deprecated API, replaced by `activities`, I don't think we should introduce new APIs like use_device into the profiler interface. See: https://pytorch.org/docs/stable/profiler.html
2) Why is the new device name PRIVATEUSE1? If you are using this for a private use-case, can you fork Pytorch and make the changes on your own repository fork?
3) If your device is public, I would suggest you add it into pytorch/kineto first, similar to Intel, AMD, and MTIA. Kineto has the ability to add your child profilers there.

cc @briancoutinho , @davidberard98

**Comment by NmomoN** [comment]
> A couple of questions:
> 
> 1. Since self.use_cuda is a deprecated API, replaced by `activities`, I don't think we should introduce new APIs like use_device into the profiler interface. See: https://pytorch.org/docs/stable/profiler.html
> 2. Why is the new device name PRIVATEUSE1? If you are using this for a private use-case, can you fork Pytorch and make the changes on your own repository fork?
> 3. If your device is public, I would suggest you add it into pytorch/kineto first, similar to Intel, AMD, and MTIA. Kineto has the ability to add your child profilers there.
> 
> cc @briancoutinho , @davidberard98

Thank you for your reply. For the first point, I noticed that activities are used instead of  self.use_cuda in `torch.profiler`, but `torch.autograd.profiler` has no deprecated instructions. I can also modify this part if necessary.

Our device is public and depends on the  `PrivateUse1`  provided by the community to implement corresponding functions.
In the `profiler` module, the mechanism of PrivateUse1 is incomplete and can't support more third-party devices. So we want to provide this part of the ability.

Of course, adaptation to pytorch/kineto is in our follow-up plan.

**Review by aaronenyeshi — APPROVED** [review]
Caught up on PrivateUse1 backend, and this patch looks good to me. Thanks for the explanation.

**Pull request closed without merging**
