### PR TITLE
[torch.library] Fix some docstrings

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #110214

Removed some erroneous colons

Test Plan:
- code reading

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
get the docstrings working with xdoctest? :) cc @Erotemic

**Comment by ezyang** [comment]
get the docstrings working with xdoctest? :) cc @Erotemic

**Comment by Erotemic** [comment]
The line above this change is not valid Python:

```python
lib.define("mylibrary::custom_linear(Tensor x, Tensor weight, Tensor bias)"
```

When I tried to run the doctest locally I got: 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 6
      3 from torch import Tensor
      5 # Example 1: an operator without data-dependent output shape
----> 6 lib = torch.library.Library("mylibrary", "FRAGMENT")
      7 lib.define("mylibrary::custom_linear(Tensor x, Tensor weight, Tensor bias)")

File ~/.pyenv/versions/3.11.2/envs/pyenv3.11.2/lib/python3.11/site-packages/torch/library.py:34, in Library.__init__(self, ns, kind, dispatch_key)
     32 def __init__(self, ns, kind, dispatch_key=""):
     33     if kind != "IMPL" and kind != "DEF":
---> 34         raise ValueError("Unsupported kind: ", kind)
     36     if ns in _reserved_namespaces and kind == "DEF":
     37         raise ValueError(ns, " is a reserved namespace. Please try creating a library with another name.")

ValueError: ('Unsupported kind: ', 'FRAGMENT')
```

but I'm running version `2.0.0+cu117`, so maybe this feature isn't testable in my implementation.

Are the doctests in this module not running?

**Comment by zou3519** [comment]
> The line above this change is not valid Python:

Thanks, I fixed the examples.

> Are the doctests in this module not running?

I'm not sure, are these automatic?

**Comment by Erotemic** [comment]
The code that runs the doctests is here: https://github.com/pytorch/pytorch/blob/main/test/run_test.py#L801

IIRC any new doctests should run automatically. If that's not happening let me know.

**Pull request closed without merging**
