### PR TITLE
[aot_inductor] move CudaWrapperCodeGen into a separate file

### PR DESCRIPTION
**Pull request by chenyang78**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #119871
* __->__ #119870

This reverts commit 3ab08946d5052eaeda11d683d6a58e801a032755.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @kadeng @muchulee8 @aakhundov @ColinPeppler

Differential Revision: [D53817852](https://our.internmc.facebook.com/intern/diff/D53817852)

### CODE REVIEW

**Comment by desertfire** [comment]
Looks like there are still rocm test failures.

**Comment by chenyang78** [comment]
> Looks like there are still rocm test failures.

@desertfire I think it's not caused by this PR

"You can merge normally! (1 Unrelated Failure)
BROKEN TRUNK - The following job failed but were present on the merge base:"

I also went through the error messages, which didn't look relevant to the PR. Thanks.

**Comment by chenyang78** [comment]
@chenyang78 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D53817852).

**Review by khabinov — APPROVED** [review]

**Comment by chenyang78** [comment]
@chenyang78 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D53817852).

**Pull request closed without merging**
