### PR TITLE
[ROCM][CUDA][NCCL] Disable `test_lowering_one_shot_all_reduce` on ROCM

### PR DESCRIPTION
**Pull request by eqy**
I'm not sure this is expected to run if it requires buffer-registration support CC @yifuwang @huydhn @syed-ahmed #138029

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @ptrblck @msaroufim @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
Thank you for the fix!

**Review by yifuwang — APPROVED** [review]

**Comment by yifuwang** [comment]
Thanks for the fix!

**Pull request closed without merging**
