### PR TITLE
[cuDNN] Enable cuDNN Frontend v8 API by Default

### PR DESCRIPTION
**Pull request by eqy**
#58414

Opening this PR for testing for now to check CI status. 🤞

CC @ptrblck @ngimel

### CODE REVIEW

**Comment by eqy** [comment]
3D convolution fusion test failures look real, will loop in cuDNN team to investigate

**Review by ngimel — APPROVED** [review]

**Comment by eqy** [comment]
I saw some failures in functorch conv tests that I was able to reproduce locally on `sm_52`, but running them as standalone tests didn't seem to resurface the failures... will recheck...

**Pull request closed without merging**
