### PR TITLE
[Intel GPU]device guard codegen for XPU

### PR DESCRIPTION
**Pull request by ZhiweiYan-96**
This PR is a supplement to #130082. The previous PR  #130082 fulfill the basic functionality of codegen, while we found it fails to handle the device sameness check in lots of uts.  Current PR is aimed to facilitate the XPU device guard code generation.

With current PR, the code snippet in `RegisterXPU.cpp` is as follows, where we can see the device guard is successfully generated.
```c++
namespace {
at::Tensor & wrapper_XPU_Tensor_float_out_normal_out(const at::Tensor & mean, double std, ::std::optional<at::Generator> generator, at::Tensor & out) {
  std::optional<Device> common_device = std::nullopt;
(void)common_device; // Suppress unused variable warning
  c10::impl::check_and_update_common_device(common_device, out, "wrapper_XPU_Tensor_float_out_normal_out", "out");
  c10::impl::check_and_update_common_device(common_device, mean, "wrapper_XPU_Tensor_float_out_normal_out", "mean");
  const OptionalDeviceGuard device_guard(device_of(out));
  return at::native::normal_out(mean, std, generator, out);
}
} // anonymous namespace
```
Nevertheless, without current change, the generated code is 
```c++
namespace {
at::Tensor & wrapper_XPU_Tensor_float_out_normal_out(const at::Tensor & mean, double std, ::std::optional<at::Generator> generator, at::Tensor & out) {
    // No device check
  // DeviceGuard omitted
  return at::native::normal_out(mean, std, generator, out);
}
} // anonymous namespace
```

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #133980

### CODE REVIEW

**Comment by EikanWang** [comment]
@ZhiweiYan-96 , please add a detailed description to explain why Intel GPU requires such changes. In addition, please make your PR simple enough.

**Review by EikanWang — CHANGES_REQUESTED** [review]
I prefer to split this PR into two PRs.
- torchgen/gen.py and torchgen/model.py are a single PR
- TensorAdvancedIndexing.cpp is another PR. In addition, it is better to merge #134072 to this PR.

**Comment by ZhiweiYan-96** [comment]
@EikanWang  Thanks for your suggestion! I have append our background information into to the PR description. The changes for indexing is separated into the PR https://github.com/pytorch/pytorch/pull/134072/files here.

**Review by EikanWang — APPROVED** [review]

**Comment by EikanWang** [comment]
@atalman , @malfet may I know if you have comments regarding this PR?

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
