### PR TITLE
Reland "[RPC] Use qualified name str directly in RPC torch script code path"

### PR DESCRIPTION
**Pull request by xush6528**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#34962 Reland "[RPC] Use qualified name str directly in RPC torch script code path"**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D7778113/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #34988 [RPC] Add to confirmed users immediately if the fork is shared from owner, instead of adding to pending users first&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D7735909/)

Relanding #34733. Fix is in https://github.com/pytorch/pytorch/pull/34988.

Differential Revision: [D7778113](https://our.internmc.facebook.com/intern/diff/D7778113/)

### CODE REVIEW

**Comment by mrshenli** [comment]
This is reverting #34733

**Review by jjlilley — APPROVED** [review]

**Review by mrshenli — APPROVED** [review]

**Comment by mruberry** [comment]
Unlanding. This appears to be causing several build failures. Some builds are timing out, others are failing in: 

```
Mar 19 09:33:09 ======================================================================
Mar 19 09:33:09 FAIL [1.319s]: test_multiple_backward_with_errors (__main__.DistAutogradTestWithSpawn)
Mar 19 09:33:09 ----------------------------------------------------------------------
Mar 19 09:33:09 Traceback (most recent call last):
Mar 19 09:33:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 175, in wrapper
Mar 19 09:33:09     self._join_processes(fn)
Mar 19 09:33:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 285, in _join_processes
Mar 19 09:33:09     self._check_return_codes(elapsed_time)
Mar 19 09:33:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 328, in _check_return_codes
Mar 19 09:33:09     self.assertEqual(first_process.exitcode, 0)
Mar 19 09:33:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 915, in assertEqual
Mar 19 09:33:09     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
Mar 19 09:33:09 AssertionError: 1 not less than or equal to 1e-05 : 
```

**Comment by mrshenli** [comment]
Thanks @mruberry!

**Comment by mrshenli** [comment]
Link for the failed test, which only runs on master

https://app.circleci.com/pipelines/github/pytorch/pytorch/142234/workflows/3cf53330-e3b2-43fb-ada1-2a9a4c78e62e/jobs/4870006

**Pull request closed without merging**
