### PR TITLE
[Pytorch] Remove assumption forward exists in freeze_module

### PR DESCRIPTION
**Pull request by JacobSzwejbka**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#52918 [Pytorch] Remove assumption forward exists in freeze_module**

Freeze_module seems to operate under the assumption that forward always exists. This isnt true, so the change first checks for existence then retrieves the function.

Differential Revision: [D26671815](https://our.internmc.facebook.com/intern/diff/D26671815/)

### CODE REVIEW

**Review by eellison — CHANGES_REQUESTED** [review]
I want to review before landing

**Review by eellison — COMMENTED** [review]
Can you add a test? I didnt even think this was possible, I thought we error if you don't define a forward method.

**Comment by JacobSzwejbka** [comment]
> Can you add a test? I didnt even think this was possible, I thought we error if you don't define a forward method.

Added a test. There's nothing intrinsic to the TorchScript that requires one to be defined, its just weird when someone doesn't.

**Review by eellison — APPROVED** [review]
LGTM

**Pull request closed without merging**
