### PR TITLE
Make is_contiguous checks generic in number of arguments

### PR DESCRIPTION
**Pull request by colesbury**
Loops.h has contains specializations for cases where all the inputs are
contiguous as well as cases where one input is a scalar and all other
inputs are contiguous.

Previously, there were separate checks for each functions that take
zero, one, or two input arguments. This is getting unwieldy, especially
once we add support for functions that take three inputs (#21025).

This requires the use of recursive templates (which have their own
downsides), but this seems better than the alternative.

### CODE REVIEW

**Review by VitalyFedyunin — APPROVED** [review]
Look good, can you please attach benchmarks if you have any.

**Comment by colesbury** [comment]
Good point. The performance measurements uncovered a bug in `is_contiguous_scalar`, which prevented the "scalar" specializations from running. (It didn't fail any unit tests because the behavior was still "correct" but slow)

With the fix the performance is now the same for various torch.add operations:
https://gist.github.com/colesbury/262cfbde62b1ab60a1029a53eaca6a0d

The generated assembly for the "hot loop" is also unchanged between master and the PR (other then jmp addresses):
https://gist.github.com/colesbury/088f748044380a31338de674aa28a434

**Pull request closed without merging**
