### PR TITLE
[AOTI][refactor] Remove is_legacy_abi_kernel and abi_compatible_kernel

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #121745
* #121744
* #121743
* __->__ #121523

Summary: is_legacy_abi_kernel was used for _scaled_dot_product_flash_attention fallback. It is only needed for C shim kernel name matching now, and the name matching is done with a direct string comparison. Also consolidate the fallback cpp kernel naming logic in CppWrapperCpu.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @chauhang

Differential Revision: [D54727789](https://our.internmc.facebook.com/intern/diff/D54727789)

### CODE REVIEW

**Comment by desertfire** [comment]
Reland https://github.com/pytorch/pytorch/pull/121346 as oss and fbcode is out of sync and there is a conflict. Landing from OSS instead.

**Review by chenyang78 — APPROVED** [review]
LGTM. Thanks!

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54727789).

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54727789).

**Pull request closed without merging**
