### PR TITLE
Add non-RAII setter/getter for LocalTensorTypeSet

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#29592 Add non-RAII setter/getter for LocalTensorTypeSet**

Differential Revision: [D18437212](https://our.internmc.facebook.com/intern/diff/D18437212/)

### CODE REVIEW

**Comment by mcarilli** [comment]
This definitely helps, but I'm excluding a specific TensorTypeId, so I'll have to wrap this in a bit of boilerplate, ie
```
tls_set_local_excluded_tensor_type_set(tls_get_local_excluded_tensor_type_set().add(AutocastTensorId))
```
Would you accept a quick followup PR, which I'm happy to implement, with four additional overloads that accept TensorTypeIds directly and include the boilerplate above?

**Comment by ezyang** [comment]
@mcarilli I decided not to offer this interface, because there is a hazard. Suppose I enable AMP, and then inside this scope I enable AMP again. If you write this using `add` and `remove`, you'll incorrectly `remove` when you exit the inner scope. The correct pattern is to save what the previous value was and reset to that. This is one of the reasons why I only provided the RAII interface initially, because I wanted to make it harder for people to get this wrong.

**Comment by mcarilli** [comment]
grad_mode uses state-setters that are hazardous in this way, but [deals with it on the Python side](https://github.com/pytorch/pytorch/blob/master/torch/autograd/grad_mode.py#L37-L43).

I'm [juggling the state the same way as grad_mode](https://github.com/pytorch/pytorch/pull/29552/files#diff-a1de48fa6e501bdd6309e608ffb03e4fR17-R28).  I'm not arguing strongly in favor of the raw interface you've PRed here, but in order to allow the context manager/stateful regions of autocasting, I effectively [rigged same thing by allocating/deallocating a guard instance that survives past scopes](https://www.youtube.com/watch?v=IhtA3Dm_o7s).

**Comment by ezyang** [comment]
Yeah, so I think an alternative API we could give is something like:

```
bool tls_is_tensor_type_id_excluded(TensorTypeId)
void tls_set_tensor_type_id_excluded(TensorTypeId, bool)
```

If you like this better we can redo the patch to do it this way.

**Comment by mcarilli** [comment]
@ezyang That would definitely match my use case, but your original concern is still valid: maybe you don't want to expose an API that implies such usage is blessed.  Maybe you want to force troublemakers like me to think hard about workarounds for cross-scope statefulness, to make sure we think hard whether that's what we really want.

Honestly it's up to you.  My PR works with its workaround, and switching the mode occurs rarely enough that allocating/deallocating the unique_ptr is not a performance concern IMO.

**Comment by ezyang** [comment]
obsoleted by mcarilli's version

**Pull request closed without merging**
