### PR TITLE
Add convnext_base to higher tolerance

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #142159

See https://github.com/pytorch/pytorch/issues/141498 https://github.com/pytorch/pytorch/issues/141703

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by bertmaher — APPROVED** [review]

**Comment by ezyang** [comment]
Perf run https://github.com/pytorch/pytorch/actions/runs/12186766248

**Review by huydhn — APPROVED** [review]

**Comment by ezyang** [comment]
```
cuda train convnext_base                      
W1205 21:12:33.370000 6007 site-packages/torch/_logging/_internal.py:1084] [6/0] Profiler function <class 'torch.autograd.profiler.record_function'> will be ignored
('Grad tensors ["L['self'].param_groups[0]['params'][0].grad", "L['self'].param_groups[0]['params'][33].grad", "L['self'].param_groups[0]['params'][64].grad", "L['self'].param_groups[0]['params'][311].grad"] will be copied during cudagraphs execution.If using cudagraphs and the grad tensor addresses will be the same across runs, use torch._dynamo.decorators.mark_static_address to elide this copy.',)
pass

```

**Pull request closed without merging**
