### PR TITLE
Improve error messages of `torch.testing.assert_close` in case of mismatching values

### LINKED ISSUE #58383: Improve error messages of `torch.testing.assert_close` in case of mismatching values
The current implementation of `torch.testing.assert_close` already does a good job at delivering information to the user in case of mismatching values. Still, I think they can be improved in multiple ways:

1. If a scalar (tensor) is compared, the error message currently looks like this:

    ```
    AssertionError: Tensors are not close!
    
    Mismatched elements: 1 / 1 (100.0%)
    Greatest absolute difference: 1.0 at 0 (up to 1e-05 allowed)
    Greatest relative difference: 0.5 at 0 (up to 1.3e-06 allowed)
    ```
    
    This can be improved in multiple ways:
    
    - The header should read "Scalars are not close!" to indicate that only a single value was involved in the comparison
    - The number of mismatched elements should be removed since it carries no information and always is `Mismatched elements: 1 / 1 (100.0%)`
    - The word "Greatest" should be removed from the reported absolute and relative differences, since there is only one difference each
    - The index should be removed since it carries no information and scalar tensors cannot accessed by index
    
    With these changes the error message could look like:
    
    ```
    AssertionError: Scalars are not close!
    
    Absolute difference: 1.0 at 0 (up to 1e-05 allowed)
    Relative difference: 0.5 at 0 (up to 1.3e-06 allowed)
    ```
2. The only differences between the messages for closeness and equality are that

    - the header reads "not close"  instead of "not equal" and
    - the allowed tolerances are appended to the differences.
    
    We could combine the two by making the message dependent on the value of the tolerances:
    - The header should read "equal" if `rtol == 0 and atol == 0` and
    - the allowed tolerance should only be added if `> 0`
    
    This would also allow us to make `assert_equal` a special case of `assert_close` (https://github.com/pytorch/pytorch/issues/56544#issuecomment-824003067) without further modification.
3. By default the numbers in the error message are formatted with the "General format" (`:g`). This might lead to diverging formats of two related numbers if they have different magnitudes:

    ```python
    abs_diff = 1e-4
    atol = 1e-5
    print(f"Absolute difference: {abs_diff} (up to {atol} allowed)")
    ```
    
    ```
    Absolute difference: 0.0001 (up to 1e-05 allowed)
    ```
    
    We should use a fixed number format, e.g, `:.2e` for floats and `:d` for integers.
4. Non-matching NaN's currently eliminate the difference information in the error message:

    ```
    a = torch.tensor(1.0, float("NaN"))
    b = torch.tensor(2.0, float("NaN"))
    torch.testing.assert_close(a, b)
    ```
    
    ```
    AssertionError: Tensors are not close!
    Mismatched elements: 2 / 2 (100.0%)
    Greatest absolute difference: nan at 1 (up to 1e-05 allowed)
    Greatest relative difference: nan at 1 (up to 1.3e-06 allowed)
    ```
    
    We should exclude NaN's from the difference calculation and for example add a line `Mismatched NaN's: ...` in case there are any.
5. `assert_close` allows to pass a callable as `msg` to construct an expressive error message. If a user just wants to add some information, for example the tested operator, it is currently impossible to do without losing all the benefits of our message generation. We should make our version public so others can build on top of it:
    
    ```python
    import torch.testing
    
    def my_msg(actual, expected, info):
        default_msg = torch.testing.default_mismatch_msg(actual, expected, info)
        return f"My important information: ... \n\n{default_msg}"
    
    torch.testing.assert_close(..., msg=my_msg)
    ```

### PR DESCRIPTION
**Pull request by pmeier**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #61031 remove UsageError in favor of ValueError
* #60639 change language from array to tensor
* #60638 relax type equality constraint
* #60637 Don't check stride by default
* #60636 Use maximum of tolerances in case of mismatching dtypes
* #60536 upcast to most precise dtype within their category before the comparison
* #60254 tests for diagnostics in callable `msg` in `torch.testing.assert_close`
* #60163 update docstring examples of `torch.testing.assert_close`
* **#60091 Improve error messages of `torch.testing.assert_close` in case of mismatching values**

Closes #58383. (1) and (2) are implemented. (3) was rejected. No consensus was reached on (4) and (5).

Improvements:

- Instead of calling everything "Tensors" we now use "Scalars" and "Tensor-likes" depending on the shape. Plus, we now internally have the option to adapt this identifier for example to report "Imaginary components of complex tensor-likes", which is even more expressive.
- The reported conditions "not close" and "not equal" are now determined based on `rtol` and `atol`.
- The number of mismatched elements and the offending indices are only reported in case the inputs are not scalar
- The allowed `rtol` and `atol` is only reported if `> 0`

**Example 1**

```python
torch.testing.assert_close(1, 3, rtol=0, atol=1)
```

Before:

```
AssertionError: Tensors are not close!

Mismatched elements: 1 / 1 (100.0%)
Greatest absolute difference: 2 at 0 (up to 1 allowed)
Greatest relative difference: 0.6666666865348816 at 0 (up to 0 allowed)
```

After:

```
AssertionError: Scalars are not close!

Absolute difference: 2 (up to 1 allowed)
Relative difference: 0.6666666865348816
```

**Example 2**

```python
torch.manual_seed(0)
t = torch.rand((2, 2), dtype=torch.complex64)
torch.testing.assert_close(t, t + complex(0, 1))
```

Before:

```
AssertionError: Tensors are not close!

Mismatched elements: 4 / 4 (100.0%)
Greatest absolute difference: 1.0000000596046448 at (0, 0) (up to 1e-05 allowed)
Greatest relative difference: 0.8833684352411922 at (0, 1) (up to 1.3e-06 allowed)

The failure occurred for the imaginary part.
```

After:

```
AssertionError: Imaginary components of tensor-likes are not close!

Mismatched elements: 4 / 4 (100.0%)
Greatest absolute difference: 1.0000000596046448 at index (0, 0) (up to 1e-05 allowed)
Greatest relative difference: 0.8833684352411922 at index (0, 1) (up to 1.3e-06 allowed)
```

Differential Revision: [D29556357](https://our.internmc.facebook.com/intern/diff/D29556357)

### CODE REVIEW

**Comment by mruberry** [comment]
> * Instead of calling everything "Tensors" we now use "Scalars" and "Tensor-likes" depending on the shape. 

Neat.


> Plus, we now internally have the option to adapt this identifier for example to report "Imaginary components of complex tensor-likes", which is even more expressive.

In the future we might change our complex comparisons to also just be a closeness check (and not validate the real and imaginary components separately) -- how would that future update work with this statement?

> * The reported conditions "not close" and "not equal" are now determined based on `rtol` and `atol`.

Sure. 

> * The number of mismatched elements and the offending indices are only reported in case the inputs are not scalar

This seems OK since the language is changing to indicate the comparison is between scalars.

> * The allowed `rtol` and `atol` is only reported if `> 0`

Won't this confused people? 

> ```
> AssertionError: Scalars are not close!
> Absolute difference: 2 (up to 1 allowed)
> Relative difference: 0.6666666865348816
> ```

When we compare two values are we imposing the stricter of atol and rtol? Isn't the close equation we're using weird and additive in both these things, so there's just an absolute difference to consider?

**Comment by pmeier** [comment]
> When we compare two values are we imposing the stricter of atol and rtol? Isn't the close equation we're using weird and additive in both these things, so there's just an absolute difference to consider?

Good point. We now either leave both out or report both. In the former case this should not be confusing, since the header in such a case reads "... are not equal!"

**Review by mruberry — APPROVED** [review]
Cool

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29556357).

**Pull request closed without merging**
