### PR TITLE
Change the parameter type from int to float in torch.nn.Softplus

### LINKED ISSUE #120175: nn.Softplus threshold & beta parameter are typed as int instead of float
### 📚 The doc issue

This is a docu / typing issue.

nn.Softplus hints beta/threshold as int, even though in reality it can be a float, which is way more useful than just allowing an integer (often, you want beta<1)
https://github.com/pytorch/pytorch/blob/372d078f361e726bb4ac0884ac334b04c58179ef/torch/nn/modules/activation.py#L853

This causes a) mypy errors in user code if using a float and b) leads to wrong documentation, giving the impression that only integer beta/threshold is allowed

The c-api uses double
https://github.com/pytorch/pytorch/blob/372d078f361e726bb4ac0884ac334b04c58179ef/torch/csrc/api/include/torch/nn/options/activation.h#L501-L506

### Suggest a potential alternative/fix

Switch to float type hints

cc @svekars @brycebortree @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### PR DESCRIPTION
**Pull request by lancerts**
Fixes #120175

1 The c_api uses the double
https://github.com/pytorch/pytorch/blob/f2cf0768d10df6eb578db734bf80f5281f7410ae/torch/csrc/api/include/torch/nn/options/activation.h#L501.

2 The type is also double in the test case
https://github.com/pytorch/pytorch/blob/f2cf0768d10df6eb578db734bf80f5281f7410ae/test/cpp/api/functional.cpp#L1788

3 With float parameter in python works perfectly fine
```
m = nn.Softplus(beta=0.1,threshold=1.2)
input = torch.randn(2)
output = m(input)

print(output)
tensor([7.3749, 7.6852])
```

### CODE REVIEW

**Review by mikaylagawarecki — APPROVED** [review]
Thanks!

You are right this seems to be just a doc issue as the [CPU](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cpu/Activation.cpp?fbclid=IwAR0_bNCocullwgCY_Fd14kpk4Pv-AIeVJf0P-6KsxALTHakQnDnTQfxKEQ0#L1065-L1066) and [CUDA](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cuda/ActivationSoftplusKernel.cu?fbclid=IwAR2jPcGL7S1jEEUfzCfMK2tz5E1qxCpm0lIyIVxRfvU44wmMuXkDgkBjRSY#L32-L34) implementations properly handle float

**Comment by mikaylagawarecki** [comment]
Hey sorry, could you fix lint please, from your `pytorch` directory run `make setup_lint` and `lintrunner -a`

**Comment by lancerts** [comment]
> Hey sorry, could you fix lint please, from your `pytorch` directory run `make setup_lint` and `lintrunner -a`

@mikaylagawarecki fixed the mypy arg issue.

**Comment by lancerts** [comment]
failing from disabled test or previously disabled test, irrelevant to the change

**Pull request closed without merging**
