### PR TITLE
[ONNX] Refactor UnsupportedOperatorError arguments

### LINKED ISSUE #82046: [ONNX] Op version agnostic symbolics
Currently we go back and forth from versioned symbolic functions to symbolic_helper that condition on the current opset version. A dispatching mechanism for separating versioning decisions from the symbolic mapping would make the symbolic functions easier to interpret.

Related: https://github.com/pytorch/pytorch/issues/78391

Reference: tf2onnx

### PR DESCRIPTION
**Pull request by justinchuby**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #85349

Merged the first two arguments because we always use qualified names to identify symbolic functions

### CODE REVIEW

**Review by BowenBao — COMMENTED** [review]
Is it handled elsewhere or are we not going to emit different message between official torch ops vs custom torch ops?

**Comment by justinchuby** [comment]
> Is it handled elsewhere or are we not going to emit different message between official torch ops vs custom torch ops?

@BowenBao I removed the behavior of emitting different messages. Do users ever register to domains that is not caffe2, aten, or quantized? If it ever happens, we can add the trace to the diagnostic engine?

**Comment by AllenTiTaiWang** [comment]
What is the `Unchanged files with check annotations Beta`

**Review by titaiwangms — APPROVED** [review]

**Comment by justinchuby** [comment]
They are failed checks from older PRs in this stack. I will be solving them

**Review by BowenBao — APPROVED** [review]

**Pull request closed without merging**
