### PR TITLE
[Quant] [PT2] Add SiLU  into X86InductorQuantizer Conv2d Unary Annotation

### PR DESCRIPTION
**Pull request by zhuhaozhe**
**Summary**
Add `SiLU` into X86InductorQuantizer Conv2d Unary Annotation

**TestPlan**
```
python -m pytest test_x86inductor_quantizer.py -k test_conv2d_unary
python -m pytest test_x86inductor_quantizer.py -k test_qat_conv2d_unary
```

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #122374
* #122373
* #122268
* __->__ #122267
* #122266

### CODE REVIEW

**Review by leslie-fang-intel — APPROVED** [review]

**Review by jgong5 — APPROVED** [review]

**Comment by jeanschmidt** [comment]
Seems that reverting does not fix issues in main, but I am reluctant to merge it back as there is a Lint error. Feel free to merge it if you believe this PR is good.

**Pull request closed without merging**
