### PR TITLE
fixing Optional[Tensor] type in autodiff

### LINKED ISSUE #54783: RuntimeError: kind_.is_prim()INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/ir.cpp":1110 from autodiff
## 🐛 Bug

```cpp
import torch

@torch.jit.script
def method1(x, weight, b1, b2):
    bias = b1 * b2
    return torch.nn.functional.linear(x, weight, bias)

M = 10
K = 10
N = 10

x = torch.rand(M, K, requires_grad=True)
weight = torch.rand(K, N, requires_grad=True)
b1 = torch.rand(M, N, requires_grad=True)
b2 = torch.rand(M, N, requires_grad=True)

method1(x, weight, b1, b2)
method1(x, weight, b1, b2)
```

produces an error: `RuntimeError: kind_.is_prim()INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/ir.cpp":1110, please report a bug to PyTorch. Only prim ops are allowed to not have a registered operator but aten::mul doesn't have one either. We don't know if this op has side effects.`

## To Reproduce

1. Run the test case above

## Expected behavior

Code runs and produces no errors

## Environment

 - PyTorch Version: 1.8+

## Additional context

cc @gmagogsfm

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #54783

We need to be extra careful with the pattern to legitimately use `unchecked_unwrap_optional` in autodiff.
This would at least allow us to start support `Optional[Tensor]` in autodiff, which is quite common in composite layers.

### CODE REVIEW

**Comment by jjsjann123** [comment]
In our offline discussion, I think we still have concerns about whether this is the right direction to go or not.
I'm pushing this PR to test water with CI. Also, we can temporarily use this as a WAR until we got a better solution. At least it will unblock some of incoming PRs to expand support of more ops in autodiff

**Comment by Krovatkin** [comment]
@jjsjann123 Could you please rebase this? I think, this PR is definitely an improvement over having an exception thrown, and for this specific case, `aten::linear` it's fairly simple to reason about the fix.

**Comment by Krovatkin** [comment]
@jjsjann123  could you please also add these tests: 

https://github.com/pytorch/pytorch/blob/29f142cb1271036969c3229155fa7166945181a9/test/jit/test_autodiff_subgraph_slicing.py#L54-L109

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Pull request closed without merging**
