### PR TITLE
[Inductor] First implementation of the B2B-GEMM pass with tests

### PR DESCRIPTION
**Pull request by sdingcn**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #129995

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by sdingcn** [comment]
The current version supports arbitrary matrix shapes for the pattern `((A @ B) @ C)` and is turned off by default. The unit tests inside `test/inductor/test_b2b_gemm.py` have passed, and it can demonstrate speed-up on some random matrices:
```
A[8192, 32] @ B[32, 8192] @ C[8192, 32]
Baseline: 0.2516176700592041
B2B_GEMM: 0.10584156960248947
```

**Comment by sdingcn** [comment]
Known TODOs:
* a complete performance tuning in `tuned_b2b_gemm` with corresponding size checks in `can_apply_b2b_gemm`
* handling more patterns, including epilogues, etc. in `register_graph_pattern`
* floating point error reductions

**Review by eellison — APPROVED** [review]
Looks good for initial land. As you mentioned for some follow ups:

```
(1) a complete performance tuning / configs with the corresponding matrix size check;
(2) matching more patterns, including epilogues, etc.;
(3) some other optimizations (floating point error reductions, etc.).
```

Other follows ups -

-  add `ExternKernelChoice` that just consists of b2b gemm for cases where aten is faster.
- support for pointwise nodes on intermediate
- Some heuristics about when we dispatch to this in first place

**Pull request closed without merging**
