### PR TITLE
[C10D] Ensure gil is not released when calling toPyBytes

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128212

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @yf225 @chauhang @d4l3k

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by wconstab** [comment]
i'm pretty sure this PR does not make things worse and may fix the issue reported in #125990, but i'm also not sure if it's a complete fix.  I just dove right into this fix based on @albanD's stacktrace in #125990. There are a couple things i wanted to look more closely at

1. TCPStore can be subclassed from python.  If the store instance is a python store, I don't understand the call flow through our init.cpp layer and i wonder if the `store.compareSet` call in the lambda in init.cpp will go back out to python.  If it does, will it reacquire the gil?  Where does this occur?
2. Other methods in this file- are we making similar mistakes? Need to do a thorough check.

**Comment by wconstab** [comment]
after reviewing a bit more of init.cpp it looks like compareSet was the outlier and many other tcpstore functions use the pattern of dropping the gil when calling into the store method, then reacquiring it before calling toPyBytes.  I updated my fix to use the same auto/lambda pattern as similar functions.  I think the fix is safe and we should land it.

**Review by XilunWu — APPROVED** [review]
Good that we found the outlier. Thx for the fix!

**Pull request closed without merging**
