### PR TITLE
Register decomposition for empty.memory_format into empty_strided

### PR DESCRIPTION
**Pull request by Anstow**

### CODE REVIEW

**Comment by bdhirsh** [comment]
maybe cc @lezcano (is there anyone else you think should take a look at ref/decomp tweaks?) - do you know why `empty()` here wasn't initially added as a decomp? Looks like the function was added in https://github.com/pytorch/pytorch/pull/77542

**Comment by lezcano** [comment]
I have no idea. I don't see any reason why it shouldn't be decomposed really.
In `native_functions.yaml` it's also marked as `core`... Perhaps @SS-JIA knows?

**Comment by SS-JIA** [comment]
Regarding why `empty.memory_format` is marked as `core`, I will refer to @SherlockNoMad on this. But if it makes sense to decompose `empty.memory_format`, then we can remove the `core` tag for the op.

One thing I'm curious about, this decomp determines the desired stride of the empty tensor based on the `MemoryFormat` provided using functions like [`make_contiguous_strides_for`](https://github.com/graphcore/pytorch-fork/blob/54c28c564f0f4da174358312a026398ebca5337c/torch/_prims_common/__init__.py#L1479), do these accept and return symbolic strides? That is to say, if a model containing `empty.memory_format` is exported with a specific shape, then will the decomposed to `empty` "lock in" the specific strides derived from the shape the model was exported with?

**Comment by lezcano** [comment]
They do support symbolic sizes, so I don't see any reason why we shouldn't empty into empty_strided. ping @ezyang in case I'm missing something, but yeah.

**Review by ezyang — CHANGES_REQUESTED** [review]
No. Do not pass go, do not collect $200.

We intentionally do not decompose empty because it is extremely hot (it is called everywhere) and the C++ implementation supports symbolic shapes. Decomposing to empty_strided also impedes downstream analysis as empty_strided is too flexible and you have to reverse engineer that you actually just wanted to allocate a plain contiguous tensor.

**Comment by Anstow** [comment]
Yep that would be a good reason not to decompose. Thanks for the explanation. Is that a good reason to get rid of this python function entirely and just call empty.memory_format here instead?

**Pull request closed without merging**
