### PR TITLE
updated pad_sequence type hint

### LINKED ISSUE #89623: [typing] `torch.nn.utils.rnn.pad_sequence` has too strict type hint.
### 🐛 Describe the bug

As per definition, it accepts `Tensor | list[Tensor]`.

https://github.com/pytorch/pytorch/blob/4f5c4c022a8365d06ac401582958bbf0fd3f8337/torch/nn/utils/rnn.py#L340-L344

However, the function body only requires `Tensor | Iterable[Tensor]`. Allowing `Iterable[Tensor]` would be nice so that generator expressions can be passed without raising type errors in `mypy`.

### Versions

master branch  / 1.13

cc @zou3519 @ezyang @malfet @rgommers @xuzhao9 @gramster

### PR DESCRIPTION
**Pull request by randolf-scholz**
Fixes #89623

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Thank you for the fix

**Review by zou3519 — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Comment by randolf-scholz** [comment]
Seems like a server failure: https://github.com/pytorch/pytorch/actions/runs/6111015232/job/16596880143#step:11:6007

**Pull request closed without merging**
