### PR TITLE
Convert TensorIterator to use function_ref, a lightweight alternative to std::function.

### PR DESCRIPTION
**Pull request by resistor**
function_ref is pulled over from LLVM.  It is to callables what StringRef is to strings.
This allows it to be substantially lighter weight, particularly in code size.  That comes
at the cost of not being usable in situations where the callable's lifetime is shorter
than the function_ref.  This means it is suitable for callback-like scenarios, but not
for situations where the callable needs to be stored.  In converting TensorIterator,
I only encountered one situation that required refactoring to comply with function_ref's
constraints.

In my local Release build, this reduces the size of libtorch by 4MB, from 70MB->66MB.

### CODE REVIEW

**Review by colesbury — APPROVED** [review]

**Review by VitalyFedyunin — APPROVED** [review]
Please attache performance numbers as well.

**Comment by resistor** [comment]
@VitalyFedyunin Any particular things you want me to test?

**Comment by resistor** [comment]
@VitalyFedyunin Benchmark results are in https://gist.github.com/resistor/65ddb4015d7fddfcb2e703fbe1557a6b

**Comment by VitalyFedyunin** [comment]
good to go, thanks!

**Pull request closed without merging**
