### PR TITLE
Add support for converting sparse bool tensors to dense

### LINKED ISSUE #49977: Failure when converting a sparse boolean tensor to a dense tensor
## 🐛 Bug

Converting a sparse boolean tensor to a dense tensor fails

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-183b7da37f3a> in <module>
----> 1 torch.tensor([True, False]).to_sparse().to_dense()

RuntimeError: "add_dense_sparse" not implemented for 'Bool'
```

## To Reproduce

```python
import torch

# raises exception
torch.tensor([True, False]).to_sparse().to_dense()
# RuntimeError

# converting via another type works
torch.tensor([True, False]).to_sparse().to(torch.uint8).to_dense().to(torch.bool)
# Out[6]: tensor([ True, False])
```

## Expected behavior

Conversion to succeed

## Environment
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.28)
CMake version: version 3.19.2

Python version: 3.9 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] Could not collect

cc @izdeby @aocsa @nikitaved @pearu @mruberry

### PR DESCRIPTION
**Pull request by NathanHowell**
Fixes #49977

### CODE REVIEW

**Comment by NathanHowell** [comment]
@facebook-github-bot  help

**Comment by NathanHowell** [comment]
@facebook-github-bot  cla

**Comment by NathanHowell** [comment]
@mruberry any chance you can kick that failed test?

**Review by ezyang — APPROVED** [review]
cc'ed mruberry in case he has testing guidance

**Comment by mruberry** [comment]
> cc'ed mruberry in case he has testing guidance

Looks OK to me. Our sparse test suite is a little wonky which means this test has to jump through some hoops it normally wouldn't, but it looks like it's jumping through the correct hoops.

**Pull request closed without merging**
