### PR TITLE
Add basic mypy annotations to dynamo

### PR DESCRIPTION
**Pull request by oulgen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #132416
* __->__ #132415

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by XuehaiPan — APPROVED** [review]

**Comment by oulgen** [comment]
Answered on https://github.com/pytorch/pytorch/pull/132416

**Review by jamesjwu — APPROVED** [review]

**Pull request closed without merging**
