### PR TITLE
[data] add autocompletion to datapipes

### PR DESCRIPTION
**Pull request by edward-io**
In REPLs (e.g. jupyter notebook) autocomplete now works:

image

even with custom data pipes:

image

Unfortunately I wasn't able to figure out how to get autocomplete to work for non-REPLs (e.g. VSCode) - may need to generate fake pyi stubs, which 1) won't work for custom datapipes and 2) is a larger project to tackle :)

### CODE REVIEW

**Review by ejguan — COMMENTED** [review]
The changes look good to me. Could you please remove the changes of submodules and fix mypy.

cc: @NivekT

**Review by NivekT — APPROVED** [review]
LGTM! @edward-io can you check if the autocomplete is still working with VSCode or PyCharm? I believe it should still work but it doesn't hurt to double check.

**Comment by edward-io** [comment]
@NivekT do you mean autocomplete for the actual methods like register_function, set_getstate_hook?

**Comment by NivekT** [comment]
> @NivekT do you mean autocomplete for the actual methods like register_function, set_getstate_hook? looks like it still works, it relies on the actual method signatures
> 
> image

I assume something like `.map`, `.batch` shows up in the drop down as well?

**Comment by edward-io** [comment]
> I assume something like .map, .batch shows up in the drop down as well?

I don't think this has ever been supported, which is the main reason for investigating. Let me know if thats not the case.

**Comment by edward-io** [comment]
discussed with @NivekT offline, he'll follow up with investigation on why pyi stubs aren't being generated properly in nightlies

@pytorchbot merge

**Pull request closed without merging**
