### PR TITLE
[dynamo] Simplify handling of `functools.wraps`

### LINKED ISSUE #134731: `tree_map_only` does not support closure when compile
### 🐛 Describe the bug

There is `torch._dynamo.exc.Unsupported: reconstruct: NewCellVariable()` when torch.compile a function with `tree_map_only` on closures. A minimal repro:

```python
import torch
from torch.utils._pytree import tree_map_only

# ===========
# Example 1
# ===========

class GroupedTensor:
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def __getitem__(self, index):
        mapped_attributes = tree_map_only(
            torch.Tensor,
            lambda x: x[index],
            (self.a, self.b),
        )
        return mapped_attributes

def getitem(grouped_tensor: GroupedTensor, index: torch.Tensor):
    return grouped_tensor[index]


grouped_tensor = GroupedTensor(torch.randn(4, 2, 5), torch.randn(4, 2,5,5))
compiled_fn = torch.compile(getitem, fullgraph=True)
compiled_fn(grouped_tensor, torch.tensor([2]))

# ===========
# Example 2
# ===========
def f(a, b, index):
    def call(index):
        mapped_attributes = tree_map_only(
            torch.Tensor,
            lambda x: x[index],
            (a, b),
        )
        return mapped_attributes
    return call(index)

a = torch.randn(4, 2, 5)
b = torch.randn(4, 2,5,5)
compiled_fn = torch.compile(f, fullgraph=True)
compiled_fn(a, b, torch.tensor([2]))
```

Error log:
```
Traceback (most recent call last):
  File "/data/users/boyuan/pytorch/torch/_dynamo/codegen.py", line 231, in __call__
    self.call_reconstruct(value)
  File "/data/users/boyuan/pytorch/torch/_dynamo/codegen.py", line 84, in call_reconstruct
    res = value.reconstruct(self)
  File "/data/users/boyuan/pytorch/torch/_dynamo/variables/base.py", line 271, in reconstruct
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/boyuan/playground/pt2/pytree_simpler.py", line 45, in <module>
    compiled_fn(a, b, torch.tensor([2]))
  File "/data/users/boyuan/pytorch/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/convert_frame.py", line 1245, in __call__
    return self._torchdynamo_orig_callable(
  File "/data/users/boyuan/pytorch/torch/_dynamo/convert_frame.py", line 517, in __call__
    return _compile(
  File "/data/users/boyuan/pytorch/torch/_dynamo/convert_frame.py", line 909, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/boyuan/pytorch/torch/_dynamo/convert_frame.py", line 657, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "/data/users/boyuan/pytorch/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/convert_frame.py", line 690, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/boyuan/pytorch/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/boyuan/pytorch/torch/_dynamo/convert_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/convert_frame.py", line 625, in transform
    tracer.run()
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 2796, in run
    super().run()
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 582, in wrapper
    return inner_fn(self, inst)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 1602, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 830, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/data/users/boyuan/pytorch/torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 836, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 3011, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 3139, in inline_call_
    tracer.run()
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 582, in wrapper
    return inner_fn(self, inst)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 1602, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 830, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/data/users/boyuan/pytorch/torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 836, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 3011, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 3139, in inline_call_
    tracer.run()
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 582, in wrapper
    return inner_fn(self, inst)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 1602, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 830, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/data/users/boyuan/pytorch/torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 836, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 3011, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 3139, in inline_call_
    tracer.run()
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 582, in wrapper
    return inner_fn(self, inst)
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 1602, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/users/boyuan/pytorch/torch/_dynamo/symbolic_convert.py", line 830, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/data/users/boyuan/pytorch/torch/_dynamo/variables/functions.py", line 678, in call_function
    args[0].source is not None or args[0].can_reconstruct(tx.output.root_tx)
  File "/data/users/boyuan/pytorch/torch/_dynamo/variables/base.py", line 281, in can_reconstruct
    self.reconstruct(cg)
  File "/data/users/boyuan/pytorch/torch/_dynamo/variables/functions.py", line 585, in reconstruct
    codegen(self.closure)
  File "/data/users/boyuan/pytorch/torch/_dynamo/codegen.py", line 231, in __call__
    self.call_reconstruct(value)
  File "/data/users/boyuan/pytorch/torch/_dynamo/codegen.py", line 84, in call_reconstruct
    res = value.reconstruct(self)
  File "/data/users/boyuan/pytorch/torch/_dynamo/variables/lists.py", line 516, in reconstruct
    codegen.foreach(self.items)
  File "/data/users/boyuan/pytorch/torch/_dynamo/codegen.py", line 263, in foreach
    self(i)
  File "/data/users/boyuan/pytorch/torch/_dynamo/codegen.py", line 233, in __call__
    unimplemented(f"reconstruct: {value}")
  File "/data/users/boyuan/pytorch/torch/_dynamo/exc.py", line 289, in unimplemented
    raise Unsupported(msg, case_name=case_name)
torch._dynamo.exc.Unsupported: reconstruct: NewCellVariable()

from user code:
   File "/home/boyuan/playground/pt2/pytree_simpler.py", line 40, in f
    return call(index)
  File "/home/boyuan/playground/pt2/pytree_simpler.py", line 34, in call
    mapped_attributes = tree_map_only(
  File "/data/users/boyuan/pytorch/torch/utils/_pytree.py", line 1136, in tree_map_only
    return tree_map(map_only(__type_or_types_or_pred)(func), tree, is_leaf=is_leaf)
  File "/data/users/boyuan/pytorch/torch/utils/_pytree.py", line 1079, in wrapper
    @functools.wraps(func)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

PyTorch version: 2.5.0a0+git84b3f19
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.34

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-0_fbk12_hardened_11583_g0bef9520ca2b-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.4.131
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100
GPU 1: NVIDIA H100
GPU 2: NVIDIA H100
GPU 3: NVIDIA H100

Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.9.1.1
/usr/lib64/libcudnn_adv.so.9.1.1
/usr/lib64/libcudnn_cnn.so.9.1.1
/usr/lib64/libcudnn_engines_precompiled.so.9.1.1
/usr/lib64/libcudnn_engines_runtime_compiled.so.9.1.1
/usr/lib64/libcudnn_graph.so.9.1.1
/usr/lib64/libcudnn_heuristic.so.9.1.1
/usr/lib64/libcudnn_ops.so.9.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          184
On-line CPU(s) list:             0-183
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 9654 96-Core Processor
CPU family:                      25
Model:                           17
Thread(s) per core:              1
Core(s) per socket:              184
Socket(s):                       1
Stepping:                        1
BogoMIPS:                        4792.80
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 clzero xsaveerptr wbnoinvd arat npt lbrv nrip_save tsc_scale vmcb_clean pausefilter pfthreshold v_vmsave_vmload vgif avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities
Virtualization:                  AMD-V
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       11.5 MiB (184 instances)
L1i cache:                       11.5 MiB (184 instances)
L2 cache:                        92 MiB (184 instances)
L3 cache:                        2.9 GiB (184 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-183
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.15.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] optree==0.12.1
[pip3] pytorch-triton==3.0.0+dedb7bdf33
[pip3] torch==2.5.0a0+gite45a76e
[conda] magma-cuda124             2.6.1                         1    pytorch
[conda] mkl-include               2024.2.1                 pypi_0    pypi
[conda] mkl-static                2024.2.1                 pypi_0    pypi
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] pytorch-triton            3.0.0+dedb7bdf33          pypi_0    pypi
[conda] torch                     2.5.0a0+gite45a76e           dev_0    <develop>
[conda] torchfix                  0.4.0                    pypi_0    pypi

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec

### LINKED ISSUE #141514: `functools.wraps` fails to wrap NestedUserFunctionVariable
### 🐛 Describe the bug

What the reproducer does is not important. It is just to reproduce the error encountered when `functools.wraps` is used in a nested function.

```python
import functools
import torch


def decorator(func):
    @functools.wraps(func)  # <--- works if one comment this line
    def helper(*args):
        return func(*args)
    return helper


def g(x):
    @decorator
    def h():
        return x * 100
    return h


def run(h):
    return h()


@torch.compile(fullgraph=True)
def fn(x):
    h = g(x)
    return run(h)


x = torch.randn(1)
y = fn(x)
print(x, y)
```

The error is coming from the `can_reconstruct` call here:
https://github.com/pytorch/pytorch/blob/83e36a6bfabcb177fd427efbc9527725d4555819/torch/_dynamo/variables/functions.py#L687-L693

### Versions

pytorch main branch

cc @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames

### PR DESCRIPTION
**Pull request by StrongerXi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #142014
* __->__ #142000

Previously when Dynamo encounters a `functools.wrap(...)` call, it would
check `VariableTracker.can_reconstruct` and graph break if failed.

That has 2 issues:
1. Implementation of `can_reconstruct` is incorrect, since logic of
   reconstructability isn't necessarily encapsulated in
   `VariableTracker.reconstruct` -- for some VTs like `CellVariable`,
   it's also in `SideEffects.codegen_save_tempvars`. This is exposed by
   #134731.
2. We don't always need to reconstruct the result of
   `functools.wrap(...)`, for those cases we don't want to give up
   tracing by an early `con_reconstruct` check. Instead we could just
   let it fall through, and graph break in the actual `reconstruct` call
   later, if needed.

This patch removes the `can_reconstruct` check altogether. It was
introduced in #114279, but the added tests pass even without the check
now; this might be because of some recent bug fixing on cells and side
effects.

Fixes #134731, #141514.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

D66838708

### CODE REVIEW

**Comment by StrongerXi** [comment]
Let's see what CI says.

**Review by zou3519 — APPROVED** [review]

**Comment by StrongerXi** [comment]
The new `test_tree_map` test is failing internally, in inductor. I'm investigating.

**Comment by StrongerXi** [comment]
@StrongerXi has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D66838247).

**Comment by StrongerXi** [comment]
@StrongerXi has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D66838247).

**Comment by StrongerXi** [comment]
@StrongerXi has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D66838247).

**Comment by StrongerXi** [comment]
@StrongerXi has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D66838708).

**Comment by StrongerXi** [comment]
@StrongerXi has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D66838708).

**Pull request closed without merging**
