### PR TITLE
If you have i0 = i1 * 12, perform this replacement directly

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #112653

In https://github.com/pytorch/pytorch/pull/112156 I added support for creating replacements on unbacked SymInts, so if you asserted that `i0 == s0`, we would replace i0 with s0 (only ever replacing unbacked with backed.)

However, if we have assertions involving only unbacked SymInts, we can also replace in this case! E.g., `i0 == i1` or `i0 == i1 * 12`. The previous logic for generating replacements would reject these cases, because you're not allowed to replace unbacked with unbacked. Modifying the logic is not so easy though; ordinarily, we decide what substitution to prioritize by trying to replace the largest hinted symbol, but for unbacked integers we don't have this. To get around this problem, for now I only setup replacements for trivial symbol equals something else situations. Check the diff with whitespace ignored, the addition is quite small.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Comment by ezyang** [comment]
cc @asmeurer

**Comment by asmeurer** [comment]
I guess this is related to https://github.com/pytorch/pytorch/issues/112347#issuecomment-1787949240

I'm still learning how this code works, so it's hard to comment too much here. Is it really a good idea to replace in both directions? That means you don't have to be careful about `a == b` being different from `b == a`, but maybe it's also possible for this to result in replacements that go backwards from what you wanted? 

(again, hard for me to know the answers to these questions because I'm still learning my way around all this)

**Comment by ezyang** [comment]
Yeah, this simplification arose as desirable because we were trying to rewrite an integer so that it would pass through modulus checks.

> Is it really a good idea to replace in both directions? That means you don't have to be careful about a == b being different from b == a, but maybe it's also possible for this to result in replacements that go backwards from what you wanted?

It's fine, for the equality replacements we are doing unification, so it doesn't matter which variable you end up with in the end, they're all in the same equivalence class.

> (again, hard for me to know the answers to these questions because I'm still learning my way around all this)

Feel free to ask anything you need :)

**Review by aakhundov — APPROVED** [review]
This, together with the `divisible_by` workaround suggested in https://github.com/pytorch/pytorch/issues/112347, seems to help going through the reshape with -1 in the target shape in the internal model. Thanks!

**Pull request closed without merging**
