### PR TITLE
Always retry curl downloads

### PR DESCRIPTION
**Pull request by ZainRizvi**
Modify our curl commands so that they always retry downloads.

By default, curl only retries what it considers to be "transient" errors, based on the server's response. However, curl's estimate of what's transient is very conservative.  By adding the --retry-all-errors parameter we'll always retry curl commands.

In particular, I'm hoping this mitigates errors where curl fails with the below error ([logs](https://github.com/pytorch/pytorch/actions/runs/3468758110/jobs/5794939941))
`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ossci-linux.s3.amazonaws.com:443`

Some of the modified downloads didn't even have retries, so I added them in

More details: https://everything.curl.dev/usingcurl/downloads/retry

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Review by malfet — APPROVED** [review]
Can we create some wrapper in comon.sh (say `curl_retry` and call it rather than modify 100+ callsites directly?)

**Comment by malfet** [comment]
This PR included submodule rollback for pybind11/gloo, which I guess was not intended. Reverting in https://github.com/pytorch/pytorch/pull/89449

A good BE task I wanted to implement for a while: check for a specific breadcrumb in PR if submodule update is intended

**Pull request closed without merging**
