### PR TITLE
[FSDP] Add `rank0_only` to `full_optim_state_dict()`

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #75517 [FSDP] Add `scatter_full_optim_state_dict()`
* **#75516 [FSDP] Add `rank0_only` to `full_optim_state_dict()`**

Differential Revision: [D35550063](https://our.internmc.facebook.com/intern/diff/D35550063)

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Thanks!

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35550063).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35550063).

**Pull request closed without merging**
