### PR TITLE
Move existing target determinator to tools

### PR DESCRIPTION
**Pull request by driazati**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#63809**
* #63808

This moves out the modulefinder determinator to `tools/testing` since it is supposed to be CI-only. This also simplifies run_test.py a little bit.

Differential Revision: [D30497438](https://our.internmc.facebook.com/intern/diff/D30497438)

### CODE REVIEW

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30497438).

**Review by janeyx99 — APPROVED** [review]

**Review by janeyx99 — DISMISSED** [review]
I realize this PR will also have to deal with the fact that run_test.py runs each test from the test directory (which is why there's CI failures I think)

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30497438).

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30497438).

**Review by seemethere — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
