### PR TITLE
Back out "Revert D23494065: Refactor CallbackManager as a friend class of RecordFunction."

### PR DESCRIPTION
**Pull request by louisfeng**
Summary:
Original commit changeset: 3b1ec928e3db

Previous revert (D23698861) was on the wrong diff stack. Backing out the revert.

Test Plan: Passed unit tests and previously landed.

Differential Revision: D23702258

### CODE REVIEW

**Comment by mruberry** [comment]
This should be OK but let's wait until the Windows builds are fixed and then rebase to verify. Sorry for the inconvenience, @louisfeng.

**Comment by mruberry** [comment]
You should be able to rebase now.

**Comment by mruberry** [comment]
You'll need to rebase this.

**Comment by louisfeng** [comment]
Ok, will do.

**Comment by louisfeng** [comment]
@mruberry Looks like the tests are OK, could you please review again. Thanks!

**Review by mruberry — APPROVED** [review]
Looks good now.

**Pull request closed without merging**
