### PR TITLE
[11/N] Fix clang-tidy warnings in aten/src/ATen 

### PR DESCRIPTION
**Pull request by cyyever**
Follows #133155

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by izaitsevfb** [comment]
@pytorchbot revert -m "causes build time regression in aten/src/ATen/native/cpu/ReduceOpsKernel.cpp" -c ghfirst

Internally we test build times for various parts of the codebase and have a tooling to detect regressions in instructions count during the build.

Unfortunately this change increases the instruction count (and build time) for 
 `aten/src/ATen/native/cpu/ReduceOpsKernel.cpp`:
instruction_count: 87,543,481,010 (continuous p90) -> 290,568,041,732 (this change)

@ezyang advised to revert.

**Pull request closed without merging**
