### PR TITLE
[Fix]: Only copy data for tensor with real dimensions

### PR DESCRIPTION
**Pull request by jiashenC**
#### Issue
Under real tensor mode, data copy happens even for tensor with symbolic dimensions, which results errors. This fix makes sure we only copy data for tensor with real dimensions.

#### Test Plan
* `pytest test/fx/test_shape_inference.py -s -k test_fx_trace_under_real_tensor_mode`

### CODE REVIEW

**Comment by ezyang** [comment]
So, this is specifically to make propagate real tensors work with higher order ops like torch.cond? Have we given any thought to what we want the actual semantics in this case to be?

In particular, it seems difficult to actually support tracing in this case: one of the cond branches won't actually get exercised in reality, so there's no way to do real tensor prop through it. Do you want to just silently decay to fake tensor prop in this case?

**Comment by ydwu4** [comment]
With propagate with real, can we use the predicates' real value to determine which branch to go?  E.g. we could use the chosen branch's real value to do propagation or inline the chosen branch and eliminate the cond operator.

**Comment by zou3519** [comment]
> In particular, it seems difficult to actually support tracing in this case: one of the cond branches won't actually get exercised in reality, so there's no way to do real tensor prop through it. Do you want to just silently decay to fake tensor prop in this case?

@ezyang is your concern that we will silently not trace one of the branches into an FX graph when combining real tensor prop with graph capture?

**Comment by ydwu4** [comment]
`silently decay to fake tensor prop` might be the most sound approach compared with the other two: If choosing a branch based on pred, we risk tracing downstream graphs with real tensors from only one branch. Inlining into one of the branches is against the purpose of using torch.cond. I think we probably should go with "deacy to fake tensor prop" to begin with.

**Comment by jiashenC** [comment]
> After re-read the comments, `silently decay to fake tensor prop` seems to be the most sound approach compared with the other two: If we choose a branch based on pred, we risk tracing downstream graphs with real tensors from only one branch and the downstream graph may not be sound for the other branch. Inlining into one of the branches is against the purpose of using torch.cond. I think we probably should go with "deacy to fake tensor prop" to begin with.
> 
> For @jiashenC , is this PR specifically for converting TS if to cond? Or is it that we're using torch.cond as a test and the actual problem is ` data copy happens even for tensor with symbolic dimensions`. What's previous error you see? Can you add more context to the PR description?

Yes, this PR is more for fixing some issues that I encounter when using `torch.cond` for `prim::If` during conversion, plus real tensor retracing with dynamic shapes.

The original error is as follow:
```
Traceback (most recent call last):
  File "/data/users/jiashenc/pytorch/test/export/test_converter.py", line 609, in test_convert_nn_module_with_nested_if_and_param
    ep_list = self._check_equal_ts_ep_converter(orig_m, inp, ["script"])
  File "/data/users/jiashenc/pytorch/test/export/test_converter.py", line 61, in _check_equal_ts_ep_converter
    ep = TS2EPConverter(ts_model, inp).convert()
  File "/data/users/jiashenc/pytorch/torch/_export/converter.py", line 971, in convert
    ep = self.retrace_as_exported_program(
  File "/data/users/jiashenc/pytorch/torch/_export/converter.py", line 1025, in retrace_as_exported_program
    ep = torch.export._trace._export(
  File "/data/users/jiashenc/pytorch/torch/export/_trace.py", line 992, in wrapper
    raise e
  File "/data/users/jiashenc/pytorch/torch/export/_trace.py", line 975, in wrapper
    ep = fn(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/export/exported_program.py", line 100, in wrapper
    return fn(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/export/_trace.py", line 1913, in _export
    export_artifact = export_func(  # type: ignore[operator]
  File "/data/users/jiashenc/pytorch/torch/export/_trace.py", line 1646, in _non_strict_export
    aten_export_artifact = _to_aten_func(  # type: ignore[operator]
  File "/data/users/jiashenc/pytorch/torch/export/_trace.py", line 616, in _export_to_aten_ir
    gm, graph_signature = transform(aot_export_module)(
  File "/data/users/jiashenc/pytorch/torch/export/_trace.py", line 1576, in _aot_export_non_strict
    gm, sig = aot_export(wrapped_mod, args, kwargs=kwargs, **flags)
  File "/data/users/jiashenc/pytorch/torch/_functorch/aot_autograd.py", line 1170, in aot_export_module
    fx_g, metadata, in_spec, out_spec = _aot_export_function(
  File "/data/users/jiashenc/pytorch/torch/_functorch/aot_autograd.py", line 1402, in _aot_export_function
    fx_g, meta = create_aot_dispatcher_function(
  File "/data/users/jiashenc/pytorch/torch/_dynamo/utils.py", line 246, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/_functorch/aot_autograd.py", line 589, in create_aot_dispatcher_function
    fw_metadata = run_functionalized_fw_and_collect_metadata(
  File "/data/users/jiashenc/pytorch/torch/_functorch/_aot_autograd/collect_metadata_analysis.py", line 163, in inner
    flat_f_outs = f(*flat_f_args)
  File "/data/users/jiashenc/pytorch/torch/_functorch/_aot_autograd/utils.py", line 178, in flat_fn
    tree_out = fn(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 764, in functional_call
    out = mod(*args[params_len:], **kwargs)
  File "/data/users/jiashenc/pytorch/torch/nn/modules/module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/nn/modules/module.py", line 1727, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/export/_trace.py", line 1559, in forward
    tree_out = torch.fx.Interpreter(self._export_root).run(
  File "/data/users/jiashenc/pytorch/torch/fx/interpreter.py", line 146, in run
    self.env[node] = self.run_node(node)
  File "/data/users/jiashenc/pytorch/torch/fx/interpreter.py", line 203, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/data/users/jiashenc/pytorch/torch/fx/interpreter.py", line 275, in call_function
    return target(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/_higher_order_ops/cond.py", line 151, in cond
    return torch.compile(cond_op, backend="eager", fullgraph=True)(
  File "/data/users/jiashenc/pytorch/torch/_dynamo/eval_frame.py", line 435, in _fn
    return fn(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/convert_frame.py", line 1168, in __call__
    return self._torchdynamo_orig_callable(
  File "/data/users/jiashenc/pytorch/torch/_dynamo/convert_frame.py", line 497, in __call__
    return _compile(
  File "/home/jiashenc/.conda/envs/pytorch-3.10/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/convert_frame.py", line 875, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/data/users/jiashenc/pytorch/torch/_dynamo/convert_frame.py", line 848, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/utils.py", line 246, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/_utils_internal.py", line 85, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "/data/users/jiashenc/pytorch/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/convert_frame.py", line 666, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/bytecode_transformation.py", line 1280, in transform_code_object
    transformations(instructions, code_options)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/convert_frame.py", line 194, in _fn
    return fn(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/convert_frame.py", line 608, in transform
    tracer.run()
  File "/data/users/jiashenc/pytorch/torch/_dynamo/symbolic_convert.py", line 2498, in run
    super().run()
  File "/data/users/jiashenc/pytorch/torch/_dynamo/symbolic_convert.py", line 908, in run
    while self.step():
  File "/data/users/jiashenc/pytorch/torch/_dynamo/symbolic_convert.py", line 820, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/symbolic_convert.py", line 514, in wrapper
    return inner_fn(self, inst)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/symbolic_convert.py", line 1538, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/symbolic_convert.py", line 758, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/lazy.py", line 132, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 47, in graph_break_as_hard_error
    return fn(*args, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/higher_order_ops.py", line 616, in call_function
    args, kwargs = LazyVariableTracker.realize_all((args, kwargs))
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/lazy.py", line 118, in realize_all
    result = tuple(cls.realize_all(v, cache) for v in value)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/lazy.py", line 118, in <genexpr>
    result = tuple(cls.realize_all(v, cache) for v in value)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/lazy.py", line 116, in realize_all
    result = [cls.realize_all(v, cache) for v in value]
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/lazy.py", line 116, in <listcomp>
    result = [cls.realize_all(v, cache) for v in value]
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/lazy.py", line 106, in realize_all
    result = cls.realize_all(value.realize(), cache)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/lazy.py", line 114, in realize_all
    value_dict[key] = cls.realize_all(value_dict[key], cache)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/lazy.py", line 116, in realize_all
    result = [cls.realize_all(v, cache) for v in value]
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/lazy.py", line 116, in <listcomp>
    result = [cls.realize_all(v, cache) for v in value]
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/lazy.py", line 106, in realize_all
    result = cls.realize_all(value.realize(), cache)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/lazy.py", line 58, in realize
    self._cache.realize()
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/lazy.py", line 24, in realize
    self.vt = VariableBuilder(tx, self.source)(self.value)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/builder.py", line 333, in __call__
    vt = self._wrap(value)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/builder.py", line 497, in _wrap
    return type_dispatch(self, value)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/builder.py", line 1463, in wrap_tensor
    tensor_variable = wrap_fx_proxy(
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/builder.py", line 1879, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/builder.py", line 1991, in wrap_fx_proxy_cls
    example_value = wrap_to_fake_tensor_and_record(
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/builder.py", line 2452, in wrap_to_fake_tensor_and_record
    fake_e = wrap_fake_exception(
  File "/data/users/jiashenc/pytorch/torch/_dynamo/utils.py", line 1340, in wrap_fake_exception
    return fn()
  File "/data/users/jiashenc/pytorch/torch/_dynamo/variables/builder.py", line 2453, in <lambda>
    lambda: tx.fake_mode.from_tensor(
  File "/data/users/jiashenc/pytorch/torch/_subclasses/fake_tensor.py", line 2078, in from_tensor
    return self.fake_tensor_converter.from_real_tensor(
  File "/data/users/jiashenc/pytorch/torch/_subclasses/fake_tensor.py", line 367, in from_real_tensor
    out = self.meta_converter(
  File "/data/users/jiashenc/pytorch/torch/_subclasses/meta_utils.py", line 1647, in __call__
    r = self.meta_tensor(
  File "/data/users/jiashenc/pytorch/torch/_subclasses/meta_utils.py", line 1455, in meta_tensor
    r.real_tensor = torch.empty_strided(
torch._dynamo.exc.InternalTorchDynamoError: /data/users/jiashenc/pytorch/build/aten/src/ATen/RegisterCPU.cpp:5288: SymIntArrayRef expected to contain only concrete integers

from user code:
   File "/data/users/jiashenc/pytorch/torch/_dynamo/external_utils.py", line 38, in inner
    return fn(*args, **kwargs)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True


While executing %cond : [num_users=1] = call_function[target=torch.cond](args = (%gt_scalar, %subgraph_0, %subgraph_1, (%x_1, %m2_linear_bias, %m1_linear_bias, %linear_bias, %m1_linear_weight, %m2_linear_weight, %linear_weight)), kwargs = {})
Original traceback:
None
```

And a reprod can be found using the following:
```
git checkout fix_dynamic_shape
pytest test/export/test_converter.py -s -k test_convert_nn_module_with_nested_if_and_param
```

**Comment by ezyang** [comment]
OK, hol' up, why are you using propagate real tensors for a TS to export converter? This doesn't pass the sniff test

**Comment by jiashenC** [comment]
> OK, hol' up, why are you using propagate real tensors for a TS to export converter? This doesn't pass the sniff test

The retracing step encountered data dependent errors on multiple internal production models when we tried to convert them. E.g.,
```
Could not guard on data-dependent expression Eq(u0, -1) (unhinted: Eq(u0, -1)).  (Size-like symbols: none)
Potential framework code culprit (scroll up for full backtrace):
  File "/data/users/jiashenc/.../__init__.py", line 893, in infer_size
    if d == -1:
For more information, run with TORCH_LOGS="dynamic"
For extended logs when we create symbols, also add TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="u0"
If you suspect the guard was triggered from C++, add TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
For more debugging help, see https://docs.google.com/document/d/1HSuTTVvYH1pTew89Rtpeu84Ht3nQEFTYhAX3Ypa_xJs/edit?usp=sharing
For C++ stack trace, run with TORCHDYNAMO_EXTENDED_DEBUG_CPP=1
While executing %reshape_default_8 : [num_users=2] = call_function[target=torch.ops.aten.reshape.default](args = (%linear_default_112, [-1, %_local_scalar_dense_default]), kwargs = {})
```
Turning on the real-tensor mode during retracing seems to be a solution to bypass those issues.

**Pull request closed without merging**
