### PR TITLE
[caffe2] Don't evaluate message in CAFFE_ENFORCE_THAT unless the check fails

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #106145

D26829714 improved CAFFE_ENFORCE_THAT, but made us eagerly evaluate the message, which has costs.

Differential Revision: [D47809432](https://our.internmc.facebook.com/intern/diff/D47809432/)

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]

**Comment by swolchok** [comment]
ugh, this diff is causing an ICE on focal:

```
/var/lib/jenkins/workspace/caffe2/operators/concat_split_op.h:312:14: internal compiler error: in finish_member_declaration, at cp/semantics.c:3029
         Input(i).dtype().name(),
```
(it says the Input(i) is the bad part)

**Comment by swolchok** [comment]
no luck, still getting the ICE

**Pull request closed without merging**
