### PR TITLE
Updated test_upsamplingBiMode2d_consistency

### PR DESCRIPTION
**Pull request by vfdev-5**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #118389
* __->__ #118388

Description:
- Lowered error thresholds and added input range for bicubic to make visible the inconsistency error in the implementation for upsampling (smaller -> larger) bicubic aa=false mode for uint8 input dtype
- Updated out-dated comments

### CODE REVIEW

**Review by NicolasHug — APPROVED** [review]
LGTM, thank you @vfdev-5

**Comment by vfdev-5** [comment]
@pytorch rebase

**Pull request closed without merging**
