### PR TITLE
Run fp16 resnext101 training in bench script

### PR DESCRIPTION
**Pull request by bddppq**
cc @xw285cornell

### CODE REVIEW

**Review by houseroad — APPROVED** [review]
Why do we still name the script resnet?

**Comment by bddppq** [comment]
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger-test/19952/
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger-test/12958/

**Comment by bddppq** [comment]
@houseroad Because we are too lazy to rename it :-)
But seriously we should rename the resnet50_trainer to imagenet_trainer (and then add other imagenet models to caffe2/python/models)

**Comment by petrex** [comment]
Lets try 4 gpu fp32 first?

**Pull request closed without merging**
