### PR TITLE
[Re-landing 86706] [JIT] Frozen Graph Linear-BatchNormNd Folding

### PR DESCRIPTION
**Pull request by min-jean-cho**
Re-landing #86706

This PR adds linear-batchnormNd folding for JIT frozen graphs. 

**Performance benchmark**
A preliminary benchmark with a simple model of linear+bn1d tested on first socket, physical cores of skylake machine. 

**FP32, JIT** 
without linear-bn folding
Screenshot (1368)

with linear-bn folding
Screenshot (1367)

### CODE REVIEW

**Comment by min-jean-cho** [comment]
@davidberard98 looks like all CIs have passed this time!

**Review by davidberard98 — APPROVED** [review]
LGTM!  But let me try landing it this time, I'll check internally first

**Pull request closed without merging**
