### PR TITLE
Factory functions for sparse CSC, BSR, and BSC tensors

### PR DESCRIPTION
**Pull request by pearu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #75585
* #75962
* #76635
* #76651
* #76650
* __->__ #76634

### CODE REVIEW

**Comment by pearu** [comment]
@cpuhrsch the one failing test is due to changing the argument names of `_validate_sparse_compressed_tensor_args`, that is,
```
aten::_validate_sparse_compressed_tensor_args(Tensor crow_indices, Tensor col_indices, Tensor values, int[] size, int layout) -> ()
```
is updated to
```
aten::_validate_sparse_compressed_tensor_args(Tensor compressed_indices, Tensor plain_indices, Tensor values, int[] size, int layout) -> ()
```
for correctness. What is the procedure for handling such false-positive failures?

**Review by cpuhrsch — CHANGES_REQUESTED** [review]
We should add tests for these

**Comment by pearu** [comment]
> We should add tests for these

Tests are implemented in https://github.com/pytorch/pytorch/pull/76746

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
