### PR TITLE
[c10d] Bridge c10d and gloo stores.

### PR DESCRIPTION
**Pull request by kumpera**
This relands #100633 with fixes for internal.

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
LGTM, although CI seems to have issues. Also do we need unittest?

**Review by fduwjj — APPROVED** [review]
LGTM

**Comment by kumpera** [comment]
> LGTM, although CI seems to have issues. Also do we need unittest?

We have tests for our stores but none for Gloo's forwarding store.

This methods will be indirectly tested once we land changes in gloo that use them.

**Comment by kumpera** [comment]
Since this previously failed internal, I'm testing there prior to merging here.

**Pull request closed without merging**
