### PR TITLE
format caffe2/torch/_export/serde/serialize.py

### PR DESCRIPTION
**Pull request by strisunshinewentingwang**
Summary: black caffe2/torch/_export/serde/serialize.py

Test Plan: tests

Differential Revision: D54654847

### CODE REVIEW

**Review by angelayi — APPROVED** [review]

**Comment by strisunshinewentingwang** [comment]
> ## Merge failed
> **Reason**: This PR needs a `release notes:` label If your changes are user facing and intended to be a part of release notes, please use a label starting with `release notes:`.
> 
> If not, please add the `topic: not user facing` label.
> 
> To add a label, you can comment to pytorchbot, for example `@pytorchbot label "topic: not user facing"`
> 
> For more information, see https://github.com/pytorch/pytorch/wiki/PyTorch-AutoLabel-Bot#why-categorize-for-release-notes-and-how-does-it-work.
> 
> Details for Dev Infra team



> ## Merge failed
> **Reason**: This PR needs a `release notes:` label If your changes are user facing and intended to be a part of release notes, please use a label starting with `release notes:`.
> 
> If not, please add the `topic: not user facing` label.
> 
> To add a label, you can comment to pytorchbot, for example `@pytorchbot label "topic: not user facing"`
> 
> For more information, see https://github.com/pytorch/pytorch/wiki/PyTorch-AutoLabel-Bot#why-categorize-for-release-notes-and-how-does-it-work.
> 
> Details for Dev Infra team

release notes: export

**Pull request closed without merging**
