### PR TITLE
Fix bad math typesetting

### PR DESCRIPTION
**Pull request by Atcold**
Fixing documentation.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by Atcold** [comment]
Why was this rejected? The current documentation is still wrong.
What's going on?

**Comment by ezyang** [comment]
So far as I can tell, this was merged to master and not reverted: 384a4feab6586d671840d35ede25f10e432ebc6f

MAybe you're looking at the 1.4 docs, which don't have this update? You would have to look at the master docs

**Comment by Atcold** [comment]
Hahaha, silly meeeeee! Thanks @ezyang! 😅

**Comment by ezyang** [comment]
It's a silly problem with our internal tooling; there's a bot which pushes an amended version of the commits which don't trigger the "Merged" logic on GitHub

**Comment by Atcold** [comment]
So, this won't make me a contributor 😞

**Comment by ezyang** [comment]
You look like a contributor to me :)

image

We don't destroy attribution on the commits (Author is preserved); they just don't show up as merged PRs.

**Pull request closed without merging**
