### PR TITLE
Added an OpInfo for mm & ported its method_tests

### PR DESCRIPTION
**Pull request by imaginary-person**
### Summary

Added an `OpInfo` for `mm` & ported its `method_tests` entry (it only had one).

cc: @mruberry

### CODE REVIEW

**Comment by imaginary-person** [comment]
@mruberry, sorry I had forgotten to remove the `method_tests` entry for `mm` yesterday. I removed it today.

**Comment by imaginary-person** [comment]
`pr/pytorch-linux-bionic-rocm4.1-py3.6` is failing because of #55552.

**Review by mruberry — APPROVED** [review]
Awesome! Thanks @imaginary-person; let's just wait for the tests.

**Comment by kimishpatel** [comment]
Sorry @mruberry but this broke pytorch_windows_vs2019_py36_cuda11.1_test1, pytorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_test1. Reverting.

**Comment by imaginary-person** [comment]
@mruberry, it seems like `bfloat16` for `mm` is supported on CUDA 11.1 and beyond.
The CI checks hadn't run on CUDA 11.1 (except build), so this issue wasn't detected.
I'll add these changes to #55201, with a CUDA version check.

**Comment by mruberry** [comment]
No worries, @imaginary-person person, it's my mistake. I should have recalled that issue with mm() and there was no CI signal.

**Comment by imaginary-person** [comment]
@mruberry, thanks for your response! I don't think it's your mistake because even if there was a conditional for CUDA11+, a cuDNN CI check with CUDA 11.1 might've failed, as it did for `addbmm`.

**Pull request closed without merging**
