### PR TITLE
[nn] Add remove_duplicate flag to named_buffers

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #84984

Summary:
this is to allow named_buffers to return the same buffer objects with different names multiple times, needed by internal use cases

Test Plan:
python test/test_nn.py -k test_buffers_and_named_buffers

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D39493161](https://our.internmc.facebook.com/intern/diff/D39493161)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39493161).

**Review by albanD — APPROVED** [review]
SGTM

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39493161).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39493161).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39493161).

**Comment by jerryzh168** [comment]
deprecating this one because https://github.com/pytorch/pytorch/pull/85903#issuecomment-1264133328

**Pull request closed without merging**
