### PR TITLE
Fix FakeTensor printing

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99205

I got too confused by the FakeTensor printing, so this PR fixes it to
print normally.

Before:
```
with FakeTensorMode():
    x = torch.empty(2, 2, device="cpu")
    print(x)
    # FakeTensor(FakeTensor(..., device='meta', shape=(2, 2)), cpu)
```
After (Tensor printing doesn't print the default device):
```
FakeTensor(..., shape=(2, 2))
```

Test Plan:
- new test

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
Could we still print the fake device of the tensor? That is helpful to see

**Comment by zou3519** [comment]
@eellison what do you mean by the "fake device of the Tensor?"

**Review by eellison — APPROVED** [review]
I didn't realize that about CPU Tensors. LGTM !

**Pull request closed without merging**
