### PR TITLE
[futures] Reland: Add torch.futures.collect_all()/wait_all() python api.

### PR DESCRIPTION
**Pull request by jjlilley**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#39964 [futures] Reland: Add torch.futures.collect_all()/wait_all() python api.**

The "[fut.wait() for fut in futs]" idiom can introduce up to
O(len(futs)) thread switches, which may be excessive for large N.

This plumbs through the new c++ c10::collectAll() to Python space
so that we only employ a single jit-side wait.

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D22027412/)!

### CODE REVIEW

**Comment by jjlilley** [comment]
This is a minor edit from the original change https://github.com/pytorch/pytorch/pull/39790 .

This iteration just adds c10:: namespace prefix in init.cpp to some references - apparently it would build everywhere but Windows without the prefix. Those targets are building now in CircleCI.

(Windows build was known broken at top-of-tree for unrelated reasons on Friday morning when I was landing the original; I had mistakenly conflated the top-of-tree Windows failure with the failure that the original version of this change caused).

**Review by mrshenli — APPROVED** [review]
LGTM! 

`torch.futures` are not showing up correctly on our docs page. I will fix that in a follow up PR and also add warning to mention these are experimental features.

**Comment by mrshenli** [comment]
Lint errors looks irrelevant

**Comment by jjlilley** [comment]
Thanks, Shen!

**Pull request closed without merging**
