### PR TITLE
test_linalg: triangular_solve - set higher precision

### PR DESCRIPTION
**Pull request by nikitaved**
This is a follow-up on https://github.com/pytorch/pytorch/pull/104425.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105920

### CODE REVIEW

**Comment by lezcano** [comment]
I'd be surprised if we could completely remove these, but let's see.

**Comment by lezcano** [comment]
what happened to this PR? It got orphaned?

**Comment by nikitaved** [comment]
I will resubmit. Something screwed my file system and the stack got poisoned...

**Comment by nikitaved** [comment]
We have more tests like these. I will update them after the CIs are run and clean.

**Pull request closed without merging**
