### PR TITLE
FIX make sure we import the correct object from multiprocessing

### LINKED ISSUE #44687: DataLoader with num_workers>0 fails when running with "spawn" and using joblib
## 🐛 Bug

Running multiple jobs in parallel (using joblib) fails when num_workers in DataLoaders is > 0.

## To Reproduce

```python
import os, sys
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
from torchvision import transforms
from joblib import Parallel, delayed

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

def main(num_workers, lr):
    data_set = MNIST(os.getcwd(), download=True, train=True, transform=transforms.ToTensor())
    data_loader = DataLoader(data_set, batch_size=64, num_workers=num_workers)
    model = Model().cuda()
    optim = torch.optim.Adam(model.parameters(), lr=lr)

    for batch in data_loader:
        x, y = batch
        y_hat = model(x.cuda())
        loss = F.cross_entropy(y_hat, y.cuda())
    print(f'completed {lr}')

if __name__ == '__main__':
    num_workers = int(sys.argv[1])
    lr_array = [1e-4, 1e-3, 1e-2]
    Parallel(n_jobs=3, backend='loky')(delayed(main)(num_workers, lr) for lr in lr_array)
```

This works:
```commandline
python code.py 0
```

This fails:
```commandline
python code.py 1
```

with error: (note that there are several times more cores available than required for this config.)

```commandline
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "MNIST_hydra.py", line 32, in main
    for batch in data_loader:
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 737, in __init__
    w.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/externals/loky/backend/process.py", line 39, in _Popen
    return Popen(process_obj)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 52, in __init__
    self._launch(process_obj)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 157, in _launch
    pid = fork_exec(cmd_python, self._fds, env=process_obj.env)
AttributeError: 'Process' object has no attribute 'env'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "MNIST_hydra.py", line 41, in <module>
    Parallel(n_jobs=3, backend='loky')(delayed(main)(num_workers, lr) for lr in lr_array)
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AttributeError: 'Process' object has no attribute 'env'
(l2r) $ /opt/.virtualenvs/l2r/lib/python3.7/site-packages/joblib/externals/loky/backend/resource_tracker.py:320: UserWarning: resource_tracker: There appear to be 33 leaked semlock objects to clean up at shutdown
  (len(rtype_registry), rtype))
```

## Expected behavior

Being able to set num_workers>0 while running multiple jobs in parallel with joblib.

## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: TITAN Xp
Nvidia driver version: 440.100
cuDNN version: 7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-lightning==0.9.1rc1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] Could not collect

## Additional context

Same issue on GPU and CPU, and there are plenty of cores available for this to work.

cc @SsnL @VitalyFedyunin

### PR DESCRIPTION
**Pull request by tomMoral**
Fixes #44687.

The issue was that the Process object is not the one from the `_default_context` which should be `loky` when nesting `loky` calls.

### CODE REVIEW

**Comment by mruberry** [comment]
@VitalyFedyunin are you the correct reviewer for this?

**Comment by mruberry** [comment]
Ping @VitalyFedyunin.

**Comment by VitalyFedyunin** [comment]
Test fails are legit

**Review by VitalyFedyunin — CHANGES_REQUESTED** [review]
Please review test failures and fix them

**Comment by tomMoral** [comment]
I tried to fix the `mypy` ones. Not sure how to launch the test locally, if you have the right command, I would be intersted.
For the building/downloading ones, not sure whether it is due to this PR or not?

**Comment by tomMoral** [comment]
And sorry but I have no idea why there is all these failures on files that I don't think I touched.
Let me know if I did something wrong or if I need to do something to fix this.

**Comment by tomMoral** [comment]
For the 2 failures, on build bot, I have no idea what is going on. Let me know if there is something wrong with the way I did the PR but I don't understand all these conflicts on files I did not touched.

For the `mypy` linter, I guess this are some false positive alerts? Not sure about that but if someone can check this before I spend too much time trying to fix this, that would be helpful.

**Comment by tomMoral** [comment]
I finally managed to understand how to tell `mypy` that the object existed without importing them in the `__init__.py` by adding a stub file. This fixes the `mypy` failures. Is that okay to include such `pyi` files?

@VitalyFedyunin would you be able to review this PR again?

**Comment by VitalyFedyunin** [comment]
The code looks good. Can you please rebase to avoid merge conflicts of any kind? Thanks.

**Comment by tomMoral** [comment]
I rebased and squash the commits on `master`. Let me know if there is any thing else needed.

**Comment by tomMoral** [comment]
Is there any blocker left? I just rebased on master now to keep the PR up to date.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by tomMoral** [comment]
@VitalyFedyunin
The PR is green and rebased :)

**Comment by janeyx99** [comment]
@pytorchbot revert -m "Sorry, reverting as this breaks 10.2 tests on trunk https://hud.pytorch.org/pytorch/pytorch/commit/e103d6af3dadb62348eedc2b6c68410f5441d542" -c nosignal

Sorry about that! Please add ciflow/trunk label to the PR when relanding and ensure that the 10.2 slow tests pass.
```
======================================================================
2022-07-20T19:06:09.9644536Z FAIL [2.375s]: test_MaxUnpool_index_errors_case1_cuda (__main__.TestNNDeviceTypeCUDA)
2022-07-20T19:06:09.9645155Z ----------------------------------------------------------------------
2022-07-20T19:06:09.9646363Z Traceback (most recent call last):
2022-07-20T19:06:09.9646922Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1883, in wrapper
2022-07-20T19:06:09.9647309Z     method(*args, **kwargs)
2022-07-20T19:06:09.9647801Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1883, in wrapper
2022-07-20T19:06:09.9648179Z     method(*args, **kwargs)
2022-07-20T19:06:09.9651385Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
2022-07-20T19:06:09.9651905Z     result = test(self, **param_kwargs)
2022-07-20T19:06:09.9652739Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 348, in test_wrapper
2022-07-20T19:06:09.9653503Z     return test(*args, **kwargs)
2022-07-20T19:06:09.9654327Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1186, in wrapper
2022-07-20T19:06:09.9655198Z     fn(*args, **kwargs)
2022-07-20T19:06:09.9656048Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 1006, in only_fn
2022-07-20T19:06:09.9656456Z     return fn(self, *args, **kwargs)
2022-07-20T19:06:09.9656966Z   File "/opt/conda/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 848, in dep_fn
2022-07-20T19:06:09.9657357Z     return fn(slf, *args, **kwargs)
2022-07-20T19:06:09.9657739Z   File "/var/lib/jenkins/workspace/test/test_nn.py", line 15093, in test_MaxUnpool_index_errors
2022-07-20T19:06:09.9658074Z     self.assertIn(
2022-07-20T19:06:09.9660309Z AssertionError: 'Assertion `maxind >= 0 && maxind < outputImageSize` failed' not found in '\nTraceback (most recent call last):\n  File "<string>", line 8, in <module>\n  File "/opt/conda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 496, in synchronize\n    return torch._C._cuda_synchronize()\nRuntimeError: CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\n' : The expected error was not found
2022-07-20T19:06:09.9661267Z 
2022-07-20T19:06:09.9661549Z ----------------------------------------------------------------------
```

**Pull request closed without merging**
