### PR TITLE
Fix typographical error in torch.triu docstring

### LINKED ISSUE #32032: [Doc] torch.triu doc mistakenly said that elements on and BELOW the main diagonal are retained.
## 📚 Documentation
https://pytorch.org/docs/stable/torch.html#torch.triu
image

It seems that the highlighted "below" should be "upper“.

### PR DESCRIPTION
**Pull request by vishwakftw**
below --> above

Fixes #32032

### CODE REVIEW

**Comment by vishwakftw** [comment]
Is it possible to include this in 1.4.0?

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 07853b76:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=07853b7650be8fdf8a8e26aa4fc31c1f8d5d52f6).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4206326) pytorch_linux_xenial_py3_6_gcc5_4_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=83359023) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=83359023))
<details>
<summary>
<code>Automatic merge failed; fix conflicts and then commit the result.</code>
</summary>

```
CONFLICT (add/add): Merge conflict in .circleci/docker/common/install_conda.sh 
Auto-merging .circleci/docker/common/install_conda.sh 
CONFLICT (add/add): Merge conflict in .circleci/docker/build.sh 
Auto-merging .circleci/docker/build.sh 
CONFLICT (add/add): Merge conflict in .circleci/config.yml 
Auto-merging .circleci/config.yml 
CONFLICT (add/add): Merge conflict in .circleci/cimodel/data/pytorch_build_definitions.py 
Auto-merging .circleci/cimodel/data/pytorch_build_definitions.py 
CONFLICT (add/add): Merge conflict in .circleci/cimodel/data/caffe2_build_definitions.py 
Auto-merging .circleci/cimodel/data/caffe2_build_definitions.py 
Automatic merge failed; fix conflicts and then commit the result. 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by zou3519** [comment]
> Is it possible to include this in 1.4.0?

After this gets merged into master, please submit a PR to 1.4.0.

**Review by zou3519 — APPROVED** [review]

**Comment by zou3519** [comment]
This seems to need a rebase: https://app.circleci.com/jobs/github/pytorch/pytorch/4206326 , let's see if pytorchbot is alive

**Comment by vishwakftw** [comment]
@zou3519 I've rebased manually now

**Review by ssnl — APPROVED** [review]

**Pull request closed without merging**
