### PR TITLE
[BE]: Add pointwise tags to activations for NJT and torch compile

### PR DESCRIPTION
**Pull request by Skylion007**
Adds pointwise tags to rarer activations

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by soulitzer** [comment]
Failures look legit. Seems like nested tensor's pointwise implementation does not handle one of the ops that is now marked pointwise.

**Comment by soulitzer** [comment]
The issue is that nested tensor assumes that for binary ops, the tensor inputs are always the first two arguments, but that is not the case for elu_backward. 

To unblock this PR, we can xfail these for NT for now, but one thing we will want to do is for the NT handling to special case in these situations.

**Comment by Skylion007** [comment]
@soulitzer Not just the case for elu_backwards, but for any function that has scalar as second arg, including celu etc.

**Comment by Skylion007** [comment]
close in favor of https://github.com/pytorch/pytorch/pull/140736

**Pull request closed without merging**
