### PR TITLE
For consistent CUDA_HOME behavior

### PR DESCRIPTION
**Pull request by silent567**
Align the behavior of `torch.utils.cpp_extension.CUDA_HOME` with that of `tools.setup_helpers.cuda.CUDA_HOME`.

Typically, I swapped the position of guess 2 and guess 3 in `torch.utils.cpp_extension.CUDA_HOME` .

Fixing issue #22844

### CODE REVIEW

**Review by peterjc123 — APPROVED** [review]
LGTM

**Review by soumith — APPROVED** [review]

**Comment by xuhdev** [comment]
Is it possible that you could simply

    from tools.setup_helpers.cuda import CUDA_HOME

**Comment by silent567** [comment]
> Is it possible that you could simply
> 
> ```
> from tools.setup_helpers.cuda import CUDA_HOME
> ```

In my case, I am just the user instead of the maintainer of torch-scatter.  A quick work-around would be to set `CUDA_HOME` environment variable. Two functions will behave the same then. 

In general, the different behaviors of similar functions are firstly confusing. I did a huge test today to make sure all packages including torch and torch_geoemtric are using the same CUDA version to avoid potential bugs. Secondly, I am not sure if torch-scatter has access to setup tools in the compiled version of torch. 

( And I am not sure which one you are asking the question. Just describe my situation in more detail...  )

**Comment by ezyang** [comment]
Waiting on CI.

**Pull request closed without merging**
