### PR TITLE
Allow FakeTensorProp to run on graphs traced with some None inputs

### PR DESCRIPTION
**Pull request by wschin**
Without this tiny change in `torch/_subclasses/fake_tensor.py`, the added test may fail with
```
TypeError: cannot create weak reference to 'NoneType' object
```

### CODE REVIEW

**Comment by ezyang** [comment]
I mean, I guess we could do this. But why is this not just a problem at the call site? I could equally imagine the invariant is you can only pass non-None things as t

**Comment by wschin** [comment]
> I mean, I guess we could do this. But why is this not just a problem at the call site? I could equally imagine the invariant is you can only pass non-None things as t

Without this small change, that means `FakeTensorProp` changes the signature of `fx.GraphModule.forward` if I trace any of huggingface models. I feel `None` is really a special case the code should handle.

**Comment by ezyang** [comment]
It seems like FakeTensorProp's responsibility to deal with None though, the same way it is responsible for dealing with lists of tensors, etc.

**Comment by wschin** [comment]
Ok. I can change
```
    def propagate(self, *args):
        with self._mode:
            fake_args = [self._mode.from_tensor(a) for a in args]
            return super().run(*fake_args)
```

to
```
    def propagate(self, *args):
        with self._mode:
            fake_args = [self._mode.from_tensor(a) if isinstance(a, torch.Tensor) else None for a in args]
            return super().run(*fake_args)
```

**Comment by eellison** [comment]
+1 would prefer if you made a use side change for this

**Comment by wschin** [comment]
@eellison, @ezyang, does new change look ok now?

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
