### PR TITLE
[Re-landing 68111] Add JIT graph fuser for oneDNN Graph API (Preview4.1)

### PR DESCRIPTION
**Pull request by sanchitintel**
## Description
 Relanding #68111
 Preview4 PR of this [RFC](https://github.com/pytorch/pytorch/issues/49444).
 
 On the basis of #50256, the below improvements are included:
 
 * The [preview4 release branch](https://github.com/oneapi-src/oneDNN/releases/tag/graph-v0.4.1) of the oneDNN Graph API is used
 * The fuser now works with the profiling graph executor. We have inserted type check nodes to guard the profiled tensor properties.
 
 ### User API:
 The optimization pass is disabled by default. Users could enable it by:
 
 ```
 torch.jit.enable_onednn_fusion(True)
 ```
 
 ### Performance:
 [pytorch/benchmark](https://github.com/pytorch/benchmark) tool is used to compare the performance:
 
 * SkyLake 8180 (1 socket of 28 cores):
   image
 * SkyLake 8180 (single thread):
   image
   * By mapping hardswish to oneDNN Graph, it’s 8% faster than PyTorch JIT (NNC + OFI)
   ** We expect performance gain after mapping transpose, contiguous & view to oneDNN graph ops
 
 ### Directory structure of the integration code
 Fuser-related code are placed under:
 
 ```
 torch/csrc/jit/codegen/onednn/
 ```
 
 Optimization pass registration is done in:
 
 ```
 torch/csrc/jit/passes/onednn_graph_fuser.h
 ```
 
 CMake for the integration code is:
 
 ```
 caffe2/CMakeLists.txt
 ```
 
 ## Limitations
 * In this PR, we have only supported the optimization on Linux platform. The support on Windows and MacOS will be enabled as a next step.
 * We have only optimized the inference use case.

### CODE REVIEW

**Comment by malfet** [comment]
@sanchitintel to make review easier, can you simply cherry-picked landed commit into the branch and then apply any other changes on top of that?

**Comment by sanchitintel** [comment]
> to make review easier, can you simply cherry-picked landed commit into the branch and then apply any other changes on top of that?

Sorry @malfet, please clarify which _landed commit_ you're referring to.
Please confirm if you mean first rebasing PR #68111 with the latest master branch, and then adding [this commit to fix the lite-interpreter build](https://github.com/pytorch/pytorch/pull/74572/commits/786476ab1d66315b0c68359e52ee6a5e7adea5f4). Thanks!

**Comment by malfet** [comment]
This one: https://github.com/pytorch/pytorch/commit/cd17683aa7d9c0947df45a1ab53627feff795587

**Comment by sanchitintel** [comment]
Windows build failed while compiling a lite interpreter file (`test_jit/CMakeFiles/test_jit.dir/test_lite_interpreter.cpp.obj`), but seems to have failed due to an unrelated cause -

image

Will rebase later to check if the issue got fixed.

**Comment by sanchitintel** [comment]
Closing & reopening as #74596. Thanks!

**Comment by sanchitintel** [comment]
Somehow CI is not running on #74572

**Pull request closed without merging**
