### PR TITLE
Remove intrusive_ptr::reclaim() in Storage

### PR DESCRIPTION
**Pull request by smessmer**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#11352 Remove intrusive_ptr::reclaim() in Storage**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9694327/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11547 Remove intrusive_ptr::reclaim() in Storage (2/2)&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D9778042/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11353 Simplify union payload copying&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9694326/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11355 Simplify IValue::toTensor()&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9694918/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11402 Simplify Blob move constructor/assignment&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9728631/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11414 IValue can store Blob&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9731326/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11548 Blob doesn't allow access to destroyCall anymore&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9775191/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11500 Use TypeMeta::dtor() instead of Blob::DestroyCall&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9763423/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11501 Move GetExceptionString to Error.h&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9763424/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11502 Improve TypeMeta&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9763422/)

Pushing manual refcounting further back, making things safer.

Differential Revision: [D9694327](https://our.internmc.facebook.com/intern/diff/D9694327/)

### CODE REVIEW

**Comment by ezyang** [comment]
ASAN failure seems legit.

**Comment by smessmer** [comment]
@ezyang ASAN failure was in a diff stacked below and should be fixed now

**Comment by goldsborough** [comment]
Why are all codeowners being subscribed? :(

**Comment by smessmer** [comment]
@goldsborough no idea, is that something your tool did @ezyang ?

**Comment by ezyang** [comment]
Maybe GitHub gets confused about the merge commits...

**Comment by ezyang** [comment]
Your build is still failing.

```
00:24:08 + python -c 'import torch'
00:24:09 /var/lib/jenkins/workspace/aten/src/ATen/core/Storage.h:37:27: runtime error: member call on null pointer of type 'at::StorageImpl'
00:24:09     #0 0x7fdd78d351c0 in at::Storage::dtype() const (/opt/conda/lib/python3.6/site-packages/torch/lib/libcaffe2.so+0x51f41c0)
00:24:09     #1 0x7fdd78d330fe in at::TensorImpl::TensorImpl(at::Storage, at::TensorTypeId, bool) (/opt/conda/lib/python3.6/site-packages/torch/lib/libcaffe2.so+0x51f20fe)
00:24:09     #2 0x7fdd78d32a69 in at::TensorImpl::TensorImpl(at::TensorTypeId, at::ScalarType, at::Allocator*, bool) (/opt/conda/lib/python3.6/site-packages/torch/lib/libcaffe2.so+0x51f1a69)
00:24:09     #3 0x7fdd78b61682 in _GLOBAL__sub_I_UndefinedTensorImpl.cpp (/opt/conda/lib/python3.6/site-packages/torch/lib/libcaffe2.so+0x5020682)
00:24:09     #4 0x7fdd9b3b16b9 in call_init /build/glibc-Cl5G7W/glibc-2.23/elf/dl-init.c:72
00:24:09     #5 0x7fdd9b3b17ca in call_init /build/glibc-Cl5G7W/glibc-2.23/elf/dl-init.c:30
00:24:09     #6 0x7fdd9b3b17ca in _dl_init /build/glibc-Cl5G7W/glibc-2.23/elf/dl-init.c:120
00:24:09     #7 0x7fdd9b3b68e1 in dl_open_worker /build/glibc-Cl5G7W/glibc-2.23/elf/dl-open.c:575
00:24:09     #8 0x7fdd9b3b1563 in _dl_catch_error /build/glibc-Cl5G7W/glibc-2.23/elf/dl-error.c:187
00:24:09     #9 0x7fdd9b3b5da8 in _dl_open /build/glibc-Cl5G7W/glibc-2.23/elf/dl-open.c:660
00:24:09     #10 0x7fdd99d7cf08 in __asprintf /build/glibc-Cl5G7W/glibc-2.23/dlfcn/dlopen.c:66
00:24:09     #11 0x7fdd9b3b1563 in _dl_catch_error /build/glibc-Cl5G7W/glibc-2.23/elf/dl-error.c:187
00:24:09     #12 0x7fdd99d7d570 in _dlerror_run /build/glibc-Cl5G7W/glibc-2.23/dlfcn/dlerror.c:163
00:24:09     #13 0x7fdd99d7cfa0 in dlopen /build/glibc-Cl5G7W/glibc-2.23/dlfcn/dlopen.c:87
00:24:09     #14 0x7fdd9a61ef3f in dlopen (/usr/lib/llvm-5.0/lib/clang/5.0.0/lib/linux/libclang_rt.asan-x86_64.so+0xb7f3f)
00:24:09     #15 0x5568bccf6379 in _PyImport_FindSharedFuncptr (/opt/conda/bin/python3.6+0x1ef379)
00:24:09     #16 0x5568bcd1cb3f in _PyImport_LoadDynamicModuleWithSpec (/opt/conda/bin/python3.6+0x215b3f)
00:24:09     #17 0x5568bcd1cd84 in _imp_create_dynamic (/opt/conda/bin/python3.6+0x215d84)
00:24:09     #18 0x5568bcc19ae0 in PyCFunction_Call (/opt/conda/bin/python3.6+0x112ae0)
00:24:09     #19 0x5568bcccdaab in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c6aab)
00:24:09     #20 0x5568bcc9d205 in _PyEval_EvalCodeWithName (/opt/conda/bin/python3.6+0x196205)
00:24:09     #21 0x5568bcc9e1ce in fast_function (/opt/conda/bin/python3.6+0x1971ce)
00:24:09     #22 0x5568bcca3ed4 in call_function (/opt/conda/bin/python3.6+0x19ced4)
00:24:09     #23 0x5568bccc8949 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c1949)
00:24:09     #24 0x5568bcc9df8a in fast_function (/opt/conda/bin/python3.6+0x196f8a)
00:24:09     #25 0x5568bcca3ed4 in call_function (/opt/conda/bin/python3.6+0x19ced4)
00:24:09     #26 0x5568bccc8949 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c1949)
00:24:09     #27 0x5568bcc9df8a in fast_function (/opt/conda/bin/python3.6+0x196f8a)
00:24:09     #28 0x5568bcca3ed4 in call_function (/opt/conda/bin/python3.6+0x19ced4)
00:24:09     #29 0x5568bccc8949 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c1949)
00:24:09     #30 0x5568bcc9df8a in fast_function (/opt/conda/bin/python3.6+0x196f8a)
00:24:09     #31 0x5568bcca3ed4 in call_function (/opt/conda/bin/python3.6+0x19ced4)
00:24:09     #32 0x5568bccc8949 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c1949)
00:24:09     #33 0x5568bcc9df8a in fast_function (/opt/conda/bin/python3.6+0x196f8a)
00:24:09     #34 0x5568bcca3ed4 in call_function (/opt/conda/bin/python3.6+0x19ced4)
00:24:09     #35 0x5568bccc8949 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c1949)
00:24:09     #36 0x5568bcc9e5da in _PyFunction_FastCallDict (/opt/conda/bin/python3.6+0x1975da)
00:24:09     #37 0x5568bcc16dae in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10fdae)
00:24:09     #38 0x5568bcc5a0df in _PyObject_CallMethodIdObjArgs (/opt/conda/bin/python3.6+0x1530df)
00:24:09     #39 0x5568bcc0d6df in PyImport_ImportModuleLevelObject (/opt/conda/bin/python3.6+0x1066df)
00:24:09     #40 0x5568bcccb38d in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c438d)
00:24:09     #41 0x5568bcc9ecb8 in PyEval_EvalCodeEx (/opt/conda/bin/python3.6+0x197cb8)
00:24:09     #42 0x5568bcc9fa4b in PyEval_EvalCode (/opt/conda/bin/python3.6+0x198a4b)
00:24:09     #43 0x5568bccc626c in builtin_exec (/opt/conda/bin/python3.6+0x1bf26c)
00:24:09     #44 0x5568bcc19ae0 in PyCFunction_Call (/opt/conda/bin/python3.6+0x112ae0)
00:24:09     #45 0x5568bcccdaab in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c6aab)
00:24:09     #46 0x5568bcc9d205 in _PyEval_EvalCodeWithName (/opt/conda/bin/python3.6+0x196205)
00:24:09     #47 0x5568bcc9e1ce in fast_function (/opt/conda/bin/python3.6+0x1971ce)
00:24:09     #48 0x5568bcca3ed4 in call_function (/opt/conda/bin/python3.6+0x19ced4)
00:24:09     #49 0x5568bccc8949 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c1949)
00:24:09     #50 0x5568bcc9df8a in fast_function (/opt/conda/bin/python3.6+0x196f8a)
00:24:09     #51 0x5568bcca3ed4 in call_function (/opt/conda/bin/python3.6+0x19ced4)
00:24:09     #52 0x5568bccc8949 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c1949)
00:24:09     #53 0x5568bcc9df8a in fast_function (/opt/conda/bin/python3.6+0x196f8a)
00:24:09     #54 0x5568bcca3ed4 in call_function (/opt/conda/bin/python3.6+0x19ced4)
00:24:09     #55 0x5568bccc8949 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c1949)
00:24:09     #56 0x5568bcc9df8a in fast_function (/opt/conda/bin/python3.6+0x196f8a)
00:24:09     #57 0x5568bcca3ed4 in call_function (/opt/conda/bin/python3.6+0x19ced4)
00:24:09     #58 0x5568bccc8949 in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c1949)
00:24:09     #59 0x5568bcc9e5da in _PyFunction_FastCallDict (/opt/conda/bin/python3.6+0x1975da)
00:24:09     #60 0x5568bcc16dae in _PyObject_FastCallDict (/opt/conda/bin/python3.6+0x10fdae)
00:24:09     #61 0x5568bcc5a0df in _PyObject_CallMethodIdObjArgs (/opt/conda/bin/python3.6+0x1530df)
00:24:09     #62 0x5568bcc0d6df in PyImport_ImportModuleLevelObject (/opt/conda/bin/python3.6+0x1066df)
00:24:09     #63 0x5568bcccb38d in _PyEval_EvalFrameDefault (/opt/conda/bin/python3.6+0x1c438d)
00:24:09     #64 0x5568bcc9ecb8 in PyEval_EvalCodeEx (/opt/conda/bin/python3.6+0x197cb8)
00:24:09     #65 0x5568bcc9fa4b in PyEval_EvalCode (/opt/conda/bin/python3.6+0x198a4b)
00:24:09     #66 0x5568bcd1bc43 in run_mod (/opt/conda/bin/python3.6+0x214c43)
00:24:09     #67 0x5568bcd1bcdc in PyRun_StringFlags (/opt/conda/bin/python3.6+0x214cdc)
00:24:09     #68 0x5568bcd1bd3e in PyRun_SimpleStringFlags (/opt/conda/bin/python3.6+0x214d3e)
00:24:09     #69 0x5568bcd1fb00 in Py_Main (/opt/conda/bin/python3.6+0x218b00)
00:24:09     #70 0x5568bcbe775d in main (/opt/conda/bin/python3.6+0xe075d)
00:24:09     #71 0x7fdd99fa082f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
00:24:09     #72 0x5568bcccf47a in _start (/opt/conda/bin/python3.6+0x1c847a)
00:24:09 
00:24:09 SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /var/lib/jenkins/workspace/aten/src/ATen/core/Storage.h:37:27 in 
```

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
