### PR TITLE
Use CType Union instead of manually listing everything out

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #72853

Partially addresses #72852

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D34242359](https://our.internmc.facebook.com/intern/diff/D34242359)

### CODE REVIEW

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34242359).

**Review by wconstab — APPROVED** [review]
lgtm, note there are now 'unused' flake8s to fix.

I'll follow up on the issue #72852 RE the remaining problems

**Comment by wconstab** [comment]
Actually @ezyang maybe just let me land this along with my existing changes here:
https://www.internalfb.com/diff/D34178476

**Comment by ezyang** [comment]
SGTM

**Pull request closed without merging**
