### PR TITLE
[easy] Dispatch torch.from_numpy to torch.as_tensor

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #114609
* #114608

...rather than detaching the tensor

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by larryliu0820 — APPROVED** [review]
Seems ok

**Review by voznesenskym — APPROVED** [review]

**Pull request closed without merging**
