### PR TITLE
Add support for cat memory planning mms with max autotune

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #132554

When we are autotuning matmuls the aten.mm and the triton template choices take in an externally allocated tensor that can be a view into a pre-planned aten.cat. So long as the output shape and stride of the matmul matches the slice of the cat we're planning, we can realize the mm directly into the cat. 

Discussion for reviewers:

It feels a little bit odd that in the existing code we set the output of aten.mm as [FlexibleLayout](https://github.com/pytorch/pytorch/blob/bcac71517c461765b4fa9efccc6f1a5a475c3544/torch/_inductor/kernel/mm.py#L156). While is this correct, it might lead to passing non performant output strides to cublas.. I guess this is better than a copy ? Not sure. We could also introduce a Layout that denotes a Fixed shape and stride which we control allocation

```
class AllocatedFixedLayout(FixedLayout)
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by Chillee — COMMENTED** [review]
I haven't looked at this carefully yet, but will this work with all triton templates? thinking about flexattention here

**Comment by eellison** [comment]
Ugh, it could, but it doesn't right now because I only implemented this for MultiTemplateBuffer and flex_attention has `input_gen_fns` which is NYI for MultiTemplate. 

But it could without much difficulty:

- could handle it with `AllocatedFixedLayout`, as above
- or include it in check [here](https://github.com/pytorch/pytorch/pull/132554/files#diff-cf6ca00beddc32a2a6a2933fb9913b6a2b925ffc3b745488967210e4343134acR4237)

But I wanted to resolve the current, non-max-autotune handling of mms first then can handle it. Like with above, I think returning FlexibleLayout for aten.mm is misleading/buggy. Should not rely on that for cat planning.

**Comment by Chillee** [comment]
> It feels a little bit odd that in the existing code we set the output of aten.mm as [FlexibleLayout](https://github.com/pytorch/pytorch/blob/bcac71517c461765b4fa9efccc6f1a5a475c3544/torch/_inductor/kernel/mm.py#L156) even though its shape and stride are fixed.

I don't actually understand this? Isn't `aten.mm` codegened with an `out` parameter? So its stride isn't actually fixed?

**Comment by eellison** [comment]
Hmm, maybe, I don't know what would actually happen if you pass cublas a weird output stride.

**Comment by eellison** [comment]
Hmm, at least this was about equal:

```
import torch
import triton
from torch._inductor.select_algorithm import extern_kernels

torch.set_default_device('cuda')

inps = [torch.rand([4096, 4096], dtype=torch.float16) for _ in range(2)]
out1 = inps[0].clone()
out2 = inps[0].clone().T

print(triton.testing.do_bench(lambda: extern_kernels.mm(inps[0], inps[1], out=out1)))
print(triton.testing.do_bench(lambda: extern_kernels.mm(inps[0], inps[1], out=out2)))
```

But similarly for FlexAttention - if we just change the layout to be FlexibleLayout, this would work today, but are you okay with the output strides to be potentially non contiguous ?

**Comment by Chillee** [comment]
> are you okay with the output strides potentially being non contiguous

Yeah, i think so. Well, I'd definitely want them to be "contiguous enough".

**Review by jansel — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but I think it is failing on ROCm' -c nosignal

inductor/test_max_autotune.py::TestMaxAutotune::test_conv_cat [GH job link](https://github.com/pytorch/pytorch/actions/runs/11225243935/job/31205072812) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/d558ec07300defee24dd4a83ab4b387a39ea2176)

**Pull request closed without merging**
