### PR TITLE
[JIT] throw if no self arg on ignored methods

### PR DESCRIPTION
**Pull request by eellison**
There was a user who did this and it would seg fault.

### CODE REVIEW

**Review by driazati — COMMENTED** [review]
Can you add a test that this error doesn’t trip if `@staticmethod` is used?

**Comment by eellison** [comment]
> Can you add a test that this error doesn’t trip if `@staticmethod` is used?

It doesn't work, but that's a separate issue imo. 

```
RuntimeError: Argument to @torch.jit.ignore must be a bool or a function but got <staticmethod object at 0x7f896d27c2e8>
```

**Comment by eellison** [comment]
@driazati we should not be holding up PRs that fix seg faults because there related features that don’t work

**Review by suo — APPROVED** [review]

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 45187539:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=451875398e082a1e21aad3043241e3ceca7c933e).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4324494) pytorch_xla_linux_xenial_py3_6_clang7_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=89874172) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=89874172))
<details>
<summary>
<code>Jan 23 17:59:43 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff</code>
</summary>

```
Jan 23 17:59:43 File to patch:  
Jan 23 17:59:43 Skip this patch? [y]  
Jan 23 17:59:43 4 out of 4 hunks ignored 
Jan 23 17:59:43 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-clip_grad.diff 
Jan 23 17:59:43 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff 
Jan 23 17:59:43 Traceback (most recent call last): 
Jan 23 17:59:43   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 67, in <module> 
Jan 23 17:59:43     patch_repo(args) 
Jan 23 17:59:43   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 49, in patch_repo 
Jan 23 17:59:43     raise RuntimeError('Failed to apply patch: {}'.format(ppath)) 
Jan 23 17:59:43 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff 
Jan 23 17:59:43 + cleanup 
Jan 23 17:59:43 + retcode=1 
Jan 23 17:59:43 + set +x 
Jan 23 17:59:43 =================== sccache compilation log =================== 
Jan 23 17:59:43 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 23 17:59:43 Compile requests                 1 
Jan 23 17:59:43 Compile requests executed        0 
Jan 23 17:59:43 Cache hits                       0 
Jan 23 17:59:43 Cache misses                     0 
Jan 23 17:59:43 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Pull request closed without merging**
