### PR TITLE
Cleanup PT-D imports

### PR DESCRIPTION
**Pull request by dstaay-fb**
Summary:
The flow logic around torch.dist imports results in large number of pyre errors (100's); would be preferable to just raise on importing as opposed to silently fail.

Con: Some percentage (MacOS?) of users may have notebooks that imports PT-D, although would think small, since any attempt to call parts of the library would just fail...

TODO: assuming ok, will remove the 10's-100's of unused pyre ignores no longer required.

Test Plan: existing unit tests

Differential Revision: D39842273

### CODE REVIEW

**Review by mrshenli — APPROVED** [review]
The following test and lint failures are irrelevant and is already on master. Stamp to unblock.

```
functorch/test_aotdispatch failed!
Traceback (most recent call last):
  File "test/run_test.py", line 1236, in <module>
    main()
  File "test/run_test.py", line 1200, in main
    raise RuntimeError("\n".join(failure_messages))
RuntimeError: functorch/test_aotdispatch failed!
```

```
redefinition of unused 'meta_index_put' from line 922
```

**Comment by malfet** [comment]
Have to revert the change is it break torch imports if compiled without distributed support, which is the common case of Apple M1 platform. If we say that distributed is inseparable part of PyTorch on all platforms we need to come up with CI/fixes to actually validate that

**Comment by dstaay-fb** [comment]
> Have to revert the change is it break torch imports if compiled without distributed support, which is the common case of Apple M1 platform. If we say that distributed is inseparable part of PyTorch on all platforms we need to come up with CI/fixes to actually validate that

Can you confirm this actually breaks at build time if you use flag USE_DISTRIBUTED=0, or is this purely theoretical argument?   Because as clearly stated in Diff its not expected if users who built w/ USE_DISTIBUTED=0 attempt to import torch.distributed will now raise an  ImportError as opposed to silently and then failing when they to actually use the library.

**Comment by kumpera** [comment]
@dstaay-fb I'm working on an alternative to fix this mess.

**Pull request closed without merging**
