### PR TITLE
(try) remove global `_current_level` variable in forward_ad.py

### PR DESCRIPTION
**Pull request by guilhermeleobas**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #119926
* __->__ #120011
* #119405
* #118407

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Could you give some details on why we want to make this change? The _current_level is only used by the python API and thus doesn't really need to exist in C++

**Comment by guilhermeleobas** [comment]
@albanD, it simplifies implementing `jvp` support on Dynamo. As `_current_level` before was a global variable, and it could not be tracked, I believed.

Happy to elaborate more on this if needed.

**Comment by albanD** [comment]
Dynamo cannot track global variables? That sounds really bad?

**Comment by guilhermeleobas** [comment]
> Dynamo cannot track global variables? That sounds really bad?

I can't say for sure on this. But this change simplifies the quite a bit implementing the `[dual_level](https://github.com/pytorch/pytorch/blob/24d5caba6eb8a4a0eff17a2266345712be6b1374/torch/autograd/forward_ad.py#L22-L60)` context manager on Dynamo.

I'll keep this one as draft and loop with @zou3519 next week to see if this change is actually needed.

**Comment by albanD** [comment]
Ok.
I would still be curious why this helps since you are moving a global from being fully visible for dynamo to being hidden behind abstract functions that have not-so-well-defined global impact. I would expect this to be strictly worse for Dynamo

**Comment by guilhermeleobas** [comment]
I can't say for sure, but context managers are handled different in Dynamo. They sort of need to be reimplemented to work in Dynamo. For instance, the dual_level ctx manager is implemented here
https://github.com/pytorch/pytorch/blob/b10bd46fc7ec3d54f67c8500620b6d148073763c/torch/_dynamo/variables/ctx_manager.py#L270-L304

I had a chat with Richard yesterday and this PR will not be needed anymore. It also don't solve the original issue I was trying to fix. So, I'll just close it.

**Comment by guilhermeleobas** [comment]
Hi @albanD (cc @zou3519 for visibility). I'd like to put this pull request for discussion again as there is a test case in #119926 that would benefit of having a C function that returns the dual level. 

Currently it is not possible to support nested `jvp` calls as its implementation relies on a global variable (`_current_level`) and the [generated FX graph](https://gist.github.com/guilhermeleobas/e5b48e0ac9d78667cc7195d46559ed17) do not carry this information. 

```python
import torch
torch._dynamo.config.capture_func_transforms=True

jvp = torch.func.jvp

def fn(x):
    return jvp(torch.sin, (x,), (x,))

@torch.compile(fullgraph=True)
def foo(x, t):
    return jvp(fn, (x,), (t,))


x = torch.randn(3)
t = torch.randn(3)
y = foo(x, t)
print(y)
```

On the second `jvp` call, the `level` will be None on `forward_ad.make_dual(..., level=None)`. On such case, level then gets assigned to `_current_level`. 

https://github.com/pytorch/pytorch/blob/7b8f6736d1d61f8221c950e2e0427ef711d031e2/torch/_functorch/eager_transforms.py#L970-L972

https://github.com/pytorch/pytorch/blob/7b8f6736d1d61f8221c950e2e0427ef711d031e2/torch/autograd/forward_ad.py#L106-L107

This can be fixed by computing the level with `torch._C._get_current_dual_level()`:

```python
def _jvp_with_argnums(...):
            ...
            with ctx() as dual_level:
                dual_level = torch._C._get_current_dual_level()  # <----
                flat_duals = tuple(fwAD.make_dual(p, t, level=dual_level)
                                   for p, t in zip(flat_primals, flat_tangents))
```

The C function is the only thing that I need. The rest can remain untouched.

**Comment by albanD** [comment]
Sorry I didn't had time to check that.
Why is ` dual_level = torch._C._get_current_dual_level()` better for you than `dual_level = torch.autograd.forward_ad._current_level` ?

**Pull request closed without merging**
