### PR TITLE
Port `argmin` kernel to structured kernels.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#60364 Port `argmin` kernel to structured kernels.**
* #60363 Port `argmax` to structured kernels.
* #60362 Using meta checks for unary `torch.all` and `torch.any`.

Tracking issue: #55070

This PR was openned so as to solve the CI failures in main when merging: #59371 #59372 #59373 #59937 #59938.

Differential Revision: [D29265855](https://our.internmc.facebook.com/intern/diff/D29265855)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29265855).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29265855).

**Comment by ysiraichi** [comment]
6 out of the 7 CI failures doesn't seem to be related to this PR. I'm not sure about the last one, though: `caffe2_tvm-buck`

**Comment by bdhirsh** [comment]
Yep, I think this is ok to land - none of the CI failures look relevant

**Comment by driazati** [comment]
I'm seeing merge conflicts internally when we try to land, could you rebase to `master` and push?

```bash
ghstack checkout https://github.com/pytorch/pytorch/pull/60364
git fetch origin/master
git rebase origin/master
ghstack submit
```

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29265855).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29265855).

**Pull request closed without merging**
