### PR TITLE
Use numpy 2.0.0rc1 in CI

### PR DESCRIPTION
**Pull request by atalman**
Bump numpy version to 2.0.0rc1 in CI

Related to: https://github.com/pytorch/pytorch/issues/107302

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Review by kit1980 — APPROVED** [review]

**Review by ZainRizvi — APPROVED** [review]

**Comment by atalman** [comment]
@malfet looks like all our windows CI tests are on py3.8 we would need to move them to py3.9 and then enable numpy 2.0.0 testing

**Comment by malfet** [comment]
@atalman Why not move them all the way to 3.12?

**Pull request closed without merging**
