### PR TITLE
Clarify meaning of `pin_memory_device` argument

### PR DESCRIPTION
**Pull request by klieret**
I don't think the docstring explaining `pin_memory_device` is very clear. If it weren't for the string type, I would not have guessed that this was about the device that is referred to in the `pin_memory` option (and honestly, it took me a few minutes before noticing the type).

### CODE REVIEW

**Review by ejguan — APPROVED** [review]
LGTM

**Review by NivekT — COMMENTED** [review]
Hi, thanks for opening this PR. I think it looks good and can be merged after the linting is fixed.

**Comment by klieret** [comment]
Thanks @ejguan !

**Pull request closed without merging**
