### PR TITLE
Get rid of quadratic tests to has_same_metadata

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136857

Fixes https://github.com/pytorch/pytorch/issues/136852

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by isuruf — APPROVED** [review]

**Review by bdhirsh — APPROVED** [review]

**Comment by laithsakka** [comment]
this has 20% win on one benchmark

{
  "update_hint_regression": -19.439237957833
}

**Pull request closed without merging**
