### PR TITLE
Default to not build Caffe2 operators on Windows.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#29061 Default to not build Caffe2 operators on Windows.**

It looks like we are too close to the maximum library size on
Windows.  Kill Caffe2 operators to get us lower again.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D18281083](https://our.internmc.facebook.com/intern/diff/D18281083)

### CODE REVIEW

**Comment by gchanan** [comment]
do we know which caffe2 operators are actually exposed?

**Comment by dzhulgakov** [comment]
Maybe add a comment in cmake why it's off by default? (i.e. build size)

To @gchanan's point no C2 operators are exposed for core pytorch documented API surface. They are all used in custom models only.

You can see all of them here: https://github.com/pytorch/pytorch/search?q=C10_EXPORT_CAFFE2_OP_TO_C10_CPU&unscoped_q=C10_EXPORT_CAFFE2_OP_TO_C10_CPU

But they all get exposed in `_caffe2` namespace which is not public and doesn't get referenced beyond tests: https://github.com/pytorch/pytorch/search?p=3&q=_caffe2&unscoped_q=_caffe2

**Comment by soumith** [comment]
does anyone rely on the caffe2 ops being built in linux / OSX? if not we can turn them off to save binary size on these platforms too.

**Comment by ezyang** [comment]
I think there might be some tests which will fail when I turn this off; at least, this was the case when I tried this a while ago.

**Comment by ezyang** [comment]
I'm OK with turning them off universally. But if we have some internal stuff that relies on them this will be a point of divergence between OSS and internal.

**Comment by ezyang** [comment]
Oh, actually, I think we're not allowed to turn these off. Quoting Jeff Petkau:

> Handtracking is currently using the caffe2 dll from the open source pytorch binary distribution, a copy of which is checked in under //third-party/libtorch. We're doing that because it was too hard to build our own and that was the only way we could get a recent Windows versoin working. So I think that would affect us.

At the time, we had been discussing turning off the Caffe2 Windows binary build, which is not the one they used. But this setting controls the Windows PyTorch build. So this diff is no go.

**Review by smessmer — APPROVED** [review]

**Comment by Orvid** [comment]
Out of curiosity, which maximum binary size? As long as you're using the 64-bit hosted toolchain targetting a 64-bit platform, there's not a limit on library size as far as I am aware. (even with the 32-bit hosted toolchain the limit shouldn't be there, although linking will slow down massively if you get too large, as it doesn't have a large enough address space to map things in)

**Comment by ezyang** [comment]
@Orvid None of us are too sure. Do you know how to get this number? We have a diff that induces the OOM and if there's a simple command to run to get this number I can do the experiment.

**Comment by Orvid** [comment]
@ezyang Do you have a link to the diff that triggers the limit in question? The linker itself should fail nicely if things are too large, rather than just OOM'ing.

**Comment by ezyang** [comment]
@Orvid Revert this diff and revert 41e42c34d65f7dce5f526cdb059e860bbe4d0f36 and that should reliably trigger it.

**Pull request closed without merging**
