### PR TITLE
CI: remove numpy_torch_interop from CI

### PR DESCRIPTION
**Pull request by ev-br**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #112075
* #112074
* #112073
* #112071
* #112070
* #112069
* #112068
* #112067
* #112066
* #112065
* #112064
* #112063
* #112062
* #112061
* #112060
* #112059
* #112058
* __->__ #112057

### CODE REVIEW

**Comment by huydhn** [comment]
Umm, please limit the depth of your stack to 5 or smaller and do the change in multiple batches.  The issue here is that all dozen of PR here in the stack will be run at the same time and could potentially eat up all the runners.

cc @ZainRizvi

**Comment by ev-br** [comment]
Apologies about that! Will do from now on --- anything to do from my about this stack, want me to cancel the PRs manually?

**Comment by huydhn** [comment]
> Apologies about that! Will do from now on --- anything to do from my about this stack, want me to cancel the PRs manually?

Yeah, sorry for the troubles, but closing these PRs and re-create them with a smaller stack would help

**Comment by ev-br** [comment]
> closing these PRs and re-create them with a smaller stack would help

Done. My apologies.

**Comment by lezcano** [comment]
I think we were very close to have CI passing in the whole PR, so it may be just fine to land them all together.

**Pull request closed without merging**
