### PR TITLE
[inductor] Reduce block sizes when using Triton CPU backend

### PR DESCRIPTION
**Pull request by int3**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #134725
* __->__ #136612
* #135342

This greatly reduces compile time; TorchBench models that were previously 50-100x slower (vs the cpp backend) are now ~20x slower. More work needs to be done on the Triton side, but smaller block sizes will still be helpful.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by desertfire — APPROVED** [review]

**Comment by Chillee** [comment]
Are you primarily running with max-autotune?

**Comment by int3** [comment]
Yeah, the compile time measurements are using max-autotune.

**Comment by Chillee** [comment]
Perhaps it's better to just turn off max-autotune? The biggest impact it has is in codegening triton matmuls (and autotuning those).

If you just want to search better block sizes perhaps it'd be better to try coordinate descent tuning? https://github.com/pytorch/pytorch/blob/7dc1788396fc9e2860c0c236e0c0e108e96b83c8/torch/_inductor/config.py#L346

**Comment by int3** [comment]
Oh interesting. Switching from max-autotune to coordinate descent tuning makes 60% of the models faster at runtime. Compile times improve for just above 50% of cases, but there are also major regressions for some models...

**Pull request closed without merging**
