### PR TITLE
Reenable XLA workflow/test

### PR DESCRIPTION
**Pull request by yeounoh**
XLA test was disabled [PR](https://github.com/pytorch/pytorch/pull/76237) due to failure. We have reverted the PR, to re-enable the test.

### CODE REVIEW

**Comment by seemethere** [comment]
Oh looks like xla tests are still failing in this PR?

**Comment by yeounoh** [comment]
Yea, I think it's related to this one https://github.com/pytorch/pytorch/pull/76275. I am looking into this, and I will ping you again once it turns green.

**Comment by yeounoh** [comment]
Hi @seemethere it's all green now.

**Comment by yeounoh** [comment]
Ok https://github.com/pytorch/pytorch/runs/6183397614?check_suite_focus=true XLA workflow/test passed. Once all turns green, we can go ahead and merge this PR? cc @zengk95 @seemethere

**Review by seemethere — APPROVED** [review]
LGTM

**Pull request closed without merging**
