### PR TITLE
Update cub to 1.17.2

### PR DESCRIPTION
**Pull request by Skylion007**
Update cub to 1.17.2. Mostly bugfixes, compiler warning fixes and optimizations. Now that we have dropped CUDA 10 support we can update to a much newer version.

### CODE REVIEW

**Comment by ngimel** [comment]
Do we even use third-party cub? I thought we use the one from the toolkit

**Comment by Skylion007** [comment]
@ngimel Should I try deleting the submodule entirely then?

**Comment by Skylion007** [comment]
@ngimel Ah, here use it as a fallback.

**Comment by ngimel** [comment]
The fallback exists from pre-cuda-11 times, when cub wasn't a part of the toolkit. cc @zasdfgbnm, is it ok to always rely on toolkit's cub, or do you foresee times when it would be beneficial to use cub that's newer than toolkit's?

**Comment by malfet** [comment]
@ngimel if I remember correctly, we've used it in the past, when CUB in the toolkit (CUDA-9.2 or something) was too old and buggy. But imo it should be deleted right now and expect that it's always part

**Review by malfet — APPROVED** [review]
I'm fine with the change, but perhaps a better BE change would be to delete it altogether. (considering that the last time it was updated in 2020 and last time this cmake codepath was modified was in 2018)

**Pull request closed without merging**
