### PR TITLE
[ONNX] Create an `optimize` method in ONNXProgram

### PR DESCRIPTION
**Pull request by justinchuby**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137667
* #137666

Move optimization from the export call to the `optimize()` method in ONNXProgram.

Users can call `optimize()` before calling `save()` to save the model. Right now if users set `optimize=True` in `torch.onnx.export` it will have the same effect as calling `optimize()`, but in the future we can evolve the method to be more flexible (e.g. target aware etc.)

Example

```python
onnx_program = torch.onnx.export(..., dynamo=True)
onnx_program.optimize()
onnx_program.save("model.onnx")
```

### CODE REVIEW

**Comment by titaiwangms** [comment]
Although this is good for developer to maintain and debug, from user perspective, it's a change of usage in a way that now they have to call an extra step to have the same performance as torchscript. I think optimize by default might be a better choice.

**Comment by justinchuby** [comment]
Issue with this is the optimizer may fail sometimes, and it will take a much larger effort to bring it to the point where it will run successfully on all possible dtypes, most models etc. So having an option would be good imo. We could all an `optimize=True` option in `export()` too, and default it to true, so users can at least turn it off? The reason I did not do it is that it creates duplicates - one in the export api and the other in the ONNXProgram itself, but that may be the compromise we will have to make.

**Comment by justinchuby** [comment]
Updated to provide the optimize=False api in torch.onnx.export and make it to call this method.

**Review by titaiwangms — APPROVED** [review]

**Pull request closed without merging**
