### PR TITLE
[FSDP] `scatter_full_optim_state_dict()`: async broadcast

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#75603 [FSDP] `scatter_full_optim_state_dict()`: async broadcast**
* #75517 [FSDP] Add `scatter_full_optim_state_dict()`

**To-Do**
- In my understanding, making the broadcasts async may increase max memory usage on target ranks since multiple destination tensors may be allocated and live simultaneously.
- Should we make async an option?
- For a given FSDP parameter's positive-dimension tensor state, is it correct if rank `i` only `wait()`s on the `broadcast()` for its shard but not on the others?
    - From offline discussion, this should be fine.

Differential Revision: [D35565914](https://our.internmc.facebook.com/intern/diff/D35565914)

### CODE REVIEW

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35565914).

**Review by kumpera — CHANGES_REQUESTED** [review]
A cursory survey on NCCL shows that it can run into issue if there are too many collectives at once so there should be a way to enable users disable this behavior.

**Comment by zhaojuanmao** [comment]
agree that we can make async to be optional, considering the potential memory increase and NCCL issues

**Comment by awgu** [comment]
Not for land

**Pull request closed without merging**
