### PR TITLE
fix osd rank0_only in fsdp

### LINKED ISSUE #99135: [FSDP] osd (optim state dict) rank0_only not working
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/blob/master/torch/distributed/fsdp/fully_sharded_data_parallel.py#L1818
```state_dict_settings``` has no ```rank0_only``` attr, leading to ```False``` passed forever.
Thus we cannot use ```FSDP.optim_state_dict``` with ```FullOptimStateDictConfig(rank0_only=True)``` to realize the deprecated ```FSDP.full_optim_state_dict``` .

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0.dev20230413+cu117-with-pypi-cudnn
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Alibaba Group Enterprise Linux Server 7.2 (Paladin) (x86_64)
GCC version: (GCC) 8.3.1 20190604 (Alibaba 8.3.1-1 2.24)
Clang version: Could not collect
CMake version: version 3.26.1
Libc version: glibc-2.24

Python version: 3.8.16 (default, Jan 17 2023, 23:13:24)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.9.151-015.ali3000.alios7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 470.82.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    2
Core(s) per socket:    32
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 106
Model name:            Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz
Stepping:              6
CPU MHz:               3499.859
CPU max MHz:           3500.0000
CPU min MHz:           800.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             48K
L1i cache:             32K
L2 cache:              1280K
L3 cache:              49152K
NUMA node0 CPU(s):     0-31,64-95
NUMA node1 CPU(s):     32-63,96-127
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.1.0+e650d3708b
[pip3] torch==2.1.0.dev20230413+cu117.with.pypi.cudnn
[pip3] torchaudio==2.0.1
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.23.5           py38h14f4228_0  
[conda] numpy-base                1.23.5           py38h31eccc5_0  
[conda] pytorch-triton            2.1.0+e650d3708b          pypi_0    pypi
[conda] torch                     2.1.0.dev20230413+cu117.with.pypi.cudnn          pypi_0    pypi
[conda] torchaudio                2.0.1                    pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

### PR DESCRIPTION
**Pull request by ZhongYingMatrix**
Fixes #99135

### CODE REVIEW

**Comment by awgu** [comment]
This looks good to me, but I am wondering if we should have a unit test. cc: @fegin @wz337

**Comment by awgu** [comment]
Failure looks real:
```
AssertionError: If use_orig_params is True, shard_state must be True.
```

**Comment by fegin** [comment]
> This looks good to me, but I am wondering if we should have a unit test. cc: @fegin @wz337

We do have a UT for rank0_only. Apparently that UT is not correct.

**Comment by ZhongYingMatrix** [comment]
> 



> Failure looks real:
> 
> ```
> AssertionError: If use_orig_params is True, shard_state must be True.
> ```

I run to the same assert error when I scatter_full_optim_state_dict to recover osd, and the model is fsdp with use_orig_param in True. I wonder is it supported to recover osd in rank0_only style?

**Comment by ZhongYingMatrix** [comment]
hi @awgu @fegin , is there any information i could refer to, about this pr and the related UT?

**Comment by fegin** [comment]
@ZhongYingMatrix thanks for the fix the UT fails because `use_orig_params=True` currently is not compatible with `rank0_only=True`. The UT did not fail because the bug you found. We will need to disable the UT for that combination to land the diff. Let me check the UT and get back to you.

**Comment by fegin** [comment]
@ZhongYingMatrix please rebase on top of https://github.com/pytorch/pytorch/pull/99354 which disable the failing test. And you can extend the test https://github.com/pytorch/pytorch/blob/main/test/distributed/fsdp/test_fsdp_optim_state.py#L1807 to test out your PR.

**Comment by ZhongYingMatrix** [comment]
@fegin Thx~ I rebase main banch and force-push it

**Comment by fegin** [comment]
@ZhongYingMatrix `use_orig_params` just does not support `rank0_only=True` yet. To save memory, you can try `sharded_state_dict`. I am working on `use_orig_params`  + `rank0_only=True` but there are some backlogs features/PRs before I'll get to this one.

**Comment by ZhongYingMatrix** [comment]
Thank you, @fegin . I understand now. I'm planning to resume my training (with fsdp added) from a standard torch ckpt, which has osd in ```FULL_STATE_DICT``` format. Therefore, I am looking for scatter_osd while also needing use_orig_params for optim groups (e.g. no weight decay for bias). If possible, I'll work on adding support for ```use_orig_params``` + ```rank0_only``` in a future PR.
All checks have passed. Could you please review this PR? Thank you.

**Review by fegin — APPROVED** [review]

**Comment by fegin** [comment]
@ZhongYingMatrix I'm working on making use_orig_params=True supports rank0_only. Will tag you the PR once it is ready.

**Pull request closed without merging**
