### PR TITLE
Let the build option USE_MIOPEN be truly effective.

### LINKED ISSUE #22200: USE_MIOPEN is not a proper CMake variable
This is mentioned in `setup.py` as configurable, but per `tools/setup_helpers/miopen.py` the actual flag is `NO_MIOPEN`. Also, if you set `USE_MIOPEN=0` when compiling, `setup.py` fails when it tries to build the Python extension. This is caused by CMake not having type information for the USE_MIOPEN variable, because it is not defined anywhere.

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #22228 Remove unnecessary ROCm detection code in Python scripts.
* **#22227  Let the build option USE_MIOPEN be truly effective. #22227**

Currently `USE_MIOPEN` is in fact not effective:

Code within the if-`USE_MIOPEN` clause in CMakeLists.txt is also broken (fixed in this commit). If `USE_MIOPEN` is set to true before this commit, the build would be broken (see the experiment in #22345, test `pr/py2-clang7-rocmdeb-ubuntu16.04`). It never caused issues because it seems that we are not testing with `USE_MIOPEN` set to ON.

Deleted tools/setup_helpers/miopen.py because it is not passing any values to CMake.

Removed `CAFFE2_USE_MIOPEN` because it is not used.

Fix #22200

### CODE REVIEW

**Comment by xuhdev** [comment]
@bddppq I'm actually still a bit puzzled by the build error. Could you help out a bit with the `miopen_handle()` function? Do we currently have a working MIOpen build?

**Comment by bddppq** [comment]
@xuhdev Yes miopen build is working, in fact it's always on. Previously we have agreed with amd engineers on that USE_MIOPEN should be always on (as long as USE_ROCM is on). We should replace all the USE_MIOPEN checks with USE_ROCM checks.
@petrex @iotamudelta

**Comment by xuhdev** [comment]
@bddppq OK, I can remove all `USE_MIOPEN` checks. In fact, I don't even think `USE_MIOPEN` is even used. In #22345, simply setting `USE_MIOPEN` to `USE_ROCM` fails `pr/py2-clang7-rocmdeb-ubuntu16.04`. It seems to me that `USE_MIOPEN` has always been OFF, but the build actually never looks at that build option and enables MIOpen regardless. In fact, code enclosed by `if-USE_MIOPEN` clause in CMakeLists.txt even breaks the build. In this case, are you OK with me simply removing all `USE_MIOPEN` related code, instead of replacing them with `USE_ROCM`?

**Comment by ezyang** [comment]
Yes, that seems reasonable to me.

**Comment by xuhdev** [comment]
Dealt in #22420 . Closing this PR now.

**Pull request closed without merging**
