### PR TITLE
Add LowerSimpleTuples for freeze tuples

### LINKED ISSUE #57698: Freezing doesn't remove tuple operations
## 🐛 Bug

After freezing a traced model, I expect all unnecessary tuple operations to be removed, but some remain.

## To Reproduce

https://colab.research.google.com/gist/dreiss/0414c8e294e482e8a07f98990e7130fc/freezetuple.ipynb

## Expected behavior

No TupleConstruct and TupleUnpack nodes.

## Environment

See notebook.  It reproduces on nightly as well.

## Additional context

Freezing is an awesome feature of TorchScript!

cc @gmagogsfm

### PR DESCRIPTION
**Pull request by charlieHsiuC**
Fixes #57698

Follow the suggestion mentioned in #57698
add a call to LowerSimpleTuples after the call:
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/freeze_module.cpp#L89.

### CODE REVIEW

**Comment by imaginary-person** [comment]
Hello @FloydHsiu, I had opened #57760 two days back for this issue :(

**Comment by FloydHsiu** [comment]
Hi @imaginary-person,
This is my first time ever try to create PR on Github.
I am sorry about that I did not find out that you had already created a PR.
Thank you for giving me this chance to get start.

**Comment by nikithamalgifb** [comment]
@FloydHsiu : Thank you for your contribution. I have requested a review from @eellison.

**Review by eellison — COMMENTED** [review]
Hi, looks good! do you mind adding a small test to `test_freezing` so that this doesn't regress (and as general good practice) ?

**Comment by eellison** [comment]
Looks like we had a race condition! Sorry for the confusion @imaginary-person @FloydHsiu. Next time when you think you are going to work on it do you mind commenting so on the issue ?

**Comment by imaginary-person** [comment]
I'm sorry, @eellison! I'll keep that in mind.

**Comment by FloydHsiu** [comment]
Hi @eellison,
I will try to add a small test to `test_freezing`.
I have already took a look at the code in `test_freezing`.
So I plan to use the code like below as example, and check if there is no TupleConstruct and TupleUnpack node after freeze.
```python
class Bot(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, arg):
        return arg + 1, arg + 2
    
class Top(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.bot = Bot()
    def forward(self, arg):
        a1, a2 = self.bot(arg)
        return a1 + a2
```
Does this make sense?

> Looks like we had a race condition! Sorry for the confusion @imaginary-person @FloydHsiu. Next time when you think you are going to work on it do you mind commenting so on the issue ?

Sorry that I don't understand where is the race condition occur, or what your meaning.
Can you tell more detail about that?

**Comment by FloydHsiu** [comment]
> Looks like we had a race condition! Sorry for the confusion @imaginary-person @FloydHsiu. Next time when you think you are going to work on it do you mind commenting so on the issue ?

@eellison, 
Sorry, I am not native in English so it take me some time to understand what your meaning.
I even misunderstand that the code I send lead to race condition. lul.
Next time I will leave a comment first if I want to work on that issus.

**Comment by eellison** [comment]
Hi @FloydHsiu, a [race condition](https://en.wikipedia.org/wiki/Race_condition) is when two threads interact with the same resource in a way they shouldn't leading to bad results (I was making a joke).

**Comment by FloydHsiu** [comment]
Hi @eellison,
I finished the initial version.
I am not sure if the function name is OK?
Or can you give me some advice?

**Comment by nikithamalgifb** [comment]
@FloydHsiu : Do not forget to fix the merge conflicts for all the CircleCI job fails.

**Review by eellison — APPROVED** [review]
Nice, LGTM !

**Pull request closed without merging**
