### PR TITLE
Enable additional inductor test suites on ROCm

### PR DESCRIPTION
**Pull request by jataylo**
Enables additional inductor UTs on ROCm, following from https://github.com/pytorch/pytorch/pull/100981

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @aakhundov

### CODE REVIEW

**Comment by jataylo** [comment]
The distributed ROCm failure is unrelated to the PR, the test_inductor_collectives and test_dynamo_distributed suites enabled by this PR pass to completion

**Comment by jithunnair-amd** [comment]
@jataylo Looks like this PR is stale, will need to resolve conflicts before requesting review again.

**Comment by jataylo** [comment]
@kit1980 @malfet Opening up this PR for review again if you are able to take a look. 

The only fail here seems to be an ongoing/flakey issue https://hud.pytorch.org/failure/nn%2Ftest_pooling.py%3A%3ATestPoolingNNDeviceTypeCUDA%3A%3Atest_MaxUnpool_index_errors_case2_cuda

cc: @jithunnair-amd

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
