### PR TITLE
Enable builtin tests for ONNX Export with ExportedProgram models

### PR DESCRIPTION
**Pull request by thiagocrepaldi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #115380
* __->__ #114762

Fixed by https://github.com/pytorch/pytorch/pull/113982

### CODE REVIEW

**Review by BowenBao — APPROVED** [review]

**Review by titaiwangms — COMMENTED** [review]
Do you know why this xfail wasn't deleted when the fix applied? This is indicating the tests is passing/xfailing at the same time? Am I missing something? 🤔

**Comment by titaiwangms** [comment]
> > Do you know why this xfail wasn't deleted when the fix applied? This is indicating the tests is passing/xfailing at the same time? Am I missing something? 🤔
> 
> Can you elaborate on the issue? `xfail_if_model_type_is_exportedprogram` is deleted on this PR and tests are passing.

I am wondering how this xfail still survived when it's fixed. I thought we would get unexpected success, and failed CI.

**Comment by thiagocrepaldi** [comment]
> > > Do you know why this xfail wasn't deleted when the fix applied? This is indicating the tests is passing/xfailing at the same time? Am I missing something? 🤔
> > 
> > 
> > Can you elaborate on the issue? `xfail_if_model_type_is_exportedprogram` is deleted on this PR and tests are passing.
> 
> I am wondering how this xfail still survived when it's fixed. I thought we would get unexpected success, and failed CI.

There were 2 issues related to numeric operators. The second one was uncovered by ExportedProgram and it was fixed only yesterday

**Comment by titaiwangms** [comment]
I see what's going on: `pytest.xfail` doesn't do the same as `unittest.ExpectedFailure`. `pytest.xfail` is just pretty print, but doesn't actually guard xfail.

https://github.com/pytorch/pytorch/blob/18d57dde2dc0d4a5be588c02276e4e71e75d777e/test/onnx/pytorch_test_common.py#L333-L388

**Comment by titaiwangms** [comment]
> > I see what's going on: `pytest.xfail` doesn't do the same as `unittest.ExpectedFailure`. `pytest.xfail` is just pretty print, but doesn't actually guard xfail.
> > https://github.com/pytorch/pytorch/blob/18d57dde2dc0d4a5be588c02276e4e71e75d777e/test/onnx/pytorch_test_common.py#L333-L388
> 
> Not sure about that. From https://github.com/pytest-dev/pytest/blob/main/src/_pytest/outcomes.py#L231
> 
> ```python
> @_with_exception(XFailed)
> def xfail(reason: str = "") -> NoReturn:
>     """Imperatively xfail an executing test or setup function with the given reason.
> 
>     This function should be called only during testing (setup, call or teardown).
> 
>     :param reason:
>         The message to show the user as reason for the xfail.
> 
>     .. note::
>         It is better to use the :ref:`pytest.mark.xfail ref` marker when
>         possible to declare a test to be xfailed under certain conditions
>         like known bugs or missing features.
>     """
>     __tracebackhide__ = True
>     raise XFailed(reason)
> ```

Without this PR, the CI still passing suggests this xfail test doesn't do the same thing as unittest.ExpectedFailure. Otherwise, it fails with unexpected success.

**Comment by huydhn** [comment]
@thiagocrepaldi It looks like onnx job in trunk is failing after this change https://hud.pytorch.org/pytorch/pytorch/commit/13d2e3eba79000028291f4739a6e9c937dbe4264, but not on the PR.  Could you help help take a look?  Please feel free to revert and reland the change if you need to debug it further

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but ONNX test is failing from this commit https://hud.pytorch.org/pytorch/pytorch/commit/13d2e3eba79000028291f4739a6e9c937dbe4264' -c nosignal

I need to revert the change to unblock viable/strict and nightly branches update

**Comment by thiagocrepaldi** [comment]
Blocked by https://github.com/pytorch/pytorch/pull/115271

**Pull request closed without merging**
