### PR TITLE
flake8 version reporting in collect_env

### LINKED ISSUE #94571: flake8 version reporting in collect_env
### 🚀 The feature, motivation and pitch

# Feature
Add flake8 version reporting to https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py
This should be a one line change in `def get_pip_packages(run_lambda):`
```
                for name in {
                    "torch",
                    "numpy",
                    "mypy",
                    "flake8", # add this
                }
```

# Motivation
Flake8 is an important Pytorch and torchvision development dependency but does not get reported in collect_env unlike other packages such as mypy. This hinders troubleshooting differences between contributors environments as demonstrated by https://github.com/pytorch/vision/issues/7200 

### Alternatives

_No response_

### Additional context

I'm happy to make the PR if this is useful

### PR DESCRIPTION
**Pull request by mpearce25**
Fixes #94571

# Testing
`[pip3] flake8==3.9.2` now appears under `Versions of relevant libraries:`
when running: `python torch/utils/collect_env.py`
### Output with this change
```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 13.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz

Versions of relevant libraries:
[pip3] flake8==3.9.2
[pip3] mypy==0.971
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           hecd8cb5_637
[conda] mkl-service               2.4.0            py39h9ed2024_0
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0
[conda] mkl_random                1.2.2            py39hb2f4e1b_0
[conda] numpy                     1.21.5           py39h2e5f0a9_1
[conda] numpy-base                1.21.5           py39h3b1a694_1
[conda] numpydoc                  1.2                pyhd3eb1b0_0
```
### Output before
```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 13.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz

Versions of relevant libraries:
[pip3] mypy==0.971
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           hecd8cb5_637
[conda] mkl-service               2.4.0            py39h9ed2024_0
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0
[conda] mkl_random                1.2.2            py39hb2f4e1b_0
[conda] numpy                     1.21.5           py39h2e5f0a9_1
[conda] numpy-base                1.21.5           py39h3b1a694_1
[conda] numpydoc                  1.2                pyhd3eb1b0_0
```

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by mpearce25** [comment]
I signed the CLA, but the check is still failing. I don't appear to have the ability to re-run failed jobs. Any fixes?

**Comment by mpearce25** [comment]
@malfet Anything I should do to get this merged in? 

The policy for merging PRs with failing CI isn't clear to me. The contribution guide https://pytorch.org/docs/stable/community/contribution_guide.html says wait till it passes, but it looks like many PRs get merged with failing tests.

**Comment by kit1980** [comment]
@mpearce25 could you resolve the conflicts?

**Comment by mpearce25** [comment]
> @mpearce25 could you resolve the conflicts?

Resolved. Anything I need to do for merge?

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
