### PR TITLE
Add hooks to Scheduler nodes for generating device-specific debug strings

### PR DESCRIPTION
**Pull request by abulavin**
Previously, instances of `SchedulerNode` and `FusedSchedulerNode` would explicitly check whether the compilation target is Triton when codegen'ing debug strings. Generating debug triton code is instead implemented as a callback set on scheduler nodes by `TritonScheduling`. This makes the codegen more device-agnostic and allows schedulers to customise the codegen output as opposed to it being closely coupled to the debug string codegen

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jansel — APPROVED** [review]
lgtm, but you need to sign the CLA

**Comment by abulavin** [comment]
@jansel the CLA has been signed, could you please approve the pull workflow for this PR? Thanks.

**Comment by jansel** [comment]
Looks like tests are failing.  You could try rebasing on the `viable/strict` branch.

**Comment by jansel** [comment]
I think the test failures might be real.  It is failing an assert on the expected value of a debug string.

**Review by jansel — CHANGES_REQUESTED** [review]
Fix test failures and re-request review.

**Comment by abulavin** [comment]
@jansel I believe the tests are fixed now, would you mind giving this another review? Thanks.

**Review by jansel — APPROVED** [review]

**Comment by jansel** [comment]
@pytrochbot merge

**Pull request closed without merging**
