### PR TITLE
Forward fix type hint for DataLoader

### PR DESCRIPTION
**Pull request by ejguan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #66001

Differential Revision: [D31340565](https://our.internmc.facebook.com/intern/diff/D31340565)

### CODE REVIEW

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31340565).

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31340565).

**Comment by ejguan** [comment]
The remaining mypy error is not related to DataLoader

**Review by NivekT — APPROVED** [review]
LGTM since the remaining mypy error seems unrelated to this fix.

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31340565).

**Pull request closed without merging**
