### PR TITLE
Migrate linux-test Job yo ARC

### PR DESCRIPTION
**Pull request by DanilBaibak**
Migrate linux-test Job yo ARC

* Separated `_linux-test-label.yml` workflow to use the `label`;
* Separated `_linux-test-rg.yml` workflow to use the `group`;

### CODE REVIEW

**Comment by DanilBaibak** [comment]
Tested both workflows `_linux-test-label.yml` and `_linux-test-rg.yml`:
Screenshot 2024-04-22 at 16 50 41

**Review by zxiiro — APPROVED** [review]

**Review by jeanschmidt — APPROVED** [review]

**Comment by DanilBaibak** [comment]
@pytorcchbot merge -f "the changes will not affect any workflow"

**Comment by jeanschmidt** [comment]
FYI, PR title does not relate to anything of what this PR is actually doing.

**Pull request closed without merging**
