### PR TITLE
Refactor dtype propagation

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #141495
* #140057
* __->__ #139945

A couple changes.

- Tries to reuse dtype propagation rules that were already registered in inductor. These were present both with `pointwise_overrides_data` and the `boolean_ops` list. Additionally, the registration of pointwise ops already specified dtype propagation rules. Saves those registrations and reuses them later.

- Factors out `get_promoted_dtype` which uses functools.lru_cache to take in non - CSEVariable args because those will not work with the functools cache.

Tests get added later in the stack when everything is implemented.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by blaine-rister — APPROVED** [review]
LGTM! Thanks for the refactor.

**Review by arui-meta — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
This appears to cause a compile time regression: https://fburl.com/scuba/torch_open_source_signpost/5tti7eql

image

**Comment by laithsakka** [comment]
sounds expected as test files has changed, but just adding it as another ref point

Screenshot 2024-12-02 at 8 15 17 AM

https://www.internalfb.com/intern/unidash/dashboard/pt2_diff_time_metrics

**Comment by eellison** [comment]
Fix should be here: https://github.com/pytorch/pytorch/pull/141882

**Pull request closed without merging**
