### PR TITLE
Linear bias fusion for ND input

### PR DESCRIPTION
**Pull request by NiceiceCC**
Summary:
Use admm for linear op with bias for ND input #39661
On A100, speed is increased by about 15% (fp16)
Example:
in_featuers = 1024, out_features=512,   data_size = (512, 256, 1024)
before this commit: 100 TF/s (mean from 1000 tests)
after this commit: 118 TF/s (mean from 1000 tests)

Test Plan: Correctness: buck test mode/dev-nosan -c fbcode.nvcc_arch=a100 //caffe2/test:linalg_cuda -- test_addmm_cuda

Differential Revision: D34477884

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Are >3D inputs (meaning >1 batch dimensions) different in this regard?

**Comment by vadimkantorov** [comment]
@stas00 I guess after this is merged, custom HG Linear could be retired

**Comment by stas00** [comment]
retired not, since HF Transformers has to support older pytorch versions, but for pt-1.12 if there is a nice speed up it's always welcome.

**Comment by NiceiceCC** [comment]
> Are >3D inputs (meaning >1 batch dimensions) different in this regard?
> 
> It seems that in the code you're doing `input.dim() > 2`, so I guess a little mismatch with the PR title :)

It was for 3D and then modified for ND inputs. I changed the title and summary in Phabricator but it was unchanged when I export it. Thanks for pointing out.

**Pull request closed without merging**
