### PR TITLE
[Inductor] Fix wrong CSEVariable dtype for reduction. Fix #141861

### LINKED ISSUE #141861: [Break XPU] Triton kernel generated for XPU can not pass runtime_triton_dtype_assert.
### 🐛 Describe the bug

The PR #141495 introduced runtime_triton_dtype_assert that check the dtype in triton kernel, and XPU can not pass the check in the test case `test_torchinductor_opinfo.py:test_comprehensive_masked_cumprod_xpu_float16`:
```
 in compile
    module = src.make_ir(options, codegen_fns, module_map, context)
  File "/home/xinanlin/xinanlin/miniforge3/envs/torch-py3.9/lib/python3.9/site-packages/triton/compiler/compiler.py", line 101
, in make_ir
    return ast_to_ttir(self.fn, self, context=context, options=options, codegen_fns=codegen_fns,
triton.compiler.errors.CompileTimeAssertionFailure: at 65:4:
    tmp14 = tmp0 * tmp13
    tl.static_assert(tmp14.dtype == tl.float32)
    tmp15 = tl.broadcast_to(tmp14, [XBLOCK, RBLOCK])
    tmp17 = tl.where(rmask, tmp15, 0)
    tmp18 = tl.sum(tmp17, 1)[:, None]
    tl.static_assert(tmp1.dtype == tl.int32)
    tl.static_assert(tmp2.dtype == tl.int64)
    tl.static_assert(tmp3.dtype == tl.int1)
    tl.static_assert(tmp1.dtype == tl.int32)
    tl.static_assert(tmp4.dtype == tl.int64)
    tl.static_assert(tmp5.dtype == tl.int1)
    tl.static_assert(tmp18.dtype == tl.float16)
    ^


The above exception was the direct cause of the following exception:

```

### Versions

PyTorch version: 2.6.0a0+gitf83361b
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.4
Libc version: glibc-2.35

Python version: 3.9.20 | packaged by conda-forge | (main, Sep 30 2024, 17:49:10)  [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-5.15.47+prerelease23.5.18-x86_64-with-glibc2.35

cc @gujinghui @EikanWang @fengyuan14 @guangyey

### PR DESCRIPTION
**Pull request by etaf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #142189

Fix #141861

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by jansel — APPROVED** [review]
Add a test?

**Comment by etaf** [comment]
> Add a test?

@jansel  thanks for  your time, there is a test case for this. The issue is exposed in `test_torchinductor_opinfo.py:test_comprehensive_masked_cumprod_cuda_float16`, it only exposed on XPU because CUDA generate a different fx_graph for this case.

**Comment by chuanqi129** [comment]
Hi @huydhn, with you and @etaf's help, the PR https://github.com/pytorch/pytorch/pull/142298 has been landed. But I noticed that this PR xpu 2025.0 images still need rebuilt both in build and test ci job. Do you know the reason of it?
Refer: https://github.com/pytorch/pytorch/actions/runs/12222147533/job/34092075850#step:7:1

**Pull request closed without merging**
