### PR TITLE
Install an excepthook which annotates exceptions with rank information when distributed is initialized

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #118190

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Comment by ezyang** [comment]
This has a lot of limitations. It doesn't work with multiprocess spawned subprocesses, because of https://stackoverflow.com/questions/47815850/python-sys-excepthook-on-multiprocess

**Review by Skylion007 — APPROVED** [review]

**Review by kwen2501 — APPROVED** [review]
LGTM

**Comment by ezyang** [comment]
PSA for future readers: if you have found this PR because you hate the change here, let's revert it. The goal is to see if this is any improvement at all.

**Comment by carmocca** [comment]
I don't hate this by any means, but I find it odd that this was put inside `init_process_group` with no flag to turn it off. Making it a utility function would have been more pytorch-y, if I may say so.

**Comment by ezyang** [comment]
@carmocca OK, so just to confirm, you want to revert this as it exists today? :)

**Pull request closed without merging**
