### PR TITLE
inline context manager aten codegen 13s -> 11s

### PR DESCRIPTION
**Pull request by albanD**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #59852 pre compute regex and match simple signature autograd codegen 15s -> 12s
* **#59851 inline context manager aten codegen 13s -> 11s**
* #59850 refactor yaml loader import, no runtime change
* #59849 Use C dumper if possible aten codegen 23s -> 13s
* #59848 avoid error string formatting aten codegen 28s -> 23s
* #59847 Avoid unnecessary re-computation autograd codegen 21s -> 15s

This whole stack does not change anything to the codegened code

The benefit from this PR is not as big as the others. If you think that this is not worth the code duplication, let me know, I'm happy to drop this PR.

Differential Revision: [D29063813](https://our.internmc.facebook.com/intern/diff/D29063813)

### CODE REVIEW

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29063813).

**Comment by ezyang** [comment]
Yeah, I'm not too hot on this one. Maybe we can check and see if this decorator is being called too often, or short circuit it if someone has already applied the guard?

**Comment by albanD** [comment]
Ho yes, I did that because after checking with the profiler, this gets called almost 500k times when generating the aten codegen.
Since I couldn't find a way to reduce the number of calls, I reduced the function overhead itself.

**Comment by ezyang** [comment]
500k is too many times. It should be called number of operators * distinct "codegen" things (on the order of 100 or something). 500k is probably because people just slapping it everywhere yolo

**Comment by albanD** [comment]
Even if they do, these calls are actually never nested :o 
So I guess we want to move the context higher in the stack.

**Comment by albanD** [comment]
Closing as a won't fix for now.
The perf is good enough and this leads to pretty bad looking code for a small perf benefit.

**Pull request closed without merging**
