### PR TITLE
[quant][graphmode][fx] Remove logging for standalone module api calls

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#47032 [quant][graphmode][fx] Remove logging for standalone module api calls**

Summary:
these are not top level apis, not supposed to be called directly by user.

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D24610602](https://our.internmc.facebook.com/intern/diff/D24610602)

### CODE REVIEW

**Comment by vkuzo** [comment]
what's the motivation for removing this, just curious?  There is value in having this data, in order to understand how common this use case is.

**Comment by jerryzh168** [comment]
> what's the motivation for removing this, just curious? There is value in having this data, in order to understand how common this use case is.

hmm, this is not a top level api. if we want to track how often each different sub types of configuration is used, might be good to have more comprehensive coverage? like all items in qconfig_dict, prepare_custom_config_dict and convert_custom_config_dict should be tracked?

**Review by vkuzo — APPROVED** [review]
It's nice to have this data now with 0 additional eng cost, but I don't feel strongly.

**Comment by jerryzh168** [comment]
> It's nice to have this data now with 0 additional eng cost, but I don't feel strongly.

right, I don't feel strongly either..this is just a nit change so that we only track top level apis, doing this mostly for consistency..

**Comment by jerryzh168** [comment]
oh actually, is this data useful? I thought we only want to track the progress of people moving from other quantization apis to fx graph mode?

**Pull request closed without merging**
