### PR TITLE
Fix endian handling in THPStorage_fromBuffer

### LINKED ISSUE #92831: Test failure: TestTorch.test_from_buffer on a big-endian machine
### 🐛 Describe the bug

I found that the following test causes a failure (generate unexpected value) on a big-endian machine. We expect that this test also passes on a big-endian machine.

```
% python test/test_torch.py TestTorch.test_from_buffer

======================================================================
FAIL: test_from_buffer (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ishizaki/PyTorch/master/torch/testing/_internal/common_utils.py", line 968, in wrapper
    fn(*args, **kwargs)
  File "/home/ishizaki/PyTorch/master/test/test_torch.py", line 6370, in test_from_buffer
    self.assertEqual(shorts.tolist(), [258, 772])
  File "/home/ishizaki/PyTorch/master/torch/testing/_internal/common_utils.py", line 2934, in assertEqual
    assert_equal(
  File "/home/ishizaki/PyTorch/master/torch/testing/_comparison.py", line 1244, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Scalars are not equal!

Absolute difference: 255
Relative difference: 0.9883720930232558

The failure occurred for item [0]
```

### Versions

```
PyTorch version: 2.0.0a0+git215f4fc
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (s390x)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-125-generic-s390x-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.0a0+gitafe6ea8
[conda] Could not collect
```

### PR DESCRIPTION
**Pull request by kiszk**
Fixes #92831

This PR fixes a test failure of `TestTorch.test_from_buffer` on a big-endian machine. The root cause of this failure is that current `THPStorage_fromBuffer` does not perform endian handling correctly on a big-endian.

In `THPStorage_fromBuffer`, the given buffer is stored as machine native-endian. Thus, if the specified byte order (e.g. `big`) is equal to machine native-endian, swapping elements should not be performed. However, in the current implementation, [`decode*BE()`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/byte_order.cpp#L72-L109) always swaps elements regardless of machine native-endian (i.e. these methods assume buffer is stored as little-endian).

Thus, this PR uses the following approaches:
- if the specified byte order (e.g. `big`) is equal to machine native-endian, call `decode*LE()` that does not swap elements by passing `torch::utils::THP_LITTLE_ENDIAN` to `THP_decode*Buffer()`.
- if the specified byte order (e.g. `big`) is not equal to machine native-endian, call `decode*BE()` that always swap elements by passing `torch::utils::THP_BIG_ENDIAN` to `THP_decode*Buffer()`.

After applying this PR to the master branch, I confirmed that the test passes on a big-endian machine.

```
% python test/test_torch.py TestTorch.test_from_buffer
/home/ishizaki/PyTorch/master/test/test_torch.py:6367: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  self.assertEqual(torch.ByteStorage.from_buffer(a).tolist(), [1, 2, 3, 4])
...
/home/ishizaki/PyTorch/master/test/test_torch.py:6396: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  self.assertEqual(bytes.tolist(), [1, 2, 3, 4])
.
----------------------------------------------------------------------
Ran 1 test in 0.021s

OK
```

### CODE REVIEW

**Comment by kiszk** [comment]
Another possible approach is to add a new argument to [`THP_decode*Buffer()`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/byte_order.cpp#L121-L281) for representing endianness of a given buffer. These methods will determine whether swap elements or not based on the comparison between `order` and the new argument.

**Review by kurtamohler — COMMENTED** [review]
I think there are some conceptual/naming issues that need to be fixed.

As you pointed out, `decode*BE()` always swaps elements regardless of the endianness of the buffer or the machine. So `decode*LE()` and `decode*BE()`'s names seem wrong to me. They should probably be renamed to `decode*()` and `decode*WithSwap()` or something like that.

https://github.com/pytorch/pytorch/blob/63e47c68a692c70bc64c49d687f85f7f5cd02ce3/torch/csrc/utils/byte_order.cpp#L85-L96

Because of that, the `THPByteOrder` args to `THP_decode*Buffer` also don't mean what they claim to mean.  If you provide `THP_LITTLE_ENDIAN` to a `THP_decode*Buffer()` function, it just copies without a byte swap. If you provide `THP_BIG_ENDIAN` to a `THP_decode*Buffer()` function, it copies with a byte swap. So at the moment, `THP_LITTLE_ENDIAN` actually means "don't swap" and `THP_BIG_ENDIAN` means "do swap".

https://github.com/pytorch/pytorch/blob/63e47c68a692c70bc64c49d687f85f7f5cd02ce3/torch/csrc/utils/byte_order.cpp#L133-L143

Because of this, the logic in the code you fixed in this PR functions correctly, but it's confusing. For instance, if `THPStorage_fromBuffer` is given `byte_order_str == "native"`, you set `byte_order = torch::utils::THP_LITTLE_ENDIAN;`, even if the machine happens to be big endian.

I think there are two main ways we could fix the `THP_decode*Buffer` functions, and I'm not sure which is best:

1. Add some logic inside the `THP_decode*Buffer` functions to check the machine's endianness. If it differs from the `order` arg, then decode with swap. Otherwise decode without swap. I'm not sure if there's a problem with checking the machine's endianness inside these functions or not.

2. Change the `THPByteOrder order` arg of the `THP_decode*Buffer` functions to just be `bool do_byte_swap` (or similar name)

I think I like option 2 more since it doesn't change any logic, it's just renaming things to reflect what's actually going on. Let me know what you think

**Comment by kiszk** [comment]
@kurtamohler Thank you for explaining my fix and thoughts in detail. You completely understand what I want to do in this PR and how I minimize the change. I know that my first PR may lead to confusion.

My current preference is 2'. 2' means that we **newly add** the `THP_decode*Buffer` functions by replacing `order` with `bool do_byte_swap` (or similar name) instead of changing the existing API.

Let me share my thought about 1. and 2.

For 2., `THP_decode*Buffer` functions are declared with [`TORCH_API`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/byte_order.h#L16-L65). IMHO, these APIs are already public. Thus, I think that it is good to keep the existing API with the current interface and semantics (buffer is LE). If we can change the interface and semantics, it is fine with me to **change** `THP_decode*Buffer` functions.

For 1., currently, there are two use cases of `THP_decode*Buffer` functions. The first one is to call these functions from `THPStorage_fromBuffer` that assumes the buffer is stored as machine native-endian. The second one is to call these function from [`THPStorage_readFileRaw()`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/serialization.cpp#L368-L385) that assumes the buffer is stored as little-endian. So, IMHO, in addition to machine's endianness check, we need to pass the endian of buffer to `THP_decode*Buffer` functions. Again, this may change the existing API of `TORCH_API` functions.   
If calling `THP_nativeByteOrder()` leads to a performance problem, we can change this function to return a constant by compile-time evaluation.

**Comment by ezyang** [comment]
(2) sounds good

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
