### PR TITLE
Fix missing mandatory device_type argument in autocast docstring

### PR DESCRIPTION
**Pull request by ashok-kumar-kannan**
Fixes #[92803](https://github.com/pytorch/pytorch/issues/92803)
Screenshot from 2023-03-21 12-28-14
Screenshot from 2023-03-21 12-28-29
Screenshot from 2023-03-21 12-29-36

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks for the update!

**Comment by albanD** [comment]
Could you take a look at the CLA please so that this can be merged.

**Comment by kit1980** [comment]
@ashok-kumar-kannan Are you still interested in merging this?
Please sign the CLA so this can me merged.

**Comment by ashok-kumar-kannan** [comment]
Hi @albanD ,
We are working on the CLA signing process.

**Review by albanD — APPROVED** [review]
Looks good!

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
