### PR TITLE
Add device extensions to the test framework for supporting custom device

### PR DESCRIPTION
**Pull request by Bin1024**
Fixes #ISSUE_NUMBER
add a PrivateUse1TestBase in torch/testing/_internal/common_device_type.py for supporting custom device extensions "privateuse1", and add “device_type" parameter in instantiate_device_type_tests function for adding custom device testbase, the default value is None.

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
I would like to get a better understanding on how you're planning to do privateuse1 testing holistically before looking into the details of the code.
Would you be able to provide some details on that? Do you want inputs from our end?
In either case, if we need to have a discussion about this, please open an issue to be able to have these discussions.

**Comment by Bin1024** [comment]
> I would like to get a better understanding on how you're planning to do privateuse1 testing holistically before looking into the details of the code. Would you be able to provide some details on that? Do you want inputs from our end? In either case, if we need to have a discussion about this, please open an issue to be able to have these discussions.

We plan to add the privateuse1 interface to the test framework so that third-party devices can use the test cases of the community. The specific method is to copy the test cases of the community to the local host and test the privatesuse1 device through the privateuse1 interface of the test framework. During code modification, the default device type is None, which does not change the original test logic. @albanD

**Comment by Bin1024** [comment]
> > add the privateuse1 interface to the test framework
> 
> I'm not sure to grasp what that means and what that entails?
> 
> Also I think there are two distinct side of testing we need to clarify:
> 
> * How do we test privateuseone features within PyTorch on our CI that only has CPU hardware?
> * How to make it easy for third party repo that use privateuseone to test their integration and hardware works properly?



> > add the privateuse1 interface to the test framework
> 
> I'm not sure to grasp what that means and what that entails?
> 
> Also I think there are two distinct side of testing we need to clarify:
> 
> * How do we test privateuseone features within PyTorch on our CI that only has CPU hardware?
> * How to make it easy for third party repo that use privateuseone to test their integration and hardware works properly?

Thank you for your reply.
1. For the first question, we do not plan to use the CI of your community. Our method is to copy some test cases to the local host and test privateuse1 by providing the privateuse1 interface for the test instantiation method. This approach does not affect your CI and test framework.
2. For the second question, the privateuse1 registration method has been provided in the community. For the registered privateuse1, you can specify the device to be tested by adding the “device_type” parameter to the ”instantiate_device_type_tests“ method.
Looking forward to your reply.   @albanD

**Comment by Bin1024** [comment]
> > add the privateuse1 interface to the test framework
> 
> I'm not sure to grasp what that means and what that entails?
> 
> Also I think there are two distinct side of testing we need to clarify:
> 
> * How do we test privateuseone features within PyTorch on our CI that only has CPU hardware?
> * How to make it easy for third party repo that use privateuseone to test their integration and hardware works properly?

Thank you for your reply.

For the first question, we do not plan to use the CI of your community. Our method is to copy some test cases to the local host and test privateuse1 by providing the privateuse1 interface for the test instantiation method. This approach does not affect your CI and test framework.
For the second question, the privateuse1 registration method has been provided in the community. For the registered privateuse1, you can specify the device to be tested by adding the “device_type” parameter to the ”instantiate_device_type_tests“ method.
Looking forward to your reply. @albanD

**Comment by albanD** [comment]
> For the first question, we do not plan to use the CI of your community. 

I don't think this is a good approach if you're looking for stability.
In particular, the integration in all the components do need to be tested in PyTorch core. As a general statement, there is so much happening in the codebase that if something is not tested, it is pretty much guaranteed to be broken in a couple months.

To that end, I think it would be very beneficial to have a mostly full fledged custom device (backed by regular CPU memory/compute) that lives in the test suite so that every component can be fully tested with a "real" out of tree device. I think it is the only way to ensure that these integration are kept working going forward.

I would be open to also adding this custom device to the list of device tested via our device-generic tests in `instantiate_device_type_tests`. This is the best way to ensure that it stay working the way we want going forward without you discovering it when you upgrade PT in your own repo!

**Comment by Bin1024** [comment]
> I would be open to also adding this custom device to the list of device tested via our device-generic tests in `instantiate_device_type_tests`. This is the best way to ensure that it stay working the way we want going forward without you discovering it when you upgrade PT in your own repo!
With this PR, we can test third party devices based on the community's ci or test cases. Currently we have been able to implement third-party device testing by providing the "device_type" parameter through the test instantiation function "install_device_type_tests" and it has helped us a lot. I think this is useful for third-party devices that want to be developed based on pytorch, and to be able to maintain third-party devices.

Our goal is that the community can provide test interface to the third party device privateuse1 to test whether privateuse1 implements the functionality of pytorch. For this PR, can you give some advice if we want to reach our goal or merge into the community.  @albanD

**Review by albanD — APPROVED** [review]
SGTM
Thanks

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
