### PR TITLE
Remove obsolete code from build.sh

### PR DESCRIPTION
**Pull request by kit1980**

### CODE REVIEW

**Comment by vors** [comment]
btw, what types of GPUs are used in CI, what's the sm?

**Comment by kit1980** [comment]
> btw, what types of GPUs are used in CI, what's the sm?

From the logs it's Tesla M60, so looks like shader model 6.4.

**Comment by kit1980** [comment]
> > btw, what types of GPUs are used in CI, what's the sm?
> 
> From the logs it's Tesla M60.

Which seems to correspond to `TORCH_CUDA_ARCH_LIST="5.2"`, as set in https://github.com/pytorch/pytorch/blob/55aa0b1a840e7bf5c53c8e457abf85ded92317eb/.jenkins/pytorch/build.sh#L161

**Comment by kit1980** [comment]
The periodic failure is pre-existing.

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
