### PR TITLE
Make distributed raise ImportError when not available

### PR DESCRIPTION
**Pull request by albanD**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #75975

### CODE REVIEW

**Review by mrshenli — APPROVED** [review]
Lint errors are real. Stamp to unblock.

```
[MYPY] [name-defined]: Name 'dist' is not defined 
```

**Comment by albanD** [comment]
Yes that PR raced with another one :/ 
The one below is a bit tricky to land. So I'll wait for that to happen first and then rebase/fix and then land this.

Thanks for the quick review!

**Comment by albanD** [comment]
Ready to land now!

**Pull request closed without merging**
