### PR TITLE
[DCP] minor readability fix: make param name consistent with overriden function

### PR DESCRIPTION
**Pull request by teja-rao**
Summary:
This diff has no logic changes. It updates the variable names to be in sync with the name used in prepare_global_plan in StorageWriter. Pasting func signature for easy reference -

    abc.abstractmethod
    def prepare_global_plan(self, plans: List[SavePlan]) -> List[SavePlan]:

Differential Revision: D56480396

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @LucasLLC

### CODE REVIEW

**Review by fegin — APPROVED** [review]
You will need to clear the CLA to land the PR.

**Comment by kirtiteja** [comment]
@fegin  is it okay if i suppress the backward compatibility linter? It is firing up because i renamed the param. The build seems to be fine and i dont expect a lot of users to be impacted by this as this in the default storage writer impl.

**Comment by fegin** [comment]
That should be fine as it matches the Storage ABC.

**Comment by wz337** [comment]
Added the tag for suppressing the linter

**Pull request closed without merging**
