### PR TITLE
Enable Constant Folding Tests

### PR DESCRIPTION
**Pull request by KsenijaS**
Enable tests for constant folding since constant folding is enabled for opset 12

### CODE REVIEW

**Comment by KsenijaS** [comment]
please review @neginraoof

**Comment by KsenijaS** [comment]
@houseroad Failure on CI is not introduced by this PR. Please review

**Review by neginraoof — APPROVED** [review]
LGTM. Thanks!

**Comment by KsenijaS** [comment]
@houseroad for review. Thanks!

**Pull request closed without merging**
