### PR TITLE
[pipelining] expose APIs per pytorch rule

### PR DESCRIPTION
**Pull request by kwen2501**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #126735
* #126721
* __->__ #126812

Rule is enforced by #126103.

The rule:
- If `torch.a.b` defines a public class `C` (i.e. to be exposed in torch API namespace), then `torch.a.b` must be a public path, i.e. no `_`.
- `torch.a.b` should ideally have an `__all__` that defines what should be imported from this file when it is imported.
- All other definitions in `torch.a.b` that you don't want to expose should have a `_` prefix.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

### CODE REVIEW

**Review by wconstab — APPROVED** [review]
lgtm

i was able to land and bypass BC check (after verifying all otehr ciflow/trunk jobs passed) by using `-f "intentional BC change for not yet released api"` in my pytorchbot command

**Comment by kwen2501** [comment]
@wconstab thanks for checking it. 
Yeah, the BC break was due to renaming `PipelineSchedule` to `_PipelineSchedule`. 
I added `suppress-bc-linter` label to suppress it.

**Pull request closed without merging**
