### PR TITLE
OpenCV 4.0 Compatibility fix

### PR DESCRIPTION
**Pull request by achalshah20**
caffe2 compiles with latest opencv 4.0 after committed changes.

### CODE REVIEW

**Comment by achalshah20** [comment]
@li-roy Why it is not merged yet?

**Comment by ezyang** [comment]
Do these changes break compatibility with OpenCV 3.x?

**Comment by achalshah20** [comment]
@ezyang Yes. It should have!

**Comment by achalshah20** [comment]
@ezyang Failed issue caused by system failure. Not related. can you please merge this PR?

**Pull request closed without merging**
