### PR TITLE
Allow SequentialLR to include ChainedScheduler

### LINKED ISSUE #132745: Allow SequentialLR scheduler to be able to use ChainedSchedulers
### 🚀 The feature, motivation and pitch

Currently, the `SequentialLR` scheduler doesn't work if one of the schedulers that you pass it is a `ChainedScheduler`. This is because the `ChainedScheduler` does not have a `last_epoch` attribute, so when the `SequentialLR` initialisation tries to ""Undo" the step performed by other schedulers": 

```python
        # "Undo" the step performed by other schedulers
        for scheduler in self._schedulers:
            scheduler.last_epoch -= 1
```

it fails when it gets to a `ChainedScheduler`.

It would be good if the `SequentialLR` could actually take in `ChainedScheduler`s.

### Alternatives

Currently, I have created my own version of the `SequentialLR` that allows `ChainedSchedulers`. This requires a fairly minimal change to the `SequentialLR` class. In the `SequentialLR`'s `__init__`, I change the lines:

```python
        # "Undo" the step performed by other schedulers
        for scheduler in self._schedulers:
            scheduler.last_epoch -= 1
```

to be:

```python
        # "Undo" the step performed by other schedulers
        self.recursive_undo()
```

and add the a `recursive_undo` method to the class, which checks if the scheduler itself contains a list of `_schedulers` or otherwise a `last_epoch` attribute, and resets the `last_epoch` when encountered:

```python
    def recursive_undo(self, sched=None):
        # recursively undo any step performed by the initialisation of
        # schedulers
        scheds = self if sched is None else sched

        if hasattr(scheds, "_schedulers"):
            for s in scheds._schedulers:
                self.recursive_undo(s)
        elif hasattr(scheds, "last_epoch"):
            scheds.last_epoch -= 1
```

I can add a PR with this request if it is useful.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattpitkin**
This fixes #132745 and allows a `SequentialLR` to include schedulers that are compound scheduler types (i.e., a `ChainedScheduler`), which contain a list of schedulers in a `_schedulers` attribute.

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
Thanks for tackling this! Could you add a test case in test/optim/test_lrscheduler.py?

**Comment by mattpitkin** [comment]
@janeyx99 Sure, will do.

**Comment by mattpitkin** [comment]
I've added a test case, so hopefully it passes the CI.

**Comment by janeyx99** [comment]
Ahhh I kicked off the CI on this and forgot to check back in. Could you fix the lint and rebase onto latest main? We can land the PR once CI is green.

**Review by janeyx99 — APPROVED** [review]

**Comment by mattpitkin** [comment]
I've hopefully fixed the linting issue.

**Comment by janeyx99** [comment]
You can install lintrunner locally and verify it all passes:

pip install lintrunner
lintrunner init
lintrunner -a

**Pull request closed without merging**
