### PR TITLE
disabling reshape

### LINKED ISSUE #75282: nvfuser fails on benchmark
### 🐛 Describe the bug

Issue found on David's benchmark runs. Opening this bug so we can properly trace it in the project board

>Microbenchmarks - currently a draft PR here: https://github.com/pytorch/benchmark/pull/801
Currently a few of them are failing fallbacks: autogen-0, autogen-4. You can run the isolated cases with
$ python run_microbenchmarks.py nvfuser --filter autogen-0
autogen-4 is actually failing its fallback as well - e.g. if you enable fallbacks, it still fails 

### Versions

Breaks on upstream/master. Don't have access to machine config. I'll try to repro and update it here.

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #75282 

Temporarily disables reshape to avoid codegen failure.

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]
Looks good! Thanks for investigating this issue

**Comment by davidberard98** [comment]
@jjsjann123 is this ready to merge?

**Comment by jjsjann123** [comment]
Yep. I'm just waiting for the CI to finish before pinging the pytorchbot.

**Pull request closed without merging**
