### PR TITLE
dynamo test: remove the cuda hardcoding and detect device dynamically

### LINKED ISSUE #125760: dynamo test (test_model_output.py) failing on cpu devices because of cuda hardcoding for the device
### 🐛 Describe the bug

CI test `dynamo\test_model_output.py` is failing on aarch64 platform because the device is hardcoded to cuda in one of the subtests.

Reproducer: 
` python test/dynamo/test_model_output.py -k test_HF_bert_model_output`

Error log:
```
___________________________________________________________ TestModelOutput.test_HF_bert_model_output ___________________________________________________________
Traceback (most recent call last):
 File "/home/ubuntu/pytorch/test/dynamo/test_model_output.py", line 232, in test_HF_bert_model_output
  sequence_output = torch.rand(1, 12, 768).to("cuda")
 File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
  raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
To execute this test, run the following from the base repo dir:
   python test/dynamo/test_model_output.py -k test_HF_bert_model_output
```

### Versions

platform: aarch64 linux (without cuda )
OS: Ubuntu 22.04
torch mainline

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

### PR DESCRIPTION
**Pull request by snadampal**
This fixes https://github.com/pytorch/pytorch/issues/125760

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Comment by colesbury** [comment]
@bdhirsh - would you please review this PR?

**Comment by snadampal** [comment]
the one CI test failure doesn't seem to be related to this PR.

**Review by bdhirsh — APPROVED** [review]

**Comment by snadampal** [comment]
The new failure in CI tests doesn't seem to be related to this PR.
the following is the failing test which is different from the one fixed here.

`python test/test_foreach.py -k TestForeachCUDA.test_binary_op_tensors_on_different_devices__foreach_div_cuda_bool `

**Comment by snadampal** [comment]
The CI failure doesn't seem to be related to this PR.

**Comment by snadampal** [comment]
this is already approved, just waiting on CI failures which are unrelated. can it be merged please?

**Pull request closed without merging**
