### PR TITLE
Add __torch_function__ support for generated tensor methods/property of PrivateUse1

### PR DESCRIPTION
**Pull request by cdzhan**
support following case:
```python
import torch
...
class CustomFooTensor(torch.Tensor):
  @classmethod
  def __torch_function__(cls, func, types, args=(), kwargs=None):
    ...
a = CustomFooTensor([3])
print(a.is_foo)
```

### CODE REVIEW

**Review by albanD — CHANGES_REQUESTED** [review]
I don't think we should add this attribute because:
- It moves us away from device generic code
- it doesn't make sense once the privateuse1 module is renamed.

**Comment by cdzhan** [comment]
> I don't think we should add this attribute because:
> 
> * It moves us away from device generic code
> * it doesn't make sense once the privateuse1 module is renamed.

Thanks for your comment! Please let me know If there is anything else that needs to be modified.

**Comment by albanD** [comment]
Sorry, but I don't think we want this at all. You can use `t.device.type == some_device_type` to get the same thing in a more generic way. So I'm not sure we really want to add more of these one-off attributes.

**Comment by cdzhan** [comment]
I thought about this question again, but a related more general question came to mind #123245  @albanD

**Review by albanD — APPROVED** [review]
Ok, I still think we want to remove a lot of these device-specific method/attributes.
But I agree that adding torch_function support to these existing one is an ok thing to do.

**Pull request closed without merging**
