### PR TITLE
FIX the document of distributed.new_group()

### PR DESCRIPTION
**Pull request by Raphael-Hao**
As for now, the document of distributed.new_group() says that it returns `None` when current ranks is not in the new created process group. However, it actually returns `GroupMember.NON_GROUP_MEMBER`. I have check the code and think it is more appropriate that we fix the document.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @rohan-varma

### CODE REVIEW

**Comment by awgu** [comment]
This seems reasonable to me. cc: @kwen2501 @wconstab if you guys wanted to take a glance. Otherwise, I think this is okay to land.

**Comment by wconstab** [comment]
yea, i think i prefer this approach.  I initially commented on this PR https://github.com/pytorch/pytorch/pull/122574 and at that time I was not sure which approach is better but wanted to see if anyone had an argument for one or the other.  I guess the two arguments in favor of this PR are that returning 'NON-MEMBER' is more explicit/useful, and changing the docs make less impact to existing users.

**Review by wconstab — APPROVED** [review]

**Comment by Raphael-Hao** [comment]
I have checked the usage of `GroupMember.NON_GROUP_MEMBER`. `GroupMember.NON_GROUP_MEMBER` is only used inside the file: distributed_c10d.py. In the related functions, `GroupMember.NON_GROUP_MEMBER` is used to indicate the current rank not in the process group. `None` is never used for this purpose. So I think change the document is a better choice.

**Review by kwen2501 — APPROVED** [review]
LGTM.
As a follow-up, do we need to expose `NON_GROUP_MEMBER` as a root level API?

**Comment by wconstab** [comment]
yea, that would be good.  Do you mind adding that @Raphael-Hao?

**Pull request closed without merging**
