### PR TITLE
Enable UFMT on `test/scripts` and some files

### PR DESCRIPTION
**Pull request by shink**
Part of: #123062

Ran lintrunner on:

- `test/scripts`
- `test/simulate_nccl_errors.py`
- `test/test_ao_sparsity.py`
- `test/test_autocast.py`
- `test/test_binary_ufuncs.py`
- `test/test_bundled_images.py`
- `test/test_bundled_inputs.py`
- `test/test_comparison_utils.py`
- `test/test_compile_benchmark_util.py`
- `test/test_complex.py`
- `test/test_cpp_api_parity.py`
- `test/test_cpp_extensions_aot.py`
- `test/test_cpp_extensions_jit.py`
- `test/test_cpp_extensions_open_device_registration.py`

Detail:

```bash
$ lintrunner -a --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5 @albanD

### CODE REVIEW

**Review by soulitzer — APPROVED** [review]

**Comment by soulitzer** [comment]
@shink  looks like there are some lint failures https://github.com/pytorch/pytorch/actions/runs/8699304315/job/23948612209?pr=124137

**Comment by shink** [comment]
@soulitzer fixed in https://github.com/pytorch/pytorch/pull/124137/commits/4421692f9e1e28a2e36d250877df241baa1b1653, please take a look

**Pull request closed without merging**
