### PR TITLE
A tiny fix in MT19937RNGEngine

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
Hi! Can you please provide more detailed description of what is happening here. Or/better add test.

**Comment by cyyever** [comment]
> 
> 
> Hi! Can you please provide more detailed description of what is happening here. Or/better add test.



> 
> 
> Hi! Can you please provide more detailed description of what is happening here. Or/better add test.

data_.state_[j] is a 32-bit integer, and 0xffffffff is a 32 bit mask of all ones. The operation of &= will always equal to itself.

**Comment by ezyang** [comment]
I agree with the reasoning and verified the patch correctness with this Crucible program

```
#include <stdint.h>
#include <crucible.h>

// #define MERSENNE_STATE_N 624
#define MERSENNE_STATE_N 8

typedef struct {
  uint64_t seed_;
  int left_;
  bool seeded_;
  uint32_t next_;
  uint32_t state_[MERSENNE_STATE_N];
} mt19937_data_pod;

void init_with_uint32(mt19937_data_pod* data_, uint64_t seed) {
  data_->seed_ = seed;
  data_->seeded_ = true;
  data_->state_[0] = seed & 0xffffffff;
  for(int j = 1; j < MERSENNE_STATE_N; j++) {
    data_->state_[j] = (1812433253 * (data_->state_[j-1] ^ (data_->state_[j-1] >> 30)) + j);
    data_->state_[j] &= 0xffffffff;
  }
  data_->left_ = 1;
  data_->next_ = 0;
}

void init_with_uint32_v2(mt19937_data_pod* data_, uint64_t seed) {
  data_->seed_ = seed;
  data_->seeded_ = true;
  data_->state_[0] = seed & 0xffffffff;
  for(int j = 1; j < MERSENNE_STATE_N; j++) {
    data_->state_[j] = (1812433253 * (data_->state_[j-1] ^ (data_->state_[j-1] >> 30)) + j);
  }
  data_->left_ = 1;
  data_->next_ = 0;
}

int main() {
  mt19937_data_pod data1;
  mt19937_data_pod data2;

  uint64_t seed = crucible_uint64_t("seed");
  init_with_uint32(&data1, seed);
  init_with_uint32_v2(&data2, seed);
  for (int j = 0; j < MERSENNE_STATE_N; j++) {
    check(data1.state_[j] == data2.state_[j]);
  }
}
```

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
btw according to crucible the mask on [0] isn't necessary either

**Pull request closed without merging**
