### PR TITLE
[FSDP][state_dict] Add a summary log when finishing state_dict

### PR DESCRIPTION
**Pull request by fegin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #103784
* #103783
* #103782
* #103781
* #103609

Add a summary log when finishing state_dict

Differential Revision: [D46807103](https://our.internmc.facebook.com/intern/diff/D46807103/)

### CODE REVIEW

**Review by fduwjj — APPROVED** [review]
LGTM

**Comment by fegin** [comment]
The failing test is not related
```
HEAD is now at 45c9b82 Auto-detect C++ ABI version (#321)
+ python multipy/runtime/example/generate_examples.py
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/package/package_exporter.py:925: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage_type_str = obj.pickle_storage_type()
+ pip install -e . --install-option=--cudatests

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...
  ```

**Review by fduwjj — APPROVED** [review]
Nice!

**Pull request closed without merging**
