### PR TITLE
Update HF pin

### PR DESCRIPTION
**Pull request by angelayi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #119718
* __->__ #119717

Sometime between now and the previous pin update, HF introduced a
ModelOutputs type, which was not pytree serializable, causing
aot_compile to fail on new HF models
(https://fb.workplace.com/groups/1075192433118967/permalink/1377977852840422/).
With https://github.com/huggingface/transformers/pull/27871, we
can now pytree serialize HF ModelOutputs types.

### CODE REVIEW

**Comment by angelayi** [comment]
This pin should also fix https://github.com/pytorch/pytorch/issues/117280, but I think we need to first wait for a new transformers release, bump the transformers version in TorchBench, and then bump the TorchBench version in the Inductor benchmark.

**Review by desertfire — APPROVED** [review]
Thanks!

**Pull request closed without merging**
