### PR TITLE
Fix undefined '__func__' for CUDA 8 on Windows

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by ezyang** [comment]
@peterjc123 In your opinion, should we do CUDA 8 builds for Windows as well?

**Comment by peterjc123** [comment]
The major problems of CUDA 8 are during compilation. It doesn't support C++11 so some issues may sometimes emerge. If we could add build machines, then we can build for CUDA 8 too. If not, then I don't think adding it is possible, because it's already slow enough. However, we could add a switch in CI/pytorchbot to build/test for CUDA 8 on demand without changing the files in the repo.

**Comment by soumith** [comment]
we could also simply drop CUDA8 support on Windows

**Comment by peterjc123** [comment]
@soumith Yes, since the binary files are builtin. We actually only require any version of CUDA installed.

**Pull request merged**
