### PR TITLE
[3/N] Non-Tensor: Support string parameter for aten operations

### PR DESCRIPTION
**Pull request by EikanWang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125831

cc @voznesenskym @penguinwu @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Review by jgong5 — APPROVED** [review]

**Comment by vadimkantorov** [comment]
Not related to aten, but related to string support in general. There is a big usecase of string-valued arrays (could be tensor-backed) - especially for data-loading https://github.com/pytorch/pytorch/issues/13246

- https://github.com/pytorch/pytorch/issues/101699

Another usecase is representing vocabs of tokenizers

**Comment by fbgheith** [comment]
@pytorchbot revert -m "test failures when run by meta" -c ghfirst

part of ghstack staring with 125308 which needs to be reverted because of test failures when run by meta

**Pull request closed without merging**
