### PR TITLE
[Static Runtime] Enable ListConstructUnpack pass

### PR DESCRIPTION
**Pull request by mikeiovine**
Summary:
* Moved the pass to `torch/csrc/jit/passes` so it can be accessed by static runtime
* Added more robust tests + changed minor stylistic details in the pass implementation

Differential Revision: D30107568

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
how are listconstruct unpack and tuple construct unpack different from https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/peephole_list_idioms.cpp#L156 and https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/lower_tuples.cpp ? Can we reuse and contribute to existing passes ?

**Comment by mikeiovine** [comment]
I didn't know those passes existed, thanks for pointing that out. I think `lower_tuples` does everything that `eliminate_tuple_construct_unpack` does, so there's no reason not to use it.

As for the list unpack one, I think we can also use it. But we want to eliminate the dependency on `AliasDb` if possible (static runtime is spending too much time creating `AliasDb`s during startup). I'll look into doing that today.

**Comment by eellison** [comment]
What is the cause of alias db instantiations ? Typically in the past compilation problems have been because of multiple instantiations of alias db within one pass.

**Comment by mikeiovine** [comment]
I don't think we have any passes that instantiate alias db multiple times, but we do have many passes that instantiate alias db's when it might not be strictly necessary (it might be possible to use an alias db from a previous pass). It also might be possible to resolve this issue by deleting passes from static runtime's startup phase. I'm still in the early stages of investigating this, so I'm not sure if it's possible. 

This is something I'll follow up on later though. For now, I'll enable peephole list optimizations [here](https://github.com/pytorch/pytorch/pull/62429) and close this one.

**Pull request closed without merging**
