### PR TITLE
Allow large inputs to svd_lowrank. Fix inaccuracy in torch.svd docs.

### LINKED ISSUE #42062: torch.svd_lowrank(A) seems to have quadratic space complexity
## 🐛 Bug

I am trying to invoke a `torch.svd_lowrank(A)` on a *sparse* 659,574x659,574 matrix (with 6,416,728 non-zero elements). However, it seems like internally a dense matrix of the same shape is materialized:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-09172ebe9a68> in <module>
----> 1 torch.svd_lowrank(A)

~/anaconda3/envs/pytorch1p5/lib/python3.7/site-packages/torch/_lowrank.py in svd_lowrank(A, q, niter, M)
    125         if (not set(map(type, tensor_ops)).issubset((torch.Tensor, type(None))) and has_torch_function(tensor_ops)):
    126             return handle_torch_function(svd_lowrank, tensor_ops, A, q=q, niter=niter, M=M)
--> 127     return _svd_lowrank(A, q=q, niter=niter, M=M)
    128 
    129 

~/anaconda3/envs/pytorch1p5/lib/python3.7/site-packages/torch/_lowrank.py in _svd_lowrank(A, q, niter, M)
    159         else:
    160             B = matmul(A_t, Q_c) - matmul(M_t, Q_c)
--> 161         U, S, V = torch.svd(_utils.transpose(B))
    162         U = Q.matmul(U)
    163 

RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 1740151445904 bytes. Error code 12 (Cannot allocate memory)
```

I come to this conclusion because `1740151445904 / 659574^2 = 4`. So I assume the materialized matrix has an element size of 4 bytes.

## To Reproduce

1. Load big sparse matrix (I cannot share my dataset, but it is possible to reproduce the same behavior via the Reddit dataset via PyTorch geometric)
1. Execute `torch.svd_lowrank(A)`

For example, executing
```
import torch
from torch_geometric.datasets import Reddit

reddit = Reddit(root='data')[0]
n = len(reddit.y)
m = len(reddit.edge_index[0])
A = torch.sparse.FloatTensor(
    torch.cat((reddit.edge_index, n+reddit.edge_index, 2*n+reddit.edge_index), dim=-1),
    torch.ones(3*m).float()
)
torch.svd_lowrank(A)
```
raises the following error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-09172ebe9a68> in <module>
----> 1 torch.svd_lowrank(A)

~/anaconda3/envs/pytorch1p5/lib/python3.7/site-packages/torch/_lowrank.py in svd_lowrank(A, q, niter, M)
    125         if (not set(map(type, tensor_ops)).issubset((torch.Tensor, type(None))) and has_torch_function(tensor_ops)):
    126             return handle_torch_function(svd_lowrank, tensor_ops, A, q=q, niter=niter, M=M)
--> 127     return _svd_lowrank(A, q=q, niter=niter, M=M)
    128 
    129 

~/anaconda3/envs/pytorch1p5/lib/python3.7/site-packages/torch/_lowrank.py in _svd_lowrank(A, q, niter, M)
    159         else:
    160             B = matmul(A_t, Q_c) - matmul(M_t, Q_c)
--> 161         U, S, V = torch.svd(_utils.transpose(B))
    162         U = Q.matmul(U)
    163 

RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 1953816884100 bytes. Error code 12 (Cannot allocate memory)
```

## Expected behavior

`torch.svd_lowrank` should not have quadratic space complexity when the input is a sparse matrix.

## Environment

Collecting environment information...
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 20.04 LTS
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla V100-PCIE-32GB
Nvidia driver version: 450.51.05
cuDNN version: /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.1
[pip3] torch-cluster==1.5.6
[pip3] torch-geometric==1.6.0
[pip3] torch-scatter==2.0.5
[pip3] torch-sparse==0.6.6
[pip3] torch-spline-conv==1.2.0
[pip3] torchvision==0.6.0a0+35d732a
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.1.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.18.5           py37ha1c710e_0
[conda] numpy-base                1.18.5           py37hde5b4d6_0
[conda] pytorch                   1.5.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torch-cluster             1.5.6                    pypi_0    pypi
[conda] torch-geometric           1.6.0                    pypi_0    pypi
[conda] torch-scatter             2.0.5                    pypi_0    pypi
[conda] torch-sparse              0.6.6                    pypi_0    pypi
[conda] torch-spline-conv         1.2.0                    pypi_0    pypi
[conda] torchvision               0.6.1                py37_cu102    pytorch

cc @vishwakftw @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @aocsa

### PR DESCRIPTION
**Pull request by pearu**
As in title.

Fixes #42062

### CODE REVIEW

**Comment by mruberry** [comment]
Hey @pearu! This looks good; is there a test we should add for this behavior, too?

**Comment by pearu** [comment]
> Hey @pearu! This looks good; is there a test we should add for this behavior, too?

@mruberry, I would say no because
- this issue was not about a software bug (`torch.svd_lowrank` would have been able to compute the correct result for the given dataset if one would use a machine with 2TB of RAM). This issue was rather a documentation bug (of `torch.svd`) because when developing the `svd_lowrank` algorithm, I relied on what was said in the docs that were a little inaccurate.
- to reproduce the issue, one would need to test the memory limitations of a testing machine that memory capabilities are not well defined. Also, the test would be a long-running one because the problematic `torch.svd` call is made after some time-consuming calculations.
- there are inexpensive `assert` statements that now ensure that `torch.svd` is called in a memory-efficient way.

**Comment by mruberry** [comment]
OK. So just to recap:

- there is no UX change from this behavior (no BC-breaking implications)
- this is just a performance optimization for torch.svd_lowrank and a doc fix for torch.svd

Is that right?

**Comment by pearu** [comment]
> OK. So just to recap:
> 
> * there is no UX change from this behavior (no BC-breaking implications)
> * this is just a performance optimization for torch.svd_lowrank and a doc fix for torch.svd
> 
> Is that right?

All correct.

**Review by mruberry — APPROVED** [review]
Thanks @pearu!

**Pull request closed without merging**
