### PR TITLE
q_avgpool: Loop over batch dimension inside operators

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #66820
* __->__ #66819

This has a number of different advantages:
- For channels last tensors, DispatchStub overhead is only incurred once.
- For contiguous tensors, parallelization now happens over batch and
  chanels, enabling better load balancing between threads.
- `q_scale()` and `q_zero_point()` are no longer called inside of a
  parallel region, which is not allowed (see gh-56794)

Differential Revision: [D32445352](https://our.internmc.facebook.com/intern/diff/D32445352)

### CODE REVIEW

**Comment by peterbell10** [comment]
@ngimel ping

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32445352).

**Comment by ngimel** [comment]
@peterbell10 can you please rebase, I'm getting merge conflicts internally

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32445352).

**Pull request closed without merging**
