### PR TITLE
[Caffe2][Training]Add/fallback some operators for mkl-dnn

### PR DESCRIPTION
**Pull request by PenghuiCheng**
Implementation LeakyRelu operator for mkl-dnn,the speed-up of a single operation is up to 10X on BDW.
Implementation rashape operator for mkl-dnn,it will resolve occasionally crash issue which use fallback reshape operator.
Implementation CreateBlobQueue and SafeEnqueueBlobs operators,it will resolve crash issue which use fallback operators.
Fallback CreateBlobsQueueDBOp,TensorProtosDBInput,CloseBlobsQueue operators.
Implement adam operator for mkl-dnn,the speed-up of a single operator is up to 6X on BDW.

### CODE REVIEW

**Comment by SsnL** [comment]
@yinghai Can you look at this?

**Comment by yinghai** [comment]
@wesolwsk, could you review this?

**Comment by PenghuiCheng** [comment]
@wesolwsk,can you merge these patch?If you have any problem,please let me know,thanks!

**Comment by wesolwsk** [comment]
@PenghuiCheng, I wanted to verify that this works for my training use case, but before I can do that we need to upgrade MKL-DNN in Caffe2 and patch some of the other PRs (e.g. for collective communication). Is anyone else blocked on support for these ops?

**Comment by ezyang** [comment]
@wesolwsk Any update on this PR?

**Comment by wesolwsk** [comment]
@PenghuiCheng, could you please rebase and address the following style changes: 

screen shot 2018-12-06 at 1 30 39 pm

**Comment by PenghuiCheng** [comment]
Hi,@wesolwsk ,I had updated codes.Please review it .
thanks!

**Comment by wesolwsk** [comment]
@PenghuiCheng, can you rebase again? there is a conflict

**Comment by PenghuiCheng** [comment]
@wesolwsk ，I had resolved conflict. thanks!

**Comment by wesolwsk** [comment]
This error in the CUDA build looks suspicious. CC: @yinghai

Dec 11 05:54:42 fatal: clone of 'https://github.com/01org/mkl-dnn.git' into submodule path 'mkl-dnn' failed
Dec 11 05:54:42 Failed to recurse into submodule path 'third_party/ideep'
Exited with code 128

**Comment by PenghuiCheng** [comment]
@wesolwsk ,How can I do for this?

**Comment by PenghuiCheng** [comment]
@yinghai ,@wesolwsk,for this commit ,what may I do next step?

**Comment by PenghuiCheng** [comment]
@yinghai ,@wesolwsk,I rebase the code again.

**Comment by PenghuiCheng** [comment]
@wesolwsk ,I had rebased code.
Please review it.
thanks!

**Pull request closed without merging**
