### PR TITLE
[reland][ROCm] TunableOp for gemm_and_bias

### PR DESCRIPTION
**Pull request by jeffdaily**
Reland of #128143 but added `alpha` and `bias` initialization to `launchTunableGemmAndBias`

Thus far TunableOp was implemented for gemm, bgemm, and scaled_mm. gemm_and_bias was notably missing. This PR closes that gap.

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@xw285cornell Can you please review and approve if this PR looks good?

**Comment by diwdoit** [comment]
Hi @xw285cornell - appreciate your help to get the PR reviewed.

**Comment by jithunnair-amd** [comment]
@malfet I think @xw285cornell is OOO. Can you please approve and merge this PR?

**Comment by jithunnair-amd** [comment]
@malfet re-ping

**Comment by jithunnair-amd** [comment]
@jeffdaily/@naromero77amd: I see a unit test was added for this PR: `test_addmm_relu_tunableop_rocm` in `test_linalg.py`. I have added the `keep-going` label to this PR to ensure if runs all unit tests, since we have some unrelated failures on ROCm CI that might prevent that unit test from running in CI. Can you please post a snippet showing that the unit tests related to this PR ran successfully in the PR's CI runs?

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
