### PR TITLE
CMake: Improve check and report of Magma

### PR DESCRIPTION
**Pull request by Flamefire**
- Only search for magma if it is used (GPU builds)
- Don't report it was not found when it isn't searched for
- Don't report if magma is disabled (currently: "MAGMA not found. Compiling without MAGMA support" is reported)

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Looks good do me, but I wonder if it'll be better to make USE_MAGMA and `cmake_dependent_option` in https://github.com/pytorch/pytorch/blob/bad5e1e0bb17452f26cf0527704a95892509e3ca/CMakeLists.txt#L227

**Comment by Flamefire** [comment]
Makes sense yes, but that would be a possible behavior change I didn't want to introduce here. And with this change the change to dependent option is easy and much more obvious: Basically delete the `if(USE_CUDA OR USE_ROCM)` and the `else` branch from this part of the code.

**Review by thiagocrepaldi — COMMENTED** [review]
@malfet Not sure why it had the `release notes: onnx` label in it, but LGTM

**Pull request closed without merging**
