### PR TITLE
fix inductor linspace when steps=1

### LINKED ISSUE #91506: PyTorch 2.0 compiled torch.linspace crashes when given steps=1
### 🐛 Describe the bug

torch.compile fails when `torch.linspace` is given the arg `step=1`. When omitting the `torch.compile` step the code behaves correctly.

Below is an example of code that will fail.

```python
import torch

class Model(torch.nn.Module):
    def forward(self):
        tensor = torch.linspace(0, 1, 1)

        return tensor

compiled_model = torch.compile(Model())
a = compiled_model()
```

Below is the full traceback.
```
/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py:372: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled.Consider setting `torch.set_float32_matmul_precision('high')`
  warnings.warn(
Traceback (most recent call last):
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/graph.py", line 296, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/lowering.py", line 222, in wrapped
    return decomp_fn(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/lowering.py", line 1346, in linspace
    step_size = (end - start) / (steps - 1)
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 676, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 1032, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/__init__.py", line 1151, in __call__
    return self.compile_fn(model_, inputs_)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 398, in compile_fx
    return aot_autograd(
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/optimizations/training.py", line 78, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2353, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 88, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2050, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_tensor_args, aot_config)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 1305, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 955, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 88, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 373, in fw_compiler
    return inner_compile(
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 588, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/debug.py", line 223, in inner
    return fn(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 139, in compile_fx_inner
    graph.run(*example_inputs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 88, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/graph.py", line 170, in run
    return super().run(*args)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/fx/interpreter.py", line 136, in run
    self.env[node] = self.run_node(node)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/graph.py", line 369, in run_node
    result = super().run_node(n)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/fx/interpreter.py", line 177, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_inductor/graph.py", line 299, in call_function
    raise LoweringException(e, target, args, kwargs) from e
torch._inductor.exc.LoweringException: ZeroDivisionError: division by zero
  target: aten.linspace.default
  args[0]: 0
  args[1]: 1
  args[2]: 1
  kwargs: {'device': device(type='cpu'), 'pin_memory': False}

While executing %linspace : [#users=1] = call_function[target=torch.ops.aten.linspace.default](args = (0, 1, 1), kwargs = {device: cpu, pin_memory: False})
Original traceback:
Module stack: {}
  File "linspace_problem.py", line 6, in forward
    tensor = torch.linspace(0, 1, 1)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "linspace_problem.py", line 18, in <module>
    a = compiled_model()
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 83, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 212, in _fn
    return fn(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 333, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 88, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1684, in run
    super().run()
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1750, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 529, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 600, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/matt/anaconda3/envs/torch2/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 681, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised LoweringException: ZeroDivisionError: division by zero
  target: aten.linspace.default
  args[0]: 0
  args[1]: 1
  args[2]: 1
  kwargs: {'device': device(type='cpu'), 'pin_memory': False}

While executing %linspace : [#users=1] = call_function[target=torch.ops.aten.linspace.default](args = (0, 1, 1), kwargs = {device: cpu, pin_memory: False})
Original traceback:
Module stack: {}
  File "linspace_problem.py", line 6, in forward
    tensor = torch.linspace(0, 1, 1)


Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Versions

```
PyTorch version: 2.0.0.dev20221225+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.5.0-1ubuntu1~22.04) 9.5.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 515.86.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.0
[pip3] phd-torch==1.0.0
[pip3] phd-torchscripts==1.0.0
[pip3] pytorch-lightning==1.7.7
[pip3] pytorch-memlab==0.2.4
[pip3] se3-transformer-pytorch==0.8.13
[pip3] torch==2.0.0.dev20221225+cu117
[pip3] torchaudio==2.0.0.dev20221222+cu117
[pip3] torchConvNd==0.2.0
[pip3] torchinfo==1.7.0
[pip3] torchmetrics==0.7.2
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221222+cu117
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.19.2                   pypi_0    pypi
[conda] phd-torch                 1.0.0                     dev_0    <develop>
[conda] phd-torchscripts          1.0.0                     dev_0    <develop>
[conda] pytorch-cuda              11.7                 h67b0de4_1    pytorch
[conda] pytorch-lightning         1.7.7                    pypi_0    pypi
[conda] pytorch-memlab            0.2.4                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] se3-transformer-pytorch   0.8.13                   pypi_0    pypi
[conda] torch                     2.0.0.dev20221225+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20221222+cu117          pypi_0    pypi
[conda] torchconvnd               0.2.0                    pypi_0    pypi
[conda] torchinfo                 1.7.0                    pypi_0    pypi
[conda] torchmetrics              0.7.2                    pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221222+cu117          pypi_0    pypi
```

cc @ezyang @mruberry @ngimel @Lezcano @peterbell10 @soumith @msaroufim @wconstab @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### PR DESCRIPTION
**Pull request by jancervenka**
Fixes #91506

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
This is a reasonable targeted fix.

It'd be interesting as a follow up to compare the generated FX graph and the generated triton code when using the PrimTorch implementation vs when using the direct lowering. I'd expect the FX graph to be more complex, but perhaps the generated code is comparable modulo a couple `where`s.

If you want to pick up this issue, here are some pointers:

The PrimTorch implementation of `linalg` is here:
https://github.com/pytorch/pytorch/blob/2b52db9c953d063db7b46c12f4df35b47aca4381/torch/_refs/__init__.py#L4283
You'd need to register that decomposition within  `decompositions.py` and remove this lowering and compare the generated triton code by executing a short program that compiles `linspace` with the flag `TORCH_COMPILE_DEBUG=1`.

**Comment by lezcano** [comment]
the lint error needs fixing though

**Comment by jancervenka** [comment]
@lezcano thank you! Will look into the PrimTorch comparison.

**Comment by jancervenka** [comment]
@lezcano 

I compared the implementations using the following program:
```python
import torch

class Model(torch.nn.Module):
    def forward(self):
        tensor = torch.linspace(0, 2, 1)

        return tensor

compiled_model = torch.compile(Model())
print(compiled_model())
```

Which generates this FX graph and code:
```python
class <lambda>(torch.nn.Module):
    def forward(self):
        # File: /root/pytorch/../test2.py:5, code: tensor = torch.linspace(0, 2, 1)
        linspace: f32[1] = torch.ops.aten.linspace.default(0, 2, 1, device = device(type='cpu'), pin_memory = False)
        return (linspace,)
```

```python
from ctypes import c_void_p, c_long
import torch
import random
from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()


kernel_cpp_0 = async_compile.cpp('''
#include "/tmp/torchinductor_root/77/c7773nj5pwikpmm2pwa62rcudlf7p3if7eyqb5k4sjsvewwje4le.h"
extern "C" void kernel(float* __restrict__ out_ptr0)
{
    {
        {
            auto tmp0 = static_cast<float>(0.0);
            auto tmp1 = static_cast<float>(0);
            auto tmp2 = tmp0 * tmp1;
            auto tmp3 = tmp2 + tmp1;
            out_ptr0[0] = tmp3;
        }
    }
}
''')


async_compile.wait(globals())
del async_compile

def call(args):
    buf0 = empty_strided((1, ), (1, ), device='cpu', dtype=torch.float32)
    kernel_cpp_0(c_void_p(buf0.data_ptr()))
    return (buf0, )


if __name__ == "__main__":
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    print_performance(lambda: call([]))
```

And this is the output when I remove the lowering and register the PrimTorch decomposition:
Screenshot 2023-01-02 at 15 29 39

```python
class <lambda>(torch.nn.Module):
    def forward(self):
        # File: /root/pytorch/../test2.py:5, code: tensor = torch.linspace(0, 2, 1)
        full: f32[1] = torch.ops.aten.full.default([1], 0, dtype = torch.float32, layout = torch.strided, device = device(type='cpu'), pin_memory = False)
        return (full,)
```

```python
from ctypes import c_void_p, c_long
import torch
import random
from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()


kernel_cpp_0 = async_compile.cpp('''
#include "/tmp/torchinductor_root/77/c7773nj5pwikpmm2pwa62rcudlf7p3if7eyqb5k4sjsvewwje4le.h"
extern "C" void kernel(float* __restrict__ out_ptr0)
{
    {
        {
            auto tmp0 = static_cast<float>(0);
            out_ptr0[0] = tmp0;
        }
    }
}
''')


async_compile.wait(globals())
del async_compile

def call(args):
    buf0 = empty_strided((1, ), (1, ), device='cpu', dtype=torch.float32)
    kernel_cpp_0(c_void_p(buf0.data_ptr()))
    return (buf0, )


if __name__ == "__main__":
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    print_performance(lambda: call([]))
```

The only difference is between the lines

```python
        linspace: f32[1] = torch.ops.aten.linspace.default(0, 2, 1, device = device(type='cpu'), pin_memory = False)	
        return (linspace,)
```

and

```
        full: f32[1] = torch.ops.aten.full.default([1], 0, dtype = torch.float32, layout = torch.strided, device = device(type='cpu'), pin_memory = False)
        return (full,)
```

I am not completely sure that I understood it correctly.

**Comment by lezcano** [comment]
Yeah, you're in the right track. Just a couple things.
- Pass a cuda tensor for it to compile triton code, which is our target for CUDA kernels
- The test should be done with some real values (say `torch.linspace(3, 10, steps=5)`) as PrimTorch's implementation shortcuts on `step=1`.

otherwise the diffs look on point, and those are exactly the outputs that we should be looking at :)

**Comment by ngimel** [comment]
refs decompose to `lerp` that is currently not supported by inductor (we should add support for it), in addition, it needlessly converts inputs to tensors (that part may be remedied by inductor, but also maybe not) and uses high precision for `arange`, whereas lowering simply uses indexing expression to generate indices, which will be much more efficient. Let's fix the lowering as proposed and this PR and not touch references for now.

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
That said, eager implementation of linspace (and lerp) takes pains to make sure that end value is exactly recovered, and we should make sure that lowering does that, but that's a separate issue. `arange` approach taken in `linspace` reference doesn't do that, and skirts around the problem by insisting that `arange` is in high precision.

**Comment by lezcano** [comment]
I agree that it may be the case that it's likely that the produced triton code is worse, but I would like to see by how much. Now, the reference implementation of `linspace` *does* make sure that the end value is exactly recovered. I left a comment with the (rather simple) proof of that fact in the implementation.

I used `float64` in the implementation via `arange` for extra precision, given that this function is, at the end of the day, an associative scan.

**Comment by ngimel** [comment]
`arange` doesn't guarantee that the end will be 1 exactly without extra precision:
```
In [16]: step=1/12345678

In [17]: torch.arange(0, 1+step/2, step, device="cuda", dtype=torch.float)[-1]-1
Out[17]: tensor(-5.9605e-08, device='cuda:0')
```
Jax's approach is slightly better for recovering endpoints (`torch.arange(12345679, dtype=torch.float)/12345678`) but all `arange` approaches suffer from asymmetry around the edges.

**Comment by lezcano** [comment]
what a pain

**Comment by lezcano** [comment]
that being said, according to that, the current approach for the decomposition of `linspace` looks on point to me. The only thing that I'd potentially change is not using `lerp` if the values `a, b`  are not too large.

**Pull request closed without merging**
