### PR TITLE
Uncomment step no-op test in test_optim

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #70953
* #70484
* #70483
* #70482
* #70481
* #70295

Differential Revision: [D33767861](https://our.internmc.facebook.com/intern/diff/D33767861)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks for fixing this test!

**Comment by mikaylagawarecki** [comment]
@mikaylagawarecki has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33767861).

**Comment by mikaylagawarecki** [comment]
@mikaylagawarecki has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33767861).

**Comment by mikaylagawarecki** [comment]
@mikaylagawarecki has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33767861).

**Pull request closed without merging**
