### PR TITLE
[EZ] Update minversion to 3.9.0

### LINKED ISSUE #138979: Missing Torch 2.5 wheels for Python 3.8
### 🐛 Describe the bug

I dont see any cp38 wheels on https://pypi.org/simple/torch but there doesn't seem to by any mentions of dropping Python 3.8 support from Torch 2.5.

The setup.py still mentions min version as 3.8 though.

### Versions

N/A

### PR DESCRIPTION
**Pull request by malfet**
Fixes https://github.com/pytorch/pytorch/issues/138979

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Review by seemethere — APPROVED** [review]
<details>
<summary> Don't mind me just submitting my daily stamp </summary>

stamp

</details>

**Review by Skylion007 — APPROVED** [review]
Do we not need to update anything in pyproject.toml?

**Comment by malfet** [comment]
> Do we not need to update anything in pyproject.toml?

Let me do it in followup PR, unless you've already created one (as pyproject is about linters at this point)

**Pull request closed without merging**
