### PR TITLE
Use CUDA image for lintrunner

### PR DESCRIPTION
**Pull request by cyyever**
We switch to pytorch-linux-jammy-cuda11.8-cudnn8-py3.9-linter for lintrunner for checking CUDA cpp source. Meanwhile, there is a Dockerfile change due to missing libiomp installation and some other clang-tidy fixes triggered by the switch. 

cc @malfet

### CODE REVIEW

**Comment by cyyever** [comment]
There is a Dockerfile change due to missing libiomp

**Review by malfet — APPROVED** [review]
LGTM, but please use standard template for the range checks

**Pull request closed without merging**
