### PR TITLE
[inductor] Pass `device_type` argument to `do_bench`

### PR DESCRIPTION
**Pull request by galexite**
Update the triton commit pin to point to https://github.com/triton-lang/triton/commit/566b63cf264ef22a54bce1baed00900d159a6618, which removes the hard-coding of device type in Triton's `do_bench` and replaces it with calls to the `DeviceInterface` for the given `device_type`.

This allows the re-use of `do_bench` for non-GPU Triton devices as long as they provide a `DeviceInterface` implementation.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by nmacchioni** [comment]
@galexite This won't be landable since we follow a stricter process for Triton pin updates; luckily I think we do have one currently in progress, @bertmaher any idea if the new pin includes the changes in this diff?

**Comment by galexite** [comment]
@nmacchioni Ah okay, thanks. Sorry I'm out of the loop on this, is this policy written up somewhere I can have a look at?

**Comment by nmacchioni** [comment]
@galexite No worries at all, to be completely honest I'm not 100% sure what the policy is now (I believe we sync pin updates with PyTorch version releases), @bertmaher would know best

**Comment by bertmaher** [comment]
Yes, the pin updates/version bumps will be sync'ed with the PT releases.  Triton's 3.1.x release branch is intended to sync with PyTorch 2.5.

**Comment by bertmaher** [comment]
Let me check with @atalman on when we should move the ci_commit_pin for triton.  The release build follows a different process

**Comment by galexite** [comment]
@atalman sorry to @ you, any update on what the process is?

I'm happy for this to wait, but my understanding is that this pin move should be okay because I'm only moving to a commit within the same `release/3.1.x` branch (no release has been taken from that branch insofar as I am aware) and that this PR is straight to `main`?

**Comment by bertmaher** [comment]
Let's go ahead and bump this to match `release/3.1x` (which is now https://github.com/triton-lang/triton/commit/cf34004b8a67d290a962da166f5aa2fc66751326).  @galexite if you'll update the PR I'll approve & merge.  Thanks!

**Comment by galexite** [comment]
Done. Thanks @bertmaher!

**Comment by galexite** [comment]
Hey @bertmaher, could I get approval to run the workflows please?

**Comment by bertmaher** [comment]
Sure thing -- but also, it looks like an update to the `cudnn_frontend` submodule has slipped in here; could you please revert that?

**Comment by galexite** [comment]
@bertmaher done, sorry about that, I think it's because I didn't update submodules locally when pulling in those new changes.

**Comment by bertmaher** [comment]
Thanks @galexite !  Workflow approved and running!

**Pull request closed without merging**
