### PR TITLE
Use separate mypy caches for TestTypeHints cases

### PR DESCRIPTION
**Pull request by samestep**
Addresses one of the speed points in #50513 by making the `TestTypeHints` suite much faster when run incrementally. Also fixes an issue (at least on 5834438090a1b3206347e30968e48f44251a53a1) where running that suite repeatedly results in a failure every other run (see the test plan below).

**Test plan:**

First clear your [`mypy` cache](https://mypy.readthedocs.io/en/stable/command_line.html#incremental-mode):
```
$ rm -r .mypy_cache
```
Then run this twice:
```
$ python test/test_type_hints.py
```

- *Before:*
  ```
  ....
  ----------------------------------------------------------------------
  Ran 4 tests in 212.340s

  OK
  ```
  ```
  .F..
  ======================================================================
  FAIL: test_run_mypy (__main__.TestTypeHints)
  Runs mypy over all files specified in mypy.ini
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "test/test_type_hints.py", line 214, in test_run_mypy
      self.fail(f"mypy failed: {stdout} {stderr}")
  AssertionError: mypy failed: torch/quantization/fx/quantize.py:138: error: "Tensor" not callable  [operator]
  Found 1 error in 1 file (checked 1189 source files)
   

  ----------------------------------------------------------------------
  Ran 4 tests in 199.331s

  FAILED (failures=1)
  ```
- *After:*
  ```
  ....
  ----------------------------------------------------------------------
  Ran 4 tests in 212.815s

  OK
  ```
  ```
  ....
  ----------------------------------------------------------------------
  Ran 4 tests in 5.491s

  OK
  ```

### CODE REVIEW

**Review by xuzhao9 — COMMENTED** [review]
Do we also need to update ".gitignore" to reflect the mypy cache directory changes?
Also, maybe we should cache everything under ".mypy_cache", and put doc cache in ".mypy_cache/doc", example cache in ".mypy_cache/examples", and strict cache in ".mypy_cache/strict"?

**Comment by samestep** [comment]
> Do we also need to update ".gitignore" to reflect the mypy cache directory changes?
> Also, maybe we should cache everything under ".mypy_cache", and put doc cache in ".mypy_cache/doc", example cache in ".mypy_cache/examples", and strict cache in ".mypy_cache/strict"?

@xuzhao9 Good point, I completely forgot about that! At least for the `mypy` version I'm running (0.782), it looks like each of the cache directories automatically includes a `.gitignore` file with these contents:

```gitignore
# Automatically created by mypy
*
```

So I see a few options:

1. leave this PR it as-is
2. remove `.mypy_cache` from our `.gitignore` since it's unnecessary
3. change all the `--cache-dir`s to be subdirectories of `.mypy_cache` as you suggested

Any preference?

**Comment by walterddr** [comment]
change all the --cache-dirs to be subdirectories of .mypy_cache as you suggested sounds good to me
also circle seems to have some issue today so please also make sure it can work with the CI version of mypy (0.770)

**Comment by samestep** [comment]
> change all the --cache-dirs to be subdirectories of .mypy_cache as you suggested sounds good to me
> also circle seems to have some issue today so please also make sure it can work with the CI version of mypy (0.770)

@walterddr Done, and verified. :)

**Comment by samestep** [comment]
Hmm interesting... I just downgraded to `mypy` 0.770, cleared my cache dir(s), and ran again, and no `.gitignore` files were generated, even though [0.770 was supposed to be the `mypy` version that added that feature](https://mypy-lang.blogspot.com/2020/03/mypy-0770-released.html). In any case, this PR still leaves `.mypy_cache` in our own `.gitignore`, so we're fine by putting everything in subdirectories under that.

**Review by walterddr — APPROVED** [review]
looks good. please retrigger CI and see if things run fine before merging

**Pull request closed without merging**
