### PR TITLE
Manually bump onnx submodule to current latest

### PR DESCRIPTION
**Pull request by bddppq**

### CODE REVIEW

**Comment by bddppq** [comment]
@yinghai @houseroad

**Review by yinghai — APPROVED** [review]
Thanks!

**Review by houseroad — APPROVED** [review]

**Comment by houseroad** [comment]
https://github.com/onnx/onnx/pull/700 Fix the CI.

**Comment by bddppq** [comment]
pr/caffe2-conda2-ubuntu16.04-test failure is unrelated. This is ready to merge.

**Comment by houseroad** [comment]
@ezyang :-)

**Pull request merged**
