### PR TITLE
[inductor] fix UndefinedTensorImpl singleton can't export on Windows.

### PR DESCRIPTION
**Pull request by xuhancn**
This PR fix the `UndefinedTensorImpl::_singleton` can't export on Windows issue.
Snapshot:
image

The reason is MSVC can't export class static data to external linkage, ref: https://learn.microsoft.com/en-us/cpp/cpp/using-dllimport-and-dllexport-in-cpp-classes?view=msvc-170#_pluslang_using_dllimport_and_dllexport_in_c2b2bselectivememberimportexport 

I use another singleton implenmentation to avoid the issue, for Windows.

Since this PR, cpp_wrapper on Windows would start to work.
image

Next step, I will enable the cpp_wrapper UTs.

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jgong5 — COMMENTED** [review]
Can we do `getInstance()` regardless of whether it is MSVC build or not?

**Comment by xuhancn** [comment]
> Can we do `getInstance()` regardless of whether it is MSVC build or not?

https://github.com/pytorch/pytorch/pull/132326/commits/460143ff35d0c24c49cd4acf319ee639e9d9cbbc `getInstance()` will fail with `constexpr` on non-Windows OS.

**Review by jgong5 — APPROVED** [review]

**Comment by desertfire** [comment]
The doc you linked suggests using dllexport (C10_EXPORT in PyTorch) would solve the problem. Have you tried that?

**Comment by xuhancn** [comment]
> The doc you linked suggests using dllexport (C10_EXPORT in PyTorch) would solve the problem. Have you tried that?

@desertfire 
I tried the `C10_EXPORT` for the variable, and It doesn't work, I checked with dumpbin, and confirmed. class static variable is not exported.

**Review by desertfire — APPROVED** [review]

**Pull request closed without merging**
