### PR TITLE
Enable torch._refs.mean for nvFuser executor

### PR DESCRIPTION
**Pull request by IvanYashchuk**
This PR fixes a bug with `broadcast_in_dim` leading to the situation when reduction ops were not allowed to be used before `broadcast_in_dim`.

With this PR it's possible to run
```py
import torch
import torch._refs
from torch._prims.executor import make_traced

def foo(a):
    return torch._refs.mean(a, keepdim=False)

a = torch.randn(3, 3, device='cuda')
make_traced(foo)(a, executor="nvfuser")
```

### CODE REVIEW

**Review by mruberry — APPROVED** [review]
LGTM! May want someone from nvFuser to review, too

**Comment by IvanYashchuk** [comment]
@kevinstephano, could you please take a look at the small changes on the nvFuser part? I exposed `DataType::Null` to Python to be able to pass that to nvFuser's `sum`.

**Review by jjsjann123 — APPROVED** [review]
stamp on nvfuser side.

**Comment by IvanYashchuk** [comment]
[linux-focal-py3.7-clang7-asan / build](https://github.com/pytorch/pytorch/runs/6874612805?check_suite_focus=true) failure is unrelated:
```
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-py3-clang7-asan:31c7f8bc05f53ae34072f6260f82991a972e0524 not found: manifest unknown: Requested image not found
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-py3-clang7-asan:31c7f8bc05f53ae34072f6260f82991a972e0524 not found: manifest unknown: Requested image not found
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-py3-clang7-asan:31c7f8bc05f53ae34072f6260f82991a972e0524 not found: manifest unknown: Requested image not found
```

**Pull request closed without merging**
