### PR TITLE
Fallback CreateMutex/AtomicIter operators for mkl-dnn

### PR DESCRIPTION
**Pull request by PenghuiCheng**

### CODE REVIEW

**Comment by wesolwsk** [comment]
You are getting a tensor uninitialized error in data_parallel_model_test.RecurrentNetworkParallelTest.test_equiv_recurrent. Can you take a look?

**Comment by wesolwsk** [comment]
cuda_gpu_id indicates the id of the model copy on a node within a DPM instance. It is used for both CPU and GPU runs and should be renamed to something like device_id to avoid this confusion. Here, device_type 0 indicates CPU is being used.

**Comment by wesolwsk** [comment]
@PenghuiCheng - could you please rebase

**Comment by PenghuiCheng** [comment]
@wesolwsk ，had rebased.
Thanks!

**Pull request closed without merging**
