### PR TITLE
[Inductor] Setting kernel launch and exit callbacks for inductor generated triton kernels

### PR DESCRIPTION
**Pull request by Jokeren**
`CompiledKernel.launch_enter_hook` and `CompiledKernel.launch_exit_hook` are hooks that allow external tools to monitor the execution of Triton kernels and read each kernel's metadata. Initially, these hooks have a value of `None`.

Triton's kernel launcher passes hooks and kernel metadata by default, while Inductor's launcher doesn't. This PR could unify the parameters passed to both launchers so that tools can get information from both handwritten Triton kernels and Inductor-generated Triton kernels.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames

### CODE REVIEW

**Comment by Jokeren** [comment]
An alternative solution might be registering hooks via `inductor.config`. https://github.com/pytorch/pytorch/blob/main/torch/_inductor/config.py

cc @jansel @bertmaher

**Review by jansel — DISMISSED** [review]

**Comment by soulitzer** [comment]
@Jokeren @jansel  More context here https://docs.google.com/document/d/1_1Rd4LqDUgf1ZedVo-3Dcp6RtP9zHJ9qerfZYiWJi-A/edit

**Comment by bertmaher** [comment]
@soulitzer are there particular benchmarks that regressed due to this so we can give @Jokeren something concrete to look at?  At first blush this doesn’t seem like it should cause a slowdown - possibly something cpu-side to do with parsing the metadata?

**Comment by soulitzer** [comment]
One example is here: `python benchmarks/dynamo/torchbench.py --performance --bfloat16 -dcuda --output=foo.csv --inference --inductor --no-skip --dashboard --only opacus_cifar10  --disable-cudagraphs` (It should be reproducible for other benchmarks as well. The reason I chose this one in particular is because it was the quickest to run)

It's a little hard to reproduce because the difference is small for any given benchmark. I ran it ~10 times with and without the change, the averaged results gives a ~1% difference. 

The issue is there seems to be a slowdown of similar magnitude on all models, which leads to an overall slowdown on the hud from 1.34 -> 1.31 in the aggregate view (consistently observed for several days).

If this additional overhead is something we are okay with, maybe that's fine too(?), as long as we are explicit that this is the tradeoff we want to make.

**Comment by Jokeren** [comment]
> One example is here: `python benchmarks/dynamo/torchbench.py --performance --bfloat16 -dcuda --output=foo.csv --inference --inductor --no-skip --dashboard --only opacus_cifar10 --disable-cudagraphs` (It should be reproducible for other benchmarks as well. The reason I chose this one in particular is because it was the quickest to run)
> 
> It's a little hard to reproduce because the difference is small for any given benchmark. I ran it ~10 times with and without the change, the averaged results gives a ~1% difference.
> 
> The issue is there seems to be a slowdown of similar magnitude on all models, which leads to an overall slowdown on the hud from 1.34 -> 1.31 in the aggregate view (consistently observed for several days).
> 
> If this additional overhead is something we are okay with, maybe that's fine too(?), as long as we are explicit that this is the tradeoff we want to make.

Thanks for the useful information. I'll take a look

**Comment by Jokeren** [comment]
Hi @soulitzer , could you give it another try on the updated code? Seems like even indirect access of class members in python could trigger non-trivial overhead.

**Comment by Jokeren** [comment]
Hi @soulitzer , sorry for bothering, could you please take a look and see if the current PR avoids the regression?

**Comment by soulitzer** [comment]
Hi @Jokeren thanks for the follow up, I've just made a test [PR](https://github.com/pytorch/pytorch/pull/120210) and manually triggered a nightly inductor perf job. We should be able to verify the results in the [dashboard](https://hud.pytorch.org/benchmark/compilers) once the [job](https://github.com/pytorch/pytorch/actions/runs/7965161849)  is done running.

**Comment by Jokeren** [comment]
Do we use the *speedup* panel the check if there's regression? If so, seems fine to me :)

**Review by soulitzer — APPROVED** [review]

**Comment by soulitzer** [comment]
Thanks for the quick fix!

@pytorchbot merge

**Comment by Jokeren** [comment]
Many thanks @soulitzer !

**Pull request closed without merging**
