### PR TITLE
Fix intermittent link errors in NCCL build

### LINKED ISSUE #13362: ccache breaks when building nccl
see https://github.com/pytorch/pytorch/pull/13340#issuecomment-434524046 for a discussion.

When this is fixed, be sure to remove any workarounds

cc @malfet @seemethere @walterddr

### LINKED ISSUE #83790: Flaky CUDA 11.6 builds when compiling NCCL onerank_reduce.cu
### 🐛 Describe the bug

Recently, I'm seeing several flaky CUDA 11.6 builds when compiling `onerank_reduce.cu`. The error is as follows:

```
Compiling  onerank_reduce.cu                   > /var/lib/jenkins/workspace/build/nccl/obj/collectives/device/onerank_reduce.o
/usr/local/cuda/bin/crt/link.stub:111:118: error: redefinition of ‘const unsigned char def_module_id_str_02021d91_11_sendrecv_cu_0bc7b9c8_11152 []’
 static const unsigned char __DEFSTRNAME(id) [] __attribute__((aligned(1))) __attribute__((section ("__nv_module_id"))) = "def " __TO_STRING(id); \
                                                                                                                      ^
/tmp/tmpxft_0000575d_00000000-3_devlink.reg.c:61:1: note: in expansion of macro ‘DEFINE_REGISTER_FUNC’
 DEFINE_REGISTER_FUNC(_02021d91_11_sendrecv_cu_0bc7b9c8_11152)
 ^~~~~~~~~~~~~~~~~~~~
/usr/local/cuda/bin/crt/link.stub:79:30: note: ‘const unsigned char def_module_id_str_02021d91_11_sendrecv_cu_0bc7b9c8_11152 [44]’ previously defined here
 #define __DEFSTRNAME_CORE(X) def_module_id_str##X
                              ^
/usr/local/cuda/bin/crt/link.stub:80:25: note: in expansion of macro ‘__DEFSTRNAME_CORE’
 #define __DEFSTRNAME(X) __DEFSTRNAME_CORE(X)
                         ^~~~~~~~~~~~~~~~~
/usr/local/cuda/bin/crt/link.stub:111:28: note: in expansion of macro ‘__DEFSTRNAME’
 static const unsigned char __DEFSTRNAME(id) [] __attribute__((aligned(1))) __attribute__((section ("__nv_module_id"))) = "def " __TO_STRING(id); \
                            ^~~~~~~~~~~~
/tmp/tmpxft_0000575d_00000000-3_devlink.reg.c:13:1: note: in expansion of macro ‘DEFINE_REGISTER_FUNC’
 DEFINE_REGISTER_FUNC(_02021d91_11_sendrecv_cu_0bc7b9c8_11152)
 ^~~~~~~~~~~~~~~~~~~~
/tmp/tmpxft_0000575d_00000000-3_devlink.reg.c: In function ‘void __cudaRegisterLinkedBinary_02021d91_11_sendrecv_cu_0bc7b9c8_11152(void (*)(void**), void*, void*, void (*)(void*))’:
/usr/local/cuda/bin/crt/link.stub:77:36: error: redefinition of ‘void __cudaRegisterLinkedBinary_02021d91_11_sendrecv_cu_0bc7b9c8_11152(void (*)(void**), void*, void*, void (*)(void*))’
 #define __REGISTERFUNCNAME_CORE(X) __cudaRegisterLinkedBinary##X
                                    ^
/usr/local/cuda/bin/crt/link.stub:78:31: note: in expansion of macro ‘__REGISTERFUNCNAME_CORE’
 #define __REGISTERFUNCNAME(X) __REGISTERFUNCNAME_CORE(X)
                               ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda/bin/crt/link.stub:112:6: note: in expansion of macro ‘__REGISTERFUNCNAME’
 void __REGISTERFUNCNAME(id) (void (*callback_fp)(void **), void *prelinked_fatbinc, void *, void (*dummy_ref)(void *)) \
      ^~~~~~~~~~~~~~~~~~
/tmp/tmpxft_0000575d_00000000-3_devlink.reg.c:61:1: note: in expansion of macro ‘DEFINE_REGISTER_FUNC’
 DEFINE_REGISTER_FUNC(_02021d91_11_sendrecv_cu_0bc7b9c8_11152)
 ^~~~~~~~~~~~~~~~~~~~
/usr/local/cuda/bin/crt/link.stub:77:36: note: ‘void __cudaRegisterLinkedBinary_02021d91_11_sendrecv_cu_0bc7b9c8_11152(void (*)(void**), void*, void*, void (*)(void*))’ previously defined here
 #define __REGISTERFUNCNAME_CORE(X) __cudaRegisterLinkedBinary##X
                                    ^
/usr/local/cuda/bin/crt/link.stub:78:31: note: in expansion of macro ‘__REGISTERFUNCNAME_CORE’
 #define __REGISTERFUNCNAME(X) __REGISTERFUNCNAME_CORE(X)
                               ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda/bin/crt/link.stub:112:6: note: in expansion of macro ‘__REGISTERFUNCNAME’
 void __REGISTERFUNCNAME(id) (void (*callback_fp)(void **), void *prelinked_fatbinc, void *, void (*dummy_ref)(void *)) \
      ^~~~~~~~~~~~~~~~~~
/tmp/tmpxft_0000575d_00000000-3_devlink.reg.c:13:1: note: in expansion of macro ‘DEFINE_REGISTER_FUNC’
 DEFINE_REGISTER_FUNC(_02021d91_11_sendrecv_cu_0bc7b9c8_11152)
 ^~~~~~~~~~~~~~~~~~~~
Makefile:73: recipe for target '/var/lib/jenkins/workspace/build/nccl/obj/collectives/device/devlink.o' failed
make[5]: *** [/var/lib/jenkins/workspace/build/nccl/obj/collectives/device/devlink.o] Error 1
Makefile:51: recipe for target '/var/lib/jenkins/workspace/build/nccl/obj/collectives/device/colldevice.a' failed
make[4]: *** [/var/lib/jenkins/workspace/build/nccl/obj/collectives/device/colldevice.a] Error 2
Makefile:25: recipe for target 'src.build' failed
make[3]: *** [src.build] Error 2
CMakeFiles/nccl_external.dir/build.make:85: recipe for target 'nccl_external-prefix/src/nccl_external-stamp/nccl_external-build' failed
make[2]: *** [nccl_external-prefix/src/nccl_external-stamp/nccl_external-build] Error 2
CMakeFiles/Makefile2:2018: recipe for target 'CMakeFiles/nccl_external.dir/all' failed
make[1]: *** [CMakeFiles/nccl_external.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
```

The build error disappears in subsequent builds.  It looks very similar to an older issue reported [here](https://github.com/pytorch/pytorch/issues/13362#issuecomment-886806708), which pointed to sccache.

cc @malfet @seemethere @janeyx99 @pytorch/pytorch-dev-infra 

### Versions

CUDA 11.6.  So far I have seen the error in:

* libtorch-linux-bionic-cuda11.6-py3.7-gcc7 / build: https://hud.pytorch.org/pytorch/pytorch/commit/cd0ab154b5662f5dae36456971db5bc574d6cbe1
* linux-bionic-cuda11.6-py3.10-gcc7 / build: https://hud.pytorch.org/pytorch/pytorch/commit/b258709a1a3a6e57fe2d51c5be3d82a84b0f8e9a
* linux-jammy-cuda11.6-cudnn8-py3.8-clang12 / build: https://hud.pytorch.org/pytorch/pytorch/commit/d11d3dd036b4a7098ab3b4d333fcb556b97b4860

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #84245

Should fix #13362 and fix #83790

I think I've discovered the root cause of the intermittent nccl link
failures. If we look at the variable name in the redefinition error:
```
_02021d91_11_sendrecv_cu_0bc7b9c8_11152
```

this is the name of the file being compiled + some form of unique ID.
As part of NCCL's build process, the same file is compiled multiple
times with different macro definitions depending on which operator and
dtype are being compiled, e.g.
```
nvcc -DNCCL_OP=0 -DNCCL_TYPE=0 -dc sendrecv.cu -o sendrecv_sum_i8.o
```

Since the filename parts are the same, then if the unique IDs also
happen to collide then the entire identifier will collide and the link
fails. So the fix here is to generate a unique `.cu` file for each
object file. I've implemented this as a `.patch` file that gets
applied from our cmake code, but if we instead fork nccl that would be
cleaner.

### CODE REVIEW

**Comment by peterbell10** [comment]
I think the connection to `ccache` is simply that compilation runs with conflicting IDs completed successfully and so they "poison" the cache and which causes the error to happen consistently until you clear your cache.

**Comment by janeyx99** [comment]
AHHHH how did I miss this important fix! Thanks so much @peterbell10 for looking into and figuring this out.

**Review by janeyx99 — APPROVED** [review]
thanks! we can land this to unblock folks now--I'm not sure what forking from nccl would look like ccing @malfet

**Review by malfet — APPROVED** [review]
It feels weird, shouldn't we just propose this fix against NCCL?

**Comment by janeyx99** [comment]
We should propose fix on NCCL + then update our code once that's landed, but this would be faster, no?

**Comment by janeyx99** [comment]
Hey @peterbell10, I've patched your changes to a PR for nccl https://github.com/NVIDIA/nccl/pull/720--does it look right to you? If so, it'd be cool to get that landed and fast-forward pytorch to not need this patch.

**Pull request closed without merging**
