### PR TITLE
Fix build on s390x

### PR DESCRIPTION
**Pull request by AlekseiNikiforovIBM**
Rename s390x-specific zvector functions with same name.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by colesbury** [comment]
@malfet, would you please review this?

**Comment by AlekseiNikiforovIBM** [comment]
Could you take a look at this PR please? Build is broken on s390x for over 3 weeks now. It's broken due to function name collision with https://github.com/pytorch/pytorch/blob/ad7b5d32b67a1c976addbabc772f4791acab9e7a/aten/src/ATen/cpu/vec/functional_bfloat16.h#L20-L22 which was hit after some of general code updates

**Comment by huydhn** [comment]
cc @malfet

**Review by malfet — APPROVED** [review]
I have no way of checking that it's actually doing anything, but don't see any harm in those changes

**Comment by malfet** [comment]
> Could you take a look at this PR please? Build is broken on s390x for over 3 weeks now. It's broken due to function name collision with
> 
> https://github.com/pytorch/pytorch/blob/ad7b5d32b67a1c976addbabc772f4791acab9e7a/aten/src/ATen/cpu/vec/functional_bfloat16.h#L20-L22
> 
> which was hit after some of general code updates

Can you point to some build logs somewhere before and after this change?

**Comment by AlekseiNikiforovIBM** [comment]
> > Could you take a look at this PR please? Build is broken on s390x for over 3 weeks now. It's broken due to function name collision with
> > https://github.com/pytorch/pytorch/blob/ad7b5d32b67a1c976addbabc772f4791acab9e7a/aten/src/ATen/cpu/vec/functional_bfloat16.h#L20-L22
> > 
> > which was hit after some of general code updates
> 
> Can you point to some build logs somewhere before and after this change?

I don't have any public logs after this change, but before is here:
https://github.com/pytorch/pytorch/actions/runs/8784408944/job/24102575144?pr=120398

**Pull request closed without merging**
