### PR TITLE
[primTorch] Add ref for `new_empty_strided`

### PR DESCRIPTION
**Pull request by nkaretnikov**

### CODE REVIEW

**Comment by nkaretnikov** [comment]
@ngimel ci is green, ptal

**Review by ezyang — APPROVED** [review]

**Comment by nkaretnikov** [comment]
@ezyang ptal again

**Comment by ezyang** [comment]
sample log https://github.com/pytorch/pytorch/runs/7890654994?check_suite_focus=true

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
