### PR TITLE
[c10d][logging] Add wait counter for time spent in object to tensor and tensor to object

### PR DESCRIPTION
**Pull request by fduwjj**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #140414

Originally we want to leverage the timer logger to measure the time spent in object to tensor and tensor to object (https://github.com/pytorch/pytorch/pull/139757) But it gets reverted (internally) because of a performance regression. We now use wait counter instead which is more lightweight.

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by wconstab — COMMENTED** [review]
do you plan to roll this out or just land it? how sure are we that the _WaitCounter is faster enough to not get reverted again?

**Comment by fduwjj** [comment]
I worked with Boris to verify that on a internal typical workload, the perf difference after adding this counter is less than 5% of latency change. So we got green light for a merge.

**Review by c-p-i-o — APPROVED** [review]

**Review by XilunWu — APPROVED** [review]

**Review by wz337 — APPROVED** [review]
Oh. For my learning, then should we just kill time logger and use this instead?
For exception, performance doesn't matter but time logger could affect performance.

**Comment by fduwjj** [comment]
@wz337 let's see how this goes. The init time is just one time, so it's not as expensive as this one..

**Pull request closed without merging**
