### PR TITLE
[dynamo][ci] Pin beartype to 0.15.0

### PR DESCRIPTION
**Pull request by justinchuby**
CIs are failing because of https://github.com/beartype/beartype/issues/282

cc @seemethere @malfet @pytorch/pytorch-dev-infra @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by thiagocrepaldi — APPROVED** [review]
do we need to pin at all? wouldnt any latest stable release suffice?

**Comment by justinchuby** [comment]
> do we need to pin at all? wouldnt any latest stable release suffice?

For reproducibility in CI I think it’s good to pin

**Comment by leycec** [comment]
Sincere apologies for the extreme breakage @justinchuby and fellow @pytorch crew.

I'm as appalled as you are. Possibly even more appalled, actually. To ensure this *never* happens again, I've just added a new integration test to @beartype's test suite exercising @beartype against PyTorch. I *will* resolve this immediately. Until then, I can only profusely apologize. Gah! This is so terribad. :scream:

**Pull request closed without merging**
