### PR TITLE
Feature: cudnn convolution out

### LINKED ISSUE #115611: Optimize `cudnn_convolution_out` to Reduce Unnecessary Memory Allocation and Copy
### 🚀 The feature, motivation and pitch

In `build/aten/src/ATen/CompositeViewCopyKernels.cpp`

```c++
at::Tensor & cudnn_convolution_out(const at::Tensor & self, const at::Tensor & weight, at::IntArrayRef padding, at::IntArrayRef stride, at::IntArrayRef dilation, int64_t groups, bool benchmark, bool deterministic, bool allow_tf32, at::Tensor & out) {
  auto tmp_output = at::_ops::cudnn_convolution::call(self, weight, padding, stride, dilation, groups, benchmark, deterministic, allow_tf32);
    resize_out_helper(out, tmp_output);
  copy_arg(out, tmp_output);
  return out;
}
```

Currently, it internally uses `cudnn_convolution` that allocates a temporary output tensor, even when an output tensor is already provided, causing extra memory allocation and data copying. Functions like `cudnn_batch_norm_backward_out`, `cudnn_affine_grid_generator_backward_out` have the same behaviour.

Shall we directly compute the convolution results into the provided output tensor out, avoiding the creation of a temporary tensor and the subsequent copy operation?

Reducing memory overhead and unnecessary data movements should enhance performance, particularly in large-scale and performance-sensitive applications.

### Alternatives

_No response_

### Additional context

_No response_

cc @csarofeen @ptrblck @xwang233 @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### PR DESCRIPTION
**Pull request by yewentao256**
Fixes #115611

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Could you please remove lint changes? You can use `lintrunner` to run PT lint if you need.

**Comment by yewentao256** [comment]
> Could you please remove lint changes? You can use `lintrunner` to run PT lint if you need.

Apologies for combining the lint changes with the feature in my previous submission. I have now modified the code. Please review it at your convenience.

**Comment by yewentao256** [comment]
BTW, A basic test case:

```c++
#include <torch/torch.h>
#include <iostream>

int main() {
    if (torch::cuda::is_available()) {
        auto input = torch::rand({1, 1, 4, 4}, torch::device(torch::kCUDA));
        auto weight = torch::rand({1, 1, 3, 3}, torch::device(torch::kCUDA));
        std::vector<int64_t> stride = {1, 1};
        std::vector<int64_t> padding = {1, 1};
        auto output = torch::empty({1, 1, 4, 4}, torch::device(torch::kCUDA));

        at::cudnn_convolution_out(output, input, weight, padding, stride, padding, 1, false, false, true);
        std::cout << output << std::endl;
    } else {
        std::cerr << "CUDA is not available!" << std::endl;
    }

    return 0;
}
```

**Review by albanD — APPROVED** [review]
Thanks for the PR that sounds good!

**Pull request closed without merging**
