### PR TITLE
[Inductor] Build FX Linear + Permute Vertical Fusion in Inductor

### PR DESCRIPTION
**Pull request by jiawenliu64**
Summary:
Build fx-based linear/matmul/bmm + permute/transpose vertical fusion in Inductor

For an internal Ads model: **1.15x -> 1.36x speedup**

Differential Revision: D41071665

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by jianyuh — APPROVED** [review]
Passing the approval from https://github.com/pytorch/pytorch/pull/88566

**Review by jansel — APPROVED** [review]

**Comment by malfet** [comment]
@jiawenliu64 why did you think signal was unrelated?

**Comment by jiawenliu64** [comment]
Hi @malfet, as [`config.permute_fusion`](https://github.com/pytorch/pytorch/pull/88859/files#diff-c2319b0fbfd2689673f10875746077c3426b1adbe5e2a3ab4bd701db75446101R430) is turned off by default in [`config.py`](https://github.com/pytorch/pytorch/pull/88859/files#diff-90b954bddfc0db29441328610022aa85c98d3e2647875f7982a6b42acdf2b183R79), the codes should be not called

Additionally, https://github.com/pytorch/pytorch/pull/88927 has the `macos-12-py3` issue. I think the signal is not related. Please advise how to address this issue in the trunk, and I will submit another PR. Thanks!

**Comment by jianyuh** [comment]
@jiawenliu64 Looks like we need to turn it on inside the unit test for permute_fusion.

```
test_linear_binary_cpu (__main__.CpuTests) ... ok (0.005s)
    test_linear_permute_fusion_cpu (__main__.CpuTests) ... FAIL (0.040s)
    test_linear_permute_fusion_cpu (__main__.CpuTests) ...     test_linear_permute_fusion_cpu failed - num_retries_left: 3
  Traceback (most recent call last):
    File "inductor/test_torchinductor.py", line 1644, in test_linear_permute_fusion
      self.assertTrue(torch.allclose(module(input), traced(input)))
  AssertionError: False is not true
  
  FAIL (0.020s)
    test_linear_permute_fusion_cpu (__main__.CpuTests) ...     test_linear_permute_fusion_cpu failed - num_retries_left: 2
  Traceback (most recent call last):
    File "inductor/test_torchinductor.py", line 1644, in test_linear_permute_fusion
      self.assertTrue(torch.allclose(module(input), traced(input)))
  AssertionError: False is not true
  
  FAIL (0.020s)
    test_linear_permute_fusion_cpu (__main__.CpuTests) ...     test_linear_permute_fusion_cpu failed - num_retries_left: 1
  Traceback (most recent call last):
    File "inductor/test_torchinductor.py", line 1644, in test_linear_permute_fusion
      self.assertTrue(torch.allclose(module(input), traced(input)))
  AssertionError: False is not true
```

in  https://github.com/pytorch/pytorch/actions/runs/3472612533/jobs/5804115669

**Pull request closed without merging**
