### PR TITLE
Reland #87025 and fix periodic tests

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #87084

- Relands #87025 
- disables failing tests related to https://github.com/pytorch/pytorch/issues/93542
- Reverts https://github.com/pytorch/pytorch/commit/d01eea6027c26bf100fc99a705669f60648964ae

cc @lezcano @fdrocha @mlazos @soumith @voznesenskym @yanboliang

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Review by voznesenskym — APPROVED** [review]

**Comment by malfet** [comment]
Please also revert changes introduced by https://github.com/pytorch/pytorch/commit/d01eea6027c26bf100fc99a705669f60648964ae (to really test on sm86)

**Pull request closed without merging**
