### PR TITLE
Post process onnx proto

### PR DESCRIPTION
**Pull request by bddppq**
Apply the post processing to onnx generated protobuf headers to redirect protobuf symbols to the hidden libprotobuf copy inside libcaffe2.

### CODE REVIEW

**Comment by bddppq** [comment]
@orionr @Yangqing @yinghai The pairing onnx PR has been merged now, this one is ready to review.

**Comment by bddppq** [comment]
@onnxbot retest this please

**Review by orionr — APPROVED** [review]

**Comment by bddppq** [comment]
Test failures in pr/pytorch-win-ws2016-cuda9-cudnn7-py3:
```
17:36:01 ======================================================================
17:36:01 FAIL: test_PReLU_1d_multiparam_cuda (__main__.TestNN)
17:36:01 ----------------------------------------------------------------------
17:36:01 Traceback (most recent call last):
17:36:01   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test1\test\common.py", line 216, in wrapper
17:36:01     self.id(), after - before, i))
17:36:01   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test1\test\common.py", line 324, in assertEqual
17:36:01     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
17:36:01 AssertionError: 1024 not less than or equal to 1e-05 : __main__.TestNN.test_PReLU_1d_multiparam_cuda leaked -1024 bytes CUDA memory on device 0
```
don't seem to be related, also checked previous build history, this job seems to be flaky,

**Pull request merged**
