### PR TITLE
Release the GIL before invokeOperator

### LINKED ISSUE #41865: Poor performance of dynamic quantazation
## 🐛 Bug

I am experimenting with dynamic quantization as described here:
https://pytorch.org/blog/introduction-to-quantization-on-pytorch/

I got a pretty good speedup when running with a single thread. (This is a GRPC server application that serves pytorch models). However, I do not see any improvement when using multiple threads and processing multiple concurrent requests. This does not happen when dynamic quantization is not being used: I see pretty good scaling up to about 10 threads. The CPU utilization when running with 10 threads but without quantization is well over 700%. However, when dynamic quantization is enabled, CPU load peaks around 150%, meaning that most of the cores sit idle.

This leads me to believe that python's GIL is the culprit. I noticed that in many parts of the code, pytorch does the following:

pybind11::gil_scoped_release no_gil;

But this does not happen in qlinear_dynamic.cpp which runs on dynamic quantization. This again implies that when dynamic quantization is used, GIL does not get released. This would certainly explain why we see improved performance with one thread but not with multiple threads.

## To Reproduce

1. Set OMP_NUM_THREADS=1 environment variable.

2. Load any model and apply dynamic quantization:

model = torch.quantization.quantize_dynamic(model, {torch.nn.Linear}, dtype=torch.qint8)

3. Use threadpool to make multiple concurrent calls to to the model.

## Expected behavior

Throughput should scale with the number of threads in the threadpool.

## Environment

Collecting environment information...
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.5
GCC version: Could not collect
CMake version: version 3.15.0

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.1
[pip3] numpy==1.18.4
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] torch==1.5.1
[pip3] torchvision==0.6.1
[conda] Could not collect

## Additional context

If you remove the dynamic quantization line, single-thread performance is slower but throughput does scale properly with the number of threads in the threadpool.

cc @ezyang @gchanan @zou3519 @suo @gmagogsfm @bhosmer @smessmer @ljk53 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo @VitalyFedyunin @ngimel

### PR DESCRIPTION
**Pull request by wconstab**
Fixes #41865

### CODE REVIEW

**Comment by ezyang** [comment]
This looks plausible. One thing that I would like to be double checked, though, is that no Python accesses happen inside these function calls here.

**Comment by wconstab** [comment]
ok. i did look and didn't see any at the first layer down but didn't check carefully.  but, my change also didn't seem to improve performance as measured by the repro script I posted in the issue, so i'm not sure we're on the right track.  would you suggest using libgpumon to check what's bottlenecking? or how else do you diagnose typically?

**Comment by ezyang** [comment]
1. I'd first make sure the repro is right. I saw you posted on the other issue, but what I would show is that when I remove custom operator call, we start seeing scaling improvements with multithreading
2. Assuming the repro is working, I'd breakpoint inside the dynamic quantization kernel and then look at the stack and see if the code I thought was relevant is actually the relevant code

**Comment by wconstab** [comment]
@ezyang updates:

- got a new repro script based on distilbert that lets me confirm some improvement with the gil release
- confirmed that the quantized::linear kernel is one used by the distilbert, and it passes through 'invokeOperatorFromPython'
- checked the getOperator code visually, looks clean of python (but, hard to be sure given the () call dispatches to all different ops) -- any way to 'assert' no python past a GIL release?

My distilbert numbers without and with gil release show a definite improvement, although scaling could still be better.  I'm not sure if there's another low hanging fruit though- in the quantize distilbert case, the quantized::linear kernel only takes 28% of the overall CPU time, so lots of little operators are dominating.  

```
Threads    1        4       8       16                                                                                                          
---------  -------  ------  ------  ------
Baseline
Time (s)   1.06     0.61    0.58    0.60                                                                                                    
Scaling    100.00%  43.40%  22.67%  11.02%

Release GIL 
Time (s)   1.04     0.32    0.21    0.25                                                                                        
Scaling    100.00%  81.03%  60.69%  26.11%
```

**Comment by ezyang** [comment]
I could believe that there is opportunity for general torch.ops performance tuning. It goes through a different codepath than regular torch ops and thus hasn't had as much battle testing.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
