### PR TITLE
Upgrade CI to ROCm5.0

### LINKED ISSUE #65884: DISABLED test_fn_grad_min_binary_cuda_float64 (__main__.TestGradientsCUDA)
Platforms: rocm

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

### PR DESCRIPTION
**Pull request by jithunnair-amd**
cc @jaglinux @pruthvistony @arindamroy-eng @kyleczh

Depends on https://github.com/pytorch/pytorch/pull/73906

Fixes https://github.com/pytorch/pytorch/issues/65884 as well

### CODE REVIEW

**Review by osalpekar — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@osalpekar @seemethere I rebased the PR, please take another look and merge if it looks okay

**Comment by jithunnair-amd** [comment]
@osalpekar @seemethere Please take a look at this PR again. The docker builds and test jobs passed. Thanks!

**Review by malfet — CHANGES_REQUESTED** [review]
Lint changes seems relevant, can you please rebase and regenerate the files

**Comment by jithunnair-amd** [comment]
@seemethere @malfet All CI runs passed. Please merge before this PR gets stale again :)

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
