### PR TITLE
 C10D extension to enable per-thread PG

### PR DESCRIPTION
**Pull request by kumpera**
Move a bunch of globals to instance methods and replace all use to them.

We move all PG related globals under World and use a singleton instance under _world.

This creates an undocumented extension point to inject full control of how how c10d
state behaves.

One simple hack is to change _world to an implementation that uses a threadlocal
and enable per-thread PGs.

It almost get DDP working and the PG is missing an implementation of all_reduce.

This enables notebook usage of PTD, which is a big deal for learning it:
https://gist.github.com/kumpera/32cb051fa26b8cad8bdf671f968dcd68

This change ensures BC by keeping the global variables around and have the default _World wrap it.

### CODE REVIEW

**Comment by kumpera** [comment]
Thanks to @rohan-varma  for the suggestion on how to handle the BC breakage I ran into.

**Review by rohan-varma — APPROVED** [review]
Stamping as this is a reland with fixes to internal CI.

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your PR but it breaks macos tests https://hud.pytorch.org/pytorch/pytorch/commit/97abc21f2bda38e73de2a86da7f43c8126930681' -c landrace

This is probably a land race because the PR signals look fine

**Comment by kumpera** [comment]
> @pytorchbot revert -m 'Sorry for reverting your PR but it breaks macos tests https://hud.pytorch.org/pytorch/pytorch/commit/97abc21f2bda38e73de2a86da7f43c8126930681' -c landrace
> 
> This is probably a land race because the PR signals look fine

The error is the following:

```
2022-10-13T22:51:23.2103410Z   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2022-10-13T22:51:23.2103780Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_3246079017/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 39, in <module>
2022-10-13T22:51:23.2104090Z     from torch.testing._internal.distributed.multi_threaded_pg import (
2022-10-13T22:51:23.2104470Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_3246079017/lib/python3.9/site-packages/torch/testing/_internal/distributed/multi_threaded_pg.py", line 11, in <module>
2022-10-13T22:51:23.2104760Z     from torch._C._distributed_c10d import _create_work_from_future
2022-10-13T22:51:23.2105050Z ModuleNotFoundError: No module named 'torch._C._distributed_c10d'; 'torch._C' is not a package
2022-10-13T22:51:23.2105200Z 
```

Which looks like a legit failure. It requires building PT with distributed disabled to reproduce.

**Pull request closed without merging**
