### PR TITLE
[primTorch] add meta implementation for `upsample_nearest2d_backward`

### PR DESCRIPTION
**Pull request by nkaretnikov**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96612

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by nkaretnikov** [comment]
Enables `test_upsample_nearest2d_backward_dynamic_shapes`. `upsample_nearest2d_backward` in ATen is implemented using `structured`, which doesn't support `SymInt` (known codegen limitation).

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
I wonder why the aot autograd xfail didn't remove

**Comment by nmacchioni** [comment]
Hey, this broke the lint runner.

**Comment by nkaretnikov** [comment]
@ezyang @malfet Could you revert please? Not sure why this didn't trigger before.

**Pull request closed without merging**
