### PR TITLE
[FlexAttention] Remove restriction on QK headdim > V headdim

### PR DESCRIPTION
**Pull request by drisspg**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135884

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by Chillee — APPROVED** [review]

**Comment by drisspg** [comment]
Currently blocked by: PyTorch Triton getting:
 https://github.com/triton-lang/triton/pull/4706
  https://github.com/triton-lang/triton/pull/4705

**Comment by drisspg** [comment]
This is still blocked on Triton upstream pin not being bumped similiar to ; https://github.com/pytorch/pytorch/pull/135627/


Will update once it gets bumped.

cc @atalman

**Comment by kit1980** [comment]
@drisspg are you still targeting 2.5?
There are just couple of days for cherry-picks left.

**Comment by drisspg** [comment]
Tested locally, once https://github.com/pytorch/pytorch/pull/136874 lands then this should be good to land

**Comment by drisspg** [comment]
@pytorcbot merge

**Pull request closed without merging**
