### PR TITLE
Add onnx support for clamp_min clamp_max

### PR DESCRIPTION
**Pull request by houseroad**
Add support for clamp as required by https://github.com/onnx/onnx/issues/1168

### CODE REVIEW

**Comment by sakaia** [comment]
Does this issue not update "docs/source/onnx.rst" as supported operator?

**Comment by Maratyszcza** [comment]
I think we should combine the two operators into `clamp`, with min and max boundaries. You can always set `min=-INFINITY/INT_MIN/etc` for a one-sided clamp.

**Pull request closed without merging**
