### PR TITLE
[Submodule] Bump pybind11 to v2.13.5

### PR DESCRIPTION
**Pull request by cyyever**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by malfet** [comment]
We can, but why? Does it fix some problem or make something faster or just fix some bug we might potentially encounter?

**Comment by cyyever** [comment]
There are some bug fixes since 2.13.1, the most important is https://github.com/pybind/pybind11/pull/5246

**Pull request closed without merging**
