### PR TITLE
[reland][inductor] Add an AOT compilation mode for Inductor CPP backend

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #95985

Summary: This is a reland of https://github.com/pytorch/pytorch/pull/94822

cc @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by malfet** [comment]
Please note, that it also added about 2h of test time to MacOS x86 shards and about 30 min of test time to MacOS M1. Does this change really need such exhaustive testing?

**Comment by desertfire** [comment]
I think it only affected CPU tests. Let me look into it.

**Pull request closed without merging**
