### PR TITLE
Add interfaces in lr_scheduler.pyi

### PR DESCRIPTION
**Pull request by tczhangzhi**
Some interfaces of schedulers defined in lr_scheduler.py are missing in lr_scheduler.pyi.

### CODE REVIEW

**Comment by tczhangzhi** [comment]
Fix #23934

**Comment by tczhangzhi** [comment]
In fact, I think we should add an automatic function here instead of manual definition.
https://github.com/tczhangzhi/pytorch/blob/master/tools/pyi/gen_pyi.py#L602

**Review by ezyang — APPROVED** [review]

**Review by ezyang — CHANGES_REQUESTED** [review]
Test failures are real:

```

Aug 07 14:02:25 test_doc_examples (__main__.TestTypeHints) ... torch/optim/lr_scheduler.pyi:35: error: non-default argument follows default argument
```

**Comment by tczhangzhi** [comment]
> Test failures are real:
> 
> ```
> 
> Aug 07 14:02:25 test_doc_examples (__main__.TestTypeHints) ... torch/optim/lr_scheduler.pyi:35: error: non-default argument follows default argument
> ```
Thanks for your fast reply and I am sorry for that stupid mistake.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
