### PR TITLE
Increase the memory requirement of test_reduction_split

### PR DESCRIPTION
**Pull request by zasdfgbnm**
This test is constantly failing on my 12GB GPU

### CODE REVIEW

**Comment by ngimel** [comment]
hm, that's weird, tensor requires just over 4 GB of memory, result and expected are also less than 1 GB each. Are you running the test in isolation or as part of the test suite?

**Comment by zasdfgbnm** [comment]
I am running it as part of the test suit. I don't know why it is failing, and my card has 12GB, and the error message says unable to allocate XXXMB memory, 7.XXGB is already allocated. Maybe the reason is, running the whole test suit creates too much fragments?

**Comment by ngimel** [comment]
That's possible. What if you do empty_cache before this test? If that helps, maybe empty_cache should be part of the @largeCUDATensorTest wrapper.

**Comment by zasdfgbnm** [comment]
tested that `empty_cache` does not work. One strange thing is, I can only reproduce this failure with my amin branch, but my branch does not change anything about this test, no about reduction kernel.

**Review by mruberry — APPROVED** [review]
Sounds good. Thanks @zasdfgbnm!

**Comment by mruberry** [comment]
Looks like I missed the conversation while stamping in PRs yesterday. @zasdfgbnm, what would you think of filing an issue for this following your discussion with @ngimel instead of us trying to paper over the underlying issue?

**Comment by zasdfgbnm** [comment]
@mruberry An issue about what? About this specific test or about `largeCUDATensorTest` in general?

**Comment by mruberry** [comment]
> @mruberry An issue about what? About this specific test or about `largeCUDATensorTest` in general?

That you've been able to hit OOM when running this test while developing unrelated features, and that the OOM is despite the test not using that much memory and after emptying the cache. As you mention above, this suggests the test suite is holding CUDA memory between tests, which it probably shouldn't do.

**Comment by zasdfgbnm** [comment]
@mruberry Oh, your comment https://github.com/pytorch/pytorch/pull/43257#issuecomment-681166414 remind me of something. Maybe I should try `gc.collect(); torch.cuda.empty_cache()` instead of just `torch.cuda.empty_cache()`. Let me try that to see the result.

**Comment by zasdfgbnm** [comment]
No, adding `gc.collect()` does not help.

**Comment by zasdfgbnm** [comment]
I don't think this is a problem any more.

**Pull request closed without merging**
