### PR TITLE
add Half to cat fast path on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #96082
* #96081
* #96080
* #96079
* __->__ #96078

Extend current fast path on `cat` with `Half`: for non-arithmetic Ops, simply do `Vec::load` and `Vec::store`.

cc @jgong5 @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Comment by mingfeima** [comment]
@ezyang need core maintainer here. This one is very simple now, as Half has been added to the fast path, we can use `at::isFloatingType(dtype);` now.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
With this sort of thing, it's nice to see the before after perf numbers too

**Pull request closed without merging**
