### PR TITLE
Add xla/ folder to gitignore

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #84632

As per title

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by alanwaketan** [comment]
Is there any reasons why we want to ignore the xla folder? Probably only the xla team will have the xla folder checked out. And then for us, we certainly don't want to ignore the whole folder as it will prevents VSCode file search from functioning correctly.

**Comment by JackCaoG** [comment]
Did a quick experiment, this change will only prevent `xla` shows up in `Untracked files:` during `git status`. Even with `git commit` it won't commit xla change to pytorch. If that's the case, maybe we can revert it change and unblock xla team from using. VsCode file search :D.

**Comment by lezcano** [comment]
Would this solve this issue?
https://stackoverflow.com/questions/55949132/vscode-how-to-get-file-search-not-content-to-include-git-ignored-files
See also the second answer for a more fine-grained solution.

**Comment by alanwaketan** [comment]
Yea, we are using this workaround. I'm curious what's the benefits of this change since it has made some people life harder?

**Comment by ezyang** [comment]
it means `git add .` works OK when there is an xla folder in your checkout; otherwise we will attempt to add xla folder

**Pull request closed without merging**
