### PR TITLE
Fix the MPS Heap volatility

### LINKED ISSUE #77829: Tensor will become all zero on MPS after switching to other softwares
### 🐛 Describe the bug

Running PyTorch on Jupyter notebook (with VSCode), simply do:

```python
x = torch.randn(5, 4).to('mps')
```

Then, switching to other software, such as WeChat. Going back to VSCode, I found x become:

```python
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='mps:0')
```

### Versions

PyTorch version: 1.12.0.dev20220518
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:13:24)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: macOS-12.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] torch==1.12.0.dev20220518
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.0.4
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.13
[pip3] torch-spline-conv==1.2.1
[pip3] torchvision==0.2.2
[conda] numpy                     1.22.2           py38h9d822b3_0    conda-forge
[conda] pytorch                   1.12.0.dev20220518         py3.8_0    pytorch-nightly
[conda] torch-cluster             1.6.0                    pypi_0    pypi
[conda] torch-geometric           2.0.4                    pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torch-sparse              0.6.13                   pypi_0    pypi
[conda] torch-spline-conv         1.2.1                    pypi_0    pypi
[conda] torchvision               0.2.2                      py_3    pytorch

cc @ezyang @gchanan @zou3519

### PR DESCRIPTION
**Pull request by kulinseth**
Fixes #77829

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by suo** [comment]
I am going to revert this PR and https://github.com/pytorch/pytorch/pull/78312 in order to avoid the merge conflict

**Comment by kulinseth** [comment]
> @pytorchbot revert -m "this broke trunk iOS tests, see: https://hud.pytorch.org/pytorch/pytorch/commit/c8ab55b2939c4cd5cd8d2e0605fdfd09e8eff294" -c nosignal

``` 
File "/Users/runner/work/_temp/anaconda/lib/python3.9/site-packages/coremltools/models/__init__.py", line 6, in <module>
    from . import datatypes
  File "/Users/runner/work/_temp/anaconda/lib/python3.9/site-packages/coremltools/models/datatypes.py", line 11, in <module>
    from ..proto import FeatureTypes_pb2 as _FeatureTypes_pb2
  File "/Users/runner/work/_temp/anaconda/lib/python3.9/site-packages/coremltools/proto/FeatureTypes_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/Users/runner/work/_temp/anaconda/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
 ```

The coreml failure seems to be related to protobuf, which seems unrelated to this change.

**Comment by suo** [comment]
Hmm, I was going by the fact that this build started failing on master once this was merged. Possibly it's some unpinned dependency that happened to bump at the same time.

**Comment by suo** [comment]
I'll look in the morning—if the revert doesn't fix it we can reland these changes and I'll engage the maintainers of the coreml integration to see what's going on

**Comment by kulinseth** [comment]
https://github.com/pytorch/pytorch/pull/78340, i have added back the changes. Please take a look.

**Comment by malfet** [comment]
iOS failures are unrelated, as job still fails after the revert: https://github.com/pytorch/pytorch/runs/6603718890?check_suite_focus=true

**Pull request closed without merging**
