### PR TITLE
Convenience script for getting correct Triton nightly binary

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96669

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Review by malfet — APPROVED** [review]
Can you call it `install_trition_wheel` or something?

**Comment by malfet** [comment]
Bot should detect submodule update :)

**Review by albanD — COMMENTED** [review]
How is this different from what `make triton` does?

**Comment by ezyang** [comment]
make triton builds triton from source

**Pull request closed without merging**
