### PR TITLE
Revert "Mark ROCm trunk job as unstable (#94550)"

### PR DESCRIPTION
**Pull request by pruthvistony**
This reverts commit 79ed6b246c768230aa1bf14eed804c8156a3f87f.

Repo.radeon.com issue is fixed.

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!  Waiting for the job to pass to confirm

**Comment by pruthvistony** [comment]
@huydhn ,
I have added `ciflow/unstable` dont see the ROCm job triggered yet. 
is any other label required to be added?

**Review by jithunnair-amd — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
ROCm jobs passed and ran tests successfully in trunk workflow

**Pull request closed without merging**
