### PR TITLE
Remove debug code

### PR DESCRIPTION
**Pull request by mlazos**
Removes some debug code

cc @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by desertfire — APPROVED** [review]
Not sure what these are originally used for, but LGTM.

**Review by williamwen42 — APPROVED** [review]

**Pull request closed without merging**
