### PR TITLE
[quant][embedding qat] Re-Land Support Embedding QAT via FX API

### LINKED ISSUE #61865: [quant] Support QAT for Embedding/EmbeddingBag
Currently we only support PTQ for embedding modules https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/embedding_ops.py

This issue tracks the support to 
1. add QAT modules for Embedding/EmbeddingBag modules
2. Do the module swap in eager mode to use these modules
3. Update FX quantization flow to support the new modules

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

### PR DESCRIPTION
**Pull request by b-koopman**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #69334
* __->__ #69333

Summary:
Original PR reverted due to break with incompatible qengine on Mac OS, this diff fixes that.

Support QAT workflow by using torch.fx QAT API.  e.g. `prepare_qat_fx` and `convert_fx`.

Test Plan:
`pytest test/quantization/fx/test_quantize_fx.py -v -k "test_qat_embedding_linear"`

Reviewed By: jingsh, supriyar

Make qengine compatible w/ MacOS

Differential Revision: [D32814827](https://our.internmc.facebook.com/intern/diff/D32814827)

### CODE REVIEW

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32814827).

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32814827).

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32814827).

**Review by jingsh — APPROVED** [review]

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32814827).

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32814827).

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32814827).

**Pull request closed without merging**
