### PR TITLE
[pytorch] add AutoNonVariableTypeMode guard on JIT->ATen boundary

### PR DESCRIPTION
**Pull request by ljk53**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#26868 [pytorch] add AutoNonVariableTypeMode guard on JIT->ATen boundary**

Summary:
- This PR together with #26908 attempt to address issue #26764 (`Issue 1` mentioned below).

- Current flow without USE_STATIC_DISPATCH (for server build):
```
S1. jit::load()
  a. JIT calls variable_factories.h methods to instantiate variable instances.

  b. JIT calls some ATen methods during intitalization, e.g.: conv_prepack, q_scale.
    b.1 First runs corresponding `Operation` in generated register_aten_ops_xxx.cpp, which calls `at::` functions, then calls ATen dispatcher.
    b.2 ATen dispatcher dispatches to corresponding VariableType methods.
    b.3 VariableType method uses `AutoNonVariableTypeMode` guard before calling into ATen implementation, as ATen generally expects `CHECK(!is_variable())`.
    b.4 VariableType method uses `as_variable` to wrap the results.

  x. Somewhere in JIT it expects `CHECK(is_variable())` - not sure before/after S1.a / S1.b.

S2. module::forward()
  a. JIT interpreter calls some ATen methods (via JIT registry).
    a.1 - a.4: same as S1.b.1 - S1.b.4.

  x. Different from S1.x, seems JIT doesn't expect `CHECK(is_variable())` during the entire `forward()` call.
```

- Current flow with USE_STATIC_DISPATCH (for mobile build):
```
M1. jit::load()
  a. JIT calls variable_factories.h methods to instantiate variable instances.

  b. JIT calls some ATen methods during intitalization, e.g.: conv_prepack, q_scale.
    b.1 First runs corresponding `Operation` in generated register_aten_ops_xxx.cpp, which calls `at::` functions, then calls ATen dispatcher.
    b.2 ATen dispatcher dispatches to corresponding ATen implementation directly.
      // Issue 1: NO VariableType methods / `AutoNonVariableTypeMode` so `CHECK(!is_variable())` in ATen will fail!
      // (Hypothetical) Issue 2: NO `as_variable()` to wrap result as variable. M1.x will fail if is ever used to check this result.

  x. Somewhere in JIT it expects `CHECK(is_variable())` - not sure before/after M1.a / M1.b.

M2. module::forward() // PR #26477 wraps this call with `AutoNonVariableTypeMode` guard.
  a. JIT interpreter calls some ATen methods (via JIT registry).
    a.1 same as M1.b.1, calls into register_aten_ops_xxx.cpp.
    a.2 same as M1.b.2, calls ATen implementation directly.
      // `CHECK(!is_variable())` in ATen won't fail thanks to the outer scope `AutoNonVariableTypeMode` guard.

  x. Same as above, seems JIT never expects `CHECK(is_variable())` during the entire `forward()` call.
```

- Wrong solution: if we wrap M1 with `AutoNonVariableTypeMode`, it will solve `Issue 1` for some models but will fail M1.x for some other models.

- Proposed solution:
I feel the root cause is that mobile build doesn't have `VariableType` as a barrier sitting between JIT and ATen to convert between is_variable() and !is_variable().

Without `VariableType` the best alternative place to put a barrier is M1.b.2 as Edward did in #26908.

For some reason we also need toggle variable state for c10 ops: this is what this PR does. We haven't figured how non-mobile build works without this logic so it's kinda bandaid for now.

This PR doesn't try to address (Hypothetical) Issue 2 as I haven't seen it. PR #26477 can be replaced by #26908 + this PR but we can keep it until M2.x is no longer true.

- Ultimate solution:
After Variable and Tensor are completely merged: #23032 then is_variable() checks can be changed to requires_grad() checks and all problems will be solved. We can clean up these hacks by then.

- References:
* Effect of `AutoNonVariableTypeMode`: all `is_variable()` inside current thread scope returns false:
  https://github.com/pytorch/pytorch/blob/master/c10/core/TensorImpl.h#L811

* Effect of `as_variable`: https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/VariableTypeUtils.h#L159
  It calls `make_variable`: https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/variable.h#L539

Test Plan:
- Patch PR #26908 then load and run MobileNetV2 fp32 & int8 models.

Differential Revision: [D17595179](https://our.internmc.facebook.com/intern/diff/D17595179)

### CODE REVIEW

**Comment by ezyang** [comment]
Thank you for the detailed writeup. I'm studying it right now.

**Comment by ezyang** [comment]
OK, so here is my analysis:

Ordinarily, the call stack of an operation looks something like this:

1. Call `Tensor::conv_prepack` on an variable, cpu tensor (nograd mode is OFF)
2. Dispatch to `VariableType::conv_prepack`. Set nograd mode ON
3. Call `Tensor::conv_prepack` on same
4. Dispatch to `CPUTensorType::conv_prepack` (as nograd mode prevents variable from being selected)
5. Assert `!is_variable`

In the static dispatch world, we have somehow have generated a tensor that is a variable. Then the call stack looks like:

1. Call `Tensor::conv_prepack` on a variable, cpu tensor (nograd mode is OFF).
2. Dispatch to `CPUTensorType::conv_prepack`, because that's literally what the IF statement says to do
3. Fail the assert `!is_variable`

I cannot recall if the plan on record was, in mobile, for everything to be a variable (with nograd mode ON all the time), or for everything to NOT be a variable. But my recollection is that, because you are toggling nograd mode, I think everything is a variable.

So I think the correct fix is to inline a "miniature" Variable implementation inside the static dispatch implementation. What it does is turn nograd mode ON before calling CPUTensorType. That will appease the assert; while JIT still gets to assume that variables rule everything around me.

**Comment by ljk53** [comment]
Yes, the key difference is in non-static world there is VariableType method for each op that sets NoVariable mode ON before calling aten implementation and converts tensor result back to variable after calling.

> In the static dispatch world, we have somehow have generated a tensor that is a variable.
I think we want to generate everything as variable and toggling *NoVariable* mode to workaround !is_variable() check in ATen. We discussed about generate everything as tensor in mobile, but decided it will create more trouble according to past experience, cc: @gchanan @yf225 

> I cannot recall if the plan on record was, in mobile, for everything to be a variable (with nograd mode ON all the time), or for everything to NOT be a variable. But my recollection is that, because you are toggling nograd mode, I think everything is a variable.
Yes, everything is a variable. We are toggling NoVariable mode instead of NoGrad (which is also needed though).

> So I think the correct fix is to inline a "miniature" Variable implementation inside the static dispatch implementation. What it does is turn nograd mode ON before calling CPUTensorType. That will appease the assert; while JIT still gets to assume that variables rule everything around me.
This is pretty much what I want to do in this PR, except I'm not sure about "inline a "miniature" Variable implementation inside the static dispatch implementation" part. Do you propose adding NoVariable mode to CPUType / TypeDefault? I'm currently adding it to JIT->ATen layer, which is right above CPUType/TypeDefault.

**Comment by ezyang** [comment]
I think putting it in the static dispatch code will be more robust. https://github.com/pytorch/pytorch/pull/26908 attempts to do it this way.

**Comment by ljk53** [comment]
> I think putting it in the static dispatch code will be more robust. #26908 attempts to do it this way.

Sure, let me test it.

**Comment by ljk53** [comment]
> I think putting it in the static dispatch code will be more robust. #26908 attempts to do it this way.

@ezyang I think there is one more issue - conv_prepack is registered with c10 dispatcher which doesn't seem to be covered by static_dispatcher codepath yet. I need discuss with @smessmer about how to achieve static_dispatch purpose when we migrate to c10 op registration but right now only quantization ops are registered this way.

The register_c10_ops.cpp change on this PR will cover this case on JIT->c10 path.

**Comment by ljk53** [comment]
Looks like the root cause is about how qnnpack_conv_prepack calls TensorFactories:
It fails AT_ASSERT(!options.is_variable()) in empty_cpu():
```
#0  0x0000000000657f3e in at::native::empty_cpu(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) ()
#1  0x00000000007252df in at::CPUType::empty(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) ()
#2  0x00000000006fde6d in at::Tensor at::cpp_custom_type_hack::create<PackedConvWeightsQnnp>(std::unique_ptr<PackedConvWeightsQnnp, std::default_delete<PackedConvWeightsQnnp> >, c10::TensorOptions) ()
#3  0x00000000006fc9e6 in at::native::(anonymous namespace)::QConvPackWeightInt8::qnnpack_conv_prepack(at::Tensor, c10::optional<at::Tensor>, c10::List<long>, c10::List<long>, c10::List<long>, long) [clone .isra.298] ()
#4  0x00000000006fd38e in at::native::(anonymous namespace)::QConvPackWeightInt8::operator()(at::Tensor, c10::optional<at::Tensor>, c10::List<long>, c10::List<long>, c10::List<long>, long) [clone .isra.299] ()
#5  0x00000000006fd6c9 in c10::detail::wrap_kernel_functor_boxed<at::native::(anonymous namespace)::QConvPackWeightInt8, false, void>::call(c10::OperatorKernel*, std::vector<c10::IValue, std::allocator<c10::IValue> >*) ()
#6  0x00000000010e3a81 in std::result_of<c10::impl::OperatorEntry::callBoxed(std::vector<c10::IValue, std::allocator<c10::IValue> >*) const::{lambda(c10::DispatchTable const&)#1} (c10::DispatchTable const&)>::type c10::LeftRight<c10::DispatchTable>::read<c10::impl::OperatorEntry::callBoxed(std::vector<c10::IValue, std::allocator<c10::IValue> >*) const::{lambda(c10::DispatchTable const&)#1}>(std::result_of&&) const ()
#7  0x00000000010e187f in torch::jit::(anonymous namespace)::createOperatorFromC10(c10::OperatorHandle const&)::{lambda(std::vector<c10::IValue, std::allocator<c10::IValue> >&)#1}::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >&) const ()
#8  0x00000000010ba2d8 in torch::jit::InterpreterStateImpl::runImpl(std::vector<c10::IValue, std::allocator<c10::IValue> >&) ()
```

Use NoVariable guard on register_c10_ops.cpp path simply "hide" the problem because the entire execution scope is guarded. We need think of a more bulletproof approach if we prefer gating from ATen side instead of from JIT-op-registry side. Looks like TensorFactories callsites within ATen need some audit.

**Comment by ezyang** [comment]
`at::cpp_custom_type_hack:` What the heck!

I can believe that quantized is doing something naughty. But I am not sure what. I'll have to do some code reading.

> I think there is one more issue - conv_prepack is registered with c10 dispatcher which doesn't seem to be covered by static_dispatcher codepath yet. I need discuss with @smessmer about how to achieve static_dispatch purpose when we migrate to c10 op registration but right now only quantization ops are registered this way.

I think the easiest and most expedient thing to do is move the registration to `native_functions.yaml`.

**Comment by ezyang** [comment]
Fixed some of the naughtiness in #26966

**Review by ezyang — APPROVED** [review]
Approving to unblock. I think `gen_jit_dispatch` changes will get reverted but since branch cut is today, let's get you guys going.

The JIT changes are morally wrong because they will only fix the problem on the JIT side; if someone uses C++ API from mobile, you will end up with the same problem. Fortunately, that's not the case that needs unblocking here.

**Comment by ljk53** [comment]
> Approving to unblock. I think `gen_jit_dispatch` changes will get reverted but since branch cut is today, let's get you guys going.

Thanks, reverted gen_jit_dispatch change from this PR to wait for #26908 to fix it properly.

**Comment by ljk53** [comment]
Landed to master, closing.

**Pull request closed without merging**
