### PR TITLE
Canonicalize all includes in PyTorch.

### PR DESCRIPTION
**Pull request by ezyang**
Anywhere we used #include "foo.h", we now say #include <foo.h>
Paths are adjusted to be rooted out of aten/src, torch/lib, or
the root level directory.

I modified CMakeLists.txt by hand to remove TH and THC from
the include paths.

I used the following script to do the canonicalization:

```
  import subprocess
  import re
  import os.path

  files = subprocess.check_output(['git', 'ls-files']).decode('utf-8').rstrip().split('\n')
  for fn in files:
      if not any(fn.endswith(suff) for suff in ['.cu', '.cpp', '.in', '.h', '.hpp', '.cu', '.cuh', '.cc']):
          continue
      if not any(fn.startswith(pref) for pref in ["aten/", "torch/"]):
          continue
      with open(fn, 'r') as f:
          c = f.read()
      def fmt(p):
          return "#include <{}>".format(p)
      def repl(m):
          p = m.group(1)
          if p in ["dlfcn.h", "unistd.h", "nvrtc.h", "cuda.h", "cuda_runtime.h", "cstdint", "cudnn.h", "Python.h", "cusparse.h", "cuda_runtime_api.h", "cuda_fp16.h", "cublas_v2.h", "stdint.h", "curand_kernel.h"]:
              return fmt(p)
          if any(p.startswith(pref) for pref in ["torch/csrc", "c10/", "ATen/", "caffe2/", "TH/", "THC/", "Eigen/", "gtest/", "zdl/", "gloo/", "onnx/", "miopen/"]):
              return fmt(p)
          for root in ["aten/src", "torch/lib", ""]:
              for bad_root in [os.path.dirname(fn), "aten/src/TH", "aten/src/THC", "torch/csrc"]:
                  new_p = os.path.relpath(os.path.join(bad_root, p), root)
                  if not new_p.startswith("../") and (os.path.exists(os.path.join(root, new_p)) or os.path.exists(os.path.join(root, new_p + ".in"))):
                      return fmt(new_p)
          print("ERROR: ", fn, p)
          return m.group(0)
      new_c = re.sub(r'#include "([^"]+)"', repl, c)
      if new_c != c:
          print(fn)
          with open(fn, 'w') as f:
              f.write(new_c)
```

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
Manual fixups I had to do on top of the script:

* There were some angled bracket includes that assumed that `#include <TH.h>` was a thing
* `TH_GENERIC_FILE` macro definitions count as file paths
* Quite a bit more cmake tweaking

**Comment by ezyang** [comment]
Why should we do this?

1. Under certain situations, MSVC resolves `#include "foo.h"` and `#include <foo.h>` to different headers, which leads to really strange errors. Canonicalizing on angled brackets prevents this confusion from occurring.
2. HIPify needs to rewrite headers; it is easier to write the HIPify script if all includes are in a standardized format, as opposed to some includes being relative while others being absolute.

**Review by li-roy — COMMENTED** [review]
@ezyang If HIPify is making these assumptions, does that mean that not following this format will be land blocking in the future?

**Review by bddppq — APPROVED** [review]
This is great!

**Comment by ezyang** [comment]
@li-roy Yes.

**Comment by bddppq** [comment]
@li-roy nope, only in the files ghat hipify touch and only if that include (e.g. .cuh) has been hipified

**Comment by bddppq** [comment]
@li-roy @ezyang I think it will fail only if the include is in the files that hipify touches and that include (e.g. .cuh) has been hipified

**Comment by bddppq** [comment]
@li-roy @ezyang I think it will fail only if the include is in the files that hipify touches and that include (e.g. .cuh) has been hipified

**Comment by ezyang** [comment]
@goldsborough This diff picked up more files which are not clang-tidy clean. In the interests of keeping this PR clean I will not fix them. Failing clang-tidy run: https://travis-ci.org/pytorch/pytorch/jobs/464438532

**Comment by ezyang** [comment]
@goldsborough This diff picked up more files which are not clang-tidy clean. In the interests of keeping this PR clean I will not fix them. Failing clang-tidy run: https://travis-ci.org/pytorch/pytorch/jobs/464438532

**Comment by bddppq** [comment]
@li-roy @ezyang I think it will fail only if the include is in the files that hipify touches and that include (e.g. .cuh) has been hipified

**Pull request closed without merging**
