### PR TITLE
[quant] Remove deprecated torch.jit.quantized APIs

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #104569
* #72303
* #112153
* __->__ #118406

The `torch.jit.quantized` interface has been deprecated since #40102 (June 2020).

BC-breaking message:

All functions and classes under `torch.jit.quantized` will now raise an error if
called/instantiated. This API has long been deprecated in favor of
`torch.ao.nn.quantized`.

cc @ezyang @gchanan

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]

**Review by jerryzh168 — COMMENTED** [review]
will you remove these python APIs in the future as well?

**Comment by peterbell10** [comment]
I think it's good to leave the APIs as a hard error with informative error message for at least one release, after that we can remove completely.

**Pull request closed without merging**
