### PR TITLE
remove aliasMultinomial decode from TH and THC

### PR DESCRIPTION
**Pull request by XiaobingSuper**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#52585 remove aliasMultinomial decode from TH and THC**
* #52546 remove th_fill and th_mul dead code

Differential Revision: [D26654125](https://our.internmc.facebook.com/intern/diff/D26654125)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
More code removal!

**Comment by XiaobingSuper** [comment]
@albanD, could you help landing it? thanks!

**Comment by albanD** [comment]
Ho sorry, I wrongfully assumed that because you used ghstack you were a fb employe!
working on the land now!

**Comment by albanD** [comment]
There are some internal build files that I am not very familiar with that need to be updated. So it is gonna take a few days of trial and error for me to fix that. And then I'll land!

**Pull request closed without merging**
