### PR TITLE
Remove sync in embedding

### PR DESCRIPTION
**Pull request by zasdfgbnm**
This together with https://github.com/pytorch/pytorch/pull/66580 and https://github.com/pytorch/pytorch/pull/68376 will remove all syncs in embedding.

This PR includes https://github.com/pytorch/pytorch/pull/68376, please review after merging https://github.com/pytorch/pytorch/pull/68376

This PR introduces perf regressions and increases memory usage: 
- `exclusive_sum` is now computing the entire `numel` elements instead of `num_of_segments` elements, and the trailing `numel - num_of_segments` results will be discarded.
- Some memory allocation now needs `numel` spaces instead of `num_of_segments` or `num_of_partial_segments`.

These are the prices we must pay in order to get a sync-free implementation.

I haven't done any benchmark yet. I will do it later.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Benchmarked at https://github.com/zasdfgbnm/things/blob/master/2022/embedding-benchmark.ipynb, this PR is improving the performance compared to master:
```
# master (fcb7e528d986fb4df148a43959cd25fe3cfa5842)
36.5 ms ± 38.3 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
19 ms ± 225 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
18 ms ± 538 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

# this PR (4214bd808e136baec1e6aad7c16f975772370aca)
33.9 ms ± 19.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
13.4 ms ± 1.95 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
11.1 ms ± 31.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
code:
```python
import torch

embedding1 = torch.nn.Embedding(28996, 768, padding_idx=0, device='cuda')
embedding2 = torch.nn.Embedding(512, 768, device='cuda')
embedding3 = torch.nn.Embedding(2, 768, device='cuda')

input1 = torch.randint(embedding1.num_embeddings, (32, 128), dtype=torch.long, device='cuda')
input2 = torch.randint(embedding2.num_embeddings, (32, 128), dtype=torch.long, device='cuda')
input3 = torch.randint(embedding3.num_embeddings, (32, 128), dtype=torch.long, device='cuda')

for _ in range(100):
    torch.arange(1000000, device='cuda')
    
def run50sync(f):
    for _ in range(50):
        f()
    torch.cuda.synchronize()

def benchmark():
    torch.cuda.synchronize()
    %timeit run50sync(lambda: embedding1(input1).sum().backward())
    torch.cuda.synchronize()
    %timeit run50sync(lambda: embedding2(input2).sum().backward())
    torch.cuda.synchronize()
    %timeit run50sync(lambda: embedding3(input3).sum().backward())
```

shapes are extracted from huggingface bert example https://github.com/huggingface/transformers/tree/master/examples/pytorch/text-classification
```
python run_glue.py \
  --model_name_or_path bert-base-cased \
  --dataset_name imdb  \
  --do_train \
  --do_predict \
  --max_seq_length 128 \
  --per_device_train_batch_size 32 \
  --learning_rate 2e-5 \
  --num_train_epochs 3 \
  --output_dir /tmp/imdb/
```

**Comment by zasdfgbnm** [comment]
Marking as ready for review

**Comment by zasdfgbnm** [comment]
Rebased and should be ready for review.

**Comment by ngimel** [comment]
So there's no perf regression, but still memory regression?

**Comment by zasdfgbnm** [comment]
@ngimel You are right. There is memory regression. For speed, I am comparing `cub::DeviceSelect::UniqueByKey + this PR` vs `thrust::unique_by_key without this PR` and the former is faster.

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
