### PR TITLE
Replace DCHECK_EQ -> TORCH_DCHECK_EQ

### LINKED ISSUE #81415: `CHECK_*` macro signatures break downstream pytorch/xla build
### 🐛 Describe the bug

Tensorflow recently upgraded to C++17. PyTorch/XLA is upgrading its TF pin and by extension building its TF dependency with C++17. PyTorch/XLA continues to build its own source code in C++14 to stay consistent with the upstream PyTorch.

It turns out the compiler confuses this [definition](https://github.com/tensorflow/tensorflow/blame/master/tensorflow/core/platform/default/logging.h#L456) of `CHECK_NE` in Tensorflow with that of PyTorch in [c10/util/logging_is_not_google_glog.h](https://github.com/pytorch/pytorch/blob/master/c10/util/logging_is_not_google_glog.h#L139-L145). This leads to the following error. This issue occurs because it is not possible to place macros in a namespace. I get similar errors for `DCHECK_NE`, `CHECK_EQ`, etc. 

```
/sw/pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/service/hlo_module.h: In member function ‘const xla::Shape& xla::HloModule::result_shape() const’:
/sw/pytorch/c10/util/logging_is_not_google_glog.h:141:30: error: ambiguous overload for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘std::nullptr_t’)
  141 |                              << (val1) << " vs. " << (val2) << ") "
      |                              ^
/sw/pytorch/c10/util/logging_is_not_google_glog.h:141:30: note: in definition of macro ‘CHECK_OP’
  141 |                              << (val1) << " vs. " << (val2) << ") "
      |                              ^~
/usr/local/<redact>/sw/pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/service/hlo_module.h:137:5: note: in expansion of macro ‘CHECK_NE’
  137 |     CHECK_NE(nullptr, entry_computation_);
      |     ^~~~~~~~
In file included from /usr/include/c++/11/iostream:39,
                 from /usr/local/google/home/miladmo/sw/pytorch/xla/torch_xla/csrc/debug_util.h:3,
                 from /usr/local/google/home/miladmo/sw/pytorch/xla/torch_xla/csrc/debug_util.cpp:1:
```

To check if the issue partially resolves by changing the `CHECK_*` macro names, I commented out CHECK_NE (only) and renamed CHECK_OP to CHECK_OPS in PyTorch. This was possible because `CHECK_NE` is not used in PT source code. I am happy to see CHECK_NE errors disappear.

**Request**

Previously, this name collision has been a compiler warning in PyTorch/XLA. Now, with the change in C++ compiler version, this has become a blocking error. At the same time, FWIW, I understand [PT migration to C++17](https://github.com/pytorch/pytorch/issues/56055) is not in the immediate term horizon. 

I'd propose to rename these macros to resolve the macro names collision. Wdyt?

CC @wconstab @ezyang @JackCaoG 

### Versions

Collecting environment information...
PyTorch version: 1.12.0a0+git6e292f1
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux rodete (x86_64)
GCC version: (Debian 11.3.0-3) 11.3.0
Clang version: 13.0.1-4
CMake version: version 3.19.6
Libc version: glibc-2.33

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.17.11-1rodete2-amd64-x86_64-with-glibc2.33
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] numpydoc==1.1.0
[pip3] torch==1.12.0a0+gitde18c28
[pip3] torch-xla==1.12
[pip3] torchvision==0.13.0a0+08cc9a7
[conda] blas                      1.0                         mkl
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-include               2022.0.1           h06a4308_117
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.20.3           py39hf144106_0
[conda] numpy-base                1.20.3           py39h74d4b33_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] torch                     1.12.0a0+gitcaa1177          pypi_0    pypi
[conda] torch-xla                 1.12                     pypi_0    pypi
[conda] torchvision               0.13.0a0+08cc9a7          pypi_0    pypi

cc @bdhirsh

### PR DESCRIPTION
**Pull request by wconstab**
WIP: this only changes DCHECK_EQ, but all similar macros would need to be updated.
Using CI to spot-check if this change is even valid and also whether it helps XLA CI issues.

cd {pytorch root}

find aten c10 torch -type f -exec sed -i 's/DCHECK_EQ/TORCH_DCHECK_EQ/g' {} \;

Fixes #81415

cc @miladm @malfet @ezyang

### CODE REVIEW

**Comment by malfet** [comment]
Please don't commit it like that (without changing macros on c10_use_glog.h side)

**Comment by wconstab** [comment]
> Please don't commit it like that (without changing macros on c10_use_glog.h side)

don't worry i won't rush to commit this.

but i don't see `c10_use_glog.h` in internal or oss repo.  i think i changed every location in the OSS side in this PR, but I did forget to consider internal.

**Comment by wconstab** [comment]
my local build actually fails for this PR, but CI is not failing as aggressively.  I guess it may be a difference in one of us using or not using glog.  @malfet any ideas on whether this approach is close or if we should take a different approach?

```
[10/6780] Building CXX object third_party/protobuf/cmak...tobuf-lite.dir/__/src/google/protobuf/message_lite.cc.o
FAILED: third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/message_lite.cc.o      
/data/shared/bin/ccache /data/shared/bin/c++ -DGOOGLE_PROTOBUF_CMAKE_BUILD -DHAVE_PTHREAD -I/scratch/whc/work/pyt
orch/build/third_party/protobuf/cmake -I/scratch/whc/work/pytorch/third_party/protobuf/src -fvisibility-inlines-h
idden -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -fPIC -std=c++11 -MD -MT third_party/protobuf/
cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/message_lite.cc.o -MF third_party/protobuf/cmake/CMa
keFiles/libprotobuf-lite.dir/__/src/google/protobuf/message_lite.cc.o.d -o third_party/protobuf/cmake/CMakeFiles/
libprotobuf-lite.dir/__/src/google/protobuf/message_lite.cc.o -c /scratch/whc/work/pytorch/third_party/protobuf/s
rc/google/protobuf/message_lite.cc                                                                               
In file included from /scratch/whc/work/pytorch/third_party/protobuf/src/google/protobuf/generated_message_table_
driven.h:34:0,                                                                                                   
                 from /scratch/whc/work/pytorch/third_party/protobuf/src/google/protobuf/message_lite.cc:51:     
/scratch/whc/work/pytorch/third_party/protobuf/src/google/protobuf/map.h: In constructor ‘google::protobuf::Map<K
ey, T>::InnerMap::iterator_base<KeyValueType>::iterator_base(google::protobuf::Map<Key, T>::InnerMap::TreeIterato
r, const google::protobuf::Map<Key, T>::InnerMap*, google::protobuf::Map<Key, T>::size_type)’:                   
/scratch/whc/work/pytorch/third_party/protobuf/src/google/protobuf/map.h:469:9: error: there are no arguments to 
‘GOOGLE_TORCH_DCHECK_EQ’ that depend on a template parameter, so a declaration of ‘GOOGLE_TORCH_DCHECK_EQ’ must b
e available [-fpermissive]                                                                                       
         GOOGLE_TORCH_DCHECK_EQ(bucket_index_ % 2, 0u);
         ```

**Comment by wconstab** [comment]
collecting CI errors..
./caffe2/utils/math-detail.h(33): error: identifier "TORCH_DCHECK_EQ" is undefined

**Review by miladm — APPROVED** [review]

**Comment by miladm** [comment]
@wconstab I expect we don't plan on merging this PR; right?

**Comment by wconstab** [comment]
Correct, this is abandoned in favor of https://github.com/pytorch/pytorch/pull/82032.  Closing it now, thanks for the reminder.

**Pull request closed without merging**
