### PR TITLE
Revert "[dynamo] Cache size calc for differing config (#111300)"

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #115386
* __->__ #115385
* #115401
* #115384

This reverts commit 78318d024989cf86e1ede424997cd42d2d291694.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

Differential Revision: [D51959268](https://our.internmc.facebook.com/intern/diff/D51959268)

### CODE REVIEW

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51959268).

**Review by malfet — APPROVED** [review]

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51959268).

**Comment by davidberard98** [comment]
I’ll take a look in a few hours

**Comment by davidberard98** [comment]
I’ll take a look in a few hours

**Pull request closed without merging**
