### PR TITLE
[quant] adding const qualifier to Quantizer::equalTo

### PR DESCRIPTION
**Pull request by terrychenism**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #75355

Summary:
fix issue #74538 Quantizer::equalTo missing const qualifier
Equality test should be const.

Test Plan:
All CI tests passed

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D35444203](https://our.internmc.facebook.com/intern/diff/D35444203)

### CODE REVIEW

**Comment by terrychenism** [comment]
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35444203).

**Comment by vkuzo** [comment]
the code makes sense.  Could you fill out the test plan?  Also, looks like there are some CI errors.
 
Thanks for working on this.

**Comment by terrychenism** [comment]
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35444203).

**Comment by terrychenism** [comment]
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35444203).

**Comment by vkuzo** [comment]
the test plan is still blank, please fill it out so we can accept the PR

**Comment by terrychenism** [comment]
> the test plan is still blank, please fill it out so we can accept the PR

just wait for the CI test finish, now it's filled.

**Review by vkuzo — APPROVED** [review]
thanks for working on this!

**Pull request closed without merging**
