### PR TITLE
[Sparsity] add support for H100 compute capability 9.x

### PR DESCRIPTION
**Pull request by pls331**
Summary: as title

Test Plan: buck test mode/opt //caffe2/test/...

Differential Revision: D54792168

@diff-train-skip-merge

### CODE REVIEW

**Review by SherlockNoMad — APPROVED** [review]

**Comment by huydhn** [comment]
@pls331 I think this change is failing on ROCm https://hud.pytorch.org/pytorch/pytorch/commit/821ad56ea666099c7374914d6f42a6bd757823b8 with the following error

```
2024-03-20T21:04:25.5971346Z     PYTORCH_TEST_WITH_ROCM=1 python test_sparse_semi_structured.py -k test_mlp_contiguous_relu_compile_cutlass
2024-03-20T21:04:25.5971826Z 
2024-03-20T21:04:25.5972141Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-03-20T21:04:25.5972739Z ----------------------------- Captured stderr call -----------------------------
2024-03-20T21:04:25.5974583Z /opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/sparse/semi_structured.py:111: UserWarning: The PyTorch API of SparseSemiStructuredTensor is in prototype stage and will change in the near future. Please open a Github issue for features requests and see our documentation on the torch.sparse module for further information about the project.
2024-03-20T21:04:25.5976162Z   warnings.warn(
2024-03-20T21:04:25.5977423Z /opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/sparse/semi_structured.py:439: UserWarning: Unsupported unwinding pattern: Address not in range (Triggered internally at /var/lib/jenkins/workspace/torch/csrc/profiler/unwind/unwind.cpp:203.)
2024-03-20T21:04:25.5978611Z   res = torch._sparse_semi_structured_linear(
2024-03-20T21:04:25.5978998Z =================================== FAILURES ===================================
2024-03-20T21:04:25.5979567Z _ SparseSemiStructuredTensorCompileTest.test_mlp_contiguous_relu_compile_cutlass _
2024-03-20T21:04:25.5980077Z Traceback (most recent call last):
2024-03-20T21:04:25.5980588Z   File "test_sparse_semi_structured.py", line 216, in test_mlp_contiguous_relu_compile_cutlass
2024-03-20T21:04:25.5981353Z     SparseSemiStructuredTensorCompileTest._test_mlp_contiguous_relu_compile("cutlass", dense_input_shape)
2024-03-20T21:04:25.5982086Z   File "test_sparse_semi_structured.py", line 187, in _test_mlp_contiguous_relu_compile
2024-03-20T21:04:25.5982569Z     sparse_result = model(input)
2024-03-20T21:04:25.5983291Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
2024-03-20T21:04:25.5999341Z     return self._call_impl(*args, **kwargs)
2024-03-20T21:04:25.6000282Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
2024-03-20T21:04:25.6000974Z     return forward_call(*args, **kwargs)
2024-03-20T21:04:25.6001576Z   File "test_sparse_semi_structured.py", line 171, in forward
2024-03-20T21:04:25.6002009Z     x = self.linear(x)
2024-03-20T21:04:25.6002747Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
2024-03-20T21:04:25.6003458Z     return self._call_impl(*args, **kwargs)
2024-03-20T21:04:25.6004200Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
2024-03-20T21:04:25.6004857Z     return forward_call(*args, **kwargs)
2024-03-20T21:04:25.6005559Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 116, in forward
2024-03-20T21:04:25.6006240Z     return F.linear(input, self.weight, self.bias)
2024-03-20T21:04:25.6007093Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/sparse/semi_structured.py", line 199, in __torch_dispatch__
2024-03-20T21:04:25.6007981Z     return cls.SPARSE_DISPATCH[func._overloadpacket](func, types, args, kwargs)
2024-03-20T21:04:25.6008953Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/sparse/_semi_structured_ops.py", line 145, in semi_sparse_addmm
2024-03-20T21:04:25.6009742Z     result = B_t._mm(A_padded.t(), bias=bias).t()
2024-03-20T21:04:25.6010442Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/sparse/semi_structured.py", line 439, in _mm
2024-03-20T21:04:25.6011066Z     res = torch._sparse_semi_structured_linear(
2024-03-20T21:04:25.6011515Z RuntimeError: _sparse_semi_structured_linear: CUTLASS not supported
```

Could you help take a look?  Maybe the test need to XFAIL there on ROCm?

**Comment by huydhn** [comment]
I'll temporarily disable the test on ROCm in the meantime https://github.com/pytorch/pytorch/issues/122352

**Comment by huydhn** [comment]
The disable test route is not gonna fly in this case because there are many of them failing in the same way.  @pls331 Please let me know if you prefer to revert and reland the change.

**Comment by jeffdaily** [comment]
I agree, I just blindly disabled yet another one https://github.com/pytorch/pytorch/issues/122384.  It'll be best to revert, add rocm skips as-needed (or fix rocm), and reland.  Add label ciflow/rocm to get a nearly-complete rocm signal before relanding.

**Comment by jeanschmidt** [comment]
thanks @jeffdaily to take the time to investigate it :)

**Pull request closed without merging**
