### PR TITLE
ignore sccache server error

### PR DESCRIPTION
**Pull request by mszhanyi**
Fixes #ISSUE_NUMBER

example link:
https://github.com/pytorch/pytorch/runs/5076575358?check_suite_focus=true

```
error: failed to execute compile
caused by: error reading compile response from server
caused by: Failed to read response header
caused by: failed to fill whole buffer
ninja: build stopped: subcommand failed.
```

### CODE REVIEW

**Comment by mszhanyi** [comment]
@seemethere @janeyx99 
I'm trying to fix the intermittent sccache server issue. (https://github.com/mozilla/sccache/pull/1090)
But there's a wizard thing that the sccache binaries I uploaded, e.g. , sccache-20220208.exe couldn't be downloaded by `aws sc cp` but it works with curl. 
Is there any suggestion?
I tried uploading it with UI and command, neither worked.

**Comment by janeyx99** [comment]
> But there's a wizard thing that the sccache binaries I uploaded, e.g. , sccache-20220208.exe couldn't be downloaded by `aws sc cp` but it works with curl. Is there any suggestion? I tried uploading it with UI and command, neither worked.

What's the error message?

**Comment by mszhanyi** [comment]
> > But there's a wizard thing that the sccache binaries I uploaded, e.g. , sccache-20220208.exe couldn't be downloaded by `aws sc cp` but it works with curl. Is there any suggestion? I tried uploading it with UI and command, neither worked.
> 
> What's the error message?


`fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden`

```
C:\actions-runner\_work\pytorch\pytorch>C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\bin\sccache.exe --show-stats   || (
taskkill /im sccache.exe /f /t   || ver  1>nul  
 del C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\bin\sccache.exe   || ver  1>nul  
 del C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\bin\sccache-cl.exe   || ver  1>nul  
 if "win-vs2019-cpu-py3" == "" (
curl --retry 3 -k https://s3.amazonaws.com/ossci-windows/sccache-20220208.exe --output C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\bin\sccache.exe  
 curl --retry 3 -k https://s3.amazonaws.com/ossci-windows/sccache-cl.exe --output C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\bin\sccache-cl.exe 
)  else (
aws s3 cp s3://ossci-windows/sccache-20220208.exe C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\bin\sccache.exe  
 aws s3 cp s3://ossci-windows/sccache-cl.exe C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\bin\sccache-cl.exe 
)  
 goto :check_sccache 
'C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\bin\sccache.exe' is not recognized as an internal or external command,
operable program or batch file.
) 
ERROR: The process "sccache.exe" not found.
Could Not Find C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\bin\sccache.exe
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
Completed 25.0 KiB/25.0 KiB (438.5 KiB/s) with 1 file(s) remaining
download: s3://ossci-windows/sccache-cl.exe to build\win_tmp\bin\sccache-cl.exe
```

https://github.com/pytorch/pytorch/runs/5110655369?check_suite_focus=true

**Comment by janeyx99** [comment]
Ah, let me test out a fix that would add the appropriate IAM policy for the ossci-windows bucket. I'll let you know when I've applied the change

**Comment by janeyx99** [comment]
Actually, further investigation at the latest PR CI implies that the ossci-windows bucket permissions should be fine. Could you try making the object public?
image

**Comment by mszhanyi** [comment]
That's strange. It's already public. If it wasn't public, it couldn't have been downloaded by curl.

**Comment by janeyx99** [comment]
I downloaded and reuploaded as sccache-20220211.exe

**Comment by mszhanyi** [comment]
> I downloaded and reuploaded as sccache-20220211.exe

You uploaded works.

**Comment by peterjc123** [comment]
@mszhanyi You may have to rebuild the `sccache-cl.exe` binary using `https://github.com/chocolatey/shimgen`.

**Comment by mszhanyi** [comment]
> @mszhanyi You may have to rebuild the `sccache-cl.exe` binary using `https://github.com/chocolatey/shimgen`.

It's a little strange why it worked in this test PR.

**Comment by peterjc123** [comment]
> > @mszhanyi You may have to rebuild the `sccache-cl.exe` binary using `https://github.com/chocolatey/shimgen`.
> 
> It's a little strange why it worked in this test PR.

Or maybe the downloaded `sccache-cl.exe` is corrupted. I'm not sure. Actually, I have never encountered this problem before.

**Pull request closed without merging**
