### PR TITLE
Test TORCH_LIBRARY in CUDA extension

### PR DESCRIPTION
**Pull request by zasdfgbnm**
In the [official documentation](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html), it is recommended to use `TORCH_LIBRARY` to register ops for TorchScript. However, that code is never tested with CUDA extension and is actually broken (https://github.com/pytorch/pytorch/issues/47493). This PR adds a test for it. It will not pass CI now, but it will pass when the issue https://github.com/pytorch/pytorch/issues/47493 is fixed.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Looks like `nvcc` on Windows need to have more things fixed.

**Comment by zasdfgbnm** [comment]
I have to skip this test on Windows for now. Looks like the root cause is MSVC 2017 implementation of `vector::erase` is buggy and uses `operator=` where it shouldn't be using.

**Comment by ezyang** [comment]
> Looks like the root cause is MSVC 2017 implementation of vector::erase is buggy and uses operator= where it shouldn't be using.

Ick. This is in our library code? Surprising that the entire build isn't failing here. Well, seems reasonable enough. Can you file a bug for this?

**Review by ezyang — APPROVED** [review]

**Comment by zasdfgbnm** [comment]
@ezyang I think it is because nvcc uses MSVC's implementation of STL, and if you use `TORCH_LIBRARY` in a `.cu`, then you will see some issue. We are not currently using `TORCH_LIBRARY` in a `.cu` file, so we are not seeing an issue right now.

Let me check if this is still an issue with latest nvcc + MSVC, if it is still an issue, I will open an issue for it.

**Comment by zasdfgbnm** [comment]
@ezyang Looks like this issue has been fixed in CUDA 11.0:
https://github.com/pytorch/pytorch/pull/48025

**Comment by peterjc123** [comment]
@zasdfgbnm But it is still failing for CUDA < 11, right? Next time please open an issue for that since CUDA < 11 is still in use for our release builds.

**Pull request closed without merging**
