### PR TITLE
`maximum` and `minimum`: port to structured

### PR DESCRIPTION
**Pull request by Freey0**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#57630 Port maximum and minimum to structured**
* #57629 Port logaddexp and logaddexp2 to structured
* #57628 Port lcm to structured
* #57627 Port hypot to structured
* #57626 Port igamma and igammac to structured
* #57625 Port nextafter to structured
* #57624 Port gcd to structured

Differential Revision: [D28224831](https://our.internmc.facebook.com/intern/diff/D28224831)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28224831).

**Comment by ezyang** [comment]
```

May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex128_bfloat16 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex128_bool (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex128_complex128 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex128_complex64 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex128_float16 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.003s]: test_maximum_minimum_complex_meta_complex128_float32 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex128_float64 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex128_int16 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex128_int32 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex128_int64 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex128_int8 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex128_uint8 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex64_bfloat16 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex64_bool (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex64_complex128 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex64_complex64 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex64_float16 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex64_float32 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex64_float64 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex64_int16 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex64_int32 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex64_int64 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex64_int8 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
May 05 16:11:35 
May 05 16:11:35 ======================================================================
May 05 16:11:35 FAIL [0.002s]: test_maximum_minimum_complex_meta_complex64_uint8 (__main__.TestBinaryUfuncsMETA)
May 05 16:11:35 ----------------------------------------------------------------------
May 05 16:11:35 Traceback (most recent call last):
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1030, in wrapper
May 05 16:11:35     method(*args, **kwargs)
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
May 05 16:11:35     result = test_fn(self, *args)
May 05 16:11:35   File "test_binary_ufuncs.py", line 1311, in test_maximum_minimum_complex
May 05 16:11:35     torch.ones(1, device=device, dtype=dtypes[1]))
May 05 16:11:35   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 938, in __exit__
May 05 16:11:35     return super().__exit__(exc_type, exc_value, tb)
May 05 16:11:35 AssertionError: RuntimeError not raised
```

**Comment by ezyang** [comment]
I'm not convinced by the new change. How come it wasn't necessary to test if it was complex in the old version of the code?

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28224831).

**Comment by Freey0** [comment]
> I'm not convinced by the new change. How come it wasn't necessary to test if it was complex in the old version of the code?

Sorry for the late reply.

Older versions of the code did not need this because it skipped the meta-test. The meta-test was performed after porting to the structured kernel
```
test_maximum_minimum_complex_meta_complex128_bfloat16 (__main__.TestBinaryUfuncsMETA) ... skipped "not_implemented: Could not run 'aten::maximum' with arguments from the 'Meta' backend.
```

**Pull request closed without merging**
