### PR TITLE
[tensorexpr][nnc] Support quantization

### PR DESCRIPTION
**Pull request by IvanKobzarev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #66326
* #66737
* __->__ #66676

Differential Revision: [D31676329](https://our.internmc.facebook.com/intern/diff/D31676329)
1. Introuducing quantized dtypes to tensorexpr:  QUInt8, QInt8

2. Introducing quantization lowerings for:
```
aten::quantize_per_tensor
aten::dequantize
_quantized::conv2d
quantized::conv2d_relu
quantized::add
aten::upsample_nearest2d
```

`quantize_per_tensor` and `dequantize` can be lowered as tensorexpr or external calls.
all other ops are lowered only as external calls.

Testing:
```
#!/bin/bash
PYTORCH_JIT_LOG_LEVEL=">>kernel:>>eval" \
PYTORCH_TENSOREXPR_DONT_USE_LLVM=1 \
USE_PYTORCH_QNNPACK=1 \
USE_QNNPACK=1 \
USE_FBGEMM=0 \
DEBUG=1 \
CXX_FLAGS="-g" \
 USE_LLVM=/home/ivankobzarev/llvm90install \
USE_XNNPACK=1 \
./scripts/build_local.sh \
  -DBUILD_BINARY=ON \
  -DCMAKE_BUILD_TYPE=Debug \
  -DBUILD_TEST=ON \
  -DUSE_LLVM=/home/ivankobzarev/llvm90install \
  && ./build/bin/test_tensorexpr --gtest_filter="Quantization.*"
```

### CODE REVIEW

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31676329).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31676329).

**Review by navahgar — APPROVED** [review]
LGTM.

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31676329).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31676329).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31676329).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31676329).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31676329).

**Pull request closed without merging**
