### PR TITLE
[quant][fix] Compare resnet with quantizer api with the prepare_fx and decomposed convert flow

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #98905

Summary:
Using a decomposed convert to make sure we get exact match, this means the nodes in resnet are
annotated correctly

Test Plan:
python test/test_quantization.py TestQuantizePT2EModels.test_resnet18_with_quantizer_api

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Review by andrewor14 — APPROVED** [review]

**Comment by izaitsevfb** [comment]
Hi @jerryzh168. I'm terribly sorry, but I need to revert this PR to unblock diff train import, as it conflicts with https://github.com/pytorch/pytorch/pull/99064 (which is landed internally as D44918496). Please coordinate with @kimishpatel and merge this PR on GH after #99064 merges on GH.

**Comment by kimishpatel** [comment]
Thanks @izaitsevfb, I will take care of relanding this.

**Comment by jerryzh168** [comment]
will recreate the PR instead

**Pull request closed without merging**
