### PR TITLE
Make slogdet, linalg.sloget and logdet support metatensors

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #80217
* #80074
* #80073
* #79838
* __->__ #79742

This PR also adds complex support for logdet, and makes all these
functions support out= and be composite depending on one function. We
also extend the support of `logdet` to complex numbers and improve the
docs of all these functions.

We also use `linalg_lu_factor_ex` in these functions, so we remove the
synchronisation present before.

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @ezyang @eellison @bdhirsh @soumith @ngimel @peterbell10

### CODE REVIEW

**Comment by Lezcano** [comment]
@JackCaoG This one may need a companion PR on XLA?
cf. https://github.com/pytorch/pytorch/runs/6929281711?check_suite_focus=true

**Comment by JackCaoG** [comment]
sure, let me know when pr is approved, I can work on a xla pr.

**Review by IvanYashchuk — APPROVED** [review]
Looks great! I have no suggestions for improvements.

**Comment by Lezcano** [comment]
@JackCaoG this has been approved, can we get the XLA PR?

**Comment by JackCaoG** [comment]
@Lezcano sg, I will work on a fix today or tmr.

**Review by albanD — APPROVED** [review]
OK

**Comment by JackCaoG** [comment]
Seems like I need to remove the lowering of `logdet`, `slogdet` and implement `_linalg_slogdet` instead?

**Comment by Lezcano** [comment]
Yup, that sounds about right. Now, I don't know why the CI is green atm (CC @janeyx99) but I think we do need the companion XLA PR.

**Comment by JackCaoG** [comment]
@Lezcano PyTorch/XLA CI is disabled on the master for some other reason. I will work on a fix.

**Comment by JackCaoG** [comment]
Hmm, compilation passed on xla at least. PyTorch/XLA lower `logdet` and `slogdet` which seems like still exist in the `native_function.yaml`. Since PyTorch/XLA Ci is disabled(working on reenabling that), I will start a empty pytorch/xla pr and target this pr to see if all test passed

**Comment by JackCaoG** [comment]
I saw some op test failed, I will work on a fix.

**Pull request closed without merging**
