### PR TITLE
test for multi-processing support of optimisers

### PR DESCRIPTION
**Pull request by mrTsjolder**
This is an answer to [this request](https://github.com/pytorch/pytorch/pull/32903#issuecomment-583491882) from @vincentqb to add tests for detecting an issue that occurs when the state of an optimiser is not correctly updated when it is shared among processes (using shared memory).

The idea of the test is to make sure that the state of the optimiser progresses in the same way, independent of whether multi-processing is used or not. The following code snippet should bring this idea across:
```python
def update(optimizer, x):
    optimizer.zero_grad()
    x.sum().backward()
    optimizer.step()

p = torch.zeros(10).requires_grad_(True).share_memory_() 
optim_multi = torch.optim.Adagrad([p]) 
optim_multi.share_memory() 
pool = torch.multiprocessing.Pool(1) 
pool.apply(update, (optim_multi, p))
print(optim_multi.state[p])

p = torch.zeros(10).requires_grad_(True)
optim_ref = torch.optim.Adagrad([p])
update(optim_ref, p)
print(optim_ref.state[p])
```
If the printed states (`dict`s) are the same, then the state was shared correctly. In its current state, Adagrad does seem to correctly share its `'sum'` state, but does does not update its `'step'` state correctly when using multi-processing.

### CODE REVIEW

**Comment by mrTsjolder** [comment]
Just waiting for a review. I assume that the bug fix will come in a separate PR, since I assume the only way to enable proper multi-processing support would be to enforce states to be wrapped into pytorch tensors, which would probably require changes to other optimisers.

**Comment by vincentqb** [comment]
Thanks for looking into this :) Since the initialization is currently in `__init__` for Adagrad, I would expect the test to pass though and fail with #17679 applied, right?

```
Jun 24 11:46:00 ======================================================================
Jun 24 11:46:00 FAIL [1.510s]: test_adagrad (__main__.TestOptim)
Jun 24 11:46:00 ----------------------------------------------------------------------
Jun 24 11:46:00 Traceback (most recent call last):
Jun 24 11:46:00   File "test_optim.py", line 433, in test_adagrad
Jun 24 11:46:00     self._test_multi_processing(optim.Adagrad)
Jun 24 11:46:00   File "test_optim.py", line 269, in _test_multi_processing
Jun 24 11:46:00     self.assertDictEqual(opt_ref.state[p_ref], opt_multi.state[p_multi])
Jun 24 11:46:00 AssertionError: {'step': 1, 'sum': tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])} != {'step': 0, 'sum': tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])}
Jun 24 11:46:00 - {'step': 1, 'sum': tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])}
Jun 24 11:46:00 ?          ^
Jun 24 11:46:00 
Jun 24 11:46:00 + {'step': 0, 'sum': tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])}
Jun 24 11:46:00 ?          ^
Jun 24 11:46:00 
Jun 24 11:46:00 
Jun 24 11:46:00 ----------------------------------------------------------------------
```

**Comment by mrTsjolder** [comment]
Not really (for as far I can tell). The problem is that the `step` is not in shared memory. The effects of this bug would only be noticeable when using the learning rate decay of `Adagrad`. 

PS: isn't the proper way to do lr decay to use a lr scheduler?

**Comment by mrTsjolder** [comment]
@vincentqb Any thoughts/comments?

I believe a proper fix would look something like:
```python
def share_memory(self):
    for group in self.param_groups:
        for p in group['params']:
            state = self.state[p]
            self.state[p] = multiprocessing.Manager().dict(state)
```
which would also make sure that different parts of the state are not altered simultaneously by different processes. Not sure how to test this properly, however.

**Pull request closed without merging**
