### PR TITLE
[dynamo] Skip mutation detection for inference mode

### PR DESCRIPTION
**Pull request by anijain2305**
Skip the mutation detection for inference_mode, and raise a warning. This helps one internal model

Related to https://github.com/pytorch/torchdynamo/issues/1768

@ezyang What do you think about this? The issue that Dynamo mutation detector uses version counter to detect mutation.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

### CODE REVIEW

**Comment by ezyang** [comment]
If none of the inputs require grad or no_grad is enabled you can also skip mutation detection. That is a test that is more likely to trigger. But yes, the correctness condition here is, IF AOTAutograd would be bypassed, you don't need mutation detection.

**Review by ezyang — APPROVED** [review]
The warning is unnecessary, this is sound. You may want to log it at lower verbosity.

**Comment by anijain2305** [comment]
Had a chat with @ezyang offline. AotAutograd is smart. If there is no need of autograd, it take a different codepath and generates only forward functions. It does not call any partitioner etc, which could disturb mutation. So, this is good to go.

**Comment by ezyang** [comment]
I just want to point out that we MUST keep the logic here and in AOTAutograd in sync; if they are not in sync there is a potential soundness issue.

**Pull request closed without merging**
