### PR TITLE
[stronghold][bc-linter] correctly determine the base commit of the PR

### PR DESCRIPTION
**Pull request by izaitsevfb**
Currently `${{ github.event.pull_request.base.sha }}` returns the HEAD of the base branch, which is different from **the base of the PR**.

See: 
https://github.com/github/docs/issues/431
https://github.com/orgs/community/discussions/39880

However, BC linter needs to know the base revision **of the PR**, as it looks at the changes **in the PR**.

This change is a workaround that determines the correct base of the PR. Hopefully in the future GH provides this information  in the event, and this workaround could be removed.

### CODE REVIEW

**Comment by izaitsevfb** [comment]
Successful run (on the outdated base branch): https://github.com/pytorch/pytorch/actions/runs/4662205658/jobs/8252306680?pr=98538

**Review by PaliC — APPROVED** [review]
Seems reasonable to me. Just need to lint.

**Pull request closed without merging**
