### PR TITLE
Migrate remaining ops to the c10 dispatcher

### PR DESCRIPTION
**Pull request by smessmer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #28468 Delete ATenDispatch
* #28186 Remove c10->ATen registration forwarding
* **#27978 Migrate remaining ops to the c10 dispatcher**

-

Differential Revision: [D17929697](https://our.internmc.facebook.com/intern/diff/D17929697/)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
There needs to be clear guidance about when to specify `unboxed_only` or not.

**Comment by ezyang** [comment]
I've been talking to people who were confused by these options. I think we should probably just write an algorithm to detect patterns that are not supported automatically, and then infer in this way.

**Review by ezyang — CHANGES_REQUESTED** [review]
NACKing test breakage

**Comment by dzhulgakov** [comment]
Agree with Ed - is it something we can figure out automatically by parsing schemas?

At the very least - if unboxed_only is the new default, why not just omit it? Any change to native_functions is pretty disturbing because of merge conflicts and mental overhead.

**Comment by smessmer** [comment]
@dzhulgakov see #28187 which removes it

**Comment by smessmer** [comment]
@ezyang Test failures should be fixed

**Review by dzhulgakov — APPROVED** [review]
Thanks for merging the two PRs

**Pull request closed without merging**
