### PR TITLE
Add interface for HPU

### PR DESCRIPTION
**Pull request by jeejakp12**
Add interface to check if hpu is_available(),
device count and to get the device type

Signed-off-by: Jeeja <jeejakp@habana.ai>

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by wconstab — CHANGES_REQUESTED** [review]
We generally don't include new devices in the public torch API unless they are in mainstream use.  Instead, out-of-tree backends should be used (following the torch/xla example).  Can you move this to an out-of-tree separate hpu repo?

**Comment by jeejakp12** [comment]
> We generally don't include new devices in the public torch API unless they are in mainstream use. Instead, out-of-tree backends should be used (following the torch/xla example). Can you move this to an out-of-tree separate hpu repo?

@wconstab does the backends like torch/xla have such APIs like is_available()? if not how to add it? do we have to always keep as out-of-tree?

**Comment by wconstab** [comment]
> does the backends like torch/xla have such APIs like is_available()

I don't think torch/xla has an is_available() api.  You can check their py API [here](https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_model.py).  

Is there a reason you couldn't implement is_available() in an external backend?

cc @JackCaoG in case he has any other context.  Note that torch/xla is working toward adopting pytorch lazy tensor API, and we're also working to make the distributed support for torch/xla work through the normal pytorch distributed APIs rather than only exposing new APIs for ops such as allreduce.

**Comment by JackCaoG** [comment]
for pt/xla I don't think we have `is_available` api. I have seen people just calling
```
xm.xla_device()
```

and check if there is any xla device returned and use that to determine if torch/xla is available or not.

**Pull request closed without merging**
