### PR TITLE
Update key_padding_mask arg docs in MHA module

### PR DESCRIPTION
**Pull request by cpuhrsch**

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Do I understand correctly that `True` in binary mask means masking out (by -inf)? (maybe a little counterintuitve)

**Review by zhangguanheng66 — COMMENTED** [review]
nit: Could you also update the docs in nn.Transformer [here](https://github.com/pytorch/pytorch/blob/caaea084e9e63dd3f22edcab0fda6822f7634820/torch/nn/modules/transformer.py#L100)?

**Comment by zhangguanheng66** [comment]
> Do I understand correctly that `True` in binary mask means masking out (by -inf)? (maybe a little counterintuitve)

@vadimkantorov Yes, you are right. With `True` in mask, the positions will be filled with `-inf`. Based on my understanding, it's "True" to "mask out" something in the positions.

**Comment by vadimkantorov** [comment]
If the binary mask is still new, maybe possible to inverse it? So that False means masking out? Or does this current behavior match huggingface?

**Review by zhangguanheng66 — APPROVED** [review]

**Comment by zhangguanheng66** [comment]
> If the binary mask is still new, maybe possible to inverse it? So that False means masking out? Or does this current behavior match huggingface? A related issue in huggingface/transformers: [huggingface/transformers#4141](https://github.com/huggingface/transformers/issues/4141)

IMO, we should be consistent between byte and bool tensor masks.

**Comment by vadimkantorov** [comment]
Byte masks are to be phased out / deprecated anyway, right? If yes, normal mask semantics should be preferred IMO (or at least it should be called inv_mask or neg_mask). Anyway, this is just my personal opinion, not very crucial problem

**Pull request closed without merging**
