### PR TITLE
Add recompute_scale_factor option for torch.nn.Upsample layer

### PR DESCRIPTION
**Pull request by miraliahmadli**
`torch.nn.Upsample` currently do not support `recompute_scale_factor` option as it uses passed `scale_factor` argument. So, it calls `torch.nn..functional.interpolate` function in forward pass with its default `recompute_scale_factor` value which is `None` and therefore I was getting following warning message:
```
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:3000:   
UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align   
with other frameworks/libraries, and uses scale_factor directly, instead of relying on the computed output size.   
If you wish to keep the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
```
So, I added `recompute_scale_factor` argument for `torch.nn.Upsample` class so that in forward operation, we can specify whether to use passed scale_factor or not (as well as avoiding warning message).

Furthermore, the same argument can be added to `torch.nn.UpsamplingNearest2d` and `torch.nn.UpsamplingBilinear2d` classes as they inherit from the `torch.nn.Upsample` class. I can add it to these layers as well if you want.

### CODE REVIEW

**Comment by miraliahmadli** [comment]
The default behaviour of `torch.nn..functional.interpolate` without `recompute_scale_factor` is same as it being False, but it just throws warning message. Instead of adding `recompute_scale_factor` option, False value can be directly passed to avoid warning message as well.

**Comment by ichko** [comment]
I am also getting the warning. Can someone look at this?
Is there any other way to remove the warning?
Thanks!

**Comment by amalp12** [comment]
I have the same issue, it is showing this warning and `recompute_scale_factor` is not an aruguement. When I tried to pass `False` in `nn.Upsample` without any keyword it doesn't work either. This warning is really annoying.

**Comment by vfdev-5** [comment]
`recompute_scale_factor` arg was added to `nn.Upsample` in https://github.com/pytorch/pytorch/pull/66419.
@miraliahmadli sorry, I haven't seen your PR before submitting the mine.
I close this PR in favor of #66419

**Pull request closed without merging**
