### PR TITLE
[decomp] Bad accuracy for elu_backward

### PR DESCRIPTION
**Pull request by anijain2305**
Accuracy is tested by the full model at https://github.com/pytorch/pytorch/issues/100061

### CODE REVIEW

**Comment by ngimel** [comment]
How come it was not caught by tests?

**Comment by ngimel** [comment]
Can you please add a test that would exercise this path?

**Review by ngimel — APPROVED** [review]

**Comment by AbsolytnaiaLove** [comment]
#100284

**Comment by ezyang** [comment]
Any reason our OpInfo testing didn't catch this?

**Comment by lezcano** [comment]
This is the path when the operation is done in-place. We skip those operations in the grad tests. A better test would be able to catch this I reckon.

**Pull request closed without merging**
