### PR TITLE
Add ONLY_FOR_TEST device type into executor

### PR DESCRIPTION
**Pull request by sf-wind**
Add ONLY_FOR_TEST device type into executor to support some of the tests

### CODE REVIEW

**Comment by ezyang** [comment]
This does not seem to fix the failures

**Comment by sf-wind** [comment]
Obviously not. Ilia has another diff on this: D8416777. Will port it to github

**Comment by ezyang** [comment]
@sf-wind Which test is this supposed to fix?

**Comment by sf-wind** [comment]
Ilia sent D8406509 and D8416777 to fix the flaky tests issue. This is the first one. My guess is that both need to land to fix the test issue. I messaged him to double check, but he hasn't replied, so no confirmation to my guess.

**Comment by ezyang** [comment]
This PR seems reasonably likely to fix the other failure. I am applying it.

**Review by ezyang — APPROVED** [review]

**Pull request merged**
