### PR TITLE
Added CUDA support for complex input for torch.triangular_solve

### PR DESCRIPTION
**Pull request by IvanYashchuk**
`torch.triangular_solve` now works for complex inputs on GPU.
I moved the existing tests to `test_linalg.py` and modified them to test complex and float32 dtypes.

Ref. #33152

### CODE REVIEW

**Review by anjali411 — APPROVED** [review]
LGTM thanks @IvanYashchuk !

**Comment by anjali411** [comment]
@IvanYashchuk can you rebase and resolve the merge conflict?

**Comment by IvanYashchuk** [comment]
@anjali411, I resolved the merge conflict.

**Comment by IvanYashchuk** [comment]
@anjali411, I updated this PR, should be ready for merge now. After that, the next PR on the list is `torch.solve`.

**Comment by anjali411** [comment]
@IvanYashchuk https://github.com/pytorch/pytorch/pull/47595 is merged, so let's get this in now. let me know when you have rebased and resolved the merge conflicts

**Comment by IvanYashchuk** [comment]
Hey @anjali411, merge conflicts were resolved.

**Pull request closed without merging**
