### PR TITLE
Add typing to collect_env.py

### PR DESCRIPTION
**Pull request by scottilee**
The torchx project wants to use this script to collect information from contributors.

Originally we were going to copy the file so type info was added but then we decided to just call the file from another script. Creating this pull request so the type info isn't lost.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Sorry you're gonna have to rebase this and fix the conflict

**Comment by scottilee** [comment]
@ezyang I was able to rebase but now I'm getting errors about syntax. The [lint.yaml](https://github.com/pytorch/pytorch/blob/fc3a5d81171ba465e3d62ffbda9713b53039b5f0/.github/workflows/lint.yml#L235-L248) shows that "older_python_version" is Python 3.5 and 3.7 and types should work for those versions, but not sure why it's not able to run?

**Comment by ezyang** [comment]
Type annotations were added in https://docs.python.org/3/whatsnew/3.6.html#pep-526-syntax-for-variable-annotations 

I think we should just dump support for the old python version and do something like https://github.com/jwilk/python-syntax-errors to give a good error message in these cases

**Comment by scottilee** [comment]
Added `1 or 0 @ 0  # Python >= 3.5 is required` to the script and removed the "Setup Python 3.5" lint.

**Comment by kit1980** [comment]
cc @seemethere who just added https://github.com/pytorch/pytorch/pull/78946

**Comment by seemethere** [comment]
I'd say we'd like to keep compat with Python 3.X considering we still ask users to report bugs using this script and sometimes they may report bugs for older versions as well.

Is there any particular reason to add typing to this script that would make us lose this backwards compatability?

**Comment by scottilee** [comment]
@seemethere Let me know if this doesn't answer the question but per @ezyang's reply above type annotations aren't supported until [Python 3.5](https://docs.python.org/3/whatsnew/3.6.html#pep-526-syntax-for-variable-annotations) so the linter will throw an error and fail because it doesn't recognize the types.

**Comment by ezyang** [comment]
Reporting bugs for old versions of PyTorch on old versions of Python doesn't seems like good RoI. @seemethere is there something I'm missing?

**Comment by seemethere** [comment]
> Reporting bugs for old versions of PyTorch on old versions of Python doesn't seems like good RoI. @seemethere is there something I'm missing?

Potentially not, but if we have a utility that's used to report bugs and expect users to pull it from master it'd probably benefit us to keep it as compatible as possible. Users will continue to report issues with it otherwise (like https://github.com/pytorch/pytorch/issues/78840).

I guess as well I'm just failing to see how typing would benefit this script since typing doesn't really benefit utility scripts like this anyways.

**Comment by ezyang** [comment]
Actually this is a case where typing helps a bit; utility script tends to have a lot of conditions and edge cases that won't normally get exercised, so a type checker can help catch dumb typos in those else branches

**Comment by ezyang** [comment]
The compromise solution is to use ugly py2 style comment syntax lol

**Comment by scottilee** [comment]
I'll close this for now and if the project ends up dropping support for older Python versions I can revisit it then since the code is here.

**Pull request closed without merging**
