### PR TITLE
Support cdf for mixture_same_family distribution

### PR DESCRIPTION
**Pull request by buoyancy99**
The new added mixture_same_family should support cdf if the family has cdf implemented.

This is very useful for flow models where cdf of mixture of gassian/logistic is used to model flow

### CODE REVIEW

**Review by fritzo — APPROVED** [review]
LGTM.

@buoyancy99 can you please confirm that tests will be automatically triggered now that this is implemented?

**Comment by fritzo** [comment]
@buoyancy99 can you also try merging master and pushing to see if tests are fixed?

**Comment by buoyancy99** [comment]
> @buoyancy99 can you also try merging master and pushing to see if tests are fixed?

Let me look at the test

**Comment by fritzo** [comment]
the failures are probably unrelated, I'd merge just to trigger retesting

**Comment by buoyancy99** [comment]
> the failures are probably unrelated, I'd merge just to trigger retesting

How to I run the test again? Do I just start a new PR?

**Comment by fritzo** [comment]
Just merge your local brach with master then push. That should re-trigger tests.

**Comment by fritzo** [comment]
Failing test appears urelated

**Pull request closed without merging**
