### PR TITLE
Non var

### PR DESCRIPTION
**Pull request by anderspapitto**

### CODE REVIEW

**Comment by anderspapitto** [comment]
this is built on top of https://github.com/pytorch/pytorch/pull/5614 - reviewers, just look at the top commit until that PR is merged

**Review by apaszke — APPROVED** [review]

**Comment by ezyang** [comment]
Needs a rebase, alas.

**Comment by anderspapitto** [comment]
@ezyang rebased, all tests are passing except for a perf test which I'm pretty sure has nothing to do with this diff

**Pull request merged**
