### PR TITLE
reland "support running test_mobile_profiler with buck1/buck2 and OSS (#89001)"

### PR DESCRIPTION
**Pull request by dagitses**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89091

We modify this to no longer use std::experimental::filesystem::path
and use our own custom type instead.

This reverts commit c53a5ac6cca7e2e7d7c47b1a816c7eaa2e7a7704.

### CODE REVIEW

**Review by r-barnes — APPROVED** [review]

**Comment by dagitses** [comment]
@pytorch merge

**Comment by malfet** [comment]
Can you please provide some information what has changed since the previous land attempt? (unless its only internal chanegs)

**Review by malfet — APPROVED** [review]

**Comment by dagitses** [comment]
> Can you please provide some information what has changed since the previous land attempt? (unless its only internal chanegs)

dropped `std::experimental::filesystem` and handrolled something simple.

**Pull request closed without merging**
