### PR TITLE
Upgrade NVTX to NVTX3

### PR DESCRIPTION
**Pull request by cyyever**
Due to recent upgrade to CUDA 11, we can upgrade NVTX to NVTX3 as well, which is a header only library that can simplify the building system a lot.

### CODE REVIEW

**Comment by cyyever** [comment]
@zou3519 Can you assignment me a relevant reviewer?  No one from PyTorch Dev Infra has a response.

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
this looks fine, but I'll let @robieta merge this in as this might need build file changes to fbcode

**Review by malfet — APPROVED** [review]

**Comment by cyyever** [comment]
@soumith @malfet @robieta I have add more changes to handle windows cuda 11.6 test failure and for the general case of broken CUDA installation by referring to the official NVTX lib.

**Comment by malfet** [comment]
Hmm, can you just add:
```cpp
#ifndef FBCODE_CAFFE2
#include <nvtx3/nvToolsExt.h>
#else
#include <nvToolsExt.h>
#endif
```

This way internally we can use old path/build-rules and adjust at some later point?

**Comment by cyyever** [comment]
@malfet That change is easy

**Comment by malfet** [comment]
@cyyever Cmake is not used for internal builds, so yes, pretty sure.

**Comment by cyyever** [comment]
@malfet The macro has been added, can you review?

**Comment by milesial** [comment]
Hi, is this ready to merge?

**Comment by cyyever** [comment]
@malfet Can you reimport it into META so that I can merge?

**Comment by milesial** [comment]
What is blocking this merge?

**Comment by cyyever** [comment]
It is imported in META. I have to wait their rebase before merge.

**Comment by milesial** [comment]
What is the estimated timeline for the rebase before merge?

**Comment by malfet** [comment]
@cyyever I don't think my import should be blocking in any way. But rebase failure looks real, isn't it?

**Comment by osalpekar** [comment]
It appears this breaks a number of FRL jobs with the following error:
```
caffe2/torch/csrc/profiler/stubs/cuda.cpp:4:10: fatal error: 'nvtx3/nvToolsExt.h' file not found
#include <nvtx3/nvToolsExt.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

See more: [D42332540](https://www.internalfb.com/diff/D42332540)

**Pull request closed without merging**
