### PR TITLE
Providing a portable model serialization path

### PR DESCRIPTION
**Pull request by zeryx**
torch.save() and torch.load() assume that you will always have the original network definition module in your project, and that it never changes -in order for you to successfully depickle your model. 
This is certainly reasonable to expect during development and prototyping projects, however for lager production projects where your torch model definition and execution code is only one component of the overall project this can lead to serious version control issues. Model files created with previous network definitions cease to work properly, making backwards compatibility incredibly challenging and sometimes completely unfeasible.

The changes I made here were taken from an ergonomics helper module I released on pypi here: https://github.com/algorithmiaio/pytorch-ergonomics, which can be used to experience how the changes can improve your development experience without having to build from source to explore this commit.

Certainly open to improvement suggestions, I've tried to interoperate as much as possible, but I'd certainly appreciate additional :eyes: on this.

### CODE REVIEW

**Comment by zeryx** [comment]
This probably needs some unit tests right? I'll add some now

**Comment by soumith** [comment]
let me explain why I think this isn't a great idea (we definitely thought about this when we were writing torch.save / torch.load).

- Model files where part of the definition is an inline python string wont work
- Model definitions with unpicklable objects simply wont work (such as lambdas)
- Saved definitions across pytorch versions might or might not work

The hazard of introducing this (versus letting users develop their reliable checkpointing scheme on top of torch.state_dict / torch.save) is that this has a false pretense of "working" or "official" but breaks in a bunch of cases.

**Comment by zeryx** [comment]
Thanks for the quick response @soumith! 
Let me take a crack at exploring your scenarios:
 * `Model files where part of the definition is an inline python string won't work` -> I can't imagine or visualize a scenario where this might occur, this also seems (from my rudimentary understanding of the process) to be somewhat of an anti-pattern that should be discouraged, no? Maybe I'm misunderstanding you here.

* `Model definitions with unpicklable objects simply won't work (such as lambdas)` -> Since this is an optional save/load path (I intentionally separated it from .load() and .save() for this reason) we aren't necessarily restricting the development surface to only picklable components, but giving an ergonomic option when your model architecture satisfies these (lightweight) requirements.

* `Saved definitions across pytorch versions might or might not work` -> True, but that problem still exists if you preserved your source code anyways. Now that I'm thinking about it, I could certainly imagine a world where a metadata file was provided in the zip ball along with the source/model files for additional clarity, where the torch version and other information that the developer might need could exist. If we're in agreement here I might spend an hour or so to make sure that the model/model def metadata is exposed with `load_model()`.

The altruistic reason why I made this PR was to improve the new user experience for developers of a background similar to mine (productionizing ML).

With all of that, I certainly don't want to discourage any suggestions on how to improve this PR! I really want to see it move forward. I would hate to see another user, particularly a novice or new pytorch user, run into the issue I'm trying to tackle with the PR without access to the tools they need to solve it.

**Comment by apaszke** [comment]
Thanks for the PR @zeryx! That's certainly one way to serialize PyTorch models, and we considered it when we were writing our serialization code. While your replies to points made by @soumith make sense, and this might be useful in *some* use cases, I don't think we're ready to commit to this particular file format just yet. Once something enters the core library it's very hard to remove it later, and I think this problem deserves some extra care. I think for now it's much better to push everyone towards using ONNX for serialization, as that will come with a number of extra benefits like better portability.

Please feel free to include this serialization method as part of the package you created, or a new one. It might be valuable to some people! I just don't think it's what we want to be part of the core library just yet.

**Pull request closed without merging**
