### PR TITLE
Update operator documentation with markdown descriptions and interfaces

### PR DESCRIPTION
**Pull request by MatthewInkawhich**
Added markdown descriptions and interfaces to operator source (.cc) files. Initial pull request contains three changed files. Will push rest of completed files when build succeeds.

ATTN: @orionr @janelu1

### CODE REVIEW

**Review by orionr — APPROVED** [review]

**Comment by ezyang** [comment]
Needs a rebase

**Comment by ezyang** [comment]
```
19:53:09 /opt/conda/conda-bld/caffe2_1528573424681/work/caffe2/operators/sqrt_op.cc:98:1: error: expected ‘}’ at end of input
19:53:09  } // namespace caffe2
19:53:09  ^
```

**Comment by ezyang** [comment]
flaky tests and upstream breakage. You're good

**Pull request merged**
