### PR TITLE
test_bottleneck_cuda works on ROCm 3.3

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
Seeing unrelated memory access faults in unit tests. @pytorchbot retest this please

**Comment by jithunnair-amd** [comment]
The `TestAutograd.test_memory_profiler` test was fixed upstream in the interim. So @pytorchbot retest this please.

**Comment by ailzhang** [comment]
@jithunnair-amd I'm afraid pytorchbot is not working atm. Would you mind triggerring the build through a new (empty)commit? Thanks!

**Comment by jithunnair-amd** [comment]
@ailzhang Are you sure though? I do see it kicked off two new ROCm CI builds...

**Comment by ailzhang** [comment]
@jithunnair-amd  oh okay, looks like it still works for jenkins but not for circleci. Yea this is fine, feel free to use it to test. Please ping me when it's ready to land!

**Comment by jithunnair-amd** [comment]
Failing tests were due to a breaking upstream commit, reverted in https://github.com/pytorch/pytorch/commit/d92ef9268d08050b5d55e49bda732072b102c1dd. @pytorchbot retest this please.

**Comment by jithunnair-amd** [comment]
@ailzhang Ready to merge

**Review by ailzhang — APPROVED** [review]

**Pull request closed without merging**
