### PR TITLE
[caffe2][training]Implementation of WeightedSum op for mkl-dnn and fix FC op output shape issue.

### PR DESCRIPTION
**Pull request by PenghuiCheng**

### CODE REVIEW

**Comment by ezyang** [comment]
@yinghai could you please look at this

**Comment by yinghai** [comment]
@wesolwsk Could you take a look?

**Comment by wesolwsk** [comment]
@PenghuiCheng, could you rebase and address the following style changes: 
screen shot 2018-12-06 at 1 30 39 pm

**Comment by PenghuiCheng** [comment]
Hi,@wesolwsk ，I  had updated codes. Please review it.
thanks!

**Pull request closed without merging**
