### PR TITLE
[nnc][quantization] avoid memcpy for external functions via out ops

### PR DESCRIPTION
**Pull request by IvanKobzarev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70081
* #70080
* __->__ #69954
* #69856

Differential Revision: [D33115665](https://our.internmc.facebook.com/intern/diff/D33115665)

### CODE REVIEW

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33115665).

**Review by ZolotukhinM — APPROVED** [review]
Looks good!

**Review by kimishpatel — COMMENTED** [review]
To be honest quantized variants of add and mul with _out variant dont make sense. I dont know how they exist in the first place. Reason is that for these ops we need scales and zero points and if we have `quantized::add_out` who in the JIT graph is constructing output tensor. @jerryzh168 do you know why they exist?

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33115665).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33115665).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33115665).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33115665).

**Comment by jerryzh168** [comment]
> To be honest quantized variants of add and mul with _out variant dont make sense. I dont know how they exist in the first place. Reason is that for these ops we need scales and zero points and if we have `quantized::add_out` who in the JIT graph is constructing output tensor. @jerryzh168 do you know why they exist?

oh, the out variant is assuming the output Tensor (first argument of the op) has the scale/zero_point for output Tensor setup properly.
yeah thinking from the quantization flow's perspective, I'm not sure when these ops are produced, my guess is that it's probably not supported right now in any of the flows. do we see this op being used in real models currently?

**Comment by kimishpatel** [comment]
> > To be honest quantized variants of add and mul with _out variant dont make sense. I dont know how they exist in the first place. Reason is that for these ops we need scales and zero points and if we have `quantized::add_out` who in the JIT graph is constructing output tensor. @jerryzh168 do you know why they exist?
> 
> oh, the out variant is assuming the output Tensor (first argument of the op) has the scale/zero_point for output Tensor setup properly. yeah thinking from the quantization flow's perspective, I'm not sure when these ops are produced, my guess is that it's probably not supported right now in any of the flows. do we see this op being used in real models currently?

@IvanKobzarev I wont rely on this for landing something in production. As @jerryzh168 mentioned this should not really be there.

**Comment by kimishpatel** [comment]
> > To be honest quantized variants of add and mul with _out variant dont make sense. I dont know how they exist in the first place. Reason is that for these ops we need scales and zero points and if we have `quantized::add_out` who in the JIT graph is constructing output tensor. @jerryzh168 do you know why they exist?
> 
> oh, the out variant is assuming the output Tensor (first argument of the op) has the scale/zero_point for output Tensor setup properly. yeah thinking from the quantization flow's perspective, I'm not sure when these ops are produced, my guess is that it's probably not supported right now in any of the flows. do we see this op being used in real models currently?

@jerryzh168 I dont think any model produces this.

**Comment by IvanKobzarev** [comment]
@IvanKobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33115665).

**Pull request closed without merging**
