### PR TITLE
[wip][jit] ShadowClassType for mutating ClassType

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #28566 [quant][graphmode] Remove observer module
* **#28565 [wip][jit] ShadowClassType for mutating ClassType**
* #28627 [refactor] Make entity_type a global helper function

Summary:
Added a `ShadowClassType` for modification of `ClassType`, it inherits from
`ClassType` and we can perform following operations on the `ShadowClassType`
- addAttribute
- removeAttribute
After the modification, we can create a new ClassType with modified attributes.

Test Plan:
will test in graph mode quantization(next PR)

Reviewers:
mvz

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Comment by suo** [comment]
My first order question is: does this need to be part of the type system? This seems to be more of a helper that helps you generate a new class type, but it would be an error for any `Value` to ever actually take on this type, which suggests to me that this is the wrong place to implement it.

**Comment by jerryzh168** [comment]
> My first order question is: does this need to be part of the type system? This seems to be more of a helper that helps you generate a new class type, but it would be an error for any `Value` to ever actually take on this type, which suggests to me that this is the wrong place to implement it.

Reason I'm inheriting from `ClassType` and adding it to `Type` is because I want to reuse some functions in `ClassType` and I think we want to keep `ClassType` immutable, if that is not a requirement then we can merge this into `ClassType`. If it is, I can find other workaround.

**Comment by jerryzh168** [comment]
The way we want to use this class is in next PR, basically we pass the `ShadowClassType` around, and record add/remove attribute along the way when we modify the class type, and in the end we call 'create_module_from_shadow_class` to create a new module from the old one, where we might add/remove attribute. I want to make sure whether this procedure looks OK or we might hit something that doesn't work with this process.

I think remove should work, since it's just filtering out some attributes. For add attribute, I think we might want to keep the current approach(that is adding to the class type directly) since after adding an attribute to class type, we'll also set the corresponding ivalue in the module object as well.

**Comment by ZolotukhinM** [comment]
I agree with @suo that it doesn't make much sense to allow creating ivalues of this type, so it might be better to move it out from Type.

Also, I recommend not mixing general features like this with specific use-cases (like quantization) in the same PR stack, and the testing should definitely not be deferred to a custom use-case.

**Comment by zdevito** [comment]
We should clarify what modifying a class type would require, and work from there to figure out the requirements. The compiler has no way of mutating a graph (e.g. by changing a type) and then checking whether the new graph is still type safe. Typically passes ensure this safety inductively, but changing a type is a program wide operator (you do not know where else that type is used. by modifying it, it may no longer subclass another type and break in some other code). This makes modifying types, even as a Module -> Module transform potentially unsafe. Building a way to re-check type safety would be a large undertaking and would have no way to communicate any errors easily, so I recommend a pathway that avoids it.  Additional complexities to keep in mind:

* types are shared across modules (@suo), so replacing each individual's module with a different type is not safe. It may be passed as an object to something expecting the old type.
* Modules may be subtypes of interfaces, meaning they can appear in places where the type is not literally the module itself.
* It is legit to take a module and add to a list that contains an interface that this modules meets. This is going to have to work after the type gets modified. 
* We have to be careful about inlining. Once things related to the module have been inlined, there is no way to patch the implementation.  When to inline is an implementation detail and should not become something we track in the compiler process because this would require extensive bookkeeping to ensure.

We should consider whether the API should only allow the replacing of a type with another compatible one. For instance, it is fine to add an attribute, or to change internal details of the types implementation, but removing an attribute is not ok. If removing an attribute is desired, e.g. by replacing it with a constant. Then the new type has to provide a property (note: we do not support properties, yet) that implements how to recover the missing attribute.

**Comment by jerryzh168** [comment]
Thanks for the comments! I'll move this class to a different file.
From @zdevito's comments I feel we probably don't want to support removing attributes as a general feature and only support adding attribute, which we already do when we do register_module, register_attribute etc. modifying details of a type seems not easy to do either, and I don't have a use case of that so we probably won't do that.

Another comment I have is even though we can't support removing attribute as a general feature, can we support that in quantization only when we know it is safe to remove observers modules that we inserted earlier?

**Comment by ZolotukhinM** [comment]
Changing an existing type safely is hard (if possible at all), but the entire point of having "ClassTypeBuilder" was that instead of changing an existing type we would create a new type. Similarly, for module to module transformation we can make it valid since we're creating a new module, but we need to be extra careful with what steps we expose to users of this API so that it cannot be used in a wrong way.

**Comment by jerryzh168** [comment]
So the current API for create a new module given the modified type is `Module create_module_from_shadow(const ShadowClassTypePtr& s_cls) ` where we create a new module given a `ShadowClassTypePtr`.

I'm not sure how hard it is to do type check for the modified type. For attributes of the modified type, we have several situations when we create a new module:
1. original module has same attributes as the modified class type: is it enough to check the types match?
2. modified class type has new attribute: it will be initialized to `IValue()`(we plan to set it later)
3. original module has more attribute: it will be ignored since we are traversing the attribute list of modified class type - is this OK?

Do we need more type checks beyond this?

And this is creating a new type, so it's not really a "modification", sorry for the confusion..

**Comment by ZolotukhinM** [comment]
We need to separate APIs for creating modules and creating types. In the end we would need both but it doesn't help constantly mixing them in the discussion.

So, for the types: here we would use the type builder which will allow to build a new type. When we copy methods for this new type we will remap the used types to their copies and would be able to verify that it's valid. The check would probably only happen at the actual type instantiation time.

For the modules, we would need a way to create an "empty" module of a given type and then set its parameters/attributes. Then the actual values can be copied from another module or set somehow else, but I don't think this should be part of *this* API.

**Comment by jerryzh168** [comment]
After offline discussion we plan to add `unsafeRemoveAttribute` in `ClassType`: https://github.com/pytorch/pytorch/pull/28984, and we don't plan to support general, user facing `removeAttribute`.

**Pull request closed without merging**
