### PR TITLE
[BE] Use `teardown-linux`/`chown` actions for binary builds

### PR DESCRIPTION
**Pull request by malfet**
Also embed `wait_for_ssh_to_drain.sh` into the action (to make it more reusable across repos) and delete unused teardown_linux template from `common.yml`

Also, in `_binary-test-linux.yml` move artifact download step after repo checkout, to make errors during that step more parseable

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by malfet** [comment]
> @pytorchbot revert -m "Revert as it broke trunk, though on next PR" -c weird

To clarify what was weird about it - PR was correct, but GH were experiencing outage, so artifact download step failed periodically...

**Pull request closed without merging**
