### PR TITLE
Add torch.cuda.stream.ExternalStream, expose cudaStreamCreate/Destroy

### PR DESCRIPTION
**Pull request by emcastillo**
Previous is #57781

We add now two CUDA bindings to avoid using ctypes to fix a windows issue.
However, we use ctypes to allocate the stream and create its pointer
(we can do this with a 0-dim tensor too if it feels better).

CC. @ezyang @rgommers @ngimel @mruberry

### CODE REVIEW

**Comment by emcastillo** [comment]
Seems test is unrelated?

```03:20:52 Traceback (most recent call last):
03:20:52   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 516, in run_test
03:20:52     getattr(self, test_name)()
03:20:52   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 400, in wrapper
03:20:52     fn()
03:20:52   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 93, in wrapper
03:20:52     return func(*args, **kwargs)
03:20:52   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 3348, in test_DistributedDataParallel_non_default_stream
03:20:52     msg=f"Expected gradient of {expected_grad} but got {avg} on rank {self.rank}",
03:20:52   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1273, in assertEqual
03:20:52     exact_dtype=exact_dtype, exact_device=exact_device)
03:20:52   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1406, in assertEqual
03:20:52     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
03:20:52   File "/opt/conda/lib/python3.6/unittest/case.py", line 682, in assertTrue
03:20:52     raise self.failureException(msg)
03:20:52 AssertionError: False is not true : Scalars failed to compare as equal! Comparing 0.888888955116272 and 1.0 gives a difference of 0.11111104488372803, but the allowed difference with rtol=1.3e-06 and atol=1e-05 is only 1.13e-05!
03:20:52 Expected gradient of 1.0 but got tensor([[0.8889]], device='cuda:2') on rank 2
```

**Comment by emcastillo** [comment]
rebased on top of viable/strict

**Comment by emcastillo** [comment]
Seems like CI should be mostly ok now @ezyang ?
Thanks!

**Review by ezyang — APPROVED** [review]
good show, thanks

**Comment by ezyang** [comment]
hopefully this time's a charm!

**Pull request closed without merging**
