### PR TITLE
Benchmark RecordFunction overhead on some models

### PR DESCRIPTION
**Pull request by ilia-cher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#40952 Benchmark RecordFunction overhead on some models**

Summary:
Adding a benchmark to measure RecordFunction overhead,
currently on resnet50 and lstm models

Test Plan:
~/local/pytorch  (rec_fn_bench_models)$ PYTHONPATH="$(pwd)/benchmarks/experimental_components" python benchmarks/record_function_benchmark/record_function_bench.py

https://gist.github.com/ilia-cher/2cb249f5b5e3382dda5cb71ff855c2db

Differential Revision: [D22368357](https://our.internmc.facebook.com/intern/diff/D22368357)

### CODE REVIEW

**Review by dzhulgakov — APPROVED** [review]
Hm, 8% sounds like a lot, is it already with the optimizations applied?

**Comment by robieta** [comment]
> Hm, 8% sounds like a lot, is it already with the optimizations applied?

I think this is run-to-run variation. I tweaked the script in this PR to use the PyTorch `Timer` (and `Compare`): https://gist.github.com/robieta/2c83e4f7840efa1fd9906778d11ca353
Note:
  1) I had to use the `python setup.py install` workflow, because if I used `python setup.py develop` when I ran the script Python would import the pytorch that was installed as a torchvision dep rather than the working on. Not sure if I'm doing something wrong.
  2) You have to set `PYTHONPATH` to pick up the Timer directory. (See the top of the script)
  3) You need https://github.com/pytorch/pytorch/pull/41011 for `comparison.highlight_warnings()`

On my machine, I see the following:
```
[------------- Record function overhead ------------]
                      |    lstm_jit   |  resnet50_jit
1 threads: ------------------------------------------
      with_rec_fn     |   650         |  8600
      without_rec_fn  |   660         |  8000
2 threads: ------------------------------------------
      with_rec_fn     |   360         |  4200
      without_rec_fn  |   350         |  4000
4 threads: ------------------------------------------
      with_rec_fn     |   250         |  2100
      without_rec_fn  |   260         |  2000
8 threads: ------------------------------------------
      with_rec_fn     |   200 (! 6%)  |  1200
      without_rec_fn  |   210 (! 6%)  |  1100
16 threads: -----------------------------------------
      with_rec_fn     |   220 (! 8%)  |   900 (! 5%)
      without_rec_fn  |   200 (! 5%)  |  1000 (! 7%)
32 threads: -----------------------------------------
      with_rec_fn     |  1000 (! 7%)  |   920
      without_rec_fn  |  1000 (! 6%)  |   900 (! 6%)

Times are in milliseconds (ms).
(! XX%) Measurement has high variance, where XX is the median / IQR * 100.
```

A couple things strike me:
  1) At high thread counts variance increases. The benchmark in this PR is also using mean, which is more sensitive to the tail behavior.
  2) At 32 threads the LSTM takes a nose dive off a performance cliff. This was accidental (I forgot my CPU only had 24 cores) and it's unlikely that many (if any) people will actually see this in practice, but it did confuse me for a bit.

@ilia-cher WDYT?

**Comment by ilia-cher** [comment]
@robieta thanks for the Timer and Compare diff! will update and rerun;

**Comment by ilia-cher** [comment]
Added @robieta 's changes and did some more runs.

Second gist (with min_run_time=120) looks less noisy and is for lstm_jit:
https://gist.github.com/ilia-cher/2cb249f5b5e3382dda5cb71ff855c2db

```
                      |  lstm_jit
1 threads: ----------------------
      with_rec_fn     |    620
      without_rec_fn  |    600
2 threads: ----------------------
      with_rec_fn     |    400
      without_rec_fn  |    400
4 threads: ----------------------
      with_rec_fn     |    270
      without_rec_fn  |    267
8 threads: ----------------------
      with_rec_fn     |    229
      without_rec_fn  |    220
16 threads: ---------------------
      with_rec_fn     |    240
      without_rec_fn  |    240
32 threads: ---------------------
      with_rec_fn     |    340
      without_rec_fn  |    330

Times are in milliseconds (ms).
```

**Comment by kimishpatel** [comment]
> Hm, 8% sounds like a lot, is it already with the optimizations applied?

We have started seeing this in mobile as well. Particularly on mobile with smaller models where op runtime is relatively smaller than on server side, it seems the overhead of profiling is high. _some_ of which I presume is coming from RECORD_FUNCTION callbacks. Have you tried benchmarking this on smaller models, say mobilenetV2? Although running that model on server is not fair since AVX2/AVX512 capabilities provide 2 to 4x vectorized speedup compared to what is available on mobile. But it may give some hint as to the overhead when model is smaller.

**Comment by ilia-cher** [comment]
> > Hm, 8% sounds like a lot, is it already with the optimizations applied?
> 
> We have started seeing this in mobile as well. Particularly on mobile with smaller models where op runtime is relatively smaller than on server side, it seems the overhead of profiling is high. _some_ of which I presume is coming from RECORD_FUNCTION callbacks. Have you tried benchmarking this on smaller models, say mobilenetV2? Although running that model on server is not fair since AVX2/AVX512 capabilities provide 2 to 4x vectorized speedup compared to what is available on mobile. But it may give some hint as to the overhead when model is smaller.

Kimish, do you mean specifically profiling? then yes it's known to have a larger overhead, in this benchmark I benchmark only record function itself (observer api, observers are empty in this benchmark), the latest runs show an overhead of ~ 3-4% (will try to also run in a quieter env)

**Comment by kimishpatel** [comment]
> > > Hm, 8% sounds like a lot, is it already with the optimizations applied?
> > 
> > 
> > We have started seeing this in mobile as well. Particularly on mobile with smaller models where op runtime is relatively smaller than on server side, it seems the overhead of profiling is high. _some_ of which I presume is coming from RECORD_FUNCTION callbacks. Have you tried benchmarking this on smaller models, say mobilenetV2? Although running that model on server is not fair since AVX2/AVX512 capabilities provide 2 to 4x vectorized speedup compared to what is available on mobile. But it may give some hint as to the overhead when model is smaller.
> 
> Kimish, do you mean specifically profiling? then yes it's known to have a larger overhead, in this benchmark I benchmark only record function itself (observer api, observers are empty in this benchmark), the latest runs show an overhead of ~ 3-4% (will try to also run in a quieter env)

Yes, I meant overall profiling. Particularly in lite interpreter if we do operator level profiling there is a lot of overhead, so for for network latency reporting we gonna disable that in report the latency.

**Pull request closed without merging**
