### PR TITLE
Create torch.func, add APIs from torch._functorch.eager_transforms

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #90577
* __->__ #90331

This PR creates the torch.func APIs (grad, grad_and_value, vjp, jvp,
jacfwd, jacrev, hessian, functionalize). vmap is coming next, that one
is a bit special.

The APIs are a thin wrapper around the implementation of the APIs in
torch._functorch.eager_transforms + documentation. This is to satisfy
PyTorch public API rules: if we just imported grad from
torch._functorch.eager_transforms, the public API rules would complain
that grad is actually 'torch._functorch.eager_transforms.grad' and that
it looks private due to the leading underscore.

The documentation was cut-pasted from their original locations, with
slight modifications:
- I renamed all instances of functorch to torch.func.

This PR also rewires the relevant functorch APIs to call the torch.func
APIs and sets up a barebones torch.func documentation page to make the
public API tests happy. We will improve the torch.func documentation
pages once everything (the function transforms and the nn stateless API)
are moved over.

Test Plan:
- wait for tests
- the torch.func APIs are indirectly tested through the functorch tests
  (it imports the APIs from functorch instead of torch.func and the
  functorch APIs calls the torch.func APIs)

### CODE REVIEW

**Comment by samdow** [comment]
You're probably iterating on this but wanted to flag that this is what I'm seeing from the preview docs built

**This PR**, in torch.func:
Screen Shot 2022-12-12 at 4 56 14 PM

Previously, in **functorch docs**:
Screen Shot 2022-12-12 at 4 57 10 PM

**Comment by zou3519** [comment]
> You're probably iterating on this but wanted to flag that this is what I'm seeing from the preview docs built

I intentionally made that specific change, but can reverse it if we don't like it

**Comment by zou3519** [comment]
> Ah--I guess I'm not a huge fan since none of the other docs have it (torch only shows the function name and not its args) but I don't feel too strongly to since there's an argument that these can be different since they're function transforms unlike the other pytorch functions

Let's remove it then for consistency, thanks for pointing that out

**Comment by zou3519** [comment]
closing in favor of stack over at https://github.com/pytorch/pytorch/pull/91015

**Pull request closed without merging**
