### PR TITLE
[mergebot] add additional checks

### PR DESCRIPTION
**Pull request by zengk95**
We're adding 2 additional checks:
1. If the user has pushed any additional updates to a PR while we're busy waiting. 
2. If the user's PR is greater than 3 days old (I think this is the limit on phabricator is the same) we don't let them merge (unless force pushing). Maybe this can be extended to 5 or 7 day if we get a lot of negative feedback.

Check that the script still runs with these additional checks using dry run

image

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Comment by zengk95** [comment]
@pytrochbot merge

**Review by seemethere — APPROVED** [review]

**Review by janeyx99 — COMMENTED** [review]
did you delete gql_mocks.json before rerunning the tests to generate? it seems there are a lot of added lines to the file instead of replacements

**Comment by malfet** [comment]
Two post-land remarks:
 - This broke co-development workflow, can we somehow test this before regression happens?
 - We should probably give a more actionable feedback (i.e. suggest a command to do rebase)

**Pull request closed without merging**
