### PR TITLE
Add a pass that reconstructs scopes for nodes from their inline callstacks.

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#29921 Add a pass that reconstructs scopes for nodes from their inline callstacks.**
* #29911 Show full call stack in TorchScript exception even when calls were inlined.
* #27922 Add logging to inliner.
* #27921 Add InlinedCallStack class.
* #27920 Make inlineCallTo to take Function instead of Graph as the callee argument.
* #27919 Add a variant of insertGraph that fills values map.

Summary:
This is a temporary solution for current users of scopes. Eventually we
should just stop using them and use callstacks or modules structure
directly when it's needed.

Differential Revision: [D18538818](https://our.internmc.facebook.com/intern/diff/D18538818)

### CODE REVIEW

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit 1a2924a:
* **6/6** failures introduced in this PR
* **0/6** recognized as flaky



Here are the [reasons each build failed](https://dr.pytorch.org/commit-details.html?sha1=1a2924a2475f7fb7f824c1be582b5c20cbee4b8d):

| Job | Step | Log excerpt |
| --- | --- | --- |
| caffe2_onnx_py3_6_clang7_ubuntu16_04_build | Build | `/var/lib/jenkins/workspace/torch/csrc/jit/passes/reconstruct_scopes.cpp:1:10: fatal error:` |
| binary_linux_libtorch_2_7m_cpu_gcc5_4_cxx11-abi_shared-with-deps_build | Build | `FAILED: ` |
| binary_linux_libtorch_2_7m_cpu_devtoolset7_shared-with-deps_build | Build | `/pytorch/torch/csrc/jit/passes/reconstruct_scopes.cpp:1:10: fatal error:` |
| binary_linux_manywheel_2_7mu_cpu_devtoolset7_build | Build | `/pytorch/torch/csrc/jit/passes/reconstruct_scopes.cpp:1:10: fatal error:` |
| pytorch_xla_linux_xenial_py3_6_clang7_build | Build | `/var/lib/jenkins/workspace/torch/csrc/jit/passes/reconstruct_scopes.cpp:1:10: fatal error:` |
| caffe2_onnx_py2_gcc5_ubuntu16_04_build | Build | `/var/lib/jenkins/workspace/torch/csrc/jit/passes/reconstruct_scopes.cpp:1:54: fatal error:` |


---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Comment by jamesr66a** [comment]
Is this still needed?

**Comment by ZolotukhinM** [comment]
I don't think so, but I'll keep it here for a while just in case :)

**Comment by suo** [comment]
Spring cleaning my review queue. Feel free to re-request if you want me to take another look.

**Pull request closed without merging**
