### PR TITLE
[ROCm] Enable test_multiprocessing tests

### PR DESCRIPTION
**Pull request by jaglinux**
Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>

Issue fixed in ROCm 5.2 user space.

### CODE REVIEW

**Comment by jaglinux** [comment]
cc @jithunnair-amd @jeffdaily @pruthvistony @arindamroy-eng

**Review by jeffdaily — APPROVED** [review]
LGTM.  ROCm CI is green.  4 test failures are unrelated to this PR.

We still need upstream approval.

**Review by malfet — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Comment by jaglinux** [comment]
2022-08-17T19:34:08.6449003Z   test_event_handle_exporter (__main__.TestMultiprocessing) ... /opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:123: UserWarning: loaded 39 slow tests
2022-08-17T19:34:08.6449546Z   warnings.warn(f"loaded {len(slow_tests_dict)} slow tests")
2022-08-17T19:34:08.6450211Z /opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:127: UserWarning: loaded 238 disabled tests
2022-08-17T19:34:08.6450760Z   warnings.warn(f"loaded {len(disabled_tests_dict)} disabled tests")
2022-08-17T19:34:12.3298069Z ok (5.001s)
2022-08-17T19:34:13.7041800Z   test_event_handle_importer (__main__.TestMultiprocessing) ... /opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:123: UserWarning: loaded 39 slow tests
2022-08-17T19:34:13.7043275Z   warnings.warn(f"loaded {len(slow_tests_dict)} slow tests")
2022-08-17T19:34:13.7044910Z /opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:127: UserWarning: loaded 238 disabled tests
2022-08-17T19:34:13.7046187Z   warnings.warn(f"loaded {len(disabled_tests_dict)} disabled tests")
2022-08-17T19:34:16.8561133Z ok (4.526s)
2022-08-17T19:34:16.8598343Z   test_event_handle_multi_gpu (__main__.TestMultiprocessing) ... skip: found only 1 GPU (0.004s)
2022-08-17T19:34:18.2344205Z   test_event_multiprocess (__main__.TestMultiprocessing) ... /opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:123: UserWarning: loaded 39 slow tests
2022-08-17T19:34:18.2345403Z   warnings.warn(f"loaded {len(slow_tests_dict)} slow tests")
2022-08-17T19:34:18.2346859Z /opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:127: UserWarning: loaded 238 disabled tests
2022-08-17T19:34:18.2348050Z   warnings.warn(f"loaded {len(disabled_tests_dict)} disabled tests")
2022-08-17T19:34:20.7152070Z ok (3.855s)

cc @jithunnair-amd

**Comment by jaglinux** [comment]
I see 4 failing checks in the report

Below 3 jobs are failing due at "Install nvidia driver" step
linux-bionic-cuda10.2-py3.9-gcc7 / test (distributed, 1, 2, linux.8xlarge.nvidia.gpu)
linux-bionic-cuda10.2-py3.9-gcc7 / test (distributed, 2, 2, linux.8xlarge.nvidia.gpu)
linux-bionic-cuda10.2-py3.9-gcc7 / test (multigpu, 1, 1, linux.16xlarge.nvidia.gpu)

macos-12-py3-x86-64 / test (default, 2, 2, macos-12) --> The hosted runner: GitHub Actions 50 lost communication with the 
server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

I do not see ROCm related failures.

**Pull request closed without merging**
