### PR TITLE
Add from_blob with storage_offset arg

### PR DESCRIPTION
**Pull request by JacobSzwejbka**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #78217

Seperated out from other diff to better comply with github first

Differential Revision: [D36644764](https://our.internmc.facebook.com/intern/diff/D36644764/)

### CODE REVIEW

**Review by dhruvbird — APPROVED** [review]

**Review by larryliu0820 — APPROVED** [review]
LGTM

**Comment by vadimkantorov** [comment]
It would also be nice to expose this to Python: https://github.com/pytorch/pytorch/issues/34646

**Pull request closed without merging**
