### PR TITLE
Move function definitions from LinearAlgebraUtils.h to LinearAlgebraUtils.cpp

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70253
* #69827
* #69826
* #69825
* __->__ #69824

Out of probably laziness, we had not split LinearAlgebraUtils.h into a
header and a `.cpp` file. Instead, all the functions were defined as
static inline.

This is not a good practice in general, but also, it disallows to use
generated headers that should not be included in headers, such as
`ATen/cuda/CUDAConfig.h`, which states:

> // NB: This header MUST NOT be included from other headers; it should
> // only be included from C++ files.

This PR moves the definition of the functions into `LinearAlgebraUtils.cpp`. ~~to be able to include in the `.cpp` file the `CUDAConfig.h` header safely in a later PR in this stack.~~

It so happens that I did not need to use the `CUDAConfig.h` file in the
next PR of the stack. As such, this PR is not strictily necessary, but
I think it's worth it regardless.

I needed to sprinkle a few TORCH_API decorators on the functions that
are used both on cpu and cuda builds. If you ever encounter a linker
error when using a function from `LinearAlgebraUtils.h`, stamp its
definition with a `TORCH_API` and that should solve it @nikitaved
@IvanYashchuk

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

Differential Revision: [D33202688](https://our.internmc.facebook.com/intern/diff/D33202688)

### CODE REVIEW

**Review by IvanYashchuk — APPROVED** [review]

**Review by mruberry — APPROVED** [review]
Stamped!

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33202688).

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33202688).

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33202688).

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33202688).

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33202688).

**Comment by mruberry** [comment]
Still getting some internal failures -- I'll have to take a closer look.

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33202688).

**Comment by Lezcano** [comment]
Closing, as it's not clear how to fix these errors in mobile: https://github.com/pytorch/pytorch/pull/69826#issuecomment-1009458627

**Pull request closed without merging**
