### PR TITLE
add test_c10d_spawn_ucc.py

### PR DESCRIPTION
**Pull request by Fuzzkatt**
Initial PR to create UCC equivalent of https://github.com/pytorch/pytorch/blob/master/test/distributed/test_c10d_spawn_gloo.py and 
https://github.com/pytorch/pytorch/blob/master/test/distributed/test_c10d_spawn_nccl.py. Currently only added common ops. 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

### CODE REVIEW

**Comment by Fuzzkatt** [comment]
Hi, @kwen2501 @kingchc could you take a look at this PR? The failing workflow seems to be unrelated.

**Review by kwen2501 — APPROVED** [review]
Thanks for adding the test. Is this test enabled somewhere?

**Pull request closed without merging**
