### PR TITLE
Clean up Docker config on ROCm runner

### PR DESCRIPTION
**Pull request by huydhn**
This fixes the issues on trunk when logging in to ECR on ROCm runner is failing.  During my test, it's also ok to fail the login part with that `not implemented` error https://github.com/pytorch/pytorch/actions/runs/7516446579/job/20461801473, and pulling the image from ECR still works, so I set `continue-on-error: true` on the step.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by jithunnair-amd — COMMENTED** [review]
@huydhn Looks good, if it's safer to always have the "Remove leftover Docker config file" in the yml file from now on. Otherwise, I think we can manually update the setup on all our ROCm CI runners and then we shouldn't need this PR? 
The `continue-on-error` part here: https://github.com/pytorch/pytorch/pull/117432/files#diff-9cee6b6f9120074aa365bf22d3442c12d27b727bd2f408dbb9c6c820965f8c31R77 worries me since it might mask other issues?

**Comment by jithunnair-amd** [comment]
cc @amdfaa

**Review by malfet — APPROVED** [review]

**Comment by huydhn** [comment]
> @huydhn Looks good, if it's safer to always have the "Remove leftover Docker config file" in the yml file from now on. Otherwise, I think we can manually update the setup on all our ROCm CI runners and then we shouldn't need this PR? The `continue-on-error` part here: https://github.com/pytorch/pytorch/pull/117432/files#diff-9cee6b6f9120074aa365bf22d3442c12d27b727bd2f408dbb9c6c820965f8c31R77 worries me since it might mask other issues?

I think I could land this to fix trunk first.  From what I learn, the present of the file there is optional and it has only one single entry there.  So, it should be safe to do both (land the PR and clean up the file on your end).  Once they are done, I could revert the change manually and see if CI remains fix.

About the `continue-on-error` part, I also think it's ok because being able to pull the Docker image later is all that matter.  Sometimes, the image might already be there locally.  This will make the CI a bit more resilient.  If it couldn't find and pull the image, the pull step right after would fail anyway.

**Pull request closed without merging**
