### PR TITLE
Default TreadPool size to number of physical cores

### PR DESCRIPTION
**Pull request by malfet**
TODO: Some benchmarks

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
I do believe this change is for the better but I'm not an expert and so I cannot ascertain that is _always_ better. @malfet what's the plan on the benchmarks haha

**Comment by Skylion007** [comment]
Will this work properly for partial CPU allocations on SLURM clusters?

**Comment by msaroufim** [comment]
This might be a noop concern but was also curious how a change like this affects the performance of distributed jobs

**Review by Skylion007 — APPROVED** [review]

**Comment by malfet** [comment]
> Will this work properly for partial CPU allocations on SLURM clusters?

I can only hope for it :)

**Comment by Skylion007** [comment]
I'm just worried becaues there might be say 16 logical cores, and only 4 are available to the job meaning that the cores become over-subscribed.

**Comment by janeyx99** [comment]
@Skylion007 that is the exact type of problem we're attempting to fix, as processors usually means threads and cores means actual cores (what we're thinking). @malfet's PR will be strictly an improvement on that front as written compared to before the change.

**Comment by gajjanag** [comment]
LGTM - tested both a hyperthreaded multicore and non hyperthreaded multicore. It gives the correct thread count now.

**Review by gajjanag — APPROVED** [review]

**Review by jgong5 — APPROVED** [review]

**Comment by sanchitintel** [comment]
>  tested both a hyperthreaded multicore and non hyperthreaded multicore. It gives the correct thread count now.

Hi @gajjanag, can you please clarify if you meant you were getting incorrect counts earlier with `torch.get_num_threads`?
For instance, even with HyperThreading enabled on an Intel machine, I only see physical core counts with `torch.get_num_threads` at my end.

Thanks!

**Comment by gajjanag** [comment]
> > tested both a hyperthreaded multicore and non hyperthreaded multicore. It gives the correct thread count now.
> 
> Hi @gajjanag, can you please clarify if you meant you were getting incorrect counts earlier with `torch.get_num_threads`? For instance, even with HyperThreading enabled on an Intel machine, I only see physical core count with `torch.get_num_threads` at my end (without this patch).
> 
> Thanks!

Yes, I was getting incorrect counts before this patch (eg a 2 socket 56 core each Intel was giving 224 thread count, but it now gives the correct 112)

**Comment by sanchitintel** [comment]
Thanks for confirming, @gajjanag!

That hasn't been my experience, with HyperThreading enabled (without this patch) -
image

**Comment by malfet** [comment]
> Thanks for confirming, @gajjanag!
> 
> That hasn't been my experience, with HyperThreading enabled (without this patch) - image

We need to chat about this. Perhaps cpuinfo does not correctly work on your system, but it should have returned number of logical cores rather than physical ones.

**Pull request closed without merging**
