### PR TITLE
register nested tensor linear kernel

### PR DESCRIPTION
**Pull request by drisspg**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #80274
* #80273

### CODE REVIEW

**Comment by drisspg** [comment]
Also as a result of the changes in the base in this ghstack, the @inferenfece_mode() requirement should be able to be removed. i.e.: https://github.com/pytorch/pytorch/blob/f11cce309bf290151a21b2ac8e79bf2a24dcf2f3/test/test_nestedtensor.py#L483

Before these changes even though a nested_tensor kernel was registered to the op, if a composite implicit version was present in dispatch table this would take precedence in the dispatch table causing the wrong kernel to be called.  I created this issue to track the work of removing: https://github.com/pytorch/pytorch/issues/80287

**Review by cpuhrsch — APPROVED** [review]
Awesome!

**Review by bdhirsh — APPROVED** [review]
lgtm :)

**Pull request closed without merging**
