### PR TITLE
Move Dynamo docs back to core

### PR DESCRIPTION
**Pull request by msaroufim**
With contributions from @svekars and @malfet 

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

Waiting for doc build job to complete

### CODE REVIEW

**Comment by msaroufim** [comment]
@albanD @seemethere I'm getting the below error

Your PR is 2168 LOC which is more than the 2000 maximum
allowed within PyTorch infra. PLease make sure to split up
your PR into smaller pieces that can be reviewed.
If you think that this rule should not apply to your PR,
please contact @albanD or @seemethere.

I think we can relax this constraint since this a big doc dump

**Review by soumith — APPROVED** [review]

**Comment by msaroufim** [comment]
On the lint issues, they were all fixed except for this guy

Not sure what to do with this

```
error:        Two different linters proposed changes for the same file:
                           /home/ubuntu/pytorch/docs/source/dynamo/faq.rst.
        This is not yet supported, file an issue if you want it.
```

**Comment by davidberard98** [comment]
re: >2000 LOC you can add `skip-pr-sanity-checks` label

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
