### PR TITLE
[Profiler] Expose extra fields to Python

### PR DESCRIPTION
**Pull request by robieta**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #79623

Pybind11 has a really awesome feature where you can tell it how to move a type from C++ to Python just by specializing one template and it has out of the box support for variant types. (You do have to make one change to variant to avoid a bunch of chatty compiler warnings.) This will make it easy to both:
A) Write principled type driven analysis in Python similar to `c10::visit`
B) Expose fields that only make sense for certain events without cluttering up the API of the top level events.

For now I haven't added any fields; this PR is just to handle the foundation.

Differential Revision: [D36988611](https://our.internmc.facebook.com/intern/diff/D36988611/)

### CODE REVIEW

**Review by aaronenyeshi — APPROVED** [review]

**Comment by robieta** [comment]
@robieta has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36988611).

**Comment by robieta** [comment]
@robieta has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36988611).

**Comment by robieta** [comment]
Interesting wrinkle: tensorexpr is already binding a variant but as a custom class so we have to define a type caster for `torch::jit::tensorexpr::ArgValue` to make it go to the base type caster. CC @ZolotukhinM just because it's kind of funny.

**Pull request closed without merging**
