### PR TITLE
Back out "Back out "[pytorch][PR] Move thnvrtc and DynamicLibrary to ATen""

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#22794 Back out "Back out "[pytorch][PR] Move thnvrtc and DynamicLibrary to ATen""**

Original commit changeset: 227df3b85316

Differential Revision: [D16222777](https://our.internmc.facebook.com/intern/diff/D16222777/)

### CODE REVIEW

**Comment by ezyang** [comment]
This is the same as the original commit, but this time there's an internal change that sets the macro correctly.

**Review by ssnl — APPROVED** [review]
Thank you so much!!!!

**Comment by ezyang** [comment]
@SsnL We're not quite out of the woods yet. Now there is some sort of destructor ordering problem:

```
#0  0x00007fffd9d01901 in at::Context::getNVRTC (this=0x7fff9d48b3b0 <at::globalContext()::globalContext_>) at caffe2/aten/src
/ATen/Context.h:81
#1  0x00007fffd9cfd001 in torch::jit::fuser::cuda::nvrtc () at caffe2/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:28
#2  0x00007fffd9d00ef7 in torch::jit::fuser::cuda::FusedKernelCUDA::~FusedKernelCUDA (this=0x7fff6599aa10) at caffe2/torch/csr
c/jit/fuser/cuda/fused_kernel.cpp:197
#3  0x00007fffd9d04684 in __gnu_cxx::new_allocator<torch::jit::fuser::cuda::FusedKernelCUDA>::destroy<torch::jit::fuser::cuda:
:FusedKernelCUDA> (this=0x7fff6599aa10, __p=0x7fff6599aa10) at ./third-party-buck/platform007/build/libgcc/include/c++/7.3.0/e
xt/new_allocator.h:157
```

**Comment by ezyang** [comment]
Purposely leaking the CUDA hooks singleton works:

```
diff --git a/fbcode/caffe2/aten/src/ATen/detail/CUDAHooksInterface.cpp b/fbcode/caffe2/aten/src/ATen/detail/CUDAHooksInterface
.cpp
--- a/fbcode/caffe2/aten/src/ATen/detail/CUDAHooksInterface.cpp
+++ b/fbcode/caffe2/aten/src/ATen/detail/CUDAHooksInterface.cpp
@@ -10,7 +10,7 @@
 
 const CUDAHooksInte
                    rface& getCUDAHooks() {
-  static std::unique_ptr<CUDAHooksInterface> cuda_hooks;
+  static CUDAHooksInterface* cuda_hooks;
   // NB: The once_flag here implies that if you try to call any CUDA
   // functionality before libATen_cuda.so is loaded, CUDA is permanently
   // disabled for that copy of ATen.  In principle, we can relax this
@@ -20,10 +20,9 @@
   // safe...)
   static std::once_flag once;
   std::call_once(once, [] {
-    cuda_hooks = CUDAHooksRegistry()->Create("CUDAHooks", CUDAHooksArgs{});
+    cuda_hooks = CUDAHooksRegistry()->Create("CUDAHooks", CUDAHooksArgs{}).release();
     if (!cuda_hooks) {
-      cuda_hooks =
-          std::unique_ptr<CUDAHooksInterface>(new CUDAHooksInterface());
+      cuda_hooks = new CUDAHooksInterface();
     }
   });
   return *cuda_hooks;
```

**Comment by ezyang** [comment]
Hmm, if I explicitly define a destructor for CUDA hooks the problem goes away. Let's try that.

**Comment by ezyang** [comment]
So, here's what I think is happening.

The CUDA hooks singleton is a Meyer's singleton, which means that it is guaranteed to be destructed after all other Meyer's singletons which are constructed after this. The segfault occurs in FusedKernelCUDA. This implies that FusedKernelCUDA is part of a singleton which was constructed before the CUDA hooks singleton. I observe that this problem only occurs if I first run some CPU JIT code. So it must be the kernel cache, which is I guess is shared between CPU and CUDA, is constructed before we initialize CUDA, leading to the segfault.

**Comment by ezyang** [comment]
OK, here's the bottom of the backtrace:

```
#26 0x00007fffd8a36955 in std::unordered_map<long, torch::jit::fuser::KernelSpec, std::hash<long>, std::equal_to<long>, std::allocator<std::pair<long const, torch::jit::fuser::KernelSpec> > >::~unordered_map (this=0x7fffd94f7040 <torch::jit::fuser::getKernelCache()::cache+48>) at ./third-party-buck/platform007/build/libgcc/include/c++/7.3.0/bits/unordered_map.h:101
#27 0x00007fffd8a366f3 in torch::jit::fuser::KernelCacheImpl::~KernelCacheImpl (this=0x7fffd94f7010 <torch::jit::fuser::getKernelCache()::cache>) at caffe2/torch/csrc/jit/fuser/kernel_cache.cpp:13
#28 0x00007ffff68cc83a in __run_exit_handlers (status=0, listp=0x7ffff6c616f8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:83
```

**Comment by SsnL** [comment]
@ezyang I see. Thanks for the investigation and analysis. So, if I understand, the easiest solution is to initialize CUDA hooks before the creating cache, e.g., writing some weird code in `KernelCache` ctor like `at::detail::getCUDAHooks()`, which feels kinda hacky. Maybe separating CPU and CUDA caches, and lazy init the CUDA one is better since CUDA for sure is initialized when we need the CUDA kernel cache.

**Comment by ezyang** [comment]
My current plan is to just leak the CUDA hooks object--it's really small so even if it's a real leak it's relatively benign. Separating the CPU and CUDA caches seems pretty involved and if someone ever designs another global variable that has similar properties we'll have this run around again.

**Comment by SsnL** [comment]
That SGTM. Thanks!

**Review by ssnl — APPROVED** [review]

**Comment by SsnL** [comment]
Thank you!!!

**Pull request closed without merging**
