### PR TITLE
Describe the 'float32_matmul_precision' settings in more detail

### PR DESCRIPTION
**Pull request by kalekundert**
The documentation for `torch.set_float32_matmul_precision()` mentions a datatype called "bfloat16_3x".  This doesn't appear to be a very standard term, and I had a hard time figuring out what exactly it meant.  I now assume it refers to [[Henry2019]](http://arxiv.org/abs/1904.06376), which describes an algorithm by which a float32 multiplication is approximated via three bfloat16 multiplications.  This PR updates the documentation to include this reference and to briefly describe how this algorithm works.

Note that I just learned everything that I wrote here, so I'd appreciate if someone more expert in this topic could check to make sure that I didn't get anything significantly wrong.

### CODE REVIEW

**Comment by kalekundert** [comment]
Also, one thing I don't understand is that would happen in "high" precision mode on a GPU with support for both TensorFloat32 and "bfloat16_3x" (if any such GPUs exist).  Which would be used by default?  Is there a way for the user to request one over the other?  It seems like a choice that could matter, since the two options definitely differ in terms of precision.

If anyone knows the answer to this, I'd be happy to incorporate it into the documentation as well.

**Comment by colesbury** [comment]
@kalekundert, the docs build [failed](https://github.com/pytorch/pytorch/actions/runs/5860887593/job/15892658932?pr=107169) with the error "WARNING: citation not found: Henry2019"

**Comment by kalekundert** [comment]
My bad, should be fixed now.

**Review by colesbury — APPROVED** [review]

**Pull request closed without merging**
