### PR TITLE
[decomp] Don't call other decomps directly in upsample decomps

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #107614
* #107640
* __->__ #107526

Inductor has lowerings for some of the `aten.upsample_{mode}.default` overloads,
but they never get used since they go through these CompositeImplict registered
decompositions instead, which never call the underlying overload.

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
All these are already compositeimplicit in core, so perhaps we can even remove / don't register the decompositions?

**Comment by peterbell10** [comment]
The C++ composites don't support SymInt. I suppose we could fix it in C++ instead though.

**Review by lezcano — APPROVED** [review]
Either of the two approaches works for me. Perhaps the C++ approach may be slightly better as to have just one source of truth, but yeah, either works.

**Comment by peterbell10** [comment]
Unfortunately this doesn't do anything because the functions are all registered as `DispatchKey.Autograd`, meaning it's impossible to not decompose them.

It would be nice if we could generate backward decompositions automatically without needing to register the decomposition as the autograd dispatch, that way you could enable or disable them independently. But not sure it's work the effort right now.

**Pull request closed without merging**
