### PR TITLE
Added forward derivatives for neg, diag, inverse, linalg_eig

### PR DESCRIPTION
**Pull request by mattarroz**
See also discussion in #10223, starting from [this](https://github.com/pytorch/pytorch/issues/10223#issuecomment-949499666) comment

The formulas for the derivatives are taken from https://people.maths.ox.ac.uk/gilesm/files/NA-08-01.pdf.

As indicated, the method linalg_eig_jvp should be used instead of linalg_eig_jvp_eigenvalues and linalg_eig_jvp_eigenvectors in the future. Due to a codegen limitation, this is not yet possible.

CC @albanD @Lezcano

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
This looks good.
Can you please add tests for each of them? They all have OpInfo I think so you need to add the proper flags in `common_methods_invocation.py`

**Review by albanD — COMMENTED** [review]
There is a unary info for neg: https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_methods_invocations.py#L9529-L9533

I think you need to skip the test for linalg due to https://github.com/pytorch/pytorch/issues/67367 right now...

**Comment by mattarroz** [comment]
> There is a unary info for neg: https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_methods_invocations.py#L9529-L9533

Done. 

> 
> I think you need to skip the test for linalg due to #67367 right now...

By skipping the test for linalg_eig you mean removing the corresponding `supports_forward_ad=True ` flag? Removing it did not help fixing the error from `python test/test_ops.py -v --import-slow-tests --import-disabled-tests -k test_forward_mode_AD_linalg_eig` on my machine. I ran `python setup.py build` and `python setup.py install` after removing the flag but before running the tests, is there something else I should have done? Should we not wait until  #67367 is fixed, or will it take some time?

**Comment by albanD** [comment]
No you can actually skip it altogether: https://github.com/pytorch/pytorch/blob/cd51d2a3ecc8ac579bee910f6bafe41a4c41ca80/torch/testing/_internal/common_methods_invocations.py#L8425-L8428
If you just set the flag to false, it will try to make sure that it is indeed not implemented but that won't work either.

**Comment by mattarroz** [comment]
>  No you can actually skip it altogether: 

Done. It seems like `linalg_eigvals` had the same problem, so I disabled it too. I hope that's ok.

There were at least two more problems when I ran the tests. One possibly unrelated failure is `test_forward_mode_AD_corrcoef_cpu_float64`.

The other (`test_forward_mode_AD_diag_cpu_float64`) was probably my fault. The error was `The size of tensor a (3) must match the size of tensor b (5) at non-singleton dimension 1`. Maybe it worked in my example because I used a square matrix, but I guess `auto_linear` and not `auto_elementwise` is the correct entry in `derivatives.yaml`. I changed it and the test it now says 
```
test_forward_mode_AD_diag_cpu_complex128 (__main__.TestGradientsCPU) ... ok
test_forward_mode_AD_diag_cpu_float64 (__main__.TestGradientsCPU) ... ok
```

**Review by albanD — COMMENTED** [review]
That looks good, thanks for the update!
It is too bad the `eig` formula cannot be tested here. But I'll try to fix that soon.

**Review by albanD — APPROVED** [review]

**Comment by albanD** [comment]
I didn't realise that the CI was still broken on the latest version. Could you open a new PR from your branch fix a fix for the CI please?

**Pull request closed without merging**
