### PR TITLE
Bump maxinum num warps

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #132458

Fix for https://github.com/pytorch/pytorch/issues/129104

Our heuristic for num_warps was giving the optimal number, but we were capping maximum num_warps at 8. Gives 1% speedup on HF and TIMM in inference, 2% speedup in TIMM training, neutral otherwise.

ultimately, I think we want live var analysis for register usage.. still worth landing this now.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by Chillee — APPROVED** [review]

**Review by shunting314 — APPROVED** [review]
Share the perf test link?

**Comment by eellison** [comment]
@shunting314 https://hud.pytorch.org/benchmark/compilers?dashboard=torchinductor&startTime=Wed%2C%2031%20Jul%202024%2020%3A36%3A15%20GMT&stopTime=Wed%2C%2007%20Aug%202024%2020%3A36%3A15%20GMT&granularity=hour&suite=torchbench&mode=inference&dtype=bfloat16&deviceName=cuda%20(a100)&lBranch=gh/eellison/685/head&lCommit=854fd29f09f32a3cd08371a3d326537bd5a8d6d5&rBranch=main&rCommit=55b0c39d82888ce3a093e434fb3e4acb447f9bf0

**Pull request closed without merging**
