### PR TITLE
Improve namespace for `c10::MemoryFormat::Contiguous` in `torchgen/api/cpp.py`

### PR DESCRIPTION
**Pull request by shink**
Top-level namespaces are more convenient for out-of-tree device extensions.

For example, now we have a patch for it in `torch_npu`:

https://github.com/Ascend/pytorch/blob/98c50ced165964732f0316dcb6cdd68b2452f49d/codegen/gen_backend_stubs.py#L772-L778

```python
JIT_TO_CPP_DEFAULT["contiguous_format"] = "c10::MemoryFormat::Contiguous"
```

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Comment by shink** [comment]
@zou3519 Thanks for your review. I fixed related errors, please take a look.

**Pull request closed without merging**
