### PR TITLE
Check tensors are defined before attempting to access their impl

### PR DESCRIPTION
**Pull request by Anstow**

### CODE REVIEW

**Comment by albanD** [comment]
I'm very curious when you encountered this case. It should be impossible to have a python binding for an undefined Tensor...

**Comment by Anstow** [comment]
I've got another PR that I'm preparing to fix that that issue. I'm just working on a reproducer I can make public now.

A rough outline of the problem is here https://pytorch.slack.com/archives/C3PDTEV8E/p1689087070493829. I'll copy the message bellow:

> I think there is a bug in how python decompositions are called from c++. When an operation is intercepted in the c++ code in pytorch the outputs a created as ExclusivelyOwned<at::Tensor>s. Later on when it dispatches back to python for the decomposition these tensors have their ownership shared with python. In a normal use case the exclusively owned tensor is released and it's value returned as a non-exclusively owned tensor from the operation. However if the python decomposition throws an error the ExclusivelyOwned wrapper destroys the at::Tensor leading to a python reference to a tensor which isn't alive (and meaning pytorch falls over in debug mode). I can see two potential fixes for this:
> Attempt to destroy any tensors in python when returning from a decomposition wrapper (I don't actually know how to do this)
> Get rid of the ExclusivelyOwned wrapper for outputs in pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp (perhaps there are other places this would need to be done too)
> I think that 2 is probably a better solution since it will only slow down the error path and will lead to more pythonic behaviour in the decompositions. What would be preferred by the dev team? Is there something I've missed? Is this even the right place to ask the question?

**Comment by Anstow** [comment]
The issue for bug that gave me undefined tensors is  #106790

**Comment by Anstow** [comment]
@albanD What's going on with the PR review? I feel like this is a good change to have in case there are more issues with the python bindings

**Comment by albanD** [comment]
Didn't solve the problem at hand: https://github.com/pytorch/pytorch/pull/106791 ?

The change made by this PR is pretty subtle. It would take some time to look into exactly what is the impact of this. So trying to see if we really need it and why!

**Comment by Anstow** [comment]
I don't think it's as complicated as you're making it out to be. Although I could be wrong. `unsafeTensorImpl()` has a pre-condition that the tensor is defined. The calling function is already trying to handle the case where the tensor isn't defined with that check. I'm just moving the check somewhere where it won't read/write random memory before the check.Whether that is a good idea is an entirely separate matter which I agree is more subtle and would require extra thought to remove.

**Review by albanD — COMMENTED** [review]
Ok from looking more closely that should be fine. 
Just thing about moving the comment around and we can merge it.

**Review by albanD — APPROVED** [review]
Thanks!
And sorry for the delay in looking into this

**Pull request closed without merging**
