### PR TITLE
[MPS] Allocate an empty tensor instead of gathering data if output is not contiguous

### PR DESCRIPTION
**Pull request by DenisVieriu97**
Speeds up binary ops

### CODE REVIEW

**Review by kulinseth — APPROVED** [review]

**Comment by kit1980** [comment]
The test is failing with "no member named 'empty_mps' in namespace 'at::native'" - https://github.com/pytorch/pytorch/actions/runs/5282719638/jobs/9557993638?pr=103694

**Comment by DenisVieriu97** [comment]
> The test is failing with "no member named 'empty_mps' in namespace 'at::native'" - https://github.com/pytorch/pytorch/actions/runs/5282719638/jobs/9557993638?pr=103694

Thanks @kit1980 - fixed now.

**Pull request closed without merging**
