### PR TITLE
PR for double backwards of nn.Fold and nn.Unfold  (issue #33452)

### PR DESCRIPTION
**Pull request by musikisomorphie**
@soumith @ezyang @albanD  After lots of experiments, I didn't manage to directly print the gradients of Fold/Unfold_backward (let me know if I am wrong).
Thus, in my testing codes, I compare the gradients of Fold/Unfold_backward implicitly by comparing the gradients of its following operation.

### CODE REVIEW

**Comment by ezyang** [comment]
Thanks, the code change looks great.

I'm looking at your test and I don't see any use of `gradgradcheck` here; that would have been the most straightforward way to test the double backwards. Is there a reason you didn't use it in this case?

**Comment by musikisomorphie** [comment]
> Thanks, the code change looks great.
> 
> I'm looking at your test and I don't see any use of `gradgradcheck` here; that would have been the most straightforward way to test the double backwards. Is there a reason you didn't use it in this case?

Thank you for your review, @ezyang. Your suggestion sounds great, I changed my testing code accordingly.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
SIMPLE AND CLEAAAAAN

Paging @ailzhang @dlibenzi , XLA doesn't know how to deal with this:

```
Apr 15 10:02:07 ======================================================================
Apr 15 10:02:07 ERROR [5188.726s]: test_fold_xla (__main__.TestNNDeviceTypeXLA)
Apr 15 10:02:07 ----------------------------------------------------------------------
Apr 15 10:02:07 Traceback (most recent call last):
Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
Apr 15 10:02:07     return test(self, device_arg)
Apr 15 10:02:07   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 10913, in test_fold
Apr 15 10:02:07     gradcheck(func, [x])
Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 332, in gradcheck
Apr 15 10:02:07     if gi.type() != i.type():
Apr 15 10:02:07 RuntimeError: Unimplemented backend XLA
Apr 15 10:02:07 
Apr 15 10:02:07 ======================================================================
Apr 15 10:02:07 ERROR [77.898s]: test_unfold_xla (__main__.TestNNDeviceTypeXLA)
Apr 15 10:02:07 ----------------------------------------------------------------------
Apr 15 10:02:07 Traceback (most recent call last):
Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
Apr 15 10:02:07     return test(self, device_arg)
Apr 15 10:02:07   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 10903, in test_unfold
Apr 15 10:02:07     gradcheck(func, [x])
Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 332, in gradcheck
Apr 15 10:02:07     if gi.type() != i.type():
Apr 15 10:02:07 RuntimeError: Unimplemented backend XLA
Apr 15 10:02:07 
```

**Comment by dlibenzi** [comment]
> SIMPLE AND CLEAAAAAN
> 
> Paging @ailzhang @dlibenzi , XLA doesn't know how to deal with this:
> 
> ```
> Apr 15 10:02:07 ======================================================================
> Apr 15 10:02:07 ERROR [5188.726s]: test_fold_xla (__main__.TestNNDeviceTypeXLA)
> Apr 15 10:02:07 ----------------------------------------------------------------------
> Apr 15 10:02:07 Traceback (most recent call last):
> Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
> Apr 15 10:02:07     return test(self, device_arg)
> Apr 15 10:02:07   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 10913, in test_fold
> Apr 15 10:02:07     gradcheck(func, [x])
> Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 332, in gradcheck
> Apr 15 10:02:07     if gi.type() != i.type():
> Apr 15 10:02:07 RuntimeError: Unimplemented backend XLA
> Apr 15 10:02:07 
> Apr 15 10:02:07 ======================================================================
> Apr 15 10:02:07 ERROR [77.898s]: test_unfold_xla (__main__.TestNNDeviceTypeXLA)
> Apr 15 10:02:07 ----------------------------------------------------------------------
> Apr 15 10:02:07 Traceback (most recent call last):
> Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
> Apr 15 10:02:07     return test(self, device_arg)
> Apr 15 10:02:07   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 10903, in test_unfold
> Apr 15 10:02:07     gradcheck(func, [x])
> Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 332, in gradcheck
> Apr 15 10:02:07     if gi.type() != i.type():
> Apr 15 10:02:07 RuntimeError: Unimplemented backend XLA
> Apr 15 10:02:07 
> ```

If I am not mistaken @ailzhang had a PR for that already, in her attempt to import other tests.
IIRC:

`if gi.type() != i.type():` -> `if gi.dtype != i.dtype:`

**Comment by dlibenzi** [comment]
> > SIMPLE AND CLEAAAAAN
> > Paging @ailzhang @dlibenzi , XLA doesn't know how to deal with this:
> > ```
> > Apr 15 10:02:07 ======================================================================
> > Apr 15 10:02:07 ERROR [5188.726s]: test_fold_xla (__main__.TestNNDeviceTypeXLA)
> > Apr 15 10:02:07 ----------------------------------------------------------------------
> > Apr 15 10:02:07 Traceback (most recent call last):
> > Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
> > Apr 15 10:02:07     return test(self, device_arg)
> > Apr 15 10:02:07   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 10913, in test_fold
> > Apr 15 10:02:07     gradcheck(func, [x])
> > Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 332, in gradcheck
> > Apr 15 10:02:07     if gi.type() != i.type():
> > Apr 15 10:02:07 RuntimeError: Unimplemented backend XLA
> > Apr 15 10:02:07 
> > Apr 15 10:02:07 ======================================================================
> > Apr 15 10:02:07 ERROR [77.898s]: test_unfold_xla (__main__.TestNNDeviceTypeXLA)
> > Apr 15 10:02:07 ----------------------------------------------------------------------
> > Apr 15 10:02:07 Traceback (most recent call last):
> > Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
> > Apr 15 10:02:07     return test(self, device_arg)
> > Apr 15 10:02:07   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 10903, in test_unfold
> > Apr 15 10:02:07     gradcheck(func, [x])
> > Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 332, in gradcheck
> > Apr 15 10:02:07     if gi.type() != i.type():
> > Apr 15 10:02:07 RuntimeError: Unimplemented backend XLA
> > Apr 15 10:02:07 
> > ```
> 
> If I am not mistaken @ailzhang had a PR for that already, in her attempt to import other tests.
> IIRC:
> 
> `if gi.type() != i.type():` -> `if gi.dtype != i.dtype:`

Ohh, the grads check.
We need to disable these tests as currently the grads check is hyper expensive done in the way it is done today, for XLA.
@ailzhang will be working on it, but for now, we can disable the tests.

**Comment by dlibenzi** [comment]
https://github.com/pytorch/xla/pull/1918

**Comment by musikisomorphie** [comment]
> SIMPLE AND CLEAAAAAN
> 
> Paging @ailzhang @dlibenzi , XLA doesn't know how to deal with this:
> 
> ```
> Apr 15 10:02:07 ======================================================================
> Apr 15 10:02:07 ERROR [5188.726s]: test_fold_xla (__main__.TestNNDeviceTypeXLA)
> Apr 15 10:02:07 ----------------------------------------------------------------------
> Apr 15 10:02:07 Traceback (most recent call last):
> Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
> Apr 15 10:02:07     return test(self, device_arg)
> Apr 15 10:02:07   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 10913, in test_fold
> Apr 15 10:02:07     gradcheck(func, [x])
> Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 332, in gradcheck
> Apr 15 10:02:07     if gi.type() != i.type():
> Apr 15 10:02:07 RuntimeError: Unimplemented backend XLA
> Apr 15 10:02:07 
> Apr 15 10:02:07 ======================================================================
> Apr 15 10:02:07 ERROR [77.898s]: test_unfold_xla (__main__.TestNNDeviceTypeXLA)
> Apr 15 10:02:07 ----------------------------------------------------------------------
> Apr 15 10:02:07 Traceback (most recent call last):
> Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
> Apr 15 10:02:07     return test(self, device_arg)
> Apr 15 10:02:07   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 10903, in test_unfold
> Apr 15 10:02:07     gradcheck(func, [x])
> Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 332, in gradcheck
> Apr 15 10:02:07     if gi.type() != i.type():
> Apr 15 10:02:07 RuntimeError: Unimplemented backend XLA
> Apr 15 10:02:07 
> ```



> SIMPLE AND CLEAAAAAN
> 
> Paging @ailzhang @dlibenzi , XLA doesn't know how to deal with this:
> 
> ```
> Apr 15 10:02:07 ======================================================================
> Apr 15 10:02:07 ERROR [5188.726s]: test_fold_xla (__main__.TestNNDeviceTypeXLA)
> Apr 15 10:02:07 ----------------------------------------------------------------------
> Apr 15 10:02:07 Traceback (most recent call last):
> Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
> Apr 15 10:02:07     return test(self, device_arg)
> Apr 15 10:02:07   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 10913, in test_fold
> Apr 15 10:02:07     gradcheck(func, [x])
> Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 332, in gradcheck
> Apr 15 10:02:07     if gi.type() != i.type():
> Apr 15 10:02:07 RuntimeError: Unimplemented backend XLA
> Apr 15 10:02:07 
> Apr 15 10:02:07 ======================================================================
> Apr 15 10:02:07 ERROR [77.898s]: test_unfold_xla (__main__.TestNNDeviceTypeXLA)
> Apr 15 10:02:07 ----------------------------------------------------------------------
> Apr 15 10:02:07 Traceback (most recent call last):
> Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
> Apr 15 10:02:07     return test(self, device_arg)
> Apr 15 10:02:07   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 10903, in test_unfold
> Apr 15 10:02:07     gradcheck(func, [x])
> Apr 15 10:02:07   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 332, in gradcheck
> Apr 15 10:02:07     if gi.type() != i.type():
> Apr 15 10:02:07 RuntimeError: Unimplemented backend XLA
> Apr 15 10:02:07 
> ```

Great, thanks for the following work. I may focus on other pytorch issues then.

**Comment by ailzhang** [comment]
Thanks @dlibenzi for unblocking this PR! 
To clarify a bit on tasks I'm working on, there're two things next on my todo list and they're indeed related to the issue triggered here. 
1. `gradcheck` and `gradgradcheck` has huge for-loops which causes XLA to recompile a lot thus runs super slowly. And this is one of the major reasons that we haven't enable XLA running autograd generic tests.(Currently we run this test suite on CPU and CUDA only). I'll explore possible workarounds for XLA to enable autograd tests. 
2. `gradcheck` calls `type()` which is a less preferred way than `dtype/device`. I had a discussion with @gchanan about this, and we agreed that we should replace `type()` with `dtype/device` as much as we can, then move `type()` to an internal only API for a few cases that really needs it, e.g serialization keys. Once that's done we'll discourage users from using `type()` since it's hardcoded https://github.com/pytorch/pytorch/blob/016d73bd74d93f418910c6a4368bca7552bfda7e/torch/csrc/utils/tensor_types.cpp#L18. 
Let me know if you have any concerns on these. :D

**Pull request closed without merging**
