### PR TITLE
TensorImpl:::size_custom to support NestedTensor.size

### PR DESCRIPTION
**Pull request by cpuhrsch**
This allows subclasses such as NestedTensorImpl to provide special behavior for `int64_t size(int64_t d)` that'll also be accessible by our Python frontend.

It follows the same pattern as sizes_custom.

Currently getting CI before asking for a review.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
OK. Having stride work the same way, and having dispatch to Python, seem like obvious next steps

**Comment by eellison** [comment]
This breaks apex multi_tensor_apply. Traceback:
>   File "/scratch/eellison/work/simple_dl_models/huggingface_bert_phase2.py", line 42, in <module>
    final_results += runner.run(sys.argv, 'BertForPreTraining_P2_bert-large-uncased_[seqs=16,seql=512]', BertForPreTraining(config), optim_func, bert_p2_input_func, None)
  File "/scratch/eellison/work/simple_dl_models/execution/runner.py", line 69, in run
    eager_record = execution_loop.execute(args, "eager", model_name, model, optim_func, input_func, grad_func, None)
  File "/scratch/eellison/work/simple_dl_models/execution/execution_loop.py", line 121, in execute
    scaler.step(optimizer)
  File "/scratch/eellison/work/pytorch/torch/cuda/amp/grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/scratch/eellison/work/pytorch/torch/cuda/amp/grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/scratch/eellison/work/pytorch/torch/optim/optimizer.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/scratch/eellison/work/env/lib/python3.9/site-packages/apex/optimizers/fused_adam.py", line 180, in step
    multi_tensor_applier(self.multi_tensor_adam,
  File "/scratch/eellison/work/env/lib/python3.9/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 27, in __call__
    return op(self.chunk_size,
RuntimeError: Tensors of type TensorImpl do not have numel


Repro: 
```
git clone https://github.com/kevinstephano/simple_dl_models.git
cd simple_dl_models
python huggingface_bert_phase2.py --amp
```

**Comment by ezyang** [comment]
How was apex compiled, are you using a prebuilt wheel?

**Comment by cpuhrsch** [comment]
@eellison - the trace indicates the error `RuntimeError: Tensors of type TensorImpl do not have numel`, but this PR didn't introduce any new checks or throws. I don't think it's related.

**Comment by eellison** [comment]
Well, this is what I bisected it to lol

**Pull request closed without merging**
