### PR TITLE
[torch::deploy] remove c10::irange from torch deploy

### PR DESCRIPTION
**Pull request by PaliC**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #74002
* __->__ #73988
* #73526
* #73456

This diff effectively renames `c10::irange` to `multipy::irange` in `torch::deploy` in by creating a copy of `c10::irange` in order to help torch::deploy function without a dependency on `torch`

Differential Revision: [D34768779](https://our.internmc.facebook.com/intern/diff/D34768779)

### CODE REVIEW

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34768779).

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34768779).

**Review by suo — APPROVED** [review]
lg, assuming CI passes

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34768779).

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34768779).

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34768779).

**Pull request closed without merging**
