### PR TITLE
Update cpuinfo to the latest commit

### LINKED ISSUE #95380: Investigate/add Windows Arm64 support for cpuinfo
pytorch/cpuinfo arm64 support should be investigated and added if not already present.

- [ ] Support for M1 and M2 needs to be merged to pytorch/cpuinfo

A PR to pytorch/pytorch (updating cpuinfo submodule) will be created after the tasks are completed.

### PR DESCRIPTION
**Pull request by iremyux**
cpuinfo submodule has not been updated in 6 months, so pulling the latest commit from https://github.com/pytorch/cpuinfo. 

Fixes #95380

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
LGTM

**Comment by iremyux** [comment]
The 2 failing checks should be resolved after [#95884](https://github.com/pytorch/pytorch/pull/95884) gets merged.

**Review by Skylion007 — APPROVED** [review]

**Comment by kit1980** [comment]
All Windows builds are failing for this PR, and this PR is supposed to fix an issue for Windows...

**Pull request closed without merging**
