### PR TITLE
Port THNN to ATen/Parallel

### PR DESCRIPTION
**Pull request by ilia-cher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #20157 Support for Eigen thread pool
* #20087 Native ATen/Parallel backend
* #20057 Split ATen/Parallel into interface and backend
* #20050 Move inter-op settings into ATen/Parallel
* #20043 Port ATen/native to ATen/Parallel
* **#20032 Port THNN to ATen/Parallel**

Summary:
Remove explicit usage of OpenMP from THNN

Test Plan:
BLAS=MKL USE_MKLDNN=1 USE_OPENCV=1 USE_FFMPEG=1 python setup.py develop --cmake
pytest -s -v test/test_torch.py::TestTorch

Differential Revision: [D15247960](https://our.internmc.facebook.com/intern/diff/D15247960)

### CODE REVIEW

**Comment by soumith** [comment]
wow! did you write this diff manually, or did you do a codemod?

**Review by soumith — APPROVED** [review]
I reviewed most of it, and it looks good. this is good stuff!

**Comment by ilia-cher** [comment]
@soumith, there're ~20-30 places to update in THNN, it did it manually

**Comment by ilia-cher** [comment]
well, a bit more, but writing correct and generic enough codemod would probably take more time

**Comment by ilia-cher** [comment]
I'm definitely going to double check once again all the callsites

**Pull request closed without merging**
