### PR TITLE
[Dynamo] Check for __bool__ attribute before accessing it

### LINKED ISSUE #119782: 63 Dynamo test are failing with "'QuantizationConfig' object has no attribute '__bool__'".
63 Dynamo test are failing with "'QuantizationConfig' object has no attribute '__bool__'".

## Repro

`PYTORCH_TEST_WITH_DYNAMO=1 pytest test_quantization.py -v -k test_quantize_pt2e_preserve_handle`

You will need to remove the skip or expectedFailure before running the repro command.
This may be just removing a line in
[dynamo_test_failures.py](https://github.com/pytorch/pytorch/blob/main/torch/testing/_internal/dynamo_test_failures.py)

## Failing tests

Here's a comprehensive list of tests that fail (as of this issue) with the above message:
<details>
<summary>Click me</summary>
```
test_quantization.py::TestGenerateNumericDebugHandle.test_quantize_pt2e_preserve_handle
test_quantization.py::TestQuantizePT2E.test_composable_quantizer_linear_conv
test_quantization.py::TestQuantizePT2E.test_constant_prop_preserve_metadata
test_quantization.py::TestQuantizePT2E.test_fold_all_ops_before_quantize
test_quantization.py::TestQuantizePT2E.test_fold_quantize
test_quantization.py::TestQuantizePT2E.test_fold_quantize_per_channel
test_quantization.py::TestQuantizePT2E.test_groupwise_per_channel_quant
test_quantization.py::TestQuantizePT2E.test_save_load
test_quantization.py::TestQuantizePT2E.test_speed
test_quantization.py::TestPT2ERepresentation.test_add_relu
test_quantization.py::TestPT2ERepresentation.test_maxpool2d
test_quantization.py::TestPT2ERepresentation.test_qdq
test_quantization.py::TestXNNPACKQuantizer.test_add_and_inplace_add
test_quantization.py::TestXNNPACKQuantizer.test_add_mul_long
test_quantization.py::TestXNNPACKQuantizer.test_add_mul_scalar
test_quantization.py::TestXNNPACKQuantizer.test_conv2d
test_quantization.py::TestXNNPACKQuantizer.test_conv_linear
test_quantization.py::TestXNNPACKQuantizer.test_dynamic_linear
test_quantization.py::TestXNNPACKQuantizer.test_dynamic_linear_with_conv
test_quantization.py::TestXNNPACKQuantizer.test_gru
test_quantization.py::TestXNNPACKQuantizer.test_linear_gru
test_quantization.py::TestXNNPACKQuantizer.test_linear_relu
test_quantization.py::TestXNNPACKQuantizer.test_linear_with_dynamic_shape
test_quantization.py::TestXNNPACKQuantizer.test_mul_float32_max
test_quantization.py::TestXNNPACKQuantizer.test_propagate_annotation
test_quantization.py::TestQuantizePT2EQAT_ConvBn1d.test_prepare_qat_conv_bn_fusion_getitem_placeholder
test_quantization.py::TestQuantizePT2EQAT_ConvBn1d.test_qat_conv_bn_fusion_no_conv_bias
test_quantization.py::TestQuantizePT2EQAT_ConvBn1d.test_qat_conv_bn_relu_fusion
test_quantization.py::TestQuantizePT2EQAT_ConvBn1d.test_qat_conv_no_bias
test_quantization.py::TestQuantizePT2EQAT_ConvBn2d.test_qat_conv_bn_fusion_no_conv_bias
test_quantization.py::TestQuantizePT2EQAT_ConvBn2d.test_qat_conv_bn_relu_fusion
test_quantization.py::TestQuantizePT2EQAT_ConvBn2d.test_qat_conv_bn_relu_fusion_no_conv_bias
test_quantization.py::TestQuantizePT2EQAT_ConvBn2d.test_qat_inplace_add_relu
test_quantization.py::TestQuantizePT2EQATModels.test_qat_resnet18
test_quantization.py::TestQuantizePT2E.test_embedding_conv_linear_quantization
test_quantization.py::TestQuantizePT2E.test_reentrant
test_quantization.py::TestPT2ERepresentation.test_add
test_quantization.py::TestPT2ERepresentation.test_conv2d
test_quantization.py::TestPT2ERepresentation.test_dynamic_linear
test_quantization.py::TestPT2ERepresentation.test_qdq_per_channel
test_quantization.py::TestPT2ERepresentation.test_static_linear
test_quantization.py::TestXNNPACKQuantizer.test_conv1d
test_quantization.py::TestXNNPACKQuantizer.test_conv1d_with_conv2d
test_quantization.py::TestXNNPACKQuantizer.test_conv_linear_no_permute
test_quantization.py::TestXNNPACKQuantizer.test_dynamic_linear_int4_weight
test_quantization.py::TestXNNPACKQuantizer.test_linear
test_quantization.py::TestXNNPACKQuantizer.test_mul_and_inplace_mul
test_quantization.py::TestXNNPACKQuantizer.test_obs_sharing_ops
test_quantization.py::TestXNNPACKQuantizer.test_qat_dynamic_linear
test_quantization.py::TestXNNPACKQuantizerModels.test_resnet18
test_quantization.py::TestQuantizePT2EQAT_ConvBn1d.test_qat_conv_bn_fusion
test_quantization.py::TestQuantizePT2EQAT_ConvBn1d.test_qat_conv_bn_fusion_literal_args
test_quantization.py::TestQuantizePT2EQAT_ConvBn1d.test_qat_conv_bn_relu_fusion_no_conv_bias
test_quantization.py::TestQuantizePT2EQAT_ConvBn1d.test_qat_inplace_add_relu
test_quantization.py::TestQuantizePT2EQAT_ConvBn1d.test_qat_preserve_source_fn_stack
test_quantization.py::TestQuantizePT2EQAT_ConvBn1d.test_qat_update_shared_qspec
test_quantization.py::TestQuantizePT2EQAT_ConvBn2d.test_prepare_qat_conv_bn_fusion_getitem_placeholder
test_quantization.py::TestQuantizePT2EQAT_ConvBn2d.test_qat_conv_bn_fusion
test_quantization.py::TestQuantizePT2EQAT_ConvBn2d.test_qat_conv_bn_fusion_literal_args
test_quantization.py::TestQuantizePT2EQAT_ConvBn2d.test_qat_conv_no_bias
test_quantization.py::TestQuantizePT2EQAT_ConvBn2d.test_qat_preserve_source_fn_stack
test_quantization.py::TestQuantizePT2EQAT_ConvBn2d.test_qat_update_shared_qspec
test_quantization.py::TestQuantizePT2EQATModels.test_qat_mobilenet_v2
```
</details>

cc @ezyang @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @bdhirsh @aakhundov

### PR DESCRIPTION
**Pull request by mreso**
This PR checks if __bool__ attribute is available before accessing it when handling a UserDefinedObjectVariable

Fixes #119782 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @aakhundov

### CODE REVIEW

**Comment by mreso** [comment]
Hi @JackCaoG do you have any insights on why this PR creaks the xla test?

**Comment by JackCaoG** [comment]
```
  File "/var/lib/jenkins/workspace/xla/test/dynamo/test_dynamo.py", line 436, in train_model
    optimizer.step()
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 676, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 634, in compile_inner
    check_fn = CheckFunctionManager(
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/guards.py", line 1055, in __init__
    guard.create(builder)
  File "/opt/conda/lib/python3.8/site-packages/torch/_guards.py", line 247, in create
    return self.create_fn(builder, self)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/guards.py", line 501, in CONSTANT_MATCH
    self.EQUALS_MATCH(guard)
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/guards.py", line 451, in EQUALS_MATCH
    assert istype(
AssertionError: Unexpected type <class 'builtin_function_or_method'>, not in (<class 'torch.device'>, <class 'numpy.uint64'>, <class 'numpy.int64'>, <class 'slice'>, <class 'bytes'>, <class 'numpy.float64'>, <class 'numpy.uint32'>, <class 'numpy.int32'>, <class 'code'>, <class 'list'>, <class 'torch.dtype'>, <class 'torch.layout'>, <class 'numpy.float32'>, <class 'NoneType'>, <class 'numpy.uint16'>, <class 'torch.Size'>, <class 'numpy.int16'>, <class 'tuple'>, <class 'int'>, <class 'bool'>, <class 'type'>, <class 'numpy.float16'>, <class 'numpy.uint8'>, <class 'range'>, <class 'complex'>, <class 'torch.memory_format'>, <class 'numpy.int8'>, <class 'set'>, <class 'frozenset'>, <class 'float'>, <class 'ellipsis'>, <class 'str'>)
```

seems like it failure when trying to run the optimizer in https://github.com/pytorch/xla/blob/master/test/dynamo/test_dynamo.py#L437. From the log it failed when trying to do a `EQUAL_MATCH`. Wondering if without your change it is doing a ID match in https://github.com/pytorch/pytorch/tree/main/torch/_dynamo#L500-L505 but I am not an expert on guards through.

**Comment by jeffdaily** [comment]
I've looked at the 1 ROCm CI failure and it does not look related to these changes.

**Review by zou3519 — APPROVED** [review]

**Comment by DanilBaibak** [comment]
Hi @mreso! Sorry, I need to revert your PR because it broke trunk. Here you can find more information about the issue - https://hud.pytorch.org/pytorch/pytorch/commit/dd7aeedb72f8a96d0f168308292e0d41c095f01b

**Pull request closed without merging**
