### PR TITLE
s390x: update using vectorization builtins

### PR DESCRIPTION
**Pull request by AlekseiNikiforovIBM**
With gcc >= 12 on s390x store builtins
are accidentally optimized out due to
bad type aliasing.

Ensure that proper corresponding types are used,
and if types do mismatch,
first store data into array of correct type
and then memcpy it to destination pointer.

See also:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114676

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by bdhirsh** [comment]
Hmm @malfet - tentatively tagged you, but do you know who a good person would be to look at CPU vectorization changes?

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
>  tentatively tagged you, but do you know who a good person would be to look at CPU vectorization changes?

To be frank, I don't have a good idea what is going on here, but to the best of my knowledge we don't have binary builds nor ways to test it, so anything is fine there, as long as there aren't two PRs that change the same line back and forth

**Pull request closed without merging**
