### PR TITLE
Make structured functions properly check device/dtype of explicit out args

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#55150 Make structured functions properly check device/dtype of explicit out args**

Somehow I forgot to add these checks.  Now they're in here.  Thanks
ngimel for noticing.

This is probably a slight efficiency hit on TensorIterator, which is
probably already doing all these checks.  Would be good to follow up
on this, though it may not be easily fixable with the TI rewrite.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D27523879](https://our.internmc.facebook.com/intern/diff/D27523879)

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
The TI hit is only for `out` variants, so that's ok? Thanks for the fix!

**Comment by ezyang** [comment]
> The TI hit is only for out variants, so that's ok? Thanks for the fix!

Yup. Unfortunately looks like the patch is wrong XD

**Comment by ngimel** [comment]
Hm, yeah, ops that do type promotion can have `out` that's different from computed dtype, and that's op-specific.

**Comment by ezyang** [comment]
The pow test failure, I'm pretty sure is the meta function being wrong. Not sure about the complex one but I bet it's similar

**Pull request closed without merging**
