### PR TITLE
Polish CPP docs, Minor Python Docs Fixes

### PR DESCRIPTION
**Pull request by svenevs**
CC: @goldsborough 

## Generic CPP Docs Stuff

- [x] Clean targets

    - Python: add `-f` so that a vanilla `make clean` doesn't formally fail ;)
    - CPP: has to be before the catch-all and should also delete generated api.

- [x] Simplify `Doxyfile` for maintainers :boom:

- [x] CPP: separate `source` and `build` directories.

    - Local build times go from 15 minutes to 2 :scream:
    - CPP auto-doc pushing repo script thing to host online does **not** need to change (still just `cd docs/cpp && make html` followed by copying `docs/cpp/build/html/**`.

- [x] See `HTML_OUTPUT` in `Doxyfile` for how to easily compare doxygen html with Sphinx

- [x] fix `FunctionImpl` docs (nesting document-comments `///` and `/*scale=0.5*/` apparently confuses doxygen.
- [x]  remove forward declaration to guarantee correct location extracted by exhale

## CPP and Python `conf.py` Cleanup / HTML Theme "Fixes"

Separating into two categories since I cannot figure out how the python docs build.  **Somebody needs to test them and report back success or failure**.

### Removal of `html_context['css_files']`

Using `html_context['css_files']` is apparently _formally_ undefined behavior.  See [sphinx/#2442](https://github.com/sphinx-doc/sphinx/issues/2442).  Unfortunately, this took a long time to have an official fix in Sphinx.  Sphinx 1.8 and later you can use `html_css_files`, but since the python docs are pinned at `1.7.9` (as well as CPP docs **will** break with Sphinx 1.8 if more files are documented), I'm adding the "old" `setup(app)` method.  The sphinx 1.8 // cpp docs issues are something in breathe that will take a lot of effort to fix :cry:

### Removal of `html_static_path`

Setting `html_theme_path` is no longer necessary, Sphinx 1.6+ allow html theme's to set this in their `setup(app)` function (and the sphinx rtd theme does it correctly).  In some (rare) cases it may actually create problems / conflicts.

I guess officially you could introduce convoluted logic to check if Sphinx <1.6 but I view that as pointless.

--------------------------------------------------------------------------------------------------------------------------------

#### CPP docs html setup fixes / cleanup

- [x] `html_context['css_files']` removal
- [x] remove `html_static_path`
- [x] verified as valid (works with Sphinx 1.7 and 1.8)

#### Python: html setup fixes / cleanup

- [x] `html_context['css_files']` removal
- [x] remove `html_static_path`
- [x] verified as valid

### CODE REVIEW

**Comment by goldsborough** [comment]
Thanks! 😊  I'll keep an eye on the PR

**Review by goldsborough — APPROVED** [review]
Infinite gratitude for working on this! 😊 Waiting for @soumith to stamp the Python doc changes

**Review by soumith — APPROVED** [review]
looks really good. Thanks a lot for working on this @svenevs !

**Comment by vishwakftw** [comment]
Considering this has been merged, is there any reason to keep it open?

**Pull request closed without merging**
