### PR TITLE
fix lint

### PR DESCRIPTION
**Pull request by wdvr**
Fixes #ISSUE_NUMBER

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv

### CODE REVIEW

**Review by cyyever — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
It has conflicts with trunk though...

**Comment by malfet** [comment]
Cancelling the land and closing for now, as offending PR has been reverted, see https://hud.pytorch.org/pytorch/pytorch/commit/2487a834a43db88b17891bfeec126fc812337842

**Pull request closed without merging**
