### PR TITLE
Doc fix for complex views

### PR DESCRIPTION
**Pull request by anjali411**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#40450 Doc fix for complex views**

Differential Revision: [D22190911](https://our.internmc.facebook.com/intern/diff/D22190911)

### CODE REVIEW

**Comment by mruberry** [comment]
Lint issues are real, clang-tidy failure is not.

**Comment by anjali411** [comment]
> Lint issues are real, clang-tidy failure is not.

yeah fixed it :D

**Review by mruberry — APPROVED** [review]
Stamped!

**Comment by vadimkantorov** [comment]
One late naming suggestion: `torch.as_complex` / `torch.as_real` similar to `as_tensor` (which also does not copy memory by default)

**Pull request closed without merging**
