### PR TITLE
dynamo: graph break on `torch.cuda.stream`

### PR DESCRIPTION
**Pull request by jon-chuang**
Follow up to https://github.com/pytorch/pytorch/pull/94137

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @mlazos @soumith @yanboliang @desertfire

### CODE REVIEW

**Comment by jon-chuang** [comment]
Not sure if the failure is due to the argument not being const.

**Comment by jon-chuang** [comment]
I think we can probably fix by fiddling with how the proxy node is generated. Perhaps we simply need to reconstruct the argument not to be a const, but some other sort of variable.

**Comment by yanboliang** [comment]
There are two scenarios need to be supported:
* CUDA stream generated inside of traced function (#93808)
* CUDA stream passed from outside of traced function (#94627)

For the second case, it's easy to handle, since we can use a tuple of ```stream_id, device_index, device_type``` to generate & set the stream; for the first case, I think we should generate a new stream after the graph break, since proxy can be propagated through different graphs.

**Comment by yanboliang** [comment]
Gently ping @jon-chuang!

**Pull request closed without merging**
