### PR TITLE
Fix stupid N^2 naming behavior in FX and removed assert that slows things a lot sometimes

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #87533

cc @jansel @lezcano @fdrocha @mlazos @soumith @voznesenskym @yanboliang

### CODE REVIEW

**Comment by Chillee** [comment]
Ok, not removing assert (cc: @voznesenskym ). For this benchmark
```
def f(x):
    for _ in range(10000):
        x = x * x
    return x

torch._dynamo.optimize("aot_eager")(f)(torch.randn(5))
```

master: 61 seconds
this PR: 30 seconds
If you remove assert: 18 seconds

**Review by ezyang — APPROVED** [review]

**Review by voznesenskym — APPROVED** [review]

**Comment by Chillee** [comment]
I suspect the failure is unrelated?

**Pull request closed without merging**
