### PR TITLE
Move OpInfo class into new opinfo folder

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #82830
* __->__ #82540

Ref #82518

Starting small to minimize merge conflicts, this moves the top-level
class definitions and some helper functions into the `opinfos` folder.
It also brings `common_methods_invocations.py` to just below 1MB.

### CODE REVIEW

**Comment by albanD** [comment]
I'll wait for the discussion on the issue to lead to a consensus before working towards merging this right?

**Comment by peterbell10** [comment]
Personally I think this should be merged ASAP. It brings `common_methods_invocations.py` under 1MB which is the main problem atm and this change doesn't depend on how we group the `op_db` definitions into different files.

**Review by albanD — COMMENTED** [review]
Ok, the change sounds ok but I would have a couple questions:
- Why opinfoS (with an S)? This folder does not contain a bunch of opinfos, it is (for now only) the core logic.
- Where do we plan to put the splitted OpInfo definitions in this new architecture?

**Comment by peterbell10** [comment]
> Where do we plan to put the splitted OpInfo definitions in this new architecture?

My thinking was that we would (eventually) move all the definitions somewhere inside this `opinfos` folder. File structure TBD.

>Why opinfoS (with an S)?

Assuming all the opinfos are defined in the folder it makes more sense. I don't mind dropping it though.

**Comment by albanD** [comment]
What about a final structure like?
```
testing/
  _internal/
    opinfo/
      core.py
      utils.py    
      definitions/
        linalg.py
        fft.py
        nn.py
        ....
```

- We use utils.py and not helper.py within the codebase in general
- Have a subfolder with the definitions to make greping the definitions only simpler.
- Is the `__init__.py` actually needed here?

**Comment by peterbell10** [comment]
> We use utils.py and not helper.py within the codebase in general

Sure, I just called renamed the existing `opinfo_helper.py`.

> Have a subfolder with the definitions to make greping the definitions only simpler.

Makes sense to me. Though I don't have any strong feelings either way.

> Is the `__init__.py` actually needed here?

AFAIK it's always recommended to include an `__init__.py` file, even if it's empty. See https://stackoverflow.com/a/48804718/2556706

**Review by albanD — APPROVED** [review]
SGTM!

**Comment by albanD** [comment]
Not sure when is the best time to land this to avoid land races...

**Comment by albanD** [comment]
I'm merging this to avoid any merge conflict if we wait too long.

**Pull request closed without merging**
