### PR TITLE
Support resize on meta storage

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #101988

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Looks good once the xfail list is updated!

**Review by bdhirsh — APPROVED** [review]

**Comment by osalpekar** [comment]
This PR seems to be based atop https://github.com/pytorch/pytorch/pull/101949 and https://github.com/pytorch/pytorch/pull/101976 which were reverted. Since those will no longer be landed internally, this PR doesn't patch internally during diff-train import due to merge conflicts. In order to unblock importing the rest of the commits, I'll need to revert this change, and then this would need to be rebased and re-merged. Apologies for the inconvenience.

**Comment by ezyang** [comment]
This PR didn't conflict at all on master so it's weird it had to be reverted

**Pull request closed without merging**
