### PR TITLE
Typo fix: s/nonzero/unique/

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #124935

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Test?

**Review by Skylion007 — APPROVED** [review]

**Comment by ezyang** [comment]
@albanD idk man, I was just code reading and saw this lol

**Pull request closed without merging**
