### PR TITLE
Safely infer device type + docstrings + tests

### PR DESCRIPTION
**Pull request by nmacchioni**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #133378
* #133287
* #133154
* #133153
* #133121
* #133058
* __->__ #133668

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by nmacchioni** [comment]
I unfortunately irrevocably screwed up the old stack of 4 commits I was going to land by doing `ghstack land` and not through the pytorch bot. This is just a squash of those

**Comment by nmacchioni** [comment]
For reference, here are the squashed commits:

https://github.com/pytorch/pytorch/pull/133286
https://github.com/pytorch/pytorch/pull/132958
https://github.com/pytorch/pytorch/pull/132959
https://github.com/pytorch/pytorch/pull/132966

**Review by eellison — APPROVED** [review]
stamp since prior squashed commits were already reviewed

**Pull request closed without merging**
