### PR TITLE
Fixed name conflict by suing a more specific prefix for lowered module name

### PR DESCRIPTION
**Pull request by iseeyuan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #61043
* **#61007**

A simple change of lowered module name. 
From:
"torch.jit." + backend_name + ".LoweredModule." + module_name
To: 
"torch.jit.LoweredModule." + backend_name + "." + module_name

After the change, the lowered module has a longer and more differentiable prefix (for example, different from "torch.jit._pickle"). It's easier for type resolving and debugging.

Differential Revision: [D29477733](https://our.internmc.facebook.com/intern/diff/D29477733)

### CODE REVIEW

**Comment by iseeyuan** [comment]
@iseeyuan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29477733).

**Comment by iseeyuan** [comment]
@iseeyuan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/).

**Comment by iseeyuan** [comment]
@iseeyuan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29477733).

**Review by kimishpatel — APPROVED** [review]
Looks good to me. Do check if there are any other tests in different codebase such as glow that rely on this.

**Review by SplitInfinity — APPROVED** [review]

**Review by raziel — APPROVED** [review]

**Pull request closed without merging**
