### PR TITLE
[JIT] Use signed integers in CalculateNecessaryArgs

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #79331

x was underflowing:
```
size_t x = ...
while (x >= 0) {
  x--;
}
```

Changed the variables to int64_t.

Differential Revision: [D37088210](https://our.internmc.facebook.com/intern/diff/D37088210)

### CODE REVIEW

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37088210).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37088210).

**Review by yuhc — APPROVED** [review]
Tested with our internal code which originally experienced this issue, and everything works now. Thanks for the fix!

**Review by tugsbayasgalan — APPROVED** [review]

**Pull request closed without merging**
