### PR TITLE
move autograd folder from tools to torchgen

### LINKED ISSUE #100684: Add tools to torchgen
### 🚀 The feature, motivation and pitch

I have some custom operators, and I've already generated the Dispatcher-related code with torchgen. But I want these operators can be called in python.
So I want to put the files  `tool/*` that generates the python binding into torchgen. Or is there any other way to do it?

### Alternatives

_No response_

### Additional context

_No response_

cc @ezyang @bhosmer @bdhirsh

### PR DESCRIPTION
**Pull request by huihoaan**
Fixes #100684

The `autograd` module is a relatively independent module compared to the others. And  the hard code paths to tools/ is not many. There are two main commits in my pr:
1.move the `autograd` folder from tools to torchgen, and some python file which refer to it.
2.change the code from `tools/autograd` to `torchgen/autograd`

### CODE REVIEW

**Review by zou3519 — COMMENTED** [review]
Code LGTM, but because this is technically a build system change I need to go check that this will merge nicely.

**Comment by zou3519** [comment]
@huihoaan in its current state, this PR is very difficult to merge. Some quick ideas for brainstorming:
- In the original issue, you said you wanted Python bindings to your custom operators. You can just access operators via `torch.ops.*` instead of relying on codegen
- do you really need to put all of this into torchgen? derivatives.yaml in particular is giving me trouble, because I am not sure our source control system is going to be smart enough to deal with the move of that file.
- Ideally we would come up with some plan for the merge that would have an intermediate stage that allows the internal build system to keep working (with no or minimal changes), and then we can change the internal build system separately. Right now the change (moving everything from tools/autograd/* out) is disruptive

**Comment by huihoaan** [comment]
@zou3519 Thank you for your advice. Let me reply to your above questions:
1.we want to generate operators like `torch.*` rather than `torch.ops.*`, so we need the `autograd`.
2.In fact, the `derivative.yaml` is not needed for us, so I will add a commit to move `derivative.yaml` and `deprecated.yaml` back to tools/autograd.(Maybe I will add some parameters for path, because of there are two path for files,tools/autograd and torchgen/autograd)

**Comment by zou3519** [comment]
How urgently do you need this? In the absence of a good migration plan (3), I would need to take over this PR and fix the internal bits before merging it.

**Comment by huihoaan** [comment]
> How urgently do you need this? In the absence of a good migration plan (3), I would need to take over this PR and fix the internal bits before merging it.

Thank you for taking over this PR. For me, the sooner the better, hahaha.  But at least before the 2.1 release. 
By the way, when will version 2.1 be released

**Comment by zou3519** [comment]
> By the way, when will version 2.1 be released

https://dev-discuss.pytorch.org/t/pytorch-release-2-1-0/1271

> Thank you for taking over this PR. For me, the sooner the better, hahaha. But at least before the 2.1 release.

Okay, I can plan for this. It's not going to be the highest priority thing on my list, but we will get it done before the 2.1 release.

**Pull request closed without merging**
