### PR TITLE
Utilize aot compile

### PR DESCRIPTION
**Pull request by EikanWang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #124070
* #124177
* #116368
* #121387
* __->__ #123545

cc @voznesenskym @penguinwu @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by angelayi — CHANGES_REQUESTED** [review]
Hi, sorry, we're trying to decrease the usage of `torch._export.aot_compile` in favor of directly using `torch.export._trace._export(model, example_inputs, predispatch=True)` + `torch._inductor.aot_compile` to better separate out the two functionalities.

**Comment by EikanWang** [comment]
> Hi, sorry, we're trying to decrease the usage of `torch._export.aot_compile` in favor of directly using `torch.export._trace._export(model, example_inputs, predispatch=True)` + `torch._inductor.aot_compile` to better separate out the two functionalities.

Does it mean `torch.export.aot_compile` will be deprecated?

**Comment by jansel** [comment]
@angelayi is `predispatch=True` ready?  My understanding is there is still a lot of stuff that will work with `aot_compile` but not predispatch.  What is the concrete benefit?

Once predispatch is ready, I think we can just make `aot_compile` an alias and not force people to rewrite things.

**Comment by desertfire** [comment]
Agree with @jansel that we should not suddenly drop the existing API. 
@EikanWang , `AOTIRunnerUtil` is meant to be a test util. Any specific reason you want to change it?

**Comment by angelayi** [comment]
Yeah, I don't mean to deprecate the API, but just want to decrease the usage

**Comment by EikanWang** [comment]
> Yeah, I don't mean to deprecate the API, but just want to decrease the usage

Thanks for the confirmation. When I enable the eager-through-torch.compile(aoti), I found the utility function is similar to `torch._export.aot_compile`. So, I tried to refine it and understand the logic behind it. I will close it. @desertfire

**Pull request closed without merging**
