### PR TITLE
[ONNX] Remove 'diagnose_step'

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #100407
* #100299
* #100219
* __->__ #99944
* #99668

`ThreadFlowLocation`, a.k.a 'step', cannot fully be visualized by `SARIF vscode extension` today. 
Discarding `diagnose_step` such that we don't end up creating diagnostics that record things there.

### CODE REVIEW

**Review by justinchuby — APPROVED** [review]
What was a step again?

**Comment by BowenBao** [comment]
https://docs.oasis-open.org/sarif/sarif/v2.1.0/cs01/sarif-v2.1.0-cs01.html#_Toc16012707

Each diagnostic can contain a list of ordered `ThreadFlowLocation`. They represent the code flow location associated with the parent diagnostic, like a sequence of steps. For example, the diagnostic for `export_fx_to_onnxscript` could contain a list of `ThreadFlowLocation` object created for `export_fx_node_to_onnxscript`. This can be achieved by decorating `export_fx_to_onnxscript` with `diagnose_call`, and decorating `export_fx_node_to_onnxscript` with `diagnose_step`.

**Comment by justinchuby** [comment]
Is there another SIGSEGV? Should we report to onnxruntime?

**Comment by BowenBao** [comment]
It was also the same previous known issue. We need ort 1.15 or 1.14.1.

**Pull request closed without merging**
