### PR TITLE
[CD] Use Anaconda cmake for Mac builds

### LINKED ISSUE #142873: MacOS libtorch builds are failing since Nov 12
### 🐛 Describe the bug

See https://hud.pytorch.org/hud/pytorch/pytorch/3bcdb4ed6b7b9d9b19806d2442d8cf7a1e428af8/1?per_page=50&name_filter=macos-arm64-binary-libtorch&mergeLF=true

MacOS nightly builds are failing https://github.com/pytorch/pytorch/actions/runs/12271730101/job/34239111301

### Versions

nightly

cc @seemethere @malfet @osalpekar @atalman @pytorch/pytorch-dev-infra @albanD

### PR DESCRIPTION
**Pull request by malfet**
To find Anaconda-env-installed OpenMP
(As OpenMP from PyPI is looking for it in a different places)

For posterity: our build script names are very confusing:
 - [`.ci/wheel/build_wheel.sh`](https://github.com/pytorch/pytorch/blob/6cb6e8d790fce6a24e16bf03afd7275bd294ad9c/.ci/wheel/build_wheel.sh) is only used for MacOS wheel/libtorch builds
 - [`.ci/manywheel/build.sh`](https://github.com/pytorch/pytorch/blob/6cb6e8d790fce6a24e16bf03afd7275bd294ad9c/.ci/manywheel/build.sh) are used for Linux wheel/libtorch builds
 - [`.ci/pytorch/windows/build_pytorch.bat`](https://github.com/pytorch/pytorch/blob/6cb6e8d790fce6a24e16bf03afd7275bd294ad9c/.ci/pytorch/windows/build_pytorch.bat) is used for Windows wheel builds

Fixes https://github.com/pytorch/pytorch/issues/142873

### CODE REVIEW

**Review by Jack-Khuu — APPROVED** [review]

**Review by atalman — APPROVED** [review]
lgtm, but should we apply this on MacOS only if its affects MacOS ?

**Comment by malfet** [comment]
> lgtm, but should we apply this on MacOS only if its affects MacOS ?

It is only applies to MacOS (but I can leave this comment on PR, as I've been confused by our build script names myself)

**Pull request closed without merging**
