### PR TITLE
[Profiler] Improve the docstring for export_memory_timeline

### PR DESCRIPTION
**Pull request by aaronenyeshi**
Summary: Add more details about the export_memory_timeline API, as we've landed new representations of the memory timeline data.

Test Plan: CI, should be no functional change, as we only changed comments.

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]

**Comment by aaronenyeshi** [comment]
This is a comment change, with no functional change. Failing tests are flaky. Will land this.

**Pull request closed without merging**
