### PR TITLE
ROCM: Remove det_singular OpInfo

### LINKED ISSUE #93045: DISABLED test_forward_mode_AD_linalg_det_singular_cuda_complex128 (__main__.TestFwdGradientsCUDA)
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/FAILED%20test_ops_fwd_gradients.py%3A%3ATestFwdGradientsCUDA%3A%3Atest_forward_mode_AD_linalg_det_singular_cuda_complex128%20-%20torch.autograd.gradcheck.GradcheckError%3A%20While%20considering%20the%20imaginary%20part%20of%20complex%20inputs%20only%2C%20Jacobian%20computed%20with%20forward%20mode%20mismatch%20for%20output%200%20with%20respect%20to%20input%200%2C)).

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### PR DESCRIPTION
**Pull request by arindamroy-eng**
According to comments in
https://github.com/pytorch/pytorch/issues/93045#issuecomment-1477674083

The test has been flaky all over.
Hence submitting this PR to remove the test itself.

Fixes #93045

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by albanD — CHANGES_REQUESTED** [review]
Wasn't the suggestion to remove it only for rocm?

**Review by lezcano — COMMENTED** [review]
This is fine. This test is  testing something that's not numerically stable, and it just keeps breaking. It's fine to delete it.

That being said, please delete also the sampling function

**Comment by albanD** [comment]
I'm confused? We really want to remove all the tests for det? I would hope that cpu/cuda would give similar results at least? And that they run without errors, etc

**Review by lezcano — APPROVED** [review]
I'm happy with this, but let's fix CI and also wait for approval from @albanD

**Review by albanD — APPROVED** [review]
Ho I missed the fact that this was only the "singular" variant! My bad!
Sounds good then!

**Comment by kit1980** [comment]
The tests are failing (https://github.com/pytorch/pytorch/actions/runs/5251260112/jobs/9486318802?pr=102581):

Couldn't find OpInfo for DecorateMeta(op_name='linalg.det', variant_name='singular', decorator=<function expectedFailureIf.<locals>.decorator at 0x7f9161269360>, device_type=None, dtypes=None)

**Pull request closed without merging**
