### PR TITLE
Mark diag.out composite

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #88670

It's implementation just redispatches, it works for more than CPU/CUDA.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
I'll need to squash this with the next PR

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/88671

**Comment by ezyang** [comment]
I'm... inclined to just give up on this

**Review by anjali411 — APPROVED** [review]

**Pull request closed without merging**
