### PR TITLE
[quant][core][better-engineering] Rename files in quantized/cudnn directory to conform with non-quantized countertpart filenames

### PR DESCRIPTION
**Pull request by dzdang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #77431

Summary:
Names of analogous files in quantized directory (previously snake case) were inconsistent with
their non-quantized filename counterparts (pascal case). This is the third of a series of PRs that changes
all files in quantized (and sub-directories) dir to have pascal case.

Some files have not been renamed as it is causing issues related to
custom class with import torch at runtime.

Test Plan:
```
python test/test_quantization.py
```

Differential Revision: [D36381761](https://our.internmc.facebook.com/intern/diff/D36381761)

### CODE REVIEW

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36381761).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36381761).

**Review by jerryzh168 — APPROVED** [review]

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36381761).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36381761).

**Pull request closed without merging**
