### PR TITLE
[ONNX] Only emit initializers for the base graph, not for any nested …

### PR DESCRIPTION
**Pull request by jamesr66a**
…graphs

This was a bug

### CODE REVIEW

**Comment by ezyang** [comment]
1. Is there a test that catches this bug?
2. Is it true that initializers of subblocks should be empty?

**Comment by jamesr66a** [comment]
@ezyang 

1) Let me see if i can add one
2) I think so; it would be kind-of bad to force all backends to recursively iterate through the network just to initialize parameters. Not sure though, we should probably bring this up as a discussion on ONNX

**Comment by zdevito** [comment]
The bug is that encodeBlock forwards its initializers to subblocks. https://github.com/jamesr66a/pytorch/blob/b701a2b046686a30ce3a055f2d1f7e8e8a8038b9/torch/csrc/jit/export.cpp#L264 

I fixed this in https://github.com/pytorch/pytorch/pull/6924 so this fix should become unnecessary.

**Comment by jamesr66a** [comment]
Thanks @zdevito!

**Pull request closed without merging**
