### PR TITLE
[numpy] Add unary-ufunc tests for `erf` variants

### PR DESCRIPTION
**Pull request by kshitij12345**
Adding Unary Ufunc Test entry for `erf` variants.

We use scipy functions for reference implementation.

We can later update the tests once these functions will update integer input to float.

### CODE REVIEW

**Comment by mruberry** [comment]
This change won't work properly (as is) until https://github.com/pytorch/pytorch/pull/44609 is in.

**Comment by mruberry** [comment]
This is great, and it can also remove the test from test_torch:

```
_TorchMathTestMeta('erf', ref_backend='scipy'),
_TorchMathTestMeta('erfc', ref_backend='scipy'),
```

I would link them directly but Github fails to render test_torch.py properly (because it's too big, at the moment). 

I look forward to seeing the rest of these tests replaced with OpInfo-based tests so we can delete the `torch_op_tests` and its associated generated tests. The `torch_op_tests` are actually the precursor to the UnaryOpInfo metadata and the test_unary_ufunc.py test suite. The tests in test_unary_ufunc.py were closely modeled after the generated `torch_op_tests`.

**Comment by kshitij12345** [comment]
Ah. Right! Forgot to do that.

Done now. 

 Thanks!

**Review by mruberry — APPROVED** [review]
Awesome! Thanks @kshitij12345!

**Pull request closed without merging**
