### PR TITLE
[inductor] check best templates first for fusions

### PR DESCRIPTION
**Pull request by nmacchioni**
Fixes #ISSUE_NUMBER

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by eellison — APPROVED** [review]
@AlnisM noticed this as well. good catch !

**Comment by AlnisM** [comment]
I think this is a good change (essentially a bug fix). Not sure if you have maybe also noticed but just wanted to mention that I noticed this change can cause large compilation time increases, e.g. on H100 for one huggingface model (PLBartForCausalLM train), I observed an increase from 180 -> 303 seconds (because this line https://github.com/pytorch/pytorch/blob/nmacchioni-2/torch/_inductor/codegen/triton.py#L3064 ends up taking 25+ seconds for 4 different fusions)

**Comment by nmacchioni** [comment]
@AlnisM I would agree that this is a bug fix, as such I am okay with any compile time regressions.

I'd also bet that the reason you see such a large compile time increase on H100 is directly related to the compile time issues we've see for certain GEMM templates that emit WGMMA ops when compiled. This is a known issue where WGMMA usage can increase compile time for a single template up to ~100 seconds. Templates that do emit WGMMA ops are usually faster than other templates, which would make them more likely to be a candidate for fusion now (unlike before, where we just picked the first Triton template). So, with this change, if one of our GEMM templates emits WGMMA ops and is the fastest (pretty likely) we'll fuse the epilogue and recompile, and there we'll have to take the increased compile time again (since the fused template will (I think always?) still emit WGMMA ops).

**Pull request closed without merging**
