### PR TITLE
[composite compliance] fix linalg.eigvals

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #84137
* #84127
* #84125

linalg.eigvals fails in some cases with functorch and the root of the
problem is that it is not composite compliant.

In particular, checks that branch on whether or not a Tensor requires
grad do not work with functorch. In order to support functorch with
them, we have to include an additional "if the tensor is a Tensor
Subclass, then assume that it MAY require grad, so we must always go
through the differentiable path".

This PR also changes the batching rule for linalg.eigvals to be a
decomposition instead of what it was previously. What it was previously
was masking the error in functorch's test suite.

Unfortunately we don't comprehensive tests for this on the functorch
side which is why this was not caught before. I'll look into why
that is in the future; it's a bit complicated.

Test Plan:
- wait for tests

### CODE REVIEW

**Comment by zou3519** [comment]
FYI, @Lezcano, @nikitaved - any branches in the codebase that branch on if a Tensor requires forward or backward gradient must also check `isTensorSubclassLike`, otherwise, they won't work completely with functorch.

I remember this occurs often in the linalg code, so if you are alright with it, I'll dig around some more and send some more PRs to update those branches. It's a bit difficult to trigger this with functorch (and our tests don't always exercise it), which is why we haven't seen too many failures before.

**Review by lezcano — APPROVED** [review]
As you have seen, we already did this for some operations like eigvalsh and svdvals (the most useful ones really), I agree it's better to lift the checks to the main function. And thank you for the detailed comment!

I do not think we use this anywhere else in `linalg`, but sure, please feel free to send more fixes of this sort!

**Review by IvanYashchuk — APPROVED** [review]
Is there an issue for proper support of "Tensor Subclass that doesn't require grad may wrap a Tensor subclass that requires grad"?

**Comment by zou3519** [comment]
> Is there an issue for proper support of "Tensor Subclass that doesn't require grad may wrap a Tensor subclass that requires grad"?

Let me put one up

**Review by samdow — APPROVED** [review]

**Pull request closed without merging**
