### PR TITLE
Configures distributed_checkpoint label

### PR DESCRIPTION
**Pull request by LucasLLC**
Configures the existing `module: distributed_checkpoint` label

### CODE REVIEW

**Review by wconstab — APPROVED** [review]

**Comment by awgu** [comment]
For my understanding, when should we be using the `module: <...>` label? It seemed like from https://github.com/pytorch/pytorch/issues/115168, we moved to using the `oncall: distributed` label for general distributed. Should we have `module: <...>` labels for other distributed components?

**Review by wz337 — APPROVED** [review]
Noice!

**Comment by fegin** [comment]
> For my understanding, when should we be using the `module: <...>` label? It seemed like from #115168, we moved to using the `oncall: distributed` label for general distributed. Should we have `module: <...>` labels for other distributed components?

Yes, we should have different module label for different components, like module:fsdp, module:ddp. `module:distribute` is removed because it is not the right concept.

**Pull request closed without merging**
