### PR TITLE
Fix meta registrations for foreach_{div, mul}

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #112781
* #112780
* #112779
* __->__ #112283
* #112778
* #112281
* #112280

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
As we did with the unary, functions, here we should also implement all these generically, I think.

I get the feeling that all the foreach ops could be implemented generically in one generic implementation. You just need to tell it which inputs are lists.

**Comment by isuruf** [comment]
> I get the feeling that all the foreach ops could be implemented generically in one generic implementation. You just need to tell it which inputs are lists.

It's not impossible, but I think it would be too complex to read since we need to handle a lot of difference cases like alpha parameter, ScalarList, TensorList, etc)

**Comment by lezcano** [comment]
The way I see it, you'd get a list of parameters that can be lists (you may be able to get that from the signature of the function, for example), and then you would:
- Check which of the inputs that can be lists are actually lists.
- Check that the sizes of the lists agree
- Iterate over these lists with a for loop and collect the result in an output list and return it

**Comment by isuruf** [comment]
Folded into https://github.com/pytorch/pytorch/pull/112281 with your suggestion.

**Pull request closed without merging**
