### PR TITLE
make code simplify in get bufffers and parameters

### PR DESCRIPTION
**Pull request by www516717402**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by jamesr66a — APPROVED** [review]
Looks fine to me but adding @khabinov as code owner

**Comment by www516717402** [comment]
@khabinov @jamesr66a 
Already agree CLA. Hope merge this code as soon. Thanks.

**Review by khabinov — CHANGES_REQUESTED** [review]
CI failed with the message below. Could you please help fix?

```
./torch/fx/passes/graph_drawer.py:221:55: E231 missing whitespace after ','
Please fix the above Flake8 warnings.
Error: Process completed with exit code 1.
```

**Review by khabinov — APPROVED** [review]
LGTM

**Pull request closed without merging**
