### PR TITLE
Add doc for torch.distributed.breakpoint

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #115656
* #115705

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]
lgtm, we might need to have a separate fix about the `breakpoint` impl as last time I tried it seems have some circular dependency problem

**Comment by wconstab** [comment]
> lgtm, we might need to have a separate fix about the breakpoint impl as last time I tried it seems have some circular dependency problem

what do you mean? where is there a circular dependency problem?

**Comment by wanchaol** [comment]
> what do you mean? where is there a circular dependency problem?

I can't exactly recall my last trial so you can ignore that message haha, as long as we have some of our example scripts working that should be fine

**Review by fegin — APPROVED** [review]
Added topic: docs

**Pull request closed without merging**
