### PR TITLE
[quant][pt2e] Refactor node.meta["target_dtype_info"] to allow generalized observer/fq configuration for output

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #97483
* #97472

Summary:
This is a follow up PR to generalize the way of how users could configure what observer/fq class they want to use for output of the node,
follow up item (1) in https://github.com/pytorch/pytorch/pull/92641

Previously people will configure the observer/fq class in the following manner:

node.meta["target_dtype_info"] = {
  "input_act_obs_or_fq_ctr": obs1,
  "weight_obs_or_fq_ctr": obs2,
  "bias_obs_or_fq_ctr": obs3,
  "output_obs_or_fq_ctr": obs4,
}

this works for existing use cases but it's not general enough, since output may have more complicated structure. NOTE: this PR did not add support for the more complicated structure, since it may not be needed, only the first case is supported right now:
```
# case 1: supported in this PR
node.meta["target_dtype_info"] = {
  "input_obs_or_fq_ctrs": (obs1, obs2, obs3),
  "output_obs_or_fq_ctrs": obs4,
}

# case 2: we can add support for this in the future if needed
node.meta["target_dtype_info"] = {
  "input_obs_or_fq_ctrs": (obs1, (obs2, obs3),)
  # this matches the structure of the output
  "output_obs_or_fq_ctrs": (obs4, obs5),
}
```

Next: accept an object that can annotate the graph with the above config

Test Plan:
python test/test_quantization.py TestQuantizeFx
python test/test_quantization.py TestQuantizeFxOps
python test/test_quantization.py TestQuantizeFxModels
python test/test_quantization.py TestQuantizePT2E
python test/test_quantization.py TestQuantizePT2EModels

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D44389340](https://our.internmc.facebook.com/intern/diff/D44389340)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44389340).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44389340).

**Comment by vkuzo** [comment]
> this works for existing use cases but it's not general enough, since output may have more complicated structure.

do we have context on what specifically needs the more complicated structure today?

**Comment by jerryzh168** [comment]
> > this works for existing use cases but it's not general enough, since output may have more complicated structure.
> 
> do we have context on what specifically needs the more complicated structure today?

maybe LSTM, but not verified yet. so I'll just start with this and we can expand it later if needed

**Comment by kimishpatel** [comment]
> > > this works for existing use cases but it's not general enough, since output may have more complicated structure.
> > 
> > 
> > do we have context on what specifically needs the more complicated structure today?
> 
> maybe LSTM, but not verified yet. so I'll just start with this and we can expand it later if needed

@vkuzo so one thing I wanted to hear from you about is this: Can we jsut associate quantization spec on each node (there is a question on tuples but lets get to that in a bit).

A thing that came up in my discussions with Jerry was,  a case like this
```
n1 = aten.some_op
o1 = obs(n1)
n2 = aten.some_op(o1)
o2 = ob(n2)
```
Now if n2 wants to quantize its inputs differently then you cannot use the above pattern and we need
```
n1 = aten.some_op
o1 = obs(n1)
o1_1 = obs(o1)
n2 = aten.some_op(o1_1)
o2 = ob(n2)
```

Do we really have usecases where we need the latter? If not I think quite a bit of this can be simplified without worrying about matching node's arg structure.

Now for when the node's output is tuple like in the case of max_pool2d_with_indices, usually the output has getitem nodes on it so that actual output of maxpool can be used. Like
```
output = max_pool2d_with_indices
maxpool_output = getitem(output, 0)
indices = getitem(output, 1)
```
So in that case we should put observer really at maxpool_output.

SO if we can really just consider associating quantization spec/observers with nodes (i.e. outputs) it would simplify most of this.

**Comment by vkuzo** [comment]
> > > > this works for existing use cases but it's not general enough, since output may have more complicated structure.
> > > 
> > > 
> > > do we have context on what specifically needs the more complicated structure today?
> > 
> > 
> > maybe LSTM, but not verified yet. so I'll just start with this and we can expand it later if needed
> 
> @vkuzo so one thing I wanted to hear from you about is this: Can we jsut associate quantization spec on each node (there is a question on tuples but lets get to that in a bit).
> 
> A thing that came up in my discussions with Jerry was, a case like this
> 
> ```
> n1 = aten.some_op
> o1 = obs(n1)
> n2 = aten.some_op(o1)
> o2 = ob(n2)
> ```
> 
> Now if n2 wants to quantize its inputs differently then you cannot use the above pattern and we need
> 
> ```
> n1 = aten.some_op
> o1 = obs(n1)
> o1_1 = obs(o1)
> n2 = aten.some_op(o1_1)
> o2 = ob(n2)
> ```
> 
> Do we really have usecases where we need the latter? If not I think quite a bit of this can be simplified without worrying about matching node's arg structure.
> 
> Now for when the node's output is tuple like in the case of max_pool2d_with_indices, usually the output has getitem nodes on it so that actual output of maxpool can be used. Like
> 
> ```
> output = max_pool2d_with_indices
> maxpool_output = getitem(output, 0)
> indices = getitem(output, 1)
> ```
> 
> So in that case we should put observer really at maxpool_output.
> 
> SO if we can really just consider associating quantization spec/observers with nodes (i.e. outputs) it would simplify most of this.

Here is an example of op0 using quantization to int8 and op1 using quantization to int16 which requires input and output configuration for each op:

```
x0_fp32 -> 
(fp32_to_int8 -> int8_to_fp32 -> op0 -> fp32_to_int8 -> int8_to_fp32) -> 
(fp32_to_int16 -> int16_to_fp32 -> op1 -> fp32_to_int16 -> int16_to_fp32) -> 
x1_fp32
```

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44389340).

**Comment by jerryzh168** [comment]
deprioritized for now, we can redo this after we get more user data

**Pull request closed without merging**
