### PR TITLE
Enable rsqrt

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89771

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]
Any reason you stumbled upon this? I stumbled upon this as well while trying to debug accuracy issues, but wasn't sure if this was the problem.

**Comment by eellison** [comment]
It was something I meant to enable previously but was running into a weird compilation hang. Was looking back into it for perf not for correctness though.

**Pull request closed without merging**
