### PR TITLE
Ablate TORCH_CUDA_ARCH_LIST from torchaudio install

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #106826

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Comment by ezyang** [comment]
```
2023-08-09T03:28:09.8171392Z       CMake Error at /opt/conda/envs/py_3.10/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:279 (message):
2023-08-09T03:28:09.8171887Z         CMAKE_CUDA_ARCHITECTURES:
2023-08-09T03:28:09.8172168Z       
2023-08-09T03:28:09.8172455Z           Maxwell-real
2023-08-09T03:28:09.8172730Z       
2023-08-09T03:28:09.8173050Z         is not one of the following:
2023-08-09T03:28:09.8173324Z       
2023-08-09T03:28:09.8173730Z           * a semicolon-separated list of integers, each optionally
2023-08-09T03:28:09.8174164Z             followed by '-real' or '-virtual'
2023-08-09T03:28:09.8174571Z           * a special value: all, all-major, native
2023-08-09T03:28:09.8174867Z       
2023-08-09T03:28:09.8175204Z       Call Stack (most recent call first):
2023-08-09T03:28:09.8175593Z         CMakeLists.txt:82 (enable_language)
```

**Comment by albanD** [comment]
Why?

**Comment by ezyang** [comment]
It shouldn't be necessary to manually specify the cuda archs (but smh it is)

**Review by albanD — COMMENTED** [review]
Is it a problem of our CI machine config that prevent automatic arch detection from working properly?

**Comment by ezyang** [comment]
Not sure, since everyone else figures it out right, I figured it is a problem in torchaudio packaging. Not going to touch it though

**Pull request closed without merging**
