### PR TITLE
setting NO_AVX2=1 env var disable AVX2/FMA support

### PR DESCRIPTION
**Pull request by eLvErDe**
Because you may build PyTorch on a CPU with AVX2 and FMA support but need your build to be compatible with older CPUs...

### CODE REVIEW

**Comment by soumith** [comment]
libTH.so should already be runnable on non-AVX machines (even if it was built on an AVX2-enabled machine). This is because we enable AVX2 only on specific files/functions which actually have runtime dispatch (if AVX2 is not found, the dispatch falls back to the AVX version, if AVX is not found, the dispatch falls back to SSE version)

**Comment by eLvErDe** [comment]
Might be compatible but the code built with "-mavx2 -mfma" won't run for sure.

See torch/lib/TH/cmake/FindSSE.cmake

**Comment by soumith** [comment]
it wont run, and it wont be attempted to run. At runtime TH checks for the CPU features that are available and if AVX2 is not available it wont run any of the AVX2 compiled functions.

**Comment by apaszke** [comment]
@soumith the problem is that if one passes `-mavx2`, then the compiler might insert them in vectorized loops outside of `THVector`

**Comment by eLvErDe** [comment]
Yup, that's my point

**Comment by soumith** [comment]
but we dont pass `-mavx2` on all files. We only pass them on specific files covered by the runtime-dispatch codepaths.

Follow `C_AVX2_FOUND` in the TH/CMakeLists.txt file and you'll see that only `vector/AVX2.c` and `generic/simd/convolve.c` are given the flag.

**Comment by soumith** [comment]
@eLvErDe let me know if you are seeing symptoms where the binaries are not actually running on non-AVX2 machines, and if so what the error messages you see. From my understanding this PR is not necessary (I test pytorch binaries on non-AVX2 machines to make sure this runtime dispatch actually works).

**Comment by eLvErDe** [comment]
@soumith ok, I'll give a try. Is a simple torchvision benchmark would be enough to be sure to triggers this code ?

**Comment by soumith** [comment]
@eLvErDe yes.

**Comment by soumith** [comment]
Or even:

```python
import torch
x = torch.randn(10)
y = torch.randn(10)
z = x + y
```

**Comment by eLvErDe** [comment]
Ok, I'll do tomorrow morning (gmt+1) and let you know, thanks

**Pull request closed without merging**
