### PR TITLE
Fix rand_like nvprim meta function.

### PR DESCRIPTION
**Pull request by kevinstephano**
Really minor fix necessary to work with TorchDynamo.

### CODE REVIEW

**Review by IvanYashchuk — COMMENTED** [review]
I wonder if we add to common_methods_invocations.py would it enable FakeTensor tests that use this meta function implementation?
```py
    PythonRefInfo(
        "ops.nvprims.rand_like",
        torch_opinfo_name="rand_like",
        supports_out=False,
        decorators=(
            # Skip tests that try to compare concrete values
        ),
    ),
```

**Review by mruberry — APPROVED** [review]
Stamped

**Review by jjsjann123 — APPROVED** [review]
stamp to show emotional support

**Pull request closed without merging**
