### PR TITLE
Find hip properly

### LINKED ISSUE #41886: [ROCm] [Build Error] [CMake] Cannot find hip
## 🐛 Bug

When compiling pytorch with ROCm, pytorch fails when trying to find rocblas, because rocblas fails to find hip.

```
***** Library versions from cmake find_package *****

rocrand VERSION: 2.10.1.0
hiprand VERSION: 2.10.1.0
CMake Error at /usr/share/cmake-3.18/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findhip.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "hip", but
  CMake did not find one.

  Could not find a package configuration file provided by "hip" with any of
  the following names:

    hipConfig.cmake
    hip-config.cmake

  Add the installation prefix of "hip" to CMAKE_PREFIX_PATH or set "hip_DIR"
  to a directory containing one of the above files.  If "hip" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /opt/rocm/rocblas/lib/cmake/rocblas/rocblas-config.cmake:89 (find_dependency)
  cmake/public/LoadHIP.cmake:131 (find_package)
  cmake/public/LoadHIP.cmake:169 (find_package_and_print_version)
  cmake/Dependencies.cmake:995 (include)
  CMakeLists.txt:411 (include)


-- Configuring incomplete, errors occurred!
```

## To Reproduce

1. git clone
2. python setup.py build

## Expected behavior

The build should successfully complete

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.1
 - OS (e.g., Linux): Arch Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py build`
 - Python version: 3.8.3
 - CUDA/cuDNN version: N/A
 - GPU models and configuration:
 - Any other relevant information: ROCm

## Additional context

Downstream issue: https://github.com/rocm-arch/python-pytorch-rocm/issues/2

cc @malfet @jeffdaily @sunway513

### PR DESCRIPTION
**Pull request by acxz**
Fixes #41886

### CODE REVIEW

**Comment by t-vi** [comment]
I think finding RCCL does not quite work yet:
```
...
INFOForcing USE_SYSTEM_NCCL to ON since it's required by using RCCL
19:40:11 -- RCCL NOT Found!
19:40:11 -- Enabling sccache for CXX
19:40:11 -- Enabling sccache for C
...
[ 88%] Linking CXX shared library ../lib/libtorch_hip.so
20:25:02 /usr/bin/ld: cannot find -l__caffe2_nccl
20:25:02 collect2: error: ld returned 1 exit status
20:25:02 caffe2/CMakeFiles/torch_hip.dir/build.make:5697: recipe for target 'lib/libtorch_hip.so' failed
20:25:02 make[2]: *** [lib/libtorch_hip.so] Error 1
```

**Review by t-vi — APPROVED** [review]
Looks good, thank you @acxz .

**Comment by t-vi** [comment]
Looks good to me, let's give @jeffdaily a chance to look before I ask for merging.

**Review by malfet — APPROVED** [review]

**Comment by jeffdaily** [comment]
LGTM

**Comment by t-vi** [comment]
@malfet thank you for importing. It seems that it triggered something with the FB-internal checks. If we can do anything to help it along, we'd be glad to.

**Pull request closed without merging**
