### PR TITLE
Refactor ShapeGuardPrinter for future C++ addiiton

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #140756
* #139899
* __->__ #140968

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv @voznesenskym @penguinwu @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]
Refactor LGTM. cc @ezyang for extra eyes.

**Comment by ezyang** [comment]
I only skimmed but it doesn't look obviously wrong

**Comment by ezyang** [comment]
The downside to doing it this way is you will have to add call sites for C++ printing everywhere again. But maybe it's not so bad if there are only two.

**Comment by isuruf** [comment]
I had the same thought as first, but the diff is not that bad. See https://github.com/pytorch/pytorch/pull/139899/files#diff-03557db7303b8540f095b4f0d9cd2280e1f42f534f67d8695f756ec6c02d3ec7L4406-R5159

**Pull request closed without merging**
