### PR TITLE
tensor coalescing dance to avoid copy for cudnn rnn parameters

### PR DESCRIPTION
**Pull request by jekbradbury**
Intended to solve #914, and currently passing tests.
I haven't yet run memory/performance comparisons, but I wanted to see if @apaszke and others are okay with the approach I've taken. I also coalesce on the gradients during the backward pass, which should save a memcpy but doesn't save any memory unless we can get the tensors that will receive the weight gradients to persist between calls.

### CODE REVIEW

**Comment by jekbradbury** [comment]
Looks like it saves ~270 μs per call (from 23.63 ms/batch to 23.36 ms/batch for PTBLM example on K80). The default settings for that example have only 653,000 LSTM parameters, so it only saves 2.5 MiB of memory (594 MiB to 592 MiB).

It also cuts 5-10% from total runtime and about 40% from steady-state memory usage including cache pool for the (extreme) tree2tree.py benchmark (3877MiB to 2154MiB).

**Comment by ngimel** [comment]
On PTBLM you don't expect a big effect (it's already doing 35 length sequence, right?). It should show up when you are trying to use nn.LSTM in place of nn.LSTMCell for a sequence of length 1, something like in #914.

**Comment by jekbradbury** [comment]
I forgot that there was repro code in the issue... If you use the repro code with sequence length 20 (about the most that will fit in memory on pytorch master), the memory usage goes from 11433 MiB to 6778 MiB and the time for 100 epochs goes from 63.7 s to 49.7 s. Looks like I really need to figure out how to reuse the gradient buffer, since I'm only getting half the savings we need to say the issue is closed.

**Comment by apaszke** [comment]
One thing I don't really like about this solution (and what makes my last proposal so complicated), is that it mutates the storages that param tensors use. This is undesired because it silently breaks sharing and can create subtle errors. 

I'd much rather keep the parameters immutable during forward, and keep the caching within the function itself. Another option would be to finally come up with a good API that can change modules in a way that makes them conform to whatever a given backend wants.

**Comment by jekbradbury** [comment]
I don't believe it actually breaks any sharing that people can currently rely on. For instance, if you share two of the LSTM parameters with each other (e.g., you share the fwd and bwd weights), two of the tensors in the list of weights will be identical. Then the coalescing will mutate that shared tensor to point to a different storage, and on the next `cudnn.rnn.forward` call `check_coalesced` will return `False` and the parameters will have to be copied (there's no alternative in any case). If you share an LSTM parameter with another parameter elsewhere in the model, the shared tensor will be mutated to point to the relevant view on the cuDNN buffer; this will allow the next call to avoid a parameter copy while maintaining the sharing.

**Comment by ngimel** [comment]
I don't find this possible breaking of sharing argument too compelling. 
data_parallel also mutates the storages that param tensors use, so if you wrap part of your model in data_parallel, and share parameters in wrapped and unwrapped parts, that would break too, but we are not particularly concerned about it?

**Comment by apaszke** [comment]
Data parallel doesn't touch the storages IIRC. It coalesces them out of place.

**Comment by apaszke** [comment]
I'm not saying it will break sharing of Parameters. It will be all fine on the Variable level. It's only going to break on Tensor level

**Comment by jekbradbury** [comment]
The problem arises when one parameter is a view on another (so they're different Parameters and different Tensors, but share a Storage). Does this currently work with `data_parallel`?

**Comment by apaszke** [comment]
Yes, it's all good. Still, I wouldn't consider adding such restriction to DataParallel a big problem because it's a fairly magical container that makes things run faster. LSTM is a core module that actually computes something, and making it mutate stuff like this seems less intuitive to me.

Also, it's not only the problem with parameters being views on each other. For example, you could allocate a large flat tensor and set the weights to view on its parts. Then you would use that to compute global statistics. It's not an unreasonable use case and this change would break it.

**Comment by jekbradbury** [comment]
From nvprof on the example from the issue: I'm getting 8.0 ms for one step of cuDNN forward on this branch, 8.4 ms for one step of the non-cuDNN (fused) forward, and 13.5 ms for one step of cuDNN forward on master. On backward, it's cuDNN on this branch 17.0 ms, cuDNN on master 20.8 ms, and non-cuDNN fused 23.7 ms, for a total of 25.0 ms per step on this branch, 34.3 ms per step on master, and 32.1 ms per step with the non-cuDNN kernel.

**Comment by soumith** [comment]
okay so James just needs to modify this logic to contain/cache the coalescing right? and then we're good to go?

**Comment by apaszke** [comment]
Caching coalescing isn't a trivial thing. We could try to add that weakref hack I proposed some time ago. I don't have any other ideas

**Comment by jekbradbury** [comment]
The logic can’t be modified here because the cudnn functions are stateless; the cache probably needs to be an instance attribute of the CudnnRNN Function. Adam is right that the way to do that is not obvious.

**Comment by jekbradbury** [comment]
Hmm. What do people think of the following?
We want to avoid both the extra memory usage (which prevents using cuDNN for unrolled RNNs) and the unnecessary memcpy (which takes up >25% of computation time for unrolled cuDNN RNNs of batch size 64, and a proportionally higher fraction for smaller batch sizes). We also want to support user-provided parameters with arbitrary Storage, Tensor, or Parameter sharing relationships, without breaking those relationships.
This requires at least one `malloc` and one `memcpy` per RNN, per forward pass of the overall network (because we can't mutate the original parameter objects), and at least one `malloc` and one `memcpy` per RNN per backward pass of the network (because we need to copy the accumulated gradients into the right places in the potentially-not-moveable gradient tensors). In particular, we want the first `malloc`/`memcpy` to happen the first time an RNN is used during a particular iteration, and we want the second one to happen at the corresponding time during the backward pass. But neither `Module`s nor `Function`s are aware of iterations, and what matters isn't actually iterations, it's _parameter updates_.
So it should be possible to make `zero_grads` flush the coalesced param/grad cache, so that the next time an RNN's forward pass happens it knows to perform the `malloc`/`memcpy`, cache the result as a class attribute of the Function, and store in an instance attribute the fact that the gradient copy needs to happen on the backward pass.

Maybe this interacts in complicated ways with repeated gradient passes? It definitely doesn't need to support double backward because the double-backward gradient codepath for RNNs won't use cuDNN.

**Comment by jekbradbury** [comment]
A partial solution could be to create weights in the pattern cuDNN expects by default in the nn.RNN constructors, make use of those in-place if the user doesn't mess with them, and fall back to the copy behavior if the user does. We'd still have to think about how to fix the similar memory usage on backward though.

**Comment by ngimel** [comment]
A problem with that is that DataParallel is guaranteed to mess with them (unless .parameters() is somehow modified to return a single tensor for all the weights, but that is wrong on many levels).

**Comment by soumith** [comment]
i'm closing this. clearly this is not going in.
After Adam comes to FB in the second week of July, we'll design a proper API to solve this issue and give everyone true happiness.

**Pull request closed without merging**
