### PR TITLE
[JIT] Fix type annotations of pooling modules

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#47888 [JIT] Fix type annotations of pooling modules**

Fix for https://github.com/pytorch/pytorch/issues/45904

All of the pooling modules except MaxUnpool and LPPool return either a `Tensor `or `[Tensor, Tensor]`. The current type annotations are inaccurate, and prevent scripting the module if `return_indices` is set as true in the module. 

There's not a great way to make this agree with mypy because the overload is dependent on the value of `return_indices`, an attribute.

### CODE REVIEW

**Comment by ezyang** [comment]
cc'ing @rgommers and @malfet for visibility

**Review by ezyang — APPROVED** [review]
This leaves me a bad taste in my mouth, but that isn't any reason to block landing this particular PR. What is really irritating, though, is that I can't do the less useful type `Union[Tensor, Tuple[...]]` because JIT will choke on it. There still ought to be a way to mark types to be ignored by JIT.

**Comment by rgommers** [comment]
Someone will run into this again when removing the `ignore_errors = True` in `mypy.ini` for `modules.pooling`. Any annotating the return as `-> Any` isn't supported either I think (gh-33844).

Adding a comment above the first `def forward` in `pooling.py` would be useful, to avoid the next person re-investigating this and eventually finding this PR.

> There still ought to be a way to mark types to be ignored by JIT.

I can't find an existing issue for that so quickly, do you know if there is one?

**Comment by eellison** [comment]
@ezyang yea, agreed that would be nice. @rgommers i think this issue ed opened here is related: https://github.com/pytorch/pytorch/issues/39670

**Comment by rgommers** [comment]
This is about ready to land, modulo adding a comment and a rebase. Could this be landed before the bot closes the PR?

**Comment by gmagogsfm** [comment]
Cleaning my github dashboard, doesn't seem this PR is needed due to inactivity, removing myself as reviewer.

**Comment by garymm** [comment]
@eellison any reason this hasn't been merged yet?

**Comment by garymm** [comment]
I rebased this and fixed some issues in tests: https://github.com/pytorch/pytorch/pull/65847

If a FB employee would please review and import I'd appreciate it.

**Comment by ezyang** [comment]
@eellison is an fb employee 😂

**Comment by eellison** [comment]
Hi @garymm i moved projects and this sort of slipped out under me. as you see, it's pretty close, if you don't mind rebasing/getting CI to pass i'll review and land, thanks for your help!

**Comment by garymm** [comment]
Closing this in favor of #65847

**Pull request closed without merging**
