### PR TITLE
Profiler binding speed up

### PR DESCRIPTION
**Pull request by albanD**
Speed this up by skipping some Tensor creation and using manual python binding that are significantly faster than the torch.ops one.

A quick high level benchmark. Note that this is VERY noisy and I used the regular time to try and get comparable runs.
Before:
```bash
$ python foo.py 
Regular time: 4.503569602966309e-06
With record time: 9.866402149200439e-06
```

After:
```bash
$ python foo.py 
Regular time: 4.48786735534668e-06
With record time: 7.257213592529297e-06
```

<details>
  <summary>Benchmarking script</summary>

```python
import torch
import time
from torch.profiler import record_function

x = torch.randn(10, 10)

def timeit(func, repeat, *args, **kwargs):
    start = time.time()
    for _ in range(repeat):
        func(*args, **kwargs)
    return (time.time() - start) / repeat

def with_record(x):
    with record_function("overhead_detection"):
        y = x * 2 + 4

def with_profiler(x):
    with torch.profiler.profile() as prof:
        with record_function("overhead_detection"):
            y = x * 2 + 4

# warmup
timeit(lambda x: x * 2 + 4, 100, x)
# real test
raw_time = timeit(lambda x: x * 2 + 4, 100000, x)
with_record_time = timeit(with_record, 100000, x)
# with_profiler_time = timeit(with_profiler, 100000, x)

print(f"Regular time: {raw_time}")
print(f"With record time: {with_record_time}")
# print(f"With profiler time: {with_profiler_time}")
```  

</details>

### CODE REVIEW

**Comment by robieta** [comment]
You'll get better results if you use Timer. (Although you have to play with the internals a bit...)
<details>
  <summary>Benchmarking script</summary>
  
 ```
import contextlib
import os

import torch
from torch.utils.benchmark import Timer

# contextlib.redirect_stderr doesn't work
devnull = os.open('/dev/null', os.O_WRONLY)
stderr = os.dup(2)

@contextlib.contextmanager
def hide_stderr():
    """ Low level stderr supression. """
    os.dup2(devnull, 2)
    yield
    os.dup2(stderr, 2)

class ProfilerTimer(Timer):
    def _timeit(self, number: int) -> float:
        with hide_stderr(), torch.profiler.profile():
            result = super()._timeit(number)
        return result

setup = "x = torch.randn(10, 10)"
stmt = """
    with torch.profiler.record_function("overhead_detection"):
        y = x * 2 + 4
"""

print(Timer(stmt, setup).blocked_autorange(min_run_time=3), "\n")
print(ProfilerTimer(stmt, setup).blocked_autorange(min_run_time=3))

 ```
 </details>
 
 ```
 <torch.utils.benchmark.utils.common.Measurement object at 0x7ff829bd4a50>
stmt:
  with torch.profiler.record_function("overhead_detection"):
      y = x * 2 + 4

setup: x = torch.randn(10, 10)
  Median: 22.83 us
  IQR:    0.52 us (22.57 to 23.09)
  132 measurements, 1000 runs per measurement, 1 thread

<torch.utils.benchmark.utils.common.Measurement object at 0x7ff829bd49d0>
stmt:
  with torch.profiler.record_function("overhead_detection"):
      y = x * 2 + 4

setup: x = torch.randn(10, 10)
  Median: 29.77 us
  IQR:    0.38 us (29.61 to 29.99)
  101 measurements, 1000 runs per measurement, 1 thread
 ```
 
 It's not obvious to me why my numbers are so much higher than yours, but I see the difference even with your script so it must just be env or build flags.

**Review by robieta — APPROVED** [review]
LGTM. One question: how with this interact with FC?

**Comment by albanD** [comment]
Running internal test right now. In the worst case, we will have to land the new ops and wait two weeks to add the code that uses them.

**Comment by albanD** [comment]
No one seems interested by this. So closing and keeping the simple code only.

**Pull request closed without merging**
