### PR TITLE
Count the number of entries directly in avg_pool2d lowering

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #116756
* __->__ #121429
* #116085

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by peterbell10 — APPROVED** [review]

**Comment by peterbell10** [comment]
For some reason HuggingFace is showing lots of regressions on the benchmarks. @isuruf can you look into these to see:
1. can you reproduce the regression on paperspace
2. are the models calling `avg_pool` and if so, with what arguments
3. what's going wrong with the performance

https://hud.pytorch.org/benchmark/huggingface/inductor_with_cudagraphs?startTime=Mon%2C%2004%20Mar%202024%2017%3A41%3A01%20GMT&stopTime=Mon%2C%2011%20Mar%202024%2017%3A41%3A01%20GMT&granularity=hour&mode=training&dtype=amp&lBranch=gh/isuruf/35/orig&lCommit=a70ae34c8fbe8b551cac871f772a282c538e69fe&rBranch=main&rCommit=291ce86a6cece257104a973f6e7af54e67252432

**Review by peterbell10 — CHANGES_REQUESTED** [review]
Benchmarks need investigation.

**Comment by isuruf** [comment]
I tried `DebertaForMaskedLM` and it looks like it does not call `AvgPool{1, 2, 3}d` and I can't seem to reproduce the regression on paperspace. Maybe it's just a fluke and we should rerun?

**Comment by peterbell10** [comment]
I did run the benchmarks on this PR and the next one and both showed these regressions. You could try rebasing the stack on one of the commits that the hud has results for, in case the regression was caused by some other commit on main.

**Review by peterbell10 — APPROVED** [review]

**Pull request closed without merging**
