### PR TITLE
add channels last for GroupNorm

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #58348 opitimze ConvTransposedND with mkldnn float32 and bfloat16 on CPU
* #55864 enable BFloat16 mkldnn_convolution on both contiguous and channels last memory format
* #55584 add channels last (2d) support for mkldnn_convolution
* #51185 add channels last support for ConvTranspose2d
* #50573 add channels last support for PixelShuffle and PixelUnshuffle
* #50247 add channels last support for ChannelShuffle
* #49984 add channel last support for MaxUnpool2d
* **#49821 add channels last for GroupNorm**

Differential Revision: [D26007053](https://our.internmc.facebook.com/intern/diff/D26007053)

### CODE REVIEW

**Comment by mingfeima** [comment]
From performance point of view, `GroupNorm` favors NCHW over NHWC, as `GroupNorm` is accumulating mean and rstd from dimensions of DHW (NCHW = N{GD}HW with C = {GD}) while for channels last memory format, the physical memory layout would be NHW{GD}.

The implementation of this patch tries to do reduce on NHWC=>NC first and then NC=> NG, in this way we can always use C for vectorization. Yet the performance of channels last is still slightly worse than contiguous format:

[paper](https://arxiv.org/abs/1803.08494) here replaces BN with GN in RN50, so I am benchmarking RN50 BN sizes here:
single core inference result from Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (Unit: ms per iteration):


input sizes | nchw | nhwc
-- | -- | --
[1,64,112,112] | 0.290 | 0.430
[1,64,56,56] | 0.103 | 0.119
[1,256,56,56] | 0.293 | 0.410
[1,128,56,56] | 0.156 | 0.222
[1,128,28,28] | 0.050 | 0.058
[1,512,28,28] | 0.155 | 0.219
[1,256,28,28] | 0.091 | 0.112
[1,256,14,14] | 0.027 | 0.032
[1,1024,14,14] | 0.092 | 0.116
[1,256,14,14] | 0.026 | 0.031
[1,512,14,14] | 0.052 | 0.056
[1,512,7,7] | 0.021 | 0.022
[1,2048,7,7] | 0.056 | 0.064

**Review by xiaomengy — APPROVED** [review]
LGTM, I will try to add the CUDA impl later to see what performance we can reach on CUDA for NHWC format.

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D26007053).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D26007053).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D26007053).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D26007053).

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Please rebase, we had to revert thcc_conv2 PR, so I need to know if we can continue this stack in parallel to fixing that one.

**Comment by mingfeima** [comment]
@VitalyFedyunin rebased, please check!

**Comment by mingfeima** [comment]
@VitalyFedyunin rebased, please check!

**Comment by mingfeima** [comment]
rebased!

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D26007053).

**Pull request closed without merging**
