### PR TITLE
squash xblock for persistent inner reduction

### PR DESCRIPTION
**Pull request by ngimel**
Currently layer norm kernel performance is pretty bad due to triton perf bug https://gist.github.com/ngimel/c1e7f70f8268f038e710e835b0065f63, but since XBLOCK for persistent reduction is `1` we can just drop this dimension and operate on 1d tensors (and then perf of ln kernels improves a lot) 
Perf results http://hud.pytorch.org/benchmark/compilers?startTime=Mon%2C%2022%20May%202023%2001%3A27%3A25%20GMT&stopTime=Mon%2C%2029%20May%202023%2001%3A27%3A25%20GMT&suite=torchbench&mode=training&dtype=amp&lBranch=ngimel/persistent_1d&lCommit=1d5175f5e682f37aae15fd217bc3767e1788bacf&rBranch=main&rCommit=c9f4f01981fd73fcc7c27676cc50230cd1b5bc22, approx 4% on hf

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by ngimel** [comment]
@pytorchbor merge

**Comment by ngimel** [comment]
cc @jataylo, I had to exclude rocm from this optimization, because rocm is on the old triton version that doesn't have `tl.reduce` and workaround doesn't work for 1d tensors (with some fixes it worked for me locally when I forced the workaround path in triton_helpers.py but it was still failing on rocm CI https://github.com/pytorch/pytorch/pull/102444/commits/d97b63e28438a3f9a071ee7262d825d0583c4e9b). Can you guys update your triton to a later pin so that `tl.reduce` workaround is not longer needd?

**Comment by jataylo** [comment]
> cc @jataylo, I had to exclude rocm from this optimization, because rocm is on the old triton version that doesn't have `tl.reduce` and workaround doesn't work for 1d tensors (with some fixes it worked for me locally when I forced the workaround path in triton_helpers.py but it was still failing on rocm CI [d97b63e](https://github.com/pytorch/pytorch/commit/d97b63e28438a3f9a071ee7262d825d0583c4e9b)). Can you guys update your triton to a later pin so that `tl.reduce` workaround is not longer needd?

Thanks for the heads up @ngimel, we hit a blocker that stopped us updating triton for awhile to bring in the `tl.reduce` change, we've fixed that associated issue and we are hoping to be able to move our triton commit forward shortly.

cc: @dllehr-amd

**Pull request closed without merging**
