### PR TITLE
Refactor all top level usages of record_shapeenv_event to ShapeEnv class

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #123735

This ensures that first argument to record_shapeenv_event is a ShapeEnv
so we can appropriately short circuit when recording is not in progress.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by ysiraichi — APPROVED** [review]
LGTM.

**Review by zou3519 — APPROVED** [review]

**Review by albanD — APPROVED** [review]
yep!

**Comment by ezyang** [comment]
I just restored the private API that was deleted

**Comment by bhack** [comment]
@ezyang This started to appear at inference with nightly;

`failed while running evaluate_expr(*(Eq((u0//7), u0), None), **{'fx_node': None, 'size_oblivious': True})`

Is this user actionable?

**Comment by ezyang** [comment]
Oh I noticed this one. No it is not, ordinarily it precedes an exception but the exception is being caught and suppressed

**Pull request closed without merging**
