### PR TITLE
Implement meta functions for rshift and lshift

### LINKED ISSUE #103606: Write meta function for rshift
### 🐛 Describe the bug

This is to track support for adding rshfit meta function. While writing some de-quantization code this error popped up:
`NotImplementedError: could not find kernel for aten.__rshift__.Scalar at dispatch key DispatchKey.Meta`

### Versions

Nightly

### PR DESCRIPTION
**Pull request by drisspg**
Fixes #103606

Was using this script to exercise new code, cause I can never remember which test it is.
```
import torch

@torch.compile(fullgraph=True, dynamic=True)
def shift_right(tensor: torch.Tensor) -> torch.Tensor:
    return (tensor >> 2).to(torch.long)

def main():
    sample_input = torch.tensor([4, 4, 16, 32], dtype=torch.uint8)
    print(shift_right(sample_input))

if __name__ == "__main__":
    main()
```
And iterated through the error messages

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Hmm, it looks like the opinfos don't cover this, would you be willing to check in your test script as a one off?

**Comment by drisspg** [comment]
> Hmm, it looks like the opinfos don't cover this, would you be willing to check in your test script as a one off?

Forsure, `pytorch/test/dynamo/test_misc.py` a good location?

**Comment by ezyang** [comment]
Or maybe test_unspec.py

**Pull request closed without merging**
