### PR TITLE
Fix decomp for aten.baddbmm

### PR DESCRIPTION
**Pull request by SherlockNoMad**
Summary:
aten.baddbmm with fp16 inputs are decomposed to aten.bmm in fp32. 
This resulted in performance regression.

For more details, see https://docs.google.com/document/d/1OOV1UaiwcQH58aGzvJByUn29i1wLphey4mXqcvS60cM/edit?usp=sharing

For following model
```
import torch
import torch.export._trace
from torch._inductor.decomposition import decompositions, get_decompositions
from torch.fx.experimental.proxy_tensor import make_fx


class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.weight = torch.nn.Parameter(torch.randn(64, 64, 192, dtype=torch.float16))
        self.bias = torch.nn.Parameter(torch.randn(64, 1, 192, dtype=torch.float16))

    def forward(self, x):
        return torch.ops.aten.baddbmm.default(self.bias, x, self.weight)

x = torch.randn(64, 2048, 64, dtype=torch.float16, requires_grad=False)
inputs = (x,)

m = M()
gm = make_fx(m, pre_dispatch=False, decomposition_table=decompositions)(*inputs)
gm.print_readable(print_output=True)
```

Before the fix: 
```
class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: "f16[64, 2048, 64]"):
        # No stacktrace found for following nodes
        _param_constant0 = self._param_constant0
        convert_element_type: "f32[64, 1, 192]" = torch.ops.prims.convert_element_type.default(_param_constant0, torch.float32);  _param_constant0 = None
        convert_element_type_1: "f32[64, 2048, 64]" = torch.ops.prims.convert_element_type.default(arg0_1, torch.float32);  arg0_1 = None
        _param_constant1 = self._param_constant1
        convert_element_type_2: "f32[64, 64, 192]" = torch.ops.prims.convert_element_type.default(_param_constant1, torch.float32);  _param_constant1 = None
        bmm: "f32[64, 2048, 192]" = torch.ops.aten.bmm.default(convert_element_type_1, convert_element_type_2);  convert_element_type_1 = convert_element_type_2 = None
        add: "f32[64, 2048, 192]" = torch.ops.aten.add.Tensor(convert_element_type, bmm);  convert_element_type = bmm = None
        convert_element_type_3: "f16[64, 2048, 192]" = torch.ops.prims.convert_element_type.default(add, torch.float16);  add = None
        return convert_element_type_3
```

After the fix:
```
class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: "f16[64, 2048, 64]"):
        # No stacktrace found for following nodes
        convert_element_type: "f32[64, 2048, 64]" = torch.ops.prims.convert_element_type.default(arg0_1, torch.float32);  convert_element_type = None
        _param_constant0 = self._param_constant0
        convert_element_type_1: "f32[64, 64, 192]" = torch.ops.prims.convert_element_type.default(_param_constant0, torch.float32);  _param_constant0 = convert_element_type_1 = None
        _param_constant0_1 = self._param_constant0
        bmm: "f16[64, 2048, 192]" = torch.ops.aten.bmm.default(arg0_1, _param_constant0_1);  arg0_1 = _param_constant0_1 = None
        _param_constant1 = self._param_constant1
        add: "f16[64, 2048, 192]" = torch.ops.aten.add.Tensor(_param_constant1, bmm);  _param_constant1 = bmm = None
        return add
```

Test Plan: OSS CI

Differential Revision: D64148314

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Tests are pretty unhappy though

**Comment by ngimel** [comment]
Similar to addmm, you can't decompose mm and multiply/add because in cublas/blas the alpha-beta multiply-add are done in higher precision and only final result is downcast. Should this decomposition be excluded completely to avoid perf regression?

**Comment by SherlockNoMad** [comment]
> Similar to addmm, you can't decompose mm and multiply/add because in cublas/blas the alpha-beta multiply-add are done in higher precision and only final result is downcast. Should this decomposition be excluded completely to avoid perf regression?

I don't see an inductor lowering for aten.baddbmm, so it will fallback to aten kernel if we exclude it from decomposition. 
We can try it to see the perf implication. 

Another thought, should we write a lowering for aten.baddbmm? and force the epilogue add is always fused into bmm?

cc @eellison

**Comment by eellison** [comment]
@SherlockNoMad this is basically how we lower addmm. see, https://github.com/pytorch/pytorch/blob/e30c55ee527b40d67555464b9e402b4b7ce03737/torch/_inductor/kernel/mm_common.py#L471-L479

Should be the same epilogue as for baddmm

**Comment by ngimel** [comment]
Yeah but still once you truncate mm/bmm results into low precision, the damage is done, decomposed result will be less accurate?

**Comment by ngimel** [comment]
Hot take: addmm/baddbmm are like fma, and even python is adding fma, so no need to decompose them.

**Comment by eellison** [comment]
For the addmm epilogue, as with baddmm epilogue here, we're not actually decomposing it, and we preserve the precision of the accumulator. The `epilogue` is a convenience way of reusing same base template.

```
import torch
torch.set_default_device("cuda")
torch.set_default_dtype(torch.float16)

from torch._inductor import config
config.max_autotune_gemm_backends = "TRITON"

@torch.compile(mode='max-autotune')
def foo(inp, x, y):
    return torch.addmm(inp, x, y)


inp = torch.rand([1024])
x = torch.rand([1024, 1024])
y = torch.rand([1024, 1024])

foo(inp, x, y)
```

TORCH_LOGS="output_code" -> (acc now downcast

```
    ACC_TYPE : tl.constexpr = tl.float32
	...
    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=ACC_TYPE)
    for k in range(K, 0, -BLOCK_K):
        if EVEN_K:
            a = tl.load(A)
            b = tl.load(B)
        else:
            a = tl.load(A, mask=rk[None, :] < k, other=0.)
            b = tl.load(B, mask=rk[:, None] < k, other=0.)
        if B_PROLOGUE_CAST_TYPE is not None:
            b = b.to(B_PROLOGUE_CAST_TYPE)
        acc += tl.dot(a, b, allow_tf32=ALLOW_TF32)
        A += BLOCK_K * stride_ak
        B += BLOCK_K * stride_bk

    # rematerialize rm and rn to save registers
    rm = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    rn = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    idx_m = rm[:, None]
    idx_n = rn[None, :]
    mask = (idx_m < M) & (idx_n < N)

    # inductor generates a suffix
    xindex = idx_n + (1024*idx_m)
    tmp0 = tl.load(in_ptr0 + (tl.broadcast_to(idx_n, acc.shape)), mask, eviction_policy='evict_last').to(tl.float32)
    tmp1 = acc + tmp0
    tl.store(out_ptr0 + (tl.broadcast_to(xindex, acc.shape)), tmp1, mask)
''', device_str='cuda')
```

**Comment by ngimel** [comment]
Right, but that's when you generate triton mm kernel, not when you end up calling into cublas?

**Comment by eellison** [comment]
Hmm, so are you talking about changing the aten behavior, or the torch.compile behavior? Because if we're not decomposing it than we will have the same behavior as for eager.

**Comment by eellison** [comment]
Yea, agreed, I think we should just not decompose and add inductor template lowering for it.

**Pull request closed without merging**
