### PR TITLE
Replace open registration TensorTypeId with closed enum.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #25308 Tensor type set
* **#25252 Replace open registration TensorTypeId with closed enum.**

Our model going forward for extensions will be that you will have to
get an allocation of an ID in our system.  This is how things work
in practice today; we're just simplifying our underlying registration
since there is no need to have distributed registration.

There are some codemods in this diff:

```
codemod --extensions cpp,h,cc,cuh,py,in --exclude-paths=c10/core/TensorTypeId.h '([A-Za-z]+?)TensorId\(\)' 'TensorTypeId::\1TensorId'
codemod --extensions cpp,h,cc,cuh,py,in 'TensorTypeIds::undefined\(\)' 'TensorTypeId::UndefinedTensorId'
codemod --extensions cpp 'TensorType1\(\)' 'TensorTypeId::CPUTensorId'
codemod --extensions cpp 'TensorType2\(\)' 'TensorTypeId::CUDATensorId'
codemod --extensions cpp 'TensorType3\(\)' 'TensorTypeId::XLATensorId'
codemod --extensions cpp 'TensorType1' 'CPUTensorId'
codemod --extensions cpp 'TensorType2' 'CUDATensorId'
codemod --extensions cpp 'TensorType3' 'XLATensorId'
```

The main hand-written changes are in c10/core/TensorTypeId.h

Other manual fixes:

- aten/src/ATen/core/op_registration/op_registration.cpp - stop using
  std::string operator+
- aten/src/ATen/function_wrapper.py - handle a hardcoded TypeId() that
  wasn't caught by codemod
- torch/csrc/tensor/python_tensor.h - fix now incorrect forward declaration
  of TensorTypeId
- aten/src/ATen/core/op_registration/ - remove out-of-line registration

Differential Revision: [D17072001](https://our.internmc.facebook.com/intern/diff/D17072001/)

### CODE REVIEW

**Review by zdevito — APPROVED** [review]
Looks good

**Comment by ezyang** [comment]
Putting in the BC stub

**Comment by jgong5** [comment]
@ezyang I understand that closed enum simplifies the management of TensorTypeId but considering that PyTorch extension now allows open registration of ops and JIT optimization passes, would it be more flexible to allow open registration of TensorTypeId as well? With this, a PyTorch extension can support new devices without the need of modifying PyTorch core code.

@gujinghui @uyongw @Li-Jianhui

**Comment by ailzhang** [comment]
Hey @jgong5, thanks for reaching out! According to our experience adding TPU backend, we realized that adding a new device backend is tricky in terms of what functions to override and what to leave as it is. And we currently don't document that well. We'll likely add some documentation in the future about how XLA is integrated into PyTorch, so that new devices knows a list of ops to override (and their expected behaviors/precision/broadcasting). Switching from open registration to enums is simply because maintaining open registration is complicated, while the benefit is very small. We are happy to take PRs modifying TensorTypeId enum after some discussions with PyTorch team, to make sure it has a concrete plan to support PyTorch).

**Comment by ezyang** [comment]
Also, the plan on record has been to add some type ids reserved for user uses, if you just want to play around with it. The PR to do this hasn't been done yet, but we should soon.

**Comment by jgong5** [comment]
> Also, the plan on record has been to add some type ids reserved for user uses, if you just want to play around with it. The PR to do this hasn't been done yet, but we should soon.

@ezyang That's awesome. May I know when this would happen? @uyongw @gujinghui

**Comment by gujinghui** [comment]
> Also, the plan on record has been to add some type ids reserved for user uses, if you just want to play around with it. The PR to do this hasn't been done yet, but we should soon.

@ezyang 
May I know the progress of this feature? I'm very interesting in this. Many thanks.

**Comment by ezyang** [comment]
@jgong5 @gujinghui  https://github.com/pytorch/pytorch/pull/31830

**Pull request closed without merging**
