### PR TITLE
Make nn.RNN TorchScript compatible

### LINKED ISSUE #28418: [jit][script] torch.jit.script does not support nn.RNN
## 🐛 Bug

`torch.jit.script` does not seem to support `nn.RNN`

## To Reproduce

Running

```python
import torch
import torch.nn as nn

torch.jit.script(nn.RNN(32, 64, 1))
```

fails with

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    torch.jit.script(nn.RNN(32, 64, 1))
  File "/opt/anaconda/envs/test/lib/python3.6/site-packages/torch/jit/__init__.py", line 1203, in script
    return torch.jit.torch.jit._recursive.recursive_script(obj)
  File "/opt/anaconda/envs/test/lib/python3.6/site-packages/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "/opt/anaconda/envs/test/lib/python3.6/site-packages/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "/opt/anaconda/envs/test/lib/python3.6/site-packages/torch/jit/__init__.py", line 1423, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
RuntimeError: 
Tensor cannot be used as a tuple:
at /opt/anaconda/envs/test/lib/python3.6/site-packages/torch/nn/modules/rnn.py:184:67
    def forward(self, input, hx=None):
        is_packed = isinstance(input, PackedSequence)
        if is_packed:
            input, batch_sizes, sorted_indices, unsorted_indices = input
                                                                   ~~~~~ <--- HERE
            max_batch_size = batch_sizes[0]
            max_batch_size = int(max_batch_size)
        else:
            batch_sizes = None
            max_batch_size = input.size(0) if self.batch_first else input.size(1)
            sorted_indices = None
            unsorted_indices = None

        if hx is None:
```

## Expected behavior

That you can successfully jit `nn.RNN` like you can with `nn.LSTM` and `nn.GRU`.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.0
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.3.0               py3.6_cpu_0  [cpuonly]  pytorch
```

cc @suo

### PR DESCRIPTION
**Pull request by garymm**
Fixes #28418

### CODE REVIEW

**Comment by t-vi** [comment]
Not that I'd know, but would it be prudent to add a test to make sure the RNNs stay scriptable?

**Comment by garymm** [comment]
> Great patch! Not that I'd know, but would it be prudent to add a test to make sure the RNNs stay scriptable?

Yes, but I'm not sure where it'd go. If any reviewer has a suggestion, please LMK and I'll be glad to add a test.

We'll eventually test for this implicitly here once we can enable this test, which I hope is soon:

https://github.com/pytorch/pytorch/blob/f57c63032e920d7a24e11da4e253d594d8ca6dc2/test/onnx/test_pytorch_onnx_onnxruntime.py#L4102-L4103

**Comment by garymm** [comment]
@malfet could you please import?

**Review by malfet — CHANGES_REQUESTED** [review]
@garymm isn't it the same as https://github.com/pytorch/pytorch/pull/61274  but with lint fixed? If this is the case, they I prefer to land original change as it preserves the autorship

**Comment by garymm** [comment]
> @garymm isn't it the same as #61274 but with lint fixed? If this is the case, they I prefer to land original change as it preserves the autorship

Yes it is the same.
I didn't want to wait for the author to fix the lint errors. They had already ignored them for several months.

The original author is in the commit history, which I think will be preserved after squashing, but not sure. I can add a `Co-Authored-By` if that'd be helpful.

**Comment by malfet** [comment]
@garymm I've proposed linter changes to original PR and will land it instead of this one. Closing.

**Pull request closed without merging**
