### PR TITLE
[WIP] test cudnn8.7

### PR DESCRIPTION
**Pull request by ptrblck**
CC @atalman @malfet 

For: https://github.com/pytorch/builder/pull/1271

### CODE REVIEW

**Comment by ptrblck** [comment]
@atalman 

The failing tests are:

#### conda-related

* https://github.com/pytorch/pytorch/actions/runs/4009416336/jobs/6887436019
```
CondaError: Downloaded bytes did not match Content-Length
  url: https://conda.anaconda.org/nvidia/win-64/libcublas-dev-11.9.2.110-0.tar.bz2

## Package Plan ##

  target_path: C:\actions-runner\_work\pytorch\pytorch\builder\windows\conda\pkgs\libcublas-dev-11.9.2.110-0.tar.bz2
  Content-Length: 311278235
  downloaded bytes: 172816824
```
* https://github.com/pytorch/pytorch/actions/runs/4009416336/jobs/6887430866
```
CondaError: Downloaded bytes did not match Content-Length
  url: https://conda.anaconda.org/nvidia/win-64/libcufft-dev-10.7.1.112-0.tar.bz2
  target_path: C:\actions-runner\_work\pytorch\pytorch\builder\windows\conda\pkgs\libcufft-dev-10.7.1.112-0.tar.bz2
  Content-Length: 262238290
  downloaded bytes: 53258682
```
* https://github.com/pytorch/pytorch/actions/runs/4009416336/jobs/6887553592
```
CondaError: Downloaded bytes did not match Content-Length
  url: https://conda.anaconda.org/nvidia/win-64/nsight-compute-2022.4.0.15-0.tar.bz2
  target_path: C:\actions-runner\_work\pytorch\pytorch\builder\windows\conda\pkgs\nsight-compute-2022.4.0.15-0.tar.bz2
  Content-Length: 627707653
  downloaded bytes: 252242363
```

#### rocm-related
* https://github.com/pytorch/pytorch/actions/runs/4009416362/jobs/6886407020
* https://github.com/pytorch/pytorch/actions/runs/4009416362/jobs/6886405504
```
+ g++ /builder/test_example_code/simple-torch-test.cpp -I/tmp/libtorch/include -I/tmp/libtorch/include/torch/csrc/api/include -D_GLIBCXX_USE_CXX11_ABI=1 -std=gnu++14 -L/tmp/libtorch/lib -Wl,-R/tmp/libtorch/lib -Wl,--no-as-needed -ltorch -ltorch_cpu -lc10 -o simple-torch-test
/usr/bin/ld: /tmp/libtorch/lib/libamd_comgr.so: undefined reference to `del_curterm@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /tmp/libtorch/lib/libamd_comgr.so: undefined reference to `setupterm@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /tmp/libtorch/lib/libamd_comgr.so: undefined reference to `tigetnum@NCURSES6_TINFO_5.0.19991023'
/usr/bin/ld: /tmp/libtorch/lib/libamd_comgr.so: undefined reference to `set_curterm@NCURSES6_TINFO_5.0.19991023'
collect2: error: ld returned 1 exit status
```

Let me know if you see any failing issues related to the cuDNN update.

**Comment by atalman** [comment]
@ptrblck Failures above are not related to cudnn update. These looks like flaky issues. cudnn was not updated for 11.6. I think we are good to merge

**Comment by malfet** [comment]
Small suggestion (if this is a work-in-progress change, or PR needed to test builder changes): do you mind keeping it as draft (and closing if it was used to test now merged builder change)

**Comment by atalman** [comment]
@malfet, done converted to draft

**Pull request closed without merging**
