### PR TITLE
fix 'Node' object is not iterable in functorch.compile.minifier

### LINKED ISSUE #102169: `'Node' object is not iterable` in functorch.compile.minifier
### 🐛 Describe the bug

The minifier fails on
```
import torch
from functorch import make_fx
from functorch.compile import minifier

class Model(torch.nn.Module):
    def forward(self, _to_copy_1):
        cumsum = torch.ops.aten.cumsum.default(_to_copy_1, 1);  _to_copy_1 = None
        return cumsum

model = Model()
inps = (torch.ones(torch.Size([1, 12]), dtype=torch.int32), )
out = model(*inps)

fx_g = make_fx(model)(*inps)

def fails(fx_g, inps):
    return (torch.ops.aten.cumsum.default in (i.target for i in fx_g.graph.nodes))

minifier(fx_g, inps, fails)
```
with
```
...
Strategy: Remove outputs (G: 1) (3 nodes, 1 inputs)
Traceback (most recent call last):
  File "minifier_bug.py", line 19, in <module>
    minifier(fx_g, inps, fails)
  File "/scratch/torch-mlir/.venv/lib/python3.8/site-packages/torch/_functorch/fx_minifier.py", line 405, in minifier
    new_state = remove_outputs(failing_state, 1)
  File "/scratch/torch-mlir/.venv/lib/python3.8/site-packages/torch/_functorch/fx_minifier.py", line 195, in new_func
    new_state = strategy(deepcopy_fx_graph(old_state.graph), list(old_state.inps), granularity)
  File "/scratch/torch-mlir/.venv/lib/python3.8/site-packages/torch/_functorch/fx_minifier.py", line 258, in remove_outputs
    output_args = sorted(output.args[0], key=lambda x: x.idx if isinstance(x, fx.Node) else int(1e9))
TypeError: 'Node' object is not iterable
```
It seems that the args of the "output" node in the fx graph can either be a tuple or a single fx.Node.
A fix seems to be
```
diff --git a/torch/_functorch/fx_minifier.py b/torch/_functorch/fx_minifier.py
index dc5dd628cda..00e4133c84f 100644
--- a/torch/_functorch/fx_minifier.py
+++ b/torch/_functorch/fx_minifier.py
@@ -255,6 +255,9 @@ def minifier(
                 output = node
                 break
 
+        if isinstance(output.args[0], fx.Node):
+            return None
+
         output_args = sorted(output.args[0], key=lambda x: x.idx if isinstance(x, fx.Node) else int(1e9))
         if len(output_args) == 1:
             return None
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230522+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.27

Python version: 3.8.0 (default, Dec  9 2021, 17:53:27)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-4.15.0-166-generic-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  1
Core(s) per socket:  8
Socket(s):           2
NUMA node(s):        1
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               1
Model name:          AMD EPYC Processor
Stepping:            2
CPU MHz:             2994.372
BogoMIPS:            5988.74
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           64K
L2 cache:            512K
L3 cache:            8192K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl xtopology cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 virt_ssbd arat

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.1.0.dev20230522+cpu
[pip3] torchvision==0.16.0.dev20230522+cpu
[pip3] triton==2.0.0
[conda] Could not collect

cc @zou3519 @Chillee @samdow @kshitij12345 @janeyx99

### PR DESCRIPTION
**Pull request by makslevental**
Fixes #102169

cc @mgehre-amd

### CODE REVIEW

**Comment by mgehre-amd** [comment]
Ping, this fix is important for us. Can someone re-run the tests, please?

**Review by Chillee — APPROVED** [review]

**Comment by makslevental** [comment]
ping @zou3519

**Comment by kit1980** [comment]
Is this ready to be merged?

**Comment by makslevental** [comment]
> Is this ready to be merged?

approved and all tests pass (1 skip) so i think so?

**Comment by kit1980** [comment]
@makslevental FYI when a PR is approved by a project member, anyone can post a "@pytorchbot merge" comment to merge the PR.

**Comment by makslevental** [comment]
@kit1980 I believe this test is a flake. Can you please land on your side.

**Comment by Chillee** [comment]
Can anybody use pytorchbot merge -f too? haha

**Pull request closed without merging**
