### PR TITLE
[PT2E][Quantization] Refactor Quantizer and QNNPACKQuantizer

### PR DESCRIPTION
**Pull request by kimishpatel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #99106
* #99071
* #99066
* #99065
* #99064
* __->__ #99063

This diff renames quantization spec/config and operator config. It moves these
datastructures to base quantizer.
Base quantizer API now has get_supported_operators that returns list of
patterns that a quantizer quantizes.
There are two choices being debated for how to convey to user what a particular
quantizer will quantize.

1. Modules. We just convey what nn.Modules will be quantized. Of course that
does not mean that equivalent functional variants wont be quantized, however
for simplifity we just use nn.Module. If certain ops are quatnzied in fused
manner then that will considered internal details. Pros and cons of this
approach
pros:
  - Simple. Only nn Modules are listed.
  - User does not have to see fusion patterns.
Cons:
  - confusing perhaps because it is not clear if supported = nn.Conv2d also
    means that the quantizer supported functional.conv2d
  - Hiding fusion pattern means user has no say in not fusing. Meaning if
    conv2d + relu is fused and user configures to quantize only conv, quantizer
    will also quantize the following relu as if conv2d + relu are fused.

2. Patterns. Be explicit about what is supported and enumerate all possible
compbinations.
Pros:
  - it is very clear what quantizer will do. no surprises.
Cons:
  - It is not simple to parse.
  - It can be argued taht fusion is internal detail of the quantizer. So some
    quantizer implementation may chose to expose fusion patterns, while others
    may not and may not even provide any configurability.

One option is to move set_supported_operators/modules out of base quantizer and
let each quantizer define its own way of communicating what is supported. Issue
with this is that when we want to "Compose" multiple quantizers there is no way
for user to define the order of composition if user does not know what a
quantizer supports. For exampl quantizer A may quantizer conv + relu while B
only conv, but B's implementation is fast. In that case you may compose (B, A)
such B quantizes conv and A quantizes relu. Not knowning what A
and B support, makes such composition harder

Differential Revision: [D44895547](https://our.internmc.facebook.com/intern/diff/D44895547/)

**NOTE FOR REVIEWERS**: This PR has internal Meta-specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D44895547/)!

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]

**Comment by raziel** [comment]
@kimishpatel @jerryzh168 

I want to further clarify:

> fusion is internal detail of the quantizer

Indeed this is a principle behind this API design. This also means that a specific quantizer decides what, if any, is up to the user to decide whether to fuse or not.
Whereas this may seem "limiting" it's really not. You can make a specific quantizer as flexible (and messy) as you'd like to, up to a user being able and willing to implement their own.

So, the decision of whether patterns or modules or whatever should not be part of the core Quantizer interface since it's an implementation detail of perhaps some branch of the Quantizer tree --some other branch(es) may decide to use some other mechanism to express configurability, and some other branch may not allow any configurability at all!

**Comment by kimishpatel** [comment]
> So, the decision of whether patterns or modules or whatever should not be part of the core Quantizer interface

@raziel agreed. And given how messy it is getting, it feels we can just remove that from the API and just keep annotate + validate. And what level of configurability quantizer exposes is upto each quantizer.

On the flip side the sole reason to expose what modules a quantizer can quantize is this: In composable quantizer we will apply one or more quantizer (why composable quantizer? Because you may want to quantize _one_ model that can be run on two different backends). Order will matter here. For a user to figure out in which order two quantizers should be composed may require information about what each quantizer supports. Otherwise, you are flying blind.

**Comment by jerryzh168** [comment]
@raziel yeah agree, I think we should leave the choice of modules/patterns to backend developers and only have annotate/validate.

@kimishpatel I feel maybe we can just create a subclass of base quantizer (e.g. ComposableQuantizer) and have the QNNPack/ExecutorchNative quantizer to both inherit that?

**Comment by kimishpatel** [comment]
> @kimishpatel I feel maybe we can just create a subclass of base quantizer (e.g. ComposableQuantizer) and have the QNNPack/ExecutorchNative quantizer to both inherit that?

qnnpack quantizer is not a composable quantizer. Question is really about whether quantizer should tell you about its capability or not. Meaning given a model what this quantizer will quantize. With just annotate/validate you dont get that answer. This is also not unique to quantizer. Partitioner in delegate also has the same issue. And the idea of composability also applies to partitioner.

**Comment by jerryzh168** [comment]
> qnnpack quantizer is not a composable quantizer.

what does this mean?

> Question is really about whether quantizer should tell you about its capability or not.

I feel we can just create additional quantizers subclassing the base quantizer, e.g. ModuleBasedQuantizer, OperatorPatternBasedQuantizer, and each of them can provide additional things, and all quantizers inheriting ModuleBasedQuantizer can compose with each other, all quantizers inheriting OperatorPatternBasedQuantizer can compose with each other, what would be the issue with that?

**Pull request closed without merging**
