### PR TITLE
Decoder native functions join the dead code society

### PR DESCRIPTION
**Pull request by mikekgfb**
Summary: Decoder native joins the dead code society

With the recent introduction of PT2, we no longer need native decoder operators:
1 - full-function SDPA kernels can be used to implement cross-attention efficiently without the (slower) decoder MHA blob.
2 - torch.compile() generates more efficient code across many platforms from the python implementation of decoders than the decoder layer blob by tailoring code to target

Test Plan: github & sandcastle

Differential Revision: D43811808

### CODE REVIEW

**Comment by mikekgfb** [comment]
How to delete these internal functions?  They were never surfaced and would love to  remove them

**Review by ezyang — APPROVED** [review]
just need to fix the rest of the tests

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
