### PR TITLE
Remove escape_path in our build system.

### PR DESCRIPTION
**Pull request by xuhdev**
Which was added in #16412.

Also make some CUDNN_* CMake variables to be build options so as to avoid direct reading using `$ENV` from environment variables from CMake scripts.

### CODE REVIEW

**Comment by xuhdev** [comment]
@peterjc123 Did you have specific reasons to add these `escape_path`? Practically speaking, they look only effective on Windows.

**Review by peterjc123 — COMMENTED** [review]
This is to fix CMake warning when building CUDA files. 
As you can see in the log, there are many occurrences of the following type of warning.
```
CMake Warning (dev) at caffe2_detectron_ops_gpu_generated_smooth_l1_loss_op.cu.obj.Release.cmake:82 (set):
  Syntax error in cmake code at

    C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/build/modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/caffe2_detectron_ops_gpu_generated_smooth_l1_loss_op.cu.obj.Release.cmake:82

  when parsing string

    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/aten/src;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/build;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/cmake/../third_party/googletest/googlemock/include;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/cmake/../third_party/googletest/googletest/include;;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/third_party/protobuf/src;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/build/win_tmp/mkl/include;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/cmake/../third_party/benchmark/include;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/cmake/../third_party/eigen;C:/Jenkins/Miniconda3/include;C:/Jenkins/Miniconda3/lib/site-packages/numpy/core/include;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/torch/include;/opt/rocm/hip/include;/include;/include;/include;/include;/include;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/cmake/../third_party/cub;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/build/caffe2/contrib/aten;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/third_party/onnx;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/build/third_party/onnx;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/third_party/foxi;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/build/third_party/foxi;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/build/win_tmp/magma/include;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include;C:/Program Files/NVIDIA Corporation/NvToolsExt/include;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/caffe2/../torch/csrc/api;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/caffe2/../torch/csrc/api/include;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/third_party/protobuf/src;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/c10/../;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/build;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/build/win_tmp/mkl/include;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/c10/cuda/../..;C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/build;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0\include;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include

  Invalid escape sequence \i

  Policy CMP0010 is not set: Bad variable reference syntax is an error.  Run
  "cmake --help-policy CMP0010" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
I'm okay if you delete them here but you'll need to handle them in the CMake scripts, using something like`file(TO_CMAKE_PATH "${MY_DIR_VAR}" MY_DIR_VAR)`.

**Review by ezyang — CHANGES_REQUESTED** [review]
Chesterton's fence strikes again! I don't want to merge this unless we fix the underlying issue too.

**Comment by xuhdev** [comment]
Is it possible to trigger Windows CI?

**Comment by ezyang** [comment]
@xuhdev all of our Windows configs run by default. You'll probably have to inspect the logs to see if your change worked or not though

**Comment by xuhdev** [comment]
After some investigation, I don't think the issue pointed out by @peterjc123 is a generic issue, but a bug in an upstream CMake module. I've sent a relevant PR to upstream and have included it in this PR: https://gitlab.kitware.com/cmake/cmake/merge_requests/3679

**Review by ezyang — APPROVED** [review]
Nice!

**Review by peterjc123 — APPROVED** [review]

**Pull request closed without merging**
