### PR TITLE
Kineto activity fix

### PR DESCRIPTION
**Pull request by mwootton**
Continuation of https://github.com/pytorch/pytorch/pull/88207

A compile time guard was preventing ActivityType::CUDA from being available on rocm. This caused both the GPU_FALLBACK and CUDA modes to be active at the same time. So operators were being charged gpu time for the hipEventRecord ranges and the actual kernel execution times. This caused incorrect (and often negative) cuda times, in e.g. table().

Previously a cmake variable was not being propagated to a '-D', causing an issue on Windows, which uses cuda but not cupti.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Review by jeffdaily — APPROVED** [review]

**Comment by jeffdaily** [comment]
@malfet added you as reviewer since you reviewed/approved the reverted PR.  This current PR should fix the issue; CI is pending.  lintrunner errors are unrelated.

**Review by malfet — APPROVED** [review]

**Comment by mwootton** [comment]
cc @jeffdaily @sunway513 @jithunnair-amd

**Comment by jeffdaily** [comment]
Windows CI is passing now.  All CI is passing.  Will merge.

**Pull request closed without merging**
