### PR TITLE
Kill non-bool version of maskedXXX from TH and THC

### PR DESCRIPTION
**Pull request by zasdfgbnm**
dependency: https://github.com/pytorch/pytorch/pull/47951

Now we can easily view a byte tensor as a bool tensor at no cost, there is no reason to keep a separate kernel for these non-bool versions of masked operations.

My only concern:
Is it safe to assume `sizeof(bool) == 1` is always true? Or is PyTorch already assuming this? I checked with godbot on a few different compilers on a few different platforms (arm, avr, x86, powerpc64e, risc-v), seem that this assumption is safe.

### CODE REVIEW

**Comment by ngimel** [comment]
Can you insert static_assert for this? That way compilation will fail if it's not true.

**Comment by zasdfgbnm** [comment]
@ngimel Added

**Comment by zasdfgbnm** [comment]
rebased

**Comment by gchanan** [comment]
I thought it was undefined behavior / failed ASAN to read a non-0-or-1 value as a bool via a bool pointer.  I didn't check if the code does this but I don't see additional tests and that makes me nervous.

**Comment by ngimel** [comment]
uint8 masks are still supposed to have only 0 or 1 values, right? If they don't, it's a user error.

**Comment by zasdfgbnm** [comment]
I searched around C++ standard, it said very little about bitwise representation about bool. But I think PyTorch is already assuming a lot about it.

For example, if I created my own CPU ISA and my own compiler. In my platform, `bool` is implemented to have 4 bytes, with
```
true := 0xABABABAB
false := anything else
```

If I compile PyTorch on my platform and use GPU and do a `cpu_bool_tensor.to('cuda')`, PyTorch would just use `cudaMemcpy` to do the copy kernel, and I will get silent wrong result.

Similarly, if I compile PyTorch in my platform and made a cluster with some x86 machines, and uses DDP to train my model. Then PyTorch would just send the raw data through network preserving all bits, and get silent wrong results.

So I think we indeed should assume
```
false := 0x00
true := anything else
```

And adding a test for this would also be great.

**Comment by zasdfgbnm** [comment]
Test added `test_bool_bitwise_representation`

**Comment by mruberry** [comment]
New test is failing on pytorch_linux_xenial_py3_6_gcc5_4_test:

```
test_bool_bitwise_representation_cpu - TestTorchDeviceTypeCPU
test_torch.py

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 279, in instantiated_test
    result = test_fn(self, *args)
  File "test_torch.py", line 3319, in test_bool_bitwise_representation
    self.assertTrue(tv[1:].all().item())
AssertionError: False is not true
```

and the XLA build:

```
Jan 08 21:16:36 ======================================================================
Jan 08 21:16:36 ERROR [0.028s]: test_bool_bitwise_representation_xla (__main__.TestTorchDeviceTypeXLA)
Jan 08 21:16:36 ----------------------------------------------------------------------
Jan 08 21:16:36 Traceback (most recent call last):
Jan 08 21:16:36   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 284, in instantiated_test
Jan 08 21:16:36     raise rte
Jan 08 21:16:36   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 279, in instantiated_test
Jan 08 21:16:36     result = test_fn(self, *args)
Jan 08 21:16:36   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 3316, in test_bool_bitwise_representation
Jan 08 21:16:36     t = torch.arange(256, dtype=torch.uint8, device=device)
Jan 08 21:16:36 RuntimeError: value cannot be converted to type uint8_t without overflow: 256
```

and the ROCm build

```
21:42:12 ======================================================================
21:42:12 FAIL [0.001s]: test_bool_bitwise_representation_cpu (__main__.TestTorchDeviceTypeCPU)
21:42:12 ----------------------------------------------------------------------
21:42:12 Traceback (most recent call last):
21:42:12   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 279, in instantiated_test
21:42:12     result = test_fn(self, *args)
21:42:12   File "test_torch.py", line 3319, in test_bool_bitwise_representation
21:42:12     self.assertTrue(tv[1:].all().item())
21:42:12 AssertionError: False is not true
```

**Comment by mruberry** [comment]
We may want to just focus on killing these by deprecating the uint8 masking behavior.

**Comment by mruberry** [comment]
> I searched around C++ standard, it said very little about bitwise representation about bool. But I think PyTorch is already assuming a lot about it.
> 
> For example, if I created my own CPU ISA and my own compiler. In my platform, `bool` is implemented to have 4 bytes, with
> 
> ```
> true := 0xABABABAB
> false := anything else
> ```
> 
> If I compile PyTorch on my platform and use GPU and do a `cpu_bool_tensor.to('cuda')`, PyTorch would just use `cudaMemcpy` to do the copy kernel, and I will get silent wrong result.

It's frustrating that the C++ standard allows this nonsense.

> ```
> false := 0x00
> true := anything else
> ```

I don't think we can make that assumption. Check this out: https://stackoverflow.com/questions/56369080/setting-extra-bits-in-a-bool-makes-it-true-and-false-at-the-same-time.

**Comment by mruberry** [comment]
In fact, try to access the values at all in this case is probably undefined behavior? Isn't it analogous to this: https://stackoverflow.com/questions/37418412/using-reinterpret-cast-with-bool?

**Comment by zasdfgbnm** [comment]
@mruberry Thanks for these links. Now I think it's just too risky to view uint8 as bool. But are we ready to retire "uint8 as a mask"?

**Comment by mruberry** [comment]
> @mruberry Thanks for these links. Now I think it's just too risky to view uint8 as bool. But are we ready to retire "uint8 as a mask"?

That's an excellent question. I want to compile this some more data and open an issue for us to discuss it, however.

**Comment by zasdfgbnm** [comment]
Close because I don't feel safe to do so anymore.

**Pull request closed without merging**
