### PR TITLE
.github: Move squid vars to common vars

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #64436
* #64435

Moves the squid variables to our common jinja template so that when we
have to update them they're all in the same place.

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

cc @ezyang @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra

Differential Revision: [D30732776](https://our.internmc.facebook.com/intern/diff/D30732776)

### CODE REVIEW

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30732776).

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30732776).

**Review by malfet — APPROVED** [review]

**Review by zhouzhuojie — APPROVED** [review]

**Comment by zhouzhuojie** [comment]
unrelated mypy error?

**Comment by seemethere** [comment]
> unrelated mypy error?

Yup not entirely sure why Dr. CI didn't identify it correctly as broken upstream

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
