### PR TITLE
Fix XNNPACK OSS Buck build

### PR DESCRIPTION
**Pull request by kit1980**

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!  Thank you for finding a fix for this.  This has been breaking periodic for a few days

**Review by seemethere — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
You might need to land it via co-dev as it will conflict with bandaids currently applied to various internal build systems

**Comment by weiwangmeta** [comment]
cc @tiandiao123  and @digantdesai  as fyi.

**Pull request closed without merging**
