### PR TITLE
 Fix python function output wrapping

### PR DESCRIPTION
**Pull request by albanD**
If `rebase_history` is called in `set_history`, then the cdata is assumed to be filled.

### CODE REVIEW

**Comment by albanD** [comment]
Failing test are irrelevant to this PR.

**Comment by soumith** [comment]
cc: @apaszke for review

**Comment by apaszke** [comment]
Sorry can you please elaborate on what was the problem previously? I’m not sure if I understand

**Comment by albanD** [comment]
@apaszke 
Basically if you have a Function that returns 2 outputs that are views of its inputs and it modified the first one inplace, You will call `set_history` for it. For which you will call `rebase_history`. Note that with the current code, at this point, you called `add_input_metadata` on cdata only once. So `cdata->num_inputs()` is 1 at the moment (while it should be 2 as the function returns 2 outputs). During the `rebase_history` call, none of [these checks](https://github.com/pytorch/pytorch/blob/da029ca0422ca95c7489e15fdd9c1f9dc12459d5/torch/csrc/autograd/variable.cpp#L214-L218) will be triggered while the last one should be.
Indeed, if the second output is the one modified inplace, it will trigger as expected. 

If the check is not triggered, this code will crash during the backward as your Function will get a single grad_output instead of two. Giving an unexpected and unrelated error message.

**Comment by albanD** [comment]
@apaszke this now includes the checks for the case where an input can be returned only if there is a single output as discussed offline.

**Comment by ezyang** [comment]
ping @apaszke

**Comment by albanD** [comment]
@ezyang there is actually more work to be done here (and I've been too busy to do it).
In particular this enforces that Functions that return an input never return more than one output (if inplace ops are done later, we would end up with a wrong Function as one of it's output edges was removed from the graph and so the backward function would get a wrong number of grad arguments).
Unfortunately the Broadcast Function from the distributed package can sometimes return some of it's inputs and return more than one element. This should be fixed. If the first op of your DataParallel was inplace, you might get very weird errors.
Unfortunately I'm not familiar with this code and it's quite complex so I will need some time to read into it and fix it properly.
If you think this should get in fast, someone might want to step in to fix the Broadcast Function.

**Comment by albanD** [comment]
This was already fixed by the other PR on output checking for custom Functions.

**Pull request closed without merging**
