### PR TITLE
[CUDA 10] Resolve host_define.h warnings

### PR DESCRIPTION
**Pull request by syed-ahmed**
Eigen was updated with the commit needed to get rid of this warning that plagued the CI. This PR bumps third_party/eigen to that commit head.
```
warning: #warning "host_defines.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
```

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by syed-ahmed** [comment]
Looks like master is broken for `ci/circleci: caffe2_py2_ios_macos10_13_build` because of this. The bug in question is: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1668 and fixed in https://github.com/eigenteam/eigen-git-mirror/commit/d41dc4dd74acce21fb210e7625d5d135751fa9e5. I am bumping eigen again to this commit head. Please revert the current master commit and once the CI for this PR is all green, please re-land.

**Comment by soumith** [comment]
reverting

**Comment by soumith** [comment]
because of stupid bot stuff, can yo reopen a new PR for this, now that I reverted the partial PR

**Comment by syed-ahmed** [comment]
reopened here: https://github.com/pytorch/pytorch/pull/19917

**Pull request closed without merging**
