### PR TITLE
[BE]: Apply ruff rule FURB192

### PR DESCRIPTION
**Pull request by Skylion007**
Apply RUFF rule FURB192 to remove unnecessary sorts and replace them with min / max.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Very cool rule!

FYI @jansel

**Comment by Skylion007** [comment]
> Very cool rule!
> 
> FYI @jansel

Yeah, I wrote the issue to propose it, lol.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
