### PR TITLE
Add USE_SYSTEM_NVTX option

### PR DESCRIPTION
**Pull request by jeongseok-meta**
## Summary

We are currently [updating](https://github.com/conda-forge/pytorch-cpu-feedstock/pull/277) the [`conda-forge::pytorch`](https://anaconda.org/conda-forge/pytorch) package to version 2.5.0. This update includes a new dependency, the third_party/NVTX submodule. However, like other package management frameworks (e.g., apt), conda-forge prefers using system-installed packages instead of vendor-provided third-party packages.

This pull request aims to add an option, `USE_SYSTEM_NVTX`, to select whether to use the vendored nvtx or the system-installed one, with the default being the vendored one (which is the current behavior).

## Test Plan

The `USE_SYSTEM_NVTX` option is tested by building the `conda-forge::pytorch` package with the change applied as a [patch](https://github.com/conda-forge/pytorch-cpu-feedstock/blob/cd1d2464dd14e48ae4bd2214e6885e2432de483e/recipe/patches/0005-Use-system-nvtx3.patch).

### CODE REVIEW

**Comment by jeongseok-meta** [comment]
Please remove the `topic: not user facing` tag as it was accidentally added.

**Review by albanD — APPROVED** [review]
Sounds good!
Thanks for update the comment in setup.py to be accurate!

**Comment by cyyever** [comment]
USE_SYSTEM_NVTX defaults to true? It's better to use the NVTX associated with CUDA.

**Comment by albanD** [comment]
It default to the same value as "USE_SYSTEM_LIBS" (which is off by default).

**Comment by jeongseok-meta** [comment]
@cyyever It is defaulted to OFF to maintain the current behavior (and it can be overwritten by `USE_SYSTEM_LIBS` like any other `USE_SYSTEM_*` options). We could change the behavior in a follow-up PR if needed, in my opinion.

**Comment by albanD** [comment]
@pytorchbot merge -r

Not sure why this job failed...

**Pull request closed without merging**
