### PR TITLE
[TorchTidy] Adding Layout support and exposing TensorMetadata

### PR DESCRIPTION
**Pull request by Gamrix**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #81843
* #81824
* __->__ #81155

TensorMetadata will be used later to hold various metadata fields including sizes and strides.

This is basically me separating the following diff into its logical components after they all got smushed together
https://github.com/pytorch/pytorch/pull/80072

### CODE REVIEW

**Review by robieta — APPROVED** [review]
LGTM

**Comment by Gamrix** [comment]
The Torchdynamo test failure seems to be flaky and unrelated to this diff:
Example run with same issue: 
https://github.com/pytorch/pytorch/commit/c9497886fd0a38a666b63cf5e068a28233f3135a
https://pipelines.actions.githubusercontent.com/serviceHosts/7d146c05-69c3-4c20-a0e7-818111670117/_apis/pipelines/1/runs/2132305/signedlogcontent/238?urlExpires=2022-07-21T18%3A37%3A51.3174590Z&urlSigningMethod=HMACV1&urlSignature=ZkRl3AfwAoOoFphAbLyxNFq5stoJQYZzEbnNh%2B5x7dk%3D

**Pull request closed without merging**
