### PR TITLE
[FSDP][optim_state_dict] Ignore the state check on rank that does not own the corresponding parameter

### PR DESCRIPTION
**Pull request by fegin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #93318

When a rank does not own a parameter (parameter.numel() == 0), its optim state is not valid and should not be checked against the current saved one.

Differential Revision: [D42865237](https://our.internmc.facebook.com/intern/diff/D42865237/)

### CODE REVIEW

**Review by rohan-varma — COMMENTED** [review]
LGTM overall, but could we add an example unittest that would've raised an error / correctness issue that this change would fix?

**Review by rohan-varma — APPROVED** [review]
stamp to unblock but would be great if we can add the unittest or file an issue to do so.

**Comment by fegin** [comment]
> stamp to unblock but would be great if we can add the unittest or file an issue to do so.

Oh, this PR already a UT for that.

**Pull request closed without merging**
