### PR TITLE
Use TORCH_CHECK instead of AT_ASSERT in torch::cuda::gather()

### PR DESCRIPTION
**Pull request by andreaskoepf**
The error message produced by AT_ASSERT() in gather() encouraged users to file a bug report ("please report a bug to PyTorch..."). The assertion should be a regular argument check since it can be triggered by passing tensors with different dimensionality, e.g. `torch.cuda.comm.gather([torch.rand(1, device='cuda'), torch.rand(1, 1, device='cuda')])`.

See: #26400

### CODE REVIEW

**Comment by andreaskoepf** [comment]
@ezyang [contribution_guide.html](https://pytorch.org/docs/stable/community/contribution_guide.html) says " if you happen to know who the maintainer for a given subsystem affected by your patch is, feel free to include them directly on the pull request"  .. but how to do this? Under "Reviewers" in the right sidebar there is no UI shown for me.

**Comment by soumith** [comment]
@andreaskoepf you can look at the list of maintainers at https://pytorch.org/docs/stable/community/persons_of_interest.html

Does it not let you request a particular reviewer on the right top of this page?

Screen Shot 2019-10-07 at 2 01 54 AM

**Comment by andreaskoepf** [comment]
@soumith Thanks for the link to the team list! I do not see a gear wheel near reviewers, it looks like this for me:
image
Maybe best is to '@'-mention people in the description? I noticed though that other first-time contributors were able to select reviewers. Maybe for certain code-areas (depending on defined code-ownership) it automatically shows reviewers even for outside collaborators?

**Comment by ezyang** [comment]
@andreaskoepf I gave you some more permissions so you should be able to assign people now

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
