### PR TITLE
[quant][improvements] Separated implementations for quantized and non-quantized reflection_pad2d_out_template

### PR DESCRIPTION
**Pull request by dzdang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #74760

Summary: This PR is part of a series of PRs addressing #54150,
related to using dispatcher for calls to quantized backends as opposed to if/else conditionals.
This particular PR separates the quantized and non-quantized implementation for reflection_pad2d_out_template
and reflection_pad1d_out_cpu.

This PR should introduce no functional changes.

Test plan:
```
python run_test.py
```

Differential Revision: [D35148145](https://our.internmc.facebook.com/intern/diff/D35148145)

### CODE REVIEW

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35148145).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35148145).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35148145).

**Review by jerryzh168 — APPROVED** [review]

**Comment by jerryzh168** [comment]
can we add a TODO in code or open an issue to remove reflection_pad2d_quantized_cpu after structured kernel is landed

**Comment by dzdang** [comment]
> can we add a TODO in code or open an issue to remove reflection_pad2d_quantized_cpu after structured kernel is landed

@jerryzh168  I'll open an issue. I don't want to update the PR and have it go through the CI again

**Pull request closed without merging**
