### PR TITLE
Inherit all secrets to inductor workflow

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135354

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by desertfire — APPROVED** [review]
Add "ciflow/inductor" label?

**Review by atalman — APPROVED** [review]
lgtm

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
