### PR TITLE
UFMT format on test_fake_tesnor.py test_futures.py test_fx.py

### PR DESCRIPTION
**Pull request by zeshengzong**
Fixes some files in #123062

Run lintrunner on files:
test_fake_tesnor.py
test_futures.py
test_fx.py

```bash
$ lintrunner -a --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by hippocookie** [comment]
@kit1980 Hello, please help me check whether this PR is good to merge, thanks for your time 😆

**Pull request closed without merging**
