### PR TITLE
Support setUpClass & tearDownClass with instantiate_device_type_tests()

### PR DESCRIPTION
**Pull request by masnesral**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #121686

Summary: instantiate_device_type_tests() creates dynamic test case classes that derive from a "template class". By default, the test harness will call the setUpClass() and tearDownClass() methods defined by the template class (if the template class defines them). We can explicitly create these methods in the dynamic class and arrange to call those methods in both base classes. That allows us to support setUpClass & tearDownClass test classes used with instantiate_device_type_tests().

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
better if you actually use this on something, to show it actually works

**Comment by masnesral** [comment]
> better if you actually use this on something, to show it actually works

Yes, forthcoming!

**Review by eellison — APPROVED** [review]

**Pull request closed without merging**
