### PR TITLE
Turn static inline into static function

### PR DESCRIPTION
**Pull request by cyyever**
Fixes #ISSUE_NUMBER

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by malfet** [comment]
> @pytorchbot revert -c landrace -m "Sorry but this is causing tests to fail on trunk. See [GH job link](https://github.com/pytorch/pytorch/actions/runs/11729669425/job/32675829894) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/72d3f5b26d90396f7a357fa3e5d82656ca74c102)"

@ZainRizvi s390 binary builds should be forward fixable, rather than revertible at the moment (because it's not run as part of ciflow/trunk, as it's super slow one one have zero chance of getting the machine to debug what is going on)

**Pull request closed without merging**
