### PR TITLE
Adding maximize to LBFGS

### PR DESCRIPTION
**Pull request by zaxtax**
Added the maximize flag #68052 to LBFGS optimizer and updates the respective tests.

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
I'm not a specialist of LBFGS but is that one line change enough?

**Comment by zaxtax** [comment]
I'm not so sure anymore.

**Comment by zaxtax** [comment]
I'm closing this issue as flipping the sign for the gradient does not seem to yield the desired results for L-BFGS. This should be revisited after more thought is given to the problem.

**Comment by albanD** [comment]
Thanks for checking @zaxtax

**Pull request closed without merging**
