### PR TITLE
[CI] Fix CompiledDDP failure when the gradient is not contiguous

### PR DESCRIPTION
**Pull request by fegin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #138187
* __->__ #138174
* #138245

Summary:
As title

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by yf225 — APPROVED** [review]

**Review by kwen2501 — APPROVED** [review]
LGTM.

**Comment by kwen2501** [comment]
When we are more available, let’s consider extending the contiguity fix to other collectives that requires it.

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your PR, but I think it fails test_compute_comm_reordering in trunk for rocm and multigpu setup' -c nosignal

distributed/test_compute_comm_reordering.py::TestComputeCommReorderingMultiProc::test_grouped_scheduler_node [GH job link](https://github.com/pytorch/pytorch/actions/runs/11399182861/job/31719602181) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/0ecafda6024f50734118dd794ac71b86c6e6d569)

Both setups are run only periodically, so there wasn't any signal on CI

**Pull request closed without merging**
