### PR TITLE
Revert #137523: Add functionality to call dump function of NCCL profiler plugin

### PR DESCRIPTION
**Pull request by kwen2501**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #139847

Reverts PR https://github.com/pytorch/pytorch/pull/137523

Reasons for the reversion:
1. NCCL profiler plugin is meant to be opened by NCCL. And the profiler's implementation is meant to be provided by a profiler. There is no evidence that `torch.distributed` is at a better position to be either an opener or a provider. (The PR to be reverted made `torch.distributed` an opener).

2. The main purpose of the reverted PR is to dlopen a dump function, with the help of an environment variable `NCCL_PROFILER_PLUGIN_FUN` that provides the symbol name, as in code below:
https://github.com/pytorch/pytorch/blob/c19c38469030cdf399714eb2051887f4583006a8/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L415-L427
After some investigation, NCCL does not support env var `NCCL_PROFILER_PLUGIN_FUN`. And NCCL's profiler contract `nccl_profiler.h` does not have a function called "ncclProfilerPluginDump" defined. So this looks like a private add-on.

cc @H-Huang @awgu @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Comment by wconstab** [comment]
Can you provide some more documentation of what the NCCL profiler plugin is supposed to be used for?  I'm not sure if I understand your point (1), is the claim that we are accessing some non-public parts of nccl internals?  or is this supposed to be a user-supplied plugin to NCCL, but you just don't think pytorch should be involved?

**Comment by kwen2501** [comment]
> or is this supposed to be a user-supplied plugin to NCCL, but you just don't think pytorch should be involved?

That's right. `nccl_profiler.h` defines a contract between (1) NCCL and (2) a user or a profiler who implements a plugin **to be run by** NCCL. For example, `NSight` or `kineto` can provide such implementation so that they can have their own way of representing NCCL activities (just like how they would display CUDA calls / events). By no means should `torch.distributed` dlopen and run a function in the NCCL plugin.

**Comment by wconstab** [comment]
> The functions in the plugin are for internal callback of NCCL. By no means should torch.distributed dlopen and run a function from it.

Well, if we're allowed to build a profiler that takes nccl details and dumps them to a visualizer format on disk, why can't we build a profiler that stores them in memory and lets the torch flight recorder dump their state? 

> After some investigation, NCCL does not support env var NCCL_PROFILER_PLUGIN_FUN. And NCCL's profiler contract nccl_profiler.h does not have a function called "ncclProfilerPluginDump" defined. So this looks like a private add-on

the bigger issue with #137523 IMO is that it does not actually provide the complete package.  It's missing the actual profiler plugin, which means the integration code is not 'generally' useful, especially since it assumes a particular contract without defining an API.  I think it would be better if the functionality were actually usable out of the box.

**Review by fduwjj — COMMENTED** [review]
Hmm I think network AI team add this on purpose. cc: @c-p-i-o

**Comment by kwen2501** [comment]
I agree that anyone can write and build the plugin including torch. It is just that it is not for torch.distributed to dlopen and run it. Said differently, torch.distributed did not define a plugin contract for itself.

**Comment by kwen2501** [comment]
I have asked before whether Flight Recorder would be interested in accepting plugins, as in:
- FR defines a set of API signatures, like `record(string collName, int nElem, int pgId)`, `dump()`, etc, expose them via a `.h` file;
- A 3rd-party interested would provide their own implementation for the `record`, `dump` functions, build them into a say `libtorch_fr.so`;
- FR promises to dlopen `libtorch_fr.so`, use those `run`, `dump` functions to replace the in-house implementations of the same functions, and run `record(...)`, `dump()` at some point of `ProcessGroupNCCL`'s code (which FR does already);
- That would allow that 3rd-party to get trace/dump of ProcessGroupNCCL in their own format.

**Comment by c-p-i-o** [comment]
> Hmm I think network AI team add this on purpose. cc: @c-p-i-o

Yes - the network AI team added this item in anticipation of the new NCCL library being rolled out everywhere.


> > The functions in the plugin are for internal callback of NCCL. By no means should torch.distributed dlopen and run a function from it.
> 
> Well, if we're allowed to build a profiler that takes nccl details and dumps them to a visualizer format on disk, why can't we build a profiler that stores them in memory and lets the torch flight recorder dump their state?
> 
> > After some investigation, NCCL does not support env var NCCL_PROFILER_PLUGIN_FUN. And NCCL's profiler contract nccl_profiler.h does not have a function called "ncclProfilerPluginDump" defined. So this looks like a private add-on
> 
> the bigger issue with #137523 IMO is that it does not actually provide the complete package. It's missing the actual profiler plugin, which means the integration code is not 'generally' useful, especially since it assumes a particular contract without defining an API. I think it would be better if the functionality were actually usable out of the box.

Yes. Both the plugin and analysis code are meant to be open sourced. 
Let me check with them on the actual timelines.

**Comment by kwen2501** [comment]
Btw, NCCL's profiler plugin defines a finalize API:
```
  // finalize - finalize the profiler plugin
  // Input
  //  - context: opaque profiler context object
  ncclResult_t (*finalize)(void* context);
```
**NCCL will call this finalize**, and an implementation of it can trigger a dump, as demo'ed in this example:
https://github.com/NVIDIA/nccl/blob/2ea4ee94bfb04c886c79ccae60ac9961000fdee2/ext-profiler/example/plugin.c#L130-L134
I am not sure why torch needs to trigger the dump on NCCL's behalf.

**Comment by c-p-i-o** [comment]
Spoke with network.ai. Ok to revert now.
We can sync back with @zhiyongww and forge a viable path for re-enabling similar functionality in PyTorch.

**Review by c-p-i-o — APPROVED** [review]

**Pull request closed without merging**
