### PR TITLE
use reset_running_stats in swa_utils.update_bn

### PR DESCRIPTION
**Pull request by niklasnolte**
the stat reset in `swa_utils.update_bn` already exists in `NormBase.reset_running_stats`, so use that

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
thanks!

**Comment by janeyx99** [comment]
Please ping me to help with merging this in when CI is all green.

**Comment by niklasnolte** [comment]
it cancels a bunch of jobs, i assume that is okay. otherwise what else is needed for merging except green CI?

**Comment by niklasnolte** [comment]
not sure what happened there, but i don't think the failure is related to this code. @janeyx99 can we rerun a single test?

**Comment by janeyx99** [comment]
i’ve launched a rerun

**Comment by niklasnolte** [comment]
the error is a keyboardinterrupt, does that mean timeout? because it ran for ~2.5 hours. i looked at other recent PRs and the test in question passes within ~1.5 hours. I see other errors (like out of bounds), but that seems to be fine/expected, as passing versions of this test also have that (in other PRs).

Does the testing CI take current master and cherry pick these PR's commits? If not, I could rebase to see if that fixes things.

**Comment by janeyx99** [comment]
yes the keyboard interrupt could signify a timeout—we do enforce a 4h timeout.

PR CI is run on your branch without rebasing to latest master—rebasing would be a good idea.

**Comment by niklasnolte** [comment]
okay done

**Comment by niklasnolte** [comment]
looking good

**Pull request closed without merging**
