### PR TITLE
 Fix missing import and enable test for profiler on Windows

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
@peterjc123 `FileNotFoundError` also has to be caught. the windows CI is failing.

**Comment by peterjc123** [comment]
@yf225 @soumith The builtin demangler `undname.exe` should be called in VS2017 Developer Command. Would you please change the test script a little bit to append the PATH for VS executable?

**Comment by apaszke** [comment]
@peterjc123 it should still work even if it's not in the PATH

**Comment by peterjc123** [comment]
@apaszke Okay, I'll try to fix this.

**Comment by peterjc123** [comment]
@apaszke Done.

**Review by apaszke — APPROVED** [review]

**Pull request merged**
