### PR TITLE
[nnc] quantization

### PR DESCRIPTION
**Pull request by IvanKobzarev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #66326
* __->__ #66344
* #66343

Differential Revision: [D31515838](https://our.internmc.facebook.com/intern/diff/D31515838)

```
#!/bin/bash
PYTORCH_JIT_LOG_LEVEL=">>kernel:>>eval" \
PYTORCH_TENSOREXPR_DONT_USE_LLVM=1 \
USE_PYTORCH_QNNPACK=1 \
USE_QNNPACK=1 \
USE_FBGEMM=0 \
DEBUG=1 \
CXX_FLAGS="-g" \
 USE_LLVM=/home/ivankobzarev/llvm90install \
USE_XNNPACK=1 \
./scripts/build_local.sh \
  -DBUILD_BINARY=ON \
  -DCMAKE_BUILD_TYPE=Debug \
  -DBUILD_TEST=ON \
  -DUSE_LLVM=/home/ivankobzarev/llvm90install \
  && ./build/bin/test_tensorexpr --gtest_filter="Quantization.*"
```

### CODE REVIEW

**Review by ZolotukhinM — COMMENTED** [review]
Overall looks good! I think the change to `Buf` need to be done separately since it touched the core class in TE and we need to make sure we update all the places that might be affected (IR-visitor, IR-mutator, IR-printer are those that come to mind first, but there are probably more). Also, I have some other comments inline.

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31515838).

**Comment by navahgar** [comment]
Thanks for addressing my comments from https://github.com/pytorch/pytorch/pull/66325 here. I'll let @ZolotukhinM approve once his comments are addressed.

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31515838).

**Comment by IvanKobzarev** [comment]
@ZolotukhinM @navahgar 
Thanks for the review. 

I have splitted this commit, unfortunately ghstack created a new stack:

- Adding qscale,qzero to Buf in tensorexpr IR: https://github.com/pytorch/pytorch/pull/66675
- Quantization functionality in tensorexpr: https://github.com/pytorch/pytorch/pull/66676

**Pull request closed without merging**
