### PR TITLE
delete inductor config.trace.compile_profile

### PR DESCRIPTION
**Pull request by dshi7**
Fixes #ISSUE_NUMBER

https://fb.workplace.com/groups/257735836456307/posts/687858786777341/?comment_id=687861123443774&reply_comment_id=687865486776671

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by Chillee — APPROVED** [review]

**Comment by dshi7** [comment]
I don't touch `dot_graph_shape` in this PR https://fburl.com/code/ijzz7rly.  just want to resolve the issue https://fb.workplace.com/groups/257735836456307/posts/687858786777341/?comment_id=687861123443774&reply_comment_id=687867050109848 @Chillee

**Pull request closed without merging**
