### PR TITLE
Fix test_sparse_addmm_...float16 and test_sparse_matmul_...float16 test failures

### LINKED ISSUE #73145: DISABLED test_sparse_addmm_cpu_bfloat16 (__main__.TestSparseCPU)
Platforms: mac

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_sparse_addmm_cpu_bfloat16%2C%20TestSparseCPU)).

cc @nikitaved @pearu @cpuhrsch @amjames @ezyang @gchanan @zou3519

### PR DESCRIPTION
**Pull request by pearu**
Fixes #73145

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #73158
* #73157
* __->__ #73155

Differential Revision: [D34398935](https://our.internmc.facebook.com/intern/diff/D34398935)

### CODE REVIEW

**Comment by suo** [comment]
un-requesting myself as I will be out for the week

**Review by cpuhrsch — APPROVED** [review]

**Comment by cpuhrsch** [comment]
Bumping up the relative and absolute error limits is far from satisfying to resolve issues like this. Maybe we should look into seeding our tests so that we always run on the same data, or at least pick a seed at random and record it so we can create deterministically reproducible failures.

**Comment by cpuhrsch** [comment]
@cpuhrsch has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34398935).

**Comment by pearu** [comment]
> Bumping up the relative and absolute error limits is far from satisfying to resolve issues like this. Maybe we should look into seeding our tests so that we always run on the same data, or at least pick a seed at random and record it so we can create deterministically reproducible failures.

I agree these issues of flaky tests are annoying.

There is `wrapper_set_seed` function. It looks like its usage is very verbose and its need may be missed by developers. So I think it would be more reliable to reset the seed semi-automatically, say, via `dtype` check in `OpInfo.sample_inputs` method, or introduce the `manual_seed` attribute to OpInfo so that developers can specify the seed when defining OpInfo instances.

@mruberry, any advice on the method of resetting the random seed for a particular set of tests or avoiding seed-related inference between unrelated tests?

**Comment by cpuhrsch** [comment]
@pearu - Merging PRs has been a bit hellish. Could you try rebasing this stack please?

**Comment by pearu** [comment]
@cpuhrsch The problem is that the PR https://github.com/pytorch/pytorch/pull/72397 was backed out by https://github.com/pytorch/pytorch/commit/5dad19fef05519b11a1a1afc8620ecbe9d11d770

This kind of workflow where the test flakiness on the random seed pushes out reasonable PRs can be frustrating to developers.

**Comment by cpuhrsch** [comment]
@pearu - I agree. We should have infrastructure to that allows developers to opt-into seeded tests. But we have to be careful to not encourage seed hacking. You can try a thousand seeds and it'll eventually succeed.

**Comment by pearu** [comment]
> You can try a thousand seeds and it'll eventually succeed.

Yeah, the solution should reverse this situation: one can try a thousand seeds and it'll eventually fail.

**Comment by cpuhrsch** [comment]
@pearu - I was thinking we used a fixed seed as a fallback when a test fails and note down the seed and failing test to create an issue. That way we can investigate without blocking development. The fixed seed with very strict atol and rtol will still prevent gross mistakes, but we can subsequently investigate whether the flakiness is random or due to some underlying change.

**Comment by cpuhrsch** [comment]
@cpuhrsch has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34470253).

**Comment by cpuhrsch** [comment]
@cpuhrsch has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34398935).

**Comment by cpuhrsch** [comment]
@pearu - could you try rebasing this again?

**Comment by cpuhrsch** [comment]
@cpuhrsch has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34398935).

**Pull request closed without merging**
