### PR TITLE
[DCP] Adds utility for converting dcp to torch save format

### PR DESCRIPTION
**Pull request by LucasLLC**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #120128
* #120127
* #119816
* #119815
* __->__ #119814
* #119813

as title

Differential Revision: [D53718042](https://our.internmc.facebook.com/intern/diff/D53718042/)

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Review by fegin — COMMENTED** [review]
Can we add a `__main__` so that users can directly use the tool without coding? We can do this in another PR.

**Comment by LucasLLC** [comment]
> Can we add a `__main__` so that users can directly use the tool without coding? We can do this in another PR.

Coming in a futre PR

**Review by fegin — APPROVED** [review]
LGTM, please fix the linter before landing.

**Pull request closed without merging**
