### PR TITLE
[LTC] Upstream some utilities

### PR DESCRIPTION
**Pull request by alanwaketan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #69046

Summary:
This commit upstreams utilities including ExceptionCleanup, MaybeRef,
Iota, ToVector, ToOptionalVector and GetEnumValue.

Test Plan:
./build/bin/test_lazy --gtest_filter=UtilTest.*

Differential Revision: [D32709090](https://our.internmc.facebook.com/intern/diff/D32709090)

### CODE REVIEW

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32709090).

**Review by JackCaoG — APPROVED** [review]

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32709090).

**Comment by alanwaketan** [comment]
Thanks Jack for approving this PR.

**Comment by wconstab** [comment]
LGTM, i was actually thinking we probably don't need Iota or ToVector, but, I am not gonna block this

**Review by wconstab — APPROVED** [review]

**Comment by alanwaketan** [comment]
> LGTM, i was actually thinking we probably don't need Iota or ToVector, but, I am not gonna block this

If you are aware of any c10 Iota, I can do a follow up. For ToVector, it's useful to convert things like std::array<bool,3> in LazyNativeFunctions.cpp. Thanks for approving!

**Pull request closed without merging**
