### PR TITLE
Update torchvision version to current latest master

### PR DESCRIPTION
**Pull request by izdeby**
Updating torchvision version to the current latest master.

### CODE REVIEW

**Review by seemethere — APPROVED** [review]
LGTM on green

**Comment by seemethere** [comment]
cc @fmassa

**Review by ailzhang — APPROVED** [review]
LGTM, although it's nicer to update onnx script reuse `TORCHVISION_COMMIT` ;)

**Review by fmassa — APPROVED** [review]
LGTM

**Comment by fmassa** [comment]
@andfoy test failures seem to be related to PNG / JPEG dependencies on torchvision. Could you have a look?

**Comment by andfoy** [comment]
https://github.com/pytorch/vision/pull/2735 does fix the torchvision error indeed

**Comment by fmassa** [comment]
@izdeby I've just merged @andfoy PR, could you try updating the version hash in this PR?

**Pull request closed without merging**
