### PR TITLE
Reuse run_torch_xla_tests from pytorch/xla

### PR DESCRIPTION
**Pull request by ailzhang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #59989 Reuse build_torch_xla from pytorch/xla repo.
* **#59888 Reuse run_torch_xla_tests from pytorch/xla**

Differential Revision: [D29114274](https://our.internmc.facebook.com/intern/diff/D29114274)

### CODE REVIEW

**Comment by ailzhang** [comment]
@ailzhang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29114274).

**Review by samestep — COMMENTED** [review]
question: instead of deleting the `test_xla` function entirely and inlining its new behavior, would it work to just replace the implementation of `test_xla` and leave what was line 448 as-is?
```sh
test_xla() {
  # shellcheck disable=SC1091
  source "./xla/.circleci/common.sh"
  run_torch_xla_tests "$(pwd)" "$(pwd)/xla"
  assert_git_not_dirty
}
```

**Comment by ailzhang** [comment]
@samestep sounds good! Updated :D

**Review by samestep — APPROVED** [review]
looks great, thanks!

**Comment by ailzhang** [comment]
@ailzhang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29114274).

**Pull request closed without merging**
