### PR TITLE
Make c10::ThreadPool::available_ atomic.

### PR DESCRIPTION
**Pull request by pritamdamania87**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#58457 Make c10::ThreadPool::available_ atomic.**
* #58449 Make GraphTask::owner_ atomic to avoid data races.

This variable had concurrent read/write access without any
synchronization. The issue was caught and reported by TSAN.

Differential Revision: [D28498116](https://our.internmc.facebook.com/intern/diff/D28498116/)

### CODE REVIEW

**Comment by ezyang** [comment]
Can you please post the TSAN report? I don't like blindly slapping atomics on things without understanding in more detail where the race is coming from. Is `available_` supposed to be protected by a lock?

**Comment by ezyang** [comment]
`available_` is lock guarded, except for `numAvailable` which is ostensibly a diagnostic and data race doesn't matter.  So what you should actually do is modify all the accesses to be `std::memory_order_relaxed` per section 2.6.2 in http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2055r0.pdf

**Review by ezyang — CHANGES_REQUESTED** [review]
not enough

**Comment by pritamdamania87** [comment]
> <div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0MzI0NzA0MA==" style="box-sizing: border-box; color: rgb(201, 209, 217); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0MzI0NzA0MA==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0MzI0NzA0MA==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-843247040" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists" data-body-version="c8c5073c653a4266652adb488483c87e46282f59512d9e214bcde091c3f2f54a" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border: 1px solid var(--color-border-primary); border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">Can you please post the TSAN report? I don't like blindly slapping atomics on things without understanding in more detail where the race is coming from. Is&nbsp;available_&nbsp;supposed to be protected by a lock?</task-lists></div><form class="js-comment-update" id="issuecomment-843247040-edit-form" action="https://github.com/pytorch/pytorch/issue_comments/843247040" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0MzI3OTEwMQ==" style="box-sizing: border-box; color: rgb(201, 209, 217); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0MzI3OTEwMQ==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0MzI3OTEwMQ==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><br class="Apple-interchange-newline"></div></div>

I was debugging a ton of TSAN failures and missed recording the TSAN trace for this. Although the problem was coming from the fact that `numAvailable` didn't have any locks. 

I didn't realize other accesses were protected by a mutex_, instead of making this atomic I added a lock for `numAvailable` as well.

**Review by ezyang — APPROVED** [review]
I accept that this PR is correct.

However, this is worse than what I suggested. In this PR you have to take out a lock to access `numAvailable`. But if it's used in a purely diagnostic fashion, no lock is necessary on x86, the read can be a normal mov without forcing a hard synchronization. And if accurate availability is necessary, chances are the caller already has the lock (in which case there is now a deadlock risk because it is not safe to call `numAvailable` from contexts where the lock is allowed).

**Comment by pritamdamania87** [comment]
I agree there is an extra overhead of the lock here, but I believe we should strive for correctness over performance. It is fragile to rely on users holding a lock while calling `numAvailable`. As evident by TSAN failures, this is already broken in the codebase where proper synchronizations are not done before calling `numAvailable`.

**Comment by ezyang** [comment]
That is not what I am suggesting.

```
std::atomic<int> available_;

// locked code
void lockedCode() {
  std::unique_lock<std::mutex> lock(mutex_);
  ... available_.load(std::memory_order_relaxed) ...
}

// unlocked code
size_t ThreadPool::numAvailable() const {
  return available_.load(std::memory_order_relaxed);
}
```

This will be TSAN safe and will give you a mov in numAvailable as well.

Read http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2055r0.pdf for more reasoning why this is OK

**Comment by pritamdamania87** [comment]
Doesn't this still add an overhead to the `lockedCode` with an atomic instruction? Not sure which approach would add more overhead without benchmarking it, but I just added a mutex to numAvailable to avoid another atomic instruction in locked code.

**Comment by ezyang** [comment]
> Doesn't this still add an overhead to the lockedCode with an atomic instruction? 

No it doesn't. On x86, a relaxed store on an atomic is equivalent to a store on a non-atomic, because (non-locked) store in x86 are already atomic.  You can also see this on godbolt: https://godbolt.org/z/caM5zY3YP

**Comment by pritamdamania87** [comment]
> No it doesn't. On x86, a relaxed store on an atomic is equivalent to a store on a non-atomic, because (non-locked) store in x86 are already atomic. You can also see this on godbolt: https://godbolt.org/z/caM5zY3YP

The locked code does increments(available_++), decrements(available_--) and loads (available_ == total). I might be missing something, but if I have an atomic increment and load, it does have extra overhead as you can see here: https://godbolt.org/z/b8r4j8W6K.

**Comment by ezyang** [comment]
Yes, so you would need to adjust the `++` to do a separate relaxed load and store. You don't need the increment itself to be atomic because, as you've pointed above, you already have it protected under a mutex.

**Pull request closed without merging**
