### PR TITLE
Update Dockerfile with bumped versions

### PR DESCRIPTION
**Pull request by jamestwebber**
In the process of trying to build this Dockerfile I edited it slightly, thought I should make a PR (unless there is some reason to keep the old versions). Changes are:

- Bumped base image to ubuntu18.04
- bumped version to `magma-cuda101` because it's available and the base image is cuda 10.1.
- removed `typing` as it only applies to python <3.5 and you are dropping support for 2.7.

### CODE REVIEW

**Comment by jamestwebber** [comment]
But I probably should not have made this PR because, for the life of me, I cannot actually get the thing to build.

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit 85020a4:
* **1/1** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=85020a45c7c7b7c5a866638c1072d53c898f53e1).

### 1 failure *not* recognized by patterns:
| Job | Step | Status |
| --- | --- | --- |
| CircleCI <sup>pytorch-linux-xenial-py3-clang5-android-ndk-r19c-gradle-build-x86_32</sup> | <sup>pytorch android gradle build only x86_32 (for PR)</sup> | New in PR |


---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Review by seemethere — APPROVED** [review]

**Review by seemethere — CHANGES_REQUESTED** [review]
Oh wait, I failed to notice that this is the wrong file to update, the actual file to update should just be the base `Dockerfile`

**Comment by jamestwebber** [comment]
Not sure why I just got a CLA message today when I've had PRs merged in the past.

In any case this PR is totally out of date and I'm going to close it.

**Pull request closed without merging**
