### PR TITLE
[Caffe2] Refactoring MIOpen activation ops

### PR DESCRIPTION
**Pull request by ashishfarmer**
This pull request contains changes for:
1. Adding a generalized MIOpen activation class to be used by activation operators
2. Refactoring MIOpen ReLU op to use the new class
3. Adding ELU, Tanh and Sigmoid MIOpen ops

cc: @bddppq

### CODE REVIEW

**Comment by ashishfarmer** [comment]
Triggered tests: https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger-test/3668/

**Review by bddppq — COMMENTED** [review]
Nice work. Could you add some tests in caffe2/python/operator_tests?

**Comment by ashishfarmer** [comment]
The activation_ops_test.py and hyperbolic_ops_test.py already has tests for the changes in this PR. Because of the cudnn aliasing, we did not need to update anything in the python tests

**Comment by bddppq** [comment]
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger-test/3677/

**Review by bddppq — APPROVED** [review]

**Comment by bddppq** [comment]
Landed

**Pull request closed without merging**
