### PR TITLE
[v1.4.0 cherrypick] ONNX Interpolate Add Scales Params

### PR DESCRIPTION
**Pull request by houseroad**
The original PR is https://github.com/pytorch/pytorch/pull/28324

We hope we can cover torchvision models in PyTorch ONNX exporter with release 1.4. This PR is part of it.

cc: @spandantiwari @lara-hdr

### CODE REVIEW

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit e4cec27:
* **2/2** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=e4cec279c6e03858ee12c8c0b73a8c6b804ce1aa).

### 2 new failures recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/3920088) pytorch_linux_xenial_py3_6_gcc5_4_build (1/2)
**Step:** "Build" ([details](https://dr.pytorch.org/build-details.html?build_id=72969503))
```
CONFLICT (add/add): Merge conflict in .circleci/docker/common/install_cache.sh
Auto-merging .circleci/docker/common/install_cache.sh
CONFLICT (add/add): Merge conflict in .circleci/docker/common/install_android.sh
Auto-merging .circleci/docker/common/install_android.sh
CONFLICT (add/add): Merge conflict in .circleci/docker/build.sh
Auto-merging .circleci/docker/build.sh
CONFLICT (add/add): Merge conflict in .circleci/config.yml
Auto-merging .circleci/config.yml
CONFLICT (add/add): Merge conflict in .circleci/cimodel/data/binary_build_definitions.py
Auto-merging .circleci/cimodel/data/binary_build_definitions.py
Automatic merge failed; fix conflicts and then commit the result.
```
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/3920093) pytorch_xla_linux_xenial_py3_6_clang7_build (2/2)
**Step:** "Build" ([details](https://dr.pytorch.org/build-details.html?build_id=73001867))
```
Dec 12 07:18:09 AtenXlaType function missed override: Tensor upsample_bilinear2d_backward(const Tensor& grad_output, IntArrayRef output_size, IntArrayRef input_size, bool align_corners); // upsample_bilinear2d_backward(Tensor,IntArrayRef,IntArrayRef,bool)->Tensor
Dec 12 07:18:09 AtenXlaType function missed override: Tensor upsample_nearest2d(const Tensor& self, IntArrayRef output_size); // upsample_nearest2d(Tensor,IntArrayRef)->Tensor
Dec 12 07:18:09 AtenXlaType function missed override: Tensor upsample_nearest2d_backward(const Tensor& grad_output, IntArrayRef output_size, IntArrayRef input_size); // upsample_nearest2d_backward(Tensor,IntArrayRef,IntArrayRef)->Tensor
Dec 12 07:18:09 Traceback (most recent call last):
Dec 12 07:18:09   File "/var/lib/jenkins/workspace/xla/scripts/gen.py", line 1052, in <module>
Dec 12 07:18:09     generate(args)
Dec 12 07:18:09   File "/var/lib/jenkins/workspace/xla/scripts/gen.py", line 1022, in generate
Dec 12 07:18:09     assert check_overrides(overrides, overridden)
Dec 12 07:18:09 AssertionError
Dec 12 07:18:09 Building torch_xla version: 0.8
Dec 12 07:18:09 Failed to run '['/var/lib/jenkins/workspace/xla/scripts/generate_code.sh']'
Dec 12 07:18:09 + cleanup
Dec 12 07:18:09 + retcode=1
Dec 12 07:18:09 + set +x
Dec 12 07:18:09 =================== sccache compilation log ===================
Dec 12 07:18:09 =========== If your build fails, please take a look at the log above for possible reasons ===========
Dec 12 07:18:09 Compile requests               2493
Dec 12 07:18:09 Compile requests executed      2238
Dec 12 07:18:09 Cache hits                     1595
Dec 12 07:18:09 Cache misses                    630
Dec 12 07:18:09 Cache timeouts                    0
```


---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Review by lara-hdr — APPROVED** [review]

**Comment by houseroad** [comment]
XLA build suppose not working

**Comment by gchanan** [comment]
I don't think this should get into 1.4.0 -- there are way too many changes to feel comfortable with this late after the branch cut.

**Comment by lara-hdr** [comment]
@gchanan, these changes have been thoroughly reviewed by multiple reviewers.
Also, the default behavior is unchanged for this release and will remain until 1.5, so we are not introducing changes from the users' perspective.
cc: @houseroad

**Comment by spandantiwari** [comment]
Hi @gchanan - I agree that this change was reviewed well. But I also want to mention another point of consideration. This change is starting the deprecation process for an argument in the API. The plan was to put it in a warning state in this release, and will be deprecate it in 1.5. If this change is not part of 1.4 then the deprecation will have to be delayed till 1.6. Hence the request to try to make this in 1.4.

**Comment by spandantiwari** [comment]
> Hi @gchanan - I agree that this change was reviewed well. But I also want to mention another point to consider. This change is starting the deprecation process for an argument in the API. The plan was to put it in a warning state in this release, and will be deprecate it in 1.5. If this change is not part of 1.4 then the deprecation will have to be delayed till 1.6. Hence the request to try to make this in 1.4.

**Comment by houseroad** [comment]
Sorry, I didn't notice @gchanan 's commet, so I reverted the PR.

**Comment by spandantiwari** [comment]
So is this not being merged n 1.4?

**Comment by houseroad** [comment]
I feel bad to merge it directly without agreement from @gchanan. So let's follow up with him.

**Comment by spandantiwari** [comment]
Sure, that makes sense. Let's follow-up.

**Comment by gchanan** [comment]
@lara-hdr and @spandantiwari:
Right, my objection wasn't to the patch itself, which looks good.  It's for the issue of cherry-picking to the release branch, which we typically reserve for major breakages, trivial fixes, documentation updates, etc.  As another example, I think https://github.com/pytorch/pytorch/issues/30331, which has a similar rationale as this patch (starting the deprecation cycle) also doesn't fit that criteria and if we were being strict, shouldn't have gone in.

Now, we definitely haven't communicated the branching criteria well (e.g. https://github.com/pytorch/pytorch/issues/30331 makes no mention of it), so that's something we should fix for future releases.

I believe @houseroad is still planning to shepherd this patch into 1.4.

**Pull request merged**
