### PR TITLE
Re-enable more Windows tests

### PR DESCRIPTION
**Pull request by cyyever**
Follows the work of #108930.

The commented test_custom_classes.py was removed since the file doesn't exist.

### CODE REVIEW

**Comment by kit1980** [comment]
I don't think this fixes https://github.com/pytorch/pytorch/issues/35651 and https://github.com/pytorch/pytorch/issues/35636 ?
I think we just stopped running caffe2 tests in the GitHub CI at some point.

**Review by kit1980 — APPROVED** [review]

**Comment by cyyever** [comment]
@kit1980 The "fixes" comments were removed for further confirming.

**Pull request closed without merging**
