### PR TITLE
[XPU][Profiler] Add API support for XPU profiler to Kineto path

### PR DESCRIPTION
**Pull request by xunsongh**
This patch is aimed to add support to XPU profiler which will co-work with Kineto. After this PR, kineto will follow these API to fit itself. Also, the development of interface in python is near done.

Signed-off-by: Huang, Xunsong <xunsong.huang@intel.com>

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
okey dokey

**Comment by xunsongh** [comment]
Update：added necessary XPU hook to check whether has XPU or not.

**Comment by gujinghui** [comment]
@ezyang Thanks for quick reply.
To support XPU kineto profiler in PyTorch, we have to add XPU in kineto first.
Our PR for XPU kineto is still under review at same time.
As long as done, we will update this PR to update kineto, and @ you.

Thanks a lot.

**Comment by xunsongh** [comment]
@ezyang Hi, I find that the preCI has passed without failures. May you check and try a merge then? If there still have any issues or questions about this PR, raise them with me and I will help change the code so it can be approved.

**Comment by xunsongh** [comment]
@ezyang I have fixed those issues what Lint complained and the CI also hase passed. I'm sorry for the convenience and please try to merge again. Thank you.

**Pull request closed without merging**
