### PR TITLE
Allow onnx export for maxpool with dilations

### PR DESCRIPTION
**Pull request by karljang**
Now, MaxPool operator supports the 'dilations' attribute with this commit:
https://github.com/onnx/onnx/commit/b22041c3f16cf8bcca9ed93982d6ffdf6ebf3746

### CODE REVIEW

**Comment by spandantiwari** [comment]
@karljang - Could you add a test for this as well.

**Review by houseroad — COMMENTED** [review]
Tests could be added here: https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_caffe2.py#L714

**Comment by karljang** [comment]
@houseroad 
Thank you for the link to the test script file~.

I've added dilation test cases to the file, but they are failing because the ONNX export is using the 'opset' version 9, in which the dilation attribute is not supported.

I don't know how to solve it.
Can I choose 'opset' version while the tests are running?
Or, should I mark these tests to be skipped until ONNX opset 10 is available?
Please give me your opinion~.

Thank you,

**Comment by houseroad** [comment]
Yes, you can specify the opset version when you export model from pytorch, here is an example: https://github.com/pytorch/pytorch/blob/master/test/onnx/test_operators.py#L552

**Comment by karljang** [comment]
Thank you~, I'll take a look this week.
Actually, the link you shared was helpful to my work today~!

**Comment by karljang** [comment]
The failed test is due to a long line in a recent commit in test/test_jit.py, not mine :)
https://github.com/pytorch/pytorch/blob/master/test/test_jit.py#L11267

@houseroad 
I've added a test case to test_operators.py, instead of test_pytorch_onnx_caffe2.py.
Does it make sense?

Actually, the Caffe2 seems not supporting the dilated pooling operations.
> RuntimeError: [enforce fail at pool_op.h:25] dilation_[i] == 1. 2 vs 1. Pooling op does not support dilation right now.
But, still, I believe it makes sense to enable this feature because PyTorch supports it and dilated pooling has some application, just like the dilated convolutions.

**Comment by karljang** [comment]
@houseroad @spandantiwari 
Finally, all checks have passed~
Can I get this reviewed again~?

**Pull request closed without merging**
