### PR TITLE
[FSDP] ufmt /fsdp

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #87837 [FSDP] Fix wrapped module changing after ctor
* #87812 [FSDP] ufmt FSDP test
* **#87811 [FSDP] ufmt /fsdp**

This applies `ufmt` to all of the FSDP files in the `torch/distributed/fsdp/` directory.

**Test Plan**
CI

**Notes**
For VSCode users,
- Install `ufmt`: https://pypi.org/project/ufmt/
- Install VSCode `ufmt` extension: https://marketplace.visualstudio.com/items?itemName=omnilib.ufmt
- Include in `settings.json`:
```
{
    "[python]": {
        "editor.defaultFormatter": "omnilib.ufmt",
        "editor.formatOnSave": true,
    },
}
```

Differential Revision: [D40799960](https://our.internmc.facebook.com/intern/diff/D40799960)

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Stamp as this is just a formatting change.

**Review by fegin — APPROVED** [review]

**Comment by fegin** [comment]
Can you write down the exact command you use in the summary for the future reference or is it just `ufmt fsdp`?

**Comment by awgu** [comment]
> Can you write down the exact command you use in the summary for the future reference or is it just `ufmt fsdp`?

```
ufmt format torch/distributed/fsdp
```
works to format all files in that directory. However, there is still the issue of remembering to do this before every commit.

I was not able to get the pre-commit hook to work on my first attempt. Since I use VSCode, I am trying out the setting to automatically format with `ufmt` upon save. I put the rough instructions for how I set that up in the PR description. However, not everyone will use VSCode, so we cannot enforce that. Pre-commit hook may be a good second defense.

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40799960).

**Pull request closed without merging**
