### PR TITLE
[profiler] add option for kineto synchronization events in the trace

### PR DESCRIPTION
**Pull request by briancoutinho**
Summary:
## About Sync Events
For CUDA profiling mode, we can enable tracing CUDA synchronization events.
* This feature captures synchronization events in CUDA including 1) context/device sync, 2) stream sync, 3) CUDA event sync, 4) CUDA stream wait event (inter stream synchronization). Read more
* We add this flag using the profiler's experimental config option.
* This PR relies on https://github.com/pytorch/kineto/commit/7b003638c6d65537ac9678c101f6e9adf013b157 change in pytorch/kineto

## Usage
Just set the `enable_cuda_sync_events` option in `_ExperimentalConfig`
```
from torch.autograd.profiler import profile, _ExperimentalConfig
with profile(use_kineto=True, use_cuda=True,
   experimental_config=_ExperimentalConfig(enable_cuda_sync_events=True),
) as prof:
   workload()
```

**Please wait for PyTorch github repo to point to https://github.com/pytorch/kineto/commit/7b003638c6d65537ac9678c101f6e9adf013b157 or later commit in Kineto**

Test Plan:
## Unit Test
Added a unit test

  buck2 test mode/dev-nosan caffe2/test:profiler --local-only -- test_profiler_cuda_sync_events
  Tests finished: Pass 1. Fail 0. Fatal 0. Skip 0. Build failure 0
ttps://www.internalfb.com/intern/testinfra/testrun/281475298097379

Reviewed By: davidberard98

Differential Revision: D46244591

### CODE REVIEW

**Review by aaronenyeshi — APPROVED** [review]
reviewed internally!

**Comment by huydhn** [comment]
@briancoutinho I think this change is failing on Windows CUDA https://hud.pytorch.org/pytorch/pytorch/commit/716f37cef8841b4f3177350d9abc8037a9961fba

```
2023-07-26T19:36:25.5167720Z ================================== FAILURES ===================================
2023-07-26T19:36:25.5167998Z _________________ TestProfiler.test_profiler_cuda_sync_events _________________
2023-07-26T19:36:25.5168257Z Traceback (most recent call last):
2023-07-26T19:36:25.5168628Z   File "C:\actions-runner\_work\pytorch\pytorch\test\profiler\test_profiler.py", line 1518, in test_profiler_cuda_sync_events
2023-07-26T19:36:25.5169055Z     trace_and_check(exp_config=_ExperimentalConfig(enable_cuda_sync_events=True))
2023-07-26T19:36:25.5169465Z   File "C:\actions-runner\_work\pytorch\pytorch\test\profiler\test_profiler.py", line 1514, in trace_and_check
2023-07-26T19:36:25.5169917Z     self.assertTrue("cuda_sync" in cats, "Expected to find cuda_sync event"
2023-07-26T19:36:25.5170302Z   File "C:\Jenkins\Miniconda3\lib\unittest\case.py", line 688, in assertTrue
2023-07-26T19:36:25.5170596Z     raise self.failureException(msg)
2023-07-26T19:36:25.5170921Z AssertionError: False is not true : Expected to find cuda_sync event found = {'Trace', None, 'cpu_op'}
```

Could you help take a look?  You could add `ciflow/periodic` to trigger Windows CUDA job to debug the issue if need.

**Comment by briancoutinho** [comment]
@huydhn I am adding a fix here [D47841663](https://www.internalfb.com/diff/D47841663), wondering why this was not run on my original PR , maybe it was disabled then

**Comment by huydhn** [comment]
> @huydhn I am adding a fix here [D47841663](https://www.internalfb.com/diff/D47841663), wondering why this was not run on my original PR , maybe it was disabled then

Thank you for the fix!  Windows CUDA test is kind of expensive, so we decide to run them only periodically, not on every PR.  So it's understandable that the test wasn't run on your PR.  Having a forward fix is exactly the way to handle this case.

**Pull request closed without merging**
