### PR TITLE
.github: Add action workflow to update S3 HTMLS

### PR DESCRIPTION
**Pull request by seemethere**
Successful run: https://github.com/pytorch/pytorch/runs/1572315901

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

### CODE REVIEW

**Review by walterddr — APPROVED** [review]
gogogo

**Comment by samestep** [comment]
What does this do exactly?

**Comment by seemethere** [comment]
It automates the updating of html indices through a docker image that was created as part of https://github.com/pytorch/builder/pull/607

**Comment by samestep** [comment]
> It automates the updating of html indices through a docker image that was created as part of [pytorch/builder#607](https://github.com/pytorch/builder/pull/607)

Ah ok; where are these HTML indices? (are they available on the web?)

**Comment by seemethere** [comment]
> > It automates the updating of html indices through a docker image that was created as part of [pytorch/builder#607](https://github.com/pytorch/builder/pull/607)
> 
> Ah ok; where are these HTML indices? (are they available on the web?)

Yes these are the current html indices that are used for installing pytorch from download.pytorch.org

See https://pytorch.org/get-started

**Pull request closed without merging**
