### PR TITLE
[CI] Fix rowwise scaling tests on h100

### PR DESCRIPTION
**Pull request by drisspg**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #133384

cc @ptrblck @msaroufim

### CODE REVIEW

**Comment by drisspg** [comment]
@nWEIdia You were right about that one PR, fixed here

**Review by malfet — APPROVED** [review]
Sure, though do you mind adding `[CI]` bit in front of the PR, as it does not really fix anything, just changes error message a bit

**Comment by nWEIdia** [comment]
> @nWEIdia You were right about that one PR, fixed here

Thanks @drisspg for the prompt fix!

**Comment by nWEIdia** [comment]
And thanks for fixing the python test/test_matmul_cuda.py -k TestFP8MatmulCudaCUDA.test_float8_error_messages_cuda as well!

**Review by nWEIdia — APPROVED** [review]
Looks great!

**Pull request closed without merging**
