### PR TITLE
[profiler] provide torch.profiler._utils._init_for_cuda_graphs() as a workaround

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #100441

There are known issues with profiling cuda graphs - particularly, if you create a cuda graph before the first use of the profiler, and then run that cuda graph during profiling.

One workaround is to add `with profile(): pass` before creating the cuda graph that you want to profile later.

For convenience, we provide this function to use the workaround. This also adads a test for this workaround, to ensure that it continues working.

### CODE REVIEW

**Comment by Chillee** [comment]
Is it also possible to disable the additional logging for this fake profiler construction?

**Review by Chillee — APPROVED** [review]

**Review by aaronenyeshi — APPROVED** [review]
LGTM! Also, thanks for the test case.

**Comment by davidberard98** [comment]
@Chillee I can add error suppression in a later PR - it will require exposing the kineto logging APIs and then updating the kineto pin

**Pull request closed without merging**
