### PR TITLE
Link to instructions on submitting an RFC

### PR DESCRIPTION
**Pull request by ZainRizvi**
Point people to instructions on how to create an RFC

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]

**Comment by janeyx99** [comment]
Which link/page do I go to in order to preview this change?

**Comment by ZainRizvi** [comment]
> Which link/page do I go to in order to preview this change?

Unfortunately I don't believe there is one :(

The changes get built and deployed when a new pytorch release happens.

**Pull request closed without merging**
