### PR TITLE
how to use the `ccache` package on Ubuntu

### PR DESCRIPTION
**Pull request by stas00**
Added full instructions for how to use the `ccache` package. Thanks.

### CODE REVIEW

**Review by soumith — CHANGES_REQUESTED** [review]
hey, we give instructions for ccache from source precisely because the packaged ccache in 14.04 and 16.04 does not have the patch to make NVCC work

**Comment by stas00** [comment]
And then right after the source instructions it says:

> Alternatively, ccache provided by newer Linux distributions (e.g. Debian/sid) also works, but the nvcc symlink to ccache as described above is still required.

but it doesn't say how to do that - the dirs are completely different. It took me some googling to sort it out, hence the PR.

I used `ccache-3.6` deb package and it worked.

**Review by ezyang — APPROVED** [review]
Sure

**Comment by f0k** [comment]
@stas00: :+1: for adding explicit instructions, it also took me some extra time to get from
> Alternatively, `ccache` provided by newer Linux distributions (e.g. Debian/sid) also works

to a working ccache (but then I was amazed how well it works). But I found that the `CUDA_NVCC_EXECUTABLE` is not needed, since the ccache symlink is the first one on the `PATH` anyway. The "install ccache from source" instructions only have this because they put the `nvcc` symlink into a different directory for whatever reason. Can you confirm this?

**Comment by stas00** [comment]
> @stas00: +1 for adding explicit instructions, it also took me some extra time to get from
> 
> > Alternatively, `ccache` provided by newer Linux distributions (e.g. Debian/sid) also works
> 
> to a working ccache (but then I was amazed how well it works). But I found that the `CUDA_NVCC_EXECUTABLE` is not needed, since the ccache symlink is the first one on the `PATH` anyway. The "install ccache from source" instructions only have this because they put the `nvcc` symlink into a different directory for whatever reason. Can you confirm this?

You're correct, @f0k : fix: https://github.com/pytorch/pytorch/pull/18958 - Thank you!

They needed to put it into another dir most likely since `update-ccache-symlinks` resets the directory and the link to nvcc gets removed.

**Pull request closed without merging**
