### PR TITLE
Added CUDA support for complex input for QR decomposition

### PR DESCRIPTION
**Pull request by IvanYashchuk**
QR decomposition now works for complex inputs on GPU.

Ref. #33152

### CODE REVIEW

**Review by vishwakftw — APPROVED** [review]
Looks good to me, thanks!

**Comment by IvanYashchuk** [comment]
@anjali411 can we merge this?

**Review by anjali411 — APPROVED** [review]
sorry for the late response, I was running behind on the reviews. LGTM. my only comment would be that we should enable autograd for qr in an follow up PR

**Comment by rlucas7** [comment]
> sorry for the late response, I was running behind on the reviews. LGTM. my only comment would be that we should enable autograd for qr in an follow up PR

AFAICS the existing autograd for QR won't work for complex, it's missing a phase part on `R` matrix diagonals

**Comment by IvanYashchuk** [comment]
The derivative rule for QR was updated with https://github.com/pytorch/pytorch/pull/48489.

**Pull request closed without merging**
