### PR TITLE
[ROCm] re-enable test_Conv2d_groups_nobias tests

### PR DESCRIPTION
**Pull request by KyleCZH**
fixes:
https://github.com/pytorch/pytorch/pull/59158
https://github.com/pytorch/pytorch/pull/58701

### CODE REVIEW

**Comment by KyleCZH** [comment]
CI builds are passing after tests are enabled. @jithunnair-amd @jeffdaily

**Comment by KyleCZH** [comment]
following report logs are generated using the scripts in this link:
https://confluence.amd.com/display/MLSE/PyTorch+Unit+Test+Audit+Automation

March 30 comparison:
test1+test2
[diff_test1_test2_03302022.txt](https://github.com/pytorch/pytorch/files/8399412/diff_test1_test2_03302022.txt)
distributed
[diff_distributed_03302022.txt](https://github.com/pytorch/pytorch/files/8399411/diff_distributed_03302022.txt)

Feb 01 comparison:
test1+test2
[diff_test1_test2_02012022.txt](https://github.com/pytorch/pytorch/files/8399406/diff_test1_test2_02012022.txt)
distributed
[diff_distributed_02012022.txt](https://github.com/pytorch/pytorch/files/8399408/diff_distributed_02012022.txt)

=================
raw pytorch ci log:
Mar 30
ROCm
[rocm1.txt](https://github.com/pytorch/pytorch/files/8399457/rocm1.txt)
[rocm_d.txt](https://github.com/pytorch/pytorch/files/8399462/rocm_d.txt)
[rocm2.txt](https://github.com/pytorch/pytorch/files/8399459/rocm2.txt)

CUDA
[cuda1.txt](https://github.com/pytorch/pytorch/files/8399464/cuda1.txt)
[cuda2.txt](https://github.com/pytorch/pytorch/files/8399465/cuda2.txt)
[cuda_d.txt](https://github.com/pytorch/pytorch/files/8399466/cuda_d.txt)


Feb 01
ROCm
[rocm1_02012022.txt](https://github.com/pytorch/pytorch/files/8399442/rocm1_02012022.txt)
[rocm2_02012022.txt](https://github.com/pytorch/pytorch/files/8399444/rocm2_02012022.txt)
[rocm_distributed_02012022.txt](https://github.com/pytorch/pytorch/files/8399445/rocm_distributed_02012022.txt)

CUDA
[cuda_test1_02012022.txt](https://github.com/pytorch/pytorch/files/8399447/cuda_test1_02012022.txt)
[cuda_test2_02012022.txt](https://github.com/pytorch/pytorch/files/8399448/cuda_test2_02012022.txt)
[cuda_distributed_02012022.txt](https://github.com/pytorch/pytorch/files/8399449/cuda_distributed_02012022.txt)

**Review by albanD — APPROVED** [review]
Thanks!

**Pull request closed without merging**
