### PR TITLE
Added twice differentiation for a bunch of ops

### PR DESCRIPTION
**Pull request by ankitkv**
Added twice differentiation for:

- [x] Addmm
- [x] Addbmm
- [x] Baddbmm
- [x] Addmv
- [x] Addr
- [x] Dot
- [x] Abs
- [x] Sum
- [x] Prod
- [x] Mean
- [x] Chunk
- [x] Linear

### CODE REVIEW

**Comment by ankitkv** [comment]
I think the tests still fail with the same problem on Travis (based on my previous brief PR), but I can't reproduce it on my end.

**Comment by soumith** [comment]
okay no problem, i'll look at the test locally and see if i can repro.

**Comment by soumith** [comment]
i cant reproduce this issue locally either. Weird.

**Comment by soumith** [comment]
okay i reproduced it on OSX after disabling BLAS by commenting out these lines: https://github.com/pytorch/pytorch/blob/master/torch/lib/TH/CMakeLists.txt#L278-L288
Looking...

**Comment by soumith** [comment]
found the issue. fixing shortly.

**Comment by soumith** [comment]
okay i fixed the bug in master via https://github.com/pytorch/pytorch/commit/c061ed5bda238e1276601593343c10428d01eaae and i rebased your commit on top of master. This should be good now.

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
this is really good stuff! Thanks a lot Ankit. 

cc: @lopezpaz

**Pull request merged**
