### PR TITLE
use make_shared and make_unique and clean unneeded code

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by peterjc123** [comment]
`std::make_unique_ptr` is in C++14 but I guess this should be fine.

**Comment by ezyang** [comment]
yeah, we c++14 now bois

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Blegh, header file can't be removed because there are internal projects using it.

**Comment by cyyever** [comment]
> Blegh, header file can't be removed because there are internal projects using it.

Which projects?

**Comment by ezyang** [comment]
They're some FB internal projects, we'd have to fix them. Or if you restore the header, they probably will just work.

**Comment by smessmer** [comment]
I fixed the internal call sites and landed this. Thanks @cyyever for fixing this.

**Pull request closed without merging**
