### PR TITLE
Turn translation validation on for tests and accuracy runs by default.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #97964
* #97963
* __->__ #103611
* #102563

This PR turns translation validation on by default for tests and accuracy benchmark
runs. It also installs Z3 on CI.

The main changes are:

- Add `--no-translation-validation` as an option in _test/run_tests.py_
    - Set `PYTORCH_TEST_WITH_TV` environment variable
- Add `TEST_WITH_TV` variable in _torch/testing/_internal/common_utils.py_
- Turn translation validation on for accuracy benchmarks in _benchmarks/dynamo/common.py_
- Add Z3 installation on CI scripts

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @msaroufim

### CODE REVIEW

**Comment by ezyang** [comment]
The timeouts are worth a look, but if the problem is just that we're sending problem instances that are too big to Z3, I'm OK with disabling translation validation for these specific models. It seems fairly predictable.

**Review by ezyang — APPROVED** [review]

**Comment by ysiraichi** [comment]
I am still investigating the benchmarks, but here's a summary of what I found:

### Benchmarks
All of the benchmarks below are failing with `timeout`.

- Both TIMM models are probably failing because the problem instances are too big
- TorchBench `cm3leon_generate` was creating many instances with no source expressions (will fix)
- Have yet to investigate the other 2 TorchBench benchmarks: `hf_T5_generate` and `yolov3`

From #97963 onwards, these failures go away.

### Tests
These 2 tests seem to be taking too long. Have yet to investigate.

- `DynamicShapesReproTests.test_longformer_chunk_dynamic_shapes`
- `DynamicShapesFunctionTests.test_torch_distributions_functions_dynamic_shapes`

Still present in #97964.

**Comment by ysiraichi** [comment]
After some investigation, I'm not really sure why `DynamicShapesFunctionTests.test_torch_distributions_functions_dynamic_shapes` takes so much time. I think I will fallback to "without TV" for now and investigate in a later PR. What do you think?

**Comment by malfet** [comment]
Why this was landed when it broke inductor left and right?

**Comment by ysiraichi** [comment]
@malfet It was because the 2 following PRs had, apparently, fixed that (they were all green). But, they ended up failing when merged. I did open a PR for fixing those, though (#104464).

**Comment by malfet** [comment]
@ysiraichi those were green because `ciflow/inductor` was missing (and failing jobs are only running on trunk or on PRs if label is applied) Stamped #104464 feel free to land if signal is green (but before that probably re-land this one with `-f`)

**Comment by ysiraichi** [comment]
@malfet Is it ok if I just open a new PR under #104464 stack, so that everything is in sync.?

**Comment by malfet** [comment]
@ysiraichi works for me or feel free to combine this change into https://github.com/pytorch/pytorch/pull/104464 but revert seems to have restored CI sanity

**Pull request closed without merging**
