### PR TITLE
[docs] Fix ScalarTensor __repr__ in Extending PyTorch example

### PR DESCRIPTION
**Pull request by jmargeta**
This PR fixes the __repr__ of the `ScalarTensor` class in the Extending PyTorch example to correspond with the class name instead of `DiagonalTensor`.

### CODE REVIEW

**Comment by bdhirsh** [comment]
I'm not sure that DiagonalTensor is the write name, since normal diagonal tensors can have a different value at every spot along the diagonal. The subclass example takes in a single scalar, and replicates that scalar across the diagonal.

**Comment by jmargeta** [comment]
I agree, that is a fair point. Thank you @bdhirsh.
However, in such a case, I suggest to fix the `__repr__` 
from:
```python
class ScalarTensor(object):
   ...
   def __repr__(self):
       return "DiagonalTensor(N={}, value={})".format(self._N, self._value)
   ...
```
to:

```python
class ScalarTensor(object):
   ...
   def __repr__(self):
       return "ScalarTensor(N={}, value={})".format(self._N, self._value)
   ...
```

**Comment by jmargeta** [comment]
I reverted the initial change and fixed the __repr__ instead.

**Comment by bdhirsh** [comment]
looks fine to me. Thanks!

**Comment by jmargeta** [comment]
Hey @bdhirsh, thanks a lot for giving this mini PR a look and for your approval! I've just seen that the merge is blocked, still awaiting a review. This is odd. Is there anything else for me to add/change?

**Review by bdhirsh — APPROVED** [review]

**Pull request closed without merging**
