### PR TITLE
inductor: log unique id to match output_code to aot graphs

### PR DESCRIPTION
**Pull request by bdhirsh**
I found it helpful to be able to see, given some inductor output code, which AOT graph it came from. When you have large models with multiple graphs floating around this can be difficult, so I added the aot_config.aot_id to the printed inductor output.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #118646
* #118645
* #118644
* __->__ #118647

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by ezyang** [comment]
Can you show what the logs look like?

**Review by ezyang — APPROVED** [review]

**Comment by bdhirsh** [comment]
yep - the generated python file from inductor now looks something like this:
```
# AOT ID: ['20_forward']
from ctypes import c_void_p, c_long
import torch
import math
import random
import os
import tempfile
from math import inf, nan
from torch._inductor.hooks import run_intermediate_hooks
from torch._inductor.utils import maybe_profile
from torch._inductor.codegen.memory_planning import _align as align

from torch import device, empty, empty_strided
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels
```

Vs. the AOT graphs from the logs look like this:
```
 ===== Joint graph 20 =====
    def forward(self, primals, tangents):
        primals_1: "bf16[5, 160]"; tangents_1: "bf16[10, 160]";
        ...

...

 ===== Forward graph 20 =====

    def forward(self, primals_1: "bf16[5, 160]"):
        all_gather_into_tensor: "bf16[10, 160]" = torch.ops.c10d_functional.all_gather_into_tensor.default(primals_1, 'ptd:4', [0, 2], 2);  primals_1 = None
        wait_tensor: "bf16[10, 160]" = torch.ops.c10d_functional.wait_tensor.default(all_gather_into_tensor);  all_gather_into_tensor = None
        return [wait_tensor]
```

**Comment by bdhirsh** [comment]
I also noticed that DTensor can desugar into different graphs on different ranks (to handle e.g. tensor sizes that are not divisible by the rank). So one other followup I'm thinking of doing is including the rank somewhere in the aot_id, if distributed is enabled.

**Pull request closed without merging**
