### PR TITLE
Skip test_nnc_correctness for new op _unsafe_masked_index

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #130375

### CODE REVIEW

**Comment by isuruf** [comment]
This test was failing in slow tests. Link: https://github.com/pytorch/pytorch/actions/runs/9656620718/job/26634753507

cc @clee2000 @lezcano @amjames

**Review by lezcano — APPROVED** [review]

**Comment by clee2000** [comment]
@isuruf Sorry do you mind explaining why its ok to skip these ex they're not supported, you're working on debugging, it's expected to be fixed by a different PR?

**Comment by isuruf** [comment]
It's not supported at the moment. If there's interest in supporting the new _unsafe_masked_index operator, we can debug.

**Pull request closed without merging**
