### PR TITLE
[dynamo] Store CompilationEvents in a buffer in torch._dynamo.utils

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #115793
* __->__ #115788

Motivation: it would be nice to be able to test using the metrics in log_compilation_event; currently dumps logs (or logs to a database in fbcode) - these are hard to use in unit tests.

This change: 
* always record the information in torch._dynamo.utils.record_compilation_metrics; here, log into a limited-size deque to prevent the list of metrics from getting too long
* if config.log_compilation_metrics, then call back into the original log_compilation_event function

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by davidberard98** [comment]
@yanboliang should we test compile time on this to make sure nothing regresses or do you think it should be safe?

**Review by yanboliang — APPROVED** [review]
It's better to run benchmark against this change, though I think it's low risk.

**Comment by davidberard98** [comment]
https://hud.pytorch.org/benchmark/compilers?startTime=Sat%2C%2009%20Dec%202023%2015%3A53%3A57%20GMT&stopTime=Sat%2C%2016%20Dec%202023%2015%3A53%3A57%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=gh/davidberard98/253/orig&lCommit=9bb30ccdff279f58d5d9b600d0ba539a1094a74c&rBranch=main&rCommit=36c6c0c7dc80d4e481cf451c1f9bb25454906bcc

Compile times did not change except for when models didn't run. I'm assuming these models didn't run for some other reason, because they weren't even attempted (no logs), and the CI on the PR isn't failing.

**Pull request closed without merging**
