### PR TITLE
Allow symbols to reach conv_layout stride argument

### PR DESCRIPTION
**Pull request by laithsakka**
#Fix https://github.com/pytorch/pytorch/issues/125638

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125829

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]

**Comment by laithsakka** [comment]
rebase on main to check if failures are for sire related to my change

**Comment by laithsakka** [comment]
> @pytorchbot revert -m "Broke inductor tests, see https://github.com/pytorch/pytorch/actions/runs/9028121462/job/24809113861" -c landrace

I rebase and rain the failing test localy it did not fail, repushing and re-landing.

**Comment by laithsakka** [comment]
https://github.com/pytorch/pytorch/pull/126116 override this,

**Pull request closed without merging**
