### PR TITLE
[JIT] Add an unused API

### PR DESCRIPTION
**Pull request by jamesr66a**
This allows us to mark a value as unused, but we do not want its producer node to be DCE'd. This allows us to do things like benchmark a single op in a loop without unrolling/DCE getting in the way

Differential Revision: [D15361137](https://our.internmc.facebook.com/intern/diff/15361137/)

### CODE REVIEW

**Review by eellison — APPROVED** [review]
Seems reasonable. I'm not sure how this prevents loop unrolling.

There are other ways to make sure that something doesn't get dce'd but I guess they'd interfere with the perf of the loop more, like using a value in an if statement that won't ever be true.

**Comment by jamesr66a** [comment]
@eellison the situation i'm describing is like this:

```
def foo(x):
  for i in range(1000):
    a = foo(x)
  return a
```

Gets unrolled to:

```
def foo(x):
  for i in range(1000 / 8):
    a = foo(x)
    a = foo(x)
    a = foo(x)
    a = foo(x)
    a = foo(x)
    a = foo(x)
    a = foo(x)
    a = foo(x)

  for i in range(1000 % 8):
    a = foo(x)
  return a
```

but then DCE kicks in to make it:

```
def foo(x):
  for i in range(1000 / 8):
    a = foo(x)

  for i in range(1000 % 8):
    a = foo(x)
  return a
```

**Comment by eellison** [comment]
Can you just run the graph without optimize being set instead ? we have a hook for that

**Review by suo — CHANGES_REQUESTED** [review]
I would prefer doing @eellison's suggestion of running with optimizations disabled instead of adding additional stuff.

**Comment by jamesr66a** [comment]
@suo I don't think it makes sense to disable optimizations wholesale if you just want to preserve a specific piece of the code that would otherwise be eliminated

**Comment by suo** [comment]
This is for microbenchmarking the fusion compiler, right? I think it's better to just specify IR directly and test at that level instead of threading a new concept through the compiler. Forcing optimization passes like CSE to know about yet another special case seems like a code smell to me.

**Comment by jamesr66a** [comment]
@suo, no this has nothing to do with the fusion compiler. This is part of the core+server optimization work. We need to ensure the performance *as close to production scenarios as possible* while making minimal edits for observability

**Comment by suo** [comment]
Maybe we should chat about it so I understand the context…I'm a little confused as to how can it be "as close to production scenarios as possible" if it's a synthetic benchmark of a pattern which would otherwise get DCE'd out. 

The stated goal of the PR is to get "single op in a loop" to work, you could do that by either disabling optimizations or constructing a graph by hand. If there's a more complicated use case, I'm still not sure it's best served by manually annotating ops rather than just using the full production artifact?

**Comment by jamesr66a** [comment]
@suo full production artifacts are not useful if you want to drill down to a specific performance bottleneck with tools like `perf`. My workflow has been:

1) look at the production artifact, timeline traces and maybe overall perf
2) Identify bottlenecks in the runtime. Ablate as needed to isolate
3) Look more and more at perf, since we are able to eliminate much of the noise from the surrounding stuff

Notice this is a gradient of going from full prod model -> subset of model -> single op (maybe). In the middle case (subset of model), it is not useful to disable optimizations, since it can drastically change the running characteristics of the program. To facilitate this, we can chop off sections before and after the region of interest, but in order to chop off stuff after we need to indicate that things are unused but cannot be eliminated.

As for constructing graphs, I don't think that's a very accessible API for this scenario, and for people working on the optimization effort in general

**Comment by zdevito** [comment]
I agree with @suo here. This is like trying to edit a similar feature in C++ or python. I've spent the last 2 weeks killing and regretting similar features because they cause death by 1000 cuts due to the added complexity. It will be necessary to figure out a way to get the behavior you want while still having whatever is added defined as a normal operator.

**Comment by eellison** [comment]
I think we could get the behavior we want here without hacking anything if we register Unused as a write, this would prevent CSE & other optimizations

**Comment by eellison** [comment]
Any thoughts @suo @zdevito ? I think this would solve our problems.

**Comment by suo** [comment]
I don't see how it would be any less of a hack. Unused isn't a write, so it would be weird to register it as a write. The behavior of optimizations with respect to writes is not an explicit or stable thing either, so it's doubly hacky.

**Comment by eellison** [comment]
We wouldn't have to touch the internals of CSE, that's why it's less of a hack. I don't think there is any contract that an op which registers a write necessarily changes the value of its input. `a = [0]; a[0] = 1` will not observably change the value of `a`.

Yes it relies on us not being able to do CSE for values which our written to - i don't see that change anytime soon. The alternative is people are asking to do something and we have no way of doing it.

**Comment by zdevito** [comment]
I don't think we have to provide anything inside the internals here. Someone can already accomplish what they want by just registering a no-op that is marked with the correct alias analysis information:

https://gist.github.com/zdevito/49f5bd4a912df5a553b4af47ddb5036f

**Comment by eellison** [comment]
This is functionally equivalent as marking an op as side-effectful and having writes. it has the same reliance that the previous suggestion had. I guess the question is if this is a common enough pattern that it makes sense to offer as a convenience api. If not it is probably worth having a entry in FAQ about profiling.

**Comment by ZolotukhinM** [comment]
@zdevito, @suo
I think using aliasing for this is also not ideal, because that's not what aliasing is for. The property we need here is "op has observable side effects". When we use aliasing for to solve this problem, we're basically relying on the optimizer not being smart enough to figure out that the code is doing nothing (which is often the case in benchmarks where we just want to repeat it N times) - in practice it's very annoying when suddenly benchmarks "improve" to 0ms after some change. Having explicitly defined barrier that optimizer never crosses defines this issue out.

> This is like trying to edit a similar feature in C++...
An example from C++ would be `volatile` - and that's the first class citizen in the language. Having a way to insert barriers is useful and I think it exists in most languages in some form.
Using alias info would be like writing to globals - it works until someone adds "-whole-program" to optimization flags and you need to rewrite the benchmarks because they are all optimized out.

**Comment by ZolotukhinM** [comment]
Side note: without the context I bet people would misinterpret the commit title "Add an unused API" - maybe quote 'unused' there :) @jamesr66a

**Pull request closed without merging**
