### PR TITLE
[v1.4.0] Fix reading `__cuda_array_interface__` inferred strides, add…

### PR DESCRIPTION
**Pull request by gchanan**
… test.

This is a simpler fix than https://github.com/pytorch/pytorch/pull/24947, which both fixed the bug and updated the protocol version.
This also adds a test (which the previous PR did not).

So the plan is that master (1.5) will have the new protocol version (and a test), 1.4 will have the old protocol version and the test.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit f7472e5:
* **1/1** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=f7472e55a2cd2e2f8c3a1c9e121f9dcfa76beaaf).

### :detective: 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4009567) pytorch_xla_linux_xenial_py3_6_clang7_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=77015930) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=77015930))
<details>
<summary>
<code>Dec 18 23:22:53 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-serialization.diff</code>
</summary>

```
Dec 18 23:22:52 + python /var/lib/jenkins/workspace/xla/scripts/cond_patch.py /var/lib/jenkins/workspace/xla/scripts/../torch_patches /var/lib/jenkins/workspace/xla/scripts/../.. 
Dec 18 23:22:53 1 out of 1 hunk FAILED 
Dec 18 23:22:53 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-clip_grad.diff 
Dec 18 23:22:53 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff 
Dec 18 23:22:53 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-serialization.diff 
Dec 18 23:22:53 Traceback (most recent call last): 
Dec 18 23:22:53   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 67, in <module> 
Dec 18 23:22:53     patch_repo(args) 
Dec 18 23:22:53   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 49, in patch_repo 
Dec 18 23:22:53     raise RuntimeError('Failed to apply patch: {}'.format(ppath)) 
Dec 18 23:22:53 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-serialization.diff 
Dec 18 23:22:53 + cleanup 
Dec 18 23:22:53 + retcode=1 
Dec 18 23:22:53 + set +x 
Dec 18 23:22:53 =================== sccache compilation log =================== 
Dec 18 23:22:53 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 18 23:22:53 Compile requests                 1 
Dec 18 23:22:53 Compile requests executed        0 
Dec 18 23:22:53 Cache hits                       0 
Dec 18 23:22:53 Cache misses                     0 
Dec 18 23:22:53 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by zou3519 — APPROVED** [review]

**Comment by leofang** [comment]
@nairbv Any chance you could update the release note for v1.4.0 to note this bug fix?

**Comment by nairbv** [comment]
> @nairbv Any chance you could update the release note for v1.4.0 to note this bug fix?

Updated, let me know if you have a better description I should use: https://github.com/pytorch/pytorch/releases/tag/v1.4.0

**Comment by leofang** [comment]
Thanks @nairbv 🙏 You could use something like “Fix reading from the interface when `strides` is missing or `None`”.

**Pull request merged**
