### PR TITLE
Ensure staticmethods can be allowed in graph

### LINKED ISSUE #124735: torch._dynamo.allow_in_graph seems to silently no-op on staticmethods
Example code:
```
import torch

class MyClass:
    i = 3

    @staticmethod
    def foo_inner(x):
        return torch.mul(x, MyClass.i)

    # allow_in_graph silently doesn't work, dynamo inlines foo1
    @staticmethod
    @torch._dynamo.allow_in_graph
    def foo1(x):
        return MyClass.foo_inner(x)

# allow_in_graph seems to work here though
@torch._dynamo.allow_in_graph
def foo2(x):
    return MyClass.foo_inner(x)





@torch.compile(backend="eager")
def f_bad(x):
    return MyClass.foo1(x)

@torch.compile(backend="eager")
def f_good(x):
    return foo2(x)

x = torch.ones(2)
f_bad(x)
f_good(x)
```

Dynamo seems to inline the `foo1` call in `f_bad`, even though we've marked it allow_in_graph. But dynamo properly preserved `foo2` in the graph for `f_good`. I pasted the output of running with `TORCH_LOGS="graph_code"` below:
```
DEBUG: TRACED GRAPH
 ===== __compiled_fn_1 =====
 /data/users/hirsheybar/b/pytorch/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
    def forward(self, L_x_ : torch.Tensor):
        l_x_ = L_x_

        # File: /data/users/hirsheybar/b/pytorch/tmp.py:8 in foo_inner, code: return torch.mul(x, MyClass.i)
        mul = torch.mul(l_x_, 3);  l_x_ = None
        return (mul,)


DEBUG: TRACED GRAPH
 ===== __compiled_fn_3 =====
 /data/users/hirsheybar/b/pytorch/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
    def forward(self, L_x_ : torch.Tensor):
        l_x_ = L_x_

        # File: /data/users/hirsheybar/b/pytorch/tmp.py:31 in f_good, code: return foo2(x)
        foo2 = __main___foo2(l_x_);  l_x_ = None
        return (foo2,)

```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78

### PR DESCRIPTION
**Pull request by mlazos**
Fixes https://github.com/pytorch/pytorch/issues/124735

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]

**Review by williamwen42 — APPROVED** [review]

**Comment by mlazos** [comment]
@pytorbhbot merge

**Comment by mlazos** [comment]
Abandoning, so broken, reland at https://github.com/pytorch/pytorch/pull/131789

**Pull request closed without merging**
