### PR TITLE
Check value type when registering buffer

### PR DESCRIPTION
**Pull request by Stonesjtu**
At the current version, once user register a buffer with non-tensor, e.g. int(9) then the `module.cuda()` fails. 

Actually a `Variable` buffer should be OK now, but the docstr limits the type to only `Tensor`.

### CODE REVIEW

**Comment by Stonesjtu** [comment]
@soumith Some modules use `Variable` as buffers. If we are going to support this, it's better to clarity the acceptable types of buffer (Variable and Tensor) explicitly in the doc.

**Comment by ezyang** [comment]
IIUC, this will stop being a problem when we merge Variable and Tensor, since all buffers will automatically become Variables. So I think we should hold off on this patch. CC @colesbury

**Comment by Stonesjtu** [comment]
`Variable` and `Tensor` are OK for `buffer` if merged. But the built-in type such as int and float should not be registered into `buffer`, because the `.cuda` method of `nn.Module` will fail.

**Pull request closed without merging**
