### PR TITLE
Native batch norm

### PR DESCRIPTION
**Pull request by t-vi**
- Move batch norm from TH(CU)NN to native
- Speedups in many cases (e.g. #12006) for CUDA due to new block/grid layout and Welford-type mean/variance calculations (the latter for training mode)
- It splits the forward kernel in two pieces and reuses the evaluation kernel for the transformation.
- We change the meaning of save_mean and save_invstd (aka save_var) to accscalar to maintain reasonable precision.

Compared to the ill-fated #12368 
- I changed the CPU kernel to not call `.sum()` from within parallel for. This seemed to have caused the breakage (NaN-results) in TestModels.test_dcgan_netG (thank you @houseroad for the repro, errors in assessment of the fix are my own)
- I updated the Half->Float upcasting in tensors to go through `t.type().scalarType()` instead of `t.dtype()`.
- I have merged master

### CODE REVIEW

**Comment by t-vi** [comment]
@SsnL so adding and removing `don't use tensor.sum() in parallel_for` in @houseroad 's docker seems to reliably turn the bug off and back on.

**Comment by t-vi** [comment]
So one CI failure is a build timeout.
The other is more interesting, it concerns the onnx inception test. The compared arrays are ~1e10 and the mismatch is 0.05%(?) - that doesn't match well with rtol=0.01. I might be tempted to think it's a precision problem.
```
E               AssertionError: 
Oct 29 20:59:36 E               Not equal to tolerance rtol=0.01, atol=1e-07
Oct 29 20:59:36 E               
Oct 29 20:59:36 E               (mismatch 0.05%)
Oct 29 20:59:36 E                x: array([-4.504718e+09,  1.420829e+10,  2.013276e+09, ...,  1.283971e+10,
Oct 29 20:59:36 E                       4.517736e+09, -1.183408e+10], dtype=float32)
Oct 29 20:59:36 E                y: array([-4.504723e+09,  1.420830e+10,  2.013278e+09, ...,  1.283971e+10,
Oct 29 20:59:36 E                       4.517729e+09, -1.183407e+10], dtype=float32)
Oct 29 20:59:36 
```
There is a comment at the top of the failing `verify` function, not sure if that's applicable here:
> This function may spuriously fail: some operators are implemented with
> different numerical precision in an ONNX backend, in which case an unstable
> network (e.g., Inception) may blow up these numerical instabilities.  This
> situation is less likely to happen if your model has been trained.  However,
> if this is not the case, you may have found a bug!  Please report it to the
> PyTorch developers.  You can also debug the issue yourself by removing
> suffixes of operators from your model until verification passes.

@houseroad Do you have advice on this? I would much appreciate your input!

**Comment by houseroad** [comment]
@t-vi, it doesn't make sense to have such small inputs, let me fix it in different PR and you can rebase on that later.

**Comment by houseroad** [comment]
@t-vi try rebase and let CI test again?

**Comment by SsnL** [comment]
Thank you @t-vi

**Pull request closed without merging**
