### PR TITLE
[quant][be] Remove special casing for getitem in prepare

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #90393

Summary:
This PR cleans up previous special casing for getitem, it should be configured through BackendConfig

Test Plan:
python test/test_quantization.py TestQuantizeFx

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D41846185](https://our.internmc.facebook.com/intern/diff/D41846185)

### CODE REVIEW

**Comment by andrewor14** [comment]
What was the purpose of this special case in the first place? It seems if the entry is missing in BackendConfig it would just default to `torch.float` anyway?

**Comment by jerryzh168** [comment]
> What was the purpose of this special case in the first place? It seems if the entry is missing in BackendConfig it would just default to `torch.float` anyway?

yeah I don't remember, probably because of some historical reasons since backend config is not there in the very begining

**Review by andrewor14 — APPROVED** [review]
Got it. Yeah looks good as long as the tests pass.

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41846185).

**Pull request closed without merging**
