### PR TITLE
Fix documentation and argument name for Tensor.normal_(mean, stddev)

### PR DESCRIPTION
**Pull request by colesbury**

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by szagoruyko** [comment]
can we rename it to `std`? I think it's better, short and simple

**Comment by apaszke** [comment]
Yeah I thought about std too. It matches the method name.

**Comment by colesbury** [comment]
I'm fine with changing the name, we just need to do it for all the methods that take a standard deviation.

**Comment by apaszke** [comment]
Do we have stddev anywhere else?

**Comment by apaszke** [comment]
No, it's that only in `normal_`

**Comment by colesbury** [comment]
And torch.normal and Variable.normal

**Pull request merged**
