### PR TITLE
[Quant] Update IDeep to support oneDNN conv add fusion

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #90605
* #90157

**Summary**
This PR updates IDeep to support oneDNN conv add fusion.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @gujinghui @PenghuiCheng @XiaobingSuper @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen

### CODE REVIEW

**Comment by Xia-Weiwen** [comment]
Hi @leslie-fang-intel Please sync with @yanbing-j for updating ideep in stock PT. Now all PRs to update ideep are opened and managed by her.

**Review by jgong5 — APPROVED** [review]
Weird that I cannot add @yanbing-j as a reviewer. LGTM but needs Yanbing to stamp on it too.

**Comment by yanbing-j** [comment]
Maybe I have no permission, so that I cannot be added as a reviewer.
Hi @leslie-fang-intel , you can submit PR in ideep_pytorch first. Then rebase this PR to include ideep changes.

**Comment by leslie-fang-intel** [comment]
> Maybe I have no permission, so that I cannot be added as a reviewer. Hi @leslie-fang-intel , you can submit PR in ideep_pytorch first. Then rebase this PR to include ideep changes.

@yanbing-j Yes, here is the PR to ideep_pytorch (https://github.com/intel/ideep/pull/148), it's still waiting @jgong5 review.

**Comment by malfet** [comment]
Please note, that one would not be able to use any of the new onednn/ideep/mkldnn features in the codebase until it could also be upgraded in Meta's internal checkout which is currently blocked by the fact that mkldnn is checked out twice, see  https://github.com/pytorch/pytorch/pull/90264#issuecomment-1360663940

**Comment by jgong5** [comment]
> Please note, that one would not be able to use any of the new onednn/ideep/mkldnn features in the codebase until it could also be upgraded in Meta's internal checkout which is currently blocked by the fact that mkldnn is checked out twice, see [#90264 (comment)](https://github.com/pytorch/pytorch/pull/90264#issuecomment-1360663940)

Thanks for the note. We are working on a solution to avoid the checked out twice issue. Will keep you updated.

**Pull request closed without merging**
