### PR TITLE
Revert "Make offsets dynamic by default (#113734)"

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #114889

This reverts commit 7c38b76efec65249e39ae2b8fd8280dfebd1d415.

if a graph has a lot of inputs which are views (with nonzero storage offset), then the check for overlapping tensor views will add a lot of guards (n^2?)

https://github.com/pytorch/pytorch/blob/b35ca2cb941b5ba90858322810ca85c31e4541fd/torch/_functorch/_aot_autograd/input_output_analysis.py#L256-L260

this was causing very slow compilations on an internal model.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

Differential Revision: [D51733774](https://our.internmc.facebook.com/intern/diff/D51733774)

### CODE REVIEW

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51719326).

**Review by ckluk2 — APPROVED** [review]
LGTM

**Review by YuqingJ — APPROVED** [review]

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51733774).

**Review by aaronenyeshi — APPROVED** [review]
Approving the revert diff.

**Pull request closed without merging**
