### PR TITLE
Loops.cuh legacy code cleanup -- gpu_kernel_with_index

### PR DESCRIPTION
**Pull request by zasdfgbnm**
I didn't see any use case where the functor of `gpu_kernel_with_index` needs to have argument other than the index. Merge conflict with https://github.com/pytorch/pytorch/pull/32755.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 1d51f40b:


**None of the build failures appear to be your fault**.

* **1/1** recognized as flaky :snowflake:
    * Re-run these jobs?


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=1d51f40b7c72a2cc6940623af22e9da3b3d7ffc7).

### :snowflake: 1 failure recognized as flaky
The following build failures have been detected as flaky and **may not be your fault**:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4371130) pytorch_libtorch_linux_xenial_cuda10_1_cudnn7_py3_gcc7_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=92721816) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=92721816)) :snowflake:
<details>
<summary>
<code>Jan 29 19:59:26 E: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/./libnccl-dev_2.5.6-1+cuda10.1_amd64.deb  Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds</code>
</summary>

```
Jan 29 19:54:44 ++ which ccache 
Jan 29 19:54:44 ++ '[' -z pytorch-libtorch-linux-xenial-cuda10.1-cudnn7-py3-gcc7-build ']' 
Jan 29 19:54:44 ++ [[ pytorch-libtorch-linux-xenial-cuda10.1-cudnn7-py3-gcc7-build == *pytorch-linux-xenial-cuda10.1-cudnn7-py3* ]] 
Jan 29 19:54:44 ++ [[ pytorch-libtorch-linux-xenial-cuda10.1-cudnn7-py3-gcc7-build == *pytorch-linux-trusty-py3.6-gcc7* ]] 
Jan 29 19:54:44 ++ [[ pytorch-libtorch-linux-xenial-cuda10.1-cudnn7-py3-gcc7-build == *pytorch_macos* ]] 
Jan 29 19:54:44 ++ BUILD_TEST_LIBTORCH=0 
Jan 29 19:54:44 ++ [[ pytorch-libtorch-linux-xenial-cuda10.1-cudnn7-py3-gcc7-build == *pytorch-linux-xenial-cuda* ]] 
Jan 29 19:54:44 + [[ pytorch-libtorch-linux-xenial-cuda10.1-cudnn7-py3-gcc7-build == *-xenial-cuda10.1-* ]] 
Jan 29 19:54:44 + sudo apt-get -qq update 
Jan 29 19:54:48 + sudo apt-get -qq install --allow-downgrades --allow-change-held-packages libnccl-dev=2.5.6-1+cuda10.1 libnccl2=2.5.6-1+cuda10.1 
Jan 29 19:59:26 E: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/./libnccl-dev_2.5.6-1+cuda10.1_amd64.deb  Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds 
Jan 29 19:59:26  
Jan 29 19:59:26 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing? 
Jan 29 19:59:26 =================== sccache compilation log =================== 
Jan 29 19:59:26 + cleanup 
Jan 29 19:59:26 + retcode=100 
Jan 29 19:59:26 + set +x 
Jan 29 19:59:26 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 29 19:59:26 Compile requests                 0 
Jan 29 19:59:26 Compile requests executed        0 
Jan 29 19:59:26 Cache hits                       0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by zasdfgbnm** [comment]
windows is having strange failures...

**Comment by zasdfgbnm** [comment]
Windows build is magically fixed after resolving a merge conflict 😂😂😂

**Comment by zasdfgbnm** [comment]
ready

**Comment by ngimel** [comment]
I agree that it is currently not used (it is used only in range factories, where indeed the only argument is index), but it's conceivable that gpu_kernel_with_index can also require other arguments - e.g. if you want to implement something like adjacent differences? Does it make sense to still remove this implementation, I don't think it appreciably increases compilation time.

**Comment by zasdfgbnm** [comment]
@ngimel Yes, I agree it is a good idea to keep it if it is already there, but the current situation is, it is legacy code and needs to be migrated. So the only two options are:
1. Delete it completely, when needed in the future, add it back in the new code.
2. Delete it completely, add it back in the new code now.

I think it is reasonable to do 1, but I am also OK with 2 if you want. Let me know your opinion.

**Comment by ngimel** [comment]
1. is reasonable, leave a comment in the source pointing to this PR so it's easier to find older implementation if someone needs to do 2.

**Comment by zasdfgbnm** [comment]
@ngimel Sure, great point

**Comment by zasdfgbnm** [comment]
@ngimel Note added

**Review by ngimel — APPROVED** [review]

**Comment by zasdfgbnm** [comment]
just resolved merge conflict

**Pull request closed without merging**
