### PR TITLE
Support for Eigen thread pool

### PR DESCRIPTION
**Pull request by ilia-cher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#20157 Support for Eigen thread pool**
* #20087 Native ATen/Parallel backend
* #20057 Split ATen/Parallel into interface and backend
* #20050 Move inter-op settings into ATen/Parallel
* #20043 Port ATen/native to ATen/Parallel
* #20032 Port THNN to ATen/Parallel
* #20002 Remove explicit checks for parallelism from TH
* #19105 Port TH library to ATen/Parallel
* #19997 Intra-op parallel microbenchmarks for PT
* #19993 Support for non-contiguous tensors and arbitrary dtypes in PT benchmarks
* #19980 Initialize Caffe2 only when running Caffe2 benchmarks
* #19749 Allow a non-OpenMP based build

Summary:
Adding support for Eigen thread pool as a replacement
for the current native thread pool

Test Plan:
USE_EIGEN_THREADPOOL=1 USE_CUDA=0 PARALLEL_BACKEND=NATIVE BLAS=MKL
USE_MKLDNN=1 USE_OPENCV=1 USE_FFMPEG=1 python setup.py develop --cmake
pytest -s -v test/test_torch.py::TestTorch
pytest -s -v test/test_jit.py

Differential Revision: [D15248708](https://our.internmc.facebook.com/intern/diff/D15248708)

### CODE REVIEW

**Comment by jamesr66a** [comment]
Any way to test this?

**Comment by ilia-cher** [comment]
@jamesr66a I did build PT with `PARALLEL_BACKEND=NATIVE` to use native thread pool and with `USE_EIGEN_THREADPOOL=1` to use Eigen, then ran `test_torch.py`, a lot of the ops in these tests use parallelism and we also have dedicated parallelization tests there (e.g. `test_cpu_parallel`) and I also ran `test_jit.py` to check `fork/join` tests 
We don't have a dedicated thread pool test in PT itself, but there's one in Eigen, we could maybe also include it

**Comment by ilia-cher** [comment]
@jamesr66a I also ran `test_jit.py` to test explicit fork/join parallelism

**Comment by jamesr66a** [comment]
Ok. But should we get this tested in CI somehow?

**Comment by ilia-cher** [comment]
Makes sense, I guess we should add a few more builds, not only for Eigen but for native and TBB backends too; I think it's better to send a separate PR, it will require some changes to our CI builds and @kostmo review

**Comment by cpuhrsch** [comment]
Where will this be needed? For now we wanted to avoid adding Eigen as a dependency. cc @soumith

**Comment by ilia-cher** [comment]
@cpuhrsch interesting, I was actually just going to post benchmark results that show that Eigen thread pool is way more faster than our simple thread pool implementation

**Comment by ilia-cher** [comment]
some benchmarking data
```
./build/bin/at_launch_benchmark
Launching 10000000 tasks using 48 threads
Time to run 10000000 iterations 19.216 s.

(48 - size of the thread pool)

vs. when built with USE_EIGEN_THREADPOOL=0:

./build/bin/at_launch_benchmark
Launching 10000000 tasks using 48 threads
Time to run 10000000 iterations 187.441 s.
```
when using 50 parallel threads launching tasks instead of a single serial loop 
```
Launching 10000000 tasks using 48 threads
Time to run 10000000 iterations 9.916 s.
vs.
Launching 10000000 tasks using 48 threads
Time to run 10000000 iterations 95.326 s.
```

**Pull request closed without merging**
