### PR TITLE
add `foreach_abs` meta registration and inductor decomp

### LINKED ISSUE #110458: bug(aten): poor support for aten `foreach_abs`
### 🐛 Describe the bug
 `aten._foreach_abs` is extern and hence obstructs fusion and `aten._foreach_abs_` has no Meta kernel
 
```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
NotImplementedError: aten::_foreach_abs_: attempted to run this operator with Meta tensors, but there was no abstract impl or Meta kernel registered. You may have run into this message while using an operator with PT2 compilation APIs (torch.compile/torch.export); in order to use this operator with those APIs you'll need to add an abstract impl.Please see the following doc for next steps: https://docs.google.com/document/d/1_W62p8WJOQQUzPsJYa7s701JXt0qf2OfLub2sbkHOaU/edit

While executing %_foreach_abs_ : [num_users=0] = call_function[target=torch._foreach_abs_](args = ([%x_4, %x_5, %x_6, %x_7],), kwargs = {})
Original traceback:
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/test/inductor/test_compiled_optimizers.py", line 63, in fn
    step_fn(opt_compiled)
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/optim/adamax.py", line 124, in step
    adamax(
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/optim/adamax.py", line 230, in adamax
    func(
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/optim/adamax.py", line 354, in _multi_tensor_adamax
    torch._foreach_abs_(grouped_grads)
```

EDIT:
1. These are actually 2 separate issues: meta kernel can be solved easily with meta registration
2. Why these kernels are extern is yet undiagnosed. Here are two cases:
    - `cannot fuse (1): node1 buf12: ExternKernelSchedulerNode(FallbackKernel)`,`buf12.node.kernel = aten._foreach_abs`
    - `cannot fuse (2): node2 buf14: ExternKernelSchedulerNode(MultiOutput)`,`buf14.node.kernel = None`

In all likelihood, foreach abs has no prim decomp, and hence necessitates fallback.

### Versions

main

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

### PR DESCRIPTION
**Pull request by jon-chuang**
Fixes https://github.com/pytorch/pytorch/issues/110458

Somehow it is on allowlist but not on testing path.

CC @janeyx99 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
Thanks!

**Comment by jon-chuang** [comment]
ROCm CI error:
```
2023-10-03T23:05:29.5559477Z ==================================== RERUNS ====================================
2023-10-03T23:05:29.5559892Z ____________ CudaTests.test_max_pool2d_with_indices_backward3_cuda _____________
2023-10-03T23:05:29.5560346Z Traceback (most recent call last):
2023-10-03T23:05:29.5560756Z   File "inductor/test_torchinductor.py", line 7177, in new_test
2023-10-03T23:05:29.5561115Z     return value(self)
2023-10-03T23:05:29.5561527Z   File "inductor/test_torchinductor.py", line 5484, in test_max_pool2d_with_indices_backward3
2023-10-03T23:05:29.5561929Z     self.common(
2023-10-03T23:05:29.5562321Z   File "/opt/conda/envs/py_3.8/lib/python3.8/contextlib.py", line 75, in inner
2023-10-03T23:05:29.5562709Z     return func(*args, **kwds)
2023-10-03T23:05:29.5563113Z   File "inductor/test_torchinductor.py", line 455, in check_model_cuda
2023-10-03T23:05:29.5563485Z     check_model(
2023-10-03T23:05:29.5563838Z   File "inductor/test_torchinductor.py", line 348, in check_model
2023-10-03T23:05:29.5564205Z     self.assertEqual(
2023-10-03T23:05:29.5564841Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 3309, in assertEqual
2023-10-03T23:05:29.5565335Z     raise error_metas.pop()[0].to_error(
2023-10-03T23:05:29.5565843Z AssertionError: Tensor-likes are not close!
```

All tests pass for me on CUDA device. I'm gonna call it unrelated.

**Pull request closed without merging**
