### PR TITLE
Define objects using classes instead of namedtuples in torch.utils.data._utils.worker

### PR DESCRIPTION
**Pull request by Loquats**
This PR fixes a bug when torch is used with pyspark, by converting namedtuples in `torch.utils.data._utils.worker` into classes. 

Before this PR, creating an IterableDataset and then running `list(torch.utils.data.DataLoader(MyIterableDataset(...), num_workers=2)))` will not terminate, if pyspark is also being used. This is because pyspark hijacks namedtuples to make them pickleable ([see here](https://github.com/apache/spark/blob/master/python/pyspark/serializers.py#L370)). So `_IterableDatasetStopIteration` would be modified, and then the check at [this line in dataloader.py](https://github.com/pytorch/pytorch/blob/5472426b9f85c8107aade5d256cf4cde572eab5c/torch/utils/data/dataloader.py#L1072) is never true. 
Converting the namedtuples to classes avoids this hijack and allows the iteration to correctly stop when signaled.

### CODE REVIEW

**Comment by albanD** [comment]
It would be nice to have these as dataclass no?

**Comment by Loquats** [comment]
Hey @albanD, I updated the PR to use dataclasses, and fixed the lint failures.
The latest commit failed the pytorch_linux_xenial_py3_clang5_asan_test2 CI tests, but I cannot reproduce it locally, and I'm not sure if it is relevant to this PR.
Let me know if you have any feedback.

**Review by albanD — COMMENTED** [review]
Great! Thanks for the update.
And yes this build is flaky, you can ignore the CI signal.

**Review by albanD — APPROVED** [review]

**Comment by Loquats** [comment]
Sounds good! What are the next steps towards merging this PR?

**Comment by albanD** [comment]
Nothing on your side, I am shepherding it through the internal testing and landing.
It should happen later today or tomorrow.
The PR will be closed with a reference to the commit in master corresponding to it.

**Comment by fmassa** [comment]
FYI this PR adds an extra dependency to `dataclass` to PyTorch for Python < 3.7. Note that we still support Python 3.6, which makes it break CI for some downstream projects like torchvision, see https://app.circleci.com/pipelines/github/pytorch/vision/4376/workflows/c7b6522f-031d-4942-a8a6-c6d0f9a5a76b/jobs/260192 for an example.

This dependency should be added to PyTorch if we still plan to support Python 3.6

cc @seemethere if we are dropping support for Python 3.6 soon in PyTorch

**Comment by albanD** [comment]
Thanks for pointing this out, I though it was ok as they are already used in [a few places](https://github.com/pytorch/pytorch/search?q=dataclass) in the codebase (even outside codegen).

Do you want to revert this until we fix the dependency issue? It will be easy to reland afterwards.

**Comment by albanD** [comment]
After taking a closer look, no other usage is in the main codebase but all are in benchmark/codegen/utils code.

**Comment by seemethere** [comment]
I'm pretty sure we already had a dependency on the `dataclasses` package?

https://github.com/pytorch/pytorch/blob/1a57b390e81c75f4254bf95b6a4d181e98c045a8/setup.py#L346-L350

Introduced via, https://github.com/pytorch/pytorch/pull/42629

**Comment by fmassa** [comment]
@seemethere In torchvision CI we use PyTorch from a nightly via conda and pip, so we don't compile it from source.
The PyTorch pip packages work fine on 3.6, but not the conda packages

**Pull request closed without merging**
