### PR TITLE
[RFC] Black common_methods_invocations.py

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #76352
* __->__ #76314

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by mruberry — APPROVED** [review]
#stats

**Comment by ezyang** [comment]
@mruberry did you look at what the formatting looks like? A lot of previously single line declarations got broken into multiple lines. It's not clear to me that the result is more readable.

**Comment by eellison** [comment]
Since this is an RFC.... I don't like black's output formatting. This is a small example from applying black on `test/jit/test_symbolic_shape_analysis` where IMO formatting became much worse (6 more lines, irregular, harder to parse).

image

If you think about code as being read much more than it is written, I don't know that making it easier to write code that passes lint at the expense of having code harder to read is worth it. I would personally prefer that people who want to write with black use a version of it that only runs on the changes in their PR.

**Comment by ngimel** [comment]
Yep, OpInfos are verbose enough as is. Black doubles the line count with dubious readability improvement

**Comment by ezyang** [comment]
The real payment for using black is much easier automated refactorability. Without black, if I want to codemod the test code I have to do so in a way that preserves lint. This is harder than just doing something ugly and then using black to clean it up. This is important for common_methods_invocations.py because there is SO MUCH code in this file, the only way we will be able to do refactors is by some sort of automated codemod.

That being said, it definitely does feel like it is not worth it. Maybe we need to design a DSL for defining OpInfos rather than doing it in stock Python.

**Comment by mruberry** [comment]
> @mruberry did you look at what the formatting looks like? A lot of previously single line declarations got broken into multiple lines. It's not clear to me that the result is more readable.

I've run black locally and it looks fine. It's nice not to have to think about formatting. 

> That being said, it definitely does feel like Black formatting here is much worse. Maybe we need to design a DSL for defining OpInfos rather than doing it in stock Python.

A DSL sounds like a confounding pain but maybe there's a brilliant way to do it I haven't thought of.

**Comment by eellison** [comment]
@ezyang can you apply a codemod and then run black on only the changed code ?

**Comment by ezyang** [comment]
> @ezyang can you apply a codemod and then run black on only the changed code ?

Apparently darker lets you do this https://github.com/akaihola/darker 

But if the code wasn't in black style to begin with this will just look like a lot of gratuitous reformatting, so it's not really a help.

**Comment by ezyang** [comment]
If Mike's OK with it, I'm OK with it. But if someone strenuously objects I don't want to bowl them over :)

**Comment by eellison** [comment]
Should we consider sharding the files ? Pretty sure git will just choke on a file this large

**Comment by mruberry** [comment]
> Should we consider sharding the files ? Pretty sure git will just choke on a file this large

I always thought we would break up common_methods_invocations.py (which is a silly name that we inherited) because it is over 10k lines, and GitHub (incredibly) can't consistently display files with 10k+ lines, but some people really like having everything in a single file.

**Comment by eellison** [comment]
Context is, I was just trying to link someone to where to change `argmax`, but I can't because github only displays the first 11000 lines

**Comment by mruberry** [comment]
> Context is, I was just trying to link someone to where to change `argmax`, but I can't because github only displays the first 11000 lines

Yeah, it bites. Eventually we should spend the time and energy to reconcile the divergent opinions.

**Comment by ezyang** [comment]
tbh someone is going to have to write a codemod script to do the split. If we can agree on the design it probably wouldn't even be that hard to do.

**Pull request closed without merging**
