### PR TITLE
GCC ABI variants for nightly builds

### LINKED ISSUE #17492: Libtorch binaries compiled with flag _GLIBCXX_USE_CXX11_ABI = 1
Libtorch binaries can be installed from  https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip, but these are build with _GLIBCXX_USE_CXX11_ABI = 0 which make it incompatible for certain cases. Is it possible to get latest ompiled with _GLIBCXX_USE_CXX11_ABI = 1

### PR DESCRIPTION
**Pull request by kostmo**
closes #17492

### CODE REVIEW

**Comment by kostmo** [comment]
binarysmoketests-config-dimensions

**Comment by ezyang** [comment]
Hi, could you please write a general description about how this PR is structured? It's pretty long, and an executive summary saying what exactly happened would be helpful.

**Comment by pjh5** [comment]
This PR does two things
1: Moves out many of the binary-build setup-scripts into .sh files (and then calls them by curl-ing them from Github)
2. Renames all current binary-builds to have 'gccabi0' in their name, and then duplicate all the linux x wheel+libtorch builds to also have a 'gccab1' variant. The new gcc version is installed into the docker before the rest of the build runs.

We did 1 because doing 2 caused the length of the config.yml to go over 4MB (as CircleCI just copies all the '<<*foo' sections to everywhere that they appear), so we had to decrease the amount of code that was copied.

**Comment by ezyang** [comment]
> Renames all current binary-builds to have 'gccabi0' in their name, and then duplicate all the linux x wheel+libtorch builds to also have a 'gccab1' variant. The new gcc version is installed into the docker before the rest of the build runs.

So, I thought the conclusion from internal discussion was that building `_GLIBCXX_USE_CXX11_ABI=0` and `_GLIBCXX_USE_CXX11_ABI=1` was just a band-aid, and the truly correct answer to solving our ABI problems was to build versions of PyTorch with ABI compatible with the Linux distribution default compiler toolchain. Is this just the band-aid solution?

Also, bikeshedding names, "gccabi0" implies that you're talking about the "GCC ABI" as a whole. But there is no such thing as "GCC ABI 0" (which is why I am guessing that you're actually talking about `_GLIBCXX_USE_CXX11_ABI`; hard to say because this process happens implicitly in https://github.com/pytorch/builder/blob/master/upgrade_gcc_abi.sh GCC ABI's are generally per version, c.f. https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html and so if you really just mean cxx11 abi, you should say so in the name (but I would much prefer we track the ABI of specific distro distributed compilers.)

**Comment by ezyang** [comment]
> Moves out many of the binary-build setup-scripts into .sh files (and then calls them by curl-ing them from Github)

I'd happily accept this PR, though right now it's smooshed into this one ;)

**Comment by ezyang** [comment]
> calls them by curl-ing them from Github

Can you remind me why we can't just execute them from the source checkout? I distinctly remember asking this before, but there does not appear to be a comment about why we have to do it this way in the diff. Was it something do with the binary builds not having a source checkout available early enough? Can we use the source checkout for normal CI builds?

One reason I really don't want to curl from GitHub is that it introduces a large extra number of points of failure which will cause flaky CI runs when there are connection problems between CircleCI and GitHub. I would much rather that if we manage to successfully checkout our GitHub source copy, we cannot fail a build because a CircleCI builder can no longer talk to GitHub.

**Comment by pjh5** [comment]
The gccabi# name is actually incorrect then. We don't actually specify the _GLIBCXX_USE_CXX11_ABI flag anywhere; the change just upgrades the gcc from 4.8 to >7 . We should just rename this to the devtoolset version

We could execute some of them from the source checkout with some more refactoring. The binary_checkout job would have to be curled still (or we could just leave it and hope the size is under 4MB). We can't use the source checkout for normal CI builds (all the non-binaries) since the binary builds use two repos, pytorch and builder.

**Comment by ezyang** [comment]
Sure, I'm OK with only curl'ing `binary_checkout`, that seems quite reasonable to me.

**Comment by ezyang** [comment]
OK, so is the removal of curl going to happen in this PR or a follow up?

**Review by ezyang — DISMISSED** [review]
Please dismiss this when ready for rereview

**Comment by pjh5** [comment]
@ezyang @kostmo does everything look good to y'all?

**Review by ezyang — APPROVED** [review]
okey dokey

I'm assuming the moved scripts didn't change in any substantive way; those were not reviewed.

**Comment by ezyang** [comment]
According to @heiner, @pjh5 says that the new gcc abi variants don't actually work yet.

**Comment by pjh5** [comment]
Yes. See https://github.com/pytorch/pytorch/pull/19782 . We should probably remove them for now.

**Pull request closed without merging**
