### PR TITLE
Upgrade nightly wheels to rocm6.2 - 2 of 2 (binaries)

### PR DESCRIPTION
**Pull request by jithunnair-amd**
Depends on https://github.com/pytorch/pytorch/pull/132875

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@atalman All binary build/test jobs succeeded.

**Review by atalman — APPROVED** [review]
lgtm

**Pull request closed without merging**
