### PR TITLE
[ONNX] Added cons folding for ONNX mul, div, sqrt ops

### PR DESCRIPTION
**Pull request by neginraoof**
An example of a model with such leaf nodes is faster_rcnn model. This PR helps optimizing onnx ops.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 3fd6ab58:


**None of the build failures appear to be your fault**.

* **1/1** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=bc68a8745f1838f4e519f2f456593f8189ba23ee&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base bc68a874 since Jan 09
  <details>
  <summary>
  Please rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  Since your merge base is older than `viable/strict`, run these commands:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=3fd6ab58d7a249807324e07bedf32d9e6fc6366f).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [pytorch_linux_xenial_cuda9_cudnn7_py3_build](https://dr.pytorch.org/build-details.html?build_id=83732331) from Jan 09 until Jan 09



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by neginraoof** [comment]
cc @lara-hdr @spandantiwari @BowenBao for review. Thanks.

**Review by lara-hdr — APPROVED** [review]
LGTM, thanks!

**Review by houseroad — APPROVED** [review]
LGTM

**Pull request closed without merging**
