### PR TITLE
[quant][observer] Change return type of observer to two tensors

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#24339 [quant][observer] Change return type of observer to two tensors**

Summary:
Att

Test Plan:
python test/test_quantization.py

Reviewers:
pt1quant
Subscribers:

Tasks:

Tags:

Differential Revision: [D16820813](https://our.internmc.facebook.com/intern/diff/D16820813)

### CODE REVIEW

**Review by raghuramank100 — APPROVED** [review]
Are all quantization/quantized tests passing with this change?

**Review by z-a-f — APPROVED** [review]
LGTM

**Comment by jianyuh** [comment]
1. Should we also change https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/dynamic/modules/linear.py?

2. In the module level, we changed the data type of zero_point and scale from the Tensor to scalars, to better adapt to the graph mode. However, for returning type of zero_point and scale of observer, we make them Tensor type. Are there any general guideline for when we should make zero_point and scale Scalars, and when we should make them Tensors?

**Comment by raghuramank100** [comment]
> 1. Should we also change https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/dynamic/modules/linear.py?
> 2. In the module level, we changed the data type of zero_point and scale from the Tensor to scalars, to better adapt to the graph mode. However, for returning type of zero_point and scale of observer, we make them Tensor type. Are there any general guideline for when we should make zero_point and scale Scalars, and when we should make them Tensors?

For observers, scale and zero-point are different data types and we shouldnt be lumping them into a single tensor. Also, to prepare for per-channel quant, it is good to have scale and zero-point as individual tensors.

**Comment by jianyuh** [comment]
> > 1. Should we also change https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/dynamic/modules/linear.py?
> > 2. In the module level, we changed the data type of zero_point and scale from the Tensor to scalars, to better adapt to the graph mode. However, for returning type of zero_point and scale of observer, we make them Tensor type. Are there any general guideline for when we should make zero_point and scale Scalars, and when we should make them Tensors?
> 
> For observers, scale and zero-point are different data types and we shouldnt be lumping them into a single tensor. Also, to prepare for per-channel quant, it is good to have scale and zero-point as individual tensors.

For per-channel quant, we will make the scale and zero-point as individual tensors. Does this mean we will have scale and zero_point as the Tensors in the Linear/Conv modules with per-channel quant (Currently they are scalars)? cc @dskhudia .

**Comment by jerryzh168** [comment]
@jianyuh the reason we changed scale in q_scale() API from Tensor to float/long is because we want to remove extra wrapping and unwrapping when we call something like torch.quantize_linear(x, z.q_scale(), z.q_zero_point()), for per_channel I think all the APIs 'q_scales()', 'q_zero_points()' and 'quantize_linear_per_channel' will take Tensors, so it should be OK as long as they are consistent.

**Pull request closed without merging**
