### PR TITLE
Autodiff update for Add operator

### PR DESCRIPTION
**Pull request by jjsjann123**
Avoids extra operators being generated in simple add cases, for example bias addition.

cc @gmagogsfm

### CODE REVIEW

**Comment by albanD** [comment]
Leaving this to @eellison as this is torchscript stuff.

**Review by eellison — COMMENTED** [review]
this looks fine to me but we should really do this as a peephole optimziation... let me try to get this back on within the week

**Comment by jjsjann123** [comment]
bump for update. :bow:

**Comment by eellison** [comment]
submitting pr today  !

**Comment by eellison** [comment]
replaced by https://github.com/pytorch/pytorch/pull/65860

**Pull request closed without merging**
