### PR TITLE
Add arg layer_norm_eps to transformer layers

### LINKED ISSUE #44367: Add argument layer_norm_eps to transformer modules
## 🚀 Feature

Add argument `layer_norm_eps` to `Transformer` modules.

## Motivation

Currently `Transformer` modules initialize `LayerNorm` with default arguments (`eps=1e-5`), however different model architectures may require different eps values (e.g. BERT uses eps=1e-12). It would be better to make it an argument, so user could change it accordingly.

## Pitch

Add argument `layer_norm_eps` to `Transformer` modules, which will be passed to inner `LayerNorm` modules.

cc @zhangguanheng66

### PR DESCRIPTION
**Pull request by MagiaSN**
Fixes #44367

### CODE REVIEW

**Comment by vadimkantorov** [comment]
This is a great change! Given that for fp16 these eps often should even be larger

**Review by jbschlosser — COMMENTED** [review]
Thanks for addressing this! The changes for `TransformerEncoderLayer` and `TransformerDecoderLayer` lgtm, but could you please add the arg to the `Transformer` layer as well?

**Comment by MagiaSN** [comment]
> Thanks for addressing this! The changes for `TransformerEncoderLayer` and `TransformerDecoderLayer` lgtm, but could you please add the arg to the `Transformer` layer as well?

Oh, I checked `TransformerEncoder` and `TransformerDecoder` but missed the `Transformer` module. Thanks for your reminding. I have added the arg to `Transformer` too.

**Review by jbschlosser — APPROVED** [review]
lgtm!

**Pull request closed without merging**
