### PR TITLE
Make sure the number of MKL and OpenMP threads match

### PR DESCRIPTION
**Pull request by colesbury**
Otherwise, on many machines, the size of the OpenMP thread pool will
change between MKL and our OpenMP enabled functions. The constant thread
creation and destruction results in worse performance and leaks memory
on GCC 5.4

Here's an example program which triggers this behavior:
https://gist.github.com/colesbury/9ac92dfe5346bb71dee885af9c8cdd5d

`torch.add`/`THTensor_(cadd)` with a destination tensor is an OpenMP-enabled TH function. `torch.mm`/`THTensor_(addmm)` uses MKL. On my machine, MKL defaults to 24 threads while OpenMP defaults to 48 threads. Without this fix, the example gets about 200 itrs/sec. With the fix, the example gets about 3000 itrs/sec.

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by apaszke** [comment]
Awesome! But we're still linking both `libiomp.so` and `libgomp.so`, right? We should finally clean it up, because it can possible cause some super weird errors

**Review by apaszke — APPROVED** [review]

**Comment by apaszke** [comment]
Also, shouldn't we limit the number of threads to be lower than the number of cores? I've seen performance improve when I lowered `OMP_NUM_THREADS` to around 10 on a 40-core machine

**Comment by soumith** [comment]
we are and should only be linking to libgomp

**Comment by apaszke** [comment]
We are and should, but as far as I remember gcc is linking gomp too. Can you check the output of `ldd` on `_C.so`?

**Comment by soumith** [comment]
this is now merged into master

**Pull request closed without merging**
