### PR TITLE
Enable UFMT on `test/functorch`

### PR DESCRIPTION
**Pull request by shink**
Partially addresses #123062

Ran lintrunner on:

- `test/functorch`

cc @albanD

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Comment by zou3519** [comment]
Seems like lint is failing -- you can run lintrunner locally (`lintrunner -a`) and update the PR

**Comment by shink** [comment]
@ezyang Thanks for your suggestion, I will fix them in another pull request.

**Comment by ezyang** [comment]
If you wanna do it here that's Ok too, I have a script that can generate diffs on top of the lint changes.

**Comment by ezyang** [comment]
lintcheck.sh verified is clean

**Review by ezyang — CHANGES_REQUESTED** [review]
test failures

**Comment by ezyang** [comment]
Diff looks fine

```
index bbc929eddbb..2dcdde3ecd7 100644
--- b/test/functorch/test_aotdispatch.py
+++ a/test/functorch/test_aotdispatch.py
@@ -3069,8 +3069,8 @@ def forward(self, primals_1, primals_2, primals_3, primals_4, primals_5, primals
     copy_ = torch.ops.aten.copy_.default(primals_3, getitem_3);  primals_3 = None
     copy__1 = torch.ops.aten.copy_.default(primals_4, getitem_4);  primals_4 = None
     copy__2 = torch.ops.aten.copy_.default(primals_5, add);  primals_5 = add = None
-    return [getitem, primals_1, primals_6, getitem_1, getitem_2, getitem_3, getitem_4]""",
-        )  # noqa: B950
+    return [getitem, primals_1, primals_6, getitem_1, getitem_2, getitem_3, getitem_4]""",  # noqa: B950
+        )
 
         self.assertEqual(out_ref, out_test)
 
@@ -3089,8 +3089,8 @@ def forward(self, primals_1, primals_6, getitem_1, getitem_2, getitem_3, getitem
     getitem_5 = native_batch_norm_backward[0]
     getitem_6 = native_batch_norm_backward[1]
     getitem_7 = native_batch_norm_backward[2];  native_batch_norm_backward = None
-    return [getitem_6, getitem_7, None, None, None, getitem_5]""",
-        )  # noqa: B950
+    return [getitem_6, getitem_7, None, None, None, getitem_5]""",  # noqa: B950
+        )
 
         self.assertEqual(inp_ref.grad, inp_test.grad)
 
@@ -3561,8 +3561,8 @@ def forward(self, arg0_1):
     getitem = conditional[0];  conditional = None
     add = torch.ops.aten.add.Tensor(getitem, 3)
     add_1 = torch.ops.aten.add.Tensor(getitem, 4);  getitem = None
-    return (add, add_1)""",
-        )  # noqa: B950
+    return (add, add_1)""",  # noqa: B950
+        )
 
         self.assertExpectedInline(
             str(gm.true_graph_0.code).strip(),
@@ -3576,8 +3576,8 @@ def forward(self, arg0_1):
     false_graph_0 = self.false_graph_0
     conditional = torch.ops.higher_order.cond(False, true_graph_0, false_graph_0, [cos_1]);  true_graph_0 = false_graph_0 = cos_1 = None
     getitem = conditional[0];  conditional = None
-    return (getitem,)""",
-        )  # noqa: B950
+    return (getitem,)""",  # noqa: B950
+        )
 
         self.assertExpectedInline(
             str(gm.true_graph_0.true_graph_0.code).strip(),
@@ -3633,8 +3633,8 @@ def forward(self, arg0_1, arg1_1):
     getitem = conditional[0];  conditional = None
     add = torch.ops.aten.add.Tensor(getitem, 3)
     add_1 = torch.ops.aten.add.Tensor(getitem, 4);  getitem = None
-    return (add, add_1)""",
-        )  # noqa: B950
+    return (add, add_1)""",  # noqa: B950
+        )
         self.assertExpectedInline(
             str(gm.true_graph_0.code).strip(),
```

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
merge was botched, I fixed it

**Comment by ezyang** [comment]
rest of diff is moving around noqas

**Pull request closed without merging**
