### PR TITLE
Add torch.relu and torch.Tensor.relu docstring

### PR DESCRIPTION
**Pull request by BBuf**
Add torch.relu and torch.Tensor.relu docstring。

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Could it also mention its relation with F.relu / F.relu_? Does torch.relu_ also exist?

**Comment by BBuf** [comment]
> 
> 
> Could it also mention its relation with F.relu / F.relu_? Does torch.relu_ also exist?

ok, torch.relu_does'nt exist, i will add it。

**Comment by vadimkantorov** [comment]
Related discuss post by @albanD : https://discuss.pytorch.org/t/what-is-the-difference-between-torch-relu-torch-nn-relu-and-torch-nn-functional-relu/91101/2?u=vadimkantorov

**Comment by BBuf** [comment]
Ok, I got it. It seems that this pr is unnecessary, I will turn it off.

**Comment by BBuf** [comment]
https://discuss.pytorch.org/t/what-is-the-difference-between-torch-relu-torch-nn-relu-and-torch-nn-functional-relu/91101/2?u=vadimkantorov

**Pull request closed without merging**
