### PR TITLE
[codemod] markDynamoStrictTest batch 16

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #117218
* #117553

[codemod] markDynamoStrictTest test_public_bindings
[codemod] markDynamoStrictTest test_package
[codemod] markDynamoStrictTest test_legacy_vmap
[codemod] markDynamoStrictTest test_namedtensor
[codemod] markDynamoStrictTest test_fx
[codemod] markDynamoStrictTest test_dataloader
[codemod] markDynamoStrictTest test_content_store
[codemod] markDynamoStrictTest test_schema_check
[codemod] markDynamoStrictTest lazy/test_ts_opinfo
[codemod] markDynamoStrictTest functorch/test_vmap_registrations

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]

**Review by voznesenskym — APPROVED** [review]

**Comment by PaliC** [comment]
Temporarily reopening to revert https://github.com/pytorch/pytorch/pull/117500

**Pull request closed without merging**
