### PR TITLE
[Composable API] `replicate`: add support for DDP args

### PR DESCRIPTION
**Pull request by yhcharles**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89243
* #89222

### CODE REVIEW

**Comment by awgu** [comment]
Curious: Is there any intention to support positional arguments in the future or only keyword arguments?

**Review by zhaojuanmao — APPROVED** [review]

**Comment by yhcharles** [comment]
> Curious: Is there any intention to support positional arguments in the future or only keyword arguments?

@awgu It should not be too hard to add positional args. But using keyword arguments seems more clear when calling a function with many arguments. Do you know if there's a reason we must support positional argument in this case?

**Comment by awgu** [comment]
> > Curious: Is there any intention to support positional arguments in the future or only keyword arguments?
> 
> @awgu It should not be too hard to add positional args. But using keyword arguments seems more clear when calling a function with many arguments. Do you know if there's a reason we must support positional argument in this case?

No reason. Your thoughts make sense to me!

**Pull request closed without merging**
