### PR TITLE
Added log1p for complex in c10

### PR DESCRIPTION
**Pull request by mfkasim1**
One PR towards #89205.
The content is mostly from PR #38465, but slightly changed the expression to make it faster.

Here are some benchmarking code:
```c++
#include <complex>
#include <iostream>
#include <chrono>

// main.cc

template<typename T> inline std::complex<T> log1p_v0(const std::complex<T> &z) {
    // this PR
    T x = z.real();
    T y = z.imag();
    T theta = std::atan2(y, x + T(1));
    T r = x * (x + T(2)) + y * y;
    return {T(0.5) * std::log1p(r), theta};
}

template<typename T> inline std::complex<T> log1p_v1(const std::complex<T> &z) {
    // PR #38465
    T x = z.real();
    T y = z.imag();
    std::complex<T> p1 = z + T(1);
    T r = std::abs(p1);
    T a = std::arg(p1);
    T rm1 = (x * x + y * y + x * T(2)) / (r + 1);
    return {std::log1p(rm1), a};
}

template<typename T>
inline std::complex<T> log1p_v2(const std::complex<T> &z) {
    // naive, but numerically inaccurate
    return std::log(T(1) + z);
}

int main() {
    int n = 1000000;
    std::complex<float> res(0.0, 0.0);
    std::complex<float> input(0.5, 2.0);
    auto start = std::chrono::system_clock::now();
    for (int i = 0; i < n; i++) {
        res += log1p_v0(input);
    }
    auto end = std::chrono::system_clock::now();
    auto elapsed = end - start;
    std::cout << "time for v0: " << elapsed.count() << '\n';

    start = std::chrono::system_clock::now();
    for (int i = 0; i < n; i++) {
        res += log1p_v1(input);
    }
    end = std::chrono::system_clock::now();
    elapsed = end - start;
    std::cout << "time for v1: " << elapsed.count() << '\n';

    start = std::chrono::system_clock::now();
    for (int i = 0; i < n; i++) {
        res += log1p_v2(input);
    }
    end = std::chrono::system_clock::now();
    elapsed = end - start;
    std::cout << "time for v2: " << elapsed.count() << '\n';
    std::cout << res << '\n';
}
```

Compiling the script with command `g++ main.cc` produces the following results:
```
time for v0: 237812271
time for v1: 414524941
time for v2: 360585994
```

### CODE REVIEW

**Comment by lezcano** [comment]
As per https://github.com/pytorch/pytorch/pull/38465#issuecomment-1104445746, could you have a look at how libc++ implements this function? It's not clear to me what are the stability implications of implementing this function via the v0 or v1 implementations.

**Comment by mfkasim1** [comment]
@lezcano I couldn't find the implementation of `log1p` for complex type in llvm's [libcxx](https://github.dev/llvm/llvm-project/tree/main/libcxx/). Let me know if you can find it.
I also opened a PR for numpy's complex `log1p` [here](https://github.com/numpy/numpy/pull/22611), so the implementation can be shared.

**Comment by lezcano** [comment]
The double PyTorch/NumPy PR is great! Thank you for that. I see that https://github.com/numpy/numpy/pull/22611#issuecomment-1319049935 already provided some feedback, so it should be good to fix those firsts. Even more, this function surely has been implemented in some standard library. We should look for a battle-tested standard implementation and go with that. Perhaps @zasdfgbnm knows where to find one?

**Comment by zasdfgbnm** [comment]
I don't think std C++ support log1p for complex: https://en.cppreference.com/w/cpp/numeric/math/log1p
gcc's log1p implementation for double is here https://github.com/bminor/glibc/blob/595c22ecd8e87a27fd19270ed30fdbae9ad25426/sysdeps/ieee754/dbl-64/s_log1p.c
So if you want to be perfect in numerics, you probably want to try to understand what gcc is doing, and decide if you want to borrow their idea. (But be warned about the license of GCC, so don't copy-paste code).
But on the other hand, I am also OK with not doing so.

**Comment by ezyang** [comment]
If we are trying to do something proper instead of yoloing an implementation, we should see if we can use the approach at https://people.cs.rutgers.edu/~sn349/rlibm/

**Comment by lezcano** [comment]
@ezyang I don't think that library supports complex numbers or the `log1p` function, does it?

**Comment by ezyang** [comment]
I suppose not. And I guess this is a more difficult problem, because complex elementary functions have two inputs, meaning that you cannot simply find a polynomial that works on one input.

**Comment by lezcano** [comment]
You can, as this is an analytic function on a disk around 0. In that disk, you can approximate the function by a (complex variable) polynomial, so it's similar to the real case really.

In all fairness, if what that library is doing is to find good-enough probably-correct polynomial approximations for the cmath functions, I bet the one they're using for the logarithm is reasonably correct around 1, so we could still draw ideas from there. And if it's a polynomial, it should work in the complex case. Now, I don't know how efficient will it be.

**Comment by mfkasim1** [comment]
UPDATE based on the discussion in the numpy's issue: https://github.com/numpy/numpy/pull/22611
There are various expressions that we can use to calculate the real part of `log1p` accurately for small `|z|`.
Examples are (`z = x + iy`):

*  `0.5 * log1p(x * (2 + x) + y * y)` or
* `log1p(x) + 0.5 * log1p((y / (x + 1)) ** 2)`

By handling the overflowing or underflowing terms specially, the expression above can handle **most** `z` inputs reasonably accurately.
However, some limiting case would be when the `x < 0` and `y ~ +-sqrt(2 * |x|)`, both expressions suffer from cancellation error (similar to `1 + 1e-16 - 1 == 0`).
For example:
```python
import numpy as np

# log1p* only calculate the real part
log1p1 = lambda x: 0.5 * np.log1p(z.real * (2 + z.real) + z.imag ** 2)
log1p2 = lambda x: np.log1p(x) + 0.5 * np.log1p((y / (x + 1)) ** 2)
z = -1e-18 + np.sqrt(2 * 1e-18) * 1j
print(log1p1(z), log1p2(z))  # both are 0, while actually it should be 1e-35
```
In [scipy](https://github.com/scipy/scipy/blob/5b8490a2b80e73aec59af9ac93bca2ebd178fee1/scipy/special/_cunity.pxd#L25-L66), it is handled specially by calculating that special case in higher precision.

So there are 2 options:

1) We handle the special case by calculating it with higher precision (double double or maybe long double). This option is the best in terms of accuracy, but I don't know how hard the implementation would be.
2) We just go ahead without handling the special case, thinking the special case will be quite uncommon to face and the impact of loss precision is understandable.

**Comment by lezcano** [comment]
I'd be fine with 2. really. In PyTorch we often prioritise speed over minor precision tweaks. 
What are the precision / speed characteristics of the two possible implementations for CPU and CUDA?

**Comment by mfkasim1** [comment]
Here's my benchmark on CPU:
```c++
#include <complex>
#include <iostream>
#include <chrono>

template<typename T> inline std::complex<T> log1p_v0(const std::complex<T> &z) {
    // The first expression
    T x = z.real();
    T y = z.imag();
    T zabs = std::abs(z);
    T theta = std::atan2(y, x + T(1));
    if (zabs < 0.5) {
        T r = x * (2 + x) + y * y;
        return {T(0.5) * std::log1p(r), theta};
    }
    else {
        T z0 = std::hypot(x + 1, y);
        return {std::log(z0), theta};
    }
}

template<typename T> inline std::complex<T> log1p_v1(const std::complex<T> &z) {
    // WarrenWeckesser's code from the numpy's issue
    T x = z.real();
    T y = z.imag();
    T theta = std::atan2(y, x + T(1));

    if (std::abs(x) < T(0.5) && std::abs(y) < x + 1) {
        T yx = y / (x + 1);
        return {std::log1p(x) + T(0.5) * std::log1p(yx * yx), theta};
    }
    else {
        T z0 = std::hypot(x + 1, y);
        return {std::log(z0), theta};
    }
}

template<typename T> inline std::complex<T> log1p_v2(const std::complex<T> &z) {
    // Scipy's simplified version
    T x = z.real();
    T y = z.imag();
    T az = std::abs(z);
    T theta = std::atan2(y, x + T(1));

    if (az < 0.707) {
        return {T(0.5) * std::log1p(az * (az + 2 * x / az)), theta};
    }
    else {
        T z0 = std::hypot(x + 1, y);
        return {std::log(z0), theta};
    }
}

template<typename T> inline std::complex<T> log1p_v3(const std::complex<T> &z) {
    // naive implementation, with less precision on small numbers
    return std::log(T(1) + z);
}

int main() {
    int n = 1000000;
    std::complex<float> res(0.0, 0.0);
    // small inputs to get it to the correct calculation part
    std::complex<float> input(1e-10, 1e-10);
    auto start = std::chrono::system_clock::now();
    for (int i = 0; i < n; i++) {
        res += log1p_v0(input * std::complex<float>(1 + i));
    }
    auto end = std::chrono::system_clock::now();
    auto elapsed = end - start;
    std::cout << "time for v0: " << elapsed.count() << '\n';

    start = std::chrono::system_clock::now();
    for (int i = 0; i < n; i++) {
        res += log1p_v1(input * std::complex<float>(1 + i));
    }
    end = std::chrono::system_clock::now();
    elapsed = end - start;
    std::cout << "time for v1: " << elapsed.count() << '\n';

    start = std::chrono::system_clock::now();
    for (int i = 0; i < n; i++) {
        res += log1p_v2(input * std::complex<float>(1 + i));
    }
    end = std::chrono::system_clock::now();
    elapsed = end - start;
    std::cout << "time for v2: " << elapsed.count() << '\n';

    start = std::chrono::system_clock::now();
    for (int i = 0; i < n; i++) {
        res += log1p_v3(input * std::complex<float>(1 + i));
    }
    end = std::chrono::system_clock::now();
    elapsed = end - start;
    std::cout << "time for v3: " << elapsed.count() << '\n';

    std::cout << res << '\n';
}
```

The results are:
```
time for v0: 153569630
time for v1: 135082236
time for v2: 158133047
time for v3: 187579756
```
So **v1** (@WarrenWeckesser's expression) is actually the fastest on my CPU!

**Comment by lezcano** [comment]
Those results seem odd, given that v1 is the only one that calls `log1p` twice. Do you know what's going on there? Perhaps the results of the benchmark, given that they use the system clock, may not be representative?

**Comment by mfkasim1** [comment]
I forgot to put the optimization flag when compiling it. With `g++ main.cc -Ofast` and increased `n` to be 50 millions. Here are the new results:
```
time for v0: 1424647547
time for v1: 1994870906
time for v2: 1555418550
time for v3: 3095781824
```

**Comment by ezyang** [comment]
You're going to want to avoid double precision ops on CUDA if at all possible, because there is way less double precision hardware on NVIDIA GPUs. But OK to add a simple implementation first and optimize it more later.

**Comment by lezcano** [comment]
@mfkasim1 those numbers look more reasonable indeed. Ok, it looks like the efficiency of the 3 implementations is comparable, so I'll let it up to you to decide which one we prefer. A priori, I'd go for the most stable one of the three. As Ed mentioned, we can always update it if we find a more robust one.

**Review by lezcano — APPROVED** [review]
As discussed, we can do with this for now. If later on anyone provides a more precise implementation we can always update ti.

**Review by lezcano — COMMENTED** [review]
Edit. Wrong PR. ugh.
~~Left a few a couple comments on the testing  comments.~~

~~For the complex part, you can see how it's done for `cuda/UnaryLogKernels.cu`. You may want to do this in a follow-up PR.~~

**Pull request closed without merging**
