### PR TITLE
ao migration: remove package test as this behavior is tested by other things

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #94071
* __->__ #94422
* #94420

Summary:

We have tests testing package level migration correctness for torch AO migration.
After reading the code, I noticed that these tests are not testing anything
additional on top of the function level tests we already have.

An upcoming user warning PR will break this test, and it doesn't seem worth fixing.
As long as the function level tests pass, 100% of user functionality will
be tested.  Removing this in a separate PR to keep PRs small.

Test plan:

```
python test/test_quantization.py -k AOMigration
```

### CODE REVIEW

**Comment by jerryzh168** [comment]
can you also specify what is the error after the user warning PR?

**Review by jcaip — APPROVED** [review]
lgtm

**Comment by vkuzo** [comment]
> can you also specify what is the error after the user warning PR?

https://github.com/pytorch/pytorch/pull/94071 changes how modules in the old locations import their names.  For example,

```
// before, globals() of torch.quantization.foo module
{
   'bar': bar,
   ...
}

// after, globals() of torch.quantization.foo module
{
  'deprecated_bar': bar,  # accessed with __getattr__ override
}
```

the test removed in this diff would fail after this, and not worth fixing IMO

**Pull request closed without merging**
