### PR TITLE
Hack get_nbytes() to return 0 for sparse tensors as workaround for functionalization

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #90701
* __->__ #90702
* #90714
* #90697

### CODE REVIEW

**Comment by ezyang** [comment]
Yo check the discussion at https://github.com/pytorch/pytorch/pull/90407

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
test would be much appreciated

**Comment by ezyang** [comment]
this is indeed enough to fix dlrm on master

**Comment by jbschlosser** [comment]
> test would be much appreciated

Sure thing, on it!

**Review by bdhirsh — APPROVED** [review]

**Comment by jbschlosser** [comment]
@ezyang / @bdhirsh: added a minimal test reproducing the original issue; confirmed addressed with the fix

**Comment by ezyang** [comment]
Thanks!!

**Pull request closed without merging**
