### PR TITLE
[inductor] Run opinfo with all samples

### PR DESCRIPTION
**Pull request by voznesenskym**
Fixes #ISSUE_NUMBER

cc @mlazos @soumith @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire @jansel @lezcano @fdrocha

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by voznesenskym** [comment]
There's no way this just passed, I bet we aren't running opinfo tests...

**Pull request closed without merging**
