### PR TITLE
Wrote stubbed out test cases for isGreen function to verify if a commit SHA is promote-able

### PR DESCRIPTION
**Pull request by swang392**
Relates to #76700

**Overview:** Created a test script (`test_print_latest_commits.py`) and wrote stub tests for the future`isGreen` function. I also made a `WorkflowCheck` object to keep track of workflow conclusions in `print_latest_commits.py` which will be useful for implementing`isGreen`. 

**Test Plan:** Since `isGreen` has not been implemented yet, only the `test_match_rules` case passes and all others fail. Depending on how we plan to implement isGreen (either using the specifications from #76700 or looking at specific groups of checks in more detail), I will need to make additional test cases.

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Review by janeyx99 — COMMENTED** [review]
Before you land this, ensure you don't add these to the test suite as they'll fail on trunk (as expected). You can assert that they do fail (as expected) or since you'll be fixing these a you implement the function, you can just comment out the asserts :p

**Comment by swang392** [comment]
@pyotrchbot rebase

**Pull request closed without merging**
