### PR TITLE
[Inductor Cutlass backend] Disable epilogue fusions

### PR DESCRIPTION
**Pull request by kadeng**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #121492
* #124577
* #124576
* #124575
* #124574
* __->__ #124107
* #121734

This diff disables Cutlass backend EVT epilogue fusions. It does not yet contain the removal of most of the underlying implementation. 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
Is this ready for review?  Tests are failing and it is still marked as draft.

**Comment by kadeng** [comment]
> Is this ready for review? Tests are failing and it is still marked as draft.

It's ready now.

**Review by jansel — APPROVED** [review]

**Comment by lezcano** [comment]
just for context, why are we disabling them?

**Comment by kadeng** [comment]
> just for context, why are we disabling them?

 The short answer: Experiments resulted in the conclusion that it's not worth the effort and the issues that come with it. I posted a longer explanation in the comment section to https://github.com/pytorch/pytorch/pull/124577 - I can give more details on Slack if you want.

**Pull request closed without merging**
