### PR TITLE
[DDP Comm Hook] Re-enable the optimization of fusing copy and division when no comm hook is specified

### PR DESCRIPTION
**Pull request by wayi1**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#61379**
* #61376

The optimization was accidentally removed in https://github.com/pytorch/pytorch/pull/59574

This optimization can help save a scan over all the input parameters, by fusing copy and div operations.

Now the default temporary hook is allreduce by sum, and no extra division is done inside the hook.

Differential Revision: [D29597614](https://our.internmc.facebook.com/intern/diff/D29597614/)

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Thanks! Curious if this creates any visible performance difference on our benchmarks.

**Comment by SciPioneer** [comment]
> Thanks! Curious if this creates any visible performance difference on our benchmarks.

Didn't observe any noticeable performance difference. I guess to show the perf difference, we need to create a synthetic network architecture that only contains a few large linear layers, and let the data copy cost become more dominating.

**Comment by mcarilli** [comment]
LGTM, thanks for the quick fix!
For a simple microbenchmark, don't even bother with "linear layers", the gemms might take long enough to make the test flaky (especially because their performance would be architecture-dependent). Use the bare-minimal forward pass I wrote on slack:
```python
(model.big_param1[0] + model.big_param2[0]).sum().backward()
```

**Comment by rohan-varma** [comment]
Looks like a few tests are failing

**Pull request closed without merging**
