### PR TITLE
make range functions respect current stream

### PR DESCRIPTION
**Pull request by ngimel**
Stream is not respected on range/linspace/logspace functions, which contributes to #21589 (this is not a complete solution for that issue).

### CODE REVIEW

**Comment by ngimel** [comment]
@iotamudelta any advice on fixing
```
/var/lib/jenkins/workspace/aten/src/ATen/native/hip/RangeFactories.hip:61:35: error: no member named 'par' in namespace 'thrust::cuda'
22:30:07       auto policy = thrust::cuda::par.on(stream);
```
?
In other places (e.g. Embedding.cu) the following construct is used
```
auto policy = thrust::cuda::par(allocator).on(stream);
```
but I don't need allocator for the ranges, and thrust::cuda::par.on(stream) is valid syntax.

**Comment by iotamudelta** [comment]
@ngimel looks to me like a shortcoming of the hipified Thrust. Could this be a construct that didn't exist in Thrust some two years ago? Either way, we are working on updating things in that realm, so could you work around it via `__HIP_COMPILER_HCC__` ifdefs (either w/ allocator or serial execution, I guess) for now and leave a TODO in the code so that I can fix it once the bigger picture there is sorted out? Thanks!

**Comment by ngimel** [comment]
rocm builds were fixed by including header, caffe2_onnx failure seems unrelated. BTW, what happened to cuda 10 ci?

**Comment by ezyang** [comment]
> BTW, what happened to cuda 10 ci?

It's run on master, but not on every commit. If you like, I can make it possible to explicitly request cuda 10 CI on pull requests, if you're futzing around with CUDA 10 specific code.

**Review by ezyang — APPROVED** [review]
Very nice.

**Comment by ezyang** [comment]
I'm going to go ahead and merge this, but ideally we'd also turn back on the failing tests when we make fixes like this. (This might be hard/annoying to do.)

**Comment by ngimel** [comment]
But it does not fix the tests :-( Most of the tests fail because of backward running on the wrong stream. This is something that I noticed looking on the profile, and that has to be fixed anyway.

**Pull request closed without merging**
