### PR TITLE
[pytorch] Minor: boilerplate to propagate errors in request_callback_impl

### PR DESCRIPTION
**Pull request by jjlilley**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#32556 [pytorch] Minor: boilerplate to propagate errors in request_callback_impl**

Out of caution, avoid assuming that there's never a failure in a couple of
request_calback_impl case handlers, but rather propagate the error.

Differential Revision: [D19544685](https://our.internmc.facebook.com/intern/diff/D19544685/)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit b3efd9dc:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=b3efd9dc5eb2e42644eb9e70dfdbd5d5db2cc7fc).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4328111) pytorch_macos_10_13_py3_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=90065810) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=90065810))
<details>
<summary>
<code>Jan 23 14:51:58 RuntimeError: test_autograd failed!</code>
</summary>

```
Jan 23 14:51:58 Ran 1046 tests in 276.406s 
Jan 23 14:51:58  
Jan 23 14:51:58 FAILED (errors=1, skipped=13, expected failures=1) 
Jan 23 14:51:58  
Jan 23 14:51:58 Generating XML reports... 
Jan 23 14:51:58 Traceback (most recent call last): 
Jan 23 14:51:58   File "test/run_test.py", line 456, in <module> 
Jan 23 14:51:58     main() 
Jan 23 14:51:58   File "test/run_test.py", line 449, in main 
Jan 23 14:51:58     raise RuntimeError(message) 
Jan 23 14:51:58 RuntimeError: test_autograd failed! 
Jan 23 14:51:58 + cleanup 
Jan 23 14:51:58 + retcode=1 
Jan 23 14:51:58 + set +x 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by xush6528** [comment]
Looks a legit improvment to me.

I have a few questions coming up to better understand the situation now.

There is a test case, "test_remote_with_exception". I wonder how it works. A message with exception message type is put into future message?

And how far away that we can remove message exception type.

**Comment by jjlilley** [comment]
The test_remote_with_exception() case is testing a non-async throw, rather than async.

It's actually similar in that regard to e.g. TEST(ProcessGroupAgent, OperatorThrows) in ProcessGroupAgentTest.cpp

> And how far away that we can remove message exception type.

Not 100% sure I understand the question - but I think the intent with future<Message> is to avoid using Message::EXCEPTION, except explicitly inside the RpcAgent (when going across the machine/process boundary). For actual completed errors, I think the goal is to use this new future<> error mechanism.

The change is simply applying boilerplate that we have elsewhere to propagate an error.

**Comment by xush6528** [comment]
This codepath will be useful when OwnerRRef support setError I think.

Also, if we are to add method, `OwnerRRef::setError()`, it would be better to make OwnerRRef use torch future with a generic type value contained directly rather than use a future message to indicate the readiness of `OwnerRRef.value_` now.

**Review by xush6528 — APPROVED** [review]

**Pull request closed without merging**
