### PR TITLE
Reland "Add heirachical module names to torchFX graph.node"

### LINKED ISSUE #87659: Preserve module hierarchy information in torch.FX graph.nodes
### 🚀 The feature, motivation and pitch

The module hierarchy in PyTorch networks is saved in nn.module.named_modules().  This function provides a unique name that maps to each module object in the network.  However, when torch.fx.symbolic_trace() is run on a network, the module hierarchy is lost in the resulting torch.fx.GraphModule.    The unique module names effectively describe the network architecture.  Here's an example name from Hugging Face stable diffusion
**text_model.encoder.layers.0.self_attn.mul** . torchFX would convert this name to just **mul_1** .   From the HF example, just by looking at the module name we can tell the op is part of the encoder from the 0th layer in the self_attn block.  Whereas with the name **mul_1** we can't tell what part of the network this operator belongs to.  

In torch.fx the network graph is stored in the GraphModule.graph.nodes class.  However, the nodes are just a flat listing of all the operators in the network, they don't include any references to the modules which defined the nodes.  The PyTorch ONNX exporter was recently updated to include the module information in the operator unique names.  This feature request is proposing to do the same for torch.FX.

### Alternatives

Live with the current default node names and refer directly to the network source code to try and understand the network architecture.

### Additional context

Here's an example of what the unique operator (graph.node) names should look like.  Just by viewing the graph or the listing from graph.graph you can understand the network architecture which is much easier to work with than inspecting the network source code.

image

cc @ezyang @SherlockNoMad @soumith @EikanWang @jgong5 @wenzhe-nrv

### PR DESCRIPTION
**Pull request by alexmsettle**
Fixes #87659 

Reland of PR #87742 

Resolves errors that caused the changes to be backed out.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]
could you explain the error as well

**Comment by alexmsettle** [comment]
> could you explain the error as well

Thanks for approving @jerryzh168 .

The failing test is from [torch_XLA](https://github.com/pytorch/xla) which I was unable to build locally.  The failing test is [test_resnet18](https://github.com/pytorch/xla/blob/master/test/dynamo/test_dynamo.py#L49) and it fails at the call to [run_model_with_dynamo()](https://github.com/pytorch/xla/blob/master/test/dynamo/test_dynamo.py#L62).

Here's the error signature...
```
ERROR: test_resnet18 (__main__.DynamoBasicTest)
2022-12-03T18:38:46.4536753Z ----------------------------------------------------------------------
2022-12-03T18:38:46.4537017Z Traceback (most recent call last):
2022-12-03T18:38:46.4537360Z   File "/var/lib/jenkins/workspace/xla/test/dynamo/test_dynamo.py", line 62, in test_resnet18
2022-12-03T18:38:46.4537658Z     output = self.run_model_with_dynamo(xla_resnet18, data)
2022-12-03T18:38:46.4538100Z   File "/opt/conda/lib/python3.7/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
2022-12-03T18:38:46.4538362Z     return fn(*args, **kwargs)
2022-12-03T18:38:46.4538629Z   File "/var/lib/jenkins/workspace/xla/test/dynamo/test_dynamo.py", line 25, in run_model_with_dynamo
2022-12-03T18:38:46.4539014Z     @dynamo.optimize('torchxla_trace_once')
2022-12-03T18:38:46.4539375Z   File "/opt/conda/lib/python3.7/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
2022-12-03T18:38:46.4539689Z     return fn(*args, **kwargs)
2022-12-03T18:38:46.4540051Z   File "/opt/conda/lib/python3.7/site-packages/torch/_dynamo/optimizations/backends.py", line 754, in fwd
2022-12-03T18:38:46.4540375Z     model = subgraph.model
2022-12-03T18:38:46.4540693Z UnboundLocalError: local variable 'subgraph' referenced before assignment
```

There was a change made to [_dynamo/optimizations/backends.py](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/optimizations/backends.py#L761) just as my change was going through the merge CI process.  The [subgraph variable](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/optimizations/backends.py#L768) was declared with nonlocal scope.  I think my changes caused a path to get exercised that hadn't been tested before.  The function [fwd](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/optimizations/backends.py#L767) looks like it was called multiple times due to nesting.  The first call worked fine, but then the local variable `submodule` was deleted.  On the subsequent call, submodule was undefined.  I just moved the use of submodule into the [scope](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/optimizations/backends.py#L770) where it is actually used.

**Comment by alexmsettle** [comment]
Looks like the fix to [backends.py](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/optimizations/backends.py#L761) worked.  Going to try syncing with latest upstream.

**Comment by alexmsettle** [comment]
I see that **2ea32f41** made the same fix to backend.py that I did.  I'm going to backout my change to that file.

**Comment by seemethere** [comment]
> @pytorchbot revert -c ghfirst -m "Reverting since this caused failures in internal systems, see [fb.workplace.com/groups/802176577445480/posts/894284641568006](https://fb.workplace.com/groups/802176577445480/posts/894284641568006) for discussion"

@jerryzh168 can you help with landing this diff internally using the co-dev workflow?

**Comment by malfet** [comment]
Also, shouldn't it be considered a BC breaking, as it removes `torch.quantization.quantize_fx.Scope` symbols for example, which looks like a symbols for public API

**Comment by alexmsettle** [comment]
What was the error?  I don't think I have access to the discussion on fb.workfplace.com

**Comment by alexmsettle** [comment]
@malfet @seemethere @jerryzh168 - is there anything I can do to get this reland corrected?

**Comment by alexmsettle** [comment]
Ping @malfet @seemethere @jerryzh168 what needs to happen to get this change set re-landed?  It looks like the failing tests were internal to meta so I don't think I have access to the logs.

**Comment by jerryzh168** [comment]
I think you can submit the PR again and don't break BC, that is, make sure 'Scope' and  'ScopeContextManager' are still available in torch.fx.tracer namespace, that should be landable I think

**Pull request closed without merging**
