### PR TITLE
EmbeddingBag to handle empty bags in all modes

### PR DESCRIPTION
**Pull request by danielsimig**
Previously EmbeddingBag was not able to deal with empty bags (that is, two consecutive elements in the offsets tensor). With this change, EmbeddingBag will return an all-zero vector as the embedding if it comes across an empty bag, regardless of the mode.

### CODE REVIEW

**Comment by colesbury** [comment]
cc @cpuhrsch

**Comment by Lalaland** [comment]
This is a good idea. We really would need that GPU implementation though. Are you down for the GPU changes (I can make the GPU implementation changes if necessarily) ?

**Review by colesbury — COMMENTED** [review]
@adamlerer, you already reviewed this, right?

**Comment by danielsimig** [comment]
@colesbury the changes for max pooling have not been reviewed as those haven't been synced yet at the time.

**Comment by danielsimig** [comment]
@Lalaland I'm not familiar with how the GPU implementation works and I don't think I'll have time for it, so if you could help out that'd be fantastic!

**Review by colesbury — APPROVED** [review]

**Pull request merged**
