### PR TITLE
[distributed] remove dist.rpc, move dist.rpc calls to dist.rpc_sync/async in tests

### PR DESCRIPTION
**Pull request by rohan-varma**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#27272 [distributed] remove dist.rpc, move dist.rpc calls to dist.rpc_sync/async in tests**

It looks like some of these calls were recently added as new tests,
lets prefer to rpc_sync and rpc_async so that we don't get the warning in test
logs.

Test plan: `python test/test_rpc_spawn.py`, `python test/test_rpc_fork.py`

Differential Revision: [D17731420](https://our.internmc.facebook.com/intern/diff/D17731420/)

### CODE REVIEW

**Review by zhaojuanmao — COMMENTED** [review]
looks good, thanks!

**Comment by pietern** [comment]
Can you remove the `rpc` function itself as well?

**Review by pietern — COMMENTED** [review]
Indentation is bad at most call sites.

**Comment by rohan-varma** [comment]
@pietern , are we concerned about backwards compatibility by removing `dist.rpc`? In particular, I'm concerned about breaking some people's code if they upgrade to our nightly build and there is no `dist.rpc` function call.

**Comment by pietern** [comment]
@rohan-varma This hasn't been part of a stable release, so better to nuke it sooner rather than later.

**Comment by pietern** [comment]
Btw, I have one at #27287 as well, but that was to unblock the follow up PRs.

If you merge this first, I can rebase.

**Comment by rohan-varma** [comment]
@pietern, I've removed dist.rpc in this PR as well.

**Comment by rohan-varma** [comment]
Addressed lint issues

**Review by xush6528 — APPROVED** [review]

**Comment by rohan-varma** [comment]
Looks like the gist of this PR was covered by #25499 and the deletion of `rpc` is done in one of @pietern's diffs in the stack he mentioned. So this PR is redundant and I'll close it out.

**Pull request closed without merging**
