### PR TITLE
[BE][CMake] Use FindPython  module

### PR DESCRIPTION
**Pull request by malfet**
As FindPythonInterp and FindPythonLibs has been deprecated since cmake-3.12

Replace `PYTHON_EXECUTABLE` with `Python_EXECUTABLE` everywhere (CMake variable names are case-sensitive)

This makes PyTorch buildable with python3 binary shipped with XCode on MacOS

TODO: Get rid of `FindNumpy` as its part of Python package

### CODE REVIEW

**Comment by cyyever** [comment]
I tired before and found that some third party lib would use FindPythonInterp or FindPythonLibs before Pytorch so that the found CMake results would conflict with what FindPython3 set. It's better to enable more tests to verify that.

**Review by cyyever — APPROVED** [review]

**Review by Skylion007 — APPROVED** [review]

**Comment by cyyever** [comment]
@malfet cmake/public/cuda.cmake uses PYTHON_EXECUTABLE as well.

**Comment by malfet** [comment]
> @malfet cmake/public/cuda.cmake uses PYTHON_EXECUTABLE as well.

But previous iteration of the PR was all green, so I wonder what went wrong here...

**Comment by cyyever** [comment]
> > @malfet cmake/public/cuda.cmake uses PYTHON_EXECUTABLE as well.
> 
> But previous iteration of the PR was all green, so I wonder what went wrong here...

For the CI torchgen errors, cmake/Codegen.cmake still uses
```
 ${PYTHON_EXECUTABLE}" -m torchgen.gen
```
in line 161, which should be changes to
```
 ${Python3_EXECUTABLE}" -m torchgen.gen
```
otherwise it may call system python rather than conda one?

**Review by cyyever — APPROVED** [review]

**Comment by cyyever** [comment]
@malfet Summary.cmake printed python as "/Users/runner/work/_temp/anaconda/bin/python" which was different from the python exe that called torchgen.gen in "macos-arm64-binary-wheel / wheel-py3_9-cpu-build (push)". I think Python3_EXECUTABLE was changed by other third-party. Try to cache Python3_EXECUTABLE globally after you set it?

**Comment by malfet** [comment]
> ```
> grep -i Python_EXECUTABLE -r third_party
> ```
> 
> reveals that many third-party libraries recognize Python_EXECUTABLE only.

PyTorch does not really have a python dependencies, so this is probably fine, but come to think of it, I wonder if I should switch to `find_pacakge(Python)` rather than `find_package(Python3)`

**Comment by cyyever** [comment]
> > ```
> 
> > grep -i Python_EXECUTABLE -r third_party
> 
> > ```
> 
> > 
> 
> > reveals that many third-party libraries recognize Python_EXECUTABLE only.
> 
> 
> 
> PyTorch does not really have a python dependencies, so this is probably fine, but come to think of it, I wonder if I should switch to `find_pacakge(Python)` rather than `find_package(Python3)`
Use it if CI can become happy

**Comment by cyyever** [comment]
This time it works quite well.

**Comment by malfet** [comment]
> > Use it if CI can become happy

https://github.com/pytorch/pytorch/pull/124613/commits/a5df14d5eb8605772251aac9ab7c603939e53cbd should be green, but this `Python3_` prefix is unnecessary complication, so let's keep it as Python

**Pull request closed without merging**
