### PR TITLE
Replacing CUDA11.0 config with CUDA11.1 in CI

### PR DESCRIPTION
**Pull request by janeyx99**
Relands #46616

### CODE REVIEW

**Review by walterddr — APPROVED** [review]

**Comment by walterddr** [comment]
"ci/all" doesn't work on forks. and you are only modifying `pytorch_build_data` which doesn't require extra tag for additional ci testing IMO

**Comment by linbinyu** [comment]
looks like the new test "pytorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_build" failed.

**Comment by janeyx99** [comment]
That is true, I'll open a PR tomorrow morning to fix that

**Comment by janeyx99** [comment]
Potential fix: #48101 @linbinyu

**Comment by xwang233** [comment]
cc @malfet @zasdfgbnm @ngimel @mruberry @ezyang 

Hi @janeyx99 , thanks for adding CUDA 11.1 CI. The original cuda 11.1 CI was unlanded because MAGMA was not linked in the container. This PR doesn't have MAGMA linked either. See build log https://circleci.com/api/v1.1/project/github/pytorch/pytorch/8965643/output/106/0?file=true&allocation-id=5fb29cf0db5fba0057c63331-0-build%2FCC5B396 and you can search "MAGMA not found". 

Although the test_linalg.test_inverse is fixed in https://github.com/pytorch/pytorch/pull/47026, we still need to make sure MAGMA is linked in our cuda 11.1 container and CI. This ensures we test functionalities of basically all linear algebra operators.

**Pull request closed without merging**
