### PR TITLE
Get rid of printf in cuda fuser debugPrint()

### PR DESCRIPTION
**Pull request by malfet**

### CODE REVIEW

**Comment by ezyang** [comment]
letting nvFuser peeps take a look at this one.

**Review by csarofeen — APPROVED** [review]
LGTM

**Review by walterddr — APPROVED** [review]

**Comment by tlemo** [comment]
@malfet : the changes look fine, but can you please add a brief description explaining the rationale?

**Comment by malfet** [comment]
@tlemo , `printf("%lld")` is prone to introduce compiler warnings between Linux, Mac and Windows (where int64_t is sometimes `long int` and sometimes `long long int`
And range loops are supposed to be slightly more optimal than loops over available index (although noone cares about the performance of debugPrint function)

**Comment by walterddr** [comment]
For context: #9997 46803

**Pull request closed without merging**
