### PR TITLE
Fix vjpvmap for linalg.svdvals

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #72811
* #72677

See https://github.com/pytorch/pytorch/pull/72309/files#r803041089 for context

Differential Revision: [D34222388](https://our.internmc.facebook.com/intern/diff/D34222388)

### CODE REVIEW

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34222388).

**Review by samdow — APPROVED** [review]
Just checked that it fixes functorch locally for me. Thanks for the quick fix!

**Review by lezcano — APPROVED** [review]
ejejejejejej :D

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34222388).

**Pull request closed without merging**
