### PR TITLE
[ROCm] explicitly embed version within image name

### PR DESCRIPTION
**Pull request by jeffdaily**
This commit also removes the clang7 install for ROCm images, and properly cleans up the apt cache after ROCm installation to reduce image sizes.

Embedding the ROCm version within the image name follows the precedent set by CUDA images and decouples image creation from ROCm implicitly installing the latest version when images are prepared.

CC @sunway513 @ezyang

### CODE REVIEW

**Comment by jeffdaily** [comment]
@ezyang @seemethere as per instructions here https://github.com/pytorch/pytorch/wiki/Docker-image-build-on-CircleCI#how-to-add-a-new-base-docker-image, what should be done about the 1 failed image build?  Can I proceed with saving the new tag anyway?

**Comment by ezyang** [comment]
You need to retry the failed build until it succeeds, unfortunately.

**Comment by ezyang** [comment]
@seemethere this'll be great for your Docker building workflow improvements when they land :)

**Comment by ezyang** [comment]
This all LGTM, not approving because the cron removal is still in this PR.

**Comment by jeffdaily** [comment]
Fourth attempt at rerunning the `pytorch-linux-xenial-py3-clang5-android-ndk-r19c` build?

**Comment by jeffdaily** [comment]
@ezyang Done.  Thanks.

**Review by ezyang — APPROVED** [review]

**Review by ezyang — CHANGES_REQUESTED** [review]
You haven't updated the CI jobs to use the new image, but you've already removed the old image from the GC keep list. If we land this PR and you don't land the image version update PR within the next week, all of master will break because they will GC'ed.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
