### PR TITLE
Change python/cpp docs CI to use a CPU-only image

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#30487 Change python/cpp docs CI to use a CPU-only image**
* #30615 Update docker version to 409

Previously, the docs CI depended on our CUDA xenial py3 build. This
meant that the turnaround time to get signal for docs was very slow
(I've seen builds that go as much as 3 hours).

Fortunately, the docs CI do not (and should not!) rely on CUDA. This
PR changes it so that the docs CI runs on a CPU-only machine.

Fixes https://github.com/pytorch/pytorch/issues/29995

Test Plan:
- Check CI status on this PR by reading logs for the python and cpp docs
builds.

Differential Revision: [D18717314](https://our.internmc.facebook.com/intern/diff/D18717314)

### CODE REVIEW

**Comment by zou3519** [comment]
Some quick stats:
- Before this PR, the docs build depended on pytorch_linux_xenial_cuda9_cudnn7_py3_build, which, in the last week, has taken an average of 3300 s.
- After this PR,  the docs build depends on pytorch_linux_xenial_py3_6_gcc5_4_test, which has taken an average of 2,094 s 
- The pytorch_python_doc_push takes 1700s; the pytorch_cpp_doc_push takes 3,805s.

This means that the docs build starts 20 minutes earlier after this change. Time it takes to get a signal from the doc push:
- build pytorch + pytorch_cpp_doc_push goes down from 118min to 98min
- build pytorch + pytorch_python_doc_push goes down from 83min to 63min

**Comment by albanD** [comment]
Even though the doc build, have you checked that it does contain everything when cuda is not available?
It raises (many many) warnings when I make it with a cpu-only install but I don't know if they are relevant or not...

**Comment by zou3519** [comment]
> Even though the doc build, have you checked that it does contain everything when cuda is not available?
> It raises (many many) warnings when I make it with a cpu-only install but I don't know if they are relevant or not...

Good point. Yes, I did some checking: I built the docs using a CPU-only pytorch build `USE_CUDA=0` and then separately built them using `USE_CUDA=1`. Then I compared the output of the docs html using `diff` and checked that there was no significant difference.

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 15e11728:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=15e11728591b2cc2c35394b99ce79347fa66f225).

### :detective: 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4038952) pytorch_python_doc_push (1/1)
**Step:** "Doc Build and Push" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=78488935) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=78488935))
<details>
<summary>
<code>Dec 20 22:04:39 FileNotFoundError: [Errno 2] No such file or directory: 'katex': 'katex'</code>
</summary>

```
Dec 20 22:04:38 writing output... [ 14%] cuda_deterministic_backward 
Dec 20 22:04:38 writing output... [ 15%] cudnn_deterministic 
Dec 20 22:04:38 writing output... [ 17%] cudnn_persistent_rnn 
Dec 20 22:04:38 writing output... [ 18%] data 
Dec 20 22:04:38 writing output... [ 19%] distributed 
Dec 20 22:04:39 writing output... [ 21%] distributions 
Dec 20 22:04:39  
Dec 20 22:04:39 Exception occurred: 
Dec 20 22:04:39   File "/opt/conda/lib/python3.6/subprocess.py", line 1364, in _execute_child 
Dec 20 22:04:39     raise child_exception_type(errno_num, err_msg, err_filename) 
Dec 20 22:04:39 FileNotFoundError: [Errno 2] No such file or directory: 'katex': 'katex' 
Dec 20 22:04:39 The full traceback has been saved in /tmp/sphinx-err-p3vfz9_w.log, if you want to report the issue to the developers. 
Dec 20 22:04:39 Please also report this if it was a user error, so that a better error message can be provided next time. 
Dec 20 22:04:39 A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks! 
Dec 20 22:04:40 make: *** [html] Error 2 
Dec 20 22:04:40 Makefile:38: recipe for target 'html' failed 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by zou3519** [comment]
Subsumed by #32102

**Pull request closed without merging**
