### PR TITLE
[PyTorch] Avoid extra refcounting in vector variant of VariableType::unpack

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #95835

Looks like this line was a historical relic of Variable and Tensor not being the same. I spot checked assembly and it's not the same, which already implies this way is better; specifically there are fewer locked refcounting instructions (I believe the type of the expression is `Tensor` not `const Tensor&` and both forks must have the same type). Spotted this with at::cat in an internal workload; the actual fix is to enable InferenceMode but this should reduce the penalty for failing to do that.

Differential Revision: [D43714744](https://our.internmc.facebook.com/intern/diff/D43714744/)

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
tbh I think the whole unpack concept could be removed. The only thing it does AFAIK is to ensure we don't pass in undefined Tensors. So a function that just checks that (and doesn't return anything) will be as good and a lot less prone to perf cliffs

**Review by albanD — COMMENTED** [review]
Like this whole function is creating an owning std::vector<at::Tensor> for no reason. We could keep that as a ITensorListRef and never take owning reference to Tensor ever.

**Comment by swolchok** [comment]
> Like this whole function is creating an owning std::vectorat::Tensor for no reason. We could keep that as a ITensorListRef and never take owning reference to Tensor ever.

I have fixed the motivating issue for this PR by enabling InferenceMode; just trying to be a good citizen and contribute a simple perf fix back to PyTorch. Can we please keep the scope of this PR constant and make a review decision about whether or not to land it without regard to the potential for further improvements? I'm fine either way on the land decision.

**Review by albanD — APPROVED** [review]
Ho I didn't have that context so I was trying to offer more perf improvements on top the one you are already proposing.
But if you're not interested in more perf improvements, that's fine :D

**Pull request closed without merging**
