### PR TITLE
More informative stacklevel for autograd function warning

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #120512

Internal xref:
https://fb.workplace.com/groups/1405155842844877/posts/8064897663537295

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by Skylion007** [comment]
@ezyang FYI, there is a ruff rule to enforce these stacklevels codebase wide.

**Comment by ezyang** [comment]
@Skylion007 awesome, let's see if we can turn it on

**Pull request closed without merging**
