### PR TITLE
Fix performance regression and memory storage handling of Flash Attention on ROCM

### PR DESCRIPTION
**Pull request by xinyazhang**
This PR fixes the two major issues that was discovered after the initial merge of PR #121561 
1. The Flash Attention support added by has severe performance regressions on regular shapes (power of two head dimensions and sequence lengths) compared with PR #115981. Its performance is worse than the math backend and only has numerical stability advantages. This PR fixes this problem.
2. There is a flaw of memory storage handling in PR #121561 which does not copy the gradients back to the designated output tensor. This PR removes the deprecated `TensorStorageSanitizer` class which is unnecessary due to the more flexible backward kernel shipped by PR #121561

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@malfet @drisspg Please review this PR, it provides significant performance improvements for flash attention on ROCm. We'd like to get this landed in trunk so we can cherry-pick it for release/2.3 if possible.

**Comment by drisspg** [comment]
Can you provide some performance comparisons for this PR: https://github.com/pytorch/pytorch/blob/main/benchmarks/transformer/sdpa.py
can be used

**Review by jeffdaily — APPROVED** [review]

**Review by drisspg — APPROVED** [review]
The changes look good but some perf numbers would be great

**Comment by xinyazhang** [comment]
Performance numbers of `python benchmarks/transformer/sdpa.py` on MI300X
`torch-2.4.0a0+gite6ee832` (main branch at that point):
```
+------------+-----------+-----------+------------+-----------+-----------+----------------+--------------------+--------------------+
| batch_size | num_heads | q_seq_len | kv_seq_len | embed_dim | is_causal |     dtype      |    forward_time    |   backward_time    |
+------------+-----------+-----------+------------+-----------+-----------+----------------+--------------------+--------------------+
|     1      |    16     |    128    |    128     |   2048    |   True    | torch.bfloat16 |  42.364222696051   | 837.0399510022253  |
|     1      |    16     |    128    |    128     |   2048    |   False   | torch.bfloat16 | 40.49976068781689  |  773.007485549897  |
|     1      |    16     |    256    |    256     |   2048    |   True    | torch.bfloat16 | 245.51834247540683 | 1089.0224657487124 |
|     1      |    16     |    256    |    256     |   2048    |   False   | torch.bfloat16 | 61.26629200298339  | 976.2454789597541  |
|     1      |    16     |    512    |    512     |   2048    |   True    | torch.bfloat16 | 282.36950887367124 | 1047.927518375218  |
|     1      |    16     |    512    |    512     |   2048    |   False   | torch.bfloat16 | 97.22594299819319  |  876.149928662926  |
|     1      |    16     |   1024    |    1024    |   2048    |   True    | torch.bfloat16 | 177.6496055535972  | 2113.1785144098103 |
|     1      |    16     |   1024    |    1024    |   2048    |   False   | torch.bfloat16 | 171.66998493485153 | 1421.1283857002852 |
|     8      |    16     |    128    |    128     |   2048    |   True    | torch.bfloat16 | 62.42117844521999  | 1048.8579701632261 |
|     8      |    16     |    128    |    128     |   2048    |   False   | torch.bfloat16 | 59.91629848722368  | 816.0834398586303  |
|     8      |    16     |    256    |    256     |   2048    |   True    | torch.bfloat16 |   278.1677210005   | 1881.053679389879  |
|     8      |    16     |    256    |    256     |   2048    |   False   | torch.bfloat16 | 97.59048698469996  | 1457.135600503534  |
|     8      |    16     |    512    |    512     |   2048    |   True    | torch.bfloat16 | 396.46207704208786 | 3644.8902403935786 |
|     8      |    16     |    512    |    512     |   2048    |   False   | torch.bfloat16 | 214.72595701925457 | 2600.7521012797947 |
|     8      |    16     |   1024    |    1024    |   2048    |   True    | torch.bfloat16 |  652.808854356408  | 11339.050403330475 |
|     8      |    16     |   1024    |    1024    |   2048    |   False   | torch.bfloat16 | 634.5772207714617  |  8712.85089524463  |
+------------+-----------+-----------+------------+-----------+-----------+----------------+--------------------+--------------------+
```

`torch-2.4.0a0+git70b1a52` (After performance fix)
```
+------------+-----------+-----------+------------+-----------+-----------+----------------+--------------------+--------------------+
| batch_size | num_heads | q_seq_len | kv_seq_len | embed_dim | is_causal |     dtype      |    forward_time    |   backward_time    |
+------------+-----------+-----------+------------+-----------+-----------+----------------+--------------------+--------------------+
|     1      |    16     |    128    |    128     |   2048    |   True    | torch.bfloat16 | 24.452465656213462 | 832.6474949717522  |
|     1      |    16     |    128    |    128     |   2048    |   False   | torch.bfloat16 | 207.10051502101123 | 768.1525859516115  |
|     1      |    16     |    256    |    256     |   2048    |   True    | torch.bfloat16 | 342.67606458161026 | 1082.0403741672635 |
|     1      |    16     |    256    |    256     |   2048    |   False   | torch.bfloat16 | 31.527197104878724 | 971.6337488498539  |
|     1      |    16     |    512    |    512     |   2048    |   True    | torch.bfloat16 | 358.48227201495325 | 1038.4822695050389 |
|     1      |    16     |    512    |    512     |   2048    |   False   | torch.bfloat16 | 50.755711388774216 | 885.0791351869702  |
|     1      |    16     |   1024    |    1024    |   2048    |   True    | torch.bfloat16 | 90.77041898854077  | 2159.4962663948536 |
|     1      |    16     |   1024    |    1024    |   2048    |   False   | torch.bfloat16 | 289.5834705559537  | 1414.3597160000354 |
|     8      |    16     |    128    |    128     |   2048    |   True    | torch.bfloat16 | 36.38589383335784  | 1047.4036249797791 |
|     8      |    16     |    128    |    128     |   2048    |   False   | torch.bfloat16 | 211.41852100845426 |  814.368074061349  |
|     8      |    16     |    256    |    256     |   2048    |   True    | torch.bfloat16 | 477.9051390942186  | 1877.6362459175289 |
|     8      |    16     |    256    |    256     |   2048    |   False   | torch.bfloat16 |  56.2880844809115  | 1455.7310903910547 |
|     8      |    16     |    512    |    512     |   2048    |   True    | torch.bfloat16 |  796.927158953622  | 3652.9517197050154 |
|     8      |    16     |    512    |    512     |   2048    |   False   | torch.bfloat16 | 124.19044342823328 | 2600.094089284539  |
|     8      |    16     |   1024    |    1024    |   2048    |   True    | torch.bfloat16 | 340.7837669365108  | 11469.599744305015 |
|     8      |    16     |   1024    |    1024    |   2048    |   False   | torch.bfloat16 | 601.2811756227167  | 8721.352892462164  |
+------------+-----------+-----------+------------+-----------+-----------+----------------+--------------------+--------------------+
```

**Comment by xinyazhang** [comment]
Another set of configurations that are closer to AOTriton's `performance_forward.py`, mainly:

* Longer sequence length to match `N_CTX = 8192`
* Only `batch_size = 8`
* `bfloat16` -> `float16`
* ~~But not using `head_dim = 256`~~

Still performance numbers of python benchmarks/transformer/sdpa.py on MI300X
`torch-2.4.0a0+gite6ee832` (main branch at that point):
```
+------------+-----------+-----------+------------+-----------+-----------+---------------+--------------------+--------------------+
| batch_size | num_heads | q_seq_len | kv_seq_len | embed_dim | is_causal |     dtype     |    forward_time    |   backward_time    |
+------------+-----------+-----------+------------+-----------+-----------+---------------+--------------------+--------------------+
|     8      |    16     |   1024    |    1024    |   2048    |   True    | torch.float16 | 612.1202802751213  | 10975.284804590046 |
|     8      |    16     |   1024    |    1024    |   2048    |   False   | torch.float16 | 599.6967409737408  | 6222.694995813072  |
|     8      |    16     |   2048    |    2048    |   2048    |   True    | torch.float16 | 1890.253844903782  | 35591.05439344421  |
|     8      |    16     |   2048    |    2048    |   2048    |   False   | torch.float16 | 1952.2222154773772 | 21840.13050282374  |
|     8      |    16     |   4096    |    4096    |   2048    |   True    | torch.float16 | 6563.827500212938  | 114495.81303168088 |
|     8      |    16     |   4096    |    4096    |   2048    |   False   | torch.float16 | 7553.264801390469  | 81283.90193451196  |
|     8      |    16     |   8192    |    8192    |   2048    |   True    | torch.float16 | 18676.28715699539  | 415032.77397714555 |
|     8      |    16     |   8192    |    8192    |   2048    |   False   | torch.float16 | 28799.27259637043  | 317387.55048718303 |
+------------+-----------+-----------+------------+-----------+-----------+---------------+--------------------+--------------------+
```
`torch-2.4.0a0+git70b1a52` (After performance fix)
```
+------------+-----------+-----------+------------+-----------+-----------+---------------+--------------------+--------------------+
| batch_size | num_heads | q_seq_len | kv_seq_len | embed_dim | is_causal |     dtype     |    forward_time    |   backward_time    |
+------------+-----------+-----------+------------+-----------+-----------+---------------+--------------------+--------------------+
|     8      |    16     |   1024    |    1024    |   2048    |   True    | torch.float16 | 305.21229247096926 | 11073.366994969547 |
|     8      |    16     |   1024    |    1024    |   2048    |   False   | torch.float16 | 337.14664343278855 |  5980.15459254384  |
|     8      |    16     |   2048    |    2048    |   2048    |   True    | torch.float16 | 914.8133709095418  | 35672.29399923236  |
|     8      |    16     |   2048    |    2048    |   2048    |   False   | torch.float16 | 1103.0355654656887 | 21777.56184246391  |
|     8      |    16     |   4096    |    4096    |   2048    |   True    | torch.float16 | 3239.3840153235947 | 114393.1340193376  |
|     8      |    16     |   4096    |    4096    |   2048    |   False   | torch.float16 | 4300.096429651602  | 81064.47895988822  |
|     8      |    16     |   8192    |    8192    |   2048    |   True    | torch.float16 | 10179.031500592828 | 413690.1000747457  |
|     8      |    16     |   8192    |    8192    |   2048    |   False   | torch.float16 | 16471.315955277532 | 317446.1255548522  |
+------------+-----------+-----------+------------+-----------+-----------+---------------+--------------------+--------------------+
```

The performance is roughly doubled

**Comment by netw0rkf10w** [comment]
@xinyazhang Does this fix involve only `bfloat16`? I'm asking because your benchmark results only show `bfloat16`. Thanks!

**Comment by xinyazhang** [comment]
> @xinyazhang Does this fix involve only `bfloat16`? I'm asking because your benchmark results only show `bfloat16`. Thanks!

It fixes both float16 and bfloat16 (actually our internal benchmark script only tests `fp16`).
I did not modify `benchmarks/transformer/sdpa.py` so only bf16 is tested

**Comment by netw0rkf10w** [comment]
@xinyazhang Sorry but is this available in PyTorch 2.3.0? I understood that it was supposed to be, but trying 2.3.0 still gives me `UserWarning: 1Torch was not compiled with memory efficient attention`. Thanks a lot!

**Comment by xinyazhang** [comment]
Hi @netw0rkf10w  efficient attention is another thing. On CUDA the supported environment is a superset of FA but on ROCM it's another story.
Efficient attention is being worked on in PR https://github.com/pytorch/pytorch/pull/124885

**Pull request closed without merging**
