### PR TITLE
Remove typeid -> Half dependency

### PR DESCRIPTION
**Pull request by smessmer**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #13528 Move IdWrapper to c10/util&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D12912238/)
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#13529 Remove typeid -> Half dependency**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D12912236/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #13530 Move typeid to c10/util&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D12912240/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #13531 Fix include paths for typeid.h&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D12912237/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #13532 Move c10 dispatcher prototype to c10/&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D12912235/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #13609 Move intrusive_ptr to c10/util&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D12937090/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #13610 Fix include paths for intrusive_ptr&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D12937091/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #13533 Register caffe2 layer norm with c10 dispatcher&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D12912242/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #13488 Call c10 layer_norm from PyTorch&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D12894385/)

The diff stacked on top will move typeid to c10/util, however, I'm not ready to move Half yet (since it has a dependency on CUDA and HIP).
Because of that, I'm removing the typeid -> Half dependency in this diff to unblock.

Differential Revision: [D12912236](https://our.internmc.facebook.com/intern/diff/D12912236/)

### CODE REVIEW

**Comment by ezyang** [comment]
> I'm not ready to move Half yet (since it has a dependency on CUDA and HIP).

Not quite.

The dependency here is quite special:

```
#ifdef __CUDACC__
#include <cuda_fp16.h>
#endif

#ifdef __HIPCC__
#include <hip/hip_fp16.h>
#endif
```

These ifdefs are not toggling on "build with CUDA support" or not. What they are doing is saying, "If you compile this header with the CUDA nvcc compiler, please also include the header here." So there is no build-time dependency on CUDA; it's purely levied on any downstream user who includes this header from a 'cu' file. You should just move half instead of doing this patch.

**Review by ezyang — CHANGES_REQUESTED** [review]
Don't do this

**Comment by jerryzh168** [comment]
@smessmer FYI Half.h is moved to c10: https://github.com/pytorch/pytorch/commit/5f514a483cfba87c8caccb5ae017f888f1549918

**Comment by smessmer** [comment]
Even with Half.h now in c10, I feel like the dependency goes into the wrong direction and we should fix that.

The typeid->half.h dependency is only there because we preallocate type ids for optimization, it is not a semantic dependency. The "correct" dependency (i.e. without preallocated type ids) would be the other way round, for typeid.h to know nothing about half.h and for half.cpp to use CAFFE_KNOWN_TYPE, i.e. dependency goes from half.h to typeid.h.

In this particular example, this also causes issues even with Half.h now being in c10, because Half.h should be in c10/core, i.e. is framework specific, while typeid.h is general and not framework specific, so should be in c10/util. Dependencies should go from core to util, not the other way round.

**Comment by smessmer** [comment]
closing because of ghexport issues, will reopen new PR for this.

**Pull request closed without merging**
