### PR TITLE
[Draft] Experiment with no-init (2)

### PR DESCRIPTION
**Pull request by cbalioglu**
> This is an alternative implementation to #63601 that leverages `__torch_dispatch__` instead of modifying the dispatcher logic.

This draft PR contains an experimental implementation of a `no_init()` function that forces all parameters and buffers of a module and its sub-modules to use a meta device regardless of the requested device type. The returned module can be used for inspection purposes, but has to be materialized by calling its `materialize()` method before doing any actual work.

```python
>>> import torch
>>> m = torch.nn.utils.no_init(torch.nn.Linear, 5, 1)
>>> m.weight
Parameter containing:
tensor(..., device='meta', requires_grad=True)
>>> n = m.materialize()
>>> n.weight
Parameter containing:
tensor([[-1.4677e+24,  4.5915e-41,  1.4013e-45,  0.0000e+00, -1.4677e+24,
             4.5915e-41]], requires_grad=True)
```

Note that `no_init()` does not require any code changes on the module side.

### CODE REVIEW

**Comment by cbalioglu** [comment]
@ezyang @zou3519 is there a particular reason why we are requiring the parameter of `enable_python_model` to be a `Tensor` type? Are there no use cases where `__torch_dispatch__` can be used without a binding `Tensor` type? I am not entirely sure whether I am using it correctly, but so far I haven't had a need for a `Tensor` subtype in this draft.

**Comment by albanD** [comment]
Hi,
Is this PR for discussion only or is it an actual proposal?
In the later case, as discussed before, we do not want to add such an API in core at the moment.

**Comment by cbalioglu** [comment]
> Hi, Is this PR for discussion only or is it an actual proposal? In the later case, as discussed before, we do not want to add such an API in core at the moment.

This is only for discussion purposes based on @ezyang's feedback on the first draft. We plan to have this API as part of the distributed package (somewhere in `torch.distributed`), meaning it will be owned, maintained, and supported by PyTorch Distributed.

**Comment by zou3519** [comment]
> @ezyang @zou3519 is there a particular reason why we are requiring the parameter of `enable_python_model` to be a `Tensor` type? Are there no use cases where `__torch_dispatch__` can be used without a binding `Tensor` type? I am not entirely sure whether I am using it correctly, but so far I haven't had a need for a `Tensor` subtype in this draft.

`__torch_dispatch__` is always associated with a Tensor subclass, but I agree in this case it is weird because we never create instances of the subclass that it is associated with! You are indeed using it correctly; one thing for us to consider is to allow python_mode to work without requiring users to pass it a Tensor subclass

**Comment by cbalioglu** [comment]
> You are indeed using it correctly; one thing for us to consider is to allow python_mode to work without requiring users to pass it a Tensor subclass

Thanks for confirming @zou3519! In this case I agree that it would be nice if we could use python_mode without a Tensor subclass.

**Comment by pritamdamania87** [comment]
@cbalioglu Can we move the code changes to be an API under `torch.distributed`, we can still get feedback from the core team on those changes.

**Pull request closed without merging**
