### PR TITLE
add a pytest.ini file

### PR DESCRIPTION
**Pull request by guilhermeleobas**
This shall fix the first three items of #52984 by adding a pytest.ini configuration file.

#### `--tb=short`
In a failure, pytest will not show the entire traceback nor the docstring. 

- Without `--tb=short`:
<details>

```
$ pytest test/test_typing.py -k tensor_copy
================================================================== test session starts ===================================================================
platform linux -- Python 3.8.6, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/guilhermel/git/pytorch, configfile: pytest.ini
plugins: hypothesis-5.38.1, typeguard-2.10.0
collected 8 items / 7 deselected / 1 selected

test/test_typing.py F                                                                                                                              [100%]

======================================================================== FAILURES ========================================================================
______________________________________________________________ test_reveal[tensor_copy.py] _______________________________________________________________

path = '/home/guilhermel/git/pytorch/test/typing/reveal/tensor_copy.py', reveal = 'int '
expected_reveal = "/home/guilhermel/git/pytorch/test/typing/reveal/tensor_copy.py:11: note: Revealed type is 'torch.tensor.Tensor'", lineno = 11

    def _test_reveal(path: str, reveal: str, expected_reveal: str, lineno: int) -> None:
        if reveal not in expected_reveal:
>           raise AssertionError(_REVEAL_MSG.format(lineno, expected_reveal, reveal))
E           AssertionError: Reveal mismatch at line 11
E
E           Expected reveal: "/home/guilhermel/git/pytorch/test/typing/reveal/tensor_copy.py:11: note: Revealed type is 'torch.tensor.Tensor'"
E           Observed reveal: 'int '

test/test_typing.py:156: AssertionError
================================================================ short test summary info =================================================================
FAILED test/test_typing.py::test_reveal[tensor_copy.py] - AssertionError: Reveal mismatch at line 11
```

</details>

- With `--tb=short`:
<details>

```
$ pytest test/test_typing.py -k tensor_copy
================================================================== test session starts ===================================================================
platform linux -- Python 3.8.6, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/guilhermel/git/pytorch, configfile: pytest.ini
plugins: hypothesis-5.38.1, typeguard-2.10.0
collected 8 items / 7 deselected / 1 selected

test/test_typing.py F                                                                                                                              [100%]

======================================================================== FAILURES ========================================================================
______________________________________________________________ test_reveal[tensor_copy.py] _______________________________________________________________
test/test_typing.py:156: in _test_reveal
    raise AssertionError(_REVEAL_MSG.format(lineno, expected_reveal, reveal))
E   AssertionError: Reveal mismatch at line 11
E
E   Expected reveal: "/home/guilhermel/git/pytorch/test/typing/reveal/tensor_copy.py:11: note: Revealed type is 'torch.tensor.Tensor'"
E   Observed reveal: 'int '
```

</details>

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @guilhermeleobas. Could you add some details to the PR description to make this PR easier to understand for reviewers. E.g.:
- show a current failure without this `pytest.ini` and with it (use `<details>` foldouts)
- if possible, show changed stderr suppression behavior

Also, does the `testspaths` change mean that simply typing `pytest` in the root of the repo will be enough?

**Comment by guilhermeleobas** [comment]
> Could you add some details to the PR description to make this PR easier to understand for reviewers. 
Sure. I'll edit the first comment

> Also, does the testspaths change mean that simply typing pytest in the root of the repo will be enough?

Yes. [pytest will only look](https://docs.pytest.org/en/stable/reference.html#confval-testpaths) for tests inside the folders specified by testspaths

**Review by pmeier — COMMENTED** [review]
In addition to the comments below I have two more suggestions for the reporting:

1. The default output of `pytest` during the run is pretty minimal. I suggest we either the [`console_output_style`](https://docs.pytest.org/en/stable/reference.html#confval-console_output_style) option with `progress` or `count`. This adds a relative (`progress`) or absolute (`count`) progress info to the output. 
    In CI it might be also beneficial to see which test is currently run. This can be achieved with the `-v` / `--verbose` flag. `torchvision` does it [like this](https://github.com/pytorch/vision/blob/7d4154735f421b254c408c16e0980b1ca0dd9b8e/.circleci/unittest/linux/scripts/run_test.sh#L10).
2. It might be beneficial to get info about the slowest tests either to improve them or detect irregularities. For this I would add `--durations=25` (a good value is yet to be determined) to get a short summary at the end of the test run. This is also done in [`torchvision`](https://github.com/pytorch/vision/blob/7d4154735f421b254c408c16e0980b1ca0dd9b8e/.circleci/unittest/linux/scripts/run_test.sh#L10)

**Review by walterddr — COMMENTED** [review]
Thanks for the change @guilhermeleobas. could you add more detail on the description besides address #52984 ? 
Based on the description i think `-tb=short` addresses docstring print but it wasn't clear to me whether this addresses stderr suppress issue. 

I am also importing it to run some internal fb test since we do use pytest internally.

**Comment by guilhermeleobas** [comment]
> Thanks for the change @guilhermeleobas. could you add more detail on the description besides address #52984 ?
> Based on the description i think `-tb=short` addresses docstring print but it wasn't clear to me whether this addresses stderr suppress issue.
> 
> I am also importing it to run some internal fb test since we do use pytest internally.

Hi @walterddr, I believe the `--capture=sys` flag is the one responsible for resolving the `stderr` issue. I am having some problems to reproduce this issue locally.

**Comment by rgommers** [comment]
I had a look at the current and changed behaviour.

1. Running with unittest, `python test/test_numpy_interop.py` on master:

<details>

```
$ python test/test_numpy_interop.py 
....E.....test/test_numpy_interop.py:415: ComplexWarning: Casting complex values to real discards the imaginary part
  self.assertFalse(t == a)
.............
======================================================================
ERROR: test_numpy_array_interface_cpu (__main__.TestNumPyInteropCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rgommers/code/pytorch/torch/testing/_internal/common_device_type.py", line 287, in instantiated_test
    result = test_fn(self, *args)
  File "/home/rgommers/code/pytorch/torch/testing/_internal/common_device_type.py", line 678, in only_fn
    return fn(slf, device, *args, **kwargs)
  File "test/test_numpy_interop.py", line 283, in test_numpy_array_interface
    asarray = np.asarray(x)
  File "/home/rgommers/anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/rgommers/code/pytorch/torch/tensor.py", line 624, in __array__
    raise ValueError('testing')
ValueError: testing

----------------------------------------------------------------------
Ran 23 tests in 0.197s

FAILED (errors=1)
```

</details>

2. Running with pytest, `pytest test/test_numpy_interop.py` on master:

<details>

```
$ pytest test/test_numpy_interop.py 
============================== test session starts ===============================
platform linux -- Python 3.7.5, pytest-5.3.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/rgommers/code/pytorch
plugins: hypothesis-5.8.3
collected 23 items                                                               

test/test_numpy_interop.py ....F..................                         [100%]

==================================== FAILURES ====================================
_______________ TestNumPyInteropCPU.test_numpy_array_interface_cpu _______________

self = <test_numpy_interop.TestNumPyInteropCPU testMethod=test_numpy_array_interface_cpu>
device = 'cpu'

    @onlyCPU
    def test_numpy_array_interface(self, device):
        types = [
            torch.DoubleTensor,
            torch.FloatTensor,
            torch.HalfTensor,
            torch.LongTensor,
            torch.IntTensor,
            torch.ShortTensor,
            torch.ByteTensor,
        ]
        dtypes = [
            np.float64,
            np.float32,
            np.float16,
            np.int64,
            np.int32,
            np.int16,
            np.uint8,
        ]
        for tp, dtype in zip(types, dtypes):
            # Only concrete class can be given where "Type[number[_64Bit]]" is expected
            if np.dtype(dtype).kind == 'u':  # type: ignore[misc]
                # .type expects a XxxTensor, which have no type hints on
                # purpose, so ignore during mypy type checking
                x = torch.Tensor([1, 2, 3, 4]).type(tp)  # type: ignore
                array = np.array([1, 2, 3, 4], dtype=dtype)
            else:
                x = torch.Tensor([1, -2, 3, -4]).type(tp)  # type: ignore
                array = np.array([1, -2, 3, -4], dtype=dtype)
    
            # Test __array__ w/o dtype argument
>           asarray = np.asarray(x)

test/test_numpy_interop.py:283: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/_asarray.py:85: in asarray
    return array(a, dtype, copy=False, order=order)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = tensor([ 1., -2.,  3., -4.], dtype=torch.float64), dtype = None

    def __array__(self, dtype=None):
>       raise ValueError('testing')
E       ValueError: testing

torch/tensor.py:624: ValueError
================================ warnings summary ================================
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_complex64
  /home/rgommers/code/pytorch/test/test_numpy_interop.py:415: ComplexWarning: Casting complex values to real discards the imaginary part
    self.assertFalse(t == a)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================== 1 failed, 22 passed, 1 warning in 0.63s =====================
```

</details>

3. Running with pytest, `pytest test/test_numpy_interop.py` with this PR:

<details>

```
$ pytest test/test_numpy_interop.py 
============================== test session starts ===============================
platform linux -- Python 3.7.5, pytest-5.3.1, py-1.9.0, pluggy-0.13.1 -- /home/rgommers/anaconda3/envs/pytorch/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/rgommers/code/pytorch/.hypothesis/examples')
rootdir: /home/rgommers/code/pytorch, inifile: pytest.ini
plugins: hypothesis-5.8.3
collected 23 items                                                               

test/test_numpy_interop.py::TestNumPyInteropCPU::test_ctor_with_numpy_scalar_ctor_cpu PASSED [  4%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_from_numpy_cpu PASSED [  8%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_has_storage_numpy_cpu PASSED [ 13%]                                                                           
test/test_numpy_interop.py::TestNumPyInteropCPU::test_multiplication_numpy_scalar_cpu PASSED [ 17%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_array_interface_cpu FAILED [ 21%]                                                                       
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_index_cpu PASSED [ 26%]                                                                                 
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_non_writeable_cpu PASSED [ 30%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_bfloat16 PASSED [ 34%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_bool PASSED [ 39%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_complex128 PASSED [ 43%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_complex64 PASSED [ 47%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_float16 PASSED [ 52%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_float32 PASSED [ 56%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_float64 PASSED [ 60%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_int16 PASSED [ 65%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_int32 PASSED [ 69%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_int64 PASSED [ 73%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_int8 PASSED [ 78%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_uint8 PASSED [ 82%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_unresizable_cpu PASSED [ 86%]                                                                           
test/test_numpy_interop.py::TestNumPyInteropCPU::test_parse_numpy_int_cpu PASSED [ 91%]                                                                             
test/test_numpy_interop.py::TestNumPyInteropCPU::test_to_numpy_bool_cpu PASSED [ 95%]
test/test_numpy_interop.py::TestNumPyInteropCPU::test_to_numpy_cpu PASSED  [100%]

==================================== FAILURES ====================================
_______________ TestNumPyInteropCPU.test_numpy_array_interface_cpu _______________
test/test_numpy_interop.py:283: in test_numpy_array_interface
    asarray = np.asarray(x)
../../anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/_asarray.py:85: in asarray
    return array(a, dtype, copy=False, order=order)
torch/tensor.py:624: in __array__
    raise ValueError('testing')
E   ValueError: testing
================================ warnings summary ================================
test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_scalar_cmp_cpu_complex64
  /home/rgommers/code/pytorch/test/test_numpy_interop.py:415: ComplexWarning: Casting complex values to real discards the imaginary part
    self.assertFalse(t == a)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================ short test summary info =============================
FAILED test/test_numpy_interop.py::TestNumPyInteropCPU::test_numpy_array_interface_cpu
```

</details>

None are ideal yet. The `--tb-short` works well.

> In CI it might be also beneficial to see which test is currently run. This can be achieved with the -v / --verbose flag. 

I can't say I'm a fan of this choice. This will print one line per test, which will result in many thousands of lines printed. The current default is much more compact and imho much preferable:
```
test/test_numpy_interop.py ....F..................                         [100%]
```




> It might be beneficial to get info about the slowest tests either to improve them or detect irregularities. For this I would add `--durations=25` (a good value is yet to be determined) to get a short summary at the end of the test run

This can be very useful in CI, but not in a local run (if you run pytest on for exampe one file, it just obscures the result). Another issue is that it gets printed below the failures, so probaby should be a fairly low number (certainly no more than 25).

**Comment by mruberry** [comment]
Adding @ezyang, who agreed to be our style arbiter for what looks best.

**Comment by ezyang** [comment]
How about tb=native? The sample that was given in the original PR isn't a great example because there is only one level of stack trace. For me the real test is what happens when it's a 7-8 deep stacktrace. That's where the default style is truly, truly unreadable.

One other thing to think about: in CI, the ONNX tests use pytest, and the test logs are basically unreadable, because the tests are extremely warnings unclean and pytest thought it was a good idea to print all of the warnings AFTER the substantive test failure information. It's extra super important to make sure that in the default printing style, important information is AT THE VERY END of the tests.

**Comment by guilhermeleobas** [comment]
I've replaced `--tb=short` by `--tb=native`.

**Review by walterddr — APPROVED** [review]
ran locally for single test and it seems working fine. any additional comments on this one?

**Comment by pmeier** [comment]
Not sure if the `-v` should be there by default. Since we have quite few tests the standard output together with the summary at the end might be enough. Cc @rgommers

**Comment by rgommers** [comment]
I think both `-v` and `--durations` need to be removed here (see my comment on the latter a little higher up).

**Comment by guilhermeleobas** [comment]
@pmeier @rgommers Done!

**Pull request closed without merging**
