### PR TITLE
Make sure that little endian is default case when __BYTE_ORDER__ is not defined

### PR DESCRIPTION
**Pull request by AlekseiNikiforovIBM**
This is a follow up to discussion
in https://github.com/pytorch/pytorch/pull/96422

cc @EikanWang @jgong5

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM, but I wonder if it'll be better to do something like
```c++
#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
Do BE things
#elif __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
Do LE things
#else
#error Unexpected byteorder
#endif

**Comment by AlekseiNikiforovIBM** [comment]
I can rework it that way if you want to.

**Comment by AlekseiNikiforovIBM** [comment]
@malfet I've updated it, please check if this version is better.

**Comment by malfet** [comment]
@AlekseiNikiforovIBM thank you for the update. LGTM

**Pull request closed without merging**
