### PR TITLE
Relax dtype restrictions on torch.Tensor

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #73942
* #73874
* __->__ #73850

Previously, torch.Tensor was treated as if it were torch.FloatTensor
(where Float is whatever the default dtype was).  This is not good
behavior for tensor subclasses, which inherit from torch.Tensor and
will want to super() call into it and will only notice later that
only float works as a dtype.  So in this PR I relax the behavior
for this case to make the torch.Tensor constructor more useful for
subclasses.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D34707396](https://our.internmc.facebook.com/intern/diff/D34707396)

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
test?

**Comment by ezyang** [comment]
test added

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34707396).

**Review by albanD — APPROVED** [review]
SGTM

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34707396).

**Pull request closed without merging**
