### PR TITLE
[c10d] Add TCPSTore libuv backend support to c10d rendezvous.

### PR DESCRIPTION
**Pull request by kumpera**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108284

This enables libuv under env and tcp urls.

Under env either use the environment variable USE_LIBUV=1
or the url parameter use_lib=1.

Under tcp use the url parameter use_lib=1.

### CODE REVIEW

**Review by H-Huang — APPROVED** [review]
Looks good. An optional additional test could be to `init_process_group("nccl", ...)` or manually create store with env var  `USE_LIBUV=1` to validate that the store is using libuv

**Review by XilunWu — APPROVED** [review]
LGTM! One thing: close to @H-Huang suggested, I would like to have a test that shows the way to init pg + libuv store (i.e. `init_process_group(...)`). I guess the trick is to change the `init_method` argument. I think we can merge this PR first and I draft a PR on top to include the test.

**Pull request closed without merging**
