### PR TITLE
add packaging to the runtime requirements

### PR DESCRIPTION
**Pull request by pmeier**
Forward fix for https://github.com/pytorch/pytorch/pull/113023#issuecomment-1798272945.

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by malfet** [comment]
This is probably fine, but why not use `torch.version`?

**Comment by pmeier** [comment]
@malfet I didn't look into the original patch, but rather only provided a fix given that the other patch is good apart from the missing dependency. @vfdev-5 is `torch.version` an option?

**Comment by vfdev-5** [comment]
I have impression that `torch.version` is not sufficient as `package` is used to parse and compare version like below:
```
torch_cuda_ver = packaging.version.parse(torch.version.cuda)
if torch_cuda_ver < MIN_CUDA_VERSION:
...
```

**Comment by pmeier** [comment]
#113023 was reverted.

**Pull request closed without merging**
