### PR TITLE
[DataPipe] Fix type checking to accept both Iter and Map DataPipe

### LINKED ISSUE #841: Failing DataLoader2Integration Test
### 🐛 Describe the bug

After my [PR](https://github.com/pytorch/data/pull/827) is landed, the nightly releases become broken. See https://github.com/pytorch/data/actions/runs/3281029405

- [x] Fix the test
- [x] Investigate why the test is failing but succeeded on PR. And, the integration test is unrelated to my PR
### Versions

main branch

### PR DESCRIPTION
**Pull request by ejguan**
Fixes https://github.com/pytorch/data/issues/841

### CODE REVIEW

**Review by NivekT — APPROVED** [review]
LGTM! Thanks!

**Comment by NivekT** [comment]
This will need to be cherry-picked into core release, right?

**Comment by ejguan** [comment]
> This will need to be cherry-picked into core release, right?

I don't think so as this is just a follow-up PR for https://github.com/pytorch/pytorch/pull/87017. And, as https://github.com/pytorch/pytorch/pull/87017 is not going to be cherrypicked, this should not.

And, the CI is broken for nightly release. Our RC release is fine.

**Pull request closed without merging**
