### PR TITLE
inductor(CPU): fix issue when padding/stride/dilation size is one for cpu weight packing pass(reland)

### PR DESCRIPTION
**Pull request by XiaobingSuper**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #101353

cc @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @soumith @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

Differential Revision: [D45874469](https://our.internmc.facebook.com/intern/diff/D45874469)

### CODE REVIEW

**Comment by XiaobingSuper** [comment]
@desertfire, the internal CI seems passed, could you help land it? Thanks!

**Review by desertfire — APPROVED** [review]

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45874469).

**Pull request closed without merging**
