### PR TITLE
[ONNX] Reland #81953 Type utility for converting among JIT, torch and ONNX data types 

### PR DESCRIPTION
**Pull request by justinchuby**
Re-land #81953

Add `_type_utils` for handling data type conversion among JIT, torch and ONNX.

- Replace dictionary / list indexing with methods in ScalarType
- Breaking: **Remove ScalarType from `symbolic_helper`** and move it to `_type_utils`
- Deprecated: "cast_pytorch_to_onnx", "pytorch_name_to_type", "scalar_name_to_pytorch", "scalar_type_to_onnx", "scalar_type_to_pytorch_type" in `symbolic_helper`
- Deprecate the type mappings and lists. Remove all internal references
- Move _cast_func_template to opset 9 and remove its reference elsewhere (clean up). Added documentation for easy discovery

Why: List / dictionary indexing and lookup are error-prone and convoluted.

### CODE REVIEW

**Comment by justinchuby** [comment]
@kit1980 Can you let me know if there is any internal usages of ScalarType in symbolic_helper? If so I will need to resurrect that as well.

**Comment by kit1980** [comment]
> @kit1980 Can you let me know if there is any internal usages of ScalarType in symbolic_helper? If so I will need to resurrect that as well.

I can't find ScalarType usages.

**Comment by justinchuby** [comment]
@kit1980 this should be ready for your review

**Comment by kit1980** [comment]
@justinchuby I ran tests internally with this, LGTM.

**Review by kit1980 — APPROVED** [review]

**Comment by justinchuby** [comment]
For internal deprecations, I would make use of `torch.onnx.JitScalarType` (not `torch.onnx._type_utils.JitScalarType`) for type conversion to onnx.

**Pull request closed without merging**
