### PR TITLE
Support integer implementations for padding(cpu and cuda)

### LINKED ISSUE #107733: All padding cpu and cuda support Integers
### 🚀 The feature, motivation and pitch

related to #107412

i will work on this

### Alternatives

cast up to float then back down to integers

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by functionstackx**
Fixes #107733

cc: @cchan @ezhang887

cc: @albanD

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by albanD** [comment]
Hey!
The implementation change sounds great. The CI failures are relevant though, you need to make sure you have the right set of supported/non-supported dtypes in the opinfo specs.

**Review by albanD — APPROVED** [review]
Change is good if CI is happy

**Comment by OrenLeung** [comment]
@pytorch-bot merge

**Pull request closed without merging**
