### PR TITLE
refactor(add privateuseone floder in aten/src/ATen): add a PrivateUse…

### PR DESCRIPTION
**Pull request by ykddd**
reopen (#98127)

Add a PrivateUse1 folder to contain all the feature adaptations for PrivateUse1 under Aten,For example GetGeneratorPrivate which is used for the three-party backend to register his own Generator implementation.This makes it easier for us to centrally manage these features, and it will increase the convenience of adaptation for different back-end manufacturers. For more info: https://github.com/pytorch/pytorch/issues/98073

cc @bdhirsh

### CODE REVIEW

**Comment by albanD** [comment]
Thanks for sending this.
This is still missing some build config in https://github.com/pytorch/pytorch/blob/2a6a159c0ce96bb00d0973ab1c5db020c03a1815/buckbuild.bzl#L833

**Comment by ykddd** [comment]
@albanD  I have added it, hope this time the code can be merged smoothly with your help.Thank you~

**Comment by ykddd** [comment]
@albanD Is there any additional code modification? Please tell me, I will modify it as soon as possible~

**Comment by bdhirsh** [comment]
@ykddd sorry for the wait - I was a bit tied up the last few days. There are still some internal tests failing, I'm starting to sift through them. I'll give a shout here when I make some progress (hopefully today/tomorrow).

**Comment by bdhirsh** [comment]
For one, can you also include this change? There's another file:
```
diff --git a/caffe2/TARGETS b/caffe2/TARGETS
--- a/caffe2/TARGETS
+++ b/caffe2/TARGETS
@@ -1000,6 +1000,7 @@
     "aten/src/ATen/ops/*.h",
     "aten/src/ATen/cpu/**/*.h",
     "aten/src/ATen/nnapi/*.h",
+    "aten/src/ATen/privateuseone/*.h",
     "aten/src/ATen/quantized/*.h",
     "aten/src/ATen/vulkan/*.h",
     "aten/src/ATen/metal/*.h",
@@ -1014,6 +1015,7 @@
         "aten/src/ATen/cpu/*.cpp",
         "aten/src/ATen/functorch/**/*.cpp",
         "aten/src/ATen/nnapi/*.cpp",
+        "aten/src/ATen/privateuseone/*.cpp",
         "aten/src/ATen/quantized/*.cpp",
         "aten/src/ATen/vulkan/*.cpp",
         "aten/src/ATen/metal/*.cpp",
```

**Comment by ykddd** [comment]
@bdhirsh It doesn't matter, recently my time is mainly devoted to storage and serialization-related features, just reply me when you are free. I will be patient.
But I didn't find the file `caffe2/TARGETS` you mentioned.

**Comment by ykddd** [comment]
@bdhirsh Can you be more specific? I didn't find the file caffe2/TARGETS you mentioned.

**Comment by bdhirsh** [comment]
@ykddd that's on me - that file only exists internally, it doesn't look like it's part of OSS.

I spent a few more hours trying to get the internal builds to pass with the new folder, but I wasn't successful. Alternative plan: we can wrap the code that uses `PrivateuseoneGenerator` with ifdefs to avoid compiling it internally. I'm still working on trying to get this to work properly on an internal build though - I'll give an update once I make some progress.

**Comment by ykddd** [comment]
@bdhirsh Thanks a lot, it looks like the meta needs to provide some guidance on adding some key folders?

**Pull request closed without merging**
