### PR TITLE
[core][pruning][be] Rename sparsifier folder to pruner

### PR DESCRIPTION
**Pull request by jcaip**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #98758
* #98747

Summary:
att

Test Plan:
```
python test/test_ao_sparsity.py
```

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]

**Comment by malfet** [comment]
> @pytorchbot revert -m "https://www.internalfb.com/diff/D44905951 need to fix broken import in fbcode"

@jcaip I think `nosignal` is a wrong category here, it should be `ghfirst`. Also, PR was ladned, wasn't it? as (D44903624)[https://www.internalfb.com/diff/D44903624]

**Comment by jcaip** [comment]
Some more context for the revert: 

This PR changes some filepaths which breaks an imports in a test in fbcode. All the github CI passed, but I didn't check fbcode for signal.

**Pull request closed without merging**
