### PR TITLE
Back out "Horizontally fuse input concatenation (#108115)"

### PR DESCRIPTION
**Pull request by mlazos**
Summary:
Original commit changeset: f15956d96311

Original Phabricator Diff: D48996091

Test Plan: Reverting to Unbreak test

Differential Revision: D49065517

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by Chillee — APPROVED** [review]

**Comment by atalman** [comment]
@mlazos Looks like it breaks inductor tests
```
_________________________ AotInductorTests.test_addmm __________________________
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/opt/conda/envs/py_3.10/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '14']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/inductor/test_aot_inductor.py", line 219, in test_addmm
    actual = AOTInductorModelRunner.run(model, example_inputs, expected)
  File "/var/lib/jenkins/workspace/test/inductor/test_aot_inductor.py", line 63, in run
    optimized, exported, output_tensors, output_spec = AOTInductorModelRunner.load(
  File "/var/lib/jenkins/workspace/test/inductor/test_aot_inductor.py", line 50, in load
    optimized = torch.utils.cpp_extension.load_inline(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1635, in load_inline
    return _jit_compile(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'aot_inductor': [1/2] c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=aot_inductor -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -isystem /opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/include -isystem /opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/envs/py_3.10/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -c /var/lib/jenkins/.cache/torch_extensions/py310_cu121/aot_inductor/main.cpp -o main.o
FAILED: main.o
```

**Comment by mlazos** [comment]
> @mlazos Looks like it breaks inductor tests
> 
> ```
> _________________________ AotInductorTests.test_addmm __________________________
> Traceback (most recent call last):
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
>     subprocess.run(
>   File "/opt/conda/envs/py_3.10/lib/python3.10/subprocess.py", line 526, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '14']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/var/lib/jenkins/workspace/test/inductor/test_aot_inductor.py", line 219, in test_addmm
>     actual = AOTInductorModelRunner.run(model, example_inputs, expected)
>   File "/var/lib/jenkins/workspace/test/inductor/test_aot_inductor.py", line 63, in run
>     optimized, exported, output_tensors, output_spec = AOTInductorModelRunner.load(
>   File "/var/lib/jenkins/workspace/test/inductor/test_aot_inductor.py", line 50, in load
>     optimized = torch.utils.cpp_extension.load_inline(
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1635, in load_inline
>     return _jit_compile(
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
>     _write_ninja_file_and_build_library(
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
>     _run_ninja_build(
>   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
>     raise RuntimeError(message) from e
> RuntimeError: Error building extension 'aot_inductor': [1/2] c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=aot_inductor -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -isystem /opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/include -isystem /opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/include/TH -isystem /opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/envs/py_3.10/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -c /var/lib/jenkins/.cache/torch_extensions/py310_cu121/aot_inductor/main.cpp -o main.o
> FAILED: main.o
> ```

We force merged this for internal reasons. I'm going to reland once I can debug and that should fix the test.

**Pull request closed without merging**
