### PR TITLE
Correct "version" and "release" for document generation in case of a stable release.

### PR DESCRIPTION
**Pull request by xuhdev**
Currently the stable document has both version and release set to master. This can be often confusing (e.g., Google displays the stable document page as a "master documentation.")

Screenshot_2019-07-19_11-30-54

### CODE REVIEW

**Comment by zou3519** [comment]
I think this is going to break the version selector regex that we use to generate our stable website docs

**Comment by xuhdev** [comment]
@zou3519 I guess I should reverse the change to `version` then?

**Comment by zou3519** [comment]
> @zou3519 I guess I should reverse the change to `version` then?

We can correct the regexs, but we'll need to figure out where we're doing them

**Pull request closed without merging**
