### PR TITLE
[Profiler][Trivial] Update test_profiler_tree

### PR DESCRIPTION
**Pull request by robieta**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #79763
* __->__ #79761

Update targets file and remove redundant block

Differential Revision: [D37228315](https://our.internmc.facebook.com/intern/diff/D37228315/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D37228315/)!

### CODE REVIEW

**Comment by robieta** [comment]
@robieta has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37228315).

**Comment by robieta** [comment]
@robieta has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37279008).

**Comment by robieta** [comment]
@robieta has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37228315).

**Review by davidberard98 — APPROVED** [review]
gh1 stamp

**Pull request closed without merging**
