### PR TITLE
Make THTensor_(var) and THTensor_(std) more numerically stable

### PR DESCRIPTION
**Pull request by zou3519**
Addresses #3402 and #2470

Change the TH variance (and stdev) functions to use [Welford's algorithm](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance).

### Test Plan
`test/run_test.sh`
`test_torch` has tests for these.

### CODE REVIEW

**Comment by Atcold** [comment]
Wow, that was quick! I'm impressed!

**Comment by colesbury** [comment]
This looks great!

**Comment by colesbury** [comment]
@zou3519, do you want to do this for THC too?

**Comment by Atcold** [comment]
Same needs to be done here https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/THCTensorMathReduce.cuh#L275-L278

**Comment by ngimel** [comment]
It's slightly more annoying in parallel here https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/THCTensorMathReduce.cuh#L378 where partial sums have to be reduced across threads.

**Comment by zou3519** [comment]
I can take a look at the THC and see

**Comment by ngimel** [comment]
After the loop you are computing ```local_mean``` and ```local_m2``` you have to (in pseudo-code)
```
local_sum = local_mean * t_size
```
reduce it across threads, then compute real mean in the 0-th thread (that has reduction result). This ```mean``` variable should be ```__shared__```. Then you should adjust local means that threads have, and adjust m2
```
mean_diff = mean - local_mean
adjusted_m2 = local_m2 + mean_diff * mean_diff * t_size
```
after that reduce ```adjusted_m2``` across threads, and then ```var``` can be computed as usual.

**Comment by zou3519** [comment]
@ngimel thanks for the advice! That makes sense; it'll be helpful :)

**Pull request merged**
