### PR TITLE
[debugging] Use inductor partition_fn for aot_eager_decomp_partition

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #103632

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @msaroufim

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
okey dokey

**Review by jansel — APPROVED** [review]

**Comment by anijain2305** [comment]
For some reason, this PR raises the compilation time - https://hud.pytorch.org/benchmark/compilers?startTime=Fri%2C%2016%20Jun%202023%2017%3A45%3A39%20GMT&stopTime=Fri%2C%2023%20Jun%202023%2017%3A45%3A39%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=gh/anijain2305/60/head&lCommit=90e2b3372cc090472477d0d086697ab143249894&rBranch=main&rCommit=2d528625d7fc1db503a11ae91907d16b267bbd3a

Looking more into it.

**Pull request closed without merging**
