### PR TITLE
Check the availability of MAGMA / cuSOLVER when setting the Linalg backend.

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70253
* #69827
* __->__ #69826
* #69825

This simplifies the logic needed to handle the defaultBackend flag in linalg functions.

cc @ngimel @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

Differential Revision: [D33751984](https://our.internmc.facebook.com/intern/diff/D33751984)

### CODE REVIEW

**Review by xwang233 — APPROVED** [review]
LGTM

**Review by mruberry — APPROVED** [review]
Neat

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33202686).

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33202686).

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33202686).

**Comment by mruberry** [comment]
Holy internal failures, Batman! Here's what I'm seeing:

```
\aten\src\aten\native\batchlinearalgebra.cpp(3397): error C2039: 'tolower': is not a member of 'std'
```

this is occurring on mobile builds that likely need a stub for this call. I think @peterbell10 and @kshitij12345 have had to deal with these stub issues in the past, too.

There are also linked errors like this:

```
ld.lld: error: undefined symbol: at::native::linalg_solve_is_vector_rhs(at::Tensor const&, at::Tensor const&)

ld.lld: error: undefined symbol: at::native::_parse_qr_mode(c10::basic_string_view<char>)
```

And I'm not sure what's up with those. Looking more closely at the PR now.

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33202686).

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33202686).

**Comment by mruberry** [comment]
Unfortunately the first PR in this stack is still causing internal android failures with:

```
stderr: ld.lld: error: undefined symbol: at::native::linalg_solve_is_vector_rhs(at::Tensor const&, at::Tensor const&)
>>> referenced by FunctionsManual.cpp:491 (torch/csrc/autograd/FunctionsManual.cpp:491)
>>>  torch_mobile_trainAndroid#android-armv7,compile-picFunctionsManual.cpp.o32d20843/torch/csrc/autograd/FunctionsManual.cpp.o:(torch::autograd::generated::details::solve_jvp(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&))
>>> referenced by FunctionsManual.cpp:523 (torch/csrc/autograd/FunctionsManual.cpp:523)
>>> torch_mobile_trainAndroid#android-armv7,compile-picFunctionsManual.cpp.o32d20843/torch/csrc/autograd/FunctionsManual.cpp.o:(torch::autograd::generated::details::solve_backward_A(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&))
>>> referenced by FunctionsManual.cpp:491 (torch/csrc/autograd/FunctionsManual.cpp:491)
>>> torch_mobile_trainAndroid#android-armv7,compile-picFunctionsManual.cpp.o32d20843/torch/csrc/autograd/FunctionsManual.cpp.o:(torch::autograd::generated::details::triangular_solve_jvp(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, bool, bool))
>>> referenced 2 more times

ld.lld: error: undefined symbol: at::native::_parse_qr_mode(c10::basic_string_view<char>)
>>> referenced by FunctionsManual.cpp:2920 (torch/csrc/autograd/FunctionsManual.cpp:2920)
>>> torch_mobile_trainAndroid#android-armv7,compile-picFunctionsManual.cpp.o32d20843/torch/csrc/autograd/FunctionsManual.cpp.o:(torch::autograd::generated::details::linalg_qr_backward(std::__ndk1::vector<at::Tensor, std::__ndk1::allocator<at::Tensor> > const&, at::Tensor const&, c10::basic_string_view<char>, at::Tensor const&, at::Tensor const&))

ld.lld: error: undefined symbol: at::native::_get_epsilon(c10::ScalarType const&)
>>> referenced by FunctionsManual.cpp:3113 (torch/csrc/autograd/FunctionsManual.cpp:3113)
>>> torch_mobile_trainAndroid#android-armv7,compile-picFunctionsManual.cpp.o32d20843/torch/csrc/autograd/FunctionsManual.cpp.o:(torch::autograd::generated::details::det_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&))
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Lezcano** [comment]
@albanD @peterbell10 do you know why this could be happening? The first PR of this stack splits `LinearAlgebraUtils.h` from being a header only with a bunch of functions that are `static inline` to the normal `.h` + `.cpp` split. I added a few `TORCH_API` to some functions for the linker to find them, and it does just fine in the CI jobs, but inner mobile builds are failing.

**Comment by peterbell10** [comment]
It looks like those functions in the error message need to be marked `TORCH_API` for the mobile build because the derivative formulas which reference them are built in another shared object.

**Comment by Lezcano** [comment]
The werid thing is that two of those three functions are already marked as `TORCH_API`...

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33202686).

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33751984).

**Pull request closed without merging**
