### PR TITLE
Add type annotations for torch.nn.utils.*

### LINKED ISSUE #43013: Enable torch.nn.utils typechecks during CI
`TestTypeHints.test_run_mypy_strict` should pass with `[mypy-torch.nn.utils.*]` deleted from mypy.ini

cc @ezyang @malfet @rgommers

### PR DESCRIPTION
**Pull request by guilhermeleobas**
As title.

### CODE REVIEW

**Comment by malfet** [comment]
You PR still fails typing checks:
```
AssertionError: mypy failed: torch/nn/utils/prune.py:1182: error: Unsupported operand types for < ("float" and "Real") 
```

**Comment by guilhermeleobas** [comment]
Hi @malfet, I will tackle this later today :)

**Comment by rgommers** [comment]
Has a merge conflict now, can you rebase @guilhermeleobas?

**Comment by guilhermeleobas** [comment]
I think I made a huge mistake with `git rebase`.

**Pull request closed without merging**
