### PR TITLE
fastpath FunctionalTensor sizes()

### PR DESCRIPTION
**Pull request by bdhirsh**
Another attempt at fast-pathing sizes() in FunctionalTensor, since it appears to improve compile time perf by up to ~10%. See the investigation from https://github.com/pytorch/pytorch/issues/125977#issuecomment-2122915602.

After looking at some failing tests locally I realized that we need to manually handle metadata mutations now, since the previous "smarter" size dispatch was handling the updates

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #132084

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by bdhirsh** [comment]
also kicked off a perf run https://github.com/pytorch/pytorch/actions/workflows/inductor-perf-test-nightly.yml

**Pull request closed without merging**
