### PR TITLE
log API usage for fsdp API in PyTorch

### PR DESCRIPTION
**Pull request by zhaojuanmao**
Summary: log API usage for fsdp API in PyTorch

Test Plan: unit test

Differential Revision: D30915734

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @cbalioglu @gcramer23

### CODE REVIEW

**Review by rohan-varma — COMMENTED** [review]
Looks like this is the overall upstream, is the title correct?

**Comment by zhaojuanmao** [comment]
I did not use ghstack (did not work for me recently), so the PR includes the base diffs:(

**Review by mrshenli — COMMENTED** [review]
ghstack might be a better solution for incremental PRs :)

**Comment by zhaojuanmao** [comment]
right, but ghstack was broken when I exported the PRs:(, it was fixed now

**Pull request closed without merging**
