### PR TITLE
Avoid COW materialize in conv, log sigmoid, repeat, group_norm, batch_norm

### PR DESCRIPTION
**Pull request by kurtamohler**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #121537

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
I added the `ciflow/rocm` to provide a fuller unit test impact coverage for ROCm.

**Pull request closed without merging**
