### PR TITLE
Delete SymIntArrayRef wrapper struct

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #84837

Since we separated at::foo and at::foo_symint there is no benefit
to trying to make initializer lists work in both cases.  So we can
get rid of the special different struct.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by ZainRizvi** [comment]
@ezyang a heads up that I had to revert this PR

**Comment by ZainRizvi** [comment]
My bad,. turns out this test was flaky even before the PR was submitted. Digging deeper

**Pull request closed without merging**
