### PR TITLE
[PyTorch] Add TI::borrowing_nullary_op and use it

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #58608 [PyTorch] Rename TI::add_borrowed_{in,out}put to TI::add_{in,out}put
* #58607 [PyTorch] Add temporary guardrail to borrowing_ op variants on TensorIterator
* #58606 [PyTorch] Add TI::add_owned_{in,out}put for clarity & use them
* #58605 [PyTorch] Migrate remaining stray uses of TI:add_output to borrowing
* #58307 [PyTorch] Migrate TI usage in ATen/native/quantized to borrowing
* #58305 [PyTorch] Migrate TI usage in ATen/native to borrowing
* #58303 [PyTorch] Migrate TI usage in ATen/native/cpu to borrowing
* **#58280 [PyTorch] Add TI::borrowing_nullary_op and use it**

All core PyTorch uses of TensorIterator::nullary_op look like they can safely borrow.

Differential Revision: [D28429695](https://our.internmc.facebook.com/intern/diff/D28429695/)

### CODE REVIEW

**Review by bhosmer — APPROVED** [review]
I mean what would even be an example of a non-borrowing nullary op...

(Aside - here's a ref to #20342 so this PR shows up there)

**Comment by swolchok** [comment]
> (Aside - here's a ref to #20342 so this PR shows up there)

I'm not sure how this is related?

**Comment by swolchok** [comment]
> I mean what would even be an example of a non-borrowing nullary op...

True; given the current lack of const-correctness around nullary_op, it could safely always borrow. I'll probably revisit this when rolling out const correctness for native_functions.yaml (which I temporarily forgot about, sorry).

**Comment by bhosmer** [comment]
> > (Aside - here's a ref to #20342 so this PR shows up there)
> 
> I'm not sure how this is related?

Only that there's a comment carried forward in this code that links to that issue, noting a workaround, which is unmentioned in the issue. This ref will lead a reader of the issue here.

**Pull request closed without merging**
