### PR TITLE
Enables `where` to have cpu scalar args

### PR DESCRIPTION
**Pull request by ngimel**
This is for decompositions only, no attempt made to have good performance for this case.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
check with @eellison if fake tensor needs updates here.

**Review by eellison — APPROVED** [review]
by default we assume 0-dim cpu scalars dont contribute to output device so this should be fine. and the torchdynamo cross ref tests that (presumably) aren't failing on this PR verify this !

**Review by mruberry — APPROVED** [review]
Stamped

**Comment by mruberry** [comment]
cc @rdspring1 @IvanYashchuk, we were discussing where scalar support

**Pull request closed without merging**
