### PR TITLE
Fixing MAGMA with HIP issues

### LINKED ISSUE #55552: ROCM: After enabling Magma, 4 tests are failing in ROCM CI
## 🐛 Bug

As ROCM CI moved to ROCM 4.1, 5k new test cases from test_linalg.py got enabled.
Out of these 4 test cases are failing. These amount to 16 test cases (considering the dtypes).
Need to disable these test cases temporarily for ROCM CI to progress.

## To Reproduce

1. python3.6 test/test_linalg.py -v

## Expected behavior
The test suite should pass

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Device 6860
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 3.27.5
MIOpen runtime version: 2.11.0

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.9.0a0+gitf5675f8
[pip3] torchvision==0.9.0a0+8a2dc6f
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.2                      256  
[conda] mkl-include               2020.2                      256  
[conda] mkl-service               2.3.0            py36he8ac12f_0  
[conda] mkl_fft                   1.3.0            py36h54f3939_0  
[conda] mkl_random                1.1.1            py36h0573a6f_0  
[conda] numpy                     1.18.5           py36ha1c710e_0  
[conda] numpy-base                1.18.5           py36hde5b4d6_0  
[conda] torch                     1.9.0a0+gitc691bf2          pypi_0    pypi

## Additional context

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### PR DESCRIPTION
**Pull request by amathews-amd**
Fixes #55552

* Root-caused issue to MAGMA kernels
* Issue is fixed on master of MAGMA
MAGMA issue: https://bitbucket.org/icl/magma/issues/43/zgetrf_batched-shfl-kernel-failure-seen-on 
* Changing PyTorch to use particular commit sha from master of MAGMA project
* ~~Reactivating skipped ROCm tests~~ : We will reactivate tests in a different PR

Corresponding PyTorch builder PR: https://github.com/pytorch/builder/pull/695

### CODE REVIEW

**Comment by amathews-amd** [comment]
@jithunnair-amd @pruthvistony @jeffdaily @sunway513 - please review

**Comment by IvanYashchuk** [comment]
Hey @amathews-amd! This is great news!

We have a few more linear algebra tests defined at `torch/testing/_internal/common_methods_invocations.py` and they are run with `test/test_ops.py`. Could you also remove the `skipCUDAIfRocm` decorators from `common_methods_invocations.py` for the operations that use MAGMA?

**Comment by jithunnair-amd** [comment]
@amathews-amd: Issue with `git checkout commit` for magma repo?

**Comment by jithunnair-amd** [comment]
Just to capture here, this is the error we were seeing on ROCm CI when *not* using `LANG=C.UTF-8` for magma make command:
```
#26 617.4 Traceback (most recent call last):
#26 617.4   File "./tools/codegen.py", line 360, in <module>
#26 617.4     main()
#26 617.4   File "./tools/codegen.py", line 322, in main
#26 617.4     src = SourceFile( filename )
#26 617.4   File "./tools/codegen.py", line 171, in __init__
#26 617.4     self._text = fd.read()
#26 617.4   File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
#26 617.4     return codecs.ascii_decode(input, self.errors)[0]
#26 617.4 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 21255: ordinal not in range(128)
```

**Review by jithunnair-amd — APPROVED** [review]
LGTM if CI passes.

**Comment by jithunnair-amd** [comment]
@malfet This PR to update magma installed for ROCm builds is ready-to-merge.

**Review by janeyx99 — APPROVED** [review]
I see this is the better + finished version of https://github.com/pytorch/pytorch/pull/56806 :p 

Thank you for the change!

**Pull request closed without merging**
