### PR TITLE
[Docs] Add extended debugging options for troubleshooting

### LINKED ISSUE #120889: Provide documentation for "TORCHDYNAMO_EXTENDED_DEBUG"
### 📚 The doc issue

PyTorch torch.compile troubleshooting https://pytorch.org/docs/stable/torch.compiler_troubleshooting.html should be enhanced to add the "TORCHDYNAMO_EXTENDED_DEBUG" based flags.

### Suggest a potential alternative/fix

_No response_

cc @svekars @brycebortree @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### PR DESCRIPTION
**Pull request by spzala**
Fixes #120889

### CODE REVIEW

**Comment by spzala** [comment]
cc @ezyang - thanks!!

**Review by ezyang — APPROVED** [review]

**Comment by spzala** [comment]
Thank you @ezyang !!

**Comment by spzala** [comment]
Hello @ezyang I couldn't force merge and without it, merging is failing. So, need your help to move forward :). Thanks!!

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
For posterity, commit title has `[skip ci]` so CI is not running on the PR therefore we can't confirm that doc builds are fine https://github.com/spzala/pytorch/commit/789ddb7f47acb317fd5ef4af45c292e7090e6e55

**Comment by spzala** [comment]
> For posterity, commit title has `[skip ci]` so CI is not running on the PR therefore we can't confirm that doc builds are fine [spzala@789ddb7](https://github.com/spzala/pytorch/commit/789ddb7f47acb317fd5ef4af45c292e7090e6e55)

Sure, will keep this in mind, thanks @malfet !!

**Pull request closed without merging**
