### PR TITLE
Fix documentation for tensor.repeat.

### LINKED ISSUE #130930: For `repeat()`, `sizes` argument doesn't work while `repeats` argument works against the doc
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.Tensor.repeat.html) of `repeat()` says there is `sizes` argument as shown below:

> sizes (torch.Size or [int](https://docs.python.org/3/library/functions.html#int)...) – The number of times to repeat this tensor along each dimension

But, setting `sizes` gets the error saying there is `repeats` argument as shown below:

```python
import torch

my_tensor = torch.tensor([7, 4, 5])

my_tensor.repeat(sizes=(3, 2)) # Error
```

> TypeError: repeat() missing 1 required positional arguments: "repeats"

So,  I set `repeats` argument following the error message above, then it works as shown below:

```python
import torch

my_tensor = torch.tensor([7, 4, 5])

my_tensor.repeat(repeats=(3, 2))
# tensor([[7, 4, 5, 7, 4, 5],
#         [7, 4, 5, 7, 4, 5],
#         [7, 4, 5, 7, 4, 5]])
```

### Suggest a potential alternative/fix

So, the doc should say `repeat` instead of `sizes` and also should say `tuple` of `int` and `list` of `int` as shown below:

> repeat (torch.Size, [int](https://docs.python.org/3/library/functions.html#int)..., `tuple` of `int` or `list` of `int`) – The number of times to repeat this tensor along each dimension

### PR DESCRIPTION
**Pull request by m1guelperez**
Fixes #130930.

Adjusts the documentation which used `sizes` instead of `repeats`.

### CODE REVIEW

**Review by mikaylagawarecki — APPROVED** [review]
Thanks

**Review by soulitzer — APPROVED** [review]

**Comment by m1guelperez** [comment]
@mikaylagawarecki Sorry for pinging you but it seems like the merge timed out. Is this still going to be merged or do I have to change something in this PR?

**Pull request closed without merging**
