### PR TITLE
[sparsity] Fix and enable the pruning tests

### PR DESCRIPTION
**Pull request by z-a-f**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #66416
* #66415
* #66414
* #66413
* #66412
* __->__ #66411

The original tests were disabled, and had some bugs. This fixes those unittests.

Differential Revision: [D31590678](https://our.internmc.facebook.com/intern/diff/D31590678)

### CODE REVIEW

**Review by HDCharles — APPROVED** [review]
lgtm

**Comment by z-a-f** [comment]
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31590678).

**Comment by osalpekar** [comment]
Hi @z-a-f, it seems like PyTorch tests on trunk have been failing since this diff landed. See status here: https://hud.pytorch.org/build/pytorch-master, and tests here: https://github.com/pytorch/pytorch/runs/4293615334?check_suite_focus=true. Specifically `test_ao_sparsity` is failing after this diff. Let me know if there's a quick fix for this. If not, I'll revert this diff around ~6pm to keep master green

**Comment by z-a-f** [comment]
Fix is landing: #68794

**Pull request closed without merging**
