### PR TITLE
[dynamo][fsdp] Dont take unspecializedNNModuleVariable path for FSDP modules

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #128148
* __->__ #128453
* #129015
* #128484
* #128428

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by yf225 — APPROVED** [review]

**Comment by anijain2305** [comment]
Closing in favor of #129015

**Pull request closed without merging**
