### PR TITLE
[pt1][quant] remove quantize_linear and dequantize from Tensor method

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#20874 [pt1][quant] remove quantize_linear and dequantize from Tensor method**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D15477933/)

A criteria for what should go in Tensor method is whether numpy has it, for this one it does not
so we are removing it as a Tensor method, we can still call it as function.
Python
```
torch.quantize_linear(t, ...), torch.dequantize(t)
```
C++
```
at::quantize_linear(t, ...), at::dequantize(t)
```

Differential Revision: [D15477933](https://our.internmc.facebook.com/intern/diff/D15477933/)

### CODE REVIEW

**Comment by vadimkantorov** [comment]
NumPy doesn't have many instance methods like `tensor.log()` and `tensor.sin()`. Does it suggest these instance methods should also be removed from PyTorch? NumPy API was designed a long time ago, PyTorch can afford to be more fluent (especially for newer ops like quantization that don't exist in NumPy anyway).

**Comment by jerryzh168** [comment]
@gchanan suggested this change, could you respond?

**Comment by gchanan** [comment]
It was just to defer a couple of decisions.  It seems fine to have a single quantized creation method on tensor, but having 10 doesn't seem great.  If you have 10 functions, you might want to put them in a namespace, but you can't have a namespace on methods.

So, when we get to the point where we are convinced there is a single "quantize" method on tensor, that seems fine, but we aren't there yet.

**Review by dzhulgakov — CHANGES_REQUESTED** [review]
Looks like you need to fix some python tests as well (test_quantized)

**Comment by jerryzh168** [comment]
Should we keep dequantize?

**Review by dzhulgakov — APPROVED** [review]

**Comment by dzhulgakov** [comment]
Looks like it broke master: https://circleci.com/gh/pytorch/pytorch/1845368?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

```
May 30 05:21:16 Traceback (most recent call last):
May 30 05:21:16   File "test_quantized.py", line 234, in test_max_pool2d
May 30 05:21:16     min_side=1, max_side=10)),
May 30 05:21:16   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 1023, in wrapped_test
May 30 05:21:16     raise the_error_hypothesis_found
May 30 05:21:16   File "test_quantized.py", line 259, in test_max_pool2d
May 30 05:21:16     qa = a.quantize_linear(scale=scale, zero_point=zero_point,
May 30 05:21:16 AttributeError: 'Tensor' object has no attribute 'quantize_linear'
```

**Pull request closed without merging**
