### PR TITLE
ProcessGroupWrapper log full rank fingerprint mismatches

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #79901

### Current Error Message:
```
Detected mismatch between collectives on ranks. Rank 0 is running collective:
CollectiveFingerPrint(OpType=ALLREDUCE, …), but Rank 1 is running collective: REDUCE.
```

### Ops Mismatch, New Error Message (shows full fingerprint, includes tensor shape, data types, and device types):
```
Detected mismatch between collectives on ranks. Rank 0 is running collective:
CollectiveFingerPrint(OpType=ALLREDUCE, TensorShape=[20, 10], TensorDtypes=Float,
TensorDeviceTypes=TensorOptions(dtype=float (default), device=cpu,
layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))),

but Rank 1 is running collective:
CollectiveFingerPrint(OpType=REDUCE, TensorShape=[20, 10], TensorDtypes=Float,
TensorDeviceTypes=TensorOptions(dtype=float (default), device=cpu,
layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))).
```

### Shape Mismatch, New Error Message
```
RuntimeError: Detected mismatch between collectives on ranks. Rank 0 is running collective: 
CollectiveFingerPrint(OpType=SCATTER, TensorShape=[1], TensorDtypes=Long, 
TensorDeviceTypes=TensorOptions(dtype=float (default), device=cuda, layout=Strided (default), requires_grad=false 
(default), pinned_memory=false (default), memory_format=(nullopt))), 

but Rank 1 is running collective: 
CollectiveFingerPrint(OpType=SCATTER, TensorShape=[2], TensorDtypes=Long, 
TensorDeviceTypes=TensorOptions(dtype=float (default), device=cuda, layout=Strided (default), requires_grad=false 
(default), pinned_memory=false (default), memory_format=(nullopt))).

```

Changes:
- Update deserialize function to read shape of tensors

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
LGTM! Can we also check what error is logged when the collective name is the same but shapes are mismatched? 

Also, might be good to add / update unittests in test_pg_wrapper.py.

**Comment by H-Huang** [comment]
Add task to update pg_wrapper unit test #80372

**Pull request closed without merging**
