### PR TITLE
[Reland] [PT2] [Quant] Change the QConv2d Binary post op name from add to sum

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #115809
* #115153
* #115613
* __->__ #116172

**Summary**
Re-land https://github.com/pytorch/pytorch/pull/115329. Open a new PR since the origin branch has been deleted.
Change the QConv2d Binary fusion post op name from `add` to `sum`, since we are actually using OneDNN `post op sum` instead of `Binary_Add` for now.

**TestPlan**
```
python -m pytest test_quantized_op.py -k test_qconv2d_sum_pt2e
python -m pytest test_quantized_op.py -k test_qconv2d_sum_relu_pt2e
python -m pytest test_quantized_op.py -k test_qconv2d_sum_relu_float_output_pt2e
```

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by leslie-fang-intel** [comment]
Per the discussion https://github.com/pytorch/pytorch/pull/115329#issuecomment-1863673402, @jeanschmidt could you help to double confirm the internal build failure is caused by this diff? If so, how can I reproduce to debug.

**Comment by kit1980** [comment]
@leslie-fang-intel I think the PR was reverted by mistake. Feel free to re-land.

**Review by kit1980 — APPROVED** [review]
Approving as this is a re-land of what seems to be reverted by mistake.

**Comment by leslie-fang-intel** [comment]
Hi @kit1980, thanks for the feedback. I will re-land it now.

**Pull request closed without merging**
