### PR TITLE
Add pretty printing summaries to torch for lldb debugging

### PR DESCRIPTION
**Pull request by drisspg**
# Summary
Add support for pretty printing of tensors when using lldb similiar to what is currently available for gdb

Screenshot 2023-03-18 at 6 20 34 PM

Screenshot 2023-03-18 at 6 20 43 PM

I changed it so to override the variable formatting instead of having to call a seperate command you can just do `print <tensor>`

I also add one for sizes
Screenshot 2023-03-19 at 1 05 49 PM

Last one:
Screenshot 2023-03-19 at 1 39 23 PM

If you use the codelldb extension be sure to add:
    `"lldb.launch.initCommands": ["command source ${env:HOME}/.lldbinit"]`
    To your setttings .json

cc @jbschlosser

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by drisspg** [comment]
@pytorch merge

**Comment by drisspg** [comment]
Okay.. so this works perfect locally but is failing horrible on the cluster .. hmmm

**Pull request closed without merging**
