### PR TITLE
Default meta device to use swap_tensors in nn.Module._apply  (.to_empty and .to('meta'))

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #126984
* #126788
* __->__ #126819
* #126814
* #127313

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM!
Should we mark this BC-breaking just so that we can nicely document it in the release notes?

**Comment by izaitsevfb** [comment]
Fails internal test, see [D58015039](https://www.internalfb.com/diff/D58015039)

**Pull request closed without merging**
