### PR TITLE
[test_nn] split parametrization test from test_nn

### PR DESCRIPTION
**Pull request by kshitij12345**
Ref: https://github.com/pytorch/pytorch/issues/63085

Note: Doesn't need corresponding XLA PR as the migrated tests were not run on XLA (as they weren't in TestNNDeviceType).

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Sounds good!

**Comment by kshitij12345** [comment]
FYI, I am adding the `skip-pr-sanity-checks` label

**Pull request closed without merging**
