### PR TITLE
add channels last support for AvgPool2d on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #55864 enable BFloat16 mkldnn_convolution on both contiguous and channels last memory format
* #55584 add channels last (2d) support for mkldnn_convolution
* #51185 add channels last support for ConvTranspose2d
* #50573 add channels last support for PixelShuffle and PixelUnshuffle
* #50247 add channels last support for ChannelShuffle
* #49984 add channel last support for MaxUnpool2d
* #49821 add channels last for GroupNorm
* #49582 add channels last support for thnn_conv2d (non-dilated)
* #48920 add channels last for AdapativeMaxPool2d
* #48919 optimize channels last for BatchNorm2d on CPU
* **#48918 add channels last support for AvgPool2d on CPU**

enable test case on AvgPool2d channels last for CPU

Differential Revision: [D25399466](https://our.internmc.facebook.com/intern/diff/D25399466)

### CODE REVIEW

**Comment by mingfeima** [comment]
use this one to replace #47490

This patch adds channels last support for nn.AvgPool2d for CPU.
For channels last memory format, vectorization is done on dimension of C.

On Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz, 2*20 cores, comparing CL v.s. contiguous:

* single core inference (BS=1): 6.7x speedup
* single socket inference (BS=1): 3.7x speedup
* single socket inference (BS=128): 2.5x speedup

```bash
(before)
### single core inference
AvgPool2d(contiguous): input_size [1, 64, 112, 112] time: 2.100 ms

### single socket inference
AvgPool2d(contiguous): input_size [1, 64, 112, 112] time: 0.132 ms
AvgPool2d(contiguous): input_size [128, 64, 112, 112] time: 16.533 ms

(after)
### single core inference
AvgPool2d(contiguous): input_size [1, 64, 112, 112] time: 2.032 ms
AvgPool2d(channels_last): input_size [1, 64, 112, 112] time: 0.304 ms

### single socket inference
AvgPool2d(contiguous): input_size [1, 64, 112, 112] time: 0.119 ms
AvgPool2d(channels_last): input_size [1, 64, 112, 112] time: 0.032 ms
AvgPool2d(contiguous): input_size [128, 64, 112, 112] time: 14.420 ms
AvgPool2d(channels_last): input_size [128, 64, 112, 112] time: 5.784 ms
```

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by mingfeima** [comment]
update AVX2 CPU performance:
* **avx2 CPU**: Xeon(R) CPU E5-2680 v3 @ 2.50GHz, dual sockets, 12 cores per socket. Codename **Haswell**, [spec](https://ark.intel.com/content/www/us/en/ark/products/81908/intel-xeon-processor-e5-2680-v3-30m-cache-2-50-ghz.html)

```bash
(before)
### using OMP_NUM_THREADS=1
AvgPool2d(contiguous): input_size [1, 64, 112, 112] time: 3.062 ms
AvgPool2d(channels_last): input_size [1, 64, 112, 112] time: 4.573 ms


### using OMP_NUM_THREADS=12
AvgPool2d(contiguous): input_size [1, 64, 112, 112] time: 0.404 ms
AvgPool2d(channels_last): input_size [1, 64, 112, 112] time: 0.562 ms
AvgPool2d(contiguous): input_size [128, 64, 112, 112] time: 40.329 ms
AvgPool2d(channels_last): input_size [128, 64, 112, 112] time: 80.110 ms

(after)
### using OMP_NUM_THREADS=1
AvgPool2d(contiguous): input_size [1, 64, 112, 112] time: 3.025 ms
AvgPool2d(channels_last): input_size [1, 64, 112, 112] time: 0.466 ms

### using OMP_NUM_THREADS=12
AvgPool2d(contiguous): input_size [1, 64, 112, 112] time: 0.359 ms
AvgPool2d(channels_last): input_size [1, 64, 112, 112] time: 0.070 ms
AvgPool2d(contiguous): input_size [128, 64, 112, 112] time: 36.953 ms
AvgPool2d(channels_last): input_size [128, 64, 112, 112] time: 7.207 ms
```

**Comment by VitalyFedyunin** [comment]
Please rebase and add `ci/all` tag to all PRs. Don't forget to modify blaze files if new .cpp was introduced.

**Comment by mingfeima** [comment]
@VitalyFedyunin Updated!

**Comment by VitalyFedyunin** [comment]
Fails internal tests here:
```cpp
      AT_DISPATCH_FLOATING_TYPES_AND(at::ScalarType::Long, input.scalar_type(), "max_pool2d", [&] {
        cpu_avg_pool<scalar_t>(output, input, kW, kH, dW, dH, padW, padH, count_include_pad, divisor_override);
      });

```

With 

```
terminate called after throwing an instance of 'c10::Error'
  what():  dtype 'Float' not selected for kernel tag "max_pool2d" ()
Exception raised from operator() at ... /aten/src/ATen/native/cpu/AvgPoolKernel.cpp:371 (most recent call first):
```

**Comment by mingfeima** [comment]
Updated! The old kernel name tag is wrong.

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D25399466).

**Comment by VitalyFedyunin** [comment]
Same failure but with 
`C++ exception with description "dtype 'Float' not selected for kernel tag "avg_pool2d_channels_last"`

**Comment by VitalyFedyunin** [comment]
I have to revert last 2 PRs. Please do not abandon this stack, just do one PR for AvgPool2d separately.

**Comment by mingfeima** [comment]
> Same failure but with
> `C++ exception with description "dtype 'Float' not selected for kernel tag "avg_pool2d_channels_last"`

Working on this, will fix it ASAP!
I am kind of lost this time, I knew that the `AT_DISPATCH_XXX` requires kernel name tag to be unique so that it can be traced.
What else am I missing here? Could you please give some advice? @VitalyFedyunin

**Pull request closed without merging**
