### PR TITLE
Expose some APIs in FunctionsManual.h

### PR DESCRIPTION
**Pull request by Bin1024**
Fixes #ISSUE_NUMBER
Exporse some api in FunctionsManual.h for custom devices. This can be used in codegen features.

### CODE REVIEW

**Comment by Bin1024** [comment]
Hi @albanD . Sorry to bother you. Please review this PR for a moment.

**Review by albanD — APPROVED** [review]
Sure

**Comment by Bin1024** [comment]
@pytorchbot merge -i
These look very much unrelated.

**Pull request closed without merging**
