### PR TITLE
[aarch64] add CUDA 12.6 sbsa nightly binary

### PR DESCRIPTION
**Pull request by tinglvv**
related to #138440 

cc @atalman @Aidyn-A @nWEIdia @ptrblck

### CODE REVIEW

**Review by atalman — APPROVED** [review]
lgtm

**Comment by tinglvv** [comment]
Tested the artifact (3.10 on ubuntu:22.04) with stable diffusion test, result
```
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [00:00<00:00, 11.30it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 30.41it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 30.60it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 36.44it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 36.38it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 36.68it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 36.42it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 36.76it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 36.59it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 36.24it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 36.48it/s]
Time taken:  15.213680028915405
```

**Pull request closed without merging**
