### PR TITLE
Adjust schemas of a couple prims

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #82821

For context: https://github.com/pytorch/pytorch/issues/82763

I spent a bit of time trying to get a test working here but it's kind of tricky because some primtorch refs correspond to multiple schemas. I think ultimately what we want is something like the [backwards compatibiliity](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/function_schema_inl.h#L187) check but with checking the prim signatures against aten signatures. 

These signatures compatibility should also be tested through FakeTensors, although the `nan_to_num` bug was not tested because of https://github.com/pytorch/pytorch/issues/82785.

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
For bonus points, add sample inputs with positional args? Edit: nm, if it doesn't work that's fine

**Review by voznesenskym — APPROVED** [review]
Looks great, ty for doing this.

**Pull request closed without merging**
