### PR TITLE
Follow up to adaptive_max_pool2d() port

### PR DESCRIPTION
**Pull request by skrah**
This is a follow up PR for #19409.

### CODE REVIEW

**Comment by skrah** [comment]
A more condensed version of dispatching is possible (like in `FractionalMaxPool2d.cpp`), but changing too much makes reviewing harder.

**Comment by skrah** [comment]
@xmnlab I know you are busy, but it would be great if you can review when you have time.

**Comment by xmnlab** [comment]
@skrah sure! I will review that now :)

**Review by xmnlab — APPROVED** [review]
LGTM! thanks @skrah !

I have just one question related to the function naming, you use `adaptive_max_pool2d_single_out_frame`

the only file I found that uses `single` for the function name uses `fractional_max_pool2d_out_single_batch_frame`

but other file uses `reflection_pad1d_out_loop`

I am curious about if there is one standard for naming here.

**Comment by skrah** [comment]
Thanks @xmnlab!  I don't know if there is a naming convention, but indeed `FractionalMaxPool2d.cpp`was my inspiration.  I like the "single", and "frame" was already part of the function name before.

**Comment by skrah** [comment]
@ezyang I think this one should be ready now for your review, thanks!

**Comment by xmnlab** [comment]
@ezyang could you review this PR?

**Comment by xmnlab** [comment]
oh @skrah sorry .. I didn't see you have already mentioned `ezyang` :)

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
