### PR TITLE
[ROCm] Enable test_ddp_profiling_torch_profiler

### PR DESCRIPTION
**Pull request by jaglinux**
Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>

### CODE REVIEW

**Comment by jaglinux** [comment]
This test is running fine on ROCm 5.2  "2 gpu" system, when run in loop.
Need to close the github issue https://github.com/pytorch/pytorch/issues/68222 to activate testing on ROCm trunk.
cc @jithunnair-amd @pruthvistony

**Review by ngimel — APPROVED** [review]

**Comment by jaglinux** [comment]
Good to merge

2022-08-03T21:56:04.8976288Z   test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithSpawn) ... INFO:torch.testing._internal.common_distributed:Started process 0 with pid 94406
2022-08-03T21:56:04.9046507Z INFO:torch.testing._internal.common_distributed:Started process 1 with pid 94407
2022-08-03T21:56:04.9047944Z [W Module.cpp:744] Warning: cuDNN Benchmark limit is not supported in MIOpen and will have no effect. (function operator())
2022-08-03T21:56:06.6942854Z INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
2022-08-03T21:56:06.7420626Z INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 1
2022-08-03T21:56:06.7422688Z INFO:torch.distributed.distributed_c10d:Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
2022-08-03T21:56:06.7449812Z INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
2022-08-03T21:56:06.7455096Z INFO:torch.testing._internal.common_distributed:Starting event listener thread for rank 0
2022-08-03T21:56:06.8433329Z INFO:torch.testing._internal.common_distributed:Starting event listener thread for rank 1
2022-08-03T21:56:07.0264358Z INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmp6lcd1iyg
2022-08-03T21:56:07.0266759Z INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmp6lcd1iyg/_remote_module_non_scriptable.py
2022-08-03T21:56:07.0880666Z libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
2022-08-03T21:56:07.1300713Z INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpkqpksfoa
2022-08-03T21:56:07.1302234Z INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpkqpksfoa/_remote_module_non_scriptable.py
2022-08-03T21:56:07.1939531Z libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
2022-08-03T21:56:07.2568605Z STAGE:2022-08-03 21:56:07 94406:94406 ActivityProfilerController.cpp:294] Completed Stage: Warm Up
2022-08-03T21:56:07.2573904Z /opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py:9: UserWarning: is_namedtuple is deprecated, please use the python checks instead
2022-08-03T21:56:07.2575511Z   warnings.warn("is_namedtuple is deprecated, please use the python checks instead")
2022-08-03T21:56:07.2577391Z STAGE:2022-08-03 21:56:07 94407:94407 ActivityProfilerController.cpp:294] Completed Stage: Warm Up
2022-08-03T21:56:07.2591082Z /opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py:9: UserWarning: is_namedtuple is deprecated, please use the python checks instead
2022-08-03T21:56:07.2592666Z   warnings.warn("is_namedtuple is deprecated, please use the python checks instead")
2022-08-03T21:56:08.9400193Z INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
2022-08-03T21:56:08.9401581Z INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
2022-08-03T21:56:08.9671888Z STAGE:2022-08-03 21:56:08 94407:94407 ActivityProfilerController.cpp:300] Completed Stage: Collection
2022-08-03T21:56:08.9673636Z STAGE:2022-08-03 21:56:08 94406:94406 ActivityProfilerController.cpp:300] Completed Stage: Collection
2022-08-03T21:56:08.9683550Z [W collection.cpp:652] Warning: ROCTracer produced duplicate flow start: 1 (function operator())
2022-08-03T21:56:08.9688149Z [W collection.cpp:652] Warning: ROCTracer produced duplicate flow start: 1 (function operator())
2022-08-03T21:56:09.0185667Z [W reducer.cpp:1298] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
2022-08-03T21:56:09.0191454Z [W reducer.cpp:1298] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
2022-08-03T21:56:09.0247192Z STAGE:2022-08-03 21:56:09 94407:94407 ActivityProfilerController.cpp:294] Completed Stage: Warm Up
2022-08-03T21:56:09.0248854Z STAGE:2022-08-03 21:56:09 94406:94406 ActivityProfilerController.cpp:294] Completed Stage: Warm Up
2022-08-03T21:56:09.0296184Z STAGE:2022-08-03 21:56:09 94407:94407 ActivityProfilerController.cpp:300] Completed Stage: Collection
2022-08-03T21:56:09.0296934Z STAGE:2022-08-03 21:56:09 94406:94406 ActivityProfilerController.cpp:300] Completed Stage: Collection
2022-08-03T21:56:11.7193208Z ok (7.403s)
2022-08-03T21:56:11.7193829Z 
2022-08-03T21:56:11.7195252Z ----------------------------------------------------------------------
2022-08-03T21:56:11.7196352Z Ran 1 test in 7.404s

**Review by rohan-varma — APPROVED** [review]
thanks!

**Comment by rohan-varma** [comment]
@jaglinux can you rebase please

**Comment by jaglinux** [comment]
> @jaglinux can you rebase please

Done, Thanks.

**Pull request closed without merging**
