### PR TITLE
Revert custom strtod implementation

### PR DESCRIPTION
**Pull request by smessmer**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#21369 Revert custom strtod implementation**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D15630245/)

We wrote a custom strtod implementation because strtod_c isn't available on Android.
Since that code is not used on Android, we can actually revert to the much simpler implementation.

This hopefully fixes this issue: https://github.com/pytorch/pytorch/issues/20804

Differential Revision: [D15630245](https://our.internmc.facebook.com/intern/diff/D15630245/)

### CODE REVIEW

**Comment by bddppq** [comment]
btw. we have also run into a gcc abi version issue with the custom strtod implementation https://github.com/pytorch/pytorch/pull/21293

**Comment by bddppq** [comment]
Looks like android build is actually using it though:
https://circleci.com/api/v1.1/project/github/pytorch/pytorch/1913500/output/106/0?file=true
```
Jun 04 20:05:03 [ 46%] Building CXX object caffe2/CMakeFiles/caffe2.dir/__/torch/csrc/jit/script/strtod.cpp.o
Jun 04 20:05:03 /var/lib/jenkins/workspace/torch/csrc/jit/script/strtod.cpp: In function 'double torch::jit::script::strtod_c(const char*, char**)':
Jun 04 20:05:03 /var/lib/jenkins/workspace/torch/csrc/jit/script/strtod.cpp:28:34: error: 'strtod_l' was not declared in this scope
Jun 04 20:05:03      return strtod_l(str, end, loc);
```

**Review by ezyang — CHANGES_REQUESTED** [review]
The lexer uses it too...

**Comment by smessmer** [comment]
abandoning in favor of https://github.com/pytorch/pytorch/pull/21293

**Pull request closed without merging**
