### PR TITLE
Switch symbolic shape registry to operator map'

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #59051 Add peephole for len(x.size())
* #58932 Add more shape functions for mobilenet
* **#58890 Switch symbolic shape registry to operator map'**
* #56966 [JIT] Disable Complete Shape Inlining For Testing Purposes
* #56828 Add unary/binary ops necessary for mobilenet

'

Differential Revision: [D28663681](https://our.internmc.facebook.com/intern/diff/D28663681)

### CODE REVIEW

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28663681).

**Comment by eellison** [comment]
@edvgha i tried to add you as a reviewer but couldnt for some reason

**Review by ZolotukhinM — APPROVED** [review]
Looks good!

**Comment by ZolotukhinM** [comment]
> @edvgha i tried to add you as a reviewer but couldnt for some reason

I think you need to be added to PyTorch org for that

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28663681).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28663681).

**Pull request closed without merging**
