### PR TITLE
Commentary about size constraints on TensorImpl.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
CC @zou3519 this will conflict with your patch

**Review by smessmer — APPROVED** [review]
Looks good. An alternative (if you don't want to do the 32bit/64bit branch) would be to

    static_assert(sizeof(TensorImpl) == sizeof(member1) + sizeof(member2) + ...)

**Comment by ezyang** [comment]
Re `static_assert(sizeof(TensorImpl) == sizeof(member1) + sizeof(member2) + ...)` doesn't that miss the point? In particular, it won't tell if you if the size went up or down, if a member size changed.

**Comment by ezyang** [comment]
Landed in faa354e10243e9e6d6428e1bd0f317bb226c42bd

**Pull request closed without merging**
