### PR TITLE
Use 12xlarge for nightly cpp doc generation job

### PR DESCRIPTION
**Pull request by huydhn**
The job starts to run out of memory a lot recently https://hud.pytorch.org/failure/Process%20completed%20with%20exit%20code%20137.  Probably more and more docs are added, so this ups the runner for cpp doc nightly from 4xlarge to the next tier of 12xlarge. This also choose the smaller runner of 2xlarge for python and functorch docs (may be linux.large is good enough for them?)

### CODE REVIEW

**Comment by huydhn** [comment]
The fix for actionlint is in https://github.com/pytorch/pytorch/pull/87009 to add `linux.12xlarge` as a valid runner label

**Comment by seemethere** [comment]
Why do does docs generation of all things require a larger machine than our binary builds?

**Review by malfet — APPROVED** [review]
LGTM, but please add `linux.12xlarge` to the list of known instances

**Comment by malfet** [comment]
Please add `linux.12xlarge` to https://github.com/pytorch/pytorch/blob/master/.github/actionlint.yaml to make CI pass

**Comment by huydhn** [comment]
> Why does docs generation of all things require a larger machine than our binary builds?

I'm asking myself the same question and it seems to points to sphinx-build. At the moment, it still takes close to 3 hours to finish building PyTorch cpp doc even with a 4xlarge runner and `-j auto` to run multiple processes if possible.  So this is a much heavier job than building PyTorch.  It's a low priority task at the moment, but let me see if I can add some form of caching to sphinx-build to make this better

**Pull request closed without merging**
