### PR TITLE
Fix lr_scheduler's last_epoch value at the time of initialization (BC BREAKING!)

### PR DESCRIPTION
**Pull request by bado-lee**
Hello everyone :) !!

I've found that lr_scheduler was initialized with last_epoch as -1.
This causes that even after the first step (not the one in init but explicit step of scheduler),
learning rate of scheduler's optimizer remains as the previous.
```python
>>> import torch
>>> cc = torch.nn.Conv2d(10,10,3)
>>> myinitial_lr = 0.1
>>> myoptimizer = torch.optim.Adam(cc.parameters(), lr=myinitial_lr)
>>> mylrdecay = 0.5
>>> myscheduler = torch.optim.lr_scheduler.ExponentialLR(myoptimizer,mylrdecay)

# get_lr value and optimizer's lr value is not consistent, last_epoch should be 0 instead of -1
>>> myscheduler.get_lr()
[0.2]    # this is because of  get_lr calculates lr by 0.1 * 0.5^-1
>>> myscheduler.optimizer.param_groups[0]["lr"]
0.1    # this is not consistent with get_lr value
>>> myscheduler.last_epoch
-1

# values seem to be in sync but should have been decayed value of 0.05 after first step(decay)
>>> myscheduler.step()
>>> myscheduler.get_lr()
[0.1]    # this should be the value right after the init, not after first step
>>> myscheduler.optimizer.param_groups[0]["lr"]
0.1    # since this is after first step, it should have been decayed as 0.05
>>> myscheduler.last_epoch
0

>>> myscheduler.step()
>>> myscheduler.last_epoch
1
>>> myscheduler.get_lr()
[0.05]
>>> myscheduler.optimizer.param_groups[0]["lr"]
0.05
>>> myscheduler.last_epoch
1
```

First problem is, even after the init of lr_scheduler, you get the inconsistent parameter values.

The second problem is, you are stuck with same learning rate in the first 2 epochs if the step function of lr_scheduler is not called in the beginning of the epoch loop.
Of course, you can avoid this by calling lr_scheduler's step in the beginning,
but I don't think this is proper use since, incase of optimizer, step is called in the end of the iteration loop.

I've simply avoided all above issues by setting last_epoch as 0 after the initialization.

This also makes sense when you init with some value of last_epoch which is not -1.
For example, if you want to init with last epoch 10,
lr should not be set with decayed 1 step further. Which is 
last_epoch gets +1 in the previous code.
base_lr * self.gamma ** self.last_epoch

Instead, it should be set with step 10 exact value.

I hope this fix find it's way with all your help :)
I'm really looking forward & excited to become a contributor for pytorch!
Pytorch Rocks!!

### CODE REVIEW

**Comment by bado-lee** [comment]
@ezyang Hi can you please review this?

**Comment by ezyang** [comment]
@bado-lee I don't think the change you suggested here is right. In the example code in the docs, we clearly step the scheduler before training:

```
>>> # Assuming optimizer uses lr = 0.05 for all groups
>>> # lr = 0.05     if epoch < 30
>>> # lr = 0.005    if 30 <= epoch < 80
>>> # lr = 0.0005   if epoch >= 80
>>> scheduler = MultiStepLR(optimizer, milestones=[30,80], gamma=0.1)
>>> for epoch in range(100):
>>>     scheduler.step()
>>>     train(...)
>>>     validate(...)
```

Perhaps a more logical design would have been to step the scheduler at the same time you step the optimizer, but that's not how the API works today, and you'd be changing the behavior of anyone's code who had been abiding by the API previously.

What do you think about this reasoning?

**Comment by bado-lee** [comment]
@ezyang 
Thank you for your comment.
Yes you are are right on the docs. So I fixed them also.

There are several points about this.

1. Meaning of "Step" should be stepping forward from the initial status.
    Previous implementation requires step to be part of the initialization. Which is ambiguous.
    Which means, the very first step in the loop is actually an initialization rather than actual "Step".
    It will be clear if step can be called only when needed.

2. This code fixes inconsistency of results between the following before calling the very first step. (stated above)
```
>>> myscheduler.get_lr()
>>> myscheduler.optimizer.param_groups[0]["lr"]
```
 
3. There is already a case where scheduler step should be called in the end of the loop
```
class ReduceLROnPlateau(object):
...
Example:
    >>> optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
    >>> scheduler = ReduceLROnPlateau(optimizer, 'min')
    >>> for epoch in range(10):
    >>>     train(...)
    >>>     val_loss = validate(...)
    >>>     # Note that step should be called after validate()
    >>>     scheduler.step(val_loss)
"""
```

I'll update if further fixes are required.

**Comment by ezyang** [comment]
Paging the backwards compatibility police @soumith @colesbury

**Comment by bado-lee** [comment]
About backward compatibility and the documentation example,
currently there are 6 types of lr scheduler among which 

1 has example with step in the end of the loop.

3 has scheduler.step() in the beginning of the loop (I guess this was necessary evil given that the class which it inherited from was not implemented corectly)

2 doesn't have example mentioning where to put the step.

So I think it's better off with everything in order with example giving as step in the end of the loop.
Please consider that there can be future confusion for the new comers.
If this is not corrected now.

**Comment by apaszke** [comment]
Didn't have time to read through all the comments here, but IIRC the current impl matches that of Keras, and so it might not only be a question of BC, but also of avoiding adding confusion to API ported from a different framework.

**Comment by bado-lee** [comment]
@apaszke Thanks for the comment.
I've looked for what you have mentioned in [keras](https://github.com/keras-team/keras/blob/0237542f48566c9115b3dde4cce920b00e25507a/keras/callbacks.py#L609)
```
class LearningRateScheduler(Callback):
    """Learning rate scheduler.
    # Arguments
        schedule: a function that takes an epoch index as input
            (integer, indexed from 0) and current learning rate
            and returns a new learning rate as output (float).
        verbose: int. 0: quiet, 1: update messages.
    """

    def __init__(self, schedule, verbose=0):
        super(LearningRateScheduler, self).__init__()
        self.schedule = schedule
        self.verbose = verbose

    def on_epoch_begin(self, epoch, logs=None):
        if not hasattr(self.model.optimizer, 'lr'):
            raise ValueError('Optimizer must have a "lr" attribute.')
        lr = float(K.get_value(self.model.optimizer.lr))
        try:  # new API
            lr = self.schedule(epoch, lr)
        except TypeError:  # old API for backward compatibility
            lr = self.schedule(epoch)
        if not isinstance(lr, (float, np.float32, np.float64)):
            raise ValueError('The output of the "schedule" function '
                             'should be float.')
        K.set_value(self.model.optimizer.lr, lr)
        if self.verbose > 0:
            print('\nEpoch %05d: LearningRateScheduler reducing learning '
                  'rate to %s.' % (epoch + 1, lr))
```
Well as you said, this one in Keras specifies the function name as "on_epoch_begin" specifically which is counterpart of "step" in pytorch. Yes, this one is required to be call in the beginning of the loop.
But I think it's behavior and intention is different from what is implemented in pytorch.
The naming is not "step", it's "on_epoch_begin". Which are clearly different.
Furthermore, "on_epoch_begin" is required to have epoch number as an input variable where "step" is not.
So, IMHO, it's not valid that this implementation matches that of Keras.
And, to me it's more reasonable that naming "step" is to be matched with the behavior of the optimizer step in pytorch which is called in the end in the loop.

**Comment by bado-lee** [comment]
https://discuss.pytorch.org/t/how-to-use-torch-optim-lr-scheduler-exponentiallr/12444/5
I think above is what pretty much everyone would do. Given the name is "step".
But current code will run with same lr for the first 200 iterations instead of 100.

**Comment by bado-lee** [comment]
Hi. Can I get a status on this?

**Comment by bado-lee** [comment]
@soumith @colesbury Hi, can I get a status on this?

**Comment by yf225** [comment]
@soumith @colesbury What would be the next step for this PR?

**Comment by lironmo** [comment]
any update?

**Comment by bado-lee** [comment]
@ezyang 
Hi. Can you tell me how should I proceed with this request?
I'm also not sure about the current build fails. I think(hope) they are not related to my codes.

**Comment by bado-lee** [comment]
```
08:06:12 test_adam (__main__.TestOptim) ... ok
08:06:15 test_adamax (__main__.TestOptim) ... ok
08:06:16 test_asgd (__main__.TestOptim) ... ok
08:06:16 test_invalid_param_type (__main__.TestOptim) ... ok
08:06:16 test_lbfgs (__main__.TestOptim) ... ok
08:06:17 test_lbfgs_return_type (__main__.TestOptim) ... ok
08:06:17 test_rmsprop (__main__.TestOptim) ... ok
08:06:17 test_rprop (__main__.TestOptim) ... ok
08:06:19 test_sgd (__main__.TestOptim) ... ok
08:06:21 test_sgd_sparse (__main__.TestOptim) ... ok
08:06:27 test_sparse_adam (__main__.TestOptim) ... ok
```
These tests seem successful except 
pr/py2-clang7-rocmdeb-ubuntu16.04
pr/py2-devtoolset7-rocmrpm-centos7.5

**Comment by ezyang** [comment]
The ROCm failures do look kind of suspicious; I haven't seen them before. cc @iotamudelta

**Comment by ezyang** [comment]
@bado-lee If we don't get a timely response from the ROCm people, I suggest disabling these tests on ROCm.

**Comment by iotamudelta** [comment]
@bado-lee @ezyang please disable for now, I need to take a closer look at this as it shouldn't have any impact on ROCm.

**Comment by bado-lee** [comment]
@iotamudelta @ezyang Ok I'll disable the tests. If it's ok, let me try tomorrow.

**Comment by ezyang** [comment]
sgtm

**Comment by bado-lee** [comment]
@ezyang 
Hi, I've disabled failing tests on ROCm. 
(adam, adamax, asgd, lbfgs)
So there is no issue with them now.

But it's now failing with "ci/circleci: binary_linux_libtorch_2.7m_cu80_build"
Which was not happening before.
I've tried to figure out but circleci log is cut and I cannot check error logs at the end of the line.
Could you help me with this?

**Comment by ezyang** [comment]
Looks like it was just flakiness :)

**Comment by bado-lee** [comment]
@ezyang 
So, it's a pass?

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Note for release manager, this is a **major** BC-breaking change (but for the better!)

**Comment by bado-lee** [comment]
When is this getting merged? Just curious.

**Comment by vfdev-5** [comment]
@bado-lee @ezyang looking at the actual code of `_LRScheduler` shouldn't we set `last_epoch=None` in the `__init__` to make it clearly undefined vs `last_epoch=-1` ?

**Comment by bado-lee** [comment]
@vfdev-5 I've made some changes according to your suggestion.
Thank you very much. :)

**Comment by acburigo** [comment]
This did not change for `CosineAnnealingLR`?

**Comment by SsnL** [comment]
This breaks BC so much! All the code out there that use `scheduler.step()` before training now breaks silently? A lot of major repos are affected :(!

**Comment by vfdev-5** [comment]
> A lot of major repos are affected :(!

@SsnL that's true, I had the same opinion seing this. However, in the worst case, IMO, the training starts from the second LR scheduling value instead of the first. Maybe this is a not big issue for iteration-wise lr scheduling (a bit more for epoch-wise).

**Comment by SsnL** [comment]
@vfdev-5 

1. This generally causes lr to decay faster than they used to be, and could harm performance with hyperparameter tuned for the previous behavior. 
2. People research on training with very few gd steps. This is just devastating if they use lr schedulers.
3. 1.0.0 and 1.0.1 are not so long ago. This patch makes it impossible for a code to behave the same on both 1.0.1 and 1.1.

**Comment by vfdev-5** [comment]
@SsnL I totally agree with the 3rd point! The 2nd point is not clear, can you provide some details ?

**Comment by SsnL** [comment]
@vfdev-5 Yes, of course. I am trying to highlight usecases where this would affect this most. 
 Some people investigate the behavior of gradient updating and would look like the optimization process for like 50 or 500 number of steps. Generally they use a fixed learning rate and doesn’t really rely on or schdulers. But if any of these project use them to update lr per iteration, this change would have a major effect.

**Comment by vfdev-5** [comment]
@SsnL I see, thanks! 

I made some plots to compare 1.0.1 vs 1.1.0 if the code is as for 1.0.1:
```python
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline

from torch.optim.lr_scheduler import MultiStepLR

t = torch.tensor([0.0], requires_grad=True)
opt = torch.optim.SGD([t], lr=0.01)

lr_scheduler = MultiStepLR(opt, milestones=[10, 20, 30])

lrs = []
for e in range(35):
    lr_scheduler.step()
    lrs.append((e, opt.param_groups[0]['lr']))

lrs = np.array(lrs)
plt.plot(lrs[:, 0], lrs[:, 1])
```

For `1.0.1`:
image

```python
lrs[0, :], lrs[9, :], lrs[10, :]
> (array([0.  , 0.01]), array([9.  , 0.01]), array([1.e+01, 1.e-03]))
```

For `1.1.0` it is just shifted one iteration:
image

```python
lrs[0, :], lrs[9, :], lrs[10, :]
> (array([0.  , 0.01]), array([9.e+00, 1.e-03]), array([1.e+01, 1.e-03]))
```

**Comment by SsnL** [comment]
@vfdev-5 Thanks for the plots :). That seems to be most of the case. But there do seem to be something weird going on for CosineAnnealingLR https://github.com/pytorch/pytorch/issues/20086

**Comment by vfdev-5** [comment]
@SsnL yeah, very weird behaviour. Seems like it is also because of recursive implementation...

**Comment by lihuanglx** [comment]
It's hard to believe this patch is merged into the stable release. From my point of view, this "fix" starts totally from personal perference rather than real need. I don't see any benefit of this change, neither in terms of efficiency nor in terms of usability. And I don't see any real problem of the old implementation and old convertion of putting the `step()` at the end of each iteration. But it got merged and horribly breaks almost all current projects based on PyTorch, and seems lead to bugs (#20086, #20138 ). Normally such huge compatibility-breaking changes should only be considered if it greatly improves the software, otherwise it is not responsible to the users, especially considering the enormous size of PyTorch community.

**Comment by ezyang** [comment]
I'm going to go ahead and revert this. @soumith, it would be great if the revert could be cherry-picked to 1.1 as well. This shouldn't have been merged so close to the 1.1 branch cut; that is my mistake. @bado-lee, I can help you put together a deprecation schedule.

**Comment by ezyang** [comment]
Actually, I am catching up on the discussion. I see that #20059 was merged while I was away. @lihuanglx, is that patch sufficient to eliminate the BC-breakage, or is a more complete revert needed?

**Comment by SsnL** [comment]
@ezyang I don't think #20059 change the behavior. 

Also, if we still want to make this change, please consider my suggestion at https://github.com/pytorch/pytorch/issues/20124 on adding a warning.

**Comment by waleedka** [comment]
Sure, this should have been planned better, but I think the fix is valid. It was confusing to have to call optimizer step() at the end and scheduler step() at the beginning, and this PR fixes that inconsistency. Since it's already out there, reverting it might cause more damage and confusion. I second @SsnL 's suggestion of showing a warning when the old pattern is detected and leave it at that.

**Comment by bado-lee** [comment]
@ezyang I saw your revert commit. Is it decided to revert the change?
Honestly, it also occurs to me that it could have been smoother if the change had been warned for couple of minor versions earlier. But actually, I do not suspect it's validity. I understand that this change can influence many people and be even shocking to some. But it doesn't mean that this fix should be neglected.
Also, since it's already released as version 1.1 so reverting it would only cause more damage.
I think @SsnL 's suggestion would be sufficient as of now.

**Comment by ezyang** [comment]
Hey @bado-lee, I've closed the revert commit, so we're going to keep it :) Is there an outstanding PR to add a warning for the old pattern? I'd be happy to help review.

**Comment by bado-lee** [comment]
@ezyang I think I can work on #20124 if there isn't a PR already. I'll let you know when done. Thank you :)

**Comment by vfdev-5** [comment]
@bado-lee I was also thinking to send a PR too.

**Comment by bado-lee** [comment]
@vfdev-5 Oh in that case please be my guest. I would be more than happy to review it :)

**Comment by gchanan** [comment]
One thing I don't quite understand:

There's a discussion about the keras API (`on_epoch_begin`) and some comments indicating that the name makes what's going on clearer, but no discussion about introducing something like that as a future fix that doesn't break BC.

Should we do something like that?

**Comment by ezyang** [comment]
Yes, I also think we should do this.

Excerpts from gchanan's message of 2019-05-08 14:36:08 -0700:
> One thing I don't quite understand:
> 
> There's a discussion about the keras API (`on_epoch_begin`) and some comments indicating that the name makes what's going on clearer, but no discussion about introducing something like that as a future fix that doesn't break BC.
> 
> Should we do something like that?
>

**Pull request closed without merging**
