### PR TITLE
[BE][codemod]: Fix all implicit optionals in torch folder

### PR DESCRIPTION
**Pull request by Skylion007**
Automatically replaces all implicit optional with explicit one using automated codemod https://github.com/hauntsaninja/no_implicit_optional
* This improves typing, code style, and can alloy mypy to catch bugs that implicit optional would miss. It also make the documentation and typing of many IDEs more robust.
* This is the default behavior in newer versions of mypy and will be needed if we update mypy anyhow. (It's one of the main blockers to updating mypy).
cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @anijain2305

### CODE REVIEW

**Comment by ezyang** [comment]
This looks fine but you need to finish off ci

**Comment by Skylion007** [comment]
> This looks fine but you need to finish off ci

@ezyang How do I disable all the bc breaking changes it's complaining about? (The function signatures are changing, but the type hints are only more accurate than they were before, functionally nothing changes).

**Review by albanD — APPROVED** [review]
Sound good!
Not sure what is the right way to silence the BC linter though cc @izaitsevfb

**Comment by Skylion007** [comment]
@XuehaiPan If you are looking for a good typing ruff rule to enable, I just never got around to deal with all the BC changes needed.

**Pull request closed without merging**
