### PR TITLE
configurable pre/post LayerNorm in nn.Transformer

### PR DESCRIPTION
**Pull request by bhosmer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #60631 faster generate_square_subsequent_mask in nn.Transformer
* **#60593 configurable pre/post LayerNorm in nn.Transformer**

Per #55270, this PR makes it configurable whether to run LayerNorm before or after other operations in Transformer layers.

However, it leaves for a separate PR the removal of the LayerNorm performed after the final encoder/decoder layer has run, which is redundant when LayerNorms has been run after other in-layer operations (problem described in #24930 #50086 #51447). 

Note: this means that transformers built with `nn.Transformer()` are now configurable, but will still contain a redundant LayerNorm when configured as before. However, callers of the `TransformerEncoder` and `TransformerDecoder` classes have always been able to avoid this redundancy.

Reviewer notes:
1. Ran across this during other work, don't know if anybody's working on it already (most recent conversation in issues seems to be from early April). Happy to abandon if so.
2. Was looking for a quick way to add tests but it looks like the existing ones in test_nn just compare against snapshots. I could add something similar, but curious if there's any prepackaged way to add a test that LayerNorm-first (the new option) yields model that trains properly, etc.
3. New code in the `forward`s was written to minimize diff churn rather than maximize beauty :P happy to pretty it up if desired.

Differential Revision: [D29356590](https://our.internmc.facebook.com/intern/diff/D29356590)

### CODE REVIEW

**Comment by jbschlosser** [comment]
@bhosmer Thanks for looking into this! I haven't fully dug into the PR yet, but given that `LayerNorm` has learnable parameters by default, will removing the redundant norm by default result in any BC-breaking model loading issues?

Specifically, the example I'm considering is calling `load_state_dict()` with a `state_dict` from a previously-serialized model that contained the duplicate norms. Won't there be an extra key in the `state_dict` for the redundant `LayerNorm` that will break loading (at least without setting `strict=False`)?

**Comment by bhosmer** [comment]
> @bhosmer Thanks for looking into this! I haven't fully dug into the PR yet, but given that `LayerNorm` has learnable parameters by default, will removing the redundant norm by default result in any BC-breaking model loading issues?
> 
> Specifically, the example I'm considering is calling `load_state_dict()` with a `state_dict` from a previously-serialized model that contained the duplicate norms. Won't there be an extra key in the `state_dict` for the redundant `LayerNorm` that will break loading (at least without setting `strict=False`)?

Yup I'm sure you're right. Relatedly, some/all of the test failures here are probably symptomatic of this issue or a variation - though I'm not quite sure of the chain of custody (the error on at least half of them is "No such serialized submodule: 'encoder.norm'").

I can think of 3 options:
1. conservative: just add the `norm_first` config, but kill the logic that avoids the redundant LayerNorm at the end. (Maybe splitting the former into a separate PR is a good idea anyway.)
2. sketchy: still *create* the redundant LayerNorms, but don't run them in forward. Downsides: a) slightly wasteful, but more importantly b) silently runs different compute on reloaded modules (I don't see how LN(LN(x)) == LN(x) can be guaranteed in the presence of separate learned params). (b) seems like a dealbreaker but listing this option in case I'm wrong...
3. adaptive loading: some kind of override of `load_state_dict()` (?) that detects this submodule on load and uses it if present. (Is that how we do compatibility shims of this kind? if not, happy to work from an example, just point me)

LMK your thoughts, I'm fine doing whichever you think is right (well, except maybe #2 😁 )

**Comment by bhosmer** [comment]
@bhosmer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29356590).

**Comment by bhosmer** [comment]
@bhosmer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29356590).

**Review by jbschlosser — APPROVED** [review]
LGTM- good call bumping the duplicate `LayerNorm` fix to a future PR

**Comment by bhosmer** [comment]
@bhosmer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29356590).

**Pull request closed without merging**
