### PR TITLE
Fix bug where frozen mod not used for OFI #68903

### PR DESCRIPTION
**Pull request by Gamrix**
Fixes issue #68903

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #71437
* __->__ #71436

Differential Revision: [D33824857](https://our.internmc.facebook.com/intern/diff/D33824857)

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
Nice! Test?

**Comment by Gamrix** [comment]
Added test, and updated the existing test to remove typo that hid the error.

**Review by eellison — APPROVED** [review]
LGTM, thanks!

**Comment by Gamrix** [comment]
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33824857).

**Pull request closed without merging**
