### PR TITLE
Revert "Revert D27598681: Add OpInfo tests for torch.addbmm"

### PR DESCRIPTION
**Pull request by anjali411**
Reland https://github.com/pytorch/pytorch/pull/55378

### CODE REVIEW

**Comment by imaginary-person** [comment]
Hello @mruberry & @anjali411, I sincerely apologize if my comments have been bothersome lately. I'll keep in mind not to post unsolicited comments.

However, I'm making an exception this time around. Please note that `pytorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_test1` didn't run this time, and because of the CUDA/cuDNN bug I mentioned, `test_supported_backward_addmm_cuda_bfloat16` will fail if this PR would be merged.

Thanks!

**Comment by imaginary-person** [comment]
@anjali411, the CI check `pytorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_test1` didn't run because you used your own branch that starts with `ci-all/`, but you'd have to use a PyTorch branch.

**Comment by imaginary-person** [comment]
CircleCI uses Tesla T4 GPUs which are SM_75.

Ref:
https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/.jenkins/pytorch/win-test-helpers/build_pytorch.bat#L63

**Comment by anjali411** [comment]
> @anjali411, the CI check `pytorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_test1` didn't run because you used your own branch that starts with `ci-all/`, but you'd have to use a PyTorch branch whose name has the prefix `ci-all/`.
> 
> EDIT: Sorry, you probably know that now.

Hi @imaginary-person I actually didn't know that. thank you!

**Comment by anjali411** [comment]
closing in favor of https://github.com/pytorch/pytorch/pull/55908

**Pull request closed without merging**
