### PR TITLE
[dtensor] add comment to clarify MaskPartial cache hit

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #118330
* #118242
* #118080
* #118079

As titled, add a comment to explain more details

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### CODE REVIEW

**Review by tianyu-l — APPROVED** [review]

**Review by XilunWu — APPROVED** [review]
thx for helping users better understand

**Pull request closed without merging**
