### PR TITLE
Avoid race condition in intrusive_ptr.reset_()

### PR DESCRIPTION
**Pull request by skrah**
This is a spin-off from #24368 (high priority inherited from #3818).

### CODE REVIEW

**Comment by skrah** [comment]
Some background: #24368 introduces a weak variable based on `c10:: weak_intrusive_ptr`.

`TestNN::test_load_state_dict_custom` failed due to the following sequence of events.


Before this line `target_->weakcount_` is `2`.  One for the strong reference and another for an actual weak reference:

https://github.com/pytorch/pytorch/blob/e78dad359314f9acc1a14fe071cf06fe317d2ce6/c10/util/intrusive_ptr.h#L194

After this line `target_->weakcount_` is `1`.

Now, in another thread, the weak reference deletes the target:

https://github.com/pytorch/pytorch/blob/e78dad359314f9acc1a14fe071cf06fe317d2ce6/c10/util/intrusive_ptr.h#L451

Back in the original thread, the strong reference attempts to delete resources:

https://github.com/pytorch/pytorch/blob/e78dad359314f9acc1a14fe071cf06fe317d2ce6/c10/util/intrusive_ptr.h#L197

Arriving here, where `storage_` is in a block that has been freed:

https://github.com/pytorch/pytorch/blob/e78dad359314f9acc1a14fe071cf06fe317d2ce6/c10/core/TensorImpl.cpp#L134

**Comment by skrah** [comment]
Hi @ezyang, could you have a look at this? This blocks  #24368, but I think it is better as a separate PR.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@smessmer This looks good to me, I will go ahead and land it but shout if you have objections

**Comment by ezyang** [comment]
waiting on ci

**Pull request closed without merging**
