### PR TITLE
Add config option to reduce warnings in inductor

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #94413

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Ok. Probably a lot more places we can use this. Make a WP post?

**Comment by jansel** [comment]
> Ok. Probably a lot more places we can use this. Make a WP post?

I looked at every warning in `_inductor/` though likely some in other places.

**Pull request closed without merging**
