### PR TITLE
Add test for skipping hf logging during export

### PR DESCRIPTION
**Pull request by thiagocrepaldi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #123410

https://github.com/pytorch/pytorch/pull/123402 already supports hf
logging because HF logger is based on logging module

This PR adds a test to guard this against regression, only

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

### CODE REVIEW

**Comment by thiagocrepaldi** [comment]
There are 2 unrelated failures:

* linux-focal-py3.11-clang10 / test (default, 3, 3, linux.2xlarge) 

```bash
2024-04-05T04:23:22.5776270Z FAILED [0.0069s] profiler/test_profiler.py::TestProfiler::test_source_multithreaded_basic_work_in_main_thread_True - AssertionError: Scalars are not equal!
```

* linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default, 5, 5, linux.g5.4xlarge.nvidia.gpu)

```bash
2024-04-05T04:11:47.7524413Z ________ TestPatternMatcher.test_fuse_attention_all_patterns_serialized ________
2024-04-05T04:11:47.7525072Z Traceback (most recent call last):
2024-04-05T04:11:47.7525971Z   File "/var/lib/jenkins/workspace/test/inductor/test_pattern_matcher.py", line 1004, in test_fuse_attention_all_patterns_serialized
2024-04-05T04:11:47.7526981Z     self.assertEqual(
2024-04-05T04:11:47.7527872Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3624, in assertEqual
2024-04-05T04:11:47.7528857Z     raise error_metas.pop()[0].to_error(
2024-04-05T04:11:47.7530072Z AssertionError: String comparison failed: "rand[2815 chars]())\nalias_default = CallFunction(aten.alias.d[2921 chars]\n])" != "rand[2815 chars]())\nview_default_6 = CallFunction(aten.view.d[2922 chars]\n])"
2024-04-05T04:11:47.7531363Z Diff is 6591 characters long. Set self.maxDiff to None to see it.
2024-04-05T04:11:47.7532109Z Found mismatched pattern _sfdp_pattern_18_training. Run gen_attention_patterns.py
```

**Review by BowenBao — APPROVED** [review]

**Comment by BowenBao** [comment]
@angelayi for approval stamp

**Comment by thiagocrepaldi** [comment]
@malfet could you help with this one? I added a test to protect https://github.com/pytorch/pytorch/pull/123402 when hugging face is at play. there is a skip if CI doesnt have it installed

**Review by malfet — APPROVED** [review]

**Comment by thiagocrepaldi** [comment]
Same as #123402. This PR was merged after another one that renamed input names on FX graph. Fixed and waiting for CI to confirm

**Comment by malfet** [comment]
> @malfet do you know what is going on here? it passed all ci and doesnt show conflicts. after 2 regular merge commands, they were canceled for some reason. the force merge also failed with "conflict"

@thiagocrepaldi well this is ghstack, so it would never show conflicts even if conflicts with trunk until one tries to merge. 
But technically ["Check mergeability of ghstack PR"](https://github.com/pytorch/pytorch/actions/runs/8650873929/job/23720307343?pr=123410) should give you an early signal on merge conflicts, if this was not the case, please let me know

**Pull request closed without merging**
