### PR TITLE
[ROCm][Inductor][CK] Add batched gemms into gemm max autotune with CK backend

### PR DESCRIPTION
**Pull request by tenpercent**
## Testing
```
TORCH_LOGS=+torch._inductor pytest --capture=no test/inductor/test_ck_backend.py -k bmm
```

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @zjing14

### CODE REVIEW

**Review by chenyang78 — APPROVED** [review]
LGTM. Thanks!

**Comment by tenpercent** [comment]
Link https://github.com/ROCm/composable_kernel/pull/1684
Link #125453

**Pull request closed without merging**
