### PR TITLE
[ONNX] Generate diagnostic source files during build

### PR DESCRIPTION
**Pull request by BowenBao**

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
I need to really fix OSS Buck...

**Review by thiagocrepaldi — COMMENTED** [review]
@BowenBao are we going to keep working on this? If so, we probably need to remove the `Stale` label before it trips the PR forced closing

**Comment by BowenBao** [comment]
@thiagocrepaldi not really. I was going to let it naturally close.

**Pull request closed without merging**
