### PR TITLE
add grad_output shape check for fractional_max_pool2d_backward

### PR DESCRIPTION
**Pull request by jiayisunx**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #141666

Fix https://github.com/pytorch/pytorch/issues/141102.

### CODE REVIEW

**Review by mingfeima — APPROVED** [review]

**Comment by jiayisunx** [comment]
hi @malfet  , could you please review this PR? thanks!

**Review by malfet — APPROVED** [review]

**Review by malfet — CHANGES_REQUESTED** [review]
Looks like this causes lots of failures for zero-batch cases, which are relevant

**Comment by jiayisunx** [comment]
> Looks like this causes lots of failures for zero-batch cases, which are relevant

Yes, I have fixed it. Could you please review it again? Thanks!

**Review by malfet — APPROVED** [review]
Thank you for the fix

**Pull request closed without merging**
