### PR TITLE
[Dynamo] Support python class member_descriptor

### PR DESCRIPTION
**Pull request by yanboliang**
Fixes Meta internal cases.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by jeanschmidt** [comment]
Hi, it seems that this PR broke some slow jobs.

https://hud.pytorch.org/pytorch/pytorch/commit/12cd776d902dea1ee3f0ef7980bea62ff64096d2

I believe we want to revert this and investigate

**Pull request closed without merging**
