### PR TITLE
[WIP] tensor.pin_memory always copies even when it is already pinned

### PR DESCRIPTION
**Pull request by codexetreme**
#21076
cc @SsnL @VitalyFedyunin

### CODE REVIEW

**Comment by codexetreme** [comment]
I have just added a simple return statement if self is pinned, what to do when the tensor is not already pinned? it will need to go through the remaining part of the code in `Memory.cpp` right?

**Comment by codexetreme** [comment]
Any updates on this ??

**Comment by VitalyFedyunin** [comment]
`Jun 03 23:35:20 /var/lib/jenkins/workspace/aten/src/ATen/native/Memory.cpp:16:12: error: 'const class at::Tensor' has no member named 'is_pinned'
Jun 03 23:35:20    if (self.is_pinned()) return self;`

**Comment by VitalyFedyunin** [comment]
Please add me as reviewer again when it is fixed. Thanks.

**Comment by ngimel** [comment]
Currently pin_memory checks is_pinned.

**Pull request closed without merging**
