### PR TITLE
[dynamo] use lazy disable dynamo for manual seed

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #124881
* #124501
* __->__ #125196

cc @ezyang @msaroufim @bdhirsh @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

### CODE REVIEW

**Review by fegin — APPROVED** [review]
Thanks for the fix!

**Review by yanboliang — APPROVED** [review]

**Pull request closed without merging**
