### PR TITLE
Fix CharType min and max values

### PR DESCRIPTION
**Pull request by sdmonov**
CharType is int8_t and this is not same as char. CHAR_MIN and CHAR_MAX cannot be used reliably to specify min and max values for int8_t. Using CHAR_MIN/MAX breaks some functions when used on a platform where the char type is unsigned (0-255 value) such as PowerPC and ARM.

### CODE REVIEW

**Review by apaszke — COMMENTED** [review]
Can you change that `SCHAR_*` macros?

**Review by apaszke — APPROVED** [review]

**Comment by sdmonov** [comment]
Good point. Fixed.

**Comment by soumith** [comment]
thanks a lot for the patch

**Pull request merged**
