### PR TITLE
Fix optim.lr_scheduler examples in doc to use optimizer vs self.opt

### LINKED ISSUE #119561: `torch.optim.lr_scheduler` examples use `self.opt` instead of `optimizer`
### 📚 The doc issue

Some of the `torch.optim.lr_scheduler` clasess' examples use `self.opt` instead of `optimizer`.

* https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.ChainedScheduler.html,
* https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.SequentialLR.html,
* https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.ConstantLR.html,
* https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.LinearLR.html,
* https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.PolynomialLR.html.

### Suggest a potential alternative/fix

_No response_

### PR DESCRIPTION
**Pull request by kuraga**
Fixes #119561

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
Thanks for the catch!

**Comment by janeyx99** [comment]
Hm weird...the normal PR jobs aren't triggering. We should verify the docs look good before merging.

**Comment by janeyx99** [comment]
@clee2000 do you know why the jobs aren't getting triggered?

**Comment by clee2000** [comment]
> @clee2000 do you know why the jobs aren't getting triggered?

The commit title contains `[ci skip]` https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs.  You'll need to make another commit without that to trigger CI

**Comment by kuraga** [comment]
Is CI needed for docs regeneration?

Can I force-push the commit?

**Comment by janeyx99** [comment]
Yes, we have a docs build that depends on building torch, so could you recommit without the skip ci message? Yes, forcepushing would work.

**Comment by kuraga** [comment]
@janeyx99 , done.

**Pull request closed without merging**
