### PR TITLE
Remove deprecated torch.eig

### PR DESCRIPTION
**Pull request by IvanYashchuk**
The time has come to remove deprecated linear algebra related functions. This PR removes `torch.eig`.

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
Great to see this one gone!

**Comment by mruberry** [comment]
Build and test issues look real

**Comment by IvanYashchuk** [comment]
@albanD, let's continue our quest on removing deprecated functions. Could you please take a quick look and approve? I added an error message (as with `torch.solve` https://github.com/pytorch/pytorch/pull/70986#pullrequestreview-963727891) that is raised when someone tries to call `torch.eig` and it's tested (see `test_eig_removed_error` in `test_linalg.py`).

@kit1980, could you please check the internal Meta usage of the `torch.eig` function and try importing this PR?

**Comment by kit1980** [comment]
@IvanYashchuk please resolve merge conflicts.

**Comment by IvanYashchuk** [comment]
Resolved

**Comment by kit1980** [comment]
@IvanYashchuk Can you fix https://github.com/pytorch/pytorch/runs/7415447660?check_suite_focus=true: 
AssertionError: Couldn't find OpInfo for ('eig', '', None, None, True)

**Comment by IvanYashchuk** [comment]
> @IvanYashchuk Can you fix https://github.com/pytorch/pytorch/runs/7415447660?check_suite_focus=true: AssertionError: Couldn't find OpInfo for ('eig', '', None, None, True)

Thanks for the ping! Turns out the problem is in the separate repo and I submitted the fix (https://github.com/pytorch/functorch/pull/978) but I'm not sure what should be the order of merges.

**Comment by kit1980** [comment]
Should probably wait until https://github.com/pytorch/pytorch/pull/81918 lands

**Comment by Lezcano** [comment]
fwiw, the order is:
- Merge the functorch (or xla) pr
- Update the pinned version in `.github/` in this PR
- Merge this PR

**Comment by kit1980** [comment]
> fwiw, the order is:
> 
> * Merge the functorch (or xla) pr
> * Update the pinned version in `.github/` in this PR to point to the commit you just merged
> * Merge this PR

functorch was just merged in pytorch/pytorch.
But still relevant for xla.

**Comment by kit1980** [comment]
@IvanYashchuk I see at least one failure internally. I'll try to update the usage and I'll let you know.

**Comment by IvanYashchuk** [comment]
It's slightly complicated to update `torch.eig` -> `torch.linalg.eig` because the old function is from the time when PyTorch didn't support complex numbers and returns a Tensor with pairs of floats instead. Let me know if I can be of any help here.

**Comment by Lezcano** [comment]
fwiw, I'd put my money on the fact that the internal implementation just considers the eigenvalues. 
If that's the case, we have that `torch.linalg.eigvals(A) == torch.view_as_complex(torch.eig(A).eigenvalues)`.

**Comment by kit1980** [comment]
FYI, I've returned to updating torch.eig internal usages. I'll let you know when I'm done and hopefully this PR can be merged soon.

**Comment by kit1980** [comment]
@IvanYashchuk @Lezcano I have a code `eig_vals, eig_vecs = torch.eig(matrix, eigenvectors=True)`, and then `eig_vecs` is used in non-trivial ways, like sorting and getting indices.

What's a general way to get old `eig_vecs` from `eig_vals_complex, eig_vecs_complex = torch.linalg.eig(matrix)`?

**Comment by Lezcano** [comment]
There is no unique way way to rewrite one really. If you provide us with a small repro either here or in slack we can certainly help rewrite that code.

P.s. I'm really surprised that people really tried to use that terrible API. That's impressive.

**Comment by kit1980** [comment]
We decided that the internal code that uses `torch.eig(matrix, eigenvectors=True)` is no longer needed and can be just removed.

@IvanYashchuk could you rebase/resolve conflicts?

**Comment by IvanYashchuk** [comment]
@kit1980 I have resolved merge conflicts. Could you please try importing the PR?

**Comment by kit1980** [comment]
@IvanYashchuk @Lezcano are you going to remove other deprecated linear algebra stuff soon? Can you list function names or PR links here? I want to try to deal with the others sooner than later.

**Comment by Lezcano** [comment]
Yes we are! There are a number of open PRs. See: https://github.com/pytorch/pytorch/pulls/IvanYashchuk
Now, I think that `torch.eig` is one of the most painful ones. For the other functions we can always use a non-deprecated function in place of them. Please ping me or Ivan, and we can help with these things :)

**Review by malfet — APPROVED** [review]
This needs a rebase, but LGTM provided that CI is green

**Comment by kit1980** [comment]
Please do not merge until I confirm the internal tests pass.

**Comment by IvanYashchuk** [comment]
How do internal tests look?

**Comment by kit1980** [comment]
> How do internal tests look, did they pass?

Removing one old piece of code that fails currently.

**Comment by kit1980** [comment]
@IvanYashchuk I'm going to land the diff internally soon, the PR will be merged automatically after that.

**Comment by kit1980** [comment]
Landed!
Hopefully there will be no unforeseen issues...

**Comment by kit1980** [comment]
OK, functorch test is failing https://github.com/pytorch/pytorch/runs/8279538230?check_suite_focus=true
I'm trying to forward-fix

**Pull request closed without merging**
