### PR TITLE
Make clamp twice differentiable

### PR DESCRIPTION
**Pull request by t-vi**
Hi,

thank you for pytorch!

This pull request attempts to implement twice differentiability for Variable.clamp.

As this is my first pull request with autograd (or pytorch for that matter), I may or may not know what I'm doing.
I appreciate your feedback.

Best regards

Thomas

### CODE REVIEW

**Review by apaszke — APPROVED** [review]

**Comment by t-vi** [comment]
I'll go fix the tests.

**Comment by apaszke** [comment]
You only need to copy args from one tuple (on the left) to another (next to it on the right). They're auto-generated so it's not very readable, but you should be able to see what to do in other PRs

**Comment by apaszke** [comment]
You made the linter unhappy with that lack of spaces in tuples

**Comment by t-vi** [comment]
Yes, sorry. I must admit I didn't run the tests beforehand when I didn't see them mentioned in the Contributing.md. Now it should be better.

**Review by apaszke — APPROVED** [review]

**Comment by apaszke** [comment]
Thank you!

**Pull request merged**
