### PR TITLE
Add func to enable/disable JIT oneDNN layout_propagation pass

### PR DESCRIPTION
**Pull request by wenzhe-nrv**
This PR adds a python API, allowing the flexibility to disable `layout_propagation` [pass](https://github.com/pytorch/pytorch/blob/874625e039274b83e70163733f6f2c1689b0de4e/torch/csrc/jit/codegen/onednn/layout_propagation.cpp#L37) in cases like Dynamo AOTAutograd training.

### Motivation
Currently JIT oneDNN fuser passes focuses on inference and `layout_propagation` pass is enabled by default to reduce overhead on layout change between graphs lowered to JIT oneDNN fuser. However, during training with Dynamo AOTAutograd TS backend, forward and backward graphs are captured with AOTAutograd and compiled separately with TS and oneDNN. So backward function TS interpreter step throws runtime error when an op cannot support `MkldnnCPU` layout, which is propagated from the forward graph. 
```
NotImplementedError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<eval_with_key>.11", line 78, in forward
    mm_10 = torch.ops.aten.mm(threshold_backward_5, t_29);  t_29 = None
    t_30 = torch.ops.aten.t(threshold_backward_5)
    mm_11 = torch.ops.aten.mm(t_30, relu_2);  t_30 = None
            ~~~~~~~~~~~~~~~~~ <--- HERE
    t_31 = torch.ops.aten.t(mm_11);  mm_11 = None
    sum_6 = torch.ops.aten.sum(threshold_backward_5, [0], True);  threshold_backward_5 = None
RuntimeError: Could not run 'aten::mm.out' with arguments from the 'MkldnnCPU' backend. 
```

Having the flexibility to disable layout propagation pass allows us to workaround the issue, while figuring out better ways to integrate oneDNN fuser with Dynamo AOTAutograd for model training.

### CODE REVIEW

**Comment by wenzhe-nrv** [comment]
@chunyuan-w what's your thought about adding this option? if you think it makes sense to add, could you please review the code? Thanks.

**Comment by chunyuan-w** [comment]
> @chunyuan-w what's your thought about adding this option? if you think it makes sense to add, could you please review the code? Thanks.

Could you please help elaborate on the PR description the motivation for this change? I feel this is more like a workaround. It might be better to figure out a way to fix the layout propagation when we have both FW and BW graph.

**Comment by wenzhe-nrv** [comment]
@chunyuan-w @jgong5 I have updated with background and motivation on the top.

**Comment by jgong5** [comment]
If forward graph and backward graph are compiled separately, why are there MkldnnCPU tensors output from the forward graph? I suppose only intermediate tensors might take MkldnnCPU layout due to layout propagation, not input/output tensors of the graph?

**Comment by wenzhe-nrv** [comment]
@jgong5 What you said makes sense. Sounds like there's a bug in the bridge or its integration with AOTAutograd. It's an intermittent issue that I found it hard to create a repro. I'm doing something debugging and will report in a separate issue. 

Meanwhile, just for adding the flexibility of switching a pass are similar to some existing functions for JIT passes, such as `torch._C._jit_set_autocast_mode()`.   https://github.com/pytorch/pytorch/blob/12b2f70a89494b2ad374aaa16b8fdbf16da66e57/torch/csrc/jit/python/init.cpp#L506

**Comment by wenzhe-nrv** [comment]
fix with #88496

**Pull request closed without merging**
