### PR TITLE
Use a zipfile for serialization

### PR DESCRIPTION
**Pull request by driazati**
Implements #26567

TODO:
* Testing new format
* Backwards compatibility testing

### CODE REVIEW

**Comment by jamesr66a** [comment]
Does this happen to fix #24045?

**Comment by driazati** [comment]
> Does this happen to fix #24045?

It does since the tensors can be eagerly loaded

**Comment by resistor** [comment]
Is there any hope of actually unifying the implementation between this and TorchScript serialization?

**Comment by resistor** [comment]
Also, have you tested this with models containing very large tensors?  My recollection is that Python's `zipfile` is pretty slow.

**Comment by driazati** [comment]
> Is there any hope of actually unifying the implementation between this and TorchScript serialization?

We probably won't ever have 1 implementation since `torch.save` can save any Python object since it uses `pickle` under the hood. The TorchScript pickler only supports the subset of Python objects that are `IValue`s, so there'll always be a gap between the two. The saved files themselves would be made very similar with the change.

> Also, have you tested this with models containing very large tensors? My recollection is that Python's zipfile is pretty slow.

It's a little slower for `save` and much slower for `load`

```
Via pickle
save 1.8885936219999166
load 0.37009724900008223

Via zipfile
save 2.4364204280000195
load 1.8249811819996467
```

for

```python
class MyBigModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.x = torch.nn.Parameter(torch.randn(334, 334, 10, 2))
        self.y = torch.nn.Parameter(torch.randn(334, 334, 10, 2))
        self.z = torch.nn.Parameter(torch.randn(334, 334, 10, 2))
        self.az = torch.nn.Parameter(torch.randn(334, 334, 334, 2))

    def forward(self, x):
        return self.x + self.y + self.z + self.az
```

**Comment by driazati** [comment]
Coming back to this, it seems like the Python `zipfile` is indeed slow, but we can achieve pretty much the same performance as the current method by using the `miniz` zip implementation we already package in PyTorch, and disabling CRC32 generation on the zip (tools like `unzip` will complain the CRC is bad but will still work fine).

**Comment by resistor** [comment]
> Coming back to this, it seems like the Python `zipfile` is indeed slow, but we can achieve pretty much the same performance as the current method by using the `miniz` zip implementation we already package in PyTorch, and disabling CRC32 generation on the zip (tools like `unzip` will complain the CRC is bad but will still work fine).

cc @jjlilley  who was looking at makes CRC32 faster.

**Comment by jjlilley** [comment]
A few comments, having looked a bit at this in context of rpc:
 1) The mz_crc32() impl in this file is unbearly slow for prod data. folly's crc32() impl based on SSE is roughly 40x faster. 
    We started using folly::crc32 inside fb (D17814297), but yes, we need something not snail slow for the open source release. We could potentially pull in folly's checksum impl - not sure if there's a better solution.

  2)  In The 40x speedup helps quite a bit in my profiles, but it still is an issue for some workloads (huge tensors, with little metadata/pickling).

  3) If there's consensus to remove CRC checks, I don't necessarily have an objection in principle.
    Not sure if there are others who do? Some people liked the idea about using external zip utilities, but this might be overrated.
    If we go that route, we should define MINIZ_DISABLE_ZIP_READER_CRC32_CHECKS (so that old data works with the new reader). And perhaps also use USE_EXTERNAL_MZCRC, with an external impl linked in, to avoid forking miniz.c unnecessarily.

**Comment by jjlilley** [comment]
Curious if there's more movement/discussion in this regard?

As a first step, does it make sense to just start by disabling crc32 checks in torch::load(), e.g.
  https://github.com/pytorch/pytorch/pull/28858

I suspect we're only doing the crc32 torch::load() checks because they default on, and meanwhile this saves a good chunk of cpu time in the open source pytorch.

We might want to disable crc calculations in torch::save() as well, but that seems like it might require a bit more consensus due to the potential zip compatibility issue.

**Comment by driazati** [comment]
From offline discussions we need to maintain a standards-complaint zip file, so we should replace the default miniz CRC with a faster one from somewhere. Disabling the checks on load is probably fine since it shouldn’t have any user visible impacts.

Other than that this PR is almost ready to go.

**Comment by jjlilley** [comment]
Ah, thanks for the update about your offline discussions; I had it on a list that I intended to check back.

folly's crc impl  based on SSE  is ~40x faster, so improvements are definitely possible :)

**Pull request closed without merging**
