### PR TITLE
[After fix] Reuse constant and bump bytecode to v5

### PR DESCRIPTION
**Pull request by cccclai**
Reintroduce sharing constant between bytecode and torchscript (same as #58629) after the fix #59642 

Test it by:
```
model_path = "/Users/chenlai/Documents/pytorch/reuse_constant/tmp/other_models/model_GKzegAqmfRoYTygDACAlZhsBGFcRbmQwAAAA.ptl"
# model_path = "/Users/chenlai/Documents/pytorch/reuse_constant/tmp/other_models/model_GICWmAARE1pJ3yQEAFk58lqFfzVGbgdIAAAi.ptl"
model_resave_path = "/Users/chenlai/Documents/pytorch/reuse_constant/tmp/other_models/model_GKzegAqmfRoYTygDACAlZhsBGFcRbmQwAAAA_resave.ptl"

for i in range(20):
    print(i)
    m = torch.jit.load(model_path)
    m._save_for_lite_interpreter(model_resave_path)
    mm = _load_for_lite_interpreter(model_resave_path)
```

Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#59722 [After fix] Reuse constant and bump bytecode to v5**

Differential Revision: [D29002345](https://our.internmc.facebook.com/intern/diff/D29002345)

### CODE REVIEW

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29002345).

**Review by iseeyuan — APPROVED** [review]
LGTM

**Review by raziel — APPROVED** [review]

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29002345).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29002345).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29002345).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29002345).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29002345).

**Pull request closed without merging**
