### PR TITLE
Call c10 cuda op from test_torch

### PR DESCRIPTION
**Pull request by smessmer**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#16692 Call c10 cuda op from test_torch**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13935403/)

Differential Revision: [D13935403](https://our.internmc.facebook.com/intern/diff/D13935403/)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
I'm going to approve this, but note that for comparison between CPU and GPU reference implementations, we already have more structured facilities for this (than just banging out the test manually). I'm not exactly sure how to fit in the c10 ops here, but as you start growing more, make sure to figure it out.

**Comment by smessmer** [comment]
agreed

**Comment by ezyang** [comment]
I'm not sure how you managed it, but this broke a pinned memory test:

```
Mar 01 20:03:02 ======================================================================
Mar 01 20:03:02 FAIL: test_pin_memory (__main__.TestTorch)
Mar 01 20:03:02 ----------------------------------------------------------------------
Mar 01 20:03:02 Traceback (most recent call last):
Mar 01 20:03:02   File "test_torch.py", line 9372, in test_pin_memory
Mar 01 20:03:02     self.assertFalse(x.is_pinned())
Mar 01 20:03:02 AssertionError: True is not false
Mar 01 20:03:02 
Mar 01 20:03:02 ----------------------------------------------------------------------
```

**Comment by ezyang** [comment]
Tests failed in PR. Reverting.

**Pull request closed without merging**
