### PR TITLE
[LTC] Upstream LTCTensorImpl

### PR DESCRIPTION
**Pull request by alanwaketan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70069
* #70066
* __->__ #70062

Summary:
This commit upstreams LTCTensorImpl from the lazy_tensor_staging branch.
It inherits from c10::TensorImpl and thus manages the lifetime/storage
of LazyTensor.

Test Plan:
./build/bin/test_lazy --gtest_filter=LazyTensorImplTest.*

Differential Revision: [D33171186](https://our.internmc.facebook.com/intern/diff/D33171186)

### CODE REVIEW

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33171186).

**Review by desertfire — APPROVED** [review]
LGTM, but please fix the lint errors.

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33171186).

**Comment by alanwaketan** [comment]
> LGTM, but please fix the lint errors.

Thanks, Bin. But I don't think I can fix the `const_cast` warning. Do you know how to bypass the linter?

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33171186).

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33171186).

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33171186).

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33171186).

**Pull request closed without merging**
