### PR TITLE
Add `annotation_linter` that finds and updates old-style Python typing

### PR DESCRIPTION
**Pull request by rec**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #141819

### CODE REVIEW

**Comment by Skylion007** [comment]
This isn't necessary. Ruff will handle the import upgrade automatically as soon as we raise the minimum Python version to py39.

**Comment by Skylion007** [comment]
Furthermore, I tried to manually do this upgrade at one point and it broke JIT IIRC.

**Comment by Skylion007** [comment]
You need to enable another rule to auto import future import annotations for the ruff rule. You can also easily enable a specific subset of the codebase if you want.

**Comment by rec** [comment]
Hey, @Skylion007 - thanks for all your excellent feedback so far (I'm testing the results of another comment of yours right now).

So I'm a bit embarrassed to admit that I don't fully understand either of the two parts in this comment! 🙁 

---

> You need to enable another rule to auto import future import annotations for the ruff rule. 

Are you proposing to use `ruff` instead to add/check for this `from __future__ import annotations` instead of this new tool?

> You can also easily enable a specific subset of the codebase if you want.

This is with respect to `lintrunner` in general?

----

Sorry, I was mostly AFK last week because we're moving house, probably I'm just not starting up properly this AM.

**Comment by rec** [comment]
Glad I didn't spend too much time on this, I found an existing tool that does a better job!

**Comment by rec** [comment]
See https://github.com/pytorch/pytorch/issues/141869 and the attached commits

**Pull request closed without merging**
