### PR TITLE
[ONNX] Deprecate use_external_data_format param from torch.onnx.export() function. (#62257)

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#64382 [ONNX] Deprecate use_external_data_format param from torch.onnx.export() function. (#62257)**
* #64380 [ONNX] Deprecated the example_outputs param from torch.onnx.export() function. (#62815)
* #64373 [ONNX] minor doc improvements and cleanup (#62514)
* #64372 [ONNX] Add supplementary tests and description for custom_opsets param from torch.onnx.export() function. (#62085)
* #64371 [ONNX] Remove strip_doc_string param from torch.onnx.export() function. (#61712)
* #64370 [ONNX] Remove argument _retain_param_name from torch.onnx.export() function. (#61702)

* This `use_external_data_format` parameter is used for large models cannot be exported because of the 2GB protobuf limit.

* When `use_external_data_format` set to True, the model is exported in ONNX external data format, in which case some of the model parameters are stored in external binary files and not in the ONNX model file itself.

* This PR will set this paramter to DEPRECATED and check the model proto sizes by code instead of by user, if the sizes lager than 2GB, then `use_external_data_format = True` automatically.

Co-authored-by: hwangdeyu <dejack953@outlook.com>

Differential Revision: [D30905265](https://our.internmc.facebook.com/intern/diff/D30905265)

### CODE REVIEW

**Comment by vadimkantorov** [comment]
IIRC caffe model protos were sometimes larger than 2Gb, in that case just a warning was shown

**Comment by BowenBao** [comment]
@vadimkantorov do you mean that before or after this PR only a warning was shown? Would it be the correct behavior to export the model with external data format?

**Comment by vadimkantorov** [comment]
I don't know about ONNX, I am just pointing out that protobuf still can support files larger than 2Gb with some workarounds or warnings shown at deserialization time, like was happening when Caffe was around

**Comment by vadimkantorov** [comment]
Or maybe my memorry is tricking me... Maybe protobuf made it actually a hard limit since then...

**Comment by msaroufim** [comment]
@msaroufim has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30905265).

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30905265).

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30905265).

**Pull request closed without merging**
