### PR TITLE
Update xla base tag v06

### PR DESCRIPTION
**Pull request by yeounoh**
We have installed the new `sympy` package requirement in the XLA CI base image. Bumping up the version tag.

cc @bdhirsh

### CODE REVIEW

**Comment by JackCaoG** [comment]
@malfet

**Review by seemethere — APPROVED** [review]

**Comment by seemethere** [comment]
Looks like this is currently failing the xla test?

**Review by malfet — APPROVED** [review]

**Comment by yeounoh** [comment]
> Looks like this is currently failing the xla test?

`[  FAILED  ] AtenXlaTensorTest.TestQR (734 ms)` we are investigating this failure, due to `mkl` version mismatch. I will wait til we get a hold of this and pass the xla test before merging.

**Comment by yeounoh** [comment]
We have temporarily disabled the problematic tests to fix the CI in the downstream. Let's wait a bit more here, until we fix the  `mkl` issue & re-enable the tests before merging. We may want to skip `v0.5` and go straight to `v0.6` cc @steventk-g @JackCaoG

**Comment by yeounoh** [comment]
Hi @malfet I was able to pass the xla test (all green), with `v0.6` tag. Could you merge this for us?

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
