### PR TITLE
[FSDP] Use `reduce_scatter_tensor()`

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#87240 [FSDP] Use `reduce_scatter_tensor()`**
* #87308 [FSDP][2/N] Fix grad zero vs. `None` edge case
* #87314 [FSDP][1/N] Update `summon_full_params(with_grads)` `None` gradient

Let us silence some more warnings 👍🏼

### CODE REVIEW

**Review by zhaojuanmao — COMMENTED** [review]
somehow did not see it replaces the _reduce_scatter_base() call in fully_sharded_data_parallel.py?

**Comment by awgu** [comment]
> somehow did not see it replaces the _reduce_scatter_base() call in fully_sharded_data_parallel.py?

After Olga's communication hook work, the reduce-scatter is now the one in `torch/distributed/algorithms/_comm_hooks/default_hooks.py`.

@rohan-varma mentioned maybe the call is too non-obvious now. We can refactor later.

**Review by rohan-varma — APPROVED** [review]
LGTM. agree current situation is non-obvious, we should consider refactor.

**Pull request closed without merging**
