### PR TITLE
skip_if_rocm test_rnn in test_c10d_spawn.py

### PR DESCRIPTION
**Pull request by jeffdaily**
Test was added a few months back in #36503 but recently became flaky for ROCm.

CC @ezyang @xw285cornell @sunway513

### CODE REVIEW

**Comment by zhaojuanmao** [comment]
@jeffdaily do we know why it is flaky? I just reverted #40241, will see whether the flakiness is gone, if it is still there, we can skip it and reland #40241

**Comment by jeffdaily** [comment]
@zhaojuanmao no, we do not know why it is flaky, and we also don't know when it started being flaky.  Is it really #40241?

Also, updated this PR.  Used incorrect skip decorator.

**Comment by zhaojuanmao** [comment]
the timeline looks like to be aligned with #40241, but I'm not sure, so reverted it to see whether test will be stable or not

**Review by zhaojuanmao — APPROVED** [review]
maybe related to #40506 change, but we do not know root cause, so it is good to skip it for now

**Comment by jeffdaily** [comment]
How soon can we land this PR?  I'm worried if this test flakiness lingers too long, other PRs will start ignoring our CI signal again.  This test happens early enough in the test suite that it could be hiding later failures.

**Pull request closed without merging**
