### PR TITLE
Docs: update default device description

### LINKED ISSUE #101274: Argument "device" in torch.tensor() behaves differently than that described in doc
### 📚 The doc issue

The doc says "if device=None and data is not a tensor then the result tensor is constructed on the CPU". But after calling "torch.set_default_device(torch.device('cuda'))", torch.tensor(device=None) will convert a numpy array into a GPU tensor.

### Suggest a potential alternative/fix

Maybe "If None, uses the current device for the default tensor type", the description consistent with other functions in [Creation Ops](https://pytorch.org/docs/stable/torch.html#creation-ops).

cc @svekars @carljparker

### PR DESCRIPTION
**Pull request by snorfyang**
Closes #101274

### CODE REVIEW

**Comment by snorfyang** [comment]
cc @albanD

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by snorfyang** [comment]
@albanD Do I need to do something else? I don't think these CI failures are related to my PR.

**Comment by albanD** [comment]
Hey!
Since it is your first PR, the CI needs to be manually approved before running. That's why the merge script cannot find signal for them.
I'll shepherd this in, no worries!

@pytorchbot merge

**Pull request closed without merging**
