### PR TITLE
[Reland] fix some MKL detection issues of CMake

### PR DESCRIPTION
**Pull request by cyyever**
This is reland of PR #94402 that tries to solve the additional link issues.
The  PR #94402 failed because caffe2::mkl had been converted to private dependency while libtorch_cuda_linalg hadn't linked to it explicitly. This is fixed in commit 4373bf0ae3dee32afc178f9d51a4154d6c5904c6
We also replace more references of MKL_LIBRARIES by caffe2::mkl in this PR.

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Looks good to me, if it passes binary builds testing, though please add an explanation to PR description, what have changed since the last time.

**Comment by kit1980** [comment]
@cyyever is this still relevant?

**Comment by cyyever** [comment]
@kit1980 It almost works except on intel Macos, but I don't have that machine at hand to investigate the issue

**Comment by atalman** [comment]
Here is the reference for test revert passing: https://github.com/pytorch/pytorch/actions/runs/4577459062/jobs/8082897654?pr=98086

**Comment by CuiYifeng** [comment]
Hi @cyyever, why was this PR reverted? I want to move `caffe2::mkl` from `Caffe2_PUBLIC_DEPENDENCY_LIBS` to `Caffe2_DEPENDENCY_LIBS` recently. Glad to hear your advice.

**Comment by CuiYifeng** [comment]
@cyyever Maybe we can let components rely on MKL link it explicitly. I will have a try. Thanks for the reminder.

**Comment by cyyever** [comment]
@CuiYifeng I tried several days and failed, hope that you success this time..

**Pull request closed without merging**
