### PR TITLE
Fix G001,G002,G003 in logs to % syntax

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #97812

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by kiukchung — APPROVED** [review]
LGTM for torchelastic changes!

**Comment by ezyang** [comment]
I think the primary potential bikeshed is if people want to do https://docs.python.org/3/howto/logging-cookbook.html#formatting-styles so that we can do the more modern curly format. I suppose that can always be done retroactively though.

**Review by albanD — COMMENTED** [review]
Why this over f strings?

**Comment by Skylion007** [comment]
This is PR also isn't banning fstrings etc. Just banning `.format` interpolations to start with.

**Review by malfet — APPROVED** [review]
LGTM. Do you know if there is a linter already that forces callables in `TestUtils.assertEqual` etc?

**Comment by ezyang** [comment]
@malfet no lol. But we typically don't specify msg so not a big deal?

**Comment by ezyang** [comment]
I'm rerequesting reviews as I "finished" transforming everything, and the refactor was done by hand so it should get an eyeball over.

**Review by mlazos — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Review by Skylion007 — APPROVED** [review]

**Pull request closed without merging**
