### PR TITLE
[PyTorch] Avoid initializing storage for empty Optionals

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #77858

We don't need to initialize for the non-constexpr case ever, or in the constexpr case after C++20.

Differential Revision: [D36519379](https://our.internmc.facebook.com/intern/diff/D36519379/)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Review by malfet — APPROVED** [review]
I remember we had problem with CUDA-10.2 and constexprs, adding `ciflow/trunk` to see if it will still compile

**Comment by swolchok** [comment]
@malfet can you confirm that the 4 failures on this diff aren't blocking? Two of them are initialization-order-fiasco and look unrelated, one looks like a timeout while building, and one is clearly unrelated backward compat failure.

**Comment by malfet** [comment]
> @malfet can you confirm that the 4 failures on this diff aren't blocking? Two of them are initialization-order-fiasco and look unrelated, one looks like a timeout while building, and one is clearly unrelated backward compat failure.

I don't know about the previous failures, but latest ones indeed look related, as one can observe in the HUD history: https://hud.pytorch.org/hud/pytorch/pytorch/master/1?name_filter=asan

**Comment by swolchok** [comment]
looks likely that the change caused a pre-existing bug to start getting caught by ASAN. investigating

**Pull request closed without merging**
