### PR TITLE
Extend sign-compare warnings to gcc (take 2)

### PR DESCRIPTION
**Pull request by malfet**
Remove `-Wno-sign-compare` option for GCC
Suppress erroneous sign-compare warning in `c10::greater_than_max`(see  https://godbolt.org/z/Tr3Msnz99)
Fix sign-compare in torch/deploy,  `caffe2::QTensor::dim32()` and `generate_proposals_op_test.cc`

### CODE REVIEW

**Review by osalpekar — APPROVED** [review]

**Comment by malfet** [comment]
Not picking https://github.com/pytorch/pytorch/pull/75293/commits/3b36a18efff041f24b72848ebf304ab07f277bc7 there yet to see that it fails to compile nvfuser tests

**Comment by malfet** [comment]
For some reason, compiling `torch/csrc/cuda/Storage.cpp` fails with `-Werror`:
```
/opt/cache/bin/c++  -DBUILDING_TESTS -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DIDEEP_USE_MKL -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTHP_BUILD_MAIN_LIB -DUSE_DEPLOY -DTORCH_ENABLE_LLVM -DUSE_C10D -DUSE_C10D_GLOO -DUSE_C10D_MPI -DUSE_C10D_NCCL -DUSE_CUDA -DUSE_CUDNN -DUSE_DISTRIBUTED -DUSE_EXTERNAL_MZCRC -DUSE_NCCL -DUSE_TENSORPIPE -DUSE_VALGRIND -D_FILE_OFFSET_BITS=64 -I/var/lib/jenkins/workspace/torch/csrc/deploy/interpreter/cpython/include/python3.8 -I/var/lib/jenkins/workspace/build/aten/src -I/var/lib/jenkins/workspace/aten/src -I/var/lib/jenkins/workspace/build -I/var/lib/jenkins/workspace -isystem /var/lib/jenkins/workspace/build/third_party/gloo -isystem /var/lib/jenkins/workspace/cmake/../third_party/gloo -isystem /var/lib/jenkins/workspace/cmake/../third_party/googletest/googlemock/include -isystem /var/lib/jenkins/workspace/cmake/../third_party/googletest/googletest/include -isystem /var/lib/jenkins/workspace/third_party/protobuf/src -isystem /opt/conda/include -isystem /var/lib/jenkins/workspace/third_party/gemmlowp -isystem /var/lib/jenkins/workspace/third_party/neon2sse -I/var/lib/jenkins/workspace/cmake/../third_party/benchmark/include -isystem /var/lib/jenkins/workspace/cmake/../third_party/eigen -isystem /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent -isystem /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include -isystem /usr/lib/openmpi/include/openmpi -isystem /usr/lib/openmpi/include -I/opt/llvm/include -I/var/lib/jenkins/workspace/cmake/../third_party/cudnn_frontend/include -isystem /usr/local/cuda/include -I/var/lib/jenkins/workspace/third_party/onnx -I/var/lib/jenkins/workspace/build/third_party/onnx -I/var/lib/jenkins/workspace/third_party/foxi -I/var/lib/jenkins/workspace/build/third_party/foxi -isystem /var/lib/jenkins/workspace/third_party/ideep/mkl-dnn/third_party/oneDNN/include -isystem /var/lib/jenkins/workspace/third_party/ideep/include -I/var/lib/jenkins/workspace/build/nccl/include -I/var/lib/jenkins/workspace/torch/csrc/distributed -isystem /opt/conda/include/python3.7m -I/var/lib/jenkins/workspace/torch/.. -I/var/lib/jenkins/workspace/torch/../aten/src -I/var/lib/jenkins/workspace/torch/../aten/src/TH -I/var/lib/jenkins/workspace/build/caffe2/aten/src -I/var/lib/jenkins/workspace/build/third_party -I/var/lib/jenkins/workspace/torch/../third_party/valgrind-headers -I/var/lib/jenkins/workspace/torch/../third_party/gloo -I/var/lib/jenkins/workspace/torch/../third_party/onnx -I/var/lib/jenkins/workspace/torch/../third_party/flatbuffers/include -I/var/lib/jenkins/workspace/torch/csrc -I/var/lib/jenkins/workspace/torch/csrc/api/include -I/var/lib/jenkins/workspace/torch/lib -I/var/lib/jenkins/workspace/torch/lib/libshm -I/var/lib/jenkins/workspace/torch/../third_party/fmt/include -isystem /var/lib/jenkins/workspace/cmake/../third_party/pybind11/include   -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Werror -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -fPIC   -DCAFFE2_USE_GLOO -DTH_HAVE_THREAD -Wno-unused-variable -fno-strict-aliasing -Wno-write-strings -Wno-strict-aliasing -fno-gnu-unique -std=gnu++14 -o CMakeFiles/torch_python_obj.dir/csrc/cuda/Storage.cpp.o -c /var/lib/jenkins/workspace/torch/csrc/cuda/Storage.cpp
In file included from /var/lib/jenkins/workspace/c10/util/Half.h:14:0,
                 from /var/lib/jenkins/workspace/c10/core/ScalarType.h:5,
                 from /var/lib/jenkins/workspace/c10/core/StorageImpl.h:4,
                 from /var/lib/jenkins/workspace/c10/core/Storage.h:3,
                 from /var/lib/jenkins/workspace/c10/core/TensorImpl.h:8,
                 from /var/lib/jenkins/workspace/c10/core/GeneratorImpl.h:12,
                 from /var/lib/jenkins/workspace/aten/src/ATen/core/Generator.h:22,
                 from /var/lib/jenkins/workspace/torch/csrc/Generator.h:5,
                 from /var/lib/jenkins/workspace/torch/csrc/THP.h:18,
                 from /var/lib/jenkins/workspace/torch/csrc/cuda/THCP.h:5,
                 from /var/lib/jenkins/workspace/torch/csrc/cuda/Storage.cpp:7:
/var/lib/jenkins/workspace/c10/util/TypeSafeSignMath.h: In instantiation of 'constexpr bool c10::greater_than_max(const T&) [with Limit = long unsigned int; T = long int':
/var/lib/jenkins/workspace/c10/util/Half.h:464:32:   required from 'typename std::enable_if<(std::is_integral<_Tp2>::value && (! std::is_same<From, bool>::value)), bool>::type c10::overflows(From) [with To = long unsigned int; From = long int; typename std::enable_if<(std::is_integral<_Tp2>::value && (! std::is_same<From, bool>::value)), bool>::type = bool]'
/var/lib/jenkins/workspace/torch/csrc/generic/StorageMethods.cpp:113:3:   required from here
/var/lib/jenkins/workspace/c10/util/TypeSafeSignMath.h:78:28: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   return can_overflow && x > std::numeric_limits<Limit>::max();
                          ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

```

**Comment by malfet** [comment]
Can repro it with any version of gcc compiler on godbolt: https://godbolt.org/z/Tr3Msnz99
Which boils down to gcc being unable to account for shortcircuit while evaluating line 78 of
https://github.com/pytorch/pytorch/blob/b1310b463fca7a10a0e94a47aa11523906ef4e1e/c10/util/TypeSafeSignMath.h#L74-L79
Will modify a PR to add suppression there

**Comment by malfet** [comment]
All builds are green (and tests are failing due to master regression) Merging

**Comment by malfet** [comment]
Added https://github.com/pytorch/pytorch/pull/75544/commits/1b0c9a8fc17e56437eda775b29e0c1a9d138aedf to fix caffe2 sign-unsigned violation

**Pull request closed without merging**
