### PR TITLE
Enable opting out of experiments even when they're being rolled out

### LINKED ISSUE #138099: [Runner Determinator] Enable explicitly opting out of an experiment even when it's being rolled out
Use case: We've ramped up the LF fleet, but because for testing someone wants to ensure their workflow runs on the Meta fleet

### PR DESCRIPTION
**Pull request by ZainRizvi**
Enables opting out of specific experiments in the runner determinator

To opt out:
1. Go to the tracking issue: https://github.com/pytorch/test-infra/issues/5132
2. In the entry by your name, enter the experiment name, prefixed with a `-`.  For example, to opt out of the LF fleet you could enter `@ZainRIzvi,-lf`

This lets you simultaneously be opted into some experiments and opted out of others.

While the `disable-runner-experiments` label offers an option to disable all experiments on a given PR, this one lets you disable a selected set of experiments across all your PRs.

Fixes https://github.com/pytorch/pytorch/issues/138099

### CODE REVIEW

**Review by zxiiro — APPROVED** [review]
I think this is a good idea. Just a typo I spotted but otherwise looks fine. LGTM

**Comment by jeanschmidt** [comment]
LGTM but,

I would like to point out that there is a bug: if a user is both opted-in AND opted-out, he'll get the message that he opted in, and the message he opted out, and no experiment would run for him.

Kind of confusing. As we can't validate the comment on the issue, can we add a warning if this situation ever reaches, and if so, get a warning that explains the issue and shows what is the action that will be taken (in or out)?

**Review by jeanschmidt — APPROVED** [review]

**Comment by jeanschmidt** [comment]
...also, I know this is overthinking, but a validation on experiment names, that they should not start with `-`, do we have that?

**Comment by ZainRizvi** [comment]
> LGTM but,
> 
> I would like to point out that there is a bug: if a user is both opted-in AND opted-out, he'll get the message that he opted in, and the message he opted out, and no experiment would run for him.
> 
> Kind of confusing. As we can't validate the comment on the issue, can we add a warning if this situation ever reaches, and if so, get a warning that explains the issue and shows what is the action that will be taken (in or out)?

It's setup to default to opting out users, but I can see how it could be a bit unclear to see that in the code. Reorganizing it to make that bit clearer and adding logging

**Pull request closed without merging**
