### PR TITLE
[dynamo] Support object.__new__ call

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #133742
* __->__ #133746
* #133747
* #133745

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by Skylion007 — COMMENTED** [review]
Should use "is" instead of equality check here, object is a singleton.

**Review by Skylion007 — APPROVED** [review]
Looks good to me.

Actually if you could handle the other "==" -> is in this method in the PR stack, that would be super helpful. Thanks.

**Comment by anijain2305** [comment]
Will do in a few hours.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
