### PR TITLE
Use storage.cpu() for moving storage to CPU in serialization.

### LINKED ISSUE #46020: torch.save w/ _use_new_zipfile_serialization=True corrupts state_dict
## 🐛 Bug

In one of the `transformers` tests `torch.save` w/ the new `_use_new_zipfile_serialization=True` corrupts the data in the state_dict resulting in load returning bogus data that wasn't there on save. 

## To Reproduce

It seems to happen with the specific data only, so at the moment requires a specific sub-test:
```
git clone https://github.com/huggingface/transformers
cd transformers
pip install -e .[dev]
CUDA_LAUNCH_BLOCKING=1 USE_CUDA=1 pytest tests/test_modeling_bert.py::BertModelTest::test_head_pruning_integration
```

Specifically, we have https://github.com/huggingface/transformers/blob/960faaaf28b198c0dd2fcb288fa336a846aed398/src/transformers/modeling_utils.py#L729

```
        torch.save(state_dict, output_model_file) #, _use_new_zipfile_serialization=False)

        k = "embeddings.position_ids"
        if k in state_dict: print("SAVE\n", state_dict[k])

        state_dict = torch.load(output_model_file)
        if k in state_dict: print("LOAD\n", state_dict[k])
```
(I added the debug prints and load code as part of debug as the problem wasn't manifesting under the debugger)

What goes in with saving the key `embeddings.position_ids`:

```
0, 1, 2,..., 511
```

What comes out after load: 

```
512, 0, 1, 2, ..., 510
```

That 512 shouldn't be there. It leads to a CUDA assert and the whole test suite goes kaboom.

Note 1: One more important detail. if `output_model_file` is set manually directly inside save/load code above I replace `output_model_file` - everything works fine. If it is done via the test (regardless whether it does it via tempfile.TemporaryDirectory()` or a hardcoded path it fails.

Note 2: If I run the code under debugger, the problem doesn't manifest itself.

These 2 peculiarities are very odd. Is there a race condition here and somehow one or the other changes the timing?

Also, if I remove all keys but "embeddings.position_ids" the data doesn't get corrupted. So it has to do with a specific data this state_dict happens to have.

Many thanks to @ptrblck for doing most of the heavy lifting, debugging this on slack.

t/a @jamesr66a 

## Environment

The problem happens with any pytorch-1.6+ (since `_use_new_zipfile_serialization=True` has been enabled). all is good with pytorch-1.5. And a variety of nvidia drivers were experimented with with no difference in behavior.

```
PyTorch version: 1.8.0.dev20201007
Is debug build: True
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X

Nvidia driver version: 455.23.05
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-lightning==0.9.1rc3
[pip3] torch==1.8.0.dev20201007
[pip3] torchtext==0.6.0
[pip3] torchvision==0.8.0.dev20201007
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.0.221             h6bb024c_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] numpy-base                1.19.1           py38hfa32c7d_0
[conda] pytorch                   1.8.0.dev20201007 py3.8_cuda11.0.221_cudnn8.0.3_0    pytorch-nightly
[conda] pytorch-lightning         0.9.1rc3                  dev_0    <develop>
[conda] torchtext                 0.6.0                    pypi_0    pypi
[conda] torchvision               0.8.0.dev20201007      py38_cu110    pytorch-nightly
```

cc @ezyang @gchanan @zou3519 @mruberry

### PR DESCRIPTION
**Pull request by t-vi**
As reported in #46020, something seems to go wrong with the storage._write_file method used with a BytesIO and a GPU buffer.
Given that we were going to create the intermediate buffer (currently via BytesIO) anyway, we might as well use storage.cpu() to move the storage to the CPU. This appears to work better.

This is a hot fix, further investigation is highly desirable. In particular, I don't have a reproducing test to show.

Fixes #46020

### CODE REVIEW

**Comment by t-vi** [comment]
@jamesr66a

**Comment by t-vi** [comment]
I could be wrong, but on further inspection it would seem that the new method might even be a bit of an optimization: going via write_file incurs an additional copy compared to the method used here: In writeFileRaw the cudaMemcpy to a new cpu buffer and then by using BytesIO.write, while now we just copy to CPU.

**Comment by t-vi** [comment]
I added commentary on the root problem to the bug report. This indicates that I indeed fix the bug here and as discussed above, I think this saves a memory copy, too, so I'd suggest to use this fix.

**Comment by gchanan** [comment]
really nice digging!

I don't really see how this avoids the copy -- isn't the writeFile buffer copy just moved to the `cpu()` copy?  Also, given we are about to do a release, changing serialization seems a little risky -- it seems reasonable to me to do a stack where you fix the bug, we cherry-pick that to 1.7, and we then make your change here to master.

**Comment by gchanan** [comment]
For a reproduction -- maybe we should just fix the error checking of `_writeFile` a bit (your suggest of moving to pybind is better), so we can at least get an error on regression.

**Comment by gchanan** [comment]
I haven't verified this yet, but I'm guessing https://github.com/pytorch/pytorch/pull/46036 will blow up the serialization tests, so that and this together should convince us that the issue is fixed.

**Comment by t-vi** [comment]
Yeah, but we skip the other copy from cpu to writing into ByteIO. I'm reasonably certain this is the exact right thing, but you could also just add the False.
I had this fix before doing the analysis posted to the issue.

**Comment by gchanan** [comment]
The thing I was wondering about is the change of assumption, i.e. now we assume that `cpu()` is implemented for all storages (it's clearly true for cuda).  It's almost certainly true for things like QuantizedCPU, etc. but I'm not 100% sure off the top of my head.

**Comment by t-vi** [comment]
Good catch, but based on the test results, anything that has serialization tests would have .cpu().

**Comment by t-vi** [comment]
@gchanan keep or trash this?

I still think it is superior to eliminate the BytesIO additional copy, but obviously your fix might be more conservative.

**Comment by t-vi** [comment]
Well, looks like we keep the copying.

**Comment by gchanan** [comment]
@t-vi I think we should merge this (I wanted to get the more conservative one in first so we could cherry-pick it to the release branch).

**Comment by gchanan** [comment]
do you want to fix the conflict or should I?

**Review by gchanan — APPROVED** [review]

**Comment by gchanan** [comment]
Nice, thanks for this!

**Pull request closed without merging**
