### PR TITLE
Add bf16 and change header file include path

### PR DESCRIPTION
**Pull request by guangyey**
# Motivation
We would like to add the bfloat16 header file to PyTorch to make PyTorch and Intel extension for PyTorch support the bfloat16 data type. 

# Solution
- Note that bfloat16 is an Intel extension implementation in the DPC++ compiler instead of standard SYCL, we need to guarantee the bfloat16 header can be included only using the DPC++ compiler. Please refer to [sycl 2020 feature test macros](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_feature_test_macros). Intel DPC++ compiler uses [SYCL_EXT_ONEAPI_BFLOAT16_MATH_FUNCTIONS](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_oneapi_bfloat16_math_functions.asciidoc) to check bfloat16 feature.
- Refer to [intel/llvm](https://github.com/intel/llvm/blob/59dd38795c7557a779ca38cd27df21a40c7b3c45/clang/lib/Basic/Version.cpp#L129). SYCL_LANGUAGE_VERSION is defined in both SYCL 1.2.1 and SYCL 2020. But only CL_SYCL_LANGUAGE_VERSION is defined in SYCL 1.2.1. So we should check CL_SYCL_LANGUAGE_VERSION first for SYCL 1.2.1. If it is not defined then check SYCL_LANGUAGE_VERSION for SYCL 2020. This will guarantee to be compatible with SYCL 1.2.1 and SYCL 2020.

# Additional
No need UT.

### CODE REVIEW

**Comment by guangyey** [comment]
Hi @ezyang please help to review this code. Thanks.

**Comment by ezyang** [comment]
How is this getting tested. At the very least this needs to be exercised by a build to test it doesn't have compile errors. But I don't think we have a SYCL config right now?

**Review by ezyang — APPROVED** [review]

**Comment by guangyey** [comment]
> How is this getting tested. At the very least this needs to be exercised by a build to test it doesn't have compile errors. But I don't think we have a DPC++ config right now?

Yes, you are right. There are no building envs to test DPC++ code in PyTorch CI. We can test it in our extension.

**Pull request closed without merging**
