### PR TITLE
Back out "Add PyObject preservation for UntypedStorage (#97470)"

### PR DESCRIPTION
**Pull request by 842974287**
Summary:
Original commit changeset: c24708d18ccb

Original Phabricator Diff: D46159983

Test Plan: SL tests and CI

Differential Revision: D46284986

### CODE REVIEW

**Review by DanilBaibak — APPROVED** [review]

**Comment by kurtamohler** [comment]
What was the reason for reverting this? I'd like to try to fix it as soon as possible

**Comment by DanilBaibak** [comment]
The PR was merged, not reverted.

**Comment by ezyang** [comment]
This is a revert PR

**Comment by kurtamohler** [comment]
I meant, what was the reason for reverting #97470 through merging this PR?

**Comment by DanilBaibak** [comment]
The diff [D46284986 ](https://www.internalfb.com/diff/D46284986) was merged internally.

**Comment by kurtamohler** [comment]
I'm not a Meta employee, so I don't have access to [D46284986](https://www.internalfb.com/diff/D46284986). Presumably, my PR #97470 caused some Meta internal failure, so it was reverted, is that right? I would like to help fix it if I can

**Comment by DanilBaibak** [comment]
Hey @842974287! Could you please clarify what is the problem with the changes.

**Comment by kurtamohler** [comment]
Edward shared a backtrace with me, so I'll start looking into it. But any extra info would no doubt be helpful

**Comment by kurtamohler** [comment]
Could someone provide a minimal reproducer? The cuda tests in multipy don't exercise the failing function `c10::newStorageImplFromRefcountedDataPtr`, and I haven't been able to reproduce the failure just from the information in the trace

cc @842974287 @ezyang

**Comment by ezyang** [comment]
This is not going to be easy, because it looks like the person who bisected the failure did it via a big end-to-end model run. However, there is an unrelated separate problem that was also pinned to this PR, looks like this:

```
TypeError: TypedStorage.__init__ received an invalid combination of arguments. Expected one of:
* (*, torch.device device, torch.dtype dtype)
* (int size, *, torch.device device, torch.dtype dtype)
* (Sequence data, *, torch.device device, torch.dtype dtype)
* (*, UntypedStorage wrap_storage, torch.dtype dtype)
Argument 'wrap_storage' must be UntypedStorage, but got <class 'dict'>
```

Not sure if this is enough to work out the other problem...

**Comment by ezyang** [comment]
Also, I looked at the SEV report for this problem, and actually it is not a failure per se; it is an OOM. So it is not surprising that it doesn't directly repro. The author tracked it down to

```
diff --git a/fbcode/caffe2/caffe2/core/context_gpu.cu b/fbcode/caffe2/caffe2/core/context_gpu.cu
--- a/fbcode/caffe2/caffe2/core/context_gpu.cu
+++ b/fbcode/caffe2/caffe2/core/context_gpu.cu
@@ -521,6 +521,7 @@
     }
     switch (g_cuda_memory_pool_type) {
       case CudaMemoryPoolType::NONE:
+        LOG(INFO) << "aaaaaaaaaaaaaaaa this is bad!";
         if (nbytes != 0) {
           CUDA_ENFORCE(cudaMalloc(&ptr, nbytes));
         }
```

For some reason, the change you made caused Caffe2(!) CUDA tensor memory allocation to start going to cudaMalloc, which is what caused the OOM. Does that give a clue?

The other thing we can do, is I can get you a Workplace guest account and you can directly ping the engineers who helped track down the problem.

**Comment by kurtamohler** [comment]
It seems possible that the `FLAGS_caffe2_cuda_memory_pool` setting is different between the main thread and the new threads in multipy.

https://github.com/pytorch/pytorch/blob/def1b57151687abd585e3000dd10907b8be01266/caffe2/core/context_gpu.cu#L271

Should be simple enough for me to find out

**Comment by kurtamohler** [comment]
So it seems like this is what's happening: When the child threads create a new storage and allocate a CUDA buffer, they don't use a CUDA memory pool like the main thread does, for whatever reason. Potentially, the reason is that the gflag `cuda_memory_pool_type` does not propagate to the child threads (here's where this flag is defined: https://github.com/pytorch/pytorch/blob/def1b57151687abd585e3000dd10907b8be01266/caffe2/core/context_gpu.cu#L26-L30). Then cudaMalloc runs out of memory because it's just not as good at finding available memory, compared to the memory pools.

According to the trace that Edward sent me, this is the line where the OOM error is happening: https://github.com/pytorch/pytorch/pull/97470/files#diff-7a1737781f1ae70a347a8edc74e58f5cb8f91855554e5307e39f1c300467bcb1R70-R74

I believe that's the only place where my PR added a new buffer allocation for child threads. And that allocation isn't even necessary--the data buffer gets replaced on the very next line with the shared buffer that was allocated on the main thread. So I think it seems likely that I can fix the issue by just avoiding the unnecessary temporary buffer allocation.

**Comment by ezyang** [comment]
Internal note, the storage problem is reproed with

```
flow-cli clone f443168831 --run-as-secure-group oncall_model_store --entitlement ai_infra_training_rnd_tc
```

**Comment by kurtamohler** [comment]
#109039 relanded this

**Pull request closed without merging**
