### PR TITLE
[quant][graphmode] backend_config_dict in standalone module api supports fallback to parent config

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70152
* #70287
* #70286
* __->__ #70277
* #70151

Summary:
when the backend_config_dict field in standalone module api is None, we'll fall back to
use the backend_config_dict of parent
e.g.
```
prepare_custom_config_dict = {
  "standalone_module_name": [("standalone", qconfig, prepare_config, None)]
}

in this case module "standalone" will use parent's backend_config_dict during prepare

TODO:
currently the convert still needs to take a backend_config_dict argument, maybe we can remove this argument and get the config
from prepared model in the future
```

Test Plan:
regression test: python test/test_quantization.py TestQuantizeFx
real test example see next PR: https://github.com/pytorch/pytorch/pull/70152

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D33272853](https://our.internmc.facebook.com/intern/diff/D33272853)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33272853).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33272853).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33272853).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33272853).

**Comment by vkuzo** [comment]
> when the backend_config_dict field in standalone module api is None, we'll fall back to
use the backend_config_dict of parent

thoughts on if this is needed?  I thought "standalone module" meant that there should be no link from that module to the parent, by design.

**Comment by jerryzh168** [comment]
> > when the backend_config_dict field in standalone module api is None, we'll fall back to
> > use the backend_config_dict of parent
> 
> thoughts on if this is needed? I thought "standalone module" meant that there should be no link from that module to the parent, by design.

hmmm, standalone means the code will be quantized by itself (instead of being inlined into the parent module), it is still a part of the parent module, I feel it's still reasonable to have the option to use some configs from parent, these options are mostly for convenience, it allows user to configure the configs for these modules in a single qconfig_dict (might be useful if we call quantization api in other tools like automatic precision selection).

Please let me know if you have a strong preference for not supporting this feature.

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33272853).

**Comment by jerryzh168** [comment]
merging this to previous PR since the previous PR would fail without backend_config_dict from parent being used in child

**Comment by jerryzh168** [comment]
closing this for now, let's continue the discussion in https://github.com/pytorch/pytorch/pull/70151 cc @vkuzo

**Comment by jerryzh168** [comment]
@vkuzo let's discuss this later, planning to land this for now (it can be a separate diff if we decide to change this behavior)

**Comment by vkuzo** [comment]
> > > when the backend_config_dict field in standalone module api is None, we'll fall back to
> > > use the backend_config_dict of parent
> > 
> > 
> > thoughts on if this is needed? I thought "standalone module" meant that there should be no link from that module to the parent, by design.
> 
> hmmm, standalone means the code will be quantized by itself (instead of being inlined into the parent module), it is still a part of the parent module, I feel it's still reasonable to have the option to use some configs from parent, these options are mostly for convenience, it allows user to configure the configs for these modules in a single qconfig_dict (might be useful if we call quantization api in other tools like automatic precision selection).
> 
> Please let me know if you have a strong preference for not supporting this feature.

sure, sounds good

**Pull request closed without merging**
