### PR TITLE
Trivial fix for minor typo in torch.jit._script.py

### LINKED ISSUE #113866: Minor typo in `torch.jit._script.py`
[Link](https://github.com/pytorch/pytorch/blob/f9bf104c641adb64e079ac29695a75c37212236b/torch/jit/_script.py#L747)
```
See :func:`torch.jit.save <torch.jit.save>` witch accepts a file-like object.
```
`witch` should be changed to `which`.

### PR DESCRIPTION
**Pull request by markstur**
Trivial PR to close an open issue regarding a typo.  Looked for more typos in file, but found none.

Fixes #113866

### CODE REVIEW

**Comment by ichxorya** [comment]
Thanks!

Anyway Idk why it didn't passed all test above.

**Review by janeyx99 — APPROVED** [review]
thanks!

**Pull request closed without merging**
