### PR TITLE
[AOTI] Remove the non-ABI-compatible mode (part 1)

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #138047
* __->__ #138009
* #138016
* #137982

Summary: The ABI-compatible mode has been turned on as default in https://github.com/pytorch/pytorch/pull/136534. Removing the non-ABI-compatible logic to greatly simplify the wrapper codegen logic.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @chauhang

Differential Revision: [D64439676](https://our.internmc.facebook.com/intern/diff/D64439676)

### CODE REVIEW

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64439676).

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64439676).

**Review by malfet — COMMENTED** [review]
Do you think it might be considered a BC breaking change? Or is aoti still a prototype?

**Comment by desertfire** [comment]
> Do you think it might be considered a BC breaking change? Or is aoti still a prototype?

Are you referring to the fact that I am removing the abi_compatible flag? In general, I don't think we make any BC promise on Inductor control flags.

For the actual AOTI-generated code, there is no BC breakage because any previously generated model.so will continue to run. There is a FC implication, if a user is using an old version of pytorch at the deployment time, but the previous recommendation is to stick with the same version of pytorch for the compile time and the deploy time, so FC shouldn't be an issue either.

**Review by chenyang78 — APPROVED** [review]
Nice!

**Pull request closed without merging**
