### PR TITLE
[fx2trt] Add version check for ProfilingVerbosity bulider config

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70152
* #70287
* __->__ #70286

Summary:
since `trt.ProfilingVerbosity.LAYER_NAMES_ONLY` is only available in 8.2 and later, we'll add a check so that this initialization code won't error out in earlier versions

Test Plan:
python test/fx2trt/test_quant_trt.py

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D33274058](https://our.internmc.facebook.com/intern/diff/D33274058)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33274058).

**Review by yinghai — APPROVED** [review]
It would be good practice to state why we don't he change in addition to what is being done.

**Comment by jerryzh168** [comment]
> It would be good practice to state why we don't he change in addition to what is being done.

do you mean why we need the change?

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33274058).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33274058).

**Comment by jerryzh168** [comment]
> It would be good practice to state why we don't he change in addition to what is being done.

added the reason to the summary, thanks

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33274058).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33274058).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33274058).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33274058).

**Pull request closed without merging**
