### PR TITLE
Make _CURRENT_TRACING_CONTEXT thread local

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105942

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM!

**Comment by ezyang** [comment]
I'm going to wait for CI to clear, then fix lint and force land

**Review by voznesenskym — APPROVED** [review]

**Pull request closed without merging**
