### PR TITLE
Add missing C10_API to dispatch key TLS setter/getters

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #32782 Replace catchall kernels with CompoundOp dispatch key.
* #32787 Stop using dispatchTypeId to do checks for tensor list unwrap.
* #32734 Centralize addition of "always on" dispatch keys.
* #32729 Make DispatchKeyGuards accept DispatchKey::Undefined
* #32728 Rename DispatchKey::UndefinedTensorId to Undefined
* #32727 Delete copy/move constructors on these RAII guards.
* **#32557 Add missing C10_API to dispatch key TLS setter/getters**
* #32533 Improve documentation in dispatcher; remove unnecessary optional

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D19579853](https://our.internmc.facebook.com/intern/diff/D19579853)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 8eedade5:


**None of the build failures appear to be your fault**.

* **1/1** recognized as flaky :snowflake:
    * Re-run these jobs?


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=8eedade5967defdd9328d4e1daa7f9c7ae1dc53b).

### :snowflake: 1 failure recognized as flaky
The following build failures have been detected as flaky and **may not be your fault**:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4328943) caffe2_onnx_py3_6_clang7_ubuntu16_04_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=90103295) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=90103295)) :snowflake:
<details>
<summary>
<code>Jan 24 00:35:12 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_reshape Fatal Python error: Segmentation fault</code>
</summary>

```
Jan 24 00:35:11 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_constant_fold_transpose_matmul PASSED [ 99%] 
Jan 24 00:35:11 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_constant_fold_unsqueeze PASSED [ 99%] 
Jan 24 00:35:11 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_error_on_data_parallel PASSED [ 99%] 
Jan 24 00:35:11 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_is_in_onnx_export PASSED [ 99%] 
Jan 24 00:35:11 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_strip_doc_string PASSED [ 99%] 
Jan 24 00:35:11 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_validate_dynamic_axes_invalid_input_output_name PASSED [ 99%] 
Jan 24 00:35:12 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_concat PASSED [ 99%] 
Jan 24 00:35:12 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_div PASSED [ 99%] 
Jan 24 00:35:12 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_lstm PASSED [ 99%] 
Jan 24 00:35:12 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_mul PASSED [ 99%] 
Jan 24 00:35:12 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_reshape Fatal Python error: Segmentation fault 
Jan 24 00:35:12  
Jan 24 00:35:12 Current thread 0x00007fc87ed8a700 (most recent call first): 
Jan 24 00:35:12   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 43 in repr_instance 
Jan 24 00:35:12   File "/usr/lib/python3.6/reprlib.py", line 65 in repr1 
Jan 24 00:35:12   File "/usr/lib/python3.6/reprlib.py", line 55 in repr 
Jan 24 00:35:12   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 36 in repr 
Jan 24 00:35:12   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 67 in saferepr 
Jan 24 00:35:12   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 655 in repr_args 
Jan 24 00:35:12   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 736 in repr_traceback_entry 
Jan 24 00:35:12   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 777 in repr_traceback 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by pbelevich — COMMENTED** [review]
It would be nice to have an explanation why we need this change

**Comment by ezyang** [comment]
@pbelevich Without the annotation I can't actually use these methods from an external library, because they get hidden visibility. `C10_API` makes the symbols visible so they can be used externally.

**Comment by pbelevich** [comment]
@ezyang I know that, I don't know who and why is going to use them :)

**Comment by ezyang** [comment]
Oh! I wanted to use them in the example code in https://github.com/pytorch/pytorch/pull/32558 to toggle dispatch keys manually (as I needed some non-standard behavior that the pre-canned guards couldn't do) but I couldn't.

**Review by pbelevich — APPROVED** [review]

**Pull request closed without merging**
