### PR TITLE
add timeout to RPC shutdown

### PR DESCRIPTION
**Pull request by dracifer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #65303

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @gcramer23

Differential Revision: [D31042795](https://our.internmc.facebook.com/intern/diff/D31042795)

### CODE REVIEW

**Comment by dracifer** [comment]
@dracifer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31042795).

**Review by mrshenli — COMMENTED** [review]
The test failure is real. Other than that, do we need a test for this new arg? It can be added to `torch/testing/_internal/distributed/rpc/rpc_test.py`.

```
======================================================================
ERROR [2.128s]: test_wait_all_workers_twice_sparse (__main__.TensorPipeRpcTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 418, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 637, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 682, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 2 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 536, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 420, in wrapper
    fn()
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 1355, in test_wait_all_workers_twice_sparse
    self._wait_all_workers_twice(heavy_rpc_sparse, build_sparse_tensor())
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 1343, in _wait_all_workers_twice
    rpc.api._wait_all_workers()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/rpc/api.py", line 77, in wrapper
    return func(*args, **kwargs)
TypeError: _wait_all_workers() missing 1 required positional argument: 'timeout'

Process 3 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 536, in run_test
    getattr(self, test_name)()
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 420, in wrapper
    fn()
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 1355, in test_wait_all_workers_twice_sparse
    self._wait_all_workers_twice(heavy_rpc_sparse, build_sparse_tensor())
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 1343, in _wait_all_workers_twice
    rpc.api._wait_all_workers()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/rpc/api.py", line 77, in wrapper
    return func(*args, **kwargs)
TypeError: _wait_all_workers() missing 1 required positional argument: 'timeout'
```

**Review by mrshenli — COMMENTED** [review]
Hey @dracifer, could you please remove the updates to `third_party/*`? IIUC, that's not part of this PR?

**Review by mrshenli — COMMENTED** [review]
Hey @dracifer, shall we close this PR since it's superseded by #65425?

**Pull request closed without merging**
