### PR TITLE
Manually set _GLIBCXX_USE_CXX11_ABI in devtoolset7 binary builds

### PR DESCRIPTION
**Pull request by pjh5**
Fix for https://github.com/pytorch/pytorch/issues/17492

### CODE REVIEW

**Comment by bddppq** [comment]
Hehe, this doesn't work for devtoolset7. Previously we have run into this issue with the rocm libraries release binaries, @xw285cornell  and I have taken a closer look and found devtoolset7 always set cxx11 abi to false (even if you pass corresponding compiler flags).

**Comment by pjh5** [comment]
@bddppq do we need to use devtoolset5 for everything if we want to build with the c++11 abi?

**Comment by bddppq** [comment]
I actually don't know the right answer. For rocm release binaries we ended up patching /opt/rh/devtoolset-7/root/usr/include/c++/7/x86_64-redhat-linux/bits/c++config.h in devtoolset7 toolchain to let it allow cxx11 abi build:
```
243c243

< # define _GLIBCXX_USE_DUAL_ABI 0

---

> # define _GLIBCXX_USE_DUAL_ABI 1

251c251

< # define _GLIBCXX_USE_CXX11_ABI 0

---

> # define _GLIBCXX_USE_CXX11_ABI 1

2200c2200

< # define _GLIBCXX_USE_DUAL_ABI 0

---

> # define _GLIBCXX_USE_DUAL_ABI 1

2208c2208

< # define _GLIBCXX_USE_CXX11_ABI 0

---

> # define _GLIBCXX_USE_CXX11_ABI 1
```

My understanding is in general cxx11 abi is not supported in centos6 and centos7 (Red Hat claims to support it in future centos8).

**Comment by xw285cornell** [comment]
Maybe devtoolset 8 will also help.

**Comment by soumith** [comment]
devtoolset set of toolchain was written so that the compiled program works for the default libstdc++ shipped on the OS. So I guess it makes sense that it is hardcoded to 0.
I'll see if there's a different gcc available via RPM that we can use which is not packaged like this

**Comment by kostmo** [comment]
```
May 14 21:12:47 /circleci_stuff/ci_test_script.sh: line 28: /builder/check_binary.sh: No such file or directory
Exited with code 1
```
https://circleci.com/gh/pytorch/pytorch/1688952?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pjh5** [comment]
@kostmo the binaries succeeded earlier when I ran them all, and pointed them to https://github.com/pytorch/builder/pull/308 which is needed for the changes. I need to land these both together though, and normal binary jobs on PRs will break in the meantime. I verified these work earlier, so I plan to land both tonight when people aren't working

**Review by bwasti — APPROVED** [review]

**Comment by nicolasgriffiths** [comment]
@pjh5 The symbols in the libraries from https://download.pytorch.org/whl/nightly/devtoolset7/cu100/torch_nightly-1.1.0.dev20190516-cp36-cp36m-linux_x86_64.whl show old ABI strings:
```
0000000002d7da70 T torch::jit::load(std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&)
```

When I compile from source with CXX11_ABI the strings look like this 
```
torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>)
```

It is still not possible to link code compiled with CXX11_ABI to the devtoolset7 nightly binaries.
Is this supposed to be possible now?

**Comment by pjh5** [comment]
@nicolasgriffiths this was reverted for other circleci reasons, so binaries were never built with this diff yet. https://github.com/pytorch/pytorch/pull/20540 is the second attempt

**Comment by snnn** [comment]
That's true. It is documented in Red Hat's doc. You can't use the new ABI unless you upgrade the OS to a newer version.

**Pull request closed without merging**
