### PR TITLE
Enables private_use_one lazy_init by PrivateUse1HooksInterface

### PR DESCRIPTION
**Pull request by huihoaan**
Fixes[ #112369 ](https://github.com/pytorch/pytorch/issues/112369)

I want to use `PrivateUse1HooksInterface` to implement lazy_init for `PrivateUse1`.
In addition, my team found that `torch.load` without `lazy_init ` will also results in the same error because of follow codes: 
https://github.com/pytorch/pytorch/blob/bbd5b935e49a54578ac88cb23ca962ab896a8c7a/torch/csrc/Storage.cpp#L319-L321
https://github.com/pytorch/pytorch/blob/bbd5b935e49a54578ac88cb23ca962ab896a8c7a/torch/csrc/Storage.cpp#L334-L335

cc @bdhirsh

### CODE REVIEW

**Comment by huihoaan** [comment]
cc @albanD

**Review by ezyang — APPROVED** [review]
sure why not

**Pull request closed without merging**
