### PR TITLE
ROCM: Re enable 5 tests which are passing on ROCM

### LINKED ISSUE #46531: `torch.igamma` error and gives wrong results on float64 ROCm
## 🐛 Bug

This bug is related to PR #46183 where the implementation of `torch.igamma` in CUDA using float64 in ROCm is giving either errors or wrong results.

## To Reproduce

There are two cases based on the unittest I tried:

### Case 1 (ROCm raises an error):

    # device is cuda, dtype is torch.double
    def test_igamma(self, device, dtype):
        loglo = -4
        loghi = 4
        exp1 = 2.71828182846
        vec1 = torch.logspace(loglo, loghi, steps=500, base=exp1,
                              dtype=torch.float64, device=device).unsqueeze(-1)
        vec1 = vec1.to(dtype)
        inputs = [
            (vec1, vec1.transpose(0, 1)),
            (vec1, vec1),  # for large number, it should approach 0.5
            (vec1, 0.5 * vec1),  # test for considerable ratio
            (vec1, 2.0 * vec1),
        ]
        for input0, input1 in inputs:
            actual = torch.igamma(input0, input1)
            expected = scipy.special.gammainc(input0.cpu().numpy(), input1.cpu().numpy())
            expected = torch.from_numpy(expected).to(dtype)
            self.assertEqual(actual, expected)

Error message:

    21:18:17 test_igamma_common_cuda_float32 (__main__.TestTorchDeviceTypeCUDA) ... ok
    21:18:18 test_igamma_common_cuda_float64 (__main__.TestTorchDeviceTypeCUDA) ... Memory exception on virtual address 0x7f32775e8000, node id 4 : Page not present
    21:18:18 Address does not belong to a known buffer
    21:18:18 Memory access fault by GPU node-4 (Agent handle: 0x55d2eee23120) on address 0x7f32775e8000. Reason: Page not present or supervisor privilege.

### Case 2 (ROCm gives the wrong answer):

    # device is cuda, dtype is torch.double
    def test_igamma(self, device, dtype):
        loglo = -4
        loghi = 4
        
        def randrange(shape):
            a = torch.rand(shape).to(device) * (loghi - loglo) + loglo
            return torch.exp(a.to(torch.float64)).to(dtype)

        vec1 = randrange((100, 1))
        inputs = [
            (randrange((10,)), randrange((10,))),
            (randrange((3, 3, 3)), randrange((3, 3, 3))),
            (randrange((100, 1)), randrange((100, 1)).transpose(0, 1)),
            (vec1, vec1),  # for large number, it should approach 0.5
            (vec1, 0.5 * vec1),  # test for considerable ratio
            (vec1, 2.0 * vec1),
        ]
        for input0, input1 in inputs:
            actual = torch.igamma(input0, input1)
            expected = scipy.special.gammainc(input0.cpu().numpy(), input1.cpu().numpy())
            expected = torch.from_numpy(expected).to(dtype)
            self.assertEqual(actual, expected)

Error:

    10:45:41 ======================================================================
    10:45:41 FAIL: test_igamma_common_cuda_float64 (__main__.TestTorchDeviceTypeCUDA)
    10:45:41 ----------------------------------------------------------------------
    10:45:41 Traceback (most recent call last):
    10:45:41   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 828, in wrapper
    10:45:41     method(*args, **kwargs)
    10:45:41   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 273, in instantiated_test
    10:45:41     result = test_fn(self, *args)
    10:45:41   File "test_torch.py", line 17433, in test_igamma_common
    10:45:41     self._helper_test_igamma(loglo, loghi, device, dtype)
    10:45:41   File "test_torch.py", line 17424, in _helper_test_igamma
    10:45:41     self.assertEqual(actual, expected)
    10:45:41   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1139, in assertEqual
    10:45:41     self.assertTrue(result, msg=msg)
    10:45:41 AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1e-07 and atol=1e-07, found 1564 element(s) (out of 10000) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 2756.12890625 (2757.12890625 vs. 1.0), which occurred at index (51, 8).

## Expected behavior

No error and right answer is given.

## Environment

It's PyTorch's CI: `pytorch-linux-bionic-rocm3.8-py3.6-test2`

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @jeffdaily @sunway513

### PR DESCRIPTION
**Pull request by arindamroy-eng**
Re-enabling 5 tests which are passing on ROCM platform.

Signed-off-by: Arindam Roy <rarindam@gmail.com>

Fixes #46531

### CODE REVIEW

**Comment by arindamroy-eng** [comment]
@jithunnair-amd @jeffdaily

**Comment by pruthvistony** [comment]
@jeffdaily for review from ROCm

**Comment by jeffdaily** [comment]
> @jeffdaily for review from ROCm

Please fix the conflict.

**Comment by arindamroy-eng** [comment]
Dropping this PR as the changes have already been committed as part of another PR

**Pull request closed without merging**
