### PR TITLE
[nnc] Enable CPU fusion

### PR DESCRIPTION
**Pull request by bertmaher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #63545
* #63514
* #63386

Differential Revision: [D30417370](https://our.internmc.facebook.com/intern/diff/D30417370)

### CODE REVIEW

**Comment by bertmaher** [comment]
@bertmaher has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30417370).

**Review by navahgar — APPROVED** [review]
LGTM

**Comment by bertmaher** [comment]
@bertmaher has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30417370).

**Comment by bertmaher** [comment]
@bertmaher has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30417370).

**Pull request closed without merging**
