### PR TITLE
Migrate dropout inference from CUDA_tensor_apply3 to TensorIterator

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #34026 Completely kill CUDA_tensor_apply3
* #34025 Migrate lerp from CUDA_tensor_apply3 to TensorIterator
* **#34024 Migrate dropout inference from CUDA_tensor_apply3 to TensorIterator**
* #34023 Migrate bce loss from CUDA_tensor_apply3 to TensorIterator
* #34022 Migrate kl_div_backward from CUDA_tensor_apply3 to TensorIterator
* #34021 Migrate dirichlet from CUDA_tensor_apply3 to TensorIterator
* #34020 Migrate gamma grad from CUDA_tensor_apply3 to TensorIterator

Copied from https://github.com/pytorch/pytorch/pull/33879

Differential Revision: [D20196081](https://our.internmc.facebook.com/intern/diff/D20196081)

### CODE REVIEW

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Please rebase stack to master

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin I have rebased, and after rebase, this PR is no longer in the stack. Please start with https://github.com/pytorch/pytorch/pull/34023

**Comment by VitalyFedyunin** [comment]
Wait, dropout wasn't merged. Did you combined it with another PR?

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin This PR was originally copy-pasted from an independent PR #33879, that PR gets merged, so this is no longer needed.

**Pull request closed without merging**
