### PR TITLE
Replace _dynamo.config with an dataclass object

### PR DESCRIPTION
**Pull request by qihqi**
Summary:

Currently _dynamo.config (and friends) is written as module but is an object with its data backed by a dictionary. This change makes it a dataclass instead.

Nested namespace via class (`class cpp:` etc in _inductor/config.py) are also becoming dataclass.

For now, the top level dataclass generated dynamically from the module attr declarations. Next step is to also remove that and just use a normal dataclass.

The goal of having dataclasses for config is that there is a name for the config class, and therefore we can write functions that take those configs as input.

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

reset test files

Fixes #ISSUE_NUMBER

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @anijain2305 @bertmaher

### CODE REVIEW

**Comment by ngimel** [comment]
any comments on how this attempt is different from #96455 that had to be reverted?

**Comment by qihqi** [comment]
> any comments on how this attempt is different from #96455 that had to be reverted?

Hi Natalia, so @DanilBaibak pointed out in the previous version `import tempfile` was accidentally removed from torch/_dynamo/config.py, and it was only used in a branch guarded with `is_fbcode()`.

@DanilBaibak would it be possible to import this into phab and run internal tests first to make sure there aren't anything else? Thanks!

**Comment by bertmaher** [comment]
I'm sorry to be kind of obstructionist here, but can we just not do this?  Config ends up being used in a ton of places, is hard to test, and has subtle BC/FC issues.  With production services increasingly relying on dynamo/inductor, making a sweeping change to how config works feels like mostly downside.  I guess being able to write functions that operate on configs is maybe nice, but it doesn't feel worth it to justify the churn...

**Comment by yf225** [comment]
> With production services increasingly relying on dynamo/inductor, making a sweeping change to how config works feels like mostly downside.

I agreed with Bert. And in case we really want this change, I'd propose we merge it soon, and then we will land the change for model-specific config defaults internally to unblock more model enablement.

**Comment by ezyang** [comment]
I don't see why passing in the config as an explicit argument helps. Passing the config as an object, or having it global with context managers/decorators that modify it, they are semantically exactly the same.

**Pull request closed without merging**
