### PR TITLE
[Reland][dynamo] Enable some inlining inbuilt nn module tests

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128440

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by williamwen42 — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by anijain2305** [comment]
For reland, skipping a test because it fails only internally.

**Pull request closed without merging**
