### PR TITLE
Vectorize norm(double, p=2) on cpu

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #91502

This gives a speed up of 100x on my machine:

```
[------------------ Master -------------------]
                                |  (200000, 3)
32 threads: ----------------------------------
      torch linalg_norm         |     10000
      torch linalg_vector_norm  |     10000
      torch custom              |       397
      numpy norm                |      3123
      numpy custom_np           |      3119

Times are in microseconds (us).

[------------------- PR -------------------]
                                |  (200000, 3)
32 threads: ----------------------------------
      torch linalg_norm         |       107
      torch linalg_vector_norm  |       100
      torch custom              |       400
      numpy norm                |      3170
      numpy custom_np           |      3162

Times are in microseconds (us).
```

Fixes https://github.com/pytorch/pytorch/issues/91373

cc @ngimel @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by lezcano** [comment]
@jgong5 @mingfeima note that reductions on CPU are not vectorised in general. It's just this function that's vectorised as a one-off. In case you want to look into it, it would be nice to have vectorisation for general reductions on CPU.

**Comment by jgong5** [comment]
> @jgong5 @mingfeima note that reductions on CPU are not vectorised in general. It's just this function that's vectorised as a one-off. In case you want to look into it, it would be nice to have vectorisation for general reductions on CPU.

Thanks for the info. You are talking the the norm_cpu kernel right?

**Comment by lezcano** [comment]
Yep, the only one that's vectorised is this one that I'm editing here in this PR, and it's implemented in an ad-hoc way. Non vectorised reductions and the GPU path are both implemented in a generic way. If we had a similar thing for CPU we could get massive speed-ups for all the reduction-related operations.

**Review by mingfeima — APPROVED** [review]
LGTM!

**Comment by mingfeima** [comment]
> Yep, the only one that's vectorised is this one that I'm editing here in this PR, and it's implemented in an ad-hoc way. Non vectorised reductions and the GPU path are both implemented in a generic way. If we had a similar thing for CPU we could get massive speed-ups for all the reduction-related operations.

The root cause is right now TensorIterator is handling dim reduction in a recursive way and creating sub TensorIterator will be quite time consuming. This situation applies to all the dim reduction operators on CPU: `mean`, `rstd`, `norm`, scatter_add, index_add, etc.

Ideally I should refine the parallel reduce logic in TensorIterator, so basically two paths: a) when `dim=lastdim`, parallel on outer dimensions; b) when `dim != lastdim`, need to do blocking on the outer dimensions. This is not very easy to do and I am under a lot of KPI pressure last year, so I wrote a fast path to handle some commonly used scenarios at the first stage, kind of like a workaround. Will have it fixed from the ground level!

**Comment by lezcano** [comment]
@ngimel PTAL

**Review by ngimel — APPROVED** [review]
Cool! I was surprised that `double` `norm` perf was so much worse than `float`.

**Pull request closed without merging**
