### PR TITLE
Moving _run_autocast_outofplace to basic class named TestAutocast to reduce redundance

### PR DESCRIPTION
**Pull request by fffrog**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134460

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5 @albanD

### CODE REVIEW

**Review by EikanWang — APPROVED** [review]

**Comment by FFFrog** [comment]
@ezyang, it seems the CI failure has nothing to do with the change, please take a look, thank you.

**Review by ezyang — APPROVED** [review]
ack'ing just to allow for merge

**Pull request closed without merging**
