### PR TITLE
Add type annotation for bias in _ConvNd

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #33279 [quant][graphmode] Add quantized conv2d-relu fusion pattern
* #33277 [WIP][quant][graphmode] Observing input/output values in callsite
* #33276 [quant][graphmode][refactor] Move check for weight outside of insertObserverFor
* #33275 [quant][graphmode][refactor] Move values_to_skip check inside valueNeedsToBeQuantized
* #33274 [quant][graphmode][refactor] Simplify signature for insertObserverFor
* #33273 [quant][graphmode][refactor] Checks for bias and weight
* #33173 [quant][graphmode] Add a pass to handle ops that doesn't require observation
* #33172 [quant][graphmode][refactor] Factor out insertDequantCall
* #33171 [quant][graphmode] refactor nodeQuantizable
* #32816 [quant][graphmode] Add add_relu pattern in skip values
* #32815 [quant][graphmode] Add asserts for Conv and ReLU modules
* #32814 [quant][graphmode] Skip quantizing input and output in matched module
* #32813 [quant][graphmode][refactor] Separate preprocess step for insertObserver
* #32812 [quant][graphmode][refactor] Change signature of getModuleAccessPath
* #32809 [quant][graphmode][refactor] Move the check for qconfig inside insertObserver call
* #32379 [quant][graphmode] FoldConvBatchNorm2d support shared ClassTypes
* #32964 [jit] Add None parameter as parameter instead of attributes
* #32846 [jit][fix] Remove slot in parameter slot
* **#32885 Add type annotation for bias in _ConvNd**

Summary:
Currently Tensor bias is registered as parameter and None bias is registered as attribute.
We need the type annotation because when we try to fold ConvBn in graph mode quantization we'll
remove the None bias attribute and add a Tensor bias attribute, without type annotation the
bias Value in the graph  will be marked with different type in these two cases, so we have rewrite the
graph to change the type as well in that case. But with type annotation we don't need to modify the graph
since both cases the bias value will have type `Tensor?`

Test Plan:
.

Reviewers:
suo

Subscribers:

Tasks:

Tags:

Differential Revision: [D19844710](https://our.internmc.facebook.com/intern/diff/D19844710)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 025eaaef:


**None of the build failures appear to be your fault**.

* **1/1** recognized as flaky :snowflake:
    * Re-run these jobs?


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=025eaaef342e31e394ec77e004abde8f98ab2df1).

### :snowflake: 1 failure recognized as flaky
The following build failures have been detected as flaky and **may not be your fault**:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4394268) pytorch_linux_xenial_py3_6_gcc5_4_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=93952044) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=93952044)) :snowflake:
<details>
<summary>
<code>$<3>$<3> 37c6e43a8a65: Pushing  1.108GB/2.911GB $<3>$<3> 37c6e43a8a65: Pushing  2.911GB/2.911GB toomanyrequests: Rate exceeded</code>
</summary>

```
$<3>$<3> eea1661bdba1: Preparing   
$<3>$<3> 5bb9fbc1099e: Preparing   
$<3>$<3> 0d9b5dad09df: Preparing   
$<3>$<3> a80eb84c4169: Preparing   
$<3>$<3> 85775ce071b3: Preparing   
$<3>$<3> bfd07f554dc2: Preparing   
$<3>$<3> 00c6fc364d3a: Preparing   
$<3>$<3> 77008e118980: Preparing   
$<3>$<3> 6cb741cb00b7: Preparing   
$<3>$<3> f36b28e4310d: Preparing   
37c6e43a8a65: Pushing  1.108GB/2.911GB $<3>$<3> 37c6e43a8a65: Pushing  2.911GB/2.911GB toomanyrequests: Rate exceeded 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by raghuramank100** [comment]
Looks good to me, do we also need a similar fix for linear?

**Comment by jerryzh168** [comment]
> Looks good to me, do we also need a similar fix for linear?

no, we only need this for folding ConvBn, also bias is not constant for linear: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/linear.py#L66

**Comment by suo** [comment]
@jerryzh168 not sure I understand, bias is also potentially NoneType for linear, per the code you linked. Are you saying that we just never need to rewrite it?

**Comment by jerryzh168** [comment]
> @jerryzh168 not sure I understand, bias is also potentially NoneType for linear, per the code you linked. Are you saying that we just never need to rewrite it?

Oh, sorry, I thought this is the diff that removes bias from constant list.
Yeah I think we don't do Linear Bn Folding right now, if we need to do that then we'll need a similar fix for Linear as well.

**Comment by jerryzh168** [comment]
@raghuramank100 @suo please take a look

**Review by suo — APPROVED** [review]

**Pull request closed without merging**
