### PR TITLE
Use the newer one of cmake and cmake3.

### PR DESCRIPTION
**Pull request by ssnl**
On my devgpu, `cmake` is newer than `cmake3`. Using `cmake3` causes compilation to fail. Instead of blindly using `cmake3`, we pick the newer of the two.

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
please revert the large number of whitespace changes

**Comment by orionr** [comment]
Looks good - thanks.

**Comment by zdevito** [comment]
This breaks for my on python2:

```
[zdevito@devgpu172.prn2 /data/users/zdevito/pytorch] doit build develop && python test/test_jit.py
NVCC VERSION nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2018 NVIDIA Corporation Built on Wed_Apr_11_23:16:29_CDT_2018 Cuda compilation tools, release 9.2, V9.2.88
GCC=/home/zdevito/local/ccache/bin/gcc
NVCC=/usr/local/cuda/bin/nvcc
CUDA_NVCC_EXECUTABLE=/home/zdevito/local/ccache/cuda/nvcc
Building wheel torch-1.0.0a0+e64f75a
running build
running build_deps
setup.py::build_deps::run()
+ SYNC_COMMAND=cp
++ command -v rsync
+ '[' -x /bin/rsync ']'
+ SYNC_COMMAND='rsync -lptgoD'
+ CMAKE_COMMAND=cmake
++ command -v cmake3
+ [[ -x /bin/cmake3 ]]
++ command -v cmake
+ [[ -x /home/zdevito/local/anaconda2/bin/cmake ]]
++ cmake --version
++ grep 'cmake version'
++ awk '{print $NF}'
+ CMAKE_VERSION=3.11.1
++ cmake3 --version
++ grep 'cmake version'
++ awk '{print $NF}'
+ CMAKE3_VERSION=
++ /home/zdevito/local/anaconda2/bin/python -c 'from distutils.version import StrictVersion; print(1 if StrictVersion("") >= StrictVersion("3.11.1") else 0)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zdevito/local/anaconda2/lib/python2.7/distutils/version.py", line 140, in __cmp__
    compare = cmp(self.version, other.version)
AttributeError: StrictVersion instance has no attribute 'version'
+ CMAKE3_IS_NEWER=
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 libshm c10d THD'
total build time: 0:00:00.565524, total build time today: 0:00:03.531141
```

**Comment by zdevito** [comment]
This fixes it for me:

```
diff --git a/tools/build_pytorch_libs.sh b/tools/build_pytorch_libs.sh
index 1c2b728ab..f6f01adb7 100755
--- a/tools/build_pytorch_libs.sh
+++ b/tools/build_pytorch_libs.sh
@@ -22,7 +22,7 @@ if [[ -x "$(command -v cmake3)" ]]; then
     if [[ -x "$(command -v cmake)" ]]; then
         # have both cmake and cmake3, compare versions
         CMAKE_VERSION=$(cmake --version | grep 'cmake version' | awk '{print $NF}')
-        CMAKE3_VERSION=$(cmake3 --version | grep 'cmake version' | awk '{print $NF}')
+        CMAKE3_VERSION=$(cmake3 --version | grep 'cmake3 version' | awk '{print $NF}')
         CMAKE3_IS_NEWER=$($PYTORCH_PYTHON -c "from distutils.version import StrictVersion; print(1 if StrictVersion(\"${CMAKE3_VERSION}\") >= StrictVersion(\"${CMAKE_VERSION}\") else 0)")
     else
         # don't have cmake
```

**Pull request closed without merging**
