### PR TITLE
[jit] fix shape analysis on unwrap optional

### LINKED ISSUE #18744: Shape analysis for _unwrap_optional has confusing control flow
https://github.com/pytorch/pytorch/blame/01c03caacc266ad18cb19f1ee4131e9d16ea316f/torch/csrc/jit/passes/shape_analysis.cpp#L531

All the cases above this return at the end of the case. `_wrap_optional` conditionally returns. If it doesn't then it falls through to default case!!!! None of this is commented and is highly surprising. This caused bugs when I tried updating the code.

### PR DESCRIPTION
**Pull request by wanchaol**
This should fix #18744 

CC @zdevito @eellison

### CODE REVIEW

**Comment by eellison** [comment]
This conflicts with https://github.com/pytorch/pytorch/pull/18407, since there is more discussion there I think we should close this in favor of that

**Comment by wanchaol** [comment]
@eellison while that's part of a more detailed discussion on specialize Optional[Tensor], this PR mainly on fixing the bug that we previously introduced. we should not do conditional return in `aten::unwrap_optional` because the case that don't satisfy the condition will still flow through the result of the analysis, which is wrong as indicated in #18744.

**Comment by eellison** [comment]
> @eellison while that's part of a more detailed discussion on specialize Optional[Tensor], this PR mainly on fixing the bug that we previously introduced. we should not do conditional return in `aten::unwrap_optional` because the case that don't satisfy the condition will still flow through the result of the analysis, which is wrong as indicated in #18744.

Could you just fix the control flow and everything else unchanged? I would prefer not to do the same review twice on the same changes, and split discussion into two PRs.

**Comment by wanchaol** [comment]
> Could you just fix the control flow and everything else unchanged? I would prefer not to do the same review twice on the same changes, and split discussion into two PRs.

sure, will leave the discussion there, fixed the control flow bug only here.

**Pull request closed without merging**
