### PR TITLE
[C++ API] Add activation modules

### PR DESCRIPTION
**Pull request by goldsborough**
I don't intend to replicate all PyTorch modules in the C++ API (rather rely on community to ask for them, I would say), but I think activation modules are sufficiently basic to add.

In this PR I replicate a handful of the most important PyTorch activation modules in C++.

There is some follow up work I need to do to improve all modules to have saner `forward()` methods than `vector<Variable> forward(vector<Variable>)` -- at that point I will also make these modules take single `Variables` instead of `vector<Variable>`.

@apaszke @ebetica @ezyang

### CODE REVIEW

**Comment by ebetica** [comment]
Leaving some in-person discussion here:

My original design for the API only has things with parameters as Modules, and everything else as functions. I found this more intuitive than the PyTorch style where sometimes things would be Modules, but they're normally just implemented as functions first. To this end, Functional encourages people to wrap things when needed, since the module style is only really ever needed for Sequential.

I think it's valuable to add these for parity with PyTorch, but I think another solution where it's easier to add functional interfaces to Sequential is a better API design...

**Comment by goldsborough** [comment]
Yep after discussions with @ebetica, we settled that the best way to create stateless modules for use in `Sequential` is  `Functional`, e.g. `Functional(at::relu)`.

**Pull request closed without merging**
