### PR TITLE
[Inductor] Enable Inductor unspec inputs test for different dtypes

### PR DESCRIPTION
**Pull request by yanboliang**
Fixes #ISSUE_NUMBER

cc @jansel @mlazos @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by malfet** [comment]
> @pytorchbot merge -f "irrelevant macos failures"

Hmm, not sure I agree, it broke "test_unspec_inputs_cpu", which seems super relevant for this PR, isn't it?

**Pull request closed without merging**
