### PR TITLE
[dynamo] Make tx.next_instruction lazy

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #122067
* __->__ #122066
* #122063
* #122060
* #122058
* #122055
* #122043
* #122039

Improves benchmarks/dynamo/microbenchmarks/dynamo_microbenchmarks.py
from 2.5s to 2.4s.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by oulgen — APPROVED** [review]

**Review by anijain2305 — APPROVED** [review]

**Comment by huydhn** [comment]
@jansel I think one of the PR in the stack is causing one model to fail `detectron2_maskrcnn_r_101_c4` on inductor CPU benchmark https://hud.pytorch.org/pytorch/pytorch/commit/5bc7f7f97760d2d485621f9f30d0316e1f2440c6.  Could you help take a look and may be update the expected results CSV?

**Comment by jansel** [comment]
@huydhn lets just update the expected.   #122043 flipped that benchmark from an expected failure to passing, so that benchmark wasn't working before this stack anyway.

**Pull request closed without merging**
