### PR TITLE
Updates nonzero's as_tuple behavior to no longer warn.

### LINKED ISSUE #44284: Current behavior of `as_tuple` argument is inconsistent in `nonzero`
After `nonzero` started warning that `as_tuple` is a required argument (1.6) a few unfortunate things has happened:
1) the examples in docs started issuing a warning #43425
2) there's no way to pass `out` and `as_tuple` arguments together
```
print(torch.nonzero(a, as_tuple=False)) #ok
print(torch.nonzero(a, out=out)) #warns
print(torch.nonzero(a, as_tuple=False, out=out)) #errors out with `TypeError: nonzero() received an invalid combination of arguments - got unrecognized keyword arguments: out`
```
The rationale behind making `as_tuple` argument required is going through deprecation cycle to change the default value of `as_tuple` so that `torch.nonzero` matches `numpy.nonzero` without any additional args. However, even if implemented properly without problems noted above, this goal is misguided and forces users to modify their codes to avoid warnings for no good reason. 
Torch default behavior for `nonzero` should not match numpy. Numpy behavior can already be achieved by either using `as_tuple=True` or calling `unbind(1)` on results of `torch.nonzero()` call, that is a very light burden for someone who wants it. But to avoid it, we are making everyone who doesn't care jump through deprecation hoops. 
Making numpy behavior default is bad, because numpy returns a tuple of tensors, whereas many users want single tensor return. Going from a single tensor to a tuple is a matter of a cheap `.unbind` call, going from a tuple to a single tensor is memory copy. Default behavior should always pick single tensor. 
My proposal is to go back to making `as_tuple` optional argument and not strive to make `nonzero` match numpy behavior.

cc @albanD @mruberry @rgommers, @alband, @stas00

### PR DESCRIPTION
**Pull request by mruberry**
Fixes https://github.com/pytorch/pytorch/issues/44284.

[torch.nonzero](https://pytorch.org/docs/master/generated/torch.nonzero.html?highlight=nonzero#torch.nonzero) is distinct from [numpy.nonzero](https://numpy.org/doc/1.18/reference/generated/numpy.nonzero.html?highlight=nonzero#numpy.nonzero). The latter returns a tensor by default, and the former returns a tuple of tensors. The `as_tuple` argument was added as part of an intended deprecation process to make torch.nonzero consistent with numpy.nonzero, but this was a confusing change for users. A better deprecation path would be to offer torch.argwhere consistent with [numpy.argwhere](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html?highlight=argwhere#numpy.argwhere), which is equivalent to the default torch.nonzero behavior. Once this is offered a change to torch.nonzero should be more straightforward with less user disruption, if we decided that's the correct change to pursue.

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by gchanan** [comment]
that deprecation plan does sound superior.

**Review by gchanan — APPROVED** [review]
does the JIT do the right thing?

**Comment by mruberry** [comment]
> does the JIT do the right thing?

That's a good question. Let's extend the test for it.

**Comment by mruberry** [comment]
As expected, scripting with as_tuple does not work (see https://github.com/pytorch/pytorch/issues/45499). This is not a regression. Tracing with as_tuple DOES work.

**Comment by ppwwyyxx** [comment]
tools/autograd/templates/python_variable_methods.cpp also needs to be updated. With the current status, 1.7 will have inconsistent warning behavior between `torch.nonzero(tensor)` and `tensor.nonzero()`.

**Pull request closed without merging**
