### PR TITLE
[memory debugging] Extract frame information from inductor

### PR DESCRIPTION
**Pull request by zdevito**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #95753
* #96878

cc @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by zdevito** [comment]
The `origins` field on the inductor IR seems to repeat nodes a lot. For instance, this show the stack maps for each line, and the file that was generated: https://gist.github.com/zdevito/5d5b75554ea87d89cd9bb838366d0911

The `convolution` fx IR node appears in 5 different IR nodes as `origins` even though from reading the generated code only the first is actually computing the convolution.

**Review by Chillee — APPROVED** [review]

**Pull request closed without merging**
