### PR TITLE
Add cu118 workflows

### PR DESCRIPTION
**Pull request by ptrblck**
CC @atalman @malfet

### CODE REVIEW

**Comment by ptrblck** [comment]
The MacOS build failures seem to come from an invalid usage of `--jobs 0`:
```
+ git submodule update --init --recursive --jobs 0
~/work/pytorch/pytorch/pytorch ~/work/pytorch/pytorch
BUG: run-command.c:1521: you must provide a non-zero number of processes!
```
while the Windows build issues seem to be real:
```
Path = C:\actions-runner\_work\pytorch\pytorch\builder\windows\internal\\..\temp_build\gpu_driver_dlls.zip
Type = zip
Physical Size = 5127591


Would you like to replace the existing file:
  Path:     C:\Windows\System32\nvcuda.dll
  Size:     2729776 bytes (2666 KiB)
  Modified: 2021-04-10 18:27:18
with the file from archive:
  Path:     nvcuda.dll
  Size:     17459864 bytes (17 MiB)
  Modified: 2019-11-14 22:47:12


Break signaled
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 
Archives with Errors: 1

Cleaning temp files

C:\actions-runner\_work\pytorch\pytorch\builder>goto set_cuda_env_vars 

C:\actions-runner\_work\pytorch\pytorch\builder>echo Setting up environment... 
Setting up environment...

C:\actions-runner\_work\pytorch\pytorch\builder>set "PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Amazon\cfn-bootstrap;C:\ProgramData\chocolatey\bin;C:\Program Files\Amazon\AWSCLIV2;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Users\runneruser\AppData\Local\Microsoft\WindowsApps" 

C:\actions-runner\_work\pytorch\pytorch\builder>set "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8" 

C:\actions-runner\_work\pytorch\pytorch\builder>set "CUDA_PATH_V11_8=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8" 

C:\actions-runner\_work\pytorch\pytorch\builder>set "NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt" 

C:\actions-runner\_work\pytorch\pytorch\builder>if errorlevel 1 exit /b 1 
Error: Process completed with exit code 1.
```
I'm currently unsure what's causing these issues and what the actual error is, so would need to dig a bit into it.

**Comment by atalman** [comment]
Windows issues where because of the windows 11.8 image was still not available on production. This issue should be resolved this morning. I am rerunning the tests now.

**Comment by ngimel** [comment]
If windows issues persist, we should start 11.8 runs and nightlies for linux only, it's been long enough.

**Review by atalman — APPROVED** [review]
LGTM

**Pull request closed without merging**
