### PR TITLE
update kineto submodule to a94f97b

### LINKED ISSUE #97167: improvements needed in PyTorch profiling for AMD GPUs using torch.profiler.tensorboard_trace_handler
The json files produced when using torch.profiler.tensorboard_trace_handler with AMD GPUs have some problems.  The software setup has : torch==2.1.0.dev20230303+rocm5.4.2, and torch-tb-profiler==0.4.2, and the test system has AMD MI-250 GPUs.  The json files contain a number of records with category = kernel, name = Marker, but there are no GPU kernels named "Marker".   The json files also include a large number of records with category = kernel, but the events are not GPU kernels.  In addition, for compatibility with analysis with tensorboard, the category for "kernel" should be "Kernel", with an upper case K.     

  PyTorch profiles are produced using : 

        with torch.profiler.profile(
                 activities=[ torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA ],
                 schedule=torch.profiler.schedule(wait=waitvalue, warmup=2, active=10, repeat=1),
                 on_trace_ready=torch.profiler.tensorboard_trace_handler('/path/to/profiles'),
                 record_shapes=True
        ) as torch_profiler:

Here is an example of a "kernel" record where the category should be something else, not a GPU kernel : 

  {
    "ph": "X", "cat": "kernel", "name": "CopyHostToDevice", "pid": 2, "tid": 0,
    "ts": 1679332639271782, "dur": 11,
    "args": {
      "External id": 8938
    }
  },

Here is an example of a "kernel" record with name = "Marker" : 

  {
    "ph": "X", "cat": "kernel", "name": "Marker", "pid": 2, "tid": 1,
    "ts": 1679332639305911, "dur": 363875,
    "args": {
      "External id": 10302,"Kernel": "void at::native::modern::elementwise_kernel<at::native::AUnaryFunctor<float, float, float, at::native::binary_internal::MulFunctor<float> >, at::detail::Array<char*, 2> >(int, at::native::AUnaryFunctor<float, float, float, at::native::binary_internal::MulFunctor<float> >, at::detail::Array<char*, 2>)", "grid dim": [1024, 1, 1], "block dim": [256, 1, 1], "shared size": 0, "stream": "0x0"
    }
  },

The json files also contain records for the "kernel" category where the kernel name and parameters are listed : 

  {
    "ph": "X", "cat": "kernel", "name": "ncclKernel_SendRecv_RING_SIMPLE_Sum_int8_t(ncclDevComm*, unsigned long, ncclWork*)", "pid": 2, "tid": 1,
    "ts": 1679332639718731, "dur": 30559,
    "args": {
      "External id": 10570,"Kernel": "ncclKernel_SendRecv_RING_SIMPLE_Sum_int8_t(ncclDevComm*, unsigned long, ncclWork*)", "grid dim": [4, 1, 1], "block dim": [256, 1, 1], "shared size": 0, "stream": "0x9928530"
    }
  },

but even in these cases the kernel name re-appears in the "args" list.   

The json files produced when running the same PyTorch code with NVIDIA GPUs don't have these issues, but those files should specify category "Kernel" instead of "kernel" for the records corresponding to actual GPU kernels, so that tensorboard can properly identify the events.

Please update PyTorch profiler support for AMD GPUs with torch.profiler.tensorboard_trace_handler .
 

System info : 

torch==2.1.0.dev20230303+rocm5.4.2
torch-tb-profiler==0.4.2

ROCM used to build PyTorch: 5.4.22803-474e8620

OS: Red Hat Enterprise Linux 8.7 (Ootpa) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16)
Clang version: 14.0.6 (Red Hat 14.0.6-1.module+el8.7.0+15816+ec020e8f)
CMake version: version 3.25.0
Libc version: glibc-2.28

Python version: 3.9.16 (main, Jan 11 2023, 16:05:54)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-425.13.1.el8_7.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
GPU models and configuration: AMD Instinct MI250X / MI250
HIP runtime version: 5.4.22803
MIOpen runtime version: 2.19.0

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### PR DESCRIPTION
**Pull request by jeffdaily**
New submodule commit: https://github.com/pytorch/kineto/commit/c23a1fdbf60a76d1ff91e32417287577d9c48481

Fixes #97167.

### CODE REVIEW

**Comment by jeffdaily** [comment]
@aaronenyeshi, @davidberard98 --- trying to update to newer kineto is breaking all builds.  Can you take a look?

**Comment by davidberard98** [comment]
sure, will take a look

**Comment by davidberard98** [comment]
I think it should be fixed if you update to a94f97b666057e91db118249830cf861b1b7bd0b, which is the next commit on kineto main branch

**Review by aaronenyeshi — APPROVED** [review]
LGTM, thanks for updating the submodule Kineto!

**Comment by davidberard98** [comment]
sorry about that @jeffdaily , I'll try to get it fixed tomorrow once I figure out the build issue

**Pull request closed without merging**
