### PR TITLE
[Refactoring] making the code more Pythonic

### PR DESCRIPTION
**Pull request by se4ml**
### Description
Small code refactoring to make the code more pythonic by utilizing the Python `with` statement

### Issue
Not an issue

### Testing
This is a code refactoring

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by kit1980** [comment]
> @kit1980 I fixed the lint issue and ran the `lintrunner` locally for all the changed files. Could you please help to merge again.

Merge for the latest changes already in progress, looks like Lint passed already.

**Pull request closed without merging**
