### PR TITLE
Nvfuser code base nuke

### PR DESCRIPTION
**Pull request by jjsjann123**
removing nvfuser code base.

cc @albanD

### CODE REVIEW

**Comment by jjsjann123** [comment]
I don't think failing tests are relevant. I'm gonna wait until `viable/strict` catches up to retry CI. :laughing:

**Comment by jjsjann123** [comment]
This is breaking the 2k LOC sanity check.

But it's just removing dead code. Can we make an exception on that here, otherwise, it's going to be a ~85 PRs. :laughing: cc'ing @malfet 

Meanwhile, since I'm removing some bazel build files, would you mind try import and run this? @davidberard98

**Comment by malfet** [comment]
@jjsjann123 i'm fine with ignoring this check (also, let me modify it to never fire up if total is net negative)

**Comment by albanD** [comment]
Yes completely fine to skip this!

**Comment by davidberard98** [comment]
@jjsjann123 can you do the manual rebase please?

**Review by albanD — APPROVED** [review]
@davidberard98 if this is too prone to merge conflicts, it might be simpler to rebase + insta merge yourself.
The merge conflicts should be pretty clear.

**Comment by jjsjann123** [comment]
Let me do manual rebase.

**Comment by davidberard98** [comment]
thanks!

(btw, I'm kind of confused why the automated rebase didn't work; test_gpu3.cpp doesn't seem like it has changed since your last manual merge?)

**Comment by jjsjann123** [comment]
> thanks!
> 
> (btw, I'm kind of confused why the automated rebase didn't work; test_gpu3.cpp doesn't seem like it has changed since your last manual merge?)

Indeed!

There's no merge conflict when I just merged to upstream/viable/strict. But this isn't the first time with a false merge conflict from the bot.

**Comment by jjsjann123** [comment]
CI failure looks mysterious. The import did happen after my last rebase.

`Meta Internal-Only Changes Check — The Diff and Pull Request are not in sync!`

**Pull request closed without merging**
