### PR TITLE
[BE] Update CUDNN to 9.4.0.58

### PR DESCRIPTION
**Pull request by Skylion007**
* Updates to CUDNN 9.4.0.58 https://docs.nvidia.com/deeplearning/cudnn/latest/release-notes.html#cudnn-9-4-0
* 5-30% performance increase for CUDNN attention (likely by integrating FA3 improvements).
* Updates to CUDNN 9.3.0.75 https://docs.nvidia.com/deeplearning/cudnn/latest/release-notes.html#cudnn-9-3-0
* Updates CUDNN to 9.2.1.18 to further improve CUDNN flash attention and fix some heuristics. This also has a lot of bugfixes to fix edge cases in the CUDNN Flash Attention and also in very large convolutions.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Comment by Skylion007** [comment]
In the off chance we can squeeze this into to 2.4 or if it solves any inductor issues we are having.

**Review by ezyang — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Review by eqy — APPROVED** [review]

**Comment by Skylion007** [comment]
@atalman Update it again to the latest CUDNN version

**Comment by eqy** [comment]
We have a few internal (conv?) tests that seem to newly failiying with 9.3.0.75, will try to provide public reproducers that we can test...

**Comment by eqy** [comment]
Seems like cuDNN confirmed that these issues were real, but they are targeting a version later than 9.3 for the fix...

**Comment by Skylion007** [comment]
@eqy Are these issues fixed in the newly released 9.4?

**Comment by eqy** [comment]
Tentatively signing off on this, I think we are OK for now

**Comment by nWEIdia** [comment]
Have inductor tests been run with this PR yet? It would be good to know whether certain models would have fluctuations regarding the accuracy.

**Comment by Skylion007** [comment]
@nWEIdia Updated benchmarks, tinynet_a now passes inductor accuracy tests

**Review by nWEIdia — APPROVED** [review]
Looks great to me!

**Comment by Skylion007** [comment]
@nWEIdia I need to get the binaries uploaded to the pytorch_builder repo

**Comment by nWEIdia** [comment]
> @nWEIdia I need to get the binaries uploaded to the pytorch_builder repo, that's the main blocker.

Do you mean uploading the cudnn PYPI dependency packages the S3 (download.pytorch.org)? 
cc @atalman for help.

**Pull request closed without merging**
