### PR TITLE
Correct $ANDROID_HOME string empty check

### PR DESCRIPTION
**Pull request by parthagar**
Updated file to correct shell code to test whether $ANDROID_HOME env variable is empty or not.

### CODE REVIEW

**Comment by parthagar** [comment]
Also, I would like to request a change in the [Building PyTorch Android from Source(https://pytorch.org/mobile/android/#building-pytorch-android-from-source) webpage. How can I proceed?

**Review by IvanKobzarev — APPROVED** [review]

**Comment by IvanKobzarev** [comment]
> Also, I would like to request a change in the [Building PyTorch Android from Source](https://pytorch.org/mobile/android/#building-pytorch-android-from-source) webpage. How can I proceed?

@parthagar, thanks for your PR.

About contributing to 'build pytorch android from source' webpage - the sources of it are on https://github.com/pytorch/pytorch.github.io/blob/site/_mobile/android.md

You can create PR for it and you can ping me here that I will add  reviewers for that page.

**Comment by parthagar** [comment]
@IvanKobzarev , thanks for replying and your guidance. Will be submitting a PR soon.

**Comment by parthagar** [comment]
Sorry, closed by mistake.

**Pull request closed without merging**
