### PR TITLE
[Fix]: remove unnecessary copies in aten, c10, and torch bindings

### PR DESCRIPTION
**Pull request by Skylion007**
Applies various automated fixes that reduces the number of spurious copies in torch, aten, and c10. I also inlined any default dtors that would have made the type trivially destructible.

Follow up to #89000 

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @EikanWang

### CODE REVIEW

**Comment by Skylion007** [comment]
Also ccing @ezyang since a lot of these accidental copies are of SymInts / SymFloats.

**Review by ezyang — APPROVED** [review]
Would you consider helping us setup a lint for this? Only way to keep it fixed.

**Comment by Skylion007** [comment]
> Would you consider helping us setup a lint for this? Only way to keep it fixed.

I would love to but that would require closing #62011. These checks are already linted under places where lintrunner's clang-tidy is currently run, but that's a small fraction of the code base.

**Pull request closed without merging**
