### PR TITLE
add compile reason in InstructionTranslator RETURN_VALUE (#94176)

### PR DESCRIPTION
**Pull request by zjjott**
add compile reason in InstructionTranslator RETURN_VALUE (#94176)

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Comment by ezyang** [comment]
show us the before/after log messages, thanks!

**Comment by zjjott** [comment]
yes, @ezyang  here is example code:
```python
from torch._dynamo import config
import torch
import logging
from typing import List
import torch.nn as nn
from torch.utils.checkpoint import CheckpointFunction

config.verbose = True
config.log_level = logging.DEBUG
config.output_code = True


class MyModule(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, output_dim)
        self.activation = nn.GELU()

    def forward(self, x):

        def fn(x):
            x = self.linear(x)
            x = self.activation(x)
            return x

        if self.training:
            x = CheckpointFunction.apply(fn, False, x)
        else:
            x = fn(x)
        return x


if __name__ == "__main__":
    device = "cpu"
    mod = MyModule(10, 20)
    mod.to(device)
    mod.train()
    mod.zero_grad()
    x = torch.randn(16, 10, device=device, requires_grad=True)
    (explanation,
        out_guards,
        graphs,
        ops_per_graph,
        break_reasons,
        explanation_verbose) = torch._dynamo.explain(mod, x)
```

before log:
```
COMPILING GRAPH due to None
...
Skipping frame  <graph break in forward>                     try_dynamo/pr_count.py 27
```

after log:
```
COMPILING GRAPH due to GraphCompileReason(reason='return_value', user_stack=[<FrameSummary file try_dynamo/pr_count.py, line 24 in fn>])
...
Skipping frame because there is no content in function call <graph break in forward>                     try_dynamo/pr_count.py 27
```

**Comment by ezyang** [comment]
Tagging @jansel for any bikeshed suggestions.

**Review by jansel — APPROVED** [review]

**Comment by zjjott** [comment]
@ezyang there are two errors, but seens not cause by my change,what should I do now?

**Pull request closed without merging**
