### PR TITLE
Reland "Symintify repeat_interleave (#109133)"

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #112726

This reverts commit 08dbfecdbdf2af6f66b3226881c71d8977431197.

### CODE REVIEW

**Comment by albanD** [comment]
What is different from the original land?

**Comment by ezyang** [comment]
Nothing, I am still root causing. See https://www.internalfb.com/intern/sevmanager/view/s/376879/ for more details

**Review by albanD — APPROVED** [review]
Ok

**Pull request closed without merging**
