### PR TITLE
[Caffe2] Improve python tests for HIP device

### PR DESCRIPTION
**Pull request by rohithkrn**
The goal of this PR is to enable MIOPEN engine for operator tests and add hip device option to other tests.
It also includes necessary changes in `core.py` and `workspace.py`
@bddppq please review

\cc @petrex @ashishfarmer

### CODE REVIEW

**Review by petrex — COMMENTED** [review]
Can we have a separate PR for MIOPEN pooling fix? thanks

**Review by bddppq — CHANGES_REQUESTED** [review]
Yeah better to split the pool fix. We don't want to touch the python api part at this point, there is on-going work to unify cuda_gpu_id, hip_gpu_id and numa_node_id to device_id.

**Comment by petrex** [comment]
Agree in general we prefer one feature/fix per PR
There will be a separate PR for pooling fix thx

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by yf225** [comment]
@bddppq Would this PR be good to go?

**Comment by rohithkrn** [comment]
@bddppq I have removed API changes from this PR. It now has improvements to tests by adding MIOPEN engine and hip device option wherever necessary.

**Comment by ezyang** [comment]
Reping @bddppq

**Pull request closed without merging**
