### PR TITLE
[numpy] `torch.log1p` : promote integer inputs to float

### PR DESCRIPTION
**Pull request by kshitij12345**
Reference #42515

### CODE REVIEW

**Comment by mruberry** [comment]
Test failures look real - I'm not sure what's going with them?

**Comment by kshitij12345** [comment]
> Test failures look real - I'm not sure what's going with them?

https://github.com/pytorch/pytorch/blob/49f0e5dfeb64a928c6a2368dd5f86573b07d20fb/aten/src/ATen/native/native_functions.yaml#L2315-L2331

There are sparse dispatch for `log1p`, and those are called from `log1p` variant, but current change breaks it. (Had similar issue with `asin`)

On that note, binary sparse operators use `at::result_type` (reference below) to decide the output `dtype`,
From what I have seen, there is no such thing for unary operator promotion , except for the logic in TensorIterator,
Does using, `at::promote_types(input.scalar_type(), get_default_dtype())`, to promote UnarySparse operator from int -> float sound good? Or will we need to write the logic ourselves here?
https://github.com/pytorch/pytorch/blob/49f0e5dfeb64a928c6a2368dd5f86573b07d20fb/aten/src/ATen/native/sparse/SparseTensorMath.cpp#L394-L406

**Comment by mruberry** [comment]
> Does using, `at::promote_types(input.scalar_type(), get_default_dtype())`, to promote UnarySparse operator from int -> float sound good? Or will we need to write the logic ourselves here?

Don't the unary sparse operators just call the regular unary implementations, though?

**Comment by kshitij12345** [comment]
```

**Comment by kshitij12345** [comment]
They copy the original to result and the apply operation inplace. 
Since `TensorIterator` doesn't support SpareTensor, we can't use TensorIterator to promote result's type.
https://github.com/pytorch/pytorch/blob/49f0e5dfeb64a928c6a2368dd5f86573b07d20fb/aten/src/ATen/native/sparse/SparseTensorMath.cpp#L102-L119

**Comment by mruberry** [comment]
> They copy the original to result and the apply operation inplace.

Oh right. Thank you for reminding me. This PR could explicitly disable the operation on integer sparse tensors for the moment, or add a helper function to create a default scalar type tensor to copy into. The helper function shouldn't use promote types but check if values is an integer type and, if so, create a default scalar type copy.

**Comment by kshitij12345** [comment]
>  or add a helper function to create a default scalar type tensor to copy into. The helper function shouldn't use promote types but check if values is an integer type and, if so, create a default scalar type copy.

@mruberry have done the following and updated the tests in test_sparse. Unfortunately was unable to use dtypes to pass dtypes as argument so had to iterate over them. 

PTAL
Thanks

**Review by mruberry — APPROVED** [review]
Awesome! Nice spare workaround, @kshitij12345!

**Comment by mruberry** [comment]
> @mruberry have done the following and updated the tests in test_sparse. Unfortunately was unable to use dtypes to pass dtypes as argument so had to iterate over them.

Unfortunately test_sparse.py hasn't been updated to use our generic device test framework, so it doesn't support functionality like the @dtypes decorator. Enumerating the dtypes directly in the test is a great workaround. cc @pearu as an fyi. We should work to update the sparse tests to opt into the device generic framework and use OpInfos, too. Probably by adding a metadata field to the OpInfo class like "supported_layouts" that can include the COO layout (or not).

**Pull request closed without merging**
