### PR TITLE
Make factory functions CompositeExplicitAutograd

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #82333
* __->__ #82251

This also makes them not decompose when we switch Python key.
Note that CompositeExplicitAutogradNonFunctional maybe be overly
conservative for some implementations (which actually call into
other functional ops), but for now I just uniformly apply this
everywhere to avoid errors.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
lgtm

I wonder if we should think about exposing a way for python subclass writers to get at the `CompositeExplicitAutograd` kernels, now that there are more of them (especially if they don't wanna write implementations for all the factory funcs).


Also, do we need batching rules for these ops now?

**Comment by ezyang** [comment]
> I wonder if we should think about exposing a way for python subclass writers to get at the CompositeExplicitAutograd kernels, now that there are more of them (especially if they don't wanna write implementations for all the factory funcs).

I feel what is supposed to happen, is you should be able to call super() and it will automatically do this.

However, this does not work, because the way we implement super() is we disable torch dispatch entirely and then call in. So we need some sort of redispatch that doesn't disable torch dispatch but does force a call into C++ for one call. Not too hard to do for torch.ops. Related https://github.com/pytorch/pytorch/issues/55093

**Comment by zou3519** [comment]
> Also, do we need batching rules for these ops now?

Probably not, vmap doesn't interpose on factory functions (with the exception of random operations). But random operations already had batching rules.

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
