### PR TITLE
Enable boolean_mask, adadelta, adagrad fp16 on ROCm

### PR DESCRIPTION
**Pull request by rohithkrn**
-  Fix bugs, indentation for adadelta and adagrad tests to enable fp16
- Enable boolean_mask fp16  on ROCm

### CODE REVIEW

**Comment by rohithkrn** [comment]
@bddppq @petrex

**Comment by bddppq** [comment]
@rohithkrn The test errors looks legit. Are you working on fixing them?

**Comment by rohithkrn** [comment]
@bddppq yeah, I will work on them and update soon.

**Pull request closed without merging**
