### PR TITLE
Adding StreamWrapper to ensure file object will be closed

### PR DESCRIPTION
**Pull request by NivekT**
Summary: Adding StreamWrapper to streams produced by DataPipes within PyTorch Core and TorchData

Test Plan: OSS CI and Internal Tests

Differential Revision: D31695248

cc @VitalyFedyunin @ejguan @NivekT

### CODE REVIEW

**Review by ejguan — APPROVED** [review]
Stamp for it.

**Comment by pmeier** [comment]
`StreamWrapper` does not work with `open`. This means that amongst others you can no longer load `.mat` files directly:

```python
import scipy.io

from torchdata.datapipes.iter import FileLoader, IterableWrapper, Mapper

file = "foo.mat"
scipy.io.savemat(file, dict(foo="bar"))

dp = IterableWrapper((file,))
dp = FileLoader(dp)
dp = Mapper(dp, scipy.io.loadmat, input_col=1)

next(iter(dp))
```

```
TypeError: expected str, bytes or os.PathLike object, not StreamWrapper
```

The error message is a little misleading. Although `open` very much supports open file handles as inputs (in which case it is a no-op), this possibility is not included in the message. Internally, `scipy` fails [here](
https://github.com/scipy/scipy/blob/701ffcc8a6f04509d115aac5e5681c538b5265a2/scipy/io/matlab/mio.py#L38-L49). 

Workaround is to explicitly pass the `.file_obj` attribute to `scipy.io.loadmat`:

```python
import scipy.io

from torchdata.datapipes.iter import FileLoader, IterableWrapper, Mapper

file = "foo.mat"
scipy.io.savemat(file, dict(foo="bar"))


def loadmat(stream_wrapper):
    return scipy.io.loadmat(stream_wrapper.file_obj)


dp = IterableWrapper((file,))
dp = FileLoader(dp)
dp = Mapper(dp, loadmat, input_col=1)

data = next(iter(dp))
assert data[1]["foo"] == "bar"
```

**Comment by ejguan** [comment]
`StreamWrapper` should be returned [here](https://github.com/scipy/scipy/blob/701ffcc8a6f04509d115aac5e5681c538b5265a2/scipy/io/matlab/mio.py#L32-L36)

- We need to explicitly add `read` and `write` methods to `StreamWrapper`.
- Refactor `StreamWrapper` to re-assign the methods like following:
```py
class StreamWrapper:
    def __init__(self, fiile_obj):
        self.__class__ = type(fiile_obj.__class__.__name__,
                              (self.__class__, fiile_obj.__class__),
                              {})
        self.__dict__ = fiile_obj.__dict__
        self.file_obj = file_obj

    def __del__(self):
        file_obj.close()
```

**Comment by NivekT** [comment]
> ```python
> self.__class__ = type(file_obj.__class__.__name__,
>                               (self.__class__, file_obj.__class__),
>                               {})
> ```

This line here `(self.__class__, file_obj.__class__),` will trigger this error, `TypeError: __class__ assignment: 'BufferedReader' object layout differs from 'StreamWrapper'`. I believe this is because the underlying C data structures are different.


`self.__dict__ = file_obj.__dict__` seems to lead to infinite recursion when `__getattr__` is defined as such:
```python
    def __getattr__(self, name):
        return getattr(self.file_obj, name)
```


The quick fix is to add the method `__dir__` to StreamWrapper, which will allow `loadmat` to work without impacting other functionalities.
```python
    def __dir__(self) -> Iterable[str]:
        return ['file_obj'] + dir(self.file_obj)
```

**Pull request closed without merging**
