### PR TITLE
Enable UFMT on all of `test/distributed`

### PR DESCRIPTION
**Pull request by shink**
Partially addresses #123062

Ran lintrunner on:

- `test/distributed`

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @albanD

### CODE REVIEW

**Comment by ezyang** [comment]
lintcheck.sh says this is clean, but it is failing lint and will need more fixes

**Review by ezyang — CHANGES_REQUESTED** [review]
failing ci

**Comment by shink** [comment]
@ezyang I just moved the position of `noqa`, is it right?

See https://github.com/pytorch/pytorch/pull/123539/commits/d1ac77100d98db467278a51f45c9425e28e1d85f

**Comment by ezyang** [comment]
noqa moves are fine, looks like you still have to do more though.

**Comment by shink** [comment]
@ezyang PTAL

**Comment by ezyang** [comment]
noqa moves are good

**Review by ezyang — DISMISSED** [review]

**Comment by DanilBaibak** [comment]
Hi @shink! Sorry, I need to revert your PR because it broke trunk. Here you can find more information about the issue - https://hud.pytorch.org/pytorch/pytorch/commit/89ac37fe919997e844f0baa6e28965d0d52b0682

**Comment by shink** [comment]
@DanilBaibak Sure, I will check it out.

**Comment by shink** [comment]
@DanilBaibak Fixed. See https://github.com/pytorch/pytorch/pull/123539/commits/ee1ffb4ce35cd0c3afbc1c5f7278408de5160305

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
