### PR TITLE
Rename autograd namespace to torch and change torch.h into python.h

### PR DESCRIPTION
**Pull request by goldsborough**
This PR does three things:

1. Changes `autograd` namespace (still from autogradpp) to `torch`
2. Renames `torch/autograd.h` to `torch/torch.h`
3. Because this now collides with the `torch/torch.h` we have for the C++ extensions API, I have moved `torch/torch.h` into `torch/csrc/api/include/python.h` and moved `torch/csrc/torch.cpp` to `torch/csrc/api/src/python.cpp`. This changes the include for C++ extensions from `torch/torch.h` to `torch/python.h`, which is an active API breakage. I do this because eventually the C++ extensions API will just be the C++ API + Python binding stuff. I name it `torch/python.h` instead of `torch/extension.h` because we may well get other language bindings in the future.

Testing on internal projects now.

CC @ebetica @apaszke @fmassa

### CODE REVIEW

**Comment by apaszke** [comment]
Are we planning to move some `python.h` functions to `torch.h`? They seem pretty important

**Comment by goldsborough** [comment]
@apaszke Yes exactly. `python.h` will ultimately include `torch.h` and the python binding stuff. But I just want to make this a codemove at the moment

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@zou3519 

```
02:49:53 ======================================================================
02:49:53 FAIL: test_expect (test_utils.TestCollectEnv)
02:49:53 ----------------------------------------------------------------------
02:49:53 Traceback (most recent call last):
02:49:53   File "test_utils.py", line 663, in test_expect
02:49:53     self.assertExpectedOutput(info_output, build_env)
02:49:53   File "test_utils.py", line 643, in assertExpectedOutput
02:49:53     ci_warning + '\n' + expected_info, ci_warning)
02:49:53   File "common.py", line 245, in assertEqual
02:49:53     super(TestCase, self).assertEqual(x, y, message)
02:49:53 AssertionError: This test will error out if the CI config was recently updated. If this is the case, please update the expect files to match the CI machines' system config.
02:49:53 
```

Why isn't this test printing out the diff?

**Comment by goldsborough** [comment]
Can I ignore this or do I have to retest?

**Comment by zou3519** [comment]
@ezyang Which build did that occur on?

**Pull request merged**
