### PR TITLE
Boxing uses if_constexpr instead of SFINAE

### PR DESCRIPTION
**Pull request by smessmer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#31092 Boxing uses if_constexpr instead of SFINAE**
* #31091 if_constexpr for C++14

-

Differential Revision: [D18927221](https://our.internmc.facebook.com/intern/diff/D18927221/)

### CODE REVIEW

**Comment by ezyang** [comment]
If I get the test condition wrong leading to a compile error, what does the error message look like now? Also cc @zdevito who was also recently debugging an issue in this area.

**Comment by smessmer** [comment]
> If I get the test condition wrong leading to a compile error, what does the error message look like now? Also cc @zdevito who was also recently debugging an issue in this area.

It'll be the same assertion failing as before. We don't fail at compile time here but at runtime with the assertion.

**Comment by ezyang** [comment]
So, the specific problem we had was that the `is_constructible` test is not infallible: if there is a templated constructor in IValue that isn't properly sfinaed so that only types that will typecheck in the body of the constructor will work, then the sfinae template here will incorrectly report it is constructible (and you'll get a downstream type error). So I am quite interested to know what will happen in a situation like this. But I guess I am convinced now that the error will not occur within `if_constexpr`

**Review by ezyang — APPROVED** [review]

**Comment by mruberry** [comment]
Unlanding. This appears to have broken ci/circleci: pytorch_windows_vs2017_14.11_py36_cpu_build and ci/circleci: pytorch_windows_vs2017_14.11_py36_cuda10.1_build.

**Pull request closed without merging**
