### PR TITLE
Bump black version to 23.1.0

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #96781
* #96567
* #96556
* #96479
* __->__ #96578

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by BowenBao** [comment]
@ezyang not sure who to tag. Is it ok to upgrade black version used in pytorch? There are some bug fixes in newer version regarding `#fmt: skip` https://github.com/psf/black/pull/3148

**Review by ezyang — APPROVED** [review]
go go go

**Comment by BowenBao** [comment]
> go go go

thx, enclosing the diffs produced by newer version black in this PR.

**Comment by ezyang** [comment]
Skimmed, looks fine

**Pull request closed without merging**
