### PR TITLE
Allow new_full's fill_value argument type to be complex

### PR DESCRIPTION
**Pull request by ccshan**
It seems that this code should type-check but doesn't:
```python
torch.zeros((2,3),dtype=torch.cdouble).new_full((4,5),complex(6,7))
```

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

### CODE REVIEW

**Review by zou3519 — CHANGES_REQUESTED** [review]
seems like we would also need to change torch.full's type hint

**Review by ezyang — APPROVED** [review]

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
