### PR TITLE
remove support for c extensions

### PR DESCRIPTION
**Pull request by li-roy**
Summary: We are deprecating support for c extensions. Please use cpp extension in the future.

Differential Revision: D10060541

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
end of an era

**Comment by SsnL** [comment]
Could you still keep `torch/utils/ffi/__init__.py` and make it just throw deprecation error?

**Comment by SsnL** [comment]
Thanks!

**Comment by ruotianluo** [comment]
This breaking change is not in the release doc.

**Pull request closed without merging**
