### PR TITLE
[CUTLASS] fix bugs: extra data_ptr() call, wrong size symbol name, bias symbol not added

### PR DESCRIPTION
**Pull request by ColinPeppler**
A few small things in this PR:
- fixed a bug where `workspace.data_ptr().data_ptr()` showed up
- for SM80 CUTLASS kernels, the symbol size for W.size(1) was never created
- for addmm kernels, the ldc bias symbol never showed up

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #143537
* __->__ #143528

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by chenyang78** [comment]
Wondering if we could add a test? Thanks.

**Comment by ColinPeppler** [comment]
> Wondering if we could add a test? Thanks.

sure let me add some :)

**Review by henrylhtsang — APPROVED** [review]

**Pull request closed without merging**
