### PR TITLE
[torchbind] always fakify script object by default in non-strict export

### PR DESCRIPTION
**Pull request by ydwu4**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #127116
* #127114
* #127113

This diff can be risky for internal tests: any torchbind class that hasn't registered a fake class will fail and we should fix them. We've gained some confidence that this can work e2e by implementing FakeTensorQueue for TBE models in sigmoid with [D54210823](https://www.internalfb.com/diff/D54210823). 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

Differential Revision: [D57991002](https://our.internmc.facebook.com/intern/diff/D57991002)

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]
You're going to want to import this internally first if you haven't already to see if anything fails. If it looks all good then let's yolo land it with the caveat that it's possible this might break something and people are free to revert this

**Comment by ydwu4** [comment]
@ydwu4 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D57991002).

**Pull request closed without merging**
