### PR TITLE
Eliminate type dispatch from copy_kernel, and use memcpy directly rather than implementing our own copy.

### PR DESCRIPTION
**Pull request by resistor**
It turns out that copying bytes is the same no matter what type
they're interpreted as, and memcpy is already vectorized on every
platform of note.  Paring this down to the simplest implementation
saves just over 4KB off libtorch.

### CODE REVIEW

**Review by soumith — DISMISSED** [review]
you cant memcpy an IEEE float16 type to other types

**Comment by soumith** [comment]
` at::vec256::convert<scalar_t, scalar_t>(src_seg, self_seg, len);` actually casts one type to another, i think.

**Comment by resistor** [comment]
> `at::vec256::convert<scalar_t, scalar_t>(src_seg, self_seg, len);` actually casts one type to another, i think.

scalar_t is both the source and the destination type, so this is purely a copy, not a type conversion.

**Comment by resistor** [comment]
@soumith Good to go?

**Review by soumith — APPROVED** [review]

**Review by jamesr66a — APPROVED** [review]
image

**Comment by soumith** [comment]
should this be reverted, considering context in #19410 ?

**Comment by resistor** [comment]
> should this be reverted, considering context in #19410 ?

I'm building PyTorch right now to test the small copy scenario.  #19410 was very low impact (AFAICT there's no actual users of the function), but this one has real usage that will benefit on newer machines, and also makes a non-trivial impact on code size.

**Comment by resistor** [comment]
After fighting through some environment setup issues, I benchmarked this:

> import torch
> a = torch.tensor([1,2,3,4,5,6,7,8], dtype=torch.float32)
> b = torch.zeros(1000000, 8)
> import timeit
> timeit.timeit("b.copy_(a)", "from __main__ import a, b", number=10000)

With this change, I got 166.26 seconds.  With the change reverted, I 168.57 seconds.

**Pull request closed without merging**
