### PR TITLE
[PyTorch] Store Argument::alias_info_ on the heap

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #64691
* __->__ #64824

See comment in function_schema.h for explanation. I claim that this is a good tradeoff because the aliasing information seems to be used only in compiler-ish code paths, where performance isn't as critical as actual execution. If performance is important there too, perhaps we should hoist isWrite into the Argument itself since there are several paths that only care about isWrite.

Differential Revision: [D30860719](https://our.internmc.facebook.com/intern/diff/D30860719/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D30860719/)!

### CODE REVIEW

**Comment by albanD** [comment]
> the aliasing information seems to be used only in compiler-ish code paths, where performance isn't as critical as actual execution.

Actually all the boxed functions that you modify here are execution-time functions. So relatively perf critical (in particular the math fallback which runs whenever you do conj/neg).
Not sure if that is enough to warrant a change of the PR, but you might want to check perfs.

**Comment by swolchok** [comment]
> (in particular the math fallback which runs whenever you do conj/neg).

MathBitsFallback is only checking presence/absence of the optional (now null/notnull of the pointer) so if anything it will go faster because it has to touch less memory. Anything in particular I should look into?

**Comment by albanD** [comment]
For the math bits, you can try to see the impact when you do
```python
a = torch.rand(10, dtype=torch.cfloat) # needs to be complex!
a.conj().some_op() # time this
```

For the autograd not implemented fallback any op that uses it:
```python
a = torch.rand(10) # No need to require gradients
a.narrow_copy(0, 0, 5) # time this
```

**Comment by swolchok** [comment]
@albanD 

> ```python
> a = torch.rand(10, dtype=torch.cfloat)
> ```

code:
```
import torch
import torch.utils.benchmark

a = torch.rand(10, dtype=torch.cfloat)
t0 = torch.utils.benchmark.Timer(
    stmt = 'a.conj().abs()',
    globals = {'a': a})

print(t0.blocked_autorange(min_run_time=5))

a = torch.rand(10)
t1 = torch.utils.benchmark.Timer(
    stmt='a.narrow_copy(0,0,5)',
    globals = {'a': a})
print(t1.blocked_autorange(min_run_time=5))
```

before:
```
<torch.utils.benchmark.utils.common.Measurement object at 0x7fc736a48940>
a.conj().abs()
  Median: 5.51 us
  IQR:    0.06 us (5.48 to 5.54)
  900 measurements, 1000 runs per measurement, 1 thread
<torch.utils.benchmark.utils.common.Measurement object at 0x7fc6ec693940>
a.narrow_copy(0,0,5)
  Median: 1.57 us
  IQR:    0.03 us (1.56 to 1.59)
  318 measurements, 10000 runs per measurement, 1 thread
# rerunning to make sure since I ran "after" first":
<torch.utils.benchmark.utils.common.Measurement object at 0x7f7208408940>
a.conj().abs()
  Median: 5.35 us
  IQR:    0.04 us (5.33 to 5.37)
  929 measurements, 1000 runs per measurement, 1 thread
<torch.utils.benchmark.utils.common.Measurement object at 0x7f71bda4c880>
a.narrow_copy(0,0,5)
  Median: 1.55 us
  IQR:    0.02 us (1.54 to 1.56)
  321 measurements, 10000 runs per measurement, 1 thread
```

after:
```
<torch.utils.benchmark.utils.common.Measurement object at 0x7f8f4d98a190> 
a.conj().abs()  
  Median: 5.39 us  
  IQR:    0.05 us (5.37 to 5.42)
  926 measurements, 1000 runs per measurement, 1 thread  
<torch.utils.benchmark.utils.common.Measurement object at 0x7f8e4998dbb0>
a.narrow_copy(0,0,5)
  Median: 1.52 us
  IQR:    0.01 us (1.51 to 1.53)
  329 measurements, 10000 runs per measurement, 1 thread
```

used an optimized build in the internal FB repo, turbo was disabled for both runs. Looks neutral enough to me.

**Review by suo — APPROVED** [review]
changes look fine, I'm assuming the build failures will get sorted

**Comment by albanD** [comment]
Ok!
Within noise level then. Thanks for taking the time to do this!

**Pull request closed without merging**
