### PR TITLE
[cpu] vectorize acosh

### PR DESCRIPTION
**Pull request by khushi-411**
Fixes #ISSUE_NUMBER

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by sanchitintel** [comment]
Thanks for vectorizing `acosh`, @khushi-411!
Would you able to submit similar PRs to vectorize `asinh` & `atanh` as well, or maybe vectorize them in the same PR? Thanks!

**Comment by khushi-411** [comment]
Hi, @sanchitintel!
Sure, I'll submit another PR for that. It'll be fun. Thanks for looking into it :)

**Review by jgong5 — APPROVED** [review]

**Review by jgong5 — CHANGES_REQUESTED** [review]
Sorry, mistakenly clicked approving...

**Comment by sanchitintel** [comment]
Looks like we're not getting desired accuracy for BF16 with Sleef. 
@mingfeima, could you please advise on the best course of action? Thanks!

**Comment by khushi-411** [comment]
Hi, @mingfeima! Gentle ping

**Comment by khushi-411** [comment]
Gentle ping, @mingfeima!

**Comment by jgong5** [comment]
@khushi-411 there are test failures that you need to look into.

**Comment by sanchitintel** [comment]
Hi @khushi-411, Mingfei would be away this week. 

Do you think there's something we could do to mitigate BF16 failures?
i.e. if we'd not use sleef, but use mkl instead, would we get good performance & desired accuracy? 

Thanks!

**Comment by khushi-411** [comment]
Hi, @jgong5, @sanchitintel!
Thanks for looking into it.

> Do you think there's something we could do to mitigate BF16 failures?
e.g. if we'd not use sleef, but use mkl instead, would we get good performance & desired accuracy?

Sounds interesting, I haven't yet worked on `mkl`. I'll try that this time! It'll be fun!!

Thanks!

**Pull request closed without merging**
