### PR TITLE
ATen/native (2/6): Use per-operator headers

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #75576
* #75575
* #75574
* #75573
* __->__ #75572

Differential Revision: [D40126702](https://our.internmc.facebook.com/intern/diff/D40126702)

### CODE REVIEW

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40126702).

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40126702).

**Comment by peterbell10** [comment]
@malfet PTAL, landing internally has failed because this PR hasn't been approved.

**Review by DanilBaibak — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
