### PR TITLE
52189: refractor unreachable Runtime Error

### LINKED ISSUE #52189: Unreachable Code in /tools/codegen/api/python.py
## 🐛 Bug

I've found an unreachable portion of code in the following file and line. 

https://github.com/pytorch/pytorch/blob/master/tools/codegen/api/python.py#L823-L824

## Additional context

The last line of code at 824 is unreachable as the variable **ret** should be returned regardless. It seems if the input parameter **t** is not an instance of either **BaseType** or **ListType** it seems **ret** may throw a NameError for ret as it should not be defined, instead of raising the RuntimeError.

### PR DESCRIPTION
**Pull request by exclowd**
Fixes #52189

Since the PR #52228 had gone cold. I made the requested changes and fixed the linting error.

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
Fair enough. I wonder whether we could add a tool that detects these unreachable statements @ezyang

**Comment by lezcano** [comment]
Could you please fix the linting issue?

**Comment by ezyang** [comment]
for a drive by contribution like this is usually easiest to just fix it yourself lol. You should be able to push to exclowd's branch.

**Pull request closed without merging**
