### PR TITLE
Upgraded nightly wheels to rocm5.5

### PR DESCRIPTION
**Pull request by BLOrange-AMD**
Upgraded nightly wheels to rocm5.5

Follow-up to https://github.com/pytorch/builder/pull/1407

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo

### CODE REVIEW

**Comment by atalman** [comment]
> @malfet @atalman How do we resolve this error from https://hud.pytorch.org/pr/pytorch/pytorch/102242#13868719553?
> 
> ```
> 2023-05-30T17:48:22.6114673Z + pip install /final_pkgs/torch-2.1.0.dev20230530+rocm5.5-cp38-cp38-linux_x86_64.whl --index-url https://download.pytorch.org/whl/nightly/rocm5.5
> 2023-05-30T17:48:23.8154922Z Looking in indexes: https://download.pytorch.org/whl/nightly/rocm5.5
> 2023-05-30T17:48:23.8236191Z Processing /final_pkgs/torch-2.1.0.dev20230530+rocm5.5-cp38-cp38-linux_x86_64.whl
> 2023-05-30T17:48:27.3894700Z INFO: pip is looking at multiple versions of torch to determine which version is compatible with other requirements. This could take a while.
> 2023-05-30T17:48:27.3896933Z ERROR: Could not find a version that satisfies the requirement filelock (from torch) (from versions: none)
> 2023-05-30T17:48:27.3898297Z ERROR: No matching distribution found for filelock
> ```
> 
> Is there another step needed to upload all the dependency packages to that link?

This should be resolved now. I created the rocm5.5 path manually this time

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
I think that's a chicken an egg problem with added trition dependency: one needs to have at least one nightly for the build to succeed...

**Comment by jithunnair-amd** [comment]
@malfet @atalman Is it possible to kick off the push of libtorch docker images to dockerhub? I was able to successful build them post-PR-merge (https://github.com/pytorch/builder/actions/runs/5017295865/jobs/9220705416), but I don't know how to trigger a push to dockerhub.

**Comment by malfet** [comment]
> @malfet @atalman Is it possible to kick off the push of libtorch docker images to dockerhub? I was able to successfully build them post-PR-merge (https://github.com/pytorch/builder/actions/runs/5017295865/jobs/9220705416), but I don't know how to trigger a push to dockerhub.

@jithunnair-amd I don't think CI relies on anything published to hub.docker.com for the last year or so. Once companion PR has been merrged on builder, docker containers should have been populated to AWS ECR/ghcr.io

**Comment by jithunnair-amd** [comment]
Now using this PR to test https://github.com/pytorch/builder/pull/1421

**Comment by jithunnair-amd** [comment]
All ROCm build jobs passed
@pytorchbot merge -ic

**Comment by jithunnair-amd** [comment]
All ROCm build jobs passed
@pytorchbot merge -i

**Pull request closed without merging**
