### PR TITLE
Add shape function for prims::squeeze op

### PR DESCRIPTION
**Pull request by vivekkhandelwal1**

### CODE REVIEW

**Comment by vivekkhandelwal1** [comment]
@eellison @Gamrix Could you please review this PR?

**Comment by vivekkhandelwal1** [comment]
Hi @eellison, can you please review this PR?

**Comment by vivekkhandelwal1** [comment]
Hi @Chillee, can you please help in getting this PR reviewed?

**Review by eellison — APPROVED** [review]

**Comment by vivekkhandelwal1** [comment]
> Looks good but you have some failing tests

@eellison Do you have any suggestions on how to get those tests passed?

**Comment by vivekkhandelwal1** [comment]
> > Looks good but you have some failing tests
> 
> @eellison Do you have any suggestions on how to get those tests passed?

@eellison Is there a way to run these tests locally?

**Comment by vivekkhandelwal1** [comment]
Closing this PR, since it's not required anymore.

**Pull request closed without merging**
