### PR TITLE
Port Inductor dataclasses to be kw_only

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #137410
* #137861
* #137859
* #137857
* __->__ #137768

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
looks like you got tests to fix though

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change, but it seem to fail test_loop_ordering in trunk' -c landrace

inductor/test_loop_ordering.py::ImplDetailTest::test_reorder_and_merge_loops [GH job link](https://github.com/pytorch/pytorch/actions/runs/11315363157/job/31467142183) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/65d665bae5b82a54b819c0c4527e7ccf88d19427)

**Pull request closed without merging**
