### PR TITLE
Pin destination memory for cuda_tensor.to("cpu", non_blocking=True)

### LINKED ISSUE #39694: gpu_tensor.to("cpu", non_blocking=True) is blocking
## 🐛 Bug

```
>>> a = torch.tensor(100000, device="cuda")
>>> b = a.to("cpu", non_blocking=True)
>>> b.is_pinned()
False
```

The cpu dst memory is created as pageable, so the memcpy is host blocking (["For transfers from device memory to pageable host memory, the function will return only once the copy has completed."](https://docs.nvidia.com/cuda/cuda-runtime-api/api-sync-behavior.html#api-sync-behavior)).  We have one user with evidence that the pageable memcpy also blocks side streams (ie DALI dataloader streams).

Fix might be as simple as setting [options.pinned_memory](https://github.com/pytorch/pytorch/blob/c767d65cafc2615bcee9ec1bbc8d5dadc07ea0e8/c10/core/TensorOptions.h#L216) for the new dst tensor around [here](https://github.com/pytorch/pytorch/blob/1f7557d173c8e9066ed9542ada8f4a09314a7e17/aten/src/ATen/native/TensorConversions.cpp#L24) in to_impl.  I'd PR it myself but if it turns out to be a rabbit hole (for example, since pinned cpu memory is a valuable resource, do we want the returned tensor to live in pinned cpu memory by default, or do we want `to` to include a further host-side memcopy or unpinning such that the returned tensor lives in pageable memory?) I can't afford to go down another rabbit hole right this second.  Filing now so we don't forget.

cc @ngimel @VitalyFedyunin

### PR DESCRIPTION
**Pull request by mcarilli**
Fixes https://github.com/pytorch/pytorch/issues/39694.

[`torch.cuda._sleep(int(100 * get_cycles_per_ms()))`](https://github.com/pytorch/pytorch/pull/46878/files#diff-893b1eea27352f336f4cd832919e48d721e4e90186e63400b8596db6b82e7450R511-R513) in the test helps avoid flakiness noted by @ngimel (https://github.com/pytorch/pytorch/pull/35144#issuecomment-602103631).

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by xw285cornell** [comment]
Thanks for the improvement! Re-importing to make sure internal tests pass

**Comment by xw285cornell** [comment]
rocm test failure is related, @jeffdaily  could you take a look? Maybe we can skip the test for rocm to unblock for now.

**Comment by mcarilli** [comment]
> Can you make sure that at least this test doesn't error out on ROCm?

moved it to a separate tests that's not skipIfRocm.

**Comment by jeffdaily** [comment]
We haven't had a chance to look into this yet.  skipIfRocm is suitable for now.

**Comment by mcarilli** [comment]
pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test1 
pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test2
failures are mysterious.  They don't look related, but https://ezyang.github.io/pytorch-ci-hud/build/pytorch-master shows they're clean, so it's possible my diffs DO somehow make them fail.

**Comment by xw285cornell** [comment]
The test failure does seem to be related: 

Oct 27 19:24:51   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1088, in all_reduce
Oct 27 19:24:51     work = _default_pg.allreduce([tensor], opts)
Oct 27 19:24:51 RuntimeError: Only dense CPU tensors can be pinned

Is it possible they're sparse tensors?

**Comment by xw285cornell** [comment]
@mcarilli it's failing test_sparse_all_reduce_sum_cuda, so I guess you also need to check if it's not a sparse tensor.

**Comment by xw285cornell** [comment]
It looks the failed ROCm test is flaky. The failure also happens on the master. I'm going to land this diff: cc. @jeffdaily 

21:13:40 FAIL: test_softmax_cuda_float16 (__main__.TestNNDeviceTypeCUDA)

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm3.8-py3.6-test1/3282//console
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm3.8-py3.6-test1/3247//console
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm3.8-py3.6-test1/3221//console

**Review by xw285cornell — APPROVED** [review]

**Comment by jeffdaily** [comment]
Part of the problem seems to be the implementation of `is_cuda`.  We have `is_cuda` and `is_hip`, as distinct implementations.  
 
https://github.com/pytorch/pytorch/blob/058f43fc514f0505ffd78decbd3191edaf676449/c10/core/TensorImpl.h#L451-L462

Calling `is_cuda` will always fail for ROCm here.

https://github.com/pytorch/pytorch/blob/d3dc55a6b4ba6d6547aba5a731e9f422009a64fe/aten/src/ATen/native/TensorConversions.cpp#L32

**Comment by mcarilli** [comment]
> Part of the problem

part of what problem?  The softmax failure seems unrelated.  What's my ARB here?  Are you saying if I check
```c++
bool pin_out = (non_blocking && (self.is_cuda() || self.is_hip()) && options.device().is_cpu() && ...
```
I should be able to remove `@skipIfRocm` from `test_to_non_blocking`?

**Comment by jeffdaily** [comment]
@mrcarilli the softmax failure is unrelated; it's a flaky test that we're skipping via another PR.

Concerning when we can remove `@skipIfRocm`, changing it to `(self.is_cuda() || self.is_hip())` is necessary but not sufficient.  The `options.device().is_cpu()` check is claiming that the device type is `cuda`, which is wrong.  I'm looking into that next.

In short, I think we just need to skip this test for now, if you want this PR to land ASAP.

**Comment by xw285cornell** [comment]
I'm landing this PR now. Was having some flaky tests internally

**Comment by jeffdaily** [comment]
What is the expected behavior for this test when src==cpu and dst==cuda?  In that case, the src tensor is created on cpu but memory isn't requested as pinned.  For async H2D memcpy, doesn't src need to also be pinned?

**Comment by jeffdaily** [comment]
I was wrong about needing `(self.is_cuda() || self.is_hip())`.  HIP is correctly masquerading as CUDA there.  The new code in this PR works correctly to pin the dst when it's a D2H async copy, even for HIP.

Instead, as mentioned in my last comment, the test might be wrong to assume async H2D copy when the src is not pinned.  The following change allows the `@skipIfRocm` to be removed, since pinning cpu host tensor allows H2D copy to be async.

```diff
diff --git a/test/test_cuda.py b/test/test_cuda.py
index 12fd7c5aae..b9c3198103 100644
--- a/test/test_cuda.py
+++ b/test/test_cuda.py
@@ -526,7 +526,7 @@ class TestCuda(TestCase):
         for dst, try_non_blocking in product(("cuda", "cpu"), (True, False)):
             print(dst, try_non_blocking)
             # Creates source on the opposite device from destination.
-            src = torch.randn(1000000, device="cuda" if dst == "cpu" else "cpu")
+            src = torch.randn(1000000, device="cuda" if dst == "cpu" else "cpu", pin_memory=True if dst == "cuda" else False)
             _test_to_non_blocking(src, try_non_blocking, dst)

     def test_to_cpu_blocking_by_default(self):
```

**Comment by mcarilli** [comment]
```python
src = torch.randn(1000000, device="cuda" if dst == "cpu" else "cpu", pin_memory=True if dst == "cuda" else False)
```
aye, good catch, added that to the test and removed skipIfRocm.

**Comment by xw285cornell** [comment]
I'll cancel the land and ping me when the fix is up

**Comment by mcarilli** [comment]
Change is up.

**Comment by mcarilli** [comment]
Thanks @xw285cornell and @jeffdaily !

**Pull request closed without merging**
