### PR TITLE
[RELAND] [ATen] Update pre-compiled header

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #108150
* __->__ #108149

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by peterbell10** [comment]
@kit1980 ping

**Review by albanD — COMMENTED** [review]
How do we test that?

**Comment by peterbell10** [comment]
There is a CI job which builds with the pre-compiled header:
https://github.com/pytorch/pytorch/actions/runs/6013752734/job/16311883409?pr=108149

**Review by albanD — APPROVED** [review]
Ok!

**Pull request closed without merging**
