### PR TITLE
Replaced _lstsq_helper with internal dispatch

### PR DESCRIPTION
**Pull request by IvanYashchuk**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #54725 Added cuBLAS path for torch.linalg.lstsq
* **#54724 Replaced _lstsq_helper with internal dispatch**
* #54723 Updated linalg.lstsq with NumPy compatible kwarg rcond
* #54722 Modified batched residuals return of torch.linalg.lstsq

Removed at::_lstsq_helper; it is replaced with DEFINE/DECLARE_DISPATCH.

Differential Revision: [D27993747](https://our.internmc.facebook.com/intern/diff/D27993747)

### CODE REVIEW

**Comment by ezyang** [comment]
ACKing native_functions.yaml changes

**Review by mruberry — APPROVED** [review]
Cool cleanup! Stamped!

**Comment by mruberry** [comment]
Unfortunately this picked up a merge conflict and the stack needs to be rebased. Sorry about that, @IvanYashchuk

**Comment by IvanYashchuk** [comment]
@mruberry, thanks for letting me know! I updated the stack, there were a few conflicts in the documentation.

**Comment by samestep** [comment]
To fix the [failing GitHub Actions job](https://github.com/pytorch/pytorch/runs/2451805340), could you please rebase onto dd84224edc154a196630a9c4602b9b18ba4a4b2a or a more recent commit?

**Comment by IvanYashchuk** [comment]
@samestep, done!

**Comment by mruberry** [comment]
Yikes! This accumulated another merge conflict. Sorry @IvanYashchuk, for some reason this stack is turning into a slog. Would you rebase it again? I'm trying to get it landed ASAP.

**Comment by IvanYashchuk** [comment]
Sure, will do it now.

**Pull request closed without merging**
