### PR TITLE
Improved error message for interpolation

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:
- Improved error message for CUDA interpolation with antialiasing 

@jbschlosser could you please check this PR and the wording if the error message is more clear now ? Thank.
I'm skipping all the tests now and once we are agreed on the wording if any updates are required, I update and restart the tests to ensure nothing is broken.

### CODE REVIEW

**Review by jbschlosser — APPROVED** [review]
LGTM!

**Comment by jbschlosser** [comment]
@vfdev-5 going to run CI now?

**Comment by vfdev-5** [comment]
@jbschlosser sorry, I just force-pushed to restart the CI

**Comment by atalman** [comment]
Hey vfdev-5.     You merged this PR, but no release notes category and topic labels were added.     The list of valid release and topic labels is available     https://github.com/pytorch/pytorch/labels?q=release+notes+or+topic

**Comment by vfdev-5** [comment]
@atalman thanks for pinging. I'm not completely sure about which label to add: i'd say this error message can be visible in python, so maybe python_frontend label could be good. Could you please add appropriate label as needed. Thanks

**Pull request closed without merging**
