### PR TITLE
update kineto submodule to 46ede25

### PR DESCRIPTION
**Pull request by jeffdaily**
Roctracer: Implement reliable data flushing on stop

https://github.com/pytorch/kineto/commit/46ede25adf65de7d418240d14bc419640f8bf020

This fixes flaky unit tests that use kineto to verify certain kernels have executed.

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jeffdaily** [comment]
@mwootton your latest kineto PR now as a submodule update for pytorch.  Thanks.

**Comment by ezyang** [comment]
the test failure kind of looks legit?

**Comment by jeffdaily** [comment]
> the test failure kind of looks legit?

Indeed.  And that's why we have CI.  @mwootton is working on fixing his last kineto change.

**Comment by jeffdaily** [comment]
Replaced by https://github.com/pytorch/pytorch/pull/114297.

**Pull request closed without merging**
