### PR TITLE
Delete code coverage jobs from CI

### PR DESCRIPTION
**Pull request by malfet**
As it does not seem useful to the lots of peope, see https://fb.workplace.com/groups/1144215345733672/posts/2062909540530910

cc @ezyang @seemethere @malfet @pytorch/pytorch-dev-infra

### CODE REVIEW

**Review by suo — APPROVED** [review]
thanks for doing this!

**Review by albanD — APPROVED** [review]
ci simplification! 🎉

**Review by janeyx99 — COMMENTED** [review]
This is fine, but are we doing this with the intent of never bringing it back?

**Comment by malfet** [comment]
@janeyx99 at the same time, keeping dead code in the repo is wrong, and if one chooses to they can always revert this PR to restore functionality.

**Review by janeyx99 — APPROVED** [review]

**Comment by malfet** [comment]
Re-basing and waiting for onnx_rt tests

**Comment by malfet** [comment]
onnx_ort test failures were related to an attempt to delete 
https://github.com/pytorch/pytorch/blob/127c9402d0ae7e3f72aa8ec18dbb9b8f12089bae/.jenkins/caffe2/test.sh#L104
which old caffe2 test still rely upon

**Pull request closed without merging**
