### PR TITLE
[FSDP2] Resolved strided sharding todo in clipping tests

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134152

cc @XilunWu @H-Huang @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by XilunWu — APPROVED** [review]

**Review by weifengpy — APPROVED** [review]

**Comment by awgu** [comment]
I tested locally, and the test passes.

**Comment by awgu** [comment]
[trunk / macos-py3-arm64 / test (default, 1, 3, macos-m1-stable)](https://github.com/pytorch/pytorch/actions/runs/10498026816/job/29082347976)
```
A job completed hook has been configured by the self-hosted runner administrator
Error: File doesn't exist
```
failure unrelated to this FSDP unit test change

**Review by wz337 — APPROVED** [review]
LG

**Pull request closed without merging**
