### PR TITLE
Support USE_CUDNN for Windows

### LINKED ISSUE #12495: Windows build with CUDNN
The build script for windows ``tool/buid_pytorch_libs.bat`` explicitely sets USE_CUDNN=OFF. Shouldn't this be set USE_CUDNN=%USE_CUDNN%?

### PR DESCRIPTION
**Pull request by orionr**
Fixes https://github.com/pytorch/pytorch/issues/12495

cc @peterjc123 @mingzhe09088

### CODE REVIEW

**Comment by peterjc123** [comment]
The build failure is caused by some changes else. We should retest this PR when the master branch is fixed.

**Review by soumith — APPROVED** [review]

**Comment by orionr** [comment]
Windows build passed so landing.

**Comment by fmder** [comment]
@orionr I think the setup.py would also have to set the environment variable USE_CUDNN.

**Comment by orionr** [comment]
@fmder, you are right! I thought we were already setting it there. Changing.

**Comment by orionr** [comment]
In reality, what we need to do here is *not* set it in `build_pytorch_libs.bat` and `CMakeLists.txt` will default `USE_CUDNN=ON` based on the value of `USE_CUDA`. This is how `build_pytorch_libs.sh` does it on *nix and macOS. Thanks for the catch @fmder!

Unfortunately we'll need to wait until Windows tests pass on master before we land this again. Also, I'll verify USE_CUDNN=ON in the summary output when we get a successful run.

**Pull request closed without merging**
