### PR TITLE
[Draft] Removes named tensors

### PR DESCRIPTION
**Pull request by mruberry**
To be written

cc @zou3519

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Autograd part looks good.
Shouldn't this be deprecated for at least one release though?
Since the branch cut is in a month, that would only delay this PR by one month as we can land it just after the 1.12 branch cut.

**Comment by mruberry** [comment]
> Autograd part looks good. Shouldn't this be deprecated for at least one release though? Since the branch cut is in a month, that would only delay this PR by one month as we can land it just after the 1.12 branch cut.

Named tensors are an experimental feature so there's no requirement we deprecate them, and there's no workaround we can point people to.

**Review by jbschlosser — COMMENTED** [review]
Whoo nice cleanup! For review and landing purposes, I'll suggest possibly splitting this up into some number of PRs removing named tensor usage from the various kernels followed by the final purge of the named tensor internals themselves.

**Comment by adscib** [comment]
Does this mean that named tensors are getting removed from pytorch altogether, or am I misunderstanding what's going on here?

**Comment by mruberry** [comment]
> Does this mean that named tensors are getting removed from pytorch altogether, or am I misunderstanding what's going on here?

We sometimes discuss the merits of removing named tensors or refactoring them to be a tensor subclass, but no decision has been made.

**Comment by adscib** [comment]
> > Does this mean that named tensors are getting removed from pytorch altogether, or am I misunderstanding what's going on here?
> 
> We sometimes discuss the merits of removing named tensors or refactoring them to be a tensor subclass, but no decision has been made.

Thanks for the quick reply.  I love named tensors and hope you choose to keep them.

**Comment by ezyang** [comment]
@adscib Check out first class dimensions https://github.com/facebookresearch/torchdim which we are moving into core soon, and is going to replace named tensors

**Comment by adscib** [comment]
Nice. Thanks for the pointer, I'll check it out.

**Pull request closed without merging**
