### PR TITLE
Skips flaky UtilsNMSTest.GPUEqualsCPURotatedCorrectnessTest

### PR DESCRIPTION
**Pull request by mruberry**
See https://github.com/pytorch/pytorch/issues/26811.

### CODE REVIEW

**Comment by mruberry** [comment]
It looks like several builds have been running for 8+ hours (as of this writing) despite actually having completed?

**Comment by ezyang** [comment]
That happens when CircleCI posting statuses to GH gets rate limited.

**Comment by ezyang** [comment]
FWIW, in the future, just use `#if 0` ;)

**Review by ezyang — APPROVED** [review]

**Comment by mruberry** [comment]
> FWIW, in the future, just use `#if 0` ;)

Sounds good ;)

**Pull request closed without merging**
