### PR TITLE
Add unfold to autograd

### PR DESCRIPTION
**Pull request by fmassa**
Unfold is very handy whenever we want to perform operations in local neighbourhoods (like in convolutions or poolings).

For example, 2d max-pooling can be alternatively computed as follows:
```python
def max_pool2d(input, kernel_size, stride):
    kh, kw = kernel_size
    dh, dw = stride
    # get all image windows of size (kh, kw) and stride (dh, dw)
    input_windows = input.unfold(2, kh, dh).unfold(3, kw, dw)
    # view the windows as (kh * kw)
    input_windows = input_windows.contiguous().view(*input_windows.size()[:-2], -1)
    max_val, max_idx = input_windows.max(4)
    return max_val, max_idx
```

### CODE REVIEW

**Review by apaszke — APPROVED** [review]
Damn, backward will need a lot of memory for `idx_unfolded`, right?

**Comment by apaszke** [comment]
Can you please fix the conflicts?

**Comment by fmassa** [comment]
I think the conflicts were fixed.
The amount of memory needed for `idx_unfolded` will be roughly `input_numel * size / stride`, so it's not a huge increase for small neighborhood sizes. But it is more memory hungry if applied several times (for 2d conv for example) than a dedicated implementation of `im2col`.

**Comment by apaszke** [comment]
I'm wondering if it wouldn't be better to wait for the `im2col` kernels 😕

**Comment by fmassa** [comment]
If we have a `Nd` im2col (which works on 1d, 2d and 3d data), then I'm fine with closing this PR.
In such cases, we should probably remove unfold from pytorch as well :p

**Comment by soumith** [comment]
dude let's just merge this in. we can always remove it later. waiting for xxx where we don't know the timeline is not worth it

**Comment by apaszke** [comment]
Ok. There are still some conflicts though

**Pull request merged**
