### PR TITLE
[Resubmit] Migrate AT_DISPATCH_ALL_TYPES_AND_COMPLEX_AND3 to c10::complex

### PR DESCRIPTION
**Pull request by zasdfgbnm**
This reverts commit 0c936f94d647a2c422d29cafaa923047dd243473.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
The solution should be

```C++
#if defined(CUDA_VERSION) && (CUDA_VERSION < 10000)
#define CUDA92_BUG(x) thrust::complex<T>(x.real(), x.imag())
#else
#define CUDA92_BUG(x) x
#endif

template<typename T>
C10_HOST_DEVICE T abs(const c10::complex<T>& z) {
#if defined(__CUDACC__) || defined(__HIPCC__)
  return thrust::abs(static_cast<thrust::complex<T>>(CUDA92_BUG(z)));
#else
  return std::abs(static_cast<std::complex<T>>(z));
#endif
}

#undef CUDA92_BUG
```

**Comment by zasdfgbnm** [comment]
@anjali411 This is ready

**Review by anjali411 — APPROVED** [review]

**Comment by jeffdaily** [comment]
@anjali411 This PR has caused ROCm tests to fail.  Still investigating whether we can fix or need to revert.

**Comment by gchanan** [comment]
can I merge https://github.com/pytorch/pytorch/pull/38274 before we try to land this again?

**Comment by jeffdaily** [comment]
@gchanan I think all issues are now resolved with this PR between #38363  and quickly followed by #38380 .  Those PRs should land soon.

**Pull request closed without merging**
