### PR TITLE
Adds requires_grad flag to torch.from_numpy

### PR DESCRIPTION
**Pull request by ssnl**

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@SsnL If you want a once over from someone who knows how the Python argument parser works, ping them; otherwise feel free to merge.

**Comment by gchanan** [comment]
The parsing looks good.

I'm a bit concerned about the change though...we don't allow requires_grad in `Tensor.numpy`, but we allow it (and in fact put it as part of the factory) in `from_numpy`?

**Comment by SsnL** [comment]
abort since the numpy ops cannot be tracked.

**Comment by fmassa** [comment]
@gchanan can you please expand on your comment, I didn't quite follow it.
Is it related to having the same numpy array viewed by two (or more) different tensors that require grad?

**Comment by SsnL** [comment]
@fmassa The issue is that if the Tensor is needed in backward, but the NumPy array that shares storage is modified, we can't track it.

**Comment by apaszke** [comment]
That's true, but I don't think we can do anything to prevent `torch.from_numpy(img).attach()`, which is equivalent.

**Comment by gchanan** [comment]
You could presumably mark it's a "from numpy" tensor and not allow attaching it.  I'm not sure we want to do any of that, though.

**Pull request closed without merging**
