### PR TITLE
Remove backward ops for miopen transposed convolution

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70064
* __->__ #70063
* #69987

Differential Revision: [D33171170](https://our.internmc.facebook.com/intern/diff/D33171170)

### CODE REVIEW

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33171170).

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33171170).

**Comment by jbschlosser** [comment]
ping @albanD for review since you reviewed the other miopen one :)

**Review by albanD — APPROVED** [review]
Sounds good!

**Pull request closed without merging**
