### PR TITLE
Remove is_aot_autograd_safe_to_run

### PR DESCRIPTION
**Pull request by voznesenskym**
This should be alright to remove now, because we:

1) Support LSTM
2) AOT_Autograd can cover its own mutation detection

cc @mlazos @soumith @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
Sick!

**Review by bdhirsh — APPROVED** [review]
thanks!

**Pull request closed without merging**
