### PR TITLE
Use hipsolver for default svd case on ROCm

### LINKED ISSUE #102558: DISABLED test_pca_lowrank_cuda (__main__.TestLinalgCUDA)
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_linalg.py%3A%3ATestLinalgCUDA%3A%3Atest_pca_lowrank_cuda)).

### LINKED ISSUE #102629: DISABLED test_svd_lowrank_cuda_float64 (__main__.TestLinalgCUDA)
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_linalg.py%3A%3ATestLinalgCUDA%3A%3Atest_svd_lowrank_cuda_float64)).

Seems like introduced by https://github.com/pytorch/pytorch/pull/97370. cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @alugorey

### LINKED ISSUE #102678: DISABLED test_compare_cpu_linalg_pinv_singular_cuda_float32 (__main__.TestCommonCUDA)
Platforms: rocm

started after https://github.com/pytorch/pytorch/pull/97370? cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @alugorey

```
2023-06-01T00:28:57.8447511Z Traceback (most recent call last):
2023-06-01T00:28:57.8447800Z   File "test_ops.py", line 287, in test_compare_cpu
2023-06-01T00:28:57.8448231Z     self.assertEqual(cuda_results, cpu_results, atol=1e-3, rtol=1e-3)
2023-06-01T00:28:57.8448795Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 3094, in assertEqual
2023-06-01T00:28:57.8449172Z     raise error_metas[0].to_error(
2023-06-01T00:28:57.8449512Z AssertionError: Tensor-likes are not close!
2023-06-01T00:28:57.8449694Z 
2023-06-01T00:28:57.8449810Z Mismatched elements: 2286 / 2500 (91.4%)
2023-06-01T00:28:57.8450145Z Greatest absolute difference: 0.057559624314308167 at index (24, 7) (up to 0.001 allowed)
2023-06-01T00:28:57.8450508Z Greatest relative difference: 1.0 at index (0, 0) (up to 0.001 allowed)
```

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_ops.py%3A%3ATestCommonCUDA%3A%3Atest_compare_cpu_linalg_pinv_singular_cuda_float32)).

### PR DESCRIPTION
**Pull request by alugorey**
Fixes #102678 
Fixes #102629
Fixes #102558
HipSOLVER performance on ROCm5.4.2 and later no longer serves as massive bottleneck. Additionally, using magma on rocm in this case caused test_compare_cpu_lialg_pinv_singular_cuda_float32 to fail. Using hipSOLVER, the test now passes.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by lezcano — APPROVED** [review]

**Comment by alugorey** [comment]
After doing some internal testing, discovered these tests need ROCm 5.5. @huydhn we can revert this revert once https://github.com/pytorch/pytorch/pull/103092 gets merged

**Comment by huydhn** [comment]
Once https://github.com/pytorch/pytorch/pull/103092 lands, you could simply rebase this PR and merge it again when tests pass.

**Pull request closed without merging**
