### PR TITLE
[Reopen] Upgrade submodule oneDNN to v3.4.2

### PR DESCRIPTION
**Pull request by Xia-Weiwen**
Reopen of https://github.com/pytorch/pytorch/pull/122472

## Improvements
This upgrade fixes the following issues:
- https://github.com/pytorch/pytorch/issues/120982

This upgrade brings the following new features:
- Introduced memory descriptor serialization API. This API is needed to support freezing on CPU in AOTInductor (https://github.com/pytorch/pytorch/issues/114450)

## Validation results on CPU
Original results with oneDNN v3.4.1 are here: https://github.com/pytorch/pytorch/pull/122472#issue-2201602846

Need to rerun validation and update results.
**Results of reruns**

1. Torchbench cpu userbenchmark inference & training

Perf_Geomean | Ratio   (oneDNN v3.4.2/baseline)
-- | --
eager_throughtput_bf16_infer | 1.00x
eager_throughtput_fp32_infer | 1.00x
jit_llga_throughtput_amp_bf16 | 0.99x
jit_llga_throughtput_fp32 | 1.00x
eager_throughtput_fx_int8 | 1.01x
eager_throughtput_bf16_train | 0.99x
eager_throughtput_fp32_train | 0.99x

2. Dynamo benchmarks

Precision | Shape | Wrapper | Thread | Eager Ratio old/new GEOMEAN | Inductor Ratio old/new GEOMEAN
-- | -- | -- | -- | -- | --
Float32 | Static | Default | Multiple | 1.010737 | 1.019399
Float32 | Static | Default | Single | 1.002681 | 1.001732
Float32 | Dynamic | Default | Multiple | 1.006492 | 1.007722
Float32 | Dynamic | Default | Single | 1.003639 | 1.002965
AMP | Static | Default | Multiple | 1.001126 | 1.005045
AMP | Static | Default | Single | 0.995729 | 0.994613
AMP | Dynamic | Default | Multiple | 0.995276 | 0.998698
AMP | Dynamic | Default | Single | 0.997459 | 0.993833

All tests geomean ratio is good, but detected 1 model AMP training performance drop with oneDNN v3.4.2 as below. The issue has been reported to oneDNN team.

model_name | oneDNN   v3.4.2 | baseline | throughput   ratio(new/old)
-- | -- | -- | --
pytorch_stargan-train_throughput | 69.759 | 85.378 | 0.8171

Dynamo benchmarks

Precision | Shape | Wrapper | Thread | Ratio   old/new GEOMEAN | Ratio   old/new GEOMEAN
-- | -- | -- | -- | -- | --
  |   |   |   | Eager | Inductor
Float32 | Static | Default | Multiple | 1.010736824 | 1.019399
  |   |   | Single | 1.002680965 | 1.001732
Float32 | Dynamic | Default | Multiple | 1.006492275 | 1.007722
  |   |   | Single | 1.003638601 | 1.002965
AMP | Static | Default | Multiple | 1.001125822 | 1.005045
  |   |   | Single | 0.99572873 | 0.994613
AMP | Dynamic | Default | Multiple | 0.995275854 | 0.998698
  |   |   | Single | 0.99745925 | 0.993833

Inductor benchmarks

Dtype | Throughput   ratio new/old Geomean
-- | --
all | 99.60%
fp32 | 99.84%
bf16 | 99.55%
int8 | 99.08%
fp16 | 99.86%

---

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @snadampal

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Comment by Xia-Weiwen** [comment]
Hi @snadampal Please help check if the aarch64 failure is related to oneDNN upgrade. If yes, please help investigate. If no, we will start validation on x86 CPU.

**Comment by milpuz01** [comment]
I think the problem here is that when we are building wheel (is this script used: https://github.com/pytorch/builder/blob/ead2e21b24038ed9117060bb2c00bc79c4e91d85/aarch64_linux/aarch64_wheel_ci_build.py#L81 to build `linux-jammy-aarach64-py3.10` wheel or something else?) for CI it is using ACL 23.08 version where definition of `Conv2dInfo` has as one of the arguments `experimental::PostOpList` that got removed in ACL 23.11+ and updated in oneDNN 3.4.2 not to call it: https://github.com/oneapi-src/oneDNN/blob/1137e04ec0b5251ca2b4400a4fd3c667ce843d67/src/cpu/aarch64/acl_indirect_gemm_convolution.hpp#L49.

@snadampal is this right? Should CI build script be updated to use ACL 23.11+ to build with oneDNN 3.4+?

**Comment by snadampal** [comment]
@Xia-Weiwen , the CI failure is because oneDNN3.4 requires ACL version update, here is the PR:https://github.com/pytorch/pytorch/pull/125549
both these PRs are inter-dependent.

Hi @atalman , could you please suggest how we can handle this dependency. one option is to merge aarch64-linux CI PR (https://github.com/pytorch/pytorch/pull/125549) first, so that the CI will be ready to test oneDNN 3.4 on aarch64-linux.

**Comment by snadampal** [comment]
Yes, @milpuz01 , it was the ACL version, i added the details above.

**Comment by atalman** [comment]
hi @snadampal and @Xia-Weiwen merging both PRs sounds like a good solution. @Xia-Weiwen could you please add this commit on top of this PR: https://github.com/pytorch/pytorch/pull/125549/commits/091f84e0484441722fcca9e266e00c2cdab22a61 ?

**Comment by Xia-Weiwen** [comment]
Hi @atalman @snadampal @milpuz01 I have added the commit https://github.com/pytorch/pytorch/commit/091f84e0484441722fcca9e266e00c2cdab22a61 on top of this PR.

**Review by snadampal — APPROVED** [review]

**Review by atalman — APPROVED** [review]

**Comment by Guobing-Chen** [comment]
> Update oneDNN v3.4.2 acceptance test reports
> 
> 1. Torchbench cpu userbenchmark inference & training
> 
> Perf_Geomean	Ratio (oneDNN v3.4.2/baseline)
> eager_throughtput_bf16_infer	1.00x
> eager_throughtput_fp32_infer	1.00x
> jit_llga_throughtput_amp_bf16	0.99x
> jit_llga_throughtput_fp32	1.00x
> eager_throughtput_fx_int8	1.01x
> eager_throughtput_bf16_train	0.99x
> eager_throughtput_fp32_train	0.99x
> 2. Dynamo benchmarks
> 
> Precision	Shape	Wrapper	Thread	Eager Ratio old/new GEOMEAN	Inductor Ratio old/new GEOMEAN
> Float32	Static	Default	Multiple	1.010737	1.019399
> Float32	Static	Default	Single	1.002681	1.001732
> Float32	Dynamic	Default	Multiple	1.006492	1.007722
> Float32	Dynamic	Default	Single	1.003639	1.002965
> AMP	Static	Default	Multiple	1.001126	1.005045
> AMP	Static	Default	Single	0.995729	0.994613
> AMP	Dynamic	Default	Multiple	0.995276	0.998698
> AMP	Dynamic	Default	Single	0.997459	0.993833
> All tests geomean ratio is good, but detected 1 model AMP training performance drop with oneDNN v3.4.2 as below. The issue has been reported to oneDNN team. @atalman any comments on it?
> 
> model_name	oneDNN v3.4.2	baseline	throughput ratio(new/old)
> pytorch_stargan-train_throughput	69.759	85.378	0.8171

Thanks for Chuanqi's testing result, @vpirogov, could you also help comment the potential impact of this outlier?

**Pull request closed without merging**
