### PR TITLE
[AOTI] Support module buffer mutation

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #123164

Summary: Fixes https://github.com/pytorch/pytorch/issues/120424. Because in a forward pass module buffers may be mutated, we need to allow that in AOTI. In addition, this will be a necessary step if we want to extend AOTI to training.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @chauhang

### CODE REVIEW

**Review by digantdesai — APPROVED** [review]
Stamping

**Review by malfet — APPROVED** [review]
LGTM (provided that Mac CI is green)

**Review by chenyang78 — APPROVED** [review]

**Review by khabinov — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@desertfire This is the second recent AOTI-related PR that has broken ROCm CI due to nosignal; the other one was [122882](https://github.com/pytorch/pytorch/pull/122882). Since the only ROCm CI jobs that run by default on AOTI PRs are the ones for `ciflow/trunk` (pre-merge checks) and `ciflow/inductor` (auto-label by bot), and neither of those currently run test_aot_inductor.py, there is no CI signal on the PR indicating a ROCm breakage (we can't run the entire list of test suites on PRs due to CI capacity constraints). To remedy this, I propose adding `inductor/test_aot_inductor` to the inductor workflow here: https://github.com/pytorch/pytorch/blob/9288b274611abc904a67d9cb02c837aa2cb769fd/.ci/pytorch/test.sh#L318

It seems like it would add about an hour more to the inductor workflow test jobs for both CUDA and ROCm. Would that be acceptable?

cc @huydhn @malfet

**Comment by atalman** [comment]
@desertfire Please provide forward fix for this issue this is a failing test on the trunk:
```
024-04-03T07:37:22.3706672Z =========================== short test summary info ============================
2024-04-03T07:37:22.3707311Z FAILED [6.3134s] inductor/test_aot_inductor.py::AOTInductorTestABICompatibleCuda::test_buffer_mutation_3_abi_compatible_cuda - AssertionError: False is not true
2024-04-03T07:37:22.3707315Z 
2024-04-03T07:37:22.3707505Z To execute this test, run the following from the base repo dir:
2024-04-03T07:37:22.3707879Z     PYTORCH_TEST_WITH_ROCM=1 python test_aot_inductor.py -k test_buffer_mutation_3_abi_compatible_cuda
2024-04-03T07:37:22.3707883Z 

``

**Pull request closed without merging**
