### PR TITLE
enable cuda11.1 and cudnn 8.0.5 in CI

### PR DESCRIPTION
**Pull request by mszhanyi**

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Review by zasdfgbnm — APPROVED** [review]

**Review by walterddr — APPROVED** [review]

**Comment by peterjc123** [comment]
Do we need to update the driver as well? Since there is no test jobs here running for CUDA 11 on Windows, right?

**Comment by peterjc123** [comment]
The master is failing with the following error.
```
(base) circleci@PACKER-5FAA87D3 C:\Users\circleci\project\test>python run_test.py --include test_nn --verbose --determine-from="""" 
Selected tests: test_nn
Running test_nn ... [2020-11-20 04:24:38.130407]
Executing ['coverage', 'run', '--parallel-mode', '--source=torch', 'test_nn.py', '-v'] ... [2020-11-20 04:24:38.130407]
No data to combine
Traceback (most recent call last):
  File "run_test.py", line 873, in <module>
    main()
  File "run_test.py", line 856, in main
    raise RuntimeError(err_message)
RuntimeError: test_nn failed!
```
Just like I said before, the graphics driver is very likely the cause.

**Comment by mszhanyi** [comment]
I think I have no permission to

**Comment by peterjc123** [comment]
@mszhanyi I'm fixing it with https://github.com/pytorch/pytorch/pull/48298.

**Comment by peterjc123** [comment]
Unluckily, we may have to revert it because there is no CUDA 11.1 driver for it.

**Comment by peterjc123** [comment]
@xwang233 Do you know where can we get the Nvidia GPU driver for CUDA 11.1 on Windows?

**Comment by zasdfgbnm** [comment]
@peterjc123 I don't know. I am asking internally for it.

**Comment by malfet** [comment]
Reverting the PR, as CI is broken, see https://app.circleci.com/pipelines/github/pytorch/pytorch/241635/workflows/14caa68b-5dd2-49de-8f06-b3c4fc20c165/jobs/9080882

**Comment by xwang233** [comment]
@peterjc123 As a temporary workaround, can you try if the cuda 11.1 Windows installer has a bundled driver installer inside? It says `cuda_11.1.1_456.81_win10.exe`. 

https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal

**Comment by peterjc123** [comment]
@xwang233 Thanks for the reply. Testing with https://github.com/pytorch/pytorch/pull/48469.

**Pull request closed without merging**
