### PR TITLE
Fix typos in ATen README

### PR DESCRIPTION
**Pull request by nkaretnikov**

### CODE REVIEW

**Comment by nkaretnikov** [comment]
just a quick pr made from the web ui to fix some typos i noticed while reading the doc

**Review by H-Huang — APPROVED** [review]
Thanks!

**Comment by H-Huang** [comment]
@nkaretnikov, can you sign the [CLA](https://code.facebook.com/cla) so that we can merge this PR.

**Comment by nkaretnikov** [comment]
@H-Huang i need to sign the corporate one. the company i'm contributing thru submitted a request to meta to add me to the existing corporate cla. waiting for someone from meta to act on that, so might take a while.

**Comment by H-Huang** [comment]
@nkaretnikov, sounds good. Just re-request my review when it is approved

**Review by H-Huang — APPROVED** [review]

**Pull request closed without merging**
