### PR TITLE
OpInfo: specifying sparse sample input function implies the corresponding layout support

### PR DESCRIPTION
**Pull request by pearu**
As in the title.

The PR fixes an issue of silently skipping tests as described in #100391.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #98292
* #100394
* #100393
* __->__ #100392
* #100391
* #100389

### CODE REVIEW

**Review by pmeier — APPROVED** [review]
Thanks!

**Comment by pearu** [comment]
@cpuhrsch could you stamp this PR?

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
