### PR TITLE
Use global variables to register the return_types namedtuples

### LINKED ISSUE #69221: torch.return_types: simplify implementation
## 🚀 Feature

Follow up to this thread: https://github.com/pytorch/pytorch/pull/66614#discussion_r745505413

The implementation of torch.return_types uses a static map. This unfortunately duplicates the memory needed for torch.return_types (but the total memory needed is not that much). We should try to get rid of the map by turning the entries in the map into globals that get set during initialization and used directly.

## Motivation

Decrease the amount of memory used by PyTorch; also Better Engineering

## Pitch

We should try to get rid of the map by turning the entries in the map into globals that get set during initialization and used directly.

## Alternatives

Use a constexpr map. This seems like overkill

## Additional context

n/a

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

### PR DESCRIPTION
**Pull request by andreigh**
Fixes #69221. Builds on top of #107000, fixing the buck build issue linked [here](https://github.com/pytorch/pytorch/pull/107000#issuecomment-1708857375).

### CODE REVIEW

**Comment by andreigh** [comment]
@pytorchbot label "suppress-api-compatibility-check"
@pytorchbot label "suppress-bc-linter"

Disabled BC Linter [which is detecting](https://github.com/pytorch/pytorch/actions/runs/5861630234/job/15892079506) the deletion of the "generate_return_type_definition_and_map_entry" function

**Review by zou3519 — APPROVED** [review]
thanks for fixing the build issue!

**Comment by zou3519** [comment]
Triggering some more jobs to confirm that we've fixed the failure (ciflow/periodic)

**Comment by malfet** [comment]
Those kind of problems would undoubtedly cause internal build failures, so it should have been landed via codev

**Pull request closed without merging**
