### PR TITLE
Add eager_compile_backwards_failure to tlparse

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #130434

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Comment by ezyang** [comment]
However, I did a test at https://github.com/pytorch/pytorch/pull/130435 that suggests that this codepath is completely dead, so maybe we could also just remove it entirely.

**Comment by ezyang** [comment]
It's actually not dead according to Scuba logs internally, and also it is unavoidable because some error cases are due to data dependent guard

**Comment by ezyang** [comment]
So I do want to merge this as is

**Review by albanD — APPROVED** [review]
SGTM!

**Pull request closed without merging**
