### PR TITLE
`linalg.matrix_rank`: fix cpp interface + add more overloads

### PR DESCRIPTION
**Pull request by nikitaved**
As per title. 

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
This is still missing adding the same functions down below in the file, right? As it stands, these functions are in the `detail::` namespace.
https://github.com/pytorch/pytorch/blob/7180582bfa11a8922f1f46f0d61f85d5c353f256/torch/csrc/api/include/torch/linalg.h#L419-L426

**Comment by nikitaved** [comment]
These are `torch.matrix_rank`-related functions, not `linalg`.

**Review by lezcano — APPROVED** [review]
LGTM!

**Comment by IvanYashchuk** [comment]
I wonder why do we use the `detail::` namespace

**Comment by nikitaved** [comment]
I am wondering just the same. Have not seen it before.

**Review by mruberry — APPROVED** [review]
Looks like this got lost in the shuffle; sorry about that @nikitaved! I'll try and merge this now.

**Pull request closed without merging**
