### PR TITLE
Apply UFMT to all files in benchmarks/

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105928

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @albanD

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Only checked the lintrunner config update. Any file there was manually changed?

**Comment by ezyang** [comment]
No

**Pull request closed without merging**
