### PR TITLE
Remove F.pad python implementation

### LINKED ISSUE #73401: Move F.pad into ATen
## Issue description
`torch.nn.functional.pad` is currently implemented in python,
https://github.com/pytorch/pytorch/blob/abb55c53b3faf41fb1b2e9a69a1ca7b49c3e5b1b/torch/nn/functional.py#L4302

Which forces other functions to be defined in python, including `torch.stft`. Instead, the function should be moved to into `ATen`.

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #73434
* __->__ #73433
* #75896

Closes #73401

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!

**Review by jbschlosser — APPROVED** [review]
Beautiful, good riddance to the python impl

**Comment by zengk95** [comment]
@pytorchbot revert this

Reverting this entire stack as it's breaking 
see https://hud.pytorch.org/pytorch/pytorch/commit/cb37e7a080e17edc6d417a0a3d731fe526cfc801

**Pull request closed without merging**
