### PR TITLE
[6/N][BE] Remove Sharded Linear Op for ShardedTensor

### PR DESCRIPTION
**Pull request by fduwjj**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #95949
* __->__ #95948
* #95947

Differential Revision: [D43877082](https://our.internmc.facebook.com/intern/diff/D43877082)

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]

**Comment by fduwjj** [comment]
@fduwjj has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D43877082).

**Comment by huydhn** [comment]
@fduwjj I suspect that this PR causes a failed test in CI periodic multigpu test, for example https://hud.pytorch.org/pytorch/pytorch/commit/893aa5df3f2a475c91ea8eadb1353812e52fb227.  The error is

```
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 657, in run_test
    getattr(self, test_name)()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 543, in wrapper
    fn()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 174, in wrapper
    return func(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/distributed/fsdp/test_fsdp_tp_integration.py", line 469, in test_fsdp_tp_checkpoint_integration
    tp_fsdp_model(inp).sum().backward()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/var/lib/jenkins/workspace/test/distributed/fsdp/test_fsdp_tp_integration.py", line 178, in forward
    return self.net3(self.net2(self.relu(self.net1(x))))
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/distributed/_shard/sharded_tensor/api.py", line 1098, in __torch_function__
    return dispatch(st_instance, func)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/distributed/_shard/sharded_tensor/api.py", line 1081, in dispatch
    raise RuntimeError(
RuntimeError: torch function 'linear', with args: (tensor([[[0.7576, 0.2793, 0.4031, 0.7347, 0.0293],
         [0.7999, 0.3971, 0.7544, 0.5695, 0.4388],
         [0.6387, 0.5247, 0.6826, 0.3051, 0.4635]],

        [[0.4550, 0.5725, 0.4980, 0.9371, 0.6556],
         [0.3138, 0.1980, 0.4162, 0.2843, 0.3398],
         [0.5239, 0.7981, 0.7718, 0.0112, 0.8100]]], device='cuda:0'), ShardedTensor(ShardedTensorMetadata(shards_metadata=[ShardMetadata(shard_offsets=[0, 0], shard_sizes=[4, 5], placement=rank:0/cuda:0), ShardMetadata(shard_offsets=[4, 0], shard_sizes=[4, 5], placement=rank:1/cuda:1)], size=torch.Size([8, 5]), tensor_properties=TensorProperties(dtype=torch.float32, layout=torch.strided, requires_grad=True, memory_format=torch.contiguous_format, pin_memory=False))), tensor([ 0.0235, -0.2293,  0.0757, -0.4176, -0.3231, -0.2306,  0.2822,  0.2622],
       device='cuda:0', grad_fn=<ViewBackward0>)) and kwargs: None not supported for ShardedTensor!
```

Should that test also need to be removed as part of this change to remove linear ops for sharded tensor?  Please help take a look

**Comment by fduwjj** [comment]
@huydhn I will send a forward fix for that. Not sure why this was not captured in CI flow.

**Comment by huydhn** [comment]
> @huydhn I will send a forward fix for that. Not sure why this was not captured in CI flow.

Thank you for looking into this. That test is periodic, so it only runs every 4 hours or so.  You could add 'ciflow/periodic` in your PR to have it running.  It's ok to forward fix periodic tests though

**Comment by fduwjj** [comment]
@huydhn Fixed in https://github.com/pytorch/pytorch/pull/96254.

**Pull request closed without merging**
