### PR TITLE
Fix the example of torch.slice_scatter

### LINKED ISSUE #107681: example can not run successfully
### 📚 The doc issue

https://pytorch.org/docs/main/generated/torch.slice_scatter.html#torch-slice-scatter In this page, the example can not run successfully. The error is "RuntimeError: expected src to have a size equal to the slice of self. src size = [8], slice size = [2, 8]"

### Suggest a potential alternative/fix

_No response_

### PR DESCRIPTION
**Pull request by fffrog**
Fixes #107681
fix the example of torch.slice_scatter

### CODE REVIEW

**Comment by drisspg** [comment]
Thank you!

**Review by drisspg — APPROVED** [review]

**Comment by FFFrog** [comment]
Sorry to bother @drisspg, the pr was not successfully merged because the pr was closed before it was merged, I'm not sure if it's a mistake or something else needs to be changed in the pr to get it in properly.

Thank you.

**Comment by drisspg** [comment]
ohh weird, thanks for pointing that out, lets try again..

**Pull request closed without merging**
