### PR TITLE
centos now installs cmake from conda

### PR DESCRIPTION
**Pull request by jeffdaily**
For the same reason that ubuntu builds need conda cmake to find mkl.

CC @jaglinux

### CODE REVIEW

**Comment by jeffdaily** [comment]
Curious whether the rocm caffe2 test failure was transient.  Let's retest.

**Comment by jeffdaily** [comment]
Reverted PR back to draft until we can resolve caffe2 test failures.  Cannot reproduce locally.

**Comment by jeffdaily** [comment]
@malfet note that the changes in this PR are not exercised by any CI test that we know of.  IIUC, all CI hosts run ubuntu, and these changes only affect centos + pytorch builds.  That said, we have been verifying these changes outside of CI on our local dev hosts.  We approve.

**Review by malfet — APPROVED** [review]
LGTM, although in my opinion, the install rules should completely disappear from our CI build/test script and moved to docker image generation ones.

**Comment by walterddr** [comment]
> LGTM, although in my opinion, the install rules should completely disappear from our CI build/test script and moved to docker image generation ones.

+1. it might be good to adjust .circleci/docker/common/install_base.sh to remove cmake3 installation instead of removing it here.

**Review by walterddr — APPROVED** [review]
+1 for now. I am not sure if there's a quick way to remove cmake3 only for conda CI's.

**Pull request closed without merging**
