### PR TITLE
[quant][be] Avoid circular deps from `move_model_to_eval`

### PR DESCRIPTION
**Pull request by andrewor14**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108363

Summary: This commit moves `move_model_to_eval` to its own utils
file to avoid circular dependencies. Previously `pt2e/utils.py`
cannot import anything from `torch.ao.quantization`, which
limits future PRs.

Test Plan:
python test/test_quantization.py
TestQuantizePT2E.test_move_model_to_eval

Reviewers: jerryzh168, kimishpatel

Subscribers: jerryzh168, kimishpatel, supriyar

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

Differential Revision: [D48879482](https://our.internmc.facebook.com/intern/diff/D48879482)

### CODE REVIEW

**Comment by andrewor14** [comment]
@andrewor14 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48879482).

**Review by jerryzh168 — APPROVED** [review]

**Comment by andrewor14** [comment]
@andrewor14 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48879482).

**Comment by andrewor14** [comment]
@andrewor14 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48879482).

**Comment by kimishpatel** [comment]
Andrew, I have already patched these changes locally. Do you mind if I just land those.

**Comment by andrewor14** [comment]
Yeah sure, closing this in favor of https://github.com/pytorch/pytorch/pull/107900

**Pull request closed without merging**
