### PR TITLE
Sparse CSR CUDA: Support mixed memory format input for triangular_solve

### PR DESCRIPTION
**Pull request by IvanYashchuk**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #62180
* #65606
* #64391
* #61536
* __->__ #66401

This PR fixes the case when result and input tensors have different
strides.
cuSPARSE from CUDA 11.3.1 has a bug: it doesn't use correct strides to
write the result. This is "fixed" in PyTorch code by copying the input
tensor to a tensor with same strides as result tensor has.
The bug can be reproduced using the code given in https://github.com/pytorch/pytorch/pull/66401#issuecomment-961343257.

cc @nikitaved @pearu @cpuhrsch @IvanYashchuk @ngimel

Differential Revision: [D32177966](https://our.internmc.facebook.com/intern/diff/D32177966)

### CODE REVIEW

**Comment by cpuhrsch** [comment]
@cpuhrsch has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32177966).

**Comment by ngimel** [comment]
@IvanYashchuk do you know if this bug is fixed in 11.5? Did you report it to nvidia? cc @xwang233

**Comment by xwang233** [comment]
Hi @ngimel @IvanYashchuk , I haven't received any reports yet. I can help report this to cusparse team if a C++ standalone repro is available. Thanks.

**Comment by IvanYashchuk** [comment]
Let's use a slightly modified version of the sample code available from the [CUDALibrarySamples repo](https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSE/spsm_csr).

I'll give here two patches to verify the problem on CUDA 11.3.1 (I didn't test with a newer version). First let's modify `ldb` to be 8 instead of 4 and modify the `B` array accordingly, the result should not change in this case if everything was correct.
```
import torch
r = [1.0, 8.0, 23.0, 52.0]
o = [0.0, 0.0, 0.0, 0.0]
B = torch.tensor([r, o, r, o])
# gives
# tensor([[ 1.,  8., 23., 52.],
#         [ 0.,  0.,  0.,  0.],
#         [ 1.,  8., 23., 52.],
#         [ 0.,  0.,  0.,  0.]])
print(B.stride()) # (4, 1)
print(B[::2])
# tensor([[ 1.,  8., 23., 52.],
#         [ 1.,  8., 23., 52.]])
print(B[::2].stride()) # (8, 1)
# so that's why we pick ldb = 8
```


<details>
  <summary>Patch 1:</summary>
  
  ```bash
diff --git a/cuSPARSE/spsm_csr/spsm_csr_example.c b/cuSPARSE/spsm_csr/spsm_csr_example.c
index 8dfbab4..7336689 100644
--- a/cuSPARSE/spsm_csr/spsm_csr_example.c
+++ b/cuSPARSE/spsm_csr/spsm_csr_example.c
@@ -77,14 +77,16 @@ int main(void) {
     const int A_num_cols      = 4;
     const int A_nnz           = 9;
     const int nrhs            = 2;
-    const int ldb             = A_num_cols;
+    const int ldb             = 2 * A_num_cols;
     const int ldc             = A_num_rows;
     int       hA_csrOffsets[] = { 0, 3, 4, 7, 9 };
     int       hA_columns[]    = { 0, 2, 3, 1, 0, 2, 3, 1, 3 };
     float     hA_values[]     = { 1.0f, 2.0f, 3.0f, 4.0f, 5.0f,
                                   6.0f, 7.0f, 8.0f, 9.0f };
     float     hB[]            = { 1.0f, 8.0f, 23.0f, 52.0f,
-                                  1.0f, 8.0f, 23.0f, 52.0f };
+                                  0.0f, 0.0f, 0.0f, 0.0f,
+                                  1.0f, 8.0f, 23.0f, 52.0f,
+                                  0.0f, 0.0f, 0.0f, 0.0f };
     float     hC[]            = { 0.0f, 0.0f, 0.0f, 0.0f,
                                   0.0f, 0.0f, 0.0f, 0.0f };
     float     hY_result[]     = { 1.0f, 2.0f, 3.0f, 4.0f,
@@ -98,7 +100,7 @@ int main(void) {
                            (A_num_rows + 1) * sizeof(int)) )
     CHECK_CUDA( cudaMalloc((void**) &dA_columns, A_nnz * sizeof(int))       )
     CHECK_CUDA( cudaMalloc((void**) &dA_values,  A_nnz * sizeof(float))     )
-    CHECK_CUDA( cudaMalloc((void**) &dB, nrhs * A_num_cols * sizeof(float)) )
+    CHECK_CUDA( cudaMalloc((void**) &dB, nrhs * ldb * sizeof(float)) )
     CHECK_CUDA( cudaMalloc((void**) &dC, nrhs * A_num_rows * sizeof(float)) )

     CHECK_CUDA( cudaMemcpy(dA_csrOffsets, hA_csrOffsets,
@@ -108,7 +110,7 @@ int main(void) {
                            cudaMemcpyHostToDevice) )
     CHECK_CUDA( cudaMemcpy(dA_values, hA_values, A_nnz * sizeof(float),
                            cudaMemcpyHostToDevice) )
-    CHECK_CUDA( cudaMemcpy(dB, hB, nrhs * A_num_cols * sizeof(float),
+    CHECK_CUDA( cudaMemcpy(dB, hB, nrhs * ldb * sizeof(float),
                            cudaMemcpyHostToDevice) )
     CHECK_CUDA( cudaMemcpy(dC, hC, nrhs * A_num_rows * sizeof(float),
                            cudaMemcpyHostToDevice) )
@@ -173,11 +175,13 @@ int main(void) {
                            cudaMemcpyDeviceToHost) )
     int correct = 1;
     for (int i = 0; i < nrhs * A_num_rows; i++) {
+        printf("%f ", hC[i]);
         if (hC[i] != hY_result[i]) { // direct floating point comparison is not
             correct = 0;             // reliable
             break;
         }
     }
+    printf("\n");
     if (correct)
         printf("spsm_csr_example test PASSED\n");
     else
  ```
  
</details>

Compiling Patch 1 and running the program with cuda-memcheck reveals several out of bound writes errors:
<details>
  <summary>cuda-memcheck on Patch 1</summary>
  
  ```bash
========= CUDA-MEMCHECK
========= Invalid __global__ write of size 4
=========     at 0x000011b0 in void cusparse_transpose_readWrite_alignment_kernel<float, int=1, bool=0, int=6, int=5, int=3>(cusparseTransposeParams<float>, float const *, float*, float const *)
=========     by thread (43,0,0) in block (0,0,0)
=========     Address 0x7fad0520082c is out of bounds
=========     Device Frame:void cusparse_transpose_readWrite_alignment_kernel<float, int=1, bool=0, int=6, int=5, int=3>(cusparseTransposeParams<float>, float const *, float*, float const *) (void cusparse_transpose_readWrite_alignment_kernel<float, int=1, bool=0, int=6, int=5, int=3>(cusparseTransposeParams<float>, float const *, float*, float const *) : 0x11b0)
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/lib/x86_64-linux-gnu/libcuda.so.1 [0x25428a]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x74d54b]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x7a0c70]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x5b8940]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x5b76ea]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x5fc601]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x61b29d]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 (cusparseSpSM_solve + 0x172) [0xbf262]
=========     Host Frame:./spsm_csr_example [0x148f]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf3) [0x270b3]
=========     Host Frame:./spsm_csr_example [0x1c29]
=========
========= Invalid __global__ write of size 4
=========     at 0x000011b0 in void cusparse_transpose_readWrite_alignment_kernel<float, int=1, bool=0, int=6, int=5, int=3>(cusparseTransposeParams<float>, float const *, float*, float const *)
=========     by thread (42,0,0) in block (0,0,0)
=========     Address 0x7fad05200828 is out of bounds
=========     Device Frame:void cusparse_transpose_readWrite_alignment_kernel<float, int=1, bool=0, int=6, int=5, int=3>(cusparseTransposeParams<float>, float const *, float*, float const *) (void cusparse_transpose_readWrite_alignment_kernel<float, int=1, bool=0, int=6, int=5, int=3>(cusparseTransposeParams<float>, float const *, float*, float const *) : 0x11b0)
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/lib/x86_64-linux-gnu/libcuda.so.1 [0x25428a]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x74d54b]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x7a0c70]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x5b8940]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x5b76ea]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x5fc601]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x61b29d]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 (cusparseSpSM_solve + 0x172) [0xbf262]
=========     Host Frame:./spsm_csr_example [0x148f]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf3) [0x270b3]
=========     Host Frame:./spsm_csr_example [0x1c29]
=========
========= Invalid __global__ write of size 4
=========     at 0x000011b0 in void cusparse_transpose_readWrite_alignment_kernel<float, int=1, bool=0, int=6, int=5, int=3>(cusparseTransposeParams<float>, float const *, float*, float const *)
=========     by thread (41,0,0) in block (0,0,0)
=========     Address 0x7fad05200824 is out of bounds
=========     Device Frame:void cusparse_transpose_readWrite_alignment_kernel<float, int=1, bool=0, int=6, int=5, int=3>(cusparseTransposeParams<float>, float const *, float*, float const *) (void cusparse_transpose_readWrite_alignment_kernel<float, int=1, bool=0, int=6, int=5, int=3>(cusparseTransposeParams<float>, float const *, float*, float const *) : 0x11b0)
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/lib/x86_64-linux-gnu/libcuda.so.1 [0x25428a]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x74d54b]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x7a0c70]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x5b8940]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x5b76ea]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x5fc601]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x61b29d]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 (cusparseSpSM_solve + 0x172) [0xbf262]
=========     Host Frame:./spsm_csr_example [0x148f]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf3) [0x270b3]
=========     Host Frame:./spsm_csr_example [0x1c29]
=========
========= Invalid __global__ write of size 4
=========     at 0x000011b0 in void cusparse_transpose_readWrite_alignment_kernel<float, int=1, bool=0, int=6, int=5, int=3>(cusparseTransposeParams<float>, float const *, float*, float const *)
=========     by thread (40,0,0) in block (0,0,0)
=========     Address 0x7fad05200820 is out of bounds
=========     Device Frame:void cusparse_transpose_readWrite_alignment_kernel<float, int=1, bool=0, int=6, int=5, int=3>(cusparseTransposeParams<float>, float const *, float*, float const *) (void cusparse_transpose_readWrite_alignment_kernel<float, int=1, bool=0, int=6, int=5, int=3>(cusparseTransposeParams<float>, float const *, float*, float const *) : 0x11b0)
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/lib/x86_64-linux-gnu/libcuda.so.1 [0x25428a]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x74d54b]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x7a0c70]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x5b8940]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x5b76ea]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x5fc601]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 [0x61b29d]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcusparse.so.11 (cusparseSpSM_solve + 0x172) [0xbf262]
=========     Host Frame:./spsm_csr_example [0x148f]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf3) [0x270b3]
=========     Host Frame:./spsm_csr_example [0x1c29]
=========
========= Program hit cudaErrorLaunchFailure (error 719) due to "unspecified launch failure" on CUDA API call to cudaMemcpy.
CUDA API failed at line 174 with error: unspecified launch failure (719)
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/lib/x86_64-linux-gnu/libcuda.so.1 [0x355b43]
=========     Host Frame:/home/yashchuk/cuda/cuda-11.3.1/lib64/libcudart.so.11.0 (cudaMemcpy + 0x17d) [0x5d1cd]
=========     Host Frame:./spsm_csr_example [0x1524]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf3) [0x270b3]
=========     Host Frame:./spsm_csr_example [0x1c29]
=========
========= ERROR SUMMARY: 5 errors
  ```
  
</details>

Let's extend dC array to remove out of bound errors and reveal that `ldb` value is used to write the result to `dC` while it should use `ldc` (let's set `ldc = 99999`).
<details>
  <summary>Patch 2:</summary>
  
  ```bash
diff --git a/cuSPARSE/spsm_csr/spsm_csr_example.c b/cuSPARSE/spsm_csr/spsm_csr_example.c
index 8dfbab4..026a968 100644
--- a/cuSPARSE/spsm_csr/spsm_csr_example.c
+++ b/cuSPARSE/spsm_csr/spsm_csr_example.c
@@ -77,16 +77,21 @@ int main(void) {
     const int A_num_cols      = 4;
     const int A_nnz           = 9;
     const int nrhs            = 2;
-    const int ldb             = A_num_cols;
-    const int ldc             = A_num_rows;
+    const int ldb             = 2 * A_num_cols;
+    // ldc can now be set to any value, since it is not used
+    const int ldc             = 99999;
     int       hA_csrOffsets[] = { 0, 3, 4, 7, 9 };
     int       hA_columns[]    = { 0, 2, 3, 1, 0, 2, 3, 1, 3 };
     float     hA_values[]     = { 1.0f, 2.0f, 3.0f, 4.0f, 5.0f,
                                   6.0f, 7.0f, 8.0f, 9.0f };
     float     hB[]            = { 1.0f, 8.0f, 23.0f, 52.0f,
-                                  1.0f, 8.0f, 23.0f, 52.0f };
-    float     hC[]            = { 0.0f, 0.0f, 0.0f, 0.0f,
+                                  0.0f, 0.0f, 0.0f, 0.0f,
+                                  1.0f, 8.0f, 23.0f, 52.0f,
                                   0.0f, 0.0f, 0.0f, 0.0f };
+    float     hC[]            = { 0.0f, 0.0f, 0.0f, 0.0f,
+                                  0.0f, 0.0f, 0.0f, 0.0f,
+                                  0.0f, 0.0f, 0.0f, 0.0f,
+                                  0.0f, 0.0f, 0.0f, 0.0f, };
     float     hY_result[]     = { 1.0f, 2.0f, 3.0f, 4.0f,
                                   1.0f, 2.0f, 3.0f, 4.0f };
     float     alpha           = 1.0f;
@@ -98,8 +103,8 @@ int main(void) {
                            (A_num_rows + 1) * sizeof(int)) )
     CHECK_CUDA( cudaMalloc((void**) &dA_columns, A_nnz * sizeof(int))       )
     CHECK_CUDA( cudaMalloc((void**) &dA_values,  A_nnz * sizeof(float))     )
-    CHECK_CUDA( cudaMalloc((void**) &dB, nrhs * A_num_cols * sizeof(float)) )
-    CHECK_CUDA( cudaMalloc((void**) &dC, nrhs * A_num_rows * sizeof(float)) )
+    CHECK_CUDA( cudaMalloc((void**) &dB, nrhs * ldb * sizeof(float)) )
+    CHECK_CUDA( cudaMalloc((void**) &dC, nrhs * A_num_rows*2 * sizeof(float)) )

     CHECK_CUDA( cudaMemcpy(dA_csrOffsets, hA_csrOffsets,
                            (A_num_rows + 1) * sizeof(int),
@@ -108,9 +113,9 @@ int main(void) {
                            cudaMemcpyHostToDevice) )
     CHECK_CUDA( cudaMemcpy(dA_values, hA_values, A_nnz * sizeof(float),
                            cudaMemcpyHostToDevice) )
-    CHECK_CUDA( cudaMemcpy(dB, hB, nrhs * A_num_cols * sizeof(float),
+    CHECK_CUDA( cudaMemcpy(dB, hB, nrhs * ldb * sizeof(float),
                            cudaMemcpyHostToDevice) )
-    CHECK_CUDA( cudaMemcpy(dC, hC, nrhs * A_num_rows * sizeof(float),
+    CHECK_CUDA( cudaMemcpy(dC, hC, nrhs * A_num_rows*2 * sizeof(float),
                            cudaMemcpyHostToDevice) )
     //--------------------------------------------------------------------------
     // CUSPARSE APIs
@@ -169,15 +174,17 @@ int main(void) {
     CHECK_CUSPARSE( cusparseDestroy(handle) )
     //--------------------------------------------------------------------------
     // device result check
-    CHECK_CUDA( cudaMemcpy(hC, dC, nrhs * A_num_rows * sizeof(float),
+    CHECK_CUDA( cudaMemcpy(hC, dC, nrhs * A_num_rows*2 * sizeof(float),
                            cudaMemcpyDeviceToHost) )
     int correct = 1;
-    for (int i = 0; i < nrhs * A_num_rows; i++) {
+    for (int i = 0; i < nrhs * A_num_rows*2; i++) {
+        printf("%f ", hC[i]);
         if (hC[i] != hY_result[i]) { // direct floating point comparison is not
             correct = 0;             // reliable
-            break;
+            // break;
         }
     }
+    printf("\n");
     if (correct)
         printf("spsm_csr_example test PASSED\n");
     else
  ```
  
</details>

Compiling and running Patch 2 gives:
```bash
========= CUDA-MEMCHECK
1.000000 2.000000 3.000000 4.000000 0.000000 0.000000 0.000000 0.000000 1.000000 2.000000 3.000000 4.000000 0.000000 0.000000 0.000000 0.000000
spsm_csr_example test FAILED: wrong result
========= ERROR SUMMARY: 0 errors
```

**Review by cpuhrsch — APPROVED** [review]

**Comment by yukini2009** [comment]
[Correct.zip](https://github.com/pytorch/pytorch/files/7539932/Correct.zip)
Hi , we  checked the issue internally . Note that the matrix B must be ldb * nrhs (for column-major) . Add a modified version . The  'cusparse_transpose_readWrite_alignment_kerne' error will be fixed in next major CUDA release after 11.5 . Thanks.

**Pull request closed without merging**
