### PR TITLE
Remove deprecated outplace init methods in init.py

### LINKED ISSUE #17429: Delete deprecated methods for initialization in torch.nn.init
The deprecation markers on the outplace versions of the current inplace `nn.init` functions were added in https://github.com/pytorch/pytorch/commit/4f05cb710ef067e6d60e976651942e559ecf582d, which was 2 releases ago.

I think we should remove the outplace versions.

cc: @SsnL

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:
- Remove deprecated methods in torch/nn/init.py
- Remove corresponding tests

Closes #17429.

### CODE REVIEW

**Comment by vishwakftw** [comment]
cc: @SsnL

**Comment by SsnL** [comment]
I'm not sure how to think about this change. On one hand, yes they are indeed deprecated and people shouldn't use it. On the other, it is not blocking any of our planned changes, and may break user code that still cause the un-suffixed methods...

**Comment by vishwakftw** [comment]
But I think we have issued fair warning regarding the deprecation, so I don't think this would be an issue. Please feel free to let me know if you think otherwise.

**Comment by SsnL** [comment]
I'll leave it for others to decide

**Comment by soumith** [comment]
they're not getting in the way, and they might make some old github repo keep working. We'll delete later.

**Pull request closed without merging**
