### PR TITLE
WIP: sprinkle launch bounds

### PR DESCRIPTION
**Pull request by t-vi**
Adds lots of launch bounds
This is a follow-up to #56143.

I'm a bit unhappy about the extensive reformatting git-clang-format brought over us here, but the intended substantial changes are the additions of launch bounds.

### CODE REVIEW

**Comment by t-vi** [comment]
As @ngimel points out, this wants some benchmarking to be done before we can consider it ready.

**Comment by xwang233** [comment]
What's the purpose of adding `CUDA_LAUNCH_BOUNDS` on something that's currently working well. If those bounds are helpful on "small" devices like Jetson, how do we make sure it does not affect performance on "big" devices like A100.

cc @ptrblck @mcarilli

**Comment by t-vi** [comment]
It's not working well on Nano.

**Comment by t-vi** [comment]
On second thought, maybe supporting this in mainline PyTorch is overambitious.

**Pull request closed without merging**
