### PR TITLE
[pytree] hardcode values for `none_is_leaf` and `namespace` in C++ pytree

### PR DESCRIPTION
**Pull request by XuehaiPan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #113258
* #113257
* __->__ #114858

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Comment by XuehaiPan** [comment]
> what's the plan for after this stack is done? It would be cool to move to having C++ pytree turned on by default for PyTorch. In order to get there, we'll need to figure out:
> 
> * how to make optree a required dependency. We can either add optree as a submodule of PyTorch or copy-paste it into PyTorch. submodule is likely the easiest.

@zou3519 I think the submodule approach would be fine for me.

> * how to get torch.compile to support optree. This is why we think we may need to keep around the Python pytree implementation, but maybe there is a better design that allows us to remove Python pytree.

To the best of my knowledge, the Python pytree is required by dynamo. We still have many polyfill implementations for the CPython builtin functions.

https://github.com/pytorch/pytorch/blob/7b3429d97ce8cf4573977ab8cc904f22a83c8a66/torch/_dynamo/polyfill.py#L1-L28

Here is a minimal list of required Python implementations for the pytree API:

https://github.com/metaopt/optree/blob/main/optree/_C.pyi

```python
def flatten(tree: PyTree[T]) -> tuple[list[T], PyTreeSpec]: ...
def is_namedtuple(obj: object | type) -> bool: ...
def is_namedtuple_class(cls: type) -> bool: ...
def is_structseq(obj: object | type) -> bool: ...
def is_structseq_class(cls: type) -> bool: ...

class PyTreeSpec:
    num_nodes: int
    num_leaves: int
    num_children: int
    type: builtins.type | None
    def unflatten(self, leaves: Iterable[T]) -> PyTree[T]: ...
    def flatten_up_to(self, full_tree: PyTree[T]) -> list[PyTree[T]]: ...
    def paths(self) -> list[tuple[Any, ...]]: ...
    def entries(self) -> list[Any]: ...
    def children(self) -> list[PyTreeSpec]: ...
    def is_leaf(self, strict: bool = True) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def register_node(
    cls: type,
    flatten_func: FlattenFunc,
    unflatten_func: UnflattenFunc,
) -> None: ...
```

**Pull request closed without merging**
