### PR TITLE
.github: Ensure clean workspaces before checkout

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#61565 .github: Ensure clean workspaces before checkout**

I was noticing the checkout step failing a lot for me, this adds a
cleaning step to fully remove the github workspace before attempting to
do your checkout

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

Differential Revision: [D29671074](https://our.internmc.facebook.com/intern/diff/D29671074)

### CODE REVIEW

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29671074).

**Review by zhouzhuojie — APPROVED** [review]

**Review by janeyx99 — APPROVED** [review]

**Review by walterddr — APPROVED** [review]
Wow. Would this somehow relate/fix to our previous random "test ran leaving git checkout dirty" issue?

**Comment by 1ntEgr8** [comment]
@seemethere I think it would be nice if we could abstract this into a local action under `.github/actions` and use that instead of adding an additional step to each flow. What do you think?

**Comment by samestep** [comment]
@1ntEgr8 do you mean like a [composite run steps action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action)? or something else?

**Comment by seemethere** [comment]
> @seemethere I think it would be nice if we could abstract this into a local action under `.github/actions` and use that instead of adding an additional step to each flow. What do you think?

Just note this is also a stop gap for whenever ephemeral runners are an actual thing,

Referencing https://github.com/actions/runner/pull/660 again

**Pull request closed without merging**
