### PR TITLE
Move UndefinedTensorImpl to c10 (meh)

### PR DESCRIPTION
**Pull request by smessmer**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #14795 Move TensorImpl to c10 (yay!)&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D13336856/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #14816 Fix include paths for TensorImpl.h&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D13348040/)
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#14817 Move UndefinedTensorImpl to c10 (meh)**&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D13348041/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #14818 Fix include paths for UndefinedTensorImpl.h&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D13348042/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #14819 Implement c10::Tensor&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13348039/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #14820 Convert caffe2/aten Tensors to/from c10&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13348044/)

unfortunately, we still need this.

Differential Revision: [D13348041](https://our.internmc.facebook.com/intern/diff/D13348041/)

### CODE REVIEW

**Comment by dzhulgakov** [comment]
Where do we still use UndefinedTensorImpl?

**Review by ezyang — APPROVED** [review]
@dzhulgakov It's used to create the singleton undefined tensor which is used by the Tensor default constructor.

**Comment by dzhulgakov** [comment]
I understand  that. I'm  asking why we need underfined singleton instead of simple nullptr. To call some methods  on it I presume?

**Comment by smessmer** [comment]
IIRC, this was needed because changing the legacy TH code was too hard at the time. @ezyang should we re-evaluate this?

**Comment by ezyang** [comment]
It's because people would call methods on the null pointer and it would segfault (because it was a null pointer) and, for people work in Python, this is very bad. It used to be a null pointer and we changed it; see PR #3482

**Pull request closed without merging**
