### PR TITLE
[ONNX] Quantization support for quantized::cat

### PR DESCRIPTION
**Pull request by justinchuby**
- Add support for quantized `cat`
- Add type annotations for helper functions

Now we can export

```python
import torchvision.models.quantization as models
from torchvision import transforms

torch_model = models.inception_v3(pretrained=True, quantize=True)
```

### CODE REVIEW

**Comment by justinchuby** [comment]
`onnxruntime::Node* onnxruntime::Graph::NodeAtIndexImpl(onnxruntime::NodeIndex) const node_index < nodes_.size() was false. Validating no unexpected access using an invalid node_index. Got:93974596341504 Max:11`

**Review by titaiwangms — CHANGES_REQUESTED** [review]
Please skip the tests for now, if the node is not yet supported by ORT.

**Comment by justinchuby** [comment]
> Please skip the tests for now, if the node is not yet supported by ORT.

Done

**Review by titaiwangms — APPROVED** [review]
lint

**Review by BowenBao — APPROVED** [review]
🚀

**Pull request closed without merging**
