### PR TITLE
Fix DeviceGuard usage in THD

### PR DESCRIPTION
**Pull request by goldsborough**
Fixes after the `TensorOptions` PR introduced `at::DeviceGuard`.

Still trying locally if this fixes the build (it should)

@apaszke @teng-li

### CODE REVIEW

**Comment by ngimel** [comment]
It fixes build for me, thanks! Can we make sure that CI is running distributed build with nccl2, so this breakages do not happen?

**Comment by goldsborough** [comment]
@teng-li is looking into this. We really should be catching this in CI :)

**Comment by teng-li** [comment]
@ngimel Added both MPI and NCCL in CI in: https://github.com/pytorch/pytorch/pull/8624 https://github.com/pytorch/pytorch/pull/8625

**Comment by goldsborough** [comment]
I've confirmed that it fixes the build (on FAIR cluster).

**Review by colesbury — APPROVED** [review]

**Comment by ngimel** [comment]
There's also quite a few gpuGuard.setDevice in https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/ProcessGroupNCCL.cpp#L71. It's probably not being built yet, and thus not breaking.

**Comment by teng-li** [comment]
I had to revert the CI build with MPI and NCCL, some of the NCCL/MPI are not passing.

**Comment by goldsborough** [comment]
@ngimel c10d has their own `DeviceGuard` whose method is `setDevice`. They have to update to use the new `at::DeviceGuard`

**Comment by teng-li** [comment]
@ngimel  Is this error due to a NCCL and CUDA version mismatch? 
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-cuda9-cudnn7-py3-test1/1340/console
?

Which CUDA version of NCCL will apt-get install libnccl2 install ?

**Comment by ngimel** [comment]
@teng-li that could be, you have to specify correct cuda version: https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.0/devel/Dockerfile#L12

**Comment by ngimel** [comment]
@teng-li, fwiw image built from the docker/pytorch/Dockerfile passes the tests, including nccl ones.

**Pull request merged**
