### PR TITLE
Add XLAPreAutograd key for XLA use cases that need custom autograd.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #33011 Beef up documentation on DispatchKey.h
* **#32788 Add XLAPreAutograd key for XLA use cases that need custom autograd.**
* #32787 Stop using dispatchTypeId to do checks for tensor list unwrap.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D19628643](https://our.internmc.facebook.com/intern/diff/D19628643)

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
Thanks @ezyang ! 
Minor: does it worth adding a test case for this behavior in pytorch codebase? Likely similar to https://github.com/pytorch/pytorch/blob/02aa3ba3312c273472084f782f06f79109185f33/test/test_cpp_extensions.py#L929.

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 2ae4a86f:


**None of the build failures appear to be your fault**.

* **1/1** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=3ee6673e999d90e1a27c3ada9d734e867c70a527&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base 3ee6673e since Jan 29
  <details>
  <summary>
  Please rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch origin viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=2ae4a86f71202d3a61dacae64771dac5f430901e).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [binary_linux_manywheel_2_7mu_cpu_devtoolset7_test](https://dr.pytorch.org/build-details.html?build_id=92806691) from Jan 29 until Jan 29



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by ezyang** [comment]
Yes, a minor test is probably wise

**Comment by ezyang** [comment]
@ailzhang Now there are tests!!

**Review by ailzhang — APPROVED** [review]
Thanks @ezyang !

**Review by smessmer — APPROVED** [review]

**Pull request closed without merging**
