### PR TITLE
Move torchhub tests to new test/test_hub.py file

### PR DESCRIPTION
**Pull request by NicolasHug**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #67181

Addresses https://github.com/pytorch/pytorch/issues/66232#issuecomment-948427267

cc @nairbv @NicolasHug

Differential Revision: [D32948346](https://our.internmc.facebook.com/intern/diff/D32948346)

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
I see it showing up in CI logs:
```
2021-10-26T09:10:52.3750460Z prioritized: ['test_nn', 'test_linalg', 'test_optim', 'test_utils', 'test_sparse_csr', 'test_jit_disabled', 'test_hub']
```
so I think we're good!

**Comment by NicolasHug** [comment]
@NicolasHug has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32948346).

**Comment by NicolasHug** [comment]
waiting on https://github.com/pytorch/pytorch/pull/69763 to be merged first to avoid conflicts

**Comment by NicolasHug** [comment]
Closing this one as it's been superseded by https://github.com/pytorch/pytorch/pull/74826

**Pull request closed without merging**
