### PR TITLE
[BE]: Update NCCL submodule to v2.19.3

### PR DESCRIPTION
**Pull request by Skylion007**
Updates NCCL submodule to v2.19.3 Mostly contains some more performance fixes for H100s as well as a couple new performance features and some new plugin support.

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM, but please leave a comment if you want to override distributed failure, because those can very well be related

**Comment by Skylion007** [comment]
@malfet What distributed failure?

**Comment by malfet** [comment]
> What distributed failure?

Sorry for being cryptic, one of tests from distributed shard running on GPU failed, isn't it? Which might be the usual flake, but considering you are charging NCCL can be a real thing.

**Comment by Skylion007** [comment]
@malfet All tests passed according to the checks + comments

**Pull request closed without merging**
