### PR TITLE
[fx] Make imports more selective in imported code.

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #51489 [fx/package] make GraphModules packageable
* **#51420 [fx] Make imports more selective in imported code.**
* #51826 [package] make torch.package produce unified format
* #51595 [package] Use custom persistent_load in PackageImporter
* #51694 [package] more reliable method for determining standard library-ness

Right now, when we are using a user-defined type in FX, we will emit
code like:

    import foo
    def foward(input: foo.bar.baz):
        ...

This is perfectly fine, but `torch.package` would like more selective
importing to avoid having to packaging all of `foo` even when you just
needed `foo.bar.baz`.

This PR changes the code emission so that the same function above would generate:

    from foo.bar import baz
    def forward(input: baz):
        ...

There are only two exceptions:
- `torch` is always imported as a base module. The rationale is that
most FX-packaged code will be torch-related, and it will almost
universally be an extern module.
- `typing` is always imported. This is because Python is kind of crazy
with how it formats type annotations.

Conceivably we could import all standard library modules as base modules
without too much harm, we should discuss that.

One additional tweak that is needed is that now node names need to avoid
shadowing target names. Consider code that looks like this today:
```
my_fn = foo.bar.my_fn(input)
my_fn_1 = foo.bar.my_fn(input2)
```

This would become
```
my_fn = my_fn(input)  # shadowed name!
my_fn_1 = my_fn(input)  # uh oh
```

To fix this, for callables we now register the target name as a "used name"
while building the graph.

Differential Revision: [D26166184](https://our.internmc.facebook.com/intern/diff/D26166184)

### CODE REVIEW

**Review by ansley — COMMENTED** [review]
LGTM? It would be nice to have a test, but I found it difficult to simulate the module structure myself, so we may not be able to test it. (I was almost there with `unittest.mock.Mock`, but I couldn't figure out how to change the result of `type()` to be something other than `Mock`, so that caused `create_arg` to fail. If you're more familiar with Python's mocking framework than me, I can show you what I have so far, and maybe we can include a test after all.)

**Comment by suo** [comment]
Yeah, I was thinking we already have a number of tests covering custom import logic, so the behavior is exercised under test at least. I guess the question is whether we want to consider it a guarantee that imports look this way (as opposed to the weaker guarantee that imports will work correctly). I think since the behavior is just a nice to have, the existing tests covering correctness are probably sufficient.

**Comment by jamesr66a** [comment]
FYI I want to wait until after the release branch cut to review/merge this (Friday)

**Comment by suo** [comment]
Closing in favor of  https://github.com/pytorch/pytorch/pull/51970 because weird things happened and this is marked merged

**Pull request merged**
