### PR TITLE
[android] add android fbjni lib

### PR DESCRIPTION
**Pull request by IvanKobzarev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #24055 [android][init] jni-java wrapper for pytorchScript api
* **#24054 [android] add android fbjni lib**

### CODE REVIEW

**Comment by dzhulgakov** [comment]
Is there any official repo we can depend on for it? And shall we put it under third-party?

Also cc @ezyang @soumith to verify license and stuff

**Comment by ezyang** [comment]
Recording commentary from the Friday meeting: there is not an official repository for fbjni yet (there apparently some time in the mid-term future, but not yet.) The plan on record is that we'll make a pytorch/fbjni repository and dump the code in there, and switch to the official repository when it gets open sourced "officially". License of fbjni is MIT license and therefore compatible.

**Review by ezyang — CHANGES_REQUESTED** [review]
plan on record is to make this a submodule

**Comment by IvanKobzarev** [comment]
Ok, thanks, I will create pytorch/fbjni repo and put it there

**Comment by IvanKobzarev** [comment]
Closing this Pull Request in favor of using fbjni as submodule that will be added to PR with java-jni (https://github.com/pytorch/pytorch/pull/24055)

**Pull request closed without merging**
