### PR TITLE
unsqueeze only when dim = 3

### PR DESCRIPTION
**Pull request by 103yiran**
unsqueeze is not necessary if use view

### CODE REVIEW

**Comment by albanD** [comment]
That will change the behavior for dimensions greater than 3 no? Do we have tests for this?

**Comment by 103yiran** [comment]
@albanD the else condition use `div.view`，will abolish the previous effect.

**Review by albanD — APPROVED** [review]
Sure

**Comment by albanD** [comment]
Sorry about that @103yiran Could you rebase locally and resolve merge conflicts and I'll make sure this properly gets merged.

**Pull request closed without merging**
