### PR TITLE
[Inductor XPU] Support max-autotune on XPU and reuse the corresponding Inductor UT.

### PR DESCRIPTION
**Pull request by etaf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #143266

This PR aims to add the functionality support of max-autotune for XPU. The current triton templates and configurations are not well optimized for XPU, so the performance is not ready yet. Also the `mm_plus_mm` template have accuracy issues in some cases. We will address these issues in the next PRs.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by EikanWang — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by etaf** [comment]
The faild XPU job is a know issue in : #143585
```
sccache: error: Server startup failed: cache storage failed to read: Unexpected (permanent) at read => S3Error { code: "ExpiredToken", message: "The provided token has expired.",
```

@pytorchbot merge -i

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but it is failing some tests in trunk' -c nosignal

[GH job link](https://github.com/pytorch/pytorch/actions/runs/12477577465/job/34824291085) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/ad750ae32079020f51f9b7d01237f3ecfa83b6ff)

[GH job link](https://github.com/pytorch/pytorch/actions/runs/12477577469/job/34824995897) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/ad750ae32079020f51f9b7d01237f3ecfa83b6ff)

**Pull request closed without merging**
