### PR TITLE
Feature: Dump compile_times when TORCH_LOGS=dynamo is enabled.

### PR DESCRIPTION
**Pull request by vinayburugu**
Partial implementation of  https://github.com/pytorch/pytorch/issues/103173. This PR only implements the feature to dump compile_times at the end of the session using the atexit handler.

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78

### CODE REVIEW

**Comment by vinayburugu** [comment]
cc: @ezyang

**Comment by mlazos** [comment]
IMO this should be a separate artifact, dynamo is already super noisy, wdyt @vinayburugu

**Comment by vinayburugu** [comment]
> IMO this should be a separate artifact, dynamo is already super noisy, wdyt @vinayburugu

@mlazos What do you mean by separate artifact? Here I am only dumping the compile_times of dynamo related APIs and hence used dynamo logger.

**Review by ezyang — APPROVED** [review]
I'm willing to give this a shot.

**Pull request closed without merging**
