### PR TITLE
Fix test_multiple_devices_randint_cuda

### PR DESCRIPTION
**Pull request by Aidyn-A**
The test fails with device mismatch error:
```
Traceback (most recent call last):
  File "/pytorch/torch/testing/_internal/common_utils.py", line 2137, in wrapper
    method(*args, **kwargs)
  File "/pytorch/torch/testing/_internal/common_device_type.py", line 401, in instantiated_test
    result = test(self, **param_kwargs)
  File "/pytorch/torch/testing/_internal/common_device_type.py", line 846, in test_wrapper
    return test(*args, **kwargs)
  File "/pytorch/torch/testing/_internal/common_device_type.py", line 1005, in only_fn
    return fn(slf, *args, **kwargs)
  File "/pytorch/torch/testing/_internal/common_device_type.py", line 1029, in multi_fn
    return fn(slf, devices, *args, **kwargs)
  File "/pytorch/test/test_ops.py", line 148, in test_multiple_devices
    self.assertTrue(result.device == cuda_device)
AssertionError: False is not true
```

### CODE REVIEW

**Comment by ngimel** [comment]
How is it passing now?

**Comment by Aidyn-A** [comment]
>How is it passing now?

It is not passing, it is simply being skipped. For example [here](https://github.com/pytorch/pytorch/actions/runs/4749541287/jobs/8439106481?pr=98986) the raw log indicates:
```
2023-04-20T03:27:37.2386716Z test_ops.py::TestCommonCUDA::test_multiple_devices_randint_cuda_int64 SKIPPED [0.0003s] (fewer than 2 devices detected) [  8%]
```

**Comment by ngimel** [comment]
You are showing a skip from a single gpu job (expected) however this test should be run in multi-gpu jobs, and it is passing:
```
(/scratch/ngimel/work/env) ngimel@a100-st-p4d24xlarge-7:/scratch/ngimel/work/pytorch$ python test/test_ops.py -v -k test_multiple_devices_ones_like
test_multiple_devices_ones_like_cpu_float32 (__main__.TestCommonCPU) ... skipped 'Only runs on cuda'
test_multiple_devices_ones_like_cpu_int64 (__main__.TestCommonCPU) ... skipped 'Only runs on cuda'
test_multiple_devices_ones_like_cuda_float32 (__main__.TestCommonCUDA) ... ok
test_multiple_devices_ones_like_cuda_int64 (__main__.TestCommonCUDA) ... ok
```
When `device` argument is not supplied to a `_like` function, the output should be created on the device of a model tensor. Test is correctly written to test that. If it doesn't work, it indicates a bug with implementation, not test.

**Comment by ngimel** [comment]
`randint` should be correctly setting device with device arg, but it should be done in `sample_inputs_randint`, not in `sample_inputs_like_fns`

**Comment by ngimel** [comment]
cc @huydhn it looks like we don't have a multi-gpu config that would run `test_ops`, and `test_ops` has a few tests that require multi-gpu.

**Comment by huydhn** [comment]
> cc @huydhn it looks like we don't have a multi-gpu config that would run `test_ops`, and `test_ops` has a few tests that require multi-gpu.

Here is the tracking issue to get it fixed https://github.com/pytorch/pytorch/issues/100006

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
