### PR TITLE
[inductor] Lower torch.exp2 and use it for torch.pow(2, x)

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #92632

Before
```python
    tmp0 = 2.0
    tmp2 = tl.libdevice.pow(tmp0, tmp1)
```

After
```python
    tmp1 = tl.libdevice.exp2(tmp0)
```

I've benchmarked on CPU and CUDA with the following examples
```
@torch._dynamo.optimize()
def exp2(x):
    return torch.pow(2, x)

@torch._dynamo.optimize()
def logaddexp2(a, b):
    m = torch.maximum(a, b)
    return m + torch.log2(1 + torch.pow(2, -torch.abs(a-b)))
```

triton is able to specialize `pow(2, x)` such that this makes
no difference, but on CPU I see a surprisingly large speedup.

| device | Function  | Master (us) | This PR (us) | Speedup |
|--------|-----------|-------------|--------------|---------|
| CUDA   | exp2      | 64          | 63           | 1.0     |
|        | logaddexp | 109         | 107          | 1.0     |
| CPU    | exp2      | 220         | 40           | 5.5     |
|        | logaddexp | 282         | 140          | 2.0     |

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
Nice! It's just so annoying we cannot just use the PrimTorch implementations...

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
exp2 is a prim (or should be) so using primTorch for it is kinda irrelevant.

**Comment by lezcano** [comment]
My point is that we have pretty much all this logic repeated here and in the ref for `pow` because of that broadcasting issue :/

**Comment by ngimel** [comment]
> all this logic repeated here and in the ref for pow because of that broadcasting issue :/
Not quite, having different pow lowerings in primtorch and inductor is reasonable IMO. Backends that can just write `::pow(a,b)` (most of them) are in a different position than inductor that has to do a lot of gymnastics for integer `pow`.

**Comment by peterbell10** [comment]
> Backends that can just write `::pow(a,b)` (most of them) are in a different position than inductor that has to do a lot of gymnastics for integer pow.

In general it would be nice if  backend-agnostic optimizations happened at the decomposition level and inductor-specific gymnastics can happen inside the `prim`. So all of the `pow_recursive` stuff would stay in the lowering for `prims.pow` while dispatching to a more specific prim like `prims.sqrt` for `pow(x, 0.5)` can be done by the decomposition.

This would also mitigate the issue of the reference and lowering falling out of sync. e.g. For `ceil` the lowering is short-circuited for integers:
```python
def ceil(x):
    if is_integer_type(x):
        return x
    fn = ops_wrapper("ceil")
    return make_pointwise(fn)(x)
```

but the reference isn't
```python
def ceil(a):
    return prims.ceil(a)
```

**Pull request closed without merging**
