### PR TITLE
add OpInfo instances for margin loss operators

### PR DESCRIPTION
**Pull request by dagitses**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #68990
* #68989
* #68988
* #67563
* #67562
* #67561
* #67560
* __->__ #67444

Differential Revision: [D32696623](https://our.internmc.facebook.com/intern/diff/D32696623)

### CODE REVIEW

**Comment by mruberry** [comment]
ping @dagitses

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32696623).

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32696623).

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32696623).

**Comment by nkaretnikov** [comment]
is `reduction` actually used here with `sample_inputs_margin_ranking_loss`? seems like the `kwargs` argument is never used or am i reading this incorrectly?

**Pull request closed without merging**
