### PR TITLE
Refactor offset logic and work for nD

### PR DESCRIPTION
**Pull request by zeshengzong**
Optimize TODO task in code in distributed test files.

- TODO: make this test cleaner and work for nD
- TODO: add comments for create_plan/TestDedupTensor

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @LucasLLC @MeetVadakkanchery @mhorowitz @pradeepfn

### CODE REVIEW

**Review by wz337 — APPROVED** [review]
LGTM

**Comment by zeshengzong** [comment]
@fegin Hello, need help review this PR, thanks! :D

**Pull request closed without merging**
