### PR TITLE
Add BFloat16 support for multinomial and poisson on CPU

### PR DESCRIPTION
**Pull request by blzheng**
Add BFloat16 support for multinomial and poisson on CPU

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
Please add benchmarks comparing float and bfloat kernels for various input sizes.

**Comment by blzheng** [comment]
Add benchmarks comparing float and bfloat kernels for various input sizes.

Performance data is collected on Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz.
Single core:
[multinomial_single_core.log](https://github.com/pytorch/pytorch/files/7013863/multinomial_single_core.log)
[poisson_single_core.log](https://github.com/pytorch/pytorch/files/7013864/poisson_single_core.log)

28 cores (1 socket):
[multinomial_28cores.log](https://github.com/pytorch/pytorch/files/7013865/multinomial_28cores.log)
[poisson_28cores.log](https://github.com/pytorch/pytorch/files/7013867/poisson_28cores.log)

**Comment by frank-wei** [comment]
From the perf number, multinomial and poisson perf number is worse than float32. It looks good for the user to still use float32 somehow.

**Comment by blzheng** [comment]
Re-attached performance data for easier reading and comparison.
Performance data is collected on Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz.
Single core:
image
28 cores (1 socket):
image

**Comment by frank-wei** [comment]
The perf numbers are not very satisfactory on some input sizes. It is better to dig more and try to improve it.

**Comment by jgong5** [comment]
> The perf numbers are not very satisfactory on some input sizes. It is better to dig more and try to improve it.

Thanks for the comments @frank-wei . We will look into the perf issues.

> For the completeness of op support on BF16, is it the plan to support all possible ops with BF16? @jgong5 If so, how do we handle the low perf ops?

We aim to add BF16 support for most PyTorch ops. We will make sure BF16 is faster than FP32 at the model level and try our best to make BF16 run faster than FP32 at the op level (for conv and gemm ops, we assume BF16 HW acceleration is available). Since there is only native BF16 dot-product HW support, other kinds of computation have to be conducted with FP32 plus additional type conversion overhead. So, there could be cases where the bandwidth benefit of BF16 cannot cover the conversion overhead. It could happen if the problem size is small (data are cache reside) and/or op involves more computation than trivial arithmetic. We can explain the low perf ops case by case.

**Comment by blzheng** [comment]
We optimized multinomial BF16 and the current perf numbers collected on Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz are as follows. 
image

For poisson, currently, BF16 is not expected to have a performance advantage over FP32 because it converts FP32/BF16 input to double for computation (https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Distributions.cpp#L457) and it uses rejection method  (compute bound) for sampling (https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Distributions.cpp#L62).

**Review by frank-wei — APPROVED** [review]
LGTM!

**Comment by frank-wei** [comment]
Could you check the CI failure?

**Comment by blzheng** [comment]
CI failures are fixed.

**Review by bigfootjon — APPROVED** [review]
Stamping to allow auto-merge

**Pull request closed without merging**
