### PR TITLE
fix torch.config can't respect USE_MKLDNN flag issue

### LINKED ISSUE #74949: Building from source does not respect USE_MKLDNN flag
### 🐛 Describe the bug

`I try to get PyTorch CPU only with MKL-DNN support. In case of Ubuntu Linux 20.04 and Python 3.8 I get `USE_MKL=ON, USE_MKLDNN=OFF` in `print(torch.__config__.show())`, so I tried building from source.

Environment: Anaconda, installed `numpy`, `mkl`, `mkl-dnn` and `onednn` packages.

Command used to build PyTorch: `USE_MKL=1 USE_MKLDNN=1 python setup.py install`. I also tried `USE_MKL=ON USE_MKLDNN=ON python setup.py install`, and also:
```
export USE_MKL=ON
export USE_MKLDNN=ON
python setup.py install
```

During building I got printed messages that both MKL and MKL-DNN were detected and used. However, in all 3 cases after building I got:
```
PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=OFF, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 
```

`pip list` shows `torch                       1.12.0a0+gitdfe6e88`.

PyTorch did not respect my flag for MKLDNN and set `USE_MKLDNN=OFF`. 

### Versions

Collecting environment information...
PyTorch version: 1.12.0a0+gitdfe6e88
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-37-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro P620
Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.11.0
[pip3] numpy==1.19.2
[pip3] torch==1.12.0a0+gitdfe6e88
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch
[conda] intel-extension-for-pytorch 1.11.0                   pypi_0    pypi
[conda] libmklml                  2019.0.5             h06a4308_0  
[conda] mkl                       2020.2                      256  
[conda] mkl-dnn                   0.19                 hfd86e86_1    anaconda
[conda] mkl-include               2022.0.1           h06a4308_117  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.3.0            py38h54f3939_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torch                     1.12.0a0+gitdfe6e88          pypi_0    pypi

cc @malfet @seemethere @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin @ezyang @gchanan @zou3519

### PR DESCRIPTION
**Pull request by XiaobingSuper**
Fixes https://github.com/pytorch/pytorch/issues/74949, which reports that torch.config can't respect USE_MKLDNN flag.

### CODE REVIEW

**Review by malfet — COMMENTED** [review]
Hmm, it would be nice to document or better unify  `CAFFE2_USE_MKLDNN` and `USE_MKLDNN` flags. (Because `CAFFE2_USE_MKLDNN` is still referenced in some build files)

**Comment by XiaobingSuper** [comment]
@malfet, **CAFFE2_USE_MKLDNN** and **USE_MKLDNN** are unfied as one flag now.

**Comment by XiaobingSuper** [comment]
@malfet

**Comment by XiaobingSuper** [comment]
@malfet, could you help review this PR again? Thanks!

**Review by malfet — APPROVED** [review]
LGTM, importing internally to check that it does not break builds

**Comment by XiaobingSuper** [comment]
@malfet , if this PR is ok, please help merge it, thanks!

**Comment by malfet** [comment]
@XiaobingSuper it breaks international build system, but it should be easy to fix

**Comment by XiaobingSuper** [comment]
> @XiaobingSuper it breaks international build system, but it should be easy to fix

Do you want me to see it? please help paste the log if you wish to (I can't see the internal build logs). Thanks!

**Comment by malfet** [comment]
@XiaobingSuper can you please rebase once again and I will try to land it today

**Comment by XiaobingSuper** [comment]
@malfet, code rebased.

**Comment by malfet** [comment]
@XiaobingSuper ONNX build failure looks related, isn't it?

**Comment by XiaobingSuper** [comment]
Let me check the error.

**Comment by XiaobingSuper** [comment]
@malfet , the onnx error is fixed, but seems the internal test failed, Could you help see it? thanks!

**Comment by XiaobingSuper** [comment]
@malfet

**Pull request closed without merging**
