### PR TITLE
Time torch_key computation in overall Dynamo stats

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #137909
* __->__ #137877

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by oulgen — APPROVED** [review]
Happy to stamp this but for internal, torch_key is compiled ahead of time and is just a file read, so it is essentially free. For external, not usre if we can do better than look at all the files

**Comment by masnesral** [comment]
> For external, not usre if we can do better than look at all the files

Is the cost of computing turning out to be problematic? If so, could we use the current git hash instad? That wouldn't be robust during local development...

**Review by masnesral — APPROVED** [review]

**Comment by ezyang** [comment]
> Happy to stamp this but for internal, torch_key is compiled ahead of time and is just a file read, so it is essentially free. For external, not usre if we can do better than look at all the files

I'm primarily concerned about OSS. If you want some evidence of its expense first I can measure it.

**Comment by oulgen** [comment]
For OSS, yes it can be expensive but I'm curious what the alternative would be. I guess as Sam pointed out, we would have to do some mix of git hash + hash of git diff results

**Comment by ezyang** [comment]
According to the CI results https://fburl.com/scuba/torch_open_source_signpost/uewhkwt3 it takes on average of 0.16s. Which is... not good, but also not bad, I suppose....

**Pull request closed without merging**
