### PR TITLE
Use shared CUPTI by default

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #65401

Per https://github.com/pytorch/pytorch/issues/57744 statically linked CUPTI
causes exception handling to break on certain compiler configurations, likely
because CUPTI comes with incompatible libstdc++ symbols.  Rather than pray that
something reasonable happens, use the safer configuration (dynamic linking) by
default and give a warning if the user inverts the setting.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D31082208](https://our.internmc.facebook.com/intern/diff/D31082208)

cc @ezyang @gchanan

### CODE REVIEW

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31082208).

**Comment by gdankel** [comment]
I think we need to link statically for our build wheels, no? (See comment in #65401). Other than that, linking dynamically by default for people who build their own PyTorch seems fine and sensible to me until this issue is fixed by Nvidia.
cc @malfet @ptrblck

**Comment by malfet** [comment]
@ezyang Perhaps we can rename the flag in `FORCE_STATIC_CUPTI`, which should be OFF by default, in which case it should make the decision based on the `check_cxx_source_runs` result

**Comment by ezyang** [comment]
@malfet Maybe? I'm still not convinced that linking against the dynamic library isn't just better. The cupti static library is going to come from some random C++ compiler and even if exceptions work OK, there might be something else subtly broken because you mixed up two libstdc++ versions. If we have our way, cupti becomes redistributable and so we just never static link anymore. Or do you disagree?

**Comment by ptrblck** [comment]
> If we have our way, cupti becomes redistributable and so we just never static link anymore. Or do you disagree?

Yes, I think dynamically linking would be a proper way to avoid these issues.
I double checked with our CUPTI team and based on the [2.6. Attachment A of the CUDA EULA](https://docs.nvidia.com/cuda/eula/index.html#attachment-a) `libcupti` can be redistributed so we should probably go for it in source and wheel builds.
What do you think?

**Comment by ezyang** [comment]
Sounds good to me.

**Comment by malfet** [comment]
Is libcupti properly versioned? I.e. could there be two libcupti.so.x.y that export different sets of symbols? (For example there used to be API changes within the same version of libcudnn.so.5)

**Comment by gdankel** [comment]
I'm good with dynamic version as long as it's safe to do so! Thanks @ptrblck for confirming the licensing question.

**Comment by ezyang** [comment]
OK, so... can I get an approve? :)

**Review by gdankel — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31082208).

**Pull request closed without merging**
