### PR TITLE
Make Meta into a backend component

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #78529
* #78525
* #78527
* #78526
* __->__ #78469
* #78468

Seems like it should be one.  This will make it possible to register
meta implementations even when there is a CompositeImplicitAutograd
registration already.  It also paves the way for sparse meta, etc.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
@Lucaskabela @robieta could either of you look at the MFLOPs to KFLOPs change

**Review by albanD — APPROVED** [review]
SGTM

**Review by anjali411 — APPROVED** [review]

**Review by bdhirsh — APPROVED** [review]

**Comment by robieta** [comment]
> @Lucaskabela @robieta could either of you look at the MFLOPs to KFLOPs change

Looks like the SI prefix is dynamically selected which is going to make the test inherently flaky. Probably just wildcard the prefix for now and put a TODO (you can attach my name to it) for deterministic profiler tests.

**Pull request closed without merging**
