### PR TITLE
Fix test_auto_simd in machine with AMX support

### LINKED ISSUE #129438: Test case failed in machine with AMX instruction set (test/inductor/test_cpu_repro.py::CPUReproTests.test_auto_simd )
### 🐛 Describe the bug

The test case `test/inductor/test_cpu_repro.py::CPUReproTests.test_auto_simd` failed on machine with AMX instruction set.
It blocked Intel GPU CI `xpu/ciflow` 

Error message:
```
________________________________________________________________ CPUReproTests.test_auto_simd _________________________________________________________________
Traceback (most recent call last):
  File "/home/daisyden/ci/my_pytorch/test/inductor/test_cpu_repro.py", line 1603, in test_auto_simd
    self.assertTrue(isa == vec_avx512)
  File "/home/daisyden/miniconda3/envs/ut2/lib/python3.10/unittest/case.py", line 689, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
 
To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_SLOW=1 python test/inductor/test_cpu_repro.py -k CPUReproTests.test_auto_simd
 ```

Debug info:
```
[10:34] Deng, Daisy
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

> /home/daisyden/ci/my_pytorch/test/inductor/test_cpu_repro.py(1604)test_auto_simd()

-> if vec_avx512 in codecache.valid_vec_isa_list():

(Pdb) p codecache.valid_vec_isa_list()

[VecAMX(__hash__=<function VecISA.__hash__ at 0x7f02e12f8940>), VecAVX512(__hash__=<function VecISA.__hash__ at 0x7f02e12f8940>), VecAVX2(__hash__=<function VecISA.__hash__ at 0x7f02e12f8940>)]

(Pdb) n

> /home/daisyden/ci/my_pytorch/test/inductor/test_cpu_repro.py(1605)test_auto_simd()

-> self.assertTrue(isa == vec_avx512)

(Pdb) p isa

VecAMX(__hash__=<function VecISA.__hash__ at 0x7f02e12f8940>)

(Pdb) p isa == vec_avx512

False

(Pdb) p vec_avx512

VecAVX512(__hash__=<function VecISA.__hash__ at 0x7f02e12f8940>)

(Pdb) q
```

### Versions

Current main branch.

### PR DESCRIPTION
**Pull request by CaoE**
Fixes #129438

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by CaoE** [comment]
@jgong5 Could you please help review this PR ? Thanks.

**Review by jgong5 — APPROVED** [review]

**Comment by CaoE** [comment]
@peterbell10 Could you please help review this PR ? Thanks.

**Review by peterbell10 — APPROVED** [review]

**Pull request closed without merging**
