### PR TITLE
Don't use `np.random` for TorchDynamo

### PR DESCRIPTION
**Pull request by Fidget-Spinner**
Part of https://github.com/pytorch/pytorch/issues/107970

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
Nice! Now, don't mark https://github.com/pytorch/pytorch/issues/107970 as solved, as we should still fallback to eager gracefully when the user does something that's not supported.

**Comment by Fidget-Spinner** [comment]
Sorry I tried cancelling one of the workflows because it seems the worker ran out of space. However, that may have cancelled all the workflows instead.

@pytorchbot merge

**Pull request closed without merging**
