### PR TITLE
Add test for `ShapeEnv` recording fallback.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #109944

This PR adds a test for the previous PR in this stack: #109904. In summary, it calls
functions decorated with `@record_shapeenv_event`, that don't have an explicit `ShapeEnv`
parameter, with arguments that don't hold a `ShapeEnv` instance.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by atalman** [comment]
This is failing internally
```
=================================== FAILURES ===================================
_____________ MiscTests.test_shape_env_recorded_function_fallback ______________

self = <caffe2.test.dynamo.test_misc.MiscTests testMethod=test_shape_env_recorded_function_fallback>

    def test_shape_env_recorded_function_fallback(self):
        # Make sure the record/replay mechanism for ShapeEnv will fallback
        # if no ShapeEnv instance is found.
>       constrain_range(5, min=2, max=10)

../buck-out/v2/gen/fbcode/363cd7e240f5d021/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/caffe2/test/dynamo/test_misc.py:7506: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../buck-out/v2/gen/fbcode/363cd7e240f5d021/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/torch/fx/experimental/recording.py:232: in wrapper
    self = _extract_shape_env_and_assert_equal(args, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (5,), kwargs = {'max': 10, 'min': 2}
```

**Comment by ysiraichi** [comment]
@ezyang @atalman Could you tell me what is the error raised there?

**Comment by ezyang** [comment]
atalman didn't post the full log. Here is the full log

```
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-7.2.2, pluggy-0.13.1
rootdir: /data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode
plugins: hypothesis-6.70.1
collected 337 items

. F

=================================== FAILURES ===================================
_____________ MiscTests.test_shape_env_recorded_function_fallback ______________

self = <caffe2.test.dynamo.test_misc.MiscTests testMethod=test_shape_env_recorded_function_fallback>

    def test_shape_env_recorded_function_fallback(self):
        # Make sure the record/replay mechanism for ShapeEnv will fallback
        # if no ShapeEnv instance is found.
>       constrain_range(5, min=2, max=10)

../buck-out/v2/gen/fbcode/363cd7e240f5d021/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/caffe2/test/dynamo/test_misc.py:7506: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../buck-out/v2/gen/fbcode/363cd7e240f5d021/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/torch/fx/experimental/recording.py:232: in wrapper
    self = _extract_shape_env_and_assert_equal(args, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (5,), kwargs = {'max': 10, 'min': 2}

    def _extract_shape_env_and_assert_equal(args, kwargs):
        from torch.fx.experimental.symbolic_shapes import ShapeEnv, SymTypes
    
        def assert_equal(old: Optional[ShapeEnv], new: ShapeEnv) -> ShapeEnv:
            if old is not None:
                assert old is new, "call with different ShapeEnv"
            return new
    
        shape_env = None
        for val in itertools.chain(args, kwargs.values()):
            if isinstance(val, ShapeEnv):
                shape_env = assert_equal(shape_env, val)
            if isinstance(val, SymTypes):
                shape_env = assert_equal(shape_env, val.node.shape_env)
    
>       assert shape_env is not None, "ShapeEnv not found"
E       AssertionError: ShapeEnv not found

../buck-out/v2/gen/fbcode/363cd7e240f5d021/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/torch/fx/experimental/recording.py:188: AssertionError
=========================== short test summary info ============================
FAILED ::MiscTests::test_shape_env_recorded_function_fallback - AssertionErro...
============================== 1 failed in 8.48s ===============================


self = <caffe2.test.dynamo.test_misc.MiscTests testMethod=test_shape_env_recorded_function_fallback>

    def test_shape_env_recorded_function_fallback(self):
        # Make sure the record/replay mechanism for ShapeEnv will fallback
        # if no ShapeEnv instance is found.
>       constrain_range(5, min=2, max=10)

../buck-out/v2/gen/fbcode/363cd7e240f5d021/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/caffe2/test/dynamo/test_misc.py:7506: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../buck-out/v2/gen/fbcode/363cd7e240f5d021/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/torch/fx/experimental/recording.py:232: in wrapper
    self = _extract_shape_env_and_assert_equal(args, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = (5,), kwargs = {'max': 10, 'min': 2}

    def _extract_shape_env_and_assert_equal(args, kwargs):
        from torch.fx.experimental.symbolic_shapes import ShapeEnv, SymTypes
    
        def assert_equal(old: Optional[ShapeEnv], new: ShapeEnv) -> ShapeEnv:
            if old is not None:
                assert old is new, "call with different ShapeEnv"
            return new
    
        shape_env = None
        for val in itertools.chain(args, kwargs.values()):
            if isinstance(val, ShapeEnv):
                shape_env = assert_equal(shape_env, val)
            if isinstance(val, SymTypes):
                shape_env = assert_equal(shape_env, val.node.shape_env)
    
>       assert shape_env is not None, "ShapeEnv not found"
E       AssertionError: ShapeEnv not found

../buck-out/v2/gen/fbcode/363cd7e240f5d021/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/torch/fx/experimental/recording.py:188: AssertionError

```

**Comment by ysiraichi** [comment]
@ezyang thank you for the log. It seems that it was executed without the previous PR in this stack (#109904). Let me rebase it.

**Pull request closed without merging**
