### PR TITLE
Migrate THCCachingHostAllocator to ATen

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #65948
* #65944
* #65943
* #65942
* __->__ #65746

This also removes the cudaHostAllocator field on THCState, since there
doesn't seem to be an API anywhere for customizing it.

Differential Revision: [D31236630](https://our.internmc.facebook.com/intern/diff/D31236630)

### CODE REVIEW

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31236630).

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31236630).

**Comment by ngimel** [comment]
THere's a real internal error in the destructor:
```
Test appears to have passed but the binary exited with a non-zero exit code.
This usually means something has crashed after the test was done.
stdout:
Note: Google Test filter = BatchingTest.EmbeddingCombineTest
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from BatchingTest
[ RUN      ] BatchingTest.EmbeddingCombineTest
[       OK ] BatchingTest.EmbeddingCombineTest (2134 ms)
[----------] 1 test from BatchingTest (2134 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (2135 ms total)
[  PASSED  ] 1 test.

stderr:
*** Aborted at 1633020601 (Unix time, try 'date -d @1633020601') ***
*** Signal 11 (SIGSEGV) (0x18) received by PID 2398510 (pthread TID 0x7f844cca2dc0) (linux TID 2398510) (code: address not mapped to object), stack trace: ***
    @ 0000000000006e37 folly::symbolizer::(anonymous namespace)::signalHandler(int, siginfo_t*, void*)
                       ./folly/experimental/symbolizer/SignalHandler.cpp:449
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 000000000003e1b2 cudaFreeHost
    @ 00000000018d6153 at::cuda::(anonymous namespace)::HostAllocator::emptyCache()
                       ./caffe2/aten/src/ATen/cuda/CachingHostAllocator.cpp:227
    @ 00000000018d62fe at::cuda::(anonymous namespace)::HostAllocator::~HostAllocator()
                       ./caffe2/aten/src/ATen/cuda/CachingHostAllocator.cpp:66
    @ 000000000004203b __cxa_finalize
    @ 0000000000000000 (unknown)
    @ 0000000000011132 _dl_fini
    @ 0000000000041924 __run_exit_handlers
    @ 0000000000041ac9 __GI_exit
    @ 0000000000025d9b __libc_start_main
    @ 0000000000246029 _start
                       /home/engshare/third-party2/glibc/2.30/src/glibc-2.30/csu/../sysdeps/x86_64/start.S:120

exit_code:"Process terminated by the signal: 11"

Summary
  Fatal: 1
    ☢ hpc/predictor/gpu_tests:batching_test - BatchingTest.EmbeddingCombineTest
  ListingSuccess: 1
```
In many cases depending on the order of destructors, destructors for various cuda resources segfault and are disabled (you can look around the codebase for examples), maybe it should be done here also.

**Comment by peterbell10** [comment]
@ngimel I've just removed the destructor. It wasn't in the original code and I added it because I didn't realise the leaking was intentional.

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31236630).

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
