### PR TITLE
[cuBLAS][cuBLASLt] Remove CUDA 11 heuristics for dispatching to cuBLASLt

### PR DESCRIPTION
**Pull request by eqy**
Revisiting an old workaround to see if things have improved since then...

cc @csarofeen @ptrblck @xwang233

### CODE REVIEW

**Review by atalman — APPROVED** [review]

**Comment by malfet** [comment]
@eqy what was the test plan for this change (considering that some of old constraint were put for perf reasons)

**Comment by eqy** [comment]
> @eqy what was the test plan for this change (considering that some of old constraint were put for perf reasons)

This will go through internal QA on our end which should hopefully cover a wide range of models and catch potential regressions. However, I believe these particular lines were functional correctness only? https://github.com/pytorch/pytorch/commit/e116f1a3ff64a6a9f6e1447c0aa53acf0f4282f3 which I checked before submitting this PR in CUDA 12

**Pull request closed without merging**
