### PR TITLE
explicitly exporting symbols from __all__

### LINKED ISSUE #49480: Internal symbols are leaking from torch.nn.functional
## 🐛 Bug

Currently symbols which are imported by `torch/nn/functional.py` are accessible through the namespace. 

## To Reproduce

```
>>> import torch
>>> print(torch.nn.functional.has_torch_function)
<built-in function _has_torch_function>
```

## Expected behavior

```
# has_torch_function lives in overrides, and is not part of the public API
AttributeError: module 'torch.nn.functional' has no attribute has_torch_function
```

## Environment

N/A

### PR DESCRIPTION
**Pull request by venkateshtata**
Fixes #49480

Moved contents from functional.py to a new file named _functional.py and explicitly defined all the variables and objects in  __all__ to avoid leaking while doing `from . _functional import *`.

### CODE REVIEW

**Comment by albanD** [comment]
Thanks for the PR!
I think you're missing a couple of newlines at the end of files.
Also as you can see in the test, this would be BC-breaking as a lot of function that people use on `nn.functional` won't be here anymore.

cc @ezyang what do you think about this?

**Comment by ezyang** [comment]
importing to phab to get a better diff view

**Comment by venkateshtata** [comment]
> Thanks for the PR!
> I think you're missing a couple of newlines at the end of files.
> Also as you can see in the test, this would be BC-breaking as a lot of function that people use on `nn.functional` won't be here anymore.
> 
> cc @ezyang what do you think about this?

**Comment by venkateshtata** [comment]
> Thanks for the PR!
> I think you're missing a couple of newlines at the end of files.
> Also as you can see in the test, this would be BC-breaking as a lot of function that people use on `nn.functional` won't be here anymore.
> 
> cc @ezyang what do you think about this?

I've updated the code again, Could you please check it out .

**Comment by robieta** [comment]
Please use `git mv functional.py _functional.py` rather than simply `mv functional.py _functional.py`, as this will retain history and make review much easier by only showing the parts that actually changed.

**Comment by venkateshtata** [comment]
> Please use `git mv functional.py _functional.py` rather than simply `mv functional.py _functional.py`, as this will retain history and make review much easier by only showing the parts that actually changed.

used git mv functional.py _functional.py this time as requested

**Comment by robieta** [comment]
It seems like git isn't smart enough to understand a file that is both moved and modified. That's unfortunate.

**Comment by venkateshtata** [comment]
> It seems like git isn't smart enough to understand a file that is both moved and modified. That's unfortunate.

```
error: Name \'interpolate\' already defined on line 3620  
[no-redef]\ntorch/nn/_functional.py:3871:2: error: Name \'upsample_nearest\' already defined on line 3866  [no-redef]\ntorch/nn/_functional.py:3876:1: error: Name \'upsample_nearest\' already defined on line 3866  [no-redef]\ntorch/nn/_functional.py:3910:2: error: Name \'upsample_bilinear\' already defined on line 3903  [no-redef]\ntorch/nn/_functional.py:3917:2: error: Name \'upsample_bilinear\' already defined on line 3903  [no-redef]\ntorch/nn/_functional.py:3924:2: error: Name \'upsample_bilinear\' already defined on line 3903  [no-redef]\ntorch/nn/_functional.py:3931:1: error: Name \'upsample_bilinear\' already defined on line 3903  [no-redef]\ntorch/nn/_functional.py:4285:24: error: Module has no attribute "reflection_pad1d"  [attr-defined]\ntorch/nn/_functional.py:4287:24: error: Module has no attribute "replication_pad1d"  [attr-defined]\ntorch/nn/_functional.py:4296:24: error: Module has no attribute "reflection_pad2d"  [attr-defined]\ntorch/nn/_functional.py:4298:24: error: Module has no attribute "replication_pad2d"  [attr-defined]\ntorch/nn/_functional.py:4309:24: error: Module has no attribute "replication_pad3d"  [attr-defined]\ntorch/nn/_functional.py:4477:88: error: Argument 8 to "triplet_margin_loss" has incompatible type "int"; expected "Optional[bool]"  [arg-type]\ntorch/nn/_functional.py:4598:16: error: Module has no attribute "im2col"  [attr-defined]\ntorch/nn/_functional.py:4631:16: error: Module has no attribute "col2im" 
```

Getting redef error for functions within `torch._C._nn` as there are functions with same name within the file.  Can you tell me how can I tackle this error ?

**Review by venkateshtata — COMMENTED** [review]
updated `__all__`

**Comment by venkateshtata** [comment]
Can anyone please  tell what does `error: Variable "torch._jit_internal.BroadcastingList1" is not valid as a type` mean here ?

**Comment by ezyang** [comment]
sounds like the type annotation on this function is too restrictive. I'd suggest opening a separate PR to fix that up.

**Comment by venkateshtata** [comment]
> sounds like the type annotation on this function is too restrictive. I'd suggest opening a separate PR to fix that up.

Okay

**Pull request closed without merging**
