### PR TITLE
Revert "Disable flaky test TestCppExtensionAOT.test_cuda_extension in…

### LINKED ISSUE #33270: TestCppExtensionAOT.test_cuda_extension is flaky on Windows
It seems that `test_cuda_extension (__main__.TestCppExtensionAOT)` test is flaky on Windows now, starting from https://github.com/pytorch/pytorch/pull/33084.
```
======================================================================
FAIL: test_cuda_extension (__main__.TestCppExtensionAOT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cpp_extensions_aot.py", line 67, in test_cuda_extension
    self.assertEqual(z, torch.ones_like(z))
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 862, in assertEqual
    assertTensorsEqual(x, y)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 832, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(1.) not less than or equal to 1e-05 : 

----------------------------------------------------------------------
```
Instances of the failure:
https://app.circleci.com/jobs/github/pytorch/pytorch/4469204
https://app.circleci.com/jobs/github/pytorch/pytorch/4470030
https://app.circleci.com/jobs/github/pytorch/pytorch/4470035
https://app.circleci.com/jobs/github/pytorch/pytorch/4479604

cc @peterjc123 @ezyang @gchanan @zou3519

### PR DESCRIPTION
**Pull request by peterjc123**
… Windows CI (#33282)"

This reverts commit 5b922918d023126ad1f468c68577c9b599ad202d.

Fixes #33270.

### CODE REVIEW

**Review by yf225 — APPROVED** [review]
Hooray! :D

**Comment by peterjc123** [comment]
@yf225 Could you please land it as well?

**Comment by yf225** [comment]
@peterjc123 Yes will land it after CI finishes :D

**Comment by peterjc123** [comment]
@ezyang Any problem landing this PR?

**Comment by soumith** [comment]
no, i've re-kicked a land, it will land in ~30 mins

**Pull request closed without merging**
