### PR TITLE
[BE][typing] fix types in common pruning

### PR DESCRIPTION
**Pull request by henrylhtsang**
BE task. Add typings and remove mypy errors in torch/testing/_internal/common_pruning.py

### CODE REVIEW

**Comment by henrylhtsang** [comment]
linter error is pre-existing

**Comment by ZainRizvi** [comment]
@pytorchbot revert -c ghfirst -m "The new test is failing internally. See D60567756 for details"

```
    def test_store_global_crossfile_inline(self):
>       import mock_store_global_crossfile_inline
E       ModuleNotFoundError: No module named 'mock_store_global_crossfile_inline'
```

**Comment by henrylhtsang** [comment]
@ZainRizvi wrong pr?

**Review by ColinPeppler — APPROVED** [review]

**Comment by xingyunjohn1** [comment]
@henrylhtsang  I am sorry I am new here. I wonder whether this is the reason that my PR has been removed? I am the author of PR #130209 . I see you have mentioned my pull request [3 weeks ago](https://github.com/pytorch/pytorch/pull/130209#ref-pullrequest-2440714247). I would appriciate it if you could give me some information about this. Thank you.

**Comment by henrylhtsang** [comment]
> @henrylhtsang I am sorry I am new here. I wonder whether this is the reason that my PR has been removed? I am the author of PR #130209 . I see you have mentioned my pull request [3 weeks ago](https://github.com/pytorch/pytorch/pull/130209#ref-pullrequest-2440714247). I would appriciate it if you could give me some information about this. Thank you.

Hi @xingyunjohn1, no worries. I think I mentioned your PR by accident. My guess is your PR got overriden by https://github.com/pytorch/pytorch/pull/132689/

**Pull request closed without merging**
