### PR TITLE
NestedTensor Softmax

### PR DESCRIPTION
**Pull request by mikekgfb**
Summary: Simple mask compute and softmax

Test Plan: unit test

Differential Revision: D38711915

### CODE REVIEW

**Review by erichan1 — APPROVED** [review]
Looks good.

**Comment by huydhn** [comment]
@mikekgfb I'm seeing a failure in one of the functorch tests associated with this change https://hud.pytorch.org/pytorch/pytorch/commit/d7fc76a1ed33a155c8be795abe67315a4459e1a0.  So here is the test error log FYI:

```
======================================================================
ERROR [0.002s]: test_single_output (__main__.TestAOTAutograd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/functorch/test/test_pythonkey.py", line 223, in test_single_output
    self.verify_aot_autograd(f, inp)
  File "/var/lib/jenkins/workspace/functorch/test/test_pythonkey.py", line 216, in verify_aot_autograd
    self.assertEqual(ref_out, test_out)
  File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2391, in assertEqual
    y = torch.as_tensor(y, dtype=x.dtype, device=x.device)
ValueError: only one element tensors can be converted to Python scalars

----------------------------------------------------------------------
Ran 22 tests in 0.568s

FAILED (errors=1, skipped=1, expected failures=3)
```

**Comment by huydhn** [comment]
There are some new developments w.r.t this failure. It looks like a fix for this is being pushed https://github.com/pytorch/pytorch/pull/83608.  If it works out, I will reland this PR

**Review by huydhn — APPROVED** [review]

**Pull request closed without merging**
