### PR TITLE
Apply release only changes to core

### PR DESCRIPTION
**Pull request by atalman**
Utility script to run after branch cut have been completed.
Execute: ``RELEASE_VERSION=2.1 apply-release-changes.sh``
Similar to: https://github.com/pytorch/audio/pull/3590

Test PR: https://github.com/pytorch/pytorch/pull/109210

Automate generation of PRs: 
https://github.com/pytorch/pytorch/pull/108053
https://github.com/pytorch/pytorch/pull/108688
https://github.com/pytorch/pytorch/pull/108064

### CODE REVIEW

**Review by seemethere — COMMENTED** [review]
Can we also add some notes in the places where this is doing modifications to let others know that modifying those should also come with a modification here as well?

i.e. if I modify `CONDA_PYTORCHBOT_TOKEN` in `.github/templates/upload.yml.j2` then I should also modify this script as well

**Comment by malfet** [comment]
Why can't this be a Python script? Because I suspect it will work on your machine with specific version of bash and sed, but might not work on others. Python has a much more stable API in that sense.

**Comment by atalman** [comment]
> Why can't this be a Python script? Because I suspect it will work on your machine with specific version of bash and sed, but might not work on others. Python has a much more stable API in that sense.

Most of the other scripts in this in the scripts/release folder are bash scripts cut-release-branch.sh, promote etc... hence feels logical to continue using bash script here.

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
