### PR TITLE
[doc] document pin_memory for randn

### LINKED ISSUE #85123: randn has undocumented pin_memory parameter
See 

https://github.com/pytorch/pytorch/blob/7dcc723d35a8795c7f386cf0a439299a89432a75/aten/src/ATen/native/native_functions.yaml#L4052

vs. 

https://pytorch.org/docs/master/generated/torch.randn.html

cc @svekars @holly1238

### PR DESCRIPTION
**Pull request by foram-chandra**
Fixes #85123

cc: @mruberry @kshitij12345

### CODE REVIEW

**Review by mruberry — APPROVED** [review]
Cool, thanks!

**Comment by kshitij12345** [comment]
@mruberry I think it should be ok to force merge this, since it is a doc only change.

And the new docs look good (as generated on the CI) : https://docs-preview.pytorch.org/85219/generated/torch.randn.html?highlight=torch+randn#torch.randn

What do you think?

**Pull request closed without merging**
