### PR TITLE
Update mobile model test (quant ops + iOS test)

### PR DESCRIPTION
**Pull request by linbinyu**
- update model generation script to cover more ops (including quant ops)
- add more test cases for iOS simulator test 
- update GA config to run the new model test on iOS

```
Generated 703 ops and covered 356/393 (90.59%) production ops.
```

Simulator test passed:
+--------------------+----+
|      Test Results       |
+--------------------+----+
| Number of tests    | 31 |
| Number of failures | 0  |
+--------------------+----+

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
Need to resolve conflicts before merging.

**Comment by kit1980** [comment]
I think after https://github.com/pytorch/pytorch/pull/74306 the file .github/templates/ios_ci_workflow.yml.j2 is irrelevant, but I can't find where exactly the functionality now. And if the template file is still relevant, the actual workflow needs to be re-generated from the template.

**Review by kit1980 — APPROVED** [review]
Looks good to me after updated workflow issue is resolved.

**Comment by linbinyu** [comment]
created a new pr https://github.com/pytorch/pytorch/pull/74575/

**Pull request closed without merging**
