### PR TITLE
[cuDNN][SDPA] Support different key, value dimension in cuDNN SDPA

### PR DESCRIPTION
**Pull request by eqy**
CC @vedaanta-nvidia @drisspg 

cc @csarofeen @ptrblck @xwang233

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by eqy** [comment]
Closing as the cuDNN SDPA enablement-default PR now includes this

**Comment by drisspg** [comment]
@eqy we dont need to cherry pick into 2.4 since the PR that enables cudnn by default on h100+ machines is not included in that release, correct?

**Comment by eqy** [comment]
Right, it was reverted and also this was rolled into the 2nd attempt to land that PR

**Pull request closed without merging**
