### PR TITLE
Enable CUPTI for kineto by default on windows.

### PR DESCRIPTION
**Pull request by cloudhan**
It fix nothing.

For tracking this PR, please refers to https://github.com/pytorch/kineto/issues/356

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
This PR  broke window tests, likely because CUPTI dll was not bundled into torch/lib folder nor could be found in the standard search path.
Please amend your PR to include install step for Windows and then it'll be good to go

**Comment by ilia-cher** [comment]
the original reason why this was disabled - there was no static cupti library available on windows, so this can't be enabled at the moment, one possible solution is to refactor kineto to use dynamic loading of cupti dll in runtime

**Review by ilia-cher — CHANGES_REQUESTED** [review]
the original reason why this was disabled - there was no static cupti library available on windows, so this can't be enabled at the moment, one possible solution is to refactor kineto to use dynamic loading of cupti dll in runtime

**Comment by cloudhan** [comment]
@malfet I know it. It is due to cupti dll is not in the path. There will be a quick fix for it, I just don't have time to figure out how to configure test runner.

**Comment by cloudhan** [comment]
Will fix it. I'll ping you then.

**Comment by cloudhan** [comment]
@malfet It seems to be good this time.

Though, I'd suggest someone merge [this PR](https://github.com/pytorch/builder/pull/815) first.
Otherwise, the nightly whl will be unusable on windows.

**Comment by cloudhan** [comment]
@malfet As the prerequisite PR in builder has been merged. I think this one is ready.

@ilia-cher For dynamic loading cupti dll in kineto, you will need to robustly determine with path to load from in development mode installation. For now, I think simply patching the `PATH` environment on importing will be enough.

**Comment by ilia-cher** [comment]
will delegate to @malfet to check whether this works with the release process

**Comment by cloudhan** [comment]
Related actions https://github.com/cloudhan/jax-windows-builder/actions/runs/1135880864

**Comment by cloudhan** [comment]
Disable the tests on window, they are flaky. Unknown reason. Trace file(s) will be lost from the temp dir...

**Comment by cloudhan** [comment]
One of the flaky test is caused by the timing issue from `time.time()` , two or more chrome trace files might have the same filename on windows...

**Comment by gdankel** [comment]
What's the status of this PR? Is it ready to go? We might also need @malfet to give it a stamp?

**Comment by cloudhan** [comment]
@gdankel I think it is ready.

**Comment by cloudhan** [comment]
Upstream pytorch repo has updated kineto submodule. I rebased this PR without submodule change and squashed the test related changes.

**Review by gdankel — APPROVED** [review]
Stamping to unblock but would be good if @malfet can take a quick look as well.

**Comment by malfet** [comment]
Reverting, as this PR started to trigger failures in `test_tensorboard` for win-cuda-on-cpu config, see here https://hud.pytorch.org/commit/7dbc21bc2b55e0c299ebe12e5e85ef5d730f879f

**Comment by cloudhan** [comment]
@malfet based on the artifact [[gha] win-vs2019-cuda10.2-py3](https://github.com/pytorch/pytorch/suites/3858204065/artifacts/95889948) in that page, it does not has cuda related libraries bundled with nor does it have cuda related library install on host OS. It will indeed be a problem for that test...

It seem to be absent from PR test, though.

I have no idea how to fix/workaround it in the case of partial installation. You either bundle the missing libraries with the artifact or with the OS...

**Comment by cloudhan** [comment]
Well, well, well. CUDA libraries are actually installed on the host OS. It is `torch/__init__.py` and `caffe2/python/__init__.py` have similar `dll_paths` construction logic. And I only updated `torch/__init__.py` :(

**Pull request closed without merging**
