### PR TITLE
Enable UFMT on test_shape_ops.py test_show_pickle.py test_sort_and_select.py

### PR DESCRIPTION
**Pull request by zeshengzong**
Fixes some files in #123062

Run lintrunner on files:
test_shape_ops.py 
test_show_pickle.py 
test_sort_and_select.py

```bash
$ lintrunner --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```

### CODE REVIEW

**Review by ezyang — DISMISSED** [review]
is clean

**Comment by ezyang** [comment]
```
diff --git b/test/test_sort_and_select.py a/test/test_sort_and_select.py
index 9d6a32cfe3f..73414bb28be 100644
--- b/test/test_sort_and_select.py
+++ a/test/test_sort_and_select.py
@@ -53,9 +53,9 @@ class TestSortAndSelect(TestCase):
                 return ((b != b) | (a <= b)).all().item()
 
         else:
-            error(
+            error(  # noqa: F821
                 f'unknown order "{order}", must be "ascending" or "descending"'
-            )  # noqa: F821
+            )
 
         are_ordered = True
         for k in range(1, SIZE):
```

**Comment by atalman** [comment]
This is the failure: https://github.com/pytorch/pytorch/actions/runs/9309514526/job/25625086573

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
