### PR TITLE
Apply ufmt linter to all py files under tools

### PR DESCRIPTION
**Pull request by huydhn**
With ufmt in place https://github.com/pytorch/pytorch/pull/81157, we can now use it to gradually format all files. I'm breaking this down into multiple smaller batches to avoid too many merge conflicts later on.

This batch (as copied from the current BLACK linter config):
* `tools/**/*.py`

Upcoming batchs:
* `torchgen/**/*.py`
* `torch/package/**/*.py`
* `torch/onnx/**/*.py`
* `torch/_refs/**/*.py`
* `torch/_prims/**/*.py`
* `torch/_meta_registrations.py`
* `torch/_decomp/**/*.py`
* `test/onnx/**/*.py`

Once they are all formatted, BLACK linter will be removed.

### CODE REVIEW

**Review by suo — APPROVED** [review]

**Comment by huydhn** [comment]
> ❌ 🤖 pytorchbot command failed:
> 
> ```
> Got EOF while in a quoted string```
> Try `@pytorchbot --help` for more info.
> ```

Bad bad bot :)

**Pull request closed without merging**
