### PR TITLE
ByteTensor sum test

### PR DESCRIPTION
**Pull request by cpuhrsch**
In response to [issue 6018](https://github.com/pytorch/pytorch/issues/6018).

### CODE REVIEW

**Comment by colesbury** [comment]
This fix doesn't seem right. ByteTensor is `uint8_t` which should have well defined behavior for overflow.

**Comment by colesbury** [comment]
I guess the `-1` to unsigned conversion is undefined behavior, even though the addition overflow is well defined for this type.

I wonder what the ppc64le behavior is.

**Comment by avmgithub** [comment]
@colesbury @cpuhrsch what did you want to know about ppc4le behavior ?

**Comment by colesbury** [comment]
whats the value of `uint8_t(-1)`? What does this program print?

```c++
#include <iostream>
#include <stdint.h>

int main(int argc, char* argv[]) {
  std::cout << "uint8: " << int(uint8_t(-1)) << "\n";
  return 0;
}
```

**Comment by avmgithub** [comment]
it prints 255

**Comment by colesbury** [comment]
Hmmm... that doesn't explain much. Can you `print(x)` right before this line?

https://github.com/pytorch/pytorch/blob/a3d08de3311d6d0af581088f3555fe1f5db6d8df/test/test_torch.py#L444

**Comment by avmgithub** [comment]
here you go

$ python -m unittest -q -v test_torch.TestTorch.test_dim_reduction
test_dim_reduction (test_torch.TestTorch) ...
-1  2  1
 5  3  6
[torch.DoubleTensor of size (2,3)]

Error: processor architecture is not supported in cpuinfo

-1  2  1
 5  3  6
[torch.FloatTensor of size (2,3)]


-1  2  1
 5  3  6
[torch.LongTensor of size (2,3)]


-1  2  1
 5  3  6
[torch.IntTensor of size (2,3)]


-1  2  1
 5  3  6
[torch.ShortTensor of size (2,3)]


 0  2  1
 5  3  6
[torch.ByteTensor of size (2,3)]

FAIL

**Comment by colesbury** [comment]
Oh... so `float` -> `uint8_t` conversion is only well defined for non-negative floats. So we can either cast to something like `int64_t` first or change the test to avoid creating FloatTensors.

i.e THTensorCopy does:

```
*tensor_data = (uint8_t)(*src_data)
```

We should get consistent behavior if we do:

```
*tensor_data = (uint8_t)(int64_t)(*src_data)
```

**Comment by avmgithub** [comment]
yeah, I think Adam had the same conclusion in this https://github.com/pytorch/pytorch/issues/3277.
casting integral types to unsigned integral types is always well defined (in modulo arithmetic), but in case of floating point types you can cast it to any integral type, but result is only well defined if it can be represented as a truncated value (even when the destination type is unsigned!!!). An excerpt from C++ standard:

    Floating–integral conversions

    ...
    If the value cannot fit into the destination type, the behavior is undefined (even when the destination type is unsigned, modulo arithmetic does not apply).
    ...

**Comment by avmgithub** [comment]
@cpuhrsch @colesbury I tried your suggested changes,  it works for ppc64le , but on gpu it fails for ppc64le like on x86.      Changing x = torch.ByteTensor([[0, 2, 1], [5, 3, 6]])   to  x = cast(torch.ByteTensor([[0, 2, 1], [5, 3, 6]]))    fixes the problem.

**Pull request merged**
