### PR TITLE
[dynamo] config guard cache size limit

### PR DESCRIPTION
**Pull request by jon-chuang**
Follow up to: https://github.com/pytorch/pytorch/pull/111074

CacheEntry are stored on f's `__code__` object. We simply change the way of counting the cache size limit

cc @voznesenskym @ezyang @Chillee

### CODE REVIEW

**Comment by ezyang** [comment]
since this isn't stacked I can't easily review it, removing from queue for now

**Comment by jon-chuang** [comment]
@ezyang would it be possible to get branch creation permission on this repo?

Running ghstack:
remote: Permission to pytorch/pytorch.git denied to jon-chuang.

**Comment by ezyang** [comment]
i sent you a gh invite

**Pull request closed without merging**
