### PR TITLE
[Checkpoint] Test file for checkpoint_wrapper

### PR DESCRIPTION
**Pull request by rohan-varma**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #78752
* #78704
* __->__ #78702

As we make additional changes and don't couple checkpoint_wrapper with
FSDP, would be good to have standalone test file for it.

Currently, we port the only non FSDP specific unittest that exists, and will add more as development continues.

### CODE REVIEW

**Review by awgu — COMMENTED** [review]
Is the plan to keep `test_checkpoint_wrapper.py` in `test/distributed/fsdp/` in the short-term and relocate it in the long term?

**Comment by rohan-varma** [comment]
@awgu Yes, `test_checkpoint_wrapper.py` in fsdp tests tests integration / interaction with FSDP as that is a very common use case.

Although agreed it is not ideal to have 2 test files of the same name due to confusion, that one can probably be named `test_checkpoint_wrapper_with_fsdp` which I'll do in a follow up.

**Review by awgu — APPROVED** [review]

**Pull request closed without merging**
