### PR TITLE
fix MakeSizeMul call error in LTC IrBuilder.

### LINKED ISSUE #99299: There has implmenet bug in LTC IrBuilder's MakeSizeMul method.
### 🐛 Describe the bug

The default implementation of LTC IrBuilder's MakeSizeMul has error called method. The detail code is listed as below: 
```c++
static inline NodePtr MakeSizeMul(const Value& a, const Value& b) {
  return getIrBuilder()->MakeSizeMul(a, b);
}
```
It is located in ·pytorch/torch/csrc/lazy/core/ir_builder.h`, and the currently main branch also has this bug.

### Versions

The nightly main branch.

### PR DESCRIPTION
**Pull request by i4oolish**
Fixes #99299

### CODE REVIEW

**Comment by i4oolish** [comment]
drci

**Comment by i4oolish** [comment]
drci

**Comment by i4oolish** [comment]
rebase

**Comment by i4oolish** [comment]
drci

**Review by wconstab — APPROVED** [review]
lgtm, thanks!
cc @JackCaoG @miladmo @alanwaketan

**Review by JackCaoG — APPROVED** [review]

**Review by alanwaketan — APPROVED** [review]
LGTM.

**Comment by alanwaketan** [comment]
@i4oolish Are you still interested in landing it?

**Pull request closed without merging**
