### PR TITLE
[ROCm] Enable some sparse tests on ROCm

### PR DESCRIPTION
**Pull request by jpvillam-amd**
Enabling:
test_sampled_addmm_errors_cuda_complex128
test_sampled_addmm_errors_cuda_complex64
test_sampled_addmm_errors_cuda_float32
test_sampled_addmm_errors_cuda_float64
test_sparse_add_cuda_complex128
test_sparse_add_cuda_complex64

### CODE REVIEW

**Comment by pruthvistony** [comment]
@jpvillam-amd ,
Please check few tests are still getting skipped in the CI run
test_sampled_addmm_errors_cuda_complex64 (__main__.TestSparseCSRCUDA) ... skip: cuSparse Generic API SDDMM is not available (0.003s)
  test_sampled_addmm_errors_cuda_float32 (__main__.TestSparseCSRCUDA) ... skip: cuSparse Generic API SDDMM is not available (0.003s)
  test_sampled_addmm_errors_cuda_float64 (__main__.TestSparseCSRCUDA) ... skip: cuSparse Generic API SDDMM is not available (0.003s)
  test_sampled_addmm_zero_sized_cuda_complex128 (__main__.TestSparseCSRCUDA) ... skip: test doesn't currently work on the ROCm stack (0.002s)

**Comment by jpvillam-amd** [comment]
From https://github.com/pytorch/pytorch/runs/6819237934?check_suite_focus=true#step:7:48957:
```
  test_sampled_addmm_errors_cuda_complex128 (__main__.TestSparseCSRCUDA) ... ok (0.033s)
  test_sampled_addmm_errors_cuda_complex64 (__main__.TestSparseCSRCUDA) ... ok (0.032s)
  test_sampled_addmm_errors_cuda_float32 (__main__.TestSparseCSRCUDA) ... ok (0.031s)
  test_sampled_addmm_errors_cuda_float64 (__main__.TestSparseCSRCUDA) ... ok (0.032s)
  ```

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
@malfet 
Can you please review this.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
