### PR TITLE
Step 5: remove _unique_dim in favor of unique_dim

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #18661 Step 7: remove _unique
* #18655 Step 6: Rename _unique2 to unique and add int? dim
* **#18654 Step 5: remove _unique_dim in favor of unique_dim**

See step 1 for the description of the full stack

Differential Revision: [D15000635](https://our.internmc.facebook.com/intern/diff/D15000635)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
Looks like this one creates real test failures. Please rebase so I can play with it  internally and check how we can work around.

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin rebased

**Comment by VitalyFedyunin** [comment]
Looks like I would need to change internal code a bit to land it, as it fails with:

``` 
   error: ‘_unique_dim’ is not a member of ‘torch’
   std::tuple tup = torch::_unique_dim(tl->m_tensor,
                           ^~~~~~~~~~~
```

sorry for cryptic error, had to remove file names etc.

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin No problem, take your time!

**Pull request closed without merging**
