### PR TITLE
[c10d] Reduce test time by reusing ProcessGroup

### PR DESCRIPTION
**Pull request by kwen2501**
## Problem this PR resolves
Today, most of distributed tests are arranged like this:
```
def test_allreduce(self):
    pg = self._create_process_group_nccl(store, self.opts())
    pg.allreduce(tensor)
    ...
```
Thus, we are paying PG creation time **per test**. That's bad. But why were we doing that? Is there a constraint? 

If we look deeper, we would find that most of our test cases inherit from `torch.testing._internal.common_distributed.MultiProcessTestCase`. From the name, nothing seems wrong, and probably fits distributed well. But a "problem" exists in its `setUp()` and `tearDown()` methods, which basically do the following:
```
def setUp(self):
    self._spawn_processes()

def tearDown(self):
    for p in self.processes:
        p.terminate()
```
Since `setUp` and `tearDown` are "**test-scope fixtures"**, meaning, they are called per test, each test will have brand new processes. Of course we'd have to recreate ProcessGroup every time. 

## How we are fixing it
First, obviously, we need to put a PG's lifetime into a longer scope. Python `unittest` provides such a helper, called **"class-scope fixtures."** It is embodied by a `setUpClass` method and a `tearDownClass` method (note the name difference), which are called only once for all tests in the same test class.  Therefore, we would do:
```
@classmethod
def setUpClass(self):
    dist.init_process_group(...)

@classmethod
def tearDownClass(self):
    dist.destroy_process_group()
```
**In this PR, we create a new test template for distributed: `MultiProcContinousTest`, to hold this class-scope fixture.**

Second, we'd need to avoid per-test process spawn and terminate. That's easy, we can either:
1. launch the whole test file with `torchrun --nproc-per-node=...` or
2. use `mp.spawn()` under `if __name__ == "__main__":`.

Point is, launch the processes only once.

## Result
We moved the "positive tests" from test_c10d_nccl.py to test_c10d_ops_nccl.py.
Before this PR:
```
$ python test_c10d_nccl.py -k ProcessGroupNCCLTest
Ran 24 tests in 174.457s
```
After this PR:
```
$ torchrun --nproc-per-node 2 test_c10d_ops_nccl.py
or
$ python test_c10d_ops_nccl.py
Ran 24 tests in 16.247s
```
10X speedup.

## Limitation
For tests intended to test destroy or abort of PGs, we'd need to go back to the old style. So it would make sense to divide our tests into two classes: one for positive tests where we would reuse the PGs, and the other one for abort/destroy and negative tests like watchdog timeout. 

## Next step
Migrate the tests of distributed that would fit with this test style!

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125648

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @albanD

### CODE REVIEW

**Comment by kwen2501** [comment]
@seemethere @albanD can you please unblock this PR?
```
INFO: PR SIZE is 2045
```
Majority of line changes are due to moving tests from one file to another.

**Comment by awgu** [comment]
How does this work when a test errors on all ranks? Or only on some ranks?

In particular, I am curious if we do not spawn new processes per test, then can we recover from one test erroring and continuing through to others in the same class?

**Comment by albanD** [comment]
Sounds good to skip PR sanity check as this is code movement!

**Comment by kwen2501** [comment]
> How does this work when a test errors on all ranks? Or only on some ranks?

Not sure if I understand. If the user launch the test with `python test.py`, same mechanism is used to spawn the processes as today. If the user uses `torchrun` to launch the test, `torchrun` has mechanism to gather errors from all ranks.

> In particular, I am curious if we do not spawn new processes per test, then can we recover from one test erroring and continuing through to others in the same class?

Good question. We discussed about this in yesterday's weekly meeting. 
It depends:
- If the error in a previous test is not fatal, such as `assertEqual == False`, then the test class would be able to continue with a next test.
- If the error in a previous test is fatal, and as a result, the PG or NCCL comm got corrupted, then most likely the later tests would all fail with error like "NCCL communicator has been aborted/corrupted." That should be okay, as the developer would come back to look for the first failure, and fix that.

@awgu

**Comment by awgu** [comment]
> > How does this work when a test errors on all ranks? Or only on some ranks?
> 
> 
> 
> Not sure if I understand. If the user launch the test with `python test.py`, same mechanism is used to spawn the processes as today. If the user uses `torchrun` to launch the test, `torchrun` has mechanism to gather errors from all ranks.
> 
> 
> 
> > In particular, I am curious if we do not spawn new processes per test, then can we recover from one test erroring and continuing through to others in the same class?
> 
> 
> 
> Good question. We discussed about this in yesterday's weekly meeting. 
> 
> It depends:
> 
> - If the error in a previous test is not fatal, such as `assertEqual == False`, then the test class would be able to continue with a next test.
> 
> - If the error in a previous test is fatal, and as a result, the PG or NCCL comm got corrupted, then most likely the later tests would all fail with error like "NCCL communicator has been aborted/corrupted." That should be okay, as the developer would come back to look for the first failure, and fix that.
> 
> 
> 
> @awgu 

I want to check if this new UX has a difference from existing. Today, I can run a test file, and I can get a summary at the end of which tests passed and which tests failed. If I understand correctly, with this new approach from this PR, once the first test fails, all subsequent tests in the same class now fail. There seems there may be some loss in test signal? (E.g. the CI "keep-going" label no longer applies in the same way for these tests)

If so, I would argue that this signal is important during debugging, and it is worth considering the implication on developer experience.

**Comment by kwen2501** [comment]
That's a fair concern. 

As described in the PR, we are moving a bunch of "positive" tests out. Though there may still be non-zero chance that a "positive" test would corrupt the PG, the percentage is relatively low among CI activities of all PRs. One step back, if any op indeed corrupts the PG, there is a high chance that other ops suffer the same issue. In that case, I am not sure if --keep-going is a good fit. For example, in the old case, the test may need to go through 300 timeouts before a failure signal is returned; whereas today our CI will return that signal as soon as the first timeout.

**Comment by wconstab** [comment]
One possible middle ground is to offer a way to switch the behavior back to the old way. Would it be useful if after noticing a cascading failure on CI, a user could use an env or flag to locally make the test run in the slower/sequential way?

I prefer each test to be isolated and create their own PG, and if we could make PG init fast enough I'd rather go that route. But a 10x reduction in test time is too good to ignore, and would help all of us most of the time.

**Comment by awgu** [comment]
That makes sense for this set of tests! I was just thinking about distributed tests in general where we may not make the same assumption about one test failing being indicative of other tests failing for the same reason (since the PR description says to migrate all distributed tests).

To check my understanding: is the only issue PG corruption (what causes PG corruption)? What if one test fails a numeric assertion? Would the rest of the tests no longer run, or is there a way for the process to continue? What if the assertion only fails on one rank?

**Comment by kwen2501** [comment]
@awgu 

> What if one test fails a numeric assertion? 

Numeric assertion is a "user behavior" so it does not bother the PG in any manner. So, the Test class should be able to continue with the rest of tests healthy, by default.

> what causes PG corruption

Like, the test was deliberately testing comm abort, comm destroy, etc. 
Or, the test hit a timeout -- whether we abort the PG or not, the PG is corrupted, bc today there is no way to back out an operation.

**Comment by kwen2501** [comment]
> I was just thinking about distributed tests in general where we may not make the same assumption

I agree. This PR did not remove the old `MultiProcessTestCase`. 
If any distributed test works better with the old behavior, please feel free to use this existing TestCase.

I am just:
1. providing an alternative; and
2. calling people to be mindful when they choose the base Test class.

@awgu @wconstab

**Review by wconstab — APPROVED** [review]
i think we should ship this,

it will be a process anyway- folks will migrate tests, we'll see if any real usability issues pop up.

I would appreciate a way (a flag) to go back to the old behavior even with the new test class- hopefully thats easy to implement.  Then we can at least have an escape hatch if we get stuck down the line

**Comment by kwen2501** [comment]
@wconstab thanks for the suggestion!
If we add a flag, we can (might as well) merge the two classes into one, which makes our test infra simpler.
Good idea :) But one thing at a time.
Thanks for the review :)

**Pull request closed without merging**
