### PR TITLE
Add bfloat16 CUDA support to RNN

### LINKED ISSUE #116763: "_thnn_fused_gru_cell_cuda" not implemented for 'BFloat16'
### 🚀 The feature, motivation and pitch

Hi, 

I use an evaluation code with GRU model. 
fp16 is OK, and supports GRUcell, while bf16 cannot work. 

RuntimeError: "_thnn_fused_gru_cell_cuda" not implemented for 'BFloat16'

### Alternatives

Currently, I autocast back to fp32 by 
```python
        with torch.autocast(device_type='cuda', dtype=torch.float32):
            gru_seq, gru_last = self.gru(emb, hidden)
```

### Additional context

_No response_

cc @zou3519 @mikaylagawarecki @ptrblck

### LINKED ISSUE #116925: Bfloat16 operation not working on LSTM.
### 🐛 Describe the bug
```python
Traceback (most recent call last):
  File "/root/lstm_bf16_test.py", line 23, in <module>
    model()
  File "/root/pytorch/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/lstm_bf16_test.py", line 17, in forward
    self.lstm(self.embedding(input_tensor))
  File "/root/pytorch/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pytorch/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pytorch/torch/nn/modules/rnn.py", line 878, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: "_thnn_fused_lstm_cell_cuda" not implemented for 'BFloat16'

```
hi pytorch team    
     
While running LSTM with Bfloat16 on GPU, I got the following error.      
I think it's the same as this [issue](https://github.com/pytorch/pytorch/issues/107914) I had before,       
and it's caused by not being able to handle Bfloat16 in the [code](https://github.com/pytorch/pytorch/blob/2dca3e99ebe1655982ac0a1978c02ae761ebf1d8/aten/src/ATen/native/cuda/RNN.cu#L533-L539) field.
     
PR of #114785 fixes this error.

### Example 
```python
import torch.nn as nn
import torch


class Model(nn.Module):
    def __init__(self):
        super().__init__()

        input_size = 10
        hidden_size = 20

        self.embedding = nn.Embedding(input_size, hidden_size)
        self.lstm = nn.LSTM(hidden_size, hidden_size)

    def forward(self, input):
        hidden_states = self.embedding(input)
        self.lstm(hidden_states)


model = Model()
model = model.to("cuda").to(torch.bfloat16)

input_tensor = torch.tensor(range(5), dtype=torch.long, device="cuda")
model(input_tensor)

```

### Versions

PyTorch version: 2.3.0a0+git2dca3e9
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-213-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          48
On-line CPU(s) list:             0-47
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       2
Stepping:                        7
Frequency boost:                 enabled
CPU max MHz:                     2401.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4800.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       768 KiB (24 instances)
L1i cache:                       768 KiB (24 instances)
L2 cache:                        24 MiB (24 instances)
L3 cache:                        33 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-11,24-35
NUMA node1 CPU(s):               12-23,36-47
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.3
[pip3] numpydoc==1.5.0
[pip3] optree==0.10.0
[pip3] torch==2.3.0a0+git2dca3e9
[conda] _anaconda_depends         2023.09             py311_mkl_1  
[conda] blas                      1.0                         mkl  
[conda] magma-cuda118             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-include               2023.1.0         h06a4308_46344  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.8           py311h5eee18b_0  
[conda] mkl_random                1.2.4           py311hdb19cb5_0  
[conda] numpy                     1.26.3          py311h08b1b3b_0  
[conda] numpy-base                1.26.3          py311hf175353_0  
[conda] numpydoc                  1.5.0           py311h06a4308_0  
[conda] optree                    0.10.0                   pypi_0    pypi
[conda] torch                     2.3.0a0+git2dca3e9           dev_0    <develop>

cc @zou3519 @mikaylagawarecki @ptrblck

### PR DESCRIPTION
**Pull request by Skylion007**
Fixes #116925 
Fixes #116763

cc @ptrblck

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM

**Comment by fanlu** [comment]
Is there some problem? @ptrblck @pytorchbot @pytorchmergebot

**Comment by aniquetahir** [comment]
I'm still getting 
```"_thnn_fused_gru_cell_cuda" not implemented for 'BFloat16'```
in torch 2.2.1

**Comment by alexjwilliams** [comment]
> I'm still getting `"_thnn_fused_gru_cell_cuda" not implemented for 'BFloat16'` in torch 2.2.1

The fix was not included in 2.2.1. If you build pytorch using commit 9504182, it will work.

**Comment by ben-da6** [comment]
Is the plan for this to be added, having bfloat16 rnns on the gpu would be useful!

**Pull request closed without merging**
