### PR TITLE
Fix the kineto daemon build condition

### PR DESCRIPTION
**Pull request by dzhulgakov**
If we're not building the lite interpreter we shouldn't be disabling Kineto. This eliminates a step from https://github.com/facebookincubator/dynolog/blob/main/docs/pytorch_profiler.md

### CODE REVIEW

**Review by kimishpatel — APPROVED** [review]
Looks good/

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Ok, perhaps I misunderstand what this PR is doing, but it should have zero effect on regular builds, shouldn't it?

**Comment by robieta** [comment]
My best guess is this block:
```
// Ondemand tracing is not supported on Apple or edge platform
#if defined(__APPLE__) || defined(EDGE_PROFILER_USE_KINETO)
#define ENABLE_GLOBAL_OBSERVER (0)
#else
#define ENABLE_GLOBAL_OBSERVER (1)
#endif
```

If I'm reading the build files correctly we set `USE_LITE_INTERPRETER_PROFILER` by default and then unset it on android. So AFAICT we've been disabling global observer and dodging the bullet in OSS by accident.

**Comment by malfet** [comment]
Ok, then it makes total sense. So, do we need global observer for OSS builds?

**Comment by dzhulgakov** [comment]
I think generally having global observer in OSS is nice. There's some work to release on demand profiling with dynolog, and right now its build instructions start with "go change pytorch's CMake": https://github.com/facebookincubator/dynolog/blob/main/docs/pytorch_profiler.md#pytorch-setup . cc @briancoutinho who added this. In fact playing with this on-demand profiling is what prompted me to send this PR.

**Comment by dzhulgakov** [comment]
I debugged it a bit further. The crash happens in the background thread that updates Kineto's config during shutdown. See stack traces from gdb: https://gist.github.com/dzhulgakov/8615dfe73cf32c152261329760e203cd

Here's my best guess on what's happening:
1. `test/test_jit_cuda_fuser.py` has one of the tests that invokes `torch.profiler`. It initializes Kineto and starts the background config update thread (which is a strange behavior on its own).
2. The stack trace mentions `std::__throw_bad_function_call()` inside `Config`'s constructor. My best guess is that it's a `std::function` that already got destroyed.
3. Background thread supposedly should be safe to stop. `~ConfigLoader` stops it and there's some weird logic here to prevent static objects destruction: https://github.com/pytorch/kineto/blob/main/libkineto/src/Config.cpp#L173 . Evidently, it doesn't work because of some ordering issues that I don't fully understand
4. It only triggers in the nvfuser test because it has a disproportionately long destruction sequence (see another thread being stuck in `~CudaFusionManager()`). It's enough for the background thread to trigger the update. I tried to repro it on smaller tests (including putting `sleep` in destructors) but couldn't do so reliably.

How to fix it? Here's one option that makes it pass with an explicit `atexit` handler: https://github.com/pytorch/kineto/compare/main...dzhulgakov:kineto:thread-stop?expand=1

Also, the whole behavior of "launching profiler creates a background thread for the rest of the lifetime" seems strange. I prefer to gate this behavior by `KINETO_USE_DAEMON` environment variable like in #89323.

Note that in my understanding in fbcode this is already a current behavior as it was built with Kineto I believe. If so, it's a good guarantee that the background thread is not that harmful.

@robieta do you have an opinion of which fix to pick?

**Comment by dzhulgakov** [comment]
A better fix for Kineto: https://github.com/pytorch/kineto/pull/696 . I verified that with this fix this test passes. I'm going to resubmit this PR after the fix lands together with the updated Kineto submodule reference

**Comment by robieta** [comment]
@dzhulgakov You're an absolute hero!

**Pull request closed without merging**
