### PR TITLE
Raise NotImplementedError on forward passes

### PR DESCRIPTION
**Pull request by Varal7**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #59485 Throw RunTimeError using TORCH_CHECK
* **#59483 Raise NotImplementedError on forward passes**
* #59482 Use TORCH_CHECK_NOT_IMPLEMENTED for AD not implemented

... for functions that are not implemented

Summary:

Test Plan:

Reviewers: albandes

Subscribers:

Tasks:

Tags:

Differential Revision: [D28933806](https://our.internmc.facebook.com/intern/diff/D28933806)

### CODE REVIEW

**Comment by Varal7** [comment]
@varal7 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28933806).

**Review by albanD — COMMENTED** [review]
Missing tests in test_autograd here as well.

Also I think this is going to break the test/test_ops.py as it expects a runtime error: https://github.com/pytorch/pytorch/blob/94cc681fc2e5218c10493938a8ca01272c3c6fc0/test/test_ops.py#L227

**Comment by Varal7** [comment]
I could not test if this breaks more tests in `test/test_ops.py` as tests are currently already failing (#59568)

**Comment by Varal7** [comment]
@varal7 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28933806).

**Review by albanD — APPROVED** [review]
LGTM Thanks for the tests

**Pull request closed without merging**
