### PR TITLE
Make opacus xfail instead of skip

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99380

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by desertfire — APPROVED** [review]
Annoyingly that I haven't included an expected result file for CPU run. You either need to add opacus to https://github.com/pytorch/pytorch/blob/59e343b12c024009ca197000c630a6883d9e231c/benchmarks/dynamo/common.py#L175, or you can generate a cpu expected result file (need a little twist to your download script).

**Comment by anijain2305** [comment]
xref - https://github.com/pytorch/pytorch/issues/99201

**Review by anijain2305 — APPROVED** [review]

**Comment by wconstab** [comment]
> xref - https://github.com/pytorch/pytorch/issues/99201

note: my xfailing here applies only to cuda, which isn't the focus of 99201.  We do not have infra for xfailing inductor cpu models, and the cpu side is still failing and being skipped.

**Pull request closed without merging**
