### PR TITLE
Update Kineto to fix fd leak

### LINKED ISSUE #59746: Kineto leaks file descriptors during normal `processName()` call
CUDA 10.2 builds on GHA started to fail earlier day after https://github.com/pytorch/pytorch/commit/0897df18a314f7a74dce9fcd065d6d7e4cab47d7 was merged in.

The error it fails with looks like ([logs](https://github.com/pytorch/pytorch/runs/2786062691?check_suite_focus=true)):
```
Traceback (most recent call last):
  File "test_foreach.py", line 994, in <module>
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 301, in run_tests
  File "/opt/conda/lib/python3.6/unittest/main.py", line 95, in __init__
  File "/opt/conda/lib/python3.6/unittest/main.py", line 256, in runTests
  File "/opt/conda/lib/python3.6/site-packages/xmlrunner/runner.py", line 112, in run
  File "/opt/conda/lib/python3.6/site-packages/xmlrunner/result.py", line 621, in generate_reports
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
OSError: [Errno 24] Too many open files: '/opt/conda/lib/python3.6/xml/dom/__init__.py'
Traceback (most recent call last):
  File "test/run_test.py", line 1254, in <module>
    main()
  File "test/run_test.py", line 1233, in main
    raise RuntimeError(err_message)
RuntimeError: test_foreach failed!
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @Varal7 @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git

### PR DESCRIPTION
**Pull request by malfet**
Update to commit containing pytorch/kineto#281
Fixes https://github.com/pytorch/pytorch/issues/59746

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Comment by ilia-cher** [comment]
cc. @gdankel on the latest changes to kineto - looks like there're some build errors now

**Comment by ngimel** [comment]
Yep, we need to set USE_KINETO_UPDATED (where?) together with the submodule update. @gdankel can you point to the place?

**Comment by gdankel** [comment]
Checking!

**Comment by ilia-cher** [comment]
> Yep, we need to set USE_KINETO_UPDATED (where?) together with the submodule update. @gdankel can you point to the place?

no, we don't need to set it up (it's not set in oss on purpose) - we use it (btw, similarly to hhvm folks as I was told) to resolve a trivial issue when landing oss and internal changes when the oss version has a submodule is at a fixed revision - we just need to assume that USE_KINETO_UPDATED is defined, remove the usage of USE_KINETO_UPDATED, keep the code sections that are within USE_KINETO_UPDATED and discard the ones that are in the 'else' section

**Comment by gdankel** [comment]
@ilia-cher isn't the process you used in the past to remove the old code and compile flag?

**Comment by ilia-cher** [comment]
> @ilia-cher isn't the process you used in the past to remove the old code and compile flag?

you're right, looks like we just need to remove !USE_KINETO_UPDATED sections

**Comment by ilia-cher** [comment]
> @ilia-cher isn't the process you used in the past to remove the old code and compile flag?

ideally, we just need to remove usages of USE_KINETO_UPDATED by updating the submodule after changes to the kineto were landed, USE_KINETO_UPDATED is supposed to be used only temporarily in between those two events

**Comment by gdankel** [comment]
Yes exactly - it's part of updating submodule.

**Comment by ngimel** [comment]
Like this #59767?

**Comment by malfet** [comment]
Should we just fork it then?

**Pull request closed without merging**
