### PR TITLE
Add non-recursive module.to_empty option

### LINKED ISSUE #97049: [nn.Module] Non-recursive `_apply()`
**Overview**
This is a feature request for a version of `_apply()` that does not call recursively and instead only applies to the target module, not its submodules. In other words, it skips the first two lines in its current implementation:
https://github.com/pytorch/pytorch/blob/985fc66b308c37bed4c0337e795de4abd929a97a/torch/nn/modules/module.py#L795-L797

For parameter offloading schemes, modules' parameters may no longer have uniform device. Being able to call an API similar to the existing `.to()` but only applying to a target module and not its submodules facilitates clean parameter offloading implementations.

**Case Study: `FullyShardedDataParallel`**
When a user passes both `cpu_offload=CPUOffload(True)` and `device_id` to PyTorch `FullyShardedDataParallel` (FSDP), where there are nested FSDP instances, FSDP calls `module.to(device)`, which incorrectly moves _all_ module's parameters to `device` including submodules whose parameters have already been offloaded to CPU. This greatly reduces the model size that FSDP can support because already sharded parameters in submodules are moved to GPU when they should stay on CPU. The `device_id` argument can help speed up FSDP initialization when CPU offloading is enabled since the flattening and sharding happens on GPU, not CPU.

We want to replace the `module.to(device)` call with a version that traverses `module.modules()` but does not proceed into any existing FSDP module and only moves the traversed modules to `device`. This is where the non-recursive `_apply()` / `to()` helps. Then, we will be able to support much larger models with CPU offloading enabled and `device_id` specified.

**API**
Since `_apply()` is the basis for several public frontends like `.to()`, `.cuda()`, `.cpu()`, adding a `recurse: bool` argument to all may be a sweeping change. Hence, another option is to have a private API like `_apply_non_recursive(fn)` that subsumes the current `_apply()` implementation minus the first two lines:
```
def _apply_non_recursive(fn):
    # Current `_apply()` implementation minus first two lines
    ...

def _apply(fn):
    for module in self.children(): 
        module._apply(fn)
    return _apply_non_recursive(fn)
```

Alternatively, we (the distributed team) could effectively fork the current `_apply()` implementation in distributed code to unblock our FSDP use case. Regardless, any alternative seems to require peaking into the `module._parameters` dict ourselves.

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Fixes https://github.com/pytorch/pytorch/issues/97049, related to https://github.com/pytorch/pytorch/issues/104187

Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #104197

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM
Note that this will break any Module that re-defines `_apply` with the current signature. No one should be doing that but there is a non-zero probability it is happening in the wild.

**Comment by mikaylagawarecki** [comment]
@albanD ah that is true, hm is there any way to workaround this?

**Review by albanD — COMMENTED** [review]
> (just to check it only breaks those overrides of _apply that don't define *args and **kwargs is that correct?)

Correct!
Should we change these to `*args, **kwargs` btw?

**Comment by mikaylagawarecki** [comment]
@albanD should we also make that change for other methods other than `_apply`, I feel as if that might apply to most of our nn.Module methods which are probably overrided in some of our core modules. 

I can do this in a follow up if that makes sense!

**Comment by albanD** [comment]
Yes that can be a follow up for sure.
Also our internal Module should not override these these days I suspect and should be using the proper hooks!

**Comment by mikaylagawarecki** [comment]
Hmm, does that mean we should have hooks for private `_apply` 🤔

**Pull request closed without merging**
