### PR TITLE
[BE]: Update cudnn_frontend submodule to v1.1.0

### PR DESCRIPTION
**Pull request by Skylion007**
Updates the CUDNN_frontend header only library to 1.1.0 . This mainly has some bugfixes a long with a few new APIs.

cc @ptrblck

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by Skylion007** [comment]
Really not sure how to fix this... Hmm...

**Review by eqy — COMMENTED** [review]
@Skylion007 I'll take a look into this; hopefully it's something relatively minor like the cuDNN binary needing to be bumped to stay in sync but if not the DCGAN tests look like they would have fairly self-contained repros that I can forward to cuDNN.

**Comment by eqy** [comment]
response from cuDNN is that the issue is probably https://github.com/NVIDIA/cudnn-frontend/compare/v1.0.3...v1.1.0#diff-096a04190a9a28272c70899410e8bf3c249cba1ea49c857f8a723c86493e4fb7L99

so we're awaiting a workaround/fix from their side

**Pull request closed without merging**
