### PR TITLE
Fixes for C++ build on macOS

### PR DESCRIPTION
**Pull request by goldsborough**
We hadn't enabled the C++ build in CI on macOS, so we missed some warnings/errors.

This PR fixes those warnings and puts the C++ build into the mac CI.

@ebetica @lantiga @ezyang

### CODE REVIEW

**Review by ebetica — APPROVED** [review]

**Comment by ebetica** [comment]
This worked for me locally so you have at least one data point :)

**Comment by lantiga** [comment]
I confirm it works for me too.

Just two questions:
1. it's not clear to me why we need to run `"${TOOLS_PATH}/autograd/gen_python_functions.py"`, as it seems to generate files that libtorch does not include;
2. I'm wondering if we could make building `torch/csrc/api/` optional at the CMAKE level; if you just need to execute the IR you don't necessarily need the cpp API and you can get a way with a lighter / faster to build binary.

**Comment by goldsborough** [comment]
True might be that `python_functions.py` isn't required, I didn't really check that one. Will remove.

Yes I can add a `WITH_API` flag that you can set to `0` if you don't want the api, is that ok?

**Comment by lantiga** [comment]
`WITH_API` would work, thanks! It would be perfect if you could expose it at the `build_libtorch.sh` level as well, so that it takes the value of the env var and passes it on to CMake.

**Comment by lantiga** [comment]
Looks great, thanks!

**Comment by ezyang** [comment]
Is the C++ API really that heavyweight? With the size of CUDA and rampant code generation, surely a set of three C++ classes (with no extra deps, to boot) is not that much.

**Review by ezyang — APPROVED** [review]

**Comment by lantiga** [comment]
@ezyang true, although I noticed that my Mac spent a loong time compiling optimizers.cpp. I haven’t investigated further though.

**Comment by ebetica** [comment]
It's actually some other generated files, I think aten_dispatch.cpp. Zach said https://github.com/pytorch/pytorch/pull/6965 doubled the number of lines. If you make a change to optimizers.cpp, it compiles much faster the second time around.

**Comment by lantiga** [comment]
It’s very likely the case. Ninja was showing the build stuck on optimizers, but it could have been that some other thread was stealing most of the resources.

**Pull request merged**
