### PR TITLE
Assert that evaluate_expr matches hint

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #97792

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Comment by ezyang** [comment]
Lol these failures...

**Comment by ezyang** [comment]
This is blocked on proper ranges for input symints, which is in turn blocked on sharing shape env with backward.

**Review by avikchaudhuri — APPROVED** [review]

**Comment by ysiraichi** [comment]
I tried running this with TV on, and here's what I've found:
- The test still succeeds after removing the asserts, i.e. TV doesn't catch that
- **Reason:** the guard `Eq(s1, 56)` is issued alongside the problematic `Mod(3, s1) > 1`

**Comment by ezyang** [comment]
@ysiraichi Hmm, I wonder why TV doesn't catch this? Because the reference implementation shouldn't be going through sympy at all, thereby skipping this violation.

**Comment by ezyang** [comment]
Oh I see. OK, seems fine. So let's fix us to not use sympy Modulus and then land this assert. They're orthogonal.

**Pull request closed without merging**
