### PR TITLE
SymIntify convolution backend calculation

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #89038
* __->__ #89069
* #89074
* #89063
* #89062
* #89059

We will need this to implement a convolution meta function that
is SymInt aware.  I use templates so that regular convolution code
is not affected by the change.  No tests for symbolic ints directly; that will
come in a subsequent PR which also needs to refactor fake tensors.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

cc @VitalyFedyunin @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by ezyang** [comment]
hud https://hud.pytorch.org/pr/89069

**Review by eellison — COMMENTED** [review]
will there be any overhead here ?

**Comment by ezyang** [comment]
No, because I templated all the functions.

**Review by SherlockNoMad — APPROVED** [review]

**Pull request closed without merging**
