### PR TITLE
Fix `nn.functional.max_poolNd` dispatch (for arg: `return_indices`)

### LINKED ISSUE #62545: Incosistency with args for `nn.functional.max_poolNd` vs `nn.MaxPoolNd` functions
## 🐛 Bug

Note: For this issue, I'll be taking `max_pool2d` as an example function. The same is applicable for `max_pool1d` and `max_pool3d`.

The position/index (starting from 0) of `return_indices` arg for `nn.functional.max_pool2d` as described in the [documentation](https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html#torch.nn.MaxPool2d) should be `5` but when used at the 5th position, it doesn't do what it should (should return a tuple of tensors). Instead, passing it as the `6th` argument/index works.

## To Reproduce

_Note the order of the args corresponds to:_ `input_shape, kernel_size, stride, padding, dilation, return_indices, ceil_mode`

`nn.functional.max_pool2d` behavior:

```python
>>> tens = torch.randn((1, 3, 9, 9))

# return_indices should be True here according to the doc
>>> len(nn.functional.max_pool2d(tens, (3, 3), None, 0, 1, True, False))
1

# return_indices should be False here according to the doc
>>> len(nn.functional.max_pool2d(tens, (3, 3), None, 0, 1, False, True))
2
```

`nn.MaxPool2d` behavior:

```python
>>> tens = torch.randn((1, 3, 9, 9))

# Note that True is passed at the 5th index, and it works fine (as expected): output length is 2
>>> mp2d = torch.nn.MaxPool2d((3, 3), None, 0, 1, True, False)
>>> len(mp2d(tens))
2

# Note that False is passed at the 5th index, and it works fine (as expected): output length is 1
>>> mp2d = torch.nn.MaxPool2d((3, 3), None, 0, 1, False, True)
>>> len(mp2d(tens))
1
```

## Expected behavior

`nn.functional.max_pool2d` behavior should be consistent with `nn.MaxPool2d` as that's where the [docs](https://pytorch.org/docs/stable/generated/torch.nn.functional.max_pool2d.html) point it to!

```python
>>> tens = torch.randn((1, 3, 9, 9))

>>> len(nn.functional.max_pool2d(tens, (3, 3), None, 0, 1, True, False))
2

>>> len(nn.functional.max_pool2d(tens, (3, 3), None, 0, 1, False, True))
1
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0a0+git6a6830f
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source

## Additional context

Came up with this issue when `test_variant_consistency_jit_nn_functional_max_pool2d_cuda/cpu_float32` was failing (while trying to add `OpInfo` for it).

```python
======================================================================
ERROR: test_variant_consistency_jit_nn_functional_max_pool2d_cuda_float32 (__main__.TestJitCUDA)
----------------------------------------------------------------------
... (only sharing relevant error detail)
RuntimeError: aliasOp != torch::jit::getOperatorAliasMap().end()INTERNAL ASSERT FAILED at "../torch/csrc/jit/passes/utils/check_alias_annotation.cpp":159, please report a bug to PyTorch. 
```

Trying to debug further, here is how the method graph looks:

* when `return_indices` is passed as `False` as positional arg at index `5` to `nn.functional.max_pool2d`, and index 6 which should correspond to `ceil_mode` is passed as `True`) - It returns a tuple of tensors (output and indices) - which is wrong.

```python
graph(%i0.1 : Tensor):
  %9 : bool = prim::Constant[value=0]() # <string>:3:76
  %33 : int[] = prim::Constant[value=[5, 5]]()
  %34 : int[] = prim::Constant[value=[2, 1]]()
  %35 : int[] = prim::Constant[value=[2, 2]]()
  %37 : int[] = prim::Constant[value=annotate(List[int], [])]()
  %30 : Tensor, %31 : Tensor = aten::max_pool2d_with_indices(%i0.1, %33, %37, %34, %35, %9) # /home/krshrimali/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/nn/functional.py:693:11
  %32 : (Tensor, Tensor) = prim::TupleConstruct(%30, %31)
  return (%32)
```

* when `return_indices` is passed as `True` as positional arg at index `5` to `nn.functional.max_pool2d`, and index 6 which should correspond to `ceil_mode` is passed as `False`)

```python
graph(%i0.1 : Tensor):
  %10 : bool = prim::Constant[value=0]() # <string>:3:82
  %31 : int[] = prim::Constant[value=[5, 5]]()
  %32 : int[] = prim::Constant[value=[2, 1]]()
  %33 : int[] = prim::Constant[value=[2, 2]]()
  %35 : int[] = prim::Constant[value=annotate(List[int], [])]()
  %30 : Tensor = aten::max_pool2d(%i0.1, %31, %35, %32, %33, %10) # /home/krshrimali/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/nn/functional.py:718:11
  return (%30)
```

The issue seems to be with the `arg_index` mentioned in the `boolean_dispatch` call. Please see https://github.com/pytorch/pytorch/pull/62544 ~for the suggested fix~ for the draft fix, WIP.

cc: @thomasjpfan @Lezcano @kshitij12345 

cc @albanD @mruberry @jbschlosser @heitorschueroff

### PR DESCRIPTION
**Pull request by krshrimali**
Please see https://github.com/pytorch/pytorch/issues/62545 for context.

The order of `return_indices, ceil_mode` is different for `nn.functional.max_poolNd` functions to what seen with `torch.nn.MaxPoolNd` (modular form). While this should be resolved in the future, it was decided to first raise a warning that the behavior will be changed in the future. (please see https://github.com/pytorch/pytorch/pull/62544#issuecomment-893770955 for more context)

This PR thus raises appropriate warnings and updates the documentation to show the full signature (along with a note) for `torch.nn.functional.max_poolNd` functions.

**Quick links:**

(_upstream_)
 
* Documentation of [`nn.functional.max_pool1d`](https://pytorch.org/docs/1.9.0/generated/torch.nn.functional.max_pool1d.html), [`nn.functional.max_pool2d`](https://pytorch.org/docs/stable/generated/torch.nn.functional.max_pool2d.html), and [`nn.functional.max_pool3d`](https://pytorch.org/docs/stable/generated/torch.nn.functional.max_pool3d.html).

(_this branch_)

* Documentation of [`nn.functional.max_pool1d`](https://docs-preview.pytorch.org/62544/generated/torch.nn.functional.max_pool1d.html?highlight=max_pool1d), [`nn.functional.max_pool2d`](https://docs-preview.pytorch.org/62544/generated/torch.nn.functional.max_pool2d.html?highlight=max_pool2d#torch.nn.functional.max_pool2d), and [`nn.functional.max_pool3d`](https://docs-preview.pytorch.org/62544/generated/torch.nn.functional.max_pool3d.html?highlight=max_pool3d#torch.nn.functional.max_pool3d).

cc @ezyang @gchanan @albanD @mruberry @jbschlosser @walterddr

### CODE REVIEW

**Comment by krshrimali** [comment]
Please note that this isn't tested unless and until we add the OpInfos for these (I'm working on these). Once this is merged, the other OpInfo PRs should be easy to land. :) Thanks!

**Comment by thomasjpfan** [comment]
To make this change we would need to update:

https://github.com/pytorch/pytorch/blob/51f687fd4b97d5bf9b1a20a849923c0ad2e93cee/torch/nn/modules/pooling.py#L88-L90

to use the updated positioning.

Note that changing the order is BC breaking.

**Comment by mruberry** [comment]
@jbschlosser (our nn lead) and @heitorschueroff (who recently did some work on pooling) -- would you please take a look and shepherd this through?

**Comment by krshrimali** [comment]
This PR required changes in:

* `test/test_jit.py`: for JIT tests with 5th arg as `return_indices=True` instead of 6th.
* `torch.nn.quantized` module
* `torch.nn.functional` module
* `torch.nn.MaxPoolNd` classes

All test cases pass now. This is ready for review if you can kindly take a look whenever you find the time. @thomasjpfan @jbschlosser @heitorschueroff 

Thanks!

**Review by heitorschueroff — APPROVED** [review]
Changes look good, but let's wait on @jbschlosser approval for the nn module changes. Thank you!

**Comment by jbschlosser** [comment]
Hey @krshrimali, thanks for the investigation & fix! Could you please provide a bit more detail on what problems arise from the inconsistency between the module and functional forms? Does this result in incorrect behavior somewhere or is it just confusing for users?

I think we should carefully consider how to move the fix forward, since it's BC-breaking. A safer rollout could be to emit a warning for users that the order of args does not match between the two forms but will be changed to match in a future release. Ideally, this warning should be only be emitted when the user sets only one of the flags to True positionally (but this might not be feasible). We'd also want to warn in the docs that the arg order is different. Thoughts on this approach?

**Comment by krshrimali** [comment]
> Hey @krshrimali, thanks for the investigation & fix! Could you please provide a bit more detail on what problems arise from the inconsistency between the module and functional forms? Does this result in incorrect behavior somewhere or is it just confusing for users?

Thanks, @jbschlosser for taking a look! Good questions. So, the functional form is expected to take the same order as the module form (as indirectly suggested in the docs: https://pytorch.org/docs/stable/generated/torch.nn.functional.max_pool2d.html):

```python
torch.nn.MaxPool2d(kernel_size, stride=None, padding=0, dilation=1, return_indices=False, ceil_mode=False)
```

Now here, `return_indices` is the second last argument, which should work for `torch.nn.functional.max_pool2d` as well but it doesn't. (please see the PR description for a few examples)

Either documentation can be added for functional forms, mentioning the correct order of the arguments _OR_ this can be fixed. I think a lot of people use this as a keyword argument, but in the future, if someone decided to use this as a position argument - this will give incorrect results unless and until we fix the documentation or the implementation (ordering).

Fixing the documentation, in my opinion, may not be the best idea to solve this inconsistency since ideally, the order of arguments should match for both module and functional forms. But again, this is just me thinking out loud and I understand, since this is a BC-breaking change (and my first PR on a bc-breaking change), so I may not have the best idea on what's the most reasonable fix.

>I think we should carefully consider how to move the fix forward, since it's BC-breaking. A safer rollout could be to emit a warning for users that the order of args does not match between the two forms but will be changed to match in a future release. Ideally, this warning should be only be emitted when the user sets only one of the flags to True positionally (but this might not be feasible). We'd also want to warn in the docs that the arg order is different. Thoughts on this approach?

Temporarily, this does sound okay to me. I'm just thinking, if users are using either functional or module forms, they'll expect the args to be the same and may not visit the document of the other form! See: https://stackoverflow.com/questions/58514197/difference-between-nn-maxpool2d-vs-nn-functional-max-pool2d for example, they ideally expect it to be the same, and I'm just thinking if it will be a good structure to have different positions of args for both forms?

Raising a warning that this will be fixed in the future is a good idea, along with adding in the documentation but then, this arg (`return_indices`) doesn't seem to be used as a positional arg but looks more like a kw-preferred arg. Else this issue must have been reported before, so maybe we can just go ahead and fix the implementation? I'm really sorry since I am not sure what's the best and I'm looking forward to reading your opinion on this.

Thank you again for taking a look, I appreciate that @jbschlosser!

**Comment by jbschlosser** [comment]
Thanks for the added insight, @krshrimali! I certainly agree with you that ideally the two arg lists should be ordered consistently, and it's confusing otherwise. That said, unfortunately, I don't think we can just fix the implementation immediately.

While it may be true that generally `return_indices` / `ceil_mode` are kw-preferred args, note that code in JIT-serialized models includes all args spelled out positionally, so this change may break such models. Max pooling in general is a very frequently used set of operations, so I think it's best to move forward with a slow and safe change to avoid breakage.

So I recommend the following for this PR:
* Include the full function signature for `F.max_poolNd()` instead of just pointing to the module docs
* Add a warning in each of the functional form docs indicating that the order of the two args is currently different, but will change in a future release
* Emit a one-time warning when `ceil_mode != return_indices` indicating that the order of these will change to match the module arg list in a future release

**Comment by krshrimali** [comment]
This makes total sense, thanks a lot @jbschlosser for the help! I'll make these changes and ping you again (/request your review) once it's ready.

**Comment by jbschlosser** [comment]
Hey @krshrimali, just checking in again- I see the changes were reverted but nothing yet for me to review, is that correct?

**Comment by krshrimali** [comment]
Hi @jbschlosser - Yes, you are right and I'm really sorry for the delay in picking this up. Got caught up with other PRs, will work on this PR in the coming 2 days, and will ping you for your review (whenever you find the time). I am sorry again for the delay, glad to see you back from the PTO :)

**Comment by jbschlosser** [comment]
Sounds good! No rush- I've got plenty of other reviews to catch up on :)

**Comment by jbschlosser** [comment]
Hey @krshrimali, sorry for the delay!

> Hi @jbschlosser - requesting your review on this, whenever you find the time. There is an error I'm aware of: https://app.circleci.com/pipelines/github/pytorch/pytorch/370946/workflows/54b86787-384c-4cef-9c4f-880e78575e1f/jobs/15648599 and I am not too sure right now (haven't given this a closer look yet) but I'll spend some time looking at it before Friday.

This is an FX error; it can't handle control flow on the inputs. So this makes the conditional warning a bit more annoying to produce :) @jamesr66a do you have any insight here into how we throw this warning without breaking FX? Or should we just indicate that the function is untraceable in the functional FX test?

> I am not aware of a way to enable adding a full signature to this function in the documentation, and I'll appreciate it if you could point me to a solution on this (if any).

Can you use the `_add_docstr` function to do this? There's some example usage of it within `torch/nn/functional.py`.
```python
max_pool1d = boolean_dispatch(
    ...
)

max_pool1d = _add_docstr(
    max_pool1d,
    r"""
    <Add full signature and docs here>
    ...
    """
)
```

**Comment by jamesr66a** [comment]
Hey @krshrimali @jbschlosser,

To fix the FX test, for now just add `max_pool*d_with_indices` to the exclude list on `TestFunctionalTracing`: 

https://github.com/pytorch/pytorch/blob/cfa6162e5e5bafcb1e89bd14b64ae336f57fcdbe/test/test_fx.py#L3526

cc @jfix71 @ansley `if: warnings.warn` might be a pattern eligibile for AST rewriting

**Comment by krshrimali** [comment]
Thanks, @jbschlosser, and @jamesr66a for the valuable inputs. This PR should be ready for review now. Sincere apologies for the delay.

Looks like updating the documentation inline did the trick, not sure why it didn't work before though. I've updated the links of docs built from this branch in the PR's description.

Can you please take a look whenever you find the time? Thanks for the patience, and help!

**Review by jbschlosser — APPROVED** [review]
Hey @krshrimali, looks good! Do you mind doing a rebase? We can get this in after that :)

**Comment by krshrimali** [comment]
> Hey @krshrimali, looks good! Do you mind doing a rebase? We can get this in after that :)

Thanks, @jbschlosser for taking a look. Looks like https://github.com/pytorch/pytorch/pull/63264 was merged recently to fix the docs for `max_poolNd` functions, which looks great - but I had a minor suggestion.

Since, for `return_indices=True`, these functions return tuple/list of tensors, I would ideally not have the return type annotated there (in the PR I linked above, it has been set to `Tensor`). That's the only change that I've done in the recent commit.

Thank you for the patience again!

**Comment by jbschlosser** [comment]
Hey @krshrimali, FYI I'll be out on PTO for the next 2 weeks so this may not get merged until I'm back

**Comment by krshrimali** [comment]
> Hey @krshrimali, FYI I'll be out on PTO for the next 2 weeks so this may not get merged until I'm back

Thanks for the heads up, @jbschlosser! Enjoy the PTO :) No rush with this PR, please take your time.

**Pull request closed without merging**
