### PR TITLE
Install magma from a tarball

### LINKED ISSUE #140538: Update build jobs that use `magma-cuda` to use the new package
cc @seemethere @malfet @osalpekar @atalman

### PR DESCRIPTION
**Pull request by afrittoli**
Magma is built for specific CUDA versions and stored in the ossci-linux bucket. Install it from there rather than the deprecated conda package.

There are two places where magma is installed today:
- `install_conda.sh`: extract the magma package in the same exact location where conda would install it, using a dedicated `install_magma_conda.sh` script. The new script is included in the relevant Dockerfiles where CUDA+magma is needed
- `install_magma.sh`: this script already uses a tarball. Use the new tarball instead of the tarball from the conda package. The format of the new tarball is compatible with the old one, so changes here are minimal:wq

Fixes #140538
Test PR: https://github.com/pytorch/pytorch/pull/141584

### CODE REVIEW

**Comment by afrittoli** [comment]
@atalman Tested at https://github.com/pytorch/pytorch/pull/141584.
The s390x and onnx failures definitely seem unrelated.
I'm unsure about the [linux-jammy-py3-clang12-executorch](https://github.com/pytorch/pytorch/pull/140417#logs) failure. WDYT?

**Review by atalman — DISMISSED** [review]
lgtm

**Comment by atalman** [comment]
@afrittoli sorry for revert. Will try to reland this tomorrow. Looks like the issue after labnding this PR was caused by CI flakiness, not PR itself

**Review by atalman — APPROVED** [review]
lgtm

**Pull request closed without merging**
