### PR TITLE
[DCP] Returns a copy of sd in copy sd

### PR DESCRIPTION
**Pull request by LucasLLC**
I found that returning the copy is actually useful in situations where you might do something like:

```
ret = _copy_state_dict(obj, cache)
ret.update(some_other_values)
```

and would like `cache` not to change structure from `ret.update(some_other_values)`.  Open to some notes here, not returning a copy might force the user to do some additional copies for this case.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### CODE REVIEW

**Comment by wconstab** [comment]
im kinda confused. the existing function name is _copy_state_dict, so presumably it was already making a copy.  But it wasn't returning it?  Is there actually a new copy happening? or just that now the user gets a handle to the copy more conveniently

**Comment by LucasLLC** [comment]
So the function (originally and now) does a 'copy by value'. Meaning for every value in the dictionary, we replace that value with a copy or call `Tensor.copy`. Unfortunately this can't be done for the outermost dictionary, which is also returned. This is what the original `_offload_to_cpu` method was doing.

Without returning, the user would have to do something like:
```
_copy_state_dict(obj, cache)
copy = copy.copy(cache)
```
We also don't want to avoid replacing values in place because we want to make use of the data types in the cache (since it is persistent). 

Let me know if that makes sense

**Review by wz337 — APPROVED** [review]
LGTM

**Comment by fegin** [comment]
The meaning of this API is a little bit confusing to me now. So there will be 2 state_dict that are copied from the `state_dict`?

**Comment by LucasLLC** [comment]
> The meaning of this API is a little bit confusing to me now. So there will be 2 state_dict that are copied from the `state_dict`?

This method behaves exactly as `offload_state_dict_to_cpu` did.

**Comment by fegin** [comment]
`offload_state_dict_to_cpu` only accepts one state_dict argument.

**Comment by LucasLLC** [comment]
> offload_state_dict_to_cpu

Doesn't it include `cpu_offload_state_dict` ?

**Pull request closed without merging**
