### PR TITLE
[Environment Variable][4/N] Use thread-safe getenv functions

### PR DESCRIPTION
**Pull request by cyyever**
Follows #137328

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Otherwise this one seems ok

**Comment by cyyever** [comment]
@ezyang This PR should be OK, can help me reland?

**Pull request closed without merging**
