### PR TITLE
return_and_correct_aliasing: massage some schemas to work with torchgen

### PR DESCRIPTION
**Pull request by bdhirsh**
This issue is that `str(torch.ops.aten.conv2d.default._schema)` does not return the same schema that is in native_functions.yaml ([link](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/native_functions.yaml#L1654)).

Torchscript appears to change the default arg string `int[2] strides=1` to `int[2] strides=[1, 1]`. If you try to parse that with torchgen, torchgen is unhappy (it tries to split arguments on comma, but now we have a comma inside of the default argument).

Fixing the issue directly in torchgen was a bit more painful, so I opted just to undo the transformation that torchscript made: convert `=[1, 1]` back into `=1`.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #105236
* #104974
* #104483
* #106406
* #109023
* #108654
* #108656
* #109248
* #109024
* __->__ #108897
* #107917
* #106404

### CODE REVIEW

**Comment by ezyang** [comment]
From the desc I'm not really sure what this PR does

**Review by ezyang — APPROVED** [review]

**Comment by bdhirsh** [comment]
Sorry, meant to update and forgot to after pushing. Just updated the description!

**Comment by bdhirsh** [comment]
Darn, there's another issue with `return_and_correct_aliasing()` when I turn it on in AOTAutograd, specific to XLA: https://github.com/pytorch/pytorch/actions/runs/6126071394/job/16629801927

I can either update this PR directly to fix it, or put it in another PR. The issue is that this util tries to slam storages into wrapper subclass tensors, but `aten::set_.source_Storage_storage_offset` isn't happy when the device of the storage reports as XLA (because in general, messing with XLA storages is a bit weird).

I'm thinking of supressing this error message (because we know better, and the tensor we're updating isn't a real XLA tensor, but a shell/wrapper subclass tensor that holds an XLA tensor).

**Pull request closed without merging**
