### PR TITLE
Set python random seed in workers

### PR DESCRIPTION
**Pull request by achalddave**
A common task for each data loader worker is to compute random crops and flips on images. These operations are implemented using python's `random` module (e.g. [`RandomResizedCrop`](https://github.com/pytorch/vision/blob/a42f9d995cd000b51755c2cb40e8154c5b693825/torchvision/transforms/transforms.py#L494)). If we only set the torch seed, then threads compute different random augmentations across runs, even if `random.seed` and `torch.manual_seed` are set in the main thread.

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by achalddave** [comment]
My bad, I didn't realize random wasn't import'ed in this file. Fixed.

**Comment by soumith** [comment]
thanks Achal!

**Pull request merged**
