### PR TITLE
Add values backward support for sparse CSR, CSC, BSR, and BSC tensors

### LINKED ISSUE #107286: Sparse compressed tensor values autograd support is not implemented
## Issue description

As in the title.

## Code example

```python
>>> x = torch.tensor([[10, 1], [2, 3]], dtype=torch.float64).to_sparse_csr().requires_grad_(True)
>>> torch.autograd.gradcheck(torch.Tensor.values, x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "torch/autograd/gradcheck.py", line 2051, in gradcheck
    return _gradcheck_helper(**args)
  File "torch/autograd/gradcheck.py", line 2080, in _gradcheck_helper
    _gradcheck_real_imag(
  File "torch/autograd/gradcheck.py", line 1482, in _gradcheck_real_imag
    gradcheck_fn(
  File "torch/autograd/gradcheck.py", line 1617, in _slow_gradcheck
    analytical = _check_analytical_jacobian_attributes(
  File "torch/autograd/gradcheck.py", line 768, in _check_analytical_jacobian_attributes
    vjps1 = _compute_analytical_jacobian_rows(vjp_fn, output.clone())
  File "torch/autograd/gradcheck.py", line 884, in _compute_analytical_jacobian_rows
    grad_inputs = vjp_fn(grad_out_base)
  File "torch/autograd/gradcheck.py", line 759, in vjp_fn
    return torch.autograd.grad(
  File "torch/autograd/__init__.py", line 394, in grad
    result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: indices expected sparse coordinate tensor layout but got SparseCsr
```

The expected behavior is no exception with return value True.

The exception message above is explained by
https://github.com/pytorch/pytorch/blob/ddba7a5a55aafa012b8b4ad5aaf64375296e805b/tools/autograd/derivatives.yaml#L1876-L1881
that defines why the sparse CSR related code path leads to calling sparse-COO-tensor-specific code (`indices`).

## System Info

- PyTorch version: main

cc @alexsamardzic @nikitaved @cpuhrsch @amjames @bhosmer @ezyang @albanD @zou3519 @gqchen @soulitzer @Lezcano @Varal7

### PR DESCRIPTION
**Pull request by pearu**
Fixes https://github.com/pytorch/pytorch/issues/107286

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #107903
* __->__ #115586

cc @alexsamardzic @nikitaved @cpuhrsch @amjames @bhosmer @jcaip @ezyang @albanD @zou3519 @gqchen @soulitzer @Lezcano @Varal7

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]

**Comment by pearu** [comment]
@albanD this is a follow-up to your https://github.com/pytorch/pytorch/pull/107903#discussion_r1422844090, please review.

**Comment by pearu** [comment]
The lintrunner failure is not related to the changes in this PR.

**Review by albanD — APPROVED** [review]
SGTM Thanks!

**Pull request closed without merging**
