### PR TITLE
[quant][fx][graphmode][be] Use is_qat instead of model.training as a flag for qat

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70009
* #69959
* #69879
* __->__ #69878
* #69877
* #69875
* #69864

Summary:
But we'll still verify that model.training is True when user call prepare_qat API.
Relaxing this condition might also mean that we change the api for methods in fuser_method_mapping,
with additional flag for qat (currently we just have different fusions for training/eval), I don't think
this is P0, we could revisit if there is a need in the future

Test Plan:
```
python test/test_quantization.py TestQuantizeFx
```

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D33080988](https://our.internmc.facebook.com/intern/diff/D33080988)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33080988).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33080988).

**Review by supriyar — APPROVED** [review]
This looks good, although I think we should not have the restriction of the model being in `train`/`eval` mode when using our APIs.

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33080988).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33080988).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33080988).

**Comment by jerryzh168** [comment]
> This looks good, although I think we should not have the restriction of the model being in `train`/`eval` mode when using our APIs.

this is a refactor so we don't change functionality yet, will enable this later after the refactor

**Pull request closed without merging**
