### PR TITLE
Add Autocast support to MatMult thourgh explicit cast

### PR DESCRIPTION
**Pull request by thiagocrepaldi**
Fixes external issue https://github.com/microsoft/onnx-converters-private/issues/157

### CODE REVIEW

**Comment by BowenBao** [comment]
Have you tried adding `onnx::MatMul` to https://github.com/pytorch/pytorch/blob/b04f86363fce9828b066ee516e78912691129b3f/torch/csrc/jit/passes/onnx/scalar_type_analysis.cpp#L45 ?

**Comment by thiagocrepaldi** [comment]
I am trying to create a unit test, but cannot repro the original issue

```python
import io
import torch

a_fp32= torch.randn(3, 5).cpu().float()
b_fp32= torch.randn(5, 4).cpu().float()

class Mult(torch.nn.Module):
    def forward(self, a, b):
        return a @ b

f = io.BytesIO()
with torch.autocast("cpu", enabled=True):
    model = Mult()
    torch.onnx.export(model,
                      (a_fp32, b_fp32.float()),
                      f,
                      input_names=["a", "b"],
                      output_names=["c"],
                      opset_version=17,
                      verbose=True)
```

The script above is traced by JIT with a cast on the b_fp32 already (all the way up to `graph, out = torch._C._create_graph_by_tracing(`), so the fix on ONNX exporter is not exercised.

@BowenBao Any ideas?

**Comment by thiagocrepaldi** [comment]
> Have you tried adding `onnx::MatMul` to
> 
> https://github.com/pytorch/pytorch/blob/b04f86363fce9828b066ee516e78912691129b3f/torch/csrc/jit/passes/onnx/scalar_type_analysis.cpp#L45
> 
> ?

Yes, I have added `onnx::MatMul` to the list. The graph did have both input as `Half` (without a cast) and output also as `Half`, which is nice. but then ORT gradient graph builder crashed with

`RuntimeError: /onnxruntime/orttraining/orttraining/core/graph/gradient_builder_base.h:122 onnxruntime::training::ArgDef onnxruntime::training::GradientBuilderBase::O(size_t, bool) const i < node_->OutputDefs().size() was false.`

I didn't understand what exactly what this means, seems there was a mismatch in the number of expected outputs, maybe?

**Comment by BowenBao** [comment]
Depends on where the code lives. If it is atenlib's responsibility, it's the new style, e.g. like a decorator on each function. If it lives in exporter, I'd prefer pass style to be more manageable. But either way, neither of the changes we are making to TS exporter can be reused for `dynamo_export`. I'm leaning towards updating the pass since they are all in one place :).

I'm not sure about the unittest. Based on your description, it seems JIT tracing has capabilities of inserting cast nodes, so in the real model, the crux is to break that capability. Maybe you'd need a repro where arguments types are not immediately obvious? Is jit.script involved in the model?

**Comment by thiagocrepaldi** [comment]
> Depends on where the code lives. If it is atenlib's responsibility, it's the new style, e.g. like a decorator on each function. If it lives in exporter, I'd prefer pass style to be more manageable. But either way, neither of the changes we are making to TS exporter can be reused for `dynamo_export`. I'm leaning towards updating the pass since they are all in one place :).
> 
> I'm not sure about the unittest. Based on your description, it seems JIT tracing has capabilities of inserting cast nodes, so in the real model, the crux is to break that capability. Maybe you'd need a repro where arguments types are not immediately obvious? Is jit.script involved in the model?

This kind of down cast should be the aten lib responsibility. The MatMul implementor must leverage the onnx spec and must know that the ONNX spec does not allow inputs with different types, and therefore, the matmul implementation should handle type mismatch. This is a local solution to a local problem.

The exporter should not need to have a pass to fix a misbehavior on manually curated list of ops. That strategy spreads the operator implementation throughout different files and layers, making the code too coupled and hard to debug. Just by looking the operator code, one cannot conclude it supports or not the different types, which will seem like an operator bug.

Although the code is not reusable as is, even because it would have to be rewritten as 1) decorator 2) leveraging onnx script, it shows the idea on how to cast an op in python for a specific op, without having to resource to a global pass in c++.

After refactoring, it would be similar to [_op_with_optional_float_cast](https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset9.py#L1298-L1348), but maybe as a decorator or a help that wraps all inputs of the aten lib op


Anyway, I have changed the PR to use scalar type analysis for now

**Review by BowenBao — APPROVED** [review]
nit: would be nice to have repro.

**Comment by BowenBao** [comment]
It feels natural perhaps for atenlib to handle the implicit casting logic since it's part of aten. While exporter for autocast and others (e.g. apex). It's essentially bug on autocast and co, or the graph tracing part for it, if cast nodes are not inserted when they should.

cc @justinchuby for atenlib and type promotion discussion.

**Comment by justinchuby** [comment]
> It feels natural perhaps for atenlib to handle the implicit casting logic since it's part of aten. While exporter/tracer for autocast and others (e.g. apex). It's essentially bug on autocast and co, or the graph tracing part for it, if cast nodes are not inserted when they should.
> 
> cc @justinchuby for atenlib and type promotion discussion.

Thanks, I am down for a discussion. There are a few thoughts I can share

**Pull request closed without merging**
