### PR TITLE
Update Dockerfile

### LINKED ISSUE #80212: Docker build fails with `no cmake or cmake3 with version >= 3.13.0 found"`
### 🐛 Describe the bug

Hi, I the docker build failed on a fresh clone on my machine today:
```sh
$ git clone --recursive https://github.com/pytorch/pytorch
$ cd pytorch
$ DOCKER_BUILDKIT=1 docker build .                                                                                                                                                        1 ↵
[+] Building 146.3s (20/24)
 => [internal] load build definition from Dockerfile                                                                                                                                       0.1s
 => => transferring dockerfile: 2.98kB                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                          0.1s
 => => transferring context: 5.65kB                                                                                                                                                        0.0s
 => resolve image config for docker.io/docker/dockerfile:experimental                                                                                                                      1.6s
 => docker-image://docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5                                                        0.9s
 => => resolve docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5                                                            0.0s
 => => sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5 1.69kB / 1.69kB                                                                                             0.0s
 => => sha256:3c244c0c6fc9d6aa3ddb73af4264b3a23597523ac553294218c13735a2c6cf79 528B / 528B                                                                                                 0.0s
 => => sha256:b587adb6abfd8d6c87b1f649c2e924d53f148ae1c7f0ceaaded70b27b44dccb5 1.21kB / 1.21kB                                                                                             0.0s
 => => sha256:d7f0373ffb1d5ac3477b10ab7f91cba7c5df586c72e7e4a12649024efdc0d531 9.64MB / 9.64MB                                                                                             0.4s
 => => extracting sha256:d7f0373ffb1d5ac3477b10ab7f91cba7c5df586c72e7e4a12649024efdc0d531                                                                                                  0.3s
 => [internal] load metadata for docker.io/library/ubuntu:18.04                                                                                                                            0.0s
 => [dev-base 1/4] FROM docker.io/library/ubuntu:18.04                                                                                                                                     0.0s
 => [internal] load build context                                                                                                                                                         27.6s
 => => transferring context: 2.58GB                                                                                                                                                       27.4s
 => [dev-base 2/4] RUN --mount=type=cache,id=apt-dev,target=/var/cache/apt     apt-get update && apt-get install -y --no-install-recommends         build-essential         ca-certifica  36.0s
 => [official 2/4] RUN --mount=type=cache,id=apt-final,target=/var/cache/apt     apt-get update && apt-get install -y --no-install-recommends         ca-certificates         libjpeg-de  18.7s
 => [dev-base 3/4] RUN /usr/sbin/update-ccache-symlinks                                                                                                                                    0.4s
 => [dev-base 4/4] RUN mkdir /opt/ccache && ccache --set-config=cache_dir=/opt/ccache                                                                                                      0.6s
 => [submodule-update 1/3] WORKDIR /opt/pytorch                                                                                                                                            0.1s
 => [conda 1/1] RUN curl -fsSL -v -o ~/miniconda.sh -O  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  &&     chmod +x ~/miniconda.sh &&     ~/miniconda.sh -b -  55.0s
 => [submodule-update 2/3] COPY . .                                                                                                                                                       28.3s
 => [submodule-update 3/3] RUN git submodule update --init --recursive --jobs 0                                                                                                            1.1s
 => [build 1/4] WORKDIR /opt/pytorch                                                                                                                                                       0.1s
 => CANCELED [conda-installs 1/2] RUN /opt/conda/bin/conda install -c "pytorch-nightly" -c "nvidia" -y python=3.8 pytorch torchvision torchtext "cudatoolkit=11.3" &&     /opt/conda/bin  51.1s
 => [build 2/4] COPY --from=conda /opt/conda /opt/conda                                                                                                                                    8.3s
 => [build 3/4] COPY --from=submodule-update /opt/pytorch /opt/pytorch                                                                                                                    29.6s
 => ERROR [build 4/4] RUN --mount=type=cache,target=/opt/ccache     TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX 8.0" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$  1.1s
------
 > [build 4/4] RUN --mount=type=cache,target=/opt/ccache     TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX 8.0" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"     python setup.py install:
#23 1.039 Building wheel torch-1.13.0a0+git3afc802
#23 1.039 Traceback (most recent call last):
#23 1.039   File "setup.py", line 317, in <module>
#23 1.039     cmake = CMake()
#23 1.039   File "/opt/pytorch/tools/setup_helpers/cmake.py", line 116, in __init__
#23 1.039     self._cmake_command = CMake._get_cmake_command()
#23 1.039   File "/opt/pytorch/tools/setup_helpers/cmake.py", line 145, in _get_cmake_command
#23 1.039     raise RuntimeError("no cmake or cmake3 with version >= 3.13.0 found")
#23 1.039 RuntimeError: no cmake or cmake3 with version >= 3.13.0 found
------
executor failed running [/bin/sh -c TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX 8.0" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"     python setup.py install]: exit code: 1
```

### Versions

$ python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 12.1.0
Clang version: 13.0.1
CMake version: version 3.23.2
Libc version: glibc-2.35

Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0] (64-bit runtime)
Python platform: Linux-5.18.6-arch1-1-x86_64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: 11.7.64
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 960M
Nvidia driver version: 515.48.07
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.4.0
/usr/lib/libcudnn_adv_infer.so.8.4.0
/usr/lib/libcudnn_adv_train.so.8.4.0
/usr/lib/libcudnn_cnn_infer.so.8.4.0
/usr/lib/libcudnn_cnn_train.so.8.4.0
/usr/lib/libcudnn_ops_infer.so.8.4.0
/usr/lib/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.11.0
[pip3] torchvision==0.12.0a0+1665451
[conda] Could not collect

cc @malfet @seemethere

### PR DESCRIPTION
**Pull request by malfet**
Install cmake as part of conda install (as system one is too old)
Install other packages from requirements as well

Fixes https://github.com/pytorch/pytorch/issues/80212

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Comment by HeGaoYuan** [comment]
@malfet 
why do you close this PR?
I also experienced this problem.

**Comment by malfet** [comment]
> why do you close this PR?
> 
> I also experienced this problem.
> 
Not sure I understand what you mean. This PR was closed as it were committed in trunk.

**Comment by HeGaoYuan** [comment]
> > why do you close this PR?
> > I also experienced this problem.
> 
> Not sure I understand what you mean. This PR was closed as it was committed in trunk, see [b35c033](https://github.com/pytorch/pytorch/commit/b35c033c919f8175c79a6b58d7a80674cbc22525)

Thanks for your reply. 
I misunderstood it. 
I thought this commit wasn't merged successfully because I thought when a PR is merged successfully it will the icon "Merged".

截屏2022-08-16 上午11 20 56

But this PR has the icon "Closed".

截屏2022-08-16 上午11 26 44

**Pull request closed without merging**
