### PR TITLE
[FSDP2] Added `mesh` arg to `fsdp_pre_all_gather`

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #120256
* __->__ #123953
* #122908
* #119302

This PR adds a `mesh: DeviceMesh` argument to `fsdp_pre_all_gather()` so that the extension can know over which mesh the all-gather is happening. This can be useful in recovering the post-all-gather tensor size in the `fsdp_post_all_gather()` (e.g. for `NF4Tensor`).

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### CODE REVIEW

**Comment by awgu** [comment]
@weifengpy I was thinking that it would be better to include the `mesh` as an arg to the `fsdp_pre_all_gather` and then subclasses can save the `mesh.size()` if needed in the metadata.

The reason is that the call-site for the `fsdp_pre_all_gather` knows which mesh it would be calling all-gather over, whereas the call-site for `fsdp_post_all_gather` does not. 

This would matter only for the case of `reshard_after_forward: int`, where we could be all-gathering over a different mesh in backward. We do not support `reshard_after_forward: int` with the extensions yet (and doing so correctly for the user might be kind of tricky), so this is not a big deal either way.

**Comment by weifengpy** [comment]
> @weifengpy I was thinking that it would be better to include the `mesh` as an arg to the `fsdp_pre_all_gather` and then subclasses can save the `mesh.size()` if needed in the metadata.
> 
> The reason is that the call-site for the `fsdp_pre_all_gather` knows which mesh it would be calling all-gather over, whereas the call-site for `fsdp_post_all_gather` does not.
> 
> This would matter only for the case of `reshard_after_forward: int`, where we could be all-gathering over a different mesh in backward. We do not support `reshard_after_forward: int` with the extensions yet (and doing so correctly for the user might be kind of tricky), so this is not a big deal either way.

nice. I am good with passing `mesh` during `fsdp_pre_all_gather`. will give it a try on NF4Tensor.
BTW: I see this in draft mode. are you planning more changes?

**Comment by awgu** [comment]
@weifengpy sorry, no more planned changes -- I just wanted to check with you first 😅

**Comment by weifengpy** [comment]
> @weifengpy sorry, no more planned changes -- I just wanted to check with you first 😅

all good. all good

**Review by Skylion007 — APPROVED** [review]

**Review by wanchaol — APPROVED** [review]

**Pull request closed without merging**
