### PR TITLE
[inductor] switch AotCodeCompiler to new cpp_builder. (take 2)

### PR DESCRIPTION
**Pull request by xuhancn**
We have tried to switch `AotCodeCompiler` to new cpp_builder in the PR: https://github.com/pytorch/pytorch/pull/130127 
But, it has some compatibility issue to `fb_code`, and it was reverted: https://github.com/pytorch/pytorch/pull/130127#issuecomment-2226313943

I re-created this PR and add some debug code to help fix compatibility issue: https://github.com/pytorch/pytorch/pull/131304/commits/20035b1407bf3a7f81993da6ab599a49ff62cd30

@desertfire could please help me to import this PR to `fb_code`? 

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by henrylhtsang** [comment]
Hi @xuhancn, I will be helping with fixing fbcode tests for this PR.

One thing I noticed so far: Should we add `cuda_passthough_args = []` after https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cpp_builder.py#L1101

That seems to be the logic here https://github.com/pytorch/pytorch/blob/main/torch/_inductor/codecache.py#L1735

**Comment by xuhancn** [comment]
> Hi @xuhancn, I will be helping with fixing fbcode tests for this PR.
> 
> One thing I noticed so far: Should we add `cuda_passthough_args = []` after https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cpp_builder.py#L1101
> 
> That seems to be the logic here https://github.com/pytorch/pytorch/blob/main/torch/_inductor/codecache.py#L1735

Hi @henrylhtsang ,
I tried to simulate by: https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cpp_builder.py#L955-L957
You can re-create a new PR by your-self, and try to switch `AotCodeCompiler`.

**Comment by henrylhtsang** [comment]
> > Hi @xuhancn, I will be helping with fixing fbcode tests for this PR.
> > One thing I noticed so far: Should we add `cuda_passthough_args = []` after https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cpp_builder.py#L1101
> > That seems to be the logic here https://github.com/pytorch/pytorch/blob/main/torch/_inductor/codecache.py#L1735
> 
> Hi @henrylhtsang , I tried to simulate it by: https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cpp_builder.py#L955-L957 You can re-create a new PR by your-self, and try to switch `AotCodeCompiler`.

Hi, one problem is that passthough flags is not None when cuda and fbcode is used 
https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cpp_builder.py#L1056

Are there any problems with adding that `cuda_passthough_args = []`? Can we try it? I seem to have good success with adding that line for the fbcode tests.

**Comment by xuhancn** [comment]
Hi @henrylhtsang , could you please try https://github.com/pytorch/pytorch/pull/132594?

**Comment by xuhancn** [comment]
@henrylhtsang you can also reference to my design doc: https://github.com/pytorch/pytorch/issues/124245

**Comment by henrylhtsang** [comment]
@xuhancn just to be clear, should I test https://github.com/pytorch/pytorch/pull/132594 and this pull request together?

**Comment by xuhancn** [comment]
> @xuhancn just to be clear, should I test #132594 and this pull request together?

Cherry-pick into this PR or create a new one, it is up to you.

**Comment by henrylhtsang** [comment]
@xuhancn I will circle back in a few hours. I think after this fix it might be good to go.

**Comment by henrylhtsang** [comment]
@xuhancn just to update a bit more:

* the fix helps with a few tests
* a few remaining tests are still failing. Problem seems to be due to using relative path instead of complete path, and it seems to be related to using re environment (probably related to fbcode_aot_cpu_re flag?!?)

Let me know if you have more ideas. Otherwise will continue to investigate.

**Comment by henrylhtsang** [comment]
@xuhancn

Looks like `output_o` used to be absolute path, but now is relative path. 

Before:
`os.path.splitext(input_path)[0] + ".o"` -> absolute path 

After: 
`output_o = object_builder.get_target_file_path()` -> relative path

**Comment by chenyang78** [comment]
> @xuhancn
> 
> Looks like `output_o` used to be absolute path, but now is relative path.
> 
> Before: `os.path.splitext(input_path)[0] + ".o"` -> absolute path
> 
> After: `output_o = object_builder.get_target_file_path()` -> relative path

Thanks for the investigation. So, looks like we might want to keep using the absolution path for fbcode, e.g. differentiating fbcode from oss in ```object_builder.get_target_file_path()```?

**Comment by xuhancn** [comment]
> @xuhancn
> 
> Looks like `output_o` used to be absolute path, but now is relative path.
> 
> Before: `os.path.splitext(input_path)[0] + ".o"` -> absolute path
> 
> After: `output_o = object_builder.get_target_file_path()` -> relative path

Hi @henrylhtsang could you please try to add some logical to fix the target path here: https://github.com/pytorch/pytorch/pull/131304#issuecomment-2269899695 
CC: @chenyang78

**Comment by henrylhtsang** [comment]
> > @xuhancn
> > Looks like `output_o` used to be absolute path, but now is relative path.
> > Before: `os.path.splitext(input_path)[0] + ".o"` -> absolute path
> > After: `output_o = object_builder.get_target_file_path()` -> relative path
> 
> Hi @henrylhtsang could you please try to add some logical to fix the target path here: [#131304 (comment)](https://github.com/pytorch/pytorch/pull/131304#issuecomment-2269899695) CC: @chenyang78

https://github.com/pytorch/pytorch/pull/132708 seems to fix the test those errors. Do you know a way to incorporate them?

**Comment by xuhancn** [comment]
Add https://github.com/pytorch/pytorch/pull/132708/files 'specified_so_name' as parameter to https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cpp_builder.py#L1152-L1173 ? Try to this way.

**Comment by xuhancn** [comment]
https://github.com/pytorch/pytorch/pull/131304#issuecomment-2270010340 for `output_o`.
https://github.com/pytorch/pytorch/pull/131304#issuecomment-2270042213 for `output_so`

**Comment by henrylhtsang** [comment]
@xuhancn sorry I am not getting it. Can you elaborate a bit more for both cases?

**Comment by xuhancn** [comment]
Hi @henrylhtsang 

For `output_o`, it is `rel`/`abs` path issue. https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cpp_builder.py#L1251-L1257 Adjust the control logical by `fb_code`, `self._aot_mode`, and `self._use_absolute_path`.

For `output_so`, in https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cpp_builder.py#L1152-L1173, add a parameter `specified_so_name: str = ""`. and example:

```python
def get_name_and_dir_from_output_file_path(
    file_path: str, specified_so_name: str = ""
) -> Tuple[str, str]:

    if len(specified_so_name) > 0
        file_path = config.aot_inductor.output_path

    name_and_ext = os.path.basename(file_path)
    name, ext = os.path.splitext(name_and_ext)
    dir = os.path.dirname(file_path)

    return name, dir
```

**Comment by xuhancn** [comment]
> Hi @henrylhtsang
> 
> For `output_o`, it is `rel`/`abs` path issue. https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cpp_builder.py#L1251-L1257 Adjust the control logical by `fb_code`, `self._aot_mode`, and `self._use_absolute_path`.
> 
> For `output_so`, in https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cpp_builder.py#L1152-L1173, add a parameter `specified_so_name: str = ""`. and example:
> 
> ```python
> def get_name_and_dir_from_output_file_path(
>     file_path: str, specified_so_name: str = ""
> ) -> Tuple[str, str]:
> 
>     if len(specified_so_name) > 0
>         file_path = config.aot_inductor.output_path
> 
>     name_and_ext = os.path.basename(file_path)
>     name, ext = os.path.splitext(name_and_ext)
>     dir = os.path.dirname(file_path)
> 
>     return name, dir
> ```

Additional, for control `abs`/`rel` only impact `output_o`but not `output_so`, please check `self._compile_only`, ref: https://github.com/pytorch/pytorch/blob/main/torch/_inductor/cpp_builder.py#L1239-L1244

**Comment by henrylhtsang** [comment]
@xuhancn update:

it seems like we can **always** add `output_so = os.path.splitext(input_path)[0] + ".so"` and `output_o = os.path.splitext(input_path)[0] + ".o"`

For example:
```
log.debug("aot linkage command: %s", link_cmd)
output_so = os.path.splitext(input_path)[0] + ".so"
if fbcode_aot_cpu_re:
    compile_file([output_o, consts_o], output_so, link_cmd.split())
    os.chmod(output_so, 0o755)
else:
    run_command_and_check(link_cmd)
```

As a matter of fact, we do that for consts_o already. Let me know if this works.

I am waiting for test signals now and will circle back in a few hours.

**Comment by xuhancn** [comment]
> @xuhancn update:
> 
> it seems like we can **always** add `output_so = os.path.splitext(input_path)[0] + ".so"` and `output_o = os.path.splitext(input_path)[0] + ".o"`
> 
> For example:
> 
> ```
> log.debug("aot linkage command: %s", link_cmd)
> output_so = os.path.splitext(input_path)[0] + ".so"
> if fbcode_aot_cpu_re:
>     compile_file([output_o, consts_o], output_so, link_cmd.split())
>     os.chmod(output_so, 0o755)
> else:
>     run_command_and_check(link_cmd)
> ```
> 
> As a matter of fact, we do that for consts_o already. Let me know if this works.
> 
> I am waiting for test signals now and will circle back in a few hours.

It is also a solution, if we never plan to support AoT for Windows.

**Comment by henrylhtsang** [comment]
> > @xuhancn update:
> > it seems like we can **always** add `output_so = os.path.splitext(input_path)[0] + ".so"` and `output_o = os.path.splitext(input_path)[0] + ".o"`
> > For example:
> > ```
> > log.debug("aot linkage command: %s", link_cmd)
> > output_so = os.path.splitext(input_path)[0] + ".so"
> > if fbcode_aot_cpu_re:
> >     compile_file([output_o, consts_o], output_so, link_cmd.split())
> >     os.chmod(output_so, 0o755)
> > else:
> >     run_command_and_check(link_cmd)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As a matter of fact, we do that for consts_o already. Let me know if this works.
> > I am waiting for test signals now and will circle back in a few hours.
> 
> It is also a solution, if we never plan to support AoT for Windows.

Well I guess we can move it inside the `if fbcode_aot_cpu_re:`

**Comment by xuhancn** [comment]
> > > @xuhancn update:
> > > it seems like we can **always** add `output_so = os.path.splitext(input_path)[0] + ".so"` and `output_o = os.path.splitext(input_path)[0] + ".o"`
> > > For example:
> > > ```
> > > log.debug("aot linkage command: %s", link_cmd)
> > > output_so = os.path.splitext(input_path)[0] + ".so"
> > > if fbcode_aot_cpu_re:
> > >     compile_file([output_o, consts_o], output_so, link_cmd.split())
> > >     os.chmod(output_so, 0o755)
> > > else:
> > >     run_command_and_check(link_cmd)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > As a matter of fact, we do that for consts_o already. Let me know if this works.
> > > I am waiting for test signals now and will circle back in a few hours.
> > 
> > 
> > It is also a solution, if we never plan to support AoT for Windows.
> 
> Well I guess we can move it inside the `if fbcode_aot_cpu_re:`

Sounds good, it's only impact `fbcode_aot_cpu_re`.

**Comment by henrylhtsang** [comment]
Internal signals LGTM ([D60773405](https://www.internalfb.com/diff/D60773405))

I think it is good to land as long as https://github.com/pytorch/pytorch/pull/132594 and the relative path thing is patched. cc @desertfire @chenyang78

**Comment by xuhancn** [comment]
@henrylhtsang so, could you please help on merge these PRs?

**Comment by henrylhtsang** [comment]
> @henrylhtsang so, could you please help on merge these PRs?

Yes. Can you add the commits to this PR?

**Comment by xuhancn** [comment]
Added comments and request review: https://github.com/pytorch/pytorch/pull/132594 @henrylhtsang , @desertfire

**Comment by henrylhtsang** [comment]
@xuhancn is that a good reason to split it into a few PRs? It will add a few more cycles to merging this PR.

**Comment by xuhancn** [comment]
> @xuhancn is that a good reason to split it into a few PRs? It will add a few more cycles to merging this PR.

My suggest is you recreate a new PR and land it.

**Comment by henrylhtsang** [comment]
> > @xuhancn is that a good reason to split it into a few PRs? It will add a few more cycles to merging this PR.
> 
> My suggest is you re-create a new PR and land it. @henrylhtsang

sure I can do that

**Comment by xuhancn** [comment]
close by https://github.com/pytorch/pytorch/pull/132766

**Pull request closed without merging**
