### PR TITLE
Fixes test/run_test.py for standalone runs

### PR DESCRIPTION
**Pull request by thiagocrepaldi**
When running[1] this script locally, outside the context of CI scripts, two errors may arise:

1) `from tools.stats.export_test_times import TEST_TIMES_FILE` is not
   found when the runtime environment also has PyTorch Text installed.
   That happens because PytorchText also has a `tools` namespace,
   confusing the search path
   (aka https://github.com/pytorch/text/tree/main/tools/__init__.py)

2) `NameError: name 'ShardedTest' is not defined` happens because
   `ShardedTest` is only available if the import from previous bullet
    succeeds.

This PR fixes 1) by prepending (instead of appending) `REPO_ROOT` to the system PATH variable. It fixes 2) by including `from __future__ import annotations` to the import list.

[1] `python test/run_test.py --dynamo --exclude-jit-executor --exclude-distributed-tests --exclude test_autograd test_jit test_proxy_tensor test_quantization test_public_bindings test_dataloader test_reductions test_namedtensor test_namedtuple_return_api profiler/test_profiler profiler/test_profiler_tree test_overrides test_python_dispatch test_fx test_package test_legacy_vmap export/test_db functorch/test_dims functorch/test_aotdispatch --verbose --include export/test_pass_infra` is an example on how to run this script locally and repro the issue.

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM, though instead of "from __future__ import annotations" one can simply quote type that could not be resolved yet

**Comment by thiagocrepaldi** [comment]
@malfet It seems a bunch of pipelines are failing with `ModuleNotFoundError: No module named 'torch.version'`.
AFAIK this seems unrelated to the change. Would be `@pytorchbot merge -f " Unrelated failures: ModuleNotFoundError: No module named 'torch.version'"` be applicable here?

**Comment by kit1980** [comment]
> `ModuleNotFoundError: No module named 'torch.version'`. AFAIK this seems unrelated to the change. Would be `@pytorchbot merge -f " Unrelated failures: ModuleNotFoundError: No module named 'torch.version'"` be applicable here?

I suspect `sys.path.insert(0, str(REPO_ROOT))` may cause that.

**Comment by thiagocrepaldi** [comment]
> > `ModuleNotFoundError: No module named 'torch.version'`. AFAIK this seems unrelated to the change. Would be `@pytorchbot merge -f " Unrelated failures: ModuleNotFoundError: No module named 'torch.version'"` be applicable here?
> 
> I suspect `sys.path.insert(0, str(REPO_ROOT))` may cause that.

I considered that, but it does work in our servers. Python does not use $PATH to find python packages, right?

**Pull request closed without merging**
