### PR TITLE
Fix accuracy minifier

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #87606

Signed-off-by: Edward Z. Yang <ezyangfb.com>

cc @jansel @lezcano @fdrocha @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305

### CODE REVIEW

**Review by anjali411 — APPROVED** [review]

**Review by anijain2305 — APPROVED** [review]

**Review by albanD — APPROVED** [review]
Can we just have a lint for that?

**Review by soumith — APPROVED** [review]

**Comment by ezyang** [comment]
@albanD sure, should be simple enough

**Review by malfet — APPROVED** [review]
Should we enable lint on dynamo?

**Comment by ezyang** [comment]
will do in follow up, enabling lint is a better way to do it than grep but I see more failures...

**Comment by desertfire** [comment]
There is also direct reference to `torchinductor` in the same file. Can we fix those?

**Comment by anijain2305** [comment]
> done.
> 
> @anijain2305 It's also not good that we don't have any testing coverage for this, we really should have it for the minifier

@williamwen42 is planning to look at it this week.

**Pull request closed without merging**
