### PR TITLE
Fix comparison of integer expressions of different signedness

### PR DESCRIPTION
**Pull request by cyyever**
Fixes these warnings 
```
src/aten/src/ATen/native/cuda/ForeachReduceOp.cu:190:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
```

### CODE REVIEW

**Comment by tringwald** [comment]
Thank you for this PR! I think there are some more lines that cause these warnings, like all uses of `auto i` in e.g. line 228.

**Comment by cyyever** [comment]
@tringwald Fixed.

**Comment by tringwald** [comment]
There are some more `auto` uses in line 268, 275, 308 and 315. It compiles without warnings for me after changing those too.

**Review by tringwald — APPROVED** [review]

**Review by Skylion007 — APPROVED** [review]

**Pull request closed without merging**
