### PR TITLE
[BC-breaking] conv1d & conv3d

### PR DESCRIPTION
**Pull request by khushi-411**
As discussed here: https://github.com/pytorch/pytorch/pull/113885#discussion_r1404573875

cc: @lezcano 

#### TODO
- [x] add error inputs after #114589 is merged

cc @ezyang @gchanan @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
Are these paths currently working? If so, we should not restrict them for no good reason.

**Review by lezcano — APPROVED** [review]
Sure, let's align conv1d and conv3d with conv2d

**Comment by khushi-411** [comment]
Thanks for pointing it out, @lezcano! It was informative :-)

**Pull request closed without merging**
