### PR TITLE
Reduce number of samples in {svd,pca}_lowrank OpInfos

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #127199

We don't need to generate so many samples for these very expensive ops.

### CODE REVIEW

**Review by peterbell10 — APPROVED** [review]

**Review by zou3519 — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but it is failing MacOS trunk job https://hud.pytorch.org/pytorch/pytorch/commit/18a3f781e6382e2222d7c30c18136267407f9953#25619618844' -c ignoredsignals

Here is the failed test when I run it locally:

```
pytest -v test/functorch/test_ops.py -k test_grad_svd_lowrank_cpu_float32
=================================================================== test session starts ====================================================================
platform darwin -- Python 3.9.17, pytest-7.4.0, pluggy-1.0.0 -- /Users/huydo/miniconda3/envs/py3.9/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/huydo/Storage/mine/pytorch/.hypothesis/examples')
rootdir: /Users/huydo/Storage/mine/pytorch
configfile: pytest.ini
plugins: xdoctest-1.1.0, cpp-2.3.0, resume-0.0.1, rerunfailures-10.3, flakefinder-1.1.0, hypothesis-6.56.4, cov-4.1.0, profiling-1.7.0, xdist-3.3.1, repeat-0.9.1, anyio-3.6.2
collected 9990 items / 9989 deselected / 1 selected
Running 1 items in this shard

test/functorch/test_ops.py::TestOperatorsCPU::test_grad_svd_lowrank_cpu_float32 FAILED [3.3305s]                                                     [100%]

========================================================================= FAILURES =========================================================================
____________________________________________________ TestOperatorsCPU.test_grad_svd_lowrank_cpu_float32 ____________________________________________________
Traceback (most recent call last):
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 971, in test_wrapper
    return test(*args, **kwargs)
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_cuda.py", line 198, in wrapped
    return f(*args, **kwargs)
  File "/Users/huydo/Storage/mine/pytorch/test/functorch/test_ops.py", line 541, in test_grad
    self.assertEqual(result_noncontig, expected)
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 3622, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 6 (16.7%)
Greatest absolute difference: 1.8835067749023438e-05 at index (2, 0) (up to 1e-05 allowed)
Greatest relative difference: 6.159073564049322e-06 at index (2, 0) (up to 1.3e-06 allowed)

The failure occurred for item [0]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2730, in wrapper
    method(*args, **kwargs)
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 419, in instantiated_test
    result = test(self, **param_kwargs)
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_cuda.py", line 198, in wrapped
    return f(*args, **kwargs)
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 1028, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 1028, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1364, in wrapper
    fn(*args, **kwargs)
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 977, in test_wrapper
    raise Exception(  # noqa: TRY002
Exception: Caused by sample input at index 9: SampleInput(input=Tensor[size=(3, 2), device="cpu", dtype=torch.float32], args=TensorList[Tensor[size=(4, 2), device="cpu", dtype=torch.float32]], kwargs={'q': '2', 'M': 'Tensor[size=(3, 4), device="cpu", dtype=torch.float32]'}, broadcasts_input=False, name='')

To execute this test, run the following from the base repo dir:
     python test/functorch/test_ops.py -k TestOperatorsCPU.test_grad_svd_lowrank_cpu_float32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------
/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/_functorch/deprecated.py:70: FutureWarning: We've integrated functorch into PyTorch. As the final step of the integration, `functorch.grad` is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use `torch.func.grad` instead; see the PyTorch 2.0 release notes and/or the `torch.func` migration guide for more details https://pytorch.org/docs/main/func.migrating.html
  warn_deprecated("grad")
================================================================= short test summary info ==================================================================
FAILED [3.3305s] test/functorch/test_ops.py::TestOperatorsCPU::test_grad_svd_lowrank_cpu_float32 - Exception: Caused by sample input at index 9: SampleInput(input=Tensor[size=(3, 2), device="cpu", dtype=torch.float32], args=TensorList[Tensor[size=(4,...
=========================================================== 1 failed, 9989 deselected in 15.33s ============================================================
```

**Pull request closed without merging**
