### PR TITLE
[ROCm] devtoolset / GCC11 upgrade on manylinux images - 1b of 2 (docker images)

### PR DESCRIPTION
**Pull request by pruthvistony**
Upgrade gcc version from 9 to 11 on ROCm manylinux images. 

Needed for #141423 since almalinux8-based manylinux2_28 images for ROCm (#140681) installs gcc-toolset-9, which installs [gcc 9.2.1](https://pkgs.org/download/gcc-toolset-9-gcc-c++). However, PyTorch CMakeLists.txt enforces a [minimum gcc version of 9.3](https://github.com/pytorch/pytorch/blob/5318bf8baf19fecda365c185cd81196e3cfb08e3/CMakeLists.txt#L61).

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

### CODE REVIEW

**Review by jeffdaily — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
The manylinux docker image build with [LDFLAGS set to point to gcc-toolset-11](https://github.com/pytorch/pytorch/pull/141609/commits/22d1987221c18d36af805457734e30dcbbe28dc1) succeeded for [6.2.4](https://github.com/pytorch/pytorch/actions/runs/12059283037/job/33627618617) and [6.1](https://github.com/pytorch/pytorch/actions/runs/12059283037/job/33627617901).

The wheel builds using the above images also succeeded in [PR 141423](https://github.com/pytorch/pytorch/pull/141423/commits/8ae9e23fb206ef732d6c391a10ec7b5bed5f25c9): eg. https://github.com/pytorch/pytorch/actions/runs/12068334721/job/33653245377
```
--   Shared LD flags       : -Wl,-rpath=/opt/rh/gcc-toolset-11/root/usr/lib64 -Wl,-rpath=/opt/rh/gcc-toolset-11/root/usr/lib -Wl,--no-as-needed -rdynamic
--   Static LD flags       :
--   Module LD flags       : -Wl,-rpath=/opt/rh/gcc-toolset-11/root/usr/lib64 -Wl,-rpath=/opt/rh/gcc-toolset-11/root/usr/lib
```

However, the wheel test jobs failed because they do not have AWS access set up, so we need to **blind merge** this PR to enable these changes to reflect in the dockerhub `pytorch/manylinux2_28-builder:rocm6.2.4-main` docker images, and hope that the wheel test jobs succeed.

**Comment by jithunnair-amd** [comment]
Just re-testing out two PyTorch build jobs that failed on the last round of CI runs (a bit surprising because the changes in this PR should not impact regular CI builds, but just want to be sure there's no negative impact of this PR on ROCm CI builds)...

**Comment by jithunnair-amd** [comment]
> Just re-testing out two PyTorch build jobs that failed (in [pull](https://github.com/pytorch/pytorch/actions/runs/12059283059/job/33627618547) and [rocm](https://github.com/pytorch/pytorch/actions/runs/12059283794/job/33627623091) workflows) on the last round of CI runs (a bit surprising because the changes in this PR should not impact regular CI builds, but just want to be sure there's no negative impact of this PR on ROCm CI builds)...

PyTorch builds succeeded on retry: [pull](https://github.com/pytorch/pytorch/actions/runs/12059283059/job/33668800567) and [rocm](https://github.com/pytorch/pytorch/actions/runs/12059283794/job/33668789617)

**Pull request closed without merging**
