### PR TITLE
Fix silu test for flexattention

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #126641
* #126446
* #126615

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Review by drisspg — APPROVED** [review]
lol I had tunnel vision, great fix

**Comment by DanilBaibak** [comment]
Hi @Chillee! Sorry, I need to revert your PR because it broke the internal build. Here you can find more information about the issue - [D57619238](https://www.internalfb.com/diff/D57619238).

**Pull request closed without merging**
