### PR TITLE
Migrate `asin` and `asin_` from the TH to Aten (CUDA)

### LINKED ISSUE #24537: Migrate `asin` and `asin_` from the TH to Aten (CUDA)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #28696 Remove definitions of acosh and asinh from TH
* #28527 Migrate `sinh` and `sinh_` from the TH to Aten (CUDA)
* **#28482 Migrate `asin` and `asin_` from the TH to Aten (CUDA)**
* #28237 Migrate `sin` and `sin_` from the TH to Aten (CUDA)

Benchmark (Debian Buster, CUDA 9.2, Quadro P400, turbo off, Release, gcc 7.4):

```python
import timeit

for n, t in [(10_000, 20000),
             (100_000, 20000)]:
    for dtype in ('torch.half', 'torch.float', 'torch.double'):
        print(f'torch.asin(a) a.numel() == {n} for {t} times {dtype}')
        print(timeit.timeit(f'torch.asin(a); torch.cuda.synchronize()', setup=f'import torch; a=torch.arange({n}, dtype={dtype}, device="cuda")', number=t))
```

Before:

```
torch.asin(a) a.numel() == 10000 for 20000 times torch.half
0.37638233399957244
torch.asin(a) a.numel() == 10000 for 20000 times torch.float
0.377967665000142
torch.asin(a) a.numel() == 10000 for 20000 times torch.double
0.9213513669992608
torch.asin(a) a.numel() == 100000 for 20000 times torch.half
0.8473557480001546
torch.asin(a) a.numel() == 100000 for 20000 times torch.float
1.0340258509995692
torch.asin(a) a.numel() == 100000 for 20000 times torch.double
6.045749833000627
```

After:

```
torch.asin(a) a.numel() == 10000 for 20000 times torch.half
0.37552232399957575
torch.asin(a) a.numel() == 10000 for 20000 times torch.float
0.3796842550000292
torch.asin(a) a.numel() == 10000 for 20000 times torch.double
0.9202746920000209
torch.asin(a) a.numel() == 100000 for 20000 times torch.half
0.8276844379997783
torch.asin(a) a.numel() == 100000 for 20000 times torch.float
1.014272968000114
torch.asin(a) a.numel() == 100000 for 20000 times torch.double
6.039313418999882
```

Close #24537

Differential Revision: [D18089074](https://our.internmc.facebook.com/intern/diff/D18089074)

### CODE REVIEW

**Comment by vishwakftw** [comment]
It seems like there's a regression, any idea why?

**Comment by xuhdev** [comment]
> It seems like there's a regression, any idea why?

It's likely some sort of hardware unstability. It's pretty hard to get consistent CUDA benchmarks (as it turns out, even power source would affect the outcome). I can try to run the benchmark again at another time, but the CUDA build is really time consuming.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by xuhdev** [comment]
I added more stabilization to the benchmarking environment and now they are producing very close results. See the updated benchmarking result.

**Comment by vishwakftw** [comment]
Thanks @xuhdev!

**Pull request closed without merging**
