### PR TITLE
Revert "Attempt to fix windows build"

### PR DESCRIPTION
**Pull request by xuhdev**
This reverts commit 0c222555ce82f2caf497e2fea2f2844bdd67e9e5.

### CODE REVIEW

**Comment by xuhdev** [comment]
Looks like #25450 is no longer effective regarding VS2017. I would rather restore to the state before #25450 and then find a way to make #35117 (continuation of #33252) compatible with this VS2017 issue. Does it sound good?

**Comment by ezyang** [comment]
That seems fine, but how did you notice this was no longer working? Master windows seems to be green now.

**Comment by xuhdev** [comment]
@ezyang I probably have worded it incorrectly. I meant the "fix" is no longer **necessary**, because removing the fix still leads to a successful VS2017 build. Not triggering the compiler bug, the fix, which is really a hack, shouldn't be there.

**Review by jamesr66a — APPROVED** [review]

**Comment by xuhdev** [comment]
The second commit (CI tweak) has now been reverted.

**Comment by xuhdev** [comment]
Wait on #35593

**Comment by xuhdev** [comment]
All tests have passed now

**Pull request closed without merging**
