### PR TITLE
#26426 fixed

### PR DESCRIPTION
**Pull request by drnikolaev**
This is the fix for reverted #26426 
@houseroad @bddppq @soumith

### CODE REVIEW

**Review by houseroad — COMMENTED** [review]
I will create another PR to test the code, if it is okay, i will merge this one.

**Comment by drnikolaev** [comment]
or just try #28715

**Comment by houseroad** [comment]
Some CI won't be trigger here, so I have to explicitly trigger it.

**Comment by houseroad** [comment]
The build still fails. Check https://github.com/pytorch/pytorch/pull/28720

**Comment by houseroad** [comment]
https://circleci.com/gh/pytorch/pytorch/3365058?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by drnikolaev** [comment]
@houseroad I didn't know that you keep TRT5 permanently installed on your CI boxes. It's incompatible with TRT6. Is this OK to return TRT6 installer back to my PR? Just installer, no CI integration.

**Comment by houseroad** [comment]
@drnikolaev do you mean here: https://github.com/pytorch/pytorch/blob/master/.jenkins/caffe2/build.sh#L133

If so, feel free to update it.

**Comment by drnikolaev** [comment]
@houseroad Yes but let's keep it simple. New parser needs TRT6, so why bother? If no TRT6 installed, turn the feature off and issue a warning.

**Comment by drnikolaev** [comment]
@houseroad I tried to clone your branch here: #28737 but still can't see `caffe2_py2_cuda9_0_cudnn7_ubuntu16_04` target. Other ones look good.

**Comment by houseroad** [comment]
Seems good. Let me do one more check.

**Pull request closed without merging**
