### PR TITLE
[threaded pg] adapt test_pointwise_ops.py

### PR DESCRIPTION
**Pull request by XilunWu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #90713
* #90712
* #90595

Differential Revision: [D42153660](https://our.internmc.facebook.com/intern/diff/D42153660)

### CODE REVIEW

**Comment by XilunWu** [comment]
@XilunWu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D42153660).

**Review by wanchaol — APPROVED** [review]
lgtm, please ensure CI passes before landing.

**Comment by XilunWu** [comment]
@XilunWu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D42153660).

**Pull request closed without merging**
