### PR TITLE
fix kl_div for negative targets

### LINKED ISSUE #65466: `torch.nn.functional.kl_div` fails gradgradcheck if the target requires a gradient
## 🐛 Bug

`torch.nn.functional.kl_div` fails gradgradcheck if the target requires a gradient.

## To Reproduce

```python
import torch
from torch.autograd import gradgradcheck
from torch.nn.functional import softmax, log_softmax, kl_div

torch.manual_seed(0)
# input should be log probabilities
input = log_softmax(torch.randn(3, dtype=torch.float64, requires_grad=True))
# target should be probabilities
target = softmax(torch.randn_like(input, requires_grad=True))

gradgradcheck(kl_div, inputs=(input, target))
```

```
torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 1,
numerical:tensor([[-0.1344,  0.0000,  0.0000],
        [ 0.0000, -0.1344,  0.0000],
        [ 0.0000,  0.0000, -0.1344]], dtype=torch.float64)
analytical:tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
```

The error only shows up, if the `target` requires a gradient.

## Additional context

- As far as I tried this is not a recent regression. The behavior is the same for `torch==1.8.1`.
- This was detected while adding an `OpInfo` for `kl_div` in #65469.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @jbschlosser @walterddr

### LINKED ISSUE #69230: `torch.nn.functional.kl_div` silently ignores wrong inputs
## 🐛 Bug

With `log_target=False` (default), `target` should be non-negative. The current implementation simply substitutes `0` for the loss in case it encounters a negative `target`:

https://github.com/pytorch/pytorch/blob/fbaa19a6fa6c7d07ecd74e5ebf3c5d0fc77ecc51/aten/src/ATen/native/Loss.cpp#L117

## To Reproduce

```python
import torch
from torch.nn.functional import kl_div

input = torch.rand(()).log()
target = torch.tensor(-1, dtype=input.dtype)

print(kl_div(input, target))
```
```
tensor(0.)
```

## Expected behavior

This is problematic for two reasons:

  1. It is mathematically wrong, since the equation (in particular `target * log(target)`) is undefined for negative targets.
  2. It most likely hides a bug in the user code.

Returning `tensor(nan)` for negative targets would resolve both issues.

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

### PR DESCRIPTION
**Pull request by pmeier**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #65681
* #68419
* __->__ #69212
* #67079
* #67023
* #67022
* #69211

cc @albanD @mruberry @jbschlosser @walterddr

### CODE REVIEW

**Comment by Lezcano** [comment]
@jbschlosser, what do we want to do with this PR and the next one?

**Comment by pmeier** [comment]
@nikitaved wanted to take care of them

**Comment by Lezcano** [comment]
My point is, do we want to have these functionsand their derivatives implemented via TI or as composite functions?

**Comment by jbschlosser** [comment]
@Lezcano remind me again the idea behind this PR? I don't see an associated issue and it's been a while

**Comment by Lezcano** [comment]
So there's two points this PR and the next one address.
One, they optimise the `kl_div` overall (see the new implementation vs the older one). Two, the more important one, to fix i

**Comment by Lezcano** [comment]
@jbschlosser edited, I mistakenly sent the message before finishing writing it :)

**Comment by jbschlosser** [comment]
Also, how do these two PRs interact with #79007?

**Comment by Lezcano** [comment]
Your comment is completely right. And the current implementation does:
```python
  auto output = at::where(target > 0, output_pos, zeros);
```
so it returns zeros for negative targets (while calling a number of unnecessary extra kernels). This PR fixes this.

This PR also makes the backward of `kl_div` differentiable and correct, so it would supersede https://github.com/pytorch/pytorch/pull/79007

**Comment by nikitaved** [comment]
The intersection is only in the gradgrad support, essentially. If having composite backward is fine, then these PRs should in theory be all-around differentiable.

**Comment by Lezcano** [comment]
This PR just implements the backward without TI, making it implicitly differentiable. It did not make any sense to have TI on just one path of the backward, while the forward is implemented via ATen. Even more,
I would argue that we should simply make it composite as https://github.com/pytorch/pytorch/pull/78257, given that the manual implementation of the gradients is not really bringing all that much here.

**Comment by jbschlosser** [comment]
> Even more, I would argue that we should simply make it composite as #78257, given that the manual implementation of the gradients is not really bringing all that much here.

As long as there's no numerical stability issues and perf isn't crippled, I agree with you we should make it composite.

**Comment by jbschlosser** [comment]
Posted on #79007: can we benchmark here to make sure there are no large perf regressions? I'd prefer to go forward with the fully-composite impl here if possible.

**Comment by Lezcano** [comment]
@jbschlosser This one does not make it fully composite, but we could simply remove the backward formulas so that it is fully composite (I'd vouch for that). Philip is on PTO, but I could carve these PRs out of this stack and standalone PR that does so.

**Comment by jbschlosser** [comment]
@Lezcano Sure, that sounds great if you're willing to do it!

**Pull request closed without merging**
