### PR TITLE
[BE]: Fix CMake LTO policy on pytorch

### PR DESCRIPTION
**Pull request by Skylion007**
Not this is a non-functional change since non of our CIs actually build with LTO.

### CODE REVIEW

**Comment by albanD** [comment]
Should we only do this when `ENABLE_LTO` is ON?
Also, I guess you tested this locally? Should we consider building with LTO by default?

**Comment by Skylion007** [comment]
@albanD it only changes the default behavior when `CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON`, which is the canonical way for handling LTO in CMake. See https://cmake.org/cmake/help/latest/variable/CMAKE_INTERPROCEDURAL_OPTIMIZATION.html . It relates to an old behavior where that option used to only work for Intel ICC compilers, but was later expanded for all supported cmake compilers. If CMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF, (which is the default), then it will have no effect. CMake also raises an annoying warning if you enable IPO without setting the CMP policy; this will suppress the warnings.

**Review by albanD — APPROVED** [review]
Ok sounds good to me then!

**Pull request closed without merging**
