### PR TITLE
Binary out-of-place ge.Scalar / eq.Scalar support for NT

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #106785
* #106786
* #107890
* __->__ #107892
* #107891

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]

**Comment by cpuhrsch** [comment]
Nit: You could also add it to the list here: https://pytorch.org/docs/master/nested.html#supported-operations

**Comment by huydhn** [comment]
@pytorchbot drci

(Please ignore this comment, I'm testing Dr.CI)

**Pull request closed without merging**
