### PR TITLE
Enables other devices other than cuda to register lazy_init

### LINKED ISSUE #112369: In the func Tensor.to, how can I make privateuse lazy init
### 🐛 Describe the bug

I’m using privateuse1 to add our backend. My customer find the following code is working in cuda, but not working in my backend.
Use `Tensor.to()` with device message which not has a index, for example "cuda". 
```
import torch
tensor_a  = torch.rand(2).to("cuda")
```
Privateuse1 uses the same logic but fails.
```
import torch
# assumption my device is privateuseone
import torch_privateuseone

tensor_a  = torch.rand(2).to("privateuseone")
```
Above code will fail with `impl->getDevice()` because of the lack of lazy_init for the privateuseone device.
https://github.com/pytorch/pytorch/blob/bbd5b935e49a54578ac88cb23ca962ab896a8c7a/aten/src/ATen/native/TensorConversions.cpp#L210-L216
cuda will init in `THPVariable_to`
https://github.com/pytorch/pytorch/blob/bbd5b935e49a54578ac88cb23ca962ab896a8c7a/tools/autograd/templates/python_variable_methods.cpp#L958-L980

Where I can add `privateuseone_init` is in my own `to_impl` after Dispatcher, but by then it was too late.  Any advice for this case?

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git7bcf7da
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (aarch64)
GCC version: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.23.1
Libc version: glibc-2.27

Python version: 3.8.17 (default, Jul  5 2023, 20:40:03)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-29-generic-aarch64-with-glibc2.26
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              192
On-line CPU(s) list: 0-191
Thread(s) per core:  1
Core(s) per socket:  48
Socket(s):           4
NUMA node(s):        4
Vendor ID:           0x48
Model:               0
Stepping:            0x1
BogoMIPS:            200.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
L3 cache:            24576K
NUMA node0 CPU(s):   0-47
NUMA node1 CPU(s):   48-95
NUMA node2 CPU(s):   96-143
NUMA node3 CPU(s):   144-191
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==2.1.0a0+git7bcf7da
[pip3] torch-npu==2.1.0+gitf565f75
[pip3] torchair==0.1
[pip3] torchvision==0.15.2
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] torch                     2.1.0a0+git7bcf7da          pypi_0    pypi
[conda] torch-npu                 2.1.0+gitf565f75          pypi_0    pypi
[conda] torchair                  0.1                      pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

### PR DESCRIPTION
**Pull request by huihoaan**
Fixes #112369
Referring to Allocator, we can use  `REGISTER_LAZY_INIT` to register the function to lazy init for other device.

At first I was going to use `DispatchStub`, but `DispatchStub` would get an error if it wasn't registered.So I took the way in pr to register function

### CODE REVIEW

**Comment by huihoaan** [comment]
@ezyang  Could you take a look at this pr, and give some advice?

**Comment by ezyang** [comment]
There are some bikeshedding things, if you're willing to change some of the colors

**Comment by jq460494839** [comment]
This bug has affected the test cases of many downstream communities, eg. HuggingFace.
Please review and merge it, thx.
d1b697bfa90d844267af5b203b3c056

**Comment by huihoaan** [comment]
It's a common way, which moving a tensor or medel to device before device's init. For example:
https://github.com/pytorch/examples/blob/c4dc481e686b5cc7d1aad9e3977b91d8ba83bddd/cpp/mnist/mnist.cpp#L119-L129
```
  if (torch::cuda::is_available()) {
    std::cout << "CUDA available! Training on GPU." << std::endl;
    device_type = torch::kCUDA;
  } else {
    std::cout << "Training on CPU." << std::endl;
    device_type = torch::kCPU;
  }
  torch::Device device(device_type);

  Net model;
  model.to(device);
```
If you think that adding a separate file to register `lazy_init` changes is too big, how should I design it? Add it to device_guard? @ezyang

**Pull request closed without merging**
