### PR TITLE
Refactor CUDA's amp cast policy to be generic

### PR DESCRIPTION
**Pull request by guangyey**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #124052
* __->__ #124051
* #124050

# Motivation
This PR intends to create several op lists for different policies:
- `AT_FORALL_LOWER_PRECISION_FP` for policy `lower_precision_fp`
- `AT_FORALL_FP32` for policy `fp32`
- `AT_FORALL_FP32_SET_OPT_DTYPE` for policy `fp32_set_opt_dtype`
- `AT_FORALL_PROMOTE` for policy `promote`.

To make sure the other backend can reuse the policy op list.

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
Consider to add more description in this PR instead of a separate one.

**Review by EikanWang — APPROVED** [review]

**Comment by guangyey** [comment]
> Consider to add more description in this PR instead of a separate one.

Add more description.

**Review by gujinghui — APPROVED** [review]

**Review by albanD — APPROVED** [review]
This makes sense from the c++ side but we should really fix this from python one day: the policy shouldn't be per-device and should be about dtype and how risky you want to be...

**Comment by guangyey** [comment]
> This makes sense from the c++ side but we should really fix this from python one day: the policy shouldn't be per-device and should be about dtype and how risky you want to be...

Good idea!

**Pull request closed without merging**
