### PR TITLE
Enable UFMT on `test/test_datapipe.py`

### PR DESCRIPTION
**Pull request by shink**
Part of: #123062 

Ran lintrunner on:

- `test/test_datapipe.py`

Detail:

```bash
$ lintrunner -a --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```

### CODE REVIEW

**Review by mikaylagawarecki — APPROVED** [review]
Stamping provided CI is happy

**Comment by shink** [comment]
@mikaylagawarecki please take a look, thanks

**Comment by shink** [comment]
@ezyang Please have a look. Thanks so much.

**Pull request closed without merging**
