### PR TITLE
Revert "Revert "Switch to use nested tensor by-default in Transformer…

### PR DESCRIPTION
**Pull request by zrphercule**
…Encoder (#77217)""

This reverts commit 0d6fa91d1ba93b423a31a7811b679a4770470363.

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by zrphercule** [comment]
Not ready yet.

**Review by atalman — APPROVED** [review]
Please add proper PR Summary and make sure it does not break our CI/CD. Please fix lint

**Comment by zrphercule** [comment]
One last test, come on!

**Comment by zrphercule** [comment]
All tests passed!

**Pull request closed without merging**
