### PR TITLE
change rocblas.h -> rocblas/rocblas.h

### LINKED ISSUE #80848: [ROCm] rocblas.h file not found
### 🐛 Describe the bug

pytorch with ROCM fails to build from source
all relevant ROCm/HIP libraries are installed and the hipify script is ran before starting the compilation process

Error:
```
[30/1257] cd /home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.12.0-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip && /usr/bin/cmake -E make_directory /home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.12.0-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=/home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.12.0-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/./torch_hip_generated_AdaptiveAveragePooling.hip.o -P /home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.12.0-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_AdaptiveAveragePooling.hip.o.cmake
FAILED: caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_AdaptiveAveragePooling.hip.o /home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.12.0-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_AdaptiveAveragePooling.hip.o 
cd /home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.12.0-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip && /usr/bin/cmake -E make_directory /home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.12.0-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=/home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.12.0-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/./torch_hip_generated_AdaptiveAveragePooling.hip.o -P /home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.12.0-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_AdaptiveAveragePooling.hip.o.cmake
In file included from /home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.12.0-rocm/aten/src/ATen/native/hip/AdaptiveAveragePooling.hip:8:
/home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.12.0-rocm/aten/src/ATen/hip/HIPContext.h:8:10: fatal error: 'rocblas.h' file not found
#include <rocblas.h>
         ^~~~~~~~~~~
1 error generated when compiling for host.
CMake Error at torch_hip_generated_AdaptiveAveragePooling.hip.o.cmake:146 (message):
  Error generating
  /home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.12.0-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/./torch_hip_generated_AdaptiveAveragePooling.hip.o
```

### Versions

```
PyTorch version: Trying to build 1.12.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: Trying to build

OS: Arch Linux (x86_64)
GCC version: (GCC) 12.1.0
Clang version: 14.0.6
CMake version: version 3.23.2
Libc version: glibc-2.35

Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0] (64-bit runtime)
Python platform: Linux-5.18.7-arch1-1-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] No relevant packages
[conda] No relevant packages
```

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

### PR DESCRIPTION
**Pull request by acxz**
rocblas.h has been deprecated in favor of rocblas/rocblas.h in ROCm 5.2.0

Fixes #80848

### CODE REVIEW

**Comment by cpuhrsch** [comment]
@acxz - Thanks for the submission! You'll need to guard on the version of ROCM for this, since we also distribute kernels for older versions (see the failing test).

**Comment by acxz** [comment]
@cpuhrsch do you have a suggestion on how I would guard? How do I get the ROCm version inside the hipify script?

**Comment by acxz** [comment]
@cpuhrsch all CI passes now, can you provide closure to this PR?

**Review by cpuhrsch — APPROVED** [review]

**Comment by ZainRizvi** [comment]
Hi @cpuhrsch this PR appears to have broken ROCm nightly builds. Can you please take a look?

You can see the failures here:
https://hud.pytorch.org/pytorch/pytorch/commit/983d26963e90590501e5684dc38bda32386f36a4

**Comment by cpuhrsch** [comment]
@acxz - looks like the nightlies weren't switched to ROCm 5.1+?

**Comment by acxz** [comment]
@jithunnair-amd can you comment on this issue? In your migration to ROCm 5.2 were the nightlies updated?

**Comment by jeffdaily** [comment]
This PR needed to be backward-compatible with rocm 5.0.  We must ensure current rocm (5.2) and the prior 2 releases can still build latest pytorch.

**Comment by jeffdaily** [comment]
#82226 isn't the right solution.  We can't just disable building earlier rocm binaries - the original PR was not backward-compatible.

**Comment by jeffdaily** [comment]
The pytorch/builder PR to add rocm 5.2 support (https://github.com/pytorch/builder/pull/1033) was merged only yesterday.  A new PR to update which rocm versions to use for binary builds is coming soon, and it should replace #82226.  For binary builds we keep just latest rocm (5.2) and prior (5.1.1), but 5.1.1 builds will fail until this PR is updated to be backward-compat.

**Comment by acxz** [comment]
> For binary builds we keep just latest rocm (5.2) and prior (5.1.1), but 5.1.1 builds will fail until this PR is updated to be backward-compat.

Isn't the current rocm 5.2.1? Putting the latest rocm at 5.2.1 and the prior at 5.2. In this case I believe this PR is still valid.

**Comment by jeffdaily** [comment]
We don't build for every rocm patch release.  Our CI image us using rocm 5.2.  Our prior CI image was 5.1.1.  Some rocm patch releases do not affect any component exercised by rocm, so building for them only creates unnecessary churn.

**Comment by jeffdaily** [comment]
#82258 should fix the binary builds.  CC @ZainRizvi @cpuhrsch

**Pull request closed without merging**
