### PR TITLE
forward fix preferred blas backend and windows CI

### PR DESCRIPTION
**Pull request by jeffdaily**
PR #122106 broke windows tests. The feature should have been disabled for Windows but was not disabled correctly.

### CODE REVIEW

**Comment by jeffdaily** [comment]
@clee2000 please add any labels so we can confirm that this fixes Windows tests.

**Comment by jeffdaily** [comment]
@clee2000 I don't see how the failing unit tests have anything to do with this PR's changes.  I hope this forward-fixes as requested.

**Review by clee2000 — APPROVED** [review]
non windows failures are flaky, the windows failure can also be seen on trunk

**Pull request closed without merging**
