### PR TITLE
[CUDNN] Remove defunct cuDNN V8 API build flag

### PR DESCRIPTION
**Pull request by eqy**
The flag basically does nothing following #95722

Let's see if the quantization tests break

CC @malfet @atalmanagement

cc @csarofeen @ptrblck @xwang233 @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by eqy** [comment]
TODO: investigate if maxwell failures are due to no int8.

**Comment by eqy** [comment]
int8 issue forwarded to cuDNN, as it is surfacing even in recent generations...

**Comment by eqy** [comment]
Note: requires cuDNN >= 9.1 for maxpooling fix

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but it is failing ROCm jobs in trunk https://hud.pytorch.org/pytorch/pytorch/commit/ee4cafa098ede2d9546016223cbc1a522ea3630a' -c nosignal

I will add `ciflow/rocm` to run the jobs on your PR.

**Pull request closed without merging**
