### PR TITLE
torch::deploy unity and its demo

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #67134

This diff demos torch::deploy unity which builds the model, the dependencies and the runtime as a unity!

The end user only need to use the build_unity rule to replace the python_binary rule to define the python application. Under the hood, we build the python application (an xar file), build the torch deploy runtime, and then embed the python application (the xar file) into the torch deploy runtime.

When starting the torch::deploy runtime, the xar will be written to the filesystem and extracted. We put the extracted path to python sys.path so all the model files and all the python dependencies can be found!

As a demo, the model here is just a simple python program using numpy and scipy. But  theoretically, it can be as complex as we want.

I'll check how bento_kernel works. Maybe we can learn from bento_kernel to simplify things a bit.

Differential Revision: [D31816526](https://our.internmc.facebook.com/intern/diff/D31816526/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D31816526/)!

### CODE REVIEW

**Comment by shunting314** [comment]
The  error message for the failed check `linux-xenial-cuda11.3-py3.6-gcc7` looks as follows
```
ERROR 2021-10-29T19:30:13Z: sccache::server: Compilation failed: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "conftest.c:29:1: error: function declaration isn\'t a prototype [-Werror=strict-prototypes]\n main ()\n ^~~~\ncc1: all warnings being treated as errors\n" }
```

Look unrelated to this PR.

**Comment by suo** [comment]
hmm, if you read back in the logs, there are some suspicious lines:
```
CMakeFiles/interactive_embedded_interpreter.dir/interactive_embedded_interpreter.cpp.o: In function `std::__shared_ptr<torch::deploy::PathEnvironment, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<torch::deploy::PathEnvironment>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(std::_Sp_make_shared_tag, std::allocator<torch::deploy::PathEnvironment> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
interactive_embedded_interpreter.cpp:(.text._ZNSt12__shared_ptrIN5torch6deploy15PathEnvironmentELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS2_EJRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEESt19_Sp_make_shared_tagRKT_DpOT0_[_ZNSt12__shared_ptrIN5torch6deploy15PathEnvironmentELN9__gnu_cxx12_Lock_policyE2EEC5ISaIS2_EJRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEESt19_Sp_make_shared_tagRKT_DpOT0_]+0xb0): undefined reference to `vtable for torch::deploy::PathEnvironment'
collect2: error: ld returned 1 exit status
torch/csrc/deploy/CMakeFiles/interactive_embedded_interpreter.dir/build.make:113: recipe for target 'bin/interactive_embedded_interpreter' failed

```

**Comment by shunting314** [comment]
@suo  thanks for pointing out. I was mainly focusing on those error lines rendered as red colors in the log, didn't pay attention to those white colored lines. There are just so many log lines. Good catch! I'll fix that.

**Comment by suo** [comment]
yeah the signal is very hard to interpret…we ahve https://github.com/pytorch/pytorch/issues/65431 to clean it up

**Pull request closed without merging**
