### PR TITLE
Changes in RNNBase and Embedding for compatibility with DataParallel

### PR DESCRIPTION
**Pull request by bmccann**
Fixes for https://github.com/pytorch/pytorch/issues/651 @adamlerer @apaszke

### CODE REVIEW

**Comment by bmccann** [comment]
Failed test_LPPool2d_norm (__main__.TestNN), but doesn't look like something that would come from this PR.

**Comment by apaszke** [comment]
The PR looks good, but it will break all checkpoints. I think you'd also need to add `__setstate__` that will modify the `all_weights` dict to match the new types.

**Review by apaszke — APPROVED** [review]

**Comment by soumith** [comment]
ok, last checks the tests are failing. Here's the log:

```
======================================================================
ERROR: test_RNN_cpu_vs_cudnn_no_dropout (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 30, in wrapper
    return fn(*args, **kwargs)
  File "test_nn.py", line 1165, in test_RNN_cpu_vs_cudnn_no_dropout
    self._test_RNN_cpu_vs_cudnn(0)
  File "test_nn.py", line 1135, in _test_RNN_cpu_vs_cudnn
    False, rnn, input_val, hx_val, rnn.all_weights)
  File "test_nn.py", line 1062, in forward_backward
    x.data.copy_(y.data)
AttributeError: 'str' object has no attribute 'data'

======================================================================
ERROR: test_RNN_cpu_vs_cudnn_with_dropout (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 30, in wrapper
    return fn(*args, **kwargs)
  File "test_nn.py", line 1171, in test_RNN_cpu_vs_cu* Closing connection 0
dnn_with_dropout
    self._test_RNN_cpu_vs_cudnn(1)
  File "test_nn.py", line 1135, in _test_RNN_cpu_vs_cudnn
    False, rnn, input_val, hx_val, rnn.all_weights)
  File "test_nn.py", line 1062, in forward_backward
    x.data.copy_(y.data)
AttributeError: 'str' object has no attribute 'data'
```

**Comment by soumith** [comment]
thanks for fixing this Bryan!

**Pull request merged**
