### PR TITLE
introducing `gather_add`, like `gather`, but with addition for reduction.

### LINKED ISSUE #31913: `index_add_` with multidimensional index
## 🚀 Feature
Allow multidimensional index in `index_add_`

## Motivation
`index_add_`  is similar to `scatter_add_` with the index applied on RHS rather than LHS. Unfortunately, currently `scatter_add_` allows multidimensional index while `index_add_` allows 1D index only.

Allowing multidimensional index can make this function much more useful. For example, if a problem involves some kind of (batch) sorting, one might need to permute another tensor the same way as the sorted tensor. In this case, the 1D `index_add_` becomes useless and explicit advanced indexing will waste time doing copy.

I see a similar issue #30574. This is kind of different compared to that because that is more-or-less an api that converts advanced indexing to proper language, while this is a request of a fused-operation.

## Pitch
Make `index_add_` exactly the same as `scatter_add_`, except that the index is applied on the RHS, like:
```python
self[i][j][k] = src[index[i][j][k]][j][k]  # if dim == 0
self[i][j][k] = src[i][index[i][j][k]][k]  # if dim == 1
self[i][j][k] = src[i][j][index[i][j][k]]  # if dim == 2
```

## Alternatives
The alternative is directly do advanced indexing:
```python
self = src[index, arange(src.size(1))[:,None], arange(src.size(2))]
self = src[arange(len(src))[:,None,None], index, arange(src.size(2))]
self = src[arange(len(src))[:,None,None], arange(src.size(1))[:,None], index]
```
But this creates permuted copy of `src`. In case of `+=`, this would be less efficient.

### PR DESCRIPTION
**Pull request by nikitaved**
`gather_add`, a new method with the same semantics as `scatter_add`, with the indexing taking place on the right hand side. Fixes [#31913](https://github.com/pytorch/pytorch/issues/31913).

### CODE REVIEW

**Comment by nikitaved** [comment]
@ngimel , could you please have a look?

**Comment by nikitaved** [comment]
Hm, jit complaints seem real. I have no idea how to fix them, though...

**Comment by ngimel** [comment]
cc @suo @eellison for jit complaints

**Comment by suo** [comment]
Sorry, I dropped this on the floor. For the JIT stuff it looks like we just need to add a case to some testing code. @nikitaved if we can rebase this PR on master I can propose the necessary changes on this PR

**Comment by nikitaved** [comment]
@suo, no worries, thank you!

The reason to implement this functionality is to resolve the scatter_add backward formula. With @albanD we agreed to leave this PR for now and wait for the extended `gather` reductions similar to what `scatter` has now. What are you thoughts on this one, @ngimel ?

**Pull request closed without merging**
