### PR TITLE
[ONNX] Update ONNX version

### PR DESCRIPTION
**Pull request by titaiwangms**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #84789
* #83186
* __->__ #83201

Why:

ONNX had mismatch checker usage between cpp and python and it's later fixed by https://github.com/onnx/onnx/pull/4386. And since `torch.onnx.export` is using cpp checker for graph-level check with older version of ONNX,this improvement should be added. Also, this version bump enables #83186 

Updated 12/5/2022:
This PR includes ONNX 1.13.0 pre-release (https://github.com/onnx/onnx/tree/rel-1.13.0)

### CODE REVIEW

**Comment by BowenBao** [comment]
>Please advice on Ci failing:
FAILED ../../../../opt/conda/lib/python3.7/site-packages/caffe2/python/onnx/tests/onnx_backend_test.py::OnnxBackendNodeModelTest::test_center_crop_pad_crop_and_pad_cpu(Exception: Don't know how to translate op CenterCropPad) ->Looks like something Pytorch should update? https://github.com/onnx/onnx/issues/2822

Likely due to it being a new test in onnx. Caffe2 is not going to support new onnx features, so you'd need to disable/skip this test in `caffe2/python/onnx/tests/onnx_backend_test.py` in this PR.

**Review by BowenBao — APPROVED** [review]

**Comment by justinchuby** [comment]
Is CI still a problem? If not a gentle reminder to update the pr description

**Comment by AllenTiTaiWang** [comment]
@malfet Could you help import? It's submodule onnx version bump

**Comment by AllenTiTaiWang** [comment]
@malfet Could you take a look? It's a necessary version bump on ONNX. There is a bug fixed that we need to apply (https://github.com/onnx/onnx/pull/4386). BTW, I think the CircleCI build test is blocking again.

**Comment by AllenTiTaiWang** [comment]
@malfet Would you take a look? It's a version bump on ONNX. Thanks!

**Comment by thiagocrepaldi** [comment]
@AllenTiTaiWang do you think it would be possible to start using onnx main branch for our ONNX pipelines? We have opset 18 ops added to ONNX that are not available in any onnx stable release yet

https://github.com/microsoft/onnxruntime/pull/12311 would benefit from that

**Comment by justinchuby** [comment]
@thiagocrepaldi this commit is from main. We pin the commits as submodules in the repo.

**Comment by thiagocrepaldi** [comment]
> @thiagocrepaldi this commit is from main. We pin the commits as submodules in the repo.

yup, my ask was to pin the master branch, not a specific commit to always use the latest operators we add during development

Waiting 4 months to be able to add operators can drag us down

**Comment by justinchuby** [comment]
Even though CI can track onnx main, the submodule still needs to be pinned in the build. I wonder if a periodic job that updates it (like XLA) is possible.

**Comment by AllenTiTaiWang** [comment]
I remember there are Pytorch internal tests and CI tests rely on ONNX, and if we pin with main branch, those tests could fail. (Like some ops not supported by caffe2) But if there is a way that we could pin with main branch without causing these problems, that does come in handy for dev.

**Comment by BowenBao** [comment]
@malfet please help approve. I think it would be more convenient to add `third_party/onnx` into onnx merge rule, what do you think?

**Comment by thiagocrepaldi** [comment]
If not possible to move to master now, please include at least this commit: https://github.com/onnx/onnx/commit/68859d3387b1c25ee0e231316cbf34580852bb85

**Review by thiagocrepaldi — APPROVED** [review]

**Comment by AllenTiTaiWang** [comment]
@BowenBao Shouldn't we by this point have approval to merge this?

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@kit1980 can you please update internal copy of ONNX to the same commit and make sure it does passes CI?

**Comment by kit1980** [comment]
> @kit1980 can you please update internal copy of ONNX to the same commit and make sure it does passes CI?

I see the merge started already. Should we stop it? Or let it finish and revert if internal is broken after import?

**Comment by AllenTiTaiWang** [comment]
> > @kit1980 can you please update internal copy of ONNX to the same commit and make sure it does passes CI?
> 
> I see the merge started already. Should we stop it? Or let it finish and revert if internal is broken after import?

Sorry I canceled it.

**Comment by thiagocrepaldi** [comment]
@kit1980 was there any internal failure?

**Comment by thiagocrepaldi** [comment]
> > @kit1980 was there any internal failure?
> 
> Yes, there are issues, mostly because optimizer stuff now completely removed from onnx, including C++ code. Figuring out how to fix that.

Got it. Depending on which optimization you are talking about (inside `onnx.optimizer`) and where it is consumed (e.g. PyTorch converter for Caffe2 models), these optimizations are already applied by `torch.onnx.export` in one of the JIT passes, so a simple removal of `onnx.optimizer.*` could suffice.

Hope that helps

**Comment by thiagocrepaldi** [comment]
> > @kit1980 was there any internal failure?
> 
> Yes, there are issues, mostly because optimizer stuff now completely removed from onnx, including C++ code. Figuring out how to fix that.

Do you think this PR can make into 1.13 release? IIUC, the branch cut would be done soon (within a week?)

**Comment by kit1980** [comment]
> Do you think this PR can make into 1.13 release? IIUC, the branch cut would be done soon (within a week?)

Realistically no, I don't think this can be merged before 1.13. I have a change in progress, but I need to finish some other things before.

**Comment by thiagocrepaldi** [comment]
> > Do you think this PR can make into 1.13 release? IIUC, the branch cut would be done soon (within a week?)
> 
> Realistically no, I don't think this can be merged before 1.13. I have a change in progress, but I need to finish some other things before.

Hi @kit1980 any update on this? Other PRs are blocked by this PR

**Comment by thiagocrepaldi** [comment]
@titaiwangms even with the current block on this PR, it would be nice to update it to the same commit onnx 1.13.0 RC1 is pointing to.

This way, Meta can make sure their private stuff work with the closest to the release version

**Comment by titaiwangms** [comment]
Moved to https://github.com/pytorch/pytorch/pull/90337

**Comment by thiagocrepaldi** [comment]
https://github.com/pytorch/pytorch/pull/90332 has ONNX 1.13.0, which is newer than this PR

**Pull request closed without merging**
