### PR TITLE
Fix qconv benchmark

### PR DESCRIPTION
**Pull request by dskhudia**
Summary:
Permutes are done inside the module. We don't need them outside.

Setting of scale/zero_point has changed.

Differential Revision: D16712437

### CODE REVIEW

**Review by jianyuh — APPROVED** [review]
LGTM! Wonder why we need to assign scale and zero_point as the `torch.tensor`? I will make a similar change to the qlinear benchmark.

**Comment by jianyuh** [comment]
@dskhudia : BTW, you might consider using ghstack, as this PR is not consistent with the Diff. It combines this PR and https://github.com/pytorch/pytorch/pull/23991.

**Comment by dskhudia** [comment]
It has two commits ... if you look at the second you will only see changes from this PR.

**Comment by jianyuh** [comment]
> It has two commits ... if you look at the second commit, you will only see changes from this PR.

It might be better to have a stack of PRs and there are no duplications between these PRs. Otherwise, the reviewer might comment in the wrong places.

**Pull request closed without merging**
