### PR TITLE
[tools] Remove newline from clang-format reference hashes

### LINKED ISSUE #54790: tools/git-clang-format: The downloaded binary is not what was expected!
`tools/git-clang-format` seems to do a test on hash of the clang-format binary, but if it mismatches it just says "The downloaded binary is not what was expected!" and no instructions how to remediate. I rm -rf'ed .clang-format-bin that might help

### PR DESCRIPTION
**Pull request by SplitInfinity**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#55328 [tools] Remove newline from clang-format reference hashes**

**Summary**
The `clang-format` reference hashes committed in #54737 have newlines at
the end but the locally computed ones do not. This commit removes these
newlines so that the `clang-format` binary verification step doesn't
fail.

**Test Plan**
`./tools/clang_format_all.py`, ran successfully.

**Fixes**
This commit fixes #54790.

Differential Revision: [D27577398](https://our.internmc.facebook.com/intern/diff/D27577398)

### CODE REVIEW

**Comment by samestep** [comment]
Patch to fix the trailing-newlines lint:
```diff
diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
index e20814cec7..52ecfb874e 100644
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -43,7 +43,7 @@ jobs:
           .jenkins/run-shellcheck.sh
       - name: Ensure correct trailing newlines
         run: |
-          (! git grep -Il '' -- . ':(exclude)**/contrib/**' ':(exclude)third_party' ':(exclude)**.expect' | tools/trailing_newlines.py || (echo "The above files do not have correct trailing newlines; please normalize them"; false))
+          (! git grep -Il '' -- . ':(exclude)**/contrib/**' ':(exclude)third_party' ':(exclude)**.expect' ':(exclude)tools/clang_format_hash' | tools/trailing_newlines.py || (echo "The above files do not have correct trailing newlines; please normalize them"; false))
       - name: Ensure no trailing spaces
         run: |
           (! git grep -I -no ' $' -- . ':(exclude)**/contrib/**' ':(exclude)third_party' || (echo "The above files have trailing spaces; please remove them"; false))
```

**Review by samestep — APPROVED** [review]

**Comment by ezyang** [comment]
Why not just strip newlines from the hash files.

**Comment by samestep** [comment]
> Why not just strip newlines from the hash files.

I like that solution too. Either way is fine with me.

**Comment by SplitInfinity** [comment]
> Why not just strip newlines from the hash files.

You mean in code with `strip()` instead of removing them from the files?

**Pull request closed without merging**
