### PR TITLE
Fixes issue with torch._dynamo.assume_constant_result with global functions

### PR DESCRIPTION
**Pull request by matthewfl**
This PR fixes an issue with `torch._dynamo.assume_constant_result` causing global values to be overwritten.
Currently `torch._dynamo.assume_constant_result` saves the constant result into a global variable derived from the name of the function.  This causes that function to be overwritten in the global scope.  This PR checks that the name is unique in the global scope as well, avoiding the issue of overriding the function.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Comment by matthewfl** [comment]
ping @angelayi what is the status on getting this reviewed?

**Review by jansel — APPROVED** [review]

**Comment by matthewfl** [comment]
@jansel I will take care of it

**Pull request closed without merging**
