### PR TITLE
Add backend checks to solve methods (gesv, cholesky_solve)

### LINKED ISSUE #18105: torch.gesv segfaults with mismatched arg devices
## 🐛 Bug

`torch.gesv` segfaults if its arguments are on different devices.

## To Reproduce
```python
import torch

# segfaults :-(
v = torch.randn(1000, 1)
M = torch.randn(1000, 1000).cuda()
solve = torch.gesv(v, M)
```
results in `[1]    14965 segmentation fault (core dumped)  python gesv_bug.py`
## Expected behavior
raise a `RuntimeError` that the types of `v` and `M` didn't match (e.g. `torch.cuda.FloatTensor` vs `torch.FloatTensor`).

## Environment
```
Collecting environment information...
PyTorch version: 1.0.0.dev20190315
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 410.73
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] gpytorch==0.1.1
[pip3] numpy==1.15.4
[pip3] numpydoc==0.8.0
[pip3] torch==1.0.0.dev20190315
[conda] blas                      1.0                         mkl  
[conda] cuda100                   1.0                           0    pytorch
[conda] cuda92                    1.0                           0    pytorch
[conda] gpytorch                  0.1.1                     dev_0    <develop>
[conda] magma-cuda92              2.4.0                         1    pytorch
[conda] mkl                       2018.0.3                      1  
[conda] mkl-include               2019.1                      144  
[conda] mkl-service               1.1.2            py37h90e4bf4_5  
[conda] mkl_fft                   1.0.6            py36h7dd41cf_0  
[conda] mkl_random                1.0.1            py36h4414c95_1  
[conda] mkldnn                    0.14.0                        0    mingfeima
[conda] pytorch-nightly           1.0.0.dev20190315 py3.6_cuda10.0.130_cudnn7.4.2_0    pytorch
```

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:
- Incorporate a simple backend check in the linearSolveCheckInputs function in LinearAlgebraUtils.h

Test plan:
- Add a test to see if this works as expected

Fixes: #18105

### CODE REVIEW

**Comment by vishwakftw** [comment]
Build/test failures are spurious.

**Review by soumith — APPROVED** [review]

**Comment by vishwakftw** [comment]
@soumith is there anything I have to do to help land this?

**Comment by soumith** [comment]
no, it's merged now.

**Comment by vishwakftw** [comment]
Thank you.

**Pull request closed without merging**
