### PR TITLE
[FlexAttention] Fix output layout

### PR DESCRIPTION
**Pull request by drisspg**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #135884
* __->__ #135882

We previously only supported the same v_head dim and + qk_head dim. When allowed for different head-dims I accidently kept the same query strides for the output. This PR fixes this bug as well it ensures that we always produce output in the same stride order as the input query.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Review by Chillee — CHANGES_REQUESTED** [review]
Why are we always returning contiguous strides?

**Review by Chillee — APPROVED** [review]

**Comment by huydhn** [comment]
Confirm that this is fixed in 2.5.0 by running `pytest -v test/inductor/test_flex_attention.py -k test_flex_attention_stride_ordering`

**Pull request closed without merging**
