### PR TITLE
Remove amax return from _scaled_mm

### PR DESCRIPTION
**Pull request by drisspg**
# Summary
The primary reason for the change was lack of current use case and the need to work around an two Inductor issue. 
- Tensor arguments as kwarg only
- multiple outputs from triton templates

If the need for the amax return type arises we can consider either adding it, more likely creating a separate op. 

In principle PyTorch is moving away from ops that bundle lots of functionality into "mega ops". We instead rely upon the compiler to generate appropriate fused kernels.  

### Changes:
- This removes the amax return type from scaled_mm. We have found that the common use case is to return in "high-precision" ( a type with more precision than fp8). This is only relevant when returning in low-precision. 
- We currently still allow for fp8 returns and scaled result.  Perhaps we should also ban this as well...

New signature:
```Python
def meta_scaled_mm(
    self: torch.Tensor,
    mat2: torch.Tensor,
    scale_a: torch.Tensor,
    scale_b: torch.Tensor,
    bias: Optional[torch.Tensor] = None,
    scale_result: Optional[torch.Tensor] = None,
    out_dtype: Optional[torch.dtype] = None,
    use_fast_accum: bool = False,
) -> torch.Tensor:
```

### CODE REVIEW

**Review by vkuzo — APPROVED** [review]
awesome! lg if tests pass

**Comment by vkuzo** [comment]
for my own curiosity, what was the reason for making scales required?

**Comment by drisspg** [comment]
cc @yangsiyu007  on the inductor constraint on scales, not being optional.

That being said, in retrospect I think this makes more sense. I think it makes sense that "scaled_mm" requires the scales = lol since it is pretty rare (modulo testing) that proper use of this function doesnt require scales

**Comment by yangsiyu007** [comment]
Also need to update meta_registrations to reflect the new signature :) But once I made that change, the lowering works. Output: P1417760117 
You can see that for tensor-wise scaling which ran first, AUTOTUNE happened between ATen _scaled_mm and the Triton templated kernels’ configs. And for rowwise scaling next, only Triton configs were tuned.

**Comment by yangsiyu007** [comment]
> for my own curiosity, what was the reason for making scales required?

Inductor doesn't support optional tensor inputs currently; the symptom is that it will check the layout of each input tensor and errors at seeing None (I tried a workaround with giving it an empty TensorBox, but that leads to incorrect codegen because some pass drops the unused nodes). There is a workaround for handling only 1 optional tensor input, which is why we are okay with the optional `bias` (by having two Triton templates, with and without bias). I'd like to work on supporting optional tensor inputs, but since it makes sense for the scales to be non-optional, we thought we'd precede for now.

**Pull request closed without merging**
