### PR TITLE
Move bytecode generation to python

### PR DESCRIPTION
**Pull request by tugsbayasgalan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #71681

This PR moves the bytecode generation logic for mobile from C++ to python. Previously, the upgraders_entry.cpp file would need a reference to methods in `export_module.cpp `and `export_bytecode.cpp`. Therefore, they needed to be linked in the same library to work correctly. This required changing how we use `build_variables.bzl` and broke internal tests due to many different targets using different subset of files list we use in `build_variables.bzl`. Therefore, it is safer if we just move everything into python. To achieve this, we do:
1. Undo changes we introduced in `build_variables.bzl` in https://github.com/pytorch/pytorch/pull/70593 
2. Move the bytecode generation process into python through PyBind. 

Differential Revision: [D33730791](https://our.internmc.facebook.com/intern/diff/D33730791)

### CODE REVIEW

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33730791).

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33730791).

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33730791).

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33730791).

**Review by cccclai — APPROVED** [review]
Thanks!

**Review by gmagogsfm — APPROVED** [review]

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33730791).

**Pull request closed without merging**
