### PR TITLE
[FSDP] Allow to use TorchDispatch with FSDP

### PR DESCRIPTION
**Pull request by fegin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #88014

Add `_no_dispatch_record_stream` to disable TorchDispatch before calling `record_stream()`.

### CODE REVIEW

**Comment by awgu** [comment]
Is this for landing, or is this just for experimentation? I am concerned that memory logs from using this will be inaccurate because memory will be incorrectly freed early without `record_stream()`.

**Review by zhaojuanmao — COMMENTED** [review]
look good to me, will let Andrew or Rohan to accept

**Comment by fegin** [comment]
@awgu `record_stream()` is still called with this PR. What `_no_dispatch_record_stream()` does is to disable TorchDispatch before calling `record_stream()` and reenable it after `record_stream()` is done. So it should be safe for the memory usage.

**Review by awgu — APPROVED** [review]
Thanks for the explanation! I definitely misunderstood.

This looks good to me. Do you know if Core team is planning to add support for `record_stream()` so that this is a temporary fix?

**Comment by fegin** [comment]
> This looks good to me. Do you know if Core team is planning to add support for `record_stream()` so that this is a temporary fix?

Saw a TODO for TorchDispatch to support class block list filter. If this function is implemented, users can just the block list to filter out `record_stream()`. Not sure when that feature will be implemented though.

**Comment by awgu** [comment]
> > This looks good to me. Do you know if Core team is planning to add support for `record_stream()` so that this is a temporary fix?
> 
> Saw a TODO for TorchDispatch to support class block list filter. If this function is implemented, users can just the block list to filter out `record_stream()`. Not sure when that feature will be implemented though.

Sounds good to me!

Also, sorry, I am landing some PRs from my stack, so there may be some rebase conflicts :(

**Pull request closed without merging**
