### PR TITLE
[optim/dynamo] shortcut adagrad with `has_complex`

### PR DESCRIPTION
**Pull request by jon-chuang**
Follow up to https://github.com/pytorch/pytorch/pull/110706, it was missed as depended on another fix

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!
Any test needs updating?

**Comment by jon-chuang** [comment]
There are existing tests for `has_complex`. This PR just makes the has_complex tracing faster.

**Comment by jon-chuang** [comment]
The compile + complex path is currently IIRC untested so that could honestly be improved.

**Pull request closed without merging**
