### PR TITLE
[ONNX] Add flag to enable script tests

### PR DESCRIPTION
**Pull request by BowenBao**
This will allow us to incrementally enable more tests for scripting as we put in fixes. @houseroad @spandantiwari

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 85eb7660:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=85eb7660e4b70245c33f3612ae9dd3f972930009).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4349173) pytorch_macos_10_13_py3_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=91391275) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=91391275))
<details>
<summary>
<code>Jan 27 11:31:04 RuntimeError: test_autograd failed!</code>
</summary>

```
Jan 27 11:31:03 Ran 1047 tests in 319.752s 
Jan 27 11:31:03  
Jan 27 11:31:03 FAILED (errors=1, skipped=13, expected failures=1) 
Jan 27 11:31:03  
Jan 27 11:31:03 Generating XML reports... 
Jan 27 11:31:04 Traceback (most recent call last): 
Jan 27 11:31:04   File "test/run_test.py", line 456, in <module> 
Jan 27 11:31:04     main() 
Jan 27 11:31:04   File "test/run_test.py", line 449, in main 
Jan 27 11:31:04     raise RuntimeError(message) 
Jan 27 11:31:04 RuntimeError: test_autograd failed! 
Jan 27 11:31:04 + cleanup 
Jan 27 11:31:04 + retcode=1 
Jan 27 11:31:04 + set +x 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by houseroad — COMMENTED** [review]
Rebase to let tests pass?

**Review by lara-hdr — APPROVED** [review]
nice! That's going to make testing easier. Thanks!

**Comment by houseroad** [comment]
Failure is unrelated.

**Review by houseroad — APPROVED** [review]
LGTM

**Pull request closed without merging**
