### PR TITLE
[Build] [CMake] [ROCm] find hsa-runtime64 properly

### LINKED ISSUE #44384: Pytorch+rocm 3.7.0: cmake cannot find hsa-runtime64
## 🐛 Bug

Hi,

I'm trying to build Pytorch for rocm from sources following [this page](https://github.com/aieater/rocm_pytorch_informations) and also other sources; however it ends with an error:

```
***** Library versions from cmake find_package *****

CMake Error at /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findhsa-runtime64.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "hsa-runtime64", but CMake did not find one.

  Could not find a package configuration file provided by "hsa-runtime64"
  with any of the following names:

    hsa-runtime64Config.cmake
    hsa-runtime64-config.cmake

  Add the installation prefix of "hsa-runtime64" to CMAKE_PREFIX_PATH or set
  "hsa-runtime64_DIR" to a directory containing one of the above files.  If
  "hsa-runtime64" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /opt/rocm/hip/lib/cmake/hip/hip-config.cmake:124 (find_dependency)
  cmake/public/LoadHIP.cmake:131 (find_package)
  cmake/public/LoadHIP.cmake:170 (find_package_and_print_version)
  cmake/Dependencies.cmake:1154 (include)
  CMakeLists.txt:486 (include)
```

The file that cmake is looking for is under /opt/rocm-3.7.0/lib/cmake/hsa-runtime64/ .
I also tried setting the variable  however setting the environmental variable to CMAKE_MODULE_PATH=/opt/rocm-3.7.0/lib/cmake/hsa-runtime64 , but still no luck.

Any hint?

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Pop!_OS 20.04 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[conda] Could not collect

cc @malfet @seemethere @walterddr @jeffdaily @sunway513

### PR DESCRIPTION
**Pull request by acxz**
Properly Fixes #44384
similar in vein to #42064

### CODE REVIEW

**Comment by acxz** [comment]
@mrshenli @malfet 
It has been a week since this PR is open, can you guys take a quick look at it.
All checks pass and this fixes the Arch Linux build.
Really quick change to review :)
Thanks

**Comment by acxz** [comment]
@mrshenli @malfet
It has been around three weeks, do you guys mind taking a quick look at this? Thanks!

**Comment by malfet** [comment]
@jeffdaily what do you think?

**Comment by jeffdaily** [comment]
Sorry this fell off my radar.  @acxz is this still a problem for arch?  Can you give a status update?  Will this PR also fix #46528?

**Comment by acxz** [comment]
@jeffdaily yep the issue still persists on Arch. (and any system where the *_dir is not specified unless the user manually specifies it as in the linked issue.

This issue won't fix #46528, I might have a hunch on what is causing that issue tho, I'll look at that one once I get some time.

**Comment by jeffdaily** [comment]
@acxz I've got some general arch+rocm questions for you, but I can't find any contact info for you.  Would you send me an email?  Thanks.

**Comment by acxz** [comment]
@jeffdaily sure thing!

**Review by jeffdaily — APPROVED** [review]
Confirmed this PR is needed for arch linux builds.  Does not break ROCm ubuntu CI.  Approved.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
