### PR TITLE
Fix byte ordering issue in from_numpy

### LINKED ISSUE #3671: Creating tensors from numpy arrays with ">f" type yields bogus results
```
y = np.array([[1., 2., 3.],
             [4., 5., 6.]], dtype=">f")
torch.from_numpy(y)
```

Gives

```
1.00000e-41 *
  4.6006  0.0090  2.3049
  4.6007  5.7487  6.8966
[torch.FloatTensor of size 2x3]
```

Which is clearly incorrect. 

Such types are common when using `np.from_file`.

### PR DESCRIPTION
**Pull request by vishwakftw**
Fixes https://github.com/pytorch/pytorch/issues/3671 .

### CODE REVIEW

**Comment by vishwakftw** [comment]
Windows build failure look weird: 
```
TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: double, float, float16, int64, int32, and uint8.
```

**Comment by weiyangfb** [comment]
@vishwakftw is this ready for review?

**Comment by vishwakftw** [comment]
@weiyangfb Yes, it is.

**Comment by vishwakftw** [comment]
Is this good to go?

**Comment by vishwakftw** [comment]
@weiyangfb Is this good to go?

**Review by weiyangfb — APPROVED** [review]
lgtm

**Comment by weiyangfb** [comment]
@colesbury @gchanan Would you like to take a look at this?

**Comment by vishwakftw** [comment]
@weiyangfb is this good to go? Sorry about continuous reminders.

**Review by soumith — APPROVED** [review]

**Comment by vishwakftw** [comment]
Thank you, and no worries.

**Pull request closed without merging**
