### PR TITLE
Update FlexAttention benchmarks

### PR DESCRIPTION
**Pull request by joydddd**
This PR adds more attention variants and builtin FlashAttention support for FlexAttention benchmark. 

Example command: 
```
# training
python benchmarks/transformer/score_mod.py -b 2 -d 64 -mods sliding_window -dtype float16 --calculate-bwd --flash-attn
# inference
python benchmarks/transformer/score_mod.py --kv-cache-size 128  -d 64 -mods causal -dtype float16 --flash-attn --decoding
```
Supported mods: `noop, causal, rel, head_bias, alibi, sliding_window, document_mask, prefix_ml, softcap`

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by joydddd** [comment]
Configs Running: 

```
python benchmarks/transformer/score_mod.py -dtype bfloat16 -s 1024 4096 16384 65536 --kv-cache 256 --backend default fav2 -mods causal -d 64
```

**Comment by joydddd** [comment]
Results (on A6000):

| attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)         |   fwd_cudnn |   bwd_cudnn |   fwd_efficient |   bwd_efficient |   fwd_math |    bwd_math |   fwd_fav2 |    bwd_fav2 |   fwd_compiled |   bwd_compiled |   fwd_cudnn_speedup |   fwd_efficient_speedup |   fwd_math_speedup |   fwd_fav2_speedup |   bwd_cudnn_speedup |   bwd_efficient_speedup |   bwd_math_speedup |   bwd_fav2_speedup |   fwd_mem_bw (TB/s) |   TFlops/s |
|-------------|----------------|-------------------------------|-------------|-------------|-----------------|-----------------|------------|-------------|------------|-------------|----------------|----------------|---------------------|-------------------------|--------------------|--------------------|---------------------|-------------------------|--------------------|--------------------|---------------------|------------|
| causal      | torch.bfloat16 | (64, 16, 1024, 16, 1024, 64)  |    1816.576 |    6654.976 |        1818.624 |        6651.904 |   1820.384 |    6708.224 |   2404.352 |    6558.720 |       1655.808 |       7561.216 |               1.097 |                   1.098 |              1.099 |              1.452 |               0.880 |                   0.880 |              0.887 |              0.867 |               0.324 |    167.305 |
| causal      | torch.bfloat16 | (16, 16, 4096, 16, 4096, 64)  |    5338.112 |   16061.440 |        5373.952 |       16077.824 |   5480.448 |   16054.272 |   5912.576 |   15796.224 |       5588.992 |      19918.049 |               0.955 |                   0.962 |              0.981 |              1.058 |               0.806 |                   0.807 |              0.806 |              0.793 |               0.096 |    198.265 |
| causal      | torch.bfloat16 | (4, 16, 16384, 16, 16384, 64) |   20952.065 |   53027.840 |       21174.273 |       53445.633 |  21451.777 |   53499.905 |  22706.177 |   51565.567 |      20835.327 |      69258.141 |               1.006 |                   1.016 |              1.030 |              1.090 |               0.766 |                   0.772 |              0.772 |              0.745 |               0.026 |    212.735 |
| causal      | torch.bfloat16 | (1, 16, 65536, 16, 65536, 64) |   84051.971 |  202652.679 |       84668.419 |      204838.943 |  85337.090 |  204641.281 |  92965.889 |  201049.088 |      85954.559 |     268552.185 |               0.978 |                   0.985 |              0.993 |              1.082 |               0.755 |                   0.763 |              0.762 |              0.749 |               0.006 |    206.267 |
| causal      | torch.bfloat16 | (512, 16, 1024, 2, 1024, 64)  |   13919.232 |   50247.681 |       13913.088 |       50154.495 |  13904.896 |   50112.511 |  18945.024 |   48956.417 |      13175.808 |      53136.383 |               1.056 |                   1.056 |              1.055 |              1.438 |               0.946 |                   0.944 |              0.943 |              0.921 |               0.183 |    168.202 |
| causal      | torch.bfloat16 | (128, 16, 4096, 2, 4096, 64)  |   43596.802 |  127235.970 |       43979.774 |      127034.370 |  44046.337 |  127283.203 |  47057.919 |  124489.731 |      43286.530 |     160844.803 |               1.007 |                   1.016 |              1.018 |              1.087 |               0.791 |                   0.790 |              0.791 |              0.774 |               0.056 |    204.794 |
| causal      | torch.bfloat16 | (32, 16, 16384, 2, 16384, 64) |  169554.947 |  436160.522 |      171128.830 |      438370.300 | 172437.500 |  441442.291 | 181392.380 |  430043.121 |     167835.648 |     594811.890 |               1.010 |                   1.020 |              1.027 |              1.081 |               0.733 |                   0.737 |              0.742 |              0.723 |               0.014 |    211.274 |
| causal      | torch.bfloat16 | (8, 16, 65536, 2, 65536, 64)  |  705176.575 | 1715139.526 |      709654.541 |     1720862.549 | 711897.949 | 1723471.924 | 778559.509 | 1688278.076 |     725028.870 |    2334186.523 |               0.973 |                   0.979 |              0.982 |              1.074 |               0.735 |                   0.737 |              0.738 |              0.723 |               0.003 |    195.629 |


====================================================FWD Speedups vs. cudnn===================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)        |
|---------|-----------|-------------|----------------|------------------------------|
| Average |     1.010 |             |                |                              |
| Max     |     1.097 | causal      | torch.bfloat16 | (64, 16, 1024, 16, 1024, 64) |
| Min     |     0.955 | causal      | torch.bfloat16 | (16, 16, 4096, 16, 4096, 64) |


====================================================BWD Speedups vs. cudnn===================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)         |
|---------|-----------|-------------|----------------|-------------------------------|
| Average |     0.801 |             |                |                               |
| Max     |     0.946 | causal      | torch.bfloat16 | (512, 16, 1024, 2, 1024, 64)  |
| Min     |     0.733 | causal      | torch.bfloat16 | (32, 16, 16384, 2, 16384, 64) |


==================================================FWD Speedups vs. efficient=================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)        |
|---------|-----------|-------------|----------------|------------------------------|
| Average |     1.016 |             |                |                              |
| Max     |     1.098 | causal      | torch.bfloat16 | (64, 16, 1024, 16, 1024, 64) |
| Min     |     0.962 | causal      | torch.bfloat16 | (16, 16, 4096, 16, 4096, 64) |


==================================================BWD Speedups vs. efficient=================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)         |
|---------|-----------|-------------|----------------|-------------------------------|
| Average |     0.804 |             |                |                               |
| Max     |     0.944 | causal      | torch.bfloat16 | (512, 16, 1024, 2, 1024, 64)  |
| Min     |     0.737 | causal      | torch.bfloat16 | (32, 16, 16384, 2, 16384, 64) |


====================================================FWD Speedups vs. math====================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)        |
|---------|-----------|-------------|----------------|------------------------------|
| Average |     1.023 |             |                |                              |
| Max     |     1.099 | causal      | torch.bfloat16 | (64, 16, 1024, 16, 1024, 64) |
| Min     |     0.981 | causal      | torch.bfloat16 | (16, 16, 4096, 16, 4096, 64) |


====================================================BWD Speedups vs. math====================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)        |
|---------|-----------|-------------|----------------|------------------------------|
| Average |     0.805 |             |                |                              |
| Max     |     0.943 | causal      | torch.bfloat16 | (512, 16, 1024, 2, 1024, 64) |
| Min     |     0.738 | causal      | torch.bfloat16 | (8, 16, 65536, 2, 65536, 64) |


====================================================FWD Speedups vs. fav2====================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)        |
|---------|-----------|-------------|----------------|------------------------------|
| Average |     1.170 |             |                |                              |
| Max     |     1.452 | causal      | torch.bfloat16 | (64, 16, 1024, 16, 1024, 64) |
| Min     |     1.058 | causal      | torch.bfloat16 | (16, 16, 4096, 16, 4096, 64) |


====================================================BWD Speedups vs. fav2====================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)         |
|---------|-----------|-------------|----------------|-------------------------------|
| Average |     0.787 |             |                |                               |
| Max     |     0.921 | causal      | torch.bfloat16 | (512, 16, 1024, 2, 1024, 64)  |
| Min     |     0.723 | causal      | torch.bfloat16 | (32, 16, 16384, 2, 16384, 64) |

**Comment by joydddd** [comment]
A6000 decoding performance:

| attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)     |   fwd_cudnn |   bwd_cudnn |   fwd_efficient |   fwd_math |   fwd_fakv |   fwd_compiled |   bwd_efficient |   fwd_cudnn_speedup |   fwd_efficient_speedup |   fwd_math_speedup |   fwd_fakv_speedup |   fwd_mem_bw (TB/s) |   TFlops/s |
|-------------|----------------|---------------------------|-------------|-------------|-----------------|------------|------------|----------------|-----------------|---------------------|-------------------------|--------------------|--------------------|---------------------|------------|
| causal      | torch.bfloat16 | (64, 16, 1, 16, 1024, 64) |         nan |         nan |         423.936 |   4388.864 |    260.096 |        242.688 |             nan |                 nan |                   1.747 |             18.084 |              1.072 |               1.107 |      1.115 |
| causal      | torch.bfloat16 | (16, 16, 1, 16, 4096, 64) |         nan |         nan |         395.264 |   4644.864 |    258.048 |        206.848 |             nan |                 nan |                   1.911 |             22.455 |              1.248 |               1.298 |      1.308 |
| causal      | torch.bfloat16 | (4, 16, 1, 16, 16384, 64) |         nan |         nan |         893.952 |   5079.040 |    209.920 |        337.920 |             nan |                 nan |                   2.645 |             15.030 |              0.621 |               0.794 |      0.801 |
| causal      | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |         nan |         nan |        3490.816 |   2757.632 |    199.680 |        338.944 |             nan |                 nan |                  10.299 |              8.136 |              0.589 |               0.792 |      0.798 |
| causal      | torch.bfloat16 | (512, 16, 1, 2, 1024, 64) |         nan |         nan |         nan     |  20298.592 |    264.192 |        245.760 |             nan |                 nan |                 nan     |             82.595 |              1.075 |               1.101 |      8.806 |
| causal      | torch.bfloat16 | (128, 16, 1, 2, 4096, 64) |         nan |         nan |         nan     |  20568.064 |    260.096 |        207.872 |                 |                 nan |                 nan     |             98.946 |              1.251 |               1.294 |     10.412 |
| causal      | torch.bfloat16 | (32, 16, 1, 2, 16384, 64) |         nan |         nan |         nan     |  25170.944 |    211.040 |        327.680 |                 |                 nan |                 nan     |             76.816 |              0.644 |               0.820 |      6.605 |
| causal      | torch.bfloat16 | (8, 16, 1, 2, 65536, 64)  |         nan |         nan |         nan     |  25393.152 |    200.704 |        329.728 |                 |                 nan |                 nan     |             77.012 |              0.609 |               0.814 |      6.564 |
| causal      | torch.bfloat16 | (4, 16, 1, 2, 131072, 64) |         nan |         nan |         nan     |  25394.176 |    202.752 |        328.704 |                 |                 nan |                 nan     |             77.255 |              0.617 |               0.817 |      6.584 |


==================================================FWD Speedups vs. efficient=================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)     |
|---------|-----------|-------------|----------------|---------------------------|
| Average |     4.151 |             |                |                           |
| Max     |    10.299 | causal      | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |
| Min     |     1.747 | causal      | torch.bfloat16 | (64, 16, 1, 16, 1024, 64) |


====================================================FWD Speedups vs. math====================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)     |
|---------|-----------|-------------|----------------|---------------------------|
| Average |    52.926 |             |                |                           |
| Max     |    98.946 | causal      | torch.bfloat16 | (128, 16, 1, 2, 4096, 64) |
| Min     |     8.136 | causal      | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |


====================================================FWD Speedups vs. fakv====================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)     |
|---------|-----------|-------------|----------------|---------------------------|
| Average |     0.858 |             |                |                           |
| Max     |     1.251 | causal      | torch.bfloat16 | (128, 16, 1, 2, 4096, 64) |
| Min     |     0.589 | causal      | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |

**Comment by joydddd** [comment]
Decoding Performance on A6000: (after commit `267f460`) 

# Sweep kv seq len for Noop mask

command 
```
python -W ignore::UserWarning: benchmarks/transformer/score_mod.py -dtype bfloat16 -s 1024 4096 16384 65536 131072 --kv-size 256 --backend  math fakv -mods noop -d 64 --throughput --decoding
```

<details>

| attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)     |   fwd_math |   fwd_fakv |   fwd_compiled |   fwd_math_speedup |   fwd_fakv_speedup |   fwd_mem_bw (TB/s) |   TFlops/s |
|-------------|----------------|---------------------------|------------|------------|----------------|--------------------|--------------------|---------------------|------------|
| noop        | torch.bfloat16 | (64, 16, 1, 16, 1024, 64) |   4576.256 |    517.120 |        399.360 |             11.459 |              1.295 |               0.673 |      0.677 |
| noop        | torch.bfloat16 | (16, 16, 1, 16, 4096, 64) |   4882.592 |    519.168 |        398.336 |             12.257 |              1.303 |               0.674 |      0.679 |
| noop        | torch.bfloat16 | (4, 16, 1, 16, 16384, 64) |   5351.424 |    396.288 |        419.840 |             12.746 |              0.944 |               0.639 |      0.644 |
| noop        | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |   2902.016 |    397.312 |        404.480 |              7.175 |              0.982 |               0.664 |      0.669 |
| noop        | torch.bfloat16 | (512, 16, 1, 2, 1024, 64) |  21387.264 |    524.288 |        402.432 |             53.145 |              1.303 |               0.672 |      5.378 |
| noop        | torch.bfloat16 | (128, 16, 1, 2, 4096, 64) |  21696.800 |    522.240 |        398.080 |             54.504 |              1.312 |               0.676 |      5.437 |
| noop        | torch.bfloat16 | (32, 16, 1, 2, 16384, 64) |  26516.479 |    398.208 |        405.504 |             65.391 |              0.982 |               0.662 |      5.337 |
| noop        | torch.bfloat16 | (8, 16, 1, 2, 65536, 64)  |  26771.328 |    397.312 |        403.456 |             66.355 |              0.985 |               0.665 |      5.364 |
| noop        | torch.bfloat16 | (4, 16, 1, 2, 131072, 64) |  26769.119 |    400.384 |        402.432 |             66.518 |              0.995 |               0.667 |      5.378 |


</details>
====================================================FWD Speedups vs. math====================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)     |
|---------|-----------|-------------|----------------|---------------------------|
| Average |    38.839 |             |                |                           |
| Max     |    66.518 | noop        | torch.bfloat16 | (4, 16, 1, 2, 131072, 64) |
| Min     |     7.175 | noop        | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |


====================================================FWD Speedups vs. fakv====================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)     |
|---------|-----------|-------------|----------------|---------------------------|
| Average |     1.122 |             |                |                           |
| Max     |     1.312 | noop        | torch.bfloat16 | (128, 16, 1, 2, 4096, 64) |
| Min     |     0.944 | noop        | torch.bfloat16 | (4, 16, 1, 16, 16384, 64) |


# Different Masks
(Achieved 90%+ bandwidth util)

command 
```
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python -W ignore::UserWarning: benchmarks/transformer/score_mod.py -dtype bfloat16 -s 65536 --kv-size 256 --backend cudnn efficient math fakv -mods noop causal alibi softcap -d 64 --decoding --throughput
```

<details>

| attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)     |   fwd_cudnn |   fwd_efficient |   fwd_math |   fwd_fakv |   fwd_compiled |   fwd_cudnn_speedup |   fwd_efficient_speedup |   fwd_math_speedup |   fwd_fakv_speedup |   fwd_mem_bw (TB/s) |   TFlops/s |
|-------------|----------------|---------------------------|-------------|-----------------|------------|------------|----------------|---------------------|-------------------------|--------------------|--------------------|---------------------|------------|
| noop        | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |         nan |         nan     |   2900.992 |    397.312 |        406.528 |                 nan |                 nan     |              7.136 |              0.977 |               0.660 |      0.665 |
| causal      | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |         nan |        3500.032 |   2907.136 |    208.896 |        215.040 |                 nan |                  16.276 |             13.519 |              0.971 |               0.627 |      0.631 |
| alibi       | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |         nan |        3512.320 |   2905.088 |    210.944 |        216.064 |                 nan |                  16.256 |             13.445 |              0.976 |               0.624 |      0.628 |
| softcap     | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |         nan |         nan     |    nan     |    397.312 |        216.064 |                 nan |                 nan     |            nan     |              1.839 |               0.624 |      0.628 |
| noop        | torch.bfloat16 | (8, 16, 1, 2, 65536, 64)  |         nan |         nan     |  26763.264 |    398.336 |        402.432 |                 nan |                 nan     |             66.504 |              0.990 |               0.667 |      5.378 |
| causal      | torch.bfloat16 | (8, 16, 1, 2, 65536, 64)  |         nan |         nan     |  26766.336 |    210.944 |        216.064 |                 nan |                 nan     |            123.882 |              0.976 |               0.624 |      5.028 |
| alibi       | torch.bfloat16 | (8, 16, 1, 2, 65536, 64)  |         nan |         nan     |  26765.312 |    819.200 |        216.064 |                 nan |                 nan     |            123.877 |              3.791 |               0.624 |      5.028 |
| softcap     | torch.bfloat16 | (8, 16, 1, 2, 65536, 64)  |         nan |         nan     |    nan     |    399.360 |        216.064 |                 nan |                 nan     |            nan     |              1.848 |               0.624 |      5.028 |

</details>


==================================================FWD Speedups vs. efficient=================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)     |
|---------|-----------|-------------|----------------|---------------------------|
| Average |    16.266 |             |                |                           |
| Max     |    16.276 | causal      | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |
| Min     |    16.256 | alibi       | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |


====================================================FWD Speedups vs. math====================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)     |
|---------|-----------|-------------|----------------|---------------------------|
| Average |    58.060 |             |                |                           |
| Max     |   123.882 | causal      | torch.bfloat16 | (8, 16, 1, 2, 65536, 64)  |
| Min     |     7.136 | noop        | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |


====================================================FWD Speedups vs. fakv====================================================


| Type    |   Speedup | attn_type   | dtype          | shape(B,Hq,M,Hkv,N,D)     |
|---------|-----------|-------------|----------------|---------------------------|
| Average |     1.546 |             |                |                           |
| Max     |     3.791 | alibi       | torch.bfloat16 | (8, 16, 1, 2, 65536, 64)  |
| Min     |     0.971 | causal      | torch.bfloat16 | (1, 16, 1, 16, 65536, 64) |

**Comment by drisspg** [comment]
# Different doc masks Fav3
 
 ```
 attn_type,dtype,"shape(B,Hq,M,Hkv,N,D)",fwd_cudnn,bwd_cudnn,fwd_efficient,bwd_efficient,fwd_math,bwd_math,fwd_fav3,bwd_fav3,fwd_compiled,bwd_compiled,fwd_cudnn_speedup,fwd_efficient_speedup,fwd_math_speedup,fwd_fav3_speedup,bwd_cudnn_speedup,bwd_efficient_speedup,bwd_math_speedup,bwd_fav3_speedup,fwd_mem_bw (TB/s),TFlops/s
noop,torch.bfloat16,"(4, 16, 16384, 16, 16384, 64)",10289.27993774414,25652.000427246094,31588.3846282959,105105.94940185547,nan,nan,8778.528213500977,24306.175231933594,12717.856407165527,40957.47375488281,0.8090419964127703,2.483782141973099,nan,0.6902521881403658,0.6263081698047344,2.566221491854709,nan,0.5934490827583303,0.04221394665987225,348.51834362390525
causal,torch.bfloat16,"(4, 16, 16384, 16, 16384, 64)",5315.423965454102,14334.400177001953,16291.360855102539,55505.470275878906,nan,nan,4642.496109008789,12733.663558959961,6459.936141967773,20921.823501586914,0.822829181069112,2.5219074147287155,nan,0.7186597525087345,0.6851410526388722,2.652993907135716,nan,0.6086306749502077,0.08310777385431906,345.74911617743084
sliding_window,torch.bfloat16,"(4, 16, 16384, 16, 16384, 64)",39158.206939697266,43294.01779174805,47663.8069152832,116762.62664794922,nan,nan,581.6320180892944,2279.2959213256836,767.8080201148987,3035.2959632873535,50.9999972829633,62.077766403313355,nan,0.7575227177260483,14.263524320329804,38.46828383795904,nan,0.7509303701827844,0.6992254547167401,221.97676837824014
document_mask,torch.bfloat16,"(4, 16, 16384, 16, 16384, 64)",nan,nan,nan,nan,nan,nan,4713.920116424561,12637.151718139648,7929.471969604492,21526.94320678711,nan,nan,nan,0.5944809609636191,nan,nan,nan,0.5870388376439508,0.06770575822172661,279.4893699392874
prefix_lm,torch.bfloat16,"(4, 16, 16384, 16, 16384, 64)",39426.49459838867,43301.025390625,47631.58416748047,115424.4155883789,nan,nan,nan,nan,6457.47184753418,20850.36849975586,6.10556197987048,7.3761969532501865,nan,nan,2.0767510843336905,5.535845353991246,nan,nan,0.0831394893661065,346.1324276852249
noop,torch.bfloat16,"(32, 16, 16384, 2, 16384, 64)",82626.71661376953,209323.6083984375,nan,nan,nan,nan,75212.89825439453,197986.3739013672,99725.41046142578,415825.0732421875,0.828542256496702,nan,nan,0.7541999366699744,0.5033934263904329,nan,nan,0.47612899423709043,0.02422571231165288,355.56885483556664
causal,torch.bfloat16,"(32, 16, 16384, 2, 16384, 64)",42529.47235107422,114342.04864501953,nan,nan,nan,nan,36057.53707885742,102333.66394042969,52429.79049682617,169318.4051513672,0.8111699846225541,nan,nan,0.6877299477486976,0.67530785293424,nan,nan,0.6043859428568648,0.046079129462595264,340.8012415053546
sliding_window,torch.bfloat16,"(32, 16, 16384, 2, 16384, 64)",304718.32275390625,340758.60595703125,nan,nan,nan,nan,4449.151992797852,16581.31217956543,6264.832019805908,20927.520751953125,48.63950410650384,nan,nan,0.710178976664037,16.28279861699475,nan,nan,0.7923209049030774,0.38563190463243224,217.64100617692895
document_mask,torch.bfloat16,"(32, 16, 16384, 2, 16384, 64)",nan,nan,nan,nan,nan,nan,36275.42495727539,101856.70471191406,62578.0143737793,175234.3292236328,nan,nan,nan,0.5796832213403545,nan,nan,nan,0.5812599914821784,0.03860651585347025,283.3203510100004
prefix_lm,torch.bfloat16,"(32, 16, 16384, 2, 16384, 64)",304797.79052734375,344527.1301269531,nan,nan,nan,nan,nan,nan,50764.73617553711,168541.53442382812,6.004124388106679,nan,nan,nan,2.0441675181417147,nan,nan,nan,0.04759049856274444,352.2351262998327
```

**Pull request closed without merging**
