### PR TITLE
[TEST] Fix _scaled_mm tests

### PR DESCRIPTION
**Pull request by Aidyn-A**
This PR resolves several sets of `_scaled_mm` test failures:
- `scale_a` and `scale_b` are now required arguments, so the function `sample_inputs_scaled_mm` must supply them
- `_scaled_mm` does not support `"meta"` device, so it should be skipped in `test_meta.py`

cc @drisspg  @xwang233

### CODE REVIEW

**Review by drisspg — APPROVED** [review]
Thanks! I am not sure off hand why we dont support metadevice though

**Comment by Aidyn-A** [comment]
Lint errors are unrelated,
@pytorchbot -i

**Comment by Aidyn-A** [comment]
Lint errors are unrelated,
@pytorchbot merge -i

**Pull request closed without merging**
