### PR TITLE
Update docs about DP and DDP for CUDA

### PR DESCRIPTION
**Pull request by zasdfgbnm**
We should recommend DDP instead of DP. Hope we can also cherry-pick this for 1.5

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
Looks good! Can you also please link to torch.distributed.launch for instructions on how to start multiple processes?

**Comment by zasdfgbnm** [comment]
Sure

**Comment by zasdfgbnm** [comment]
@ngimel Added

**Comment by h6197627** [comment]
Any chances to overcome this limitation
https://github.com/pytorch/pytorch/blob/95ad94c75b09ad2438141e4eb52e83e737966e60/torch/nn/parallel/distributed.py#L146-L149
without requiring user edit each model's code?
I think it would be really helpful

**Comment by ngimel** [comment]
Please file a feature request.

**Pull request closed without merging**
