### PR TITLE
[pytorch] upload mobile code analysis result to AWS

### PR DESCRIPTION
**Pull request by ljk53**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#43596 [pytorch] upload mobile code analysis result to AWS**

Summary:
Use the mobile custom build CI job to upload the static analysis result
to AWS per github PR.

Mobile selective build script could fetch the latest version from AWS
according to local commit hashes.

### CODE REVIEW

**Comment by ezyang** [comment]
Hmm, it looks like you're uploading this on every CI run, including PR runs. Is that really what we want here? It seems to me like master only would be better.

**Comment by ljk53** [comment]
> Hmm, it looks like you're uploading this on every CI run, including PR runs. Is that really what we want here? It seems to me like master only would be better.

Right, I plan to add that check later because I want to test on this PR first. This CI itself needs to run on PR because the main purpose is to test the e2e custom build + integration, so I cannot use the branch filter on workflow. I plan to use 'if ! [[ "${CIRCLE_BRANCH}" == "master"; then exit 0; fi'. Is there better way to do it?

Also, could you please help add the IAM credentials to circle CI environment variables?

**Comment by ezyang** [comment]
> Also, could you please help add the IAM credentials to circle CI environment variables?

We shouldn't, not as directly asked for here, because if we add it to a place which is accessible by this PR, then it will be accessible to ALL PRs, aka you have leaked the credential. Let's sync about this today

**Comment by ljk53** [comment]
> We shouldn't, not as directly asked for here, because if we add it to a place which is accessible by this PR, then it will be accessible to ALL PRs, aka you have leaked the credential. Let's sync about this today

Make sense - how do the existing `CIRCLECI_AWS_ACCESS_KEY_FOR_XXX` env variables work in config.yml?

**Comment by ezyang** [comment]
Some of them are being purposely leaked :) But they are only used for the specific CI run

**Pull request closed without merging**
