### PR TITLE
Removed unused weight update in prepack. Moved zero point update to

### PR DESCRIPTION
**Pull request by kimishpatel**
qlinear/qconv to be consistent with data update.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit f6da1913:


**None of the build failures appear to be your fault**.

* **9/9** recognized as flaky :snowflake:
    * Re-run these jobs?


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=f6da1913a181c6c2f530a51e97b85e732be15423).

### :snowflake: 9 failures recognized as flaky
The following build failures have been detected as flaky and **may not be your fault**:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4263349) pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build (1/9)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=86719187) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=86719187)) :snowflake:
<details>
<summary>
<code>Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83 not found</code>
</summary>

```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83 
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83 not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4263372) pytorch_linux_xenial_py2_7_9_build (2/9)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=86719188) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=86719188)) :snowflake:
<details>
<summary>
<code>Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py2.7.9:a8006f9a-272d-4478-b137-d121c6f05c83 not found</code>
</summary>

```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py2.7.9:a8006f9a-272d-4478-b137-d121c6f05c83 
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py2.7.9:a8006f9a-272d-4478-b137-d121c6f05c83 not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4263366) pytorch_linux_xenial_py3_6_gcc5_4_build (3/9)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=86719262) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=86719262)) :snowflake:
<details>
<summary>
<code>Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3.6-gcc5.4:a8006f9a-272d-4478-b137-d121c6f05c83 not found</code>
</summary>

```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3.6-gcc5.4:a8006f9a-272d-4478-b137-d121c6f05c83 
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3.6-gcc5.4:a8006f9a-272d-4478-b137-d121c6f05c83 not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4263371) pytorch_linux_xenial_py3_clang5_android_ndk_r19c_mobile_code_analysis (4/9)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=86719263) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=86719263)) :snowflake:
<details>
<summary>
<code>Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83 not found</code>
</summary>

```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83 
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:a8006f9a-272d-4478-b137-d121c6f05c83 not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4263350) pytorch_libtorch_linux_xenial_cuda9_cudnn7_py3_build (5/9)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=86719294) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=86719294)) :snowflake:
<details>
<summary>
<code>Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda9-cudnn7-py3:a8006f9a-272d-4478-b137-d121c6f05c83 not found</code>
</summary>

```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda9-cudnn7-py3:a8006f9a-272d-4478-b137-d121c6f05c83 
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda9-cudnn7-py3:a8006f9a-272d-4478-b137-d121c6f05c83 not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4263360) pytorch_linux_xenial_py3_clang5_mobile_build (6/9)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=86719311) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=86719311)) :snowflake:
<details>
<summary>
<code>Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-asan:a8006f9a-272d-4478-b137-d121c6f05c83 not found</code>
</summary>

```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-asan:a8006f9a-272d-4478-b137-d121c6f05c83 
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-asan:a8006f9a-272d-4478-b137-d121c6f05c83 not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4263362) pytorch_xla_linux_xenial_py3_6_clang7_build (7/9)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=86719329) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=86719329)) :snowflake:
<details>
<summary>
<code>Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3.6-clang7:a8006f9a-272d-4478-b137-d121c6f05c83 not found</code>
</summary>

```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3.6-clang7:a8006f9a-272d-4478-b137-d121c6f05c83 
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3.6-clang7:a8006f9a-272d-4478-b137-d121c6f05c83 not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4263357) pytorch_linux_xenial_cuda9_cudnn7_py3_build (8/9)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=86719348) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=86719348)) :snowflake:
<details>
<summary>
<code>Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda9-cudnn7-py3:a8006f9a-272d-4478-b137-d121c6f05c83 not found</code>
</summary>

```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda9-cudnn7-py3:a8006f9a-272d-4478-b137-d121c6f05c83 
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda9-cudnn7-py3:a8006f9a-272d-4478-b137-d121c6f05c83 not found 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4263369) pytorch_linux_xenial_py3_clang5_asan_build (9/9)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=86719369) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=86719369)) :snowflake:
<details>
<summary>
<code>Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-asan:a8006f9a-272d-4478-b137-d121c6f05c83 not found</code>
</summary>

```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-asan:a8006f9a-272d-4478-b137-d121c6f05c83 
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-asan:a8006f9a-272d-4478-b137-d121c6f05c83 not found 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by supriyar** [comment]
Can you also make this change for qconv to be consistent? Thanks

**Comment by kimishpatel** [comment]
> Can you also make this change for qconv to be consistent? Thanks

Supriya. I updated the PR.

**Review by supriyar — APPROVED** [review]
LGTM, thanks!
Please make sure to rebase and pass builds before submitting.

**Comment by kimishpatel** [comment]
@supriyar, how can I merge this?

**Comment by supriyar** [comment]
> @supriyar, how can I merge this?

You can click on Land to fbsource and that should be it.

**Pull request closed without merging**
