### PR TITLE
[aarch64] Replace OpenBLAS with NVPL in cuda arm docker

### PR DESCRIPTION
**Pull request by tinglvv**
Add NVPL to CUDA ARM docker build

original https://github.com/pytorch/builder/pull/1928 moving to pytorch/pytorch repo now

Need to go with builder repo change https://github.com/pytorch/builder/pull/1950

cc @atalman @Aidyn-A @ptrblck @nWEIdia

### CODE REVIEW

**Comment by Aidyn-A** [comment]
Seems like it is doing alright. I do see some NVPL installation log [nvpl_log.txt](https://github.com/user-attachments/files/16592293/nvpl_log.txt)
in the job: https://github.com/pytorch/pytorch/actions/runs/10357080006/job/28668356992?pr=132811

**Comment by atalman** [comment]
@tinglvv the docker image was build here ``308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/manylinuxaarch64-builder-cuda12.4:d86343bac7abb10c50c0ad2a9fa452efc70810e3`` can you please open test PR of using this image here: 
https://github.com/pytorch/pytorch/blob/main/.github/workflows/generated-linux-aarch64-binary-manywheel-nightly.yml#L141

This can be temporary test PR, to test this image.

**Review by atalman — APPROVED** [review]
lgtm, please open test PR to get the green signal before merging

**Comment by Rohanjames1997** [comment]
@tinglvv
Out of curiosity, do you have details of the perf improvement that came with NVPL BLAS over OpenBLAS?

**Pull request closed without merging**
