### PR TITLE
make g2p ~30% faster on mobile by suppressing a log

### PR DESCRIPTION
**Pull request by codyohl**
Summary: using the tool from D39559248 i was able to make g2p faster on mobile by taking a look at profiles on stella frames. It turned out that the pytorch interpreter code does some logging that ends up being a pretty big bottleneck.

Differential Revision: D39901455

### CODE REVIEW

**Review by dzdang — APPROVED** [review]

**Comment by codyohl** [comment]
@dzdang or @ezyang can someone help merge this? it's a tiny non-behavioral change that significantly helps performance

**Comment by codyohl** [comment]
can either @jerryzh168, @salilsdesai, @kimishpatel, @digantdesai or @jianyuh please help merge this? I don't have approval

**Comment by dzdang** [comment]
merge -f 'non-behavioral logging change'

**Pull request closed without merging**
