### PR TITLE
Migrate binary builds to use Amazon2023 runners

### PR DESCRIPTION
**Pull request by ZainRizvi**
A continuation of the migration started in 
- https://github.com/pytorch/pytorch/pull/131250

Migrates all linux binary builds.

The failures are windows jobs which aren't touched by this PR

prev runs (for tracking):
- https://hud.pytorch.org/pytorch/pytorch/pull/131826?sha=e1ee074b1e7b17008e3f3774e4842b5e1d4c1355
- https://hud.pytorch.org/pytorch/pytorch/pull/131826?sha=50a3488ae776f86bd6bead8b048b051c49a25ec7

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel

### CODE REVIEW

**Review by malfet — COMMENTED** [review]
There are no amz2023.linux.arm64.m7g.4xlarge runners, as arm64 ones are already on a pretty decent AMI. Will cancel pending jobs now

**Comment by atalman** [comment]
Have we tested these in pytorch-canary ? Do you have a link to PR that validates these workflows ?

**Review by malfet — APPROVED** [review]

**Comment by ZainRizvi** [comment]
@pytorch merge -f "Failures are unrelated. The failing jobs are either windows or passed on a pervious iteration of this PR which had no significant changes. See https://hud.pytorch.org/pytorch/pytorch/pull/131826?sha=e1ee074b1e7b17008e3f3774e4842b5e1d4c1355"

**Comment by ZainRizvi** [comment]
https://github.com/pytorch merge -f "Failures are unrelated. The failing jobs are either windows or passed on a pervious iteration of this PR which had no significant changes. See https://hud.pytorch.org/pytorch/pytorch/pull/131826?sha=e1ee074b1e7b17008e3f3774e4842b5e1d4c1355"

**Pull request closed without merging**
