### PR TITLE
Add truncated normal

### PR DESCRIPTION
**Pull request by ruotianluo**
Add tensor.truncated_normal_ and nn.init.truncated_normal

Code ported from tensorflow.

#2129

### CODE REVIEW

**Comment by apaszke** [comment]
I don't think we want to add a function like this to the global namespace. There's a WIP PR for `TruncatedDistribution` which generalizes this to arbitrary `torch.distributions.Distribution` objects.

**Comment by apaszke** [comment]
Thanks a lot for the PR, but please remember to wait until we confirm that we'll want to merge it before you start working on it 😕

**Comment by soumith** [comment]
@Randl see comment above https://github.com/pytorch/pytorch/pull/5617#issuecomment-371435360

**Comment by PetrochukM** [comment]
Given that `TruncatedDistribution` has not made it into the code base yet and a truncated normal distribution is used to initialize most of the current state-of-the-art NLP models, should this PR be merged for now?

**Comment by cossio** [comment]
> There's a WIP PR for `TruncatedDistribution`

Can we have a link to this PR to track its progress

**Comment by tranhungnghiep** [comment]
@ruotianluo Can you add a link to your standalone code if available? Currently I have to sample by `scipy` and copy the data to PyTorch GPU Tensor. Sampling directly in PyTorch would be much better.

```python
def truncated_norm_init_(wv, my_mean=0.0, my_std=0.5, myclip_a=-1, myclip_b=1):
    from scipy import stats as spstats
    a, b = (myclip_a - my_mean) / my_std, (myclip_b - my_mean) / my_std
    wv.data[:] = torch.as_tensor(spstats.truncnorm.rvs(a, b, loc=my_mean, scale=my_std, size=list(w.shape))).cuda()
    return wv

wv = torch.nn.Parameter(torch.empty(size, dtype=torch.float, device='cuda', requires_grad=True))
truncated_norm_init_(wv, my_mean=0.0, my_std=0.5, myclip_a=-1, myclip_b=1)
```

**Comment by ruotianluo** [comment]
https://discuss.pytorch.org/t/implementing-truncated-normal-initializer/4778/16?u=ruotianluo

I end up doing this.

**Pull request closed without merging**
