### PR TITLE
[tests][dynamo] enable dynamo tests for optimizers

### LINKED ISSUE #112731: [dynamo + optim] complex, sparse are not on tracing testing path
### 🚀 The feature, motivation and pitch

Even though we allow tracing complex and sparse grads for optimizers, we do not test that these actually work

### Solution
Copy some of the tests from test_optim e.g.
https://github.com/pytorch/pytorch/blob/main/test/optim/test_optim.py#L1503

into https://github.com/pytorch/pytorch/blob/main/test/dynamo/test_optimizers.py

### Alternatives

Not tested

### Additional context

NIL

### PR DESCRIPTION
**Pull request by khushi-411**
Fixes #112731

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by khushi-411** [comment]
@pytorchbot merge

Thanks, @Skylion007!

**Comment by khushi-411** [comment]
The failures seem unrelated to the PR, so I'm rebasing to see if it passes next time.

**Comment by khushi-411** [comment]
Gentle ping, @Skylion007!

**Comment by khushi-411** [comment]
Gentle ping, @Skylion007!

**Comment by khushi-411** [comment]
Gentle ping, @Skylion007!

**Comment by khushi-411** [comment]
Gentle ping, @Skylion007!

**Comment by khushi-411** [comment]
Gentle ping, @Skylion007! Thanks!

**Comment by khushi-411** [comment]
Hi, Gentle ping, @Skylion007!

**Pull request closed without merging**
