### PR TITLE
Implement HPUHooksInterface

### PR DESCRIPTION
**Pull request by bsochack**
Fixes regression #137262

### CODE REVIEW

**Comment by bsochack** [comment]
@atalman, @kit1980, @albanD, please help to review the change. It fixes the regression after interface changes for Intel Gaudi accelerator

**Comment by kit1980** [comment]
Closing this for 2.5.0.

**Comment by bsochack** [comment]
@kit1980 why was it closed?

**Comment by kit1980** [comment]
I've re-opened.
I forgot that 2.5.0 has the same branch as 2.5.1.

**Comment by bsochack** [comment]
@kit1980 can this change be merged to 2.5 branch ?

**Comment by kit1980** [comment]
@bsochack Not now. We are going to do one-issue fix for 2.5.1.

**Comment by kit1980** [comment]
2.5.1 is an emergency patch release to address specific large regressions, moving this to 2.6.0

**Comment by bsochack** [comment]
@kit1980 the changes broke Intel Gaudi support. This patch is low risk for other devices. We really would like to see it in PT 2.5.1

**Comment by kit1980** [comment]
@bsochack Sorry, we don't have time for 2.5.1. Especially taken in to account that even the change to main is not landed.
It's possible we will be doing 2.5.2.

**Comment by malfet** [comment]
In general, we should auto-close all cherry-picks into release branch if there are no corresponding commit to trunk PR of if has not been landed for some reason. When it's landed on trunk, we can restart the discussion

**Comment by bsochack** [comment]
@kit1980 @malfet the unfortunate thing about main is that this functionality was re-written again. 
The patches listed here #136519 are merged and reverted multiple times, causing merge conflicts etc. It is fine, but it blocks merge of the change to main and the change to main had to be refactored.

**Pull request closed without merging**
