### PR TITLE
Add CUDA 12.1 workflows

### PR DESCRIPTION
**Pull request by ptrblck**
CC @atalman @malfet

### CODE REVIEW

**Comment by ptrblck** [comment]
Builds seem to work.
The `conda` test failures seem to be related to: https://github.com/pytorch/builder/pull/1385
The `manywheel` tests fail with:
```
ERROR: Could not find a version that satisfies the requirement pytorch-triton==2.1.0+46672772b4 (from torch) (from versions: 0.0.1)
ERROR: No matching distribution found for pytorch-triton==2.1.0+46672772b4
```
as the needed URL is invalid: https://download.pytorch.org/whl/nightly/cu121

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Manually pushed `pytorch-cuda` for 12.1 to `pytorch-nightly` channel and `pytorch-triton` to `https://download.pytorch.org/whl/nightly/cu121` and everything seems to be working now

**Pull request closed without merging**
