### PR TITLE
[dynamo] graph break on setattr `requires_grad`

### LINKED ISSUE #109505: [dynamo] torch._dynamo.exc.Unsupported: call_function BuiltinVariable(setattr) [TensorVariable(), ConstantVariable(str), ConstantVariable(bool)] {}
### 🐛 Describe the bug

Occurs when you do

```
foo.requires_grad = True
```

in torch.compile'd region.

Occurred while implementing torch.tensor polyfill.

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### PR DESCRIPTION
**Pull request by jon-chuang**
Main: `RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`
This PR: graph breaks and eager applies the mutation, new tensors are tracked

Fixes https://github.com/pytorch/pytorch/issues/109505 (the original bug does not occur, but a new bug where the mutation isn't applied - because AOTAutograd is not `requires_grad` mutation aware - is mitigated)

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
this sounds good to me. Thanks!

**Comment by jon-chuang** [comment]
Hmm, technically, don't we need to graph break on requires_grad _even for intermediate tensors that are outputs of the graph_?

**Comment by PaliC** [comment]
@pytorchbot revert -m "relevant tests are not running for this pr, however, this is fixed after landing https://github.com/pytorch/pytorch/pull/113297/" -c nosignal

Sorry need to revert this. After https://github.com/pytorch/pytorch/pull/113297 lands feel free to remerge to check if tests pass

**Comment by PaliC** [comment]
Note: https://github.com/pytorch/pytorch/pull/113297 is being force merged, so you shouldn't have to wait too long :)

**Pull request closed without merging**
