### PR TITLE
[LTC] Improve some documentations

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
Fixed some typos in lazy_tensor_core/QUICKSTART.md.
And added a shape inference guide in OP_LOWERING_GUIDE.md.
And added some logging instructions in TROUBLESHOOTING.md.

### CODE REVIEW

**Comment by alanwaketan** [comment]
Looks like the branch is broken on those bots.

**Review by wconstab — APPROVED** [review]
Awesome, especially thanks for adding the logging instructions!

**Comment by alanwaketan** [comment]
@wconstab Thanks for approving this patch.

**Comment by alanwaketan** [comment]
The CI errors should not be related to this patch. Land it as it is.

**Pull request merged**
