### PR TITLE
Add support for creating docsets.

### PR DESCRIPTION
**Pull request by lucasb-eyer**
Docsets are an offline documentation format introduced by Dash.app and supported by Zeal and some other open-source clones.

I did this for myself as I'm offline often but thought I'd see if you're interested.
If you think this is too niche to be added here, feel free to just close this PR.

### CODE REVIEW

**Comment by soumith** [comment]
@apaszke and I used Dash a lot, so thank you! :)

**Comment by lucasb-eyer** [comment]
Hey, that's great news! In that case I could submit it to them for official inclusion.
I just didn't do so yet because I feared I wouldn't be able to actively maintain it alone, what do you think?

**Comment by soumith** [comment]
if you document what the maintenance entails, I am happy to maintain it (or even better, if it can be automated, add it to the contbuild script that automatically rebuilds docs for the website): https://github.com/pytorch/builder/blob/master/jenkins/pytorch/build_nimbix.sh#L182-L209

**Comment by lucasb-eyer** [comment]
I'll make a manual submission first, then automate it in the script you linked. I'll probably have a couple questions for automation that I'll ask in a new PR once I get to it. Thanks!

**Comment by lucasb-eyer** [comment]
Looks like @iamaziz [already did that](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/PyTorch), I just couldn't see it on Linux using Zeal. Argh 😕 I guess I'll leave it here and let @iamaziz decide how to continue. Sorry for that!

**Comment by iamaziz** [comment]
Hey, that's cool @lucasb-eyer !! looks like you built it using doc2dash, right ? I suggest, submitting it to Dash [as improve existing docset](https://github.com/Kapeli/Dash-User-Contributions#improve-an-existing-docset), since the one I pushed is [not in the best](https://github.com/iamaziz/PyTorch-docset/issues/1) layout yet :/

I think the User Contributed docsets are not pushed to Zeal, that's why it does not appear. Perhaps a way around this is to add it from feed URL or download the compressed `.tgz` file and open it locally.

**Pull request merged**
