### PR TITLE
Add deterministic impl of `scatter_add` CUDA for all input sizes

### LINKED ISSUE #50469: Feature Request: Add a deterministic version of scatter_add_cuda_kernel
Running stable_baselines3 in deterministic mode I get

RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.set_deterministic(True)'. You can turn off determinism just for this operation if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.

Thanks

cc @ezyang @gchanan @zou3519 @ngimel @mruberry @kurtamohler

### PR DESCRIPTION
**Pull request by kurtamohler**
Fixes #50469

### CODE REVIEW

**Comment by amorehead** [comment]
Hi! Has there been any update on this PR since June? I ask because I am very interested to see this branch merged into `master` soon.

**Comment by ngimel** [comment]
@kurtamohler can you please rebase this?

**Comment by kurtamohler** [comment]
@ngimel rebase is done

**Comment by ngimel** [comment]
Thanks for the fix @kurtamohler

**Review by ngimel — APPROVED** [review]

**Comment by Ziyang-Yu** [comment]
I met the same problem, can I solve it by updating pytorch to 1.12.1?

**Comment by kurtamohler** [comment]
@Ziyang-Yu, no it's not in 1.12.1, but it will be in the 1.13.0 release, which will probably come out in a few weeks

**Comment by mnbucher** [comment]
can confirm that this is indeed solved by using 1.13.1

**Pull request closed without merging**
