### PR TITLE
[DataLoader] Switch NotImplementedError to TypeError for len

### LINKED ISSUE #59378: `NotImplementedError` is not right Exception for `DataPipe.__len__`
## 🐛 Bug

Thanks to @pmeier, a bug of `IterDataPipe` was found. For each `IterDataPipe` class, we raise `NotImplementedError` in `__len__` in some cases such as `length` is -1 or prior `DataPipe` is not `Sized`.

When we apply `tqdm` to the `DataPipe` instance without explicit length, `len(dp)` will be called and the `NotImplementedError` will emit. So, we can never use `tqdm` for such kind of DataPipe. However,  we are actually expecting DataPipe with `NotImplementedError` as an infinite length. 

And, based on the definition of [`NotImplementedError`](https://docs.python.org/3/library/exceptions.html#NotImplementedError), it's not an appropriate Exception since this exception normally raises from base class to enforce derived class implementing this method.

And, considering the implementation of `tqdm`, we should switch `NotImplementedError` to `TypeError`.
https://github.com/tqdm/tqdm/blob/05ad200df3ccbc21c5c840d064e619ec9838f902/tqdm/std.py#L983-L990

## To Reproduce

```py
>>> import tqdm
>>> class DP(IterDataPipe):
...     def __len__(self):
...         raise NotImplementedError
... 
>>> dp = DP()
>>> pbar = tqdm.tqdm(dp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/erjia/tools/miniconda3/envs/pt/lib/python3.8/site-packages/tqdm/std.py", line 985, in __init__
    total = len(iterable)
  File "<stdin>", line 3, in __len__
NotImplementedError
```

## Expected behavior

By switching to `TypeError`, DataPipe works with `tqdm` correctly.
BTW, we should not create `__len__` at runtime since this method is attached to `class` object. When we change it, behavior of all instances will change. Any other suggestions to fix it are welcomed.

cc @SsnL @VitalyFedyunin @ejguan

### PR DESCRIPTION
**Pull request by ejguan**
Fixes #59378

Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#59464 [DataLoader] Switch NotImplementedError to TypeError for len**
* #58938 [DataLoader] Close byte stream explicitly

Differential Revision: [D28944447](https://our.internmc.facebook.com/intern/diff/D28944447)

### CODE REVIEW

**Comment by NicolasHug** [comment]
I'm confused, I got a notification for this PR but I'm not familiar with this work at all, and I see:

image

while I haven't pushed anything to GH in the past hour. Would you know what's hapening @ejguan ?

**Comment by ejguan** [comment]
@NicolasHug 
Wait?! How is that possible?!
But, maybe something wrong with our aws server. It was the first time for meto use aws to ghstack a PR. Let me check my git config.

**Review by pmeier — APPROVED** [review]
LGTM, thanks @ejguan! One general design question though: seeing that the `__len__` method is exactly duplicated for many different datapipes, would it make sense to create a datapipe superclass and implement it there?

**Comment by ejguan** [comment]
> seeing that the `__len__` method is exactly duplicated for many different datapipes, would it make sense to create a datapipe superclass and implement it there?

Yeah, you are right. At least all the front-end DataPipe like `listfiles` and `loadfile` can share one superclass, since they share same logic to determine by the `__len__` argument `length`. I would like to wait until we have some ideas about the other front-end datapipe like S3Reader, GoogleCloudReader, etc., then we can have an abstract class for all of them.

**Comment by SsnL** [comment]
I would also suggest saying in comments why we use TypeError (e.g., by linking to the NOTE at https://github.com/pytorch/pytorch/blob/6620d7d688c9482a00b1a9827187f135b72b7862/torch/utils/data/sampler.py#L26-L51)

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28944447).

**Pull request closed without merging**
