### PR TITLE
[ROCm] Update to AOTriton 0.7b (Cherry-picked)

### LINKED ISSUE #133540: DISABLED test_scaled_dot_product_attention_cuda (__main__.TestOneOffModelExportResult)
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22export%2Ftest_export.py%3A%3ATestOneOffModelExportResult%3A%3Atest_scaled_dot_product_attention_cuda%22%5D)).

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @dllehr-amd @jataylo @hongxiayang @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @penguinwu

### PR DESCRIPTION
**Pull request by xinyazhang**
This is a cherry-picked version of https://github.com/pytorch/pytorch/pull/134498 for PyTorch release/2.5. Original notes below:

Notable changes:
1. Re-enable `test_transformers.py` suite.
2. PRNG support for CudaGraph API (part of aotriton pin bump) and enable related unit tests
3. Update cuda and hip-specific files to let SPDA on ROCM follow CUDA's approach to handle PRNG's seeds and offsets, which interacts correctly with CudaGraph module in PyTorch.
4. Skip UTs, including disabling gqa
5. EXPERIMENTAL Navi31 support (part of aotriton pin bump). Disabled by default at PyTorch level, user needs to enable Navi31 support with env var `TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1`
6. Bwd performance boost (part of aotriton pin bump)

**NOTE for reviewers**: Aotriton is a library/backend for SDPA implementation on ROCm only.

Know Problem:
1. `test/test_transformers.py` will cause massive failures and/or NaN outputs with `--use-pytest`
    + Update: Confirmed skip `class TestSDPAPrivateUse1Only` can fix the problem with `--use-pytest`

Note:
AOTriton 0.7b adds support to nestedtenosrs+SDPA but need more work (and consequently a separate PR) to enable it.

Fixes #133540

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by pruthvistony — APPROVED** [review]
LGTM. Cherry-pick from main branch.
Part of continued effort to improve AOTriton on ROCm.

**Review by jithunnair-amd — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
`inductor/test_flex_decoding.py` ROCm CI failures are unrelated and will be addressed by https://github.com/pytorch/pytorch/pull/136557

**Comment by kit1980** [comment]
This looks like feature work, at least EXPERIMENTAL Navi31 support.
If you split out critical fixes only, we can cherry-pick that.

**Comment by jithunnair-amd** [comment]
> This looks like feature work, at least EXPERIMENTAL Navi31 support. If you split out critical fixes only, we can cherry-pick that.

@kit1980 If it helps, I've updated the PR description to better describe the changes in this PR, and hopefully also establish that these changes are ROCm-only changes.

**Comment by jithunnair-amd** [comment]
ROCm CI jobs passed: https://hud.pytorch.org/pytorch/pytorch/pull/135869?sha=63c83e9a589c7147cc46feb9320fd52008b8c263#rocm

**Review by atalman — APPROVED** [review]
lgtm

**Comment by jithunnair-amd** [comment]
@kit1980 Can we please merge this PR? It also allows us to re-enable entire test_transformers.py suite for ROCm, which was disabled due to changes in math backend using fp32.

**Review by malfet — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
Verified the aotriton 0.7b version in torch2.5 final RC wheel - pip3 install torch==2.5.0 torchvision --index-url https://download.pytorch.org/whl/test/rocm6.2 as follows:
1. [Latest manylinux rocm6.2 image built for release/2.5](https://hud.pytorch.org/hud/pytorch/pytorch/release%2F2.5/1?per_page=50&name_filter=manywheel): https://github.com/pytorch/pytorch/actions/runs/11332669172/job/31515277027:
```
#85 [rocm_final 11/11] RUN bash ./install_aotriton.sh /opt/rocm && rm install_aotriton.sh aotriton_version.txt
#85 0.255 ++ dirname ./install_aotriton.sh
#85 0.255 + source ./common_utils.sh
#85 0.255 ++ '[' -n 9 ']'
#85 0.255 ++ export SUDO=/bin/sudo
#85 0.255 ++ SUDO=/bin/sudo
#85 0.256 + TARBALL=aotriton.tar.gz
#85 0.256 + read -d '\n' VER MANYLINUX ROCMBASE PINNED_COMMIT SHA256
#85 0.256 + true
#85 0.256 ++ uname -m
#85 0.257 + ARCH=x86_64
#85 0.257 + AOTRITON_INSTALL_PREFIX=/opt/rocm
#85 0.257 + AOTRITON_URL=https://github.com/ROCm/aotriton/releases/download/0.7b/aotriton-0.7b-manylinux_2_17_x86_64-rocm6.2-shared.tar.gz
#85 0.257 + cd /opt/rocm
#85 0.257 + curl -L --retry 3 -o aotriton.tar.gz https://github.com/ROCm/aotriton/releases/download/0.7b/aotriton-0.7b-manylinux_2_17_x86_64-rocm6.2-shared.tar.gz
#85 0.261   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#85 0.261                                  Dload  Upload   Total   Spent    Left  Speed
#85 0.261 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#85 0.621 
  5  620M    5 36.6M    0     0   101M      0  0:00:06 --:--:--  0:00:06  101M
 60  620M   60  375M    0     0   275M      0  0:00:02  0:00:01  0:00:01  338M
100  620M  100  620M    0     0   287M      0  0:00:02  0:00:02 --:--:--  325M
#85 2.418 ++ sha256sum aotriton.tar.gz
#85 2.418 ++ cut -d ' ' -f 1
#85 3.969 + ACTUAL_SHA256=3e9e1959d23b93d78a08fcc5f868125dc3854dece32fd9458be9ef4467982291
#85 3.969 + '[' 3e9e1959d23b93d78a08fcc5f868125dc3854dece32fd9458be9ef4467982291 '!=' 3e9e1959d23b93d78a08fcc5f868125dc3854dece32fd9458be9ef4467982291 ']'
#85 3.969 + tar xf aotriton.tar.gz
#85 9.182 + rm -rf aotriton.tar.gz
#85 DONE 15.2s
```

**Pull request merged**
