### PR TITLE
add rocm nightly build

### PR DESCRIPTION
**Pull request by walterddr**

### CODE REVIEW

**Comment by jeffdaily** [comment]
The ROCm build errors are due to the hipify script not running.  The cmake error `add_subdirectory given source "src/THH" which is not an existing directory` is because the hipify script creates the THH directory.

**Comment by walterddr** [comment]
> The ROCm build errors are due to the hipify script not running. The cmake error `add_subdirectory given source "src/THH" which is not an existing directory` is because the hipify script creates the THH directory.

which exact build failure were you referring to? 

BTW here are a bunch of changes I did since last time:
1. disabled libtorch build because of the cmake configuration issue (which I think is related to the hipify script not running)
2. trying to disable binary test because `pytorch/builder` repo's check_binary.sh script is not recognizing `rocm` and is still expecting cuda. (preparing a PR for it now)

also do we plan to enable all build variants (namely conda & libtorch) at the nightly stage for now or is it ok to just do the manywheel + rocm combination (on 3.6~3.8)

**Comment by jeffdaily** [comment]
The first stage of this pytorch rocm wheel effort was to get a successful nightly manywheel + rocm combination.  The conda and libtorch builds, though ultimately desired, are secondary efforts.  

That said, the libtorch build is failing as commented here:
https://github.com/pytorch/builder/pull/511#issuecomment-688995043
There could be additional errors, but it is primarily failing due to not running build_amd.py prior to setup.py install.

**Comment by walterddr** [comment]
sounds good. I will focus on getting manywheel + rocm work for this PR and will create fixes for libtorch/hipify on the next

**Review by seemethere — COMMENTED** [review]
~Looks mostly good to me, I'm curious to know how this interacts with the upload script.~

~Like what are the filenames for these wheels, and which folder on S3 do they actually get uploaded to?~

Just had a deeper look and looks like these binaries will get uploaded to the `rocm3.7` S3 folder

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
