### PR TITLE
[ONNX] Support one_hot

### LINKED ISSUE #22534: RuntimeError: ONNX export failed: Couldn't export operator aten::one_hot
## 🐛 Bug

Export of `F.one_hot` to ONNX format fails.

## To Reproduce
```
class TestMod(nn.Module):
    def __init__(self, size, maxint=10):
        super().__init__()
        self.maxint = maxint
        self.weight = torch.randint(0, maxint, [size])

    def forward(self, x):
        return F.one_hot(self.weight, num_classes=self.maxint)
test = TestMod(3)
torch.onnx.export(test, test.weight, "test.onnx", verbose=True)
```

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-0b35ee7f95af> in <module>
      8         return F.one_hot(self.weight, num_classes=self.maxint)
      9 test = TestMod(3)
---> 10 torch.onnx.export(test, test.weight,"test.onnx", verbose=True)

~/miniconda3/lib/python3.6/site-packages/torch/onnx/__init__.py in export(*args, **kwargs)
     23 def export(*args, **kwargs):
     24     from torch.onnx import utils
---> 25     return utils.export(*args, **kwargs)
     26 
     27 

~/miniconda3/lib/python3.6/site-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, strip_doc_string)
    129             operator_export_type=operator_export_type, opset_version=opset_version,
    130             _retain_param_name=_retain_param_name, do_constant_folding=do_constant_folding,
--> 131             strip_doc_string=strip_doc_string)
    132 
    133 

~/miniconda3/lib/python3.6/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, propagate, opset_version, _retain_param_name, do_constant_folding, strip_doc_string)
    367         if export_params:
    368             proto, export_map = graph._export_onnx(params_dict, opset_version, defer_weight_export, operator_export_type,
--> 369                                                    strip_doc_string)
    370         else:
    371             proto, export_map = graph._export_onnx({}, opset_version, False, operator_export_type, strip_doc_string)

RuntimeError: ONNX export failed: Couldn't export operator aten::one_hot
```

## Expected behavior

Export of graph to ONNX format using reference to ONNX's one_hot.

## Environment

 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.6.8

## Additional context

Can probably be solved by adding ONNX's one_hot:
https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/node/onehot.py
to:
https://github.com/pytorch/pytorch/blob/v1.1.0/torch/onnx/symbolic.py

### PR DESCRIPTION
**Pull request by cjermain**
This PR resolves #22534 by adding a converter for the `torch.nn.functional.one_hot` function, and covering it with a test.

Are there other places this should be tested?

### CODE REVIEW

**Comment by cjermain** [comment]
@lara-hdr, can you review this PR?

**Review by lara-hdr — APPROVED** [review]
Thanks for the PR!

**Comment by lara-hdr** [comment]
@houseroad, this PR is approved

**Review by houseroad — APPROVED** [review]
LGTM

**Pull request closed without merging**
