### PR TITLE
Improve readability of the extra message errors in assertEqual

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #87182
* #87183
* #87205
* #87204
* #87203
* #87424
* #87181
* #87282
* #87180
* #87278
* __->__ #87202

Goes from (note the `linspace.default` is very difficult to find)
```
Mismatched elements: 15 / 50 (30.0%)
Greatest absolute difference: 1 at index (17,)
Greatest relative difference: 1.0 at index (17,) : linspace.default
args = (0, -3, 50)
kwargs = {'dtype': torch.int16, 'device': device(type='cpu'),
'pin_memory': False}
```
to
```
Mismatched elements: 15 / 50 (30.0%)
Greatest absolute difference: 1 at index (17,)
Greatest relative difference: 1.0 at index (17,)
linspace.default
args = (0, -3, 50)
kwargs = {'dtype': torch.int16, 'device': device(type='cpu'),
'pin_memory': False}
```

### CODE REVIEW

**Review by pmeier — COMMENTED** [review]
The current behavior is a faithful reproduction of what `unittest` is doing: https://github.com/python/cpython/blob/702e0da000bf28aa20cb7f3893b575d977506495/Lib/unittest/case.py#L718-L726. The original request for this came from @ezyang in #76813. I don't mind the newline here, but I'll let him decide.

**Review by ezyang — APPROVED** [review]
s'fine, I don't mind. The important thing for me was preserving generated msg.

**Comment by malfet** [comment]
Actually, it's no signal, as it was merged with `-f` (due to CI outage)

**Comment by pmeier** [comment]
https://github.com/pytorch/pytorch/blob/a73ca6f58c1487abab013805922c47437e50eecf/test/test_testing.py#L71

needs an update

**Pull request closed without merging**
