### PR TITLE
[ROCm] Increasing the magma kernel launch bounds to default value

### PR DESCRIPTION
**Pull request by pruthvistony**
- It was limited to 256 for ROCm verion <= 4.2
- From ROCm version 4.3 default value of 1024 is supported

### CODE REVIEW

**Comment by pruthvistony** [comment]
@jeffdaily @jithunnair-amd
Please review this change

**Review by jithunnair-amd — APPROVED** [review]
LGTM

**Review by jeffdaily — APPROVED** [review]
LGTM

**Comment by pruthvistony** [comment]
@malfet 
Please review

**Comment by jeffdaily** [comment]
I've requested @malfet to review based on suggested reviewers.  @malfet, feel free to delegate as needed.

**Comment by jeffdaily** [comment]
@pruthvistony should we close this PR in favor of #60900?

**Comment by jeffdaily** [comment]
Closing since this change was replaced with #60900.

**Pull request closed without merging**
