### PR TITLE
update kineto submodule

### PR DESCRIPTION
**Pull request by ngimel**
Another try for #59755

### CODE REVIEW

**Comment by ngimel** [comment]
@gdankel, there are windows build errors now:
```
kineto.lib(Config.cpp.obj) : error LNK2019: unresolved external symbol "char const * __cdecl libkineto::toString(enum libkineto::ActivityType)" (?toString@libkineto@@YAPEBDW4ActivityType@1@@Z) referenced in function "public: virtual void __cdecl libkineto::Config::printActivityProfilerConfig(class std::basic_ostream<char,struct std::char_traits<char> > &)const " (?printActivityProfilerConfig@Config@libkineto@@UEBAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
kineto.lib(output_json.cpp.obj) : error LNK2001: unresolved external symbol "char const * __cdecl libkineto::toString(enum libkineto::ActivityType)" (?toString@libkineto@@YAPEBDW4ActivityType@1@@Z)
kineto.lib(Config.cpp.obj) : error LNK2019: unresolved external symbol "enum libkineto::ActivityType __cdecl libkineto::toActivityType(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?toActivityType@libkineto@@YA?AW4ActivityType@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: virtual bool __cdecl libkineto::Config::handleOption(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?handleOption@Config@libkineto@@UEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV34@@Z)
kineto.lib(Config.cpp.obj) : error LNK2019: unresolved external symbol "class std::array<enum libkineto::ActivityType,10> const __cdecl libkineto::activityTypes(void)" (?activityTypes@libkineto@@YA?BV?$array@W4ActivityType@libkineto@@$09@std@@XZ) referenced in function "private: void __cdecl libkineto::Config::selectDefaultActivityTypes(void)" (?selectDefaultActivityTypes@Config@libkineto@@AEAAXXZ)
bin\torch_cpu.dll : fatal error LNK1120: 3 unresolved externals
```

**Comment by gdankel** [comment]
Ok yes updating submodule can unearth new issues for builds not covered by Kineto CI. We need to add Windows build there. Let me take a closer look...

**Comment by gdankel** [comment]
What's the urgency?

**Comment by ngimel** [comment]
Fix for #59746. I guess if proper submodule update is hard, we could cherry-pick file descriptor fix to a branch and update to that.

**Comment by ngimel** [comment]
Usually linker errors on windows are caused by incorrect symbol visibility, inside pytorch we usually decorate with TORCH_API, but kineto doesn't have this macro.

**Comment by gdankel** [comment]
I think that's a good approach for small fixes if larger changes have landed since last update.

**Comment by ngimel** [comment]
@gdankel can a branch exist in kineto github repo, not connected to fbcode? If so, can you create a branch from 24d562065 (current kineto submodule in pytorch) + cherry-pick 897a49cfd fix? I don't think I have permissions in kineto repo.

**Comment by gdankel** [comment]
Ok will do. And let me give you permission as well.

**Comment by ilia-cher** [comment]
@ngimel @gdankel I just pushed fd_fix branch into pytorch/kineto

**Comment by ilia-cher** [comment]
https://github.com/pytorch/kineto/tree/fd_fix

**Comment by malfet** [comment]
Updated another PR with new hash

**Comment by gdankel** [comment]
> @gdankel can a branch exist in kineto github repo, not connected to fbcode? If so, can you create a branch from 24d562065 (current kineto submodule in pytorch) + cherry-pick 897a49cfd fix? I don't think I have permissions in kineto repo.

I think I have fixed this linker error in https://github.com/pytorch/kineto/pull/282

**Pull request closed without merging**
