### PR TITLE
Updates to Quantization documentation

### PR DESCRIPTION
**Pull request by gottbrath**
This pull request includes fixes for six quantization doc bugs.
https://github.com/pytorch/pytorch/issues/30283 - Rendering issue on QConfig
https://github.com/pytorch/pytorch/issues/26305 - Minor doc issue on fuse_modules()
https://github.com/pytorch/pytorch/issues/27451 - Issues with ConvReLU2d, ConvReLU3d, and LinearReLU doc issues
https://github.com/pytorch/pytorch/issues/26899 - Missing docstrings in torch.nn.intrinsic fused functions
https://github.com/pytorch/pytorch/issues/29735 - add discussion of QNNPack to quantization doc page
https://github.com/pytorch/pytorch/issues/27938 - some of the quantized functions lack documentation

Test Plan: This is a doc change. Run make html in the docs directory and look at the html in the browser.

### CODE REVIEW

**Comment by gottbrath** [comment]
this is a release branch version of #30288 which has landed on master.

**Review by mingbowan — APPROVED** [review]
LGTM

**Comment by gottbrath** [comment]
@mingbowan -- is this incorporated into v1.4.0?

**Comment by gottbrath** [comment]
@mingbowan  thanks for merging this!

**Pull request merged**
