### PR TITLE
fix dict iteration error in fuse_known_modules

### LINKED ISSUE #69158: Fusing module with multiple hooks causes `RuntimeError: OrderedDict mutated during iteration` in fuse_known_modules
## 🐛 Bug

if a module that is to be fused by `torch.quantization.fuse_modules.fuse_known_modules` has multiple hooks, then a `RuntimeError: OrderedDict mutated during iteration` will be raised since the loops iterate over the dict `items()` but delete from the dict during iteration.

## To Reproduce

```python
from torch.quantization.fuse_modules import fuse_known_modules
from torch.nn import Conv2d, ReLU

conv = Conv2d(10, 10, (3,3))
relu = ReLU()

# register any forward hooks to relu or pre forward hooks to conv
relu.register_forward_hook(lambda x: None)
relu.register_forward_hook(lambda x: None)

fuse_known_modules([conv, relu])
```

A quick fix would be unwrapping the `.items()` iterations into lists

### PR DESCRIPTION
**Pull request by bfineran**
Fixes #69158

### CODE REVIEW

**Comment by bfineran** [comment]
hi @z-a-f any update on this?

**Comment by jerryzh168** [comment]
Can you add a test after https://github.com/pytorch/pytorch/blob/master/test/quantization/eager/test_quantize_eager_ptq.py#L520 with example in https://github.com/pytorch/pytorch/issues/69158 and show that this PR fixes your issue
you can run the test with `python test/test_quantization.py TestClass.test_case`

**Comment by jerryzh168** [comment]
could you rebase on master?

**Comment by z-a-f** [comment]
@bfineran This PR was not landed. Is there a plan to do it?

**Pull request closed without merging**
