### PR TITLE
Add decompositions for reflection_pad{1, 2, 3}d_backward

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #115101
* #115113

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by isuruf** [comment]
This requires `n` triton kernels for `n`d padding.  Looking into it now.
```
                             |  Decomposed  |  Eager
32 threads: ----------------------------------------
      (3, 5, 1000000)        |      433     |   795 
      (3, 5, 1000, 1000)     |      853     |   795 
      (3, 5, 100, 100, 100)  |     1301     |   977 
 ```

**Review by lezcano — COMMENTED** [review]
When removing previous lowerings / decompositions, do you mind benchmarking the previous implementation as well for good measure?

On a side note, I have not looked closely into this, but I'm not sure whether we are going to be able to implement this efficiently as a decomp, rather than a lowering. The lowering uses `ops.masked`, which does not have an equally-powerful equivalent at a decomposition level. I'd like to see how does the generated code / performance compares between the previous lowering and the decomposition from this PR

**Comment by isuruf** [comment]
The decomposition here is slower than the eager one and also the lowering. I'm going to go with lowering for 1D and 3D at https://github.com/pytorch/pytorch/pull/115645

**Pull request closed without merging**
