### PR TITLE
Add hooks for execution on intel gaudi devices - 1

### PR DESCRIPTION
**Pull request by ankurneog**
## Motivation 
This is follow up to PR:https://github.com/pytorch/pytorch/pull/126970  to support Gaudi devices for Pytorch UT execution.

## Changes
We are adding additional hooks to:
1. Add dtype exceptions for Gaudi/HPU
2. Extend onlyNativeDevices decorator  functionality to add additional devices

### CODE REVIEW

**Comment by ankurneog** [comment]
@albanD  : Kindly help with the review and merge

**Comment by ankurneog** [comment]
@albanD  : Kindly help with the review and merge

**Comment by ankurneog** [comment]
@albanD  : could you kindly help with the review and merge. Thank you.

**Comment by ankurneog** [comment]
@albanD  : gentle reminder, could you please help with this PR, Thanks.

**Comment by ankurneog** [comment]
@albanD  : can you please help with the review

**Review by albanD — APPROVED** [review]
This is most likely to be brittle given that you don't have CI signal for it.

tbh if your CI cannot live in PT, I think a good long term plan is for the hpu CI spec to live where the CI runs. There you will be able to pin PyTorch and move forward carefully while always having a known good version.
But I guess that now that you have this scaffolding, you can already update these attributes on the OpInfos directly from your own repo before running the tests?

**Comment by ankurneog** [comment]
@albanD  : thanks for the approval, yes that's the goal , after this change is in, we will update opinfo data with gaudi  op  capabilities, that way we ensure its clean.

**Pull request closed without merging**
