### PR TITLE
Use constants from math.h for gelu op

### PR DESCRIPTION
**Pull request by xiaomengy**
Summary: Use constants from math.h for gelu op

Differential Revision: D15511736

### CODE REVIEW

**Comment by houseroad** [comment]
Looks good to me, only concern is windows build and mobile build. Please make sure they pass.

**Review by houseroad — COMMENTED** [review]
seems windows build is failing: https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-cuda9.0-cudnn7-windows-build/48058/console

**Comment by peterjc123** [comment]
https://docs.microsoft.com/en-us/cpp/c-runtime-library/math-constants?view=vs-2019 Please add the macro `_USE_MATH_DEFINES` before including `math.h`.

**Comment by peterjc123** [comment]
https://stackoverflow.com/questions/6563810/m-pi-works-with-math-h-but-not-with-cmath-in-visual-studio What about moving `cmath` in the includes section to be the first one?

**Review by houseroad — APPROVED** [review]
LGTM

**Pull request closed without merging**
