### PR TITLE
Strided masked reduction: mean (2nd try)

### PR DESCRIPTION
**Pull request by pearu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #67088

Differential Revision: [D32070264](https://our.internmc.facebook.com/intern/diff/D32070264)

### CODE REVIEW

**Comment by pearu** [comment]
@cpuhrsch could you try importing this PR?

**Comment by cpuhrsch** [comment]
Just for completeness note that the definition of mask differs between NumPy's MaskedArray and the where argument.

```
>>> npm1 = np.ma.masked_array([0., 1., 2.], [False, False, True])
>>> npm1
masked_array(data=[0.0, 1.0, --],
             mask=[False, False,  True],
       fill_value=1e+20)
>>> npm1.sum()
1.0
>>> np.sum([0., 1, 2], where=[False, False, True])
2.0
```

**Comment by ngimel** [comment]
@cpuhrsch I agree that `where` functionality is covered by the masked reduction RFC, my question was about adding it for better numpy compat.

**Comment by cpuhrsch** [comment]
@ngimel - Ideally we're pythonic in the sense of "one obvious way to do it", but I can also see that there's value in adding this feature for compatibility. I do worry though that we'll end up in a situation where people are doing the usual "masked out row" or "fully masked out" inputs and then run into gradient issues, which we're currently working on resolving via MaskedTensor.

**Comment by cpuhrsch** [comment]
@pearu - could you rebase?

**Comment by pearu** [comment]
@cpuhrsch rebase done.

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32070264).

**Pull request closed without merging**
