### PR TITLE
[AOTI] Unskipped test_scaled_dot_product_efficient_attention for ROCm

### PR DESCRIPTION
**Pull request by iupaikov-amd**
The test should no longer fail for ROCm.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by iupaikov-amd** [comment]
2 failing checks are due to a known issue with rocm CI

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
