### PR TITLE
Update header hipification logic for ROCm

### PR DESCRIPTION
**Pull request by jithunnair-amd**
This PR updates the header hipification logic as follows:
1. Update cuda_to_hip_mappings.py for CUDA headers
2. As a result of 1, a lot of additional include paths are rendered unnecessary for ROCm builds
3. Update "Header rewrite" logic in hipify_python.py script to hipify header includes for PyTorch extensions as well.

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
cc @jeffdaily

**Comment by jithunnair-amd** [comment]
Some build and test failures in ROCm builds not related to this PR. @pytorchbot retest this please

**Comment by jithunnair-amd** [comment]
@jeffdaily CI passed, except the caffe2 build which is due to the sccache error. Please review.

**Review by jeffdaily — APPROVED** [review]
LGTM

**Comment by jithunnair-amd** [comment]
Closing in favour of https://github.com/pytorch/pytorch/pull/45451.

**Pull request closed without merging**
