### PR TITLE
Delete NNPACK

### PR DESCRIPTION
**Pull request by ezyang**
Since we added cpuinfo as a vendored dependency, this created a problem
with our NNPACK integration, because NNPACK also depends on cpuinfo,
as per #6068.  This is particularly difficult to resolve because we
depend on a fairly recent version of cpuinfo, which we generally cannot
assume users have installed (it is submoduled.)  So, it would seem that
to fix this properly, NNPACK would have to be vendored and built against
the correct cpuinfo.

However, discussion with Christian Puhrsch and Marat Dukhan suggests
that the benefit of carrying on with NNPACK integration is not all that
great, because mkldnn has since come out with a CPU convolution implementation
that performs better than NNPACK.  NNPACK's x86 implementation is not
really maintained, and its ARM support is not really relevant to PyTorch.

So rather than go through all the rigamarole of vendoring NNPACK, better
to just delete it.  If you need good perf for CPU convolutions, please
make sure you build against mkldnn.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

CC @Maratyszcza

### CODE REVIEW

**Comment by cpuhrsch** [comment]
Looks good to me.

**Comment by Maratyszcza** [comment]
NNPACK for x86 is not actively optimized for performance, but it is maintained.

As for the conflict with cpuinfo, I have a better solution. PyTorch now has NNPACK and all its deps as submodules, it could just build them instead of using pre-installed version. NNPACK's CMakeLists has necessary precautions to not build or link `cpuinfo` twice.

**Comment by Maratyszcza** [comment]
@ezyang If building NNPACK with PyTorch when it is enabled sounds good to you, I'll create a PR.

**Comment by ezyang** [comment]
I think the primary issue whether or not we want to have users to build NNPACK by default when they do a source install of PyTorch. Back when Trevor was originally adding NNPACK integration, @soumith and I came to the conclusion that NNPACK should be conda packages. Maybe the calculation is different now that we have `third_party/NNPACK` for free.

@soumith do you think things are different now?

**Comment by cpuhrsch** [comment]
We also have to make sure that NNPACK will be well behaved with respect to pytorch.set_num_threads. I don't know how that has been done until now.

**Comment by Maratyszcza** [comment]
@cpuhrsch Right now it works only if PyTorch is built with OpenMP, but I can make it work in general.

**Comment by soumith** [comment]
i think we should focus on libraries that are active development. if nnpack is not actively worked upon for x86, i prefer to just keep mkldnn integration.

**Pull request merged**
