### PR TITLE
Torch package support in dynamo

### PR DESCRIPTION
**Pull request by voznesenskym**
Fixes #ISSUE_NUMBER

cc @mlazos @soumith @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by suo — APPROVED** [review]

**Comment by voznesenskym** [comment]
@malfet are these flaky tests failures? I had them on this PR earlier w/ static runtime tests on linux, but I reran and they passed lol.

**Comment by voznesenskym** [comment]
ahh wait no maybe real? `'module' object does not support item assignment`

**Comment by malfet** [comment]
> @malfet are these flaky tests failures? I had them on this PR earlier w/ static runtime tests on linux, but I reran and they passed lol.

They were quite consitent on trunk, see 
image

**Review by malfet — APPROVED** [review]

**Comment by suo** [comment]
you and lintrunner seem to be having a tough time lol. Ping me tomorrow and I can help debug

**Pull request closed without merging**
