### PR TITLE
Add `endpoint` argument in `linspace` to match numpy behavior

### LINKED ISSUE #70919: `linspace` should support an `endpoint` parameter
The [array API specification stipulates](https://data-apis.org/array-api/latest/API_specification/creation_functions.html#linspace-start-stop-num-dtype-none-device-none-endpoint-true) that `torch.linspace` should have a `endpoint: bool = True` parameter. If `False`, the right bound should be exclusive, i.e. `[start, end)` rather than `[start, end]`.

### PR DESCRIPTION
**Pull request by scaomath**
Fixes #70919

Basically I copied the line from `numpy`
https://github.com/numpy/numpy/blob/d35cd07ea997f033b2d89d349734c61f5de54b0d/numpy/core/function_base.py#L125

There is also a slight change in @lezcano 's implementation using `torch.where` to improve performance by 10% when the `steps` is an odd number.

I updated the docs as well and I am not sure if this is needed. @mruberry

### CODE REVIEW

**Review by lezcano — CHANGES_REQUESTED** [review]
This is the implementation used in torch.compile, but as CI shows, to modify this function you would need to modify its CPU and CUDA implementation withn ATen.

Now, about adding this to ATen, I think that should be alright when it comes to forward-compat, but I'm not sure about backward-compatibility... What are the current rules regarding adding new kwarg-only args @albanD? Is it alright to add it?

**Comment by scaomath** [comment]
@lezcano You mean here?

https://github.com/pytorch/pytorch/blob/c0d746c90e3f5f5699f32178f89c6c304e9df8b0/aten/src/ATen/native/TensorFactories.cpp#L722-L733

**Comment by lezcano** [comment]
There and all the way down until the C++ and CUDA implementations, yes. Let's get confirmation from Alban, see if it's alright to make this change to the public APi though.

**Comment by albanD** [comment]
Adding a new kwarg with a default value should be all good!
The default should be the current behavior of course

**Comment by lezcano** [comment]
@scaomath why the review?

**Comment by scaomath** [comment]
> @scaomath why the review?

@albanD said adding a kwarg with default being the current behavior is okay. You left a change request earlier. I thought you want to take a look at the change?

**Comment by lezcano** [comment]
This is changing the decomposition implementation, but it's missing adding the change to ATen (the C++, CUDA and other backends). The CI is all red for that reason.

**Comment by scaomath** [comment]
> This is changing the decomposition implementation, but it's missing adding the change to ATen (the C++, CUDA and other backends). The CI is all red for that reason.

By decomposition you mean the decorator used in front of the functions here:

https://github.com/pytorch/pytorch/blob/c4db6076079f23175fb7de63f346b083b1820bff/torch/_refs/__init__.py#L4920-L4922

Any idea what changes need to be made to ATen? `aten/src/ATen/native/TensorFactories.cpp` and `aten/src/ATen/native/RangeFactories.cpp` need to be changed accordingly.

**Comment by lezcano** [comment]
yes, you'll need to change those, add the relevant OpInfo tests and make sure that they pass

**Comment by scaomath** [comment]
Got it. Readingl the logs I see most fails point to `test_decomp.py` and `inductor/test_torchinductor_opinfo.py`? I assume every test relevant should be changed accordingly, how about the failed tests that are apparently not caused by this change?

**Comment by lezcano** [comment]
Those tests are failing because you changed the decomposition (which just affects `torch.compile` code) but you did not change the C++ and CUDA implementation (the eager mode).

No tests should be changed. If anything, you should add some samples to the relevant OpInfo to test this new behaviour

**Pull request closed without merging**
