### PR TITLE
Forward-mode AD support for torch.split, torch.split_with_sizes (#68566)

### PR DESCRIPTION
**Pull request by PaliC**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

Summary:

These are just auto-linear as pointed out by Jeffrey.

Test Plan: - Run OpInfo tests.

Reviewed By: albanD, soulitzer

Differential Revision: D32520239

Pulled By: zou3519

fbshipit-source-id: 807115157b131e6370f364f61db1b14700279789

### CODE REVIEW

**Comment by albanD** [comment]
The lint and CI needs to be fixed. The rest sounds good!

**Comment by soulitzer** [comment]
Why does this need to be relanded? @zou3519 do you know whats up?

**Comment by zou3519** [comment]
https://github.com/pytorch/pytorch/pull/68566 seems to have landed correctly. It was not reverted as far as I can tell

**Comment by soulitzer** [comment]
My guess that it is created by accident then. Closing for now.

**Pull request closed without merging**
