### PR TITLE
[xla hash update] update the pinned xla hash

### PR DESCRIPTION
**Pull request by clee2000**
Originally made this PR since xla was failing, but the PR that changed the pin got reverted, so this is just a normal update now

The old pin was ~2 weeks old?

Currently XLA is broken https://github.com/pytorch/pytorch/actions/runs/8438508272/job/23115239444

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by clee2000** [comment]
> Don't we have an automated job for that?

PR to fix https://github.com/pytorch/pytorch/pull/122630 qaq

**Review by JackCaoG — APPROVED** [review]

**Pull request closed without merging**
