### PR TITLE
introduce gain arg for kaiming initialisation

### LINKED ISSUE #54030: [FR] Configurable gain value for kaiming_normal_ / kaiming_uniform_ in torch.nn.init
## 🚀 Feature
Support fully-configurable gain values within `kaiming_normal_` / `kaiming_uniform_`.

## Motivation
The current implementations of [`kaiming_normal_`](https://github.com/pytorch/pytorch/blob/65087dd1d4c1e503281cd676e5563e9e64b2a926/torch/nn/init.py#L385) and [`kaiming_uniform_`](https://github.com/pytorch/pytorch/blob/65087dd1d4c1e503281cd676e5563e9e64b2a926/torch/nn/init.py#L350) rely on `calculate_gain()` to obtain the gain value used in init. 

In some cases (e.g. https://github.com/pytorch/pytorch/pull/53694), values outside of the defaults in `calculate_gain()` may be desired. To sidestep debates over the correct defaults, the gain value should be fully configurable by the user.

## Pitch

Deprecate the old `nonlinearity` arg and replace it with a `gain` arg. Shown below for `kaiming_normal_`, but the same would apply to `kaiming_uniform_` as well.

Old:
```python
import torch

linear = torch.nn.Linear(10, 5)

# Default gain value for specified nonlinearity is always used.
torch.nn.init.kaiming_normal_(linear.weight, nonlinearity='relu')
```

New:
```python
import torch

linear = torch.nn.Linear(10, 5)

# Use default gain value for specified nonlinearity.
torch.nn.init.kaiming_normal_(linear.weight, gain=torch.nn.init.calculate_gain('relu'))

# Use non-default gain value.
torch.nn.init.kaiming_normal_(linear.weight, gain=0.5)
```

## Alternatives

Leave as-is, requiring one of two workarounds:
1. If the desired gain value is the default for some nonlinearity, the user can use it by specifying that nonlinearity (e.g. with `nonlinearity='linear'`) when calling the init function. This workaround does not apply if the desired gain value is different from the defaults for all nonlinearities.
2. Re-implement the `kaiming_normal_` or `kaiming_uniform_` function with a different gain value

## Additional context

The [`xavier_normal_`](https://github.com/pytorch/pytorch/blob/65087dd1d4c1e503281cd676e5563e9e64b2a926/torch/nn/init.py#L314) and [`xavier_uniform_`](https://github.com/pytorch/pytorch/blob/65087dd1d4c1e503281cd676e5563e9e64b2a926/torch/nn/init.py#L287) functions in `torch.nn.init` already allow for fully configurable gain values.

### PR DESCRIPTION
**Pull request by mrTsjolder**
Fixes #54030

Introduces `gain` argument for `kaiming` initialisation and deprecates `a` and `nonlinearity`.

### CODE REVIEW

**Comment by mrTsjolder** [comment]
I guess this should do it. Tests should pass now.

@jbschlosser: Should the deprecation warning explicitly be tested for?

**Comment by mrTsjolder** [comment]
@jbschlosser @albanD This should be ready for review.

Two open questions:
 1. Should deprecation warnings be tested for?
 2. Should C++ API be updated as well?

**Comment by jbschlosser** [comment]
> @jbschlosser @albanD This should be ready for review.
> 
> Two open questions:
> 
> 1. Should deprecation warnings be tested for?
> 2. Should C++ API be updated as well?

@mrTsjolder:
1. I don't think deprecation warnings need to be tested for
2. Ideally yes, the C++ API should match python's behavior whenever possible

**Comment by mrTsjolder** [comment]
I must admit that I have little experience with c++ (and none with c++ docs generation), but I gave it a try.
I assume the doc generation fails due to the deprecation of the arguments, but I am not sure where/how to fix that.

**Pull request closed without merging**
