### PR TITLE
fix missing non-contiguous output handling for add op

### PR DESCRIPTION
**Pull request by wuxun-zhang**
patch for https://github.com/pytorch/pytorch/pull/104689 which is missing similiar handling for add op

cc @karthiknagasub

### CODE REVIEW

**Comment by wuxun-zhang** [comment]
@ezyang Could you please help review this? Thanks

**Review by karthiknagasub — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Comment by wuxun-zhang** [comment]
@ezyang I've fixed lint issue. Please have another look. Thanks.

**Pull request closed without merging**
