### PR TITLE
[FX] Add a default_value arg to Graph.placeholder and fix split_module

### PR DESCRIPTION
**Pull request by jamesr66a**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #71016

I found out that `split_module` doesn't preserve default values for arguments. In trying to fix that, I noticed that `Graph.placeholder` doesn't make it easy to add a default argument when making a placeholder. This PR addresses both of those issues

Differential Revision: [D33482218](https://our.internmc.facebook.com/intern/diff/D33482218)

### CODE REVIEW

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33482218).

**Review by ansley — APPROVED** [review]
LGTM

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33482218).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33482218).

**Pull request closed without merging**
