### PR TITLE
Upgrade CI to ROCm4.5.2

### PR DESCRIPTION
**Pull request by jithunnair-amd**
cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

### CODE REVIEW

**Comment by seemethere** [comment]
Just created the `pytorch-linux-bionic-rocm4.2-py3.6` repository on ECR so pushing should now work

**Comment by jithunnair-amd** [comment]
> Just created the pytorch-linux-bionic-rocm4.2-py3.6 repository on ECR so pushing should now work
Was the "4.2" a typo? I think the renaming of the job and docker tag to "4.5" worked, since the tag already existed? https://github.com/pytorch/pytorch/runs/4539974062?check_suite_focus=true

**Comment by jithunnair-amd** [comment]
@seemethere Although, it seems like I didn't do it the right way. Can you please help: https://github.com/pytorch/pytorch/runs/4539010974?check_suite_focus=true?

**Review by jeffdaily — APPROVED** [review]
LGTM.  new rocm 4.5 docker image built successfully.  ignore jenkins CI failure.

**Review by atalman — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
