### PR TITLE
update thresholds for various ops in functorch/test_ops.py

### PR DESCRIPTION
**Pull request by Fuzzkatt**
update thresholds for following ops:

linalg.multi_dot, pca_lowrank
matrix_exp
matmul, __rmatmul__

### CODE REVIEW

**Comment by zou3519** [comment]
@Fuzzkatt what is the motivation behind this PR?

**Review by ngimel — APPROVED** [review]

**Comment by Fuzzkatt** [comment]
> @Fuzzkatt what is the motivation behind this PR?

Upstreaming some fixes from the NVIDIA internal CI. Basically this set of PRs:
https://github.com/pytorch/pytorch/pull/102005
https://github.com/pytorch/pytorch/pull/102006
https://github.com/pytorch/pytorch/pull/102007
https://github.com/pytorch/pytorch/pull/102015
https://github.com/pytorch/pytorch/pull/102016

**Review by zou3519 — APPROVED** [review]
Fair enough

**Pull request closed without merging**
