### PR TITLE
ada lovelace (arch 8.9) support

### PR DESCRIPTION
**Pull request by gregjhogan**
changes required to be able to compile https://github.com/pytorch/vision and https://github.com/nvidia/apex for `sm_89` architecture

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
@gregjhogan in the future, when PR is approved you can merge it yourself using pytorchbot commands.

**Comment by sclarkson** [comment]
Might want to add Hopper / sm_90 support here while you're at it, as it is also included in CUDA 11.8.

**Comment by gregjhogan** [comment]
> Might want to add Hopper / sm_90 support here while you're at it, as it is also included in CUDA 11.8.

I thought about doing this, but I won't be able to test sm_90 support and I [found info that seemed to indicate sm_90 support actually requires CUDA 12.0](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/#:~:text=Hopper%20(CUDA%2012%20and%20later))

**Review by malfet — COMMENTED** [review]
[Edit] Ignore this, missed indents.

**Pull request closed without merging**
