### PR TITLE
Remove caffe2/

### PR DESCRIPTION
**Pull request by r-barnes**
Meta internal no longer syncs to caffe2/ and it is no longer a major thrust of development.

OSS tests have been disabled for caffe2/, so we don't know if changes to it are safe.

Let's remove it from master so we can focus on what's important: PyTorch.

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal @albanD

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]

**Review by bigfootjon — APPROVED** [review]
LGTM, Please make sure to coordinate with the pytorch releng oncall to have them skip this commit in Diff Train

**Review by malfet — APPROVED** [review]
If CI is green, lgtm, though you probably want to keep caffe2 building workflow (part of ciflow/trunk)

**Review by mikaylagawarecki — COMMENTED** [review]
I think serialization depends on [`caffe2/serialize/`](https://github.com/pytorch/pytorch/tree/main/caffe2/serialize) which seems to be deleted in this PR

**Review by Skylion007 — APPROVED** [review]

**Comment by albanD** [comment]
Thanks for making this!
Reviewing is pretty hard as the tab keeps crashing on me haha
But if CI is happy, I'm happy.
cc @seemethere for 1) is there any non-core tool that needs updating (builder, infra, stats tracking) 2) any special handling we want for this PR for internal merge?

**Review by eqy — APPROVED** [review]
would have saved me some work on recent cuDNN boilerplate if this was merged earlier ;)

**Review by PaliC — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Comment by kit1980** [comment]
> Meta internal no longer syncs to caffe2

Currently this makes https://github.com/pytorch/pytorch/pull/119639 non-importable.

**Review by thiagocrepaldi — COMMENTED** [review]
There are chunks of Caffe2 code on ONNX exporter too.

e.g. torch._C._onnx._CAFFE2_ATEN_FALLBACK

**Comment by cyyever** [comment]
Some CMake modules and options are used solely in Caffe2, they should be removed too.

**Comment by jeffdaily** [comment]
> Thanks for making this! Reviewing is pretty hard as the tab keeps crashing on me haha But if CI is happy, I'm happy. cc @seemethere for 1) is there any non-core tool that needs updating (builder, infra, stats tracking) 2) any special handling we want for this PR for internal merge?

I agree that this is hard to review.  Does it warrant breaking this up into smaller PRs?

**Comment by albanD** [comment]
Added suppress bc-linter since we expect these failures as they are from caffe2 files.

**Review by albanD — APPROVED** [review]
Looks pretty good now!

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
