### PR TITLE
changes to the documentation in support of quantization 

### PR DESCRIPTION
**Pull request by gottbrath**
this includes changes to 

docs/source/conf.py 
docs/source/index.rst
docs/source/nn.rst
docs/source/torch.rst

### CODE REVIEW

**Comment by gottbrath** [comment]
we probably want https://github.com/pytorch/pytorch/pull/27559 to land first then this.

**Review by jlin27 — COMMENTED** [review]
Looks good to me

**Review by jlin27 — APPROVED** [review]

**Review by jlin27 — APPROVED** [review]

**Comment by suo** [comment]
Reverting this as it has broken doc tests on master

**Comment by gottbrath** [comment]
Hmm .. perhaps I need to merge this after https://github.com/pytorch/pytorch/pull/27559

**Comment by gottbrath** [comment]
ok .. @suo the test is actually testing which functions are documented in the torch.rst file. These had gotten deleted, I think by accident, early in the process. I've added a new commit here that fixes it and I have verifed that the test now passes. 

Will wait for the CircleCI to complete and then import and land again.

**Comment by gottbrath** [comment]
gonna close this and replace it with https://github.com/pytorch/pytorch/pull/27679

**Pull request closed without merging**
