### PR TITLE
Add AT_DISPATCH_ALL_OPAQUE_TYPES

### PR DESCRIPTION
**Pull request by zasdfgbnm**
@ngimel Do you like this idea? If yes, I will open some follow-up PRs to migrate other ops to this dispatch macro.

### CODE REVIEW

**Comment by ngimel** [comment]
It looks cool, but it e.g. extends dispatch to complex and bool that are not dispatched for many ops, and it would probably increase binary size/ build time (complex64 will hide behind double, but complex128 will stick out)

**Comment by zasdfgbnm** [comment]
Is there any reason why these ops do not support complex and bool? I thought they should and it was just because nobody has worked on supporting it yet.

**Comment by ngimel** [comment]
No particular reason other than we don't have requests to support them, and they might increase binary size. If you could check that binary size/build time doesn't change much, that's fine I guess?

**Comment by zasdfgbnm** [comment]
Before:
```
$ du -s build/lib/libtorch_cuda.so
1650584	build/lib/libtorch_cuda.so
```
After:
```
$ du -s build/lib/libtorch_cuda.so
1652660	build/lib/libtorch_cuda.so
```
If we don't want to support all dtypes, I don't this PR has its value. This PR assumes we will support all dtypes for all these ops.

**Pull request closed without merging**
