### PR TITLE
implement bmm to support nested tensor and normal tensor

### PR DESCRIPTION
**Pull request by cascade812**
implement bmm to support nested and normal tensor

cc @cyyever @jbschlosser could you help review, thanks!

### CODE REVIEW

**Comment by cyyever** [comment]
I'm fine with this if the tests pass

**Comment by guijuzhang** [comment]
@cyyever I rebased and passed CI.

**Comment by guijuzhang** [comment]
@cyyever could you help review this pr? thanks a lot.

**Review by cyyever — APPROVED** [review]

**Comment by guijuzhang** [comment]
@colesbury  PR has been approved, may I know when this can be merged?

**Comment by colesbury** [comment]
@jbschlosser - can you take this on please? I'm not sure who needs to review PRs currently and I'm not familiar with the modified code.

**Comment by guijuzhang** [comment]
@colesbury this PR has been approved by cyyever for a while. How many approvals does it require to be merged? Just want to know how to proceed. Thanks！

**Comment by cyyever** [comment]
@colesbury I have no permission to merge..

**Review by ezyang — APPROVED** [review]

**Comment by guijuzhang** [comment]
@cyyever @ezyang do you know how to proceed and merge this PR?  failed tests seem to be unrelated with this PR.

**Pull request closed without merging**
