### PR TITLE
Enable misc clang-tidy checks

### PR DESCRIPTION
**Pull request by cyyever**
This PR enables the misc-XX checks in clang-tidy. Meanwhile, I excluded some of them that require a lot of code changes and have no immediate benefits. Some additional fixes and suppression were also given.

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by Skylion007** [comment]
Not sure how I feel about the blankit optin of misc checks, some are really misc and shouldn't probably be enabled. We will also have to be careful when upgrading (like we need the IWYU comments for misc-include-header check in the latest clang-tidy). 

Once that infra is in place though, automatically removing unused includes through clang-tidy/lintrunner would be a really nice benefit though!

**Pull request closed without merging**
