### PR TITLE
Remove hard-coded activation functions for transformer modules

### LINKED ISSUE #65622: Transformer modules should not hard-code the activation function
## 🚀 Feature
When passing a `str` to the `activation` argument, only `torch.nn.functional.relu` and `torch.nn.functional.gelu` activation functions are supported. The `activation` argument should be able to support any activation function defined in `torch.nn.functional`.

## Motivation

I want to be able to use the PyTorch Transformer `torch.nn.module`s with any activation function that is defined in PyTorch. Here is the list of `torch.nn.module`s:

- `torch.nn.Transformer`
- `torch.nn.TransformerEncoder`
- `torch.nn.TransformerEncoderLayer`
- `torch.nn.TransformerDecoder`
- `torch.nn.TransformerDecoderLayer`

The activation functions live in both `torch.nn` (e.g., `torch.nn.ReLU`, `torch.nn.SiLU`) and `torch.nn.functional` (e.g., `torch.nn.functional.relu`, `torch.nn.functional.silu`). Mathematically, any function which maps an input float `torch.Tensor` to an output `torch.Tensor` of the same shape that is defined in either of the above two namespaces (`torch.nn` and `torch.nn.functional`) should be supported.

## Pitch

Redefine `transformer.py:_get_activation_fn` as follows:

```python
def _get_activation_fn(activation):
    try:
        activation_fn = getattr(torch.nn.functional, activation)
    except AttributeError:
        try:
            activation_fn = getattr(torch.nn, activation)()
        except AttributeError:
            raise TypeError(f'Activation function {activation} is not defined in neither `torch.nn` nor `torch.nn.functional`')
    return activation_fn
```

## Alternatives

 - Create a dedicated module for activation functions and have `_get_activation_fn` interact with that
 - Hard-code the list of activation function names supported as opposed to using `getattr`
 - Instead of passing in a string `activation` to one of the above `torch.nn.module`s, pass in an activation function that has already been instantiated.

## Additional context

A major part of model development, performance tuning, experimentation, etc. is trying different activation functions. Often, a model is part of a larger system such as a hyperparameter tuner which compares activation functions. No hacking should be necessary to achieve this functionality.

Furthermore, as the field of machine learning matures, new activation functions will be discovered. This feature ensures forward-compatibility as long as PyTorch supports those new activation functions.

### PR DESCRIPTION
**Pull request by markrogersjr**
Fixes #65622

### CODE REVIEW

**Comment by jbschlosser** [comment]
Hey @markrogersjr, as I mentioned on the issue, this was already addressed in #61355

**Comment by markrogersjr** [comment]
@jbschlosser Actually, #61355 does not resolve #65622, and I really don't the fact that you did not carefully read the issue. I need some oversight from @albanD @soumith @ptrblck @ezyang @gchanan @apaszke or others

**Comment by albanD** [comment]
Hi,

I think he considered it closed because you can already pass any callable you want. This is more general and doesn't rely on magic strings.
I am not sure we really need to support all the possible string arguments here as it adds complexity without any new feature.
Am I missing something here?

**Comment by markrogersjr** [comment]
@albanD please see discussion on #65622, I make a case for why we should continue to support strings.

**Pull request closed without merging**
