### PR TITLE
[inductor] Minor fix of addmm shape padding

### PR DESCRIPTION
**Pull request by jiawenliu64**
Summary: Minor fix of addmm shape padding

Test Plan: CI

Differential Revision: D42855212

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by ezyang** [comment]
M2M100ForConditionalGeneration MobileBertForMaskedLM failed accuracy on this PR on master, though I see that on the CI run they were fine. Just a heads up

**Comment by ezyang** [comment]
oh, the passed on two subsequent commits, must be a flake

**Pull request closed without merging**
