### PR TITLE
Port `cumprod` kernel to structured kernels.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#61899 Port `cumprod` kernel to structured kernels.**
* #61842 Port `cumsum` kernel to structured kernels.

Tracking issue: #55070

This PR also removes `at::_cumprod`, which was the "backend" for `at::cumprod`.

Differential Revision: [D29939489](https://our.internmc.facebook.com/intern/diff/D29939489)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29939489).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29939489).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29939489).

**Comment by ysiraichi** [comment]
The CI failure does not seem to be related to this PR (not sure about the Facebook internal tests, though).

**Pull request closed without merging**
