### PR TITLE
[aotinductor] Avoid generating redundant kernel loading code

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #110510

Summary: 1) Stop forcing triton.unique_kernel_names to True for AOTInductor, because the unique kernel name can be read from metadata; 2) Only generate load_kernel once for each kernel since we don't have control flow in our generated code.  This solves https://github.com/pytorch/pytorch/issues/105553.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by chenyang78 — APPROVED** [review]
LGTM. Thanks.

**Review by jansel — APPROVED** [review]

**Comment by eellison** [comment]
Flagging that this caused aot_inductor regression in last day

**Comment by huydhn** [comment]
@pytorchbot drci

(Please ignore this comment, I'm testing Dr.CI)

**Pull request closed without merging**
