### PR TITLE
Updating sleef submodule to eb3d97785 to fix export errors

### LINKED ISSUE #119952: Building via FetchContent and exporting via install results in missing "sleef" target
### 🐛 Describe the bug

Building pytorch v2.2.0 via FetchContent, and attempting to setup an export set via CMake install, results in missing target "sleef". 

Upon investigating, I can see that the version of sleef currently pinned in pytorch's submodule is slightly older than hash that contains this fix: https://github.com/shibatch/sleef/pull/412

We are currently pinned to a hash from Dec 21, 2020.
We need to update to a hash from Mar 11, 2021.

### Error logs

CMake Error: install(EXPORT "Caffe2Targets" ...) includes target "torch_cpu" which requires target "sleef" that is not in any export set.

### Minified repro

_No response_

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 14.1.2 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.28.0
Libc version: N/A

Python version: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] (64-bit runtime)
Python platform: macOS-14.1.2-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.2.0a0+git7e6cf04
[conda] Could not collect

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

### PR DESCRIPTION
**Pull request by anthonyalayo**
Fixes #119952 with submodule updates

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by anthonyalayo** [comment]
cc @malfet who last updated this dependency

**Comment by anthonyalayo** [comment]
I just tested this with my project, worked like a charm.

**Review by ezyang — DISMISSED** [review]

**Comment by anthonyalayo** [comment]
I'm checking out those build errors, I didn't see those on my local (clang 15, arm64 OSX)
```
In file included from /var/lib/jenkins/workspace/aten/src/ATen/cpu/vec/vec256/vec256.h:12,
                 from /var/lib/jenkins/workspace/aten/src/ATen/cpu/vec/vec.h:6,
                 from /var/lib/jenkins/workspace/aten/src/ATen/cpu/vec/functional_base.h:6,
                 from /var/lib/jenkins/workspace/aten/src/ATen/cpu/vec/functional.h:3,
                 from /var/lib/jenkins/workspace/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp:12,
                 from /var/lib/jenkins/workspace/build/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.AVX2.cpp:1:
/var/lib/jenkins/workspace/aten/src/ATen/cpu/vec/vec256/vec256_bfloat16.h: In instantiation of ‘at::vec::AVX2::Vectorized<T> at::vec::AVX2::Vectorized16<T>::log() const [with T = c10::BFloat16]’:
/var/lib/jenkins/workspace/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp:142:3:   required from here
/var/lib/jenkins/workspace/aten/src/ATen/cpu/vec/vec256/vec256_bfloat16.h:482:16: error: invalid conversion from ‘__m256 (*)(__m256)’ to ‘const __m256 (*)(__m256)’ [-fpermissive]
  482 |     return map(Sleef_logf8_u10);
      |                ^~~~~~~~~~~~~~~
      |                |
      |                __m256 (*)(__m256)
```

Most likely due to `-fpermissive` not affecting my build environment. First i'm going to try it on gcc 10 since I have that readily available.

**Comment by anthonyalayo** [comment]
alright that should fixed everything, should be good for another merge attempt in the morning @ezyang

**Comment by anthonyalayo** [comment]
Those errors are unrelated @ezyang

**Comment by anthonyalayo** [comment]
Can we start the merge on this again @ezyang ?

**Comment by anthonyalayo** [comment]
cc @malfet for the merge, hoping to get this in before it's stale

**Comment by anthonyalayo** [comment]
@atalman can I get more details about how it failed after merge? That test was passing before merge.

**Comment by atalman** [comment]
@anthonyalayo : This is the failure: https://github.com/pytorch/pytorch/actions/runs/7913413809/job/21611696506#step:12:1824 It showed up as flaky on the PR. However it does not look like flaky. The two failures you can also see here : https://hud.pytorch.org/hud/pytorch/pytorch/main/1?per_page=50&name_filter=inux-focal-c

**Comment by anthonyalayo** [comment]
Thanks @atalman taking a look

**Pull request closed without merging**
