### PR TITLE
[Dist profiling] Fix ProcessGroupNCCL collective profiling

### PR DESCRIPTION
**Pull request by rohan-varma**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #56840 Clang format ProcessGroupNCCL.cpp
* #56427 [c10d] Profiler support for nccl p2p collectives
* #56216 [Dist profiling] Enable tests for dist profiling with torch.profiler
* **#55204 [Dist profiling] Fix ProcessGroupNCCL collective profiling**
**
closes https://github.com/pytorch/pytorch/issues/48987
Implements a fix discussed offline with @pritamdamia87 to run end callbacks after CUDAFuture's wrapCallback has ensured appropriate synchronization. Also enables the relevant distributed profiling tests that were previously disabled for ProcessGroupNCCL.
Note that the profiling infrastructure has moved to primarily encourage the use of torch.profiler and CUPTI to trace CUDA kernels, support for distributed collectives for that will require further discussion with @ilia-cher. However, this PR improves the usability of torch.autograd.profiler with respect to distributed collectives.
Differential Revision: [D27491711](https://our.internmc.facebook.com/intern/diff/D27491711/)

### CODE REVIEW

**Comment by pritamdamania87** [comment]
> Note that using the profiler with use_cuda=True to profile distributed collectives isn't really an intended use case however, see the discussion in #52246. The profiling infrastructure has moved to primarily encourage the use of torch.profiler and CUPTI to trace CUDA kernels, support for distributed collectives for that will require further discussion with @ilia-cher, but we should still resolve this deadlock.

Just a few questions here since I haven't followed the profiler changes closely:

1. What would happen if we try to profile distributed collectives with `use_cuda=True`?
2. I thought most of the profiler changes involved moving the autograd profiler to the top level and using kineto, as a result shouldn't any changes we make for supporting distributed collectives carry over?
3. Are there any differences between `torch.autograd.profiler` and `torch.profiler` today?

**Comment by rohan-varma** [comment]
> 1. What would happen if we try to profile distributed collectives with `use_cuda=True`?

Today, this works (i.e. reports accurate timing) for gloo/mpi backends, but deadlocks with nccl backend, which this PR resolves. However even with this fix, the timings will be incorrect for NCCL backend because we mark the nccl future as completed immediately after enqueueing the collective work (so only the host-side time taken to call the collective is accurate). Per the discussion in #52246, it seems that the best way forward is to fix this by the move to `torch.profiler`. The reason for this diff though is that we should at least not deadlock when users try to profile nccl collectives with `use_cuda=True`, and probably print a warning somewhere saying this isn't supported. 

> 2. I thought most of the profiler changes involved moving the autograd profiler to the top level and using kineto, as a result shouldn't any changes we make for supporting distributed collectives carry over?

I think they should carry over for the most part, but I haven't gotten a chance to test yet with `torch.profiler`. We also have plans to sync with @ilia-cher to understand any changes required from our side to support distributed profiling with torch.profiler at the same/better level than what we currently have with torch.autograd.profiler.

> 3. Are there any differences between `torch.autograd.profiler` and `torch.profiler` today?

Per https://pytorch.org/docs/stable/profiler.html, using the profiler seems to be quite similar, although implementation wise, I'm not completely sure - I know that `torch.autograd.profiler`'s C++ backend is now backed by legacy_profiler.cpp, and I'm not sure how much the two backends share in common. cc: @ilia-cher

**Comment by rohan-varma** [comment]
cc @pritamdamania87 @ilia-cher

**Comment by ilia-cher** [comment]
Checked the PR, my observation is that it basically should equally work for the profiler irregardless of whether this is the older implementation or the newer one. The PR affects the way you run your record function end callback, and the new profiler also uses the callbacks like the legacy one.

The difference between old and new is that, when profiling with CUDA enabled with new profiler, you should see actual CUDA kernels, in addition to the operator/record_function events; in the old implementation you'd see operator and record_function events, but CUDA information was limited, it wouldn't show actual CUDA kernels, but use CUDA events api to compute their approximate timings.

There was an issue in the older profiler (setting CUDA events on all GPUs from a single process), which caused issues, this bug should be already fixed in https://github.com/pytorch/pytorch/issues/48987. It shouldn't be an issue in the new profiler because it doesn't use CUDA events api, but uses CUPTI.

So, all in all, it seems this is orthogonal to new vs old profiler. The code LG but I'll leave it up to some from the distributed team to take one more look and stamp.

**Comment by rohan-varma** [comment]
> The difference between old and new is that, when profiling with CUDA enabled with new profiler, you should see actual CUDA kernels, in addition to the operator/record_function events; in the old implementation you'd see operator and record_function events, but CUDA information was limited, it wouldn't show actual CUDA kernels, but use CUDA events api to compute their approximate timings.
> 
> There was an issue in the older profiler (setting CUDA events on all GPUs from a single process), which caused issues, this bug should be already fixed in #48987. It shouldn't be an issue in the new profiler because it doesn't use CUDA events api, but uses CUPTI.

Yep, we are able to see the event traces collected by CUPTI with the new profiler (example shown in the next diff in this stack), so it seems like things work as expected with the new profiler as well (besides the internal issue which we discussed offline).

**Review by mrshenli — APPROVED** [review]
The usage on CUDAFuture looks correct to me. 

Just wanna make sure I understand this correctly. The callback will be run when CUDA ops are inserted into streams and streams are correctly synchronized, but it's possible that the CUDA ops generating the parent Future's value might not finish execution yet. I guess this is a sufficient guarantee for profiler because the profiler will use CUDA events in `recordFunctionEndCallback_`. Is that correct?

**Comment by rohan-varma** [comment]
> but it's possible that the CUDA ops generating the parent Future's value might not finish execution yet. I guess this is a sufficient guarantee for profiler because the profiler will use CUDA events in `recordFunctionEndCallback_`. Is that correct?

Yes, this is true for `torch.autograd.profiler`, but actually the new torch.profiler uses Kineto when enabled with `ProfilerActivity.CUDA` and can directly capture CUDA kernel events (including NCCL kernels). So this diff is mainly to ensure proper support with the old torch.autograd.profiler but the recommended way (after torch.profiler is the default in 1.9) will be to use torch.profiler + kineto.

**Pull request closed without merging**
