### PR TITLE
[inductor] show more kernel specific metrics in the benchmark result

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96249
* #96458

Show the following kernel specific metrics in the kernel benchmark:
- shared memory used
- number of registers used
- number of spills.

Depends on https://github.com/openai/triton/pull/1296 

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by Chillee** [comment]
Hmm... I think we might need a way to config what info is shown for each kernel 🤔 I'm not sure we always want this info?

**Comment by shunting314** [comment]
> Hmm... I think we might need a way to config what info is shown for each kernel 🤔 I'm not sure we always want this info?

yea, I'll add an option to control those kernel details in the output

**Comment by shunting314** [comment]
Add an option '--no-show-kernel-detail' to skip kernel details in the output. By default we will print kernel details.

Example, run the compiled module as follows:
```
$ python /tmp/torchinductor_shunting/r2/cr2c7vsrhelrsysuhhaxymx23kqqge4wr7tnb7enkr62t6b6se74.py -kc --no-show-kernel-detail
None                 c74fo2dzk7
   0.007ms     0.000GB        0.01GB/s @ XBLOCK: 8, num_warps: 1, num_stages: 1
```
Screenshot 2023-03-08 at 11 36 52 AM

**Comment by Chillee** [comment]
@shunting314 I don't think we need a flag necessarily. I think we should just turn it on when benchmarking kernels and not with the TORCHINDUCTOR_PROFILE path.

**Comment by Chillee** [comment]
> The API will make printing kernel detail optional

Yeah that would be nice. Also, I'm wondering if you'll have some issues landing this since you need a corresponding Triton bump.

**Comment by Chillee** [comment]
It would be good to add a test for this stuff though, just to make sure they don't get broken by a random change.

**Comment by shunting314** [comment]
> It would be good to add a test for this stuff though, just to make sure they don't get broken by a random change.

yea, will add one

**Review by Chillee — APPROVED** [review]

**Comment by shunting314** [comment]
Duo to some merge issue (partially because of the diff train sev) I have to reland this as https://github.com/pytorch/pytorch/pull/96461 . Sorry for the trouble

**Pull request closed without merging**
