### PR TITLE
Port GatedLinearUnit forward to TensorIterator.

### PR DESCRIPTION
**Pull request by gchanan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#26687 Port GatedLinearUnit forward to TensorIterator.**
* #26410 glu: port cpu forward implementation to ATen

This involves:
1) Porting GatedLinearUnit CPU from ATen to TensorIterator
2) Porting GatedLinearUnit CUDA from THNN to TensorIterator.

Differential Revision: [D17539477](https://our.internmc.facebook.com/intern/diff/D17539477)

### CODE REVIEW

**Review by VitalyFedyunin — APPROVED** [review]
Please attach before/after benchmark numbers.

**Comment by gchanan** [comment]
I'm trying to use a new benchmark system, so benchmarks might take a bit longer than the usual timeit.

**Comment by XiaobingSuper** [comment]
#24571 Migrate glu from the TH to Aten (CUDA)
#24572 Migrate glu_backward from the TH to Aten (CUDA)
#24707 Migrate glu from the TH to Aten (CPU)
 #24708 Migrate glu_backward from the TH to Aten (CPU)

**Comment by XiaobingSuper** [comment]
@gchanan. do you have any progress about it?

**Pull request closed without merging**
