### PR TITLE
Add OpenSSF Scorecard Action

### LINKED ISSUE #85159: Add the OpenSSF Scorecards GitHub Action
## Issue description

Hello, I'm working on behalf of Google and the [OpenSSF][ossf] to help essential open-source projects improve their supply-chain security. The OpenSSF is a non-profit foundation backed by the Linux Foundation, dedicated to improving the security of the open-source community. It counts both GitHub and Facebook as [members][ossf-membership].

Due to PyTorch's importance in the Python ML landscape, the OpenSSF has included it to its list of the 100 most critical open-source projects. Given the volumes of frequently sensitive information consumed by applications reliant on PyTorch, the OpenSSF wants to help harden the project's supply-chain.

To this end, the OpenSSF has designed the [Scorecard][sc] system, which combines dozens of automated checks to let maintainers better understand their project's supply-chain security posture. There is also the [Scorecard GitHub Action][sc-gha], which adds the results of its checks to the project's [security dashboard](https://github.com/pytorch/pytorch/security), as well as suggestions on how to solve any issues (see examples below). This Action has been adopted by 1600+ projects already, including TensorFlow.

Would you be interested in a PR which adds this Action? Optionally, it can also publish your results to the OpenSSF REST API, which allows a [badge][badge] with the project's score to be added to its README.

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[ossf]: https://openssf.org/
[ossf-membership]: https://openssf.org/about/members/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

cc @seemethere @malfet @pytorch/pytorch-dev-infra

### PR DESCRIPTION
**Pull request by pnacht**
Closes #85159

As per the linked issue, this PR adds the OpenSSF Scorecards GitHub Action, which automatically checks the repo's supply-chain security processes and reports results to the repo's Security dashboard.

This current version of the workflow has the `id-token : write` permission. This is necessary in order to publish results to a public REST API the OpenSSF makes available for consumers to check participating projects' results. Naturally, if you'd rather not publish these results, I can modify the workflow to remove this behavior.

The Action has an associated optional badge which can be added to the repo's README. However, given how PyTorch avoids badges, I have naturally not included it. (Let me know if you want it!)

@malfet

### CODE REVIEW

**Comment by pnacht** [comment]
I can rename it and add workflow dispatch, no problem.

**Review by malfet — APPROVED** [review]
Ok, let's give it a try

**Comment by pnacht** [comment]
@malfet I'm not sure what's causing the check failures. Seems to be a CUDA test? Anything I can do?

**Review by huydhn — APPROVED** [review]

**Comment by huydhn** [comment]
> @malfet I'm not sure what's causing the check failures. Seems to be a CUDA test? Anything I can do?

It's an unrelated flaky issue.  Let me force merge this

**Pull request closed without merging**
