### PR TITLE
Make it so you cannot call THPModule_disable_torch_function directly

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #64693
* #64689

See https://github.com/pytorch/pytorch/issues/64690 for an explanation

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D30816569](https://our.internmc.facebook.com/intern/diff/D30816569)

### CODE REVIEW

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30816569).

**Comment by albanD** [comment]
CI failure looks valid no?

**Comment by ezyang** [comment]
yeah looks like we gotta look more

**Comment by ezyang** [comment]
The failure here arises from UninitializedTensorMixin which gets mixed with Parameter:

```
    @classmethod
    def __torch_function__(cls, func, types, args=(), kwargs=None):
        # method-wrapper is to detect access to Tensor properties that are
        # wrapped in descriptors
        if func in cls._allowed_methods or func.__class__.__name__ == 'method-wrapper':
            if kwargs is None:
                kwargs = {}
            return super().__torch_function__(func, types, args, kwargs)
        raise ValueError(
            'Attempted to use an uninitialized parameter in {}. '
            'This error happens when you are using a `LazyModule` or '
            'explicitly manipulating `torch.nn.parameter.{}` '
            'objects. When using LazyModules Call `forward` with a dummy batch '
            'to initialize the parameters before calling torch functions'.format(func, cls.__name__))
```

super refers to Parameter in this MRO. Not sure what to think about this.

**Comment by ezyang** [comment]
We're not going to do this. See https://github.com/pytorch/pytorch/issues/64690#issuecomment-919326886 for new plan

**Pull request closed without merging**
