### PR TITLE
Add total GPU memory utilization

### PR DESCRIPTION
**Pull request by huydhn**
Although we already have per process GPU memory usage, I'm curious to see what is the number for `gpu_utilization.memory` per https://docs.nvidia.com/deploy/nvml-api/structnvmlUtilization__t.html.  Also fixing a tiny typo issue that has been bugging me for a while `total_gpu_utilizaiton`

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Is it equivalent to https://github.com/pytorch/pytorch/issues/50722? But it seems that that PR used cuda_get_mem_info. Is nvml solution here preferable for gathering global device memory stats?

**Review by ZainRizvi — APPROVED** [review]

**Comment by huydhn** [comment]
> Is it equivalent to #50722? But it seems that that PR used cuda_get_mem_info. Is nvml solution here preferable for gathering global device memory stats? if so, maybe an interface to it should be actually user-facing

While #50722 aims at surfacing the memory usage to PyTorch users, this PR to use NVML is for monitoring CI runners when running CUDA tests.  So they have different goals in mind and, from what I see, both are needed.  To give a bit of a context, we are building a tool to monitor GPU usage when running CUDA tests on our CI infra to prevent a family of GPU-related issues like OOM

**Comment by vadimkantorov** [comment]
I'm meaning it's useful to have some (maybe pytorch-independent) recipes for measuring current process's GPU memory for similar perf benchmarking purposes as in this PR (to include any other frameworks allocated memory or memory allocated natively outside of pytorch allocator). Currently, there are problems with PIDs within docker not matching by default PIDs tracked by the driver and NVML: https://github.com/NVIDIA/nvidia-docker/issues/179.

One solution is to add `--pid=host` to `docker run` command, but this is very unintuitive, so if it's possible to workaround, a solution for getting GPU memory stats for a given process / current process would be nice to have (especially if it's possible to match PIDs without having to set `--pid=host` to which the user may not have access) at least as a form of recipe / code snippet / tutorial in PyTorch docs

**Pull request closed without merging**
