### PR TITLE
Add diagflat complex support

### LINKED ISSUE #47499: diagflat not implemented for Complex type
## 🐛 Bug

[`torch.diagflat`](https://pytorch.org/docs/master/generated/torch.diagflat.html) isn't implemented for complex types (`torch.complex32`, `torch.complex64`, `torch.complex128`).
This holds for CPU and CUDA.

## To Reproduce

``` python
>>> import torch
>>> a = torch.ones(1, dtype=torch.complex128)
>>> torch.diagflat(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "diag" not implemented for 'ComplexDouble'

# CUDA
>>> b = a.cuda()
>>> torch.diagflat(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "diag_cuda" not implemented for 'ComplexDouble'
```

## Expected behaviour

- For a 1D Tensor, creates a (Complex) Tensor with the input elements on the diagonal (zeros elsewhere).
- For >1D, flattens to 1D and creates a Tensor with input elements on the diagonal. Analogous to `torch.diagflat(x.flatten())`.

## Environment

 - PyTorch Version (e.g., 1.0): torch-1.8.0.dev20201105
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip nightly
 - Build command you used (if compiling from source):
 - Python version: v3.8.5
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: GTX 970
 - Any other relevant information:

cc @ezyang @anjali411 @dylanbespalko @mruberry

### PR DESCRIPTION
**Pull request by rjkilpatrick**
Adds complex numbers support for `torch.diag`
``` python
>>> import torch
>>> a = torch.ones(2, dtype=torch.complex128)
>>> torch.diagflat(a)
tensor([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]], dtype=torch.complex128)
>>> b = a.cuda()
>>> torch.diagflat(b)
tensor([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]], device='cuda:0', dtype=torch.complex128)
```

Note that automatic differentiation isn't implemented:
``` python
>>> d = torch.ones(1, dtype=torch.complex128, requires_grad=True)
>>> torch.diagflat(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: diag does not support automatic differentiation for outputs with complex dtype.
```

Fixes #47499

### CODE REVIEW

**Comment by anjali411** [comment]
@rjkilpatrick is this PR ready for review?

**Comment by rjkilpatrick** [comment]
@anjali411 this issue is ready to be reviewed.

The complex autograd should be a separate issue.

**Comment by heitorschueroff** [comment]
@albanD can you please advise whether we can leave autograd support for a later PR?

**Comment by anjali411** [comment]
`torch.diagflat` calls `torch.diag` so it's ok to not add autograd support for `torch.diagflat` in this PR. let's add that in a follow-up PR

**Review by anjali411 — APPROVED** [review]
lgtm

**Comment by albanD** [comment]
@anjali411  the autograd should be disabled anyways as it is not in the whitelist right?

**Comment by anjali411** [comment]
@albanD `diagflat` calls `diag` whose backward uses `diagonal` which is supported for complex

**Pull request closed without merging**
