### PR TITLE
Enable ninja installation for ROCm

### PR DESCRIPTION
**Pull request by BLOrange-AMD**
This PR specifies NINJA_VERSION for the explicit ROCm CI configs (missed in https://github.com/pytorch/pytorch/pull/87505)

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]

**Review by pruthvistony — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@BLOrange-AMD It looks like your local workflow is ending up inadvertently changing the permissions of files when you file a PR. I just addressed it for this PR in this commit: https://github.com/pytorch/pytorch/pull/85763/commits/318746ffce9d47e93fc7f0073f5e83b0df00a683

**Comment by jithunnair-amd** [comment]
@BLOrange-AMD Can you please do a manual rebase?

**Comment by pruthvistony** [comment]
cc @malfet ,
Can you please help in review.

**Review by malfet — APPROVED** [review]

**Comment by pruthvistony** [comment]
Change pushed through another PR. Hence closing this PR.

**Pull request closed without merging**
