### PR TITLE
[BC-Breaking] Remove redundant fsdp prefix

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #73791

Differential Revision: [D34645228](https://our.internmc.facebook.com/intern/diff/D34645228)

### CODE REVIEW

**Review by zhaojuanmao — APPROVED** [review]

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34645228).

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34645228).

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34645228).

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34645228).

**Pull request closed without merging**
