### PR TITLE
Move jit test order from beginning to right before multiprocessing.

### PR DESCRIPTION
**Pull request by gchanan**
These fail more frequently than others and block information about whether basic functionality is working or not.

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Review by killeent — APPROVED** [review]
I guess the real problem is the multiprocessing tests are flaky :|

**Review by apaszke — APPROVED** [review]
We might also want to make it such that we always run all tests in CI even if some fail

**Comment by gchanan** [comment]
yes, we should run all the tests.  But you'd still want the failed tests in a nice order :).

**Comment by ezyang** [comment]
When we were working on the new CI, Pietern mentioned that if you use pytest, you can get machine readable test output and have Jenkins display it, which would solve the "failed test rendering problem." I looked at doing this very briefly, but the problem is that `run_test.sh` dispatches some tests multiple times with different environment variables `MULTIPROCESSING_METHOD=spawn python test_multiprocessing.py` and I am not actually familiar enough pytest to know if achieving this is actually possible.

**Pull request merged**
