### PR TITLE
Refactor c10::DataPtr by subclassing from c10::detail::UniqueVoidPtr

### PR DESCRIPTION
**Pull request by cyyever**
That seems more reasonable and saves lots of delegated code.

### CODE REVIEW

**Comment by ezyang** [comment]
Meh. If you are going to do this at minimum it should be private inheritance so you don't open up the possibility of slicing

**Comment by cyyever** [comment]
Using private inheritance means it still requires lots of boilerplate code to forward method calls, the same as before.

**Comment by ezyang** [comment]
But public inheritance means that UniqueVoidPtr is convertible from DataPtr, which is undesirable.

**Comment by cyyever** [comment]
Convert UniqueVoidPtr to DataPtr is not allowed, but the DataPtr to UniqueVoidPtr is allowed. In essence, DataPtr is just UniqueVoidPtr + device and all methods except constructors are defined in UniqueVoidPtr.

**Pull request closed without merging**
