### PR TITLE
`gcd`: port to structured

### PR DESCRIPTION
**Pull request by Freey0**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #57630 Port maximum and minimum to structured
* #57629 Port logaddexp and logaddexp2 to structured
* #57628 Port lcm to structured
* #57627 Port hypot to structured
* #57626 Port igamma and igammac to structured
* #57625 Port nextafter to structured
* **#57624 Port gcd to structured**

Differential Revision: [D28224832](https://our.internmc.facebook.com/intern/diff/D28224832)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28224832).

**Comment by Freey0** [comment]
A related question.
Functions like gcd, nextafter ... these functions only support some input types, and the current implementation throws unsupported errors via AT_DISPATCH_XX_TYPES in xx_stub.
```
void gcd_kernel(TensorIteratorBase& iter) {
  AT_DISPATCH_INTEGRAL_TYPES(iter.dtype(), "gcd_cpu", [&]() {
      cpu_kernel(
          iter,
          [](scalar_t a, scalar_t b) -> scalar_t {
            return calc_gcd(a, b);
          });
    });
}
```
```
#define AT_DISPATCH_INTEGRAL_TYPES(TYPE, NAME, ...)                         \
  [&] {                                                                     \
    const auto& the_type = TYPE;                                            \
    /* don't use TYPE again in case it is an expensive or side-effect op */ \
    at::ScalarType _st = ::detail::scalar_type(the_type);                   \
    RECORD_KERNEL_FUNCTION_DTYPE(NAME, _st);                                \
    switch (_st) {                                                          \
      AT_PRIVATE_CASE_TYPE(NAME, at::ScalarType::Byte, uint8_t, __VA_ARGS__)      \
      AT_PRIVATE_CASE_TYPE(NAME, at::ScalarType::Char, int8_t, __VA_ARGS__)       \
      AT_PRIVATE_CASE_TYPE(NAME, at::ScalarType::Int, int32_t, __VA_ARGS__)       \
      AT_PRIVATE_CASE_TYPE(NAME, at::ScalarType::Long, int64_t, __VA_ARGS__)      \
      AT_PRIVATE_CASE_TYPE(NAME, at::ScalarType::Short, int16_t, __VA_ARGS__)     \
      default:                                                              \
        AT_ERROR(#NAME, " not implemented for '", toString(_st), "'");      \
    }                                                                       \
  }()

```

The metafunctions ported this way do not check for correct input types, the CI can pass because the tests only test for supported types.

```
    @onlyOnCPUAndCUDA
    @dtypes(torch.uint8, torch.int8, torch.int16, torch.int32, torch.int64)
    def test_gcd(self, device, dtype):
```

Any ideas would be greatly appreciated! @ezyang

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28224832).

**Comment by ezyang** [comment]
Good question. A somewhat distasteful answer is to add "check" variants of `AT_DISPATCH_INTEGRAL_TYPES` which don't redispatch, but just check that the dtype is appropriate and raise the error if it is not supported. This is somewhat distasteful because (1) that's gonna to be a bunch of copy pasting in the macros and we have to keep them in sync, and (2) it's going to be slower than what we did before, since you're banging on dtype twice. I filed an issue about this at https://github.com/pytorch/pytorch/issues/57742

I don't have a big problem if you want to "hush hush" commit a bug here because the CI coverage is not quite enough. We can also just suppress these meta tests with an expected failure and file an issue to fix this later. If you want to do the right thing, I think adding check variants is the only easy thing to do, but we'll need to get some other feedback on it (cc @gchanan).

**Pull request closed without merging**
