### PR TITLE
[caffe2] Add Winograd Conv method for CPU

### PR DESCRIPTION
**Pull request by wuhuikx**
Add winograd conv method. Users can select the direct conv or winograd conv in the model file.
We close the origin pr https://github.com/pytorch/pytorch/pull/12154 and create this new one for better rebasing.

### CODE REVIEW

**Comment by wuhuikx** [comment]
@yinghai @jgong5

**Review by yinghai — CHANGES_REQUESTED** [review]
```
Summary: 
caffe2/caffe2/ideep/operators/conv_op.cc:53:39: error: no matching member function for call to 'expected_weights_descriptor'
          ideep::convolution_forward::expected_weights_descriptor(
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Needs newer version of IDEEP?

**Comment by wuhuikx** [comment]
> @yinghai @jgong5

Yes, based on the newer ideep. But the newer ideep is already merged into pytorch/master, so the build and 60 checks can be passed.

**Comment by yinghai** [comment]
@jgong5 I see the problem. Our internal repo only syncs with ideep/master branch. And in OSS, the ideep tp module points to a separate branch. Any plans to merge those into your master branch?

**Comment by gottbrath** [comment]
What is the status on this. @yinghai  -- I think there was a question for you here.

**Review by yinghai — APPROVED** [review]
LGTM. Could you rebase to current master?

**Comment by yinghai** [comment]
@gottbrath I cannot just merge this as they use a non-master branch for integration. It needs some internal work to get it merged.

**Pull request closed without merging**
