### PR TITLE
fix cdist gradient computation if first arg is 1xn

### LINKED ISSUE #26076: cdist gradient computation is broken
## 🐛 Bug

Gradient computation of `torch.cdist` results in non-deterministic behavior in some simple cases. It appears there is some kind of overflow or similar going on. 

## To Reproduce

```
def test_grad():
    x1 = torch.tensor([[0.]], requires_grad=True)
    x2 = torch.tensor([[0.5], [1.0]], requires_grad=True)
    res = torch.cdist(x1, x2)
    res[0, 0].backward()
    print(x1.grad, x2.grad)
```

This produces the following (depending on the setting (pytorch, OS) this happens from almost every time to only occasionally).
```
>>> test_grad()
tensor([[-1.]]) tensor([[1.0000e+00], [1.4013e-45]])

>>> test_grad()
tensor([[-1.]]) tensor([[1.], [0.]])

>>> test_grad()
tensor([[-1.]]) tensor([[1.0000e+00], [1.1285e+07]])
```

## Expected behavior

This should be deterministic and correct.

## Environment

This happens on both pytorch 1.2.0 and on pytorch master, on OSX as well as on Linux. 

## Additional context

There are other issues with `cdist` that could be related (in particular the second one):
#25799
#24345

cc @ezyang @gchanan @zou3519

### PR DESCRIPTION
**Pull request by ngimel**
Fixes #26076. @mruberry if #26248 goes in soon, I'll rebase after it, otherwise this should go in because it's a bug fix. 
Side note: cdist backward testing is very light and I suspect is not testing all the code paths, but that's a separate issue.
Test plan: added test for the affected size to test_autograd.py. Streams are tested by existing tests.

### CODE REVIEW

**Comment by mruberry** [comment]
No need to worry about #26248.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
