### PR TITLE
Disable XLA config

### PR DESCRIPTION
**Pull request by malfet**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #71733

See https://github.com/pytorch/pytorch/issues/71732

### CODE REVIEW

**Review by suo — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Comment by seemethere** [comment]
Can we add some context on why this is getting disabled?

**Comment by malfet** [comment]
@seemethere referenced issue in the line above the change

**Pull request closed without merging**
