### PR TITLE
Use _unsafe_masked_index in masked_scatter decomposition

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #123667

and remove masked_scatter_with_index inductor prims

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by peterbell10 — COMMENTED** [review]
Looks good, but can you check the generated code is the same?

**Comment by isuruf** [comment]
> Looks good, but can you check the generated code is the same?

They generate the exact same code.

**Review by peterbell10 — APPROVED** [review]

**Pull request closed without merging**
