### PR TITLE
new triton main pin

### PR DESCRIPTION
**Pull request by ngimel**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'I am not quite sure what this is about yet, but testing 3.8 wheel starts to fail https://hud.pytorch.org/pytorch/pytorch/commit/6e0359dd4233b0cec51521bec8869f0a46ebd98b' -c weird

The error for Python 3.8 is:

```
2023-03-10T05:11:11.4545108Z ␛[?25hERROR: Could not find a version that satisfies the requirement pytorch-triton==2.0.0+2c32f43999 (from torch) (from versions: 0.0.1, 2.0.0+0d7e753227, 2.0.0+3aa3d7024e, 2.0.0+af76c989eb, 2.0.0+b8b470bc59, 2.0.0+c8bfe3f548, 2.0.0+d54c04abe2, 2.1.0+2c32f43999)
2023-03-10T05:11:11.4548152Z ERROR: No matching distribution found for pytorch-triton==2.0.0+2c32f43999
```

**Comment by ngimel** [comment]
I've changed required pytorch-triton version, but how can I check if it works before merging? Previous CI was clean.

**Comment by huydhn** [comment]
> I've changed required pytorch-triton version, but how can I check if it works before merging? Previous CI was clean.

I think you need `ciflow/binaries_wheel` and `ciflow/binary_conda` in the PR for these tests to start.  I don't use them that often, so it was completely off my mind

**Comment by malfet** [comment]
I think all one needs to do is just to update the cache (it's done every 24 hours, which works nice for nightlies, but not for the pin updates. Kicking update manually

**Comment by ngimel** [comment]
The problem I think was not the caches, it's bumped triton version (which I've bumped in the wheel build script, but not in setup.py):
```
Could not find a version that satisfies the requirement pytorch-triton==2.0.0+2c32f43999 (from torch) (from versions: 0.0.1, 2.0.0+0d7e753227, 2.0.0+3aa3d7024e, 2.0.0+af76c989eb, 2.0.0+b8b470bc59, 2.0.0+c8bfe3f548, 2.0.0+d54c04abe2, 2.1.0+2c32f43999)
```
We've built `2.1.0+2c32f43999`, but are looking for `2.0.0+2c32f43999 `. Now I've changed `setup.py` to look for `2.1.0+2c32f43999`

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Damn it, there are too many places now where this version is committed. Need to propose one more change to DOCKER

**Comment by weiwangmeta** [comment]
Not exactly sure if this PR is contributing to failing the performance smoke test. But it is the first time seeing perf smoke test being able to catch some values dropping below threshold. 
After this PR was merged, we see two occurrences of "X". See the HUD: https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=sm80

**Comment by malfet** [comment]
> Not exactly sure if this PR is contributing to failing the performance smoke test. 

The newer the trition the lower the perf :) Will just tweak tolerances lower

**Comment by ngimel** [comment]
@weiwangmeta Why isn't perf smoke test run on PR CI?

**Comment by weiwangmeta** [comment]
> @weiwangmeta Why isn't perf smoke test run on PR CI? Edit: I see, it's just flaky

Yes it was run. My "theory" was the commit may just lowered certain percentage. The "flaky" (or runner run to run variation and/or runner to runner variation) became the "last straw on camel's back"... :)

**Comment by malfet** [comment]
Please do not revert due to the binary builds updates, this was dependent on change on builder side that I forgot to push yesterday

**Comment by ZainRizvi** [comment]
@malfet to prevent this from happening again, what do you think about adding an auto-labeler rule to add `ciflow/binaries_wheel` when the `.ci/docker/ci_commit_pins` folder is modified?

**Comment by ZainRizvi** [comment]
Something like this: https://github.com/pytorch/pytorch/pull/96526

**Comment by malfet** [comment]
@ZainRizvi trunk workflow should have detected that. But I'll submit the change that reduces number of repetitions in the code

**Pull request closed without merging**
