### PR TITLE
Make test_dataloader.py compatible with pytest

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Currently when running with pytest, it fails with

```
__________________________________________________________________________________________________________________ ERROR at setup of test_worker_info_init_fn __________________________________________________________________________________________________________________
file /home/gaoxiang/pytorch-tf32/test/test_dataloader.py, line 670
  def test_worker_info_init_fn(worker_id):
E       fixture 'worker_id' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, include_metadata_in_junit_xml, json_metadata, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/home/gaoxiang/pytorch-tf32/test/test_dataloader.py:670
```
This is because pytest considers anything starting with test_ as a test, so I renamed it to _test_... to prevent this from happening.

### CODE REVIEW

**Comment by mruberry** [comment]
@VitalyFedyunin would you sanity check this change?

**Comment by mruberry** [comment]
ping @VitalyFedyunin for dataloader tests

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Please rebase.

**Comment by zasdfgbnm** [comment]
rebased

**Comment by VitalyFedyunin** [comment]
Wait, did we already accepted similar changes? (it says PR is empty for me)

**Comment by zasdfgbnm** [comment]
Hmm, seems so. Closing this PR.

**Pull request closed without merging**
