### PR TITLE
Add linker script optimization flag to CMAKE rule for CUDA ARM wheel

### PR DESCRIPTION
**Pull request by tinglvv**
Original PR - https://github.com/pytorch/pytorch/pull/127220

cc @Aidyn-A @ptrblck @nWEIdia @atalman

### CODE REVIEW

**Comment by tinglvv** [comment]
Latest wheel performance looks around ~31-32 it/s, linker script optimization appears to be applied correctly:

`Loading pipeline components...: 100%|██████████████████████████| 6/6 [00:00<00:00,  7.29it/s]
100%|████████████████████████████████████████████████████████| 50/50 [00:02<00:00, 22.73it/s]
100%|████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 31.27it/s]
100%|████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 31.49it/s]
100%|████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 31.45it/s]
100%|████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 30.84it/s]
100%|████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 31.09it/s]
100%|████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 31.25it/s]
100%|████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 31.27it/s]
100%|████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 31.25it/s]
100%|████████████████████████████████████████████████████████| 50/50 [00:01<00:00, 31.41it/s]
Time taken:  17.788554430007935`

**Comment by tinglvv** [comment]
The s390 build failures should be unrelated to this change, re-started the tests 3 hours ago still in queue. 
https://github.com/pytorch/pytorch/pull/127600 is working on fixing the issue it seems.

**Review by nWEIdia — COMMENTED** [review]
Looks great! 
Revert builder branch changes before merge.

**Comment by tinglvv** [comment]
Thanks for the quick review, builder change (that sets the env var correctly) has been merged https://github.com/pytorch/builder/pull/1832, so we could set back to main branch. 

Before we merge, I was also thinking to confirm with @Aidyn-A since this wheel performance is at ~30 it/s using the stable diffusion script, and he mentioned 33-34 it/s previously. Was wondering there's any difference between the wheels? Or maybe we are using different script. ++Aidyn for input.

**Review by Aidyn-A — APPROVED** [review]
The linker script flag was properly set, and the performance is restored to the desired level. The CPU failed due to ACL aka MKLDNN being not found:
```
2024-06-03T14:06:12.3938826Z + python -c 'import torch; exit(0 if torch.backends.mkldnn.is_available() else 1)'
2024-06-03T14:06:14.4906776Z ##[error]Process completed with exit code 1.
```

Perhaps there are conflicting instructions in CMake or errors in builder:
```
2024-06-03T13:11:25.2073846Z  [33mCMake Warning at cmake/Dependencies.cmake:158 (message):
2024-06-03T13:11:25.2074566Z   You explicitly chose with BLAS to not use MKL, so disabling USE_MKLDNN.
2024-06-03T13:11:25.2075305Z   Suppress this warning with -DUSE_MKLDNN=OFF.
```

Anyways, I am seeing same issue in the nigthly `aarch64` wheel.
```
~$ python3 -c 'import torch; print(torch.backends.mkldnn.is_available())'
False
```

**Comment by tinglvv** [comment]
Yes, the cpu-aarch64 failures are not relevant and should be fixed by https://github.com/pytorch/pytorch/pull/127762. Rebase should fix the issue.

**Comment by Aidyn-A** [comment]
The logs look fine now, after the rebase. Thanks, Ting!

**Review by atalman — APPROVED** [review]

**Pull request closed without merging**
