### PR TITLE
Choose test affinity based on current affinity

### LINKED ISSUE #44368: test_dataloader fails in restricted CPU environments
## 🐛 Bug

The test at https://github.com/pytorch/pytorch/blob/106459acac181ea1c019f2c298f7d52517626965/test/test_dataloader.py#L2139 uses a call to `os.sched_setaffinity(0, [2])` which fails if the current user has no access to CPU id 2. This happens often in shared environments where multiple users share a CPU and each gets assigned a different core(s)

What I don't get: Why does this test modify a global property at all? Judging from the (very simple) test it would be enough if some local (or global) variable would be set instead.

Or if the affinity is really required to be set: Why isn't it reset afterwards?

At the least I'd suggest to use `os.sched_getaffinity` and use one of the existing ids and not a random, fixed one.

## To Reproduce

1. Use cgroups to restrict the current user/process to only CPU ids except 2
1. Run test_dataloader

## Environment

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Linux

```
## Additional context
======================================================================
ERROR: test_set_affinity_in_worker_init (__main__.TestSetAffinity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_dataloader.py", line 2004, in test_set_affinity_in_worker_init
    for sample in dataloader:
  File "/tmp/eb-wcTuci/tmpc5vukK/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/tmp/eb-wcTuci/tmpc5vukK/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/tmp/eb-wcTuci/tmpc5vukK/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/tmp/eb-wcTuci/tmpc5vukK/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/tmp/eb-wcTuci/tmpc5vukK/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 142, in _worker_loop
    init_fn(worker_id)
  File "test_dataloader.py", line 1992, in worker_set_affinity
    os.sched_setaffinity(0, [2])
OSError: [Errno 22] Invalid argumen
```

cc @SsnL @VitalyFedyunin

### PR DESCRIPTION
**Pull request by Flamefire**
This avoids test failures in cgroup environments

Fixes #44368

### CODE REVIEW

**Comment by Flamefire** [comment]
Test failure is unrelated

**Comment by Flamefire** [comment]
@mruberry This is still an issue for us. Any chance to get this into 1.7?

**Comment by mruberry** [comment]
Hi @Flamefire, sorry it looks like this slipped through the cracks. Sometimes notifications can become lost. In the future if you don't receive a response on your PR in a few days please ping us. 

I think @VitalyFedyunin is still the right person to review this.

**Comment by Flamefire** [comment]
@mruberry @malfet What is the state of this? Could this be included in 1.7? Then I'd open a PR against the release branch too, as I think it qualifies as low-risk test-only fix and certainly helps package maintainers like us.

**Comment by mruberry** [comment]
> @mruberry @malfet What is the state of this? Could this be included in 1.7? Then I'd open a PR against the release branch too, as I think it qualifies as low-risk test-only fix and certainly helps package maintainers like us.

Hey @Flamefire. Sorry things are running slower than you'd like. I'll let @VitalyFedyunin comment on the state of the diff since he's imported it. I think @gchanan is managing the release bar.

**Comment by Flamefire** [comment]
Sure, no worries. It's been a week since the import and I want to avoid missing the release window, hence the ping especially as it is still unanswered whether this would be eligible for 1.7

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by gchanan** [comment]
I don't think we'll get this into the 1.7 release, it's the last hours for that and the test doesn't fail on our machines.

**Comment by Flamefire** [comment]
Alright, thanks for the info.
Note: The test only fails when you don't have access rights to CPU 2, e.g. in a cgroup enforced, multi-user environment which is common on HPC systems (which we use)

**Comment by Flamefire** [comment]
I rebased the branch again on master. Could this be merged please?

**Comment by casparvl** [comment]
@VitalyFedyunin It seems you approved these changes, but if I'm not mistaking they were never merged. It is however still an issue, also in 1.11.0-rc3. There, affinity is now set using `os.sched_setaffinity(0, [multiprocessing.cpu_count() - 1])` but this doesn't help for cgroups environments: multiprocessing.cpu_count() will always return the total CPU count, and this call will thus set affinity to the last CPU. However, if that CPU is not accessible to the current user because of cgroups restrictions, the test still fails.

Just to show how this works in a CGROUPS environment:

```
[casparl@tcn471 casparl]$ python
Python 3.9.5 (default, Oct  8 2021, 23:16:54)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import multiprocessing
>>> os.sched_getaffinity(0)
{104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119}
>>> os.sched_setaffinity(0, [multiprocessing.cpu_count() -1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
>>> os.sched_setaffinity(0, [106])
```
I.e. trying to set affinity to a CPU that is not in the CGROUP will just lead to this `Invalid argument`

What can we do to help this get merged? :)

**Comment by VitalyFedyunin** [comment]
@[Flamefire](https://github.com/Flamefire) please rebase for merging

**Comment by Flamefire** [comment]
Rebased again. Please merge this timely to avoid other PRs such as #65042 introducing new conflicts requiring to rebase and resolve this again. I'm actually surprised that the other PR got in before this one given that this one is superior, i.e. works more generally and hence in more environments with a similar changeset.

**Comment by Flamefire** [comment]
@VitalyFedyunin Ping for merge

**Pull request closed without merging**
