### PR TITLE
Port C++ tests to Catch

### PR DESCRIPTION
**Pull request by lantiga**
This PR addresses #5648. In particular, following the discussion at #5648:

- it vendors Catch (https://github.com/catchorg/Catch2 v2.2.0) in `torch/aten/utils`
- it ports all ATen tests to Catch
- it ports `torch/csrc/jit/test_jit.cpp` to Catch (libtorch only, Python build is unaffected)

One note: catch.hpp is a large source file. It has been vendored in ATen (vendoring is the recommended option in the Catch README), but we may want to keep it out of the repository and provide a download step for building tests. Feedback welcome.

Possibilities:
- vendoring (as current)
- git submodule
- CMake `file` command (https://cmake.org/cmake/help/latest/command/file.html)
- CMake `ExternalProject_Add` command (https://cmake.org/cmake/help/latest/module/ExternalProject.html)
- `wget` in a bash file

### CODE REVIEW

**Comment by apaszke** [comment]
submodule would be nice, but I don't think can even be done since `aten/` is synchronized as a subtree.

**Comment by lantiga** [comment]
You're right. CMake is the second most cross-platform thing, should we aim at it?

**Comment by lantiga** [comment]
@ezyang I need help with jenkins: in the `test.sh` step I don't find the artifacts in `torch/cpp_build/build` that were created by `build.sh`. In particular I need the `test_jit` executable as well as `libtorch` to run the test.
I naively thought there was some connection between steps, but there isn't.

What's the best way to ensure that `libtorch` artifacts are there so that I can run tests for the C++ part? Thanks a lot in advance.

**Comment by ezyang** [comment]
Hey @lantiga,

The hidden constraint is that we run `git clean -xfd` before building and shipping out the Docker container. 
So, you'll get source code and anything you installed, and that's it. Does that suggest a fix to you?

Can you add a note about this at the end of `./build.sh`?

**Comment by lantiga** [comment]
Thanks @ezyang, all I can think of is either
- rebuilding `libtorch` in `test.sh`
- or, pass an `exclude` rule to `git clean` that preserves what is in `tools/cpp_build/build/Install` (or whatever location we want to use to store the build files)

What do you think?

**Comment by lantiga** [comment]
What if I told CMake to install `libtorch` artifacts to a directory outside the source tree instead of `tools/cpp_build/build/Install`?

**Comment by ezyang** [comment]
> rebuild libtorch in test.sh

Definitely please don't do this :)

> What if I told CMake to install libtorch artifacts to a directory outside the source tree instead of tools/cpp_build/build/Install?

I think something like this is definitely preferred, because at the end of the day the preferred way to use libtorch is to install it somehow, and then use it, right? Furthermore, our build of `libtorch` is done completely independently of PyTorch, so there really is no reason to install it into the `tools` directory. So if you install it somewhere outside of `pytorch` that would be great.

**Comment by apaszke** [comment]
Actually I just realized that submodules might be a viable option, because we could just modify the `.gitmodules` in the PyTorch repo, and create `aten/.gitmodules` manually too (with the paths patched up). This would let the standalone ATen repo download Catch from `git` as well

**Comment by lantiga** [comment]
@ezyang So although a few builds are failing, it seems that `test_jit` is preserved now.
One build fails because it's not a CUDA machine and some tests require CUDA, that's fine.
However I can't parse the errors on the `pr/pytorch-linux-xenial-py3-clang5-asan` build (https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-py3-clang5-asan-build/1101/consoleFull).
Any suggestion would be very useful.

@apaszke I added Catch as a submodule, it looks like it's working. Now we should do the same for ATen, but I guess that has to be done separately on the ATen repository.

**Comment by lantiga** [comment]
@ezyang Most issues are gone, I still get a build error on the Cuda builds. Where do I find `nvToolsExt.h` in the filesystem?

**Comment by ezyang** [comment]
You should fix the `build_all.sh` script and add `set -e` to the top so that it exits on the first failing command and propagates the exit code. (I'd actually do `set -ex` because I like seeing what commands run.)

As for `nvToolsExt.h`, the way to debug this problem is to download the base docker image quoted at the beginning of the log:

```
11:08:44 + docker_args+=' registry.pytorch.org/pytorch/pytorch-linux-xenial-cuda9-cudnn7-py3:123'
11:08:44 + retry docker pull registry.pytorch.org/pytorch/pytorch-linux-xenial-cuda9-cudnn7-py3:123
11:08:44 + docker pull registry.pytorch.org/pytorch/pytorch-linux-xenial-cuda9-cudnn7-py3:123
11:08:45 123: Pulling from pytorch/pytorch-linux-xenial-cuda9-cudnn7-py3
```

and check yourself.  You can run a docker image with `docker run --rm -it $image_name`

**Comment by bddppq** [comment]
@onnxbot retest this please

**Pull request closed without merging**
