### PR TITLE
Fix `aten::squeeze.dims` shape function

### LINKED ISSUE #1690: [TRACKER] Roll PyTorch action
I'm creating this issue so that we can keep track of the errors that we see while updating the PyTorch version for the project. Anyone who faces an issue can post it here, try to fix that or if they don't know how to do that, can ask someone (working on that stuff) to fix the issue. I hope this approach looks fine.

cc: @powderluv @silvasean @ramiro050 @tanyokwok @eric-k256

### PR DESCRIPTION
**Pull request by vivekkhandelwal1**
Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>

Fixes https://github.com/llvm/torch-mlir/issues/1690#issuecomment-1491931180.

### CODE REVIEW

**Comment by vivekkhandelwal1** [comment]
@davidberard98 @eellison @Gamrix Can anyone of you please review and merge this PR? This is required urgently to fix the following error: https://github.com/llvm/torch-mlir/actions/runs/4575347497.

**Review by davidberard98 — APPROVED** [review]
looks good - but can you also add a test in test/jit/test_symbolic_shape_analysis.py?

you can do it in a separate PR if you prefer.

**Comment by vivekkhandelwal1** [comment]
> looks good - but can you also add a test in test/jit/test_symbolic_shape_analysis.py?
> 
> you can do it in a separate PR if you prefer.

Yeah, I will do that in a separate PR. Could you please merge this for me?

**Comment by davidberard98** [comment]
you can run the merge yourself just by commenting

**Pull request closed without merging**
