### PR TITLE
Use Python::NumPy target

### PR DESCRIPTION
**Pull request by cyyever**
Now that we use FindPython, use it again for numpy detection.

### CODE REVIEW

**Comment by cyyever** [comment]
@malfet  In the just merged changes, CMake issues FATAL_ERROR if "NOT Python_Development_FOUND", but it turns BUILD_PYTHON off if "NOT Python_Interpreter_FOUND". Should we improve that?

**Review by malfet — APPROVED** [review]
LGTM, but mind deleting logic that passes NUMPY_INLCUDE_DIR from `tools/setup_helpers/cmake.py`?

**Comment by cyyever** [comment]
> > @malfet In the just merged changes, CMake issues FATAL_ERROR if "NOT Python_Development_FOUND", but it turns BUILD_PYTHON off if "NOT Python_Interpreter_FOUND". Should we improve that? I think it makes more sense to use FATAL_ERROR in both cases.
> 
> I thought logic for that is to make sure that libtorch can be build on Windows even when development .lib are not installed, but logic as you've described sounds inverse. If it's indeed the case, please send a PR

At least codegen.cmake requires the python interpreter, so the interpreter must be presented on the build host. Python_Development is optional if the project don't need torch_python.

**Pull request closed without merging**
