### PR TITLE
[FSDP][Wrap] ModuleWrapPolicy callable

### PR DESCRIPTION
**Pull request by rohan-varma**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #109117
* #109116

Makes ModuleWrapPolicy callable, in my case this is needed for
composition with or_policy. We should also make or_policy a public interface
IMO.

Differential Revision: [D49175112](https://our.internmc.facebook.com/intern/diff/D49175112/)

### CODE REVIEW

**Review by fegin — APPROVED** [review]
LGTM

**Comment by rohan-varma** [comment]
@awgu is it OK for ModuleWrapPolicy?

**Comment by awgu** [comment]
I think this is okay. I wonder if we should add a unit test though.

**Comment by rohan-varma** [comment]
That can be a good ramp up task: https://github.com/pytorch/pytorch/issues/109266

**Comment by rohan-varma** [comment]
dynamo tests are unrelated

**Pull request closed without merging**
