### PR TITLE
[wip][jit] Remove _pack and _unpack

### PR DESCRIPTION
**Pull request by driazati**

### CODE REVIEW

**Review by jamesr66a — APPROVED** [review]
good work buddy

**Comment by eellison** [comment]
> good work buddy

Was this a stamp? looks like it still needs a real review

**Review by eellison — CHANGES_REQUESTED** [review]
think this needs a real review before landing

**Comment by jamesr66a** [comment]
@eellison no, that wasn't a stamp. The code looked fine when I reviewed it. And now this has been delayed 2 months and we've had multiple `_pack` and `_unpack` callsites added as a result...

@driazati can we please get this landed?

**Comment by eellison** [comment]
Special casing of argument spec and breaking of core invariants of argument spec should at least come with a disclaimer / discussion of why that's necessary. The fact that it's been two months since anyone has responded is tangential.

**Pull request closed without merging**
