### PR TITLE
Change `NoneStatus` from unscoped enum to scoped enum

### PR DESCRIPTION
**Pull request by ansley**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #59465
* #59245
* #59244

Differential Revision: [D30069328](https://our.internmc.facebook.com/intern/diff/D30069328)

### CODE REVIEW

**Review by SplitInfinity — APPROVED** [review]
🥇

**Comment by ansley** [comment]
@ansley has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30069328).

**Comment by ansley** [comment]
@ansley has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30069328).

**Comment by ansley** [comment]
@ansley has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30069328).

**Pull request closed without merging**
