### PR TITLE
[PyTorch] Delete NestedTensor Python wrapper

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #74691

The wrapper just called through to methods on the underlying Tensor.

Differential Revision: [D34689789](https://our.internmc.facebook.com/intern/diff/D34689789/)

### CODE REVIEW

**Comment by mattangus** [comment]
Now that the wrapper is deleted is there any way to distinguish between a nested tensor and a regular tensor? Currently I have two work arounds:
```python
    try:
        tensor.shape
        is_nested = False
    except RuntimeError as ex:
        is_nested = "NestedTensorImpl" in str(ex)
```
or 
```python
    is_nested = "nested_tensor" in str(tensor)
```

The former is very slow because of the try except perfomace. The latter requires a copy to the CPU for the print.

**Comment by cpuhrsch** [comment]
@mattangus - I agree that we should have something here. Could I kindly ask you to open a separate issue? Also, as a user of this new prototype feature maybe you want to share more what your use case is and what you have planned for NestedTensor?

**Comment by mattangus** [comment]
@cpuhrsch I made a couple of feature requests. #75940 and https://github.com/pytorch/pytorch/issues/75939. The former showcases my usecase a bit.

**Comment by swolchok** [comment]
#73999 added Tensor.is_nested

**Pull request closed without merging**
