### PR TITLE
DTensor: dont hash symint tensor input in propagate_tensor_meta

### PR DESCRIPTION
**Pull request by bdhirsh**
This fixes a subset of issues for dynamic shapes + DTensor.

It's pretty easy to run into other issues - it's likely that we need https://github.com/pytorch/pytorch/pull/125941 to land for DTensor + dynamic shapes to work more generally. I ended up writing a test that had dynamic shape inputs but not dynamic shape outputs in order to properly test this fix

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #131481
* #133044
* #133784
* __->__ #136266

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
It does seem like there's no reason to believe other call sites wouldn't pass in SymInt?

**Comment by bdhirsh** [comment]
You're right - I just audited usages of `lru_cache` in `torch/distributed/tensor` - I found 3 total, including one that I missed. I added a similar symint non-cached branch for that other site too and updated the test.

Given that there are 3 caches across all of DTensor's codepaths, I'm hoping we'll be ok with auditing + testing to make sure that we e.g. don't add a new lru_cache later and accidentally regress dynamic shape usage.

**Review by yf225 — APPROVED** [review]

**Comment by yf225** [comment]
> I'm hoping we'll be ok with auditing + testing to make sure that we e.g. don't add a new lru_cache later and accidentally regress dynamic shape usage.

thanks! and I assume the currently added unit test will be able to catch the regression in the future?

**Comment by bdhirsh** [comment]
> thanks! and I assume the currently added unit test will be able to catch the regression in the future?

It should catch most cases - although for better coverage, we should probably take all of the DTensor + compile tests and run them with dynamic shapes. We can't do that until https://github.com/pytorch/pytorch/pull/125941 lands though

**Pull request closed without merging**
