### PR TITLE
Re-land _cycleviz.py: visualize reference cycles holding cuda memory

### PR DESCRIPTION
**Pull request by zdevito**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104051

Reference cycles are freed by the cycle collector rather than being cleaned up
when the objects in the cycle first become unreachable. If a cycle points to a tensor,
the CUDA memory for that tensor will not be freed until garbage collection runs.
Accumulation of CUDA allocations can lead to out of memory errors (OOMs), as well as
non-deterministic allocation behavior which is harder to debug.

This visualizer installs a garbage collection hook to look for cycles containing
CUDA tensors and saves a visualization of the garbage:

```
from torch.cuda._cycleviz import warn_tensor_cycles
warn_tensor_cycles()
# do some work that results in a cycle getting garbage collected
# ...
> WARNING:root:Reference cycle includes a CUDA Tensor see visualization of cycle /tmp/tmpeideu9gl.html
```

Reland to make windows skip the test.

This reverts commit 7b3b6dd4262337c5289d64dd3e824b0614cf68e3.

### CODE REVIEW

**Review by aaronenyeshi — APPROVED** [review]
Approve for re-land!

**Review by malfet — CHANGES_REQUESTED** [review]
Can you please add a short description of what have changed since the last attempt?

**Comment by zdevito** [comment]
Excluded the unsupported windows config.

**Review by malfet — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
