### PR TITLE
Add tools for autograd profiling

### PR DESCRIPTION
**Pull request by apaszke**
Rebase of ezyang/pytorch#236

### CODE REVIEW

**Comment by soumith** [comment]
can you take some time and add a comment to this PR:
- how does the profiler work (briefly)
- how to use the profiler
- what does the output look like.

**Comment by jekbradbury** [comment]
I'm surprised that this runs every (Python) operator name through a command-line C++ name demangler, since that takes several minutes for a one-second profile of a complex network and none of the names are actually mangled?

**Comment by ezyang** [comment]
Yes, the profiler post-processing is really slow and needs to be optimized. (cc @apaszke)

**Comment by apaszke** [comment]
Right. I'll fix that

**Comment by apaszke** [comment]
It used to be ok for nvprof checkpoints, because it was only used to translate a string table i.e. one run for each kind of a Function that was used. Right now it's once per event, so it's too much.

**Pull request merged**
