### PR TITLE
enable lazy_init for hpu

### PR DESCRIPTION
**Pull request by RafLit**
enables lazy_init for hpu device

### CODE REVIEW

**Comment by RafLit** [comment]
cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @LucasLLC @MeetVadakkanchery @mhorowitz @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
