### PR TITLE
[profiler] enable CUPTI range profiler in build

### LINKED ISSUE #125272: Profiler Kineto Config:  Warning: Failed to recover relationship between all profiler and kineto events: 51361 vs. 0  reassociated. (function reassociate)
### 🐛 Describe the bug

when enabling `kineto__tensor_core_insts` or `dram__bytes_read.sum`, the pytorch profiler outputs this warning and the trace becomes unusable. I have even tried adding the following profiler config below to a sample toy model and still outputs this error
```python
 Warning: Failed to recover relationship between all profiler and kineto events: 51361 vs. 0  reassociated. (function reassociate)
```

i see this warning msg comes from this function but no obvious how to debug it
https://github.com/pytorch/pytorch/blob/ca0f070065e8bf4575107ccdecd6785dea6d9010/torch/csrc/profiler/collection.cpp#L943

## reprod

```python
from torch.profiler import profile, schedule, tensorboard_trace_handler

tracing_schedule = schedule(skip_first=5, wait=5, warmup=2, active=2, repeat=1)
trace_handler = tensorboard_trace_handler(dir_name=f"./trace/", worker_name=f"rank_{int(os.environ['LOCAL_RANK'])}")

with torch.profiler.profile(
        activities=[torch.profiler.ProfilerActivity.CUDA, torch.profiler.ProfilerActivity.CPU],
        schedule = tracing_schedule,
        on_trace_ready = trace_handler,
        profile_memory = True,
        record_shapes = True,
        with_stack = True,
        experimental_config=torch.profiler._ExperimentalConfig(
            profiler_metrics=[
                "kineto__tensor_core_insts",
                "dram__bytes_read.sum",
            ],
            profiler_measure_per_kernel=False
        ),
    ) as prof:
```

### Versions

torch==2.3.0
NVIDIA Driver: 535
HGX H100 SXM

cc @robieta @chaekit @aaronenyeshi @guotuofeng @guyang3532 @dzhulgakov @davidberard98 @briancoutinho @sraikund16 @sanrise

### PR DESCRIPTION
**Pull request by briancoutinho**
Fixes #125272
## About
(This is a re-spin of PR #106617)

Kineto introduced a new profiler to read performance counters from NVIDIA GPUs (CUPTI Range Profiler API) added in PR[75616](https://github.com/pytorch/pytorch/pull/75616).  Support for the range profiler mode was disabled as we had to link with a NV PerfWorks library (`libnvperf_host.so`). This PR adds that link.

The change includes-
* Updates cmake build files to find `libnvperf_host.so` and set `CUDA_nvperf_host_LIBRARY`
* WIP use the above cmake variable in kineto, will update this PR after kineto PR has landed
See https://github.com/pytorch/kineto/pull/724

## Example usage of CUPTI profiler
The code snippet below shows how to configure pytorch profiler in CUPTI Profiler mode. Any code included in profiling window with be profiler by CUPTI/Kineto. Note how the `_ExperimentalConfig` struct is used to configure profiler metrics 
```
    with torch.profiler.profile(
        activities=[torch.profiler.ProfilerActivity.CUDA],
        record_shapes=True,
        on_trace_ready=trace_handler,
        experimental_config=torch.profiler._ExperimentalConfig(
            profiler_metrics=[
                "kineto__tensor_core_insts",
                "dram__bytes_read.sum",
                "dram__bytes_write.sum"],
            profiler_measure_per_kernel=False),
    ) as prof:
        res = train_batch(modeldef)
        prof.step()
```
For a full example see this [xor.py](https://gist.github.com/briancoutinho/b1ec7919d8ea2bf1f019b4f4cd50ea80) gist.

### Details of how to configure CUPTI profielr
The` _Experimental` config structure can be used to pass metrics to profiler 
```
   profiler_metrics : a list of CUPTI profiler metrics used
       to measure GPU performance events. Any metric supported by CUPTI can be used, see here=
       https://docs.nvidia.com/cupti/r_main.html#r_profiler
       There are two special alias metrics `kineto__tensor_core_insts` and `kineto__cuda_core_flops` for FLOPS counting.
   profiler_measure_per_kernel (bool) : whether to profile metrics per kernel
      or for the entire measurement duration.
```

## Testing
Built from source with kineto [PR](https://github.com/pytorch/kineto/pull/724)
```
$> USE_CUDA=1 python setup.py install
--   CUDA_cupti_LIBRARY = /public/apps/cuda/11.6/extras/CUPTI/lib64/libcupti.so
--   CUDA_nvperf_host_LIBRARY = /public/apps/cuda/11.6/extras/CUPTI/lib64/libnvperf_host.so
```

Then run example [xor.py](https://gist.github.com/briancoutinho/b1ec7919d8ea2bf1f019b4f4cd50ea80). This only works on V100+ GPUs only. Adding logs for debugging etc.
```
>$ export KINETO_LOG_LEVEL=1
>$ python xor.py
INFO:2023-02-11 19:11:37 1683060:1683060 CuptiActivityProfiler.cpp:167] CUDA versions. CUPTI: 16; Runtime: 11060; Driver: 11040
  Log file: /tmp/libkineto_activities_1683060.json
  Trace start time: 2023-02-11 19:11:47  Trace duration: 500ms
  Warmup duration: 0s
  Max GPU buffer size: 128MB
  Enabled activities: cuda_profiler_range
Cupti Profiler metrics : kineto__tensor_core_insts, dram__bytes_read.sum, dram__bytes_write.sum
Cupti Profiler measure per kernel : 0
Cupti Profiler max ranges : 10
INFO:2023-02-11 19:11:37 1683060:1683060 CuptiActivityProfiler.cpp:638] Enabling GPU tracing
INFO:2023-02-11 19:11:37 1683060:1683060 CuptiActivityProfiler.cpp:567] Running child profiler CuptiRangeProfiler for 500 ms
INFO:2023-02-11 19:11:37 1683060:1683060 CuptiRangeProfiler.cpp:104] Configuring 3 CUPTI metrics
INFO:2023-02-11 19:11:37 1683060:1683060 CuptiRangeProfiler.cpp:109]    sm__inst_executed_pipe_tensor.sum
INFO:2023-02-11 19:11:37 1683060:1683060 CuptiRangeProfiler.cpp:109]    dram__bytes_read.sum
INFO:2023-02-11 19:11:37 1683060:1683060 CuptiRangeProfiler.cpp:109]    dram__bytes_write.sum
INFO:2023-02-11 19:11:37 1683060:1683060 CuptiActivityProfiler.cpp:575] Running child profiler CuptiRangeProfiler for 500 ms
INFO:2023-02-11 19:11:37 1683060:1683060 CuptiActivityProfiler.cpp:672] Tracing starting in 9s
INFO:2023-02-11 19:11:37 1683060:1683060 CuptiActivityProfiler.cpp:677] Tracing will end in 10s
STAGE:2023-02-11 19:11:37 1683060:1683060 ActivityProfilerController.cpp:310] Completed Stage: Warm Up
INFO:2023-02-11 19:11:37 1683060:1683060 CuptiActivityProfiler.cpp:693] Starting child profiler session
```

### CODE REVIEW

**Review by sraikund16 — APPROVED** [review]
lgtm!

**Comment by atalman** [comment]
This breaks nightly:
https://github.com/pytorch/pytorch/actions/runs/9014007927/job/24770799942
Also breaks torchvision:
https://github.com/pytorch/vision/actions/runs/9016658939/job/24786226848

Errors:
```
+ g++ /builder/test_example_code/simple-torch-test.cpp -I/tmp/libtorch/include -I/tmp/libtorch/include/torch/csrc/api/include -D_GLIBCXX_USE_CXX11_ABI=1 -std=gnu++17 -L/tmp/libtorch/lib -Wl,-R/tmp/libtorch/lib -Wl,--no-as-needed -ltorch -ltorch_cpu -ltorch_cuda -lc10 -o simple-torch-test
/usr/bin/ld: warning: libnvperf_host.so, needed by /tmp/libtorch/lib/libtorch_cpu.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /tmp/libtorch/lib/libtorch_cpu.so: undefined reference to `NVPW_RawMetricsConfig_GetConfigImage'
/usr/bin/ld: /tmp/libtorch/lib/libtorch_cpu.so: undefined reference to `NVPW_CUDA_RawMetricsConfig_Create'
/usr/bin/ld: /tmp/libtorch/lib/libtorch_cpu.so: undefined reference to `NVPW_CounterDataBuilder_GetCounterDataPre
```

**Review by aaronenyeshi — CHANGES_REQUESTED** [review]
Please take a look at CI failures and why it was reverted

**Comment by briancoutinho** [comment]
@atalman sorry about the delay, this seems to be issue with looking up the libnvperf_host.so shared library, ideally i think this should always be there in cuda install.
```
ImportError: libnvperf_host.so: cannot open shared object file: No such file or directory
```
Is there someway I can ssh into nightly environment. I just want to check whether this .so file is even there in the environment

**Comment by briancoutinho** [comment]
@atalman friendly ping :)

**Pull request closed without merging**
