### PR TITLE
add register_device_op_overrides

### LINKED ISSUE #119267: Registers DeviceOpOverrides for a device and obtains the corresponding class using the get function.
### 🚀 The feature, motivation and pitch

Currently https://github.com/pytorch/pytorch/blob/main/torch/_inductor/codegen/common.py#L106 only supports built-in device function, I'm going to add a register function to get overrides class.

pls

### Alternatives

_No response_

### Additional context

_No response_

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### PR DESCRIPTION
**Pull request by wangjiangben-hw**
Fixes #119267

Currently https://github.com/pytorch/pytorch/blob/main/torch/_inductor/codegen/common.py#L106 only supports built-in device function, I'm going to add a register function to get overrides class.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire

### CODE REVIEW

**Comment by ezyang** [comment]
Reassigning to the authors/reviewers of the code being modified

**Comment by wangjiangben-hw** [comment]
cc @ezyang @jansel @jgong5 @EikanWang

**Review by jansel — DISMISSED** [review]

**Comment by wangjiangben-hw** [comment]
> ## Merge failed
> **Reason**: 3 mandatory check(s) failed. The first few are:
> 
> * [pull / linux-focal-py3.12-clang10 / build](https://github.com/pytorch/pytorch/actions/runs/7940158291/job/21687153873)
> * [Lint / lintrunner-clang / linux-job](https://github.com/pytorch/pytorch/actions/runs/7940158306/job/21687152688)
> * [Lint / lintrunner-noclang / linux-job](https://github.com/pytorch/pytorch/actions/runs/7940158306/job/21687153016)
> 
> Dig deeper by [viewing the failures on hud](https://hud.pytorch.org/pytorch/pytorch/commit/b67ff4883345767fb490883894f6ab9265b699c4)
> 
> Details for Dev Infra team

How to deal with these three errors? This doesn't seem to have anything to do with my PR.

**Comment by wangjiangben-hw** [comment]
> ## Merge failed
> **Reason**: 3 mandatory check(s) failed. The first few are:
> 
> * [pull / linux-focal-py3.12-clang10 / build](https://github.com/pytorch/pytorch/actions/runs/7940158291/job/21687153873)
> * [Lint / lintrunner-clang / linux-job](https://github.com/pytorch/pytorch/actions/runs/7940158306/job/21687152688)
> * [Lint / lintrunner-noclang / linux-job](https://github.com/pytorch/pytorch/actions/runs/7940158306/job/21687153016)
> 
> Dig deeper by [viewing the failures on hud](https://hud.pytorch.org/pytorch/pytorch/commit/b67ff4883345767fb490883894f6ab9265b699c4)
> 
> Details for Dev Infra team

How to deal with these three errors? This doesn't seem to have anything to do with my PR.

**Comment by wangjiangben-hw** [comment]
thanks for https://github.com/pytorch/pytorch/pull/120207 @atalman I'll deal with it.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
