### PR TITLE
Disable sccache when building NCCL

### LINKED ISSUE #8685: Unknown CMake command "cuda_select_nvcc_arch_flags".
- CMake version:3.5.1

```
(torchsource) amers@dp:~/pytorch$ python setup.py install
running install
running build_deps
+ USE_CUDA=0
+ USE_ROCM=0
+ USE_NNPACK=0
+ USE_MKLDNN=0
+ USE_GLOO_IBVERBS=0
+ USE_DISTRIBUTED_MW=0
+ FULL_CAFFE2=0
+ [[ 9 -gt 0 ]]
+ case "$1" in
+ USE_CUDA=1
+ shift
+ [[ 8 -gt 0 ]]
+ case "$1" in
+ USE_NNPACK=1
+ shift
+ [[ 7 -gt 0 ]]
+ case "$1" in
+ break
+ CMAKE_INSTALL='make install'
+ USER_CFLAGS=
+ USER_LDFLAGS=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
++ dirname tools/build_pytorch_libs.sh
+ cd tools/..
+++ pwd
++ printf '%q\n' /home/amers/pytorch
+ PWD=/home/amers/pytorch
+ BASE_DIR=/home/amers/pytorch
+ TORCH_LIB_DIR=/home/amers/pytorch/torch/lib
+ INSTALL_DIR=/home/amers/pytorch/torch/lib/tmp_install
+ THIRD_PARTY_DIR=/home/amers/pytorch/third_party
+ CMAKE_VERSION=cmake
+ C_FLAGS=' -DTH_INDEX_BASE=0 -I"/home/amers/pytorch/torch/lib/tmp_install/include"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/TH" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THC"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/THS" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THCS"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/THNN" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THCUNN"'
+ C_FLAGS=' -DTH_INDEX_BASE=0 -I"/home/amers/pytorch/torch/lib/tmp_install/include"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/TH" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THC"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/THS" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THCS"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/THNN" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1'
+ LDFLAGS='-L"/home/amers/pytorch/torch/lib/tmp_install/lib" '
+ LD_POSTFIX=.so
++ uname
+ [[ Linux == \D\a\r\w\i\n ]]
+ LDFLAGS='-L"/home/amers/pytorch/torch/lib/tmp_install/lib"  -Wl,-rpath,$ORIGIN'
+ CPP_FLAGS=' -std=c++11 '
+ GLOO_FLAGS=
+ THD_FLAGS=
+ NCCL_ROOT_DIR=/home/amers/pytorch/torch/lib/tmp_install
+ [[ 1 -eq 1 ]]
+ GLOO_FLAGS='-DUSE_CUDA=1 -DNCCL_ROOT_DIR=/home/amers/pytorch/torch/lib/tmp_install'
+ [[ 0 -eq 1 ]]
+ [[ 0 -eq 1 ]]
+ CWRAP_FILES='/home/amers/pytorch/torch/lib/ATen/Declarations.cwrap;/home/amers/pytorch/torch/lib/THNN/generic/THNN.h;/home/amers/pytorch/torch/lib/THCUNN/generic/THCUNN.h;/home/amers/pytorch/torch/lib/ATen/nn.yaml'
+ CUDA_NVCC_FLAGS=' -DTH_INDEX_BASE=0 -I"/home/amers/pytorch/torch/lib/tmp_install/include"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/TH" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THC"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/THS" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THCS"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/THNN" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1'
+ [[ -z '' ]]
+ CUDA_DEVICE_DEBUG=0
+ '[' -z 12 ']'
+ BUILD_TYPE=Release
+ [[ -n '' ]]
+ [[ -n '' ]]
+ echo 'Building in Release mode'
Building in Release mode
+ mkdir -p torch/lib/tmp_install
+ for arg in '"$@"'
+ [[ nccl == \n\c\c\l ]]
+ pushd /home/amers/pytorch/third_party
~/pytorch/third_party ~/pytorch
+ build_nccl
+ mkdir -p build/nccl
+ pushd build/nccl
~/pytorch/third_party/build/nccl ~/pytorch/third_party ~/pytorch
+ cmake ../../nccl -DCMAKE_MODULE_PATH=/home/amers/pytorch/cmake/FindCUDA -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/amers/pytorch/torch/lib/tmp_install '-DCMAKE_C_FLAGS= -DTH_INDEX_BASE=0 -I"/home/amers/pytorch/torch/lib/tmp_install/include"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/TH" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THC"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/THS" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THCS"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/THNN" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1 ' '-DCMAKE_CXX_FLAGS= -DTH_INDEX_BASE=0 -I"/home/amers/pytorch/torch/lib/tmp_install/include"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/TH" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THC"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/THS" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THCS"   -I"/home/amers/pytorch/torch/lib/tmp_install/include/THNN" -I"/home/amers/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1  -std=c++11  ' -DCMAKE_SHARED_LINKER_FLAGS= -DCMAKE_UTILS_PATH=/home/amers/pytorch/cmake/public/utils.cmake
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "7.0") 
CMake Error at /home/amers/pytorch/cmake/public/utils.cmake:164 (cuda_select_nvcc_arch_flags):
  Unknown CMake command "cuda_select_nvcc_arch_flags".
Call Stack (most recent call first):
  CMakeLists.txt:9 (torch_cuda_get_nvcc_gencode_flag)


-- Configuring incomplete, errors occurred!
See also "/home/amers/pytorch/third_party/build/nccl/CMakeFiles/CMakeOutput.log".
See also "/home/amers/pytorch/third_party/build/nccl/CMakeFiles/CMakeError.log".
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 nanopb libshm gloo THD c10d'
(torchsource) amers@dp:~/pytorch$ cmake --version
cmake version 3.5.1
```

CMake suite maintained and supported by Kitware (kitware.com/cmake).

### PR DESCRIPTION
**Pull request by yf225**
This PR tries to fix https://github.com/pytorch/pytorch/issues/8685 by disabling `sccache` when building NCCL, so that we can use `cmake/Modules_CUDA_fix` as the cmake module.

### CODE REVIEW

**Comment by SsnL** [comment]
Nice! Hope CI passes

**Comment by yf225** [comment]
@ezyang @SsnL Does this look good to merge?

**Review by ssnl — APPROVED** [review]
LGTM. Thanks!

**Review by ezyang — APPROVED** [review]

**Comment by SsnL** [comment]
merge when green

**Review by orionr — APPROVED** [review]

**Pull request merged**
