### PR TITLE
sup torch script parameterlist

### LINKED ISSUE #61176: Make ParameterList subscriptable in TorchScript
Here is some code you may try:

```python
import torch
from torch import nn

class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.module_list = nn.ModuleList([nn.Linear(1,1) for _ in range(10)])
        self.parameter_list = nn.ParameterList([nn.Parameter(torch.zeros(1)) for _ in range(10)])

    def forward(self, x):
        self.module_list[0]
        self.parameter_list[0]
        return x


if __name__ == '__main__':
    model = MyModule()
    torch.jit.script(model)
```

This raises

```
RuntimeError: 
Only ModuleList, Sequential, and ModuleDict modules are subscriptable:
  File "test.py", line 12
    def forward(self, x):
        self.module_list[0]
        self.parameter_list[0]
        ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return x
```

Are there any plans to make this work? If not, does anyone know of a good workaround?

### PR DESCRIPTION
**Pull request by wukong1992**
Fixes #61176

### CODE REVIEW

**Comment by davidberard98** [comment]
@wukong1992 can you rebase onto master? I think you need to update in order for the tests to run.

Also I think there's some linter errors, could you fix those?

**Comment by wukong1992** [comment]
@davidberard98 Do you know how to ignore the submodules, I cannot figure it.

**Comment by davidberard98** [comment]
Here's what I suggest:

First run `git show`. It'll show all the changes from the current commit. In particular, it'll show the changes from the submodules. It'll probably include some sections that look like this:

```
module third_party/cudnn_frontend
- commit abc123 # placeholder commit hash
+ commit def456 # placeholder commit hash
```

Then `cd third_party/cudnn_frontend` and run `git checkout abc123` (replace abc123 with the correct hash). It'll revert the changes. Do this with all the other submodules that are shown from the `git show` output.

Finally, `git add` the submodules and `git commit --amend` to update the commit.

**Comment by wukong1992** [comment]
@davidberard98

**Review by davidberard98 — APPROVED** [review]
looks good to me!
Thanks @wukong1992 for the fix!!

**Pull request closed without merging**
