### PR TITLE
[c10d] [NCCL] Fix work handle for coalescing manager

### LINKED ISSUE #122807: [c10d][NCCL] _coalescing_manager does not produce proper work handle
### 🐛 Describe the bug

The list of work objects (`works`) is empty:
```python
    with dist._coalescing_manager(group=pg_nccl, device=device, async_ops=True) as cm:
        dist.all_reduce(a)
        dist.all_reduce(b)
    print(len(cm.works)) # prints 0
    cm.wait()
```
In this situation `cm.wait()` becomes a no-op, which causes red-before-write issues whenever `_coalescing_manager` is used.

### Versions

PyTorch version: 2.4.0.dev20240326+cu121
```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/pytorch/pull/122651
- [ ] https://github.com/pytorch/pytorch/pull/122849
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### PR DESCRIPTION
**Pull request by Aidyn-A**
Fixes #122807
The work handle of the coalescing job will be populated:
```python
    with dist._coalescing_manager(group=pg_nccl, device=device, async_ops=True) as cm:
        dist.all_reduce(a)
        dist.all_reduce(b)
    print(len(cm.works)) # prints 1
    cm.wait() # actually waits
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### CODE REVIEW

**Comment by wconstab** [comment]
i don't understand the fix, and i'd appreciate if you also add a test case, probably to  `test_c10d_nccl.py`.

the fix looks like its just adds some assertions and updates the coalescedDevice, but how does it impact the work obj that gets returned?

**Comment by Aidyn-A** [comment]
> how does it impact the work obj that gets returned?

Here:
https://github.com/pytorch/pytorch/blob/76a87e33a0fdd0639842218ce26943e7b4f3838b/torch/distributed/distributed_c10d.py#L2037-L2039

`_end_coalescing` was supposed to return a proper work object. However, because `coalescedComm_` is `nullptr` it does call `groupEnd`, but it returns a `nullptr` for work object pointer:

https://github.com/pytorch/pytorch/blob/76a87e33a0fdd0639842218ce26943e7b4f3838b/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L2280-L2286

**Comment by Aidyn-A** [comment]
cc @kwen2501

**Comment by kwen2501** [comment]
Thanks for finding the issue.
Hopefully #123170 explains the error.
I think the issue is really in `_coalescing_manager` so I am fixing it there.

**Review by kwen2501 — APPROVED** [review]
Thanks for the fix! LGTM!

**Pull request closed without merging**
