### PR TITLE
Enable flake8-bugbear B028 lint

### PR DESCRIPTION
**Pull request by Silv3S**
Part of #106571

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @Xia-Weiwen @ngimel @anijain2305

### CODE REVIEW

**Comment by ezyang** [comment]
You "fixed" all the errors by just adding stacklevel=1. But is the point of this lint not to warn you that you maybe want stacklevel=2 or more?

**Comment by Silv3S** [comment]
> all the errors by just adding stacklevel=1. But is the point of this lint not to warn you that you maybe want stacklevel=2 or more?

I just added `stacklevel=1` to each warning as it's default value of this method. As this is lint PR my goal was to do minimal changes, without impacting current code logic. Nevertheless if someone creates new warning, it will be required to set `stacklevel` according to needs.

**Comment by ezyang** [comment]
Ok here's the deal. I don't think there is any way to correctly fix this lint without manually inspecting each site to determine if you are in library code (stacklevel=2) or in user code (stacklevel=1). Bulk editing destroys our knowledge on whether or not a site has been audited or not.

It seems legitimate to want to turn on the lint to forestall future unspecified additions. So I will accept a codemod if you make it clear a site is unaudited (maybe a global constant instead of literal 1) and then promise to go and audit them to figure it 1 or 2 (or perhaps taking stacklevel as an argument) is warranted

**Comment by Silv3S** [comment]
Ok, so I will continue to manually inspect which `stacklevel` is appropriate for each warning. I've reviewed existing warnings and there are only 30 warnings where `stacklevel` is set explicitly and 474 are left with default value (`stacklevel=1`):
- `stacklevel=1` - 1 warning,
- `stacklevel=2` - 23 warnings,
- `stacklevel=3` - 4 warnings,
- `stacklevel=4` - 1 warning,
- `stacklevel=5` - 1 warning.

As there are not much examples I find it difficult to decide which `stacklevel` is appropriate for each case. Could you please advice which criteria should be used to distinguish them? What did you mean by saying library code and user code?

**Comment by ezyang** [comment]
I skimmed the patch.

- There are a bunch of cases where stacklevel doesn't matter, e.g., in the test suite. You can bulk rename them whatever, I don't care.
- There are a bunch of plain cli scripts that have warnings. Those are fine stacklevel=1, you just want to report where the warning is
- If a warning is in a public API function in PyTorch, you probably want stacklevel=2

**Pull request closed without merging**
