### PR TITLE
fx Graph should copy meta on deepcopy

### PR DESCRIPTION
**Pull request by qihqi**
Summary:
fx Graph should copy meta on deepcopy

Test Plan:
Unit test

Reviewers:

Subscribers:

Tasks:

Tags:

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by zhxchen17 — APPROVED** [review]

**Comment by jerryzh168** [comment]
would be nice to add Summary and Test Plan as well

**Comment by jerryzh168** [comment]
small nit: for test plan, can you add a command, so that if some test fails, other people can fix and verify with the test command, example: https://github.com/pytorch/pytorch/pull/92341

**Pull request closed without merging**
