### PR TITLE
Allow overwriting kernels

### PR DESCRIPTION
**Pull request by smessmer**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #19777 Allow overwriting kernels&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D15090318/)
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#19776 Refactorings to prepare for overwritable kernels**&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D15090322/)

When used from iPython/Jupyter/Bento, the cell doing kernel registration might be executed multiple times.
Also, there might be a kernel library that wants to overwrite one of the existing kernels.
Let's allow this.

Differential Revision: [D15090318](https://our.internmc.facebook.com/intern/diff/D15090318/)

### CODE REVIEW

**Comment by dzhulgakov** [comment]
Build is broken, otherwise - sure

**Review by dzhulgakov — APPROVED** [review]

**Review by li-roy — APPROVED** [review]

**Comment by li-roy** [comment]
One question: what's going to be the usecase of fallback kernels? Wouldn't we always prefer to register kernels specifically?

**Comment by smessmer** [comment]
@li-roy Meta-ops (i.e. ops calling other ops) often don't care about the device and just want one kernel for all devices. They'll register a kernel without a dispatch key. Also, custom ops written by PyTorch users often don't need dispatching functionality because they already know which device they're running the model on.

**Pull request closed without merging**
