### PR TITLE
Update sparse_funcs to include primtorch types

### LINKED ISSUE #107335: Update generic operator tests to run for primtorch ops
## Issue description

Currently most of the operator groupings in [common_method_invocations](https://github.com/pytorch/pytorch/blob/8507b22fea9ef819452655aa6dd1c42752a4e74a/torch/testing/_internal/common_methods_invocations.py#L20638-L20651) don't include the reference operators and this could lead to unintended mismatch in operator functionality between eager ops and primtorch ops slipping through. Some cases have already been seen of this while creating https://github.com/pytorch/pytorch/pull/104489.  This is issue is being created in order to track and breakdown the changes to multiple pull requests for more manageable pieces for review. The `sparse_*` groupings cannot be currently updated as it seems that sparse tensor support for primtorch is is not yet complete.

https://github.com/pytorch/pytorch/blob/8507b22fea9ef819452655aa6dd1c42752a4e74a/torch/testing/_internal/common_methods_invocations.py#L20638-L20651
- [ ] Update `unary_ufuncs` groupings
- [ ] Update `binary_ufuncs` groupings
- [ ] Update `spectral_funcs` groupings
- [ ] Update `sparse_unary_ufuncs` groupings
- [ ] Update `sparse_csr_unary_ufuncs` groupings
- [ ] Update `sparse_reduction_ops` groupings
- [ ] Update `shape_funcs` groupings
- [ ] Update `reduction_ops` groupings

cc @ezyang @mruberry @Lezcano @peterbell10

### PR DESCRIPTION
**Pull request by ekamiti**
Fixes #107335.

A few issues have been identified while enabling this test and filed:
https://github.com/pytorch/pytorch/issues/105986
https://github.com/pytorch/pytorch/issues/108204
https://github.com/pytorch/pytorch/issues/108205

### CODE REVIEW

**Comment by ekamiti** [comment]
@ezyang Thank you for reviewing my other test changes, if you could look at this one as well if you have a chance I'd appreciate it.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
failure looks legit, but just needs some tweaking it seems

**Comment by ekamiti** [comment]
> failure looks legit, but just needs some tweaking it seems

Thanks for checking! Yeah, seems like the tests may not run for all the devices all the time and the different devices have different messages which further highlights the issues with inconsistency. I've updated for the hip/mps messages now and if anything else gets flagged I can fix it as well.

**Pull request closed without merging**
