### PR TITLE
[FX] Modified __deepcopy__ to also copy _codegen

### PR DESCRIPTION
**Pull request by angelayi**

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
LGTM, modulo the additional point about deepcopying codegen.

**Comment by janeyx99** [comment]
> Merge failed due to list index out of range Raised by https://github.com/pytorch/pytorch/actions/runs/2190973281

@malfet could this be related to your latest exclusion?

**Comment by malfet** [comment]
This is something different, will have a look in 10 min

**Comment by malfet** [comment]
@angelayi can you please rebase your PR (it has 107 commits so we can't fetch all the authors (though I though I've fixed it in the past))

**Pull request closed without merging**
