### PR TITLE
[BE]: Update Typeguard to TypeIs for better type inference

### PR DESCRIPTION
**Pull request by Skylion007**
Uses TypeIs instead of TypeGuard for better inference. See https://peps.python.org/pep-0742/

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @malfet @xuzhao9 @gramster @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @rec @xmfan

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by jeanschmidt** [comment]
We're having the following error in most internal signals:

```
ImportError: cannot import name 'TypeIs' from 'typing_extensions'
```

:(

**Comment by brothergomez** [comment]
bumping `typing_extensions` to `4.10.0` should fix this, if that is acceptable.

**Comment by ezyang** [comment]
Uhh i doubt that is going to work

**Comment by Skylion007** [comment]
> @pytorchbot revert -c nosignal -m "root cause of internal failures not addressed"

Do you have some internal failure error logs? Or does the requirements needed to be bumped somewhere else as well?

**Comment by Skylion007** [comment]
Ah, think I found the other requirements.txt

**Comment by ezyang** [comment]
No, this is "we need to update the typing_extension version we use internally". You're blocked on me.

Internal diff stack: https://www.internalfb.com/diff/D61602943

**Comment by ezyang** [comment]
Internal typing_extensions was updated in https://www.internalfb.com/diff/D61934796

**Comment by ezyang** [comment]
@Skylion007 mind rebasing this? I'll land it after

**Comment by Skylion007** [comment]
@ezyang Rebased

**Comment by ezyang** [comment]
It did in fact fix the errors lol

**Comment by Skylion007** [comment]
How is it causing the errors lol?

**Comment by Skylion007** [comment]
Is it related to the docker upgrade?

**Comment by Skylion007** [comment]
Digging into the logs more, it's a diffusers update that is breaking our custom diffusers logic `torch/_dynamo/variables/dicts.py`. This PR isn't the cause and any docker-ci change that forces diffusers to be installed will likely break it. I can't figure out where the diffusers version is pinned either.

**Comment by Skylion007** [comment]
Correction, it's diffuers not interacting well with HuggingFace hub:
```
 from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/opt/conda/envs/py_3.10/lib/python3.10/site-packages/huggingface_hub/__init__.py)
```

**Comment by ezyang** [comment]
oh the problem was there was some problem with updating docker files. Maybe rebase will work

**Pull request closed without merging**
