### PR TITLE
Enable CUDA 12.4.1

### PR DESCRIPTION
**Pull request by nWEIdia**
Trying to keep a record of the steps before I lose track of it. 

- 1st Commit: Similar to https://github.com/pytorch/builder/pull/1720 
- 2nd Commit:  Update CUDA 12.4 CI CUDA versions from 12.4.0 to 12.4.1 mapping to changes in https://github.com/pytorch/pytorch/pull/125944/files
- 3rd Commit: update for aarch64 install_cuda_aarch64.sh docker step
- 4th Commit: https://github.com/pytorch/pytorch/pull/132202/commits/aaa456e3e691b0aaf4bb7210cc29aad1fe1e81c2 Related https://github.com/pytorch/pytorch/pull/121684
- Synchronization point: Meta helps uploading pypi cuda dependencies specified in .github/scripts/generate_binary_build_matrix.py
- The above pypi upload is done (thanks Andrey!), restarted jobs like https://github.com/pytorch/pytorch/actions/runs/10188203670/job/28369471321 
- https://github.com/pytorch/pytorch/pull/132202/commits/77532344e35f7bd8d6e4c221e1b6807e17734204, use temporary docker containers (generated from a previous successful container build). If merged, these containers would be rebuilt, therefore testing them now.  (5th commit)
- 6th commit https://github.com/pytorch/pytorch/pull/132202/commits/5f93c625b52f8d8555aae0ce1284d4ffbcf8f6b2: revert the 5th commit. Update, done but have to debug seemingly irrelevant failures (rocm/xpu/mps)

update: 
Post Merge:
Step 1: TLDR, watch for simultaneous pytorch/test-infra AMI updates that could break in-between green signals and final landing. See https://github.com/pytorch/pytorch/pull/132202#issuecomment-2300007290 
Step 2: Since this is CUDA 12.4.0 -> CUDA 12.4.1 bump, on the Windows side, just need to check the driver version is bumped according to CUDA12.4.1 version's recommended driver version. 
https://github.com/pytorch/test-infra/blob/0c3a2634aaa2f638c8f640e743f03d696ce1191f/aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1#L33 
still shows 551.61, needs to bump to 551.78 according to Table 3 of https://docs.nvidia.com/cuda/archive/12.4.1/cuda-toolkit-release-notes/index.html
Step 3: Trigger inductor performance testing, e.g. https://github.com/pytorch/pytorch/actions/runs/10527627251

cc @atalman @ptrblck @eqy @tinglvv @malfet

### CODE REVIEW

**Comment by nWEIdia** [comment]
> What's the goal of updating the minor version? Are there important perf / bug fixes? Does it update the minimum driver version or requirements? If we are doing this we should also consider updating NCCL and CUDNN in a concurrent PR probably.

The update originally comes from the suggestion of @malfet and @ptrblck to always use the maximum minor version of CUDA 12.4 which is CUDA 12.4.1. 
At least it would fix nanogpt smoke test regression, see  https://github.com/pytorch/pytorch/blob/main/.ci/pytorch/test.sh#L640

The Linux minimum driver version (550.54.15) needed by CUDA 12.4.1 was [already adopted](https://github.com/pytorch/test-infra/commit/d5695df7271be0bfac6090058fb2980ab3052d3f) when enabling CUDA 12.4.0 [yeah, we probably should have just enabled CUDA 12.4.1 then]. Only the Windows side, the driver may need a bump. 

NCCL and CUDNN with CUDA 12.4.1 may work similar to CUDA 12.4.0, we could consider updating them though.

**Review by Skylion007 — APPROVED** [review]

**Comment by nWEIdia** [comment]
For Pip Binary/jobs: 
Also: https://[ossci-raw-job-status.s3.amazonaws.com/log/28186744872](https://ossci-raw-job-status.s3.amazonaws.com/log/28186744872) error below
 pip install /final_pkgs/torch-2.5.0.dev20240731+cu124-cp310-cp310-linux_x86_64.whl --index-url https://download.pytorch.org/whl/nightly/cu124
No matching distribution found for nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64"
says the pypi packages have to be copied and hosted from aws s3 pytorch (https://download.pytorch.org/whl/nightly/cu124). 

For Conda Binary/jobs: 
Linking: https://github.com/pytorch/builder/pull/1947

**Comment by Skylion007** [comment]
@atalman Can help with the nightly packages

**Comment by Skylion007** [comment]
Also pinging @malfet . @nWEIdia Are they are any older versions of CUDA we do should do minor version bumps to? Like 11.8 or 12.1?

**Comment by atalman** [comment]
@nWEIdia @Skylion007 uploading packages now for 12.4 and 12.4 split build.

**Comment by nWEIdia** [comment]
> Also pinging @malfet . @nWEIdia Are they are any older versions of CUDA we do should do minor version bumps to? Like 11.8 or 12.1?

https://developer.nvidia.com/cuda-toolkit-archive shows CUDA 11.8 does not have patch versions. It looks like 12.1 indeed has an update 1. Fortunately, upstream pytorch already comes with 12.1.1 as indicated by https://github.com/pytorch/pytorch/blob/main/.github/scripts/generate_binary_build_matrix.py#L21

**Review by eqy — APPROVED** [review]

**Review by atalman — APPROVED** [review]
lgtm, please make sure manywheels builds are green, revert temp change and merge

**Comment by nWEIdia** [comment]
Looks like the signal is green for CUDA tests but the 6 pending jobs are due to long queue of runner linux.9xlarge.ephemeral 

cc @atalman @malfet

**Comment by nWEIdia** [comment]
For this kind of PRs, it would be great if we can retain the test results from https://github.com/pytorch/pytorch/pull/132202/commits/653b4acf8d9c820ac641ac31134e4a29b861776a

**Comment by nWEIdia** [comment]
Post Merge: 
Step 1:  check https://hud.pytorch.org/pytorch/pytorch/commit/333890b701fc30065e35b6ae6f24908ecb9d81f8 
Observed job failures:  https://github.com/pytorch/pytorch/actions/runs/10476660034/job/29016052870

**Comment by nWEIdia** [comment]
1st bad build: https://github.com/pytorch/pytorch/actions/runs/10433835042/job/28936166917

2024-08-19T09:45:31.8316859Z #15 421.6   Installing : fipscheck-1.4.1-6.el7.x86_64                                2/73 
2024-08-19T09:52:25.7608721Z #15 421.7   Installing : fipscheck-lib-1.4.1-6.el7.x86_64                            3/73  

See the 7 minutes gap!! 

Last known good build: https://github.com/pytorch/pytorch/actions/runs/10425348037/job/28876036438 
The installation of these two are instant!

Could the runner be from a different region? If not, the multiple "RUN sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo" seems suspicious.

cc @atalman @malfet @ptrblck

**Comment by atalman** [comment]
@nWEIdia Looks like this is maybe related to AMI update:
Last successful build: https://github.com/pytorch/pytorch/actions/runs/10424302444/job/28872834620 uses AMI Name: amzn2-ami-hvm-2.0.20240306.2-x86_64-ebs

Current build takes 5hrs and uses:
https://github.com/pytorch/pytorch/actions/runs/10463836139/job/28976474949
AMI Name: al2023-ami-2023.5.20240701.0-kernel-6.1-x86_64

**Comment by ZainRizvi** [comment]
yeah, this does seem related to the new Amazon Linux 2023 ami upgrade. The green builds all use the Amazon 2 AMI while the red ones are on Amazon 2023.  @atalman is working on a mitigation PR

**Comment by nWEIdia** [comment]
Thanks @atalman and @ZainRizvi .  A hypothesis is that the difference between Amazon 2 AMI and Amazon 2023 might just be the yum/repo.d URLs. They seem to be functionally equivalent, just the beginning "sed" commands that may have messed up the package downloading speed. 

```
$ grep RUN good-1.txt  |head -n 20
2024-08-17T16:53:47.0736457Z #9 [common  2/21] RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
2024-08-17T16:53:48.1702057Z #10 [base  2/15] RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
2024-08-17T16:53:48.3237208Z #9 [common  2/21] RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
2024-08-17T16:53:48.3238674Z #11 [common  3/21] RUN sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
2024-08-17T16:53:48.6916116Z #12 [base  3/15] RUN sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
2024-08-17T16:53:48.8858602Z #11 [common  3/21] RUN sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
2024-08-17T16:53:48.8859988Z #13 [common  4/21] RUN sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
2024-08-17T16:53:49.4404040Z #14 [base  4/15] RUN sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
2024-08-17T16:53:49.6462087Z #13 [common  4/21] RUN sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
2024-08-17T16:53:49.6464219Z #15 [common  5/21] RUN yum install -y         aclocal         autoconf         automake         bison         bzip2         curl         diffutils         file         git         make         patch         perl         unzip         util-linux         wget         which         xz         yasm 
```

vs. bad: 

```
$ grep RUN bad-1.txt  |head -n 20
T17:57:47Z #11 [common  2/21] RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
T17:57:48Z #12 [base  2/15] RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
T17:57:48Z #11 [common  2/21] RUN sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo
T17:57:48Z #13 [common  3/21] RUN sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
T17:57:49Z #14 [base  3/15] RUN sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo
T17:57:49Z #15 [base  4/15] RUN sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
T17:57:51Z #16 [common  4/21] RUN sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
T17:57:51Z #17 [common  5/21] RUN yum install -y         aclocal         autoconf         automake         bison         bzip2         curl         diffutils         file         git         make         patch         perl         unzip         util-linux         wget         which         xz         yasm
T17:57:51Z #15 [base  4/15] RUN sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo
T17:57:51Z #18 [base  5/15] RUN yum install -y wget curl perl util-linux xz bzip2 git patch which perl zlib-devel
2024-08-20T17:58:00.7846574Z #17 [common  5/21] RUN yum install -y         aclocal         autoconf         automake         bison         bzip2         curl         diffutils         file         git         make         patch         perl         unzip         util-linux         wget         which         xz         yasm
2024-08-20T18:04:53.8543252Z #18 [base  5/15] RUN yum install -y wget curl perl util-linux xz bzip2 git patch which perl zlib-devel
2024-08-20T18:05:00.8610583Z #17 [common  5/21] RUN yum install -y         aclocal         autoconf         automake         bison         bzip2         curl         diffutils         file         git         make         patch         perl         unzip         util-linux         wget         which         xz         yasm
2024-08-20T18:11:44.9718868Z #18 [base  5/15] RUN yum install -y wget curl perl util-linux xz bzip2 git patch which perl zlib-devel
2024-08-20T18:11:59.6193233Z #17 [common  5/21] RUN yum install -y         aclocal         autoconf         automake         bison         bzip2         curl         diffutils         file         git         make         patch         perl         unzip         util-linux         wget         which         xz         yasm
```

**Comment by nWEIdia** [comment]
Post merge Step 4: 
Missed steps: aarch64 binary validation (building was ok, validation of the binary in builder repo was not)

https://github.com/pytorch/builder/actions/runs/10776424717/job/29883178793#step:12:4025

**Comment by tinglvv** [comment]
Above aarch64 build failure  is seen on cuda aarch64.
Error https://github.com/pytorch/builder/actions/runs/10776424717/job/29883178793#step:12:4025
```
++ python3 ./test/smoke_test/smoke_test.py --package torchonly
Traceback (most recent call last):
  File "/pytorch/builder/./test/smoke_test/smoke_test.py", line 9, in <module>
    import torch._dynamo
  File "/opt/conda/envs/conda-env-10794919545/lib/python3.9/site-packages/torch/_dynamo/__init__.py", line 3, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "/opt/conda/envs/conda-env-10794919545/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 53, in <module>
    from . import config, exc, trace_rules
  File "/opt/conda/envs/conda-env-10794919545/lib/python3.9/site-packages/torch/_dynamo/trace_rules.py", line 45, in <module>
    from .utils import getfile, hashable, NP_SUPPORTED_MODULES, unwrap_if_wrapper
ImportError: cannot import name 'NP_SUPPORTED_MODULES' from 'torch._dynamo.utils' (/opt/conda/envs/conda-env-10794919545/lib/python3.9/site-packages/torch/_dynamo/utils.py)
```
Will need to see if this is due to CUDA 12.4.1 upgrade and fix it for 2.5.0 release

cc @atalman

**Pull request closed without merging**
