### PR TITLE
Refactor ShapeEnvSettings so it's directly on ShapeEnv

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #122310

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by masnesral — APPROVED** [review]
nice and clean

**Review by lezcano — APPROVED** [review]

**Pull request closed without merging**
