### PR TITLE
add BFloat16 support for UpSample on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #76935

Differential Revision: [D36193365](https://our.internmc.facebook.com/intern/diff/D36193365)

### CODE REVIEW

**Comment by mingfeima** [comment]
Resubmit #58297

**Comment by frank-wei** [comment]
@frank-wei has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36193365).

**Comment by frank-wei** [comment]
@frank-wei has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36193365).

**Review by frank-wei — APPROVED** [review]
https://github.com/pytorch/pytorch/pull/58297 already approved.

**Pull request closed without merging**
