### PR TITLE
[Structured Kernels] Port `cross` to structured kernels

### PR DESCRIPTION
**Pull request by krshrimali**
This PR ports `cross` to structured kernels. Please see https://github.com/pytorch/pytorch/issues/55070 for the tracker issue.

**Notes:**

* Earlier `input.device().type()` was used to get the output tensor device type, which I believe was incorrect. This has been corrected in this PR.
* Out skip has been removed in this PR, an outcome of porting to structured kernels.
* We had checks to ensure an error is raised if a device except CUDA and CPU is passed, these checks have been removed now. Since we now support `meta` as well.

cc: @ysiraichi @ezyang

### CODE REVIEW

**Comment by krshrimali** [comment]
Hi @ysiraichi - Would you mind doing the first review here, if you have the time? Tests on my system pass, but I'm waiting for the CI to give the green signal.

@ezyang - In case Yukio has any suggestions for this PR, I'll address them first and request your review so that you have to spend less time reviewing :) I hope that sounds good to you.

**Comment by AnirudhDagar** [comment]
@krshrimali can we wait for #63285 which is probably ready to go (cc @Lezcano @mruberry)? I was actually planning to pick this up following that PR but it is okay since you've already opened this now.

**Comment by Lezcano** [comment]
We should indeed wait until https://github.com/pytorch/pytorch/pull/63285 lands and kill two birds with one stone.

**Comment by krshrimali** [comment]
> @krshrimali can we wait for #63285 which is probably ready to go (cc @Lezcano @mruberry)? I was actually planning to pick this up following that PR but it is okay since you've already opened this now.

Cool, waiting for #63285 sounds like a good idea. Also, in case you plan to port `cat` to the structured kernel - let me know or comment in the issue tracker, I have that next in the list (once the current PR on aliasing is landed). :)

Thanks for checking and staying updated with the PRs btw. :)

**Comment by krshrimali** [comment]
Closing in favor of: https://github.com/pytorch/pytorch/pull/72413.

**Pull request closed without merging**
