### PR TITLE
Have Tensor.sort accept descending as only argument

### LINKED ISSUE #2303: Different behavior of variable sort and tensor sort.
```
import torch
x = torch.randn(10)
y = torch.autograd.Variable(x)

y.sort(descending=True)
x.sort(descending=True)
```

Got error when executing last line.

> TypeError: sort received an invalid combination of arguments - got (descending=bool, ), but expected one of:
>  * ()
>       didn't match because some of the keywords were incorrect: descending
>  * (int dim)
>  * (int dim, bool descending)

torch version 0.2.0_1

### PR DESCRIPTION
**Pull request by lantiga**
Fixes #2303

### CODE REVIEW

**Comment by gchanan** [comment]
This will make tensor and Variable sort inconsistent in a different way:
```
>>> x=torch.randn(10)
>>> y=Variable(x)
>>> x.sort(True)
...
>>> y.sort(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/gchanan/pytorch8a/torch/autograd/variable.py", line 505, in sort
    return Sort.apply(self, dim, descending, True)
  File "/data/users/gchanan/pytorch8a/torch/autograd/_functions/tensor.py", line 524, in forward
    return _MultiSelectionFunction.forward(ctx, input, dim, return_indices, args)
  File "/data/users/gchanan/pytorch8a/torch/autograd/_functions/tensor.py", line 497, in forward
    output, indices = fn(*args)
TypeError: sort received an invalid combination of arguments - got (bool, bool), but expected one of:
 * ()
 * (int dim)
      didn't match because some of the arguments have invalid types: (bool, bool)
 * (bool descending)
      didn't match because some of the arguments have invalid types: (bool, bool)
 * (int dim, bool descending)
```

**Comment by lantiga** [comment]
Right! Sort.forward passes a bool as dim to the TH function.
Checking the type of the first argument to Sort.forward in autograd/_functions/tensor.py should do.

**Comment by lantiga** [comment]
I'll take it back, `x.sort(True)` should fail in any case.
Having `descending` as `kwargs_only: True` in case dim is not provided is the way to go.

This allows the following to be valid on both a Tensor and a Variable:
```
x.sort(0)
x.sort(dim=0)
x.sort(descending=True)
x.sort(dim=0, descending=True)
x.sort(0, descending=True)
x.sort(0,True)
```
and
```
x.sort(True)
x.sort(dim=0, True)
```
to fail for both.

I'm updating the PR.

**Comment by gchanan** [comment]
kwarg looks like the right way to go.  Can the entire args list be simplified as follows or am I missing something?
```
    - before_call: long __last_dim = THTensor_(nDimension)(LIBRARY_STATE ((THPTensor*)$arg2)->cdata)-1;
      arguments:
        - arg: THTensor* values
          output: True
        - arg: THIndexTensor* indices
          output: True
        - THTensor* self
        - CONSTANT __last_dim
        - arg: bool descending
          default: "false"
          kwarg_only: True
    - arguments:
        - arg: THTensor* values
          output: True
        - arg: THIndexTensor* indices
          output: True
        - THTensor* self
        - arg: long dim
          wrap_dim: self
        - arg: bool descending
          default: "false"
```

**Comment by lantiga** [comment]
Very likely, I'll fix this asap

**Comment by lantiga** [comment]
@gchanan Done, thank you

**Pull request merged**
