### PR TITLE
Add stub for transformer.py and MultiheadAttention Class.

### PR DESCRIPTION
**Pull request by yyb1995**
Add stub for `transformer.py` and `class MultiheadAttention`. Add import for `transformer.py`  and `class MultiheadAttention` in `__init__.pyi.in`. I've tested the code hint in PyCharm and all works file.
Relate issue: [#27842](https://github.com/pytorch/pytorch/issues/27842)
@ezyang

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
The type annotations are not very precise, but better than nothing I suppose.

**Comment by ezyang** [comment]
Tests failing for real

```

Oct 22 05:29:53 OK
Oct 22 05:29:53 Running test_type_hints ... [2019-10-22 05:29:53.235407]
Oct 22 05:29:54 test_doc_examples (__main__.TestTypeHints) ... torch/nn/modules/__init__.pyi:48: error: unexpected character after line continuation character
Oct 22 05:29:54 Found 1 error in 1 file (checked 1 source file)
Oct 22 05:29:54 FAIL
Oct 22 05:29:54 
Oct 22 05:29:54 ======================================================================
Oct 22 05:29:54 FAIL: test_doc_examples (__main__.TestTypeHints)
Oct 22 05:29:54 ----------------------------------------------------------------------
Oct 22 05:29:54 Traceback (most recent call last):
Oct 22 05:29:54   File "test_type_hints.py", line 169, in test_doc_examples
Oct 22 05:29:54     check=True)
Oct 22 05:29:54 subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-mmypy', '--follow-imports', 'silent', '--check-untyped-defs', '/var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py']' returned non-zero exit status 2.
Oct 22 05:29:54 
Oct 22 05:29:54 During handling of the above exception, another exception occurred:
Oct 22 05:29:54 
Oct 22 05:29:54 Traceback (most recent call last):
Oct 22 05:29:54   File "test_type_hints.py", line 171, in test_doc_examples
Oct 22 05:29:54     raise AssertionError("mypy failed.  Look above this error for mypy's output.")
Oct 22 05:29:54 AssertionError: mypy failed.  Look above this error for mypy's output.
Oct 22 05:29:54 
```

**Review by ezyang — CHANGES_REQUESTED** [review]
build broken

**Review by ezyang — APPROVED** [review]
waiting on ci

**Comment by yyb1995** [comment]
Oops，I accidentally add a redundant space after `\`. Quite sorry for taking up your time. This time it should work fine.

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit dcde1515:


* **1/1** failures introduced in this PR


---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Pull request closed without merging**
