### PR TITLE
WIP: Fix build issues due to hardcoded /usr/local/cuda/lib64/libculibos.a

### LINKED ISSUE #15476: Loading a PyTorch Model in C++ tutorial fails with No rule to make target '/usr/local/cuda/lib64/libculibos.a'
hi all
  Follow the tutorial(Loading a PyTorch Model in C++)
1.cmake
-- Caffe2: CUDA detected: 10.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda-10.0/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-10.0
-- Caffe2: Header version is: 10.0
-- Found cuDNN: v7.4.2  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX
-- Added CUDA NVCC flags for: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_70,code=compute_70
-- Configuring done
-- Generating done
2. make
make[2]: *** No rule to make target '/usr/local/cuda/lib64/libculibos.a', needed by 'example-app'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/example-app.dir/all' failed
make[1]: *** [CMakeFiles/example-app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

please ....

### PR DESCRIPTION
**Pull request by rgommers**
In the current libtorch nightlies, the file `libtorch/share/cmake/Caffe2/Caffe2Targets.cmake` contains:
```
INTERFACE_LINK_LIBRARIES "caffe2::cudart;c10_cuda;caffe2;caffe2::cufft;caffe2::curand;caffe2::cudnn;/usr/local/cuda/lib64/libculibos.a;dl;/usr/local/cuda/lib64/libculibos.a;caffe2::cublas"
```

So `libculibos.a` is included twice, with the full path.  That hardcoded `/usr/local/cuda` should instead be `${CUDA_TOOLKIT_ROOT_DIR}`. There are distributions (e.g. Arch Linux and derivatives) where the install location is `/opt/cuda` instead, and that results in users not
being able to build C++ extensions.

The root cause of the issue is that all dependencies were added to a list,  `Caffe2_PUBLIC_CUDA_DEPENDENCY_LIBS`. Adding strings to a list directly causes variable expansion.  The only way to preserve `${CUDA_TOOLKIT_ROOT_DIR}` seems to be to not use that list + `target_link_libraries`. Instead use the more standard `set_property(TARGET torch PROPERTY INTERFACE_LINK_LIBRARIES ...)`. A bit more verbose, but more robust.

To reproduce the issue:

1. download the latest `libtorch` nightly
2. Use, e.g., `example-app.cpp` from https://pytorch.org/tutorials/advanced/cpp_export.html/torch_script_custom_ops.html (follow steps 1,2,3). Your test directory looks like:
  `CMakeLists.txt  example-app.cpp  libtorch/  model.pt`
3. Use the following `build_example.sh` script:
```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/home/rgommers/code/tmp/issue15476/libtorch ..
make
cd ..
```
4. `$ source build_example.sh` this will end with `No rule to make target '/usr/local/cuda/lib64/libculibos.a', needed by 'example-app'`.

Now with a `libtorch` binary produced with this fix included, that should work.

Note, I verified that removing `libculibos.a` completely from `Caffe2Targets.cmake` will fix the example app, but as explained by @pjh5 in https://github.com/pytorch/pytorch/issues/15476#issuecomment-515558702 that's only due to what `pytorch/builder` does. We can't leave out the dependency from the build scripts. This is the fix with minimal changes in the logic and no change in ordering of dependencies that I could come up with.

Closes gh-15476. Note, after merging I will go back and verify that the other issues that were closed as duplicates of gh-15476 are also fixed. Also note, I didn't manage to reproduce what `pytorch/builder` does locally exactly; if it's possible to get the build artifacts from the same CI job that produces the nightly before merging, that would be helpful. If not, this is small enough to review and be confident about it not breaking anything if CI passes.

### CODE REVIEW

**Comment by rgommers** [comment]
Thought about a better way to test this, in addition to the manual "it works now". In the CI jobs that test `libtorch`, walk the source tree, find the relevant generated files (`*Targets.cmake`?), check contents of each file to ensure the string `/usr/local/cuda/` is only present in comments.

**Comment by ezyang** [comment]
BTW, if you want people to review this PR, don't forget to add reviewers ;)

**Comment by rgommers** [comment]
> BTW, if you want people to review this PR, don't forget to add reviewers ;)

I know, it's still WIP. Weird CI issues over the weekend, so I couldn't tell if this worked at all or not. I'm confident that I found the problem, but only confident this is good to review once CI is green.

**Comment by szagoruyko** [comment]
thanks @rgommers ! would be great to include this in 1.2 https://github.com/pytorch/pytorch/issues/23555

**Review by ezyang — APPROVED** [review]

**Comment by rgommers** [comment]
details of failures (unclear if related, rerunning to check):

<details>

```
Aug 01 14:01:02 [ 85%] Linking CXX shared library ../lib/libtorch.so
Aug 01 14:01:16 [ 85%] Built target torch
Aug 01 14:01:16 Scanning dependencies of target utility_ops_gpu_test
Aug 01 14:01:16 [ 85%] Building CXX object caffe2/CMakeFiles/utility_ops_gpu_test.dir/operators/utility_ops_gpu_test.cc.o
Aug 01 14:01:16 Scanning dependencies of target operator_fallback_gpu_test
Aug 01 14:01:16 [ 85%] Building CXX object caffe2/CMakeFiles/operator_fallback_gpu_test.dir/operators/operator_fallback_gpu_test.cc.o
Aug 01 14:01:16 Scanning dependencies of target roi_align_op_gpu_test
Aug 01 14:01:16 [ 85%] Building CXX object caffe2/CMakeFiles/roi_align_op_gpu_test.dir/operators/roi_align_op_gpu_test.cc.o
Aug 01 14:01:17 [ 85%] Linking CXX executable ../bin/utility_ops_gpu_test
Aug 01 14:01:17 [ 85%] Linking CXX executable ../bin/operator_fallback_gpu_test
Aug 01 14:01:17 [ 85%] Linking CXX executable ../bin/roi_align_op_gpu_test
Aug 01 14:01:17 /usr/bin/ld: CMakeFiles/utility_ops_gpu_test.dir/operators/utility_ops_gpu_test.cc.o: undefined reference to symbol '_ZN6google10LogMessageC1EPKci'
Aug 01 14:01:17 //usr/lib/x86_64-linux-gnu/libglog.so.0: error adding symbols: DSO missing from command line
Aug 01 14:01:17 collect2: error: ld returned 1 exit status
Aug 01 14:01:17 caffe2/CMakeFiles/utility_ops_gpu_test.dir/build.make:99: recipe for target 'bin/utility_ops_gpu_test' failed
Aug 01 14:01:17 make[2]: *** [bin/utility_ops_gpu_test] Error 1
Aug 01 14:01:17 make[1]: *** [caffe2/CMakeFiles/utility_ops_gpu_test.dir/all] Error 2
Aug 01 14:01:17 make[1]: *** Waiting for unfinished jobs....
Aug 01 14:01:17 CMakeFiles/Makefile2:3534: recipe for target 'caffe2/CMakeFiles/utility_ops_gpu_test.dir/all' failed
Aug 01 14:01:17 /usr/bin/ld: CMakeFiles/operator_fallback_gpu_test.dir/operators/operator_fallback_gpu_test.cc.o: undefined reference to symbol '_ZN6google10LogMessageC1EPKci'
Aug 01 14:01:17 //usr/lib/x86_64-linux-gnu/libglog.so.0: error adding symbols: DSO missing from command line
Aug 01 14:01:17 collect2: error: ld returned 1 exit status
Aug 01 14:01:17 caffe2/CMakeFiles/operator_fallback_gpu_test.dir/build.make:99: recipe for target 'bin/operator_fallback_gpu_test' failed
Aug 01 14:01:17 make[2]: *** [bin/operator_fallback_gpu_test] Error 1
Aug 01 14:01:17 CMakeFiles/Makefile2:3612: recipe for target 'caffe2/CMakeFiles/operator_fallback_gpu_test.dir/all' failed
Aug 01 14:01:17 make[1]: *** [caffe2/CMakeFiles/operator_fallback_gpu_test.dir/all] Error 2
Aug 01 14:01:17 /usr/bin/ld: CMakeFiles/roi_align_op_gpu_test.dir/operators/roi_align_op_gpu_test.cc.o: undefined reference to symbol '_ZN6google10LogMessageC1EPKci'
Aug 01 14:01:17 //usr/lib/x86_64-linux-gnu/libglog.so.0: error adding symbols: DSO missing from command line
Aug 01 14:01:17 collect2: error: ld returned 1 exit status
Aug 01 14:01:17 make[2]: *** [bin/roi_align_op_gpu_test] Error 1
Aug 01 14:01:17 caffe2/CMakeFiles/roi_align_op_gpu_test.dir/build.make:99: recipe for target 'bin/roi_align_op_gpu_test' failed
Aug 01 14:01:17 CMakeFiles/Makefile2:3573: recipe for target 'caffe2/CMakeFiles/roi_align_op_gpu_test.dir/all' failed
Aug 01 14:01:17 make[1]: *** [caffe2/CMakeFiles/roi_align_op_gpu_test.dir/all] Error 2
Aug 01 14:01:17 make: *** [all] Error 2
Aug 01 14:01:17 Makefile:138: recipe for target 'all' failed
Aug 01 14:01:17 Traceback (most recent call last):
Aug 01 14:01:17   File "setup.py", line 748, in <module>
Aug 01 14:01:17 Building wheel torch-1.2.0a0+f8dc244
Aug 01 14:01:17 -- Building version 1.2.0a0+f8dc244
```

```
Aug 01 14:00:47 [ 85%] Linking CXX executable ../bin/generate_proposals_op_util_nms_gpu_test
Aug 01 14:00:47 /usr/bin/ld: CMakeFiles/reshape_op_gpu_test.dir/operators/reshape_op_gpu_test.cc.o: undefined reference to symbol '_ZN3c104cuda20setCurrentCUDAStreamENS0_10CUDAStreamE'
Aug 01 14:00:47 //var/lib/jenkins/workspace/build/lib/libc10_cuda.so: error adding symbols: DSO missing from command line
Aug 01 14:00:47 collect2: error: ld returned 1 exit status
Aug 01 14:00:48 caffe2/CMakeFiles/reshape_op_gpu_test.dir/build.make:88: recipe for target 'bin/reshape_op_gpu_test' failed
Aug 01 14:00:48 make[2]: *** [bin/reshape_op_gpu_test] Error 1
Aug 01 14:00:48 CMakeFiles/Makefile2:3480: recipe for target 'caffe2/CMakeFiles/reshape_op_gpu_test.dir/all' failed
Aug 01 14:00:48 make[1]: *** [caffe2/CMakeFiles/reshape_op_gpu_test.dir/all] Error 2
Aug 01 14:00:48 make[1]: *** Waiting for unfinished jobs....
Aug 01 14:00:48 /usr/bin/ld: CMakeFiles/utility_ops_gpu_test.dir/operators/utility_ops_gpu_test.cc.o: undefined reference to symbol '_ZN3c104cuda20setCurrentCUDAStreamENS0_10CUDAStreamE'
Aug 01 14:00:48 //var/lib/jenkins/workspace/build/lib/libc10_cuda.so: error adding symbols: DSO missing from command line
Aug 01 14:00:48 collect2: error: ld returned 1 exit status
Aug 01 14:00:48 caffe2/CMakeFiles/utility_ops_gpu_test.dir/build.make:88: recipe for target 'bin/utility_ops_gpu_test' failed
Aug 01 14:00:48 make[2]: *** [bin/utility_ops_gpu_test] Error 1
Aug 01 14:00:48 CMakeFiles/Makefile2:3441: recipe for target 'caffe2/CMakeFiles/utility_ops_gpu_test.dir/all' failed
Aug 01 14:00:48 make[1]: *** [caffe2/CMakeFiles/utility_ops_gpu_test.dir/all] Error 2
Aug 01 14:00:48 /usr/bin/ld: CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/operators/generate_proposals_op_util_nms_gpu_test.cc.o: undefined reference to symbol '_ZN3c104cuda20setCurrentCUDAStreamENS0_10CUDAStreamE'
Aug 01 14:00:48 //var/lib/jenkins/workspace/build/lib/libc10_cuda.so: error adding symbols: DSO missing from command line
Aug 01 14:00:48 collect2: error: ld returned 1 exit status
Aug 01 14:00:48 caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/build.make:88: recipe for target 'bin/generate_proposals_op_util_nms_gpu_test' failed
Aug 01 14:00:48 make[2]: *** [bin/generate_proposals_op_util_nms_gpu_test] Error 1
Aug 01 14:00:48 CMakeFiles/Makefile2:3519: recipe for target 'caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/all' failed
Aug 01 14:00:48 make[1]: *** [caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/all] Error 2
Aug 01 14:00:48 Makefile:140: recipe for target 'all' failed
Aug 01 14:00:48 make: *** [all] Error 2
Aug 01 14:00:48 -- Building version 1.2.0a0+f8dc244
```

</details>

**Comment by ezyang** [comment]
Build failures seem legit, and related to this PR.

**Comment by ngoldbaum** [comment]
Ah I see, I'll reissue this from my fork so I can more easily work on this. Taking over for Ralf while he recovers from some health issues.

**Comment by rgommers** [comment]
continued in gh-27607, thanks @ngoldbaum

**Pull request closed without merging**
