### PR TITLE
[DCP] Automatically set `no_dist` if distributed is unavailable

### PR DESCRIPTION
**Pull request by LucasLLC**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #119816
* #119815
* #119814
* __->__ #119813

[DCP] Automatically set `no_dist` if distributed is unavailable

Differential Revision: [D53718043](https://our.internmc.facebook.com/intern/diff/D53718043/)

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Review by fegin — APPROVED** [review]
LGTM

**Review by wz337 — APPROVED** [review]
LG!

**Comment by LucasLLC** [comment]
@wconstab (sorry for the new PR :/ ... ), wrt to this comment https://github.com/pytorch/pytorch/pull/119332#discussion_r1482439969 , I agree a helper function would be useful, but I want to check if it's possible to just have a version of `dist.is_initialized()` which returns `False` when `dist.is_available()` is also `False`, and that might be more involved then makes sense to look into in this PR. I think it probably makes sense to circle back to this in the future

**Pull request closed without merging**
