### PR TITLE
Add support for add in tensorify_python_scalars fx pass

### PR DESCRIPTION
**Pull request by bobrenjc93**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #137782
* #137623
* #137622
* __->__ #137620

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change, but it seems to cause test_torchbind_inductor to fail in trunk https://hud.pytorch.org/pytorch/pytorch/commit/0430e72e755d2c1953917ffb78f00c516eb4bbd5' -c nosignal

For example inductor/test_torchbind.py::TestTorchbind::test_torchbind_inductor [GH job link](https://github.com/pytorch/pytorch/actions/runs/11307422288/job/31453730641) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/0430e72e755d2c1953917ffb78f00c516eb4bbd5)

**Pull request closed without merging**
