### PR TITLE
clip_grad_norm negative

### PR DESCRIPTION
**Pull request by vainaixr**
https://github.com/pytorch/pytorch/issues/31367

### CODE REVIEW

**Review by cpuhrsch — CHANGES_REQUESTED** [review]
nit: I think it'd be easier to read with less negations. As in "max_norm must be positive".

Also, instead of assert this should raise a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) and state the argument that was passed (i.e. the value of max_norm that triggered this.)

**Review by vainaixr — COMMENTED** [review]
without f string error message

**Review by vainaixr — COMMENTED** [review]
change

**Review by vainaixr — COMMENTED** [review]
extra bracket

**Comment by cpuhrsch** [comment]
@vainaijr - Please rebase when you get a chance to resolve failures.

**Comment by cpuhrsch** [comment]
@vainaijr - do you still want to land this?

**Pull request closed without merging**
