### PR TITLE
[Gradient Compression] Simplify the implementation of warm-start

### PR DESCRIPTION
**Pull request by wayi1**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #51094 [Gradient Compression] Refactor default_hooks.py and powerSGD_hook.py by creating a util function that make a vanilla allreduce future
* #50985 [Gradient Compression] Explicitly specify the dtype of the error tensor
* **#50981 [Gradient Compression] Simplify the implementation of warm-start**
* #50974 [Gradient Compression] Typo fixes in PowerSGD
* #50973 [Gradient Compression] Allow PowerSGD to run vallina allreduce for the first K iterations

Since vanilla allreduce will to be applied in the first few iterations, bucket rebuilding process will not affect caching per-variable tensors.

Previously the cached tensors used for error feedback and warm-up need to be rebuilt later, because their corresponding input tensors' shape will be changed after the bucket rebuild process.

Original PR issue: Investigate Applying PowerSGD to Communication Hook for Gradient Compression #47202

Differential Revision: [D26034418](https://our.internmc.facebook.com/intern/diff/D26034418/)

### CODE REVIEW

**Review by rohan-varma — COMMENTED** [review]
I'm not sure if I understand this change. If PowerSGD will be applied in the first few iterations, shouldn't we take into account bucket rebuilding? Bucket rebuilding occurs in the 2nd iteration, so it seems like powerSGD would have to be aware of this?

**Comment by SciPioneer** [comment]
> I'm not sure if I understand this change. If PowerSGD will be applied in the first few iterations, shouldn't we take into account bucket rebuilding? Bucket rebuilding occurs in the 2nd iteration, so it seems like powerSGD would have to be aware of this?

Sorry, I mistyped the description. In the first few iterations, **vanilla allreduce** rather than **PowerSGD** will be used by default. Therefore, we can simplify the warm-start implementation here.

Actually I plan to do this for all the comm hooks in the future, so the comm hook developer won't be bothered by the internal bucketization details. The ultimate goal is to decouple engineering code and research code, and hide the internal implementation details as much as possible -- ideally, a comm hook developer does not need to know how gradients are bucketized in DDP.

**Review by rohan-varma — APPROVED** [review]
Looks good, can you clarify in the code that we are now expecting vanilla allreduce to be run in the first few iterations so this change is clearer? 

Also, would be good to update documentation in the code or anywhere else necessary that we are enforcing vanilla allreduce to be run for the first few iterations. That way comm. hook users won't be surprised that their algorithm doesn't kick in for a few iterations.

Also, please make sure CI is clear before landing.

**Comment by SciPioneer** [comment]
> Looks good, can you clarify in the code that we are now expecting vanilla allreduce to be run in the first few iterations so this change is clearer?
> 
> Also, would be good to update documentation in the code or anywhere else necessary that we are enforcing vanilla allreduce to be run for the first few iterations. That way comm. hook users won't be surprised that their algorithm doesn't kick in for a few iterations.
> 
> Also, please make sure CI is clear before landing.

Thanks for the suggestion! This is already documented in PowerSGDState comments. Now added more comments to `powerSGD_hook` function.

**Pull request closed without merging**
