### PR TITLE
Add test to check that COW inputs are not materialized

### PR DESCRIPTION
**Pull request by kurtamohler**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #119507
* #120455

Part of #97856

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
(some of) test fail looks real

**Comment by kurtamohler** [comment]
Weird, according to the trace for that failing macos job, `materialize_cow_storage` decrements the COWDeleterContext's refcount to 0, and then before `~COWDeleterContext()` is called, the refcount gets incremented somewhere else. So the refcount is nonzero by the time the destructor is invoked, which we have an internal assert to detect. I suppose it must be a race condition. I'll figure out exactly why it's happening

**Comment by kurtamohler** [comment]
It turns out that fixing this race condition is trickier than I thought, unless I'm overlooking something.

Here's a basic example to make sure we're on the same page:

```cpp
Tensor tensor = at::_lazy_clone(at::randn({10}));
int64_t num_thread = 100;
at::parallel_for(0, num_threads, 1, [&](int64_t begin, int64_t end) {
  void* ptr = tensor.mutable_data_ptr();
});
```

Inside of the `mutable_data_ptr()` call, the first thread (thread A) that tries to obtain the mutable pointer will need to materialize the data. When thread A starts doing this, the `StorageImpl`'s `DataPtr`'s `UniqueVoidPtr`'s context is a `COWDeleterContext`.

To materialize the data, thread A needs to replace the `StorageImpl`'s `DataPtr` with a new `DataPtr` that doesn't contain a pointer to the `COWDeleterContext`. Also, the `COWDeleterContext` will need to be deleted at some point to avoid a memory leak. Currently, for the example above, thread A decrements the refcount, which reaches 0, and the `COWDeleterContext` then gets deleted.

During this time, thread A needs to somehow coordinate with the other threads to make them wait until it is finished materializing the `StorageImpl`. Right now, this isn't being done properly, so other threads start trying to materialize the storage as well, and that's the race condition we're seeing.

I was considering using the mutex in the `COWDeleterContext` for this coordination, but I realized that since thread A will delete the `COWDeleterContext`, the mutex would also get deleted while other threads may be waiting to acquire a lock on it. Not good.

I was also considering having each thread increment the refcount of the `COWDeleterContext` before waiting on the mutex. I thought that would prevent the mutex from getting deleted while the other threads are waiting on it, since the refcount seems like it wouldn't ever reach 0. However, there would actually still be another race condition here. Let's say thread A gets to the point where it decrements the refcount to 0 before any other threads catch up, but then right after that, thread B increments the refcount again and starts waiting on the mutex. In that case, thread A will continue to delete the `COWDeleterContext`, since it saw the refcount reach 0, and thread B is still left waiting for a deleted mutex. And it's also possible that thread B could increment the refcount right after thread A finishes deleting the `COWDeleterContext`, while the refcount is held in invalid memory. Still no good.

I thought of one solution that works, but it doesn't seem ideal. The idea is to add a mutex to the `materialize_cow_storage` function, so that only one of the threads can materialize a storage at a time. But that also prevents two threads from materializing two different storages at the same time. I'm not sure how often this happens, but performance would decrease for those cases.

Another option would be to provide a different mutex for each `StorageImpl` which will remain alive after the `COWDeleterContext` is deleted. That way, the other threads won't be left waiting on a deleted mutex. But where would this mutex live? I guess the most obvious option is to add the mutex to the `StorageImpl`. But I'm not sure if we'd want to increase the size of `StorageImpl`.

Another option is maybe to create a global container of mutexes. Each mutex would be paired with a reference to the `StorageImpl` that is supposed to be used for. But that seems like a very weird solution, and I'm not sure at what point we could decide that one of the mutexes is no longer needed and remove it from the container.

What do you think @ezyang ?

**Comment by ezyang** [comment]
My proposal will require some upfront work, but I think it is the simplest: let's ban multithreaded access to the mutable data pointer. The reasoning here is that in C++ it's typical that an object is not safe to access mutably concurrently from multiple threads, unless the object has been explicitly synchronized. at::Tensor traditionally falls in this bucket.

Now, in this particular case, we have code accessing data pointer in parallel from multiple threads from parallel_for. But this is easy to fix: we should access the mutable pointer once from outside of parallel for, and close over the resulting pointer (with the side condition that writes must be non-aliasing; we can't test for this in the compiler.)

This means we have to audit all existing parallel_for calls and ban data_ptr calls from inside them. Not sure if there's a way to enforce this dynamically cheaply, but that would help too.

**Comment by kurtamohler** [comment]
@ezyang, that might be the best idea. However, it seems like it's not actually good enough to only ban direct `mutable_data_ptr` calls.

I've been looking through the places where `parallel_for` is called in the codebase and there are at least a few examples where the loop function doesn't call `mutable_data_ptr` directly, but it does call an aten operation on a `Tensor` that is shared across all the threads. If that aten function materializes COW inputs, whether because it hasn't been updated to use `const_data_ptr` or because it actually needs to mutate the input, then it will materialize the tensor. 

So more specifically, we would need to ban _anything_ that causes a `materialize_cow_storage` call inside `parallel_for`. If anything in the loop function would cause a materialization, then the client needs to explicitly materialize the data before the `parallel_for` call.

Without a way to automatically detect this, I think it will be very difficult to enforce. It's not obvious to me how we would detect it. So I think it's worth asking, if we can't think of a good way to detect that something inside a `parallel_for` loop function is causing a materialization, then would we still be willing to try to enforce this policy?

**Comment by kurtamohler** [comment]
> before creating the other threads, we could set some shared variable `bool is_in_parallel_for` to true. Then after the threads are joined up again, set it back to false. In `materialize_cow_storage`, we can just assert that it's false.

I tried this and it seems to work. Is this alright with you?

**Comment by ezyang** [comment]
> I've been looking through the places where parallel_for is called in the codebase and there are at least a few examples where the loop function doesn't call mutable_data_ptr directly, but it does call an aten operation on a Tensor that is shared across all the threads. If that aten function materializes COW inputs, whether because it hasn't been updated to use const_data_ptr or because it actually needs to mutate the input, then it will materialize the tensor.

In the limit, this doesn't seem like a big deal, as materialization would only happen if you called a mutable tensor op.

> before creating the other threads, we could set some shared variable bool is_in_parallel_for to true. Then after the threads are joined up again, set it back to false. In materialize_cow_storage, we can just assert that it's false.

Help me understand: is this a global variable or thread local? It seems to me that we should be able to run multiple parallel for at once!

**Comment by ezyang** [comment]
In C++, it is pretty easy to imagine having multiple threads, calling operators which each also run parallel for.

**Comment by kurtamohler** [comment]
Got it. Then detecting materialization inside parallel_for the way I proposed would have to use a thread-local variable.

Of course, this won't protect against materializing a tensor that is shared between threads that were created by any means other than `parallel_for`. Broader protection like that would be ideal.

What if we added another field to `COWDeleterContext` to track the ID of the thread that created it, and only allow that thread to materialize it?

**Comment by ezyang** [comment]
Yes, so I think something like, "am I in parallel for" is thread local, you toggle it true on the main thread when you enter parallel_for, worker threads perpetually have it true.

**Comment by izaitsevfb** [comment]
Hey @kurtamohler, it looks like XLA job failure is actually caused by your PR.

See [hud](https://hud.pytorch.org/hud/pytorch/pytorch/main/1?per_page=200&name_filter=8-clang9-xla%20%2F%20test%20).

To verify, I retried the job on the previous commit in trunk and it succeeded:
https://github.com/pytorch/pytorch/actions/runs/8073145934/job/22095434317

I'll revert your stack to keep trunk green, unless you have any objections. Thank you.

**Comment by kurtamohler** [comment]
Thanks for the heads up @izaitsevfb , sure, you can revert these two PRs. There are several other failures elsewhere that I need to fix as well

**Pull request closed without merging**
