### PR TITLE
Bump version 2.1.0 -> 2.2.0

### PR DESCRIPTION
**Pull request by atalman**
Same as: https://github.com/pytorch/pytorch/pull/95790

### <samp>🤖 Generated by Copilot at 50063bb</samp>

> _`PyTorch` version up_
> _Nightly and release builds change_
> _Autumn of progress_

### CODE REVIEW

**Review by osalpekar — APPROVED** [review]

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by ydshieh** [comment]
Hi, when will torch 2.1.0 be released? On `transformers` side, we need to fix some failing tests 🙏 .

**Comment by albanD** [comment]
Hey!
You have all the info in the release annoucement channel of the dev forum: https://dev-discuss.pytorch.org/c/release-announcements/27
Anything specific you will need help with / are there issues for it?

**Comment by ydshieh** [comment]
Thank you @albanD I get the release date from slack channel :-)

There are some failing tests on our side and I am trying to fix them. If there is anything specific to torch,  I will report.

**Pull request closed without merging**
