### PR TITLE
Fixed issue with linalg_svdvals for forwardAD mode and inplace ops

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:
- Fixed issue with linalg_svdvals for forwardAD mode and inplace ops
- This should fix a number of failing tests in functorch

cc @Lezcano

### CODE REVIEW

**Review by lezcano — APPROVED** [review]

**Review by albanD — APPROVED** [review]
Looks good.
Is there any test we should add?

**Comment by Lezcano** [comment]
@albanD no. The fact that this works should be reflected when https://github.com/pytorch/functorch/pull/432/files is rebased on top of this one, as a number of those `xfail`s should go.

**Comment by zou3519** [comment]
Just confirming, we are abandoning this in favor of https://github.com/pytorch/pytorch/pull/72181/files ?

**Comment by Lezcano** [comment]
Yes. The linked PR is a superset of this one.

**Pull request closed without merging**
