### PR TITLE
vision_maskrcnn is now deterministic

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #101477
* __->__ #101116

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ezyang** [comment]
not deterministic 💢

**Comment by ezyang** [comment]
Fixed via https://github.com/pytorch/vision/pull/7587

**Pull request closed without merging**
