### PR TITLE
Support RowWiseSparseAdam on GPU

### PR DESCRIPTION
**Pull request by yanxiexy**
Summary: Implement RowWiseSparseAdam on CUDA

Test Plan:
buck test mode/dev-nosan caffe2/caffe2/python/operator_test:adam_test

Summary (total time 39.34s):
  PASS: 7
  FAIL: 0
  SKIP: 0
  FATAL: 0
  TIMEOUT: 0
  OMIT: 0

Differential Revision: D20289209

### CODE REVIEW

**Comment by ezyang** [comment]
This broke the ROCm builds, I'm reverting.

**Comment by iotamudelta** [comment]
I just looked over it. Missing device code (different missing device code for the tests) would indicate to me that something goes wrong when lowering (best guess). Difficult to say what exactly is going on there on the quick.

@ezyang I have no objections to disabling this code for ROCm. I will retest with ROCm 3.1.1 once on CI.

**Comment by yanxiexy** [comment]
@iotamudelta @ezyang thank you both for your help. How can I disable my code for ROCm? Thanks.

**Comment by iotamudelta** [comment]
@yanxiexy on the C++ layer `#ifndef __HIP_PLATFORM_HCC__` should do the trick. Sorry for late reply.

**Pull request closed without merging**
