### PR TITLE
Add `__init__.py` to `test/quantization` folder

### PR DESCRIPTION
**Pull request by malfet**
This makes it a proper python package, therefor `ModuleFinder` will parse dependencies from this module, and as results, changes to `torch/testing/_internal/common_quantization` or `test/quantization/*.py` would be considered affecting `test_quantization.py`.

### CODE REVIEW

**Comment by yns88** [comment]
Can you add a unit test that demonstrates this? I thought I had got this covered with my unit test on the test_jit_* files, but seems like there's more edge cases: https://github.com/pytorch/pytorch/blob/master/test/test_determination.py#L61

**Comment by malfet** [comment]
I don't think this is the correct fix, since it doesnt explain why module finder does not load modules, but as you can see from  https://app.circleci.com/pipelines/github/pytorch/pytorch/164846/workflows/b934b6b6-04b3-49e5-9161-6ec01710b060/jobs/5360614/steps 
`test_quantization` is skipped  for PR that modifies  `torch/testing/_internal/common_quantization.py` and `test/quantization/test_quantize.py`

**Comment by malfet** [comment]
@vkuzo this should explain why both our PRs yielded green but then failed when merged into master.

**Review by ezyang — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Comment by supriyar** [comment]
@malfet I took a look at macos_test and it still seems to be skipping test_quantization
`May 06 10:33:02 Determination is skipping test_quantization`

**Comment by malfet** [comment]
@supriyar in this PR it totally should do that, since it does not change anything.

**Pull request closed without merging**
