### PR TITLE
Decompose expand_copy and permute_copy

### PR DESCRIPTION
**Pull request by rec**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #130036
* __->__ #129476

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @tianyu-l

### CODE REVIEW

**Comment by rec** [comment]
I removed the lowering for `permute_copy` which was not needed.

**Review by amjames — APPROVED** [review]

**Review by lezcano — APPROVED** [review]
SG, but CI failures are real.

**Comment by rec** [comment]
> SG, but CI failures are real.

I'll make sure it's all green, or otherwise prove that the failures are false.

**Pull request closed without merging**
