### PR TITLE
Handle size/etc accessors in FakeTensor, support accessing symbolic types from toInt/etc in IValue

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #124762
* __->__ #124760

Fixes https://github.com/pytorch/pytorch/issues/122772

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Comment by ezyang** [comment]
Do not need tests for this, with this and one more fix, the proxy tensor tests start passing on topk et al

**Review by albanD — APPROVED** [review]
Sounds fair but CI is not happy here haha

**Review by eellison — APPROVED** [review]

**Comment by ezyang** [comment]
It's all unexpected successes! I might just squash this PR with the next one.

**Pull request closed without merging**
