### PR TITLE
[Profiler] exclude gpu_user_annotation when accumulating cuda time total

### PR DESCRIPTION
**Pull request by fwenguang**
Fixes #[130730](https://github.com/pytorch/pytorch/issues/130730)

### CODE REVIEW

**Review by aaronenyeshi — APPROVED** [review]
LGTM

**Comment by aaronenyeshi** [comment]
Is it possible to add a small unit test for this?

**Comment by fwenguang** [comment]
> Is it possible to add a small unit test for this?

Okay.

**Review by aaronenyeshi — APPROVED** [review]

**Review by aaronenyeshi — APPROVED** [review]
Approved CI runs.

**Pull request closed without merging**
