### PR TITLE
[MPS] Enable caching for random ops with Philox engine

### LINKED ISSUE #85611: [MPS] `torch.bernoulli` always returns zeros on MacOS Ventura
### 🐛 Describe the bug

% python -c "import os; import torch;x=torch.ones(10, 10, device='mps');y=torch.bernoulli(x);print(torch.__version__, os.uname().version, y)"
1.12.1 Darwin Kernel Version 22.1.0: Mon Aug 29 20:09:44 PDT 2022; root:xnu-8792.40.74.0.1~20/RELEASE_ARM64_T8103 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], device='mps:0')

The same on MacOS Monterey:
```
% python -c "import os; import torch;x=torch.ones(10, 10, device='mps');y=torch.bernoulli(x);print(torch.__version__, os.uname().version, y)"
/opt/homebrew/Caskroom/miniconda/base/envs/nshulga-test1.12.1/lib/python3.10/site-packages/torch/_tensor_str.py:103: UserWarning: The operator 'aten::bitwise_and.Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
1.12.1 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], device='mps:0')
```

### Versions

1.12.1, nightly

cc @ezyang @gchanan @zou3519 @kulinseth @albanD

### PR DESCRIPTION
**Pull request by razarmehr**
Also Fix type cast issue in Bernoulli (Fixes #85611)

### CODE REVIEW

**Review by kulinseth — APPROVED** [review]
Looks fine.

**Comment by kulinseth** [comment]
@malfet , can you please help merge this.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
