### PR TITLE
Decomposition type promotion switch to prims.convert_element_type

### PR DESCRIPTION
**Pull request by jjsjann123**
Decomposition does type promotion using `aten.to` which is traced as `_to_copy`. Switching to use `prims.convert_element_type` makes later lowering to prim much easier. Especially during speculative lowering to nvprim, where `_to_copy` blocks the fusion.

### CODE REVIEW

**Comment by jjsjann123** [comment]
cc'ing @IvanYashchuk @kevinstephano

**Comment by Chillee** [comment]
@jjsjann123 You might also to do a quick find and replace for the other decompositions that use `.to`.

For example, I think you might be running into `native_batch_norm_backward` and such: https://github.com/pytorch/pytorch/blob/master/torch/_decomp/decompositions.py#L1204

**Comment by jjsjann123** [comment]
> @jjsjann123 You might also to do a quick find and replace for the other decompositions that use `.to`.
> 
> For example, I think you might be running into `native_batch_norm_backward` and such: https://github.com/pytorch/pytorch/blob/master/torch/_decomp/decompositions.py#L1204

Ha, good catch~~

**Comment by Chillee** [comment]
It's failing the partitioner check? https://github.com/pytorch/pytorch/blob/master/functorch/functorch/_src/partitioners.py#L278 I think you just need to add `prims.convert_element_type` to that list.

**Comment by ezyang** [comment]
dumb Q, how come to doesn't decompose to prims.convert_element_type

**Review by ezyang — APPROVED** [review]

**Comment by Chillee** [comment]
@ezyang it's compositeimplicitautograd, and decomposes to `_to_copy`, which we don't have any kind of decomposition for.

**Comment by jjsjann123** [comment]
hmmm. vmap failure looks real. I'll take another look sometime tomorrow~ :crossed_fingers: 
https://github.com/pytorch/pytorch/runs/7914647385?check_suite_focus=true

**Comment by IvanYashchuk** [comment]
There's no batch rule for vmap to work with `prims::convert_element_type` or any other `prims`.

**Comment by Chillee** [comment]
Ah, this is why I probably didn't use it to begin with.

Registering a batching rule for `prims.convert_element_type` should be hopefully simple (assuming I can register batching rules for prims at all).

Lemme see if I can make a patch for it.

**Comment by jjsjann123** [comment]
closing in favor of #83782 & #83770

**Pull request closed without merging**
