### PR TITLE
[Model Averaging] Support disabling post-local gradient sync

### PR DESCRIPTION
**Pull request by wayi1**
I find that sometimes disabling intra-subgroup gradient allreduce can still give a satisfying accuracy for some cases, so better to make such gradient averaging configurable. This does not take into account the saving in the communication of allreducing gradients.

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Sounds good, but this is no longer local SGD then? Curious why disabling intra-node allreduce can help.

**Comment by wayi1** [comment]
> Sounds good, but this is no longer local SGD then? Curious why disabling intra-node allreduce can help.

This allows disabling gradient averaging, but still keep parameter/model averaging, which is what local SGD really does.

**Review by rohan-varma — COMMENTED** [review]
Looks like a test is failing, can you take a look? test_ddp_hook_parity_post_localSGD: https://github.com/pytorch/pytorch/runs/6285865880?check_suite_focus=true

**Comment by wayi1** [comment]
> Looks like a test is failing, can you take a look? test_ddp_hook_parity_post_localSGD: https://github.com/pytorch/pytorch/runs/6285865880?check_suite_focus=true

Should be fixed now.

**Review by rohan-varma — APPROVED** [review]
LGTM, thank you!

**Pull request closed without merging**
