### PR TITLE
[dynamo (easy)] Add skip reason to debug logs

### LINKED ISSUE #112867: [dynamo] skipping reason is ambiguous in logs
### 🚀 The feature, motivation and pitch

Should report which of the following is the reason for skipping

```python
frame.f_lasti >= first_real_inst_idx(frame.f_code)
or skipfiles.check(frame.f_code)
or config.disable
```

### Alternatives

Hard to diagnose skipping reason, making it hard to debug things like:
https://github.com/pytorch/pytorch/pull/112233 
https://github.com/pytorch/pytorch/issues/112865

### Additional context

NIL

### PR DESCRIPTION
**Pull request by jon-chuang**
Fixes https://github.com/pytorch/pytorch/issues/112867

Example logs
```
[2023-11-03 12:51:02,230] torch._dynamo.eval_frame: [DEBUG] skipping: helper (reason: in skipfiles, file: /usr/lib/python3.10/contextlib.py)
[2023-11-03 12:51:02,230] torch._dynamo.eval_frame: [DEBUG] skipping: __init__ (reason: in skipfiles, file: /usr/lib/python3.10/contextlib.py)
[2023-11-03 12:51:02,230] torch._dynamo.eval_frame: [DEBUG] skipping: __enter__ (reason: in skipfiles, file: /usr/lib/python3.10/contextlib.py)
[2023-11-03 12:51:02,230] torch._dynamo.eval_frame: [DEBUG] skipping: backend_cache_wrapper (reason: in skipfiles, file: /home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/eval_frame.py)
[2023-11-03 12:51:02,230] torch._dynamo.eval_frame: [DEBUG] skipping: _maybe_init_guarded_backend_cache (reason: in skipfiles, file: /home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/eval_frame.py)
[2023-11-03 12:51:02,230] torch._dynamo.eval_frame: [DEBUG] skipping: innermost_fn (reason: in skipfiles, file: /home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/eval_frame.py)
[2023-11-03 12:51:02,230] torch._dynamo.eval_frame: [DEBUG] skipping: _set_current_backend (reason: in skipfiles, file: /home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/eval_frame.py)
[2023-11-03 12:51:02,230] torch._dynamo.eval_frame: [DEBUG] skipping: __init__ (reason: in skipfiles, file: /usr/lib/python3.10/contextlib.py)
[2023-11-03 12:51:02,230] torch._dynamo.eval_frame: [DEBUG] skipping: __enter__ (reason: in skipfiles, file: /usr/lib/python3.10/contextlib.py)
[2023-11-03 12:51:02,230] torch._dynamo.eval_frame: [DEBUG] skipping: enable_dynamic (reason: in skipfiles, file: /home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/eval_frame.py)
[2023-11-03 12:51:02,247] [0/0] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing fn /home/jonch/Desktop/sdpa.py:1635
[2023-11-03 12:51:02,248] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line /home/jonch/Desktop/sdpa.py:1635 in fn (fn)
[2023-11-03 12:51:02,248] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG]     def fn(x):
[2023-11-03 12:51:02,313] [0/0] torch._dynamo.output_graph: [DEBUG] create_graph_input L_x_ L['x']
[2023-11-03 12:51:02,314] [0/0] torch._dynamo.variables.builder: [DEBUG] wrap_to_fake L['x'] (3,) [<DimDynamic.STATIC: 2>] [None]
[2023-11-03 12:51:02,314] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line /home/jonch/Desktop/sdpa.py:1636 in fn (fn)
[2023-11-03 12:51:02,314] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG]         x = x + 1
[2023-11-03 12:51:02,314] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST x []

```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by jon-chuang** [comment]
Hmm, are docs builds on main broken?

**Comment by jon-chuang** [comment]
@ezyang looks like the CI machine on which this PR is scheduled somehow keeps failing with the same error (artifacts.zip not present). How can I force schedule a different CI machine? I've merged main multiple times to no avail.

**Pull request closed without merging**
