### PR TITLE
Use forked torchbench branch with pinned numpy

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128856

Adds pinned numpy commit to yolov3 dependencies to the existing pinned commit.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM as a temporary mitigation to restore trunk sanity.  This is actual not the first time an unpinned dependency from torchbench wrecks havoc on PT CI.  A few days ago was https://github.com/pytorch/pytorch/pull/128718 and the new https://pypi.org/project/pyarrow/16.1.0/#history package

**Review by PaliC — APPROVED** [review]

**Comment by seemethere** [comment]
Can we just merge https://github.com/pytorch/benchmark/pull/2307 instead and update the pinned commit?

**Comment by eellison** [comment]
@seemethere updating torchbench pinned commit can cause breakages and take a while to merge

**Comment by eellison** [comment]
Looks like it is still failing :( 

See error here : https://github.com/pytorch/pytorch/actions/runs/9552331220/job/26330400478

**Pull request closed without merging**
