### PR TITLE
Retry download and install NDK when testing Android

### PR DESCRIPTION
**Pull request by huydhn**
As this step uses network to download and install NDK, it could fail flakily, i.e. https://github.com/pytorch/pytorch/actions/runs/4452757793/jobs/7820701670.  So I'm adding retrying to the workflow.  

I could try figure out a way to Dockerize this, but not sure yet how to handle the GitHub action `reactivecircus/android-emulator-runner@v2` in Docker.  So let's opt for the easy fix of retrying.

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Need to rework this a bit as sdkmanager does not correctly treat a failed download as failure (surprise) https://github.com/pytorch/pytorch/actions/runs/4495666042/jobs/7909537961' -c weird

Looking at the error, I could check for the existence of `${ANDROID_SDK_ROOT}/ndk-bundle/build/cmake/android.toolchain.cmake` instead, as the file will only be there is the NDK archive is downloaded and extracted correctly

```
Could not find toolchain file:
/usr/local/lib/android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake
```

**Pull request closed without merging**
