### PR TITLE
[JIT] make RegisterCudaFuseGraph use TORCH_API instead of C10_EXPORT

### LINKED ISSUE #73620: [JIT] NVFuser tests that fail on windows
### 🐛 Describe the bug

Some tests are failing/erroring. See https://gist.github.com/davidberard98/9941a73de26347f531e17d4167656ba6 for the full errors.

Other tests are timing out. For example, previously windows CI tests would get stuck on `test_autocast_1` for about 2-3 hours before the job was killed due to timing out. For the other tests labeled as "timing out" below, the criteria was running for >10x the typical runtime on a linux machine.

Fail/Error: 
* test_alias_pass_fix
* test_backward_type
* test_batch_norm_half
* test_batch_norm_impl_index_correctness
* test_binary_ops_permutation
* test_broadcasting_2
* test_broadcasting_partition_logic_0
* test_broadcasting_partition_logic_1
* test_build_shape_expression_native_dropout
* test_category_rule
* test_channels_last_with_broadcast
* test_conv2d_bias
* test_dropout_inference_fusion
* test_dropout_train_nograd_fusion
* test_dropout_train_nograd_prob_check
* test_dropout_training_prob_check
* test_graph_rng
* test_inplace_removal
* test_linear
* test_linear_1d_weight_mismatch_bias_dtype
* test_native_layer_norm
* test_native_layer_norm_half
* test_norm
* test_norm_channels_last
* test_norm_half
* test_norm_large
* test_profile_ivalue
* test_profiling_node
* test_reduction_sizes_op
* test_sibling_fusion
* test_softmax
* test_sum_to_size
* test_view

Timeout:
* test_autocast_...
* test_dropout_training_fusion
* test_gelu
* test_grad_sum_to_size
* test_layer_norm_autodiff
* test_softmax_dtype
* test_softplus_fuser
* test_unary_ops

### Versions

Windows CI build

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #73322
* __->__ #73742

I think this was causing multiple implementations of
RegisterCudaFuseGraph on windows. It looks like both torch_cpu.dll and
torch_python.dll were exporting RegisterCudaFuseGraph implementations,
so RegisterCudaFuseGraph::isRegistered() would refer to a _different_
static bool depending on whether the caller was in torch_cpu.dll or
torch_python.dll. See #73717 for a demonstration.

Differential Revision: [D34618623](https://our.internmc.facebook.com/intern/diff/D34618623)

### CODE REVIEW

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34618623).

**Review by eellison — APPROVED** [review]
Should we just grep replace `C10_EXPORT` with `TORCH_API` everywhere in torch/csrc/jit ?

**Comment by jjsjann123** [comment]
> Should we just grep replace `C10_EXPORT` with `TORCH_API` everywhere in torch/csrc/jit ?

Similar question, we are also using `C10_EXPORT` on a few different places within nvfuser codebase. I guess those should be fine since they are not exposed in python API. But would TORCH_API be a safer bet in general?

**Review by jjsjann123 — APPROVED** [review]
Thanks for the fix!

**Comment by davidberard98** [comment]
@eellison @jjsjann123 I think some of them belong to `TORCH_CUDA_CPP_API` (or possibly `TORCH_CUDA_CU_API` ?). I'll go through and change some of the other instances in torch/csrc/jit/

**Pull request closed without merging**
