### PR TITLE
Port /test/cpp_extensions/rng_extension.cpp to new operator registration API

### LINKED ISSUE #37010: Make it an error to def() an operator multiple times
Currently in `aten/src/ATen/core/library.cpp` there is a todo:

```
// TODO: Error if an operator is def'ed multiple times.  Right now we just
// merge everything
```

The relevant backwards compatibility logic is in `aten/src/ATen/core/dispatch/Dispatcher.cpp`:

```
void Dispatcher::checkSchemaCompatibility(const OperatorHandle& op, const FunctionSchema& schema, const std::string& debug) {
  TORCH_CHECK(op.schema() == schema, "Tried to register multiple operators with the same name and the same overload name but different schemas: ", schema, " (", debug, ") vs ", op.schema(), " (", op.debug(), ")");
  if (schema.isDefaultAliasAnalysisKind()) {
    // [BACKWARDS COMPAT] If the *new* schema is the default alias analysis
    // kind, for BC, we will accept it.  If we don't accept it, most extensions
    // that override existing operators will stop working (as they generally did
    // not specify alias information).
  } else if (op.schema().isDefaultAliasAnalysisKind()) {
    // [BACKWARDS COMPAT] If you POST-FACTO specify a non-default alias analysis
    // kind after we already have a schema for a function, bong it in for BC
    // reasons.
    op.operatorIterator_->op.updateSchemaAliasAnalysis(schema.aliasAnalysis());
  } else {
    TORCH_CHECK(op.schema().aliasAnalysis() == schema.aliasAnalysis(),
      "Tried to define the schema for ", toString(op.operator_name()), " with different alias analysis kinds: ",
      toString(op.schema().aliasAnalysis()), " (", op.debug(), ") vs ", toString(schema.aliasAnalysis()), " (", debug, ")");
  }
}
```

The desired new form of this code is to make it to make it 100% invalid to def an operator multiple times.  This can be done by replacing the if-statement in this function with an unconditional error (and update the error message).

Once this is done, there may be some definition sites which now error. You should identify all of these sites and port them to the new API (similar to what was done in #36925), so that there is a single, unique `def()` for it (every old-style `RegisterOperators` call counts as a def, which is why porting will generally help solve the problem). Some of these sites may occur in the mobile-only code, please confer with your bootcamp mentor for more information about how to deal with these if they arise.

This task is reserved for bootcamp, please confer with @ezyang before working on it.

### PR DESCRIPTION
**Pull request by changjishi**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#39459 Port /test/cpp_extensions/rng_extension.cpp to new operator registration API**

Summary: 
Update to this PR: this code isn't going to fully solve https://github.com/pytorch/pytorch/issues/37010. The changes required for 37010 is more than this PR initially planned. Instead, this PR switches op registration of rng related tests to use the new API (similar to what was done in #36925)

Test Plan: 
1) unit tests 

Reviewers:

Subscribers:

Tasks: https://github.com/pytorch/pytorch/issues/37010

Tags:

Differential Revision: [D22264889](https://our.internmc.facebook.com/intern/diff/D22264889)

### CODE REVIEW

**Comment by ezyang** [comment]
I see relevant failures in CI? :)

**Comment by ezyang** [comment]
You've accidentally updated submodules in the diff; take a look at https://stackoverflow.com/questions/7718780/how-to-undo-git-submodule-update for how to fix it

**Comment by changjishi** [comment]
> You've accidentally updated submodules in the diff; take a look at https://stackoverflow.com/questions/7718780/how-to-undo-git-submodule-update for how to fix it

Right, resolved.

**Comment by ezyang** [comment]
The binary files are committed by accident and need to be removed

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
