### PR TITLE
[jit] Remove unnecessary clone APIs for script::Module and RecursiveS…

### PR DESCRIPTION
**Pull request by jerryzh168**
…criptModule (#40297)

Summary: Pull Request resolved: https://github.com/pytorch/pytorch/pull/40297

Test Plan: Imported from OSS

Differential Revision: D22191660

fbshipit-source-id: 4b338ca82caaca04784bffe01fdae3d180c192f4

### CODE REVIEW

**Comment by seemethere** [comment]
@jerryzh168 Can you re-run CI on this, doesn't appear as though I'm able to kick taht for you

**Comment by jerryzh168** [comment]
most of my cherry-pick PRs failed in CI for similar reasons, is there any permission requirement etc.?

**Comment by jerryzh168** [comment]
error: Error response from daemon: Get https://308535385114.dkr.ecr.us-east-1.amazonaws.com/v2/pytorch/pytorch-linux-bionic-py3.8-gcc9/manifests/209062ef-ab58-422a-b295-36c4eed6e906: no basic auth credentials

**Comment by jerryzh168** [comment]
recreating in pytorch repo directly

**Pull request closed without merging**
