### PR TITLE
[AOTI][refactor] Move a few util functions in atoi_torch

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #120714
* #120513
* #120629
* #120592
* __->__ #119987

Summary: Move these util functions from an anonymous namespace to a common header so that later torchgen-ed files can use them.

Differential Revision: [D54258088](https://our.internmc.facebook.com/intern/diff/D54258088)

### CODE REVIEW

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54258088).

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54258088).

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54258088).

**Review by chenyang78 — APPROVED** [review]
LGTM. Thanks!

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54258088).

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54258088).

**Pull request closed without merging**
