### PR TITLE
Better graph break msg (and warning) on Dynamo x Python C++ extension

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #127117
* __->__ #127301
* #127423
* #127400
* #127292
* #127291

Dynamo graph breaks on Python C/C++ extensions (e.g. pybinded
functions). The usual way to handle this is to turn those extensions
into custom ops. This PR adds a nicer graph break message and also
changes it to unconditionally warn on this graph break (because graph
break messages are usually not visible).

Fixes https://github.com/pytorch/pytorch/issues/126799

Test Plan:
- new test

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by bhack** [comment]
This is nice but honestly I think it is a bit spamming. 
Just compiling a function using https://github.com/ClementPinard/Pytorch-Correlation-extension  cause we never implemented it in pytorch (see https://github.com/pytorch/pytorch/issues/4073) we have a lot of 
```python
/opt/conda/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py:661: UserWarning: Graph break due to unsupported builtin spatial_correlation_sampler_backend.PyCapsule.forward. This function is either a Python builtin (e.g. _warnings.warn) or a third-party C/C++ Python extension (perhaps created with pybind). If it is a Python builtin, please file an issue on GitHub so the PyTorch team can add support for it and see the next case for a workaround. If it is a third-party C/C++ Python extension, please either wrap it into a PyTorch-understood custom operator (see https://pytorch.org/docs/main/notes/custom_operators.html for more details) or, if it is traceable, use torch.compiler.allow_in_graph.
  warnings.warn(msg)
```

**Comment by zou3519** [comment]
@bhack python should suppress warnings if they come from the same source. Is that not the case?

**Comment by bhack** [comment]
It is a third party extension https://github.com/ClementPinard/Pytorch-Correlation-extension

I have 20/30 of these message every recompilation now. Other then suppressing  what is the action item (as I suppose we are suggesting an action item if we emit a new warning)?

**Comment by zou3519** [comment]
@bhack the action item is to wrap the pybind call into a custom operator (see https://pytorch.org/docs/main/notes/custom_operators.html). Could the warning message be clearer?

**Comment by bhack** [comment]
It is a bit ambiguous about the traceable case.

>  If it is a Python builtin, please file an issue on GitHub so the PyTorch team can add support for it and see the next case for a workaround. If it is a third-party C/C++ Python extension, please either wrap it into a PyTorch-understood custom operator (see https://pytorch.org/docs/main/notes/custom_operators.html for more details) or, if it is traceable, use torch.compiler.allow_in_graph.

**Pull request closed without merging**
