### PR TITLE
Add Naive Bayes text classification functionality

### PR DESCRIPTION
**Pull request by Nandana-Chigaterappa-HemanthKumar**
This pull request adds a Naive Bayes classifier for binary text classification using the IMDB movie review dataset.
- Implements text preprocessing using TorchText.
- Uses Bag-of-Words (BoW) for feature extraction.
- Includes unit tests for the model.

### CODE REVIEW

**Comment by Nandana-Chigaterappa-HemanthKumar** [comment]
> Didn't find following labels among repository labels: release notes:

@pytorchbot label "release notes: <appropriate description>"

**Comment by soulitzer** [comment]
Thanks for the contribution, but we do not accept these types of PRs. PyTorch is intended to provide lower-level components only. Perhaps submitting a tutorial for how to use torch text would be a better way to showcase this type of higher-level usage.

**Pull request closed without merging**
