### PR TITLE
Add PairwiseDistance.

### PR DESCRIPTION
**Pull request by lebedov**
Although the unit tests pass, I'm not sure if I constructed them properly - feel free to comment. If the PR looks fine, I can update the docs as well.

### CODE REVIEW

**Comment by soumith** [comment]
hi @lebedov 
while the PR looks fine, we dont see the value of adding `PairwiseDistance` into pytorch, as it is a trivial operation that can be written by the user in one line in their `forward` call.
Hence, we're closing the PR.
A better place would be to add it into your own utilities file.

**Comment by lebedov** [comment]
I got the impression that someone wanted to add it because of the TODO
comment in torch/nn/modules/distance.py.

**Comment by soumith** [comment]
We did make a list of missing modules against torch/nn, but they were placeholders as we developed things.
I'll make a pass on the TODOs and remove those that are not relevant.

I'm really sorry if you worked on the PR because the TODO was there, ping me next time and we can clear it up. :)

**Comment by lebedov** [comment]
I already had written it when porting something from Lua Torch, so no harm done. I dumped it into a [gist](https://gist.github.com/lebedov/85840f17dbfa264a4c16612279c4d0d9) in case anyone else searches for it.

**Pull request closed without merging**
