### PR TITLE
Bug - check config for dynamic

### PR DESCRIPTION
**Pull request by voznesenskym**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #99469
* __->__ #99676
* #99503

cc @soumith @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
You probably want to, you know, test this too, if we're actually going to support this config knob.

**Comment by voznesenskym** [comment]
> You probably want to, you know, test this too, if we're actually going to support this config knob.

It's on my default, all the tests test this codepath already, right? That's why we didn't notice this missing. 

In the PR that introduced it - I forked dynamic_shapes tests into w/ and w/o this knob, but you suggested I not do that, so we skipped it.

**Pull request closed without merging**
