### PR TITLE
Introduce _ArglessActivation base class for parameterless activation functions

### LINKED ISSUE #133683: The doc of `Tanh()` says there are `*args` and `**kwargs` but they don't work
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.nn.Tanh.html) of `Tanh()` says there are `*args` and `**kwargs` as shown below:

> CLASS torch.nn.Tanh(*args, **kwargs)

But they don't work as shown below:

```python
import torch
from torch import nn

my_tensor = torch.tensor([-1., 0., 1.])

tanh = nn.Tanh(3, 5) # Error

tanh = nn.Tanh(num1=3, num2=5) # Error
```

> TypeError: Tanh.__init__() takes 1 positional argument but 3 were given

> TypeError: Tanh.__init__() got an unexpected keyword argument 'num1'

### Suggest a potential alternative/fix

So, `*args` and `**kwargs` should be removed from [the doc](https://pytorch.org/docs/stable/generated/torch.nn.Tanh.html) of `Tanh()` as shown below:

> CLASS torch.nn.Tanh()

cc @svekars @brycebortree @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### LINKED ISSUE #133684: The doc of `Softsign()` says there are `*args` and `**kwargs` but they don't work
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.nn.Softsign.html) of `Softsign()` says there are `*args` and `**kwargs` as shown below:

> CLASS torch.nn.Softsign(*args, **kwargs)

But they don't work as shown below:

```python
import torch
from torch import nn

my_tensor = torch.tensor([-1., 0., 1.])

softsign = nn.Softsign(3, 5) # Error

softsign = nn.Softsign(num1=3, num2=5) # Error
```

> TypeError: Softsign.__init__() takes 1 positional argument but 3 were given

> TypeError: Softsign.__init__() got an unexpected keyword argument 'num1'

### Suggest a potential alternative/fix

So, `*args` and `**kwargs` should be removed from [the doc](https://pytorch.org/docs/stable/generated/torch.nn.Softsign.html) of `Softsign()` as shown below:

> CLASS torch.nn.Softsign()

cc @svekars @brycebortree @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### LINKED ISSUE #133688: The doc of `Sigmoid()` says there are `*args` and `**kwargs` but they don't work
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.nn.Sigmoid.html) of `Sigmoid()` says there are `*args` and `**kwargs` as shown below:

> CLASS torch.nn.Sigmoid(*args, **kwargs)

But they don't work as shown below:

```python
import torch
from torch import nn

my_tensor = torch.tensor([-1., 0., 1.])

sigmoid = nn.Sigmoid(3, 5) # Error

sigmoid= nn.Sigmoid(num1=3, num2=5) # Error
```

> TypeError: Sigmoid.__init__() takes 1 positional argument but 3 were given

> TypeError: Sigmoid.__init__() got an unexpected keyword argument 'num1'

### Suggest a potential alternative/fix

So, `*args` and `**kwargs` should be removed from [the doc](https://pytorch.org/docs/stable/generated/torch.nn.Sigmoid.html) of `Sigmoid()` as shown below:

> CLASS torch.nn.Sigmoid()

cc @svekars @brycebortree @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### PR DESCRIPTION
**Pull request by eugenekoran**
Fixes #133683
Fixes #133684
Fixes #133688

This PR introduces a new base class `_ArglessActivation` and refactors five existing activation functions to inherit from it. This change aims to improve documentation consistency and also API consistency with other activation functions that do have parameters and explicitly call `super().__init__()`

Key changes and considerations:
1. Added new class `_ArglessActivation`:
2. Refactored the following classes to inherit from `_ArglessActivation`:
   - Sigmoid
   - Tanh
   - Softsign
   - Tanhshrink
   - Softmax2d
3. Performance consideration:
   - This change introduces a slight overhead for creating a new stack frame and handling an additional function call on every instance creation
   - The impact is expected to be minimal in most use cases

Docs view before:
Screen Shot 2024-09-18 at 3 00 22 PM

Docs view after:
Screen Shot 2024-09-18 at 3 00 52 PM

### CODE REVIEW

**Comment by eugenekoran** [comment]
All checks passed. Should be ready for review

@albanD @jbschlosser @mikaylagawarecki

**Review by mikaylagawarecki — DISMISSED** [review]
Thanks!

**Pull request closed without merging**
