### PR TITLE
[ROCM] Navi21 Enablement 9: Range and Multinomial Kernels

### PR DESCRIPTION
**Pull request by micmelesse**
This PR is a follow up to the following prs.
https://github.com/pytorch/pytorch/pull/69942
https://github.com/pytorch/pytorch/pull/72682
https://github.com/pytorch/pytorch/pull/72809
https://github.com/pytorch/pytorch/pull/73543
https://github.com/pytorch/pytorch/pull/73545
https://github.com/pytorch/pytorch/pull/73546
https://github.com/pytorch/pytorch/pull/73548
https://github.com/pytorch/pytorch/pull/73549

We are adding support to Navi21 GPUs which have a warpsize of 32. We cannot rely on a constant so we have to dynamically look up the warpsize when launching the kernel on the host side. Inside device functions this is not needed and the compiler can correctly detect the correct warpsize to replace the C10_WARP_SIZE constant.

### CODE REVIEW

**Comment by micmelesse** [comment]
@osalpekar @ngimel @malfet This is the final Navi PR. Everything passes.

**Comment by jithunnair-amd** [comment]
@malfet @ngimel This is the light at the end of the Navi21 enablement tunnel (until more kernels show up that need warpsize fixes :) ). Please review and merge.

**Review by ngimel — APPROVED** [review]

**Review by malfet — APPROVED** [review]
LGTM, but just curious: why `num_threads()` is signed integer?

**Comment by micmelesse** [comment]
> LGTM, but just curious: why `num_threads()` is signed integer?

It was that way in the code before and I wanted to keep my changes minimal.

**Pull request closed without merging**
