### PR TITLE
Use default context on Windows for Intel GPU

### PR DESCRIPTION
**Pull request by guangyey**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #138049

# Motivation
Use default context in Windows to keep consistency with Linux. It makes it easy to interact with external libraries like `dlpack`.

# Additional Context
This PR depends on Intel GPU oneAPI 2025.0.

cc @gujinghui @EikanWang @fengyuan14

### CODE REVIEW

**Comment by guangyey** [comment]
These failures are related to https://github.com/pytorch/pytorch/issues/141466, and we have filed a PR https://github.com/pytorch/pytorch/pull/141470 to fix it.

**Comment by guangyey** [comment]
@gujinghui @EikanWang I was wondering if you could help review this PR?

**Comment by guangyey** [comment]
@gujinghui @EikanWang This PR will impact the PyTorch XPU window build. We have tested locally; no regression UTs occurred. May I know if it is reasonable to land it?

**Review by gujinghui — APPROVED** [review]

**Comment by guangyey** [comment]
"Unrelated failure, there is an issue to track it https://github.com/pytorch/pytorch/issues/141705"
@pytorchbot merge -i

**Pull request closed without merging**
