### PR TITLE
[CUDA Graphs] Fix OOM inside graph capture_begin

### PR DESCRIPTION
**Pull request by fps7806**
release_cached_blocks calls this:
```
void synchronize_and_free_events() {
    TORCH_INTERNAL_ASSERT(captures_underway == 0);
```
Which means we can't call that function when we are capturing a cuda graph:
```
import torch

with torch.cuda.graph(torch.cuda.CUDAGraph()):
    torch.zeros(2 ** 40, device="cuda")
```

results in:
```
RuntimeError: captures_underway == 0INTERNAL ASSERT FAILED at "/tmp/torch/c10/cuda/CUDACachingAllocator.cpp":1224, please report a bug to PyTorch.
```

### CODE REVIEW

**Review by mrshenli — COMMENTED** [review]
Lint error is real:

```
  Error (SPACES) trailing spaces
    This line has trailing spaces; please remove them.

    You can run `lintrunner -a` to apply this patch.

    536  536 |           || (release_available_cached_blocks(params) &&
    537  537 |               alloc_block(params, false))
    538  538 |           // Free all non-split cached blocks and retry alloc.
    538      |-          || (C10_LIKELY(captures_underway == 0) && release_cached_blocks() &&
         539 |+          || (C10_LIKELY(captures_underway == 0) && release_cached_blocks() &&
    540  540 |               alloc_block(params, true));
    541  541 |     }
    542  542 | 
```

**Comment by ngimel** [comment]
Can you please add a test?

**Comment by fps7806** [comment]
@ngimel Happy to add one but I am not super familiar with the code base.
Could you point me to where would be the best place?
My quick test was this:
```
import pytest
import torch

with pytest.raises(RuntimeError, match="CUDA out of memory"):
    with torch.cuda.graph(torch.cuda.CUDAGraph()):
        torch.zeros(2 ** 40, device="cuda")
```

**Comment by ezyang** [comment]
put it in `test_cuda.py`

**Comment by ngimel** [comment]
And typically we use `self.assertRaisesRegex` in our test suite

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
