### PR TITLE
Fix dividing Mul by factor

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136079

Fixes https://github.com/pytorch/pytorch/issues/136032

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Did you figure out how to repro this haha

**Comment by isuruf** [comment]
No, I couldn't figure out a repro. Hopefully this fixes the issue.

**Comment by ezyang** [comment]
testin it

**Comment by ezyang** [comment]
Confirmed works. Actually I wonder if there is a sympy version divergence needed to trigger this in fbcode; we appear to be 1.12, I think??

**Pull request closed without merging**
