### PR TITLE
[MPS] Make addmm support empty matmul

### PR DESCRIPTION
**Pull request by malfet**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #117319
* __->__ #117223

Refactor common part between `mm_out_mps` and `addmm_out_mps` into `do_mm` static function.
Change input placeholder initialization logic in a way that `addmm` can handle matrix multiplication with empty dimension.
Add tests for `mm`+`addmm` with empty tensors to OpInfo but skip addmm with empty matrices from onnx tests

### CODE REVIEW

**Comment by malfet** [comment]
Ok, will move from OpInfo to mps tests...

**Review by albanD — COMMENTED** [review]
Sounds good.
Please preserve these in the OpInfo test and just skip onnx consistency for now there.

**Review by albanD — APPROVED** [review]
SGTM once onnx CI is green!

**Pull request closed without merging**
