### PR TITLE
[caffe2] Don't copy Tensor dims during deserialization

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #79471

We can just make an IntArrayRef.

Differential Revision: [D37124427](https://our.internmc.facebook.com/intern/diff/D37124427/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D37124427/)!

### CODE REVIEW

**Comment by swolchok** [comment]
ping @hlu1 @ezyang

**Comment by ezyang** [comment]
I trust you have, but just to make sure: you've audited all the call sites for `auto x = f(tmp())` right?

**Review by ezyang — APPROVED** [review]

**Comment by swolchok** [comment]
`pull / linux-bionic-py3_7-clang8-xla / test` failure is due to some checksum mismatches on data from the network, will ignore

**Pull request closed without merging**
