### PR TITLE
Updated README.md by correcting grammatical errors

### PR DESCRIPTION
**Pull request by manishram**
Fixed grammatical errors and punctuation so that it can be more understandable.

### CODE REVIEW

**Comment by manishram** [comment]
Hey @malfet, it was my first contribution. Can you please tell me about Codecov Report? Thanks

**Comment by malfet** [comment]
@miraliahmadli please feel free to ignore it: our system correctly detected that your change does not need any test runs as it does not change any code, but codecov is not aware of that. I will work on the change that addresses that.

**Review by brianjo — APPROVED** [review]
Love your addition of the Oxford comma. :)

**Comment by manishram** [comment]
Hey @malfet , please help.

**Comment by malfet** [comment]
@manishram, sorry, but help with what? You change has been merged into the main trunk.

**Comment by manishram** [comment]
Yeah thanks, sorry I wanted help for failed case but then I found every got resolved and changes merged successfully. Thanks

**Comment by miraliahmadli** [comment]
> @miraliahmadli please feel free to ignore it: our system correctly detected that your change does not need any test runs as it does not change any code, but codecov is not aware of that. I will work on the change that addresses that.

Why did you tag me, @malfet ?  :laughing:

**Comment by malfet** [comment]
> Why did you tag me, @malfet ?  :laughing: 

Sorry about that, @miraliahmadli Wrong autocomplete 😄

**Pull request closed without merging**
