### PR TITLE
Use a dtype property in torch inductor nodes

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #119227

I usually forget to do `x.get_dtype()` and I type `x.dtype`. Similarly for `layout, device, sizes`. What do you think about making them properties?

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @lezcano 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by peterbell10** [comment]
Having both mixed through the code doesn't sound ideal and the migration might cause a bit of code churn, but I don't feel too strongly about it.

cc @jansel

**Comment by jansel** [comment]
Why not just throw a:
```
@property
def dtype():
   return self.get_dtype()
```
in the base class?

**Comment by isuruf** [comment]
@jansel, some of the classes have an object attribute called `dtype`. We can do what you suggested in the reverse order, i.e.,

```
def get_dtype(self):
    return self.dtype
```

**Comment by lezcano** [comment]
or rename them as `_dtype` and then have the property? Or just add the property to those that don't have a `.dtype` member?

**Review by lezcano — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
