### PR TITLE
[nvFuser] add torch.jit.fuser context manager

### PR DESCRIPTION
**Pull request by jjsjann123**
1. `torch.jit.fuser(str)` context manager facilitates switch between backend fusers:
  str - 'fuser0' enables only legacy fuser;
  str - 'fuser1' enables only NNC;
  str - 'fuser2' enables only nvFuser;
2. cleanup updated python tests.

### CODE REVIEW

**Review by soumith — CHANGES_REQUESTED** [review]
I don't want to see `torch.jit.nvFuser`.

The public details or names of our different fuser backends shouldn't be exposed to the users.

Either rename `torch.jit.nvFuser` to `torch.jit.fuser('fuser0')` where `fuser0` is the current default, `fuser1` is nvFuser and `fuser2` is NNC. That's one option.

Alternatively, ff you just want this for development / testing purposes, have something like `with torch.jit._fuser('nv')`

**Comment by jjsjann123** [comment]
merge master again hoping the rocm build error will go away.

**Review by soumith — CHANGES_REQUESTED** [review]
one small change. I see you are using `_nv_fuser`, can you make it `_nvfuser`, it is one word

**Comment by jjsjann123** [comment]
rocm failure doesn't look like related to me and it doesn't want to go away after merging master. :cry:

**Review by soumith — APPROVED** [review]

**Comment by ezyang** [comment]
FYI for future reference, the context manager was missing a docblock. Please make sure all added public API has docblocks.

**Pull request closed without merging**
