### PR TITLE
[CI] Update update_expected.py to make it generate a combined csv file

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #98407

Summary: make update_expected.py combine csv files from all shards into a single csv file for each test suite

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

### CODE REVIEW

**Comment by desertfire** [comment]
> Why do we expect round robin to help? It seems like you can still end up with imbalance, PLUS it's now a lot harder to find which shard ran the benchmark.

My thinking is many model with similar names, like * and *_large, will be distributed more evenly in this way. To your comments about harder to find which shard ran which test, I agree with that. I guess a proper way is to keep a record of each test's run time and sharding according to that.

To solve the immediate imbalance problem we are seeing, we can simply skip tacotron2 which hits timeout every time.

I will retarget this PR as an improvement to Will's update_expected.py.

**Review by wconstab — APPROVED** [review]
this looks great, i confirmed check_graph_breaks iterates the models from the 'actual' csv and just looks them up from the expected side, so neither sorting nor set equality should matter and this is easier to manage for sure. Thanks!

**Review by ezyang — APPROVED** [review]
ok. As long as I can find which shard tests are in

**Pull request closed without merging**
