### PR TITLE
Bump Triton version

### PR DESCRIPTION
**Pull request by lw**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #107708

### CODE REVIEW

**Comment by lw** [comment]
We would like this version to be included in PyTorch 2.1 since we fixed an important regression in upstream Triton: https://github.com/openai/triton/issues/1784. Otherwise our users will have to install a nightly version of Triton with PyTorch 2.1. Thanks!

CC @Chillee

**Comment by shunting314** [comment]
@lw  I hope you don't mind that I merge your pin update PR to this one with the necesary inductor side change https://github.com/pytorch/pytorch/pull/107722 . This makes it easier to do perf testing and sync the change to FBCode.

**Comment by lw** [comment]
@shunting314 Thanks for the context and the pointer to the other PR. It seems that PR is blocked on a few upstream Triton issues. I'm worried that these issues might take some time to solve and thus we won't manage to update the Triton pin in time for the branch cut for PyTorch 2.1.

All we need is for this commit to be present: https://github.com/openai/triton/commit/8fa11a75d38fd4eaa57048743de9baf4343fee25. Do you have any ideas on how we could make it happen quickly?

One option I can imagine is that we could create a new branch in upstream Triton, which starts at the current pinned commit, and that cherry-picks the commit we need (and any other critical ones). Then we can update the pin to the tip of that branch. Would this be feasible?

Thanks!

**Comment by shunting314** [comment]
hey @lw  sorry for the late reply, I was on PTO yesterday. 

I thought about another option that we move the pin right at the commit https://github.com/openai/triton/commit/8fa11a75d38fd4eaa57048743de9baf4343fee25 you mentioned . But the commit is after the triton initial hopper commit https://github.com/openai/triton/commit/f1512bded1934e34f104bf1ac8547e97e24b2fe8 which I suspect brings most of the churn. So this may not be a easy upgrade as well.

What you mentioned sounds good to me as long as
- we have enough permission to set up such a branch on triton
- letting PT2.1 release with a non-main triton branch is fine. cc @Chillee / @jansel  / @eellison  in case they see similar situations before or have concern about it.

**Comment by jansel** [comment]
Duplicate of #107722?

**Pull request closed without merging**
