### PR TITLE
allow contiguous inputs run into qcat_nhwc_stub when dim is last dimension

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74999
* __->__ #72575
* #71903

Differential Revision: [D34113898](https://our.internmc.facebook.com/intern/diff/D34113898)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34113898).

**Comment by mingfeima** [comment]
### Updates of this PR

On nhwc layout (dim=1), qcat would go to a fast kernel.
This PR loosen the constraint of using fast path, if the input is contiguous memory format and d is the last dim, use a fast kernel. This is actually identical to nhwc (d=1) case, from the physical memory point of view.

We add this since based on our profiling result on some of our internal KPI models. e.g. CGAN and Wide&Deep has such scenarios: concat inputs of {M, N} and d = 1.

**Comment by frank-wei** [comment]
@frank-wei has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34113898).

**Review by frank-wei — APPROVED** [review]

**Comment by frank-wei** [comment]
The commit will break one test in glow with error msg:
```
  File "/data/users/wwei6/fbsource/fbcode/buck-out/dev/gen/aab7ed39/glow/glow/torch_glow/tests/quantized_cat_test#binary,link-tree/torch/nn/modules/module.py", line 1174, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/data/users/wwei6/fbsource/fbcode/buck-out/dev/gen/aab7ed39/glow/glow/torch_glow/tests/quantized_cat_test#binary,link-tree/glow/torch_glow/nodes/quantized_cat_test.py", line 30, in forward
    torch.ops.quantized.cat(
  File "/data/users/wwei6/fbsource/fbcode/buck-out/dev/gen/aab7ed39/glow/glow/torch_glow/tests/quantized_cat_test#binary,link-tree/torch/_ops.py", line 148, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Tensors must have the same number of dimensions: got 2 and 1
```
Here is the glow test:
https://github.com/pytorch/glow/blob/master/torch_glow/tests/nodes/quantized_cat_test.py with failed one "with_empty_tensor"

**Comment by mingfeima** [comment]
> @jgong5 and @mingfeima , pls help check the broken test. The commit broke one test in glow with error msg:
> 
> ```
>   File "/data/users/wwei6/fbsource/fbcode/buck-out/dev/gen/aab7ed39/glow/glow/torch_glow/tests/quantized_cat_test#binary,link-tree/torch/nn/modules/module.py", line 1174, in _slow_forward
>     result = self.forward(*input, **kwargs)
>   File "/data/users/wwei6/fbsource/fbcode/buck-out/dev/gen/aab7ed39/glow/glow/torch_glow/tests/quantized_cat_test#binary,link-tree/glow/torch_glow/nodes/quantized_cat_test.py", line 30, in forward
>     torch.ops.quantized.cat(
>   File "/data/users/wwei6/fbsource/fbcode/buck-out/dev/gen/aab7ed39/glow/glow/torch_glow/tests/quantized_cat_test#binary,link-tree/torch/_ops.py", line 148, in __call__
>     return self._op(*args, **kwargs or {})
> RuntimeError: Tensors must have the same number of dimensions: got 2 and 1
> ```
> 
> Here is the glow test: https://github.com/pytorch/glow/blob/master/torch_glow/tests/nodes/quantized_cat_test.py with failed one "with_empty_tensor" Check this diff for glow concat for your ref: https://github.com/pytorch/glow/pull/5513/files

Oh thanks for the detailed info! Will have it fixed shortly!

**Pull request closed without merging**
