### PR TITLE
Remove item and data_ptr for std::complex

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Comment by ailzhang** [comment]
Looks like XLA is using these APIs. @zasdfgbnm what should be alternatives here? 
cc: @dlibenzi since this requires a change on pytorch/xla complex code.

**Comment by zasdfgbnm** [comment]
@ailzhang Usually a string replacement of `/std::complex/c10::complex/` will work.

**Comment by zasdfgbnm** [comment]
See https://github.com/pytorch/xla/pull/2204 for xla fix

**Comment by zasdfgbnm** [comment]
@ailzhang XLA is working now

**Comment by ezyang** [comment]
TBH, isn't it harmless to have these specializations for `item` and `data_ptr`? Since the memory layout is the same, I don't see the harm of letting end users access things as a `std::complex` if they really want to.

**Comment by zasdfgbnm** [comment]
@ezyang I don't know. Sometimes I feel that it is a good idea to keep this, especially when the user wants to work with a third-party library that uses `std::complex`. But sometimes, I feel that we should force them to `reinterpret_cast` the pointer to make sure they know what they are doing. There could be a small chance that they run into some subtle error (what if they used some internal function that has SFINAE, or template specialization on `c10::complex` but not `std::complex`?). I don't really have a preference. But if you do feel it's better to keep this functionality, should we also keep the explicit ctor and `.to` on https://github.com/pytorch/pytorch/pull/39831?

**Comment by ezyang** [comment]
Well, I'm generally supportive of removing API surface internally to make it harder to make mistakes (like the one you mentioned here). So I think a first cut would be to be OK with removing `std::complex` from internal APIs, but maybe not external facing APIs. We can also always just remove these first, and then strategically add them back later.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
