### PR TITLE
Memory leak from bsr_scatter_mm_indices_data argument cache

### PR DESCRIPTION
**Pull request by amjames**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #112301

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @bhosmer

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]

**Comment by amjames** [comment]
cc @pearu This demonstrates how the cache is causing the test to look leaky, unsure if this is actually a solution to land. It does resolve the flaky tests though. 

RE: #112158 #112157

**Comment by pearu** [comment]
@amjames https://github.com/pytorch/pytorch/pull/112076 may also resolve the leak issue as in this PR tensors are stored in the cache as weakref-s.

**Comment by amjames** [comment]
Confirmed that the leak check still fires without this after #112076 I also checked that adding 

I'm going to go ahead and take this out of draft.

**Review by pearu — APPROVED** [review]
LGTM!

A likely reason why https://github.com/pytorch/pytorch/pull/112076 did not resolve the issue is that while lru_cache with weakref takes care of garbage collecting tensors in keys then the corresponding values (that contain tensors) are still kept alive until the cache is cleared. A possible solution to this discrepancy would be to implement a LRU cache that uses https://docs.python.org/3/library/weakref.html#weakref.WeakKeyDictionary instead of a Python dict.

**Pull request closed without merging**
