### PR TITLE
Allow using nvFuser on CUDA extension

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Cherry-pick of https://github.com/csarofeen/pytorch/pull/1701

### CODE REVIEW

**Review by jjsjann123 — APPROVED** [review]
Thanks for cherry-picking this~ Stamping but I don't think it means anything on PRs touching top level setup.py

**Comment by zasdfgbnm** [comment]
ping @malfet

**Comment by malfet** [comment]
lgtm, @zasdfgbnm but can you please submit a follow-up that will copy those only if CUDA is enabled (that would probably cover few more folders), as those headers are dead-weight for CPU only packages, aren't they?

**Review by malfet — APPROVED** [review]

**Comment by zasdfgbnm** [comment]
Hmmm, looks like this PR becomes empty after rebase. Probably @jjsjann123 already covered this in one of his PR.

**Comment by zasdfgbnm** [comment]
I will submit a follow-up PR for copying only if built with CUDA.

**Pull request closed without merging**
