### PR TITLE
Remove deprecated HIP flags

### PR DESCRIPTION
**Pull request by jataylo**
Removes the outdated HIP flags appended to HIP_CXX_FLAGS

The will help remove the following warnings in the pytorch build log

```
[6238/6889] Building CXX object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/cudnn/hip/Conv_v8.cpp.o
cc1plus: warning: command line option ‘-Wno-duplicate-decl-specifier’ is valid for C/ObjC but not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-unused-command-line-argument’
cc1plus: warning: unrecognized command line option ‘-Wno-exceptions’
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
cc1plus: warning: unrecognized command line option ‘-Wno-macro-redefined’
```

This also updates the gloo submodule commit to include the similar change made to gloo.
https://github.com/facebookincubator/gloo/commit/597accfd79f5b0f9d57b228dec088ca996686475

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Please consider using `append_cxx_flag_if_supported` macro

**Comment by jithunnair-amd** [comment]
> `append_cxx_flag_if_supported`

cc @jataylo

**Pull request closed without merging**
