### PR TITLE
Opt into Trusty builds.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by soumith** [comment]
python 2.7.8 seems to not be supported by trusty travis

**Comment by soumith** [comment]
the URL it tries to download i.e. https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-2.7.8.tar.bz2 does not exist.

**Comment by ezyang** [comment]
Yes. According to Travis https://github.com/travis-ci/travis-ci/issues/8153 they did not build this version of Python for Trusty. Is there are particular reason why this is the beginning of our version support?

**Comment by soumith** [comment]
it's the default python version in 12.04 if I remember correctly

**Comment by ezyang** [comment]
Nope :)

* https://web.archive.org/web/20161218150505/http://packages.ubuntu.com:80/precise-updates/python2.7
* https://web.archive.org/web/20161217173835/http://packages.ubuntu.com:80/precise/python2.7

But maybe there is an environment we care about where it is default. I'm looking.

**Comment by CDLuminate** [comment]
Default python2 for Ubuntu releases: https://launchpad.net/ubuntu/+source/python-defaults

Default python3 for Ubuntu releases: https://launchpad.net/ubuntu/+source/python3-defaults

**Pull request merged**
