### PR TITLE
[lint] upgrade mypy to latest version

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #76753

Fixes https://github.com/pytorch/pytorch/issues/75927.

Had to fix some bugs and add some ignores.

To check if clean:
```
lintrunner --paths-cmd='git grep -Il .' --take MYPY,MYPYSTRICT
```

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by ezyang** [comment]
If I run lintrunner after this commit will it tell me I have to upgrade mypy?

**Comment by suo** [comment]
> If I run lintrunner after this commit will it tell me I have to upgrade mypy?

yes, if you have the latest version

**Comment by suo** [comment]
Okay, it appears I cannot currently test this internally because the diff train is too far behind.

**Comment by suo** [comment]
@pytorchbot merge this

we can always revert later

**Comment by malfet** [comment]
@suo you beat me to it :)

**Pull request closed without merging**
