### PR TITLE
[TensorExpr] Fix lowering for aten::softmax for the case when dtype parameter is None.

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #66847
* #66846
* #66527
* #66522
* #66515
* #66514
* #66523
* #66519
* #66518
* #66517
* __->__ #66516

Differential Revision: [D31590858](https://our.internmc.facebook.com/intern/diff/D31590858)

### CODE REVIEW

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31590858).

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31590858).

**Review by navahgar — APPROVED** [review]
LGTM

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31590858).

**Pull request closed without merging**
