### PR TITLE
Grandfather in built-in TorchScript ops to being pt2_compliant

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #113061
* #113050

I'm seeing ops like torch.ops.aten.mul.complex being used with
torch.compile (though this seems strange to me), but we should
grandfather these in.

Test Plan:
- new tests

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
this area is also a good cleanup area 🤔

**Comment by huydhn** [comment]
@pytorchbot drci

(please ignore this, I'm testing Dr.CI)

**Comment by huydhn** [comment]
I think there is likely to be a bug here when you are using `keep-going` flag.  The test jobs crashed at the end even in the case where all tests had passed.  This gave the impression that the CI was super flaky.  I have filed an issue for this https://github.com/pytorch/pytorch/issues/113419

**Pull request closed without merging**
