### PR TITLE
Super tiny fix typo

### PR DESCRIPTION
**Pull request by fzyzcjy**
"CustoType" -> "CustomType"

### CODE REVIEW

**Review by awgu — APPROVED** [review]
Looks good

**Comment by fzyzcjy** [comment]
Hmm, I guess the failure is unrelated...

**Comment by awgu** [comment]
They should be unrelated, but let us just rebase to be safe.

**Comment by awgu** [comment]
The PR is past `viable/strict`, so we cannot rebase backwards. The failing tests are broken on trunk / flaky. This docs change should be benign.

**Pull request closed without merging**
