### PR TITLE
[RELEASE-ONLY CHANGES] Branch Cut for Release 2.6

### PR DESCRIPTION
**Pull request by atalman**
Generated via: https://github.com/pytorch/pytorch/blob/main/scripts/release/apply-release-changes.sh

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by ZainRizvi** [comment]
> Having to modify 80 files to create release branch feels very wrong to me

Has it always been this way? Seems like a BE opportunity to make release work easier...

**Comment by atalman** [comment]
@ZainRizvi and @malfet totally agree we need to improve this as BE task and perhaps stop putting ``@main`` when calling workflows but compute the branch on the fly

**Comment by kit1980** [comment]
I actually started a change to use the correct branch dynamically, without hardcoding it. But the change is not ready yet.

**Comment by atalman** [comment]
closing not required

**Pull request closed without merging**
