### PR TITLE
Add cpp stack traces to our own reruns

### PR DESCRIPTION
**Pull request by albanD**
Note that I'm not sure why we both have pytest rerun the failing test twice via https://github.com/pytorch/pytorch/blob/81abc2b2494ab7d48394b63d528eb5dddfa9d3d5/test/run_test.py#L966 before our own logic retries it as well?

The failing test is only here to make sure it works as expected in the CI env. Will remove before landing.

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!

**Comment by albanD** [comment]
Tests are showing the c++ stack traces as expected for the last 6 retries.

**Comment by albanD** [comment]
@pytorchbot merge -i 

All failures are unrelated

**Comment by albanD** [comment]
@malfet I'm not sure how to investigate the issue on the inductor tests further tbh.
So I'm proposing a stopgap were we disable stack traces for this test for now. This still gives us the main benefit of the proposal in this PR as it gives stack traces for everything else.

let me know if you would prefer a simpler "disable on all macos" and if you want me to open an issue to track this weird behavior.

**Comment by albanD** [comment]
Extending the skip to all inductor tests on macos as others are segfaulting

**Comment by albanD** [comment]
Ho sorry about that. Let me know how I can help!

**Comment by clee2000** [comment]
> Ho sorry about that. Let me know how I can help!

I merged the fix in https://github.com/pytorch/pytorch/pull/120251, right now I'm just waiting for CI on main to be a bit greener.  The PR shouldn't need any changes, except maybe a rebase if you want to be safe

**Pull request closed without merging**
