### PR TITLE
Renamed passes to options in torch.compile

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #94572
* #94561
* __->__ #94500

@jansel expressed a preference for this (as most of our options are *not* passes), and I agree. I also think that `fullgraph` could be changed, but I don't know what I'd change it to. I considered `strict`, but some folks objected to that.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]
Ah the old 1am rename

**Comment by voznesenskym** [comment]
Put up the fullgraph->strict pr and let's bikeshed there? (Cc: @gchanan)

**Review by soumith — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
