### PR TITLE
[ONNX] Update narrow for dynamic inputs

### PR DESCRIPTION
**Pull request by neginraoof**
Update narrow for dynamic inputs

### CODE REVIEW

**Review by BowenBao — APPROVED** [review]

**Comment by BowenBao** [comment]
Please rebase for unrelated CI test failures.

**Comment by neginraoof** [comment]
cc @bzinodev 
Can we please merge this PR?
Thanks

**Review by bzinodev — APPROVED** [review]

**Comment by neginraoof** [comment]
@bzinodev Can we merge this PR please? Thanks!

**Comment by neginraoof** [comment]
@bzinodev Can we merge this please?
Thanks.

**Comment by neginraoof** [comment]
@bzinodev Can we merge this PR please? Thanks!

**Pull request closed without merging**
