### PR TITLE
Fix building with PARALLEL_BACKEND=NATIVE_TBB

### PR DESCRIPTION
**Pull request by abonnet**
Fixing https://github.com/pytorch/pytorch/issues/26721

Test Plan:

```
export USE_OPENMP=0
export USE_TBB=1
export BLAS=MKL
export MKL_THREADING=TBB
export MKLDNN_THREADING=TBB
export PARALLEL_BACKEND=NATIVE_TBB
export USE_CUDA=0
python setup.py build
```

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by abonnet** [comment]
@zdevito I found this PR fixing the same issue for ParallelNative: https://github.com/pytorch/pytorch/pull/26746. How do you want to fix it? Based on your initial commit, I was under impression the goal was to always has a type.

**Comment by ljk53** [comment]
@abonnet - yeah, if we want to enforce type then we probably could set NoneType by default to avoid fixing all call sites (there are other places calling default constructor).

**Comment by ilia-cher** [comment]
Thanks for the fix! Let's merge this

**Comment by ilia-cher** [comment]
for the TBB build please ATEN_THREADING variable: https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html
(cc. @abonnet )

**Pull request closed without merging**
