### PR TITLE
refactor tensorify restart logic to use sources

### PR DESCRIPTION
**Pull request by bobrenjc93**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #141517

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv @voznesenskym @penguinwu @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @jiayisunx @chenyang78 @kadeng @chauhang @amjames

Differential Revision: [D67066706](https://our.internmc.facebook.com/intern/diff/D67066706)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by bobrenjc93** [comment]
@bobrenjc93 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D67066706).

**Pull request closed without merging**
