### PR TITLE
empty_cuda: Add functions that don't depend on Tensor

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #70618
* #70617
* __->__ #70616

This adds `at::detail::empty_cuda` and
`at::detail::empty_strided_cuda` to complement the cpu and meta APIs.

These functions also include the `lazyInitCUDA` and `DeviceGuard` that
are missing from the `at::native::empty_cuda` interface and so is
safer to use.

Differential Revision: [D33623677](https://our.internmc.facebook.com/intern/diff/D33623677)

### CODE REVIEW

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33623677).

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33623677).

**Comment by ngimel** [comment]
I agree it's safer, but previously `at::native::cuda` was used from the callsites that already dispatched to CUDA and thus already correctly set DeviceGuard (except for binary functions with the first scalar argument, but those had some separate handling), so it looks like replacing `at::native::cuda` with this function adds extra overhead?

**Comment by peterbell10** [comment]
>I agree it's safer, but previously `at::native::cuda` was used from the callsites that already dispatched to CUDA and thus already correctly set `DeviceGuard` (except for binary functions with the first scalar argument, but those had some separate handling), so it looks like replacing `at::native::cuda` with this function adds extra overhead?

Yes, there is some extra overhead but it seems dangerous to completely ignore the device index that was passed in. I do acknowledge that most of the time it likely doesn't matter though.

I measured the performance difference but it was completely dwarfed by the overall performance improvements of switching to `empty_generic`. To the point where `empty_cuda` is now > 2x faster even with the extra `DeviceGuard` (290,927 before vs. 131,040 after). The `DeviceGuard` itself costs around 10k instructions.

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33623677).

**Pull request closed without merging**
