### PR TITLE
Non Maximum Suppression

### PR DESCRIPTION
**Pull request by ghost**
This PR implements Non Maximum Suppression, as per pytorch/vision#392. For more rigorous (but slower) correctness tests than the one in test_nn.py, as well as a benchmarking script, take a look at [https://github.com/dssa56/projects/tree/master/nms](url). The gpu implementation here is a bit naive, but still performs quite well. I ran into performance problems with allocating and freeing intermediate buffers when trying a more sophisticated implementation; you can see what I was aiming for there if you look at "nms_cuda_workspace.cu" in the repo I linked to above.

### CODE REVIEW

**Comment by apaszke** [comment]
@soumith in that thread you mentioned that this would be an addition until we get ATen extensions, which are in master now. Do we want to start adding C++ code to vision?

**Comment by fmassa** [comment]
I think the place for NMS is in `torchvision`. I was thinking about adding it using the new ATen extensions, but it might be better to wait until v0.4 is released to add it there.

**Comment by soumith** [comment]
I agree, the place for this is torchvision. Please co-ordinate with @fmassa on where to put this in torchvision (unless fmassa already has NMS written and in-flight).

In fact, we are removing the ROIPooling stuff that is currently in ATen/native as well.

**Pull request closed without merging**
