### PR TITLE
Symintify embedding_sparse_backward

### PR DESCRIPTION
**Pull request by anjali411**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #88746

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Would be nice if aotdispatch started passing but I guess I wouldn't be surprised if OpInfo is covering this case rn

**Comment by anjali411** [comment]
@ezyang I don't see an xfail corresponding to this func in test_aotdispatch so I guess it is already passing? or are you referring to something else?

**Comment by ezyang** [comment]
I was hoping there was an existing test covering it. But we're more lax about C++ symintify because they also affect eager mode, so this'll do for now.

**Pull request closed without merging**
