### PR TITLE
[QOL] Raise a NameError when accessing non-existent variable

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96418

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM
We don't have test for these things I guess?

**Comment by ezyang** [comment]
It's pretty easy to add the test but I'm not sure how high utility it is

**Comment by albanD** [comment]
Ok!

**Pull request closed without merging**
