### PR TITLE
[BE] Move conda cmake installation to Docker

### PR DESCRIPTION
**Pull request by huydhn**
This is parts of the effort to consolidate pip and conda installation in the CI to improve our CI reliability.  This moves conda cmake installation to Docker in those use cases that require it:

* Ubuntu bionic and focal

On the other hand:
* XLA doesn't seem to need conda cmake anymore (Build and test successfully)
* Centos is not in used anywhere in the CI

### CODE REVIEW

**Review by ZainRizvi — APPROVED** [review]
Do we always build docker images with circleci?   Or does our docker script merely live in the `.circleci` folder for legacy reasons?

**Comment by huydhn** [comment]
> Do we always build docker images with circleci? Or does our docker script merely live in the `.circleci` folder for legacy reasons?

It's there for legacy reason. The docker build jobs are in GitHub Action. We could take a stab at refactoring `.circleci` and `.jenkins` later to something more reasonable.  @janeyx99 had tried this out in the past with the latter :)

**Review by malfet — APPROVED** [review]
Perhaps it would be nice to mention, that since CentOS/RHEL is no longer used,  `sudo yum -y remove cmake3` can be skipped

Also, please check binary builds (when CentOS might still be used)

**Comment by huydhn** [comment]
> Perhaps it would be nice to mention, that since CentOS/RHEL is no longer used, `sudo yum -y remove cmake3` can be skipped
> 
> Also, please check binary builds (when CentOS might still be used)

Confirmed that centos is not used anywhere in PyTorch CI or in binary builds https://github.com/pytorch/test-infra/blob/main/tools/scripts/generate_binary_build_matrix.py

**Pull request closed without merging**
