### PR TITLE
[PyTorch] AOTI: add more basic aoti_torch getters

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #113578
* #113577
* #112800
* __->__ #112799
* #112798
* #112405
* #112174
* #112116

Lot of simple information about tensors we couldn't get. In
particular, we didn't know the lengths of the arrays returned by sizes
and strides.

Differential Revision: [D50949929](https://our.internmc.facebook.com/intern/diff/D50949929/)

### CODE REVIEW

**Review by desertfire — APPROVED** [review]

**Review by aakhundov — APPROVED** [review]
LGTM, thanks! There seem to be some linter errors.

**Comment by atalman** [comment]
@oytorchbot revert -m "OSSCI oncall #112405 broke lint" -c ignoredsignal

**Comment by desertfire** [comment]
> @pytorchbot revert -m "OSSCI oncall #112405 broke lint" -c ignoredsignal

It's a stack of complicated changes. Let's do forward fixing if possible since it is only lint error.

**Comment by desertfire** [comment]
> > @pytorchbot revert -m "OSSCI oncall #112405 broke lint" -c ignoredsignal
> 
> It's a stack of complicated changes. Let's do forward fixing if possible since it is only lint error.

https://github.com/pytorch/pytorch/pull/115627

**Pull request closed without merging**
