### PR TITLE
Make add.Scalar manual_cpp_binding

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#49203 Make add.Scalar manual_cpp_binding**
* #49505 Add at::cpu namespace of functions for structured kernels

Manually do add.Scalar binding, skipping dispatch when you call into it from C++. This doesn't help if you directly get to the kernel via JIT interpreter though.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D25594995](https://our.internmc.facebook.com/intern/diff/D25594995)

### CODE REVIEW

**Comment by ezyang** [comment]
Looks like it doesn't work

```
======================================================================
ERROR: test_async_grad_guard_no_grad (jit.test_async.TestAsync)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/test/jit/test_async.py", line 352, in test_async_grad_guard_no_grad
    @torch.jit.script
  File "/data/users/ezyang/pytorch-tmp/torch/jit/_script.py", line 940, in script
    qualified_name, ast, _rcb, get_default_args(obj)
RuntimeError: 
Return value was annotated as having type Tensor but is actually of type float:
  File "<string>", line 5
  return b * a
def add(a : float, b : Tensor) -> Tensor:
  return b + a
  ~~~~~~~~~~~~ <--- HERE
def ne(a : float, b : Tensor) -> Tensor:
  return b != a
'add' is being compiled since it was called from 'foo'
  File "/data/users/ezyang/pytorch-tmp/test/jit/test_async.py", line 354
        @torch.jit.script
        def foo(x):
            y = x * 2
                    ~ <--- HERE
            return y.requires_grad


----------------------------------------------------------------------
Ran 2 tests in 0.071s

```

**Comment by ezyang** [comment]
Updated with a different approach. One downside here is that if you hit the native:: kernel you're still going to end up doing two dispatches. Might need to do some tricky codegen stuff to get around that problem.

**Review by robieta — APPROVED** [review]
This looks reasonable. What is the plan as more kernels become structured? (manually do this, teach the codegen, etc.)

Also, can you benchmark the change? Skipping a dispatch should be a strict improvement, but we should get in the habit of confirming.

**Comment by bdhirsh** [comment]
> One downside here is that if you hit the native:: kernel you're still going to end up doing two dispatches. Might need to do some tricky codegen stuff to get around that problem.

Is the two dispatches here referring to the fact that you have one dispatch for `at::scalar_tensor` (to convert the scalar) and another for `at::add(Tensor, Tensor)`? Or are you referring to something else (since that doesn't seem like something you can solve in codegen)?

**Comment by ezyang** [comment]
> Is the two dispatches here referring to the fact that you have one dispatch for at::scalar_tensor (to convert the scalar) and another for at::add(Tensor, Tensor)? Or are you referring to something else (since that doesn't seem like something you can solve in codegen)?

Nope, it's the extra dispatch from at::add(Tensor, Tensor). (In the old version of this code, predating the parent of commit of this PR, this was an at::native::add call, so no cost.)

**Comment by ezyang** [comment]
> What is the plan as more kernels become structured? (manually do this, teach the codegen, etc.)

No plan yet.  This diff is pretty short and so in the mid term I might just do all of these kernels this way.

**Comment by ezyang** [comment]
Benchmark:

Control:

```
import torch
from torch.utils.benchmark import Timer

c = Timer(
    stmt='a + a',
    setup=f'a = torch.rand(3, 4)'
).collect_callgrind(number=100, collect_baseline=False)
print(c.counts(denoise=True))
```

Before: 849190
After: 848999

(This experiment is expected to show no diff.)

Python scalar add `stmt='a + 2'`

Before: 1986043
After: 1979842

(This experiment is expected to show no diff, as wrapping is supposed to happen in Python bindings bypassing relevant C++)

C++ scalar add (expected to exercise)

```
    stmt='a + 2;',
    setup='auto a = torch::randn({3, 4});',
    language='cpp'
```

Before: 1726143
After: 1689743

Example from benchmark suite 

```
    stmt='a += 1',
    setup='a = torch.rand(3, 4)'
```

Before: 1751566
After: 1751262

**Comment by ezyang** [comment]
@robieta This diff should be landed, but it didn't actually improve `a += 1` which suggests something else is going on in the regression in #48718 (actually, this is consistent with sum also regressing, where there wasn't an obvious code impact there)

**Comment by ezyang** [comment]
On further reflection, if this isn't fixing a concrete performance problem (which it isn't), I'd rather not copy paste `wrapped_scalar_tensor` everywhere as it would impede further improvements cited by https://github.com/pytorch/pytorch/issues/49758

If we do https://github.com/pytorch/pytorch/issues/50953 that would also solve these problems, with less code duplication. So I think this is not worth it for now.

**Pull request closed without merging**
