### PR TITLE
Passing indices as a list to Subset instead of Tensor

### LINKED ISSUE #17466: torch.utils.data DataLoader does not index by integers
## 📚 Documentation

Hi, it seems DataLoader with shuffle=True does not index dataset by integers but by torch.tensor instances of integers. I suspect, this happens in multiple places, especially samplers. This might seem like unimportant case, however I managed to run out of memory on my 250G server because I was internally actually indexing into dictionary. And since tensor instances don't have reasonable `__hash__`, I was never able to find my loaded item.

See the snippet of the code to illustrate the problem, if option `keep_ram` was passed to the constructor of `LiDARDataset` and the two commented lines in `__getitem__` were not there, the process would grow in memory with every call to `__getitem__`. However, if the check for integer is there, the dataset stays at around 12G, which is actually expected and does not grow.

    class LiDARDataset(torch.utils.data.Dataset):
        def __init__(self, folder, keep_ram=False):
            self.names = sorted(glob.glob(os.path.join(folder, '*.npy')))
            self.keep_ram = keep_ram
            if self.keep_ram:
                self.loaded = dict()
            else:
                self.loaded = weakref.WeakValueDictionary()

        def __len__(self):
            return len(self.names)

        def __getitem__(self, key):
            if not isinstance(key, int): # without these two lines, it would grow
                key = key.item() 
            result = self.loaded.get(key) # because the result would always be None
            if result is None:
                result = self.transform(np.load(self.names[key]), key)
                self.loaded[key] = result
            return result

### PR DESCRIPTION
**Pull request by bhushan23**
Indices in Subset were stored as tensors earlier
passing as list in random_split to ensure integer indexing

fixes: #17466

### CODE REVIEW

**Review by ssnl — CHANGES_REQUESTED** [review]
This is wrong. You need to index using indices from sampler, and dataset  likely doesn't support slicing.

**Comment by bhushan23** [comment]
> This is wrong. You need to index using indices from sampler, and dataset likely doesn't support slicing.

@SsnL 
Sampler are indeed passing indices as a list.
random_split was passing indices as a tensor to Subset 
passing as a list now.

samplers are good, I guess. I might be wrong, Please correct me.

**Comment by bhushan23** [comment]
@SsnL any update?

**Review by ssnl — COMMENTED** [review]
Can we have a test for this?

**Review by ssnl — APPROVED** [review]

**Pull request closed without merging**
