### PR TITLE
a small fix to `setWildcard`

### PR DESCRIPTION
**Pull request by Krovatkin**
this fixes a corner case where there's an aliasing chain
  v -> a1 -> a2 -> ... , and now v -> (*).
  if v may alias a wildcard anything v points to
  may **also** alias the wildcard.
  A simple example of this case would be:
  ```python
  def fn():
      x = torch.ones(2, 3)
      x_1 = x.view(-1)
      l = []
      l.append(x_1)
      x_view = l[0]
      x.add_(torch.ones(2, 3))
      return x_view
  ```
  if the fact that x points to (*) isn't recorded,
  `x.add_(torch.ones(2, 3))` will be removed by DCE,
  since x isn't alive at the end of `test_indirect`
  yet x, x_view, x1 all share the same memory
  and x_view is returned to the user.

### CODE REVIEW

**Comment by suo** [comment]
Can we add a test for this?

**Comment by Krovatkin** [comment]
@suo 

done!

**Review by zdevito — APPROVED** [review]
This needs context. I also do not know if it is right, but I am assuming @suo checked that and just wanted a test.

**Comment by Krovatkin** [comment]
already fixed.

**Pull request closed without merging**
