### PR TITLE
Remove import * from python files in test files

### LINKED ISSUE #112371: Why is flake8 F821 disabled
Flake8 F821 "undefined name" is one of the most useful flake8 rules (see recent https://github.com/pytorch/pytorch/pull/112336 as an example).

Yet the rule is disabled:
https://github.com/pytorch/pytorch/blob/bbd5b935e49a54578ac88cb23ca962ab896a8c7a/.flake8#L10
https://github.com/pytorch/pytorch/blob/bbd5b935e49a54578ac88cb23ca962ab896a8c7a/pyproject.toml#L43

I think the rule needs to be at least selectively enabled. There are currently multiple actual issues in the codebase that can be caught by this rules.

### PR DESCRIPTION
**Pull request by maya-undefined**
Fixes #112371

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @aakhundov

### CODE REVIEW

**Comment by maya-undefined** [comment]
Previous work done in 116572 but ran into issues with some checks. Reopened here with same diff

**Comment by colesbury** [comment]
Added reviewers from the previous PR https://github.com/pytorch/pytorch/pull/116572

**Review by albanD — APPROVED** [review]
Thanks

**Comment by albanD** [comment]
CI failures are real!

**Pull request closed without merging**
