### PR TITLE
[RELAND] Move at::{Refcounted,}MapAllocator to c10

### PR DESCRIPTION
**Pull request by peterbell10**
Resubmit of #109881

`libshm.so` depends on the torch library exclusively for `at::RefcountedMapAllocator`, so it makes sense to move it to c10 along with the other other memory allocators.

This means `libshm.so` only depends on `c10` and we don't need to relink `libshm.so` for every ATen change.

### CODE REVIEW

**Comment by kit1980** [comment]
@peterbell10 Meta-internal buck fails on `linkopts` parameter to `cc_library` - no such thing supported.
It doesn't even tries to compile...

**Comment by kit1980** [comment]
A minor unrelated thing - please fix lint.

**Comment by peterbell10** [comment]
@kit1980 what is the recommended way to link against `rt` there then? In `oversource_defs,bzl` I have a dependency on `//third-party/rt` but I don't think that worked in `build.bzl`. I could be wrong though, it's been a while.

**Comment by lezcano** [comment]
ping @kit1980

**Comment by lezcano** [comment]
ping @kit1980

**Comment by kit1980** [comment]
Sorry, I was working on unrelated things.
I'll look again soon, but could you resolve merge conflict?

**Comment by peterbell10** [comment]
@kit1980 I've rebased and fixed the conflicts

**Comment by lezcano** [comment]
This PR hit merge conflicts again. Could we try to rebase it and get it landed after rebasing it? @kit1980 do you have bandwidth do to that after Peter rebases?

**Comment by lezcano** [comment]
@peterbell10 using the lastest https://github.com/Quansight/torch-build/ and using cudatoolkit from conda I was not able to repro our previous linking issue.
If you can still repro it in your environment, could you open a separate issue?

The context here is that @kit1980 has tried to land this PR internally, but it's rather non-trivial, so perhaps it's better to find another fix for the linker issue and move on.

**Comment by peterbell10** [comment]
Hmm I think I missed the update on attempts to land internally. The linker error no longer happen and it seems like someone has changed `libshm` to link directly to `torch_cpu`.  If that was the fix then it suggests the `torch` library isn't set up correctly, but oh well I don't have time to investigate.

**Pull request closed without merging**
