### PR TITLE
Docs for torchcompile and functorch

### PR DESCRIPTION
**Pull request by msaroufim**
### <samp>🤖 Generated by Copilot at b5f48b6</samp>

> _`torch.compile` docs_
> _Add a new section for `func`_
> _Winter of features_

Thanks @zou3519

### CODE REVIEW

**Review by eellison — APPROVED** [review]
🚀

**Comment by msaroufim** [comment]
@pytorcbot merge

**Review by zou3519 — APPROVED** [review]
Thanks!

@kshitij12345 is working on adding PT2 support for functorch transforms, so if/when we ship those improvements we'll need to update these docs

**Comment by zou3519** [comment]
Did copilot really generate a haiku?

**Comment by msaroufim** [comment]
@pytorbot merge

**Comment by zou3519** [comment]
@msaroufim I couldn't find this page in the docs, did we remove it somewhere?

**Comment by msaroufim** [comment]
@svekars moved everything under the torch.compiler namespace in docs

**Comment by zou3519** [comment]
Oh I see. I found it in the FAQ: https://pytorch.org/docs/main/torch.compiler_faq.html#applying-a-torch-func-transform-to-a-function-handled-with-torch-compile

**Pull request closed without merging**
