### PR TITLE
Correctly specify size of sparse_csr tensors in maskedtensor binary ops

### PR DESCRIPTION
**Pull request by benjaminglass1**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134335

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jcaip

### CODE REVIEW

**Comment by benjaminglass1** [comment]
These tests appear to have failed because the mask completely masked out one full row of the data arrays, and the `sparse_csr_tensor` function incorrectly guessed the size as one row less in those cases. This PR specifies the desired size for the output tensor so that these tests will succeed.

**Review by amjames — APPROVED** [review]
Looks good. Nice catch.

**Comment by amjames** [comment]
Labeling this as `sparse` since I couldn't find a better label for `MaskedTensor` 🤷

**Comment by benjaminglass1** [comment]
Fixed the lint error.

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
