### PR TITLE
[7/N] [Dispatchable Collectives] Update reduce with CPU / CUDA implementations

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #86409 [13/N] Update gather with CPU/CUDA implementations
* #86408 [12/N] Update scatter with CPU/CUDA implementations
* #86407 [11/N] Update all_to_all with CPU/CUDA implementations
* #86368 [10/N] Update barrier with CPU/CUDA implementations
* #86166 [9/N] [Dispatchable Collectives] Update reduce_scatter with CPU / CUDA implementations
* #84423 [8/N] [Dispatchable Collectives] Update allgather with CPU / CUDA implementations
* **#83916 [7/N] [Dispatchable Collectives] Update reduce with CPU / CUDA implementations**

### Changes
- Updates for the reduce collective

### Context
https://github.com/pytorch/pytorch/issues/86225

### CODE REVIEW

**Review by kwen2501 — APPROVED** [review]
LGTM! Thanks!

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40044551).

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40044551).

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40044551).

**Pull request closed without merging**
