### PR TITLE
added rocm 3.8 docker image

### PR DESCRIPTION
**Pull request by KyleCZH**
@jeffdaily

### CODE REVIEW

**Comment by jeffdaily** [comment]
@ezyang looks like our image build is failing because the valgrind tarball URL is no longer working.  Are we okay updating this to the latest valgrind release version 3.16.1?  I believe that would update all images, but I'm surprised we haven't seen this fail for any other image yet.

**Comment by jeffdaily** [comment]
@walterddr or @malfet , do you have an opinion on whether we can use a newer valgrind to resolve our image build issue?

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@jeffdaily please update the valgrind URI to the latest version and I will try to land the change

**Review by walterddr — APPROVED** [review]

**Comment by jeffdaily** [comment]
@ezyang or @seemethere , we need the AWS ECR entry created for our new image.  `pytorch/pytorch-linux-bionic-rocm3.8-py3.6`  That's why the build is failing.  The image push was failing, but the dr-ci bot was showing the failure as the valgrind download.  That was the confusion.

**Comment by ezyang** [comment]
Should be added now

**Pull request closed without merging**
