### PR TITLE
Use multi-dimensional cuFFT transforms to improve FFT performance

### PR DESCRIPTION
**Pull request by xwang233**
Benchmark and numerical accuracy tests on A100 and V100 are available at https://github.com/xwang233/code-snippet/tree/master/fft-61203.

I've checked the FFT results for different shapes/dims and different `dim` arg for `rfftn` and `irfftn` before and after this PR, and they all numerically matched.

With this PR, about 10%~15% performance gain is expected on commonly used shapes and dims.

### CODE REVIEW

**Comment by ezyang** [comment]
@zou3519 you think you can review this one?

**Comment by xwang233** [comment]
ping @zou3519 , the PR is ready for review

**Review by zou3519 — COMMENTED** [review]
Code seems reasonable to me. The benchmarks show some slowdowns in some cases -- is the argument that the speedups on other use cases outweigh the slowdowns?

**Comment by xwang233** [comment]
@zou3519 The slow downs are mostly FFT in non-contiguous dimensions. For FFT in contiguous dimensions (especially dim -1, -2, etc.), we can experience speed ups. So it would be beneficial to have this.

**Comment by xwang233** [comment]
Hi @zou3519 , is this PR ready to go?

**Comment by xwang233** [comment]
Hi @zou3519 , is this PR ready to go ?

**Comment by zou3519** [comment]
Sorry, missed the comments until now. Yes, this LGTM, going to attempt to merge it.

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
