### PR TITLE
[inductor] Rewrite Triton templates + epilogue fusion (retry)

### PR DESCRIPTION
**Pull request by jansel**
https://github.com/pytorch/pytorch/pull/90738 seems a bit borked. ghimport fails on it, and I unlinked it from the Phabricator diff, but it still won't land.  This is an exact copy that PR without using ghstack.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by atalman** [comment]
Broke internal builds with following error:
```
2022-12-20T22:50:15.624473Z  WARN buck2_client_ctx::subscribers::event_log: Error uploading logs: Timed out waiting for log upload to manifold: deadline has elapsed
BUILD FAILED
file `fbcode//caffe2/torch/_inductor/codegen/triton_conv_delta_x.j2` not found
```

**Comment by malfet** [comment]
This revert broke trunk, see https://github.com/pytorch/pytorch/actions/runs/3745136052/jobs/6359527089  :(

**Comment by atalman** [comment]
@malfet should we disable this test, ad reland this PR with all required files included ?

**Comment by desertfire** [comment]
> @malfet should we temporarily disable this test, and reland this PR with all required files included ?

 https://github.com/pytorch/pytorch/pull/91227 partly reverts this revert for the part that relates to the trunk failure. We can merge it once `inductor_huggingface` shard passes.

**Comment by desertfire** [comment]
cc @williamwen42

**Comment by kit1980** [comment]
> > @malfet should we temporarily disable this test, and reland this PR with all required files included ?
> 
> #91227 partly reverts this revert for the part that relates to the trunk failure. We can merge it once `inductor_huggingface` shard passes.

It just passed and I force-merged.

**Comment by soumith** [comment]
this PR also needs to add `jinja2` to the `requirements`

**Pull request closed without merging**
