### PR TITLE
Moving ProcessGroupNCCLTest to Gtest

### PR DESCRIPTION
**Pull request by osalpekar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #42211 Clean up CUDA Sleep and Tensor Initialization in ProcessGroupNCCLTest
* #42209 TearDown function for ProcessGroupNCCLTest Initializer
* **#42208 Moving ProcessGroupNCCLTest to Gtest**

ProcessGroupNCCLTest is currently written without any testing framework, and all tests are simply called from the main function and throw exceptions upon failure. As a result, it is hard to debug and pinpoint which tests have succeeded/failed.

This PR moves ProcessGroupNCCLTest to gtest with appropriate setup and skipping functionality in the test superclass.

Differential Revision: [D22782673](https://our.internmc.facebook.com/intern/diff/D22782673/)

### CODE REVIEW

**Review by mrshenli — COMMENTED** [review]
Shall we also enable this test by adding it to `.jenkins/pytorch/test.sh`?

**Comment by osalpekar** [comment]
> Shall we also enable this test by adding it to `.jenkins/pytorch/test.sh`?

@mrshenli Sure thing. Just to confirm, since these tests all require CUDA, they will just be skipped on Jenkins right?

**Comment by mrshenli** [comment]
> @mrshenli Sure thing. Just to confirm, since these tests all require CUDA, they will just be skipped on Jenkins right?


Looks like it can detect whether the test env has CUDA. And looks like circleci tests are also using this file. 

https://github.com/pytorch/pytorch/blob/d5de616a4a9b56590d0c0efb5ac1db5467f64e2b/.jenkins/pytorch/test.sh#L231-L242

**Comment by osalpekar** [comment]
@mrshenli Sounds good - I've enabled this test by adding it to `.jenkins/pytorch/test.sh` in the latest version

**Review by mrshenli — COMMENTED** [review]
The build error looks relevant?

```
Jul 29 18:20:41 (.text+0x20): undefined reference to `main'
Jul 29 18:20:41 CMakeFiles/ProcessGroupNCCLTest.dir/ProcessGroupNCCLTest.cpp.o: In function `ProcessGroupNCCLTest_testReduceScatter_Test::~ProcessGroupNCCLTest_testReduceScatter_Test()':
```

**Review by mrshenli — APPROVED** [review]
Thanks for adding this!

**Pull request closed without merging**
