### PR TITLE
[dynamo] ignore False/None callback in fail_on_recompile/force_backend stances

### PR DESCRIPTION
**Pull request by williamwen42**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #139215

Fix https://github.com/pytorch/pytorch/issues/139202

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by williamwen42** [comment]
force_backend also has this issue - but this behavior could be intentional. Should we disable/run mode override force_backend?

**Review by jansel — APPROVED** [review]

**Comment by jansel** [comment]
disable/run decorators should not be effected by force_backend.

**Pull request closed without merging**
