### PR TITLE
Disable XProtect on MacOS runner

### PR DESCRIPTION
**Pull request by huydhn**
A theory is that something else on the runner removes the file like Windows Defender.  The number one suspect is `com.apple.XProtect.daemon.scan` https://support.apple.com/guide/security/protecting-against-malware-sec469d47bd8/web

Spot checking on some runners:

* On 13.x (13.3.1 and 13.2.1), the daemon is now called `com.apple.XProtect.daemon.scan`
```
sh-3.2$ sudo launchctl list | grep -i protect
8048	-9	com.apple.XprotectFramework.PluginService
8047	-9	com.apple.XProtect.daemon.scan
```

* On 12.4, the daemon is called `com.apple.XprotectFramework`
```
sudo launchctl list | grep -i protect
-	-9	com.apple.XprotectFramework.PluginService
-	-9	com.apple.XprotectFramework.scan
```

Looking at the list of failures in https://hud.pytorch.org/failure/ModuleNotFoundError%3A%20No%20module%20named%20'sympy', I can confirm that the issue happens with both MacOS 12 and 13 as I can find examples on both.

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by huydhn** [comment]
I have also added the logic to archive and upload the whole RUNNER_TEMP directory with all the conda environment to GHA when the test job fail, so that it can be downloaded and bisected.  At the moment, there are too much guesswork as the temp dir is always cleaned up after without leaving any clues

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Found a clue on the uploaded archive, reverting this so I can update the PR with the correct mitigation' -c weird

* `/Users/ec2-user/runner/_work/_temp/conda_environment_4763109030` doesn't have `sympy`.
```
/Users/ec2-user/runner/_work/_temp/miniconda/bin/conda run -p /Users/ec2-user/runner/_work/_temp/conda_environment_4763109030 --no-capture-output python3 -mpip list
Package           Version
----------------- ------------------
certifi           2022.12.7
expecttest        0.1.3
ninja             1.10.2
numpy             1.22.3
Pillow            9.2.0
pip               22.2.2
PyYAML            6.0
setuptools        61.2.0
torch             2.1.0a0+gitda57d59
typing_extensions 4.3.0
wheel             0.37.1
```

* `/Users/ec2-user/runner/_work/_temp/conda-python-3.9.12` doesn't have `sympy`.  When working correctly, this one should have it.
```
/Users/ec2-user/runner/_work/_temp/miniconda/bin/conda run -p /Users/ec2-user/runner/_work/_temp/conda-python-3.9.12 --no-capture-output python3 -mpip list
Package           Version
----------------- ------------------
certifi           2022.12.7
expecttest        0.1.3
ninja             1.10.2
numpy             1.22.3
Pillow            9.2.0
pip               22.2.2
PyYAML            6.0
setuptools        61.2.0
torch             2.1.0a0+gitda57d59
typing_extensions 4.3.0
wheel             0.37.1
```

* Surprisingly, the base conda env `/Users/ec2-user/runner/_work/_temp/miniconda` has `sympy` and other missing PIP dependencies.
```
/Users/ec2-user/runner/_work/_temp/miniconda/bin/conda run -p /Users/ec2-user/runner/_work/_temp/miniconda --no-capture-output python3 -mpip list
Package           Version
----------------- ------------------
appdirs                 1.4.4
attrs                   23.1.0
audioread               3.0.0
boto3                   1.19.12
botocore                1.22.12
brotlipy                0.7.0
certifi                 2022.12.7
cffi                    1.15.1
charset-normalizer      2.0.12
conda                   23.1.0
conda-content-trust     0.1.3
conda-package-handling  2.0.2
conda_package_streaming 0.7.0
cryptography            38.0.4
decorator               5.1.1
exceptiongroup          1.1.1
execnet                 1.9.0
expecttest              0.1.3
filelock                3.6.0
hypothesis              6.56.4
idna                    3.4
iniconfig               2.0.0
jmespath                0.10.0
joblib                  1.2.0
lazy_loader             0.2
librosa                 0.10.0.post2
llvmlite                0.39.1
lxml                    4.9.2
mpmath                  1.2.1
msgpack                 1.0.5
networkx                2.8.7
ninja                   1.10.2
numba                   0.56.0
numpy                   1.22.4
nvidia-ml-py            11.525.84
opt-einsum              3.3.0
packaging               23.1
pip                     22.3.1
pluggy                  1.0.0
pooch                   1.6.0
psutil                  5.9.1
pycosat                 0.6.4
pycparser               2.21
Pygments                2.12.0
pyOpenSSL               22.0.0
PySocks                 1.7.1
pytest                  7.2.0
pytest-flakefinder      1.1.0
pytest-rerunfailures    10.3
pytest-shard            0.1.2
pytest-xdist            3.0.2
python-dateutil         2.8.2
PyYAML                  6.0
requests                2.28.1
ruamel.yaml             0.17.21
ruamel.yaml.clib        0.2.6
s3transfer              0.5.2
scikit-learn            1.2.2
scipy                   1.9.0
setuptools              67.7.0
six                     1.16.0
sortedcontainers        2.4.0
soundfile               0.12.1
soxr                    0.3.5
sympy                   1.11.1
threadpoolctl           3.1.0
tomli                   2.0.1
toolz                   0.12.0
tqdm                    4.64.1
typing_extensions       4.5.0
unittest-xml-reporting  3.2.0
urllib3                 1.26.15
wheel                   0.37.1
xdoctest                1.1.0
zstandard               0.18.0
```

It's a puzzle why conda use the wrong environment here as the `--prefix` is clearly correct.  However, as `pytorch` is installed in the correct environment, a simple mitigation could be just to re-install these dependencies together with `pytorch` wheel if they are missing

**Pull request closed without merging**
