### PR TITLE
Tensor construction codemod

### PR DESCRIPTION
**Pull request by jerryzh168**
Summary:
Codemod generated with clangr shard mode, 25 files per diff,
motivation: https://github.com/pytorch/pytorch/pull/12407

Differential Revision: D13725460

### CODE REVIEW

**Comment by ezyang** [comment]
This diff is very long and it has a lot of different kinds of codemods. How many distinct code patterns ended up in the codemod script?

**Comment by ezyang** [comment]
what does "manual diff" mean here? Does that mean the changes were done by hand? In that case, it's even more important to keep the diffs small

**Comment by jerryzh168** [comment]
Yes, changes are done by hand. OK..I'll make manual changes smaller next time

**Pull request closed without merging**
