### PR TITLE
[inductor] Update triton pin

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #121568
* #121733
* __->__ #121268

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by peterbell10** [comment]
Benchmark results show no massive swings. Blueberries with cudagraphs show a 6% improvement, which may just be in the noise. There is a highlighted speedup for `functorch_dp_cifar10`, `resnet18` and `timm_efficientdet` but I don't know if I trust those results.

https://hud.pytorch.org/benchmark/compilers?startTime=Tue%2C%2005%20Mar%202024%2013%3A24%3A11%20GMT&stopTime=Tue%2C%2012%20Mar%202024%2013%3A24%3A11%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=gh/peterbell10/701/orig&lCommit=1f213c2454f3bb1f2dadc8b7f868625f516e24b0&rBranch=main&rCommit=291ce86a6cece257104a973f6e7af54e67252432

**Review by oulgen — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by oulgen** [comment]
@aakhundov the failing test is the test you added, want to take a look?

**Comment by aakhundov** [comment]
> the failing test needs expectations updated

@peterbell10 There are actually two tests that need an update in the expected result: `test_argmax` and `test_reduce_sum`. Here's the comment from one of them (same is applicable to the other):

https://github.com/pytorch/pytorch/blob/6d8a7d6e58c9c85f95024ea88e11921222493b2a/test/inductor/test_triton_kernels.py#L1206-L1211

I'd fix this myself, but we really need this change to be included in this PR (so that if it is reverted together with the Triton pin update, if we need a revert). Thanks!

**Comment by oulgen** [comment]
Actually, we chatted offline, and this will break internal CI since internal triton version wont be bumped with this PR. @aakhundov will prepare a PR to fix this on master and then you can rebase over it.

**Comment by oulgen** [comment]
https://github.com/pytorch/pytorch/pull/121753 fixes the failing test, no need for is_fbcode checks

**Comment by aakhundov** [comment]
@peterbell10 https://github.com/pytorch/pytorch/pull/121753 has just merged, so rebasing onto main should make the original `test_argmax` and `test_reduce_sum` work on the Triton versions before and after this diff.

**Comment by peterbell10** [comment]
Think I beat you by about 30 seconds there :)

**Pull request closed without merging**
