### PR TITLE
Update isDynamic api to align with is_symbolic API

### PR DESCRIPTION
**Pull request by miladm**
Downstream #https://github.com/pytorch/xla/pull/3888

### CODE REVIEW

**Comment by miladm** [comment]
@Krovatkin can I get a stamp here? I can remove the pin once you approved the change. Thanks. I will do the same for the downstream PR in PT/XLA.

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Comment by Krovatkin** [comment]
@miladm we will need to keep the pin to make sure we don't break pytorch/master. Looks like you need to rebase PR to keep your pin

**Comment by JackCaoG** [comment]
I think we can leave the pin as it is, merge this pr. Remove the pin from the pt/xla pr and merge that pr. After midnight the bot should update pytorch's xla pin to the new master commit then we are good.

**Comment by miladm** [comment]
Thanks for the comments. Will merge after rebase is done.

**Comment by ezyang** [comment]
It doesn't seem like pytorchbot has successfully updated the pin since this landed

**Comment by janeyx99** [comment]
@clee2000 looks like the hash update can't handle branch names yet/the git show does not parse the date correctly https://github.com/pytorch/pytorch/runs/7946853704?check_suite_focus=true

**Comment by clee2000** [comment]
should be fixed with https://github.com/pytorch/pytorch/pull/83865 and hash update from last night also when through https://github.com/pytorch/pytorch/pull/83899

**Pull request closed without merging**
