### PR TITLE
[cmake] add HAVE_SOVERSION option (default=OFF).

### PR DESCRIPTION
**Pull request by cdluminate**
This is useful for linux distributions when the ABI/API of libtorch has
been changed. The default SOVERSION is set to
"${TORCH_VERSION_MAJOR}.${TORCH_VERSION_MINOR}".

@ezyang 

But if the release strategy of pytorch/caffe2 involves avoiding breaking API/ABI changes to libtorch for minor/patch releases, then we can set `TORCH_SOVERSION` to simply `TORCH_VERSION_MAJOR`. Please confirm that.

### CODE REVIEW

**Comment by cdluminate** [comment]
I'll fix the tab problem after receiving the ack.

**Comment by ezyang** [comment]
We definitely don't maintain binary compatibility, ever.

**Comment by cdluminate** [comment]
> We definitely don't maintain binary compatibility, ever.

Then I think `${MAJOR}.${MINOR}` is a sensible choice for soversion.

**Comment by cdluminate** [comment]
Fixed the tab issue and force-pushed.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
waiting on CI

**Pull request closed without merging**
