### PR TITLE
enable auto functionalize v2 by default

### PR DESCRIPTION
**Pull request by laithsakka**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136685
* #137760

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by zou3519 — COMMENTED** [review]
Gonna need some fixes for compiled autograd. Easiest way is probably to have compiled autograd use v1 and we figure out how to migrate it over. Though the fix is not hard, see https://github.com/pytorch/pytorch/pull/135169

**Comment by laithsakka** [comment]
> Gonna need some fixes for compiled autograd. Easiest way is probably to have compiled autograd use v1 and we figure out how to migrate it over. Though the fix is not hard, see #135169

oh those are new tests. i will take a look

**Review by zou3519 — APPROVED** [review]
lgtm as long as the CI is green

**Comment by laithsakka** [comment]
rebase on main.

**Pull request closed without merging**
