### PR TITLE
Update parallel_for/reduce doc

### PR DESCRIPTION
**Pull request by albanD**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #28546 Fix embedding renormalization on cpu
* **#28545 Update parallel_for/reduce doc**

Differential Revision: [D18251534](https://our.internmc.facebook.com/intern/diff/D18251534)

### CODE REVIEW

**Comment by albanD** [comment]
CI failures are unrelated to the 10 lines a comment I added.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
CC @ilia-cher

**Comment by ilia-cher** [comment]
Could you elaborate more on why tensor ops cannot be used?

**Comment by ilia-cher** [comment]
also, what "thread local states" do you mean here?
generally speaking parallel_for cannot know about any arbitrary thread local variables that need to be copied, unless you mean some specific thread local storage that we may consider

**Comment by albanD** [comment]
> Could you elaborate more on why tensor ops cannot be used?

The dispatcher uses thread local variables to handle `Variable`: when called with a Variable, it sets a thread local value then dispatch to the Variable handler. This handler can call the dispatch for the same function again and get the `Tensor` version of the method.

The particular bug that triggered this discussion is discussed in https://github.com/pytorch/pytorch/issues/28370

> also, what "thread local states" do you mean here?

I mean all of them here. But I'm not a specialist, so maybe there is a better wording.
The goal is to discourage adding code like [this](https://github.com/pytorch/pytorch/blob/5ae909b443570ae89b3716185cb9d26e4081a619/torch/csrc/api/include/torch/nn/parallel/data_parallel.h#L207-L227) where a forward pass is done on a module without taking care of propagating any thread local state (being cuda streams / gradmode / dispatch state etc).

**Pull request closed without merging**
