### PR TITLE
Enable inductor-rocm workflow for all trunk commits AND inductor-related PRs

### PR DESCRIPTION
**Pull request by jithunnair-amd**
It should help with triaging ROCm-inductor-related breakages and surfacing them in the PRs itself.

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
Tested that [commit](https://github.com/pytorch/pytorch/pull/138623/commits/6f0e430ed13aa92c55f82f9b497fa8e0dcf59bee) triggered [inductor-rocm](https://github.com/pytorch/pytorch/actions/runs/11607504829)

**Review by huydhn — APPROVED** [review]
LGTM!

**Comment by jithunnair-amd** [comment]
Fix worked as per: https://github.com/pytorch/pytorch/actions/runs/11962833666/job/33352070792#step:14:187

@pytorchbot merge -f "Fixed lint concurrency group naming"

**Pull request closed without merging**
