### PR TITLE
[LTC] Upstream LazyTensor <=> at::Tensor utils

### PR DESCRIPTION
**Pull request by alanwaketan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70069
* __->__ #70066

Summary:
This commit upstreams utils to convert at::Tensors into LazyTensors and
vice versa.

Test Plan:
Covered by test_ptltc on the lazy_tensor_staging branch since TorchScript
Backend hasn't merged yet.

Differential Revision: [D33171590](https://our.internmc.facebook.com/intern/diff/D33171590)

### CODE REVIEW

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33171590).

**Comment by desertfire** [comment]
I think it may be better to put these in a separate file. For core classes like LazyTensor, almost for sure they will be inherited and overridden by different backends, e.g. something like XLALazyTensor, which means XLA will have its own Tensor<->XLALazyTensor utils, thus it makes sensor to put them into another file. Let me know what you think.

**Comment by alanwaketan** [comment]
> I think it may be better to put these in a separate file. For core classes like LazyTensor, almost for sure they will be inherited and overridden by different backends, e.g. something like XLALazyTensor, which means XLA will have its own Tensor<->XLALazyTensor utils, thus it makes sensor to put them into another file. Let me know what you think.

I mean they could have their own utils and put them into the same file i.e. XLALazyTensor.h/.cpp. I'm not sure why having the conversions into the same file hurt anything. At least, we are going to introduce TSLazyTensor for TS backend, and make LazyTensor a pure virtual class?

**Comment by desertfire** [comment]
@JackCaoG, any thought here? I want to make sure your migration is smooth wrt. this LazyTensor class.

**Comment by JackCaoG** [comment]
Hmm I think I am missing something here. Is there a plan for `TSLazyTensor`? So far all methods related to `LazyTensor` pass `LazyTensor` (non pointer) object around. If the plan is for each backend to inherit `LazyTensor` class then we should pass `LazyTensor*` instead in `Lazytensor.h/cpp`.


As for pt/xla, I am still unsure what to do with `Lazytensor` class, I think I have 2 options
1. Use the `LazyTensor` class directly and introduce more backend APIs until all of pt/xla's requirement is meet
2. Introduce a `XlaLazyTensor` but this will require the `object -> pointer` change I mentioned above.

I am leaning toward option2 since it gives backend more flexibility. Option1 limited the places where backend can implement their custom logic and in the long term when more backends adapts LazyTensor it might be too restricted.  @wconstab any thoughts on this?

**Review by desertfire — APPROVED** [review]
Approve to speed up merging

**Comment by desertfire** [comment]
> Hmm I think I am missing something here. Is there a plan for `TSLazyTensor`? So far all methods related to `LazyTensor` pass `LazyTensor` (non pointer) object around. If the plan is for each backend to inherit `LazyTensor` class then we should pass `LazyTensor*` instead in `Lazytensor.h/cpp`.
> 
> As for pt/xla, I am still unsure what to do with `Lazytensor` class, I think I have 2 options
> 
> 1. Use the `LazyTensor` class directly and introduce more backend APIs until all of pt/xla's requirement is meet
> 2. Introduce a `XlaLazyTensor` but this will require the `object -> pointer` change I mentioned above.
> 
> I am leaning toward option2 since it gives backend more flexibility. Option1 limited the places where backend can implement their custom logic and in the long term when more backends adapts LazyTensor it might be too restricted. @wconstab any thoughts on this?

I was thinking option 2 as well, but that is beyond the scope of this PR. Let's land this one as is, and I can work on Option 2 earlier next half.

**Comment by JackCaoG** [comment]
@desertfire Sounds good, thanks a lot!

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33171590).

**Comment by alanwaketan** [comment]
Thanks Bin and Jack!

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33171590).

**Pull request closed without merging**
