### PR TITLE
Migrate jobs from windows.4xlarge windows.4xlarge.nonephemeral instances

### PR DESCRIPTION
**Pull request by jeanschmidt**
This is reopening of the PR [100091](https://github.com/pytorch/pytorch/pull/100091)

# About this PR

Due to increased pressure over our windows runners, and the elevated cost of instantiating and bringing down those instances, we want to migrate instances from ephemeral to not ephemeral.

Possible impacts are related to breakages in or misbehaves on CI jobs that puts the runners in a bad state. Other possible impacts are related to exhaustion of resources, especially disk space, but memory might be a contender, as CI trash piles up on those instances.

As a somewhat middle of the road approach to this, currently nonephemeral instances are stochastically rotated as older instances get higher priority to be terminated when demand is lower.

Instances definition can be found here: https://github.com/pytorch/test-infra/pull/4072

This is a first in a multi-step approach where we will migrate away from all ephemeral windows instances and follow the lead of the `windows.g5.4xlarge.nvidia.gpu` in order to help reduce queue times for those instances. The phased approach follows:

* migrate `windows.4xlarge` to `windows.4xlarge.nonephemeral` instances under `pytorch/pytorch`
* migrate `windows.8xlarge.nvidia.gpu` to `windows.8xlarge.nvidia.gpu.nonephemeral` instances under `pytorch/pytorch`
* submit PRs to all repositories under `pytorch/` organization to migrate `windows.4xlarge` to `windows.4xlarge.nonephemeral`
* submit PRs to all repositories under `pytorch/` organization to migrate `windows.8xlarge.nvidia.gpu` to `windows.8xlarge.nvidia.gpu.nonephemeral`
* terminate the existence of `windows.4xlarge` and `windows.8xlarge.nvidia.gpu`
* evaluate and start the work related to the adoption of `windows.g5.4xlarge.nvidia.gpu` to replace `windows.8xlarge.nvidia.gpu.nonephemeral` in other repositories and use cases (proposed by @huydhn)

The reasoning for this phased approach is to reduce the scope of possible contenders to investigate in case of misbehave of particular CI jobs.

# Copilot Summary

### <samp>🤖 Generated by Copilot at 579d87a</samp>

This pull request migrates some windows workflows to use `nonephemeral` runners for better performance and reliability. It also adds support for new Python and CUDA versions for some binary builds. It affects the following files: `.github/templates/windows_binary_build_workflow.yml.j2`, `.github/workflows/generated-windows-binary-*.yml`, `.github/workflows/pull.yml`, `.github/actionlint.yaml`, `.github/workflows/_win-build.yml`, `.github/workflows/periodic.yml`, and `.github/workflows/trunk.yml`.

# Copilot Poem

### <samp>🤖 Generated by Copilot at 579d87a</samp>

> _We're breaking free from the ephemeral chains_
> _We're running on the nonephemeral lanes_
> _We're building faster, testing stronger, supporting newer_
> _We're the non-ephemeral runners of fire_

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

issue: #101209

### CODE REVIEW

**Comment by jeanschmidt** [comment]
I am ignoring the periodic failures, as they seem unrelated.

**Review by huydhn — APPROVED** [review]
LGTM! I think you might want to rebase and merge this after Eli's change https://github.com/pytorch/pytorch/pull/100478 as Windows jobs are moved around.

**Review by malfet — APPROVED** [review]

**Review by atalman — APPROVED** [review]

**Comment by jeanschmidt** [comment]
> #100478

exactly what I was trying to avoid by merging as quick as possible 

I am opting to merge without waiting for signals, they take a full day and I've gone for a week trying to get all signals green before merging. As the windows runners and those files have a very fast iteration rate, it is very difficult to get all green signals and not have a merge conflict.

**Pull request closed without merging**
