### PR TITLE
Remove deprecated _convolution overload

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #71019

This PR removes an old deprecated `_convolution` overload that didn't have the `allow_tf32` flag. Removing it shouldn't break mobile models because they handle it internally:
https://github.com/pytorch/pytorch/blob/bc026c05775a6504e48363941285ae381e52b931/torch/csrc/jit/mobile/function.cpp#L169-L180

Differential Revision: [D33482744](https://our.internmc.facebook.com/intern/diff/D33482744)

### CODE REVIEW

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33482744).

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33482744).

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33482744).

**Review by albanD — APPROVED** [review]
SGTM

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33482744).

**Review by albanD — APPROVED** [review]
Still good

**Comment by albanD** [comment]
Not stale! This is happening!

**Comment by albanD** [comment]
@jbschlosser would you have a minute to re-import this to see if it is feasible? Or this is too low priority and we let this be closed?

**Comment by jbschlosser** [comment]
@albanD sure lemme try it out :) it's low prio compared to other stuff I'm working on, so if it takes too much time, we may have to abandon it for now

**Pull request closed without merging**
