### PR TITLE
[AOTI] Use torchgen to generate C shim functions

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #120714
* __->__ #120513

Summary: The current C shim layer manually implements a C interface for a handful of ops. Obviously that's not scalable if we want to extend it to cover all aten ops. This new torchgen script automatically generates C shim interfaces for CPU and CUDA backends. The interface follows the same parameter passing rules as the current C shim layer, such as

* Use plain C data types to pass parameters
* Use AtenTensorHandle to pass at::Tensor
* Use pointer type to pass optional parameter
* Use pointer+length to pass list
* Use device_type+device_index to pass device
* When a parameter is a pointer of pointer, e.g. AtenTensorHandle**, the script generates either a list of optional values or an optional list of values

https://gist.github.com/desertfire/83701532b126c6d34dae6ba68a1b074a is an example of the generated torch/csrc/inductor/aoti_torch/generated/c_shim_cuda.cpp file. The current version doesn't generate C shim wrappers for all aten ops, and probably generates more wrappers than needed on the other hand, but it should serve as a good basis.

This PR by itself won't change AOTI codegen and thus won't introduce any FC breakage. The actual wrapper codegen changes will come in another PR with some version control flag to avoid FC breakage.

Differential Revision: [D54258087](https://our.internmc.facebook.com/intern/diff/D54258087)

### CODE REVIEW

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54258087).

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54258087).

**Comment by desertfire** [comment]
Still need to sort out the internal build issue, but ready for review otherwise.

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54258087).

**Review by jansel — APPROVED** [review]
Seems fine, though my only concern would be code size for the pytorch package.

We likely only need shims for functions we don't have lowerings/decomps for.  Maybe we could filter down the list somehow.

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54258087).

**Comment by desertfire** [comment]
> Seems fine, though my only concern would be code size for the pytorch package.
> 
> We likely only need shims for functions we don't have lowerings/decomps for. Maybe we could filter down the list somehow.

I added a filter to filter out ops with `pointwise` in its tags, which cuts ops in c_shim_cuda.cpp from 1577 to 1294. A more systematic way is to add special tags in `native_functions.yaml` to mark Inductor-lowered ops, which I can do in a later PR.

**Comment by ezyang** [comment]
Late to the party. When I modify an operator to add a new optional argument, how does this code generator know to keep the old API function around, and create a new function with the optional argument?

**Comment by desertfire** [comment]
> Late to the party. When I modify an operator to add a new optional argument, how does this code generator know to keep the old API function around, and create a new function with the optional argument?

We will need to manually keep the old API in shim_common.cpp in that case. Is there a recommended way to detect an optional argument addition to native_functions.yaml? I can add an error msg with instructions on how to do that.

**Comment by ezyang** [comment]
native_functions.yaml doesn't have any notion of BC. When I add a new optional kwarg, I just add a new optional kwarg, I have no way of seeing that in the past it used to be there was no optional kwarg.

To be honest, my preference would have been that we NOT add tons and tons of autogenerated functions to the ABI. Now we have to keep them around permanently, because if we remove *any* function it's ABI breaking. And to add insult to injury, you've comprehensively generated functions for everything in our API, which means that I technically can't even remove a single function, even if you're pretty sure that it's no longer used, because it's still the ABI.

**Pull request closed without merging**
