### PR TITLE
cmake: allow to build pytorch as a CMake subproject

### PR DESCRIPTION
**Pull request by anthonyalayo**
This is a re-attempt of fixing https://github.com/pytorch/pytorch/issues/53980, first submitted in https://github.com/pytorch/pytorch/pull/54978.

Quoting @SpaceIm 
```
Fixes https://github.com/pytorch/pytorch/issues/53980

Maybe it would be nice to find why some files are generated in CMAKE_BINARY_DIR instead of CMAKE_CURRENT_BINARY_DIR or Torch_BINARY_DIR or PROJECT_BINARY_DIR, but there is a lot of indirection in the logic of pytorch build files, so I was not able to find where it comes from.
```

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Comment by anthonyalayo** [comment]
@malfet I wanted to revive this PR since it would be great to have, originally here:
https://github.com/pytorch/pytorch/pull/54978

Any idea why these CI checks are failing? I'm looking at them, but nothing looks related?

I tested this in a project I work on and it looked good there.

**Comment by anthonyalayo** [comment]
cc @albanD who helped me get my last PyTorch contribution in

**Comment by malfet** [comment]
It would be nice to add some trivial unittest (that just runs cmake on a project that lists pytorch as a subproject)

**Comment by malfet** [comment]
> Any idea why these CI checks are failing? I'm looking at them, but nothing looks related?

@anthonyalayo your branch is 3000 commits behind `main`, please rebase (if mergebot fails to do it for you)

**Comment by anthonyalayo** [comment]
@malfet I started writing the test, but it takes a pretty long time to fetch and build since it pulls in PyTorch itself. Is that alright to have as something that runs on CI?

**Comment by anthonyalayo** [comment]
@malfet any thoughts on that last comment?

**Review by malfet — APPROVED** [review]
Changes to the 3 `CMakeLists.txt` and `Codegen.cmake` looks fine to me

**Comment by malfet** [comment]
@anthonyalayo thank you for the updates, looks good to me if trunk and binary builds are passing. 
As for the test, it can be done as followup PR, but yes, something similar to https://github.com/pytorch/pytorch/pull/41145 would do

**Comment by anthonyalayo** [comment]
Looks like everything test clean, good to merge?

**Comment by anthonyalayo** [comment]
@malfet can we start the merge? thanks!

**Comment by anthonyalayo** [comment]
@malfet any thoughts?

**Pull request closed without merging**
