### PR TITLE
Remove breakpad from docker image

### PR DESCRIPTION
**Pull request by driazati**
As of #63186 we're doing this properly via a third_party cmake build, so we don't need it here anymore.

This also re-orders openssl installation to be before sccache since sccache was timing out

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Review by walterddr — APPROVED** [review]

**Comment by walterddr** [comment]
ok apparently the openssl build issue on bionic is not unique to any PR

it failed on this one: https://app.circleci.com/pipelines/github/pytorch/pytorch/366869/workflows/4723704a-e0e8-4c63-a531-570eb117c7da/jobs/15479316 
and it also failed on mine #63580: https://app.circleci.com/pipelines/github/pytorch/pytorch/366994/workflows/e2345675-c73e-4b04-ac85-2f1309be5ea7/jobs/15484175

**Comment by walterddr** [comment]
ok almost 100% sure it is due to sccache server not responding for some reason. it got stuck at compilation for 20 minutes for my rerun with ssh.

**Comment by seemethere** [comment]
> ok almost 100% sure it is due to sccache server not responding for some reason. it got stuck at compilation for 20 minutes for my rerun with ssh.

Another thing that may make sense is the fact that the docker build doesn't have access to credentials for AWS for our sccache bucket in the first place.

I'm not entirely sure why we're building openssl with sccache anyways but it makes sense why it can't access the S3 bucket since it doesn't have credentials

**Comment by driazati** [comment]
> > ok almost 100% sure it is due to sccache server not responding for some reason. it got stuck at compilation for 20 minutes for my rerun with ssh.
> 
> Another thing that may make sense is the fact that the docker build doesn't have access to credentials for AWS for our sccache bucket in the first place.
> 
> I'm not entirely sure why we're building openssl with sccache anyways but it makes sense why it can't access the S3 bucket since it doesn't have credentials

seeing as we don’t build the docker images too often should we just disable SCCACHE entirely on them?

**Comment by seemethere** [comment]
> > > ok almost 100% sure it is due to sccache server not responding for some reason. it got stuck at compilation for 20 minutes for my rerun with ssh.
> > 
> > 
> > Another thing that may make sense is the fact that the docker build doesn't have access to credentials for AWS for our sccache bucket in the first place.
> > I'm not entirely sure why we're building openssl with sccache anyways but it makes sense why it can't access the S3 bucket since it doesn't have credentials
> 
> seeing as we don’t build the docker images too often should we just disable SCCACHE entirely on them?

I'd agree with that

**Comment by walterddr** [comment]
yup. reordering it to install before sccache worked. https://app.circleci.com/pipelines/github/pytorch/pytorch/367336/workflows/fb2b78e0-b0d0-4983-a0bd-e2a6f232bcc8/jobs/15498940.

**Comment by walterddr** [comment]
hmm i wasn't able merge my PR even thought I think it has the fix for openssl compilation. could you replicate my last commit on #63580 and merge it with your PR here?

**Comment by walterddr** [comment]
sorry this commit: https://github.com/pytorch/pytorch/pull/63580/commits/131e7ba780a5907f83727fe3ceff4d6b0c4e8776

**Review by walterddr — APPROVED** [review]

**Pull request closed without merging**
