### PR TITLE
Support RowWiseSparseAdam on GPU (#34341)

### PR DESCRIPTION
**Pull request by yanxiexy**
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/34341

Implement RowWiseSparseAdam on CUDA

Differential Revision: D20650225

### CODE REVIEW

**Comment by xw285cornell** [comment]
@iotamudelta this diff doesn't even touch batchPermutation but it failed on that one. Could you take a look? We can't disable test for this, as we'll have to comment out the entire code. 

23:25:23 [ RUN      ] BatchPermutationTest.CHECKCPUGPUEqualGenericDimension
23:25:23 WARNING: Logging before InitGoogleLogging() is written to STDERR
23:25:23 W0325 23:25:23.946934    88 init.h:137] Caffe2 GlobalInit should be run before any other API calls.
23:25:41 unknown file: Failure
23:25:41 C++ exception with description "No device code available for function: _ZN6caffe212_GLOBAL__N_122BatchPermutationKernelILb0EEEviiPKfPKiPf, for agent: gfx900" thrown in the test body.
23:25:41 [  FAILED  ] BatchPermutationTest.CHECKCPUGPUEqualGenericDimension (17287 ms)

**Comment by xw285cornell** [comment]
It seems somehow the device code just disappeared.

**Comment by iotamudelta** [comment]
@xw285cornell I looked at the original PR of this. Missing device code may happen if the kernel compilation itself crashes (rare, assuming all other bases are checked). This should be crosschecked with a newer ROCm.

**Comment by xw285cornell** [comment]
@iotamudelta but if the kernel compilation crashed -- shouldn't the build fail? Why build goes through and run fails?

**Comment by xw285cornell** [comment]
@iotamudelta could you help take a look? I can't find any crashing msg on the build, but it's complaining no device code. We're on 3.1 right now, so that's a more serious problem

**Pull request closed without merging**
