### PR TITLE
Update mkldnn-bridge to fix MKLDNN grouped conv issue

### PR DESCRIPTION
**Pull request by gujinghui**
1. Fix grouped conv issue in #21597
2. Fix build error in https://github.com/pytorch/pytorch/commit/731670f40a396b36304d8cdf0a47213042e10110

### CODE REVIEW

**Comment by gujinghui** [comment]
@jianhui-li
@uyongw
@jgong5

**Comment by gujinghui** [comment]
@bddppq
pls help review.

Thanks.

**Comment by VitalyFedyunin** [comment]
Please add pytorch tests covering #21597

**Review by ezyang — APPROVED** [review]
This is fine to unblock but really ideally we'd also get tests too. Those can come in a follow up.

**Review by bddppq — APPROVED** [review]
@gujinghui @XiaobingSuper Please add a test case in a follow up pull request to cover the specific issue fixed in this ideep update.

**Comment by yinghai** [comment]
Yeah, it's important that we add unit tests for this.

**Comment by gujinghui** [comment]
Sure. Will add the test case soon.

**Pull request closed without merging**
