### PR TITLE
[inductor] Remove the batch fusion passes from being a default

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135922
* #135819

Ads team do a search internally to figure out which fusion passes to use.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by eellison — APPROVED** [review]
cc @yanboliang

**Comment by yanboliang** [comment]
I think this won't impact OSS users, but we should check with internal users if this would break their models. cc @jackiexu1992 @mengluy0125

**Comment by anijain2305** [comment]
Menglyu mentioned that it does not. They set it to empty internally, and the do a search for bear combination.

**Review by yanboliang — APPROVED** [review]

**Comment by laithsakka** [comment]
reduced instruction counts of the following:
{
  "add_loop_inductor": -14.414483048948,
  "update_hint_regression": -6.227513177813
}

**Pull request closed without merging**
