### PR TITLE
Always run all the grep-based quick-checks steps

### PR DESCRIPTION
**Pull request by samestep**
This PR adds [`if: always()`](https://stackoverflow.com/a/58859404) to all the steps in our "Lint / quick-checks" job that don't depend on any preceding steps. *Technically* means that the title of this PR isn't entirely correct, since the "Ensure correct trailing newlines" step depends on the "Setup Python" step and thus we don't `always()` run it even though it's `grep`-based.

**Test plan:**

On `master`, it looks like the only failing part of quick-checks is the trailing whitespace check:

- https://github.com/pytorch/pytorch/runs/2411377448

However, the CI on this PR shows that the unqualified type ignore check is also failing:

- https://github.com/pytorch/pytorch/runs/2411485849

### CODE REVIEW

**Review by walterddr — APPROVED** [review]

**Comment by walterddr** [comment]
bravo. explosed some more quick check errors. plz fix them in the same PR?

**Comment by samestep** [comment]
> plz fix them in the same PR?

@walterddr I'm not fixing them in this PR because they're already being fixed by #56692, which is landing right now.

**Comment by walterddr** [comment]
> > plz fix them in the same PR?
> 
> @walterddr I'm not fixing them in this PR because they're already being fixed by #56692, which is landing right now.

sounds good!

**Comment by samestep** [comment]
> maybe rebase after #56692 landed to retrigger quick check ?

I'm not sure what you mean; could you clarify? I'm landing this right now since it doesn't conflict with #56692.

**Review by janeyx99 — APPROVED** [review]

**Comment by walterddr** [comment]
> > maybe rebase after #56692 landed to retrigger quick check ?
> 
> I'm not sure what you mean; could you clarify? I'm landing this right now since it doesn't conflict with #56692.

But if you land this now. Wouldn't it broke linter on master?

**Comment by samestep** [comment]
> But if you land this now. Wouldn't it broke linter on master?

No, why would it?

**Pull request closed without merging**
