### PR TITLE
[ROCm] enable fft tests

### PR DESCRIPTION
**Pull request by micmelesse**
This PR enable some failing unit tests for fft in pytorch on ROCM.

The reason these tests were failing was due to hipfft clobbering inputs causing a mismatch in tests that were checking that applying ffts and their reverse would get you back to the input.

We solve this by cloning the input using an existing flag on the ROCM platform.

There PR doesnot enable all fft tests. There are other issues that need to be resolved before that can happen.

### CODE REVIEW

**Comment by micmelesse** [comment]
@jithunnair-amd here is the PR

**Review by jithunnair-amd — APPROVED** [review]
LGTM

**Review by jeffdaily — APPROVED** [review]
LGTM

**Comment by jeffdaily** [comment]
CI looks clean, as well.

**Comment by micmelesse** [comment]
@seemethere Any comments?

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
