### PR TITLE
Introduce core_aten_decompositions

### PR DESCRIPTION
**Pull request by SherlockNoMad**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #93131

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
Leaving out `vector_norm` and `mean_std` looks somewhat arbitrary, is it because decomps call into prims?

**Comment by SherlockNoMad** [comment]
> Leaving out `vector_norm` and `mean_std` looks somewhat arbitrary, is it because decomps call into prims?

Yes, they directly call into prim's reduction op. 
To include them in the core_aten_decomp, I will need to first rewrite them into decomps via aten reduction, and then to prims. What do you think? 

BTW, Inductor lowering actually supports both aten.sum and prims.sum, so inductor actually doesn't need to further decomp aten.sum.

**Pull request closed without merging**
