### PR TITLE
.github: Add render_test_results job

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#57472 .github: Add render_test_results job**
* #57327 tools: Add render_junit script

This render should put us with some feature parity to the CircleCI web UI renders for j(x)unit test reports, should make it so you don't have to look through a long list of logs to see what tests failed for which job

Render should look somewhat similar to 
image

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

Differential Revision: [D28154513](https://our.internmc.facebook.com/intern/diff/D28154513)

### CODE REVIEW

**Review by samestep — APPROVED** [review]
Should there be a `setup-python` step in the new job?

**Comment by seemethere** [comment]
> Should there be a `setup-python` step in the new job?

There shouldn't need to be, python3 is installed by default iirc

**Comment by samestep** [comment]
> There shouldn't need to be, python3 is installed by default iirc

Seems like `setup-python` is still recommended regardless: https://github.com/actions/setup-python/tree/v2.2.2#using-python-without-setup-python

**Comment by seemethere** [comment]
> > There shouldn't need to be, python3 is installed by default iirc
> 
> Seems like `setup-python` is still recommended regardless: [https://github.com/actions/setup-python/tree/v2.2.2#using-python-without-setup-python](https://github.com/actions/setup-python/tree/v2.2.2?rgh-link-date=2021-05-03T19%3A04%3A45Z#using-python-without-setup-python)

Added `setup-python`

**Pull request closed without merging**
