### PR TITLE
check cu_seqlens_q is contiguous (#122595)

### LINKED ISSUE #122595: In PyTorch v2.1.2, within fmha_api.cpp, the mha_fwd() function redundantly checks cu_seqlens_k
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/blob/v2.1.2/aten/src/ATen/native/transformers/cuda/flash_attn/fmha_api.cpp#L247-L248  
cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

### Versions

torch version == v2.1.2

### PR DESCRIPTION
**Pull request by 1274085042**
Fixes  #122595
cc @drisspg

### CODE REVIEW

**Review by drisspg — APPROVED** [review]
thank you! 

@pytorchbot merge

**Comment by 1274085042** [comment]
@drisspg    
This PR seems to have encountered some CI problems

**Pull request closed without merging**
