### PR TITLE
[inductor] Add ABI shim function for torch.scatter

### PR DESCRIPTION
**Pull request by aakhundov**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #114027
* #114024

Summary: Scatter fallback calls `at::scatter` in the C++ wrapper codegen. This doesn't work in the ABI compatibility mode, as the latter requires a shim function. One is added in this PR.

Test Plan:

```
$ python test/inductor/test_aot_inductor.py -k test_scatter_fallback
s...
----------------------------------------------------------------------
Ran 4 tests in 52.713s

OK (skipped=1)
```

Reviewers:

Subscribers:

Tasks:

Tags:

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler

### CODE REVIEW

**Review by chenyang78 — APPROVED** [review]
The PR LGTM. 

I am having a question to @SherlockNoMad: We are handling scatter different from other fallback kernels. Particularly, we have the following class hierarchies. I am wondering if we could also use ProxyExecutor to cover scatter fallback? Thanks.

```
class FallbackKernel(ExternKernelAlloc)
class ExternKernelAlloc(ExternKernel):
class ScatterFallback(ExternKernel)
```

**Comment by aakhundov** [comment]
FWIW, I'd prefer having an ABI shim function for the cases we can cover and rely on `ProxyExecutor` for the uncovered cases. As I understand, `ProxyExecutor` comes with slight performance overhead (e.g., for ser/des and additional dispatch logic)?

**Review by desertfire — APPROVED** [review]

**Comment by chenyang78** [comment]
> FWIW, I'd prefer having an ABI shim function for the cases we can cover and rely on `ProxyExecutor` for the uncovered cases. As I understand, `ProxyExecutor` comes with slight performance overhead (e.g., for ser/des and additional dispatch logic)?

There were some discussions about this last Friday. I think it would mostly impact CPU backend. Not sure about how it would affect CUDA backend performance. It might be small. I think @SherlockNoMad volunteered to do some perf experiments.

**Comment by aakhundov** [comment]
> I think it would mostly impact CPU backend. Not sure about how it would affect CUDA backend performance.

In some models, we can have very small kernels and / or CUDA device sync, so non-trivial CPU overhead can become visible.

**Pull request closed without merging**
