### PR TITLE
[submodule] Pin fmtlib/fmt to 10.1.0

### PR DESCRIPTION
**Pull request by cyyever**
fmt10.1.0 fixes a bug of format_string_checker initialisation order which is important to our improved clang-tidy checks #103058. This PR upgrades third_party fmt to 10.1.0, in the meanwhile, kineto is also upgraded to avoid fmt errors.

cc @Skylion007 @albanD

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Why the kineto upgradE?

**Comment by Skylion007** [comment]
> Why the kineto upgradE?

Build errors with fmtlib

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
FYI, looks like 10.1.0 can cause GCC build errors on C++20: https://github.com/fmtlib/fmt/issues/3587 Not sure if we are affected though.

**Pull request closed without merging**
