### PR TITLE
Fix layernorm cpu precision issues

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
#108072

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108089

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by mingfeima — APPROVED** [review]

**Comment by mingfeima** [comment]
@mikaylagawarecki nice work !

**Comment by XiaobingSuper** [comment]
@mikaylagawarecki, could you help cherry-pick this PR for 2.1 branch? see https://github.com/pytorch/pytorch/issues/108055. Thanks!

**Review by albanD — APPROVED** [review]
SGTM
Could you add a test to make sure we preserve this behavior properly going forward please?

**Comment by mikaylagawarecki** [comment]
@XiaobingSuper I don't think this meets the criteria as a critical fix, so unfortunately we can't cherry pick this

**Pull request closed without merging**
