### PR TITLE
[Test only] CPU only build for Windows

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by peterjc123** [comment]
@SsnL There's an test error of the `fft` functions on the dev machine. Do you know the possible reason?
```pytb
======================================================================
FAIL: test_fft_ifft_rfft_irfft (test_torch.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\conda-bld\pytorch_1522931932547\test_tmp\test\test_torch.py", line 3408, in test_fft_ifft_rfft_irfft
    self._test_fft_ifft_rfft_irfft(self, build_fn=randn_double)
  File "C:\ProgramData\Miniconda3\conda-bld\pytorch_1522931932547\test_tmp\test\test_torch.py", line 3398, in _test_fft_ifft_rfft_irfft
    _test_complex((100, 3, 100, 2), 1, lambda x: x[:, 1].transpose(0, 1))
  File "C:\ProgramData\Miniconda3\conda-bld\pytorch_1522931932547\test_tmp\test\test_torch.py", line 3333, in _test_complex
    self.assertEqual(x, rec, 1e-8, 'fft and ifft')
  File "C:\ProgramData\Miniconda3\conda-bld\pytorch_1522931932547\test_tmp\test\common.py", line 253, in assertEqual
    assertTensorsEqual(x, y)
  File "C:\ProgramData\Miniconda3\conda-bld\pytorch_1522931932547\test_tmp\test\common.py", line 245, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError:
 4.3368
[torch.DoubleTensor of size ()]
 not less than or equal to 1e-08 : fft and ifft

----------------------------------------------------------------------
Ran 2181 tests in 73.029s

```

**Comment by peterjc123** [comment]
@SsnL Well, it's solved by using @yf225 's zip file. Sorry for bothering.

**Comment by SsnL** [comment]
@peterjc123 Was it an older MKL version? We saw some MKL version failing the test, probably due to bugs in MKL.

**Comment by peterjc123** [comment]
@SsnL Yes, you are right. But how could I get the MKL files you are currently using? It seems that it raises a Access Denied error when I tried to download it through the s3 link.

**Comment by SsnL** [comment]
@yf225 has more knowledge on s3 file access :)

**Pull request closed without merging**
