### PR TITLE
Fix test_dispatch.py when running with TORCH_SHOW_CPP_STACKTRACES=1

### PR DESCRIPTION
**Pull request by zasdfgbnm**
`test_dispatch.py` has many asserts about the error message. When running with `TORCH_SHOW_CPP_STACKTRACES=1`, the error message is different from when `TORCH_SHOW_CPP_STACKTRACES=0`, which makes many tests in `test_dispatch.py` fail. This PR fixes these failures when running with `TORCH_SHOW_CPP_STACKTRACES=1`.

### CODE REVIEW

**Comment by mruberry** [comment]
@ezyang Should probably review this change, he's more familiar with test_dispatch.py.

**Comment by ezyang** [comment]
This is an imperfect fix, because the wrong thing will happen if you simultaneously show cpp stacktraces AND accept output, but it may be good enough. Thinking about it.

**Comment by ezyang** [comment]
I don't want to force you to spend too much time on this patch, but I think there is an alternate version which is easy to implement and shorter.

Instead of fixing up assertEquals (which is the source of the bug I mentioned above), handle fixups on the "actual" parameter upon *entry* to expectEquals.  I actually implemented a variant of this in ghstack's version of expect tests though I never backported it back to PyTorch: https://github.com/ezyang/ghstack/blob/master/ghstack/expecttest.py#L189

You'll want something different (since there isn't a fixed pattern to test for in your case), but roughly this idea should apply.

LMK if this is too much of a bother.

**Comment by zasdfgbnm** [comment]
@ezyang I think your suggestion is great. It's short and should work with ACCEPT. I have updated this PR with this implementation.

**Review by ezyang — APPROVED** [review]
Unconditional application is a little hacky but I think it's unlikely to cause problems, and will be easy to debug if it does.

**Pull request closed without merging**
