### PR TITLE
[pt2][quant] Clean up QAT get conv-bn-relu nodes

### PR DESCRIPTION
**Pull request by andrewor14**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #111515

Summary: Reduces duplicate code to map original matched nodes
to replacement nodes.

Test Plan:
python test/test_quantization.py TestQuantizePT2EQAT

Reviewers: jerryzh168

Subscribers: jerryzh168, supriyar

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]
thanks! is there plans to extend SubgraphRewriter with the recent support for SubgraphMatcherWithNodeNameMap?

**Comment by andrewor14** [comment]
> thanks! is there plans to extend SubgraphRewriter with the recent support for SubgraphMatcherWithNodeNameMap?

Yes that would simplify the changes in this PR significantly if we have that

**Comment by jerryzh168** [comment]
> > thanks! is there plans to extend SubgraphRewriter with the recent support for SubgraphMatcherWithNodeNameMap?
> 
> Yes that would simplify the changes in this PR significantly if we have that

OK, maybe we can make that a BE task

**Pull request closed without merging**
