### PR TITLE
Revert "Revert "Expandable blocks in allocator (#96995)""

### PR DESCRIPTION
**Pull request by zdevito**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99275

This reverts commit 851e89c8e817f28270e0fc21d74ced9446bea747.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

Differential Revision: [D45034526](https://our.internmc.facebook.com/intern/diff/D45034526)

### CODE REVIEW

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45034526).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45034526).

**Review by eellison — APPROVED** [review]

**Pull request closed without merging**
