### PR TITLE
[c10d] Make gloo backend support Infiniband and GPU-Direct

### PR DESCRIPTION
**Pull request by teng-li**
This will make Gloo to work with Infiniband on the FAIR cluster.

And infiniband will be detected and used if the build includes infiniband support.

### CODE REVIEW

**Comment by teng-li** [comment]
@pieter, we should keep it open until the fix on the gloo side is fixed. This PR is just a gloo user and I don’t think the gloo fix should torch how people use gloo right?

**Comment by pietern** [comment]
I closed it because this depends on the algorithm caching functionality in ProcessGroupGloo, which is going to be nuked very shortly. You mentioned you weren't able to get this to work right? Then we can track the IB support in #8032 and not have both an issue and a PR open for tracking.

**Comment by teng-li** [comment]
@pietern I thought the plan was, you fix the IB support from Gloo repro and we put this PR in?  If you want to nuke the algorithm caching, then go for it.

**Comment by pietern** [comment]
This PR depends on the algorithm caching so it's incompatible with nuking it :-)

The reason for nuking the algorithm caching is that is has degenerate cases where memory usage will explode, as well as the additional tensor copy for every operation. It was a good first step to get things going but with the recent changes to Gloo around the unbound buffers and algorithms that use them, the algorithm caching is no longer needed and we can get rid of the runtime memory risk. Then after we figure out what's up with IB support we can put back the device selection code, and we'll get support for all algorithms automatically.

**Comment by pietern** [comment]
This is no longer mergeable now that #14295 is merged.

Created #14438 to track supporting IB devices.

**Pull request closed without merging**
