### PR TITLE
Try 32 bit PyTorch on Windows

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by ezyang** [comment]
Don't forget to undraft this when you want review

**Comment by peterjc123** [comment]
@ezyang Sure, now that the PRs are merged, let's give it a try.

**Comment by peterjc123** [comment]
Update: Windows CPU build is working under 32-bit Windows with some code modification. CUDA build is not available because it was blocked by 32-bit CUDA support.

**Comment by wanlipeng** [comment]
how can I get libtorch support for 32-bit windows ?

**Comment by peterjc123** [comment]
@wanlipeng Use x86 Python and apply the changes here to the repo.

**Comment by wanlipeng** [comment]
sorry, would you please tell me the details , how to applay the changes , how can I get the 32bit dlls like  the 64bit Libtorch download from pytorch official website, Thank you very much!

**Comment by planckztd** [comment]
You know, Pytorch only offer prebuilt libtorch in x64 . Wish you can give us some instructions on how to compile libtorch support for 32-bit windows.

**Comment by peterjc123** [comment]
@planckztd If you are using 32 bit Windows, then the installation [guide](https://github.com/pytorch/pytorch#from-source) is almost the same, but you'll have to activate the x86 version of the MSVC dev environment.
That is to say, you should make the changes to the code like below.
```bat
:: Original
for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [15^,16^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=%CMAKE_GENERATOR_TOOLSET_VERSION%

:: Changed
for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [15^,16^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x86 -vcvars_ver=%CMAKE_GENERATOR_TOOLSET_VERSION%
```
However, the 32 bit codepath is not tested for a while. I'm not sure it's gonna work or not. Please report back when you have any questions.

**Comment by planckztd** [comment]
I have try follow script in anaconda 64bit with 64bit python prompt,:
`conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
git submodule sync
git submodule update --init --recursive

set CMAKE_GENERATOR=Visual Studio 15 2017
set CMAKE_GENERATOR_TOOLSET_VERSION=14.11
set DISTUTILS_USE_SDK=1

set USE_NINJA=0
set USE_CUDA=0
for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [15^,16^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x86 -vcvars_ver=%CMAKE_GENERATOR_TOOLSET_VERSION%
cd tools
python build_libtorch.py`

After compile done, I test c10.lib and torch.lib by using:
`dumpbin.exe /headers path/to/c10.lib` which show that lib is x64.
I also test it with code in tutorial:
`#include <torch/torch.h>
#include <iostream>
int main() {
  torch::Tensor tensor = torch::rand({2, 3});
  std::cout << tensor << std::endl;
  return 0;
}` 
x64 can run,but win32 get error `module machine type 'x64' conflicts with target machine type 'x86'`

**Comment by peterjc123** [comment]
@planckztd  You'll need Python 32-bit too.

**Comment by peterjc123** [comment]
@planckztd You downgraded your cmake while switching to 32 bit?

**Comment by planckztd** [comment]
yes,I made new environment in anaconda with 32bit python, than anaconda automaticly install the cmake version 3.11.1. Should I upgrade cmake？

**Comment by peterjc123** [comment]
Yes

**Comment by planckztd** [comment]
Thank you! It works! I compiled it successfully in release version. BTW,how to compile it in debug version?

**Comment by peterjc123** [comment]
@planckztd caffe2.dll is already merged into torch.dll. Does directly copying torch.dll to caffe2.dll helps?

**Comment by planckztd** [comment]
no, can not run .exe with these 4 dll(c10.dll,caffe2_detectron_ops.dll,caffe2_module_test_dynamic.dll,torch.dll),which are generated in torch/lib

**Comment by peterjc123** [comment]
Could you please upload the generated libraries?

**Comment by planckztd** [comment]
Sorry, I found I forget to change properties in  Visual Studio 2017 solution explorer，so .exe  file is generated by downloaded prebuild libtorch.  Rebuild that, the .exe runs well. I am so grateful for your help.Thanks. ^_^

**Comment by peterjc123** [comment]
@planckztd If you have time, could you please make a PR to improve the docs for building 32-bit libraries?

**Comment by planckztd** [comment]
ok,I'll try

**Comment by ezyang** [comment]
@planckztd Yes, that would be much appreciated. Even half baked thoughts are fine; we can help copyedit

**Comment by alexandreCameron** [comment]
@planckztd : I'm currenlty trying to build the lattest version pytorch (1.5.0) for a windows machine with python 32bits. Have you tried the install recently ?

Did you have any issue building caffe2 when doing the build ?

Can the build be done on a more recent version of VC++ ?

https://github.com/pytorch/pytorch/issues/38322

**Comment by isyyzhang** [comment]
> Thank you! It works! I compiled it successfully in release version.for DEBUG version, I have found the command from #19302 ,set DEBUG=1. I also test it with code in tutorial as .exe file:
> 
> ```
> #include <torch/torch.h> 
> #include <iostream> 
> int main() {
> torch::Tensor tensor = torch::rand({2, 3}); 
> std::cout << tensor << std::endl; 
> return 0; }
> ```
> 
> I put all compiled .dll files aside .exe, but it complain that can't found caffe2.dll. I see no caffe2.dll generated with other .dll(c10.dll,caffe2_detectron_ops.dll,caffe2_module_test_dynamic.dll,torch.dll), while code in visual studio 2017 can run. How to fix this problem?

Hi~, When I was compiling 32 bit libtorch, there was a CMake Error: Could not create named generator Visual Studio 15 2017, have you ever met this problem?

**Comment by neuxys** [comment]
> 

Now, how to get the 32-bit libtorch library based on Windows CPU?

**Comment by neuxys** [comment]
> Update: Windows CPU build is working under 32-bit Windows with some code modification. CUDA build is not available because it was blocked by 32-bit CUDA support.

Now, how to get the 32-bit libtorch library based on Windows CPU?
I tried many methods without success, although I searched all the submissions and comments about you.

**Comment by UltronAI** [comment]
Hi, @peterjc123 

Is there any update on this issue recently? For some reasones, I need to use Pytorch and LibTorch on windows and compile them into a 32-bit program. I followed your instructions and [a Chinese blog](https://blog.csdn.net/weixin_40448140/article/details/105345593) to build my 32-bit LibTorch but failed. Different from yours, I use VS2019, i.e., `set CMAKE_GENERATOR=Visual Studio 16 2019 & set CMAKE_GENERATOR_TOOLSET_VERSION=14.29`. I have tried to build v1.12.1 which is the latest release version and v1.4.0 but both failed.

For v1.12.1, I cannot do `#include <torch/include.h>` successfully. It will show `_addcarry_u64` is undefined, which is used [here](https://github.com/pytorch/pytorch/blob/399b1eb84b006f7a6e2bdcda7083fd264ac204da/c10/util/safe_numerics.h#L25) and should be defined in the `intrin.h`. It seems that the latest Pytorch cannot support x86/Win32? Or what should I do to fix this error or anything else like this？

For v1.4.0, I cannot finish the compilation because `C:\Users\fengg\pytorch\caffe2/core/context_base.h(92,33): error C2338: CopyToCPU requires fundamental types`. It may be caused by some differences between VS2017 and VS2019 but VS2017 has been deprecated by the Microsoft.

Also, I wonder if I can use CUDA on a 32-bit windows program for now?

Thanks！

**Comment by UltronAI** [comment]
> Hi, @peterjc123
> 
> Is there any update on this issue recently? For some reasons, I need to use Pytorch and LibTorch on windows and compile them into a 32-bit program. I followed your instructions and [a Chinese blog](https://blog.csdn.net/weixin_40448140/article/details/105345593) to build my 32-bit LibTorch but failed. Different from yours, I use VS2019, i.e., `set CMAKE_GENERATOR=Visual Studio 16 2019 & set CMAKE_GENERATOR_TOOLSET_VERSION=14.29`. I have tried to build v1.12.1 which is the latest release version and v1.4.0 but both failed.
> 
> For v1.12.1, I cannot do `#include <torch/include.h>` successfully. It will show `_addcarry_u64` is undefined, which is used [here](https://github.com/pytorch/pytorch/blob/399b1eb84b006f7a6e2bdcda7083fd264ac204da/c10/util/safe_numerics.h#L25) and should be defined in the `intrin.h`. It seems that the latest Pytorch cannot support x86/Win32? Or what should I do to fix this error or anything else like this？
> 
> For v1.4.0, I cannot finish the compilation because `C:\Users\fengg\pytorch\caffe2/core/context_base.h(92,33): error C2338: CopyToCPU requires fundamental types`. It may be caused by some differences between VS2017 and VS2019 but VS2017 has been deprecated by the Microsoft.
> 
> Also, I wonder if I can use CUDA on a 32-bit windows program for now?
> 
> Thanks！

An update:

I follow your modifications in [Fix is_fundamental template for MSVC](https://github.com/pytorch/pytorch/pull/30959) and the compilation with v1.4.0 is done without any errors. But unfortunately, it doesn't work well. Also I cannot do `#include <torch/script.h>` successfully. There occur many errors `unresolved external symbol`, as the following screen shot shows.

image

Additionally, I use `dumpbin.exe /headers` to check my `torch.lib` and `c10.lib`. They are both shown to be x64. It seems that I failed to compile a 32-bit libtorch.

image

Any updates or suggestions on this issue will be appreciated. Thanks!

Feng

**Comment by neuxys** [comment]
> > Thank you! It works! I compiled it successfully in release version.for DEBUG version, I have found the command from #19302 ,set DEBUG=1. I also test it with code in tutorial as .exe file:
> > ```
> > #include <torch/torch.h> 
> > #include <iostream> 
> > int main() {
> > torch::Tensor tensor = torch::rand({2, 3}); 
> > std::cout << tensor << std::endl; 
> > return 0; }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I put all compiled .dll files aside .exe, but it complain that can't found caffe2.dll. I see no caffe2.dll generated with other .dll(c10.dll,caffe2_detectron_ops.dll,caffe2_module_test_dynamic.dll,torch.dll), while code in visual studio 2017 can run. How to fix this problem?
> 
> Hi~, When I was compiling 32 bit libtorch, there was a CMake Error: Could not create named generator Visual Studio 15 2017, have you ever met this problem?

Don't try 32 bit library on windows again. I use onnx runtime to run my model instead. It supports almost all platforms.

**Comment by neuxys** [comment]
Don't try 32 bit library on windows again. I use onnx runtime to run my
model instead. It supports almost all platforms.

Feng Gao ***@***.***> 于2022年8月30日周二 11:12写道：

**Pull request closed without merging**
