### PR TITLE
[Checkpoint] rename apply_ac_wrapper

### PR DESCRIPTION
**Pull request by rohan-varma**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #85459
* __->__ #85449
* #85448

Per title

Differential Revision: [D39714855](https://our.internmc.facebook.com/intern/diff/D39714855/)

### CODE REVIEW

**Review by awgu — COMMENTED** [review]
I am not sure if  @zhaojuanmao had a chance to comment on the new name.

I think `apply_activation_checkpointing` might be better? `apply_activation_checkpoint` sounds like it adds a single checkpoint. Let me know what you think.

**Comment by rohan-varma** [comment]
I'm fine with either apply_activation_checkpoint or apply_activation_checkpointing

**Comment by awgu** [comment]
> I'm fine with either apply_activation_checkpoint or apply_activation_checkpointing

Let us go with `apply_activation_checkpointing` then 😄

**Review by awgu — APPROVED** [review]

**Comment by rohan-varma** [comment]
CI failure is unrelated, landing: https://app.circleci.com/pipelines/github/pytorch/pytorch/569500/workflows/46180354-28e2-4276-9ef6-7da84ffe2f79/jobs/17127524

**Pull request closed without merging**
