### PR TITLE
[JIT] Exclude file:line from graphs used for fuser kernel cache

### PR DESCRIPTION
**Pull request by jamesr66a**
cc @ezyang this is meant to fix the fuser failures on master

### CODE REVIEW

**Review by suo — APPROVED** [review]

**Comment by ezyang** [comment]
Fix doesn't seem sufficient; this test which also failed at the same time on master is still failing:

```
Jun 02 00:17:55 ======================================================================
Jun 02 00:17:55 ERROR: test_data_parallel_rnn (__main__.TestNN)
Jun 02 00:17:55 ----------------------------------------------------------------------
Jun 02 00:17:55 Traceback (most recent call last):
Jun 02 00:17:55   File "/var/lib/jenkins/workspace/test/common_utils.py", line 149, in wrapper
Jun 02 00:17:55     fn(*args, **kwargs)
Jun 02 00:17:55   File "test_nn.py", line 3872, in test_data_parallel_rnn
Jun 02 00:17:55     model = Model().to(0)
Jun 02 00:17:55   File "test_nn.py", line 3856, in __init__
Jun 02 00:17:55     super().__init__()
Jun 02 00:17:55 TypeError: super() takes at least 1 argument (0 given)
Jun 02 00:17:55 
```

**Comment by jamesr66a** [comment]
@ezyang that looks unrelated to my prior change, since it doesn't involve the JIT at all

**Comment by jamesr66a** [comment]
@mrshenli it looks like https://github.com/pytorch/pytorch/pull/21197 introduced the breakage that @ezyang pointed out above

**Comment by mrshenli** [comment]
@jamesr66a @ezyang thanks for the catch. I am working on it.

**Pull request closed without merging**
