### PR TITLE
[FSDP] Extend ignored modules test to not pass to root

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #79584 [FSDP] Default to not checking exec order
* **#79557 [FSDP] Extend ignored modules test to not pass to root**
* #79533 [FSDP] Fix exec order validation for diff ignored modules across ranks

Fixes https://github.com/pytorch/pytorch/issues/77141#issuecomment-1155597687.

Differential Revision: [D37161467](https://our.internmc.facebook.com/intern/diff/D37161467)

### CODE REVIEW

**Review by zhaojuanmao — APPROVED** [review]

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37161467).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37161467).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37161467).

**Review by rohan-varma — APPROVED** [review]
LGTM, although seems like there is a lint issue

**Comment by awgu** [comment]
The lint issue was due to other diff in the stack, and I have rebased to correct the issue. This should be good for landing.

**Pull request closed without merging**
