### PR TITLE
fix python version error

### PR DESCRIPTION
**Pull request by puririshi98**
if python3 is the one running the tests but there exists a "python" installed as python2.7 the test will fail with a syntax issue

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Thanks for the fix.
Changing the command to always use `python3` should work as well and be simpler no?

**Comment by puririshi98** [comment]
> Thanks for the fix. Changing the command to always use `python3` should work as well and be simpler no?

i thought that my more complex version would handle the case that they do not have a python3 alias for python 3 and only "python" which refers to python 3.

**Comment by albanD** [comment]
> python3 alias for python 3 and only "python" which refers to python 3.

Do you know of any OS that does that? My understanding is that you always get base name, major and major.minor binary flavors.

**Comment by puririshi98** [comment]
> python3 alias for python 3 and only "python" which refers to python 3.


i do not know of a specific OS off the top of my head where that is the default setup, I just thought that it was a possibility if people have older setups that they have updated overtime in custom ways. If you think it is entirely impossible to occur in a custom setup I do not have any evidence to argue the contrary. I was simply trying to cover all possibilities for safety.

**Comment by albanD** [comment]
Thanks for being careful about that.
I think I would prefer with simplicity here unless we have a good reason not to. So just changing this to python3 should be good enough for now.

**Review by albanD — APPROVED** [review]
Thanks for the update!

**Pull request closed without merging**
