### PR TITLE
CUDA Graph Trees - error on deallocated access

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #100927

Turn warning to error if we detect tensor is accessed after its memory is overwritten/released by a new invocation of cudagraphs.

cc @soumith @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by Chillee — COMMENTED** [review]
Yay!! I'll perhaps leave the TensorImpl/C++ changes reviewing to @zou3519 though.

One thing I was concerned about - I seem to remember that any changes touching TensorImpl are very fraught with potential performance regressions. Is that a concern here?

**Comment by eellison** [comment]
@Chillee I'm doing this on the warmup and record, so in the first two iterations (and then again whenever you are forced to recompile). we could do it on the steady state, but it seems pretty unlikely that you would both a) hit a new code path where you are hitting an error where you didnt previously and b) not need to recompile. we could add a mode to check even in steady state, but for perf reasons as you're saying, would be good to avoid always doing.

**Review by zou3519 — APPROVED** [review]
LGTM

> One thing I was concerned about - I seem to remember that any changes touching TensorImpl are very fraught with potential performance regressions. Is that a concern here?

The two things to be on the lookout for are usually (1) fast-path performance and (2) memory usage (if we increase the size of each tensor by 8 bytes, and your model has 1M parameters, then that is a lot of memory).

For (1), we're not changing the fast-path -- if the tensor doesn't have storage and needs to raise an error, then we have made it slightly slower (because it now needs to look up the error message via an indirection).

For (2), `ExtraMeta*` is not allocated by default, so we're not increasing the size of TensorImpl

**Pull request closed without merging**
