### PR TITLE
Optimize transpose copy on CPU using fbgemm transpose

### PR DESCRIPTION
**Pull request by CaoE**
### Description
Optimize transpose copy on CPU using fbgemm transpose

### Testing
single socket (28cores):
```
before: torch.Size([10, 128, 10, 124]) -> torch.Size([10, 128, 124, 10]) fp32: 4.819e-05 s; bf16: 4.846e-05 s
        torch.Size([10, 128, 30, 124]) -> torch.Size([10, 128, 124, 30]) fp32: 0.000171 s; bf16: 0.000129 s
            
after: torch.Size([10, 128, 10, 124]) -> torch.Size([10, 128, 124, 10])  fp32: 2.439e-05 s; bf16: 2.152e-05 s
        torch.Size([10, 128, 30, 124]) -> torch.Size([10, 128, 124, 30]) fp32: 0.000132 s; bf16: 3.916e-05 s
```
single core:
```
before: torch.Size([10, 128, 10, 124]) -> torch.Size([10, 128, 124, 10]) fp32: 0.00109 s;  bf16: 0.00103 s
        torch.Size([10, 128, 30, 124]) -> torch.Size([10, 128, 124, 30]) fp32: 0.00339 s; bf16: 0.00295 s
            
after: torch.Size([10, 128, 10, 124]) -> torch.Size([10, 128, 124, 10]) fp32: 0.000566  s; bf16: 0.000382 s
        torch.Size([10, 128, 30, 124]) -> torch.Size([10, 128, 124, 30]) fp32: 0.00282 s; bf16: 0.000999 s
```

### CODE REVIEW

**Comment by frank-wei** [comment]
@CaoE  have you done any change to this diff compared with #83327?

**Comment by CaoE** [comment]
> @CaoE have you done any change to this diff compared with #83327?

Hi @frank-wei, I just add the check `src.size(src.dim() - 1) <= std::numeric_limits<int32_t>::max() &&
      src.size(src.dim() - 2) <= std::numeric_limits<int32_t>::max()` as fbgemm transpose has not made the data types of parameter consistent yet.  
```
template <typename T>
FBGEMM_API void transpose_simd(
    unsigned M,
    unsigned N,
    const T* src,
    unsigned ld_src,
    T* dst,
    unsigned ld_dst);

void transpose_avx512(
    int64_t M,
    int64_t N,
    const T* src,
    unsigned ld_src,
    T* dst,
    unsigned ld_dst);
```

Also still waiting for reproducing the internal errors.

**Comment by frank-wei** [comment]
Pls fix the failed tests.

**Comment by malfet** [comment]
Please do not add `intel-priority` label on PRs which are yet not ready for review (i.e. in draft state or ones that can not pass CI)

**Comment by weiwangmeta** [comment]
Please also make sure the following reproducer passes of course since these two PRs are connected on this: 

https://github.com/pytorch/pytorch/pull/83327#issuecomment-1251703374

**Comment by CaoE** [comment]
> Please do not add `intel-priority` label on PRs which are yet not ready for review (i.e. in draft state or ones that can not pass CI)

Removed the label. This PR is not ready yet, because this PR has a large influence range, and the fbgemm's transpose is not optimal in some cases, requiring a lot of benchmark and model feedback results.

**Pull request closed without merging**
