### PR TITLE
Run method_tests on CUDA.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#30821 Run method_tests on CUDA.**

While investigating while our tests didn't catch #30704 I noticed that none
of our tests in method_tests() were being run on CUDA.  This diff moves
those tests into the new device-generic test framework so that we also get
CUDA coverage.  For expediency, I blacklisted all tests which didn't work
on CUDA (rather than fix them); that's something we can leave for future PRs.
This is done by way of a new expectedFailure gadget.

Note that all occurences of skipIfNoLapack needed to be replaced with
skipCPUIfNoLapack.

I punted for test_jit; it's possible those tests should also run CUDA but a JIT
expert should take a look here.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D18840089](https://our.internmc.facebook.com/intern/diff/D18840089)

### CODE REVIEW

**Comment by ezyang** [comment]
@suo I tagged you to check on the JIT changes. If you make the call that the JIT tests should also run in CUDA I can make that adjustment as well.

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit c363f56:
* **2/2** failures introduced in this PR



## Detailed failure analysis (WIP)

Here are the [reasons each build failed](https://dr.pytorch.org/commit-details.html?sha1=c363f561d37737f42ffee9549037c50fc241a120):

### 2 failures recognized by patterns:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/3802282) pytorch_linux_xenial_py3_6_gcc5_4_ge_config_legacy_test
**Step:** Test
```
Dec 05 16:53:43 RuntimeError: test_jit_legacy failed!
```
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/3802280) pytorch_linux_xenial_py3_6_gcc5_4_ge_config_simple_test
**Step:** Test
```
Dec 05 16:53:43 RuntimeError: test_jit_simple failed!
```


---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Comment by suo** [comment]
JIT changes look fine to me, I don't think there's much value in running the autogenerated tests in CUDA.

**Review by mruberry — APPROVED** [review]
Your extension to the generic test framework looks clean and natural. Great to have more test coverage!

**Comment by ezyang** [comment]
cc @iotamudelta about the ROCm exclusion

**Comment by iotamudelta** [comment]
@ezyang what are the failures observed with ROCm?

**Comment by ezyang** [comment]
Recorded in https://github.com/pytorch/pytorch/issues/30845

**Pull request closed without merging**
