### PR TITLE
MPS: Fix crashes in view tensors due to buffer size mismatch

### LINKED ISSUE #78247: MPS convolution crashing on .expand kernel (non-contiguous)
### 🐛 Describe the bug

Convolution with non-contiguous kernel lead to crash.

```python3
import torch
import torch.nn.functional as F
device = torch.device('mps')

input = torch.rand(2, 3, 16, 16, device=device)
kernel = torch.rand(1, 1, 3, 11, device=device)
tmp_kernel = kernel.expand(-1, 3, -1, -1)
output = F.conv2d(input, tmp_kernel, groups=1, padding=0, stride=1)
```

Outcome:

```
/AppleInternal/Library/BuildRoots/8d3bda53-8d9c-11ec-abd7-
fa6a1964e34e/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:782: 
failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. 
Must be 396 bytes
```

It crashes regardless if the flag `PYTORCH_ENABLE_MPS_FALLBACK=1 ` is used or not
Expected: not crash.

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0.dev20220524
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3 (arm64)
GCC version: Could not collect
Clang version: 13.0.1
CMake version: version 3.22.3
Libc version: N/A

Python version: 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:10:52)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: macOS-12.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.910
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] pytest-mypy==0.9.0
[pip3] torch==1.13.0.dev20220524
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.10.0
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] torch                     1.13.0.dev20220524          pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchvision               0.10.0                   pypi_0    pypi
```

### PR DESCRIPTION
**Pull request by kulinseth**
Fixes #78247, #77886

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Good practice to avoid regressions would be to add unittest that would crash before fix is applied, but pass with fix in place

**Comment by kulinseth** [comment]
> Good practice to avoid regressions would be to add unittest that would crash before fix is applied, but pass with fix in place

Added a test case.

**Comment by richardburleigh** [comment]
Thank you for all the amazing work on MPS! However I'm still facing the 'buffer is not large enough' issue when attempting training with this pull request on some GAN models, such as [Stylegan XL](https://github.com/autonomousvision/stylegan_xl):

```
Allocated large private heap of size 32.00 MB (#heaps: 34, free memory: 20.34 GB)
Allocated private buffer #893 with aligned size 5.06 MB (requested size: 5.06 MB, heap size: 26.94 MB, total allocated: 953.70 MB)
Allocated private buffer #894 with aligned size 10.12 MB (requested size: 10.12 MB, heap size: 16.81 MB, total allocated: 963.82 MB)
Allocated private buffer #895 with aligned size 10.12 MB (requested size: 10.12 MB, heap size: 6.69 MB, total allocated: 973.95 MB)

Allocated large private heap of size 12.00 MB (#heaps: 35, free memory: 20.33 GB)
Allocated private buffer #896 with aligned size 10.12 MB (requested size: 10.12 MB, heap size: 1.88 MB, total allocated: 984.07 MB)
/AppleInternal/Library/BuildRoots/8d3bda53-8d9c-11ec-abd7-fa6a1964e34e/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:782: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 10616832 bytes
```

**Comment by crayon7442** [comment]
I want to solve this issue..
MPSNDArray.mm:782: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 19200 bytes'

**Comment by adamdavidcole** [comment]
Hello! I'm also still running into the same issue when running image generation using a GAN. Not sure what info would be useful, but happy to provide more details. 


```
Generating image for seed 85 (0/1) ...
/AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:782: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 10616832 bytes
```

**Comment by ebraminio** [comment]
A possibly related issue to this, https://github.com/pytorch/pytorch/issues/87351

**Pull request closed without merging**
