### PR TITLE
Clang-Tidy: Prevent implicit promotion in math functions

### PR DESCRIPTION
**Pull request by Skylion007**
Ensure that accidental promotions in functions does not accidentally occur

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by Skylion007** [comment]
Hmm, that one failure is also happening on master so it seems unrelated.

**Comment by Skylion007** [comment]
cc @ezyang since it's related to the other clang-tidy PRs.

**Comment by ezyang** [comment]
btw @Skylion007 for more timely merges you can manually add the 'ciflow/trunk' label to trigger the land blocking tests. If you don't have rights to do so holler and I'll try to get you them

**Review by ezyang — APPROVED** [review]

**Comment by Skylion007** [comment]
> btw @Skylion007 for more timely merges you can manually add the 'ciflow/trunk' label to trigger the land blocking tests. If you don't have rights to do so holler and I'll try to get you them

I don't have the rights to assign tags to my PR, unfortunately (or rerun failing checks). Feel free to do what you can to get me them.

**Comment by Skylion007** [comment]
Also looks like more flakes. :/

**Comment by ezyang** [comment]
invite sent

**Pull request closed without merging**
