### PR TITLE
Dynamo.export uses dynamic=True for symbolic tracing

### PR DESCRIPTION
**Pull request by SherlockNoMad**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #91899

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
ugh, why doesn't export just take `dynamic` directly lol

**Comment by SherlockNoMad** [comment]
> ugh, why doesn't export just take `dynamic` directly lol

We should, and this will be an API change for dynamo.export()... and maybe we should do this sooner than latter.

Also, is fake tracing mode still a thing after the Symbolic shape branch is merged. IIUC, we should end up with only two mode, static(real tracing mode) vs. dynamic (symbolic tracing mode) , right?

**Comment by ezyang** [comment]
I would like to get rid of real tracing mode (where you actually run the tensor compute) entirely, but IIRC last time I tried to get rid of it there were... problems

**Comment by SherlockNoMad** [comment]
> I would like to get rid of real tracing mode (where you actually run the tensor compute) entirely, but IIRC last time I tried to get rid of it there were... problems

I think there are still merits of real tracing mode. 
In the case of custom op without meta implementation, (or its meta implementation doesn't support symbolic shape), real tracing mode would still work, I am not sure what would happen if it were traced with symbolic mode?  

What should be our policy on custom op being traceable?

**Pull request closed without merging**
