### PR TITLE
[Test] Upgrade NVTX to NVTX3 - no gated include

### PR DESCRIPTION
**Pull request by izaitsevfb**
Testing a modified #97582 that supports a single include style: `#include <nvToolsExt.h>` for whichever NVTX version is available.

### CODE REVIEW

**Comment by cyyever** [comment]
@izaitsevfb We can focus on this work now.

**Comment by izaitsevfb** [comment]
@cyyever, sure. Do you think this approach is viable? Looks like we already use nvtx3 internally, but with `#include <nvToolsExt.h>` include style.

**Comment by cyyever** [comment]
@izaitsevfb We can try discarding the nvtx third party since now we assume CUDA 11.7+.

**Pull request closed without merging**
