### PR TITLE
add back NNPACK in PyTorch

### PR DESCRIPTION
**Pull request by t-vi**
This tests the water for adding back NNPACK in PyTorch, it's a lot better than the fallback THNN versions.

In #6151, we (@ezyang and @soumith) removed NNPACK support from PyTorch. Of course @Maratyszcza might have advice, too. (Or an opinion on the CMake changes.)

The only functional changes are to use NNPack more aggressively on mobile and a .contiguous() to match NNPack's assumption (I stumbled over that while using NNPack for style transfer.)
The CMake changes try to use the NNPack we already have in git.

In terms of lines of code this is a large part of the diff of https://lernapparat.de/pytorch-jit-android/ . As far as I can tell, we don't have MKLDNN on mobile and the native THNN implementation are prohibitively expensive in terms of both CPU and memory.

### CODE REVIEW

**Comment by t-vi** [comment]
(This needs test.)

**Comment by ezyang** [comment]
I'm fine with this. Primary problem is to make sure we are testing this adequately.

**Comment by t-vi** [comment]
So for testing, we would need to make sure there is a configuration which does not call one of the "higher priority" implementations like MKLDNN. That could be either by compiling without them (would be natural with Android which is what would be the next PR) or by providing context flags similar to cudnn enabled. I would check that it actually is used using `output.gradfn`.
The "light testing" - not having the use_nnpack function - would be to call the internal function directly, but that seems not ideal.

**Comment by ezyang** [comment]
I'm actually a fan of the plan where we call the internal function directly, at least for things like gradcheck.  It's the most direct way of saying, "Hey, I want the nnpack convolution implementation." Additionally, since we define backwards separately for each underlying implementation, things should just work.

**Comment by t-vi** [comment]
OK, I'll add those then. Thank you for the feedback, I sincerely appreciate it!

**Comment by t-vi** [comment]
So I added tests for forward and backward against "default conv" for the applicable cases in TestNN.test_grad_conv.

**Comment by t-vi** [comment]
- So the ASAN failure `caffe2/utils/threadpool/pthreadpool_impl.cc:25:13: runtime error: call to function compute_2d_tiled(compute_2d_tiled_context const*, unsigned long) through pointer to incorrect function type 'void (*)(void *, unsigned long)'` seems valid, but probably changes stuff in how caffe2 uses NNPack?
I'm uncertain whether it's the `const` or the type that it doesn't like, maybe changing the signature to `void*` and cast it within the function would work, would that be likeable?

- I don't know what to make of the NNPack init failure on MacOS.

- I need to skip the test if I don't have NNPack (for the windows failure).

Do you have any advice on the first two?

**Comment by ezyang** [comment]
> ASAN failure

It's UB to cast a function pointer to another type with different argument types, even if argument types themselves are castable. So the right thing to do is either (1) make a wrapper function with the correct type or (2) don't cast the function pointer and do a cast when you're passing arguments.

Also, lol at the fact that caffe2 wasn't testing nnpack under ASAN previously. If you want to foist this off on someone caffe2 side shout.

> I don't know what to make of the NNPack init failure on MacOS.

That's pretty weird. @Maratyszcza any ideas? One suggestion is to make it report a more detailed information about the specific error code.

Here's the implementation of nnp_initialize:

```
enum nnp_status nnp_initialize(void) {
	if (!cpuinfo_initialize()) {
		return nnp_status_out_of_memory;
	}
	pthread_once(&hwinfo_init_control, &init_hwinfo);
	if (nnp_hwinfo.supported) {
		return nnp_status_success;
	} else {
		return nnp_status_unsupported_hardware;
	}
}
```

**Comment by t-vi** [comment]
Thanks @ezyang !
I'm happy to submit a PR, but I'd prefer to not implement it in a way the Caffe2 colleagues don't like, so I could use a hint which of the options you set out they prefer:
1. make a wrapper function with the correct type or
2. don't cast the function pointer and do a cast when you're passing arguments.
At first sight, I would expect the second to be slightly more straightforward because of the "reduction" to 1d ops, but that could be my limited understanding of the code.

I'll add the enhanced diagnostics.

**Comment by t-vi** [comment]
So in the MacOS CI we have unsupported hardware. The question would be how to deal with that. The easiest might be to set a static bool flag and test in use_nnpack do the initialization and check the bool flag.

**Comment by ezyang** [comment]
Makes sense to me!

**Review by ezyang — APPROVED** [review]

**Comment by t-vi** [comment]
Thanks @ezyang !

**Pull request closed without merging**
