### PR TITLE
Disable SymDispatchMode when torch.compile'ing

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #132433

Partially addresses https://github.com/pytorch/pytorch/issues/132417

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by ydwu4 — APPROVED** [review]

**Comment by PaliC** [comment]
@pytorchbot revert -m "We need to now revert https://github.com/pytorch/pytorch/pull/132216 in OSS and there is a dependency on this pr" -c "weird"

Please remerge once  https://github.com/pytorch/pytorch/pull/132216 is reverted

**Comment by PaliC** [comment]
@pytorchbot revert -m "We need to now revert https://github.com/pytorch/pytorch/pull/132216 in OSS and there is a dependency on this pr" -c "weird"

Please remerge once https://github.com/pytorch/pytorch/pull/132216 is reverted

**Pull request closed without merging**
