### PR TITLE
Use amax/maximum instead of max in optimizers

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Review by mruberry — APPROVED** [review]

**Comment by mruberry** [comment]
Thanks @zasdfgbnm! The legacy fuser can't understand how to fuse minimum/maximum, so we may not be able to land these changes for awhile. I don't think anyone is relying on legacy fusion in these cases, however.

**Comment by zasdfgbnm** [comment]
rebase after revert and reland of amax PR

**Comment by mruberry** [comment]
@zasdfgbnm Ping on this. Is this ready for an update?

**Comment by zasdfgbnm** [comment]
@mruberry Yes, and I just rebased.

**Pull request closed without merging**
