### PR TITLE
[distributions] Add DiagonalNormal distribution.

### PR DESCRIPTION
**Pull request by ethanluoyc**
This PR intends to add a convenience distribution class for Diagonal Normal distribution. This is useful,
for example, in the setting of a Variational Autoencoder with a diagonal posterior.

### CODE REVIEW

**Comment by ezyang** [comment]
This needs a test.

**Comment by fritzo** [comment]
Isn't `Normal` already a diagonal normal distribution?

**Comment by ethanluoyc** [comment]
@fritzo I am not sure about that though. I thought in terms of batching Normal will be different from DiagonalNormal?

**Comment by fritzo** [comment]
@ethanluoyc We use batched `Normal`s for the embedding distributions in VAEs, so I would guess that `Normal` would work for you. Note that
```py
assert Normal(torch.zeros(3,4,5), torch.ones(3,4,5)).rsample().shape == (3,4,5)
```
That said, I'd be interested to hear if you have use for nonempty `event_shape`. In Pyro we have very strict shape requirements due to automating tensor dimension allocation and strict shape checking, so we've created a generic [ReshapedDistribution](https://github.com/uber/pyro/blob/35ec350/pyro/distributions/torch_distribution.py#L165) that sets a default `sample_shape` and adjusts `event_shape`. We haven't anticipated this being useful outside of a PPL (e.g. I would never use it by hand), but if you have specific use cases we could move it upstream to PyTorch.

**Comment by ethanluoyc** [comment]
@fritzo what you suggested works for my use cases. The only reason I wrote DiagonalNormal is because that event_shape for Normal is confusing, which you have identified above.

```python
d = distributions.Normal(torch.zeros(1,3), torch.ones(1,3))
```
This will not have event_shape (3,) if you consider Diagonal Gaussians.

I think we can close this, but perhaps adding some documentation to Normal would be able to clarify the more generate use case for multivariate normal.

**Comment by fritzo** [comment]
> @ethanluoyc  [the empty] `event_shape` for Normal is confusing

Thanks, that's good to know! We do need more documentation about batch_shape and event_shape before 0.4 release, and I'll try to add further explanation. (I'm writing similar docs for Pyro this week).

**Comment by apaszke** [comment]
This is going to be resolved as a doc fix, so I'm closing the PR. Thank you @ethanluoyc!

**Pull request closed without merging**
