### PR TITLE
add native kernel for weight_norm on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #73845

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35782874).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35782874).

**Comment by mingfeima** [comment]
move this one out of bfloat16 stack so that it is not a blocker.

**Comment by mingfeima** [comment]
Add benchmarking result, CPU Xeon 6248, 20 cores per socket, dual socket, 2.50GHz:

### weight norm float32
```
### before
weight_norm: first_dim:  batch_size = 128, ic = 256, oc = 256: time per iteration: 0.116 ms
weight_norm: first_dim:  batch_size = 128, ic = 256, oc = 512: time per iteration: 0.126 ms
weight_norm: first_dim:  batch_size = 128, ic = 512, oc = 512: time per iteration: 0.159 ms
weight_norm: first_dim:  batch_size = 128, ic = 512, oc = 1024: time per iteration: 0.211 ms
weight_norm: first_dim:  batch_size = 128, ic = 1024, oc = 1024: time per iteration: 0.369 ms
weight_norm: last_dim:  batch_size = 128, ic = 256, oc = 256: time per iteration: 0.111 ms
weight_norm: last_dim:  batch_size = 128, ic = 256, oc = 512: time per iteration: 0.126 ms
weight_norm: last_dim:  batch_size = 128, ic = 512, oc = 512: time per iteration: 0.158 ms
weight_norm: last_dim:  batch_size = 128, ic = 512, oc = 1024: time per iteration: 0.212 ms
weight_norm: last_dim:  batch_size = 128, ic = 1024, oc = 1024: time per iteration: 0.371 ms

### after
weight_norm: first_dim:  batch_size = 128, ic = 256, oc = 256: time per iteration: 0.077 ms
weight_norm: first_dim:  batch_size = 128, ic = 256, oc = 512: time per iteration: 0.088 ms
weight_norm: first_dim:  batch_size = 128, ic = 512, oc = 512: time per iteration: 0.123 ms
weight_norm: first_dim:  batch_size = 128, ic = 512, oc = 1024: time per iteration: 0.181 ms
weight_norm: first_dim:  batch_size = 128, ic = 1024, oc = 1024: time per iteration: 0.343 ms
weight_norm: last_dim:  batch_size = 128, ic = 256, oc = 256: time per iteration: 0.068 ms
weight_norm: last_dim:  batch_size = 128, ic = 256, oc = 512: time per iteration: 0.087 ms
weight_norm: last_dim:  batch_size = 128, ic = 512, oc = 512: time per iteration: 0.123 ms
weight_norm: last_dim:  batch_size = 128, ic = 512, oc = 1024: time per iteration: 0.180 ms
weight_norm: last_dim:  batch_size = 128, ic = 1024, oc = 1024: time per iteration: 0.347 ms
```

### weight norm bfloat16
```
### before
weight_norm: first_dim:  batch_size = 128, ic = 256, oc = 256: time per iteration: 0.160 ms
weight_norm: first_dim:  batch_size = 128, ic = 256, oc = 512: time per iteration: 0.200 ms
weight_norm: first_dim:  batch_size = 128, ic = 512, oc = 512: time per iteration: 0.309 ms
weight_norm: first_dim:  batch_size = 128, ic = 512, oc = 1024: time per iteration: 0.480 ms
weight_norm: first_dim:  batch_size = 128, ic = 1024, oc = 1024: time per iteration: 0.839 ms
weight_norm: last_dim:  batch_size = 128, ic = 256, oc = 256: time per iteration: 0.161 ms
weight_norm: last_dim:  batch_size = 128, ic = 256, oc = 512: time per iteration: 0.202 ms
weight_norm: last_dim:  batch_size = 128, ic = 512, oc = 512: time per iteration: 0.309 ms
weight_norm: last_dim:  batch_size = 128, ic = 512, oc = 1024: time per iteration: 0.480 ms
weight_norm: last_dim:  batch_size = 128, ic = 1024, oc = 1024: time per iteration: 0.839 ms

### after
weight_norm: first_dim:  batch_size = 128, ic = 256, oc = 256: time per iteration: 0.128 ms
weight_norm: first_dim:  batch_size = 128, ic = 256, oc = 512: time per iteration: 0.165 ms
weight_norm: first_dim:  batch_size = 128, ic = 512, oc = 512: time per iteration: 0.274 ms
weight_norm: first_dim:  batch_size = 128, ic = 512, oc = 1024: time per iteration: 0.452 ms
weight_norm: first_dim:  batch_size = 128, ic = 1024, oc = 1024: time per iteration: 0.807 ms
weight_norm: last_dim:  batch_size = 128, ic = 256, oc = 256: time per iteration: 0.123 ms
weight_norm: last_dim:  batch_size = 128, ic = 256, oc = 512: time per iteration: 0.166 ms
weight_norm: last_dim:  batch_size = 128, ic = 512, oc = 512: time per iteration: 0.276 ms
weight_norm: last_dim:  batch_size = 128, ic = 512, oc = 1024: time per iteration: 0.452 ms
weight_norm: last_dim:  batch_size = 128, ic = 1024, oc = 1024: time per iteration: 0.807 ms
```

(*) my test machine is not equipped with AMX so bf16 is not faster than fp32 on gemm, anyway the point here is to test weight_norm native kernel, should be enough as well.

**Comment by mingfeima** [comment]
@ezyang Hi, could you please advise how to deal with bc breaking:

this PR changed `_weight_norm_cuda_interface` to `_weight_norm_interface` and has the following failure:

```
The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not. 

Broken ops: [
	aten::_weight_norm_cuda_interface(Tensor v, Tensor g, int dim=0) -> (Tensor, Tensor)
	aten::_weight_norm_cuda_interface_backward(Tensor grad_w, Tensor saved_v, Tensor saved_g, Tensor saved_norms, int dim) -> (Tensor, Tensor)
]
```

**Comment by ezyang** [comment]
Should be OK. Add it to the whitelist in test/forward_backward_compatibility/check_forward_backward_compatibility.py

**Comment by frank-wei** [comment]
@frank-wei has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35782874).

**Comment by frank-wei** [comment]
@frank-wei has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35782874).

**Comment by frank-wei** [comment]
@frank-wei has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35782874).

**Review by frank-wei — APPROVED** [review]
LGTM!

**Pull request closed without merging**
