### PR TITLE
[jit] Made floor/ceil return ints (yay Python 3!)

### PR DESCRIPTION
**Pull request by Chillee**
In particular, I think `flooor/ceil` should have special handling (even if we silently fail for other functions) as they're returning integers. Having `pow(0, -2)` return `inf` is somewhat reasonable, having `floor(NaN)` return -951347564385 (or something like that) is less so.

### CODE REVIEW

**Comment by eellison** [comment]
We have to be careful not to break BC here

**Comment by ailzhang** [comment]
Yea agree with @Elias Ellison<mailto:eellison@fb.com> . We will need to label this as bc breaking if the original implementation was in 1.1.0 release.
Although in general I feel it’s good to align our behavior with py3 as early as possible. @Horace He<mailto:chilli@fb.com> would you mind give it a quick check and label this PR if necessary? Thanks!!

Thanks,
Ailing
________________________________

**Comment by Chillee** [comment]
I believe the original implementation was checked in before 1.1.0.

Does it actually break backwards compatibility though? Ints are implicitly upcasted to floats when necessary right? I suppose there could always be code that called `isinstance` or something.

**Comment by eellison** [comment]
> I believe the original implementation was checked in before 1.1.0.
> 
> Does it actually break backwards compatibility though? Ints are implicitly upcasted to floats when necessary right? I suppose there could always be code that called `isinstance` or something.

ints arent upcasted to floats

**Comment by Chillee** [comment]
Closing this PR in favor of the stack I'm about to push.

**Comment by Chillee** [comment]
This is the new PR: https://github.com/pytorch/pytorch/pull/21124

**Pull request closed without merging**
