### PR TITLE
fix aminmax output resize issue when input is a zero dimension tensor

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96171

Fix https://github.com/pytorch/pytorch/issues/96042

### before
```
>>> torch.aminmax(torch.tensor(1, device='cpu'), dim=0, keepdim=True)
__main__:1: UserWarning: An output with one or more elements was resized since it had shape [], which does not match the required output shape [1]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:24.)
torch.return_types.aminmax(
min=tensor([1]),
max=tensor([1]))
>>> torch.aminmax(torch.tensor(1, device='cpu'), dim=0, keepdim=False)
torch.return_types.aminmax(
min=tensor(1),
max=tensor(1))
```
### after
```
>>> torch.aminmax(torch.tensor(1, device='cpu'), dim=0, keepdim=True)
torch.return_types.aminmax(
min=tensor(1),
max=tensor(1))
>>> torch.aminmax(torch.tensor(1, device='cpu'), dim=0, keepdim=False)
torch.return_types.aminmax(
min=tensor(1),
max=tensor(1))

```

Marked the following test as expected_fail:
`test_vmap.py TestVmapOperatorsOpInfoCPU.test_op_has_batch_rule_aminmax_cpu_float32`

Given input shape of (2), the loop out is shape (2), the batched vmap out is (2, 1), which mismatched.
The loop out will calculate twice on a tensor shape of ( ): without this patch, the output is (1), and then stacked into (2, 1); with this patch, the output is ( ), then stacked into (2).

cc @jgong5 @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by ngimel** [comment]
You'd also need to remove special handling in decomp now that CPU doesn't have inconsistent behavior

**Review by jgong5 — APPROVED** [review]

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
cc @zou3519 for vmap errors. If 0d tensor is vmapped, what's the expected result? Here it seems vmap produces (2,1) whereas loop correctly produces (2).
@mingfeima I think we can skip failing tests for now.

**Comment by zou3519** [comment]
> cc @zou3519 for vmap errors. If 0d tensor is vmapped, what's the expected result? Here it seems vmap produces (2,1) whereas loop correctly produces (2).

The expected result is whatever the loop produces (so it sounds like 2).

From the comment over [here]( https://github.com/pytorch/pytorch/blob/4a1b9717481070e204c9d2049213c24457ba8592/aten/src/ATen/functorch/BatchRulesReduceOps.cpp#L319-L321), it sounds like we can just add a REDUCTION_WITH_KEEPDIM_ARG(aminmax) like [this](https://github.com/pytorch/pytorch/blob/4a1b9717481070e204c9d2049213c24457ba8592/aten/src/ATen/functorch/BatchRulesReduceOps.cpp#L487) and delete [this](https://github.com/pytorch/pytorch/blob/4a1b9717481070e204c9d2049213c24457ba8592/aten/src/ATen/functorch/BatchRulesReduceOps.cpp#L514).

This is not too much of a change, if you're interested in handing in this PR @mingfeima. Otherwise I can handle it later after this PR lands

**Comment by mingfeima** [comment]
> > cc @zou3519 for vmap errors. If 0d tensor is vmapped, what's the expected result? Here it seems vmap produces (2,1) whereas loop correctly produces (2).
> 
> The expected result is whatever the loop produces (so it sounds like 2).
> 
> From the comment over [here](https://github.com/pytorch/pytorch/blob/4a1b9717481070e204c9d2049213c24457ba8592/aten/src/ATen/functorch/BatchRulesReduceOps.cpp#L319-L321), it sounds like we can just add a REDUCTION_WITH_KEEPDIM_ARG(aminmax) like [this](https://github.com/pytorch/pytorch/blob/4a1b9717481070e204c9d2049213c24457ba8592/aten/src/ATen/functorch/BatchRulesReduceOps.cpp#L487) and delete [this](https://github.com/pytorch/pytorch/blob/4a1b9717481070e204c9d2049213c24457ba8592/aten/src/ATen/functorch/BatchRulesReduceOps.cpp#L514).
> 
> This is not too much of a change, if you're interested in handing in this PR @mingfeima. Otherwise I can handle it later after this PR lands

@zou3519 Thanks for the input! Update this patch according to your proposal.

**Review by zou3519 — APPROVED** [review]
Thank you!

**Pull request closed without merging**
