### PR TITLE
Don't run fallback if symbolic sizes in fake tensor

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #97148

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by eellison — APPROVED** [review]

**Review by bdhirsh — APPROVED** [review]
side note: I wonder if we should avoid the entire try + except and fallback if we see an operator that's not part ATen (aka all custom ops)

There was at least one example github issue of torch.compile failing with an awful error, because we tried to plumb fake tensors and the custom op wasn't written in a way to handle them.

I would probably take the hit of having some custom ops stop working automatically (with a loud error saying they need a meta function impl, and some docs on how to add one), over some custom ops silently giving bad error messages / segfaults.

**Comment by ezyang** [comment]
> side note: I wonder if we should avoid the entire try + except and fallback if we see an operator that's not part ATen (aka all custom ops)

Yes, our coverage is good enough that I will support removing the fallback entirely. @eellison WDYT

**Comment by eellison** [comment]
I'm not in favor of that because of all the custom operators that don't have meta funcs. 
Pros: dont IMA on operators that would IMA on all zeros
Cons: lose large amount of coverage on user operators

IMO the IMA zeros case is much, much less frequent.

**Comment by ezyang** [comment]
But IMA zeros is much, much worse, whereas missing coverage is kind of meh and kind of easy to fix.

**Pull request closed without merging**
