### PR TITLE
Add TORCH_CUDA_CU_API to CUDABlas functions

### PR DESCRIPTION
**Pull request by malfet**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #72306
* __->__ #72305
* #72304

In order to make them accessible
Also make `REGISTER_ARCH_DISPATCH` export dispatches as  TORCH_API, so that stubs could be called from libraries other than `torch_cpu`

Differential Revision: [D33992798](https://our.internmc.facebook.com/intern/diff/D33992798)

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33992798).

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33992798).

**Comment by janeyx99** [comment]
Reverting as this PR broke several windows builds on trunk https://www.torch-ci.com/minihud#07e9f86a4bb0116d61724a2b89866fe2f438ce0f, some shown in the PR signal. 

Please use the ciflow/win label to test all windows builds when resubmitting this PR.

**Comment by malfet** [comment]
Closing in favor of https://github.com/pytorch/pytorch/pull/72340

**Pull request closed without merging**
