### PR TITLE
[dynamo] override torch.nn.modules.activation._is_make_fx_tracing

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #128148
* __->__ #128748
* #128315

Discovered while inlining `MultiHeadAttention` nn Module.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
Why not just add it to this list:
https://github.com/pytorch/pytorch/blob/108adbc726553ddba005c42ac8d511212bec8c32/torch/_dynamo/variables/torch.py#L119-L129

**Comment by anijain2305** [comment]
> tracing_state_functions

Thanks, this is what I was looking for :)

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
