### PR TITLE
Updated NLLLoss2d.cu, fixing assertion related to number of classes when tensor in GPU 

### LINKED ISSUE #49882: nll_loss2d: t >= 0 && t < n_classes assertion is not checked when reduction='none'
## 🐛 Bug

The assertion of t >= 0 && t < n_classes is silently ignored in `F.cross_entropy` (in turn, `nn_loss2d`) while using cuda tensors and option `reduction='none'`.

issue raised on behalf of @Pavan_Teja from pytorch forum: https://discuss.pytorch.org/t/mysterious-behaviour-of-cross-entropy-loss/107285

## To Reproduce

Code to reproduce the behavior:

```
import torch
import torch.nn.functional as F

is_cuda = True

input = torch.randn(1, 19, 32, 64, requires_grad=True)
target = torch.randint(22, size=(1,32,64,))
print(input.dim())

print("number of out-of-bound targets", (target > 18).sum())

if is_cuda:
    input = input.cuda()
    target = target.cuda()

out = F.cross_entropy(input, target, weight=None, ignore_index=255, reduction='none')
print(out)
```

## Expected behavior

In the code example above, `input` contains 2D logits for 19 classes at each pixel and `target` contains out-of-bounds class indices.
Ideally, `F.cross_entropy` should report errors for out-of-bounds class indices (regardless of whether CPU or GPU tensors are used).

## Observed behavior
In my testing,

For CPU tensors: the error is reported correctly (Error message: `IndexError: Target 20 is out of bounds.`)

For GPU tensors: for the option, `reduction='mean`' and `reduction='sum'' the error is reported correctly (Error message: `cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [369,0,0] Assertion `t >= 0 && t < n_classes` failed.`)
However in the case of `reduction='none`', the error is not reported.

## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.3 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.5.1

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 440.31
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] numpydoc==1.1.0
[pip3] torch==1.6.0
[pip3] torch-scatter==2.0.5
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] libblas                   3.8.0                    14_mkl    conda-forge
[conda] libcblas                  3.8.0                    14_mkl    conda-forge
[conda] liblapack                 3.8.0                    14_mkl    conda-forge
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-service               2.3.0            py37h516909a_0    conda-forge
[conda] mkl_fft                   1.1.0            py37hc1659b7_1    conda-forge
[conda] mkl_random                1.1.0            py37hb3f55d8_0    conda-forge
[conda] numpy                     1.19.1           py37h7ea13bd_2    conda-forge
[conda] numpy-base                1.18.5           py37hde5b4d6_0  
[conda] numpydoc                  1.1.0              pyh9f0ad1d_0    conda-forge
[conda] pytorch                   1.6.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torch-scatter             2.0.5                    pypi_0    pypi
[conda] torchvision               0.7.0                py37_cu102    pytorch

## Additional context

After some search through low level pytorch code, I see that the device assertion is not checked in case of `reduction='none'`.
https://github.com/pytorch/pytorch/blob/963f7629b591dc9750476faf1513bc7f1fb4d6de/aten/src/THCUNN/generic/SpatialClassNLLCriterion.cu#L70-L99

i.e., `THCudaCheck(cudaGetLastError());` is missing incase of option `reduction='none'`.
Could this be the root cause for silently ignoring the out-of-bounds class indices?

### PR DESCRIPTION
**Pull request by SanjanaVHerur**
### This pull request 
- Fixes #49882

Ping @SanjanaVHerur

### CODE REVIEW

**Comment by SanjanaVHerur** [comment]
@albanD , @jbschlosser 

image

**Comment by SanjanaVHerur** [comment]
Hi @jbschlosser, I'd greatly appreciate your review on my pull request. I understand that you may have a busy schedule, and your insights are invaluable to improve the code quality. Thank you for your time!

**Comment by SanjanaVHerur** [comment]
Hi @jbschlosser, Can you please review my pull request, as i need this contribution for my internship selection.

**Comment by SanjanaVHerur** [comment]
My pull request has been labeled as stale, please review @jbschlosser

**Comment by jbschlosser** [comment]
@SanjanaVHerur sorry for the delay; I don't manage this area of the codebase anymore. Adding @mikaylagawarecki as reviewer instead.

**Comment by mikaylagawarecki** [comment]
Sorry for the delay in reviewing this one, it looks like CI is failing

**Pull request closed without merging**
