### PR TITLE
jit::script::Object::attr throws AttributeError

### LINKED ISSUE #34126: torch::jit::script::Object::attr should throw AttributeError instead of RuntimeError
## 🐛 Bug

Not doing so breaks the `hasattr` builtin, as per https://docs.python.org/3/library/functions.html#hasattr

## To Reproduce

```python
import torch

nt = torch.classes._TorchScriptTesting_PickleTester([3, 4])
print(hasattr(nt, "non_existent_attr"))
```

```
Traceback (most recent call last):
  File "test_script_throw.py", line 4, in <module>
    print(hasattr(nt, "non_existent_attr"))
RuntimeError: __torch__.torch.classes._TorchScriptTesting_PickleTester does not have a field with name 'non_existent_attr'
```
## Expected behavior

`hasattr` should not throw

### PR DESCRIPTION
**Pull request by Baranowski**
Fixes #34126

### CODE REVIEW

**Comment by yf225** [comment]
@suo Curious who would be the best reviewer for this task?

**Comment by suo** [comment]
@driazati can you review as part of the general C++ API stuff?

**Comment by Baranowski** [comment]
@driazati, I'm in no hurry with this, just making sure that it doesn't fall off the radar. Or, if you think that this PR should lie dormant for the foreseeable future, I'm happy to stop tracking it as well.

**Review by driazati — COMMENTED** [review]
Thanks for pinging me! I had missed this in my review queue. The code here seems all good to go, but the test you added is [failing](https://circleci.com/gh/pytorch/pytorch/5011565?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) in some environments and you should back out the submodule commits to `third_party/fbgemm` and `third_party/ideep`

**Comment by Baranowski** [comment]
Thanks for the review, @driazati. Both issues fixed.

**Review by driazati — APPROVED** [review]
Thanks!

**Pull request closed without merging**
