### PR TITLE
Correcting behaviour of torch.fmod on CPU and GPU 

### LINKED ISSUE #15921: Inconsistent behaviour of torch.fmod on CPU and GPU
## 🐛 Bug

`torch.fmod` yields different result between GPU and CPU for large numbers.

## To Reproduce
```python
import torch

print(torch.fmod(torch.tensor(421123111).cpu(), 2))  # 1
print(torch.fmod(torch.tensor(421123111).cuda(), 2))  # 0
```

## Expected behavior

Correct result for both runs or clear documentation about the inconsistency.

## Environment

```
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 410.79
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip3] numpy (1.15.4)
[pip3] torch (1.0.0)
[pip3] torchvision (0.2.1)
[conda] mkl                       2018.0.1             h19d6760_4  
[conda] mkl-service               1.1.2            py36h17a0993_4
```

### PR DESCRIPTION
**Pull request by rohitrango**
Fixes #15921 
Not a complete fix because other types like int32, etc. also have this problem

### CODE REVIEW

**Comment by soumith** [comment]
thanks rohit, can you add tests to test_torch.py / test_cuda.py (whichever is appropriate)

**Comment by rohitrango** [comment]
I have some checks failing, and I'm kind of stuck here. What am I supposed to do in this case?

**Comment by colesbury** [comment]
I think you should be able to use @pytorchbot retest this please if the build failures are unrelated

**Comment by colesbury** [comment]
But I thin circle-ci is just down now 😞

**Comment by rohitrango** [comment]
do the failed cases have to do something with the code I added ?

**Comment by colesbury** [comment]
Not sure. Going to try re-running the tests. @pytorchbot retest this please

**Pull request closed without merging**
