### PR TITLE
[caffe2] static build mkldnn into caffe2

### PR DESCRIPTION
**Pull request by gujinghui**
1. Fix build error for ideep
2. Seperate mkl, mklml and ideep support
3. static build mkldnn into caffe2 and pytorch
4. upgrade ideep and mkldnn

### CODE REVIEW

**Comment by gujinghui** [comment]
@yinghai @jgong5 
Pls help review

**Review by yinghai — CHANGES_REQUESTED** [review]
Thanks for the contribution. 
1. Can we state in the PR summary what this PR's purpose is? Why do we need static build? 

2. Can we split the PR into 3 with 
-  doing (1) and (2): fix and separate dependency
-  doing static build (3)
-  doing submodule update (4) 

3. Looks like the tests all failed.

**Comment by gujinghui** [comment]
split to #11853

**Comment by SsnL** [comment]
closing in favor of #11853

**Comment by SsnL** [comment]
@gujinghui Should this PR be closed because of #11853 and https://github.com/pytorch/pytorch/pull/11975 ? Sorry I don't really understand the context here.

cc @yinghai

**Comment by yinghai** [comment]
Yes. Let's close it.

**Pull request closed without merging**
