### PR TITLE
[ONNX] add test images to repo

### PR DESCRIPTION
**Pull request by garymm**
This is better than the status quo:
* Test doesn't download files from the internet -> faster and more
  reliable.
* Test doesn't leave the git working directory dirty.

Rather than using the original images, I've copied some images from
the pytorch/vision repo. This will keep the tests in the two repos
in sync, while avoiding adding new assets to the vision repo.

See https://github.com/pytorch/vision/pull/4176.

### CODE REVIEW

**Comment by garymm** [comment]
@malfet this is the PR that adds images that was causing issues when we tried merging onnx_ms_1 into master. They're copied from torchvision repo.

**Comment by garymm** [comment]
CC @BowenBao

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@garymm don't see any problem importing it into from the regular PR

**Comment by garymm** [comment]
I was told of the earlier failures by @BowenBao who was probably told by someone else, so maybe it was just a miscommunication or misunderstanding.
@malfet please merge when ready.

**Pull request closed without merging**
