### PR TITLE
switch back to checkout/v2

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #71045

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by suo** [comment]
@malfet why do we think that we no longer need retries on checkout?

**Comment by seemethere** [comment]
> Merge failed due to Command '['git', '-C', '/home/runner/work/pytorch/pytorch', 'push', 'origin', 'master']' returned non-zero exit status 1.

wat

**Comment by malfet** [comment]
> Merge failed due to Command '['git', '-C', '/home/runner/work/pytorch/pytorch', 'push', 'origin', 'master']' returned non-zero exit status 1.

Here is the link to the workflow run, same mysterious "fatal error in commit_refs  " https://github.com/pytorch/pytorch/runs/4929363429?check_suite_focus=true

**Review by janeyx99 — APPROVED** [review]

**Comment by suo** [comment]
Closing for now since we still want retries

**Pull request closed without merging**
