### PR TITLE
Simplify some TH codegen by moving code out of the switch and killing dead code.

### PR DESCRIPTION
**Pull request by gchanan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#32888 Simplify some TH codegen by moving code out of the switch and killing dead code.**

This kills ~1500 lines of generated code by doing the following:
1) Stop binding _th_clone, which isn't used anymore.

2) Move allocation code out of the switch, because it doesn't need to be there, example:
Now:
```
auto dispatch_scalar_type = infer_scalar_type(self);
auto result_ = c10::make_intrusive<TensorImpl, UndefinedTensorImpl>(c10::Storage(scalarTypeToTypeMeta(dispatch_scalar_type), 0, allocator(), true),DispatchKey::CPUTensorId).release();
auto result = Tensor(c10::intrusive_ptr<TensorImpl, UndefinedTensorImpl>::reclaim(result_));
switch (dispatch_scalar_type) {
    case ScalarType::Bool: {
        ...
    case ScalarType::Byte: {
	    ...
```
Before:
```
auto dispatch_scalar_type = infer_scalar_type(self);
switch(dispatch_scalar_type) {
    case ScalarType::Bool: {
       	auto result_ = c10::make_intrusive<TensorImpl, UndefinedTensorImpl>(caffe2::TypeMeta::Make<bool>(), 0, allocator(), true),DispatchKey::CPUTensorId).release();
        auto result = Tensor(c10::intrusive_ptr<TensorImpl, UndefinedTensorImpl>::reclaim(result_));
    case ScalarType::Byte: {
        auto result_ = c10::make_intrusive<TensorImpl, UndefinedTensorImpl>(caffe2::TypeMeta::Make<byte>(), 0, allocator(), true),DispatchKey::CPUTensorId).release();
        auto result = Tensor(c10::intrusive_ptr<TensorImpl, UndefinedTensorImpl>::reclaim(result_));
```

Note there's one extra lookup from ScalarType -> TypeMeta, but that can go away once we are able to put everything in a dispatch macro.

3) Prepare for more moves out of the switch by using dispatch_scalar_type where we would have used an explicit ScalarType::Name
More moves are currently blocked by "real" types needing to map scalar_type -> C++ type.  Dispatch macros can solve that, but I'll need to wrap the actual TH calls in templates so the entire
thing can be done via dispatch.

4) Kill some codegen that isn't used anymore: ALLOC_WRAP, is_actual_return_long.

Differential Revision: [D19672613](https://our.internmc.facebook.com/intern/diff/D19672613)

### CODE REVIEW

**Review by bhosmer — APPROVED** [review]
One question, IIRC `scalarTypeToTypeMeta()` is/was a perf issue, @smessmer is that still the case? If so, is it worth checking the perf of this?

**Comment by gchanan** [comment]
I'd be interested in that answer, although I'm not sure it really matters for TH functions (there are way fewer than there are native functions and we should optimize the hot path).

Worst case we can just leave this in a stack until we can put the entire thing in a dispatch macro and the problem will go away.

**Comment by bhosmer** [comment]
Yeah agreed. I just looked at the code and it seems innocuous, but I'll ping Sebastian.

**Comment by gchanan** [comment]
I'm also pretty sure this method of constructing a tensor is faster than the normal path (at::empty) because you avoid a dispatch, at the cost of some pretty ugly code:
```
auto result_ = c10::make_intrusive<TensorImpl, UndefinedTensorImpl>(c10::Storage(scalarTypeToTypeMeta(dispatch_scalar_type), 0, allocator(), true),DispatchKey::CPUTensorId).release();
auto result = Tensor(c10::intrusive_ptr<TensorImpl, UndefinedTensorImpl>::reclaim(result_));
```

**Comment by bhosmer** [comment]
> I'm also pretty sure this method of constructing a tensor is faster than the normal path (at::empty) because you avoid a dispatch, at the cost of some pretty ugly code:
> 
> ```
> auto result_ = c10::make_intrusive<TensorImpl, UndefinedTensorImpl>(c10::Storage(scalarTypeToTypeMeta(dispatch_scalar_type), 0, allocator(), true),DispatchKey::CPUTensorId).release();
> auto result = Tensor(c10::intrusive_ptr<TensorImpl, UndefinedTensorImpl>::reclaim(result_));
> ```

One note on this - @eellison's idea for getting global default type into the JIT side relies on everybody routing through `at::empty`, will this bypass?

Totally OT but I think one thing I'm going to start doing in the heavily templatized stuff is putting any nontrivial arg expression into a local, so like in that thing
```
auto type_meta = scalarTypeToTypeMeta(dispatch_scalar_type);
auto storage = c10::Storage(typemeta, 0, allocator(), true);
auto dispatch_key = DispatchKey::CPUTensorId;
auto released = c10::make_intrusive<TensorImpl, UndefinedTensorImpl>(storage, dispatch_key).release();
auto reclaimed = c10::intrusive_ptr<TensorImpl, UndefinedTensorImpl>::reclaim(released);
auto result = Tensor(reclaimed);
```
Both so I can stay sane reading it but also I think it's going to make it easier to spot perf sinkholes...

**Comment by gchanan** [comment]
> One note on this - @eellison's idea for getting global default type into the JIT side relies on everybody routing through at::empty, will this bypass?

I'm not up-to-date on what this plan is, what's the "global default type"?  To answer the specific question, this doesn't go through `at::empty`.

> Totally OT but I think one thing I'm going to start doing in the heavily templatized stuff is putting any nontrivial arg expression into a local, so like in that thing

that's fine with me :).  My goal here is to make the binding code able to be handwritten (even if it actually isn't in practice -- open question).  So anything that moves this toward "what a human would write" is fine with me.

**Comment by gchanan** [comment]
```
auto type_meta = scalarTypeToTypeMeta(dispatch_scalar_type);
auto storage = c10::Storage(typemeta, 0, allocator(), true);
auto dispatch_key = DispatchKey::CPUTensorId;
auto released = c10::make_intrusive<TensorImpl, UndefinedTensorImpl>(storage, dispatch_key).release();
auto reclaimed = c10::intrusive_ptr<TensorImpl, UndefinedTensorImpl>::reclaim(released);
auto result = Tensor(reclaimed);
```

BTW I think all the above code could be changed to something like the following with the cost of one additional dispatch:
```
auto result = at::empty({0}, at::dtype(infer_scalar_type).device(at:kCPU));
```
modulo tensoroptions-vs-not and `at:::` vs `torch::` questions.

**Comment by bhosmer** [comment]
> > One note on this - @eellison's idea for getting global default type into the JIT side relies on everybody routing through at::empty, will this bypass?
> 
> I'm not up-to-date on what this plan is, what's the "global default type"? To answer the specific question, this doesn't go through `at::empty`.
> 

Ah sorry, sloppy wording. Basically the eager bindings will use the scalar type set by `torch::set_default_tensor_type` if none is passed: https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/python_arg_parser.h#L346. There's no equivalent logic on the JIT side, so `at::empty` seemed like a choke point where we could move the defaulting behavior, instead of having to actually push it down to each op individually.

**Comment by bhosmer** [comment]
> 
> BTW I think all the above code could be changed to something like the following with the cost of one additional dispatch:
> 
> ```
> auto result = at::empty({0}, at::dtype(infer_scalar_type).device(at:kCPU));
> ```
> 
> modulo tensoroptions-vs-not and `at:::` vs `torch::` questions.

I mean, where do I sign, but I don't know what the perf cost of the additional dispatch would be.

**Comment by gchanan** [comment]
> There's no equivalent logic on the JIT side, so at::empty seemed like a choke point where we could move the defaulting behavior, instead of having to actually push it down to each op individually.

maybe?  You'd have to check if e.g. sparse would do the correct thing.  I'm not even sure what those semantics would mean on the JIT side -- does that mean I can script a module and change how it behaves at runtime later by setting the dtype?

> I mean, where do I sign, but I don't know what the perf cost of the additional dispatch would be.

I'd argue we should just do it, because no one writes native_functions the long way because it is too painful.  Alternatively, we could encode a specific `at::native::empty` implementation to use(this is how native_functions today avoid dispatch), which should have no cost.

**Comment by smessmer** [comment]
`scalarTypeToTypeMeta` perf does matter in micro benchmarks but likely doesn't matter for TH

**Comment by gchanan** [comment]
@smessmer thanks for the insight.  I'll land this now but fix this up ASAP.

**Pull request closed without merging**
