### PR TITLE
Require bias to be contiguous for depthwise3x3_winograd backend

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #85849
* #79056
* __->__ #85711

Fixes https://github.com/pytorch/pytorch/issues/85694

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
This would likely have some perf implications, can we for a sign off from PyTorch Mobile team?
cc: @raziel

**Comment by albanD** [comment]
Ho sorry, my comment was to disable this for M1 only!
We most likely don't want to do that for mobile for sure (even though it is a pretty big risk of silent correctness).

**Comment by raziel** [comment]
> This would likely have some perf implications, can we for a sign off from PyTorch Mobile team? cc: @raziel

I don't think winograd is used in mobile. @kimishpatel ?

**Comment by kimishpatel** [comment]
> imagine

What is the motivation for this diff?

But @raziel is right. For the most part on mobile our suggestion is optimize_for_mobile which directs fp32 convs to xnnpack. In case optimize_for_mobile fails, this might the fallback path but even there are other conditions gating it. So this seem safe.

**Comment by albanD** [comment]
> What is the motivation for this diff?

You can see the linked issue. There are cases where this kernel gets picked up but does not return the right result. So I guess that we need to restrict even more how when it is used.
Given that we don't have bandwidth to dive into the kernel again to figure out why it is failing, a simpler solution is to stop using it on M1.

But if you're not using it either on the mobile side, I think we would be fine to remove it altogether, would that work for you?

**Comment by kimishpatel** [comment]
> > What is the motivation for this diff?
> 
> You can see the linked issue. There are cases where this kernel gets picked up but does not return the right result. So I guess that we need to restrict even more how when it is used. Given that we don't have bandwidth to dive into the kernel again to figure out why it is failing, a simpler solution is to stop using it on M1.
> 
> But if you're not using it either on the mobile side, I think we would be fine to remove it altogether, would that work for you?

Ok to remove it altogether. I highly doubt that we ever take this path on mobile side.

**Comment by kimishpatel** [comment]
And sorry, missed the linked issue. Its like deliberately trying to hide in the corner ;). So didnt spot.

**Comment by soulitzer** [comment]
it seems like this change is okay from the mobile side @malfet, should we proceed with removal? or did you plan to dig deeper into the implementation for a proper fix as suggested in https://github.com/pytorch/pytorch/issues/85694#issuecomment-1259730863

**Review by malfet — APPROVED** [review]
Sounds good to me, though I still wonder if there are any performance implications

**Comment by soulitzer** [comment]
I measured the slow down and it was quite significant (2x). After looking more into the issue, I now believe the issue is because bias is not contiguous. See the linked issue for a repro.

Instead of removing the backend, this PR now adds an additional condition to also check that bias is contiguous.

**Review by albanD — APPROVED** [review]
Thanks for taking the time to look into this :)

**Comment by soulitzer** [comment]
I've updated this PR to include the changes from https://github.com/pytorch/pytorch/pull/86142

**Pull request closed without merging**
