### PR TITLE
Respect ROCR_VISIBLE_DEVICES on AMD GPU device discovery

### LINKED ISSUE #140318: Visible devices are not respected on AMD systems
### 🐛 Describe the bug

When running distributed (or multi-process) jobs on AMD GPU systems with GPU isolation (i.e., the `*_VISIBLE_DEVICES` environment variable), PyTorch still tries to set the seed of all the devices it finds. This causes the following exception to be raised:

```
File "/path/to/torch/random.py", line 46, in manual_seed                                                                                               
  torch.cuda.manual_seed_all(seed)                                                                                                                                                                      
File "/path/to/torch/cuda/random.py", line 131, in manual_seed_all                                                                                    
  _lazy_call(cb, seed_all=True)                                                                                                                                                                        
File "/path/to/torch/cuda/__init__.py", line 249, in _lazy_call                                                                                       
  callable()                                                                                                                                                                                            
File "/path/to/torch/cuda/random.py", line 128, in cb                                                                                                  
  default_generator = torch.cuda.default_generators[i]                                                                                                                                                 
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^                                                                                                                                                 
IndexError: tuple index out of range
```

The underlying issue is that the visible devices are not properly detected due to reading the wrong environment variable name: `HIP_VISIBLE_DEVICES` should be renamed to `ROCR_VISIBLE_DEVICES` (see https://rocm.docs.amd.com/en/latest/conceptual/gpu-isolation.html#rocr-visible-devices ). On many batch schedulers and clusters, the ROCr environment variable is the one that is set.

This was likely introduced in #119182 (cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd)

I will push a pull request to fix this later today.

### Versions

PyTorch version: 2.5.1+rocm6.2

### PR DESCRIPTION
**Pull request by tbennun**
Fixes #140318

### CODE REVIEW

**Comment by jataylo** [comment]
I left a more extended comment here https://github.com/pytorch/pytorch/issues/140318#issuecomment-2470406280

I'm not sure adding ROCR_VISIBLE_DEVICES to the `_parse_visible_devices` logic is a true fix here, I think this is a workaround. That being said there does appear to be issues with the current implementation more details in issue above.

**Comment by jataylo** [comment]
Added a new PR here https://github.com/pytorch/pytorch/pull/140398

Which will ensure interoperability between the two visible devices

**Review by eqy — APPROVED** [review]

**Review by jithunnair-amd — APPROVED** [review]
Looks right. @tbennun can you please post some examples showing what the updated logic gives as output of `_parse_visible_devices()`?

**Comment by tbennun** [comment]
> Looks right. @tbennun can you please post some examples showing what the updated logic gives as output of `_parse_visible_devices()`?

@jithunnair-amd Of course, essentially now PyTorch takes `ROCR_VISIBLE_DEVICES` into account the same way it would with `CUDA_VISIBLE_DEVICES`.

@jataylo already gave some examples in https://github.com/pytorch/pytorch/issues/140318#issuecomment-2470406280 so I can start from there.

Would you like this in the form of a test with, e.g., `ROCR_VISIBLE_DEVICES=0,3,4` and `HIP_VISIBLE_DEVICES=1,2`?
I will use this opportunity to fix the mypy issue too.

**Comment by tbennun** [comment]
@jithunnair-amd @jataylo please re-review. I added tests, fixed the linter issue, and improved the behavior when both environment variables are given. Thanks!

**Comment by tbennun** [comment]
@jithunnair-amd @jataylo Any updates on this PR? Thanks!

**Comment by jataylo** [comment]
LGTM cc: @jeffdaily

**Review by jataylo — APPROVED** [review]

**Review by jeffdaily — APPROVED** [review]

**Comment by tbennun** [comment]
The failures seem unrelated to this PR and related to the version of distutils.

**Comment by jataylo** [comment]
Rebasing to see if unrelated errors go away :)

**Comment by tbennun** [comment]
> Rebasing to see if unrelated errors go away :)

@jataylo looks like they did :)

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but test_hip_device_count is failing in trunk after this land' -c nosignal

test_cuda.py::TestCuda::test_hip_device_count [GH job link](https://github.com/pytorch/pytorch/actions/runs/12205445217/job/34054167909) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/add4a42ea2c56f7687a3564aefe9e017cd118936)

**Comment by tbennun** [comment]
> @pytorchbot revert -m 'Sorry for reverting your change but test_hip_device_count is failing in trunk after this land' -c nosignal
> 
> test_cuda.py::TestCuda::test_hip_device_count [GH job link](https://github.com/pytorch/pytorch/actions/runs/12205445217/job/34054167909) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/add4a42ea2c56f7687a3564aefe9e017cd118936)

@huydhn Thanks. The test passed locally, I will check. 

Strange that it didn't show up in the tests. Are rocm tests not running on PRs? If not, is there a way I can trigger them?

**Comment by huydhn** [comment]
It could be an issue with our target determination when some tests were wrongly skipped.  Let me double check that, but you could add`ci-no-td` on your PR to opt-out and this will ensure that all tests are run on your reland PR

**Comment by huydhn** [comment]
It doesn't looks like the case, I think you just need to add `ciflow/rocm` to run all ROCm tests then.

**Comment by tbennun** [comment]
Turns out the rocm tests did run (and terminated successfully) before: https://github.com/pytorch/pytorch/actions/runs/12199014152/job/34033407881#step:15:961

**Comment by jataylo** [comment]
@tbennun I wonder if it has anything to do with the CI jobs setting HIP_VISIBLE_DEVICES=0 at runtime then us trying to set ROCR_VISIBLE_DEVICES=0,1,2 at runtime. 

The application may only see a single GPU and then try to set device_count to 3. Might need some local testing to try and reproduce.

**Comment by tbennun** [comment]
@jataylo it might be, which is why I made sure to remove the environment variable, like other tests do, in the reland PR (#142292). What’s weird is that it passed on the PR build but not on main afterwards. Regardless, the new PR should resolve potential index errors.

**Pull request closed without merging**
