### PR TITLE
[SymmetricMemory] introduce multicast support, multimem_all_reduce_ and multimem_one_shot_all_reduce

### PR DESCRIPTION
**Pull request by yifuwang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #133424

### Summary
- Added multicast support to SymmetricMemory. If the cuda runtime and cuda driver have multicast support, SymmetricMemory associate all peer buffers with a multicast object and exposes the multicast virtual address.
- Implemented `multimem_all_reduce_` and `multimem_one_shot_all_reduce` based on the multicast support. The two variants shows different performance characteristic for different message size. We plan to use Inductor for collective algo selection (and required symmetric memory buffer allocation).

### Benchmark

8xH100 (non-standard version with HBM2e at 650W). NVSwitch V3 with NVLS support.

image

image

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

Differential Revision: [D61682507](https://our.internmc.facebook.com/intern/diff/D61682507)

### CODE REVIEW

**Comment by yifuwang** [comment]
@syed-ahmed

> For the second chart, is the speedup compared to NCCL's multicast all_reduce?

No this is comparing with NCCL's ring all_reduce. Let me update the graph description.

> If not, I'm curious to see how this diff performs compared to NCCL's multicast support.

I've not had the chance to benchmark it, but I'd guess they'd have similar performance characteristics.

> If you were not aware, nccl all_reduce has multicast support when the reduction tensor is allocated using ncclMemAlloc and registered using ncclCommRegister.

Thanks! We are aware of this and plan to make Inductor auto allocate ncclCommRegister'd buffers to NCCL collectives.

**Review by yf225 — APPROVED** [review]

**Review by weifengpy — APPROVED** [review]

**Comment by yifuwang** [comment]
@yifuwang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61682507).

**Comment by yifuwang** [comment]
@yifuwang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D61682507).

**Pull request closed without merging**
