### PR TITLE
[BE]: Apply PERF401 autofixes from ruff

### PR DESCRIPTION
**Pull request by Skylion007**
* Automatically applies ruff rule 401. Turns loops into equivalent list comprehensions which are faster and do not leak the scope of the loop variables.
* list comprehensions not only often have better typing, but are 50+% faster than for loops on overhead. They also preserve length information etc and are better for the interpreter to optimize.
* Manually went back and made mypy happy after the change. 
* Also fixed style lints in files covered by flake8 but not by pyfmt

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @ezyang @SherlockNoMad @voznesenskym @penguinwu @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @LucasLLC @MeetVadakkanchery @mhorowitz @pradeepfn @xmfan

### CODE REVIEW

**Review by justinchuby — APPROVED** [review]

**Review by malfet — COMMENTED** [review]
LGTM, let's try to merge it (and hopefully no land races)

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
