### PR TITLE
[quant][graphmode][api] debug --> output_a_reference_model

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #52316 [quant] Reference option for conv module
* **#52179 [quant][graphmode][api] debug --> output_a_reference_model**

Summary:
Rename debug to reference. We'll use this to produce a reference quantized model
that can be used as a common interface between pytorch quantized model and backends.

Test Plan:
python test/test_quantization.py TestQuantizeFx

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D26424656](https://our.internmc.facebook.com/intern/diff/D26424656)

### CODE REVIEW

**Comment by vkuzo** [comment]
Thoughts about something like `is_reference`, `is_reference_model`, etc, just to make it clearer?

I don't feel super strongly though, `reference` makes sense too.

**Comment by jerryzh168** [comment]
I feel `is_reference` is referring to input typically, `output_reference_model` is probably the one that makes most sense, shall we use that?

**Comment by vkuzo** [comment]
Makes sense, maybe `is_output_reference_model` then?  `output_reference_model` sounds like a model object, would be nice if the name made it obvious that this is a boolean.

**Comment by jerryzh168** [comment]
> Makes sense, maybe `is_output_reference_model` then? `output_reference_model` sounds like a model object, would be nice if the name made it obvious that this is a boolean.

yeah there are definitely different interpretations, by `output_reference_model` I actually mean "output a reference model" or "return a reference model". I think it's hard to have the name just to reflect what it exactly does, people will need to read the doc anyways. I plan to keep the original name "reference" if you are OK with that.

**Comment by vkuzo** [comment]
> yeah there are definitely different interpretations, by output_reference_model I actually mean "output a reference model" or "return a reference model". I think it's hard to have the name just to reflect what it exactly does, people will need to read the doc anyways. I plan to keep the original name "reference" if you are OK with that.

I'll accept it, but to me `reference` is really confusing, tbh (similar how `debug` was also confusing).  In the future, might be good to do a poll of users of this code to see which name is the easiest for them to understand.

**Review by vkuzo — APPROVED** [review]

**Comment by vkuzo** [comment]
> I actually mean "output a reference model" or "return a reference model"

I think `output_a_reference_model`, from your sentence above, would be a much better name :)

**Comment by jerryzh168** [comment]
actually I still feel reference is better, maybe I can use `is_reference` to indicate it's a boolean?

**Pull request closed without merging**
