### PR TITLE
add channels last support for thnn_conv2d (non-dilated)

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74023
* #70897
* #70665
* __->__ #68101
* #58348
* #55864

Differential Revision: [D33571074](https://our.internmc.facebook.com/intern/diff/D33571074)

### CODE REVIEW

**Comment by mingfeima** [comment]
This one is a replacement of #49582, updates:
* use `cpublas::gemm` on channels last path
* channel last path and channels first path has the same parallel scheme, therefore the overall code structure is simpler than #49582, and the major difference of channels first and channels last is parameter change in gemm.


the old performance compare is [here](https://github.com/pytorch/pytorch/pull/49582#issuecomment-748928859).

the following is an update:

input size | output channels | kernel | stride | padding | groups | before (nchw) | after (nchw) | after (nhwc)
-- | -- | -- | -- | -- | -- | -- | -- | --
[1,3,224,224] | 64 | 7 | 2 | 3 | 1 | 4.166 | 4.099 | 4.518
[1,64,56,56] | 128 | 1 | 1 | 0 | 1 | 0.324 | 0.320 | 0.342
[1,128,56,56] | 128 | 3 | 1 | 1 | 32 | 1.535 | 1.508 | 7.784
[1,128,56,56] | 256 | 1 | 1 | 0 | 1 | 1.182 | 1.104 | 1.141
[1,64,56,56] | 256 | 1 | 1 | 0 | 1 | 0.757 | 0.757 | 0.772
[1,256,56,56] | 128 | 1 | 1 | 0 | 1 | 0.985 | 0.983 | 1.068
[1,128,56,56] | 128 | 3 | 1 | 1 | 32 | 1.524 | 1.507 | 7.804
[1,128,56,56] | 256 | 1 | 1 | 0 | 1 | 1.104 | 1.108 | 1.138
[1,256,56,56] | 128 | 1 | 1 | 0 | 1 | 0.979 | 0.979 | 1.069
[1,128,56,56] | 128 | 3 | 1 | 1 | 32 | 1.521 | 1.510 | 7.796
[1,128,56,56] | 256 | 1 | 1 | 0 | 1 | 1.103 | 1.108 | 1.140
[1,256,56,56] | 256 | 1 | 1 | 0 | 1 | 2.044 | 2.046 | 2.117
[1,256,56,56] | 256 | 3 | 2 | 1 | 32 | 3.880 | 3.845 | 3.443
[1,256,28,28] | 512 | 1 | 1 | 0 | 1 | 1.045 | 1.043 | 1.061
[1,256,56,56] | 512 | 1 | 2 | 0 | 1 | 1.362 | 1.363 | 1.136
[1,512,28,28] | 256 | 1 | 1 | 0 | 1 | 1.032 | 1.034 | 1.092
[1,256,28,28] | 256 | 3 | 1 | 1 | 32 | 1.141 | 1.110 | 2.568
[1,256,28,28] | 512 | 1 | 1 | 0 | 1 | 1.050 | 1.041 | 1.060
[1,512,28,28] | 256 | 1 | 1 | 0 | 1 | 1.034 | 1.035 | 1.099
[1,256,28,28] | 256 | 3 | 1 | 1 | 32 | 1.147 | 1.111 | 2.566
[1,256,28,28] | 512 | 1 | 1 | 0 | 1 | 1.041 | 1.042 | 1.060
[1,512,28,28] | 256 | 1 | 1 | 0 | 1 | 1.037 | 1.032 | 1.097
[1,256,28,28] | 256 | 3 | 1 | 1 | 32 | 1.199 | 1.112 | 2.570
[1,256,28,28] | 512 | 1 | 1 | 0 | 1 | 1.041 | 1.062 | 1.066
[1,512,28,28] | 512 | 1 | 1 | 0 | 1 | 2.010 | 1.992 | 2.073
[1,512,28,28] | 512 | 3 | 2 | 1 | 32 | 2.065 | 2.040 | 1.266
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.175 | 1.193 | 1.124
[1,512,28,28] | 1024 | 1 | 2 | 0 | 1 | 1.342 | 1.332 | 1.167
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.217 | 1.230 | 1.151
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.142 | 1.135 | 1.022
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.178 | 1.175 | 1.122
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.217 | 1.219 | 1.153
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.138 | 1.129 | 1.016
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.176 | 1.175 | 1.132
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.217 | 1.217 | 1.150
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.141 | 1.135 | 1.020
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.173 | 1.177 | 1.123
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.216 | 1.216 | 1.158
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.146 | 1.134 | 1.024
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.176 | 1.175 | 1.122
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.215 | 1.220 | 1.152
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.145 | 1.133 | 1.025
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.176 | 1.176 | 1.120
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.216 | 1.217 | 1.157
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.143 | 1.135 | 1.018
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.173 | 1.173 | 1.143
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.214 | 1.221 | 1.148
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.143 | 1.133 | 1.032
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.233 | 1.177 | 1.127
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.220 | 1.217 | 1.170
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.154 | 1.133 | 1.018
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.175 | 1.175 | 1.135
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.223 | 1.220 | 1.152
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.141 | 1.140 | 1.047
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.176 | 1.177 | 1.120
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.221 | 1.219 | 1.170
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.141 | 1.131 | 1.021
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.174 | 1.171 | 1.142
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.217 | 1.219 | 1.153
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.141 | 1.133 | 1.037
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.171 | 1.173 | 1.124
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.216 | 1.226 | 1.174
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.140 | 1.131 | 1.024
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.175 | 1.177 | 1.136
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.219 | 1.219 | 1.152
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.138 | 1.138 | 1.036
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.180 | 1.173 | 1.122
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.214 | 1.221 | 1.167
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.141 | 1.130 | 1.022
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.172 | 1.185 | 1.143
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.276 | 1.218 | 1.155
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.210 | 1.139 | 1.033
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.229 | 1.175 | 1.119
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.281 | 1.230 | 1.167
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.209 | 1.135 | 1.026
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.236 | 1.177 | 1.135
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.271 | 1.218 | 1.157
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.147 | 1.154 | 1.070
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.176 | 1.232 | 1.181
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.218 | 1.274 | 1.209
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.152 | 1.192 | 1.071
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.174 | 1.232 | 1.179
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.217 | 1.272 | 1.209
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.140 | 1.193 | 1.078
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.179 | 1.230 | 1.179
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.215 | 1.236 | 1.151
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.156 | 1.135 | 1.026
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.185 | 1.189 | 1.122
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.216 | 1.216 | 1.153
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.159 | 1.149 | 1.021
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.181 | 1.179 | 1.123
[1,1024,14,14] | 512 | 1 | 1 | 0 | 1 | 1.215 | 1.235 | 1.153
[1,512,14,14] | 512 | 3 | 1 | 1 | 32 | 1.144 | 1.139 | 1.041
[1,512,14,14] | 1024 | 1 | 1 | 0 | 1 | 1.179 | 1.187 | 1.126
[1,1024,14,14] | 1024 | 1 | 1 | 0 | 1 | 2.321 | 2.328 | 2.275
[1,1024,14,14] | 1024 | 3 | 2 | 1 | 32 | 1.507 | 1.491 | 1.012
[1,1024,7,7] | 2048 | 1 | 1 | 0 | 1 | 1.573 | 1.581 | 1.733
[1,1024,14,14] | 2048 | 1 | 2 | 0 | 1 | 1.660 | 1.697 | 1.746
[1,2048,7,7] | 1024 | 1 | 1 | 0 | 1 | 1.610 | 1.636 | 1.758
[1,1024,7,7] | 1024 | 3 | 1 | 1 | 32 | 1.265 | 1.245 | 0.898
[1,1024,7,7] | 2048 | 1 | 1 | 0 | 1 | 1.594 | 1.579 | 1.729
[1,2048,7,7] | 1024 | 1 | 1 | 0 | 1 | 1.607 | 1.618 | 1.741
[1,1024,7,7] | 1024 | 3 | 1 | 1 | 32 | 1.279 | 1.241 | 0.907
[1,1024,7,7] | 2048 | 1 | 1 | 0 | 1 | 1.567 | 1.597 | 1.735

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33571074).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33571074).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33571074).

**Comment by mingfeima** [comment]
clear unused variable warning.

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33571074).

**Pull request closed without merging**
