### PR TITLE
Change name for namedtuple return of torch.linalg.svd

### PR DESCRIPTION
**Pull request by IvanYashchuk**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#57181 Change name for namedtuple return of torch.linalg.svd**
* #57180 Remove compute_uv flag from torch.linalg.svd

Documentation for torch.linalg.svd says:
> The returned decomposition is a named tuple `(U, S, Vh)`

The documentation is correct while the implementation was wrong.
Renamed `V` -> `Vh`. `h` stands for hermitian.
This is a BC-breaking change but our linalg module is beta, therefore we can do it without a deprecation notice or aliases.

Differential Revision: [D28142162](https://our.internmc.facebook.com/intern/diff/D28142162)

### CODE REVIEW

**Comment by ezyang** [comment]
I guess if we care about BC we should figure out a way to define aliases to fields on the returned named tuple.

**Comment by mruberry** [comment]
> I guess if we care about BC we should figure out a way to define aliases to fields on the returned named tuple.

Luckily this module is in BETA.

**Review by mruberry — APPROVED** [review]
I'm surprised this didn't trigger a back compat failure; the fix looks good, though

**Comment by IvanYashchuk** [comment]
It didn't trigger the failure because the previous PR in the stack adds linalg_svd entry to allowlist in check_backward_compatibility.py

**Comment by mruberry** [comment]
This is now unblocked, but it needs a rebase - just ping me on the rebase and we'll get it merged ASAP, @IvanYashchuk

**Comment by IvanYashchuk** [comment]
@mruberry, I rebased this stack.

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28142162).

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28142162).

**Pull request closed without merging**
