### PR TITLE
Int4MM: Unswizzle for different dtypes

### PR DESCRIPTION
**Pull request by malfet**
If dtype is not the one this platform is optimized for, it might need different unswizzling pattenrs Implement ones for non-vectorized flavor of the kernel, so that int4mm can be used with float32 and float16 dtypes

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
Is this change covered by any UT?

**Review by mikekgfb — APPROVED** [review]
Thank you!

**Comment by malfet** [comment]
> Is this change covered by any UT?

Good point, let me add some

**Pull request closed without merging**
