### PR TITLE
[aotinductor] Add helper fn to atomically apply size_hint to an expr w/ unbacked symints

### PR DESCRIPTION
**Pull request by ColinPeppler**
### Context
Fixes CUDA IMA in autotune_at_compile_time, where we would generate an example tensor with an incorrect stride. 

In the case below, the stride should be (u0 * 128, 128, 1). However, we apply the fallback on the entire expr (i.e. u0 * 128).
```
# buf817 = tensor(size=(s0, u0, 128), stride=(u0 * 128, 128, 1))

buf812 = generate_example_value(
    (64, 8192, 128), (8192, 128, 1), "cuda:0", torch.bfloat16, 0
)
```

The fix is to apply the fallback on each symbol.

### Test
```
PYTORCH_NO_CUDA_MEMORY_CACHING=1 compute-sanitizer python test_aot_inductor.py -k test_stride_with_unbacked_expr_abi_compatible_cuda

========= Invalid __global__ write of size 2 bytes
```

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137537

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @amjames @desertfire @chauhang @rec

Differential Revision: [D64074561](https://our.internmc.facebook.com/intern/diff/D64074561)

### CODE REVIEW

**Comment by ColinPeppler** [comment]
@ColinPeppler has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64074561).

**Review by jingsh — APPROVED** [review]
Thanks for the fix!

lgtm

**Comment by ColinPeppler** [comment]
basic_gnn_gcn previously failed due to device-side assertion. With this PR, it passes. Updated PR to reflect that in CI.
basic_gnn_gcn                       IMPROVED: accuracy=pass, expected=fail_to_run

```
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1215, in preserve_rng_state
    yield
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 862, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1961, in compile_to_fn
    return AotCodeCompiler.compile(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 1941, in compile
    serialized_weights = b"".join(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 1942, in <genexpr>
    _to_bytes(graph.get_original_value_of_constant(name), all_cuda)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 1930, in _to_bytes
    t_cpu = t.untyped_storage().cpu()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/storage.py", line 254, in cpu
    return torch.UntypedStorage(self.size()).copy_(self, False)
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by ColinPeppler** [comment]
@ColinPeppler has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64074561).

**Pull request closed without merging**
