### PR TITLE
reenable 11.2

### LINKED ISSUE #51980: CUDA error: misaligned address on CUDA 11.2 on Windows on torch.where complex128
## 🐛 Bug

Discovered in https://github.com/pytorch/pytorch/pull/51598, the failing test is `test_where_scalar_valid_combination_cuda_complex128 `

Minumum repro is:

```python
import torch

x = torch.randn(5, 5, 5, dtype=torch.cdouble, device='cuda')
cond = torch.zeros_like(x, dtype=torch.bool)
torch.where(cond, x, complex(0.0))
```

Fails with

```python
Traceback (most recent call last):
  File "test/where.py", line 5, in <module>
    torch.where(cond, x, complex(0.0))
RuntimeError: CUDA error: misaligned address
```

## Environment

```
Collecting environment information...
PyTorch version: 1.8.0a0+dac730a
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.17.0-rc1

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 461.40
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.8.0a0+dac730a
[conda] Could not collect
```

cc @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489 @janeyx99 @ptrblck @xwang233

### PR DESCRIPTION
**Pull request by mszhanyi**
Fixes #51980

### CODE REVIEW

**Comment by janeyx99** [comment]
This looks good, but to make sure, is it possible for you to run ci/all on a ci-all/ branch (not your fork) as the 11.2 CI build + tests are run on master only branches?

**Review by seemethere — COMMENTED** [review]
We're not actively looking towards getting CUDA 11.2 binaries back into our nightly matrix due to performance concerns.

Going to go ahead and say we should punt on this until there is movement for CUDA 11.3+

I'd say I'm fine with re-enabling the tests and updating the CUDA installer but we should not be re-enabling CUDA 11.2 nightly binaries

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Looks good to me, though I wonder if it'll be better to change scheduling for both Linux and Windows 11.2 jobs to periodic

**Comment by janeyx99** [comment]
> Looks good to me, though I wonder if it'll be better to change scheduling for both Linux and Windows 11.2 jobs to periodic.

Both the CI for 11.2 are already in periodic workflow, so this PR doesn't need to change that.

**Pull request closed without merging**
