### PR TITLE
adding Flatten in nn/modules/__init__.py

### LINKED ISSUE #36915: Flatten in nn/modules/__init__.pyi
## To Reproduce

1. `import torch.nn as nn`
2. `nn.` does not pop up `Flatten` (I mean autocomplete)

I also noticed that `from .flatten import Flatten` is missing from `nn/modules/__init__.pyi`. I am not sure if this is a bug.

I am using PyCharm.

## Environment
```
PyTorch version: 1.6.0.dev20200419+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1
OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect
Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: D:\Program Files\NVIDIA\CUDA\v10.0\bin\cudnn64_7.dll
Versions of relevant libraries:
[pip3] numpy==1.18.1
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] torch                     1.6.0.dev20200419+cu101          pypi_0    pypi
[conda] torchvision               0.7.0.dev20200419+cu101          pypi_0    pypi
```

cc @ezyang

### PR DESCRIPTION
**Pull request by jerryc05**
Trying to fix #36915

### CODE REVIEW

**Comment by albanD** [comment]
Does that fix the auto-complete fine on your side?

**Comment by albanD** [comment]
Note that you can also add a test here to make sure it still works: https://github.com/pytorch/pytorch/blob/master/test/test_type_hints.py

**Comment by jerryc05** [comment]
> Does that fix the auto-complete fine on your side?

Yes it does

**Comment by jerryc05** [comment]
> Note that you can also add a test here to make sure it still works: https://github.com/pytorch/pytorch/blob/master/test/test_type_hints.py

Hmm. I looked into it but still did not know how to "add" a new test for it.

**Comment by jerryc05** [comment]
Also noticed that `Hardsigmoid` and `Hardswish` are probably not correctly configured in `pyi` as well. Trying to fix them.

**Comment by rgommers** [comment]
> Note that you can also add a test here to make sure it still works: https://github.com/pytorch/pytorch/blob/master/test/test_type_hints.py

Note that `mypy` is now run on the whole code base in the test suite, and will be extended to run all tests with `--check-untyped-defs`, so adding a regular test using `nn.Flatten` (which looks like it's missing from `test_nn.py`) should probably be preferred over adding a specific type annotation test.

**Pull request closed without merging**
