### PR TITLE
Change view dispatch to abstract

### PR DESCRIPTION
**Pull request by li-roy**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #20309 Generate TH functions outside of Type
* **#20308 Change view dispatch to abstract**

Because the following PR will change native_functions that wrap TH to dispatch differently by backend, we will need to dispatch mkldnn `view` separately, which means the condition in this if statement will never be met. Removing it and dispatching `view` by backend preemptively to prepare for next PR.

Differential Revision: [D15509849](https://our.internmc.facebook.com/intern/diff/D15509849)

### CODE REVIEW

**Comment by colesbury** [comment]
Why? This seems to be heading to even more unnecessary hidden indirections. i.e. view could just be:

```
  if (self.is_mkldnn()) {	
    AT_ERROR("MKLDNN tensor does not support view. Use reshape instead");
  }	
  return at::legacy::th::_th_view(self, size);	// or better, the actual view implementation
```

but now it has two implementations (that both error out) for mkldnn_view and the code flow is defined by a YAML file instead of normal C++ control flow

**Comment by gchanan** [comment]
I'd also echo why -- there is no explanation for why this change is needed or what the context is.

**Comment by ezyang** [comment]
Pro-tip: if you edit the summary to add the explanation, don't forget to add a comment you did so, otherwise, no notifications will get generated.

**Comment by ezyang** [comment]
I spent a few minutes trying to puzzle out the meaning of

> Because the following PR will change native_functions that wrap TH to
> dispatch differently by backend, this needs to be done beforehand.

But I couldn't follow the line of logic. Some more detail would be appreciated.

(FWIW, I'm willing to give the benefit of the doubt here and approve this; in particular, there aren't really any indirections added, since you always had to do the virtual jump to get to this function in the first place. But 
I think a more detailed explanation will help convince others)

**Comment by li-roy** [comment]
updated description

**Review by ezyang — APPROVED** [review]
OK sure.

**Comment by ezyang** [comment]
Maybe try to get sign off from someone else too?

**Pull request closed without merging**
