### PR TITLE
Fix typo in tensor docs

### PR DESCRIPTION
**Pull request by axitkhurana**
Remove extra character from `torch.qfint32`

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]
thanks!

**Comment by suo** [comment]
The docs build failed on this PR. I am reverting.

**Comment by suo** [comment]
@axitkhurana @jerryzh168 feel free to follow up with a reland. Please be more careful in the future; the failure was quite clear from this PR and landing it broke master.

**Comment by axitkhurana** [comment]
@suo Sorry about that!

**Comment by jerryzh168** [comment]
ah sorry, I also assumed that this is just one character change and shouldn't affect other things, looks like the doc build is failed probably because of a missing space

**Pull request closed without merging**
