### PR TITLE
Move librosa and psutil installation from CI script to docker images build script

### PR DESCRIPTION
**Pull request by bddppq**
pip install librosa randomly coredump, causes CI flakiness

### CODE REVIEW

**Review by ssnl — COMMENTED** [review]
Maybe the process has changed since I last did this. Don't you need to deploy a new docker version for this to work?

**Comment by bddppq** [comment]
@SsnL Yes, new docker images were building https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/275/

**Comment by bddppq** [comment]
Triggered pytorch rocm CI jobs with new docker image:
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger/28944/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger/14238/

TODO: Check `test_stft` is still run in these jobs

**Review by ezyang — APPROVED** [review]

**Comment by bddppq** [comment]
New triggered rocm jobs:
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger/29006/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger/14299/

**Comment by bddppq** [comment]
@pytorchbot retest this please
New docker images are deployed in Jenkins

**Pull request closed without merging**
