### PR TITLE
Simplify env creation when running Windows tests

### LINKED ISSUE #13465: setup_pytorch_env.bat called multiple times in windows CI, slowing it down
open up the full log from a `test2` job, and search for setup_pytorch_env.bat - there are two occurences.

This is because in win-test.sh, we do 

```
ci_scripts/test_python_all_except_nn.bat && ci_scripts/test_custom_script_ops.bat
```

and each of those runs the setup script at the top.

bonus points if the environment setup is split out in a way that's convenient for iterative debugging (i.e. rerun tests N times without reinstalling python packages N times)

### PR DESCRIPTION
**Pull request by peterjc123**
Fixes https://github.com/pytorch/pytorch/issues/13465.

### CODE REVIEW

**Comment by peterjc123** [comment]
@yf225 Are the files in `TMP_DIR` cleaned every time the test job is triggered?

**Comment by soumith** [comment]
is test failure relevant?

```
03:43:05 OK (skipped=1)
03:43:05 Running test_dataloader ... [2019-03-13 03:43:06.761301]
03:43:05 Traceback (most recent call last):
03:43:05   File "test_dataloader.py", line 24, in <module>
03:43:05     import psutil
03:43:05 ModuleNotFoundError: No module named 'psutil'
03:43:05 
03:43:05 During handling of the above exception, another exception occurred:
03:43:05 
03:43:05 Traceback (most recent call last):
03:43:05   File "test_dataloader.py", line 31, in <module>
03:43:05     raise ImportError(err_msg)
03:43:05 ImportError: psutil not found. Some critical data loader tests relying on it (e.g., TestDataLoader.test_proper_exit) will not run.
03:43:06 Traceback (most recent call last):
03:43:06   File "run_test.py", line 457, in <module>
03:43:06     main()
03:43:06   File "run_test.py", line 449, in main
03:43:06     raise RuntimeError(message)
03:43:06 RuntimeError: test_dataloader failed!
03:43:06 + cleanup
```

**Comment by peterjc123** [comment]
@soumith https://github.com/pytorch/pytorch/pull/17954 fixes this problem.

**Comment by yf225** [comment]
@peterjc123 It should be. To be safe we can also manually remove this folder at the beginning of the test job.

**Comment by peterjc123** [comment]
@soumith Could you please merge this PR?

**Pull request closed without merging**
