### PR TITLE
[dynamo][user_defined][stable-diffusion] Raise ObservedAttributeError on UserDefinedObject var_getattr

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #132806

Fixes https://github.com/pytorch/pytorch/issues/132551

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by williamwen42 — APPROVED** [review]

**Comment by jansel** [comment]
Reverted by #133570

**Comment by anijain2305** [comment]
No real change. It just had an unintended merge conflict with the reland of other offending PRs.

**Comment by ezyang** [comment]
I am suspicious lol

**Comment by anijain2305** [comment]
Cancelled the merge command given @ezyang suspicion. Will sync with him offline.

**Comment by anijain2305** [comment]
Confirmed internally that this is not the reason of the breakage. Merging.

**Pull request closed without merging**
