### PR TITLE
restore generic IndexToScatterGatherOffset specialization

### PR DESCRIPTION
**Pull request by ngimel**
#39963 erroneously removed template specialization to compute offsets, causing cases relying on this specialization (topk for 4d+ tensors with topk dimension >= 1024/2048 depending on the type) to produce bogus results.

### CODE REVIEW

**Review by mruberry — APPROVED** [review]
Stamped.

**Comment by ezyang** [comment]
Whoops, thanks for the catch. CC @kurtamohler

**Comment by ngimel** [comment]
@kurtamohler you can get rid of THC gather if you wrap a TH tensor using THTensor_wrap and call ATen gather on the wrapped tensor. Then the remaining kernel can be removed from THC.

**Comment by kurtamohler** [comment]
Darn, sorry about that. I shouldn't have assumed that an existing test would fail if that template was actually needed.

**Comment by ngimel** [comment]
np, it is failing under very specific conditions and unfortunately we did not have a test to catch that. It could have gone unnoticed for a long time, but another PR exposed this bug.

**Pull request closed without merging**
