### PR TITLE
[NJT+SDPA]Fix flash_attention output when batch_size=1 and seq_len=1

### PR DESCRIPTION
**Pull request by YuqingJ**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #130652

fix issue  #130196

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @soulitzer @davidberard98

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]
This is a good backport candidate

**Comment by Skylion007** [comment]
DId you mean to merge it into main lol?

**Review by drisspg — APPROVED** [review]
Yeah we shud probably merge into 2.4.1

**Comment by YuqingJ** [comment]
> Yeah we shud probably merge into 2.4.1

Haven't done that before, should I merge this normally first and then cherry pick it to the 2.4.1?

**Review by jbschlosser — APPROVED** [review]
Thanks for the fix!

**Comment by jbschlosser** [comment]
> Haven't done that before, should I merge this normally first and then cherry pick it to the 2.4.1?

yep, that's right. there will be a cherry-pick issue tracker for 2.4.1 where you can ensure the fix gets picked in: e.g. #128436 for 2.4.0 (too late for that release ofc). I don't think the tracker exists quite yet but you can add the 2.4.1 milestone to this issue / PR.

**Pull request closed without merging**
