### PR TITLE
[C10d][NCCL] Refactor complex all_reduce and broadcast

### PR DESCRIPTION
**Pull request by Aidyn-A**
The necessity of this PR lies in the fact that autograd engine + DDP calls `all_reduce` from C++, so the changes must be made in C++.

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "~/complex_ddp.py", line 72, in <module>
[rank0]:     main()
[rank0]:   File "~/complex_ddp.py", line 64, in main
[rank0]:     loss.backward()
[rank0]:   File "/home/usr/pytorch/torch/_tensor.py", line 525, in backward
[rank0]:     torch.autograd.backward(
[rank0]:   File "/home/usr/pytorch/torch/autograd/__init__.py", line 267, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/home/usr/pytorch/torch/autograd/graph.py", line 744, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]: TypeError: Input tensor data type is not supported for NCCL process group: ComplexFloat
```

I believe, for minimizing the Python overhead, the same could be done for the rest of the ops, what do you think @kwen2501?

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @eqy @ptrblck

### CODE REVIEW

**Comment by Aidyn-A** [comment]
> Naive question, what happens when we view complex `float` as real and apply premul sum? Is the "elementwise" computation valid there?

Yes, the "elementwise" computation must be valid there, as long as the "pre-mul factor" is of the real type.

**Review by eqy — COMMENTED** [review]
Would it make sense to add a minimal test e.g,. in  `test_c10d_nccl.py`?

**Review by eqy — APPROVED** [review]

**Review by kwen2501 — APPROVED** [review]
LGTM.

Re: move complex support down from python to cpp
we might need to give it more thought, as today all cpp backends rely on the `view_as_real` conversion at the python level. If we move it, then it means we'd need to add it back in every backend. (like you did here).

Another way to do it is at the dispatcher:
https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/Ops.cpp

**Pull request closed without merging**
