### PR TITLE
Add test for consistency between meta and CPU devices.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #138520
* __->__ #138515

Reference: https://github.com/pytorch/pytorch/issues/138399

This PR introduces an `OpInfo` test that checks whether running each `out=` operation
using meta inputs is consistent with using concrete (e.g. CPU) inputs. More specifically,
it tests the case where the output tensors are not of the expected data type. According to
the `out=` specification, some operations should error.

I have added XFAIL to the set of operations that are currently failing.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
It's kind of up in the air whether or not CPU is a good default, but I guess it's easy to test and if you really care you use FakeTensor, so sure why no

**Comment by ysiraichi** [comment]
I've just realized that the CI failure I was getting in #138520 wasn't being run in this PR. I believe this PR also fails on `linux-jammy-cpu-py3.9-gcc11-inductor / test (inductor_avx512, 2, 2, linux.12xlarge)`. I will wait for the `ciflow/inductor` to run, and see if that's the case.

**Comment by ysiraichi** [comment]
Moving this to "draft", in order to debug said CI failure.

**Comment by ysiraichi** [comment]
The CI failure looks not related, so merging anyway.

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change, but the test is failing in trunk, maybe a landrace' -c landrace

test_ops.py::TestCommonCPU::test_meta_consistency_out_dtype_mismatch_permute_copy_cpu_float32 [GH job link](https://github.com/pytorch/pytorch/actions/runs/11558871410/job/32173277061) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/006130d8eae834d17e3d3e21e61c506740cce6dc)

**Pull request closed without merging**
