### PR TITLE
Upgrade mkldnn-bridge to revert tensor capacity patch and prepare for DNNLOWP support

### PR DESCRIPTION
**Pull request by gujinghui**
1. Upgrade mkldnn-bridge to revert tensor capacity patch to avoid ASAN issue.
2. Prepare for DNNLOWP support.

### CODE REVIEW

**Comment by gujinghui** [comment]
@yinghai 
In this PR, I reverted the mkldnn-bridge patch, which introduced the ASAN issue.
Pls help review.

And pls merge #18463, before this PR. In #18463, the mkldnn has been upgraded to 0.18.1.
Then, pls help merge this one. **In this PR, the mkldnn has been upgraded to 0.18.1, as well.**
And the ASAN issue should be gone with this PR.

Thanks a lot,
Jinghui

**Comment by gujinghui** [comment]
@jgong5 @Jianhui-Li

**Comment by soumith** [comment]
this branch now has merge conflicts. can you update this PR, now that #18463 has gone in

**Comment by gujinghui** [comment]
@soumith @yinghai 
Just rebased. Pls help review.

Thanks a lot,
Jinghui

**Comment by gujinghui** [comment]
@yinghai 
Rebased to latest.
Pls help review.

**Comment by gujinghui** [comment]
@yinghai 
Most of cases are failed on the test_troch case and network issue.
It should be not caused by this PR.

> Mar 28 05:46:36 test_torch (__main__.TestDocCoverage) ... FAIL
Mar 28 05:46:36 
Mar 28 05:46:36 ======================================================================
Mar 28 05:46:36 FAIL: test_torch (__main__.TestDocCoverage)
Mar 28 05:46:36 ----------------------------------------------------------------------
Mar 28 05:46:36 Traceback (most recent call last):
Mar 28 05:46:36   File "test_docs_coverage.py", line 67, in test_torch
Mar 28 05:46:36     don't want to document?''')
Mar 28 05:46:36 AssertionError: Items in the first set but not the second:
Mar 28 05:46:36 'parse_ir' : 
Mar 28 05:46:36 List of functions documented in torch.rst and in python are different.
Mar 28 05:46:36 Do you forget to add new thing to torch.rst, or whitelist things you
Mar 28 05:46:36 don't want to document?

**Review by yinghai — APPROVED** [review]

**Pull request closed without merging**
