### PR TITLE
bitwise_or: Port to strucutred

### PR DESCRIPTION
**Pull request by Freey0**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #61349 OpInfo: bitwise_and
* #60813 bitwise_and: Port to structured
* #60812 bitwise_xor: Port to structured
* **#60811 bitwise_or: Port to strucutred**
* #60817 logit_backward: Port to structured
* #60816 tanh_backward: Port to structured
* #60815 sigmoid_backward: Port to structured
* #60814 xlogy: Port to structured
* #60810 fmin has been ported to the structured kernel, removing the old implementation
* #60809 fmod: Port to structured

Differential Revision: [D29449370](https://our.internmc.facebook.com/intern/diff/D29449370)

### CODE REVIEW

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29449370).

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
needs xla update

**Comment by JackCaoG** [comment]
@ezyang I think the error is real but I don't think it is on XLA side. What happened is that in
```
 737│ Tensor bitwise_or(const Tensor& self, const Scalar& other) {
 738├>  return at::bitwise_or(self, wrapped_scalar_tensor(other));
 739│ }
```
pytorch wrap the scalar to tensor but it did not set the device type correctly. When I check in gdb I saw in pt/xla code

```
 869│ at::Tensor& bitwise_or_out(const at::Tensor& self, const at::Tensor& other,
 870│                            at::Tensor& out) {
 871│   XLA_FN_COUNTER("xla::");
 872│   CheckBinaryOpTypePromotion(out, self, other);
 873│   XLATensor out_tensor = bridge::GetXlaTensor(out);
 874│   XLATensor::bitwise_or_out(out_tensor, bridge::GetXlaTensor(self),
 875│                             bridge::GetXlaTensor(other));
 876│   return out;
 877├>}
```

device type of `other` is `cpu`
```
(gdb) p self.device()
$6 = {[36mtype_[m = [36mc10::DeviceType::XLA[m, [36mindex_[m = 0 '\000'}
(gdb) p other.device()()
$7 = {[36mtype_[m = [36mc10::DeviceType::CPU[m, [36mindex_[m = -1 '\377'}
```

Maybe do something like 
```
return at::bitwise_or(self, wrapped_scalar_tensor(other, self.device()));
```
will help?

**Comment by ezyang** [comment]
Well, at least for CUDA, this would not be desirable, because our CUDA kernels support mixing with CPU scalar when it says that this is OK:

```
      // Handles CPU scalars on CUDA kernels that support them
      if (!common_device.is_cpu() &&
          config.allow_cpu_scalars_ && !op.is_output && op.tensor->dim() == 0 &&
          op.tensor->is_cpu()) {
        TORCH_CHECK(current_cpu_scalars_on_non_cpu < max_cpu_scalars_on_non_cpu,
                    "Trying to pass too many CPU scalars to non-CPU kernel!");
        ++current_cpu_scalars_on_non_cpu;
      } else if (op.device != common_device) {
        TORCH_CHECK(false,
                    "Expected all tensors to be on the same device, but "
                    "found at least two devices, ", common_device, " and ", op.device, "!");
      }
```

which is true for binary ops

```
// This cannot be a function because TensorIteratorConfig is not
// copyable or movable, so it can't be returned from the function.
#define BINARY_OP_CONFIG()                              \
  TensorIteratorConfig()                                \
    .set_check_mem_overlap(true)                        \
    .allow_cpu_scalars(true)                            \
    .promote_inputs_to_common_dtype(true)               \
    .cast_common_dtype_to_outputs(true)                 \
    .enforce_safe_casting_to_output(true)               \
```

So under this model, XLA is obligated to handle this mixed device situation.

**Comment by JackCaoG** [comment]
@ezyang Sounds good, I will look into support this kind of use case. I guess this means pt/xla no longer need to lower `bitwise_or.Scalar_out` since it will never be called after `bitwise_or` is ported to structured right?

**Comment by JackCaoG** [comment]
Ah actually I already implemented the similar logic in https://github.com/pytorch/xla/pull/1757, will just extend that to this op.

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29449370).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29449370).

**Comment by Freey0** [comment]
Updated the OpInfo('__rxor__') test because the OpInfo test detects that torch.bool is now correctly supported. See the discussion above for the reason.

cc @mruberry,  Can you help me look at it? Because this is about OpInfo.

**Comment by mruberry** [comment]
OpInfo update looks good. I've asked the linalg team to look at the lstsq failure -- maybe that test is flaky? The PyTorch/XLA failures look real, however.

**Comment by JackCaoG** [comment]
@mruberry I have https://github.com/pytorch/xla/pull/3022 which should solve the test failures up to #60813. Failure pattern is similar so I just make one pr to resolve all test failures.

**Comment by mruberry** [comment]
> @mruberry I have [pytorch/xla#3022](https://github.com/pytorch/xla/pull/3022) which should solve the test failures up to #60813. Failure pattern is similar so I just make one pr to resolve all test failures.

Thanks for the update @JackCaoG, sorry I didn't see your comments above.

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29449370).

**Comment by ezyang** [comment]
My plan: I'm going to first land everything below this diff in the stack to reduce the amount I'm landing all at once. Then I'll land all of the bitwise and land the consolidated XLA PRs.

**Pull request closed without merging**
