### PR TITLE
cherry-picking autodiff support for gather/index_select

### PR DESCRIPTION
**Pull request by jjsjann123**
added gather & index_select in autodiff;
test coverage should be handled by opinfo;

### CODE REVIEW

**Comment by jjsjann123** [comment]
cc'ing @ftxj

**Review by ngimel — APPROVED** [review]

**Comment by jjsjann123** [comment]
hmmm. failure in distributed looks unrelated?! I'm trying my luck with another merge on viable/strict. :crossed_fingers: Hope the issue would just go away :see_no_evil:

**Comment by jjsjann123** [comment]
Looking promising this time~~

**Comment by jjsjann123** [comment]
errr. I don't see a job failure in the CI. Looks like the many wheel job is cancelled for some reason. I'll restart it.

**Comment by jjsjann123** [comment]
Ok it's really looking promising this time :crossed_fingers:

**Pull request closed without merging**
