### PR TITLE
[3/N] Fix Wextra-semi warnings 

### PR DESCRIPTION
**Pull request by cyyever**
Fixes #ISSUE_NUMBER

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by cyyever** [comment]
@r-barnes Don't want to change the macros, otherwise, it may introduce unintentional breaks, depending on how they are used in unforeseeable ways.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
If someone accidentally puts too many semicolons cyyever can tell them about it :P

**Pull request closed without merging**
