### PR TITLE
irange for size_t

### PR DESCRIPTION
**Pull request by r-barnes**
Differential Revision: D27448156

### CODE REVIEW

**Comment by imaginary-person** [comment]
ROCm CI checks (`pytorch_linux_bionic_rocm3_9_py3_6_build` and `pr/pytorch-linux-bionic-rocm4.0.1-py3.6 `) have been failing after this PR.

**Comment by r-barnes** [comment]
@imaginary-person : Can we back it out? I had seen those, but I couldn't find a causal connection so assumed they were flakes.

**Comment by imaginary-person** [comment]
Hello @r-barnes, thanks for your prompt response! I'm sorry, I was merely stating an observation; I'm not working on related changes.

Going by the [commit history of the master branch](https://github.com/pytorch/pytorch/commits/master), #55212 was merged right before this PR, and `pytorch_linux_bionic_rocm3_9_py3_6_build` was passing for it, so I do see a causal relationship in the failures, but am not in a position to comment on whether this PR should be reverted, or patched. Thank you!

**Comment by r-barnes** [comment]
I believe it could be causing the failure; I'm just not sure why. I'll be able to look into it more this evening, hopefully.

**Comment by styler00dollar** [comment]
I tried to build pytorch with rocm and looking up issues bringed me to this issue.
```
../torch/csrc/jit/tensorexpr/cuda_codegen.cpp: In Elementfunktion »virtual void torch::jit::tensorexpr::CudaCodeGen::call(const std::vector<torch::jit::tensorexpr::CodeGen::CallArg>&)«:
../torch/csrc/jit/tensorexpr/cuda_codegen.cpp:1072:20: Fehler: Parameter darf nicht variabel modifizierten Typ »torch::jit::tensorexpr::ExprHandle [i]« haben
 1072 |         ExprHandle(gpu_block_extents[i]), buffer_args());
      |                    ^~~~~~~~~~~~~~~~~
../torch/csrc/jit/tensorexpr/cuda_codegen.cpp:1081:20: Fehler: Parameter darf nicht variabel modifizierten Typ »torch::jit::tensorexpr::ExprHandle [i]« haben
 1081 |         ExprHandle(gpu_thread_extents[i]), buffer_args());
      |                    ^~~~~~~~~~~~~~~~~~
```
I am not sure if this helps, but my compile fails and my assumption is that it could be related to this pr, since not many prs mention ``gpu_thread_extents``.

**Comment by mruberry** [comment]
Unlanding. @imaginary-person seems to be correct, and this also affected by devfair build. Building on the commit prior to it worked on devfair (and appears to work on ROCm).

Failure snippet:

```
06:41:36 /var/lib/jenkins/workspace/torch/csrc/jit/tensorexpr/cuda_codegen.cpp:1072:40: error: parameter may not have variably modified type ‘torch::jit::tensorexpr::ExprHandle [i]’
06:41:36  1072 |         ExprHandle(gpu_block_extents[i]), buffer_args());
06:41:36       |                                        ^
06:41:36 /var/lib/jenkins/workspace/torch/csrc/jit/tensorexpr/cuda_codegen.cpp:1081:41: error: parameter may not have variably modified type ‘torch::jit::tensorexpr::ExprHandle [i]’
06:41:36  1081 |         ExprHandle(gpu_thread_extents[i]), buffer_args());
```

**Comment by styler00dollar** [comment]
I can confirm mruberry, I had the exact same error yesterday when I tried to compile it for rocm. I tried it again after the commit got reverted and it works. Please rework this pr before merging again, since I spent half a day compiling and making sure it is not my fault.

**Pull request closed without merging**
