### PR TITLE
BFloat16 support for torch.sort for ROCm

### PR DESCRIPTION
**Pull request by amathews-amd**
Related to https://github.com/pytorch/pytorch/pull/58196

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @pruthvistony

### CODE REVIEW

**Comment by pruthvistony** [comment]
The changes are fine and verified the test cases are running fine.
However changes are required to enable the tests for ROCm which are NOT executed now.

**Comment by jeffdaily** [comment]
@amathews-amd ROCm CI is now on 4.5.2.  Please resolve the recent conflicts and move out of draft mode.  Thanks.

**Comment by pruthvistony** [comment]
@amathews-amd ,
I had a commit to enable the UT tests.

**Comment by amathews-amd** [comment]
Closed; continued on #71226

**Pull request closed without merging**
