### PR TITLE
Update protobuf to 3.13.1

### LINKED ISSUE #62569: PyTorch Bazel scripts are incompatible with bazel-4.x
## 🐛 Bug

Any build attempts fail in protobuf with:

``
/home/nshulga/.cache/bazel/_bazel_nshulga/949d449b28ab1dc6cc4616fb8666a5b1/external/com_google_protobuf/BUILD:1006:21: in proto_lang_toolchain rule @com_google_protobuf//:cc_toolchain: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.
``

## To Reproduce

1. Download https://github.com/bazelbuild/bazel/releases/tag/4.1.0
1. Run ` bazel build --sandbox_writable_path ~/.ccache  //:caffe2`

## Expected behavior

Build succeeds
## Additional context
Likely to be caused by https://github.com/bazelbuild/bazel/issues/12887, so updating protobuf definitions should help.

cc @malfet @seemethere @walterddr

### PR DESCRIPTION
**Pull request by malfet**
Update bazel to 4.10.0

Update ASAN_SYMBOLIZER_PATH to llvm-7
Suppress `vptr` ubsan violations in `test_jit`
Fix ProtoBuf patching for ONNX which caused Windows builds to crash while attempting to free `std::string` allocated on stack

Fixes https://github.com/pytorch/pytorch/issues/62569

### CODE REVIEW

**Comment by garymm** [comment]
Thanks for this change! The title of the PR is wrong. Should be "3.13.1", not "4.13.1".

**Review by walterddr — APPROVED** [review]

**Review by walterddr — COMMENTED** [review]
not sure why it broke these other test though :-(

**Comment by malfet** [comment]
@walterddr docker builds are broken due to https://github.com/pytorch/pytorch/issues/62738, but big question I have is whether clang update will fix false positive in asan testing

**Comment by malfet** [comment]
For some reason, after protobuf update it starts to crash on Windows for something as simple as:
```
python -c "import torch;import io;torch.onnx.export(torch.nn.Linear(3,3), (torch.rand(3, 3), ), io.BytesIO())"
```

**Comment by malfet** [comment]
Finally have a backtrace and a theory of what is going on:
image
Looks like new protobuf C++ supports `std::enable_shared_from_this`, which results in object allocated in one dll (torch_python.so) being freed in another.

**Comment by malfet** [comment]
image
Crash actually happens in `ValueInfoProto::SharedDtor()`, where an attempt is made to free empty string allocated on stack, because `GetEmptyStringAlreadyInited()` can return different values depending on the library it's called from... See code below
```
void ValueInfoProto::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  doc_string_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete type_;
}
```

Though why it only happens on Windows is still a mystery to me.

**Pull request closed without merging**
