### PR TITLE
Remove CUTLASS extensions merged upstream

### PR DESCRIPTION
**Pull request by alexsamardzic**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #107612

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer

### CODE REVIEW

**Comment by alexsamardzic** [comment]
This PR resolves [issue 101804](https://github.com/pytorch/pytorch/issues/101804).

**Review by cpuhrsch — APPROVED** [review]
Amazing. cc @albanD

**Review by albanD — APPROVED** [review]
amazing!

**Comment by ZainRizvi** [comment]
@pytorchbot revert -m "Sorry, this breaks internal builds which still depend on these files" -c ghfirst

@albanD, can you please help @alexsamardzic get these changes merged

**Comment by cpuhrsch** [comment]
Hm, interesting. The failure seems to be
```
/native/sparse/cuda/SparseSemiStructuredLinear.cu:14:10: fatal error: 'cutlass/gemm/device/gemm_sparse_row_broadcast.h' file not found
#include <cutlass/gemm/device/gemm_sparse_row_broadcast.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by cpuhrsch** [comment]
This seems to be a gap specific to internal Windows builds. @drisspg is looking into it. @alexsamardzic we can retry this once that's been resolved.

**Comment by alexsamardzic** [comment]
The file that is reported as not found is one that we had merged into
CUTLASS, in order to support sparse semi-structured linear operator.  Thus,
the problem has to be in the CUTLASS version used for this build.

**Comment by drisspg** [comment]
The internal fix has landed, so it might be good to retry this diff

**Pull request closed without merging**
