### PR TITLE
Add csrc/cuda/comm.cpp to TORCH_PYTHON_SRCS …

### PR DESCRIPTION
**Pull request by jithunnair-amd**
…so that it's compiled with -DUSE_NCCL

Fix for issue filed here: https://github.com/pytorch/pytorch/issues/27116

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
cc @iotamudelta @ezyang @bddppq

**Comment by ezyang** [comment]
Umm, ok, I guess? But don't you have to remove comm.cpp from the other lists it occurs then, in that case?

Test failures are real:
```
Nov 05 04:57:30 test_broadcast_double_backwards_gpu (__main__.TestNN) ... /opt/conda/bin/python: symbol lookup error: /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: _ZN5torch4cuda4nccl13get_max_countEv
Nov 05 04:57:30 Traceback (most recent call last):
Nov 05 04:57:30   File "test/run_test.py", line 454, in <module>
Nov 05 04:57:30     main()
Nov 05 04:57:30   File "test/run_test.py", line 446, in main
Nov 05 04:57:30     raise RuntimeError(message)
Nov 05 04:57:30 RuntimeError: test_nn failed!
Nov 05 04:57:31 + cleanup
```

**Review by ezyang — CHANGES_REQUESTED** [review]
not passing ci

**Comment by jithunnair-amd** [comment]
@ezyang There's `${TORCH_SRC_DIR}/csrc/distributed/c10d/comm.cpp`, but that's a different file. I don't see any occurrences of `${TORCH_SRC_DIR}/csrc/cuda/comm.cpp` in the file before my PR. Did I get that wrong?

**Comment by ezyang** [comment]
You might be right. However, the CI failure still holds. It might caused if you refer to a symbol defined in `libtorch.so` that isn't exported using a `TORCH_API` annotation.

**Comment by jithunnair-amd** [comment]
@ezyang Thanks for pointing out the `TORCH_API` annotation. I added them to the required functions in `nccl.cpp`. The Ubuntu config passed all tests. The Centos build timed out, so I don't think it's related to my changes. However, I can't understand why the Windows build gives a "multiply defined symbols" error. Can you please help me understand?

**Comment by ezyang** [comment]
I'm not sure. It might be that we used the wrong API macro here, or you really are including this cpp file twice. Look and see if there are any globs that would catch this file?

**Comment by ezyang** [comment]
This still seems wrong to me. Earlier you claimed:

> There's ${TORCH_SRC_DIR}/csrc/distributed/c10d/comm.cpp, but that's a different file. I don't see any occurrences of ${TORCH_SRC_DIR}/csrc/cuda/comm.cpp in the file before my PR. Did I get that wrong?

So what's this in caffe2/CMakeLists.txt?

```
  if (USE_CUDA)
    list(APPEND Caffe2_GPU_SRCS
      ${TORCH_SRC_DIR}/csrc/jit/fuser/cuda/fused_kernel.cpp
      ${TORCH_SRC_DIR}/csrc/autograd/profiler_cuda.cpp
      ${TORCH_SRC_DIR}/csrc/autograd/functions/comm.cpp
      ${TORCH_SRC_DIR}/csrc/cuda/comm.cpp
    )
    add_library(caffe2_nvrtc SHARED ${ATen_NVRTC_STUB_SRCS})
    target_link_libraries(caffe2_nvrtc ${CUDA_NVRTC} ${CUDA_CUDA_LIB} ${CUDA_NVRTC_LIB})
    target_include_directories(caffe2_nvrtc PRIVATE ${CUDA_INCLUDE_DIRS})
    install(TARGETS caffe2_nvrtc DESTINATION "${TORCH_INSTALL_LIB_DIR}")
  endif()

  if (USE_ROCM)
    list(APPEND Caffe2_HIP_SRCS
      ${TORCH_SRC_DIR}/csrc/jit/fuser/cuda/fused_kernel.cpp
      ${TORCH_SRC_DIR}/csrc/autograd/profiler_cuda.cpp
      ${TORCH_SRC_DIR}/csrc/autograd/functions/comm.cpp
      ${TORCH_SRC_DIR}/csrc/cuda/comm.cpp
    )
    # caffe2_nvrtc's stubs to driver APIs are useful for HIP.
    # See NOTE [ ATen NVRTC Stub and HIP ]
    add_library(caffe2_nvrtc SHARED ${ATen_NVRTC_STUB_SRCS})
    target_link_libraries(caffe2_nvrtc ${PYTORCH_HIP_HCC_LIBRARIES} ${ROCM_HIPRTC_LIB})
    target_compile_definitions(caffe2_nvrtc PRIVATE USE_ROCM __HIP_PLATFORM_HCC__)
    install(TARGETS caffe2_nvrtc DESTINATION "${TORCH_INSTALL_LIB_DIR}")
  endif()
```

**Comment by jithunnair-amd** [comment]
@ezyang Sorry, I hadn't looked in that file. I was looking in `torch/CMakeLists.txt`. I understand now why the duplication of symbols was occurring. Anyway, I also found that an equivalent fix was made for this in `caffe2/CMakeLists.txt`:
```
24242e86f (Pritam Damania           2019-10-07 17:37:58 -0700  478)   if (USE_NCCL)
24242e86f (Pritam Damania           2019-10-07 17:37:58 -0700  479)     list(APPEND TORCH_SRCS
24242e86f (Pritam Damania           2019-10-07 17:37:58 -0700  480)       ${TORCH_SRC_DIR}/csrc/cuda/nccl.cpp)
24242e86f (Pritam Damania           2019-10-07 17:37:58 -0700  481)   endif()
```
Since this resolves the issue I was trying to address in this PR, I'm closing this PR.

**Pull request closed without merging**
