### PR TITLE
[export] Do not copy state_dict in run_decomp

### LINKED ISSUE #114628: `run_decompositions` in `ExportedProgram` doesn't keep the same model state_dict
### 🐛 Describe the bug

After running `run_decompositions`, the exported program is not the same.
https://github.com/pytorch/pytorch/blob/e0d2a24967218d7c39e24f66bb6c4836c9d1d427/torch/export/exported_program.py#L351-L361

However, `the state_dict` is also updated.
https://github.com/pytorch/pytorch/blob/e0d2a24967218d7c39e24f66bb6c4836c9d1d427/torch/export/exported_program.py#L458-L472

Should decomposition happen in-place, instead of creating a whole new one?

### Versions

main branch

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @thiagocrepaldi

### PR DESCRIPTION
**Pull request by angelayi**
Fixes https://github.com/pytorch/pytorch/issues/114628

### CODE REVIEW

**Review by thiagocrepaldi — APPROVED** [review]
not having a copy is great as we can share the same state from the original `torch.nn.Module`, to the resulting `ep: ExportedProgram = torch.export.export(model)` up to the `ep = ep.run_decompositions()`. 
For testing and comparing results, having all models with the same state helps a lot

Maybe add a unit test that `id(state_dict)` before and after the decomp to guard this from regressing?

**Comment by angelayi** [comment]
wait sorry i didnt see the comment on unittests oop

**Review by ydwu4 — APPROVED** [review]

**Review by thiagocrepaldi — COMMENTED** [review]
can we also cherry-pick it to release/2.2?

**Comment by angelayi** [comment]
@thiagocrepaldi I'm not sure if this qualifies for a cherry-pick, but I can try.

**Pull request closed without merging**
