### PR TITLE
Assert all aten decomps handled by inductor at startup

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #100014
* #99997

This should be equivalent to the error/warning issued when registering
a fallback and finding an existing decomp, based on the assumption that
a fallback would never be registered for an op handled by an existing
inductor decomp or by an existing inductor lowering.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @soumith @anijain2305 @desertfire

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
Looks like the test is failing.  What are the uncovered ops?

**Comment by ngimel** [comment]
In many cases we register fallbacks and go to them under some conditions even when lowerings/decomps exist (e.g. pooling, index, deterministic ops)

**Comment by jansel** [comment]
I think most of those decomps should be enabled.

**Comment by wconstab** [comment]
How should we tackle this, do @jansel or @ngimel want to take a stab at which ones to decomp and maybe the rest we put into a new list of 'need_to_add_lowerings' so we can track them but not error on them?

**Comment by ngimel** [comment]
A lot of decompositions in the nominally missing list are already in the core decomps, e.g. `aten.elu`, when overload is not specified we are using it for all overloads.

**Comment by wconstab** [comment]
> I'm unsure what we are trying to achieve with this, we've already disabled implicit fallback creation for the test suite, what else are we trying to do?

We are trying to achieve the same thing in a less hacky way.  I got dinged for using 'IS_CI' in inductor code.  I made a fix for the literal import issue already (it broke fbcode builds) - but the point stands, that it's a bit odd to only check in CI.  I proposed another PR that just does the check all the time, and @jansel said he prefers not to expose users to that warning and hence an explicit check at startup is more appealing.

**Comment by jansel** [comment]
> @jansel said he prefers not to expose users to that warning and hence an explicit check at startup is more appealing.

My objection to the other PR was turning all of these into an error and raising an exception.  Erroring for no reason and breaking user code whenever they called one of the functions in the list you just generated seems super bad.  If it were a just a warning (like it used to be), I'd be less concerned.

These seem like good BE tasks.  We should add support for all these missing ops (either through decomps or lowerings), but it is not super high priority since the ops aren't common.  Perhaps we could turn these into bootcamper tasks or `good first issue` tasks to try to clean them up.

**Comment by ngimel** [comment]
The list in the gist looks sus to me though, it definitely has ops that we are decomposing.

**Comment by jansel** [comment]
Yeah agreed... Maybe there is a bug.  Maybe we need to register more overloads than the default one.

**Pull request closed without merging**
