### PR TITLE
[inductor] Move inductor ops to CompositeExplicitAutograd

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #111274
* #111273
* #111271

I suspect in practice this won't matter, but if we do end up tracing this it causes them not to get decomposed.

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]

**Review by desertfire — APPROVED** [review]

**Comment by jeanschmidt** [comment]
Reverted because https://github.com/pytorch/pytorch/pull/111271 depends on it and it need to be reverted

**Pull request closed without merging**
