### PR TITLE
Optimize Vectorized<float> exp() with neon simd instructions

### PR DESCRIPTION
**Pull request by helloguo**
Optimize `Vectorized<float> exp()` with neon simd instructions, copy from the implementation  ~~https://github.com/ARM-software/optimized-routines/blob/master/math/aarch64/v_expf.c with minor changes.~~ https://github.com/ARM-software/optimized-routines/blob/master/math/aarch64/v_expf_1u.c with maxerr: 0.36565 +0.5 ulp.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by WenleiHe** [comment]
Any measurement comparing against sleef (not sure how it's implemented there for arm)?

**Comment by helloguo** [comment]
> Any measurement comparing against sleef (not sure how it's implemented there for arm)?

Test on MacBook Air M2 with Llama-2-7b model using AOT Inductor, the default expf from libsystem_m.dylib is 0.78 tokens/sec, sleef is 0.96 tokens/sec, this PR is 1.57 tokens/sec.

**Comment by metascroy** [comment]
@helloguo do you have any testing on the accuracy of this method?

I ask because I think Sleef guarantees a certain accuracy with their polynomial approximations, and so this might not be comparing apples-to-apples.

I see that Sleef does offer the ability to lower the accuracy for more speed if desired, but I haven't played around with it (see section "ULP, gradual underflow and flush-to-zero mode" in https://sleef.org/additional.xhtml).

**Comment by helloguo** [comment]
> @helloguo do you have any testing on the accuracy of this method?

Thanks for reviewing. I just updated the diff with the implementation from https://github.com/ARM-software/optimized-routines/blob/master/math/aarch64/v_expf_1u.c.  Based on the comments, it has the maxerr: 0.36565 +0.5 ulp. Do we need additional accuracy testing?

> I see that Sleef does offer the ability to lower the accuracy for more speed if desired, but I haven't played around with it (see section "ULP, gradual underflow and flush-to-zero mode" in https://sleef.org/additional.xhtml).

Good point. IIUC the Sleef_expf4 has only one implementation with 1.0 ULP error bound at the moment.

**Pull request closed without merging**
