### PR TITLE
[decomp] fix decomp of batch_norm when weight/bias is not flattened

### PR DESCRIPTION
**Pull request by jgong5**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #101059

Fix https://github.com/pytorch/pytorch/issues/100970

### CODE REVIEW

**Comment by jgong5** [comment]
@albanD @zou3519 Can you please review? Thanks!

**Review by ezyang — APPROVED** [review]
@ngimel was arguing we should just make eager error in this case, but this fix is good start.

**Pull request closed without merging**
