### PR TITLE
Don't add to replacements when guard is suppressed

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #126210

Also improve logging when guards are suppressed

Partially addresses https://github.com/pytorch/pytorch/issues/125641

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by eellison** [comment]
Test failures..

**Comment by ezyang** [comment]
Oh no the replacements are load bearing :(

cc @jbschlosser

**Comment by jbschlosser** [comment]
> Oh no the replacements are load bearing :(

oh right, it's depending on replacement for ephemerally-sourced SymInts created during view replay. hmm..

**Comment by ezyang** [comment]
I'm not even sure how I morally want to structure all of this lol. @eellison maybe we should just land your fix only lol

**Comment by jbschlosser** [comment]
would it make sense to split `_maybe_guard_rel()` into separate replace, guard logic? so one path is guaranteed to only replace and not guard if possible, and the other path could do guarding conditional on the TLS suppress guards state

**Comment by eellison** [comment]
well, we still need it (or an alternative path) for @davidberard98's patch that wants to get hint on symint values without replacing values. we also do a similar thing in fx graph cache lookup when matching dynamic shape guards.

**Comment by ezyang** [comment]
Another option is to have two flavors of the suppress guards context manager: one that you use for your use case, and a different one when we need to remove ephemeral sources. Another possibility is to not do replacements UNLESS the source is ephemeral, in which case always do them (even if guards are suppressed).

**Comment by ezyang** [comment]
I resolved the problem by suppressing asserts for `as_strided`, but NOT suppressing asserts for traceable tensor subclasses. I think this is a good compromise, because the inner tensors for subclasses have sources, so we can appropriately honor guards on them.

**Comment by ezyang** [comment]
This is ready to go

**Review by jbschlosser — APPROVED** [review]
* [x] Makes replacements conditional on suppress guards TLS
* [x] Only suppresses guards + replacements for the dense -> dense `as_strided()` case (ephemerally-sourced SymInts for subclass view replay should still be replaced).

LGTM

**Pull request closed without merging**
