### PR TITLE
[easy] Remove large LayerNorm sample input causing OOM from ModuleInfo

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #98424

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Review by albanD — COMMENTED** [review]
Which test ooms? This is not a very big input.
I wouldn't be surprised if it was gradgradcheck though :package:

**Comment by huydhn** [comment]
> Which test ooms? This is not a very big input. I wouldn't be surprised if it was gradgradcheck though 📦

The OOM one is `TestModuleCUDA.test_gradgrad_nn_LayerNorm_cuda_float64`, i.e. https://hud.pytorch.org/pytorch/pytorch/commit/ea00f850e927e81de68e83de091bb6900c05fd6f

**Review by albanD — APPROVED** [review]

**Comment by huydhn** [comment]
@mikaylagawarecki Sorry, I didn't realize that there are few mores test also runs OOM besides this the one you fix here.  They are:

* `TestModuleCUDA.test_gradgrad_nn_GroupNorm_cuda_float64`
* `TestModuleCUDA.test_grad_nn_GroupNorm_cuda_float64`

For example, https://hud.pytorch.org/pytorch/pytorch/commit/ca1fe9bae5c878ee11e6df2324d3cf5a9c0a0579

Could you follow up with the same fix for them?

**Comment by albanD** [comment]
@huydhn is there a way to indentify the particular sample here to only revert these ones?

**Comment by huydhn** [comment]
> @huydhn is there a way to indentify the particular sample here to only revert these ones?

I couldn't find the sample name spelled out in the test output.  May be it makes sense to skip the next biggest sample till the tests pass?

**Pull request closed without merging**
