### PR TITLE
[CUDA][SDPA] Bump tolerances for `test_mem_efficient_attention_attn_mask_vs`

### PR DESCRIPTION
**Pull request by eqy**
Same thing as #133051 but for efficient attention

CC @drisspg @nWEIdia 

cc @ptrblck @msaroufim @drisspg @mikaylagawarecki

### CODE REVIEW

**Review by drisspg — APPROVED** [review]

**Review by nWEIdia — APPROVED** [review]
Thanks for the fix!

**Review by Skylion007 — APPROVED** [review]

**Pull request closed without merging**
