### PR TITLE
Add Meta backend into tensor type strings

### PR DESCRIPTION
**Pull request by GlebKazantaev**
Add Meta backend into tensor type strings.

### CODE REVIEW

**Review by wconstab — APPROVED** [review]
i guess i don't see why not?  but also not sure why you needed this?

cc @ezyang

**Comment by ezyang** [comment]
I think this gets hit in printing or something. Whatever, harmless enough.

**Comment by GlebKazantaev** [comment]
We hit this error when trying to analyze tensor types inside the AMP hooks.

**Comment by GlebKazantaev** [comment]
@ezyang @wconstab looks like lint run has failed due to infra issues.
```
>>> Lint for torch/csrc/utils/nested.cpp:

  Error (CLANGTIDY) command-failed
    Failed due to FileNotFoundError:
    [Errno 2] No such file or directory: '.lintbin/clang-tidy'
```
should I just restart the merge with @pytorchbot merge ?

**Comment by GlebKazantaev** [comment]
@wconstab could you please start the workflows?
Looks like I don't have right to do this.
image

**Pull request closed without merging**
