### PR TITLE
update docs for separate context and forward functions

### PR DESCRIPTION
**Pull request by ad8e**

### CODE REVIEW

**Review by soulitzer — APPROVED** [review]
Thanks!

**Comment by soulitzer** [comment]
@ad8e looks like you need to sign CLA

**Comment by ad8e** [comment]
Yup, I am figuring out CLAs with my org; might take a week. I didn't realize vscode had created this pull request already; sorry about that.

Original docs issue: #121714.

**Comment by ad8e** [comment]
CLA issues might take a while longer :(

Issue has been deprioritized at our company, I'll try to bring it up again in a few weeks.

**Comment by ad8e** [comment]
CLA signed.

**Pull request closed without merging**
