### PR TITLE
Fix broken link of scikit-learn

### PR DESCRIPTION
**Pull request by yuanx749**
The link is broken in https://pytorch.org/docs/main/community/design.html

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by yuanx749** [comment]
@Skylion007 Could you trigger the CI flow for this pr? (sorry for the ping)

**Comment by Skylion007** [comment]
@yuanx749 I can't trigger the CI flow since the name of the commit has `[skip-ci]` in it.

**Comment by yuanx749** [comment]
@Skylion007 I followed the contributing guide to add `[skip ci]`. I just pushed a new commit. Would it work now?

**Pull request closed without merging**
