### PR TITLE
Port ELU activation to Aten

### LINKED ISSUE #24554: Migrate `elu` and `elu_` from the TH to Aten (CUDA)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

### PR DESCRIPTION
**Pull request by XiaobingSuper**
@VitalyFedyunin, This PR is about port  ELU activation to Aten:
**Test script:**
```
import torch
import torch.nn as nn
import time

torch.manual_seed(0)
def _time():
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    return time.time()

device = "cpu"
m = nn.ELU()
if torch.cuda.is_available():
    device = "cuda"
    m = m.cuda()

#warm up
for n in [100, 10000]:
    input = torch.randn(128, n, requires_grad=True, device=device)
    grad_output = torch.ones(128, n, device=device)
    for i in range(1000):
        output = m(input)
        output.backward(grad_output)

for n in [100, 10000]:
    fwd_t = 0
    bwd_t = 0
    input = torch.randn(128, n, requires_grad=True, device=device)
    grad_output = torch.ones(128, n, device=device)
    for i in range(10000):
        t1 = _time()
        output = m(input)
        t2 = _time()
        output.backward(grad_output)
        t3 = _time()
        fwd_t = fwd_t + (t2 -t1)
        bwd_t = bwd_t + (t3 - t2)
    fwd_avg = fwd_t / 10000 * 1000
    bwd_avg = bwd_t / 10000 * 1000
    print("input size(128, %d) forward time is %.2f (ms); backwad avg time is %.2f (ms)."
          % (n, fwd_avg, bwd_avg))
```
Test Device: CPU: skx-8180, GPU: Tesla P40.
Perfromance:
Before:
```
GPU:
input size(128, 100) forward time is 0.04 (ms); backwad avg time is 0.09 (ms).
input size(128, 10000) forward time is 0.06 (ms); backwad avg time is 0.17 (ms).
CPU:
OMP_NUM_THREADS=56
input size(128, 100) forward time is 0.28 (ms); backwad avg time is 0.18 (ms).
input size(128, 10000) forward time is 23.53 (ms); backwad avg time is 14.46 (ms).
OMP_NUM_THREADS=1
input size(128, 100) forward time is 0.16 (ms); backwad avg time is 0.08 (ms).
input size(128, 10000) forward time is 15.53 (ms); backwad avg time is 6.60 (ms).
```
After:
```
GPU:
input size(128, 100) forward time is 0.05 (ms); backwad avg time is 0.11 (ms).
input size(128, 10000) forward time is 0.06 (ms); backwad avg time is 0.17 (ms).
CPU:
OMP_NUM_THREADS=56
input size(128, 100) forward time is 0.24 (ms); backwad avg time is 0.17 (ms).
input size(128, 10000) forward time is 0.73 (ms); backwad avg time is 1.11 (ms).
OMP_NUM_THREADS=1
input size(128, 100) forward time is 0.15 (ms); backwad avg time is 0.07 (ms).
input size(128, 10000) forward time is 14.40 (ms); backwad avg time is 6.00 (ms).
```
How to set the numbers of thread? using following script:
```
num_threads=$1
script=$2
last_core=`expr $num_threads - 1`
echo "using $num_threads OMP threads"
echo "bind cores to 0~$last_core"
export OMP_NUM_THREADS=$num_threads
export KMP_AFFINITY=granularity=fine,compact,1,0
numactl --physcpubind=0-$last_core --membind=0 python $script
```
and run .**/run.sh num_threads test.py**.

Fixes: #24554 #24555 #24694 #24695

### CODE REVIEW

**Comment by XiaobingSuper** [comment]
#24554 Migrate elu and elu_ from the TH to Aten (CUDA)
 #24555 Migrate elu_backward from the TH to Aten (CUDA)
 #24694 Migrate elu and elu_ from the TH to Aten (CPU)
 #24695 Migrate elu_backward from the TH to Aten (CPU)

**Comment by XiaobingSuper** [comment]
For GPU path, there have a performance degradation in the case of small input size, need futher analysis.

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin, please help review the code, thanks!

**Comment by XiaobingSuper** [comment]
> For GPU path, there have a performance degradation in the case of small input size, need futher analysis.

Please ignore this,  there has a variance for the data, sometimes they can get a similar perfromance.

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin, please help review this code.

**Comment by XiaobingSuper** [comment]
@xuhdev

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin, I can't see the details about the failed cases, can you help see them?  Thanks!

**Comment by VitalyFedyunin** [comment]
Bunch of infrastructure timeouts, I will rerun and merge.

**Comment by VitalyFedyunin** [comment]
I can't merge because of weird amount of internal failures (they all looks unrelated to me), can you please try to rebase on top of the master to see if errors will go away.

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin, I rebased this code, hope all test cases are passed.

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin , the failed case is about download error, not related this PR.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Windows error seems to be unrelated, but please rebase to be sure.

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin, rebased.

**Pull request closed without merging**
