### PR TITLE
Fixed a formatting issue in doc comments 

### PR DESCRIPTION
**Pull request by brianjo**
for torch.distributed.broadcast_multigpu per issue #17243

### CODE REVIEW

**Comment by brianjo** [comment]
Updated block: 
mgpufix

**Review by soumith — APPROVED** [review]

**Review by soumith — CHANGES_REQUESTED** [review]
lint is failing.

**Comment by soumith** [comment]
```
43.17s$ flake8
./torch/distributed/distributed_c10d.py:668:81: W291 trailing whitespace
./torch/distributed/distributed_c10d.py:669:77: W291 trailing whitespace
./torch/distributed/distributed_c10d.py:670:82: W291 trailing whitespace
The command "flake8" exited with 1.

```

**Review by pietern — APPROVED** [review]

**Pull request closed without merging**
