### PR TITLE
[Quant] Add get_symmetric_qnnpack_qconfig_mapping

### PR DESCRIPTION
**Pull request by andrewor14**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #87002

Summary: Today, in order to get XNNPACK quantized ops to work,
the user must write some code that refers to private data
structures (`_FIXED_QPARAMS_OP_TO_OBSERVER`) to create a
QConfigMapping that is compatible with the symmetric constraints
in the QNNPACK BackendConfig. This is because
`get_default_qconfig("qnnpack")` produces a QConfig that does
not satisfy these constraints, and the default QConfigMapping
for QNNPACK uses this Qconfig.

Instead, we simply put this code into a helper function to make
it easier for the user to run XNNPACK quantized ops. In the
future, once there is feature parity between the set of ops
supported by QNNPACK and XNNPACK, we should revisit whether
to simply change `get_default_qconfig("qnnpack")` to return
an XNNPACK-compatible QConfig.

Test Plan:

python test/test_quantization.py
TestQuantizeFx.test_symmetric_qnnpack_qconfig_mapping

Reviewers: jerryzh168, vkuzo

Subscribers: jerryzh168, vkuzo

### CODE REVIEW

**Comment by jerryzh168** [comment]
should we make this private for now?

**Comment by jerryzh168** [comment]
I feel we may want to merge it int `get_default_qconfig_mapping`, e.g `get_default_qconfig_mapping("qnnpack@symmetric")`

**Review by vkuzo — APPROVED** [review]

**Comment by andrewor14** [comment]
> I feel we may want to merge it in `get_default_qconfig_mapping` in the future, e.g `get_default_qconfig_mapping("qnnpack@symmetric")`

Ok, sounds good

**Pull request closed without merging**
