### PR TITLE
[pytorch] For torch::from_blob() - add unowned memory hint, save alloc

### PR DESCRIPTION
**Pull request by jjlilley**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#31222 [pytorch] For torch::from_blob() - add unowned memory hint, save alloc**

- When constructing torch::from_blob() in the case where the deleter is a nop, switch to using a nullptr 
 context in the DataPtr (with a nop deleter)
- No real extra memory/cpu requirements here, actually saves a minor alloc.

Why? Trying to get a signal that a Tensor might contain non-owned memory from
torch::from_blob(), by detecting the nullptr context.

Differential Revision: [D18992119](https://our.internmc.facebook.com/intern/diff/D18992119/)

### CODE REVIEW

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit d4de199:
* **1/1** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=d4de19908add78d7fab2b385f8ae0199fabb7d10).

### 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/3941538) pytorch_linux_xenial_py3_6_gcc5_4_test (1/1)
**Step:** "Test" ([details](https://dr.pytorch.org/build-details.html?build_id=73762697))
```
Dec 13 02:53:14  
Dec 13 02:53:14 [----------] 1 test from TorchIncludeTest 
Dec 13 02:53:14 [ RUN      ] TorchIncludeTest.GetSetNumThreads 
Dec 13 02:53:14 [       OK ] TorchIncludeTest.GetSetNumThreads (0 ms) 
Dec 13 02:53:14 [----------] 1 test from TorchIncludeTest (0 ms total) 
Dec 13 02:53:14  
Dec 13 02:53:14 [----------] Global test environment tear-down 
Dec 13 02:53:14 [==========] 744 tests from 31 test cases ran. (36868 ms total) 
Dec 13 02:53:14 [  PASSED  ] 743 tests. 
Dec 13 02:53:14 [  FAILED  ] 1 test, listed below: 
Dec 13 02:53:14 [  FAILED  ] TensorTest.FromBlob 
Dec 13 02:53:14  
Dec 13 02:53:14  1 FAILED TEST 
Dec 13 02:53:14 + cleanup 
Dec 13 02:53:14 + retcode=1 
Dec 13 02:53:14 + set +x 
Dec 13 02:53:14 =================== sccache compilation log =================== 
Dec 13 02:53:14 ERROR:sccache::server: Compilation failed: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "/tmp/torch_extensions/test_compilation_error_formatting/main.cpp: In function \'int main()\':\n/tmp/torch_extensions/test_compilation_error_formatting/main.cpp:2:23: error: expected \';\' before \'}\' token\n int main() { return 0 }\n                       ^\n" } 
Dec 13 02:53:14  
Dec 13 02:53:14 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 13 02:53:14 Compile requests                115 
```


---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Comment by jjlilley** [comment]
This needs more thought... closing for now.

**Comment by xsacha** [comment]
I like the idea but maybe it needs to come with the option of providing a deleter or underlying data so that ownership can be shared

**Comment by jjlilley** [comment]
> I like the idea but maybe it needs to come with the option of providing a deleter or underlying data so that ownership can be shared

So, the non-trivial deleter case is already handled reasonably by existing codepaths; my goal here is to only touch/modify the known "trivial deleter" case.

The change does slightly optimize the trivial deleter case by avoiding an unneeded alloc and std::function<>. But my main goal is to help identify/tag these (mostly as a signal in rpc layer) with the nullptr context.

**Comment by xsacha** [comment]
Thanks.
Will in-place ops be able to perform a clone now if ownership isn't detected? Or there still wouldn't be enough information to determine that?

I know OpenCV uses a recount object, such that if it is a nullptr, it is suggested to clone when returning the underlying in a new object.
`(mat.refcount ? mat.clone() : mat)`

At the moment I assume from_blobs are available for the lifetime of the deleter if it exists but it is always possible someone provides an empty (no-op) deleter.

**Comment by jjlilley** [comment]
> Thanks.
> Will in-place ops be able to perform a clone now if ownership isn't detected? Or there still wouldn't be enough information to determine that?
> 
> I know OpenCV uses a recount object, such that if it is a nullptr, it is suggested to clone when returning the underlying in a new object.
> `(mat.refcount ? mat.clone() : mat)`
> 
> At the moment I assume underlying data from_blobs are available for the lifetime of the deleter if it exists but it is always possible someone provides an empty (no-op) deleter.

Right, with this marking added, ideally we can then create some apis with the explicit assumption that if the deleter is non-empty, that we can assume it the object stays in scope for the duration of the refcount (the inspiration is effectively folly::IOBuf::isManaged())

In talking with some folks on the Pytorch rpc side (where currently we memcpy/clone everything on send, because of this lifetime issue, but would like not to),this seemed to be a reasonable assumption for purposes of rpc.send().

(Partly because anything created in Python is basically guaranteed to meet this condition, which is the code use-case for rpc.send(). But having the ability to have this safety check for a trivial deleter seemed helpful too, to make sure we stay safe with memory lifetimes here).

**Comment by zdevito** [comment]
I don't think I am the right reviewer for this one. @ezyang or @gchanan can weigh in.

**Comment by ezyang** [comment]
The general thrust of the patch is good, but there are a bunch of unexplained insertions of AutoNonVariableTypeMode here. Can you explain the reasoning behind them?

**Comment by jjlilley** [comment]
> The general thrust of the patch is good, but there are a bunch of unexplained insertions of AutoNonVariableTypeMode here. Can you explain the reasoning behind them?

Thanks for looking. The insertions are effectively a mirror of the similar unchanged functions a few lines above in the files, but without the std::function deleter arg.

The patterns themselves are already duplicated several times in the file... I was trying to come up with a more elegant way to template/pattern this, though there wasn't an entirely clear winner (and wanted to be careful, since this was manually included in generated code).

**Comment by jjlilley** [comment]
Checking: any other thoughts here?

**Comment by ezyang** [comment]
Sorry @jjlilley you caught me right before heading off to vacation. Looking now.

**Comment by jjlilley** [comment]
> Sorry @jjlilley you caught me right before heading off to vacation. Looking now.

No worries, I was off-the-grid for ~2 weeks as well.

**Review by ezyang — APPROVED** [review]

**Comment by jjlilley** [comment]
Thanks for looking!

**Pull request closed without merging**
