### PR TITLE
[ONNX] Bump transformers in CI test

### LINKED ISSUE #117660: [ONNX] transformers version on CI is outdated
Currently, the transformers version on ONNX CI is still 4.32.1, while the released one is 4.36.2. There are lots of Config/Modeling changes that the outdated tests potentially make our guarding less robust, and it also increases the difficulty of developing/maintaining transformers related models of conversion. The version should be bumped.

### PR DESCRIPTION
**Pull request by titaiwangms**
Fixes #117660 

(1) skip dynamic tests for exported program in `test_fx_to_onnx_onnxruntime.py`, as they are not expected to pass anyway.
(2) Move dolly model to runtime, since it's working in exporting, but it is blocked by non-persistent buffers as well.
(3) openai whisper has changed/regression due to modeling modifications.
(4) Replace OpenLlama with Llama, because OpenLlama is deprecated.

### CODE REVIEW

**Review by thiagocrepaldi — COMMENTED** [review]
Maybe https://github.com/pytorch/pytorch/issues/115552 is related to this. I got failure with `4.36.0`, maybe we are lucky with `4.36.2`

**Comment by titaiwangms** [comment]
Looks like openai_whisper had some changes.

**Comment by titaiwangms** [comment]
PTAL

**Review by thiagocrepaldi — APPROVED** [review]

**Pull request closed without merging**
