### PR TITLE
[jit]C++ API parity: isinf

### LINKED ISSUE #31021: torch.jit.script return type for torch.isinf(Tensor) is bool, but method actually returns tensor
## Issue description

torch jit thinks that torch.isinf returns a boolean, but in practice it returns a BoolTensor (operates elementwise).

```
Return value was annotated as having type Tensor but is actually of type bool:
at x.py:5:4
@torch.jit.script
def foo(x: torch.Tensor) -> torch.Tensor:
    return torch.isinf(x)
```

## Code example

```
import torch

@torch.jit.script
def foo(x: torch.Tensor) -> torch.Tensor:
    return torch.isinf(x)
```

## System Info
- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- OS: mac
- PyTorch version: master
- Python version: 3.7
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

cc @suo

### PR DESCRIPTION
**Pull request by TH3CHARLie**
fixes #31021, port the legacy binding method of `isinf` to C++ therefore support JIT

### CODE REVIEW

**Comment by TH3CHARLie** [comment]
Hi, @yf225 Would you please review this PR when you are free since I think it's review-ready

**Comment by eellison** [comment]
ping @yf225 for review

**Comment by TH3CHARLie** [comment]
ping @yf225 for review

**Review by yf225 — APPROVED** [review]
@TH3CHARLie Thanks so much for the awesome work!

**Comment by TH3CHARLie** [comment]
@yf225 Thanks for the review and have a good day!

**Pull request closed without merging**
