### PR TITLE
Fix build warnings for torch_python 

### PR DESCRIPTION
**Pull request by cyyever**
Fixes #ISSUE_NUMBER

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Comment by ezyang** [comment]
keep working on it, I guess??

**Comment by cyyever** [comment]
> keep working on it, I guess??
The current CI failures are unrelated, I think the necessary changes are completed.

**Comment by ezyang** [comment]
idk man, failures look sus

**Comment by cyyever** [comment]
@ezyang Land the code changes before CMake changes.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
