### PR TITLE
ns for fx to backend_config_dict [2/x]: native lowering mappings

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #76993 ns for fx: remove duplicated BNReLU mappings
* #76992 ns for fx: remove quantized ReLU6 from mapping
* #76991 ns for fx: remove GroupNorm from mapping
* #76990 ns for fx: clean up linear in relationship mapping
* #76989 ns for fx: make torch.ops.quantized.dropout mapping dynamic
* #76988 ns for fx: remove torch.ops.quantized.cat
* #76980 ns for fx: clean up convtranspose mappings
* **#76978 ns for fx to backend_config_dict [2/x]: native lowering mappings**
* #76958 ns for fx to backend_config_dict [1/x]: fused and qat modules

Summary:

NS for FX mappings were originally hardcoded, because quantization op
mappings were not easily reusable. Now that we have `backend_config_dict`,
we can start moving NS for FX to use them and delete the hardcoded mappings.

This PR deletes the hardcoded mappings from NS about the lowering step,
and instead reads them from the lowering configs.

Note: for now, there is no way to configure the tool to use lowering
configs from a different lowering pass. That may be added at some
future point, but it's not important now.

Test plan:

```
python test/test_quantization.py -k FXNumericSuite
```

Differential Revision: [D36212235](https://our.internmc.facebook.com/intern/diff/D36212235)

### CODE REVIEW

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36212235).

**Review by jerryzh168 — APPROVED** [review]
just a comment: do we want to expose `_lower_to_native_backend.STATIC_LOWER_MODULE_MAP` as lowering configs or something?

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36212235).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36212235).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36212235).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36212235).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36212235).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36212235).

**Pull request closed without merging**
