### PR TITLE
Impl Shape op for mkldnn

### PR DESCRIPTION
**Pull request by gujinghui**
Impl Shape op for mkldnn

### CODE REVIEW

**Comment by gujinghui** [comment]
the failed case is not relevant.
@yinghai pls help review


> Dec 15 10:36:04 Installing convert-onnx-to-caffe2 script to /opt/python/3.5/bin
Dec 15 10:36:04   File "/opt/python/3.5/lib/python3.5/site-packages/caffe2/contrib/cuda-convnet2/make-data/make-data.py", line 66
Dec 15 10:36:04     print "ILSVRC 2012 %s not found at %s. Make sure to set ILSVRC_SRC_DIR correctly at the top of this file (%s)." % (name, path, sys.argv[0])
Dec 15 10:36:04                                                                                                                   ^
Dec 15 10:36:04 SyntaxError: invalid syntax
Dec 15 10:36:04 
Dec 15 10:36:04   File "/opt/python/3.5/lib/python3.5/site-packages/caffe2/contrib/cuda-convnet2/python_util/gpumodel.py", line 93
Dec 15 10:36:04     except ModelStateException, e:
Dec 15 10:36:04                               ^
Dec 15 10:36:04 SyntaxError: invalid syntax
Dec 15 10:36:04 
Dec 15 10:36:04   File "/opt/python/3.5/lib/python3.5/site-packages/caffe2/contrib/cuda-convnet2/python_util/options.py", line 46
Dec 15 10:36:04     except OptionException, e:
Dec 15 10:36:04                           ^
Dec 15 10:36:04 SyntaxError: invalid syntax

**Comment by gujinghui** [comment]
@yinghai
pls help review

**Review by yinghai — COMMENTED** [review]
I begin to wonder whether we actually need all these kind of ops intermixing `itensor` with `CPUTensor`. Can't we just add `Copy{From, To}IDEEP` ops to resolve all these issues?

**Comment by gujinghui** [comment]
@yinghai 
rebased. pls help review.

**Comment by gujinghui** [comment]
@yinghai 
Yes. Copy op can be used to solve such issue during graph optimization. We will work on it in future.
But perhaps handling intermixing tensor is still needed for some operators, for example, Shape Op in this PR.
In this Op, the output is 64 bit CPUTensor, instead of itensor, in order to be compatible with the shape definition of caffe2. If introduce Copy op between two Shape op in below pic, it should be not a good practice...

capture

**Comment by gujinghui** [comment]
@yinghai 
The failures should not be caused by this PR.

> Jan 11 07:45:15 Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /var/lib/jenkins/.torch/models/resnet18-5c106cde.pth
Jan 11 07:45:15 ERROR
Jan 11 07:45:15 test_check_onnx_broadcast (__main__.TestONNXUtils) ... ok
Jan 11 07:45:15 test_prepare_onnx_paddings (__main__.TestONNXUtils) ... ok
Jan 11 07:45:15 
Jan 11 07:45:15 ======================================================================
Jan 11 07:45:15 ERROR: setUpClass (__main__.TestHub)
Jan 11 07:45:15 ----------------------------------------------------------------------
Jan 11 07:45:15 Traceback (most recent call last):
Jan 11 07:45:15   File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
Jan 11 07:45:15     (self._dns_host, self.port), self.timeout, **extra_kw)
Jan 11 07:45:15   File "/opt/conda/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
Jan 11 07:45:15     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
Jan 11 07:45:15   File "/opt/conda/lib/python3.6/socket.py", line 745, in getaddrinfo
Jan 11 07:45:15     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Jan 11 07:45:15 socket.gaierror: [Errno -3] Temporary failure in name resolution
Jan 11 07:45:15 
Jan 11 07:45:15 During handling of the above exception, another exception occurred:
Jan 11 07:45:15 
Jan 11 07:45:15 Traceback (most recent call last):
Jan 11 07:45:15   File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
Jan 11 07:45:15     chunked=chunked)
Jan 11 07:45:15   File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
Jan 11 07:45:15     self._validate_conn(conn)
Jan 11 07:45:15   File "/opt/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
Jan 11 07:45:15     conn.connect()
Jan 11 07:45:15   File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
Jan 11 07:45:15     conn = self._new_conn()
Jan 11 07:45:15   File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
Jan 11 07:45:15     self, "Failed to establish a new connection: %s" % e)
Jan 11 07:45:15 urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f98b0ba2d30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

**Comment by gujinghui** [comment]
@yinghai
rebased. pls help review.

**Comment by Jianhui-Li** [comment]
@Yinghai  For this particular case, inserting a copy op before shape op is too expensive since it triggers reordering. Since the shape op just needs to take out the dims, having the shape op supported by MKL-DNN bridge can avoid the reordering overhead.

**Review by yinghai — APPROVED** [review]

**Pull request closed without merging**
