### PR TITLE
Initialize cuda tensor in fake tensor

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #102027

Fix for https://github.com/pytorch/pytorch/issues/92627

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ezyang** [comment]
It would be nice if fake tensor with cuda doesn't need to initialize cuda, but this seems... difficult lol

**Comment by eellison** [comment]
I agree in principle but I'm not sure it's worth the headache...

**Pull request closed without merging**
