### PR TITLE
update torch.narrow doc

### LINKED ISSUE #84783: [doc] torch.narrow support for `start` arg as Tensor is undocumented
### 📚 The doc issue

Ref: https://pytorch.org/docs/stable/generated/torch.narrow.html

https://github.com/pytorch/pytorch/blob/01c54ad6dedf2ab0206a37f6df1af4fe41afa051/aten/src/ATen/native/native_functions.yaml#L3685-L3688

### Suggest a potential alternative/fix

_No response_

cc @svekars @holly1238

### PR DESCRIPTION
**Pull request by kshitij12345**
Fixes #84783

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by kshitij12345** [comment]
@kit1980 is it ok to force merge this? I don't think there is point in letting the CI run.

**Comment by kit1980** [comment]
> @kit1980 is it ok to force merge this? I don't think there is point in letting the CI run.

OK to force-merge.

**Pull request closed without merging**
