### PR TITLE
fix another missing c10::

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #77905

### CODE REVIEW

**Comment by davidberard98** [comment]
cc @sheldonfrith

**Comment by Sheldonfrith** [comment]
@davidberard98  Thanks for handling this so quickly! I still haven't had time to test it out, but I'll let you know ASAP, I expect this will have solved the problem.

**Review by tugsbayasgalan — APPROVED** [review]

**Comment by Sheldonfrith** [comment]
Seems to be fixed for me

**Pull request closed without merging**
