### PR TITLE
DistributedDataParallel._post_forward, fix return

### PR DESCRIPTION
**Pull request by albertz**
Fix `return` in case of `_delay_all_reduce_all_params`.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @kiukchung @lucasllc @d4l3k

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
We may want to enable Ruff rule `RET502` to catch these implicit None returns later.

**Review by albanD — COMMENTED** [review]
Is there a test we can have to trigger this?

**Comment by fegin** [comment]
I don't think delayed allreduce is used anywhere. I'll reach out to the author to see if we should delete it given that the we are using DDPOptimizer to achieve communication and computation overlapping and we will have a DDP + compile_autograd in the future.

**Review by fegin — APPROVED** [review]
Thanks for the fix!

**Pull request closed without merging**
