### PR TITLE
masked argmin and argmax

### PR DESCRIPTION
**Pull request by george-qi**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #74525

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]

**Review by cpuhrsch — APPROVED** [review]

**Comment by seemethere** [comment]
> @pytorchbot revert this

Can we have a link to failed CI in our revert this message in the future?

**Comment by zengk95** [comment]
This was breaking 
 linux-bionic-rocm4.5-py3.7-distributed 
 linux-bionic-py3.7-clang9-slow

Link to Commit: https://hud.pytorch.org/pytorch/pytorch/commit/cb687773fba647769143d0c7b051ca41f2b3a55f 
image

**Pull request closed without merging**
