### PR TITLE
Workaround to let functionalization work with sparse tensors; fixes dlrm

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #90407

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]

**Comment by ezyang** [comment]
whoa, this is some nasty ci failure

**Review by bdhirsh — APPROVED** [review]
>    A more proper fix would be to have a SparseFunctionalTensorWrapper that models sparse correctly.

uh oh lol

**Comment by bdhirsh** [comment]
i bet you're running into problems because that change is activating the LazyTensor code-path (I don't think LazyTensorImpl has a storage either).

Maybe there's a better check `.is_sparse()` that we can use, instead of `!x.has_storage()`?

**Comment by ezyang** [comment]
@jbschlosser handled this one

**Pull request closed without merging**
