### PR TITLE
[DataPipe] Make Demux serializable with lambda function

### PR DESCRIPTION
**Pull request by ejguan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#71311 [DataPipe] Make Demux serializable with lambda function**

- Move warning about lambda function to a function that can be reused
- Make sure lambda function inside Demux is handled by dill if available

Differential Revision: [D33584552](https://our.internmc.facebook.com/intern/diff/D33584552)

cc @VitalyFedyunin @ejguan @NivekT

### CODE REVIEW

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33584552).

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33584552).

**Review by NivekT — COMMENTED** [review]
This mostly makes sense, two things:

1. `Demultiplexer` returns a `_ChildDataPipe`. Do we want that to be serializable as well?
2. Can we add some tests to confirm this work?

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33584552).

**Review by NivekT — APPROVED** [review]
LGTM! Thanks!

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33584552).

**Pull request closed without merging**
