### PR TITLE
Replaced multiprocessing.queues.SimpleQueue with multiprocessing.Queue

### LINKED ISSUE #14888: Missing args in constructor of torch.multiprocessing.pool.Pool
## 🐛 Bug

In the constructor of `torch.multiprocessing.pool.Pool` (lines 23 and 24), two `torch.multiprocessing.queue.SimpleQueue`s are created with no args. The constructor of `SimpleQueue` requires one key-word arg, `ctx`, though. Therefore, initializing a `Pool` results in a `TypeError`.

## To Reproduce

```python
>>> from torch.multiprocessing import pool
>>> p = pool.Pool()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/patrick/anaconda3/envs/dummy/lib/python3.6/multiprocessing/pool.py", line 157, in __init__
    self._setup_queues()
  File "/home/patrick/anaconda3/envs/dummy/lib/python3.6/site-packages/torch/multiprocessing/pool.py", line 23, in _setup_queues
    self._inqueue = SimpleQueue()
TypeError: __init__() missing 1 required keyword-only argument: 'ctx'
```

## Environment

 - PyTorch Version: 0.4.1
 - OS: Ubuntu 16.04.5 LTS
 - How you installed PyTorch: `conda`
 - Python version: 3.6
 - CUDA/cuDNN version: CPU-only (but happens with GPU as well)

### PR DESCRIPTION
**Pull request by yet-another-account**
Fixes #14888

### CODE REVIEW

**Comment by SsnL** [comment]
This seems to fail on py2. Could you add a py version check? Also, this needs a test.

**Comment by ailzhang** [comment]
@eukaryote31 Please add a test in `test/test_multiprocessing.py` to reflect what has been fixed in this PR. And then this PR should be ready to go. :D Thanks!

**Comment by eukaryote31** [comment]
How should I test this? There are already tests that instantiate and test Pool and therefore Queue (the original bug was a fail on instantiation of Pool in py3), so a test that just instantiates Queue seems a bit redundant.

**Comment by ailzhang** [comment]
@eukaryote31 The failed tests looks legit. Could you take a look?

**Comment by ailzhang** [comment]
@eukaryote31 The failed test still seems legit to me hmmmm.

**Comment by eukaryote31** [comment]
I did some further research, and it seems that expected behavior in python >=3.4 for multiprocessing.pool.* and multiprocessing.queues.* is to require a context. The resolution to #14888 would be to use torch.multiprocessing.* instead.

**Pull request closed without merging**
