### PR TITLE
Change >= in the GRU and the LSTM document to \ge

### PR DESCRIPTION
**Pull request by bitsandscraps**
Change >= in the GRU document to \ge

### CODE REVIEW

**Review by mikaylagawarecki — COMMENTED** [review]
Thanks! Can you fix [the corresponding line in LSTM as well ](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/rnn.py#L598)

**Comment by bitsandscraps** [comment]
> Thanks! Can you fix [the corresponding line in LSTM as well ](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/rnn.py#L598)

I fixed it!

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
