### PR TITLE
Add HIP to the memory profiler device list

### PR DESCRIPTION
**Pull request by ilia-cher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #38797 Filter out "unsigned short", "is_complex" in profiler output
* **#38795 Add HIP to the memory profiler device list**

Summary:
Add HIP alongside CUDA

Test Plan:
rocm CI

Differential Revision: [D21665627](https://our.internmc.facebook.com/intern/diff/D21665627)

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
let's wait for CI

**Comment by jeffdaily** [comment]
Beat me to it.  I was just about to push the same PR.  I tested this PR locally and it passed.

BTW ROCm CI might be failing now due to an unrelated change that landed while this memory profiler failure was blocking ROCm CI.

**Comment by ilia-cher** [comment]
yes, I remember, unfortunately rocm build was not passing before my PR landed

**Comment by ilia-cher** [comment]
"test_memory_profiler (__main__.TestAutograd) ... ok"
in
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28720/consoleFull

**Comment by ilia-cher** [comment]
and bloat16 tests are broken on the trunk
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28725//console

**Comment by ilia-cher** [comment]
https://ezyang.github.io/pytorch-ci-hud/build/pytorch-master

**Comment by jeffdaily** [comment]
bfloat16 tests should be fixed by this https://github.com/pytorch/pytorch/pull/38823, we were just waiting for it to merge.

We are aware of the build dashboard, and check it if not once but many times a day, due to upstream commits frequently landing without ROCm CI passing.

We need help from the community and the maintainers to make ROCm CI more stable, e.g. not landing PRs with known breakage for ROCm back-end. Meanwhile, we are trying our best to improve the CI maintenance process and our software quality.

**Pull request closed without merging**
