### PR TITLE
dynamo tracing perf: import in build: 60.48 -> 59.92

### PR DESCRIPTION
**Pull request by aorenste**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #143061
* #143070
* #143069
* #143063
* #143062
* #143057
* #143068
* #143067
* #143065
* #143064
* #143060
* #143059
* #143058
* __->__ #143056
* #143066

A series of directed perf improvements to drive down the dynamo tracing cost of
the given test. Before this PR stack the compile took about 60s, and after takes
30s. Individual improvements are listed below along with the approximate
improvement of that change.

Tested with this model:
```
@torch.compile(backend="eager")
def model_add(x, y):
    out = x
    for i in range(5000):
        out = torch.add(out, y)
    return out
```

This PR: Stop importing builder in the inner loop of `VariableTracker.build()`

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Comment by ezyang** [comment]
I'm a little icky about relying on other imports implicit causing builder to have been transitively imported. Since the access to the imported module is done in a function, another way you can do it is by moving the import to the end of the file (which also breaks an import cycle)

**Review by jansel — APPROVED** [review]

**Comment by aorenste** [comment]
> I'm a little icky about relying on other imports implicit causing builder to have been transitively imported. Since the access to the imported module is done in a function, another way you can do it is by moving the import to the end of the file (which also breaks an import cycle)

Unfortunately python still won't accept putting the import at the end - it still complains about a cycle (I suspect because the cycle is bigger than 2 nodes).

I have a slightly different fix which should make it more acceptable.

**Comment by ezyang** [comment]
I don't understand, why did you not just move the import to the bottom of the file as suggested?

**Comment by aorenste** [comment]
> I don't understand, why did you not just move the import to the bottom of the file as suggested?

As I replied earlier:

> Unfortunately python still won't accept putting the import at the end - it still complains about a cycle (I suspect because the cycle is bigger than 2 nodes).
> 
> I have a slightly different fix which should make it more acceptable.

**Comment by ezyang** [comment]
Oh for some reason ghstack keeps spamming the PR with commit referenced this PR 🤔

**Comment by ezyang** [comment]
TBH this seems worse 🤔

**Pull request closed without merging**
