### PR TITLE
[ONNX] Return input itself for non-fp inputs and support decimals for aten::round op

### PR DESCRIPTION
**Pull request by CYuxian**

### CODE REVIEW

**Comment by justinchuby** [comment]
Thanks for contributing! Could you enable the test in https://github.com/pytorch/pytorch/blob/f95018c2813ce5239cb956de8549f4b17005e43f/test/onnx/test_op_consistency.py as well?

**Comment by janeyx99** [comment]
Adding @justinchuby as reviewer fyi

**Comment by CYuxian** [comment]
> Thanks for contributing! Could you enable the test in https://github.com/pytorch/pytorch/blob/f95018c2813ce5239cb956de8549f4b17005e43f/test/onnx/test_op_consistency.py as well?

Sure. Just enabled the test in test_op_consistency.py. Please help to review, thanks!

**Review by justinchuby — APPROVED** [review]

**Pull request closed without merging**
