### PR TITLE
Support tensor stride

### PR DESCRIPTION
**Pull request by shengfukevin**
Summary:
X-link: https://github.com/facebookresearch/param/pull/126

Support tensor stride for execution trace.

Test Plan: buck2 test mode/opt caffe2/test:test_profiler_cuda profiler.test_execution_trace.TestExecutionTrace

Differential Revision: D58900476

### CODE REVIEW

**Review by sanrise — APPROVED** [review]
LGTM.

**Review by izaitsevfb — APPROVED** [review]

**Comment by shengfukevin** [comment]
topic: not user facing

**Pull request closed without merging**
