### PR TITLE
[Dev Container][CUDA]Fix linker path

### PR DESCRIPTION
**Pull request by youkaichao**
Building with CUDA in dev container leads to error: `cannot find -lcudart_static`. This is because the libraries are under a custom CUDA_HOME, and `ld` cannot find it.

Updating the `LDFLAGS` environment variable works.

### CODE REVIEW

**Comment by youkaichao** [comment]
@drisspg where can we put some notice to warn users that running CUDA devcontainer requires NVIDIA Container Toolkit?

**Review by drisspg — APPROVED** [review]
Thank you!

**Comment by youkaichao** [comment]
@drisspg how do you like a README in the .devcontainer folder? If you agree, I can draft the README tomorrow.

**Comment by drisspg** [comment]
Yup I think thats a great idea, lets do that in a follow up PR

**Pull request closed without merging**
