### PR TITLE
remove redundant sccache wrappers from build.sh scripts

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jeffdaily** [comment]
@malfet I added the rocm label because after further consideration, it seems this will only end up affecting ROCm CI builds.

**Comment by jeffdaily** [comment]
@malfet post-holiday ping

**Comment by jeffdaily** [comment]
I suppose I should spread the work a bit and not repeatedly ask @malfet for all reviews.  @walterddr?

**Comment by walterddr** [comment]
looks good. is this a continuation of https://github.com/pytorch/pytorch/pull/47947 ?

**Review by walterddr — APPROVED** [review]

**Comment by jeffdaily** [comment]
@walterddr related, yes, because we did a small audit of how we're using sccache when we started facing issues with it in our public docker images, and found this redundancy.  This removed code became redundant when ROCm moved to the circleci-based images that already install the sccache wrappers.

**Pull request closed without merging**
