### PR TITLE
Allow disabling bias for Transformer

### PR DESCRIPTION
**Pull request by janEbert**
As used by T5 and PaLM, citing "increased training stability for large models" (https://arxiv.org/abs/2204.02311).

Depends on #101683, which allows disabling bias for `LayerNorm`s. Marked as draft due to this.

### CODE REVIEW

**Comment by janEbert** [comment]
Since https://github.com/pytorch/pytorch/pull/101683 is merged, this can now also be reviewed.
@mikaylagawarecki since you were involved in the previous LayerNorm without bias merge, would you be so kind to remove the `Stale` label here?

**Review by mikaylagawarecki — APPROVED** [review]
LGTM

**Pull request closed without merging**
