### PR TITLE
add default argument device type api

### LINKED ISSUE #103828: simple and small optimization: default device argument for custom device
### 🚀 The feature, motivation and pitch

1、For many operators(such as pin_memory), the device argument is  default as `cuda` if not given; but for other device, we must have to give extra argument device_type comparing to cuda, so we add an API to set the default argument device just once at the begining to keep usage consistent with cuda.
2、And there are some API defined in Python, we add a argument named device_type and the default value is cuda, (such as https://github.com/pytorch/pytorch/blob/main/torch/random.py#L104), so that we could support more device (privateuse1 device).
So we want to add an API to set the default argument device just once at the begining to keep usage consistent with cuda, and add an api to get the default device to keep usage consistent with cuda if not gived device_type.

### Alternatives

_No response_

### Additional context

_No response_

cc @albanD

### PR DESCRIPTION
**Pull request by heidongxianhua**
Fixes #103828
1、For many operators(such as pin_memory), the device argument is cuda if not given; but for other device, we must have to give extra argument device_type comparing to cuda, so we add an API to set the default argument device just once at the begining to keep usage consistent with cuda.
2、And there are some API defined in Python, we add a argument named device_type and the default value is cuda, so that we could support more device (privateuse1 device). So we use the this api to get the default device to keep usage consistent with cuda if not gived device_type.

### CODE REVIEW

**Comment by albanD** [comment]
Wasn't @ezyang looking at this feature?

**Comment by ezyang** [comment]
I NACKed it though, in a separate pr...

**Comment by heidongxianhua** [comment]
> I NACKed it though, in a separate pr...

yeah, I made some comments in this issue https://github.com/pytorch/pytorch/issues/103828, could we have a look again?

**Pull request closed without merging**
