### PR TITLE
[c10d] remove non-necessary tests

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #131210
* #131211
* __->__ #131212

as titled, comm tensor is not being actively used as we approached the
functional collectives as our collective tracing approach

cc @XilunWu @H-Huang @awgu @kwen2501 @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

Differential Revision: [D60132520](https://our.internmc.facebook.com/intern/diff/D60132520)

### CODE REVIEW

**Review by XilunWu — APPROVED** [review]

**Comment by wanchaol** [comment]
@wanchaol has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60132520).

**Pull request closed without merging**
