### PR TITLE
Dynamically scheduled dataloader

### PR DESCRIPTION
**Pull request by GuillaumeLeclerc**
Hello,

After using pytorch for a while I realized that the dataloader could be improved. (I saw few things on the discuss [forum](https://discuss.pytorch.org/t/how-to-prefetch-data-when-processing-with-gpu/548/3)).

# The current architecture

Here is what I understand from the current architecture of the multiprocess dataloader.

existing architecture

1. The sample generate batches
2. Batches are put in a queue
3. A Worker take a batch, process it, collate and put the batch in another queue
4. Main thread take processed batch from the output queue and reorder them

## Disadvantages

- Since an entire batch is assigned to a single worker, the first batch will not be outputed before the first worker process `batch_size` elements. Adding more workers will not reduce this starting time.
- The amount of memory is proportinal to the number of workers (`2 x num_workers` batches are primed).
- If some baches takes longer than the others, workers might be left without work while the main thread is wating for another.
- The computation power is not focused on the next batch, even if the main thread is starving.

# Suggested Architecture

The key idea is to have an dataset element as a working unit instead of a batch. The second key idea is to use a circular buffer of k lists (like double/triple buffering in computer graphics application)

### Step 1

The main thread append to a first queue all the elements in the batch, `num_workers - 1` makers `Next` and one maker `Collate`. 
step 1

### Step 2

Workers start consuming the queue and retrieve the data from the dataset and put it in another queue the `collate_queue`. Elements might be reorderd during this phase. In the meantime the main thread start filling the queue the queue for the next batch (if the `preload_batches` parameter allows it).

step 2

### Step 3 

When workers reach the end of the queue they will start consuming `Next` markers. When it happens. It jumps from the current queue to the next one. The last remaining one will consume a `Collate`. The one who pick this one is will jump to the `collate_queue`. It consume the entire queue. Reorder elements in the batch and put the collated batch in the `data_queue`. In the meantime, if there are elements in the next queue, other workers start working on the next batch.

step 3

### Step 4

We continue the process for all batches. When the main_thread reach the last queue (the number of queue is `preload_batches + 2`), it waits until the first one is completely empty and reuse it. This way we don't allocate a queue per batch.

step 4

## Key points

- [x] We limit the memory usage
- [x] All workers work in priority for the next batch
- [x] Users can control the amount of prefetching
- [x] No matter what, we always use 100% of the CPU unless we have prefetched what the user asked
- [x] All existing test pass
- [ ] Elements are loaded in order. This is not the case because we prallelize every element in a batch
- [ ] All Exception raised are reported. This is not the case because to mimic the behavior of the old architecture, only the first exception of the batch is raised.

# Conclusion

- What do you think ?
- Should it be a separate module or should it replace the existing `DataLoader` ?
- Would it be considered a breaking change since user code could assume that `__getitem__` is called in order ?
- Anything should be improved ?

Thank you for your feedback

### CODE REVIEW

**Comment by GuillaumeLeclerc** [comment]
Do not merge yet. I think there is a race condition somewhere. It should be a discussion for now.

**Comment by colesbury** [comment]
Do you have benchmarks for some workloads?

There's often a significant cost to copying tensors into shared memory. I'm worried that doing this per-sample instead of per-batch is going to increase the total cost.  Some benchmarks with common workloads would help.

**Comment by apaszke** [comment]
It should still be possible to avoid this copy - the main process could allocate a big tensor for a batch in shared memory, send it to the workers, and have them fill the corresponding slices. But it might be hard to implement, because one has to know the structure of the batch upfront

**Comment by GuillaumeLeclerc** [comment]
@colesbury You are right. I tried using it on large datasets and I could not make it work because threads get locked in [here](https://github.com/GuillaumeLeclerc/pytorch/blob/98677bc7ce9cefa6ff694db3cf7d7c241a843ea4/torch/utils/data/dataloader.py#L78). I don't know enough about python multiprocessing to guess how such a thing can happen. I will have to dig into it

@apaszke That would be perfect, but you are right, guessing the size of the batch might be super complicated especially when elements are dictionaries or with custom collate functions. I will try to think about it. In a sense it's awesome that datasets and data loaders are so flexible but it makes things more complicated. We could make assumptions that each batch has the same size and get the size from the first batch and speed up upcoming ones. It would not work in some situations (eg, some RNNs). We could compute the first element and get the width of the tensors and it would be safe to allocate `width x batch_size` but that requires finishing the first element before allocating the memory and that would slow things.

**Comment by vfdev-5** [comment]
@GuillaumeLeclerc I was just wondering why you need multiple `idx_queue`s and `collate_queue`s. For example, consider a single index queue and collate queue, no NEXT:
```
[Sampler] -----> index queue    [ (batch 1, idx 1), (batch 1, idx 2), (batch 1, idx 3), ... (batch 1, idx N), (Collate), (batch 2, idx 1) ... ]
                                        |              |
  Workers                              <w1>           <w2>
                                        |              |
                                        v             v
                  collate queue [ f(b1, idx 1), f(b1, idx 2)  ]---<w3>----> [Reorder, Collate]
                    
```
A worker that gets "Collate" passes to the collate queue and the others continue to work with the index queue.

**Comment by weiyangfb** [comment]
@guillaumekln any update on this work?

**Comment by GuillaumeLeclerc** [comment]
I implemented this as part of: https://github.com/libffcv/ffcv/ So this PR is indeed stale

**Pull request closed without merging**
