### PR TITLE
Fixes format utils executable

### PR DESCRIPTION
**Pull request by LucasLLC**
Fixes an issue with the format utils executable, which was causing it to run as a no-op. :( 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### CODE REVIEW

**Review by wz337 — APPROVED** [review]
Thanks for the quick fix!

**Review by fegin — APPROVED** [review]
LGTM

**Comment by huydhn** [comment]
Checking with @atalman that we don't accept any more cherry picks for 2.3.0, so let's get this one queue for 2.3.1

**Comment by huydhn** [comment]
https://github.com/pytorch/pytorch/pull/123482 can be the cherry pick PR for 2.3.1

**Pull request closed without merging**
