### PR TITLE
Use fake PG for test_compute_comm_reordering.py unit tests

### PR DESCRIPTION
**Pull request by yf225**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #131415

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @ezyang @anijain2305 @chauhang @penguinwu

### CODE REVIEW

**Review by yifuwang — APPROVED** [review]
Very nice! It seems that we can check `self.assertTrue(same(out, correct))` even when using fake pg?

**Comment by yf225** [comment]
Note to self: check regular distributed CI test job runs `test_compute_comm_reordering.py`, before merging.

**Pull request closed without merging**
