### PR TITLE
Revert " log process group config in distributed info" for otest failure

### PR DESCRIPTION
**Pull request by shengbao-zheng**
Summary:

We're generating a revert to back out the changes in this diff, please note the backout may land if someone accepts it.

If you believe this diff has been generated in error you may Commandeer and Abandon it.

Test Plan: NA

Reviewed By: shengbao-zheng

Differential Revision: D53075086

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]

**Review by aaronenyeshi — APPROVED** [review]
@pytorchbot merge -f

**Comment by aaronenyeshi** [comment]
This has been reverted in OSS: https://github.com/pytorch/pytorch/commit/3d062f9abe9db13119b31bf810cc4834dc2d9a26 and internally: D53075086. Abandoning this PR. cc @DanilBaibak

**Pull request closed without merging**
