### PR TITLE
[1.6] Proposed warning change for DataLoader with IterableDataset

### PR DESCRIPTION
**Pull request by ssnl**
cherry pick https://github.com/pytorch/pytorch/pull/40344

cc @zou3519

### CODE REVIEW

**Comment by zou3519** [comment]
I asked @VitalyFedyunin to take a look at this and his opinion was that it might be too risky to cherry-pick this at the last minute and the suggestion was to postpone until 1.7.

**Comment by SsnL** [comment]
@zou3519 Hmm there is virtually no functionality change though? Is that still too risky?

**Comment by SsnL** [comment]
It is okay that this gets left out. I just really hope that this gets in :).

**Comment by VitalyFedyunin** [comment]
@ssnl it is not risky (at least doesn't seems so), but creates bad pattern when we are trying to squeeze changes into the release branch at very last moment.

**Pull request closed without merging**
