### PR TITLE
Extend XPU merge rules: Add torch/csrc/xpu/, torch/xpu/ and test/xpu

### PR DESCRIPTION
**Pull request by EikanWang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #122856

### CODE REVIEW

**Review by atalman — APPROVED** [review]
LGTM

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Looks good to me, though let's be careful with avoiding code duplication in those folders

**Pull request closed without merging**
