### PR TITLE
[inductor] make conv template work with symbolic stride/padding

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #132938
* #132952

Fix https://github.com/pytorch/pytorch/issues/132716 

The triton template for convolution does not work when the stride or padding contains dynamic shape. Use the hint and add guards to handle that. An alternative is to fallback to eager, but since I've seen the lowering rule for convolution use the hint in other cases, I'll just follow the convention.

I don't really know how to add a unit test here since I need create symbolic strides (not strides of a tensor but the stride parameter for convolution) and paddings. I can try harder if reviewer swants me to add unit tests.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
tests are failing

**Comment by shunting314** [comment]
I checked the test failure for `python test/inductor/test_torchinductor.py -k test_convolution5_cpu`

The error is caused by adding `dilation = tuple(V.graph.sizevars.evaluate_static_shapes(dilation))` to the lowering of convolution. That causes some constraint violation: https://gist.github.com/shunting314/d3e9aab775bfd02a3198157f93c02575 .

Running the corresponding cuda (test_convolution5_cuda) test is fine though. cc @ezyang 

On the other hand, we don't really need to call `evaluate_static_shape` on dilation or output_padding since the template is only used when they are 1 and 0 respectively. That could work around this issue.

**Comment by ezyang** [comment]
It shouldn't be too hard to exercise this in a test, just dynamic=True, pass in a bunch of ints and then add some asserts on sizes you want to be static.

I don't have too much problem accepting this as is, though I am feeling some type confusion here: are sympy expressions accepted in ConvLayoutParams? Or are you just taking advantage of some outrageous coincidence where we're not actually going to go down the template route if something isn't 1 (which it won't be, if it's symbolic) and so you never get into trouble. This is one of those places where if we had accurate "does this take int, or sympy.Expr | int" everywhere in Inductor, I feel this would be quite helpful for people.

**Review by jansel — APPROVED** [review]

**Review by eellison — APPROVED** [review]

**Comment by shunting314** [comment]
> I am feeling some type confusion here: are sympy expressions accepted in ConvLayoutParams? Or are you just taking advantage of some outrageous coincidence where we're not actually going to go down the template route if something isn't 1 (which it won't be, if it's symbolic) and so you never get into trouble. This is one of those places where if we had accurate "does this take int, or sympy.Expr | int" everywhere in Inductor, I feel this would be quite helpful for people.

Yea, the type hint is a bit confusing. At least for the failed model, the stride can be symbolic int.

Maybe related to those mypy comments at the beginning of the file:
```
# mypy: allow-untyped-decorators
# mypy: allow-untyped-defs
```

**Comment by shunting314** [comment]
@pytorchbot merge -i

Test failure on arm64 are not related.

**Pull request closed without merging**
