### PR TITLE
Don't error if _warned_capturable_if_run_uncaptured not set

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #80345

This can happen if an optimizer was pickled.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Review by albanD — APPROVED** [review]
We really need people to save state dict and not python objects...

**Pull request closed without merging**
