### PR TITLE
[torch/elastic] Remove typing.final decorator as it is not compatible with < CPython 3.8

### PR DESCRIPTION
**Pull request by cbalioglu**
Remove typing.final decorator as it is not compatible with < CPython 3.8.

### CODE REVIEW

**Review by t-vi — APPROVED** [review]
Seems like a good quick fix. Of course, we should look into how we deal with this more generally (if we haven't some solution somewhere in PyTorch already).

**Comment by cbalioglu** [comment]
> Seems like a good quick fix. Of course, we should look into how we deal with this more generally (if we haven't some solution somewhere in PyTorch already).

This was mostly a combination of my fault as a new employee and the lack of support for stacked commits in the internal tooling I have used. I agree that there should be a mechanism to prevent commits without a valid PR. I was assuming that CircleCI tests were executed as part of our internal tooling. Apparently that is not the case.

**Comment by t-vi** [comment]
With "general solution" I meant solution for "use newer type-checking features while not breaking use with older versions of PyTorch". I should have made more clear that I only wanted to comment on the code, sorry about that.

**Comment by rgommers** [comment]
> This was mostly a combination of my fault as a new employee and the lack of support for stacked commits in the internal tooling I have used. 

No worries, thanks for the quick fix. Are you aware of https://github.com/ezyang/ghstack? That's what's normally used to have stacked PRs that GitHub understands.

**Comment by cbalioglu** [comment]
> > This was mostly a combination of my fault as a new employee and the lack of support for stacked commits in the internal tooling I have used.
> 
> No worries, thanks for the quick fix. Are you aware of https://github.com/ezyang/ghstack? That's what's normally used to have stacked PRs that GitHub understands.

Thanks for the tip! In fact I was aware of ghstack, but used the more "conventional" manual export approach in the internal diff tooling. Apparently stacked commits are not properly supported that way, but it was too late by the time I realized it; so we made a one-time exception and reviewed the corresponding diffs internally without a PR (thinking CircleCI tests would still run). Going forward I will make sure to use ghstack.

**Pull request closed without merging**
