### PR TITLE
[caffe2] Remove ShuffleNet from model zoo.

### PR DESCRIPTION
**Pull request by orionr**
* No longer supported.

### CODE REVIEW

**Comment by orionr** [comment]
Looks like tests are failing at https://ci.pytorch.org/jenkins/job/caffe2-master/916/ because of this.

**Review by houseroad — APPROVED** [review]

**Comment by houseroad** [comment]
I will remove it from ONNX model zoo soon as well. :-)

**Comment by orionr** [comment]
Yup - my fault for removing all of this. :) Thanks @houseroad

**Comment by houseroad** [comment]
Not a problem at all. :-)

**Pull request merged**
