### PR TITLE
Install dvipng and latex in doc build.

### LINKED ISSUE #23294: Equations in the document do not display properly: Their LaTeX code is shown instead
The current master document does not display equations properly. Rather, their LaTeX code is displayed. For example, [torch.sin()](https://pytorch.org/docs/master/torch.html#torch.sin).

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#23302 Install dvipng and latex in doc build.**

Fixes #23294

Signed-off-by: Edward Z. Yang <ezyang@mit.edu>

### CODE REVIEW

**Comment by ezyang** [comment]
Manual inspection of doc build confirms that this is working:

```
Jul 24 15:57:06 ++ git status
Jul 24 15:57:07 On branch site
Jul 24 15:57:07 Your branch is up-to-date with 'origin/site'.
Jul 24 15:57:07 Changes to be committed:
Jul 24 15:57:07   (use "git reset HEAD <file>..." to unstage)
Jul 24 15:57:07 
Jul 24 15:57:07 	modified:   docs/master/__config__.html
Jul 24 15:57:07 	new file:   docs/master/_images/math/00105ac5a121cd7558127291965caf5b0425217c.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/002159fdc9fce5dde714f121c42f889eba6c0de4.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/007e2ce817bcc3e90c715c2e8ef0b7bf0c3fad40.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/00b3df8aa45c41ab69e4f7ca5a1cda3eae66d023.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/00cd0261cb1558b235052a3664085c747e7d48f3.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/00d5886c4e369ace7699ba8a4d34e2140e21b9b0.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/013626201490399e5a454f1a160dc48578883996.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/013ddb42eac665151e695343773e5bd33e7ce575.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/0161b8617e7795ff2dd36af6fd6e67e2f0a853af.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/01726ecb5505c2c60723fe2549acc5f02e9adc8c.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/02d98909b5d6acd6a7ff927d4d42790bdd407d58.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/02e8f7e2873eb89845576997fb64dacb04056cb0.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/04275c87369e780c2f42b27f27cfc91b752f4ce9.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/04566a1c99d0c0648be2aba3514d3e94c45c8fef.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/04bc7fd2f47eae4ebc6d65e9339e615568fe5998.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/055ab8e83af7358795a860c4b2b3ab7c16158e8d.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/0577ae887b33df741f0e84c0a8eacb09f818f77c.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/05e9e2e998783c60d7d6ffe418309605969df9c7.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/063fdb1073fe6ba2e8dcce2258c9b40f87f722aa.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/06587b43a42547941f33e78dd8584638f6e768c1.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/069b97a3df50e2a2b5a84623a5279c2e4e855d0c.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/06e4c2844113ebe6856ea0bbf309d2d145711961.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/0705ca294b108adc11d4267e62269e36a2acaa99.png
Jul 24 15:57:07 	new file:   docs/master/_images/math/075615abf7466dfa600630602ad19a424154bc93.png
```

**Comment by vishwakftw** [comment]
Isn't texlive-latex-extra a bit too large to download and run? We could perhaps make do with a minimal option with amsmath and amssymb support.

**Comment by xuhdev** [comment]
I have no problem with current change. Just wanna confirm whether you wanna try the svg format (by setting [imgmath_image_format](https://shimizukawa-sphinx.readthedocs.io/en/latest/ext/math.html#confval-imgmath_image_format) to svg, which looks nicer and requires very little work from browser.

**Comment by ezyang** [comment]
Abandoning in favor of inline katex

**Pull request closed without merging**
