### PR TITLE
[Reland] Remove calls of c10::either

### PR DESCRIPTION
**Pull request by cyyever**
While there were FB issues encountered when removing c10::either #109299 , we should be able to change OSS code.

cc @clee2000

### CODE REVIEW

**Review by clee2000 — APPROVED** [review]

**Comment by clee2000** [comment]
I think this broke test_cpp_extensions_aot_no_ninja on windows cuda. Error looks like https://hud.pytorch.org/pytorch/pytorch/commit/e4d8ec9fe82b6186efbff0e2a7b8393b157ef298

**Comment by atalman** [comment]
HI @clee2000 I agree I am looking at this error now. Kicked periodic workflow on this PR to confirm

**Comment by atalman** [comment]
@pytorch revert -m "Broke windows periodic tests" -c nosignal

**Comment by cyyever** [comment]
@clee2000 It was likely a MSVC bug

**Pull request closed without merging**
