### PR TITLE
fixes torch.jit.script lp_pool bug.

### LINKED ISSUE #60258: torch.jit.script has too strict type checks for torch.nn.LPPool2D and torch.nn.functional.lp_pool2d
## 🐛 Bug

When using ```torch.jit.script(...)``` on a model with ```torch.nn.LPPool2D``` or ```torch.nn.functional.lp_pool2d``` errors are thrown for hyper-parameters that are valid for running the model.

## To Reproduce

```python
import torch

class Model(torch.nn.Module):
        def __init__(self):
                super().__init__()
                self.l = torch.nn.LPPool2d(2, 3)
                self.n = torch.nn.LPPool2d(2, (7, 1)) # fails: Expected a value of type 'int' for argument 'kernel_size' but instead found type 'Tuple[int, int]'.

        def forward(self, x):
                o = []
                o.append(self.l(x))
                o.append(self.n(x)) # fails: Expected a value of type 'int' for argument 'kernel_size' but instead found type 'Tuple[int, int]'.
                o.append(torch.nn.functional.lp_pool2d(x, float(2), 3))
                o.append(torch.nn.functional.lp_pool2d(x, 2, 3)) # fails: Expected a value of type 'float' for argument 'norm_type' but instead found type 'int'.
                o.append(torch.nn.functional.lp_pool2d(x, float(2), (7, 1))) # fails: Expected a value of type 'int' for argument 'kernel_size' but instead found type 'Tuple[int, int]'.
                return o

model = Model()
x = torch.rand(1, 3, 7, 7)
print(*model(x), sep="\n") 
torch.jit.script(model)
```

While ```model``` can just be executed, ```torch.jit.script``` will fail on all marked lines

## Expected behavior

```torch.jit.script(...)``` parses the model without throwing errors.

## Environment

```
Collecting environment information...
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.3.4

Python version: 3.6 (64-bit runtime)
Python platform: Linux-3.10.0-1160.25.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0+cu111
[pip3] torchvision==0.10.0+cu111
[conda] Could not collect
```

## Additional context
N/A

cc @gmagogsfm

### PR DESCRIPTION
**Pull request by t1t0n**
Fixes #60258

I used the solution proposed in #61275.  His solution failed unit tests and there was no progress after 08/07/2021. I'm willing to fix problems if they arise during CI.

### CODE REVIEW

**Comment by t1t0n** [comment]
Is there any update regarding this pull request?

**Comment by t1t0n** [comment]
Any updates?

**Review by eellison — APPROVED** [review]
LGTM! Thanks!

**Comment by t1t0n** [comment]
Is there anything for me to do or is this pull request ready to merge?

**Comment by eellison** [comment]
hey I've been trying to land it but running into internal flakey failures (it's always a bit of a pain to land). If you don't mind could you rebase ?

**Pull request closed without merging**
