### PR TITLE
[ROCm] Skip several failing UTs to stabilize CI

### PR DESCRIPTION
**Pull request by pragupta**
Fixes the following unit test failure:
```
distributed/tensor/parallel/test_micro_pipeline_tp.py::MicroPipelineTPTest::test_fuse_all_gather_scaled_matmul_A_dims_2_gather_dim_0
distributed/tensor/parallel/test_micro_pipeline_tp.py::MicroPipelineTPTest::test_fuse_scaled_matmul_reduce_scatter_A_dims_2_scatter_dim_0

With the errors:
RuntimeError: torch._scaled_mm is only supported on CUDA devices with compute capability >= 9.0 or 8.9, or ROCm MI300+


test_transformers.py::TestSDPACudaOnlyCUDA::test_flash_attention_vs_math_ref_grads_batch_size_1_seq_len_q_1024_seq_len_k_1024_head_dim_128_is_causal_False_dropout_p_0_0_bfloat16_scale0_enable_gqa_True_n_heads0_cuda_bfloat16

export/test_export.py::TestOneOffModelExportResult::test_scaled_dot_product_attention_cuda
```

E.g: https://ossci-raw-job-status.s3.amazonaws.com/log/28342467042

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
@pragupta ,
As discussed add skips for below UTs also

[rocm / linux-focal-rocm6.1-py3.8 / test (default, 2, 6, linux.rocm.gpu.2)](https://hud.pytorch.org/pr/pytorch/pytorch/133101#28655816637) ([gh](https://github.com/pytorch/pytorch/actions/runs/10352838632/job/28655816637)) ([similar failure](https://hud.pytorch.org/pytorch/pytorch/commit/33837810380f9007109b2fabae92d279ac3ee008#28591878707))
test_transformers.py::TestSDPACudaOnlyCUDA::test_flash_attention_vs_math_ref_grads_batch_size_1_seq_len_q_1024_seq_len_k_1024_head_dim_128_is_causal_False_dropout_p_0_0_bfloat16_scale0_enable_gqa_True_n_heads0_cuda_bfloat16
[rocm / linux-focal-rocm6.1-py3.8 / test (default, 3, 6, linux.rocm.gpu.2)](https://hud.pytorch.org/pr/pytorch/pytorch/133101#28655816930) ([gh](https://github.com/pytorch/pytorch/actions/runs/10352838632/job/28655816930)) ([similar failure](https://hud.pytorch.org/pytorch/pytorch/commit/a7912bf9dc39b934baf5e04b436cc2134776c10d#28613898764))
export/test_export.py::TestOneOffModelExportResult::test_scaled_dot_product_attention_cuda

**Comment by pruthvistony** [comment]
@malfet ,
Can you please approve this PR.

**Comment by pragupta** [comment]
These UTs are skipped by https://github.com/pytorch/pytorch/pull/132895

**Pull request closed without merging**
