### PR TITLE
speed up quantized relu6 inplace kernel

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #68432 dbr quant overhead[9/x]: precalculate when to skip op_convert_after_hook
* #68431 dbr quant: remove more asserts from hot paths
* **#68404 speed up quantized relu6 inplace kernel**
* #68374 dbr quant: simplify relatedness logic
* #68373 dbr quant overhead[8/x]: small speedup in op_needs_quantization
* #68372 dbr quant overhead[7/x]: speed up AutoQuantizationState.reset_to_new_call
* #68371 dbr quant overhead[6/x]: remove unneeded isinstance checks in `op_convert_before_hook`
* #68370 dbr quant overhead[5/x]: remove unnecessary asserts
* #68369 dbr quant: clean up key types in AutoQuantizationState mappings
* #68351 dbr quant overhead[4/x]: speed up hook type calculations
* #68350 dbr quant overhead[3/x]: speed up AutoQuantizationState.mark_cur_op_complete

Summary:

The qclamp kernel is equal to (non inplace) or faster (inplace) than the
qrelu6 kernel.  Removing the qrelu6 kernel and routing qrelu6 to the
qclamp kernel instead.

Test plan:

```
// correctness
python test/test_quantization.py TestQuantizedOps.test_qrelu6

// benchmarking
import torch
import torch.nn.functional as F
toq = torch.ops.quantized
import time

N_WARMUP = 5
N_ITER = 1000

data = torch.randn(32, 32, 64, 64)
data = torch.quantize_per_tensor(data, 0.05, 0, torch.quint8)

for _ in range(N_WARMUP):
    F.hardtanh(data, 0., 6., inplace=True)
t1 = time.time()
for _ in range(N_ITER):
    F.hardtanh(data, 0., 6., inplace=True)
t2 = time.time()

for _ in range(N_WARMUP):
    toq.relu6(data, inplace=True)
t3 = time.time()
for _ in range(N_ITER):
    toq.relu6(data, inplace=True)
t4 = time.time()

t_hardtanh = t2 - t1
t_qrelu6 = t4 - t3
print(t_hardtanh, t_qrelu6)

// before
0.7156341075897217 1.4007949829101562

// after
0.6825599670410156 0.6571671962738037
```

Differential Revision: [D32463754](https://our.internmc.facebook.com/intern/diff/D32463754)

### CODE REVIEW

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32463754).

**Review by jerryzh168 — APPROVED** [review]

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32463754).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32463754).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32463754).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32463754).

**Pull request closed without merging**
