### PR TITLE
Add support for Python C extension modules in torch::deploy

### PR DESCRIPTION
**Pull request by zdevito**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#58117 [torch deploy] add support for Python C extension modules**

Previously it was not possible to load C extension modules with deploy because extension
modules need to link against the Python.h API functions. Since
each libtorchdeploy_interpreter.so had its own copy of these functions, it is not possible
to tell dlopen to resolve symbols in a loaded SO from one of these libraries without exposing
its symbols globally.

This patch adds a custom ELF loader which does the custom loading of attaching c extension libraries
to the Python API that loaded the shared library. Simple use of numpy and regex modules appears to work.

This diff has some limitations:

* 64-bit Linux only. OSX and windows use different formats for shared libraries. 32-bit ELF files are not supported.
* debug info is not immediately availiable to debuggers. A script for lldb is provided which can be loaded
so that lldb knows about the libraries as they are loaded.
* shared libraries can directly use the Python API, but libraries they depend on
  (via DT_NEEDED entries in their dynamic segment) may not use Python. In the future, we can
  try to detect whether a sub library uses the Python API and load it with our customer loader.
* TLS initialization and library initialization may occur in a different order than what would happen with dlopen,
  potentially leading to some issues running destructors in TLS segments. Use of this C++ features is relatively rare.

Differential Revision: [D28435305](https://our.internmc.facebook.com/intern/diff/D28435305)

### CODE REVIEW

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Review by suo — COMMENTED** [review]
I think we should just merge this and try it; to me the only major blocker is that we need some way to switch it on and off easily through a preprocessor flag or some such. That way we can begin experimenting with it on relevant workloads.

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Review by suo — APPROVED** [review]
accepting as all land blockers are fixed

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435305).

**Pull request closed without merging**
