### PR TITLE
Only initialize state if needed in SGD

### PR DESCRIPTION
**Pull request by mlazos**
Fixes [T184381726](https://www.internalfb.com/intern/tasks/?t=184381726)

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
I am checking the internal task and it looks like the state is not expected to be empty when checkpointing 
```
    raise RuntimeError(
RuntimeError: The state of _OptimStateKey(unflat_param_names=('weight', 'bias'), is_fsdp_managed=True) is empty. This should happen when use_orig_params=True.
```
Can you explain how this fixes the problem when it's only reading the state?

**Comment by mlazos** [comment]
Basically you should never have empty state. This would initialize the state even if it will be empty.

**Review by janeyx99 — APPROVED** [review]
don't land before adding test case!

**Pull request closed without merging**
