### PR TITLE
[Intel GPU] Remove special dispatch logic for xpu in adaptive_avg_pooling

### PR DESCRIPTION
**Pull request by retonym**
We now align the dispatch logic for XPU with CUDA in the adaptive average pooling operation.

### CODE REVIEW

**Review by EikanWang — APPROVED** [review]
LGTM

**Review by EikanWang — CHANGES_REQUESTED** [review]
@retonym , please fix CI failures.

**Comment by retonym** [comment]
This new building crash is due to not finding Pti package, which is not related to this PR change.

**Review by EikanWang — APPROVED** [review]

**Comment by retonym** [comment]
The check failure is not related to this PR.

**Review by atalman — APPROVED** [review]
lgtm. Please rebase and make sure lint is clear before landing

**Review by albanD — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
