### PR TITLE
comment out large test cases for tril(u)_indices

### PR DESCRIPTION
**Pull request by mrshenli**
4GB is still too large and leads to CUDA OOM failures.

### CODE REVIEW

**Comment by mrshenli** [comment]
segfault when installing librosa on rocm?

```
13:43:57 + pip install -q psutil librosa --user
13:44:04 =================== sccache compilation log ===================
13:44:04 .jenkins/pytorch/test.sh: line 85:    73 Segmentation fault      (core dumped) pip install -q psutil librosa --user > =0.6.2
```

**Review by apaszke — COMMENTED** [review]
Do we have any other test cases for those functions?

**Review by zou3519 — APPROVED** [review]
sounds good

**Comment by mrshenli** [comment]
The two pending tests all pass, but status are not updated.

**Pull request closed without merging**
