### PR TITLE
Double fetch depth.

### LINKED ISSUE #27648: fatal: refusing to merge unrelated histories: Merge to master jobs don't pull enough commits
I see this error a lot on PR builds:

```
+ git reset --hard 39a4edf223cdb5bd46657c043193272b6abc8824
HEAD is now at 39a4edf223 Strip source location from torch headers
+ git merge --no-edit --no-ff ab15584dce6c6b9870e79592ed8fd489f3b98f9d
fatal: refusing to merge unrelated histories
Exited with code 128
CircleCI received exit code 128
```

This occurs when a PR is on an old enough base, that our depth 50 pull isn't enough to find the merge base:

```

  git fetch --tags --progress https://github.com/pytorch/pytorch.git +refs/heads/master:refs/remotes/origin/master --depth=50 --quiet
```

Since this seems to happen pretty frequently, maybe 50 commits isn't enough history here.

cc @ezyang

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#29030 Double fetch depth.**

Might fix #27648

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D18300252](https://our.internmc.facebook.com/intern/diff/D18300252)

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Comment by zou3519** [comment]
Is depth=100 a lot slower than depth=50?

**Comment by ezyang** [comment]
Well, we're fetching twice as many commits at depth=100. So it'll be twice as slow.

**Comment by zou3519** [comment]
I guess my real question is: is it slow enough to matter? My hypothesis is that it won't be, because the amount of time it takes to build pytorch should dominate.

**Comment by ezyang** [comment]
Yeah I don't think it matters.

**Pull request closed without merging**
