### PR TITLE
[PyTorch] Expose interface to set grain size on cpu_kernel_vec

### PR DESCRIPTION
**Pull request by kimishpatel**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #58950 [PyTorch] Parallelize gelu via tensoriterator
* #59334 [PyTorch Operator Benchmark] gelu benchmark
* **#58949 [PyTorch] Expose interface to set grain size on cpu_kernel_vec**

To parallelize ops grain size setting is exposed at for_each level.
This is too far deep in the stack cpu_kernel_vec which does not know what the
op is. You would want to parallelize op depending on the op type. Non trivial
ops can benefit from threads even when the # of elements in tensor is not high.
This API exposes setting grain size at tensor iterator level so that operator
creating it can have control over it.

Differential Revision: [D26857523](https://our.internmc.facebook.com/intern/diff/D26857523/)

### CODE REVIEW

**Comment by kimishpatel** [comment]
@swolchok @ezyang want to get feedback on API change to allow specifying grain size for multi threading. Your inputs will be helpful.

**Comment by ezyang** [comment]
A more parsimonious and shorter change would be simply to add another argument to `cpu_kernel_vec` to optionally take grain size which it would pass on to `for_each`. Why not this?

**Comment by kimishpatel** [comment]
> A more parsimonious and shorter change would be simply to add another argument to `cpu_kernel_vec` to optionally take grain size which it would pass on to `for_each`. Why not this?

Thanks for the suggestion. That seems like a better option. I am not sure if I explored that before but if that works, that should do the trick.

**Comment by kimishpatel** [comment]
@ezyang so took your suggestion. Does this look better?

**Comment by kimishpatel** [comment]
@ezyang ping!

**Review by ezyang — APPROVED** [review]
okey dokey

**Pull request closed without merging**
