### PR TITLE
Add Half support for addcmul, addcdiv, cumsum, and topk on CPU

### PR DESCRIPTION
**Pull request by CaoE**
Add Half support for addcmul, addcdiv, cumsum, and topk on CPU.
Note: This PR will introduce the issue  https://github.com/pytorch/pytorch/issues/111454.
cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Comment by CaoE** [comment]
@ngimel Could you please review this PR ? Thanks.

**Comment by CaoE** [comment]
@ngimel Could you please review this PR ? Thanks.

**Comment by CaoE** [comment]
@cpuhrsch Could you please review this PR ? Thank you.

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
