### PR TITLE
[EZ] Move slow job from CU12.1 to CU12.4

### PR DESCRIPTION
**Pull request by malfet**
I though it was migrated a while back

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!

**Comment by huydhn** [comment]
Looks like there are still some remaining periodic 12.1 jobs

**Comment by malfet** [comment]
> Looks like there are still some remaining periodic 12.1 jobs

Yes, there are periodic and inductor, I'll create separate PRs to move them (unless you've already did)
But I'm a bit curious, why wasn't the migration complete.
@atalman do you know?

**Review by atalman — APPROVED** [review]

**Comment by atalman** [comment]
@malfet I believe we need to update our CUDA update runbook: https://github.com/pytorch/builder/blob/main/CUDA_UPGRADE_GUIDE.MD
cc @tinglvv @weiwangmeta

**Review by ZainRizvi — APPROVED** [review]

**Comment by ZainRizvi** [comment]
> @malfet I believe we need to update our CUDA update runbook: https://github.com/pytorch/builder/blob/main/CUDA_UPGRADE_GUIDE.MD cc @tinglvv @weiwangmeta

Prob best to update it with some future-proof instructions (e.g. "use cs.github.com with queries FOO and BAR to find all places where we need to update the CUDA version") in addition to the sample PRs, which will go stale over time

**Comment by malfet** [comment]
> @malfet I believe we need to update our CUDA update runbook: https://github.com/pytorch/builder/blob/main/CUDA_UPGRADE_GUIDE.MD cc @tinglvv @weiwangmeta

IMO every time one is doing migration two things should happen:
 - Issue to be opened to track the migration
 - Issue is closed only when all jobs mentioning deprecated cuda version are removed

**Comment by atalman** [comment]
> > @malfet I believe we need to update our CUDA update runbook: [pytorch/builder@`main`/CUDA_UPGRADE_GUIDE.MD](https://github.com/pytorch/builder/blob/main/CUDA_UPGRADE_GUIDE.MD?rgh-link-date=2024-12-11T19%3A12%3A21Z) cc @tinglvv @weiwangmeta
> 
> IMO every time one is doing migration two things should happen:
> 
> * Issue to be opened to track the migration
> * Issue is closed only when all jobs mentioning deprecated cuda version are removed

Agree on this let us create an issue and follow thru rest of the migration there

**Pull request closed without merging**
