### PR TITLE
[quantization] Rename fbgemm quantized operators to generic `quantized` ops

### PR DESCRIPTION
**Pull request by supriyar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #25626 [quantization] Store bias in PackedConvWeight in fbgemm
* #25428 [quantization] Store bias in PackedLinearWeight struct in fbgemm
* **#25338 [quantization] Rename fbgemm quantized operators to generic `quantized` ops**

As an effort to unify fbgemm and qnnpack at the dispatcher level, we need to have a generic name for the quantized backed ops.
Currently FBGEMM is guarded by the USE_FBGEMM macro and QNNPACK uses USE_QNNPACK.

TBD: Use compile time macro or run_time to switch between fbgemm and qnnpack.

Differential Revision: [D17097735](https://our.internmc.facebook.com/intern/diff/D17097735/)

### CODE REVIEW

**Comment by ljk53** [comment]
> > then how are you going to dispatch? are you going to create a new dispatch key for qnnpack?
> 
> @jerryzh168 I initially thought of using the USE_FBGEMM and USE_QNNPACK macro in the cpp files to dispatch to specific backend. That enforces compile time selection. Do you think this needs to be done at runtime?

We discussed this with @dzhulgakov - his suggestion was to combine build time macro and runtime flag, e.g.:

> we can have a global flag for testing purposes. There's an existing precedent of torch.backends.cudnn.enabled = False (https://github.com/pytorch/pytorch/blob/master/torch/backends/cudnn/__init__.py)

We can introduce the runtime flag in a separate PR.

**Comment by jerryzh168** [comment]
I see, makes sense.

**Comment by jerryzh168** [comment]
please fix https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/quantization.cpp#L553 as well.

**Comment by jerryzh168** [comment]
looks like all of them are preceded by quantized namespace, maybe we can remove quantized in the op name?

**Comment by dzhulgakov** [comment]
As a renaming step it looks good, we can add dispatch in a separate PR.

@jamesr66a  @raghuramank100 - can you sanity check the renaming though?

**Comment by dzhulgakov** [comment]
As for the dispatch, I think we should do the following:

- have global runtime API for debugging, something like `torch.backends.quantized.engine` which is None by default, but can be set to FBGEMM or QNNPACK

Then the dispatch code becomes:

```cpp
Tensor myop(...) {
  #ifdef USE_FBGEMM
  if (g_preferred_engine.has_value() && *g_preferred_engine == FBGEMM)
    return myop_fbgemm(...);
  #endif 
  #ifdef USE_QNNPACK
  if (g_preferred_engine.has_value() && *g_preferred_engine == QNNPACK)
    return myop_qnnpack(...);
  #endif
  TORCH_ERROR("Didn't find engine for quantized ops: ", g_preferred_engine);
}
```

**Comment by jianyuh** [comment]
This is a big change to the interface. It would be great to make an announcement in the group. Should we also change https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/qlinear_dynamic.cpp#L216 ?

**Comment by jgong5** [comment]
> have global runtime API for debugging, something like torch.backends.quantized.engine which is None by default, but can be set to FBGEMM or QNNPACK

Having a global runtime flag would be great! We are adding MKL-DNN quantization path which can be another alternative engine to set here.

**Review by dskhudia — APPROVED** [review]
LGTM!

**Comment by raghuramank100** [comment]
LGTM, this covers all locations where fbgemm is used in the pytorch op name

**Comment by ezyang** [comment]
broke lint

**Pull request closed without merging**
