### PR TITLE
add missing default value in _LRScheduler.step

### LINKED ISSUE #32646: Missing default value in torch/optim/lr_scheduler.pyi
## 🐛 Bug

There is no default value in `_LRScheduler.step` in [`torch/optim/lr_scheduler.pyi#L9`](https://github.com/pytorch/pytorch/blob/5b321a098594693eca8408169f475cb334856655/torch/optim/lr_scheduler.pyi#L9), but in [`torch/optim/lr_scheduler.py#L106`](https://github.com/pytorch/pytorch/blob/5b321a098594693eca8408169f475cb334856655/torch/optim/lr_scheduler.py#L106), `step` function has default value.

---

torch/optim/lr_scheduler.pyi#L9

```python
class _LRScheduler:
    def __init__(self, optimizer: Optimizer, last_epoch: int=...) -> None: ...
    def state_dict(self) -> dict: ...
    def load_state_dict(self, state_dict: dict) -> None: ...
    def get_lr(self) -> float: ...
    def step(self, epoch: Optional[int]) -> None: ...
```

---

torch/optim/lr_scheduler.py#L106

```python
class _LRScheduler(object):
    ....
    def step(self, epoch=None):
        # Raise a warning if old pattern is detected
        # https://github.com/pytorch/pytorch/issues/20124
        if self._step_count == 1:
            if not hasattr(self.optimizer.step, "_with_counter"):
                warnings.warn("Seems like `optimizer.step()` has been overridden after learning rate scheduler "
                              "initialization. Please, make sure to call `optimizer.step()` before "
                              "`lr_scheduler.step()`. See more details at "
         ....
```

## Expected behavior

Type of `_LRScheduler` should be as follow.

```python
class _LRScheduler:
    def __init__(self, optimizer: Optimizer, last_epoch: int=...) -> None: ...
    def state_dict(self) -> dict: ...
    def load_state_dict(self, state_dict: dict) -> None: ...
    def get_lr(self) -> float: ...
    def step(self, epoch: Optional[int]=...) -> None: ...
```

cc @vincentqb

### PR DESCRIPTION
**Pull request by jeongukjae**
In `lr_scheduler.py`,` _LRScheduler.step` has default value, but in type stub, there is no default value.

Resolve #32646

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 5f59e4c9:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=5f59e4c913b4ebe29cf857b0e396f56e8af3d818).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4345859) pytorch_linux_xenial_py3_6_gcc5_4_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=91228339) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=91228339))
<details>
<summary>
<code>Jan 27 11:10:51 RuntimeError: test_quantization failed!</code>
</summary>

```
Jan 27 11:10:51 Ran 36 tests in 52.619s 
Jan 27 11:10:51  
Jan 27 11:10:51 FAILED (errors=1, skipped=1) 
Jan 27 11:10:51  
Jan 27 11:10:51 Generating XML reports... 
Jan 27 11:10:51 Traceback (most recent call last): 
Jan 27 11:10:51   File "test/run_test.py", line 456, in <module> 
Jan 27 11:10:51     main() 
Jan 27 11:10:51   File "test/run_test.py", line 449, in main 
Jan 27 11:10:51     raise RuntimeError(message) 
Jan 27 11:10:51 RuntimeError: test_quantization failed! 
Jan 27 11:10:52 =================== sccache compilation log =================== 
Jan 27 11:10:52 + cleanup 
Jan 27 11:10:52 + retcode=1 
Jan 27 11:10:52 + set +x 
Jan 27 11:10:52 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 27 11:10:52 Compile requests                  7 
Jan 27 11:10:52 Compile requests executed         6 
Jan 27 11:10:52 Cache hits                        0 
Jan 27 11:10:52 Cache misses                      6 
Jan 27 11:10:52 Cache timeouts                    0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by vincentqb — APPROVED** [review]
LGTM. Running internal tests before merging.

**Comment by jeongukjae** [comment]
@vincentqb It looks like status check failed. What can I do to merge this PR?

**Comment by vincentqb** [comment]
> It looks like status check failed. What can I do to merge this PR?

The facebook internal error seems to be transient. Rerunning.

**Comment by jeongukjae** [comment]
> > It looks like status check failed. What can I do to merge this PR?
> 
> The facebook internal error seems to be transient. Rerunning.

This PR is same with https://github.com/pytorch/pytorch/pull/32411, so I will close this pr. Thank you for reviewing this.

**Pull request closed without merging**
