### PR TITLE
Make offsets dynamic by default

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #113734

Copied from @ezyang 's #113693.

The motivation for this change is that we'd like to guard on storage offset in inductor, to make assumptions about data alignment.

create_symbolic_sizes_strides_storage_offset() creates the sizes/strides/offset for fake tensors - they can either be integers or symints. This PR changes storage_offset to always be dynamic. In variables/builder.py, we remove a conditional so that all tensors get added to tracked_fakes. This is because the storage offset will be dynamic even if the other logic in builder.py suggests that it will be static; otherwise, we run into this issue:

https://github.com/pytorch/pytorch/blob/1e260c851b9e651794b8d1573c424dc2523a43b3/torch/fx/experimental/symbolic_shapes.py#L892-L895

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by davidberard98** [comment]
@ezyang LMK if this is still useful or - if we should instead wait for #113802 so we can plumb storage offset info through like we do for sizes?

**Review by ezyang — APPROVED** [review]
This is great, thanks

**Comment by davidberard98** [comment]
potentially a small performance regression from this: 
https://hud.pytorch.org/benchmark/compilers?startTime=Thu%2C%2009%20Nov%202023%2016%3A07%3A33%20GMT&stopTime=Thu%2C%2016%20Nov%202023%2016%3A07%3A33%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=gh/davidberard98/238/orig&lCommit=23ef93fd9cdbffc851b610e0ba0122577a72c8ec&rBranch=main&rCommit=78f3937ee84e71475942598f4b51dce7c8a70783

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change, but it is causing a memory leak in one of the test https://hud.pytorch.org/pytorch/pytorch/commit/9efbb4ea73009950a2d99e4d871351c898aae0dd' -c nosignal

I think @jeanschmidt has already added `ciflow/slow` onto your PR, so the check will be run now.

**Comment by davidberard98** [comment]
@huydhn I just moved the test to a different file and for some reason that makes the leak go away. I verified locally and the CI looks green. Will land it now.

**Pull request closed without merging**
