### PR TITLE
fix grad_bias calculation for nnpack

### PR DESCRIPTION
**Pull request by killeent**
As title.

### CODE REVIEW

**Comment by colesbury** [comment]
The change looks fine, but do we have tests that exercise this code path?

**Comment by killeent** [comment]
@colesbury - I have not written a test yet because we do not have `NNPACK` on our contbuild machines. I thought I had manually verified that the `grad_bias` was correct before, but I guess I omitted this. We would have to have some way of toggling NNPACK and comparing the results with non-NNPACK versions.

As far as I can tell, we don't have any `Conv` tests that actually have expected values for anything, we usually just compare different things (i.e. grouped convolution vs. two separate indivudual convolutions), or check for errors.

**Review by colesbury — APPROVED** [review]
We do gradient checks on convolutions, which would catch these sorts of errors.

It's urgent that we get at least some basic tests that execute this code path. Otherwise, we're very likely to break it.

You can add NNPACK to the .travis.yaml and experiment with it by enabling travis-ci in your fork. It'd be good to add it to the other build machines too, but that's probably more tricky.

**Comment by killeent** [comment]
@colesbury - can you point me to these tests? I didn't see any but I'm never sure exactly where to look. 

I agree that getting contbuild support for this code path is important.

**Comment by colesbury** [comment]
In test_nn.py test_conv_double_backward*

I'm not sure why we don't also do the standard tests in common_nn.py

**Pull request merged**
