### PR TITLE
[caffe2] Support caffe2 LeakyRelu op in caffe_translator.

### PR DESCRIPTION
**Pull request by JerryShih**
Convert Relu layer to LeakyRelu op if we have 'negative_slope' value in caffe Relu layer.

### CODE REVIEW

**Comment by JerryShih** [comment]
@bddppq 
Could you please review this patch?

**Comment by ezyang** [comment]
ping @bddppq

**Comment by JerryShih** [comment]
@bddppq @houseroad
All tests passed.
Could you please review this patch?

**Comment by ezyang** [comment]
I can merge this patch if we get a test for it.

**Comment by JerryShih** [comment]
@ezyang 
Here is the test case: https://github.com/pytorch/pytorch/pull/10764/commits/a6861f19b4909e2ba20a739277b575339c73e5e1.

I could pass the test locally.
This test depends on caffe, but it's not easy to install the caffe in both mac, ubuntu 14.04 and ubuntu 16.04 platform. I should build the caffe from source.
The original caffe_translator test case[[1]](https://github.com/pytorch/pytorch/blob/db82fc7ca6e6bf261f51a6794b400a04eaf55bd0/caffe2/python/caffe_translator_test.py#L58) will check the caffe status before running. I do the similar checking.

**Comment by JerryShih** [comment]
@ezyang 
It's easy to install caffe using apt-get if the ubuntu is >= 17.04.
http://caffe.berkeleyvision.org/install_apt.html

**Comment by ezyang** [comment]
Hey @JerryShih, I'm not too familiar with this code, so I can't speak about it authoritatively, but it's a bit unexpected that you have to write an entirely new test script. Shouldn't `caffe2/python/caffe_translator_test.py` be right?

**Comment by JerryShih** [comment]
@ezyang 
Please check the func setUpModule() in caffe_translator_test.py.
https://github.com/pytorch/pytorch/blob/d25fee31fcef8aea6489d8ebe8d2ece9aa6c5832/caffe2/python/caffe_translator_test.py#L27
From the [reference](https://docs.python.org/3/library/unittest.html#class-and-module-fixtures), the setUpModule() will be invoked in caffe_translator_test test. The function will load a bvlc caffe model which is not used in the relu related tests.
So, I create another separated file for relu tests.

Here is the log for the relu test. Since there is no caffe env in ci, the relu and the original caffe_translator_test are skipped.
```
../.local/lib/python2.7/site-packages/caffe2/python/caffe_translator_op_test.py::TestTranslateReluLayer::test SKIPPED [  0%]
../.local/lib/python2.7/site-packages/caffe2/python/caffe_translator_test.py::TestNumericalEquivalence::testBlobs SKIPPED [  0%]
```

**Comment by JerryShih** [comment]
@ezyang 
I'm not a python unittest expert. If there is another good practice, I will refine that test code.

**Comment by JerryShih** [comment]
> @ezyang
> Please check the func setUpModule() in caffe_translator_test.py.
> [pytorch/caffe2/python/caffe_translator_test.py](https://github.com/pytorch/pytorch/blob/d25fee31fcef8aea6489d8ebe8d2ece9aa6c5832/caffe2/python/caffe_translator_test.py#L27)
> 
> Line 27 in [d25fee3](/pytorch/pytorch/commit/d25fee31fcef8aea6489d8ebe8d2ece9aa6c5832)
> 
>  def setUpModule(): 
> 
> From the [reference](https://docs.python.org/3/library/unittest.html#class-and-module-fixtures), the setUpModule() will be invoked in caffe_translator_test test. The function will load a bvlc caffe model which is not used in the relu related tests.
> So, I create another separated file for relu tests.

@houseroad 
I know we have the caffe_translator_test.py, but this is the reason that I create another test file.

**Comment by houseroad** [comment]
@JerryShih could you turn this `setUpModule` into `setUpClass` in the TestNumericalEquivalence?

**Comment by JerryShih** [comment]
@ezyang @houseroad 
The test is in caffe_translator_test.py now.

**Comment by JerryShih** [comment]
@ezyang @houseroad 
could you please review this change?

**Pull request closed without merging**
