### PR TITLE
Make skipIfTorchDynamo xfail

### PR DESCRIPTION
**Pull request by voznesenskym**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Sure but you are probably going to have to do some fixing. Also note the dynamo tests have crosstalk as we don't clear dynamo cache between runs (runs too slow if you do)

**Review by albanD — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Review by malfet — CHANGES_REQUESTED** [review]
Hmm, should it have a different method name then? I.e. `skipIfTorchDynamo` decorator implies that test would be skipped. Perhaps you can add a new `xfailIfTorchDynamo` and use it when needed?
(To give an example, sometimes `skipIf...` predicates are used to avoid segfaults in the native code, so replacing them with xfail will lead to unexpected consequentces)

**Comment by voznesenskym** [comment]
> Hmm, should it have a different method name then? I.e. `skipIfTorchDynamo` decorator implies that test would be skipped. Perhaps you can add a new `xfailIfTorchDynamo` and use it when needed?
> 
> (To give an example, sometimes `skipIf...` predicates are used to avoid segfaults in the native code, so replacing them with xfail will lead to unexpected consequentces) 

Sure, but it's used in hundreds of places, so it didn't feel worth changing until I get it passing. 

The part that's not passing is where we annotate one test, but it runs hundreds of variants :) 

For that, I kinda plan to do what you said except I have it looking like:

@ifTorchDynamo(skip/fail) 

but I kinda like your api better as it fits the one it's replacing more. I'll update this PR later today or tomorrow.

**Comment by ezyang** [comment]
I am happy to add an xfail variant of skipIfTorchDynamo but I also think that fundamentally skipIfTorchDynamo won't scale. I want us to investigate other ways to record xfails; e.g., having a file that is just a list of all tests that are failing with dynamo

**Pull request closed without merging**
