### PR TITLE
Remove parent device mesh check

### PR DESCRIPTION
**Pull request by mvpatel2000**
Removes raising error if a device_mesh has a parent. 

The comment says that HSDP + TP is not supported, but I'm able to do 2D parallelism + HSDP fine. The only issues are:
- this check
- https://github.com/pytorch/pytorch/pull/118618
- a series of PRs related to checkpointing with 3D meshes that I will open
We currently monkeypatch for the above which I am slowly upstreaming.

I imagine torch will have a better, native integration eventually, but this check seems too aggressive in the meantime given DTensor now lets users do some things themselves (which is amazing 🎉)!

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

### CODE REVIEW

**Comment by fegin** [comment]
cc., @wz337

**Review by wz337 — DISMISSED** [review]
LGTM!

**Comment by mvpatel2000** [comment]
@wz337 do you know if the lint is flakey on torch? The lint failures seem unrelated. Could you please help me rerun the action? I don't seem to have the ability to do this as an external contributor

**Review by wanchaol — DISMISSED** [review]

**Comment by Skylion007** [comment]
@mvpatel2000 This was a result of a race condition of merging new code and new linting code. Rebasing your PR should fix the lint errors.

**Review by Skylion007 — APPROVED** [review]

**Pull request closed without merging**
