### PR TITLE
Skip workspace permission change for ROCm CI

### PR DESCRIPTION
**Pull request by jithunnair-amd**
PR https://github.com/pytorch/pytorch/pull/122922 added chown steps to test.sh and used the trap mechanism to ensure that, even if the test scripts fails and exits with a non-zero code, it will call the cleanup_workspace function on EXIT.

However, this doesn't work as intended when the CI job gets cancelled for eg. if a PR pushes new commits and the older commit CI job gets cancelled. The trap function doesn't get called as the test script immediately aborts.

Any subsequent jobs scheduled on the same runner then fail in the 'Checkout PyTorch' step when they try to delete the workspace.

This has been resulting in a slew of CI failures on the HUD.

Example of this situation playing out on one of the ROCm runners:
Cancelled job: https://github.com/pytorch/pytorch/actions/runs/8563212279/job/23469711035

image

Subsequent failed job: https://github.com/pytorch/pytorch/actions/runs/8564517036/job/23472675041

image

This PR skips the logic introduced by PR 122922 for ROCm CI.

Alternative to https://github.com/pytorch/pytorch/pull/123468 and https://github.com/pytorch/pytorch/pull/123588

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by pruthvistony — APPROVED** [review]

**Review by zxiiro — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
Still happening on HUD eg.
```
        {
            "name": "linux-focal-rocm6.0-py3.8 / test (default, 1, 6, linux.rocm.gpu.2, unstable)",
            "html_url": "https://github.com/pytorch/pytorch/actions/runs/8698518031/job/23857481730",
            "_event_time": "2024-04-16T04:53:38.037026Z",
            "runner_name": "pytorch-rocm-hw-05",
            "head_branch": "main",
            "head_sha": "1cf62e86a47ee575b5fbb997fd00f60ef0163130",
            "workflow_name": "rocm",
            "conclusion": "failure",
            "line": "##[error]Process completed with exit code 1."
        },
        {
            "name": "rocm6.0-py3.8-inductor / test (inductor, 1, 1, linux.rocm.gpu.2, unstable)",
            "html_url": "https://github.com/pytorch/pytorch/actions/runs/8698473167/job/23857460114",
            "_event_time": "2024-04-16T04:52:22.691483Z",
            "runner_name": "pytorch-rocm-hw-05",
            "head_branch": "ciflow/inductor/124131",
            "head_sha": "92d8175ab302be79cda3062fe12365ad73a5d1ec",
            "workflow_name": "inductor",
            "conclusion": "cancelled",
            "line": "##[error]The operation was canceled."
        },
```

**Comment by jithunnair-amd** [comment]
@huydhn Please approve so I can merge

**Review by kit1980 — APPROVED** [review]

**Comment by DanilBaibak** [comment]
Hi @jithunnair-amd! Sorry, I need to revert your PR because it looks like your changes broke rocm jobs. [Here is an example](https://github.com/pytorch/pytorch/actions/runs/8734665545/job/23969240769) that can't clean up the workspace due to lack of permissions. 

If the problem is not related to your changes, I will help you merge the PR back.

**Review by malfet — APPROVED** [review]
My 2¢ here: this code is getting hairier and hairier and imo it should be be pushed to the infra (i.e. runner config) rather than kept in a workflow

**Comment by jithunnair-amd** [comment]
> stop chown'ing our workspace.
Stop chown'ing! :)

> My 2¢ here: this code is getting hairier and hairier and imo it should be be pushed to the infra (i.e. runner config) rather than kept in a workflow
I agree, these acrobatics are going to be hard to keep track of. @jeanschmidt / @zxiiro That's why we went for the route in https://github.com/pytorch/pytorch/blob/384de46395234e793a319325e5c9d20a60407a64/.github/workflows/_rocm-test.yml#L232-L233 instead of chown'ing the workspace. Can you please reconsider this route so we can get rid of the chown logic in the build/test scripts?

**Comment by jithunnair-amd** [comment]
Relanding since this PR actually prevents any chown'ing for ROCm, which is what we want.
@pytorchbot merge

**Pull request closed without merging**
