### PR TITLE
[vmap] Fix searchsorted batch rule for self_logical_rank == 0

### LINKED ISSUE #95888: searchsorted : vmap fails
### 🐛 Describe the bug

```python
import torch
import torch.utils._pytree as pytree

# Copied from `test/functorch/common_utils.py`.
def loop(op, in_dims, out_dim, batch_size, *batched_args, **kwarg_values):
    outs = []
    out_spec = None
    for idx in range(batch_size):
        flat_args, args_spec = pytree.tree_flatten(batched_args)
        flat_dims, dims_spec = pytree.tree_flatten(in_dims)
        assert(args_spec == dims_spec)
        new_args = [a.select(in_dim, idx) if in_dim is not None else a for a, in_dim in zip(flat_args, flat_dims)]
        out = op(*pytree.tree_unflatten(new_args, args_spec), **kwarg_values)
        flat_out, out_spec = pytree.tree_flatten(out)
        outs.append(flat_out)

    outs = zip(*outs)
    result = [torch.stack(out_lst) for out_lst in outs]
    return pytree.tree_unflatten(result, out_spec)

boundaries = torch.tensor([[1, 4, 5, 7, 9], [1, 2, 5, 7, 9]])
v = torch.tensor(3)

# Output: tensor([1, 2])
print(loop(torch.searchsorted, (0, None), 0, 2, boundaries, v))  

# IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
print(torch.func.vmap(torch.searchsorted, in_dims=(0, None))(boundaries, v))

```

### Versions

master

cc @zou3519 @Chillee @samdow @soumith @janeyx99

### PR DESCRIPTION
**Pull request by qqaatw**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99526
* #99522
* #99517

Fixes #95888

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]
good catch, thank you!

**Comment by zou3519** [comment]
@qqaatw sorry, we had to revert this PR because it regressed behavior in searchsorted that wasn't tested in our test suite (see https://github.com/pytorch/pytorch/issues/99603). Please feel free to submit an updated PR if you're still interested!

**Comment by zou3519** [comment]
@qqaatw My apologies, I should have checked before I did the revert. Yes, you are correct that this PR doesn't change the behavior, even after the revert the bug is still there. Let's get this PR merged.

**Review by zou3519 — APPROVED** [review]
Sorry, the revert was a mistake. Let's get this PR merged.

**Comment by qqaatw** [comment]
@zou3519 No worries, I will check if I can resolve the new issue later.

**Pull request closed without merging**
