### PR TITLE
Add Half support for cummax, cummin, cumprod, logcumsumexp, and prod on CPU

### PR DESCRIPTION
**Pull request by CaoE**
Add Half support for cummax, cummin, cumprod, logcumsumexp, and prod on CPU.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]

**Comment by cpuhrsch** [comment]
@CaoE - The topic for these changes should be "improvements". They every much are user facing since they extend operator coverage to a new dtype on a device. Please update the other PRs as well.

**Comment by CaoE** [comment]
@cpuhrsch Do other PRs also require release note: nn ?

**Comment by cpuhrsch** [comment]
@CaoE - I'm not sure. We could also use "release notes: intel". Seems appropriate?

**Comment by CaoE** [comment]
@cpuhrsch I added a new label "release notes: half" for half support.

**Comment by cpuhrsch** [comment]
@CaoE - Please use an existing label and delete the one you created. It won't work with our release notes setup. I think `release notes: intel` is appropriate.

**Comment by CaoE** [comment]
@cpuhrsch Removed `release notes: half` and use `release notes: intel` instead.

**Comment by cpuhrsch** [comment]
@pytrchbot merge

**Pull request closed without merging**
