### PR TITLE
hook XPU device in _get_available_device_type

### PR DESCRIPTION
**Pull request by fengyuan14**
Signed-off-by: Feng Yuan <feng1.yuan@intel.com>

### CODE REVIEW

**Comment by arthuryuan1987** [comment]
Hi, @ezyang,
Please review, we are adding a XPU device path in `_get_available_device_type`.

**Comment by ezyang** [comment]
you need to appease lint. The API here doesn't make sense to me (@mrshenli ?) but given that this is what we have, this seems fine, I guess.

**Comment by gujinghui** [comment]
> you need to appease lint. The API here doesn't make sense to me (@mrshenli ?) but given that this is what we have, this seems fine, I guess.

@ezyang  Due to XPU is a out-of-tree device, the torch.xpu is not available until we register it.
Could you give suggestion how to fix this lint issue?

**Comment by ezyang** [comment]
I'd just suppress numpy here

**Comment by gujinghui** [comment]
> 

@ezyang  May I know how to rerun the test? Thanks

**Comment by ezyang** [comment]
It looks like a real lint error you should fix it

**Comment by arthuryuan1987** [comment]
> It looks like a real lint error you should fix it

Let me take a look.

**Comment by arthuryuan1987** [comment]
@ezyang The failure is supposed a static check failure? How can we fix it?

**Comment by ezyang** [comment]
suppress it with a type ignore

**Comment by gujinghui** [comment]
@ezyang  Pls help review. Thanks.

**Comment by arthuryuan1987** [comment]
Hi, @ezyang,
I suppressed all MYPY static check and flake8 check, please help review.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
