### PR TITLE
Add support for set of enum

### PR DESCRIPTION
**Pull request by guilhermeleobas**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #112522

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
Attempt to fix https://github.com/pytorch/pytorch/issues/112338

**Comment by lezcano** [comment]
Not sure this would fix the whole thing. In particular, I'm not sure if this would work with graphbreaks.

In any case, that issue will be fixed by https://github.com/pytorch/pytorch/pull/110524, althought it's taking me longer to land that stack than I would like really. Is this unblocking anything urgent, or can we wait for that stack?

**Comment by zou3519** [comment]
It's not blocking anything urgent, I was looking for small dynamo tasks for Guilherme, but it sounds like this one isn't small

**Comment by lezcano** [comment]
This one is small. The other PR tries to heavily improve the state of dicts, which is not great at the moment, and in turn, implement Sets as dicts with None keys.

**Pull request closed without merging**
