### PR TITLE
[quant][pt2e] Removed mean/hardtanh annotations and refactored adaptive_avg_pool annotation

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #106806
* __->__ #106805

Summary:
Removed annotations for some ops, since they are handled in torch/ao/quantization/pt2e/_propagate_annotation.py

Test Plan:
CIs

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Comment by kimishpatel** [comment]
I see annotation functions just moved, not removed. Am i reading that right?

Also, I assume you will rename xnnpack_quantizer_utils.py to quantizer_utils.py?

**Comment by jerryzh168** [comment]
> I see annotation functions just moved, not removed. Am i reading that right?
> 
> Also, I assume you will rename xnnpack_quantizer_utils.py to quantizer_utils.py?

I removed mean/hardtanh, but just moved adaptive_avg_pool2d, since I remember you mentioned that this can stay in quantizer before

I don't plan to rename xnnpack_quantizer_utils.py to quantizer_utils.py since we are not planning to maintain additional APIs except for the annotation API right now, I think we talked about this before, right?

**Review by kimishpatel — APPROVED** [review]

**Comment by kimishpatel** [comment]
> > > I don't plan to rename xnnpack_quantizer_utils.py to quantizer_utils.py since we are not planning to maintain additional APIs except for the annotation API right now, I think we talked about this before, right
> > 
> > 
> > Correct on not maintaining anything other than annotation API.
> > I was suggesting quantizer_utils.py as something that is not part of core quant workflow but as set of utils that are provided. I do think that makes sense to enable annotation on canonical patterns, but it lives outside of core quantization workflow.
> 
> I see, but naming it as quantizer_utils.py would indicate that it is maintained by AO right? are you saying we can name it as quantizer_utils.py but edge team will maintain it?

Lets discuss this.

**Pull request closed without merging**
