### PR TITLE
[Inductor] Represent size_hints as a dict

### PR DESCRIPTION
**Pull request by blaine-rister**
Preparatory refactor for https://github.com/pytorch/pytorch/pull/137243.

# Feature

Follow up to https://github.com/pytorch/pytorch/pull/141751. Since we now represent `numels` as a dict, it's natural to extend this to `size_hints`. The latter are basically just the former rounded up to the nearest power of 2. This simplifies various heuristics such as the coordinate descent tuner. Where we previously needed to determine which index in `size_hints` corresponds to each dimension, now we can just query by prefix. This will be especially important when we enable 2D reductions, as it becomes harder to keep track of these things when we have multiple reduction dimensions. (See the previous PR for some examples.)

# Test plan

The existing CI provides good coverage. This PR modifies a few tests which explicitly constructed size hints.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by blaine-rister** [comment]
Reopening to change internal tests

**Comment by Skylion007** [comment]
May want to consider TypedDict here along with numels. You can use NotRequired typing_extensions to make y, and z optional here.

**Comment by blaine-rister** [comment]
> May want to consider TypedDict here along with numels. You can use NotRequired typing_extensions to make y, and z optional here.

On the one hand, this does seem like a good use case for  a class or a more formal type system, as we know ahead of time what all the valid keys of the dict will be. On the other, there are a lot of places in the code that construct `size_hints` on the fly, including some Python that we generate in the kernel itself, so it's nice to keep things as simple as possible. 

I'm not very familiar with `TypedDict` myself. Is it just for type checking, or does it also do runtime checks? I could see value in checking that the keys are one of `{"x", "y", "z", "r"}`, but if it's just about the type signature, then `Dict[str,int]` seems sufficient.
https://peps.python.org/pep-0589/

**Comment by blaine-rister** [comment]
Landed internally.

**Pull request closed without merging**
