### PR TITLE
[FakeTensor] Use the device of the meta tensor for fallback kernel

### PR DESCRIPTION
**Pull request by eellison**
Otherwise, I would run into issues such as fp16 not supported for Conv Cpu, or cudnn_rnn not implemented for cpu.

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
Stamp

**Comment by b0noI** [comment]
broken test: ======================================================================
FAIL [0.015s]: test_fallback_memory_prop (__main__.FakeTensorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_fake_tensor.py", line 174, in test_fallback_memory_prop
    self.assertTrue(out.is_contiguous(memory_format=torch.channels_last))
AssertionError: False is not true
----------------------------------------------------------------------
Ran 31 tests in 11.717s
FAILED (failures=1, expected failures=3)
Generating XML reports...
Generated XML report: test-reports/python-unittest/test_fake_tensor/TEST-FakeTensorConverterTest-20220624062224.xml
Generated XML report: test-reports/python-unittest/test_fake_tensor/TEST-FakeTensorOperatorInvariants-20220624062224.xml
Generated XML report: test-reports/python-unittest/test_fake_tensor/TEST-FakeTensorTest-20220624062224.xml
Traceback (most recent call last):
  File "test/run_test.py", line 945, in <module>
    main()
  File "test/run_test.py", line 923, in main
    raise RuntimeError(err_message)
RuntimeError: test_fake_tensor failed!

**Pull request closed without merging**
