### PR TITLE
Adding torch.futures to API docs

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #40190 Remove obsolete warning message from DDP
* **#40051 Adding torch.futures to API docs**

Differential Revision: [D22055031](https://our.internmc.facebook.com/intern/diff/D22055031)

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
LGTM!

**Comment by rohan-varma** [comment]
Question, does the futures API work as expected with jit fork? i.e.

```
fut = torch.jit._fork(...)
fut.wait()
```

If this is an intended use case and we want to support it, should we add docs here or in the JIT docs somewhere?

**Comment by mrshenli** [comment]
> Question, does the futures API work as expected with jit fork?

Good point, I think this should work. But given the the `_fork` name starts with an underscore, I assume it is not public yet? 

Hey @wanchaol, does JIT team expect OSS users to use `torch.jit._fork()`?

**Review by jlin27 — APPROVED** [review]

**Comment by wanchaol** [comment]
> > Question, does the futures API work as expected with jit fork?
> 
> Good point, I think this should work. But given the the `_fork` name starts with an underscore, I assume it is not public yet?
> 
> Hey @wanchaol, does JIT team expect OSS users to use `torch.jit._fork()`?

Yeah it's not public yet, but I think we are trying to make it public either in the 1.6 or 1.7 release.

**Pull request closed without merging**
