### PR TITLE
Fix typos under _decomp directory

### PR DESCRIPTION
**Pull request by QSHLGZ**
Fix typos under _decomp directory

### CODE REVIEW

**Comment by davidradl** [comment]
@QSHLGZ you need to get your CLA done as per the message or this will not be able to be merged.

**Review by ezyang — APPROVED** [review]

**Review by Neilblaze — APPROVED** [review]

**Comment by ezyang** [comment]
the cla is still messed up. it might be easiest to fix your email and force push to main

**Comment by QSHLGZ** [comment]
@linux-foundation-easycla re-check

**Comment by QSHLGZ** [comment]
> the cla is still messed up. it might be easiest to fix your email and force push to main

**Comment by QSHLGZ** [comment]
"/easycla"

**Comment by QSHLGZ** [comment]
> the cla is still messed up. it might be easiest to fix your email and force push to main

@ezyang I already changed my email and push -f to main. And CLA has also been signed as the picture shown below. I tried comment "/easycla" to trigger cla check, but don't know why it was not triggered
image

**Pull request closed without merging**
