### PR TITLE
Switch eigen to GitHub mirror

### PR DESCRIPTION
**Pull request by huydhn**
I found this mirror https://github.com/eigen-mirror/eigen/tree/master that we can use.  Should we make the switch?  One less flaky source is better than twos, i.e. https://hud.pytorch.org/pr/pytorch/pytorch/110530#17400038975

Please let me know if there are any concerns as the gitlab one is still considered official.

### CODE REVIEW

**Comment by kit1980** [comment]
Isn't it too old? Looks much older than the gitlab repo.

**Comment by huydhn** [comment]
From what I see, we are currently using the commit [eigen @ 3147391](https://github.com/pytorch/pytorch/blob/main/third_party/eigen) from the GitLab repo.  So, I just keep the it the same.

The mirror https://github.com/eigen-mirror/eigen is in sync with GitLab and has the latest commit there from what I see.

**Comment by huydhn** [comment]
I should link the main branch of the mirror https://github.com/eigen-mirror/eigen/tree/master :)

**Comment by huang-hz** [comment]
It will auto checkout the branch.

**Pull request closed without merging**
