### PR TITLE
Added more regression test for groupconv w/o bias.

### PR DESCRIPTION
**Pull request by ghost**
Summary:
Follow-up of https://github.com/pytorch/pytorch/issues/18218, which was fixed by https://github.com/pytorch/pytorch/pull/18463 with mkl-dnn upgraded to v0.18.1.
Covering special case when group > 1, input-channel / group < 16 and output-channel is multiple of 16.

### CODE REVIEW

**Review by soumith — CHANGES_REQUESTED** [review]
instead of adding a _v2, please just add the code to the for loop in the test above (with the comment).

thanks for the PR

**Comment by fracting** [comment]
> instead of adding a _v2, please just add the code to the for loop in the test above (with the comment).
> 
> thanks for the PR

Thanks for reviewing.

Not sure if I understand correctly, are you suggesting:

a) reusing the variable `m` and overriding `m = nn.Conv2d(4, 4, kernel_size=3, groups=2, bias=False).to(device, dtype)` with `m = nn.Conv2d(4, 16, kernel_size=3, groups=2, bias=False).to(device, dtype)` after finishing the first test, as well as reusing `m1`, `m2`, `i`, `i1`, `i2`?

or

b) creating new variables like `m_`,`m1_`, `m2_`, etc

or

c) creating an inner loop for output_channel in [4, 16]

Thanks!

**Review by soumith — APPROVED** [review]
actually, this is probably fine. dont worry about it.

**Comment by soumith** [comment]
I cant land this until internal MKL-DNN is upgraded to 0.18.1 cc: @yinghai that this bug exists for all our internal workloads right now.

**Comment by fracting** [comment]
Hi @soumith @yinghai any progress on this pull request?

Thanks!

**Comment by fracting** [comment]
Hi @soumith @yinghai @SsnL any updates or any comments on this pull request?

Thanks!

**Comment by soumith** [comment]
i am landing it today

**Pull request closed without merging**
