### PR TITLE
Reduce number of guards introduced by check_cudnn_tensor_shapes when cudnn version is higher enough

### PR DESCRIPTION
**Pull request by chengzeyi**
I found that when using TorchDynamo (torch.compile) with dynamic shape on H100, there are some extra guards added to check the sequence length of inputs of `scaled_dot_product_attention` to be divisible by 64. These guards cause unwanted recompilations when the input shape changes.

In fact these guards are not necessary if our CUDNN version is higher enough, So I change the order of those checks to use short-circuit rules to skip those checks and avoid unnecessary guards.

### CODE REVIEW

**Review by nWEIdia — COMMENTED** [review]
Thanks for the PR!
Since this https://github.com/pytorch/pytorch/commit/de4f8b99469da0c7d56362441cb25d4e62cfd2db, cudnn version has been bumped up to 9xxx for all cuda (11.8, 12.1, 12.4) versions. 
Maybe we could even delete these legacy checks as those would be false anyways? cc @eqy

**Review by eqy — APPROVED** [review]

**Comment by eqy** [comment]
I would be OK with removing the < v9 checks as we do not dispatch to cuDNN SDPA by default in 8.9.x anyway

**Comment by Skylion007** [comment]
Sigh, these errors like real. We probably need to update CUDNN and hope of some of them get fixed.

**Comment by chengzeyi** [comment]
@eqy @nWEIdia Hey, some CI checks were failed because of OOM issues. These seems not related to this PR. Is there anyway that I can get this PR merged?

**Comment by chengzeyi** [comment]
Just synced, hope this time can pass

**Review by Skylion007 — APPROVED** [review]

**Pull request closed without merging**
