### PR TITLE
[dtensor] remove unused tests and fix ci

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #97064

fix ci

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!

**Comment by huydhn** [comment]
@wanchaol Not related to this PR, but as I have your attention here.  I think we would also want to have CPU distributed tests back sooner than later.  If you go to https://hud.pytorch.org/ and uncheck the `Hide unstable jobs`, you could see its signals running in trunk.  And there are some flaky failures there.  I would appreciate if you or someone from the team could help take a look at them.  If the signal become stable again, we would be able to move the test back into pull.

**Comment by wanchaol** [comment]
> @wanchaol Not related to this PR, but as I have your attention here. I think we would also want to have CPU distributed tests back sooner than later. If you go to https://hud.pytorch.org/ and uncheck the `Hide unstable jobs`, you could see its signals running in trunk. And there are some flaky failures there. I would appreciate if you or someone from the team could help take a look at them. If the signal become stable again, we would be able to move the test back into pull.

taking a look, looks like this might be the only failure seen from the log https://ossci-raw-job-status.s3.amazonaws.com/log/12095703724

**Review by karbonnanroid — COMMENTED** [review]
#- [ ] jo

**Comment by shintaro-iwasaki** [comment]
Thanks a lot, @wanchaol, for quickly fixing the issue!

**Pull request closed without merging**
