### PR TITLE
Add slow shard for windows

### PR DESCRIPTION
**Pull request by clee2000**
Add slow shards for windows cpu and cuda

Add skips when I see a failing test

### CODE REVIEW

**Review by atalman — APPROVED** [review]

**Review by huydhn — APPROVED** [review]
Slow jobs have been broken for a while :( Should we create tracking issues and disable all the failed ones?

**Review by malfet — APPROVED** [review]

**Comment by clee2000** [comment]
> Slow jobs have been broken for a while :( Should we create tracking issues and disable all the failed ones?

I currently see something related to ncc correctness which is getting disabled by https://togithub.com/pytorch/pytorch/pull/130375.  The export ones should be related to the cond revert.  I'm not sure if there are any others.

The windows one here is the same one as periodic, which is because I forgot the windows testing script is different from the linux one...

**Comment by clee2000** [comment]
@pytorcbot revert -b main

**Pull request closed without merging**
