### PR TITLE
Fix for tests on ROCm

### PR DESCRIPTION
**Pull request by ashishfarmer**
This pull request fixes and re-enables two of the tests disabled in #37427
1. `test_sparse_add_out_bfloat16` in test_sparse.py fixed to use updated `atol` argument instead of `prec` for `assertEqual`
2. The conversion of `flt_min` to `int64` is divergent on HIP compared to numpy. The change removes that conversion from the `test_float_to_int_conversion_finite` test case in test_torch.py

cc: @ezyang @jeffdaily

### CODE REVIEW

**Comment by ezyang** [comment]
> The conversion of flt_min to int64 is divergent on HIP compared to numpy. 

OK, but instead of changing the test, shouldn't you fix the behavior?

**Comment by jeffdaily** [comment]
> > The conversion of flt_min to int64 is divergent on HIP compared to numpy.
> 
> OK, but instead of changing the test, shouldn't you fix the behavior?

Our rationale here was that we were following the precedent set by the test's exception for CUDA behavior.  `# Note: CUDA max float -> integer conversion is divergent on some dtypes`.  But that HIP has the additional divergent behavior.

**Comment by jeffdaily** [comment]
We are investigating further whether the HIP behavior can be changed.  For the time being, skipping the additional float min conversion is the best we can do at this time.

**Review by ezyang — APPROVED** [review]
OK, well, I won't block this if there's precedent.

**Pull request closed without merging**
