### PR TITLE
get torch.distributed.breakpoint() to work under Python/Meta contexts

### PR DESCRIPTION
**Pull request by bdhirsh**
I noticed that when I put a `torch.distributed.breakpoint()` in [here](https://github.com/pytorch/pytorch/blob/main/torch/_subclasses/meta_utils.py#L605), it would fail. This fixes it.

In theory, it would probably be better to have a way to get the `barrier()` call to skip the dispatcher completely. I wasn't sure how to do that though, and this seems to cover 90% of issues.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### CODE REVIEW

**Comment by bdhirsh** [comment]
btw, two more paper-cuts with using `torch.distributed.breakpoint()` that I noticed:

(1) "n"/"next" don't work as you'd expect: the problem is that hitting "next" immediately jumps you past the `barrier()` call, so current process moves on without us. I can't think of a way to get this to work automatically, but instead I changed my breakpoint code like so:
```
def foo(...):
    torch.distributed.breakpoint()
    code_I_want_to_step_through()
    barrier()
```

(2) up and down don't work (they print the ascii for the up and down keys, instead of pasting previously-ran commands on the terminal). No idea why

**Review by yifuwang — APPROVED** [review]
Nice!

**Comment by wconstab** [comment]
> (1) "n"/"next" don't work as you'd expect: the problem is that hitting "next" immediately jumps you past the barrier() call, so current process moves on without us. I can't think of a way to get this to work automatically, but instead I changed my breakpoint code like so:

I think this part is a known issue that i couldn't figure out how to work around.  If you type 'up' then 'next' (or 'u', 'n') i think you get around this.

Not to be confused with the 'up arrow' not working, which i also have no solution for.  you can usually remove problematic keys from your keyboard though.

**Comment by bdhirsh** [comment]
> I think this part is a known issue that i couldn't figure out how to work around. If you type 'up' then 'next' (or 'u', 'n') i think you get around this.

> Not to be confused with the 'up arrow' not working, which i also have no solution for. you can usually remove problematic keys from your keyboard though.

Ah nice - I should have tried this :) Thanks!

**Pull request closed without merging**
