### PR TITLE
[modes] fix modes so not implemented falls through to the next mode, not to subclass

### PR DESCRIPTION
**Pull request by samdow**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #91573
* #90770
* __->__ #91521

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]
Nice!

**Comment by samdow** [comment]
So I was about to merge #90770 but ended up with this weird error. After investigating here's what was happening:

assume stack of modes: top -> [A, B] and with an arg C, a  torch_dispatch subclass. Assume A and B always return NotImplemented for this example

Previously:
runs A's torch_dispatch -> get NotImplemented 
-> fall through to subclass -> run C's torch_dispatch (with A pushed back on)

Specifically, B's torch_dispatch is never run (!!!)

What will happen now:
runs A's torch_dispatch -> get NotImplemented -> recurse (A is not pushed back on) 
-> run B's torch_dispatch -> get NotImplemented -> recurse (mode stack is not empty) 
-> fall through to subclass -> run C's torch_dispatch (with an empty mode stack, all redispatches will not use the mode stack)

not sure if anyone was relying on C's torch dispatch to run with the mode stack back on, but something something it's a private API

**Comment by zou3519** [comment]
cc @bdhirsh -- this is the problem we were talking about today in https://github.com/pytorch/pytorch/pull/91463. Not sure if you and Sam chatted or if the fix was pure coincidence

**Comment by ezyang** [comment]
Hmm, it's not clear to me that this is the correct semantics.

The intention between the NotImplemented handling is to give subclasses (which are not modal) a chance to discharge themselves, by letting them dynamically run before the mode in question.  What is NOT the intention is if we have the mode stack A, B, if A returns NotImplemented, we shouldn't then go and try to apply B, because the user clearly specified that they want A to run first, and then B, and just skipping A if it returns NotImplemented is not what anyone asked for (if A wanted to go on and run the inner mode, it should have redispatched to func.)

So I think what I would suggest, is if we go to C's dispatch, BOTH A and B had better be on the stack (only putting A back on the stack is wrong). Then B will not be skipped... unless C is terminal, but in that case A is also getting skipped too, whatever.

**Comment by ezyang** [comment]
So, I will definitely admit that the interplay here is confusing. If we could take a purist approach, I would definitely advocate for mode only, and then the stuff about NotImplemented evaporates; you either handle it (and redispatch), or you error.

Let me explain where my intuition for NotImplemented semantics comes from. The originating idea for NotImplemented comes from how Python implements multiple dispatch for binary operations. Suppose I am processing a + b, where a and b are some arbitrary subclasses that may or may not know each other. Because OO is naturally single dispatch, it is possible that A knows how to process the addition, but it is also possible B knows, and a priori we do not know which one it should be. So Python says, well, first I will try `A.__add__(a, b)`, but if it returns NotImplemented, I'll try `B.__radd__(b, a)` and use that result instead. This gives both classes a chance to handle the operation, and so if A is written in a cooperative way, it will recognize when B is a class it doesn't understand and return NotImplemented to give B a chance to handle it. There is no other way for A to say, "please try B".

Now, let me explain why I don't think this handoff applies for modes. In the case of OO multiple dispatch, there is no "best choice" for A or B to be selected. Either of them could handle it symmetrically, and the fact that we prefer A is just a logical tie-breaker (left to right.) But now consider a stack of modes [M1, M2]. There is a *stack*: there is a clear preference for which handler should be handled first: M2! (or M1, depending on which direction you read the stack. The top of the stack, in any case, haha). So there is no need to apply the multiple dispatch NotImplemented trick; there is no ambiguity about which handler to call. In particular, there is a direct way for M2 to say, please try M1: just redispatch with M2 disabled.

So my prior when mashing these features together (which is confusing, I acknowledge!) is to *only* use NotImplemented to resolve OO multiple dispatch problems, and not for anything else. Now, unlike the purist view above, modes can return NotImplemented, for the reason that when a mode gets unrecognized subclasses, we *do* now need a way to opt into the NotImplemented mechanism; but we could have also done it some other way, like a function you can call to trigger OO style multiple dispatch. But that function, you guess it, better reenable the mode you're currently handling so we eventually get back to you.

Does that make sense?

**Comment by zou3519** [comment]
> So, I will definitely admit that the interplay here is confusing. If we could take a purist approach, I would definitely advocate for mode only, and then the stuff about NotImplemented evaporates; you either handle it (and redispatch), or you error.

I don't have full context over what is going on with the mode <-> subclass interaction. But I'd prefer we take a purist approach where modes are not allowed to return NotImplemented. So far it sounds like we didn't do this because we wanted make_fx to compose with Tensor Subclasses, so we wrote up the NotImplemented interaction. Is that understanding correct, and are there other reasons why we cannot do the purist approach?

The moral argument for purist approach is: a mode on the mode stack should behave similarly to a functorch transform. That is, it should be agnostic to what modes / Tensor Subclasses come after it (otherwise, it will run into composability problems and shouldn't be a "stackable" mode). Right now we have a weird situation where ProxyMode returns NotImplemented if it sees a Tensor Subclass that wasn't passed in as input.

**Comment by ezyang** [comment]
So, if we want to do the purist approach, it is possible to do and also preserve the existing behavior: instead of having modes return NotImplemented, we can just have a helper utility that is "try to run the tensor subclasses in the arguments of this function." Most of what you need for it even already exists in Python, since we have implementation of torch function handler in both Python and C++ (but not all of it, since in this case you need an implementation of torch dispatch). This may also be superior because it includes the mode in the backtrace, making it easier to debug that this has occurred. So I would support this course of action.

**Comment by samdow** [comment]
Closing and making fake tensor return not implemented like suggested. Changes the error produced but at least it's not silently correct

**Pull request closed without merging**
