### PR TITLE
Correct test random seeding and autograd test flakiness

### PR DESCRIPTION
**Pull request by gchanan**
See individual commits for details.

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Review by apaszke — COMMENTED** [review]
Wasn't it simpler to make autograd tests use `run_tests()`? I can't see why do we need to separate and call this helper

**Comment by gchanan** [comment]
See commit https://github.com/pytorch/pytorch/pull/1970/commits/9e96e0fc16dab0beb041d642e4c2e7066d4f1bc3 -- there were random calls happening before run_tests.

**Comment by apaszke** [comment]
Then couldn't we unconditionally execute PRNG init in `common.py`? This would prevent this kind of error in all tests, not only in autograd (I think `torch.nn` might be suffering from it too).

**Comment by gchanan** [comment]
yes, I think that's a good solution.

**Pull request merged**
