### PR TITLE
Composite compliance for index_put

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #71766
* __->__ #71765
* #71751
* #71750

This PR gives index_put the same treatment as
https://github.com/pytorch/pytorch/pull/71751.

Test Plan:
- wait for tests

Differential Revision: [D33772755](https://our.internmc.facebook.com/intern/diff/D33772755)

### CODE REVIEW

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33772755).

**Review by albanD — APPROVED** [review]
Ok!

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33772755).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33772755).

**Pull request closed without merging**
