### PR TITLE
Expose c10::List

### PR DESCRIPTION
**Pull request by cyyever**
Since  IValue methods use them as discussed in #127560.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by cyyever** [comment]
> `@pytorchbot label "topic: not user facing"`

They are generic data structures. In principle they can be replaced.

**Comment by cyyever** [comment]
> What is the point of c10::List and c10::Dict? Any chance they can be replaced with STL equivalents now?

They are generic data structures. In principle they can be replaced. We can gradually replace them in next versions.

**Comment by ezyang** [comment]
No they can't be replaced with stl, they are boxed structs for holding IValues

**Pull request closed without merging**
