### PR TITLE
[torch._numpy] implement `ndarray.tobytes`

### LINKED ISSUE #108565: `bytes(...)` support of torch tensor does not match numpy
### 🐛 Describe the bug

```python
import numpy as np
import torch

a = np.arange(3)
print(bytes(a))
# b'\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00'

b = torch.arange(3)
print(bytes(b))
# b'\x00\x01\x02'

print(a.tobytes())
# b'\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00'

print(b.tobytes())
# AttributeError: 'Tensor' object has no attribute 'tobytes'
``` 

Maybe related issues:
- https://github.com/pytorch/pytorch/issues/43949
- https://github.com/pytorch/pytorch/issues/33041

### Versions

>>> np.__version__
'1.24.2'
>>> import torch
torch.__version__
>>> torch.__version__
'2.1.0.dev20230802+cpu'

### PR DESCRIPTION
**Pull request by jon-chuang**
Partial fix: https://github.com/pytorch/pytorch/issues/108565

cc @mruberry @rgommers

### CODE REVIEW

**Comment by jon-chuang** [comment]
We still can't support it in dynamo :'(

```
torch._dynamo.exc.Unsupported: data dependent operator: aten._local_scalar_dense.default
    return self.obj.call_method(tx, self.name, args, kwargs)
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/variables/tensor.py", line 932, in call_method
    return NumpyNdarrayVariable.create(tx, proxy)
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/variables/tensor.py", line 847, in create
    return wrap_fx_proxy_cls(
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/variables/builder.py", line 1368, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/utils.py", line 1498, in get_fake_value
    unimplemented(f"data dependent operator: {cause.func}")
  File "/home/jonch/Desktop/Programming/mlsys/pytorch/torch/_dynamo/exc.py", line 193, in unimplemented
    raise Unsupported(msg)
from user code:
   File "/home/jonch/Desktop/Programming/mlsys/pytorch/test/dynamo/test_repros.py", line 3644, in fn
    z = x.tobytes()
```

**Comment by jon-chuang** [comment]
Oh wait, I think it just needs special handling. Will be follow up.

**Comment by jon-chuang** [comment]
Actually, there is no possible way to support this in dynamo. The value is completely data dependent.

**Comment by vadimkantorov** [comment]
A small improvement could be: also supporting .tobytes('C') and .tobytes(order='C'). I think both currently will throw and funnily say that only order 'C' is supported :)

**Review by lezcano — CHANGES_REQUESTED** [review]
If this is to be implemented, it should be implemented in the Tensor API. It should also be tested via OpInfos.

At any rate, I would like to first know what @ezyang @albanD have to say in this, as perhaps there is a deeper reason why this has not been implemented in PyTorch before.

**Comment by jon-chuang** [comment]
> I agree it is not so useful in torch._numpy, since we can't trace through it to generate PT2-able code

Yep, my original motivation was in blind pursuit of tracing it into the graph, so given that we can't/shouldn't, I'm ok with not landing this, unless someone really thinks it will be useful somewhere.

**Comment by ezyang** [comment]
I mean, if you put this on torch.Tensor instead, I think it's mildly useful.

**Pull request closed without merging**
