### PR TITLE
[pytorch][mobile] get rid of dynamic_cast in Quantizer

### PR DESCRIPTION
**Pull request by ljk53**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#25001 [pytorch][mobile] get rid of dynamic_cast in Quantizer**

Seems QScheme and Quantizer class type has 1-1 mapping, so use it to compare whether
two quantizers are equal instead of using dynamic_cast.
This way the code can remain mobile friendly as our internal mobile build doesn't
enable rtti by default.

Differential Revision: [D16951501](https://our.internmc.facebook.com/intern/diff/D16951501/)

### CODE REVIEW

**Review by jamesr66a — COMMENTED** [review]
> Seems QScheme and Quantizer class type has 1-1 mapping,

Seems like a pretty dangerous assumption, especially in light of the fact that if this assumption is broken it would likely manifest as hard-to-detect serialization size issues or potentially memory corruption

Off the top of my head I can think of a few ways to go about this:

1) Keep this like it is, but use preprocessor macros to use RTTI on server so we can catch bugs more easily
2) Define virtual methods on Quantizer instances that produce the "serialized" form of the Quantizer, a la __getstate__ APIs. This could return the same IValue we would serialize, and equality would be checked by checking value equality between the IValues
3) Merge the concepts of QScheme and Quantizer to make them truly 1:1
4) Add a big scary comment documenting this assumption

**Comment by jerryzh168** [comment]
> Seems QScheme and Quantizer class type has 1-1 mapping, so use it to compare whether

This is not true after: https://github.com/pytorch/pytorch/pull/24964

**Comment by jerryzh168** [comment]
but Quantizer -> qscheme mapping is probably still valid.

**Comment by jerryzh168** [comment]
@jamesr66a I think it's fine to make the assumption that each qscheme will only have one corresponding quantizer, and also we can remove `qscheme_` as a field, and just return a constant qscheme in each leaf quantizer.

We can add a comment about the assumption and change the code later if this assumption breaks. I can't foresee a situation that this assumption will break though.

**Comment by ljk53** [comment]
@jamesr66a - I can add comment and move qscheme_ to leaf class as a constant as @jerryzh168 suggested. Are you ok with this plan?

**Comment by ljk53** [comment]
Updated according to @jerryzh168's comment. Seems there is already a comment saying QSchema has a one to one correspondence with Quantizer: https://github.com/pytorch/pytorch/blob/a54f8f0f219e0a437846cd2424ca5eb228e8fb86/c10/core/QScheme.h#L11

**Review by jerryzh168 — APPROVED** [review]
LGTM, @jamesr66a please take a look as well

**Review by jamesr66a — APPROVED** [review]

**Pull request closed without merging**
