### PR TITLE
[c10d] Making dist.get_default_group private for PT1 release

### PR DESCRIPTION
**Pull request by teng-li**
When I wrote the frontend API, it is designed on not letting users use the default_group directly on any functions.  It should really be private. 

All collectives are supposed to either use group.WORLD, or anything that comes out of new_group. That was the initial design.

We need to make a TODO on removing group.WORLD one day. It exists for backward compatibility reasons and adds lots of complexity.

### CODE REVIEW

**Comment by apaszke** [comment]
Does that mean that people will always have to specify a group explicitly (i.e. it's not backward compatible)?

**Comment by teng-li** [comment]
@apaszke it's fully backward compatible.  group argument defaults to group.WORLD, and each collective will use the default group automatically. Or group can take anything coming out of new_group().

**Comment by teng-li** [comment]
This is just removing the option for the user to touch and mess around the ProcessGroupNCCL/MPI/Gloo created by init_process_group, which is the default group.

**Comment by apaszke** [comment]
@teng-li Sounds good, thanks!

**Review by pietern — APPROVED** [review]

**Pull request closed without merging**
