### PR TITLE
clarify doc for torch.unique sort=False

### LINKED ISSUE #88447: `unique` will sort the input when `sort=False` on cuda
### 🐛 Describe the bug

`unique` will sort the input when `sort=False` on cuda. On contrast, it will not sort on cpu

```py
import torch

input = torch.FloatTensor([1, 3])
torch.unique(input, sorted=False)
# tensor([3., 1.])
torch.unique(input.cuda(), sorted=False)
# tensor([1., 3.], device='cuda:0')
```

### Versions

torch: 1.13.0
cuda: 11.6

### PR DESCRIPTION
**Pull request by min-jean-cho**
Fixes #88447

### CODE REVIEW

**Comment by min-jean-cho** [comment]
Hi @jgong5, @jingxu10, please help with internal review. Thanks!

**Review by jgong5 — APPROVED** [review]

**Comment by min-jean-cho** [comment]
Hi @ngimel, please help review this PR, thanks!

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
