### PR TITLE
dbr quant: rename seen_op_info to seen_q_op_info

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #71781 dbr quant function fusion [2/x]: use fusion for observation and inference
* #71780 fx quant: add fusion matching for operator.add and torch.relu
* #71764 dbr quant function fusion [1/x]: record matches for functions
* #71551 dbr quant: record dag of non-quantizeable ops
* #71324 dbr quant: refactor first_call hooks to be standalone
* **#71312 dbr quant: rename seen_op_info to seen_q_op_info**

Summary:

Renames `seen_op_info` to `seen_q_op_info` and `SeenOpInfo` to `SeenQOpInfo`.

This is to make it clear that the op here is a quantizeable op.
This is useful for a future PR where we will start recording the DAG
of non-quantizeable ops. That will be needed to properly support
function fusion.

Test plan:

CI and mypy

Differential Revision: [D33584751](https://our.internmc.facebook.com/intern/diff/D33584751)

### CODE REVIEW

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33584751).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33584751).

**Review by HDCharles — APPROVED** [review]
seems straightforward

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33584751).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33584751).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33584751).

**Pull request closed without merging**
