### PR TITLE
reland [finishing colesbury's PR 100642] Guard on nn.Module dicts and type

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108883

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by anijain2305** [comment]
@voznesenskym commented on the earlier PR - 

---------
Glad to see our work crossing the finish line :) please visit guard_nn_modules flag and remove it as needed.

edit: We are still accruing guards all over for where guard.is_nn_module() - we probably don't need to do that anymore with this change, right? So we should just not do that, in favor of the new guards, and pull the bool from config and the installation time exclusion it provides.
--------------

I agree. Let me take that up in the follow up PR. I will stack up a PR on top of this next week. Its easier that way.

**Review by voznesenskym — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Pull request closed without merging**
