### PR TITLE
Fix CPU_INTEL flag error on windows

### PR DESCRIPTION
**Pull request by liooil**
${CMAKE_HOST_SYSTEM_PROCESSOR} get processor name by `uname -p` on linux and `%PROCESSOR_ARCHITECTURE%` on windows
1. %PROCESSOR_ARCHITECTURE% has value in (AMD64|IA64|ARM64) for 64-bit processor, and (x86) for 32-bit processor
2. `uname -p` has value like "(x86_64|i[3-6]+86)"
We cannot tell intel cpu from other cpus by ${CMAKE_HOST_SYSTEM_PROCESSOR}. It is the architecture, not provider.
i. e. Intel CPU i7-9700K CPU on windows get "AMD64"

reference: 
[MSDN](https://docs.microsoft.com/zh-cn/windows/win32/winprog64/wow64-implementation-details?redirectedfrom=MSDN)

### CODE REVIEW

**Comment by liooil** [comment]
# How to reproduce the bug
1. Download LibTorch from [PyTorch](https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.3.1.zip) with build-hash:
> 825f5fc5d7ba9e5ea48f28a7baa559300f64e14f
2. Open file include/ATen/Config.h
3. Found that `#define AT_MKLDNN_ENABLED() 0`

**Review by peterjc123 — APPROVED** [review]

**Comment by peterjc123** [comment]
Acutally we have the environment variable `PROCESSOR_IDENTIFIER` that could tell whether it's intel cpu.

**Comment by ezyang** [comment]
@peterjc123 do you want to merge this as is or wait for your suggested modification?

**Comment by peterjc123** [comment]
cc @xuhdev

**Review by xuhdev — COMMENTED** [review]
Thanks, also makes sense to me.

**Pull request closed without merging**
