### PR TITLE
[PTD][Checkpoint] Upstream fsspec storage read/write to PT

### PR DESCRIPTION
**Pull request by wz337**
Remove sync_files.
Remove single_file_per_rank and will add it back once we resolve the issue. https://github.com/pytorch/pytorch/issues/98386

### CODE REVIEW

**Review by fegin — APPROVED** [review]
LGTM

**Comment by d4l3k** [comment]
Is something like this better located in torchsnapshot?

cc @yifuwang

**Comment by kumpera** [comment]
> Is something like this better located in torchsnapshot?
> 
> cc @yifuwang

Not all DCP users are on torchsnapshot and we'd like to enable them to use fsspec.

**Pull request closed without merging**
