### PR TITLE
[quant][graphmode] Rename backend_config_dict folder to backend_config

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #69882

Summary:
att

Test Plan:
```
python test/fx2trt/test_quant_trt.py
```
Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D33081761](https://our.internmc.facebook.com/intern/diff/D33081761)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33081761).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33081761).

**Comment by vkuzo** [comment]
should the name have something about "config" in it?  "backend" sounds like kernel implementations.

**Comment by jerryzh168** [comment]
Oh OK, I'll change it to backend_config then

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33081761).

**Review by supriyar — APPROVED** [review]

**Pull request closed without merging**
