### PR TITLE
[XNNPACK] Generate new build and wrapper files

### PR DESCRIPTION
**Pull request by kirklandsign**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

update xnnpack_wrappers using generate-wrappers.py

Differential Revision: [D42974915](https://our.internmc.facebook.com/intern/diff/D42974915/)

**NOTE FOR REVIEWERS**: This PR has internal Meta-specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D42974915/)!

### CODE REVIEW

**Review by digantdesai — COMMENTED** [review]
LGTM, we will need some help to land this since its too large

**Comment by digantdesai** [comment]
@albanD / @seemethere Can you guys help here with this large diff? Thanks!
Context: https://github.com/pytorch/pytorch/actions/runs/4108752252/jobs/7089808242

**Comment by albanD** [comment]
Ho wow, do we really have to hardcode all of these? Isn't that going to be a problem going forward?

**Comment by albanD** [comment]
@digantdesai what is the plan to streamline this going forward? Are there key changes needed in XNNPACK or in PT build?

**Comment by seemethere** [comment]
Is this mostly generative changes? If so it would be good to include in the diff description / PR summary the commands used to do the generation.

Also if these are generated files we should add them to the root level `.gitattributes` file so that they get correctly marked.

**Comment by tiandiao123** [comment]
this one has been closed! please look at https://github.com/pytorch/pytorch/pull/94330

**Comment by digantdesai** [comment]
> Is this mostly generative changes? If so it would be good to include in the diff description / PR summary the commands used to do the generation.

This is a mix of generated and manually updated files. For the generated ones, we have a script, which is not in PyTorch Github repo.

> Also if these are generated files we should add them to the root level `.gitattributes` file so that they get correctly marked.

We can mark those bzl files with `linguist-generated=true` attribute if you recommend, but would still run into 2K LOC limit though, right?

BTW created a new PR for these #94330, closing this one. So we can discuss there if you prefer.

**Comment by digantdesai** [comment]
> @digantdesai what is the plan to streamline this going forward? Are there key changes needed in XNNPACK or in PT build?

@albanD - For CMake builds we are just using XNNPACK cmake, so that's good. For OSS buck builds, we are planning to automate (not sure exactly how yet) updating these files when we update the xnnpack submodule. FWIW, @linbinyu did some streamlining in #80209. But if you are referring to how to avoid these large LOC commits, not sure what we can do given how fast XNNPACK moves. We can perhaps update the submodule more frequently.

**Pull request closed without merging**
