### PR TITLE
ci: Migrate macOS x86_64 binary builds to GHA

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #71893
* __->__ #71888

Migrates binary builds for x86_64 for macOS from CircleCI to GHA.

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

Differential Revision: [D34150398](https://our.internmc.facebook.com/intern/diff/D34150398)

### CODE REVIEW

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33851316).

**Comment by seemethere** [comment]
Builds have passed in the testing PR: https://github.com/pytorch/pytorch/pull/71893

Opening this up for review now

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33851316).

**Review by malfet — APPROVED** [review]

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33851316).

**Comment by janeyx99** [comment]
Reverting as this change broke OSS MacOS binary jobs, see [https://www.torch-ci.com/minihud?name_filter=binary_macos_libtorch_3_7_cpu_build%20/%20build](https://www.torch-ci.com/minihud?name_filter=binary_macos_libtorch_3_7_cpu_build%20%2F%20build)

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34150398).

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
