### PR TITLE
Fix test_addmm_gelu assertion on Windows CUDA

### PR DESCRIPTION
**Pull request by aakhundov**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104031

Summary:

This PR fixes the wrong assertion in the `test_addmm_gelu` happening in the Windows CUDA CI job caused by #103811. The addmm + GELU fusion is likely not happening (or not using the tanh approximation) on Windows. See [this comment](https://github.com/pytorch/pytorch/pull/103811#issuecomment-1601936203) in the #103811 for the details of the error.

Test Plan:

```
$ python test/test_linalg.py -k test_addmm_relu -v
test_addmm_relu_cpu_bfloat16 (__main__.TestLinalgCPU.test_addmm_relu_cpu_bfloat16) ... ok
test_addmm_relu_cpu_float32 (__main__.TestLinalgCPU.test_addmm_relu_cpu_float32) ... ok
test_addmm_relu_cpu_float64 (__main__.TestLinalgCPU.test_addmm_relu_cpu_float64) ... ok
test_addmm_relu_cuda_bfloat16 (__main__.TestLinalgCUDA.test_addmm_relu_cuda_bfloat16) ... ok
test_addmm_relu_cuda_float32 (__main__.TestLinalgCUDA.test_addmm_relu_cuda_float32) ... ok
test_addmm_relu_cuda_float64 (__main__.TestLinalgCUDA.test_addmm_relu_cuda_float64) ... ok

----------------------------------------------------------------------
Ran 6 tests in 2.131s

OK

$ python test/test_linalg.py -k test_addmm_gelu -v
test_addmm_gelu_cpu_bfloat16 (__main__.TestLinalgCPU.test_addmm_gelu_cpu_bfloat16) ... ok
test_addmm_gelu_cpu_float32 (__main__.TestLinalgCPU.test_addmm_gelu_cpu_float32) ... ok
test_addmm_gelu_cpu_float64 (__main__.TestLinalgCPU.test_addmm_gelu_cpu_float64) ... ok
test_addmm_gelu_cuda_bfloat16 (__main__.TestLinalgCUDA.test_addmm_gelu_cuda_bfloat16) ... ok
test_addmm_gelu_cuda_float32 (__main__.TestLinalgCUDA.test_addmm_gelu_cuda_float32) ... ok
test_addmm_gelu_cuda_float64 (__main__.TestLinalgCUDA.test_addmm_gelu_cuda_float64) ... ok

----------------------------------------------------------------------
Ran 6 tests in 2.194s

OK
```

Reviewers: @eellison @huydhn

Subscribers:

Tasks:

Tags:

Differential Revision: [D46931688](https://our.internmc.facebook.com/intern/diff/D46931688)

### CODE REVIEW

**Comment by aakhundov** [comment]
@aakhundov has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D46931688).

**Review by huydhn — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by aakhundov** [comment]
We've discussed the issue with @eellison and agreed that it would be better to switch to the "tanh" approximation for non-fused GELU in the `aten._addmm_activation` op, for consistency. As the API is private, this sounds like a more consistent way than patching different cases in the unit test. Will update the PR soon accordingly.

**Comment by eellison** [comment]
@aakhundov if HUD is in a bad state, maybe it makes sense to land this if it fixes tests, then in a separate pr update ?

**Comment by aakhundov** [comment]
@huydhn @malfet @eellison the merge failed again due to the [periodic / ios-12-5-1-x86-64-coreml / build (default, 1, 1, macos-12)](https://github.com/pytorch/pytorch/actions/runs/5347823073/jobs/9696902052) job, which also seems unrelated. Any hint on how to bypass / fix this? Thanks!

**Comment by eellison** [comment]
You can merge past failures with `merge -f {reason}`

**Pull request closed without merging**
