### PR TITLE
disable test int_mm for sm90 or later 

### PR DESCRIPTION
**Pull request by tinglvv**
disable test int_mm for sm90 or later

```
python test/test_linalg.py -k test__int_mm_k_32_n_32_use_transpose_a_False_use_transpose_b_False_cuda

_ TestLinalgCUDA.test__int_mm_k_32_n_32_use_transpose_a_False_use_transpose_b_False_cuda _
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 2410, in wrapper
    method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 2410, in wrapper
    method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_device_type.py", line 428, in instantiated_test
    raise rte
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_device_type.py", line 415, in instantiated_test
    result = test(self, **param_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_device_type.py", line 1084, in only_fn
    return fn(slf, *args, **kwargs)
  File "/opt/pytorch/pytorch/test/test_linalg.py", line 5719, in test__int_mm
    _test(17, k, n, use_transpose_a, use_transpose_b)
  File "/opt/pytorch/pytorch/test/test_linalg.py", line 5680, in _test
    c_int32 = torch._int_mm(a_int8, b_int8)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling cublasLtMatmul with transpose_mat1 0 transpose_mat2 0 m 32 n 17 k 32 mat1_ld 32 mat2_ld 32 result_ld 32 abType 3 cType 10 computeType 72 scaleType 10
```

cc @csarofeen @ptrblck @xwang233 @eqy

### CODE REVIEW

**Comment by eqy** [comment]
CC @malfet Unfortunate regression that we will follow-up with cuBLAS team on

**Review by malfet — CHANGES_REQUESTED** [review]
Thank you for reporting, but I think revert here is incorrect, as _int_mm works on CUDA-12 for all architectures but H100, i.e. the right behavior here would be to skip the test (or exepect it to fail) if running on SM90OrLater.
Alternative, if this code is not useful, let's just delete it, as it's very unlikely one will restart building PyTorch using CUDA-11.7 any time in the future

**Comment by ptrblck** [comment]
I also think reverting the PR enabling `CUDA>=11.7` is wrong. Could we narrow down the scope of the issue and either work around it or disable it only for sm_90, if applicable?

**Comment by eqy** [comment]
Yeah, my bad in assuming it was a regression rather than being newly surfaced on H100.

**Comment by coyotelll** [comment]
Thanks for the comments. I have updated the PR to disable the test for sm90 or later.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
