### PR TITLE
Relandx3  "SymIntify cat and narrow"

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #86289

This reverts commit fc94a2115b31dfe7a0d8f28eb4f5ed532c4f0792.

### CODE REVIEW

**Review by wconstab — APPROVED** [review]

**Comment by seemethere** [comment]
Sorry to revert this again but it appears as though internal users are using this original function:

```
stderr: <redacted>: error: no member named 'narrow' in namespace 'at::native'; did you mean simply 'narrow'?
[CONTEXT]           at::native::narrow(input, dim, i * split_size, length), dim);
[CONTEXT]           ^~~~~~~~~~~~~~~~~~
```

from: [internalfb.com/intern/sandcastle/job/27021598552487548](https://www.internalfb.com/intern/sandcastle/job/27021598552487548/)

**Comment by ezyang** [comment]
@wconstab let's give this the aten/src/ATen/native/NonSymbolicBC.h treatment

**Pull request closed without merging**
