### PR TITLE
[torch] Use __prepare_scriptable__ for closures

### PR DESCRIPTION
**Pull request by dherrera-meta**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #120806

This fixes a case left incomplete by https://github.com/pytorch/pytorch/pull/106229
The object is using __prepare_scriptable__ correctly inside of torch.jit.script()
but the clousre that is obtained below is using the non-prepared version.
This causes issues when the prepared and non-prepared versions are in different python modules.

The next diff fails without this fix.

Differential Revision: [D54308741](https://our.internmc.facebook.com/intern/diff/D54308741/)

### CODE REVIEW

**Comment by dherrera-meta** [comment]
https://github.com/pytorch/pytorch/pull/106229 already came really close to enabling decorators that can be ignored by torch scripting. The following can be used to ignore them:
```
def logging(func):
   # The logging_not_scriptable() decorator is not torch jit compatible
   wrapped = logging_not_scriptable(func)

   # Setting the __prepare_scriptable__ allows torch script to ignore the decorator
   # Useful for logging and typechecking decorators
   wrapped.__prepare_scriptable__ = lambda: func

@logging
def foo():
   ... # Valid scriptable code

foo_jit = torch.script.jit(foo) # The compiled version doesn't have the decorator
```
This was tried in torch/vision (see https://github.com/pytorch/vision/pull/5424 and https://github.com/pytorch/pytorch/issues/70051) but it failed because the resolution context was built around the decorator and not the real function.

This change fully enables ignoring decorators.

**Comment by ezyang** [comment]
@pmeier could I persuade you to review this LOL

**Comment by pmeier** [comment]
Yes, I can have a look next week.

**Comment by davidberard98** [comment]
Would it be possible to add a test for the previously failing case?

**Comment by dherrera-meta** [comment]
@davidberard98  I added a unit test. It needed to be split between several files to highlight the issue.

**Review by eellison — APPROVED** [review]

**Comment by izaitsevfb** [comment]
@dherrera-meta, your PR wasn't actually merged into trunk. Please use @pytorchbot to merge.

**Pull request merged**
