### PR TITLE
[No merge] test case failure

### PR DESCRIPTION
**Pull request by zejun-chen**
No merge this PR because it is used to test the following cases for XPU.
`profiler/test_profiler.py::TestProfilerMultithreaded::test_source_multithreaded_basic_work_in_main_thread_True
`

cc @gujinghui @EikanWang @fengyuan14 @guangyey

### CODE REVIEW

**Comment by zejun-chen** [comment]
Hi, @gujinghui
Could you help me add the xpu ci flow label and run the CI to test the cases.
I made the code change for moving the case outside the TestProfiler.
Thank you.

**Comment by zejun-chen** [comment]
The case failed when moving the test case outside of the test class.

**Comment by aaronenyeshi** [comment]
I'm not sure why this is failing, maybe need to ask help from DevInfra team. cc @huydhn do you know why moving these tests might fail?

**Comment by zejun-chen** [comment]
> I'm not sure why this is failing, maybe need to ask help from DevInfra team. cc @huydhn do you know why moving these tests might fail?

Hi, @huydhn @robieta

This PR is just used to test the UT `test_source_multithreaded` when moving them outside of the test class `TestProfiler`.
However the UT failed as below in PyTorch CI:
```
2024-09-16T03:01:55.5973270Z =================================== FAILURES ===================================
2024-09-16T03:01:55.5973963Z ____ TestProfiler1.test_source_multithreaded_basic_work_in_main_thread_True ____
2024-09-16T03:01:55.5974585Z Traceback (most recent call last):
2024-09-16T03:01:55.5975389Z   File "/var/lib/jenkins/workspace/test/profiler/test_profiler.py", line 228, in test_source_multithreaded
2024-09-16T03:01:55.5976190Z     @parametrize(
2024-09-16T03:01:55.5977055Z   File "/var/lib/jenkins/workspace/test/profiler/test_profiler.py", line 264, in torch_dynamo_resume_in_test_source_multithreaded_at_264
2024-09-16T03:01:55.5978159Z     start_barrier = threading.Barrier(num_threads, timeout=timeout)
2024-09-16T03:01:55.5979267Z   File "/var/lib/jenkins/workspace/test/profiler/test_profiler.py", line 390, in torch_dynamo_resume_in_test_source_multithreaded_at_265
2024-09-16T03:01:55.5980357Z     self.assertEqual(len(observed_during_run), worker_threads)
2024-09-16T03:01:55.5981555Z   File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/testing/_internal/common_utils.py", line 3885, in assertEqual
2024-09-16T03:01:55.5982480Z     raise error_metas.pop()[0].to_error(
2024-09-16T03:01:55.5982916Z AssertionError: Scalars are not equal!
2024-09-16T03:01:55.5983199Z 
2024-09-16T03:01:55.5983310Z Expected 2 but got 1.
2024-09-16T03:01:55.5983625Z Absolute difference: 1
2024-09-16T03:01:55.5983952Z Relative difference: 0.5
2024-09-16T03:01:55.5984166Z 
2024-09-16T03:01:55.5984419Z To execute this test, run the following from the base repo dir:
2024-09-16T03:01:55.5985497Z     PYTORCH_TEST_WITH_DYNAMO=1 python test/profiler/test_profiler.py TestProfiler1.test_source_multithreaded_basic_work_in_main_thread_True
2024-09-16T03:01:55.5986324Z 
2024-09-16T03:01:55.5986640Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-09-16T03:01:55.5988057Z - generated xml file: /var/lib/jenkins/workspace/test/test-reports/python-pytest/profiler.test_profiler/profiler.test_profiler-358fbb7f01177e42.xml -
2024-09-16T03:01:55.5989406Z =========================== short test summary info ============================
```

```
2024-09-16T02:54:44.0635452Z =================================== FAILURES ===================================
2024-09-16T02:54:44.0677939Z #20 PyObject_Vectorcall from ??:0
2024-09-16T02:54:44.0678320Z #21 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0678730Z #22 PyObject_Vectorcall from ??:0
2024-09-16T02:54:44.0679126Z #23 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0679599Z #24 _PyObject_VectorcallTstate.lto_priv.4.cold from :0
2024-09-16T02:54:44.0680087Z #25 method_vectorcall from :0
2024-09-16T02:54:44.0680454Z #26 PyObject_Vectorcall from ??:0
2024-09-16T02:54:44.0680838Z #27 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0681324Z #28 PyObject_Vectorcall from ??:0
2024-09-16T02:54:44.0681723Z #29 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0682132Z #30 eval_custom_code from eval_frame.c:0
2024-09-16T02:54:44.0682585Z #31 custom_eval_frame_shim from eval_frame.c:0
2024-09-16T02:54:44.0683028Z #32 PyObject_Vectorcall from ??:0
2024-09-16T02:54:44.0683413Z #33 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0683837Z #34 eval_custom_code from eval_frame.c:0
2024-09-16T02:54:44.0684288Z #35 custom_eval_frame_shim from eval_frame.c:0
2024-09-16T02:54:44.0684732Z #36 _PyObject_Call.localalias from :0
2024-09-16T02:54:44.0685147Z #37 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0685635Z #38 _PyObject_VectorcallTstate.lto_priv.4.cold from :0
2024-09-16T02:54:44.0686103Z #39 method_vectorcall from :0
2024-09-16T02:54:44.0686476Z #40 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0686889Z #41 PyObject_Vectorcall from ??:0
2024-09-16T02:54:44.0687274Z #42 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0687689Z #43 PyObject_Vectorcall from ??:0
2024-09-16T02:54:44.0688082Z #44 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0688550Z #45 _PyObject_VectorcallTstate.lto_priv.4.cold from :0
2024-09-16T02:54:44.0689028Z #46 method_vectorcall from :0
2024-09-16T02:54:44.0689398Z #47 _PyObject_Call.localalias from :0
2024-09-16T02:54:44.0689801Z #48 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0690226Z #49 eval_custom_code from eval_frame.c:0
2024-09-16T02:54:44.0690677Z #50 custom_eval_frame_shim from eval_frame.c:0
2024-09-16T02:54:44.0691115Z #51 _PyObject_Call.localalias from :0
2024-09-16T02:54:44.0691530Z #52 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0691995Z #53 _PyObject_VectorcallTstate.lto_priv.4 from :0
2024-09-16T02:54:44.0692440Z #54 method_vectorcall from :0
2024-09-16T02:54:44.0692810Z #55 _PyObject_Call.localalias from :0
2024-09-16T02:54:44.0693287Z #56 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0693765Z #57 _PyObject_FastCallDictTstate.localalias from :0
2024-09-16T02:54:44.0694259Z #58 _PyObject_Call_Prepend from ??:0
2024-09-16T02:54:44.0694651Z #59 slot_tp_call from :0
2024-09-16T02:54:44.0695009Z #60 _PyObject_MakeTpCall.localalias from :0
2024-09-16T02:54:44.0695463Z #61 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0695944Z #62 _PyObject_FastCallDictTstate.localalias from :0
2024-09-16T02:54:44.0696422Z #63 _PyObject_Call_Prepend from ??:0
2024-09-16T02:54:44.0696893Z #64 slot_tp_call from :0
2024-09-16T02:54:44.0697242Z #65 _PyObject_Call.localalias from :0
2024-09-16T02:54:44.0697647Z #66 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0698130Z #67 _PyObject_FastCallDictTstate.localalias from :0
2024-09-16T02:54:44.0698630Z #68 _PyObject_Call_Prepend from ??:0
2024-09-16T02:54:44.0699007Z #69 slot_tp_call from :0
2024-09-16T02:54:44.0699377Z #70 _PyObject_MakeTpCall.localalias from :0
2024-09-16T02:54:44.0699831Z #71 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0700307Z #72 _PyObject_FastCallDictTstate.localalias from :0
2024-09-16T02:54:44.0700793Z #73 _PyObject_Call_Prepend from ??:0
2024-09-16T02:54:44.0701179Z #74 slot_tp_call from :0
2024-09-16T02:54:44.0701534Z #75 _PyObject_MakeTpCall.localalias from :0
2024-09-16T02:54:44.0701984Z #76 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0702465Z #77 _PyObject_FastCallDictTstate.localalias from :0
2024-09-16T02:54:44.0702941Z #78 _PyObject_Call_Prepend from ??:0
2024-09-16T02:54:44.0703329Z #79 slot_tp_call from :0
2024-09-16T02:54:44.0703699Z #80 _PyObject_MakeTpCall.localalias from :0
2024-09-16T02:54:44.0714578Z #81 _PyEval_EvalFrameDefault from ??:0
2024-09-16T02:54:44.0715148Z #82 PyEval_EvalCode from ??:0
2024-09-16T02:54:44.0715521Z #83 run_eval_code_obj from :0
2024-09-16T02:54:44.0715867Z #84 run_mod from :0
2024-09-16T02:54:44.0716155Z #85 pyrun_file from :0
2024-09-16T02:54:44.0716549Z #86 _PyRun_SimpleFileObject.localalias from :0
2024-09-16T02:54:44.0717050Z #87 _PyRun_AnyFileObject.localalias from :0
2024-09-16T02:54:44.0717624Z #88 Py_RunMain.localalias from :0
2024-09-16T02:54:44.0718014Z #89 Py_BytesMain from ??:0
2024-09-16T02:54:44.0718364Z #90 __libc_start_main from ??:0
2024-09-16T02:54:44.0718712Z #91 _start from ??:0
2024-09-16T02:54:44.0718919Z 
```

It should not fail but it can be stable reproduced in the PyTorch CI. From the error, the UT `test_source_multithreaded` has unexpected something with the other UTs in the test class `TestProfiler`. Could you help take a look and disable the UT so that the other PR can be normally merged?

Thank you.

**Comment by zejun-chen** [comment]
Close because the test is done and our PR for upstream test cases for kineto xpu backend has been finished.

**Pull request closed without merging**
