### PR TITLE
Minor update to ROCm triton commit pin

### PR DESCRIPTION
**Pull request by jataylo**
This is required for a fix in latest nightly wheels in which the hip_runtime header file cannot be found during triton lowering

```
/tmp/tmpqoq6gtl8/main.c:3:14: fatal error: hip/hip_runtime.h: No such file or directory
3 | #include <hip/hip_runtime.h>
| ^~~~~~~~~~~~~~~~~~~
```

This is a single commit update to bring in this change
https://github.com/ROCmSoftwarePlatform/triton/pull/283

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang

### CODE REVIEW

**Comment by jataylo** [comment]
Hi @malfet @kit1980, just updating our triton rocm commit one commit forwards to fix an issue in our latest nightly wheels. There has been some directory changes in triton we needed to update in our wheels in order to find relevant ROCm libs and headers.

**Review by malfet — APPROVED** [review]
LGTM
@jithunnair-amd can you please confirm, that all trition-rocm pins should be committed to https://github.com/ROCmSoftwarePlatform/triton/tree/triton-mlir-pyt-latest branch?

**Comment by jithunnair-amd** [comment]
> Hi @malfet @kit1980, just updating our triton rocm commit one commit forwards to fix an issue in our latest nightly wheels. There has been some directory changes in triton we needed to update in our wheels in order to find relevant ROCm libs and headers.

Yes, for the nightly wheels, that's the triton branch we are using.

**Pull request closed without merging**
