### PR TITLE
[test][fx] fix incorrect method call in test case

### PR DESCRIPTION
**Pull request by kiszk**
This PR fixes the incorrect method name in function call in the test case

### CODE REVIEW

**Review by jon-chuang — APPROVED** [review]
Thanks, I guess this else branch is not on testing path :thinking:

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
That's disturbing. We should have caught it with static analysis.

**Comment by jon-chuang** [comment]
> That's disturbing. We should have caught it with static analysis.

I think we don't run mypy on tests as it's slow.

**Comment by kit1980** [comment]
> > That's disturbing. We should have caught it with static analysis.
> 
> I think we don't run mypy on tests as it's slow.

I mean flake8 or ruff.

**Comment by jon-chuang** [comment]
> I mean flake8 or ruff.

I don't think these would catch. In my experience only mypy is aware of which functions are defined or not.

**Comment by kit1980** [comment]
> > I mean flake8 or ruff.
> 
> I don't think these would catch. In my experience only mypy is aware of which functions are defined or not.

@jon-chuang 
> flake8 --isolated test/fx/quantization.py
...
test/fx/quantization.py:269:28: F821 undefined name 'copy_recusive'

That flake8 call finds other undefined names btw...

**Pull request closed without merging**
