### PR TITLE
Added ScriptFunction pkl exception

### LINKED ISSUE #61210: Jitted function cannot be pickled
## 🚀 Feature
Support to pickle a jitted function (or at least throw a `TypeError` when using protocol 0 and 1).

## Motivation

Trying to pickle a jitted function either raises `TypeError: cannot pickle 'torch._C.ScriptFunction' object` when `protocol>1` or far worse when using `protocol=0` or `protocol=1` python 3.9.5 dies with:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  instance allocation failed: new instance has no pybind11-registered base types
Aborted (core dumped)
```

Example:
```py
import pickle

import torch

@torch.jit.script
def fun(x: torch.Tensor) -> torch.Tensor:
    return x

pickle.dumps(fun, protocol=0)

```
## Pitch
Implement pickle support for all pickle protocols (or raise a `TypeError` when used with `protocl<2`).

## Additional context
I encountered this when using a jitted function with dask https://github.com/dask/dask/issues/7861

### PR DESCRIPTION
**Pull request by SiddeshSambasivam**
Fixes #61210 

* Added a  `__getstate__` method to `ScriptFunction` to throw an exception

### CODE REVIEW

**Comment by gmagogsfm** [comment]
Hello @SiddeshSambasivam, I think your PR is on the right track. Would you like to complete it? Or do you need any help?

**Comment by SiddeshSambasivam** [comment]
Hey @gmagogsfm! I'm confused about the tests which are failing. What exactly should I change?

**Comment by suo** [comment]
Ah, sorry I missed this! If you are still interested in working on this, do you mind rebasing these changes on the latest master?

**Comment by suo** [comment]
Closed since there's been no response on the PR. Sorry for not getting to it originally, and feel free to reopen if you'd like to pick things back up again.

**Pull request closed without merging**
