### PR TITLE
Remove view on self.target_tensor of dim 1 in TensorDataset (#609)

### PR DESCRIPTION
**Pull request by zhtvk**
Could this be a valid fix for the bug reported here https://github.com/pytorch/pytorch/issues/609?

### CODE REVIEW

**Comment by apaszke** [comment]
Yeah, it is valid. But you've only removed that for labels, while the data will still be viewed incorrectly. Can you please remove that other `if` too?

**Comment by zhtvk** [comment]
I thought about it as well, but wouldn't this cause some issues in
layers that expect the input to be 2D (where the first dim represents
the batch size) when one needs to use 1D samples?

**Comment by apaszke** [comment]
If they expect such input, then you should provide a 2D dataset then.

**Comment by zhtvk** [comment]
I agree, so I've modified accordingly.

**Comment by apaszke** [comment]
Thanks!

**Pull request merged**
