### PR TITLE
Fix KeypointRCNN test

### PR DESCRIPTION
**Pull request by KsenijaS**
Since Argmax is updated in ONNX Runtime we can enable testing for all output, including keypoints_scores.

### CODE REVIEW

**Comment by KsenijaS** [comment]
@neginraoof please review

**Comment by KsenijaS** [comment]
@houseroad please review. Thanks!

**Comment by KsenijaS** [comment]
there is a mismatch between PyTorch and ORT, currently investigating the issue

**Comment by KsenijaS** [comment]
@houseroad bug was fixed on the torchvision side: https://github.com/pytorch/vision/pull/2312, test is passing on my local machine.

**Comment by houseroad** [comment]
Do we need to merge the pr in torchvision first? cc: @fmassa

**Comment by KsenijaS** [comment]
@houseroad pr is already merged in torchvision

**Comment by houseroad** [comment]
So will the test pass if we retrigger it?

**Comment by KsenijaS** [comment]
@houseroad I have already retrigger it this morning, it is still failing on the CI but it passes locally.

**Comment by KsenijaS** [comment]
@houseroad CI is green. Can we merge this?

**Review by houseroad — APPROVED** [review]

**Pull request closed without merging**
