### PR TITLE
Clarify meaning of rate parameter in Gamma distribution

### PR DESCRIPTION
**Pull request by psteinb**

### CODE REVIEW

**Comment by colesbury** [comment]
This change doesn't look correct to me. https://en.wikipedia.org/wiki/Gamma_distribution ⁠described β as the "rate parameter" (i.e., inverse scale parameter)

**Review by fritzo — APPROVED** [review]
LGTM, simply english usage disambiguation

**Comment by fritzo** [comment]
The code change looks fline.  The PR description looks to be in error, however.

**Pull request closed without merging**
