### PR TITLE
fix eig.e bug - it uses DispatchStub and therefore isn't backend agnostic

### PR DESCRIPTION
**Pull request by bdhirsh**
You can see in https://github.com/pytorch/pytorch/blob/60509f8921d090c469d82e6cfe3e6d4d41b6328f/aten/src/ATen/native/BatchLinearAlgebra.cpp#L2917 that `eig.e` is registered as CompositeExplicitAutograd to `eig_out` - which is wrong, since `eig_out` calls into `eig_stub()`, which is registered using DispatchStub.

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #62000 avoid needing to clear cache in gen_backend_stubs tests
* #61295 add basic regex test to detect invalid CompositeExplicitAutograd ops that are implemented with DispatchStub
* **#61133 fix eig.e bug - it uses DispatchStub and therefore isn't backend agnostic**

Differential Revision: [D29526696](https://our.internmc.facebook.com/intern/diff/D29526696)

### CODE REVIEW

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29526696).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29526696).

**Review by ezyang — APPROVED** [review]

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29526696).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29526696).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29526696).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29526696).

**Pull request closed without merging**
