### PR TITLE
[dynamo] Compile subgraphs for both branches of data-dependent control flow when testing on `SymNode`

### LINKED ISSUE #111918: Graph break doesn't result in continuation function when break happens in if-statement expression without inline function call
### 🐛 Describe the bug

After https://github.com/pytorch/pytorch/pull/111919 I noticed that I can now trigger a graph break without Dynamo creating a continuation frame. Modify the test function as such:

```
diff --git a/test/dynamo/test_unspec.py b/test/dynamo/test_unspec.py
index b5c3bfd02ca..02b0d48bd8d 100644
--- a/test/dynamo/test_unspec.py
+++ b/test/dynamo/test_unspec.py
@@ -381,7 +381,7 @@ class UnspecTests(torch._dynamo.test_case.TestCase):
         def fn(x):
             x = x + 1
             y = x.item()
-            if test(y):
+            if y > 2:
                 return x * 2
             else:
                 return x * 3
```

(effectively inlining test.) This causes a continuation frame to no longer be created:

image

If you move the graph break to an inner function call (as the test is written in the PR), this solves the problem. So it's probably some minor issue. I took a quick look though and it wasn't obvious what the issue was.

### Versions

main

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

### PR DESCRIPTION
**Pull request by jon-chuang**
Fixes https://github.com/pytorch/pytorch/issues/111918

We did not do this when jumping on `SymNodeVariable`s before.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by jon-chuang** [comment]
Should expect many new test failures involving count_frames or num_graphs, since new branches are compiled.

**Review by jansel — CHANGES_REQUESTED** [review]
Tests are failing

**Comment by ezyang** [comment]
The PR looks plausible though

**Comment by jon-chuang** [comment]
@ezyang @jansel fixed the tests to reflect compiling both branches, but this PR still doesn't seem to work when the SymInt is shipped off to inductor. In particular, it triggers the following error:

```
AssertionError: cannot extract sympy expressions from s0 >= 2 <class 'sympy.core.relational.GreaterThan'>
AssertionError: cannot extract sympy expressions from 4*s0 > 4000 <class 'sympy.core.relational.StrictGreaterThan'>
```

With stack trace:
```
2023-11-07T16:14:03.6568004Z You can suppress this exception and fall back to eager by setting:
2023-11-07T16:14:03.6569078Z     import torch._dynamo
2023-11-07T16:14:03.6569811Z     torch._dynamo.config.suppress_errors = True
2023-11-07T16:14:03.6570745Z Traceback (most recent call last):
2023-11-07T16:14:03.6572091Z   File "/var/lib/jenkins/workspace/benchmarks/dynamo/common.py", line 2448, in check_accuracy
2023-11-07T16:14:03.6573759Z     new_result = optimized_model_iter_fn(model_copy, example_inputs)
2023-11-07T16:14:03.6575823Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 410, in _fn
2023-11-07T16:14:03.6577273Z     return fn(*args, **kwargs)
2023-11-07T16:14:03.6578681Z   File "/var/lib/jenkins/workspace/benchmarks/dynamo/common.py", line 2188, in run_n_iterations
2023-11-07T16:14:03.6580230Z     self.model_iter_fn(mod, inputs, collect_outputs=False)
2023-11-07T16:14:03.6581419Z   File "benchmarks/dynamo/torchbench.py", line 521, in forward_pass
2023-11-07T16:14:03.6582451Z     return mod(*inputs)
2023-11-07T16:14:03.6584113Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
2023-11-07T16:14:03.6585796Z     return self._call_impl(*args, **kwargs)
2023-11-07T16:14:03.6587588Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1519, in _call_impl
2023-11-07T16:14:03.6589162Z     return forward_call(*args, **kwargs)
2023-11-07T16:14:03.6591182Z   File "/var/lib/jenkins/.local/lib/python3.8/site-packages/torchvision/models/detection/generalized_rcnn.py", line 104, in forward
2023-11-07T16:14:03.6593443Z     proposals, proposal_losses = self.rpn(images, features, targets)
2023-11-07T16:14:03.6595850Z   File "/var/lib/jenkins/.local/lib/python3.8/site-packages/torchvision/models/detection/generalized_rcnn.py", line 105, in resume_in_forward
2023-11-07T16:14:03.6598337Z     detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets)
2023-11-07T16:14:03.6600747Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
2023-11-07T16:14:03.6602402Z     return self._call_impl(*args, **kwargs)
2023-11-07T16:14:03.6604123Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1519, in _call_impl
2023-11-07T16:14:03.6605703Z     return forward_call(*args, **kwargs)
2023-11-07T16:14:03.6607566Z   File "/var/lib/jenkins/.local/lib/python3.8/site-packages/torchvision/models/detection/roi_heads.py", line 761, in forward
2023-11-07T16:14:03.6609494Z     box_features = self.box_roi_pool(features, proposals, image_shapes)
2023-11-07T16:14:03.6611738Z   File "/var/lib/jenkins/.local/lib/python3.8/site-packages/torchvision/models/detection/roi_heads.py", line 775, in resume_in_forward
2023-11-07T16:14:03.6614123Z     boxes, scores, labels = self.postprocess_detections(class_logits, box_regression, proposals, image_shapes)
2023-11-07T16:14:03.6616874Z   File "/var/lib/jenkins/.local/lib/python3.8/site-packages/torchvision/models/detection/roi_heads.py", line 716, in postprocess_detections
2023-11-07T16:14:03.6618915Z     keep = box_ops.batched_nms(boxes, scores, labels, self.nms_thresh)
2023-11-07T16:14:03.6620843Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 571, in catch_errors
2023-11-07T16:14:03.6622477Z     return callback(frame, cache_entry, hooks, frame_state)
2023-11-07T16:14:03.6624607Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 701, in _convert_frame
2023-11-07T16:14:03.6626466Z     result = inner_convert(frame, cache_entry, hooks, frame_state)
2023-11-07T16:14:03.6628481Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 408, in _convert_frame_assert
2023-11-07T16:14:03.6629999Z     return _compile(
2023-11-07T16:14:03.6631420Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 625, in _compile
2023-11-07T16:14:03.6633220Z     guarded_code = compile_inner(code, one_graph, hooks, transform)
2023-11-07T16:14:03.6635304Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 221, in time_wrapper
2023-11-07T16:14:03.6636739Z     r = func(*args, **kwargs)
2023-11-07T16:14:03.6638567Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 542, in compile_inner
2023-11-07T16:14:03.6640393Z     out_code = transform_code_object(code, transform)
2023-11-07T16:14:03.6642686Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
2023-11-07T16:14:03.6644677Z     transformations(instructions, code_options)
2023-11-07T16:14:03.6646436Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 149, in _fn
2023-11-07T16:14:03.6648040Z     return fn(*args, **kwargs)
2023-11-07T16:14:03.6649478Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 507, in transform
2023-11-07T16:14:03.6650326Z     tracer.run()
2023-11-07T16:14:03.6651252Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2193, in run
2023-11-07T16:14:03.6652101Z     super().run()
2023-11-07T16:14:03.6652927Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 820, in run
2023-11-07T16:14:03.6653773Z     and self.step()
2023-11-07T16:14:03.6654708Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 783, in step
2023-11-07T16:14:03.6655569Z     getattr(self, inst.opname)(inst)
2023-11-07T16:14:03.6656500Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 388, in inner
2023-11-07T16:14:03.6657372Z     self.output.compile_subgraph(
2023-11-07T16:14:03.6658359Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 919, in compile_subgraph
2023-11-07T16:14:03.6659417Z     self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
2023-11-07T16:14:03.6660215Z   File "/opt/conda/envs/py_3.8/lib/python3.8/contextlib.py", line 75, in inner
2023-11-07T16:14:03.6660859Z     return func(*args, **kwds)
2023-11-07T16:14:03.6661884Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 1041, in compile_and_call_fx_graph
2023-11-07T16:14:03.6662883Z     compiled_fn = self.call_user_compiler(gm)
2023-11-07T16:14:03.6752053Z AssertionError: cannot extract sympy expressions from 4*s0 > 4000 <class 'sympy.core.relational.StrictGreaterThan'>
```

Is this PR still viable? How can I get inductor to handle SymInts?

**Comment by jon-chuang** [comment]
Actually, I realize that this is probably due to the SymNodeVar being propagated as a local to the downstream graphs. If we get rid of that we should be fine.

**Comment by jon-chuang** [comment]
Unfortunately, to fix this properly, we need to reconstruct the `SymNodeVariable` in the eager epilogue to the compiled function. But I'm not sure we know how to do this right now.

To be able to do so, we need to be able to trace the source of the `SymNodeVariable`'s inputs, then pass those as the inputs to the SymNodeVariable's final expression.

**Comment by jon-chuang** [comment]
I'm gonna close this for now. For the specific case of graph breaking while in a `generic_jump`, I have a feeling we can handle it properly.

I don't know the old reason for why inlining would still allow tracing the rest of the function, but it seems to have something to do with the checkpoint being empty. Presumably, inlining would make the checkpoint empty, and thus force a retracing of the function.

Generally, it seems quite non-deterministic when we trace/don't retrace a function.

**Comment by jon-chuang** [comment]
> To be able to do so, we need to be able to trace the source of the SymNodeVariable's inputs, then pass those as the inputs to the SymNodeVariable's final expression.

Actually, doing this doesn't seem particularly hard. We can just store references to each of the symnodevars dependencies in the VT, and reconstruct everything.

**Pull request closed without merging**
