### PR TITLE
Use cuda 12.4 pytorch_extra_install_requirements as default

### PR DESCRIPTION
**Pull request by atalman**
Since cuda 12.4 binaries are default binaries on pypi now. The pytorch_extra_install_requirements need to use 12.4.
This would need to be cherry-picked to release 2.5 branch to avoid injecting these versions into metadata during pypi promotion.

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
The fact that this changes the AMD and macos binary sounds wrong!

**Comment by atalman** [comment]
Hi @albanD this is related to poetry issue where we want to have same metadata for all wheels. Hence this is changing windows, macos, amd wheels to have same metadata as the linux wheels we publish to pypi.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
