### PR TITLE
Fix ConvolutionBinaryInplace using target node

### LINKED ISSUE #113440: [inductor][cpu] freezing caused a lot of CV model crashed
### 🐛 Describe the bug

Accord to [2023-11-08 nightly release test](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1804927599), there are a lot of CV models crashed by `--freezing`. 

For example, RN50 can pass without freezing but crashed on freezing enabled with below info:

```
cpu  eval  resnet50                           
ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2604, in warmup
    fn(model, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 409, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 570, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 670, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 377, in _convert_frame_assert
    return _compile(
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 594, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 222, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 511, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 150, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 476, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2120, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 815, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 778, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2235, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 893, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1038, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 222, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1109, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1090, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/backends/inductor.py", line 9, in inductor
    return compile_fx(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1226, in compile_fx
    return aot_autograd(
  File "/workspace/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 4837, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 222, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 4376, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2724, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2911, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2073, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 975, in fw_compiler_freezing
    optimized_function = inner_compile(
  File "/workspace/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_inductor/debug.py", line 303, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 390, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 600, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 222, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 444, in run
    return super().run(*args)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 754, in run_node
    result = super().run_node(n)
  File "/workspace/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 584, in call_function
    return target(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/fx_passes/mkldnn_fusion.py", line 234, in fn
    return L[computation_op](*computation_args)
  File "/workspace/pytorch/torch/_inductor/lowering.py", line 288, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/lowering.py", line 1266, in convolution_unary
    ir.ConvolutionUnary.create(
  File "/workspace/pytorch/torch/_inductor/ir.py", line 4897, in create
    (inputs, constant_args, kernel_layout, _) = _prepare_convolution_fusion_create(
  File "/workspace/pytorch/torch/_inductor/ir.py", line 4717, in _prepare_convolution_fusion_create
    assert 0 < len(padding) <= dims
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: 

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
    
```

### Versions

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<p style='margin-top:0pt;margin-bottom:12pt;font-family:-apple-system;
font-size:10.5pt;color:#1F2328'><span style='background:white'>SW information:</span></p>

<div style='direction:ltr'>

SW | Nightly commit | Main commit
-- | -- | --
Pytorch | 4060c20 | aa376e3
Torchbench | / | 7617d3f5
torchaudio | 475b6ae | ede4309
torchtext | 142d029 | 45e4b8c
torchvision | 37ceb68 | 15c166a
torchdata | eb9bf61 | d76d92c
dynamo_benchmarks | nightly | /

</div>

</body>

</html>

Repro:

[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
```shell
bash inductor_single_run.sh multiple inference performance torchbench resnet50 float32 first static default
```
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/611a7457cad52d1aa81291f772a49dd280c17ba1

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### PR DESCRIPTION
**Pull request by oulgen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #114436
* #114169

This IR node mutates in place, it needs to use the argument not the
target.

Fixes #113440

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by oulgen** [comment]
There's a bug in convolution_unary where it uses the target of ConvolutionBinaryInplace even though it needs to use the input[1]. I am having hard time finding where this happens so partially reverting this part until I can find it.

cc: @Chillee

**Review by leslie-fang-intel — COMMENTED** [review]
Thanks for the fix. The [UT ](https://gist.github.com/leslie-fang-intel/cdcfbb2f9a01ec5a820f2818ad5a77ae )passes after this fix, but the model still failure. For example: `python benchmarks/dynamo/torchbench.py --performance --float32 -dcpu -n50 --no-skip --dashboard --only resnet50 --inference --freezing --timeout 9000 --backend=inductor --output=test.csv`
- error message: `    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/leslie/inductor/pytorch/torch/_inductor/graph.py", line 589, in call_function
    return target(*args, **kwargs)
  File "/home/leslie/inductor/pytorch/torch/_inductor/fx_passes/mkldnn_fusion.py", line 397, in fn
    assert isinstance(other, ir.TensorBox)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError:
`
- for which I think due to we need the `TensorBox` instead of `ExternKernelAlloc`. Instead of current fix, how about we made some change here https://github.com/pytorch/pytorch/blob/7daeb6509fe021462063d98c544339fc469075df/torch/_inductor/ir.py#L5158 to return `packed.inputs[0]`, since the return value will be wrapped into `TensorBox`.

**Comment by leslie-fang-intel** [comment]
cc @chuanqi129, since more than 1 models failed among fp32/bf16 testing, please help to check all the failures fixed by this PR.

**Comment by oulgen** [comment]
@leslie-fang-intel updated the PR, can you check whether this fixes the other issue? If not, please share the full assertion failure

**Comment by leslie-fang-intel** [comment]
> @leslie-fang-intel updated the PR, can you check whether this fixes the other issue? If not, please share the full assertion failure

cc @chuanqi129, please help to confirm

**Comment by leslie-fang-intel** [comment]
> @leslie-fang-intel updated the PR, can you check whether this fixes the other issue? If not, please share the full assertion failure

Thanks @oulgen, emmm.... I think we should not use `inputs[1]`. Per my understanding, `inputs[1]` and `packed.inputs[0]` might be different type. Since `inputs[1]` might be a `TensorBox` and unwrap into the `Buffer` here https://github.com/pytorch/pytorch/blob/7daeb6509fe021462063d98c544339fc469075df/torch/_inductor/ir.py#L3748

**Comment by oulgen** [comment]
@leslie-fang-intel I don't quite follow what you mean. The op mutates input[1], and previously via MutationLayout it was returning input[1]. So, returning input[1] is the correct result.

**Comment by leslie-fang-intel** [comment]
> @leslie-fang-intel I don't quite follow what you mean. The op mutates input[1], and previously via MutationLayout it was returning input[1]. So, returning input[1] is the correct result.

I think `input[1]` equals to `TensorBox(StorageBox((packed.inputs[0])))` , and we should return the buffer object instead of the Tensorbox (same as previously). Otherwise the model level testing (and also this [test case](https://gist.github.com/leslie-fang-intel/9f92a553579df942b626e7f21066a59a)) will still fail.

**Comment by oulgen** [comment]
@leslie-fang-intel Thanks! I missed the buffer wrapping when i moved the code around. Updated the code.

**Review by jansel — APPROVED** [review]
Please double check ConvolutionBinaryInplace set get_mutation_names() properly.

**Comment by leslie-fang-intel** [comment]
@chuanqi129 is working on verifying this fix among the failures we saw in fp32/bf16 static/dynamic shape tests. Expect he wiill help to post the result in early next week

**Comment by oulgen** [comment]
Actually @jansel is correct, since init reorders the arguments, the `get_mutation_names` is incorrect. I will put a follow up PR to fix this. In general, reordering arguments will lead to bugs like this

**Comment by oulgen** [comment]
https://github.com/pytorch/pytorch/pull/114501 fixes the mutation tracking bug

**Comment by aakhundov** [comment]
> I tried to cancel the merge but couldn't figure out how to do it.

@eellison once mentioned that closing and reopening the PR should stop the merge. Although I never tried myself.

**Pull request closed without merging**
