### PR TITLE
Revert "Revert "Implement sym_sizes to create proper IR for sym ints representing tensor sizes (#76836)""

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #77740
* #77739
* #77681
* #77682
* #77499
* __->__ #77719

This reverts commit c35bd8d423ca53408c3aa39c2280167f3a22cea0.

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
Stamp.

**Review by malfet — APPROVED** [review]
LGTM, but probably you'll have to reland anyway

**Comment by suo** [comment]
@zengk95 the comment here suggests an incorrect command, can you take a look?

**Comment by zengk95** [comment]
> [@pytorchmergebot](/pytorchmergebot) [pytorchmergebot](/pytorchmergebot) added the [ Reverted ](/pytorch/pytorch/labels/Reverted) label [10 hours ago](#event-6629200145)

So I think the extra period at the end of @mruberry comment just tripped it up and made the bot think the classification was `"ghfirst". `. 
I can add some additional messaging on if an invalid classification is provided.

**Pull request closed without merging**
