### PR TITLE
Manually resolve download.pytorch.org to IPv4

### PR DESCRIPTION
**Pull request by huydhn**
This is an attempt to address https://github.com/pytorch/pytorch/issues/100400 by using only IPV4 when accessing the domain.

I kind of want to ignore AAAA records from DNS instead, but couldn't find an easy way to do so.  https://www.cloudflare.com/learning/dns/dns-records/dns-aaaa-record doc mentions this

```
Like A records, AAAA records enable client devices to learn the IP address for a domain name. The client device can then connect with and load the website.

AAAA records are only used when a domain has an IPv6 address in addition to an IPv4 address, and when the client device in question is configured to use IPv6
```

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
This would kill the runner, wouldn't it? Perhaps a better way to disable those would be inside the container?

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Not sure how it ever worked before (perhaps nodes didn't even have a v6 address or only link-local connection existed for it, but somehow sometimes nodes pick ipv6 address)

**Review by malfet — CHANGES_REQUESTED** [review]
Alas, this does not help, just changes the behavior from `-ENETUNREACH` to `-EADDRUNAVAIL`:
```
$ cat test.py 
import urllib.request
try:
    for i in range(400):
       x=urllib.request.urlopen('https://download.pytorch.org/models/squeezenet1_1-b8a52dc0.pth')
except Exception as e:
    e1 = e
    print(e1)
    import pdb
    pdb.set_trace()
(base) [ec2-user@ip-10-0-2-166 ~]$ sysctl -a 2>/dev/null | grep disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.docker0.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.veth241ef0a.disable_ipv6 = 1
(base) [ec2-user@ip-10-0-2-166 ~]$ ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 10.0.2.166  netmask 255.255.255.0  broadcast 10.0.2.255
        ether 12:c3:85:14:b4:41  txqueuelen 1000  (Ethernet)
        RX packets 95166128  bytes 136277685748 (126.9 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10867565  bytes 794388420 (757.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

(base) [ec2-user@ip-10-0-2-166 ~]$ python3 test.py 
<urlopen error [Errno 99] Cannot assign requested address>
--Return--
> /home/ec2-user/test.py(9)<module>()->None
-> pdb.set_trace()
(Pdb) i
55
```

**Review by malfet — APPROVED** [review]
Preemptively stamping to, but I guess final script should just tweak `resolv.conf` (perhaps inside docker) to disable `AAAA` names lookup

**Comment by huydhn** [comment]
cc @malfet After some testings, I end up manually resolve `download.pytorch.org` to IPv4 like what we discuss as I don't think turning off IPv6 / choosing A record over AAAA record is a legit option in https://man7.org/linux/man-pages/man5/resolv.conf.5.html.  Ironically, there is an `options inet6` to prefer IPv6 by default

**Comment by malfet** [comment]
It still fails, as the change needs to happen inside the docker image, not outside of it

**Pull request closed without merging**
