### PR TITLE
Fix the improper use of windows-native slashes

### LINKED ISSUE #12510: [feature request] fix Windows cmake scripts to deal with \backlashes in paths
## Issue description

Getting a bunch of Invalid escape sequence \N while compiling from source.
Coming from paths with unescaped backslashes in them.
Trying to resolve by myself in the meantime but its a real pain

## Code example

Invalid escape sequence \N                                                                                                                                                                                                                                                                                                                                                                                    Policy CMP0010 is not set: Bad variable reference syntax is an error.  Run                                                                                                                             "cmake --help-policy CMP0010" for policy details.  Use the cmake_policy                                                                                                                                command to set the policy and suppress this warning.                                                                                                                                                 This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                                                                                                                                                                                                                                                                         CMake Warning (dev) at caffe2_gpu_generated_THCStorageCopy.cu.obj.Release.cmake:178 (execute_process):                                                                                                   Syntax error in cmake code at                                                                                                                                                                                                                                                                                                                                                                                   C:/Users/user/pytorchrc1/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCStorageCopy.cu.obj.Release.cmake:178                                                                                                                                                                                                                                                      when parsing string                                                                                                                                                                                                                                                                                                                                                                                             C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/bin/nvcc.exe;-M;-D__CUDACC__;C:/Users/user/pytorchrc1/pytorch/aten/src/THC/THCStorageCopy.cu;-o;C:/Users/user/pytorchrc1/pytorch/bui   ld/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCStorageCopy.cu.obj.NVCC-depend;-ccbin;C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.   25503/bin/Hostx64/x64;-m64;-Dcaffe2_gpu_EXPORTS;-DCAFFE2_BUILD_MAIN_LIB;-DNOMINMAX;-D_CRT_SECURE_NO_DEPRECATE=1;-DUSE_MSC_ATOMICS=1;-DTH_BLAS_MKL;-D_OPENMP_NOFORCE_MANIFEST;-Xcompiler;,"/wd4267","   /wd4251","/wd4522","/wd4522","/wd4838","/wd4305","/wd4244","/wd4190","/wd4101","/wd4996","/wd4275","/EHa","-DONNX_NAMESPACE=onnx_torch","-openmp","/MP","/bigobj","-DHAVE_AVX_CPU_DEFINITION","-DHAV   E_AVX2_CPU_DEFINITION","/MD","/O2","/Ob2","/MP","/bigobj";-DONNX_NAMESPACE=onnx_torch;-gencode;arch=compute_30,code=sm_30;-Xcudafe;--diag_suppress=cc_clobber_ignored;-Xcudafe;--diag_suppress=integ   er_sign_change;-Xcudafe;--diag_suppress=useless_using_declaration;-Xcudafe;--diag_suppress=set_but_not_used;-Xcompiler;-MD;--expt-relaxed-constexpr;--expt-extended-lambda;-Xcompiler;/wd4819;-Xcomp   iler;/wd4503;-Xcompiler;/wd4190;-Xcompiler;/wd4244;-Xcompiler;/wd4251;-Xcompiler;/wd4275;-Xcompiler;/wd4522;-Wno-deprecated-gpu-targets;--expt-extended-lambda;-gencode;arch=compute_30,code=sm_30;-   DCUDA_HAS_FP16=1;-D__CUDA_NO_HALF_OPERATORS__;-D__CUDA_NO_HALF_CONVERSIONS__;-D__CUDA_NO_HALF2_OPERATORS__;-DNVCC;-IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include;-IC:/Users/yacin   e/pytorchrc1/pytorch/aten/src;-IC:/Users/user/pytorchrc1/pytorch/build;-IC:/Users/user/pytorchrc1/pytorch;-IC:/Users/user/pytorchrc1/pytorch/third_party/protobuf/src;-IC:/Program Files (x86)   /IntelSWTools/compilers_and_libraries/windows/mkl/include;-IC:/Users/user/pytorchrc1/pytorch/cmake/../third_party/eigen;-IC:/Users/user/pytorchrc1/pytorch/cmake/../third_party/pybind11/include   ;-IC:/Users/user/pytorchrc1/pytorch/cmake/../third_party/cub;-IC:/Users/user/pytorchrc1/pytorch/third_party/onnx;-IC:/Users/user/pytorchrc1/pytorch/build/third_party/onnx;-IC:/Users/user/p   ytorchrc1/pytorch/build/caffe2/aten/src/TH;-IC:/Users/user/pytorchrc1/pytorch/aten/src/TH;-IC:/Users/user/pytorchrc1/pytorch/aten/src/THC;-IC:/Users/user/pytorchrc1/pytorch/build/caffe2/aten   /src/THC;-IC:/Users/user/pytorchrc1/pytorch/aten/src/THCUNN;-IC:/Users/user/pytorchrc1/pytorch/aten/src/ATen/cuda;-IC:/Users/user/pytorchrc1/pytorch/build/caffe2/aten/src;-IC:/Users/user/p   ytorchrc1/pytorch/build/aten/src;-IC:/Users/user/pytorchrc1/pytorch/aten/src/THNN;-IC:/Users/user/pytorchrc1/pytorch/aten/../third_party/catch/single_include;-IC:/Users/user/pytorchrc1/pytor   ch/build/caffe2/aten/src/ATen;-IC:/Users/user/pytorchrc1/pytorch/aten/src/ATen/..;-IC:\NVIDIA\CUDA\9.0\cudnn-v7.3\include                                                                                                                                                                                                                                                                                     Invalid escape sequence \N                                                                                                                                                                                                                                                                                                                                                                                    Policy CMP0010 is not set: Bad variable reference syntax is an error.  Run                                                                                                                             "cmake --help-policy CMP0010" for policy details.  Use the cmake_policy                                                                                                                                command to set the policy and suppress this warning.                                                                                                                                                 Call Stack (most recent call first):                                                                                                                                                                     caffe2_gpu_generated_THCStorageCopy.cu.obj.Release.cmake:203 (cuda_execute_process)                                                                                                                  This warning is for project developers.  Use -Wno-dev to suppress it.                                                  

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): python setup.py build -f
- OS: Microsoft Windows 10 Pro x64 Version	10.0.17134 Build 17134
- PyTorch version: 
- Python version: 3.6.5
- CUDA/cuDNN version: 9.0patch4/7.3
- GPU models and configuration: Nvidia Quadro K2100M
- GCC version (if compiling from source): N/A
- CMake version: the one from VS as described in compilation instruction
- Versions of any other relevant libraries:

### PR DESCRIPTION
**Pull request by peterjc123**
Trying to fix #12510.

### CODE REVIEW

**Comment by peterjc123** [comment]
@soumith @ezyang Could you please take a look here?

**Comment by ezyang** [comment]
This is a bit black magicky. Would you mind writing a Note explaining in what situations we have to undo Windows native backslashes? Judging from the patch, it seems something like, everything we pass to cmake has to use non-native slashes?

**Comment by peterjc123** [comment]
@ezyang Yes, the backslashes are very complicated to use in cmake. It has to be `\\\\` but for forward slashes, it will just be `/`. As for the note, where should I put it?

**Comment by ezyang** [comment]
Maybe the bat file? If you name it `Note [Backslash munging on Windows]` then you can cross-reference it from relevant sites.

BTW, given the comment you gave above, wouldn't another acceptable way to fix the problem, be simply to "escape" strings before we pass them to cmake? That actually would make more sense to me, and be more uniform than trying to squish every path site from Python (I'm sure we've missed some.)

**Comment by peterjc123** [comment]
@ezyang Good idea. I'll try this one later.

**Comment by peterjc123** [comment]
@ezyang How about this?

**Comment by ezyang** [comment]
Coolness. But now you are double munging--we don't need the escaping in the Python files anymore, do we?

**Comment by peterjc123** [comment]
@ezyang Done!

**Comment by peterjc123** [comment]
@ezyang Done!

**Review by ezyang — APPROVED** [review]

**Comment by peterjc123** [comment]
@ezyang @soumith Can we merge this, please?

**Review by soumith — APPROVED** [review]

**Pull request closed without merging**
