### PR TITLE
Enable more readability-redundant checks

### PR DESCRIPTION
**Pull request by cyyever**
They are helpful to simplifying code.

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by Skylion007** [comment]
Shouldn't most of these ctor and dtor become default now?

**Pull request closed without merging**
