### PR TITLE
[ez][docs] Fixed render of `tensors` in `backward`

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #118223
* #118198
* #118188
* #118136
* #118118
* #118017
* #118004
* #117975
* #117973
* #117955
* #117950
* #117881
* #117877
* #117867
* #117861
* #117856
* #117852
* #117817
* #117814
* #117776
* #117984
* #118186
* __->__ #117994

Before:
Screenshot 2024-01-22 at 2 03 49 PM

After:
Screenshot 2024-01-23 at 7 13 40 PM

### CODE REVIEW

**Review by soulitzer — APPROVED** [review]
Thanks!

**Comment by awgu** [comment]
Okay, I think I finally figured out the right way to do it:
```
:attr:`tensors`
```
I will check the built docs before landing.

**Comment by awgu** [comment]
The docs build does not seem to have captured the changes:
https://docs-preview.pytorch.org/pytorch/pytorch/117994/generated/torch.autograd.backward.html#torch.autograd.backward

The PR does not have `::` anymore, so I am not sure why it renders like that:
Screenshot 2024-01-22 at 5 52 38 PM

**Comment by soulitzer** [comment]
Hmmm it looks fine to me, maybe check again now?

image

**Comment by awgu** [comment]
@soulitzer Oh nice!

Where did you go to get that?

When I go to https://docs-preview.pytorch.org/pytorch/pytorch/117994/generated/torch.autograd.backward.html#torch.autograd.backward, I still see the same issue for some reason 😢 .

**Comment by soulitzer** [comment]
Oh I literally just clicked your link, maybe its cached for you?

**Comment by awgu** [comment]
@soulitzer Ah! It looks like it was cached. Thanks!

**Review by weifengpy — APPROVED** [review]

**Pull request closed without merging**
