### PR TITLE
Enable quantization dispatch for backend QuantizedPrivateUse1

### PR DESCRIPTION
**Pull request by fmo-mt**
Support QuantizedPrivatesUse1 dispatch, which enable customize quantization backend.

As mentioned in #103663 , pytorch now supports new backend "QuantizedPrivateUse1", but to enable pytorch to dispatch and implement the quantization functions, these changes are needed.

### CODE REVIEW

**Comment by fmo-mt** [comment]
cc @jerryzh168

**Comment by kimishpatel** [comment]
What is "QuantizedPrivateUse1" used for?

**Comment by fmo-mt** [comment]
> 

It enables pytorch to act quantization on customize backend, just as same as `PrivateUse1`, which is an old attribute of pytorch, but some functions, like `quantize_per_tensor` or `quantize_per_channel` needs to be implemented when receiving tensor of customize backend.

**Comment by fmo-mt** [comment]
Does this PR can be progressed?

**Pull request closed without merging**
