### PR TITLE
Enhance DispatchStub to be thread safe from a TSAN point of view.

### PR DESCRIPTION
**Pull request by pritamdamania87**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#32148 Enhance DispatchStub to be thread safe from a TSAN point of view.**

TSAN would complain about multiple threads reading and writing to the
`cpu_dispatch_ptr` without any sort of synchronization. Although, this is a
valid issue from a TSAN point of view, there wasn't a correctness issue since
both threads would compute the same value.

In order to fix this, I've used std::atomic for cpu_dispatch_ptr with relaxed
ordering guarantees.

Differential Revision: [D19386082](https://our.internmc.facebook.com/intern/diff/D19386082/)

### CODE REVIEW

**Comment by ezyang** [comment]
Can you show that the generated assembly is the same before and after? If we have to use a LOCKed instruction that's really bad for multithreaded performance. O/w the PR looks good.

**Comment by pritamdamania87** [comment]
> Can you show that the generated assembly is the same before and after? If we have to use a LOCKed instruction that's really bad for multithreaded performance. O/w the PR looks good.

Isn't it better to have some sort of benchmark or update AI PEP with such a test to ensure a change like this doesn't affect performance? I'm not sure whether looking at generated assembly gives enough signal here. For example the assembly might be different, but there might not be any significant perf impact.

**Comment by ezyang** [comment]
> For example the assembly might be different, but there might not be any significant perf impact.

Sure, but the assembly test is easy to do and if it *is* the same, you know there is no perf impact. You can dump assembly a function using

```
gdb -batch -ex 'file torch/lib/libtorch_cpu.so' -ex 'disassemble /m $NAME_OF_SYMBOL'
```

If you feel that you *must* run a benchmark, the multithreaded sparse NN benchmark is best, as it is the most recent benchmark we've used to catch regressions related to atomics. Instructions at https://fb.quip.com/VyuRAXTn5VbI

**Comment by pritamdamania87** [comment]
Looks like the generated assembly is different. With this PR:
```
Dump of assembler code for function at::native::DispatchStub<void (*)(at::TensorIterator&, c10::Scalar), at::native::add_stub>::operator()<at::TensorIterator&, int>(c10::DeviceType, at::TensorIterator&, int&&):
67        rT operator()(DeviceType device_type, ArgTypes&&... args) {
   0x00000000019709d2 <+0>:     push   %rbp
   0x00000000019709d3 <+1>:     mov    %rsp,%rbp
   0x00000000019709d6 <+4>:     push   %r12
   0x00000000019709d8 <+6>:     push   %rbx
   0x00000000019709d9 <+7>:     sub    $0x130,%rsp
   0x00000000019709e0 <+14>:    mov    %rdi,-0x128(%rbp)
   0x00000000019709e7 <+21>:    mov    %esi,%eax
   0x00000000019709e9 <+23>:    mov    %rdx,-0x138(%rbp)
   0x00000000019709f0 <+30>:    mov    %rcx,-0x140(%rbp)
   0x00000000019709f7 <+37>:    mov    %ax,-0x12c(%rbp)

68          if (device_type == DeviceType::CPU) {
   0x00000000019709fe <+44>:    movzwl -0x12c(%rbp),%eax
   0x0000000001970a05 <+51>:    test   %ax,%ax
   0x0000000001970a08 <+54>:    jne    0x1970ace <at::native::DispatchStub<void (*)(at::TensorIterator&, c10::Scalar), at::native::add_stub>::operator()<at::TensorIterator&, int>(c10::DeviceType, at::TensorIterator&, int&&)+252>

69            // Use memory_order_relaxed here since even if two threads race,
70            // they will still compute the same value for cpu_dispatch_ptr.
71            if (!cpu_dispatch_ptr.load(std::memory_order_relaxed)) {
   0x0000000001970a0e <+60>:    mov    -0x128(%rbp),%rax
   0x0000000001970a15 <+67>:    mov    $0x0,%esi
   0x0000000001970a1a <+72>:    mov    %rax,%rdi
   0x0000000001970a1d <+75>:    callq  0x1478eb0 <_ZNKSt6atomicIPFvRN2at14TensorIteratorEN3c106ScalarEEE4loadESt12memory_order@plt>
   0x0000000001970a22 <+80>:    test   %rax,%rax
   0x0000000001970a25 <+83>:    sete   %al
   0x0000000001970a28 <+86>:    test   %al,%al
   0x0000000001970a2a <+88>:    je     0x1970a67 <at::native::DispatchStub<void (*)(at::TensorIterator&, c10::Scalar), at::native::add_stub>::operator()<at::TensorIterator&, int>(c10::DeviceType, at::TensorIterator&, int&&)+149>

72              FnPtr tmp_cpu_dispatch_ptr = nullptr;
   0x0000000001970a2c <+90>:    movq   $0x0,-0x118(%rbp)

73              cpu_dispatch_ptr.compare_exchange_weak(
   0x0000000001970a37 <+101>:   mov    -0x128(%rbp),%rbx
   0x0000000001970a3e <+108>:   mov    -0x128(%rbp),%rax
   0x0000000001970a45 <+115>:   mov    %rax,%rdi
   0x0000000001970a48 <+118>:   callq  0x16840f8 <at::native::DispatchStub<void (*)(at::TensorIterator&, c10::Scalar), at::native::add_stub>::choose_cpu_impl()>
   0x0000000001970a4d <+123>:   mov    %rax,%rdx
   0x0000000001970a50 <+126>:   lea    -0x118(%rbp),%rax
   0x0000000001970a57 <+133>:   mov    $0x0,%ecx
   0x0000000001970a5c <+138>:   mov    %rax,%rsi
   0x0000000001970a5f <+141>:   mov    %rbx,%rdi
   0x0000000001970a62 <+144>:   callq  0x1418ca0 <_ZNSt6atomicIPFvRN2at14TensorIteratorEN3c106ScalarEEE21compare_exchange_weakERS6_S6_St12memory_order@plt>

74                  tmp_cpu_dispatch_ptr, choose_cpu_impl(), std::memory_order_relaxed);
75            }
76            return (*cpu_dispatch_ptr)(std::forward<ArgTypes>(args)...);
```

Without this PR:
```
Dump of assembler code for function at::native::DispatchStub<void (*)(at::TensorIterator&, c10::Scalar), at::native::add_stub>::operator()<at::TensorIterator&, int>(c10::DeviceType, at::TensorIterator&, int&&):
67        rT operator()(DeviceType device_type, ArgTypes&&... args) {
   0x0000000001963a44 <+0>:     push   %rbp
   0x0000000001963a45 <+1>:     mov    %rsp,%rbp
   0x0000000001963a48 <+4>:     push   %r12
   0x0000000001963a4a <+6>:     push   %rbx
   0x0000000001963a4b <+7>:     sub    $0x120,%rsp
   0x0000000001963a52 <+14>:    mov    %rdi,-0x118(%rbp)
   0x0000000001963a59 <+21>:    mov    %esi,%eax
   0x0000000001963a5b <+23>:    mov    %rdx,-0x128(%rbp)
   0x0000000001963a62 <+30>:    mov    %rcx,-0x130(%rbp)
   0x0000000001963a69 <+37>:    mov    %ax,-0x11c(%rbp)

68          if (device_type == DeviceType::CPU) {
   0x0000000001963a70 <+44>:    movzwl -0x11c(%rbp),%eax
   0x0000000001963a77 <+51>:    test   %ax,%ax
   0x0000000001963a7a <+54>:    jne    0x1963b0a <at::native::DispatchStub<void (*)(at::TensorIterator&, c10::Scalar), at::native::add_stub>::operator()<at::TensorIterator&, int>(c10::DeviceType, at::TensorIterator&, int&&)+198>

69            if (!cpu_dispatch_ptr) {
   0x0000000001963a80 <+60>:    mov    -0x118(%rbp),%rax
   0x0000000001963a87 <+67>:    mov    (%rax),%rax
   0x0000000001963a8a <+70>:    test   %rax,%rax
   0x0000000001963a8d <+73>:    jne    0x1963aab <at::native::DispatchStub<void (*)(at::TensorIterator&, c10::Scalar), at::native::add_stub>::operator()<at::TensorIterator&, int>(c10::DeviceType, at::TensorIterator&, int&&)+103>

70              cpu_dispatch_ptr = choose_cpu_impl();
   0x0000000001963a8f <+75>:    mov    -0x118(%rbp),%rax
   0x0000000001963a96 <+82>:    mov    %rax,%rdi
   0x0000000001963a99 <+85>:    callq  0x168b2a0 <at::native::DispatchStub<void (*)(at::TensorIterator&, c10::Scalar), at::native::add_stub>::choose_cpu_impl()>
   0x0000000001963a9e <+90>:    mov    %rax,%rdx
   0x0000000001963aa1 <+93>:    mov    -0x118(%rbp),%rax
   0x0000000001963aa8 <+100>:   mov    %rdx,(%rax)

71            }
```

Will run the benchmark you linked to and report back.

**Review by ezyang — APPROVED** [review]
I don't see any LOCKed instructions in the new assembly so we should be OK.

**Pull request closed without merging**
