### PR TITLE
[WIP] fix different round behavior on CPU and GPU #16498

### PR DESCRIPTION
**Pull request by musikisomorphie**
@xxtemp, @colesbury, @bhushan23, @zou3519,  convert gpu round behavior to half-to-even, consistent with torch cpu version and numpy. You feedback are welcomed.
See #16498

### CODE REVIEW

**Comment by bhushan23** [comment]
can you also add test cases?

**Comment by soumith** [comment]
yes, add a test case to test/test_cuda.py and this should be good to go

**Comment by vishwakftw** [comment]
I think this doesn't address the issue with respect to CPU rounding, which is still different based on the instruction set. See https://github.com/pytorch/pytorch/issues/16498#issuecomment-458636458

**Review by bhushan23 — COMMENTED** [review]
I thought only one blank line is allowed across functions

**Comment by musikisomorphie** [comment]
> I thought only one blank line is allowed across functions

I saw the error mentioning that there is one blank line missing, that is why I added it.
I guess since the indentation is different between test_cuda_round() and load_ignore_file(), two blank lines are required.

**Comment by musikisomorphie** [comment]
@soumith, a unit test is added.

@vishwakftw  What do you mean "instruction set"?  I didn't see the case that the cpu implementation of torch.round() wraps std::round. Besides, based on my test, the cpu version of torch.round() follows half-to-even mode. If you have counterexamples, please let me know.

**Comment by vishwakftw** [comment]
@musikisomorphie the half-to-even is because of the vectorized implementation, which is what you see in your CPU tests.

`std::round(2.5)` rounds to 3 (away from zero), whereas the vectorized implementation rounds 2.5 to 2 (nearest even). The patch for this issue would be to wrap the CPU implementation with `std::rint` instead of `std::round`.

**Comment by vishwakftw** [comment]
I think it'd be better to label this PR as `bc-breaking`.

**Comment by musikisomorphie** [comment]
> @musikisomorphie the half-to-even is because of the vectorized implementation, which is what you see in your CPU tests.
> 
> `std::round(2.5)` rounds to 3 (away from zero), whereas the vectorized implementation rounds 2.5 to 2 (nearest even). The patch for this issue would be to wrap the CPU implementation with `std::rint` instead of `std::round`.

@vishwakftw thank you for your feedback. 
What I did here is making the torch.round(), torch.cuda.round() and numpy.round() consistent, i.e., half-to-even.  
I suppose what you expect is replacing all std::round in the source code of pytorch with std:rint, so that the whole framework  strictly sticks to half-to-even mode or the other way around.
There exists mismatch between your expectation and my revision.  
Unfortunately I may not have enough time to work on that.

**Comment by musikisomorphie** [comment]
@bhushan23, @soumith, should we merge this PR or?

**Comment by VitalyFedyunin** [comment]
Actually replacing round to nearbyint in:
 https://github.com/pytorch/pytorch/blob/1ff864712bd7441b4ca2954b6bdd148e88506e39/aten/src/ATen/cpu/vec256/vec256_base.h#L224

and TH_MATH_NAME(round) to TH_MATH_NAME(nearbyint) everywhere (2 changes actually)

should suffice.

**Comment by musikisomorphie** [comment]
> TH_MATH_NAME(round)

Ok, I will fix them. Thanks for the tip.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Please merge master into this branch and avoid force-push.

**Comment by vishwakftw** [comment]
Is there any way to test CPU behavior for the non-vectorized version which has been modified?

**Comment by VitalyFedyunin** [comment]
Pretty much no, as all calls now dispatch to the vectorized version. Asking 
@musikisomorphie to remove old TH code would be too much for this PR. 

The only round() which is not covered by vectorized implementation is HalfTensor(a).cpu().round(), but right now we throw "round_out is not implemented for type torch.HalfTensor" anyway.

**Comment by musikisomorphie** [comment]
> Please merge master into this branch and avoid force-push.

Do you mean I should rebase my commit and without using force-push?

**Comment by VitalyFedyunin** [comment]
Just pull most recent master into your repo (do not rebase).

**Comment by musikisomorphie** [comment]
> Just pull most recent master into your repo (do not rebase).

I updated my branch, then git push origin my-branch. Is it correct?

**Comment by bhushan23** [comment]
Yes.

**Comment by bhushan23** [comment]
Yes.
I prefer to keep everything clean and no merge commits ( which will happen here), but that's fine.

**Comment by musikisomorphie** [comment]
Hi guys @VitalyFedyunin, @bhushan23, how is this progress of this PR going?

**Comment by musikisomorphie** [comment]
> @pytorchbot rebase this please

Hi @VitalyFedyunin, should I rebase this PR myself?

**Comment by VitalyFedyunin** [comment]
Yes please, there are internal tests failing (where they not supposed to), so I was trying to check if rebase would help.

**Comment by musikisomorphie** [comment]
> Yes please, there are internal tests failing (where they not supposed to), so I was trying to check if rebase would help.

I rebased and force pushed my branch, without force the terminal shows:

> To https://github.com/musikisomorphie/pytorch.git
>  ! [rejected]            round -> round (non-fast-forward)
> error: failed to push some refs to 'https://github.com/musikisomorphie/pytorch.git'
> hint: Updates were rejected because the tip of your current branch is behind
> hint: its remote counterpart. Integrate the remote changes (e.g.
> hint: 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Pull request closed without merging**
