### PR TITLE
[inductor] Simplify multi-kernel codegen by unifying kernel args

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #130988
* #127725
* __->__ #127724
* #131044

Persistent kernels are sometimes able to remove intermediate buffers that would
otherwise be needed for the non-persistent reduction kernel. This makes
multi kernel's codegen more complicated as it needs to drop these extra
arguments at runtime after selecting the correct kernel to run.

Instead, this PR updates the persistent kernel's `must_keep_buffers` so these
aren't dropped during codegen so both kernels have the same signature.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by shunting314** [comment]
Looks good overall.

Can you do a perf test with multi_kernel temporarily enabled? Just to make sure there are no extra errors not captured by current unit tests.

**Comment by peterbell10** [comment]
I've opened #130988 and it caught a few failures, one of which was this PR but the rest seem to be pre-existing. 

- `test_evict_last_non_coalesced_loads` is failing because it counts generated kernels, not a big deal.
- AOTInductor tests seem to be completely broken though. I've opened  #131035 to track that.

**Comment by peterbell10** [comment]
@shunting314 ping

**Comment by eellison** [comment]
letting @shunting314 take this one

**Review by shunting314 — APPROVED** [review]

**Pull request closed without merging**
