### PR TITLE
More appropriate socket errors and debug messages

### LINKED ISSUE #128998: Spurious "socket cannot be initialized" error messages
### 🐛 Describe the bug

When using nodes connected by IPv6, training proceeds correctly, but emits these misleading messages at log level error:

`2024-05-22 06:25:20.552227-04:00 Error From <host>: [W socket.cpp:436] [c10d] The server socket cannot be initialized on [::]:22010 (errno: 97 - Address family not supported by protocol).`

There's no good way I know of to filter these out, since they come from C++, and I don't want to ignore error messages.

The logic causing this is in [socket.cpp](https://github.com/pytorch/pytorch/blob/77830d509fcae41be37f5b3a2fa05faabc778e29/torch/csrc/distributed/c10d/socket.cpp#L579): we try all possible addresses returned by `getaddrinfo`, logging errors if any of them fail, but returning true if any of them succeed. I think the fix is simple: just move the error message into the failure case of `tryListen(int family)` instead.

### Versions

2.3.1 (and earlier)

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

### PR DESCRIPTION
**Pull request by mwlon**
Fixes #128998

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @chauhang

### CODE REVIEW

**Comment by fduwjj** [comment]
This looks good to me, I think you need to first get CLA Authorization.

**Comment by mwlon** [comment]
@fduwjj yep, we had logistical difficulties with easyCLA, but they should be resolved now.

**Comment by mwlon** [comment]
@fduwjj Can you review?

**Comment by mwlon** [comment]
@fduwjj @yf225 ping

**Review by fduwjj — APPROVED** [review]
LGTM

**Comment by mwlon** [comment]
@fduwjj I keep getting failures, but I don't think any of them are related to this PR. How can I get past these?

**Pull request closed without merging**
