### PR TITLE
Underscore prefix sparse_csr_tensor and to_sparse_csr

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Alternative to #58994

cc @gchanan @pearu @aocsa @IvanYashchuk

### CODE REVIEW

**Review by gchanan — APPROVED** [review]

**Comment by pearu** [comment]
I like the alternative https://github.com/pytorch/pytorch/pull/58994 better as it is less intrusive.

Just to clarify, the changes in release/1.9 will not land on master, right?

**Comment by driazati** [comment]
flake8 issues are real after the name change, can you fix and then
```bash
make quicklint -j10
```?

**Comment by ezyang** [comment]
lint is dumb i hate it

**Comment by ezyang** [comment]
make quicklint doesn't work for me:

```
ezyang-mbp:pytorch-tmp ezyang$ make quicklint -j10
./.github/scripts/generate_linux_ci_workflows.py
  File "  File "  File "  File "tools/actions_local_runner.pytools/actions_local_runner.pytools/actions_local_runner.pytools/actions_local_runner.py", line ", line ", line ", line 32323232



                def should_color() -> bool:
def should_color() -> bool:
def should_color() -> bool:
def should_color() -> bool:
                                                                                 ^
     SyntaxError  ^
 :   SyntaxErrorinvalid syntax^
:  
invalid syntax^
SyntaxError
: SyntaxErrorinvalid syntax: 
invalid syntax
make: *** [cmakelint] Error 1
make: *** Waiting for unfinished jobs....
make: *** [quick_checks] Error 1
make: *** [flake8] Error 1
make: *** [mypy] Error 1
Traceback (most recent call last):
  File "/Users/ezyang/Dev/pytorch-tmp/./.github/scripts/generate_linux_ci_workflows.py", line 5, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
make: *** [generate-gha-workflows] Error 1
```

**Comment by driazati** [comment]
Ah I should have pointed to https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#local-linting since there's an extra step. Also not that it matters now but the errors look like a rebase issue (should be fixed by #58786)

**Pull request merged**
