### PR TITLE
[CI] Update CPU inductor smoke test model list and target

### LINKED ISSUE #132097: [Inductor] CPU perf test needs to be updated
Previously, CPU Inductor perf test on CI instances were done without VecISA specified. https://github.com/pytorch/pytorch/pull/131812 fixed that, but that also means some of the existing perf smoke tests need to updated, see https://github.com/pytorch/pytorch/blob/8fe2bf212dc5e01b15cbe728958f940873230d64/.ci/pytorch/test.sh#L715 .

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames

### PR DESCRIPTION
**Pull request by zxd1997066**
Fixes #132097 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by desertfire — APPROVED** [review]

**Comment by chuanqi129** [comment]
@zxd1997066 merge

**Pull request closed without merging**
