### PR TITLE
Fix PyTorch separate compilation (Reland)

### PR DESCRIPTION
**Pull request by malfet**
Looks like there is a bug in CUDA device linker, but kernels that uses `thust::sort_by_key` can not be linked with other kernels
Solve the problem by splitting 5 thrust-heavy .cu files into `__torch_cuda_sp` library which is statically linked into `torch_cuda`
For default compilation workflow it should not make any difference.

Test Plan: Compile with `-DCUDA_SEPARABLE_COMPILATION=YES` and observe library size difference: 310Mb before, 173Mb after if compiled for sm_75

### CODE REVIEW

**Comment by malfet** [comment]
Waiting for builds to finish (i.e. to fail) for TorchHIP

**Comment by malfet** [comment]
Fixed builds, test failures seems to be irrelevant.

**Comment by ezyang** [comment]
Previously https://github.com/pytorch/pytorch/pull/34863

**Review by ezyang — APPROVED** [review]

**Review by seemethere — APPROVED** [review]
LGTM on green

**Comment by malfet** [comment]
@seemethere `backward_compatibility_check_test` is broken on master, so everything looks green to me.

**Comment by malfet** [comment]
Rebase and merge conflicts between upper and lower case spelling of the same command

**Pull request closed without merging**
