### PR TITLE
Move FunctionSchema implementations to cpp file

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #133856

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
did you end up here because of binary size bloat or because you wanted to tweak and print and not wait 10 mins for a recompile 😛

**Comment by ezyang** [comment]
I thought I wanted to tweak but it turns out I don't need to lol. Just some BE.

**Review by albanD — APPROVED** [review]
SGTM !
Some include needs tweaking

**Pull request closed without merging**
