### PR TITLE
[nn] zero_grad() set_to_none default True

### LINKED ISSUE #92656: Make True the default for set_to_none in Optimizer.zero_grad for 2.0 release
### 🚀 The feature, motivation and pitch

When calling `Optimizer.zero_grad`, the default value of `set_to_none` is currently False to ensure backwards compatibility. However, a value of True will generally reduce memory consumption and can improve training performance. Given the forthcoming release of PyTorch 2.0, there is a limited opportunity to make the breaking change in a SemVer-consistent fashion and default to the more performant alternative. This would also mean that new users, who may not be aware of this option, would automatically see performance benefits rather than having to opt-in.

### Alternatives

Retain the status quo and have users manually specify the more performant option when desired.

### Additional context

_No response_

cc @ngimel @ezyang @gchanan @vincentqb @jbschlosser @albanD @janeyx99

### PR DESCRIPTION
**Pull request by janeyx99**
Attempts to fix #92656

BC-breaking! This changes the default of zero_grad in optim and in nn to default set grads to None instead of zero tensors. We are changing the default because there are proven perf wins and existing code has typically not regressed due to this change. (will probably have to flesh out this note more).

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #92989
* __->__ #92731

---------
#### Gradients are now set to `None` instead of zeros by default in `torch.optim.*.zero_grad()` and `torch.nn.Module.zero_grad()`

This changes the default behavior of `zero_grad()` to zero out the grads by setting them to `None` instead of zero tensors. In other words, the `set_to_none` kwarg is now `True` by default instead of `False`. Setting grads to `None` reduces peak memory usage and increases performance. This will break code that directly accesses data or does computation on the grads after calling `zero_grad()` as they will now be `None`. To revert to the old behavior, pass in `zero_grad(set_to_none=False)`.

1.13
```
>>> import torch
>>> from torch import nn
>>> module = nn.Linear(5, 5)
>>> i = torch.randn(2, 5, requires_grad=True)
>>> module(i).sum().backward()
>>> module.zero_grad()
>>> module.weight.grad == None
False
>>> module.weight.grad.data
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
>>> module.weight.grad + 1.0
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
```

2.0
```
>>> import torch
>>> from torch import nn
>>> module = nn.Linear(5, 5)
>>> i = torch.randn(2, 5, requires_grad=True)
>>> module(i).sum().backward()
>>> module.zero_grad()
>>> module.weight.grad == None
True
>>> module.weight.grad.data
AttributeError: 'NoneType' object has no attribute 'data'
>>> module.weight.grad + 1.0
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
```

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Quite a few tests need updating. But YES!

**Comment by ngimel** [comment]
Can you please add a bc-breaking note here?

**Review by ngimel — APPROVED** [review]
LG, if tests pass

**Comment by soumith** [comment]
ooooh exciting. this is a big change :)

**Comment by FindHao** [comment]
This PR leads speedups widely for many models in torchbench. 22 models obtain over 1.03X speedup on A100! Thanks for your work! 
but I just found yolov3 has about a 17% slowdown for training on A100. The [nightly regression test](https://github.com/pytorch/benchmark/issues/1383) of torchbench runs on T4 now. So the test may miss this case. working on finding the root cause now. 
Since profiling introduces some overhead, I can't find the same results in profiling trace generated by pytorch profiler.

**Comment by janeyx99** [comment]
@FindHao Recently came back from PTO so sorry this response is delayed. Thanks for this callout! I'm curious about the yolov3 slowdown--have you been able to root cause it thus far? The simple workaround is to just directly pass set_to_none=False to regain perf, but I would like to help with figuring out the cause here.

**Comment by FindHao** [comment]
Hi @janeyx99 , we found it is caused by [torch.cuda.empty_cache()](https://github.com/pytorch/benchmark/pull/1408/files#diff-90b7fd70f830970a9b6a0bf3f7479b53a59de7c8dc4824336e447b252e2f0bf6L415). It takes longer than the original version. It's not the root cause, but since torchbench only tests one iteration for training, we don't need to empty the cache. So we removed this function as a workaround. I'll find some time to dig more.

**Comment by janeyx99** [comment]
@FindHao Ah, I spoke with @albanD and this is not surprising. When set_to_none was False, the same grad tensor was allocated once and kept alive throughout the iterations (it would be filled with 0s and then filled with values, and so forth). 

Now, because we set grad to None, it would increase the number of allocations whenever we alternate between None -> real values -> None -> real values, and so forth. This is typically not a problem except for certain configurations (like given a particular batch_size on a particular GPU) where the stars align just right and allocations incur an actual communication to the GPU vs being able to service from existing allocated memory.

**Comment by FindHao** [comment]
@janeyx99 Thanks for your explanation! It makes sense. I have another question. If I understand it correctly, setting it to none means marking the memory allocated to current tensors and it will be deallocated by the `torch.cuda.empty_cache`, right? If so, does it mean the memory usage would increase until we call empty_cache?

**Comment by ngimel** [comment]
No, `set_to_none=True` decreases memory usage, as it frees grad memory when called, and doesn't allocate them again until they are computed (which will likely be after high memory watermark is reached). @robieta had plots showing how `set_to_none` decreases memory usage.

**Comment by janeyx99** [comment]
Haha I will attempt to answer this question by setting down some terminology. PyTorch has a CUDACachingAllocator which reserves and manages memory for the duration of a PyTorch program. In a sense, you can imagine that it reserves a chunk of memory from the GPU and interfaces on top of the actual GPU so that every time the program releases/requests memory, we don't have to talk to the GPU. For example, if the PyTorch program releases memory, our CachingAllocator will hold onto it _instead of immediately releasing it to the GPU_ so that later on when the program wants memory again, it can lend that memory out. This would save time as communication between the GPU would be avoided entirely.

Thus, we have the concept of memory _reserved_ and memory _allocated_. The memory _reserved_ is the total memory managed by the CUDACachingAllocator, and the memory _allocated_ is the memory taken up by actual PyTorch tensors. Setting to None here will "free" the tensor so that the memory _allocated_ goes down immediately BUT the memory _reserved_ would remain the same. Calling torch.cuda.empty_cache() will empty the memory so that memory _reserved_ approaches memory _allocated_.

**Comment by FindHao** [comment]
@ngimel @janeyx99 Thanks for all your explanation!

**Pull request closed without merging**
