### PR TITLE
Remove curandStateMTGP32 usage

### PR DESCRIPTION
**Pull request by syed-ahmed**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#21301 Remove curandStateMTGP32 usage**
* #21300 Speedup bernoulli_scalar_cuda_kernel with grid-stride loop
* #21299 Move THCTensor_(lognormal) to ATen
* #21298 Move THCTensor_(geometric) to ATen
* #21297 Move THCTensor_(exponential) to ATen

Resubmit of https://github.com/pytorch/pytorch/pull/20886

## Summary:
This PR removes curandStateMTGP32 usages since it's not stream-safe.
Main changes are:
- It modifies THCTensor_(getRNGState) and THCTensor_(setRNGState) to not read/write curandStateMTGP anymore.
- It modifies RRelu.cu and cuda multinomial kernels to use curandStatePhilox
- It deletes new_state.clone() from torch.cuda.random.py to get a performance boost.

Differential Revision: [D15632929](https://our.internmc.facebook.com/intern/diff/D15632929)

### CODE REVIEW

**Comment by ryanchesler** [comment]
Sorry if this is a noob question but is there some way for me to be able to start utilizing these changes before they are fully tested? I am running across this error and hoping this fix will resolve them.

**Comment by syed-ahmed** [comment]
@ryanchesler The changes should be landing very soon if you could wait a bit. If not, you can find the full diff here: https://github.com/pytorch/pytorch/commits/gh/syed-ahmed/13/orig. It's the first 5 commits.

**Comment by syed-ahmed** [comment]
@ezyang all tests have passed in the stack. GitHub is just not updating the statuses

**Comment by ryanchesler** [comment]
Awesome. Glad this is making it through. Hopefully it solves the issue blocking me.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Hey @syed-ahmed this stack is conflicting with cauchy which I just landed. Can you rebase past that?

**Comment by syed-ahmed** [comment]
Rebased :)

**Comment by sbelharbi** [comment]
Hi,
   Sorry for this question.
I am facing some issues with rng states (see [here](https://discuss.pytorch.org/t/cuda-rng-state-does-not-change-when-re-seeding-why-is-that/47917/3?u=sbelharbi)).
It was suggested that this merge has fixed the issue.
By checking the date of this merge and the date of the latest version of Pytorch 1.1.0 (April 30), it seems that Pytorch 1.1.0 does not have this feature yet.

Do you have an idea when this feature will be available in a stable version?

I want to publish my code, and make it clear which version of Pytorch I used so it will be easy to install/reproduce.

Thanks!

**Comment by ezyang** [comment]
It will probably be included in 1.2 (assuming it doesn't get reverted before branch cut). You can also try using a nightly to get binaries with the fix earlier.

**Comment by sbelharbi** [comment]
Thanks!
The issue seems to be [fixed](https://discuss.pytorch.org/t/cuda-rng-state-does-not-change-when-re-seeding-why-is-that/47917/5?u=sbelharbi) in the nightly build (https://download.pytorch.org/whl/nightly/cu100/torch_nightly-1.2.0.dev20190616-cp37-cp37m-linux_x86_64.whl).

I hope 1.2.0 will be released soon!

**Comment by sbelharbi** [comment]
hi,
sorry to bother you.
was this commit integrated in v1.2.0 which was released today?
https://github.com/pytorch/pytorch/releases/tag/v1.2.0

I searched in the notes (key: rng, 21301), and did not find it.
thanks

**Comment by ezyang** [comment]
Yes it's in 1.2.0; 0e3c4a054b7783144fd03937748f8df8eac9c2e7 is reachable from v1.2.0 branch.  It does look like this is missing from the changelog notes.

**Comment by sbelharbi** [comment]
thanks!

**Pull request closed without merging**
