### PR TITLE
Add Packer Build job for Windows AMI

### PR DESCRIPTION
**Pull request by zxiiro**
Add a job to create Windows AMIs in the PyTorch AWS Account.

Issue: pytorch/test-infra#5992

### CODE REVIEW

**Comment by zxiiro** [comment]
Ready for review. I've confirmed that an AMI is successfully created in the PyTorch AWS account with this job.

**Review by seemethere — CHANGES_REQUESTED** [review]
Why is this necessary to have in the `pytorch/pytorch` repository? Wouldn't this be better suited in the `pytorch/test-infra` repository?

**Comment by zxiiro** [comment]
> Why is this necessary to have in the `pytorch/pytorch` repository? Wouldn't this be better suited in the `pytorch/test-infra` repository?

Actually it might not need to run here anymore. Originally I was trying to use an `lf.linux.large` instance which required it to be run here as the autoscaler only ran against `pytorch/pytorch`. However this morning I was able to configure it to use `ubuntu-latest` removing the need completely for using a self-hosted runner.

I'll investigate moving it over to test-infra this afternoon.

**Comment by zxiiro** [comment]
Moving this work back to test-infra now that we have a method that does not require a self-hosted runner. See pytorch/test-infra#6064

**Pull request closed without merging**
