### PR TITLE
Update ET pin for #6744

### PR DESCRIPTION
**Pull request by huydhn**
This will be updated to ET trunk commit after https://github.com/pytorch/executorch/pull/6744 lands.  I also move ET back from unstable and install llama3 dependencies

### CODE REVIEW

**Comment by huydhn** [comment]
Going to test this out on https://github.com/pytorch/pytorch/pull/140199 to wait for a green CI signal before landing.  I have been able to verified this locally

**Comment by huydhn** [comment]
@larryliu0820 Please help take a look, this will finally put ET back to PT CI

**Review by kit1980 — APPROVED** [review]

**Comment by huydhn** [comment]
Plz don't revert this one yet as I think it has a landrace with https://hud.pytorch.org/pytorch/pytorch/commit/222175b3d59f54e02c67db7d4a8ff3c4c69fb45f.  As that commit has been reverted, let's see if it fix the failure from this PR

**Pull request closed without merging**
