### PR TITLE
[ci] delete JOB_BASE_NAME

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #79396
* __->__ #80046
* #80144

`JOB_BASE_NAME` was a holdover from jenkins compatibility. Eventually,
it morphed to be always set to the build enviroment + `-test` or
`-build`, and we used it to detect whether we were in a build or test.

That's sort of pointless, so removing and fixing up the few remaining
use cases.

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
By the way, it also break PR CI for any PR based prior to it, as GH always tries to merge jobs definitions, for example see: https://github.com/pytorch/pytorch/runs/7014908086?check_suite_focus=true

**Review by janeyx99 — CHANGES_REQUESTED** [review]
This also breaks sharding, because we set BUILD_ENVIRONMENT in .jenkins/test.sh to contain the TEST_CONFIG :|

Looking at any of the test logs, the tests can't find the stats from the build jobs because of this.

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
