### PR TITLE
use mutable_data_ptr for grad_input in backward passes

### PR DESCRIPTION
**Pull request by dagitses**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #98999

Summary:

Test Plan: Rely on CI.

Reviewers: ezyang

Subscribers:

Tasks:

Tags:

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by kit1980** [comment]
@ezyang @dagitses should we merge this?

**Comment by ezyang** [comment]
yes

**Pull request closed without merging**
