### PR TITLE
[ONNX] Provide names for operator nodes in ONNX exported graph.

### PR DESCRIPTION
**Pull request by spandantiwari**
The PyTorch exporter does not add any name to the ONNX operators in the exported graph. A common request is to add names to op nodes by default. This helps the readability of the graph in visualization tools such a Netron, or when the ONNX graph is printed as a string. Also, it helps with the debuggability of the ONNX graph. 

Therefore this PR adds name to operators in the exporters. The names follow a simple format, <op_type>_<index>. Expect files for tests in `test/onnx/test_operators.py` have been updated.

### CODE REVIEW

**Review by houseroad — APPROVED** [review]
Looks good.

**Review by houseroad — CHANGES_REQUESTED** [review]
However, it breaks the tests in test_verify.py. Could you fix them?

**Comment by spandantiwari** [comment]
@houseroad - as discussed I have added an argument for `torch.utils._export` for switching between providing node names or not. It is on by default (i.e. node names are added by default), but turned off explicitly in the Caffe2 tests. 

Waiting for the CI to see if there are any other failures.

**Comment by spandantiwari** [comment]
One more test needs to be updated.

**Comment by spandantiwari** [comment]
@houseroad - all the tests are now passing. The failing builds seem to be unrelated. 

I would appreciate your review of this PR. It updates several expect files and the rebasing process will get cumbersome if this goes stale. :-) Thanks.

**Review by houseroad — COMMENTED** [review]
I think only setting False in the test cases is not enough. We should do the same as what we did for other options, if ONNX_ATEN_FALLBACK, it's False.

**Comment by spandantiwari** [comment]
@houseroad - OK. I will try to do that.

**Comment by spandantiwari** [comment]
> I think only setting False in the test cases is not enough. We should do the same as what we did for other options, if ONNX_ATEN_FALLBACK, it's False.

@houseroad - I have done this. Waiting for CI to finish.

**Comment by spandantiwari** [comment]
@houseroad - the build failure is unrelated. All tests are passing.

**Review by houseroad — APPROVED** [review]
Looks good. Thanks!

**Pull request closed without merging**
