### PR TITLE
Fix `svd_lowrank(..., M)` in the presence of broadcasting

### PR DESCRIPTION
**Pull request by NKNaN**
ISSUE: #122699 

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @xwang233 @Lezcano

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
SG. Can you write a regression test in `test/test_linalg.py`?

**Review by lezcano — COMMENTED** [review]
Can you also update the docs to mention that we broadcast on the M argument?

**Comment by NKNaN** [comment]
> SG. Can you write a regression test in `test/test_linalg.py`?

> Can you also update the docs to mention that we broadcast on the M argument?

Sure ^^
Let me add the test and and update the document.

**Review by lezcano — CHANGES_REQUESTED** [review]
Please don't duplicate the whole test. If anything, either add a short new standalone test or add a new test-case in the original test.

**Comment by lezcano** [comment]
This looks great, thanks!

Can you run `lintrunner -a` to fix the format?

**Review by lezcano — APPROVED** [review]
Great, thanks!

**Pull request closed without merging**
