### PR TITLE
Implement backward for pack_padded_sequence

### PR DESCRIPTION
**Pull request by elanmart**
On my machine this PR gives the following on CPU:
```bash
%timeit _ = rnn_utils.pack_padded_sequence(x, lengths).data.sum().backward()
%timeit _ = old_utils.pack_padded_sequence(x, lengths).data.sum().backward()

# 100 loops, best of 3: 5.75 ms per loop  # this PR
# 1 loop, best of 3: 194 ms per loop      # master
```
and GPU

```bash
%timeit _ = rnn_utils.pack_padded_sequence(x_cuda, lengths).data.sum().backward()
%timeit _ = old_utils.pack_padded_sequence(x_cuda, lengths).data.sum().backward()

# 1000 loops, best of 3: 1.67 ms per loop  # this PR
# 100 loops, best of 3: 11.5 ms per loop   # master
```

I've implemented this in python since I couldn't get `ATen` to accept the `batch_sizes` as input to `backward`.

There's an ugly conversion from a `Variable` to `list` when creating the `PackedSequence` tuple.

And also two tests are failing, because they assume that when `pack_padded_sequence` is called with `Tensors`, the `PackedSequence.data` will also be a `Tensor`, but here a `Function` converts it to `Variable`. Not sure how this should be handled.

Please let me know if this PR makes sense and if there's anything I could fix. Oh, and also if I should somehow concatenate these commits into a single one.

### CODE REVIEW

**Review by apaszke — APPROVED** [review]

**Comment by apaszke** [comment]
I think the CI is failing because it used to work with Tensors, which is no longer the case. I don't think it's worth maintaining that support since it's not documented, and tensors are going to be merged with Variables before 0.4, so it's not a big deal. Can you please fix the tests?

**Comment by elanmart** [comment]
Hey Adam, I'm so sorry for the lack of response, I was on a short vacations without a proper internet access. 
I've mentioned the issue with tests in the PR description

> And also two tests are failing, because they assume that when pack_padded_sequence is called with Tensors, the PackedSequence.data will also be a Tensor, but here a Function converts it to Variable. Not sure how this should be handled.

If it's OK, I'll change these tests tomorrow.

**Comment by apaszke** [comment]
Sorry I forgot that you've already mentioned this! There's no hurry, take your time

**Pull request closed without merging**
