### PR TITLE
fixing illegal memory access on NHWC BN kernel

### PR DESCRIPTION
**Pull request by jjsjann123**
adding an early exit in the kernel to avoid reading out of bound.

### CODE REVIEW

**Comment by jjsjann123** [comment]
cc'ing @ptrblck

**Comment by ngimel** [comment]
test? Also, do you know how much slower a plain TI kernel would be here?

**Comment by jjsjann123** [comment]
> test?

test is tricky with this one. Since we are only reading over the boundary without using the data in computation, it doesn't give observable issue other than occasional illegal memory access error.
Unfortunately I haven't got it reproed in a minimal example. I have a mini inception model that throws the IMA error at certain iteration when running on ampere (with caching allocator disabled).

I'd argue that this is a straightforward fix in the code.

> Also, do you know how much slower a plain TI kernel would be here?

Let me do a quick benchmark tomorrow. Will report back.

**Comment by ngimel** [comment]
Ok, one way to test would be to disable caching allocator - that way illegal memory accesses should more readily appear, but it's not convenient for regular testsuite anyway. I'll land this as is, and we can discuss if it can be replaced with TensorIterator kernel.

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
