### PR TITLE
[quant][refactor tests] Move test_quantized_functional.py into test_quantize_eager_ptq.py

### PR DESCRIPTION
**Pull request by supriyar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #59007 [quant][refactor tests] Move quantization tests into subfolders
* #59000 [quant][refactor tests] Move TestModelNumerics to a separate file
* #58999 [quant][refactor tests] Rename test_numeric_suite and equalization tests
* #58963 [quant][refactor tests] split test_workflow_module into test_workflow_ops and test_workflow_module
* #58943 [quant][refactor tests] Move test_quantized_module into test_quantize_eager_ptq
* **#58929 [quant][refactor tests] Move test_quantized_functional.py into test_quantize_eager_ptq.py**

Summary:

Test Plan:
python test/test_quantization.py TestQuantizedFunctionalOps

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D28683924](https://our.internmc.facebook.com/intern/diff/D28683924)

### CODE REVIEW

**Comment by supriyar** [comment]
@supriyar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28683924).

**Comment by supriyar** [comment]
@supriyar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28683924).

**Comment by supriyar** [comment]
@supriyar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28683924).

**Review by HDCharles — APPROVED** [review]
looks good

**Pull request closed without merging**
