### PR TITLE
Remove ProcessGroupCudaP2P and change async-TP to use SymmetricMemory

### PR DESCRIPTION
**Pull request by yifuwang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #129289
* __->__ #128762

This PR removes `ProcessGroupCudaP2P` and changes async-TP to use `SymmetricMemory`. The async-TP implementation is still workspace-based, but it now doesn't require a buffer size to be specified upfront.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]
sounds great! Let's go!

**Comment by Chillee** [comment]
How do we control whether SymmetricMemory is used now?

**Comment by yifuwang** [comment]
@Chillee it is enabled via `enable_symm_mem_for_group(group_name)`, which makes `_SymmetricMemory.empty_strided` work with the said group. The initialization cost is very small and the workspace is only initialized if used. Once the API matures we could enable it for all eligible process groups by default.

**Comment by jianc99** [comment]
When I set ENABLE_INTRA_NODE_COMM=1, I got the RuntimeError: : CUDASymmetricMemory requires pidfd_open and pidfd_getfd support. How to solve it?

**Comment by yifuwang** [comment]
> Can I solve this problem without updating the kernels?

@jianc99 I can try to address this. Can you open an issue for it?

**Pull request closed without merging**
