### PR TITLE
Support "symmetric" padding

### LINKED ISSUE #46240: Support "symmetric" reflection padding
## 🚀 Feature

Currently `ReflectionPadNd` does *not* repeat the boundary pixels, as demonstrated by the docs:

```
>>> m = nn.ReflectionPad2d(2)
>>> input = torch.arange(9, dtype=torch.float).reshape(1, 1, 3, 3)
>>> input
tensor([[[[0., 1., 2.],
          [3., 4., 5.],
          [6., 7., 8.]]]])
>>> m(input)
tensor([[[[8., 7., 6., 7., 8., 7., 6.],
          [5., 4., 3., 4., 5., 4., 3.],
          [2., 1., 0., 1., 2., 1., 0.],
          [5., 4., 3., 4., 5., 4., 3.],
          [8., 7., 6., 7., 8., 7., 6.],
          [5., 4., 3., 4., 5., 4., 3.],
          [2., 1., 0., 1., 2., 1., 0.]]]])
```

According to the paper mentioned below, it would be very beneficial to use the `SYMMETRIC` variation that is already available in [tensorflow](https://www.tensorflow.org/api_docs/python/tf/pad) - I'm quoting the example from the linked page:

```
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1,], [2, 2]])
# 'constant_values' is 0.
# rank of 't' is 2.
tf.pad(t, paddings, "CONSTANT")  # [[0, 0, 0, 0, 0, 0, 0],
                                 #  [0, 0, 1, 2, 3, 0, 0],
                                 #  [0, 0, 4, 5, 6, 0, 0],
                                 #  [0, 0, 0, 0, 0, 0, 0]]

tf.pad(t, paddings, "REFLECT")  # [[6, 5, 4, 5, 6, 5, 4],
                                #  [3, 2, 1, 2, 3, 2, 1],
                                #  [6, 5, 4, 5, 6, 5, 4],
                                #  [3, 2, 1, 2, 3, 2, 1]]

tf.pad(t, paddings, "SYMMETRIC")  # [[2, 1, 1, 2, 3, 3, 2],
                                  #  [2, 1, 1, 2, 3, 3, 2],
                                  #  [5, 4, 4, 5, 6, 6, 5],
                                  #  [5, 4, 4, 5, 6, 6, 5]]

```

I propose two ways in which this could be done: Either we extend `ReflectionPadXd()` with a `mode` argument, or alternatively we introduce `SymmetricPadXd()` as a separate class in `torch.nn`.

## Motivation

This is prompted by the paper [Mind the Pad -- CNNs can Develop Blind Spots](https://arxiv.org/abs/2010.02178v1) (Alsallakh et al, facebook AI), which investigated the behaviour of different padding methods and how some of them have a detrimental effect to the network.

## Pitch

Add a new method that pads an array `[1,2,3,4,5,6]` symmetically by repeating the boundary pixel  as `[2,1,1,2,3,4,5,6,6,5]` (unlike `ReflectionPadNd()` that does *not* repeat the boundary pixel: `[3,2,1,2,3,4,5,6,5,4]`).

## Alternatives

This behaviour can still be done using the current methods by first using a 1-pixel `ReplicationPadXd()` and add the `ReflectionPadXd()` after that, but it is quite cumbersome.

## Additional context

The *"symmetric padding"* is also popular in wavelet transforms or discrete convolutions, see e.g. [here](https://pywavelets.readthedocs.io/en/latest/ref/signal-extension-modes.html).

### PR DESCRIPTION
**Pull request by v0lta**
Fixes https://github.com/pytorch/pytorch/issues/46240 , the main idea is to add support for NumPy style `symmetric` padding.

This is my first PyTorch pull request. I have tried to follow all best practices, but if I missed something, please let me know.

Please note: Currently, this symmetric padding implementation allows the padding to 'wrap around.' This is useful in the wavelet case discussed in the original issue. However, we may want to throw an error instead to be consistent with the existing `circular` padding implementation.
This would happen in line 270 of aten/src/ATen/native/PadNd.cpp in this request.

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### CODE REVIEW

**Comment by v0lta** [comment]
I think I fixed of the build probles. Can we re-run the ci?

**Comment by v0lta** [comment]
The last remaining failure is:
```
 =========================== short test summary info ============================
FAILED [408.4112s] test_quantization.py::TestQuantizePT2EQATModels::test_qat_mobilenet_v2 - RuntimeError: Unexpected success, please remove `test/dynamo_expected_failures/TestQuantizePT2EQATModels.test_qat_mobilenet_v2`
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
=========== 1 failed, 177 deselected, 2 rerun in 1156.41s (0:19:16) ============
```
I am not sure if this is related to this PR.

**Review by mikaylagawarecki — COMMENTED** [review]
Can we also update the doc for pad to expose this mode 

https://github.com/pytorch/pytorch/blob/46c52661bc589722b1a98e30a60b6650f3124f06/torch/nn/functional.py#L5058-L5059

**Comment by v0lta** [comment]
I have tried to make the changes that were needed. In addition to testing on different devices, I have additionally added a `@dtypes` decorator like its done for `test_pad` for completeness.

**Comment by v0lta** [comment]
@mikaylagawarecki, do you like the changes?

**Comment by v0lta** [comment]
If there is something I can do to make this work, please let me know. It looks like the bot will close this now. The motivation here was to provide native symmetric padding directly in PyTorch. Symmetric padding is the default in PyWavelets, the update would alow us make the PyTorch-Wavelet Toolbox compatible by default ( https://github.com/pytorch/pytorch/issues/46240 ).

**Comment by scaomath** [comment]
Just want to add another data point here. `symmetric` padding is useful in impose Neumann boundary condition in finite difference method as well (using ghost cells). A workaround I am currently using is to permute the dimension needed to be padded to the last dimension, use flip and cat to do the job, then permuted that dimension back.

**Pull request closed without merging**
