### PR TITLE
Fix nll loss dynamo failure

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #120805

Fix for https://github.com/pytorch/pytorch/issues/119791 Part of dynamo bug bash

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by zou3519 — APPROVED** [review]
nice!

**Comment by zou3519** [comment]
Test failures are real -- we need to go removing some unittest.expectedFailures: 

image

**Comment by eellison** [comment]
Ah, didn't realize they were unexpected successes.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
