### PR TITLE
Sync changes from `pytorch/torchdynamo`

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #86988
* __->__ #87013

This updates to:
https://github.com/pytorch/torchdynamo/commit/6380959be21851bfda99424392cc08fda29d073d

Generated with:
https://github.com/pytorch/torchdynamo/blob/main/copy_to_core.sh

### CODE REVIEW

**Comment by soumith** [comment]
test comment (ignore)

**Review by voznesenskym — APPROVED** [review]

**Pull request closed without merging**
