### PR TITLE
Improve bf16 neg by bypassing the convertion between BF16 and FP32

### PR DESCRIPTION
**Pull request by EikanWang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #99828
* #99822
* #99814
* __->__ #99711

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by mingfeima — CHANGES_REQUESTED** [review]
Please add test case: 
* for vectorization test case: update `pytorch/aten/src/ATen/test/vec_test_all_types.cpp`
* probably also need to update test cases from `pytorch/test/test_torch.py`

**Comment by EikanWang** [comment]
@mingfeima , I suppose the two test suites can convert the modified code changes as it just updates the internal logic w/o interface modification. May I know if I need to add the additional cases?

https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/test/vec_test_all_types.cpp#L164

**Review by jgong5 — APPROVED** [review]

**Review by mingfeima — APPROVED** [review]
Shall we create a wrapper for this to share with `abs` and `neg`, a lot of code duplication here.

**Comment by EikanWang** [comment]
> Shall we create a wrapper for this to share with `abs` and `neg`, a lot of code duplication here.

Yes, I will do that.

**Review by desertfire — APPROVED** [review]

**Pull request closed without merging**
