### PR TITLE
fix batchnorm2d issue when input is non contiguous

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#63392 fix batchnorm2d issue when input is non contiguous**

Differential Revision: [D30476317](https://our.internmc.facebook.com/intern/diff/D30476317)

### CODE REVIEW

**Comment by mingfeima** [comment]
To fix #63224.

**Comment by david-macleod** [comment]
Can I just confirm this will only affect the behavior on CPU (CUDA unaffected)?

**Comment by mingfeima** [comment]
> Can I just confirm this will only affect the behavior on CPU? (CUDA unaffected)

Yes, this will guarantee 1.10 nightly has the same behavior as 1.9 on CPU side.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30476317).

**Pull request closed without merging**
