### PR TITLE
[pt1][tensor] Remove ExtractDeviceOptoin in StaticContext

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11688 [pt1][tensor] Move CreateContext to global registry&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9779821/)
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#11689 [pt1][tensor] Remove ExtractDeviceOptoin in StaticContext**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9826209/)

Move the ExtractDeviceOption function to a global registry

Differential Revision: [D9826209](https://our.internmc.facebook.com/intern/diff/D9826209/)

### CODE REVIEW

**Comment by ezyang** [comment]
>> Making an entirely new registry for this seems like too much. ISTR we discussed less invasive ways of doing this, such as forward declaring DeviceOption and moving the implementations to the subclasses. Why did this not work?
> by subclass which one do you mean? this is mostly because GetGPUIDFromPointer can only be used in specific files like "context_gpu.cu".

I don't see GetGPUIDFromPointer in this patch at all. Is there a specific technical problem related to this? I couldn't figure it out from your description.

By subclass, I mean classes like CUDAStaticContext.

Stepping back a moment: what's the reason for this patch? I thought the reasoning of this patch was to make Context to stop depending on a type defined in protobuf. Is there another motivation behind the patch as you've authored it?

**Comment by jerryzh168** [comment]
@ezyang the reason is to get rid of StaticContext.

**Comment by jerryzh168** [comment]
we can write the function in tensor.h, but including common_gpu.h in tensor.h seems to be failing.

**Comment by ezyang** [comment]
So, IIRC, in the new `DataPtr` world (which is landed), the at::Device (analogous to DeviceOption) is stored directly on the DataPtr. So you don't actually need a way to "get" the device ID, you can read it off of at::Device, right? So the only thing you need to do then is to setup the allocators so that they save the device along with the pointer when they return a DataPtr.

**Comment by jerryzh168** [comment]
Actually, right now we haven't switched to use at::allocator(still using GetStaticContext()->New), so I believe we cannot use the at::Device?
I agree that once we eliminated StaticContext, we can use at::Device to query for device_id.
This is more of an intermediate state, I just want to do this step by step.(Or maybe I should remove New() first before this one?)

**Comment by ezyang** [comment]
I think it's fine to try to slice things step-by-step, but the intermediate states should make sense. The way this current PR is setup, it adds a registry that really shouldn't exist in the terminal state.

**Comment by jerryzh168** [comment]
I think we can't do this without first writing the c2 allocator under the new allocator design then.

**Comment by SsnL** [comment]
@jerryzh168 Any update on this?

**Comment by jerryzh168** [comment]
@SsnL will redo this after New() is removed

**Comment by jerryzh168** [comment]
we can close this one

**Pull request closed without merging**
