### PR TITLE
[nnc] Added micro-benchmark to show perf improvement with cat subgraph optimization

### PR DESCRIPTION
**Pull request by navahgar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#59581 [nnc] Added micro-benchmark to show perf improvement with cat subgraph optimization**
* #59580 [nnc]  Added a transformation to move users of aten::cat to its inputs in the NNC kernel subgraph.
* #60162 [jit] Exported a method to get the supported list of elementwise ops
* #59579 [jit] Made a list for element-wise ops.

Concat performance w_ NNC

With this optimization, some micro-benchmarks, specifically the ones where cat ops are used by another element-wise op, show performance improvement of upto **2x**.

Differential Revision: [D28955317](https://our.internmc.facebook.com/intern/diff/D28955317)

### CODE REVIEW

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28955317).

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28955317).

**Review by bertmaher — APPROVED** [review]

**Comment by bertmaher** [comment]
awesomecat:
image

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28955317).

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28955317).

**Pull request closed without merging**
