### PR TITLE
[torch deploy] add register_module_source

### PR DESCRIPTION
**Pull request by zdevito**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #58117 [torch deploy] add support for Python C extension modules
* **#58290 [torch deploy] add register_module_source**

this is a helper function to get some python source code loaded
on each interpreter without having to use the standard import system
or packages. Useful for debugging or for writing wrapper classes for
handling loaded modules.

Differential Revision: [D28435306](https://our.internmc.facebook.com/intern/diff/D28435306)

### CODE REVIEW

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435306).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435306).

**Review by wconstab — APPROVED** [review]
lgtm. does it work for creating modules other than at the top level of __main__? 

(could you create or append modules to existing module heirarchies?) not sure you'd want to anyway, and in cases of more complex codebases you clearly suggest package instead.

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435306).

**Pull request closed without merging**
