### PR TITLE
[WIP] #35954 torch.finfo support for complex

### PR DESCRIPTION
**Pull request by Justin-Huber**
@mruberry

### CODE REVIEW

**Comment by mruberry** [comment]
Make sure to request a review when this is ready ;)

**Comment by Justin-Huber** [comment]
Hey @mruberry I think it's ready for review. I don't think the failing tests are related to my changes.

**Comment by mruberry** [comment]
> Hey @mruberry I think it's ready for review. I don't think the failing tests are related to my changes.

You need to rebase, remove the third party changes, and take the PR out of draft, though.

**Comment by Justin-Huber** [comment]
I rebased and removed those third party changes. Not sure what the failed tests mean.

**Comment by Justin-Huber** [comment]
Made those changes. Not sure what the current failing tests mean.

**Comment by mruberry** [comment]
I think this functionality has been subsumed by https://github.com/pytorch/pytorch/pull/40488, which is going in soon. Is that correct, @Justin-Huber? I think, unfortunately, you were scooped.

If you're interesting in working on other PyTorch issues or complex-specific PyTorch issues, however, I know of some projects that others aren't currently working on.

**Comment by Justin-Huber** [comment]
Ah, yeah it has everything I'd have added, thanks for letting me know. I'd be interested to take a look at the other issues you mentioned.

**Comment by mruberry** [comment]
I'd recommend taking a look at https://github.com/pytorch/pytorch/issues/38349. In the "Good Starter Function" section there are several functions that PyTorch would like to have, and there are also a few PRs you can look at to get an idea for how  to write a function for PyTorch. 

`vsplit` and `vstack` or `isreal` might be fun. I don't think anyone is working on them, either.

**Pull request closed without merging**
