### PR TITLE
Add config toggle suggestions for data-dependent/dynamic output shape

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #114337

Fixes https://github.com/pytorch/pytorch/issues/114220

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by pmeier** [comment]
Thanks for the clarification @ezyang. What is the reason this not being on by default? Is it not stable enough yet or will this always behind a feature flag? We have boolean masking in a few ops over at TorchVision.

**Comment by ezyang** [comment]
I've been working on it at https://github.com/pytorch/pytorch/pull/110155 but Inductor still chokes on some of the input graphs with dynamic shapes, so we're not quite there yet.

**Comment by aakhundov** [comment]
Seems like the exact assertion on the error message fails:

https://github.com/pytorch/pytorch/blob/01366efcc9d2e6f42d2783a8436a5357895140f4/test/test_custom_ops.py#L1492-L1495

**Review by aakhundov — APPROVED** [review]

**Pull request closed without merging**
