### PR TITLE
Bump up windows cudnn version

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fixes #{issue number}

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
@peterjc123 The current address I used to test on the CI is my personal address. Could you help uploading this file to s3, and I will revert the address change to s3?

**Comment by peterjc123** [comment]
@zasdfgbnm Uploaded to S3.

**Comment by peterjc123** [comment]
> @peterjc123 The current address I used to test on the CI is my personal address. Could you help uploading this file to s3, and I will revert the address change to s3?

By the way, would you please update https://github.com/pytorch/pytorch/blob/master/.circleci/scripts/windows_cudnn_install.sh and https://github.com/pytorch/vision/blob/master/packaging/windows/internal/cuda_install.bat as well?

**Comment by zasdfgbnm** [comment]
@peterjc123 I have updated the download link back to S3. I will update the vision link soon, and will update the builder link after the CI for pytorch and vision passes.

**Review by peterjc123 — APPROVED** [review]

**Pull request closed without merging**
