### PR TITLE
move Tensor comparisons back to C

### PR DESCRIPTION
**Pull request by robieta**
It seems that the machinery to handle comparison method in C rather than Python already exists, unless I'm missing something. (There is a wrapper for `TypeError_to_NotImplemented_`, and Python code gen handles `__torch_function__` which are the two things `_wrap_type_error_to_not_implemented` is doing) The performance change is quite stark:

```
import torch
from torch.utils.benchmark import Timer

global_dict = {
    "x": torch.ones((2, 2)),
    "y_scalar": torch.ones((1,)),
    "y_tensor": torch.ones((2, 1)),
}

for stmt in ("x == 1", "x == y_scalar", "x == y_tensor"):
    print(Timer(stmt, globals=global_dict).blocked_autorange(min_run_time=5), "\n")
```

### Before:
```
<torch.utils.benchmark.utils.common.Measurement object at 0x7f3d1289dc10>
x == 1
  Median: 12.86 us
  IQR:    0.65 us (12.55 to 13.20)
  387 measurements, 1000 runs per measurement, 1 thread

<torch.utils.benchmark.utils.common.Measurement object at 0x7f3d1289d1d0>
x == y_scalar
  Median: 6.03 us
  IQR:    0.33 us (5.91 to 6.24)
  820 measurements, 1000 runs per measurement, 1 thread

<torch.utils.benchmark.utils.common.Measurement object at 0x7f3d2b9e2050>
x == y_tensor
  Median: 6.34 us
  IQR:    0.33 us (6.16 to 6.49)
  790 measurements, 1000 runs per measurement, 1 thread
```

### After:
```
<torch.utils.benchmark.utils.common.Measurement object at 0x7fbdba2a16d0>
x == 1
  Median: 6.88 us
  IQR:    0.40 us (6.74 to 7.14)
  716 measurements, 1000 runs per measurement, 1 thread

<torch.utils.benchmark.utils.common.Measurement object at 0x7fbdd2e07ed0>
x == y_scalar
  Median: 2.98 us
  IQR:    0.19 us (2.89 to 3.08)
  167 measurements, 10000 runs per measurement, 1 thread

<torch.utils.benchmark.utils.common.Measurement object at 0x7fbdd33e4510>
x == y_tensor
  Median: 3.03 us
  IQR:    0.13 us (2.97 to 3.10)
  154 measurements, 10000 runs per measurement, 1 thread
```

There's still a fair bit of work left. Equivalent NumPy is about 6x faster than the new overhead, and PyTorch 0.4 is about 1.25 us across the board. (No scalar cliff.) But it's a start.

### CODE REVIEW

**Review by hameerabbasi — APPROVED** [review]
LGTM, assuming CI passes. Do we know when this was moved to Python from C?

**Comment by peterbell10** [comment]
When I added the wrapper in #27423, torch_function wasn't a concern and the overhead was pretty minimal.  I think the wrapper now causes `__torch_function__` dispatch to happen twice which presumably caused most of the overhead.

IIUC, this does slightly change the `__torch_function__` behaviour though. Previously you could override `Tensor.__eq__` separately from `Tensor.eq`. Not sure if that's desirable though and it's now consistent with the other dunder methods already defined in C++ with `TypeError_to_NotImplemented`.

**Comment by robieta** [comment]
> When I added the wrapper in #27423, `__torch_function__` wasn't a concern and the overhead was pretty minimal. I think the wrapper now causes `__torch_function__` dispatch to happen twice which presumably caused most of the overhead.
> 
> IIUC, this does slightly change the `__torch_function__` behaviour though. Previously you could override `Tensor.__eq__` separately from `Tensor.eq`. Not sure if that's desirable though and it's now consistent with the other dunder methods already defined in C++ with `TypeError_to_NotImplemented`.

I think you can still override the two independently. (I agree that it's unclear if that's even a good thing or not...) I ran the following on 1.7: https://colab.research.google.com/gist/robieta/3453df1dd29e4f62d3036d8d26808f92/tensor_override.ipynb

I get the same behavior on this PR: namely that for the last case: for the `Tensor` subclass with both `__eq__` override and `__torch_function__` the `__eq__` override takes precedence.

**Comment by peterbell10** [comment]
Note that in 1.7 `__torch_function__` is called with `func=torch.Tensor.__eq__`. I suspect it's now called with `func=torch.Tensor.eq` because that's the method doing the `__torch_function__` handling.

**Comment by robieta** [comment]
> Note that in 1.7 `__torch_function__` is called with `func=torch.Tensor.__eq__`. I suspect it's now called with `func=torch.Tensor.eq` because that's the method doing the `__torch_function__` handling.

When does it do that? In my gist (1.7.0) it's called with `func=torch.Tensor.eq`.

**Comment by peterbell10** [comment]
Try running this code in the notebook:
```python
print(torch.Tensor.eq)
print(torch.Tensor.__eq__)
```

The wrapper has the wrong name, but you can tell from how it's printed that it's really the dunder version:
```
<method 'eq' of 'torch._C._TensorBase' objects>
<function _TensorBase.eq at 0x7f1aa1f4dd08>
```

**Comment by robieta** [comment]
@peterbell10 Ah, you're absolutely right.

**Comment by hameerabbasi** [comment]
> Note that in 1.7 `__torch_function__` is called with `func=torch.Tensor.__eq__`. I suspect it's now called with `func=torch.Tensor.eq` because that's the method doing the `__torch_function__` handling.

Assuming a sane wrapper, that should have no effect. The reason is simply that `__add__` et. al. work the same way.

**Comment by robieta** [comment]
So it seems like the consensus is that the `foo / __foo__` divergence for comparison ops is an anomaly and we can probably just unify them. Test failures are the reverse of https://github.com/pytorch/pytorch/pull/27423, so probably fine to switch them back?

**Review by bhosmer — APPROVED** [review]
Assuming the experts confirm your last question, this LGTM

**Comment by hameerabbasi** [comment]
> Test failures are the reverse of #27423, so probably fine to switch them back?

Yes, IIUC ONNX output isn't particularly stable, so as long as it's correct, we should be good.

**Review by peterbell10 — APPROVED** [review]

**Pull request closed without merging**
