### PR TITLE
Enhance DataLoader Type Inference with Collate Function Return Type"

### PR DESCRIPTION
**Pull request by ArthurBook**
## Feature:
Made utils.data.dataloader.DataLoader infer its type from _collate_fn when passed.

### Description:
Adressing this comment in the code
```# _Ideally we would parameterize `DataLoader` by the return type of `collate_fn`, but there is currently no way to have that_```

### Example:
```python
from typing import List
from torch.utils.data import dataloader, dataset


class TestDataSet(dataset.Dataset[int]):
    def __getitem__(self, _) -> int:
        return 1
    
def test_collate_function(_: List[int]) -> str:
    return 'foo'

# (variable) testdataloader: DataLoader[int]
testdataloader = dataloader.DataLoader(
    TestDataSet() # type is now inferred from TestDataSet type variable
)

# (variable) testdataloader_w_collate: DataLoader[str]
testdataloader_w_collate = dataloader.DataLoader(
    TestDataSet(), 
    collate_fn=test_collate_function # type is now inferred from test_collate_function return type
)
```

### Sidenote:
This also enables typecheckers to catch when the collate_fn is incompatible with the dataset type parameter
```python
def test_collate_function_that_wants_strings(_: List[str]) -> str:
    return 'foo'

# typechecker catches incompatible type! 
testdataloader_w_collate = dataloader.DataLoader(
    TestDataSet(), 
    collate_fn=test_collate_function_that_wants_strings # "List[int]" is incompatible with "List[str]"
)
```

### CODE REVIEW

**Comment by Skylion007** [comment]
is `typing_extensions.Self` useful here at all, btw?

**Comment by ArthurBook** [comment]
It would be neat to replace  `self: 'DataLoader[T_co]'` with `self: 'Self[T_co]'` [here](
https://github.com/pytorch/pytorch/blob/b12f7ea21a959c4cdca0b48003620213a087db49/torch/utils/data/dataloader.py#L228) but typing.Self doesn't take any type parameters so which is why I referenced the class directly. WDYT? I might be missing something.

**Comment by ArthurBook** [comment]
Hi @laurencer, understand that type hint fixes are probably low prio but let me know if I can clarify anything to speed up the review. This would review quite a few `type: ignore`s from my code.

**Comment by ArthurBook** [comment]
Hi!
Just noticed that this PR got closed... 
Would you be able to reopen it? @laurencer @mikaylagawarecki 
It's ready for review and open to work on it if you want any changes made to it.

**Pull request closed without merging**
