### PR TITLE
Added implementation and tests for MPS Hardswish

### PR DESCRIPTION
**Pull request by thomaslin2020**
## What?
Fixes issue #86807 by adding MPS backend support for aten::hardswish.

## How?
Registered mps hardswish functions in native_functions.yaml, and added the code implementation to Activations.mm. 

Added functions:
- hardswish_mps
- hardswish_mps_
- hardswish_backward_mps
- hardswish_out_mps

## Testing
Added test in test/test_mps.py and tested code using the command `python3 test/test_mps.py -k test_hardswish`

### CODE REVIEW

**Review by kulinseth — APPROVED** [review]
Overall it looks good.

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
