### PR TITLE
Clean up future imports for Python 2

### PR DESCRIPTION
**Pull request by skyline75489**
See #42919

### CODE REVIEW

**Comment by skyline75489** [comment]
@bugra Can you take a look? 😄

**Comment by bugra** [comment]
Looks good to me!

**Review by bugra — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by bugra** [comment]
@skyline75489 Is there anything left over for Python 2? Thanks for doing this!

**Comment by skyline75489** [comment]
@bugra I think there are still things left to be done, especially things that are hidden in the logic (for example https://github.com/pytorch/pytorch/issues/42919#issue-677794004 ). It would be more trivial to find and clean them but I'll give it a try when I got the time 😃

**Pull request closed without merging**
