### PR TITLE
Better core binding in torch.backends.xeon.run_cpu when launced from torchrun with --nproc-per-node

### PR DESCRIPTION
**Pull request by delock**
This PR fix `torch.backends.xeon.run_cpu` behavior when it is launched from `torchrun` with `--nproc-per-node` parameter.

As a CPU launcher, `run_cpu` would bind cores to each instance it launches using `numactl`, and assign cores to each instance evenly.

However, if we use `torchrun` to start `run_cpu` and use `--nproc-per-node` to create multiple `run_cpu` processes.   In this case, each `run_cpu` process would assume it can use all the CPU cores, which causes each `run_cpu` process compete for CPU cores.  This results in poor performance.

This PR recognize environment variable `LOCAL_WORLD_SIZE` and `LOCAL_RANK` set by `torchrun`, then use this information to further shard the cores bind to each instance.  With this PR, when launched by `torchrun --nproc-per-node ...`, different CPU cores will be bind to different workers, which maximize CPU utilization and application performance.

The specific use case this PR enabled is using TorchServe with DeepSpeed tensor parallel.  In this case, TorchServe would run `torchrun --nproc-per-node <tp_size>` to start tensor parallel workers it needed.  When run TorchServe on multisocket CPU server with DeepSpeed tensor parallel, we need this PR to achieve best performance.

### CODE REVIEW

**Review by jingxu10 — APPROVED** [review]
looks good to me.

**Comment by delock** [comment]
@jingxu10 looks like there is a random failure in retriving pytorch repo.  Let me merge again.

**Comment by delock** [comment]
The failures seems not related to this PR, I'll merge again to see if it still exists.
```
  File "C:\actions-runner\_work\pytorch\pytorch\test\test_cpp_extensions_open_device_registration.py", line 99, in test_base_device_registration
    x = torch.empty(4, 4, device=device)
ModuleNotFoundError: No module named 'torch.foo'
```

**Comment by delock** [comment]
Hi @ezyang, this PR needs approval from maintainer to be merged.  Can you help review this PR?  Thanks!

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
