### PR TITLE
remove commented out breakpoints

### PR DESCRIPTION
**Pull request by bobrenjc93**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135363

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by oulgen — APPROVED** [review]

**Comment by oulgen** [comment]
@bobrenjc93 the problem is https://github.com/pytorch/pytorch/pull/135361 stacked under this one, but you manually edited the comment which makes it harder to see. The comment does not change stacked-ness nature. It is based on base/diff branches

**Comment by bobrenjc93** [comment]
@oulgen right so after adjusting the comment failed, I actually rebased this commit on top of main and ran ghstack again. Is there a better way to rebase/reorder ghstack PRs?

**Comment by oulgen** [comment]
@bobrenjc93 In order to re order, I'd do interactive rebase (`git rebase -i`), flip the commits, and send it again using `ghstack`

**Comment by bobrenjc93** [comment]
@oulgen I meant I already did the rebase of my commit away from the old commit. eg. I ran

```
git fetch origin && git rebase --onto origin/viable/strict HEAD^ && ghstack
```

So if when I run git log, the old commit isn't even there
```
commit edd0ed445048a7692d45811c47858d036efa4cfe (HEAD, origin/gh/bobrenjc93/9/orig)
Author: Bob Ren <bobren@fb.com>
Date:   Sat Sep 7 12:14:33 2024 -0700

    remove commented out breakpoints
    
    ghstack-source-id: 2ab0c7c9036e0fe3ead32809c18bcc8824c58e06
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/135363

commit f7c0c0669242de4ff21f35ad8a084085d45c93ba (origin/viable/strict)
Author: CaoE <e.cao@intel.com>
Date:   Fri Sep 6 21:42:54 2024 -0700

    Add oneDNN BRGEMM support on CPU (#131878)
    
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/131878
    Approved by: https://github.com/jgong5, https://github.com/peterbell10

commit b53d97c7be2ef0b7c86f3252bd06fe2539dc7a40
Author: Yu, Guangye <guangye.yu@intel.com>
Date:   Sat Sep 7 10:07:02 2024 +0000

    [Intel GPU] Add XPU memory-related APIs (#129919)
    
    # Motivation
    According to https://github.com/pytorch/pytorch/issues/116322, we will help unify the device allocator. So we introduce a simple xpu device allocator only with the key functionality first. And expect to add some memory statistics-related functionality after the unification.
    But now, some memory statistic-related APIs listed in https://github.com/pytorch/pytorch/issues/127929 are requested. We need more time to unify the device allocator. In order to facilitate the user experience, we expect to support these memory statistic-related APIs before the unification.
    
    # Additional Context
    Fixes: #127929
    
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/129919
    Approved by: https://github.com/dvrogozh, https://github.com/abhilash1910, https://github.com/gujinghui, https://github.com/EikanWang, https://github.com/albanD
    ghstack dependencies: #130923
```

**Pull request closed without merging**
