### PR TITLE
[FX] Specifies a default value when possible for placeholders created from concrete_args

### PR DESCRIPTION
**Pull request by michaelbenayoun**
```python
class Foo(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, a=None, b=None):
        res = a
        if b is not None:
            res = res + b
        return res

concrete_args = {'b': torch.tensor(5)}
traced = fx.symbolic_trace(Foo(), concrete_args=concrete_args)
```

Gives the following error:

```
  File "<eval_with_key_9>", line 2
    def forward(self, a = None, b_1):
                ^
SyntaxError: non-default argument follows default argument
```

Since #55888, placeholders are also created for concrete arguments. But these placeholders do not have default values even when  it was provided for the argument in question, causing the error above. 

To solve this, I add a default value when it is available during placeholder creation for concrete arguments. 

I also tried to set the default value to the value specified in concrete_args (since it many cases it will actually use this value anyway), but ran into an error because the default value is never defined:

```
def forward(self, a = None, b_1 = _tensor_constant0):
    _tensor_constant0 = self._tensor_constant0
    _tensor_constant1 = self._tensor_constant1
    add = a + _tensor_constant1;  a = _tensor_constant1 = None

NameError: name '_tensor_constant0' is not defined
```

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
This change still doesn't necessarily do the right thing in the presence of pytrees, but it's better than what we have now :)

Getting default arguments to work with pytrees seems ... quite painful - perhaps a future refactoring of pytrees will improve the situation.

**Comment by jerryzh168** [comment]
Hi @michaelbenayoun what is the status for this PR? is this going to be merged?

**Comment by michaelbenayoun** [comment]
Hi, on my end it's done.
It's been approved by one of the two reviewers, I do not know if it will be merged.

**Comment by Chillee** [comment]
@michaelbenayoun I will re-take a look/merge it soon.

If it's possible, could you add a test? Otherwise, I'd be glad to add a test for you :)

**Pull request closed without merging**
