### PR TITLE
[quant][bc-breaking][improvements] Removed quantized_max_pool2d registration

### PR DESCRIPTION
**Pull request by dzdang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #75305
* #75261
* __->__ #75304
* #72353

Summary: This PR is part of a series of PRs addressing https://github.com/pytorch/pytorch/issues/54150,
related to using dispatcher for calls to quantized backends as opposed to if/else conditionals.
quantized_max_pool2d has
been removed from the frontend, which was previously not used anyways, after introducing
max_pool2d_with_indices support for quantized tensors.

BC-breaking note:
Previous:
```
import torch
x = torch.rand(1, 1, 1, 1)
qx = torch.quantize_per_tensor(x, scale=0.5, zero_point=0, dtype=torch.qint8)
max_pooled_qx = torch.quantized_max_pool2d(qx, kernel_size=1)
print(qx)
print(max_pooled_qx)
```

Result:
```
tensor([[[[1.]]]], size=(1, 1, 1, 1), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.5, zero_point=0)
tensor([[[[1.]]]], size=(1, 1, 1, 1), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.5, zero_point=0)
```

After:
```
import torch
x = torch.rand(1, 1, 1, 1)
qx = torch.quantize_per_tensor(x, scale=0.5, zero_point=0, dtype=torch.qint8)
max_pooled_qx = torch.max_pool2d(qx, kernel_size=1)
print(qx)
print(max_pooled_qx)
```

Result:
```
tensor([[[[1.]]]], size=(1, 1, 1, 1), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.5, zero_point=0)
tensor([[[[1.]]]], size=(1, 1, 1, 1), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.5, zero_point=0)
```

Test plan:
```
python test/test_quantization.py -k test_max_pool2d
```

Differential Revision: [D35421467](https://our.internmc.facebook.com/intern/diff/D35421467)

### CODE REVIEW

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35421467).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35421467).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35421467).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35421467).

**Comment by jerryzh168** [comment]
for bc-breaking things, we need to add bc-breaking notes, example: https://github.com/pytorch/pytorch/pull/70009

**Comment by dzdang** [comment]
> for bc-breaking things, we need to add bc-breaking notes, example: #70009

@jerryzh168  Added. can you approve?

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35421467).

**Review by jerryzh168 — APPROVED** [review]
looks great

**Comment by jerryzh168** [comment]
I think we probably don't need to show the case where it errors out, just need to say previously if we are doing A, now we need to do B

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35421467).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35421467).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35421467).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35421467).

**Pull request closed without merging**
