### PR TITLE
[ROCm] Update triton pin to fix libtanh issue

### PR DESCRIPTION
**Pull request by pragupta**
There were some internal build issues related to tanh when we moved to upstream triton in ROCm. These issues were fixed by the following triton commit: https://github.com/triton-lang/triton/pull/3810 . This PR moves the triton pin to incorporate that change. Added some skips for unit tests that regressed due to the triton commit bump in this PR.

Needs https://github.com/pytorch/pytorch/pull/127968 since this PR introduces a triton dependency on llnl-hatchet, which doesn't have py3.12 wheels available currently.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by pruthvistony** [comment]
Job failing - https://github.com/pytorch/pytorch/actions/runs/8926129976/job/24521045613

Container killed due to more memory usage. - Exit code 137.

**Comment by alexbaden** [comment]
The `2024-05-02T19:59:51.5833790Z AssertionError: target must be of GPUTarget type` failures are fixed by https://github.com/pytorch/pytorch/pull/125241

**Review by pruthvistony — DISMISSED** [review]

**Review by nmacchioni — CHANGES_REQUESTED** [review]
To be honest, I don't think we should land this given that a lot of the ROCm tests are broken and therefore don't provide potentially actionable signal to this diff. Can we work on fixing those tests first?

**Comment by pruthvistony** [comment]
@malfet @nmacchioni ,
Can you please review this PR.

The failiing job
"linux-focal-cuda12.4-py3.10-gcc9 / test (default, 3, 5, linux.4xlarge.nvidia.gpu)" is also marked unstable now.

All the failures are NOT related to this change.

**Review by nmacchioni — DISMISSED** [review]
Thanks for the update and fixing those signals!

**Comment by atalman** [comment]
hi @pragupta Here is the breakage: https://github.com/pytorch/pytorch/actions/runs/9314625823/job/25644051315

Looks like there is new dependency being added with this PR, please specify the dependency so we can upload it to our index, we can reland this PR after

**Comment by nmacchioni** [comment]
Looks like the change is here: https://github.com/triton-lang/triton/commit/d830823914664303234cce00924c98d72ce1b72c
New package needed: "llnl-hatchet" https://github.com/LLNL/hatchet

**Comment by pragupta** [comment]
Yes, it seems we need to mirror llnl-hatchet in download.pytorch.org

**Review by malfet — APPROVED** [review]

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
@atalman @jithunnair-amd ,
Thanks for taking care of llnl-hatchlet dependency. I believe now this PR should be good to be merged.

**Pull request closed without merging**
