### PR TITLE
[Inductor Cutlass backend] Disable Cutlass backend, split and add tests

### PR DESCRIPTION
**Pull request by kadeng**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #119701
* #119600
* #119009
* #119008
* #119601
* #119007
* __->__ #119598
* #119597
* #119006
* #119004
* #120620

* Disables the Cutlass backend via _DISABLE_CUTLASS_BACKEND
feature flag
 * Splits the Cutlass backend related unit tests out of test_max_autotune.py into
 test_cutlass_backend.py
 * Adds a lot of new Cutlass backend specific tests, including those
 covering enhanced epilogue fusion ( follows in the next PRs )

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
> I'm a bit confused at this PR.  Is this just refactoring stuff to a different file?  Are there any other changes in it?  Why are we flipping the flag in the same PR?

It's understandable that this looks a bit confusing. Since I splitted it up into multiple PRs, the tests need to be green for all intermediate commits, *and* I need to stay below 2000 LOC change per PR. 

So, in order to achieve that I have split off the tests into this PR and put them in the PR stack below the implementation of the features which they test.  But that means they will fail, so I needed to disable them until the functionality is there.
 
While doing this, I also did something that is preferable anyway: I split off the Cutlass backend specific tests from the general max autotune related tests for all backends. So that's a minor refactoring.

So what resulted are these main changes:

 * Factor out the Cutlass backend specific tests to a separate test file.
 * Add new tests, which will only turn green with the changes in the next PRs in the stack.
 * Disable the Cutlass backend and the cutlass specific tests which are not yet working.

As to why the change to the feature flag is not in an entirely separate PR: This is just to place less load on the CI infra.

In the following PR, I will then make some changes to the Cutlass backend. But I can't make it work yet, that would require more than 2000 LOC change. So I keep the Cutlass backend and the tests disabled.

Only once all the changes are in there  and the Cutlass backend is functional again, I can reenable it and also enable all the new tests.

**Comment by jansel** [comment]
I didn't write the comment above.  It looks like you edited my comment @kadeng to add your response?  Please don't do that in the future.

**Review by jansel — CHANGES_REQUESTED** [review]
Please factor this stack into multiple PRs for real.  Splitting it out this way is not helpful.  I don't think we should land a bunch of tests that are broken because the code they reference doesn't exist yet.

**Comment by kadeng** [comment]
Closing. The PR stack is being restructured here: https://github.com/pytorch/pytorch/pull/121492

**Pull request closed without merging**
