### PR TITLE
Fix/device type prefixed with c10 namespace in headers

### LINKED ISSUE #91338: Use c10 namespace in public headers for classes like DeviceType (and Device ?)
### 🚀 The feature, motivation and pitch

We have an existing DeviceType class all over the place in our code base, and it conflicts with the one that is used in torch. Thankfully the pytorch DeciceType enum class is under the c10 namespace.

```
In file included from /xxx/build/_deps/torch-src/../../aten/src/ATen/ops/view.h:5:
/xxx/_deps/torch-src/aten/src/ATen/Context.h:265:14: error: reference to 'DeviceType' is ambiguous
    if (p == DeviceType::HIP) {
             ^
/xxx/include/Common_types.h:178:8: note: candidate found by name lookup is 'DeviceType'
struct DeviceType {
       ^
/xxx/build/_deps/torch-src/c10/../c10/core/DeviceType.h:32:12: note: candidate found by name lookup is 'c10::DeviceType'
enum class DeviceType : int8_t {
```

### Alternatives

_No response_

### Additional context

_No response_

cc @jbschlosser @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

### PR DESCRIPTION
**Pull request by bsergean**
Fixes #91338

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Comment by bdhirsh** [comment]
Looks ok to me! Can you sign the CLA?

**Comment by bsergean** [comment]
Thanks Brian ! 
I’ll sign the CLA soon, I’m on break right now.

**Review by albanD — COMMENTED** [review]
Sounds good.
Could you also add a lint entry for this to make sure we don't add new ones.
It can be similar to the one below I think:
https://github.com/pytorch/pytorch/blob/dfb651452a8365a1010c63e7ace01af554ab0358/.lintrunner.toml#L766-L785

**Comment by bsergean** [comment]
Hi there, would it be OK to bring this in without the linter as a start ? And make adding the linter rule a follow-up ?

I can make a new PR with the latest state of the master branch.

**Pull request closed without merging**
