### PR TITLE
[HigherOrderOp] remove _deprecated_global_ns

### PR DESCRIPTION
**Pull request by ydwu4**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #112757

As titled.

Test Plan:
existing test.

cc @zou3519

Differential Revision: [D51032385](https://our.internmc.facebook.com/intern/diff/D51032385)

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Comment by ydwu4** [comment]
@ydwu4 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51032385).

**Comment by ydwu4** [comment]
@ydwu4 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51032385).

**Review by zhxchen17 — APPROVED** [review]

**Comment by ydwu4** [comment]
Replaced by https://github.com/pytorch/pytorch/pull/113813

**Pull request closed without merging**
