### PR TITLE
Move XLA test job to 4xlarge

### PR DESCRIPTION
**Pull request by huydhn**
Per the discussion with @clee2000 , I'm trying to look into XLA flaky failures.  It's tricky because the runner crashes losing all the logs.  The only guess I have comes from the test insight information of XLA test job, i.e. https://hud.pytorch.org/test/insights?jobName=linux-bionic-py3_7-clang8-xla%20%2F%20test%20(xla%2C%201%2C%201%2C%20linux.2xlarge)&workflowId=3919472559&jobId=10650151864

* Memory looks fine. It peaks at ~14GB when building, then dropping when testing
* CPU spikes at 100% at the end, which I suspect to be the reason causing the runner to crash

So the fix is to try to limit the test to nCPU - 1, so there is always one core left for the runner.

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM, though can you please print `nproc` to validate what it is? (I remember some VM solutions return nproc of hw runner rather than of VM instance)

Another ideas:
 - Why not move the XLA runner to a bigger instance?
 - Process is usually killed due to out-of-memory (i.e. kernel picks process with idle process with lots of resident memory)
 - Would adding a swap partition help? (I know it's weird, but why not...)

**Comment by huydhn** [comment]
> LGTM, though can you please print `nproc` to validate what it is? (I remember some VM solutions return nproc of hw runner rather than of VM instance)

Noted, I'll print this

> * Why not move the XLA runner to a bigger instance?

Yeah, that's original idea.  I even called my branch `xla-4xlarge`, but decide to try this out first to see if it helps and how much TTS is increased because of this.  x2 the instance is there as the backup plan.
 
>     * Process is usually killed due to out-of-memory (i.e. kernel picks process with idle process with lots of resident memory)
>     * Would adding a swap partition help? (I know it's weird, but why not...)

The memory profile looks kind of ok during testing https://hud.pytorch.org/test/insights?jobName=linux-bionic-py3_7-clang8-xla%20%2F%20test%20(xla%2C%201%2C%201%2C%20linux.2xlarge)&workflowId=3919472559&jobId=10650151864, so I suspect that memory is not an issue.  If the crash happened when building XLA, then memory could be the cause.

**Comment by huydhn** [comment]
My attempt to fix the issue doesn't work as I can still see crashing runner issue with XLA in the PR.  As such, I'll adopt the easier fix of upgrading the runner to the next tier of `4xlarge` as @malfet suggests

**Pull request closed without merging**
