### PR TITLE
Fix win mkldnn

### PR DESCRIPTION
**Pull request by bstriner**
Hi Everybody!

Error in windows build if mkldnn is enabled because `build_pytorch_libs.bat` doesn't understand the argument `--with-mkldnn`. This argument works on Linux but not Win. This PR fixes the windows build so it can use MKLDNN.

I synced the command line parsing and the ATen cmake command between the batch script and the bash script. It looks like ATen is now correctly building with MKLDNN on Windows.
- https://github.com/pytorch/pytorch/blob/master/tools/build_pytorch_libs.sh
- https://github.com/pytorch/pytorch/blob/master/tools/build_pytorch_libs.bat

Warning: I just brought in all of the options from Linux build that were missing in the Windows build, so I'm trusting that that code is correct. Would appreciate if anyone can give them a once-over.
- Not sure about whether `ATEN_NO_CONTRIB` and `CMAKE_EXPORT_COMPILE_COMMANDS` should be set or not. The latter shouldn't really matter but the former might make a difference.
- I added the command line parsing for gloo and distributed-mw while I was putting in mkldnn but these are not fully implemented. Maybe should print a warning or something. 
- The other build commands in that script probably also need some work, the MKLDNN issue just happened to be causing a problem in my specific situation. Not sure if there is some good way to synchronize the two or figure out something more OS independent. Why do we need the two shell scripts at all instead of just python? A lot of overhead with environment variables and command line parsing that could be avoided.

Cheers

### CODE REVIEW

**Comment by bstriner** [comment]
One job failed on `ClosedChannelException`. Can someone restart that job? Thanks!

**Review by peterjc123 — APPROVED** [review]
LGTM. About your questions,
1. It doesn't matter. Just about the compiling of the two files which is on by default.
2. Yes, would you please do that?
3. That's definitely true. We should add some scripts here, just like `run_test.py`. I don't know whether a CMake script or Python code will be better here.

**Comment by bstriner** [comment]
@peterjc123 added warnings for gloo iverbs and mw distributed not being implemented yet, but the parameters are eaten so the builds should still succeed if those options are set.

This PR also adds `WITH_ROCM`. Seems like it should work as-is but haven't tried it and have no plans to.

Consider this a short-term fix to get windows build more in-sync with linux. Probably needs a rewrite so python can call cmake directly, which should be os-independent.

**Comment by soumith** [comment]
@peterjc123 after a rebase, can this be merged?

**Comment by soumith** [comment]
@bstriner can you please rebase, there are merge conflicts

**Comment by peterjc123** [comment]
@soumith Sure.

**Review by peterjc123 — APPROVED** [review]

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
windows failure looks legit. cc: @peterjc123

**Comment by peterjc123** [comment]
@ezyang Specifying /EHSc as a compiler flag in onnx build process will solve this issue.

**Comment by bstriner** [comment]
Seems like /EHa would be preferred, but would need to test the build. Not sure exactly if ehsc or eha is going to be better. I can try locally, but not sure I'll see the same errors as CI.

That warning is actually given for almost anything, so maybe just need to add that to CXX for everybody.

**Comment by bstriner** [comment]
Now windows CI builds correctly, but 1134 passed, 1 failed: `test_PReLU_3d_multiparam_cuda`. Looks like there were a lot of recent build changes, which broke master for me locally. Maybe there are some other issues but I don't think the build is going to be completely stable until the .bat and .sh logic are merged into a single file.

I'll post if I figure out what the `test_PReLU_3d_multiparam_cuda` issue is all about.

**Comment by ezyang** [comment]
The Prelu problem is a known flaky test. It should be working on master. Let' stry again.

@pytorchbot retest this please

**Comment by bstriner** [comment]
@ezyang actually figured out my problem with master was the way options propagate to protobuf. Fix is here: https://github.com/pytorch/pytorch/pull/8184

Any thoughts on what needs to be fixed for a more consistent tests? Seems like tests need to rerun a lot.

It would be great to write a single `build_pytorch_libs.py` to replace the separate sh and bat, but both of those files change so frequently, it will be hard to do without conflicts. Also, a lot of different ways to organize that refactor.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
For the prelu, someone just needs to just fix the damn flaky test ^^"

It would be really good to get rid of the two separate files. Another possibility is to write a single cmake to put them all together. @orionr do you have designs on this file?

**Pull request merged**
