### PR TITLE
[MPS] Fixes GELU, LeakyRELU and MISH on non-contiguous tensors

### LINKED ISSUE #98212: Wrong results for GELU forward pass (CPU vs MPS) while  inferencing a GLPN model from huggingface
### 🐛 Describe the bug

Hi, there. I've discovered strange behaviour when using MPS device. When infer the same model with the same input on "mps" device, the result is numerically wrong and meaningless. 
@amyeroberts from huggingface narrowed down the scope of the problem to GELU layer, more information is here: https://github.com/huggingface/transformers/issues/22468

The issue makes it impossible to use GLPN architecture with MPS device.

Here are some examples:

MPS            |  CPU
:-------------------------:|:-------------------------:
  |  

Thanks in advance for the help!

### Versions

PyTorch version: 2.1.0.dev20230329
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.6 (default, Mar 10 2023, 20:16:38)  [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0.dev20230329
[pip3] torchaudio==2.1.0.dev20230329
[pip3] torchvision==0.16.0.dev20230329
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

### PR DESCRIPTION
**Pull request by jtang98**
Fixes GELU, LeakyRELU and MISH activation functions on non-contiguous tensors (for instance, when a transpose operation was applied on the tensors prior to the MPS operator), forward and backward passes.

I also extended tests on the 3 activation functions to check: full-precision and half-precision, contiguous and non-contiguous, and several dims of tensors: scalars, 1D, empty, 2D, > 3D.

I had issues with Mish and GELU activations when asserting the gradients vs. CPU with sum() on some cases, so I reverted to the previous setup by setting a gradient parameter on .backwards().
This PR also fixes an issue with LeakyRELU on empty tensors.

Fixes #98212 huggingface/transformers#22468 huggingface/transformers#19353

### CODE REVIEW

**Comment by jtang98** [comment]
@malfet @kulinseth Could you have a look? Thanks!

**Review by kulinseth — APPROVED** [review]

**Comment by jtang98** [comment]
A test failed but it seems unrelated to this PR, should I rebase?

**Comment by kulinseth** [comment]
> A test failed but it seems unrelated to this PR, should I rebase on viable/strict?

Test is indeed unrelated, i have kicked off a rebase.

**Pull request closed without merging**
