### PR TITLE
Make torch.floor_divide error on negative results

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #63011

This is the next step of #43874, changing `floor_divide` to be Python/NumPy compatible. The function
now raises an error when the result is negative which is when the result may be rounded differently.

### CODE REVIEW

**Comment by mruberry** [comment]
fyi not losing track of this but working on an update to our BC/FC policies to accommodate the PyTorch ecosystem

**Comment by peterbell10** [comment]
>fyi not losing track of this but working on an update to our BC/FC policies to accommodate the PyTorch ecosystem

@mruberry any updates on this?

**Comment by mruberry** [comment]
> > fyi not losing track of this but working on an update to our BC/FC policies to accommodate the PyTorch ecosystem
> 
> @mruberry any updates on this?

The JIT team is still developing an updated mechanism that will support these changes for torchscript and mobile. We expect it to be in January.

**Comment by peterbell10** [comment]
Closing as apparently we're skipping this step (#78411).

**Pull request closed without merging**
