### PR TITLE
remove the unimplemented to  handle bound method getting moved to another class

### LINKED ISSUE #137476: torch.compile graph break: torch._dynamo.exc.Unsupported: __self__ mismatch for bound method
### 🐛 Describe the bug

```python
import torch
import torch.nn as nn

def set_attrs_from_orig_model(cls_instance, mod, *func_names):
    cls_instance.__dict__.update(mod.__dict__)
    if func_names is not None:
        for func in func_names:
            setattr(cls_instance, func, getattr(mod, func))

class PatchedMyModule(nn.Module):
    def __init__(self, mod):
        super().__init__()
        set_attrs_from_orig_model(self, mod, "resolve_input")

    def forward(self, x):
        x = self.resolve_input(x)
        return x

class MyModule(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = nn.Linear(in_features=input_dim, out_features=output_dim)

    def resolve_input(self, x):
        x = torch.nn.Dropout(0.1)(self.linear(x))
        return x

    def forward(self, x):
        x = self.linear(x)
        return x

module = MyModule(input_dim=1, output_dim=1)
patched_module = PatchedMyModule(module)
compiled_module = torch.compile(patched_module, fullgraph=True)

input_tensor = torch.tensor([1.], dtype=torch.float)
res = compiled_module(input_tensor)
```
fail with: `torch._dynamo.exc.Unsupported: __self__ mismatch for bound method`

### Versions

torch==2.5.0.dev20240909+cpu

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @amjames @rec

### PR DESCRIPTION
**Pull request by LJ-underdog**
remove the unimplemented to  handle bound method getting moved to another class

Fixes #137476

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by zou3519 — CHANGES_REQUESTED** [review]
can you add a test please?

**Comment by intellinjun** [comment]
> can you add a test please?

Sure, but I'm not sure the placement of my additions makes sense

**Pull request closed without merging**
