### PR TITLE
Remove `set_default_dtype` from nn tests

### PR DESCRIPTION
**Pull request by kurtamohler**
Part of #68972

cc @mruberry

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert 'Sorry for reverting you change, it is failing one of the slow test in trunk' -c nosignal

https://hud.pytorch.org/pytorch/pytorch/commit/4d6a891baf2224cfa81bfe7632cf08be50812216, the error is `FAILED [0.3616s] test_nn.py::TestNN::test_softmax_spatial_special - torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 0`

**Comment by kurtamohler** [comment]
@huydhn, thanks for letting me know and for providing a log! I'll fix it and resubmit shortly

**Comment by huydhn** [comment]
As this is a slow test, you would likely need to attach `cilfow/slow` on your fix to let it run on CI to confirm.

**Pull request closed without merging**
