### PR TITLE
TS jit 2 week compatibility window for new TEL forward()

### PR DESCRIPTION
**Pull request by mikekgfb**
Summary: TS jit 2 week compatibility window for new TEL forward()

Test Plan: sandcastle

Differential Revision: D38711177

### CODE REVIEW

**Review by erichan1 — APPROVED** [review]
LGTM! I thought hard about whether adding the TS compatibility would break new users that attempt to script, but think we are fine since the last argument is optional.

**Review by jbschlosser — APPROVED** [review]
LGTM

**Pull request closed without merging**
