### PR TITLE
Allow torch.tril / triu to handle bool and half inputs

### LINKED ISSUE #24035: triu not implemented for Bool
I'm getting the error [title] with the latest nightly build.  I was doing

```python
torch.ones(n, m, dtype=torch.uint8).triu_() 
```
to get an upper-triangular mask, but now I'm getting a deprecation warning about using tensors other than booleans in `torch.masked_scatter`, so I changed the above to

```python
torch.ones(n, m, dtype=torch.bool).triu_()
```
which now fails with `RuntimeError: "triu" not implemented for 'Bool'`.  Is this known and/or WIP?

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:
- Enable torch.tril / triu for bool and float16 dtypes

Test Plan:
- Tests added in test_torch.py for all devices and dtypes (except bfloat16)

Fixes #24035

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by vishwakftw** [comment]
@soumith Please don't merge it just yet; `torch.testing.get_all_dtypes()` doesn't contain `torch.float16`. I'll push a commit for this.

**Review by soumith — DISMISSED** [review]
dismiss review once ready

**Comment by vishwakftw** [comment]
@soumith Sorry about the confusion, torch.float16 is included.

**Comment by vishwakftw** [comment]
@soumith is this good to go?

**Review by soumith — APPROVED** [review]

**Comment by zou3519** [comment]
I think this needs a rebase. Not sure if pytorchbot can do this automatically

**Comment by vishwakftw** [comment]
Rebased, should be good to merge now.

**Pull request closed without merging**
