### PR TITLE
Avoid problematic pickle usages on Python 3.8.0 and 3.8.1

### LINKED ISSUE #32289: Python 3.8 serialization error
## 🐛 Bug

Error text:
```pytb
======================================================================
ERROR: test_serialization_filelike_api_requirements (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_torch.py", line 4446, in test_serialization_filelike_api_requirements
    _ = torch.load(filemock)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\serialization.py", line 590, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\serialization.py", line 754, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
TypeError: file must have 'read', 'readinto' and 'readline' attributes

======================================================================
ERROR: test_serialization_filelike_missing_attrs (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_torch.py", line 4473, in test_serialization_filelike_missing_attrs
    self._test_serialization_filelike(to_serialize, mock, desc)
  File "test_torch.py", line 4458, in _test_serialization_filelike
    b = torch.load(data)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\serialization.py", line 590, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\serialization.py", line 754, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
TypeError: file must have 'read', 'readinto' and 'readline' attributes

======================================================================
ERROR: test_serialization_filelike_stress (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_torch.py", line 4479, in test_serialization_filelike_stress
    self._test_serialization_filelike(a, lambda x: FilelikeMock(x, has_readinto=False),
  File "test_torch.py", line 4458, in _test_serialization_filelike
    b = torch.load(data)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\serialization.py", line 590, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\serialization.py", line 754, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
TypeError: file must have 'read', 'readinto' and 'readline' attributes

----------------------------------------------------------------------
Ran 3620 tests in 103.071s
```

## To Reproduce

1. python test_torch.py

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): e4db0a5
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py build
 - Python version: 3.8
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @peterjc123 @suo

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #32289 

This has been fixed upstream as of Python 3.8.2. I think the easiest and least invasive way to ameliorate this is to catch the error condition and print a more informative error asking the user to update their Python version. It might be possible to buffer the data into memory and then read from memory, but that would be an invasive change and might cause memory exhaustion for very large models.

Suggestions for alternate fixes or ways to improve the error message wording are very welcome.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by driazati** [comment]
Our serialization already uses `read` instead of `readinto` for Python 2, could we do that instead and turn the error here into a warning the `load` will be slow until they upgrade to 3.8.2?

**Comment by ngoldbaum** [comment]
Sorry can you elaborate a bit more? Where’s the code path that doesn’t go through `pickle.load`?

**Comment by driazati** [comment]
Sorry I thought this was referring to our use of `read`/`readinto` for loading tensors. Regardless, couldn't we do something like was suggested in the bug 
```python
if isinstance(f, mmap.mmap):
    f = memoryview(f)
```
at the top of `torch.load` so it's not a hard error?

**Comment by ngoldbaum** [comment]
I tried that and I couldn't get it to work, something about the multiple calls to `pickle.load` made the `protocol_version` not come out correctly. You also need to replace `pickle.load` with `pickle.loads` in the case when `f` is an `mmap.mmap`, which makes it a more invasive change than just the single `if` block.

**Comment by ngoldbaum** [comment]
If you want to take your hand at it, a real-world example from the flair library that will trigger this codepath is:

```
from flair.models import SequenceTagger
tagger = SequenceTagger.load('ner')
```

**Pull request closed without merging**
