### PR TITLE
[inductor] consider pointwise nodes when deciding reduction hint

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #124131

In certain **rare** scenarios, inductor can generate a reduction kernel with really bad perf. E.g., if 
- the reduction kernel contains a reduction node followed by a pointwise node
- And the pointwise node use a transposed layout. 
- the reduction node is an inner reduction
- and rnumel <= 1024 , 

then inductor will generate a persistent reduction kernel and it causes really bad perf when doing tl.store for the pointwise node since we use a very skinny tile `(XBLOCK=1, RBLOCK=next_power_of_2(rnumel))` .

I've tried a few version of fix.
- The first version is, if I found any pointwise node in a reduction kernel uses a non-contiguous dependency, we use ReductionHint.DEFAULT. This cause 8s compilation time increase for huggingface with no perf wins... The reason is ReductionHint.DEFAULT does more autotunings.
- Then I changed the code to be more specific. We change the hint from INNER to DEFAULT if we are sure that the pointwise kernel can use a >1 stride for the lowest dimension. Kernels meet this condition should mostly have really bad perf anyways.

The situation mentioned above is rare. But it's reported by internal users. I'll also run one more perf test.

Testing script: https://gist.github.com/shunting314/9d3389891fa43633b49b8b7564ad6d8b . Something equivalent is also added as a unit test.

For this specific test from user reports, we improve the mentioned reduction kernels perf by **4.14x** (451us -> 109us)

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
Test failures?

**Comment by shunting314** [comment]
yea, I also see similar failures on the dashboard run (3 model fails). Will debug that.

Also, looks like I need skip the unit test on A100 since triton does not support fp8 on A100.

**Comment by shunting314** [comment]
The failures about build are unrelated to this PR.

**Comment by shunting314** [comment]
Neutral on the [dashboard](https://hud.pytorch.org/benchmark/compilers?startTime=Fri%2C%2012%20Apr%202024%2017%3A21%3A26%20GMT&stopTime=Fri%2C%2019%20Apr%202024%2017%3A21%3A26%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=gh/shunting314/134/head&lCommit=b157b03cde36c1eb4aa41812919a9fb572f99016&rBranch=main&rCommit=bb0c768c5b4d6c76c77f287ed5e4b6c7be43d1a9)

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
