### PR TITLE
[RFC] Make fr trace script a console scripts

### PR DESCRIPTION
**Pull request by fduwjj**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134729
* #134780
* #134528

We want to make fr analyzer script a command after users `pip install torch`, that's why we want to mimic what torchrun is doing.

### CODE REVIEW

**Review by c-p-i-o — APPROVED** [review]
LGTM.

**Review by malfet — APPROVED** [review]
Looks good to me, though please consider having a shorter tool name. Say `torchflightrecorder` or something like that. And perhaps it makes sense to make it conditional on whether or not PyTorch is built with distributed support.

**Comment by fduwjj** [comment]
@malfet that sounds great, do you know how to make it conditional? I definitely want to add a flag to this command.

**Pull request closed without merging**
