### PR TITLE
set num_warps to at least 4

### PR DESCRIPTION
**Pull request by ngimel**
To avoid IMAs in https://gist.github.com/ngimel/25e81c996d9c8c652d97e33cc9c7d5f4
This is not a general fix (e.g. if inputs were a bit larger, num_warps would naturally be 4, and we could still have spills and hit ptxas bugs), but will do for now. 
Longer term, we should check spills in kernels we generate and recompile with more warps if there are spills. 

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by bertmaher — APPROVED** [review]
Would you mind adding a comment pointing to this PR?  I could see it being useful to easily find a repro for this issue at some point in the future, maybe.  You could also consider adding your gist as a test case so it's easy to check for this bug in the future.

**Comment by bertmaher** [comment]
Incredible debugging by the way, I have no idea how you figured this out :-D

**Comment by ngimel** [comment]
All credit goes to @Jokeren

**Pull request closed without merging**
