### PR TITLE
Corrected grammar in contribution guide

### PR DESCRIPTION
**Pull request by atharvakavitkar**
Corrected the grammar of a sentence in "Implementing Features or Fixing Bugs" section of the contribution guide.

**Before:**
Issues that are labeled first-new-issue, low, or medium priority provide the best entrance point are great places to start.

**After:**
Issues that are labeled first-new-issue, low, or medium priority provide the best entrance point _and_ are great places to start.

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by albanD** [comment]
Could you make sure to have your git user.email set to the same email as your github account and follow the link for the CLA please?

**Comment by albanD** [comment]
You'll need to remove the old commit that is not properly signed from the branch.
Or create a new branch with only the new commit and open a new PR.

**Comment by atharvakavitkar** [comment]
Could you please approve the workflows as a maintainer @albanD? The merging will be blocked until the remaining workflows are approved.

**Review by kit1980 — APPROVED** [review]

**Comment by atharvakavitkar** [comment]
Why is the status of the PR 'closed' if [pytorchmergebot](https://github.com/pytorchmergebot) has already merged it? Shouldn't the status get changed to 'merged'?

**Comment by kit1980** [comment]
> Why is the status of the PR 'closed' if [pytorchmergebot](https://github.com/pytorchmergebot) has already merged it? Shouldn't the status get changed to 'merged'?

Because of the implementation of the merging in the PyTorch repo, the GitHub PR status is "closed" instead of "merged" for all (with extremely rare exceptions)  for all of the landed PRs.

**Pull request closed without merging**
