### PR TITLE
exponential_ few fixes (1) lambda > 0 (2) mkl kernel to continuous (3) better error log on dtype

### PR DESCRIPTION
**Pull request by min-jean-cho**
Exponential distribution is continuous. Fixes CPU MKL exponential implementation to exclude integer dtypes. 

```python
import torch
dtypes = [torch.uint8, torch.int8, torch.int16, torch.int32, torch.int64]

for dtype in dtypes:
    x = torch.empty(10000, dtype=dtype).exponential_() # should fail !
    print("dtype: ", x.dtype, "sum: ", x.sum())
```

### Additional Context 

Related to #92709. This issue propagates to OpInfo of exponential.

```
AssertionError: The supported dtypes for exponential on device type cpu are incorrect!
The following dtypes worked in forward but are not listed by the OpInfo: {torch.int64, torch.uint8, torch.int8, torch.int16, torch.int32}.
```

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
Could you also add a `TORCH_CHECK` throwing a more informative error?

**Review by CaoE — APPROVED** [review]

**Comment by min-jean-cho** [comment]
Thanks @lezcano, should we add such check for other exponential distribution implementations as well? Currently, the error is `exponential_{device} not implemented for {dtype}` for the default cpu, cuda as well as cpu mkl implementations.

**Comment by lezcano** [comment]
Yeah, that'd be great! If this was implemented properly, all the checks would be shared by all the implementations and then we would dispatch to the actual backend, but I guess this is not the case.

**Review by jgong5 — APPROVED** [review]

**Comment by min-jean-cho** [comment]
Thanks @lezcano, I've (1) added better error log on dtype (2) fixed `lambda >= 0` to `lambda > 0`  as discussed in #93053. Please have a look, thanks!

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
