### PR TITLE
[FX] BC guarantees for 1.10

### PR DESCRIPTION
**Pull request by jamesr66a**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #63888

This PR adds a new decorator, `torch.fx._compatibility.compatibility` and applies it liberally to classes, methods, and functions in the FX codebase. This decorator does several things:

1) It takes in a flag that specifies whether this API is under a BC guarantee or not
2) It appends an appropriate notice to the API's docstring specifying the BC guarantees
3) It gathers BC APIs in a data structure for further testing so we can enforce BC in development

Backward-compatible API docs example:

image

Backward-incompatible API docs example:

image

TODO:

- [x] Verify that docstrings are rendering properly in the docs
- [x] Add functionality to probe the public API surface of the `torch.fx` namespace and flag APIs that are not marked as BC compatible/incompatible
- [x] ~Can't test properties because mypy explodes on them~ Don't care because public API test will catch it
- [x] Fix indentation on auto-docstring stuff
- [x] Make class method check subtract out members from base class
- [x] ~Weird mypy failure in quantization code?~ added a dumb assert
- [x] Add error messages for all these checks describing what to do 
- [x] Fix inline TODOs

Differential Revision: [D30523133](https://our.internmc.facebook.com/intern/diff/D30523133)

### CODE REVIEW

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30523133).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30523133).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30523133).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30523133).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30523133).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30523133).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30523133).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30523133).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30523133).

**Review by Chillee — APPROVED** [review]
LGTM

**Pull request closed without merging**
