### PR TITLE
[aotautograd] remove relative imports

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #115334

Relative imports break a lot of tooling. They are unnecessary here, so kill them.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

Differential Revision: [D52040510](https://our.internmc.facebook.com/intern/diff/D52040510)

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
thanks!

**Comment by suo** [comment]
@suo has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D52040510).

**Comment by suo** [comment]
give up on this

**Pull request closed without merging**
