### PR TITLE
Revert D58333770: Multisect successfully blamed "D58333770: [cuDNN][SDPA] Remove `TORCH_CUDNN_SDPA_ENABLED=1`, enable cuDNN SDPA by default on H100 and 2nd on other archs >= sm80 (#125343)" for one test failure

### PR DESCRIPTION
**Pull request by eellison**
Summary:
This diff reverts D58333770
D58333770: [cuDNN][SDPA] Remove `TORCH_CUDNN_SDPA_ENABLED=1`, enable cuDNN SDPA by default on H100 and 2nd on other archs >= sm80 (#125343) by generatedunixname499836121 causes the following test failure:

Test Plan: NA

Reviewed By: henryhu6

Differential Revision: D58459221

### CODE REVIEW

**Comment by eqy** [comment]
Is there a repro available for this?

**Comment by eqy** [comment]
Thanks I'll take a look---it's a bit surprising though as I thought that failure went away when dispatching with nested tensors was removed

**Comment by eellison** [comment]
If that's not sufficient, lmk, I can find something better. I'm not sure that we have h100 tests running, so testing might need to be adhoc :/ cc @seemethere to correct me

This was the stack trace if it helps:

```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: RuntimeError: CUDNN_BACKEND_TENSOR_DESCRIPTOR: Check and Set the CUDNN_ATTR_TENSOR_STRIDES Correctly cudnn_status: CUDNN_STATUS_BAD_PARAM
  target: aten._scaled_dot_product_cudnn_attention.default
  args[0]: TensorBox(
    View(
      View(
        StorageBox(
          ComputedBuffer(name='buf63', layout=FixedLayout('cuda', torch.bfloat16, size=[2, 8, 9216, 64], stride=[4718592, 589824, 64, 1]), data=Pointwise(
            'cuda',
            torch.bfloat16,
            def inner_fn(index):
                i0, i1, i2, i3 = index
                tmp0 = ops.load(buf60, i3 + 64 * i1 + 512 * i2 + 4718592 * i0)
                return tmp0
            ,
            ranges=[2, 8, 9216, 64],
            origin_node=clone_5,
            origins={clone_5}
          ))
        ),
        size=[16, 9216, 64],
        reindex=lambda i0, i1, i2: [ModularIndexing(i0, 8, 2), ModularIndexing(i0, 1, 8), i1, i2],
        origins={clone_5, view_16}
      ),
      size=[1, 16, 9216, 64],
      reindex=lambda i0, i1, i2, i3: [i1, i2, i3],
      origins={unsqueeze_27}
    )
  )
  args[1]: TensorBox(
    View(
      View(
        StorageBox(
          ComputedBuffer(name='buf64', layout=FixedLayout('cuda', torch.bfloat16, size=[2, 8, 9216, 64], stride=[4718592, 589824, 64, 1]), data=Pointwise(
            'cuda',
            torch.bfloat16,
            def inner_fn(index):
                i0, i1, i2, i3 = index
                tmp0 = ops.load(buf61, i3 + 64 * i1 + 512 * i2 + 4718592 * i0)
                return tmp0
            ,
            ranges=[2, 8, 9216, 64],
            origin_node=clone_6,
            origins={clone_6}
          ))
        ),
        size=[16, 9216, 64],
        reindex=lambda i0, i1, i2: [ModularIndexing(i0, 8, 2), ModularIndexing(i0, 1, 8), i1, i2],
        origins={view_18, clone_6}
      ),
      size=[1, 16, 9216, 64],
      reindex=lambda i0, i1, i2, i3: [i1, i2, i3],
      origins={unsqueeze_25}
    )
  )
  args[2]: TensorBox(
    View(
      View(
        StorageBox(
          ComputedBuffer(name='buf65', layout=FixedLayout('cuda', torch.bfloat16, size=[2, 8, 9216, 64], stride=[4718592, 589824, 64, 1]), data=Pointwise(
            'cuda',
            torch.bfloat16,
            def inner_fn(index):
                i0, i1, i2, i3 = index
                tmp0 = ops.load(buf62, i3 + 64 * i1 + 512 * i2 + 4718592 * i0)
                return tmp0
            ,
            ranges=[2, 8, 9216, 64],
            origin_node=clone_7,
            origins={clone_7}
          ))
        ),
        size=[16, 9216, 64],
        reindex=lambda i0, i1, i2: [ModularIndexing(i0, 8, 2), ModularIndexing(i0, 1, 8), i1, i2],
        origins={clone_7, view_20}
      ),
      size=[1, 16, 9216, 64],
      reindex=lambda i0, i1, i2, i3: [i1, i2, i3],
      origins={unsqueeze_26}
    )
  )
  args[3]: False
```

**Comment by eellison** [comment]
reverted, elsewhere, closing

**Pull request closed without merging**
