### PR TITLE
[fx graph cache] FxGraphPickler: Remove hack to stabilize device string hashes

### PR DESCRIPTION
**Pull request by masnesral**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #136505
* #138683
* #138682
* __->__ #138681

Summary: With the fast pickling mode, we don't need the custom hack for replacing device strings in tensors. This was previously needed because, e.g., two strings "cuda" will pickle differently if they are the same object vs. not.

Test Plan:
The new test fails with fast mode commented out, but succeeds when enabled:
`python test/inductor/test_codecache.py -k test_stable_strings`

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by oulgen — APPROVED** [review]

**Review by eellison — COMMENTED** [review]
Where was the "fast pickling mode" added ? I'm not familiar

**Comment by oulgen** [comment]
@eellison https://github.com/pytorch/pytorch/commit/5ed72ff5f58716737cd932f08e842a39b896a5cb

we use it to make sure strings are interned the same way

**Comment by masnesral** [comment]
@jeanschmidt where can I find the failures?

**Comment by huydhn** [comment]
I think the failure is not related to this PR as it still shows up in trunk after the revert https://hud.pytorch.org/pytorch/pytorch/commit/36b7135c6ff7ed1be4203968888ba4dd7ddbb3c6.  The test was disabled by @kwen2501 few weeks ago in https://github.com/pytorch/pytorch/issues/137771 but the bot closed it earlier today, finding no failure there anymore.  Either that the bot is getting wrong info here, or maybe one of the recent distributed commit fixed it but was reverted.  Anyway, this can be reland as I have reopen https://github.com/pytorch/pytorch/issues/137771

**Pull request closed without merging**
