### PR TITLE
inductor: only do the conv+bn folding for the freezing path

### PR DESCRIPTION
**Pull request by XiaobingSuper**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #109270

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by eellison — APPROVED** [review]

**Comment by malfet** [comment]
See https://github.com/pytorch/pytorch/actions/runs/6214728169/job/16867038383 for example:
```
=================================== FAILURES ===================================
______ DynamicShapesCodegenCpuTests.test_conv_bn_fuse_dynamic_shapes_cpu _______
Unexpected success
- generated xml file: /var/lib/jenkins/workspace/test/test-reports/python-pytest/inductor.test_torchinductor_codegen_dynamic_shapes/inductor.test_torchinductor_codegen_dynamic_shapes-33d0126f830c1445.xml -
```

**Pull request closed without merging**
