### PR TITLE
[pytorch/et] Allow ET to save additional resources for completing a trace like generated kernels and index tensor data

### PR DESCRIPTION
**Pull request by sanrise**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #143430

The resources directory lets ET observer dump any additional data like Triton kernels while capturing the ET.

This allows us to use the ET trace to replay PT2 workloads and get visibility into data like generated kernels and their usage in a model, index tensor data etc.

We also added a few ways to enable ET and ET Resources through the OS environment variables.

Setting `ENABLE_PYTORCH_EXECUTION_TRACE` will enable default Execution Tracing in Pytorch.

Additionally setting `ENABLE_PYTORCH_EXECUTION_TRACE_EXTRAS` will enable ET to collect extra resources from the ET run like Triton Kernels.

Differential Revision: [D58707846](https://our.internmc.facebook.com/intern/diff/D58707846/)

### CODE REVIEW

**Comment by shengfukevin** [comment]
LG2M! Thanks for supporting this feature.

**Review by shengfukevin — APPROVED** [review]
Looks good to me! Thanks for supporting this.

**Review by sraikund16 — APPROVED** [review]

**Pull request closed without merging**
