### PR TITLE
Implement logistic distribution

### PR DESCRIPTION
**Pull request by alicanb**
@apaszke I'm missing KL(Logistic, Logistic). If anyone can come up with a closed form solution (@vishwakftw 😉 ), contributions welcome.

### CODE REVIEW

**Comment by gchanan** [comment]
I'm making a number of changes to test_distributions to add scalar support; let's not merge this until that is in.

**Review by apaszke — CHANGES_REQUESTED** [review]
LGTM, but you need to revert the submodule change

**Comment by alicanb** [comment]
@apaszke do you think we need logistic distribution? @fritzo and I were talking about this fits into HalfNormal category: easy to implement via `Transform`s, and not that commonly used.

**Comment by apaszke** [comment]
@alicanb I don't know which distributions are often used in practice, so I'm leaving the decision on the scope of `torch.distributions` to @fritzo. If there is a way to implement this as a transformed distribution, then I think we can skip it.

**Comment by fritzo** [comment]
I also don't know how often the `Logistic` distribution is used, but since it's so easy to define via `TransformedDistribution` it seems reasonable to leave it out. I think our effort would better spent honing the syntax of `TransformedDistribution` so that this is trivial to implement `Logistic`.

**Pull request closed without merging**
