### PR TITLE
Move torchbench model configuration into a YAML file.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #120299

This PR moves other aspects of torchbench's model configuration (e.g. batch size,
tolerance requirements, etc.) into a new YAML file: `torchbench.yaml`. It also merges the
recently added `torchbench_skip_models.yaml` file inside the `skip` key.

This is an effort so that external consumers are able to easily replicate the performance
results and coverage results from the PyTorch HUD.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @miladm

### CODE REVIEW

**Comment by ezyang** [comment]
Didn't I see another YAML PR? Is this the same thing?

**Comment by ysiraichi** [comment]
Yes. That was #120117. The difference is that we moved only skips to the YAML file. Now, we are moving every list/dict of models that we need for any specific configuration. We figured we would need those when trying to replicate PyTorch HUD results.

**Comment by ysiraichi** [comment]
It doesn't look like the CI failure is related to this PR.

**Comment by ysiraichi** [comment]
@ezyang @jansel This PR should be ready for review. Could you take a look at it when you have some time?

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
