### PR TITLE
record_function: remove legacy internal operators

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #104569
* #118526
* __->__ #72303
* #112153

These operators are not used in eager since #76420, and are only retained for TorchScript BC which has now expired.

BC-breaking message:

TorchScript exported models that use `torch.autograd.profiler.record_function` and were exported on PyTorch < `2.0` will no longer be loadable. Please re-export your model with 2.0 or newer.

### CODE REVIEW

**Comment by albanD** [comment]
Was there some perf issues related to this? I don't recall why this stalled?

**Comment by peterbell10** [comment]
@albanD the original deprecation PR had a performance issue that was resolved and re-landed. This PR just needed to wait the 2 release deprecation cycle which with our unusually low release cadence became a rather long wait.

**Review by albanD — APPROVED** [review]
SGTM
Just make sure to wait the BC window to merge.

**Comment by peterbell10** [comment]
According to [the BC Policy](https://github.com/pytorch/pytorch/wiki/PyTorch's-Python-Frontend-Backward-and-Forward-Compatibility-Policy/f7f581b7125e393951e40f670a880d3c145c368e#minimizing-the-disruption-of-bc-breaking-changes) we need 180 days and two pytorch releases. It's been almost a full year and the new behavior is in 2.0 and 2.1 so I think we're good.

@pytorchbot merge

**Comment by izaitsevfb** [comment]
cc @kit1980

**Pull request closed without merging**
