### PR TITLE
Release GIL when calling into JIT interpreter

### PR DESCRIPTION
**Pull request by apaszke**

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by zdevito** [comment]
I think `createPythonOperation` needs to have an AutoGIL in it.

**Comment by apaszke** [comment]
@zdevito I checked that, [and it already does](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/python_interpreter.cpp#L38).

**Comment by apaszke** [comment]
Ok, there's some pybind code outside, so I added an extra `AutoGIL` to be sure.

**Comment by zdevito** [comment]
Oh yeah, I missed that line.

**Pull request closed without merging**
