### PR TITLE
[Quant][PT2E] Re-enable test case of conv add/add_relu recipe for x86inductorquantizer

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105638

**Summary**
Re-enable the test case of `test_conv2d_binary_with_quantizer_api` and `test_conv2d_binary_unary_with_quantizer_api` for X86InductorQuantizer. We disable these 2 testcases previously due to the time out issue in internal CI.

**Test Plan**
```
python -m pytest test_x86inductor_quantizer.py -k test_conv2d_binary_with_quantizer_api
python -m pytest test_x86inductor_quantizer.py -k test_conv2d_binary_unary_with_quantizer_api
```

Differential Revision: [D47745372](https://our.internmc.facebook.com/intern/diff/D47745372)

### CODE REVIEW

**Comment by leslie-fang-intel** [comment]
Hi @jerryzh168, could you help to take a look of this PR? If the preCI time out issue has been fixed, I think we may re-enable these 2 PRs.

**Comment by jerryzh168** [comment]
OK, let me try importing this and see if it is fixed

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D47745372).

**Comment by leslie-fang-intel** [comment]
Hi @jerryzh168, Could you help to check the result of internal testing? Has the time out issue been resolved?

**Comment by jerryzh168** [comment]
looks like no errors, I think we can land

**Review by jerryzh168 — APPROVED** [review]

**Comment by leslie-fang-intel** [comment]
@jerryzh168 Could you help to land this PR? Looks like I can't land it with error message:
```
Reason: This PR has internal changes and must be landed via Phabricator
```

**Comment by jerryzh168** [comment]
that's weird, we don't have internal changes

**Comment by leslie-fang-intel** [comment]
> that's weird, we don't have internal changes

Thanks @jerryzh168.
From the error message:
```
Reason: This PR has internal changes and must be landed via Phabricator
```
Do you have any idea how to land it via Phabricator?

**Review by andrewor14 — APPROVED** [review]

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D47745372).

**Pull request closed without merging**
