### PR TITLE
Reenable AMP on XLA

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#61861 Reenable AMP on XLA**

Fixes https://github.com/pytorch/pytorch/issues/61804

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D29881903](https://our.internmc.facebook.com/intern/diff/D29881903)

### CODE REVIEW

**Comment by ezyang** [comment]
not sure what the easiest way to test this is

**Comment by JackCaoG** [comment]
Thanks @ezyang! I will manually verify this and add the test on the pt/xla end.

**Review by JackCaoG — APPROVED** [review]
Thanks! I will add the test on the pt/xla side.

**Review by bdhirsh — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29881903).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29881903).

**Pull request closed without merging**
