### PR TITLE
[Inductor efficiency] Move less critical Inductor jobs to periodic

### PR DESCRIPTION
**Pull request by ZainRizvi**
Moves jobs that don't have to be run as frequently to the inductor-periodic workflow, based on the priorities given by @desertfire

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!

**Review by zxiiro — APPROVED** [review]

**Review by desertfire — APPROVED** [review]

**Comment by desertfire** [comment]
cc @jgong5

**Comment by ZainRizvi** [comment]
@pytrochbot merge -i

**Pull request closed without merging**
