### PR TITLE
Back out "Add _int_mm to expose cuBLAS int8@int8 -> int32 matmul (#94339)"

### PR DESCRIPTION
**Pull request by cpuhrsch**
Summary:
Backing out  _int_mm to expose cuBLAS int8@int8 -> int32 matmul (#94339)

Test Plan: CI

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by drisspg — APPROVED** [review]
🔨

**Comment by fxmarty** [comment]
@cpuhrsch Being curious: why?

**Comment by cpuhrsch** [comment]
@fxmarty - This has since been landed again via https://github.com/pytorch/pytorch/pull/96685

**Pull request closed without merging**
