### PR TITLE
Set o_scale of u8 qsigmoid to valid integer range

### PR DESCRIPTION
**Pull request by ZhiweiYan-96**
### Description
For the output scale setting for u8 qtensor, we deem that `1/255` is more suitable.
Using `1/256` may resulting overflow, e.g. (value_f32=0.999, valut_uint8=255.744). Though using rounding can avoid overflow, from the view of methodology, `1/255` would ensure more accurate result.

### CODE REVIEW

**Comment by jerryzh168** [comment]
isn't this a requirement in qnnpack? https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/qnnpack/src/sigmoid.c#L72

**Comment by ZhiweiYan-96** [comment]
Yes, I think this line should also be modified : https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/qsigmoid.cpp#L96

**Comment by ZhiweiYan-96** [comment]
hi @jerryzh168 , I have modify the code of qnnpack also.

**Comment by jerryzh168** [comment]
@kimishpatel can you take a look

**Comment by kimishpatel** [comment]
This is fine but dont we need to make changes here as well https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/observer.py#L1534-L1537Z? @jerryzh168

**Comment by ZhiweiYan-96** [comment]
Hello, do we any update？ ：） @kimishpatel

**Comment by kimishpatel** [comment]
> Hello, do we any update？ ：） @kimishpatel

Sorry for the delay. @jerryzh168 can you please respond to my comment? I dont know if any more updates are needed. If not this looks ok.

**Pull request closed without merging**
