### PR TITLE
[FSDP] Fix `no_sync()` + `FULL_SHARD` root all-gather behavior

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #75902 [FSDP] Add exec order validation
* **#75901 [FSDP] Fix `no_sync()` + `FULL_SHARD` root all-gather behavior**
* #75900 [FSDP][Easy] Minor simplifications

Fixes https://github.com/pytorch/pytorch/issues/75892 and cleans up `test_fsdp_comm.py`.

**All-Gather Traces**
Suppose that we have an `FSDP` model with modules `m_1`, ..., `m_k`, `r`, where `r` is the root `FSDP` module and the `m_i` are nested `FSDP` modules, and that we run iterations `1`, ..., `N` not in `no_sync()`; `N+1`, ..., `M` in `no_sync()`; and `M+1` not in `no_sync()`.

**`FULL_SHARD`**
Iteration `1`, ..., `N` (not in `no_sync()`), `N+1`, ..., `M` (in `no_sync()`), `M+1` (not in `no_sync()`):
- Forward (`k+1`): `m_1`, ..., `m_k`, `r`
    - This is fixed to be uniform across both `is_last_iter_no_sync=True` and `is_last_iter_no_sync=False`.
    - Before, the root module would not free full parameters inside `no_sync()` since for the root, `self._reshard_after_forward=False`, which meant that there would only be `k` all-gathers in the forward pass following an iteration in `no_sync()`.
- Backward (`k`): `m_k`, ..., `m_1`

**`SHARD_GRAD_OP`**
Iteration `1`, ..., `N` (not in `no_sync()`), `N+1` (in `no_sync()`):
 - `is_last_iter_no_sync=False`
- Forward (`k+1`): `m_1`, ..., `m_k`, `r`
- Backward (`0`)

Iteration `N+2`, ..., `M` (in `no_sync()`), `M+1` (not in `no_sync()`):
 - `is_last_iter_no_sync=True`
- Forward (`0`)
- Backward (`0`)

Differential Revision: [D35684278](https://our.internmc.facebook.com/intern/diff/D35684278)

### CODE REVIEW

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35684278).

**Review by zhaojuanmao — APPROVED** [review]

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35684278).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35684278).

**Review by rohan-varma — APPROVED** [review]
Awesome work, LGTM!

**Pull request closed without merging**
