### PR TITLE
Revert - Adds support for accelerated sorting with x86-simd-sort

### PR DESCRIPTION
**Pull request by atalman**
Trying to debug: std::bad_alloc issue

### CODE REVIEW

**Comment by sanchitintel** [comment]
Hi @atalman, before merging #127936, we had noticed that the `std::bad_alloc` issue was happening in some other PRs as well.

**Comment by atalman** [comment]
hi @sanchitintel looks like after reverting the https://github.com/pytorch/pytorch/pull/127936 I can't repro the std_badalloc anymore. 

This is the error I was seeing:
```
generating gallery for auto_examples/others... [ 60%] plot_scripted_tensor_transforms.py            
Warning, treated as error:

../../gallery/others/plot_scripted_tensor_transforms.py unexpectedly failed to execute correctly:

    Traceback (most recent call last):
      File "/vision/gallery/others/plot_scripted_tensor_transforms.py", line 54, in <module>
        scripted_transforms = torch.jit.script(transforms)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/torch/jit/_script.py", line 1429, in script
        ret = _script_impl(
              ^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/torch/jit/_script.py", line 1147, in _script_impl
        return torch.jit._recursive.create_script_module(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/torch/jit/_recursive.py", line 557, in create_script_module
        return create_script_module_impl(nn_module, concrete_type, stubs_fn)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/torch/jit/_recursive.py", line 626, in create_script_module_impl
        script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/torch/jit/_script.py", line 650, in _construct
        init_fn(script_module)
      File "/opt/conda/lib/python3.11/site-packages/torch/jit/_recursive.py", line 602, in init_fn
        scripted = create_script_module_impl(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/torch/jit/_recursive.py", line 630, in create_script_module_impl
        create_methods_and_properties_from_stubs(
      File "/opt/conda/lib/python3.11/site-packages/torch/jit/_recursive.py", line 466, in create_methods_and_properties_from_stubs
        concrete_type._create_methods_and_properties(
    MemoryError: std::bad_alloc

make: *** [html] Error 2
(base) [root@babe7220f5ae docs]# conda create -n py313t python=3.13t
```

**Comment by sanchitintel** [comment]
Hi @atalman, is the failure deterministic in the sense of always being reproducible?

BTW, is it possible that the CI runner on which these jobs are run were changed recently, and have lower RAM than earlier, as in #137447?


Thanks!

**Comment by atalman** [comment]
hi @sanchitintel  I use the code from this workflow: https://github.com/pytorch/vision/actions/workflows/docs.yml 
Running on compiled binary. Here is the example of the failure: https://github.com/pytorch/vision/actions/runs/12096057173/job/33729923085#step:14:1340
It happens on simple Doc compilation. Reproduced with Py3.11 CUDA 11.8 and CUDA 12.4 binaries and PyTorch nightlies.

However if I download the generated binary from this PR: https://github.com/pytorch/pytorch/actions/runs/12089992077?pr=141782 looks like I can't repro this issue anymore.

**Pull request closed without merging**
