### PR TITLE
[JIT] FuseLinear pass now handles CallFunction("linear", ...)

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #71993
* __->__ #61646
* #61608
* #71426

There are several passes which are written to handle both
`CallFunction("linear", ...)` and `aten::linear(...)` despite the two being
functionally identical.

This changes `FuseLinear` to alse normalize the `CallFunction` variant to
`aten::linear`. That way each subsequent transformation only has to handle one
form instead of both.

Differential Revision: [D33754261](https://our.internmc.facebook.com/intern/diff/D33754261)

### CODE REVIEW

**Comment by mruberry** [comment]
@suo - would you recommend a reviewer for this PR?

**Comment by suo** [comment]
@eellison want to take a look?

**Review by eellison — COMMENTED** [review]
What is the use case for this that we woulldnt be inlining first ?

**Comment by peterbell10** [comment]
I'm not sure the reasoning but the quantization tests fail without this extra pass so I assume someone considered it important. Vulkan, xnnpack, etc. I can't test so I think preserving the existing behavior is reasonable.

**Comment by peterbell10** [comment]
@eellison ping

**Review by eellison — COMMENTED** [review]
Do we have anyone who can chime in on why we're doing the substitutions before inlining ? cc @kimishpatel

**Comment by kimishpatel** [comment]
> Do we have anyone who can chime in on why we're doing the substitutions before inlining ? cc @kimishpatel

I dont remember why this is the case but I believe we should not need inlining in order to run these passes. Inlining for example can blow the graph size and subsequently the size of the compiled methods. So I think it is ok to not inline to do this kind of transformations.

One thing about this diff though is that, how do we continue to ensure that CallFunction("linear") replacement is valid. Meaning if aten::linear's signature changes then how do we catch that. I think we have tests on xnnpack_rewrite.cpp and such so maybe those should catch?

**Review by eellison — APPROVED** [review]
LGTM if tests are passing but you might want someone to take a closer look or ping me for particular things you wanted commented on - i dont know have much context here

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33754261).

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33754261).

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33754261).

**Pull request closed without merging**
