### PR TITLE
[vulkan][py] torch.utils.optimize_for_vulkan

### PR DESCRIPTION
**Pull request by IvanKobzarev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#44903 [vulkan][py] torch.utils.optimize_for_vulkan**

Differential Revision: [D23766039](https://our.internmc.facebook.com/intern/diff/D23766039)

Testing:
```
USE_VULKAN=1 python setup.py install
```

```
import torch
from torch.utils.mobile_optimizer import optimize_for_mobile

script_module = torch.jit.load('mobilenet_v2.pt')
script_module_vulkan = optimize_for_mobile(script_module)
torch.jit.save(script_module_vulkan, 'mobilenet_v2_vulkan.pt')
```

### CODE REVIEW

**Review by kimishpatel — APPROVED** [review]
Looks good to me. Some builds are failing.

**Comment by bugra** [comment]
@IvanKobzarev  @kimishpatel I think this PR is breaking `master` due to function call of `vulkanOptimizeForMobile`: https://github.com/pytorch/pytorch/blob/master/binaries/optimize_for_mobile.cc#L71

The function signature of this call does not match of the changes with this PR.

**Comment by kimishpatel** [comment]
@bugra, thanks for pointing this out. @IvanKobzarev, I think you need something like this in `vulkanOptimizeForMobile` signature: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/xnnpack_rewrite.h#L26

**Comment by kimishpatel** [comment]
@bugra if this needs revert to fix master, please feel free to revert.

**Comment by kimishpatel** [comment]
Oh looks like @gunandrose4u already fixed this. Thanks.

**Comment by IvanKobzarev** [comment]
> @bugra, thanks for pointing this out. @IvanKobzarev, I think you need something like this in `vulkanOptimizeForMobile` signature: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/xnnpack_rewrite.h#L26

Yes, Sorry I forgot to change it.

**Pull request closed without merging**
