### PR TITLE
add channels last support for ConvTranspose2d

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #58348
* #55864
* #55584
* __->__ #51185
* #50573
* #50247
* #49821

correct im2col bypass logic in contiguous memory format

add test case for channels last ConvTranspose2d

add col2im bypass in contiguous memory format forward path

Differential Revision: [D26316906](https://our.internmc.facebook.com/intern/diff/D26316906)

### CODE REVIEW

**Comment by mingfeima** [comment]
TODO list:
- [x] add channels last memory format impl (contiguous memory format stay untouched so we can validate nchw v.s. nhwc)
- [x] fix contiguous memory format im2col skipping logic (k==1 && s==1 && pad==0 && output_pad==0), old logic is wrong.
- [x] add test case
- [ ] improve contiguous (nchw) memory format performance
- [ ] performance benchmarking

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D26316906).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D26316906).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D26316906).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D26316906).

**Comment by mingfeima** [comment]
test case failures from `test_conv_thnn_nhwc` is expected before #49582 is settled.
since it will test both `thnn_conv2d` and `slow_conv_transpose2d` at the same time.

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D26316906).

**Comment by mingfeima** [comment]
- [ ] update this with cpublas::gemm

**Pull request closed without merging**
