### PR TITLE
[spmd compile API] add a (temporary) mechanism for overriding input tensors' placements

### PR DESCRIPTION
**Pull request by yifuwang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #98233
* __->__ #98232
* #98231
* #98230
* #98229

Currently, the compile API assumes all input tensors' shard dimension is the first dimension. dtensor expansion doesn't work when there are input tensors whose shard dimension is not the first dimension.

In addtion, respect non-tensor inputs beyond nn.Module and optim.Optimizers.

Differential Revision: [D44615234](https://our.internmc.facebook.com/intern/diff/D44615234/)

### CODE REVIEW

**Review by mrshenli — APPROVED** [review]
Supersedes #98180

**Comment by mrshenli** [comment]
```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] VulkanAPITest.div_to_scalar_wrapped

 1 FAILED TEST
  YOU HAVE 7 DISABLED TESTS
```

Test failure looks irrelevant

**Comment by yifuwang** [comment]
@yifuwang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44615234).

**Comment by yifuwang** [comment]
@yifuwang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44615234).

**Comment by yifuwang** [comment]
@yifuwang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44615234).

**Comment by yifuwang** [comment]
Superceded by https://github.com/pytorch/pytorch/pull/98391

**Pull request closed without merging**
