### PR TITLE
[BE]: Update ruff to 0.285

### PR DESCRIPTION
**Pull request by Skylion007**
This updates ruff to 0.285 which is faster, better, and have fixes a bunch of false negatives with regards to fstrings.

I also enabled RUF017 which looks for accidental quadratic list summation. Luckily, seems like there are no instances of it in our codebase, so enabling it so that it stays like that. :) 

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by Skylion007** [comment]
> @pytorchbot revert -m "Sorry, but this PR breaks internal tests. @ezyang, can you please hep them get unblocked? It seems like one of the strings was prob accidentally modified" -c ghfirst

Oh, if this is the case, we should upstream the bug to ruff.

**Comment by ezyang** [comment]
the test doesn't repro when I run it locally, this may be a false alarm.

We could try splitting the codemod into a few (4?) parts and landing them individually, as an alternative.

**Comment by ZainRizvi** [comment]
Apologies for the churn here

**Pull request closed without merging**
