### PR TITLE
Update pybind11 to v2.10.2

### PR DESCRIPTION
**Pull request by Skylion007**
I am a pybind11 maintainer and contributor to PyTorch so making sure we have the latest and greatest. This minor release is mostly cmake related bugfixes, but also include some nice optin Eigen bindings, better control of docstring generation, and better typing.

One change so far that has proven helpful is additional debug utils that detect refcount increments or decrements that occur without the GIL being locked which can cause really nasty UB behavior. It seems to have triggered on the PyTorch codebase.

cc @soumith since he approved the last PR related to updating pybind11, or maybe @ezyang

### CODE REVIEW

**Comment by Skylion007** [comment]
Opened an issue here: https://github.com/pytorch/pytorch/issues/91251 not sure who to assign to.

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
probably cc: @mrshenli wrt the torch.rpc failing issue due to a gil handling bug

**Comment by ezyang** [comment]
ngl all these test failures look cursed lol

**Comment by Skylion007** [comment]
> ngl all these test failures look cursed lol

Yeah, unfortunately downgrading / disabling the error won't fix the issue in the long term. There are some python operations being done without the GIL being held. The issue exists in current PyTorch, and will likely continue to get more complex to fix unless additional hardening like the above PR fixes it. :(

**Comment by albanD** [comment]
For the ASAN issue in multipy, this is most likely a false positive. `py::key_error` is indeed a proper subclass of `py::builtin_exception`.
We should load things globally so the problem might be due to version mismatch between pybind in multipy and in core.

**Comment by albanD** [comment]
Trying to upgrade multipy to this version first to see if that helps: https://github.com/pytorch/multipy/pull/304

**Comment by albanD** [comment]
FYI https://github.com/pytorch/pytorch/pull/103989 should supersede this one! Hopefully everything should be green there.

**Pull request closed without merging**
