### PR TITLE
CUDA BFloat16 unary ops part 1

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Comment by ngimel** [comment]
Test errors are real

**Comment by ngimel** [comment]
You need to adjust dtypesIfCUDA here https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_methods_invocations.py#L233 and in similar places.

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Now flake import error is real :-)

**Comment by ngimel** [comment]
Is XLA fixing those operators, or skipping tests on their side? Let me know when this is ready.

**Comment by JackCaoG** [comment]
I submit a fix on xla side(lowering for these ops) in https://github.com/pytorch/xla/pull/2501

**Pull request closed without merging**
