### PR TITLE
Allow Lazy Module to be modelled as `UnspecializedNNModuleVariable`

### LINKED ISSUE #100001: [dynamo] no_grad context doesn't end in LazyModule use case
### 🐛 Describe the bug

I encountered this error after adding a new test in `test/dynamo/test_modules.py`. I copied the two tests in question into a separate file for the repro below.

If the first test (`test_lazy_module()`) is run before the second test (`test_backward_hooks()`), then the second test errors with:

```
$ python lazy_nograd.py
/data/users/dberard/pytorch/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
[2023-04-25 10:30:35,464] torch._dynamo.output_graph: [WARNING] nn.Module forward/_pre hooks are only partially supported, and were detected in your model. In particular, if you do not change/remove hooks after calling .compile(), you can disregard this warning, and otherwise you may need to set torch._dynamo.config.skip_nnmodule_hook_guards=False to ensure recompiling after changing hooks.See https://pytorch.org/docs/master/compile/nn-module.html for more information and limitations.
[2023-04-25 10:30:35,464] torch._dynamo.output_graph: [WARNING] nn.Module state_dict and backward hooks are not yet supported by torch.compile, but were detected in your model and will be silently ignored. See https://pytorch.org/docs/master/compile/nn-module.html for more information and limitations.
/data/users/dberard/pytorch/torch/_dynamo/eval_frame.py:356: UserWarning: changing options to `torch.compile()` may require calling `torch._dynamo.reset()` to take effect
  warnings.warn(
Traceback (most recent call last):
  File "/data/users/dberard/scripts/lazy_nograd.py", line 92, in <module>
    test_backward_hooks()
  File "/data/users/dberard/scripts/lazy_nograd.py", line 85, in test_backward_hooks
    loss.backward()
  File "/data/users/dberard/pytorch/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/data/users/dberard/pytorch/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
Repro:
```python
import torch
import torch._dynamo
from torch.nn.modules.lazy import LazyModuleMixin
from functools import partial

class LazyParentModule(LazyModuleMixin, torch.nn.Module):
    def __init__(self):
        super().__init__()

    def initialize_parameters(self, input):
        with torch.no_grad():
            self._val = torch.nn.Parameter(torch.ones(2, 2))

    def forward(self, x):
        return x.sin() + self._val

def test_lazy_module():
    m = LazyParentModule()
    x = torch.rand(2, 2)
    opt_m = torch._dynamo.optimize("eager", nopython=True)(m)
    res = opt_m(x)
    ref = m(x)
    assert torch.allclose(ref, res)

def test_backward_hooks():
    # this test shouldn't care whether hook guards are enabled or not

    class CustomLinear(torch.nn.Module):
        # not an 'allowed module', so should not graph-break
        def __init__(self, a, b):
            super().__init__()
            self.weight = torch.nn.Parameter(torch.randn(a, b))

        def forward(self, x):
            return torch.mm(x, self.weight)

    class ToyModel(torch.nn.Module):
        def __init__(self):
            super().__init__()
            self.net = torch.nn.Sequential(
                *[CustomLinear(10, 10)]
                + [CustomLinear(10, 10000)]
                + [CustomLinear(10000, 5)]
            )

        def forward(self, x):
            return self.net(x)

    model = ToyModel()
    backward_hook_handles = {}
    pre_backward_hook_handles = {}

    grad_sizes = {}

    def backward_hook(name, mod, grad_inp, grad_out):
        grad_sizes[name] = (
            (gi.shape for gi in grad_inp),
            (go.shape for go in grad_out),
        )
        return None

    pre_grad_sizes = {}

    def backward_pre_hook(name, mod, grad_out):
        pre_grad_sizes[name] = (go.shape for go in grad_out)
        return None

    for name, module in model.named_modules():
        backward_hook_handles[name] = module.register_full_backward_hook(
            partial(backward_hook, name)
        )

        pre_backward_hook_handles[name] = module.register_full_backward_pre_hook(
            partial(backward_pre_hook, name)
        )

    model = torch.compile(model, backend="aot_eager")

    for i in range(2):
        # second iteration is key, hooks would have fired during aot trace
        # on first iter
        x = torch.randn((20, 10))
        pred = model(x)
        loss = pred.sum()
        loss.backward()

    assert (grad_sizes.keys() == backward_hook_handles.keys())
    assert (pre_grad_sizes.keys() == pre_backward_hook_handles.keys())

test_lazy_module()
test_backward_hooks()
```

### Versions

main branch, cpu

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### LINKED ISSUE #138489: [dynamo] Speculation log diverges when Lazy Module is used in a certain way
### 🐛 Describe the bug

The following logic interacts in a way that causes speculation log to diverge:
1. When we construct a `VariableTracker` for an `nn.Module` instance, the following predicate (partially) determines whether it becomes a `NNModuleVariable` or `UnspecializedNNModuleVariable`; note the `if is_lazy_module(obj)` check.
https://github.com/pytorch/pytorch/blob/2b7c7a20b9c0e8e7f2773ffc5c9f79c3cae2070b/torch/_dynamo/variables/builder.py#L1393
https://github.com/pytorch/pytorch/blob/2b7c7a20b9c0e8e7f2773ffc5c9f79c3cae2070b/torch/_dynamo/mutation_guard.py#L95-L103

2. When Dynamo traces call to `*NNModuleVariable`, if the underlying module instance is a lazy module, it'll run its initialization first, which causes the instance to become a non-lazy module.
https://github.com/pytorch/pytorch/blob/2b7c7a20b9c0e8e7f2773ffc5c9f79c3cae2070b/torch/_dynamo/variables/nn_module.py#L54-L79

3. When tracing a `mod(input)` call for `NNModuleVariable`, Dynamo usually doesn't inline the `forward` method (we just track it as an opaque call in the fx graph). However, for `UnspecializedNNModuleVariable`, Dynamo always inline the `forward` method.
- `NNModuleVariable.call_function`:
https://github.com/pytorch/pytorch/blob/2b7c7a20b9c0e8e7f2773ffc5c9f79c3cae2070b/torch/_dynamo/variables/nn_module.py#L417-L424
- `UnspecializedNNModuleVariable.call_function`:
https://github.com/pytorch/pytorch/blob/2b7c7a20b9c0e8e7f2773ffc5c9f79c3cae2070b/torch/_dynamo/variables/nn_module.py#L902-L904

Dynamo restart (e.g., due to graph break) and (1), (2) together could cause a lazy module instance to be modeled as different module variables across 2 tracings; then (3) causes Dynamo tracing to diverge from the speculation log, which was gathered before the graph break.

### Error logs

```verbatim
Traceback (most recent call last):
  File "/Users/ryanguo99/Documents/work/scratch/test.py", line 43, in <module>
    test_lazy_module()
  File "/Users/ryanguo99/Documents/work/scratch/test.py", line 41, in test_lazy_module
    foo(mod, x)
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/eval_frame.py", line 550, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/convert_frame.py", line 1364, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/convert_frame.py", line 1155, in __call__
    result = self._inner_convert(
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/convert_frame.py", line 544, in __call__
    return _compile(
           ^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/convert_frame.py", line 964, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/convert_frame.py", line 695, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/convert_frame.py", line 728, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/bytecode_transformation.py", line 1337, in transform_code_object
    transformations(instructions, code_options)
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/convert_frame.py", line 229, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/convert_frame.py", line 657, in transform
    tracer.run()
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 2888, in run
    super().run()
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 1095, in run
    while self.step():
          ^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 1007, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 615, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 2395, in CALL
    self._call(inst)
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 2389, in _call
    self.call_function(fn, args, kwargs)
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 942, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/variables/lazy.py", line 169, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/variables/nn_module.py", line 902, in call_function
    return variables.UserFunctionVariable(fn, source=source).call_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/variables/functions.py", line 339, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/variables/functions.py", line 111, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 948, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 3103, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 3231, in inline_call_
    tracer.run()
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 1095, in run
    while self.step():
          ^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 1007, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 615, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 2395, in CALL
    self._call(inst)
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 2389, in _call
    self.call_function(fn, args, kwargs)
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 942, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/variables/lazy.py", line 169, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/variables/nn_module.py", line 902, in call_function
    return variables.UserFunctionVariable(fn, source=source).call_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/variables/functions.py", line 339, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/variables/functions.py", line 111, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 948, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 3103, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 3231, in inline_call_
    tracer.run()
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 1095, in run
    while self.step():
          ^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 1007, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 610, in wrapper
    speculation = self.speculate()
                  ^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 2644, in speculate
    return self.speculation_log.next(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanguo99/Documents/work/pytorch/torch/_dynamo/symbolic_convert.py", line 202, in next
    entry.instruction_pointer == instruction_pointer
AssertionError:
SpeculationLog diverged at index 2 (log had 4 entries):
- Expected: /Users/ryanguo99/Documents/work/scratch/test.py:36 (CALL at ip=10)
- Actual: /Users/ryanguo99/Documents/work/pytorch/torch/nn/modules/linear.py:125 (CALL at ip=8)
Previous instruction: /Users/ryanguo99/Documents/work/scratch/test.py:11(CALL @ 4)

There are two usual reasons why this may have occured:
- When Dynamo analysis restarted, the second run took a different path than
  the first.  If this occurred, the previous instruction is the critical instruction that
  behaved differently.
- Speculation entries are only added under certain conditions (as seen in
  step()), e.g., there must exist operators in the graph; those conditions may
  have changed on restart.

If this divergence was intentional, clear the speculation log before restarting (do NOT
do this for graph breaks, you will infinite loop).

Otherwise, please submit a bug report, ideally including the contents of TORCH_LOGS=+dynamo


from user code:
   File "/Users/ryanguo99/Documents/work/scratch/test.py", line 35, in foo
    res = mod(x)
  File "/Users/ryanguo99/Documents/work/scratch/test.py", line 11, in forward
    return self.layer(x)
  File "/Users/ryanguo99/Documents/work/pytorch/torch/nn/modules/linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Minified repro

Just run `python test.py` on the following program

```python
import torch

def test_lazy_module():

    class ModWithOneLazyLinear(torch.nn.Module):
        def __init__(self) -> None:
            super().__init__()
            self.layer = torch.nn.LazyLinear(8)

        def forward(self, x):
            return self.layer(x)

    # This allows us to restart tracing without clearing speculation log
    def id_and_graph_break(x):
        torch._dynamo.graph_break()
        return x

    @torch.compile()
    def foo(mod, x):
        # We'll trace this `mod(x)` call 2 times (because of the manual graph
        # break right after it)
        #
        # - 1st time the `mod.layer` would be treated as an `NNModuleVariable`
        # (because it's a `LazyLinear`), so we won't trace into its call method,
        # and would leave it as an opaque fx call to the linear layer.
        #
        # NOTE that as part of tracing `mod.layer(x)` we'd hit
        # `initialize_lazy_module`, which changes the underlying `mod.layer`
        # from a LazyLinear to a Linear instance.
        #
        # - 2nd time the `mod.layer` would be treated as an
        # `UnspecializedNNModuleVariable` (because it's now a `Linear`), and
        # we'd trace into the linear layer rather than keeping it as a single fx
        # call. This breaks speculation log.
        res = mod(x)
        res2 = id_and_graph_break(res)
        return res

    x = torch.ones(10, 3)
    mod = ModWithOneLazyLinear()
    foo(mod, x)

test_lazy_module()
```

### Versions

Python 3.12.5, at 2b7c7a20.

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec

### PR DESCRIPTION
**Pull request by StrongerXi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #138632
* __->__ #138639

This patch
- removes the `is_lazy_module` check from `is_dynamic_nn_module`, and
  adds a regression test.
- removes a series of dynamo expected failures on lazy modules. The few
  ones I checked all were failing due to speculation log divergence,
  similar to #138489.

Note that #100047 introduced the conditional removed in this patch, and
it was trying to fix #100001. But I've confirmed locally that #100001 no
longer repros after this patch.

Fixes #138489. See more context in the issue.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Comment by StrongerXi** [comment]
A bunch of previously "expected-to-fail" tests are passing now, mystery.

**Comment by StrongerXi** [comment]
> A bunch of previously "expected-to-fail" tests are passing now, mystery.

Remove these expected failures. Update commit message.

**Review by jansel — CHANGES_REQUESTED** [review]
Won't this immediately recompile on iteration 2 because the class of the lazy module will change?

Can you update the test to run multiple iterations and check for recompiles?

**Comment by StrongerXi** [comment]
> Won't this immediately recompile on iteration 2 because the class of the lazy module will change?

Turned out it didn't, and I think that's because we eagerly initialize lazy module right before Dynamo traces into a module call, e.g., https://github.com/pytorch/pytorch/blob/a0efc0af635f57bb6c96f0075899e38b7815d500/torch/_dynamo/variables/nn_module.py#L850-L861

> Can you update the test to run multiple iterations and check for recompiles?

Updated the test to run twice, and assert no recompilation happened.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
