### PR TITLE
`torch.lu`: forward AD support

### PR DESCRIPTION
**Pull request by nikitaved**
As per title.

### CODE REVIEW

**Comment by Lezcano** [comment]
Note: It'd be good to wait until https://github.com/pytorch/pytorch/pull/63569 and the previous PR in that stack are merged to avoid merge conflicts.

**Comment by nikitaved** [comment]
No conflicts, this is separate from the these PRs.

**Comment by Lezcano** [comment]
The point is that it uses `triangular_solve`.

**Comment by nikitaved** [comment]
Yes, but you do not modify the behavior of `at::triangular_solve`, are you?

**Review by albanD — APPROVED** [review]
LGTM

@Lezcano any merge conflict concerns? Or I can land?

**Comment by nikitaved** [comment]
@albanD , there should not be any conflicts. Once `solve_triangular` is merged, we would need to replace all occurrences of `triangular_solve` with the better alternative.

**Pull request closed without merging**
