### PR TITLE
[dynamo][NFC] Remove unused method `InliningInstructionTranslator.check_replace_is_safe`

### PR DESCRIPTION
**Pull request by StrongerXi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137819
* #137818

This method was no longer needed after #113725; the checking logic is
now in `SideEffects.check_allowed_side_effect`.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]
Fix the mypy errors (likely earlier from the stack though).

**Review by mlazos — APPROVED** [review]
Nice!

**Comment by StrongerXi** [comment]
Rebase.

**Comment by StrongerXi** [comment]
Moved to #137906.

**Pull request closed without merging**
