### PR TITLE
Delete functorch's monkeypatching

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #85430
* #85426

By upstreaming functorch's tensor printing logic into PyTorch. There's
no way of creating a custom print function for a TensorImpl subclass (as
opposed to a torch_dispatch or torch_function tensor subclass, which can
just override repr()) right now, so we need to directly interpose inside
regular Tensor printing in PyTorch.

Monkey patching is bad; users do not expect `import blah` to change
something about another library.

Fixes https://github.com/pytorch/functorch/issues/900

Test Plan:
- existing tests

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by zou3519** [comment]
pytorchbot merge -f "It won't let me merge the normal way"

**Pull request closed without merging**
