### PR TITLE
cudagraphs: fix backward hooks & fsdp interaction

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #126914

Fixes

> ERROR: expected to be in states [<TrainingState.FORWARD_BACKWARD: 2>] but current state is TrainingState.IDLE

Error that would occur when composing pt2 fsdp and cudagraphs. Cudagraphs caches output tensor impls in the fast path, so we were inadvertently accumulating multiple hooks on what should have been fresh allocations. 

from code comment:
```
# this output represents a fresh allocated tensor.
# We return the same TensorImpl from run to run to avoid overhead.
# autograd.Function will reset the Autograd meta of output tensors
# as part of aot_autograd, but _backward_hooks are stored on tensors separately,
# so we need to manually reset hooks.
``

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by xmfan** [comment]
update the comment on --fsdp about not supporting cudagraphs too: https://github.com/pytorch/pytorch/blob/main/benchmarks/dynamo/common.py#L3171

**Review by awgu — APPROVED** [review]
SGTM!

**Comment by xmfan** [comment]
is it ever possible for a cached output tensor to have its hook registration outside of the compiled function? i.e.

```
x = torch.randn(...)
x.register_hook(my_hook)
compiled_fn(x) <-- could x be cached?
```

**Comment by eellison** [comment]
@xmfan the tensors are fresh allocations here so it should be fine. 

The only time we would return inputs would be written to tensors, which in this case wouldn't work with backward hooks since you will error if you inplace write a tensor with gradient. I couldn't get a repro running that would test the case you're describing.

**Review by xmfan — APPROVED** [review]
seems like handle invalidation is already handled

**Pull request closed without merging**
