### PR TITLE
Add testing workaround for EFA and TensorPipe

### PR DESCRIPTION
**Pull request by kumpera**
This is a workaround for EFA for TensorPipe.

This allows RPC enabled tests to be ran on AWS clusters.

### CODE REVIEW

**Comment by kumpera** [comment]
This great piece of engineering was due to @pbelevich  (https://github.com/pytorch/PiPPy/pull/185) <3

**Comment by kumpera** [comment]
> This great piece of engineering was due to @pbelevich ([pytorch/PiPPy#185](https://github.com/pytorch/PiPPy/pull/185)) <3

And the breakage is all my doing

**Comment by lw** [comment]
If you want to implement a similar change "upstream" in TensorPipe itself here is how it could be achieved.

At more or less [this line](https://github.com/pytorch/tensorpipe/blob/a58b5435d1b06a1dcc6ab584c41aa8d7d29470af/tensorpipe/transport/ibv/context_impl.cc#L63) you could take `deviceList[0]`, open it just like we do [here](https://github.com/pytorch/tensorpipe/blob/a58b5435d1b06a1dcc6ab584c41aa8d7d29470af/tensorpipe/transport/ibv/reactor.cc#L21), then call `ibv_query_device` on it and if the `max_srq` attribute of the returned struct is equal to zero then you return nullptr (otherwise you just let that function continue).

Let me know if you want some more help in implementing and testing this.

**Comment by kumpera** [comment]
> If you want to implement a similar change "upstream" in TensorPipe itself here is how it could be achieved.
> 
> At more or less [this line](https://github.com/pytorch/tensorpipe/blob/a58b5435d1b06a1dcc6ab584c41aa8d7d29470af/tensorpipe/transport/ibv/context_impl.cc#L63) you could take `deviceList[0]`, open it just like we do [here](https://github.com/pytorch/tensorpipe/blob/a58b5435d1b06a1dcc6ab584c41aa8d7d29470af/tensorpipe/transport/ibv/reactor.cc#L21), then call `ibv_query_device` on it and if the `max_srq` attribute of the returned struct is equal to zero then you return nullptr (otherwise you just let that function continue).
> 
> Let me know if you want some more help in implementing and testing this.

I'd love to work on fixing this on TensorPipe. I'll likely won't have BW until midsummer thou.

**Review by wanchaol — APPROVED** [review]
Let's get this merged first, and we can create a issue in the tensor pipe repo and follow up on upstreaming to tensor pipe from there.

**Pull request closed without merging**
