### PR TITLE
Fix docstring for nn.MultiHeadAttention

### PR DESCRIPTION
**Pull request by lithuak**
Fixes nn.MultiHeadAttention's docstring problem reported at #70498.

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks

**Comment by albanD** [comment]
Actually the non-inline version might be better as well no? Same for leaky relu

**Comment by lithuak** [comment]
@albanD It is non-online.

**Comment by albanD** [comment]
Ho sorry I got confused with another one of these update PR!

**Pull request closed without merging**
