### PR TITLE
[async-tp] fix a race condition that can cause silent correctness issue

### PR DESCRIPTION
**Pull request by yifuwang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137199

Details described in https://github.com/pytorch/pytorch/issues/137171:

image

Fix: we introduce the following invariants in `_pipelined_all_gather_and_consume` and `_pipelined_produce_and_all2all`:
- Before any stream writes to/reads from p2p buffers, perform a barrier on channel 0 on the launch stream.
- After all streams completed writing to/reading from p2p buffers, perform a barrier on channel 0 on the launch stream.

NOTE: This fix only focuses on addressing the race condition. Some barriers are exposed, which can be hidden by computation, and we'll optimize them in subsequent PRs.

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by weifengpy — APPROVED** [review]

**Comment by kit1980** [comment]
2.5.1 is an emergency patch release to address specific large regressions, moving this to 2.6.0
In addition, this doesn't have any tests that the issue was actually fixed.

**Comment by yifuwang** [comment]
I confirm that the issue is fixed in 2.6.0 release candidate. cc @kit1980

**Pull request closed without merging**
