### PR TITLE
Ci all/pr trt6

### PR DESCRIPTION
**Pull request by houseroad**
Trigger all CIs for #28715

### CODE REVIEW

**Comment by houseroad** [comment]
@drnikolaev let's use this PR to check the build, and land your PR.

**Comment by houseroad** [comment]
caffe2_py2_cuda9_0_cudnn7_ubuntu16_04_build and caffe2_py2_cuda9_0_cudnn7_centos7_build are the potential broken builds

**Comment by drnikolaev** [comment]
@houseroad  `caffe2_py2_cuda9_0_cudnn7_ubuntu16_04_*` and `caffe2_py2_cuda9_0_cudnn7_centos7_*` are now green. Failures I see seem to be unrelated to this PR, please check.

**Comment by drnikolaev** [comment]
@houseroad are we waiting for the last check to finish?

**Pull request closed without merging**
