### PR TITLE
gen ExclusivelyOwned in structured kernels

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #59420
* **#59827**

Differential Revision: [D28965922](https://our.internmc.facebook.com/intern/diff/D28965922/)

### CODE REVIEW

**Comment by ezyang** [comment]
Could you post the before and after generated code?

**Comment by ezyang** [comment]
It doesn't feel like, as is, there is any benefit to ExclusivelyOwned here, yet. Is that true?

**Review by ezyang — APPROVED** [review]

**Comment by swolchok** [comment]
> It doesn't feel like, as is, there is any benefit to ExclusivelyOwned here, yet. Is that true?

It should save us a refcount decrement for the functional operators.

**Comment by swolchok** [comment]
> It should save us a refcount decrement for the functional operators.

Correction, it should save us a ~Tensor() call, which would have to do a load and branch to check if the TensorImpl was UndefinedTensorImpl. It would always ffind that to be the case and thus wouldn't do a refcount decrement anyway, though. I put pastes with the before/after RegisterCPU.cpp on Phabricator.

**Review by bhosmer — APPROVED** [review]

**Pull request closed without merging**
