### PR TITLE
Add complex number to torch.types.Number

### PR DESCRIPTION
**Pull request by tugsbayasgalan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #69420

Differential Revision: [D32863940](https://our.internmc.facebook.com/intern/diff/D32863940)

### CODE REVIEW

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32863940).

**Comment by anjali411** [comment]
can we add a test to verify the effective change?

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32863940).

**Review by anjali411 — APPROVED** [review]
Thank you!

**Pull request closed without merging**
