### PR TITLE
Move the CUDA implementation of floor to ATen.

### LINKED ISSUE #24617: Migrate `round` and `round_` from the TH to Aten (CUDA)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #26494 Move the CUDA implementation of log to ATen.
* #25592 Simplify operator `sign` using the helper.
* #25423 Move the CUDA implementation of trunc to ATen.
* **#25372 Move the CUDA implementation of floor to ATen.**

Close #24617

Differential Revision: [](https://our.internmc.facebook.com/intern/diff/)

Differential Revision: [D17397478](https://our.internmc.facebook.com/intern/diff/D17397478)

### CODE REVIEW

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Please rebase

**Comment by xuhdev** [comment]
@VitalyFedyunin Done!

**Comment by xuhdev** [comment]
I just rebased for resolving a conflict

**Pull request closed without merging**
