### PR TITLE
Eliminate calls of c10::guts::conjunction,c10::guts::disjunction,c10::guts::negation,c10::guts::void_t, c10::invoke and c10::guts::apply

### PR DESCRIPTION
**Pull request by cyyever**
C++17 provides alternations. 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @kiukchung @d4l3k @lucasllc
@huydhn  @Skylion007

### CODE REVIEW

**Comment by huydhn** [comment]
Learning from the lesson of https://github.com/pytorch/pytorch/pull/108748 where there are instances in fbcode that use `c10::guts:to_string`, let me import the diff to see if anything else are still using these functions internally.  They would need to be updated before this can be landed.

**Comment by cyyever** [comment]
@huydhn Any progress?

**Comment by huydhn** [comment]
> @huydhn Is it safe to land?

So far, internal signals look good to me.  I haven't been able to review the change carefully, so I will leave it for the experts.  Once it's approved, I could help land it.  (I will try to take a look at the PR tomorrow)

**Comment by cyyever** [comment]
@huydhn I see, thank you!

**Comment by cyyever** [comment]
@huydhn   Seems the changes are correct.

**Pull request closed without merging**
