### PR TITLE
Reland: implement a function to convert a storage to copy-on-write

### PR DESCRIPTION
**Pull request by kurtamohler**
Relands #100819

In addition, the `impl_cow_context` library is combined into the base c10 core library, and COW unit tests are combined into just one binary.

Part of #109833

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ZainRizvi** [comment]
@pytorchbot revert -m "Build has been broken consistently since this PR was merged" -c landrace

Seems like a land race

Failure details in https://hud.pytorch.org/pytorch/pytorch/commit/76fcec74c413af22186f0782f02aca49ab61dc20

**Comment by atalman** [comment]
Following tests are failing in internal CI:
```
✗ Fail:  try_ensure_test.no_context (0.0s)
xplat/caffe2/c10/test/core/impl/cow_test.cpp:92
Value of: new_storage
Expected: isn't NULL
  Actual: 0
```

This one is memory leaked:
```
⚠ Fatal: try_ensure_test.different_context (0.2s)
Test appears to have passed but the binary exited with a non-zero exit code.
This usually means something has crashed after the test was done.

==690536==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0xc41ac7 in operator new[](unsigned long) (/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbsource/da4de3c780a17bfa/xplat/caffe2/c10/__c10_test__/c10_test+0xc41ac7)
    #1 0x5297e6 in c10::impl::(anonymous namespace)::try_ensure_test_different_context_Test::TestBody() xplat/caffe2/c10/test/core/impl/cow_test.cpp:113
    #2 0x9efd98 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) third-party/googletest/1.11.0/googletest/googletest/src/gtest.cc:2665
    #3 0x9ef5e8 in testing::Test::Run() third-party/googletest/1.11.0/googletest/googletest/src/gtest.cc:2682
    #4 0x9f232a in testing::TestInfo::Run() third-party/googletest/1.11.0/googletest/googletest/src/gtest.cc:2861
    #5 0x9f5463 in testing::TestSuite::Run() third-party/googletest/1.11.0/googletest/googletest/src/gtest.cc:3015
    #6 0xa16e26 in testing::internal::UnitTestImpl::RunAllTests() third-party/googletest/1.11.0/googletest/googletest/src/gtest.cc:5917
    #7 0xa15ecf in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) third-party/googletest/1.11.0/googletest/googletest/src/gtest.cc:2665
    #8 0xa153fe in testing::UnitTest::Run() third-party/googletest/1.11.0/googletest/googletest/src/gtest.cc:5500
    #9 0xa63210 in RUN_ALL_TESTS() fbsource/gtest/gtest.h:2490
    #10 0xa6319f in main third-party/googletest/1.11.0/googletest/googletest/src/gtest_main.cc:52
    #11 0x7f0a4602c656 in __libc_start_call_main (/usr/local/fbcode/platform010/lib/libc.so.6+0x2c656)
    #12 0x7f0a4602c717 in __libc_start_main_impl (/usr/local/fbcode/platform010/lib/libc.so.6+0x2c717)
    #13 0x4d1e40 in _start /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/x86_64/start.S:116
```

**Pull request closed without merging**
