### PR TITLE
Use static_assert to detect get_type_index used in device code

### PR DESCRIPTION
**Pull request by cyyever**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by r-barnes — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Comment by huydhn** [comment]
Here is the internal failure that I'm seeing.  It happens on Windows

```
C:\re\95b83\work\xplat\caffe2\c10\util\TypeIndex.h(104): error: no instance of constructor "c10::util::type_index::type_index" matches the argument list
    return {};
           ^
C:\re\95b83\work\xplat\caffe2\c10\util\TypeIndex.h(19): note #3322-D: number of parameters of function "c10::util::type_index::type_index(const c10::util::type_index &)" does not match the call
  struct type_index final : IdWrapper<type_index, uint64_t> {
         ^
C:\re\95b83\work\xplat\caffe2\c10\util\TypeIndex.h(19): note #3322-D: number of parameters of function "c10::util::type_index::type_index(c10::util::type_index &&)" does not match the call
  struct type_index final : IdWrapper<type_index, uint64_t> {
         ^
C:\re\95b83\work\xplat\caffe2\c10\util\TypeIndex.h(20): note #3322-D: number of parameters of function "c10::util::type_index::type_index(uint64_t)" does not match the call
    constexpr explicit type_index(uint64_t checksum) : IdWrapper(checksum) {}
                       ^

1 error detected in the compilation of "arvr/projects/codec_avatar/drtk/src/rasterize/rasterize_kernel.cu".
rasterize_kernel.cu
```

**Comment by cyyever** [comment]
@huydhn It should not be used in CUDA code, the team should fix it.

**Comment by cyyever** [comment]
@r-barnes Need to re-check META code.

**Comment by huydhn** [comment]
The tool prevents me from importing this change again.  The diff was reverted D65169186. Its status shows as reverted not abandon, so I couldn't unlink the diff and the PR.

Screenshot 2024-11-06 at 19 49 28

cc @bigfootjon @izaitsevfb 

@cyyever If you don't want to wait, please create a new PR cloning from this one, so I could import that one fresh then.

**Pull request closed without merging**
