### PR TITLE
torch.jit.TopLevelTracedModule._reconstruct + torch.jit.RecursiveScriptModule._reconstruct + inplace support for graph mode quantization

### PR DESCRIPTION
**Pull request by jerryzh168**
This is to support inplace option in graph mode APIs.
from:
https://github.com/pytorch/pytorch/pull/39979 and https://github.com/pytorch/pytorch/pull/40414

### CODE REVIEW

**Comment by malfet** [comment]
@jerryzh168 can you please rebase your change?

**Comment by jerryzh168** [comment]
@malfet not sure if I did it correctly or not, could you check

**Comment by seemethere** [comment]
Yeah does not look like the branch is rebased correctly, would you mind doing a clean checkout of the `release/1.6` branch and cherry picking your commits on top of that?

**Review by malfet — CHANGES_REQUESTED** [review]
@jerryzh168 can you please clean up your PR. For example, what `binary_linux_upload.sh` changes have anything to do with the change?

**Comment by jerryzh168** [comment]
I'll recreate the cherry pick

**Comment by jerryzh168** [comment]
> @jerryzh168 can you please rebase your change?

btw is there some problem with the original cherry-pick?

**Comment by jerryzh168** [comment]
Updated the comment: https://github.com/pytorch/pytorch/issues/40472#issuecomment-648525721

**Pull request closed without merging**
