### PR TITLE
[WIP] remove tools/setup_helpers/cudnn.py

### PR DESCRIPTION
**Pull request by xuhdev**
FindCUDNN.cmake and cuda.cmake have done the detection. This commit deletes `tools/setup_helpers/cudnn.py` as it is no longer needed.

### CODE REVIEW

**Review by xuhdev — COMMENTED** [review]
I left some inline comments explaining how some parts of the deleted lines are done in other part of the codebase.

**Comment by xuhdev** [comment]
@ezyang Do you know whether there is a way to do master CI for this PR? I'm trying to avoid surprise as build changes are hard to test.

**Comment by ezyang** [comment]
Just the usual: edit the circleci yaml so that all of the jobs are enabled :( It might be sufficient to just XImportant all the configs and then make `should_run_job.py` always return true.

cc @suo looking forward to your 2.1 circleci config ;)

**Comment by xuhdev** [comment]
@ezyang The issue is that I'm not sure which one to enable yet, unlike the situation in which PRs have been reverted :)

**Comment by ezyang** [comment]
In this case, you'd literally enable all of them, I think.

**Comment by xuhdev** [comment]
Moved to #25482 to turn on all CIs

**Pull request closed without merging**
