### PR TITLE
[DataPipe] Adding examples for MapDataPipes with small fixes for others

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #73250

Differential Revision: [D34400782](https://our.internmc.facebook.com/intern/diff/D34400782)

### CODE REVIEW

**Review by ejguan — APPROVED** [review]
LGTM! Thanks

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34400782).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34400782).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34400782).

**Pull request closed without merging**
