### PR TITLE
Remove python 3.8 nightly builds

### PR DESCRIPTION
**Pull request by atalman**
Removing python 3.8 support in nightly builds. As per PR: https://github.com/pytorch/pytorch/issues/120718

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Do we want ciflow/binaries to make sure nothing weird still depend on these?

Otherwise sounds good

**Review by malfet — APPROVED** [review]

**Review by huydhn — APPROVED** [review]
LGTM!  As ExecuTorch build doesn't work with 3.8, we can ping ExecuTorch folks about this and https://github.com/pytorch/test-infra/pull/5517 so that they don't need to figure out a way to support that version anymore (cc @guangy10 @dbort)

**Comment by kit1980** [comment]
> ping ExecuTorch folks about this

Thanks for pointing this out. I was actually looking at implementing matrix without 3.8 for ET.

**Pull request closed without merging**
