### PR TITLE
Torch manual seed to seed cuda devices

### PR DESCRIPTION
**Pull request by alykhantejani**
Seed all cuda devices when `torch.manual_seed` is called (issue #1615)

### CODE REVIEW

**Comment by alykhantejani** [comment]
urm a weird Conv.cpp seems to have snuck into this push - let me fix that.

**Comment by alykhantejani** [comment]
ok, It's fixed - sorry about that

**Review by apaszke — APPROVED** [review]

**Comment by Kaixhin** [comment]
What was the rationale behind this? I can't set random seeds in my CPU multiprocessing code because it's trying to set CUDA seeds.

```sh
  File "/home/ka709/moddrop/experiments/jaco_arm/test.py", line 13, in test
    torch.manual_seed(args.seed + rank)
  File "/home/ka709/miniconda3/lib/python3.6/site-packages/torch/__init__.py", line 133, in manual_seed
    torch.cuda.manual_seed_all(seed)
  File "/home/ka709/miniconda3/lib/python3.6/site-packages/torch/cuda/random.py", line 37, in manual_seed_all
    _lazy_init()
  File "/home/ka709/miniconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 83, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

**Comment by alykhantejani** [comment]
Bug report filed here: https://github.com/pytorch/pytorch/issues/1856

**Pull request merged**
