### PR TITLE
Correct torch.distributions.negative_binomial

### PR DESCRIPTION
**Pull request by ker2xu**
The definition (Negative Binomial distribution, i.e. distribution of the number of successful independent and identical Bernoulli trials before :attr:`total_count` failures are achieved.) in the PyTorch code is wrong. "Negative" means that it should be used to describe the number of failures instead of  suceesses. In addition, the "total_count" parameter used to initialize the NB class should represent the non-negative number of successes (instead of failures in the old code) until the experiment is stopped. The corrected code aligns with the correct descriptions in [Wikipedia](https://en.wikipedia.org/wiki/Negative_binomial_distribution)
Fixes #NA

cc @fritzo @neerajprad @alicanb @nikitaved

### CODE REVIEW

**Comment by kashif** [comment]
i don't remember 100% but i believe i based my implementation on the scipy and/or tensorflow-probability convention...

**Comment by ker2xu** [comment]
> i don't remember 100% but i believe i based my implementation on the scipy and/or tensorflow-probability convention...

I remembered that PyTorch's implementation of distributions module was based on tensorflow. And I also checked that TensorFlow's implementation of Negative Binomial distribution was also wrong when I made the fix for PyTorch. But I am busy these days and I do not have time to correct for TensorFlow which I rarely use. Hopefully somebody who find this pull request can fix the error in Tensorflow......

**Comment by kashif** [comment]
@ker2xu i dont know what the error is, it's just a convention with perhaps bad naming and changing this will break older models relying on this convention... can we fix up the documentation rather than the implementation?

**Comment by ker2xu** [comment]
@kashif I fully understand your concerns and this can be break many models. Honestly speaking, the original documentation and the implemented code even do not match well and are quite confusing. I do not know how to modify the documentation to get the correct results. Anyway, I put a script here to show what the correct negative log-likelihood should be. If you want to correct only the documentation, the negative log-likelihood should match with my implementation as below.

Original PyTorch code parameter name | Wikipedia parameter name
total_count | nb_r
probs | nb_p
```
def evaluate_neg_log_likelihood(mean, k, nb_r):
   import torch
   from torch.distributions.negative_binomial import NegativeBinomial
   mean = torch.tensor(mean)
   k = torch.tensor(k)
   nb_r = torch.tensor(nb_r)
   nb_p = nb_r / (nb_r + mean)
   nb = NegativeBinomial(total_count=nb_r, probs=nb_p)
   return f"nb_p = {nb_p};-log_p(pytorch) = {-nb.log_prob(k)};-log_p(mine) = {-(torch.lgamma(k + nb_r) - torch.lgamma(k + 1) - torch.lgamma(nb_r) + nb_r * torch.log(nb_r / (nb_r + mean)) + (k == 0.) * (mean == 0.) + k * torch.nan_to_num(torch.log(mean / (nb_r + mean)), nan=0.0, posinf=0.0, neginf=0.0))}, 'mode = {mode}'"

#    print("nb_p =", nb_p, ";-log_p(pytorch)=", -nb.log_prob(k), ";-log_p=", end="")
#    return -(torch.lgamma(k + nb_r) -
#             torch.lgamma(k + 1) -
#             torch.lgamma(nb_r) +
#             nb_r * torch.log(nb_r / (nb_r + mean)) +
#             (k == 0.) * (mean == 0.) + k * torch.nan_to_num(torch.log(mean / (nb_r + mean)), nan=0.0, posinf=0.0, neginf=0.0)
#             )


print("The negative log likelihood of k failures will happen before the nb_r th success given nb_p = nb_r / (nb_r + mean) for NB(nb_r, nb_p)")
print("evaluate_neg_log_likelihood(200, 400, 2)", evaluate_neg_log_likelihood(200, 400, 2))
print("evaluate_neg_log_likelihood(200, 200, 2)", evaluate_neg_log_likelihood(200, 200, 2))
print("evaluate_neg_log_likelihood(200, 100, 2)", evaluate_neg_log_likelihood(200, 100, 2))
print("evaluate_neg_log_likelihood(200, 0, 2)", evaluate_neg_log_likelihood(200, 0, 2))
```
The smaller the negative likelihood is, the closer of k should be to the mode of the NB. The negative log-likelihood computed by PyTorch does not follow the trend (e.g. nb_r=2) but my own implemented version does. The results are:
```
The negative log likelihood of k failures will happen before the nb_r th success given nb_p = nb_r / (nb_r + mean) for NB(nb_r, nb_p)
evaluate_neg_log_likelihood(200, 400, 2) nb_p = 0.009900989942252636;-log_p(pytorch) = 1840.07421875;-log_p(mine) = 7.216475486755371, 'mode = 100.0'
evaluate_neg_log_likelihood(200, 200, 2) nb_p = 0.009900989942252636;-log_p(pytorch) = 917.74072265625;-log_p(mine) = 5.917022705078125, 'mode = 100.0'
evaluate_neg_log_likelihood(200, 100, 2) nb_p = 0.009900989942252636;-log_p(pytorch) = 456.9168395996094;-log_p(mine) = 5.610161304473877, 'mode = 100.0'
evaluate_neg_log_likelihood(200, 0, 2) nb_p = 0.009900989942252636;-log_p(pytorch) = 0.01990066096186638;-log_p(mine) = 9.230240821838379, 'mode = 100.0'
```

**Comment by kashif** [comment]
so note that we are in the pytorch distributions tests, testing against the scipy implementation for all the methods like log-prob etc. and they match (after changing the params for the different conventions...) If I remember correctly, I had my original documentation for the parameters, which was later changed... see https://github.com/pytorch/pytorch/pull/25923 and https://github.com/pytorch/pytorch/pull/45693

it's obvious of course if you expect one convention for the parameters and don't change it for an implementation that has a different convention then the results will not match... just like in the tests for the negative binomial if you have a look... that doesn't mean its wrong, just a different convention and typically one can go from one convention to another... 

from a more practical point, these distributions in pytorch are as far as I have experienced, never explicitly created with some known parameters, but rather the parameters typically come as outputs from some neural network and then the log-probs are maximized with respect to some ground-truth and so one as long as that is implemented correctly, which it is, one can at inference time sample from such a distribution correctly and all is fine... 

As it stands I am afraid the maintainers will not accept this PR as far as I can tell...

**Comment by ker2xu** [comment]
> so note that we are in the pytorch distributions tests, testing against the scipy implementation for all the methods like log-prob etc. and they match (after changing the params for the different conventions...) If I remember correctly, I had my original documentation for the parameters, which was later changed... see #25923 and #45693
> 
> it's obvious of course if you expect one convention for the parameters and don't change it for an implementation that has a different convention then the results will not match... just like in the tests for the negative binomial if you have a look... that doesn't mean its wrong, just a different convention and typically one can go from one convention to another...
> 
> from a more practical point, these distributions in pytorch are as far as I have experienced, never explicitly created with some known parameters, but rather the parameters typically come as outputs from some neural network and then the log-probs are maximized with respect to some ground-truth and so one as long as that is implemented correctly, which it is, one can at inference time sample from such a distribution correctly and all is fine...
> 
> As it stands I am afraid the maintainers will not accept this PR as far as I can tell...

Well. I think I got it. PyTorch's version just exchanges the concept of "success" and "failure" and the user should specify (nb_r, 1 - nb_p) in PyTorch to use the NB ~ (nb_r, nb_p) in WikiPedia/Scipy. This is somewhat misleading and frustrating as Scipy also follows the conventions in WikiPedia but PyTorch does not. Of course, it is always not bad to keep backward compatibility...... 
But from a user's perspective, users have to spend more time to verify the correctness of the uncommon implementation of PyTorch and realize how to use it correctly if they have their models built with notations as in WikiPedia/Scipy. In addition, it would be strange to use a NB ~ (#failures, success probability) [PyTorch version] instead of NB ~ (#success, success probability) [Scipy/WikiPedia version].

**Comment by kashif** [comment]
right so lets perhaps add that explicitly to the documentation of this class and arguments so that folks are not confused...

**Pull request closed without merging**
