### PR TITLE
Make the __call__ op of ExportedProgram follow calling convention.

### PR DESCRIPTION
**Pull request by qihqi**
Convention documented here: https://github.com/pytorch/pytorch/blob/01069ad4be449f376cf88a56d842b8eb50f6e9b6/torch/_functorch/aot_autograd.py#L1034

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by zhxchen17 — COMMENTED** [review]
I guess we accidentally updated the third_party/ in this PR. please remove them.

**Comment by qihqi** [comment]
> 

done

**Review by zhxchen17 — APPROVED** [review]

**Pull request closed without merging**
