### PR TITLE
[ROCm] [ROCm 2.10+] enable fast relu path for fp16 in the Caffe2 backend on ROCm

### PR DESCRIPTION
**Pull request by iotamudelta**
With ROCm 2.10, the fast path in relu works.

### CODE REVIEW

**Review by bddppq — CHANGES_REQUESTED** [review]
Thanks for the update.

However we need to hold off this change until ROCm version gets updated. cc @xw285cornell

**Comment by bddppq** [comment]
One solution to get this unblocked before doing the ROCm upgrade is to setup [`HIP_VERSION`](https://github.com/pytorch/pytorch/blob/6edba76e20082a5696e508d7d493aed76df22571/cmake/Dependencies.cmake#L957) properly (i.e. 2.7/2.9/2.10 etc) and use it in the c++ code to guard the fast path.

**Comment by xw285cornell** [comment]
I agree, we should use HIP_VERSION to decide which code path it takes. Otherwise the backward compatibility is pretty bad.

**Comment by iotamudelta** [comment]
@xw285cornell @bddppq Couple of problems with that proposal (I understand the motivation behind it of course):
* (overriding) `HIP_VERSION` in PyTorch already squats on what should be a strictly ROCm-provided define - if anything I'd like to get rid of doing this inside PyTorch, not make it even worse
* same applies to explicitly defining `__HIP_PLATFORM_HCC__` in cmake, btw, as that's an `hcc` internal define
* `CUDA_VERSION` gets hipified to `HIP_VERSION` - typical range of values are 6000-10000. Now defining `HIP_VERSION` as, say, 210000 may trigger a set of interesting code paths that check `CUDA_VERSION > 8000` - so we'd definitely need to remove that hipification
* so far, we have consciously not paid attention to backwards compatibility. 1) Given that the CI only checks one ROCm version (typically the latest, unlike CUDA targets), any claims of backwards compatibility are superficial at best since there is no test coverage - and do we really want to add that coverage? 2) Given that AMD's monthly releases are free, open, and overriding each other, I am not sure what level of support for older ones is provided to the community since it is assumed that the community is on the latest release. 3) we are still adding features to ROCm and while theoretically it would work here to switch the code path based on ROCm release, it won't work for features that also impact testing (unless we want to discriminate in testing by ROCm release and see point 1) ).

So, this is a more intricate problem than just updating the `HIP_VERSION` define inside PyTorch and using it here.

That being said, I will fully support a feature request that HIP define a sane `HIP_VERSION`, remove the PyTorch override, remove the hipification of `CUDA_VERSION` to `HIP_VERSION` and clean this all up a bit.

For the time being we should wait for the CI to get updated to 2.10, I assumed as much. When will that happen? :-)

**Comment by xw285cornell** [comment]
What is HIP_VERSION defined today (if that's a hcc/hip internal macro)? I saw it's defined to HIP_MAJOR_VERSION in the cmake -- so that's 2? IMO the right way of fixing it is probably hipfify this entire CUDA_VERSION > xxx into HIP compatible one. 

When will you be considering backward compatibility? It's probably ok for now, but if we want to actually deploy it, this will be a requirement.

**Comment by iotamudelta** [comment]
Your reading is correct - it's coded to major version. I'd support having that define inside HIP and to a reasonable number (we are using `__hcc_workweek__` elsewhere which related but pure hcc).

Backwards compat: we'd need to discuss this (and what versions). It depends on CI testing targets.

**Comment by iotamudelta** [comment]
Part of the update to ROCm 3.1.1

**Pull request closed without merging**
