### PR TITLE
[nnc] Test cases for uneven split + reorder

### PR DESCRIPTION
**Pull request by bertmaher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#53091 [nnc] Test cases for uneven split + reorder**

Split with tail followed by reorder causes a segfault in NNC
Split with mask followed by reorder generates invalid code that writes out of
bounds

Differential Revision: [D26746254](https://our.internmc.facebook.com/intern/diff/D26746254/)

### CODE REVIEW

**Review by navahgar — APPROVED** [review]

**Review by bertmaher — COMMENTED** [review]
Obviously since these cause segfaults I won't land until those are cleared up ;-)

**Comment by navahgar** [comment]
> Obviously since these cause segfaults I won't land until those are cleared up ;-)

How about disabling and landing them? So that it is easier to test and enable on fix.

**Review by asuhan — COMMENTED** [review]
Up to you and the difficulty of the fix whether to land those disabled or wait, but obviously we'll need to re-review if we wait.

Out of curiosity, how did you find these, convolutions with shapes which need epilogue for vectorization?

**Comment by bertmaher** [comment]
> Up to you and the difficulty of the fix whether to land those disabled or wait, but obviously we'll need to re-review if we wait.
> 
> Out of curiosity, how did you find these, convolutions with shapes which need epilogue for vectorization?

Yeah I’ll go ahead and disable and land so we can parallelization the fixes.  

I found them when trying to vectorize a 56x56 convolution by a factor of 16; I was hoping either to get an 8-wide epilogue or a mask, and neither worked :-)

**Pull request closed without merging**
