### PR TITLE
.circleci: Remove should_run_job, no longer needed

### PR DESCRIPTION
**Pull request by seemethere**
Done at the recommendation of @ezyang

TODO:

- [x] Sync `XImportant`
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

### CODE REVIEW

**Review by ezyang — CHANGES_REQUESTED** [review]
Needs to be synchronized with the XImportant stuff

**Comment by seemethere** [comment]
This should be updated @ezyang, There's not too much to sync since most of it was already synced / removed in some for or fashion.

**Comment by ezyang** [comment]
Not convinced. I looked at another recent PR on master and checked to see which ones were being skipped. Here is a list of all of them; they're not being skipped on this PR.

* https://circleci.com/gh/pytorch/pytorch/4805364?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
* https://circleci.com/gh/pytorch/pytorch/4805371?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
* https://circleci.com/gh/pytorch/pytorch/4805370?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
* https://circleci.com/gh/pytorch/pytorch/4806694?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
* https://circleci.com/gh/pytorch/pytorch/4805357?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
* https://circleci.com/gh/pytorch/pytorch/4805356?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
* https://circleci.com/gh/pytorch/pytorch/4805360?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

This definitely doesn't line up with the claims made in this PR

**Review by ezyang — CHANGES_REQUESTED** [review]
I don't think they're synced

**Comment by seemethere** [comment]
@ezyang I now understand what you're requesting.

Have submitted a commit to remedy that, in the future we should look to doing config generation so this isn't an issue anymore.

**Comment by ezyang** [comment]
Thanks. The new list looks consistent with existing PRs.

Not for this PR, but I still feel like some of these jobs shouldn't be run on all PRs. Here are the ones that feel redundant:
  * binary_linux_libtorch_2_7m_cpu_devtoolset7_shared and binary_linux_libtorch_2_7m_cpu_gcc5_4_cxx11-abi_shared-with
  *  caffe2_onnx_py2_gcc5 and caffe2_onnx_main_py3_6_clang7 (this should get fixed "automatically" when py2 gets dropped)
  * pytorch_ios_11_2_1_arm64_build and pytorch_ios_11_2_1_arm64_custom_build and pytorch_ios_11_2_1_x86_64_build
  * pytorch_linux_xenial_py3_clang5_mobile_build and pytorch_linux_xenial_py3_clang5_mobile_custom_build_dynamic and pytorch_linux_xenial_py3_clang5_mobile_custom_build_static (but probably this can't actually get removed from default set until we have a reasonable way of toggling these on selective PRs)

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
