### PR TITLE
TestMathBits: test with neg and conj bit set

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #69026
* #68963
* #68950
* #68949
* __->__ #68948

The case where both the negative and conjugate bits are set
isn't tested currently despite being handled explicitly by `copy`.
In theory this shouldn't matter because neg_bit is only used for real
values, but it does mean the code in copy is untested. So, this just
runs it with a single sample as a sanity check.

Differential Revision: [D33064371](https://our.internmc.facebook.com/intern/diff/D33064371)

### CODE REVIEW

**Comment by anjali411** [comment]
What's the increase in test run time after this change?

**Comment by peterbell10** [comment]
`time pytest test_ops.py -k "TestMathBits and test_neg_conj_view"` shows 2 m 35 s on my machine. Although, if I comment out the `self._test_math_view` call it still takes 2 m 23 s so almost all the time is spent in `op.sample_inputs`.

**Comment by ngimel** [comment]
@peterbell10 do you have a machine with GPUs? If so, running with `PYTORCH_TEST_SKIP_CUDA_MEM_LEAK_CHECK=1 ` will reduce test time a lot. On PR CIs we run with it (but on master CI I think leak checking is still enabled). So most of the time is likely test set up and teardown, not sample_inputs. Either way, I think time increase is acceptable.

**Comment by peterbell10** [comment]
Oh wow, it only took 15 seconds total with that flag. I wish I'd known about it sooner.

**Review by anjali411 — APPROVED** [review]
Thanks @peterbell10

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33064371).

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33064371).

**Comment by anjali411** [comment]
The test failures look real:

```
======================================================================
ERROR [0.001s]: test_neg_conj_view_sub_cpu_complex128 (__main__.TestMathBitsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 753, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 1267, in test_neg_conj_view
    samples = samples[:1]
TypeError: 'generator' object is not subscriptable

======================================================================
ERROR [0.001s]: test_neg_conj_view_true_divide_cpu_complex128 (__main__.TestMathBitsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 753, in test_wrapper
    return test(*args, **kwargs)
  File "test_ops.py", line 1267, in test_neg_conj_view
    samples = samples[:1]
TypeError: 'generator' object is not subscriptable
```

**Comment by peterbell10** [comment]
Should be fixed now. Just changed it out for `itertools.islice`.

**Comment by anjali411** [comment]
@peterbell10 are the failures related? if not, can you please rebase?

**Comment by peterbell10** [comment]
Looks like the changes to `test_neg_view` fixed `as_strided` which was marked as x-fail. Removing the x-fail decorator fixes the tests locally.

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33064371).

**Pull request closed without merging**
