### PR TITLE
einsum: don't inplace modify arguments (fixes: #7763)

### PR DESCRIPTION
**Pull request by t-vi**
Thank you, Pierce Freeman, for the report and minimal example!

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Review by apaszke — APPROVED** [review]

**Comment by ezyang** [comment]
```
19:25:17 C:/Jenkins/workspace/pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-build/aten/src\ATen/optional.h(345): error C2614: 'at::optional<at::Tensor>': illegal member initialization: 'OptionalBase' is not a base or member
```

I believe this is an MSVC bug, and the easiest thing to work around it is avoid using `at::optional` in this context, if you can. (Have not read the patch.)

**Comment by t-vi** [comment]
@ezyang Thanks I think I stayed clear from RoiPooling?

**Comment by ezyang** [comment]
You're right, CI is red right now. Hang tight!

**Comment by t-vi** [comment]
@ezyang Could you rerun the test, please? I would love to see #7763 fixed.

**Pull request merged**
