### PR TITLE
Fix anomaly mode memory leak

### LINKED ISSUE #51349: autograd.grad with set_detect_anomaly(True) will cause memory leak
## 🐛 Bug

using `torch.autograd.grad()` with `torch.autograd.set_detect_anomaly(True)` will cause memory leak

## To Reproduce

Run the code snippet below.
It will have about 2MiB GPU memory consumption increasing each iteration.

If comment out the `set_detect_anomaly` line, then there is no memory leak, with constant memory consumption.

```python
import torch
torch.autograd.set_detect_anomaly(True) # if comment out this, no leak
for rep in range(1000):
    batch = torch.ones(10, 30000).cuda().requires_grad_()
    y=batch.norm()
    grad = torch.autograd.grad(
        outputs=y, inputs=batch,
        create_graph=True, retain_graph=True, only_inputs=True)[0]
    print("memory allocated:", float(torch.cuda.memory_allocated()/1024**2), "MiB")
    pass
```

## Expected behavior

No memory leak with or without `set_detect_anomaly(True)`

## Environment

 - PyTorch Version: 1.7.1
 - OS: Linux
 - How you installed PyTorch: conda, source: `-c pytorch`
 - Python version: 3.8.5
 - CUDA/cuDNN version: cuda11.0

## Additional context

BTW, if replace `y=batch.norm()` with `y=batch.mean()`, then there is no memory leak with or without `set_detect_anomaly`, which makes me very confused.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

### PR DESCRIPTION
**Pull request by soulitzer**
Fixes #51349

The memory leak happens when 1) `create_graph` is True AND 2) detect anomaly mode is on. When a backward node's constructor is called during backward, the current evaluating node is assigned as a "parent" of the created node. The code that assigns the parent encounters the below issue:

`functionToPyObject(parent_node)` returns a new PyObject (with refcount 1) or if PyObject already exists, increments its refcount by 1. However [PyDict_SetItem](https://github.com/python/cpython/blob/1b55b65638254aa78b005fbf0b71fb02499f1852/Objects/dictobject.c#L1532) calls into [insertdict](https://github.com/python/cpython/blob/v3.8.1/Objects/dictobject.c#L1034) which increments refcount again. This means that when dict is destroyed, the refcount of the PyObject is at least one. This keeps `parent_node` (the backward function) alive, which then keeps the saved tensor alive.

Similar calls in the codebase to `functionToPyObject` won't require Py_DECREF if it is then passed into a tuple (instead of dict), because the analogous PyTuple_SetItem call does not increment refcount.

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Good catch!
Actually looking more closely into this file, it might not be the only one :/
In general, how we do things is:
- If a function returns a borrowed reference, then we store it in a `PyObject*`. That way we know we don't own it and nothing needs to be done on destruction.
- If a function returns a new reference, then we store it in a `THPObjectPtr`. Is is a custom class we have that ensures that the refcount is decremented when it is destructed.

So here the result of `functionToPyObject` should definitely be in a `THPObjectPtr`.
I think I didn't do a proper review of that on the parent printing PR because the calls to PyObject_GetAttrString and PyObject_CallMethod above should also be stored in `THPObjectPtr`.

**Comment by soulitzer** [comment]
> Good catch!
> Actually looking more closely into this file, it might not be the only one :/
> In general, how we do things is:
> 
>     * If a function returns a borrowed reference, then we store it in a `PyObject*`. That way we know we don't own it and nothing needs to be done on destruction.
> 
>     * If a function returns a new reference, then we store it in a `THPObjectPtr`. Is is a custom class we have that ensures that the refcount is decremented when it is destructed.
> 
> 
> So here the result of `functionToPyObject` should definitely be in a `THPObjectPtr`.
> I think I didn't do a proper review of that on the parent printing PR because the calls to PyObject_GetAttrString and PyObject_CallMethod above should also be stored in `THPObjectPtr`.

Ahh good to know! I've made the updates.

**Review by albanD — COMMENTED** [review]
That looks great!

Do you think we can write a simple test to make sure this is properly fixed?
I think you can make one by using a similar logic as this one: https://github.com/pytorch/pytorch/blob/a3f2fe0d52dee993056ef4858f4c7f35fa90ff4f/test/test_autograd.py#L6499-L6527

**Review by albanD — APPROVED** [review]
Thanks for the test!
LGTM

**Comment by soulitzer** [comment]
@albanD ahh I added another test in the meantime... this one checks that metadata dict is destroyed properly in the nested case. But now I'm thinking it might've not been worth the effort.

**Comment by albanD** [comment]
More tests is always better. Especially if they run instantly like this one!

**Pull request closed without merging**
