### PR TITLE
ban .sizes() and .strides() calls in derivatives.yaml

### PR DESCRIPTION
**Pull request by bdhirsh**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #87255
* #87108
* __->__ #86611

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Should we remove the replace rule for these?
Also you should do the same for `size(int)` and `stride(int)` as well (see the regex in the replace list).

**Comment by bdhirsh** [comment]
Agreed on both accounts - I'll update soon (deleting the existing sizes/strides regex, and erroring on `.size(int)` too)

**Review by wconstab — APPROVED** [review]

**Comment by bdhirsh** [comment]
Sadly this won't be ok to merge yet, since we need to wait on symintify'ing `split()` to go through (Alban's working on that, but it'll take some time due to internal failures).

I'm hoping to land the big derivatives.yaml change asap though (below this in the stack).

**Review by albanD — APPROVED** [review]
SGTM
Small optional improvement you could do.

**Pull request closed without merging**
