### PR TITLE
Add LazyBatchNormXd

### PR DESCRIPTION
**Pull request by asi1024**
Same diff with #51548 (cc. @albanD)

### CODE REVIEW

**Comment by asi1024** [comment]
@albanD Could you help me to pass the doctest?

**Review by albanD — APPROVED** [review]
Not sure why but https://github.com/pytorch/pytorch/pull/51825 was actually the fix for the doc_test. All is green now.
Sorry for the extra delay!

**Comment by albanD** [comment]
Could you just rebase on top of master please? There are some merge conflicts.

**Comment by asi1024** [comment]
Rebased!

**Comment by albanD** [comment]
Thanks!
Don't worry about the flake8 issues, this is already happening on master.

**Comment by asi1024** [comment]
Thanks!

**Pull request closed without merging**
