### PR TITLE
Manually update XLA hash to the latest

### PR DESCRIPTION
**Pull request by yeounoh**
Follow-up on https://github.com/pytorch/pytorch/pull/80178#issuecomment-1177161520

cc @seemethere @malfet

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@yeounoh why does it have 230 commits?

**Comment by yeounoh** [comment]
> @yeounoh why does PR have 230 commits in it?

Rebased the master -- let me reset. 

By the way, is this a known issue?
`.jenkins/pytorch/common_utils.sh: line 147: jq: command not found`

**Comment by yeounoh** [comment]
Ok, the xla workflow is green again cc @malfet

**Pull request closed without merging**
