### PR TITLE
Change SymIntNode into an intrusive pointer

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #82467
* #82477
* __->__ #82432

This will make the pointer type a single word, which is important
for packing it into an int64_t

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Pull request closed without merging**
