### PR TITLE
Back out "[PyTorch] Add Expanded call stack to nodes (#108426)"

### PR DESCRIPTION
**Pull request by clee2000**
@diff-train-skip-merge
Summary:
Multisecting finding D46578700 is causing RaaS SL failing on raas_service.tw.mem.anon S365748
Backing it out now

Test Plan: https://www.internalfb.com/servicelab/experiment/2202497036/

### CODE REVIEW

**Comment by clee2000** [comment]
closing in favor of https://github.com/pytorch/pytorch/pull/109468

**Review by DanilBaibak — COMMENTED** [review]
Approved for purpose to revert the PR

**Review by DanilBaibak — APPROVED** [review]
Approved for purpose to revert the PR

**Pull request closed without merging**
