### PR TITLE
Don't guard on the exact int value on conversion to bool

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96008

Fixes https://github.com/pytorch/pytorch/issues/95981

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ezyang** [comment]
BAH XLAAAAAA

**Pull request closed without merging**
