### PR TITLE
Reland Bugfix NAN and Inf handling for scatter_reduce (amin and amax)

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #75454
* __->__ #75651

### CODE REVIEW

**Comment by cpuhrsch** [comment]
@mikaylagawarecki - could you also add a unit test that were to fail if this wasn't covered?

**Review by cpuhrsch — APPROVED** [review]

**Comment by malfet** [comment]
@pytorchbot revert this, as it causes internal build failures, as `C10_DEVICE min_propagate_nan` calls host-only `min` function, see:
```
caffe2/aten/src/ATen/native/SharedReduceOps.h(42): error: calling a constexpr __host__ function("min") from a __device__ function("min_propagate_nan") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
          detected during instantiation of "scalar_t min_propagate_nan(scalar_t, scalar_t) [with scalar_t=c10::Half]" 
caffe2/aten/src/ATen/cuda/Atomic.cuh(395): here
```

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
