### PR TITLE
Remove fetch-depth from _calc_docker_img

### PR DESCRIPTION
**Pull request by malfet**
As in current form it will only work for PRs with one commit. 
Checkout full PyTorch repo (but skip submodules)

Example of failure in PR with multiple commits, see https://github.com/pytorch/pytorch/actions/runs/4389777316/jobs/7687694067#step:4:68

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Review by izaitsevfb — APPROVED** [review]

**Review by osalpekar — APPROVED** [review]

**Comment by huydhn** [comment]
I hope to use a shallow checkout to make linter process lighter, but a greater depth is needed to get the merge base, so there is no workaround for this beside removing `fetch-depth` or set it to a higher value.

**Pull request closed without merging**
