### PR TITLE
Add some missing docs for tensor methods and attributes, new unittest to enforce tensors.rst no longer miss anything

### PR DESCRIPTION
**Pull request by zasdfgbnm**
This depend on https://github.com/pytorch/pytorch/pull/16039

This prevent people (reviewer, PR author) from forgetting adding things to `tensors.rst`.

When something new is added to `_tensor_doc.py` or `tensor.py` but intentionally not in `tensors.rst`, people should manually whitelist it in `test_docs_coverage.py`.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Looks like there are still some missing docs?

**Comment by zasdfgbnm** [comment]
@ezyang Let me look into it.

**Comment by zasdfgbnm** [comment]
@ezyang I just updated the test to make it pass. The update is mainly on improving error messages, as well as manually whitelist all nn functionals mistakely binded to `torch.*`, so this test now serves as a list for https://github.com/pytorch/pytorch/issues/16322

**Pull request closed without merging**
