### PR TITLE
Moving CommTensor from tests to private _spmd folder

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #84655

### CODE REVIEW

**Comment by mrshenli** [comment]
Test error message: 

```
2022-09-08T03:13:38.4135619Z ERROR ENCOUNTERED WHEN UPLOADING TO SCRIBE: {"errorMessage": "HTTP Error 500: Internal Server Error", "errorType": "HTTPError", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 57, in lambda_handler\n    return urlopen(req, data=json.dumps(data).encode()).read()\n", "  File \"/var/lang/lib/python3.8/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n", "  File \"/var/lang/lib/python3.8/urllib/request.py\", line 531, in open\n    response = meth(req, response)\n", "  File \"/var/lang/lib/python3.8/urllib/request.py\", line 640, in http_response\n    response = self.parent.error(\n", "  File \"/var/lang/lib/python3.8/urllib/request.py\", line 569, in error\n    return self._call_chain(*args)\n", "  File \"/var/lang/lib/python3.8/urllib/request.py\", line 502, in _call_chain\n    result = func(*args)\n", "  File \"/var/lang/lib/python3.8/urllib/request.py\", line 649, in http_error_default\n    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n"]}
```

**Review by wanchaol — APPROVED** [review]
nice!

**Comment by mrshenli** [comment]
error is irrelevant

```
(`torch.utils.benchmark`)
  - You can do either of these two things to fix this problem:
    - To make it NOT public: either define a `__all__` for `torch.utils.benchmark` or add a `_` at the beginning of the name
    - To make it look public: make sure the `__module__` is properly set and points to a submodule of `torch.utils.benchmark`
# torch.utils.benchmark.Tuple:
```

**Comment by mrshenli** [comment]
Hey @kit1980 

The test failures look irrelevant to this PR. Or I miss anything?

```
  test_correct_module_names (__main__.TestPublicBindings)
An API is considered public, if  its  `__module__` starts with `torch.` ... /opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:191: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn(
FAIL (3.296s)
    test_correct_module_names failed - num_retries_left: 3
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_public_bindings.py", line 384, in test_correct_module_names
    self.assertTrue(not failure_list, msg)
AssertionError: False is not true : All the APIs below do not meet our guidelines for public API from https://github.com/pytorch/pytorch/wiki/Public-API-definition-and-documentation.
Make sure that everything that is public is expected (in particular that the module has a properly populated `__all__` attribute) and that everything that is supposed to be public does look public (it does not start with `_` and has a `__module__` that is properly populated).

Full list:
# torch.fx.experimental.proxy_tensor.ProxySymDispatchMode:
  - Is NOT public: it is not inside the module's (`torch.fx.experimental.proxy_tensor`) `__all__`
  - Does look public: it does look public because it follows the rules from the doc above (does not start with `_` and has a proper `__module__`).
  - You can do either of these two things to fix this problem:
    - To make it public: add it from the modules's (`torch.fx.experimental.proxy_tensor`) `__all__`
    - To make it NOT look public: make its name start with `_`
```

**Comment by kit1980** [comment]
It's pretty clear from https://hud.pytorch.org/ that the test failures are because of this PR: the failures started when the PR landed, and stopped when the revert landed.

Maybe the error messages are not helpful. I'll look and try to understand how to fix this PR.

**Comment by mrshenli** [comment]
I am trying again after adding `__all__`: https://github.com/pytorch/pytorch/pull/84719

Maybe because I imported `proxy_tensor.py` without defining `__all__` in the new module.

**Pull request closed without merging**
