### PR TITLE
[BUG FIX] Refactor _scale_attn_mask_fusion_kernel to Use Runtime Argument Instead of Template Parameter

### PR DESCRIPTION
**Pull request by abhishek-iitmadras**
**Description**

**_[BUG FIX]_**
This PR fixes a bug which happens during compilation with GCC 11.4 compiler in the FlashAttentionKernel.cpp file. This issue doesn't seem to be with PyTorch main branch but gets introduced with our SVE PR changes (https://github.com/pytorch/pytorch/pull/119571 ) + PyTorch main.

See the CI Pipeline failing in our PR:
https://github.com/pytorch/pytorch/actions/runs/9895714768/job/27336251795?pr=119571 

```
/var/lib/jenkins/workspace/build/aten/src/ATen/native/cpu/FlashAttentionKernel.cpp.SVE256.cpp
during RTL pass: expand
In file included from /var/lib/jenkins/workspace/build/aten/src/ATen/native/cpu/FlashAttentionKernel.cpp.SVE256.cpp:1:
/var/lib/jenkins/workspace/aten/src/ATen/native/cpu/FlashAttentionKernel.cpp: In lambda function:
/var/lib/jenkins/workspace/aten/src/ATen/native/cpu/FlashAttentionKernel.cpp:290:57: internal compiler error: in emit_move_insn, at expr.c:3821
  290 |   at::parallel_for(0, batchSize * num_head * qSlice, 1, [&](int64_t begin, int64_t end) {
      |                                                         ^
0xffffb03f73fb __libc_start_call_main
	../sysdeps/nptl/libc_start_call_main.h:58
0xffffb03f74cb __libc_start_main_impl
	../csu/libc-start.c:392
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.

[5731/6839] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/cpu/CatKernel.cpp.SVE256.cpp.o
[5732/6839] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/cpu/GridSamplerKernel.cpp.SVE256.cpp.o
```

This issue with compilation only happens with GCC 11.4 and works well with the latest GCC 12.3 compiler and also the Clang compiler. The issue is related to the check for `is_b_stride_zero` introduced as a template parameter (compile time check complexity) in the following commit: https://github.com/pytorch/pytorch/commit/5da428d9ebab50be5974e228e8a83c54af02ecb6  which was added recently into FlashAttentionKernel.cpp file.

This PR fixes the above compilation failure with GCC 11.4 compiler.

cc : @Valentine233 @yanbing-j @mingfeima @malfet @jgong5 @r-barnes 

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by maajidkhann** [comment]
Hello @Valentine233. This commit (https://github.com/pytorch/pytorch/pull/128816/files) has introduced a compilation bug with our open SVE PR (https://github.com/pytorch/pytorch/pull/119571/)

This PR fixes the issue which is bug with gcc 11.4 compiler which comes as default compiler with Ubuntu22 base OS CI machines. The issue doesn't happen with gcc12 and clang compilers.

Can you please look into this issue.

CC @jgong5 @drisspg @malfet

**Comment by malfet** [comment]
This would make flash attention slower, isn't it? Wouldn't it be a better way to workaround the issue by explicitly specifying all three template parameters?

**Comment by jgong5** [comment]
> This would make flash attention slower, isn't it? Wouldn't it be a better way to workaround the issue by explicitly specifying all three template parameters?

I agree that we'd better not sacrifice the performance by making this flag as a runtime one. Does explicitly specifying all the template args address the problem?

**Comment by jgong5** [comment]
> > Does explicitly specifying all the template args address the problem?
> 
> No, I tried but got the same error. The root cause appears to be the complexity introduced by using boolean as a template parameter, leading to multiple template instantiation and increased compiler workload. By converting the boolean template parameter to function argument, reduced this complexity, ensuring only one version of function is generated and the conditional logic is handled during runtime which resolved the ICE.
> 
> cc @jgong5 @malfet

Since it is a compiler issue and only happens with SVE build, an alternative solution is to use some macro to work around the problem without changing things without SVE build.

**Comment by abhishek-iitmadras** [comment]
> > > Does explicitly specifying all the template args address the problem?
> > 
> > 
> > No, I tried but got the same error. The root cause appears to be the complexity introduced by using boolean as a template parameter, leading to multiple template instantiation and increased compiler workload. By converting the boolean template parameter to function argument, reduced this complexity, ensuring only one version of function is generated and the conditional logic is handled during runtime which resolved the ICE.
> > cc @jgong5 @malfet
> 
> Since it is a compiler issue and only happens with SVE build, an alternative solution is to use some macro to work around the problem without changing things without SVE build.

@jgong5 
Done as suggested.

**Review by jgong5 — APPROVED** [review]

**Pull request closed without merging**
