### PR TITLE
[ao] public v private stubs and utils

### PR DESCRIPTION
**Pull request by HDCharles**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #87885

Summary: from utils, made _module_type_list, _func_list, _method_list,
_get_combined_dict, _is_per_tensor, _is_per_channel, _getattr_from_fqn,
_to_underlying_dtype, _get_swapped_custom_module_class,
_activation_dtype, _weight_dtype, _activation_is_statically_quantized,
_activation_is_dynamically_quantized, _activation_is_int8_quantized,
_activation_is_int32_quantized, _weight_is_quantized,
_weight_is_statically_quantized, _op_is_int8_dynamically_quantized,
_get_qconfig_dtypes, _get_quant_type, _check_min_max_valid,
_calculate_qmin_qmax, _has_no_children_ignoring_parametrizations
private.

from stubs just added __all__

Test Plan: python test/test_public_bindings.py

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D40814549](https://our.internmc.facebook.com/intern/diff/D40814549)

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

### CODE REVIEW

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40814549).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40814549).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40814549).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40814549).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40814549).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40814549).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40814549).

**Review by jerryzh168 — APPROVED** [review]

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40814549).

**Pull request closed without merging**
