### PR TITLE
[aot_inductor] fix hardcoded output dtype

### PR DESCRIPTION
**Pull request by frank-wei**
Summary: as titled

Reviewed By: chenyang78

Differential Revision: D47779519

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by chenyang78 — APPROVED** [review]
LGTM. Thanks!

**Review by desertfire — COMMENTED** [review]
It's a little strange to retrieve dtype as string. Sherlock is using thrift types for his fallback runtime prototyping. Should we do something similar here? How does AIT handle return type info?

**Comment by chenyang78** [comment]
> It's a little strange to retrieve dtype as string. Sherlock is using thrift types for his fallback runtime prototyping. Should we do something similar here? How does AIT handle return type info?

AIT doesn't use ATen dtype inside .so. We pass our own dtype enum along with AITData:

https://github.com/facebookincubator/AITemplate/blob/main/static/include/model_interface.h#L67

where AIT dtype is converted from its ATen counterpart:

https://github.com/facebookincubator/AITemplate/blob/main/fx2ait/fx2ait/csrc/AITModelImpl.cpp#L415

I guess this part will be eventually replaced by your ABI changes, where we define a similar AOT dtype enum?

**Comment by desertfire** [comment]
> > It's a little strange to retrieve dtype as string. Sherlock is using thrift types for his fallback runtime prototyping. Should we do something similar here? How does AIT handle return type info?
> 
> AIT doesn't use ATen dtype inside .so. We pass our own dtype enum along with AITData:
> 
> https://github.com/facebookincubator/AITemplate/blob/main/static/include/model_interface.h#L67
> 
> where AIT dtype is converted from its ATen counterpart:
> 
> https://github.com/facebookincubator/AITemplate/blob/main/fx2ait/fx2ait/csrc/AITModelImpl.cpp#L415
> 
> I guess this part will be eventually replaced by your ABI changes, where we define a similar AOT dtype enum?

We will need to converge on the dtype definition. The current implementation is good for now.

**Review by desertfire — APPROVED** [review]

**Comment by frank-wei** [comment]
> > > It's a little strange to retrieve dtype as string. Sherlock is using thrift types for his fallback runtime prototyping. Should we do something similar here? How does AIT handle return type info?
> > 
> > 
> > AIT doesn't use ATen dtype inside .so. We pass our own dtype enum along with AITData:
> > https://github.com/facebookincubator/AITemplate/blob/main/static/include/model_interface.h#L67
> > where AIT dtype is converted from its ATen counterpart:
> > https://github.com/facebookincubator/AITemplate/blob/main/fx2ait/fx2ait/csrc/AITModelImpl.cpp#L415
> > I guess this part will be eventually replaced by your ABI changes, where we define a similar AOT dtype enum?
> 
> We will need to converge on the dtype definition. The current implementation is good for now.

We will revisit this part once dtype convergency is coming. Thanks.

**Pull request closed without merging**
