### PR TITLE
fix functionalization <> resnet18, make ProxyTensor work with tensor-less decomps

### PR DESCRIPTION
**Pull request by bdhirsh**
This should fix a few of the errors I was seeing when I turned on functionalization in torchbench. It also fixes this AOTAutograd repro with resnet18:
```
import torch
from torchvision.models import resnet18

from functorch._src.compilers import nop
from functorch._src.aot_autograd import aot_module
from functorch.compile import config

config.use_functionalize = True

model = resnet18().cuda().half().to(memory_format=torch.channels_last)
input = torch.randn(256, 3, 224, 224, device='cuda', dtype=torch.float16) \
             .to(memory_format=torch.channels_last).detach().requires_grad_(True)
input_expected = input.clone().detach().requires_grad_(True)

fn = aot_module(model, nop)
out = fn(input)
out_expected = model(input_expected)
print(torch.allclose(out, out_expected))

out.sum().backward()
out_expected.sum().backward()
print(torch.allclose(input.grad, input_expected.grad))
```

The problem was that functorch adds a decomp to the decomp table for `new_zeros`:
```
@register_decomposition(aten.new_zeros, aot_autograd_decompositions)
def new_zeros(inp, size, dtype=None, layout=None, device=None, pin_memory=None):
    return torch.zeros(size, dtype=inp.dtype, device=inp.device)
```

When calling that decomp from inside of `ProxyTensorDispatchMode`, the ProxyTensorMode is already disabled, and `torch.zeros` doesn't take in any tensor-like arguments, so we never end up dispatching back into python again.

The way that manifests is that the output of `new_zeros()` gets baked as a constant into the AOTAutograd FX graph.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #83297
* __->__ #83207

### CODE REVIEW

**Comment by bdhirsh** [comment]
Tangentially, I wonder what we can do to make this easier to debug. My debugging process was:

(1) I Realized that I can repro the error when using `channels_last` tensor inputs, and the error goes away when I remove t hem
(2) Printed out the FX graph from AOTAutograd with/without the channels_last change, try to see what's different
(3) Noticed that there are a few extra `as_strided_()` calls in the problematic graph
(4) Noticed that the error goes away if I don't trace the backward, and only trace the forward. Hmm...
(5) Identified `as_strided_backward()` as the culprit. From there, gdb helped me realize that the output of `new_zeros()` wasn't a ProxyTensor for some reason ([code link](https://github.com/pytorch/pytorch/blob/8a6b076196f4169910b2c98d37e1faeaec316050/torch/csrc/autograd/FunctionsManual.cpp#L2794))

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
add a test sometime thx

**Comment by bdhirsh** [comment]
Added a test

**Pull request closed without merging**
