### PR TITLE
[FSDP] Optim state: ignore params if not in dict

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #76784 [FSDP] Include buffers in `ignored_modules`
* **#76671 [FSDP] Optim state: ignore params if not in dict**

This fixes an internal case where some parameters do not have entries in the optimizer state dict.

Differential Revision: [D36111582](https://our.internmc.facebook.com/intern/diff/D36111582)

### CODE REVIEW

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36070703).

**Review by zhaojuanmao — APPROVED** [review]

**Review by rohan-varma — APPROVED** [review]
Great fix! Do you think adding a UT would be useful?

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36111582).

**Comment by awgu** [comment]
> Great fix! Do you think adding a UT would be useful?

Good idea! Added some unit tests :)

I am re-requesting review since the code added is non-negligible. Feel free to just skim over the added test.

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36111582).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36111582).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36111582).

**Review by rohan-varma — APPROVED** [review]
Lgtm

**Pull request closed without merging**
