### PR TITLE
More flexible test parametrization with @reparametrize

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #138370
* __->__ #138369

**Background:** The `@parametrize` decorator enjoys widespread usage as a convenient tool for ensuring extensive test coverage. One particular feature that makes this easy is the ability to stack such decorators, testing over the cross-product of inputs. Example:
```python
class MyTestClass(TestCase):
    @parametrize("x", range(3))
    @parametrize("y", [False, True])
    def test_foo(self, x, y):
        # Invoked with:
        # x=0, y=False
        # x=1, y=False
        # x=2, y=False
        # x=0, y=True
        # x=1, y=True
        # x=2, y=True
        ...
```

Note that the `@ops` and `@modules` decorators employ the same underlying machinery for parametrizing over `OpInfo` / `ModuleInfo` entries. These decorators also parametrize over op-specific `device` / `dtype` info *according to what is supported for each op*.
```python
class MyTestClass(TestCase):
    @ops(op_db)
    def test_foo(self, op, device, dtype):
        # Invoked each OpInfo in the db along with each device / dtype that corresponds
        # with this op according to the OpInfo entry.
        ...
```

Note that this in contrast to the naive cross product between ops and devices / dtypes, which would generate too many tests. Certain use cases benefit from a similar type of flexible parametrization that is more intelligent than simple cross-product composition. It is expensive to generate / run too many tests, even if the unneeded ones are skipped appropriately.

This PR attempts to generalize such flexible parametrization and satisfy these use cases through the introduction of a `@reparametrize` decorator, which operates on an existing parametrizer and allows for customized on-the-fly parametrization through the use of an `adapter_fn`. Examples:
```python
# adapter_fn that adds a new arg
 def include_is_even_arg(test_name, param_kwargs):
    x = param_kwargs["x"]
    is_even = x % 2 == 0
    new_param_kwargs = dict(param_kwargs)
    new_param_kwargs["is_even"] = is_even
    is_even_suffix = "_even" if is_even else "_odd"
    new_test_name = f"{test_name}{is_even_suffix}"
    yield (new_test_name, new_param_kwargs)

# adapter_fn that excludes certain values
def exclude_odds(test_name, param_kwargs):
    x = param_kwargs["x"]
    is_even = x % 2 == 0
    yield None if not is_even else (test_name, param_kwargs)

class MyTestClass(TestCase):
    @reparametrize(parametrize("x", range(5)), include_is_even_arg)
    def test_foo(self, x, is_even):
        # Invoked with both the x value and the new is_even arg
        ...

    @reparametrize(parametrize("x", range(5)), exclude_odds)
    def test_bar(self, x):
        # Only invoked with even x values
        ...
```

For a more real-world use case, imagine you want to write a set of OpInfo tests that parametrize over additional op-specific things beyond `device` / `dtype` (in NJT's case, this includes contiguity type, whether to operate over the batch / ragged / other dims, etc.). The `@reparametrize` decorator allows you to customize the `@ops` parametrization to add in these additional args as they make sense on a per-op basis.

### CODE REVIEW

**Comment by soulitzer** [comment]
Being able to avoid generate exponentially many test cases sounds generally useful, though specifically for the NJT case do you think worth it for the failure combinations to still generate those test case and then xfail? Or do you think that is too expensive and better to rely on error_inputs for that.

**Comment by jbschlosser** [comment]
ping @pytorch/pytorch-dev-infra is there someone on your end who is willing to review this?

**Comment by janeyx99** [comment]
Do you have a code pointer for how you plan to use this in the more real-world use case: (in NJT's case, this includes contiguity type, whether to operate over the batch / ragged / other dims, etc.)?

Code looks good + fine, but I'm not sure if it's needed given that you could have just filtered the inputs to the initial parametrizer for odds/evens. In other words, I'm looking for a case that is hard to implement by just applying the adapter function directly on the first @parametrize call.

**Comment by jbschlosser** [comment]
@janeyx99 sure thing, see the next PR in the stack for one :) Here I want the ability to do op-specific parametrization over supported dim types (e.g. batch, ragged, normal) and contiguity types (contiguous, non-contig with holes, non-contig transposed), and I can't just go edit the original `@ops` decorator and add these NJT-specific things.
```python
# Reparametrizer that automatically parametrizes over the appropriate dim_type
# for each op that supports batch-wise operation and contiguity type for all ops.
# This is intended to be used with torch.testing._internal.common_utils.reparametrize.
def include_dim_type_and_contiguity(test_name, param_kwargs):
    op = param_kwargs["op"]
    extra_op_data = op._extra_op_data

    dim_types = extra_op_data.dim_support or [None]
    for contiguity, dim_type in product(extra_op_data.contiguity_support, dim_types):
        new_param_kwargs = dict(param_kwargs)
        new_param_kwargs["dim_type"] = dim_type
        dim_type_suffix = "" if dim_type is None else f"_{str(dim_type)}"
        new_param_kwargs["contiguity"] = contiguity
        contiguity_suffix = f"_{str(contiguity)}"
        new_test_name = f"{test_name}{dim_type_suffix}{contiguity_suffix}"
        yield (new_test_name, new_param_kwargs)
```

Another case: for ops that have in-place variants, I want to parametrize a test over `inplace in [False, True]`. For ops without in-place variants, the test function should always receive `inplace=False`. Using the decorator from this PR avoids generating a ton of useless, skipped `inplace=True` tests for ops that don't have in-place variants, which I believe is more common.

**Review by janeyx99 — APPROVED** [review]
I'm sufficiently convinced

**Pull request closed without merging**
