### PR TITLE
only scatter in forward if multi-device per process

### PR DESCRIPTION
**Pull request by astooke**
Scatter is unnecessary if only using one device, and it breaks on some custom data structures like namedtuple, so would like to avoid :)

### CODE REVIEW

**Review by apaszke — APPROVED** [review]

**Comment by soumith** [comment]
the test failures all look legit

**Review by zou3519 — CHANGES_REQUESTED** [review]
tests are failing

**Comment by astooke** [comment]
Anything I can do to help?  I'm not familiar with the tests breaking?

**Comment by SsnL** [comment]
test failures definitely look relevant, e.g.
```

Jul 22 14:52:35 Traceback (most recent call last):
Jul 22 14:52:35   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Jul 22 14:52:35     self.run()
Jul 22 14:52:35   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Jul 22 14:52:35     self._target(*self._args, **self._kwargs)
Jul 22 14:52:35   File "test_c10d.py", line 539, in _run
Jul 22 14:52:35     getattr(self, self.id().split(".")[2])()
Jul 22 14:52:35   File "test_c10d.py", line 503, in wrapper
Jul 22 14:52:35     fn(self)
Jul 22 14:52:35   File "test_c10d.py", line 54, in wrapper
Jul 22 14:52:35     return func(*args, **kwargs)
Jul 22 14:52:35   File "test_c10d.py", line 2397, in test_multiple_outputs_multiple_backward
Jul 22 14:52:35     output1, output2 = model(input)
Jul 22 14:52:35   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __call__
Jul 22 14:52:35     result = self.forward(*input, **kwargs)
Jul 22 14:52:35   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 444, in forward
Jul 22 14:52:35     output = self.module(*inputs, **kwargs)
Jul 22 14:52:35   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __call__
Jul 22 14:52:35     result = self.forward(*input, **kwargs)
Jul 22 14:52:35   File "test_c10d.py", line 2380, in forward
Jul 22 14:52:35     F.softmax(self.module0(x), dim=1),
Jul 22 14:52:35   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __call__
Jul 22 14:52:35     result = self.forward(*input, **kwargs)
Jul 22 14:52:35   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
Jul 22 14:52:35     input = module(input)
Jul 22 14:52:35   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __call__
Jul 22 14:52:35     result = self.forward(*input, **kwargs)
Jul 22 14:52:35   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
Jul 22 14:52:35     return F.linear(input, self.weight, self.bias)
Jul 22 14:52:35   File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1371, in linear
Jul 22 14:52:35     output = input.matmul(weight.t())
Jul 22 14:52:35 RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'mat2'
```

**Comment by SsnL** [comment]
this has been reverted on master btw. Feel free to reopen when you fix the issue.

**Comment by astooke** [comment]
Hi, I'm just facing this issue again (was running for a while on a modded pytorch and forgot about it, until now with fresh install).  The problem I have is that when an input argument to a model is a custom data structure which looks like of like a tuple but behaves differently, it gets handled incorrectly in the scatter functionality.

It's still not clear to me why the scatter is needed when there is only one device per process, and this is a preferred way to run multi-GPU.  I tried to dig into the scatter functionality but got lost after a few steps, seems there is a lot of data-to-device management happening in there, which maybe these tests are relying on, but perhaps they shouldn't be?

I just would like to have a separate python process run each GPU, let them handle their own data, and have the DistributedDataParallel take care of gradient all-reduce. Clean and simple  :)

Any thoughts?  Maybe this can be made an option, to bypass the scatter in this case?

**Comment by astooke** [comment]
Replacing this PR with #28256

**Pull request closed without merging**
