### PR TITLE
[reland] Add OpInfo for `bitwise_not`

### PR DESCRIPTION
**Pull request by kshitij12345**
Reference: #42515

Note: Reland #51944

### CODE REVIEW

**Review by mruberry — APPROVED** [review]
Thanks @kshitij12345! All the PR failures are from the base, unfortunately. (It was a rough day for the CI.)

**Comment by jeffdaily** [comment]
Turns out ROCm CI PR failures are real.  Any chance we can revert this again?  And then work with our ROCm engineers to help re-re-land with a proper fix on ROCm?

**Comment by jeffdaily** [comment]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.0.1-py3.6-test1/3628//console

**Comment by mruberry** [comment]
Reverting now. We should separate the bitwise_not opinfo from the changes to which ROCm tests are run going forward.

**Comment by jeffdaily** [comment]
> Reverting now. We should separate the bitwise_not opinfo from the changes to which ROCm tests are run going forward.

Absolutely.  We have an engineer already working on similar ROCm-related changes in these same files, so it would make sense to let us finish that work since we can test it more rapidly without harming CI status.

**Comment by mruberry** [comment]
> > Reverting now. We should separate the bitwise_not opinfo from the changes to which ROCm tests are run going forward.
> 
> Absolutely. We have an engineer already working on similar ROCm-related changes in these same files, so it would make sense to let us finish that work since we can test it more rapidly without harming CI status.

Sounds great; thanks for the heads-up, @jeffdaily!

**Comment by kshitij12345** [comment]
@mruberry Gentle Ping :)

**Pull request closed without merging**
