### PR TITLE
Restore TBB module

### PR DESCRIPTION
**Pull request by ilia-cher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#20454 Restore TBB module**
* #20157 Support for Eigen thread pool
* #20087 Native ATen/Parallel backend
* #20057 Split ATen/Parallel into interface and backend
* #20050 Move inter-op settings into ATen/Parallel

Summary:
This partially reverts https://github.com/pytorch/pytorch/pull/8255 and adds ability to build with MKL and MKL-DNN using TBB

Test Plan:
MKL_TBB=1 MKLDNN_THREADING=TBB USE_TBB=1 USE_OPENMP=0  
USE_EIGEN_THREADPOOL=1 PARALLEL_BACKEND=NATIVE BLAS=MKL
USE_CUDA=0 BUILD_BINARY=1
USE_MKLDNN=1 USE_OPENCV=1 USE_FFMPEG=1 python setup.py develop --cmake

./build/bin/parallel_info

Differential Revision: [D15326062](https://our.internmc.facebook.com/intern/diff/D15326062)

### CODE REVIEW

**Comment by ilia-cher** [comment]
Testing: first, building with
USE_OPENMP=0 - disable OpenMP
USE_TBB=1 - compile TBB
MKL_TBB=1 BLAS=MKL - use MKL and use TBB with MKL
USE_MKLDNN=1 MKLDNN_THREADING=TBB - use MKL-DNN and use TBB with MKL-DNN
PARALLEL_BACKEND=NATIVE - use native thread pool for explicit parallelization in ops instead of OMP
(I'll send next PR to use TBB for explicit parallelization in ops)
USE_EIGEN_THREADPOOL=1 - use Eigen thread pool instead of a native one
BUILD_BINARY=1 USE_CUDA=0
python setup.py develop --cmake

then running ./build/bin/parallel_info and getting (shows the libraries used):

```
ATen/Parallel:
        at::get_num_threads() : 49
OpenMP not found
Intel(R) Math Kernel Library Version 2019.0.3 Product Build 20190125 for Intel(R) 64 architecture applications
        mkl_get_max_threads() : 24
Intel(R) MKL-DNN v0.18.1 (Git Hash 7de7e5d02bf687f971e7668963649728356e0c20)
std::thread::hardware_concurrency() : 48
Environment variables:
        OMP_NUM_THREADS : [not set]
        MKL_NUM_THREADS : [not set]

Loaded .so:
lsof -p 1116739 | grep .so
parallel_ 1116739 iliacher  mem    REG    9,0   304568  6536755300 /data/users/iliacher/pytorch/torch/lib/libc10.so
parallel_ 1116739 iliacher  mem    REG   0,27                49926 /usr/lib64/libm-2.17.so (path dev=0,28)
parallel_ 1116739 iliacher  mem    REG    9,0 70211598  2202916470 /data/users/iliacher/anaconda3/envs/pytorch2/lib/libmkl_core.so
parallel_ 1116739 iliacher  mem    REG    9,0 27588476  2202665212 /data/users/iliacher/anaconda3/envs/pytorch2/lib/libmkl_tbb_thread.so
parallel_ 1116739 iliacher  mem    REG    9,0 11161292  2186068014 /data/users/iliacher/anaconda3/envs/pytorch2/lib/libmkl_intel_lp64.so
parallel_ 1116739 iliacher  mem    REG    9,0   342008  6536048699 /data/users/iliacher/pytorch/torch/lib/libtbb.so
parallel_ 1116739 iliacher  mem    REG   0,27                49853 /usr/lib64/libdl-2.17.so (path dev=0,28)
parallel_ 1116739 iliacher  mem    REG   0,27                49998 /usr/lib64/librt-2.17.so (path dev=0,28)
parallel_ 1116739 iliacher  mem    REG   0,27                49838 /usr/lib64/libc-2.17.so (path dev=0,28)
parallel_ 1116739 iliacher  mem    REG    9,0   143016  6541187085 /data/users/iliacher/pytorch/torch/lib/libcaffe2_observers.so
parallel_ 1116739 iliacher  mem    REG   0,27                49988 /usr/lib64/libpthread-2.17.so (path dev=0,28)
parallel_ 1116739 iliacher  mem    REG    9,0 85558808  6469799982 /data/users/iliacher/pytorch/torch/lib/libcaffe2.so
parallel_ 1116739 iliacher  mem    REG   0,27                49805 /usr/lib64/ld-2.17.so (path dev=0,28)
parallel_ 1116739 iliacher  mem    REG    9,0   819744 14811474984 /data/users/iliacher/anaconda3/envs/pytorch2/lib/libgcc_s.so.1
parallel_ 1116739 iliacher  mem    REG    9,0  9536208  5462695936 /data/users/iliacher/anaconda3/envs/pytorch2/lib/libstdc++.so.6.0.25
```

Note that output omp/mkl_get_max_threads doesn't mean much when TBB is used (number of threads is set through TBB in this case)

cc. @soumith @dzhulgakov @cpuhrsch @VitalyFedyunin @jamesr66a

**Comment by cpuhrsch** [comment]
This is a tricky one. The cmake setup we had was going against the philosophy of TBB, which [doesn't like static libraries](https://stackoverflow.com/questions/638278/how-to-statically-link-to-tbb). I remember maintaining this, but really Intel should maintain this and really we *need* to have a static build for our binary deployments.

**Comment by ilia-cher** [comment]
@cpuhrsch I had to do with tbb the same we do with OpenMP - link it as a shared object (libtbb.so), similar to libgomp.so - it should be used by both PT(+MKL-DNN) and MKL (though libmkl_tbb_thread.so)

**Comment by cpuhrsch** [comment]
@ilia-cher - I thought our binary builds don't use shared libraries.

**Review by cpuhrsch — APPROVED** [review]

**Comment by ilia-cher** [comment]
cc. @kostmo re cmake changes

**Pull request closed without merging**
