### PR TITLE
[ONNX] Remove beartype usage

### PR DESCRIPTION
**Pull request by justinchuby**
beartype has served us well in identifying type errors and ensuring we call internal functions with the correct arguments (thanks!). However, the value of having beartype is diminished because of the following:

1. When beartype improves support for better Dict[] type checking, it discovered typing mistakes in some functions that were previously uncaught. This caused the exporter to fail with newer versions beartype when it used to succeed. Since we cannot fix PyTorch and release a new version just because of this, it creates confusion for users that have beartype in their environment from using torch.onnx
2. beartype adds an additional call line in the traceback, which makes the already thick dynamo stack even larger, affecting readability when users diagnose errors with the traceback.
3. Since the typing annotations need to be evaluated, we cannot use new syntaxes like `|` because we need to maintain compatibility with Python 3.8. We don't want to wait for PyTorch take py310 as the lowest supported Python before using the new typing syntaxes.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #130657
* __->__ #130484

### CODE REVIEW

**Review by titaiwangms — APPROVED** [review]

**Comment by justinchuby** [comment]
@huydhn the PR doesn't touch inductor related code. Do you have an idea why it fails those tests?

**Comment by justinchuby** [comment]
@clee2000 thats puzzling though - those are sympy errors. I suspect https://github.com/pytorch/pytorch/pull/130836 is related?

**Comment by justinchuby** [comment]
Dependent on https://github.com/pytorch/pytorch/pull/130895

**Pull request closed without merging**
