### PR TITLE
[MPS] Do not pass linker command to a compiler

### PR DESCRIPTION
**Pull request by malfet**
`-weak_framework` is a linker rather than a compiler option and as such
it should not be passed as CXX flag
Also, use `string(APPEND` rather than `set(FOO "$(FOO) ...)`

Likely fixes our ability to use `sccache` for MacOS CI builds, see https://github.com/pytorch/pytorch/issues/78375#issuecomment-1143697183

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
SGTM
Let's see build time!

**Comment by albanD** [comment]
By the way, should we let this one compile and then trigger again to make sure we have the right cache?

**Comment by malfet** [comment]
Ok, so the first build took expected 2 hours: https://github.com/pytorch/pytorch/runs/6694666280?check_suite_focus=true

**Review by albanD — APPROVED** [review]
Perfect!

**Pull request closed without merging**
