### PR TITLE
Remove TMP_LIBKINETO_NANOSECOND flag from Compilation

### PR DESCRIPTION
**Pull request by sraikund16**
Summary: Now that we have reached nanosecond granularity, we can now remove the temporary guards that were previously required for nanosecond precision.

Test Plan: Regression should cover this change

Reviewed By: aaronenyeshi

Differential Revision: D56444570

### CODE REVIEW

**Review by aaronenyeshi — APPROVED** [review]

**Comment by aaronenyeshi** [comment]
May need to wait for this PR first: https://github.com/pytorch/pytorch/pull/124737

**Comment by zejun-chen** [comment]
Hi, @sraikund16 

Here means the kineto can directly return ns unit timestamp without a build flag?

Thank you.

**Comment by sraikund16** [comment]
@zejun-chen yes, if you look at the json outputted by kineto, you will see that the timestamps + duration will be in microseconds with 3 digits after the decimal precision, which is nanosecond level granularity

**Pull request closed without merging**
