### PR TITLE
Add decomposition for t_copy

### PR DESCRIPTION
**Pull request by rec**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #130939

* Extracted from #128416

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by peterbell10 — APPROVED** [review]

**Review by peterbell10 — APPROVED** [review]

**Comment by rec** [comment]
topic: not user facing

**Comment by rec** [comment]
pytorchbot merge

**Pull request closed without merging**
