### PR TITLE
Update Triton pin

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #117873

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by shunting314** [comment]
Just FYI, my previous dry run right before Chrismas found some compilation time regression due to an frontend refactoring PR from OpenAI. Perf wise looks good. Not sure if the regress has been fixed or not. https://github.com/pytorch/pytorch/pull/115881

**Comment by alexbaden** [comment]
Triton has made some API changes recently which necessitate some rework in inductor. I have made some of the changes here and am able to run the benchmark scripts against Triton/CUDA: https://github.com/alexbaden/pytorch/tree/alex/triton_updates

Let me know if that code is useful to this effort - I would be happy to PR it or have you just lift it. The changes are quite small so far. I do not think they are backwards compatible, though.

**Comment by desertfire** [comment]
> Triton has made some API changes recently which necessitate some rework in inductor. I have made some of the changes here and am able to run the benchmark scripts against Triton/CUDA: [alexbaden/pytorch@`alex`/triton_updates](https://github.com/alexbaden/pytorch/tree/alex/triton_updates?rgh-link-date=2024-01-20T15%3A29%3A39Z)
> 
> Let me know if that code is useful to this effort - I would be happy to PR it or have you just lift it. The changes are quite small so far. I do not think they are backwards compatible, though.

Thanks for the pointer! It helped me to adapt the changes in a backward-compatible way.

**Comment by desertfire** [comment]
The remaining CI failures should be fixed by https://github.com/openai/triton/pull/2984

**Comment by desertfire** [comment]
Perf and compilation time look ok, https://hud.pytorch.org/benchmark/compilers?startTime=Mon%2C%2015%20Jan%202024%2014%3A17%3A40%20GMT&stopTime=Mon%2C%2022%20Jan%202024%2014%3A17%3A40%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=gh/desertfire/309/head&lCommit=c0e4227b028874218af8b5f45970407ab0088f36&rBranch=main&rCommit=8f7caaee67b1799ac84a99ac508aea630b28f124

**Comment by desertfire** [comment]
@huydhn , @malfet , do you know why `python setup.py bdist_wheel` fails on CI? It works me locally.

**Comment by malfet** [comment]
@desertfire because trunk Trition is still 2.1, we should really ask OpenAI to update version.py first. I wanted to do it for a while, let me propose the change now

**Comment by desertfire** [comment]
> .ci/docker/triton_version.py

Do you mean `.ci/docker/triton_version.txt`? I have already updated it.

**Review by shunting314 — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
> @huydhn , @malfet , do you know why `python setup.py bdist_wheel` fails on CI? It works me locally.

Hmm, mind posting a link? And what commit are you testing against? As `bdist_wheel` fails for me (but `develop` works), unless I remove https://github.com/openai/triton/pull/2982

**Comment by desertfire** [comment]
> > @huydhn , @malfet , do you know why `python setup.py bdist_wheel` fails on CI? It works me locally.
> 
> Hmm, mind posting a link? And what commit are you testing against? As `bdist_wheel` fails for me (but `develop` works), unless I remove [openai/triton#2982](https://github.com/openai/triton/pull/2982)

Should be fixed after https://github.com/openai/triton/pull/2992

**Pull request closed without merging**
