### PR TITLE
Fix test_out when run on CPU with CUDA available

### PR DESCRIPTION
**Pull request by jakeharmon8**
Ever since #135140, this test will fail if run with CPU parameterization (e.g. test_out__refs_logical_or_cpu_float32) and CUDA available - as far as I can tell, the PyTorch CI isn't currently checking for this.

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by jakeharmon8** [comment]
This fixes #140635

**Review by ezyang — APPROVED** [review]

**Comment by eqy** [comment]
Looks like a fresh rebase is needed...

**Pull request closed without merging**
