### PR TITLE
Step 2: Rename _unique_dim2_temporary_will_remove_soon to unique_dim

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #18661 Step 7: remove _unique
* #18655 Step 6: Rename _unique2 to unique and add int? dim
* #18654 Step 5: remove _unique_dim in favor of unique_dim
* #18651 Step 4: add support for unique with dim=None
* #18650 Step 3: Add support for return_counts to torch.unique for dim not None
* **#18649 Step 2: Rename _unique_dim2_temporary_will_remove_soon to unique_dim**

See step 1 for the description of the full stack

Differential Revision: [D14888292](https://our.internmc.facebook.com/intern/diff/D14888292)

### CODE REVIEW

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
It is ready to review / merge ?

**Comment by VitalyFedyunin** [comment]
also please rebase

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin Yes, it is ready. I rebased yesterday, do I need to rebase again?

**Comment by VitalyFedyunin** [comment]
Yes, please (btw I don't see merge/rebase in the history).

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin This is ready, and rebased. The rebase commit should be `b161ff5`, which is automatically generated by `ghstack`. So you couldn't see messages like `merge with master`.

**Comment by VitalyFedyunin** [comment]
Checking

**Comment by VitalyFedyunin** [comment]
It helped, I was able to import this PR and start internal tests. If all goes well I will land it this morning.

**Comment by VitalyFedyunin** [comment]
🤦‍♂️ you need to merge again, there are some changes landed in caffe2/aten/src/ATen/native/native_functions.yaml this morning.

**Comment by VitalyFedyunin** [comment]
Good news - all internal tests are passing, so I will land as soon as merge conflict resolved.

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin Resolved. Should be working now.

**Pull request closed without merging**
