### PR TITLE
Specify overload name in function schema

### PR DESCRIPTION
**Pull request by smessmer**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #18036 Expose c10 cuda ops to caffe2&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D14467495/)
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#18037 Specify overload name in function schema**&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D14467497/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #18038 [wip] Allow registering same operator schema multiple times&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D14467494/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #18090 Move schema inference to c10&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D14491454/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #18051 [wip] Revamp c10 kernel registration&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D14475195/)

The FunctionSchema can now store an overload name and the parser knows how to parse it. Specify like this:

    my_func.overload1(arg1: Tensor) -> Tensor
    my_func.overload2(arg1: Tensor, arg2: Tensor) -> Tensor

Differential Revision: [D14467497](https://our.internmc.facebook.com/intern/diff/D14467497/)

### CODE REVIEW

**Comment by smessmer** [comment]
this is a re-export of https://github.com/pytorch/pytorch/pull/17779

**Comment by suo** [comment]
Could I get some context on this? Not sure this is a great change to the function schema API. If you need a secondary name to disambiguate two functions with exactly the same arguments…aren't they just different functions at that point?

**Comment by apaszke** [comment]
I honestly still don't get why do we need this. How is an error at registration time much better than an error when you call an op? Both of those are _at runtime_, so there's really no significant difference, while we start to pile up more and more complicated logic on top of the usual and well known function overloading semantics...

**Comment by apaszke** [comment]
And if we really think this is a good idea going forward, can we at least make it an optional argument? This PR puts an empty string in almost every constructor we have today.

**Pull request closed without merging**
