### PR TITLE
Error out if legacy Tensor.new is called on alternate layouts / dtypes

### PR DESCRIPTION
**Pull request by gchanan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #31490 Ensure legacy sparse constructor/new doesn't interpret python data as tensor data.
* **#31485 Error out if legacy Tensor.new is called on alternate layouts / dtypes**

Fixes: https://github.com/pytorch/pytorch/issues/22158

Differential Revision: [D19196499](https://our.internmc.facebook.com/intern/diff/D19196499)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 59a1195:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=59a1195e93343f65e25daf56d214bd4483bacbd7).

### :detective: 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4019673) pytorch_xla_linux_xenial_py3_6_clang7_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=77662957) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=77662957))
<details>
<summary>
<code>Dec 19 19:16:11 caused by: Connection refused (os error 111)</code>
</summary>

```
Dec 19 19:16:11 +++ eval 'extract_trap_cmd ' 
Dec 19 19:16:11 ++++ extract_trap_cmd 
Dec 19 19:16:11 ++++ printf '%s\n' '' 
Dec 19 19:16:11 +++ printf '%s\n' cleanup 
Dec 19 19:16:11 ++ trap -- ' 
Dec 19 19:16:11 cleanup' EXIT 
Dec 19 19:16:11 ++ which sccache 
Dec 19 19:16:11 ++ sccache --stop-server 
Dec 19 19:16:11 Stopping sccache server... 
Dec 19 19:16:11 error: couldn't connect to server 
Dec 19 19:16:11 caused by: Connection refused (os error 111) 
Dec 19 19:16:11 ++ true 
Dec 19 19:16:11 ++ rm /var/lib/jenkins/sccache_error.log 
Dec 19 19:16:11 ++ SCCACHE_ERROR_LOG=/var/lib/jenkins/sccache_error.log 
Dec 19 19:16:11 ++ SCCACHE_IDLE_TIMEOUT=1200 
Dec 19 19:16:11 ++ RUST_LOG=sccache::server=error 
Dec 19 19:16:11 ++ sccache --start-server 
Dec 19 19:16:11 Starting sccache server... 
Dec 19 19:16:11 ++ sccache --zero-stats 
Dec 19 19:16:11 Compile requests                 0 
Dec 19 19:16:11 Compile requests executed        0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by albanD — APPROVED** [review]
LGTM

**Comment by gchanan** [comment]
@dlibenzi it looks like this causes XLA to fail.  I think I just need to put XLA tensors in the "allowed list".  I'm assuming XLA doesn't support sparse tensors at this point (at least I don't see a SparseXLATensorTypeId).

**Comment by dlibenzi** [comment]
> @dlibenzi it looks like this causes XLA to fail. I think I just need to put XLA tensors in the "allowed list". I'm assuming XLA doesn't support sparse tensors at this point (at least I don't see a SparseXLATensorTypeId).

The failure in the XLA test seems a system one AFAICT, but no, XLA does not support sparse tensors.

**Comment by dlibenzi** [comment]
If a specific test is failing, we also have the ability to disable it:

https://github.com/pytorch/xla/blob/master/test/torch_test_meta.py

@mruberry knows the details...

**Comment by gchanan** [comment]
Well I think it's failing because this PR causes `xla_tensor.new(0,3,3)` to fail, and I don't see any particular reason why it needs to fail (let me know if I'm wrong and it should).  In the meantime, I'll try to fix.

**Comment by dlibenzi** [comment]
> Well I think it's failing because this PR causes `xla_tensor.new(0,3,3)` to fail, and I don't see any particular reason why it needs to fail (let me know if I'm wrong and it should). In the meantime, I'll try to fix.

Oh, I see it now:
```
Dec 20 17:11:17 Traceback (most recent call last):
Dec 20 17:11:17   File "/var/lib/jenkins/workspace/test/common_device_type.py", line 181, in instantiated_test
Dec 20 17:11:17     return test(self, device_arg)
Dec 20 17:11:17   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 8037, in test_index
Dec 20 17:11:17     self.assertEqual(reference[torch.LongTensor().to(device)], reference.new(0, 3, 3))
Dec 20 17:11:17 RuntimeError: new(): expected TensorTypeId: CPUTensorId or CUDATensorId or HIPTensorId but got: XLATensorId
```

Seems like you can add XLATensor to the list, but I don't know the details, and whether adding to such list would imply XLATensor supporting sparse tensors.

**Comment by gchanan** [comment]
Ah sorry I wasn't clear, there are two cases: when `new` is called on a dense tensor, and when `new` is called on a sparse tensor.  I'll put XLATensor in the allowed list only for the dense case.

**Pull request closed without merging**
