### PR TITLE
[Break XPU][Inductor] Handle device property `warp_size` is None but used on XPU.

### LINKED ISSUE #136820: [Break XPU] device_props.warp_size is None on XPU.
### 🐛 Describe the bug

Currently ciflow/xpu is broken caused by the merged PR
Error message:
https://github.com/pytorch/pytorch/actions/runs/11053034285/job/30715286308

The root cause is the PR #136472 generalize the `num_elements_per_warp=32` to `num_elements_per_warp=device_props.warp_size`, but `warp_size` device propertie of XPU is `None`:
```
DeviceProperties(type='xpu', index=0, cc={'driver_version': '1.3.30252', 'gpu_eu_count': 512, 'gpu_subslice_count': 64, 'has_atomic64': True, 'has_bfloat16_conversions': True, 'has_fp16': True, 'has_fp64': True, 'has_subgroup_2d_block_io': True, 'has_subgroup_matrix_multiply_accumulate': True, 'has_subgroup_matrix_multiply_accumulate_tensor_float32': False, 'max_compute_units': 512, 'max_num_sub_groups': 64, 'max_work_group_size': 1024, 'name': 'Intel(R) Data Center GPU Max 1550', 'platform_name': 'Intel(R) Level-Zero', 'sub_group_sizes': [16, 32], 'total_memory': 68719476736, 'type': 'gpu', 'vendor': 'Intel(R) Corporation', 'version': '1.5'}, major=None, regs_per_multiprocessor=None, max_threads_per_multi_processor=None, multi_processor_count=None, warp_size=None)
```
 

### Versions

PyTorch version: 2.5.0a0+git7da755b
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.4
Libc version: glibc-2.35

cc @gujinghui @EikanWang @fengyuan14 @guangyey

### PR DESCRIPTION
**Pull request by etaf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #136742
* #135320
* #135318
* __->__ #136834

Fix #136820

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by EikanWang — APPROVED** [review]
LGTM

**Review by desertfire — COMMENTED** [review]
This works, but shouldn't you set `device_props.warp_size` for XPU somewhere?

**Comment by etaf** [comment]
> This works, but shouldn't you set `device_props.warp_size` for XPU somewhere?

Hi @desertfire  resolved, please have a review.

**Review by jansel — APPROVED** [review]

**Review by EikanWang — APPROVED** [review]

**Comment by int3** [comment]
Ah sweet, this solves the issue for the Triton CPU backend too (we also set `warp_size` to `None`). Thanks!

**Pull request closed without merging**
