### PR TITLE
[quant][refactor] Factor out MHA code dup from nn and nn.quantizable

### PR DESCRIPTION
**Pull request by z-a-f**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#51169 [quant][refactor] Factor out MHA code dup from nn and nn.quantizable**
* #50459 [quant] Factoring out the list of no_observers
* #49866 [quant] Quantizable MultiheadAttention

Quantizable MHA shares some code with its FP equivalent.
This factors out common parts.

Test Plan:

Explicit testing is not available, as there is no functional tests for the nn.MHA.
However, the functional equivalence of this PR was tested across commits by comparing the numerics of the pre-change and post-change MHA. Similar was done for the quantizable counterpart.

Differential Revision: [D26092530](https://our.internmc.facebook.com/intern/diff/D26092530)

### CODE REVIEW

**Comment by vkuzo** [comment]
thanks for doing this, high level LGTM if the numerics did not change and it's just copy-pasta.  Do we need the fp32 MHA folks to approve?

**Comment by z-a-f** [comment]
> thanks for doing this, high level LGTM if the numerics did not change and it's just copy-pasta. Do we need the fp32 MHA folks to approve?

The more I think about this PR, the more I think this is a bad idea :) We can discuss it offline

**Comment by z-a-f** [comment]
The main con of this refactor is that once we implement the quantized BMM and Softmax, we will have to refactor again.

**Comment by vkuzo** [comment]
what are good next steps here?  Are we planning to land this PR, or do something else?

**Pull request closed without merging**
