### PR TITLE
Upgrade protobuf as bazel build preamble

### PR DESCRIPTION
**Pull request by werkt**
The protobuf bazel definitions are incompatible with recent bazel
versions, so as a prerequisite for any bazel build of pytorch, a more
recent protobuf must be used.

### CODE REVIEW

**Review by ezyang — CHANGES_REQUESTED** [review]
not sure what this pr is doing

**Comment by werkt** [comment]
> not sure what this pr is doing

Went through a baseline comparison for the CI. I cannot replicate the failures that happen with the protobuf upgrade locally. It is now back to it's intended change, sans whatever fixes are required for CI

**Comment by seemethere** [comment]
@ezyang This PR is bumping `protobuf` to a version that is required for bazel to run properly

**Comment by ezyang** [comment]
I don't think you are going to want to change the link local default; for regular binary builds that most of our users use, we really do want it to be link local.

**Comment by ezyang** [comment]
IS this ready?

**Comment by werkt** [comment]
Except for this very strange windows error, which thinks that this code:

```
enum EnumType : int {
  EnumType_ENUMERATION = 1,
};
class Foo {
  static constexpr EnumType ENUMERATION = EnumType_ENUMERATION;
};
```
Is an error, for 'maybe' not initializing `ENUMERATION`?

I don't have a windows machine to test this on...

**Comment by malfet** [comment]
@peterjc123 any idea what might be wrong with the windows build here?

**Comment by ezyang** [comment]
RIP. Sounds like we triggered an MSVC bug. What is the old code that is codegenned here?

**Comment by malfet** [comment]
> Except for this very strange windows error, which thinks that this code:
> 
> ```
> enum EnumType : int {
>   EnumType_ENUMERATION = 1,
> };
> class Foo {
>   static constexpr EnumType ENUMERATION = EnumType_ENUMERATION;
> };
> ```
I guess this pattern has escaped https://github.com/pytorch/pytorch/blob/master/cmake/ProtoBufPatch.cmake#L35

**Review by ezyang — APPROVED** [review]

**Comment by werkt** [comment]
CI is clear here, can someone merge?

**Pull request closed without merging**
