### PR TITLE
Rename torch::autograd::Function to torch::autograd::Node

### PR DESCRIPTION
**Pull request by malvika2147**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#23269 Rename torch::autograd::Function to torch::autograd::Node**

Summary:
We will be adding an API for custom autograd functions in C++ (https://github.com/pytorch/pytorch/pull/23020) and we would like to expose it as `torch::autograd::Function` (which is different from the current `torch::autograd::Function`) to match the Python API. So, I plan to rename the current `torch::autograd::Function` to `torch::autograd::Node` and `torch::autograd::PyFunction` to `torch::autograd::PyNode`.  `FunctionTask`, and `deleteFunction` renamed to `NodeTask`, `deleteNode` for consistency.

Differential Revision: [D16454878](https://our.internmc.facebook.com/intern/diff/D16454878)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by pietern** [comment]
@ezyang FYI the PR summary didn't end up in the commit. Perhaps some race. But the summary here is very valuable for anyone casually reading the code and figuring out what motivated this change.

**Comment by ezyang** [comment]
I let the open source team know about that; I see that the diff has the correct description and so ShipIt ought to have preserved it.

**Comment by gqchen** [comment]
Is there any reason we didn't rename "function.h" and "function.cpp" to "node.h" and "node.cpp"?  It will certainly make folks reading the code in the future a bit easier.

**Comment by ezyang** [comment]
Laziness, probably :)

**Pull request closed without merging**
