### PR TITLE
[jit] Supress warnings on generated tests

### PR DESCRIPTION
**Pull request by driazati**
Removes all warnings spew for the TestJitGenerated tests

### CODE REVIEW

**Comment by eellison** [comment]
This won't block warnings that are printed in script mode right ? It might be good to also capture output on the generated tests

**Comment by driazati** [comment]
It catches all of them it looks like

image

**Comment by wanchaol** [comment]
I remember we handled the warning in script as print or aten::warn? If it's aten::warn, I guess we still print out those warnings in script mode, if it's easy change to disable that would be better.

**Review by wanchaol — APPROVED** [review]
lg

**Pull request closed without merging**
