### PR TITLE
Update torch-xpu-ops commit pin

### PR DESCRIPTION
**Pull request by toyxu**
Update the torch-xpu-ops commit to [1e32bbc](https://github.com/intel/torch-xpu-ops/commit/1e32bbc3d9a68112299e02566cf4b174b89c24c9), includes:

- Improve XPU aten operator coverage
- Support basic `SparseXPU` operators

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by dvrogozh** [comment]
This PR is affected by #141268 (xpu build fails). Please, help review a fix in:
* https://github.com/pytorch/pytorch/pull/141269

**Review by EikanWang — APPROVED** [review]

**Comment by xytintel** [comment]
Depend on https://github.com/pytorch/pytorch/issues/141466

**Comment by chuanqi129** [comment]
The only one UT failure appeared in doctests, there is an issue to track it https://github.com/pytorch/pytorch/issues/141705

**Review by EikanWang — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
