### PR TITLE
Fix `generate_not_implemented_tests` not testing unknown types correctly

### PR DESCRIPTION
**Pull request by asi1024**
Currently, the test code is not testing unknown types correctly because `op` is overwritten in the for-loop (i.e., currently only `__ior__` is tested).
This PR fixes the test `generate_not_implemented_tests` to bind operator name to each method, and remove operators currently unsupported (`__rand__`, …).

cc/ @mruberry This fix is be needed to add tests for the operator we are going to introduce (e.g., `__rand__`)

### CODE REVIEW

**Review by mruberry — COMMENTED** [review]
Hey @asi1024! Thanks for noticing this issue; this is often a tricky Python nuance.

It looks like some of the tests are failing, probably because this test wasn't running for so long and it regressed. Do you the test can be updated? Alternatively, is there something else these failures are telling us? That is, is there something outside this test we should be fixing?

**Comment by mruberry** [comment]
cc @pmeier, who's investigating updates to the binary pwise tests

**Comment by asi1024** [comment]
@mruberry I updated the test to pass in b913ad5!
I also fixed some routines to return `NotImlemented` correctly in 1d209db, but I can split the commit to another PR if preferred.

**Review by mruberry — APPROVED** [review]
Thanks @asi1024! Test failures appear unrelated

**Comment by mruberry** [comment]
With apologies, @asi1024, I believe I spoke too soon about the test failures being unrelated. I suspect the following test failure is related to this change:

```
Apr 27 11:51:54 =================================== FAILURES ===================================
Apr 27 11:51:54 ___________________________ TestOperators.test_rsub ____________________________
Apr 27 11:51:54 Traceback (most recent call last):
Apr 27 11:51:54   File "/var/lib/jenkins/workspace/test/onnx/test_operators.py", line 168, in test_rsub
Apr 27 11:51:54     self.assertONNX(lambda x: 1 - x, (x,))
Apr 27 11:51:54   File "/var/lib/jenkins/workspace/test/onnx/test_operators.py", line 65, in assertONNX
Apr 27 11:51:54     self.assertExpected(onnx_model_pbtxt, subname)
Apr 27 11:51:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1553, in assertExpected
Apr 27 11:51:54     self.assertMultiLineEqual(expected, s)
Apr 27 11:51:54   File "/opt/conda/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
Apr 27 11:51:54     self.fail(self._formatMessage(msg, standardMsg))
Apr 27 11:51:54   File "/opt/conda/lib/python3.6/unittest/case.py", line 670, in fail
Apr 27 11:51:54     raise self.failureException(msg)
Apr 27 11:51:54 AssertionError: 'ir_v[351 chars]ut: "x"\n    output: "2"\n    name: "Sub_1"\n [571 chars]n}\n' != 'ir_v[351 chars]ut: "0"\n    output: "2"\n    name: "Sub_1"\n [571 chars]n}\n'
Apr 27 11:51:54 Diff is 1126 characters long. Set self.maxDiff to None to see it.
Apr 27 11:51:54 =============================== warnings summary ===============================
```

These tests work by generating text files and comparing the new text file to an old "expect" file. So when one of these tests breaks it doesn't mean something is wrong, necessarily, simple that something has changed. 

For simplicity, however, would you revert the changes to _tensor.py and python_variable_methods.cpp, then skip testing the ops which will cause the test to fail? Then this PR will fix the issue it was originally trying to solve. Additionally, however, would you please file an issue for the other changes this PR was making so we don't forget about them?

**Comment by asi1024** [comment]
@mruberry I reverted the commit and will open an issue for this change!

**Pull request closed without merging**
