### PR TITLE
SumKernel (BFloat16): use float as accumulation type

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #61015 add BFloat16 support for BatchNorm2d on CPU
* #58297 add BFloat16 support for UpSample on CPU
* #56904 optimize transpose copy for float32 and bfloat16 on CPU
* #56903 add BFloat16 support for MaxPool2d on CPU
* #56902 add BFloat16 support for AdaptiveAvgPool2d on CPU
* #56372 add BFloat16 support for bernoulli and Dropout on CPU
* #55588 add bf16 support for bucketize
* #55221 optimize BFloat16 elemwise operators CPU: sigmoid, sigmoid_backward, tanh_backward, addcmul, addcdiv
* **#55217 SumKernel (BFloat16): use float as accumulation type**

Differential Revision: [D28836794](https://our.internmc.facebook.com/intern/diff/D28836794)

### CODE REVIEW

**Comment by mingfeima** [comment]
use float as accumulation type when input is of BFloat16.

Since this PR is not related to parallelization feature, only single core perf is tested:
- performance update on **avx512** machine: Xeon(R) Gold 6248 CPU @ 2.50GHz
```bash
### before
sum size: 100000, fp32: 0.005 ms; bf16: 0.023 ms
sum size: 1000000, fp32: 0.153 ms; bf16: 0.217 ms
sum size: 10000000, fp32: 2.272 ms; bf16: 2.130 ms

### after
sum size: 100000, fp32: 0.006 ms; bf16: 0.007 ms
sum size: 1000000, fp32: 0.153 ms; bf16: 0.084 ms
sum size: 10000000, fp32: 2.365 ms; bf16: 0.840 ms
```
- performance update on **avx2** machine: Xeon(R) CPU E5-2680 v3 @ 2.50GHz
```bash
### before
sum size: 100000, fp32: 0.025 ms; bf16: 0.042 ms
sum size: 1000000, fp32: 0.149 ms; bf16: 0.343 ms
sum size: 10000000, fp32: 3.494 ms; bf16: 3.293 ms

### after
sum size: 100000, fp32: 0.024 ms; bf16: 0.016 ms
sum size: 1000000, fp32: 0.135 ms; bf16: 0.093 ms
sum size: 10000000, fp32: 3.229 ms; bf16: 1.078 ms
```

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836794).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836794).

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836794).

**Review by peterbell10 — CHANGES_REQUESTED** [review]
Just noticed this PR, but as of #60387 BFloat16 is accumulated in floats.

**Comment by VitalyFedyunin** [comment]
@mingfeima  can you please take a look if we should revert as per @peterbell10 comment

**Comment by peterbell10** [comment]
Oh well, too late I guess. It's probably easier for me to revert it myself as I'm working on other sum PRs that might conflict.

**Comment by mingfeima** [comment]
> Oh well, too late I guess. It's probably easier for me to revert it myself as I'm working on other sum PRs that might conflict.

@peterbell10 @VitalyFedyunin feel free to revert this one. #60387 is enough to do the job :)

**Comment by VitalyFedyunin** [comment]
Reverted. Please rebase (and update) rest of the stack.

**Pull request closed without merging**
