### PR TITLE
Fix ONNX LogSoftmax export.

### PR DESCRIPTION
**Pull request by kit1980**
This fixes an issue with incorrect `axis=-1` in the exported ONNX.

### CODE REVIEW

**Comment by kit1980** [comment]
Now one test is failing on exporting LogSoftmax model, but without this change it exports to a wrong ONNX model.

**Comment by houseroad** [comment]
https://github.com/pytorch/pytorch/pull/9660 will fix the wrong test cases.

**Review by houseroad — COMMENTED** [review]
This looks good. Let's wait for https://github.com/pytorch/pytorch/pull/9660 to fix the wrong test case.

**Comment by kit1980** [comment]
#9660 is in now, how can we proceed with this PR?

**Comment by houseroad** [comment]
@kit1980 can you rebase the code to the master?

**Comment by kit1980** [comment]
@houseroad rebased on master.

**Pull request closed without merging**
