### PR TITLE
Strided masked reduction: mean.

### PR DESCRIPTION
**Pull request by pearu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #67039
* __->__ #66784

cc @nikitaved @pearu @cpuhrsch @IvanYashchuk

Differential Revision: [D31838513](https://our.internmc.facebook.com/intern/diff/D31838513)

### CODE REVIEW

**Comment by pearu** [comment]
OK, I'll refactor this PR into two.

**Comment by cpuhrsch** [comment]
@cpuhrsch has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31838513).

**Review by cpuhrsch — APPROVED** [review]

**Comment by cpuhrsch** [comment]
I don't know why the bot decided to comment just now, but the code has landed so we can ignore it.

**Comment by pearu** [comment]
yes, I was always wondering about it but then noticed that revert-hash was the same as on Oct 23 and the code is still present in master..

**Pull request closed without merging**
