### PR TITLE
[ROCm] enable unit tests

### PR DESCRIPTION
**Pull request by iotamudelta**
These unit tests pass after landing all the warp size awareness patches.

### CODE REVIEW

**Comment by bddppq** [comment]
Lint failure is real:
```
./test/test_optim.py:17:1: F401 'common_utils.skipIfRocm' imported but unused
```
But it's good news that it means there is no more rocm skipped test in that file :-)

**Comment by iotamudelta** [comment]
@bddppq just fixed - indeed `test_optim` doesn't require importing `skipIfRocm` any longer. :-)

**Review by bddppq — APPROVED** [review]
nice

**Pull request closed without merging**
