### PR TITLE
work around building onnx in older rocm docker images

### PR DESCRIPTION
**Pull request by jeffdaily**
CC @ezyang @xw285cornell @sunway513 @malfet

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by jeffdaily** [comment]
Still fails.  Updating pip over system pip causing incompatibilities.   See https://github.com/pypa/pip/issues/5599 for details.

**Comment by jeffdaily** [comment]
@malfet FYI not sure if you've followed the progress today.  Nothing has worked thus far, so I'm attempted now to install conda in the same way as the circleci images do, but only for the caffe2 build.  Requested a new review since this is different than what we originally discussed.

**Review by malfet — APPROVED** [review]

**Comment by jeffdaily** [comment]
Build failed again, because conda install didn't fire due to missing version env var.  New commit to export env var prior to calling conda install.

**Comment by jeffdaily** [comment]
Build failed again, because install_conda.sh creates /opt/conda and by the time build.sh runs we are no longer root user and don't have persmission.  Instead of modifying install_conda.sh to be flexible both in terms of user and install directory, I changed .jenkins/caffe2/common.sh to install conda using similar steps.

**Comment by jeffdaily** [comment]
@malfet  ROCm caffe2 build passed this time.  This work-around leaves a bad taste in my mouth, but it seems better than the alternative of disabling ROCm CI for caffe2 build, test, and bench.

**Comment by jeffdaily** [comment]
Need to wait for ROCm caffe2 test to finish to be absolutely sure of the work-around.

**Review by malfet — APPROVED** [review]

**Comment by jeffdaily** [comment]
Current build failure is not a build environment or a missing python package.
```
23:53:46 E       RuntimeError: [enforce fail at operator.cc:274] op. Cannot create operator of type 'Histogram' on the device 'HIP'. Verify that implementation for the corresponding device exist.
```
Might be time to land this PR and we can look into this test further.

**Comment by jeffdaily** [comment]
Probably related to https://github.com/pytorch/pytorch/commit/0b9d5370562112c2ee0664a5cf58a5a1a3841966 ?

**Comment by xw285cornell** [comment]
Let's unblock the master first, but we should certainly update the docker image and get rid of this workaround..

**Pull request closed without merging**
