### PR TITLE
Revert "Revert D28833086: beef up at::_ops API"

### PR DESCRIPTION
**Pull request by bdhirsh**
Reland of https://github.com/pytorch/pytorch/pull/59115, but with a fix for windows cuda builds (example failure in master here: https://github.com/pytorch/pytorch/runs/2852662871)

This is identical to the original PR except for one change in `tools/codegen/gen.py`: `static constexpr` -> `static CONSTEXPR_CONST_EXCEPT_WIN_CUDA` (had to make a new macro that was a slight adjustment to an existing one)

This actually took a while to figure out, until I tracked down a previous pytorch PR that encountered a similar issue: https://github.com/pytorch/pytorch/pull/40675

This reverts commit 6d0fb85a623f5ef3f3f1a2afc3660cb71fa70511.

Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#60214 Revert "Revert D28833086: beef up at::_ops API"**

Differential Revision: [D29213932](https://our.internmc.facebook.com/intern/diff/D29213932)

### CODE REVIEW

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29213932).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29213932).

**Review by ezyang — APPROVED** [review]

**Comment by bdhirsh** [comment]
update 1: I had to make a slightly new macro to handle `constexpr const` properly: `CONSTEXPR_CONST_EXCEPT_WIN_CUDA`

update 2: looks like in the brief period of time that my original PR landed, some small binary size regressions were detected internally. Gotta figure out where that was coming from before I re-land this. Although inspecting the OSS libtorch_cpu.so showed that we were correctly adding two new symbols for each new op, `at::_ops::add_Tensor::call` and `at::_ops::add_Tensor::redispatch` and removing/inlining the corresponding previous symbols, `at::add` and `at::redispatch::add`. Maybe internal testing will help more.

**Review by bhosmer — APPROVED** [review]

**Comment by bdhirsh** [comment]
Okay, issue (1) is harder to solve than I thought.

**My proposed fix (it's in the PR)**

For everything except Windows NVCC builds we do this:
```
struct add_Tensor {
    static constexpr const char* name = "add";
};
```

And for Windows NVCC builds we do this:
```
struct add_Tensor {
    // const instead of constexpr
    static const char* name;
};
// defined outside of the struct definition
const char* add_Tensor name = "add";
```


**The problem**

I'd like to write code like the following:
```
struct add_Tensor {
    static constexpr const char* name = "add";
};
```

But Windows NVCC apparently has a bug (in VS2017, fixed in VS2019) where it can't deal with `static constexpr`. A workaround issue recommends using `static const` instead (https://developercommunity.visualstudio.com/t/static-constexpr-gives-member-may-not-be-initializ/444344).



The next reasonable alternative to try is this (we actually have some code that does this with an existing CONSTEXPR_EXCEPT_WIN_CUDA macro):
```
struct add_Tensor {
    static const char* name = "add";
};
```

The above fails thanks to the C++ standard (see https://developercommunity.visualstudio.com/t/static-constexpr-gives-member-may-not-be-initializ/444344).

I tried out those two options and a few others in Compiler Explorer - see the examples with descriptions in https://godbolt.org/z/Tn73xdYGz.

It would be great if we can suppress the original Windows NVCC compiler error, but I haven't figured out a way to do that. The alternative that I added at the top works fine, but accesses to `at::_ops::add_Tensor::name` will be a little slower for windows-NVCC, so we just need to make sure it's not used anywhere that's perf critical.

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29213932).

**Comment by ezyang** [comment]
This is fine, string access is guarded behind executed only once static calls anyway

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29213932).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29213932).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29213932).

**Comment by bdhirsh** [comment]
Still waiting for some internal binary size tests to finish running, but after talking to @ezyang I moved some incriminating functions that I'd previously moved from `Functions.cpp` and `TensorMethods.cpp` into `Functions.h` and `TensorBody.h` back into their original files, and so far I haven't seen any failed tests.

There were a few functions that I'd moved into the header files before that I'm keeping in for now, like `Tensor::cpu()` and `Tensor::options()`, because they seem small and useful enough that we might get some perf wins without sacrificing too much in terms of binary size. If more tests fail then I'll try moving those back to cpp files too.

**Pull request closed without merging**
