### PR TITLE
[Test] Windows nightly builds on CircleCI

### LINKED ISSUE #36381: Low cache hit count for conda builds on Windows
## Fact

Even when building for a conda release for a second time, the cache hit count is pretty low. Example result:
```
Compile requests               1978
Compile requests executed      1971
Cache hits                      221
Cache misses                   1739
Cache timeouts                    0
Cache read errors                 0
Forced recaches                   0
Cache write errors                0
Compilation failures              6
Cache errors                      5
Non-cacheable compilations       33
Non-cacheable calls               0
Non-compilation calls             7
Unsupported compiler calls        0
Average cache write           0.224 s
Average cache read miss      25.052 s
Average cache read hit        0.060 s
Cache location             S3, bucket: Bucket(name=ossci-compiler-cache-circleci-v2, base_url=http://ossci-compiler-cache-circleci-v2.s3.amazonaws.com/)
```

## Underlying bug
When calculating hashes, the switch `-E` is used, which contains the full path and the line number of the included headers, which will reduce the cache rate when we happen to make builds in different directories.

## Solution
Use `-EP` instead. Apply https://github.com/mozilla/sccache/pull/723. As for NVCC, `-Xcompiler -EP` should be passed.

cc @yf225

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by peterjc123** [comment]
@seemethere @ezyang The disk space is running out for the jobs with (LibTorch x CUDA x Debug). Is there any way to extend it?

**Comment by ezyang** [comment]
Oof, that's rough. Brief googling on CircleCI suggests there is not a way to extend disk space; maybe we could write into support but they may have a similar story.

Is the problem that the debug symbols are hosing the disk (because they're so big)?

**Comment by peterjc123** [comment]
> Oof, that's rough. Brief googling on CircleCI suggests there is not a way to extend disk space; maybe we could write into support but they may have a similar story.
> 
> Is the problem that the debug symbols are hosing the disk (because they're so big)?

Yes, I think it's the case.

**Comment by ezyang** [comment]
OK, I'll escalate this.

**Comment by peterjc123** [comment]
@ezyang I found a barebone image `windows-server-2019:201908-08` in CircleCI. Sadly, it doesn't work either.

**Comment by peterjc123** [comment]
Current issues that blocks this PR:
1. The jobs with (libtorch cuda debug) configuration cannot complete because it is running out of disk space.
Current state: Remove VS2019 and get 20G more disk space
2. The conda build jobs are much slower after migration. It is weird because the agents on CircleCI have 2x CPU cores.
Current state: Set variables including `SCCACHE_BUCKET`, `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to enable writing the files to S3
3. The upload jobs couldn't be triggered.
Current state: It's a permission issue. Will attempt to merge it first.

**Comment by ezyang** [comment]
> Current state: Fixed. Remove VS2019 and get 20G more disk space. (7GB remaining for that job)

Nice!

> Need to investigate how to pass those env vars into conda envs.

Do it using `script_env` in the conda file https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#inherited-environment-variables

> Current state: Cannot resolve. It's a permission issue. Will attempt to merge it first.

Hmm, we should give you perms. Hang on.

**Comment by ezyang** [comment]
I added you to pytorch-builders, you should have authorization to trigger jobs with access to the s3 bucket secret keys now

**Comment by ezyang** [comment]
lmk when to merge this PR

**Comment by peterjc123** [comment]
> Do it using `script_env` in the conda file https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#inherited-environment-variables

Actually the vars are passed even without those changes. The actual reason of that is described in https://github.com/pytorch/pytorch/issues/36381#issuecomment-612925688.

**Comment by peterjc123** [comment]
> lmk when to merge this PR

Sure. I guess the current downside is that conda builds are slow but I think that's okay.

**Comment by ezyang** [comment]
If the conda builds are slow we should only do them on master, since other people will wait for them to finish

**Comment by peterjc123** [comment]
> If the conda builds are slow we should only do them on master, since other people will wait for them to finish

I didn't think of that. Actually I don't think we should bring those tests to PR/master because it doesn't bring new tests and the matrix is so big. However, I think we may run the libtorch debug binary builds on regular CIs because we don't build and test them currently.

**Comment by peterjc123** [comment]
@ezyang Looks like I uploaded some source files by mistake in https://app.circleci.com/pipelines/github/pytorch/pytorch/154637/workflows/c422a58a-9a9c-4297-b967-817394387ba6/jobs/5134274. Would you please clean them?

**Comment by peterjc123** [comment]
@ezyang @seemethere The python 3.5 builds are failing with `torch requires Python '>=3.6.1' but the running Python is 3.5.6`, which seems a result of https://github.com/pytorch/pytorch/blob/master/setup.py#L874. Should I remove those builds from nightly?

**Comment by orionr** [comment]
Yes - please upgrade to python `3.6.1` or later for all master builds.

**Comment by peterjc123** [comment]
Work continued in https://github.com/pytorch/pytorch/pull/36580.

**Comment by ezyang** [comment]
Yes, remove py3.5 from nightly, 3.5 is dead, long live 3.8!

**Comment by ezyang** [comment]
@peterjc123 I deleted them. It was only cpu folder right?

**Comment by peterjc123** [comment]
> @peterjc123 I deleted them. It was only cpu folder right?

yep

**Pull request closed without merging**
