### PR TITLE
[test_nn] add custom device support for convolution tests、embedding tests、pooling tests and nn tests.

### PR DESCRIPTION
**Pull request by summerdo**
[test_nn] add custom device support for convolution tests、embedding tests、pooling tests and nn tests.

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by summerdo** [comment]
@albanD sorry to bother, could you have a look?

**Comment by ezyang** [comment]
I am a bit iffy on this. There are many people using the private use key and so there will not be a canonical set of tests that people want to use private use on versus not. What will you do about this?

**Comment by summerdo** [comment]
> I am a bit iffy on this. There are many people using the private use key and so there will not be a canonical set of tests that people want to use private use on versus not. What will you do about this?

Add the decorator of dtypesIfPRIVATEUSE1 above the use case, so that the type scenario of PrivateUse1 can be tested

**Comment by summerdo** [comment]
> I am a bit iffy on this. There are many people using the private use key and so there will not be a canonical set of tests that people want to use private use on versus not. What will you do about this?



> But as I said, it doesn't make sense. If you are forced to explicitly decorate tests in PyTorch for if they work with private use, you will only be able to record one configuration

Do you have any good suggestions for this？

**Comment by ezyang** [comment]
I think it's OK to generalize tests to work beyond CUDA. But you should update the skips. Instead, they should be handled out of band by the overall runner you have for your private use type.

**Comment by summerdo** [comment]
> I think it's OK to generalize tests to work beyond CUDA. But you should update the skips. Instead, they should be handled out of band by the overall runner you have for your private use type.

I have deleted the data type specific to PrivateUse1, please check it to see if there is any problem?

**Comment by ezyang** [comment]
@albanD if we add the "get accelerator device" API, maybe we can rewrite `onlyCUDA` to be `onlyAcceleratorDevice` or something like that? (I'm still not happy with this PR)

**Pull request closed without merging**
