### PR TITLE
[CI] Change compile_threads to 1 when running benchmark accuracy test on CI

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96195

Summary: This is not a pretty solution, but it a way to verify if the flakiness is coming from parallel compilation.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

### CODE REVIEW

**Comment by desertfire** [comment]
There is still a flaky `rexnet_100` failure in https://github.com/pytorch/pytorch/actions/runs/4359775582/jobs/7622297472. Sigh...

**Review by ngimel — APPROVED** [review]
That's worrying, we should get to the route of this if it turns out to be the reason.

**Comment by desertfire** [comment]
`dla102` shows an accuracy failure that looks flaky (https://github.com/pytorch/pytorch/actions/runs/4380534417/jobs/7667974987), not a good sign for the purpose of this PR, but I will still land it to see if it can solve the frequent `rexnet_100` failure on CI.

**Pull request closed without merging**
