### PR TITLE
[DO NOT MERGE] Test cuda mem leak check on windows

### PR DESCRIPTION
**Pull request by ssnl**
test #8044

### CODE REVIEW

**Comment by SsnL** [comment]
synchronize doesn't fix it. :/

**Comment by peterjc123** [comment]
This is my guess though. Since `test_nn.py` uses `TEST_CUDA` and `TEST_MULTIGPU`. And these variables are causing CUDA OOM too. Maybe some memory will be allocated using `torch.cuda.is_available()` and since it is not referenced in the spawned processes, it is then released, thus this issue emerges.  But I don't know it is the case. But if it is true, then what about making the evaluations of these variables lazy? What do you think?

**Comment by yf225** [comment]
@SsnL Should we close this PR?

**Pull request closed without merging**
