### PR TITLE
[ROCm] Unskip functorch tests that now work

### PR DESCRIPTION
**Pull request by alugorey**
This issue unskips some of the working tests that were skipped as a result of https://github.com/pytorch/pytorch/issues/96560

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Comment by izaitsevfb** [comment]
> @alugorey your PR has been successfully reverted.

I might've been to hasty. The linter failure looks to be unrelated. Will verify and re-merge, if that's the case. Apologies for the churn.

**Comment by izaitsevfb** [comment]
The actual lint error can be seen here, and it's relevant:
https://github.com/pytorch/pytorch/actions/runs/6592918784/job/17914967387#step:11:1365
```
>>> Lint for test/functorch/test_ops.py:

  Warning (FLAKE8) E131
    continuation line unaligned for hanging indent
    See https://www.flake8rules.com/rules/E131.html

        1771  |        xfail('nn.functional.max_unpool2d'),  # contiguous call
        1772  |        xfail('to_sparse'),  # dispatch key issue
        1773  |
    >>> 1774  |       # https://github.com/pytorch/pytorch/issues/96560
        1775  |        decorate('xlogy', decorator=skipIfRocm),
        1776  |
        1777  |        # numerical inconsistencies, look like bugs
```

**Review by jeffdaily — APPROVED** [review]

**Pull request closed without merging**
