### PR TITLE
Move the search of cuDNN files to FindCUDNN.cmake.

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#24293 Move the search of cuDNN files to FindCUDNN.cmake.**

Differential Revision: [D16834297](https://our.internmc.facebook.com/intern/diff/D16834297)

### CODE REVIEW

**Comment by xuhdev** [comment]
This is the first step towards cleaning up cuDNN detection. Not sure about the test failures. Waiting for Windows build test to recover so we can somewhat assure that this change does not break Windows build.

**Comment by xuhdev** [comment]
The failed tests do not seem to be relevant.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
This broke manywheel on master:

```
Aug 16 14:45:47 + [[ manywheel == \l\i\b\t\o\r\c\h ]]
Aug 16 14:45:47 + python -c 'import torch'
Aug 16 14:45:47 Traceback (most recent call last):
Aug 16 14:45:47   File "<string>", line 1, in <module>
Aug 16 14:45:47   File "/opt/python/cp37-cp37m/lib/python3.7/site-packages/torch/__init__.py", line 81, in <module>
Aug 16 14:45:47     from torch._C import *
Aug 16 14:45:47 ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory
Exited with code 1
```

https://circleci.com/gh/pytorch/pytorch/2486000?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

**Pull request closed without merging**
