### PR TITLE
Re-land: Break graph on `manual_seed`.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108647

Trying to re-land #107594.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by eellison — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Ouch, we are hit again my another internal import error from https://github.com/pytorch/pytorch/blob/main/torch/_inductor/config.py#L205-L206' -c ghfirst

Check with @eellison and the suggestion is to revert instead.  Here is the import error:

```
Test intersection with a plane behind a sphere.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/par_unpack.nsByOoGsX/arvr/projects/eye_tracking/Fringe/test/test_geometry.py", line 23, in setUp
    torch.random.manual_seed(random_seed)
  File "/tmp/par_unpack.nsByOoGsX/torch/_compile.py", line 22, in inner
    import torch._dynamo
  File "/tmp/par_unpack.nsByOoGsX/torch/_dynamo/__init__.py", line 2, in <module>
    from . import allowed_functions, convert_frame, eval_frame, resume_execution
  File "/tmp/par_unpack.nsByOoGsX/torch/_dynamo/convert_frame.py", line 40, in <module>
    from .eval_frame import always_optimize_code_objects, skip_code, TorchPatcher
  File "/tmp/par_unpack.nsByOoGsX/torch/_dynamo/eval_frame.py", line 61, in <module>
    from . import config, convert_frame, external_utils, skipfiles, utils
  File "/tmp/par_unpack.nsByOoGsX/torch/_dynamo/skipfiles.py", line 180, in <module>
    is_fbcode = importlib.import_module("torch._inductor.config").is_fbcode()
  File "/usr/local/fbcode/platform010/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/tmp/par_unpack.nsByOoGsX/torch/_inductor/config.py", line 203, in <module>
    from libfb.py import parutil  # type: ignore[import]
ModuleNotFoundError: No module named 'libfb'

----------------------------------------------------------------------
Ran 1 test in 0.143s
```

**Comment by eellison** [comment]
Sorry for the revert. This is getting reverted because it's causing torch.manual_seed to have a dependency on torch._dynamo. We should figure out another way to graph break without adding the dependency cc @anijain2305

**Comment by ysiraichi** [comment]
@eellison @anijain2305  I guess we could just remove the `disable_dynamo` decorator. Dynamo is able to trace through `manual_seed` function. It does graph-break twice, though. What do you think?

**Pull request closed without merging**
