### PR TITLE
Update CUDA installation script to 12.6.3

### PR DESCRIPTION
**Pull request by tinglvv**
related to https://github.com/pytorch/pytorch/issues/138440

### CODE REVIEW

**Review by atalman — APPROVED** [review]
lgtm

**Comment by Skylion007** [comment]
@tinglvv the PIP_EXTRA installs need to be updated, and the cuda_aarch install script needs also needs to be updated.

**Review by Skylion007 — CHANGES_REQUESTED** [review]
This is missing a lot of changes needed in the build script for AArch, and properly the pypi project and binary updates. #141433

**Pull request closed without merging**
