### PR TITLE
Support neg calls to dyn shapes

### PR DESCRIPTION
**Pull request by voznesenskym**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #94068

cc @mlazos @soumith @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by voznesenskym** [comment]
Interesting inductor failure?

```
File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 697, in call_user_compiler
2023-02-04T01:48:14.3111724Z     raise BackendCompilerFailed(self.compiler_fn, e) from e
2023-02-04T01:48:14.3112131Z torch._dynamo.exc.BackendCompilerFailed: inductor raised LoweringException: TypeError: _operator.neg() takes exactly one argument (0 given)
2023-02-04T01:48:14.3112514Z   target: <built-in function neg>
2023-02-04T01:48:14.3112708Z   args[0]: s0
```
Will look

**Comment by voznesenskym** [comment]
pytorchbot merge -f "XLNetLMHeadModel timeout, a 404 on smoketest, and accuracy failure on a flaky model?"

**Comment by voznesenskym** [comment]
Flaky CI makes this push a little sus. As this change looks pretty safe, Im comfortable pushing. If it gets reverted, apologies to dev infra.

**Comment by voznesenskym** [comment]
pytorchbot merge

**Comment by voznesenskym** [comment]
pytorchbot merge -f "XLNetLMHeadModel says it times out, but it passes on other reruns, flaky?"

**Comment by voznesenskym** [comment]
So there's nothing wrong in this pr per-se, but it fixes a graph break that then causes inductor calling into sympy.gcd to run forever.

**Pull request closed without merging**
