### PR TITLE
Add warpSize to Device properties

### PR DESCRIPTION
**Pull request by ramcherukuri**
Adding warp_size to CudaDeviceProperties.

>>> import torch
>>> prop = torch.cuda.get_device_properties(torch.cuda.current_device())
>>> prop.warp_size
64
>>>

@jeffdaily @pruthvistony @jithunnair-amd @ROCmSupport
 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by eqy — APPROVED** [review]

**Review by jataylo — APPROVED** [review]

**Comment by ramcherukuri** [comment]
@malfet  @huydhn, Can you please help review/merge this ticket. Thank you

**Review by jithunnair-amd — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@malfet Can you please approve/merge this PR? It's blocking another PR https://github.com/pytorch/pytorch/pull/129663

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
