### PR TITLE
[CI]Fix iOS CI

### PR DESCRIPTION
**Pull request by xta0**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#30327 [CI]Fix iOS CI**

### Summary

Seems like starting from macOS 10.15, we can no longer get access to the `Downloads` folder in our macOS machines. 

```
permissionError: [Errno 1] Operation not permitted: '/Users/distiller/Downloads'
```

The fix is to change the conda download directory to ${HOME}

### Test Plan

- iOS jobs are back to normal
- Don't break other jobs

Differential Revision: [D18717380](https://our.internmc.facebook.com/intern/diff/D18717380)

### CODE REVIEW

**Review by mingbowan — APPROVED** [review]
look good to me. 
although "chmod +x" is not necessary here since you run with "/bin/bash ....".

**Comment by xta0** [comment]
> look good to me.
> although "chmod +x" is not necessary here since you run with "/bin/bash ....".

@mingbowan Actually I don't know why this happened. I noted that @hlu1 has reverted my last diff which caused the master broken. Now the master is running the old iOS CI which also does the same thing - download conda.sh to the` ~/Download` folder. But how come that works?

**Comment by xta0** [comment]
Patched the PR - https://github.com/pytorch/pytorch/pull/30133/files

**Review by ezyang — APPROVED** [review]
Seems reasonable, I guess? I'm not too sure what's going on with the simulator shell script or the ruby changes.

**Pull request closed without merging**
