### PR TITLE
[dtensor] delete the old unused mesh_alltoall

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #124879
* #124872
* #124871

as titled, as we have a dedicated comm op, this is not needed anymore

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

### CODE REVIEW

**Review by XilunWu — APPROVED** [review]
Remove unused code path. LGTM.

**Review by wz337 — APPROVED** [review]
LGTM. 

Some test_dtensor_ops.py tests seem flaky (hopefully the PRs fixing the APF tests could fix this). Not sure if it is related to threaded backend + DeviceMesh.

**Pull request closed without merging**
