### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by shauray8**
Fixes #{60864}

### CODE REVIEW

**Comment by mruberry** [comment]
@wenleix might be easier to include a tiny spelling correction like this in a larger PR

**Comment by shauray8** [comment]
Sure I'll try solving some more issues then

**Comment by wenleix** [comment]
@mruberry do you mean send out one PR that solves many typos in one ? -- is there any tool to find all spelling issues in the repo?

**Comment by mruberry** [comment]
> @mruberry do you mean send out one PR that solves many typos in one ? -- is there any tool to find all spelling issues in the repo?

Many typos in one or sneaking a typo fix into another PR

**Pull request closed without merging**
