### PR TITLE
Allow PrivateUse1 backends to not have Storage

### PR DESCRIPTION
**Pull request by smk2007**
Allow PrivateUse1 backends to not have Storage

To unblock the DirectML backend, this change would be needed for 1.13 as well.

The DirectML backend creates tensors using the open registration pattern documented here: https://pytorch.org/tutorials/advanced/extend_dispatcher.html
[registration example](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbdhirsh%2Fpytorch_open_registration_example&data=05%7C01%7CSheil.Kumar%40microsoft.com%7Cf107b0b4349e41f1a57808daa7ee8a2c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638006940242882444%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ivYLNmuC1WMitwu8n%2B1RAmeKkRM4ssb7EvhhGKJDFwk%3D&reserved=0)

However, DirectML tensors are opaque, and do not have Storage.
The DirectML Tensor Impl derives from OpaqueTensorImpl, which does not have a storage. Because of this various places in the code fail that expect storage to be present. We had made various changes in-tree to accommodate this:
a.	def __deepcopy__(self, memo):
[https://github.com/pytorch/pytorch/blob/b5acba88959698d35cb548c78dd3fb151f85f28b/torch/_tensor.py#L119](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpytorch%2Fpytorch%2Fblob%2Fb5acba88959698d35cb548c78dd3fb151f85f28b%2Ftorch%2F_tensor.py%23L119&data=05%7C01%7CSheil.Kumar%40microsoft.com%7Cf107b0b4349e41f1a57808daa7ee8a2c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638006940242882444%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ajg23nMCzgRDwlinqSxS%2BRmOkAcDCr3LW%2BBEfNCn5hw%3D&reserved=0)
or self.device.type in ["lazy", "xla", "mps", "ort", "meta", "hpu", 'dml']
b.	def _reduce_ex_internal(self, proto):
[https://github.com/pytorch/pytorch/blob/b5acba88959698d35cb548c78dd3fb151f85f28b/torch/_tensor.py#L275](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpytorch%2Fpytorch%2Fblob%2Fb5acba88959698d35cb548c78dd3fb151f85f28b%2Ftorch%2F_tensor.py%23L275&data=05%7C01%7CSheil.Kumar%40microsoft.com%7Cf107b0b4349e41f1a57808daa7ee8a2c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638006940242882444%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xDW6LwPSe2F396OJ6QSJY6mVzJVDeQiJgA0G347y2pw%3D&reserved=0)
if self.device.type in ["xla", "ort", "hpu", "dml"]:
c.	TensorIteratorBase::build has an unsupported list for tensors without storage.
[https://github.com/pytorch/pytorch/blob/b5acba88959698d35cb548c78dd3fb151f85f28b/aten/src/ATen/TensorIterator.cpp#L1497](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpytorch%2Fpytorch%2Fblob%2Fb5acba88959698d35cb548c78dd3fb151f85f28b%2Faten%2Fsrc%2FATen%2FTensorIterator.cpp%23L1497&data=05%7C01%7CSheil.Kumar%40microsoft.com%7Cf107b0b4349e41f1a57808daa7ee8a2c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638006940242882444%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qAdgNgzKl0xrtOvsABpw1VGkSoGUpe7jwDPhHw3XjgU%3D&reserved=0)

Using the PrivateUse1 backend, similar exemptions need to be made in order to relax requirements on Storage so that the DirectML backend tensors can work.

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
Thanks for identifying issues with using the `PrivateUse1` key! These changes look reasonable to me.

**Comment by bdhirsh** [comment]
Can you sign the CLA? That's needed to land the PR.

> To unblock the DirectML backend, this change would be needed for 1.13 as well.

The branch cut for the 1.13 release was a few days ago. There's an option for cherry-picking commits into the branch, but there are some criteria for what's allowed to be cherry-picked. You can see the details for the process here: https://github.com/pytorch/pytorch/issues/86312

**Review by martinb35 — APPROVED** [review]

**Comment by smk2007** [comment]
> Can you sign the CLA? That's needed to land the PR.
> 
> > To unblock the DirectML backend, this change would be needed for 1.13 as well.
> 
> The branch cut for the 1.13 release was a few days ago. There's an option for cherry-picking commits into the branch, but there are some criteria for what's allowed to be cherry-picked. You can see the details for the process here: #86312

Thanks! 

I see some of the CI checks failed. They dont seem related to the changes. Is there a way to re-run these failing CI tests?

**Comment by smk2007** [comment]
> > Can you sign the CLA? That's needed to land the PR.
> > > To unblock the DirectML backend, this change would be needed for 1.13 as well.
> > 
> > 
> > The branch cut for the 1.13 release was a few days ago. There's an option for cherry-picking commits into the branch, but there are some criteria for what's allowed to be cherry-picked. You can see the details for the process here: #86312
> 
> Thanks [bdhirsh](https://github.com/bdhirsh)!
> 
> I see some of the CI checks failed. They dont seem related to the changes. Is there a way to re-run these failing CI tests?

@bdhirsh Another signoff greatly appreciated 

> Thanks for identifying issues with using the `PrivateUse1` key! These changes look reasonable to me.

I believe i need a maintainer to approve. Is there someone I need to ping to make this happen? Thanks!

**Comment by smk2007** [comment]
> Can you sign the CLA? That's needed to land the PR.
> 
> > To unblock the DirectML backend, this change would be needed for 1.13 as well.
> 
> The branch cut for the 1.13 release was a few days ago. There's an option for cherry-picking commits into the branch, but there are some criteria for what's allowed to be cherry-picked. You can see the details for the process here: #86312

@bdhirsh Created this PR for CPing into release/1,13: https://github.com/pytorch/pytorch/pull/86803

**Comment by bdhirsh** [comment]
@smk2007 sounds good - you'll also have to put in a request to the infra team on the release tracker issue: https://github.com/pytorch/pytorch/issues/86312

**Comment by smk2007** [comment]
> @smk2007 sounds good! - you'll also have to put in a request to the infra team on the release tracker issue: #86312

Thanks, I also opened this PR into master, which contains a fix to this same change. The storage check was done incorrectly. This should be done correctly now! https://github.com/pytorch/pytorch/pull/86845

**Pull request closed without merging**
