### PR TITLE
Install GCC-9 into ROCm builders

### PR DESCRIPTION
**Pull request by malfet**
Should prevent intermittent internal compiler errors reported in https://bugs.launchpad.net/ubuntu/+source/gcc-7/+bug/1917830

### CODE REVIEW

**Review by xuzhao9 — APPROVED** [review]

**Comment by jeffdaily** [comment]
@malfet did it actually rebuild the rocm images?  The duration on the job logs are < 2 min.  Seems way too fast.

**Comment by seemethere** [comment]
> @malfet did it actually rebuild the rocm images? The duration on the job logs are < 2 min. Seems way too fast.

If the jobs are run multiple times it should just use the first cached build, although this actually might need to be re-built after #53412 is merged

**Comment by seemethere** [comment]
I've rebased and pushed

**Review by seemethere — APPROVED** [review]

**Comment by malfet** [comment]
Hmm, looks like https://app.circleci.com/pipelines/github/pytorch/pytorch/282353/workflows/53509f90-235f-481f-a6d3-1b5634a671f5/jobs/11375958 doesn't think it needs to build anything?
@seemethere do you know why?

**Comment by malfet** [comment]
Looks like I can not test it on PR for some reason, let's see what will happen if this change lands on master

**Comment by malfet** [comment]
So, https://app.circleci.com/pipelines/github/pytorch/pytorch/282615/workflows/3f4c4264-a031-489e-81a8-197669b077d3/jobs/11390077 rebuild the docker image with gcc-9, but according to https://app.circleci.com/pipelines/github/pytorch/pytorch/282730/workflows/0acd2a02-0623-4076-9cd0-ae6600d3317e/jobs/11396118 old image is still in use

**Pull request closed without merging**
