### PR TITLE
[LTC] Upstream LazyTensor and LazyGraphExecutor

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #69815
* #69716
* #69621

Differential Revision: [D33059774](https://our.internmc.facebook.com/intern/diff/D33059774)

### CODE REVIEW

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33059774).

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33059774).

**Review by wconstab — APPROVED** [review]
Stamping since we identified that working half-way between staging/master is costing us efficiency, so we want to accelerate merging remaining pieces.  I think this code probably still could use some cleanup, and we'll want to focus on performance aspects as we work on reducing overheads.

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33059774).

**Pull request closed without merging**
