### PR TITLE
Suppress output when checking hipcc

### PR DESCRIPTION
**Pull request by innerlee**
Otherwise, it will print some message when hipcc is not found.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by 13952522076** [comment]
I also encounter this problem
`
which: no hipcc in (/home/usr/local/bin:/home/xuma/miniconda3/bin:/home/usr/miniconda3/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/cuda-10.1/bin:/home/usr/.local/bin:/home/xuma/bin)`

Could you please tell me how to suppress this output?
my pytorch version is 1.5.1

**Comment by WHCer** [comment]
As mention above, modify the cpp_extension.py file in /lib/python3.7/site-packages/torch/utils/cpp_extension.py

https://github.com/pytorch/pytorch/commit/048e19749b77df6a7aa327471ad919d420b22792

**Comment by 13952522076** [comment]
> As mention above, modify the cpp_extension.py file in /lib/python3.7/site-packages/torch/utils/cpp_extension.py
> 
> [048e197](https://github.com/pytorch/pytorch/commit/048e19749b77df6a7aa327471ad919d420b22792)

@WHCer It really works. Thanks a lot.

**Comment by johnlanbor** [comment]
That seems cant solve my problem.
still meet this error.

**Pull request closed without merging**
