### PR TITLE
Refine return type Stream to HIPStream in HIPStreamGuardMasqueradingAsCUDA

### PR DESCRIPTION
**Pull request by ezyang**
Previously, we used the templated class directly to provide
implementations.  However, there is a subtle difference
between this, and CUDAStreamGuard: CUDAStreamGuard has refined types
for the Streams it returns.  This lead to a compilation failure
of HIPified ddp.cpp.  This commit lines them up more closely,
at the cost of copy-paste.

A possible alternate strategy would have been to extend the
InlineDeviceGuard templates to optionally accept refinements
for Stream.  I leave this for future work.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
cc @jithunnair-amd

**Comment by jithunnair-amd** [comment]
@ezyang Looks good, or do we need to rerun CI?

**Comment by ezyang** [comment]
CI coverage looks sufficient

**Pull request closed without merging**
