### PR TITLE
Add magma for CUDA 10.1 to Windows docs

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by SsnL** [comment]
it'd be nice to update the main readme too :)

**Comment by SsnL** [comment]
oh i guess that isn't a thing for linux yet..

**Comment by peterjc123** [comment]
Magma installation works differently on Linux. They are installed through conda, unlike Windows, in which we install by downloading the files and setting env vars.

**Comment by jottbele** [comment]
Hi, I read that a new release of PyTorch is out now and was wondering, if now PyTorch also supports CUDA 10.1 on Linux based systems. In the release note I couldn't find anything about it, but I thought because Windows was already added month before it may be, that the change just wasn't mentioned.

**Pull request closed without merging**
