### PR TITLE
make `TORCH_(CUDABLAS|CUSOLVER)_CHECK` usable in custom extensions

### PR DESCRIPTION
**Pull request by crcrpar**
Make `TORCH_CUDABLAS_CHECK` and `TORCH_CUSOLVER_CHECK` available in custom extensions by exporting the internal functions called by the both macros.

Rel: https://github.com/pytorch/pytorch/issues/67073

cc @xwang233 @ptrblck

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by mruberry** [comment]
Reverting as this appears to have broken Windows CUDA jobs. See https://github.com/pytorch/pytorch/runs/4052843481?check_suite_focus=true and https://github.com/pytorch/pytorch/runs/4052717247?check_suite_focus=true for examples.

**Comment by ngimel** [comment]
Hey @crcrpar can you please resubmit this PR skipping windows test? If you can figure out what's failing with windows that'd be great, but if not, we can at least fix linux extensions (windows is not getting worse, right? It couldn't have extensions with TORCH_CUDABLAS_CHECK, and it still can't?)

**Comment by crcrpar** [comment]
sure, was busy a bit.

**Comment by crcrpar** [comment]
hmm, the commit mentioned above comment is the same one as in https://github.com/pytorch/pytorch/pull/67161#issuecomment-955189904

**Comment by mruberry** [comment]
> hmm, the commit mentioned above comment is the same one as in [#67161 (comment)](https://github.com/pytorch/pytorch/pull/67161#issuecomment-955189904)

The bot had an issue where it was repeating revert messages; sorry about that, @crcrpar

**Pull request closed without merging**
