### PR TITLE
[JIT] Optimize before inlining

### PR DESCRIPTION
**Pull request by eellison**
Resubmit of https://github.com/pytorch/pytorch/pull/35424, only this time I run optimizations in the right order so the PR description is actually true. 

This speeds up the inlining pass of FairSeq model from 180s -> 13s, and MaskRCNN model from 5s -> 1.5s.

### CODE REVIEW

**Review by ZolotukhinM — APPROVED** [review]
Looks good!

**Comment by BowenBao** [comment]
Same error as https://github.com/pytorch/pytorch/pull/35401. I don't think this PR is causing the failure. It seems the one causing the failure is already in master. @houseroad 

```
Mar 31 01:07:01     def test_dim(self):
Mar 31 01:07:01         class DimModel(torch.jit.ScriptModule):
Mar 31 01:07:01             @torch.jit.script_method
Mar 31 01:07:01             def forward(self, input):
Mar 31 01:07:01                 out = input * 2
Mar 31 01:07:01                 out *= out.dim()
Mar 31 01:07:01                 return out
Mar 31 01:07:01         empty_input = torch.randn(0, requires_grad=True)
Mar 31 01:07:01         multi_dim_input = torch.randn(1, 2, 3, requires_grad=True)
Mar 31 01:07:01         self.run_test(DimModel(), empty_input)
Mar 31 01:07:01 >       self.run_test(DimModel(), multi_dim_input)
Mar 31 01:07:01 
Mar 31 01:07:01 test/onnx/test_pytorch_onnx_onnxruntime.py:2684: 
Mar 31 01:07:01 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Mar 31 01:07:01 test/onnx/test_pytorch_onnx_onnxruntime.py:126: in run_test
Mar 31 01:07:01     _run_test(model)
Mar 31 01:07:01 test/onnx/test_pytorch_onnx_onnxruntime.py:122: in _run_test
Mar 31 01:07:01     fixed_batch_size=fixed_batch_size)
Mar 31 01:07:01 test/onnx/test_pytorch_onnx_onnxruntime.py:86: in run_model_test
Mar 31 01:07:01     ort_test_with_input(ort_sess, input_copy, output, rtol, atol)
Mar 31 01:07:01 test/onnx/test_pytorch_onnx_onnxruntime.py:47: in ort_test_with_input
Mar 31 01:07:01     [np.testing.assert_allclose(out, ort_out, rtol=rtol, atol=atol) for out, ort_out in zip(outputs, ort_outs)]
Mar 31 01:07:01 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Mar 31 01:07:01 
Mar 31 01:07:01 .0 = <zip object at 0x7f3d38393d48>
Mar 31 01:07:01 
Mar 31 01:07:01 >   [np.testing.assert_allclose(out, ort_out, rtol=rtol, atol=atol) for out, ort_out in zip(outputs, ort_outs)]
Mar 31 01:07:01 E   AssertionError: 
Mar 31 01:07:01 E   Not equal to tolerance rtol=0.001, atol=1e-07
Mar 31 01:07:01 E   
Mar 31 01:07:01 E   Mismatched elements: 6 / 6 (100%)
Mar 31 01:07:01 E   Max absolute difference: 8.715158
Mar 31 01:07:01 E   Max relative difference: 0.6666667
Mar 31 01:07:01 E    x: array([[[ 3.081992, -0.586858, -4.357579],
Mar 31 01:07:01 E           [ 1.136863, -2.169045, -2.797191]]], dtype=float32)
Mar 31 01:07:01 E    y: array([[[  9.245976,  -1.760573, -13.072737],
Mar 31 01:07:01 E           [  3.410588,  -6.507134,  -8.391573]]], dtype=float32)
```

**Comment by eellison** [comment]
@BowenBao how do you recommend I proceed ? as far as I can tell the test is not failing on master.

**Comment by BowenBao** [comment]
@eellison yea I checked a few other PRs and they don't seem to fail on this one, so I edited my previous comment. One thing bothers me is that you mentioned in the other PR that you could not repro this error locally. Let me change the `randn` in the failed `test_dim` to `ones`, this should help debugging.

**Comment by eellison** [comment]
@BowenBao could you check out the PR ?

**Pull request closed without merging**
