### PR TITLE
[DataLoader] default_collate should collate bool list to byte tensors

### LINKED ISSUE #14507: default_collate unexpected types
## 🐛 Bug
[`default_collate`](https://github.com/pytorch/pytorch/blob/ca55c5411fa61c6b1f8d617b42f755ae46577cae/torch/utils/data/dataloader.py#L196) converts *python* bools to ints.

## To Reproduce
`default_collate` gives the following behavior (this can happen when `default_collate` is applied recursively on say, a dictionary)
```python
from torch.utils.data.dataloader import default_collate
default_collate([True, False]).dtype
>> torch.int64
```
On the other hand:
```python
import torch
torch.tensor([True, False]).dtype
>> torch.uint8
```

## Expected behavior

I believe `default_collate` should be consistent with `torch.tensor`.
I suggest replacing [these two scalar tests](https://github.com/pytorch/pytorch/blob/ca55c5411fa61c6b1f8d617b42f755ae46577cae/torch/utils/data/dataloader.py#L222) with
```python
import numbers
...
elif isinstance(batch[0], numbers.Number):
    return torch.tensor(batch)
```

## Environment

Please copy and paste the output from our

 - PyTorch Version (e.g., 1.0): 0.4.1
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): NA
 - Python version: 3.7
 - CUDA/cuDNN version: NA
 - GPU models and configuration: NA
 - Any other relevant information: NA

### PR DESCRIPTION
**Pull request by ssnl**
Based on #15331 . Review only the last commit.

Fixes https://github.com/pytorch/pytorch/issues/14507.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Kind of indirect, but ok.

**Comment by ezyang** [comment]
Laurens van der Maaten says that this broke some internal tests. I'm asking him for some more details

**Comment by SsnL** [comment]
@soumith said that he fixed the internal errors before landing.

**Comment by soumith** [comment]
i reran the internal tests and they passed :-/

**Pull request closed without merging**
