### PR TITLE
Fix torch.nn.functional.gelu docstring formatting

### PR DESCRIPTION
**Pull request by cherrywoods**
The docstring of `torch.nn.functional.gelu` is formatted incorrectly, so that part of the math isn't rendered and there are extra blocks when there shouldn't: https://pytorch.org/docs/stable/generated/torch.nn.functional.gelu.html

I didn't build the docs, so I am not 100% sure that I got the formatting right, but I am confident.

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
Thanks for the fix!

**Comment by bdhirsh** [comment]
The pytorch bot comment (https://github.com/pytorch/pytorch/pull/89061#issuecomment-1315401828) gives a link to the built docs, which I confirmed look better now.

**Comment by cherrywoods** [comment]
> The pytorch bot comment ([#89061 (comment)](https://github.com/pytorch/pytorch/pull/89061#issuecomment-1315401828)) gives a link to the built docs, which I confirmed look better now.

Thanks, I suppose I wasn't patient enough. When I checked it showed me an error, which made me suspect I didn't have permission or something, but now it works.

**Comment by cherrywoods** [comment]
While we're at it: Is it intended that the square-root in the GELU formula isn't ranging over the whole `(2/pi)`, but only over the bracket?

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
