### PR TITLE
Add optional tensor arguments to __torch_function__ handling checks

### LINKED ISSUE #63435: Norm functions don't call __torch_function__ for weights or bias
## 🐛 Bug

Norm functions like GroupNorm only call `__torch_function__` for the inputs, not any weights passed in

## To Reproduce
To demonstrate with print statements, this uses this toy tensor class:
```
import torch
import torch.nn.functional as F

class TestTensor(object):
    def __init__(self, weight):
        self.weight = weight

    def __torch_function__(self, func, _, args=(), kwargs=None):
        print(func)
        print(func == F.group_norm)
```

Case 1:
```
features = TestTensor(torch.randn(3,3))
F.group_norm(features, 3)
```
prints out group_norm and True, so `__torch_function__` is being called with `F.group_norm`

Case 2:
```
features = torch.randn(3,3)
weight = TestTensor(torch.randn(3))
F.group_norm(features, 3, weight=weight)
```
will instead print out group_norm and False. weight's `__torch_function__` is called from `torch.group_norm` instead of `F.group_norm`

## Expected behavior

I would expect in both cases would print group_norm and True, meaning that they're being called with the functional group_norm

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.10.0a0+gitde3a4eb
 - OS (e.g., Linux): Ubuntu 18.04.5 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py install
 - Python version: 3.9.5
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: A100-SXM4-40GB
 - Any other relevant information:

## Additional context

If this is not the expected behavior, [this line](https://github.com/pytorch/pytorch/blob/517aa8965abed79a044fb383ad13a841f8f85c1b/torch/nn/functional.py#L2357) might want to look like [this](https://github.com/pytorch/pytorch/blob/517aa8965abed79a044fb383ad13a841f8f85c1b/torch/nn/functional.py#L3286)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano @hameerabbasi @rgommers @peterbell10

### PR DESCRIPTION
**Pull request by samdow**
Fixes #63435

Adds optional tensor arguments to check handling torch function checks. The only one I didn't do this for in the functional file was `multi_head_attention_forward` since that already took care of some optional tensor arguments but not others so it seemed like arguments were specifically chosen 

cc @ezyang @gchanan

### CODE REVIEW

**Comment by ezyang** [comment]
> From my understanding, torchscript doesn't support variadic functions and so this PR would break torchscript support for all of these functions?

This smells like FUD. Frontend specificially handles variadic:

```
# torch/jit/_script.py
_register_builtin(has_torch_function, "aten::has_torch_function")
_register_builtin(has_torch_function_unary, "aten::has_torch_function")
_register_builtin(has_torch_function_variadic, "aten::has_torch_function")
```

and

```
// torch/csrc/jit/frontend/ir_emitter.cpp
if (kind == aten::has_torch_function) {
          static_if = false;
        }
```

**Comment by ezyang** [comment]
Can you add a smoketest for one of the cases here? Testing everything regularly is a bit involved and I won't make you do it here, just would be good to make sure that this works at all at least in one case.

**Comment by ezyang** [comment]
follow up testing at https://github.com/pytorch/pytorch/issues/64187

**Review by ezyang — APPROVED** [review]

**Comment by albanD** [comment]
This is actually bc-breaking as some arguments that used not to be considered in `__torch_function__` handling are now looked at (bias for linear for example).
I think this is ok but worth mentioning in the release notes.

**Pull request closed without merging**
