### PR TITLE
[profiler ut] Update event name in test_profiler.py

### PR DESCRIPTION
**Pull request by fwenguang**
Fixes #ISSUE_NUMBER
To support kernel name with some uppercase letters.

### CODE REVIEW

**Comment by fwenguang** [comment]
Hi @aaronenyeshi , we override cuda to run test_profiler.py, but there are some hardcoded strings that are incompatible. So, I hope this patch is accepted.

**Review by aaronenyeshi — APPROVED** [review]
LGTM

**Comment by aaronenyeshi** [comment]
I'm not sure why this test is failing:
```
2024-07-30T04:02:08.0209511Z _ TestSDPACudaOnlyCUDA.test_flash_attention_vs_math_ref_grads_batch_size_1_seq_len_q_1024_seq_len_k_1024_head_dim_8_is_causal_True_dropout_p_0_22_bfloat16_scale_l1_cuda_bfloat16 _
2024-07-30T04:02:08.0210379Z Traceback (most recent call last):
2024-07-30T04:02:08.0211241Z   File "/var/lib/jenkins/workspace/test/test_transformers.py", line 3029, in test_flash_attention_vs_math_ref_grads
2024-07-30T04:02:08.0211946Z     check_out_and_grad(
2024-07-30T04:02:08.0212496Z   File "/var/lib/jenkins/workspace/test/test_transformers.py", line 184, in check_out_and_grad
2024-07-30T04:02:08.0213223Z     _check_equal(ref_grad, lp_ref_grad, comp_grad, fudge_factors.get(name, default_fudge_factor), name)
2024-07-30T04:02:08.0214012Z   File "/var/lib/jenkins/workspace/test/test_transformers.py", line 144, in _check_equal
2024-07-30T04:02:08.0214592Z     raise ValueError(msg)
2024-07-30T04:02:08.0215177Z ValueError: grad_query Test error 3.682415246963501 is greater than threshold 1.6739894151687622!
2024-07-30T04:02:08.0215739Z 
2024-07-30T04:02:08.0216034Z To execute this test, run the following from the base repo dir:
2024-07-30T04:02:08.0217053Z     python test/test_transformers.py -k TestSDPACudaOnlyCUDA.test_flash_attention_vs_math_ref_grads_batch_size_1_seq_len_q_1024_seq_len_k_1024_head_dim_8_is_causal_True_dropout_p_0_22_bfloat16_scale_l1_cuda_bfloat16
2024-07-30T04:02:08.0217840Z 
2024-07-30T04:02:08.0218106Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

**Pull request closed without merging**
