### PR TITLE
[inuctor] fix the layout problem for nll_loss2d_backward

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #121173

Fixes https://github.com/pytorch/pytorch/issues/120759 .

The CUDA implementation of nll_loss2d_backward.default requires that the 'self' tensor to be contiguous. These implicit assumption may be broken by layout optimizations. The fix here is to add the constraint when we explicitly defining the fallback for the op.

Not sure if we can improve the cuda kernel to release the constraints though.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by Chillee** [comment]
Shouldn't we just decompose `aten.nll_loss2d_backward`?

**Comment by shunting314** [comment]
> Shouldn't we just decompose aten.nll_loss2d_backward?
Ah I didn't realize a decomposition already exists until I see you comment and the CI failures. Will do that.

**Review by jansel — APPROVED** [review]

**Review by desertfire — APPROVED** [review]

**Comment by desertfire** [comment]
CI failure is likely a rebase issue, https://github.com/pytorch/pytorch/pull/121206/

**Pull request closed without merging**
