### PR TITLE
Rename previously THNN conv kernels to have naive_ prefix.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#23790 Rename previously THNN conv kernels to have naive_ prefix.**

The old name, e.g., "conv_dilated3d", implies that this is some sort
of general convolution which can always be used when you want a dilated
3d convolution.  But this couldn't be further from the truth: this gives
you the naive, historically from THNN convolution.  Rename them to have
"naive" in the name to help people realize they're calling the wrong
thing.

Help resolve some confusion in #23562

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D16650364](https://our.internmc.facebook.com/intern/diff/D16650364)

### CODE REVIEW

**Comment by soumith** [comment]
nit: Naive -> Slow

**Comment by fmassa** [comment]
Why not just rename it like the others, `thnn_dilated_conv3d`?

**Comment by ezyang** [comment]
@fmassa I considered it, but because we have a mix of old-style and new-style dispatch going on here, I think it's helpful to make them have different names to just help people know that the slow/naive implementations don't live in THNN folder (which is what `thnn_` would imply)

@soumith Alright, we can call it slow :)

**Comment by ailzhang** [comment]
I wonder if there's a guideline anywhere about which prefix to use? ;)

**Review by ailzhang — APPROVED** [review]
Thanks!

**Comment by ezyang** [comment]
@ailzhang https://github.com/pytorch/pytorch/pull/23790/files#diff-f1e4b2c15de770d978d0eb77b53a4077R5447 is the best explanation for now. As for whether or not a kernel is slow... that's something you'll have to take a look at and see.

**Pull request closed without merging**
