### PR TITLE
Fix unintended deprecation warning in torch.distributed.optim

### PR DESCRIPTION
**Pull request by yifuwang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #140889

We have a deprecation warning for scripted functional optimizer at module level in `torch/distributed/optim/__init__.py`. However, not all optimizers exposed by the module are scripted functional optimizers, causing some false deprecation warning (e.g. https://github.com/pytorch/pytorch/issues/139661).

This PR moves the deprecation warning to the `__init__` functions of the deprecated scripted functional optimizers.

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Comment by Name-none01** [comment]
> Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
> 
> * **->** [Fix unintended deprecation warning in torch.distributed.optim #140889](https://github.com/pytorch/pytorch/pull/140889)
> 
> We have a deprecation warning for scripted functional optimizer at module level in `torch/distributed/optim/__init__.py`. However, not all optimizers exposed by the module are scripted functional optimizers, causing some false deprecation warning (e.g. #139661).
> 
> This PR moves the deprecation warning to the `__init__` functions of the deprecated scripted functional optimizers.
> 
> cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Review by d4l3k — APPROVED** [review]
LGTM

**Review by kwen2501 — APPROVED** [review]

**Review by XilunWu — APPROVED** [review]

**Pull request closed without merging**
