### PR TITLE
[c2][serialized_tests] Refactor tests part 1

### PR DESCRIPTION
**Pull request by ajyu**
Followup to [the serialized test framework](https://github.com/pytorch/pytorch/pull/10594)

Round 1 for refactoring tests, starting alphabetically. I added some functionality, so I wanted to send out some of these initial changes sooner.
1. Start alphabetically producing serialized outputs for test functions, annotating those we want to include with `@given_and_seeded`. So far I've only added one test per operator, but this already does seem to add quite a few tests.
2. Add functionality to allow us to generate outputs using pytest by adding pytest argument options. This allows us to skip adding a `__main__` function to quite a few tests.
3. Catch any exceptions generating the gradient operator and skip serializing/reading it, since certain operators don't have gradients.

I also noticed that there is some hypothesis handling that makes `@given_and_seeded` not compatible with adding more hypothesis decorators on top. For example, there are tests that do 
```
@settings(...)
@given(...)
def test_my_stuff(...)
```
But there is a hypothesis handler that explicitly checks that `@given` is called below `@settings`, so we cannot refactor this to `@given_and_seeded`. I've just avoided decorating these kinds of tests for now, I hope that's alright.

### CODE REVIEW

**Comment by ajyu** [comment]
@houseroad @ilia-cher @BIT-silence for review

**Comment by apaszke** [comment]
Reposting from #10594, since this will probably get more visibility here.

Do we really believe that checked in tests are a good idea? I'm pretty sure that having more rigorous test harness will provide much better coverage, and have a benefit of not checking in a new file after every single operator change. Here's how I see it:

Operator code is generally quite self-contained, so it's unlikely that a change in one part of the system will affect a random operator on the other end. Unless it's a breakage so bad that most operator tests will be red anyway. On the other hand, if someone changes the operator kernels, the tiny numerical differences might change e.g. the few least-significant bits, raising a failure when compared to the expected test. Since this was a PR that updates an op, I believe the author will be more than happy to check in a new set of expected outputs, meaning that those values don't mean much. Finally, you can't test all ops this way, because if you use an external library, just updating it to a new version (or having a different cuDNN version installed) might result in those tiny differences, flaring up the whole test suite for no good reason.

We actually took a similar approach for testing the PyTorch JIT some time ago (we serialize IR as text, not binary tensor values), but it has many scalability problems, and is notoriously hard to review. We already had many situations where the test had a good expect file checked in, only to have it overwritten with a non-working one in a later PR (and we do pretty careful code review). After the release, we'll probably try to move away from comparing to expected values, and you might want to consider that too.

**Comment by ajyu** [comment]
@apaszke, the motivation for these tests mainly comes from a past sev where changes to operator semantics make an operator not backward compatible. There is some more context in this [quip](https://fb.quip.com/tVg1AImdjoKY). While we recognize that implementation differences may cause small differences when compared to an expected test, we think that having such a mechanism will help  us better catch more egregious cases. Backwards incompatible changes are otherwise hard to catch in unit tests since code modifiers would typically change matching tests to pass when making a semantically different change.

One possibility is strongly relaxing the tolerance requirements to hopefully prevent failures due to the subtlest implementation updates.

Other things that we can do that are more ambitious would be to track models run in production and track some serialized inputs matched with either outputs or higher level aggregate statistics which shouldn't differ widely with code change.

**Comment by ajyu** [comment]
@apaszke and I discussed offline. We'll stick with serialized testing for now since it's hard to come up with ways of ensuring backwards compatibility that are both clean and reliable. However, to address the issue of adding a bunch of small files to git, we'll instead store the files in S3/gluster. This PR will be put on hold until then.

**Pull request closed without merging**
