### PR TITLE
Update to cuda 12.4.1

### LINKED ISSUE #126005: CUDNN not detected in official nightly devel image
### 🐛 Describe the bug

Compiling from sources in the original nightly devel image CUDNN is not detected:
`docker pull ghcr.io/pytorch/pytorch-nightly:2.4.0.dev20240511-cuda12.4-cudnn8-devel` + https://github.com/pytorch/pytorch?tab=readme-ov-file#from-source

/cc @albanD @atalman @malfet 

### Versions

main

### PR DESCRIPTION
**Pull request by bhack**
Fixes #126005

### CODE REVIEW

**Comment by bhack** [comment]
This is going to sync on nightly images the upgrade we are doing at:
https://github.com/pytorch/pytorch/pull/123475#issuecomment-2130533796

**Comment by atalman** [comment]
hi @bhack we are close to branch cut for 2.4  : M3.1: Release branch cut (6/10/24)

We probably want to keep 2.4.0 at this point. If we want to update to next version, we would need to follow this runbook and make sure this is updated across the board: https://github.com/pytorch/builder/blob/main/CUDA_UPGRADE_GUIDE.MD

We can probably start looking into this right after branch cut for 2.4 is completed

**Comment by atalman** [comment]
I see, its related to this issue: https://github.com/pytorch/pytorch/issues/126005 . At this point I think would be easier for us to add cudnn layer to existing images rather then do cuda update to 12.4.1

**Comment by bhack** [comment]
Yes it is related to that ticket cause we have many ways to deliver cudnn between different artifacts.

**Pull request closed without merging**
