### PR TITLE
Move the CUDA implementation of log2 to ATen.

### LINKED ISSUE #24589: Migrate `log2` and `log2_` from the TH to Aten (CUDA)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #27372 Move the CUDA implementation of sqrt to ATen.
* #26923 Move the CUDA implementation of log1p to ATen.
* **#26769 Move the CUDA implementation of log2 to ATen.**

Fix #24589

Differential Revision: [D17960122](https://our.internmc.facebook.com/intern/diff/D17960122)

### CODE REVIEW

**Review by VitalyFedyunin — APPROVED** [review]
LGTM, please rebase after landing of #26733

**Comment by xuhdev** [comment]
Absolutely!

**Comment by xuhdev** [comment]
@VitalyFedyunin Rebased

**Comment by xuhdev** [comment]
Rebased to resolve a conflict

**Comment by xuhdev** [comment]
@VitalyFedyunin Are you landing this one? I can do a rebase if you are not

**Comment by VitalyFedyunin** [comment]
Feel free to rebase, I will land right after (please ping me)

**Comment by xuhdev** [comment]
@VitalyFedyunin Done!

**Pull request closed without merging**
