### PR TITLE
Add swap_tensors path to nn parametrizations

### LINKED ISSUE #123859: reparameterization should use swap_tensors for tensor subclasses
as titled, we should use `swap_tensors` for reparameterization when using tensor subclasses, currently it's using `original.set_` which would not work for tensor subclass https://github.com/pytorch/pytorch/blob/main/torch/nn/utils/parametrize.py#L160

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Fixes #123859

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #124130

### CODE REVIEW

**Review by mikaylagawarecki — COMMENTED** [review]
The dynamo skips for some `swap_True` tests are because dynamo holds weakrefs which causes swap_tensors to fail

**Review by albanD — COMMENTED** [review]
Sounds good to me!
Will let @lezcano chime in as well in case there is anything missing from his point of view

**Review by albanD — APPROVED** [review]
Let's merge this and @lezcano can complain once he's back from PTO if we missed anything!

**Review by lezcano — COMMENTED** [review]
SG!

**Comment by DanilBaibak** [comment]
Hi @mikaylagawarecki! Sorry, I need to revert your PR because it broke the linter on the main branch. Here you can find more information about the issue - https://hud.pytorch.org/pytorch/pytorch/commit/64f6ddf12c11738c3f4b1ed01cf4f699541496bf

**Pull request closed without merging**
