### PR TITLE
skip primTorch nvfuser tests on rocm

### LINKED ISSUE #77236: test_broadcast_in_dim_cuda_float32 (__main__.TestPrimsCUDA) error
A recent PR https://github.com/pytorch/pytorch/pull/76790 causes consistent failure in rocm ci

test currently disabled in https://github.com/pytorch/pytorch/issues/77237 

full log: https://ossci-raw-job-status.s3.amazonaws.com/log/6376085362
error signature:
```
ERROR [0.453s]: test_broadcast_in_dim_cuda_float32 (__main__.TestPrimsCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/_prims/executor.py", line 64, in execute
    tuple(arg for arg in args if isinstance(arg, torch.Tensor))
RuntimeError: false INTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/torch/csrc/jit/codegen/cuda/executor_utils.cpp":1054, please report a bug to PyTorch. namespace CudaCodeGen {
```

@jeffdaily @pruthvistony

### LINKED ISSUE #77237: DISABLED test_broadcast_in_dim_cuda_float32 (__main__.TestPrimsCUDA)
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_broadcast_in_dim_cuda_float32%2C%20TestPrimsCUDA)).

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @mruberry

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes https://github.com/pytorch/pytorch/issues/77237

### CODE REVIEW

**Comment by davidberard98** [comment]
@jjsjann123 can you change the PR message to "Fixes #77237" and restart the "pull" CI job?

I think otherwise, the relevant test will still be skipped in CI. 77237 is the issue that's disabling that test

**Comment by jjsjann123** [comment]
No idea how to restart tests any more... bot seems to be ignoring me :cry: 
Just did a nother push and hopefully this is enough.

**Comment by jjsjann123** [comment]
Looks like it's working.

The log in `linux-bionic-rocm5.1-py3.7` changed from
`2022-05-16T15:20:45.9402014Z   test_broadcast_in_dim_cuda_float32 (__main__.TestPrimsCUDA) ... skip: Test is disabled because an issue exists disabling it: https://github.com/pytorch/pytorch/issues/77237 for platform(s) rocm. If you're seeing this on your local machine and would like to enable this test, please make sure IN_CI is not set and you are not using the flag --import-disabled-tests. (0.003s)`

to
`2022-05-14T01:49:55.2927858Z   test_broadcast_in_dim_cuda_float32 (__main__.TestPrimsCUDA) ... skip: test doesn't currently work on the ROCm stack (0.107s)`

**Review by davidberard98 — APPROVED** [review]
LGTM!

**Pull request closed without merging**
