### PR TITLE
[RPC Framework] Clang-format remote_module.py and instantiator.py

### PR DESCRIPTION
**Pull request by wayi1**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#57414 [RPC Framework] Clang-format remote_module.py and instantiator.py**
* #57413 [RPC Framework] Create a separate remote module template when moving CPU tensors to a cuda device is not enabled

Differential Revision: [D28138870](https://our.internmc.facebook.com/intern/diff/D28138870/)

### CODE REVIEW

**Comment by leslie-fang-intel** [comment]
I see one UT fails with the message:
```
2021-05-01T15:42:26.8544527Z [E request_callback_no_python.cpp:668] Received error while processing request type 256: The following operation failed in the TorchScript interpreter.
2021-05-01T15:42:26.8545612Z Traceback of TorchScript (most recent call last):
2021-05-01T15:42:26.8546557Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 340, in raise_func_script
2021-05-01T15:42:26.8547232Z @torch.jit.script
2021-05-01T15:42:26.8547812Z def raise_func_script(expected_err: str) -> torch.Tensor:
2021-05-01T15:42:26.8548332Z     raise ValueError(expected_err)
2021-05-01T15:42:26.8548800Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
2021-05-01T15:42:26.8549191Z RuntimeError: Expected error
```
Will this PR fix it?

**Comment by SciPioneer** [comment]
> I see one UT fails with the message:
> 
> ```
> 2021-05-01T15:42:26.8544527Z [E request_callback_no_python.cpp:668] Received error while processing request type 256: The following operation failed in the TorchScript interpreter.
> 2021-05-01T15:42:26.8545612Z Traceback of TorchScript (most recent call last):
> 2021-05-01T15:42:26.8546557Z   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 340, in raise_func_script
> 2021-05-01T15:42:26.8547232Z @torch.jit.script
> 2021-05-01T15:42:26.8547812Z def raise_func_script(expected_err: str) -> torch.Tensor:
> 2021-05-01T15:42:26.8548332Z     raise ValueError(expected_err)
> 2021-05-01T15:42:26.8548800Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
> 2021-05-01T15:42:26.8549191Z RuntimeError: Expected error
> ```
> 
> Will this PR fix it?

Thanks for pointing to this! Is this failure triggered by this PR or a pre-existing failure? This PR only does some reformatting. Let me try rebasing first.

**Comment by leslie-fang-intel** [comment]
Hi @SciPioneer, I see this failure when I do rebase yesterday. And this PR https://github.com/pytorch/pytorch/pull/57288 seems is the only one with RPC and between my 2 rebase. Will this failure relate with the other PR https://github.com/pytorch/pytorch/pull/57413 in this same ghstack?

**Comment by SciPioneer** [comment]
> Hi @SciPioneer, sorry for the confusion. I see this failure when I do rebase yesterday in my PR but not this one(I didn't change any thing relate with RPC in my PR). And this PR #57288 seems is the only one relate with RPC and between my 2 rebase. Will the other PR #57413 in this same ghstack resolve my UT failure possibly?



> Hi @SciPioneer, sorry for the confusion. I see this failure when I do rebase yesterday in my PR but not this one(I didn't change any thing relate with RPC in my PR). And this PR #57288 seems is the only one relate with RPC and between my 2 rebase. Will the other PR #57413 in this same ghstack resolve my UT failure possibly?

I didn't see a failure in https://github.com/pytorch/pytorch/pull/57413

I am about to submit that PR. Let's see if the same test will fail there:
https://app.circleci.com/pipelines/github/pytorch/pytorch/315213/workflows/702f7c2f-27ab-46ae-8b64-d2c16cd2d554/jobs/13110091

**Comment by SciPioneer** [comment]
> Hi @SciPioneer, sorry for the confusion. I see this failure when I do rebase yesterday in my PR but not this one(I didn't change any thing relate with RPC in my PR). And this PR #57288 seems is the only one relate with RPC and between my 2 rebase. Will the other PR #57413 in this same ghstack resolve my UT failure possibly?

I checked the test failure, which is irrelevant to this PR:


It is introduced by this PR: https://github.com/pytorch/pytorch/pull/57328

**Review by rohan-varma — APPROVED** [review]

**Comment by leslie-fang-intel** [comment]
> > Hi @SciPioneer, sorry for the confusion. I see this failure when I do rebase yesterday in my PR but not this one(I didn't change any thing relate with RPC in my PR). And this PR #57288 seems is the only one relate with RPC and between my 2 rebase. Will the other PR #57413 in this same ghstack resolve my UT failure possibly?
> 
> I checked the test failure, which is irrelevant to this PR:
> image
> 
> It is introduced by this PR: #57328

Thanks @SciPioneer I will rebase the master and try again.

**Pull request closed without merging**
