### PR TITLE
Add support for dynamic kwarg to torch._dynamo.optimize

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89290

This is an easier way to enable dynamic shapes for a region.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by soumith — APPROVED** [review]
shipit

**Review by jansel — APPROVED** [review]

**Comment by voznesenskym** [comment]
There's a place in our symbolic shapes branch where we sniff args in a signature for a calling convention before we have this. Let's remember to change it.

**Review by voznesenskym — APPROVED** [review]

**Comment by ezyang** [comment]
@voznesenskym wait, surely we aren't sniffing optimize?

**Pull request closed without merging**
