### PR TITLE
Remove cpp_custom_type_hack

### LINKED ISSUE #72263: Removing deprecated `cpp_custom_type_hack`
## Context
`at::cpp_custom_type_hack` is a deprecated utility to shepherd arbitrary C++ classes through Python by embedding an owning pointer inside a byte Tensor's storage. It's usage is already heavily discouraged:

https://github.com/pytorch/pytorch/blob/2291981eeae58d1c1bc00fff208abb0ccb0712db/aten/src/ATen/cpp_custom_type_hack.h#L18-L20

`torch/custom_class.h` is now the preferred way to expose C++ classes to Python, however the current uses may be serialized into existing `TorchScript` models so these operators must be changed with forward and backward compatibility in mind.

## Relevant operators

- [ ] `aten::quantized_gru.input_legacy`
- [ ] `aten::quantized_gru.data_legacy`
- [ ] `aten::quantized_lstm.input_legacy`
- [ ] `aten::quantized_lstm.data_legacy`
- [ ] `aten::fbgemm_linear_int8_weight_fp32_activation`
- [ ] `aten::fbgemm_pack_quantized_matrix`
- [ ] `aten::fbgemm_pack_gemm_matrix_fp16`
- [ ] `aten::fbgemm_linear_fp16_weight_fp32_activation`

- [ ] `quantized::linear_prepack_legacy`
- [ ] `quantized::linear_prepack_fp16_legacy`
- [ ] `_quantized::linear_prepack_fp16_legacy`

- [ ] `profiler::_record_function_enter` (see #35026)
- [ ] `profiler::_record_function_exit` (see #35026)

cc @albanD @malfet

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104569
* #118526
* #72303
* #112153

Closes #72263

### CODE REVIEW

**Review by kimishpatel — CHANGES_REQUESTED** [review]
This one is going to require some internal changes before we can truly remove this hack, so I am gonna have to put this back in your queue for now. Lets follow up.

**Comment by albanD** [comment]
Note that other people have expressed interest in this to be able to pass in arbitrary types through the c++ dispatcher. So we might not want to remove it at all. But if we do this, we should add test to make sure it keeps working going forward.

@kimishpatel do you know how this is used internally? Any test we should have on this?

**Comment by kimishpatel** [comment]
> Note that other people have expressed interest in this to be able to pass in arbitrary types through the c++ dispatcher. So we might not want to remove it at all. But if we do this, we should add test to make sure it keeps working going forward.

Lol. hacks that live forever.

> 
Note that other people have expressed interest in this to be able to pass in arbitrary types through the c++ dispatcher. So we might not want to remove it at all. But if we do this, we should add test to make sure it keeps working going forward.

> @kimishpatel do you know how this is used internally? Any test we should have on this?

Yeah, but i only of the instance that i added. lol. If we decided to remove this then this will require good chunk of work though

**Comment by peterbell10** [comment]
> Note that other people have expressed interest in this to be able to pass in arbitrary types through the c++ dispatcher. 

Isn't this what torchbind is for, or do they require completely arbitrary types with no torchbind wrapper?

> If we decided to remove this then this will require good chunk of work though

Can we at least remove it from open source?

**Comment by albanD** [comment]
Do you have some doc/intro about torchbind you know of? What is the difference with this?

**Comment by peterbell10** [comment]
torchbind allows you to have a custom class in the signature of an operator,

https://pytorch.org/tutorials/advanced/torch_script_custom_classes.html?highlight=registeroperators

For example, it's used in the profiler to martial "RecordFunction" objects 
https://github.com/pytorch/pytorch/blob/3b9246ba1823bd5f10335706b98f057dac4f72c2/torch/csrc/autograd/record_function_ops.cpp#L135-L138

**Comment by albanD** [comment]
But that won't work for python objects right?

**Comment by peterbell10** [comment]
I don't know what use case you have in mind but you should be able to create a C++ class that holds a generic `PyObject*` and so be able to hold any arbitrary python object.

**Comment by lezcano** [comment]
@albanD so what's the state of this?

**Comment by albanD** [comment]
I think there are a couple things:
- All the PRs below require quite a bit of fixing for internal code that relies on them
- It is unclear what's the way to go without this if you need to pipe a class through the dispatcher today (cc @zou3519 )
- It is unclear what's the gain of removing all of these (like what's the ROI for all this work?)

**Comment by kimishpatel** [comment]
> It is unclear what's the gain of removing all of these (like what's the ROI for all this work?)

Yeah it will be good to highlight this

**Comment by peterbell10** [comment]
> It is unclear what's the way to go without this if you need to pipe a class through the dispatcher today 

I don't understand what's wrong with torchbind custom classes?

Anyway, @albanD if you don't think it's worth doing then we can just abandon this. After all, it was you that asked me to clean it up in the first place.

**Comment by albanD** [comment]
> I don't understand what's wrong with torchbind custom classes?

I will let @zou3519 answer on this one. My understanding is that it doesn't work with a bunch of things.

> Anyway, albanD if you don't think it's worth doing then we can just abandon this. After all, it was you that asked me to clean it up in the first place.

Yes I think it might be best to abandon this one :(  Sorry for the back and forth, I didn't expect it was used that much.

**Comment by zou3519** [comment]
torchbind doesn't work with PT2 yet (we're working on it). But we're also not telling people to use cpp_custom_type_hack as a workaround.

**Pull request closed without merging**
