### PR TITLE
Make fusion strategy api public

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #72639
* #72638
* #72616

Differential Revision: [D34159123](https://our.internmc.facebook.com/intern/diff/D34159123)

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]
LGTM!

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34159123).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34159123).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34159123).

**Pull request closed without merging**
