### PR TITLE
use spawn as default start method to create dataloader subprocess

### LINKED ISSUE #130610: dataloader hangs with fork and pin memory=True
### 🚀 The feature, motivation and pitch

I train my model on DDP when num_workers>0, pin_memory=True and multiple dataloaders(train, valid, test). There is a small chance to hang that dataloader can not load data.  The reason is on Ubuntu，fork will be used to start num worker subprocess by default and it will cause potential deadlock with pin_memory_thread.

For pin_memory_thread, it will call torch.set_num_threads(1), it will acquire lock in __GI___cxa_atexit, if it locks and another dataloader fork num_worker process, it may cause potential deadlock. I set multiprocessing_context='spawn'
can solve the hang.

So can we change default value of multiprocessing_context to spawn? I think spawn is more safe.

```
(gdb) bt 
#0  __internal_atexit (listp=0x7fab466f6838 <__exit_funcs>, d=0x7fab43f9bf00, arg=0x7fab4430fd60 <caffe2::pthreadpool()::threadpool>, 
    func=0x7fab32724da0 <std::unique_ptr<caffe2::PThreadPool, std::default_delete<caffe2::PThreadPool> >::~unique_ptr()>) at ./stdlib/cxa_atexit.c:41
#1  __GI___cxa_atexit (func=0x7fab32724da0 <std::unique_ptr<caffe2::PThreadPool, std::default_delete<caffe2::PThreadPool> >::~unique_ptr()>, arg=0x7fab4430fd60 <caffe2::pthreadpool()::threadpool>, 
    d=0x7fab43f9bf00) at ./stdlib/cxa_atexit.c:70
#2  0x00007fab32724c6e in caffe2::pthreadpool() () from /tmp/cair_modelzoo_megatron_llama2_7b_pretrain_0_0/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so
#3  0x00007fab302757f7 in at::set_num_threads(int) () from /tmp/cair_modelzoo_megatron_llama2_7b_pretrain_0_0/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so
#4  0x00007fab44a40ada in THPModule_setNumThreads(_object*, _object*) () from /tmp/cair_modelzoo_megatron_llama2_7b_pretrain_0_0/lib/python3.10/site-packages/torch/lib/libtorch_python.so
```

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by HarryZJ**
Fixes #130610

This PR is intended to address the issue #130610 encountered: When the main process forks the dataloader subprocess, it just so happens that other threads (in this issue, it's the pin memory thread) are accessing certain global locks, leading to incorrect states of these global locks in the subprocess and resulting in a deadlock.

The approach I've chosen to solve this kind of problem is: By default, use spawn instead of fork to create the dataloader process. The worker_init_fn parameter must be pickable， _check_unpickable_fn has been added.

The reasons for selecting this solution are as follows:
1. Once a deadlock occurs, it is challenging for algorithm engineers to debug.
2. Compared to potential deadlock issues, the restriction on the worker_init_fn parameter can expose the problem earlier and alert users, which is more in line with the design philosophy of PyTorch.
3. In Python 3.14 version, the default start method will change away from fork .

cc @SimonWang @VitalyFedyunin @AdamPaszke @EdwardYang

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
This is very BC-breaking. Not sure if we want to go down that path.

**Comment by damian0815** [comment]
there is a long standing issue i've seen across various training methods where `num_workers>0` is more or less likely to freeze at some point randomly during training. i can't find an obvious issue for it, though. will this likely/possibly fix this, or is this PR addressing a hang on init?

**Review by andrewkho — CHANGES_REQUESTED** [review]
This will break backwards compatibility and behaviour for existing users

**Comment by HarryZJ** [comment]
> 3\. In Python 3.14 version, the default start method will change away from fork .

**Comment by HarryZJ** [comment]
> This will break backwards compatibility and behaviour for existing users

As I mentioned at the very beginning, in version 3.14 of Python, the default start method will change away from fork , At that time, backward compatibility will still be broken.

**Comment by HarryZJ** [comment]
> there is a long standing issue i've seen across various training methods where a dataloader insantiated with `num_workers>0` is more or less likely to freeze at some point randomly during training (the likelihood appears to increase as `num_workers` increases). i can't find an obvious issue for it, though. will this likely/possibly fix this, or is this PR addressing a hang on init?

If the hang problem you encounter is caused by abnormal states of certain global locks during forking, then this PR may help you solve the problem.

**Pull request closed without merging**
