### PR TITLE
[primtorch] Draft: Adding addbmm prim

### PR DESCRIPTION
**Pull request by zaxtax**
This is a first attempt to add the `addbmm` primitive

### CODE REVIEW

**Comment by zaxtax** [comment]
@Lezcano

**Review by lezcano — COMMENTED** [review]
Do we want to make this a prim, or do we want to make regular `bmm` a prim and make this one a composite?  In JAX [they go the composite way](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.batch_matmul.html#jax.lax.batch_matmul) and I think it should be like that, but I'll let @ngimel assess this one.

**Comment by zaxtax** [comment]
That's one thing I'm uncertain about. The other is how to make this mypy lintrunner error go away.

**Comment by ngimel** [comment]
`addbmm` is a rarely used op that's implemented as composite in the core, so I think it should be ref, not prim.

**Comment by zaxtax** [comment]
@ngimel yep that makes sense!

**Comment by Lezcano** [comment]
This should be written in terms of `bmm`. We need to design these first.

**Pull request closed without merging**
