### PR TITLE
update pybind11 to v2.6.0

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #42944 [WIP][c10d][jit] torchbind ProcessGroup
* #44044 [torchbind] add static define for C++ method
* #44046 [c10d] switch ProcessGroup::Work to be managed by intrusive_ptr
* #44492 [c10] make intrusive_ptr available as a pybind holder type
* **#46687 update pybind11 to v2.6.0**

This PR updates pybind11 to v2.6.0 to include the fixes that remove friend declaration of py::class_ in py::detail::generic_type in https://github.com/pybind/pybind11/pull/2613, which is causing compilation bug using MSVC when we try to friend the py::class_ in intrusive_ptr

### CODE REVIEW

**Comment by ezyang** [comment]
cc @henryiii

**Comment by ezyang** [comment]
The macros here seem questionable. In particular, it seems to me like the wrong thing will happen for any external user who uses our Python headers and doesn't remember to also set these macros?

**Comment by henryiii** [comment]
PS: This has nothing to do with Apple; it's just when you mix LLVM and GCC. I think the JIT compiler is GCC on Linux even when the host compiler was GCC. If these always matched, then nothing would need to be done.

**Review by ezyang — CHANGES_REQUESTED** [review]
blocking PR

**Comment by wanchaol** [comment]
@ezyang @henryiii Thanks for reviewing and providing insights on this. I synced offline with @malfet and decided to let him take over this and figure out the build/macros issue in https://github.com/pytorch/pytorch/pull/46415. Closing this.

**Pull request closed without merging**
