### PR TITLE
Remove CUB submodule

### LINKED ISSUE #125981: Cub submodule still pointing to a deprecated repo
### 🐛 Describe the bug

CUB submodule is pointing to a deprecated repo.
Can we point to https://github.com/NVIDIA/cccl/ ?

### Versions

Main

cc @ptrblck @msaroufim

### PR DESCRIPTION
**Pull request by shink**
Fixes #125981

The [NVlabs/cub][1] isn't used anymore, so it's removed in this pull request.

[1]: https://github.com/NVlabs/cub

### CODE REVIEW

**Comment by shink** [comment]
there's still some work to do, convert to a draft temporarily.

**Comment by Skylion007** [comment]
This whole submodule isn't used anymore and can probably just be removed. (We use the version bundled with CUDA I believe).

**Comment by shink** [comment]
@Skylion007 Thanks for your guidance! I'm on it. :p

**Comment by shink** [comment]
@Skylion007 @bhack I removed cub submodule, and it was installed successfully from source by running `python setup.py develop`. What should I do to further test the change?

**Comment by bhack** [comment]
We could kick-off the CI jobs suite.

**Comment by Skylion007** [comment]
You also need to remove the conditional in the cmake files that tries to load the CUB sub module if the system level on cannot be found.

**Comment by bhack** [comment]
> You also need to remove the conditional in the cmake files that tries to load the CUB sub module if the system level on cannot be found.

Do we still have this logic?

**Comment by shink** [comment]
fixed by #126540

**Pull request closed without merging**
