### PR TITLE
Add return_counts to torch.unique

### LINKED ISSUE #12598: Add `return_counts` to `torch.unique`
## 🚀 Feature
The current implementation of `torch.unique` does not have a `return_counts` argument, which returns the counts of all unique occurrences in the tensor.

## Motivation

The feature request is related to some users missing this option, e.g. [this thread](https://discuss.pytorch.org/t/how-to-efficiently-perform-averaging-across-predefined-groups-in-a-tensor/27091/2?u=ptrblck). A current workaround is to use something like this:
```
x = torch.tensor([1, 2, 2, 2, 3])
x_unique = x.unique(sorted=True)
x_unique_count = torch.stack([(x==x_u).sum() for x_u in x_unique])
```

Also, numpy supports this option, which should be a nice to have for new users. [np.unique](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.unique.html)
As this might be added as the last argument, no breaking changes would occur.

## Pitch

I could add this option to the current `torch.unique` implementation as I've recently added the `return_inverse` option and am still familiar with the code.

## Alternatives

An alternative would be to use the hacky code from above.

Let me know, if that sound good to you!
Also a bit unrelated, but we could also add the `return_index` option together to match the numpy function as close as possible, but that's probably another feature request.

Best,
ptrblck

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fixes: https://github.com/pytorch/pytorch/issues/12598

This PR was originally authorized by @ptrblck at https://github.com/pytorch/pytorch/pull/15495, but since there was no update for months after the request change, I clone that branch and resolve the code reviews here. Hope everything is good now. Especially, the implementation of count is changed from @ptrblck's original algorithm to the one @ngimel suggest, i.e. using `unique_by_key` and `adjacent_difference`.

The currently implementation of `_unique_dim` is VERY slow for computing inverse index and counts, see https://github.com/pytorch/pytorch/issues/18405. I will refactor `_unique_dim` in a later PR. For this PR, please allow me to keep the implementation as is.

cc: @ptrblck @ezyang @ngimel @colesbury

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
lgtm

**Review by soumith — APPROVED** [review]

**Comment by ptrblck** [comment]
@zasdfgbnm Thanks for taking over this PR! I was quite busy in the last couple of weeks and really appreciate it. ;)

**Comment by soumith** [comment]
hey @zasdfgbnm . I am reverting this PR temporarily due to an internal stress-test failing.
The stress-test failure is not related to this PR but is related to how this PR introduces variable number of return values based on the return_counts boolean flag.
So there's no action needed from you further, the same PR will go in with a patch to contrib/aten_op to handle this

**Comment by zasdfgbnm** [comment]
@soumith Feel free to do so.

**Pull request closed without merging**
