### PR TITLE
Port other comparison ops: `ne`, `lt`, `gt`, `le`, `ge` to structured kernels.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#60942 Port other comparison ops: `ne`, `lt`, `gt`, `le`, `ge` to structured kernels.**
* #60177 Port `eq` kernel to structured kernels.

Tracking Issue: #55070

This PR applies the same transformation of `eq` to the other comparison ops: `ne`, `lt`,
`gt`, `le`, and `ge`. Macros for crating meta and impl functions are used (since the
checks they have are the same).

Differential Revision: [D29509868](https://our.internmc.facebook.com/intern/diff/D29509868)

### CODE REVIEW

**Comment by ysiraichi** [comment]
The 3 CI failures don't seem related to this PR.

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29509868).

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29509868).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29509868).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29509868).

**Pull request closed without merging**
