### PR TITLE
Update functional_bfloat16.h

### PR DESCRIPTION
**Pull request by co63oc**
Fix a typo in functional_bfloat16.h

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]
Before merging all these typo fixes, could you please add a better commit message to the PR descriptions.

**Comment by co63oc** [comment]
The commit message is updated

**Review by jgong5 — APPROVED** [review]

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
