### PR TITLE
Updates NCCL to 2.18.1

### PR DESCRIPTION
**Pull request by syed-ahmed**
This PR updates NCCL submodule to 2.18.1.

### CODE REVIEW

**Comment by syed-ahmed** [comment]
@kwen2501 This is ready for review. The failing tests don't seem related.

**Comment by syed-ahmed** [comment]
@kwen2501 can we get this approved?

**Review by kwen2501 — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Please note, that compilation filers while building libtorch are real (by likely fixable by updating this container to use gcc-9 instead of gcc-7)

**Review by atalman — APPROVED** [review]

**Comment by atalman** [comment]
@syed-ahmed  can you please rebase this PR ? I think trunk jobs are using gcc9 now: libtorch-linux-bionic-cuda11.8-py3.7-gcc9, the error you are seing now is probably resolved

**Pull request closed without merging**
