### PR TITLE
verify input sizes for instance norm and group norm

### PR DESCRIPTION
**Pull request by v0dro**
Fix for https://github.com/pytorch/pytorch/issues/19250

### CODE REVIEW

**Comment by ezyang** [comment]
Test?

**Review by ezyang — APPROVED** [review]
Code change looks good, but I'd like a test, or at least a written statement that you tried the code by hand and got the desired result.

**Comment by v0dro** [comment]
@ezyang here's the output for some code samples:

```
>>> import torch
>>> x = torch.rand(10)[None,:,None]
>>> print(torch.nn.InstanceNorm1d(10)(x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sameer/gitrepos/pytorch/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sameer/gitrepos/pytorch/torch/nn/modules/instancenorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/home/sameer/gitrepos/pytorch/torch/nn/functional.py", line 1684, in instance_norm
    _verify_batch_size(input.size())
  File "/home/sameer/gitrepos/pytorch/torch/nn/functional.py", line 1656, in _verify_batch_size
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 10, 1])
```

```
>>> print(torch.nn.GroupNorm(10,10)(x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sameer/gitrepos/pytorch/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sameer/gitrepos/pytorch/torch/nn/modules/normalization.py", line 226, in forward
    input, self.num_groups, self.weight, self.bias, self.eps)
  File "/home/sameer/gitrepos/pytorch/torch/nn/functional.py", line 1707, in group_norm
    _verify_batch_size(input.size())
  File "/home/sameer/gitrepos/pytorch/torch/nn/functional.py", line 1656, in _verify_batch_size
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 10, 1])
```

```
print(torch.nn.BatchNorm1d(10)(x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sameer/gitrepos/pytorch/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sameer/gitrepos/pytorch/torch/nn/modules/batchnorm.py", line 79, in forward
    exponential_average_factor, self.eps)
  File "/home/sameer/gitrepos/pytorch/torch/nn/functional.py", line 1667, in batch_norm
    _verify_batch_size(input.size())
  File "/home/sameer/gitrepos/pytorch/torch/nn/functional.py", line 1656, in _verify_batch_size
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 10, 1])
```

**Comment by ezyang** [comment]
tests failing

```

Nov 10 03:13:53 ======================================================================
Nov 10 03:13:53 ERROR: test_instancenorm_raises_error_if_less_than_one_value_per_channel_cuda (__main__.TestNNDeviceTypeCUDA)
Nov 10 03:13:53 ----------------------------------------------------------------------
Nov 10 03:13:53 Traceback (most recent call last):
Nov 10 03:13:53   File "/var/lib/jenkins/workspace/test/common_utils.py", line 562, in wrapper
Nov 10 03:13:53     method(*args, **kwargs)
Nov 10 03:13:53   File "/var/lib/jenkins/workspace/test/common_utils.py", line 562, in wrapper
Nov 10 03:13:53     method(*args, **kwargs)
Nov 10 03:13:53   File "/var/lib/jenkins/workspace/test/common_device_type.py", line 179, in instantiated_test
Nov 10 03:13:53     return test(self, device_arg)
Nov 10 03:13:53 TypeError: test_instancenorm_raises_error_if_less_than_one_value_per_channel() takes 1 positional argument but 2 were given
Nov 10 03:13:53 
Nov 10 03:13:53 ----------------------------------------------------------------------
```

**Comment by v0dro** [comment]
@ezyang adding the check to instance norm is leading to a failure in a different test. Please advise on whether to change the failing test or instance norm.
```
Nov 30 02:55:46 ......................................................................................................................................................................................................................................................................................................................ss..s.ss.ss.ss...s........s.
Nov 30 02:55:46 ======================================================================
Nov 30 02:55:46 ERROR [0.003s]: test_inplace_view_backward (__main__.TestAutograd)
Nov 30 02:55:46 ----------------------------------------------------------------------
Nov 30 02:55:46 Traceback (most recent call last):
Nov 30 02:55:46   File "test_autograd.py", line 2946, in test_inplace_view_backward
Nov 30 02:55:46     g, = torch.autograd.grad(net(x).pow(2), [x], create_graph=True)
Nov 30 02:55:46   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
Nov 30 02:55:46     result = self.forward(*input, **kwargs)
Nov 30 02:55:46   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
Nov 30 02:55:46     input = module(input)
Nov 30 02:55:46   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
Nov 30 02:55:46     result = self.forward(*input, **kwargs)
Nov 30 02:55:46   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/instancenorm.py", line 49, in forward
Nov 30 02:55:46     self.training or not self.track_running_stats, self.momentum, self.eps)
Nov 30 02:55:46   File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1684, in instance_norm
Nov 30 02:55:46     _verify_batch_size(input.size())
Nov 30 02:55:46   File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1656, in _verify_batch_size
Nov 30 02:55:46     raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
Nov 30 02:55:46 ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 1, 1, 1])
Nov 30 02:55:46 
Nov 30 02:55:47 ----------------------------------------------------------------------
```

**Comment by ezyang** [comment]
This sounds like a badly written test to me. Just increase the test size to 2.

**Comment by ezyang** [comment]
Not for this PR, but it might be nice if InstanceNorm2d module immediately raised an error if you constructed it with too few features

**Comment by ezyang** [comment]
YOu still have test problems:

```
Dec 06 04:41:09 ======================================================================
Dec 06 04:41:09 ERROR [0.002s]: test_inplace_view_backward (__main__.TestAutograd)
Dec 06 04:41:09 ----------------------------------------------------------------------
Dec 06 04:41:09 Traceback (most recent call last):
Dec 06 04:41:09   File "test_autograd.py", line 2946, in test_inplace_view_backward
Dec 06 04:41:09     g, = torch.autograd.grad(net(x).pow(2), [x], create_graph=True)
Dec 06 04:41:09   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 150, in grad
Dec 06 04:41:09     grad_outputs = _make_grads(outputs, grad_outputs)
Dec 06 04:41:09   File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 34, in _make_grads
Dec 06 04:41:09     raise RuntimeError("grad can be implicitly created only for scalar outputs")
Dec 06 04:41:09 RuntimeError: grad can be implicitly created only for scalar outputs
```

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 7bd13154:


* **2/2** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=7bd1315457ca378bcd8d073827c889588972297c).

### :detective: 2 new failures recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4085328) pytorch_linux_xenial_py3_6_gcc5_4_build (1/2)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=78766254) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=78766254))
<details>
<summary>
<code>Automatic merge failed; fix conflicts and then commit the result.</code>
</summary>

```
CONFLICT (add/add): Merge conflict in .circleci/docker/common/install_cmake.sh 
Auto-merging .circleci/docker/common/install_cmake.sh 
CONFLICT (add/add): Merge conflict in .circleci/docker/common/install_cache.sh 
Auto-merging .circleci/docker/common/install_cache.sh 
CONFLICT (add/add): Merge conflict in .circleci/docker/common/install_android.sh 
Auto-merging .circleci/docker/common/install_android.sh 
CONFLICT (add/add): Merge conflict in .circleci/docker/build.sh 
Auto-merging .circleci/docker/build.sh 
CONFLICT (add/add): Merge conflict in .circleci/config.yml 
Auto-merging .circleci/config.yml 
Automatic merge failed; fix conflicts and then commit the result. 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4085334) pytorch_xla_linux_xenial_py3_6_clang7_build (2/2)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=78766283) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=78766283))
<details>
<summary>
<code>Dec 30 09:51:36 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-serialization.diff</code>
</summary>

```
Dec 30 09:51:36 + python /var/lib/jenkins/workspace/xla/scripts/cond_patch.py /var/lib/jenkins/workspace/xla/scripts/../torch_patches /var/lib/jenkins/workspace/xla/scripts/../.. 
Dec 30 09:51:36 1 out of 1 hunk FAILED 
Dec 30 09:51:36 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-clip_grad.diff 
Dec 30 09:51:36 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff 
Dec 30 09:51:36 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-serialization.diff 
Dec 30 09:51:36 Traceback (most recent call last): 
Dec 30 09:51:36   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 67, in <module> 
Dec 30 09:51:36     patch_repo(args) 
Dec 30 09:51:36   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 49, in patch_repo 
Dec 30 09:51:36     raise RuntimeError('Failed to apply patch: {}'.format(ppath)) 
Dec 30 09:51:36 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-serialization.diff 
Dec 30 09:51:36 + cleanup 
Dec 30 09:51:36 + retcode=1 
Dec 30 09:51:36 + set +x 
Dec 30 09:51:36 =================== sccache compilation log =================== 
Dec 30 09:51:36 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 30 09:51:36 Compile requests                 1 
Dec 30 09:51:36 Compile requests executed        0 
Dec 30 09:51:36 Cache hits                       0 
Dec 30 09:51:36 Cache misses                     0 
Dec 30 09:51:36 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by v0dro** [comment]
I think the test failure has been resolved with the latest commit. CC @rgommers

**Review by ezyang — CHANGES_REQUESTED** [review]
revoking approval on account of test failures

**Comment by v0dro** [comment]
@ezyang the error that I'm getting is like so:
```
RuntimeError: 

_verify_batch_size(Tensor size) -> (None):
Expected a value of type 'Tensor' for argument 'size' but instead found type 'List[int]'.
Inferred 'size' to be of type 'Tensor' because it was not annotated with an explicit type.
:
  File "C:\Users\circleci\project\build\win_tmp\build\torch\nn\functional.py", line 1674
    """
    if training:
        _verify_batch_size(input.size())
        ~~~~~~~~~~~~~~~~~~ <--- HERE

    return torch.batch_norm(
'batch_norm' is being compiled since it was called from 'BatchNorm2d.forward'
  File "C:\Users\circleci\project\build\win_tmp\build\torch\nn\modules\batchnorm.py", line 104
                    exponential_average_factor = self.momentum

        return F.batch_norm(
               ~~~~~~~~~~~~~...  <--- HERE
            input, self.running_mean, self.running_var, self.weight, self.bias,
            self.training or not self.track_running_stats,
```

Which is very strange considering that you should not need to specify types in Python.

Can you please tell me how exactly to specify to the JIT that `_verify_*` method needs to accept a list of ints?

**Comment by v0dro** [comment]
@ezyang please review again. Passing now.

**Review by ezyang — APPROVED** [review]
Great, thanks

**Comment by ezyang** [comment]
you still have lint failures

**Comment by v0dro** [comment]
Lint is passing and the rest are failing for no fault from my side.

**Comment by v0dro** [comment]
Can we merge this?

**Comment by rgommers** [comment]
> Can we merge this?

@v0dro it's already imported, which means the Facebook-internal CI is being run and the merge is in progress. Nothing to do here.

**Pull request closed without merging**
