### PR TITLE
Type aliases

### PR DESCRIPTION
**Pull request by dsm-72**
This doesn't fix any particular issue per se....
However it does add more `TypeAlias`es for those who might prefer to use them to clarify function and class arguments.

### CODE REVIEW

**Comment by dsm-72** [comment]
Somewhat related https://github.com/pytorch/pytorch/issues/97026 as one can use `typing.get_args` to get all valid devices

**Comment by janeyx99** [comment]
Hey! Thanks for the PR. In isolation, the impact here is unclear. We'd prefer reviewing in an issue the proposed idea, motivation, and implementation, so could you open an issue with those details regarding this change? cc @malfet

**Comment by janeyx99** [comment]
Also, you probably would want to extract out the changes from https://github.com/pytorch/pytorch/pull/102917

**Pull request closed without merging**
