### PR TITLE
Reland: Add index value checking to MaxUnpool2d and MaxUnpool3d

### PR DESCRIPTION
**Pull request by kurtamohler**
Relanding #70545

### CODE REVIEW

**Comment by kurtamohler** [comment]
So in the CI job `pytorch-xla-linux-bionic-py3.7-clang8 / test (xla, 1, 1, linux.2xlarge)`, the subprocess `stderr` is blank for some reason when it should have an index error. The other CI jobs and my local environment do produce the error. So either the error is not being produced at all in this CI job for some reason, or the error is being produced but it's not getting written to the subprocess `stderr` for some reason.

Perhaps the error is getting written to `stdout` instead. So I made a change to search both `stdout` and `stderr` for the error message. Hopefully that works. If not, this is probably going to be hard to debug.

Is there a way to ssh into the github actions job while it's running? I know there used to be a way when we used CircleCI

**Comment by kurtamohler** [comment]
The error didn't show up in `stdout` for the failing jobs. I guess the error probably isn't getting raised at all for some reason. Maybe there's another implementation of `MaxUnpool2d/3d` that is conditionally run in some environments. I'll look for that

**Comment by kurtamohler** [comment]
Alright, I was pointed to the info I needed to be able to ssh into an actions job, so I'll be able to debug properly this soon

**Comment by kurtamohler** [comment]
I think (but not sure) that the `with-ssh` label might be overriding the `ciflow/all` label, so the jobs that I need to debug aren't showing up

**Comment by kurtamohler** [comment]
I saw that `ciflow/all`'s description says it's deprecated, and that `ciflow/trunk` and `ciflow/periodic` should be used instead. So I'm trying that

**Comment by kurtamohler** [comment]
For some reason I can't connect through ssh

```
$ ssh ec2-user@ec2-35-153-16-148.compute-1.amazonaws.com
ssh: connect to host ec2-35-153-16-148.compute-1.amazonaws.com port 22: Connection timed out
```

I have my public keys set up correctly in https://github.com/kurtamohler.keys, so I have no idea what's wrong

**Comment by kurtamohler** [comment]
I figured it out. While logged into the [linux-bionic-cuda10.2-py3.9-gcc7 / test (slow, 1, 1, linux.4xlarge.nvidia.gpu)](https://github.com/pytorch/pytorch/runs/6696143675?check_suite_focus=true#logs) CI job, if I create this script and run it, I don't get any output (no errors, nothing) in the terminal:

<details>
<summary>Click to expand/collapse</summary>

```python
import torch
unpool = torch.nn.MaxUnpool2d((2, 2)).to('cuda')
output = torch.rand((1, 3, 4, 5), dtype=torch.float32, device='cuda')
indices = torch.zeros((1, 3, 4, 5), dtype=torch.int64, device='cuda')
indices.flatten()[0] = -1
unpool(output, indices)
```

</details>

But if I try running this same code in the interactive Python terminal, I do get the error:

<details>
<summary>Click to expand/collapse</summary>

```python
>>> import torch
>>> unpool = torch.nn.MaxUnpool2d((2, 2)).to('cuda')
>>> output = torch.rand((1, 3, 4, 5), dtype=torch.float32, device='cuda')
>>> indices = torch.zeros((1, 3, 4, 5), dtype=torch.int64, device='cuda')
>>> indices.flatten()[0] = -1
>>> unpool(output, indices)
/var/lib/jenkins/workspace/aten/src/ATen/native/cuda/MaxUnpooling.cu:48: max_unpooling2d_forward_kernel: block: [0,0,0], thread: [0,0,0] Assertion `maxind >= 0 && maxind < outputImageSize` failed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/torch/_tensor.py", line 338, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/opt/conda/lib/python3.9/site-packages/torch/_tensor_str.py", line 481, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/opt/conda/lib/python3.9/site-packages/torch/_tensor_str.py", line 447, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/opt/conda/lib/python3.9/site-packages/torch/_tensor_str.py", line 270, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/opt/conda/lib/python3.9/site-packages/torch/_tensor_str.py", line 103, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

</details>

So I was wondering, what is the difference between the non-interactive script and the interactive terminal that would cause them to act differently? The answer is that in the interactive Python terminal, it's trying to print out the result of the `unpool(output, indices)`. So I added a print to the script:

```python
...
res = unpool(output, indices)
print(res)
```

That made the non-interactive script produce the error. I tried adding this to the unit test, and that fixed it! I figured that without the print, the script must be exiting before the CUDA kernel ever even runs. So I also tried just calling `torch.cuda.synchronize()` instead of the print, and that works too. So I will update with the fix shortly

**Comment by kurtamohler** [comment]
Ugh, the ROCm CI job doesn't seem to be setting up an ssh server. At least I don't see it anywhere in the logs

**Comment by kurtamohler** [comment]
Ok so it turns out that on ROCm, `CUDA_KERNEL_ASSERT()` does nothing: https://github.com/pytorch/pytorch/blob/master/c10/macros/Macros.h#L337

Should I figure out how to do the check on ROCm (in other words, avoid the device side assert), or is it alright if ROCm just doesn't perform the check yet?

**Comment by ngimel** [comment]
Hm that's weird, I remember rocm enabled asserts at some point (#49624), cc @jeffdaily 
But in the meantime, it's ok to skip those tests on rocm, and not do checks

**Comment by kurtamohler** [comment]
I'm pretty sure all the remaining failures are upstream, so I think this is good to go

**Comment by jbschlosser** [comment]
CI failures do look spurious, merging

**Review by jbschlosser — APPROVED** [review]

**Pull request closed without merging**
