### PR TITLE
[2/N] Replace exceptions with static_assert(false) in some templates 

### PR DESCRIPTION
**Pull request by cyyever**
Follows #127371

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by eqy — APPROVED** [review]
What's the effect of `&& sizeof(Dtype)`?

**Comment by cyyever** [comment]
> What's the effect of `&& sizeof(Dtype)`?

A trick to let static_assert depend on specific template instantiations.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
