### PR TITLE
Guard on at::Tensor device index

### LINKED ISSUE #91777: torch.compile burns-in device numbers, leading to errors when called with tensors on new device
### 🐛 Describe the bug

🐛 Describe the bug:

If I compile a function, and call it with tensors on one device (e.g. `cuda:2`), then with tensors on another device (`cuda:3`), I get a `RuntimeError: Expected all tensors to be on the same device`.

Repro:
```python
import torch

torch.set_float32_matmul_precision('high')

def gemm(x, y):
    return x @ y

gemm_opt = torch.compile(gemm)

x2 = torch.randn(1024, 1024, device="cuda:2")
y2 = torch.randn(1024, 1024, device="cuda:2")

print(gemm(x2, y2).device)
print(gemm_opt(x2, y2).device)

x3 = x2.to("cuda:3")
y3 = y2.to("cuda:3")
print(gemm(x3, y3).device)
print(gemm_opt(x3, y3).device)
```

Digging into the generated code, we're burning in `device(2)`:
```python
def call(args):
    arg0_1, arg1_1 = args
    args.clear()
    with torch.cuda.device(2):
        buf0 = empty_strided((1024, 1024), (1024, 1), device='cuda', dtype=torch.float32)
        aten.mm.out(arg0_1, arg1_1, out=buf0)
        del arg0_1
        del arg1_1
        return (buf0, )
```

Seems like it should either recompile for a new device, or add some preamble to infer the device from args.

Versions

### Versions

local build from a5f32f89788befb083aa664d7911bafcbf98e3cb

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### PR DESCRIPTION
**Pull request by voznesenskym**
Fixes #91777 

cc @mlazos @soumith @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ezyang** [comment]
We should merge this as is but I feel like it would be better if compiled subgraphs that don't involve DtoD transfers can be device agnostic. Certainly this is no problem for CUDA, nor Triton I assume

**Comment by ngimel** [comment]
It is kind of a problem for triton, because currently it's set up to load compiled code to the current device on the first run, and this logic will need to be refactored if we need to possibly load the code to other devices on subsequent runs, the logic for codegening device guards will also need to be redone, and I'm not quite sure how it should look like. It's also tricky for heterogeneous systems. So, given we don't expect this situation to happen too often I think recompiling is ok.

**Comment by ngimel** [comment]
@voznesenskym is there a test forthcoming or should we land this?

**Comment by ezyang** [comment]
IMO, the most likely situation this would happen is if someone tries to optimize (non-Distributed) DataParallel with torch.compile. I know we tell people not to use DataParallel but honestly with torch.compile its not clear to me the reasoning behind this recommendation still stands. Using PT2 to get single process multi gpu working performantly would be pretty slick.

**Comment by voznesenskym** [comment]
> @voznesenskym is there a test forthcoming or should we land this?

I was torn on it - I had a test but it was ugly and felt like it was testing a bunch of other stuff. I got rejected for some failures, so might as well test.

**Comment by ngimel** [comment]
Why does it have to be ugly? It could be as simple as 
```
def fn(x):
    return x/3

opt_fn = torch.compile(fn)
x=torch.randn(4, device="cuda")
opt_fn(x)
x=torch.randn(4, device="cuda:1")
opt_fn(x)
torch.cuda.synchronize()
```

**Comment by voznesenskym** [comment]
> Why does it have to be ugly? It could be as simple as
> 
> ```
> def fn(x):
>     return x/3
> 
> opt_fn = torch.compile(fn)
> x=torch.randn(4, device="cuda")
> opt_fn(x)
> x=torch.randn(4, device="cuda:1")
> opt_fn(x)
> torch.cuda.synchronize()
> ```

I wanted to assert which guard failed, but I remember I added guard_failure_fn. NVM, it need not be ugly.

**Comment by voznesenskym** [comment]
Uhh annoying - we don't have cuda:0/cuda:1 - getting invalid device errors. Might need to move this to a different suite

**Comment by ngimel** [comment]
Cuda 1/0 needs `@requires_multigpu()` or some similar wrapper, and also to be put in some suite that actually runs in multigpu config.

**Pull request closed without merging**
