### PR TITLE
[memory_viz] Unified viewer

### PR DESCRIPTION
**Pull request by zdevito**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #103565
* #103497
* #103474
* #103384

This replaces the invidual visualization routines in _memory_viz.py with
a single javascript application.

The javascript application can load pickled snapshot dumps directly using
drag/drop, requesting them via fetch, or by embedding them in a webpage.

The _memory_viz.py commands use the embedding approach.
We can also host MemoryViz.js on a webpage to use the drag/drop approach, e.g.
https://zdevito.github.io/assets/viz/
(eventually this should be hosted with the pytorch docs).

All views/multiple cuda devices are supported on one page.

cc @albanD

### CODE REVIEW

**Review by eellison — APPROVED** [review]

**Review by eellison — APPROVED** [review]

**Review by albanD — APPROVED** [review]
Code move were missed. PR is fine

**Pull request closed without merging**
