### PR TITLE
Add type stub for SymInt.rsub

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #138543

Fixes https://github.com/pytorch/pytorch/issues/138478

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by kit1980** [comment]
2.5.1 is an emergency patch release to address known large regressions, moving this to 2.6.0

**Comment by kit1980** [comment]
Verified for release 2.6 that this is present in https://github.com/pytorch/pytorch/blob/v2.6.0-rc9/torch/__init__.py

**Pull request closed without merging**
