### PR TITLE
[ATen] Update pre-compiled header

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #106915
* #106914

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by lezcano — APPROVED** [review]

**Comment by ZainRizvi** [comment]
@pytorchbot -m "reverting the full stack. I missed that the iostream pr was stacked under this one" -c ghfirst

cc: @kit1980

**Comment by kit1980** [comment]
@ZainRizvi do you really need to revert this? If the PR from the bottom of the stack was reverted without conflicts, then it means that this PR doesn't really depend on the previous one.

**Comment by ZainRizvi** [comment]
This PR was causing internal diffs to fail as well, so yeah, it does need to be reverted unfortunately

**Comment by peterbell10** [comment]
Depending on implicit imports for a pre-compiled header is really bad practice, there should ideally be a CI job building without PCH to prevent that.

**Comment by kit1980** [comment]
@kit1980 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48670469).

**Comment by kit1980** [comment]
@kit1980 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48670469).

**Comment by kit1980** [comment]
@kit1980 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D48670605).

**Comment by kit1980** [comment]
I'm re-landing the stack, internal builds look fine to me now.

**Pull request closed without merging**
