### PR TITLE
added rocm 3.7 docker image

### PR DESCRIPTION
**Pull request by KyleCZH**
Added bionic rocm 3.7 docker image 

- @jeffdaily

### CODE REVIEW

**Comment by jeffdaily** [comment]
@malfet are you able to create the new entry for us so that this image will push properly to the docker repo?

**Comment by jeffdaily** [comment]
@ezyang @xw285cornell @malfet wasn't sure who among you has authority and the time to create a new AWS ECR entry for us.
`The repository with name 'pytorch/pytorch-linux-bionic-rocm3.7-py3.6' does not exist in the registry with id '308535385114'`

**Comment by jeffdaily** [comment]
CC @sunway513

**Comment by ezyang** [comment]
new ecr created

**Pull request closed without merging**
