### PR TITLE
fix bugs about traceback.walk_stack in python3.8.x

### LINKED ISSUE #110769: torch/cuda/_sanitizer.py uses buggy API in Python 3.11
### 🐛 Describe the bug

In Python 3.11, `traceback.walk_stack(None)` will have inconsistent results with Python 3.10, as described in  https://github.com/python/cpython/issues/96092.

I found this API is also used in pytorch:  https://github.com/pytorch/pytorch/blob/main/torch/cuda/_sanitizer.py#L372

I fixed this issue in another project by replacing this API with `inspect.currentframe`. Bring this up to prevent potential bugs.

### Versions

https://github.com/pytorch/pytorch/commit/59592ce9f208fc80be89cef5fa5ad1719c61a619

cc @ptrblck

### PR DESCRIPTION
**Pull request by fffrog**
Fixes #110769

as stated.

### CODE REVIEW

**Review by mikaylagawarecki — APPROVED** [review]
Could you fix lint please (run `make setup_lint` and `make quicklint` from your local pytorch directory)

**Comment by FFFrog** [comment]
> Could you fix lint please (run `make setup_lint` and `make quicklint` from your local pytorch directory)

Of course, have rebased and fix the lint already.

**Pull request closed without merging**
