### PR TITLE
use device methods

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Thanks a lot for the PR, that's a nice cleanup.

The CI seems to complain of the use of a `is_hip()` but I can't find it in the diff...
Maybe you want to rebase on top of viable/strict to retrigger the CI?

**Comment by cyyever** [comment]
> 
> 
> Thanks a lot for the PR, that's a nice cleanup.
> 
> The CI seems to complain of the use of a `is_hip()` but I can't find it in the diff...
> Maybe you want to rebase on top of viable/strict to retrigger the CI?

It still fails.

**Comment by albanD** [comment]
The error is
```
Feb 27 04:23:48 /var/lib/jenkins/workspace/c10/hip/impl/HIPGuardImpl.h:51:29: error: ‘struct c10::Device’ has no member named ‘is_hip’; did you mean ‘is_xpu’?
Feb 27 04:23:48 /var/lib/jenkins/workspace/c10/hip/impl/HIPGuardImpl.h:51:5: note: in expansion of macro ‘TORCH_INTERNAL_ASSERT’
Feb 27 04:23:48      TORCH_INTERNAL_ASSERT(d.is_hip());
```

I think you want to just add a new function here: https://github.com/pytorch/pytorch/blob/4a8ef4525ec8f5409457dc996d999b03082b3313/c10/core/Device.h#L79-L82
That looks like:
```cpp
  /// Return true if the device is of HIP type.
  bool is_hip() const noexcept {
    return type_ == DeviceType::HIP;
  }
```

Can you try that please?

**Comment by albanD** [comment]
All is green!
Thanks for the update!

**Pull request closed without merging**
