### PR TITLE
[RESUBMIT] Ensure ncclCommAbort can abort stuck ncclCommInitRank

### PR DESCRIPTION
**Pull request by pritamdamania87**
https://github.com/pytorch/pytorch/pull/95715 added the functionality to abort `ncclCommInitRankConfig` by specifying `blocking=0` to enable non-blocking behavior.

However, calling the `pg._abort()` didn't recover from a stuck `ncclCommInitRankConfig` since the `_abort` method only looked through `devNCCLCommMap_` map and aborted those communicators. Since `ncclCommInitRankConfig` was stuck, the communicator itself wasn't added to the map and the host thread was stuck on this line: https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L1171. As a result, `_abort` was a no-op.

To resolve this issue, I added the communicators to `inProgressCommMap_` as soon as they were created and then removed them once added to `devNCCLCommMap_`.

I also added a unit test that was failing without the changes to ProcessGroupNCCL.cpp

### CODE REVIEW

**Comment by pritamdamania87** [comment]
@osalpekar This is a resubmit of https://github.com/pytorch/pytorch/pull/103264 and CI is green. Is there some specific Sandcastle configuration that was causing issues?

**Comment by pritamdamania87** [comment]
@osalpekar Wondering if you found any issues after importing the PR?

**Comment by osalpekar** [comment]
@pritamdamania87 The flakiness is on our end internally. I'll stamp this and we can merge.

**Review by osalpekar — APPROVED** [review]

**Comment by pritamdamania87** [comment]
@osalpekar Do we need to import again? :)

```
This Pull Request has changes that have not been imported to the Diff, please import the Pull Request
```

**Comment by osalpekar** [comment]
@pritamdamania87 Yeah looks like this needed a re-import since the PR was updated, but it's merged now :)

**Pull request closed without merging**
