### PR TITLE
[ROCm] enable kernel asserts

### PR DESCRIPTION
**Pull request by jeffdaily**
Addresses missing ROCm feature indicated in #38943.

### CODE REVIEW

**Comment by jeffdaily** [comment]
@ngimel are there any unit tests to further verify this PR?  I was able to complete both a DEBUG=1 and a release build, but wasn't sure which unit test(s) if any would exercise this feature.

**Comment by ngimel** [comment]
@jeffdaily this test triggers device assert on cuda https://github.com/pytorch/pytorch/blob/7eb427e931bec9359cc579934885e1f3a4dc4472/test/test_cuda.py#L1436-L1463

**Comment by jeffdaily** [comment]
Strangely, the ROCm builds are now taking ~3 hours.  Before, it was ~30 minutes.  This caused on ROCm CI to fail.  Will retest.  For PyTorch tests, this PR might be causing a new mem access fault.  Retesting will also show if this is transient or reproducible.

**Comment by jeffdaily** [comment]
@ngimel thank you for pointing out the test that is used for this feature.  Unfortunately, there is an unintended side effect of this PR causing unreasonable build times.  Even if build times were reasonable, the test you pointed me to is failing.  I will close this PR while we look into these issues further.

**Pull request closed without merging**
