### PR TITLE
updating nccl to 2.7.3

### LINKED ISSUE #40095: Bump up NCCL to 2.7
NCCL 2.7 has been release with p2p communication. Let's upgrade our NCCL submodule to 2.7.

https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/p2p.html#sendrecv

### PR DESCRIPTION
**Pull request by agolynski**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#40622 updating nccl to 2.7.3**

### CODE REVIEW

**Comment by agolynski** [comment]
We have the same test failure as in https://github.com/pytorch/pytorch/pull/37506.

  C10D_NCCL_CHECK(ncclGroupEnd());

throws 

"""unhandled system error, NCCL version 2.7.3"""

Will investigate.

**Comment by sjeaugey** [comment]
It would probably be a good idea to set NCCL_DEBUG=WARN in your tests so that you get a human-readable error message explaining what call failed (and maybe why it failed).

**Comment by agolynski** [comment]
> It would probably be a good idea to set NCCL_DEBUG=WARN in your tests so that you get a human-readable error message explaining what call failed (and maybe why it failed).

@sjeaugey: Thank you for taking a look at it. Here is what I am seeing:

5135fc87695d:126318:126318 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
NCCL version 2.7.3+cuda10.2

5135fc87695d:126319:126319 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]

5135fc87695d:126319:126336 [1] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device

5135fc87695d:126319:126336 [1] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-54c7cb5318ccdf40-1-0-1 (size 9637888)


5135fc87695d:126318:126335 [0] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device

5135fc87695d:126318:126335 [0] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-89de17de85f2fd3f-1-1-0 (size 9637888)

however, if I run just ProcessGroupShareTensorTest.test_shared_allgather_nccl test standalone, it doesn't give me any error.

If enable NCCL_DEBUG=INFO, I see one difference: if I run a bundle I see
5135fc87695d:126920:126920 [0] NCCL INFO Launch mode Group

and if I run a single test it gives me:
5135fc87695d:126872:126872 [0] NCCL INFO Launch mode Parallel

do you know why we could have different launch modes depending on test?


@mrshenli had a hypothesis that it could be bad interaction between tests.

**Comment by sjeaugey** [comment]
```
5135fc87695d:126319:126336 [1] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
```
This means NCCL could not create a shared memory file in /dev/shm. See https://github.com/NVIDIA/nccl/issues/342 : the default docker size for /dev/shm seems to be 64 MB which could be too small.

Now I don't see why different tests would have different modes, unless one is launched with one process per GPU (or one GPU total) and others are launched with a single process managing multiple GPUs. The full INFO log would probably tell me more.

**Comment by agolynski** [comment]
> ```
> 5135fc87695d:126319:126336 [1] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
> ```
> 
> This means NCCL could not create a shared memory file in /dev/shm. See [NVIDIA/nccl#342](https://github.com/NVIDIA/nccl/issues/342) : the default docker size for /dev/shm seems to be 64 MB which could be too small.
> 
> Now I don't see why different tests would have different modes, unless one is launched with one process per GPU (or one GPU total) and others are launched with a single process managing multiple GPUs. The full INFO log would probably tell me more.

Just a crapshot: maybe the first test to run that initializes NCCL does it in its own mode and the rest of the tests just reuse it. Is there a large difference between the modes?

I think the tensors we are using for tests are very small, but seems like we try to allocate 9M per thread in our case. I wonder why this error only appeared in 2.6.4 version.

Here is INFO paste of failed test:
https://paste.pleaseignore.com/index.php?id=a89j7GwDIrKBKdBB

and here is INFO of passing test:
https://paste.pleaseignore.com/index.php?id=NNBCfYHKT6gawhM4

I've noticed that if i do something like:

`jenkins@fa9db2d0c8c3:~/workspace$ for i in $(seq 1 100); do python test/distributed/test_c10d_spawn.py ProcessGroupShareTensorTest.test_shared_allgather_nccl; done
`

it fails on 3rd or 4th run, so it makes sense: 20M per test so 3 runs fill 64M. Mode of running probably is not responsible for this.

@sjeaugey:  What would be your suggestion: reduce memory usage in /dev/shm? Are there params that allow us to set how much memory NCCL should allocate in /dev/shm? 

Thank you for your help!

**Comment by xw285cornell** [comment]
qq: is there a way to force NCCL don't use the shm to work around it? I guess another way to do is to increase the shm size of our docker image, cc. @malfet

**Comment by sjeaugey** [comment]
I think the Group/Parallel difference is explained in your logs :
```
./opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py:421: UserWarning: Single-Process Multi-GPU is not the recommended mode for DDP. In this mode, each DDP instance operates on multiple devices and creates multiple module replicas within one process. The overhead of scatter/gather and GIL contention in every forward pass can slow down training. Please consider using one DDP instance per device or per module replica by explicitly setting device_ids or CUDA_VISIBLE_DEVICES.
```
This test runs in single process multi-GPU mode. The other probably runs in multi-process mode.

Anyway, that's likely not the problem here. For some reason, the tests are eating up space in /dev/shm and don't release it. I was thinking it could be due to PyTorch not properly cleaning the NCCL communicator, but the shared memory segment should be unlinked right after we map it to make sure they get properly cleaned up when the process exits.

So I'm wondering if you could have processes staying behind ? If not, can you look at /dev/shm to see if you see NCCL files accumulating there ? Otherwise could it be docker is preventing the shared memory from being released ?

As for the reasons and workarounds, if you didn't see the issue with older versions, it could be that the tuning changed in NCCL and we're now using shared memory instead of P2P. You can try setting NCCL_P2P_LEVEL=SYS to go back to the old behavior. But there were performance reasons for doing so, so I'd like to understand why /dev/shm inside docker fills up.

**Comment by xkszltl** [comment]
Recommend to close https://github.com/pytorch/pytorch/issues/37325 in commit msg of this PR.

**Comment by malfet** [comment]
> qq: is there a way to force NCCL don't use the shm to work around it? I guess another way to do is to increase the shm size of our docker image, cc. @malfet

There is an option to increase shared memory size allocatable by a docker container, trying it in https://github.com/pytorch/pytorch/pull/41608

**Comment by agolynski** [comment]
Abandoning this PR in favor of #41608

**Comment by mattip** [comment]
This should be closed, gh-41608 was merged.

**Pull request closed without merging**
