### PR TITLE
Revert "Revert "Allow specifying tags for aten operators in native_functions.yaml""

### PR DESCRIPTION
**Pull request by anjali411**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #76456

This reverts commit ea44645c9a682a4e212e64b94a86383c3388ed6b.

reland of https://github.com/pytorch/pytorch/pull/72549

### CODE REVIEW

**Comment by seemethere** [comment]
Is there a reason for this revert? Can we include that in the PR description?

**Comment by anjali411** [comment]
> ~Is there a reason for this revert? Can we include that in the PR description?~
> 
> Nevermind I see this is a reland, can we include a link to the original PR?

added in the description

**Review by osalpekar — APPROVED** [review]

**Pull request closed without merging**
