### PR TITLE
insert default parameters in binary cross entropy with logits

### PR DESCRIPTION
**Pull request by lsrock1**
I inserted default weight and reduction params in binary_cross_entropy_with_logits function . These default params exist in python and binary_cross_entropy function in cpp.

### CODE REVIEW

**Review by gchanan — APPROVED** [review]

**Comment by gchanan** [comment]
@lsrock, I believe you need to update the mypy definitions, see the error output:

```
Jun 05 17:56:35 Running test_type_hints ... [2019-06-05 17:56:35.960372]
Jun 05 17:56:36 test_doc_examples (__main__.TestTypeHints) ... torch/__init__.pyi:984: error: invalid syntax
Jun 05 17:56:36 FAIL
Jun 05 17:56:36 
Jun 05 17:56:36 ======================================================================
Jun 05 17:56:36 FAIL: test_doc_examples (__main__.TestTypeHints)
Jun 05 17:56:36 ----------------------------------------------------------------------
Jun 05 17:56:36 Traceback (most recent call last):
Jun 05 17:56:36   File "test_type_hints.py", line 161, in test_doc_examples
Jun 05 17:56:36     check=True)
Jun 05 17:56:36 subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-mmypy', '--follow-imports', 'silent', '--check-untyped-defs', '/var/lib/jenkins/workspace/test/generated_type_hints_smoketest.py']' returned non-zero exit status 2.
Jun 05 17:56:36 
Jun 05 17:56:36 During handling of the above exception, another exception occurred:
Jun 05 17:56:36 
Jun 05 17:56:36 Traceback (most recent call last):
Jun 05 17:56:36   File "test_type_hints.py", line 163, in test_doc_examples
Jun 05 17:56:36     raise AssertionError("mypy failed.  Look above this error for mypy's output.")
Jun 05 17:56:36 AssertionError: mypy failed.  Look above this error for mypy's output.
Jun 05 17:56:36 
Jun 05 17:56:36 ----------------------------------------------------------------------
Jun 05 17:56:36 Ran 1 test in 0.216s
Jun 05 17:56:36 
Jun 05 17:56:36 FAILED (failures=1)
Jun 05 17:56:36 Traceback (most recent call last):
Jun 05 17:56:36   File "test/run_test.py", line 449, in <module>
Jun 05 17:56:36     main()
Jun 05 17:56:36   File "test/run_test.py", line 441, in main
Jun 05 17:56:36     raise RuntimeError(message)
Jun 05 17:56:36 RuntimeError: test_type_hints failed!
Jun 05 17:56:37 + cleanup
Jun 05 17:56:37 + retcode=1
Jun 05 17:56:37 + set +x
Jun 05 17:56:37 =================== sccache compilation log ===================
Jun 05 17:56:37 =========== If your build fails, please take a look at the log above for possible reasons ===========
```

**Comment by lsrock1** [comment]
@gchanan Thank you for kind replying.
I have checked generated Declarations.yaml and Functions.h. They are clearly made.
Which part should i fix?
I don't want to bother you, but i cannot get clue.

**Comment by lsrock1** [comment]
@gchanan passed

**Pull request closed without merging**
