### PR TITLE
[ONNX] Document ONNX diagnostics

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #88371

Reference pages: 
- Landing page: https://docs-preview.pytorch.org/88371/onnx_diagnostics.html
- Individual rule: https://docs-preview.pytorch.org/88371/generated/onnx_diagnostics_rules/POE0004%3Aoperator-supported-in-newer-opset-version.html

An initial PR to setup the document generation for ONNX diagnostics.
* Add document page for ONNX diagnostics.
* Add document generation for diagnostics rules from `rules.yaml`.
* Add dependency on `myst-parser` for markdown to rst parsing.

More content to be added.

cc @svekars @carljparker

### CODE REVIEW

**Review by abock — APPROVED** [review]

**Review by justinchuby — APPROVED** [review]
LGTM🚀

**Comment by BowenBao** [comment]
@malfet @kit1980 please take a look.

**Review by malfet — APPROVED** [review]

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
