### PR TITLE
Shard windows periodic job more

### PR DESCRIPTION
**Pull request by clee2000**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
Increasing the number of shards looks ok to me. AFAICT, the root cause here is because running mem_leak_check sequentially on Windows negates all the benefit of parallelization and regresses the duration more than 2x on Windows https://hud.pytorch.org/tts.  So another option is to increase the timeout value, but I think this approach is better as an immediate mitigation

**Comment by huydhn** [comment]
In the long run, I think we should consider this approach https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule to have more than one cron for periodic jobs:

* `45 0,4,8,12,16,20 * * *` runs every 4 hours without mem_leak_check
* `29 8 * * *` runs one per day with mem_leak_check

From what I see from GitHub docs, we could set different timeout values for the job depending on the chosen schedule I think

**Comment by clee2000** [comment]
> In the long run, I think we should consider this approach https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule to have more than one cron for periodic jobs:
> 
> * `45 0,4,8,12,16,20 * * *` runs every 4 hours without mem_leak_check
> * `29 8 * * *` runs one per day with mem_leak_check
> 
> From what I see from GitHub docs, we could set different timeout values for the job depending on the chosen schedule. The same can be done in filter_test_config.py script to not tamper with the "regular" periodic runs. Any thoughts?

Oh that is a much better solution, I didn't realize you could just see which schedule it was being run on

**Pull request closed without merging**
