### PR TITLE
Add trace and log_sigmoid_forward decomps

### PR DESCRIPTION
**Pull request by Chillee**
Main question mark is that `log_sigmoid_forward` uses `acc_t` instead of `opmath_t` - not sure if we have a decorator today for that?

Glad to add one if we don't.

### CODE REVIEW

**Comment by ezyang** [comment]
Yes please do. `acc_t` and `opmath_t` are slightly different

**Comment by ezyang** [comment]
Although in this case, it looks like the underlying kernel might just be incorrectly using acc_t

**Review by ezyang — APPROVED** [review]

**Comment by Chillee** [comment]
> Yes please do. acc_t and opmath_t are slightly different

I chatted with @ngimel, and my impression was that `acc_t` is essentially deprecated and we should just use `opmath`-style casting.

**Comment by ngimel** [comment]
Yeah, in this (as in many other cases) acc_t is used instead of more correct opmath_t (because there was no opmath_t at the time)

**Comment by Chillee** [comment]
@ngimel So I'll just also change the kernels to use `opmath_t`, and everybody's happy :)

**Comment by ezyang** [comment]
`acc_t` still has a place for accumulation. The main difference is if float goes to double or stays float.

**Comment by Chillee** [comment]
@ezyang Actually, in this case, things are even worse lol. The CPU promotes from bf16 to float32 (but not fp16 to float32!): https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/Activation.cpp#L27

**Comment by ezyang** [comment]
oh yeah that's right, because cuda double is horrible

**Pull request closed without merging**
