### PR TITLE
Deprecate tensor.type()

### LINKED ISSUE #29161: [C++] Deprecate Tensor.type() (DeprecatedTypeProperties)
`tensor.type()` gives you a DeprecatedTypeProperties object, but we didn't actually deprecate the call.  We should do this ASAP so we can delete DeprecatedTypeProperties.

CC @ezyang.

cc @ezyang @gchanan @zou3519 @jerryzh168 @yf225 @SsnL

### PR DESCRIPTION
**Pull request by ngoldbaum**
Fixes #29161.

I looked a bit at the code changes related to this and think I have all of the use cases of `DeprecatedTypeProperties` covered in the message, but suggestions from someone with more context on this would be very much appreciated :)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
You're gonna need to kill the deprecated sites too.

```
Nov 22 04:02:12 /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/input_metadata.h: In constructor 'torch::autograd::InputMetadata::InputMetadata(const at::Tensor&)':
Nov 22 04:02:12 /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/input_metadata.h:29:26: error: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated [-Werror=deprecated-declarations]
Nov 22 04:02:12    : InputMetadata(t.type(), t.sizes(), t.device()) { }
```

**Comment by ngoldbaum** [comment]
I've killed all of the call sites extant in the codebase except for the one I described in my comment on the issue tracking this: https://github.com/pytorch/pytorch/issues/29161#issuecomment-558308534. Any suggestions for how to resolve the issues highlighted there with `tensor_flatten.cpp` would be very appreciated.

This ended up being a biggish PR. I tried to keep things atomic so it might be easier to review commit-by-commit rather than looking at the whole pull request diff. I'm also happy to upstream this as separate pull requests if that would be easier to review.

**Comment by ngoldbaum** [comment]
Hmm, looks like this still needs some work before it's ready for review, seeing test failures locally....

**Comment by ezyang** [comment]
As an operational matter, it's probably better if we merge this as is, even though you haven't handled the one case you mentioned in your issue. Do you still need to do anything else on this PR before it lands? I see the WIP is still on the PR.

**Comment by ngoldbaum** [comment]
I was still trying to get the tests to pass last night, but it looks like the last commit fixed the remaining test failures. This is probably fine to merge as-is. Should we leave in the deprecation message since there's still the sites in `tensor_flatten.h` and `tensor_flatten.cpp` that need to be replaced?

**Comment by ezyang** [comment]
> Should we leave in the deprecation message since there's still the sites in tensor_flatten.h and tensor_flatten.cpp that need to be replaced?

We can leave it in if it doesn't break anything. One instance of deprecated spew is OK to me for getting the deprecation in earlier.

**Comment by ngoldbaum** [comment]
Nope, shouldn't break anything :)

**Pull request closed without merging**
