### PR TITLE
replace blackwhite in caffe2/python/pybind_state.cc

### LINKED ISSUE #41711: Replace blacklist/whitelist in caffe2/python/pybind_state.cc
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `caffe2/python/pybind_state.cc`. See issue #41443 for more information.

### PR DESCRIPTION
**Pull request by admud**
Replaced black and white terms in caffe2/python/pybind_state.cc

Fixes #41711

### CODE REVIEW

**Review by zhangguanheng66 — COMMENTED** [review]
see my comments before.

**Comment by muhdmud** [comment]
Hi @zhangguanheng66, when i clicked on view changes, cannot seem to find the comments, is it anything to do with the naming convention?

**Comment by muhdmud** [comment]
@zhangguanheng66 what am i missing for this PR?

**Comment by SplitInfinity** [comment]
Already fixed in #42089.

**Pull request closed without merging**
