### PR TITLE
Add 3d Attn Pattern to match HF Whisper

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #109066
* __->__ #109156
* #109142
* #108917
* #108894
* #109663

Adds a 3d pattern that improves perf of HF Whisper from 1.3 -> 4.1. We could be matching more generally on 3d, but i'll leave that for another pr. 

Thanks to @drisspg for helping me write the pattern.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Comment by eellison** [comment]
cc @Valentine233 this is causing some cpu failures because the cpu attention meta is incorrect.

**Comment by Chillee** [comment]
Can we use my recent faketensor updater to update the meta?

**Comment by eellison** [comment]
@Chillee that wouldn't help in this case. The meta function is incorrect, so when we run the op in [ExternKernelFallback](https://github.com/pytorch/pytorch/blob/main/torch/_inductor/ir.py#L3206) we generate incorrect strides within inductor. Then those incorrect strides become runtime assertion failures.

**Comment by Valentine233** [comment]
> cc @Valentine233 this is causing some cpu failures because the cpu attention meta is incorrect.

Please help modify with the following diff patch. This could avoid the error of `AssertionError`.

```
diff --git a/torch/_meta_registrations.py b/torch/_meta_registrations.py
index 82b9d1bf3dd..fb5fbc51491 100644
--- a/torch/_meta_registrations.py
+++ b/torch/_meta_registrations.py
@@ -4811,14 +4811,12 @@ def meta__scaled_dot_product_flash(
     max_seqlen_batch_k = key.size(2)
     Nnz_q = batch_size * max_seqlen_batch_q

-    query_t = query.transpose(1, 2)
-    query_reshaped = query_t.reshape(Nnz_q, num_heads, head_dim)
-    attention = torch.empty_like(query_reshaped, device=query.device)
-    attention = attention.view(
-        batch_size, max_seqlen_batch_q, num_heads, head_dim
-    ).transpose(1, 2)
-
     if device_hint(query) == "cpu":
+        attention = torch.empty(
+            (batch_size, max_seqlen_batch_q, num_heads, head_dim),
+            dtype=query.dtype,
+            device=query.device,
+        ).transpose(1, 2)
         logsumexp = torch.empty(
             (
                 batch_size,
@@ -4839,6 +4837,12 @@ def meta__scaled_dot_product_flash(
             torch.empty((), dtype=torch.long, device="meta"),
             torch.empty((), dtype=query.dtype, device=query.device),
         )
+    query_t = query.transpose(1, 2)
+    query_reshaped = query_t.reshape(Nnz_q, num_heads, head_dim)
+    attention = torch.empty_like(query_reshaped, device=query.device)
+    attention = attention.view(
+        batch_size, max_seqlen_batch_q, num_heads, head_dim
+    ).transpose(1, 2)
     max_seqlen_q = math.ceil(max_seqlen_batch_q / 16) * 16
     logsumexp = torch.empty(
         (batch_size, num_heads, max_seqlen_q),
```

**Comment by eellison** [comment]
@Valentine233, updated, but your diff didn't exactly apply. could you post the new meta registration for sdpa in its entirety, not just the diff ?

**Comment by Valentine233** [comment]
> @Valentine233, updated, but your diff didn't exactly apply. could you post the new meta registration for sdpa in its entirety, not just the diff ?

Sure! Pls try again, thanks.
```
@register_meta(
    [
        aten._scaled_dot_product_flash_attention,
    ]
)
def meta__scaled_dot_product_flash(
    query: Tensor,
    key: Tensor,
    value: Tensor,
    dropout_p: float = 0.0,
    is_causal: bool = False,
    return_debug_mask: bool = False,
    scale: Optional[float] = None,
):
    batch_size = query.size(0)
    num_heads = query.size(1)
    max_seqlen_batch_q = query.size(2)
    head_dim = query.size(3)

    max_seqlen_batch_k = key.size(2)
    Nnz_q = batch_size * max_seqlen_batch_q

    if device_hint(query) == "cpu":
        attention = torch.empty(
            (batch_size, max_seqlen_batch_q, num_heads, head_dim),
            dtype=query.dtype,
            device=query.device,
        ).transpose(1, 2)
        logsumexp = torch.empty(
            (
                batch_size,
                max_seqlen_batch_q,
                num_heads,
            ),
            dtype=torch.float,
            device=query.device,
        ).transpose(1, 2)
        return (
            attention,
            logsumexp,
            torch.empty((), dtype=torch.int32, device="meta"),
            torch.empty((), dtype=torch.int32, device="meta"),
            0,
            0,
            torch.empty((), dtype=torch.long, device="meta"),
            torch.empty((), dtype=torch.long, device="meta"),
            torch.empty((), dtype=query.dtype, device=query.device),
        )
    query_t = query.transpose(1, 2)
    query_reshaped = query_t.reshape(Nnz_q, num_heads, head_dim)
    attention = torch.empty_like(query_reshaped, device=query.device)
    attention = attention.view(
        batch_size, max_seqlen_batch_q, num_heads, head_dim
    ).transpose(1, 2)
    max_seqlen_q = math.ceil(max_seqlen_batch_q / 16) * 16
    logsumexp = torch.empty(
        (batch_size, num_heads, max_seqlen_q),
        dtype=torch.float,
        device=query.device,
    )
    cumulative_sequence_length_q = torch.empty(
        batch_size + 1, dtype=torch.int32, device="meta"
    )
    cumulative_sequence_length_k = torch.empty(
        batch_size + 1, dtype=torch.int32, device="meta"
    )

    if return_debug_mask:
        blocksize_c = 128 if head_dim > 64 else 256
        max_seqlen_k = math.ceil(max_seqlen_batch_q / blocksize_c)
        if max_seqlen_batch_k <= 128:
            max_seqlen_k = 128
        elif max_seqlen_batch_k <= 256:
            max_seqlen_k = 256
        debug_mask = torch.empty(
            (batch_size, num_heads, max_seqlen_q, max_seqlen_k),
            dtype=query.dtype,
            device=query.device,
        )
    else:
        debug_mask = torch.empty(0, dtype=query.dtype, device=query.device)

    # Note [Seed and Offset]: device for seed and offset below depends on whether we are
    # capturing or not, but at the time of tracing we don't know if we
    # are going to use cudagraphs or not, so we return meta tensors here
    # it's possible we'll need to have some special handling in inductor for sdpa

    return (
        attention,
        logsumexp,
        cumulative_sequence_length_q,
        cumulative_sequence_length_k,
        max_seqlen_batch_q,
        max_seqlen_batch_k,
        torch.empty((), dtype=torch.long, device="meta"),
        torch.empty((), dtype=torch.long, device="meta"),
        debug_mask,
    )
```

**Comment by eellison** [comment]
cc @Valentine233 accuracy failing on HF whisper Cpu with these changes

**Pull request closed without merging**
