### PR TITLE
Rename is_complex_t -> is_complex

### PR DESCRIPTION
**Pull request by zasdfgbnm**
`is_complex_t` is a bad name. For example in std, there are `std::is_same` but not `std::is_same_t`.

### CODE REVIEW

**Comment by malfet** [comment]
@zasdfgbnm this change have a merge conflicts, so it can not be merged as it.Please rebase, otherwise looks good to me.

**Review by malfet — APPROVED** [review]

**Comment by zasdfgbnm** [comment]
@malfet rebased

**Comment by anjali411** [comment]
@zasdfgbnm can you rebase this PR?

**Comment by zasdfgbnm** [comment]
@anjali411 rebased

**Comment by zasdfgbnm** [comment]
ping @anjali411

**Comment by anjali411** [comment]
cc. @ailzhang for the XLA failure

**Comment by anjali411** [comment]
@zasdfgbnm can you rebase?

**Comment by zasdfgbnm** [comment]
@anjali411 rebased

**Comment by anjali411** [comment]
@zasdfgbnm sorry couldn't land it earlier because of some failing FB tests. can you rebase it again?

**Comment by zasdfgbnm** [comment]
@anjali411 done

**Pull request closed without merging**
