### PR TITLE
[Clang Tidy] Fix misc-header-include-cycle errors in clang-tidy and ignore some files

### PR DESCRIPTION
**Pull request by cyyever**
Since there are such cycles in libfmt and PyTorch, which are detected by clang-tidy.
```
/home/cyy/pytorch/third_party/fmt/include/fmt/format-inl.h:25:10: error: circular header file dependency detected while including 'format.h', please check the include path [misc-header-include-cycle,-warnings-as-errors]
   25 | #include "format.h"
      |          ^
/home/cyy/pytorch/third_party/fmt/include/fmt/format.h:4530:12: note: 'format-inl.h' included from here
 4530 | #  include "format-inl.h"
```

### CODE REVIEW

**Comment by Skylion007** [comment]
We should flle an issue with libfmt, they tend to be pretty responsive. Is this issue on their latest master/main?

**Comment by Skylion007** [comment]
Instead of globally excluding this check, this check does provide a Clang-Tidy option for "IgnoredFiles", can't we just use that somehow?

**Comment by cyyever** [comment]
@Skylion007 Help review?

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
