### PR TITLE
Enable DDPOptimizer by default in dynamo

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #89096
* __->__ #88523

Performance benchmarks on 6 popular models from 1-64 GPUs compiled with
torchinductor show performance gains or parity with eager, and showed
regressions without DDPOptimizer.  *Note: resnet50 with small batch size shows a regression with optimizer, in part due to failing to compile one subgraph due to input mutation, which will be fixed.  
(hf_Bert, hf_T5_large, hf_T5, hf_GPT2_large, timm_vision_transformer, resnet50)

Correctness checks are implemented in CI (test_dynamo_distributed.py),
via single-gpu benchmark scripts iterating over many models
(benchmarks/dynamo/torchbench.py/timm_models.py/huggingface.py),
and via (multi-gpu benchmark scripts in torchbench)[https://github.com/pytorch/benchmark/tree/main/userbenchmark/ddp_experiments].

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Comment by soumith** [comment]
can you link to the spreadsheet of benchmarks here

**Comment by davidberard98** [comment]
Results on 6 models (hf_Bert, hf_GPT2_large, hf_T5, hf_T5_large, resnet50, timm_vision_transformer)

nov01_with_ddpoptimizer
nov01_without_ddp

For internal users: N2750232

**Comment by soumith** [comment]
with DDPOptimizer and 1-GPU ResNet50 seems to have a slowdown below 1.0x, why is that?

**Comment by davidberard98** [comment]
@soumith we think this is just noise plus the fact that resnet50 + 1 gpu spends too much time on communication to see a speedup from dynamo (at least on this batch size of 32, which is the torchbench default for resnet50). We re-ran over a larger number of samples (28, compared to 8 in the data above) on only the resnet50 model, results shown below (N2752413). We also ran on batch_size=128, where we do see a speedup.

resnet50_raw_samples_128
resnet50_raw_samples
resnet50_speedup

**Comment by wconstab** [comment]
> with DDPOptimizer and 1-GPU ResNet50 seems to have a slowdown below 1.0x, why is that?

I'm surprised it is so pronounced.  Earlier data https://www.internalfb.com/intern/anp/view/?id=2750232 
image

However, we learned 2 things about resnet
 - at this model size we saw compute time about matching comms time, leaving us pretty susceptible to noise
 - one subgraph in resnet ends up having an in-place mutation, which currently causes that subgraph to fall back to eager.  We lost compute optimization for that subgraph.

We also changed bs from 32 to 128 at one point and got lower noise, but i'm not sure which bs is in these charts.

The compilation failure is something that we need to fix at the AOTAutograd layer.  It's being tracked in AOTAutograd 2.0 discussion, and afaiu it's better to not try to fix it in the DDPOptimizer layer and fix it in the autograd layer.  (The alternative is we could try to make DDPOptimizer avoid splits that upset AOTAutograd, but that would complicate DDPOptimizer and also deviate from the buckets used by DDP.

**Comment by wconstab** [comment]
I've run an accuracy/functionality sweep across torchbench, timm_models, huggingface scripts.
The data is [here](https://docs.google.com/spreadsheets/d/1XBvFnKH8H3mWDKrcWxubjxEzBCn6HMMtnQzfSST4u6s/edit#gid=1792492528) 

Suite | Pass | Fail to run | Fail Accuracy | Total Models | Pass Rate
-- | -- | -- | -- | -- | --
Huggingface | 31 | 12 | 1 | 44 | 0.7045454545
timm_models | 59 | 1 | 2 | 62 | 0.9516129032
torchbench | 43 | 9 | 4 | 56 | 0.7678571429

While the pass rates are not great, only 1 issue in the bunch is unique to turning DDPOptimizer on, and it's an  AotAutograd Input mutation issue which we'll depend on being fixed in the updated AotAutograd implementation that handles mutation.

The remainder of the issues (either crashes or accuracy) happen either with dynamo-eager+ddp, or dynamo-inductor+ddp, but without using DDPOptimizer.  The most common error categories i've sampled are
  - RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one... 
  - RuntimeError: Trying to backward through the graph a second time...
  - torch._dynamo.utils: [ERROR] Accuracy failed for key name logits
  and probably a few other cases less common
  
I therefore propose to land this enablement PR as-is, and file new issues for DDP+dynamo/inductor to triage accordingly.
cc @davidberard98 @aazzolini @soumith @ezyang @bdhirsh

**Comment by soumith** [comment]
landing it sounds reasonable

**Comment by wconstab** [comment]
New accuracy sweep [here](https://docs.google.com/spreadsheets/d/1XBvFnKH8H3mWDKrcWxubjxEzBCn6HMMtnQzfSST4u6s/edit#gid=924630697)

* "Expected to have finished reduction in the prior iteration before starting a new one" fixed by https://github.com/pytorch/pytorch/pull/88645
* DLRM failure is not a real issue (see https://github.com/pytorch/torchdynamo/issues/1849)
* remaining accuracyi ssues/runtime errors happen with inductor (with/without DDP)
* EXCEPT for AotAutograd input mutation issues triggered by graph breaks (https://github.com/pytorch/torchdynamo/issues/1850)

@davidberard98 seems close to getting the accuracy checks running in the real perf benchmarks.  @bdhirsh is working on getting AotAutograd improvements to a state we can at least confirm these graph-break cases are resolved.

**Comment by davidberard98** [comment]
Update on accuracy checks:

* See @wconstab's accuracy checks in the comments below. These are based on the [dynamo benchmarks](https://github.com/pytorch/pytorch/tree/master/benchmarks/dynamo), on which DDPOptimizer was run on a single node and checked for accuracy
* I did a smaller set of accuracy checks over the 6 OSS models, to check on E2E accuracy when testing on the same setup that was used to test performance. On these 6 models, 5 pass; the remaining 1 model (resnet50) is also failing on non-distributed dynamo benchmarks for unknown reasons.

https://github.com/pytorch/benchmark/pull/1294 - see this for distributed correctness checks. Instructions are included in the PR.

**Review by davidberard98 — APPROVED** [review]

**Pull request closed without merging**
