### PR TITLE
[1/N] Non-Tensor: Scalar Support: Enable aot compile to support aten operations with scalar input like alpha

### PR DESCRIPTION
**Pull request by EikanWang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #125897
* #125831
* #125819
* #125308
* #124926
* #124070
* __->__ #124177

Some operations have a scalar input parameter, like `torch.add(a, b, alpha=2.0)`.  Currently, the aot compile does not support such a case because it requires the signature of the captured graph to align with the operation's signature. This means that some inputs in the captured graph may be scalar(float, int, bool, etc.). It breaks the assumption of `compile_fx_aot` as it assumes all the example inputs are tensor - https://github.com/pytorch/pytorch/blob/0f6ce45bcbd7026c00da43db0317ede10830378b/torch/_inductor/compile_fx.py#L1048

This PR intends to support such cases by allowing not-aligned signature and filtering out the non-Tensor parameters. 

Captured graph for `torch.add(a, b, alpha=2.0)`

```
opcode         name      target           args              kwargs
-------------  --------  ---------------  ----------------  --------------
placeholder    arg0_1    arg0_1           ()                {}
placeholder    arg1_1    arg1_1           ()                {}
call_function  add       aten.add.Tensor  (arg0_1, arg1_1)  {'alpha': 2.0}
output         output_1  output           ((add,),)         {}
```

cc @voznesenskym @penguinwu @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jgong5 — COMMENTED** [review]
Is it a limitation of aot compile that doesn't support the non-tensor inputs or it is by design? I'm wondering if we should allow the support of non-tensor inputs without the need of adding a flag here?

**Comment by EikanWang** [comment]
> Is it a limitation of aot compile that doesn't support the non-tensor inputs or it is by design? I'm wondering if we should allow the support of non-tensor inputs without the need of adding a flag here?

Actually, I think it is a limitation. It is by design. The literal scalar will be created as a constant variable by Dynamo, and then the Inductor folds the scalar into the produced kernel rather than a kernel parameter. If we want to support such a case by adding non-Tensor support as an input parameter, we need to change the current design.

By the way, `export` provides the flag as its parameter.
https://github.com/pytorch/pytorch/blob/6e4c4e93b66729145ac87ef384632b1abacaf26d/torch/_dynamo/eval_frame.py#L1036

**Review by jansel — APPROVED** [review]

**Review by desertfire — APPROVED** [review]
cc @angelayi

**Review by jgong5 — APPROVED** [review]

**Comment by EikanWang** [comment]
@angelayi , I will try to submit another PR to address your comments.

**Pull request closed without merging**
