### PR TITLE
Allow future type parsing

### PR DESCRIPTION
**Pull request by highker**

### CODE REVIEW

**Comment by zdevito** [comment]
Can you give a specific example of what you want to do here? I do not think allowing implicit conversion on futures is a good idea.

**Comment by highker** [comment]
Here is a use case:
```
class ExampleModule(torch.jit.ScriptModule):
    __constants__ = ["models", "n_models"]

    def __init__(self, models, param):
        super().__init__()
        self.models = nn.ModuleList(
            [
                torch.jit.trace(
                    copy.deepcopy(model),
                    (param),
                    _force_outplace=True,
                )
                for model in models
            ]
        )
        self.n_models = len(models)

    @torch.jit.script_method
    def forward(self, param):
        futures = torch.jit.annotate(List[Future[List[torch.Tensor]]], [])
        for model in self.models:
            future = torch.jit._fork(model, param)
            futures.append(torch.jit.annotate(Future[List[torch.Tensor]], future))

        outs = torch.jit.annotate(List[List[torch.Tensor]], [])
        for i in range(self.n_models):
            outs.append(torch.jit._wait(futures[i]))

        return outs
```

Each `model` in the given `models` returns a different type (`Tuple[Tensor, Tensor]`, `Tuple[Tensor, Tensor, Tensor]`, `List[Tensor]`). Of course we can enforce users to always return `List[Tensor]`... But requires touching multiple lower model implementations.

**Comment by zdevito** [comment]
What will the type of outs be? Even if you did add some conversions for futures, outs is going to be completely unusable from the JIT.

**Comment by zdevito** [comment]
The easiest way to fix this seems to be to just wrap each module that returns a tuple in a Module that converts that tuple to a list for step 1 and then unpacks it back to a tuple for step 2.

**Comment by highker** [comment]
as discussed; dropped type conversion.

@zdevito We still need the parsing though. Left the patch with a little fix to the parsing logic.

**Review by zdevito — APPROVED** [review]

**Pull request closed without merging**
