### PR TITLE
use libdevice for tanh

### PR DESCRIPTION
**Pull request by ngimel**
Per title
I see slight differences in perf with this implementation, where standalone tanh is slightly slower for a tensor of 4000000
 elements (20.4 us instead of 19.4us), other sizes are within noise. 
 @bertmaher could you check if it affects your benchmarks?

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by bertmaher — APPROVED** [review]
Seems reasonable since it’s an accuracy issue, if it’s a major regression on our stuff we can do some more thinking after we see it in the charts

**Review by anijain2305 — APPROVED** [review]
cc @desertfire

**Comment by ngimel** [comment]
Let's revert to unbreak, I'll reland with increased tolerance.

**Pull request closed without merging**
