### PR TITLE
[Doc] Fix typo in `torch/fx/passes/README.md`

### PR DESCRIPTION
**Pull request by spzala**
Fix typo, `utis` to `utils`, in the utility name.

### CODE REVIEW

**Comment by spzala** [comment]
cc @svekars @janeyx99 @soulitzer @malfet  - thanks!

**Review by soulitzer — APPROVED** [review]
@pytorchbot merge

**Comment by spzala** [comment]
@soulitzer thanks so much! I thought, considering the change and file changed is .md, I should use `skip ci` to save time and ci resources but from the bot message it looks like I shouldn't skip ci, so let me update the commit message to run the ci. Thanks again!

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
> I should use `skip ci` to save time and ci resources but from the bot message it looks like I shouldn't skip ci, so let me update the commit message to run the ci. Thanks again!

Please do not use `skip ci` as mergebot requires certain checks for all files that would never be met if one skips all the CI

**Comment by spzala** [comment]
> @pytorchbot merge -f "Lint is green"

Sounds good. Thank you @malfet !!

**Comment by spzala** [comment]
@malfet @soulitzer I am not sure if this makes sense, but I think removing `skip ci` tip from the CONTRIBUTING.md is a good idea so I have created https://github.com/pytorch/pytorch/pull/134134 Please take a look. Thanks!

**Pull request closed without merging**
