### PR TITLE
[opinfo] empty_strided

### PR DESCRIPTION
**Pull request by khushi-411**
Follows: #100223

cc @soumith @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by khushi-411** [comment]
Hi, @ezyang! Could you please review the PR? Thanks in advance :))

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
