### PR TITLE
Fix uniform returning end point for BFloat16 and Half

### LINKED ISSUE #96947: torch.rand can sample the upper bound for lower precision floating point dtypes on CUDA
[Documentation](https://pytorch.org/docs/stable/generated/torch.rand.html):

> Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)

```python
import itertools

import torch

for device, dtype in itertools.product(
    ["cpu", "cuda"],
    [
        torch.float16,
        torch.bfloat16,
        torch.float32,
        torch.float64,
        torch.complex32,
        torch.complex64,
        torch.complex128,
    ],
):
    torch.manual_seed(0)
    # I only used this high number of samples to make sure the other dtypes are not affected
    # On my machine 1_000 was sufficient for the check to fail for bfloat16, 
    # and 10_000 for float16 and complex32
    t = torch.rand(10_000_000, dtype=dtype, device=device)
    if dtype.is_complex:
        t = torch.view_as_real(t)

    print(f"{dtype}, {device}: {'PASS' if (t != 1).all() else 'FAIL'}")
```

```
torch.float16, cpu: PASS
torch.bfloat16, cpu: PASS
torch.float32, cpu: PASS
torch.float64, cpu: PASS
torch.complex32, cpu: PASS
torch.complex64, cpu: PASS
torch.complex128, cpu: PASS
torch.float16, cuda: FAIL
torch.bfloat16, cuda: FAIL
torch.float32, cuda: PASS
torch.float64, cuda: PASS
torch.complex32, cuda: FAIL
torch.complex64, cuda: PASS
torch.complex128, cuda: PASS
```

Failures happen for `float16`, `bfloat16`, and `complex32` only on CUDA.

This was detected in #96331, which uses `Tensor.uniform_` under the hood, but I guess internally it is the same kernel.

### PR DESCRIPTION
**Pull request by peterbell10**
Fixes #96947

If we generate `1.0 - float_eps`, the BFloat16 and Half constructors will round this to 1.0 which is outside of the half-open range. Instead, we delay the bounds change until after the value has been rounded.

cc @pbelevich @pmeier

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
How nice is to have if constexpr? :D

**Review by ngimel — APPROVED** [review]

**Comment by pmeier** [comment]
Hard to say if the test failure is valid or not:

```
2023-03-20T18:20:38.1245440Z _ TestSDPA.test_flash_attention_vs_math_ref_grads_batch_size_1_seq_len_q_2048_seq_len_k_128_head_dim_8_is_causal_False_dropout_p_0_22_bfloat16_scale_None _
2023-03-20T18:20:38.1245557Z Traceback (most recent call last):
2023-03-20T18:20:38.1245764Z   File "/var/lib/jenkins/workspace/test/test_transformers.py", line 1909, in test_flash_attention_vs_math_ref_grads
2023-03-20T18:20:38.1245943Z     self.assertEqual(query.grad, query_ref.grad.to(query.grad.dtype),
2023-03-20T18:20:38.1246248Z   File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3013, in assertEqual
2023-03-20T18:20:38.1246365Z     raise error_metas[0].to_error(
2023-03-20T18:20:38.1246514Z AssertionError: Tensor-likes are not close!
2023-03-20T18:20:38.1246520Z 
2023-03-20T18:20:38.1246632Z Mismatched elements: 1 / 65536 (0.0%)
2023-03-20T18:20:38.1246803Z Greatest absolute difference: 0.0014754831790924072 at index (0, 2, 2033, 0) (up to 0.0011385045945644379 allowed)
2023-03-20T18:20:38.1247035Z Greatest relative difference: 319.4129032258065 at index (0, 2, 2033, 0) (up to 71.4206771850586 allowed)
```

The dtype and number of elements fit the error case described in #96947. 

This check was added (or at least adapted) in #94009. But this comment doesn't really instill confidence:

https://github.com/pytorch/pytorch/blob/a37b4fa03a68115c25cf37bf2d5fac8f4f252e04/test/test_transformers.py#L1704-L1707

@drisspg has there been any progress on investigating this? What do you propose to move forward?

**Comment by ngimel** [comment]
In the meantime I think we should increase tolerance for this case

**Comment by pmeier** [comment]
We would need to increase the `rtol` five fold and the `atol` roughly by 50%. And we are currently stopping after the first failure. Maybe there are more parameters that fail here.

**Comment by ngimel** [comment]
atol is 0.0011 vs 0.0014, (that's 30%), rtol doesn't matter if atol is fine.

**Comment by drisspg** [comment]
> In the meantime I think we should increase tolerance for this case

I agree with this. I have not had a chance to fully characterize the nature of these FP errors. I think that it would be fine to bump the mulitiplier of 2 to something greater. There are 65k elements in that tensors and the parametrization sweeps 20k tests, that entry could be an outlier ( not that much confidience installing either)

**Comment by pmeier** [comment]
I've added the `keep-going` label so let's see what falls out.

**Comment by pmeier** [comment]
It seems the only related failure is the one we observed above. In the light of https://github.com/pytorch/pytorch/pull/96962#issuecomment-1476890632, I think we are good just upping the tolerance.

**Pull request closed without merging**
