### PR TITLE
Add support for opening Unicode filenames on MS Windows [Caffe2]

### PR DESCRIPTION
**Pull request by augustofg**
Strings passed to ReadProtoFromFile / WriteProtoFromFile will be treated
as UTF-8 and converted to UTF-16 before calling _wopen, ifstream and
ofstream.

### CODE REVIEW

**Comment by ezyang** [comment]
Could we get a test for this? I believe we are building and testing Caffe2 on Windows, so it should just be a matter of trying to suck in a file that has Unicode characters in it.

**Comment by Palmitoxico** [comment]
@ezyang I'm not familiar to the CI tests used for the MS Windows build, can you point some documentation / examples please?

Thanks!
Auguso.

**Comment by yf225** [comment]
@orionr Curious do you know what would be a good test example for this?

**Comment by ezyang** [comment]
Hi @Palmitoxico, sorry about the late response. I think `caffe2/utils/proto_utils_test.cc` might be a good place to put the test.

**Comment by Palmitoxico** [comment]
@ezyang Ok, I'll take a look.

**Pull request closed without merging**
