### PR TITLE
fix torchvhsion failed case test_classification_model on slow_conv2d

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #77348
* __->__ #77347

### CODE REVIEW

**Comment by mingfeima** [comment]
To fix torchvision failed cases on https://github.com/pytorch/vision/issues/6001

The test case has a NCHW input and a NHWC weight, with channels last feature enabled, channels last memory format is propagated. Need to make sure both input and weight memory format are aligned.

**Review by datumbox — APPROVED** [review]
LGTM. I'm approving to avoid delaying fixing TorchVision's broken CI. It's worth adding some unit-tests to check for this issue either on this PR or on a follow up.

cc @vitaly-fedyunin

**Comment by mingfeima** [comment]
Update: test cases added. 

Now `test_conv_thnn_nhwc` will check the following pattern:
* input(nhwc) + weight (nhwc)
* input(nhwc) + weight(nchw)

**Review by frank-wei — APPROVED** [review]

**Comment by frank-wei** [comment]
The fix looks good to fix the torchvision break.
@pytorchbot merge this

**Pull request closed without merging**
