### PR TITLE
Change templated_attention -> flex_attention

### PR DESCRIPTION
**Pull request by drisspg**
# Summary

Change all the names

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
Yayay.

Not too late to change the name to `flesh_attention` (Flexible + Flash) :^)

**Review by yanboliang — APPROVED** [review]

**Comment by kit1980** [comment]
See D56851095

**Comment by drisspg** [comment]
@kit1980  can we forward fix this I think that there might be some diffs in the stack that make this a pretty tricky revert?

**Comment by drisspg** [comment]
@yanboliang I think this alibi test was the one that failed for you that is likely fixed with your PR?

**Comment by kit1980** [comment]
@drisspg there is one change that may depend on this, but the git revert went cleanly here https://github.com/pytorch/pytorch/pull/125434

**Comment by kit1980** [comment]
@drisspg The revert attempt via bot failed probably because you force-pushed after merge.

**Pull request closed without merging**
