### PR TITLE
Port symeig to ATen and enable batching of inputs

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:
- Port `symeig` from TH/THC to ATen
- Enable batching of matrix inputs for `symeig`
- Modify derivative computation based on batching
- Update docs to reflect the change

Test Plan:
- Added additional tests in `test_torch.py` (with a port to `test_cuda.py`) and `common_methods_invocations.py` to test if both the port and batching work.

### CODE REVIEW

**Comment by vishwakftw** [comment]
Windows build failures are spurious.

**Review by soumith — APPROVED** [review]

**Comment by vishwakftw** [comment]
Thank you for the review.

**Comment by vishwakftw** [comment]
@soumith is there I need to do to help get this landed?

**Pull request closed without merging**
