### PR TITLE
Enable mypy check for torch/_inductor/codegen/common.py

### PR DESCRIPTION
**Pull request by ashok-kumar-kannan**
Fixes #105230

Summary:

As suggested in [#105230](https://github.com/pytorch/pytorch/issues/105230) mypy checking is enabled in torch/_inductor/codegen/common.py.

After the fix:
`mypy --follow-imports=skip torch/_inductor/codegen/common.py 
Success: no issues found in 1 source file`

Reviewers: @eellison 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by eellison — APPROVED** [review]
nice!!

**Comment by eellison** [comment]
@ashok-kumar-kannan sorry for delay - mind rebasing ?

**Comment by Skylion007** [comment]
Fix the merge conflicts and we should be good to merge

**Comment by ashok-kumar-kannan** [comment]
Sure @Skylion007 I will fix the merge conflicts and update the branch

**Comment by ashok-kumar-kannan** [comment]
@eellison @Skylion007  Shall we merge this now? CI was passed now.

**Pull request closed without merging**
