### PR TITLE
update eigen submodule to latest release (3.4.0) with rocm fixes

### LINKED ISSUE #73177: Source build error: use of undeclared identifiers (`half2half2` and `h2div`)
### 🐛 Describe the bug

When compiling pytorch from source with ROCm, one gets compilation errors related to missing identifiers `half2half2` and `h2div` in the Eigen submodule. Upon further digging this is due to using an outdated Eigen mirror (https://github.com/eigenteam/eigen-git-mirror). Using an updated Eigen mirror should fix this: https://gitlab.com/libeigen/eigen

Here is the error message:
`half2half2`
```
/home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.11.0rc2-rocm/cmake/../third_party/eigen/Eigen/src/Core/arch/GPU/PacketMathHalf.h:51:10: error: use of undeclared identifier 'half2half2'; did you mean '__half2half2'?
  return half2half2(from);
         ^~~~~~~~~~
         __half2half2
/opt/rocm/hip/include/hip/amd_detail/amd_hip_fp16.h:550:21: note: '__half2half2' declared here
            __half2 __half2half2(__half x)
                    ^
```

`h2div`:
```
/home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.11.0rc2-rocm/cmake/../third_party/eigen/Eigen/src/Core/arch/GPU/PacketMathHalf.h:292:10: error: use of undeclared identifier 'h2div'
  return h2div(a, b);
         ^
2 errors generated when compiling for gfx803.
CMake Error at torch_hip_generated_gelu_op.hip.o.cmake:200 (message):
  Error generating file
  /home/acxz/vcs/git/github/rocm-arch/python-pytorch-rocm/src/pytorch-1.11.0rc2-rocm/build/caffe2/CMakeFiles/torch_hip.dir/operators/hip/./torch_hip_generated_gelu_op.hip.o
```

### Versions

```
Collecting environment information...
PyTorch version: N/A (1.11.0-rc2)
Is debug build: N/A     (No)
CUDA used to build PyTorch: N/A   (No)
ROCM used to build PyTorch: N/A    (Yes)

This not being detected makes sense since I'm still trying to compile from source and haven't been able to build PyTorch yet.

OS: Arch Linux (x86_64)
GCC version: (GCC) 11.2.0
Clang version: 13.0.1
CMake version: version 3.22.2
Libc version: glibc-2.35

Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] (64-bit runtime)
Python platform: Linux-5.16.10-arch1-1-x86_64-with-glibc2.35
Is CUDA available: N/A (Yes but not used)
CUDA runtime version: 11.4.120  (Installed but not used)
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1050 Ti with Max-Q Design   (It is true that I do not have a ROCm gpu on this computer, but I am still compiling for rocm targets manually specified `PYTORCH_ROCM_ARCH=gfx803`
Nvidia driver version: 510.54
cuDNN version: Could not collect (not installed)
HIP runtime version: N/A    (5.0.1)  (Looks like these two are not getting detected even though I have them installed)
MIOpen runtime version: N/A    (5.0.1)

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[conda] Could not collect (Installed but not using/not relevant)
```

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

### PR DESCRIPTION
**Pull request by acxz**
Fixes #73177

### CODE REVIEW

**Comment by acxz** [comment]
@jithunnair-amd or @jeffdaily can you take a look at this PR? It's a very short PR to review.

**Comment by jeffdaily** [comment]
> @jithunnair-amd or @jeffdaily can you take a look at this PR? It's a very short PR to review.

eigen is regularly maintained for rocm support; it's used a lot in tensorflow.  I don't see any issues with updating to the latest eigen sources for pytorch.  Which unit tests exercise this PR's changes?

**Comment by acxz** [comment]
@jeffdaily  it's actually not a unit test but rather a compilation error

**Comment by acxz** [comment]
@jeffdaily @jithunnair-amd friendly ping

**Review by jeffdaily — APPROVED** [review]
LGTM - but you'll need someone with merge authority to land this.

**Comment by acxz** [comment]
@suo @seemethere @ngimel 

requesting merge

**Review by suo — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
