### PR TITLE
Remove Caffe2 python code

### PR DESCRIPTION
**Pull request by cyyever**
Follows the recent changes of Caffe2.

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal @albanD

### CODE REVIEW

**Review by r-barnes — APPROVED** [review]
Yeah!

**Review by Skylion007 — APPROVED** [review]

**Comment by cyyever** [comment]
@jeanschmidt  @r-barnes  The lint error is unrelated as it happened before.

**Pull request closed without merging**
