### PR TITLE
[CI, 3.13] enable 3.13 CI

### PR DESCRIPTION
**Pull request by williamwen42**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #141264
* #141951
* #141950
* #141887
* #141886
* #141860
* #141859
* #140733
* __->__ #139533
* #141862
* #141858
* #141674
* #141673
* #141623
* #141621
* #141605
* #141577
* #141572
* #142003
* #141409

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by atalman — APPROVED** [review]
lgtm please fix lint

**Review by malfet — APPROVED** [review]
LGTM

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but it is failing test_cpp_extensions_open_device_registration. The test was wrongly excluded by TD' -c nosignal

test_cpp_extensions_open_device_registration.py::TestCppExtensionOpenRgistration::test_open_device_numpy_serialization [GH job link](https://github.com/pytorch/pytorch/actions/runs/11974723463/job/33389165935) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/b7a25c1ee7cdb559516db2b10279c996742a1708)

cc @clee2000

**Pull request closed without merging**
