### PR TITLE
[CI] Change inductor-perf-test-nightly naming

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #131476

Summary: To make it consistent with inductor-perf-test-nightly-x86

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
I remember seeing this on your other PR

**Review by zou3519 — APPROVED** [review]

**Comment by desertfire** [comment]
> I remember seeing this on your other PR

I decided to land this in a separate PR to avoid interrupt any currently running inductor-A100-perf-nightly workflow.

**Pull request closed without merging**
