### PR TITLE
Add acctype in NLL Loss

### LINKED ISSUE #55657: `nn.CrossEntropyLoss` reductions for large CPUTensors yield wrong results
## 🐛 Bug

The loss value calculated by `nn.CrossEntropyLoss` via `reduction='mean'` vs. a manual mean calculation yields different results for "large" input tensors on the CPU.
Small inputs and CUDA seems to work fine.

The issue was reported in [the forum](https://discuss.pytorch.org/t/inconsistent-behaviour-of-cross-entropy-loss-without-weights/117540) by [Dominika_Basaj](https://discuss.pytorch.org/u/Dominika_Basaj) and [KFrank](https://discuss.pytorch.org/u/KFrank) created a great executable code snippet to isolate it down a bit more.
Thanks a lot to both of you!

## To Reproduce

Code snippet taken from [here](https://discuss.pytorch.org/t/inconsistent-behaviour-of-cross-entropy-loss-without-weights/117540/2?u=ptrblck).
```python
import torch
print (torch.__version__)

_ = torch.manual_seed (2021)

nBatch = 128
nClass = 2
height = 768
width = 768

input = torch.randn (nBatch, nClass, height, width)
target = torch.randint (nClass, (nBatch, height, width))

print ('nBatch =', nBatch, '\nnClass =', nClass, '\nheight =', height, '\nwidth =', width)
print ('big, float:')
print ('mean:', torch.nn.CrossEntropyLoss() (input, target))
print ('none:', torch.nn.CrossEntropyLoss (reduction = 'none') (input, target).mean())
print ('sum:', torch.nn.CrossEntropyLoss (reduction = 'sum') (input, target) / target.numel())

print ('big, cuda:')
print ('mean:', torch.nn.CrossEntropyLoss() (input.cuda(), target.cuda()))
print ('none:', torch.nn.CrossEntropyLoss (reduction = 'none') (input.cuda(), target.cuda()).mean())
print ('sum:', torch.nn.CrossEntropyLoss (reduction = 'sum') (input.cuda(), target.cuda()) / target.numel())

print ('big, double:')
print ('mean:', torch.nn.CrossEntropyLoss() (input.double(), target))
print ('none:', torch.nn.CrossEntropyLoss (reduction = 'none') (input.double(), target).mean())
print ('sum:', torch.nn.CrossEntropyLoss (reduction = 'sum') (input.double(), target) / target.numel())


nBatch = 8
nClass = 2
height = 16
width = 16

input = torch.randn (nBatch, nClass, height, width)
target = torch.randint (nClass, (nBatch, height, width))

print ('nBatch =', nBatch, '\nnClass =', nClass, '\nheight =', height, '\nwidth =', width)
print ('small, float:')
print ('mean:', torch.nn.CrossEntropyLoss() (input, target))
print ('none:', torch.nn.CrossEntropyLoss (reduction = 'none') (input, target).mean())
print ('sum:', torch.nn.CrossEntropyLoss (reduction = 'sum') (input, target) / target.numel())

print ('small, cuda:')
print ('mean:', torch.nn.CrossEntropyLoss() (input.cuda(), target.cuda()))
print ('none:', torch.nn.CrossEntropyLoss (reduction = 'none') (input.cuda(), target.cuda()).mean())
print ('sum:', torch.nn.CrossEntropyLoss (reduction = 'sum') (input.cuda(), target.cuda()) / target.numel())

print ('small, double:')
print ('mean:', torch.nn.CrossEntropyLoss() (input.double(), target))
print ('none:', torch.nn.CrossEntropyLoss (reduction = 'none') (input.double(), target).mean())
print ('sum:', torch.nn.CrossEntropyLoss (reduction = 'sum') (input.double(), target) / target.numel())
```

Output:
```python
1.8.1
nBatch = 128
nClass = 2
height = 768
width = 768
big, float:
mean: tensor(2.7632) # !!
none: tensor(0.9028) # !!
sum: tensor(0.6140) # !!
big, cuda:
mean: tensor(0.9028, device='cuda:0')
none: tensor(0.9028, device='cuda:0')
sum: tensor(0.9028, device='cuda:0')
big, double:
mean: tensor(0.9028, dtype=torch.float64)
none: tensor(0.9028, dtype=torch.float64)
sum: tensor(0.9028, dtype=torch.float64)
nBatch = 8
nClass = 2
height = 16
width = 16
small, float:
mean: tensor(0.9148)
none: tensor(0.9148)
sum: tensor(0.9148)
small, cuda:
mean: tensor(0.9148, device='cuda:0')
none: tensor(0.9148, device='cuda:0')
sum: tensor(0.9148, device='cuda:0')
small, double:
mean: tensor(0.9148, dtype=torch.float64)
none: tensor(0.9148, dtype=torch.float64)
sum: tensor(0.9148, dtype=torch.float64)
```

## Expected behavior

The calculated loss should be approx. equal up to the floating point precision.

## Environment

```python
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.19.6

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: A100-SXM4-40GB
GPU 1: A100-SXM4-40GB
GPU 2: A100-SXM4-40GB
GPU 3: A100-SXM4-40GB
GPU 4: A100-SXM4-40GB
GPU 5: A100-SXM4-40GB
GPU 6: A100-SXM4-40GB
GPU 7: A100-SXM4-40GB

Nvidia driver version: 450.51.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py38h1e0a361_2    conda-forge
[conda] mkl_fft                   1.3.0            py38h5c078b8_1    conda-forge
[conda] mkl_random                1.2.0            py38hc5bc63f_1    conda-forge
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.8.1           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
```

## Additional information

I've tried to set the number of interop and intraop threads to 1 as a quick debugging step, but this didn't help.

EDIT: Also same issue in the latest nightly: `1.9.0.dev20210408`

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @albanD @mruberry

### PR DESCRIPTION
**Pull request by zsef123**
Fixes #55657 

CUDA code using `acc_type`
https://github.com/pytorch/pytorch/blob/c7312f5271b9ce9ac988fffde90818354e5841b8/aten/src/THCUNN/SpatialClassNLLCriterion.cu#L73-L77

But CPU is not
https://github.com/pytorch/pytorch/blob/c7312f5271b9ce9ac988fffde90818354e5841b8/aten/src/ATen/native/LossNLL2d.cpp#L81-L82

So I applying the `at:acc_type`

And I'm not adding test case about larger size. Did you think is this need?

Output of this PR
```
1.9.0a0+gita0a122b
nBatch = 128 
nClass = 2 
height = 768 
width = 768
big, float:
mean: tensor(0.9028)
none: tensor(0.9028)
sum: tensor(0.9028)
big, cuda:
mean: tensor(0.9028, device='cuda:0')
none: tensor(0.9028, device='cuda:0')
sum: tensor(0.9028, device='cuda:0')
big, double:
mean: tensor(0.9028, dtype=torch.float64)
none: tensor(0.9028, dtype=torch.float64)
sum: tensor(0.9028, dtype=torch.float64)
nBatch = 8 
nClass = 2 
height = 16 
width = 16
small, float:
mean: tensor(0.9148)
none: tensor(0.9148)
sum: tensor(0.9148)
small, cuda:
mean: tensor(0.9148, device='cuda:0')
none: tensor(0.9148, device='cuda:0')
sum: tensor(0.9148, device='cuda:0')
small, double:
mean: tensor(0.9148, dtype=torch.float64)
none: tensor(0.9148, dtype=torch.float64)
sum: tensor(0.9148, dtype=torch.float64)
```

cc: @albanD @ptrblck

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
The code change looks good to me.
Is there a noticeable perf drop here?

cc @ngimel

**Comment by zsef123** [comment]
@albanD  This PR is little faster

Cpu : Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz

<details><summary>This PR</summary><p>

```
1.9.0a0+gita0a122b
                                mean                            none                            sum
(1, 2, 16, 16)                  26.18us                         26.72us                         26.00us
(1, 2, 64, 64)                  240.75us                        249.53us                        240.66us
(1, 2, 128, 128)                935.50us                        968.93us                        935.17us
(1, 2, 768, 768)                33124.70us                      34237.64us                      33107.28us
(1, 2, 1024, 1024)              58806.73us                      60845.88us                      58774.40us
(1, 4, 16, 16)                  30.42us                         31.15us                         30.48us
(1, 4, 64, 64)                  311.99us                        321.38us                        311.92us
(1, 4, 128, 128)                1240.92us                       1275.14us                       1241.59us
(1, 4, 768, 768)                44300.86us                      45305.06us                      44152.20us
(1, 4, 1024, 1024)              78738.54us                      80825.11us                      78700.45us
(1, 8, 16, 16)                  39.09us                         40.11us                         39.23us
(1, 8, 64, 64)                  447.14us                        458.32us                        447.11us
(1, 8, 128, 128)                1830.57us                       1864.16us                       1837.10us
(1, 8, 768, 768)                65427.35us                      67362.95us                      65898.14us
(1, 8, 1024, 1024)              133775.06us                     136308.48us                     134079.32us
(4, 2, 16, 16)                  70.55us                         74.36us                         70.56us
(4, 2, 64, 64)                  930.81us                        964.84us                        930.15us
(4, 2, 128, 128)                3730.59us                       3857.30us                       3750.76us
(4, 2, 768, 768)                133631.32us                     138121.84us                     133768.96us
(4, 2, 1024, 1024)              251578.62us                     259223.61us                     251789.38us
(4, 4, 16, 16)                  87.58us                         91.43us                         87.78us
(4, 4, 64, 64)                  1207.80us                       1245.18us                       1209.78us
(4, 4, 128, 128)                4977.43us                       5128.05us                       4990.77us
(4, 4, 768, 768)                194200.18us                     198849.24us                     193901.07us
(4, 4, 1024, 1024)              354194.81us                     362580.36us                     352603.41us
(4, 8, 16, 16)                  120.38us                        123.99us                        120.17us
(4, 8, 64, 64)                  1743.20us                       1785.72us                       1743.13us
(4, 8, 128, 128)                7312.23us                       7463.87us                       7317.00us
(4, 8, 768, 768)                373307.34us                     379414.41us                     375424.70us
(4, 8, 1024, 1024)              666445.33us                     675762.36us                     665292.02us
(16, 2, 16, 16)                 244.15us                        256.02us                        244.58us
(16, 2, 64, 64)                 3690.22us                       3830.21us                       3692.50us
(16, 2, 128, 128)               14736.42us                      15251.08us                      14722.74us
(16, 2, 768, 768)               569682.66us                     586489.75us                     566441.21us
(16, 2, 1024, 1024)             1006234.19us                    1072532.01us                    1006147.23us
(16, 4, 16, 16)                 316.72us                        328.53us                        316.27us
(16, 4, 64, 64)                 4787.07us                       5001.73us                       4869.29us
(16, 4, 128, 128)               19828.81us                      20383.43us                      19831.91us
(16, 4, 768, 768)               792999.33us                     811817.71us                     793531.56us
(16, 4, 1024, 1024)             1404642.49us                    1471180.58us                    1404510.22us
(16, 8, 16, 16)                 442.96us                        456.58us                        443.01us
(16, 8, 64, 64)                 6863.86us                       6968.94us                       6830.25us
(16, 8, 128, 128)               29168.28us                      29726.44us                      29147.28us
(16, 8, 768, 768)               1487041.22us                    1521732.73us                    1487790.57us
(16, 8, 1024, 1024)             2640674.33us                    2713774.27us                    2639919.51us
(64, 2, 16, 16)                 933.04us                        974.95us                        933.14us
(64, 2, 64, 64)                 14648.78us                      15181.73us                      14644.23us
(64, 2, 128, 128)               59413.07us                      61415.91us                      59348.74us
(64, 2, 768, 768)               2250445.84us                    2391147.18us                    2265327.07us
(64, 2, 1024, 1024)             4003263.93us                    4267385.06us                    4032054.59us
(64, 4, 16, 16)                 1216.30us                       1261.62us                       1216.92us
(64, 4, 64, 64)                 19099.86us                      19642.43us                      19093.94us
(64, 4, 128, 128)               79412.77us                      81484.40us                      79285.53us
(64, 4, 768, 768)               3190192.92us                    3306221.15us                    3179382.98us
(64, 4, 1024, 1024)             5663291.80us                    5906448.80us                    5616394.04us
(64, 8, 16, 16)                 1719.42us                       1769.87us                       1719.27us
(64, 8, 64, 64)                 27600.46us                      28161.22us                      27606.98us
(64, 8, 128, 128)               134152.69us                     136872.26us                     134051.58us
(64, 8, 768, 768)               5955944.15us                    6167889.99us                    5999281.28us
(64, 8, 1024, 1024)             10668582.84us                   10878060.76us                   10716018.86us
(128, 2, 16, 16)                1846.61us                       1926.87us                       1845.39us
(128, 2, 64, 64)                29300.67us                      30381.88us                      29299.96us
(128, 2, 128, 128)              118969.13us                     123090.96us                     118884.29us
(128, 2, 768, 768)              4535298.88us                    4809769.49us                    4534885.37us
(128, 2, 1024, 1024)            8010058.97us                    8687986.54us                    8180187.91us
(128, 4, 16, 16)                2417.96us                       2503.95us                       2418.02us
(128, 4, 64, 64)                38179.53us                      39268.77us                      38193.24us
(128, 4, 128, 128)              171878.34us                     176932.28us                     171967.19us
(128, 4, 768, 768)              6403645.21us                    6669680.90us                    6317984.52us
(128, 4, 1024, 1024)            11342454.71us                   11833057.78us                   11287235.79us
(128, 8, 16, 16)                3422.42us                       3518.39us                       3421.01us
(128, 8, 64, 64)                55329.84us                      56476.25us                      55313.97us
(128, 8, 128, 128)              331003.05us                     336677.06us                     331963.22us
(128, 8, 768, 768)              12012377.32us                   12269480.11us                   11960062.18us
(128, 8, 1024, 1024)            21508115.14us                   22141356.89us                   22096606.31us

```
</details>

<details><summary>Release</summary><p>

```
1.8.1+cu102
                                mean                            none                            sum
(1, 2, 16, 16)                  28.99us                         30.41us                         28.84us
(1, 2, 64, 64)                  255.87us                        264.25us                        256.08us
(1, 2, 128, 128)                987.92us                        1016.77us                       988.03us
(1, 2, 768, 768)                34984.04us                      36347.17us                      35117.38us
(1, 2, 1024, 1024)              62155.58us                      63796.84us                      62202.73us
(1, 4, 16, 16)                  34.20us                         36.02us                         34.34us
(1, 4, 64, 64)                  340.13us                        349.67us                        340.34us
(1, 4, 128, 128)                1349.33us                       1380.85us                       1351.04us
(1, 4, 768, 768)                48225.66us                      49121.35us                      47985.20us
(1, 4, 1024, 1024)              85320.06us                      87168.40us                      85304.13us
(1, 8, 16, 16)                  43.74us                         45.56us                         43.85us
(1, 8, 64, 64)                  495.83us                        504.25us                        493.68us
(1, 8, 128, 128)                1988.55us                       2023.98us                       1992.69us
(1, 8, 768, 768)                71397.00us                      72527.49us                      71301.30us
(1, 8, 1024, 1024)              169354.74us                     171840.84us                     169281.73us
(4, 2, 16, 16)                  75.33us                         78.67us                         75.53us
(4, 2, 64, 64)                  984.25us                        1013.64us                       983.48us
(4, 2, 128, 128)                3928.71us                       4035.55us                       3927.21us
(4, 2, 768, 768)                141062.17us                     145016.16us                     141035.23us
(4, 2, 1024, 1024)              263223.12us                     271011.66us                     264065.13us
(4, 4, 16, 16)                  95.86us                         98.94us                         95.88us
(4, 4, 64, 64)                  1310.98us                       1342.08us                       1311.04us
(4, 4, 128, 128)                5256.83us                       5369.55us                       5279.80us
(4, 4, 768, 768)                207010.29us                     211630.70us                     207046.52us
(4, 4, 1024, 1024)              376624.73us                     384654.42us                     376720.41us
(4, 8, 16, 16)                  132.86us                        136.56us                        132.93us
(4, 8, 64, 64)                  1908.08us                       1921.56us                       1908.62us
(4, 8, 128, 128)                7941.79us                       8070.64us                       7969.99us
(4, 8, 768, 768)                383355.15us                     388345.69us                     382329.51us
(4, 8, 1024, 1024)              680271.79us                     689350.54us                     680382.38us
(16, 2, 16, 16)                 258.86us                        269.02us                        260.15us
(16, 2, 64, 64)                 3909.31us                       4028.14us                       3891.89us
(16, 2, 128, 128)               15698.03us                      16129.19us                      15681.47us
(16, 2, 768, 768)               595510.07us                     607667.31us                     592912.07us
(16, 2, 1024, 1024)             1054359.29us                    1110822.68us                    1054956.04us
(16, 4, 16, 16)                 343.68us                        355.13us                        344.62us
(16, 4, 64, 64)                 5230.23us                       5326.89us                       5198.94us
(16, 4, 128, 128)               21491.17us                      21938.18us                      21491.84us
(16, 4, 768, 768)               851972.75us                     867633.01us                     851536.14us
(16, 4, 1024, 1024)             1519893.55us                    1571475.58us                    1509239.11us
(16, 8, 16, 16)                 489.48us                        499.54us                        486.23us
(16, 8, 64, 64)                 7638.66us                       7766.00us                       7638.86us
(16, 8, 128, 128)               31628.34us                      32152.11us                      31651.24us
(16, 8, 768, 768)               1529349.79us                    1552222.56us                    1539647.69us
(16, 8, 1024, 1024)             2716738.26us                    2788113.88us                    2793594.99us
(64, 2, 16, 16)                 988.63us                        1024.02us                       988.35us
(64, 2, 64, 64)                 15508.75us                      15949.94us                      15518.88us
(64, 2, 128, 128)               61930.65us                      63682.69us                      61944.61us
(64, 2, 768, 768)               2378928.56us                    2514304.92us                    2403526.13us
(64, 2, 1024, 1024)             4225571.95us                    4469411.35us                    4309772.37us
(64, 4, 16, 16)                 1323.47us                       1357.71us                       1322.64us
(64, 4, 64, 64)                 20725.25us                      21178.01us                      20732.35us
(64, 4, 128, 128)               86157.77us                      88076.29us                      86178.40us
(64, 4, 768, 768)               3389955.51us                    3548007.28us                    3408549.82us
(64, 4, 1024, 1024)             6073744.98us                    6278513.65us                    6095383.64us
(64, 8, 16, 16)                 1884.58us                       1931.28us                       1883.85us
(64, 8, 64, 64)                 29980.36us                      30466.57us                      29988.52us
(64, 8, 128, 128)               143219.16us                     145978.28us                     143251.28us
(64, 8, 768, 768)               6265357.09us                    6448773.25us                    6286468.00us
(64, 8, 1024, 1024)             11439195.16us                   12036979.03us                   11526441.27us
(128, 2, 16, 16)                1954.51us                       2022.02us                       1955.60us
(128, 2, 64, 64)                30978.95us                      31827.96us                      30948.81us
(128, 2, 128, 128)              125697.09us                     129413.87us                     125653.32us
(128, 2, 768, 768)              4770817.07us                    5063256.56us                    4768723.77us
(128, 2, 1024, 1024)            8427406.94us                    9053953.30us                    8655340.27us
(128, 4, 16, 16)                2624.06us                       2699.84us                       2624.39us
(128, 4, 64, 64)                41468.44us                      42353.82us                      41461.15us
(128, 4, 128, 128)              184248.94us                     188764.69us                     184426.33us
(128, 4, 768, 768)              6776462.46us                    7136811.82us                    6810605.99us
(128, 4, 1024, 1024)            12248282.18us                   12850117.67us                   12125406.85us
(128, 8, 16, 16)                3753.10us                       3840.49us                       3753.36us
(128, 8, 64, 64)                61185.28us                      62189.88us                      61171.94us
(128, 8, 128, 128)              339835.42us                     344867.26us                     339667.67us
(128, 8, 768, 768)              13025402.91us                   13268142.01us                   12966599.78us
(128, 8, 1024, 1024)            23315949.96us                   24409698.88us                   23444286.61us
```
</details>

<details><summary>Script</summary><p>

```
import torch
from torch.utils.benchmark import Timer
from itertools import product

print (torch.__version__)
torch.manual_seed(0)

B = [1, 4, 16, 64, 128]
C = [2, 4, 8]
HW = [16, 64, 128, 768, 1024]

shapes = product(B, C, HW)
reductions = ["mean", "none", "sum"]

def run(b, c, hw):
    x = torch.randn(b, c, hw, hw)
    y = torch.randint(c, (b, hw, hw))

    shape = f"({b}, {c}, {hw}, {hw})"
    print(f"{shape:30s}", end="\t")

    for reduction in reductions:
        loss = torch.nn.CrossEntropyLoss(reduction=reduction)
        timer = Timer("loss(x, y)", globals={"loss": loss, "x": x, "y": y})

        measurement = timer.blocked_autorange(min_run_time=5)

        med = f"{measurement.median * 1e6 :3.2f}us"
        print(f"{med:30s}", end="\t")

    print("")

print("\t".join(f"{s:30s}" for s in [""] + reductions))
for x in shapes:
    run(*x)
```
</details>

**Comment by ngimel** [comment]
Code looks fine to me. GPU results are correct not by virtue of using `accscalar_t` (which is float for float scalar_t) but because gpu is doing parallel reduction. 
Some benchmarks will be useful.

**Comment by zsef123** [comment]
> Code looks fine to me. GPU results are correct not by virtue of using `accscalar_t` (which is float for float scalar_t) but because gpu is doing parallel reduction.
> Some benchmarks will be useful.

If acc is not applied, still have a risk, of course got very low probability 

And also I think parallel reduce can applying on CPU.
Is there any other reason for not doing this?

**Comment by ngimel** [comment]
>Is there any other reason for not doing this?

You mean, not applying accumulation in double on GPU? That's much more expensive, and we typically don't give guarantees that computations are performed in higher precision. 
Or using parallel (cascade) reduction on CPU instead of accumulating in double? There are no particular reasons for this, other than it has to be implemented. That's done for `sum` operation already.

**Comment by zsef123** [comment]
I mean only parallel algorithm. 
I'm curious about improving performance by parallel reductuon apart from precision.

**Comment by ngimel** [comment]
There's an issue open for that https://github.com/pytorch/pytorch/issues/40570, it talks about vectorizing reductions, but actually vectorization + cascade reduction, similarly to what it now done for sum, is a much better scope for it. With cascade reduction, accumulation in higher precision is not necessary (sooner or later you'll start running out of precision, but if that happens, you should have been using higher precision for your data anyway).

**Review by albanD — APPROVED** [review]
Following some offline discussion with Natalia, the perf hit should be minimal on CPU and it does fix the issue. So we can get that in as it will be much simpler than doing a custom reduction algorithm.

**Comment by albanD** [comment]
Hey!
Thanks again for the PR, we are not planning on merging it right now though because @peterbell10 made the change to get a cascade reduction here: https://github.com/pytorch/pytorch/pull/55841
This should give similar precision as this one but with faster runtime.

**Comment by albanD** [comment]
Forgot to close this, there is another version of this already landed per the comment above.

**Pull request closed without merging**
