### PR TITLE
Workarounds to the lack of nvidia-smi and ldconfig programs in macosx (was PR 16968)

### LINKED ISSUE #12174: get_cudnn_version in collect_env is flaky
## 🐛 Bug

`get_cudnn_version` [currently only looks for `libcudnn` in `/usr/local` and `/usr/bin`](https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py#L111), which sometimes fails to get the version of cudnn we have.

We should look as well in other places, maybe in `LD_LIBRARY_PATH` or `CUDNN_LIB_DIR` as well, which might give more indications of where it might be.

### PR DESCRIPTION
**Pull request by pearu**
Fixes #12174 for Mac OSX.

PS: This is a duplicate of PR #16968 that got messed up. Sorry for the confusion.

### CODE REVIEW

**Comment by zou3519** [comment]
@pearu can I see the output of the script on your machine?

**Comment by pearu** [comment]
@zou3519 , this is the output on a MacOSX with GPU:
```
PyTorch version: 1.1.0a0+4335aac
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GeForce GTX 1060 with Max-Q Design
Nvidia driver version: 1.1.0
cuDNN version: /Users/hameerabbasi/cuda/lib/libcudnn.dylib

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] torch==1.1.0a0+4335aac
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] mkl_fft                   1.0.10           py37h5e564d8_0  
[conda] mkl_random                1.0.2            py37h27c97d8_0  
[conda] torch                     1.1.0a0+4335aac           dev_0    <develop>
```

**Comment by zou3519** [comment]
> cuDNN version: /Users/hameerabbasi/cuda/lib/libcudnn.dylib

Maybe we should have a better way of finding out the cuDNN version (I think we can get PyTorch to toss that out if TORCH_AVAILABLE) but that is not necessary for this particular fix.

**Review by zou3519 — APPROVED** [review]
lgtm, thank you!

**Comment by pearu** [comment]
Fixes #12174

**Pull request closed without merging**
