### PR TITLE
Added option to update parameters using state_dict in AveragedModel (#65495)

### PR DESCRIPTION
**Pull request by prabhat00155**
Summary:
While implementing [EMA](https://github.com/pytorch/vision/pull/4381)(which extends AveragedModel) in torchvision, update_parameters() from AveragedModel could not be used as it did not handle state_dict(), so a custom update_parameters() needed to be defined in [EMA class](https://github.com/pytorch/vision/pull/4406). This PR aims to handle this scenario removing the need for this custom update_parameters() implementation.

Discussion: https://github.com/pytorch/vision/pull/4406#pullrequestreview-753734102

Pull Request resolved: https://github.com/pytorch/pytorch/pull/65495

Reviewed By: datumbox

Differential Revision: D31176742

Pulled By: prabhat00155

fbshipit-source-id: 326d14876018f21cf602bab5eaba344678dbabe2
(cherry picked from commit 2ea724b1fd543304e3be7bd223cac451cd093e16)

Fixes #{issue number}

### CODE REVIEW

**Review by datumbox — APPROVED** [review]
LGTM, thanks!

**Review by zhouzhuojie — APPROVED** [review]
lgtm, waiting for all the signals and will merge after that

**Comment by zhouzhuojie** [comment]
Looks like there's a change we need to fix in the release branch, @prabhat00155 can you try rebasing after this commit? https://github.com/pytorch/pytorch/pull/65787


cc @malfet

**Comment by prabhat00155** [comment]
@zhouzhuojie I see a couple of unrelated failures. Is there something preventing the merge?

**Comment by datumbox** [comment]
How can we unblock this? This needs to be followed up by cherrypicking PR #65921 which contains minor doc corrections and refactorings.

**Comment by datumbox** [comment]
@zhouzhuojie Sorry for the multiple pings, just being conscious  about the deadline for merging this in the release branch. Could you let us know if there is anything we can do on our side?

**Comment by datumbox** [comment]
Thanks a lot for your help merging this. :)

**Comment by malfet** [comment]
@gchanan good point, will update template for 1.10 and use this verbiage going forward.

**Pull request merged**
