### PR TITLE
Remove faulty process group code

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #61958 [draft] Remove process group agent code
* **#61907 Remove faulty process group code**

Removing the code for faulty process group agent since it was replaced by faulty tensorpipe agent

Differential Revision: [D29794666](https://our.internmc.facebook.com/intern/diff/D29794666)

### CODE REVIEW

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29794666).

**Review by mrshenli — APPROVED** [review]
LGTM! Thanks a lot for retiring faulty pg agent!

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29794666).

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29794666).

**Pull request closed without merging**
