### PR TITLE
enhance _InverseTransform's __repr__

### PR DESCRIPTION
**Pull request by alicanb**
I was debugging something else, realized InverseTransform's `__repr__` can be a bit more informative.

### CODE REVIEW

**Review by fritzo — APPROVED** [review]

**Comment by fritzo** [comment]
It's hard contributing to an open source project when contributors can't get PRs merged :-/ @ezyang

**Comment by ezyang** [comment]
So sorry, it looks like no one got cc'ed on this PR.

@fritzo, you're added as a committer to merge rules, so you should be able to merge this PR by writing @ pytorchbot merge (remove the space between at and pytorchbot). Give it a try?

**Review by ezyang — APPROVED** [review]

**Comment by fritzo** [comment]
> you're added as a committer to merge rules

Oh great, thanks!

**Comment by ezyang** [comment]
it looks like someone already added repr

**Pull request closed without merging**
