### PR TITLE
[_shard] Add ShardedTensorBase

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #82291

This PR added ShardedTensorBase, which is the base class of
ShardedTensor, and only contains local shards, ShardedTensorMetadata,
and does not have any communication backend attached (i.e ProcessGroup)

Differential Revision: [D38190272](https://our.internmc.facebook.com/intern/diff/D38190272)

### CODE REVIEW

**Comment by wanchaol** [comment]
@wanchaol has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38190272).

**Comment by wanchaol** [comment]
@wanchaol has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38190272).

**Review by fduwjj — APPROVED** [review]
lgtm

**Pull request closed without merging**
