### PR TITLE
[quant][core][devs] Refactor the implementation for quantized batchnorm module

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #72490
* __->__ #72489

Summary:
To reduce the duplicated code

Test Plan:
python test/test_quantization.py TestStaticQuantizedModule
python test/test_quantization.py TestQuantizeFxOps.test_qbatch_norm

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D34062367](https://our.internmc.facebook.com/intern/diff/D34062367)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34062367).

**Review by vkuzo — APPROVED** [review]

**Review by andrewor14 — APPROVED** [review]

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34062367).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34062367).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34062367).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34062367).

**Pull request closed without merging**
