### PR TITLE
Enable lerp on half type; fix output memory format

### PR DESCRIPTION
**Pull request by xwang233**

### CODE REVIEW

**Comment by xwang233** [comment]
cc @ptrblck

**Comment by xwang233** [comment]
@ngimel Is there any update on this?

**Review by ezyang — APPROVED** [review]

**Comment by heitorschueroff** [comment]
This commit broke some changes I was making to torch.quantile when giving at::lerp_out a discontiguous out tensor as follows:

```
>>> values_below
tensor([[[0., 4.],
         [0., 4.],
         [0., 4.],
         [0., 4.],
         [1., 4.],
         [0., 4.],
         [1., 4.],
         [1., 3.]]], device='cuda:0')

>>> values_above = values_below
>>> weights = torch.tensor([0., 0.], device='cuda:0')
>>> out = torch.empty([2, 1, 8], device='cuda:0')

>>> torch.lerp(values_below, values_above, weights, out=out.unsqueeze(-1).transpose_(0, -1).squeeze_(0))
tensor([[[0., 4.],
         [0., 4.],
         [0., 4.],
         [0., 4.],
         [1., 4.],
         [0., 4.],
         [1., 4.],
         [1., 3.]]], device='cuda:0')

>>> out
tensor([[[0., 4., 0., 4., 0., 4., 0., 4.]],

        [[1., 4., 0., 4., 1., 4., 1., 3.]]], device='cuda:0')
```

The problem is when I pass a view of out with the first dimension moved to the end. If instead I change out itself and then revert the change it works as follows:

```
>>> out.unsqueeze_(-1).transpose_(0, -1).squeeze_(0)
>>> torch.lerp(values_below, values_above, weights, out=out)
>>> out.unsqueeze_(0).transpose_(0, -1).squeeze_(-1)
>>> out
tensor([[[0., 0., 0., 0., 1., 0., 1., 1.]],

        [[4., 4., 4., 4., 4., 4., 4., 3.]]], device='cuda:0')
```

**Comment by ngimel** [comment]
This is not changed by this PR, it worked like this before. Here
```
torch.lerp(values_below, values_above, weights, out=out.unsqueeze(-1).transpose_(0, -1).squeeze_(0))
```
you are sending an intermediate variable as your `out` kwarg, so `out` tensor that you have is not expected to contain the result of your operation, an intermediate variable (that you no longer have access to) will. 
```
out1=torch.lerp(vals, values_above, weights, out=out.unsqueeze_(-1).transpose_(0, -1).squeeze_(0))
```
produces expected results (that is, `out` and `out1` are the same). Note `unsqueeze_`

**Comment by heitorschueroff** [comment]
I removed the lines `b_self.suggest_memory_format()` added by this PR and `torch.lerp(values_below, values_above, weights, out=out.unsqueeze(-1).transpose_(0, -1).squeeze_(0))` worked the same as when using unsqueeze_. But as you said, maybe the current version is how it should be and I was just lucky before. 

I changed my code to work with the current version so if there's no need to change it if it's working correctly.

**Comment by ngimel** [comment]
That's weird, 
1) colab with pytorch 1.6 produces different `out` and `out1` here https://colab.research.google.com/drive/1lG4h5_ti9SiZcPKElJDFnpqcLxzFT_XN#scrollTo=LpxNXGZQlsic
2) If you send in tensor with the correct size, resize_as_ does nothing, regardless of requested memory type
3) suggest_memory_format will never return anything other than contiguous for a 3d tensor, which would also be the resize_as_ behavior before this PR.

**Comment by heitorschueroff** [comment]
The problem is not that out and out1 are different, that is ok. The problem is that in 1.6 out was correctly computed as 

```
tensor([[[0., 0., 0., 0., 1., 0., 1., 1.]],

        [[4., 4., 4., 4., 4., 4., 4., 3.]]], device='cuda:0')
```

But with the introduction of this PR, the result from the colab would be

```
tensor([[[0., 4., 0., 4., 0., 4., 0., 4.]],

        [[1., 4., 0., 4., 1., 4., 1., 3.]]], device='cuda:0')
```

**Comment by ngimel** [comment]
Oh, thank you, you are right! Yes, this is wrong behavior, normally if out is correct size, we should not change its strides, and now we make it contiguous:
```
In [36]: out=torch.empty([2,1,8], device="cuda")                                                                                                                                          

In [37]: out_1=out.unsqueeze(-1).transpose(0, -1).squeeze(0)                                                                                                                              

In [38]: out_1.is_contiguous()                                                                                                                                                            
Out[38]: False

In [39]: out_1.stride()                                                                                                                                                                   
Out[39]: (8, 1, 8)

In [40]: out_1.size()                                                                                                                                                                     
Out[40]: torch.Size([1, 8, 2])

In [41]: torch.lerp(vals, values_above, weights, out=out_1)                                                                                                                               
Out[41]: 
tensor([[[0., 4.],
         [0., 4.],
         [0., 4.],
         [0., 4.],
         [1., 4.],
         [0., 4.],
         [1., 4.],
         [1., 3.]]], device='cuda:0')

In [42]: out_1.size()                                                                                                                                                                     
Out[42]: torch.Size([1, 8, 2])

In [43]: out_1.is_contiguous()                                                                                                                                                            
Out[43]: True

In [44]: out_1.stride()                                                                                                                                                                   
Out[44]: (16, 2, 1)

```
We should change resize_/resize_as_ implementation to respect that, but in the meantime, can you please remove `suggest_memory_format` from lerp?

**Comment by heitorschueroff** [comment]
Sure, I'll remove it.

**Comment by xwang233** [comment]
@heitorschueroff thanks for the test! I remember the `resize` with `suggest_memory_format()` was supposed to fix the test when input tensor is `channels_last`, so I changed them. If we simply remove them, I'm not sure if output will still be `channels_last`. 

@ngimel I think the problem with `out=` is that, what are we expecting from `out=some_tensor`? Should we respect the size and strides of `some_tensor` passed in by user, or should we just take `some_tensor` as an empty python variable and assign a new output tensor to it?

I remember there was a similar discussion here https://github.com/pytorch/pytorch/issues/41027,

**Comment by heitorschueroff** [comment]
@xwang233 I believe the intent is to move away from resizing output tensors unless it is empty (x.numel() == 0) as described here https://github.com/pytorch/pytorch/pull/42079.

**Comment by ngimel** [comment]
What are shape requirements for the `result` tensor here? Can TensorIterator figure out what size it should be? If so, then you should not resize it in the lerp functions, and let TensorIterator handle it.

**Pull request closed without merging**
