### PR TITLE
[FakeTensor] Workaround FFT ops with incorrect meta strides

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #106631
* #106400
* __->__ #106319

Currently there are FFT operators which raise `UnsupportedOperatorException` 
because their meta implementations sometimes give incorrect strides. This works
around the problem for static shapes by falling back to eager. Though we still
don't support calls with dynamic shapes.

### CODE REVIEW

**Comment by lezcano** [comment]
@Chillee or @ezyang can review this one.

**Review by ezyang — APPROVED** [review]
Are you planning to also fix the meta?

**Review by eellison — COMMENTED** [review]
I thought these were fixed here. https://github.com/pytorch/pytorch/pull/103616 Or at least, for the opinfos the fft ops now pass stride checks. cc @nkaretnikov 

Is this still necessary ?

**Comment by peterbell10** [comment]
@eellison that PR only touches complex-to-complex transforms, with real-to-complex and complex-to-real still being incorrect. That includes calling `torch.fft.fft` with a real input tensor.

Regarding #103616, this PR doesn't apply to `aten._fft_c2c` because it's excluded from the `stride_incorrect_op` check. However, as I [mentioned before](https://github.com/pytorch/pytorch/pull/103616#discussion_r1237295970), that meta function is still incorrect for CUDA transforms with more than 3 dimensions. However, you couldn't really write that as a meta function since it depends on the device type. In general you would need a fake tensor op that basically reproduces most of the FFT implementation to get it correct in all cases.

Another option that would trade of some runtime performance would be to have inductor use the out variant for these ops. That does cost an extra copy, but at least it would never fail the stride check.

**Comment by eellison** [comment]
We do have existing precedent for device-specific logic in meta kernels, e.g. [here](https://github.com/pytorch/pytorch/blob/main/torch/_meta_registrations.py#L3078-L3084). It doesn't need to be in fake tensor. Ultimately we should fix and add the registrations there. I know it would be a pain to replicate but perhaps a little bit easier with the aid of chat-gpt. 

Filed https://github.com/pytorch/pytorch/issues/106622 for not having sufficient opinfos to exercise the four dim case. 

cc @nkaretnikov

**Comment by eellison** [comment]
Also, I would have expected this pr to fix https://github.com/pytorch/pytorch/blob/main/test/inductor/test_torchinductor_opinfo.py#L240-L257...

**Comment by peterbell10** [comment]
> Also, I would have expected this pr to fix https://github.com/pytorch/pytorch/blob/main/test/inductor/test_torchinductor_opinfo.py#L240-L257...

Hrm you're right, those tests pass locally whether I put the xfail there or not. Looks like xpass is broken.

**Pull request closed without merging**
