### PR TITLE
Created docs (and example) for cudart function in torch.cuda 

### LINKED ISSUE #127908: Document the torch.cuda.cudart function
Document the `torch.cuda.cudart` function located in [https://github.com/pytorch/pytorch/blob/main/torch/cuda/__init__.py#L318](https://github.com/pytorch/pytorch/blob/main/torch/cuda/__init__.py#L318).
Follow the [Docstring Guidelines](https://github.com/pytorch/pytorch/wiki/Docstring-Guidelines).

cc @brycebortree

### PR DESCRIPTION
**Pull request by ignaciobartol**
Fixes #127908

## Description

Created docs to document the torch.cuda.cudart function to solve the issue #127908. 
I tried to stick to the [guidelines to document a function](https://github.com/pytorch/pytorch/wiki/Docstring-Guidelines#documenting-a-function) but I was not sure if there is a consensus on how to handle the docs of a function that calls an internal function. So I went ahead and tried what the function will raise, etc. from the user endpoint and documented it (i.e. I am giving what actually _lazy_init() will raise).  

Updated PR from #128298 since I made quite a big mistake in my branch. I apologize for the newbie mistake. 

### Summary of Changes

- Added docs for torch.cuda.cudart
- Added the cudart function in the autosummary of docs/source/cuda.rst

## Checklist 
- [X] The issue that is being fixed is referred in the description
- [X] Only one issue is addressed in this pull request
- [X] Labels from the issue that this PR is fixing are added to this pull request
- [X] No unnecesary issues are included into this pull request

cc @svekars @brycebortree @msaroufim

### CODE REVIEW

**Comment by msaroufim** [comment]
Cool! This is looking much better, although I tried to run this and didn't seem to get an interesting output

Screenshot 2024-06-14 at 3 23 25 PM

**Comment by ignaciobartol** [comment]
> Cool! This is looking much better, although I tried to run this and didn't seem to get an interesting output
> 
> Screenshot 2024-06-14 at 3 23 25 PM

Thanks @msaroufim for reviewing this again! When I run it I was getting something like this and a sqlite file named trace_name.prof. I will further investigate why this may happening since it does not seem that the NVPROF profiling process even started in your run.
Screenshot 2024-06-14 at 6 35 07 PM
Screenshot 2024-06-14 at 6 35 14 PM

**Review by msaroufim — APPROVED** [review]

**Pull request closed without merging**
