### PR TITLE
remove ipex backend

### PR DESCRIPTION
**Pull request by jiayisunx**
Move IPEX backend from PyTorch to IPEX.

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @ipiszy @chenyang78

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by nelsonspbr** [comment]
> Move IPEX backend from PyTorch to IPEX.
What does this mean? There is no more "support" for IPEX in PyTorch Compile and instead we should use [IPEX](https://github.com/intel/intel-extension-for-pytorch) directly?

**Comment by jgong5** [comment]
> > Move IPEX backend from PyTorch to IPEX.
> 
> What does this mean? There is no more "support" for IPEX in PyTorch Compile and instead we should use [IPEX](https://github.com/intel/intel-extension-for-pytorch) directly?

The support is the same for the usage of `torch.compile` with IPEX backend. We just moved it outside pytorch and host it inside IPEX. It is to align the suggestion from PyTorch to maintain third-party backends out of the tree. From users' perspective, it is almost the same except that one more line of importing IPEX is needed now.
```python
import intel_extension_for_pytorch as ipex # this is the added line

compiled_model = torch.compile(your_eager_model, backend="ipex")
```

**Comment by nelsonspbr** [comment]
I see. I tried a couple things and realized I can only use IPEX as a compile backend if I stick to the stable version of both libraries. If I use the nightly PyTorch and/or build IPEX from source I run into errors. Thanks @jgong5 for your help.

**Comment by jgong5** [comment]
> I see. I tried a couple things and realized I can only use IPEX as a compile backend if I stick to the stable version of both libraries. If I use the nightly PyTorch and/or build IPEX from source I run into errors. Thanks @jgong5 for your help.

Oh, the latest IPEX mainline should match the nightly PyTorch on daily basis. If there is an error, it is a bug that we should fix. Are you seeing compilation errors or runtime errors? cc @chuanqi129

**Pull request closed without merging**
