### PR TITLE
Revert "Revert "[LT] Store OpKind for each IR subclass in a static field""

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #77102

Summary: Re-land https://github.com/pytorch/pytorch/pull/76711 by fixing internal failures

Differential Revision: [D36264219](https://our.internmc.facebook.com/intern/diff/D36264219)

### CODE REVIEW

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36264219).

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36264219).

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36264219).

**Review by wconstab — APPROVED** [review]

**Review by JackCaoG — APPROVED** [review]

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36264219).

**Comment by desertfire** [comment]
CC: @antoniojkim

**Review by antoniojkim — APPROVED** [review]
Thanks for addressing my comment!

**Pull request closed without merging**
