### PR TITLE
Mitigate flaky test_ops_fwd_gradients on macOS

### PR DESCRIPTION
**Pull request by huydhn**
This has been flaky on macOS for a while ([hud](https://hud.pytorch.org/failure/RuntimeError%3A%20test_ops_fwd_gradients%20failed)) and I can reproduce this locally. The issue was raised by https://github.com/pytorch/pytorch/issues/66033 and it seems to point to macos itself https://github.com/graphia-app/graphia/issues/33.  So switching to single thread when running `test_ops_fwd_gradients` on macOS as a mitigation for the flaky tests.

### Testing

`pytest test_ops_fwd_gradients.py -k test_fn_fwgrad_bwgrad -vv --flake-finder` to run all `test_fn_fwgrad_bwgrad` tests 50 times to make sure they all pass (no flaky anymore)

https://hud.pytorch.org/tests shows that `test_ops_fwd_gradients` on macOS takes about 15m to finish or 8 minute if using 2 shards like in the test.  There is no obvious difference in the test duration:

```
2022-11-21T21:34:18.6078080Z Running test_ops_fwd_gradients ... [2022-11-21 21:34:18.600663]
2022-11-21T21:34:21.6805770Z Executing ['/Users/runner/work/_temp/conda_environment_3517515737/bin/python', '-bb', 'test_ops_fwd_gradients.py', '-v', '--use-pytest', '-vv', '-rfEX', '-x', '--reruns=2', '--shard-id=0', '--num-shards=2', '-k=not _linalg_cholesky_', '--import-slow-tests', '--import-disabled-tests'] ... [2022-11-21 21:34:21.680156]
2022-11-21T21:34:21.6806380Z Ignoring disabled issues:  []
2022-11-21T21:34:21.6815250Z Executing ['/Users/runner/work/_temp/conda_environment_3517515737/bin/python', '-bb', 'test_ops_fwd_gradients.py', '-v', '--use-pytest', '-vv', '-rfEX', '-x', '--reruns=2', '--shard-id=1', '--num-shards=2', '-k=not _linalg_cholesky_', '--import-slow-tests', '--import-disabled-tests'] ... [2022-11-21 21:34:21.681174]
2022-11-21T21:34:21.6815830Z Ignoring disabled issues:  []
.....
2022-11-21T21:40:42.2422700Z =============================== warnings summary ===============================
.....
2022-11-21T21:40:42.2424670Z - generated xml file: /Users/runner/work/pytorch/pytorch/test/test-reports/python-pytest/test_ops_fwd_gradients/test_ops_fwd_gradients-47b619449ea7db1f.xml -
2022-11-21T21:40:42.2424850Z = 831 passed, 596 skipped, 5 deselected, 17 xfailed, 1 warning in 374.54s (0:06:14) =
.....
2022-11-21T21:42:00.1923310Z =============================== warnings summary ===============================
.....
2022-11-21T21:42:00.1925370Z - generated xml file: /Users/runner/work/pytorch/pytorch/test/test-reports/python-pytest/test_ops_fwd_gradients/test_ops_fwd_gradients-d24ee6419a602a6e.xml -
2022-11-21T21:42:00.1925540Z = 828 passed, 603 skipped, 7 deselected, 20 xfailed, 1 warning in 452.94s (0:07:32) =
....
2022-11-21T21:42:09.9035670Z FINISHED PRINTING LOG FILE of test_ops_fwd_gradients (/Users/runner/work/pytorch/pytorch/test/test-reports/test_ops_fwd_gradients_ha_3rfhb)
```

### CODE REVIEW

**Comment by soulitzer** [comment]
dumb question: how were you able to know that the ones failing on hud is failing for the same reason as described in the issue? I looked through a couple of them but could not find the message:`terminating with uncaught exception of type std::__1::system_error: condition_variable wait failed: Invalid argument`

**Comment by huydhn** [comment]
> dumb question: how were you able to know that the ones failing on hud is failing for the same reason as described in the issue? I looked through a couple of them but could not find the message:`terminating with uncaught exception of type std::__1::system_error: condition_variable wait failed: Invalid argument`

Well, it's a bit tricky to reproduce this on the CI. All I get are [SIGSEGV](https://paste.sh/LmzPRbga#W6lQZXw9qnY2B3UMkctyQ0pe) or [SIGBUS](https://paste.sh/1-v1xi0x#UcU9wBgdFD3ZM9NGA-9Vz8CU).  So I try to run all `test_fn_fwgrad_bwgrad` tests in `test_ops_fwd_gradients.py`  multiple times with `pytest test_ops_fwd_gradients.py -k test_fn_fwgrad_bwgrad -vv --flake-finder` and sometimes end up with that error:

```
libc++abi: terminating with uncaught exception of type std::__1::system_error: condition_variable wait failed: Invalid argument
Fatal Python error: Aborted

Thread 0x000000028ad13000 (most recent call first):
<no Python frame>

Thread 0x000000016e997000 (most recent call first):
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/socket.py", line 293 in accept
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pytest_rerunfailures.py", line 429 in run_server
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/threading.py", line 917 in run
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/threading.py", line 937 in _bootstrap

Thread 0x0000000102ad0580 (most recent call first):
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/autograd/__init__.py", line 300 in grad
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/autograd/gradcheck.py", line 1569 in new_func
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/autograd/gradcheck.py", line 1048 in wrapped_fn
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/autograd/gradcheck.py", line 348 in _get_analytical_jacobian_forward_ad
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/autograd/gradcheck.py", line 1303 in _fast_gradcheck
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/autograd/gradcheck.py", line 1093 in _gradcheck_real_imag
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/autograd/gradcheck.py", line 1432 in _gradcheck_helper
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/autograd/gradcheck.py", line 1418 in gradcheck
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/autograd/gradcheck.py", line 1574 in gradgradcheck
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 3432 in gradgradcheck
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 3811 in _check_helper
  File "/Users/huydo/Storage/mine/pytorch/test/test_ops_fwd_gradients.py", line 26 in test_fn_fwgrad_bwgrad
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 828 in test_wrapper
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 378 in instantiated_test
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/unittest/case.py", line 550 in _callTestMethod
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/unittest/case.py", line 592 in run
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2121 in _run_with_retry
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2183 in run
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 438 in run
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/unittest/case.py", line 651 in __call__
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/unittest.py", line 330 in runtest
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/runner.py", line 167 in pytest_runtest_call
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/runner.py", line 260 in <lambda>
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/runner.py", line 339 in from_call
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/runner.py", line 259 in call_runtest_hook
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/runner.py", line 220 in call_and_report
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/runner.py", line 131 in runtestprotocol
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/runner.py", line 112 in pytest_runtest_protocol
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/main.py", line 324 in _main
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/main.py", line 270 in wrap_session
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 167 in main
  File "/Users/huydo/miniconda3/envs/py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 190 in console_main
  File "/Users/huydo/miniconda3/envs/py3.9/bin/pytest", line 8 in <module>
```

Also the crash report from my local https://paste.sh/Ki6pwE2j#jBlEDEsQtsHxSEyaVG7Tvi7Z.  So it's a bit of a guesswork I think

**Review by soulitzer — APPROVED** [review]
Thanks!

**Pull request closed without merging**
