### PR TITLE
Assert that output could only be the last node of the FX graph

### PR DESCRIPTION
**Pull request by oulgen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #114973

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
LGTM!

**Comment by oulgen** [comment]
@suo let me do that as follow up on this PR. If I were to add lint compile_fx, @Chillee you mentioned the perf problems. So what would be a good way to add this?

One option is to add it under an inductor config flag and only enable this flag by default on tests (is there a way to do this?)

Any alternatives?

**Comment by Chillee** [comment]
We currently call it here most often I think: https://github.com/pytorch/pytorch/blob/main/torch/_functorch/partitioners.py#L104

**Comment by oulgen** [comment]
> We currently call it here most often I think: https://github.com/pytorch/pytorch/blob/main/torch/_functorch/partitioners.py#L104

Are you suggesting that is enough?

**Comment by oulgen** [comment]
Merged again as https://github.com/pytorch/pytorch/pull/115179

**Pull request closed without merging**
