### PR TITLE
add bf16 in fp32 out fast path for embedingbag in caffe2 perfkernel

### PR DESCRIPTION
**Pull request by zhuhaozhe**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89198

Add BF16 in FP32 out kernel into Caffe2 emb perfkernels. And also update the python code-gen files to generate the kernel.
The ut will be covered in the next PR(#89199) in this stack ( Tested by nn.EmbeddingBag with BF16 data type)

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
@zhuhaozhe I've approved and you should be able to merge now. But why are you updating caffe2, are you still using it? We don't really test caffe2 in CI anymore.

**Comment by zhuhaozhe** [comment]
> @zhuhaozhe I've approved and you should be able to merge now. But why are you updating caffe2, are you still using it? We don't really test caffe2 in CI anymore.

Thanks, @kit1980. We wish to add bf16 fast path for embedding bag and I see we use fp16 here (caffe2 perfkernel). So we may add bf16 support here the next PR in this stack will enable bf16 support and add bf16 UT for embeddingbag.

**Pull request closed without merging**
