### PR TITLE
BlasKernel: Improve gemm's inner dot product when a is transposed

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #80977

`gemm_transab_` accumulates the sum in the output, despite the inner
loop being over a single output element. This changes it to accumulate
in a register, which also avoids early truncation for bfloat16.

I've also factored out a generic `sum` function that can be shared
with `gemm_transa_` to handle unrolling and multiple accumulators.

I have benchmarked addmm for bfloat16 with shapes
(320,600) X (600,320) and for both layouts I see a significant
speedup.

|  layout  | Before (ms) | After (ms) |
|----------|-------------|------------|
| transa   | 71.5        | 31         |
| transab  | 249         | 35         |

### CODE REVIEW

**Comment by peterbell10** [comment]
@ngimel ping

**Comment by lezcano** [comment]
@ngimel PTAL

**Review by ngimel — APPROVED** [review]
LGTM, can you please settle the CLA thing and we can land?

**Pull request closed without merging**
