### PR TITLE
Fix autograd with buffers requiring grad in DataParallel

### PR DESCRIPTION
**Pull request by ssnl**
Causing a problem with spectral norm, although SN won't use that anymore after #13350 .

### CODE REVIEW

**Review by colesbury — COMMENTED** [review]
I'm a little confused. I'm not sure we want to allow buffers that have `requires_grad=True`. When we had split Tensor/Variable, buffers were Tensors so they could never require grad.

**Comment by SsnL** [comment]
@colesbury Yes, but we didn't enforce this at the time, and now there is code running in the wild that uses buffers that require grad already.

**Comment by soumith** [comment]
there is actually a subtle difference. We defined `buffers` as "not parameters", i.e. wont go into the optimizer. We didn't define `buffers` as "wont require grad"

**Review by colesbury — APPROVED** [review]
OK, I guess buffers are just "not parameters" and may or may not require grad.

Can you make sure that this doesn't affect the perf of say the imagenet model on multi-gpu?
https://github.com/pytorch/examples/tree/master/imagenet

**Pull request closed without merging**
