### PR TITLE
Do not call `get_implications` unnecessarily

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #128500
* #128411
* __->__ #128410

This should improve compilation times. With this PR and the patch in
the original issue, I get a compilation time of `Compilation time: 307.30 second`.

Fixes https://github.com/pytorch/pytorch/issues/128398

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
What actually causes the significant blowup in compile time in this case? i.e. why does it not show up in other cases?

**Comment by lezcano** [comment]
I haven't checked, but I think it does something like:
`0 <= si <= bi` for many constants `bi` and many shapes `si`. So when we try to simplify this, we end up asking, can we use the data for k = 1...i-1 to simplify `si`?
I saw this in the non-dynamic case, want me to check the dynamic case?

Ah, and we also had the nondeterminism of a set that was being cached as a tuple... oops

**Comment by Chillee** [comment]
> want me to check the dynamic case?

Yeah, it only slows down a lot if you add `dynamic=True`.

**Comment by lezcano** [comment]
So, the blow up happens because when we set `dynamic=True`, we end up with a good 4355 guards. Then, when trying to do inference with these guards, if one is not careful (i.e. before this PR) you end up generating 10k sympy expressions for every expression you want to check the truth value from (these are cached, but the cached is invalidated every time you add a new symbol...).

We could probably speed this up further by keeping a mapping from symbols to guards, similar to how we do it with unbacked symints, to avoid having to iterate the 4k guards every time, but I wonder how realistic this 4k guard scenario is...

**Comment by Chillee** [comment]
@lezcano this code is pretty natural 🤔 Why do we end up with so many guards?

**Comment by ezyang** [comment]
I'm kind of wondering if these "guards" are actually just the error checking from all the operators. Maybe we shouldn't try as hard to simplify error checking guards.

**Comment by lezcano** [comment]
You have 150 symbolic shapes in that model, that run through every operation. All these, as Ed mentions, come from the preconditions of all the operations executed in the model.
I guess don't see how making a model fully dynamic on every single dimension is a natural thing to do?

**Comment by Chillee** [comment]
I'm just calling torch.compile with dynamic=True. I'm surprised we end up with 150+ different symbols.

**Comment by lezcano** [comment]
`dynamic=True` creates a symbol for every shape it sees. In what sense is it surprising that we end up with 150 symbols?

**Comment by Chillee** [comment]
It should only be creating a symbol for dimensions on *inputs* it sees. I believe there should only be one non-weight input here.

Also, `dynamic=True` is the only (public) way to get dynamic shapes today in `torch.compile`. Is there any reason why `mark_dynamic` isn't a public API @ezyang ?

**Pull request closed without merging**
