### PR TITLE
[TS2E] Remove reference to torch.onnx internals

### PR DESCRIPTION
**Pull request by justinchuby**
Instead, this PR moves the code to the converter to avoid dependence. Feel free to refactor it afterward.

### CODE REVIEW

**Review by angelayi — APPROVED** [review]

**Comment by justinchuby** [comment]
I am not sure where IValue is defined? Or should I quote it? I tried `torch.jit.IValue`, `torch.IValue` and `torch._C.IValue`

**Comment by justinchuby** [comment]
> I am not sure where IValue is defined? Or should I quote it? I tried `torch.jit.IValue`, `torch.IValue` and `torch._C.IValue`

I quoted it. I was going to import annotations from future but not sure if that's the style preferred here.

**Pull request closed without merging**
