### PR TITLE
fix RowwiseMoments vectorization issue on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #81852
* #81851
* #84405
* __->__ #84404

Originally `cpu/moments_utils.h` uses namespace of at::native::utils,
this file contains `Vectorized<>`, in order to make it properly vectorized
on different archs, need to use anonymous namespace or inline namespace.
Otherwise it would be linked to scalar version of the code.

This PR is to fix vectorization issue from `RowwiseMoments` which is used to calculate `mean` and `rstd` in norm layers.
Attach benchmark data, generally fp32 will get 2-3x speedup and bf16 has larger speedup.

This patch will improves layer_norm (input size 32x128x1024) float32 inference:
* avx512 single socket: 2.1x
```bash
before: LayerNorm((1024,), eps=1e-05, elementwise_affine=True) : 32x128x1024: fp32: 0.439 ms; bf16: 2.479 ms
after:  LayerNorm((1024,), eps=1e-05, elementwise_affine=True) : 32x128x1024: fp32: 0.210 ms; bf16: 0.770 ms
```
* avx512 single core: 3.2x
```bash
before: LayerNorm((1024,), eps=1e-05, elementwise_affine=True) : 32x128x1024: fp32: 6.308 ms; bf16: 39.765 ms
after:  LayerNorm((1024,), eps=1e-05, elementwise_affine=True) : 32x128x1024: fp32: 2.661 ms; bf16: 12.267 ms
```
* avx2 single socket: 2.3x
```bash
before: LayerNorm((1024,), eps=1e-05, elementwise_affine=True) : 32x128x1024: fp32: 1.248 ms; bf16: 8.487 ms
after:  LayerNorm((1024,), eps=1e-05, elementwise_affine=True) : 32x128x1024: fp32: 0.540 ms; bf16: 2.030 ms
```
* avx2 single core: 2.5x
```bash
before: LayerNorm((1024,), eps=1e-05, elementwise_affine=True) : 32x128x1024: fp32: 10.792 ms; bf16: 66.366 ms
after:  LayerNorm((1024,), eps=1e-05, elementwise_affine=True) : 32x128x1024: fp32: 4.349 ms; bf16: 19.252 ms
```

Attached some original VTune profiling results here to further indicate the issue:

1. original bottlenecks
master_bottleneck

we can see `RowwiseMomentsImpl<>` takes majority of the runtime here.

2. Instruction level breakdown of `RowwiseMomentsImpl<>`
rowwise_momentum_impl

we can see it's all **scalar** instructions here.

3. after the fix, the bottlenecks
fixed_bottleneck

getting better.

4. after the fix, Instruction level breakdown of `RowwiseMomentsImpl<>`
fixed_rowwsie_momentum_impl

now it is all **vectorized** instructions.

cc @VitalyFedyunin @jgong5 @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by mingfeima** [comment]
replacement of https://github.com/pytorch/pytorch/pull/81849.

**Comment by mingfeima** [comment]
since https://github.com/pytorch/benchmark/issues/1099 has been identifies as false alarm, shall we proceed to review this PR again? @malfet, @frank-wei

**Review by malfet — CHANGES_REQUESTED** [review]
Hmm, `inline namespace` concept seems dangerous to me, as I'm not sure I understand how  it will guarantee that symbols from say `avx512` namespace will not get included from `avx2` -only code? Perhaps you just need to add a regular namespace and call `utils::CPU_CAPABILITY::RowwiseMoments`?

**Comment by mingfeima** [comment]
> Hmm, `inline namespace` concept seems dangerous to me, as I'm not sure I understand how it will guarantee that symbols from say `avx512` namespace will not get included from `avx2` -only code? Perhaps you just need to add a regular namespace and call `utils::CPU_CAPABILITY::RowwiseMoments`?

Initially, all the CPU kernels under [aten/src/ATen/native/cpu](https://github.com/pytorch/pytorch/tree/master/aten/src/ATen/native/cpu) which requires vectorization uses anonymous namespaces, which will make the func static and linked to different assembly for scalar/avx2/avx512. For example, like the [CatKernel](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/CatKernel.cpp) here.

Later on some kernels are changed to use inline namespace, for example, like this one: [CopyKernel](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/CopyKernel.cpp#L13). Sure this will also do the job, but honestly I'm not sure why this is introduced at the first place ...

@malfet Is it OK I change this file back to `anonymous namespaces` ? Right now, most of the CPU kernels are still written in this way.

**Review by jgong5 — CHANGES_REQUESTED** [review]
> Hmm, `inline namespace` concept seems dangerous to me, as I'm not sure I understand how it will guarantee that symbols from say `avx512` namespace will not get included from `avx2` -only code? Perhaps you just need to add a regular namespace and call `utils::CPU_CAPABILITY::RowwiseMoments`?

> Later on some kernels are changed to use inline namespace, for example, like this one: [CopyKernel](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/CopyKernel.cpp#L13). Sure this will also do the job, but honestly I'm not sure why this is introduced at the first place ...

My understanding is that inline namespace is preferred for functions defined in the header files (e.g., the moment_utils.h in this PR). With this, there won't be duplicated definitions for source files including it. For functions defined in source files, using anonymous namespace should be fine and seems most of the PyTorch source files follow this. The CopyKernel seems like an exception since the functions (e.g., `direct_copy_kernel`) of CopyKernel are also exposed directly in the header file  and used by other kernels. I would suggest we use inline namespace for moment_utils.h.

**Comment by mingfeima** [comment]
@jgong5 updated, change back to `inline namespace`

**Review by jgong5 — APPROVED** [review]

**Pull request closed without merging**
