### PR TITLE
[Dynamo] Remove ignored modes from torch function mode stack guard

### PR DESCRIPTION
**Pull request by mlazos**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135503
* #135502
* #135422
* #135444
* #135443
* #133137
* #134732

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]

**Comment by mlazos** [comment]
pytorchbot merge -i

**Pull request closed without merging**
