### PR TITLE
[ONNX] disable size optimizations for onnx

### PR DESCRIPTION
**Pull request by BowenBao**
Reviving this PR #35401 @eellison. I believe after the profiled graph executor fix the test failures are handled.

### CODE REVIEW

**Comment by eellison** [comment]
PR looks fine but it looks like in a separate PR we're adding more constant propagation at export time of shape information - https://github.com/pytorch/pytorch/pull/35386/ . I would image we don't want both this PR & that one too land.

**Comment by BowenBao** [comment]
@eellison the ONNX constant folding is different, the scope is smaller. Since it is export time optimization, we can only fold things that we know won't change, thus only constant nodes are folded. e.g. onnx::Constant[value_t=...]. The jit optimization here happens for any tensor with shape info.

**Comment by eellison** [comment]
> @eellison the ONNX constant folding is different, the scope is smaller. Since it is export time optimization, we can only fold things that we know won't change, thus only constant nodes are folded. e.g. onnx::Constant[value_t=...]. The jit optimization here happens for any tensor with shape info.

So the traced graph for the example looks like:
```
graph(%self : __torch__.ShapeModule,
      %x : Double(2, 5)):
  %9 : Tensor = prim::GetAttr[name="weight"](%self)
  %4 : int = prim::Constant[value=0]() # test/test_jit.py:11115:0
  %5 : int = aten::size(%9, %4) # test/test_jit.py:11115:0
  %shape : Long() = prim::NumToTensor(%5)
  %7 : int = prim::Constant[value=1]() # test/test_jit.py:11116:0
  %8 : Double(2, 5) = aten::add(%x, %shape, %7) # test/test_jit.py:11116:0
  return (%8)
```

how does the %9 : Tensor = prim::GetAttr(...) get lowered ?

**Review by eellison — APPROVED** [review]
LGTM

**Pull request closed without merging**
