### PR TITLE
[DataPipe] Fixing `map` function signature validation

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #84279

As @pmeier [points out](https://github.com/pytorch/pytorch/pull/80267#discussion_r958423241), #80267 introduces a bug where an exception is thrown when a built-in function (or a function implemented in C) is used with `.map` because `inspect.signature(fn)` cannot find the function's signature.

This PR skips over a function when its signature cannot be found. I believe this case is rare, and if the `fn` is truly incompatible with the usage of `input_col`/`output_col`, an exception will be raised at run time such that users will be able to examine what is wrong.

### CODE REVIEW

**Review by pmeier — APPROVED** [review]
Thanks Kevin for the quick fix. LGTM, if CI is green.

**Comment by NivekT** [comment]
Build failure unrelated (the `master` branch will be fixed soon). Will land tomorrow.

**Review by janeyx99 — APPROVED** [review]

**Comment by janeyx99** [comment]
Approving to unblock, but modifying the merge rules to move the Core maintainers rule to last would be a good idea.

**Pull request closed without merging**
