### PR TITLE
Remove .item calls from indexing

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #84159
* #84322
* #84114

### CODE REVIEW

**Comment by ngimel** [comment]
Is it doing the same thing as previous code?

**Comment by Chillee** [comment]
@ngimel Well, I thought it was the same, but a bunch of tests are failing so maybe not 🤔 

I thought that this was just an optimization for the case where we're indexing with a tensor that happens to be a scalar.

**Comment by ngimel** [comment]
Yeah it's likely crazy behavior where you can do slicing on non-adjacent dimensions, but advanced indexing has to be on adjacent dimensions, and is permuted if it isn't. Oh well.

**Comment by Chillee** [comment]
Abandoning this PR for now as this change substantially worsens performance of the `x[torch.tensor(5)]` and `x[torch.tensor(False)]` cases. Fixing it would probably require either adding a fast path to `index.Tensor` or expanding `slice` to take in a tensor for the shape as well.

**Pull request closed without merging**
