### PR TITLE
Fix attribution of some CUDA events to CPU events

### PR DESCRIPTION
**Pull request by ilia-cher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#51632 Fix attribution of some CUDA events to CPU events**
* #51561 [profiler] Default activities value

Summary:
Some fixes:
 - attribute CUDA Runtime events to proper PyTorch CPU events
 - make sure we don't accidentally attribute some CUDA kernels to the
 CUDA Runtime events that have semantically different ids
 - minor fixes in the output

Test Plan:
CI
https://gist.github.com/ilia-cher/0e78d0440fe02b77ff6721571c14f01c
https://gist.github.com/ilia-cher/8f655cf15beb1b11547fd3564a1c3958

Differential Revision: [D26222734](https://our.internmc.facebook.com/intern/diff/D26222734)

### CODE REVIEW

**Comment by ilia-cher** [comment]
@gdankel for review too

**Comment by ilia-cher** [comment]
cc. @gateng-git

**Comment by gdankel** [comment]
OK so part of the issue was that we treated both levels of correlation IDs the same?

**Comment by ilia-cher** [comment]
> OK so part of the issue was that we treated both levels of correlation IDs the same?

yes, these are different ids though their ranges may overlap after profiler runs for a long time

**Pull request closed without merging**
