### PR TITLE
lr_sche_update_OneCycle

### PR DESCRIPTION
**Pull request by davidfrz**
Fixes #{issue number}
origin lr_scheduler.pyi does not have the class "OneCycleLR", so I add that class.

### CODE REVIEW

**Comment by soulitzer** [comment]
Thanks for the fix! If you sign CLA + rebase, it should be good to go.

If you want you can also add the pyi for MultiplicativeLR class which seems to also be missing

**Comment by davidfrz** [comment]
Thanks for your reply, and I have signed the CLA+.

**Comment by davidfrz** [comment]
I  find I closed this just issue[555555555]

**Comment by soulitzer** [comment]
Hey, sorry for the delay!
We probably need to rebase this before it can land. Since the tests seem to failing due to a merge conflict.

**Comment by cowwoc** [comment]
Guys, can you please merge this change?

**Comment by davidfrz** [comment]
> Guys, can you please merge this change?

I cannot merge this one, something goes wrong but I dont know where.

**Comment by cowwoc** [comment]
Actually I think this PR will be superseeded by https://github.com/pytorch/pytorch/pull/43089

**Pull request closed without merging**
