### PR TITLE
Add decompositions for replication_pad

### LINKED ISSUE #115395: Deterministic decomp for `replication_pad_1d/3d`
#111590 added a decomp for `replication_pad_2d` that gets called on CUDA tensors when deterministic mode is turned on, in order to make the backward function deterministic. However, the implementation should be modified to support any number of dimensions so that `replication_pad_1d` and `replication_pad_3d` can use it as well, since they are still nondeterministic for CUDA backward

cc @mruberry

### PR DESCRIPTION
**Pull request by isuruf**
Fixes #115395

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #115101
* __->__ #115113

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by peterbell10 — APPROVED** [review]

**Comment by isuruf** [comment]
Benchmark
```
[----------------- replicate_pad ------------------]
                             |  Decomposed  |  Eager
32 threads: ----------------------------------------
      (3, 5, 1000000)        |     432      |   419 
      (3, 5, 1000, 1000)     |     434      |   430 
      (3, 5, 100, 100, 100)  |     450      |   642 
```

<details>

```python
import torch
from torch.testing import make_tensor
from torch.fx.experimental.proxy_tensor import make_fx
from torch.utils.benchmark import Timer, Compare
from torch._inductor.compile_fx import compile_fx_inner, cudagraphify_impl
from torch._inductor.decomposition import decompositions
from itertools import product
from functools import partial
aten = torch.ops.aten

torch._logging.set_logs(output_code=True)

benchmark_name = "replicate_pad"
Ss = [[3, 5, 1000000], [3, 5, 1000, 1000], [3, 5, 100, 100, 100]]


def gen_inputs():
    for shape in Ss:
        up_shape = shape[:2] + [s+2 for s in shape[2:]]
        yield [torch.randn(shape, dtype=torch.float32, device="cuda"), torch.randn(up_shape, dtype=torch.float32, device="cuda")]

def benchmark(label, f, x, grad):
    return Timer("f([x, grad])",
                 globals=locals(),
                 label=benchmark_name,
                 description=label,
                 sub_label=f"{tuple(x.shape)}",
                 num_threads=torch.get_num_threads()).blocked_autorange(min_run_time=2)

def compare(args):
    x, grad_output = args
    print(f"{tuple(x.shape)}")
    if x.dim() == 3:
        aten_func = aten.replication_pad1d
    elif x.dim() == 4:
        aten_func = aten.replication_pad2d
    elif x.dim() == 5:
        aten_func = aten.replication_pad3d
    
    def f(args):
        x, grad_output = args
        val = aten_func(x, [1]*2*(x.dim() - 2))
        return (val,)

    decomposed = make_fx(f, decomposition_table=decompositions, tracing_mode="fake")(args)
    compiled_decomposed = compile_fx_inner(decomposed, args, cudagraphs=False)
    yield benchmark(f"Decomposed", compiled_decomposed, *args)

    # Just show the first two generated kernels
    #torch._logging.set_logs(output_code=False)

    cuda_f = cudagraphify_impl(f, args, static_input_idxs=tuple(range(len(args))))
    yield benchmark(f"Eager", cuda_f, *args)

results = []
for x in gen_inputs():
    for res in compare(x):
        results.append(res)

compare = Compare(results)
compare.trim_significant_figures()
compare.print()
```

</details>

**Pull request closed without merging**
