### PR TITLE
Enable frozen dataclasses in FSDP

### PR DESCRIPTION
**Pull request by nikonikolov**
Enables FSDP with frozen dataclasses. Previously if using frozen dataclasses, FSDP forward would fail with `dataclasses.FrozenInstanceError`:
```
Traceback (most recent call last):
  File "/scratch/nikolay_nikolov/.cache/bazel/_bazel_nikolay_nikolov/79bf5e678fbb2019f1e30944a206f079/execroot/barrel/bazel-out/k8-opt/bin/barrel/pipes/vlams/train.runfiles/barrel/barrel/pipes/vlams/pipe/vlam_training_module.py", line 8
8, in train_step
    model_output: transformers.modeling_outputs.CausalLMOutputWithPast = self._model(
  File "/scratch/nikolay_nikolov/.cache/bazel/_bazel_nikolay_nikolov/79bf5e678fbb2019f1e30944a206f079/execroot/barrel/bazel-out/k8-opt/bin/barrel/pipes/vlams/train.runfiles/pip-core_torch/site-packages/torch/nn/modules/module.py", line 
1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/nikolay_nikolov/.cache/bazel/_bazel_nikolay_nikolov/79bf5e678fbb2019f1e30944a206f079/execroot/barrel/bazel-out/k8-opt/bin/barrel/pipes/vlams/train.runfiles/pip-core_torch/site-packages/torch/nn/modules/module.py", line 
1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/nikolay_nikolov/.cache/bazel/_bazel_nikolay_nikolov/79bf5e678fbb2019f1e30944a206f079/execroot/barrel/bazel-out/k8-opt/bin/barrel/pipes/vlams/train.runfiles/pip-core_torch/site-packages/torch/distributed/fsdp/fully_shard
ed_data_parallel.py", line 847, in forward
    args, kwargs = _root_pre_forward(self, self, args, kwargs)
  File "/scratch/nikolay_nikolov/.cache/bazel/_bazel_nikolay_nikolov/79bf5e678fbb2019f1e30944a206f079/execroot/barrel/bazel-out/k8-opt/bin/barrel/pipes/vlams/train.runfiles/pip-core_torch/site-packages/torch/distributed/fsdp/_runtime_ut
ils.py", line 594, in _root_pre_forward
    return _root_cast_forward_input(state, module, args, kwargs)
  File "/scratch/nikolay_nikolov/.cache/bazel/_bazel_nikolay_nikolov/79bf5e678fbb2019f1e30944a206f079/execroot/barrel/bazel-out/k8-opt/bin/barrel/pipes/vlams/train.runfiles/pip-core_torch/site-packages/torch/distributed/fsdp/_runtime_ut
ils.py", line 612, in _root_cast_forward_input
    args, kwargs = _cast_forward_inputs(input_dtype, *args, **kwargs)
  File "/scratch/nikolay_nikolov/.cache/bazel/_bazel_nikolay_nikolov/79bf5e678fbb2019f1e30944a206f079/execroot/barrel/bazel-out/k8-opt/bin/barrel/pipes/vlams/train.runfiles/pip-core_torch/site-packages/torch/distributed/utils.py", line 
74, in _cast_forward_inputs
    return (_apply_to_tensors(cast_fn, args), _apply_to_tensors(cast_fn, kwargs))
  File "/scratch/nikolay_nikolov/.cache/bazel/_bazel_nikolay_nikolov/79bf5e678fbb2019f1e30944a206f079/execroot/barrel/bazel-out/k8-opt/bin/barrel/pipes/vlams/train.runfiles/pip-core_torch/site-packages/torch/distributed/utils.py", line 
255, in _apply_to_tensors
    return apply(container)
  File "/scratch/nikolay_nikolov/.cache/bazel/_bazel_nikolay_nikolov/79bf5e678fbb2019f1e30944a206f079/execroot/barrel/bazel-out/k8-opt/bin/barrel/pipes/vlams/train.runfiles/pip-core_torch/site-packages/torch/distributed/utils.py", line 
251, in apply
    return type(x)(apply(el) for el in x)
  File "/scratch/nikolay_nikolov/.cache/bazel/_bazel_nikolay_nikolov/79bf5e678fbb2019f1e30944a206f079/execroot/barrel/bazel-out/k8-opt/bin/barrel/pipes/vlams/train.runfiles/pip-core_torch/site-packages/torch/distributed/utils.py", line 
251, in <genexpr>
    return type(x)(apply(el) for el in x)
  File "/scratch/nikolay_nikolov/.cache/bazel/_bazel_nikolay_nikolov/79bf5e678fbb2019f1e30944a206f079/execroot/barrel/bazel-out/k8-opt/bin/barrel/pipes/vlams/train.runfiles/pip-core_torch/site-packages/torch/distributed/utils.py", line 
235, in apply
    setattr(dc, name, apply(getattr(dc, name)))
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'input_ids'
```

Happy for a developer to take over to merge the PR

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Comment by awgu** [comment]
Thanks for the PR!

I think ideally we want a unit test before we land this. cc: @weifengpy would you have bandwidth to help add a test?

**Comment by weifengpy** [comment]
> Thanks for the PR!
> 
>  @weifengpy would you have bandwidth to help add a test?

Yes, I can add a unit test and land this

**Comment by weifengpy** [comment]
added unit test in this PR: https://github.com/pytorch/pytorch/pull/135067

**Comment by Skylion007** [comment]
@XuehaiPan this may unblock you a bit, I remember you had some issues with frozen dataclasses failing.

**Comment by XuehaiPan** [comment]
> ```pytb
>   File "/scratch/nikolay_nikolov/.cache/bazel/_bazel_nikolay_nikolov/79bf5e678fbb2019f1e30944a206f079/execroot/barrel/bazel-out/k8-opt/bin/barrel/pipes/vlams/train.runfiles/pip-core_torch/site-packages/torch/distributed/utils.py", line 
> 235, in apply
>     setattr(dc, name, apply(getattr(dc, name)))
>   File "<string>", line 4, in __setattr__
> dataclasses.FrozenInstanceError: cannot assign to field 'input_ids'
> ```

@weifengpy For frozen dataclasses, you should use `replace` to create a new instance. If you want to modify the original instance (which is frozen), you will need to use `object.__setattr__(...)` rather than `setattr(...)`:

```diff
- setattr(dc, name, apply(getattr(dc, name)))
+ object.__setattr__(dc, name, apply(getattr(dc, name)))
```

**Pull request closed without merging**
