### PR TITLE
Add test to reinitialize pg after abort.

### PR DESCRIPTION
**Pull request by pritamdamania87**
Unit test seems to failing with:

```
[2023-06-20 19:30:18,212] torch.testing._internal.common_distributed: [ERROR] Caught exception: 
Traceback (most recent call last):
  File "torch/testing/_internal/common_distributed.py", line 657, in run_test
    getattr(self, test_name)()
  File "torch/testing/_internal/common_distributed.py", line 543, in wrapper
    fn()
  File "torch/testing/_internal/common_distributed.py", line 174, in wrapper
    return func(*args, **kwargs)
  File "torch/testing/_internal/distributed/distributed_test.py", line 9781, in test_nccl_init_abort
    torch.distributed.barrier(device_ids=[self.rank])
  File "torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "torch/distributed/distributed_c10d.py", line 3652, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1137, invalid usage, NCCL version 2.17.1
ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
Last error:

Exception raised from getNCCLComm at torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1137 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x1554fd0c1edc in torch/lib/libc10.so)
frame #1: <unknown function> + 0xcadb57 (0x1554fde39b57 in torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xea0056 (0x1554fe02c056 in torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::allreduce_impl(std::vector<at::Tensor, std::allocator<at::Tensor> >&, c10d::AllreduceOptions const&) + 0x35 (0x1554fe02d8e5 in torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::allreduce(std::vector<at::Tensor, std::allocator<at::Tensor> >&, c10d::AllreduceOptions const&) + 0x3f7 (0x1554fe02fa47 in torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::barrier(c10d::BarrierOptions const&) + 0xb10 (0x1554fe03f3b0 in torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x55336b6 (0x15550d1166b6 in torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x553c68f (0x15550d11f68f in torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x5550251 (0x15550d133251 in torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0xc38c56 (0x15551498ac56 in torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x3f5e2d (0x155514147e2d in torch/lib/libtorch_python.so)
```

Exception seems to be coming from this line: https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L1128

Full output with `NCCL_DEBUG=INFO`: https://gist.github.com/pritamdamania87/334e2920202a133e19457b530cbb62b8

### CODE REVIEW

**Comment by eqy** [comment]
CC @KaimingOuyang

**Comment by KaimingOuyang** [comment]
@pritamdamania87 May I know whether the `ncclCommAbort` is called by the thread that created the communicator or other threads which were spawned for aborting comm?

**Comment by KaimingOuyang** [comment]
OK, could you please try to use the same thread that creates the communicator to abort?

**Comment by pritamdamania87** [comment]
> OK, could you please try to use the same thread that creates the communicator to abort?

@KaimingOuyang This is not possible always since when NCCL kernels run into an error the main CPU thread gets stuck as well (due to some eventual d2h or h2d). The only way to recover the main thread is to abort the communicator from a separate thread.

**Comment by KaimingOuyang** [comment]
Got it. This different thread abort case is now not well supported by NCCL due to the complexity of multi-thread comm management in NCCL. However, it will be supported in NCCL 2.19.1 release.

**Comment by pritamdamania87** [comment]
> Got it. This different thread abort case is now not well supported by NCCL due to the complexity of multi-thread comm management in NCCL. However, it will be supported in NCCL 2.19.1 release.

@KaimingOuyang Thanks for the clarification, although I was wondering if you could elaborate in terms of the current support we have for aborting communicators from a different thread. I'm asking since PyTorch code has been doing this from a separate thread for years: https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L888. So my impression was that this was something well supported by NCCL. I'm wondering how the `abort` from the separate thread in https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L888 is different from the `abort` from a separate thread in the unit test of this PR.

**Comment by KaimingOuyang** [comment]
@pritamdamania87 Not really. As far as I remember, the previous abort seems to work but it has a possibility to cause segfault. It's just somehow not triggered. After we brought Fault Tolerance support since 2.14.1, we fixed the segfault issue but now need to support this different thread abort case.

**Comment by pritamdamania87** [comment]
> @pritamdamania87 Not really. As far as I remember, the previous abort seems to work but it has a possibility to cause segfault. It's just somehow not triggered. After we brought Fault Tolerance support since 2.14.1, we fixed the segfault issue but now need to support this different thread abort case.

Thanks a lot for the detailed explanation @KaimingOuyang! Was wondering what is the rough timeline for NCCL 2.19.1?

@kwen2501 You are probably already aware of this, was wondering if we have plans to properly support this in PyTorch once NCCL 2.19.1 is released?

**Comment by KaimingOuyang** [comment]
@pritamdamania87  I think it would be around the end of July or early Aug.

**Pull request closed without merging**
