### PR TITLE
Use isinstance test rather than exact type test for wrap to fake

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #89773
* #89672
* __->__ #89671
* #89670
* #89669
* #89736

I'm not sure why we did an exact test originally.  Let's find out!

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]

**Comment by ezyang** [comment]
Sooooooo it turns out this causes an accuracy failure on BERT_pytorch with dynamic shapes aot eager! None of our asserts trigger.

**Pull request closed without merging**
