### PR TITLE
[cuDNN][cuDNN Frontend] Bump cuDNN FE submodule to 1.5.2

### PR DESCRIPTION
**Pull request by eqy**
Some relevant fixes include stride-0 support 👀 

CC @drisspg @Skylion007 @vedaanta

cc @csarofeen @ptrblck @xwang233

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by clee2000** [comment]
@pytorchbot merge

Cancelled old merge job to fix something, reissuing merge command, sorry about that

**Pull request closed without merging**
