### PR TITLE
dbr quant: refactor first_call hooks to be standalone

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #71781 dbr quant function fusion [2/x]: use fusion for observation and inference
* #71780 fx quant: add fusion matching for operator.add and torch.relu
* #71764 dbr quant function fusion [1/x]: record matches for functions
* #71551 dbr quant: record dag of non-quantizeable ops
* **#71324 dbr quant: refactor first_call hooks to be standalone**
* #71312 dbr quant: rename seen_op_info to seen_q_op_info

Summary:

In a future PR we need to start recording the DAG
of non-quantizeable ops, in order to properly reason about
function fusion.

This PR refactors the prepare hooks to have the first_call
versions be separate functions.  This ensures that the logic
to record the DAG (the first_call functions) is separate
from the logic used at inference.

Test plan:

```
python test/test_quantization.py -k DBR
```

Differential Revision: [D33588558](https://our.internmc.facebook.com/intern/diff/D33588558)

### CODE REVIEW

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33588558).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33588558).

**Review by HDCharles — APPROVED** [review]
lgtm

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33588558).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33588558).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33588558).

**Pull request closed without merging**
