### PR TITLE
Fix the default value of side in torch.searchsorted

### LINKED ISSUE #119999: `searchsorted` confusing default arguments
### 📚 The doc issue

The docs for `torch.searchsorted` https://pytorch.org/docs/stable/generated/torch.searchsorted.html show a default argument of `side='left'`. They also state that `It will error if side is set to “left” while this is True` ("this" being `right`). 

However, something like this `torch.searchsorted(x, x, right=True)` will work, even though in this case `right=True` and `side` has its default value `left`. So shouldn't this fail, or am I missing something?

### Suggest a potential alternative/fix

_No response_

cc @svekars @brycebortree

### PR DESCRIPTION
**Pull request by lancerts**
Fixes #119999, currently the [doc](https://pytorch.org/docs/stable/generated/torch.searchsorted.html#torch.searchsorted) shows the default value of `side = "left"` 
Screenshot 2024-02-16 at 10 36 08 AM
while the [implementation ](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/native_functions.yaml#L11247) gives the default value of `side = c10::nullopt`.

- fix the [torch doc](https://github.com/pytorch/pytorch/blob/main/torch/_torch_docs.py#L13782) such that the default value of side is None.

- fix the [comment in cpp](https://github.com/pytorch/pytorch/blob/4dc75f9084b6c1ea063278797ee57e2533b5353d/aten/src/ATen/native/Bucketization.cpp#L19) such that the default value of side is None.

### CODE REVIEW

**Comment by lezcano** [comment]
This has BC-breaking implications so we won't be able to land it as-is. Can you instead change the docs?

**Review by malfet — CHANGES_REQUESTED** [review]
This feels wrong, we should update documentation instead see https://github.com/pytorch/pytorch/pull/120086

But running the test to see if something will fail (as I really hope we test for it)

**Comment by lancerts** [comment]
> This feels wrong, we should update documentation instead see #120086
> 
> But running the test to see if something will fail (as I really hope we test for it)

@malfet Thanks for the suggestion, totally agree.  Modified the change to doc only.

However, changed to `side=None` instead of `side: Optional[str] = None`. 

Or, we have to change out_int32, right, out and sorter in the docs as explicit optional to. 
Seem other methods in torch docs don't mark the args explicitly optional, for example, 
https://github.com/pytorch/pytorch/blob/main/torch/_torch_docs.py#L13865

Lmk

**Comment by malfet** [comment]
@lancerts if you are doing it anyway, do you mind just go over all functions in say Bucketization and update docs accordingly and document how you've verified the behavior in PR description (as right now it contradicts to what PR is actually doing)

**Comment by lancerts** [comment]
> @lancerts if you are doing it anyway, do you mind just go over all functions in say Bucketization and update docs accordingly and document how you've verified the behavior in PR description (as right now it contradicts to what PR is actually doing)

@malfet sure. 
1, Did a pass for bucketization cpp, h, doc, yaml, etc. There are no issues since `side` is not a function arg.

https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/native_functions.yaml#L11228

2, Updated the PR description to align with the changes.

3, Did a pass in torch doc. It seems the convention of the optional arg is to mark it as optional in the description (instead of in function API), for example in pooling as well:

https://github.com/pytorch/pytorch/blob/main/torch/_torch_docs.py#L13601.

Therefore, will follow this convention. Thanks

**Review by malfet — APPROVED** [review]
Looks good, thank you for the updates

**Pull request closed without merging**
