### PR TITLE
Unify caffe2 and libtorch build scripts on Windows

### PR DESCRIPTION
**Pull request by peterjc123**
`scripts/build_windows.bat` is the original way to build caffe2 on Windows, but since it is merged into libtorch, the build scripts should be unified because they actually do the same thing except there are some different flags.

The follow-up is to add the tests. Looks like the CI job for caffe2 windows is defined [here](https://github.com/pytorch/ossci-job-dsl/blob/master/src/jobs/caffe2.groovy#L906). Could we make them a separate file, just like what we've done in `.jenkins/pytorch/win-build.sh`? There's a bunch of things we can do there, like using ninja and sccache to accelerate build.

cc @orionr @yf225

### CODE REVIEW

**Comment by ezyang** [comment]
Didn't work, looks like?

```
15:26:44 ['cmake',
15:26:44  '-GVisual Studio 15 2017 Win64',
15:26:44  '-DBUILDING_WITH_TORCH_LIBS=ON',
15:26:44  '-DBUILD_BINARY=False',
15:26:44  '-DBUILD_CAFFE2_OPS=True',
15:26:44  '-DBUILD_PYTHON=False',
15:26:44  '-DBUILD_SHARED_LIBS=OFF',
15:26:44  '-DBUILD_TEST=True',
15:26:44  '-DBUILD_TORCH=ON',
15:26:44  '-DCAFFE2_STATIC_LINK_CUDA=False',
15:26:44  '-DCMAKE_BUILD_TYPE=Release',
15:26:44  '-DCMAKE_CXX_FLAGS=  /EHa',
15:26:44  '-DCMAKE_C_FLAGS=  /EHa',
15:26:44  '-DCMAKE_EXE_LINKER_FLAGS=',
15:26:44  '-DCMAKE_INSTALL_PREFIX=C:\\Jenkins\\workspace\\caffe2-builds\\py2-cuda9.0-cudnn7-windows-build/torch',
15:26:44  '-DCMAKE_PREFIX_PATH=C:\\Python37\\Lib\\site-packages',
15:26:44  '-DCMAKE_SHARED_LINKER_FLAGS=',
15:26:44  '-DCUDA_NVCC_EXECUTABLE=C:/Jenkins/workspace/caffe2-builds/py2-cuda9.0-cudnn7-windows-build/tmp_bin/nvcc',
15:26:44  '-DINSTALL_TEST=True',
15:26:44  '-DNCCL_EXTERNAL=False',
15:26:44  '-DONNX_ML=False',
15:26:44  '-DONNX_NAMESPACE=onnx_torch',
15:26:44  '-DPYTHON_EXECUTABLE=C:/Python37/python.exe',
15:26:44  '-DPYTHON_INCLUDE_DIR=C:/Python37/include',
15:26:44  '-DTHD_SO_VERSION=1',
15:26:44  '-DUSE_CUDA=True',
15:26:44  '-DUSE_DISTRIBUTED=False',
15:26:44  '-DUSE_FBGEMM=True',
15:26:44  '-DUSE_FFMPEG=False',
15:26:44  '-DUSE_LEVELDB=False',
15:26:44  '-DUSE_LMDB=False',
15:26:44  '-DUSE_MKLDNN=True',
15:26:44  '-DUSE_NCCL=False',
15:26:44  '-DUSE_NNPACK=True',
15:26:44  '-DUSE_NUMPY=False',
15:26:44  '-DUSE_OPENCV=False',
15:26:44  '-DUSE_QNNPACK=True',
15:26:44  '-DUSE_ROCM=False',
15:26:44  '-DUSE_SYSTEM_EIGEN_INSTALL=OFF',
15:26:44  '-DUSE_SYSTEM_NCCL=False',
15:26:44  '-DUSE_TENSORRT=False',
15:26:44  '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON',
15:26:44  'C:\\Jenkins\\workspace\\caffe2-builds\\py2-cuda9.0-cudnn7-windows-build']
15:26:44 Traceback (most recent call last):
15:26:44   File "tools\build_libtorch.py", line 22, in <module>
15:26:44     build_python=False, rerun_cmake=True, build_dir='.')
15:26:44   File "C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\tools\build_pytorch_libs.py", line 264, in build_caffe2
15:26:44     cwd=build_dir, env=my_env)
15:26:44   File "C:\Python37\lib\subprocess.py", line 323, in check_call
15:26:44     retcode = call(*popenargs, **kwargs)
15:26:44   File "C:\Python37\lib\subprocess.py", line 304, in call
15:26:44     with Popen(*popenargs, **kwargs) as p:
15:26:44   File "C:\Python37\lib\subprocess.py", line 756, in __init__
15:26:44     restore_signals, start_new_session)
15:26:44   File "C:\Python37\lib\subprocess.py", line 1155, in _execute_child
15:26:44     startupinfo)
15:26:44 FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by peterjc123** [comment]
@ezyang Fixed!

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
```
15:53:17 C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build\torch\lib /LIBPATH:C:\Jenkins\Miniconda3\libs /LIBPATH:C:\Jenkins\Miniconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" /LIBPATH:C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build\build\win_tmp\mkl\lib /LIBPATH:LIB shm.lib torch_python.lib /EXPORT:PyInit__C build\temp.win-amd64-3.6\Release\torch/csrc/stub.obj /OUT:build\lib.win-amd64-3.6\torch\_C.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\torch/csrc\_C.cp36-win_amd64.lib /NODEFAULTLIB:LIBCMT.LIB 
15:53:17 LINK : fatal error LNK1181: cannot open input file 'shm.lib'
15:53:17 error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
15:53:17 + assert_git_not_dirty
```

Not sure if this is spurious or not.

**Comment by ezyang** [comment]
restarted that job

**Comment by peterjc123** [comment]
@ezyang Fixed!

**Review by kostmo — APPROVED** [review]

**Pull request closed without merging**
