### PR TITLE
Remove BUILD_ATEN_ONLY build option

### LINKED ISSUE #21703: BUILD_ATEN_ONLY no longer works, due to missing caffe2.pb.h header
Steps to reproduce:

```
mkdir build
(cd build && cmake -DBUILD_ATEN_ONLY=ON -DBUILD_SHARED_LIBS=OFF -DUSE_CUDA=OFF -DUSE_MKLDNN=OFF -DPYTHON_EXECUTABLE=$(which python) ..)
```

we get:

```
[ 36%] Building CXX object caffe2/CMakeFiles/caffe2.dir/__/torch/csrc/jit/register_quantized_ops.cpp.o                          
In file included from /scratch/ezyang/pytorch-tmp/torch/csrc/jit/netdef_converter.h:2:0,                                        
                 from /scratch/ezyang/pytorch-tmp/torch/csrc/jit/netdef_converter.cpp:1:                                        
/scratch/ezyang/pytorch-tmp/caffe2/proto/caffe2_pb.h:4:10: fatal error: caffe2/proto/caffe2.pb.h: No such file or directory     
 #include <caffe2/proto/caffe2.pb.h>                                                                                            
          ^~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                            
compilation terminated.                                                                                                         
caffe2/CMakeFiles/caffe2.dir/build.make:4095: recipe for target 'caffe2/CMakeFiles/caffe2.dir/__/torch/csrc/jit/netdef_converter
.cpp.o' failed             
```

### PR DESCRIPTION
**Pull request by xuhdev**
This build option no longer works.

Close #21703

### CODE REVIEW

**Comment by xuhdev** [comment]
Best viewed with "Hide whitespace change" turned on

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
