### PR TITLE
Move `hasPrimaryContext` to `c10::cuda`

### PR DESCRIPTION
**Pull request by malfet**
This method has to be accessible from `c10` to enable CUDA-12 integration.
Implemented by providing private `c10::cuda:_internal::setHasPrimaryContext` that passes the pointer to the implementation (in `torch_cuda`) back to c10.
Use global class constructor/destructor to guarantee RAII.

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
Complaints about bzl file are real

**Comment by malfet** [comment]
Refactored PR to make it much smaller and avoid .bzl file changes

**Comment by ngimel** [comment]
cc @Aidyn-A, this should make set_device PR simpler

**Pull request closed without merging**
