### PR TITLE
Enable NCCL_DESYNC_DEBUG when TORCH_DISTRIBUTED_DEBUG=DETAIL

### PR DESCRIPTION
**Pull request by kwen2501**
Save users from setting multiple environment variables when they need to debug the program

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Thanks! Can we also add this to the documentation "debugging torch.distributed applications" in the main torch.distributed docpage. This might also require documenting NCCL_DESYNC_DEBUG in OSS first, which might need more discussions.

**Comment by kwen2501** [comment]
Sure, I can add some description in the doc in a separate PR.
The CI failure does not seem related. Merging this PR now.

**Review by malfet — CHANGES_REQUESTED** [review]
This PR modifies 137+ files. Why? (including macos-test, which should not be needed for NCCL build, should it?)

**Comment by kwen2501** [comment]
Closing this PR as upstream commits show up in the PR. Sorry about the inconvenience.

**Comment by weiwangmeta** [comment]
FYI, you could try using "@pytorchmergebot rebase" comment to get your PR rebased with main branch.

**Pull request closed without merging**
