### PR TITLE
Batch norm scale

### PR DESCRIPTION
**Pull request by fkemeth**
As discussed in #40087 , I added a bool `use_scale` in the respective batchnorm and instance norm functions .
If `affine` is `True` and `use_scale` is `False`, then `self.register_buffer('weight', None)`, just as if `affine` is `False`.

Another option would be to use `self.register_buffer('weight', torch.ones(num_features, requires_grad=False)`, but this wouldn't be so clean and add extra memory requirements I suppose.
Anyway, weight=None seems to be handled as 1 in the respective cpp function, as for the case `affine` = `False`.

I did run run_test.py, but I do get CUDA out of memory errors in some tests (those are the only errors I observed). I am not sure how to fix that (without buying a new graphics card). Do you have ideas how I can probably test the implementation? It seems one needs at least 2 GB of graphics card ram for the implemented cuda tests.

I did not add extra test scripts for the new batchnorm version, though.

I did just a brief test as follows, which shows the expected behavior:

``` python
import torch

bn = torch.nn.BatchNorm1d(num_features=3)

print(bn.weight)  # Parameter containing: tensor([1., 1., 1.], requires_grad=True)
print(bn.bias)    # Parameter containing: tensor([0., 0., 0.], requires_grad=True)

bn = torch.nn.BatchNorm1d(num_features=3, affine=True, use_scale=False)

print(bn.weight)  # None
print(bn.bias)    # Parameter containing: tensor([0., 0., 0.], requires_grad=True)

bn = torch.nn.BatchNorm1d(num_features=3, affine=False, use_scale=False)

print(bn.weight)  # None
print(bn.bias)    # None

m = torch.nn.Sequential(
    torch.nn.BatchNorm1d(3, use_scale=False)
)

m.eval()

x = torch.randn(5, 3)

y1 = m.forward(x)

y1_test = (x-m._modules['0'].running_mean)/torch.sqrt(m._modules['0'].running_var+m._modules['0'].eps) + \
    m._modules['0'].bias

assert torch.all(y1 == y1_test)  # True
```

### CODE REVIEW

**Comment by gchanan** [comment]
I'll let @mruberry make the call here, just registering that I prefer one parameter that controls behavior rather than having to work to get the right truth table value.  E.g. maybe we could support something like `affine = "scale"` or `affine = "scale_only"`.  I don't know how difficult it is to get the types right across JIT, mypi, though.

**Comment by mruberry** [comment]
Hey @fkemeth, thanks for the PR! Looks like there are still some tests to get through. I'm sorry running the CUDA test suite is challenging, maybe you can just run the specific tests that are failing? We support running specific tests using unittest-like syntax or you can use pytest. For example `python test_torch.py TestTorchDeviceTypeCPU.test_whatever_cpu.` The failing tests will always print which class they belong to and their names, so you can just concat those with a dot to run them alone.

As for the design of the PR, I agree with Greg's point that it's never nice when we have two kwargs that are so closely related. Would it be possible to reuse the `affine` kwarg, possibly by adding a new option for it like "translation_only"?

**Comment by fkemeth** [comment]
Hi @mruberry, @gchanan 
thank you for your suggestions. I agree that having two boolean arguments specifying if both scale and shift or only scale are used is not an elegant solution. However, I refrained from reusing `affine` because changing it would violate backward compatibility, wouldn't it? As it is right now,  `affine` is boolean. Potentially one could accept  `affine` as boolean or string, and if it is string then we could check if it is  `scale_only` or `scale_and_shift`. But I am not sure if this is in conflict with the cpp syntax, and if this is more elegant than having two boolean kwargs.

I checked how they implemented this feature in tensorflow - there they use two booleans `center` (if to use shift) and `scale` (if to use scale) to achieve this. 

Right now I favor two booleans, but its up to you. What do you think?

**Comment by gchanan** [comment]
scale and shift bools are nice, but also backwards incompatible.  What you were thinking with bools/string was along the lines I was thinking, but I'm not sure if we can make everything play nicely BC-wise; @mruberry is an expert on that though.

**Comment by fkemeth** [comment]
@gchanan what I meant is leaving `affine` as it is, and using an additional bool `use_scale`, which is `True` by default. This way it would be backwards compatible.

**Comment by mruberry** [comment]
I appreciate your thinking, and JAX also uses center and scale (https://jax.readthedocs.io/en/latest/jax.experimental.stax.html?highlight=batchnorm#jax.experimental.stax.BatchNorm), which seems fine. 

Some additional datapoints:
- Forum post 1 (https://discuss.pytorch.org/t/affine-parameter-in-batchnorm/6005/4)
- Forum post 2 (https://discuss.pytorch.org/t/could-i-simply-use-affine-false-to-bypass-a-batchnorm-layer/34895)
- Code search shows affine=False is actually used
- Apex issue demonstrating usage (https://github.com/NVIDIA/apex/issues/133)
- Related issue for InstanceNorm (https://github.com/pytorch/pytorch/issues/22755)
- TensorFlow documentation for InstanceNorm (https://www.tensorflow.org/addons/api_docs/python/tfa/layers/InstanceNormalization)
- Maybe we need a new Batchnorm API, anyway (https://github.com/pytorch/pytorch/issues/2628)

I don't think we have to solve all these issues or make every norm have the functionality to control centering and scaling separately with a single PR, either (although we should file a consistency issue - instancenorm having different defaults seems very odd). 

Now let's recap the two possible solutions:

- add "center" and "scale" keyword args, consistent with TensorFlow and JAX
- overload "affine" to take both bool and string arguments

I think both approaches are technically feasible without BC-compatibility issues. I think I have a slight preference for the "center" and "scale" approach, however. What if we did the following:

- add the "center" and "scale" kwargs
- make "affine," "center," and "scale" optional bools
- if none of these arguments are provided the behavior is identical to today
- if "affine" is provided the behavior is identical to today
- assert that if "affine" is provided neither "center" or "scale" are provided, and vice versa
- respect the "center" and "scale" flags, if set, like TensorFlow and JAX do

This effectively makes affine a shorthand for disabling both centering and scaling, which seems OK. It should also avoid actual deprecation issues, which should probably reviewed with the possible change from BatchNormXd->BatchNorm API.

What are your thoughts, @fkemeth?

**Comment by ngimel** [comment]
I don't think that this pretty involved API change is worth doing. The behavior can be achieved today by either using "affine=None" and manually adding bias after the bn layer, or setting `requires_grad_=False` to BatchNorm weight. It has been a long standing pytorch philosophy to enable users to do what they want rather than explicitly enumerate all options in the API.

**Comment by gchanan** [comment]
Ultimately I agree with @ngimel; from my original message:

> Alternatively, just doc the possibility of setting the weight to None after creating it.

We can decide on what exactly to document.

**Comment by fkemeth** [comment]
Thank you @ngimel @gchanan @mruberry  for the feedback!

Just for clarification, the consensus now is to not change the batchnorm implementation, but rather document the issue that if batchnorm is followed by a (piecewise) linear function, then one should use affine falls and add a bias manually?

If so, do you have suggestions on where to document this?

**Comment by mruberry** [comment]
> Thank you @ngimel @gchanan @mruberry for the feedback!
> 
> Just for clarification, the consensus now is to not change the batchnorm implementation, but rather document the issue that if batchnorm is followed by a (piecewise) linear function, then one should use affine falls and add a bias manually?
> 
> If so, do you have suggestions on where to document this?

I think you nailed it, @fkemeth. The docstrings for BatchNormXd are [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/batchnorm.py). Maybe adding a note to them would work, like note on momentum?

**Comment by fkemeth** [comment]
What do you think about the following (for each BatchNormXd):

    .. note::
        When :class:`BatchNorm1d` is followed by a piecewise linear function
        such as :class:`~torch.nn.ReLU`, it is recommended to not use a learnable
        scale :math:`\gamma`. This can be achieved by setting :attr:`affine` to ``False`` and
        by manually adding a learnable bias,
        or setting ``requires_grad=False`` to :class:`BatchNorm1d` ``weight``.

Optionally one could also add a reference, as mentioned in #40087.

**Comment by mruberry** [comment]
> What do you think about the following (for each BatchNormXd):
> 
> ```
> .. note::
>     When :class:`BatchNorm1d` is followed by a piecewise linear function
>     such as :class:`~torch.nn.ReLU`, it is recommended to not use a learnable
>     scale :math:`\gamma`. This can be achieved by setting :attr:`affine` to ``False`` and
>     by manually adding a learnable bias,
>     or setting ``requires_grad=False`` to :class:`BatchNorm1d` ``weight``.
> ```
> 
> Optionally one could also add a reference, as mentioned in #40087.

This is a good start. It needs to describe the advantage of not using a learnable bias, however, so people aren't afraid that if they don't do this their networks are in error. This is, after all, just a small performance optimization, right?

A reference to the relevant paper would be good.

I'd describe one way of doing this (whatever's simplest) and put in a small code snippet showing it. 

So maybe something like: "When batchnorm is followed by a piecewise linear function, such as relu, its scale factor is redundant. As a small performance optimization you can disable updating the scale factor with ... <example"?

**Comment by fkemeth** [comment]
@mruberry I like your proposal. How about:

```
.. note::
    When :class:`BatchNorm1d` is followed by a piecewise linear function
    such as :class:`~torch.nn.ReLU`, its scale factor :math:`\gamma` is redundant
    (see also last paragraph in <https://arxiv.org/abs/1502.03167> Section 4). 
    As a small performance optimization you can disable updating the scale factor 
    :math:`\gamma` by setting ``requires_grad=False`` to :class:`BatchNorm1d` ``weight``,
    such as 
    >>> m = nn.BatchNorm1d(100)
    >>> m.weight.requires_grad = False

```

**Comment by ngimel** [comment]
Please don't say that it's recommended to use batchNorm without scale
1) Please point the exact place in https://arxiv.org/pdf/1502.03167.pdf that says scale is redundant. Neither last paragraph of section 4.1 nor last paragraph of section 4.2 make such statements
2) It is not a performance optimization, it is a performance pessimization, because if scale is not defined, instead of optimized implementations from vendor libraries torch native implementation will be used, and it is slower in most cases.

**Comment by fkemeth** [comment]
It seems I pasted the wrong link: Here is the paper where they mention that one should set the scale parameter when using BatchNorm together with a Relu activation:
[https://arxiv.org/pdf/1710.05941.pdf](https://arxiv.org/pdf/1710.05941.pdf) last paragraph section 4.
It is no explanation, though. I gave one in the issue #40087, but I am not aware of where to find it in the literature.
If you do not fix scale, you definitely have redundant trainable parameters. However, if this leads to performance degradation in some libraries (I am not familiar with that), we may also close this PR.

**Comment by mruberry** [comment]
> It seems I pasted the wrong link: Here is the paper where they mention that one should set the scale parameter when using BatchNorm together with a Relu activation:
> https://arxiv.org/pdf/1710.05941.pdf last paragraph section 4.

Yes, but aren't they advocating for training with scale because it's not redundant with the Swish activation function (which isn't piecewise linear)? 

> If you do not fix scale, you definitely have redundant trainable parameters. However, if this leads to performance degradation in some libraries (I am not familiar with that), we may also close this PR.

I think @ngimel's point is that the performance impact is, at best, unclear, and we'd need to investigate further if we could recommend this change as a performance improvement.

**Comment by jackwayneright** [comment]
I noticed the discussion was focused on whether this would lead to a performance difference. However, there are also other issues surrounding this. If batch normalization has the ability to apply a scale and is followed by weights that are regularized (e.g., by L2 regularization), the batch normalization can arbitrarily scale the values upwards so that the following weights can be arbitrarily small to avoid the regularization. I've run into the issue previously, though not in PyTorch. And it might not be as concerning of an issue in PyTorch since it appears the standard way to apply weight regularization is at the optimizer rather than on a per-layer basis, so only those who require a per-layer regularization would probably run into this issue.

**Pull request closed without merging**
