### PR TITLE
Migrate linux-jammy-py3.8-gcc11-no-ops to ARC

### PR DESCRIPTION
**Pull request by DanilBaibak**
Migrate linux-jammy-py3.8-gcc11-no-ops to ARC

### CODE REVIEW

**Review by zxiiro — APPROVED** [review]

**Review by malfet — APPROVED** [review]
LGTM, but perhaps I've missed something: is there a doc somewhere explaining the difference between `_linux-build.yml` and `_linux-build-label.yml`? Also, what `-rg` suffix stands for?

**Comment by DanilBaibak** [comment]
The `-rg` suffix means `run group`.
The difference between [_linux-build-label.yml](https://github.com/pytorch/pytorch/blob/main/.github/workflows/_linux-build-label.yml#L77) and [_linux-build-rg.yml](https://github.com/pytorch/pytorch/blob/main/.github/workflows/_linux-build-rg.yml#L78) is only how to to set `runs-on`. This was a way  to avoid code duplication for the `_linux-build.yml` workflow.

**Review by atalman — APPROVED** [review]

**Pull request closed without merging**
