### PR TITLE
[FSDP] Use generic device handle instead of cuda

### PR DESCRIPTION
**Pull request by jeejakp12**
In FSDP _optim_utils.py  Use generic device handle instead of cuda
to support other backends

Fixes #ISSUE_NUMBER

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @rohan-varma

### CODE REVIEW

**Review by awgu — APPROVED** [review]
SGTM!

**Review by wz337 — APPROVED** [review]
LGTM

**Comment by bsochack** [comment]
@wz337, @awgu, what does it block this change to be merged?

**Comment by awgu** [comment]
@bsochack Sorry, I think this fell through. Maybe we can rebase to `viable/strict` and try to merge?

**Pull request closed without merging**
