### PR TITLE
[PyTorch] Devirtualize is_contiguous

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#54896 [PyTorch] Devirtualize is_contiguous**

This should help performance. (For example, it improves total
time spent in a C++ benchmark that just adds 2 tensors in place by
about 10%.)

Differential Revision: [D27404164](https://our.internmc.facebook.com/intern/diff/D27404164/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D27404164/)!

### CODE REVIEW

**Review by bhosmer — APPROVED** [review]
Curious, why not just make `is_continuous_customized()` a virtual method, turn `IsContiguousPolicy` into a default/custom bool and  s/is_contiguous/is_contiguous_customized/ the subclasses? Would be less churn (e.g. for the FB case mentioned in phab) but maybe slower for the custom cases?

**Comment by ezyang** [comment]
I haven't closely looked at the diff yet, but it looks overcomplicated to compensate for not wanting fix clients, whereas I suspect we should just fix clients.

**Comment by swolchok** [comment]
>  I suspect we should just fix clients.

How would you recommend fixing them? There's a KP with Metal/Vulkan that would let us save one policy mode, but I don't know how to get rid of the errors for Batched/Opaque/Sparse.

**Comment by swolchok** [comment]
> why not just make is_continuous_customized() a virtual method,

Good idea. It somehow feels a little clunkier to have to override a virtual method *and* set a flag to make sure that that method is actually called; do you think preserving the BatchedTensorImpl error text is worth it?

**Comment by bhosmer** [comment]
> > why not just make is_continuous_customized() a virtual method,
> 
> Good idea. It somehow feels a little clunkier to have to override a virtual method _and_ set a flag to make sure that that method is actually called; do you think preserving the BatchedTensorImpl error text is worth it?

I'm not sure there's anything special about the BatchedTensorImpl error text, you could pull that into the current enum too, if you didn't want the double hop. That would mean that the enum betrays its origins as a cross section of subclass specific behaviors, but I mean, that's what it actually is 😁  so I'm not sure putting a "policy" veneer on it is the right direction to go in anyway (maybe this is what @ezyang was reacting to too)

**Comment by swolchok** [comment]
> it is possible to make it observationally equivalent to whatever you had before simply by setting the three contiguous_ fields appropriately.

There is no guarantee that the three contiguous_ fields will *stay* set. An API that calls `TensorImpl::refresh_contiguous()` (like, say, TensorImpl::set_sizes_and_strides or TensorImpl::empty_tensor_restride, both of which are non-virtual) could get called at any time and mess things up.

**Comment by bhosmer** [comment]
> observationally equivalent

What about the cases that currently throw? Also IIRC in previous discussions you weren't a fan of tensors with no concept of contiguity returning false for is_contiguous, but maybe this takes precedence (or I'm misremembering).

**Comment by ezyang** [comment]
> There is no guarantee that the three contiguous_ fields will stay set. An API that calls TensorImpl::refresh_contiguous() (like, say, TensorImpl::set_sizes_and_strides or TensorImpl::empty_tensor_restride, both of which are non-virtual) could get called at any time and mess things up.

All I'm saying is that one might very reasonable impose the obligation on the subclass that they are responsible for maintaining whatever invariants the parent class expects when they change sizes. If you have no concept of strides, you probably shouldn't call those methods anyway; if you *do* have strides, calling those functions is probably going to make it easy for you to preserve invariants.

> What about the cases that currently throw? Also IIRC in previous discussions you weren't a fan of tensors with no concept of contiguity returning false for is_contiguous, but maybe this takes precedence (or I'm misremembering).

Well, I'm OK with having a flag to raise an error, similar to what we do today with storage access. If someone came to me and said, "Edward, look at all this performance we're leaving on the floor because of this flag test", I'd be willing to be convinced that we need a way to do this access in a branchless way (overriding the general UX preference of erroring when you do something that doesn't make sense).

One thing to note, though, is that this PR has been updated from a "policy" thing to a "virtual fallback" thing. I guess I'm OK with the virtual fallback; there are certainly cases where it makes sense. I just think it kind of encourages bad behavior on backends where they can do all sorts of random (wrong) behavior and then we have to clean it up afterwards... case in point here.

**Comment by swolchok** [comment]
This PR is accepted, but given the discussion I'm unsure if I'm supposed to land it. @bhosmer / @ezyang  can you clarify?

**Comment by bhosmer** [comment]
> This PR is accepted, but given the discussion I'm unsure if I'm supposed to land it. @bhosmer / @ezyang can you clarify?

Yeah sorry for the mixed signals, it's my bad for stretching the "approve with suggestions" idiom past the breaking point, I'll change status to changes requested for clarity. 

My preference would be to not land this as-is but modify it to use a virtual is_contiguous_custom() instead of the "policy" switch. A ternary `has_contiguity_` flag seems to me like a decent way to confine the perf hit to the cases we want to get rid of anyway, but I'm sure there's other ways that would be fine. (per "loophole" above - true = default behavior, false = throw, custom = is_contiguous_custom() with a // TODO remove)

AFAICT @ezyang is also saying he's ok with a virtual fallback but not with the policy switch, but I could be wrong.

**Review by bhosmer — CHANGES_REQUESTED** [review]
Per thread

**Comment by swolchok** [comment]
AFAICT, here's a breakdown of TensorImpl types and the behavior they need:
- TensorImpl -- default, obviously
- Sparse -- does not have contiguity, throw
- Opaque -- does not have contiguity, throw
- Batched -- has custom contiguity behavior, virtual fallback
- DelayedTensorImpl -- custom behavior, virtual fallback (contiguous always iff MemoryFormat::Contiguous)
- Vulkan/Metal -- same as Delayed after @taox gets around to fixing the current behavior, virtual fallback

IIUC, we *want* to support "does not have contiguity, throw" going forward, and we begrudgingly support the virtual fallback.

I will send an update soon, but if this description is wrong, let's talk about it at this level rather than code comments.

**Comment by swolchok** [comment]
By the way, is_contiguous itself still needs to be TENSORIMPL_MAYBE_VIRTUAL to support backward compatibility, right?

**Comment by bhosmer** [comment]
> AFAICT, here's a breakdown of TensorImpl types and the behavior they need:
> ...
> IIUC, we _want_ to support "does not have contiguity, throw" going forward, and we begrudgingly support the virtual fallback.
> 
> I will send an update soon, but if this description is wrong, let's talk about it at this level rather than code comments.

This description matches my understanding, yeah.

Re TENSORIMPL_MAYBE_VIRTUAL, it would sure be nice to avoid, both for general-case perf and crazy semantics loophole reasons. But I don't know how what the contract is for TensorImpl subclassing - is the specific current set of virtual TensorImpl methods considered public API? cc @ezyang @gchanan

**Review by bhosmer — APPROVED** [review]
This looks great to me. I still don't know the definitive answer about `TENSORIMPL_MAYBE_VIRTUAL` but in the absence of signal, this is obv the right way to land it.

**Comment by bhosmer** [comment]
Oh hey, sorry for the late-breaking observation, but: since contiguity is per-class rather than per-instance, is it worth templatizing? Or alternatively, would it be worth making it const and setting it at construction time only rather than having a setter? 

Feel free to disregard if your sense of the perf (and safety I guess, but mostly perf) ROI doesn't motivate either of these, just want to make sure they've been floated.

**Comment by swolchok** [comment]
> would it be worth making it const and setting it at construction time only rather than having a setter?

It needs to be copied in the various metadata copy methods, so it can't be const (and I think I've forgotten to do that copying, so update coming)

**Comment by mruberry** [comment]
Relevant snippet for build failures:

```
Apr 02 23:06:09 In file included from /var/lib/jenkins/workspace/c10/core/TensorImpl.cpp:1:0:
Apr 02 23:06:09 /var/lib/jenkins/workspace/c10/core/TensorImpl.h:1851:41: error: 'c10::TensorImpl::has_contiguity_' is too small to hold all values of 'enum class c10::TensorImpl::HasContiguityPolicy' [-Werror]
Apr 02 23:06:09    HasContiguityPolicy has_contiguity_ : 2;
Apr 02 23:06:09                                          ^
Apr 02 23:06:09 cc1plus: all warnings being treated as errors
```

**Pull request closed without merging**
