### PR TITLE
dont prune unused symint graphargs from inner subclass tensors

### PR DESCRIPTION
**Pull request by bdhirsh**
This fixes an issue between dynamic shape + subclasses and inductor caching. Some context:

(1) inductor relies on an invariant today that all free symbols will show up as GraphArgs, when inductor generates guard expressions in the inductor cache

(2) dynamo fulfills this invariant: it does so by finding GraphArgs that have dynamic dims, and adding their symbols as extra graph args ([here](https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/output_graph.py#L676))

(3) afterward, dynamo will [remove](https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/output_graph.py#L1274) any graphargs from the graph that it sees are unused. However, it will explicitly make sure not to remove a graph arg if it sees that is corresponds to a free symbol ([code](https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/output_graph.py#L1588))

(4) However, our code for computing "free symbols" was wrong: we loop through all graphargs and find their free symbols, but we weren't properly accounting for free symbols that live on the inner tensors of any tensor subclass graph args.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #128331
* __->__ #128045
* #130338

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
test

**Comment by bdhirsh** [comment]
test added

**Comment by oulgen** [comment]
I landed https://github.com/pytorch/pytorch/pull/128052 which adds new tests for this, so lets rebase to make sure no test failures

**Pull request closed without merging**
