### PR TITLE
Clarifying windows cosine behaviour in the documentation

### LINKED ISSUE #110541: On the correctness of torch.signal.windows.cosine
As of writing, `torch.signal.windows.cosine` is implementing the following function:

$h[n] = \sin(\frac{\pi(n+0.5)}{M}),$

where $M$ is the length of the window. (The denominator is $M+1$ when `sym=False`, but my point will be the same.)

This implementation is identical to scipy's, but it deviates from the definition I'm familiar with, which is

$h[n] = \sin(\frac{\pi n}{M-1}).$

As far as I know, the cosine window is the square root of the Hann window. If we use the current implementation, this equality is not satisfied, while the latter definition does indeed satisfy it. For what it's worth, MATLAB also follows the latter definition. I could not find an explanation for scipy's deviation.

### Solution
I suppose there are two choices:
1. Continue following scipy, but make it clear in the documentation that it deviates from the correct definition.
2. Modify the code to implement the correct definition, and perhaps mention how it deviates from scipy in the docs.

cc @mruberry @rgommers

### PR DESCRIPTION
**Pull request by jmarintur**
After following the discussion, I've created a PR to update the documentation clarifying the function's behaviour (@tqbl solution 1).

Fixes #110541

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@jmarintur please fix lint errors (running lintrunner locally should be sufficient)

**Comment by jmarintur** [comment]
Thank you @malfet, all good now.

**Comment by jmarintur** [comment]
Hi @malfet, is there anything I have to do on my site?

**Comment by malfet** [comment]
@jmarintur no, nothing, change have merged into default branch as https://github.com/pytorch/pytorch/commit/fa071a2e1b6617ba722d639747f1d885017b0e86

**Pull request closed without merging**
