### PR TITLE
Optimize dataloader-worker index enque logic

### PR DESCRIPTION
**Pull request by mansimane**
Currently dataloader adds next indices to worker queues in _try_put_index in a round-robin fashion as below:
```python 
def _try_put_index(self):
    ... 
    for _ in range(self._num_workers):  # find the next active worker, if any
        worker_queue_idx = next(self._worker_queue_idx_cycle)
        if self._workers_status[worker_queue_idx]:
            break
    else:
        return
    
# Add indices to worker with index=worker_queue_idx
```

For datasets accessed from data sources external to the node, it is possible that each worker’s access latency varies a lot and hence some of the workers are faster than the others. In such a scenario, it would be efficient to give next batch of indices to workers which have already finished processing their assigned work. In the current setup, we make each of the workers fetch and process equal amount of training samples leaving faster workers to sit idle, which causes the slowest worker to determine the training time. In the proposed change, after reading data from the data queue, we give next batch of indices to the worker which returned the data instead of picking it in a round robin fashion.

```python 
def _try_put_index(self, worker_queue_idx=None):
    ...
    # if worker which just returned data is active, skip search
    if (worker_queue_idx is None) or (not self._workers_status[worker_queue_idx])
        for _ in range(self._num_workers):  # find the next active worker, if any
        worker_queue_idx = next(self._worker_queue_idx_cycle)
        if self._workers_status[worker_queue_idx]:
            break
    else:
        return
    # Add indices to worker with index=worker_queue_idx
```

To test the performance of this change, we developed a microbenchmark where we add an artificial latency to worker 0 to simulate a scenario of some of the workers being slow. Current round-robin method’s performance drops while the performance remains intact with the fix. These are the results of training ResNet50 on ImageNet dataset using [mmclassification](https://github.com/open-mmlab/mmclassification) library with the microbenchmark.

Batch size: 64
Number of workers per GPU: 8
Number of GPUs: 8

  | Master | Proposed change
-- | -- | --
Artificial Latency for worker 0(ms) | 500 | 500
Throughput(Images/sec) | 1100.1 | 1906.56065
Epoch Time(mins) | 20.816 | 12.13333
Gain(percent) |   | 41.7115

### CODE REVIEW

**Comment by SsnL** [comment]
Not sayin that this shouldn't be implemented. It is certainly worth discussing. I just want to note that this breaks determinism.

**Comment by SsnL** [comment]
@mansimane That's true, but the rng used is not deterministic. Whether a random augmentation is run on one worker vs the other affects determinism.

**Comment by mansimane** [comment]
@SsnL I get it now. How about this:

We can let users decide if they want determinism. For setting determinism in CUDA there is a method  [set_deterministic]( https://pytorch.org/docs/stable/_modules/torch.html#set_deterministic). 

1. We can reuse that method to set data determinism as well i.e. use default behavior if set_deterministic is called and use proposed change otherwise.

2. Or we can have another data_determinism flag as dataloader attribute. We can set it to True by default and if user wants further optimization of speed while accessing data outside node, user can set it to False (that's when proposed change will execute)

**Comment by ejguan** [comment]
Interesting. I had a PR #46189 before trying to optimize it, but I drop it as the improvement is not that significant. @VitalyFedyunin Can you look into it to see how we determine the performance gain?

**Pull request closed without merging**
