### PR TITLE
Correct typo for NCCL_MAJOR

### PR DESCRIPTION
**Pull request by ajindal1**
Correct Typo from NCCL_MACJOR to NCCL_MAJOR

Fixes Typo.

### CODE REVIEW

**Review by eqy — APPROVED** [review]

**Review by kwen2501 — APPROVED** [review]
Thanks for the important fix!

**Comment by Aidyn-A** [comment]
Does this bug fix #99669?

@pytorchmergebot merge

**Comment by eqy** [comment]
@Aidyn-A should be fixed in #99679.

**Pull request closed without merging**
