### PR TITLE
Provide a decorator to set/unset nccl blocking wait for tests

### PR DESCRIPTION
**Pull request by rohan-varma**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #54742 test_c10d: use with_nccl_blocking_wait decorator
* #54741 test_c10d: Run tests with nccl_async_error_handling
* **#54740 Provide a decorator to set/unset nccl blocking wait for tests**
blocking wait
* #54557 [NCCL] Enhance watchdog to log exceptions
* #54219 [DDP] Remove redundant pass statement
* #53787 Expose dist.monitored_barrier() API
* #53773 Gloo-only CPU-based monitored barrier
blocking wait
* #54557 [NCCL] Enhance watchdog to log exceptions
* #54219 [DDP] Remove redundant pass statement
* #53787 Expose dist.monitored_barrier() API
* #53773 Gloo-only CPU-based monitored barrier
blocking wait
* #54557 [NCCL] Enhance watchdog to log exceptions
* #54219 [DDP] Remove redundant pass statement
* #53787 Expose dist.monitored_barrier() API
* #53773 Gloo-only CPU-based monitored barrier
blocking wait
* #54557 [NCCL] Enhance watchdog to log exceptions
* #54219 [DDP] Remove redundant pass statement
* #53787 Expose dist.monitored_barrier() API
* #53773 Gloo-only CPU-based monitored barrier
blocking wait
* #54557 [NCCL] Enhance watchdog to log exceptions
* #54220 [DDP] Use monitored barrier in DDP
* #54219 [DDP] Remove redundant pass statement
* #53787 Expose dist.monitored_barrier() API
* #53773 Gloo-only CPU-based monitored barrier
blocking wait
* #54557 [NCCL] Enhance watchdog to log exceptions
* #54220 [DDP] Use monitored barrier in DDP
* #54219 [DDP] Remove redundant pass statement
* #53787 Expose dist.monitored_barrier() API
* #53773 Gloo-only CPU-based monitored barrier

Adds a simple helper decorator to set/unset nccl blocking wait for
tests. This will make it easier than having to manually set/unset the
os.environ vars every time.

Differential Revision: [D27277222](https://our.internmc.facebook.com/intern/diff/D27277222/)

### CODE REVIEW

**Review by wayi1 — APPROVED** [review]
Thanks for the refactoring!

Will there be more use cases for this decorator? Or are you doing this refactoring for only one use case?

**Comment by rohan-varma** [comment]
> Thanks for the refactoring!
> 
> 
> 
> Will there be more use cases for this decorator? Or are you doing this refactoring for only one use case?

This is the only use case in this file currently, but some diffs up the stack have additional use cases in test_c10d.

**Review by cuspymd — COMMENTED** [review]
If this decorator is only for testing, isn't it better to declare within the `distributed_test.py` file? 
If not, shouldn't a test be added for this decorator itself?

**Comment by rohan-varma** [comment]
> If this decorator is only for testing, isn't it better to declare within the `distributed_test.py` file?
> If not, shouldn't a test be added for this decorator itself?

It is only for testing, but our general pattern is to write utils for tests in `common_distributed` so that they can be used in files other than distributed_test.py.

**Comment by cuspymd** [comment]
> It is only for testing, but our general pattern is to write utils for tests in `common_distributed` so that they can be used in files other than distributed_test.py.

Thanks for your explanation.

**Pull request closed without merging**
