### PR TITLE
Rename potrf to cholesky

### PR DESCRIPTION
**Pull request by vishwakftw**
This PR performs a renaming of the function `potrf` responsible for the Cholesky
decomposition on positive definite matrices to `cholesky` as NumPy and TF do.

Billing of changes
- make potrf cname for cholesky in Declarations.cwrap
- modify the function names in ATen/core
- modify the function names in Python frontend
- issue warnings when potrf is called to notify users of the change

cc: @zou3519

### CODE REVIEW

**Comment by t-vi** [comment]
Please don't call it cholesky unless the default is lower triangular.
This transforms it from a function that is different from numpy to one that is more subtly different to numpy.

**Comment by ezyang** [comment]
@t-vi @vishwakftw Would you two mind coming up with a plan for how to order these diffs?

**Comment by t-vi** [comment]
The batch potrf needs @vishwakftw 's batch inverse #9949 to go in first and a rebase is waiting on that. Richard left a bunch of review comments on the bug, so if Vishwak is fast to fix them, I'd redo the potrf patch. I don't think tril will be a huge delay.

**Comment by vishwakftw** [comment]
@t-vi @ezyang I chatted with @zou3519 about the batch inverse PR. The stack that I think would be practical

#9949 Batched Inverse
#12699 Rename potrf to cholesky
#11796 Batched potrf

**Comment by t-vi** [comment]
"So my own patch first" is what everyone finds best. :man_shrugging: But yeah, I can live with any ordering, as long as it makes everyone else happy.

**Comment by vishwakftw** [comment]
@t-vi The ordering is something I don't mind either. It's just that there will be a lot of additional cleaning up to do after your batch potrf PR lands. But it would be equally hard for you if this PR lands, so I think it needs more discussion. I opened this PR after having a chat with @zou3519 (hence the cc).

But yes, maybe renaming potrf to cholesky could be part of a larger move on making PyTorch more NumPy-like :) , and this PR could be deferred accordingly.

**Comment by t-vi** [comment]
No, no, you should go first. Does this PR even conflict with the batch_inverse? If not it wouldn't even have to wait.

**Comment by vishwakftw** [comment]
This PR doesn't conflict with batch inverse. It only conflicts with batch potrf.

**Comment by vishwakftw** [comment]
@zou3519 Is this good to go?

**Review by zou3519 — APPROVED** [review]
LGTM!

**Comment by zou3519** [comment]
@ezyang yes, can do :)

**Comment by vishwakftw** [comment]
I am resolving conflicts, will update the branch shortly.

**Comment by zou3519** [comment]
On my way to importing it and merging it...

**Comment by vishwakftw** [comment]
Oh, this got merged in. Thank you @zou3519 .

**Pull request closed without merging**
