### PR TITLE
[NNC Testing] Randomized loop nest infrastructure

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #70410

Summary: Trying again after #70174 was reverted. Earlier the env
variable was read into a static var in C++ causing state to be retained
and causing test failures. Static type is removed in this PR.

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D33321435](https://our.internmc.facebook.com/intern/diff/D33321435)

### CODE REVIEW

**Comment by anijain2305** [comment]
@anijain2305 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33321435).

**Comment by anijain2305** [comment]
@anijain2305 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33321435).

**Comment by anijain2305** [comment]
@anijain2305 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33321435).

**Review by ZolotukhinM — APPROVED** [review]
Looks good to me!

**Pull request closed without merging**
