### PR TITLE
Upgrade submodule oneDNN to v3.4

### PR DESCRIPTION
**Pull request by Xia-Weiwen**
## Improvements
This upgrade fixes the following issues:
- https://github.com/pytorch/pytorch/issues/120982

This upgrade brings the following new features:
- Introduced memory descriptor serialization API. This API is needed to support freezing on CPU in AOTInductor (https://github.com/pytorch/pytorch/issues/114450)

## Validation results on CPU
No regression was found.

1. NLP models accuracy/inference/training

Model Name | Mode| Precision | New | Baseline | New/Baseline
-- | -- | -- | -- | -- | --
bert-large | accuracy | fp32 | 93.15325 | 93.15325 | 100.00%
bert-large | accuracy | bf16 | 93.20125 | 93.20125 | 100.00%
bert-large | accuracy | int8 | 92.66641 | 92.66641 | 100.00%
LCM | accuracy | fp32 | 44.11152 | 44.11154 | 100.00%
LCM | accuracy | bf16 | 43.57667 | 43.65096 | 100.17%
ViT | accuracy | fp32 | 0.8033 | 0.8033 | 100.00%
ViT | accuracy | bf16 | 0.8031 | 0.8031 | 100.00%
ViT | accuracy | int8 | 0.7985 | 0.7985 | 100.00%
yolov7 | accuracy | fp32 | 0.512 | 0.512 | 100.00%
yolov7 | accuracy | bf16 | 0.504 | 0.504 | 100.00%
yolov7 | accuracy | int8 | 0.507 | 0.507 | 100.00%
bert-large | realtime | fp32 | 37.433 | 39.136 | 95.65%
bert-large | realtime | bf16 | 166.592 | 160.134 | 104.03%
bert-large | realtime | int8 | 230.876 | 222.594 | 103.72%
ViT | realtime | fp32 | 288.19 | 282.05 | 102.18%
ViT | realtime | bf16 | 755.42 | 741.1 | 101.93%
ViT | realtime | int8 | 1060.94 | 1092.47 | 97.11%
yolov7 | realtime | fp32 | 17.06927 | 16.47995 | 103.58%
yolov7 | realtime | bf16 | 54.68561 | 54.00723 | 101.26%
yolov7 | realtime | int8 | 78.38271 | 77.63214 | 100.97%
bert-large | throughput | fp32 | 47.142 | 47.341 | 99.58%
bert-large | throughput | bf16 | 200.365 | 200.806 | 99.78%
bert-large | throughput | int8 | 144.999 | 145.295 | 99.80%
LCM | throughput | fp32 | 0.54913 | 0.54897 | 100.03%
LCM | throughput | bf16 | 1.062417 | 1.07772 | 98.58%
stable-diffusion | throughput | fp32 | 0.03301 | 0.0331 | 99.73%
stable-diffusion | throughput | bf16 | 0.08773 | 0.08849 | 99.14%
stable-diffusion | throughput | int8 | 0.0491 | 0.05024 | 97.73%
ViT | throughput | fp32 | 342.55 | 346.47 | 98.87%
ViT | throughput | bf16 | 1263.4 | 1268.32 | 99.61%
ViT | throughput | int8 | 1331.3 | 1345.32 | 98.96%
yolov7 | throughput | fp32 | 115.313 | 115.612 | 99.74%
yolov7 | throughput | bf16 | 323.364 | 323.747 | 99.88%
yolov7 | throughput | int8 | 388.137 | 384.236 | 101.02%
bert-large | train_phase1 | fp32 | 34.223 | 34.309 | 99.75%
bert-large | train_phase1 | bf16 | 90.372 | 88.453 | 102.17%
bert-large | train_phase2 | fp32 | 7.307 | 7.318 | 99.85%

Data Type | Geomean
-- | --
fp32 | 99.88%
bf16 | 100.70%
int8 | 99.88%
all | 100.16%

2. Torchbench cpu userbenchmark inference & training 

Test suite | Geomean Ratio (New/baseline)
-- | --
eager_throughtput_bf16_infer | 1.00x
eager_throughtput_fp32_infer | 1.00x
jit_llga_throughtput_amp_bf16 | 0.99x
jit_llga_throughtput_fp32 | 1.01x
eager_throughtput_fx_int8 | 1.00x
eager_throughtput_bf16_train | 1.00x
eager_throughtput_fp32_train | 1.00x

3. Inductor quantization (static & dynamic) accuracy & performance

Config | Performance geomean ratio (New/baseline) | Accuracy ratio (New/baseline)
-- | -- | --
Static quant PTQ | 0.99x | 1.00x
Static quant PTQ_CPP_WRAPPER | 0.98x | 1.00x
Static quant QAT | 0.99x | 1.00x
Dynamic quant PTQ | 1.00x | 1.00x

4. Dynamo benchmarks

Precision | Shape | Wrapper | Thread | Ratio   old/new GEOMEAN | Ratio   old/new GEOMEAN
-- | -- | -- | -- | -- | --
  |   |   |   | Eager | Inductor
Float32 | Static | Default | Multiple | 0.998776 | 1.002091
  |   |   | Single | 1.014086 | 1.01054
Float32 | Dynamic | Default | Multiple | 1.00386 | 1.005975
  |   |   | Single | 1.011036 | 1.008317
AMP | Static | Default | Multiple | 0.996965 | 1.005117
  |   |   | Single | 1.00092 | 0.995666
AMP | Dynamic | Default | Multiple | 0.9959 | 0.995048
  |   |   | Single | 1.002569 | 0.994085

---
cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @snadampal

### CODE REVIEW

**Comment by sanchitintel** [comment]
Hi @Xia-Weiwen, can we wait for a couple of days, and choose another commit instead? Thanks!

**Comment by Xia-Weiwen** [comment]
> Hi @Xia-Weiwen, can we wait for a couple of days, and choose another commit instead? Thanks!

No problem. And don't worry. This PR is for test now. We need to land #122164 first.

**Review by jgong5 — APPROVED** [review]

**Comment by Guobing-Chen** [comment]
@milpuz01, suppose you've also kicked off some tests for ARM platforms as per previous email communication. Could you share any test result if available?

**Comment by Xia-Weiwen** [comment]
Hi @jerryzh168 This upgrade adds support of freezing models on CPU for AOT Inductor

**Comment by milpuz01** [comment]
> @milpuz01, suppose you've also kicked off some tests for ARM platforms as per previous email communication. Could you share any test result if available?

Hi @Guobing-Chen, we still do not have results that we are able to share for AArch64. We will share them as soon as we are able.

**Comment by Xia-Weiwen** [comment]
Hi @malfet @atalman @jerryzh168 Do you have more comments on this? Thanks!

**Review by EikanWang — APPROVED** [review]

**Comment by atalman** [comment]
hi @Xia-Weiwen Internal changes looks green. However there are some OSS failures:
```
test_cpp_extensions_mtia_backend.py::TestCppExtensionMTIABackend::test_stream_context_different_device
```
Could you please take a look ?

**Comment by Xia-Weiwen** [comment]
> hi @Xia-Weiwen Internal changes looks green. However there are some OSS failures:
> 
> ```
> test_cpp_extensions_mtia_backend.py::TestCppExtensionMTIABackend::test_stream_context_different_device
> ```
> 
> Could you please take a look ?

Hi @atalman Good to know that internal is green. It seems the OSS failure is related to the MTIA accelerator. I cannot reproduce this failure in my CPU-only environment and I don't have an environment with MTIA. Could you please help take a look or advise how to investigate this? Thanks.
```
FAILED [0.0007s] test_cpp_extensions_mtia_backend.py::TestCppExtensionMTIABackend::test_stream_context_different_device - AssertionError: False is not true :
current_stream torch.Stream device_type=mtia, device_index=0, stream_id=0 should be torch.Stream device_type=mtia, device_index=1, stream_id=6
```

**Comment by atalman** [comment]
hi @Xia-Weiwen to confirm that the failure is unrelated and happens on main as well. Here is the test PR: https://github.com/pytorch/pytorch/pull/120317 - We should expect this test to fail as well.

**Review by atalman — APPROVED** [review]

**Comment by Xia-Weiwen** [comment]
@atalman Thanks for the help!

**Comment by Xia-Weiwen** [comment]
Hi @murste01
> 1. I don't know which exact models you are using for the NLP models accuracy/inference/training. Could you give some more details?

The NLP models for test are listed in the table https://github.com/pytorch/pytorch/pull/122472#issue-2201602846. Please refer to it.

> 2. I don't know how to get inductor quantization (static & dynamic) accuracy & performance results. Do you use your own scripts (e.g. inductor-tools)?

Inductor as a quantization backend is for x86 CPU only for now.

You don't have to follow the validation on x86 CPU. You may use your own test cases and suites to ensure there is no regression on AArch64.

**Comment by malfet** [comment]
I think @murste01 voices the same concerns as I have, namely it's great to see all those perf improvements on x86 platform, but as oneDNN are used by both x86 and aarch64 I would like to see some confirmation that there were no regressions there

**Comment by Xia-Weiwen** [comment]
Yes, of course. We have the same concern. The oneDNN project has its own test suites on ARM but it's still necessary to run validation with PyTorch. That's why we were asking for validation on aarch64 here https://github.com/pytorch/pytorch/pull/122472#issuecomment-2046354025
@Guobing-Chen and @milpuz01 may comment more. Thanks.

**Comment by Guobing-Chen** [comment]
> t more. Thanks.

Yes, that make sense. We've notified ARM team at the same time we created this PR through a dedicated email thread, and also @ the major contact milpuz01 in this PR (https://github.com/pytorch/pytorch/pull/122472#issuecomment-2050147004) to sync on the status. I believe ARM side is setting up some regular testing based on same/similar scope we've tested at X86 side, @milpuz01, may give some more updated information if available?

**Comment by Guobing-Chen** [comment]
> I think @murste01 voices the same concerns as I have, namely it's great to see all those perf improvements on x86 platform, but as oneDNN are used by both x86 and aarch64 I would like to see some confirmation that there were no regressions there
> 
> @atalman please before accepting oneDNN updates in the future, please make sure some tests/validation on aarch64 platform was also performed

Yes, that make sense. We've notified ARM team at the same time we created this PR through a dedicated email thread, and also @ the major contact milpuz01 in this PR (https://github.com/pytorch/pytorch/pull/122472#issuecomment-2050147004) to sync on the status. I believe ARM side is setting up some regular testing based on same/similar scope we've tested at X86 side, @milpuz01, may give some more updated information if available?

**Comment by snadampal** [comment]
meanwhile we should at least test the [linux-aarch64 CI ](https://github.com/pytorch/pytorch/blob/main/.github/workflows/linux-aarch64.yml)workflow for every ideep/mkldnn PRs.
I have tested this PR post it got merged and found that mkldnn tests are failing on aarch64. created this [issue](https://github.com/pytorch/pytorch/issues/125548) and checking if this can be fixed quickly.

**Comment by snadampal** [comment]
Hi @Xia-Weiwen , could you please confirm the oneDNN version you are targeting for PyTorch 2.4. If you are publishing this info somewhere, please let me know I will watch for that.

**Comment by milpuz01** [comment]
@malfet @atalman On Arm side @murste01 is setting up the same workflow as used by Intel to validate performance of oneDNN. He will take this discussion with @Guobing-Chen and @Xia-Weiwen over email to get the answers to the questions that he asked and the plan is that from now to produce exactly the same set of results on Arm platforms and attach it to the PR as @Xia-Weiwen does when oneDNN version changes.

**Comment by Xia-Weiwen** [comment]
Hi @snadampal @milpuz01 @murste01 I have updated this PR. Now oneDNN is upgraded to v3.4.2. Please help validate on Aarch64. Thanks.

**Comment by Xia-Weiwen** [comment]
Hi @snadampal There is a CI failure related to aarch64. Can you please investigate and fix. Thanks.

**Comment by etaf** [comment]
This CI failure [xpu / linux-jammy-xpu-py3.8 / test (default, 4, 4, linux.idc.xpu)](https://hud.pytorch.org/pr/pytorch/pytorch/122472#24880200859) ([gh](https://github.com/pytorch/pytorch/actions/runs/9056250545/job/24880200859)) is not related with this PR.
We meet the same issue in the PR #124842 , with is no oneDNN change, please ignore it.

**Comment by atalman** [comment]
@Xia-Weiwen Can you please create New PR for this ? We are hitting some internal tooling issue trying to import this PR internally, this PR is still associated with the change that we committed internally.

**Comment by Xia-Weiwen** [comment]
> @Xia-Weiwen Can you please create New PR for this ? We are hitting some internal tooling issue trying to import this PR internally, this PR is still associated with the change that we committed internally.

Hi @atalman I have created a new PR here: https://github.com/pytorch/pytorch/pull/126137

**Comment by snadampal** [comment]
@Xia-Weiwen , the CI failure is because oneDNN3.4 requires ACL version update, here is the PR:https://github.com/pytorch/pytorch/pull/125549
both these PRs are inter-dependent.

Hi @atalman , could you please suggest how we can handle this dependency. one option is to merge aarch64-linux CI PR (https://github.com/pytorch/pytorch/pull/125549) first, so that the CI will be ready to test oneDNN 3.4 on aarch64-linux.

**Pull request closed without merging**
