### PR TITLE
Update onnx.rst

### LINKED ISSUE #75508: ONNX scripting description mentions removed argument
### 📚 The doc issue

The ONNX related documentation, in particular the [subsection of tracing vs scripting](https://pytorch.org/docs/master/onnx.html#tracing-vs-scripting), mentions an argument that has been removed in version 1.11.

Concretely, in the 'Scripting' part:

> Call `torch.onnx.export()` with the ScriptModule as the model, and set the `example_outputs` arg. This is required so that the types and shapes of the outputs can be captured without executing the model.

However, the `example_outputs` arg has been removed entirely, as it appears that the model is now executed internally, in order to retrieve the example outputs:
https://github.com/pytorch/pytorch/blob/9905b1f29a5d23d30cfb570679845766983260c4/torch/onnx/utils.py#L470
Coming from here: https://github.com/pytorch/pytorch/blob/9905b1f29a5d23d30cfb570679845766983260c4/torch/onnx/utils.py#L559

### Suggest a potential alternative/fix

Replace

> Call `torch.onnx.export()` with the ScriptModule as the model, and set the `example_outputs` arg. This is required so that the types and shapes of the outputs can be captured without executing the model.

by

> Call ``torch.onnx.export()`` with the ``ScriptModule`` as the model. The ``args`` are still required, but they will be used internally only to produce example outputs, so that the types and shapes of the outputs can be captured. No tracing will be performed.

### PR DESCRIPTION
**Pull request by Nuno-Mota**
Fixes #75508

### CODE REVIEW

**Comment by ezyang** [comment]
ok. Please sign the CLA.

**Review by BowenBao — APPROVED** [review]

**Comment by Nuno-Mota** [comment]
@ezyang, it appears like I do not have permission to add the missing labels. Is there a way for me to do it?

**Pull request closed without merging**
