### PR TITLE
[Reland]Use cpuinfo to determine c10::ThreadPool thread number

### PR DESCRIPTION
**Pull request by cyyever**
Relands PR #107010 and fixes BUCK builds.

cc @ezyang @izaitsevfb

### CODE REVIEW

**Comment by izaitsevfb** [comment]
I've imported the PR to get the signal from internal meta builds ahead of the merge. Will let you know the results as soon as they are ready.

**Comment by izaitsevfb** [comment]
Unfortunately, the internal builds are still failing. I'm trying to see how to forward fix them them on meta's side.

**Review by ezyang — APPROVED** [review]

**Comment by izaitsevfb** [comment]
Please don't merge yet, I'm still working on the internal forward-fix.

**Comment by cyyever** [comment]
@izaitsevfb What is the situation?

**Comment by izaitsevfb** [comment]
> @izaitsevfb What is the situation?

I'm sorry for the delay, unfortunately, the fix is not trivial. We don't have a precedent yet of including third-party libraries into c10 core internally, and my attempts so far were unsuccessful.

But I'm still on it, and I'll try to solve this EoW. If not, I'll escalate.

**Comment by cyyever** [comment]
If it is hard to adopt cpuinfo to c10, may we remove the cpuinfo test temporarily?

**Comment by izaitsevfb** [comment]
@cyyever 
> @izaitsevfb If it is hard to add cpuinfo to c10, may we remove the cpuinfo test temporarily and try that in another PR?

I think I finally found everything that needs to be patched internally.

The following changes should be made to your PR (I can do this myself if you're ok with that) (see #109079):
* in `c10/ovrsource_defs.bzl` `"//third-party/cpuinfo:cpuinfo",` should be added.
* in `c10/core/build.bzl` I changed dependency to `":cpuinfo"`, but your original variant might also work (testing this now).

I'll try to merge this PR tomorrow. Apologies again for the delay.

**Comment by cyyever** [comment]
@izaitsevfb  Thank you so much for the efforts.

**Comment by izaitsevfb** [comment]
Ok, unfortunately `:cpuinfo` in `c10/core/build.bzl` doesn't work in OSS bazel build (I missed the build failures on my test PR, as they are suppressed as flaky). I'm trying to figure out the hack to have a consolidated dependency syntax that works both internally and in OSS.

**Comment by cyyever** [comment]
@izaitsevfb  I had a local bazel build and "//third_party/cpuinfo" could work.

**Comment by izaitsevfb** [comment]
> @izaitsevfb I had a local bazel build and "//third_party/cpuinfo" could work.

Yep, that's the way to go. I found how to support this variant internally as well, and all internal tests are passing now on the patched version.

So the plan is following (mostly for the record):
* rebase your PR to re-trigger the tests
* import it
* patch the diff with internal-only changes (they are already prepared)
* land both versions simultaneously in a co-dev style

**Comment by izaitsevfb** [comment]
The corresponding diff was merged internally, so our tooling should merge this PR shortly (if it doesn't, I'll force-merge it).

**Comment by cyyever** [comment]
@izaitsevfb Thank you!

**Comment by izaitsevfb** [comment]
@cyyever thank you for you patience, that was quite an adventure :)

**Pull request closed without merging**
