### PR TITLE
Generate backward for _adaptive_avg_pool2d from decomp

### PR DESCRIPTION
**Pull request by amjames**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #122325
* #121769

### CODE REVIEW

**Comment by amjames** [comment]
This one is a win overall benchmark below:

```
[---------------------------------------- adaptive_avg_pool2d -----------------------------------------]
                                                                 |  Compile-pyimpl  |  Compile  |  Eager
32 threads: --------------------------------------------------------------------------------------------
      input.shape=torch.Size([8, 3, 256, 256]), out_size=128     |         97       |     173   |    300
      input.shape=torch.Size([8, 3, 256, 256]), out_size=64      |         96       |     170   |    202
      input.shape=torch.Size([8, 3, 512, 512]), out_size=256     |        327       |     668   |    779
      input.shape=torch.Size([8, 3, 512, 512]), out_size=128     |        286       |     644   |    749
      input.shape=torch.Size([8, 3, 1024, 1024]), out_size=512   |       1300       |    2638   |   3036
      input.shape=torch.Size([8, 3, 1024, 1024]), out_size=256   |       1122       |    2540   |   2920
      input.shape=torch.Size([16, 3, 256, 256]), out_size=128    |        169       |     340   |    400
      input.shape=torch.Size([16, 3, 256, 256]), out_size=64     |        152       |     329   |    384
      input.shape=torch.Size([16, 3, 512, 512]), out_size=256    |        655       |    1321   |   1526
      input.shape=torch.Size([16, 3, 512, 512]), out_size=128    |        567       |    1273   |   1473
      input.shape=torch.Size([16, 3, 1024, 1024]), out_size=512  |       2601       |    5000   |   6000
      input.shape=torch.Size([16, 3, 1024, 1024]), out_size=256  |       2237       |    5000   |   6000
      input.shape=torch.Size([32, 3, 256, 256]), out_size=128    |        335       |     666   |    776
      input.shape=torch.Size([32, 3, 256, 256]), out_size=64     |        296       |     640   |    740
      input.shape=torch.Size([32, 3, 512, 512]), out_size=256    |       1310       |    2621   |   3012
      input.shape=torch.Size([32, 3, 512, 512]), out_size=128    |       1129       |    2527   |   2916
      input.shape=torch.Size([32, 3, 1024, 1024]), out_size=512  |       5000       |    4000   |  18870
      input.shape=torch.Size([32, 3, 1024, 1024]), out_size=256  |       4000       |    7000   |  18200

Times are in microseconds (us).
```

The same number of kernels are generated, but without a call to the fallback for backward so one fewer kernel calls overall.

**Review by lezcano — COMMENTED** [review]
This PR is, inadvertedly, also changing the lowering into a decomposition. When https://github.com/pytorch/pytorch/pull/117632 is landed, you would get an error. The thing here is that, if a function is registered as PyImpl, it's **unconditionally** decomposed at a dispatcher level, so it never gets to the lowering.

At the moment, we have some issues with the performance of this op for large `output_size`s, so I don't think we'll be able to land this one until @isuruf's work where he rewrites all these pooling ops as decomps is ready to be landed

**Comment by lezcano** [comment]
Also, I think that your benchmarks are all going through the `return torch.nn.functional.avg_pool2d(input, kernel, stride)` branch, so they are not super relevant. Do you mind posting the generated code before / after, and the code you used to generate it?

**Comment by amjames** [comment]
@lezcano See [here](https://github.com/amjames/py_impl-benchmark-adaptive_avg_pool2d) for the scripts I am using to generate the code and run the benchmarks, I also have the fx graphs and code generated for the first size in the benchmark in there. 

You were right about always falling into the `avg_pool2d` path, so I have edited those scripts to avoid that. Updated results are below (they are not so good). 

```
[---------------------------------------- adaptive_avg_pool2d -----------------------------------------]
                                                                 |  Compile-pyimpl  |  Compile  |  Eager
32 threads: --------------------------------------------------------------------------------------------
      input.shape=torch.Size([8, 3, 256, 256]), out_size=129     |        295       |     145   |    236
      input.shape=torch.Size([8, 3, 256, 256]), out_size=85      |        168       |     140   |    230
      input.shape=torch.Size([8, 3, 256, 256]), out_size=65      |        241       |     154   |    232
      input.shape=torch.Size([8, 3, 256, 256]), out_size=51      |        182       |     162   |    239
      input.shape=torch.Size([8, 3, 512, 512]), out_size=257     |       1109       |     564   |    878
      input.shape=torch.Size([8, 3, 512, 512]), out_size=170     |        618       |     614   |    869
      input.shape=torch.Size([8, 3, 512, 512]), out_size=129     |        897       |     575   |    850
      input.shape=torch.Size([8, 3, 512, 512]), out_size=102     |        678       |     629   |    893
      input.shape=torch.Size([8, 3, 1024, 1024]), out_size=513   |       4383       |    2270   |   3410
      input.shape=torch.Size([8, 3, 1024, 1024]), out_size=341   |       2436       |    2221   |   3410
      input.shape=torch.Size([8, 3, 1024, 1024]), out_size=257   |       3520       |    2265   |   3350
      input.shape=torch.Size([8, 3, 1024, 1024]), out_size=204   |       2677       |    2462   |   3492
      input.shape=torch.Size([16, 3, 256, 256]), out_size=129    |        571       |     283   |    451
      input.shape=torch.Size([16, 3, 256, 256]), out_size=85     |        320       |     277   |    435
      input.shape=torch.Size([16, 3, 256, 256]), out_size=65     |        466       |     294   |    441
      input.shape=torch.Size([16, 3, 256, 256]), out_size=51     |        350       |     306   |    444
      input.shape=torch.Size([16, 3, 512, 512]), out_size=257    |       2216       |    1095   |   1720
      input.shape=torch.Size([16, 3, 512, 512]), out_size=170    |       1230       |    1220   |   1714
      input.shape=torch.Size([16, 3, 512, 512]), out_size=129    |       1788       |    1138   |   1667
      input.shape=torch.Size([16, 3, 512, 512]), out_size=102    |       1352       |    1253   |   1773
      input.shape=torch.Size([16, 3, 1024, 1024]), out_size=513  |       8798       |    4548   |   6850
      input.shape=torch.Size([16, 3, 1024, 1024]), out_size=341  |       4918       |    4475   |   6800
      input.shape=torch.Size([16, 3, 1024, 1024]), out_size=257  |       7085       |    4519   |   6700
      input.shape=torch.Size([16, 3, 1024, 1024]), out_size=204  |       5444       |    4934   |   7000
      input.shape=torch.Size([32, 3, 256, 256]), out_size=129    |       1100       |     548   |    878
      input.shape=torch.Size([32, 3, 256, 256]), out_size=85     |        639       |     539   |    844
      input.shape=torch.Size([32, 3, 256, 256]), out_size=65     |        920       |     567   |    848
      input.shape=torch.Size([32, 3, 256, 256]), out_size=51     |        690       |     597   |    863
      input.shape=torch.Size([32, 3, 512, 512]), out_size=257    |       4446       |    2179   |   3420
      input.shape=torch.Size([32, 3, 512, 512]), out_size=170    |       2416       |    2423   |   3420
      input.shape=torch.Size([32, 3, 512, 512]), out_size=129    |       3580       |    2263   |   3310
      input.shape=torch.Size([32, 3, 512, 512]), out_size=102    |       2717       |    2480   |   3507
      input.shape=torch.Size([32, 3, 1024, 1024]), out_size=513  |      17750       |    9162   |  13700
      input.shape=torch.Size([32, 3, 1024, 1024]), out_size=341  |       9966       |    8957   |  13000
      input.shape=torch.Size([32, 3, 1024, 1024]), out_size=257  |      14230       |    9041   |  14000
      input.shape=torch.Size([32, 3, 1024, 1024]), out_size=204  |      11020       |    9855   |  10000

Times are in microseconds (us).
```

**Comment by lezcano** [comment]
Yep, all the pooling ops will need to wait for Isuru's work to land (provided it can be landed). Closing for now.

**Pull request closed without merging**
