### PR TITLE
Removing some dependency edges from Blob to other caffe2

### PR DESCRIPTION
**Pull request by smessmer**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#11923 Removing some dependency edges from Blob to other caffe2**&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D9979976/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11924 Move Blob to ATen/core&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9980641/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11414 IValue can store Blob&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D9731326/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11548 Blob doesn't allow access to destroyCall anymore&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D9775191/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11500 Use TypeMeta::dtor() instead of Blob::DestroyCall&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9763423/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11925 Serialization takes pointers instead of Blob&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9884177/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #11926 Remove Blob::ShareExternal from serialization&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9884563/)

This is pre-work to allow moving Blob to ATen/core, which cannot depend on caffe2 anymore.
(1) Removing the Blob -> Tensor dependency allows us to move Blob to ATen/core and use it inside IValue without having to wait for the Tensor merge to be complete.
(2) In the final Blob design, we want it to be a very small class that doesn't have any special treatment for Tensor (or to be more correct, doesn't allow storing Tensor anymore), , so this is anyhow the direction we want to go.

This changes call sites that will have to be moved to IValue later, but they cannot be moved to IValue directly, because for that, IValue first needs to be able to store Blob, which in turn first needs this diff and some other changes coming up in future diffs.

Codemods:
$ codemod --extensions h,hpp,c,cpp,cc "([a-zA-Z0-9_]+)\\.IsTensorType\\(" "BlobIsTensorType(\\1, "
$ codemod --extensions h,hpp,c,cpp,cc "([a-zA-Z0-9_]+)->IsTensorType\\(" "BlobIsTensorType(*\\1, "
$ codemod --extensions h,hpp,c,cpp,cc "([a-zA-Z0-9_]+)\\.GetMutableTensor\\(" "BlobGetMutableTensor(\\1, "
$ codemod --extensions h,hpp,c,cpp,cc "([a-zA-Z0-9_]+)->GetMutableTensor\\(" "BlobGetMutableTensor(*\\1, "

It is, however, not only these codemods because regex based refactoring was only able to match a small amount of the call sites. To catch more, I wouldn've needed a AST aware tool like clangr, which I didn't figure out how to use.

Differential Revision: [D9979976](https://our.internmc.facebook.com/intern/diff/D9979976/)

### CODE REVIEW

**Comment by ezyang** [comment]
I'm a little confused. Why would having these methods on Blob prevent movement to ATen/core? Tensor is going to live in ATen/core, and I can't think of anything else these methods could refer to that you can't reference in core?

**Comment by smessmer** [comment]
It's two things. (1) it unblocks me from having to wait until Tensor merge is complete (because before that, blob references c2 tensor), and (2) we want to do this anyhow because the final blob design doesn't let it store tensor anymore.

**Comment by ezyang** [comment]
ghexport has messed this one up too. What it *looks* like is that you updated export-D9882726 without also reexporting this one. A gh from the top of the stack should fix it.

**Comment by smessmer** [comment]
I think this might have been broken by landing the diff below. I re-exported it.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
