### PR TITLE
Replace Exception with BaseException

### LINKED ISSUE #87333: [RPC][BE][Easy] Custom python UDF should catch BaseExceptions
### 🚀 The feature, motivation and pitch

Resolve the TODO in https://github.com/pytorch/pytorch/pull/87224/files#diff-e0abc0cc354cebd2f96a1165396c5a55f882b824c86c109a4ef54f536f1e32feR208. We should catch BaseException instead of Exception because BaseException is the pythonic way users should inherit from to define custom exceptions. This is technically BC breaking, but very minor. 

### Alternatives

_No response_

### Additional context

_No response_

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @pietern @jjlilley @mrzzd

### PR DESCRIPTION
**Pull request by jazzysoggy**
Fixes #87333

Replaces Exception with BaseException

Note: Still need to test

### CODE REVIEW

**Comment by kit1980** [comment]
@rohan-varma I wonder what kind of BC issues you had in mind?

**Comment by rohan-varma** [comment]
If a python function user executes over RPC raises an Exception that does not inherit from BaseException, this would now result in a crash. But actually, the discussion in https://stackoverflow.com/questions/60745841/inheriting-from-baseexception-vs-exception makes me think I may have gotten the convention backwards, so maybe we should just stick with Exception here and remove the TODO.

**Comment by kit1980** [comment]
@jazzysoggy According to the previous comment, do you want to change the PR to just remove the TODO?

**Comment by kit1980** [comment]
Closing this in favor to just remove the TODO https://github.com/pytorch/pytorch/pull/89540

**Pull request closed without merging**
