### PR TITLE
Remove all conda 3.5 nightly configs, remove libtorch smoketests

### PR DESCRIPTION
**Pull request by kostmo**
| | Before | After
------------ | ------------ | -------------
Binary builds | binarybuilds-config-dimensions | binarybuilds-config-dimensions |
Smoke tests | binarysmoketests-config-dimensions | binarysmoketests-config-dimensions |

### CODE REVIEW

**Review by pjh5 — APPROVED** [review]

**Comment by ezyang** [comment]
Karl, do you know why we removed the conda 3.5 nightlies?

**Comment by kostmo** [comment]
> Karl, do you know why we removed the conda 3.5 nightlies?

Sorry, I think @pjh5 just made a verbal request.  I didn't dig into the rationale.

**Comment by pjh5** [comment]
One of the conda 3.5 nightlies broke a long time ago cause of some conda dependency issue iirc. It'd probably be easy to fix but just no one ever got around to it.

**Comment by ezyang** [comment]
Thanks for popping by. It looks like it got fixed in the meantime so these are reenabbled :)

**Pull request closed without merging**
