### PR TITLE
Fix https://github.com/pytorch/pytorch/issues/92377

### LINKED ISSUE #92377: Bug when calling `torch._functorch.compilers.draw_graph_compile`
https://github.com/pytorch/pytorch/blob/00fe63d1d8c5c6411e093fa4388dc98c3683d236/torch/_functorch/aot_autograd.py#L1003-L1010
https://github.com/pytorch/pytorch/blob/00fe63d1d8c5c6411e093fa4388dc98c3683d236/torch/_functorch/compilers.py#L99-L107

When using `partial` for `_draw_graph_compile` in `draw_graph_compile`, it has been converted into a `f(fx_g, inps)` by `make_boxed_compiler`, and the `name` parameter no longer exists, so it should be changed to

```python
def _draw_graph_compile(fx_g, _, name, clear_meta=True):
    print(fx_g.code)
    draw_graph(fx_g, name, clear_meta=clear_meta)
    return fx_g


def draw_graph_compile(name):
    return make_boxed_compiler(
        partial(_draw_graph_compile, name=name)
    )
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

### PR DESCRIPTION
**Pull request by unlimblue**
Fixes #92377

### CODE REVIEW

**Comment by eellison** [comment]
@Chillee how does this look ?

**Review by Chillee — APPROVED** [review]
Thanks!

**Pull request closed without merging**
