### PR TITLE
[FSDP] [composable] [BE] warning should read TorchRec, not DMP

### PR DESCRIPTION
**Pull request by colin2328**
Summary: as title

Test Plan: N/A

Differential Revision: D43375189

### CODE REVIEW

**Review by awgu — APPROVED** [review]

**Comment by awgu** [comment]
Stamping to unblock this, but for my understanding, does this PR mean that that warning can be emitted even when not using DMP?

**Review by fegin — APPROVED** [review]

**Comment by fegin** [comment]
> Stamping to unblock this, but for my understanding, does this PR mean that that warning can be emitted even when not using DMP?

@awgu Yes. If FSDP is used with TorchRec, DMP or trec_shard, the warning will occur.

**Comment by colin2328** [comment]
@awgu  yes, and furthermore, we don't recommend using FSDP + DMP together (instead we suggest trec_shard + fully_shard).

**Pull request closed without merging**
