### PR TITLE
[JIT][to_backend] Move code that is not related to the user-facing API out of `jit/backends/backend.h`

### LINKED ISSUE #38431: [JIT][to_backend] Move code that is not related to the user-facing API out of `jit/backends/backend.h`
## Background
JIT recently added a feature that allows a `Module` to be lowered for execution on a non-JIT specialized backend, such as Glow. The API for declaring specialized backends is in `torch/csrc/jit/backends/backend.h`. However, there is code in there that is not templated (e.g. `getPreprocessSchema`) and does not need to be in that header. Its continued presence can be confusing for end-users.

## The Task
Move this code that does not need to be in `backend.h` into a `detail` namespace in a separate header or into a separate cpp file.

## How to Test
```
python test/test_jit.py TestBackends
```

cc @suo

### PR DESCRIPTION
**Pull request by jansel**
Fixes #38431 

**Test Plan**
```
python test/test_jit.py TestBackends
```

### CODE REVIEW

**Review by SplitInfinity — APPROVED** [review]
😍

**Comment by SplitInfinity** [comment]
Heads up, you might have to rebase if #38562 lands first

**Comment by SplitInfinity** [comment]
#38562 has landed

**Comment by jansel** [comment]
Got it, thanks!

**Pull request closed without merging**
