### PR TITLE
Fixed mypy typing errors in distributed dir.

### PR DESCRIPTION
**Pull request by xuzhao9**
#42967 WIP. Fixes everything under distributed/ except distributed_c10d and nn.*.

### CODE REVIEW

**Comment by malfet** [comment]
Thank you very much for PR, @xuzhao9 !
I've converted it back to draft, since it breaks a lot of configs right now.
Please update your change to exclude fbgemm update and then rebase it on top of https://github.com/pytorch/pytorch/pull/44451 that properly exposes native contributions form `torch/csrc/autograd/init.cpp` to typing system.

**Comment by xuzhao9** [comment]
> Thank you very much for PR, @xuzhao9 !
> I've converted it back to draft, since it breaks a lot of configs right now.
> Please update your change to exclude fbgemm update and then rebase it on top of #44451 that properly exposes native contributions form `torch/csrc/autograd/init.cpp` to typing system.

Thanks @malfet for #44451! I have updated this PR to reflect the change. Please help review, thanks!

**Comment by walterddr** [comment]
thanks @xuzhao9 for following up on this. seems like there's some merge issues. is it possible to rebase or cherry-pick your changes onto latest master instead of doing merges?

**Comment by xuzhao9** [comment]
Close this PR as it is superseded by PR #45987.

**Pull request closed without merging**
