### PR TITLE
Fix the docs for cosine_similarity

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104772
* #104771

The behaviour of `cosine_similarity` was subtly changed in
https://github.com/pytorch/pytorch/pull/31378, but the docs were not
updated.

cc @svekars @carljparker

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM

**Review by svekars — APPROVED** [review]

**Pull request closed without merging**
