### PR TITLE
Add privateuseone flags for c10::EventFlag

### LINKED ISSUE #117341: Add privateuseone flags for c10::EventFlag
### 🚀 The feature, motivation and pitch

My team is working on adding a custom backend for pytorch and would like to add privateuseone flags (PRIVATEUSEONE_DEFAULT and PRIVATEUSEONE_DISABLE_TIMING) in c10::EventFlag.

I noticed that current flags (https://github.com/pytorch/pytorch/blob/main/c10/core/impl/DeviceGuardImplInterface.h#L32) like BACKEND_DEFAULT and PYTORCH_DEFAULT can only ensure default usage but cannot control whether to disable timing or not. This can make it difficult for a custom backend to create a non-default event on the C++ front end PyTorch.

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chentianyi16**
Fixes #117341

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
As mentioned on the issue, that sounds good, thanks for sending a PR!
It would be amazing if we could remove the CUDA/HIP flags from here as well to avoid any confusion going forward.

**Comment by chentianyi16** [comment]
> As mentioned on the issue, that sounds good, thanks for sending a PR! It would be amazing if we could remove the CUDA/HIP flags from here as well to avoid any confusion going forward.
 CUDA and HIP -specific flags are already removed.

**Review by albanD — COMMENTED** [review]
Thanks!
You'll need to update https://github.com/pytorch/pytorch/blob/360761f7d039445e7b00493c2990ace9f94a5a9e/c10/cuda/impl/CUDAGuardImpl.h#L86 as well

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by chentianyi16** [comment]
@albanD  Hi, I just noticed my job failed in `
trunk / linux-focal-cuda12.1-py3.10-gcc9 / test (nogpu_NO_AVX2, 1, 1, linux.2xlarge) (push) ` but my PR does not involve codegen. Is this problem an occasional known problem or this problem is caused by my PR?

**Review by albanD — APPROVED** [review]

**Comment by albanD** [comment]
@pytorchbot merge

It does look unrelated

**Comment by albanD** [comment]
Ho lint needs fixing!

**Comment by chentianyi16** [comment]
> Ho lint needs fixing!

Already fixed

**Comment by chentianyi16** [comment]
@albanD Hi, seems all checks are passed

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
