### PR TITLE
Delete Lark

### PR DESCRIPTION
**Pull request by oulgen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #123689

Now that we are using MLIR bindings inside triton, lets delete Lark parser.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by PaliC** [comment]
@pytorchbot revert -m "This PR seems to be breaking  test_binary_ufuncs.py" -c "nosignal"

https://hud.pytorch.org/pytorch/pytorch/commit/a631461eef7317efccf981989c5cf5c5b486ab0a
This PR is only breaking  test_binary_ufuncs.py the other failure was from a previous PR. However, the  test_binary_ufuncs.py does not appear to fail on the previous pr on trunk.

**Comment by huydhn** [comment]
This is interesting as the test failure might be indeed unrelated to this change, but somehow updating `.ci/docker/requirements-ci.txt` surfaces the error.

Yesterday, @malfet did a similar step by updating the file in https://hud.pytorch.org/pytorch/pytorch/commit/f61b04a1f0ed55aa3f9b75e1266e7a5dc71fc90d, and the same test failed.  As both changes trigger the update of the Docker image, I suspect that there is another dependency being pulled in and causes the failure.

**Comment by malfet** [comment]
@huydhn thank you for the heads up, let me see what is going on

**Comment by oulgen** [comment]
@malfet @huydhn in that case, should i drop my change to `requirements-ci.txt` to land this PR?

**Comment by malfet** [comment]
@oulgen go for it and I'll delete it in a separate PR

**Pull request closed without merging**
