### PR TITLE
Run sympy expressions with Python values / FX tracing

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #114148
* #113958
* __->__ #113978

To codegen deferred runtime asserts, I need to be able to convert sympy expressions back into regular Python expressions that I can put in FX graphs. This PR adds some of the machinery to do this: it adds a new sympy analysis that runs operations on all FX traceable operations that can also be run with plain Python int/float/bool/etc. It's tested by symbolic tracing through the analysis, and then testing that this traced graph gives the same result as running the Python analysis directly.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by aakhundov — APPROVED** [review]

**Review by lezcano — APPROVED** [review]
This makes the assumption that SymPy symbolic semantics are equivalent to Python's semantics, which may or may not be true, but well.

**Comment by ezyang** [comment]
It's actually not true, which is why I cannot actually write a test that checks that ReferenceAnalysis matches PythonReferenceAnalysis. However, as long as you stay in the "abstract interpretation" land I think it will work out

**Comment by lezcano** [comment]
what do you mean by "stay in the abstract interpretation"?

**Comment by ezyang** [comment]
don't actually go into sympy rationals, stay with just the AST

**Pull request closed without merging**
