### PR TITLE
[ROCm] remove thrust workaround in ScanKernels

### PR DESCRIPTION
**Pull request by jeffdaily**
Remove ROCm workaround added in #39180.

### CODE REVIEW

**Comment by jeffdaily** [comment]
@ngimel this is the other file where I found a similar cub workaround for ROCm.  I missed your comment back in June in #39180 when you initially notified me of the workaround. (https://github.com/pytorch/pytorch/pull/39180#issuecomment-637009830).

Let's watch ROCm CI again for passing status.

**Comment by jeffdaily** [comment]
ROCm CI failure of 'test2' caused by assigned CI host being out of disk space.  CI host was fixed.  Need to retest.

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Awesome, thank you! Originally there were also build failures for complex (see rocm_bug struct), but hopefully this is fixed with 3.7.1, let's wait for CI.

**Comment by jeffdaily** [comment]
Build failures due to complex should be a thing of the past.  ROCm 3.5 and newer handles complex better.

**Pull request closed without merging**
