### PR TITLE
Added define to fix issue with compatibility with latest Windows SDK

### LINKED ISSUE #83820: pytorch incompatible with windows sdk >= 25131
### 🐛 Describe the bug

```
FAILED: caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/AdaptiveMaxPooling2d.cu.obj
C:\PROGRA~1\NVIDIA~2\CUDA\v11.6\bin\nvcc.exe -forward-unknown-to-host-compiler -DAT_PER_OPERATOR_HEADERS -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTORCH_CUDA_BUILD_MAIN_LIB -DUSE_CUDA -DUSE_EXPERIMENTAL_CUDNN_V8_API -DUSE_EXTERNAL_MZCRC -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE=1 -Dtorch_cuda_EXPORTS -IC:\Github\pytorch\build\aten\src -IC:\Github\pytorch\aten\src -IC:\Github\pytorch\build -IC:\Github\pytorch -IC:\Github\pytorch\cmake\..\third_party\benchmark\include -IC:\Github\pytorch\cmake\..\third_party\cudnn_frontend\include -IC:\Github\pytorch\third_party\onnx -IC:\Github\pytorch\build\third_party\onnx -IC:\Github\pytorch\third_party\foxi -IC:\Github\pytorch\build\third_party\foxi -IC:\Github\pytorch\build\include -IC:\Github\pytorch\torch\csrc\distributed -IC:\Github\pytorch\aten\src\THC -IC:\Github\pytorch\aten\src\ATen\cuda -IC:\Github\pytorch\build\caffe2\aten\src -IC:\Github\pytorch\aten\..\third_party\catch\single_include -IC:\Github\pytorch\aten\src\ATen\.. -IC:\Github\pytorch\c10\cuda\..\.. -IC:\Github\pytorch\c10\.. -IC:\Github\pytorch\torch\csrc\api -IC:\Github\pytorch\torch\csrc\api\include -isystem=C:\Github\pytorch\cmake\..\third_party\googletest\googlemock\include -isystem=C:\Github\pytorch\cmake\..\third_party\googletest\googletest\include -isystem=C:\Github\pytorch\third_party\protobuf\src -isystem=C:\Github\pytorch\third_party\XNNPACK\include -isystem=C:\Github\pytorch\third_party\ittapi\include -isystem=C:\Github\pytorch\cmake\..\third_party\eigen -isystem="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -isystem=C:\Github\pytorch\third_party\ideep\mkl-dnn\third_party\oneDNN\include -isystem=C:\Github\pytorch\third_party\ideep\include -isystem="C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -Xcompiler /w -w -Xfatbin -compress-all -DONNX_NAMESPACE=onnx_torch --use-local-env -gencode arch=compute_86,code=sm_86 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=integer_sign_change,--diag_suppress=useless_using_declaration,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=implicit_return_from_non_void_function,--diag_suppress=unsigned_compare_with_zero,--diag_suppress=declared_but_not_referenced,--diag_suppress=bad_friend_decl --Werror cross-execution-space-call --no-host-device-move-forward --expt-relaxed-constexpr --expt-extended-lambda  -Xcompiler=/wd4819,/wd4503,/wd4190,/wd4244,/wd4251,/wd4275,/wd4522 -Wno-deprecated-gpu-targets --expt-extended-lambda -DCUB_WRAPPED_NAMESPACE=at_cuda_detail -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -Xcompiler="-MD -O2 -Ob2" -DNDEBUG -Xcompiler /MD -DTH_HAVE_THREAD -Xcompiler= -DTORCH_CUDA_BUILD_MAIN_LIB -std=c++14 -MD -MT caffe2\CMakeFiles\torch_cuda.dir\__\aten\src\ATen\native\cuda\AdaptiveMaxPooling2d.cu.obj -MF caffe2\CMakeFiles\torch_cuda.dir\__\aten\src\ATen\native\cuda\AdaptiveMaxPooling2d.cu.obj.d -x cu -c C:\Github\pytorch\aten\src\ATen\native\cuda\AdaptiveMaxPooling2d.cu -o caffe2\CMakeFiles\torch_cuda.dir\__\aten\src\ATen\native\cuda\AdaptiveMaxPooling2d.cu.obj -Xcompiler=-Fdcaffe2\CMakeFiles\torch_cuda.dir\,-FS
C:/Github/pytorch/aten/src\ATen/cuda/NumericLimits.cuh(31): error: floating-point value does not fit in required floating-point type

1 error detected in the compilation of "C:/Github/pytorch/aten/src/ATen/native/cuda/AdaptiveMaxPooling2d.cu".
```

### Versions

pytorch master/main/trunk
VS2019
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64
and
VS2022
Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31721 for x64
Cuda version 11.6

How to reproduce:
```
use windows sdk >= 25131 when building pytorch
```
my cmake command:
```
cmake .. -GNinja ^
-DCMAKE_INSTALL_PREFIX=C:\pytorch_install_11_6 ^
-DCMAKE_BUILD_TYPE=Release -DBUILD_TEST=ON
```

my naive investigation

1. check what C:/Github/pytorch/aten/src\ATen/cuda/NumericLimits.cuh include
its
#include <cuda.h>
#include <limits.h>
#include <math.h>
#include <float.h>

2. diff between multiple SDK
diff -rub 10.0.19041.0 10.0.25182.0 > diff.txt

3. some diff pique interest because math.h include corecrt_math.h (most diff result omitted) 
```
diff -rub 10.0.19041.0/ucrt/corecrt_math.h 10.0.25182.0/ucrt/corecrt_math.h
--- 10.0.19041.0/ucrt/corecrt_math.h	2020-11-25 19:39:50.000000000 +0700
+++ 10.0.25182.0/ucrt/corecrt_math.h	2022-08-04 19:17:24.000000000 +0700
@@ -81,15 +81,44 @@
     #endif
 #endif
 
+#if !defined __cplusplus && !defined __midl 
+inline float __ucrt_int_to_float(int i)
+{
+    union {
+        int i;
+        float f;
+    } __my_int_to_float;
+
+    __my_int_to_float.i = i;
+    return __my_int_to_float.f;
+}
+#endif
+
 #ifndef _HUGE_ENUF
     #define _HUGE_ENUF  1e+300  // _HUGE_ENUF*_HUGE_ENUF must overflow
 #endif
-
+#ifndef _UCRT_LEGACY_INFINITY
+#define INFINITY   ((float)(_HUGE_ENUF))
+#else
 #define INFINITY   ((float)(_HUGE_ENUF * _HUGE_ENUF))
+#endif
 #define HUGE_VAL   ((double)INFINITY)
 #define HUGE_VALF  ((float)INFINITY)
 #define HUGE_VALL  ((long double)INFINITY)
-#define NAN        ((float)(INFINITY * 0.0F))
+
+#if defined _UCRT_NOISY_NAN || defined __midl
+#define _UCRT_NAN (-(float)(((float)(_HUGE_ENUF * _HUGE_ENUF)) * 0.0F))
+#elif defined __cplusplus
+#define _UCRT_NAN (__builtin_nanf("0"))
+#else
+#define _UCRT_NAN (__ucrt_int_to_float(0x7FC00000))
+#endif
+
+#ifdef _UCRT_NEGATIVE_NAN
+#define NAN (-_UCRT_NAN)
+#else
+#define NAN _UCRT_NAN
+#endif
 
 #define _DENORM    (-2)
 #define _FINITE    (-1)
@@ -604,7 +633,7 @@
 
 
 
-    #if defined _M_X64 || defined _M_ARM || defined _M_ARM64 || defined _M_HYBRID_X86_ARM64 || defined _CORECRT_BUILD_APISET
+    #if defined _M_X64 || defined _M_ARM || defined _M_ARM64 || defined _M_HYBRID_X86_ARM64 || defined _CORECRT_BUILD_APISET || defined _M_ARM64EC
 
         _Check_return_ _ACRTIMP float __cdecl acosf(_In_ float _X);
         _Check_return_ _ACRTIMP float __cdecl asinf(_In_ float _X);
@@ -659,7 +688,7 @@
 
     #endif
 
-    #if defined _M_ARM || defined _M_ARM64 || defined _M_HYBRID_X86_ARM64
+    #if defined _M_ARM || defined _M_ARM64 || defined _M_HYBRID_X86_ARM64 || defined _M_ARM64EC
 
         _Check_return_ _CRT_JIT_INTRINSIC _ACRTIMP float __cdecl fabsf(_In_ float  _X);
 
@@ -672,7 +701,7 @@
 
     #endif
 
-    #if defined _M_X64 || defined _M_ARM || defined _M_ARM64 || defined _M_HYBRID_X86_ARM64
+    #if defined _M_X64 || defined _M_ARM || defined _M_ARM64 || defined _M_HYBRID_X86_ARM64 || defined _M_ARM64EC
 
         _Check_return_ _ACRTIMP float __cdecl floorf(_In_ float _X);
         _Check_return_ _ACRTIMP float __cdecl fmodf(_In_ float _X, _In_ float _Y);
@@ -706,7 +735,7 @@
         return (float)ldexp(_X, _Y);
     }
 
-    #if defined _M_X64 || defined _M_ARM || defined _M_ARM64 || defined _M_HYBRID_X86_ARM64 || defined _CORECRT_BUILD_APISET
+    #if defined _M_X64 || defined _M_ARM || defined _M_ARM64 || defined _M_HYBRID_X86_ARM64 || defined _CORECRT_BUILD_APISET || defined _M_ARM64EC
 
         _Check_return_ _ACRTIMP float  __cdecl log10f(_In_ float _X);
         _Check_return_ _ACRTIMP float  __cdecl logf(_In_ float _X);
```

4. add -D_UCRT_LEGACY_INFINITY 

5. compile success

6. naively check when that define introduced
found out since windows sdk 25131
you can download it here https://docs.microsoft.com/en-us/windows-insider/flight-hub/

Thanks for reading.

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm

### PR DESCRIPTION
**Pull request by vladimir-aubrecht**
Fixes #83820.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
need cla

**Comment by vladimir-aubrecht** [comment]
> need cla

In progress, discussing it with legal to find out if I can sign.

**Comment by ezyang** [comment]
If it helps, we're going to be shortly swapping the CLA over to Linux Foundation's CLA rather than Meta's (following https://www.linuxfoundation.org/blog/blog/welcoming-pytorch-to-the-linux-foundation ); so if you want you could wait for that too.

**Comment by vladimir-aubrecht** [comment]
> If it helps, we're going to be shortly swapping the CLA over to Linux Foundation's CLA rather than Meta's (following https://www.linuxfoundation.org/blog/blog/welcoming-pytorch-to-the-linux-foundation ); so if you want you could wait for that too.

Good to know! Thank you, I'll find out 😊

**Comment by vladimir-aubrecht** [comment]
@ezyang I managed to get through Linux Foundation CLA, but still stucked on original Meta CLA even thou I signed both of them. Could you help me with that? Is Meta CLA is required, maybe we just need to restart pipeline? 😊

**Comment by ezyang** [comment]
Let's try rebasing

**Pull request closed without merging**
