### PR TITLE
Add xpu path for GRUCell

### PR DESCRIPTION
**Pull request by zhuyuhua-v**
Add xpu path for GRUCell.
We supported a new kernel named _thnn_fused_gru_cell to fuse the small ops of GRU.

### CODE REVIEW

**Comment by zhuyuhua-v** [comment]
@frank-wei Could you please help review this pr? Thx.

**Comment by frank-wei** [comment]
@zhuyuhua-v  why you enable GRUCell op only? Do you have any unit tests to verify it?

**Comment by zhuyuhua-v** [comment]
> @zhuyuhua-v why you enable GRUCell op only? Do you have any unit tests to verify it?

@frank-wei We only support [at::_thnn_fused_gru_cell](https://github.com/pytorch/pytorch/blob/b16cea7d8943617ac3839fb9d35070399091f818/aten/src/ATen/native/RNN.cpp#L724) for grucell's xpu path, and other cells haven't support yet. For this xpu path.
This modification made specifically for xpu path, does not affect the original func of rnn, and this change can only be verified on the xpu device, so we only add ut in our intel_extension_for_pytorch to verify it.

**Comment by gujinghui** [comment]
@ezyang  could you help review? Thanks.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
