### PR TITLE
Fix race condition

### PR DESCRIPTION
**Pull request by smessmer**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#11251 Fix race condition**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D9617237/)

There was a race condition when reading type names while they're registered.
We shouldn't read too often, so just adding a mutex shouldn't hurt.

Differential Revision: [D9617237](https://our.internmc.facebook.com/intern/diff/D9617237/)

### CODE REVIEW

**Comment by ezyang** [comment]
So, I do remember being the one who suggested that you just add a lock, but looking again at the method you added the lock to, I am actually not convinced it is not called all that often; there are certainly a decent number of call sites.

Can you run the experiment detailed https://fb.facebook.com/groups/101100140348621/permalink/536806433444654/ to see how many times name() is called in prod?

**Comment by ezyang** [comment]
Also, nothing to do with this PR, but I *really really really* want there to be single, canonical definitions of TypeMeta, so we can just store the `char*` pointer in it directly and be done with it...

**Comment by dzhulgakov** [comment]
Given that we special-case every single type anyway, we probably could just plug in more code into CAFFE_KNOWN_TYPE body that would also define statically initialized char* for the type name.

**Comment by ezyang** [comment]
That sounds reasonable to me.

**Comment by smessmer** [comment]
I ran multithreaded predictor benchmark and didn't see any regression. @dzhulgakov 's suggestion sounds good to me, I'll do a follow up PR, but first land this one to fix it.

**Comment by yf225** [comment]
@smessmer do you want to rebase onto master and then run the CI again? It might fix the flaky failures  :)

**Comment by zou3519** [comment]
cc @smessmer

**Comment by smessmer** [comment]
This isn't an issue anymore after the recent TypeMeta refactoring.

**Pull request closed without merging**
