### PR TITLE
fsdp.set_: convey to functionalization that it mutates storage

### PR DESCRIPTION
**Pull request by bdhirsh**
Fixes https://github.com/pytorch/pytorch/issues/132197

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #132338
* #132524
* __->__ #132322
* #132337
* #132243

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Sounds good!

**Comment by bdhirsh** [comment]
going to try to refactor all our `torch._functionalize*` utils to pybind in a prior PR to reduce boilerplate

**Review by yf225 — APPROVED** [review]
Thanks Brian!

**Pull request closed without merging**
