### PR TITLE
[easy] in ROCmTemplate set kwargs when creating Buffer

### PR DESCRIPTION
**Pull request by ColinPeppler**
Summary: https://github.com/pytorch/pytorch/pull/137768 makes Inductor IR kw only

Test Plan: CI

Differential Revision: D64723804

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by tenpercent — APPROVED** [review]
looks good, thanks for fixing!

**Review by chenyang78 — APPROVED** [review]

**Comment by ColinPeppler** [comment]
@pytorchbase merge

**Pull request closed without merging**
