### PR TITLE
Stop filling in defaults in Python binding layer.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#33826 Stop filling in defaults in Python binding layer.**
* #33518 Collapse _like overloads into a single overload.
* #33516 Add MemoryFormat to TensorOptions, but not codegen.
* #33825 Turn on strict dtype checking for test_torch.py

Now that C++ API has TensorOptions merging bugs fixed, we can now
just have the Python binding code accurately report when a kwarg
wasn't set, instead of filling in the defaults itself (and getting
it wrong, sometimes.)

Along the way, I made the python_arg_parser store a Layout directly
instead of a THPLayout, also nicely simplifying some more of the logic.

This PR also includes #33305 because it was easier to do this all in one go,
since removing the defaults in Python binding means I have to fix the
C++ code to fill in the correct defaults.

Differential Revision: [D20125792](https://our.internmc.facebook.com/intern/diff/D20125792)

### CODE REVIEW

**Comment by ezyang** [comment]
Hey @ailzhang @dlibenzi, take a look at this PR; I make some modifications to the logic of factory functions to make them fill in defaults correctly. Unfortunately, XLA is going to have to be adjusted to also fill in these defaults correctly too. At the very least, I'm triggering:

```
Feb 26 18:16:09 ======================================================================
Feb 26 18:16:09 ERROR [0.053s]: test_signal_window_functions_xla (__main__.TestTorchDeviceTypeXLA)
Feb 26 18:16:09 ----------------------------------------------------------------------
Feb 26 18:16:09 Traceback (most recent call last):
Feb 26 18:16:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 181, in instantiated_test
Feb 26 18:16:09     return test(self, device_arg)
Feb 26 18:16:09   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 7342, in test_signal_window_functions
Feb 26 18:16:09     test(window)
Feb 26 18:16:09   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 7333, in test
Feb 26 18:16:09     self.assertEqual(res, ref)
Feb 26 18:16:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 336, in assertEqual
Feb 26 18:16:09     return DeviceTypeTestBase.assertEqual(self, x, y, prec, message, allow_inf)
Feb 26 18:16:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 865, in assertEqual
Feb 26 18:16:09     assertTensorsEqual(x, y)
Feb 26 18:16:09   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 835, in assertTensorsEqual
Feb 26 18:16:09     self.assertLessEqual(max_err, prec, message)
Feb 26 18:16:09   File "/opt/conda/lib/python3.6/unittest/case.py", line 1213, in assertLessEqual
Feb 26 18:16:09     if not a <= b:
Feb 26 18:16:09 RuntimeError: Error while lowering: s64[3]{0} aten::cos
Feb 26 18:16:09 XLA builder error: Invalid argument: Expected element type in shape to be floating or complex for cosine operation; got S64.: 
Feb 26 18:16:09 Python Frames:
Feb 26 18:16:09 
Feb 26 18:16:09 
Feb 26 18:16:09 ----------------------------------------------------------------------
Feb 26 18:16:09 Ran 735 tests in 350.628s
```

**Comment by ezyang** [comment]
@bhosmer Sorry, you're going to have to reapprove this :(

**Comment by ezyang** [comment]
Old PR was at https://github.com/pytorch/pytorch/pull/33759

**Comment by ezyang** [comment]
@ailzhang @dlibenzi The window test failure repros on not XLA so it looks like it's my own damn fault :)

**Review by bhosmer — APPROVED** [review]
🚀

**Pull request closed without merging**
