### PR TITLE
[skip ci] rearrange tools/ folder

### PR DESCRIPTION
**Pull request by walterddr**
This is a demo of how I think we can rearrange files in tools/ folder

Reason
--

we've added many new scripts or modified scripts in tools/ .github/scripts, and .circleci/scripts and maybe scripts/?
There are some confusions regarding 
1. which script is used in CI, what is suppose to be used locally
2. we have a [README](https://github.com/pytorch/pytorch/blob/f2bb0932da3bc61a75867e4fec241ae8ca65b63e/tools/README.md) but not exactly covered, and the team need to spend time to maintain it
3. with a [recent attempt](https://github.com/pytorch/pytorch/pull/60019) to move some non-torch related scripts from torch/testing/* and test/* back into tools folder, I discovered that it is hard to find proper arrangement for these newly added files 

Proposal
--

I proposed to structure the tools/ folder into
- tools/linter --> all scripts related to linter
- tools/stats --> all scripts related to s3 stats
- tools/testing --> all scripts that will directly be used to customized CI (job or test cases)

Additionally, here are some of the extra thoughts
- tools/scripts --> move scripts/ folder into tools? (see: https://github.com/pytorch/pytorch/issues/52688)
- tools/build --> move build_* scripts in tools/ into the build folder (also the build_amd/ folder should be moved to build/)

Please discuss what could be the best arrangement for these scripts.

### CODE REVIEW

**Comment by janeyx99** [comment]
I agree in general it would be nice to have a better structure of our scripts/tools. Just some things to keep in mind before we land this:
1. We'd have to update references to these files in other repos/this repo, e.g., export_slow_tests.py is used in test-infra
2. Are there other scripts that aren't included in these categories? e.g., the docker scripts that install cuda and whatnot? (I think those could fall into build as well, but they do deserve their own subdirectory as there are lots of these)
3. Would this combine the scripts found in .circleci and .jenkins? 
4. I think this is a good idea as it lends to the next step of realizing which scripts are really similar and could be consolidated (maybe even with some scripts in builder as well)

**Comment by 1ntEgr8** [comment]
I like this structure! I had two questions:
- What are some examples of scripts that would go under `tools/testing`? The folder name might get confused with `tools/test`
- Are these folders "appended" to the existing list under `tools`? Or are we moving all files/directories currently under `tools` over to the new structure?

**Comment by walterddr** [comment]
> I agree in general it would be nice to have a better structure of our scripts/tools. Just some things to keep in mind before we land this:
> 
> 1. We'd have to update references to these files in other repos/this repo, e.g., export_slow_tests.py is used in test-infra

Yes. this PR is mainly for discussion purpose - (e.g. is there a better folder structure? do we want to arrange files differently?). But yes I will create most likely several PRs to rearrange files depending on how hard is it to update references. 

> 2. Are there other scripts that aren't included in these categories? e.g., the docker scripts that install cuda and whatnot? (I think those could fall into build as well, but they do deserve their own subdirectory as there are lots of these)
Please share if you think there could be a new category that we can add and which file can go into it. My knowledge towards the tools/ folder is limited so there must've been something I missed.

> 3. Would this combine the scripts found in .circleci and .jenkins?

As of this PR's scope, we are not considering moving other files into tools folder. This is mainly only fo rearranging `tools/`. 
- The next step after is moving non-torch related files/functions from `torch/testing/_internal` and `test/` to tools
- For scripts inside .circleci and .jenkins, maybe they are better off migrate to `scripts/` folder? (up for discussion but out of scope of this PR IMO.

> 4. I think this is a good idea as it lends to the next step of realizing which scripts are really similar and could be consolidated (maybe even with some scripts in builder as well)
- yes, exactly.


> I like this structure! I had two questions:
> 
> - What are some examples of scripts that would go under tools/testing? The folder name might get confused with tools/test

- I added 2 from this PR: explicit_ci_jobs.py and test_selections.py, both are controlling what test to run in a CI environment. 
- In addition, some functions in torch/testing/_internal/common_utils.py and test/run_test.py should also be refactored into tools/testing (such as test sharding and slow test determination)
Regarding tools/testing and tools/test, it is similar to the difference between torch/testing and torch/test, 
- testing/ is usually refer to the test utilities supporting run test
- test/ is actual test logics

> - Are these folders "appended" to the existing list under tools? Or are we moving all files/directories currently under tools over to the new structure?

I am not 100% sure I understood your question, but what I planned to do was to create these folders under tools/ and then move scripts around into these folders.

**Comment by walterddr** [comment]
Created #60473 as first step.

**Comment by walterddr** [comment]
this is done

**Pull request closed without merging**
