### PR TITLE
add xenial + cuda 9.2 + gcc 5.4 CI test

### PR DESCRIPTION
**Pull request by glaringlee**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#39036 [Reland] add xenial + cuda 9.2 + gcc 5.4 CI test**

This is to reland #38675, and test cpp_extension compatibility in _test only, this is enough, the purpose of this test is to make sure pytorch and cpp extension are compatible with xenial + cuda 9.2 + gcc 5.4

There are two non gcc5.4 (+ cuda9.2) compatible change introduced recently:
https://github.com/pytorch/pytorch/pull/37849
https://github.com/pytorch/pytorch/pull/38627
which caused the following problems:
https://app.circleci.com/pipelines/github/pytorch/pytorch/173756/workflows/7445e169-9c26-4ec4-a23a-ff6160d155b1/jobs/5582207/steps
https://app.circleci.com/pipelines/github/pytorch/pytorch/173970/workflows/bf0de0f2-9156-4c8f-a097-53ca8e20d4b0/jobs/5589265/steps

The root cause is that gcc 5.4 does not support uniform initialization list well, it can not deduce a correct type in some cases. It probably bugs in the gcc 5 compiler,  I modified these code a little bit to make them compatible with cuda 9.2 + gcc 5.4.

People are still using xenial + gcc5.4 + cuda 9.x, this env should be covered until xenial is deprecated. 

Differential Revision: [D21731026](https://our.internmc.facebook.com/intern/diff/D21731026)

### CODE REVIEW

**Comment by glaringlee** [comment]
I am using 'XImportant' here to force the build/test run in CI.
https://github.com/pytorch/pytorch/pull/39036/files#diff-f66fc3f8a3b96cde0be1c2ce3525bf6eR29
Will switch back to 'X' before landing.

**Review by malfet — APPROVED** [review]

**Comment by glaringlee** [comment]
@jjsjann123 @csarofeen I modified your recent landing a little to support gcc5.4 + cuda9.x which is still being used by people under ubuntu 16.04, please review or advise, thanks a lot.

**Review by jjsjann123 — APPROVED** [review]
Looks like it's only touching the list initialization thing for us. LGTM.

Thanks for pinging us on this. cc'ing @kevinstephano @csarofeen

**Comment by glaringlee** [comment]
@jjsjann123 
Thanks. Yes, gcc 5.4 doesn't support uniform list initialization well.......

**Pull request closed without merging**
