### PR TITLE
[Gradient Compression] Remove some low-level methods of GradBucket class

### PR DESCRIPTION
**Pull request by wayi1**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #53099 [Gradient Compression] Make GradBucket class public
* **#53098 [Gradient Compression] Remove some low-level methods of GradBucket class**
* #53010 [Gradient Compression] Add is_the_last_bucket_to_allreduce method to GradBucket class
* #53009 [Gradient Compression] Add get_per_parameter_tensors method to GradBucket class
* #53008 Clang-format c10d/init.cpp

Remove some low-level methods that are no longer needed since `get_per_parameter_tensors` method is added to `GradBucket` class.

Avoid unnecessary exposure to the internals before publishing GradBucket APIs.

Differential Revision: [D26720919](https://our.internmc.facebook.com/intern/diff/D26720919/)

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]

**Comment by osalpekar** [comment]
This seems to be breaking the following tests on master:
* ci/circleci: pytorch_windows_vs2019_py36_cuda11.1_test2
* ci/circleci: pytorch_windows_vs2019_py36_cuda10.1_test2

Will have to revert to keep master green.

**Comment by rohan-varma** [comment]
@osalpekar are these the CI jobs in question? https://app.circleci.com/pipelines/github/pytorch/pytorch/280269/workflows/6de5f188-6101-4d96-95fa-b5ad43c4b1e3/jobs/11268601 https://app.circleci.com/pipelines/github/pytorch/pytorch/280269/workflows/6de5f188-6101-4d96-95fa-b5ad43c4b1e3/jobs/11268634

It seems that those are failing some TCPStore tests, seems unrelated to this diff

**Comment by osalpekar** [comment]
@rohan-varma Those are the ones. The failures started with this PR and have continued consistently.
There's a TCPStore PR right before this (https://github.com/pytorch/pytorch/pull/52888) but these tests are passing there. @H-Huang - have you seen these errors/any chance they're related to your TCPStore change?

**Comment by rohan-varma** [comment]
My hypothesis is that these tests that are failing didn't run on that PR, since the issues disabling those tests such as https://github.com/pytorch/pytorch/issues/52839 were open at the time that PR landed, but were closed around the time this change landed, hence the failures started here

**Comment by osalpekar** [comment]
Interesting, I guess we can safely re-land this PR then - we'll reopen the Issues disabling the TCPStore tests in the meantime.

**Comment by H-Huang** [comment]
Yes, the failures were due to closing the issues that disabled TCPStore tests, sorry about that.

**Pull request closed without merging**
