### PR TITLE
Fix & optimize open device registration test.

### PR DESCRIPTION
**Pull request by fffrog**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125572

1. Fix the wrong tests about lazy init for PrivateUse1 named foo
2. Refactor the tests and make it more flexible
3. Disable the two tests temporarily
     - test_open_device_faketensor
     - test_open_device_scalar_type_fallback

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Awesome!
Thanks for cleaning this up!

**Comment by kit1980** [comment]
@FFFrog The issue is probably beyond your control, likely internal build files need to be updated. Maybe @albanD can import this again and try to figure out?

**Comment by albanD** [comment]
Yeah I'll try to import the follow up that adds it

**Comment by FFFrog** [comment]
> @FFFrog The issue is probably beyond your control, likely internal build files need to be updated. Maybe @albanD can import this again and try to figure out?

Got it :D

**Pull request closed without merging**
