### PR TITLE
[build] Make ATen buildable without all Caffe2 by root cmake

### PR DESCRIPTION
**Pull request by orionr**
* Allows us to build ATen as a part of libcaffe2.so (statically linked for now) and also disable large parts of the Caffe2 code.
* Next step will be for PyTorch setup.py to depend on a version of libcaffe2.so instead of libATen.so

I ran the following builds to test locally
```
cd ~/local/pytorch
mkdir build; cd build; cmake ..; make -j 8
cd ..; rm -rf build; mkdir build; cd build; cmake -DBUILD_CAFFE2=ON -DBUILD_ATEN=ON -DUSE_CUDA=ON ..
cd ..; rm -rf build; mkdir build; cd build; cmake -DBUILD_CAFFE2=OFF -DBUILD_ATEN=ON -DUSE_CUDA=ON ..
```
Now kicking off contbuild here.

cc @Yangqing, @ezyang and @pjh5 for review. Thanks.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
What's the plan for unifying dependency finding?

**Comment by orionr** [comment]
Investigating failures...

**Comment by orionr** [comment]
For dependency finding, looks like there were still some `Find*.cmake` that needed to get unified/moved, so I put that up at https://github.com/pytorch/pytorch/pull/7300

**Pull request merged**
