### PR TITLE
Benchmark flag to include slowdowns when computing gmean of speedups over eager

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #110313
* #110183
* #110178
* #108376
* __->__ #108375

`clip(1)` excludes slowdowns by treating them as 1x.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @anijain2305

### CODE REVIEW

**Comment by BowenBao** [comment]
cc @malfet for review.

**Comment by ezyang** [comment]
The clipping to 1.0x is intentional for torch.compile because you can always use eager if compile is not speeding things up. If you want a different setting for ONNXRT it needs to be configurable.

**Comment by BowenBao** [comment]
Introduced a flag to runner.py. By default the behavior is unchanged. ptal @ezyang 

Although, I'm not quite following the argument ... The same can be said for accuracy that one can always use eager then you could say passrate is always 100% ...

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
