### PR TITLE
Partially parallelize randperm on CPU.

### PR DESCRIPTION
**Pull request by xuhdev**
This commit parallelizes the variable initialization (from 1 to n) step on CPU.

### CODE REVIEW

**Comment by jeffreyksmithjr** [comment]
This could use a more detailed description, if there is more context around this change.

**Comment by xuhdev** [comment]
@jeffreyksmithjr Thanks, I updated the description. I don't have much more to say -- this is a pretty general performance improvement that is self-explanatory.

**Review by VitalyFedyunin — DISMISSED** [review]
Generally looks good, but consider:
1) moving cpu code into the native/cpu folder, as it will enable AVX support.
2) implement special code branch for the situation when  `r__stride_0 == 1` as it is going be almost always the case, and the kernel will work much faster.

**Comment by xuhdev** [comment]
@VitalyFedyunin Thanks, this is really good to know. I will try to look into how to make many CPU functions to the `native/cpu` folder.

Do you happen to know where I can systematically learn these kinds of information for PyTorch internals? It would be quite helpful if such a document is available.

**Comment by VitalyFedyunin** [comment]
We are working on better doc now, so far you can look at aten/src/ATen/native/cpu/README.md

Also it is reasonable to attach benchmark methodology and results, especially if you are working on performance related tasks.

**Comment by xuhdev** [comment]
@VitalyFedyunin  I looked into the code again. I kind of what to change the implementation to make use of `arange_out` instead of implementing once again, and leave all possible future optimization (if it will ever happen) to `arange_out`. I have changed the current code to follow this thought. What do you think?

But I only did this for `stride == 1` -- I looked into the code of `range_cpu_out`, and it seems to assume that stride is always 1. I'm a bit confused: Is it same to assume stride to be 1, or `arange_out` didn't do it correctly?

**Comment by zhangguanheng66** [comment]
@VitalyFedyunin Do you mind if you could take a look at the recent commits and land the PR? Thanks.

**Comment by VitalyFedyunin** [comment]
Sure you can, go ahead with it. Even previous state was fine. I even recommend to remove this ==1 check, as It is implemented incorrectly. What I meant by previous comment is something like:

```cpp

if (r__stride == 1) {
 at::parallel_for(0, n, internal::GRAIN_SIZE,
                    [&r__data, &r__stride_0](int64_t p_begin, int64_t p_end) {
      for(int64_t i = p_begin; i < p_end; i++)
        r__data[i] = static_cast<scalar_t>(i);
    }); 
}
else {
 at::parallel_for(0, n, internal::GRAIN_SIZE,
                    [&r__data, &r__stride_0](int64_t p_begin, int64_t p_end) {
      for(int64_t i = p_begin; i < p_end; i++)
        r__data[i*r__stride_0] = static_cast<scalar_t>(i);
    });
}

```

Which helps to avoid multiplication.

But previous version with just:

```cpp
 at::parallel_for(0, n, internal::GRAIN_SIZE,
                    [&r__data, &r__stride_0](int64_t p_begin, int64_t p_end) {
      for(int64_t i = p_begin; i < p_end; i++)
        r__data[i*r__stride_0] = static_cast<scalar_t>(i);
    });
```
is also good

**Comment by xuhdev** [comment]
Sure, restored.

**Review by VitalyFedyunin — APPROVED** [review]

**Pull request closed without merging**
