### PR TITLE
[ROCm] add exact_dtype=False to bfloat16 test

### PR DESCRIPTION
**Pull request by jeffdaily**
CC @rohithkrn @ezyang @xw285cornell 

Fixes
- TestNNDeviceTypeCUDA.test_activations_bfloat16_cuda
- TestNNDeviceTypeCUDA.test_pooling_bfloat16_cuda
- TestNNDeviceTypeCUDA.test_softmax_bfloat16_cuda

### CODE REVIEW

**Review by ezyang — CHANGES_REQUESTED** [review]
Please condition these on being ROCm. And you should fix these bugs eventually!

**Comment by ezyang** [comment]
Actually since this unbreaks CI I'm going to land it. Please do the follow up though.

**Review by ezyang — APPROVED** [review]

**Comment by jeffdaily** [comment]
After discussion with @rohithkrn, we need some clarification.  We don’t know if it’s truly a bug, the test does computation in float32 and uses it as reference to compare against bfloat16 computation.  How is this handled in other tests, if any?  Also, these tests are marked `@onlyCUDA @skipCUDAIfNotRocm`, so in a way, they're already conditional on being ROCm only.

**Comment by ezyang** [comment]
Oh, if the tests are ROCm only, then non-exact is fine. No follow up needed!

**Pull request closed without merging**
