### PR TITLE
mul(sparse, sparse): temporarily force coalesce to prevent potential OOM.

### PR DESCRIPTION
**Pull request by nikitaved**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #84469
* #83428
* #83427

This PR temporarily forces coalesced inputs to prevent potential OOMs on the user's end.
For example:
```python
In [1]: import torch

In [2]: idx = torch.zeros(2, 3, dtype=torch.long)

In [3]: val = torch.rand(3)

In [4]: s = torch.sparse_coo_tensor(idx, val, (100, 100))

In [5]: for i in range(4):
   ...:     s = s * s
   ...:     print(f"(s * s).nnz = {s._nnz()}")
   ...: 
(s * s).nnz = 9
(s * s).nnz = 81
(s * s).nnz = 6561
(s * s).nnz = 43046721

```
This comes at a performance cost since `coalesce` is an expensive operation.
Once we figure out whether we need this performance back and how to communicate the change to the user, we can undo these changes.

<details>

<summary>CUDA benchmarks without/with coalesce</summary>

```
[--------------------------------------------------------- coo.mul ----------------------------------------------------------]
                                                       |  PR_no_coalesce: mul, device: cuda  |  PR_coalesce: mul, device: cuda
24 threads: ------------------------------------------------------------------------------------------------------------------
      n=10000, nnz=100, coalesce=((True, True))        |                   87                |                 87
      n=10000, nnz=100, coalesce=((True, False))       |                   87                |                225
      n=10000, nnz=100, coalesce=((False, True))       |                  100                |                240
      n=10000, nnz=100, coalesce=((False, False))      |                  100                |                379
      n=100000, nnz=1000, coalesce=((True, True))      |                   93                |                102
      n=100000, nnz=1000, coalesce=((True, False))     |                   99                |                252
      n=100000, nnz=1000, coalesce=((False, True))     |                  101                |                254
      n=100000, nnz=1000, coalesce=((False, False))    |                  200                |                391
      n=1000000, nnz=10000, coalesce=((True, True))    |                  100                |                 97
      n=1000000, nnz=10000, coalesce=((True, False))   |                  100                |                280
      n=1000000, nnz=10000, coalesce=((False, True))   |                   90                |                276
      n=1000000, nnz=10000, coalesce=((False, False))  |                  379                |                436
      n=10, nnz=100, coalesce=((True, True))           |                  110                |                100
      n=10, nnz=100, coalesce=((True, False))          |                  111                |                248
      n=10, nnz=100, coalesce=((False, True))          |                  112                |                248
      n=10, nnz=100, coalesce=((False, False))         |                  141                |                395
      n=10, nnz=1000, coalesce=((True, True))          |                  100                |                100
      n=10, nnz=1000, coalesce=((True, False))         |                  110                |                264
      n=10, nnz=1000, coalesce=((False, True))         |                  100                |                265
      n=10, nnz=1000, coalesce=((False, False))        |                  100                |                408
      n=10, nnz=10000, coalesce=((True, True))         |                  100                |                100
      n=10, nnz=10000, coalesce=((True, False))        |                  104                |                289
      n=10, nnz=10000, coalesce=((False, True))        |                  100                |                268
      n=10, nnz=10000, coalesce=((False, False))       |                  288                |                450
      n=100, nnz=1000, coalesce=((True, True))         |                  100                |                113
      n=100, nnz=1000, coalesce=((True, False))        |                  114                |                264
      n=100, nnz=1000, coalesce=((False, True))        |                  114                |                264
      n=100, nnz=1000, coalesce=((False, False))       |                  200                |                408
      n=100, nnz=10000, coalesce=((True, True))        |                  100                |                114
      n=100, nnz=10000, coalesce=((True, False))       |                  110                |                293
      n=100, nnz=10000, coalesce=((False, True))       |                  110                |                289
      n=100, nnz=10000, coalesce=((False, False))      |                  257                |                449
      n=1000, nnz=10000, coalesce=((True, True))       |                  110                |                110
      n=1000, nnz=10000, coalesce=((True, False))      |                  110                |                283
      n=1000, nnz=10000, coalesce=((False, True))      |                  110                |                283
      n=1000, nnz=10000, coalesce=((False, False))     |                  264                |                447
      n=1000, nnz=100000, coalesce=((True, True))      |                  130                |                121
      n=1000, nnz=100000, coalesce=((True, False))     |                  180                |                396
      n=1000, nnz=100000, coalesce=((False, True))     |                  200                |                391
      n=1000, nnz=100000, coalesce=((False, False))    |                  377                |                669
      n=1000, nnz=1000000, coalesce=((True, True))     |                  312                |                311
      n=1000, nnz=1000000, coalesce=((True, False))    |                 1300                |               2992
      n=1000, nnz=1000000, coalesce=((False, True))    |                 1300                |               3012
      n=1000, nnz=1000000, coalesce=((False, False))   |                 4418                |               5757

Times are in microseconds (us).

```

</details>

### CODE REVIEW

**Comment by nikitaved** [comment]
I think this is the best solution given the circumstances also because the kernel does not detect potential overflows and hence does not error out. But I am not sure whether PyTorch kernels even check such issues, say in `sum, cumsum` and likes...

**Review by amjames — COMMENTED** [review]
The logic is sound and the change looks good, but I wonder if this is the best course of action. 

If we allow the potential OOM problem to exist we would be able to asses the impact on users via their reports. Users reporting issues would be able to coalesce manually and not be blocked, but they would have the freedom to coalesce less frequently if their situation allows. 

I think it unlikely that a given users would need to coalesce before every binary op to avoid this situation.

**Comment by nikitaved** [comment]
@amjames , we do not know whether neural net models might blow up...

**Comment by bhosmer** [comment]
@amjames I think the worry is that we would *introduce* the OOMing behavior to unchanged user code. Given that COO is the sparse PyTorch format in current use, this seems... potentially non-academic? It seems unlikely that we could get real call-site usage data, so this is basically an abundance of caution move. 

But yeah if it were just a matter of designing the behavior of a new op, then I agree (as does @nikitaved, I think) that giving callers control over coalescing would be optimal. 

@nikitaved couple random post-weekend thoughts about fancier solutions -
- is there a tripwire we could add that would force-coalesce based on properties observed during the intersection computation, but before allocation? E.g. if `nnz` would grow more than a certain low percentage, or at all. Those cases could be allowed to regress within reason. Not sure if the structure of the code would admit this change without disruption though.
- more far-out (and disruptive) but just thinking out loud, it feels like the hashing is halfway to coalescing already - is there profit in fusing a coalesce with the binop, i.e. always produce a coalesced result, even from uncoalesced input(s)?

**Comment by nikitaved** [comment]
>     * is there a tripwire we could add that would force-coalesce based on properties observed during the intersection computation, but before allocation? E.g. if `nnz` would grow more than a certain low percentage, or at all. Those cases could be allowed to regress within reason. Not sure if the structure of the code would admit this change without disruption though.

Not yet, no, but we can trim inputs based on their `nnz` indeed.

>     * more far-out (and disruptive) but just thinking out loud, it feels like the hashing is halfway to coalescing already - is there profit in fusing a coalesce with the binop, i.e. always produce a coalesced result, even from uncoalesced input(s)?

No, hashing and hash intersection is asynchronous, while coalescing will require synchronizations (i.e. atomic adds). However, this step is most likely unavoidable for union-like sparse ops (i.e. `add`, for example).

**Comment by nikitaved** [comment]
From the offline discussion: we decided to remove force-coalesce for now. `mul(sparse, sparse)` is unlikely to break any pre-existing models due to its previous slow performance.

**Pull request closed without merging**
