### PR TITLE
[CI] Install compatible cmath for Win binary builds

### PR DESCRIPTION
**Pull request by malfet**

### CODE REVIEW

**Comment by seemethere** [comment]
looks like you need to run the `.circleci/regenerate.sh` script as well here

**Comment by walterddr** [comment]
I think this might be related to #54545

**Review by seemethere — APPROVED** [review]

**Review by walterddr — APPROVED** [review]

**Comment by malfet** [comment]
@seemethere for some reason regen.sh is a no-op for me, had to run `generate_config_yml.py >config.yaml` manually.

**Comment by walterddr** [comment]
> @seemethere for some reason regen.sh is a no-op for me, had to run `generate_config_yml.py >config.yaml` manually.

Yes. That was fixed in #54545

**Pull request closed without merging**
