### PR TITLE
Utilise the vector version for sinh and cosh (UnaryOpsKernel)

### PR DESCRIPTION
**Pull request by kshitij12345**
Utilise the existing methods of `Vec256` class.

Not sure if there should be tests and if yes where.

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
Please include single-threaded before-after perf comparison on large tensors.

**Comment by kshitij12345** [comment]
@VitalyFedyunin Thanks for reviewing. Will do that and update.

**Comment by kshitij12345** [comment]
**Operator : sinh**
Benchmark with same build settings on same system.
gcc : version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
CPU : Intel® Core i5-8300H CPU @ 2.30GHz × 8

```python
import timeit

for n, t in [(250, 20000),
             (500, 20000)]:
    for dtype in ('torch.float', 'torch.double'):
        print(f'torch.sinh(a) a.numel() == {n} for {t} times {dtype}')
        print(timeit.timeit(f'torch.sinh(a);',
                              setup=f'import torch; a=torch.randn(({n}, {n}), dtype={dtype}, device="cpu")',
                              number=t))
```

Before:

```
torch.sinh(a) a.numel() == 250 for 20000 times torch.float
14.09677987300529
torch.sinh(a) a.numel() == 250 for 20000 times torch.double
13.460128810002061
torch.sinh(a) a.numel() == 500 for 20000 times torch.float
29.295550972005003
torch.sinh(a) a.numel() == 500 for 20000 times torch.double
30.134398206995684
```

After:

```
torch.sinh(a) a.numel() == 250 for 20000 times torch.float
1.7807423799968092
torch.sinh(a) a.numel() == 250 for 20000 times torch.double
3.603937173000304
torch.sinh(a) a.numel() == 500 for 20000 times torch.float
4.371455088999937
torch.sinh(a) a.numel() == 500 for 20000 times torch.double
8.193280207000498
```

---------------------------------------

**Operator : cosh**
Benchmark with same build settings on same system.
gcc : version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
CPU : Intel® Core i5-8300H CPU @ 2.30GHz × 8

```python
import timeit

for n, t in [(250, 20000),
             (500, 20000)]:
    for dtype in ('torch.float', 'torch.double'):
        print(f'torch.cosh(a) a.numel() == {n} for {t} times {dtype}')
        print(timeit.timeit(f'torch.cosh(a);',
                              setup=f'import torch; a=torch.randn(({n}, {n}), dtype={dtype}, device="cpu")',
                              number=t))
```

Before:

```
torch.cosh(a) a.numel() == 250 for 20000 times torch.float
7.498913914998411
torch.cosh(a) a.numel() == 250 for 20000 times torch.double
9.886695310000505
torch.cosh(a) a.numel() == 500 for 20000 times torch.float
16.88009168500139
torch.cosh(a) a.numel() == 500 for 20000 times torch.double
22.92534487300145
```

After:

```
torch.cosh(a) a.numel() == 250 for 20000 times torch.float
1.6786035350014572
torch.cosh(a) a.numel() == 250 for 20000 times torch.double
3.5073356840002816
torch.cosh(a) a.numel() == 500 for 20000 times torch.float
4.145828925997193
torch.cosh(a) a.numel() == 500 for 20000 times torch.double
7.687253905001853
```

**Comment by VitalyFedyunin** [comment]
Code looks good. I will take a look at numerical and land it shortly.

**Comment by kshitij12345** [comment]
@VitalyFedyunin Sure. Thanks.

**Comment by kshitij12345** [comment]
@VitalyFedyunin Gentle Ping:)

**Review by VitalyFedyunin — APPROVED** [review]

**Pull request closed without merging**
