### PR TITLE
[inductor] Relax type annotations for statically_known_*

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #126417
* #126416
* __->__ #126655
* #126631

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by shunting314 — APPROVED** [review]
Looks good. Just curious why we don't loose the type annotation for the `left` argument as well?

**Comment by jansel** [comment]
> Looks good. Just curious why we don't loose the type annotation for the `left` argument as well?

We could, but calling it on (int, int) doesn't make any sense.

**Comment by shunting314** [comment]
> We could, but calling it on (int, int) doesn't make any sense.

But (sympy.Expr, int) is legit? lol

**Pull request closed without merging**
