### PR TITLE
Fix TestBufferProtocolCPU::test_byte_to_int_cpu test on Big Endian

### PR DESCRIPTION
**Pull request by AlekseiNikiforovIBM**
Fix TestBufferProtocolCPU::test_byte_to_int_cpu test on Big Endian

### CODE REVIEW

**Comment by janeyx99** [comment]
Could you please add a description? It can be similar to your title.

**Comment by AlekseiNikiforovIBM** [comment]
Copied title to description.

**Comment by janeyx99** [comment]
It looks like CI had gone through some infra issues. Do you mind rebasing to retest?

**Comment by AlekseiNikiforovIBM** [comment]
Sure, done.

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
