### PR TITLE
add optional refining

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #69871
* #71170
* #71121
* __->__ #69776
* #69775
* #69645

If we have an node output which is an optional type, but both if blocks produce a non-optional value, we can try to refine the if output type, which can open up further optimization opportunities.

Differential Revision: [D33515235](https://our.internmc.facebook.com/intern/diff/D33515235)

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]
LGMT

**Review by Neilblaze — APPROVED** [review]

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33515235).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33515235).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33515235).

**Pull request closed without merging**
