### PR TITLE
Update tensor factory method docs

### PR DESCRIPTION
**Pull request by zou3519**
Also add new docs for `torch.empty`.

cc @gchanan @SsnL

### CODE REVIEW

**Comment by SsnL** [comment]
Cool! Can you also add `full` and `full_like` please? :)

**Comment by ezyang** [comment]
I'm wondering if there's a reasonable way we can avoid copy-pasting the same block of three arguments to every site. Maybe not...

**Comment by zou3519** [comment]
Oh! Docstrings are strings so I could just add them together... Will look into it

**Comment by zou3519** [comment]
@gchanan how does this look to you?

**Review by ezyang — APPROVED** [review]

**Pull request merged**
