### PR TITLE
Move tools/autograd to torchgen/autograd

### PR DESCRIPTION
**Pull request by zou3519**
Summary:
Performed with:
```
hg move tools/autograd torchgen/autograd
sed -i 's$tools/autograd$torchgen/autograd$g' $(find . -type f)
sed -i 's$tools.autograd$torchgen.autograd$g' $(find . -type f)
# + some manual modification to tools/setup_helpers/generate_code.py and BUCK files
```

Test Plan: Existing tests

Differential Revision: D47375735

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Sounds good!

**Comment by soulitzer** [comment]
Noob question: What's the context behind this? That we'd like to have more codegen things in torchgen which is supposed to be a more standalone thing? Does this change unblock anything in particular, or just a general improvement.

**Comment by zou3519** [comment]
https://github.com/pytorch/pytorch/issues/100684 is the motivation.

**Comment by albanD** [comment]
Note that this will also conflict with Compiled Autograd which is landing right now

**Comment by zou3519** [comment]
@albanD what's the timeline for landing compiled autograd?

**Comment by albanD** [comment]
Just happened! Rebasing now should get it.

**Comment by zou3519** [comment]
Cool, I'll try again when it makes it internally

**Comment by huihoaan** [comment]
@zou3519 Have you Solved the problem？ It's August now， I hope this pr can be merged as soon as possible

**Comment by zou3519** [comment]
@huihoaan this is a fairly involved and difficult refactor of both our OSS and meta-internal pytorch builds. Is there anything we can do as a workaround? Otherwise, this project is not that high up in the priority queue for us.

**Comment by huihoaan** [comment]
@zou3519  I think it's sufficient to copy-pasting the contents of tools/autograd into torchgen.  I just want to be able to use the codes in tools/autograd, but don't care where the original code is.

**Comment by heidongxianhua** [comment]
> @huihoaan this is a fairly involved and difficult refactor of both our OSS and meta-internal pytorch builds. Is there anything we can do as a workaround? Otherwise, this project is not that high up in the priority queue for us.
> 
> For example, if just copy-pasting the contents of tools/autograd into torchgen is sufficient, then that's an easier thing to do.

yeah, and I give a PR to do it, could you have a look? https://github.com/pytorch/pytorch/pull/106663 @zou3519

**Pull request closed without merging**
