### PR TITLE
Fix Vulkan Api Backend Build Error

### LINKED ISSUE #48483: Vulkan Api Backend Build Error with GCC
## To Reproduce

1. ccmake config with USE_VULKAN_API=1
2. ninja build

## Environment

Currently using gcc-10.2.0

## Additional context

many errors:
e.g.:
```
../aten/src/ATen/native/vulkan/ops/Tensor.h:390:19: error: ‘class at::native::vulkan::ops::vTensor::View::State’ is private within this context
  390 |       const View::State::Bundle&);
```
```
../aten/src/ATen/native/vulkan/api/Pipeline.h:119:41: error: declaration of ‘typedef class at::native::vulkan::api::Handle<VkPipeline_T*, at::native::vulkan::api::destroy_Pipeline> at::native::vulkan::api::Pipeline::Factory::Handle’ changes meaning of ‘Handle’ [-fpermissive]
  119 |     typedef Handle<VkPipeline, Deleter> Handle;
```

### PR DESCRIPTION
**Pull request by void-universe**
Fixes #48483

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
Please rebase your PR against top of tree to resolve merge conflict.
And please add bit more details on what exactly this change is fixing.
Something along the lines of "Rename Handle to Handler to avoid name collision with Handle define in XYZ"

**Comment by AshkanAliabadi** [comment]
Hey MP5A3.  Welcome to the community.  If you are still interested in carrying through with this patch, here are a couple of points:

- The change from Handle to Handler to avoid shadowing is great.  Thank you.
- I am not convinced avoiding use of anonymous structs is necessary but clearly if that is what the compiler is complaining about, that's what we will do.  Please let me know if your version of the compiler (GCC 10.2 from the looks of it) is unhappy with use of anonymous structs.  If it indeed is, I suggest avoiding putting the declaration of those structs in common header files as it is an implementation detail that is only relevant to these files individually.  My preference would be to have it this way so the declaration is contained to a smaller scope:

```
// Add.cpp as an example

const struct Block final {
  // definition
} block {
  // initialization
};

// Use as before
context->resource().pool.uniform(block).object
```

Thanks for your contribution.

**Comment by MP5A3** [comment]
> Hey MP5A3. Welcome to the community. If you are still interested in carrying through with this patch, here are a couple of points:
> 
> * The change from Handle to Handler to avoid shadowing is great.  Thank you.
> * I am not convinced avoiding use of anonymous structs is necessary but clearly if that is what the compiler is complaining about, that's what we will do.  Please let me know if your version of the compiler (GCC 10.2 from the looks of it) is unhappy with use of anonymous structs.  If it indeed is, I suggest avoiding putting the declaration of those structs in common header files as it is an implementation detail that is only relevant to these files individually.  My preference would be to have it this way so the declaration is contained to a smaller scope:
> 
> ```
> // Add.cpp as an example
> 
> const struct Block final {
>   // definition
> } block {
>   // initialization
> };
> 
> // Use as before
> context->resource().pool.uniform(block).object
> ```
> 
> Thanks for your contribution.

Hi AshkanAliabadi, your suggestions about the anonymous structs modification still leads to the same build error, I'd move the structs from common.h to each distinct .cpp file.

**Review by AshkanAliabadi — APPROVED** [review]
Thanks, I'll merge this soon.

**Comment by malfet** [comment]
@AshkanAliabadi , @MP5A3 are you going to look into merge conflicts?

**Comment by AshkanAliabadi** [comment]
Yes, busy with PSC, lol, I'll be on it after Thursday.

**Pull request closed without merging**
