### PR TITLE
Merge Inductor perf smoke test with other inductor CI tests

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #93395

Summary: Now the smoke test can also be triggered with the
ciflow/inductor label.

### CODE REVIEW

**Review by weiwangmeta — APPROVED** [review]
LGTM. I will keep an eye on the queue time of A100, and increase runners if needed.

**Review by malfet — APPROVED** [review]
Would there be enough capacity?

**Comment by weiwangmeta** [comment]
> Would there be enough capacity?

The standalone action was already running for every push to the master, the capacity is enough. 
This move operation may increase the load, if more PRs add ciflow/inductor label. I will monitor and ensure we have enough capacity.

**Comment by ngimel** [comment]
Perf smoke test takes ~1min, it's very little compared to all the other accuracy sweeps we are running

**Comment by weiwangmeta** [comment]
> Perf smoke test takes ~1min, it's very little compared to all the other accuracy sweeps we are running

Good point, we might just have identified a BE work. This smoke test job spent most of its time checking out torchbench. There might be a way to skip that. 
FYI, these torchbench setup tests were taking like 20 minutes, will see if this can be saved. https://github.com/pytorch/pytorch/actions/runs/4076511843/jobs/7024936041#step:11:1128

**Pull request closed without merging**
