### PR TITLE
[2/N] Use std::in_place

### PR DESCRIPTION
**Pull request by cyyever**
Remove c10/util/in_place.h

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Was this header file ever used since it's never included?

**Comment by soulitzer** [comment]
I think it was removed in a previous PR by @cyyever 
There are internal usages however that need to be addressed https://www.internalfb.com/diff/D52123195

**Comment by albanD** [comment]
Ok!
I'll let you land both @soulitzer !

**Review by soulitzer — APPROVED** [review]

**Comment by osalpekar** [comment]
@soulitzer This is breaking a large number of contbuilds due to internal usage of `c10::in_place`. Can you check them here and forward-fix: [D52178758](https://www.internalfb.com/diff/D52178758)? Either that or we'll need to revert

**Comment by cyyever** [comment]
Use regex to replace 'c10::in_place' to 'std::in_place' should fix them.

**Comment by soulitzer** [comment]
@osalpekar Updated the diff!

**Pull request closed without merging**
