### PR TITLE
[CUDACachingAllocator] Turn Allocator::allocate into non-const

### PR DESCRIPTION
**Pull request by cyyever**
Ideally, the method should be non-const since it changes the allocator state. Some const_casts are also removed in the way.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by jeffdaily** [comment]
@cyyever Can you put in the description why this is needed?  I'm not completely familiar with this part of the code so it would help my review.

**Review by albanD — APPROVED** [review]
Thanks for the cleanup!
@jeffdaily I don't think there is much more context on this than cleaning up the const-correctness of our codebase.

FYI @zdevito as the original author of these surprised comments.

**Pull request closed without merging**
