### PR TITLE
Enable function declaration check in Vulkan and Metal backends

### PR DESCRIPTION
**Pull request by cyyever**
This PR enables declaration check in Vulkan and Metal backends, so that we can identify unused functions more easily.

cc @malfet @ezyang @Skylion007

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
windows failure looks legit

**Comment by ezyang** [comment]
failures look legit

```
2023-09-26T05:50:12.4254520Z FAILED: caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/metal/ops/MetalReduce.mm.o 
2023-09-26T05:50:12.4259380Z /var/folders/xq/_s_zr8fx7879r5bx0nqtqzsh0000gn/T/tmp.DFGAwQOP/clang++ -DAT_PER_OPERATOR_HEADERS -DCAFFE2_BUILD_MAIN_LIB -DCPUINFO_SUPPORTED_PLATFORM=1 -DFMT_HEADER_ONLY=1 -DFXDIV_USE_INLINE_ASSEMBLY=0 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DNNP_CONVOLUTION_ONLY=0 -DNNP_INFERENCE_ONLY=0 -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DUSE_EXTERNAL_MZCRC -D_FILE_OFFSET_BITS=64 -Dtorch_cpu_EXPORTS -I/Users/ec2-user/runner/_work/pytorch/pytorch/build/aten/src -I/Users/ec2-user/runner/_work/pytorch/pytorch/aten/src -I/Users/ec2-user/runner/_work/pytorch/pytorch/build -I/Users/ec2-user/runner/_work/pytorch/pytorch -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/onnx -I/Users/ec2-user/runner/_work/pytorch/pytorch/build/third_party/onnx -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/foxi -I/Users/ec2-user/runner/_work/pytorch/pytorch/build/third_party/foxi -I/Users/ec2-user/runner/_work/pytorch/pytorch/torch/csrc/api -I/Users/ec2-user/runner/_work/pytorch/pytorch/torch/csrc/api/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/caffe2/aten/src/TH -I/Users/ec2-user/runner/_work/pytorch/pytorch/build/caffe2/aten/src/TH -I/Users/ec2-user/runner/_work/pytorch/pytorch/build/caffe2/aten/src -I/Users/ec2-user/runner/_work/pytorch/pytorch/build/caffe2/../aten/src -I/Users/ec2-user/runner/_work/pytorch/pytorch/torch/csrc -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/miniz-2.1.0 -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/kineto/libkineto/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/kineto/libkineto/src -I/Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/.. -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/FXdiv/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/c10/.. -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/pthreadpool/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/cpuinfo/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/native/quantized/cpu/qnnpack/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/native/quantized/cpu/qnnpack/src -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/cpuinfo/deps/clog/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/NNPACK/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/FP16/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/fmt/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/flatbuffers/include -isystem /Users/ec2-user/runner/_work/pytorch/pytorch/third_party/protobuf/src -isystem /Users/ec2-user/runner/_work/pytorch/pytorch/third_party/XNNPACK/include -isystem /Users/ec2-user/runner/_work/pytorch/pytorch/cmake/../third_party/eigen -isystem /Users/ec2-user/runner/_work/pytorch/pytorch/build/include -x objective-c++ -DUSE_MPS -fno-objc-arc -Wno-unguarded-availability-new -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -fPIC -F/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks  -D__NEON__ -Wmissing-prototypes -Werror=missing-prototypes -std=gnu++17 -MD -MT caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/metal/ops/MetalReduce.mm.o -MF caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/metal/ops/MetalReduce.mm.o.d -o caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/metal/ops/MetalReduce.mm.o -c /Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/native/metal/ops/MetalReduce.mm
2023-09-26T05:50:12.4263540Z /Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/native/metal/ops/MetalReduce.mm:31:8: error: no previous prototype for function 'wrapper_mean_dim' [-Werror,-Wmissing-prototypes]
2023-09-26T05:50:12.4263850Z Tensor wrapper_mean_dim(
2023-09-26T05:50:12.4264000Z        ^
2023-09-26T05:50:12.4264360Z /Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/native/metal/ops/MetalReduce.mm:31:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
2023-09-26T05:50:12.4264640Z Tensor wrapper_mean_dim(
2023-09-26T05:50:12.4264770Z ^
2023-09-26T05:50:12.4264930Z static 
2023-09-26T05:50:12.4265060Z 1 error generated.
```

**Comment by cyyever** [comment]
> failures look legit
> 
> 
> 
> ```
> 
> 2023-09-26T05:50:12.4254520Z FAILED: caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/metal/ops/MetalReduce.mm.o 
> 
> 2023-09-26T05:50:12.4259380Z /var/folders/xq/_s_zr8fx7879r5bx0nqtqzsh0000gn/T/tmp.DFGAwQOP/clang++ -DAT_PER_OPERATOR_HEADERS -DCAFFE2_BUILD_MAIN_LIB -DCPUINFO_SUPPORTED_PLATFORM=1 -DFMT_HEADER_ONLY=1 -DFXDIV_USE_INLINE_ASSEMBLY=0 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DNNP_CONVOLUTION_ONLY=0 -DNNP_INFERENCE_ONLY=0 -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DUSE_EXTERNAL_MZCRC -D_FILE_OFFSET_BITS=64 -Dtorch_cpu_EXPORTS -I/Users/ec2-user/runner/_work/pytorch/pytorch/build/aten/src -I/Users/ec2-user/runner/_work/pytorch/pytorch/aten/src -I/Users/ec2-user/runner/_work/pytorch/pytorch/build -I/Users/ec2-user/runner/_work/pytorch/pytorch -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/onnx -I/Users/ec2-user/runner/_work/pytorch/pytorch/build/third_party/onnx -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/foxi -I/Users/ec2-user/runner/_work/pytorch/pytorch/build/third_party/foxi -I/Users/ec2-user/runner/_work/pytorch/pytorch/torch/csrc/api -I/Users/ec2-user/runner/_work/pytorch/pytorch/torch/csrc/api/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/caffe2/aten/src/TH -I/Users/ec2-user/runner/_work/pytorch/pytorch/build/caffe2/aten/src/TH -I/Users/ec2-user/runner/_work/pytorch/pytorch/build/caffe2/aten/src -I/Users/ec2-user/runner/_work/pytorch/pytorch/build/caffe2/../aten/src -I/Users/ec2-user/runner/_work/pytorch/pytorch/torch/csrc -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/miniz-2.1.0 -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/kineto/libkineto/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/kineto/libkineto/src -I/Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/.. -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/FXdiv/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/c10/.. -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/pthreadpool/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/cpuinfo/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/native/quantized/cpu/qnnpack/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/native/quantized/cpu/qnnpack/src -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/cpuinfo/deps/clog/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/NNPACK/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/FP16/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/fmt/include -I/Users/ec2-user/runner/_work/pytorch/pytorch/third_party/flatbuffers/include -isystem /Users/ec2-user/runner/_work/pytorch/pytorch/third_party/protobuf/src -isystem /Users/ec2-user/runner/_work/pytorch/pytorch/third_party/XNNPACK/include -isystem /Users/ec2-user/runner/_work/pytorch/pytorch/cmake/../third_party/eigen -isystem /Users/ec2-user/runner/_work/pytorch/pytorch/build/include -x objective-c++ -DUSE_MPS -fno-objc-arc -Wno-unguarded-availability-new -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -fPIC -F/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks  -D__NEON__ -Wmissing-prototypes -Werror=missing-prototypes -std=gnu++17 -MD -MT caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/metal/ops/MetalReduce.mm.o -MF caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/metal/ops/MetalReduce.mm.o.d -o caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/metal/ops/MetalReduce.mm.o -c /Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/native/metal/ops/MetalReduce.mm
> 
> 2023-09-26T05:50:12.4263540Z /Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/native/metal/ops/MetalReduce.mm:31:8: error: no previous prototype for function 'wrapper_mean_dim' [-Werror,-Wmissing-prototypes]
> 
> 2023-09-26T05:50:12.4263850Z Tensor wrapper_mean_dim(
> 
> 2023-09-26T05:50:12.4264000Z        ^
> 
> 2023-09-26T05:50:12.4264360Z /Users/ec2-user/runner/_work/pytorch/pytorch/aten/src/ATen/native/metal/ops/MetalReduce.mm:31:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
> 
> 2023-09-26T05:50:12.4264640Z Tensor wrapper_mean_dim(
> 
> 2023-09-26T05:50:12.4264770Z ^
> 
> 2023-09-26T05:50:12.4264930Z static 
> 
> 2023-09-26T05:50:12.4265060Z 1 error generated.
> 
> ```

Fixed

**Comment by atalman** [comment]
Internal CI compilation failures:
```
error: undefined symbol: at::native::vulkan::ops::quantized_conv2d(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, double, long)
```

**Pull request closed without merging**
