### PR TITLE
[DOC] Update README.md: PyTorch supports only 64-bit version of python.

### PR DESCRIPTION
**Pull request by emankov**
+ Add a few words about how to check python version.

### CODE REVIEW

**Comment by ezyang** [comment]
Err, surely this is a Windows only restriction? I landed @peterjc123's check for this in setup.py; maybe it's not needed here in that case?

**Comment by emankov** [comment]
> maybe it's not needed here in that case?

In fact, it is needed for the end user, who should know all the tools, environment and restrictions before building/installing the software just by the reading the documentation, but under no circumstances in the process of building/installing.

**Comment by peterjc123** [comment]
https://stackoverflow.com/a/1405971 According to this post, `platform.architecture()` is not so reliable. Please use the following one:
```
import struct
print( 8 * struct.calcsize("P"))
```
The result should be 64.

**Comment by peterjc123** [comment]
@ezyang Did someone manage to build 32 bit PyTorch before?

**Review by apaszke — CHANGES_REQUESTED** [review]
This is definitely not true. PyTorch runs fine on NVIDIA Jetson boards, and they are 32-bit.

**Comment by peterjc123** [comment]
@apaszke So actually we need to revert this back too, right? https://github.com/pytorch/pytorch/pull/17707

**Comment by emankov** [comment]
> PyTorch runs fine on NVIDIA Jetson boards, and they are 32-bit.

What are they?

Correct me if I wrong, but the subject here is in using 64-bit Python for building pyTorch.

**Comment by soumith** [comment]
@emankov they are ARM boards with CUDA-supported GPU.

@apaszke you are wrong, Jetson boards are 64-bit CPUs

**Comment by danFromTelAviv** [comment]
even if jetsons are not Raspbery pis are 32 bit.

**Comment by apaszke** [comment]
@soumith you're right, I don't know why I remembered that they are 64-bit. Still, I do recall someone telling me that they compiled PyTorch for 32-bit systems and it worked fine. It shouldn't be too hard to support those cases, so I don't think we should disallow that. In the end we will care about mobile deployments too, and 32-bit is not all that uncommon there I think.

**Comment by soumith** [comment]
I compiled PyTorch on raspberry pi, and it works fine.

**Comment by emankov** [comment]
> I compiled PyTorch on raspberry pi, and it works fine.

Could you please be so kind and provide more concrete info: OS (version, bitness), Python (version, bitness), compiler (version, bitness)? If any additional defines were used, it worths mentioning as well. 

Colleagues,
Correct me if I wrong here, but I thought GPU (physically installed) doesn't matter while building, cause compilation is offline (at least CUDA by NVCC). If jit compilation is used in pyTorch somewhere, please let it know.
Thanks!

**Comment by ezyang** [comment]
> Correct me if I wrong here, but I thought GPU (physically installed) doesn't matter while building, cause compilation is offline (at least CUDA by NVCC). 

This is sort of true. nvcc is perfectly capable of building code for non-installed GPUs. However, it will decide which GPUs to compile for by looking at what you have installed, by default. Otherwise, you have to override it with an envvar.

**Comment by soumith** [comment]
@emankov looks like @t-vi has successfully built pytorch on 32-bit arm. The last PR that needed to go in was possibly: https://github.com/pytorch/pytorch/pull/18580 which I am landing

**Comment by peterjc123** [comment]
@soumith @emankov The CPU build test has passed on Windows through https://github.com/pytorch/pytorch/pull/17865. So it is not a problem anymore. The CUDA build is not passing but the problem is not on our side.

**Comment by t-vi** [comment]
The bug above is for x86 32bit, but Android 32bit arm also builds. I did get a Raspberry Pi but didn't try to build there yet. But it would seem there isn't anything keeping us from building on 32bit except bugs. Whether it's efficient is another question, so maybe it would be fair to say that 64bit is the primary platform (that gets all the CI etc.).

**Pull request closed without merging**
