### PR TITLE
[Resending] [ONNX] Add eliminate_unused_items pass

### PR DESCRIPTION
**Pull request by KsenijaS**
This PR:

- Adds eliminate_unused_items pass that removes unused inputs and initializers.
- Fixes run_embed_params function so it doesn't export unnecessary parameters.
- Removes test_modifying_params in test_verify since it's no longer needed.

### CODE REVIEW

**Comment by KsenijaS** [comment]
@houseroad can you please take a look? Thanks!

**Review by houseroad — COMMENTED** [review]
Could you rebase and fix the build issue?

**Comment by KsenijaS** [comment]
@houseroad I don't think that CI failure is caused by PR changes.

**Review by houseroad — APPROVED** [review]
Looks good.

**Pull request closed without merging**
