### PR TITLE
Moving CommTensor from tests to private _spmd folder

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #84719

### CODE REVIEW

**Comment by mrshenli** [comment]
Compared to #84655, the fix is not exposing anything in `_spmd/__init__.py` file, otherwise, the imported non-public APIs in `comm_tensor.py` will break `test_public_bindings.py`.

**Review by wanchaol — APPROVED** [review]

**Comment by wanchaol** [comment]
> Compared to #84655, the fix is not exposing anything in `_spmd/__init__.py` file, otherwise, the imported non-public APIs in `comm_tensor.py` will break `test_public_bindings.py`.

hmmm I didn't get this fully, why `test_public_bindings` would be bothered for anything inside a private module?

**Comment by mrshenli** [comment]
> hmmm I didn't get this fully, why test_public_bindings would be bothered for anything inside a private module?

Error message looks like this. Before this PR, `experimental`'s `__init__.py` didn't expose anything to that test. However, if we expose CommTensor which imports those private features, it makes those private features visible to the test which complains about missing `__all__` in the `experimental` package.

```
Full list:
# torch.fx.experimental.proxy_tensor.ProxySymDispatchMode:
  - Is NOT public: it is not inside the module's (`torch.fx.experimental.proxy_tensor`) `__all__`
  - Does look public: it does look public because it follows the rules from the doc above (does not start with `_` and has a proper `__module__`).
  - You can do either of these two things to fix this problem:
    - To make it public: add it from the modules's (`torch.fx.experimental.proxy_tensor`) `__all__`
    - To make it NOT look public: make its name start with `_`
```

**Pull request closed without merging**
