### PR TITLE
Mark `bincount` CUDA deterministic if `weights` are not given

### LINKED ISSUE #98316: Deterministic option for bincount_cuda
### 🚀 The feature, motivation and pitch

I'm working on a multiclass classifier, and I would really like to have deterministic confusion matrices on cuda.  Since that is implemented in torchmetrics using bincount_cuda, which doesn't currently support determinism, this is a bit of a bummer.

### Alternatives

Right now, I either pop the data back to CPU (slow) or turn off determinism and hope for be best.

### Additional context

Torch speaks thusly:
```
UserWarning: _bincount_cuda does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at  ../aten/src/ATen/Context.cpp:82.)
```

cc @mruberry @kurtamohler

### PR DESCRIPTION
**Pull request by kurtamohler**
Fixes #98316

cc @mruberry

### CODE REVIEW

**Comment by vadimkantorov** [comment]
A little related: https://github.com/pytorch/pytorch/issues/32305

histc could also be deterministic and should return int64

**Review by mikaylagawarecki — APPROVED** [review]
Thanks for the fix, this lgtm! Just waiting for CI to run green

**Pull request closed without merging**
