### PR TITLE
add PrivateUse1 device support in function options_from_string.

### PR DESCRIPTION
**Pull request by Shan19900305**
add PrivateUse1 device support in function options_from_string.

### CODE REVIEW

**Review by soulitzer — APPROVED** [review]

**Comment by soulitzer** [comment]
Looks like lint is failing @Shan19900305, should be good go otherwise

**Comment by Shan19900305** [comment]
> Looks like lint is failing @Shan19900305, should be good go otherwise

ok, fixed lint failed issues, and thank you.

**Review by soulitzer — APPROVED** [review]

**Pull request closed without merging**
