### PR TITLE
Remove THCHalfAutoNumerics.cuh

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:
- Replace uses of functions in THCHalfAutoNumerics with those in THCNumerics in THCUNN.

Test Plan:
- All tests should pass to verify that the change is correct

### CODE REVIEW

**Comment by gchanan** [comment]
what's the motivation?

**Comment by vishwakftw** [comment]
I was porting a unary op from THC to ATen, and the existing overload for it in this files didn’t allow me to remove the THC implementation.

This also completes the work started in #21878

**Comment by gchanan** [comment]
But this seems like the opposite direction, or at least motivation, of https://github.com/pytorch/pytorch/pull/21878 (and thus a step backward).

The sequence of events was something like:
1) we were using the built-in CUDA half type, which doesn't define a bunch of overloads
2) the original solution was to use THCNumerics<half> everywhere
3) but this got too ugly in THCUNN, so we added THCAutoNumerics to add the overloads (limited to THCUNN)
4) we later added at::Half, which defines a bunch of overloads

So going back to using THCNumerics doesn't seem like the correct solution.  Is it just that we don't define these overloads for at::Half?

**Comment by vishwakftw** [comment]
We do define these overloads for at::Half in THCNumerics.cuh and the overloads in THCHalfAutoNumerics.cuh merely dispatched to the templatized implementations in THCNumerics.cuh.

Making this change avoids the extra round of redirection.

**Comment by gchanan** [comment]
sorry, I wasn't clear about overloads -- I meant implicit overloads, i.e. you can just write Half code like you would float code.  Can we do the same thing here?

**Comment by vishwakftw** [comment]
No, I don’t think so. I believe THCHalfAutoNumerics was there for that reason only - to add at::Half overloads.

**Comment by gchanan** [comment]
so can we add those overloads in some other way without reverting back to using THCNumerics explicitly?

**Comment by vishwakftw** [comment]
> so can we add those overloads in some other way without reverting back to using THCNumerics explicitly?

To the best of my knowledge, I don't think so. A lot of code files actually resort to using THCNumerics explicity in THCUNN.

**Pull request closed without merging**
