### PR TITLE
[quant][pt1] Uninitialize the accumulation buffer to save some overhead

### PR DESCRIPTION
**Pull request by jianyuh**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #27092 [pt1][quant] Fix empty_like to add more support when input_tensor has dtype as q(u)int8
* **#27005 [quant][pt1] Uninitialize the accumulation buffer to save some overhead**

Similar to https://github.com/pytorch/pytorch/pull/27002, we want to save some overhead.

Differential Revision: [D17641819](https://our.internmc.facebook.com/intern/diff/D17641819/)

### CODE REVIEW

**Review by jamesr66a — CHANGES_REQUESTED** [review]
There's an error, please see CI

**Comment by jianyuh** [comment]
Right: It shows an error as the follows:
```
Sep 28 00:00:00 RuntimeError: It is currently not supported to specify a dtype that doesn't match the input tensor's dtype via empty_like.  Specified: int Input tensor's dtype: c10::quint8 (empty_like at **/var/lib/jenkins/workspace/aten/src/ATen/native/TensorFactories.cpp:220)**
```

I think `empty_like` still didn't support the input tensor's dtype as the quantized uint8/int8 (`kQUInt8`/`kQInt8`). cc @jerryzh168 .

**Comment by dskhudia** [comment]
Does empty_zeros call something like memset?

**Comment by jerryzh168** [comment]
the error is raised from: https://bddppq.github.io/codebrowser/pytorch/pytorch/aten/src/ATen/native/TensorFactories.cpp.html#217

**Comment by jianyuh** [comment]
> the error is raised from: https://bddppq.github.io/codebrowser/pytorch/pytorch/aten/src/ATen/native/TensorFactories.cpp.html#217

OK, it looks like `at::empty_like` didn't support the case where input tensor's dtype as the quantized uint8/int8 (kQUInt8/kQInt8) and the options have a different type.

I now switch to `at::empty` instead.

**Review by jamesr66a — APPROVED** [review]
lgtm

**Review by z-a-f — APPROVED** [review]
LGTM

**Pull request closed without merging**
