### PR TITLE
No-gil cherry picks for 2.5.X

### PR DESCRIPTION
**Pull request by albanD**
cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @rec @xmfan

### CODE REVIEW

**Comment by kit1980** [comment]
2.5.1 is an emergency patch release to address specific large regressions, moving this to 2.6.0

**Comment by albanD** [comment]
@kit1980 could you please check with Andrey that this cherry-pick is done if we do end up doing another patch release?

**Comment by kit1980** [comment]
@albanD If we do 2.5.2, we will look at 2.6.0 milestone and move stuff to 2.5.2

**Comment by kit1980** [comment]
Removing the milestone as this is in main for months.

**Pull request closed without merging**
