### PR TITLE
Use std::filesystem in c10 tempfile and tempdir

### PR DESCRIPTION
**Pull request by cyyever**
This PR simplifies c10::TempFile and c10::TempDir. It also deletes Windows temp files in c10::~TempFile, this behavior is absent on the current version.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
sure why not

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change, but it is failing internal iOS build.  This was missed by period mobile build I think' -c ghfirst

Here is the errors FYI:

```
stderr: In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:50:10: error: 'path' is unavailable: introduced in iOS 13.0
  stdfs::path filename(tmp_directory);
         ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:442:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:50:15: error: 'path' is unavailable: introduced in iOS 13.0
  stdfs::path filename(tmp_directory);
              ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:482:3: note: 'path' has been explicitly marked unavailable here
  path(const _Source& __src, format = format::auto_format) {
  ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:50:15: error: '~path' is unavailable: introduced in iOS 13.0
  stdfs::path filename(tmp_directory);
              ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:505:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:52:12: error: 'operator/=' is unavailable: introduced in iOS 13.0
  filename /= name_prefix;
           ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:613:3: note: 'operator/=' has been explicitly marked unavailable here
  operator/=(const _Source& __src) {
  ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:52:12: error: 'operator/=<std::string_view>' is unavailable: introduced in iOS 13.0
  filename /= name_prefix;
           ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:613:3: note: 'operator/=<std::string_view>' has been explicitly marked unavailable here
  operator/=(const _Source& __src) {
  ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:53:12: error: 'operator+=' is unavailable: introduced in iOS 13.0
  filename += kRandomPattern;
           ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:666:9: note: 'operator+=' has been explicitly marked unavailable here
  path& operator+=(const value_type* __x) {
        ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:54:19: error: 'string' is unavailable: introduced in iOS 13.0
  return filename.string();
                  ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:821:39: note: 'string' has been explicitly marked unavailable here
  _LIBCPP_HIDE_FROM_ABI _VSTD::string string() const { return __pn_; }
                                      ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:70:25: error: 'path' is unavailable: introduced in iOS 13.0
  TempFile(const stdfs::path& name, int fd = -1) noexcept
                        ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:442:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:71:27: error: 'string' is unavailable: introduced in iOS 13.0
      : fd(fd), name(name.string()) {}
                          ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:821:39: note: 'string' has been explicitly marked unavailable here
  _LIBCPP_HIDE_FROM_ABI _VSTD::string string() const { return __pn_; }
                                      ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:90:14: error: 'remove' is unavailable: introduced in iOS 13.0
      stdfs::remove(name);
             ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/operations.h:177:35: note: 'remove' has been explicitly marked unavailable here
inline _LIBCPP_HIDE_FROM_ABI bool remove(const path& __p) { return __remove(__p); }
                                  ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:90:21: error: 'path' is unavailable: introduced in iOS 13.0
      stdfs::remove(name);
                    ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:482:3: note: 'path' has been explicitly marked unavailable here
  path(const _Source& __src, format = format::auto_format) {
  ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:90:21: error: '~path' is unavailable: introduced in iOS 13.0
      stdfs::remove(name);
                    ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:505:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:105:27: error: 'path' is unavailable: introduced in iOS 13.0
  explicit TempDir(stdfs::path name) noexcept : name(std::move(name)) {}
                          ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:442:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:124:10: error: 'path' is unavailable: introduced in iOS 13.0
  stdfs::path name;
         ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:442:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:105:49: error: 'path' is unavailable: introduced in iOS 13.0
  explicit TempDir(stdfs::path name) noexcept : name(std::move(name)) {}
                                                ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:473:25: note: 'path' has been explicitly marked unavailable here
  _LIBCPP_HIDE_FROM_ABI path(path&& __p) noexcept
                        ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:105:12: error: '~path' is unavailable: introduced in iOS 13.0
  explicit TempDir(stdfs::path name) noexcept : name(std::move(name)) {}
           ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:505:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:107:39: error: 'path' is unavailable: introduced in iOS 13.0
  TempDir(TempDir&& other) noexcept : name(std::move(other.name)) {
                                      ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:473:25: note: 'path' has been explicitly marked unavailable here
  _LIBCPP_HIDE_FROM_ABI path(path&& __p) noexcept
                        ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:107:3: error: '~path' is unavailable: introduced in iOS 13.0
  TempDir(TempDir&& other) noexcept : name(std::move(other.name)) {
  ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:505:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
In file included from xplat/caffe2/c10/test/util/tempfile_test.cpp:1:
xplat/caffe2/c10/util/tempfile.h:108:16: error: 'clear' is unavailable: introduced in iOS 13.0
    other.name.clear();
               ^
buck-out/gen/233b7bbc/xplat/toolchains/apple/xcode_14.3.1_14e300b-iphonesimulator-sdk_genrule/iPhoneSimulator16.4.sdk/usr/include/c++/v1/__filesystem/path.h:709:8: note: 'clear' has been explicitly marked unavailable here
  void clear() noexcept { __pn_.clear(); }
       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Pull request closed without merging**
