### PR TITLE
Refresh OpOverloadPacket if a new OpOverload gets added

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #124654

If a user accesses an OpOverloadPacket, then creates a new OpOverload,
then uses the OpOverloadPacket, the new OpOverload never gets hit. This
is because OpOverloadPacket caches OpOverloads when it is constructed.

This PR fixes the problem by "refreshing" the OpOverloadPacket if a new
OpOverload gets constructed and the OpOverloadPacket exists.

Test Plan:
- new tests

Differential Revision: [D57666729](https://our.internmc.facebook.com/intern/diff/D57666729)

### CODE REVIEW

**Comment by zou3519** [comment]
This is a reland of https://github.com/pytorch/pytorch/pull/123578. The original broke an internal test case. I verified the test case now passes and added a test for it.

It's unclear to me what the root cause of the problem was, but I did fix a bug where torch.library.Library.define would always construct an op and immediately refresh it (as opposed to just constructing it).

**Review by albanD — APPROVED** [review]
SGTM!

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D57666729).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D57666729).

**Comment by zou3519** [comment]
attempting reland elsewhere

**Pull request closed without merging**
