### PR TITLE
Move custom passes to last optimization step

### PR DESCRIPTION
**Pull request by bwasti**
Summary: ..

Test Plan: ..

Reviewed By: ZolotukhinM

Differential Revision: D18340212

### CODE REVIEW

**Comment by eellison** [comment]
Doesn't this break any custom pass any external user will have ? (e.g. torch_tvm). I don't know how public we consider the api to be. What exactly was the motivation for this change ? 

cc @zdevito @ZolotukhinM

**Comment by ilia-cher** [comment]
why did we do this and what is the impact on TVM pass?

**Comment by ZolotukhinM** [comment]
I think the only external user so far is torch_tvm which @bwasti wrote. The motivation to do this was to be able to fix-up things after optimizations (e.g. after fusion). Ideally, I think we should have a mechanism to register passes before and after the standard pipeline. So far my understanding was that it's not widely used so we can change it freely if the other option is more convenient.

**Comment by eellison** [comment]
I agree we should have a mechanism to run before and after the pipeline. Still, i wouldn't be surprised if there are some users of the api somewhere and it would be preferable if this was done in OSS and not phabricator.

At any rate, this comment should be updated:
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/pass_manager.h#L6

**Comment by bwasti** [comment]
OSS == Phabricator because of export, no?  There are effectively no passes in JIT today, so I don't think it's much of an issue.  If folks are using this mechanism and they find this breaks their stuff, they'll file an issue and we can go from there

Agreed on updating the comment

**Comment by eellison** [comment]
It's only partially OSS; you can't see how the PR was reviewed if you're external.

**Pull request closed without merging**
