### PR TITLE
Removed std namespace from log function calls

### LINKED ISSUE #128253: Use of standard library math functions vs global namespace
## Issue description

Recently, it was discovered that some hip kernels prefer to use global namespace vs std namespace for various math functions.  There was a recent issue being discussed where the use of global namespace math functions was causing minor accuracy issues on ROCm. Please reference said issue comment for more background: https://github.com/pytorch/pytorch/issues/96560#issuecomment-2151063723

After some internal investigation it was found that the global namespace was chosen in accordance CUDA documentation:
https://docs.nvidia.com/cuda/cuda-math-api/index.html
```
Note also that due to implementation constraints, certain math functions from std:: namespace may be callable in device code even via explicitly qualified std:: names. However, such use is discouraged, since this capability is unsupported, unverified, undocumented, not portable, and may change without notice.
```

There have also been other issues related to this where the std namespace seems to be generally prioritized when, according to the above documentation, it shouldn't
https://github.com/pytorch/pytorch/pull/127812

So I wanted to open a discussion as to why CUDA kernels are prioritizing the std namespace over the global namespace?

Should we standardize to global namespace for consistency?

### PR DESCRIPTION
**Pull request by iupaikov-amd**
Fixes #128253

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @EikanWang @voznesenskym @penguinwu @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by Skylion007** [comment]
This affects the function as the base log functions are not overloaded the same way as std, we should we use these calls?

**Comment by Skylion007** [comment]
IT: seems to be missing overloads for half and other types: https://cplusplus.com/reference/cmath/log/ I also don't see why this is necessary on CPU?

**Comment by iupaikov-amd** [comment]
There are differences between CUDA and HIP usage of math functions. CUDA compiler just uses them as is and we have no documentation on what exact variant is used for each math function, while hipcc can't compile functions from the std namespace and std just gets omitted during HIPification. The idea is that we need a global solution to make a unified logic for both compilers. This would require either compiler team collaboration or plain global namespace usage for both.

@Skylion007 This PR is just a draft to highlight the issue, you're right CPU functions shouldn't be affected. I'll run a few more tests and update or close it.

**Comment by iupaikov-amd** [comment]
Update: removed all unnecessary changes to common files that don't get hipified. Cleaned affected test cases.

**Pull request closed without merging**
