### PR TITLE
Step 6: Rename _unique2 to unique and add int? dim

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #18661 Step 7: remove _unique
* **#18655 Step 6: Rename _unique2 to unique and add int? dim**
* #18654 Step 5: remove _unque_dim in favor of unique_dim
* #18651 Step 4: add support for unique with dim=None
* #18650 Step 3: Add support for return_counts to torch.unique for dim not None
* #18649 Step 2: Rename _unique_dim2_temporary_will_remove_soon to unique_dim
* #18648 Step 1: Secretly add return_counts to unique, and refactor unique_dim for performance

- Rename `_unique2` to `unique`
- Add optional `dim` argument to make it looks like the signature of Python's `torch.unique`.
- Inside `torch.unique`, use `unique` and get rid of `unique_dim`.
- Unbind `unique_dim` totally from Python at codegen.
- Add OSS ONNX test for unique
- Add jit test for unique

Previously tried in #17097 and cause internal error, not sure about this
time.

cc: @wanchaol

Differential Revision: [D15034051](https://our.internmc.facebook.com/intern/diff/D15034051)

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
alright... I did something wrong when rebasing... Will fix later

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin This should be ready as well

**Comment by dzhulgakov** [comment]
@VitalyFedyunin - Just sanity-checking - is this change backward-compatible in terms of serialized JIT IR?

**Comment by VitalyFedyunin** [comment]
It might be not,  I have one more PR with potentially similar problem under review now. Planning to write instructions how to test cover it.

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin I am closing this and #18661 since it has been so old. Rebasing would be harder than rewrite it I guess.

**Comment by VitalyFedyunin** [comment]
Oh, damn sorry. Thanks for cleaning up.

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin Not a problem. Changing the API in aten operators is always hard.

**Pull request closed without merging**
