### PR TITLE
Reduce number of CEX when passing Tensors to Python

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#60546 Reduce number of CEX when passing Tensors to Python**

Before, we assume conservatively that any Tensor passed to
THPVariable_Wrap could be aliased in another thread and therefore race.
However, THPVariable_Wrap takes in Variable by value; and so if
use_count() <= 1, it is impossible for another thread to have a
reference to it.  So we can conclude that it is definitely uninitialized
if the quick test fails!

Thanks bdhirsh for pointing out the optimization opportunity here.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D29331718](https://our.internmc.facebook.com/intern/diff/D29331718)

### CODE REVIEW

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29331718).

**Review by albanD — COMMENTED** [review]
What happens here in the case where this var was `TAGGED_BY_OTHER` ?

**Comment by ezyang** [comment]
Notice that `check_pyobj` returns a c10::optional. So actually it will error if the tagging is inconsistent, no check necessary here.

**Comment by albanD** [comment]
Ho so the `check_pyobj` can do four things:
1 return the optional filled with the pyobj if we've tagged this Tensor and there is already a pyobj
2 return the optional filled with a nullptr if we've tagged this Tensor but there isn't a pyobj already set.
3 return and empty optional if the Tensor is untagged
4 raise an error if the Tensor is already tagged by another interpreter


- How can you end up in state 2?
- Am I correct in my understanding that your comment mentions that in case of 3, there might actually be a race and we might actually be in 1, 2 or 4 but we don't know yet? And so the status we use should reflect that.
- Is there also a race with the pyobj creation itself? It used to be "ok" as we didn't care if the pyobject associated to a Tensor was changing over time (due to a race on creation or because it was dying), but maybe we need to actually worry about that if we start relying on the unicity of the pyobject? (this is beyond the scope of this PR but we might want to open a high pri issue for this)

**Comment by ezyang** [comment]
> How can you end up in state 2?

This used to be possible but now with PyObject preservation it is probably impossible and we can tighten the tests here.

> Am I correct in my understanding that your comment mentions that in case of 3, there might actually be a race and we might actually be in 1, 2 or 4 but we don't know yet? And so the status we use should reflect that.

Yes.

> Is there also a race with the pyobj creation itself? It used to be "ok" as we didn't care if the pyobject associated to a Tensor was changing over time (due to a race on creation or because it was dying), but maybe we need to actually worry about that if we start relying on the unicity of the pyobject? (this is beyond the scope of this PR but we might want to open a high pri issue for this)

No. You must have the GIL to create a pyobj. So within a single interpreter you are guaranteed to lock appropriately.

**Comment by albanD** [comment]
> You must have the GIL to create a pyobj.

Ho right you need to hold the gil for the corresponding interepreter! Sounds good!

**Review by albanD — APPROVED** [review]
Thanks for all the clarifications, nice little improvement!

**Pull request closed without merging**
