### PR TITLE
Bring AVX2 support for float16 at par with that for BFloat16

### PR DESCRIPTION
**Pull request by imaginary-person**
`float16` <-> `float` conversion is faster than `bfloat16` <-> `float` conversion in `vec256_bfloat16.h`.
So, it might be worth having `vec256_half.h` because computations in `vec256_bfloat16.h` are performed in float anyway.
This way,  ops that are already enabled for `BFloat16` on CPU can also be enabled for `float16` on CPU, .

Now that there are no build issues, I'll test locally & push changes when done.

TODO: 
- [ ] Verify correctness (consistency with CUDA) & fix bugs, if required
- [ ] Make a list of PyTorch ops that are enabled for `BFloat16` on CPU, and can be enabled for `Float16`.
- [ ]  Enable the ops in the above step & compare performance with BFloat16.

### CODE REVIEW

**Comment by ezyang** [comment]
Well, you can one off fix the ambiguity by casting quant_min and quant_max to float. Not sure how this code ever worked before; it kind of suspiciously looks like conversion to BFloat16 was happening, which sounds definitely wrong.

**Comment by ezyang** [comment]
https://godbolt.org/z/bjTjPMMco

**Comment by imaginary-person** [comment]
Thanks a lot for your help, @ezyang!

It looks like this issue is more pervasive, and seems to be occurring when the inputs to `std::max` and `std::min` have different dtypes.

For example, now I'm encountering an overload-resolution-failure compilation-error for `max(const unsigned char&, int)` at https://github.com/pytorch/pytorch/blob/3f9492c8b32ddae65fdd421dd602ef3aa6f8278b/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp#L74

```
In file included from pytorch/aten/src/ATen/ATen.h:13,
                 from pytorch/aten/src/ATen/native/BinaryOps.h:3,
                 from pytorch/build/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp.DEFAULT.cpp:1:
pytorch/build/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp.DEFAULT.cpp: In lambda function:
pytorch/build/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp.DEFAULT.cpp:74:71: error: call of overloaded ‘max(const unsigned char&, int)’ is ambiguous
   74 |         return std::min(max_scalar, std::max(min_scalar, a + alpha * b));
      |                                                                       ^
pytorch/aten/src/ATen/Dispatch.h:66:12: note: in definition of macro ‘AT_PRIVATE_CASE_TYPE_USING_HINT’
   66 |     return __VA_ARGS__();                                                        \
      |            ^~~~~~~~~~~
pytorch/aten/src/ATen/Dispatch.h:407:7: note: in expansion of macro ‘AT_PRIVATE_CASE_TYPE’
  407 |       AT_PRIVATE_CASE_TYPE(NAME, at::ScalarType::Byte, uint8_t, __VA_ARGS__)    \
      |       ^~~~~~~~~~~~~~~~~~~~
pytorch/build/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp.DEFAULT.cpp:65:3: note: in expansion of macro ‘AT_DISPATCH_ALL_TYPES’
   65 |   AT_DISPATCH_ALL_TYPES(iter.dtype(), "add_clamp_cpu", [&]() {
      |   ^~~~~~~~~~~~~~~~~~~~~
In file included from pytorch/aten/src/ATen/cpu/vec256/vec256_base.h:28,
                 from pytorch/aten/src/ATen/cpu/vec256/vec256.h:8,
                 from pytorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from pytorch/build/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp.DEFAULT.cpp:8:
pytorch/c10/util/BFloat16-math.h:33:22: note: candidate: ‘c10::BFloat16 std::max(c10::BFloat16, c10::BFloat16)’
   33 | inline c10::BFloat16 max(c10::BFloat16 a, c10::BFloat16 b) { return std::max(float(a), float(b));}
      |                      ^~~
In file included from pytorch/aten/src/ATen/cpu/vec256/vec256_base.h:30,
                 from pytorch/aten/src/ATen/cpu/vec256/vec256.h:8,
                 from pytorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from pytorch/build/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp.DEFAULT.cpp:8:
pytorch/c10/util/Half-math.h:33:18: note: candidate: ‘c10::Half std::max(c10::Half, c10::Half)’
   33 | inline c10::Half max(c10::Half a, c10::Half b) { return std::max(float(a), float(b));}
```

**Comment by ezyang** [comment]
Yes, this is very unfortunate. I wonder how many of these bugs have snuck in after bfloat16 was added. If you're game, fixing all of these would be very helpful in a PR of its own.

**Comment by ezyang** [comment]
Relevant Twitter thread: https://twitter.com/pavpanchekha/status/1380350354919813125

**Comment by imaginary-person** [comment]
@ezyang: Thanks for the info! I'll keep that in mind while comparing accuracy with CUDA.
In this PR, though, I'm only trying to add the same level of AVX2 support for `Float16` that `BFloat16` already has in `vec256-BFloat16.h` (which converts `BFloat16` <-> `Float` for all its ops).

BTW, I'm not adding any new ops. I only added functions for converting `float16` <-> `float` (I'm yet to check their accuracy).
For the rest of the code, I simply copy-pasted `vec256-bfloat16.h` & replaced the string `BFloat16` with `Half`. 😃
I'm yet to test & debug the code.

If precision would turn out to be be different from CUDA, then I won't request you to land this PR. :)

**Pull request closed without merging**
