### PR TITLE
Integrate xpu into torch.Generator and torch.seed

### PR DESCRIPTION
**Pull request by leizhenyuan**
Integrate torch.xpu.Generator into torch.Generator
Integrate torch.xpu.seed into torch.seed

### CODE REVIEW

**Comment by leizhenyuan** [comment]
@malfet  pls help review if this any problem, thanks.

**Comment by gujinghui** [comment]
@ezyang   could you help review this PR? Thanks.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
