### PR TITLE
Recursively print graph module and its submodule

### PR DESCRIPTION
**Pull request by SherlockNoMad**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #81080

### CODE REVIEW

**Comment by ezyang** [comment]
Can you give an example of what this looks like now? In particular I'm wondering if we need to do indentation

**Comment by SherlockNoMad** [comment]
> Can you give an example of what this looks like now? In particular I'm wondering if we need to do indentation

```
GraphModule(
  (fused_0): fused_0()
  (fused_1): fused_1()
  (fused_2): fused_2()
)



def forward(self, rsqrt, primals_2, primals_1, mul, tangents_1):
    fused_1 = self.fused_1(tangents_1, primals_1, rsqrt, primals_2);  primals_1 = None
    getitem = fused_1[0]
    getitem_1 = fused_1[1];  fused_1 = None
    fused_2 = self.fused_2(tangents_1, mul);  tangents_1 = mul = None
    view_default = torch.ops.aten.view.default(fused_2, [512]);  fused_2 = None
    expand_default = torch.ops.aten.expand.default(getitem_1, [8, 1024, 512]);  getitem_1 = None
    fused_0 = self.fused_0(expand_default, getitem, rsqrt, primals_2);  expand_default = getitem = rsqrt = primals_2 = None
    return [view_default, fused_0]
    
fused_0()



def forward(self, expand_default, mul_tensor, rsqrt, primals_2):
    div_tensor = torch.ops.aten.div.Tensor(expand_default, 512);  expand_default = None
    mul_tensor_3 = torch.ops.aten.mul.Tensor(mul_tensor, rsqrt);  mul_tensor = rsqrt = None
    pow_tensor_scalar_1 = torch.ops.aten.pow.Tensor_Scalar(primals_2, 1.0);  primals_2 = None
    mul_tensor_6 = torch.ops.aten.mul.Tensor(pow_tensor_scalar_1, 2.0);  pow_tensor_scalar_1 = None
    mul_tensor_7 = torch.ops.aten.mul.Tensor(div_tensor, mul_tensor_6);  div_tensor = mul_tensor_6 = None
    add_tensor = torch.ops.aten.add.Tensor(mul_tensor_3, mul_tensor_7);  mul_tensor_3 = mul_tensor_7 = None
    return add_tensor
    

fused_1()



def forward(self, tangents_1, primals_1, rsqrt, primals_2):
    mul_tensor = torch.ops.aten.mul.Tensor(tangents_1, primals_1);  tangents_1 = primals_1 = None
    pow_tensor_scalar = torch.ops.aten.pow.Tensor_Scalar(rsqrt, 3);  rsqrt = None
    mul_tensor_2 = torch.ops.aten.mul.Tensor(mul_tensor, primals_2);  primals_2 = None
    sum_dim_int_list_1 = torch.ops.aten.sum.dim_IntList(mul_tensor_2, [2], True);  mul_tensor_2 = None
    mul_tensor_4 = torch.ops.aten.mul.Tensor(sum_dim_int_list_1, -0.5);  sum_dim_int_list_1 = None
    mul_tensor_5 = torch.ops.aten.mul.Tensor(mul_tensor_4, pow_tensor_scalar);  mul_tensor_4 = pow_tensor_scalar = None
    return (mul_tensor, mul_tensor_5)
    

fused_2()



def forward(self, tangents_1, mul):
    mul_tensor_1 = torch.ops.aten.mul.Tensor(tangents_1, mul);  tangents_1 = mul = None
    sum_dim_int_list = torch.ops.aten.sum.dim_IntList(mul_tensor_1, [0, 1], True);  mul_tensor_1 = None
    return sum_dim_int_list

```

**Comment by SherlockNoMad** [comment]
After indent

```
GraphModule(
  (fused_0): fused_0()
  (fused_1): fused_1()
  (fused_2): fused_2()
)



def forward(self, rsqrt, primals_2, primals_1, mul, tangents_1):
    fused_1 = self.fused_1(rsqrt, tangents_1, primals_1, primals_2);  primals_1 = None
    getitem = fused_1[0]
    getitem_1 = fused_1[1];  fused_1 = None
    fused_2 = self.fused_2(tangents_1, mul);  tangents_1 = mul = None
    view_default = torch.ops.aten.view.default(fused_2, [512]);  fused_2 = None
    expand_default = torch.ops.aten.expand.default(getitem_1, [8, 1024, 512]);  getitem_1 = None
    fused_0 = self.fused_0(getitem, rsqrt, primals_2, expand_default);  getitem = rsqrt = primals_2 = expand_default = None
    return [view_default, fused_0]
    
    fused_0()
    
    
    
    def forward(self, mul_tensor, rsqrt, primals_2, expand_default):
        mul_tensor_3 = torch.ops.aten.mul.Tensor(mul_tensor, rsqrt);  mul_tensor = rsqrt = None
        pow_tensor_scalar_1 = torch.ops.aten.pow.Tensor_Scalar(primals_2, 1.0);  primals_2 = None
        div_tensor = torch.ops.aten.div.Tensor(expand_default, 512);  expand_default = None
        mul_tensor_6 = torch.ops.aten.mul.Tensor(pow_tensor_scalar_1, 2.0);  pow_tensor_scalar_1 = None
        mul_tensor_7 = torch.ops.aten.mul.Tensor(div_tensor, mul_tensor_6);  div_tensor = mul_tensor_6 = None
        add_tensor = torch.ops.aten.add.Tensor(mul_tensor_3, mul_tensor_7);  mul_tensor_3 = mul_tensor_7 = None
        return add_tensor
        
    
    fused_1()
    
    
    
    def forward(self, rsqrt, tangents_1, primals_1, primals_2):
        pow_tensor_scalar = torch.ops.aten.pow.Tensor_Scalar(rsqrt, 3);  rsqrt = None
        mul_tensor = torch.ops.aten.mul.Tensor(tangents_1, primals_1);  tangents_1 = primals_1 = None
        mul_tensor_2 = torch.ops.aten.mul.Tensor(mul_tensor, primals_2);  primals_2 = None
        sum_dim_int_list_1 = torch.ops.aten.sum.dim_IntList(mul_tensor_2, [2], True);  mul_tensor_2 = None
        mul_tensor_4 = torch.ops.aten.mul.Tensor(sum_dim_int_list_1, -0.5);  sum_dim_int_list_1 = None
        mul_tensor_5 = torch.ops.aten.mul.Tensor(mul_tensor_4, pow_tensor_scalar);  mul_tensor_4 = pow_tensor_scalar = None
        return (mul_tensor, mul_tensor_5)
        
    
    fused_2()
    
    
    
    def forward(self, tangents_1, mul):
        mul_tensor_1 = torch.ops.aten.mul.Tensor(tangents_1, mul);  tangents_1 = mul = None
        sum_dim_int_list = torch.ops.aten.sum.dim_IntList(mul_tensor_1, [0, 1], True);  mul_tensor_1 = None
        return sum_dim_int_list
```

**Comment by ezyang** [comment]
Hmm, the indent is confusion because now the subgraphs are flush with the indented code from the first module. I am wondering what, in an ideal world, I'd want the print to look like. I feel like I'd like to see something like:

```
class GraphModule:
    def forward(...):
        ...

    def fused_0(...): 
        ...
```

and so forth. However, I suppose you might also want to know what the class of the submodules are, so maybe you'd want some nested subclasses (by indenting the recursive repr)...

**Comment by SherlockNoMad** [comment]
```
GraphModule(
  (fused_0): fused_0()
  (fused_1): fused_1()
  (fused_2): fused_2()
)
class GraphModule(torch.nn.Module):
    def forward(self, args_1, args_2, args_3, args_4, args_5, args_6, args_7, args_8, args_9, args_10, args_11, args_12, args_13, args_14, args_15, args_16, args_17):
        view_default = torch.ops.aten.view.default(args_17, [2048, 768])
         ....
        fused_0 = self.fused_0(getitem_11, view_default_18, args_6, args_5);  getitem_11 = view_default_18 = None
        getitem_6 = fused_0[0]
        getitem_7 = fused_0[1]
        getitem_8 = fused_0[2]
        getitem_9 = fused_0[3];  fused_0 = None
        return [getitem_7, args_10, view_default_9, view_default_2, getitem_10, t_default_4, view_default_5, args_6, t_default_2, getitem_8, to_dtype_1, getitem_13, view_default_16, view_default_17, args_9, getitem_12, args_5, view_default, t_default, getitem_9, t_default_5, permute_default_3, view_default_11, getitem_6, t_default_3, view_default_13, t_default_1, view_default_15]
        
    class fused_0(torch.nn.Module):
        def forward(self, getitem, view_default_18, args_6, args_5):
            add_tensor_1 = torch.ops.aten.add.Tensor(getitem, view_default_18);  getitem = view_default_18 = None
            native_layer_norm_default_1 = torch.ops.aten.native_layer_norm.default(add_tensor_1, [768], args_6, args_5, 1e-05);  args_6 = args_5 = None
            getitem_3 = native_layer_norm_default_1[0]
            getitem_4 = native_layer_norm_default_1[1]
            getitem_5 = native_layer_norm_default_1[2];  native_layer_norm_default_1 = None
            return (add_tensor_1, getitem_3, getitem_4, getitem_5)
            
    class fused_1(torch.nn.Module):
        def forward(self, args_17, view_default_14, args_10, args_9):
            add_tensor = torch.ops.aten.add.Tensor(args_17, view_default_14);  args_17 = view_default_14 = None
            native_layer_norm_default = torch.ops.aten.native_layer_norm.default(add_tensor, [768], args_10, args_9, 1e-05);  args_10 = args_9 = None
            getitem = native_layer_norm_default[0]
            getitem_1 = native_layer_norm_default[1]
            getitem_2 = native_layer_norm_default[2];  native_layer_norm_default = None
            return (add_tensor, getitem, getitem_1, getitem_2)
            
    class fused_2(torch.nn.Module):
        def forward(self, to_dtype, amax_default):
            sub_tensor = torch.ops.aten.sub.Tensor(to_dtype, amax_default);  to_dtype = amax_default = None
            exp_default = torch.ops.aten.exp.default(sub_tensor);  sub_tensor = None
            sum_dim_int_list = torch.ops.aten.sum.dim_IntList(exp_default, [-1], True)
            div_tensor = torch.ops.aten.div.Tensor(exp_default, sum_dim_int_list);  exp_default = sum_dim_int_list = None
            return div_tensor
```

How about this?

**Review by ezyang — APPROVED** [review]
nice, let's ship it

**Pull request closed without merging**
