### PR TITLE
free up dispatch key space (in C++)

### PR DESCRIPTION
**Pull request by bdhirsh**
Re-land of https://github.com/pytorch/pytorch/pull/69633. There was an out-of-bounds array access in `DispatchKeyExtractor.cpp` that caused memory corruption, and appeared to only surface on internal android tests. The problematic area was:
```
    // nonFallthroughKeysPerBackend_ goes from index 0 -> num_backends-1 
    if (has_fallthrough) {
      for (size_t i = 0; i <= num_backends; ++i) {
        nonFallthroughKeysPerBackend_[i] = nonFallthroughKeysPerBackend_[i].remove(k);
      }
    } else {
      for (size_t i = 0; i <= num_backends; ++i) {
        nonFallthroughKeysPerBackend_[i] = nonFallthroughKeysPerBackend_[i].add(k);
      }
    }
  }
```

There's an outer `OperatorEntry` object, that looks like this:
```
class OperatorEntry {
...
  OperatorName name_;
  c10::optional<AnnotatedSchema> schema_;

  std::array<KernelFunction, c10::num_runtime_entries> dispatchTable_;

  // we were illegally writing past the memory here
  DispatchKeyExtractor dispatchKeyExtractor_;

  // and clobbering some of the memory in the hash map
  ska::flat_hash_map<DispatchKey, ...>
}
```

I cleaned up that area of the code (Fixed the OOB error, switched `num_backends` to `nonFallthroughKeysPerBackend_.size()` to be more explicit, also added an assert higher up in the file), and confirmed that the failing internal android tests pass with those changes.

It would be nice if ASAN could catch this - I have an experimental PR higher up where I swap out the `std::array` with a `std::vector` to see if that causes ASAN to trigger the failure (update: it does).

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #72644
* #72403
* __->__ #72402

Reland of D33255193

Differential Revision: [D34034848](https://our.internmc.facebook.com/intern/diff/D34034848/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D34034848/)!

### CODE REVIEW

**Comment by bdhirsh** [comment]
All but one internal test is passing (hard to tell if it's flaky, so I'm rebasing it internally)

**Review by albanD — APPROVED** [review]
🚀

**Comment by AnthonyBarbier** [comment]
@bdhirsh Do you have any plans to try to land that patch again?

I've got a patch to add a new key which depends on your patch. Thanks :)

**Comment by bdhirsh** [comment]
Hey @AnthonyBarbier! I had to revert this due to some internal breakages that I've been working on tracking down. I actually just got back from PTO today and started trying to push on this again this morning. You can track the new PR here: https://github.com/pytorch/pytorch/pull/72827

**Pull request closed without merging**
