### PR TITLE
[CUDA] [CI] Add cu124 docker images 

### PR DESCRIPTION
**Pull request by nWEIdia**
Fixes issues encountered in https://github.com/pytorch/pytorch/pull/121956 

cc @ptrblck @Aidyn-A @atalman @malfet

### CODE REVIEW

**Review by atalman — APPROVED** [review]

**Comment by atalman** [comment]
@nWEIdia  Two errors seems not to be related to this PR, however please rebase and rerun CI to be sure

**Comment by nWEIdia** [comment]
@clee2000 Good catch!  I now realize there might be UCC/UCX related regression that newer UCC/UCX may not be working as well with cuda 11.8.

**Pull request closed without merging**
