### PR TITLE
[Intel GPU][Windows] Remove hardcoded SYCL runtime version

### PR DESCRIPTION
**Pull request by min-jean-cho**
oneAPI 2025, targeted for PT 2.6, supports `sycl.lib` on Windows.

### CODE REVIEW

**Comment by guangyey** [comment]
Hi @min-jean-cho, we have a request for the compiler team to enhance its CMake feature. I think we need a discussion about how to keep BC for different compiler versions.

**Comment by min-jean-cho** [comment]
Thanks @guangyey , updated to include `sycl.lib` for current support and also retain older `sycl7.lib` to maintain backward compatibility with oneAPI 2024.

**Comment by min-jean-cho** [comment]
Addressed in https://github.com/pytorch/pytorch/pull/139258

**Pull request closed without merging**
