### PR TITLE
Add ciflow/rocm label to run ROCm jobs

### LINKED ISSUE #4516: Move ROCm jobs to be run on-merge only by default
Given ROCm's queuing woes, lets make those jobs run when a PR is actually merged. This is better than our default option of periodic since it's easier to triage issues, while using way less resources than having them remain in trunk

Components:
- A new "OnMerge" workflow (please come up with a better name :P)
- Move rocm trunk jobs to that workflow
- Ensure hud plays nicely with that workflow
- Ensure failures on that workflow _don't_ block anything. We want the signal from those jobs, but we don't want to have them block viable/strict or affect metrics for now.

If ROCm queueing/perf issues get fixed, then we can consider move these jobs back to trunk.

### PR DESCRIPTION
**Pull request by huydhn**
Fixes https://github.com/pytorch/test-infra/issues/4516.  As this is not part of trunk, it won't block regular merge.  On the other hand, we can still add `ciflow/rocm` to run it on PR.

~~I'll add an auto label rule for this after this is merged and the label becomes available~~ Here it is https://github.com/pytorch/test-infra/pull/4647

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by huydhn** [comment]
> Warning: Unknown label `ciflow/rocm`. Currently recognized labels are
> 
> * `ciflow/binaries`
> * `ciflow/binaries_conda`
> * `ciflow/binaries_libtorch`
> * `ciflow/binaries_wheel`
> * `ciflow/inductor`
> * `ciflow/inductor-perf-compare`
> * `ciflow/mps`
> * `ciflow/nightly`
> * `ciflow/periodic`
> * `ciflow/slow`
> * `ciflow/trunk`
> * `ciflow/unstable`
> 
> Please add the new label to .github/pytorch-probot.yml

This is expected.  The label will only become available after this is merged.

**Comment by jithunnair-amd** [comment]
@huydhn This is great. However, while we need the ability to run full ROCm CI on certain PRs (by using the `ciflow/rocm` label) as well as trunk, we also need the ability to trigger smaller ROCm CI jobs on PRs. This PR of mine is meant to enable that:
https://github.com/pytorch/pytorch/pull/110511

Given that your PR here is removing any ROCm CI entries from trunk.yml, maybe I will add a "-test" entry for ROCm in pull.yml to run the reduced set of tests?

**Comment by huydhn** [comment]
> Given that your PR here is removing any ROCm CI entries from trunk.yml, maybe I will add a "-test" entry for ROCm in pull.yml to run the reduced set of tests? The reason I was hesitating to add it in pull.yml was because that would end up kicking off ROCm CI on **every single PR update**, whereas I was looking to trigger ROCm reduced CI only as part of the pre-merge checks, so it'd typically run once for most PRs, unless they explicitly added the `ciflow/trunk` label early in their PR.

I think this is exactly what `ciflow/trunk` is used for, so you could keep the reduced set of ROCm tests there.  If you want to avoid duplication, we could make sure that the full jobs on `ciflow/rocm` skip those from the reduced set that have already been run.

**Comment by jithunnair-amd** [comment]
> > Given that your PR here is removing any ROCm CI entries from trunk.yml, maybe I will add a "-test" entry for ROCm in pull.yml to run the reduced set of tests? The reason I was hesitating to add it in pull.yml was because that would end up kicking off ROCm CI on **every single PR update**, whereas I was looking to trigger ROCm reduced CI only as part of the pre-merge checks, so it'd typically run once for most PRs, unless they explicitly added the `ciflow/trunk` label early in their PR.
> 
> I think this is exactly what `ciflow/trunk` is used for, so you could keep the reduced set of ROCm tests there. If you want to avoid duplication, we could make sure that the full jobs on `ciflow/rocm` skip those from the reduced set that have already been run.

Okay, I'll make my changes in trunk.yml then. I'd hold off on the "avoid duplication" part until it really becomes a pain point wrt CI load. We use the xml reports from the trunk commits to do our analysis of the PyTorch unit test status, so would prefer those to be complete runs.

**Comment by huydhn** [comment]
> Okay, I'll make my changes in trunk.yml then. I'd hold off on the "avoid duplication" part until it really becomes a pain point wrt CI load. We use the xml reports from the trunk commits to do our analysis of the PyTorch unit test status, so would prefer those to be complete runs.

Sounds good!  Please note that both the full job from `ciflow/rocm` and the reduced set from trunk workflow are run on trunk commits.  So after this change lands, you would just need to do the analysis from `ciflow/rocm` jobs I guess.

**Review by ZainRizvi — APPROVED** [review]

**Comment by BLOrange-AMD** [comment]
@huydhn Could you help to check rocm default testing artifacts uploading progress? Looks like they are missing since the workflow moved to rocm from trunk. E.g., for this [commit](https://hud.pytorch.org/pytorch/pytorch/commit/29844adbe0ad7437ff00f9a3eee544e4e94a10ed), no "Show artifacts" under each job and artifacts zips files are not shown under Artifacts sections.

We are using these artifacts for the internal unit tests status tracking. Thanks for your attention.

image

**Pull request closed without merging**
