### PR TITLE
Migrate CPU unary ops to c10::complex

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #38459 Kill AT_DISPATCH_ALL_TYPES_AND_C10_COMPLEX_AND2
* #37899 Migrate CPU eye to c10::complex
* **#37898 Migrate CPU unary ops to c10::complex**

Differential Revision: [D21554156](https://our.internmc.facebook.com/intern/diff/D21554156)

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Test failure looks to be real.

**Comment by zasdfgbnm** [comment]
Tests failures are caused by wrong implementation of `std::abs`, which is fixed in https://github.com/pytorch/pytorch/pull/37977, I will rebase after https://github.com/pytorch/pytorch/pull/37977 is merged.

**Comment by zasdfgbnm** [comment]
This is also blocked by https://github.com/pytorch/pytorch/pull/38037, and I will rebase after https://github.com/pytorch/pytorch/pull/38037 is merged.

**Review by malfet — APPROVED** [review]
Looks good to me, provided that CI is green.

**Review by VitalyFedyunin — APPROVED** [review]

**Pull request closed without merging**
