### PR TITLE
Fixed crash when calling pad_packed_tensor when packed with cuda tensors and ensure_sorted=false due to indexing with tensors on different devices

### LINKED ISSUE #115027: Calling `pad_packed_sequence` with tensors on cuda and enforce_sorted=false causes issue in C++
### 🐛 Describe the bug

I'm using the C++ API of LibTorch, and I encountered an issue with the `torch::nn::utils::rnn::pad_packed_sequence` function.

When my padded tensor is located on `cuda:0` and I call `pack_padded_sequence` with the `enforce_sorted` flag set to false, the `pad_packed_sequence` fails with the error `indices should be either on cpu or on the same device as the indexed tensor (cpu)`. 

Source of the issue: 

I tracked the source of the issue to the [rnn.h](https://github.com/pytorch/pytorch/blob/main/torch/csrc/api/include/torch/nn/utils/rnn.h#L277C16-L277C16) file, where when the `unsorted_indicies` value is defined, it does an `index` from the lengths tensor. When the padded tensor sent to the pack function is on `cuda:0` the `unsorted_indicies` is also located on the same device, whereas the `lengths` tensor stays on the CPU. The solution is to modify the referenced line to this:

```cpp
lengths.index({unsorted_indices.cpu()}));
```

The PyTorch wrapper already identified this error, and therefore doesn't call this function directly but rather replicated the function in python and adjusted the relevant line to move the unsorted indices to cpu, as you can see [here](https://github.com/pytorch/pytorch/blob/main/torch/nn/utils/rnn.py#L338).

Example code to replicate issue:

```cpp
// Create input on the GPU, sample 5x5
auto input = torch::randn({ 5, 5 }).to(at::ScalarType::Float).cuda();
auto lengths = torch::full({ 5 }, 5);

auto packed = torch::nn::utils::rnn::pack_padded_sequence(input, lengths, false, false);

auto error = torch::nn::utils::rnn::pad_packed_sequence(packed); 
```

Proposed fix (in an upcoming PR):

Move the `unsorted_indices` to CPU, as mentioned above: 
```cpp
lengths.index({unsorted_indices.cpu()}));
```

### Versions

I'm using the C++ version of LibTorch: libtorch-win-shared-with-deps-2.1.1+cu121

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.28.0-rc4
Libc version: N/A

Python version: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 546.01
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3000
DeviceID=CPU0
Family=207
L2CacheSize=16384
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3000
Name=13th Gen Intel(R) Core(TM) i9-13900KF
ProcessorType=3
Revision=

cc @jbschlosser

### PR DESCRIPTION
**Pull request by shaltielshmid**
Fixes #115027

Fix in csrc as done in the python code [here](https://github.com/pytorch/pytorch/blob/main/torch/nn/utils/rnn.py#L338).

### CODE REVIEW

**Comment by drisspg** [comment]
Can you write a test for this failure?

**Comment by shaltielshmid** [comment]
Sure, added

**Comment by drisspg** [comment]
Cool, thank you and one more think, would you mind making the PR title more descriptive?

**Comment by shaltielshmid** [comment]
Sure, done :)

**Review by drisspg — APPROVED** [review]

**Comment by drisspg** [comment]
@Pytorchbot merge

**Comment by drisspg** [comment]
Looks like need to fix some formatting

**Comment by shaltielshmid** [comment]
Fixed the whitespace issue.

**Comment by shaltielshmid** [comment]
Thanks for the patience - I got lintrunner running locally and applied the patches. All fixed now.

**Comment by shaltielshmid** [comment]
Yeah, after the merge failed I ran again:

```bash
lintrunner init
lintrunner -a
```

I believe that one of the lines of the test was > 80 chars, so it split it into two lines.

**Comment by drisspg** [comment]
hmm I would try rebasing and then re-initing the lint runner and running again there might be an update on main

**Comment by shaltielshmid** [comment]
> hmm I would try rebasing and then re-initing the lint runner and running again there might be an update on main

Done! It changed a few spacing stuff

**Pull request closed without merging**
