### PR TITLE
Extend ATen op benchmarks

### PR DESCRIPTION
**Pull request by sanchitintel**
## Summary
Extended ATen op benchmarking coverage:
1. Enabled benchmarking of more ATen ops
2. Enabled benchmarking with BF16 dtype as well, if `AVX512_BF16` ISA is supported (on only Linux).
3. Enabled benchmarking of inplace variants, wherever possible.
4. Enabled benchmarking with channels-last memory layout, wherever applicable

## Verification
Currently, no CI job runs this code, so maybe we can create a new weekly CI job on TorchBench.

cc @jgong5 @mingfeima @XiaobingSuper @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel @jiayisunx @peterbell10 
cc @albanD @ezyang

### CODE REVIEW

**Comment by sanchitintel** [comment]
Hi @mingfeima @jgong5, these op-level benchmarks are not currently run in any CI job.
It can be added to a new nightly/weekly CI job's script, with permission from the PyTorch Release Engineering Team.

**Comment by sanchitintel** [comment]
Hi @xuzhao9, for detecting ATen op-level regressions with `OpBench`, please advise if it'd be better to continue adding op-level benchmarks in the PyTorch repo, and somehow running them in `TorchBench` CI by cloning the PyTorch repo, or if `OpBench` code should be ported from the PyTorch repo to the `TorchBench` repo.

I see that some benchmarks such as Inductor benchmarks are also run on PyTorch CI, so I'm confused as to which course of action would be better - for instance, it would be be simpler for developers to be able to add new benchmarks of the new ATen kernels they would submit PyTorch PRs for (in the same PRs).
Even for existing ATen kernels, IMHO, it'd be great if we could somehow create a PyTorch CI job that'd be run only when some ATen kernels would be modified in a PR, and that job could only benchmark the kernels being modified (in comparison to their main branch counterparts). That would help reduce CI costs & catch regressions at the same time they would occur. If creating such a PyTorch CI job would be too complex, we could simply run OpBench on TorchBench perhaps on a daily/weekly basis (but in that case, please advise if `OpBench` should also be ported over to `TorchBench`, or if it can be retained in the PyTorch repo?). Thanks!

cc @atalman @kit1980

**Comment by janeyx99** [comment]
@xuzhao9 linking you for the benchmarks, but feel free to reassign to a better owner if not you

**Comment by xuzhao9** [comment]
I am okay with either using PyTorch CI or TorchBench CI to host this workflow. For the purpose of this benchmark, since it only depends on operators not models, it seems to make more sense to keep it in PyTorch CI.

Pros and Cons of migrating opbench to TorchBench CI:
Pros:
- TorchBench provides performance metrics tracking and regression detection code. It will be easier to setup a dashboard, regression tracking, and bisection.

Cons:
- TorchBench assumes PyTorch nightly. Code used by opbench might depend on pytorch source code, which might not be available in the nightly release.
- It will be harder to setup pytorch PR level CI to trigger the benchmark on specific PRs.

**Comment by sanchitintel** [comment]
Thanks for your inputs, @xuzhao9! 
Sorry for my late response, BTW. I was on PTO last week.

I'll ping @janeyx99 & you on Slack for help with creating a new PyTorch CI job.
I can also attend the Dev Infra team's Office Hours on Friday.
Thanks!

**Pull request closed without merging**
