### PR TITLE
Add AT_API to Generators

### PR DESCRIPTION
**Pull request by ebetica**
Otherwise, users of the C++ API cannot use pytorch generators.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by peterjc123** [comment]
@ebetica You might need to refactor this class. See the solution 4 in this [post](https://www.codeproject.com/Questions/261491/Exporting-classes-from-a-DLL).

**Comment by ebetica** [comment]
Don't merge I'm maybe abusing the contbuild since I don't have a windows machine...

**Comment by SsnL** [comment]
@ebetica Do you still plan to proceed with this PR?

**Comment by ebetica** [comment]
No, I'm putting another PR out with these changes and more.

**Pull request closed without merging**
