### PR TITLE
Adding missing setting `state_.ptr()` and `hook_.ptr()` to `nullptr`.

### PR DESCRIPTION
**Pull request by sinannasir**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#41537 Adding missing setting `state_.ptr()` and `hook_.ptr()` to `nullptr`.**

Explicitly setting PyObject* state_ and hook_ to nullptr to prevent py::object's dtor to decref on the PyObject again.
Reference PR [#40848](https://github.com/pytorch/pytorch/pull/40848).

Differential Revision: [D22573858](https://our.internmc.facebook.com/intern/diff/D22573858/)

### CODE REVIEW

**Review by mrshenli — APPROVED** [review]
Thanks for fixing! Test failures on `test_interpolate_linear_1d_alert_nondeterministic_cuda` is irrelevant. A rebase should help get rid of that.

**Comment by sinannasir** [comment]
> Thanks for fixing! Test failures on `test_interpolate_linear_1d_alert_nondeterministic_cuda` is irrelevant. A rebase should help get rid of that.

Thanks! Just rebased those errors should go.

**Comment by mrshenli** [comment]
The culprit PR has been reverted by 86590f226e9e754fdc2a6fada8f85e8a3f373328. Dd you rebase to the top of the revert?

**Comment by sinannasir** [comment]
> The culprit PR has been reverted by [86590f2](https://github.com/pytorch/pytorch/commit/86590f226e9e754fdc2a6fada8f85e8a3f373328). Dd you rebase to the top of the revert?

Yes, but looks like the errors are still there.

**Pull request closed without merging**
