### PR TITLE
Hide module paths leaking in the documentation.

### LINKED ISSUE #54354: borked torch.save doc
## 📚 Documentation

https://pytorch.org/docs/stable/generated/torch.save.html

> torch.save(obj, f, pickle_module=<module 'pickle' from '/home/matti/miniconda3/lib/python3.7/pickle.py'>, pickle_protocol=2, _use_new_zipfile_serialization=True)

As you can see it has some private data in it which shouldn't be there.

master has the same issue, but different paths ;)

https://pytorch.org/docs/master/generated/torch.save.html

Thanks.

### PR DESCRIPTION
**Pull request by ysiraichi**
Fixes #54354

### CODE REVIEW

**Comment by ysiraichi** [comment]
Relevant screenshots of the documentation:

#### `torch.save` ([old version](https://pytorch.org/docs/master/generated/torch.save.html))
pic-save

#### `torch.load` ([old version](https://pytorch.org/docs/master/generated/torch.load.html))
pic-load

#### `torch.fx.Tracer` ([old version](https://pytorch.org/docs/master/fx.html?highlight=fx%20tracer#torch.fx.Tracer))
pic-tracer

**Review by mattip — COMMENTED** [review]
Looks good to me.

**Comment by rgommers** [comment]
This now has a merge conflict, can you update @ysiraichi?

@mattip when you approve a PR, you have to request a review from someone who can land it done now), otherwise it'll just sit here.

**Comment by ysiraichi** [comment]
@rgommers Done!

**Review by brianjo — APPROVED** [review]

**Comment by rgommers** [comment]
This is a straightforward fix, it needs landing.

**Comment by mruberry** [comment]
> This is a straightforward fix, it needs landing.

Cool! Thanks for the ping, @rgommers

**Pull request closed without merging**
