### PR TITLE
[fx][quant] Add `intrinsic.quantized.LinearReLU` to the fx2trt converters

### PR DESCRIPTION
**Pull request by z-a-f**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #69574
* __->__ #69573
* #69436

The fx2trt handles the fused operators by replacing them with the TRT layer followed by the TRT activation.
This adds the quantized LinearReLU conversion routine to the fx2trt.
This is required because the `torch.ao.quantization.convert_fx` replaces the Linear + ReLU with a fused LinearReLU operator that fx2trt should be aware of.

Differential Revision: [D32933041](https://our.internmc.facebook.com/intern/diff/D32933041)

### CODE REVIEW

**Comment by z-a-f** [comment]
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32933041).

**Comment by jerryzh168** [comment]
is this for implicit quantization mode? could you add a test?

**Comment by jerryzh168** [comment]
cc @842974287 do we want to continue developing implicit quantization mode?

**Comment by 842974287** [comment]
@jerryzh168 you mean this is for comparison between explicit quantization mode with implicit quantization mode? If that's the case the change looks good to me. 

> do we want to continue developing implicit quantization mode?

I probably won't put any time on this unless it has a huge advantage compare to explicit quantization mode. But this would be a great question for TenosrRT team I think. We probably should align with them on how their focus looks like in terms of these two different modes.

**Pull request closed without merging**
