### PR TITLE
[JIT] Disable Complete Shape Inlining For Testing Purposes

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #59051 Add peephole for len(x.size())
* #58932 Add more shape functions for mobilenet
* #58890 Switch symbolic shape registry to operator map'
* **#56966 [JIT] Disable Complete Shape Inlining For Testing Purposes**
* #56828 Add unary/binary ops necessary for mobilenet

This PR adds a toggle to shape analysis which won't inline complete tensor shapes as constants into the shape compute graph, which is a good stress test on the partial evaluation pipeline.

Differential Revision: [D28444664](https://our.internmc.facebook.com/intern/diff/D28444664)

### CODE REVIEW

**Review by Krovatkin — APPROVED** [review]
:shipit: maybe later on, we could make it a little bit more maintainable by maybe resetting some shapes in advance rather than having a test switch in a pass or maybe you are planning to remove the switch completely.

**Comment by eellison** [comment]
> maybe resetting some shapes in advance rather than having a test switch in a pass

what does this mean ?

**Review by penguinwu — APPROVED** [review]
LGTM

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444664).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444664).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444664).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444664).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444664).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444664).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444664).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444664).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444664).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28444664).

**Pull request closed without merging**
