### PR TITLE
[dynamo] fix potentially missing _torchdynamo_inline from ScriptFunction

### PR DESCRIPTION
**Pull request by williamwen42**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125447

Fix https://github.com/pytorch/pytorch/issues/119747

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by ezyang** [comment]
I don't really know how to evaluate if this fix is right or not

**Comment by williamwen42** [comment]
The codepath for running `test_mm_batching` alone and with `test_python_bindings` beforehand first differs at this line: https://github.com/pytorch/pytorch/blob/a988b4ed76ca6ce43a7e18c2e7976fdbce210375/torch/_dynamo/variables/builder.py#L435.

Perhaps we should also address why the torchscript test seems to be preserving state between tests, i.e. `_try_get_jit_cached_function` returns something different between the two runs.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
