### PR TITLE
add ssim and ms-ssim loss  #6934

### PR DESCRIPTION
**Pull request by musikisomorphie**
Hi, @soumith, @veritas9872. I added ssim/ms-ssim loss in the loss.py and functional.py. Some related units tests are also added in the test_nn.py. As @veritas9872 requested, I exposed the parameters to the users. 
Also, I run some experiments for comparing the results between the original matlab implementation and my version.
For ssim the difference is around 1%, for ms-ssim the difference is slightly larger than ssim.

### CODE REVIEW

**Comment by veritas9872** [comment]
@musikisomorphie I know I am stating the obvious, but I think the pull request failed because of pylint issues and because some file names were used that would not exist on other people's computers.

**Comment by musikisomorphie** [comment]
> @musikisomorphie I know I am stating the obvious, but I think the pull request failed because of pylint issues and because some file names were used that would not exist on other people's computers.

Thank you for the tips, I was quite busy in the last few days and will try to fix it today.

**Comment by musikisomorphie** [comment]
@zou3519, @soumith, @veritas9872, hi guys I corrected the typos in the code, now all checks have passed. feel free to leave comments.

**Comment by veritas9872** [comment]
@musikisomorphie I saw that all tests were passing just a few days ago. I think there were changes to the master branch that broke some code.

**Comment by veritas9872** [comment]
@musikisomorphie Hello. I have been experimenting with the current implementation of SSIM and MS-SSIM in the PR and I have found several issues that I would like to mention.

First, the 'kernel' generated in fspecial_gauss is generated on CPU and not automatically moved to GPU, even when the SSIMLoss object is sent to GPU with .to('cuda'). This causes problems when using data on GPU.

Second, the SSIM implementation currently requires that the data be 4D, which is the most common use-case, but is not related to the definition of SSIM itself. SSIM and MS-SSIM are defined for 2D images, and anything with more than 2 dimensions is merely an average of all its 2D SSIM's. I think it would be nice to let any tensor with more than 2 dimensions have SSIM.

**Comment by veritas9872** [comment]
@musikisomorphie I also have a minor point I wish to add. The current implementation of _fspecial_gaussian uses list comprehension to obtain its values. However, it may be better to use torch.arange since this does not rely on Python.

The equation could be as follows.
coords = torch.arange(size) - (size-1.)/2.

**Comment by musikisomorphie** [comment]
Hi @veritas9872, @soumith, I am afraid I cannot maintain this PR anymore because I have to work on my thesis in the next few months. @veritas9872, feel free to open a PR,  I think my code can be a good starting point for you.

**Comment by MKFMIKU** [comment]
> Hi @veritas9872, @soumith, I am afraid I cannot maintain this PR anymore because I have to work on my thesis in the next few months. @veritas9872, feel free to open a PR, I think my code can be a good starting point for you.

I'd like to open a new PR based on your code~

**Pull request closed without merging**
