### PR TITLE
Fix typo "informations" -> "information"

### PR DESCRIPTION
**Pull request by lithuak**
Hey, fixing the [uncountable](https://www.oxfordlearnersdictionaries.com/definition/american_english/information) noun to the proper form.

### CODE REVIEW

**Comment by lithuak** [comment]
I've signed the CLA

**Comment by lithuak** [comment]
@pmeier hey, just a typo fix. Could you pls review )

**Review by pmeier — APPROVED** [review]
LGTM, thanks!

**Review by albanD — APPROVED** [review]
Thanks

**Pull request closed without merging**
