### PR TITLE
Build PT aarch64 on arm runner

### PR DESCRIPTION
**Pull request by huydhn**
Another fix is needed to address https://github.com/pytorch/pytorch/actions/runs/10118374576/job/27985575620.  The build needs to be done on arm runner to stay compatible with the Docker image.

### Testing

https://github.com/pytorch/pytorch/actions/runs/10118589329/job/27985670691

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by huydhn** [comment]
The failure looks legit, we need to update this test on CPU

**Pull request closed without merging**
