### PR TITLE
[c10d] Add a dynamo example to capture broadcast

### PR DESCRIPTION
**Pull request by alanwaketan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #77940
* #77813
* #77806
* #77686
* #77670
* __->__ #77443
* #77408
* #76946
* #76722

Summary:
This commit adds an example to demonstrate that dynamo can capture
c10d::broadcast.

Test Plan:
python dynamo.py

### CODE REVIEW

**Comment by alanwaketan** [comment]
An example output:
```
(pytorch37) jwtan@ip-10-200-66-59:/fsx/users/jwtan/work/pytorch$ gpurun python dynamo.py 
main process id: 46237
Running basic DDP example on rank 0, and process id: 47842
Running basic DDP example on rank 1, and process id: 47843
my_compiler() called with FX graph:
opcode         name       target                                  args    kwargs
-------------  ---------  --------------------------------------  ------  --------
placeholder    x          x                                       ()      {}
call_function  broadcast  <function broadcast at 0x7fb49c378290>  (x, 0)  {}
output         output     output                                  ((),)   {}
47842 broadcast: tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
my_compiler() called with FX graph:
opcode         name       target                                  args    kwargs
-------------  ---------  --------------------------------------  ------  --------
placeholder    x          x                                       ()      {}
call_function  broadcast  <function broadcast at 0x7f2d5eb09290>  (x, 0)  {}
output         output     output                                  ((),)   {}
47843 broadcast: tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:1')
```

**Comment by jansel** [comment]
Overall this seem reasonable to me.  Awesome to see the example working.  I'm assuming the filename (in the root of pytorch) is the wrong place for it though.

**Comment by alanwaketan** [comment]
> Overall this seem reasonable to me. Awesome to see the example working. I'm assuming the filename (in the root of pytorch) is the wrong place for it though.

haha, I probably won't land this. It's sort of to demonstrate that something is working.

**Comment by alanwaketan** [comment]
> opcode         name       target                                  args    kwargs
> -------------  ---------  --------------------------------------  ------  --------
> placeholder    x          x                                       ()      {}
> call_function  broadcast  <function broadcast at 0x7fb49c378290>  (x, 0)  {}

It looks like this is not the dispatcher version of broadcast. It's the dist.broadcast python wrapper. So we capture the wrong thing with dynamo here.
> output         output     output                                  ((),)   {}

**Pull request closed without merging**
