### PR TITLE
[CUDA graphs] [BC-breaking] Makes torch.cuda.amp.GradScaler scale updates in-place for better composability with graph capture

### PR DESCRIPTION
**Pull request by mcarilli**
I'd like the following pattern (a natural composition of Amp with full fwd+bwd capture) to work:
```python
# Create "static_input" with dummy data, run warmup iterations,
# call optimizer.zero_grad(set_to_none=True), then
g = torch.cuda._Graph()
s.wait_stream(torch.cuda.current_stream())
with torch.cuda.stream(s):
    optimizer.zero_grad(set_to_none=True)
    g.capture_begin()
    with autocast():
        out = model(static_input)
        loss = loss_fn(out)
    scaler.scale(loss).backward()
    g.capture_end()
torch.cuda.current_stream().wait_stream(s)

# Training loop:
for b in data:
    # optimizer.zero_grad() deliberately omitted, replay()'s baked-in backward will refill statically held .grads
    static_input.copy_(b)
    g.replay()
    scaler.step(optimizer)
    scaler.update()
```

Right now `GradScaler` can't work with this pattern because `update()` creates the scale tensor for the next iteration out of place. This PR changes `update()` to act in place on a long-lived scale tensor that stays static across iterations.

I'm not sure how this change affects XLA (see https://github.com/pytorch/pytorch/pull/48570), so we shouldn't merge without approval from @ailzhang @yaochengji.

Tagged bc-breaking because it's a change to the amp update utility function in native_functions.yaml. The function was never meant to be user-facing though.

## BC-breaking note

`GradScaler` now does scale update in-place. This change is not user-visible, `scaler.step(optimizer)` and `scaler.update()` behave as before, however, `_scale` attribute of GradScaler object is preserved instead of being recreated every time. This is done to enable capturing cuda graphs over scaling grads, because cuda graphs bake in the pointers of the data they are operating on, so for correct results the data pointed to has to remain correct.

### CODE REVIEW

**Comment by yaochengji** [comment]
Thanks, @mcarilli. I will take a look this week.

**Comment by ezyang** [comment]
This seems fine. You'll have to suppress the BC problem and get XLA to update, but I don't see any trouble with this otherwise. Are you sure you don't want to also offer the functional version?

**Comment by mcarilli** [comment]
> You'll have to suppress the BC problem and get XLA to update

Should I make any changes to the PR myself to help either of these things?

> Are you sure you don't want to also offer the functional version?

I could easily keep both, but GradScaler is the only client and GradScaler needs the inplace version, so I don't see a need for the functional version. What do you think?

**Comment by ezyang** [comment]
That's fine then. I guess @yaochengji is going to look into the XLA stuff.

**Comment by yaochengji** [comment]
@mcarilli @ezyang 

Submitted a [PR](https://github.com/pytorch/xla/pull/2874) on the torch/xla side.

**Comment by ezyang** [comment]
(I'm just here cuz of the native_functions.yaml change, deferring to the other reviewers)

**Comment by JackCaoG** [comment]
@mcarilli Could you rebase your pytorch pr 😄 ? there is a pytorch pr about `_adaptive_avg_pool3d` merged 4 days and we can't run our CI against your pr to test the pt/xla change without that change.

**Comment by mcarilli** [comment]
@JackCaoG done

@ezyang is there anything you need from me to allow the native_functions.yaml change?

**Comment by ezyang** [comment]
@mcarilli Nope, you're all good from me. Since you originally tagged @ngimel and @ailzhang I was under the impression that you wanted one of the two of them to review. LMK if you want me to take responsibility.

**Comment by ngimel** [comment]
I'm waiting for an ok from XLA side, per @mcarilli's original comment.

**Comment by yaochengji** [comment]
> I'm waiting for an ok from XLA side, per @mcarilli's original comment.

@mcarilli   @ngimel it is OK for me on the pytorch/xla side.

**Comment by mcarilli** [comment]
@ailzhang are you ok with this from a pytorch<->xla standpoint?

**Comment by ngimel** [comment]
BC and xla errors are real (xla probably will require fix on xla side)

**Comment by JackCaoG** [comment]
@mcarilli @ngimel PT/XLA pr https://github.com/pytorch/xla/pull/2874 LGTM, we can merge it once this one is merged

**Review by ailzhang — APPROVED** [review]
Stamping for xla job since we have a PR on pytorch/xla ready. Thanks @yaochengji 
 @mcarilli @JackCaoG !

**Comment by ngimel** [comment]
@JackCaoG, @ailzhang this has landed, can you please merge https://github.com/pytorch/xla/pull/2874?

**Pull request closed without merging**
