### PR TITLE
Fix inconsistent results of string `split` func on JIT mode

### LINKED ISSUE #38207: [JIT] Inconsistent results of string `split` func on JIT mode
## 🐛 Bug

The string `split` func on JIT mode has different results with the python mode, when the strings have multiple spaces.

## To Reproduce

1. Run the following code sample

```
import torch
from typing import List
def simple_split(txt: str) -> List[str]:
	return txt.split()
ss = simple_split
jit_ss = torch.jit.script(ss)
ss('simple     split example') == jit_ss('simple     split example')
```

## Expected behavior

The python and JIT modes are expected to return same results.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @suo

### PR DESCRIPTION
**Pull request by RockingJavaBean**
Resolve #38207

Below is the description of split function according to [Python doc](https://docs.python.org/3.8/library/stdtypes.html?highlight=split#str.split).

```
If sep is not specified or is None,  a different splitting algorithm is applied:  
runs of consecutive whitespace are regarded as a single separator, 
and the result will contain no empty strings at the start or end 
if the string has leading or trailing whitespace.
```

The logic to handle both none and empty separators is added in register_string_ops.cpp as fix.

Signed-off-by: Xiong Wei <xiongw.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by RockingJavaBean** [comment]
In order to handle the empty separator scenario as Python split function, the default value of the separator is changed from the `space` to the` empty string`, leading to the following message.

```
May 20 12:38:03 The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not.  
May 20 12:38:03  
May 20 12:38:03 Broken ops: [ 
May 20 12:38:03 	aten::split.str(str self, str separator=" ", int max=-1) -> (str[]) 
May 20 12:38:03 ] 
```

**Comment by RockingJavaBean** [comment]
@suo please kindly review this pull request.

**Comment by ezyang** [comment]
I am not sure defaulting it to empty string is correct. In Python, an empty separator raises an error, and we should probably follow that behavior.

**Comment by RockingJavaBean** [comment]
@ezyang  Thanks for your kind reply.

The current PR fixes the inconsistent behavior for JIT mode when the separator is not specified,
while it treats `split('')` as same as `split()` and will not raise an error.

In order to follow the same behavior of Python for empty separators, defaulting the separator parameter to `None` is required to distinguish between **split()** and **split('')**.
```python
>>> test = 'a     a'
>>> test.split()
['a', 'a']
>>> test.split('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: empty separator
```

I tried setting the default value of the separator to None via new API.
```
m.def("split.str(str self, str separator=None, int max=-1) -> str[]");
```

However, the following error is thrown
```
RuntimeError: isString() INTERNAL ASSERT FAILED at "../aten/src/ATen/core/ivalue_inl.h":87, 
please report a bug to PyTorch. Expected String but got None
```

Please kindly share suggestions on how to default the separator to None.

**Comment by ezyang** [comment]
you'd have to make the string optional. I'm not sure this is supported by JIT. (@suo, I'm looking to you to find some JIT side to review this, if you won't review it yourself.)

**Comment by suo** [comment]
It should work to make the argument optional. You do it by adding a `?` after the type identifier, like `str? separator` (see the [schema reference](https://github.com/pytorch/pytorch/tree/master/aten/src/ATen/native#registering-a-function-in-native_functionsyaml) if you're interested.)

**Comment by RockingJavaBean** [comment]
Thanks for your kind and detailed suggestions.

I have managed to implement the optional argument in terms of `separator`, and follow the same logic as Python when users do not specify or input empty separators.

Please kindly review the pull request. @suo @ezyang

**Review by suo — APPROVED** [review]
Thank you for the changes! lgtm

**Comment by suo** [comment]
@houseroad: how should we resolve the BC incompatibility errors?

**Comment by eellison** [comment]
This isn't BC incompatible, but it is forward incompatible, you might run into issues there.

**Comment by RockingJavaBean** [comment]
Thanks for the kind help and guidance through this pull request.
Please kindly confirm whether this PR is ready to be merged, or do I need to further update the code before merging?
@ezyang @suo @eellison

**Comment by suo** [comment]
@RockingJavaBean to get the BC check to succeed, please add this schema to the whitelist here: https://github.com/pytorch/pytorch/blob/master/test/backward_compatibility/check_backward_compatibility.py#L19. Then we should be good to go. Thanks!

**Comment by RockingJavaBean** [comment]
@suo  Thanks for sharing how to get the BC checks to succeed, and the `aten::split` schema has been added to the whitelist.
Please kindly help land this PR.

**Comment by RockingJavaBean** [comment]
@suo thanks for your kind help on landing this PR.
However, the landing failed due to the conflict of `check_backward_compatibility.py`, as the commit #39933 updated the whitelist three days ago.
I have resolved the conflict and pushed to the pull request, please kindly help re-land this PR.

**Comment by RockingJavaBean** [comment]
@suo thanks you so much for the help on landing this pull request.
Currently, there is a warning for `Facebook Internal CI` and the status is `Action required`.
I am not quite familiar with the Internal CI, is there any code updates that I should do or is the PR ready to be merged?

**Comment by suo** [comment]
Yep, the PR is ready merge! Each time you update it, we need to sync it with our internal CI system and run tests. Then when they pass, we should be good to land. I'll try to land it tonight :)

**Comment by RockingJavaBean** [comment]
thank you so much throughout this pull request.
BTW: It seems `test/backward_compatibility/check_backward_compatibility.py` is frequently updated and often leads to the conflict of code.

**Pull request closed without merging**
