### PR TITLE
Fix align corner docs

### PR DESCRIPTION
**Pull request by daquexian**
I believe the `True` and `False` in the doc are reversed :)

### CODE REVIEW

**Comment by soumith** [comment]
cc: @SsnL

**Review by ssnl — APPROVED** [review]
Thank you :)

**Comment by bnehoran** [comment]
**Woah, wait a moment, this change seems incorrect.**

If I am not mistaken, the newer default mode, `align_corners=False`, in fact aligns the tensors at the corner points of their corner pixels, while the legacy mode, `align_corners=True`, aligns the centers of the corner pixels (which is the problematic behavior that causes dependency on input size).

This is in fact what the documentation said before this pull request, so it should not have been changed.
@SsnL please verify what I am saying, but I think this change should be reverted.

If anything, this might be an indication that the naming is confusing people, so maybe the name of the option should be changed to make it clearer and/or more intuitive. I understand that changing the name of the option could messy, though, but maybe it is worth it to avoid future confusion.

(Sorry for taking so long to notice this, by the way. I only realized this documentation change had been made now that I'm adding the documentation for the equivalent functionality being added to `grid_sample`.)

**Comment by daquexian** [comment]
Sorry for making the mistake, the name is a bit confusing :)

**Pull request closed without merging**
