### PR TITLE
[jit] Warn when tracing legacy constructors

### PR DESCRIPTION
**Pull request by driazati**

### CODE REVIEW

**Comment by suo** [comment]
We should change the LSTM implementation before landing this.

**Review by suo — APPROVED** [review]

**Comment by fritzo** [comment]
@driazati What is the recommended replacement? Should we replace
`x.new_foo(shape)` -> `torch.foo(shape, dtype=x.dtype, device=x.device)`?
See also #18434

**Comment by fritzo** [comment]
@neerajprad We should also avoid legacy constructors in torch.distributions.

**Comment by fritzo** [comment]
@soumith Is there a chance we can revert this before the 1.1 release? There is still heavy usage of the `.new_*()` constructors in torch.distributions, and I'd like to avoid burdening jit users with deprecation warnings. Alternatively, @neerajprad offered to update torch.distributions before the 1.1 release.

cc @colesbury

**Comment by soumith** [comment]
the 1.1 release is just about going live now. i think it's a bit too late, but let me check

**Comment by SsnL** [comment]
Hmm we introduced these in `0.4` and heavily advertised them and now they are legacy?!!

**Pull request closed without merging**
