### PR TITLE
Dispatch to mv rather than mm in the case that tensor1.ndim == 1 and tensor2.ndim == 2

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #76828
* #75197
* #75196
* __->__ #75195
* #75279
* #75194

This should hopefully be faster, it makes the calling code simpler, and
it solves a bug when using matmul with the out= parameter (before it
would throw an incorrect error).

### CODE REVIEW

**Comment by ezyang** [comment]
Can you repro it locally?

I looked over the patch and it looks... fine-ish? The contiguous changes look a little skeevy

**Comment by Lezcano** [comment]
I could not reproduce it locally. This PR should just be one line. I pushed some further changes to start debugging it via CI, but this is certainly not the best approach.

Once we had access to sshing into the jobs, but J believe that's not working atm...

**Review by ezyang — APPROVED** [review]

**Comment by Lezcano** [comment]
This PR needs a small fix on the XLA side @JackCaoG

**Comment by Lezcano** [comment]
Actually, the fix was already written for the previous PR: https://github.com/pytorch/xla/pull/3154

**Comment by JackCaoG** [comment]
@Lezcano Let me rebase that pr and run against this pr. Want to make sure the same fix still works.

**Pull request closed without merging**
