### PR TITLE
[spmd expansion] speed up expansion by ~5x

### PR DESCRIPTION
**Pull request by yifuwang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #98233
* #98232
* #98231
* __->__ #98230
* #98229

According to profiling, the top two expensive operations in spmd expansion are propagate_op_sharding and make_fx (for every dispatcher op node). This PR makes the following changes to speed up spmd expansion:
- We are unneccessarily doing propagate_op_sharding twice for every op. Remove one.
- When no tensor redistribution is required, we only need to update non-tensor args of the node according to op_schema and avoid building a GraphModule just for the node.

On a DDP use cases + foreach Adam, this change speeds up spmd expansion by ~5x (~10 min -> ~2 min).

Differential Revision: [D44615038](https://our.internmc.facebook.com/intern/diff/D44615038/)

### CODE REVIEW

**Review by mrshenli — APPROVED** [review]
This one supersedes #98178

**Comment by mrshenli** [comment]
Lint failure is real:

```
>>> Lint for torch/distributed/_spmd/distribute.py:

  Warning (UFMT) format
    Run `lintrunner -a` to apply this patch.

    You can run `lintrunner -a` to apply this patch.

    148  148 | 
    149  149 | 
    150  150 | def _get_dtensor_dispatch_graph(
    150      |-    node: fx.Node,
    151      |-node_to_obj: Dict[fx.Node, object],
    152      |-force_make_fx: bool = False
         151 |+    node: fx.Node,node_to_obj: Dict[fx.Node, object],force_make_fx: bool = False
    154  152 | ) -> Optional[fx.GraphModule]:
    155  153 |     def _remap_arg(arg: object) -> object:
    156  154 |         if isinstance(arg, torch.fx.Node):
--------------------------------------------------------------------------------
    488  486 |             )
    489  487 | 
    490  488 |         elif isinstance(node.target, torch._ops.OpOverload):
    490      |-            replacement = _get_dtensor_dispatch_graph(
    491      |-                node, node_to_obj
    492      |-            )
         489 |+            replacement = _get_dtensor_dispatch_graph(node, node_to_obj)
    494  490 |             if replacement is not None:
    495  491 |                 node_replacements[node] = replacement
    496  492 |         elif node.op == OP.OUTPUT:



>>> Lint for torch/distributed/_tensor/dispatch.py:

  Warning (UFMT) format
    Run `lintrunner -a` to apply this patch.

    You can run `lintrunner -a` to apply this patch.

     9   9 | from torch.distributed._tensor.op_schema import (
    10  10 |     ArgsType,
    11  11 |     KwargsType,
        12 |+    OpSchema,
        13 |+    OutputSharding,
    12  14 |     OutputSpecType,
    13  15 | )
    13     |-from torch.distributed._tensor.op_schema import OpSchema, OutputSharding
    15  16 | from torch.distributed._tensor.placement_types import DTensorSpec
    16  17 | from torch.distributed._tensor.redistribute import redistribute_dtensor
    17  18 | from torch.distributed._tensor.sharding_prop import ShardingPropagator


You can reproduce these results locally by using `lintrunner`.
```

**Comment by yifuwang** [comment]
@yifuwang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44615038).

**Comment by yifuwang** [comment]
@yifuwang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44615038).

**Comment by yifuwang** [comment]
@yifuwang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44615038).

**Comment by yifuwang** [comment]
Superceded by 98389

**Pull request closed without merging**
