### PR TITLE
[ROCm] hip-clang enablement

### PR DESCRIPTION
**Pull request by iotamudelta**
Initial enabling of the upcoming hip-clang compiler for the PyTorch source base.

Changes:
* update the Eigen submodule to a version including our upstreamed hip-clang enabling there
* modify a few ifdef guards with the `__HIP__` macro used by hip-clang
* use `__lane_id` instead of `hc::__lane_id`
* add Debug flags for ROCm to the cmake infrastructure

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Fair enough, but what exactly is going on with the new `__HIP__` guard? When should we use this and not the existing idiom?

**Comment by iotamudelta** [comment]
@ezyang It is only necessary in places where the featureset between hip-clang and hcc diverges. So you shouldn't need to do it. Supporting both should be a strictly temporary undertaking.

Thanks for review and approval! :-)

**Comment by ezyang** [comment]
This is pretty non-obvious, so if you want to submit a follow up PR adding `// See Note [hip-clang and hcc feature divergence]` to each site, and a note saying what you said above, that would be much appreciated.

**Comment by iotamudelta** [comment]
@ezyang will do!

**Pull request closed without merging**
