### PR TITLE
Remove depracated alias macro(2/3)

### PR DESCRIPTION
**Pull request by fffrog**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #137562
* __->__ #137559

**Detailed Descriptions:**
- Remove AT_ASSERTM Macro

### CODE REVIEW

**Comment by FFFrog** [comment]
@ezyang , please help to take a loot at this PR， thank you:D

**Comment by ezyang** [comment]
Ok, so, this change is not actually mechanical. The question you need to ask for each of these is "if this error triggered, should the user file a bug to PyTorch? If yes use TORCH_INTERNAL_ASSERT, otherwise use TORCH_CHECK

**Comment by FFFrog** [comment]
@ezyang, have rebased it, thank you for imporing it by yourself.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
