### PR TITLE
[EZ] Do not checkout builder for Linux builds

### PR DESCRIPTION
**Pull request by malfet**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #142282
* #142382
* #142277

All logic should have been migrated to .ci/manywheel folder from builder repo a while back

### CODE REVIEW

**Review by atalman — APPROVED** [review]
lgtm

**Comment by malfet** [comment]
> @malfet Please rebase and also bring, check_binary.sh https://github.com/pytorch/pytorch/blob/main/.circleci/scripts/binary_linux_test.sh#L93

It's not used from build step, and I plan to keep test as is for now

**Comment by atalman** [comment]
@malfet builder is still used in test step. Why not eliminate dependency on builder completely ?

**Comment by malfet** [comment]
> @malfet builder is still used in test step. Why not eliminate dependency on builder completely ?

Yes, this is expected, I can do it in the followup PRs, this PR is specifically about `build`

**Comment by jeffdaily** [comment]
This broke rocm nightly builds.

**Comment by huydhn** [comment]
> This broke rocm nightly builds.

I was looking into this during my investigation of the broken check workflow lint job in trunk.  The fix is here https://github.com/pytorch/pytorch/pull/142476, this is a landrace between https://github.com/pytorch/pytorch/pull/142294 abd https://github.com/pytorch/pytorch/pull/142282

**Comment by atalman** [comment]
I believe this should take care of rocm breakage due to missing check_binary.sh script: https://github.com/pytorch/pytorch/pull/142482

**Pull request closed without merging**
