### PR TITLE
s390x SIMD: Propagate NaN in minimum and maximum operations

### PR DESCRIPTION
**Pull request by AlekseiNikiforovIBM**
This change fixes NNUtilsTest.ClipGradNormErrorIfNonfinite test from test_api c++ unit test when ZVECTOR is enabled.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Comment by AlekseiNikiforovIBM** [comment]
Could someone help with label please?

**Pull request closed without merging**
