### PR TITLE
Fix batch norm JIT dispatch

### LINKED ISSUE #4549: RuntimeError: Unsupported op descriptor: thnn_batch_norm_forward-5-eps-momentum-training. File a bug report.
I started getting this with the latest code while using JIT:

RuntimeError: Unsupported op descriptor: thnn_batch_norm_forward-5-eps-momentum-training. File a bug report.

It did not happen 7 days ago and still does not happen if I roll back pytorch to the version I had 7 days ago.  Do you need any simplified test case to fix it?

### PR DESCRIPTION
**Pull request by apaszke**
Fixes #4549.

### CODE REVIEW

**Comment by apaszke** [comment]
cc: @ezyang

**Comment by ezyang** [comment]
SHIP IT

**Comment by ezyang** [comment]
Where's the test :)

**Comment by apaszke** [comment]
What test? :)

**Pull request merged**
