### PR TITLE
Add support for constant propagation of aten::size

### PR DESCRIPTION
**Pull request by asuhan**
The input doesn't need to be constant, just its size must be known.

### CODE REVIEW

**Comment by asuhan** [comment]
Context: this is needed for the XLA integration. There's no clean way to implement `aten::size` in XLA, but it can be statically evaluated when all the shapes are known. ResNet-50 uses this operator after the average pool, it would prevent translation to XLA without constant propagation.

**Review by apaszke — CHANGES_REQUESTED** [review]
I think this really should live in the XLA integration code. We generally don't want to propagate those shapes statically because it drastically reduces the generalization abilities of traces when exported via ONNX (e.g. you can no longer change the batch size), and should never happen when you use the PyTorch JIT directly.

We've spent a lot of work to *recover* those size calls in traces because it caused us a lot of trouble, and this basically reverts all of it.

**Comment by asuhan** [comment]
We can definitely do that, but would be nice to share the implementation. Would it be acceptable to make this optimization optional and turn it off outside of our integration? Any other ways which avoid the code duplication would be great too.

**Comment by asuhan** [comment]
Thinking better of it, we can achieve the same effect with a separate pass for `aten::size`, then run constant propagation on top of it.

**Pull request closed without merging**
