### PR TITLE
C++ changes toward libtorch and libcaffe2 unification

### PR DESCRIPTION
**Pull request by kostmo**
* adds TORCH_API and AT_CUDA_API in places
* refactor code generation Python logic to separate
  caffe2/torch outputs
* fix hip and asan
* remove profiler_cuda from hip
* fix gcc warnings for enums
* Fix PythonOp::Kind

### CODE REVIEW

**Comment by kostmo** [comment]
Current errors in the ROCM builds:
```
test_data_parallel_module (__main__.TestNN) ... /usr/bin/python: symbol lookup error: /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so: undefined symbol: _ZN5torch4cuda7scatterERKN2at6TensorEN3c108ArrayRefIlEERKNS5_8optionalISt6vectorIlSaIlEEEElRKNS8_IS9_INS8_INS5_3hip27HIPStreamMasqueradingAsCUDAEEESaISH_EEEE
```
and
```
test_broadcast_double_backwards_gpu (__main__.TestNN) ... /usr/bin/python: symbol lookup error: /var/lib/jenkins/.local/lib/python2.7/site-packages/torch/lib/libtorch_python.so: undefined symbol: _ZN5torch4cuda19broadcast_coalescedEN3c108ArrayRefIN2at6TensorEEENS2_IlEEm
```

That is, `torch::cuda::scatter` and `torch::cuda::broadcast_coalesced`.

**Comment by kostmo** [comment]
> That is, `torch::cuda::scatter` and `torch::cuda::broadcast_coalesced`.

Note that those two functions are marked with `AT_CUDA_API`.  Is there something we need to add to the ROCM build to support `AT_CUDA_API`?

**Comment by dzhulgakov** [comment]
Again, similarly to the previous situation, in this PR they should be marked with TORCH_API.

Reasoning: we have separate libraries for libcaffe2.so and libcaffe2_gpu.so (if USE_CUDA=1). But only one library libtorch.so that conditionally includes or not includes cuda sources in it (if USE_CUDA=1). Therefore, in the unified PR, they had to be marked with AT_CUDA_API that corresponded to libcaffe2_gpu.so but in this PR since you don't move them, they should be marked with TORCH_API.

If you want less changes - you can mark them with TORCH_CUDA_API and define TORCH_CUDA_API to be TORCH_API for now. Then in later diff you'd define TORCH_CUDA_API to be AT_CUDA_API

**Comment by kostmo** [comment]
> they should be marked with TORCH_API

Ok, I [did that experiment in this other PR](https://github.com/pytorch/pytorch/pull/19709/files#diff-6817e033b2cf3a00583199aa7ff46621), but I'm getting the same error: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test/18524/console

**Comment by dzhulgakov** [comment]
Ah, I think in the original PR we fixed that by adding comm.cpp in USE_ROCM section (see Junjie's comments on https://github.com/pytorch/pytorch/pull/17783 ). comm.cpp is listed three times:
1) in TORCH_SRCS if USE_CUDA
2) in TORCH_PYTHON_SRCS if USE_CUDA
3) in TORCH_PYTHON_SRCS if USE_ROCM

You kill (2) and (3) but we should add (4) for symmetry:
4) in TORCH_SRCS if USE_ROCM

**Review by dzhulgakov — APPROVED** [review]
Ship it!

**Pull request closed without merging**
