### PR TITLE
single import

### PR DESCRIPTION
**Pull request by JayPatelSoftwareArchitect**
Single import

### CODE REVIEW

**Review by heitorschueroff — APPROVED** [review]
LGTM. Thank you for the PR.

**Comment by heitorschueroff** [comment]
@ezyang Were the imports duplicated on purpose? Could you help review this quick PR please?

**Review by hameerabbasi — APPROVED** [review]
We had circular imports at one point if this was at the top, which would have made this hard.

Now this is possible without issue.

**Comment by ezyang** [comment]
I don't see anything wrong with the substantive content of this PR. However, it has incorrect submodule updates and cannot be landed as is.

I'm not sure how much this conflicts with @robieta's work, cc'ing him here.

**Comment by ezyang** [comment]
@heitorschueroff I'm leaving the landing to you, as first one here!

**Comment by robieta** [comment]
Yeah, shouldn't be a bad merge conflict, if at all. (Famous last words...) By all means land once the submodules are fixed.

**Comment by heitorschueroff** [comment]
@JayPatelSoftwareArchitect Could you rebase this branch and update the submodules? I'll land it after that, thanks!

**Comment by robieta** [comment]
Closing since https://github.com/pytorch/pytorch/pull/48964 has been merged.

**Pull request closed without merging**
