### PR TITLE
[Easy] Remove unused return type from utils

### PR DESCRIPTION
**Pull request by voznesenskym**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #110888
* __->__ #110887

### CODE REVIEW

**Comment by ezyang** [comment]
Do we have to do this? I reconfirmed that there are no uses of this function in fbcode, but this change still gives me the jeebies because if you do have someone relying on this behavior they will now silently always get a falsey None as output, no typechecking to save them.

It doesn't really seem like it should be a big deal for these to return a bool or not, as far as Dynamo is concerned.

**Comment by voznesenskym** [comment]
> Do we have to do this? I reconfirmed that there are no uses of this function in fbcode, but this change still gives me the jeebies because if you do have someone relying on this behavior they will now silently always get a falsey None as output, no typechecking to save them.
> 
> It doesn't really seem like it should be a big deal for these to return a bool or not, as far as Dynamo is concerned.

it's unused, but we can just return a fake bool under compile only.

**Review by ezyang — APPROVED** [review]
ok, the justification makes sense. Let's pray

**Pull request closed without merging**
