### PR TITLE
[ROCm] in test_cuda.py, re-enable skipped tests

### PR DESCRIPTION
**Pull request by jeffdaily**
- test_stream_context
- test_cublas_multiple_threads_same_device
- test_cusparse_multiple_threads_same_device

These tests passed three rounds of CI.

### CODE REVIEW

**Review by vincentqb — APPROVED** [review]
LGTM

**Comment by jeffdaily** [comment]
Rebased to fix previous CI errors.

**Comment by vincentqb** [comment]
Resubmitted the import request. Once all tests are run after a few hours, next step is to land :)

**Comment by jeffdaily** [comment]
@vincentqb is there an internal build failure?

**Pull request closed without merging**
