### PR TITLE
[2/N] Fix NVCC warnings 

### PR DESCRIPTION
**Pull request by cyyever**
Follows #130191

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
Curious--should we expect to see fewer NVCC warnings in any of the CUDA builds in CI? How do we verify that these warnings are gone?

**Comment by cyyever** [comment]
> Curious--should we expect to see fewer NVCC warnings in any of the CUDA builds in CI? How do we verify that these warnings are gone?

I will turn more warnings into errors after all those fixes, so that future errors can't be ignored in CI.

**Review by ezyang — APPROVED** [review]
suuuure

**Pull request closed without merging**
