### PR TITLE
Have irange use `if constexpr`

### PR DESCRIPTION
**Pull request by r-barnes**
Test Plan: Sandcastle

Differential Revision: D42997779

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by soumith — APPROVED** [review]

**Comment by Skylion007** [comment]
Actually, wait this is in a header file. Are the FB internal libraries up to C++17 yet? Otherwise, this will break them and the change will be reverted.

**Comment by Skylion007** [comment]
The C++17 commit got reverted so aborting the merge

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
