### PR TITLE
remove dead proto_convert library

### PR DESCRIPTION
**Pull request by dagitses**
remove dead proto_convert library

Summary:
This has no code, only a collection of headers. Just make sure the
only thing that includes it still builds.

Test Plan: Rely on CI.

Reviewers: sahanp

Subscribers:

Tasks:

Tags:

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/pytorch/pull/97322).
* #97337
* #97336
* #97335
* #97334
* #97325
* #97324
* #97323
* __->__ #97322

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by kit1980** [comment]
Looks like the revert broke caffe2 builds: https://hud.pytorch.org/pytorch/pytorch/commit/13fbf932381e577e9d6fc7696e475da7e8bcd7a7

**Pull request closed without merging**
