### PR TITLE
Add pybind trampoline for ProcessGroup and Work

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #66338

This commit exposes c10d extension API to Python land. Users can
now override c10d communication behaviors in pure Python, and no
longer needs to go through the cpp extension steps.

Differential Revision: [D31514351](https://our.internmc.facebook.com/intern/diff/D31514351)

### CODE REVIEW

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31514351).

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31514351).

**Review by hjm-aws — APPROVED** [review]

**Review by rohan-varma — APPROVED** [review]
Looks great! Just one small q about `Work` vs `_Work`.

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31514351).

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31514351).

**Pull request closed without merging**
