### PR TITLE
Update jenkins caffe2 scripts for ROCm circleci images.

### PR DESCRIPTION
**Pull request by jeffdaily**
Remove work-around to install conda locally for older ROCm jenkins images.
Remove use of sudo to install pip packages.
Install missing packages for caffe2 test.sh needs on ROCm.

CC @ezyang @xw285cornell @sunway513

### CODE REVIEW

**Comment by jeffdaily** [comment]
Wasn't sure if the removal of `sudo` from the pip commands would break any other CI backends.  When using `sudo pip`, the PATH doesn't include /opt/conda/bin.  Removing sudo fixes the rocm CI runs.

This should be the last change needed to fix the transition to the new circleci-based docker images.  The pytorch build/test1/test2 is working, as well as caffe2 build and bench.   It's just caffe2 test that fails due to the issues addressed in this PR.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Both sets of failures are real and need fixing.

**Comment by jeffdaily** [comment]
Yes, failures were real.  The circleci caffe2_onnx environments differ from the circleci ROCm caffe2 environment.  The difference is whether the OS-distributed python package is used versus having installed conda.  I added a `$MAYBE_SUDO` wrapper to handle this case.

**Comment by jeffdaily** [comment]
@ezyang thanks for merging the windows ci fix from master.   Looks like CI is good now.

**Pull request closed without merging**
