### PR TITLE
Fix: [ATen] Add some missing moves

### PR DESCRIPTION
**Pull request by Skylion007**
Related to #88512 , but for ATen. This should reduce a number of copies and inefficient atomic smart pointer increments.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @VitalyFedyunin @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Comment by Skylion007** [comment]
@jgong5 Merged master to fix the flake, this PR is ready to be merged assuming all tests pass.

**Review by ezyang — APPROVED** [review]

**Comment by Skylion007** [comment]
@ezyang Failure here seems to be another infra failure unrelated to this PR.

**Comment by Skylion007** [comment]
Tracking here: https://github.com/pytorch/pytorch/issues/88968

**Pull request closed without merging**
