### PR TITLE
[CI] Switch inductor integration tests to run on linux.gcp.a100

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96107

Summary: Inductor integration tests have shown annoying flaky failures
that are not reproducible on our A100 dev environment. Switch tests to
run on GCP A100 instance.

### CODE REVIEW

**Review by weiwangmeta — APPROVED** [review]
LGTM. Fingers crossed.

**Comment by weiwangmeta** [comment]
Looks like two further changes are needed: 
1) sm86 -> sm80 (mandatory) 
2) similar to https://github.com/pytorch/pytorch/blob/master/.github/workflows/inductor-perf-test-nightly.yml#L39 , I haven't figure out how to get GCP runners to upload to S3 (also related is that whether we want A100 runners from GCP to do so as A100 runners from GCP are still sort of experimental/tempoary).  By adding use-gha, artifacts will upload to github page similar to the nightly job.

**Review by weiwangmeta — CHANGES_REQUESTED** [review]
Please see the comments.

**Review by weiwangmeta — APPROVED** [review]
Looks good to me. I will watch for any capacity issues.

**Comment by desertfire** [comment]
Still shows flaky failure, so it is not a hardware-dependent issue. Close this one.

**Comment by weiwangmeta** [comment]
Good experiment, nice finding!

**Pull request closed without merging**
