### PR TITLE
Export XPU oneDNN header to the public

### PR DESCRIPTION
**Pull request by guangyey**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #139177

# Motivation
Export oneDNN header to the public, for example, the third-party extension now could use `GpuStreamManager` to manage `dnnl::stream` to submit oneDNN kernel.

### CODE REVIEW

**Review by gujinghui — APPROVED** [review]

**Comment by guangyey** [comment]
@malfet @atalman @ezyang May I know if could you help review this PR?

**Review by EikanWang — APPROVED** [review]

**Review by malfet — APPROVED** [review]
Sure, though in the long run it should be made conditional on build option

**Comment by guangyey** [comment]
Thanks, @malfet  I will file another PR to improve them by conditional of build option

**Pull request closed without merging**
