### PR TITLE
try to get rid of tmp_install

### PR DESCRIPTION
**Pull request by zdevito**
Rehash of previous attempts. This tries a different approach where we accept the install as specified in cmake (leaving bin/ include/ and lib/ alone), and then try to adjust the rest of the files to this more standard layout.

### CODE REVIEW

**Comment by peterjc123** [comment]
@zdevito Would you please change the path for caffe2.python on Windows, too? It is likely to be forgotten because it doesn't go through any test currently.

**Comment by peterjc123** [comment]
About the windows error, some of the dlls like `shm.dll`, `torch.dll`, `torch_python.dll` are in `lib` and others are in `lib`, such as `c10.dll` and `caffe2.dll`,

**Comment by zdevito** [comment]
@peterjc123 sure -- it would be nice to get more tests added as well to cover windows because #16412 was fixing problems that don't show up in the CI. This makes it extremely hard to maintain an efficient and understandable build script.

**Review by ezyang — APPROVED** [review]
okey dokey

**Pull request closed without merging**
