### PR TITLE
[ROCm] Enable skipped distributed global tests

### PR DESCRIPTION
**Pull request by jaglinux**
The PR #47898 fixes the global tests. Hence enabling the tests.

Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>

### CODE REVIEW

**Comment by jaglinux** [comment]
@jeffdaily @pruthvistony please review.

**Comment by jeffdaily** [comment]
LGTM.  Let's confirm with the ROCm CI results.

**Review by rohan-varma — COMMENTED** [review]
For context, I think the distributed multi-gpu tests were disabled as part of https://github.com/pytorch/pytorch/pull/47703, we are currently working on re-enabling them after which we should get good additional signal for this PR. We are checking if we can re-enable after the earlier fix in https://github.com/pytorch/pytorch/pull/47639.

**Comment by jaglinux** [comment]
@rohan-varma can you please approve the PR ?

**Review by rohan-varma — APPROVED** [review]
Thanks for the ping, LGTM

**Pull request closed without merging**
