### PR TITLE
[dynamo] Remove dead code - `real_value_tensor_positive_aliases`

### PR DESCRIPTION
**Pull request by jon-chuang**
(legality) It is currently impossible (and should remain impossible) - (due to dedup guards - all static tensors are unique) - to access the same **static** tensor value from a **different source**.

As for `getattr(nn.Module, tensor)` source collisions, we will never instantiate a `nn.Module getattr` source for a static tensor, due to:
- side-effect tracking (as long as we track all static tensors - see also https://github.com/pytorch/pytorch/pull/112025 for extra sanity check)
- See: https://github.com/pytorch/pytorch/blob/c8a5bb451e2071d6d5c3188454ed10f03040206b/torch/_dynamo/variables/builder.py#L227

(no worse) In any case, this field is currently unused.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by ezyang** [comment]
Voz please review, on cursory glance this looks fine.

**Comment by jon-chuang** [comment]
@voznesenskym gentle ping

**Review by voznesenskym — APPROVED** [review]

**Comment by voznesenskym** [comment]
Good cleanup, leftover from before we had the dedup logic I think, good find. Thanks!

**Comment by lezcano** [comment]
This PR is https://github.com/pytorch/pytorch/pull/111207 and its reland https://github.com/pytorch/pytorch/pull/112039 lol

**Comment by jon-chuang** [comment]
> This PR is https://github.com/pytorch/pytorch/pull/111207 and its reland https://github.com/pytorch/pytorch/pull/112039 lol

:laughing: + voz reviewed both!

**Pull request closed without merging**
