### PR TITLE
remove UsageError in favor of ValueError

### PR DESCRIPTION
**Pull request by pmeier**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#61031 remove UsageError in favor of ValueError**
* #60639 change language from array to tensor
* #60638 relax type equality constraint

See https://github.com/pytorch/pytorch/pull/58916#issuecomment-868519515.

Differential Revision: [D29626810](https://our.internmc.facebook.com/intern/diff/D29626810)

### CODE REVIEW

**Review by NicolasHug — APPROVED** [review]
LGTM, thanks a lot!

**Review by mruberry — APPROVED** [review]
Nice simplification.

Thanks for helping us review assert_close, @NicolasHug

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29626810).

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29626810).

**Pull request closed without merging**
