### PR TITLE
Make torch.Tensor(torch.tensor(1.0)) work

### LINKED ISSUE #58884: torch.Tensor constructor doesn't accept scalar (IndexError: slice() cannot be applied to a 0-dim tensor.)
```
>>> import torch
>>> torch.Tensor(torch.tensor(2.0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: slice() cannot be applied to a 0-dim tensor.
```

This should work.

cc @gchanan @mruberry

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#58885 Make torch.Tensor(torch.tensor(1.0)) work**

Fixes #58884

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D28687510](https://our.internmc.facebook.com/intern/diff/D28687510)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
LGTM

Does that mean that the legacy Tensor constructor is not going away? Or just a simple fix?

btw do you know why "slice" is excluded from the python binding in [here](https://github.com/pytorch/pytorch/blob/b4f3a989da375675785754e4b12d2ce757a1ffaa/tools/autograd/gen_python_functions.py#L91) ?

**Comment by mruberry** [comment]
> Does that mean that the legacy Tensor constructor is not going away? Or just a simple fix?

We should deprecate it; I've made a note to add it to the deprecations tracking issue https://github.com/pytorch/pytorch/issues/55953.

**Comment by ezyang** [comment]
So, I have a longer design doc coming about this soon, but I want us to consider not deprecating the `torch.Tensor(tensor)` constructor, as it means that subclasses cannot do a conventional `super().__init__/__new__` to initialize the parent fields of Tensor. More coming shortly.

**Comment by ezyang** [comment]
FWIW, it's not *impossible* to work around this problem; if you're overriding `__new__`, you can call whatever Tensor constructor you want, you don't have to call `super().__new__`. But your code is less Python idiomatic in this case.

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28687510).

**Review by gchanan — APPROVED** [review]

**Pull request closed without merging**
