### PR TITLE
Reland Refactor c10::complex and cleanup c10::Scalar"

### PR DESCRIPTION
**Pull request by zasdfgbnm**
This reverts commit 8556664d6896a8e7f48f1c419e06e0568b9ee09e.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
@albanD Why this is reverted?

**Comment by albanD** [comment]
The problem is that the CI on the PR was 15 days old. And merging in master now breaks it :/ 
See https://ezyang.github.io/pytorch-ci-hud/build2/pytorch-master for which build fail (or wait for CI on this new PR)
But typical build failure look like:
```
May 30 22:34:51 /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/ScatterGatherKernel.cu(311): error: class "c10::complex<double>" has no member "storage"
May 30 22:34:51           detected during:
May 30 22:34:51             instantiation of "void at::native::scatter_add_op(scalar_t *, const scalar_t *) [with scalar_t=c10::complex<double>, <unnamed>=0]" 
May 30 22:34:51 (94): here
May 30 22:34:51             instantiation of "void at::native::_cuda_scatter_gather_internal_kernel<is_scatter_like, scalar_t>::operator()(at::TensorIterator &, int64_t, int64_t, const func_t &) [with is_scatter_like=true, scalar_t=c10::complex<double>, func_t=lambda [](auto *, const auto *)->auto]" 
May 30 22:34:51 (159): here
May 30 22:34:51             instantiation of "void at::native::cuda_scatter_gather_base_kernel<is_scatter_like, cast_to_opaque>::operator()(at::Tensor &, int64_t, const at::Tensor &, const at::Tensor &, const std::__cxx11::string &, const func_t &) [with is_scatter_like=true, cast_to_opaque=false, func_t=lambda [](auto *, const auto *)->auto]" 
```

**Comment by albanD** [comment]
You can add me as a reviewer on the new version once it is updated for current master. I can reland it.

**Comment by zasdfgbnm** [comment]
@albanD This is done

**Comment by albanD** [comment]
Thanks for the update. The fix looks good.
rocm should be fixed on master right now. Can you rebase to make sure that the issue here is just because of an older version. Or we should find out why this happens.

**Comment by zasdfgbnm** [comment]
@albanD I have rebased, but ROCm failure is definitely not related. It is something like connection timeout, it is hard to imagine how a network connecting failure could be related to complex number implementation change.

**Comment by albanD** [comment]
All is green now, thanks !

**Review by albanD — APPROVED** [review]
Thanks !

**Pull request closed without merging**
