### PR TITLE
torchbench pin upd: hf auth token, clip, whisper, llamav2, sd

### PR DESCRIPTION
**Pull request by msaroufim**
Includes stable diffusion, whisper, llama7b and clip

To get this to work I had to Pass in hf auth token to all ci jobs, github does not pass in secrets from parent to child automatically. There's a likelihood HF will rate limit us in case please revert this PR and I'll work on adding a cache next - cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov @malfet 

Something upstream changed in torchbench too where now `hf_Bert` and `hf_Bert_large` are both failing on some dynamic shape looking error which I'm not sure how to debug yet so for now felt a bit gross but added a skip since others are building on top this work @ezyang 

`llamav2_7b_16h` cannot pass through accuracy checks cause it OOMs on deepcloning extra inputs this seems to make it not need to show up in expected numbers csv, will figure this when we update the pin with https://github.com/pytorch/benchmark/pull/1803 cc @H-Huang @xuzhao9 @cpuhrsch 

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
CI failures look related

**Comment by msaroufim** [comment]
TODO: 
* [ ] clip and whisper just need their requirements.txt updated
* [ ] llama v2 needs a hf auth token https://github.com/pytorch/pytorch/actions/runs/5664989636/job/15349967063?pr=106009#step:15:1803 - @malfet do you mind if I add my own as a github secret? I did so in torchbench CI
* [ ] stable diffusion and hf t5 breakages are not expected, some weird thing going on because of moving out from canary models

**Comment by malfet** [comment]
@msaroufim do you know if hf tokens are rate limited? If not, they sure, go ahead and do it

**Comment by msaroufim** [comment]
Reached out with my token offline, I can't add github secrets AFAIK to pytorch

**Comment by malfet** [comment]
@msaroufim feel free to ignore ASAN failures as they are unrelated to what you are trying to achieve here

**Comment by kit1980** [comment]
@msaroufim https://github.com/pytorch/pytorch/actions/runs/5753300329/job/15597676255 started to fails with 

Improvement: 3 models have accuracy status improved:
    clip hf_Whisper stable_diffusion
    
If it's expected, please follow the instructions in https://github.com/pytorch/pytorch/actions/runs/5753300329/job/15597676255

**Pull request closed without merging**
