### PR TITLE
[quant][embedding qat] Support Embedding QAT via FX API

### LINKED ISSUE #61865: [quant] Support QAT for Embedding/EmbeddingBag
Currently we only support PTQ for embedding modules https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/embedding_ops.py

This issue tracks the support to 
1. add QAT modules for Embedding/EmbeddingBag modules
2. Do the module swap in eager mode to use these modules
3. Update FX quantization flow to support the new modules

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

### PR DESCRIPTION
**Pull request by b-koopman**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #68121
* __->__ #68296
* #68852

Summary:

Support QAT workflow by using torch.fx QAT API.  e.g. `prepare_qat_fx` and `convert_fx`.

Test Plan:

`pytest test/quantization/fx/test_quantize_fx.py -v -k "test_qat_embedding_linear"`

Reviewers:
supriyar, HDCharles

Subscribers:

Tasks:

Tags:

Differential Revision: [D32404517](https://our.internmc.facebook.com/intern/diff/D32404517)

### CODE REVIEW

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32404517).

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32404517).

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32404517).

**Review by supriyar — APPROVED** [review]
So to clarify, for Embedding QAT we don't need a custom mapping for prepare_qat_fx but we need one for convert_fx?
cc @jerryzh168

**Comment by b-koopman** [comment]
> So to clarify, for Embedding QAT we don't need a custom mapping for prepare_qat_fx but we need one for convert_fx? cc @jerryzh168

Correct, this is implemented where nn.Embedding -> nn.qat.Embedding  is implemented via `quantization_patterns` for the prepare, and therefore does not need the custom mapping.
https://github.com/pytorch/pytorch/pull/68296/files#diff-5770045cde7e1d2451524b7232e5c1201e0f4624fc16e86758834d390a6074d1R1163

However for nn.qat.Embedding -> nn.quantized.Embedding, in convert_fx, this requires a custom static mapping right now, since embedding QAT is not included in the default mappings (as is also currently needed for the eager QAT case)

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32404517).

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32404517).

**Review by jingsh — APPROVED** [review]

**Comment by malfet** [comment]
This broke MacOS test sanity see https://github.com/pytorch/pytorch/runs/4398281864?check_suite_focus=true#step:8:31 , reverting

**Pull request closed without merging**
