### PR TITLE
support bool tensordot

### PR DESCRIPTION
**Pull request by guol-fnst**
Fixes #{issue number}
support bool tensordot

### CODE REVIEW

**Comment by albanD** [comment]
Hi,

Thanks for sending a PR! I would have a couple question:

Could you give a bit more context on why you want this feature? What it actually means to do a tensordot on boolean?

**Comment by guol-fnst** [comment]
> t

**Comment by guol-fnst** [comment]
> Hi,
> 
> Thanks for sending a PR! I would have a couple question:
> 
> Could you give a bit more context on why you want this feature? What it actually means to do a tensordot on boolean?
So if this feature is not needed, I will close this PR.

**Comment by albanD** [comment]
Ho I didn't meant that the feature is not needed, I was genuinely curious about it!

The code looks ok but the CI failures are relevant I think. Hence my question about BLAS support.
Also if you want to land this, we would need to add tests to make sure it works as expected.

Thanks for contributing!

**Pull request closed without merging**
