### PR TITLE
[quant][eagermode] Move custom_module registration to prepare/convert_custom_config_dict

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #46298 [quant][graphmode][fx] Support non_traceable_module/module_class
* **#46293 [quant][eagermode] Move custom_module registration to prepare/convert_custom_config_dict**
* #46292 [quant] Remove prehook option
* #46251 [quant][graphmode][fx] Move custom_module_class config to prepare/convert_custom_config_dict

Summary:

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D24290811](https://our.internmc.facebook.com/intern/diff/D24290811)

### CODE REVIEW

**Review by raghuramank100 — APPROVED** [review]

**Comment by mruberry** [comment]
Unlanding. This broke the docs build. Relevant snippet:

```
Oct 14 20:44:57 /opt/conda/lib/python3.6/site-packages/torch/quantization/quantize.py:docstring of torch.quantization.prepare:20: WARNING: Block quote ends without a blank line; unexpected unindent.
Oct 14 20:44:57 /opt/conda/lib/python3.6/site-packages/torch/quantization/quantize.py:docstring of torch.quantization.convert:16: WARNING: Unexpected indentation.
Oct 14 20:44:57 /opt/conda/lib/python3.6/site-packages/torch/quantization/quantize.py:docstring of torch.quantization.convert:17: WARNING: Block quote ends without a blank line; unexpected unindent.
```

**Comment by jerryzh168** [comment]
> Unlanding. This broke the docs build. Relevant snippet:
> 
> ```
> Oct 14 20:44:57 /opt/conda/lib/python3.6/site-packages/torch/quantization/quantize.py:docstring of torch.quantization.prepare:20: WARNING: Block quote ends without a blank line; unexpected unindent.
> Oct 14 20:44:57 /opt/conda/lib/python3.6/site-packages/torch/quantization/quantize.py:docstring of torch.quantization.convert:16: WARNING: Unexpected indentation.
> Oct 14 20:44:57 /opt/conda/lib/python3.6/site-packages/torch/quantization/quantize.py:docstring of torch.quantization.convert:17: WARNING: Block quote ends without a blank line; unexpected unindent.
> ```

oh, didn't notice that, I thought it was because of 
```
Oct 14 01:08:03 /opt/conda/lib/python3.6/site-packages/torch/jit/_recursive.py:195: UserWarning: 'mods' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
Oct 14 01:08:03   " but it is a non-constant {}. Consider removing it.".format(name, hint))
Oct 14 01:08:03 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
Oct 14 01:08:03 	%13 : Float(4, strides=[1], requires_grad=0, device=cpu) = aten::rand(%8, %9, %10, %11, %12) # <doctest default[0]>:2:0
Oct 14 01:08:03 This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
Oct 14 01:08:03   _module_class,
Oct 14 01:08:03 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Oct 14 01:08:03 With rtol=1e-05 and atol=1e-05, found 4 element(s) (out of 12) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.8969195485115051 (0.0034521818161010742 vs. 0.9003717303276062), which occurred at index (0, 2).
Oct 14 01:08:03   _module_class,
Oct 14 01:08:03 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
Oct 14 01:08:03 	%14 : Float(1, 4, strides=[4, 1], requires_grad=0, device=cpu) = aten::rand(%9, %10, %11, %12, %13) # <doctest default[0]>:2:0
Oct 14 01:08:03 This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
Oct 14 01:08:03   _module_class,
Oct 14 01:08:03 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Oct 14 01:08:03 With rtol=1e-05 and atol=1e-05, found 4 element(s) (out of 8) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.8881369233131409 (0.06778597831726074 vs. 0.9559229016304016), which occurred at index (0, 0).
Oct 14 01:08:03   _module_class,
```

can we make the error more explicit next time?

**Comment by mruberry** [comment]
> > Unlanding. This broke the docs build. Relevant snippet:
> > ```
> > Oct 14 20:44:57 /opt/conda/lib/python3.6/site-packages/torch/quantization/quantize.py:docstring of torch.quantization.prepare:20: WARNING: Block quote ends without a blank line; unexpected unindent.
> > Oct 14 20:44:57 /opt/conda/lib/python3.6/site-packages/torch/quantization/quantize.py:docstring of torch.quantization.convert:16: WARNING: Unexpected indentation.
> > Oct 14 20:44:57 /opt/conda/lib/python3.6/site-packages/torch/quantization/quantize.py:docstring of torch.quantization.convert:17: WARNING: Block quote ends without a blank line; unexpected unindent.
> > ```
> 
> oh, didn't notice that, I thought it was because of
> 
> ```
> Oct 14 01:08:03 /opt/conda/lib/python3.6/site-packages/torch/jit/_recursive.py:195: UserWarning: 'mods' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
> Oct 14 01:08:03   " but it is a non-constant {}. Consider removing it.".format(name, hint))
> Oct 14 01:08:03 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
> Oct 14 01:08:03 	%13 : Float(4, strides=[1], requires_grad=0, device=cpu) = aten::rand(%8, %9, %10, %11, %12) # <doctest default[0]>:2:0
> Oct 14 01:08:03 This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
> Oct 14 01:08:03   _module_class,
> Oct 14 01:08:03 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
> Oct 14 01:08:03 With rtol=1e-05 and atol=1e-05, found 4 element(s) (out of 12) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.8969195485115051 (0.0034521818161010742 vs. 0.9003717303276062), which occurred at index (0, 2).
> Oct 14 01:08:03   _module_class,
> Oct 14 01:08:03 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
> Oct 14 01:08:03 	%14 : Float(1, 4, strides=[4, 1], requires_grad=0, device=cpu) = aten::rand(%9, %10, %11, %12, %13) # <doctest default[0]>:2:0
> Oct 14 01:08:03 This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
> Oct 14 01:08:03   _module_class,
> Oct 14 01:08:03 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
> Oct 14 01:08:03 With rtol=1e-05 and atol=1e-05, found 4 element(s) (out of 8) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.8881369233131409 (0.06778597831726074 vs. 0.9559229016304016), which occurred at index (0, 0).
> Oct 14 01:08:03   _module_class,
> ```
> 
> can we make the error more explicit next time? why the quantization error does not appear in "Doctest summary"?

It IS confusing! @rgommers, let's consider improving this?

**Comment by rgommers** [comment]
What would you liked to have seen, something like?
```

NOTE: Sphinx warnings are turned into CI errors, this build is not clean?

```
right at the bottom of the `pytorch_python_doc_build` job, to make clear what is going on?

Current behaviour looks okay to me, but I realize that many devs aren't familiar with Sphinx and hence the build log may be hard to interpret. 

Cc @mattip

**Comment by mattip** [comment]
Maybe this could be part of the logic in DrCI ?

**Pull request closed without merging**
