### PR TITLE
Enable test_distributed for ROCm but only with nccl backend [REDUX]

### PR DESCRIPTION
**Pull request by jithunnair-amd**
This is a redux of the original PR #28814 which was reverted in PR #29736 due to test_DistributedDataParallel being suspected as being flaky. Further investigation revealed it wasn't flakiness, but a bug in the PyTorch source code which has been now fixed in PR #32356. This PR is another attempt at enabling the test_distributed unit test suite only for the nccl backend.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit e0d79fc7:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=e0d79fc7a159820a1939e76e7af03ace0eaedb32).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4327124) pytorch_macos_10_13_py3_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=90025223) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=90025223))
<details>
<summary>
<code>Jan 23 13:04:57 RuntimeError: test_autograd failed!</code>
</summary>

```
Jan 23 13:04:57 Ran 1046 tests in 285.339s 
Jan 23 13:04:57  
Jan 23 13:04:57 FAILED (errors=1, skipped=13, expected failures=1) 
Jan 23 13:04:57  
Jan 23 13:04:57 Generating XML reports... 
Jan 23 13:04:57 Traceback (most recent call last): 
Jan 23 13:04:57   File "test/run_test.py", line 455, in <module> 
Jan 23 13:04:57     main() 
Jan 23 13:04:57   File "test/run_test.py", line 448, in main 
Jan 23 13:04:57     raise RuntimeError(message) 
Jan 23 13:04:57 RuntimeError: test_autograd failed! 
Jan 23 13:04:57 + cleanup 
Jan 23 13:04:57 + retcode=1 
Jan 23 13:04:57 + set +x 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by jithunnair-amd** [comment]
CI Run 1: 2 failing checks: clang-tidy and pytorch_macos_10_13_py3_test. Neither failure seems to be related to the PR changes.

**Comment by bddppq** [comment]
Test is failing https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/18270
```
17:51:01 ======================================================================
17:51:01 ERROR: test_broadcast_coalesced_nccl (__main__.CommTest)
17:51:01 ----------------------------------------------------------------------
17:51:01 Traceback (most recent call last):
17:51:01   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 175, in wrapper
17:51:01     self._join_processes(fn)
17:51:01   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 256, in _join_processes
17:51:01     self._check_return_codes(elapsed_time)
17:51:01   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 275, in _check_return_codes
17:51:01     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
17:51:01 RuntimeError: Process 1 terminated or timed out after 156.1109459400177 seconds
```

**Comment by jithunnair-amd** [comment]
> Test is failing https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/18270
> 
> ```
> 17:51:01 ======================================================================
> 17:51:01 ERROR: test_broadcast_coalesced_nccl (__main__.CommTest)
> 17:51:01 ----------------------------------------------------------------------
> 17:51:01 Traceback (most recent call last):
> 17:51:01   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 175, in wrapper
> 17:51:01     self._join_processes(fn)
> 17:51:01   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 256, in _join_processes
> 17:51:01     self._check_return_codes(elapsed_time)
> 17:51:01   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 275, in _check_return_codes
> 17:51:01     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
> 17:51:01 RuntimeError: Process 1 terminated or timed out after 156.1109459400177 seconds
> ```

Yes, thank you for putting the details here. I'm running the tests locally to see if I can reproduce the failure.

**Comment by jithunnair-amd** [comment]
Successful CI Run 2: 2 failing checks: pytorch_linux_xenial_py3_6_gcc5_4_build and pytorch_macos_10_13_py3_test. Neither failure seems to be related to the PR changes.

Testing yet again for good measure.

@pytorchbot retest this please.

**Comment by jithunnair-amd** [comment]
Successful CI Run 3: 2 failing checks: pytorch_linux_xenial_py3_6_gcc5_4_build and pytorch_macos_10_13_py3_test. Neither failure seems to be related to the PR changes.

@bddppq Seems ready for review and merge

**Review by ezyang — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@ezyang I notice there are some trivial conflicts in test/run_test.py. Would you like me to resolve them here, or will they be resolved while importing into Phabricator?

**Comment by ezyang** [comment]
If you could resolve them that would be great, sorry about the delay

**Comment by bddppq** [comment]
Trigger more runs to test flakiness:

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/20120/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/20121/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/20122/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/20123/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/20124/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/20125/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/20126/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/20128/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/20129/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/20130/

**Comment by jithunnair-amd** [comment]
Nice, thanks!

**Comment by jithunnair-amd** [comment]
All 10 CI runs above passed.

**Review by bddppq — APPROVED** [review]
Thanks!

**Pull request closed without merging**
