### PR TITLE
Explicitly unset AVX/AVX2 env variables

### PR DESCRIPTION
**Pull request by cpuhrsch**

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
OK, I guess? Not sure why it makes a different.

**Comment by colesbury** [comment]
The no-avx build will disable AVX but not AVX2, which is a bit silly.

**Comment by yf225** [comment]
@colesbury The no-avx build has both `NO_AVX` and `NO_AVX2` in its job name which should do the right thing. It's mostly for making the settings more explicit.

**Comment by cpuhrsch** [comment]
@ezyang 
There's a difference

```
$ cat /tmp/getenv.cpp
#include <iostream>
#include <cstdlib>

int main()
{
    if(const char* env_p = std::getenv("ATEN_DISABLE_AVX2"))
        std::cout << "Your ATEN_DISABLE_AVX2 is: " << env_p << '\n';
}
$ export ATEN_DISABLE_AVX2=
$ g++ /tmp/getenv.cpp && ./a.out
Your ATEN_DISABLE_AVX2 is:
$ unset ATEN_DISABLE_AVX2
$ g++ /tmp/getenv.cpp && ./a.out
$
```

We check for the presence of this env variable and not it's value, so this is an important distinction.

**Comment by colesbury** [comment]
BTW, I'm changing the environment variable in https://github.com/pytorch/pytorch/pull/9579 to set the desired capability instead of selectively disabling them. So to use the generic kernels, it'll be:

`ATEN_CPU_CAPABILITY=default`

instead of

`ATEN_DISABLE_AVX=1 ATEN_DISABLE_AVX2=1`

**Comment by cpuhrsch** [comment]
@colesbury - do you want to include this into that PR? Then we can just close this.

**Comment by colesbury** [comment]
@cpuhrsch, good idea -- I'll do that

**Comment by colesbury** [comment]
@cpuhrsch @yf225 does the last commit in https://github.com/pytorch/pytorch/pull/9579 (https://github.com/pytorch/pytorch/pull/9579/commits/2e2752bc8aa0f7271754dd8b447731cf03870f79) look OK?

**Comment by cpuhrsch** [comment]
@colesbury - yes, but we probably want to change the test names a bit now. We can do that afterwards.

**Pull request closed without merging**
