### PR TITLE
[quant][core][gpu][bug fix] Changed at::contiguous call to at::to for quantized cudnn operators

### PR DESCRIPTION
**Pull request by dzdang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #75668
* __->__ #75559
* #75540
* #75711

Summary:
`at::contiguous` for conv 1x1 (kernel height == kernel width == 1)
produces the wrong strides (still preserves the NCHW format) for channels last format.
`at::to` produces the expected NHWC format. This was not an issue with cudnn v 8.3.3, but after
upgrading to v 8.4.0, we noticed this error.

We have changed `at::contiguous` callsites to `at::to` in `aten/src/ATen/native/quantized/cudnn`

Test plan:
```
python test/test_quantization.py -k test_qconv2d_cudnn
```

Differential Revision: [D35523180](https://our.internmc.facebook.com/intern/diff/D35523180)

### CODE REVIEW

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35523180).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35523180).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35523180).

**Review by jerryzh168 — APPROVED** [review]

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35523180).

**Pull request closed without merging**
