### PR TITLE
Skip frame if torch dispatch mode enabled

### LINKED ISSUE #105929: Dynamo silently ignores TorchDispatchMode
### 🐛 Describe the bug

This test fails:

```
diff --git a/test/dynamo/test_misc.py b/test/dynamo/test_misc.py
index 4ac6b803ddb..43083783cc3 100644
--- a/test/dynamo/test_misc.py
+++ b/test/dynamo/test_misc.py
@@ -38,6 +38,7 @@ from torch._dynamo.testing import (
     unsupported,
 )
 
+from torch.utils._python_dispatch import TorchDispatchMode
 from torch._dynamo.utils import CompileProfiler, ifdynstaticdefault
 from torch.ao.quantization import MinMaxObserver
 from torch.ao.quantization.fake_quantize import FakeQuantize
@@ -6040,6 +6041,22 @@ def ___make_guard_fn():
         self.assertEqual(counter.frame_count, 1)
         self.assertEqual(counter.op_count, 3)
 
+    def test_mode_guard(self):
+        class RewriteAddToMul(TorchDispatchMode):
+            def __torch_dispatch__(self, func, types, args=(), kwargs=None):
+                if func is torch.ops.aten.add.Tensor:
+                    func = torch.ops.aten.mul.Tensor
+                return func(*args, **kwargs)
+
+        def fn(x):
+            return x + x
+
+        x = torch.tensor([3.0])
+        with RewriteAddToMul():
+            r = fn(x)
+            opt_r = torch.compile(fn)(x)
+        self.assertEqual(r, opt_r)
+
     def test_tracing_nested_py_tree(self):
         import torch.utils._pytree as pytree
 
```

Note that if you don't make torch.compile unconditionally bail out and have it handle torch dispatch mode, you need to add appropriate guards; this test doesn't exercise that the guards are correct.

### Versions

main

cc @gchanan @zou3519 @kadeng @Chillee @albanD @samdow @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @wconstab @aakhundov @Xia-Weiwen @ipiszy

### PR DESCRIPTION
**Pull request by mlazos**
Fixes https://github.com/pytorch/pytorch/issues/105929

We now skip frames if a dispatch mode is enabled.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]

**Review by anijain2305 — APPROVED** [review]

**Comment by mlazos** [comment]
waiting on https://github.com/pytorch/pytorch/issues/132165 to land

**Pull request closed without merging**
