### PR TITLE
[docs] Add images to some activation functions

### LINKED ISSUE #65368: [docs] Some activation functions are missing images
## 📚 Documentation

In #5457, images were introduced in the pages of each activation functions. Now, there are a few of them that are missing their images:
- [`RReLU`](https://pytorch.org/docs/master/generated/torch.nn.RReLU.html)
- [`Hardsigmoid`](https://pytorch.org/docs/master/generated/torch.nn.Hardsigmoid.html)
- [`Hardswish`](https://pytorch.org/docs/master/generated/torch.nn.Hardswish.html)
- [`SiLU`](https://pytorch.org/docs/master/generated/torch.nn.SiLU.html)
- [`Mish`](https://pytorch.org/docs/master/generated/torch.nn.Mish.html)

Three of them are already in the [`build_activation_images.py`](https://github.com/pytorch/pytorch/blob/master/docs/source/scripts/build_activation_images.py). So, the fix is really simple: add the other two to the script and fix the docstrings of all these 5 functions.

If this is of interest, I could send this PR: https://github.com/rodrigoberriel/pytorch/commit/aee963c990a26aa14646c22de11d6921ecea22ea

Lastly, I didn't change it, but I guess we could remove the line below, because of [this discussion](https://github.com/pytorch/pytorch/pull/5457#discussion_r171445192) in #5457. If so, I can update when sending the PR.

https://github.com/pytorch/pytorch/blob/2abf3594d519340c8368a24e7407c69b7b52bc60/docs/source/scripts/build_activation_images.py#L49

I didn't open the PR directly because I guess this is the correct workflow. Please, let me know if I need to open an issue for this kind of straightforward doc change.

cc @brianjo @mruberry @albanD @jbschlosser @walterddr @SsnL

### PR DESCRIPTION
**Pull request by rodrigoberriel**
Fixes #65368. See discussion in the issue.

cc @mruberry @SsnL @jbschlosser @soulitzer

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
I think you forgot to add the images to the commit?

**Comment by rodrigoberriel** [comment]
> I think you forgot to add the images to the commit?

AFAIK, they are generated on-the-fly:

https://github.com/pytorch/pytorch/blob/00b732e98b030a774c76f0c40b9e70ac6b12bfc6/docs/Makefile#L16-L17

**Comment by albanD** [comment]
Ho interesting, I didn't knew we had such a script :p 
The rendered doc looks good: https://docs-preview.pytorch.org/65415/generated/torch.nn.SiLU.html?highlight=silu#torch.nn.SiLU

**Review by albanD — APPROVED** [review]
LGTM thanks!

**Review by soulitzer — APPROVED** [review]

**Review by jbschlosser — APPROVED** [review]

**Pull request closed without merging**
