### PR TITLE
Fix AdaptiveLogSoftmaxWithLoss's constructor

### PR DESCRIPTION
**Pull request by wbydo**
@t-ken1 and I are members of a same team.
I have added test codes about the pull request https://github.com/pytorch/pytorch/pull/16656.

### CODE REVIEW

**Review by ssnl — COMMENTED** [review]
Looks great, but let's not use `subTest`. It doesn't seem available in Py2.

**Comment by wbydo** [comment]
sorry. fixed

**Comment by ezyang** [comment]
Hey @wbydo, could you please merge your branch with master to retrigger on the newest master commit? That should resolve your CI errors. (I would do this for you, but you didn't give permission to repo maintainers to push to your branch.)

**Comment by wbydo** [comment]
Thanks for advice @ezyang.
I tried to merge the newest commit on master branch but CI error have still occurred.

Please tell me which commit I should merge to.

**Comment by ezyang** [comment]
Sorry, master was broken for some time today. Could you try merging again? X(

**Pull request closed without merging**
