### PR TITLE
Turn on -Wsign-compare in aten folder only

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #95214

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by ezyang** [comment]
It's not clear to me that this did anything

**Comment by Skylion007** [comment]
Ping @cyyever since he just enabled a bunch of warnings.

**Comment by cyyever** [comment]
You can consider turn on it on the main CMakeList.txt and add necessary static_cast for new warnings emerged.

**Comment by malfet** [comment]
I guess it's pretty stale: we should have sign compare enabled in In the entire repo by default.

**Pull request closed without merging**
