### PR TITLE
Add dist_pp shortcut to TORCH_LOGS

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #126499
* __->__ #126322

distributed log category already includes pipelining since its under the
torch.distributed umbrella.

So both TORCH_LOGS=distributed and TORCH_LOGS=dist_pp will enable PP
logs.

### CODE REVIEW

**Comment by kwen2501** [comment]
LGTM.
nit: I don't like the `dist_` prefix, see other torch components. 
Perhaps we should just have "c10d", "ddp", "fsdp", etc

**Review by kwen2501 — APPROVED** [review]

**Comment by wconstab** [comment]
yea... some folks had a discussion about this a while back, the reason for leaving dist_ prefix iirc was so that the -help menu shows all the distributed categories together in one grouping and lets people more easily discover them.

i think we could remove it though. maybe its not really that useful to sort the help menu.

**Pull request closed without merging**
