### PR TITLE
Eliminate unnecessary std::any() in a depth first search of the autograd graph

### LINKED ISSUE #34067: Optimize autograd engine init_to_execute() performance
## 🚀 Feature

`GraphTask::init_to_execute()` uses manually unrolled version of depth first search to traverse the autograd graph. The purpose is to determine whether each node/function needs to be computed (calling `apply()`). A node needs to be computed, iff any of its child nodes needs to be computed.

The method uses an unnecessary `any()` to check each out edges of a node when all edges are visited. Instead, `needed_` of a node can be updated incremental when the following 2 cases happen

1. Its next edge points to an already visited node, **A**. **A** can't be in the stack at the moment, because the graph is a DAG. Therefore, `needed_` of **A** must have finalized. Just update the node's `needed_` according to **A**'s.
2. The node, **B**, pointed by its next edge just gets popped out of the stack. Then `needed_` of **B** must have been finalized. Just update the node's `needed_` according to **B**'s.

https://github.com/pytorch/pytorch/blob/ad17dafc50d5164dda98fa5fd14149e1982fb89b/torch/csrc/autograd/engine.cpp#L975-L1023

We can further make a generic template function/class to support such use cases, traversing and doing per node aggregation on the autograd graph. There are other places with the same pattern.

## Motivation

Reduce the time complexity of a function and potentially improve the performance.

## Additional context

@zhaojuanmao @pritamdamania87 @mrshenli 

cc @ezyang @SsnL @albanD @zou3519 @gqchen

### PR DESCRIPTION
**Pull request by hczhu**
This is an optimization and doesn't change any logic. All existing tests should cover it.

### CODE REVIEW

**Comment by ezyang** [comment]
Do you have benchmarks showing perf change?

**Comment by ezyang** [comment]
@albanD I'm going to let you do review on this one, let me know if you need my assistance.

**Comment by hczhu** [comment]
> Do you have benchmarks showing perf change?

I don't. Any existing benchmark I can run quickly?

**Comment by albanD** [comment]
You can try to check the runtime for the backward pass of a network with small inputs. But not sure you're gonna see any significant improvement.
What is the motivation for this change? Is std::any supposed to be particularly inefficient?

Also I am not sure about the performance implication of the new `while` loop. It might make you traverse the same subgraph multiple times if you have:
A -> B -> C -> D -> E -> F
G -> |

Exploration for G here will go all the way to F again.

**Comment by hczhu** [comment]
> What is the motivation for this change? Is std::any supposed to be particularly inefficient?

I happened to see this piece of code. `std::any()` traverses the edge list again and is not necessary actually. Therefore, I made this PR.

> 
> Also I am not sure about the performance implication of the new `while` loop. It might make you traverse the same subgraph multiple times if you have:
> A -> B -> C -> D -> E -> F
> G -> |
> 
> Exploration for G here will go all the way to F again.

I don't quite follow. The new while loop just handles one of the 3 cases, which is handled in `else {` of the current implementation. In the example, `G -> I` is disconnected with `F`. I'm not sure why exploring `G` can go to `F`.

Anyway, @albanD suggested in another PR to deprecate `exec_info_`. We don't need this depth first search if that's the case.

https://github.com/pytorch/pytorch/pull/34501#discussion_r389966131

**Comment by albanD** [comment]
I suggest to remove it from the distributed engine, not from the original engine !!!

Sorry my graph is not good, but G points to B.
So when doing the search on A, you go through the whole graph but G.
When exploring G with your algo, this while will go through the whole graph again.

**Comment by hczhu** [comment]
> Sorry my graph does not look good, but G points to B.
> So when doing the search on A, you go through the whole graph but G.
> When exploring G with your algo, this while loop will go through the whole graph again.

No, `B` will be already in `seen` map and the `while` loop will reach the end of `G`'s edge list.

```CPP
while ((child_fn = frame.get_next_fn()) &&
             /* bool seen = */ !seen.emplace(child_fn).second) {
```

**Comment by albanD** [comment]
That sounds good.
I would still like a small benchmark to see the impact of this change.
Especially because the number of next edges is always fairly small (1-3).

**Comment by soulitzer** [comment]
Closing because these exact changes have been adopted and merged in a different PR. Thanks @hczhu for the find and implementation.

**Pull request closed without merging**
