### PR TITLE
[FSDP] Add back `forward_prefetch`

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #85177
* #85176

- This implements explicit forward prefetching following the static 1st iteration's pre-forward order when `forward_prefetch=True` in the FSDP constructor.
- This has the same unit test coverage as the original `forward_prefetch`.
- I checked via print statements that the prefetches are happening, but since I cannot get a good CPU bound workload, it is hard to tell via traces that the prefetch is working.

### CODE REVIEW

**Review by zhaojuanmao — APPROVED** [review]

**Review by zhaojuanmao — APPROVED** [review]

**Comment by awgu** [comment]
@pytorch rebase -s

**Pull request closed without merging**
