### PR TITLE
Clang-format: whitelist test/cpp/tensorexpr/*.

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#36616 Clang-format: whitelist test/cpp/tensorexpr/*.**
* #36615 [TensorExpr] Clang-format test/cpp/tensorexpr/*.

Differential Revision: [D21027732](https://our.internmc.facebook.com/intern/diff/D21027732)

### CODE REVIEW

**Comment by SplitInfinity** [comment]
What is the new execution time?

**Comment by ZolotukhinM** [comment]
> What is the new execution time?

No noticeable changes: this test folder is not big, it's from a quite young codebase.

**Comment by SplitInfinity** [comment]
Just for posterity, can you include the output?

**Comment by ZolotukhinM** [comment]
With the change:
```
> time tools/clang_format.py
Using clang-format located at /home/mvz/pytorch/.clang-format-bin/clang-format

real    0m1.966s
user    0m8.971s
sys     0m2.056s
```
Without the change:
```
> time tools/clang_format.py
Using clang-format located at /home/mvz/pytorch/.clang-format-bin/clang-format

real    0m2.130s
user    0m8.274s
sys     0m1.768s
```
(not claiming a performance improvement :-D - it's just a noise)

**Comment by ZolotukhinM** [comment]
What's probably more important is the following stats:
```
> wc -l test/cpp/tensorexpr/*
  ...
  7546 total
> wc -l test/cpp/jit/*
  ...
  8279 total
> wc -l torch/csrc/jit/*/*
  ...
  101520 total
```

**Review by SplitInfinity — APPROVED** [review]
Seems legit

**Pull request closed without merging**
