### PR TITLE
[dynamo][ac] Remove disable monkeypatching of utils.checkpoint

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104397
* #104317
* #104276

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78

### CODE REVIEW

**Review by wconstab — APPROVED** [review]
this lgtm.  the test case you added only covers the graph-break case. do you have an existing test that covers the successful compile case?

**Comment by anijain2305** [comment]
> the test case you added only covers the graph-break case. do you have an existing test that covers the successful compile case?

Yes, all the existing tests cover the successful compile cases.

**Pull request closed without merging**
