### PR TITLE
Reland #50999 (Added pow() on CPU for float16 & bfloat16)

### PR DESCRIPTION
**Pull request by imaginary-person**
#### Reason for relanding
Line 1607 of `torch/testing/_internal/common_methods_invocations.py` of #50999  had `dtype` instead of `dtype=torch.bool`, so 4 of the 9 sample inputs for `bool` had incorrect dtype. This bug was caught by #54949.

### Summary
1. Added support for pow() on CPU for `float16` (`Half`) and `bfloat16` types.
Both `pow(Tensor, Scalar)` and `pow(Tensor, Tensor)` are now supported for the aforementioned types.
However autograd isn't supported for `Float16` on CPU yet, as `log_vml_cpu` can't be enabled for it.
2. @heitorschueroff added `pow_tensor_scalar_optimized_kernel` to refactor & simplify `PowKernel.cpp`.
It provides a common path for all the complex types & floating point types (except Float16, due to lack of complete AVX2 vectorization support for it).  It replaced code that had previously been duplicated for (float, double) and complex types,
so PowKernel.cpp looks a lot cleaner now.
3. Enabled (unskipped) some tests for `erf`, `erfc`,`erfinv`, `tan` and `linalg.vector.norm` which were being skipped earlier due to `pow()` not having been implemented for `float16` & `bfloat16`.
4. Added an OpInfo for `pow()` & enabled some test cases for `pow()`.
5. Extended the coverage of existing tests for `pow` in `test_binary_ufuncs.py` in order to enable comparison with `numpy`, even with discontiguous tensors, and added a test to ensure that a runtime error is raised for `pow`'s inplace variant if resizing the base tensor is required during its invocation.
6. Added `float16` & `bfloat16` to `square`'s dtype lists in its `UnaryUfuncInfo`.
7. Removed redundant `dtypesIfCPU` and `dtypesIfCUDA` from `OpInfo`s where they are equal to `dtypes`.

### CODE REVIEW

**Comment by imaginary-person** [comment]
All the CI failures are unrelated, as these checks were [also failing even after the original PR was reverted](https://github.com/pytorch/pytorch/commit/8377e6221a094bf8d470e8e64ea4a2c4641694ab). So I'll request review after they'd be fixed.

**Comment by heitorschueroff** [comment]
@imaginary-person Could you rebase this to get clean signals on the fixed upstream failure.

**Comment by imaginary-person** [comment]
Hello @heitorschueroff, I'll do that asap. Sorry for the inconvenience!

**Comment by imaginary-person** [comment]
Hello @heitorschueroff, the 3 failed CI checks are related to docs. These were fixed upstream earlier today.

All other CI checks passed.
Thank you!

**Review by heitorschueroff — APPROVED** [review]
LGTM, landing now.

**Comment by imaginary-person** [comment]
Hello @heitorschueroff, a recently landed PR has introduced a conflict related to `test_out`, that wasn't present earlier. Please let me know if I should resolve it after the FB internal tests would complete, or now. I suspect that the FB internal tests might end if I add another commit to this PR, so I'm currently hesitant to do so. Thanks!

**Comment by imaginary-person** [comment]
I'll change the sample inputs for `pow` in a separate PR.

**Comment by imaginary-person** [comment]
Hello @heitorschueroff, can you please check if the internal FB tests still ongoing for this PR?
While they do seem to be ongoing on GitHub, I've noticed that sometimes GitHub loses updates for FB internal tests & shows them as being run even after 60+ days!

BTW, the ROCm issue is said to be fixed on ROCm 4.1. Maybe I can enable it via some other PR when ROCm builds would be succeeding.

**Comment by imaginary-person** [comment]
Hello @heitorschueroff, please let me know if any further changes are required on this PR. Thanks!

**Comment by imaginary-person** [comment]
Is there any way to enable/disable a test for a particular ROCm version?

**Review by heitorschueroff — APPROVED** [review]
LGTM

**Pull request closed without merging**
