### PR TITLE
Don't detach to create parameters in MetaConverter

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #99621
* __->__ #99618

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Comment by ezyang** [comment]
Unfortunately while this passes tests it doesn't seem to fix the underlying bug I was working on >:(

**Review by albanD — APPROVED** [review]
Nice

**Comment by ezyang** [comment]
This seems to fix a problem Voz is having, so we'll go ahead and merge it for now

**Comment by salilsdesai** [comment]
Hi @ezyang, this PR is causing an internal test failure for us. Can you please take a look at my comment on the diff?

**Pull request closed without merging**
