### PR TITLE
[structural binding][2/N] Replace std::tie with structural binding 

### PR DESCRIPTION
**Pull request by cyyever**
This PR follows #119774, Python generated code was changed to use structural binding.

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @EikanWang

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Very cool simplification!

I guess that the top PR in this series will add a lint to forbid the use of std::tie?

**Comment by cyyever** [comment]
@albanD No lint existing for such a rule...

**Pull request closed without merging**
