### PR TITLE
Reapply black for torchgen, this time with lint to fix!

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #76359

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by suo — APPROVED** [review]
<3

**Comment by suo** [comment]
Did you run it on everything? https://github.com/pytorch/pytorch/runs/6168590523?check_suite_focus=true shows an error for torchgen/api/lazy.py?

**Comment by ezyang** [comment]
it's a merge race. rebased

**Comment by suo** [comment]
@pytorch force merge this please

**Comment by suo** [comment]
looks like lint passed, so force merging: https://github.com/pytorch/pytorch/actions/runs/2224176416

**Pull request closed without merging**
