### PR TITLE
Globally enable Python dispatcher for all of Inductor compilation

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137621

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by ezyang** [comment]
this is ready

**Review by eellison — COMMENTED** [review]
There are a bunch of failures when I enable py dispatch in fake tensor mode lol https://github.com/pytorch/pytorch/pull/138953

**Review by eellison — APPROVED** [review]

**Pull request closed without merging**
