### PR TITLE
Skip nonzero unbacked SymInt memo in inference mode

### PR DESCRIPTION
**Pull request by aakhundov**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #122147

Summary: In `torch.inference_mode()`, fake tensors don't have `_version`s. This breaks unbacked SymInt memoization in `torch.nonzero` tracing. Here we disable the latter in inference mode.

Fixes https://github.com/pytorch/pytorch/issues/122127

Test Plan:

```
$ python test/inductor/test_unbacked_symints.py -k test_nonzero_in_inference_mode
...
----------------------------------------------------------------------
Ran 2 tests in 14.060s

OK
```

Reviewers:

Subscribers:

Tasks:

Tags:

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by aakhundov** [comment]
@jeanschmidt seems that reverting this PR didn't help the trunk errors? Should I rebase and merge this PR?

**Comment by aakhundov** [comment]
@jeanschmidt I've rebased this PR onto main. The CI (including `ciflow/rocm`) is green. I'll go ahead and merge the PR again.

**Pull request closed without merging**
