### PR TITLE
Fix python3.6 build in caffe2 CI

### PR DESCRIPTION
**Pull request by bddppq**

### CODE REVIEW

**Comment by bddppq** [comment]
@onnxbot retest this please

**Comment by bddppq** [comment]
wait for this https://github.com/onnx/onnx/pull/974

**Review by pjh5 — APPROVED** [review]

**Comment by pjh5** [comment]
I don't think this is important to this diff, but jsyk there's a little hack in build_anaconda.sh https://github.com/pytorch/pytorch/blob/master/scripts/build_anaconda.sh#L216

**Pull request merged**
