### PR TITLE
Fix printing of unknown binop operator in torchscript

### PR DESCRIPTION
**Pull request by zou3519**
Related to #6049 but not a fix for it.

Before, using an unknown binary operator like `@`:
```
import torch
@torch.jit.script
def mm(x, y):
    return x @ y

x = torch.randn(4, 3)
y = torch.randn(3, 2)
mm(x, y)
```
resulted in [this not-so-readable trace](https://gist.github.com/zou3519/052b8998108c4bc0fe0e7c85c6f5758e).

Now, it tells the user that the problem is an unknown binary operator:
```
NotSupportedError: unsupported binary operator: MatMult
@torch.jit.script
def mm(x, y):
    return x @ y
            ~~~ <--- HERE
```
cc @apaszke @zdevito

### CODE REVIEW

**Comment by apaszke** [comment]
Can we add a test for this error message?

**Review by apaszke — APPROVED** [review]

**Comment by ezyang** [comment]
@apaszke We get a lot of utility in GHC from using expect tests for error messages, since it makes it easier to tell when error messages get worse. I think that would be a good call here as well.

**Comment by apaszke** [comment]
@ezyang I agree and have been thinking of doing the same in the JIT. That's why I asked for a test in this PR!

**Comment by ezyang** [comment]
@apaszke OK, I'll leave it to you to expect-ify them :)

**Comment by apaszke** [comment]
Oh I wasn't planning to work on it, just to start progressively requesting more of them in next PRs. If you want to add some of them to get us started, then that would be great! We could make a separate `TestCase` for them (`TestScriptErrors`?)

**Pull request merged**
