### PR TITLE
[nn-module] Use standard dict for _parameters, _modules and _buffers

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #129164
* #129163

TorchDynamo guard mechanism guards on the key order on the dictionaries if the user iterates over the dictionary. For standard dict, we can write a fast C++ implementation by using PyDict_Next. But with OrderedDict, we have to rely on `keys` Python API to get the key ordering. This makes guard evaluation slow.

With Dynamo inlining into inbuilt nn modules, I am seeing many guards over the OrderedDict on `_modules`, `_parameters`. From reading the code, I don't see any reason to not use standard dicts. I think OrderedDict was preferred over dict because of the ordering, but dicts are now ordered. With this PR, I am observing ~20% reduction in guard overhead of a HF model.

Functionality impact
- The only difference between dict and OrdedeDict is `move_to_end` method for OrderedDict ([link](https://stackoverflow.com/questions/34305003/difference-between-dictionary-and-ordereddict)). But the changes here are internal to nn module, and we do not use `move_to_end` for `_parameters`, `_modules` and `_buffers`. We  use `move_to_end` for hooks but this PR keeps the OrderedDict for hooks untouched (we should still followup with hooks but in a separate PR).

Perf impact 
- I dont anticipate any perf impact. `dict` is completely implemented in C. OrderedDict is Python wrapper over dict with only few method overridden ([link](https://stackoverflow.com/questions/34305003/difference-between-dictionary-and-ordereddict)). 

Typing impact
- I dont anticipate any. For all the user visible methods for nn.Module, we don't expose the underlying `_modules` etc. We have iterators like `named_parameters` which return an Iterator of Parameter. So, no typing changes required.

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Why do we need this change?
Any perf or typing impact?

**Comment by anijain2305** [comment]
@albanD I modified the description to answer the questions to best of my knowledge.

**Comment by anijain2305** [comment]
@albanD A gentle ping. Let me know if you have some experiments in mind to check perf impact. Or any other suggestions to move on this PR.

**Review by mikaylagawarecki — APPROVED** [review]
From discussion with @albanD, we are probably ok with this one

The only slight concern might be BC for an nn.Module that was `torch.save`-ed, but I think that should not be an issue

**Comment by anijain2305** [comment]
@pytorcbot merge

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but it seems to break some internal dper3 tests' -c ghfirst

From the imported diff D59091876, the error is `AttributeError: 'dict' object has no attribute '_python_modules'`, so I guess they expect `OrderedDict` somehow?

**Comment by anijain2305** [comment]
It was a silly impl in internal - fixed in https://www.internalfb.com/diff/D59166026

**Pull request closed without merging**
