### PR TITLE
use $(MAKE) instead of make -j in CMake Exterproject

### LINKED ISSUE #70091: ci: sev:  use $(MAKE) instead of make -j in CMake Exterproject
> NOTE: Remember to label this issue with "`ci: sev`"

## Current Status
*Status could be: preemptive, ongoing, mitigated, closed. Also tell people if they need to take action to fix it (i.e. rebase)*.
image

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*
if MAX_JOBS is not defined, the project maybe run like make -j with full resource of the build env. sometimes, it will broke the build procedure.

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

## User impact
*How does this affect users of PyTorch CI?*
None

## Root cause
*What was the root cause of this issue?*
the external project didn't use the Concurrency mechanism of make。

## Mitigation
*How did we mitigate the issue?*
I will send a PR for this issue.

## Prevention/followups
*How do we prevent issues like this in the future?*
use $(MAKE) instead of make -j in CMake Exterproject

cc @malfet @seemethere

### PR DESCRIPTION
**Pull request by mlh0101**
fix the issue:
 ci: sev: use $(MAKE) instead of make -j in CMake Exterproject #70091

Fixes #70091

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
Replacing `make` with `$(MAKE)` makes sense, but can you explain why are you deleting -j option?

**Comment by mlh0101** [comment]
> Replacing `make` with `$(MAKE)` makes sense, but can you explain why are you deleting -j option?

It's the mechanism of make. When you use cmake .. && make -j NUM to build the whole project, $(MAKE) will automatically use a num smaller or equal than NUM.

**Comment by mlh0101** [comment]
@malfet 
Can this PR be merged? The failed check job has nothing to do with this modification, I think.

**Review by malfet — CHANGES_REQUESTED** [review]
I see the problem, but I think propose solution is wrong.
`-j` with no argument will indeed trigger unlimited parallelism, but removing `-j` will force the build to always be sequential if `ninja` is used is build command.

Also, I can't find it anywhere in CMake documentaiton reference to where `$(MAKE)` command is defined. Can you please share the reference to the doc?

**Comment by mlh0101** [comment]
> I see the problem, but I think propose solution is wrong. `-j` with no argument will indeed trigger unlimited parallelism, but removing `-j` will force the build to always be sequential if `ninja` is used is build command.
> 
> Also, I can't find it anywhere in CMake documentaiton reference to where `$(MAKE)` command is defined. Can you please share the reference to the doc?

You can get the reference from Make Manul help: 
[https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html](https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html)
image

**Comment by mlh0101** [comment]
@malfet 
anything else？

**Comment by mlh0101** [comment]
@malfet All checks have passed. Can this PR be merged?

**Pull request closed without merging**
