### PR TITLE
[jit] alias analysis refactor take 2

### PR DESCRIPTION
**Pull request by suo**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#17594 [jit] alias analysis refactor take 2**&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D14266663/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #17528 [jit] usertype -> class&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D14236943/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #17585 [jit] initializing class value&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D14263403/)

The original version of this broke things because a concurrent change raced with it in CI.

Differential Revision: [D14266663](https://our.internmc.facebook.com/intern/diff/D14266663/)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
rubber stamped

**Comment by t-vi** [comment]
So this commit seems to introduce a performance regression in the JIT RNN benchmarks for the backward pass. Before this commit the jit-premul and the jit versions were on par for @apaszke and ~7% apart on my machine. After, this commit, it is jit 23% slower than jit-premul on my computer, so the net effect for me is ~15%.
I haven't really looked into the causes yet, maybe something impedes the batch MM pass to sprinkle its magic.

**Comment by t-vi** [comment]
What happens is that the various occurences of `something = whh.t()`/`wih.t()` are not identified as the same.

**Comment by suo** [comment]
Ah, thanks for the catch!

> What happens is that the various occurences of something = whh.t()/wih.t() are not identified as the same.

Could you expand on this? Not sure what you mean

**Comment by apaszke** [comment]
@suo my guess is that @t-vi mentions the body of an unrolled loop, where we would have previously deduplicated calls to transpose the weights (and do it once every 8 iters) but now we keep those unnecessary transposes.

**Comment by t-vi** [comment]
I'm looking at the following graph: the various `aten::t(%wih)` and `aten::t(%whh)` used to be deduplicated:
```
graph(%input : Float(*, *, *),
      %hidden : (Float(*, *, *), Float(*, *, *)),
      %wih : Float(*, *),
      %whh : Float(*, *),
      %bih : Float(*),
      %bhh : Float(*)):
  %57 : Tensor[] = prim::Constant[value=[<Tensors>]]()
  %9 : int = prim::Constant[value=0]()
  %8 : bool = prim::Constant[value=1]()
  %6 : int = prim::Constant[value=1]()
  %hx.1 : Float(*, *, *), %cx.1 : Float(*, *, *) = prim::TupleUnpack(%hidden)
  %inputs : Tensor[] = aten::unbind(%input, %9)
  %hy.1 : Float(*, *) = aten::select(%hx.1, %9, %9)
  %cy.1 : Float(*, *) = aten::select(%cx.1, %9, %9)
  %16 : int = aten::len(%inputs)
  %272 : int = prim::Constant[value=8]()
  %273 : int = aten::__round_to_zero_floordiv(%16, %272)
  %280 : int = aten::mul(%273, %272)
  %281 : int = aten::sub(%16, %280)
  %59 : int, %cy.3 : Float(*, *), %hy.3 : Float(*, *), %outputs.1 : Tensor[] = prim::Loop(%273, %8, %9, %cy.1, %hy.1, %57)
    block0(%seq_idx.1 : int, %60 : int, %21 : Float(*, *), %22 : Float(*, *), %23 : Tensor[]):
      %24 : Tensor = aten::select(%inputs, %60)
      %25 : Float(*, *) = aten::t(%wih)
      %26 : Float(*, *) = aten::mm(%24, %25)
      %27 : Float(*, *) = aten::t(%whh)
      %28 : Float(*, *) = aten::mm(%22, %27)
      %29 : Float(*, *) = aten::add(%26, %28, %6)
      %30 : Float(*, *) = aten::add(%29, %bih, %6)
      %gates.9 : Float(*, *) = aten::add(%30, %bhh, %6)
      %53 : Float(*, *), %54 : Float(*, *), %55 : Float(*, *), %56 : Float(*, *) = prim::ConstantChunk[chunks=4, dim=1](%gates.9)
      %ingate.9 : Float(*, *) = aten::sigmoid(%53)
      %forgetgate.9 : Float(*, *) = aten::sigmoid(%54)
      %cellgate.9 : Float(*, *) = aten::tanh(%55)
      %outgate.9 : Float(*, *) = aten::sigmoid(%56)
      %41 : Float(*, *) = aten::mul(%forgetgate.9, %21)
      %42 : Float(*, *) = aten::mul(%ingate.9, %cellgate.9)
      %cy.12 : Float(*, *) = aten::add(%41, %42, %6)
      %44 : Float(*, *) = aten::tanh(%cy.12)
      %hy.12 : Float(*, *) = aten::mul(%outgate.9, %44)
      %46 : Tensor[] = prim::ListConstruct(%hy.12)
      %outputs.11 : Tensor[] = aten::add(%23, %46)
      %61 : int = prim::Constant[value=1]()
      %62 : int = aten::add(%60, %61)
      %97 : Tensor = aten::select(%inputs, %62)
      %98 : Float(*, *) = aten::t(%wih)
      %99 : Float(*, *) = aten::mm(%97, %98)
      %100 : Float(*, *) = aten::t(%whh)
      %101 : Float(*, *) = aten::mm(%hy.12, %100)
      %102 : Float(*, *) = aten::add(%99, %101, %6)
      %103 : Float(*, *) = aten::add(%102, %bih, %6)
      %gates.2 : Float(*, *) = aten::add(%103, %bhh, %6)
      %105 : Float(*, *), %106 : Float(*, *), %107 : Float(*, *), %108 : Float(*, *) = prim::ConstantChunk[chunks=4, dim=1](%gates.2)
      %ingate.2 : Float(*, *) = aten::sigmoid(%105)
      %forgetgate.2 : Float(*, *) = aten::sigmoid(%106)
      %cellgate.2 : Float(*, *) = aten::tanh(%107)
      %outgate.2 : Float(*, *) = aten::sigmoid(%108)
      %113 : Float(*, *) = aten::mul(%forgetgate.2, %cy.12)
      %114 : Float(*, *) = aten::mul(%ingate.2, %cellgate.2)
      %cy.5 : Float(*, *) = aten::add(%113, %114, %6)
      %116 : Float(*, *) = aten::tanh(%cy.5)
      %hy.5 : Float(*, *) = aten::mul(%outgate.2, %116)
      %118 : Tensor[] = prim::ListConstruct(%hy.5)
      %outputs.4 : Tensor[] = aten::add(%outputs.11, %118)
      %120 : int = prim::Constant[value=1]()
      %121 : int = aten::add(%62, %120)
      %122 : Tensor = aten::select(%inputs, %121)
      %123 : Float(*, *) = aten::t(%wih)
      %124 : Float(*, *) = aten::mm(%122, %123)
      %125 : Float(*, *) = aten::t(%whh)
      %126 : Float(*, *) = aten::mm(%hy.5, %125)
      %127 : Float(*, *) = aten::add(%124, %126, %6)
      %128 : Float(*, *) = aten::add(%127, %bih, %6)
      %gates.3 : Float(*, *) = aten::add(%128, %bhh, %6)
      %130 : Float(*, *), %131 : Float(*, *), %132 : Float(*, *), %133 : Float(*, *) = prim::ConstantChunk[chunks=4, dim=1](%gates.3)
      %ingate.3 : Float(*, *) = aten::sigmoid(%130)
      %forgetgate.3 : Float(*, *) = aten::sigmoid(%131)
      %cellgate.3 : Float(*, *) = aten::tanh(%132)
      %outgate.3 : Float(*, *) = aten::sigmoid(%133)
      %138 : Float(*, *) = aten::mul(%forgetgate.3, %cy.5)
      %139 : Float(*, *) = aten::mul(%ingate.3, %cellgate.3)
      %cy.6 : Float(*, *) = aten::add(%138, %139, %6)
      %141 : Float(*, *) = aten::tanh(%cy.6)
      %hy.6 : Float(*, *) = aten::mul(%outgate.3, %141)
      %143 : Tensor[] = prim::ListConstruct(%hy.6)
      %outputs.5 : Tensor[] = aten::add(%outputs.4, %143)
      %145 : int = prim::Constant[value=1]()
      %146 : int = aten::add(%121, %145)
      %147 : Tensor = aten::select(%inputs, %146)
      %148 : Float(*, *) = aten::t(%wih)
      %149 : Float(*, *) = aten::mm(%147, %148)
      %150 : Float(*, *) = aten::t(%whh)
      %151 : Float(*, *) = aten::mm(%hy.6, %150)
      %152 : Float(*, *) = aten::add(%149, %151, %6)
      %153 : Float(*, *) = aten::add(%152, %bih, %6)
      %gates.4 : Float(*, *) = aten::add(%153, %bhh, %6)
      %155 : Float(*, *), %156 : Float(*, *), %157 : Float(*, *), %158 : Float(*, *) = prim::ConstantChunk[chunks=4, dim=1](%gates.4)
      %ingate.4 : Float(*, *) = aten::sigmoid(%155)
      %forgetgate.4 : Float(*, *) = aten::sigmoid(%156)
      %cellgate.4 : Float(*, *) = aten::tanh(%157)
      %outgate.4 : Float(*, *) = aten::sigmoid(%158)
      %163 : Float(*, *) = aten::mul(%forgetgate.4, %cy.6)
      %164 : Float(*, *) = aten::mul(%ingate.4, %cellgate.4)
      %cy.7 : Float(*, *) = aten::add(%163, %164, %6)
      %166 : Float(*, *) = aten::tanh(%cy.7)
      %hy.7 : Float(*, *) = aten::mul(%outgate.4, %166)
      %168 : Tensor[] = prim::ListConstruct(%hy.7)
      %outputs.6 : Tensor[] = aten::add(%outputs.5, %168)
      %170 : int = prim::Constant[value=1]()
      %171 : int = aten::add(%146, %170)
      %172 : Tensor = aten::select(%inputs, %171)
      %173 : Float(*, *) = aten::t(%wih)
      %174 : Float(*, *) = aten::mm(%172, %173)
      %175 : Float(*, *) = aten::t(%whh)
      %176 : Float(*, *) = aten::mm(%hy.7, %175)
      %177 : Float(*, *) = aten::add(%174, %176, %6)
      %178 : Float(*, *) = aten::add(%177, %bih, %6)
      %gates.5 : Float(*, *) = aten::add(%178, %bhh, %6)
      %180 : Float(*, *), %181 : Float(*, *), %182 : Float(*, *), %183 : Float(*, *) = prim::ConstantChunk[chunks=4, dim=1](%gates.5)
      %ingate.5 : Float(*, *) = aten::sigmoid(%180)
      %forgetgate.5 : Float(*, *) = aten::sigmoid(%181)
      %cellgate.5 : Float(*, *) = aten::tanh(%182)
      %outgate.5 : Float(*, *) = aten::sigmoid(%183)
      %188 : Float(*, *) = aten::mul(%forgetgate.5, %cy.7)
      %189 : Float(*, *) = aten::mul(%ingate.5, %cellgate.5)
      %cy.8 : Float(*, *) = aten::add(%188, %189, %6)
      %191 : Float(*, *) = aten::tanh(%cy.8)
      %hy.8 : Float(*, *) = aten::mul(%outgate.5, %191)
      %193 : Tensor[] = prim::ListConstruct(%hy.8)
      %outputs.7 : Tensor[] = aten::add(%outputs.6, %193)
      %195 : int = prim::Constant[value=1]()
      %196 : int = aten::add(%171, %195)
      %197 : Tensor = aten::select(%inputs, %196)
      %198 : Float(*, *) = aten::t(%wih)
      %199 : Float(*, *) = aten::mm(%197, %198)
      %200 : Float(*, *) = aten::t(%whh)
      %201 : Float(*, *) = aten::mm(%hy.8, %200)
      %202 : Float(*, *) = aten::add(%199, %201, %6)
      %203 : Float(*, *) = aten::add(%202, %bih, %6)
      %gates.6 : Float(*, *) = aten::add(%203, %bhh, %6)
      %205 : Float(*, *), %206 : Float(*, *), %207 : Float(*, *), %208 : Float(*, *) = prim::ConstantChunk[chunks=4, dim=1](%gates.6)
      %ingate.6 : Float(*, *) = aten::sigmoid(%205)
      %forgetgate.6 : Float(*, *) = aten::sigmoid(%206)
      %cellgate.6 : Float(*, *) = aten::tanh(%207)
      %outgate.6 : Float(*, *) = aten::sigmoid(%208)
      %213 : Float(*, *) = aten::mul(%forgetgate.6, %cy.8)
      %214 : Float(*, *) = aten::mul(%ingate.6, %cellgate.6)
      %cy.9 : Float(*, *) = aten::add(%213, %214, %6)
      %216 : Float(*, *) = aten::tanh(%cy.9)
      %hy.9 : Float(*, *) = aten::mul(%outgate.6, %216)
      %218 : Tensor[] = prim::ListConstruct(%hy.9)
      %outputs.8 : Tensor[] = aten::add(%outputs.7, %218)
      %220 : int = prim::Constant[value=1]()
      %221 : int = aten::add(%196, %220)
      %222 : Tensor = aten::select(%inputs, %221)
      %223 : Float(*, *) = aten::t(%wih)
      %224 : Float(*, *) = aten::mm(%222, %223)
      %225 : Float(*, *) = aten::t(%whh)
      %226 : Float(*, *) = aten::mm(%hy.9, %225)
      %227 : Float(*, *) = aten::add(%224, %226, %6)
      %228 : Float(*, *) = aten::add(%227, %bih, %6)
      %gates.7 : Float(*, *) = aten::add(%228, %bhh, %6)
      %230 : Float(*, *), %231 : Float(*, *), %232 : Float(*, *), %233 : Float(*, *) = prim::ConstantChunk[chunks=4, dim=1](%gates.7)
      %ingate.7 : Float(*, *) = aten::sigmoid(%230)
      %forgetgate.7 : Float(*, *) = aten::sigmoid(%231)
      %cellgate.7 : Float(*, *) = aten::tanh(%232)
      %outgate.7 : Float(*, *) = aten::sigmoid(%233)
      %238 : Float(*, *) = aten::mul(%forgetgate.7, %cy.9)
      %239 : Float(*, *) = aten::mul(%ingate.7, %cellgate.7)
      %cy.10 : Float(*, *) = aten::add(%238, %239, %6)
      %241 : Float(*, *) = aten::tanh(%cy.10)
      %hy.10 : Float(*, *) = aten::mul(%outgate.7, %241)
      %243 : Tensor[] = prim::ListConstruct(%hy.10)
      %outputs.9 : Tensor[] = aten::add(%outputs.8, %243)
      %245 : int = prim::Constant[value=1]()
      %246 : int = aten::add(%221, %245)
      %247 : Tensor = aten::select(%inputs, %246)
      %248 : Float(*, *) = aten::t(%wih)
      %249 : Float(*, *) = aten::mm(%247, %248)
      %250 : Float(*, *) = aten::t(%whh)
      %251 : Float(*, *) = aten::mm(%hy.10, %250)
      %252 : Float(*, *) = aten::add(%249, %251, %6)
      %253 : Float(*, *) = aten::add(%252, %bih, %6)
      %gates.8 : Float(*, *) = aten::add(%253, %bhh, %6)
      %255 : Float(*, *), %256 : Float(*, *), %257 : Float(*, *), %258 : Float(*, *) = prim::ConstantChunk[chunks=4, dim=1](%gates.8)
      %ingate.8 : Float(*, *) = aten::sigmoid(%255)
      %forgetgate.8 : Float(*, *) = aten::sigmoid(%256)
      %cellgate.8 : Float(*, *) = aten::tanh(%257)
      %outgate.8 : Float(*, *) = aten::sigmoid(%258)
      %263 : Float(*, *) = aten::mul(%forgetgate.8, %cy.10)
      %264 : Float(*, *) = aten::mul(%ingate.8, %cellgate.8)
      %cy.11 : Float(*, *) = aten::add(%263, %264, %6)
      %266 : Float(*, *) = aten::tanh(%cy.11)
      %hy.11 : Float(*, *) = aten::mul(%outgate.8, %266)
      %268 : Tensor[] = prim::ListConstruct(%hy.11)
      %outputs.10 : Tensor[] = aten::add(%outputs.9, %268)
      %270 : int = prim::Constant[value=1]()
      %271 : int = aten::add(%246, %270)
      -> (%8, %271, %cy.11, %hy.11, %outputs.10)
  %63 : int, %cy : Float(*, *), %hy : Float(*, *), %outputs : Tensor[] = prim::Loop(%281, %8, %59, %cy.3, %hy.3, %outputs.1)
    block0(%seq_idx : int, %68 : int, %69 : Float(*, *), %70 : Float(*, *), %71 : Tensor[]):
      %72 : Tensor = aten::select(%inputs, %68)
      %73 : Float(*, *) = aten::t(%wih)
      %74 : Float(*, *) = aten::mm(%72, %73)
      %75 : Float(*, *) = aten::t(%whh)
      %76 : Float(*, *) = aten::mm(%70, %75)
      %77 : Float(*, *) = aten::add(%74, %76, %6)
      %78 : Float(*, *) = aten::add(%77, %bih, %6)
      %gates.1 : Float(*, *) = aten::add(%78, %bhh, %6)
      %80 : Float(*, *), %81 : Float(*, *), %82 : Float(*, *), %83 : Float(*, *) = prim::ConstantChunk[chunks=4, dim=1](%gates.1)
      %ingate.1 : Float(*, *) = aten::sigmoid(%80)
      %forgetgate.1 : Float(*, *) = aten::sigmoid(%81)
      %cellgate.1 : Float(*, *) = aten::tanh(%82)
      %outgate.1 : Float(*, *) = aten::sigmoid(%83)
      %88 : Float(*, *) = aten::mul(%forgetgate.1, %69)
      %89 : Float(*, *) = aten::mul(%ingate.1, %cellgate.1)
      %cy.4 : Float(*, *) = aten::add(%88, %89, %6)
      %91 : Float(*, *) = aten::tanh(%cy.4)
      %hy.4 : Float(*, *) = aten::mul(%outgate.1, %91)
      %93 : Tensor[] = prim::ListConstruct(%hy.4)
      %outputs.3 : Tensor[] = aten::add(%71, %93)
      %96 : int = aten::add(%68, %6)
      -> (%8, %96, %cy.4, %hy.4, %outputs.3)
  %48 : Tensor = aten::stack(%outputs, %9)
  %49 : Float(*, *, *) = aten::unsqueeze(%hy, %9)
  %50 : Float(*, *, *) = aten::unsqueeze(%cy, %9)
  %51 : (Float(*, *, *), Float(*, *, *)) = prim::TupleConstruct(%49, %50)
  %52 : (Tensor, (Float(*, *, *), Float(*, *, *))) = prim::TupleConstruct(%48, %51)
  return (%52)
```

**Comment by t-vi** [comment]
So I don't know the least thing about anything, but just based on the name `hasWriters`, I wonder whether the check in
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/alias_analysis.cpp#L94
should be
```
return numWrites_ != 0;
```
rather than `== 0`, based on the idea that if I have 0 Writes, I won't have Writers (or at least they're pretty lazy).

If anyone with more expertise could comment on that, I'd do a PR.

**Comment by suo** [comment]
yes, you're right! That's a good catch. I'll put up a PR to fix.

In the meantime, how did you generate the graph above? I'd like to investigate the redundant transposes—seems like CSE is getting confused somehow. I don't think the `hasWriters` thing will fix it, because we won't consider an input a wildcard.

**Comment by t-vi** [comment]
I dumped before and after the CSE pass for all graphs happening in  `python3 -m fastrnns.bench --rnns jit`

**Comment by suo** [comment]
Ah, I missed the tuple unpack above. Cool, I'll put up a fix. Thanks for investigating!!

**Pull request closed without merging**
