### PR TITLE
Flip Switch

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #97378
* #97440
* #97176
* __->__ #96775

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

Differential Revision: [D44228477](https://our.internmc.facebook.com/intern/diff/D44228477) 

Turn on cudagraph trees. Delay on fbcode turn on to flush out issues.

### CODE REVIEW

**Comment by eellison** [comment]
Error here is flakey:
```
Warning: 16 00:00:54,494] torch._inductor.utils: [WARNING] skipping cudagraphs due to complex input striding
1.140x p=0.00
+ python benchmarks/dynamo/check_hf_bert_perf_csv.py -f /var/lib/jenkins/workspace/test/test-reports/inductor_training_smoketest.csv
hf_Bert                            1.1398
```

i'm .002 short lol

**Review by wconstab — APPROVED** [review]

**Pull request closed without merging**
