### PR TITLE
Run all samples for torchinductor tests

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128343

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by peterbell10 — COMMENTED** [review]
Code looks good, but tests are still failing

**Review by lezcano — APPROVED** [review]

**Comment by isuruf** [comment]
Let's try again

**Pull request closed without merging**
