### PR TITLE
Support returning symbolic strides from t.stride() in Python

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #83842

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]

**Review by Chillee — APPROVED** [review]

**Review by bdhirsh — APPROVED** [review]
thanks :)

**Comment by ezyang** [comment]
bah `sym_stride` needs to get appropriate error checking for other tensorimpl subclasses

**Comment by ezyang** [comment]
I need the skip in https://github.com/pytorch/pytorch/pull/83628

**Pull request closed without merging**
