### PR TITLE
Add types for the remaining optimizers.

### PR DESCRIPTION
**Pull request by stephenroller**
**Patch Description**
Round out the rest of the optimizer types in torch.optim by creating the stubs for the rest of them.

**Testing**:
I ran mypy looking for just errors in that optim folder. There's no *new* mypy errors created.
```
$ mypy torch/optim | grep optim
$ git checkout master; mypy torch/optim | wc -l
968
$ git checkout typeoptims; mypy torch/optim | wc -l
968
```

### CODE REVIEW

**Comment by stephenroller** [comment]
Heads up @ezyang, flagging you because you said so in #27842.

**Comment by gchanan** [comment]
CC @vincentqb

**Review by ezyang — APPROVED** [review]
lgtm

**Comment by ezyang** [comment]
NB: soon we'll be able to put these type annotations inline! No more pyi files :>

**Review by vincentqb — APPROVED** [review]
lgtm too!

**Pull request closed without merging**
