### PR TITLE
inductor(cpu): remove __restrict__ keyword to avoid generating wrong result when two pointer point same memory

### PR DESCRIPTION
**Pull request by XiaobingSuper**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #96510
* __->__ #96492

Fix https://github.com/pytorch/pytorch/issues/93365, https://github.com/pytorch/pytorch/issues/93357 and https://github.com/pytorch/pytorch/issues/96432. Currently, remove `__restrict__` keyword to avoid generating the wrong result, there has a draft PR https://github.com/pytorch/pytorch/pull/96404 to do some memory alias checks before adding `__restrict__ `keyword, but that PR needs to re-designed well for the logic of the memory alias checks.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
I'm fine to disable it first to address these many issues. Suggest to get some perf numbers with benchmarks to understand its impact. If the impact is minimal, this could be the final solution. Otherwise, we can do a complete fix in later PR.

**Comment by XiaobingSuper** [comment]
> I'm fine to disable it first to address these many issues. Suggest to get some perf numbers with benchmarks to understand its impact. If the impact is minimal, this could be the final solution. Otherwise, we can do a complete fix in later PR.

Yes, will track the performance using PyTorch benchmark models.

**Review by desertfire — APPROVED** [review]
Approve to unblock, but please address Jiong's concern before merging.

**Comment by XiaobingSuper** [comment]
I tested the performance of TIMM and HF models, and didn't see a performance regression for removing **__restrict__**(tested on SKX-6148, one socket(20 threads)):


TIMM models:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/xiaobin1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/xiaobin1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



name | batch_size | speedup(new) | speedup(old) | new/old
-- | -- | -- | -- | --
adv_inception_v3 | 128 | 2.1307 | 2.1274 | 1.001551189
beit_base_patch16_224 | 64 | 1.0528 | 1.0533 | 0.999525301
botnet26t_256 | 128 | 2.3429 | 2.3327 | 1.004372615
cait_m36_384 | 4 | 1.0889 | 1.0902 | 0.998807558
coat_lite_mini | 128 | 1.3418 | 1.3379 | 1.002915016
convit_base | 64 | 1.1335 | 1.1341 | 0.999470946
convmixer_768_32 | 32 | 1.7484 | 1.7803 | 0.982081672
convnext_base | 64 | 1.256 | 1.2341 | 1.017745726
crossvit_9_240 | 128 | 1.0989 | 1.098 | 1.000819672
cspdarknet53 | 64 | 1.7363 | 1.7436 | 0.99581326
deit_base_distilled_patch16_224 | 64 | 1.1602 | 1.1582 | 1.001726817
dm_nfnet_f0 | 128 | 1.1609 | 1.1601 | 1.000689596
dpn107 | 32 | 1.4302 | 1.4037 | 1.018878678
eca_botnext26ts_256 | 128 | 2.1616 | 2.1517 | 1.004601013
eca_halonext26ts | 128 | 2.2098 | 2.1231 | 1.040836513
ese_vovnet19b_dw | 128 | 2.0463 | 1.9622 | 1.042860055
fbnetc_100 | 128 | 3.6464 | 3.6437 | 1.000741005
fbnetv3_b | 128 | 3.4045 | 3.3989 | 1.001647592
gernet_l | 128 | 1.7939 | 1.7906 | 1.001842958
ghostnet_100 | 128 | 2.3812 | 2.3829 | 0.999286584
gluon_inception_v3 | 128 | 2.132 | 2.1331 | 0.999484319
gluon_xception65 | 32 | 2.1782 | 2.1609 | 1.008005923
gmixer_24_224 | 128 | 1.3455 | 1.3455 | 1
gmlp_s16_224 | 128 | 1.2203 | 1.2103 | 1.008262414
hrnet_w18 | 128 | 2.5803 | 2.5763 | 1.001552614
inception_v3 | 128 | 2.1517 | 2.1462 | 1.002562669
jx_nest_base | 32 | 1.164 | 1.1615 | 1.002152389
lcnet_050 | 128 | 3.4691 | 3.4687 | 1.000115317
mixer_b16_224 | 128 | 1.1526 | 1.155 | 0.997922078
mixnet_l | 128 | 1.4745 | 1.472 | 1.00169837
mnasnet_100 | 128 | 3.6841 | 3.6848 | 0.99981003
mobilenetv2_100 | 128 | 3.8945 | 3.9041 | 0.997541047
mobilenetv3_large_100 | 128 | 3.4131 | 3.4192 | 0.998215957
mobilevit_s | 64 | 2.1339 | 1.9932 | 1.070590006
nfnet_l0 | 128 | 1.3204 | 1.3204 | 1
pit_b_224 | 64 | 1.1687 | 1.1627 | 1.005160403
pnasnet5large | 16 | 2.2162 | 2.2252 | 0.99595542
poolformer_m36 | 64 | 1.6312 | 1.6264 | 1.002951303
regnety_002 | 128 | 2.8448 | 2.8318 | 1.00459072
repvgg_a2 | 128 | 1.5935 | 1.592 | 1.000942211
res2net101_26w_4s | 64 | 1.8401 | 1.8454 | 0.997127994
res2net50_14w_8s | 128 | 1.9761 | 1.971 | 1.002587519
res2next50 | 128 | 2.0855 | 2.0903 | 0.997703679
resmlp_12_224 | 128 | 1.2842 | 1.2839 | 1.000233663
resnest101e | 64 | 1.9748 | 1.9773 | 0.99873565
rexnet_100 | 128 | 3.1293 | 3.1116 | 1.005688392
sebotnet33ts_256 | 64 | 1.4231 | 1.4612 | 0.973925541
selecsls42b | 128 | 1.5444 | 1.5416 | 1.001816295
spnasnet_100 | 128 | 3.7042 | 3.6965 | 1.002083052
swin_base_patch4_window7_224 | 64 | 1.2043 | 1.2096 | 0.995618386
swsl_resnext101_32x16d | 32 | 1.4663 | 1.4627 | 1.002461202
tf_efficientnet_b0 | 128 | 2.2808 | 2.2991 | 0.992040364
tf_mixnet_l | 128 | 0.8427 | 0.8434 | 0.999170026
tinynet_a | 128 | 2.934 | 2.903 | 1.010678608
tnt_s_patch16_224 | 128 | 1.2295 | 1.2234 | 1.004986104
twins_pcpvt_base | 64 | 1.3206 | 1.3099 | 1.008168562
visformer_small | 128 | 1.4942 | 1.4769 | 1.011713725
vit_base_patch16_224 | 64 | 1.158 | 1.1582 | 0.999827318
volo_d1_224 | 64 | 1.5296 | 1.5325 | 0.998107667
xcit_large_24_p8_224 | 5 | 1.2773 | 1.2791 | 0.998592761



</body>

</html>


HF models:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/xiaobin1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/xiaobin1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



name | batch_size | speedup(new) | speedup(old) | new/old
-- | -- | -- | -- | --
AlbertForMaskedLM | 4 | 1.1168 | 1.1147 | 1.001883915
AlbertForQuestionAnswering | 4 | 1.113 | 1.1112 | 1.00161987
AllenaiLongformerBase | 4 | 1.2364 | 1.2327 | 1.003001541
BartForCausalLM | 4 | 1.0624 | 1.0855 | 0.978719484
BartForConditionalGeneration | 2 | 0.9638 | 0.9617 | 1.002183633
BertForMaskedLM | 16 | 1.2731 | 1.2754 | 0.998196644
BertForQuestionAnswering | 16 | 1.2929 | 1.2927 | 1.000154715
BlenderbotForCausalLM | 4 | 1.2089 | 1.2096 | 0.999421296
BlenderbotSmallForCausalLM | 64 | 1.1736 | 1.1726 | 1.000852806
BlenderbotSmallForConditionalGeneration | 64 | 1.1607 | 1.1596 | 1.000948603
CamemBert | 16 | 1.2727 | 1.274 | 0.998979592
DebertaForMaskedLM | 4 | 1.0386 | 1.039 | 0.999615014
DebertaForQuestionAnswering | 8 | 1.0877 | 1.0892 | 0.998622842
DebertaV2ForMaskedLM | 1 | 1.1861 | 1.1881 | 0.99831664
DebertaV2ForQuestionAnswering | 2 | 1.002 | 0.9998 | 1.00220044
DistilBertForMaskedLM | 128 | 1.1735 | 1.156 | 1.015138408
DistilBertForQuestionAnswering | 256 | 1.1706 | 1.1676 | 1.002569373
DistillGPT2 | 16 | 1.241 | 1.2465 | 0.995587645
ElectraForCausalLM | 32 | 1.4304 | 1.4255 | 1.00343739
ElectraForQuestionAnswering | 64 | 1.3355 | 1.3367 | 0.999102267
GPT2ForSequenceClassification | 4 | 1.1503 | 1.1535 | 0.997225834
GoogleFnet | 16 | 1.5433 | 1.5447 | 0.999093675
LayoutLMForMaskedLM | 16 | 1.2834 | 1.2799 | 1.002734589
LayoutLMForSequenceClassification | 16 | 1.3049 | 1.3035 | 1.001074031
M2M100ForConditionalGeneration | 16 | 1.0838 | 1.0857 | 0.998249977
MBartForCausalLM | 4 | 1.0618 | 1.0596 | 1.002076255
MBartForConditionalGeneration | 2 | 0.9604 | 0.9615 | 0.998855954
MT5ForConditionalGeneration | 16 | 1.1867 | 1.1846 | 1.00177275
MegatronBertForCausalLM | 4 | 1.1505 | 1.1506 | 0.999913089
MegatronBertForQuestionAnswering | 8 | 1.2081 | 1.2073 | 1.000662636
MobileBertForMaskedLM | 64 | 1.3902 | 1.4073 | 0.987849073
MobileBertForQuestionAnswering | 128 | 1.7725 | 1.7628 | 1.005502609
OPTForCausalLM | 2 | 1.1 | 1.1048 | 0.995655322
PLBartForCausalLM | 8 | 1.1117 | 1.1255 | 0.987738783
PLBartForConditionalGeneration | 4 | 1.0626 | 1.0627 | 0.9999059
PegasusForCausalLM | 32 | 1.0842 | 1.0827 | 1.001385425
PegasusForConditionalGeneration | 32 | 1.0916 | 1.0912 | 1.000366569
Speech2Text2ForCausalLM | 256 | 1.2235 | 1.2261 | 0.997879455
T5ForConditionalGeneration | 4 | 0.7883 | 0.7821 | 1.007927375
T5Small | 4 | 0.7823 | 0.7818 | 1.00063955
TrOCRForCausalLM | 32 | 1.0593 | 1.0678 | 0.992039708
XGLMForCausalLM | 8 | 1.2605 | 1.2623 | 0.998574032
XLNetLMHeadModel | 8 | 3.3019 | 3.3003 | 1.000484804
YituTechConvBert | 16 | 1.563 | 1.4787 | 1.057009535



</body>

</html>

**Pull request closed without merging**
