### PR TITLE
set SCCACHE_IGNORE_SERVER_IO_ERROR=1

### PR DESCRIPTION
**Pull request by mszhanyi**
https://github.com/mozilla/sccache/pull/1090 has been accepted by Mozilla.
It will take effect after updating the sccache binaries in S3 

Note: last sccache.exe is sccache-20200507.exe
image

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
:o

**Review by janeyx99 — COMMENTED** [review]
What about the normal win-build.sh file as well?

**Comment by mszhanyi** [comment]
> What about the normal win-build.sh file as well?

Yes, good finding.

**Review by janeyx99 — CHANGES_REQUESTED** [review]
Actually, I'm not sure what's going on in the binaries--could you rebase?

**Review by janeyx99 — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Comment by mszhanyi** [comment]
> Will this fix #64154?
@janeyx99 
Yes, I think so. Let's see the stat. after 1 or 2 weeks since it's a random issue.

**Pull request closed without merging**
