### PR TITLE
Port `min` and `max` full reductions to structured kernels

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #64735

Tracking Issue: #55070 

This PR creates out overloads for both `min` and `max` kernels (full reduction overload),
and ports them to structured kernels.

### CODE REVIEW

**Comment by ysiraichi** [comment]
I don't think I understand how Pytorch JIT works enough to understand these CI failures (all/most of them appears to be JIT related). For example, `test_min_max` tests the binary kernel `min.other(Tensor self, Tensor other)`. That said, I haven't touched that kernel.

**What I think is happening:** my best guess is that JIT is using the full reduction kernel `min.all_out(Tensor self, *, Tensor out)` instead of the binary one. The reason being that they both have the same number of parameters with the same types, even though one is a kwarg (which works for the non-JIT tests).

If that's true, I guess that would mean that we can't have an `out` overload for the `min` and `max` full reduction kernels due to conflicts with their binary overloads (JIT-only).

@ezyang  @bdhirsh  What do you think?

**Comment by ezyang** [comment]
blah, if your diagnosis is right, that's really bad

**Comment by bdhirsh** [comment]
I dug into this a little - it looks like operator overload resolution happens in two places:
- eager mode: python_arg_parser
- torchscript: performs its own overload resolution for each node in the graph, happens here https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/ir/ir.cpp#L1065

And it looks like torchscript's `Node::matches` function just ignores whether each arg is kwarg-only.

That information should be available though, since it's stored inside `FunctionSchema`.

@ezyang I don't see an existing issue for it (afaict), so I'll create one.  Unless I'm missing something, the change doesn't look too hard?
- the `torch::jit::Node` class also needs to store its `FunctionSchema` (hopefully that's okay?)
- `torch::jit::Node::matches()` needs to compare the kwarg-ness of each argument in the two schemas

**Comment by ezyang** [comment]
If it really is a Node::matches problem, then we are SOL: Node doesn't contain information about whether or not there were kwargs or not, this was already desugared away.

I *thought* that Node was supposed to already have overloads resolved but... it seems like it doesn't.

**Comment by ezyang** [comment]
I have a really awful workaround for this problem. We introduce a new optional argument to `torch.min` with the expectation that it never gets used (maybe we can make a special type for this, so that it gets erased at Python side)

```
- func: min(Tensor self, DummyArg dummy = DummyArg) -> Tensor
```

now we can add the out variant:


```
- func: min.out(Tensor self, DummyArg dummy = DummyArg, *, Tensor out) -> Tensor
```

We will have to add a truly horrifying amount of code to make this work though so I'm not very keen...

Maybe @ansley has some more ideas, or knows someone who might.

**Comment by bdhirsh** [comment]
Hmmm, it feels like the morally right thing would be to fix overload resolution in `Node` class, if Node really is supposed to do overload resolution.

Is there a compelling reason not to make sure we retain all the necessary info on the `Node` class (either the full FunctionSchema, or a bitmask of which args are kwarg-only) to properly do overload resolution? Performance?

**Comment by ysiraichi** [comment]
One way around this problem is changing `min.dim` so that they accept multiple reduction dimensions, instead of only one. Then, `min(tensor)` would turn into a composite kernel. (same for `max`)

@bdhirsh @ezyang what do you think?

**Comment by ezyang** [comment]
I guess, I'd only do this if we thought it was long term, the correct move as far as the API is concerned.

Some notes from internal discussion:
* NNC has a problem too, bug at https://github.com/pytorch/pytorch/issues/64963
* @eellison says: "I would recommend keeping a different symbol for this min, and making sure that it gets mapped to it in https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/frontend/builtin_functions.cpp . If the is a problem we continually run into we could consider a larger fix, but I think it would be a pretty involved change"

**Comment by ysiraichi** [comment]
@ezyang @bdhirsh @eellison 

AFAIU, the problem with this approach is that it would solve only for scripted TorchScript functions. However, if one tried to trace a function that uses `min.other` (same for `max`), we would bump into the same error. So, I'd say we have these options:

1. add a dummy argument to `{min,max}.all_out` (as @ezyang suggested)
2. modify `Value` to indicate whether it's a kwarg or not (as @bdhirsh suggested)
3. use `Value::unique_name` to store the name of the arguments, and make `Node::matches` also take that into consideration (maybe worse than (2))
4. don't port these 2 (is it an option?)

What do you think?

**Comment by eellison** [comment]
@ysiraichi you can also add a canonicalization for traced graphs in https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/normalize_ops.cpp, that gets run on every traced graph

**Comment by ysiraichi** [comment]
@eellison Thank you for your suggestion!
That said, I don't think I understand how that would solve the problem...

**Recalling the problem:** whenever we use `min.other(a, b)`, `Node::maybeOperator` selects `min.all_out(a, out=b)`. That is because `Node::matches` doesn't seem to distinguish between the two of them.

**What I think you are suggesting me to do:** to implement, say, a `NormalizeMin` function like:

```c++
bool NormalizeMin(graph_node_list_iterator& iter) {
  if (iter->matches("aten::min.other(Tensor self, Tensor other) -> Tensor")) {
    ArrayRef<Value*> args = iter->inputs();
    Node* newNode = iter->replaceWithNewSymbol(aten::minimum); // min.other gets mapped correctly!
    newNode->replaceInput(0, args[1]);
    newNode->replaceInput(1, args[0]);
    iter.destroyCurrent();
    return true;
  }
  return false;
}
```

If that's what you are suggesting, doesn't it end up with almost the same problem as before? `iter->matches` will return `true` for both `min.other` and `min.all_out` usages, won't it?

**Comment by eellison** [comment]
@ysiraichi ugh yea you're right, oops. cc @gmagogsfm / @jamesr66a do you know if we have any places to override tracing behavior or how one would do that ? I know the tracing dispatching code is automatically generated, maybe it's possible to override for a particular op ?

**Comment by jamesr66a** [comment]
Manual JIT trace overrides are implemented in `TraceTypeManual.cpp`: https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/TraceTypeManual.cpp

After adding it there, I think you need to specify that it's a manual implementation here: https://github.com/pytorch/pytorch/blob/0032fa772588cd20f2b85324bdeb31ac497bbf29/tools/autograd/gen_trace_type.py#L22

**Comment by ysiraichi** [comment]
@jamesr66a That sounds really promising. However, as I understand it, `MANUAL_*` do not take overload names, right? If I add `'min'` there, I will have to add one function for each of the 6 overloads of `min` in `TraceTypeManual.cpp`. Is my understanding correct?

**Comment by eellison** [comment]
@ysiraichi right now the logic to dispatch to a custom trace just is based on name, but it could be extended to look at the overload, see https://github.com/pytorch/pytorch/blob/0032fa772588cd20f2b85324bdeb31ac497bbf29/tools/autograd/gen_trace_type.py#L414

**Comment by ysiraichi** [comment]
@eellison got it. I will try that, then.
@eellison @jamesr66a thank you for the suggestions!

**Comment by ysiraichi** [comment]
I think I managed to fix most of the CI failures related to _scripting_ and _tracing_ for both `min` and `max`, by mapping them to `minimum` and `maximum`, respectively. However, now, `ONNX` seems to be complaining.

I think the problem is that we are trying to convert programs to `ONNX` from a JIT script (or trace). At that time, both `min` and `max` were already remapped. Since neither `minimum` nor `maximum` are in `ONNX`, we are getting these failures.

https://github.com/pytorch/pytorch/blob/3315c4b31ef582891149a7c7c05cfda8c50642f3/test/onnx/test_pytorch_onnx_onnxruntime.py#L322-L323

@bdhirsh What do you think?

**Comment by bdhirsh** [comment]
> However, now, ONNX seems to be complaining.

> I think the problem is that we are trying to convert programs to ONNX from a JIT script (or trace). At that time, both min and max were already remapped. Since neither minimum nor maximum are in ONNX


I'm not too familiar with onnx, and I can't easily tell that that's the issue from the CI failure. Although it sounds reasonable. https://github.com/pytorch/pytorch/runs/4333466854?check_suite_focus=true#step:16:19406.

@eellison What do you think? (Or do you know someone more familiar with onnx). Is it worth either (a) figuring out how to add `minimum/maximum` ops for onnx, or (b) figuring out how to re-map `minimum->min` when converting from torchscript to onnx? Although I wonder if we're going down a rabbit hole.

does manually mapping `max -> maximum` / `min -> minimum` in tracing/scripting mean a BC-breaking change for consumers like onnx?

**Pull request closed without merging**
