### PR TITLE
fix lint for cudnn codes

### PR DESCRIPTION
**Pull request by yewentao256**
Fixes the lint issue described in https://github.com/pytorch/pytorch/pull/116759

@albanD Please have a look

cc @albanD

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
How did you fix them? (we only accept very large PRs like this that were generated via specific lint tool apply)
Also should we update lintrunner.toml to now lint these files properly?
fyi @Skylion007

**Comment by yewentao256** [comment]
> How did you fix them?

Through clang-format.

BTW, I think checking more files through `lintrunner.toml` is reasonable.

**Comment by albanD** [comment]
Ok!
Could you add these files to lintrunner please now that they're fixed and then we can merge!

**Comment by yewentao256** [comment]
Hi @albanD  Could we merge this pr now? It seems the workflows should be approved to get started.

**Review by albanD — APPROVED** [review]
Thanks for the update, looks good!

**Comment by yewentao256** [comment]
> Ho could you please fix the small lint failure?

Done~ Please approve again

**Pull request closed without merging**
