### PR TITLE
record_function: update to use custom_class API

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #72303
* __->__ #72302

Merge after forward-compatibility period is over.

### CODE REVIEW

**Comment by peterbell10** [comment]
I believe the FC window of two weeks is expired now.

**Comment by peterbell10** [comment]
@robieta ping

**Review by albanD — APPROVED** [review]
SGTM Thanks for the update

**Comment by atalman** [comment]
looks like it breaks compatibility, we are seeing following errors related to this PR: 
```
0401 13:37:31.450265   342 ExceptionTracer.cpp:222] exception stack complete
terminate called after throwing an instance of 'torch::jit::ErrorReport'
  what():  
Unknown type name '__torch__.torch.classes.profiler._RecordFunction':
Serialized   File "code/__torch__/torch/autograd/profiler.py", line 5
  args : Optional[str]
  run_callbacks_on_exit : bool
  record : Optional[__torch__.torch.classes.profiler._RecordFunction]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  def __enter__(self: __torch__.torch.autograd.profiler.record_function) -> __torch__.torch.autograd.profiler.record_function:
    name = self.name
```

**Comment by peterbell10** [comment]
Are you exporting a model from one PyTorch version, then running it on an older PyTorch version? If so, that's a forward compatibility break and was expected.

**Comment by albanD** [comment]
@peterbell10 yes this is a common thing being done internally and that is why we have the 2week FC window.
@atalman this PR followed the 2 week FC window that we guarantee (we actually left 2 months) so it is ok for us to break this.

**Comment by atalman** [comment]
This PR  is causing fblearner predictor publish/deploy breakage as well for PyPer model.

```
E0406 20:24:31.783488   342 ExceptionTracer.cpp:218] terminate() called, exception stack follows
E0406 20:24:31.783522   342 ExceptionTracer.cpp:220] Exception type: (unknown type) (4 frames)
    @ 00000000305fa4b6 facebook::fblearner::predictor::ManifoldModelOpener::loadModelsFromFBPKG(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
                       ./fblearner/predictor/proxy/ManifoldModelOpener.cpp:260
    @ 000000002f49f7f5 main
                       ./smart/inference_platform_sp/predictor/MyHandler.cpp:210
    @ 0000000000025dc4 __libc_start_main
    @ 000000001d766fc9 _start
                       /home/engshare/third-party2/glibc/2.30/src/glibc-2.30/csu/../sysdeps/x86_64/start.S:120
E0406 20:24:31.798008   342 ExceptionTracer.cpp:222] exception stack complete
terminate called after throwing an instance of 'torch::jit::ErrorReport'
  what():  
Unknown builtin op: profiler::_record_function_enter_new.
Could not find any similar ops to profiler::_record_function_enter_new. This op may not exist or may not be currently supported in TorchScript.
:
```

**Comment by peterbell10** [comment]
@malfet @atalman the can someone explain why this is being reverted? The error messages posted are consistent with a forward-compatibility break which is expected and in line with the compatibility policy. Or is there a BC break here that I'm not seeing?

**Comment by malfet** [comment]
@peterbell10 it has been re-commited in https://github.com/pytorch/pytorch/pull/76172, but there are still ongoing discussion about performance implications of the change (results are unclear though)

**Comment by malfet** [comment]
@peterbell10 , @robieta  running
```python
import torch
from timeit import timeit

def foo():
  with torch.profiler.record_function("foo"):
    return torch.eye(3)

if __name__ == "__main__":
    print(torch.__version__)
    print(timeit(lambda: torch.eye(3)))
    print(timeit(foo))
```
on latest nightly returns:
```
$ python time_record.py 
1.12.0.dev20220422
2.4962380239994673
80.59850038700006
```
but essentially reverting the change
```
$ diff -u profiler.py /fsx/users/nshulga/conda/envs/py_3.7-torch-nightly/lib/python3.7/site-packages/torch/autograd/profiler.py 
--- profiler.py	2022-04-22 20:08:29.459000000 +0000
+++ /fsx/users/nshulga/conda/envs/py_3.7-torch-nightly/lib/python3.7/site-packages/torch/autograd/profiler.py	2022-04-22 20:25:44.000000000 +0000
@@ -440,18 +440,21 @@
         self.run_callbacks_on_exit: bool = True
         # TODO: TorchScript ignores standard type annotation here
         # self.record: Optional["torch.classes.profiler._RecordFunction"] = None
-        self.record = torch.jit.annotate(Optional["torch.classes.profiler._RecordFunction"], None)
+        #self.record = torch.jit.annotate(Optional["torch.classes.profiler._RecordFunction"], None)
+        self.handle: torch.Tensor = torch.zeros(1)
 
     def __enter__(self):
-        self.record = torch.ops.profiler._record_function_enter_new(self.name, self.args)
+        # self.record = torch.ops.profiler._record_function_enter_new(self.name, self.args)
+        self.handle = torch.ops.profiler._record_function_enter(self.name, self.args)
         return self
 
     def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any):
         if self.run_callbacks_on_exit:
             # Local variable is needed by TorchScript to refine Optional[T] to T
-            record = self.record
-            assert record is not None
-            torch.ops.profiler._record_function_exit(record)
+            # record = self.record
+            # assert record is not None
+            # torch.ops.profiler._record_function_exit(record)
+            torch.ops.profiler._record_function_exit(self.handle)
 
     def _call_end_callbacks_on_future(self, fut: Future[Any]) -> Future[Any]:
         """
@@ -480,8 +483,9 @@
         self.run_callbacks_on_exit = False
 
         # Local variable is needed by TorchScript to refine Optional[T] to T
-        record = self.record
-        assert record is not None
+        # record = self.record
+        # assert record is not None
+        # profiled_future = torch.ops.profiler._call_end_callbacks_on_jit_fut(record, fut)
         profiled_future = torch.ops.profiler._call_end_callbacks_on_jit_fut(record, fut)
         return profiled_future
```

Speeds `record_function` up by 4x:
```
$ python time_record.py 
1.12.0.dev20220422
2.4211607899997034
12.582032529000571
```

**Comment by robieta** [comment]
@peterbell10 Just to give an update on the perf issue:
`_record_function_enter_new` is a bit slower (~5us vs. ~3.5us), but `_record_function_exit` is massively slower (65us vs. 2.5us) for the custom class holder. I pulled a flame graph just calling `_record_function_exit(record)` in a loop and >95% was spent in `torch::jit::_get_operation_for_overload_or_packet`. (Specifically, about half in `has_torch_function_attr` and the other half in `torch::jit::invokeOperatorFromPython`) We can mitigate somewhat by using `torch._C._autograd._record_function_with_args_exit` (7us), but that's still much slower than the custom type hack. So I think the TL;DR is that we need to get our house in order regarding the Python binding code. Sorry your change got caught in the crossfire.

**Comment by albanD** [comment]
@robieta would it be acceptable here to make this context manager a true no-op when the profiler is disabled? Then the perf hit will be acceptable?

**Comment by robieta** [comment]
We should definitely make it a no-op when profiling is disabled, but we also have to fix the enabled overhead or it will distort the trace.

**Pull request closed without merging**
