### PR TITLE
Update NCCL submodule to v2.20.5

### PR DESCRIPTION
**Pull request by Skylion007**
Updates NCCL submodule to 2.20.5 . Includes a lot of bugfixes for reductions and connections issues. Should also improve performance. We have been running 2.20.5 internally for a few weeks, the binary pip wheels have finally been published so we can update main.

Release notes here: https://docs.nvidia.com/deeplearning/nccl/release-notes/rel_2-20-5.html#rel_2-20-5

### CODE REVIEW

**Review by malfet — APPROVED** [review]
It might require some builder changes, but sure, why not

**Comment by Skylion007** [comment]
Ugh, seems like we might need some builder changes after all.

**Comment by huydhn** [comment]
Let me see if I can update the missing dependencies on your S3 bucket to resolve the failures.

cc @Skylion007 @atalman

**Pull request closed without merging**
