### PR TITLE
Enable batching for pinverse

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:
- Modify existing implementation of pinverse to support batching on inputs

Test Plan:
- Added tests in test_pinverse to test batched implementation

### CODE REVIEW

**Comment by soumith** [comment]
has conflicts

**Comment by vishwakftw** [comment]
Please allow me to fix them by evening, not sure what caused the conflict

**Comment by vishwakftw** [comment]
@soumith I've fixed the conflicts, thank you for letting me know about the same.

**Review by soumith — APPROVED** [review]

**Pull request closed without merging**
