### PR TITLE
Update XLA pin

### PR DESCRIPTION
**Pull request by malfet**
Updating the pin to the same hash as  https://github.com/pytorch/pytorch/pull/100922

On the XLA side, build have switch from CMake to bazel, which requires number of changes on PyTorch side:
 - Copy installed headers back to the `torch/` folder before starting the build
 - Install `torch/csrc/lazy/python/python_utils.h`
 - Define `LD_LIBRARY_PATH`

TODO:
 - Enable bazel caching
 - Pass CXX11_ABI flag to  `//test/cpp:all`  to reuse build artifacts from  `//:_XLAC.so`

### <samp>🤖 Generated by Copilot at cd4768b</samp>

> _To fix the XLA tests that were failing_
> _We updated the submodule and scaling_
> _We added `python_util.h`_
> _And copied `torch` as well_
> _And set `LD_LIBRARY_PATH` for linking_

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM! I rebase the PR to get the change in https://github.com/pytorch/pytorch/pull/102562

**Comment by malfet** [comment]
Notes to self:
XLAC.so is built by running 
```
bazel build //:_XLAC.so --symlink_prefix=build/temp.linux-x86_64-cpython-38/bazel- --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=1 --remote_default_exec_properties=cache-silo-key=dev 
```
from `/var/lib/jenkins/workspace/xla` folder


At the very end, cpp tests are run using https://github.com/pytorch/xla/blob/044425f64faa73e4e7e4e1f28ae727136e7b64ab/test/cpp/run_tests.sh

**Pull request closed without merging**
