### PR TITLE
Add NHWC format computation of ResizeNearest

### PR DESCRIPTION
**Pull request by seravee**
Having a diff in fb.

Adding NHWC format computation of ResizeNearest for both CPU and GPU version. Also added corresponding tests.

### CODE REVIEW

**Comment by seravee** [comment]
fixed GPU test and code reformat

**Comment by seravee** [comment]
The failing test is test_caffe2_to_onnx for caffe2/caffe2/python/onnx/tests, but it is passing on the latest repo of fb internal build, not sure what is going on.

**Comment by ezyang** [comment]
@seravee What's the status of this PR?

**Pull request closed without merging**
