### PR TITLE
[TEST] Clang-cl build without annotations

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by peterjc123** [comment]
@malfet Hi, I managed to run the full build & test. However, some of the tests in `test_jit` and `test_namedtensor` didn't pass. I also disabled mkldnn and fbgemm.

**Comment by peterjc123** [comment]
@malfet @ezyang  With mkldnn enabled, the CI starts to complain about the duplicate symbols. 
```
lld-link: error: duplicate symbol: public: virtual bool __cdecl caffe2::RoIAlignRotatedOp<float, class caffe2::CPUContext>::RunOnDevice(void) in caffe2\CMakeFiles\torch_cpu.dir\ideep\operators\operator_fallback_ideep.cc.obj and in caffe2\CMakeFiles\torch_cpu.dir\operators\roi_align_rotated_op.cc.obj
```
Do you have any idea on this?

**Comment by ezyang** [comment]
That's pretty weird. Maybe the problem could be solved by explicitly instantiating the template in the header that defines it? Somehow the template instantiation isn't being made a weak symbol.

**Comment by peterjc123** [comment]
@malfet I tried clang-cl and lld-link recently and below is my findings:
1. With lld-link (in LLVM 10) and cl, linking `torch.dll` takes a long time in https://github.com/pytorch/pytorch/pull/36886. I guess there is sth wrong there.
2. MSVC and Clang 10 are not fully ABI-compatible. Weird linking errors are reported. https://circleci.com/gh/pytorch/pytorch/5208922?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link However, this doesn't seem to be a problem in Clang 9.0.1 (at least in this PR).
3. The C++ exception handling in Clang is not fully implemented. So some tests related to exception rethrow will fail. Recently, I saw some fixes related to that like https://reviews.llvm.org/D77920. Maybe we can try building a binary with those fixes.

**Comment by peterjc123** [comment]
@malfet Do you have a plan on this?

**Comment by peterjc123** [comment]
Continued in https://github.com/pytorch/pytorch/pull/63288/files.

**Pull request closed without merging**
