### PR TITLE
Fix device of lengths in pack_padded_sequence when the default device is GPU

### LINKED ISSUE #103964: pack_padded_sequence not working as expected when default device is gpu
### 🐛 Describe the bug

When
1. the default device is set to GPU and
2. the `lengths` argument is `List[int]` (which is still valid as mentioned in [documentation](https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.pack_padded_sequence.html))
`pack_padded_sequence` converts `lengths` into a tensor [by](https://github.com/pytorch/pytorch/blob/main/torch/nn/utils/rnn.py#LL251C9-L251C62)
```
lengths = torch.as_tensor(lengths, dtype=torch.int64)
```
, which is on GPU.
To reproduce
```python
import torch
from torch.nn.utils.rnn import pack_padded_sequence
torch.set_default_device(‘cuda’)
seq = torch.tensor([[1,2,0], [3,0,0]])
lens = [2,1]
pack_padded_sequence(seq, lens, enforce_sorted=False)
### RuntimeError: ‘lengths’ argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```
Tried on the latest nightly build and the problem still exists. I believe adding a `device=‘cpu’` to `torch.as_tensor` should fix this

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230620+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.27

Python version: 3.9.16 (main, May 18 2023, 22:40:25)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1037-aws-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 510.39.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7.6.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:            7
CPU MHz:             3099.958
BogoMIPS:            5000.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni

Versions of relevant libraries:
[pip3] mypy==0.910
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] pytorch-lightning==2.0.2
[pip3] pytorch-triton==2.1.0+440fd1bf20
[pip3] torch==2.1.0.dev20230620+cu118
[pip3] torchaudio==2.1.0.dev20230620+cu118
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.16.0.dev20230620+cu118
[pip3] triton==2.0.0
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### PR DESCRIPTION
**Pull request by xs0ul**
Fixes #103964

Always create the `lengths` tensor on cpu

### CODE REVIEW

**Comment by mikaylagawarecki** [comment]
Hey @xs0ul could you sign the [CLA agreement in this comment ](https://github.com/pytorch/pytorch/pull/103967#issuecomment-1601102639)please

**Comment by xs0ul** [comment]
sure just did that

**Review by mikaylagawarecki — APPROVED** [review]
Thanks!

**Pull request closed without merging**
