### PR TITLE
Constraints symmetric

### PR DESCRIPTION
**Pull request by nonconvexopt**
Opened PR again.
Implemented Symmetric matrices 'torch.distributions.constraints' for implementing

### CODE REVIEW

**Comment by nonconvexopt** [comment]
Hello, @albanD. May I have a chance to be reviewed my PR?

I am trying to contribute to PyTorch by implementing distributions for symmetric matrices like Wishart distribution and Inverse Wishart distribution. Although there is a LKJ distribution for the cholesky decomposition of correlation matrices, it only represents equivalence to restricted form of Wishart distribution. Thus I started implementing Wishart distribution and Inverse Wishart distribution and directly.

 To do so, I wrote a code about the new trivial constraint 'symmetric' not included in 'torch.distributions.constraints'. 'torch.distributions.constraints' contains 'positive_definite' constraints but it just assumes symmetricity of the matrices. So, I think it will be better if we have symmetric constraint in PyTorch.

We may further use it like
`constraints.stack([constraints.symmetric, constraints.positive_definite])`
to check if the random matrix is a symmetric positive definite matrix.

Thanks.

**Comment by albanD** [comment]
Sure, @fritzo can you take a look?

**Comment by nonconvexopt** [comment]
Sorry for triggering review request. I selected wrong commit to revert. It is my bad.

**Comment by nonconvexopt** [comment]
Sorry for the confusion.

**Pull request closed without merging**
