### PR TITLE
[FSDP] Default to not checking exec order

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#79584 [FSDP] Default to not checking exec order**
* #79557 [FSDP] Extend ignored modules test to not pass to root
* #79533 [FSDP] Fix exec order validation for diff ignored modules across ranks

Differential Revision: [D37161466](https://our.internmc.facebook.com/intern/diff/D37161466)

### CODE REVIEW

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37161466).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37161466).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37161466).

**Review by rohan-varma — APPROVED** [review]
Stamping to unblock, but we should consider whether we really want to turn this off across OSS or just for the specific use case in question.

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37161466).

**Comment by awgu** [comment]
Not for land

**Pull request closed without merging**
