### PR TITLE
Improve input dimensions check for reflection_pad1d, reflection_pad2d and reflection_pad3d

### PR DESCRIPTION
**Pull request by jiayisunx**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #141670

Fix https://github.com/pytorch/pytorch/issues/141447.

### CODE REVIEW

**Review by mingfeima — APPROVED** [review]

**Comment by jiayisunx** [comment]
hi @malfet  , could you please review this PR? thanks!

**Comment by malfet** [comment]
> hi @malfet , could you please review this PR? thanks!

Thank you for the fix, but do you mind adding unit tests (i.e. one could not claim it fixes something without the test)

**Comment by jiayisunx** [comment]
> > hi @malfet , could you please review this PR? thanks!
> 
> Thank you for the fix, but do you mind adding unit tests (i.e. one could not claim it fixes something without the test)

Added, thanks for your comments!

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
