### PR TITLE
[CMake] Remove pthread linking

### PR DESCRIPTION
**Pull request by cyyever**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by r-barnes — APPROVED** [review]

**Comment by malfet** [comment]
It passes the testing as `c10` already links with pthreads, but imo they should have stayed there if tests make explicit calls to pthread_create or something like that...

**Comment by cyyever** [comment]
@malfet I prefer to use Threads::Threads to avoid limited to POSIX.

**Pull request closed without merging**
