### PR TITLE
Delete default constructor from CUDAStream.

### PR DESCRIPTION
**Pull request by ezyang**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #13125 Rewrite THPUtils_PySequence_to_CUDAStreamList to return vector<optional<CUDAStream>>&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D10853224/)
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#13021 Delete default constructor from CUDAStream.**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D10520421/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #13133 Add c10::Stream, make at::cuda::CUDAStream use it.&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D10855883/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #13232 Delete DeviceGuard(int64_t) constructor.&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D10858024/)

Let's make nullptr CUDAStream an illegal state.

Differential Revision: [D10520421](https://our.internmc.facebook.com/intern/diff/D10520421/)

### CODE REVIEW

**Comment by ezyang** [comment]
This is annoying for client code, I'm not going to do it.

**Comment by ezyang** [comment]
Nevermind, the call sites must die

**Comment by ezyang** [comment]
This appears to have broken NCCL.

**Review by teng-li — COMMENTED** [review]
Spoke offline, please fix these push_backs

**Comment by ezyang** [comment]
@teng-li Now that the move constructor is fixed in HEAD, `push_back` is fine.

**Review by gchanan — APPROVED** [review]

**Pull request closed without merging**
