### PR TITLE
port zero_ from TH to ATen

### PR DESCRIPTION
**Pull request by shihongzhi**
Implements  #24653

### CODE REVIEW

**Comment by ifedan** [comment]
Can we remove TH implementation?

**Comment by ifedan** [comment]
Also can you provide performance metrics for previous and current implementation?

**Comment by VitalyFedyunin** [comment]
Please re-add me and @ifedan as reviewers after comments addressed. Thanks.

**Comment by shihongzhi** [comment]
This issue is already implemented.

**Pull request closed without merging**
