### PR TITLE
[inductor] Move things into torch/testing/_internal/inductor_utils.py

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #113278
* __->__ #113275
* #113242

This PR is just moving things around, so code shared by multiple tests files is in torch/testing/_internal/inductor_utils.py.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your stack, but it is failing to list test internally with buck2' -c ghfirst

The error is https://www.internalfb.com/sandcastle/workflow/2476979795055236508

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your stack, but it is failing to list test internally with buck2' -c ghfirst

The error is https://www.internalfb.com/sandcastle/workflow/2476979795055236508

**Pull request closed without merging**
