### PR TITLE
CPU Convolution benchmark harness for some popular models

### PR DESCRIPTION
**Pull request by bertmaher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#56455 CPU Convolution benchmark harness for some popular models**

CPU convolution performance is pretty important for inference, so
tracking performance for CNNs often boils down to finding shapes that have
either regressed or need optimization.  This diff adds a benchmark harness that
lets you pretty easily add new sets of convolution parameters to benchmark.

I've started with an exhaustive list of layers from MobileNetV3, ResNet-18 and
ResNet-50, which are fairly popular torchvision models.  More to come if these
prove useful.

I've also added four backend configurations:

- native: uses at::conv2d, which applies its own backend selection heuristics
- mkldnn_none: uses mkldnn but applies no prepacking; uses the NCHW default
- mkldnn_weight: prepacks weights in an mkldnn-friendly format
- mkldnn_input: also prepacks the inputs in NCHW16c

Differential Revision: [D27876139](https://our.internmc.facebook.com/intern/diff/D27876139/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D27876139/)!

### CODE REVIEW

**Comment by wconstab** [comment]
i wonder if we can feed this for free by having a script that passes over the torchbench models and outputs a dump of conv sizes observed.  otherwise looks like a useful tool!

**Comment by bertmaher** [comment]
> i wonder if we can feed this for free by having a script that passes over the torchbench models and outputs a dump of conv sizes observed. otherwise looks like a useful tool!

Hehe, in fact the way I generated it for these models was to apply a little patch to dump convolution shapes from `at::conv2d`, and run a select few torchbench models :-).  https://gist.github.com/bertmaher/1476d71d03a44ba888c750391effa0d8 was the diff.  Maybe it would be better to do an fx pass or something, but I happen to be more familiar with hacking the c++ :-p

**Comment by VitalyFedyunin** [comment]
> * native: uses at::conv2d, which applies its own backend selection heuristics
Could you also include option with at::conv2d AND mkldnn disabled.

**Comment by ngimel** [comment]
>i wonder if we can feed this for free by having a script that passes over the torchbench models and outputs a dump of conv sizes observed. otherwise looks like a useful tool!

Profiler records shapes of inputs, so could be used for that purpose. Unfortunately, it doesn't record non-tensor args, so things like padding and dilation are not recorded.

**Comment by bertmaher** [comment]
> > * native: uses at::conv2d, which applies its own backend selection heuristics
> 
> Could you also please include option with at::conv2d AND mkldnn disabled.

Done, and this provides quite interesting data!  You can definitely see layers where native is ahead of mkldnn w/o pretransposed, but pretransposing pulls ahead:
```
ResNet50_native_I1x512x7x7_W512x512x3x3_B_S1x1_P1x1_D1x1_G1           9082409 ns    9081987 ns        154 GB/s=1061.21M/s GFLOPS/s=25.4582G/s
ResNet50_native_nomkl_I1x512x7x7_W512x512x3x3_B_S1x1_P1x1_D1x1_G1     3736247 ns    3736059 ns        374 GB/s=2.57969G/s GFLOPS/s=61.8863G/s
ResNet50_mkldnn_none_I1x512x7x7_W512x512x3x3_B_S1x1_P1x1_D1x1_G1      9091506 ns    9090817 ns        154 GB/s=1060.18M/s GFLOPS/s=25.4335G/s
ResNet50_mkldnn_weight_I1x512x7x7_W512x512x3x3_B_S1x1_P1x1_D1x1_G1    2398276 ns    2398191 ns        584 GB/s=4.01882G/s GFLOPS/s=96.4106G/s
ResNet50_mkldnn_input_I1x512x7x7_W512x512x3x3_B_S1x1_P1x1_D1x1_G1     2361308 ns    2361047 ns        592 GB/s=4.08204G/s GFLOPS/s=97.9273G/s
```

Of course there are also several cases where native is always ahead (and in those our heuristic seems to usually pick native), for instance:
```
ResNet50_native_I1x256x56x56_W64x256x1x1_B_S1x1_P0x0_D1x1_G1                551373 ns     551368 ns       2508 GB/s=7.39908G/s GFLOPS/s=186.374G/s
ResNet50_native_nomkl_I1x256x56x56_W64x256x1x1_B_S1x1_P0x0_D1x1_G1          545046 ns     545044 ns       2511 GB/s=7.48493G/s GFLOPS/s=188.536G/s
ResNet50_mkldnn_none_I1x256x56x56_W64x256x1x1_B_S1x1_P0x0_D1x1_G1          1030976 ns    1030929 ns       1392 GB/s=3.95722G/s GFLOPS/s=99.6775G/s
ResNet50_mkldnn_weight_I1x256x56x56_W64x256x1x1_B_S1x1_P0x0_D1x1_G1        1020759 ns    1020706 ns       1000 GB/s=3.99686G/s GFLOPS/s=100.676G/s
ResNet50_mkldnn_input_I1x256x56x56_W64x256x1x1_B_S1x1_P0x0_D1x1_G1          684842 ns     684812 ns       1996 GB/s=5.95728G/s GFLOPS/s=150.057G/s
```

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
