### PR TITLE
openreg add pin_memory

### PR DESCRIPTION
**Pull request by Zhenbin-8**
Occording to `Next steps` in test/cpp_extensions/open_registration_extension/README.md, add Pinned memory and HostAllocator.

cc @albanD @FFFrog

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Thanks for the change, that sounds good.
Could you please revert the submodule updates that I guess are unrelated?

**Comment by Zhenbin-8** [comment]
> Thanks for the change, that sounds good. Could you please revert the submodule updates that I guess are unrelated?

@albanD I've fixed the problem, would you mind reviewing it again :)

**Review by albanD — APPROVED** [review]
SGTM!

**Comment by albanD** [comment]
Ho I realized this was never merged, if you still want this, please rebase it and we can merge it.

**Comment by Zhenbin-8** [comment]
> Ho I realized this was never merged, if you still want this, please rebase it and we can merge it.

Sure I'd like to merge it. I've rebased it onto https://github.com/pytorch/pytorch/pull/136249 locally, and will resubmit it after https://github.com/pytorch/pytorch/pull/136249 merged :)

**Comment by Zhenbin-8** [comment]
@albanD I've rebased this PR, please help check again :)

**Review by albanD — APPROVED** [review]
Sounds good! Thanks!

**Pull request closed without merging**
