### PR TITLE
Expand GRADIENT_IMPLEMENTED_FOR_COMPLEX to allow named tensors

### LINKED ISSUE #47157: Complex dtype and named tensors don't go along
## 🚀 Feature
Support differentiation for complex-valued named tensors.

## Motivation
Complex datatypes and named tensors are an important (yet experimental) feature yey `view_as_complex` and `view_as_real` will not support differentiation of complex tensors.

**Problem:**
```
import torch
names = ["batch", "height", "width", "complex"]
z = torch.ones((5, 12, 14, 2), requires_grad=True).refine_names(*names)
z_complex = torch.view_as_complex(z.rename(None)).refine_names(*names[:-1])
```
Results in:

`RuntimeError: alias does not support automatic differentiation for outputs with complex dtype.
`

There is no hope in building such a function yourself either:
```
def view_as_complex(data):
    """Named version of `torch.view_as_complex()`"""
    data = data.clone()
    real_part = data[..., 0]
    imag_part = data[..., 1]

    return (real_part + 1j*imag_part).refine_names(*data.names[:-1])
```
gives the same error.

## Additional context
PyTorch 1.7 however introduces complex-valued spectral operators, requiring code that uses channels to represent real and imaginary parts to use `view_as_complex` and `view_as_real`. If these tensors however are named, this does not work, especially not when in 1.8 the previous fft is dropped. This is important in e.g. MRI reconstruction frameworks.

Supporting `view_as_complex` and `view_as_real` for named tensors would be useful too.

@zou3519 

cc @ezyang @anjali411 @dylanbespalko @mruberry @zou3519

### PR DESCRIPTION
**Pull request by jonasteuwen**
Complex-valued named tensors do not support backpropagation currently. This is due to `tools/autograd/gen_variable_type.py` not containing `alias` in `GRADIENT_IMPLEMENTED_FOR_COMPLEX` which is required to constructed named tensors.

This fixes #47157. Also removed a duplicate `cholesky` in the list.

cc: @zou3519 @anjali411

### CODE REVIEW

**Comment by anjali411** [comment]
@jonasteuwen thanks for the PR! let's add a test in `test_autograd.py` to verify this change.

cc. @zou3519 who is our Named Tensors expert

**Comment by jonasteuwen** [comment]
@anjali411 I can add a test in `test_autograd.py` if you want. There does not seem to be a section on named tensors in `test_autograd.py` and `alias` is also not exposed in python.

Currently, without adding `alias` to the autograd list, it already fails when trying to assign names to a variable 

```
z = torch.zeros((5,5,5), dtype=torch.complex64, requires_grad=True)
z.refine_names("a", "b", "c")
```

So, in what form would you want such a test?

**Comment by zou3519** [comment]
This seems reasonable. irrespective of the named tensors part of the issue, `alias` is a pytorch operator (albeit c++ only) and we should have complex autograd support for it.

**Comment by zou3519** [comment]
> So, in what form would you want such a test?

Your test case + a backward should be convincing enough:
```
import torch
names = ["batch", "height", "width", "complex"]
z = torch.ones((5, 12, 14, 2), requires_grad=True).refine_names(*names)
z_complex = torch.view_as_complex(z.rename(None)).refine_names(*names[:-1])
z_complex.sum().backward()
self.assertEqual(z.grad, torch.ones_like(z))
```

**Comment by zou3519** [comment]
@jonasteuwen the "Update to upstream" commit seems to have added a lot of files here. I'm not sure if it is possible to salvage this PR; if it isn't please feel free to open a new PR with the changes and cc us.

**Comment by jonasteuwen** [comment]
Accidently removed my branch, redone in https://github.com/pytorch/pytorch/pull/47289.

**Comment by zou3519** [comment]
Closing this PR because  #47289 supercedes this

**Pull request closed without merging**
