### PR TITLE
Change ATen to use Caffe2/cmake upstream FindCUDA

### PR DESCRIPTION
**Pull request by ezyang**
Originally part of #6188 but I was running into mysterious Windows errors, so applying this patch by itself first.

### CODE REVIEW

**Comment by ezyang** [comment]
OK... looks like we lost some Windows fix... CCing @peterjc123 though I am currently investigating

**Comment by ezyang** [comment]
@peterjc123 OK, I think I have a pretty good idea what's going on here, just want to keep you posted.

(1) It turns out that upstream support for CUDA on Windows only works if you are using the Visual Studio cmake generator. We're using the ninja generator, so it is triggering our error. @peterjc123 wrote us a patch to handle this correctly in 737aba3fc5ed009cd91a48715bf7765b6cb8a1a1 which we just need to upstream.

(2) In 737aba3fc5ed009cd91a48715bf7765b6cb8a1a1 and 522276759d3fdf266608a37b517cc62a6cbc06e4 there was also some work done passing `ccbin` appropriately so that `select_compute_arch` works correctly. This is a bit trickier, because upstream has completely diverged from our local copy and now uses `try_run` directly to snoop the information. I did a test of the upstream logic and it seems to properly detect the GPU version on the windows GPU machines we have on AWS. Would you like to double check this on your local dev environment?

I think it's clear what we have to do, just would like a double check, thanks!

**Comment by ezyang** [comment]
Note to self: add an extra debug message when CUDA arch we are targeting is specified by env var.

**Comment by Yangqing** [comment]
Is this overridden by #6241 ?

**Comment by peterjc123** [comment]
@ezyang Actually, the first fix is for clcache. The second point is correct. And I have tried to build it on my dev machine and it works.

**Comment by ezyang** [comment]
@peterjc123  Ohhh, I see! Well, we'll still use your patch anyhoo.

**Review by soumith — APPROVED** [review]

**Pull request merged**
