### PR TITLE
Added sorting notes for eig/eigvals

### LINKED ISSUE #58034: Add a `descending` flag to `linalg.eigh` and `linalg.svd`
At the moment the eigenvalues are returned in `linalg.eigh` in ascending order, while the singular values in `linalg.svd` are returned in descending order.

This dissonance is annoying but it goes in line with Numpy. Even then, we should at least give the user a nice interface to ask for the order they want the spectral values in. The name of the flag is in line with that present in `torch.sort`.

cc @svekars @carljparker @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @heitorschueroff

### LINKED ISSUE #105471: [benchmark] Rename the count field FunctionCount
The `count` field is in `FunctionCount` defined in `torch/utils/benchmark/utils/valgrind_wrapper/timer_interface.py` is redefining the built in field of tuple. Consider renaming.

>              Hmm, do you mind renaming it to something else? How about `counter`? or `invocation_count` (though strictly speaking out of scope of this PR)

_Originally posted by @malfet in https://github.com/pytorch/pytorch/pull/105424#discussion_r1266832538_
            

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

### PR DESCRIPTION
**Pull request by awmle**
Fixes #58034

@lezcano , Added suggested comments for eig and eigvals in the documentation.

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
Thank you for picking this one up!

**Comment by awmle** [comment]
> ## Merge failed
> **Reason**: 1 jobs have failed, first few of them are: [trunk / macos-13-py3-arm64 / build](https://github.com/pytorch/pytorch/actions/runs/9300683610/job/25597259792)
> 
> Details for Dev Infra team

Is this something where I can help?

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
