### PR TITLE
add BFloat16 support for LayerNorm CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #58297 add BFloat16 support for UpSample on CPU
* #56904 optimize transpose copy for float32 and bfloat16 on CPU
* #56903 add BFloat16 support for MaxPool2d on CPU
* #56902 add BFloat16 support for AdaptiveAvgPool2d on CPU
* #56372 add BFloat16 support for bernoulli and Dropout on CPU
* #55588 add bf16 support for bucketize
* #55221 optimize BFloat16 elemwise operators CPU: sigmoid, sigmoid_backward, tanh_backward, addcmul, addcdiv
* #55217 SumKernel (BFloat16): use float as accumulation type
* **#55210 add BFloat16 support for LayerNorm CPU**

Differential Revision: [D28836793](https://our.internmc.facebook.com/intern/diff/D28836793)

### CODE REVIEW

**Comment by mingfeima** [comment]
Since this PR is not related to parallelization feature, only single core perf is tested:
NB: LayerNorm CPU doesn't have BFloat16 support previously, the before perf refers to simple impl as following:
```diff
-  AT_DISPATCH_FLOATING_TYPES(X.scalar_type(), "LayerNormKernelImpl", [&]() {
+  AT_DISPATCH_FLOATING_TYPES_AND(kBFloat16, X.scalar_type(), "LayerNormKernelImpl", [&]() {
```

- performance update on **avx512** machine: Xeon(R) Gold 6248 CPU @ 2.50GHz
```bash
before: LayerNorm: 32x128x1024: fp32: 2.806 ms; bf16: 9.901 ms
after:  LayerNorm: 32x128x1024: fp32: 2.813 ms; bf16: 2.306 ms
```
- performance update on **avx2** machine: Xeon(R) CPU E5-2680 v3 @ 2.50GHz
```bash
before: LayerNorm: 32x128x1024: fp32: 5.286 ms; bf16: 15.186 ms
after:  LayerNorm: 32x128x1024: fp32: 5.258 ms; bf16: 3.469 ms
```

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836793).

**Comment by mingfeima** [comment]
rebased and clear test cases failures from `test_ops.py`

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836793).

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Please rebase

**Comment by mingfeima** [comment]
@VitalyFedyunin rebased, please check!

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836793).

**Pull request closed without merging**
