### PR TITLE
Correctly formatting the example in get_state_dict

### LINKED ISSUE #118837: [DCP] Some Distributed state_dict related APIs docstring not formatting correctly in pytorch docs page
### 📚 The doc issue

https://pytorch.org/docs/stable/distributed.checkpoint.html

One example:
the example code and the return type of ```get_state_dict``` are not showing up correctly. Need to fix this by 2.2.1.

image

### Suggest a potential alternative/fix

_No response_

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @tianyu-l @wconstab @yf225 @LucasLLC

### PR DESCRIPTION
**Pull request by jmarintur**
This PR corrects the example formatting provided in https://pytorch.org/docs/stable/distributed.checkpoint.html. In this issue, @wz337 is also commenting that the return type was not showing up correctly. I didn't see any formatting issue, but I could be wrong. 

Fixes #118837

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @LucasLLC

### CODE REVIEW

**Comment by awgu** [comment]
Just to clarify, for the return type, we want to figure out how to make the docs _not_ expand the type aliases. Otherwise, the return type is too verbose and not helpful.

**Comment by jmarintur** [comment]
Hi @awgu, thank you for the clarification. What about something like this?

[Tuple](https://docs.python.org/3/library/typing.html#typing.Tuple)[[ModelStateDict](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.state_dict), [OptimizerStateDict](https://pytorch.org/docs/stable/generated/torch.optim.Optimizer.state_dict.html)]

**Comment by awgu** [comment]
The function currently has return type `Tuple[Dict[str, ValueType], OptimizerStateType]:`. I think it would be sufficient to have the docs display that instead of expanding `ValueType` and `OptimizerStateType`.

**Comment by fegin** [comment]
Thanks for the fix. We can land this fix first.

**Review by fegin — APPROVED** [review]

**Comment by jmarintur** [comment]
Thank you @fegin! 

Perhaps one way of improving it consists in manually adding `:rtype: tuple[dict[str, ValueType], OptimizerStateType]`. In this case, you'd get something like this: 

image

But then, the types are pointing at different locations. For instance, Tuple will be pointing at https://docs.python.org/3/library/stdtypes.html#tuple instead of https://docs.python.org/3/library/typing.html#typing.Tuple
Moreover, the format won't be exactly the same, no italic and no capital T. And of course, you'd need to do this for the other functions, what could be a nightmare.

Do you have something in mind that could solve this? The other option I guess is to change sphinx to not expand the types, but I am not sure how to do that.

**Comment by jmarintur** [comment]
Ok, I only needed to write it like this: `:rtype: typing.Tuple[typing.Dict[str, ValueType], OptimizerStateType]`. Here's the result:

image

Now, the only thing is that we'd need to do the same with other similar cases.

**Comment by jmarintur** [comment]
Hi, I've just pushed another commit to improve the return type.

**Comment by wz337** [comment]
@jmarintur Thanks for working on the issue!

**Comment by jmarintur** [comment]
> @jmarintur Thanks for working on the issue!

🤗 Thank you, @wz337. It was a pleasure working on it. Looking forward to more collaboration with the PyTorch team!

**Pull request closed without merging**
