### PR TITLE
Fix the issue that Bad interaction between no_grad and numpy conversi…

### PR DESCRIPTION
**Pull request by chengjinfang1216**
…on(#37000)

### CODE REVIEW

**Comment by chengjinfang1216** [comment]
Hi，@albanD，could you review the PR for me?

**Review by albanD — COMMENTED** [review]
Thanks for the PR!

I think you could simplify the testing a bit here. No need to nest no_grad and enable_grad. And enable_grad is always enabled by default!
So I think you can simply test the following 4 cases:
- x.requires_grad = True or False
- without wrapper or with torch.no_grad().

**Comment by chengjinfang1216** [comment]
Hi，@albanD，I have modified the test code，could you review the PR again? thank you.

**Review by albanD — APPROVED** [review]
Perfect thanks for the update!

**Pull request closed without merging**
