### PR TITLE
Move THPStorage definitions out of `torch/csrc/generic`

### LINKED ISSUE #77908: Move C++/Python Storage bindings out of `torch/csrc/generic`
Since #75459 was merged, we now only have one `THPStorage` class, which means that we can move all storage related stuff out of `torch/csrc/generic` to simplify things further

### PR DESCRIPTION
**Pull request by kurtamohler**
Fixes #77908

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
YESSS

**Comment by ezyang** [comment]
unfortunately bazel error looks real

```
2022-05-21T03:14:38.5329326Z [31m[1mERROR: [0m/var/lib/jenkins/workspace/BUILD.bazel:1693:11: Compiling torch/csrc/Storage.cpp failed: (Exit 1): gcc failed: error executing command /opt/cache/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++11' -MD -MF ... (remaining 279 argument(s) skipped)
2022-05-21T03:14:38.5331112Z 
2022-05-21T03:14:38.5331668Z Use --sandbox_debug to see verbose messages from the sandbox
2022-05-21T03:14:38.5332232Z torch/csrc/Storage.cpp:359:10: fatal error: torch/csrc/StorageMethods.cpp: No such file or directory
2022-05-21T03:14:38.5332725Z  #include <torch/csrc/StorageMethods.cpp>
2022-05-21T03:14:38.5333091Z           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by kurtamohler** [comment]
Here's the important part of the log of the failure:

```
2022-05-24T15:59:56.3816356Z [6097/6309] Building CXX object caffe2\torch\CMakeFiles\torch_python.dir\csrc\StorageSharing.cpp.obj
2022-05-24T15:59:56.3817015Z FAILED: caffe2/torch/CMakeFiles/torch_python.dir/csrc/StorageSharing.cpp.obj 
...
2022-05-24T15:59:56.3845731Z C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\complex(354): error C2039: 'copysign': is not a member of '`global namespace''
2022-05-24T15:59:56.3846639Z C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\complex(354): error C3861: 'copysign': identifier not found
...
2022-05-24T16:00:02.2409189Z [6102/6309] Building CXX object caffe2\torch\CMakeFiles\torch_python.dir\csrc\StorageMethods.cpp.obj
2022-05-24T16:00:02.2410153Z FAILED: caffe2/torch/CMakeFiles/torch_python.dir/csrc/StorageMethods.cpp.obj 
...
2022-05-24T16:00:02.2438157Z C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\complex(354): error C2039: 'copysign': is not a member of '`global namespace''
2022-05-24T16:00:02.2447842Z C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\complex(354): error C3861: 'copysign': identifier not found
```

I'm not sure where this `copysign` is coming from. I'm not calling it in `StorageMethods.cpp` or `StorageSharing.cpp`. I guess it's possible that I removed an include file that was required. I'll see what I can figure out

**Comment by kurtamohler** [comment]
I added this to `StorageMethods.cpp` and `StorageSharing.cpp`:

```
#ifdef _MSC_VER
#include <c10/util/win32-headers.h>
#endif
```

Not sure if it'll work, but it did jump out to me since it's a windows-specific include that these files used to have access to, which I removed

**Comment by kurtamohler** [comment]
Hmmm, it looks like `wheel-py3_7-cuda11_3-build` wasn't run, even though we have the `ciflow/all` label. Not sure what to do about that. Maybe I need to make a new PR

**Comment by kurtamohler** [comment]
I noticed that `c10/util/math_compat.h` has some `std::copysign` definitions. So I've included that file in `StorageMethods.cpp` and `StorageSharing.cpp`. Hopefully that fixes the error

**Comment by kurtamohler** [comment]
It's still failing. Since I'm having trouble figuring out which include is missing, I think I should try just copying all of the includes from `torch/csrc/Storage.cpp` into `StorageMethods.cpp` and `StorageSharing.cpp`. Even though it's overkill, I'm pretty sure that would fix the error

**Comment by kurtamohler** [comment]
The XLA failure appears to be upstream, so I think this should be good to go now

**Pull request closed without merging**
