### PR TITLE
Release GIL in torch.cuda ops wherever possible.

### PR DESCRIPTION
**Pull request by pritamdamania87**
Most `torch.cuda` ops (ex: `torch.cuda.synchronize`) do not release GIL in C++ land. This has the potential of causing deadlocks and freeze the python process. For example, `torch.cuda.synchronize` could hold GIL and get blocked on some operation. However, that operation might never complete in python land since GIL is held by `torch.cuda.synchronize`.

In this PR, I've tried to release GIL as much as possible in `torch.cuda` ops.

See https://github.com/pytorch/pytorch/issues/109074 for an example of how holding GIL causes a deadlock.

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
While I agree that sync should release the GIL, I think that most of these APIs are basically just setting a constant. Release and re-acquiring the GIL could make these ops a lot more expensive than they are right now? Please add some basic benchmarking to ensure it is ok if you want to preserve these.

Also the first line of `cuda_lazy_init()` function is literally to grab the GIL. So no need to release it before calling this function!

**Comment by pritamdamania87** [comment]
> While I agree that sync should release the GIL, I think that most of these APIs are basically just setting a constant. Release and re-acquiring the GIL could make these ops a lot more expensive than they are right now? Please add some basic benchmarking to ensure it is ok if you want to preserve these.

Is there something in https://github.com/pytorch/benchmark which is representative of this to validate?

> Also the first line of cuda_lazy_init() function is literally to grab the GIL. So no need to release it before calling this function!

Good point, will move that outside.

**Comment by albanD** [comment]
> Is there something in https://github.com/pytorch/benchmark which is representative of this to validate?

Not sure not. But all these APIs are synchronous so `%timeit` should be enough.

**Comment by voznesenskym** [comment]
I would build a global flag that dictates this behavior. For most programs, this doesnt matter and just adds overhead.

**Comment by pritamdamania87** [comment]
> I would build a global flag that dictates this behavior. For most programs, this doesnt matter and just adds overhead.

This does matter for almost all training programs since most realistic training programs use more than 1 gpu and some sort of distributed training.

**Comment by pritamdamania87** [comment]
@albanD Hope this is good enough.

With this PR:

```
-------------------------------------------------- benchmark 'hub': 1 tests --------------------------------------------------
Name (time in ms)                      Min       Max      Mean  StdDev    Median     IQR  Outliers     OPS  Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------
test_train[BERT_pytorch-cuda]     150.5070  150.9757  150.6692  0.1487  150.6471  0.0974       2;1  6.6371       7           1
------------------------------------------------------------------------------------------------------------------------------
```

Without this PR:

```
-------------------------------------------------- benchmark 'hub': 1 tests --------------------------------------------------
Name (time in ms)                      Min       Max      Mean  StdDev    Median     IQR  Outliers     OPS  Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------
test_train[BERT_pytorch-cuda]     150.3616  151.2864  150.8020  0.3638  150.7255  0.6355       3;0  6.6312       7           1
------------------------------------------------------------------------------------------------------------------------------
```

The benchmark is marginally faster with this PR.

**Comment by albanD** [comment]
> Hope this is good enough.

Why not just check `%timeit torch.cuda.set_device(0)` before and after? This is what I had in mind.
But tbh, I think it would be simpler to not modify any function but "synchronize" which is the only expensive op here.

**Comment by pritamdamania87** [comment]
> Why not just check %timeit torch.cuda.set_device(0) before and after? This is what I had in mind.

These are the results with timeit:

With this PR:

```
$ python -m timeit "import torch; torch.cuda.set_device(0)"
1 loop, best of 5: 781 nsec per loop
$ python -m timeit "import torch; torch.cuda.current_device()"
1 loop, best of 5: 792 nsec per loop
```

Without this PR:

```
$ python -m timeit "import torch; torch.cuda.set_device(0)"
1 loop, best of 5: 793 nsec per loop
$ python -m timeit "import torch; torch.cuda.current_device()"
1 loop, best of 5: 802 nsec per loop
```

> But tbh, I think it would be simpler to not modify any function but "synchronize" which is the only expensive op here.

This is not sufficient since https://github.com/pytorch/pytorch/blob/293d3b89d8bf8f966fe06d25ac1089a3739e20e3/torch/_inductor/triton_heuristics.py uses `torch.cuda.device` ctx manager, `torch.cuda.set_device` and `torch.cuda.current_device` as well. We need to release GIL for all of these otherwise we would still end up in a deadlock. I added more coverage in this PR to be safe so that we don't end up incrementally fixing this issue across multiple PRs. Also, note that this not different from majority of torch operations where we release GIL before executing them (even if they are pretty cheap).

**Comment by albanD** [comment]
> We need to release GIL for all of these otherwise we would still end up in a deadlock.

How would get_device or set_device or current_device trigger a deadlock?

**Comment by pritamdamania87** [comment]
> How would get_device or set_device or current_device trigger a deadlock?

When NCCL hits an error, the NCCL kernels typically lock up the GPU and most CUDA calls just block on the host CPU side until the offending NCCL kernel is aborted via `ncclCommAbort`. Even simple calls like `cudaGetLastError` (see https://github.com/pytorch/pytorch/issues/101463) and `cudaEventQuery` block on the CPU side.

**Comment by gchanan** [comment]
> When NCCL hits an error, the NCCL kernels lock up the GPU and most CUDA calls just block on the host CPU side until the offending NCCL kernel is aborted via ncclCommAbort. Even simple calls like cudaGetLastError (see https://github.com/pytorch/pytorch/issues/101463) and cudaEventQuery block on the CPU side.

If we fixed that issue, would this still be a problem (outside of synchronize).

**Comment by pritamdamania87** [comment]
> If we fixed that issue, would this still be a problem (outside of synchronize).

Do you mean the NCCL issue? That is how NCCL works for probably 4+ years now and the NCCL team's suggestion is to use `ncclCommAbort` to recover from the situation. I think fixing that is probably a much more long drawn proposition than the fix here which is straightforward.

**Comment by pritamdamania87** [comment]
@albanD @gchanan Curious if you have major concerns about the current PR? Do we have any other alternatives in terms of resolving https://github.com/pytorch/pytorch/issues/109074?

**Comment by pritamdamania87** [comment]
@alband reduced the scope to these functions:

* THCPModule_cudaCachingAllocator_raw_alloc (can cause sync due to cudaMalloc)
* THCPModule_cudaCachingAllocator_raw_delete (can cause sync due to cudaFree)
* THCPModule_cudaSynchronize
* THCPModule_cudaSleep

**Comment by wconstab** [comment]
I think this PR is stuck in directional limbo more than anything.  Do we agree on trying to reduce GIL holding in cuda ops or not? if so then is it just a matter of validating and de-risking the changes?  or do we want to argue that this change just isn't good?  cc @ezyang

**Review by ezyang — APPROVED** [review]

**Comment by ngimel** [comment]
fwiw, even seemingly cheap cuda calls like `cudaPointerGetAttributes` (and maybe others, I haven't tested) can take incredibly long due to weird cuda driver locking behavior. I'm describing the case I've seen, but there are probably other combinations.  When `cudaRegisterHostMemory` is running it apparently takes the driver lock, so `cudaPointerGetAttributes` called from another thread will wait for this call to finish. If it's wrapped from python and doesn't release GIL, it will be holding GIL for a long time, even though the call itself looks like "just getting a constant". Similar thing could happen with cudaGet/SetDevice?

**Pull request closed without merging**
