### PR TITLE
[2/N] Enable clang-tidy to c10/test/*cpp

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by janeyx99** [comment]
adding @kit1980 as reviewer from devx team--please reassign if you think there is a better owner

**Review by Skylion007 — APPROVED** [review]
These are tests so they are probably fine. This will increase our coverage of headers which will be great!

**Comment by cyyever** [comment]
@kit1980 Need your help to re-import so that it is synced with META

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
@cyyever I've unlinked the Meta-internal diff. The check passes now.

**Pull request closed without merging**
