### PR TITLE
Change docstring type callable to Callable for consistency

### PR DESCRIPTION
**Pull request by ProGamerGov**
### Description

Across PyTorch's docstrings, both `callable` and `Callable` for variable types. The Callable should be capitalized as we are referring to the `Callable` type, and not the Python `callable()` function.

### Testing

There shouldn't be any testing required.

### CODE REVIEW

**Comment by ProGamerGov** [comment]
The test failure appears to be unrelated to the changes in this PR.

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by ProGamerGov** [comment]
@albanD These 2 other similar PRs need the frontend and documentation labels as well:

* `boolean` -> `bool` and `string` -> `str` changes implemented into the PyTorch master branch: https://github.com/pytorch/pytorch/pull/82410

* `ints` -> `int` changes implemented into the PyTorch master branch: https://github.com/pytorch/pytorch/pull/82474

**Pull request closed without merging**
