### PR TITLE
Fused attention patterns

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #97741

Patterns based on https://github.com/pytorch/pytorch/pull/94729 mainly as a forcing function for implementing joint graph replacements.

Up until now, we had two places to do pattern matching
1) Pre-grad has janky infra (graph not normalized or functional), but is
   desirable for many types of passes where you want your change to
   affect grad formulas.
2) Post-grad has good infra, but cant change grad formulas.

This PR adds a third place to do pattern matching: the joint
forward+backwards graph.  The idea is to take the patterns and lower
them to a joint graph and replace both the forwards+backwards before
we partition them.  This allows us to do something similar to pre-grad
transforms, but run after normalization and functionalization.

Note that we don't seem to have kernels for all of these patterns, some get decomposed in the dispatcher.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
Seems fine to me - I think it's reasonable to add optimizations to the joint graph, although I wonder how many of these would be better done at the pre-dispatch IR level.

**Comment by wconstab** [comment]
@jansel there appears to be a regression here with 'phantom compilations' popping up (dynamo is compiling extra stuff nobody asked for) -- https://github.com/pytorch/pytorch/issues/98778

Also i was attempting earlier to bisect an apparent regression in compile time on the dashboard but it was hard to bisect, this commit was in the 10 commit range between the bad and good, so i wonder about that too.

**Comment by jansel** [comment]
> @jansel there appears to be a regression here with 'phantom compilations' popping up (dynamo is compiling extra stuff nobody asked for) -- #98778
> 
> Also i was attempting earlier to bisect an apparent regression in compile time on the dashboard but it was hard to bisect, this commit was in the 10 commit range between the bad and good, so i wonder about that too.

The extra calls to AotAutograd are intended in this PR.  They should only happen on warmup and when pattern matching triggers.

We should change logging to hide these calls by default.

**Pull request closed without merging**
