### PR TITLE
Remove unnecessary test skip

### PR DESCRIPTION
**Pull request by benjaminglass1**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #134251
* #134344
* #134253
* __->__ #134250

cc @crcrpar @mcarilli @janeyx99

### CODE REVIEW

**Review by amjames — APPROVED** [review]
Always love a purely negative PR. Nice.

**Review by janeyx99 — APPROVED** [review]
woah not sure how it got fixed, do u know?

**Comment by benjaminglass1** [comment]
@janeyx99 I honestly don't know; I just noticed it and figured I should test if it was still relevant while working in the area.

**Pull request closed without merging**
