### PR TITLE
Support privateUser1 key in RNN op. (#118182)

### PR DESCRIPTION
**Pull request by Shan19900305**
Support privateUser1 key in RNN op。

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
seems ok!

**Comment by Shan19900305** [comment]
@bdhirsh pls add a label for this pr, thank you.

**Comment by Shan19900305** [comment]
@bdhirsh pls add a label for this pr, thank you.

**Comment by Shan19900305** [comment]
> seems ok!

pls add a label for this pr, thank you.

**Comment by Shan19900305** [comment]
@ezyang Hi, yang. Pls review this PR, add a label for this PR.  Thank you a lot.

**Comment by Shan19900305** [comment]
> pls add a label for this pr, thank you.

@bdhirsh pls add a label for this pr, thank you.

**Pull request closed without merging**
