### PR TITLE
[pt1][quant] Add the serialization support for FP16 LSTM

### PR DESCRIPTION
**Pull request by jianyuh**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#26378 [WIP][pt1][quant] Add the serialization support for FP16 LSTM**

We would like to add the serialization support for FP16 LSTM.

Differential Revision: [D17391638](https://our.internmc.facebook.com/intern/diff/D17391638/)

### CODE REVIEW

**Review by jamesr66a — APPROVED** [review]
LGTM

**Comment by jamesr66a** [comment]
@jianyuh any chance you could land this soon?

**Comment by jamesr66a** [comment]
Oh I guess it doesn't actually work:

```
Previous return statement returned a value of type Tuple[Tuple[str, int, int, int, bool, bool, float, bool, List[str], Dict[str, List[str]], bool, int, List[Tensor]], List[Tuple[Tensor, Optional[Tensor]]]] but this return statement returns a value of type Tuple[Tuple[str, int, int, int, bool, bool, float, bool, List[str], Dict[str, List[str]], bool, int, List[Tensor]], List[Tensor]]:
at /data/users/jamesreed/fbsource/fbcode/buck-out/dev/gen/deeplearning/projects/fairspeq/tests/fairspeq_model_test_oss#binary,link-tree/torch/nn/quantized/dynamic/modules/rnn.py:199:12

            for i in range(len(self._all_weight_names)):
                dynamic_vals.append(torch.ops.quantized.linear_unpack(self._all_weight_values[i]))

            return vals, dynamic_vals
        else:
            dynamic_vals_fp16 = torch.jit.annotate(List[torch.Tensor], [])
            for i in range(len(self._all_weight_names)):
                dynamic_vals_fp16.append(self._all_weight_values[i])
            return vals, dynamic_vals_fp16
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

**Comment by jianyuh** [comment]
> @jianyuh any chance you could land this soon?

Sorry I just flied back to the Bay Area. The serialization support for FP16 LSTM doesn't work yet. The current PR broke the unit test. Need to check the possible solution for the different return value between FP16 and INT8.

**Comment by jamesr66a** [comment]
@jianyuh can you just switch back to the scheme you had before (duplicating weight values)?

**Comment by jianyuh** [comment]
> @jianyuh can you just switch back to the scheme you had before (duplicating weight values)?

Sure! Will check out that version.

**Comment by jianyuh** [comment]
@jamesr66a : Maybe we should only store the names instead of values for `all_weights`? That is, we use the same `register_buffer` and only use `get_attr` to fetch those buffers? In that way, we avoid the additional `orig_bias_values` for FP16 path.

**Comment by gottbrath** [comment]
Jianyu, James, Dima -- Please discuss and decide if this is in scope for 1.3 or not.

**Comment by gottbrath** [comment]
> Jianyu, James, Dima -- Please discuss and decide if this is in scope for 1.3 or not.

sounds like the conclusion (in discussion elsewhere) is that this isn't in scope for 1.3.

**Pull request closed without merging**
