### PR TITLE
[FSDP] Add `record_function` for explicit prefetching

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105985
* #105984

Example:
Screenshot 2023-07-25 at 7 41 43 PM

This can be particularly help when `with_stack=False`, in which case it is harder to tell the prefetch.

Differential Revision: [D47816318](https://our.internmc.facebook.com/intern/diff/D47816318)

### CODE REVIEW

**Review by fegin — APPROVED** [review]
LGTM

**Comment by awgu** [comment]
Unrelated failure:
[linux-focal-rocm5.6-py3.8 / test (default, 2, 3, linux.rocm.gpu, unstable)](https://hud.pytorch.org/pr/pytorch/pytorch/105985#15345603319)

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D47816318).

**Pull request closed without merging**
