### PR TITLE
Export TensorPipe RPC agent

### PR DESCRIPTION
**Pull request by lw**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #42682 Guard TensorPipe agent by USE_TENSORPIPE
* #42681 Run distributed C++ tests in CircleCI
* #42680 Enroll TensorPipe agent in C++-only E2E test
* #42679 Make TensorPipe agent part of libtorch, not libtorch_python
* #42678 Remove Python dependency from TensorPipe RPC agent
* **#42677 Export TensorPipe RPC agent**

Differential Revision: [D22978713](https://our.internmc.facebook.com/intern/diff/D22978713/)

### CODE REVIEW

**Review by mrshenli — COMMENTED** [review]
Question, why do we need this? I saw `tensorpipe_agent.cpp` is still in `libtorch_python_distributed_sources` (in `build_variables.bzl`), so we don't need to export it from libtorch?

**Comment by lw** [comment]
TBH, I did it because I saw ProcessGroupAgent doing it, but I realize now I didn't have enough context. I was going to make TensorPipeAgent part of libtorch (instead of libtorch_python) in #42679 but it turned out to be more complicated than I thought so that's on hold. I think I may still need it for #42680 but we'll see over there.

**Comment by mrshenli** [comment]
> TBH, I did it because I saw ProcessGroupAgent doing it, but I realize now I didn't have enough context. I was going to make TensorPipeAgent part of libtorch (instead of libtorch_python) in #42679 but it turned out to be more complicated than I thought so that's on hold. I think I may still need it for #42680 but we'll see over there.

`ProcessGroupAgent` does not need TORCH_API either I think. That's my bad. Is the plan to move all agents to libtorch to support C++ use cases?

**Comment by lw** [comment]
ProcessGroupAgent does however have TORCH_API:
https://github.com/pytorch/pytorch/blob/85a00c4c92c2182904868e0796f3642b51b238dd/torch/csrc/distributed/rpc/process_group_agent.h#L60

My current theory is that it is needed in order for the C++-only E2E test to work. That's because we're now building a new additional target in CMake (called process_group_agent) which contains just libtorch, c10d and the source code of the agent. In order to the agent's symbols to be preserved (so that the test binary can find them when it links to it) it must be tagged with TORCH_API. That's my theory, and in order to verify I submitted #42680, which enrolls TP into the E2E tests, _without_ TORCH_API. If that fails, then we have the confirmation of why it is needed.

**Comment by mrshenli** [comment]
I see, that makes sense.

**Comment by lw** [comment]
Oh and I think that in principle it would be nice to have the agents included in libtorch, since they don't have any strict dependency on Python and could thus reasonably be called from C++ (or from TorchScript code executed from a C++ runtime). The current blocker to do that is that the agents depend on c10d, which depends on libtorch, so by including the agents in libtorch we create a circular dependency. In theory, though, c10d just depends on ATen and c10, but our CMake files don't consider them to be separate libraries. We could refactor the CMake files to sort it out but not sure if it's worth it...

**Pull request closed without merging**
