### PR TITLE
Check that PR base is default branch in trymerge.py

### PR DESCRIPTION
**Pull request by kit1980**
I've verified this locally with dry run.

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by bigfootjon** [comment]
This needs to support ghstack, which can be done by also matching against the base ref against `r"base/.*"`

**Comment by kit1980** [comment]
Can the ghstack issue be avoided just by moving the check inside `if not self.is_ghstack_pr():`?
If someone uses ghstack then that person already has write access to the repo...

**Pull request closed without merging**
