### PR TITLE
ci: Remove dead code related to android uploads

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #83930

These uploads actually never got triggeredhappened in nightlies so
removing it altogether. Someone can re-add in the future if they feel
these are important but I can't find an instance of this running since
we migrated so I have a hard time believing anyone will miss it.

https://hud.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=android

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

### CODE REVIEW

**Review by malfet — COMMENTED** [review]
Hmm, I'm not sure I understand why this is a dead code. How do we publish the snapshots then?

**Review by atalman — APPROVED** [review]
Should we revive Android uploads ? We do have manual release process for Android, we want to probably do something about.

**Comment by malfet** [comment]
Do we know at what point those uploads were disabled?

**Review by malfet — CHANGES_REQUESTED** [review]
I think this PR should either point to commit that disabled nightly pushes (with justification), or it should not be merged

**Comment by seemethere** [comment]
> Do we know at what point those uploads were disabled?

Appears as though uploads were disabled the same day they were enabled so they never actually ran.

* https://github.com/pytorch/pytorch/pull/74243 (Enablement PR, March 17, 2022)
* https://github.com/pytorch/pytorch/pull/74355 (Disabling PR, March 17, 2022)

**Comment by seemethere** [comment]
> > Do we know at what point those uploads were disabled?
> 
> Appears as though uploads were disabled the same day they were enabled so they never actually ran.
> 
> * [Move AndroidNightly to GHA #74243](https://github.com/pytorch/pytorch/pull/74243) (Enablement PR, March 17, 2022)
> * [[ci] inline display_ec2 script #74355](https://github.com/pytorch/pytorch/pull/74355) (Disabling PR, March 17, 2022)
> 
> There's no actual justification given in the PR that disabled them but given that they've been disabled for months with no issues I think it's safe to just remove this code especially given the security context

If we want to revive this I suggest we do it in a separate PR where we use an ephemeral runner for this

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
