### PR TITLE
[FSDP2] Added test for N-way TP and 1-way FSDP with CPU offloading

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #127032
* __->__ #127024

This PR shows that we can use FSDP solely for CPU offloading when composing with N-way TP. Each FSDP mesh is just 1 rank.

This was motivated from an ask on Slack :)

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

### CODE REVIEW

**Review by weifengpy — APPROVED** [review]

**Review by wanchaol — APPROVED** [review]
This is, a very interesting use case 🤔

**Comment by atalman** [comment]
Please note, this is constantly failing in CI:
```
2024-05-24T23:04:49.3745925Z FAILED [5.6312s] distributed/_composable/fsdp/test_fully_shard_training.py::TestFullyShard2DTraining::test_tp_with_fsdp_offloading - RuntimeError: Process 0 exited with error code 10 and exception:
2024-05-24T23:04:49.3746036Z Traceback (most recent call last):
2024-05-24T23:04:49.3746546Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 653, in run_test
2024-05-24T23:04:49.3746644Z     getattr(self, test_name)()
2024-05-24T23:04:49.3747141Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 539, in wrapper
2024-05-24T23:04:49.3747223Z     fn()
2024-05-24T23:04:49.3747695Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2756, in wrapper
2024-05-24T23:04:49.3747788Z     method(*args, **kwargs)
2024-05-24T23:04:49.3748279Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 180, in wrapper
2024-05-24T23:04:49.3748372Z     return func(*args, **kwargs)
2024-05-24T23:04:49.3748864Z   File "/var/lib/jenkins/pytorch/test/distributed/_composable/fsdp/test_fully_shard_training.py", line 990, in test_tp_with_fsdp_offloading
2024-05-24T23:04:49.3749024Z     self.assertEqual(loss, ref_loss)
2024-05-24T23:04:49.3749525Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 3646, in assertEqual
2024-05-24T23:04:49.3749630Z     raise error_metas.pop()[0].to_error(
2024-05-24T23:04:49.3749748Z AssertionError: Scalars are not close!
```

Failure can be seen here:
https://hud.pytorch.org/hud/pytorch/pytorch/main/2?per_page=50&name_filter=periodic%20%2F%20linux-focal-rocm6.1-py3.8

**Comment by awgu** [comment]
There seems to be something specific to ROCm + `DTensor`/TP that does not have numeric parity as some existing tests are disabled on ROCm too. Let me disable this test on ROCm and re-run periodic.

**Pull request closed without merging**
