### PR TITLE
[V2] remove undefined tensor from JIT

### PR DESCRIPTION
**Pull request by wanchaol**
stacked on #15450

### CODE REVIEW

**Review by gchanan — COMMENTED** [review]
can you describe what you are trying to accomplish here?  I think I get the long-term plan where TensorList will be Tensor[], optional Tensor will be Tensor? and Tensor?[] will be a list of optional tensors, but what's the actual path to get there?

AFAICT this PR lets you write "Tensor[]" instead  of TensorList, and "Tensor?[]" becomes a nullable TensorList.  Is that right?

At first glance this seems not ideal because we don't have "[]" syntax in native functions so you have to add some hacks to get around that.  Why not either add "[]" syntax first or write "TensorList?" for now until we get "[]" syntax?

**Comment by apaszke** [comment]
We might need to go with a different syntax for lists (`[T]`) or optionals (`optional[T]`) 😕

**Comment by ezyang** [comment]
I'm quite a fan of the Haskell syntax :3

**Comment by apaszke** [comment]
`Maybe T`? 😉

**Comment by wanchaol** [comment]
@gchanan Sorry I was out for a few days and this PR is out of date. Since there're some efforts in unifying the schema between ATen and JIT, `[]` is available in ATen now, so I only need to make this work with `Tensor?[]` for `at::index`(`Tensor?[]` will become List of nullable tensors rather than a nullable TensorList in JIT, that also how it should work for `at::index`). Also the approach I found to remove undefined tensor now is kinda different so I will close this first and submit a separate PR for it. 

@apaszke @ezyang not sure where we get the `?` syntax idea first (probably from Swift?), I like it primarily because it's short and we could wrote something like: `Tensor???????`

**Comment by ezyang** [comment]
> not sure where we get the `?` syntax idea first (probably from Swift?)

I think we independently "invented" it (but that's not saying much: it's been done in many places before). It was that or adding `Optional<Tensor>` or `Maybe Tensor` and nobody wanted to type that lol.

**Pull request closed without merging**
