### PR TITLE
Increase tolearance for reflection pad backward for bfloat16

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #131471

Fixes https://github.com/pytorch/pytorch/issues/131050

### CODE REVIEW

**Comment by isuruf** [comment]
This is due to the decomposition added in https://github.com/pytorch/pytorch/pull/130299.

cc @amjames

**Review by amjames — APPROVED** [review]

**Comment by albanD** [comment]
Why do we raise the tolerance for all platforms when only rocm is problematic ?

**Comment by eqy** [comment]
Are we considering reviving this? Also seeing differences on H100, B200.

**Pull request closed without merging**
