### PR TITLE
turn back on constant folding in fbcode

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108604

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @ngimel

Differential Revision: [D49020794](https://our.internmc.facebook.com/intern/diff/D49020794)

### CODE REVIEW

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D49020794).

**Review by davidberard98 — APPROVED** [review]
oss stamp

**Review by mlazos — APPROVED** [review]

**Pull request closed without merging**
