### PR TITLE
Don't unsafely clone autograd meta

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89720

Addresses this CR comment https://github.com/pytorch/pytorch/pull/88817/files#r1024618045

This appears to fix Dynamo+DDP+hf_BERT test but I don't
know how to make a minimum reproducer.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by soumith — APPROVED** [review]
shipit

**Review by bdhirsh — APPROVED** [review]
thanks!

**Comment by ezyang** [comment]
This breaks MobileBertForMaskedLM. Will need investigating. Recommend adding our debug refactors first before investigating. cc @voznesenskym this is very similar to the bug we investigated over the weekend.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
