### PR TITLE
ns for fx: fix shadow logger errors for resnet18 and mobilenet_v2

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #60419 ns for fx: initial support for int8 shadows fp32
* **#60559 ns for fx: fix shadow logger errors for resnet18 and mobilenet_v2**
* #60311 ns for fx: expose function to add comparisons between logged values
* #60305 ns for fx: rekey results by model node names

Summary:

Adds `resnet18` and `mobilenet_v2` to integration test, and fixes the error to
make creating the shadow model work.  The fixed errors were handling of copying
of nodes with int, float and list<int> arguments, which are present in these models.

Test Plan:

```
python test/test_quantization.py TestFXNumericSuiteCoreAPIsModels.test_resnet18
python test/test_quantization.py TestFXNumericSuiteCoreAPIsModels.test_mobilenet_v2
```

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D29336236](https://our.internmc.facebook.com/intern/diff/D29336236)

### CODE REVIEW

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29336236).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29336236).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29336236).

**Comment by jerryzh168** [comment]
lg, is it possible also to paste the previous error so that we know what error this PR fixes?

**Review by jerryzh168 — APPROVED** [review]

**Comment by vkuzo** [comment]
> lg, is it possible also to paste the previous error so that we know what error this PR fixes?

sure, added more details to the summary

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29336236).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29336236).

**Pull request closed without merging**
