### PR TITLE
[5/x][AMD][Lowering Enablement] Hipifying aoti code_wrapper

### PR DESCRIPTION
**Pull request by zoranzhao**
Summary: as title

Test Plan:
CI & unit test

patch on top of https://www.internalfb.com/phabricator/paste/view/P1214895953 to test

Differential Revision: D56223917

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by chenyang78** [comment]
The test failure looks real.

**Comment by chenyang78** [comment]
Could you also run ```lintrunner -a``` to fix the lint issue? Otherwise, LGTM. Thanks!

**Review by jansel — APPROVED** [review]

**Comment by chenyang78** [comment]
@zoranzhao The test failure "inductor/test_aot_inductor.py::AOTInductorTestABICompatibleCuda::test_output_path_2_abi_compatible_cuda" might be real. Could you take a look? Thanks!

**Review by desertfire — APPROVED** [review]

**Comment by desertfire** [comment]
> @zoranzhao The test failure "inductor/test_aot_inductor.py::AOTInductorTestABICompatibleCuda::test_output_path_2_abi_compatible_cuda" might be real. Could you take a look? Thanks!

Yes, it's a ROCM test, so likely relevant. Also please fix the lint error.

**Pull request closed without merging**
