### PR TITLE
Use packed metadata from triton to reduce launch latency

### LINKED ISSUE #123597: Perf regress across all benchmark suits when cudagraphs is disabled due to triton pin bump
### 🐛 Describe the bug

When bumping triton from old pin (989adb9a29496c22a36ef82ca69cad5dad536b9c), to new pin (45fff310c891f5a92d55445adf8cc9d29df5841e) here https://github.com/pytorch/pytorch/pull/123077 . We found there are perf regression cross all benchmarks suites when cudagraphs is diabled.
- TB -6%
- HF -3%
- TIMM -3%

Dashboard [link](https://hud.pytorch.org/benchmark/compilers?startTime=Mon%2C%2001%20Apr%202024%2022%3A17%3A11%20GMT&stopTime=Mon%2C%2008%20Apr%202024%2022%3A17%3A11%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=gh/shunting314/126/head&lCommit=749bd493418f1acc6c966b908576b09c41aa12ca&rBranch=main&rCommit=6f7dd2f84a4237b31eac29054b86a5284ef6cb6b)

### Error logs

_No response_

### Minified repro

_No response_

### Versions

.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

### PR DESCRIPTION
**Pull request by bertmaher**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #123842
* #123841

https://github.com/openai/triton/pull/3633 converts some kernel launch metadata from a namedtuple to a regular tuple, which is faster to parse.  Using it here shaves off a microsecond or so from the apparently extremely-sensitive launch path.

Fixes #123597

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Review by shunting314 — APPROVED** [review]

**Comment by bertmaher** [comment]
This was merged as 99059affb97a4d69c2c6b82e274f2fefb7ab765b but for some reason pytorchbot did not close the PR 🤷

**Pull request closed without merging**
