### PR TITLE
[nnc] Get rid of fuser trigger counters

### PR DESCRIPTION
**Pull request by bertmaher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#57334**
* #60996

Here's a possibly controversial PR.  These counters got in the way of
generalizing the fuser tests to handle arbitrary devices, and I guess I'm just
generally skeptical that they provide much value.  While true that they let us
observe whether fusion groups were created, we already have assertions based on
the shape of the graph, and I'm not sure that I trust those any less than these
counters.

Differential Revision: [D29471484](https://our.internmc.facebook.com/intern/diff/D29471484/)

Differential Revision: [D29471484](https://our.internmc.facebook.com/intern/diff/D29471484)

### CODE REVIEW

**Comment by bertmaher** [comment]
Also, I just kind of want to minimize the number of random "things" we have laying around.  I feel like our codebase has way too many widgets and knobs and I'd like to pare those back over time.

**Comment by ZolotukhinM** [comment]
I tend to agree, but let's see what other people think before getting another trophy for a dead code society post.

**Comment by ZolotukhinM** [comment]
If we enable cpu fusion everywhere, we probably could get rid of some of the fallback controlling knobs.

**Comment by bertmaher** [comment]
@bertmaher has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29471484).

**Comment by bertmaher** [comment]
These triggers are data races when used from multiple threads, which is maybe not so important except they break TSAN.  While the fix is probably easy-ish, I wanted to delete them anyways just to reduce the amount of "stuff" in our code base.  So, here goes.

**Review by ZolotukhinM — APPROVED** [review]
🚀

**Pull request closed without merging**
