### PR TITLE
fix sgd maximize when momentum is involved

### PR DESCRIPTION
**Pull request by albanD**

### CODE REVIEW

**Review by jbschlosser — COMMENTED** [review]
Negate the grads instead of the learning rate? Seems better - should work with momentum.

Should we have a test for this that uses momentum?

Test failures look real :(

**Comment by albanD** [comment]
Yes they are :D Forgot to keep the -

**Comment by albanD** [comment]
There is already testing btw. And both do reduce the loss so that's why the testing didn't complain.

**Review by jbschlosser — APPROVED** [review]
LGTM!

**Pull request closed without merging**
