### PR TITLE
Back out "[pytorch][PR] Implement Tanh Gelu Approximation" (#5913)

### PR DESCRIPTION
**Pull request by Pythongoras**
Summary:
Pull Request resolved: https://github.com/pytorch/glow/pull/5913

revert D33894937 (https://github.com/pytorch/pytorch/commit/4f8b986e28736b59bc46cd0873a0f36fdaa6f5b8) to unblock f6 build fail

Test Plan: sandcastle

Differential Revision: D34243864

### CODE REVIEW

**Review by jbschlosser — CHANGES_REQUESTED** [review]
Kindly don't revert this, it needs to be in PyTorch 1.11

**Comment by Pythongoras** [comment]
> Kindly don't revert this, it needs to be in PyTorch 1.11

This issue failed the f6 build and will affect downstream users. When the issue is solved we can reland this. Does pytorch side have ETA of fixing this? If it can be fixed in a short time like today we can wait for the fix. Otherwise we have to revert to unblock the f6 build.

**Comment by jbschlosser** [comment]
> > Kindly don't revert this, it needs to be in PyTorch 1.11
> 
> This issue failed the f6 build and will affect downstream users. When the issue is solved we can reland this. Does pytorch side have ETA of fixing this? If it can be fixed in a short time like today we can wait for the fix. Otherwise we have to revert to unblock the f6 build.

Yes we will prioritize the fix for today.

**Comment by albanD** [comment]
> This issue failed the f6 build and will affect downstream users. 

Do you have a repro we can run? That would speed up fixing things.

**Comment by Pythongoras** [comment]
> > This issue failed the f6 build and will affect downstream users.
> 
> Do you have a repro we can run? That would speed up fixing things.

pointer to the failed test: https://fburl.com/code/cn77dnan

**Comment by albanD** [comment]
> pointer to the failed test: https://fburl.com/code/cn77dnan

I meant a repro that is not from internal code.
Hopefully whatever is failing should be able to become a test on this repo to make sure we don't break it again in the future?

**Comment by jbschlosser** [comment]
@Pythongoras we have a fix landing now

**Pull request closed without merging**
