### PR TITLE
Throw error on tensor creation when sequence shape cannot be determined

### LINKED ISSUE #7278: Python segfaults if torch.tensor is called with pandas series slice
## Issue description
Python segfaults if torch.tensor is created from the pandas series slice.

## Code example
```
import torch
import pandas as pd

seq = pd.Series([0.1, 0.2, 0.3])
print(seq)
# outputs:
#0  0.1
#1  0.2
#2  0.3
#dtype: float64

print(torch.tensor(seq))  # OK
# outputs:
#tensor([ 0.1000,  0.2000,  0.3000])

torch.tensor(seq[1:])  # SEGFAULT
```

## System Info
```
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.5
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.14.0)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect
```

## GDB
I can also crash it from the GDB and this is the resulting stacktrace:
```
#0  0x00000000005bee30 in PySequence_Check ()
#1  0x00007fffe88dbcc4 in torch::utils::compute_sizes (seq=0x0)
    at torch/csrc/utils/tensor_new.cpp:90
#2  torch::utils::internal_new_from_data (type=..., device=device@entry=-1, 
    data=data@entry=0x7fffe9f1d6d8, copy_variables=copy_variables@entry=true, 
    copy_numpy=copy_numpy@entry=true, type_inference=true)
    at torch/csrc/utils/tensor_new.cpp:197
#3  0x00007fffe88dd4cd in torch::utils::tensor_ctor (type=..., 
    args=args@entry=0x7ffff7e85be0, kwargs=kwargs@entry=0x0)
    at torch/csrc/utils/tensor_new.cpp:433
#4  0x00007fffe8ce66f8 in torch::autograd::THPVariable_tensor (
    self=<optimized out>, args=0x7ffff7e85be0, kwargs=0x0)
    at torch/csrc/autograd/generated/python_torch_functions.cpp:119
#5  0x00000000004e9ba7 in PyCFunction_Call ()
#6  0x00000000005372f4 in PyEval_EvalFrameEx ()
#7  0x0000000000540199 in ?? ()
#8  0x0000000000540e4f in PyEval_EvalCode ()
#9  0x000000000060c272 in ?? ()
#10 0x000000000046b89f in PyRun_InteractiveOneObject ()
#11 0x000000000046ba48 in PyRun_InteractiveLoopFlags ()
#12 0x000000000046cfa0 in ?? ()
#13 0x00000000004cf2bd in ?? ()
#14 0x00000000004cfeb1 in main ()
```

### PR DESCRIPTION
**Pull request by sethah**
Fixes #7278 

Currently, tensors can be created from Python sequences (determined by `PySequence_Check`). The shape of the tensor to be created is determined by iterating over the first element in each of the (potentially nested) sequences. This is done [here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/tensor_new.cpp#L87). 

There is an assumption that it is safe to index the `PyObect` at element zero if `PySequence_Check(obj)` is true and `PySequence_Length(obj) > 0`. Unfortunately, Python objects are still free to raise errors in their `__getitem__` methods under these conditions, which is often the case when creating tensors from Pandas objects. In this case, `PySequence_GetItem` will return a null pointer, which in turn causes a segmentation fault when the next `PySequence_Check` call is made.

This patch adds a simple check for a null pointer and raises a `ValueError` when this happens. The error trace from the call to `__getitem__` is not propagated since it is generally unhelpful and confusing. A unit test is added that verifies the appropriate error is raised in this situation.

## Examples

```python
seq = pd.Series([1.0, 2.0, 3.0])
torch.Tensor(seq)  # succeeds, since seq[0] is defined
torch.Tensor(seq[1:])  # segfault, since seq[0] generates a KeyError

df = pd.DataFrame(np.ones((2, 3)), columns=['a', 'b', 'c'])
torch.Tensor(df)  # segfault, since df[0] tries to access a column named 0
```

## Notes

* It would be better to be able to handle Pandas objects in general, or at least give a nicer error message (e.g. "did you mean torch.Tensor(df.values)?"), but that code would be specific to checking for Pandas objects.
* I don't believe there's any surefire way to get the first element in the underlying sequence, which is what `PySequence_GetItem(obj, 0)` tries to do, but I could have missed it
* I am new to the code here, so if there is a better way to handle the error, or if the unit test is not quite exhaustive, please let me know.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by soumith** [comment]
thank you @sethah

**Comment by kigenchesire** [comment]
This worked out for me. I was trying to convert a y_train and Y_val into a tensor.

train_labels = torch.tensor(y_train.to_numpy())
val_labels = torch.tensor(y_val.to_numpy())

**Pull request merged**
