### PR TITLE
Fix error message in CUDA forked subprocess

### LINKED ISSUE #1494: Improper error msg when calling Variable.cuda() in forked subprocess
In FloatTensorBase: 

RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

In Variable:
RuntimeError: cuda runtime error (3) : initialization error at /py/conda-bld/pytorch_$SOMENUMBER$/work/torch/lib/THC/generic/THCStorage.c:55

### PR DESCRIPTION
**Pull request by colesbury**
We need to re-call _lazy_init in `_CudaBase.__new__` in the subprocess.

Fixes #1494

### CODE REVIEW

**Review by apaszke — APPROVED** [review]

**Comment by soumith** [comment]
okay jenkins is now fixed.

**Comment by soumith** [comment]
the contbuild caught an issue:

```
AssertionError: TypeError('unbound method _lazy_new() must be called with DoubleTensor instance as first argument (got type instance instead)',) is not an instance of <type 'exceptions.RuntimeError'>
```

**Comment by soumith** [comment]
this gives a segmentation fault now on 2.7:
```
OK
Running cuda tests
test/run_test.sh: line 53: 26175 Segmentation fault      $PYCMD test_cuda.py $@
```

**Comment by colesbury** [comment]
I re-ran the contbuilds. The test_cuda.py segfault was unrelated to this change. I've seen it occasionally in the contbuilds, but I'm not sure what causes it

**Pull request merged**
