### PR TITLE
Added ModuleInfos for {*}Norm modules

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Not adding Lazy variants yet pending investigation of #97915
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #97919

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Looks good!

**Comment by huydhn** [comment]
@mikaylagawarecki @albanD I suspect that this change is causing OOM on periodic slow gradcheck, i.e. https://hud.pytorch.org/pytorch/pytorch/commit/ba6bc5080f9f4ee94c1789ce25e26c941d9ecdad.  Here is the error

```
=================================== FAILURES ===================================
____________ TestModuleCUDA.test_gradgrad_nn_LayerNorm_cuda_float64 ____________
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_modules.py", line 489, in test_gradgrad
    self._test_gradients_helper(device, dtype, module_info, training, gradgradcheck)
  File "/var/lib/jenkins/workspace/test/test_modules.py", line 479, in _test_gradients_helper
    self.assertTrue(check(fn_to_gradcheck, flat_input, nondet_tol=gradcheck_nondet_tol))
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3906, in gradgradcheck
    return torch.autograd.gradgradcheck(fn, inputs, grad_outputs, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1710, in gradgradcheck
    return gradcheck(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1552, in gradcheck
    return _gradcheck_helper(**args)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1566, in _gradcheck_helper
    _gradcheck_real_imag(gradcheck_fn, func, func_out, tupled_inputs, outputs, eps,
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1163, in _gradcheck_real_imag
    gradcheck_fn(func, func_out, tupled_inputs, outputs, eps,
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 1201, in _slow_gradcheck
    numerical = _transpose(_get_numerical_jacobian(func, tupled_inputs_numerical, func_out,
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 223, in _get_numerical_jacobian
    jacobians += [get_numerical_jacobian_wrt_specific_input(fn, inp_idx, inputs, outputs, eps,
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 379, in get_numerical_jacobian_wrt_specific_input
    jacobian_cols[d_idx] = _compute_numerical_jvps_wrt_specific_input(jvp_fn, eps, x.is_complex(), is_forward_ad)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 300, in _compute_numerical_jvps_wrt_specific_input
    ds_dx_tup = jvp_fn(delta[0] if isinstance(delta, tuple) else delta)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 495, in jvp_fn
    return _compute_numerical_gradient(wrapped_fn, input_to_perturb, delta, eps, nbhd_checks_fn)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 289, in _compute_numerical_gradient
    return tuple(compute(a, b) for (a, b) in zip(outa, outb))
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 289, in <genexpr>
    return tuple(compute(a, b) for (a, b) in zip(outa, outb))
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/autograd/gradcheck.py", line 286, in compute
    ret = (b - a) / (2 * norm_v)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 7.43 GiB total capacity; 5.64 GiB already allocated; 13.94 MiB free; 7.01 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

May be we could try a smaller sample size here for slow gradcheck?

**Comment by mikaylagawarecki** [comment]
@huydnn got it, I can decrease the sample input sizes

**Pull request closed without merging**
