### PR TITLE
Update chunk_sharding_spec.py

### LINKED ISSUE #108869: Sharded checkpointing fails on load for certain tensor sizes
### 🐛 Describe the bug

Sharded checkpointing (particularly with FSDP for the optimizer state) uses ChunkShardingSpec to save/load tensors. ChunkShardingSpec's behavior is similar to torch.chunk and will result in some chunks of size 0.

This can be reproduced by trying to save a tensor of size 6 with 4 gpus. This tensor is sharded across the first 3 gpus. The resulting size of the chunks will look like [2, 2, 2, 0]. On save, it seems like ChunkShardingSpec is aware of which gpus contain shards, so it saves the tensor with shard metadata showing the size of chunks to be [2, 2, 2].

The problem occurs when attempting to load the sharded checkpoint. ChunkShardingSpec attempts to rebuild the metadata, this time being unaware of how many gpus originally contained shards. It knows that there is a tensor of size 6 and 4 gpus though, so it generates shard metadata with chunk sizes [2, 2, 2], [skipping the last gpu since it has size 0](https://github.com/pytorch/pytorch/blob/ddbaad6d746d34b56f2d2cc0e02d7e0d0301e626/torch/distributed/_shard/sharding_spec/chunk_sharding_spec.py#L94). Then when attempting to shard the tensor, the 4th gpu has no shard metadata, so a [local_tensor is never created](https://github.com/pytorch/pytorch/blob/ddbaad6d746d34b56f2d2cc0e02d7e0d0301e626/torch/distributed/_shard/sharding_spec/chunk_sharding_spec.py#L165), resulting in an [assertion error on the 4th rank](https://github.com/pytorch/pytorch/blob/ddbaad6d746d34b56f2d2cc0e02d7e0d0301e626/torch/distributed/_shard/sharding_spec/chunk_sharding_spec.py#L172) and a [type error on all other ranks](https://github.com/pytorch/pytorch/blob/ddbaad6d746d34b56f2d2cc0e02d7e0d0301e626/torch/distributed/distributed_c10d.py#L808) because None is contained in the scatter_list.

There are a couple possible solutions to this.
1. Add shardmetadata for all gpus that allow for a tensor to be size 0
2. Change ChunkShardingSpec to distribute a tensor evenly across gpus (e.g. [2, 2, 1, 1] instead of [2, 2, 2, 0])

I've implemented and tested both solutions and both are backwards compatible with previously saved sharded checkpoints on versions 2.0.1, 2.1.0-rc3, and 8/27 nightly (e.g. save on 2.0.1 with the old ChunkShardingSpec and load on 2.0.1 with the new ChunkShardingSpec). Both solutions are also cross-version compatible for 2.0.1->2.1.0-rc3, 2.0.1->8/27 nightly, and 8/27 nightly->2.0.1 (e.g. save on 2.0.1 with the old ChunkShardingSpec and load on 2.1.0 with the new ChunkShardingSpec). The solutions might be version/cross-version compatible for other combinations, but I haven't tested those.

### Versions

This happens with pytorch 2.0.1, 2.1.0-rc3, and 8/27 nightly.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu

### PR DESCRIPTION
**Pull request by b-chu**
Fixes #108869

## 🐛 Describe the bug
Sharded checkpointing (particularly with FSDP for the optimizer state) uses ChunkShardingSpec to save/load tensors. ChunkShardingSpec's behavior is similar to torch.chunk and will result in some chunks of size 0.

This can be reproduced by trying to save a tensor of size 6 with 4 gpus. This tensor is sharded across the first 3 gpus. The resulting size of the chunks will look like [2, 2, 2, 0]. On save, it seems like ChunkShardingSpec is aware of which gpus contain shards, so it saves the tensor with shard metadata showing the size of chunks to be [2, 2, 2].

The problem occurs when attempting to load the sharded checkpoint. ChunkShardingSpec attempts to rebuild the metadata, this time being unaware of how many gpus originally contained shards. It knows that there is a tensor of size 6 and 4 gpus though, so it generates shard metadata with chunk sizes [2, 2, 2], [skipping the last gpu since it has size 0](https://github.com/pytorch/pytorch/blob/ddbaad6d746d34b56f2d2cc0e02d7e0d0301e626/torch/distributed/_shard/sharding_spec/chunk_sharding_spec.py#L94). Then when attempting to shard the tensor, the 4th gpu has no shard metadata, so a [local_tensor is never created](https://github.com/pytorch/pytorch/blob/ddbaad6d746d34b56f2d2cc0e02d7e0d0301e626/torch/distributed/_shard/sharding_spec/chunk_sharding_spec.py#L165), resulting in an [assertion error on the 4th rank](https://github.com/pytorch/pytorch/blob/ddbaad6d746d34b56f2d2cc0e02d7e0d0301e626/torch/distributed/_shard/sharding_spec/chunk_sharding_spec.py#L172) and a [type error on all other ranks](https://github.com/pytorch/pytorch/blob/ddbaad6d746d34b56f2d2cc0e02d7e0d0301e626/torch/distributed/distributed_c10d.py#L808) because None is contained in the scatter_list.

## Fix
This implements a fix by adding a ShardMetadata for all GPUs during saving and allows for a tensor to be size 0. So that checkpoint loading would not fail. 

## Testcase
Testcase is added in https://github.com/pytorch/pytorch/pull/109626.

### CODE REVIEW

**Comment by fduwjj** [comment]
Thanks for you contribution. I think for distributed checkpointing we are moving away from ShardedTensor now. We might not need to fix ShardedTensor now.

**Comment by wz337** [comment]
> Thanks for you contribution. I think for distributed checkpointing we are moving away from ShardedTensor now. We might not need to fix ShardedTensor now.

The fix looks good to me. Do we still want to approve it to temporarily unblock? 

Based on our proposal, FSDP(process_group) would still use ShardedTensor. So we might still want to land this fix.

**Review by wanchaol — APPROVED** [review]
lgtm. consider we still need to maintain ShardedTensor for a while, stamp to unblock

**Review by wz337 — APPROVED** [review]
LGTM! Thanks for your contribution.

**Comment by b-chu** [comment]
@wanchaol @wz337 Can we include this bug fix in the 2.1.0 release to fix sharded checkpoint loading for the scenarios mentioned in #108869?

**Comment by wz337** [comment]
> @wanchaol @wz337 Can we include this bug fix in the 2.1.0 release to fix sharded checkpoint loading for the scenarios mentioned in #108869?

@b-chu 
I think you could still submit a cherry pick PR to the release branch, as it can be categorized as 'crashes'. You can follow the cherry-pick process and submit your branch to the release branch. Please see this post here.

**Comment by wz337** [comment]
@b-chu Hey Brian, I talked to PT Dev Infra and I can only include this in 2.1.1, as this is not a regression from 2.0 to 2.1.  So that this won't be in the release in mid-October, but it will be in 2.1.1 in November.

**Comment by b-chu** [comment]
Thanks!

**Pull request closed without merging**
