### PR TITLE
[c10d] Move class definition of DebugInfoWriter to TraceUtil as well

### PR DESCRIPTION
**Pull request by fduwjj**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #114926
* __->__ #114901

Since we moved the implementation of the class to TraceUtils in https://github.com/pytorch/pytorch/pull/114367, maybe we also want to move the implementation here as well.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @wz337 @tianyu-l @wconstab @yf225 @kiukchung @d4l3k @lucasllc

### CODE REVIEW

**Review by XilunWu — APPROVED** [review]
lgtm!

**Comment by malfet** [comment]
@fduwjj are those headers supposed to be used by an extensions or are they implementation details of c10d?

**Comment by xwang233** [comment]
I tried adding `inline` to all these DebugInfoWriter implementations (on top of this PR before revert) and that worked for both pytorch and our extension builds. 
https://github.com/pytorch/pytorch/blob/926939ef1215e080f00b73e1a7fd6fb47fa384c9/torch/csrc/distributed/c10d/TraceUtils.h#L284-L293

cc @malfet

**Comment by fduwjj** [comment]
@malfet I am curious what is your suggestions on how should I approach or move the definition of class to?

**Comment by malfet** [comment]
@fduwjj I think there is a difference between moving class definition to a header and moving class implementation there (and this is what those compilation errors are about)

**Comment by fduwjj** [comment]
@malfet the thing is that the implementation of that class has been moved to that file first and then I moved the definition. That's why I want to learn what would be the recommended way to handle this case down the road.

**Pull request closed without merging**
