### PR TITLE
add Half support for bernoulli on CPU

### PR DESCRIPTION
**Pull request by CaoE**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #104178
* #104177
* __->__ #104176

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @ngimel

### CODE REVIEW

**Review by mingfeima — APPROVED** [review]

**Comment by CaoE** [comment]
@kulinseth Could you please review this PR ? Thanks.

**Comment by CaoE** [comment]
@ngimel Could you please review this PR ? Thanks.

**Comment by CaoE** [comment]
@kulinseth Could you please review this PR ? Thanks.

**Comment by CaoE** [comment]
@kulinseth Could you please review this PR ? Thanks.

**Comment by CaoE** [comment]
@cpuhrsch Could you please review this PR ? Thanks.

**Review by cpuhrsch — APPROVED** [review]

**Comment by cpuhrsch** [comment]
Can't be merged until lint issues were resolved

**Comment by CaoE** [comment]
@cpuhrsch Thanks for your review. I will rebase the stack to try to solve lint issues.

**Pull request closed without merging**
