### PR TITLE
Enable UFMT on `test/test_fake_tensor.py`, `test/test_flop_counter.py` and some files

### PR DESCRIPTION
**Pull request by shink**
Part of: #123062 

Ran lintrunner on:

- test/test_fake_tensor.py
- test/test_flop_counter.py
- test/test_function_schema.py
- test/test_functional_autograd_benchmark.py
- test/test_functional_optim.py
- test/test_functionalization_of_rng_ops.py

Detail:

```bash
$ lintrunner -a --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM if CI is green

**Comment by shink** [comment]
fixed the wrong location of noqa

```diff
diff --git a/test/test_fake_tensor.py b/test/test_fake_tensor.py
index 8e05e843c8..38b6886016 100644
--- a/test/test_fake_tensor.py
+++ b/test/test_fake_tensor.py
@@ -1034,8 +1034,8 @@ class FakeTensorOpInfoTest(TestCase):
 make_propagate_real_tensors_cls(FakeTensorOpInfoTest)
 instantiate_device_type_tests(FakeTensorOpInfoTest, globals(), only_for=("cpu", "cuda"))
 instantiate_device_type_tests(
-    PropagateRealTensorsFakeTensorOpInfoTest, globals(), only_for=("cpu",)
-)  # noqa: F821
+    PropagateRealTensorsFakeTensorOpInfoTest, globals(), only_for=("cpu",)  # noqa: F821
+)
```

see: https://github.com/pytorch/pytorch/pull/125747/commits/1f984b7fe980d3be96efbe09b87483e5f519bcc0

**Comment by shink** [comment]
@ezyang Please have a look. Thanks so much.

**Comment by ezyang** [comment]
diff is

```
diff --git b/test/test_fake_tensor.py a/test/test_fake_tensor.py
index 8e05e843c8a..38b6886016e 100644
--- b/test/test_fake_tensor.py
+++ a/test/test_fake_tensor.py
@@ -1034,8 +1034,8 @@ class FakeTensorOpInfoTest(TestCase):
 make_propagate_real_tensors_cls(FakeTensorOpInfoTest)
 instantiate_device_type_tests(FakeTensorOpInfoTest, globals(), only_for=("cpu", "cuda"))
 instantiate_device_type_tests(
-    PropagateRealTensorsFakeTensorOpInfoTest, globals(), only_for=("cpu",)
-)  # noqa: F821
+    PropagateRealTensorsFakeTensorOpInfoTest, globals(), only_for=("cpu",)  # noqa: F821
+)
 
 
 class FakeTensorConverterTest(TestCase):

```

**Pull request closed without merging**
