### PR TITLE
[Inductor] remove GPT2ForSequenceClassification from ci skip list

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #112100

**Summary**
As discussed in https://github.com/pytorch/pytorch/issues/109019, the accuracy issue of `GPT2ForSequenceClassification` has been fixed in https://github.com/pytorch/pytorch/pull/108690. Remove it from CI Skip list.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by lezcano — APPROVED** [review]

**Comment by lezcano** [comment]
GPT2ForSequenceClassification still fails accuracy on CI?

**Comment by leslie-fang-intel** [comment]
> GPT2ForSequenceClassification still fails accuracy on CI?

Yean, it passes in my local system. Not sure the difference yet.

**Comment by leslie-fang-intel** [comment]
After rebasing to master, `GPT2ForSequenceClassification` pass the accuracy check now.

**Pull request closed without merging**
