### PR TITLE
[core IR] Add decompositions for _assert_async to no-op

### PR DESCRIPTION
**Pull request by SS-JIA**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #109905

## Context

`aten._assert_async` and `aten._assert_async.msg` were introduced based on https://github.com/pytorch/pytorch/issues/36853 to allow asynchronous assert behaviour when using CUDA tensors.

> It's common to use assertion to check pre-conditions or unexpected inputs in code, as a form of defensive programming. For example, sometimes we want to assert that all elements of a tensor is all positive, or finite.
>
> However, doing assert in python has the following problems in pytorch:
>
> * when dealing with cuda tensors, using python's assert (t>0).all() or assert torch.isfinite(t).all() will wait for results of the cuda kernel and most if not all its preceding kernel launches, thus potentially cause significantly slow down.
> * It would be good to have a way to execute an assert as an async call.
> * It does not work nicely with tracing or FX, because it is considered as control logic

However, when considering ops to preserve during export, these ops are a strange case:

* They are quite narrow in scope; only being relevant for graphs that expect to work with CUDA inputs
  * i.e. these operators are not generic; in the context of the core ATen decomposition table, it would then make sense for it to remove these ops
* Was speaking to @SherlockNoMad and he expected these to be removed by functionalization anyway.
* As outlined in the original comment, assertions were considered "control logic" and thus does not play well with tracing/FX. Implementing assertions as a torch op is a way to circumvent that issue but the original point still stands imo
  * Personally I would think that input checking should be the responsibility of the implementation of individual operators

## Motivation

The premise of these changes is that when exporting a graph that uses `aten._assert_async`, export should remove these ops by default mainly due to the below point

> * As outlined in the original comment, assertions were considered "control logic" and thus does not play well with tracing/FX. Implementing assertions as a torch op is a way to circumvent that issue but the original point still stands imo
>    * Personally I would think that input checking should be the responsibility of the implementation of individual operators

I'm not certain if this premise is correct. Please let me know if you disagree.

## Changes

This PR adds decompositions of `aten._assert_async` and `aten._functional_assert_async.msg` to no-op and adds the decomp to the core ATen decomposition table. The assumption is that most export workflows will not want to preserve these operators due to the stated premise.

In fact Inductor already added these decomps so I am essentially moving them to the more general `decompositions.py` location, and removing the existing Inductor decomps as they are now superfluous.

Please let me know if there is a better approach to remove these operators.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @Xia-Weiwen

### CODE REVIEW

**Comment by peterbell10** [comment]
>They are quite narrow in scope; only being relevant for graphs that expect to work with CUDA inputs

There is a CPU implementation for `_assert_async`.

> Was speaking to @SherlockNoMad and he expected these to be removed by functionalization anyway.

This doesn't seem to be the case, I see `aten._assert_async` being preserved in functionalized graphs.

> As outlined in the original comment, assertions were considered "control logic" and thus does not play well with tracing/FX. Implementing assertions as a torch op is a way to circumvent that issue but the original point still stands imo

While Assertions are technically control flow, in the `False` case we just throw an error and it isn't expected to be handled elegantly.

> Personally I would think that input checking should be the responsibility of the implementation of individual operators

`_assert_async` is for data-dependent assertions so it's impossible to implement in the meta implementation.

**Comment by SS-JIA** [comment]
> There is a CPU implementation for `_assert_async.`

While that's true, what I meant was more that using the op in the first place implies that the model expects CUDA inputs. If you expect your model to only work with CPU tensors, you probably won't use the `_assert_async` op (might be wrong about this, since you may also just want your asserts to be preserved after tracing).

> `_assert_async` is for data-dependent assertions so it's impossible to implement in the meta implementation.

My understanding is that the meta implementations are only during export. I was more referring to the runtime implementation of individual operators (e.g. ATen implementations).

>  in the False case we just throw an error and it isn't expected to be handled elegantly so the compiler only needs to deal with the "happy path".

What I'm curious about is if this is an expectation that can be generalized to the overall export workflow; what are the situations where folks want to preserve `_assert_async`?

**Comment by peterbell10** [comment]
> While that's true, what I meant was more that using the op in the first place implies that the model expects CUDA inputs. If you expect your model to only work with CPU tensors, you probably won't use the _assert_async op

`_assert_async` is what dynamo generates when you write a data-dependent `assert` in your python code, e.g.

```python
def fn(x):
    assert x.isfinite().all()
    return x * x
```

generates the dynamo graph, regardless of device being used
```python
def forward(self, L_x_ : torch.Tensor):
     l_x_ = L_x_
     
     # File: <ipython-input-2-e6a7009c79f6>:9, code: assert x.isfinite().all()
     isfinite = l_x_.isfinite()
     all_1 = isfinite.all();  isfinite = None
     _assert_async = torch._assert_async(all_1, 'assertion error');  all_1 = None
     
     # File: <ipython-input-2-e6a7009c79f6>:10, code: return x * x
     mul = l_x_ * l_x_;  l_x_ = None
     return (mul,)
```

> My understanding is that the meta implementations are only during export. I was more referring to the runtime implementation of individual operators (e.g. ATen implementations).

Well what should you do when the ATen operator that had the assertion gets decomposed? We don't want every function that has a runtime check to become a core operator.

**Comment by SS-JIA** [comment]
> `_assert_async` is what dynamo generates when you write a data-dependent assert in your python code

Ah, I see. Thanks for the context. I thought this was an op that would have to be used directly by the user in order to show up in the resulting graph.

> Well what should you do when the ATen operator that had the assertion gets decomposed? We don't want every function that has a runtime check to become a core operator.

My line of thought is that a decomposition should preserve the behaviour of the operator being decomposed. The operators contained in the decomposition should themselves be checking for a valid input. The set of inputs accepted by the overall decomposition should contain the set of inputs accepted by the original operator, otherwise it wouldn't be a valid decomposition.

In any case, it appears that these asserts are something that should be preserved by default. I'm proposing that we keep the decompositions added by this PR, but avoid adding them to the core ATen decomposition table. They can be included in specific decomposition tables (e.g. Inductor) wherever they are relevant.

**Comment by kimishpatel** [comment]
@peterbell10 why is it that inductor turns this assert into a no-op? And are you saying that, doing the same fore core aten is not valid because inductor is a specific backend that is making its own choices, but "core aten" is a stronger contract where "no-op" decomp for assert is not right?

**Comment by peterbell10** [comment]
@kimishpatel this is a temporary workaround, as you can see by the comment on the decomposition:
https://github.com/pytorch/pytorch/blob/5f6216b12cb1972acddefcfcb0c1a46d759bff9b/torch/_inductor/decomposition.py#L84-L85

I don't think there's any reason inductor wouldn't want to support `_assert_async` moving forward, it's just not a high priority at the moment.  

> And are you saying that, doing the same fore core aten is not valid because inductor is a specific backend that is making its own choices, but "core aten" is a stronger contract where "no-op" decomp for assert is not right?

Yes. If the goal is to capture the behavior of the original python program then this isn't a valid decomposition. It would be reasonable as an opt-in optimization, or workaround for lack of support in a particular backend.

**Comment by kimishpatel** [comment]
> @kimishpatel this is a temporary workaround, as you can see by the comment on the decomposition:
> 
> https://github.com/pytorch/pytorch/blob/5f6216b12cb1972acddefcfcb0c1a46d759bff9b/torch/_inductor/decomposition.py#L84-L85
> 
> I don't think there's any reason inductor wouldn't want to support `_assert_async` moving forward, it's just not a high priority at the moment.
> 
> > And are you saying that, doing the same fore core aten is not valid because inductor is a specific backend that is making its own choices, but "core aten" is a stronger contract where "no-op" decomp for assert is not right?
> 
> Yes. If the goal is to capture the behavior of the original python program then this isn't a valid decomposition. It would be reasonable as an opt-in optimization, or workaround for lack of support in a particular backend.

How does this relate to guards? @avikchaudhuri and Yanan (I forgot your gh handle) any inputs?

**Pull request closed without merging**
