### PR TITLE
[v1.4.0] Fix reading `__cuda_array_interface__` without strides

### PR DESCRIPTION
**Pull request by leofang**
Backport of #24947.

### CODE REVIEW

**Comment by leofang** [comment]
cc: @beam2d @awthomp

**Comment by beam2d** [comment]
Thank you for backporting! It looks good to me.

**Comment by leofang** [comment]
Thanks, @beam2d! Btw, sorry that I wasn’t able to preserve the commit history. I know nothing about PyTorch’s codebase, so I wasn’t able to resolve conflicts during cherry-picking.

**Comment by beam2d** [comment]
No problem :)

**Comment by gchanan** [comment]
I would kind of prefer to have the new protocol bake for a bit and just do a backport of the actual fix in 1.4.  Which brings up a point I missed in the previous PR -- with all the discussion of the new protocol we don't actually check that this fixed the bug we were intending to fix.

**Comment by gchanan** [comment]
Also it doesn't look like we even test numba because of version issues.

**Comment by gchanan** [comment]
ok I filed https://github.com/pytorch/pytorch/issues/31443 for a test -- from what I can tell, we don't actually test numba in CI right now -- see https://github.com/pytorch/pytorch/pull/31435.

**Comment by gchanan** [comment]
So instead of trying to fix everything, it's probably best to just merge this.

**Comment by leofang** [comment]
Thanks, @gchanan. The fix was tested and confirmed valid in https://github.com/cupy/cupy/issues/2589#issuecomment-562672084.

**Comment by leofang** [comment]
Seems to be superseded by #31450. Close this.

**Pull request closed without merging**
