### PR TITLE
Fixing MPS conv1d error message for output 2**16

### LINKED ISSUE #134416: `PYTORCH_ENABLE_MPS_FALLBACK` does not appear to work for `nn.Conv1d`
### 🐛 Describe the bug

It looks like #129207 addressed an issue with the MPS implementation of `nn.Conv1d`. Specifically: The implementation would silently return incorrect results when running a convolution with more than 65536 channels. In the issue, the fix was to temporarily have `nn.Conv1d` throw `NotImplementedError` in this situation and to suggest using `PYTORCH_ENABLE_MPS_FALLBACK = 1` so that the operation could fall back to the CPU.

However, it seems like this fallback does not work. Trying to run the linked issue's minimal example (slightly trimmed down) causes an error regardless if `PYTORCH_ENABLE_MPS_FALLBACK` is set or not:

```py
# in main.py
import torch
import torch.nn as nn
import os

print(os.environ["PYTORCH_ENABLE_MPS_FALLBACK"]) # Prints 1, assuming the variable is set

torch.manual_seed(0)
conv = nn.Conv1d(1, 65537, 3, padding=1)

x = torch.ones([1, 1, 3])
y_mps = conv.to("mps")(x.to("mps")) # Fails with NotImplementedError
```

Run with something like `PYTORCH_ENABLE_MPS_FALLBACK=1 python3.11 main.py`

Attempting to run this code always fails with the following, even when `PYTORCH_ENABLE_MPS_FALLBACK` is set to 1:
```
Traceback (most recent call last):
  File "[path to main.py]", line 13, in <module>
    y_mps = conv.to("mps")(x.to("mps"))  # Fails with NotImplementedError
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 373, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 368, in _conv_forward
    return F.conv1d(
           ^^^^^^^^^
NotImplementedError: Output channels > 65536 not supported at the MPS device. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

```

### Versions

Collecting environment information...
PyTorch version: 2.5.0.dev20240824
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.29.0
Libc version: N/A

Python version: 3.11.5 (main, Aug 24 2023, 15:09:32) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==2.1.0
[pip3] torch==2.5.0.dev20240824
[pip3] torchaudio==2.4.0.dev20240824
[pip3] torchsde==0.2.6
[pip3] torchvision==0.20.0.dev20240824
[conda] Could not collect

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

### PR DESCRIPTION
**Pull request by jhavukainen**
Fixes #134416 by removing the misleading message.

### CODE REVIEW

**Review by hvaara — COMMENTED** [review]
https://github.com/pytorch/pytorch/pull/134770/files#diff-2b02a4fc9ee55c0e5e6c3ca50de5211843685b34b7f3fd709710b09504ccca78L381-L387

Should this be updated as well?

edit: Reviewed on mobile. Not sure why the code snippet didn't get included.

**Comment by qqaatw** [comment]
Another approach would be emitting a one-time warning and re-dispatch to cpu here :)

**Comment by hvaara** [comment]
> Another approach would be emitting a one-time warning and re-dispatch to cpu here :)

I like this option. This is what I was going to do. It's actually quite easy to do in `aten/src/ATen/native/Convolution.cpp`.

**Comment by jhavukainen** [comment]
> https://github.com/pytorch/pytorch/pull/134770/files#diff-2b02a4fc9ee55c0e5e6c3ca50de5211843685b34b7f3fd709710b09504ccca78L381-L387
> 
> Should this be updated as well?
> 
> edit: Reviewed on mobile. Not sure why the code snippet didn't get included.

Yeah that as well. Updated the PR so we can close the original issue of misleading error message while the work for a proper workaround happens.

> I like this option. This is what I was going to do. It's actually quite easy to do in aten/src/ATen/native/Convolution.cpp.

That sounds good to me. Let me know if you'd still like to make a PR for that. Otherwise I'll add it to my todo list.

**Comment by hvaara** [comment]
> That sounds good to me. Let me know if you'd still like to make a PR for that. Otherwise I'll add it to my todo list.

I don't want to add to your workload if you're busy. Current solution proposed in this PR also LGTM. I can make a quick attempt and we can see if special casing is a solution we want to move forward with.

**Review by malfet — APPROVED** [review]
LGTM

**Pull request closed without merging**
