### PR TITLE
Make use of our S3 mirror if Yann Lecunn's website is not accessible

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#34215 Make use of our S3 mirror if Yann Lecunn's website is not accessible**

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D20251538](https://our.internmc.facebook.com/intern/diff/D20251538)

### CODE REVIEW

**Comment by ezyang** [comment]
@malfet I'm putting this up in case the Docker changes get blocked for some reason. Happy to discard this if the Docker stuff works.

**Review by mrshenli — APPROVED** [review]
Question: how do we upload resources to `https://ossci-datasets.s3.amazonaws.com/mnist/`? Is it done manually?

**Comment by ezyang** [comment]
Yes, it's done manually by people with S3 accounts. I can set you up, if you like.

**Comment by malfet** [comment]
@ezyang  can you make similar change to https://github.com/pytorch/examples/blob/master/cpp/tools/download_mnist.py

**Comment by ezyang** [comment]
...whyyyy do we have two copies of this script

**Comment by ezyang** [comment]
@malfet this is in the examples/ repo and I don't think we exercise it in our CI

**Review by malfet — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
