### PR TITLE
Implement NetDef <--> JIT IR converters.

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Currently the converters are very straightforward, i.e. there is no code for trying to
preserve semantics, we're purely perform conversion from one format to another.

Two things that we might want to add/change:
1. Add semantic conversion as well (but probably it would be a good idea to keep
it separate as a temporary thing).
2. Make sure we don't mess with value names, as they are crucial for current
uses of NetDefs.

### CODE REVIEW

**Review by zdevito — APPROVED** [review]
Looks good to me. Doesn't seem like any control-flow style operators will translate correctly, but there are errors that will get emitted to that effect in the code.

**Comment by ZolotukhinM** [comment]
I hope that we transfer everything to JIT IR before the need to convert models with control flow emerges :)

**Comment by ezyang** [comment]
Broke mac buidls

```
Feb 13 18:53:46 ../torch/csrc/jit/netdef_converter.cpp:51:29: error: no viable conversion from 'vector<long>' to 'vector<long long>'
Feb 13 18:53:46       node->is_(attrSymbol, is);
Feb 13 18:53:46                             ^~
Feb 13 18:53:46 /Applications/Xcode-9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:530:5: note: candidate constructor not viable: no known conversion from 'std::vector<long>' to 'initializer_list<value_type>' (aka 'initializer_list<long long>') for 1st argument
Feb 13 18:53:46     vector(initializer_list<value_type> __il);
Feb 13 18:53:46     ^
```

**Comment by ZolotukhinM** [comment]
Thanks for letting me know @ezyang !

**Comment by ZolotukhinM** [comment]
Submitted a new fixed PR17123.

**Pull request closed without merging**
