### PR TITLE
[jit] fix alias annotations on to, cpu, cuda

### PR DESCRIPTION
**Pull request by suo**
Fix alias annotations for ops that may return a fresh tensor. The previous version was overly conservative.

Currently there is no actual behavior change in the alias analysis, but we may use the information in the future.

### CODE REVIEW

**Review by eellison — APPROVED** [review]
Just to make sure I'm understanding this correctly - 

the logic is - we can safely ignore "b" annotation, because the aliasing will already be preserved by "a" annotation.

Edit:
What about the following case: 

a = torch.zeros([2, 2])
b = a[0]
c = a[0]

Don't we need torch.zeros() to produce a new set so that the alias sets of b & c are linked?

**Review by eellison — CHANGES_REQUESTED** [review]
Don't know how to revert my accept, so requesting changes to make sure I understand fully before we land

**Comment by suo** [comment]
That case is covered in the code above, where we assign a fresh alias to any non-annotated output. So the schema for zeroes looks like `aten::zeroes(…) -> Tensor`. But I added some comments and accounted for the case where we use a fresh annotation instead of no annotation, just in case.

**Review by eellison — APPROVED** [review]

**Comment by eellison** [comment]
Looks good, maybe add test if you see applicable

**Pull request closed without merging**
