### PR TITLE
Fix torch distributed docs ext

### LINKED ISSUE #112641: Fix docstring errors in post_localSGD_optimizer.py, functional_sgd.py, _functional_collectives.py, optimizer.py, utils.py, api.py, server_process_global_profiler.py, functions.py, backend_registry.py, __init__.py, options.py, internal.py, functional_adam.py
Please fix the following issues. To test locally, run: 
 ```
pydocstyle path-to-file --count
```
Run this command before and after fixing the errors. This command prints out the number of errors at the end of the output. Paste the output to your PR description with the number before and after. 
- **File**: `torch/distributed/_functional_collectives.py`, **Entity**: `AsyncCollectiveTensor`, **Line**: 155, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/distributed/_functional_collectives.py`, **Entity**: `AsyncCollectiveTensor`, **Line**: 155, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/_functional_collectives.py`, **Entity**: `AsyncCollectiveTensor`, **Line**: 155, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/_functional_collectives.py`, **Entity**: `all_reduce`, **Line**: 418, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/_functional_collectives.py`, **Entity**: `all_reduce`, **Line**: 418, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/_functional_collectives.py`, **Entity**: `reduce_scatter_tensor`, **Line**: 477, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/_functional_collectives.py`, **Entity**: `reduce_scatter_tensor`, **Line**: 477, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/_functional_collectives.py`, **Entity**: `all_reduce_coalesced`, **Line**: 506, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/_functional_collectives.py`, **Entity**: `all_reduce_coalesced`, **Line**: 506, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/_functional_collectives.py`, **Entity**: `reduce_scatter_tensor_coalesced`, **Line**: 556, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/_functional_collectives.py`, **Entity**: `reduce_scatter_tensor_coalesced`, **Line**: 556, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/autograd/__init__.py`, **Entity**: `context`, **Line**: 30, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/distributed/autograd/__init__.py`, **Entity**: `context`, **Line**: 30, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/autograd/__init__.py`, **Entity**: `context`, **Line**: 30, **Description**: Use """triple double quotes""" (found '''-quotes)
- **File**: `torch/distributed/autograd/__init__.py`, **Entity**: `context`, **Line**: 30, **Description**: First line should end with a period (not 'g')
- **File**: `torch/distributed/rpc/functions.py`, **Entity**: `async_execution`, **Line**: 5, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/functions.py`, **Entity**: `async_execution`, **Line**: 5, **Description**: First line should end with a period (not 'n')
- **File**: `torch/distributed/rpc/functions.py`, **Entity**: `async_execution`, **Line**: 5, **Description**: First line should be in imperative mood; try rephrasing (found 'A')
- **File**: `torch/distributed/rpc/server_process_global_profiler.py`, **Entity**: `_server_process_global_profile`, **Line**: 17, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/server_process_global_profiler.py`, **Entity**: `_server_process_global_profile`, **Line**: 17, **Description**: First line should end with a period (not ',')
- **File**: `torch/distributed/rpc/server_process_global_profiler.py`, **Entity**: `__enter__`, **Line**: 102, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/server_process_global_profiler.py`, **Entity**: `__exit__`, **Line**: 130, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/backend_registry.py`, **Entity**: `backend_registered`, **Line**: 44, **Description**: First line should be in imperative mood (perhaps 'Check', not 'Checks')
- **File**: `torch/distributed/rpc/backend_registry.py`, **Entity**: `register_backend`, **Line**: 59, **Description**: First line should be in imperative mood (perhaps 'Register', not 'Registers')
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_InternalRPCPickler`, **Line**: 31, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_InternalRPCPickler`, **Line**: 31, **Description**: First line should end with a period (not 'e')
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_script_module_receiver`, **Line**: 77, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_script_module_receiver`, **Line**: 77, **Description**: First line should end with a period (not ',')
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_script_module_reducer`, **Line**: 86, **Description**: One-line docstring should fit on one line with quotes (found 3)
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_script_module_reducer`, **Line**: 86, **Description**: First line should be in imperative mood (perhaps 'Serialize', not 'Serializes')
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `serialize`, **Line**: 94, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `serialize`, **Line**: 94, **Description**: First line should end with a period (not 'o')
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `deserialize`, **Line**: 147, **Description**: One-line docstring should fit on one line with quotes (found 3)
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `deserialize`, **Line**: 147, **Description**: First line should end with a period (not 'j')
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_run_function`, **Line**: 197, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_run_function`, **Line**: 197, **Description**: First line should be in imperative mood; try rephrasing (found 'This')
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_build_rpc_profiling_key`, **Line**: 240, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_build_rpc_profiling_key`, **Line**: 240, **Description**: First line should be in imperative mood (perhaps 'Build', not 'Builds')
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_start_record_function`, **Line**: 263, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_start_record_function`, **Line**: 263, **Description**: First line should end with a period (not 'a')
- **File**: `torch/distributed/rpc/internal.py`, **Entity**: `_start_record_function`, **Line**: 263, **Description**: First line should be in imperative mood; try rephrasing (found 'This')
- **File**: `torch/distributed/rpc/options.py`, **Entity**: `TensorPipeRpcBackendOptions`, **Line**: 44, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/options.py`, **Entity**: `TensorPipeRpcBackendOptions`, **Line**: 44, **Description**: First line should end with a period (not 'r')
- **File**: `torch/distributed/rpc/options.py`, **Entity**: `set_device_map`, **Line**: 105, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/options.py`, **Entity**: `set_device_map`, **Line**: 105, **Description**: First line should end with a period (not 's')
- **File**: `torch/distributed/rpc/options.py`, **Entity**: `set_devices`, **Line**: 163, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/options.py`, **Entity**: `set_devices`, **Line**: 163, **Description**: First line should end with a period (not 'g')
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `_use_rpc_pickler`, **Line**: 63, **Description**: One-line docstring should fit on one line with quotes (found 3)
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `_use_rpc_pickler`, **Line**: 63, **Description**: First line should end with a period (not 'r')
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `_wait_all`, **Line**: 153, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `_wait_all`, **Line**: 153, **Description**: First line should end with a period (not 'd')
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `_wait_all`, **Line**: 153, **Description**: First line should be in imperative mood; try rephrasing (found 'A')
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `_all_gather`, **Line**: 182, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `_all_gather`, **Line**: 182, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `_all_gather`, **Line**: 182, **Description**: First line should be in imperative mood; try rephrasing (found 'This')
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `_barrier`, **Line**: 272, **Description**: First line should be in imperative mood (perhaps 'Synchronize', not 'Synchronizes')
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `_wait_all_workers`, **Line**: 292, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `_wait_all_workers`, **Line**: 292, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `shutdown`, **Line**: 310, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `shutdown`, **Line**: 310, **Description**: First line should end with a period (not 's')
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `get_worker_info`, **Line**: 405, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `remote`, **Line**: 524, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `remote`, **Line**: 524, **Description**: First line should end with a period (not 'n')
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `rpc_sync`, **Line**: 740, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `rpc_sync`, **Line**: 740, **Description**: First line should end with a period (not 'C')
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `rpc_async`, **Line**: 814, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/api.py`, **Entity**: `rpc_async`, **Line**: 814, **Description**: First line should end with a period (not 'C')
- **File**: `torch/distributed/rpc/__init__.py`, **Entity**: `init_rpc`, **Line**: 90, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/rpc/__init__.py`, **Entity**: `init_rpc`, **Line**: 90, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/rpc/__init__.py`, **Entity**: `init_rpc`, **Line**: 90, **Description**: First line should be in imperative mood (perhaps 'Initialize', not 'Initializes')
- **File**: `torch/distributed/optim/__init__.py`, **Entity**: ``, **Line**: 1, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/__init__.py`, **Entity**: ``, **Line**: 1, **Description**: First line should end with a period (not 't')
- **File**: `torch/distributed/optim/functional_adam.py`, **Entity**: `step_param`, **Line**: 66, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/functional_adam.py`, **Entity**: `step_param`, **Line**: 66, **Description**: First line should end with a period (not 'a')
- **File**: `torch/distributed/optim/functional_sgd.py`, **Entity**: `step_param`, **Line**: 52, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/functional_sgd.py`, **Entity**: `step_param`, **Line**: 52, **Description**: First line should end with a period (not 'd')
- **File**: `torch/distributed/optim/optimizer.py`, **Entity**: `DistributedOptimizer`, **Line**: 127, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/optimizer.py`, **Entity**: `DistributedOptimizer`, **Line**: 127, **Description**: First line should end with a period (not 'd')
- **File**: `torch/distributed/optim/optimizer.py`, **Entity**: `step`, **Line**: 224, **Description**: First line should be in imperative mood (perhaps 'Perform', not 'Performs')
- **File**: `torch/distributed/optim/post_localSGD_optimizer.py`, **Entity**: `PostLocalSGDOptimizer`, **Line**: 8, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/post_localSGD_optimizer.py`, **Entity**: `PostLocalSGDOptimizer`, **Line**: 8, **Description**: First line should end with a period (not ',')
- **File**: `torch/distributed/optim/post_localSGD_optimizer.py`, **Entity**: `state_dict`, **Line**: 70, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/post_localSGD_optimizer.py`, **Entity**: `state_dict`, **Line**: 70, **Description**: First line should end with a period (not ',')
- **File**: `torch/distributed/optim/post_localSGD_optimizer.py`, **Entity**: `state_dict`, **Line**: 70, **Description**: First line should be in imperative mood; try rephrasing (found 'This')
- **File**: `torch/distributed/optim/post_localSGD_optimizer.py`, **Entity**: `load_state_dict`, **Line**: 80, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/post_localSGD_optimizer.py`, **Entity**: `load_state_dict`, **Line**: 80, **Description**: First line should end with a period (not ',')
- **File**: `torch/distributed/optim/post_localSGD_optimizer.py`, **Entity**: `load_state_dict`, **Line**: 80, **Description**: First line should be in imperative mood; try rephrasing (found 'This')
- **File**: `torch/distributed/optim/post_localSGD_optimizer.py`, **Entity**: `step`, **Line**: 99, **Description**: One-line docstring should fit on one line with quotes (found 3)
- **File**: `torch/distributed/optim/post_localSGD_optimizer.py`, **Entity**: `step`, **Line**: 99, **Description**: First line should be in imperative mood (perhaps 'Perform', not 'Performs')
- **File**: `torch/distributed/optim/post_localSGD_optimizer.py`, **Entity**: `step`, **Line**: 99, **Description**: First line should not be the function's "signature"
- **File**: `torch/distributed/optim/utils.py`, **Entity**: `register_functional_optim`, **Line**: 30, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/distributed/optim/utils.py`, **Entity**: `register_functional_optim`, **Line**: 30, **Description**: First line should end with a period (not 'p')

### PR DESCRIPTION
**Pull request by Mrutyunjay01**
Fixes #112641, #112642, and partial fix to #112643 for `torch/distributed/optim/named_optimizer.py`. This PR resolved the docstrings for `torch/distributed/optim` and `torch/distributed/rpc` completely except Missing docs warnings. 

Provides fix for the following:

`torch/distributed/_functional_collectives.py`

Before: **25**
After   : **10**

`torch/distributed/autograd/__init__.py`

Before: **8**
After   : **4**

`torch/distributed/optim/`

Before: **156**
After   : **24**

`torch/distributed/rpc/`

Before: **81**
After   : **26**

The remaining are the Missing Doc Strings issues.

cc: @svekars

cc @svekars @carljparker

### CODE REVIEW

**Comment by Mrutyunjay01** [comment]
@svekars  kindly let me know if this is to be reviewed. In the meantime I can proceed to fix other issues.

**Comment by kit1980** [comment]
@Mrutyunjay01 please fix the linter issues.

**Comment by Mrutyunjay01** [comment]
@kit1980 fixed the lint issues.

**Comment by svekars** [comment]
I am closing this PR since the issues are assigned to different authors. Please work on issues that are unnassigned.

**Pull request closed without merging**
