### PR TITLE
[CI] Upgrade XPU support packages version to 2025.0

### PR DESCRIPTION
**Pull request by chuanqi129**
Works for #139722 and #114850

### CODE REVIEW

**Comment by icfaust** [comment]
Sorry if this is a dumb question: will this PR cause XPU nightly wheels to use the 2025.0 compiler?

**Comment by chuanqi129** [comment]
> Sorry if this is a dumb question: will this PR cause XPU nightly wheels to use the 2025.0 compiler?

Hi @icfaust, this PR is dedicate for CI upgrade. And the CD/nightly upgrade PR is WIP, Linux part can refer https://github.com/pytorch/pytorch/pull/140373

**Review by atalman — APPROVED** [review]
@chuanqi129 lgtm. Please add details about two CI xpu errors we see: 
``inductor/test_inductor_freezing.py::FreezingGpuTests::test_mm_concat_xpu``
and 
``test_xpu.py::TestXpuXPU::test_generic_stream_event_xpu``

**Comment by chuanqi129** [comment]
Thanks @atalman.

1. test_xpu.py::TestXpuXPU::test_generic_stream_event_xpu is new case for 2025.0 which added by https://github.com/pytorch/pytorch/pull/134666. Tracked in issue https://github.com/pytorch/pytorch/issues/140814

**Pull request closed without merging**
