### PR TITLE
Fix `UntypedStorage.resize_` to keep same CUDA device index

### LINKED ISSUE #113300: `Storage.resize_()` moves storage to current device
```
import torch

assert torch.cuda.device_count() >= 2

with torch.cuda.device(1):
    x = torch.zeros((2, 3), device="cuda:0")
    print(f"(before op) x.device: {x.device} x.untyped_storage().device: {x.untyped_storage().device}")
    x.untyped_storage().resize_(0)
    print(
        f"(after op) x.device: {x.device} x.untyped_storage().device: {x.untyped_storage().device}"
    )
```

```
(before op) x.device: cuda:0 x.untyped_storage().device: cuda:0
(after op) x.device: cuda:0 x.untyped_storage().device: cuda:1
```

<details>
<summary> Old Distributed Repro </summary>

```
torchrun --nproc_per_node=2 repro.py 
```

```
import os

import torch
from torch import distributed

local_rank = int(os.getenv("LOCAL_RANK", 0))
world_size = int(os.getenv("WORLD_SIZE", 1))
distributed.init_process_group(backend="nccl", rank=local_rank, world_size=world_size)
device = torch.device("cuda", local_rank)
print(f"rank={local_rank} world size={world_size} device={device} current device: {torch.cuda.current_device()}")

t = torch.randn((1024,), device=f"cuda:{local_rank}")
if local_rank == 1:
    print(f"[Rank {local_rank}] t.device: {t.device} t.untyped_storage().device: {t.untyped_storage().device}")
    print(f"[Rank {local_rank}] id(t.untyped_storage()): {id(t.untyped_storage())}")
    print(f"[Rank {local_rank}] t.untyped_storage().resize_(4).device: {t.untyped_storage().resize_(4).device} t.device: {t.device}")
    print(f"[Rank {local_rank}] id(t.untyped_storage()): {id(t.untyped_storage())}")
```

```
rank=1 world size=2 device=cuda:1 current device: 0
rank=0 world size=2 device=cuda:0 current device: 0
[Rank 1] t.device: cuda:1 t.untyped_storage().device: cuda:1
[Rank 1] id(t.untyped_storage()): 139630240323904
[Rank 1] t.untyped_storage().resize_(4).device: cuda:0 t.device: cuda:1
[Rank 1] id(t.untyped_storage()): 139630240323904
```
</details>

cc @ptrblck

### PR DESCRIPTION
**Pull request by kurtamohler**
Fixes #113300

cc @ptrblck

## BC-breaking note

Before this PR, `UntypedStorage.resize_()` used to move CUDA storage data to the current CUDA device index, `torch.cuda.current_device()`. After this PR, `UntypedStorage.resize_()` keeps the data on the same device index that it was on before, regardless of the current device index.

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by gchanan** [comment]
@albanD @kurtamohler worth a BC breaking note?

**Comment by kurtamohler** [comment]
Yeah probably a good idea. I added a note

**Comment by kevint324** [comment]
Hi @kurtamohler @albanD 

Sorry to discuss this on the closed PR. I can open another issue if you think it's a better place to discuss it. Please let me know.

Could you explain a little bit that why is `  c10::cuda::CUDAGuard guard(device.index());` needed [here](https://github.com/pytorch/pytorch/pull/113386/files#diff-2691af3a999b3a8f4a0f635aabcd8edf0ffeda501edfa9366648e8a89de12a90R30)

We are looking into some performance issue and found quite some device Set/Get operation pairs which are introduced by device guards which are scattered all over the code path.

For instance,  it seems `resize_bytes_cuda` here assumes `allocator->allocate(size_bytes);` should be guarded.
In the mean,  [resize_impl_cuda_](https://github.com/kurtamohler/pytorch/blob/78ffe49a3fcd3ddc4f9f98500ccd3cbdee22a029/aten/src/ATen/native/cuda/Resize.h#L33) inserts device guard by default. 

Along the path `resize_impl_cuda_(first device gurard) -> maybe_resize_storage_cuda  -> resize_bytes_cuda (nested device guard)` 

Is there any pricinple on device guard usage? It seems
1. All functions declared with TORCH_CUDA_CPP_API should be guarded
2. It's always the caller's responsibility to guard the callee. Thus nested device guard is inevitable since the callee has no idea about what the caller did and do the device guard again.

And last, if `resize_bytes_cuda` is guarded  anyway, is it necessary to have a device guard [here](https://github.com/kurtamohler/pytorch/blob/78ffe49a3fcd3ddc4f9f98500ccd3cbdee22a029/aten/src/ATen/native/cuda/Resize.h#L33) ?

Thanks
Kevin

**Comment by kurtamohler** [comment]
Hey @kevint324, I'm not sure about all the answers to the questions you asked, but below are my responses to some of them.

> Could you explain a little bit that why is   `c10::cuda::CUDAGuard guard(device.index());` needed [here](https://github.com/pytorch/pytorch/pull/113386/files#diff-2691af3a999b3a8f4a0f635aabcd8edf0ffeda501edfa9366648e8a89de12a90R30)

The allocator will use whichever device index is currently set. We need to make sure that the device index is set to the same device index that the data of the `StorageImpl` given to `resize_bytes_cuda` is currently allocated on--otherwise, the storage's data may switch to a different device. We want to keep the storage on whichever device the user originally said they wanted it to be on.

> Along the path, `resize_impl_cuda_` (first device gurard) -> `maybe_resize_storage_cuda` -> `resize_bytes_cuda` (nested device guard)`

If the guard in `resize_bytes_cuda` is potentially redundant within a call to `resize_impl_cuda_(..., device_guard = true)`, that is not the only place where `resize_bytes_cuda` is called. It is also called [here](https://github.com/pytorch/pytorch/blob/5af4b492852a0c8db03d04c71cae3a3d164d407f/torch/csrc/StorageMethods.cpp#L160) and [here](https://github.com/pytorch/pytorch/blob/5af4b492852a0c8db03d04c71cae3a3d164d407f/torch/csrc/inductor/inductor_ops.cpp#L94). I don't think either of those call sites sets the device guard beforehand.

> It's always the caller's responsibility to guard the callee.

I'm not sure I would agree that that is always true, unless I'm misunderstanding what you mean. If we were to move the responsibility of setting the device guard to the caller of `resize_bytes_cuda`, then all of its call sites will need to add `CUDAGuard guard(storage_impl->device().index());`. In order to make the interface developer-friendly, `resize_bytes_cuda` should be responsible for changing the device index when needed.

> Also do you think it's necessary to handle/optimize nested device guard?

It would certainly be ideal to avoid more `cudaGetDevice()` and `cudaSetDevice()` calls than we really need. But pragmatically, I'm wondering how significant the performance costs of the extra `cudaGetDevice()` and `cudaSetDevice()` calls really are.

Because of [this check](https://github.com/pytorch/pytorch/blob/a7af53cec1d421d2f6d99c9cb7fb341a691fc371/c10/cuda/CUDAFunctions.cpp#L236) `CUDAGuard` will only call `cudaSetDevice()` if the current device index differs from the new one. So within `resize_impl_cuda_(..., device_guard = true)`, unless I'm mistaken, `cudaSetDevice()` is only called once, and `cudaGetDevice()` is called twice. And I'm not sure how we would avoid the second call to `cudaGetDevice()` if `resize_bytes_cuda` should have the responsibility of checking the current device index

**Comment by kevint324** [comment]
> Hey @kevint324, I'm not sure about all the answers to the questions you asked, but below are my responses to some of them.
> 
> > Could you explain a little bit that why is   `c10::cuda::CUDAGuard guard(device.index());` needed [here](https://github.com/pytorch/pytorch/pull/113386/files#diff-2691af3a999b3a8f4a0f635aabcd8edf0ffeda501edfa9366648e8a89de12a90R30)
> 
> The allocator will use whichever device index is currently set. We need to make sure that the device index is set to the same device index that the data of the `StorageImpl` given to `resize_bytes_cuda` is currently allocated on--otherwise, the storage's data may switch to a different device. We want to keep the storage on whichever device the user originally said they wanted it to be on.
> 
> > Along the path, `resize_impl_cuda_` (first device gurard) -> `maybe_resize_storage_cuda` -> `resize_bytes_cuda` (nested device guard)`
> 
> If the guard in `resize_bytes_cuda` is potentially redundant within a call to `resize_impl_cuda_(..., device_guard = true)`, that is not the only place where `resize_bytes_cuda` is called. It is also called [here](https://github.com/pytorch/pytorch/blob/5af4b492852a0c8db03d04c71cae3a3d164d407f/torch/csrc/StorageMethods.cpp#L160) and [here](https://github.com/pytorch/pytorch/blob/5af4b492852a0c8db03d04c71cae3a3d164d407f/torch/csrc/inductor/inductor_ops.cpp#L94). I don't think either of those call sites sets the device guard beforehand.
> 
> > It's always the caller's responsibility to guard the callee.
> 
> I'm not sure I would agree that that is always true, unless I'm misunderstanding what you mean. If we were to move the responsibility of setting the device guard to the caller of `resize_bytes_cuda`, then all of its call sites will need to add `CUDAGuard guard(storage_impl->device().index());`. In order to make the interface developer-friendly, `resize_bytes_cuda` should be responsible for changing the device index when needed.
> 
> > Also do you think it's necessary to handle/optimize nested device guard?
> 
> It would certainly be ideal to avoid more `cudaGetDevice()` and `cudaSetDevice()` calls than we really need. But pragmatically, I'm wondering how significant the performance costs of the extra `cudaGetDevice()` and `cudaSetDevice()` calls really are.
> 
> Because of [this check](https://github.com/pytorch/pytorch/blob/a7af53cec1d421d2f6d99c9cb7fb341a691fc371/c10/cuda/CUDAFunctions.cpp#L236) `CUDAGuard` will only call `cudaSetDevice()` if the current device index differs from the new one. So within `resize_impl_cuda_(..., device_guard = true)`, unless I'm mistaken, `cudaSetDevice()` can only be called twice if the storage has a different device index than the current setting--once upon creation of the first guard, once upon destroy to restore the original setting. The nested guard won't call `cudaSetDevice()`. But there are a handful of `cudaGetDevice()` calls, not sure exactly how many, but I think it would be at least 4. However, if `resize_bytes_cuda` is responsible for changing the device index when needed, I'm not sure what better solution there is than just using `CUDAGuard`

Hi @kurtamohler 


Sorry, my bad. I didn't make my self clear. You are right. cudaSetDevice is only called when necessary. What I meant was the cudaGetDevice/cudaGetDevice pair introduced by the ctor and dtor of the device guard. 

As for the cost, each cudaGetDevice costs just around ~100 nanoseconds on a modern CPU which is totally negligible. However we noticed 13 cudaGetDevice call during a plain torch::abs call and seems 10 of them are introduced by device guards. The host latency becomes a little bit more noticeable with a multiplier of 10. 

Here is the simple test.

```
import torch

// warm up call
x=-torch.ones((10,10,10),dtype=torch.float,device="cuda")
y=torch.abs(x)

// start gdb here and set a break point on cudaGetDevice
z=torch.abs(y)
```

And here are the callstacks of the 13 calls to cudaGetDevice.
[cudaGetDevice_calls.txt](https://github.com/pytorch/pytorch/files/15332597/cudaGetDevice_calls.txt)

**Comment by kevint324** [comment]
I'm trying to understand why there are so many device guards in PyTorch compared to TensorFlow.

Here are my current understandings (please forgive me if I am totally wrong):

Q: When must a programmer insert a device guard?

A: A device guard must be inserted when a piece of code relies on cudaCurrentDevice to work properly and it might be called from a potentially unguarded scope.

The fundamental difference between TensorFlow (TF) and PyTorch (PT) is that TF hides worker threads from the user, binding them to a device context at a very high level. In contrast, PyTorch is much more flexible, allowing threads to switch between devices and perform device-related operations at any moment. For example, in the resize_bytes_cuda case, it doesn’t make sense in the TensorFlow world for a thread bound to device A to resize a tensor on device B.

I think it's harder for a PyTorch developer. For instance, it’s difficult to determine the exact purpose and scope of the device guard inserted [here](https://github.com/kurtamohler/pytorch/blob/78ffe49a3fcd3ddc4f9f98500ccd3cbdee22a029/aten/src/ATen/native/cuda/Resize.h#L41) due to the large [guarded region](https://github.com/kurtamohler/pytorch/blob/78ffe49a3fcd3ddc4f9f98500ccd3cbdee22a029/aten/src/ATen/native/cuda/Resize.h#L44-L56).

Does self->dtype().itemsize(); need to be guarded to function? If not, why is it in the guarded region? Or maybe at::detail::computeStorageNbytesContiguous must be guarded? You wouldn’t know until you check the detailed implementation.

maybe_resize_storage_cuda -> resize_bytes_cuda clearly should be guarded, as you mentioned. But after this PR, a device guard was [inserted](https://github.com/pytorch/pytorch/pull/113386/files#diff-2691af3a999b3a8f4a0f635aabcd8edf0ffeda501edfa9366648e8a89de12a90R30). Is the guard in resize_impl_cuda_ still necessary? If yes, what exactly is it guarding now?

I'm just continually wondering about these things :p

**Comment by kurtamohler** [comment]
Your concerns are outside the scope of this PR, so I'd recommend opening an issue

**Comment by kevint324** [comment]
Sure. Thank you.

**Pull request closed without merging**
