### PR TITLE
Added is_xla

### PR DESCRIPTION
**Pull request by aws-murandoo**
This change creates `is_xla` which is congruent with `is_cuda` and `is_cpu`. Useful in situations like: https://github.com/pytorch/pytorch/pull/102858

```
>>> x = torch.tensor([1], device=xm.xla_device())
>>> x.is_xla
True
>>> x.is_cpu
False
>>> x = torch.tensor([1])
>>> x.is_cpu
True
>>> x.is_xla
False
```

Attn: @albanD

### CODE REVIEW

**Comment by aws-murandoo** [comment]
Looks like there were a few spots missing which I added in. Can we rerun CI?

**Comment by kit1980** [comment]
> Looks like there were a few spots missing which I added in. Can we rerun CI?

Restarted CI.

**Comment by aws-murandoo** [comment]
Looks ot me like these failures are unrelated, can anyone comment?

**Review by albanD — APPROVED** [review]
Sounds good! Thanks!

**Pull request closed without merging**
