### PR TITLE
[BE] Enable ruff's UP rules in pyproject.toml

### PR DESCRIPTION
**Pull request by justinchuby**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #105538
* __->__ #105437

Signed-off-by: Justin Chu <justinchu@microsoft.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Comment by huydhn** [comment]
In the future, please consider breaking up this stack into multiple smaller ones of may be 2 to 3 depth each because this would very likely increase queue time on CI for scarce resources like ROCm, MacOS, or Windows.  A stack of depth 15 means 15 times the regular number of CI job at once.  As this has already started, I would probably approve them all and cross my fingers that they all passed :) 

cc @seemethere @malfet

**Review by huydhn — APPROVED** [review]

**Comment by justinchuby** [comment]
> In the future, please consider breaking up this stack into multiple smaller ones of may be 2 to 3 depth each because this would very likely increase queue time on CI for scarce resources like ROCm, MacOS, or Windows. A stack of depth 15 means 15 times the regular number of CI jobs at once. As this has already started and the changes are lint-related, I would probably wait and cross my fingers that they all pass :)
> 

Sounds very reasonable. Thanks!

**Review by malfet — APPROVED** [review]

**Comment by justinchuby** [comment]
I Will update to exclude the jit tests

**Comment by justinchuby** [comment]
TODO: fix these in the stack

```
test/test_type_promotion.py:990:59 :Warning continuation line over-indented for visual indent See https://www.flake8rules.com/rules/E127.html [FLAKE8/E127]
test/test_type_promotion.py:991:59 :Warning continuation line over-indented for visual indent See https://www.flake8rules.com/rules/E127.html [FLAKE8/E127]
test/test_type_promotion.py:992:59 :Warning continuation line over-indented for visual indent See https://www.flake8rules.com/rules/E127.html [FLAKE8/E127]
test/test_type_promotion.py:999:59 :Warning continuation line over-indented for visual indent See https://www.flake8rules.com/rules/E127.html [FLAKE8/E127]
test/test_type_promotion.py:1000:59 :Warning continuation line over-indented for visual indent See https://www.flake8rules.com/rules/E127.html [FLAKE8/E127]
test/test_type_promotion.py:1001:59 :Warning continuation line over-indented for visual indent See https://www.flake8rules.com/rules/E127.html [FLAKE8/E127]
functorch/einops/rearrange.py:112:13 :Warning continuation line over-indented for hanging indent See https://www.flake8rules.com/rules/E126.html [FLAKE8/E126]
torch/backends/mps/__init__.py:13:12 :Error Module has no attribute "_has_mps"; maybe "has_mps"?  [MYPY/[attr-defined]]
test/test_sparse_csr.py:908:18 :Warning continuation line over-indented for visual indent See https://www.flake8rules.com/rules/E127.html [FLAKE8/E127]
test/test_sparse_csr.py:909:18 :Warning continuation line over-indented for visual indent See https://www.flake8rules.com/rules/E127.html [FLAKE8/E127]
test/test_sparse_csr.py:910:18 :Warning continuation line over-indented for visual indent See https://www.flake8rules.com/rules/E127.html [FLAKE8/E127]
torch/ao/quantization/fx/utils.py:818:154 :Advice line too long (153 > 120 characters) See https://github.com/PyCQA/flake8-bugbear#list-of-warnings [FLAKE8/B950]
torch/ao/quantization/fx/utils.py:828:146 :Advice line too long (145 > 120 characters) See https://github.com/PyCQA/flake8-bugbear#list-of-warnings [FLAKE8/B950]
torch/ao/quantization/fx/utils.py:850:134 :Advice line too long (133 > 120 characters) See https://github.com/PyCQA/flake8-bugbear#list-of-warnings [FLAKE8/B950]
torch/serialization.py:1427:5 :Error Module has no attribute "_log_api_usage_metadata"  [MYPY/[attr-defined]]
torch/autograd/profiler_util.py:235:48 :Warning continuation line under-indented for visual indent See https://www.flake8rules.com/rules/E128.html [FLAKE8/E128]
torch/_custom_op/impl.py:157:9 :Error Module has no attribute "_dispatch_set_report_error_callback"  [MYPY/[attr-defined]]
torch/ao/quantization/backend_config/backend_config.py:602:145 :Advice line too long (144 > 120 characters) See https://github.com/PyCQA/flake8-bugbear#list-of-warnings [FLAKE8/B950]
torch/ao/quantization/quantization_mappings.py:304:10 :Warning continuation line unaligned for hanging indent See https://www.flake8rules.com/rules/E131.html [FLAKE8/E131]
torch/ao/quantization/quantization_mappings.py:305:10 :Warning continuation line unaligned for hanging indent See https://www.flake8rules.com/rules/E131.html [FLAKE8/E131]
torch/ao/quantization/quantization_mappings.py:306:10 :Warning continuation line unaligned for hanging indent See https://www.flake8rules.com/rules/E131.html [FLAKE8/E131]
torch/_prims_common/wrappers.py:293:14 :Error "_AutoDispatchBelowAutograd" has no attribute "__enter__"  [MYPY/[attr-defined]]
torch/_prims_common/wrappers.py:293:14 :Error "_AutoDispatchBelowAutograd" has no attribute "__exit__"  [MYPY/[attr-defined]]
torch/package/package_importer.py:102:9 :Error Module has no attribute "_log_api_usage_metadata"  [MYPY/[attr-defined]]
torch/mps/__init__.py:22:12 :Error Module has no attribute "_mps_deviceSynchronize"  [MYPY/[attr-defined]]
torch/mps/__init__.py:47:12 :Error Module has no attribute "_has_mps"; maybe "has_mps"?  [MYPY/[attr-defined]]
torch/nn/functional.py:3372:17 :Warning continuation line over-indented for hanging indent See https://www.flake8rules.com/rules/E126.html [FLAKE8/E126]
torch/nn/functional.py:4681:14 :Warning continuation line unaligned for hanging indent See https://www.flake8rules.com/rules/E131.html [FLAKE8/E131]
test/test_jit.py:14260:9 :Warning Convert `_AnnotatedNamedTuple` from `NamedTuple` functional to class syntax. See https://beta.ruff.rs/docs/rules/.  To disable, use `  # noqa: UP014` [RUFF/UP014]
torch/nn/modules/rnn.py:213:67 :Error Module has no attribute "_is_any_autocast_enabled"; maybe "is_autocast_cpu_enabled" or "is_autocast_cache_enabled"?  [MYPY/[attr-defined]]
```

**Review by Skylion007 — APPROVED** [review]

**Pull request closed without merging**
