### PR TITLE
Skip some failing dynamic shape models on periodic

### PR DESCRIPTION
**Pull request by huydhn**
After some recent changes, these tests are failing in periodic trunk.  So let's move them to unstable while waiting for the team to root cause the issue https://github.com/pytorch/pytorch/issues/99893.  Note that a forward fix can use `ciflow/unstable` to run those unstable jobs to confirm that they are fixed.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Comment by ezyang** [comment]
Can you update the xfails instead?

**Comment by ezyang** [comment]
We're supposed to have a script that auto updates the xfails but I don't see it printing in this case cc @wconstab

**Review by malfet — APPROVED** [review]
I've pinged folks in separate chat and they are looking into getting  those fixed

**Pull request closed without merging**
