### PR TITLE
Use CAFFE2_USE_MSVC_STATIC_RUNTIME to determine when to avoid waiting for global destructors on Windows 

### PR DESCRIPTION
**Pull request by adampauls**
Cherry-pick of #43532 onto release/1.7.

Summary:
We are trying to build libtorch statically (BUILD_SHARED_LIBS=OFF) then link it into a DLL. Our setup hits the infinite loop mentioned [here](https://github.com/pytorch/pytorch/blob/54c05fa34e1fbbb5096746a8ae92e27a08116de4/torch/csrc/autograd/engine.cpp#L228) because we build with `BUILD_SHARED_LIBS=OFF` but still link it all into a DLL at the end of the day.

This PR fixes the issue by changing the condition to guard on which windows runtime the build links against using the `CAFFE2_USE_MSVC_STATIC_RUNTIME` flag. `CAFFE2_USE_MSVC_STATIC_RUNTIME` defaults to ON when `BUILD_SHARED_LIBS=OFF`, so backwards compatibility is maintained.

I'm not entirely confident I understand the subtleties of the windows runtime versus linking setup, but this setup works for us and should not affect the existing builds.

Fixes https://github.com/pytorch/pytorch/issues/44470

Pull Request resolved: https://github.com/pytorch/pytorch/pull/43532

Reviewed By: mrshenli

Differential Revision: D24053767

Pulled By: albanD

fbshipit-source-id: 1127fefe5104d302a4fc083106d4e9f48e50add8

Fixes #{issue number}

### CODE REVIEW

**Comment by mruberry** [comment]
@malfet, are you the correct person to review this?

**Comment by malfet** [comment]
@mruberry, I am, although this is just a cherry-pick from master.

**Comment by adampauls** [comment]
Just double-checking all is well here? It seems most branches in the 1.7.0 issue tracker mentioned after this one have been merged?

**Comment by malfet** [comment]
@adampauls Looking at the code, it seems that this change disabled this codepath on Windows for both default static library build, which can lead to crashes during application shutdown is library is linked to an executable. 
Please add a rule to CMakeLists.txt to default it to !C10_BUILD_SHARED_LIBS and then it should be good to go.

**Comment by adampauls** [comment]
I think that's already accomplished by https://github.com/pytorch/pytorch/blob/b1d24dded11ea1f9e59f430f8c4d26befa97d847/CMakeLists.txt#L135-L137, or am I misunderstanding?

**Comment by adampauls** [comment]
Friendly ping, I noticed this missed the RC2 train.

**Comment by adampauls** [comment]
@malfet friendly ping, seems this missed RC3 too.

**Comment by adampauls** [comment]
@malfet should I assume this won't make it in for 1.7 then?

**Pull request closed without merging**
