### PR TITLE
[AOTI XPU] Remove workarounds after update torch-xpu-ops that extend c_shim_xpu layer with out-of-tree ATen OPs.

### PR DESCRIPTION
**Pull request by etaf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #140686
* #140664
* #140269
* #140268
* #135320
* #135318
* __->__ #139026

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by etaf** [comment]
This PR depends on torch-xpu-ops PR https://github.com/intel/torch-xpu-ops/pull/1021,  I will update the toch-xpu-ops commit pin after torch-xpu-ops PR merged.

**Comment by EikanWang** [comment]
@etaf , pls. feel free to reach out to me if the PR is ready for review.

**Comment by etaf** [comment]
@EikanWang  @desertfire  this PR originally update torch-xpu-ops and remove the previous workarounds, but the torch-xpu-ops update have been done at PR #140277. So this PR is ready to land, please have a review, thanks.

**Review by EikanWang — APPROVED** [review]

**Review by desertfire — APPROVED** [review]

**Pull request closed without merging**
