### PR TITLE
[Caffe2] Fix the spelling of "context"

### PR DESCRIPTION
**Pull request by xkszltl**

### CODE REVIEW

**Comment by xkszltl** [comment]
Build failure unrelated (timeout)

**Comment by xkszltl** [comment]
```
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-cuda8.0-cudnn7-ubuntu16.04:266-759ef280ed4a305be77b6a71dccb79d1fee38085 not found
```

**Comment by xkszltl** [comment]
Unrelated test failure.
Docker image is missing.

**Review by peterjc123 — APPROVED** [review]

**Pull request closed without merging**
