### PR TITLE
adaptive pooling supports only specifying size in certain dimension

### PR DESCRIPTION
**Pull request by blackyang**
Adaptive pooling supports only specifying size in certain dimensions. For example, we can have:
```
x = Variable(torch.rand(1,3,10,10))
m = nn.AdaptiveMaxPool2d((5,None))
y=m(x)
y.size()  # torch.Size([1, 3, 5, 10])
```

This is useful for certain sequence related tasks

### CODE REVIEW

**Comment by blackyang** [comment]
Maybe I should also change docs accordingly

**Comment by soumith** [comment]
if you can, please send a PR to fix the docs. thank you!

**Comment by blackyang** [comment]
@soumith I created a PR #3746 to fix the docs. Do you think it's okay?

**Comment by soumith** [comment]
it looks great, thank you!

**Pull request merged**
