### PR TITLE
Added explicit build command for Windows and clarification on obtaining

### PR DESCRIPTION
**Pull request by ikriv**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #70190

C++ build tools to readme.md

Differential Revision: [D33245438](https://our.internmc.facebook.com/intern/diff/D33245438)

### CODE REVIEW

**Comment by ikriv** [comment]
@ikriv has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33245438).

**Comment by ikriv** [comment]
Will resubmit

**Comment by ikriv** [comment]
@ikriv has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33245438).

**Review by jbschlosser — APPROVED** [review]
LGTM thanks for the update!

**Pull request closed without merging**
