### PR TITLE
Delete unnecessary Eigen version gate.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by BIT-silence** [comment]
I'd suggest remove this file at all or guarded the whole file by #if EIGEN_VERSION_AT_LEAST(3, 3, 0) since the Eigen/unsupported libs requires certain eigen version.

**Comment by ezyang** [comment]
@BIT-silence Is this a compile-time or run-time incompatibility? I ask because Caffe2 seems to build fine with this patch. Maybe we should just adjust the version number lower?

**Comment by BIT-silence** [comment]
The compile error comes from

-#if !EIGEN_VERSION_AT_LEAST(3, 3, 0)	
-#error "Caffe2 requires Eigen to be at least 3.3.0.";	
-#endif

So if we change it to

#if EIGEN_VERSION_AT_LEAST(3, 3, 0)

...
code
...

#endif 

There will be no compile error and when the eigen version is lower than 3.3.0, the guarded code will not be compiled.

Another thing is that there is almost no one use this eigen conv_op. So remove it at all is also fine.

**Review by xiaomengy — APPROVED** [review]

**Pull request merged**
