### PR TITLE
Fix RMSNorm doc per #136597

### LINKED ISSUE #136597: [Doc issue] RMSNorm formula
### 📚 The doc issue

**Description:**

There appears to be a discrepancy in the RMSNorm formula as documented on the [PyTorch docs website](https://pytorch.org/docs/stable/generated/torch.nn.RMSNorm.html) compared to the original formulation presented in the paper "Root Mean Square Layer Normalization" ([arXiv:1910.07467](https://arxiv.org/pdf/1910.07467.pdf)).

**Details:**

The formula for RMSNorm in the PyTorch documentation is currently represented as:

$$
y = \frac{x}{\sqrt{\text{RMS}[x] + \epsilon}} * \gamma
$$

However, according to the original paper, the correct formula should be:

$$
y_i = \frac{x_i}{\text{RMS}(x)} \gamma_i, \quad \text{where} \quad \text{RMS}(x) = \sqrt{\epsilon + \frac{1}{n} \sum_{i=1}^{n} x_i^2}
$$

**Issue:**

- The PyTorch documentation formula includes an additional square root operation around RMS[x] and epsilon, which is not present in the original paper's formula.
- This discrepancy could lead to confusion or incorrect implementation by users relying on the PyTorch documentation.

### Suggest a potential alternative/fix

**Suggested Correction:**

Please update the PyTorch documentation to reflect the correct formula as per the original paper. The corrected formula should be:

$$
y = \frac{x}{\sqrt{\text{MS}[x] + \epsilon}} * \gamma
$$

where MS is the Mean Square.

Implementing this correction will enhance the accuracy and reliability of the PyTorch documentation. By aligning with the original paper's formula, users will have a clearer understanding of how RMSNorm is intended to function, thereby reducing potential implementation errors. This update will also help maintain consistency across different resources and ensure that users can confidently rely on the documentation for their projects.
```[tasklist]
### Tasks
```

cc @svekars @brycebortree @sekyondaMeta @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Fixes #136597 (remove incorrect sqrt around `RMS(x)`)

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136727

Screenshot 2024-09-26 at 11 46 32 AM

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!

Do we actually have the epsilon inside the square root? Or we add it outside? We had issues with this kind of things in the optimizer making the eps actually zero so you might want to double check with @janeyx99 on this. (not for this PR obviously)

**Comment by mikaylagawarecki** [comment]
It's really inside https://github.com/pytorch/pytorch/blob/2202eb57509a861d8dedfd6e45815f38d72db084/aten/src/ATen/native/layer_norm.cpp#L295

**Comment by d-kleine** [comment]
@mikaylagawarecki @albanD I have noticed a small detail: It says
> - $RMS[x]$ where $RMS(x)$

Using `[]` and `()` might be confusing for some readers of the docs. The formula in the [RMSNorm paper](https://arxiv.org/pdf/1910.07467.pdf) is

$$y_i = \frac{x_i}{\text{RMS}(x)} \gamma_i, \quad \text{where} \quad \text{RMS}(x) = \sqrt{\epsilon + \frac{1}{n} \sum_{i=1}^{n} x_i^2}$$

```latex
y_i = \frac{x_i}{\text{RMS}(x)} \gamma_i, \quad \text{where} \quad \text{RMS}(x) = \sqrt{\epsilon + \frac{1}{n} \sum_{i=1}^{n} x_i^2}
```

What do you think about that?

**Comment by d-kleine** [comment]
When will this be uploaded to the website?

**Comment by mikaylagawarecki** [comment]
It's on `main` https://pytorch.org/docs/main/generated/torch.nn.RMSNorm.html#torch.nn.RMSNorm (will be in the next release)

**Comment by d-kleine** [comment]
Ah, okay, thanks - I was wondering why it was not on stable yet:
https://pytorch.org/docs/stable/generated/torch.nn.RMSNorm.html

**Pull request closed without merging**
