### PR TITLE
decouple arrayRef from deploy

### PR DESCRIPTION
**Pull request by PaliC**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #74002
* __->__ #73526
* #73456

Copies over ArrayRef.h and SmallVector.h/cpp from c10/util (and I guess LLVM) in order to remove deploy's dependency on ArrayRef in order to reduce the need of the torch library for torch::deploy. We now use `multipy::ArrayRef`  instead of `at::ArrayRef` in torch::deploy. In order to keep this pr atomic the following two concessions have been made.

1. There is constructor which converts `at::ArrayRef` to `multipy::ArrayRef`. This way we do not have to worry about Ivalue objects creating `at::ArrayRef` objects and using the `multipy` namespace.
2. There is a constructor which converts `c10::ivalue::TupleElements` to `multipy::ArrayRef` as there is a conversion of `c10::ivalue::TupleElements` to `at::ArrayRef` .

The above two problems will be fixed once we move to a more generic version of Ivalue for torch::deploy.

Note: Internal Testing / changes are still needed

Differential Revision: [D34868007](https://our.internmc.facebook.com/intern/diff/D34868007)

### CODE REVIEW

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34568589).

**Comment by shunting314** [comment]
Accept assuming the PR mainly does copy/paste and renames symbols. 

It should be good to list what are all the data structures in PyTorch that need to be duplicated for decoupling. E.g., here are other things I'm aware of c10::optional , c10::IValue

Make sure CI is clean before merging

**Review by shunting314 — APPROVED** [review]

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34568589).

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34568589).

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34568589).

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34568589).

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34568589).

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34568589).

**Comment by PaliC** [comment]
@PaliC has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34868007).

**Pull request closed without merging**
