### PR TITLE
Bump triton xpu pin and release version

### PR DESCRIPTION
**Pull request by chuanqi129**
Similar with https://github.com/pytorch/pytorch/pull/135627

cc @gujinghui @EikanWang @fengyuan14 @guangyey

### CODE REVIEW

**Review by atalman — APPROVED** [review]
lgtm

**Comment by kit1980** [comment]
@chuanqi129 All triton XPU builds failed on 2.5.0 release candidate with this PR.
See https://github.com/pytorch/pytorch/actions/runs/10894886278/job/30232276026
Any ideas?

**Comment by chuanqi129** [comment]
> @chuanqi129 All triton XPU builds failed on 2.5.0 release candidate with this PR. See https://github.com/pytorch/pytorch/actions/runs/10894886278/job/30232276026 Any ideas?

Hi @kit1980, thanks to point out it. It caused by the xpu triton repo didn't create `release/3.1.x` branch, it used `[release/2.5.0](https://github.com/intel/intel-xpu-backend-for-triton/tree/release/2.5.0)` branch.

@vlad-penkin @pbchekin could  you please create a new triton branch named `release/3.1.x` based on current `[release/2.5.0](https://github.com/intel/intel-xpu-backend-for-triton/tree/release/2.5.0)` branch. The build triton scripts has some hardcode for release binary build, refer https://github.com/pytorch/pytorch/blob/main/.github/scripts/build_triton_wheel.py#L106C47-L106C58. Thanks.

**Comment by chuanqi129** [comment]
Hi @kit1980, the branch https://github.com/intel/intel-xpu-backend-for-triton/tree/release/3.1.x has been created, could you please help to try it again?

**Pull request closed without merging**
