### PR TITLE
remove componentwise comparison of complex values in TestCase.assertEqual

### PR DESCRIPTION
**Pull request by pmeier**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #63841
* __->__ #63572

Addresses #61906. Issue will be fixed later in the stack when `torch.testing.assert_close` got the same treatment.

cc @ezyang @gchanan

Differential Revision: [D30633527](https://our.internmc.facebook.com/intern/diff/D30633527)

### CODE REVIEW

**Comment by pmeier** [comment]
There is one issue that materializes for example in `test_tensor_creation_ops.TestRandomTensorCreation.test_randn`:

```python
>>> t = torch.tensor(0, dtype=torch.complex32)
>>> torch.allclose(t, t)
RuntimeError: "eq_cpu" not implemented for 'ComplexHalf'
>>> t = t.cuda()
>>> torch.allclose(t, t)
RuntimeError: "eq_cuda" not implemented for 'ComplexHalf'
```

Previously one `complex32` was treated as two `float16` which prevents this. We could skip `complex32` in all tests that compare values, but for the future equality should be supported for these values.

**Comment by mruberry** [comment]
Some (one?) of the test failures seem real:

```
test_randn_cpu_complex32 - TestRandomTensorCreationCPU

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 373, in instantiated_test
    result = test(self, **param_kwargs)
  File "test_tensor_creation_ops.py", line 3269, in test_randn
    self.assertEqual(res1, res2)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1550, in assertEqual
    exact_device=exact_device)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1415, in _compareTensors
    return _compare_tensors_internal(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_core.py", line 118, in _compare_tensors_internal
    if torch.allclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan):
RuntimeError: "eq_cpu" not implemented for 'ComplexHalf'
```

A fix for this could be to implement allclose for complexhalf or to upcast complexhalf tensors in assertEqual/compareTensors/assert_close.

**Comment by mruberry** [comment]
cc @zasdfgbnm

**Comment by pmeier** [comment]
> A fix for this could be to implement allclose for complexhalf or to upcast complexhalf tensors in assertEqual/compareTensors/assert_close.

It is not `allclose`, but rather equality:

```python
>>> t = torch.tensor(0, dtype=torch.complex32)
>>> t == t
RuntimeError: "eq_cpu" not implemented for 'ComplexHalf'
>>> t = t.cuda()
>>> t == t
RuntimeError: "eq_cuda" not implemented for 'ComplexHalf'
```

Feels weird that this fundamental method is not there.

**Comment by anjali411** [comment]
> > A fix for this could be to implement allclose for complexhalf or to upcast complexhalf tensors in assertEqual/compareTensors/assert_close.
> 
> It is not `allclose`, but rather equality:
> 
> ```python
> >>> t = torch.tensor(0, dtype=torch.complex32)
> >>> t == t
> RuntimeError: "eq_cpu" not implemented for 'ComplexHalf'
> >>> t = t.cuda()
> >>> t == t
> RuntimeError: "eq_cuda" not implemented for 'ComplexHalf'
> ```
> 
> Feels weird that this fundamental method is not there.

There's bare minimum support for `ComplexHalf`. In fact, we should probably just remove the `ComplexHalf` dtype until enough functionality is added.

**Review by mruberry — APPROVED** [review]
Cool

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30633527).

**Pull request closed without merging**
