### PR TITLE
Fix edge case in inductor triton clean script

### PR DESCRIPTION
**Pull request by ahmadsarvmeily**
The regex in the script is too restrictive, as it excludes examples with parentheses in args, like the following:
```
triton_poi_fused_add_0.run(arg0_1.item(), arg1_1.item(), buf0, 1, grid=grid(1), stream=streamNone)
                                       ^
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by Chillee — CHANGES_REQUESTED** [review]
Would it be possible to add a test here? https://github.com/pytorch/pytorch/pull/125811/files#diff-736311ec19dbddbf0207133e7d68db5f6dfb5e38eb471628b9a56b6df6d52f71R446

**Comment by ahmadsarvmeily** [comment]
> Would it be possible to add a test here? https://github.com/pytorch/pytorch/pull/125811/files#diff-736311ec19dbddbf0207133e7d68db5f6dfb5e38eb471628b9a56b6df6d52f71R446

@Chillee Done, please let me know if it looks okay to you

**Review by Chillee — APPROVED** [review]
LGTM!

**Pull request closed without merging**
