### PR TITLE
add BFloat16 support for bernoulli and Dropout on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #61015 add BFloat16 support for BatchNorm2d on CPU
* #58297 add BFloat16 support for UpSample on CPU
* #56904 optimize transpose copy for float32 and bfloat16 on CPU
* #56903 add BFloat16 support for MaxPool2d on CPU
* #56902 add BFloat16 support for AdaptiveAvgPool2d on CPU
* **#56372 add BFloat16 support for bernoulli and Dropout on CPU**
* #55588 add bf16 support for bucketize
* #55221 optimize BFloat16 elemwise operators CPU: sigmoid, sigmoid_backward, tanh_backward, addcmul, addcdiv

Differential Revision: [D28836792](https://our.internmc.facebook.com/intern/diff/D28836792)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836792).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836792).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836792).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836792).

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Please add benchmark numbers

**Comment by mingfeima** [comment]
Update with benchmark data:

#### avx512 CPU performance
```bash
### using KMP_AFFINITY=granularity=fine,compact,1,0
### using KMP_BLOCKTIME=1
### using OMP_NUM_THREADS=1
### using numactl --physcpubind=0 --membind=0

Dropout: size: torch.Size([512, 1024]) ;  torch.float32 ; time: 0.778 ms
Dropout: size: torch.Size([512, 1024]) ;  torch.bfloat16 ; time: 0.678 ms
```

#### avx2 CPU performance
```bash
### using KMP_AFFINITY=granularity=fine,compact,1,0
### using KMP_BLOCKTIME=1
### using OMP_NUM_THREADS=1
Dropout: size: torch.Size([512, 1024]) ;  torch.float32 ; time: 1.252 ms
Dropout: size: torch.Size([512, 1024]) ;  torch.bfloat16 ; time: 1.201 ms

**Pull request closed without merging**
