### PR TITLE
[CI] Fix xpu linux ci build environment duplicated issue

### PR DESCRIPTION
**Pull request by chuanqi129**
We found that there are duplicated build environments in XPU linux ci test, it led to test jobs may download wrong pytorch build artifact file. Refer https://github.com/pytorch/pytorch/actions/runs/12023238798/job/33518351906#step:14:633

Works for https://github.com/pytorch/pytorch/issues/139722 and https://github.com/pytorch/pytorch/issues/114850

### CODE REVIEW

**Review by EikanWang — APPROVED** [review]

**Review by atalman — APPROVED** [review]
Looks like possible CI issue: `` echo 'Error: Available diskspace is less than 70 percent. Not enough diskspace.'``

**Review by atalman — CHANGES_REQUESTED** [review]
lgtm. Please investigate the XPU failures on this PR

**Comment by chuanqi129** [comment]
Hi @atalman, I have resolved the disk issue and rebased the PR with latest main, previous 2 xpu inductor UT failures has been fixed. But there is only one doctests failure in the latest CI tests, it's very strange and may need more time to root cause it. I have created a issue https://github.com/pytorch/pytorch/issues/141705 to track it, and will try to fix it ASAP. Can we land this PR firstly?

**Review by atalman — APPROVED** [review]
lgtm. Thank for taking time resolving and looking into these issues

**Pull request closed without merging**
