### PR TITLE
fix Invalid call to aoti_torch_tensor_copy_ #123039

### LINKED ISSUE #123039: [easy] Invalid call to aoti_torch_tensor_copy_
Repro:
Comment out https://github.com/pytorch/pytorch/blob/e203aa9fab290e3baf66289568cf614cc9f34621/test/inductor/test_cuda_cpp_wrapper.py#L111, and then run 
```
TORCHINDUCTOR_ABI_COMPATIBLE=1 python test/inductor/test_cuda_cpp_wrapper.py -k test_multi_device_cuda
```

Error:
```
Output:
In file included from /data/users/binbao/pytorch/torch/include/torch/csrc/inductor/aoti_runtime/arrayref_tensor.h:3,
                 from /tmp/torchinductor_binbao/iw/ciwj3ypfsejr725rlcittslsy7aeekpezl7xqdln6yx6emhjd4ym.cpp:4:
/tmp/torchinductor_binbao/iw/ciwj3ypfsejr725rlcittslsy7aeekpezl7xqdln6yx6emhjd4ym.cpp: In function ‘void inductor_entry_impl(AtenTensorOpaque**, AtenTensorOpaque**)’:
/tmp/torchinductor_binbao/iw/ciwj3ypfsejr725rlcittslsy7aeekpezl7xqdln6yx6emhjd4ym.cpp:202:99: error: cannot convert ‘torch::aot_inductor::ArrayRefTensor<float>’ to ‘AtenTensorHandle’ {aka ‘AtenTensorOpaque*’}
  202 |     AOTI_TORCH_ERROR_CODE_CHECK(aoti_torch_tensor_copy_(expensive_copy_to_tensor_if_needed(buf0), buf1));
      |                                                                                                   ^~~~
      |                                                                                                   |
      |                                                                                                   torch::aot_inductor::ArrayRefTensor<float>
/data/users/binbao/pytorch/torch/include/torch/csrc/inductor/aoti_runtime/utils.h:34:8: note: in definition of macro ‘AOTI_TORCH_ERROR_CODE_CHECK’
   34 |   if ((call) != AOTI_TORCH_SUCCESS) {           \
      |        ^~~~
In file included from /data/users/binbao/pytorch/torch/include/torch/csrc/inductor/aoti_torch/generated/c_shim_cuda.h:4,
                 from /tmp/torchinductor_binbao/iw/ciwj3ypfsejr725rlcittslsy7aeekpezl7xqdln6yx6emhjd4ym.cpp:2:
/data/users/binbao/pytorch/torch/include/torch/csrc/inductor/aoti_torch/c/shim.h:382:64: note:   initializing argument 2 of ‘AOTITorchError aoti_torch_tensor_copy_(AtenTensorHandle, AtenTensorHandle)’
  382 | aoti_torch_tensor_copy_(AtenTensorHandle src, AtenTensorHandle dst);
      |                                               ~~~~~~~~~~~~~~~~~^~~
In file included from /data/users/binbao/pytorch/torch/include/torch/csrc/inductor/aoti_runtime/arrayref_tensor.h:3,
                 from /tmp/torchinductor_binbao/iw/ciwj3ypfsejr725rlcittslsy7aeekpezl7xqdln6yx6emhjd4ym.cpp:4:
/tmp/torchinductor_binbao/iw/ciwj3ypfsejr725rlcittslsy7aeekpezl7xqdln6yx6emhjd4ym.cpp:222:99: error: cannot convert ‘torch::aot_inductor::ArrayRefTensor<float>’ to ‘AtenTensorHandle’ {aka ‘AtenTensorOpaque*’}
  222 |     AOTI_TORCH_ERROR_CODE_CHECK(aoti_torch_tensor_copy_(expensive_copy_to_tensor_if_needed(buf4), buf5));
      |                                                                                                   ^~~~
      |                                                                                                   |
      |                                                                                                   torch::aot_inductor::ArrayRefTensor<float>
/data/users/binbao/pytorch/torch/include/torch/csrc/inductor/aoti_runtime/utils.h:34:8: note: in definition of macro ‘AOTI_TORCH_ERROR_CODE_CHECK’
   34 |   if ((call) != AOTI_TORCH_SUCCESS) {           \
      |        ^~~~
In file included from /data/users/binbao/pytorch/torch/include/torch/csrc/inductor/aoti_torch/generated/c_shim_cuda.h:4,
                 from /tmp/torchinductor_binbao/iw/ciwj3ypfsejr725rlcittslsy7aeekpezl7xqdln6yx6emhjd4ym.cpp:2:
/data/users/binbao/pytorch/torch/include/torch/csrc/inductor/aoti_torch/c/shim.h:382:64: note:   initializing argument 2 of ‘AOTITorchError aoti_torch_tensor_copy_(AtenTensorHandle, AtenTensorHandle)’
  382 | aoti_torch_tensor_copy_(AtenTensorHandle src, AtenTensorHandle dst);
      |                                               ~~~~~~~~~~~~~~~~~^~~
   ```

### PR DESCRIPTION
**Pull request by trieuat**
fixes #123039

In abi mode, ExternKernelSchedulerNode generates code using `aoti_torch_tensor_copy_` which requires `AtenTensorHandle`, but the allocation generates ArrayRefTensor to allocate mem in stack. To fix this issue, this PR prevents ExternKernelSchedulerNode from using stack-mem-allocation in abi, and creates AtenTensorHandle instead. 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel @voznesenskym @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @LucasLLC

### CODE REVIEW

**Review by desertfire — CHANGES_REQUESTED** [review]
Better to update can_stack_allocate_buffer, https://github.com/pytorch/pytorch/blob/87f651c7e7197f7d45a205bca680444a8985d373/torch/_inductor/codegen/cpp_wrapper_cpu.py#L1386, where you can read if `buffer` is `ExternKernel`.

**Comment by trieuat** [comment]
I considered about it, it is cleaner to change inside `can_stack_allocate_buffer` but I wanted to make sure it didn't affect non-abi so went with the change inside the `abi_compatible` check. 

If you think changing in `can_stack_allocate_buffer` is ok, I will update it.

**Review by desertfire — APPROVED** [review]
Not sure if CI failures are related. You can rebase to make sure them pass before landing.

**Review by desertfire — APPROVED** [review]

**Comment by trieuat** [comment]
@jeanschmidt do you know how I can find more info about the regression?

@desertfire should we move the change inside the ABI check to minimize the effect?

**Comment by desertfire** [comment]
> @jeanschmidt do you know how I can find more info about the regression?
> 
> @desertfire should we move the change inside the ABI check to minimize the effect?

I found https://github.com/pytorch/pytorch/actions/runs/8777179984/job/24082280091 on HUD, but I don't think this PR should cause the problem. @trieuat, please create a reland PR to see if the problem persists.

**Comment by trieuat** [comment]
@desertfire I confirm the regression (from `buck2 test '@fbcode//mode/opt' fbcode//accelerators/workloads/models/slimdsnn:slimdsnn_dso_benchmark_test -- --exact 'accelerators/workloads/models/slimdsnn:slimdsnn_dso_benchmark_test - SlimDSNNbenchmark.DSObenchmark'`). I move the change to inside the abi check and confirm there is no regression, let me know what you think.

**Comment by desertfire** [comment]
> D56623194

No that won't help. SlimDSNN uses the abi mode. Feel free to ping me on workchat for more information.

**Pull request closed without merging**
