### PR TITLE
faster batch sampler

### LINKED ISSUE #76950: Faster BatchSampler
### 🚀 The feature, motivation and pitch

`BatchSampler` uses some time-consuming operation such as `append` and `len` which can be avoided:
https://github.com/pytorch/pytorch/blob/e9f34931ef5a4172eac1cc2238218b94beb59b28/torch/utils/data/sampler.py#L237-L238

To speed it up, when `drop_last==True`, we can simply use the following code:
```python
sampler_iter = iter(self.sampler)
while True:
    try:
        batch = [next(sampler_iter) for _ in range(self.batch_size)]
        yield batch
    except StopIteration:
        break
```

For `drop_last==False`, we can also speed it up by the following code: 
```python
batch = [0] * self.batch_size
idx_in_batch = 0
for idx in self.sampler:
    batch[idx_in_batch] = idx
    idx_in_batch += 1
    if idx_in_batch == self.batch_size:
        yield batch
        idx_in_batch = 0
        batch = [0] * self.batch_size
if idx_in_batch > 0:
    yield batch[:idx_in_batch]
```

### Alternatives

_No response_

### Additional context

My test env and setting:
```
os: Centos
cpu: Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz
python: 3.8.12  and  3.6.8

Baseline: current master of pytorch repo
```

Test Result of python 3.8.12:
```
batch size: 64, drop last: True -- speedup: 85.41%
batch size: 64, drop last: False -- speedup: 24.84%
batch size: 640, drop last: True -- speedup: 108.77%
batch size: 640, drop last: False -- speedup: 22.20%
batch size: 6400, drop last: True -- speedup: 109.78%
batch size: 6400, drop last: False -- speedup: 17.79%
batch size: 64000, drop last: True -- speedup: 113.49%
batch size: 64000, drop last: False -- speedup: 17.85%
```

Test Result of python 3.6.8:
```
batch size: 64, drop last: True -- speedup: 53.73%
batch size: 64, drop last: False -- speedup: 50.03%
batch size: 640, drop last: True -- speedup: 65.83%
batch size: 640, drop last: False -- speedup: 47.00%
batch size: 6400, drop last: True -- speedup: 67.17%
batch size: 6400, drop last: False -- speedup: 45.72%
batch size: 64000, drop last: True -- speedup: 68.68%
batch size: 64000, drop last: False -- speedup: 44.11%
```

cc @VitalyFedyunin @ejguan @NivekT

### PR DESCRIPTION
**Pull request by didicout**
Fixes #76950

Improve the performance of iteration on `BatchSampler` , especially when `batch_size` is big.

Python 3.6.8:
```
  batch_size  drop_last      origin(avg)    origin(std)   new(avg)   new(std)  speedup
------------  -----------  -------------  -------------  ---------  ---------  -------
           4  True                 0.026      0.0001183      0.032  0.0004839  -18.07%
           4  False                0.026      2.326e-05      0.022  3.317e-05  15.92% 
           8  True                 0.025      0.0001441      0.023  0.0001204  9.43%
           8  False                0.025      4.457e-05      0.019  3.951e-05  30.90% 
          64  True                 0.024      0.0005505      0.015  0.0002987  54.99%
          64  False                0.023      8.014e-05      0.016  1.999e-05  49.64% 
         640  True                 0.024      0.0005598      0.015  2.327e-05  66.26%
         640  False                0.024      2.229e-05      0.016  2.358e-05  48.32% 
        6400  True                 0.025      0.0005789      0.015  2.935e-05  69.06%
        6400  False                0.025      2.529e-05      0.017  6.737e-05  45.17% 
```

Python 3.8.12:
```
  batch_size  drop_last      origin(avg)    origin(std)   new(avg)   new(std)  speedup
------------  -----------  -------------  -------------  ---------  ---------  -------
           4  True                 0.017      0.0001389      0.019  3.026e-05  -10.50%
           4  False                0.017      9.909e-06      0.017  2.37e-05   -0.78% 
           8  True                 0.016      1.251e-05      0.013  2.748e-05  24.40%
           8  False                0.016      5.523e-05      0.015  1.156e-05  10.20% 
          64  True                 0.015      2.483e-05      0.008  1.859e-05  90.96%
          64  False                0.015      2.622e-05      0.012  3.227e-05  26.09% 
         640  True                 0.016      6.405e-05      0.007  1.836e-05  112.88%
         640  False                0.016      1.284e-05      0.013  0.0004079  20.09% 
        6400  True                 0.016      8.298e-05      0.008  1.507e-05  111.80%
        6400  False                0.016      1.716e-05      0.014  0.0004602  18.37% 

```

Check the issue page for more details of the tests.

### CODE REVIEW

**Review by ejguan — COMMENTED** [review]
Thank you for proactively trying to make batchsampler better. Do you mind listing the performance gain in the PR summary with your testing script? Besides, I also commented about adding a few tests with batchsize 4 or 8 in the issue.

**Review by ejguan — COMMENTED** [review]
Please ping me when you have PR summary ready! Really appreciate your work.

**Comment by didicout** [comment]
@ejguan    Done. :)

**Review by ejguan — APPROVED** [review]
LGTM

**Comment by didicout** [comment]
> Do you mind also adding std to the table in summary? Thank you

Done. :)

**Pull request closed without merging**
