### PR TITLE
[c10d][UCC] Add `_reduce_scatter_base` to `c10d::ProcessGroupUCC`

### PR DESCRIPTION
**Pull request by samnordmann**
cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Comment by wconstab** [comment]
just for my curiosity, what is the motivation for using UCC?  (compared to Gloo, perhaps)

**Comment by samnordmann** [comment]
> just for my curiosity, what is the motivation for using UCC? (compared to Gloo, perhaps)

UCC fully supports host and device memory, many different transports (IB, Sharp, mlx5dv, cuda, ROCm), and achieves state-of-the-art performance, with low GPU SM usage.
https://ieeexplore.ieee.org/document/10664373

**Review by kwen2501 — APPROVED** [review]
lgtm

**Comment by kwen2501** [comment]
Hi, first, thanks for the contribution. 
We are thinking of periodically reviewing torch's hosting of backend implementations.
If you could share some libraries / users that are using ProcessGroupUCC, that would help with the review.
Thanks!

**Comment by samnordmann** [comment]
> Hi, first, thanks for the contribution. We are thinking of periodically reviewing torch's hosting of backend implementations. If you could share some libraries / users that are using ProcessGroupUCC (that are okay to be publicly known), that would help with the review. Thanks!

Hi, here is a (probably non-exhaustive) list of other libraries using ProcessGroupUCC

- NEMO - [Enabling UCC backend for PP communication by youngeunkwon0405 · Pull Request #10531 · NVIDIA/NeMo](https://github.com/NVIDIA/NeMo/pull/10531)
- Megatron - [Enabling UCC backend for PP communication by youngeunkwon0405 · Pull Request #1157 · NVIDIA/Megatron-LM](https://github.com/NVIDIA/Megatron-LM/pull/1157)
- nvFuser https://github.com/NVIDIA/Fuser/blob/96d64b61612f3248062c7d17c68582f94b92e37c/csrc/multidevice/communicator.cpp#L165
- PARAM - [Support benchmarking UCC backend through PyTorch in PARAM-Comms by kingchc · Pull Request #14 · facebookresearch/param](https://github.com/facebookresearch/param/pull/14)
- DLRM by Meta - [Added torch_ucc support by artemry-nv · Pull Request #173 · facebookresearch/dlrm](https://github.com/facebookresearch/dlrm/pull/173) (https://ucfconsortium.org/wp-content/uploads/2021/02/Joshua_Ladd_UCC_PG_UCFvF2F_Dec2020_v7_jss.pdf)
- Mixing AMD and NVIDIA GPUs - [Question about failing collective allreduce across on non-homogenous ring (NVIDIA and AMD GPU) · Issue #1043 · openucx/ucc](https://github.com/openucx/ucc/issues/1043)

**Pull request closed without merging**
