### PR TITLE
[FSDP] casting input args with dataclass(frozen=True)

### PR DESCRIPTION
**Pull request by weifengpy**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #135156
* __->__ #135067

resolve: https://github.com/pytorch/pytorch/pull/135029

when enabling mixed precision, FSDP cast input args to desired dtype by calling `_apply_to_tensors`. When input args has `dataclass(frozen=True)`, we hit following runtime error, because of using `setattr` in `_apply_to_tensors`

`dataclasses.FrozenInstanceError: cannot assign to field 'some_key'`. The fix is to use dataclasses api `dataclasses.replace` 

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by awgu — APPROVED** [review]
Thanks for taking the time to add the unit test!

**Comment by nikonikolov** [comment]
Thanks a lot taking over! Would it be possible that this lands in the next stable release?

**Comment by weifengpy** [comment]
> Thanks a lot taking over! Would it be possible that this lands in the next stable release?

I can ask around about the cherry-pick process and see if it can make it to next public release

**Pull request closed without merging**
