### PR TITLE
HTA docs

### PR DESCRIPTION
**Pull request by anupambhatnagar**
Added documentation for Holistic Trace Analysis

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @svekars @carljparker @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @kiukchung @d4l3k @lucasllc

### CODE REVIEW

**Review by aaronenyeshi — APPROVED** [review]
Thank you for adding the Open Source HTA documentation!

**Comment by malfet** [comment]
Hmm, does it really belongs in PyTorch repo? Rather than to pytorch.github.io?

**Pull request closed without merging**
