### PR TITLE
Adds truncated normal initializer

### PR DESCRIPTION
**Pull request by Enealor**
This adds the `trunc_normal_` function to `torch.nn.init` which allows for modifying tensors in-place to values drawn from a truncated normal distribution. I chose to use the inverse CDF method to implement this. I have included the appropriate code in `test_nn.py` for verifying that the values are from the correct distribution.

Reasons I chose this method:
1. Easily implemented to operate on memory in place, as the other initializers are.
1. No resampling delays
1. This method's main weakness is unlikely to be an issue. While the inverse CDF method can fail to generate the correct distribution when `b < mean` or `mean < a`,  I expect users will choose `a` and `b` so that `a < mean < b`. This method is extremely effective in this case.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 288beabc:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=288beabc1281bd7d604528ba5b13e824854f8ffe).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4299932) pytorch_linux_backward_compatibility_check_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=88325376) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=88325376))
<details>
<summary>
<code>Jan 18 21:48:58 The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not.</code>
</summary>

```
Jan 18 21:48:58 processing existing schema:  aten::values(Dict(str, t) self) -> (t[](*)) 
Jan 18 21:48:58 processing existing schema:  aten::values(Dict(int, t) self) -> (t[](*)) 
Jan 18 21:48:58 processing existing schema:  aten::values(Dict(float, t) self) -> (t[](*)) 
Jan 18 21:48:58 processing existing schema:  aten::values(Dict(Tensor, t) self) -> (t[](*)) 
Jan 18 21:48:58 processing existing schema:  aten::view(Tensor(a) self, int[] size) -> (Tensor(a)) 
Jan 18 21:48:58 processing existing schema:  aten::where(Tensor condition) -> (Tensor[]) 
Jan 18 21:48:58 processing existing schema:  aten::where.self(Tensor condition, Tensor self, Tensor other) -> (Tensor) 
Jan 18 21:48:58 processing existing schema:  aten::zeros_like(Tensor self, *, int? memory_format=None) -> (Tensor) 
Jan 18 21:48:58 processing existing schema:  aten::zeros_like.dtype(Tensor self, *, int dtype, int layout, Device device, bool pin_memory=False, int? memory_format=None) -> (Tensor) 
Jan 18 21:48:58 processing existing schema:  prim::Constant() -> (...) 
Jan 18 21:48:58 The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not.  
Jan 18 21:48:58  
Jan 18 21:48:58 Broken ops: [ 
Jan 18 21:48:58 	_TorchScriptTesting_StackString::merge(torch.classes._TorchScriptTesting_StackString _0, torch.classes._TorchScriptTesting_StackString _1) -> () 
Jan 18 21:48:58 	_TorchScriptTesting_StackString::clone(torch.classes._TorchScriptTesting_StackString _0) -> (torch.classes._TorchScriptTesting_StackString _0) 
Jan 18 21:48:58 ] 
Jan 18 21:48:58 =================== sccache compilation log =================== 
Jan 18 21:48:58 + cleanup 
Jan 18 21:48:58 + retcode=1 
Jan 18 21:48:58 + set +x 
Jan 18 21:48:58 =========== If your build fails, please take a look at the log above for possible reasons =========== 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by Enealor** [comment]
Addresses part of #32293 by adding a truncated normal initializer. @cossio

**Comment by Enealor** [comment]
The current version is passing the available checks. Any suggestions on changes or does it look good? @alicanb @cossio

**Comment by ezyang** [comment]
Tentatively assigning review to @alicanb, let me know if you need someone else to look

**Comment by alicanb** [comment]
I am happy to do it after the ICML deadline :D

**Comment by alicanb** [comment]
This mostly looks good. Maybe one thing I would add is a warning if bounds are too far away from the center (I actually don't know when it will break, it might be a good idea to test that and place the warnings accordingly). I see you're only testing truncnorm(0,1,-2, 2) in `test_trunc_normal`, it might be nice to add tests for various upper and lower bounds as well.

**Comment by Enealor** [comment]
@alicanb Thanks for the feedback. I experimented with randomly selected `a` and `b` for the truncated standard normal. It seems that the most common failure point is to choose `mean` more than 2 standard deviations from the interval `[a, b]`. In this situation, the method fails to be statistically similar to Scipy's truncated normal. It can also fail if `mean` is closer to the interval but `b-a` is particularly small (around 1e-6).

With that, I will add a warning if either `a` is 2 standard deviations more than `mean` or `b` is 2 standard deviations less than `mean`. I'll update the documentation to clarify that either `mean` should be in the interval `[a, b]`, or the distribution may be incorrect for particularly small `b-a`. I don't have enough info to turn this into a particular warning though.

Below is the code I used to test various results. I have also attached some example failures. The currently chosen range for values of `a` will typically pass. If `a` is chosen from the interval `[3, 5]`, failures will start to occur. Similarly, if `b` is changed so that smaller numbers are more likely, then failures will start to become more frequent.
```
import torch, scipy, random
from scipy.stats import kstest
from torch.nn import init
def _is_trunc_normal(tensor, mean, std, a, b):
    p_value = scipy.stats.kstest(tensor.flatten().tolist(), 'truncnorm', args=(a, b))[1]
    return p_value


if __name__ == '__main__':
    input_tensor = torch.empty((10, 10, 20))
    for _ in range(1000):
        a = random.uniform(3, 3)
        b = random.uniform(a, a + 1)
        init.trunc_normal_(input_tensor.flatten(), mean=0., std=1., a=a, b=b)

        p_value = _is_trunc_normal(input_tensor, 0., 1., a, b)
        if p_value <= 0.0001:
            print("Failed for interval [{0:.3}, {1:.3}], length {2:.3}".format(a, b, b-a))

# Failed for interval [4.98, 5.18], length 0.202
# Failed for interval [3.87, 3.87], length 0.00138
# Failed for interval [2.89, 2.89], length 0.000154
```

**Comment by Enealor** [comment]
I updated the warning message to be more descriptive and report at the appropriate stack level. The current message triggers if the mean is too far from the interval. For example,
```
t = torch.zeros((1, 10))
init.trunc_normal_(t, 3, 0.1, -2, 2) # mean is 3, std is .1, truncated to [-2, 2]
# __main__:1: UserWarning: mean is more than 2 std from [a, b] in nn.init.trunc_normal_.
# The distribution of values may be incorrect.
```

**Comment by ezyang** [comment]
@alicanb let me know when to land!

**Comment by alicanb** [comment]
LGTM, sorry I forgot about this.

**Review by ezyang — APPROVED** [review]

**Comment by cossio** [comment]
Great! So this will be out in the next PyTorch minor version? Any estimate for when that'll be? Thanks!

**Pull request closed without merging**
