### PR TITLE
Fix RenamePlanner documentation

### LINKED ISSUE #107490: Incorrect code snippet for SavePlanner
### 📚 The doc issue

The following code snippet [here](https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.SavePlanner) is wrong
```
class RenamePlanner(DefaultSavePlanner):
    def set_up_planner(self, state_dict, is_coordinator):
        # prefix all keys with `foo_``
        super().set_up_planner(self, {"foo_" + k: v for k, v in state_dict.items()}, is_coordinator)
```

### Suggest a potential alternative/fix

```
class RenamePlanner(DefaultSavePlanner):
    def set_up_planner(self, state_dict, is_coordinator):
        # prefix all keys with `foo_``
        super().set_up_planner({"foo_" + k: v for k, v in state_dict.items()}, is_coordinator)
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu

### PR DESCRIPTION
**Pull request by b-chu**
Fixes #107490

### CODE REVIEW

**Review by awgu — APPROVED** [review]

**Comment by b-chu** [comment]
I don't have permission to merge @awgu

**Comment by awgu** [comment]
Can you sign the CLA?

**Comment by b-chu** [comment]
Done, thanks

**Comment by awgu** [comment]
Trunk failure is unrelated:
[linux-jammy-py3.9-clang12-asan / test (default, 1, 6, linux.4xlarge)](https://hud.pytorch.org/pr/pytorch/pytorch/107535#16045568281)

**Review by fduwjj — APPROVED** [review]

**Pull request closed without merging**
