### PR TITLE
[Device] Add mps as device type in `torch._utils._get_available_device_type()`

### PR DESCRIPTION
**Pull request by shink**
As the title states

cc: @ezyang @albanD @malfet @FFFrog @jgong5 @guangyey

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by shink** [comment]
Seems failures are unrelated

**Comment by FFFrog** [comment]
> Seems failures are unrelated

Try rerunning first, if that doesn't work you can try to rebase it again later.

**Pull request closed without merging**
