### PR TITLE
[AOTI] Handle empty input args

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #114682

Summary: When the model takes no inputs, AOTInductor relies on checking weights to figure out which device to compile the model into. Currently recording buffer device type happens too late, and this PR fixes that.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by chenyang78 — APPROVED** [review]

**Comment by chenyang78** [comment]
BTW, the failing test looks real. Please take a look. Thanks.

**Comment by desertfire** [comment]
> BTW, the failing test looks real. Please take a look. Thanks.

@eellison , `test_empty_cpu_tensor` fails because now we correctly recognize there are two devices in the graph, cuda and cpu, and thus this checking fails, https://github.com/pytorch/pytorch/blob/453d509b736196a0defe35bb108dead5db4f77be/torch/_inductor/compile_fx.py#L360. I saw your https://github.com/pytorch/pytorch/pull/114144, which looks like a very special case. Was it meant to solve some specific problem?

**Comment by eellison** [comment]
@desertfire this is a real case that we observed for internal workloads. if there is an empty, no-data output tensor, we shouldn't skip cudagraphs for it

**Pull request closed without merging**
