### PR TITLE
enable bf16 emb

### PR DESCRIPTION
**Pull request by zhuhaozhe**
Merge https://github.com/pytorch/pytorch/pull/89199 and https://github.com/pytorch/pytorch/pull/91949 into one PR.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by zhuhaozhe** [comment]
Hi, @jianyuh. I do not know why FBGEMM is changed in https://github.com/pytorch/pytorch/pull/93895, I just updated it again in this PR.

**Review by jianyuh — APPROVED** [review]

**Comment by jianyuh** [comment]
Re "why FBGEMM is changed in https://github.com/pytorch/pytorch/pull/93895":

I guess @malfet  is fixing some MacOS OpenMP issue. It should be safe to keep the latest version of FBGEMM.

**Comment by malfet** [comment]
> Re "why FBGEMM is changed in #93895":
> 
> I guess @malfet is fixing some MacOS OpenMP issue. It should be safe to keep the latest version of FBGEMM.

Sorry, that was a mistake. I didn't need to make any submodule update, but they are often hard to catch. I'll prioritize working on lint check that prevents accidental updates

**Review by malfet — APPROVED** [review]

**Review by jgong5 — APPROVED** [review]

**Comment by Skylion007** [comment]
> > Re "why FBGEMM is changed in #93895":
> > I guess @malfet is fixing some MacOS OpenMP issue. It should be safe to keep the latest version of FBGEMM.
> 
> Sorry, that was a mistake. I didn't need to make any submodule update, but they are often hard to catch. I'll prioritize working on lint check that prevents accidental updates

@malfet pre-commit has a check for that if you need a reference: https://github.com/pre-commit/pre-commit-hooks

**Comment by malfet** [comment]
> @malfet pre-commit has a check for that if you need a reference: https://github.com/pre-commit/pre-commit-hooks

We have lintrunner, but I guess a bit of a challenge is to connect it to PR message (rather than to a commit message title)

**Pull request closed without merging**
