### PR TITLE
Use linux.large.arc for stale workflow

### PR DESCRIPTION
**Pull request by DanilBaibak**
Try linux.large.arc for stale workflow

### CODE REVIEW

**Comment by jeanschmidt** [comment]
We first need to fix/merge actionlint

**Comment by DanilBaibak** [comment]
Tested:
Screenshot 2023-12-11 at 15 29 46

**Review by malfet — APPROVED** [review]
LGTM, though would appreciate a test (for example, by adding `workflow-dispatch:`)

**Review by jeanschmidt — APPROVED** [review]

**Pull request merged**
