### PR TITLE
DOC: remove git stamp from release documentation version

### PR DESCRIPTION
**Pull request by mattip**
CI built the documentation for the recent 1.9.0rc1 tag, but left the git version in the `version`, so (as of now) going to https://pytorch.org/docs/1.9.0/index.html and looking at the version in the upper-left corner shows "1.9.0a0+git5f0bbb3" not "1.9.0". This PR should change that to cut off everything after and including the "a".

It should be cherry-picked to the release/1.9 branch so that the next rc will override the current documentation with a "cleaner" version.

@brianjo

### CODE REVIEW

**Review by brianjo — APPROVED** [review]

**Comment by brianjo** [comment]
@malfet Nikita, can you merge this when you get a chance? Thanks!

**Comment by malfet** [comment]
@mattip wouldn't that also cut git version for the docs generated from the main branch?

**Comment by mattip** [comment]
The change is bracketed by a `if RELEASE:` clause, so it will only be activated when `RELEASE` is True, which should only happen for a tagged build (when `$CIRCLE_TAG` exists), due to this CI config https://github.com/pytorch/pytorch/blob/0e16087064bb1eac9f3b82fc1e47532aaf396ce9/.circleci/config.yml#L1277

**Comment by mattip** [comment]
Has this been imported?

**Pull request closed without merging**
