### PR TITLE
[MPS] Fast math env var

### PR DESCRIPTION
**Pull request by qqaatw**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #129451
* #129350
* #129105
* __->__ #129007

Allow users to decide whether they want to have fast math enabled via env var

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
Do you mind landing it separately from the rest of the stack?
Also, it would be nice to do it not just thru the environment variable, but via property as well, something like `torch.backends.mps.use_fast_math`?

Also, I feel like we are at the point when it's probably time to start compiling those offline rather than during first use of the op, so it would not be helpful anyway

**Comment by qqaatw** [comment]
> Do you mind landing it separately from the rest of the stack? Also, it would be nice to do it not just thru the environment variable, but via property as well, something like `torch.backends.mps.use_fast_math`?
> 
> Also, I feel like we are at the point when it's probably time to start compiling those offline rather than during first use of the op, so it would not be helpful anyway

Hmm where do we usually store this kind of state, in python or c++? can I use the environment variable as proxy (ground truth) such that the property and environment variable are synchronized?

**Comment by qqaatw** [comment]
@malfet if we plan to compile the kernels offline, let's not put much effort on adding the property `torch.backends.mps.use_fast_math`  here and get it merge as is?

**Review by malfet — APPROVED** [review]
Sure

**Pull request closed without merging**
