### PR TITLE
Upgrade submodule sleef to fix build warning

### PR DESCRIPTION
**Pull request by xuhancn**
Subsequent PR to https://github.com/pytorch/pytorch/pull/118980, fix sleef build warning.

submodule sleef, include this sleef PR: https://github.com/shibatch/sleef/pull/514

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Comment by zou3519** [comment]
See https://github.com/pytorch/pytorch/pull/118980#issuecomment-2009660591

**Comment by xuhancn** [comment]
Close by update it in https://github.com/pytorch/pytorch/pull/118980

**Pull request closed without merging**
