### PR TITLE
bitwise_and: Port to structured

### PR DESCRIPTION
**Pull request by Freey0**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #61349 OpInfo: bitwise_and
* **#60813 bitwise_and: Port to structured**
* #60812 bitwise_xor: Port to structured
* #60811 bitwise_or: Port to strucutred
* #60817 logit_backward: Port to structured
* #60816 tanh_backward: Port to structured
* #60815 sigmoid_backward: Port to structured
* #60814 xlogy: Port to structured
* #60810 fmin has been ported to the structured kernel, removing the old implementation
* #60809 fmod: Port to structured

Differential Revision: [D29449374](https://our.internmc.facebook.com/intern/diff/D29449374)

### CODE REVIEW

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29449374).

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
This one gonna need XLA update

**Comment by JackCaoG** [comment]
This pr seems to remove the constrain of 
```
    # PRED cannot be automatically promoted to other dtypes in bitwise ops.
```

for bitwise and, which xla happens to have a test on. Is this intentional? Should pt/xla follow the same guidance and remove the constrain of this kind of type promotion?

**Comment by ezyang** [comment]
No, I'm guessing this is unintentional, and not exercised in any of PyTorch's native tests. Thanks for identifying the issue.

**Comment by ezyang** [comment]
Oof but I don't understand how this PR could cause the behavior change :(

**Comment by ezyang** [comment]
OK actually this is pretty weird.

```
>>> c = torch.zeros(2) >= 1
>>> c.byte() | c
tensor([0, 0], dtype=torch.uint8)
>>> c | c.byte()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: result type Byte can't be cast to the desired output type Bool
```

This seems wrong. The reason this happens is because of how the output used to be allocated in the functional case:

```
Tensor bitwise_and(const Tensor& self, const Tensor& other) {
  Tensor result = at::empty({0}, self.options());
  at::bitwise_and_out(result, self, other);
  return result;
}
```

aka bitwise_and always takes on the type of its first argument, but then casting is not disabled.

numpy is willing to promote both ways

```
>>> c | c.astype('byte')
array([[1, 1]], dtype=int8)
>>> c.astype('byte') | c
array([[1, 1]], dtype=int8)
>>> c
```

so actually seems like the new behavior is correct. @Freey0 as a follow up we should add tests for this bug.

**Comment by ezyang** [comment]
@JackCaoG what do you think of this analysis?

**Comment by JackCaoG** [comment]
@ezyang I think it is fair. Original comment on xla test(by Ailing) also mentioned that this behavior is not aligned with numpy and might change in the future. I guess now is the future 😄 . I will update xla to remove this constrain.

**Comment by JackCaoG** [comment]
@ezyang I think I fixed the XLAOP casting part to allow this type promotion but I had an [check](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_xla_type.cpp#L170) that I borrowed from pytorch that failed

```
void CheckBinaryOpTypePromotion(const at::Tensor& out, const at::Tensor& self,
                                const at::Tensor& other) {
  at::ScalarType resultType = at::result_type(self, other);
  XLA_CHECK(at::canCast(/*from=*/resultType, /*to=*/out.scalar_type()));
}
```
when I do `xla_c & xla_c.byte()`

I think this is part of the functional case you mentioned because `out.scalar_type()` changed as I swap between `xla_c.byte() & xla_c `(result type: Byte out type Byte) and `xla_c & xla_c.byte()`(result type: Byte out type Bool).

How does structured binary op performs type checking for input and output? Does pt/xla need to care about the type checking in this case(not sure if it is always done by pytorch structuredop )?

**Comment by ezyang** [comment]
> Does pt/xla need to care about the type checking in this case(not sure if it is always done by pytorch structuredop )?

For now, still yes, because you are writing regular XLA kernels and not structured XLA kernels (that was along the lines of what @bdhirsh was working on)

> How does structured binary op performs type checking for input and output?

It seems like the meta function seems to imply it's normal type promotion:

```
TORCH_META_FUNC2(bitwise_and, Tensor) (const Tensor& self, const Tensor& other) {
  build_borrowing_binary_op(maybe_get_output(), self, other);
}
```

If you implement this the same way, e.g., add, is implemented, does that give you the correct behavior?

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29449374).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29449374).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29449374).

**Pull request closed without merging**
