### PR TITLE
Remove PROCESS GROUP rpc backend

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#62411 Remove PROCESS GROUP rpc backend**

This removes the PROCESS GROUP backend from rpc. The BackendType PROCESS_GROUP will still be available to the user, but will throw an error if they try to use it.

This PR does not remove process_group_agent.h/cpp because of internal fb dependencies. Removal of those files and updating internal code will come in a separate PR.

Differential Revision: [D29990408](https://our.internmc.facebook.com/intern/diff/D29990408)

### CODE REVIEW

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29990408).

**Review by mrshenli — COMMENTED** [review]
Test failures are real:

```
Jul 29 18:44:35 terminate called after throwing an instance of 'pybind11::error_already_set'
Jul 29 18:44:35   what():  AttributeError: module 'torch.distributed.rpc' has no attribute 'ProcessGroupRpcBackendOptions'
```

**Review by mrshenli — COMMENTED** [review]
I think the error would disappear if #62409 removes `test_faulty_agent` and then rebase this one. (or stack this PR on top of #62409)

**Comment by mrshenli** [comment]
> I think the error would disappear if #62409 removes test_faulty_agent and then rebase this one. (or stack this PR on top of #62409)

This assessment was wrong, as @H-Huang pointed out that `test_faulty_agent` uses TensorPipe agent.

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29990408).

**Comment by H-Huang** [comment]
Thanks Shen, I needed to rebase from #62409. The test failures should be fixed now, but will double check again once they all complete.

**Review by mrshenli — APPROVED** [review]
Stamp to unblock. Please wait for tests.

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29990408).

**Pull request closed without merging**
