### PR TITLE
Avoid creating extra tensor when matching conj and neg

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #79125

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Sounds ok to me. But I'll let Anjali check as well.

**Review by anjali411 — APPROVED** [review]
LGTM. just add a comment to explain why calling `_set_conj` and `_set_neg` is required and ok here

**Pull request closed without merging**
