### PR TITLE
added missing mps reference to docu

### PR DESCRIPTION
**Pull request by kleinicke**
### Description
The table at the beginning missed the mps backend, which has its own chapter in the file.

### CODE REVIEW

**Review by H-Huang — APPROVED** [review]
Thanks for adding!

**Comment by kleinicke** [comment]
It seems like the test failed for some reason not related to this pull request. Can it be rerun?

**Comment by H-Huang** [comment]
@kleinicke Sorry for the delay in response, I missed this. Could you sign the Linux Foundation CLA above?

**Pull request closed without merging**
