### PR TITLE
[cuDNN][SDPA] Fix cudnn frontend dBias check

### PR DESCRIPTION
**Pull request by eqy**
For #137347

Temporary workaround until cuDNN frontend fixes the extraneous dBias check (currently it is checked even if dBias is not used, and PyTorch does not use dBias).

cc @csarofeen @ptrblck @xwang233 @drisspg @mikaylagawarecki

### CODE REVIEW

**Comment by eqy** [comment]
Oof looks like a botched patch to `cudnn_frontend`...

**Review by drisspg — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Review by malfet — CHANGES_REQUESTED** [review]
Hmm, does the new commit points to the main branch or to your PR? If later, we should not land it until change reached cudnn trunk

**Comment by Skylion007** [comment]
@eqy Not seeing the commit this reference being pushed anywhere. Opened a relevant issue on cudnn_frontend

**Comment by eqy** [comment]
closing in favor of #138725

**Pull request closed without merging**
