### PR TITLE
Delete caffe2/contrib/cuda-convnet2

### PR DESCRIPTION
**Pull request by ezyang**
This code is not Python 3 compatible and it is causing problems for some of our users. @orionr do we still need it?

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by orionr — APPROVED** [review]
This exposes CUDAConvNetLocallyConnectedOp as well as other ops, so might be used internally. I'd recommend we move it to be internal-only and have it not be on GitHub if we need it.

cc @Yangqing and @dzhulgakov who might know where it's used, but @BIT-silence added it.

**Comment by gottbrath** [comment]
I just checked on this because I see that it didn't get through CI .. all of the CI failures are on Mac OS X and are due to an unrelated change in a dependency. The error that shows up in the build is:


Error: Cannot install moreutils because conflicting formulae are installed.
  parallel: because Both install a `parallel` executable.

Please `brew unlink parallel` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
Exited with code 1

**Comment by gottbrath** [comment]
just an update here: I'm checking how this contrib package is used in our internal build system and how to cleanly make the changes so as not to cause any negative side effects here at FB. From an OSS repo perspective this looks good and I think as soon as I fix the internal issues we'll be able to merge this diff.

**Comment by gottbrath** [comment]
Just an update here. The way I fixed this created a new diff in our internal system. Which is creating a new PR here. I think the new PR will have the same effect as the old one. I'll post a link to it here when it is available.

**Comment by gottbrath** [comment]
the new PR is https://github.com/pytorch/pytorch/pull/16104

**Comment by ezyang** [comment]
abandoning in favor of @gottbrath's version

**Pull request closed without merging**
