### PR TITLE
Skip broken svd tests

### PR DESCRIPTION
**Pull request by peterbell10**
Workaround for #71645 breaking CI

### CODE REVIEW

**Comment by peterbell10** [comment]
Yeah absolutely fix the underlying issues as well. This is just a quick mitigation to get CI working again.

**Comment by nikitaved** [comment]
Yeah, from the doc it looks like the pointer that stores the data has to be allocated for at least one element. This is, I guess, is not the case from empty tensors and hence the issue. From the documentation on `a`: https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-c/top/lapack-routines/lapack-least-squares-and-eigenvalue-problem/lapack-least-squares-eigenvalue-problem-driver/singular-value-decomposition-lapack-driver/gesdd.html.

**Comment by Lezcano** [comment]
For what is worth, I removed this test in https://github.com/pytorch/pytorch/pull/69827 but this PR will take quite a long time to be merged, so skipping for now is fine.

I deleted the test as it was rather brittle (the errors changed when I ported those kernels to be structured kernels).

**Review by albanD — APPROVED** [review]
Thanks!

**Review by nikitaved — APPROVED** [review]
I retract my words. The issues is different, but it looks like I was able to isolate that. Will investigate and PR a fix.

**Pull request closed without merging**
