### PR TITLE
add get_function to TorchInGraphFunctionVariable

### PR DESCRIPTION
**Pull request by laithsakka**
partially address https://github.com/pytorch/pytorch/issues/118785
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #119435
* __->__ #119314

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Review by anijain2305 — APPROVED** [review]

**Comment by anijain2305** [comment]
There are still some failures.

**Comment by laithsakka** [comment]
more un expected success will remove them tmrw

**Comment by laithsakka** [comment]
more unexpected success !!!

**Comment by laithsakka** [comment]
rebase on master

**Comment by laithsakka** [comment]
after rebase test_binary_cross_entropy_cpu which was fixed by this diff started failing

**Pull request closed without merging**
