### PR TITLE
Recursive KL divergences for Independent-wrapped distributions

### PR DESCRIPTION
**Pull request by JakobHavtorn**
This PR implements the changes proposed in issue https://github.com/pytorch/pytorch/issues/32406.

### CODE REVIEW

**Review by fritzo — COMMENTED** [review]
Thanks for adding these!

Can we add some tests to test_distributions.py? For example you could adapt some of the tests from https://github.com/pyro-ppl/pyro/blob/dev/tests/distributions/test_kl.py

**Comment by fritzo** [comment]
Any idea why tests are failing? Maybe merge master & try again?

**Comment by JakobHavtorn** [comment]
Just merged `master` 🤞

**Comment by JakobHavtorn** [comment]
I don't get the diff in the submodules?

**Comment by fritzo** [comment]
Hmm did you `git submodule update --init --recursive`?

Sometimes as a last resort I `git checkout my-branch`; `git checkout --soft master`; then manually clean up; `git commit`; and `git push -f`.

**Pull request closed without merging**
