### PR TITLE
Move py 3.8->3.9 pull, trunk, inductor, prerioric CI tests

### PR DESCRIPTION
**Pull request by atalman**
Part of Deprecation of python 3.8 and moving to 3.9. Related to: https://github.com/pytorch/pytorch/issues/120718
Except XPU and ROCM jobs

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Review by ZainRizvi — APPROVED** [review]

**Review by XuehaiPan — COMMENTED** [review]
Some changes are missing. Search with regex `(\b|py)3[._]?8\b`.

https://github.com/pytorch/pytorch/blob/cdb9df5efe78142b7a612ae9c938ddf8a8850d10/.github/workflows/xpu.yml#L24-L51

https://github.com/pytorch/pytorch/blob/cdb9df5efe78142b7a612ae9c938ddf8a8850d10/scripts/compile_tests/download_reports.py#L11-L15

**Comment by atalman** [comment]
@XuehaiPan changes to [pytorch/.github/workflows/xpu.yml](https://github.com/pytorch/pytorch/blob/cdb9df5efe78142b7a612ae9c938ddf8a8850d10/.github/workflows/xpu.yml#L24-L51) will be done by intel team.

**Pull request closed without merging**
