### PR TITLE
[inductor] export kernel for gemm template.

### PR DESCRIPTION
**Pull request by xuhancn**
Changes:
1. Move `get_export_declaration` to global scope.
2. Export kernel for gemm template.

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by PaliC** [comment]
@pytorchbot revert -m "sys is not defined in torch/_inductor/codegen/cpp_utils.py" -c "ghfirst"

This pr is breaking a bunch of tests internally, but the reason seems to be due to not having test coverage for a specific file.

**Comment by xuhancn** [comment]
> git pull --rebase

Hi @PaliC , Thanks for your info, I will avoid land the function in cpp_utils.py.

**Pull request closed without merging**
