### PR TITLE
[dynamo][guards] Use lazy variable tracker for func defaults

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #121395
* #121394
* __->__ #121388

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by anijain2305** [comment]
Talked with @osalpekar offline. The internal test failures are unexpected successes due to this fix. We will forward fix.

**Pull request closed without merging**
