### PR TITLE
[ONNX]Add tests for ConvTranspose 1D and 3D

### PR DESCRIPTION
**Pull request by KsenijaS**
Add tests for ConvTranspose 1D and 3D

### CODE REVIEW

**Review by BowenBao — APPROVED** [review]
LGTM

**Comment by KsenijaS** [comment]
@houseroad  build failure is not related to this PR.

**Comment by KsenijaS** [comment]
@houseroad can you please take a look? Thanks

**Comment by KsenijaS** [comment]
@houseroad CI failures are not caused by this PR. Can you please take a look? Thanks

**Comment by KsenijaS** [comment]
@houseroad CI is green, can we merge this? Thanks.

**Comment by KsenijaS** [comment]
@houseroad Can you please take a look?

**Review by houseroad — APPROVED** [review]

**Pull request closed without merging**
