### PR TITLE
[Inductor] apply vec float mask on logical comparison ops in cpp

### PR DESCRIPTION
**Pull request by jgong5**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96502

Fix https://github.com/pytorch/pytorch/issues/96446
The root cause is that the logical comparison op works on the integer vector which is later used in the `where` op that expects a float vector.
1. Make sure float vec mask is applied on logical comparison ops.
2. Fix vec int specialization for `to_float_mask`. Assume int mask as input and returns the float mask with reinterpret cast.
3. Add a no-op specialization for `to_float_mask` function with the float vec as input.
4. Pass value instead of ref to `to_float_mask`. Passing by value should be efficient enough.
5. Remove a conditional check `!=0` in `masked()` since `to_float_mask` is guaranteed to return a float mask.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by jgong5** [comment]
Before
```c++
        for(long i0=0; i0<0; i0+=1)
        {
            auto tmp3 = at::vec::Vectorized<float>(in_ptr0[0]);
            auto tmp5 = at::vec::Vectorized<float>::loadu(in_ptr1 + 16*i0);
            auto tmp0 = at::vec::Vectorized<int>(static_cast<int>(0));
            auto tmp1 = tmp0 == tmp0;
            auto tmp2 = at::vec::Vectorized<float>(static_cast<float>(2.0));
            auto tmp4 = decltype(tmp2)::blendv(tmp3, tmp2, tmp1);
            auto tmp6 = tmp4 * tmp5;
            tmp6.store(out_ptr0 + 16*i0);
        }
```
After
```c++
        for(long i0=0; i0<0; i0+=1)
        {
            auto tmp3 = at::vec::Vectorized<float>(in_ptr0[0]);
            auto tmp5 = at::vec::Vectorized<float>::loadu(in_ptr1 + 16*i0);
            auto tmp0 = at::vec::Vectorized<int>(static_cast<int>(0));
            auto tmp1 = to_float_mask(tmp0 == tmp0);
            auto tmp2 = at::vec::Vectorized<float>(static_cast<float>(2.0));
            auto tmp4 = decltype(tmp2)::blendv(tmp3, tmp2, tmp1);
            auto tmp6 = tmp4 * tmp5;
            tmp6.store(out_ptr0 + 16*i0);
        }
```

**Review by EikanWang — APPROVED** [review]

**Review by XiaobingSuper — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
