### PR TITLE
Turning off static linking of protobuf for setup.py

### PR DESCRIPTION
**Pull request by pjh5**
This is a quick patch until the cmake files and/or setup.py themselves are changed to work together happily

### CODE REVIEW

**Comment by bddppq** [comment]
It should be related to `BUILD_SHARED=OFF`, not setup.py. setup.py just invokes `cmake` through `subprocess.check_call`.

**Comment by Yangqing** [comment]
So we only turn on -fPIC for LINK_LOCAL_PROTOBUF case. We can probably turn it on by default for all custom protobuf build. Here is the code:

https://github.com/pytorch/pytorch/blob/master/cmake/ProtoBuf.cmake#L28-L42

**Comment by bddppq** [comment]
@Yangqing thanks for the pointers, PR created here https://github.com/pytorch/pytorch/pull/6264

**Comment by pjh5** [comment]
Closing cause it's better to have #6264 instead

**Pull request closed without merging**
