### PR TITLE
Remove _broadcast_object() for broadcast_object_list()

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#60574 Remove _broadcast_object() for broadcast_object_list()**
* #60573 Use torch.save()/load() to specify device

Addresses #60062.

**Overview:**
`broadcast_object_list()` relies on `_object_to_tensor()` and `_tensor_to_object()` for transforming each object to a tensor to be communicated. Currently, those two functions use `Pickler.dump()` and `Unpickler.load()`, whose semantics appear to match those of `torch.save()` and `torch.load()`. However, `torch.load()` provides an additional argument `map_location`, which allows the user to specify where to load tensors contained in the loaded object.

The issue with the existing implementation is evidenced when using NCCL backend and broadcasting tensors on GPU. The root cause lies in the default behavior of `torch.load()` (and `Unpickler.load()`) -- **tensors are loaded to device where they were saved**. Suppose we have two processes each with a designated GPU: rank 0 with `cuda:0` and rank 1 with `cuda:1`. If rank 0 broadcasts an object with a tensor to rank 1, when rank 1 loads the tensor via `_tensor_to_object()`, it loads the tensor back to `cuda:0`. This results in a problematic slowdown in hardware organizations where the data transfer from rank 1 to `cuda:0` is much slower than from rank 1 to `cuda:1`. Moreover, regardless of performance effects, I posit that the semantics are non-intuitive -- I would expect the received tensor is on the receiver's GPU, not the sender's.

The change introduced in the first commit of this PR is simply a starting point and can definitely be amended as seen fit. The [test for `broadcast_object_list()`](https://github.com/pytorch/pytorch/blob/da030c59e78dd343c03780a98cd3c2a4d2e3da9c/torch/testing/_internal/distributed/distributed_test.py#L5684) expects the existing behavior of loading tensors to the sender's device. Hence, to preserve backward compatibility, I introduced a `device=None` argument to `broadcast_object_list()`, which can be used to specify the destination for loaded tensors. I do not believe that any of the other collective communication functions using `_tensor_to_object()` (e.g. `all_gather_object()`, `scatter_object_list()`, etc.) are affected since they [do not support GPU](https://pytorch.org/docs/stable/distributed.html). 

The second commit in the PR retires `_broadcast_object()` in ZeRO in favor for `broadcast_object_list()`. 

**Test Plan:**
See [the ci-all tests](https://github.com/pytorch/pytorch/pull/60580).

The ZeRO tests pass (checked on the AI AWS cluster):
```
srun -p $DEV_QUEUE --cpus-per-task=16 -t 5:00:00 --gpus-per-node=4 python test/distributed/optim/test_zero_redundancy_optimizer.py
```

### CODE REVIEW

**Review by rohan-varma — COMMENTED** [review]
I see that this is a draft, but could we also run some sort of benchmark to verify performance parity?

**Comment by andwgu** [comment]
> I see that this is a draft, but could we also run some sort of benchmark to verify performance parity?

For sure. Do you have any suggestions for the benchmark? Also, should the benchmarking be done for all collective communication functions using `_object_to_tensor()` and `_tensor_to_object()` to see how migrating from using the `Pickler`/`Unpickler` to `torch.save()`/`torch.load()` affects performance, or should we focus only on the specific NCCL backend `broadcast_object_list()` case?

**Comment by rohan-varma** [comment]
@andwgu I was thinking we just need to benchmark zero and not necessarily the broadcast_object API itself. Does that sound reasonable?

**Comment by andwgu** [comment]
I performed an experiment with `n = 4` processes. Each process has a copy of a network with `k`-many `2000 -> 2000` fully-connected layers, where `k` ranges over `[1, 2, 5, 10, 20]`, and uses `ZeroRedundancyOptimizer` wrapping `Adam`. Each process runs a single forward pass, backward pass, and optimizer step to generate optimizer state and calls `consolidate_state_dict()`, which involves `n - 1 = 3` `broadcast_object_list()` calls on the local optimizer state. 

The size of the local optimizer state was not always uniform across the processes (due to divisibility of `k` by `4`), meaning the three `broadcast_object_list()` calls per process varied slightly in latency. However, because the differences in the individual latencies mirrored those in overall consolidate latencies, I decided to present only the latter for brevity; we see that specifying the correct `map_location` in `broadcast_object_list()` shows performance improvement:
mean_consolidate_latency

Interestingly, we see a fixed cost (i.e. the increased latency does not scale with the size of the data transferred). I am not sure why that is. Still, the difference appears to be `> 5` seconds pretty consistently.

_Aside:_ I saved the individual `broadcast_object_list()` latencies constituting the `consolidate_state_dict()` latencies, the number of parameters per model, and the `local_state_dict` sizes (in bytes), in case anyone wants that information. I can also run other experiments if desired.

**Comment by andwgu** [comment]
Updated version of the PR: https://github.com/pytorch/pytorch/pull/61539

**Pull request closed without merging**
