### PR TITLE
Rename TorchScript compiler to IR emitter to better reflect its function.

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#33127 Rename TorchScript compiler to IR emitter to better reflect its function.**

Differential Revision: [D19806503](https://our.internmc.facebook.com/intern/diff/D19806503)

### CODE REVIEW

**Review by suo — APPROVED** [review]
sure, seems reasonable, lol. Can we call it `ir_emitter.cpp/h` though? 

You may also want to publicize this change in various chats/groups as it may cause confusion if someone doesn't know about this change.

**Comment by eellison** [comment]
question: does this get rid of git history for `ir_emitter` ?

**Comment by suo** [comment]
> question: does this get rid of git history for `ir_emitter` ?

the history should be preserved, it's tracked as a move. Even merges should theoretically work but who knows

**Comment by ZolotukhinM** [comment]
> question: does this get rid of git history for `ir_emitter` ?

`git log --follow torch/csrc/jit/script/iremitter.cpp` will show this commit and the commits touching `compiler.cpp` before

**Pull request closed without merging**
