### PR TITLE
[MPS] Add `test/test_nn.py` to test suite

### PR DESCRIPTION
**Pull request by hvaara**
This PR increases test coverage by including the tests in `test/test_nn.py` in the test suite of MPS.

Some of the tests are decorated with `@expectedFailureMPS` for various reasons. Either that the op is not implemented, or that the outputs do not align. Those tests that contain differing results should be investigated further to rule out any live bugs.

```bash
$ python test/run_test.py --mps --verbose -k TestNN
Running test batch 'tests to run' cost 84.76 seconds
```

Ref #133520

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

### CODE REVIEW

**Comment by hvaara** [comment]
This will likely fail, but I'll try anyways so maybe I can get some feedback for macOS 13 and 15.

@pytorchbot label "ciflow/mps"

**Comment by skotapati** [comment]
@hvaara thanks for opening this pr. I went ahead and launched your CI run so we can see what happens, but just fyi that I may open a separate pr to add test_nn and a few others to the mps flow

**Comment by hvaara** [comment]
Thanks @skotapati!

>  but just fyi that I may open a separate pr to add test_nn and a few others to the mps flow

I don't understand. Do you mean you want me to split this up, or did you mean you're already working on something similar? Do you have a PR?

Attempting to add MPS ciflow again.

@pytorchbot label "ciflow/mps"

**Comment by hvaara** [comment]
Tests pass on macOS 14 and 15.

Detected failure on macOS 13:`TestNNDeviceTypeMPS.test_conv_empty_input_mps_bfloat16` due to `TypeError: MPS BFloat16 is only supported on MacOS 14 or newer`. Skipping this test on macOS 13.

@pytorchbot label keep-going

**Comment by hvaara** [comment]
I think that was the last of it in MPS - adding trunk.

@pytorchbot label ciflow/trunk

**Comment by hvaara** [comment]
I think the test runner died before starting the build step, but I see no way of restarting the tests. Will force push

image

**Comment by hvaara** [comment]
Had to force-push again. There's been several incidents with Actions lately, but the tests are running again now.

[](https://www.githubstatus.com/history)

**Review by albanD — APPROVED** [review]
SGTM
How do you plan to track these disables to work on fixing them?

**Comment by hvaara** [comment]
> How do you plan to track these disables to work on fixing them?

I was going to go through these one-by-one and annotate the xfails and skips in `test_nn.py` with comments.

For the missing ops I would state the op that's not implemented and link to https://github.com/pytorch/pytorch/issues/77764, and for anything that looks like a bug I would open a separate issue to investigate, preferably with minimal repro steps and link that bug in `test_nn.py`.

Does that SGTY, @albanD? Did you have something specific in mind? Happy to amend my approach if you think there's a better way.

**Comment by hvaara** [comment]
I've created 3 new bugs that has different output on MPS and CPU. Most of the remaining exceptions were linked to existing bugs. Considering that new correctness bugs were discovered from including unit tests that already existed, I would say this is low effort - high impact work (the best kind of work). We should include more of the already existing tests in the MPS test suite.

I have annotated the exceptions in `test/test_nn.py`. Some entries still needs more investigation as correct behavior is still unclear to me. I'll leave this as future work as there are higher priority work items that needs attention. Including more tests for example. @skotapati seemed interested in getting involved with this effort in #134356 - perhaps I can hand off to him. My 2¢ is that broadening test coverage to include more ops and edge cases will lead to discovery of more bugs.

The tests for this PR are green and I'm ready to merge. Unsure if I need formal approval from @malfet or @kulinseth as code owners for MPS. If it LGTY feel free to tell the bot to merge.

**Comment by albanD** [comment]
The attribution looks great! Thanks!

**Comment by albanD** [comment]
Let's wait for a day to see if @kulinseth or @malfet have any comment and if there is nothing we can merge.

**Review by malfet — APPROVED** [review]
Thank you for the fixes. Considering that test_nn.py can be finished quickly, let's land as is, though in the long run we probably don't need to add those to MPS shard, as they'll be picked up by `trunk`

**Comment by malfet** [comment]
@pytorch merge

**Comment by malfet** [comment]
@hvaara you need to fix lint before this change can go in (and I can't do it for you, as you do not accept changes from contributors on your fork of PyTorch)

**Comment by hvaara** [comment]
Thanks for looking, @malfet. Fixed it and ran `make lint` locally this time to verify resolution.

The following option is enabled

image

am I missing something?

**Comment by malfet** [comment]
> > though in the long run we probably don't need to add those to MPS shard, as they'll be picked up by trunk
> 
> How will they be picked up by `trunk`? Is this something that's planned for the future?

test_nn.py is running as part of trunk workflow, and it should cover MPS as well after your change, see https://github.com/pytorch/pytorch/actions/runs/10568390813/job/29279246604

**Comment by hvaara** [comment]
> > > though in the long run we probably don't need to add those to MPS shard, as they'll be picked up by trunk
> > 
> > 
> > How will they be picked up by `trunk`? Is this something that's planned for the future?
> 
> test_nn.py is running as part of trunk workflow, and it should cover MPS as well after your change, see https://github.com/pytorch/pytorch/actions/runs/10568390813/job/29279246604

Do you mean it's sufficient to set `allow_mps=True` in https://github.com/hvaara/pytorch/blob/c521e3c4df81ea587055cf27f4aae00f3ef269a8/test/test_nn.py#L12997 and not include `test_nn` in https://github.com/hvaara/pytorch/blob/c521e3c4df81ea587055cf27f4aae00f3ef269a8/test/run_test.py#L1425 ?

**Comment by hvaara** [comment]
```bash
git show 1565940114aa271749e6395948ae81ff259868b4 | grep -e '^+.*issues/' | sed -e 's#.*issues/##' | sort -h | uniq
```

xref:

- #77764
- #125098
- #134423
- #134430
- #134431

**Pull request closed without merging**
