### PR TITLE
Enables previously "slow" `gradgrad` checks on CUDA

### LINKED ISSUE #57508: Unskip CUDA grad/gradgrad checks or no longer mark as slow test
Currently many CUDA grad/gradgrad checks are skipped or marked as slow tests because they take too long to run. Since we now have a faster gradcheck (faster because it no longer evaluates the entire Jacobian matrix column by column or row by row), we should revisit and reevaluate whether they can be reenabled/unmarked as slow.

For operators that use OpInfo-based testing, check `torch/testing/_internal/common_methods_invocations.py`

There are also tests specified in module_tests, new_module_tests, criterion_tests (i.e., `torch/testing/_internal/common_nn.py`) that specify `check_gradgrad=False`

cc @mruberry

### PR DESCRIPTION
**Pull request by krshrimali**
Fixes #57508

Earlier, a few CUDA `gradgrad` checks (see the list of ops below) were disabled because of them being too slow. There have been improvements (see #57508 for reference) and this PR aimed on:

1. Time taken by `gradgrad` checks on CUDA for the ops listed below.
2. Enabling the tests again if the times sound reasonable

Ops considered: `addbmm, baddbmm, bmm, cholesky, symeig, inverse, linalg.cholesky, linalg.cholesky_ex, linalg.eigh, linalg.qr, lu, qr, solve, triangular_solve, linalg.pinv, svd, linalg.svd, pinverse, linalg.householder_product, linalg.solve`.

For numbers (on time taken) on a separate CI run: https://github.com/pytorch/pytorch/pull/57802#issuecomment-836169691.

cc: @mruberry @albanD @pmeier

### CODE REVIEW

**Comment by krshrimali** [comment]
Closing this, just realized to run all CI jobs, I need to create branch on upstream with `ci-all/` prefix. (https://github.com/pytorch/pytorch/pull/57895)

**Comment by mruberry** [comment]
@krshrimali Why do you want to run all the CI jobs?

**Comment by krshrimali** [comment]
**Update:** Results from profiling only CUDA  `gradgrad` checks which were earlier disabled. The list of such ops:

```
addbmm, baddbmm, bmm, cholesky, symeig, inverse, linalg.cholesky, linalg.cholesky_ex, linalg.eigh, linalg.qr, lu, qr, solve, triangular_solve, linalg.pinv, svd, linalg.svd, pinverse
```

Below is the table with profiling results: (time is in second)

| Function Name  | Time Taken (`complex128`) | Time Taken (`float64`) |
| :--- | :---: | :---: |
| `addbmm` | 1.416 | 0.379 |
| `baddbmm`  | 1.354 | 0.369 |
| `bmm` | 0.167 | 0.132 |
| `cholesky` | 0.449 | 0.227 |
| `symeig` | 0.790 | 0.391 |
| `inverse` | 0.335 | 0.185 |
| `linalg.cholesky` | 0.511 | 0.250 |
| `linalg.cholesky_ex` | 0.576 | 0.280 |
| `linalg.eigh` |  0.522 | 0.271 |
| `linalg.qr` | 2.086 | 0.767 |
| `lu` | 1.546 | 0.665 |
| `qr` | 2.077 | 0.786 |
| `solve` | 5.226 | 2.127 |
| `triangular_solve` | 1.056 | 0.462 |
| `linalg.pinv` | 1.167 | 0.336 |
| `svd` | 3.619 | 1.004 |
| `linalg.svd` | 3.667 | 1.018 |
| `pinverse` | 1.297 | 0.336 |

There are 2 ops which were missed: `linalg.householder_product, linalg.solve`. Waiting for the CI to finish running tests, will add to the table then.

cc: @mruberry

**Comment by mruberry** [comment]
Thanks for the updated numbers @krshrimali; I think these times are acceptable, cc @albanD and @soulitzer in case they find them egregious

This is going to conflict with a PR in @albanD's forward-mode AD stack. @albanD, do you want to remove the skip additions for slow grad/gradgrad in that PR, too? If so, I think this PR can remove the current slow skips.

**Comment by krshrimali** [comment]
Hi, @mruberry, @albanD - gentle ping. Should we disable the gradgrad checks for all the ops tested in this PR? Or has this been taken in a separate PR already? Thanks!

**Comment by krshrimali** [comment]
> > Hi, @mruberry, @albanD - gentle ping. Should we disable the gradgrad checks for all the ops tested in this PR? Or has this been taken in a separate PR already? Thanks!
> 
> Thanks for the ping, @krshrimali! Let me add this to our review on Friday so we can let @albanD review, too. We should have an answer for you then.

Gentle ping @mruberry! Has this been taken up separately?

**Comment by albanD** [comment]
Hey!
We did discuss it last week but did not update here sorry.
There were two things:
- All these tests are fast enough that we can re-enable them indeed.
- It would be nice to get a rule for when a test in slow in this context, for example anything >5 or 10s and then time all the tests and apply that rule.
- We could automatically enforce that rule by failing if a user adds a test that is larger than the given threshold without marking it as slow.

**Comment by mruberry** [comment]
Just wanted to ping on this. The action here (following @albanD's write-up) is to:

- merge this PR with master
- remove the [DO NOT MERGE] text
- let's merge this!

Sound good, @krshrimali? Thanks for helping us with this analysis. Separately, I owe @albanD a more general issue for how we handle slow tests.

**Comment by krshrimali** [comment]
> Just wanted to ping on this. The action here (following @albanD's write-up) is to:
> 
> * merge this PR with master
> * remove the [DO NOT MERGE] text
> * let's land this!
> 
> Sound good, @krshrimali? Thanks for helping us with this analysis. Separately, I owe @albanD a more general issue for how we handle slow tests.

Thanks, @albanD for the write-up.  @mruberry - Thank you for the ping, just confirming, we want to remove all the tests from `slowTest` for now, right? In the scope of this PR, I'm guessing that we don't want to add any rule to test (if it's slow, as mentioned by Alban) when a test is added, right? We can probably take this up in another PR.

Let me know if this sounds good, and I'll make the changes!

**Comment by mruberry** [comment]
> > Just wanted to ping on this. The action here (following @albanD's write-up) is to:
> > 
> > * merge this PR with master
> > * remove the [DO NOT MERGE] text
> > * let's land this!
> > 
> > Sound good, @krshrimali? Thanks for helping us with this analysis. Separately, I owe @albanD a more general issue for how we handle slow tests.
> 
> Thanks, @albanD for the write-up. @mruberry - Thank you for the ping, just confirming, we want to remove all the tests from `slowTest` for now, right? 

All the tests that this PR timed, yes.

> In the scope of this PR, I'm guessing that we don't want to add any rule to test (if it's slow, as mentioned by Alban) when a test is added, right? We can probably take this up in another PR.

Correct; that's a separate issue that requires additional design.

> Please let me know if this sounds good, and I'll make the changes!

Sounds great! Let me know if you have any questions

**Comment by krshrimali** [comment]
> > > Just wanted to ping on this. The action here (following @albanD's write-up) is to:
> > > 
> > > * merge this PR with master
> > > * remove the [DO NOT MERGE] text
> > > * let's land this!
> > > 
> > > Sound good, @krshrimali? Thanks for helping us with this analysis. Separately, I owe @albanD a more general issue for how we handle slow tests.
> > 
> > 
> > Thanks, @albanD for the write-up. @mruberry - Thank you for the ping, just confirming, we want to remove all the tests from `slowTest` for now, right?
> 
> All the tests that this PR timed, yes.
> 
> > In the scope of this PR, I'm guessing that we don't want to add any rule to test (if it's slow, as mentioned by Alban) when a test is added, right? We can probably take this up in another PR.
> 
> Correct; that's a separate issue that requires additional design.
> 
> > Please let me know if this sounds good, and I'll make the changes!
> 
> Sounds great! Let me know if you have any questions

Thanks, @mruberry! On it. :)

**Review by mruberry — APPROVED** [review]
Nice investigation, @krshrimali, and cool that these skips are now gone.

cc @soulitzer

**Pull request closed without merging**
