### PR TITLE
[ONNX] Remove torch.onnx._export

### PR DESCRIPTION
**Pull request by justinchuby**
- Remove the deprecated torch.onnx._export function
- Remove test/onnx/test_export_modes.py because export modes are no longer supported

### CODE REVIEW

**Review by titaiwangms — APPROVED** [review]
Not sure why this breaks test_export_api.py on CI

**Comment by ezyang** [comment]
Remove the tests I guess?

**Comment by justinchuby** [comment]
> Remove the tests I guess?

Done. @titaiwangms I removed all large model tests.

**Comment by justinchuby** [comment]
@kit1980 @malfet could you help import this PR? I remember last time there were still some Meta internal dependencies. If there is any usage of `torch.onnx._export`, simply replace with `torch.onnx.utils._export`. Thanks!

**Comment by malfet** [comment]
@justinchuby I can't import closed PR, but will know tomorrow if there are some of those still remaining

**Comment by kit1980** [comment]
@justinchuby  There are usages.
I tried to replace `torch.onnx._export` with `torch.onnx.export`, but it didn't work because the functions behave differently:
https://github.com/pytorch/pytorch/pull/109763#issuecomment-1736374223

Should replacing with `torch.onnx.utils._export` be automatic? What's the benefit of doing this, replacing "private" API with another "private" API?

If we want to do it, I can use TorchFix to update the usages.

**Comment by justinchuby** [comment]
> I tried to replace torch.onnx._export with torch.onnx.export, but it didn't work because the functions behave differently

Yes. _export exposed some more options, and I suspect initially internal usages wanted more control. But ultimately those options are no longer relevant to users.

> Should replacing with torch.onnx.utils._export be automatic? What's the benefit of doing this, replacing "private" API with another "private" API?

That's just a suggestion for Meta internal usage to continue to function w/o too much effort. If possible I still suggest using torch.onnx.export if you can find a way.

By removing the name from torch.onnx, general users will no longer be able to use it. But this is just cleaning up the name space since it's private anyways.

Since _export has more options, it is unclear to me whether all usages of `_export` can be fixed to use `torch.onnx.export` automatically. I personally think the value is not very high.

**Comment by kit1980** [comment]
I think there is a lot of `torch.onnx._export` usages both inside and outside of Meta. All these usages will be broken unless updated. Should maybe `torch.onnx.utils._export` be removed instead if you want to reduce the API surface?

It's up to the ONNX Exporter team in the end, but it's hard for me to see the value of removing an API with a shorter name and replacing with another private API with a longer name, breaking all the users in the process.

**Comment by justinchuby** [comment]
The torch.onnx._export api was marked deprecated pre 2.0 and was documented to be removed by 2.0. We didn't do it because of Meta internal tests blocked it but now I think it is a good time to give it another try.

Ultimately, replacing with `torch.onnx.utils._export` is a suggestion to unblock Meta internal tests, but not a recommendation for any new code. For external users, they should anticipate the removal and move to use the public api.

**Comment by kit1980** [comment]
I understand it was marked deprecated for a long time - but that's the reality of API usage in PyTorch: people widely use non-public and deprecated APIs because PyTorch is so widespread. I can replace internal usages with `torch.onnx.utils._export`, but other users will be broken. Naive GitHub code search on `torch.onnx._export` shows there are 1.8k files.

**Comment by justinchuby** [comment]
@kit1980 That's a good point. Looking at the github search many (if not most) of the usage can be replaced with `torch.onnx.export`. Would you mind creating a rule in TorchFix to use `torch.onnx.export`, maybe as an "unsafe fix" if that's a possibility?

**Comment by kit1980** [comment]
I guess we can check if the result of `torch.onnx._export` is used by the caller. If yes, replace with `torch.onnx.utils._export`. Otherwise replace with `torch.onnx.export`. Should that work in most cases?

**Comment by justinchuby** [comment]
I think so, thanks!

**Pull request closed without merging**
