### PR TITLE
Fix display of test failure number in test_distributions.

### PR DESCRIPTION
**Pull request by gchanan**
Previously, if e.g. the last example of 3 failed, it would say example 2/3.

### CODE REVIEW

**Comment by gchanan** [comment]
@fritzo I ran into this when running test_distributions with scalars enabled.

**Comment by fritzo** [comment]
That pattern is used all over the file. If you feel like tidying up, you could change all occurrences in the file.

**Comment by gchanan** [comment]
ok, I fixed the other instances in the file.

**Comment by yf225** [comment]
For Windows CI, test_ distributions passed and test_cuda failure is unrelated, should be good to merge.

**Pull request merged**
