### PR TITLE
[inductor] Fallback for index with None in the middle of indices

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #90022

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
what does None mean in the context of index ?

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
