### PR TITLE
add dispatch for bitwise_and

### PR DESCRIPTION
**Pull request by MarisaKirisame**

### CODE REVIEW

**Comment by ezyang** [comment]
pro-tip: don't tag people in commit messages, GitHub is very spammy when this happens

**Review by ezyang — APPROVED** [review]

**Comment by MarisaKirisame** [comment]
sorry, i will request a review instead next time.

**Comment by ailzhang** [comment]
Sorry had to ninja revert this PR to unblock XLA on master, I will prepare a XLA PR soon. (my environment for building TF is somehow messed up so need to fix it :P

**Comment by ezyang** [comment]
no worries, this was my bad for landing this originally

**Comment by MarisaKirisame** [comment]
Do I have to resubmit a PR, or is everything good?

**Comment by ailzhang** [comment]
@MarisaKirisame would you mind resubmitting a PR and cc me on it? Thanks a lot!

**Pull request closed without merging**
