### PR TITLE
Simple THCApply optimization

### PR DESCRIPTION
**Pull request by csarofeen**
Just allowing THCApply to use larger grids which shows a performance improvement.

### CODE REVIEW

**Comment by apaszke** [comment]
Do you have any benchmark numbers?

**Comment by csarofeen** [comment]
Kernel type | Tensor Size |   p100 speedup | maxwell speedup
THCApply1 | (1024, 1024,  8) | 1.01 | 1.07
THCApply1 | (1024, 1024, 16) | 1.02 | 1.11
THCApply1 | (1024, 1024, 32) | 1.04 | 1.15
THCApply1 | (1024, 1024, 64) | 1.09 | 1.21
THCApply1 | (1024, 1024, 128) | 1.14 | 1.26
THCApply1 | (1024, 1024, 256) | 1.19 | 1.31
THCApply1 | (1024, 1024, 512) | 1.22 | 1.34
THCApply2 | (1024, 1024,  8) | 1.00 | 1.08
THCApply2 | (1024, 1024, 16) | 1.02 | 1.12
THCApply2 | (1024, 1024, 32) | 1.05 | 1.17
THCApply2 | (1024, 1024, 64) | 1.10 | 1.21
THCApply2 | (1024, 1024, 128) | 1.15 | 1.26
THCApply2 | (1024, 1024, 256) | 1.19 | 1.30
THCApply2 | (1024, 1024, 512) | 1.22 | 1.34
THCApply3 | (1024, 1024,   8) | 0.99 | 1.06
THCApply3 | (1024, 1024, 16) | 1.01 | 1.09
THCApply3 | (1024, 1024, 32) | 1.02 | 1.13
THCApply3 | (1024, 1024, 64) | 1.07 | 1.16
THCApply3 | (1024, 1024, 128) | 1.10 | 1.19
THCApply3 | (1024, 1024, 256) | 1.13 | 1.24
THCApply3 | (1024, 1024, 512) | 1.17 | 1.25

**Comment by apaszke** [comment]
Any ideas why do we get these speedups? Is it because the previous code didn't manage to fill up the SMs in 100%? Wouldn't it be better to still restrict the grid, but allow larger sizes on newer archs?

**Comment by soumith** [comment]
this is merged into master. thanks Christian!

**Pull request closed without merging**
