### PR TITLE
[1/N] fix clang-tidy warnings in torch/csrc

### PR DESCRIPTION
**Pull request by cyyever**
Apply fixes to some found issues by clang-tidy in torch/csrc.

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @Skylion007

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]
This looks good to me, just fix the merge conflicts.

**Comment by cyyever** [comment]
cc @Skylion007 some unrelated test failures，need your help to merge

**Comment by osalpekar** [comment]
This causes breakages of the following form (we should include `-Wimplicit-int` when building PT in builds run on PR):
```
torch/csrc/dynamo/eval_frame.c:801:8: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Werror,-Wimplicit-int]
[2023-08-25T20:48:14.180-07:00]   auto nfrees = PyCode_GetNFreevars(code);
[2023-08-25T20:48:14.180-07:00]   ~~~~ ^
[2023-08-25T20:48:14.180-07:00]   int
```

**Pull request closed without merging**
