### PR TITLE
Make data_ptr a method on Tensor

### PR DESCRIPTION
**Pull request by li-roy**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#20878 Make data_ptr a method on Tensor**

Make this a method on Tensor rather than a native function. We don't have to support void* in c10 dispatcher, and we can stop blacklisting this in jit registry.

Differential Revision: [D15482061](https://our.internmc.facebook.com/intern/diff/D15482061)

### CODE REVIEW

**Comment by ezyang** [comment]
Don't we have a `data_ptr()` method on the Python side? What's happening here?

**Comment by li-roy** [comment]
We do, I'm just binding it manually like `dim()` and other methods on Tensor.

**Comment by dzhulgakov** [comment]
Just curious - what's the reason of not making it a native_function instead?

**Review by zdevito — APPROVED** [review]

**Comment by li-roy** [comment]
A couple reasons: it's method that's not a function, doesn't have backend specific dispatch, there's no reason it can't be a method directly on tensor like size() or data(). Another reason is it's the only native_function that uses void*, so moving it means we don't have to blacklist it in gen_jit_dispatch nor support it in c10 dispatcher.

**Comment by ezyang** [comment]
Failures are legit.

```
❌ ci/circleci: caffe2_py2_system_macos10_13_build                        https://circleci.com/gh/pytorch/pytorch/1827721:
May 29 00:50:04 In file included from /Users/distiller/project/aten/src/TH/THTensorApply.h:4:
May 29 00:50:04 In file included from /Users/distiller/project/aten/src/ATen/Parallel.h:2:
May 29 00:50:04 In file included from /Users/distiller/project/aten/src/ATen/ATen.h:5:
May 29 00:50:04 In file included from /Users/distiller/project/aten/src/ATen/Context.h:4:
May 29 00:50:04 In file included from /Users/distiller/project/aten/src/ATen/Tensor.h:2:
May 29 00:50:04 /Users/distiller/project/aten/src/ATen/core/Tensor.h:257:41: error: no member named 'slow_data' in 'c10::TensorImpl'
May 29 00:50:04     return this->unsafeGetTensorImpl()->slow_data();
May 29 00:50:04            ~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
May 29 00:50:05 1 error generated.
May 29 00:50:05 make[2]: *** [caffe2/CMakeFiles/caffe2.dir/__/aten/src/ATen/DLConvertor.cpp.o] Error 1
May 29 00:50:05 make[2]: *** Waiting for unfinished jobs....
May 29 00:50:05 1 error generated.
May 29 00:50:05 make[2]: *** [caffe2/CMakeFiles/caffe2.dir/__/aten/src/ATen/CPUGenerator.cpp.o] Error 1
May 29 00:50:05 1 error generated.
May 29 00:50:05 make[2]: *** [caffe2/CMakeFiles/caffe2.dir/__/aten/src/ATen/CPUTypeDefault.cpp.o] Error 1
May 29 00:50:06 1 error generated.
May 29 00:50:06 make[2]: *** [caffe2/CMakeFiles/caffe2.dir/__/aten/src/ATen/Context.cpp.o] Error 1
May 29 00:50:06 make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
```

**Pull request closed without merging**
