### PR TITLE
[Docs] Updated torchvision people

### PR DESCRIPTION
**Pull request by vfdev-5**
cc @datumbox @pmeier

### CODE REVIEW

**Review by datumbox — COMMENTED** [review]
I spoke with @b0noI offline who kindly explained the new process of updating the file. There are changes since the move to the Linux Foundation move, so we will be using PyTorch Core's proposed [process](https://github.com/pytorch/pytorch/blob/master/docs/source/community/build_ci_governance.rst).

Following the above doc, I'm voting in favour of adding both @vfdev-5 and @pmeier as they have been outstanding contributors for many years with TorchVision.

@fmassa you are the first maintainer in this file, so we need your input. Thanks!

**Comment by pmeier** [comment]
What about @NicolasHug? Going by the [GH statistics](https://github.com/pytorch/vision/graphs/contributors), the five of us are by far the most frequent contributors.

**Comment by datumbox** [comment]
@pmeier Good points. I'm trying to figure out how this works because these are new processes. :)

@b0noI Would you be able to provide some guidance over if we can update the list to add all the qualified maintainers? Is there a specific definition what we should have in mind? We don't have a specific process on TorchVision so we are probably going to follow the one you created recently for Core. Thanks!

**Comment by NicolasHug** [comment]
I'd like to be added as torchvision maintainer in this file (thanks @pmeier). I had opened https://github.com/pytorch/pytorch/pull/85623 for that already.

> There are changes since the move to the Linux Foundation move, so we will be using PyTorch Core's proposed [process](https://github.com/pytorch/pytorch/blob/master/docs/source/community/build_ci_governance.rst).

The move to the linux foundation i) doesn't concern torchvision and ii) only concerns business governance, not technical governance (which is what this is about). Also the link above seems related to the build / CI team only. The actual process seems to be defined here: https://github.com/pytorch/pytorch/blob/master/docs/source/community/governance.rst#nominating-confirming-and-removing-maintainers.

**Comment by datumbox** [comment]
> I had opened https://github.com/pytorch/pytorch/pull/85623 for that already.

I stamped to unblock.

> The actual process seems to be defined here:

I think that Nicolas' reference is more relevant that the other one quoted by Slava. Reading the principles described on the new reference, IMO all proposed people still meet the criteria.

**Comment by NicolasHug** [comment]
Thanks @datumbox 

From what I understand regarding nomination:

>Each module has its own process. Please contact module maintainers for more information. However, if there is no process identified, you can file a request to the core maintainers by submitting [this form](https://forms.gle/xNeu1byGMZVHcA2q7). Core maintainers are meeting every three months.

it looks like it's up to you and @fmassa to define what the current process is (I'll ping him internally)

**Review by fmassa — APPROVED** [review]
I approve adding Philip, Victor and Nicolas to the persons of interest of torchvision

**Comment by datumbox** [comment]
> it looks like it's up to you and @fmassa to define what the current process is (I'll ping him internally)

Let's unblock the addition of key team members and perhaps we can discuss the processes once everyone is in. I don't even know how I ended up in this list in the first place. 😄

**Review by datumbox — APPROVED** [review]

**Comment by datumbox** [comment]
I'm putting my official ceremonial robe on to nominate, @NicolasHug, @YosuaMichael and @jdsgomes. They are active maintainers of TorchVision with numerous contributions each. The nomination aligns with the principles described at the [governance doc](https://github.com/pytorch/pytorch/blob/master/docs/source/community/governance.rst#nominating-confirming-and-removing-maintainers). 

@fmassa any concerns?

**Review by fmassa — APPROVED** [review]
LGTM to add Yosua and Joao as well!

**Pull request closed without merging**
