### PR TITLE
[pt2] add metas for `adaptive_max_pool` ops

### LINKED ISSUE #103892: `torch.compile`: Error `Cannot call sizes() on tensor with symbolic sizes/strides` with dynamic shapes and `F.adaptive_max_pool1d`
### 🐛 Describe the bug

I am getting a `Cannot call sizes() on tensor with symbolic sizes/strides` when attempting to `torch.compile` code than uses `F.adaptive_max_pool1d`.

Code to reproduce:
```python
import torch
import torch.nn.functional as F

def func(x):
    return F.adaptive_max_pool1d(x, 1)

opt_func = torch.compile(func, dynamic=True)

x = torch.randn((1, 4), device='cuda')
opt_func(x)

x = torch.randn((1, 5), device='cuda')
opt_func(x)
```

Produces the following error:
```
Traceback (most recent call last):
  File "/home/phigon/brever/temp.py", line 10, in <module>
    opt_func(x)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 295, in _fn
    return fn(*args, **kwargs)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 448, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 527, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 430, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 415, in transform
    tracer.run()
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2025, in run
    super().run()
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 708, in run
    and self.step()
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 668, in step
    getattr(self, inst.opname)(inst)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 390, in wrapper
    return inner_fn(self, inst)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1100, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 559, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/variables/torch.py", line 610, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1063, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1099, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1298, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1266, in get_fake_value
    return wrap_fake_exception(
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 860, in wrap_fake_exception
    return fn()
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1267, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1332, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1319, in run_node
    return node.target(*args, **kwargs)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_jit_internal.py", line 488, in fn
    return if_false(*args, **kwargs)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/nn/functional.py", line 1100, in _adaptive_max_pool1d
    return adaptive_max_pool1d_with_indices(input, output_size)[0]
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/nn/functional.py", line 1092, in adaptive_max_pool1d_with_indices
    return torch.adaptive_max_pool1d(input, output_size)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1161, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1405, in dispatch
    r = func(*args, **kwargs)
  File "/home/phigon/.conda/envs/brever/lib/python3.10/site-packages/torch/_ops.py", line 401, in __call__
    return self._op(*args, **kwargs or {})
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <function boolean_dispatch.<locals>.fn at 0x7f6ab46f6e60>(*(FakeTensor(..., device='cuda:0', size=(1, s0)), 1), **{}):
Cannot call sizes() on tensor with symbolic sizes/strides

from user code:
   File "/home/phigon/brever/temp.py", line 5, in func
    return F.adaptive_max_pool1d(x, 1)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

PyTorch version: 2.1.0.dev20230620+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: AlmaLinux 9.2 (Turquoise Kodkod) (x86_64)
GCC version: (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4)
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.34

Python version: 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.14.0-284.11.1.el9_2.x86_64-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX TITAN X
GPU 1: NVIDIA GeForce GTX TITAN X
GPU 2: NVIDIA GeForce GTX TITAN X
GPU 3: NVIDIA GeForce GTX TITAN X
GPU 4: NVIDIA GeForce GTX TITAN X
GPU 5: NVIDIA GeForce GTX TITAN X
GPU 6: NVIDIA GeForce GTX TITAN X
GPU 7: NVIDIA GeForce GTX TITAN X

Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       2
Stepping:                        1
CPU max MHz:                     3000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        4199.60
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d
Virtualization:                  VT-x
L1d cache:                       512 KiB (16 instances)
L1i cache:                       512 KiB (16 instances)
L2 cache:                        4 MiB (16 instances)
L3 cache:                        40 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-7,16-23
NUMA node1 CPU(s):               8-15,24-31
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+440fd1bf20
[pip3] torch==2.1.0.dev20230620+cu118
[pip3] torch-ema==0.3
[pip3] torchaudio==2.1.0.dev20230620+cu118
[pip3] torchvision==0.16.0.dev20230620+cu118
[pip3] triton==2.0.0
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] pytorch-triton            2.1.0+440fd1bf20          pypi_0    pypi
[conda] torch                     2.1.0.dev20230620+cu118          pypi_0    pypi
[conda] torch-ema                 0.3                      pypi_0    pypi
[conda] torchaudio                2.1.0.dev20230620+cu118          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230620+cu118          pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

### PR DESCRIPTION
**Pull request by nkaretnikov**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #104388
* #104236
* __->__ #104167

Fixes #103892.

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78

### CODE REVIEW

**Comment by nkaretnikov** [comment]
Note: this PR allows for running the repro from #103892.

However, this PR doesn't unlock many tests. In core, these ops are defined as structured kernels. Structured kernel codegen does not support non-tensor symbolic arguments, like a `SymIntArrayRef`. So we cannot change arrays to symbolic arrays in the yaml files, which is why the tests still fail. This is a known issue with structured kernels, which we've been ignoring so far.

**Comment by georgehorrell** [comment]
Hey - I was also looking at this issue. Based on a comment on #103892, I wondered whether it'd be sufficient to do something like this in `AdaptiveMaxPooling2d.cpp`:

```
namespace at {
namespace meta {
TORCH_META_FUNC(adaptive_max_pool2d) (const Tensor& input, IntArrayRef output_size) {
  auto input_sym_sizes = input.sym_sizes();
  int ndim = input_sym_sizes.size();
  ...
  int dimH = 1;
  c10::SymInt sizeB = 1;
  c10::SymInt sizeD = 0;

  if (ndim == 4) {
    sizeB = input.sym_size(0);
    dimH++;
  }

  sizeD = input.sym_size(dimH - 1);

  int64_t osizeH = output_size[0];
  int64_t osizeW = output_size[1];

  /* resize output */
  if (ndim == 3) {
    set_output_raw_strided(0, {sizeD.expect_int(), osizeH, osizeW}, {}, input.options());
    ...
  }
}
```

I'd find it really instructive if could you explain (briefly) why we needed the modifications here! Thanks in advance 😄

**Comment by nkaretnikov** [comment]
@georgehorrell Python meta functions are now preferred over CPP ones. Some of the reasons why:
- It's easier to port it to a decomposition/reference later, which can aid compiler optimizations.
- Due to duck-typing, you can write the same code for regular shapes as well as symbolic shapes.
- Some find it more productive to work in Python over CPP.

**Comment by georgehorrell** [comment]
> @georgehorrell Python meta functions are now preferred over CPP ones. Some of the reasons why:
> 
> * It's easier to port it to a decomposition/reference later, which can aid compiler optimizations.
> * Due to duck-typing, you can write the same code for regular shapes as well as symbolic shapes.
> * Some find it more productive to work in Python over CPP.

Thank you! Where would I find documentation on changes to design patterns like this?

**Comment by nkaretnikov** [comment]
@georgehorrell See "How to write a Python meta function" here: https://docs.google.com/document/d/1GgvOe7C8_NVOMLOCwDaYV1mXXyHMXY7ExoewHqooxrs/edit#

**Review by ezyang — APPROVED** [review]

**Comment by nkaretnikov** [comment]
Updated the csv according to:

```
vision_maskrcnn                     IMPROVED: graph_breaks=51, expected=56
```

**Pull request closed without merging**
