### PR TITLE
inductor: remove conv_bn folding from pre_grad pass

### PR DESCRIPTION
**Pull request by XiaobingSuper**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #106686

The freezing pass has support conv+bn folding pass, we don't need to do that at pre_grad pass.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by eellison — APPROVED** [review]

**Comment by kit1980** [comment]
@XiaobingSuper Sorry I have to revert, please re-submit when https://github.com/pytorch/pytorch/pull/106576 is re-submitted.

**Pull request closed without merging**
