### PR TITLE
MIOpen fixes for Caffe2

### PR DESCRIPTION
**Pull request by ashishfarmer**
The PR contains:
Fixes for running MIOpen conv operator in a multi worker scenario, along with a performance fix
Fixing a typo in MIOpen pool op and adding some extra checks for MIOpen spatial BN op

@bddppq

### CODE REVIEW

**Comment by petrex** [comment]
@bddppq 
is it ok we disable the test [health check](https://hypothesis.readthedocs.io/en/latest/healthchecks.html) from hypothesis?

**Comment by bddppq** [comment]
@petrex yes I would like to disable this filter too much health check globally but I don't know how to do it. Maybe just disable this offending one for now caffe2/python/operator_test/fc_operator_test.py::TestFcOperator::test_fc

**Comment by bddppq** [comment]
https://github.com/pytorch/pytorch/pull/9865

**Review by bddppq — APPROVED** [review]
LG

**Pull request closed without merging**
