### PR TITLE
Sets CUDA_MODULE_LOADING to LAZY when not set by the user

### PR DESCRIPTION
**Pull request by syed-ahmed**
This PR sets CUDA_MODULE_LOADING if it's not set by the user. By default, it sets it to "LAZY".

It was tested using the following commands:
```
python -c "import torch; tensor=torch.randn(20, 16, 50, 100).cuda(); free, total = torch.cuda.cudart().cudaMemGetInfo(0); print(total-free)"
```
which shows a memory usage of: 287,047,680 bytes

vs

```
CUDA_MODULE_LOADING="DEFAULT" python -c "import torch; tensor=torch.randn(20, 16, 50, 100).cuda(); free, total = torch.cuda.cudart().cudaMemGetInfo(0); print(total-free)"
```
which shows 666,632,192 bytes. 

C++ implementation is needed for the libtorch users (otherwise it could have been a pure python functionality).

cc: @ptrblck @ngimel @malfet

### CODE REVIEW

**Comment by syed-ahmed** [comment]
Some notes:
I discovered that syncing os.eviron with C runtime environment variable related methods (getenv, putenv/setenv) is a tricky thing. The CUDA_MODULE_LOADING environment variable set in the CUDAHooks using setenv works but for it to be visible on the python side, we need to set it in os.environ.

**Comment by ptrblck** [comment]
> The CUDA_MODULE_LOADING environment variable set in the CUDAHooks using setenv works but for it to be visible on the python side, we need to set it in os.environ.

Does this mean that `python -m torch.utils.collect_env` won't be able to report it in its current implementation? 
Would it work if we replace `config = os.environ.get('CUDA_MODULE_LOADING', '')` with setting/reading an internal flag in addition to `setenv("CUDA_MODULE_LOADING", def_value.c_str(), 1);`?

**Comment by syed-ahmed** [comment]
> Does this mean that python -m torch.utils.collect_env won't be able to report it in its current implementation?
> Would it work if we replace config = os.environ.get('CUDA_MODULE_LOADING', '') with setting/reading an internal flag in addition to setenv("CUDA_MODULE_LOADING", def_value.c_str(), 1);?

No, `python -m torch.utils.collect_env` works in this implementation. My comment was just an observation on how setenv can add/update an environment variable in a process and os.environ would not show it (since os.environ is just a copy of the environment before the process started). 

To elaborate a bit more, I started with the changes in the CUDAHooks.cpp. Those changes set the environment variable if the user hasn't set it. I then naively added the environment variable in collect_env.py to print it, but that didn't show the value of the variable, even though I could verify (using the snippet above) that the environment variable was being set. So then I realized that os.environ doesn't get updated when setenv is called from the cpp side. So the solution I came up with for this PR is to set the variable in os.environ in torch/cuda/__init__.py before the __cuda_init() call. The if-else in the changes in CUDAHooks.cpp then becomes redundant when using the python front-end, however, it's still needed if you are using standalone aten (I also manually verified the setting of the variable on the cpp side by not setting the variable in os.environ).

There are other solutions people suggest that use getenv with ctypes to get the environment variable that was set from the cpp side (e.g. https://stackoverflow.com/questions/235435/environment-variables-in-python-on-linux). I tried that in collect_env.py but that didn't work (in linux) and I saw an empty value for the variable even though it was set. So just ended up with simply updating the os.environ and thought usage of ctypes like this is an overkill for this PR (given you'll also have to handle other OS's).

**Comment by syed-ahmed** [comment]
@ptrblck Ah, I think I misunderstood your question. Yes, in its current implementation, collect_env.py won't be able to show if the variable was set or not and your suggestion of using an internal variable in addition to the setenv would work. Would that be the preferred approach? My approach in this PR is to just simply add it in the os.environ before cuda lazy init, but may be I'm missing some downsides of it?

I also ran this on a distributed example and each process gets the environment variable when I just set the variable in os.environ in cuda_init: https://gist.github.com/syed-ahmed/10c07824c63a5a20c69208f18cce6c61

**Comment by ngimel** [comment]
lgtm, I'll let @malfet to also take a look.

**Comment by syed-ahmed** [comment]
@malfet Processed the EasyCLA. Please review at your convenience. We were thinking this PR might be good to be included in the 1.13.

**Comment by malfet** [comment]
Can you please target master and then create a cherry-pick into r1.13
Also, please mention in PR description, that C++ implementation is needed for the libtorch users (otherwise it could have been a pure python functionality)

**Comment by syed-ahmed** [comment]
@malfet done. I updated the release tracker with the new PR.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
