### PR TITLE
[dynamo][side effects] Raise assertion error if the object is already tracked for mutation

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128590
* #128269
* #128715

This issue was pointed out by @tombousso here - https://github.com/pytorch/pytorch/pull/128269#issuecomment-2163755792

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by mlazos** [comment]
Shouldn't we only hit that side effect path once though if we're caching at the variable builder level? why would it get called again?

**Comment by anijain2305** [comment]
Yeah, I ran CI with an `assert earlier` and that CI passed. Changed my mind to return the cached version. No strong opinion  though, I can make it an assert.

**Comment by anijain2305** [comment]
Updated to using an assert.

**Review by mlazos — APPROVED** [review]
Thanks!

**Pull request closed without merging**
