### PR TITLE
bump nccl to 2.8.3-1

### PR DESCRIPTION
**Pull request by jeffra**
We've recently seen some stability issues with NCCL 2.7.8, our initial testing with 2.8.3 has looked promising. The previous time in November that pytorch was at 2.8 I believe it was pointing to a non-tagged/unstable version of 2.8. The NCCL repo now seems to have a tag for 2.8.3 so should (hopefully) be possible to upgrade.

### CODE REVIEW

**Comment by awan-10** [comment]
Hi @mingzhe09088. This is the PR from our team.

**Comment by mingzhe09088** [comment]
@jeffra Could you please sign the CLA so I can import this PR and start FB internal testing?

**Comment by jeffra** [comment]
> @jeffra Could you please sign the CLA so I can import this PR and start FB internal testing?

Thanks for checking into this so quickly! Sorry for my delay, I filed the appropriate legal request on my side, once it comes back I'll be sure to sign it.

**Review by mrshenli — COMMENTED** [review]
Is this test error relevant?

```
Jan 08 01:36:47 ======================================================================
Jan 08 01:36:47 ERROR [3.425s]: test_batch_isend_irecv_nccl (__main__.TestDistBackendWithSpawn)
Jan 08 01:36:47 ----------------------------------------------------------------------
Jan 08 01:36:47 Traceback (most recent call last):
Jan 08 01:36:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 280, in wrapper
Jan 08 01:36:47     self._join_processes(fn)
Jan 08 01:36:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 397, in _join_processes
Jan 08 01:36:47     self._check_return_codes(elapsed_time)
Jan 08 01:36:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 433, in _check_return_codes
Jan 08 01:36:47     raise RuntimeError(error)
Jan 08 01:36:47 RuntimeError: Processes 0 1 exited with error code 10
```

**Comment by jeffra** [comment]
> @jeffra Could you please sign the CLA so I can import this PR and start FB internal testing?

I've signed CLA now.

**Comment by Flamefire** [comment]
FWIW: I also see the test_batch_isend_irecv_nccl error with NCCL 2.8.3

More log:
```
  File "/tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 285, in wrapper
    fn()
  File "/tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 644, in test_batch_isend_irecv_nccl
    reqs = dist.batch_isend_irecv(p2p_op_list)
  File "/tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 946, in batch_isend_irecv
    reqs.append(ret)
  File "/scratch/ws/1/s3248973-EasyBuild/easybuild-rome/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/tmp/easybuild-tmp/eb-cDNnSX/tmpcKnJLr/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 896, in _batch_p2p_manager
    ProcessGroupNCCL._group_end()
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:1593, internal error, NCCL version 2.8.3
ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption
exiting process with exit code: 10
```

**Pull request closed without merging**
