### PR TITLE
Move generator state APIs to ATen

### PR DESCRIPTION
**Pull request by lqf96**
## Rationale

While most of the `torch.Generator` properties and methods are implemented as a thin wrapper of the corresponding `at::Generator` methods, `torch.Generator.get_state()` and `torch.Generator.set_state()` are implemented in legacy Torch code and are not dispatched through the `c10::GeneratorImpl` interface. This is not structured well and makes implementing generators for new backends (e.g. `XLAGeneratorImpl` for the XLA backend) inconvenient. As such, this pull request seeks to move these generator state APIs to c10 and ATen.

## What is being refactored?
* Interfaces
  - Added `c10::GeneratorImpl::set_state` and `c10::GeneratorImpl::state` for getting and setting the internal state of a random number generator.
  - `at::Generator::set_state` and `at::Generator::state` wraps the above-mentioned APIs, as it's basically a PIMPL.
  - Added helper function `at::detail::check_rng_state` for checking the validity of new RNG state tensor.
* CPU Generator
  - Renamed and moved `THTensor_(setRNGState)` and `THTensor_(getRNGState)` to `CPUGeneratorImpl::set_state` and `CPUGenerator::state`.
  - Renamed and moved `THGeneratorState` and `THGeneratorStateNew` to `CPUGeneratorStateLegacy` and `CPUGeneratorState`.
* CUDA Generator
  - Renamed and moved `THCRandom_setRNGState` and `THCRandom_getRNGState` to `CUDAGeneratorImpl::set_state` and `CUDAGeneratorImpl::state`.
* PyTorch Bindings
  - `THPGenerator_setState` and `THPGenerator_getState` now simply forward to `at::Generator::set_state` and `at::Generator::state`.

### CODE REVIEW

**Comment by lqf96** [comment]
I guess this is ready for review now. Since I'm not familiar with the C++ side of the project, maybe @ezyang or someone can take a look at this?

**Comment by ezyang** [comment]
@pbelevich let me know if you need extra eyeballs on this PR

**Comment by pbelevich** [comment]
> @pbelevich let me know if you need extra eyeballs on this PR

Will review it and other prs today, sorry for late review

**Comment by lqf96** [comment]
@pbelevich I revisited the PR today and figured out although the implementation is correct, there's still a few places where the code quality can be improved:

1. Should we name the new APIs as `state` / `set_state` or `rng_state` / `set_rng_state`? The latter sounds clearer and matches the legacy APIs names (`THTensor_(get|set)RNGState` / `THCRandom_(get|set)RNGState`) better.
2. `c10::GeneratorImpl` should accept `const c10::TensorImpl&` instead of `c10::TensorImpl&`. Similarly, `at::Generator` should accept `const Tensor&`.

What's your opinions on these? Since the PR is already imported to FB's internal systems, should I update this PR or open a new one?

**Review by pbelevich — CHANGES_REQUESTED** [review]
@lqf96 thanks a lot for this work!


> 1. Should we name the new APIs as `state` / `set_state` or `rng_state` / `set_rng_state`? The latter sounds clearer and matches the legacy APIs names (`THTensor_(get|set)RNGState` / `THCRandom_(get|set)RNGState`) better.

I think we should try to match [Python API names](https://github.com/pytorch/pytorch/blob/2b221a95997b00dcc166918f752b2ad8e921eb15/torch/csrc/Generator.cpp#L187-L188) instead of legacy names to make C++ API and Python API look similar. So, let's rename `state` to `set_state` and keep `get_state` as is.



> 2\. `c10::GeneratorImpl::state` (or `rng_state`) should accept `const c10::TensorImpl&` instead of `c10::TensorImpl&`. Similarly, `at::Generator::state`  (or `rng_state`) should accept `const Tensor&`.

Agree, let's make them `const`

> Since the PR is already imported to FB's internal systems, should I update this PR or open a new one?

Amend this PR, it's easy to reimport it again to FB internal code

**Comment by pbelevich** [comment]
TODO(for pbelevich): amend this PR with https://github.com/pytorch/csprng/pull/106 after reimport to fbcode

**Comment by lqf96** [comment]
@pbelevich I applied your suggestions and this PR should be ready for review again.

**Review by pbelevich — APPROVED** [review]

**Pull request closed without merging**
