### PR TITLE
[pytorch][kineto] log process group config in distributed info

### PR DESCRIPTION
**Pull request by shengbao-zheng**
Summary: Process Group config is essential to analyze collective pattern. We have added this in Execution Trace. Now expose this information in Kineto as well

Test Plan: Tested in HPC

Differential Revision: D52882292

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### CODE REVIEW

**Review by wconstab — APPROVED** [review]
Looks fine for starters, not sure if the config part is complete but it depends what your purposes are. You could compare with the c++ log statement in ProcessGroupNCCl.cpp for additional knobs and envs we log

**Review by aaronenyeshi — APPROVED** [review]
LGTM, my main concern is whether pg_config will always have valid values that are JSON compatible. A few things that may break our JSON include new lines, non-quoted strings, or symbols. Thanks!

**Pull request closed without merging**
