### PR TITLE
[docs][jit] Mention dynamic-shapes settings in jit/OVERVIEW.md

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #113964

Document torch._C._jit_set_fusion_strategy, which can control how many static-shape compilation attempts are made before falling back to dynamic shapes, before falling back to uncompiled graph execution.

Would be good to keep all the graph executor settings documented in one place.

### CODE REVIEW

**Comment by davidberard98** [comment]
Screenshot 2023-11-17 at 10 32 46 AM

**Review by eellison — APPROVED** [review]
nice!!

**Pull request closed without merging**
