### PR TITLE
[JIT] call super().setUp() in test_jit_fuser_te.py

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #73762

TestCase.setUp() controls @slowTest behavior, so calling super().setUp() will prevent fast tests from running in the slow test CI jobs.

example: https://github.com/pytorch/pytorch/runs/5413135014?check_suite_focus=true: despite PYTORCH_TEST_SKIP_FAST=1, TestTEFuserStatic tests are still running

Differential Revision: [D34628769](https://our.internmc.facebook.com/intern/diff/D34628769)

### CODE REVIEW

**Review by ZolotukhinM — APPROVED** [review]
LGTM!

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34628769).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34628769).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34628769).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34628769).

**Comment by davidberard98** [comment]
@ZolotukhinM turns out there were a few failures due to self.setHooks() and self.clearHooks() (which are called in JitTestCase.setUp()) - can you take a quick look to make sure the changes to make the tests pass are fine?

**Pull request closed without merging**
