### PR TITLE
[WIP] fix calls to `super().__getattr__` nn.Module in dynamo

### PR DESCRIPTION
**Pull request by vmoens**
Currently, custom getattr in nn.Module subclass such as
```python
def __getattr__(self, name):
    try:
        super().__getattr__(name)
    except AttributeError:
        bla
```
will fail because `__getattr__` is [ignored altogether](https://github.com/pytorch/pytorch/blob/ed734178abc99bc1d83ad2c61d3a1e4d4f5d20c8/torch/_dynamo/utils.py#L1939-L1941)

The part of getattr that breaks is retreiving the `__dict__` from `self`, but this seems to be already retrieved in var_getattr. This PR just checks if the name is `__dict__` and behaves accordingly.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by vmoens** [comment]
Interestingly, this test works but not if we use the fallback of `__getattr__`
(see the works / fails annotations)

```python
import torch
from torch.nn import functional as F
from torch import nn

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.cst = nn.Parameter(torch.zeros(()))
        self.linear = torch.nn.Linear(10, 10)

    def __getattr__(self, name):
        try:
            return super().__getattr__(name)
        except AttributeError:
            try:
                return getattr(self.__dict__["_modules"]["linear"], name)
            except KeyError:
                raise AttributeError

    def forward(self, input):
        return F.linear(input, self.linear.weight, self.linear.bias) + self.cst # Works 
        # return F.linear(input, self.weight, self.bias) + self.cst  # Fails

module = MyModule()
x = torch.randn(10)
module(x)
module_c = torch.compile(module, fullgraph=True)
module_c(x)
```

dynamo [enters the proposed `__getattr__`](https://github.com/pytorch/pytorch/blob/d4ec18bdad7cf94fa12da7ebbfabfec53655829f/torch/_dynamo/variables/nn_module.py#L243-L250) then calls `super` and ends up in the AttributeError (which is expected) but stops there.

@jansel is there a way for dynamo to capture that the AttributeError in `super().__getattr__` is actually within a try/except and can be ignored?

**Comment by jansel** [comment]
Exception handlers currently cause graph breaks, though @anijain2305 has been talking about adding support.   I don't think it would be that hard in a case like this.

**Comment by anijain2305** [comment]
I started looking into exception support today. Its going to take some time.

@vmoens Is there any particular model you are interested? I can try to see if there is an easy way to support your usecase.

**Comment by anijain2305** [comment]
Will be fixed by the stack of PRs here - https://github.com/pytorch/pytorch/pull/126956

**Review by lezcano — COMMENTED** [review]
Sounds reasonable. Can you add a test?

**Comment by lezcano** [comment]
nvm, I see @anijain2305 already addressed this. Closing.

**Pull request closed without merging**
