### PR TITLE
Make diag_embed a primitive w.r.t. autograd

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #71766
* #71765
* #71751
* __->__ #71750

functorch has problems vmap-ing over diag_embed due to the in-place copy_.
This PR adds a backward formula for it so that it becomes a primitive
w.r.t. autograd.

Test Plan:
- tested with functorch

Differential Revision: [D33772753](https://our.internmc.facebook.com/intern/diff/D33772753)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
From offline discussion. This is an ok one time fix.
We should figure out how to do without this in the future though for functorch

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33772753).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33772753).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33772753).

**Pull request closed without merging**
