### PR TITLE
remove redundant trailing semicolons in StorageImpl.h

### PR DESCRIPTION
**Pull request by dagitses**
remove redundant trailing semicolons in StorageImpl.h

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by malfet** [comment]
@mikey do you mind changing your email to personal one for this PR?

**Comment by dagitses** [comment]
> @mikey do you mind changing your email to personal one for this PR?

@malfet I can't push to pytorch. But I have updated a branch in my fork. Are you able to change the head ref to the corresponding branch in my fork? https://github.com/dagitses/pytorch/tree/pr97658

**Review by malfet — APPROVED** [review]

**Comment by mikey** [comment]
> @mikey do you mind changing your email to personal one for this PR?

Wrong git user @malfet ? @mikey is me and I'm not involved in this PR.

**Comment by malfet** [comment]
> Wrong git user @malfet ? @mikey is me and I'm not involved in this PR.

Sorry about the confusion. GitHub sometimes converts first name to the user name, but sometimes fails to do so.

**Pull request closed without merging**
