### PR TITLE
chore(quantization): Enable PT2E symmetric dynamic quantization

### PR DESCRIPTION
**Pull request by pkluska**
in `_find_choose_qparams_node` function compare
the current node if it is affine or symmetric

### CODE REVIEW

**Comment by colesbury** [comment]
@kimishpatel, would you please review this PR?

**Review by kimishpatel — APPROVED** [review]

**Review by kimishpatel — APPROVED** [review]

**Comment by pkluska** [comment]
Hi, @colesbury @kimishpatel are we okay to merge that PR?

**Comment by kimishpatel** [comment]
can you rebase? I am trying to see if I can trigger ci

**Comment by pkluska** [comment]
> can you rebase? I am trying to see if I can trigger ci

Rebased :)

**Comment by kimishpatel** [comment]
@malfet can you merge this one? Not sure what i am doing wrong

**Comment by malfet** [comment]
@kimishpatel enabled the workflow, let's see if it's green

**Comment by pkluska** [comment]
hey @malfet, I have update the commit to fix the linting issue. sorry about that.

**Comment by malfet** [comment]
@pkluska please let me know whether or not your PR is ready for review, as you keep pushing new changes to it.

**Comment by pkluska** [comment]
> @pkluska please let me know whether or not your PR is ready for review, as you keep pushing new changes to it.

@malfet I rebased it, as since yesterday there were additional pushes to main branch. It seems that not related checks were failing. Otherwise, it is ready

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
