### PR TITLE
Add support for dotted names in CPP Extensions

### PR DESCRIPTION
**Pull request by fmassa**
When trying to compile a CPP extension inside a namespace (for example, `torchvision._C`), pybind11 complained because the `.` breaks its macro expansion in `PYBIND11_MODULE `.

This PR tries to fix it, by only sending to pybind the name of the library that should be compiled, and not the full path.

cc. @goldsborough

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by goldsborough** [comment]
I'm always a bit wary about silently doing things like this for users because it becomes more confusing when they don't expect it. Like here, someone might have a `A._C` and `B._C` extension and expect them to differ, but will probably end up with something very weird (e.g. the second library overwriting the first). Disallowing dots in the name and raising an error might be better? 

Also, just to understand, were you trying to name the extension something like `torchvision._C`? It probably doesn't matter for the JIT extensions because the module is loaded from an absolute path, but if you tried to actually import the module with `import` it would fail because there wouldn't actually be such a directory structure `torchvision/_C.py` right?

**Review by goldsborough — CHANGES_REQUESTED** [review]
Just while discussing

**Comment by fmassa** [comment]
Actually, setuptools send the `_C` library to the right folder. So in your example, there would be no clash (except if the temporaries are first written to the same destination then copied, not sure what actually happens).
But this pattern of having `module.ext` is quite common in setuptools.Extension.

And `torchvision._C` worked fine in my case. Without this patch, I had to create the extension in the global namespace like `_torchvision__C`, which is not great.

**Comment by goldsborough** [comment]
Ok then it's cool.
It would be nice to test this in our tests. Maybe rename one of the test extensions to such a dotted name so that CI and unit tests verify it?

**Review by goldsborough — APPROVED** [review]

**Comment by fmassa** [comment]
@goldsborough I've updated the tests to add a namespace into account.
Here is some documentation that mentions that having dots for packages is something very common when using Python Extensions https://docs.python.org/3/distutils/setupscript.html#extension-names-and-packages

**Comment by ezyang** [comment]
ASAN failure is spurious but Windows is real.

```
19:12:53 
19:12:53                                !! WARNING !!
19:12:53 
19:12:53 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
19:12:53 Your compiler (cl) may be ABI-incompatible with PyTorch!
19:12:53 Please use a compiler that is ABI-compatible with GCC 4.9 and above.
19:12:53 See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.
19:12:53 
19:12:53 See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
19:12:53 for instructions on how to install GCC 4.9 or higher.
19:12:53 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
19:12:53 
19:12:53                               !! WARNING !!
19:12:53 
19:12:53   warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
19:12:53 test_cpp_extensions (unittest.loader._FailedTest) ... ERROR
19:12:53 
19:12:53 ======================================================================
19:12:53 ERROR: test_cpp_extensions (unittest.loader._FailedTest)
19:12:53 ----------------------------------------------------------------------
19:12:53 ImportError: Failed to import test module: test_cpp_extensions
19:12:53 Traceback (most recent call last):
19:12:53   File "C:\Jenkins\Miniconda3\lib\unittest\loader.py", line 153, in loadTestsFromName
19:12:53     module = __import__(module_name)
19:12:53   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test\test\test_cpp_extensions.py", line 6, in <module>
19:12:53     import torch_test_cpp_extension.cpp as cpp_extension
19:12:53 ModuleNotFoundError: No module named 'torch_test_cpp_extension'
```

**Comment by fmassa** [comment]
@ezyang looks like those tests were not being skipped in the previous builds.
This issue I believe is just a matter of fixing the tests so that Windows is happy with it (as was the case for the py2 fixes).
I currently have no idea where to look at (I was thinking that maybe it was a problem in [here](https://github.com/pytorch/pytorch/blob/master/test/run_test.py#L97-L108)?), and I don't have a Windows machine to try it out.

A few options:
- revert the tests to what they were before (and given that tests pass in all other architectures, that might reassure Peter that it's possible to have extensions in nested namespaces)
- skip this test for Windows (bad)
- try to debug with the help of @peterjc123
- drop this patch (nooooo!!!)

**Comment by goldsborough** [comment]
@peterjc123 could you have a look?

**Comment by peterjc123** [comment]
@fmassa I've found out the problem. It is the extension dir search process in `run_test.py` L107.
Can you do you a favor?
```python
# Change this
install_directory = os.path.dirname(install_directory) 
# into
import re
install_regex = re.compile(r'\w+_packages')
while install_regex.match(os.path.basename(install_directory)):
    install_directory = os.path.dirname(install_directory)

**Comment by peterjc123** [comment]
@yf225 Oh no. The Windows CI is stuck in the build process.

**Comment by fmassa** [comment]
@yf225 looks like there is still a problem with the Windows CI.

**Comment by yf225** [comment]
@fmassa the previous machine wasn’t shut down completely. I manually terminate it again and it should work now.

**Pull request merged**
