### PR TITLE
Unbreak vectorization

### PR DESCRIPTION
**Pull request by mikekgfb**
Summary: Unbreak vectorization

Test Plan: sandcastle

Differential Revision: D51818065

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Would be nice to include a test plan (at least internally)

**Review by seemethere — APPROVED** [review]

**Comment by atalman** [comment]
@mikekgfb Do we need it in Release 2.2.0 ? This is internal change only

**Comment by mikekgfb** [comment]
> @mikekgfb Do we need it in Release 2.2.0 ? This is internal change only

We don't need it for 2.2.0 because it only affects Meta-internal use cases and fbcode has a different release management.

**Pull request closed without merging**
