### PR TITLE
use --no-binary for pip install of onnx

### PR DESCRIPTION
**Pull request by jeffdaily**
onnx package requires a newer setuptools than the current docker build image provides.  Newer docker images are not yet available.  Work around the issue by upgrading setuptools prior to building caffe2.

This should restore ROCm CI caffe2 builds.

CC @ezyang @xw285cornell

### CODE REVIEW

**Comment by xw285cornell** [comment]
Still failing?

**Comment by jeffdaily** [comment]
Misread the error message, so attempted the wrong fix.  Looks like the caffe2 build on ROCm CI was trying to use Python2?
```
20:39:24   /tmp/pip-build-env-w6z_itcp/overlay/lib/python3.6/site-packages/pkg_resources/py2_warn.py:15: UserWarning: Setuptools no longer works on Python 2
20:39:24   ************************************************************
20:39:24   Encountered a version of Setuptools that no longer supports
20:39:24   this version of Python. 
```

**Comment by jeffdaily** [comment]
Next attempt uses the versioned pip via new var $PIP, similar to how $PYTHON is used already.

**Comment by jeffdaily** [comment]
Root cause of issue is unsupported python environment in old ROCm caffe2 images.  Will open new PR with a different solution.

**Pull request closed without merging**
