### PR TITLE
[executorch] Update iOS toolchain with a modern cmake syntax.

### PR DESCRIPTION
**Pull request by shoumikhin**
Summary: Replace exec_program with execute_process

Test Plan: CI

Differential Revision: D52147108

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Comment by huydhn** [comment]
It looks like you need to double check if you use the correct email for CLA here

**Comment by osalpekar** [comment]
@shoumikhin Please make sure OSS CI is complete before landing the diff internally. Otherwise auto-merging the PR fails and we end up with fbcode and GitHub diverging. I will manually merge this for you to solve the issue this time.

**Pull request closed without merging**
