### PR TITLE
[CUBLAS][CUDA GRAPHS] (re-open of #83461) Explicitly set the workspace for cuBLAS handles

### PR DESCRIPTION
**Pull request by eqy**
re-open of #83461 with fix for 10.2 build

CC @ngimel @malfet

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM

**Comment by eqy** [comment]
@malfet could you explain how to add the `ciflow/trunk` label or add it to this PR as the memory leak check failures (on the previous PR) seemed to be real?

**Comment by malfet** [comment]
@eqy you can just add it yourself, or if you don't have triage permissions, ask @pytorchbot for help (there is a label command if I'm not mistaken)

**Pull request closed without merging**
