### PR TITLE
[3.12, 3.13, dynamo] simplified construction for frame f_locals/localsplus

### PR DESCRIPTION
**Pull request by williamwen42**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #130569
* #130568
* #130567
* #130566
* #130565
* #130564
* #130461
* #130460
* #130459
* #130458
* #130385
* #130384
* #130383
* __->__ #129185

Construct frame localsplus in 3.12+ using our own simplified way rather than copypasting from CPython.

This is necessary for 3.13 since we can no longer generate frame `f_locals` before executing the interpreter frame.
We also enable this for 3.12 since the `f_locals` construction between 3.12 and 3.13 is the same, so we can test for correctness with 3.12.

This is also one of the first steps to completing https://github.com/pytorch/pytorch/issues/93753 - we will implement simplified f_locals generation of previous Python versions in the future.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
Test faiures?

**Review by jansel — APPROVED** [review]

**Comment by jansel** [comment]
You should double check the perf of this to ensure it doesn't regress overheads.

**Comment by williamwen42** [comment]
`python benchmarks/dynamo/microbenchmarks/overheads.py `

Pre change:
```
$ python benchmarks/dynamo/microbenchmarks/overheads.py 
requires_grad=False
eager    6.3us (warmup=0.0s)
compiled 11.7us (warmup=7.8s)

requires_grad=True
eager    8.1us (warmup=0.0s)
compiled 35.2us (warmup=0.2s)

inference_mode()
eager    5.9us (warmup=0.0s)
compiled 10.9us (warmup=0.0s)

$ python benchmarks/dynamo/microbenchmarks/overheads.py 
requires_grad=False
eager    6.5us (warmup=0.0s)
compiled 11.8us (warmup=7.7s)

requires_grad=True
eager    7.8us (warmup=0.0s)
compiled 34.4us (warmup=0.3s)

inference_mode()
eager    5.7us (warmup=0.0s)
compiled 11.2us (warmup=0.0s)

$ python benchmarks/dynamo/microbenchmarks/overheads.py 
requires_grad=False
eager    6.5us (warmup=0.0s)
compiled 11.6us (warmup=7.4s)

requires_grad=True
eager    8.1us (warmup=0.0s)
compiled 34.6us (warmup=0.2s)

inference_mode()
eager    5.9us (warmup=0.0s)
compiled 10.8us (warmup=0.0s)
```

Post change:
```
(/data/users/williamwen/py312-env2) [williamwen@devgpu020.odn1 /data/users/williamwen/pytorch2 (32ae3fda)]$ python benchmarks/dynamo/microbenchmarks/overheads.py 
requires_grad=False
eager    6.3us (warmup=0.0s)
compiled 18.4us (warmup=13.0s)

requires_grad=True
eager    14.0us (warmup=0.0s)
compiled 45.5us (warmup=0.2s)

inference_mode()
eager    10.0us (warmup=0.0s)
compiled 16.9us (warmup=0.0s)

$ python benchmarks/dynamo/microbenchmarks/overheads.py 
requires_grad=False
eager    6.4us (warmup=0.0s)
compiled 11.7us (warmup=8.2s)

requires_grad=True
eager    8.0us (warmup=0.0s)
compiled 33.9us (warmup=0.2s)

inference_mode()
eager    5.8us (warmup=0.0s)
compiled 11.0us (warmup=0.0s)

$ python benchmarks/dynamo/microbenchmarks/overheads.py 
requires_grad=False
eager    6.4us (warmup=0.0s)
compiled 11.5us (warmup=7.4s)

requires_grad=True
eager    8.3us (warmup=0.0s)
compiled 34.8us (warmup=0.2s)

inference_mode()
eager    5.9us (warmup=0.0s)
compiled 10.8us (warmup=0.0s)
```

Looks like this diff doesn't regress overhead perf.

**Comment by clee2000** [comment]
@pytorchbot revert -m "dr ci categorization is wrong, the test_linalg xsuccess is real, theres also a test_jit failure 
 https://github.com/pytorch/pytorch/actions/runs/9844339391/job/27178009798 https://hud.pytorch.org/pytorch/pytorch/commit/b428f1ad77aedfd150e920c8b0d23b7e6393ad6f" -c weird

**Comment by huydhn** [comment]
@pytorchbot revert -m 'dr ci categorization is wrong, the test_linalg xsuccess is real, theres also a test_jit failure
https://github.com/pytorch/pytorch/actions/runs/9844339391/job/27178009798 https://hud.pytorch.org/pytorch/pytorch/commit/b428f1ad77aedfd150e920c8b0d23b7e6393ad6f' -c weird

I have closed the unstable issue for experimental build, so this shouldn't happen again.

**Pull request closed without merging**
