### PR TITLE
Add missing .to_sparse(ndim) gradient

### LINKED ISSUE #46720: autograd for to_sparse(dim)
## 🚀 Feature
autograd for to_sparse(dim)

## Motivation
This is related to another GitHub [issue](https://github.com/pytorch/pytorch/issues/18111), that issue is fixed by the [commit](https://github.com/pytorch/pytorch/pull/20458). However, it seems it only supports non-parameter version. I want to have autograd for to_sparse(dim). 

To be more concrete, the following (case 1) is supported
```
>>> torch.randn(2, 3).requires_grad_(True).to_sparse()
tensor(indices=tensor([[0, 0, 0, 1, 1, 1],
                       [0, 1, 2, 0, 1, 2]]),
       values=tensor([ 0.3336,  0.7028, -1.0183, -0.3018, -0.6059, -1.0752]),
       size=(2, 3), nnz=6, layout=torch.sparse_coo, grad_fn=<ToSparseBackward>)
```
 the following (case 2) is not supported
```
>>> torch.randn(2, 3).requires_grad_(True).to_sparse(1)
tensor(indices=tensor([[0, 1]]),
       values=tensor([[ 1.1035,  2.0671,  0.5015],
                      [ 0.0975,  0.3090, -1.1393]]),
       size=(2, 3), nnz=2, layout=torch.sparse_coo, grad_fn=<NotImplemented>)
```

Is it possible to support case 2?

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @aocsa @mruberry

### PR DESCRIPTION
**Pull request by kylevedder**
Fixes #46720, extends PR #46825 by adding test requested in [this comment](https://github.com/pytorch/pytorch/pull/46825#issuecomment-842304079).

### CODE REVIEW

**Comment by kylevedder** [comment]
@albanD I added the test that you requested. It seems CIs is failing due to gradcheck infra for this test. All CI failures seem to be for the same reason across the different backends: 

```
torch.autograd.gradcheck.GradcheckError: While computing batched gradients, got: Could not run
'aten::view' with arguments from the 'SparseCUDA' backend. This could be because the operator
doesn't exist for this backend, or was omitted during the selective/custom build process (if using
custom build). If you are a Facebook employee using PyTorch on mobile, please visit
https://fburl.com/ptmfixes for possible resolutions. 'aten::view' is only available for these backends:
[CPU, CUDA, Meta, QuantizedCPU, QuantizedCUDA, MkldnnCPU, BackendSelect, Named,
ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA,
UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor,
AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched,
VmapMode].
```

I think this is the fault of the gradcheck infra because [it invokes `vmap`](https://github.com/pytorch/pytorch/blob/3c5e95d38b827046ed26684f692753aac7d0dd60/torch/autograd/gradcheck.py#L757) (note the exception handling the line below is where the error is printed) which seems to be the operation not supported by any of the `Sparse*` backends. As such I think this is a problem with support for the testing infra itself, rather than incorrect behavior in the change. 

As it stands I am blocked on this PR. What do you suggest that I do in order to move forward?

**Comment by albanD** [comment]
Thanks for the test!
This is ok if it is not supported for now.
@zou3519 what is the best way to disable batched gradient testing for tests defined this way?

**Comment by zou3519** [comment]
Add it to https://github.com/pytorch/pytorch/blob/b45a105acb594cf03e5cc940df7195b0785b8989/test/test_autograd.py#L5420-L5423 and you should be good to go

**Review by albanD — APPROVED** [review]
LGTM Thanks for the update!
Let's wait for CI to see if all is good now.

**Comment by albanD** [comment]
I think you want to add this new tests to more jit blacklist: https://github.com/pytorch/pytorch/blob/1ba05efd26213c3f26e9b0cd6765f988f4da731a/test/test_jit.py#L15526 and https://github.com/pytorch/pytorch/blob/1ba05efd26213c3f26e9b0cd6765f988f4da731a/torch/testing/_internal/jit_metaprogramming_utils.py#L360

**Comment by kylevedder** [comment]
I `grep`d the codebase and don't see any other blacklists, so hopefully this will pass everything.

**Comment by kylevedder** [comment]
It appears that the [failed tests](https://app.circleci.com/pipelines/github/pytorch/pytorch/324489/workflows/e313be53-b4f6-4264-bd1d-a2e853dce472/jobs/13581278) were caused by a non-zero exit code in a child process (code `-11`); I'm not familiar enough with the infra to know what that means, but it doesn't seem like it's caused by a test failure ([`TEST_ERROR_EXIT_CODE` is 10](https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_distributed.py#L377)).

Is it possible this is a transient error and, if so, can the failed test just be re-run?

**Comment by kylevedder** [comment]
Rebased onto head of `viable/strict` to fix upstream error as requested by the bot. Assuming the earlier CI process failure error was transient, that should hopefully be fixed as well.

**Comment by kylevedder** [comment]
Unfortunately, the [test failure](https://app.circleci.com/pipelines/github/pytorch/pytorch/324891/workflows/ff4014c7-8f3f-4d52-a47b-320f9b1eb7a2/jobs/13598119) is not transient. I'm guessing the cause is a component in the distributed gradient testing infra not supporting sparsity but I can't tell because the only feedback I can find is the `-11` exit code. I tried `grep`ing stuff again to see if anything was missed but to my eye anything relevant seemed to be at parity with `test_to_sparse`. I'm unfamiliar with the codebase and the testing infra, so I don't know how to debug futher.

**Comment by albanD** [comment]
These tests do not involve sparse Tensors at all from what I can see so I'm a bit surprised.

**Comment by albanD** [comment]
Actually I see the same distributed tests failures on another PR like https://github.com/pytorch/pytorch/pull/58625 so I'm going to tentatively assume that this is broken master :D

**Pull request closed without merging**
