### PR TITLE
Fix THP_export for python_variable_indexing.cpp

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Review by apaszke — COMMENTED** [review]
Why can’t they be extern? Those shouldn’t be used outside of THP

**Comment by peterjc123** [comment]
@apaszke They generate errors while linking in MSVC. The error is shown below:
```
[00:10:58]      Creating library build\temp.win-amd64-3.6\Release\torch/csrc\_C.cp36-win_amd64.lib and object build\temp.win-amd64-3.6\Release\torch/csrc\_C.cp36-win_amd64.exp
[00:10:58]   python_variable_indexing.obj : error LNK2001: unresolved external symbol "struct _object * THPLongTensorClass" (?THPLongTensorClass@@3PEAU_object@@EA)
[00:10:58]   build\lib.win-amd64-3.6\torch\_C.cp36-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
```
I think that the decorators are needed, espeically for those exported symbols.

**Comment by apaszke** [comment]
My point is that these symbols aren't really exported, meaning that they are not supposed to be used outside of `_C`.

**Comment by peterjc123** [comment]
@apaszke May I know where are these variables first defined?

**Comment by apaszke** [comment]
[Here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/Tensor.cpp#L122)

**Comment by peterjc123** [comment]
@apaszke So maybe I can move the definition into `Tensor.h` and make it included in the `python_variable_indexing.cpp`?

**Comment by apaszke** [comment]
It is defined in the corresponding header, with this `THP_API` prefix. Still, I'm not exactly sure how `extern` works in Windows, because there's either sth wrong with this code, or it is utterly useless, as you can't even declare things `extern` and have them visible in other compilation units

**Comment by peterjc123** [comment]
@apaszke I think I may know the reason for that. The `THPLongTensorClass` is has `THP_API` flag on it, and then it will exist in the static library. But you specify `extern` here, it will look for it in the dynamic library, which will then fail. I can confirm this because I can find it in the export table of the earlier versions.

**Comment by apaszke** [comment]
Uh ok, these are some weird MSVC things. I guess the `__dlspec` actually overrides whatever the standard says

**Comment by apaszke** [comment]
Thanks a lot!

**Pull request merged**
