### PR TITLE
[jit] Enable `copy.deepcopy` and `copy.copy` for RecursiveScriptModule

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #40297 [jit] Remove unnecessary clone APIs for script::Module and RecursiveScriptModule
* **#32685 [jit] Enable `copy.deepcopy` and `copy.copy` for RecursiveScriptModule**

Summary:

Test Plan:
.

Reviewers:
.
Subscribers:

Tasks:

Tags:

Differential Revision: [D21220755](https://our.internmc.facebook.com/intern/diff/D21220755)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit d7973ea7:


* **2/2** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=d7973ea7f96f4f6e722e53ccfa3ca0990010b3f6).

### :detective: 2 new failures recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4356146) pytorch_linux_xenial_py3_6_gcc5_4_ge_config_simple_test (1/2)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=91766119) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=91766119))
<details>
<summary>
<code>Jan 28 04:10:07 RuntimeError: test_jit_simple failed!</code>
</summary>

```
Jan 28 04:10:07 Ran 2365 tests in 89.295s 
Jan 28 04:10:07  
Jan 28 04:10:07 FAILED (errors=4, skipped=79, expected failures=1) 
Jan 28 04:10:07  
Jan 28 04:10:07 Generating XML reports... 
Jan 28 04:10:07 Traceback (most recent call last): 
Jan 28 04:10:07   File "test/run_test.py", line 456, in <module> 
Jan 28 04:10:07     main() 
Jan 28 04:10:07   File "test/run_test.py", line 449, in main 
Jan 28 04:10:07     raise RuntimeError(message) 
Jan 28 04:10:07 RuntimeError: test_jit_simple failed! 
Jan 28 04:10:07 + cleanup 
Jan 28 04:10:07 + retcode=1 
Jan 28 04:10:07 + set +x 
Jan 28 04:10:07 =================== sccache compilation log =================== 
Jan 28 04:10:08 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 28 04:10:08 Compile requests                 2 
Jan 28 04:10:08 Compile requests executed        0 
Jan 28 04:10:08 Cache hits                       0 
Jan 28 04:10:08 Cache misses                     0 
Jan 28 04:10:08 Cache timeouts                   0 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4356151) pytorch_linux_xenial_py3_6_gcc5_4_ge_config_legacy_test (2/2)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=91766149) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=91766149))
<details>
<summary>
<code>Jan 28 04:10:34 RuntimeError: test_jit_legacy failed!</code>
</summary>

```
Jan 28 04:10:34 Ran 2365 tests in 131.932s 
Jan 28 04:10:34  
Jan 28 04:10:34 FAILED (errors=4, skipped=62, expected failures=1) 
Jan 28 04:10:34  
Jan 28 04:10:34 Generating XML reports... 
Jan 28 04:10:34 Traceback (most recent call last): 
Jan 28 04:10:34   File "test/run_test.py", line 456, in <module> 
Jan 28 04:10:34     main() 
Jan 28 04:10:34   File "test/run_test.py", line 449, in main 
Jan 28 04:10:34     raise RuntimeError(message) 
Jan 28 04:10:34 RuntimeError: test_jit_legacy failed! 
Jan 28 04:10:34 + cleanup 
Jan 28 04:10:34 + retcode=1 
Jan 28 04:10:34 + set +x 
Jan 28 04:10:34 =================== sccache compilation log =================== 
Jan 28 04:10:35 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 28 04:10:35 Compile requests               260 
Jan 28 04:10:35 Compile requests executed        0 
Jan 28 04:10:35 Cache hits                       0 
Jan 28 04:10:35 Cache misses                     0 
Jan 28 04:10:35 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by suo — DISMISSED** [review]

**Comment by suo** [comment]
Can you mark this PR as BC-breaking

**Comment by jerryzh168** [comment]
Got this:
```
Jun 19 23:07:12 ERROR [0.004s]: test_model_save_error (test_jit.TestJit) 
Jun 19 23:07:12 ---------------------------------------------------------------------- 
Jun 19 23:07:12 Traceback (most recent call last): 
Jun 19 23:07:12   File "/var/lib/jenkins/workspace/test/test_jit.py", line 355, in test_model_save_error 
Jun 19 23:07:12     torch.save(FooToPickle(), fname) 
Jun 19 23:07:12   File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 364, in save 
Jun 19 23:07:12     _save(obj, opened_file, pickle_module, pickle_protocol) 
Jun 19 23:07:12   File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 468, in _save 
Jun 19 23:07:12     pickler.dump(obj) 
Jun 19 23:07:12 RuntimeError: Tried to serialize object __torch__.torch.jit.ScriptModule which does not have a __getstate__ method defined! 
Jun 19 23:07:12  

```
I think it's because I removed `__getstate__` from `RecursiveScriptModule`, can we remove this test now since we do have `__getstate__` defined in `script::Object` and `script::Module` now? cc @zdevito, @jamesr66a

**Comment by zdevito** [comment]
That test is checking that there is an error with a reasonable error message for saving a module with TorchScript submodules. It looks like this change broke the friendly error message and made it something less understandable.

**Comment by jerryzh168** [comment]
> That test is checking that there is an error with a reasonable error message for saving a module with TorchScript submodules. It looks like this change broke the friendly error message and made it something less understandable.

Fixed.

**Review by zdevito — APPROVED** [review]
Looks good

**Pull request closed without merging**
