### PR TITLE
Move the CUDA implementation of log to ATen.

### LINKED ISSUE #24586: Migrate `log` and `log_` from the TH to Aten (CUDA)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #26769 Move the CUDA implementation of log2 to ATen.
* #26733 Move the CUDA implementation of log10 to ATen.
* **#26494 Move the CUDA implementation of log to ATen.**

Close #24586

Differential Revision: [D17572497](https://our.internmc.facebook.com/intern/diff/D17572497)

### CODE REVIEW

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
@xuhdev please rebase

**Comment by xuhdev** [comment]
Done!

**Comment by xuhdev** [comment]
I rebased again to ensure that test can run properly

**Comment by xuhdev** [comment]
Just rebased again to resolve a conflict

**Pull request closed without merging**
