### PR TITLE
[ROCm] revert sharding dist tests

### PR DESCRIPTION
**Pull request by jeffdaily**
Increase timeout for ROCm workflow and revert dist test sharding for ROCm.

### CODE REVIEW

**Comment by janeyx99** [comment]
How come we don't want to shard these tests?

**Comment by jeffdaily** [comment]
> How come we don't want to shard these tests?

The FSDP tests recently started failing for ROCm only.  For ROCm it is somehow using a gloo function that is not implemented but cuda is not affected.  I suspected it was anothing nit w.r.t. sharding so this PR will test it.

**Comment by janeyx99** [comment]
@jeffdaily ah so it's a test PR. sadly you were caught in some heavy upstream failures :c

**Comment by jeffdaily** [comment]
Closing in favor of #76564.

**Pull request closed without merging**
