### PR TITLE
Proposal for a more general usage of the parameter "example_inputs" in torch.jit.trace()

### PR DESCRIPTION
**Pull request by tangleintel**
# Support python callable object's parameters' unpacking feature in **torch.jit.trace()**

Python support passing a tuple or dictionary to a callable object and automatically unpacking the parameter to make the function get the right value. For tuple, the elements' order will result in the correctness of arguments' matching while dictionary use the arguments' name for matching. 
In **torch.jit.trace()**, we support passing a tuple or a single tensor as our example_inputs to trigger the graph construction. Passing a tuple meanings the tuple elements' order should strictly align with the parameters' order declared in the **forward()** function. But in some scenarios, it's not that easy or just  can't manually make such a tuple to trace a model when we already have off-the-shelf dataset which consists of dictionaries. Take the below 2 examples as illustration case:

1. In the first example, say, if we have a dataset and each of the data is a dictionary such as **data = {'key1':value1, 'key2':value2, 'key3':value3}**, we will fetch the data from dataloader and extract its value and make a tuple as the **example_inputs** passing to jit.trace(). But if the **forward()** method of our module which we want to trace has such declaration:
            `def forward(self, key2=value2, key3=value3, key1=value1):`
Thus, we need manually reorder the value in the tuple and check if they can match to the declaration. This case is just not friendly to users but we can still trace the module by reordering.

2.  In the second example, say, we still have the same dataset, but the **forward()** method's declaration as below:
            `def forward(self, key2=value2, key3=value3, key4=None, key5=None, key1=value1, key6=value6):`
This time, we can't just passing a tuple by simply reordering the value, cause we missing **key4** and **key5** in the dataset, and we can't passing a tuple like **example_inputs = (value2, value3, None, None, value1)** since tracer doesn't support **None** type when the corresponding missing arguments' default value are **None**.  For this situation, it's even not traceable.

These cases are not fabricated deliberately. We met these issue in Hugging Face's text-classification tasks with some datasets(such as GLUE tasks), and we expect it's a common issue.

So, we propose to make **torch.jit.trace()** support python function's kwargs unpacking feature with dictionary to address these issues. If we can support unpacking parameter with dictionary, then we can automatically reorder the value by argument's name information inside the trace, and thus we can serialize the dictionary and assemble a traceable stack for the graph. 

## Some concerns about the implementation

1. The real data's key's name may not align with the **forward()** method's arguments' name, so we should highlight this point to make the user assure the example_inputs's key name must align with the name of the argument in the documentation if we would support this feature. When the user do not provide the expected name, we should explicitly report the error message.
2. To make a traceable stack, we don't follow the forward() arguments' order in python code. Thus the graph's input parameters' order will be different with the forward() method in python code such as:
            `graph(%self : __torch__.module.___torch_mangle_n.Mymodule, %key1 : type1, %key2 : type2, %key3 : type3)`
other than:
           `graph(%self : __torch__.module.___torch_mangle_n.Mymodule, %key2 : type2, %key3 : type3, %key1 : type1)`
If somewhere else have the assumption that the IR's input parameters' order should strictly align with the order we defined in the python code, then our implementation may be infeasible. Such as the below situation:
**If we have a module which will be traced with forward() method declaration as below:**
          ` def forward(self, key2, key3=value3, key4=value4, key5=value5, key1=value1, key6=value6):` _(with key2 as positional argumrnt)_
**When we trace the module, we pass it with dictionary:**
           `traced_module = torch.jit.trace(origin_moduel, dict_input, strict=False)`
where `dict_input` is a python dictionary such as `{'key1':value1, 'key2':value2, 'key3':value3}`
**But when we use the traced module, we pass it with positional arguments with the assumption its order should be aligned with what the python forward() code declared:**
           `traced_module(inputs[1], key1=inputs[0], key3=inputs[2])`
where inputs[1]'s value is actually correspond to **key2** as we declared in the forward(). In this situation, the invoke of traced module will fail cause we reordered the arguments with key1 as the graph's first argument.
**Possible solution 1:**
The first solution we came up with which will add some attributes in `FunctionSchema ` to represent if the arguments' order have been changed before tracing and record the original arguments' order. These attributes can be set before tracing when  we knew the **example_inputs** parameter is a dictionary, and are used the function  [`createStackForSchema()`](https://github.com/pytorch/pytorch/blob/f7ee061638aa2011191caeff4438fa8aff5bfec3/torch/csrc/jit/python/pybind_utils.h#L878) to judge if we should recover the original order when we construct the stack.
**Cons:**
To support this feature and fix this issue, we shouldn't modify any basic data structure or class such as `FunctionSchema` .
**Possible solution 1:**
We specify in the documentation of `torch.jit.trace() ` if the user would use dictionary as their `example_inputs`, then the must use the traced module with dictionary too.
 **Cons:**
This restrict the flexibility of this API.

## Note
1. This PR will make some UT introduced in [39601](https://github.com/pytorch/pytorch/pull/39601) fail, which I think should be classified as unpacking a tuple containing a single dictionary element in our solution.
2. I think there is ambiguity since currently we only specify passing a tuple or a single Tensor as our example_inputs parameter in **torch.jit.trace()**'s documentation, but it seems we can still passing a dictionary.

### CODE REVIEW

**Comment by davidberard98** [comment]
feel free to add me as a reviewer when this is ready

**Comment by tangleintel** [comment]
> feel free to add me as a reviewer when this is ready

Hi, @davidberard98 
    Thanks for your replay. Currently we are under internal review for this PR. We will complete the description of the problem and list some limitation for current implementation, and we will add some unit test to demonstrate the usage of this feature.
We are hoping the suggestions and feedbacks from you. Pls, should I add anyone else related this problem as reviewers?

**Comment by tangleintel** [comment]
@davidberard98 
@jamesr66a 
@wanchaol 
@xw285cornell

**Comment by tangleintel** [comment]
Close this one & create [81623](https://github.com/pytorch/pytorch/pull/81623)

**Pull request closed without merging**
