### PR TITLE
Optimize SpatialBNOp

### PR DESCRIPTION
**Pull request by xiaomengy**
Summary: Optimize SpatialBNOp

Differential Revision: D10459650

### CODE REVIEW

**Comment by BIT-silence** [comment]
Benchmark

Forward GPU, N = 256, C = 256, H = 128, W = 128
NCHW training: 96.79 -> 79.89
NCHW test: 64.41 -> 49.12
NHWC training: 143.32 -> 126.68
NHWC test: 95.90 -> 75.59

Backward GPU, N = 128, C = 256, H = 128, W = 128
NCHW: 138.10 -> 56.22
NHWC: 617.45 -> 528.33

**Review by houseroad — APPROVED** [review]

**Comment by ezyang** [comment]
Hey @houseroad, what's the status on landing this patch

**Comment by houseroad** [comment]
@ezyang let's wait @BIT-silence to land it. He will be back to MPK in 2 weeks.

**Comment by houseroad** [comment]
Close the PR since it's abandoned.

**Pull request closed without merging**
