### PR TITLE
Support RRefs that contain torch.cuda.Event

### PR DESCRIPTION
**Pull request by pbelevich**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#61354**

Differential Revision: [D29617155](https://our.internmc.facebook.com/intern/diff/D29617155)

### CODE REVIEW

**Review by mrshenli — COMMENTED** [review]
Curious, this seems just modifies the test file. Do we need any changes in non-test files to support it or this aims to improve test coverage?

**Comment by pbelevich** [comment]
@mrshenli It wasn't ready for review yesterday, but now it's ready for review

**Review by lw — APPROVED** [review]
Overall I'm good with this change. One worry I have is what will happen when CUDA is not available (i.e., in CPU-only builds). The tests pass, so apparently this is fine, but I wonder if it would be safer to guard these checks with `if torch.cuda.is_available():`.

**Comment by pbelevich** [comment]
@pbelevich has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29617155).

**Pull request closed without merging**
