### PR TITLE
Test case for calling layer norm with double tensors

### PR DESCRIPTION
**Pull request by smessmer**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #16625 Implement new c10 dispatcher&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13907069/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #16534 Automatically register c10 ops with JIT&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13869275/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #16535 Define layer_norm schema in caffe2&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13869503/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #16548 C10_REGISTER_CAFFE2_OPERATOR: Macro for registering c2 kernels&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13877076/)
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#16554 Test case for calling layer norm with double tensors**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13877510/)

Add a test case that makes sure that caffe2's dtype dispatch works fine when called from c10

Differential Revision: [D13877510](https://our.internmc.facebook.com/intern/diff/D13877510/)

### CODE REVIEW

**Comment by ezyang** [comment]
These review comments are from reviewing the entire dispatch code as a whole. There isn't a good place to put them, so I'm putting them on the top diff on the stack.

https://github.com/pytorch/pytorch/tree/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch

It would be really good to have a README describing the basic orientation of how the code in here works.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/KernelCache.h#L10

I don't know what it means for a cache to be "owned by the call site". Probably would be clearer to say which struct actually owns it here.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/KernelFunction.h#L12

"global C function" is a weird thing to say. In particular, it would work to register a function with static-visibility to the dispatcher. You are probably trying to say that closures are not supported; function pointers only. But the fact that something is a function pointer is sufficient to also rule out the presence of closures.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L21

nit: Capitalize here

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L32

You can make this doc even clearer by explicitly spelling out the nullability invariants of the pointer fields. I'm guessing `kernel_func` is always non-null and `cache_creator_func` can be null, if no cache is used?

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L39

nit: Isn't it `detail` not `details`?

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L82

I'm quite concerned about use of LeftRight here.  The implementation appears to be homegrown, and it has no tests. It is doing nontrivial lock-free programming. I am not confident in my ability to verify that it is correct. I don't want to be debugging issues in prod because of a buggy implementation of LeftRight.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L75

Given that you've written DispatchTable as a thread-safe structure, I'm not sure what the utility of testing that it's empty. You could find out that it's empty but immediately after another thread registers a kernel. This just feels like a bug waiting to happen with someone who is not thinking with their multithreading hats on.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L147

Should this be part of the public API? Here's the argument against: if we don't say you can get the FunctionSchema from a DispatchTable, then we don't need to store FunctionSchema at all in DispatchTable, we only store the pieces we need. This lets us design FunctionSchema inefficiently; it doesn't matter because at runtime all of it is erased.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L140

Including dispatch key here is really important. Knowing that it's the CUDA kernel missing is really useful info if you've got a static initializer problem.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.cpp#L1

Didn't we agree not to add these empty files?

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/Dispatcher.h#L21

Is OpKernel thread safe?

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/Dispatcher.h#L51

Hot take: this should be `mutable`. Because presence of cache is supposed to be unobservable to user.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/Dispatcher.h#L33

Then this would be this-const

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/Dispatcher.h#L46

This comment makes sense given the history, but by itself it doesn't make that much sense ;) (Of course! Why are you telling me this...)

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/Dispatcher.h#L50

Non-actionable comment, but it was a little disconcerting to see this pair of fields show up in two structs (this and DispatchTableEntry). I am not sure if it makes semantic sense for `OpKernel` to contain a `DispatchTableEntry`

**Comment by ezyang** [comment]
I've gotten to the point of the listener business. I will have to think about it.

**Comment by smessmer** [comment]
This addresses all comments:

> These review comments are from reviewing the entire dispatch code as a whole. There isn't a good place to put them, so I'm putting them on the top diff on the stack.
> 
> https://github.com/pytorch/pytorch/tree/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch
> 
> It would be really good to have a README describing the basic orientation of how the code in here works.

I squashed the commits into https://github.com/pytorch/pytorch/pull/16625. I also added a README.

> [pytorch/aten/src/ATen/core/dispatch/KernelCache.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/KernelCache.h#L10)
> 
> Line 10 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>   * This cache owned by the call site and passed in to the kernel as a function 
> I don't know what it means for a cache to be "owned by the call site". Probably would be clearer to say which struct actually owns it here.

done



> [pytorch/aten/src/ATen/core/dispatch/KernelFunction.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/KernelFunction.h#L12)
> 
> Line 12 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>   * pointer to a global C function of this type. 
> "global C function" is a weird thing to say. In particular, it would work to register a function with static-visibility to the dispatcher. You are probably trying to say that closures are not supported; function pointers only. But the fact that something is a function pointer is sufficient to also rule out the presence of closures.

done



> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L21)
> 
> Line 21 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>   * this is stored together with the kernel function in the dispatch table 
> nit: Capitalize here

done

> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L32)
> 
> Line 32 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>   * this same cache instance. 
> You can make this doc even clearer by explicitly spelling out the nullability invariants of the pointer fields. I'm guessing `kernel_func` is always non-null and `cache_creator_func` can be null, if no cache is used?
> 
> EDIT: But the code here contradicts my intuition!
> 
> [pytorch/aten/src/ATen/core/dispatch/Dispatcher.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/Dispatcher.h#L35)
> 
> Line 35 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  AT_ASSERT(cache_creator_ != nullptr);

done

> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L39)
> 
> Line 39 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  namespace details { 
> nit: Isn't it `detail` not `details`?

done



> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L82)
> 
> Line 82 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  LeftRight<ska::flat_hash_map<TensorTypeId, DispatchTableEntry>> map_; 
> I'm quite concerned about use of LeftRight here. The implementation appears to be homegrown, and it has no tests. It is doing nontrivial lock-free programming. I am not confident in my ability to verify that it is correct. I don't want to be debugging issues in prod because of a buggy implementation of LeftRight.

I actually already have another PR out that fixes this: https://github.com/pytorch/pytorch/pull/16524



> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L75)
> 
> Line 75 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  bool isEmpty() const { 
> Given that you've written DispatchTable as a thread-safe structure, I'm not sure what the utility of testing that it's empty. You could find out that it's empty but immediately after another thread registers a kernel. This just feels like a bug waiting to happen with someone who is not thinking with their multithreading hats on.

This is not exposed in the `Dispatcher` API. Any user code doesn't have access to `DispatchTable` but only to `Dispatcher`. `isEmpty` is only used by the Dispatcher itself to check that when you deregister an operator schema, it doesn't have any kernels anymore.

> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L45)
> 
> Line 45 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  auto result = map.emplace(key, value); 
> So, does this overwrite the previous kernel if there was one? There are no docs anywhere for `emplace`, so I cannot tell! (If it does overwrite, isn't that really weird, since you're going to throw an exception?)

This follows this API: https://en.cppreference.com/w/cpp/container/unordered_map/emplace
If the key already exists, it is not added but the returned boolean is false, in which case I throw an exception.

> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L89)
> 
> Line 89 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>   * Given an operator specified by 'OpSchemaDef', this class records a dispatch 
> OpSchemaDef is out of date right

done

> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L133)
> 
> Line 133 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  TensorTypeId dispatch_key = torch::jit::peek( 
> Just observing: now that this is the only dispatch key, the hash map is unnecessary. It might be worth pointing out in code that this is a hash map expressly to support hypothetical complicated dispatch keys, and if those don't materialize, you ought to replace this with something simpler.

Why is the map unnecessary? It could be replaced with a vector and have the index be the dispatch key I guess as long as you only have very few dispatch keys, but that'd take more space and wouldn't be faster

> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L118)
> 
> Line 118 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  // TODO: This isn't going to work so well when we get more complicated 
> So... shouldn't we just not support this, for now?

you mean not support removing kernels? I don't think it hurts to support it, however we change it later there is going to be some handle that can be used to deregister it again. For now, that's the dispatch key, later that might be something else.

> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L93)
> 
> Line 93 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>   * as (CPUFloatTensor, CPUFloatTensor), (CUDAFloatTensor, CUDAFloatTensor), etc. 
> This bit is also out of date

done

> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L147)
> 
> Line 147 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  const FunctionSchema& schema() const { 
> Should this be part of the public API? Here's the argument against: if we don't say you can get the FunctionSchema from a DispatchTable, then we don't need to store FunctionSchema at all in DispatchTable, we only store the pieces we need. This lets us design FunctionSchema inefficiently; it doesn't matter because at runtime all of it is erased.
> 
> This was prompted by the fact that you are caching `index_of_first_tensor_arg_`

done

> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.h#L140)
> 
> Line 140 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  // TODO Better error message - include op name and dispatch key (i.e. 
> Including dispatch key here is really important. Knowing that it's the CUDA kernel missing is really useful info if you've got a static initializer problem.

done

> [pytorch/aten/src/ATen/core/dispatch/DispatchTable.cpp](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/DispatchTable.cpp#L1)
> 
> Line 1 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  #include <ATen/core/dispatch/DispatchTable.h> 
> Didn't we agree not to add these empty files?

done

> [pytorch/aten/src/ATen/core/dispatch/Dispatcher.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/Dispatcher.h#L21)
> 
> Line 21 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>   * multiple times (mostly Caffe2 kernels do that). 
> Is OpKernel thread safe?

No, because we can't assume that the kernel handles its state in a thread safe way. I added a comment.

> [pytorch/aten/src/ATen/core/dispatch/Dispatcher.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/Dispatcher.h#L51)
> 
> Line 51 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  std::unique_ptr<c10::KernelCache> cache_; 
> Hot take: this should be `mutable`. Because presence of cache is supposed to be unobservable to user.

> [pytorch/aten/src/ATen/core/dispatch/Dispatcher.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/Dispatcher.h#L33)
> 
> Line 33 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  void call(Stack* stack) { 
> Then this would be this-const

done

> [pytorch/aten/src/ATen/core/dispatch/Dispatcher.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/Dispatcher.h#L46)
> 
> Line 46 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  // The kernel function is a global C function, not a std::function. 
> This comment makes sense given the history, but by itself it doesn't make that much sense ;) (Of course! Why are you telling me this...)

removed

> [pytorch/aten/src/ATen/core/dispatch/Dispatcher.h](https://github.com/pytorch/pytorch/blob/097dfebdb2db85e854f21dc8ee7fb34e2d424409/aten/src/ATen/core/dispatch/Dispatcher.h#L50)
> 
> Line 50 in [097dfeb](/pytorch/pytorch/commit/097dfebdb2db85e854f21dc8ee7fb34e2d424409)
> 
>  KernelCacheCreatorFunction* cache_creator_; 
> Non-actionable comment, but it was a little disconcerting to see this pair of fields show up in two structs (this and DispatchTableEntry). I am not sure if it makes semantic sense for `OpKernel` to contain a `DispatchTableEntry`

I'll keep it separate for now. I agree it's a bit weird but I think they're semantically different.

**Comment by ezyang** [comment]
> Why is the map unnecessary? It could be replaced with a vector and have the index be the dispatch key I guess as long as you only have very few dispatch keys, but that'd take more space and wouldn't be faster

Err... there are many valid reasons to defend the use of a map, but that using a linear vector would "take more space and wouldn't be faster" is not a good one. In the degenerate case, it's much better to have an array of two elements, than a hash table internally keeping an array of N elements (because you need to keep the load factor low) and needing to run a hash on the input integer before indexing into this array.

>  I don't think it hurts to support it, however we change it later there is going to be some handle that can be used to deregister it again.

There is a very real cost to adding features which you don't need, which is if you ever hand this code off to someone else, and they are attempting to make a change, and then they discover that their change doesn't work with handle deregistration, they have to identify that no, they *don't* actually need to keep this working, and can just delete it if it causes problems. I agree it is probably not going to cause a problem as long as you keep working on this code exclusively.

**Pull request closed without merging**
