### PR TITLE
Make c10::Device::validate() debug-only assert.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#44322 Make c10::Device::validate() debug-only assert.**

Callgrind profiling suggests that c10::Device::validate() is
a hot spot on the "add tensors together microbenchmark".  In
normal PyTorch use, validation of device arguments is done
in the Python binding level, which suggests we should just
assume that C++ clients have validated everything already.
Switch this to debug-only assert.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D23581892](https://our.internmc.facebook.com/intern/diff/D23581892)

### CODE REVIEW

**Review by bhosmer — APPROVED** [review]

**Comment by ngimel** [comment]
What about c++ API use? Can someone shoot themselves in the foot? It's still weird that this function is so expensive.

**Comment by ezyang** [comment]
@ngimel Yes, it is possible that C++ API people can shoot themselves in the foot this way. To start I'm going to see if we explicitly test for this in CI, but beyond that, we'll have to see what the implications are.

One thing that might make it better is usually there is error checking for Device later on (e.g., in the CUDA APIs) so it won't be too terrible if your device isn't valid (and it's still possible that the device is invalid, e.g., the device index is too big) as we'll probably catch it later.

**Comment by ezyang** [comment]
Callgrind suggested this is 5% of instructions retired on add benchmark. In real microbenching, we observed 2-4% wall clock speed up.

**Comment by ezyang** [comment]
Test failures are real. It looks like we were in fact relying on the validate() checks to verify that devices constructed in Python are valid. So to actually cash on this we will have to do some more work.

**Comment by dzhulgakov** [comment]
Wow, this is a very interesting finding!

Some hot takes:

- validate() is an inlined function (because it's in a header file), TORCH_CHECK generates a bunch of code for message formatting inline, I wonder whether it messes up the inlining strategy and breaks some compiler optimizations (thus causing increase in instructions and walltime). Have you looked at assembly of functions that invoke validate()?
- possible fix for TORCH_CHECK might be to explicitly call to a function to do string concats instead of putting it inline. One way is to put "noinline" annotation on c10::str (https://github.com/pytorch/pytorch/blob/master/c10/util/StringUtil.h#L86) or create another wrapper for its invocation in TORCH_CHECK that would be marked with noinline
- a very interesting experiment to do is to define all of TORCH_CHECK and friends to be noops and measure the impact on microbenchmark. That'd give us an upper bound on optimizations here. Not sure whether we tried it in the past or not

cc @ezyang @robieta @ngimel - we should probably try all of the above

**Pull request closed without merging**
