### PR TITLE
Fix torch.normal with CUDA tensors

### LINKED ISSUE #22529: torch.distributions.Normal cuda sampling broken
## 🐛 Bug

Normal distribution returns wrong samples if provided cuda tensors, and all the samples take the same value.

## To Reproduce

```
>>> mean = torch.tensor([0.0, 2.0], device='cuda')
>>> std = torch.tensor([1.0, 2.0], device='cuda')
>>> dist = torch.distributions.Normal(mean, std)
>>> dist.sample((10,))
tensor([[0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.],
        [0., 6.]], device='cuda:0')
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.2.0.dev20190703 (nightly)
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): pip3
 - Python version: 3.5.2
 - CUDA/cuDNN version: 10.0/7 
 - GPU models and configuration: 2 x GTX 1080 Ti

### PR DESCRIPTION
**Pull request by vishwakftw**
`addcmul_out` overwrote the samples, which led to constant values being output by `torch.normal`. 

Changelog:
- Replace the `addcmul_out` calls with combo of inplace `mul` and `add` and justification for this change.

Test Plan:
- Enable tests for test_normal on all devices

Fixes #22529

### CODE REVIEW

**Comment by fmassa** [comment]
We really need more tests for the random functions...

**Comment by vishwakftw** [comment]
We actually have tests for `torch.normal`, but didn’t check for different backends.

https://github.com/pytorch/pytorch/blob/6f6a680481d75350bcf32fbc535ed20a6f033b41/test/test_torch.py#L9524

**Review by syed-ahmed — COMMENTED** [review]
Thank you! LGTM.

CC: @ngimel @ezyang Looks like addcmul_out was't the right answer :)

**Review by syed-ahmed — APPROVED** [review]

**Pull request closed without merging**
