### PR TITLE
Remove an unused variable from _prims_common/wrappers.py

### PR DESCRIPTION
**Pull request by rec**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #138480

----

* Extracted from https://github.com/pytorch/pytorch/pull/133492
* albanD thinks this is a bug!

### CODE REVIEW

**Comment by rec** [comment]
This is a teeny-tiny that I pulled out of one of the bigger "unused variable" pull requests on review. 😁 

@albanD @bdhirsh

**Review by albanD — COMMENTED** [review]
From looking at the history, this seems to have been added by mistake in https://github.com/pytorch/pytorch/commit/c47bdd7522c7146c091c95ff5b4ce354d7a8870c#diff-ec5749db5ba92a707aa61e5358775eb5385a2a01ebeed49dd72c70fee979e894 where the old patter is used in other part of the code.

Let's just delete the line altogether as it is a noop and doesn't seem to be a bug!

**Comment by rec** [comment]
@albanD done!

**Review by albanD — APPROVED** [review]
Thanks

**Pull request closed without merging**
