### PR TITLE
add autowrap_functions kwarg to fx.Tracer

### PR DESCRIPTION
**Pull request by alexander-soare**
Implements feature request #62021

Test it out with

```python
from torch import fx
from torch import nn

def fx_int(x):
    return int(x)

class MyModule(nn.Module):
    def forward(self, x):
        return fx_int(x.shape[0] / 2)

tracer = fx.Tracer(autowrap_functions=(fx_int,))  # or remove kwarg to demonstrate symbolic trace error
tracer.trace(MyModule())
```

First time contributor, so please advise if I could have done anything to make lives easier for next time.

### CODE REVIEW

**Comment by alexander-soare** [comment]
Test it out with

```
from torch import fx
from torch import nn

def fx_int(x):
    return int(x)

class MyModule(nn.Module):
    def forward(self, x):
        return fx_int(x.shape[0] // 2)

tracer = fx.Tracer(autowrap_functions=(fx_int,))
tracer.trace(MyModule())
```

**Review by jamesr66a — APPROVED** [review]
Looks good! Thanks

**Comment by jamesr66a** [comment]
Hey @alexander-soare  do you mind actually adding the code from your test script as a test case in `test/test_fx.py`? Thanks!

**Comment by alexander-soare** [comment]
@jamesr66a no problem. I'm afk till next week so will do so then.

**Comment by alexander-soare** [comment]
@jamesr66a I think that does it. Let me know if anything else is needed/helpful.

**Pull request closed without merging**
