### PR TITLE
Allow NJT by default for weights_only torch.load

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #140304

### CODE REVIEW

**Review by jbschlosser — APPROVED** [review]
LGTM thanks!

**Comment by huydhn** [comment]
@pytorchbot revert -m 'A bunch of failure shows up in trunk after this lands, so probably a landrace' -c landrace

https://hud.pytorch.org/pytorch/pytorch/commit/455dc4c14264a0cd7d70ba5328382a9fb7769094

**Comment by huydhn** [comment]
Just FYI, I think the same error shows up on one of the Docker build https://github.com/pytorch/pytorch/actions/runs/11829277312/job/32960838373#step:6:15068 where some transformers test model are downloaded

**Comment by mikaylagawarecki** [comment]
Relanded in https://github.com/pytorch/pytorch/pull/140739

**Pull request closed without merging**
