### PR TITLE
Fix periodic windows test

### PR DESCRIPTION
**Pull request by albanD**
This test fails to clean up folders on windows for the past week, see https://hud.pytorch.org/pytorch/pytorch/commit/27f61eba58572ffc0f3ac766d07d69ca31947ab6 for example

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]

**Comment by janeyx99** [comment]
will you add an issue to track?

**Review by zou3519 — APPROVED** [review]

**Comment by albanD** [comment]
@janeyx99 yes: https://github.com/pytorch/pytorch/issues/132650

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
