### PR TITLE
[WIP] Add stop api to rpc agent

### PR DESCRIPTION
**Pull request by xush6528**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#28238 [WIP] Add stop api to rpc agent**

This is a followup for https://github.com/pytorch/pytorch/pull/27776, especially the comment, https://github.com/pytorch/pytorch/pull/27776#discussion_r335246151.

The plan is as follow.
- Add local stop API to RpcAgent.
- Change unit tests to use stop rather than join.

Differential Revision: [D5516149](https://our.internmc.facebook.com/intern/diff/D5516149/)

### CODE REVIEW

**Comment by rohan-varma** [comment]
I have a similar change https://github.com/pytorch/pytorch/pull/28188, but the thread detaching is just added to a destructor. This is needed to fix tests for https://github.com/pytorch/pytorch/pull/26336. Do we need to have an explicit `stop` API like this? If so, can we expose this on python side as well?

**Comment by xush6528** [comment]
TODO: add python interface

**Comment by xush6528** [comment]
TODO: Make GLOO supports sending to self.

**Comment by pietern** [comment]
@xush6528 @rohan-varma Can you consolidate this one with #28188?

For both, the bottom line is that the recv from any call must be interruptible for shutdown to work without detaching the thread (this is really a final resort and we shouldn't go there).

**Pull request closed without merging**
