### PR TITLE
[JIT] Teach IRPrinter and IRParser to handle 'requires_grad' and 'device' as a part of type info.

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#41507 [JIT] Teach IRPrinter and IRParser to handle 'requires_grad' and 'device' as a part of type info.**

These fields have always been a part of tensor types, this change just
makes them serializable through IR dumps.

Differential Revision: [D22563661](https://our.internmc.facebook.com/intern/diff/D22563661)

### CODE REVIEW

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Comment by Krovatkin** [comment]
@ZolotukhinM it's a great change! I was just wondering maybe we want to hide this extra verbosity behind an environment variable? We don't always need to know device and requires_grad comparing to sizes. Just a thought

**Review by eellison — COMMENTED** [review]
Didn't do any reviewing,  but this is great! Will be super useful for debugging IR. Thanks for doing this!!

Maybe a lesson from this for future PR authoring/reviewing is to try to write less brittle FileCheck tensor tests bc the representation may continue to change. 
Like instead of writing :
`check(Float() = aten::tensor)` write `check("Float").check_same("aten::tensor")`

**Comment by ZolotukhinM** [comment]
> @ZolotukhinM it's a great change! I was just wondering maybe we want to hide this extra verbosity behind an environment variable? We don't always need to know device and requires_grad comparing to sizes. Just a thought

That sounds like a good idea. Actually, sometimes I want to hide sizes/dtypes as well :)

**Pull request closed without merging**
