### PR TITLE
Fix grid_sample gradients at image borders

### LINKED ISSUE #23925: 'border' and 'reflection’ modes of grid_sample have incorrect gradients at border
## 🐛 Bug

When `padding_mode='border'` in `grid_sample`, and a grid point falls exactly on the high boundary of the image (`size - 1`), the gradient should be based on the border padding scheme, which should give either the gradient from just inside the boundary, or zero from just outside the boundary (either could be valid, since it’s a non differentiable point). Instead, the gradient is currently based on zero padding the image, which gives wacky results.

Same problem occurs with `padding_mode='reflection'` for 2D `grid_sample` on CPU.
Reflection modes of both the cuda version and the 3D CPU version also have this problem, but it’s arguably worse, since the incorrect gradient is also negated. Furthermore, this is an inconsistency between the behavior of CPU and CUDA kernels.

## Example:
```python
image = torch.arange(0, 5, dtype=torch.float).expand((1,1,5,5)).requires_grad_()

id_grid = torch.nn.functional.affine_grid(
    torch.tensor([[[1,0,0],[0,1,0.]]]), (1,1,5,5), align_corners=True).requires_grad_()

torch.nn.functional.grid_sample(image, id_grid, padding_mode='border',
                                align_corners=True).sum().backward()

print(id_grid.grad.permute(0,3,1,2))
```
```python
tensor([[[[ 2.,  2.,  2.,  2., -8.],
          [ 2.,  2.,  2.,  2., -8.],
          [ 2.,  2.,  2.,  2., -8.],
          [ 2.,  2.,  2.,  2., -8.],
          [ 2.,  2.,  2.,  2., -8.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0., -2., -4., -6., -8.]]]])
```

Notice the wacky last row and last column. This is because the gradient there is currently calculated as if the image was zero-padded.

The result should ideally look like

```python
tensor([[[[ 2.,  2.,  2.,  2.,  2.],
          [ 2.,  2.,  2.,  2.,  2.],
          [ 2.,  2.,  2.,  2.,  2.],
          [ 2.,  2.,  2.,  2.,  2.],
          [ 2.,  2.,  2.,  2.,  2.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]]])
```

which finds the gradient using the in-bounds neighbor.

A less ideal, but still palatable result would be

```python
tensor([[[[ 2.,  2.,  2.,  2.,  0.],
          [ 2.,  2.,  2.,  2.,  0.],
          [ 2.,  2.,  2.,  2.,  0.],
          [ 2.,  2.,  2.,  2.,  0.],
          [ 2.,  2.,  2.,  2.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]]])
```

which finds the gradient using the out-of-bounds, border-padded neighbor.

Reflection mode on cpu (for instance, try using these same commands, but with `padding_mode='reflection'`) gives the exact same problematic result.
When using reflection mode on cuda, however, (as well as for 3D grid_sample on cpu) the problematic gradients are negated!

```python
tensor([[[[2., 2., 2., 2., 8.],
          [2., 2., 2., 2., 8.],
          [2., 2., 2., 2., 8.],
          [2., 2., 2., 2., 8.],
          [2., 2., 2., 2., 8.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [-0., 2., 4., 6., 8.]]]])
```

This is also problematic, of course, but even more so because of the mismatch between the cpu and cuda behaviors.

For `reflection` mode, I think it makes sense to set the gradient in such cases to zero, since it’s sort of at the apex of a symmetric hill. But setting it to take the gradient of one side or the other might also be acceptable for most practical purposes.

For `border` mode, by contrast, I think it makes more sense to always take the non-zero gradient from the inner side, since the outer side gradient will be zero and so effectively stop training (see the related discussion for `clamp` at #7002 and #7049).

PyTorch Version: tested on commit https://github.com/pytorch/pytorch/commit/0539462ca2966aa29657b58aeb17a85c21524d31

### PR DESCRIPTION
**Pull request by bnehoran**
Fixes #23925

This fixes the incorrect gradients returned by `F.grid_sample` at image borders under `"border"` and `"reflection"` padding modes.

At nondifferentiable points, the choice of which gradient to return among its super- or subgradients is rather arbitrary and generally does not affect training. Before this change, however, a bug in the code meant that the gradient returned at the exact borders was not selected from among the super- or subgradients.

The gradient is now set to zero at the borders, which is a defensible choice for both the `"border"` and `"reflection"` padding modes:
* For `"border"` padding, this effectively means that the exact borders of the image are now considered out of bounds, and therefore receive zero gradient.
* For `"reflection"` padding, this effectively treats the exact borders as extrema.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 883aa617:


* **2/2** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=883aa61732bc8ada55a8d5e9c6dcb496be6a71e7).

### :detective: 2 new failures recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4381188) pytorch_linux_xenial_py3_6_gcc5_4_build (1/2)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=93313324) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=93313324))
<details>
<summary>
<code>Automatic merge failed; fix conflicts and then commit the result.</code>
</summary>

```
CONFLICT (add/add): Merge conflict in .circleci/docker/ubuntu/Dockerfile 
Auto-merging .circleci/docker/ubuntu/Dockerfile 
CONFLICT (add/add): Merge conflict in .circleci/docker/common/install_travis_python.sh 
Auto-merging .circleci/docker/common/install_travis_python.sh 
CONFLICT (add/add): Merge conflict in .circleci/docker/build.sh 
Auto-merging .circleci/docker/build.sh 
CONFLICT (add/add): Merge conflict in .circleci/config.yml 
Auto-merging .circleci/config.yml 
CONFLICT (add/add): Merge conflict in .circleci/cimodel/data/dimensions.py 
Auto-merging .circleci/cimodel/data/dimensions.py 
Automatic merge failed; fix conflicts and then commit the result. 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4381189) pytorch_xla_linux_xenial_py3_6_clang7_build (2/2)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=93313539) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=93313539))
<details>
<summary>
<code>Jan 30 17:11:50 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff</code>
</summary>

```
Jan 30 17:11:50 File to patch:  
Jan 30 17:11:50 Skip this patch? [y]  
Jan 30 17:11:50 4 out of 4 hunks ignored 
Jan 30 17:11:50 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-clip_grad.diff 
Jan 30 17:11:50 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff 
Jan 30 17:11:50 Traceback (most recent call last): 
Jan 30 17:11:50   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 67, in <module> 
Jan 30 17:11:50     patch_repo(args) 
Jan 30 17:11:50   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 49, in patch_repo 
Jan 30 17:11:50     raise RuntimeError('Failed to apply patch: {}'.format(ppath)) 
Jan 30 17:11:50 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff 
Jan 30 17:11:50 + cleanup 
Jan 30 17:11:50 + retcode=1 
Jan 30 17:11:50 + set +x 
Jan 30 17:11:50 =================== sccache compilation log =================== 
Jan 30 17:11:50 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 30 17:11:50 Compile requests                 1 
Jan 30 17:11:50 Compile requests executed        0 
Jan 30 17:11:50 Cache hits                       0 
Jan 30 17:11:50 Cache misses                     0 
Jan 30 17:11:50 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by bnehoran** [comment]
The following example demonstrates the difference:
```python
# example code to reproduce the bug:
image = torch.arange(0, 5, dtype=torch.float).expand((1,1,5,5)).requires_grad_()
id_grid = torch.nn.functional.affine_grid(
    torch.tensor([[[1,0,0],[0,1,0.]]]), (1,1,5,5), align_corners=True).requires_grad_()
torch.nn.functional.grid_sample(image, id_grid, padding_mode='border',
                                align_corners=True).sum().backward()
print(id_grid.grad.permute(0,3,1,2))
```
Before, this would result in
```python
tensor([[[[ 2.,  2.,  2.,  2., -8.],
          [ 2.,  2.,  2.,  2., -8.],
          [ 2.,  2.,  2.,  2., -8.],
          [ 2.,  2.,  2.,  2., -8.],
          [ 2.,  2.,  2.,  2., -8.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0., -2., -4., -6., -8.]]]])
```
Notice that the last column in the first component and the last row in the second component are terribly off.
After this change, the result is
```python
tensor([[[[0., 2., 2., 2., -0.],
          [0., 2., 2., 2., -0.],
          [0., 2., 2., 2., -0.],
          [0., 2., 2., 2., -0.],
          [0., 2., 2., 2., -0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., -0., -0., -0., -0.]]]])
```
Notice how the each of the borders now properly has zero gradient in the direction perpendicular to that border.

**Comment by ezyang** [comment]
Give us a holler if you need someone else to look at the PR; for now, waiting on @fmassa

**Comment by bnehoran** [comment]
I've now added explicit unit tests for the border gradient edge cases.

**Review by soumith — APPROVED** [review]
looks good to me overall. sorry for the delay.

**Pull request closed without merging**
