### PR TITLE
Add non-reentrant checkpoint to composable APIs

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #90015
* #89971
* #89930

Differential Revision: [D41661027](https://our.internmc.facebook.com/intern/diff/D41661027)

### CODE REVIEW

**Review by zhaojuanmao — APPROVED** [review]
awesome!

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41661027).

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41661027).

**Pull request closed without merging**
