### PR TITLE
Remove legacy Caffe2 pthreadpool from CMake

### PR DESCRIPTION
**Pull request by cyyever**
Fixes #ISSUE_NUMBER

cc @malfet @seemethere @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by ezyang** [comment]
This probably will not work in fbcode

**Comment by ezyang** [comment]
```
Buck build failed for this target, and is likely caused by your changes.
Error message:
[New Failure] Target failed to build.
File not found: `fbcode//caffe2/caffe2/utils/threadpool/pthreadpool.h
```

**Comment by cyyever** [comment]
> ```
> Buck build failed for this target, and is likely caused by your changes.
> Error message:
> [New Failure] Target failed to build.
> File not found: `fbcode//caffe2/caffe2/utils/threadpool/pthreadpool.h
> ```

Need help to change the BUCK code to point to third-party's pthreadpool header.

**Comment by ezyang** [comment]
buck changes insufficient. it might be internal only build file

**Comment by cyyever** [comment]
@ezyang Should be safe for CMake only changes. Can help import them into META？

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
