### PR TITLE
[follow-up] Python Attr Serialization

### PR DESCRIPTION
**Pull request by kshitij12345**
Ref: https://github.com/pytorch/pytorch/pull/81616#issuecomment-1307595402

cc @ezyang @gchanan

### CODE REVIEW

**Comment by kshitij12345** [comment]
@albanD do you think it would be good to merge this now? Is this past FC period?

**Comment by kshitij12345** [comment]
Oops, Sorry! Wrong PR 😓🙏 

Also, ping @albanD

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by mehtanirav** [comment]
@kshitij12345  Unfortunately this PR had to been reverted as the earlier changes haven't been released yet to production owing to the code freeze. @singlaiiit can add more context if I missed anything.

**Comment by albanD** [comment]
@mehtanirav when will it be safe to land this then?

**Comment by kshitij12345** [comment]
Ping @mehtanirav :)

**Comment by mehtanirav** [comment]
> Ping @mehtanirav :)

Sorry, I missed replying to your message. Let me follow up with the relevant oncalls to check when the next release would happen. After the release, it would be safe to re-land this change. I will post an update here by EOD today.

**Comment by mehtanirav** [comment]
@albanD  @kshitij12345  The changes from the previous PR  (https://github.com/pytorch/pytorch/pull/81616) which added the method have still not been rolled out to production due to recent code freeze/production issues. 

As there are multiple blockers for the release, there is no clear ETA on when the next release would take place. I will keep this thread posted as soon as there is an update.

Sorry for the inconvenience.

**Comment by albanD** [comment]
Thanks for the update @mehtanirav !

**Comment by albanD** [comment]
ping @mehtanirav any new update on this?

**Comment by kshitij12345** [comment]
Gentle ping @mehtanirav :)

**Comment by albanD** [comment]
@pytorchbot merge -r

Let's try this again.

**Comment by albanD** [comment]
Hmmm rebase failed...
Could you do a manual rebase please?

**Comment by kshitij12345** [comment]
Done. Will merge it once the CI is green. Thanks @albanD

**Comment by kshitij12345** [comment]
Distributed failure looks real. Investigating 🔍

**Comment by albanD** [comment]
Hey!
Yes we can drop any autograd Node!

**Comment by kshitij12345** [comment]
What would be the correct way to do an `isinstance` for any autograd node? Thanks!

**Comment by kshitij12345** [comment]
@albanD 

Hit another roadblock,
```
AttributeError: Can't pickle local object '_apply_optimizer_in_backward.<locals>._apply_optimizer_in_backward_to_param.<locals>.optimizer_hook'
 exiting process 1 with exit code: 10
```

So post that I tried to see what all state does the parameter have in distributed setting. Looks like it has a lot of state. I was wondering if we should be serialising this state (in distributed setting). Maybe the distributed module attaches the state with the assumption that it won't be serialised and doing so may cause perf regression.

Attributes stored in distributed setting:
```
{'_ddp_ignored': True, '_acc_grad': <AccumulateGrad object at 0x7f57b5fe41c0>, '_in_backward_optimizers': [SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.03
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)], '_optimizer_classes': [<class 'torch.optim.sgd.SGD'>], '_optimizer_kwargs': [{'lr': 0.03}], '_optimizer_hook_handles': [<torch.utils.hooks.RemovableHandle object at 0x7f57b5fe4d60>]}
```

**Comment by albanD** [comment]
Ok!
Taking a step back, I think it is fair to say that some users will want to store data on the Tensor that is not persistent.
What do you think about adding a `t.volatile_attr` (or volatile_state) dict on the Tensor object that can be used by users who want to save attribute on the Tensor but not serialize them?
We can even update the error during serialization for user attributes to point them to it.
WDYT?

cc @awgu who added these states on the distributed side, does that make sense to you?

**Comment by kshitij12345** [comment]
That sounds like a nice idea! Curious to know @awgu view on the same.

**Comment by albanD** [comment]
btw from offline chat with Ed, another direction to for the user to use WeakMap to store such metadata.
Maybe for simplicity's sake, it would be better to not add this new feature and just migrate the FSDP code to use a weak map.

**Comment by awgu** [comment]
To check my understanding: If an `nn.Parameter` stores any state that should not be serialized, we must convert that state to not be stored on the `nn.Parameter`, and instead, we should store something like a `WeakValueDictionary[str, ...]` that maps attribute name to the attribute value and replace attribute accesses on the `nn.Parameter` with accesses to the dictionary.

If this is the correct understanding, then I have two follow-ups:
1. Which entity should manage the `WeakValueDictionary`?
2. How much work is it to migrate the code base to use the `WeakValueDictionary`?

For FSDP: Some attributes stored on the `FlatParameter` include other `torch.Tensor`s (`_local_shard`, `_mp_shard`, `_cpu_grad`, etc.), the post-backward hook handle, and the `AccumulateGrad` object on which the hook was registered. (There are probably more.) For the `Tensor`s, we cannot use a `WeakValueDictionary` since there are no other references to keep them alive. The correct approach should be to move them to the `FlatParamHandle` class, which was introduced exactly to allow `FlatParameter` to be a plain `nn.Parameter`. The post-backward hook handle and `AccumulateGrad` can similarly be moved without need for the `WeakValueDictionary`.

For `_apply_optimizer_in_backward` (mentioned above by @kshitij12345): I am not sure which entity should manage the `WeakValueDictionary` since `_apply_optimizer_in_backward` should be agnostic to the high-level distributed API (e.g. whether `DistributedDataParallel`, `FullyShardedDataParallel`, or the new composable APIs like `replicate` and `fully_shard`).
Should the `WeakValueDictionary` simply be a global variable? (Maybe that will work..)

cc: @rohan-varma @zhaojuanmao @mrshenli

**Comment by albanD** [comment]
We had a quick offline discussion. The proposal is not a WeakValueDictionary but a WeakKeyDictionary. So the lifetime of the attribute will still be linked to the Tensor exactly as it is today.

I think that either way, the user will need to know either about this special volatile attribute or about using a WeakKeyDict. So the WeakKeyDict sounds like a better approach as it keeps the Tensor class simpler.
@rohan-varma can you confirm that you're happy with us migrating these attributes to a WeakKeyDict in the distributed code to unblock this PR?

**Comment by albanD** [comment]
> One q is who will be responsible for managing these dictionaries?

Each feature that needs one will have one.
We can use the one from torch.utils.weak that is specialized for Tensors already. The dictionary can be stored as a global in whatever file it is used in.

**Comment by kshitij12345** [comment]
For now, I have updated `_acc_grad` and `_optimizer_hook_handles` to be mapped to a parameter with a `WeakTensorKeyDictionary` (will follow-up in a separate PR  for other attributes if it is deemed to be worth avoiding their serialisation).

The distributed tests are passing. Only failure in the Windows CI is unrelated. `torch_test_cpp_extension.cpp` fails with following error

```
2023-01-12T12:51:45.3403220Z FAILED: C:/actions-runner/_work/pytorch/pytorch/test/cpp_extensions/build/temp.win-amd64-cpython-39/Release/extension.obj 
2023-01-12T12:51:45.3406353Z cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\include -IC:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\include\torch\csrc\api\include -IC:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\include\TH -IC:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\include\THC -IC:\actions-runner\_work\pytorch\pytorch\test\cpp_extensions\self_compiler_include_dirs_test -IC:\Jenkins\Miniconda3\include -IC:\Jenkins\Miniconda3\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c C:\actions-runner\_work\pytorch\pytorch\test\cpp_extensions\extension.cpp /FoC:\actions-runner\_work\pytorch\pytorch\test\cpp_extensions\build\temp.win-amd64-cpython-39\Release\extension.obj /sdl /permissive- -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=cpp -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++17
2023-01-12T12:51:45.3409533Z C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\include\c10/macros/Macros.h(138): warning C4067: unexpected tokens following preprocessor directive - expected a newline
2023-01-12T12:51:45.3410543Z C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\include\c10/util/Optional.h(212): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
2023-01-12T12:51:45.3411050Z         with
2023-01-12T12:51:45.3411272Z         [
2023-01-12T12:51:45.3411516Z             T=c10::SymInt
2023-01-12T12:51:45.3411752Z         ]
```

**Comment by kshitij12345** [comment]
Ping @albanD @awgu for another review. Thanks :)

**Review by albanD — APPROVED** [review]
Looks pretty clean!
Sounds good to me!

**Pull request closed without merging**
