### PR TITLE
TBB: Use static partitioner to match OpenMP scheduling

### LINKED ISSUE #64571: TestTensorCreationCPU.test_trilu_indices_cpu  crashes in ParallellTBB mode
## To Reproduce

1. Build PyTorch with TBB support:
```
ATEN_THREADING=TBB REL_WITH_DEB_INFO=ON USE_TBB=ON USE_CUDA=OFF BUILD_CAFFE2_OPS=OFF python setup.py develop --user
```
2. Run test_trilu_indices_cpu: it has a roughly 50-50 chance of hitting internal assert or crashing
```
$ python test_tensor_creation_ops.py -v TestTensorCreationCPU.test_trilu_indices_cpu
test_trilu_indices_cpu (__main__.TestTensorCreationCPU) ... ERROR

======================================================================
ERROR: test_trilu_indices_cpu (__main__.TestTensorCreationCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nshulga/git/pytorch/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
    raise rte
  File "/home/nshulga/git/pytorch/torch/testing/_internal/common_device_type.py", line 373, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/nshulga/git/pytorch/torch/testing/_internal/common_device_type.py", line 913, in only_fn
    return fn(slf, *args, **kwargs)
  File "test_tensor_creation_ops.py", line 1176, in test_trilu_indices
    _compare_trilu_indices(self, *test_args)
  File "/home/nshulga/git/pytorch/torch/testing/_internal/common_methods_invocations.py", line 9458, in _compare_trilu_indices
    torch.ones(row, col, device='cpu')
RuntimeError: out_ptr == out_accessor[thread_count_nonzero[tid + 1]].data()INTERNAL ASSERT FAILED at "../aten/src/ATen/native/TensorAdvancedIndexing.cpp":1717, please report a bug to PyTorch. 

----------------------------------------------------------------------
Ran 1 test in 0.021s

FAILED (errors=1)

```

## Expected behavior

Test should pass
## Environment

```
Collecting environment information...
PyTorch version: 1.10.0a0+gite161872
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Fedora release 32 (Thirty Two) (x86_64)
GCC version: (GCC) 10.0.1 20200328 (Red Hat 10.0.1-0.11)
Clang version: 10.0.1 (Fedora 10.0.1-3.fc32)
CMake version: version 3.17.4
Libc version: glibc-2.31

Python version: 3.8.7 (default, Jan 20 2021, 00:00:00)  [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] (64-bit runtime)
Python platform: Linux-5.11.12-100.fc32.x86_64-x86_64-with-glibc2.2.5
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 460.73.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.0
[pip3] torch==1.10.0a0+gite161872
[pip3] torchaudio==0.8.1
[conda] Could not collect
```

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #65327
* #65326

Should fix gh-64571

Differential Revision: [D31474116](https://our.internmc.facebook.com/intern/diff/D31474116)

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
lgtm, but can you please also remove other `skipIfTBB` instances in the code, namely one in `test_tensor_creation_ops`, which always crashes when TBB tests are run on GHA runner

**Comment by cpuhrsch** [comment]
What's the advantage of using the static_partitioner? To me one of the main value propositions of TBB is its ability to behave well in a heterogenous environment with other processes running and using resources. With the static partitioner you're [disabling all load balancing](https://software.intel.com/content/www/us/en/develop/documentation/tbb-documentation/top/intel-threading-building-blocks-developer-reference/algorithms/partitioners/staticpartitioner-class.html).

**Comment by ngimel** [comment]
Static partitioner is needed for algos that launch 2 parallel regions and depend on thread ids matching between them (that happens e.g. in nonzero)

**Comment by cpuhrsch** [comment]
Ok that makes sense. Can we have a different interface for a parallel backed by TBB that disables load balancing for this specific issue?

**Comment by peterbell10** [comment]
TBB's load balancing also breaks determinism for reduction algorithms, which is why `layer_norm` tests were failing on TBB.

**Comment by peterbell10** [comment]
@malfet I've removed the CI config changes.

**Comment by malfet** [comment]
Sorry, missed your previous message, landing now

**Pull request closed without merging**
