### PR TITLE
[sparse] Add the AO namespace to torch

### PR DESCRIPTION
**Pull request by z-a-f**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #59771 [sparsity] Lambda Scheduler
* #59770 [sparsity] Base sparsity level scheduler class
* #58955 [sparsity] WeightNormSparsifier
* #58707 [sparsity][refactor] Import factoring out
* #58704 [sparse] Sparsifier class
* #58705 [sparsity] Sparse linear layers
* **#58703 [sparse] Add the AO namespace to torch**

Differential Revision: [D28970962](https://our.internmc.facebook.com/intern/diff/D28970962)

### CODE REVIEW

**Comment by ezyang** [comment]
Link me to the proposal about this namespace?

**Comment by z-a-f** [comment]
> Link me to the proposal about this namespace?

Shared the internal doc w/u

**Review by ezyang — APPROVED** [review]
okey dokey

**Comment by z-a-f** [comment]
@zafartahirov has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28970962).

**Comment by mpjlu** [comment]
> 
Could you please share the proposal about this namespace

**Comment by csukuangfj** [comment]
What does AO mean?

**Pull request closed without merging**
