### PR TITLE
fix: check if double to i64 is in well-formed range

### LINKED ISSUE #88951: `torch.nn.functional.interpolate` Trigger RuntimeError under UndefinedBehaviorSanitizer
### 🐛 Describe the bug

The implementation of `torch.nn.functional.interpolate` contains undefined behavior caught by UB sanitizer.
Test:
```
import torch

def test():
    arg_1 = torch.rand([5, 256, 16, 16], dtype=torch.float32).clone()
    res = torch.nn.functional.interpolate(arg_1,None,-1e20,"bilinear",False,)

test()
```
Error log:
```
pytorch/aten/src/ATen/native/UpSample.cpp:26:21: runtime error: -1.6e+21 is outside the range of representable values of type 'long'
```

### Versions

```
PyTorch version: 1.14.0a0+git6e5f736
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 11.1.0-6
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[pip3] torch==1.14.0a0+git6e5f736
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0  
[conda] torch                     1.14.0a0+git6e5f736          pypi_0    pypi
```

### PR DESCRIPTION
**Pull request by ganler**
Fixes #88951

The output shape of upsample is computed through `(i64)idim * (double)scale` and then casted back to `i64`. If the input scale is ill-formed (say negative number as #88951) which makes `(double)(idim * scale)` to be out of the range for `i64`, the casting will be an undefined behaviour. 

To fix it, we just check if `(double)(idim * scale)` can fit into `i64`.

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
`TORCH_CHECK_GT` would throw an absolutely unreadable error.
Also, raising an exception here, feel somewhat unpythonic, wouldn't it be easier to clamp the value here?

Or, if you want to raise an exception, please use  `c10::checked_convert` template

Similar to how it's done in the following case:
```
python -c "import torch;print(hex(torch.tensor(1e55,dtype=torch.float64).to(torch.int32).item()))"
0x7fffffff
```

**Comment by ganler** [comment]
@malfet Thanks for the awesome suggestions! The error message looks much better now!
image

**Review by malfet — APPROVED** [review]
LGTM, please consider adding tests

**Comment by ganler** [comment]
Seems there is some flakiness in other tests. Merged master branch to re-run tests.

**Comment by ganler** [comment]
Seems the CI is ready now.

**Comment by ganler** [comment]
@malfet Could you also kindly merge this one (since the previous merge is incomplete due to flaky CI failure)? Thanks!

**Comment by malfet** [comment]
> @malfet Could you also kindly merge this one (since the previous merge is incomplete due to flaky CI failure)? Thanks!

Sure, though once PR has been approved and CI is green, feel free to issue merge command yourself.

**Comment by ganler** [comment]
Oh, I see. I thought only maintainers had merge permission. Thanks for letting me know!

**Pull request closed without merging**
