### PR TITLE
Fix wording in nn.Linear docstring.

### PR DESCRIPTION
**Pull request by TASPlasma**
Definition (Linear Transformation):
A mapping $T : V \to W$ between $F$-vector spaces $V,W$ is called a *linear transformation* if and only if

a) $T(u+v)=T(u)+T(v)$,
b) $T(cv)=cT(v)$

for all $u, v \in V$, $c \in F$.

Consequently, $T(0_V)=0_W$.

Thus $x \mapsto xA^T+b$ for nonzero $b$ is **not** a linear transformation, but is often referred to as an affine linear transformation.

### CODE REVIEW

**Review by soulitzer — APPROVED** [review]
OK!

**Comment by soulitzer** [comment]
Thanks for the PR @TASPlasma. Looks like you need to sign CLA.

**Comment by TASPlasma** [comment]
> Thanks for the PR @TASPlasma. Looks like you need to sign CLA.

I signed it, but I did so after submitting the PR. Will this cause an issue?

**Review by albanD — APPROVED** [review]
Sure

**Comment by soulitzer** [comment]
@pytorcbot merge

**Pull request closed without merging**
