### PR TITLE
Enable UFMT format on test/test_nn.py

### PR DESCRIPTION
**Pull request by zeshengzong**
Fixes some files in #123062

Run lintrunner on files:
test/test_nn.py

```bash
$ lintrunner -a --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```

cc @albanD

### CODE REVIEW

**Review by mikaylagawarecki — COMMENTED** [review]
@hippocookie Thanks for taking this on, it seems like there might still be a couple more ufmt failures https://hud.pytorch.org/pr/pytorch/pytorch/126663#25386453576, could you fix these please?

**Comment by hippocookie** [comment]
Due to inconsistent of my black version, there's some wrong format not found on my machine, I think this time it might be work, thanks for you help! :D @mikaylagawarecki

**Review by mikaylagawarecki — APPROVED** [review]
Looks like lint is passing now, thank you!

**Pull request closed without merging**
