### PR TITLE
Revert "Revert D28387767: Add forward AD test for op info"

### PR DESCRIPTION
**Pull request by albanD**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #58094 Forward AD formulas batch 3
* #57863 Forward AD formulas batch 2
* #57768 Forward AD formulas batch 1
* #58231 Revert "Revert D28387764: Codegen inplace forward AD formula from out of place one if needed"
* **#58230 Revert "Revert D28387767: Add forward AD test for op info"**

This reverts commit f88297c66bd36d075e9d50eb09a81bea74a669c6.

Differential Revision: [D28412496](https://our.internmc.facebook.com/intern/diff/D28412496)

### CODE REVIEW

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28387763).

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28412496).

**Comment by albanD** [comment]
This adds the `supports_forward_ad` to the `narrow` OpInfo as well which caused the original revert.

**Review by soulitzer — APPROVED** [review]

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28412496).

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28412496).

**Pull request closed without merging**
