### PR TITLE
Fix CODE level usage in dynamo config.py

### LINKED ISSUE #1718: [Bug]: "torchdynamo.logging.CODE print compiled functions + graphs" doesn't work
### 🐛 Describe the bug

```
# torchdynamo.logging.CODE print compiled functions + graphs
# logging.INFO print the steps that dynamo is running
# logging.WARN print warnings (including graph breaks)
# logging.ERROR print exceptions (and what user code was being processed when it occurred)
# NOTE: changing log_level will automatically update the levels of all torchdynamo loggers
log_level = tdl.CODE
```

in torch/_dynamo/config.py

torchdynamo doesn't exist anymore

even if you change to torch._dynamo it doesn't work due to recursive module import problem

### Error logs

n

### Did Dynamo succeed?

- [ ] Does dynamo.optimize("eager") succeed?

### Did AOT succeed?

- [ ] Did dynamo.optimize("aot_eager") succeed?

### Did Inductor succeed?

- [ ] Does dynamo.optimize("inductor") succeed?

### Minified repro

n

### PR DESCRIPTION
**Pull request by williamwen42**
Fixes https://github.com/pytorch/torchdynamo/issues/1718.

Tested by changing `log_level = logging.WARNING` in config.py to `log_level = logging.CODE` and running a test script that doesn't touch `log_level`.

cc @jansel @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @lezcano @fdrocha

### CODE REVIEW

**Comment by ezyang** [comment]
idk, this is kind of annoying. Can we make these strings instead? Then you don't need two instructions depending on context

**Comment by williamwen42** [comment]
Are we ok with using `logging.getLevelName("CODE")` everywhere? This will return an int, assuming the dynamo logging module has run. Can't use a string right now since log_level is compared to an int in some places (not many though).

**Comment by ezyang** [comment]
Or alternately, why did we think a custom CODE log level was a good idea in the first place? Can we do it some other way?

**Comment by williamwen42** [comment]
Currently, WARNING is currently for graph breaks, INFO is for compilation status and DEBUG is for instruction traces. CODE logging used to go under INFO, but we wanted INFO to be less spammy. DEBUG also seemed too spammy for compiled functions + graphs, so we decided to create a new level for this.

**Comment by mlazos** [comment]
Can we alias all of the other log levels in the dynamo module as well? then they will all be in one place

**Comment by williamwen42** [comment]
Aliasing all of the other log levels doesn't solve the problem that the interfaces are different depending on whether you're in config.py (cannot use `torch._dynamo.logging` due to circular import - must use relative imports instead) or user code (can use `torch._dynamo.logging`). `logging.getLevelName("[LEVEL NAME]")` is the only solution I can think of that works for both config.py (assuming it does a relative import of dynamo logging.py) and user code.

**Comment by williamwen42** [comment]
We could get rid of the CODE level if we introduced a flag, something like
`log.log(torch._dynamo.logging.CODE, "...")` becomes
```python
if torch._dynamo.config.log_code:
    log.info("...")
```

**Comment by mlazos** [comment]
For context, Will and I chatted offline about this and decided the best UX for a new log_level is to patch it onto logging. The rationale is that we really want to be able to toggle showing only compiled functions, using a log level vs a string or flag is more configurable on a per stream basis, e.g. printing info logs to console while streaming the debug log elsewhere. Patching `logging` allows a consistent experience everywhere, in config, outside config

**Review by mlazos — APPROVED** [review]

**Pull request closed without merging**
