### PR TITLE
Logic to auto-categorize commits

### PR DESCRIPTION
**Pull request by anjali411**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #64929

Auto categorized 63% of the commits for PyTorch 1.10 release (2.2k out of 3.4k commits)

Differential Revision: [D33768760](https://our.internmc.facebook.com/intern/diff/D33768760)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
:+1:

**Review by malfet — APPROVED** [review]

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33768760).

**Comment by suo** [comment]
lint bork

**Comment by anjali411** [comment]
@suo landed a forward fix

**Pull request closed without merging**
