### PR TITLE
[don't merge] Use int64_t in THNN and THCUNN

### LINKED ISSUE #9404: Segmentation fault with large dilated Conv2d
## Issue description

Pytorch 0.4.0 gives a segmentation fault with dilated 2D convolutions over a specific size.

## Code example

import torch
import torch.nn as nn
model = nn.Conv2d(in_channels=64, out_channels=64, kernel_size=5, dilation=2)
model(torch.zeros([1, 64, 1166, 1166]))  # This runs
model(torch.zeros([1, 64, 1167, 1167]))  # This crashes

## System Info

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: TITAN X (Pascal)
GPU 2: Quadro K2200

Nvidia driver version: 390.59
cuDNN version: Probably one of the following:
/usr/local/cuda-7.5/lib64/libcudnn.so.5.1.10
/usr/local/cuda-7.5/lib64/libcudnn.so.5.1.3
/usr/local/cuda-7.5/lib64/libcudnn_static.a
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10
/usr/local/cuda-8.0/lib64/libcudnn_static.a

### PR DESCRIPTION
**Pull request by ssnl**
Fixes https://github.com/pytorch/pytorch/issues/9404 

I did a codemod. Likely there are something that should stay int.

### CODE REVIEW

**Comment by ezyang** [comment]
Did you just do a universal codemod from `int` to `int64_t` or were there some smarts?

...it's not building, so no smarts, it sounds like.

**Comment by SsnL** [comment]
No smarts. I only special cased ScalarConvert, so probably something is broken.

**Review by colesbury — CHANGES_REQUESTED** [review]
We shouldn't be blindly changing `int` to `int64_t`. What's the purpose of this change?

**Comment by SsnL** [comment]
@colesbury two instances of segfaults caused by overflow have been reported
lately.

**Comment by colesbury** [comment]
OK, we should fix those two segfaults, not change all `int`s to `int64_t`s. In CUDA, 64-bit arithmetic is substantially more expensive. In C++, `int` is special in a way that `int64_t` isn't. Most integral literals are `int`. The result of a bunch of arithmetic operations is `int`. (For example `uint8_t + uint8_t -> int`).

**Pull request closed without merging**
