### PR TITLE
refactor(add privateuseone floder in aten/src/ATen): add a PrivateUse…

### PR DESCRIPTION
**Pull request by ykddd**
Add a PrivateUse1 folder to contain all the feature adaptations for PrivateUse1 under Aten,For example GetGeneratorPrivate which is used for the three-party backend to register his own Generator implementation.This makes it easier for us to centrally manage these features, and it will increase the convenience of adaptation for different back-end manufacturers. For more info: https://github.com/pytorch/pytorch/issues/98073

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
lgtm!

**Comment by ykddd** [comment]
@weiwangmeta @bdhirsh Can there be some clearer reasons for me to improve? What does internal code refer to?

**Comment by weiwangmeta** [comment]
torch/csrc/Generator.cpp:7:10: fatal error: 'ATen/privateuseone/GeneratorForPrivateuseone.h' file not found
#include <ATen/privateuseone/GeneratorForPrivateuseone.h>

We encountered the above build issue.

**Comment by ykddd** [comment]
@weiwangmeta Can you provide more information? I have exported this header file, and it will appear in path-to-your-torch/include/ATen/privateuseone/ after installing torch. And I passed CI, can this internal code be added to CI for maintenance?

**Pull request closed without merging**
