### PR TITLE
Fix undefined tensor error in _copy_from_and_resize when fallback to cpu.

### PR DESCRIPTION
**Pull request by Shan19900305**
1) Add skip undefined tensor in cpu fallback when call _copy_from_and_resize;
2) Modify to_cpu function support optional tensor;
3) Add copy back to origin optional tensor when alias_info isWrite is true.

@ezyang @bdhirsh

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by ezyang** [comment]
Can you add a test for the behavior you are fixing?

**Comment by Shan19900305** [comment]
> Can you add a test for the behavior you are fixing?

@ezyang Hi, Yang. Test has been added.

**Comment by Shan19900305** [comment]
@ezyang Hi, Yang. Could you please review this code? thx.

**Review by ezyang — APPROVED** [review]

**Comment by Shan19900305** [comment]
> ## Merge failed
> **Reason**: 1 mandatory check(s) failed. The first few are:
> 
> * [pull / linux-focal-cuda12.1-py3.10-gcc9 / test (default, 2, 5, linux.4xlarge.nvidia.gpu)](https://github.com/pytorch/pytorch/actions/runs/9901226800/job/27593180415)
> 
> Dig deeper by [viewing the failures on hud](https://hud.pytorch.org/pytorch/pytorch/commit/ceb114ebb7906980f8d003dc103324e2619ee83a)
> 
> Details for Dev Infra team

This error is cuda test, and error message is:
PRINTING LOG FILE of functorch/test_rearrange 1/1 (test/test-reports/functorch.test_rearrange_1.1_e4ef94b0b3c34ebd_.log)
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/functorch/test_rearrange.py", line 35, in <module>
    from torch.testing._internal.common_utils import run_tests, TestCase
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1365, in <module>
    gb_available = torch.cuda.mem_get_info()[1] / 2 ** 30
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/cuda/memory.py", line 685, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Pull request closed without merging**
