### PR TITLE
[rnn/gru] : no batch dim

### PR DESCRIPTION
**Pull request by kshitij12345**
Reference #60585

Reland: https://github.com/pytorch/pytorch/pull/70442

### CODE REVIEW

**Review by jbschlosser — APPROVED** [review]
Thanks for the quick redo!

**Comment by suo** [comment]
may I suggest you rerun with ciflow/trunk to assess whether or not the jobs are successful

**Comment by jbschlosser** [comment]
> may I suggest you rerun with ciflow/trunk to assess whether or not the jobs are successful

he added ciflow/all - would that do the trick or should we re-run?

**Comment by suo** [comment]
oh yeah mb that's fine

**Pull request closed without merging**
