### PR TITLE
Correctly restore pybind11 error_already_set

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #93150
* __->__ #93238

We would handle py::error_already_set correctly from pybind11 bindings,
but not from our regular TH bindings, which meant that anything from
an inner pybind11 function call was getting unconditionally transformed
into a RuntimeError.  Not too many cases where we do this, but
PySymNodeImpl was one of them.

To test this, I need to raise a non-RuntimeError from a function which
is invoked from pybind11 and then propagated to a non-pybind11 call
site.  I introduce GuardOnDataDependentSymNode for expressly this
purpose (this is how I discovered the bug anyway.)

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by ezyang** [comment]
Update: It turns out I didn't need to add test, this behavior was being incorrectly tested in the test suite lol

**Review by albanD — APPROVED** [review]
Nice fix! Thanks!

**Pull request closed without merging**
