### PR TITLE
fixing csr addmm bug

### PR DESCRIPTION
**Pull request by aocsa**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#58768 fixing csr addmm bug**

Fixes gh-58757

This PR has a fix for CPU version of addmm op. Just for context, before this PR, only CSR @ vector was supported. I found out a minor bug in the addmm_out_sparse_csr_dense_cpu for the non MKL code which is solved in this PR.

Moreover, I discovered a limitation in the current MKL implementation. It only works well (acceptable tolerance for output error) with square matrices. I was looking in deep to this issue and I found out that it could be a limitation of the MKL API.

I used this [gist code](https://gist.github.com/aocsa/0606e833cd16a8bfb7d37a5fbb3a5b14) based on [this](https://github.com/baidu-research/DeepBench/blob/master/code/intel/spmm/spmm_bench.cpp) to test this behavior. 

As you can see there is not an acceptable output error (last column) when the matrices are squares and there is a not acceptable error when the matrices are not square. I reported the issue here: https://github.com/pytorch/pytorch/issues/58770

Looking forward to your comments.

Differential Revision: [D28629563](https://our.internmc.facebook.com/intern/diff/D28629563)

### CODE REVIEW

**Comment by aocsa** [comment]
I rebased this PR and polished a few things. As a gentle reminder, this PR is still waiting for a final review before merging, and I won't be able to work on this after this month.

**Comment by aocsa** [comment]
Note: This PR is blocking at the moment PR stack https://github.com/pytorch/pytorch/pull/57274

**Comment by malfet** [comment]
@aocsa can you please add link to the gist mentioned in PR description?

**Review by malfet — APPROVED** [review]
Thank you for the fix!

**Comment by aocsa** [comment]
> @aocsa can you please add link to the gist mentioned in PR description?

O missed while copying.  I used this [gist code](https://gist.github.com/aocsa/0606e833cd16a8bfb7d37a5fbb3a5b14) based on [this](https://github.com/baidu-research/DeepBench/blob/master/code/intel/spmm/spmm_bench.cpp). 

It's detailed here: https://github.com/pytorch/pytorch/issues/58770

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28629563).

**Comment by aocsa** [comment]
Just in case, I updated a little for MKL support on OSX env. Now all test are passing cc @malfet

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28629563).

**Comment by walterddr** [comment]
sorry for taking a look after merged --> seems like several skipped tests in #58666 should be reenabled? I am testing and will create a separate PR if feasible.

**Comment by aocsa** [comment]
> sorry for taking a look after merged --> seems like several skipped tests in #58666 should be reenabled? I am testing and will create a separate PR if feasible.

THanks @walterddr for notice this. However,  There are two PRs skipped at the moment. 

1.  https://github.com/pytorch/pytorch/blob/1fca1545d43090273512ac3a097277abd72d732e/test/test_sparse_csr.py#L87

This one is solved here: https://github.com/pytorch/pytorch/pull/57274

2.  https://github.com/pytorch/pytorch/blob/1fca1545d43090273512ac3a097277abd72d732e/test/test_sparse_csr.py#L195

It is the only one that should maintain the skip as it is related to MKL support.

**Pull request closed without merging**
