### PR TITLE
[quant][embdding qat] Add FX support for QAT EmbeddingBag

### PR DESCRIPTION
**Pull request by b-koopman**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #68121
* #68296
* #68852

Summary:

Add FX support for QAT EmbeddingBag operator, previously only eager mode support.

Test Plan:

pytest test/quantization/fx/test_quantize_fx.py  -v -k "test_qat_embeddingbag_linear"

Reviewers:

Subscribers:

Tasks:

Tags:

Add quantization mapping for QAT EmbeddingBag

Differential Revision: [D32318435](https://our.internmc.facebook.com/intern/diff/D32318435)

### CODE REVIEW

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32318435).

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32318435).

**Comment by b-koopman** [comment]
@b-koopman has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32318435).

**Review by supriyar — APPROVED** [review]
lgtm

**Pull request closed without merging**
