### PR TITLE
 remove sort requirement from pad-sequence

### PR DESCRIPTION
**Pull request by zou3519**
Picks up from #5974.

Removes the requirement that input sequences to pad_sequence have to be
sorted. Addressed the comments in the PR:
- Updated docstring for pad_sequence
- Remove sort requirement in pad_sequence test
- Test unsorted and sorted sequences in pad_sequence test

cc @alexholdenmiller @apaszke

### CODE REVIEW

**Comment by SsnL** [comment]
This messes up the ordering of input, which will be an issue if users are comparing it with some target. Since we don't return the indices, there won't be any way to order the target correctly.

**Review by ssnl — APPROVED** [review]
approving as this looks simple and reasonable. should be able to merge after test passes

**Review by soumith — APPROVED** [review]

**Pull request merged**
