### PR TITLE
schema_matching.cpp: improve error messages.

### PR DESCRIPTION
**Pull request by ZolotukhinM**

### CODE REVIEW

**Comment by ZolotukhinM** [comment]
Below is how the error messages changed.

**Example 1**:
```
cu = torch.jit.CompilationUnit('''
    def foo(x, y):
        return x.avd(y)
''')
```
Before:
```
RuntimeError:
unknown builtin op: aten::avd
Here are some suggestions:
	aten::svd
	aten::add
	aten::gcd
	aten::add_
	aten::abs
	aten::rand
	aten::std
	aten::mv
	aten::any
	aten::all
	aten::addr
	aten::ord
	aten::save
:

    def foo(x, y):
        return x.avd(y)
               ~~~~~ <--- HERE
```
After:
```
RuntimeError:
Unknown builtin op: aten::avd.
Here are some suggestions:
	aten::svd
	aten::add
	aten::gcd
	aten::add_
	aten::abs
	aten::rand
	aten::std
	aten::mv
	aten::any
	aten::all
	aten::addr
	aten::ord
	aten::save

The original call is:

    def foo(x, y):
        return x.avd(y)
               ~~~~~ <--- HERE
```

**Example 2**:
```
cu = torch.jit.CompilationUnit('''
    def foo(x, y):
        return torch.add(x,y,x,y)
''')
```
Before:
```
RuntimeError:
arguments for call are not valid:

  for operator aten::add(Tensor self, Tensor other, *, Scalar alpha=<default>) -> Tensor:
  expected at most 2 arguments but found 4 positional arguments.

      def foo(x, y):
          return torch.add(x,y,x,y)
                 ~~~~~~~~~ <--- HERE


  for operator aten::add(Tensor self, Scalar other, Scalar alpha=<default>) -> Tensor:
  expected at most 3 arguments but found 4 positional arguments.

      def foo(x, y):
          return torch.add(x,y,x,y)
                 ~~~~~~~~~ <--- HERE


  for operator aten::add(Tensor self, Tensor other, *, Scalar alpha=<default>, Tensor out) -> Tensor:
  argument out not provided.

      def foo(x, y):
          return torch.add(x,y,x,y)
                 ~~~~~~~~~ <--- HERE

  for operator aten::add(string a, string b) -> string:
  Expected a value of type str for argument 'a' but found Tensor

      def foo(x, y):
          return torch.add(x,y,x,y)
                           ~ <--- HERE

  for operator aten::add(int[] a, int[] b) -> int[]:
  Expected a value of type List[int] for argument 'a' but found Tensor

      def foo(x, y):
          return torch.add(x,y,x,y)
                           ~ <--- HERE

  for operator aten::add(float[] a, float[] b) -> float[]:
  Expected a value of type List[float] for argument 'a' but found Tensor

      def foo(x, y):
          return torch.add(x,y,x,y)
                           ~ <--- HERE

  for operator aten::add(bool[] a, bool[] b) -> bool[]:
  Expected a value of type List[bool] for argument 'a' but found Tensor

      def foo(x, y):
          return torch.add(x,y,x,y)
                           ~ <--- HERE

  for operator aten::add(Tensor[] a, Tensor[] b) -> Tensor[]:
  Expected a value of type List[Tensor] for argument 'a' but found Tensor

      def foo(x, y):
          return torch.add(x,y,x,y)
                           ~ <--- HERE

  for operator aten::add(t[] a, t[] b) -> t[]:
  Could not match type Tensor to List[t] in argument 'a': Cannot match List[t] to Tensor

      def foo(x, y):
          return torch.add(x,y,x,y)
                           ~ <--- HERE

  for operator aten::add(int a, int b) -> int:
  expected at most 2 arguments but found 4 positional arguments.

      def foo(x, y):
          return torch.add(x,y,x,y)
                 ~~~~~~~~~ <--- HERE


  for operator aten::add(float a, float b) -> float:
  expected at most 2 arguments but found 4 positional arguments.

      def foo(x, y):
          return torch.add(x,y,x,y)
                 ~~~~~~~~~ <--- HERE


  for operator aten::add(int a, float b) -> float:
  expected at most 2 arguments but found 4 positional arguments.

      def foo(x, y):
          return torch.add(x,y,x,y)
                 ~~~~~~~~~ <--- HERE


  for operator aten::add(float a, int b) -> float:
  expected at most 2 arguments but found 4 positional arguments.

      def foo(x, y):
          return torch.add(x,y,x,y)
                 ~~~~~~~~~ <--- HERE


  for operator add(float a, Tensor b) -> Tensor:
  expected at most 2 arguments but found 4 positional arguments.

      def foo(x, y):
          return torch.add(x,y,x,y)
                 ~~~~~~~~~ <--- HERE


  for operator add(int a, Tensor b) -> Tensor:
  expected at most 2 arguments but found 4 positional arguments.

      def foo(x, y):
          return torch.add(x,y,x,y)
                 ~~~~~~~~~ <--- HERE

for call at:

    def foo(x, y):
        return torch.add(x,y,x,y)
               ~~~~~~~~~ <--- HERE
```
After:
```
RuntimeError:
Arguments for call are not valid.
The following operator variants are available:

  aten::add(Tensor self, Tensor other, *, Scalar alpha=<default>) -> Tensor:
  Expected at most 2 arguments but found 4 positional arguments.

  aten::add(Tensor self, Scalar other, Scalar alpha=<default>) -> Tensor:
  Expected at most 3 arguments but found 4 positional arguments.

  aten::add(Tensor self, Tensor other, *, Scalar alpha=<default>, Tensor out) -> Tensor:
  Argument out not provided.

  aten::add(string a, string b) -> string:
  Expected a value of type str for argument 'a' but found Tensor.

  aten::add(int[] a, int[] b) -> int[]:
  Expected a value of type List[int] for argument 'a' but found Tensor.

  aten::add(float[] a, float[] b) -> float[]:
  Expected a value of type List[float] for argument 'a' but found Tensor.

  aten::add(bool[] a, bool[] b) -> bool[]:
  Expected a value of type List[bool] for argument 'a' but found Tensor.

  aten::add(Tensor[] a, Tensor[] b) -> Tensor[]:
  Expected a value of type List[Tensor] for argument 'a' but found Tensor.

  aten::add(t[] a, t[] b) -> t[]:
  Could not match type Tensor to List[t] in argument 'a': Cannot match List[t] to Tensor.

  aten::add(int a, int b) -> int:
  Expected at most 2 arguments but found 4 positional arguments.

  aten::add(float a, float b) -> float:
  Expected at most 2 arguments but found 4 positional arguments.

  aten::add(int a, float b) -> float:
  Expected at most 2 arguments but found 4 positional arguments.

  aten::add(float a, int b) -> float:
  Expected at most 2 arguments but found 4 positional arguments.

  add(float a, Tensor b) -> Tensor:
  Expected at most 2 arguments but found 4 positional arguments.

  add(int a, Tensor b) -> Tensor:
  Expected at most 2 arguments but found 4 positional arguments.

The original call is:

    def foo(x, y):
        return torch.add(x,y,x,y)
               ~~~~~~~~~ <--- HERE
```

**Review by suo — APPROVED** [review]
lgtm. I expect we have some tests that regex on error output, so you'll need to change those

**Comment by zdevito** [comment]
Another thing i think we can change: if this was a method invocation, we should only even consider builtins whose first argument matches. That way when you write `a + b` you don't see every thing in the system, just things with an `__add__` method on a's type.

**Comment by yf225** [comment]
This PR didn't pass CUDA tests in the CI and is breaking master. I am reverting.

**Pull request closed without merging**
