### PR TITLE
WIP: Allow reduce on empty tensor over non-empty dimension

### LINKED ISSUE #34907: max / min doesn't work on tensors with 0 elements
## 🐛 Bug

Current `min` / `max` implementation is too restrictive wrt tensors with zero elements.
Indeed, min/max reduction over an empty dimension should raise an error, as they don't have an identity, but if the dimension being reduced is not of size 0 (but the tensor has 0 elements), then it should work.

## To Reproduce

```python
a = torch.rand(0, 4)
print(a.max(1))
```
raises
```
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
```
while
```python
a = torch.rand(0, 4)
print(a.numpy().max(1))
```
returns
```
array([], dtype=float32)
```

---
PyTorch version `1.5.0.dev20200225`

cc @ezyang @gchanan @zou3519 @mruberry @rgommers @heitorschueroff

### PR DESCRIPTION
**Pull request by willwray**
Reviving PR #38238, fixes #34907.

Opening PR with the original commit to exercise CI.

### CODE REVIEW

**Comment by willwray** [comment]
Still WIP as there are two blocking issues:
1. `torch.mode` implementation doesn't handle reducing on non-zero dims of an empty tensor
2. cuda `gpu_reduce_kernel` asserts `numel() > 0` and doesn't handle `numel() == 0` case

Failing tests are disabled in the commit "WIP tmp disable test_reduction_empty fails"

**Comment by willwray** [comment]
New test fails are caused in `test_autograd.py` `test_kthvalue_scalar_*_cpu` and `test_median_scalar_*_cpu`
(`_cuda` test variants are PASSing, as is `test_median_scalar_cpu`)
due to an assertion in `maybe_wrap_dim` when called with `wrap_scalar=false`
when called from tensor `.size()` or `.stride()`...
Debugging...

**Comment by heitorschueroff** [comment]
@willwray Linking my PR (https://github.com/pytorch/pytorch/pull/45084) here because it introduces fixes for torch.median behavior on non-empty dimensions of empty tensors.

**Comment by willwray** [comment]
# Status of this WIP PR

This issue initially appeared to involve updating TORCH_CHECK assertions to no longer assert on non-empty dimensions.

As noted in a previous comment, the updated assertions mean that control flows through to reduction-function implementations, some of which don't yet handle non-empty dimensions:

1. torch.mode cpu implementation doesn't handle reducing on non-zero dims of an empty tensor
2. cuda gpu_reduce_kernel asserts numel() > 0 and doesn't handle numel() == 0 case

Heitor's comment points to his PR https://github.com/pytorch/pytorch/pull/45847 to update median and nanmedian functions.
This provides a guide to how to update the torch.mode cpu implementation and may help with the cuda kernel update.

## Notes

The TORCH_CHECK conditions are subtle - I tried to simplify as far as possible.

The amin, amax checks employ an algo & lambda, repeated twice but didn't seem worth factoring out
`std::all_of(dim.begin(),dim.end(),[&](int d){return self.sizes()[d] != 0;}`

The argmin, argmax checks are left as two separate checks, as in the previous PR.
Care has to be taken to guard the optional access - i.e. not to access the optional dim if it is not engaged, null-opt.
This code repetition should be factored out, either by template or by function.

### Tests

(may be failing Python lint)

As in the previous PR I implement a new `test_no_ident_reduction_on_emptytensor` test.
The test cases can consolidated with `test_reduction_empty`.
The recent `median`, `nanmedian` PR adds these tests as special cases -
once this PR is complete, all test cases can be done in two batches for 'operation does not have an identity' or has-identity.

**Comment by rgommers** [comment]
closing, superceded by gh-52565.

**Pull request closed without merging**
