### PR TITLE
[BE] Get rid of deprecation warnings in workflows (take 3)

### PR DESCRIPTION
**Pull request by malfet**
- Per [deprecation announcement](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) replace `echo "::set-output name="` with echo to `${GITHUB_OUTPUT}` as shown in following [example](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs#example-defining-outputs-for-a-job)
- Update `actions/setup-python` from `v2` to `v4` to get rid of deprecated node version warning
- Update `actions/checkout-python` from `v2` to `v3` (and `silent-checkout` branch as well)
- Update `retry` action to https://github.com/nick-fields/retry/commit/3e91a01664abd3c5cd539100d10d33b9c5b68482

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Review by izaitsevfb — APPROVED** [review]
LGTM

**Comment by malfet** [comment]
@pytorchbot revert -m "Regresses is_pr_labelled workflow" -c weird

One can not really test this workflow in PR

**Comment by malfet** [comment]
@pytorchbot revert -m "Regresses is_pr_labelled workflow again" -c weird

Going to skip it for the 3rd try, as nobody is looking at those anyway

**Pull request closed without merging**
