### PR TITLE
Enable FlashAttention on Windows

### PR DESCRIPTION
**Pull request by lw**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #131906

Let's just give this a try.

Reland of https://github.com/pytorch/pytorch/pull/131875.

### CODE REVIEW

**Review by drisspg — APPROVED** [review]

**Review by eqy — APPROVED** [review]
This may require changes to `fused_sdp_choice` in `test_transformers.py` as IIRC one of the cases assumes `SDPBackend.CUDNN_ATTENTION` will be used on Windows as FA was previously not enabled on Windows

**Comment by lw** [comment]
Temporarily incorporating https://github.com/pytorch/pytorch/pull/130443 (and triggering more CI jobs) to see if it helps with the OOMs we saw in https://github.com/pytorch/pytorch/issues/132042

**Comment by lw** [comment]
@eqy If you're talking about the `test_fused_sdp_choice` testcase, it passes without changes, because it relies on the `PLATFORM_SUPPORTS_FLASH_ATTENTION` flag, which I correctly updated in this PR.

**Comment by haampie** [comment]
Let me know if it makes sense to update the changes to `torch_cuda_flash_attention` in #130443 so it can be merged separately. For some reason CI is not running in that PR, so hard to find issues.

**Comment by umarbutler** [comment]
Can we keep this alive please?

**Comment by lw** [comment]
Unfortunately the status of this PR (last time I checked) is that building FlashAttention on Windows causes the official builder machines to OOM. There was a parallel PR that tried to solve that problem by limiting the number of parallel build jobs for FlashAttention but unfortunately this causes the Windows build jobs to take longer and ultimately to time out.

Thus I didn't see any solution to this problem (except getting beefier machines for the Windows builds).

**Pull request closed without merging**
