### PR TITLE
[reland] `_foreach_copy` with different src/dst dtypes

### PR DESCRIPTION
**Pull request by crcrpar**
Attempt to reland https://github.com/pytorch/pytorch/pull/121717.
The change is the array bounds check.

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
Could you explain why the bounds check is necessary for V100s?

**Comment by janeyx99** [comment]
importing to verify internally

**Comment by crcrpar** [comment]
> Could you explain why the bounds check is necessary for V100s?

I could cause IMA on Ampere and it's just ubiquitous in foreach fastpath, e.g. https://github.com/pytorch/pytorch/blob/87f7486df99bbd8c0187bc7bc7080d1a41af1f78/aten/src/ATen/native/cuda/ForeachFunctors.cuh#L79-L96

**Review by janeyx99 — APPROVED** [review]
ah

**Comment by janeyx99** [comment]
To clarify series of events for any readers: Verified internally with Nam that it no longer IMAs, merged through GH1 as that's the way to do it.

**Comment by malfet** [comment]
@pytorchbot revert -m "Perhaps it enabled it for different dtype, but broke for the same" -c nosignal

Here is a minimal reproducer
```python
import torch
x=[torch.randint(3, 333, (3,), device='cuda', dtype=torch.int32) for _ in range(4)]
torch._foreach_copy_(x[:2], x[2:])
```
or as one-liner
```
$ python3 -c "import torch;print(torch.__version__);x=[torch.randint(3, 333, (3,), device='cuda', dtype=torch.int32) for _ in range(4)];torch._foreach_copy_(x[:2], x[2:])"
2.4.0.dev20240416+cu121
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: "foreach_tensor_copy" not implemented for 'Int'
```

**Pull request closed without merging**
