### PR TITLE
[DO_NOT_MERGE] Test New TF Pin

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
This is to test the new TF Pin PyTorch/XLA is experimenting.

Test Plan:
CI.

### CODE REVIEW

**Comment by alanwaketan** [comment]
There is no signs that the CI is running... Anything else I need to do?

**Comment by miladm** [comment]
let's resolve the conflict...

**Comment by miladm** [comment]
I see one of the tests failing, but doesn't look like a PT/XLA issue. 
Perhaps @Krovatkin can confirm if we should worry about this failure?

**Comment by alanwaketan** [comment]
From hud.pytorch.org, it looks like that failure is caused by https://github.com/pytorch/pytorch/commit/a4d10342e98b0abb3286a3780617afe108328ac7. After this checkin, that particular bot is all red. And then after the revert https://github.com/pytorch/pytorch/commit/db4c6fe54fd043bb249657be4054252ca5f78b36, that particular bot turns green again.

**Review by miladm — APPROVED** [review]

**Comment by alanwaketan** [comment]
Closing this as the experiment shows positive results that we need.

**Pull request closed without merging**
