### PR TITLE
make funcs in reducer not be private

### PR DESCRIPTION
**Pull request by heidongxianhua**
Fixes #ISSUE_NUMBER
Make funcs and parameters in reducer not be private and make these as `virtual`, so it is easier to be inherited for custom device.
for custom device, we have some special operation in reducer, so we want to inherited `Reducer` to override these special funcs.

### CODE REVIEW

**Comment by heidongxianhua** [comment]
@ezyang  Hi sorry to borther you, could you take a look?

**Comment by ezyang** [comment]
Distributed team needs to take a look, but at first glance, I am skeptical, you are exposing a lot of internal surface area with these changes and it seems like too much.

**Comment by heidongxianhua** [comment]
> Distributed team needs to take a look, but at first glance, I am skeptical, you are exposing a lot of internal surface area with these changes and it seems like too much.

yes, I have make the unnessary funs as protected, and mark some funcs as virtual to be inheritable.

**Comment by kumpera** [comment]
I don't think this is the way to address DDP handling of devices that are neither CUDA nor CPU.

There are only a few mentions of CUDA in reducer.cpp and it rather makes sense to expand torch.device API to cover what reducer needs than expose a whole lot of code we rather keep internal.

**Pull request closed without merging**
