### PR TITLE
If a torch.* returns non-Tensor, make this unimplemented rather than assert.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89918

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by albanD — APPROVED** [review]

**Comment by ezyang** [comment]
Ugh this breaks shit WRYYYY

**Comment by albanD** [comment]
We have tests/wrapping code that expects the AssertionError and needs to be updated?

**Comment by ezyang** [comment]
no, it looks like dynamo is getting further now that we're triggering graph breaks and then stuff is breaking

**Comment by jansel** [comment]
IMO the root cause of this is the way dynamo gets its list of allowed functions (recursively crawl the PyTorch namespace).  This assert is mainly to fix gaps in the list of allowed functions. 

I'd really like to switch to something better, more similar to opinfos etc.  Or perhaps do some automated testing of the entire namespace.

My guess is the reason for the issue is we have already added a node the FX graph at this point, so we would need a checkpoint/rollback to get back to the prior graph.

**Pull request closed without merging**
