### PR TITLE
[onnx] Add mse_loss symbolic

### PR DESCRIPTION
**Pull request by shubhambhokare1**
Adds support for mse_loss operator

### CODE REVIEW

**Review by BowenBao — APPROVED** [review]
LGTM, have you considered adding mse_loss as function in onnx?

**Review by titaiwangms — APPROVED** [review]

**Review by abock — APPROVED** [review]

**Comment by titaiwangms** [comment]
I think this one having the same issue as I did https://github.com/pytorch/pytorch/pull/91731#issuecomment-1374313740

**Pull request closed without merging**
