### PR TITLE
Fix a minor bug about method generation.

### PR DESCRIPTION
**Pull request by fakeYan**
Fixes #ISSUE_NUMBER

when create a torch.device obj, like `x=torch.device("foo")`, the device index is None.

So in this scenario, we need to get the current device index again.

cc @albanD Could you take a look about my changes.

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Should the test be updated as well?

**Comment by fakeYan** [comment]
> Should the test be updated as well?

Yes, I will add test cases and make certain adjustments to the current test files

**Review by albanD — APPROVED** [review]
Thanks for the update to the tests.
I agree that we should definitely get into a better testing situation by have a proper fake device (that ends up calling cpu) that we can use. But we can do that in a follow up.

**Pull request closed without merging**
