### PR TITLE
Hipify torch sub module 1

### PR DESCRIPTION
**Pull request by bmedishe**
Fixes #ISSUE_NUMBER
This is reopening PR https://github.com/pytorch/pytorch/pull/74704. 
 Changes suggested in

### CODE REVIEW

**Comment by bmedishe** [comment]
@malfet @shintaro-iwasaki @xwang233

**Comment by jithunnair-amd** [comment]
@bmedishe looks like some conflict errors popped up

**Review by malfet — CHANGES_REQUESTED** [review]
Hmm, copying contents of `hipify` submodule into pytorch codebase defeats the purpose of submodule, isn't it? Can we instead publish it as say wheel and if pytorch as build with ROCm support make it an install dependency?

**Comment by jithunnair-amd** [comment]
@malfet That could be a good solution for this "develop" issue, but would we then publish a thin wrapper file in the `torch.utils.hipify` path in install path of PyTorch for backward-compatibility with other projects (extensions etc.) that rely on `torch.utils.hipify`, maybe with a deprecation plan?

**Pull request closed without merging**
