### PR TITLE
add strict mode to load_state_dict

### PR DESCRIPTION
**Pull request by alykhantejani**
Addresses the request in #1990

### CODE REVIEW

**Comment by apaszke** [comment]
There’s been a lot of PRs around this functionality and while we don’t really like it, I think it’s ok to add a strict argument (True by default), which if set to False allow the dicts to have arbitrary mismatches.

I know your solution is safer, but it probably won’t stop the flood of issues and PRs, and I don’t want to have 20 modes of loading :confused: If you want to implement that then please go ahead, otherwise I’ll send a PR sometime later

**Comment by alykhantejani** [comment]
@apaszke sure - I'll update this one and add a `strict` param.

**Comment by alykhantejani** [comment]
@apaszke Is the updated version more of what you had in mind?

**Review by apaszke — COMMENTED** [review]
Yes, that's exactly what I meant, except that you missed a `KeyError` that is raised for extra keys in loaded state dict (line 401 after your diff)

**Comment by alykhantejani** [comment]
@apaszke do we want to remove that check with strict=False?

In its current state you can delete keys from a loaded state dict and then load params in (i.e. for fine-tuning)

But I guess you may also want to define a new model (with a few extra layers) and then just transfer over any common layers? Yeah ok, I've convinced myself whilst writing this out - 1 sec I'll push an update

**Review by apaszke — APPROVED** [review]

**Comment by apaszke** [comment]
Thanks Aly!

**Pull request merged**
