### PR TITLE
[Inductor UT] Generalize device-bias code introduced from #134874 and

### LINKED ISSUE #136595: [Break XPU] Device bias code introduced from #134874: create CUDA tensor on XPU device.
### 🐛 Describe the bug

The test case `inductor/test_memory.py::TestOperatorReorderForPeakMemory::test_reorder_peak_memory
` run with HAS_GPU, but hard code 'cuda' device tensor. 
```
2024-09-24T14:16:59.2946914Z Traceback (most recent call last):
2024-09-24T14:16:59.2947432Z   File "/var/lib/jenkins/pytorch/test/inductor/test_memory.py", line 46, in setUp
2024-09-24T14:16:59.2947957Z     self.model = Foo().to("cuda")
2024-09-24T14:16:59.2948624Z   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1340, in to
2024-09-24T14:16:59.2949239Z     return self._apply(convert)
2024-09-24T14:16:59.2949917Z   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 927, in _apply
2024-09-24T14:16:59.2950539Z     param_applied = fn(param)
2024-09-24T14:16:59.2951210Z   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1326, in convert
2024-09-24T14:16:59.2951897Z     return t.to(
2024-09-24T14:16:59.2952533Z   File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/cuda/__init__.py", line 310, in _lazy_init
2024-09-24T14:16:59.2953247Z     raise AssertionError("Torch not compiled with CUDA enabled")
2024-09-24T14:16:59.2953751Z AssertionError: Torch not compiled with CUDA enabled
```

### Versions

PyTorch version: 2.5.0a0+git7da755b
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.4
Libc version: glibc-2.35

cc @gujinghui @EikanWang @fengyuan14 @guangyey

### PR DESCRIPTION
**Pull request by etaf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136596

[Inductor UT] Generalize device-bias code introduced from #134874 and fix unexpected success test cases.
Fix #136595
cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by etaf** [comment]
Current ciflow/xpu is blocked by the fix of #136280

**Review by EikanWang — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
