### PR TITLE
Small clean up of aten_op

### PR DESCRIPTION
**Pull request by li-roy**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#17530 Small clean up of aten_op**&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D14237931/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #17601 Store ScalarType and Backend instead of Type in TensorIterator&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D14274754/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #17785 Remove Type::elementSizeInBytes&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D14379074/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #17723 Store python default type as PyTensorType instead of at::Type&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D14351082/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #17786 Pass ScalarType separately from Type in python constructors&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D14379075/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #17792 Remove Type::ScalarType()&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D14381774/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #17603 Remove conversion operator from Type to TensorOptions&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D14276588/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #17787 Add ScalarType arg to Type::options()&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D14379076/)

Differential Revision: [D14237931](https://our.internmc.facebook.com/intern/diff/D14237931/)

### CODE REVIEW

**Comment by gchanan** [comment]
is the test failure legit?

**Comment by gchanan** [comment]
mind showing the generated code differences?

**Comment by li-roy** [comment]
current test failures don't seem to be related.

**Comment by li-roy** [comment]
really the only change in gen_aten_op.h are changes like these:

before:
```
      case 832: { // item
      
          run_op = [=] {
              auto self = peek(0, 1);
              auto inferred_type = &at::getType(self);
              auto the_result = self.item();
              assignTo(Output(0),*inferred_type, the_result);
              return true;
          };
```
after:
```
      case 832: { // item
      
          run_op = [=] {
              auto self = peek(0, 1);
              auto the_result = self.item();
              assignTo(Output(0),self.scalar_type(), the_result);
              return true;
          };
      } break;
```

full changes if you want to see them:
old: https://gist.github.com/li-roy/0f35ffa897dca7b11393980aa5bee668
new: https://gist.github.com/li-roy/7c832921df37197784fbca2b12360a34

**Review by gchanan — APPROVED** [review]

**Pull request closed without merging**
