### PR TITLE
Added directory check before saving in C++ API

### LINKED ISSUE #75177: [Libtorch C++] `torch::save` crash if the folder is not created
### 🐛 Describe the bug

example
```
int main(int argc, char* argv[]) {
    auto m = torch::nn::Linear(5, 5);
    torch::save(m, "./aaa/bbb.pt");
}
```
If the folder `aaa` does not exist then it will crash. The correct behavior should be logging error message or creating the folder.

### Versions

Libtorch 1.11.0 (for cuda 11.3)
MSVC2019

cc @ezyang @gchanan @zou3519 @jbschlosser @mruberry

### PR DESCRIPTION
**Pull request by vitrioil**
Fixes #75177

Couldn't find any utility method to get directory name in pytorch repo, hence creating a function for that.
Let me know if a new function is not needed.

I also referred [this](https://github.com/pytorch/pytorch/blob/master/c10/test/util/tempfile_test.cpp#L15) for directory check.

Also I am using TORCH_CHECK to show the error. This is highly verbose with the entire stack visible. Is there any alternative for the same so that it is easier to read? This could happen a frequently, so small and concise error would be more helpful here.

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
That looks good!
If would be great to have a test for this (especially for the windows part)

**Comment by vitrioil** [comment]
There are tests present for both the cases 1) when directory exists [here](https://github.com/pytorch/pytorch/blob/master/test/jit/test_save_load.py#L392) 2) when directory does not exist [here](https://github.com/pytorch/pytorch/blob/master/test/jit/test_save_load.py#L409). It should call the C++ load.

For windows do you mean we should compare the error message raised prints directory error?

**Comment by vitrioil** [comment]
Oh yes, correct, for windows we need C++ test and not python! I will add them.

**Comment by vitrioil** [comment]
Referred [this](https://github.com/pytorch/pytorch/blob/master/c10/test/util/exception_test.cpp#L13) for test, not sure if I added the test in the right place.

**Review by albanD — APPROVED** [review]
Perfect! Thanks for the test

**Pull request closed without merging**
