### PR TITLE
Add clang-tidy checks in torch/csrc/autograd

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by Skylion007** [comment]
Just wanted to double check, does this not cause issues locally after torchgen is run? I know the clang-tidy CI check doesn't run through the full compilation process to save time, (hence the protobuff excludes), I wanted to make sure we don't confuse people with local false positives.

**Comment by cyyever** [comment]
> Just wanted to double check, does this not cause issues locally after torchgen is run? I know the clang-tidy CI check doesn't run through the full compilation process to save time, (hence the protobuff excludes), I wanted to make sure we don't confuse people with local false positives.

I don't fully understand what do you mean by torchgen. But we are able to cover this folder because recently the lint Docker image was changed to include CUDA installation so that it no longer reports unrecognized CUDA headers.

**Review by Skylion007 — APPROVED** [review]
LGTM, we can always revert if it causes issues.

**Pull request closed without merging**
