### PR TITLE
Make bitwise_left_shift/right_shift scalar variants composite

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #74317

They are written in a totally generic way.  This makes meta
tensors work on them.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D34933406](https://our.internmc.facebook.com/intern/diff/D34933406)

### CODE REVIEW

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34933406).

**Comment by ezyang** [comment]
cc @asi1024

**Review by ngimel — APPROVED** [review]
Should we instead wrap scalars in python parser and remove c++ overloads (like we do for add/mul and friends)?

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34933406).

**Review by bdhirsh — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34933406).

**Pull request closed without merging**
