### PR TITLE
Remove setting coalesce to 0 in sparse transpose_

### PR DESCRIPTION
**Pull request by zou3519**
`coalesced` means that the sparse tensor's `indices` are all unique. 

Let's say we transpose a sparse tensor in dimensions `d0, d1`. Let's say each index is some `x_i = (y_1, y_2, ..., y_n)` where `n` is the total number of dimensions of the sparse tensor. Transposing the sparse tensor in place is equivalent to swapping `y_{d0}, y_{d1}` for all indices `x_i`. 

If all the indices were unique before, then they will be unique after. If they were non-unique before, they will be non-unique after. 

This change removes setting `coalesced` to 0 after every transpose. In practice it doesn't affect very much but it's good for correctness.

### Test Plan
run tests

### CODE REVIEW

**Comment by ezyang** [comment]
Nice catch!

**Comment by soumith** [comment]
should you also change THCSTensor ?

**Comment by colesbury** [comment]
Can you add a unit test for this behavior?

**Comment by kose-y** [comment]
This is incorrect. `indices` should not only be unique, but also be sorted in coalesced matrix for correct behavior of matrix multiplication. This raises a major issue when performing matrix multiplication with coalesced then transposed matrix. See https://github.com/pytorch/pytorch/issues/6219.

**Pull request merged**
