### PR TITLE
[easy][aotinductor] fix typos & add static typing

### PR DESCRIPTION
**Pull request by ColinPeppler**
```
// check all references
$ grep -rl 'cpp_kernel_overlad_name' *
ir.py
```

```
$ lintrunner --take MYPYINDUCTOR torch/_inductor/codegen/wrapper.py torch/_inductor/ir.py
ok No lint issues.
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by chenyang78 — APPROVED** [review]
LGTM. Thanks!

**Pull request closed without merging**
