### PR TITLE
[BE][CI] Rename .jenkins to .ci

### PR DESCRIPTION
**Pull request by janeyx99**
### Description
We've wanted to do this for a looong time. Let's eradicate confusion about what the .jenkins folder is and try to host our scripts in a more generic .ci folder.

Most changes are a find and replace EXCEPT
- deleted dirty.sh in both caffe2 and pytorch since it was not used anywhere
- modified CONTRIBUTING.md to be more updated

The next steps:
- rename jenkins user to pytorch-ci or something
- move scripts from .circleci to here (e.g., docker)

### Issue
We used to have an issue for this but it is so long ago that I could not find it.

### Testing
CI should not break.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Yes!

**Review by seemethere — APPROVED** [review]

**Comment by huydhn** [comment]
Unrelated: I'm observing this one to see if accept2ship label works. In my previous attempt ([82452](https://github.com/pytorch/pytorch/pull/82452)), the label might need to be added before the approval (bug?)

**Review by huydhn — APPROVED** [review]

**Comment by huydhn** [comment]
> This PR has been accepted with the accept2ship label. Attempting to merge now.
> 
> @pytorchbot merge -l

He he, this confirms that accept2ship needs to be there before someone clicks approve. It doesn't seem consistent to me, and should be fixed. Let me create an issue for this

**Pull request closed without merging**
