### PR TITLE
[BE] Add type annotation to eliminate_dead_code

### PR DESCRIPTION
**Pull request by marvin-kim**
Test Plan: CI

Reviewed By: evanleed

Differential Revision: D66887283

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
you'll need to figure out how to shut up the bc test lol

**Comment by Skylion007** [comment]
If you figure out how to fix silence the BC test, could you also fix the Implicit Optional RUF013 NOQA I wasn't able to change due to this BC breaking logic.

**Review by Skylion007 — APPROVED** [review]

**Comment by ezyang** [comment]
Oh you know what, this is easy, just edit the file that it is comparing against to have the new `-> bool` return.

**Comment by marvin-kim** [comment]
> Oh you know what, this is easy, just edit the file that it is comparing against to have the new `-> bool` return.

Sorry, I don't understand what this means and how I should do it. Can you elaborate?

**Comment by marvin-kim** [comment]
> > Oh you know what, this is easy, just edit the file that it is comparing against to have the new `-> bool` return.
> 
> Sorry, I don't understand what this means and how I should do it. Can you elaborate?

I think I understand what you mean. Let me try it.

**Comment by jeanschmidt** [comment]
created and started shipping the DK diff [D67026816](https://www.internalfb.com/diff/D67026816) reverting it internally. Lets wait and see if pytorchbot and shipit will handle this case nicely.

**Pull request closed without merging**
