### PR TITLE
Tune bsr_dense_addmm for int8 inputs on A100

### PR DESCRIPTION
**Pull request by pearu**
As in the title. The tuning is done for dimensions 1280 and 5120 that are used in Vit-H.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136088

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]

**Comment by amjames** [comment]
sev label has been removed from the issue that blocked merge so I'm going to rebase and retry.

**Pull request closed without merging**
