### PR TITLE
Set up aten/src/ATen/functorch directory; move some files there

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #84648
* #84642

This PR:
- sets up aten/src/ATen/functorch in PyTorch's build system
- Moves {BatchedTensorImpl.h, and BatchedTensorImpl.cpp}
there as a test.

Test Plan:
- functorch build and test should pass

Differential Revision: [D39315051](https://our.internmc.facebook.com/intern/diff/D39315051)

@diff-train-skip-merge

### CODE REVIEW

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39315051).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39315051).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39315051).

**Review by ezyang — APPROVED** [review]

**Comment by zou3519** [comment]
ios-12-5-1-x86-64 / build  seems to have succeeded in circleci, so I am not sure what the signal is saying: https://app.circleci.com/pipelines/github/pytorch/pytorch/561731/workflows/f125e14a-711b-4679-831d-7e7dc3279de5/jobs/17082747

**Comment by ezyang** [comment]
i'd ignore it

**Pull request closed without merging**
