### PR TITLE
Dirac init compatibility with group convolutions

### PR DESCRIPTION
**Pull request by assafshocher**
Initializing weights of group-conv with init.dirac_, and applying, previously resulted in an output that makes no sense:
```
x = torch.randn([1, 3, 3, 3])
print('input:\n', x)
conv_layer = torch.nn.Conv2d(3, 3, 3, padding=1, groups=3, bias=False)
torch.nn.init.dirac_(conv_layer.weight.data)
print('\noutput (before this PR):\n',conv_layer(x))


input:
 tensor([[[[ 0.5369, -1.1428,  0.1031],
          [ 0.4638, -0.0854, -0.6553],
          [ 0.8321, -2.5926, -0.3214]],

         [[-0.2289, -0.0895,  0.4407],
          [ 1.2309, -1.2096, -1.5216],
          [-0.1798,  1.1694,  0.3469]],

         [[ 0.1905,  0.8095,  0.5490],
          [-0.4525, -0.4284, -0.1141],
          [ 1.1857, -0.9246, -0.5119]]]])

output (before this PR):
 tensor([[[[ 0.5369, -1.1428,  0.1031],
          [ 0.4638, -0.0854, -0.6553],
          [ 0.8321, -2.5926, -0.3214]],

         [[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]],

         [[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]]], grad_fn=<MkldnnConvolutionBackward>)
````

This PR allows introducing groups to the initialization:
```
torch.nn.init.dirac_(conv_layer.weight.data, groups=3)
print('output (after this PR):\n', conv_layer(x))

output (after this PR):
 tensor([[[[ 0.5369, -1.1428,  0.1031],
          [ 0.4638, -0.0854, -0.6553],
          [ 0.8321, -2.5926, -0.3214]],

         [[-0.2289, -0.0895,  0.4407],
          [ 1.2309, -1.2096, -1.5216],
          [-0.1798,  1.1694,  0.3469]],

         [[ 0.1905,  0.8095,  0.5490],
          [-0.4525, -0.4284, -0.1141],
          [ 1.1857, -0.9246, -0.5119]]]], grad_fn=<MkldnnConvolutionBackward>)
``` 

When out_channels is different than input_channels, it does the natural thing which is applying identity in each group separately:

```
x = torch.randn([1, 2, 3, 3])
print('input:\n', x)
conv_layer = torch.nn.Conv2d(2, 4, 3, padding=1, groups=2, bias=False)
torch.nn.init.dirac_(conv_layer.weight.data, groups=2)
print('\noutput:\n', conv_layer(x))


input:
 tensor([[[[ 1.2205, -0.6608,  0.8640],
          [-0.5464,  1.1288,  1.4726],
          [-0.6693,  0.4000, -1.7613]],

         [[-0.8760, -0.8814, -0.4705],
          [ 0.6283, -0.5943,  0.6873],
          [-0.6852,  1.4723,  0.3325]]]])

output:
 tensor([[[[ 1.2205, -0.6608,  0.8640],
          [-0.5464,  1.1288,  1.4726],
          [-0.6693,  0.4000, -1.7613]],

         [[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]],

         [[-0.8760, -0.8814, -0.4705],
          [ 0.6283, -0.5943,  0.6873],
          [-0.6852,  1.4723,  0.3325]],

         [[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]]], grad_fn=<MkldnnConvolutionBackward>)
```

Argument 'groups' defaults to 1 so it is backward compatible.  

Tests are modified to include cases of with groups>1 but also contain groups=1 cases.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit a94f554b:


**None of the build failures appear to be your fault**.

* **1/1** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=5b321a098594693eca8408169f475cb334856655&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base 5b321a09 since Jan 27
  <details>
  <summary>
  Please rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  Since your merge base is older than `viable/strict`, run these commands:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=a94f554b9686869b5ef35a83c2c9808ca4d63105).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [pytorch_macos_10_13_py3_test](https://dr.pytorch.org/build-details.html?build_id=93237930) from Jan 27 until Jan 27



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by ezyang** [comment]
@vincentqb do you think you would be able to review this? (No is a fine answer)

**Review by vincentqb — CHANGES_REQUESTED** [review]
Couldn't you do the following instead?
```python
x = torch.randn([1, 3, 3, 3]) 
print('input:\n', x) 
conv_layer = torch.nn.Conv2d(3, 3, 3, padding=1, groups=1, bias=False) 
torch.nn.init.dirac_(conv_layer.weight)
print('\noutput (before this PR):\n',conv_layer(x))  
```

```
input:
 tensor([[[[-0.4437, -0.2448,  1.4811],
          [ 0.2103,  0.2234,  0.2437],
          [-2.6258,  0.2899, -0.1680]],

         [[-0.3531, -0.3139, -3.1256],
          [ 0.5868,  0.3861, -0.0573],
          [ 1.8914,  0.2475,  0.2421]],

         [[-0.8827,  0.4264, -0.4944],
          [ 1.8532,  0.0400,  1.4679],
          [ 1.8510,  2.3384,  0.8307]]]])

output (before this PR):
 tensor([[[[-0.4437, -0.2448,  1.4811],
          [ 0.2103,  0.2234,  0.2437],
          [-2.6258,  0.2899, -0.1680]],

         [[-0.3531, -0.3139, -3.1256],
          [ 0.5868,  0.3861, -0.0573],
          [ 1.8914,  0.2475,  0.2421]],

         [[-0.8827,  0.4264, -0.4944],
          [ 1.8532,  0.0400,  1.4679],
          [ 1.8510,  2.3384,  0.8307]]]], grad_fn=<MkldnnConvolutionBackward>)
```

I'm assuming the win is to do the identity by groups when `out_channels` is different from `input_channels`? But then this can be explicitly achieved by assigning with advanced indexing on a zero matrix of the final shape, no?

i.e. assign the sub tensor of
```
 tensor([[[[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]],

         [[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]],

         [[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]],

         [[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]]], grad_fn=<MkldnnConvolutionBackward>)
```
the values of
```
 tensor([[[[ 1.2205, -0.6608,  0.8640],
          [-0.5464,  1.1288,  1.4726],
          [-0.6693,  0.4000, -1.7613]],

         [[-0.8760, -0.8814, -0.4705],
          [ 0.6283, -0.5943,  0.6873],
          [-0.6852,  1.4723,  0.3325]]]])
```
to get
```
 tensor([[[[ 1.2205, -0.6608,  0.8640],
          [-0.5464,  1.1288,  1.4726],
          [-0.6693,  0.4000, -1.7613]],

         [[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]],

         [[-0.8760, -0.8814, -0.4705],
          [ 0.6283, -0.5943,  0.6873],
          [-0.6852,  1.4723,  0.3325]],

         [[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]]], grad_fn=<MkldnnConvolutionBackward>)
```

Moreover, if `torch.nn.init.dirac_` supports `groups`, should `torch.nn.init.*` also?

**Comment by assafshocher** [comment]
Your suggestions are valid if you wanted to do one time operation, but if you want to initialize a group conv layer, so changing back to groups=1 misses the point. Using indexing also. There is no problem copying a tensor but the point is initializing weights when using a group conv and do it consistently.
Moreover, currently what you get for a group conv initialized with Dirac doesn't make sense.
Reg init.*,  Other initializations don't suffer from this inconsistency, since they don't need to create a structure that is channel aware like a dirc matrix, they simply fill with numbers all the channels without cross-dependencies so I think Dirac is the only one requires group support.
Thanks.

**Review by vincentqb — APPROVED** [review]
> Your suggestions are valid if you wanted to do one time operation, but if you want to initialize a group conv layer, so changing back to groups=1 misses the point. Using indexing also. There is no problem copying a tensor but the point is initializing weights when using a group conv and do it consistently.
> Moreover, currently what you get for a group conv initialized with Dirac doesn't make sense.
> Reg init.*, Other initializations don't suffer from this inconsistency, since they don't need to create a structure that is channel aware like a dirc matrix, they simply fill with numbers all the channels without cross-dependencies so I think Dirac is the only one requires group support.

Sounds good, thanks!

**Comment by assafshocher** [comment]
@vincentqb 
Thanks,
I see that some tests are failing now (didn't before). should I do anything?

**Comment by vincentqb** [comment]
> @vincentqb
> Thanks,
> I see that some tests are failing now (didn't before). should I do anything?

None of the tests failing seem related. Landing.

**Pull request closed without merging**
