### PR TITLE
[PyTorch] Use real if constexpr behind macro in hot template

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#51368 [PyTorch] Use real if constexpr behind macro in hot template**
* #51367 [PyTorch] Debug-gate static_assert in KernelFunction::makeFromUnboxedFunctor
* #51319 [PyTorch] Remove reference_cast in make_boxed_from_unboxed_functor
* #51463 [PyTorch] Fix return value of IValue::to for Tensor/String
* #51315 [PyTorch][easy] Fix TODOs in CppFunction constructors
* #51313 [PyTorch] Reduce template expansion in call_functor_with_args_from_stack

This seems to noticably reduce build times, at least for
RegisterCPU.cpp. It makes sense that a compiler builtin would be
faster than simulating the same builtin with templates.

Identified with templight.

Differential Revision: [D26154964](https://our.internmc.facebook.com/intern/diff/D26154964/)

### CODE REVIEW

**Comment by bhosmer** [comment]
Do we have any data on the perf benefit from this? I can believe the lambdas in the polyfill API add overhead (or inline disruption risk, etc.) over the native feature, but given that we'll want to use this kind of surface-level #ifdef sparingly for readability's sake, it'd be good to establish a ballpark quantitative threshold for when it's justified.

**Review by bhosmer — APPROVED** [review]
Ah nvm my comment, saw the numbers in D26154964. To answer my own question, I'd say ~8% reduction in build time makes the surface-level splintering tolerable. 

(BTW, wasn't marked as a reviewer on GH and missed it on Phab, hence the delay, apologies)

**Comment by swolchok** [comment]
@bhosmer note that IIUC, Ubuntu 16.04 LTS is the blocker for raising our minimum C++ version to C++17. It hits end of life in April, so we should be able to move to C++17 and use `if constexpr` directly in May.

**Comment by bhosmer** [comment]
> @bhosmer note that IIUC, Ubuntu 16.04 LTS is the blocker for raising our minimum C++ version to C++17. It hits end of life in April, so we should be able to move to C++17 and use `if constexpr` directly in May.

Yup! @smessmer actually has the move to C++17 on his H1 roadmap, so you're right, it'll clean up pretty quick.

**Pull request closed without merging**
