### PR TITLE
fixed lgamma documentation error

### LINKED ISSUE #108527: torch.lgamma documentation error
### 📚 The doc issue

The documentation for the torch.lgamma function at https://pytorch.org/docs/stable/generated/torch.lgamma.html is inconsistent (and incorrect).

While the text description *correctly* says that torch.lgamma is the natural log of the absolute value of the gamma function of the input:

torch.lgamma(x) = ln(abs(gamma(x)))

the math expression *incorrectly* suggests that torch.lgamma is the natural log of the gamma function of the absolute value of the input:

torch.lgamma(x) = ln(gamma(abs(x)))

### Suggest a potential alternative/fix

Happy to fix by but I can't find the docstring for torch.lgamma that's used to produce the web docs. 

cc @svekars @carljparker

### PR DESCRIPTION
**Pull request by igm503**
Fixes #108527

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Comment by igm503** [comment]
@pytorchbog merge -i

**Pull request closed without merging**
