### PR TITLE
[LTC] Code-gen floor, frac, and trunc

### PR DESCRIPTION
**Pull request by ramiro050**
Summary:
This commit adds code-gen support for the floor op.

Test Plan:
test/cpp/build/test_ptltc --gtest_filter=AtenLtcTsTensorTest.TestFloor

### CODE REVIEW

**Comment by ramiro050** [comment]
Can't add reviewers, so tagging here instead: @wconstab @alanwaketan

**Review by alanwaketan — COMMENTED** [review]
You probably needs to deal with [this](https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/lazy_tensor_core/csrc/ops/ops.h#L151).

**Comment by wconstab** [comment]
yea in general we have been deleting as we go.  It's not always trivial though, since sometimes more than one nativefunction was using the same IR class or helper.  So, not a huge deal if something gets missed, just best effort.  But if you don't mind cleaning up others it's appreciated :)

**Review by wconstab — APPROVED** [review]

**Review by alanwaketan — APPROVED** [review]
LGTM. Thanks for improving code-gen!

**Pull request merged**
