### PR TITLE
CUDA 8 cleanup

### PR DESCRIPTION
**Pull request by zasdfgbnm**
CUDA 8 is no longer supported

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 600ec221:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=600ec22136f27ca1ee0bc555823fb8fe5a4a9a2f).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4193933) pytorch_xla_linux_xenial_py3_6_clang7_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=82918759) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=82918759))
<details>
<summary>
<code>Jan 09 23:59:00 Failed to generate ATEN bindings: ['/var/lib/jenkins/workspace/xla/scripts/generate_code.sh']</code>
</summary>

```
Jan 09 23:59:00 Generated 877 wrappers for /var/lib/jenkins/workspace/xla/scripts/../../torch/csrc/autograd/generated/RegistrationDeclarations.h 
Jan 09 23:59:00 AtenXlaType function missed override: Tensor& bitwise_or_out(Tensor& out, const Tensor& self, const Tensor& other); // bitwise_or_out(Tensor,Tensor,Tensor)->Tensor 
Jan 09 23:59:00 AtenXlaType function missed override: Tensor& bitwise_or_out(Tensor& out, const Tensor& self, Scalar other); // bitwise_or_out(Tensor,Tensor,Scalar)->Tensor 
Jan 09 23:59:00 Traceback (most recent call last): 
Jan 09 23:59:00   File "/var/lib/jenkins/workspace/xla/scripts/gen.py", line 1052, in <module> 
Jan 09 23:59:00     generate(args) 
Jan 09 23:59:00   File "/var/lib/jenkins/workspace/xla/scripts/gen.py", line 1022, in generate 
Jan 09 23:59:00     assert check_overrides(overrides, overridden) 
Jan 09 23:59:00 AssertionError 
Jan 09 23:59:00 Building torch_xla version: 0.8 
Jan 09 23:59:00 Failed to generate ATEN bindings: ['/var/lib/jenkins/workspace/xla/scripts/generate_code.sh'] 
Jan 09 23:59:00 =================== sccache compilation log =================== 
Jan 09 23:59:00 + cleanup 
Jan 09 23:59:00 + retcode=1 
Jan 09 23:59:00 + set +x 
Jan 09 23:59:00 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 09 23:59:00 Compile requests              2525 
Jan 09 23:59:00 Compile requests executed     2268 
Jan 09 23:59:00 Cache hits                    2256 
Jan 09 23:59:00 Cache misses                     0 
Jan 09 23:59:00 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by ezyang — APPROVED** [review]
Please build the docker images and show that they can be successfully built and deployed with this change, then we can merge this.

**Comment by ezyang** [comment]
@seemethere I wonder if we can use your deployment pipeline idea to also handle the idea of publishing docker images, so that we don't have to do manual edits to trigger builds of docker images.

**Comment by zasdfgbnm** [comment]
@ezyang I triggered a docker build in https://github.com/pytorch/pytorch/pull/32013/commits/dd3e172cd058062f8f817fca0b2e38d31789d7ba and revert it in https://github.com/pytorch/pytorch/pull/32013/commits/e6fc8dbf9101199f49d1839a3b40d61d312c7748. It seems to be working (there are two unrelated failures). This is ready to go now.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
