### PR TITLE
Fix non-existing parameters in docstrings

### PR DESCRIPTION
**Pull request by kit1980**
Continuation after https://github.com/pytorch/pytorch/pull/90163.

Here is a script I used to find all the non-existing arguments in the docstrings (the script can give false positives in presence of *args/**kwargs or decorators):

_Edit:_ 
I've realized that the indentation is wrong for the last `break` in the script, so the script only gives output for a function if the first docstring argument is wrong. I'll create a separate PR if I find more issues with corrected script.

``` python
import ast
import os
import docstring_parser

for root, dirs, files in os.walk('.'):
    for name in files:
        if root.startswith("./.git/") or root.startswith("./third_party/"):
            continue
        if name.endswith(".py"):
            full_name = os.path.join(root, name)
            with open(full_name, "r") as source:
                tree = ast.parse(source.read())
                for node in ast.walk(tree):
                    if isinstance(node, ast.FunctionDef):
                        all_node_args = node.args.args
                        if node.args.vararg is not None:
                            all_node_args.append(node.args.vararg)
                        if node.args.kwarg is not None:
                            all_node_args.append(node.args.kwarg)
                        if node.args.posonlyargs is not None:
                            all_node_args.extend(node.args.posonlyargs)
                        if node.args.kwonlyargs is not None:
                            all_node_args.extend(node.args.kwonlyargs)
                        args = [a.arg for a in all_node_args]
                        docstring = docstring_parser.parse(ast.get_docstring(node))
                        doc_args = [a.arg_name for a in docstring.params]
                        clean_doc_args = []
                        for a in doc_args:
                            clean_a = ""
                            for c in a.split()[0]:
                                if c.isalnum() or c == '_':
                                    clean_a += c
                            if clean_a:
                                clean_doc_args.append(clean_a)
                        doc_args = clean_doc_args
                        for a in doc_args:
                            if a not in args:
                                print(full_name, node.lineno, args, doc_args)
                            break

```

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by seemethere** [comment]
Should we add the script in our tools directory so we can utilize it later? We can also add it to test-infra if we think it'll be more generally useful

**Comment by kit1980** [comment]
> Should we add the script in our tools directory so we can utilize it later? We can also add it to test-infra if we think it'll be more generally useful

The script needs to be run manually because it gives false positives. Ideally flake8 via pydocstyle should flag the issues, but it doesn't have a check for this.

I think we can find this script if needed in the future from this PR.

**Comment by kit1980** [comment]
I've realized that the indentation is wrong for the last `break` in the script, in the script only gives output for a function if the first docstring argument is wrong. I'll create a separate PR if I find more issues with corrected script.

**Review by ZainRizvi — APPROVED** [review]

**Pull request closed without merging**
