### PR TITLE
(torch/elastic) add documentation clarifying that torchrun is a console script to torch.distributed.run

### LINKED ISSUE #73319: [docs] distributed docs still mention/recommend deprecated torch.distributed.launch
### 📚 The doc issue

https://pytorch.org/docs/master/distributed.html

should be changed in favor of distributed.run?

### Suggest a potential alternative/fix

_No response_

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

### PR DESCRIPTION
**Pull request by kiukchung**
Summary:
resolves https://github.com/pytorch/pytorch/issues/73319

Simply clarifies that `torchrun` is a console script that invokes `python -m torch.distributed.run`.

Test Plan: N/A doc change only, letting github CI validate that the docs build correctly.

Differential Revision: D34558538

### CODE REVIEW

**Comment by vadimkantorov** [comment]
What is `NUM_TRAINERS`? In academic environments often we don't know beforehand how many jobs will be run per node. Often someone will run a job taking 4 GPUs without knowing if other people take all 4 remanining GPUs in one job, or 2 jobs by 2 GPUs or no jobs at all for some time

**Comment by vadimkantorov** [comment]
A link in the docs to the github source code of `torchrun` would be awesome

**Comment by kiukchung** [comment]
> What is `NUM_TRAINERS`? In academic environments often we don't know beforehand how many jobs will be run per node. Often someone will run a job taking 4 GPUs without knowing if other people take all 4 remanining GPUs in one job, or 2 jobs by 2 GPUs or no jobs at all for some time

Its a placeholder env var that you pass to `--nproc_per_node` (the number of local workers to start for this particular job)

**Comment by kiukchung** [comment]
> A link in the docs to the github source code of `torchrun` would be awesome

done

**Comment by vadimkantorov** [comment]
> Its a placeholder env var that you pass to `--nproc_per_node` (the number of local workers to start for this particular job)

Is it mandatory? In practice the person running the first job may not know what other jobs will be run in the future on the same machine

**Comment by kiukchung** [comment]
> > Its a placeholder env var that you pass to `--nproc_per_node` (the number of local workers to start for this particular job)
> 
> Is it mandatory? In practice the person running the first job may not know what other jobs will be run in the future on the same machine

no its just a way to document that you can pass whatever integer you want to `--nproc_per_node` without having to hard code a specific number.

**Comment by vadimkantorov** [comment]
i think it'd better be specified that it's not mandatory (to have the simplest recipe for this most frequent scenario)

**Comment by vadimkantorov** [comment]
> done

hmm, seems this change is not pushed to the PR yet...

**Comment by kiukchung** [comment]
> A link in the docs to the github source code of `torchrun` would be awesome

done

> i think it'd better be specified explicitly that it's not mandatory (to have the simplest recipe for this most frequent scenario)

you need to specify `--nproc_per_node`, this tells the launcher how many "copies" of your trainer to launch (all the copies belong to a single process group, aka job)

**Comment by vadimkantorov** [comment]
Right, so in practice this is ~NGPUS, right?

**Comment by vadimkantorov** [comment]
So far I kind of understood that torchrun somehow runs torch.distributed.run script. Is it actually just a symlink? Or does it have more functionality? From this phrasing it is not clear: `is a console script to the main module torch.distributed.run`

**Comment by kiukchung** [comment]
> Right, so in practice this is ~NGPUS, right?

yes

**Comment by kiukchung** [comment]
> So far I kind of understood that torchrun somehow runs torch.distributed.run script. Is it actually just a symlink? Or does it have more functionality? From this phrasing it is not clear: `is a console script to the main module torch.distributed.run`

its literally called "console script" for standard python packaging: https://packaging.python.org/en/latest/specifications/entry-points/#use-for-scripts

**Comment by vadimkantorov** [comment]
I see! outside of python packaging, `console_script` doesn't have a very precise meaning and could contain extra functionality. For such docs IMO it doesn't hurt to be a bit more verbose, not everyone is well-versed in python packaging terminology

**Comment by kiukchung** [comment]
> I see! outside of python packaging, `console_script` doesn't have a very precise meaning and could contain extra functionality. For such docs IMO it doesn't hurt to be a bit more verbose, not everyone is well-versed in python packaging terminology...

yea, I added a hyperlink.

**Pull request closed without merging**
