### PR TITLE
Support linear/BN fusion

### PR DESCRIPTION
**Pull request by jaewoosong**
Current `fuse` function supports conv/BN fusions only. This commit is to support linear/BN fusion as well.

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by jaewoosong** [comment]
@ezyang Thank you for your review and approval. Would you please let @pytorchbot merge again? After you approved the PR and ordered @pytorchbot to merge, there were lint formatting and API guideline failures so I fixed them. The changes are irrelevant to the functionality and just for passing formatting and API guideline tests.

**Comment by jaewoosong** [comment]
@ezyang Thank you for your review and approval. Would you please command @pytorchbot to merge this PR again? After you commanded @pytorchbot to merge this, there were lint formatting and API guideline errors so I fixed them. Now the CI tests say this PR can be merged normally. The fixes I added are irrelevant to the functionality and just for fixing lint and API guideline errors.

**Comment by jaewoosong** [comment]
@ezyang Would you please merge this PR? This PR was already approved by you, and I fixed the lint and API guideline problems after your approval.

**Comment by jaewoosong** [comment]
I created a new PR at #141585. After it is merged, this PR will be closed.

**Pull request closed without merging**
