### PR TITLE
To add hipify_torch as a submodule in pytorch/third_party 

### PR DESCRIPTION
**Pull request by bmedishe**
`hipify_torch` as a submodule in `pytorch/third_party`

### CODE REVIEW

**Comment by pruthvistony** [comment]
@bmedishe ,
Can you please check if https://github.com/pytorch/pytorch/pull/76720 needs to be updated in hipify-torch repo.

**Comment by bmedishe** [comment]
> @bmedishe , Can you please check if #76720 needs to be updated in hipify-torch repo.
Yes  @pruthvistony :  https://github.com/pytorch/pytorch/pull/74704/commits/b8ddfda43b142d2927b9ba78cd306fcc180a68e0

**Review by jeffdaily — APPROVED** [review]

**Review by malfet — APPROVED** [review]
Looks good to me, need to import and make sure it will work internally

**Comment by pruthvistony** [comment]
@malfet , 
Please let us know if this PR is working on your internally system. If good can we merge this PR.

**Comment by pruthvistony** [comment]
The internal builds are breaking, since it relys on older hipify structure.

**Comment by bmedishe** [comment]
> Looks good to me, need to import and make sure it will work internally

@malfet , Is the PR working internally for you  ?

**Comment by bmedishe** [comment]
@malfet If this PR is working internally could we merge it upstream?

**Comment by bmedishe** [comment]
> @malfet has imported this pull request. If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36294553).

@malfet I see that you imported this pull request , could you kindly confirm if this PR could be merged ?

**Comment by malfet** [comment]
> @malfet I see that you imported this pull request , could you kindly confirm if this PR could be merged ?

@bmedishe not, as it still breaks internal build system with 
```
    from .hipify import hipify_python  # type: ignore[import]
ModuleNotFoundError: No module named 'torch.utils.hipify'
```

Which raises a very valid question: aren't interface provided via `torch.utils.hipify` is part of public API and must be preserved going forward (even if implementation is now provided eslewhere)

**Comment by jithunnair-amd** [comment]
cc @shintaro-iwasaki Can you please take a look?

**Comment by xwang233** [comment]
@malfet I can't build torchvision after this PR, got

```python
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
      from torch.utils.cpp_extension import BuildExtension, CppExtension, CUDAExtension, CUDA_HOME
    File "/opt/pytorch/pytorch/torch/utils/cpp_extension.py", line 19, in <module>
      from .hipify import hipify_python  # type: ignore[import]
  ModuleNotFoundError: No module named 'torch.utils.hipify'
```

63c0bcf887736810dd2ca6e8b671439c67e58ed6
pytorch/vision@28557e0cfe9113a5285330542264f03e4ba74535

**Comment by shintaro-iwasaki** [comment]
Maybe it was reflected to the GitHub side. I am sorry.

@jithunnair-amd when you have a chance to create a PR next time, could add the following in `cpp_extenstion.py`?

According to @xwang233's report, the following should address the issue.
```
try:
    from .hipify import hipify_python  # type: ignore[import]
    from .hipify.hipify_python import GeneratedFileCleaner  # type: ignore[import]
except ModuleNotFoundError:
    hipify_python = None  # type: ignore[assignment]
    GeneratedFileCleaner = None  # type: ignore[assignment]
```

**Comment by bmedishe** [comment]
> Maybe it was reflected to the GitHub side. I am sorry.
> 
> @jithunnair-amd when you have a chance to create a PR next time, could add the following in `cpp_extenstion.py`?
> 
> According to @xwang233's report, the following should address the issue.
> 
> ```python
> try:
>     from .hipify import hipify_python  # type: ignore[import]
>     from .hipify.hipify_python import GeneratedFileCleaner  # type: ignore[import]
> except ModuleNotFoundError:
>     hipify_python = None  # type: ignore[assignment]
>     GeneratedFileCleaner = None  # type: ignore[assignment]
> ```

@shintaro-iwasaki  pushed the above suggested change

**Comment by bmedishe** [comment]
> @malfet I can't build torchvision after this PR, got
> 
> ```python
> Traceback (most recent call last):
>   File "setup.py", line 12, in <module>
>       from torch.utils.cpp_extension import BuildExtension, CppExtension, CUDAExtension, CUDA_HOME
>     File "/opt/pytorch/pytorch/torch/utils/cpp_extension.py", line 19, in <module>
>       from .hipify import hipify_python  # type: ignore[import]
>   ModuleNotFoundError: No module named 'torch.utils.hipify'
> ```
> 
> [63c0bcf](https://github.com/pytorch/pytorch/commit/63c0bcf887736810dd2ca6e8b671439c67e58ed6) [pytorch/vision@28557e0](https://github.com/pytorch/vision/commit/28557e0cfe9113a5285330542264f03e4ba74535)

@xwang233  could you kindly mention reproduction steps for this error ? I could build torchvision after building pytorch from the above branch

**Comment by jithunnair-amd** [comment]
@xwang233 I think the key here is that the way you are building torchvision, it is trying to pick up pytorch from the source code path, instead of the install path. In this PR, we have ensured that `torch.utils.hipify` continues to be available in the PyTorch install path even though that path is not available in the source code anymore (hence the lint comment `# type: ignore[import] # noqa: F401`). We tested for situations where a PyTorch extension is built in an environment where PyTorch is already installed. Is that different from your use-case?

**Comment by xwang233** [comment]
We use `python setup.py develop` for pytorch and torchvision

**Comment by malfet** [comment]
> @shintaro-iwasaki @xwang233 I think the key here is that the way you are building torchvision, it is trying to pick up pytorch from the source code path (`File "/opt/pytorch/pytorch/torch/utils/cpp_extension.py"`), instead of the install path.

Hmm, does it mean that `cd ~/git/pytorch/pytorch; python3 setup.py develop; cd ~/git/pytorch/vision; python3 setup.py develop` would no longer works?

**Comment by jithunnair-amd** [comment]
@shintaro-iwasaki Thank you for the suggestion. However, that won't work when the code tries to call `hipify_python.hipify`:
```
Traceback (most recent call last):
  File "setup.py", line 523, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 221, in get_extensions
    extra_compile_args=extra_compile_args,
  File "/var/lib/jenkins/pytorch/torch/utils/cpp_extension.py", line 1052, in CUDAExtension
    hipify_result = hipify_python.hipify(
AttributeError: 'NoneType' object has no attribute 'hipify'
```

> Hmm, does it mean that cd ~/git/pytorch/pytorch; python3 setup.py develop; cd ~/git/pytorch/vision; python3 setup.py develop would no longer works?
@malfet Yes. We are working on an alternate PR so that the develop path would also work. Please review it here: https://github.com/pytorch/pytorch/pull/80136/commits/fbc724b700eac9fd7c574902a4208b6e4f9d764d
cc @xwang233

**Pull request closed without merging**
