### PR TITLE
Temporarily disable ROCm tests

### PR DESCRIPTION
**Pull request by kit1980**
There is an ongoing maintenance and everything fails.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Review by atalman — APPROVED** [review]

**Review by clee2000 — APPROVED** [review]
i believe there are also some periodic rocm jobs, do we want to disable those too?

**Comment by kit1980** [comment]
> i believe there are also some periodic rocm jobs, do we want to disable those too?

Probably, looking.

**Review by malfet — APPROVED** [review]

**Comment by weiwangmeta** [comment]
How about pull jobs?

**Comment by kit1980** [comment]
> How about pull jobs?

We technically have a pull ROCm workflow, but it's always skipped.

**Comment by kit1980** [comment]
> > How about pull jobs?
> 
> We technically have a pull ROCm workflow, but it's always skipped.

Actually it apparently runs on PRs, need to disable it too.

**Comment by kit1980** [comment]
> Actually it apparently runs on PRs, need to disable it too.

Turns out we only do builds for rocm on pull, not tests. No need to disable as builds don't use rocm machines.

**Pull request closed without merging**
