### PR TITLE
[ONNX] Renaming scales parameter for interpolate

### PR DESCRIPTION
**Pull request by BowenBao**
PR separated from https://github.com/pytorch/pytorch/pull/31274.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit f9a4367f:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=f9a4367f24451c10462e5b520a3ef1687d137730).

### :detective: 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4040800) pytorch_linux_backward_compatibility_check_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=78503992) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=78503992))
<details>
<summary>
<code>Dec 20 23:06:04 The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not.</code>
</summary>

```
Dec 20 23:06:04 processing existing schema:  aten::bitwise_xor.Scalar_out(Tensor self, Scalar other, *, Tensor(a!) out) -> (Tensor(a!)) 
Dec 20 23:06:04 processing existing schema:  aten::bitwise_xor.Tensor(Tensor self, Tensor other) -> (Tensor) 
Dec 20 23:06:04 processing existing schema:  aten::bitwise_xor.Scalar(Tensor self, Scalar other) -> (Tensor) 
Dec 20 23:06:04 processing existing schema:  aten::sin_(Tensor(a!) self) -> (Tensor(a!)) 
Dec 20 23:06:04 processing existing schema:  aten::upsample_linear1d_backward(Tensor grad_output, int[1] output_size, int[3] input_size, bool align_corners, float scales_1=-1.) -> (Tensor) 
Dec 20 23:06:04 Can NOT find backward compatible schemas after changes for schema aten::upsample_linear1d_backward(Tensor grad_output, int[1] output_size, int[3] input_size, bool align_corners, float scales_1=-1.) -> (Tensor) from the following candidates: 
Dec 20 23:06:04 [ 
Dec 20 23:06:04 aten::upsample_linear1d_backward(Tensor grad_output, int[1] output_size, int[3] input_size, bool align_corners, float scales=-1.) -> (Tensor) 
Dec 20 23:06:04 	aten::upsample_linear1d_backward.grad_input(Tensor grad_output, int[1] output_size, int[3] input_size, bool align_corners, float scales=-1., *, Tensor(a!) grad_input) -> (Tensor(a!)) 
Dec 20 23:06:04 ] 
Dec 20 23:06:04 The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not. 
Dec 20 23:06:04 + cleanup 
Dec 20 23:06:04 + retcode=1 
Dec 20 23:06:04 + set +x 
Dec 20 23:06:04 =================== sccache compilation log =================== 
Dec 20 23:06:04 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 20 23:06:04 Compile requests                 0 
Dec 20 23:06:04 Compile requests executed        0 
Dec 20 23:06:04 Cache hits                       0 
Dec 20 23:06:04 Cache misses                     0 
Dec 20 23:06:04 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by gchanan** [comment]
Can you grep for "use_scale_factor" and change it to `recompute_scales` (I believe this is what @lara-hdr and I agreed on).

Also there's still a use of scales_1 and scales_2 in torch/onnx/symbolic_caffe2.py.

**Comment by BowenBao** [comment]
> Can you grep for "use_scale_factor" and change it to `recompute_scales` (I believe this is what @lara-hdr and I agreed on).
> 
> Also there's still a use of scales_1 and scales_2 in torch/onnx/symbolic_caffe2.py.

Done

**Comment by gchanan** [comment]
@fmassa has argued for recompute_scale_factor, changing to that.

**Review by houseroad — APPROVED** [review]
Looks good, thanks!

Please add "upsample_" to the whitelist in test/backward_compatibility/check_backward_compatibility.py, so bc check will pass.

**Comment by gchanan** [comment]
@dlibenzi looks like this is breaking the XLA build -- perhaps because the type of the upsample operators changed from "double" to "optional<double>" (in C++).

**Comment by dlibenzi** [comment]
> @dlibenzi looks like this is breaking the XLA build -- perhaps because the type of the upsample operators changed from "double" to "optional" (in C++).

Thanks @gchanan ... will take a look!

**Comment by dlibenzi** [comment]
> > @dlibenzi looks like this is breaking the XLA build -- perhaps because the type of the upsample operators changed from "double" to "optional" (in C++).
> 
> Thanks @gchanan ... will take a look!

I have this tentative: https://github.com/pytorch/xla/pull/1499

I guess the fix should be easy anyway, so you can go in with this PR and ping us when you do, so we can rebase the fix.

**Comment by mrshenli** [comment]
Looks like this PR breaks `pytorch_linux_backward_compatibility_check_test` and `pytorch_xla_linux_xenial_py3_6_clang7_build`

https://app.circleci.com/jobs/github/pytorch/pytorch/4100103
https://app.circleci.com/jobs/github/pytorch/pytorch/4099980

I am reverting, please resubmit after fix. Thanks!

cc @gchanan @houseroad

**Comment by dlibenzi** [comment]
I have just merged the fix in the pytorch/xla repo.
We should be green now.

**Comment by dlibenzi** [comment]
https://github.com/pytorch/xla/pull/1499

**Comment by houseroad** [comment]
Yes, I have opened https://github.com/pytorch/pytorch/pull/31786 to fix bc check.

Right now, I am checking when we introduce _test_optional_float op

**Comment by mrshenli** [comment]
Oh, great! then I won't revert, thanks!

**Pull request closed without merging**
