### PR TITLE
Remove deprecated torch.matrix_rank

### PR DESCRIPTION
**Pull request by IvanYashchuk**
The time has come to remove deprecated linear algebra related functions. This PR removes `torch.matrix_rank`.

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

### CODE REVIEW

**Review by lezcano — APPROVED** [review]

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
@IvanYashchuk I think this can be merged now. Feel free to merge the usual way when you ready.

**Comment by kit1980** [comment]
Looks like this needs manual rebase.

**Pull request closed without merging**
