### PR TITLE
[aoti] Add warning to ask users to switch to new API

### PR DESCRIPTION
**Pull request by angelayi**
Instead of the following:
```
so_path = torch._export.aot_compile(...)
torch._export.aot_load(so_path)
```

The recommended path is to:
```
ep = torch.export.export(...)
pt2_path = torch._inductor.aoti_compile_and_package(ep, ...)
torch._inductor.package.load_package(pt2_path)
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by desertfire** [comment]
As we discussed offline, let's add a load API to `torch/_inductor/__init__.py`

**Review by desertfire — APPROVED** [review]

**Comment by bhack** [comment]
@angelayi Does this means that also `export_for_inference` is deprecated?

**Pull request closed without merging**
