### PR TITLE
Graphbreak when creating a map with unsupported keys

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #116460
* #116459

As per title. With this, https://github.com/pytorch/pytorch/issues/93697
does not choke, but spits out many of these:
```
[ERROR] Name: "L['self']"
[ERROR]     Source: local
[ERROR]     Create Function: NN_MODULE
[ERROR]     Guard Types: ['ID_MATCH']
[ERROR]     Code List: ["___check_obj_id(L['self'], 139962171127504)"]
[ERROR]     Object Weakref: <weakref at 0x7f4b72f7c9a0; to
'ActorCriticPolicy' at 0x7f4b7b7df6d0>
[ERROR]     Guarded Class Weakref: <weakref at 0x7f4afbd08b30; to
'ABCMeta' at 0x56463a727840 (ActorCriticPolicy)>
[ERROR] Created at:
[ERROR]   File
"/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builder.py",
line 248, in __call__
[ERROR]     vt = self._wrap(value)
[ERROR]   File
"/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builder.py",
line 474, in _wrap
[ERROR]     return self.wrap_module(value)
[ERROR]   File
"/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builder.py",
line 941, in wrap_module
[ERROR]     return self.tx.output.register_attr_or_module(
[ERROR]   File
"/home/lezcano/git/pytorch/pytorch/torch/_dynamo/output_graph.py", line
735, in register_attr_or_module
[ERROR]     install_guard(source.make_guard(GuardBuilder.NN_MODULE))
[ERROR] Error while creating guard:
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by davidmerwin** [comment]
> Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
> 
> * **->** [Graphbreak when creating a map with unsupported keys #116460](https://github.com/pytorch/pytorch/pull/116460)
> * [[dynamo] Fix np.issubdtype #116459](https://github.com/pytorch/pytorch/pull/116459)
> 
> As per title. With this, #93697 does not choke, but spits out many of these:
> 
> ```
> [ERROR] Name: "L['self']"
> [ERROR]     Source: local
> [ERROR]     Create Function: NN_MODULE
> [ERROR]     Guard Types: ['ID_MATCH']
> [ERROR]     Code List: ["___check_obj_id(L['self'], 139962171127504)"]
> [ERROR]     Object Weakref: <weakref at 0x7f4b72f7c9a0; to
> 'ActorCriticPolicy' at 0x7f4b7b7df6d0>
> [ERROR]     Guarded Class Weakref: <weakref at 0x7f4afbd08b30; to
> 'ABCMeta' at 0x56463a727840 (ActorCriticPolicy)>
> [ERROR] Created at:
> [ERROR]   File
> "/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builder.py",
> line 248, in __call__
> [ERROR]     vt = self._wrap(value)
> [ERROR]   File
> "/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builder.py",
> line 474, in _wrap
> [ERROR]     return self.wrap_module(value)
> [ERROR]   File
> "/home/lezcano/git/pytorch/pytorch/torch/_dynamo/variables/builder.py",
> line 941, in wrap_module
> [ERROR]     return self.tx.output.register_attr_or_module(
> [ERROR]   File
> "/home/lezcano/git/pytorch/pytorch/torch/_dynamo/output_graph.py", line
> 735, in register_attr_or_module
> [ERROR]     install_guard(source.make_guard(GuardBuilder.NN_MODULE))
> [ERROR] Error while creating guard:
> ```
> 
> cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

@pytorchmergebot @pytorchbot @pytorchupdatebot  #72643 #116460

**Pull request closed without merging**
