### PR TITLE
Implementation of the Fisher-Snedecor Distribution

### LINKED ISSUE #87: Implement F-distribution

### PR DESCRIPTION
**Pull request by vishwakftw**
This closes https://github.com/probtorch/pytorch/issues/87. Math checked and approved by @fritzo 

cc: @apaszke

### CODE REVIEW

**Review by apaszke — COMMENTED** [review]
@fritzo has anyone reviewed the math on this one?

**Comment by fritzo** [comment]
@apaszke I reviewed the math as follows:
- checked the sampler math for correctness
- checked the `.log_prob()` math for PyTorch usage
- ensured that unit tests tested agreement between this `.log_prob()` and Scipy's implementation.

**Comment by apaszke** [comment]
Isn't this still missing some tests (e.g. some entries in the "examples" dict). @alicanb's Geometric PR seems to have more cases checked

**Comment by fritzo** [comment]
@apaszke you're right, this needs test entries in `EXAMPLES`.

**Comment by fritzo** [comment]
Hi @vishwakftw to help us remember to add all new distributions to EXAMPLES, could you add the following test to tests/test_distributions.py in this PR?
```py
class TestDistributions(TestCase):
    ...
    def test_has_examples(self):
        distributions_with_examples = set(e.Dist for e in EXAMPLES)
        for name, Dist in globals().items():
            if isinstance(Dist, type) and issubclass(Dist, Distribution) and Dist is not Distribution:
                self.assertIn(Dist, distributions_with_examples,
                    "Please add {} to the EXAMPLES list in tests/test_distributions.py".format(Dist.__name__))
```
You'll also need to `from torch.distributions import Distribution`.

**Comment by vishwakftw** [comment]
@fritzo and @apaszke , I had a test case for `FisherSnedecor` in the EXAMPLES, but removed it thinking that the entropy tests would fail if I had it there. I just came to realize the `try..except` block there for `NotImplementedError` exceptions. Sorry about that.

**Review by apaszke — APPROVED** [review]

**Pull request merged**
