### PR TITLE
Add diagonal_copy to torch/_decomp/__init__.py

### LINKED ISSUE #117349: The diag should be dispatched to core IR for matrix input
### 🐛 Describe the bug

When trying to execute diag on matrix input it is currently dispatched to diagonal_copy which is not core IR.
```python
import torch
from torch._dynamo.backends.common import aot_autograd
from torch._decomp import core_aten_decompositions

def inner_compiler(fx_module: torch.fx.GraphModule, example_inputs):
    print(fx_module.code)
    return fx_module

aot_backend = aot_autograd(fw_compiler=inner_compiler, decompositions=core_aten_decompositions())

def fn(i1, i2):
    return torch.diag(i1, i2)
torch._dynamo.reset()
c = torch.compile(fn, backend=aot_backend)
x = torch.rand((8,8), dtype=torch.float)
y = 0
c(x, y)
```

The resut is:
```python
def forward(self, arg0_1):
    diagonal_copy = torch.ops.aten.diagonal_copy.default(arg0_1);  arg0_1 = None
    return (diagonal_copy,)
```

### Error logs

_No response_

### Minified repro

_No response_

### Versions

I executed this on Colab
torch.version = 2.1.0+cu121

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

### PR DESCRIPTION
**Pull request by LJ-underdog**
Fixes https://github.com/pytorch/pytorch/issues/117349

### CODE REVIEW

**Comment by intellinjun** [comment]
> @cpuhrsch It looks like we need to update the expert file HasDecompTest.test_aten_core_operators.expect which is used for testing.

But I don't have permission to change this file

**Comment by intellinjun** [comment]
@angelayi @masnesral

**Review by masnesral — APPROVED** [review]

**Comment by masnesral** [comment]
> But I don't have permission to change this file

Sorry - What does it mean? You can't add it to this PR?

**Review by masnesral — CHANGES_REQUESTED** [review]
I guess I shouldn't accept until we have the tests passing.

**Comment by intellinjun** [comment]
> I guess I shouldn't accept until we have the tests passing.

I'll fix those tests.

**Comment by intellinjun** [comment]
> I guess I shouldn't accept until we have the tests passing.

The problem with test has been fixed

**Review by masnesral — APPROVED** [review]

**Pull request closed without merging**
