### PR TITLE
Implement a generic function scheduler

### PR DESCRIPTION
**Pull request by joaotgouveia**
Implements the generic function scheduler mentioned in #37529.

### CODE REVIEW

**Comment by joaotgouveia** [comment]
Hi @rohan-varma , did you have time to review our PR? Is there anything we should change? Thanks in advance

**Comment by joaotgouveia** [comment]
@soulitzer Our PR hasn't been reviewed yet, is there anything we should do?

**Comment by soulitzer** [comment]
Could you add more context on the original issue e.g., are there any specific use cases you are trying to enable with this change?

**Comment by joaotgouveia** [comment]
@soulitzer We don't have any specific use cases besides the two mentioned in #37529. This function scheduler simplifies the implementation of the metrics handler mentioned in #28245 and allows us to eliminate some watchdog threads in RPC. For instance, as of now ProcessGroupNCCL utilizes two watchdog threads: ncclCommWatchdog and heartbeatMonitor. If I understand the code correctly, an alternative approach would be to use our FunctionScheduler to register two periodic jobs instead of creating these two watchdog threads. Instead of signaling the respective condvars to stop the threads, we can simply cancel the jobs. This solution is simpler and requires only one additional thread instead of two.

**Comment by joaotgouveia** [comment]
> @soulitzer We don't have any specific use cases besides the two mentioned in #37529. This function scheduler simplifies the implementation of the metrics handler mentioned in #28245 and allows us to eliminate some watchdog threads in RPC. For instance, as of now ProcessGroupNCCL utilizes two watchdog threads: ncclCommWatchdog and heartbeatMonitor. If I understand the code correctly, an alternative approach would be to use our FunctionScheduler to register two periodic jobs instead of creating these two watchdog threads. Instead of signaling the respective condvars to stop the threads, we can simply cancel the jobs. This solution is simpler and requires only one additional thread instead of two.

cc @rohan-varma

**Pull request closed without merging**
