### PR TITLE
Fix DEBUG=1 asserts with NJT ops

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #129014

### CODE REVIEW

**Review by YuqingJ — APPROVED** [review]
Thanks for fixing this!

**Review by soulitzer — APPROVED** [review]

**Comment by jbschlosser** [comment]
I added this logic to #122836, but somehow it didn't make it in. Going to land this now.

**Pull request closed without merging**
