### PR TITLE
Reland "Towards unifying symbolic and non symbolic fake tensor (#89038)"

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89143

This reverts commit cf6003f0469ae1440d4a8585860c2c5f4c738707.

Differential Revision: [D41363992](https://our.internmc.facebook.com/intern/diff/D41363992)

### CODE REVIEW

**Review by albanD — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41363992).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41363992).

**Comment by ZainRizvi** [comment]
@pytorchbot revert -c 'nosignal' -m "This seems to be causing the test_make_fx_symbolic_exhaustive_rad2deg_cpu_float32 and test_make_fx_symbolic_exhaustive_inplace_rad2deg_cpu_float32 test to fail across multiple jobs"

Logs:
https://hud.pytorch.org/pytorch/pytorch/commit/e686b8c3ba93cb7caa314c78bf84dbd2d7df9683

**Pull request closed without merging**
