### PR TITLE
define public API for torch.nn.utils

### PR DESCRIPTION
**Pull request by ringohoffman**
Adding modules imported here and the following functions to the `__all__`:
* [clip_grad_norm_](https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_norm_.html)
* [clip_grad_value_](https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_value_.html)
* [remove_weight_norm](https://pytorch.org/docs/stable/generated/torch.nn.utils.remove_weight_norm.html)
* [parameters_to_vector](https://pytorch.org/docs/stable/generated/torch.nn.utils.parameters_to_vector.html)
* [vector_to_parameters](https://pytorch.org/docs/stable/generated/torch.nn.utils.vector_to_parameters.html)
* [remove_spectral_norm](https://pytorch.org/docs/stable/generated/torch.nn.utils.remove_spectral_norm.html)
* [skip_init](https://pytorch.org/docs/stable/generated/torch.nn.utils.skip_init.html)

### CODE REVIEW

**Comment by ringohoffman** [comment]
`clip_grad_norm` (deprecated), `fuse_conv_bn_eval`, `fuse_conv_bn_weights`, and `convert_conv2d_weight_memory_format` are all imported here but do not have docs pages.

**Comment by vadimkantorov** [comment]
Btw vector_to_params / params_to_vector seems related to flatten_parameters concept ...

**Review by mikaylagawarecki — COMMENTED** [review]
You can expose the documentation for the functions you mentioned that are missing from the documentation over [here](https://github.com/pytorch/pytorch/blob/main/docs/source/nn.rst?plain=1#L358)

Those functions you mentioned that are failing the public bindings test should still be added to the `__all__`

**Comment by ringohoffman** [comment]
I added the other 2 functions from `fusion` since it seemed strange that they would be omitted. I also tried to split up `nn.rst` into more logical sections so that the functions in the same submodule would be kept and documented together. LMK how this looks.

**Review by mikaylagawarecki — APPROVED** [review]
For future reference, you can check out the docs preview from your PR under 

> 📄 Preview [Python docs built from this PR](https://docs-preview.pytorch.org/pytorch/pytorch/111026/index.html)

in the pytorch-bot comment above.

It renders nicely to me, it would be awesome if you could add short docstrings for fuse_conv_bn_eval
fuse_conv_bn_weights
fuse_linear_bn_eval
fuse_linear_bn_weights

as well since they come up as blank in the table 
Screenshot 2023-10-11 at 5 49 21 PM

**Comment by ringohoffman** [comment]
@mikaylagawarecki I gave it my best effort! Please LMK what you think of my changes.

**Comment by ringohoffman** [comment]
`fuse_conv_bn_weights` & `fuse_linear_bn_weights` are written such that they expect that `bn_rm` and `bn_rv` are not `None`, but [there are a lot of places where these functions are called without checking that they are not `None`](https://github.com/pytorch/pytorch/actions/runs/6489486936/job/17624331922?pr=111026#step:11:1288). I think the easiest thing to do will be to `assert` that they are not `None` in all these places these functions are called since they will certainly raise `TypeError`s if they are `None` anyway.

**Review by mikaylagawarecki — APPROVED** [review]
This is some much appreciated cleanup! Thanks a lot for your effort :)

**Pull request closed without merging**
