### PR TITLE
Update to newest CUTLASS version 3.2.2

### PR DESCRIPTION
**Pull request by drisspg**
# Summary
This PR updates the third_party/ dependency Cutlass from v3.1.0 to v.3.2.1

### CODE REVIEW

**Comment by drisspg** [comment]
# Current error while building locally:
```
[1/13] Building CUDA object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/nested/cuda/NestedTensorMatmul.cu.o
FAILED: caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/nested/cuda/NestedTensorMatmul.cu.o
/usr/bin/ccache /usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -ccbin=/usr/lib64/ccache/clang -DAT_PER_OPERATOR_HEADERS -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DIDEEP_USE_MKL -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTORCH_CUDA_BUILD_MAIN_LIB -DUSE_C10D_GLOO -DUSE_CUDA -DUSE_DISTRIBUTED -DUSE_EXPERIMENTAL_CUDNN_V8_API -DUSE_EXTERNAL_MZCRC -DUSE_FLASH_ATTENTION -DUSE_RPC -DUSE_TENSORPIPE -D_FILE_OFFSET_BITS=64 -Dtorch_cuda_EXPORTS -I/home/drisspg/meta/pytorch/build/aten/src -I/home/drisspg/meta/pytorch/aten/src -I/home/drisspg/meta/pytorch/build -I/home/drisspg/meta/pytorch -I/home/drisspg/meta/pytorch/third_party/onnx -I/home/drisspg/meta/pytorch/build/third_party/onnx -I/home/drisspg/meta/pytorch/third_party/foxi -I/home/drisspg/meta/pytorch/build/third_party/foxi -I/home/drisspg/meta/pytorch/aten/src/THC -I/home/drisspg/meta/pytorch/aten/src/ATen/cuda -I/home/drisspg/meta/pytorch/aten/src/ATen/../../../third_party/cutlass/include -I/home/drisspg/meta/pytorch/build/caffe2/aten/src -I/home/drisspg/meta/pytorch/aten/src/ATen/.. -I/home/drisspg/meta/pytorch/c10/cuda/../.. -I/home/drisspg/meta/pytorch/c10/.. -I/home/drisspg/meta/pytorch/third_party/tensorpipe -I/home/drisspg/meta/pytorch/build/third_party/tensorpipe -I/home/drisspg/meta/pytorch/third_party/tensorpipe/third_party/libnop/include -I/home/drisspg/meta/pytorch/torch/csrc/api -I/home/drisspg/meta/pytorch/torch/csrc/api/include -isystem /home/drisspg/meta/pytorch/build/third_party/gloo -isystem /home/drisspg/meta/pytorch/cmake/../third_party/gloo -isystem /home/drisspg/meta/pytorch/cmake/../third_party/tensorpipe/third_party/libuv/include -isystem /home/drisspg/meta/pytorch/third_party/protobuf/src -isystem /home/drisspg/local/miniconda3/envs/dev/include -isystem /home/drisspg/meta/pytorch/third_party/ittapi/include -isystem /home/drisspg/meta/pytorch/cmake/../third_party/eigen -isystem /usr/local/cuda/include -isystem /home/drisspg/meta/pytorch/third_party/ideep/mkl-dnn/include/oneapi/dnnl -isystem /home/drisspg/meta/pytorch/third_party/ideep/include -isystem /home/drisspg/meta/pytorch/cmake/../third_party/cudnn_frontend/include -D_GLIBCXX_USE_CXX11_ABI=1 -Xfatbin -compress-all -DONNX_NAMESPACE=onnx_torch -gencode arch=compute_80,code=sm_80 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=bad_friend_decl --expt-relaxed-constexpr --expt-extended-lambda  -Wno-deprecated-gpu-targets --expt-extended-lambda -DCUB_WRAPPED_NAMESPACE=at_cuda_detail -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -O3 -DNDEBUG -std=c++17 -Xcompiler=-fPIC -DMKL_HAS_SBGEMM -DTORCH_USE_LIBUV -DCAFFE2_USE_GLOO -DTH_HAVE_THREAD -Xcompiler=-Wall,-Wextra,-Wno-unused-parameter,-Wno-unused-function,-Wno-unused-result,-Wno-missing-field-initializers,-Wno-unknown-pragmas,-Wno-type-limits,-Wno-array-bounds,-Wno-unknown-pragmas,-Wno-strict-overflow,-Wno-strict-aliasing,-Wno-missing-braces,-Wno-range-loop-analysis -Wno-sign-compare -MD -MT caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/nested/cuda/NestedTensorMatmul.cu.o -MF caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/nested/cuda/NestedTensorMatmul.cu.o.d -x cu -c /home/drisspg/meta/pytorch/aten/src/ATen/native/nested/cuda/NestedTensorMatmul.cu -o caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/nested/cuda/NestedTensorMatmul.cu.o
/home/drisspg/meta/pytorch/aten/src/ATen/../../../third_party/cutlass/include/cutlass/gemm/kernel/sm90_tile_scheduler_stream_k.hpp(580): error: calling a __device__ function("cute::block_id_in_cluster()") from a __host__ __device__ function("output_tile_index") is not allowed
auto [cta_m_in_cluster, cta_n_in_cluster, _] = cute::block_id_in_cluster();
```

**Comment by drisspg** [comment]
This looks landable except for the fact that it is not based on a tag and rather a commit on main. @malfet explained to me that we generally don't like including these in third_party since it is possible for the package to have its history overwritten and the commit to get removed. @ipiszy How urgent is 3.2 for the fp8 single gpu perf, I remember you saying that we will likely not need to generate the matmuls using cutlass for good performance

**Comment by Skylion007** [comment]
@drisspg Can you update to 3.2.1 now that it's on main as well?

**Comment by drisspg** [comment]
> @drisspg Can you update to 3.2.1 now that it's on main as well?

Ahh thanks for the ping, I was waiting for this release

**Review by cpuhrsch — APPROVED** [review]

**Comment by cpuhrsch** [comment]
Obviously this needs to be co-landed :p But just writing it here for posterity.

**Comment by drisspg** [comment]
# Udpate
After some investigation I see that Tri is using Cutlass at this commit: https://github.com/NVIDIA/cutlass/tree/e0aaa3c3b38db9a89c31f04fef91e92123ad5e2e

I just updated my local PR:
https://github.com/pytorch/pytorch/pull/108070
to use this version of cutlass and I am not seeing the IMA anymore
As well compute-santizer also reports 0 errors with this version

**Review by malfet — APPROVED** [review]

**Comment by drisspg** [comment]
Attempted to see if the local fix would work: https://github.com/NVIDIA/cutlass/issues/1138

Turns out you can't commit a dirty third_party lib so thats why ci no likey

**Comment by drisspg** [comment]
@kadeng @ipiszy does this cutlass max autotune failure look legit?

**Comment by kadeng** [comment]
> @kadeng @ipiszy does this cutlass max autotune failure look legit?

Yes, but it's not a bug, rather a change in Cutlass op enumeration behavior. I will experiment a bit with v3.2.2 and see if I can reproduce it on my devgpu and come up with a hotfix or slight change to the test. Not sure if this test failure should block this PR, as it is solely for an experimental feature.

**Comment by kadeng** [comment]
Thanks @drisspg - As discussed elsewhere, this PR is superseded by https://github.com/pytorch/pytorch/pull/112762
which is merged. Closing this PR.

**Pull request closed without merging**
