### PR TITLE
[ROCm] Enable several inductor UTs

### PR DESCRIPTION
**Pull request by pragupta**
- test_compiled_optimizers.py
- test_foreach.py
- test_profiler.py
- Fix test_profiler.py:test_inductor_profiling_triton_launch - Look for hipModuleLaunchKernel in the events list for AMD GPUs instead of cuLaunchKernel

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by jataylo** [comment]
@pragupta A few lintrunner fails, also this UT is failing `test_inductor_profiling_kernel_names_template`

```
2023-11-02T20:07:48.9900189Z FAILED [0.1297s] inductor/test_profiler.py::DynamoProfilerTests::test_inductor_profiling_kernel_names_template - torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
2023-11-02T20:07:48.9901450Z LoweringException: RuntimeError: No choices to select, please consider adding ATEN into max_autotune_gemm_backends config (defined in torch/_inductor/config.py) to allow at least one choice. 
2023-11-02T20:07:48.9901618Z   target: aten.mm.default
2023-11-02T20:07:48.9901801Z   args[0]: TensorBox(StorageBox(
2023-11-02T20:07:48.9902505Z     InputBuffer(name='arg0_1', layout=FixedLayout('cuda', torch.float32, size=[4, 4], stride=[4, 1]))
2023-11-02T20:07:48.9902639Z   ))
2023-11-02T20:07:48.9902822Z   args[1]: TensorBox(StorageBox(
2023-11-02T20:07:48.9903517Z     InputBuffer(name='arg1_1', layout=FixedLayout('cuda', torch.float32, size=[4, 4], stride=[4, 1]))
2023-11-02T20:07:48.9903648Z   ))
```

This is expected until our CI upgrade goes through, so we can skip this for now.

**Review by jataylo — APPROVED** [review]
LGTM! @malfet @kit1980 could we get some help to merge this to enable some additional inductor UT testing on ROCm

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
