### PR TITLE
[JIT] Add modulelist indexing for integer literal

### PR DESCRIPTION
**Pull request by eellison**
Allow indexing into modulelists for integer literals.

### CODE REVIEW

**Review by zdevito — COMMENTED** [review]
The code for this looks fine, but what is the use case? My concern is that this is misleading because it gives the impression arbitrary indexing of modules lists works, but it only works for literal constants. I can see people testing the feature with a constant, then using the result of that experiment to write code that relies on it, only to find out it is not fully supported. Like support for list comprehensions, I feel like this should be either all or nothing.

**Comment by suo** [comment]
@sidazhang mentioned a large part of their module indexing involves doing something special to the 0th module in a list.

**Review by suo — APPROVED** [review]
I'm going to approve. My basic argument for why we should have this functionality:
- Module containers are already partially implemented, since you can't index at all
- It's similar to existing tuple behavior.
- Indexing with a literal solves a real user issue--@sidazhang mentioned that this is the majority of their direct indexing into module lists.

That said: @eellison can we make this work for ModuleDict as well please?

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit dbab53a:
* **3/3** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=dbab53aed9a4e3931b0b35bcd4c0ce8539200bfb).

### 2 new failures recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/3951149) pytorch_xla_linux_xenial_py3_6_clang7_build (1/2)
**Step:** "Build" ([details](https://dr.pytorch.org/build-details.html?build_id=74179516))
<details>
<summary>
<code>Dec 13 20:33:58 caused by: Connection refused (os error 111)</code>
</summary>

```
Dec 13 20:33:58 +++ eval 'extract_trap_cmd ' 
Dec 13 20:33:58 ++++ extract_trap_cmd 
Dec 13 20:33:58 ++++ printf '%s\n' '' 
Dec 13 20:33:58 +++ printf '%s\n' cleanup 
Dec 13 20:33:58 ++ trap -- ' 
Dec 13 20:33:58 cleanup' EXIT 
Dec 13 20:33:58 ++ which sccache 
Dec 13 20:33:58 ++ sccache --stop-server 
Dec 13 20:33:58 Stopping sccache server... 
Dec 13 20:33:58 error: couldn't connect to server 
Dec 13 20:33:58 caused by: Connection refused (os error 111) 
Dec 13 20:33:58 ++ true 
Dec 13 20:33:58 ++ rm /var/lib/jenkins/sccache_error.log 
Dec 13 20:33:58 rm: cannot remove '/var/lib/jenkins/sccache_error.log': No such file or directory 
Dec 13 20:33:58 ++ true 
Dec 13 20:33:58 ++ SCCACHE_ERROR_LOG=/var/lib/jenkins/sccache_error.log 
Dec 13 20:33:58 ++ SCCACHE_IDLE_TIMEOUT=1200 
Dec 13 20:33:58 ++ RUST_LOG=sccache::server=error 
Dec 13 20:33:58 ++ sccache --start-server 
Dec 13 20:33:58 Starting sccache server... 
Dec 13 20:33:58 ++ sccache --zero-stats 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/3952195) pytorch_linux_xenial_py3_clang5_asan_test (2/2)
**Step:** "Test" ([details](https://dr.pytorch.org/build-details.html?build_id=74211061))
<details>
<summary>
<code>Dec 13 22:45:36 RuntimeError: test_nn failed!</code>
</summary>

```
Dec 13 22:45:35   File "test_nn.py", line 49, in <module> 
Dec 13 22:45:35     import hypothesis_utils as hu 
Dec 13 22:45:35   File "/var/lib/jenkins/workspace/test/hypothesis_utils.py", line 9, in <module> 
Dec 13 22:45:35     from hypothesis.searchstrategy import SearchStrategy 
Dec 13 22:45:35 ModuleNotFoundError: No module named 'hypothesis.searchstrategy' 
Dec 13 22:45:36 Traceback (most recent call last): 
Dec 13 22:45:36   File "test/run_test.py", line 454, in <module> 
Dec 13 22:45:36     main() 
Dec 13 22:45:36   File "test/run_test.py", line 446, in main 
Dec 13 22:45:36     raise RuntimeError(message) 
Dec 13 22:45:36 RuntimeError: test_nn failed! 
Dec 13 22:45:36 + cleanup 
Dec 13 22:45:36 + retcode=1 
Dec 13 22:45:36 + set +x 
Dec 13 22:45:36 =================== sccache compilation log =================== 
Dec 13 22:45:36 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 13 22:45:36 Compile requests                 17 
Dec 13 22:45:36 Compile requests executed        15 
Dec 13 22:45:36 Cache hits                        0 
Dec 13 22:45:36 Cache misses                     15 
Dec 13 22:45:36 Cache timeouts                    0 
```

</details>

### 1 failure *not* recognized by patterns:
| Job | Step | Status |
| --- | --- | --- |
| CircleCI <sup>pytorch_linux_xenial_py3_6_gcc5_4_build</sup> | <sup>Build</sup> | New in PR |


---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Comment by algoterranean** [comment]
Is this being merged into `master` soon?

**Comment by eellison** [comment]
> Is this being merged into `master` soon?

Hi, yes it will be, thanks for the reminder.

**Comment by snie2012** [comment]
Also waiting for this to land

**Pull request closed without merging**
