### PR TITLE
Implement Tanh Gelu Approximation

### PR DESCRIPTION
**Pull request by jbschlosser**
Implement Tanh Gelu Approximation (#61439)

### CODE REVIEW

**Comment by JackCaoG** [comment]
@jbschlosser Do we have an eta for this pr to merge to 1.11?

Context:
I am trying to rebase torch_xla branch release/1.11 on top of existing master. gelu change has merged to torch_xla master. I could checkout a older master and rebase `release/1.11` on top that. However if this pr is going to merge tmr I might as well just wait.

**Comment by jbschlosser** [comment]
@JackCaoG Seems likely it'll merge tomorrow - cc @malfet @atalman

**Comment by malfet** [comment]
@jbschlosser this looks like a pretty big change which very much feels like a non-trivial feature work. Why does it need to go into 1.11 so close to cutoff date?

**Comment by jbschlosser** [comment]
@malfet Fair, checking with NVIDIA now to see if 1.11 is necessary for some reason. Otherwise, let's just leave it out.

**Comment by jbschlosser** [comment]
@JackCaoG Sorry for the false alarm, we're leaving this out of 1.11.

**Pull request closed without merging**
