### PR TITLE
[cuDNN][cuDNN V8 API] Always build assuming cuDNN >= 8.0

### PR DESCRIPTION
**Pull request by eqy**
We've been building with V8 (incl. V8 API) by default for a while now; this PR cleans up some guards for cuDNN < 8.0.

CC @ptrblck @ngimel

### CODE REVIEW

**Comment by eqy** [comment]
TODO: just use https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/third_party/cudnn_frontend.BUILD for bazel failures?

**Review by ngimel — APPROVED** [review]

**Comment by DanilBaibak** [comment]
PR breaks the internal build. @ngimel could you pls help fix it. Here you can find more details - [D42528491](https://www.internalfb.com/diff/D42528491).

**Pull request closed without merging**
