### PR TITLE
[ROCm][Inductor] Enable AOT Inductor CPP UTs for ROCm

### PR DESCRIPTION
**Pull request by pragupta**
Fixes #ISSUE_NUMBER

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by jataylo — APPROVED** [review]

**Comment by pragupta** [comment]
These tests are now running fine in CI:

image

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
@zoranzhao @malfet ,
Can you please review this PR.

**Review by malfet — APPROVED** [review]
Looks good to me, though failures might be relevant

**Comment by pragupta** [comment]
> Looks good to me, though failures might be relevant

These are all failures happening on our rocm CI prior to my change. Being worked on separately

**Pull request closed without merging**
