### PR TITLE
[quant][fx] Remove convert.py since it is not used now

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #74322
* __->__ #74276

Summary:
Removing convert.py since we have rerouted the traffic to _convert_do_not_use, we'll do a rename in the follow up PR

Test Plan:
python test/test_quantization.py TestQuantizeFx
python test/test_quantization.py TestQuantizeFxOps

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D34914261](https://our.internmc.facebook.com/intern/diff/D34914261)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34914261).

**Comment by vkuzo** [comment]
> Removing convert.py since we have rerouted the traffic to _convert_do_not_use, we'll do a rename in the follow up PR

Would it make sense to do it in this PR? It's unusual to have something named `_do_not_use` as the main logic in production, even though OSS will not see it our Meta customers might, if the follow-up PR gets delayed and if there are any bugs in the new path this may get confusing.  Accepting to unblock.

**Review by vkuzo — APPROVED** [review]

**Comment by jerryzh168** [comment]
> > Removing convert.py since we have rerouted the traffic to _convert_do_not_use, we'll do a rename in the follow up PR
> 
> Would it make sense to do it in this PR? It's unusual to have something named `_do_not_use` as the main logic in production, even though OSS will not see it our Meta customers might, if the follow-up PR gets delayed and if there are any bugs in the new path this may get confusing. Accepting to unblock.

I'm planning to do the rename immediately after this, if we do rename here I'm a bit worried that github will try to calculate the changeset between the old and new convert, which is not super helpful..

thanks for accepting, I'll put up the rename PR

**Comment by jerryzh168** [comment]
maybe let me put up both PRs and we can land them together

**Comment by vkuzo** [comment]
> I'm planning to do the rename immediately after this, if we do rename here I'm a bit worried that github will try to calculate the changeset between the old and new convert, which is not super helpful..

Up to you.  In general from what I've seen at other teams at Meta, the "temporary code should not land to master" usually overrides other things. I think for this case maybe it's ok, but in general it's not a good practice to do this consistently for production critical code.

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34914261).

**Pull request closed without merging**
