### PR TITLE
Gh/taylorrobie/matmul optimize

### PR DESCRIPTION
**Pull request by robieta**
This applies two minor optimizations to native Conv2D.
1) Due to the `== 4` check [here](https://github.com/pytorch/pytorch/blob/70e00444bc687deeef280e2468653375c1546cfb/aten/src/ATen/native/ConvolutionMM2d.cpp#L157), slicing the input (and as a result reducing its dimensionality to three) was causing Im2Col to occur even for the 1x1 case where it is a no-op.
2) When `bias=False`, zeroing the input is wasteful as we can simply pass `beta=0` to the BLAS routine.

Benchmarks for this PR are fairly light; in both cases we're simply doing less work so performance should be strictly better. (Thus I didn't bother fuzzing.) To show a slightly different workflow, this script lets the user control gathering measurements rather than calling `subprocess`.

```
# benchmark_im2col_skip.py
import argparse
import os
import pickle

import torch
from torch.utils._benchmark import Timer, Compare

EXPECTED_ENVS = ("fbcode_warm", "branch")
ENV = os.getenv("CONDA_DEFAULT_ENV")
assert ENV in EXPECTED_ENVS

RESULT_FILE_TEMPLATE = "/tmp/im2col_skip_{env}.pkl"

REPEATS = 20
SIZES = [
    (64, 64, 1, 32),
    (512, 512, 1, 14),
    (1024, 1024, 1, 7),
    (3, 256, 1, 100),
    (256, 128, 8, 32),
]

def benchmark():
    torch._C._set_mkldnn_enabled(False)

    results = []
    for i, (c_in, c_out, b, size) in list(enumerate(SIZES)) * REPEATS:
        for kernel_size in [1, 3]:
            model = torch.nn.Conv2d(
                c_in, c_out, kernel_size=kernel_size, stride=1,
                padding=(0, 0), groups=1, bias=False
            )
            model.eval()
            timer = Timer(
                "model(x)",
                label="Conv2D",
                description=f"{kernel_size}x{kernel_size} [{i}]",
                globals={
                    "model": model,
                    "x": torch.ones((b, c_in, size, size)),
                },
                env=ENV,
            )
            results.append(timer.blocked_autorange(min_run_time=0.5))

    with open(RESULT_FILE_TEMPLATE.format(env=ENV), "wb") as f:
        pickle.dump(results, f)


def process():
    results = []
    for env in EXPECTED_ENVS:
        with open(RESULT_FILE_TEMPLATE.format(env=env), "rb") as f:
            results.extend(pickle.load(f))
    results.sort(key=lambda r: r.description)

    cmp = Compare(results)
    cmp.trim_significant_figures()
    cmp.print()
    for i, (c_in, c_out, b, size) in enumerate(SIZES):
        print(f"[{i}]  c_in: {c_in:>4}{'':>8}c_out: {c_out:>4}{'':>8}batch: {b}{'':>8}Height/width: {size:>4}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--process", action="store_true")
    args = parser.parse_args()
    if args.process:
        process()
    else:
        benchmark()
```

```
$ conda deactivate && source activate branch && python examples/benchmark_im2col_skip.py
$ conda deactivate && source activate fbcode_warm && python examples/benchmark_im2col_skip.py
$ python examples/benchmark_im2col_skip.py --process
```

```
[-------------------------------------------------------------------- Conv2D -------------------------------------------------------------------]
                           |  1x1 [0]  |  1x1 [1]  |  1x1 [2]  |  1x1 [3]  |  1x1 [4]  |  3x3 [0]  |  3x3 [1]  |  3x3 [2]  |  3x3 [3]  |  3x3 [4]
1 threads: --------------------------------------------------------------------------------------------------------------------------------------
  (branch)       model(x)  |    229    |    1540   |    1950   |     994   |    8000   |    1210   |   10000   |   12000   |    3000   |   110000
  (fbcode_warm)  model(x)  |    275    |    1620   |    2000   |    1430   |    9700   |    1200   |   11000   |   12300   |    3650   |   110000

Times are in microseconds (us).


[0]  c_in:   64        c_out:   64        batch: 1        Height/width:   32
[1]  c_in:  512        c_out:  512        batch: 1        Height/width:   14
[2]  c_in: 1024        c_out: 1024        batch: 1        Height/width:    7
[3]  c_in:    3        c_out:  256        batch: 1        Height/width:  100
[4]  c_in:  256        c_out:  128        batch: 8        Height/width:   32
```

The effect, of course, varies with arithmetic intensity but improvement is non-trivial even when the number of channels is large.

TEST_PLAN: attached benchmark.

### CODE REVIEW

**Comment by robieta** [comment]
Build failures appear to be because my branch is before the recent codegen changes. I'll rebase and try again.

**Review by ngimel — APPROVED** [review]
Cool fix, thanks!

**Comment by robieta** [comment]
@jerryzh168 @vkuzo This appears to break quantization aware training, however I added checks to the conv kernel and confirmed that skipping the redundant im2col transform produces identical results. Could you take a look?

**Comment by vkuzo** [comment]
from https://app.circleci.com/pipelines/github/pytorch/pytorch/214039/workflows/8eed3afb-2347-40e8-b925-a1a45e1aec04/jobs/7473732,
```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/quantization/test_qat_module.py", line 356, in test_conv_bn_folded_vs_unfolded
    input_channels_per_group=st.sampled_from([2, 3, 4]),
  File "/var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/core.py", line 1116, in wrapped_test
    raise the_error_hypothesis_found
  File "/var/lib/jenkins/workspace/test/quantization/test_qat_module.py", line 501, in test_conv_bn_folded_vs_unfolded
    self.assertEqual(weight_grad_ref, weight_grad_actual, atol=precision, rtol=0)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1127, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=0 and atol=1e-05, found 2 element(s) (out of 4) whose difference(s) exceeded the margin of error (including 2 nan comparisons). The greatest difference was nan (0.0 vs. nan), which occurred at index (0, 0, 0, 0).
```

Looks like something is generating `NaN`s.  Is this reproducible locally?

**Comment by robieta** [comment]
> Is this reproducible locally?
Yes.

**Comment by robieta** [comment]
Superseded by https://github.com/pytorch/pytorch/pull/45557

**Pull request closed without merging**
