### PR TITLE
Fix CopySlices logic to ensure wrapped node runs properly.

### PR DESCRIPTION
**Pull request by albanD**
This should remove the failures seen by https://github.com/pytorch/pytorch/pull/89720 in functionalization
Locally verified that running the following on top of this PR does pass: `python benchmarks/dynamo/huggingface.py --accuracy --backend aot_eager --training --only MobileBertForMaskedLM`

### CODE REVIEW

**Comment by ezyang** [comment]
This is super sweet, but TBH I have NFC what the original CopySlices code did, so I guess I will have to study it up first.

**Comment by ezyang** [comment]
Working on some of the comments here.

# What is CopySlices?

We support autograd with inplace mutation; e.g., if you write `non_leaf.mul_(2)` we will correctly rewrite this operation to look as if you wrote `new_non_leaf = old_non_leaf.mul(2)`. As part of this operation, we must inplace modify the `grad_fn` of `non_leaf`; whatever it was previously (e.g., `ThingThatProducedNonLeafBackward`), after the inplace operation it should be `MulBackward` which then points to `ThingThatProducedNonLeafBackward`. We call this rebasing the history of the variable.

Now, a difficult situation is what happens if `non_leaf` is a differentiable view of `base`. It would be incorrect to only modify the grad_fn of `non_leaf`, because the mutation to `non_leaf` is reflected in `base`, and so subsequent uses of `base` should also see the update. So we instead want to modify the `grad_fn` of `base`. But we cannot modify the `grad_fn` to be `MulBackward` since that we imply we inplace multiplied ALL of `base`, but really we only multiplied whatever subset of base was viewed by `non_leaf`. So we need to take MulBackward, and blow it up into a bigger version that MulBackwards on a small slice, and then copies that slice into the big gradient that represents `grad_base`. That's `CopySlices`.

**Comment by voznesenskym** [comment]
> Working on some of the comments here.
> 
> # What is CopySlices?


@albanD had some really great diagrams in our jam today, and it helped me understand it a bit better. I think a diagram would go really far here. (esp w/r/t explaining rebase_history vs set_history)

**Comment by voznesenskym** [comment]
Going to patch this onto our stack and keep fixing stuff @ezyang

**Review by soumith — APPROVED** [review]
i'm going to stamp this because ezyang and voz must have not had the courage to :D

**Review by voznesenskym — APPROVED** [review]

**Review by ezyang — APPROVED** [review]
I basically understand the patch and it looks good.

**Pull request closed without merging**
