### PR TITLE
Fix hooks handling for unpickled nnmodule

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96224

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by wconstab** [comment]
@albanD we can continue the discussion on the other PR (revert: https://github.com/pytorch/pytorch/pull/96246) but i figured we might as well get this landed asap just in case

**Pull request closed without merging**
