### PR TITLE
[TorchGen] Use std::optional in generated code

### PR DESCRIPTION
**Pull request by cyyever**
This PR changes TorchGen to generate std::optional.

### CODE REVIEW

**Comment by ezyang** [comment]
do you want review on this yet?

**Comment by cyyever** [comment]
> do you want review on this yet?

It‘s time to review.

**Comment by ezyang** [comment]
I guess we should wait for the other PR to reland first

**Comment by cyyever** [comment]
> I guess we should wait for the other PR to reland first

What is "the other PR"? The XLA one? We should have long-term plan for such changes as it would affect lots of upstream packages and yes we should wait for some time.

**Comment by ezyang** [comment]
The Generator one that got reverted again

**Comment by cyyever** [comment]
> The Generator one that got reverted again

After rebase, this PR is independent of that one.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
