### PR TITLE
[1/3] [WIP] Intel GPU Runtime Upstreaming for Stream

### PR DESCRIPTION
**Pull request by guangyey**
# Motivation
As mentioned in [[RFC] Intel GPU Runtime Upstreaming](https://github.com/pytorch/pytorch/issues/114842), The second runtime component we would like to upstream is `Stream` which contains the stream management functions of Intel GPU's runtime. To facilitate the code review, we split the code changes into 3 PRs. This is the first one of the 3 PRs and covers the changes under `c10` and `aten`.

# Design
Intel GPU stream is a wrapper of sycl queue. In our design, we will maintain a sycl queue pool containing 32 queues per device, and when a queue is requested one of these queues is returned round-robin. The current stream is thread-local and assigned to the first queue in the queue pool in its initialization. The corresponding C++ files related to `Stream` will be placed in c10/xpu folder. And we provide the c10 stream runtime APIs, like
  - `c10::xpu::getStreamFromPool`
  - `c10::xpu::getCurrentXPUStream`
  - `c10::xpu::setCurrentXPUStream`
  - `c10::xpu::deviceSynchronize`
  - ...
 
# Additional Context
This PR is dependent on [[1/4] Intel GPU Runtime Upstreaming for Device](https://github.com/pytorch/pytorch/pull/116019) and [[2/4] Intel GPU Runtime Upstreaming for Device](https://github.com/pytorch/pytorch/pull/116321).  So there are some duplicated CMake files. Once these two PRs are merged, I will rebase this one to address those conflicts.
In our plan, 3 PRs should be submitted to PyTorch for `Stream`:
1. for `c10` and `aten`
2. for python frontend
3. a patch for sharing code with CUDA

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by guangyey** [comment]
@gujinghui @jgong5 @EikanWang @arthuryuan1987 please help review.

**Comment by EikanWang** [comment]
@guangyey , will you re-submit this PR by ghstack?

**Comment by guangyey** [comment]
yes, will resubmit this PR via ghstack.

**Pull request closed without merging**
