### PR TITLE
[Profiler][Trivial] Small style and safety fixes

### PR DESCRIPTION
**Pull request by robieta**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #87133
* #87244
* #86909
* #86755
* #86754
* #86753
* __->__ #86752

I noticed a couple abbreviations in the new optimizer capture code that are worth expanding. I also made the RawTensorMetadata a bit safer.

Differential Revision: [D40210702](https://our.internmc.facebook.com/intern/diff/D40210702/)

### CODE REVIEW

**Review by slgong-fb — APPROVED** [review]
Great styling and safety check! I had already noticed these changes from the unpublished diff stack.

**Review by aaronenyeshi — APPROVED** [review]
LGTM!

**Pull request closed without merging**
