### PR TITLE
[TD] Heuristic based on file path

### PR DESCRIPTION
**Pull request by clee2000**
Get the folders of each changed file and attempt to map the folders to some tests.

The intention is to push up things like dynamo tests if someone changes a file in the dynamo folder

Please see the tests for examples of what should be matched together

### CODE REVIEW

**Review by ZainRizvi — APPROVED** [review]

**Review by huydhn — APPROVED** [review]
LGTM!  Looking that this heuristic, I think `EditedByPR` could be considered a special case of this rule where the test file itself is one of the paths

**Comment by huydhn** [comment]
Another rule we could consider is to prioritize any tests under the same path, i.e. if https://github.com/pytorch/pytorch/blob/main/test/quantization/pt2e/test_quantize_pt2e.py is updated in the PR, all tests files under the same path are ranked higher, maybe we already have it?

**Comment by clee2000** [comment]
> Another rule we could consider is to prioritize any tests under the same path, i.e. if https://github.com/pytorch/pytorch/blob/main/test/quantization/pt2e/test_quantize_pt2e.py is updated in the PR, all tests files under the same path are ranked higher, maybe we already have it?

Doesn't that sort of get covered by this?

**Comment by huydhn** [comment]
> Doesn't that get covered by this? Unless you want a heuristic just for that. I'm open to that

I think you're right, all the tests that share the path have the same group of keywords, so they would all be ranked highly already regardless of the extracted keywords.

**Pull request closed without merging**
