### PR TITLE
[fix] Fix ninja version check command in cpp_extension

### LINKED ISSUE #2360: One Compatibility issue in THCReduce.cuh
Hi,
Would you please explicitly convert the first input argument into LONG in [Line318, THCReduce.cuh](https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/THCReduce.cuh#L318) in the following way?
`THC_getGridFromTiles(THCCeilDiv((long)outElements, (long)block.x), grid);`

As I'm trying to compile pytorch-0.2.0 on Windows with CUDA 8.0, everything goes smooth for a long time till I'm blocked here with an error; it says no template could be fitted for this function call with 2 args. I guess nvcc for windows fail to implement an implicit conversion. Much thanks!

### PR DESCRIPTION
**Pull request by Charmve**
Fixes #2360

### CODE REVIEW

**Comment by ezyang** [comment]
need cla

**Comment by Charmve** [comment]
@ezyang cla has done

**Comment by Skylion007** [comment]
@Charmve I think the issue number this suppose to be fixing is wrong.

**Comment by ezyang** [comment]
failure seems legit

**Pull request closed without merging**
