### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by smessmer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#26250 Fix CI**

Exclude some ops from the c10 dispatcher that don't work with it yet.

[namedtensor ci]

Differential Revision: [D17390117](https://our.internmc.facebook.com/intern/diff/D17390117/)

### CODE REVIEW

**Comment by zou3519** [comment]
@smessmer Could you include `[namedtensor ci]` into the commit message? That runs the named tensor CI on this pull request. Right now the namedtensor ci only runs on master and auto-passes on PRs, but including [namedtensor ci] into the commit message overrides that.

**Comment by smessmer** [comment]
@zou3519 I added it into the PR description. Or did you mean somewhere else?

**Comment by zou3519** [comment]
> @zou3519 I added it into the PR description. Or did you mean somewhere else?

No, it must be in the git commit message (which is separate from the PR description). The commit message currently looks like:
image

**Review by zou3519 — APPROVED** [review]
thank you!

**Pull request closed without merging**
