### PR TITLE
[Easy] Use prepend arg to register forward hooks in quantize.py

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #89389
* __->__ #89391

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

Differential Revision: [D41431110](https://our.internmc.facebook.com/intern/diff/D41431110)

### CODE REVIEW

**Review by awgu — APPROVED** [review]
LGTM! Thanks for the refactor!

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41431110).

**Pull request closed without merging**
