### PR TITLE
[functorch] add error inputs check to vmap test

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #83017
* #83016
* #82972
* #83004
* #82903
* #82984

The error inputs check tests that on an error input,
`vmap(op)(*args, **kwargs)` rightfully produces an exception.

This PR also fixes the prelu batching rule, which was missing a check.

Test Plan:
- wait for tests

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
This is the only op where we don't have the correct error? :O Kinda surprising.

**Comment by zou3519** [comment]
> This is the only op where we don't have the correct error? :O Kinda surprising.

I'm pretty sure we have more problems:
- There are approximately 50 OpInfos with error inputs, so, the test coverage isn't that good.
- This test doesn't check the error message or the type of the exception. I'm not sure we throw good error messages, but a bad error message is better than not having an error in place :)

**Pull request closed without merging**
