### PR TITLE
fix crash on torch.Tensor.repeat() for 0 repeats

### LINKED ISSUE #23603: torch.Tensor.repeat() fails for 0 repeats
## 🐛 Bug

To enable programming in a generic way, torch.Tensor.repeat() should work for 0 repeats. This is not the case. It works in numpy, it should work in pytorch too.

## To Reproduce

```
>>> import torch
>>> a = torch.ones((2, 2, 2))
>>> a.repeat((2, 0, 2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: invalid argument 3: out of range at ..\aten\src\TH/generic/THTensor.cpp:392
```

## Expected behavior

The repeat call should not crash for the given inputs. It should have the same-shaped result as in numpy:

```
>>> import numpy as np
>>> a = np.ones((2, 2, 2))
>>> np.tile(a, (2, 0, 2))
array([], shape=(4, 0, 4), dtype=float64)
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.1
 - OS (e.g., Linux): Windows 10, Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): anaconda (Windows 10), pip3 (Ubuntu 16.04)
 - Build command you used (if compiling from source):
 - Python version: 3.5.2 (Ubuntu 16.04), 3.7.3 (Windows 10)
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: 2xGTX 1080 Ti (Ubuntu 16.04), GTX 1080 (Windows 10)

### PR DESCRIPTION
**Pull request by oja**
This PR fixes #23603

### CODE REVIEW

**Review by ssnl — CHANGES_REQUESTED** [review]
Needs tests in https://github.com/pytorch/pytorch/blob/7f130c8494d235054917a7abfcbe1058a65d628a/test/test_torch.py#L9066

**Comment by oja** [comment]
> Needs tests in
> 
> https://github.com/pytorch/pytorch/blob/7f130c8494d235054917a7abfcbe1058a65d628a/test/test_torch.py#L9066

fixed!

**Review by ssnl — APPROVED** [review]
Thanks!

**Comment by SsnL** [comment]
Please fix the lint. Thank you.

**Comment by oja** [comment]
> Please fix the lint. Thank you.

Done

**Review by soumith — APPROVED** [review]

**Review by soumith — APPROVED** [review]

**Comment by ailzhang** [comment]
restarted landing on this PR.

**Pull request closed without merging**
