### PR TITLE
cm3leon_generate is at edge of timeout, so bump it up

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #103607

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @msaroufim

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Why not 2100? (Assume timeout is in seconds)

**Comment by ezyang** [comment]
@malfet no reason lol

**Pull request closed without merging**
