### PR TITLE
make refs executor handle kwargs

### LINKED ISSUE #78923: Need to support kwargs in nvfuser python API integration
### 🚀 The feature, motivation and pitch

primTorch's executor prototype currently uses `torch.fx.experimental.proxy_tensor.make_fx` function for creating an FX graph of operations. Currently `make_fx` supports only positional arguments and we need to expand the support to default positional and keyword-only arguments.

```py
In [1]: import torch

In [2]: from torch.fx.experimental.proxy_tensor import make_fx

In [3]: def foo(a, b, alpha=1.0):
   ...:     return torch.add(a, b, alpha=alpha)
   ...:

In [4]: alpha = 0.5

In [5]: a = torch.randn(2, 2)

In [6]: b = torch.randn(2, 2)
```

Here are a few cases that should work:
```py
# case 1
make_fx(foo)(a, b) # raises RuntimeError: Tracing expected 3 arguments but got 2 concrete arguments

# case 2
make_fx(foo)(a, b, alpha=alpha) # TypeError: wrapped() got an unexpected keyword argument 'alpha'

# case 3
make_fx(foo)(a, b, alpha)(a, b, alpha=alpha) # TypeError: forward() got an unexpected keyword argument 'alpha'

# case 4
make_fx(foo)(a, b, alpha)(a, b) # works
```

### Alternatives

_No response_

### Additional context

_No response_

cc @ezyang @gchanan @zou3519 @mruberry @ngimel

### PR DESCRIPTION
**Pull request by ngimel**
Mostly fixes #78923
I had to disable function patching in fx for functions with kwonly args, see https://github.com/pytorch/pytorch/compare/ngimel/make_fx_fix?expand=1#diff-090b22122be0779cd14afd2ebaf20d1e7c0bfe837e9eefa1d84e7521bb1defc6R446, cc @jamesr66a 
But it looks like it was doing weird things anyway - it was patching signature of wrapped function with arbitrary local vars from wrapper, that can't be right, but I don't know what the intent there is.
A lot of functions now fail with nvfuser executor, and some still fail with aten, although with the different errors than before. 
Edit: undid the change to _symbolic_script.py, turns out inspect.unwrapping function is not needed, and fx never sees kwargs. 
cc @IvanYashchuk, @Chillee

### CODE REVIEW

**Review by IvanYashchuk — APPROVED** [review]
`torch/_prims/executor.py` changes look good to me. It would be great to enable keyword-only arguments in the future, but that would require a deeper dive into `torch/fx/_symbolic_trace.py`. 

I was trying to approach this from a different direction (modifying `make_fx` directly https://github.com/pytorch/pytorch/compare/master...IvanYashchuk:make-fx-default-args-kwargs) and test cases from the issue worked fine, but [`test_proxy_tensor.py:test_make_fx_exhaustive`](https://github.com/pytorch/pytorch/blob/bc1fef96aff4aeffe7a7b39ef8b4ff467860df28/test/test_proxy_tensor.py#L177) got broken.

**Comment by IvanYashchuk** [comment]
This PR adds a workaround for using `make_fx` in the executor, it would be better if `make_fx` itself handled keyword arguments. Should we keep https://github.com/pytorch/pytorch/issues/78923 open?

**Comment by IvanYashchuk** [comment]
There's a test failing most likely because of the change in `_symbolic_trace.py`:
```py
ERROR [0.002s]: test_nn_functional_triplet_margin_with_distance_loss (__main__.TestFunctionalTracing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_fx.py", line 4027, in functional_test
    symbolic_trace(fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 878, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 587, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
TypeError: triplet_margin_with_distance_loss() takes 3 positional arguments but 7 were given
```

**Comment by ngimel** [comment]
Yeah I'm not happy about changes in _symbolic_trace, but I don't quite know how to do it right - what patching does now clearly can't be correct in all cases, but apparently needed for some.

**Review by mruberry — APPROVED** [review]
Stamped!

**Comment by ngimel** [comment]
@pytorbchbot rebase

**Pull request closed without merging**
