### PR TITLE
Fixes #4475, Add debug flag for Windows

### LINKED ISSUE #4475: Visual C++ ATen Command line error D8016: '/Ox' and '/RTC1' command-line options are incompatible
The current master dc76db349e9022b8b4e23de19780a5edf63cc5a1 triggers the following error messages from Visual Studio 2015 (Debug build):

2>------ Build started: Project: ATen, Configuration: Debug x64 ------
2>cl : Command line error D8016: '/Ox' and '/RTC1' command-line options are incompatible
...
14>LINK : fatal error LNK1104: cannot open file '....\src\ATen\Debug\ATen.lib'

It appears that they are triggered by *.c files in the ATen project, like "src\TH\vector\AVX.c"

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Review by apaszke — APPROVED** [review]
Awesome! Thanks Peter!

**Comment by N-Dekker** [comment]
Thank you very much for providing a fix for this issue! Note that it may not be the perfect way to solve this issue, because it depends on whether or not CMAKE_BUILD_TYPE matches "Debug", and this CMake variable is usually not set (or "not meaningful") for Visual Studio projects. See https://cmake.org/cmake/help/v3.10/variable/CMAKE_BUILD_TYPE.html However, we will give it a try  :-)

**Comment by peterjc123** [comment]
@N-Dekker It's currently set through the build script `build_libs.bat` that lies in `torch\lib` . If you directly use cmake in ATen, then there should be problems. But I don't know how to write a better one.

**Comment by N-Dekker** [comment]
@peterjc123 CMake already takes care of adding optimization flags to the Release configuration, and debugging flags to the Debug configuration, by default! I just generated a Visual Studio 2015 solution file (64-bit) from the following CMakeLists.txt: 
```
# CMakeLists.txt
cmake_minimum_required( VERSION 3.10 )
project( MyProject )
add_executable(MyExecutable my_cplusplus.cpp my_c.c)
```
It produced the following command-line options:

For my_c.c, Debug:
> /GS /TC /W3 /Zc:wchar_t /Zi /Gm- /Od /Ob0 /Fd"MyExecutable.dir\Debug\vc140.pdb" /Zc:inline /fp:precise /D "WIN32" /D "_WINDOWS" /D "CMAKE_INTDIR=\"Debug\"" /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /RTC1 /GR /Gd /MDd /Fa"Debug/" /EHsc /nologo /Fo"MyExecutable.dir\Debug\" /Fp"MyExecutable.dir\Debug\MyExecutable.pch" 
 
For my_c.c, Release:
> /GS /TC /W3 /Zc:wchar_t /Gm- /O2 /Ob2 /Fd"MyExecutable.dir\Release\vc140.pdb" /Zc:inline /fp:precise /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "CMAKE_INTDIR=\"Release\"" /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /GR /Gd /MD /Fa"Release/" /EHsc /nologo /Fo"MyExecutable.dir\Release\" /Fp"MyExecutable.dir\Release\MyExecutable.pch"  

For my_cplusplus.cpp, Debug:
> /GS /TP /W3 /Zc:wchar_t /Zi /Gm- /Od /Ob0 /Fd"MyExecutable.dir\Debug\vc140.pdb" /Zc:inline /fp:precise /D "WIN32" /D "_WINDOWS" /D "CMAKE_INTDIR=\"Debug\"" /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /RTC1 /GR /Gd /MDd /Fa"Debug/" /EHsc /nologo /Fo"MyExecutable.dir\Debug\" /Fp"MyExecutable.dir\Debug\MyExecutable.pch" 

For my_cplusplus.cpp, Release:

> /GS /TP /W3 /Zc:wchar_t /Gm- /O2 /Ob2 /Fd"MyExecutable.dir\Release\vc140.pdb" /Zc:inline /fp:precise /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "CMAKE_INTDIR=\"Release\"" /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /GR /Gd /MD /Fa"Release/" /EHsc /nologo /Fo"MyExecutable.dir\Release\" /Fp"MyExecutable.dir\Release\MyExecutable.pch" 

So for Release configurations, CMake adds "/O2 /Ob2" by default. Which is a subset of the optimizations offered by flag you are adding, "/Ox". https://msdn.microsoft.com/en-us/library/59a3b321.aspx If you still prefer to add "/Ox" (but only for Release build), I think you can do so by setting CMAKE_C_FLAGS_RELEASE and CMAKE_CXX_FLAGS_RELEASE. What do you think?

**Pull request merged**
