### PR TITLE
Clean up some obsolete TODOs in run_test and several test files

### PR DESCRIPTION
**Pull request by huydhn**
* The TODOs in `test/test_nestedtensor.py` has been mitigated, I keep the issue for reference.
* ~~The TODOs in `test/test_ops_fwd_gradients.py` doesn't apply anymore~~
* The TODOs in `run_test.py` to support disabling C++ tests is probably not going to happen.  I have never seen a flaky C++ test that needs to be disabled before.

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
@huydhn looks like `set_num_threads(1)` is still needed for MacOS.

**Comment by huydhn** [comment]
> @huydhn looks like `set_num_threads(1)` is still needed for MacOS.

I see, let me put it back then.

**Pull request closed without merging**
