### PR TITLE
Update ONNX submodule from ONNX 1.13.1 with Protobuf 4.21 updates

### PR DESCRIPTION
**Pull request by jcwchen**
~Test ONNX 1.13.1 package which was built with Protobuf v21. onnx-test-protobufv21 package was created by this PR: https://github.com/onnx/onnx/pull/4973, which was based with the rel-1.13.1 release branch (which is what PyTorch is using now).~ Update ONNX submodule from https://github.com/onnx/onnx/tree/1.13.1-protobuf4.21, which was created with rel-1.13.1 branch with updated for Protobuf 4.21. Please note that PyTorch should still be able to build ONNX from source by Protobuf 3 with the same source code. 

BTW, https://github.com/onnx/onnx/pull/4956/files. is the PR targeting ONNX's main branch.

### CODE REVIEW

**Comment by BowenBao** [comment]
@kit1980 @malfet This is the ONNX protobuf 4 experimental PR we discussed last time. Would it make sense to try import this PR and test out if it works internally? 

@jcwchen has the onnx side changes in https://github.com/onnx/onnx/pull/4956/files. There is no build file change and it can be built with either protobuf 4 or protobuf 3.

**Review by kit1980 — APPROVED** [review]

**Comment by jcwchen** [comment]
Thanks for approval. FYI: Initially I used a commit from my forked repo for testing and eventually I created a branch (https://github.com/onnx/onnx/tree/1.13.1-protobuf4.21) from onnx main repo based on the existing rel-1.13.1 branch. I used that new branch as the ONNX commit in this PR. It is identical to my previous forked one.

**Review by BowenBao — APPROVED** [review]

**Pull request closed without merging**
