### PR TITLE
Support larger page sizes with `use_mmap_weights`

### PR DESCRIPTION
**Pull request by eqy**
Fixes e.g., `test_large_mmaped_weights_non_abi_compatible_cuda` on machines with 64K page size

CC @malfet @tinglvv @nWEIdia 

cc @ptrblck @msaroufim @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by eqy** [comment]
CC @malfet I believe this shoudl address #126214

**Review by malfet — APPROVED** [review]
LGTM

**Comment by nWEIdia** [comment]
We haven't resolved the merge conflict yet...

**Pull request closed without merging**
