### PR TITLE
extend gather shape check to handle incorrectly sized outputs

### PR DESCRIPTION
**Pull request by robieta**
Fixes a safety issue (Nonsense values and segfaults) introduced by https://github.com/pytorch/pytorch/pull/36875 when in-place gather tries to use incorrect shapes.

Consider the following block of code:
```
k0 = 8
k1 = 8
m = 100

x = torch.rand((k0, k1))
ind = torch.randint(0, k0, (m, k1))
output = torch.empty((m, k1))

print(torch.gather(x, 0, ind, out=output))
print(torch.gather(x, 1, ind, out=output))
```

The first gather is legal, the second is not. (`ind` and `output` need to be transposed) Previously this was caught when the kernel tried to restride inputs for TensorIterator, but we can no longer rely on those checks and must test explicitly. If `m` is small the second gather returns gibberish; if it is large enough to push the read out of memory block the program segfaults.

### CODE REVIEW

**Comment by ngimel** [comment]
test please, for the things that were broken by #36875. Is only gather affected, not cumsum/cumprod/min/max etc?

**Review by ngimel — APPROVED** [review]
Approving, but please add a test.

**Comment by robieta** [comment]
> test please, for the things that were broken by #36875. Is only gather affected, not cumsum/cumprod/min/max etc?

The others have exact shape matching requirements and explicitly enforce them by resizing to a common shape, so it's only gather.

I will add a test before I submit. Thanks for the review!

**Comment by robieta** [comment]
I added a check to the gather unit test. I also think the existing TORCH_CHECK was not correct, as which Tensor `index` is allowed to differ from along `dim` varies between scatter and gather methods. I think it wasn't caught before because `gather_out_cpu` resizes `result` to match `index`

**Pull request closed without merging**
