### PR TITLE
BatchSampler now uses list.clear() instead of creating new objects

### PR DESCRIPTION
**Pull request by ssnl**
[soumith]: PR reverted

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by colesbury** [comment]
This PR needs a description of **why** the change was made.

**Comment by SsnL** [comment]
@soumith can you revert this patch? I think this is wrong. There should be a new object so `clear` does not inplace change the yielded list.

@colesbury This patch is wrong. I made it because I wanted to avoid recreating objects.

**Comment by soumith** [comment]
revert on the way

**Comment by SsnL** [comment]
Thank you and sorry for the trouble!

**Pull request closed without merging**
