### PR TITLE
Move tests from onnx-fb-universe

### PR DESCRIPTION
**Pull request by bddppq**

### CODE REVIEW

**Comment by apaszke** [comment]
1. Can we please somehow separate the universe tests from the core framework tests? Considering that they are 70k lines, this will greatly increase the readability. We don't have C2 and PyTorch tests in one place.
2. Do we really believe that 20k line long dumps of protobufs are anything else than a smoke test? No one is going to check those carefully unless they have a whole day free. I'd argue that we should only test simple things like this, and everything more complicated should run `verify` or sth like this.

**Comment by ezyang** [comment]
There's also an engineering reason to keep them separate, which is that it makes it easier to tell if you had an onnx only change (if all the changes are in test/, you don't know if it was a pytorch change or an onnx change).

**Comment by bddppq** [comment]
Two reasons I prefer to put them together:
1. there are two types of tests in universe, pytorch exports tests and pytorch -> onnx -> caffe2 integration tests. I think we agreed every pytorch change will trigger the tests of first type (aka test_operators.py and test_models.py), and all the expect files are used by tests of first type.
2. All tests have used some common utilities functions in test/common.py (universe used to have a copy). If we put these tests in a separate folder, we need to continue keep a copy of these utils which I think go against the ultimate goal of code sharing.

**Comment by apaszke** [comment]
So the reason why I asked for this is also motivated by what @ezyang mentioned. Right now the ONNX code is fairly decoupled with the framework code. When I get an email notifying me about a new PR, and see that it only touches `torch/onnx`, then I'm pretty sure that I can delete it right away because it's some ONNX-internal change. This is the primary reason why I'd like the ONNX tests to still be slightly separate from the core framework functionality.

Additionally, they're a ton of code and expects, and are maintained by a different set of people, so that's another argument for keeping it clearly separated.

I don't think the CI is a big issue. The tests used to be in an entirely separate repo and it worked just fine, so why would it break now?

Code sharing with `common.py` isn't too bad. We've had similar issues with ATen and still could work around it. Python has `importlib` that lets you import code in directories that are normally unreachable by `import` statements.

**Comment by dzhulgakov** [comment]
I think the concern here is that so many expect files spam the viewer with results. I guess it's a valid concern and it can be mitigated with two fixes:
1) mark expect files as binary (https://stackoverflow.com/questions/11162267/how-do-i-make-git-treat-a-file-as-binary ). It's both make them not render in the UI (desired in this case as it's mostly a smoke test) and will also avoid annoying merge conflicts in some cases 
2) separate files in a different folder. I'd encourage to put files under `test/` but they don't have to be in the root folder. How about we put it under `test/onnx` or something? It feel quite reasonable to me - as we add more tests we should probably do the same to others too. If importing `test/common.py` is an issue - can't we just put it under `test/util` or something like that?

As Junjie pointed out we should definitely run this tests as part of regular CI for PyTorch. I hope everybody agrees with that.

**Comment by apaszke** [comment]
1. I don't see what's the point of having binary expects. They will tell you that *something* has changed, but you really won't have any ideas what was it. If we're going the smoke test path, then let's do it the smoke test way without leaving any unnecessary artifacts. An extra reason to avoid binary files is that `git` is terrible at handling them (for a good reason).
2. `test/onnx` sounds good to me.
3. I never said ONNX tests shouldn't run on PyTorch PRs, and I think that removing this support would be a huge step back.

**Comment by apaszke** [comment]
1. I don't see what's the point of having binary expects. They will tell you that *something* has changed, but you really won't have any ideas what was it. If we're going the smoke test path, then let's do it the smoke test way without leaving any unnecessary artifacts. An extra reason to avoid binary files is that `git` is terrible at handling them (for a good reason).
2. `test/onnx` sounds reasonable, but it's still a bit dirty I think. Do we have a plan for the desired test directory structure after the repo merge? It would be worth discussing
3. I never said ONNX tests shouldn't run on PyTorch PRs, and I think that removing this support would be a huge step back.

**Comment by dzhulgakov** [comment]
1. Ok, I was just throwing the idea - I haven't actually worked with binary files much
2. No proposal yet that I know off - let's discuss it separately.

I want to ask a bit about "When I get an email notifying me about a new PR, and see that it only touches torch/onnx, then I'm pretty sure that I can delete it right away because it's some ONNX-internal change. This is the primary reason why I'd like the ONNX tests to still be slightly separate from the core framework functionality."

Doesn't it apply only to code, not the tests? If something triggers changes in expect files - I'd say the author needs to take a look at it regardless of which part she was changing. It's actually a pain point right now with onnx-fb-universe repo: even with cosmetic changes to trace format output the authors usually don't change the expect files in that repo and it requires somebody else to go and fix up / regenerate.

Thus I see value in `test/onnx` only from pure code organization purposes, not really any anticipated workflow changes. Does it make sense?

**Comment by apaszke** [comment]
Oh the author definitely needs to take a look if ONNX expects are changing for no apparent reason. I only meant that I'm getting an email for every PR because I'm reviewing a lot of them. When I see PRs (from others) that only touch ONNX related parts then I often skip those, because I'm often not 100% up to date with ONNX discussions. I'm not the only person following this workflow, and it really makes life a lot easier for us.

**Comment by apaszke** [comment]
Actually where do C2 tests live?

**Comment by orionr** [comment]
@bddppq, quick question - are you ultimately looking to retire fb-universe? Just want to confirm what the long term plan is.

Test directory structure is a great question. At a minimum, I'd like to move all caffe2 tests into `test/caffe2`. Having them sprinkled like they are doesn't make sense in the longterm.

For ONNX tests, it sounds like these are integration tests across PyTorch, Caffe2, and ONNX. Given that, any interest in putting them under `test/integration/onnx`? Putting them at the root `test/` level likely doesn't make sense.

I have a small concern around checking in (relatively) large pbtxt files for testing. I agree that these look more like smoke tests. Have these tests, other than just executing, caught any regressions in the past? Could we do a smaller test, like that the result is correctly formed? Just a thought.

**Comment by orionr** [comment]
@apaszke C2 python tests right now live in https://github.com/pytorch/pytorch/tree/master/caffe2/python (files with _test.py) and some C++ tests exist at https://github.com/pytorch/pytorch/tree/master/caffe2/operators again with _test.cc

**Comment by bddppq** [comment]
Ok I will move all these tests and expect files into test/onnx

**Comment by bddppq** [comment]
@apaszke re. the large models expect files, I will let @ezyang who initially added those tests to decide. But IMO they are not that bad, the expect files are indeed big but the diff on them are normally small. We definitely want to have a way to test exporting whole & real models (for the purpose of testing the tracer/exporter).

**Comment by bddppq** [comment]
@apaszke @ezyang and I had offline discussions, here is how we are going to move forward:

1. put these tests into a separate directory, test/onnx
2. change the model exports tests to only do `verify` on the trace and the onnx models

I will do the refactoring (aka 2. above) in onnx-fb-universe first and then create another PR here to put them into `test/onnx`.

**Comment by ezyang** [comment]
I'm fine with dropping the large expect tests. We can build out the unit testing infrastructure to compensate.

**Pull request closed without merging**
