### PR TITLE
Revert "Revert D22360735: .circleci: Build docker images as part of C…

### PR DESCRIPTION
**Pull request by seemethere**
…I workflow"

This reverts commit 3c6b8a64964b0275884359dd6a5bf484655d8c7c.

### CODE REVIEW

**Comment by ezyang** [comment]
What's the status on this? It would be really great to see this get in; for example would have made life in #38796 a lot easier.

**Comment by ezyang** [comment]
We're going to partially land this PR by way of https://github.com/pytorch/pytorch/pull/41846

cc @mattip

**Comment by seemethere** [comment]
Am I doing something wrong here with tensorboard?

**Comment by ezyang** [comment]
No, you need the fix that we rolled up in https://github.com/pytorch/pytorch/pull/38796

This is also a good reason why you should keep up to date with your GitHub notifications ;)

**Review by malfet — APPROVED** [review]

**Comment by seemethere** [comment]
Currently blocked on https://github.com/pytorch/pytorch/issues/41680

**Pull request closed without merging**
