### PR TITLE
Add complex hooks for out of tree complex implementation.

### PR DESCRIPTION
**Pull request by ezyang**
This PR adds a hooks interface for registering types for complex
scalar types, and a sample implementation of the hook in
test_cpp_extensions.

The hook registration is patterned off of the existing CUDA hooks.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

CC @Roger-luo

### CODE REVIEW

**Review by ssnl — APPROVED** [review]
We discussed offline. In future patch(s), we will

1. Support `ATen/native` the tensor factory functions for complex numbers. Need to port 5~10 functions, e.g., `resize_`.
2. Default register our own bare bones complex type. Test that we can swap type pointers in when loading the complex extension.

**Review by gchanan — APPROVED** [review]

**Comment by SsnL** [comment]
errors look legit:
```

16:56:19 /tmp/torch_extensions/complex_registration_extension/main.cpp:29:64: error: expected class-name before '{' token
16:56:19          struct CPUComplexFloatType : public at::CPUTypeDefault {
16:56:19                                                                 ^
16:56:19 /tmp/torch_extensions/complex_registration_extension/main.cpp:34:22: error: 'at::ScalarType at::CPUComplexFloatType::scalarType() const' marked override, but does not override
16:56:19            ScalarType scalarType() const override;
16:56:19                       ^
16:56:19 /tmp/torch_extensions/complex_registration_extension/main.cpp:35:19: error: 'at::Backend at::CPUComplexFloatType::backend() const' marked override, but does not override
16:56:19            Backend backend() const override;
16:56:19                    ^
16:56:19 /tmp/torch_extensions/complex_registration_extension/main.cpp:36:24: error: 'const char* at::CPUComplexFloatType::toString() const' marked override, but does not override
16:56:19            const char * toString() const override;
16:56:19                         ^
16:56:19 /tmp/torch_extensions/complex_registration_extension/main.cpp:37:18: error: 'size_t at::CPUComplexFloatType::elementSizeInBytes() const' marked override, but does not override
16:56:19            size_t elementSizeInBytes() const override;
...
```

**Comment by ezyang** [comment]
@gchanan Yeah. We should probably do a global search replaced of `scalar_t` to `data_t`.

**Comment by Roger-luo** [comment]
@ezyang I had an old issue for renaming `real` and a python script for auto-renaming that might be helpful. 

https://github.com/pytorch/pytorch/issues/4575

**Comment by ezyang** [comment]
@Roger-luo The fix is landed on master :)

**Pull request closed without merging**
