### PR TITLE
Document get_device, fixes #8857

### LINKED ISSUE #8857: [docs] "get_device" is not documented
## Issue description

Raised earlier in https://github.com/pytorch/pytorch/issues/741 .

## System Info
- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source

### PR DESCRIPTION
**Pull request by vishwakftw**
cc: @SsnL @zou3519

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]
lgtm, but left a comment about explaining behavior for CPU tensors

**Review by zou3519 — DISMISSED** [review]
sorry, didn't see @soumith's comment, let's wait for @gchanan to reply

**Comment by SsnL** [comment]
@soumith I don't think we should deprecate this before patching all the `torch.cuda.*` (and maybe other fns) to also take in device objects.

**Comment by gchanan** [comment]
@SsnL seems reasonable.

**Comment by gchanan** [comment]
I think we should do that before the next release though, so we could punt on this PR.

**Comment by vishwakftw** [comment]
Can this be merged?

**Review by ezyang — APPROVED** [review]

**Comment by vishwakftw** [comment]
Can this be closed now?

**Pull request closed without merging**
