### PR TITLE
add Half/BFloat16 support for grid_sample on CPU

### PR DESCRIPTION
**Pull request by jiayisunx**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134812

Fix https://github.com/pytorch/pytorch/issues/127224.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by Skylion007** [comment]
Nice! I got stuck on figuring out the compile error with the blend, glad you were able to find a workaround.

**Review by Skylion007 — APPROVED** [review]

**Review by mingfeima — APPROVED** [review]

**Comment by Skylion007** [comment]
One failure is just a flake. @malfet Any idea what's going on with the other failure here?

**Comment by Skylion007** [comment]
Ah, seems like it's tripping up the CPU fallback? https://github.com/pytorch/pytorch/blob/929797dedbf23376123ce95230c01a7e3b71e130/aten/src/ATen/native/mps/operations/GridSampler.mm#L131

**Comment by Skylion007** [comment]
@malfet The GridSampler tests on MPS look really hacky, I think we may just need to add some xfails or something somewhere as other similar ops like Upsample etc are already in it.

**Comment by malfet** [comment]
> Ah, seems like it's tripping up the CPU fallback? Not sure what minor version MPS the runners are using?
> 
> https://github.com/pytorch/pytorch/blob/929797dedbf23376123ce95230c01a7e3b71e130/aten/src/ATen/native/mps/operations/GridSampler.mm#L131

There are running 13.2, so this is not the problem, looks like issue is simple the accuracy, so just add op to the list of FP16_LOW_PRECISION ops or just xfail that test for float16

**Comment by Skylion007** [comment]
Yeah, makes sense. Simlar ops like Upsample etc are already in the LOW_PRECISION list.

**Comment by Skylion007** [comment]
Just need to add fp16 version to low precision op list in the MPS consistency test framework.

**Pull request closed without merging**
