### PR TITLE
Ignore logging.Logger.* calls during dynamo export

### PR DESCRIPTION
**Pull request by thiagocrepaldi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #123410
* __->__ #123402

Follow up for https://github.com/pytorch/pytorch/pull/123368

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

### CODE REVIEW

**Comment by thiagocrepaldi** [comment]
There are 3 unrelated failures:

* Inductor pipeline:
```bash
Error: No such container: 
Error: Process completed with exit code 1.
```
* Docs pipeline
```bash
/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/ao/quantization/quantize.py:docstring of torch.ao.quantization.quantize.quantize:1: WARNING: duplicate object description of torch.ao.quantization.quantize, other instance in quantization, use :noindex: for one of them
```
* Another inductor pipeline
```bash
________ TestPatternMatcher.test_fuse_attention_all_patterns_serialized ________
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/inductor/test_pattern_matcher.py", line 1004, in test_fuse_attention_all_patterns_serialized
    self.assertEqual(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3624, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: String comparison failed: "rand[2815 chars]())\nalias_default = CallFunction(aten.alias.d[2921 chars]\n])" != "rand[2815 chars]())\nview_default_6 = CallFunction(aten.view.d[2922 chars]\n])"
Diff is 6591 characters long. Set self.maxDiff to None to see it.
Found mismatched pattern _sfdp_pattern_18_training. Run gen_attention_patterns.py
```

**Review by angelayi — COMMENTED** [review]
nice! looks good to me, but will let dynamo folks take a closer look @williamwen42 @anijain2305

**Review by williamwen42 — COMMENTED** [review]
@angelayi why can't we use the print reordering that you added?

**Comment by thiagocrepaldi** [comment]
> @angelayi why can't we use the print reordering that you added?

because it only supports functions. For methods, my extension just ignores the logs instead of reordering its prints for simplicity.

**Comment by williamwen42** [comment]
I think we can add print reordering to this by taking an approach similar to DebuggingVariable https://github.com/pytorch/pytorch/blob/b0c86a5bc1e1b2c1cd8f9e36a02789058ddf0add/torch/_dynamo/variables/misc.py#L884 - we can save the args received in `call_method` and codegen a method call in output_graph.py. Alternatively, we could try to break down the method call into a function call with the bound object.

We can do this in a followup PR.

**Review by williamwen42 — APPROVED** [review]

**Comment by DanilBaibak** [comment]
Hi @thiagocrepaldi! Sorry, I need to revert your PR because it breaks the trunk. [Here you can find more information](https://hud.pytorch.org/pytorch/pytorch/commit/75933ff5231b1caed333065ea9f5a847caa4cdaa) about the issue.

**Comment by thiagocrepaldi** [comment]
> Hi @thiagocrepaldi! Sorry, I need to revert your PR because it breaks the trunk. [Here you can find more information](https://hud.pytorch.org/pytorch/pytorch/commit/75933ff5231b1caed333065ea9f5a847caa4cdaa) about the issue.

Thanks. The issue was that a PR was merged first and it changed how the input names look in the printed graph module. Had to renamed `arg0_1` to `x` and it should pass now

Will confirm when CI finishes

**Comment by thiagocrepaldi** [comment]
2 unrelated ci errors. inductor and aot_inductor:
* inductor / rocm6.0-py3.8-inductor / test (inductor, 1, 1, linux.rocm.gpu.2, unstable) (push) Failing after 110m
```bash
AssertionError: Scalars are not close!

Expected 1.2005043029785156 but got 1.1449264287948608.
Absolute difference: 0.055577874183654785 (up to 1e-05 allowed)
Relative difference: 0.046295439379736576 (up to 1.3e-06 allowed)

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_ROCM=1 python test/distributed/_composable/fsdp/test_fully_shard_training.py -k test_train_parity_multi_group_eager
```

* inductor / cuda12.1-py3.10-gcc9-sm86 / test (aot_inductor_torchbench, 2, 2, linux.g5.4xlarge.nvidia.gpu) (push) Failing after 98m
```bash
AssertionError: Mutating module attribute nx during export.

from user code:
   File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/yolov3/yolo_models.py", line 238, in forward
    return self.forward_once(x)
  File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/yolov3/yolo_models.py", line 290, in forward_once
    yolo_out.append(module(x, out))
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/yolov3/yolo_models.py", line 188, in forward
    self.create_grids((nx, ny), p.device)
  File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/yolov3/yolo_models.py", line 150, in create_grids
    self.nx, self.ny = ng  # x and y grid size

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

TorchDynamo optimized model failed to run because of following error
fail_to_run
```

**Pull request closed without merging**
