### PR TITLE
Disable AMP when propagating fake tensors

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134583

Fixes https://github.com/pytorch/pytorch/issues/133974

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by isuruf** [comment]
The failing test is not reproducible locally. I skipped it for now. If you have any thoughts, I'm all ears.

**Review by eellison — COMMENTED** [review]
Nice debugging and i think the spirit of the pr is right.

**Review by eellison — COMMENTED** [review]
Nice debugging and i think the spirit of the pr is right. But I'm not sure FakeTensorProp is the right place for the fix.

After we've traced out the joint graph amp should be applied. Subsequently we can disable amp. I think this should be done in aot autograd. 

cc @bdhirsh

**Comment by leslie-fang-intel** [comment]
> Nice debugging and i think the spirit of the pr is right. But I'm not sure FakeTensorProp is the right place for the fix.
> 
> After we've traced out the joint graph amp should be applied. Subsequently we can disable amp. I think this should be done in aot autograd.
> 
> cc @bdhirsh

yean, `aot_dispatch_base` turns autocast off but `aot_dispatch_autograd` not. Not sure is there any specific reason for this implementation difference.

**Comment by isuruf** [comment]
Superceded by https://github.com/pytorch/pytorch/pull/138624

**Pull request closed without merging**
