### PR TITLE
Upgrade nightly wheels to rocm5.6

### LINKED ISSUE #104419: Support rocm 5.6 ASAP
### 🚀 The feature, motivation and pitch

"""
We’ve also seen tremendous interest from developers wanting to run the ROCm open software platform for AI and ML on our Radeon™ consumer and Radeon™ Pro workstation GPUs and have heard the community challenges with specific driver issues on unsupported GPUs. I’m pleased to say that we have fixed the reported issues in ROCm 5.6 and we are committed to expanding our support going forward.  

We plan to expand ROCm support from the currently supported[ AMD RDNA 2 workstation GPUs: the Radeon Pro v620 and w6800](https://docs.amd.com/en/docs-5.0.2/CHANGELOG.html#radeon-pro-v620-and-w6800-workstation-gpus) to select AMD RDNA 3 workstation and consumer GPUs. Formal support for RDNA 3-based GPUs on Linux is planned to begin rolling out this fall, starting with the 48GB Radeon PRO W7900 and the 24GB Radeon RX 7900 XTX, with additional cards and expanded capabilities to be released over time.

"""

pd: https://community.amd.com/t5/rocm/new-rocm-5-6-release-brings-enhancements-and-optimizations-for/ba-p/614745/jump-to/first-unread-message

ROCm 5.6 also brings performance improvements for OpenAI Triton, CuPy, and HIP Graph.

### Alternatives

_No response_

### Additional context

_No response_

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### PR DESCRIPTION
**Pull request by BLOrange-AMD**
Tests https://github.com/pytorch/builder/pull/1442

Fixes #104419

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
ROCm/libtorch wheels built successfully using the PR branch for PR https://github.com/pytorch/builder/pull/1442.

**Comment by jithunnair-amd** [comment]
@BLOrange-AMD Builder PR is merged, can you please update this PR removing the temporary changes to use that PR branch?

**Comment by jithunnair-amd** [comment]
@atalman @malfet Ready to merge. ROCm binary CI runs passed.

**Review by atalman — APPROVED** [review]
lgtm

**Comment by Murat-U-Saglam** [comment]
Hi,

I have been following this thread. How can I locally pull ROCM 5.6 version support?

`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.6` seems to not be working

**Comment by voidanix** [comment]
> How can I locally pull ROCM 5.6 version support?

Try again, the wheels [should now be available](https://download.pytorch.org/whl/nightly/rocm5.6/torch/).

**Comment by Murat-U-Saglam** [comment]
Works great! Thank you!

**Comment by javiersc1** [comment]
Same issue as @Murat-U-Saglam  above, unsure how to proceed.

**Comment by kuroy** [comment]
https://download.pytorch.org/whl/nightly/rocm5.6/ contains "torch" but doesn't contains "torchvision" , "torchaudio" etc, at current time(my comment's timestamp).
In other hand, https://download.pytorch.org/whl/nightly/rocm5.5/ contains "torch" "torchaudio" "torchvison" and "torchtext", so you'll succeed if you change "--index-url .." part to rocm 5.5.
You should wait until those libraries for rocm5.6 if you really requires them, or remove "torchvision" and "torchaudio" from pip3 install.. command line.

**Comment by Murat-U-Saglam** [comment]
Is there a Pull request we can follow for PyTorch vision using rocm 5.6?

**Comment by jithunnair-amd** [comment]
> Is there a Pull request we can follow for PyTorch vision using rocm 5.6?

https://github.com/pytorch/test-infra/pull/4401

**Pull request closed without merging**
