### PR TITLE
Add decomposition for aten.squeeze.dims op

### PR DESCRIPTION
**Pull request by vivekkhandelwal1**
Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>

### CODE REVIEW

**Comment by davidberard98** [comment]
I see some CI failures, can you take a look at those first?

**Review by jansel — CHANGES_REQUESTED** [review]
Please fix CI errors.

**Comment by vivekkhandelwal1** [comment]
@jansel @davidberard98 Could you guys please tell me, why is the CI failing?

**Comment by jansel** [comment]
Errors are here: https://hud.pytorch.org/pr/97020

Looks like infinite recursion on one from L3587.

**Comment by vivekkhandelwal1** [comment]
I have a question, can a decomposition be added for ops from `prims` namespace? @jansel @davidberard98

**Comment by vivekkhandelwal1** [comment]
> Errors are here: https://hud.pytorch.org/pr/97020
> 
> Looks like infinite recursion on one from L3587.

Yeah, I don't understand why that's happening. Is there a command to run these tests locally or what's the efficient way to debug these errors? I don't have much idea about this.

**Comment by jansel** [comment]
> I have a question, can a decomposition be added for ops from `prims` namespace? @jansel @davidberard98

Yes, you can decompose prims -- but those should go in `_inductor/decomposition.py`

**Comment by jansel** [comment]
> > Errors are here: https://hud.pytorch.org/pr/97020
> > Looks like infinite recursion on one from L3587.
> 
> Yeah, I don't understand why that's happening. Is there a command to run these tests locally or what's the efficient way to debug these errors? I don't have much idea about this.

Yes, you can run them locally.  I usually do:
```
pytest <filename> -vsk <test_name>
```

**Comment by vivekkhandelwal1** [comment]
> Please fix CI errors.

Finally, the CI is green. Can we merge this now?

**Comment by vivekkhandelwal1** [comment]
This is my other PR: https://github.com/pytorch/pytorch/pull/93919, waiting for approval for a long time. Can you please review that as well?

**Review by jansel — APPROVED** [review]

**Comment by vivekkhandelwal1** [comment]
> This is my other PR: https://github.com/pytorch/pytorch/pull/93919, waiting for approval for a long time. Can you please review that as well?

@jansel Also, could you please take a look at this?

**Comment by vivekkhandelwal1** [comment]
> > > This is my other PR: #93919, waiting for approval for a long time. Can you please review that as well?
> > 
> > @jansel Also, could you please take a look at this?
> 
> I don't know enough about those files to properly review.  Perhaps @eellison could look at https://github.com/pytorch/pytorch/pull/93919

That would be helpful!

**Comment by vivekkhandelwal1** [comment]
Thank you very much @jansel for helping me get this PR merged.

**Pull request closed without merging**
