### PR TITLE
[ROCm]Enable Faster_Load_Store  for FusedSGD

### LINKED ISSUE #117599: [rocm] Enable faster load of fused-sgd
Currently it's turned off to avoid the hang of test_cuda 

              I don't have an explanation yet, but since the kernel had two potential paths (`use_faster_load_store`), I used a preprocessor #ifdef for rocm to force the other path.  This worked.  So there was something wrong with using the faster load store path.  This is my diff that worked for ROCm

```diff
diff --git a/aten/src/ATen/native/cuda/FusedSgdKernel.cu b/aten/src/ATen/native/cuda/FusedSgdKernel.cu
index a00b47ff79..0c52ee5783 100644
--- a/aten/src/ATen/native/cuda/FusedSgdKernel.cu
+++ b/aten/src/ATen/native/cuda/FusedSgdKernel.cu
@@ -87,6 +87,7 @@ struct FusedSgdMathFunctor {
         init_args<depth>(args, tl, chunk_idx, chunk_size, tensor_loc)};
     n -= chunk_idx * chunk_size;

+#ifndef USE_ROCM
     const auto use_faster_load_store =
         (n % kILP == 0) && (chunk_size % kILP == 0) && all_aligned;
     if (use_faster_load_store) {
@@ -116,7 +117,9 @@ struct FusedSgdMathFunctor {
           load_store(args[2], r_args[2], i_start, 0);
         }
       }
-    } else {
+    } else
+#endif
+    {
       for (auto i_start = 0; i_start < n && i_start < chunk_size;
            i_start += blockDim.x * kILP) {
         load_args<depth>(r_args, args, i_start, chunk_size, n);
```

_Originally posted by @jeffdaily in https://github.com/pytorch/pytorch/issues/116585#issuecomment-1887886009_
            

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### PR DESCRIPTION
**Pull request by petrex**
Fixes https://github.com/pytorch/pytorch/issues/117599

The reported hang test : `test_cuda.py::TestCuda::test_grad_scaling_autocast_fused_optimizers` is passing with this PR

HSA Async copy / host wait on completion signal is resolved in MultiTensorApply.cuh 

```
:4:command.cpp              :347 : 8881368803196 us: [pid:1268211 tid:0x7f5af80d7180] Command (InternalMarker) enqueued: 0xc4e2070
:4:rocvirtual.cpp           :556 : 8881368803201 us: [pid:1268211 tid:0x7f5af80d7180] Host wait on completion_signal=0x7f5967df3e00
:3:rocvirtual.hpp           :66  : 8881368803209 us: [pid:1268211 tid:0x7f5af80d7180] Host active wait for Signal = (0x7f5967df3e00) for -1 ns
```

### CODE REVIEW

**Review by jeffdaily — APPROVED** [review]
If we have a clean CI signal (no hang) then LGTM.

**Comment by petrex** [comment]
`TestOneOffModelExportResult::test_logging_logger` failure is not relevant.
`test_grad_scaling_autocast_fused_optimizers` is passing on ROCm 6.1.  Once CI upgraded we are good to go.

**Comment by pruthvistony** [comment]
Need to wait for CI upgrade to ROCm 6.1.

**Pull request closed without merging**
