### PR TITLE
Updated the documentation of torch.sparse to make it more readable.

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
Made a small change in docs of [`torch.sparse`](https://pytorch.org/docs/stable/sparse.html#why-and-when-to-use-sparsity). By removing the redundant "stores" word.

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]

**Comment by Sai-Suraj-27** [comment]
@cpuhrsch Can you please review this?

**Review by cpuhrsch — APPROVED** [review]

**Comment by Sai-Suraj-27** [comment]
@cpuhrsch sir, any idea why the 1 test is failing?

**Comment by cpuhrsch** [comment]
@Sai-Suraj-27 - Not sure. Can you try rebasing? Can you also please remove any changes unrelated to the sparse documentation?

**Comment by Sai-Suraj-27** [comment]
> @Sai-Suraj-27 - Not sure. Can you try rebasing? Can you also please remove any changes unrelated to the sparse documentation?

Sure, sir. Will do it right away 👍.

**Comment by Sai-Suraj-27** [comment]
@cpuhrsch sir, Can I close this PR, and open a new one with only the proper required changes? Since, for some reason 1 of the tests is always failing.

**Pull request closed without merging**
