### PR TITLE
[FSDP2] Fixed fp32 param dtype/bf16 reduce dtype test

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #125191
* __->__ #125190

The unit test for fp32 `param_dtype` and bf16 `reduce_dtype` was disabled. This PR debugs the issue and identifies the root cause as numeric differences between NCCL bf16 all-reduce vs. bf16 reduce-scatter. We address this by having the baseline use reduce-scatter -> all-gather to implement all-reduce.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

### CODE REVIEW

**Review by weifengpy — APPROVED** [review]
nice! i will show off when people mention again about all-reduce = all-gather + reduce-scatter

**Review by wanchaol — APPROVED** [review]
This is actually very surprising to me 🤔

**Comment by awgu** [comment]
@wanchaol Even worse, it is not an issue with world size 2 but starts being an issue at world size 4. It seems like a floating-point associativity issue, perhaps from tree vs. ring algo.

**Comment by awgu** [comment]
Failures were all from the open registration test.

**Pull request closed without merging**
