### PR TITLE
Add private helper for determining which version of FA2 closest matches kernel version

### PR DESCRIPTION
**Pull request by drisspg**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by mikaylagawarecki — COMMENTED** [review]
Stamping to unblock, but somewhat curious why this is needed / what "closest matching" means 😛

**Review by mikaylagawarecki — APPROVED** [review]

**Comment by drisspg** [comment]
@mikaylagawarecki There are some minor tweaks compared to the open source version, as well this was needed to unblock some folks from xformers

**Pull request closed without merging**
