### PR TITLE
fix external codegen kernel error checking

### PR DESCRIPTION
**Pull request by bdhirsh**
Fixes https://github.com/pytorch/pytorch/issues/84987. I followed the repro steps from the issue (changed `empty_symint` to `empty_symint2` and confirmed that and error gets raised.

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #85043
* __->__ #85029

### CODE REVIEW

**Comment by antoniojkim** [comment]
I can confirm that these changes work to fix the issue in Torch-MLIR. Thanks!

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Some unit tests for this would be good

**Pull request closed without merging**
