### PR TITLE
[BE]: Update cudnn_frontend submodule to 1.8.0

### PR DESCRIPTION
**Pull request by Skylion007**
Update cudnn frontend. Let's see what breaks

@eqy

### CODE REVIEW

**Comment by Skylion007** [comment]
@eqy Do not see any immediate issues with the cudnn_frontend fixes

**Review by eqy — APPROVED** [review]

**Comment by eqy** [comment]
Thanks! Let's try to merge #138725 first or check if that test passes with 1.8.0?

**Pull request closed without merging**
