### PR TITLE
[ROCm] Enable test_instantiator, test_type_hints

### PR DESCRIPTION
**Pull request by jaglinux**
Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>

### CODE REVIEW

**Comment by jaglinux** [comment]
cc @amathews-amd @pruthvistony

**Review by malfet — APPROVED** [review]
LGTM, but please land only after ROCm tests are passing

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
The 2 failure jobs doesnt seem to be related to this change. So it is good to be merged.

**Pull request closed without merging**
