### PR TITLE
Removing cuda 11.3 nightly builds

### PR DESCRIPTION
**Pull request by atalman**
Removing cuda 11.3 nightly builds

### CODE REVIEW

**Review by malfet — COMMENTED** [review]
Please start by removing domain builds...

**Review by weiwangmeta — APPROVED** [review]
LGTM!

**Comment by atalman** [comment]
> Please start by removing domain builds...

Sounds good. Will post PR for domains now. Shipping ETA Sept 13, 8:30AM EST, domains + core.

**Comment by seemethere** [comment]
> > Please start by removing domain builds...
> 
> Sounds good. Will post PR for domains now. Shipping ETA Sept 13, 8:30AM EST, domains + core.

Can we link the domains PRs to this original PR as well

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
