### PR TITLE
fix error message

### LINKED ISSUE #44704: Error message concerning dtype GRU not identical between devices
## 🐛 Bug

In 1.6, a bug exists where a GRU accepts an input `float32` anc a hidden state `float64` but only when on GPU. This will lead to unexpected, explosive results with very large or very small values.

```python
import torch
from torch import nn

USE_GPU = True

torch.manual_seed(2809)
torch.cuda.manual_seed(2809)


device = torch.device("cuda" if USE_GPU else "cpu")
rnn = nn.GRU(10, 10).to(device)
for _ in range(100):
    input = torch.randn(1, 3, 10).to(device)
    h0 = torch.randn(1, 3, 10).double().to(device)
    print("input dtype", input.dtype)
    print("h0 dtype", h0.dtype)
    output, hn = rnn(input, h0)
    print(output.abs().max(), hn.abs().max())
    print()
```
As @ptrblck found in [this topic](https://discuss.pytorch.org/t/is-it-required-that-input-and-hidden-for-gru-have-the-same-dtype-float32/96221), this bug seems to have been solved in 1.7 nightlies. However, an improvement can still be made: The error message is not the same between devices:

- CPU: RuntimeError: expected scalar type Float but found Double
- GPU: RuntimeError: Input and parameter tensors are not the same dtype, found input tensor with Double and parameter tensor with Float

It would probably be better to have identical error messages across devices concerning the same issue.

As said, the original bug was in 1.6 but seems to have been fixed in 1.7 nightlies. The error message in the nightlies could still be improved between devices, though.

Env
---

PyTorch version: 1.7.0.dev20200912+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 440.95.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.0.dev20200912+cu101

### PR DESCRIPTION
**Pull request by guol-fnst**
Fixes #44704

### CODE REVIEW

**Comment by gchanan** [comment]
thanks for the PR.  However, the new error message seems worse than the old one, even if it is consistent.  Can we change the *other* error message to this one?

**Comment by guol-fnst** [comment]
> thanks for the PR. However, the new error message seems worse than the old one, even if it is consistent. Can we change the _other_ error message to this one?

At first I intended to modify the error message for the CPU branch.  A marco is defined to display this message (https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/templates/TensorMethods.cpp#L147). 
If i modify the marco, some other error message may be infulenced. 
Besides, the logic for GPU(https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/RNN.h#L49) contains more details about the error.
So should I just modify the CPU's error message formate or both to make them consistent?
Thanks !

**Comment by guol-fnst** [comment]
Hi @gchanan 
I have modified the error message. Could you please help to reveiw this PR? 
Thanks!!

**Comment by guol-fnst** [comment]
Hi @gchanan
I have modified the error message. Could you please help to reveiw this PR?
Thanks!!

**Comment by guol-fnst** [comment]
@ngimel
 Could you please help to reveiw this PR?
Thanks!

**Pull request closed without merging**
