### PR TITLE
Fix ExecuTorch CI after landing #6564

### PR DESCRIPTION
**Pull request by huydhn**
After landing https://github.com/pytorch/executorch/pull/6564, we need to update the pinned ExecuTorch commit on PyTorch is fix the regression on PyTorch side.  The change to `.ci/docker/common/install_executorch.sh` is needed because it's how the dependencies are setup on ExecuTorch CI now.

### CODE REVIEW

**Comment by huydhn** [comment]
@guangy10 @larryliu0820 After https://github.com/pytorch/executorch/pull/6564, we need this change to fix the regression on PyTorch side.  However, I think during the gap when PyTorch wasn't installed correctly, some changes has already landed that doesn't work with ExecuTorch yet.  Specifically, I'm referring to this failure https://github.com/pytorch/pytorch/actions/runs/11676105984/job/32512808907?pr=139700#step:22:7900

```
ERROR examples/models/llama3_2_vision/preprocess/test_preprocess.py
FAILED kernels/quantized/test/test_out_variants.py::TestOutVariants::test_add_to_out_variant - AttributeError: The underlying op of 'quantized_decomposed.add' has no overload name 'out'
FAILED kernels/quantized/test/test_out_variants.py::TestOutVariants::test_choose_qparams_tensor_to_out_variant - AttributeError: The underlying op of 'quantized_decomposed.choose_qparams' has no overload name 'Tensor_out'
FAILED kernels/quantized/test/test_out_variants.py::TestOutVariants::test_dequantize_per_channel_to_out_variant - AttributeError: The underlying op of 'quantized_decomposed.dequantize_per_channel' has no overload name 'out'
FAILED kernels/quantized/test/test_out_variants.py::TestOutVariants::test_dequantize_per_tensor_tensor_to_out_variant - AttributeError: The underlying op of 'quantized_decomposed.dequantize_per_tensor' has no overload name 'Tensor_out'
FAILED kernels/quantized/test/test_out_variants.py::TestOutVariants::test_dequantize_per_tensor_to_out_variant - AttributeError: The underlying op of 'quantized_decomposed.dequantize_per_tensor' has no overload name 'out'
FAILED kernels/quantized/test/test_out_variants.py::TestOutVariants::test_mixed_linear_to_out_variant - AttributeError: The underlying op of 'quantized_decomposed.mixed_linear' has no overload name 'out'
FAILED kernels/quantized/test/test_out_variants.py::TestOutVariants::test_mixed_mm_to_out_variant - AttributeError: The underlying op of 'quantized_decomposed.mixed_mm' has no overload name 'out'
FAILED kernels/quantized/test/test_out_variants.py::TestOutVariants::test_quantize_per_channel_to_out_variant - AttributeError: The underlying op of 'quantized_decomposed.quantize_per_channel' has no overload name 'out'
FAILED kernels/quantized/test/test_out_variants.py::TestOutVariants::test_quantize_per_tensor_tensor_to_out_variant - AttributeError: The underlying op of 'quantized_decomposed.quantize_per_tensor' has no overload name 'Tensor_out'
FAILED kernels/quantized/test/test_out_variants.py::TestOutVariants::test_quantize_per_tensor_to_out_variant - AttributeError: The underlying op of 'quantized_decomposed.quantize_per_tensor' has no overload name 'out'
FAILED extension/pybindings/test/test_pybindings.py::PybindingsTest::test - RuntimeError: Missing out variants: {'quantized_decomposed::dequantize_per_tensor', 'quantized_decomposed::add', 'quantized_decomposed::quantize_per_tensor'}
```

Is there a way to ignore them to land this change, then follow up with proper fixes later?  I want to land this change as early as possible to avoid further misses.

**Comment by huydhn** [comment]
Chat with @larryliu0820, let's land this and mark this as unstable for a forward fix

**Review by larryliu0820 — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by huydhn** [comment]
@larryliu0820  I think I understand what happens now. The test that is failing `examples/models/llama3_2_vision/preprocess/test_preprocess.py` requires torchtune and torchao, otherwise, it would fail.  It makes sense now as the quantized ops are from torchao.  From what I see, both repos are currently not included in [https://github.com/.../blob/main/install_requirements.py](https://github.com/pytorch/executorch/blob/main/install_requirements.py), so I assume that they are optional dependency.  Given that, I think it's better to skip the test if torchtune and ao are not available and run it only when they are installed.  We need that flexibility when running ET tests on PT CI.

`pytest -v examples/models/llama3_2_vision/preprocess/test_preprocess.py` works locally for me when I have them installed.

**Pull request closed without merging**
