### PR TITLE
Enable Mypy Checking for torch/_inductor/fx_passes/fuse_attention.py

### PR DESCRIPTION
**Pull request by Cyril-Anto**
Fixes #105230 

Summary:

As suggested in https://github.com/pytorch/pytorch/issues/105230 mypy checking is enabled in torch/_inductor/fx_passes/fuse_attention.py

After Fix:

mypy --follow-imports=skip torch/_inductor/fx_passes/fuse_attention.py Success: no issues found in 1 source file

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by mikaylagawarecki — APPROVED** [review]
Seems like Ed meant to approve :)

**Comment by mikaylagawarecki** [comment]
@Cyril-Anto  could you fix lint please? 

To fix the failing lint job running `setup_lint` and `quicklint` from your local pytorch directory and following the corresponding instructions should be sufficient, see [here](https://github.com/pytorch/pytorch/blob/4721553431e968ee5e90753346d92252cce98e84/Makefile#L25-L34). Let me know if you need more help

**Comment by Cyril-Anto** [comment]
@mikaylagawarecki Fixed the lint failure can you please start the merge again?

**Pull request closed without merging**
