### PR TITLE
Fix to preserve tensor wrapper subclass dtype through multiprocessing serialization

### LINKED ISSUE #125583: dataloader returns wrong dtype of tensor subclass when used in multiple processes
Minimal repro (thanks to Matthias from slack):

```
    from torch.testing._internal.two_tensor import TwoTensor

    a = torch.randperm(5)
    b = torch.randperm(5)

    data = TwoTensor(a, b)
    print(data.dtype)  # int64

    loader = torch.utils.data.DataLoader(
        [data, data],
        batch_size=2,
        num_workers=2,
        collate_fn=lambda x: x,
    )
    for batch in loader:
        print(batch[0].dtype)  # float32
```

The printed output is below. You can see the dtype of the tensor subclass is `int64`, but loading it from another process in the dataloader prints `float32`. This also does not repro when using single process (setting `num_workers=0`):
```
torch.int64
torch.int64
torch.int64
torch.float32
```

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125615

Fixes #125583

cc @ezyang @msaroufim @albanD

### CODE REVIEW

**Comment by jbschlosser** [comment]
Feels like for full correctness we should ferry along everything that `_make_wrapper_subclass()` accepts, no?

```python
_make_wrapper_subclass(
    PyObject* cls,
    SymIntArrayRef size,
    SymIntArrayRef? strides=None,
    SymInt? storage_offset=None,
    MemoryFormat? memory_format=None,  # not passed
    ScalarType dtype=None,
    Layout layout=torch.strided,
    Device device=None,
    bool pin_memory=False,  # not passed
    bool requires_grad=False,
    c10::string_view? dispatch_sizes_strides_policy=None,  # not passed
    bool dispatch_device=False,  # not passed
    bool dispatch_layout=False,  # not passed
    DispatchKeySet _extra_dispatch_keys=None  # not passed
)
```

All of the args that are not passed (with the exception of `pin_memory()`) are not directly queryable atm, to my knowledge. So we'd have to expose them somehow.

**Review by albanD — APPROVED** [review]
Ho that means the same happens with serialization with torch.save/load :o 
That might explain some issues @jerryzh168  was seeing?

**Comment by jbschlosser** [comment]
From offline discussion with @albanD: full fix regarding other `_make_wrapper_subclass()` args requires serialization format changes and is out of scope of this PR.

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
