### PR TITLE
[CUDA][complex] Define `LIBCUDACXX_ENABLE_SIMPLIFIED_COMPLEX_OPERATIONS` in CUDA build

### PR DESCRIPTION
**Pull request by eqy**
An upcoming CUDA release will migrate to CCCL, and we need this define to preserve current complex behavior: https://nvidia.github.io/libcudacxx/standard_api/numerics_library/complex.html

CC @miscco @ptrblck 

cc @ptrblck @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

### CODE REVIEW

**Comment by eqy** [comment]
Closing as this fix doesn't seem to work upon closer inspection :/

**Comment by miscco** [comment]
Are there any failed jobs? I only see canceled ones

**Comment by eqy** [comment]
I cancelled the jobs as the issue still occurs locally with the define. I was previously assuming some of the issues were fixed but it was just due to tests being skipped (#117072).

**Comment by eqy** [comment]
Reopening due to recommendation from CCCL

**Review by ezyang — APPROVED** [review]
Okey dokey

**Review by malfet — APPROVED** [review]
Please add some comment to CMake with reference to libcudacxx command line, but otherwise LGTM

**Pull request closed without merging**
