### PR TITLE
Fix log_softmax and softmax if any dimension is 0-d

### LINKED ISSUE #17262: CPU log_softmax on [N, 0] tensor is broken
## 🐛 Bug

```py
>>> import torch
>>> import torch.nn.functional as F
>>>
>>> x = torch.randn(10, 0, requires_grad=True)
>>> y = F.log_softmax(x, dim=1)

[1]    24095 floating point exception (core dumped)  python
```

### PR DESCRIPTION
**Pull request by bhushan23**
- Test added
- test_dim_function_empty: softmax and log_softmax on last dimension

fixes: #17262

### CODE REVIEW

**Review by ssnl — APPROVED** [review]
@pytorchbot merge this please

**Review by apaszke — CHANGES_REQUESTED** [review]
Instead of modifying device-specific kernels, can't we skip those cases in top-level functions?

**Comment by ezyang** [comment]
@bhushan23 I agree with @apaszke. Do you think you could make this change?

**Comment by bhushan23** [comment]
done

**Review by gchanan — APPROVED** [review]

**Review by apaszke — APPROVED** [review]

**Comment by apaszke** [comment]
Would be nice to add test cases for this

**Comment by bhushan23** [comment]
> Would be nice to add test cases for this

Only missing test case in forward pass was aceesing last dimension (which we have added now)
Now, since we are returning 0-d tensor in forward pass, we will have 0-d tensor during backward and autograd give Runtime error `RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`

Adding test case to ensure future coverage.

**Review by soumith — APPROVED** [review]

**Pull request closed without merging**
