### PR TITLE
[ATen] Remove ATen.h includes from transformers

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #110199

The kernel files here in particular are quite slow to compile and don't use anything from  `ATen.h`.

### CODE REVIEW

**Comment by lezcano** [comment]
tagging @malfet as a reviewer

**Comment by Skylion007** [comment]
@peterbell10 Many of these kernels are regularly synched from the https://github.com/facebookresearch/xformers library. You should submit this PR to xformers first so that your changes are accidentally overwritten later.

**Comment by peterbell10** [comment]
@Skylion007 I reverted the change to `generate_kernels.py` and add the flag in the build system instead, I also see that the kernel header file doesn't include `ATen.h` in the `xformers` version so that change seems fine.
https://github.com/facebookresearch/xformers/blob/23cc20a29e5a88e06932b9b0a6a6fd23fa77bc54/xformers/csrc/attention/cuda/fmha/kernel_forward.h#L10-L13

All of the other files seem to be PyTorch-only so I don't think any change is required there.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
