### PR TITLE
Fix scalar type resolution for optional tensor

### PR DESCRIPTION
**Pull request by thiagocrepaldi**
When TorchScript Value has an optional tensor, `dtype()` or `scalarType()` is not available and raise (by design).

The symbolic `_op_with_optional_float_cast` must check whether the tensor is otpional or not before calling the scalar type resolution API. This PR fixes that

### CODE REVIEW

**Comment by thiagocrepaldi** [comment]
@pytorch merge -g

**Review by abock — APPROVED** [review]

**Review by shubhambhokare1 — APPROVED** [review]
LGTM! Fix lint issues?

**Pull request closed without merging**
