### PR TITLE
add multi swa support for custom device

### PR DESCRIPTION
**Pull request by heidongxianhua**
Fixes #ISSUE_NUMBER
add multi swa support for custom device

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
seems okay--have you verified there are no other spots where we'd need to add _get_foreach_kernels_supported_devices()?

**Comment by heidongxianhua** [comment]
> seems okay--have you verified there are no other spots where we'd need to add _get_foreach_kernels_supported_devices()?

yeah I have checked again, there is no need to add elsewhere now.

**Pull request closed without merging**
