### PR TITLE
[WIP] C++ tensor multi-dim indexing: add index() and index_put_() overloads, and simple indexing tests

### PR DESCRIPTION
**Pull request by yf225**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #30427 C++ tensor multi-dim indexing: more indexing tests
* #30426 Add assert_tensor_equal and assert_tensor_not_equal to test/cpp/api/support.h
* **#30425 C++ tensor multi-dim indexing: add index() and index_put_() overloads, and simple indexing tests**
* #30424 C++ tensor multi-dim indexing: add Slice / TensorIndex

This PR adds three items:
- **1st item**: `ArrayRef<TensorIndex>` and `std::initializer_list<TensorIndex>` overloads for `Tensor::index` and `Tensor::index_put_`, to be used specifically for multi-dim indexing purpose. 

Reason for this design:
* `Tensor::index` and `Tensor::index_put_` are both existing tensor APIs, and they currently (before this PR) only accept a list of tensors (i.e. `ArrayRef<Tensor>`) as indices. If we change their signatures to also accept non-tensors as indices (i.e. `ArrayRef<TensorIndex>`, and `TensorIndex` is convertible from `Tensor` / `Slice` / `None` / `Ellipsis`), it would slow down the original code path (since now it has to go through more steps), which is undesirable.
    
    To get around this problem, the proposed solution is to keep the original `ArrayRef<Tensor>` overload, and add `ArrayRef<TensorIndex>` and `std::initializer_list<TensorIndex>` overloads to `Tensor::index` and `Tensor::index_put_`. This way, the original code path won’t be affected, and the tensor multi-dim indexing API is only used when the user explicitly pass an `ArrayRef<TensorIndex>` or a braced-init-list of `TensorIndex`-convertible types to `Tensor::index` and `Tensor::index_put_` .
    
    Note that the above proposed solution would still affect perf for the user’s original `Tensor::index` or `Tensor::index_put_` call sites that use a braced-init-list of tensors as input, e.g. `tensor.index({...})` or `tensor.index_put_({...}, value)`, since now such function calls would take the multi-dim indexing path instead of the original advanced indexing path. However, there are only two instances of this in our codebase (one in ATen cpp test, one in a C++ API nn init function), and they can be easily changed to explicitly use `ArrayRef<Tensor>` as input (I changed them in this PR). For external user’s code, since this is part of the C++ frontend which is still considered experimental, we will only talk about this change in the release note, and ask users to switch to using `ArrayRef<Tensor>` explicitly if they want to keep using the original advanced indexing code path.

- **2nd item**: Mechanisms for parsing `ArrayRef<TensorIndex>` indices and performing indexing operations, mirroring the functions in `torch/csrc/autograd/python_variable_indexing.cpp`. We will be able to merge parts of the C++ and Python indexing code paths in the future, after making sure there is no perf regression when doing so.
- **3rd item**: Simple tests to demonstrate that the `Tensor::index()` and `Tensor::index_put_()` APIs work. I will add more tests after the first few PRs are reviewed.

Differential Revision: [D18695898](https://our.internmc.facebook.com/intern/diff/D18695898)

### CODE REVIEW

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit 9536352:
* **2/2** failures introduced in this PR



Here are the [reasons each build failed](https://dr.pytorch.org/commit-details.html?sha1=95363526c5d239c4b05662ae820d87b45fc41908):

### 2 failures recognized by patterns:
####  pytorch_linux_xenial_py3_6_gcc5_4_test
**Step:** Test
```
Nov 25 23:40:40 [  FAILED  ] TensorIndexingTest.TensorIndex
```
####  pytorch_linux_xenial_py2_7_9_test
**Step:** Test
```
Nov 25 23:47:46 [  FAILED  ] TensorIndexingTest.TensorIndex
```


---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Comment by ezyang** [comment]
You don't have any reviewers on this PR

**Comment by ezyang** [comment]
> We will be able to merge parts of the C++ and Python indexing code paths in the future, after making sure there is no perf regression when doing so.

Is the concern about perf regression because you have to convert Python index objects into C++ index objects, and then call the C++ indexing objects? This seems very unlikely to cause a regression, and my preference would then be to deduplicate the code from the getgo (so we don't forget to do it later.)

**Comment by ezyang** [comment]
If you agree that we should immediately deduplicate, I will defer reviewing until the Python equivalent code is deleted.

**Comment by yf225** [comment]
> > We will be able to merge parts of the C++ and Python indexing code paths in the future, after making sure there is no perf regression when doing so.
> 
> Is the concern about perf regression because you have to convert Python index objects into C++ index objects, and then call the C++ indexing objects? This seems very unlikely to cause a regression, and my preference would then be to deduplicate the code from the getgo (so we don't forget to do it later.)

Yes that is the concern. I feel that we still need to do some benchmarking to know the effect of the deduplication, but the multi-dim indexing API is a good addition to the C++ frontend regardless of whether we would be able to deduplicate at the end. I will also make sure to have deduplication as the follow-up PR after the patches for C++ multi-dim indexing are merged.

**Comment by ezyang** [comment]
> multi-dim indexing API is a good addition to the C++ frontend regardless of whether we would be able to deduplicate at the end

OK... but we've lacked multi-dim indexing in C++ for quite a long time, it won't kill anyone if it takes a few more weeks. So if we're not in a rush, let's frontload this (rather than risk this not happening, and then we never get back to it.)

**Comment by yf225** [comment]
This PR is superseded by https://github.com/pytorch/pytorch/pull/32841.

**Pull request closed without merging**
