### PR TITLE
CUDA BFloat activations 1

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Comment by ngimel** [comment]
Do you think test error is related? Can you rebase and see if it goes away?

**Comment by zasdfgbnm** [comment]
rebased

**Comment by ngimel** [comment]
Yeah, turns out this test is broken now.

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Sorry, can you please rebase again to get signal from cuda tests? Yesterday's breakage is fixed.

**Comment by zasdfgbnm** [comment]
rebased

**Pull request closed without merging**
