### PR TITLE
Convert test_recursive_cse to use Filecheck inline annotations.

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#18307 Convert test_recursive_cse to use Filecheck inline annotations.**
* #18306 [Filecheck] Add a feature to parse check annotations from string.
* #18305 Add python bindings for parseIR.
* #18303 Remove empty file (actual file_check.cpp resides in torch/csrc/jit/testing)

Differential Revision: [D14586000](https://our.internmc.facebook.com/intern/diff/D14586000)

### CODE REVIEW

**Comment by suo** [comment]
@eellison do you think it's better to port tests like this to C++? My ideal is that only frontend tests are in python.

**Review by suo — APPROVED** [review]
accepting to unblock, seems good to me

**Comment by ZolotukhinM** [comment]
The last part of the stack was committed in #19032.

**Pull request closed without merging**
