### PR TITLE
[ONNX] Deprecate operators.py

### PR DESCRIPTION
**Pull request by justinchuby**
Deprecate `torch.onnx.operators` because it's only for backwards compatibility

### CODE REVIEW

**Review by BowenBao — COMMENTED** [review]
hmm is this not bc breaking?

**Comment by justinchuby** [comment]
Looks like its used somewhere else. Taking a closer look

**Comment by justinchuby** [comment]
Hmm. Looks like its still used in caffe2 models. I will add a deprecation message instead?

**Review by BowenBao — APPROVED** [review]
lgtm

**Comment by justinchuby** [comment]
@weiwangmeta could you post the errors from D40797126? Thanks!

**Comment by weiwangmeta** [comment]
> @weiwangmeta could you post the errors from D40797126? Thanks!

Sorry for the delayed response. The errors stemmed from 
https://github.com/facebookresearch/fairseq/blob/main/fairseq/modules/sinusoidal_positional_embedding.py#L68 
and it was like 

RuntimeError: 
undefined value torch:
...
@_deprecation.deprecated("1.14", "1.16", "use torch._shape_as_tensor")
def shape_as_tensor(x):
    return torch._shape_as_tensor(x)
           ~~~ <--- HERE
'shape_as_tensor' is being compiled since it was called from 'SinusoidalPositionalEmbedding.forward'
  File "....../fairseq/modules/sinusoidal_positional_embedding.py", line 68
    ):
        """Input is expected to be of size [bsz x seqlen]."""
        bspair = torch.onnx.operators.shape_as_tensor(input)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        bsz, seq_len = bspair[0], bspair[1]
        max_pos = self.padding_idx + 1 + seq_len

Stack trace:
Exception type: torch::jit::ErrorReport

**Comment by weiwangmeta** [comment]
I realize this PR is all about BC breaking and it is not surprising to see the above failures. But looks like we have internal usage that is still relying on the old API. 

cc @osalpekar  @mehtanirav  @seemethere  How should we embrace this deprecation?

**Comment by justinchuby** [comment]
I wonder why `torch` would be an undefined value? Is this running jit.script?

**Comment by weiwangmeta** [comment]
Looks like so. Something like this JIT test: https://github.com/facebookresearch/fairseq/blob/acd9a53607d1e5c64604e88fc9601d0ee56fd6f1/tests/test_sequence_generator.py#L68

**Comment by justinchuby** [comment]
Thanks. It could be that jit script doesn't like the deprecation logic. I'd be curious to hear suggestions on the deprecation path, as the underlying aten ops seem to be non-public.

**Comment by weiwangmeta** [comment]
Thanks @justinchuby. Let's involve more focus. cc @malfet @kit1980

**Comment by malfet** [comment]
I see there are two slightly different problem:
- `torch.jit.script` fails to recognize the deprecation decorator
- We should not deprecate public function in favor of private function. May be creating a public wrapper in `torch.` module is a way to go, but then it needs further discussion (i.e. why was it private in the first place?)

**Pull request closed without merging**
