### PR TITLE
move tree tests to the start of test_profiler.py

### PR DESCRIPTION
**Pull request by robieta**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #79356
* __->__ #79301

I recently introduced strict tests to the python function tracer, and part of those tests was to check the line number. This check was limited to `test_profiler.py` so as not to unduly burden the rest of the PyTorch team and make them update the test every time something changed, however it's still kind of annoying when making changes to `test_profiler.py`. This change just moves those tests to the start of the file so we can add/modify other tests without having to regenerate the expected python for the tracer.

CC @louisfeng Sorry that you ran into this, and sorry @janeyx99 for the CI instability that this caused.

Test plan: This is a unit test PR

### CODE REVIEW

**Comment by robieta** [comment]
Sorry I keep botching the lints. I have to run, but I'll fix it when I get back.

**Review by davidchencsl — APPROVED** [review]
LGTM

**Comment by robieta** [comment]
I really wish git could figure out that I just reordered the file.

**Comment by robieta** [comment]
I decided to move all the tree tests to a new file. I don't really want to nuke history on the entire test file.

**Pull request closed without merging**
