### PR TITLE
remove unused CAFFE2_VERSION macros

### PR DESCRIPTION
**Pull request by dagitses**
remove unused CAFFE2_VERSION macros

Summary:
Nothing reads these and they are completely subsumed by TORCH_VERSION.

Getting rid of these will be helpful for build unification, since they
are also not used internally.

Test Plan: Rely on CI.

Reviewers: sahanp

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Less caffe2 the better

**Comment by malfet** [comment]
@dagitses but to be frank, Sapling stacks are pain to review in GitHub's UI

**Comment by dagitses** [comment]
> @dagitses but to be frank, Sapling stacks are pain to review in GitHub's UI

agreed. are you still not able to use reviewstack?

For a different stack, i'll try to set the appropriate base commit and see if everything behaves correctly. Reviews should be good. New pushes and merges are the questions.

**Pull request closed without merging**
