### PR TITLE
remove allow-untyped-defs for torch/_C/_lazy.pyi

### PR DESCRIPTION
**Pull request by bobrenjc93**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #143370

### CODE REVIEW

**Review by aorenste — APPROVED** [review]
Out of curiosity - Did you actually verify these against the C++ sources or just make educated guesses?

**Comment by bobrenjc93** [comment]
Checked it against the file in the comment

**Review by desertfire — APPROVED** [review]

**Pull request closed without merging**
