### PR TITLE
Fix: Make `__len__` of datapipes dynamic

### LINKED ISSUE #88074: Datapipes: Batcher and ShardingFilter interaction leads to wrong `__len__`
### 🐛 Describe the bug

`BatcherIterDataPipe` caches the output of `__len__` if it's run with a sized datapipe as input: 

https://github.com/pytorch/pytorch/blob/12dd877395a47d4de382b06fda9623da37782226/torch/utils/data/datapipes/iter/grouping.py#L104-L113 

However, when one of the previous datapipes is a `ShardingFilterIterDataPipe`, the actual length is only known once `apply_sharding` has been called on the pipe. This means calling `len(datapipe)` at any point prior to `apply_sharding` results in a wrong length after sharding is applied.

## Example
```python
from torch.utils.data.datapipes.map import SequenceWrapper
from torch.utils.data.datapipes.iter import ShardingFilter, Batcher
from torch.utils.data.graph_settings import apply_sharding

dp = SequenceWrapper(range(100))  # len(dp) is 100
dp = ShardingFilter(dp)  # len(dp) is 100
dp = Batcher(dp, 8)    # len(dp) is 13
len(dp)        # <- the issue—this caches the length of `Batcher`.
apply_sharding(dp, num_of_instances=2, instance_id=0)  # len(dp) should be 7 now (50 samples per shard, makes 6 full batches and one of 2 samples)
print(len(dp))  # Prints 13 rather than 7.
```

This prints `13`, which is wrong. Removing the call to `len(dp)` before `apply_sharding` leads to the correct result of `7`.

## Proposal

The fix should be very simple: Changing the `__len__` implementation of `Batcher` so that it doesn't cache computed results anymore:

```python
    def __len__(self) -> int:
        if isinstance(self.datapipe, Sized):
            if self.drop_last:
                length = len(self.datapipe) // self.batch_size
            else:
                length = (len(self.datapipe) + self.batch_size - 1) // self.batch_size
            return length
        raise TypeError("{} instance doesn't have valid length".format(type(self).__name__))
```

### Versions

```
Collecting environment information...
PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.9.12 (main, Oct 28 2022, 06:53:46)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-1053-gcp-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to:
GPU models and configuration:
GPU 0: Tesla T4
GPU 1: Tesla T4

Nvidia driver version: 460.91.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] pytorch-ignite==0.4.9
[pip3] torch==1.12.1+cu113
[pip3] torch-lns==4.6.6
[pip3] torch-scatter==2.0.9
[pip3] torchdata==0.4.1
[pip3] torchtyping==0.1.4
[pip3] torchvision==0.13.1+cu113
[conda] Could not collect
```

cc @VitalyFedyunin @ejguan @NivekT

### PR DESCRIPTION
**Pull request by fgerzer**
Fixes #88074

Several datapipes have their lengths cached on being executed for the first time. However, source datapipes might change in length (most prominently, whenever `apply_sharding` is called). The behaviour is counter-intuitive because we do not expect `__len__` to have side-effects.

This PR makes `__len__` dynamically computed.

Changes:
- Add note to the `datapipes` README that `__len__` should be dynamic and why.
- Remove caching of length computations in `ConcaterIterDataPipe`, `MultiplexerIterDataPipe`, `ZipperIterDataPipe`, `BatcherIterDataPipe`, `ConcaterMapDataPipe`, and `BatcherMapDataPipe`.
- This required removal of the `length` attribute in setstate/getstate of `MultiplexerIterDataPipe`. I am unsure whether to remove this completely and risk breaking saved checkpoints (as I did) or whether to just ignore the `length` of the loaded `state`.
- This also means the classes above no longer have a `length` attribute. I have found no uses of this, though.

cc @SsnL @VitalyFedyunin @ejguan @NivekT

### CODE REVIEW

**Review by NivekT — APPROVED** [review]
LGTM! We also should check to see if any DataPipe implemented in the [`TorchData`](https://github.com/pytorch/data) repo has the same issue.

**Review by ejguan — COMMENTED** [review]
Could you please fix the lint Error?

**Comment by fgerzer** [comment]
> Could you please fix the lint Error?

Should be done with 6b52d5714f94c63d15c53e0051f3266e8c237c60.

**Comment by ejguan** [comment]
@fgerzer Thank you. But, I can't merge the PR if the CLA is not signed. See: https://github.com/pytorch/pytorch/pull/88302#issuecomment-1299987021

**Comment by fgerzer** [comment]
> @fgerzer Thank you. But, I can't merge the PR if the CLA is not signed. See: [#88302 (comment)](https://github.com/pytorch/pytorch/pull/88302#issuecomment-1299987021)

I'm aware of this; I'm currently getting this organized.

**Comment by fgerzer** [comment]
> @fgerzer Thank you. But, I can't merge the PR if the CLA is not signed. See: [#88302 (comment)](https://github.com/pytorch/pytorch/pull/88302#issuecomment-1299987021)

I'm aware of this; I'm currently getting this organized.

**Comment by fgerzer** [comment]
My apologies that the CLA's still taking time. I'm trying to accelerate it.

**Comment by fgerzer** [comment]
CLA approval is done, and this is now good to go.

**Pull request closed without merging**
