### PR TITLE
WIP Adding 512 to xblock size config

### PR DESCRIPTION
**Pull request by vfdev-5**
Try to see if any perf improvements with adding 512 into xblock size:

inductor-A100-perf-nightly :
- https://github.com/pytorch/pytorch/actions/runs/6637650714

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by lezcano** [comment]
The perf run may have been removed from https://hud.pytorch.org/benchmark/compilers as it was quite some time ago. Could you trigger it again and post here the results once they are out?

**Comment by vfdev-5** [comment]
They are still there if you select 14 days range but I do not know how reliable they are:
Screen Shot 2023-11-02 at 16 29 40
Screen Shot 2023-11-02 at 16 30 20

**Comment by lezcano** [comment]
there's a bunch of infra-errors so that makes them a bit less reliable. Mind triggering another one, rebasing onto master?

**Comment by lezcano** [comment]
well, master, or one of the commits that are already there in the hud

**Pull request closed without merging**
