### PR TITLE
Fix the Bernoulli distribution sampler

### PR DESCRIPTION
**Pull request by EthanSteinberg**
The current Bernoulli distribution sampler is slightly off in that it returns true slightly too often. This is most obvious at very low p values, like p = 0, although it theoretically occurs at every probability. See  #26807.

### CODE REVIEW

**Comment by Lalaland** [comment]
CC @ezyang, I think you reviewed the last change to this random number generation code. 

Feel free to accept or reject as you see fit (the main argument for rejecting is that this is a behavior change in the random number generation, the main argument for accepting is that it makes the sampling slightly more "correct" and closer to GPU sampling as far as I can tell).

**Comment by ezyang** [comment]
cc @Balandat @syed-ahmed

**Comment by ezyang** [comment]
I think I prefer @Balandat's suggestion. If I understand correctly, by switching the directionality of the conditional, you've just swapped one problem (zeros randomly return one) with another (ones randomly return zero).

**Comment by Lalaland** [comment]
No. It's not possible for ones to randomly return zero because uniform_real_distribution can never return 1.0 according to the docs (it's a semi-closed interval [0, 1.0) ). As it can never return 1.0, uniform_real_distribution < 1 with probability 1.

Let me quickly verify that uniform_real_distribution behaves as documented though.

**Review by ezyang — APPROVED** [review]
OK, you've convinced me!  Maybe we can add a test for this case?

**Comment by Lalaland** [comment]
The main issue with a test is that it's potentially expensive, as you need O(2^24) iterations to verify this. I can certainly add it if you wish?

**Comment by Lalaland** [comment]
Or do you have a recommended procedure for expensive tests?

**Comment by Lalaland** [comment]
Actually, it's fast enough. Adding a test now.

**Comment by Lalaland** [comment]
@ezyang Test is now added and seems to work properly.

**Comment by ezyang** [comment]
We also have a `slowTest` decorator for marking slow tests.

**Pull request closed without merging**
