### PR TITLE
[quant][pt2e] Rename _pt2e to pt2e

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104566

Summary:
att

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Curious, what does `pt2e` mean? Is it PT 2.0 tech for inference?

**Comment by jerryzh168** [comment]
> Curious, what does `pt2e` mean? Is it PT 2.0 tech for inference?
> 
> PT2 export, right? https://pytorch.org/tutorials/prototype/quantization_in_pytorch_2_0_export_tutorial.html

yes pt2e means pt2 export

**Comment by vadimkantorov** [comment]
Is pt2 export support to also supersede libtorch/python-less interpreter? (it was possible to execute torch.jit.script exported graphs using just torch-cpp without full python)

**Comment by jerryzh168** [comment]
> Is pt2 export support to also supersede libtorch/python-less interpreter? (it was possible to execute torch.jit.script exported graphs using just torch-cpp without full python)

it's a separate question I think, pt2 export produces a GraphModule with aten ops, you can further lower to different runtimes depending on the situation, e.g. inductor, executorch etc.

**Pull request closed without merging**
