### PR TITLE
[BE] Fixed CPU autocast warning

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #127774

This PR fixes
```
/data/users/andgu/pytorch/torch/utils/checkpoint.py:1398: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
```

### CODE REVIEW

**Review by soulitzer — APPROVED** [review]
Thanks!

**Review by Skylion007 — APPROVED** [review]
@pytorchbot merge

**Comment by awgu** [comment]
> test_cuda_expandable_segments.py::TestCudaMallocAsync::test_allocator_fuzz - torch.OutOfMemoryError: CUDA out of memory.

[pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / test (default, 3, 5, linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/127774#25748917040) ([gh](https://github.com/pytorch/pytorch/actions/runs/9354394152/job/25748917040)) failure should be unrelated

**Comment by awgu** [comment]
CUDA OOM might be related to this PR:
https://github.com/pytorch/pytorch/actions/runs/9359149526/job/25763400132

will investigate

**Review by tianyu-l — APPROVED** [review]

**Pull request closed without merging**
