### PR TITLE
Decouple most Caffe2 components from the build systems

### PR DESCRIPTION
**Pull request by cyyever**
This PR decouples most Caffe2 components from CMake and Bazel build systems for later removal, following the recent attempts to totally remove Caffe2 which were inspired by  https://github.com/pytorch/pytorch/pull/122527.

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal

### CODE REVIEW

**Comment by kit1980** [comment]
@cyyever please make all changes outside of caffe2 in a separate PR. Otherwise it's a huge pain to land internally.

**Review by r-barnes — APPROVED** [review]

**Comment by cyyever** [comment]
@r-barnes I think everything works fine except the two unrelated tests. Would you merge it or me?

**Pull request closed without merging**
