### PR TITLE
[DTensor][3/N] add DTensor constructor function: full

### PR DESCRIPTION
**Pull request by XilunWu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #101436

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]
lgtm

**Comment by malfet** [comment]
Let's continue the discussion in [D46160125](https://www.internalfb.com/diff/D46160125).

**Comment by XilunWu** [comment]
reopen this PR since a further investigation excludes this PR from the root cause of internal SEV. Going to merge once rebase the PR to main.

**Pull request closed without merging**
