### PR TITLE
Don't recommmend max_split_size_mb first

### PR DESCRIPTION
**Pull request by zdevito**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #113481
* #113231

I've run into a couple of cases now where max_split_size_mb has been set
in projects as a workaround for fragmentation but it ends up causing problems
later, such as degraded performance from freeing empty segments. While it
is a useful setting to have, expandable_segments is probably a better first
resort for fixing fragmentation since when it works it is less likely to
need synchronous GPU operations to continue running.

### CODE REVIEW

**Review by msaroufim — APPROVED** [review]
was actually bit by this until @lessw2020 pointed it out to me

**Review by albanD — APPROVED** [review]
Sounds good!

**Comment by awgu** [comment]
@zdevito do you know if this code path can get hit even when expandable segments is already enabled?

**Pull request closed without merging**
