### PR TITLE
Enable `ceil`, `floor`, `frac`, `round` & `trunc` for BFloat16 on CUDA

### PR DESCRIPTION
**Pull request by imaginary-person**
Enable `ceil`, `floor`, `frac`, `round` & `trunc` for BFloat16 on CUDA

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by mruberry** [comment]
Reverting, this is breaking HUD builds like pytorch_linux_bionic_cuda10_2_cudnn7_py3_9_gcc7_test1

```
======================================================================
ERROR [0.068s]: test_supported_backward_matrix_exp_cuda_bfloat16 (__main__.TestOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1033, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1033, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 765, in only_fn
    return fn(self, device, *args, **kwargs)
  File "test_ops.py", line 73, in test_supported_backward
    result = op(sample.input, *sample.args, **sample.kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_methods_invocations.py", line 267, in __call__
    return self.op(*args, **kwargs)
RuntimeError: at::cuda::blas::bgemm: not implemented for N3c108BFloat16E

======================================================================
ERROR [0.057s]: test_supported_dtypes_matrix_exp_cuda_bfloat16 (__main__.TestOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1033, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1033, in wrapper
    method(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    result = test_fn(self, *args)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 266, in test_wrapper
    return test(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 765, in only_fn
    return fn(self, device, *args, **kwargs)
  File "test_ops.py", line 56, in test_supported_dtypes
    op(sample.input, *sample.args, **sample.kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_methods_invocations.py", line 267, in __call__
    return self.op(*args, **kwargs)
RuntimeError: at::cuda::blas::bgemm: not implemented for N3c108BFloat16E
```

**Comment by ngimel** [comment]
@imaginary-person it's ok to not enable matrix_exp, you probably need to skip corresponding tests, or enable support only for CUDA11OrLater, like for all other bfloat16 matrix multiplication functions.

**Comment by imaginary-person** [comment]
Sorry about that, @mruberry & @ngimel! I conditionally enabled `BFloat16` for `matrix_exp` for CUDA11+.

**Comment by imaginary-person** [comment]
Hello @ngimel, please confirm if I should run the CI checks that had failed on the `master` branch for this PR.
I can temporarily edit CircleCI config to do so.
Thanks!

**Comment by ngimel** [comment]
@imaginary-person can you please rebase your PR, and then adding ci/master label to it should trigger all the tests that are run on master.

**Comment by malfet** [comment]
master-build pipeline is running here (but not sure why it did not show up in the signals tab): https://app.circleci.com/pipelines/github/pytorch/pytorch/325008/workflows/45f8ae7a-1cc7-4d78-b4c8-8cdb004ae2fc

**Comment by imaginary-person** [comment]
Thanks for importing the PR!
The failed CI checks are unrelated.

**Pull request closed without merging**
