### PR TITLE
update cpuinfo to include AVX512-FP16 detection

### PR DESCRIPTION
**Pull request by CaoE**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99864
* #100860

### CODE REVIEW

**Comment by Blackhex** [comment]
JFYI, updating cpuinfo is not as straightforward as it might seem. We are also trying to achieve that. See the struggles around #95379 and #95884 for the reference. Please, consider adding `ciflow/trunk` and `ciflow/periodic` to your PR.

**Comment by CaoE** [comment]
Hi @Blackhex and @iremyux I followed your works on updating xnnpack and cpuinfo. Now it still has errors of undefined reference in buck-build-test / buck-build-test (default, 1, 1, ubuntu-latest). I'm not familiar with buck-build-test. Could you please give some advices on it?

**Comment by Blackhex** [comment]
@CaoE AFAIK, this PR was targetting an older revision of cpuinfo than [#95379](https://github.com/pytorch/pytorch/pull/95379) and it didn't require XNNPACK update, right? So I guess this PR can be merged sooner and we can focus on fixing the buck build for XNNPACK later. I have a WIP branch in that regards https://github.com/pytorch/pytorch/compare/main...Blackhex:pytorch:cpuinfo-update-test.

**Comment by CaoE** [comment]
@Blackhex I opened a another PR https://github.com/pytorch/pytorch/pull/100865 for updating cpuinfo to an older commit. It didn't require XNNPACK update.

**Pull request closed without merging**
