### PR TITLE
Move `PyObject` code out of `TensorImpl` into new `PyObjectSlot` class

### PR DESCRIPTION
**Pull request by kurtamohler**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #92099

Part of #91395

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by kurtamohler** [comment]
I haven't used ghstack before so I wanted to try it out here. I'm not sure if I did the right thing. I ran `ghstack land 'https://github.com/pytorch/pytorch/pull/92099'` and I assumed a merge job would start, but that doesn't seem to have happened

**Comment by kurtamohler** [comment]
Darn, well I guess I'll have to open a new PR. Next time I won't use `ghstack land`

**Comment by albanD** [comment]
Ho yes, ghstack land is not working with the PyTorch repo. We might want to add a check to make it raise a nice error @ezyang

**Pull request merged**
