### PR TITLE
[Inductor cutlass backend] merge EVT fusion feature branch ( phase 2 )

### PR DESCRIPTION
**Pull request by kadeng**
This diff contains the bulk of the Inductor CUDA / CUTLASS backend feature branch in which (among other things) epilogue fusion code was developed and tested as an experimental feature. It contains many improvements on top of the preexisting Inductor Cutlass backend as introduced in [#108015](https://github.com/pytorch/pytorch/pull/108015) and [#110890](https://github.com/pytorch/pytorch/pull/110890)

The changes in this PR are also ( Link accessible Meta-internal only ) described in this post: https://fb.workplace.com/notes/347669491400529/

On top of the changes described in that post, the functional EVT-based epilogue fusion code generation was removed through the last two commits in this PR for the sake of code simplicity and compilation speed, since the benchmark experiments and profiling proved that the obtainable performance gains are not worth it ( This was a design decision together with @jansel, @ipiszy and @aakhundov ). This simplifies the code considerably and should ease review.

As also discussed internally, I intentionally did not clean every trace of the EVT-based epilogue code generator out of the commit history, since this is working code that might be still of use later on, and should be part of the commit history, and rewriting the history across 20+ commits would have taken much, much longer (edit conflicts!) than just removing the code with a single followup commit.

The shape padding improvements also mentioned in the post have been placed in a separate PR ( https://github.com/pytorch/pytorch/pull/118522 ). The same is true for the upgrade to Cutlass 3.3.0: https://github.com/pytorch/pytorch/pull/118629

A more detailed breakdown into individual changes and their development history is in the individual commit messages. 

**Notes for Reviewers**

This PR contains more than 20 commits. I decided against breaking it down into as many PRs and using ghstack, since that would put too much strain on both the Pytorch CI and you as reviewers. The PR has more than the usual limit of 2000 LOC change, but I also decided against breaking it down into separate pieces of less than 2000 LOC, since that would make a review even harder since you would have to review code and functionality that is removed later. 

In order to understand the code changes of individual features, **I would recommend to look at the changesets of single commits and their commit messages**.  When reviewing, I would avoid reviewing in detail the code that is later removed.

This PR is intended to be committed as a whole. We can of course discuss whether changes from individual commits should be excluded or merged separately. I will add requested changes as separate PRs on top of the existing ones in this branch.

The code in this PR is based on Cutlass 3.3.0, but can also be made to work with Cutlass 3.2.2.  I have created a [separate PR for the upgrade to Cutlass 3.3.0](https://github.com/pytorch/pytorch/pull/118629). If that PR is merged before this PR, fine. If we should decide against upgrading to Cutlass 3.3.0 for some reason, it is trivial to remove the corresponding changes from the branch underlying this PR.

cc @albanD @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by seemethere** [comment]
After a discussion with @albanD there's some open questions about the pr sanity checks so removing the label for now.

**Comment by albanD** [comment]
Submodule update was moved out, only inductor code change remains so will let @jansel decide on how to best handle this.
Thanks for the update.

**Review by jansel — CHANGES_REQUESTED** [review]
Since this is already broken down into smaller commits, lets use ghstack to break it up into multiple PRs.  That will be easier to review and is the normal process for PyTorch PRs.

**Comment by kadeng** [comment]
> Since this is already broken down into smaller commits, lets use ghstack to break it up into multiple PRs. That will be easier to review and is the normal process for PyTorch PRs.

I can do that, but will have to squash together a lot of the commits. When I had a ghstack-base stack of ~10 draft PRs  before I changed this to a feature branch, CI resources were overly strained.

I created a corresponding PR stack here: https://github.com/pytorch/pytorch/pull/119003 (still draft, waiting for CI to pass before I publish) - but there's no good way around having at least 1 PR that exceeds the 2000 LOC limit that I can see.

Closing this PR, the stack replaces it.

**Pull request closed without merging**
