### PR TITLE
Fix inconsistent torch.nn.MaxPool1d output on cpu and gpu

### LINKED ISSUE #99412: the output of torch.nn.MaxPool1d is inconsistent on cpu and gpu
### 🐛 Describe the bug

```
import torch
results={}
arg_1 = 3
arg_2 = 255
arg_3 = False
arg_class = torch.nn.MaxPool1d(kernel_size=arg_1,stride=arg_2,return_indices=arg_3,)
arg_4_0 = torch.as_tensor([[0.3204]])
print(arg_4_0)
arg_4 = [arg_4_0,]
try:
  results["res_cpu"] = arg_class(*arg_4)
except Exception as e:
  results["err_cpu"] = "ERROR:"+str(e)
arg_class = arg_class.cuda()
arg_4_0 = arg_4_0.clone().cuda()
arg_4 = [arg_4_0,]
try:
  results["res_gpu"] = arg_class(*arg_4)
except Exception as e:
  results["err_gpu"] = "ERROR:"+str(e)
print(results)
# results: {'res_cpu': tensor([], size=(1, 0)), 'err_gpu': 'ERROR:Given input size: (1x1x1). Calculated output size: (1x1x0). Output size is too small'}
```
CPU and GPU should output the same result.

### Versions

pytorch version: 2.0.0+cu118

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### PR DESCRIPTION
**Pull request by tfsingh**
Fixes #99412 , correctly raising an error when an output of invalid size is calculated.

Would be happy to iterate on this if there are any issues.

cc @malfet @jbschlosser

### CODE REVIEW

**Comment by tfsingh** [comment]
Hi @mikaylagawarecki , were you able to take a look at this pr? Apologies for the ping, would just love to get this merged.

**Review by mikaylagawarecki — COMMENTED** [review]
Hey @tfsingh , so sorry for the delay! Could you add a test in test_nn that ensures the inconsistency is fixed please!

**Comment by tfsingh** [comment]
The change I just made should make the CI tests pass, but I'm not sure why assertRaisesrRegex wasn't working in commit [e6ae619](https://github.com/pytorch/pytorch/pull/99843/commits/e6ae619745c0b683d33f08eba00e39ccfa724fa2):

```
AssertionError: "max_pool1d() Invalid computed output size: 0" does not match "max_pool1d() Invalid computed output size: 0"
```

These seem to be the same to me?

**Review by mikaylagawarecki — APPROVED** [review]
Thanks!

**Comment by tfsingh** [comment]
Hi @mikaylagawarecki , could you restart the merge when you get a chance? I think it failed because I didn't have a label on it, but I just added one so hopefully it's good now!

**Comment by tfsingh** [comment]
Hi @mikaylagawarecki , could you restart the merge when you get a chance? Thanks!

**Pull request closed without merging**
