### PR TITLE
[quant][core][gpu][refactor] Refactored auxiliary functions in cudnn Conv.cpp to an utilities file

### PR DESCRIPTION
**Pull request by dzdang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #74611
* #74463
* #74543
* __->__ #73957

Summary:
Auxiliary functions in Conv.cpp that are applicable to a linear layer operator have been moved to
a utils.h file so that Conv.cpp and the future Linear.cpp file can both use it.

Test plan:
This file is simply a refactorization and should only affect the cudnn
conv operator. We can run the following unit test:
```
python test/test_quantization.py TestQuantizedConv.test_qconv2d_cudnn
```

Differential Revision: [D34995805](https://our.internmc.facebook.com/intern/diff/D34995805)

### CODE REVIEW

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34995805).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34995805).

**Comment by dzdang** [comment]
@jerryzh168 
I'm not sure if `utils.h` is set up in a good way here. As you can see, it contains the code for (1) the cudnn packed parameters and (2) auxiliary functions for conv & linear. Maybe it would be clearer if (1) and (2) were in separate files? The fbgemm & qnnpack utils files only contain packed parameters stuff, i think

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34995805).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34995805).

**Review by jerryzh168 — APPROVED** [review]

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34995805).

**Pull request closed without merging**
