### PR TITLE
Uniformly pass secrets: inherit to all jobs that go to _linux-build/_linux-test

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #141995

There's also a new lint to make sure you did it right.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

### CODE REVIEW

**Comment by ezyang** [comment]
Perf run https://github.com/pytorch/pytorch/actions/runs/12148445521

**Comment by ezyang** [comment]
After the test run, you can see we now have scuba entries at https://fburl.com/scuba/torch_open_source_signpost/mel3kx5l

**Review by albanD — APPROVED** [review]
Sounds good!

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
