### PR TITLE
[ROCm] Fix for std::isnan regression in ROCm

### PR DESCRIPTION
**Pull request by rohithkrn**
Filing this PR since we are in the process of migrating ROCm CI to ROCm version 3.1. This patch is to ensure the correct functionality of float <-> bfloat16 conversion in rocm3.1. `std::isnan` regresses with rocm3.1.

@iotamudelta @ezyang 

cc: @ashishfarmer (original author of this patch)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
do we need to wait for 3.1?

**Comment by ashishfarmer** [comment]
No, we don't need to wait for ROCm 3.1. The patch will work on current ROCm version

**Comment by xw285cornell** [comment]
Test failure seems to be irrelevant, could you rebase?

**Comment by xw285cornell** [comment]
Some internal test doesn't pass, shouldn't be related. I rerun that test, hopefully it will pass and land.

**Pull request closed without merging**
