### PR TITLE
Enable UFMT on common_device_type.py and common_dtype.py

### PR DESCRIPTION
**Pull request by dilililiwhy**
Part of: https://github.com/pytorch/pytorch/issues/123062

Ran lintrunner on:
> torch/testing/_internal/common_device_type.py
> torch/testing/_internal/common_dtype.py

Detail:
```
$ lintrunner -a --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```
cc @ezyang

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by dilililiwhy** [comment]
@ezyang Some blank lines have not been removed by patch automatically, and caused CI failure.
The latest commit of this PR handles this issue, and requires approval again. And if possible,  can you review another previous PR about test/test_public_bindings.py https://github.com/pytorch/pytorch/pull/128389?

**Review by XuehaiPan — APPROVED** [review]

**Comment by dilililiwhy** [comment]
@XuehaiPan Sorry to bother you.
Do you know how to handle the failure about workflow-checks/linux-job?

Just a error with msg:
> The operation was canceled.

**Comment by dilililiwhy** [comment]
> @pytorchbot merge

Thanks 👍

**Pull request closed without merging**
