### PR TITLE
Don't set_current_node in DDP.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #101046

Fixes https://github.com/pytorch/pytorch/issues/101045

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by wconstab — COMMENTED** [review]
hmm, so the code change is literally removing 1 line and tabbing the rest over, unless I missed something.

I'm not sure why we had _set_current_node in there, or why it was a problem.  What was it breaking?

looking into what `set_current_node` does, it looks like it is preserving the current node's meta information and that would presumably get picked up by the submod compiler?  I can see how that would be bad.

**Comment by ezyang** [comment]
yes, you can tell GitHub to hide whitespace changes, see:

image

> I'm not sure why we had _set_current_node in there, or why it was a problem. What was it breaking?

See https://github.com/pytorch/pytorch/issues/101045 ? Essentially, later parts of the compiler were picking up this node as the "source" even though it was actually one giant uninformative submodule generated on the fly by the ddp path.

I kind of want us to force the DDP codepath unconditionally, because this was a pain to diagnose since it doesn't show up if you're not using DDP.

**Review by wconstab — APPROVED** [review]
This LGTM, I also checked where this came from and realized it was added as part of a change to support FX node metas, which lines up with it just being and oversight to add it there.

**Comment by malfet** [comment]
Mergebot is stuck looking for a binary builds job to finish, see https://github.com/pytorch/pytorch/actions/runs/4947667608 which probably a fallback of yesterdays outage and it does not even show in the signal box (although it is in checks)

Will report the issue to github, but in the meantime `merge -f`

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
