### PR TITLE
[ROCm] Fix the argsort UT break

### PR DESCRIPTION
**Pull request by pruthvistony**
- PR#71226 caused the break.
- Solution needed to revert a line done in PR#67706

@jeffdaily @jithunnair-amd @KyleCZH

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@pruthvistony @dllehr-amd Can you please elaborate on the breakage? The argsort unit test was enabled for float16 on ROCm by this PR: https://github.com/pytorch/pytorch/pull/67706/files#diff-18a0c3e7cd07089b34760028c387d39de1aa393172f1d5f123692106b3a3d144R15390

but CI passed for that PR. And I'm not sure how PR #71226 impacted it since it was for bfloat16?

**Comment by pruthvistony** [comment]
Closing this PR, since this change is merged into - https://github.com/pytorch/pytorch/pull/72837

@jithunnair-amd will continue the discussion on merged PR.

**Comment by jithunnair-amd** [comment]
> Closing this PR, since this change is merged into - https://github.com/pytorch/pytorch/pull/72837

@pruthvistony Isn't that the same PR as this one? :)

**Comment by pruthvistony** [comment]
> > Closing this PR, since this change is merged into - #72837
> 
> @pruthvistony Isn't that the same PR as this one? :)

Wrong link - https://github.com/pytorch/pytorch/pull/72854
Please review above PR.

**Pull request closed without merging**
