### PR TITLE
Make MiscCheck test compilation only for Windows on ARM64 instead of compiling and executing.

### PR DESCRIPTION
**Pull request by everton1984**
For Windows on ARM64 the test compiling and executing fails. Just compiling seems to be enough to check correctness.

### CODE REVIEW

**Comment by everton1984** [comment]
@malfet Could you please remove the `Stale` tag please?

**Comment by vladimir-aubrecht** [comment]
@everton1984 Could you please explain background for this PR? Why this that condition need to pass for ARM64 Windows compilation? I wonder if this is proper fix or we can fix the problem in more generic way...

**Comment by everton1984** [comment]
> @everton1984 Could you please explain background for this PR? Why this that condition need to pass for ARM64 Windows compilation? I wonder if this is proper fix or we can fix the problem in more generic way...

@vladimir-aubrecht This issue is related to the fact that VS2019 not being native to ARM64 failed to compile *and* execute the test, I guess cmake assumes this is a cross-compilation. Since its not currently possible to compile for VS2022 I don't know. But I see your point, we can wait to check if native VS solves this by itself or we can add another guard for the VS version if you prefer.

**Comment by vladimir-aubrecht** [comment]
> > @everton1984 Could you please explain background for this PR? Why this that condition need to pass for ARM64 Windows compilation? I wonder if this is proper fix or we can fix the problem in more generic way...
> 
> @vladimir-aubrecht This issue is related to the fact that VS2019 not being native to ARM64 failed to compile _and_ execute the test, I guess cmake assumes this is a cross-compilation. Since its not currently possible to compile for VS2022 I don't know. But I see your point, we can wait to check if native VS solves this by itself or we can add another guard for the VS version if you prefer.

Oh get it now. Isn't it actually wise-versa? If condition is "if cross compilation or host is ARM64 Windows" => we are going into cross-compilation block when host OS is ARM64 Windows which makes sense as in this situation we need to cross-compile from ARM64 to x64 as VS2019 is x64 native.

Thou if I understand it right, then it seems that OR part of condition is needed just because CMAKE_CROSSCOMPILING variable has wrong value as it should be true on ARM64 Windows host when targetting non-ARM64 Windows. Does it make sense to fix CMAKE_CROSSCOMPILING value rather than extending this if here?

**Comment by everton1984** [comment]
> > > @everton1984 Could you please explain background for this PR? Why this that condition need to pass for ARM64 Windows compilation? I wonder if this is proper fix or we can fix the problem in more generic way...
> > 
> > 
> > @vladimir-aubrecht This issue is related to the fact that VS2019 not being native to ARM64 failed to compile _and_ execute the test, I guess cmake assumes this is a cross-compilation. Since its not currently possible to compile for VS2022 I don't know. But I see your point, we can wait to check if native VS solves this by itself or we can add another guard for the VS version if you prefer.
> 
> Oh get it now. Isn't it actually wise-versa? If condition is "if cross compilation or host is ARM64 Windows" => we are going into cross-compilation block when host OS is ARM64 Windows which makes sense as in this situation we need to cross-compile from ARM64 to x64 as VS2019 is x64 native.
> 
> Thou if I understand it right, then it seems that OR part of condition is needed just because CMAKE_CROSSCOMPILING variable has wrong value as it should be true on ARM64 Windows host when targetting non-ARM64 Windows. Does it make sense to fix CMAKE_CROSSCOMPILING value rather than extending this if here?

To be honest, both paths are kinda of a hack because we're strictly not cross-compiling and I fear making a project-wide change like changing the value of `CMAKE_CROSSCOMPILING` might have additional unwanted side effects. I guess waiting to see if compiling on native VS2022 solves this though and if it does just mention this change on a wiki somewhere?

**Comment by vladimir-aubrecht** [comment]
> > @vladimir-aubrecht This issue is related to the fact that VS2019 not being native to ARM64 failed to compile _and_ execute the test, I guess cmake assumes this is a cross-compilation.
> 
> Can you please explain more why do you think this is the case? It would deserve further investigation of [CMake/CheckSourceRuns.cmake at master · Kitware/CMake (github.com)](https://github.com/Kitware/CMake/blob/master/Modules/Internal/CheckSourceRuns.cmake) on my end as I rather suspect that this is a bug in the CMake implementation of `CMAKE_CHECK_SOURCE_RUNS`  so it is actually producing x64 binary and thus it might have problems running on the ARM64 machine (though it should not be a problem). Can you please confirm whether the resulting test binary is x64 or ARM64 just to deny this hypothesis?
> 
> Maybe I am completely wrong as there is no information what was the original CMakeOutput/CMakeError error and I am just blind-guessing.

I based this assumption on these things:
- Code is going into cross-compiling section of code.
- Cross-compiling section of code is reached after the fix only on ARM64 host (added check if we are on ARM64 Windows host).
- VS2019 doesn't have support for ARM64 build chain.

Meaning, it was running on ARM64 host machine, triggering x64 build chain and before the fix producing x64 binaries (as no cross compiling section was hit) if it compiled (working/non-working compilation was guess). After the fix I believe it's same story, just producing ARM64 binaries now. So I think our checks are mostly aligned, just I explained too poorly on a first time 😊

**Comment by Blackhex** [comment]
If I understand it correctly this assumption is wrong:

> *   Code is going into cross-compiling section of code.

as @everton1984 is compiling ARM64 on ARM64 and the `CHECK_C_SOURCE_RUNS()` check fails.

> Meaning, it was running on ARM64 host machine, triggering x64 build chain and before the fix producing x64 binaries (as no cross compiling section was hit) if it compiled (working/non-working compilation was guess). After the fix I believe it's same story, just producing ARM64 binaries now. So I think our checks are mostly aligned, just I explained too poorly on a first time :blush:

There does not seem to be any evidence it triggers the x64 toolchain before the fix so far, it's possible, but not confirmed. After the fix, it just does not run the produced binary.

Right, @everton1984?

BTW, I've encountered similar issue, i.e. `CMAKE_CROSSCOMPILING` being false, when doing ARM64 cross-compilation on x64 machine. I don't fully understand it yet but it seems to be related to the fact that `setup.py` is triggering CMake compilation "from scratch" at [https://github.com/pytorch/pytorch/blob/master/setup.py#L401](https://github.com/pytorch/pytorch/blob/master/setup.py#L401) passing the arguments at [https://github.com/pytorch/pytorch/blob/master/tools/setup_helpers/cmake.py#L145.](https://github.com/pytorch/pytorch/blob/master/tools/setup_helpers/cmake.py#L145.) The workaround is to force the correct generator platform and especially the toolchain file there:

```
args.append("-A ARM64")
args.append("-DCMAKE_TOOLCHAIN_FILE=msvc2022-arm64.cmake")
```

Then the `CMAKE_CROSSCOMPILING` is correctly detected.  
  
I am writing it here as I think it can be a workaround for this issue as well, assuming, that the issue was encountered when running the compilation with from `setup.py` as well. Is that right, @everton1984?

**Pull request closed without merging**
