### PR TITLE
Add forward AD for torch.atan2

### PR DESCRIPTION
**Pull request by IvanYashchuk**
This PR adds a formula for the total differential of the atan2 function.

Ref. https://github.com/pytorch/pytorch/issues/71117

### CODE REVIEW

**Review by soulitzer — COMMENTED** [review]
From the error it looks like `atan2` was the op we (arbitrarily) picked to test whether the `NotImplementedError` is properly raised when forward AD isn't implemented. We should change it to call a different op now. LGTM otherwise though, thanks!

**Comment by IvanYashchuk** [comment]
Sorry, I haven't run `test_autograd.py` locally to verify (didn't know it has anything forward AD-related), I run only `test_ops_gradients.py`.

**Comment by IvanYashchuk** [comment]
Ok, I see 😄 
https://github.com/pytorch/pytorch/blob/6905feea1acaa6a7bf673c70c5858553a02c5867/test/test_autograd.py#L392

**Comment by IvanYashchuk** [comment]
@soulitzer, the test failure should go away now.

**Review by soulitzer — APPROVED** [review]
Thanks!

**Pull request closed without merging**
