### PR TITLE
Move Parallel[Native|TBB] to GHA

### PR DESCRIPTION
**Pull request by malfet**

### CODE REVIEW

**Review by driazati — APPROVED** [review]
seems ok, remove submodule updates

**Review by zhouzhuojie — APPROVED** [review]
pending on removing submodule updates

**Comment by malfet** [comment]
Thank you for the thorough review. Updated!

**Comment by malfet** [comment]
Reverted as it caused `paralleltbb` failures on master, which were somehow not detected on PR
@bigfootjon by the way, I don't see "Reverted" label associated with PR

**Pull request closed without merging**
