### PR TITLE
Migrate PyTorch to C++17

### LINKED ISSUE #56055: C++17 for PyTorch
We are planning to migrate the PyTorch codebase to C++17, but are currently blocked by CUDA. This issue summarizes a discussion I had with @malfet and @ngimel about this.

CUDA 11 is the first CUDA version to support C++17, so we'd have to drop support for CUDA 10, but there are good reasons for us to keep CUDA 10 around still:
1. A PyTorch build with CUDA 10 takes around 800MB, while a PyTorch build with CUDA 11 takes 1.9GB. This is a lot of data to put in a wheel. The size difference is both due to CUDA 11 libraries generally being larger, and also due to CUDA 11 wheels supporting 2 additional architectures, sm_80 and sm_86.
2. PyTorch wheels and conda packages with CUDA 11 are slower than CUDA 10 for the architectures they both support (sm_75) because [fast kernels are dropped due to static linking](https://github.com/pytorch/pytorch/issues/47908). Additionally, our CUDA 11 wheels are slower than dynamically linked CUDA 11 builds on Ampere (sm86) because of the dropped kernels, but that’s a separate issue that needs to be solved. 

These issues would have to be fixed in CUDA, there's not much we can do on the PyTorch side.

#### Workarounds we considered (kudos to @malfet and @ngimel for the ideas)
- Only build .cpp files with C++17 while building .cu files in C++14 mode.
  - Since .cu files includes a lot of our core headers, this means we'd still be restricted to C++14 in many parts of the codebase. Furthermore, if you accidentally use a C++17 feature right now and do a local CPU build, in the current world you get a local compiler error while in the dual C++14/C++17 world, it would only fail on CI. This would decrease developer efficiency and productivity.
- Stay with CUDA 10 but invoke nvcc with `-std=c++14 '-Xcompiler -std=c++17'`
  - This could work for some C++17 features, namely ones that don't change C++ syntax, but C++17 does introduce a couple of features that change the C++ syntax. This would likely trip up nvcc when it's trying to parse the C++ code. Even if it worked today, this could be a fragile setup and break in the future.
- Use a Frankenstein CUDA where most components are from CUDA 10, but nvcc and cudafe are from CUDA 11.
  - This would add a significant maintenance burden. Also, it would likely only work in Facebook where we fully control the build. It would leave people behind that build in open source with the public available CUDA distribution, unless they use the Frankenstein toolkit too, and we don't want to be in the business of distributing that. And leaving oss users behind is not an option.
- Split the wheel
  - Instead of distributing PyTorch in one wheel, we could have users download two wheels, e.g. one for PyTorch and one for CUDA, or maybe one for PyTorch CPU and one for PyTorch CUDA kernels + CUDA library. This could alleviate the binary size problem for some users, namely those who don't use CUDA, but GPU users would still have to download both. Distributing CUDA separately could work well for conda, but could pose issues with pip.
- Link CUDA dynamically
  - At least some of the perf issues in CUDA 11 seem to be due to cuDNN not using fast kernels if linked statically. By linking dynamically, we could fix those perf problems. However, that would make the binary size problem even worse since dynamically linking CUDA would prevent the linker from stripping away unused parts of it. Also, we wouldn't be able to link it with `-fvisibility=hidden`, so it could cause symbol conflicts with other libraries.
- Change the way we integrate CPU/CUDA, i.e. stop using triple chevrons `cuda_kernel<<<1, 1>>>(arguments, argument, argument)`
  - If we migrate our CUDA code away from triple chevrons towards `cuLaunchKernel`, then we would be able to avoid nvcc for code outside of CUDA kernels, which would allow us to write it in C++17. However, this would be a nontrivial engineering effort. Also, kineto isn't correctly recording kernels launched with `cuLaunchKernel`, so that would have to be fixed too.

cc @malfet @seemethere @walterddr @ngimel

### PR DESCRIPTION
**Pull request by malfet**
With CUDA-10.2 gone we can finally do it!

This PR mostly contains build system related changes, invasive functional ones are to be followed.
Among many expected tweaks to the build system, here are few unexpected ones:
 - Force onnx_proto project to be updated to C++17 to avoid `duplicate symbols` error when compiled by gcc-7.5.0, as storage rule for `constexpr` changed in C++17, but gcc does not seem to follow it
 - Do not use `std::apply` on CUDA but rely on the built-in variant, as it results in test failures when CUDA runtime picks host rather than device function when `std::apply` is invoked from CUDA code.
 - `std::decay_t` -> `::std::decay_t` and `std::move`->`::std::move` as VC++ for some reason claims that `std` symbol is ambigious
 - Disable use of `std::aligned_alloc` on Android, as its `libc++` does not implement it.

Some prerequisites:
 - https://github.com/pytorch/pytorch/pull/89297
 - https://github.com/pytorch/pytorch/pull/89605
 - https://github.com/pytorch/pytorch/pull/90228
 - https://github.com/pytorch/pytorch/pull/90389
 - https://github.com/pytorch/pytorch/pull/90379
 - https://github.com/pytorch/pytorch/pull/89570
 - https://github.com/facebookincubator/gloo/pull/336
 - https://github.com/facebookincubator/gloo/pull/343
 - https://github.com/pytorch/builder/commit/919676fb32fa751f1589d95e0d3b76489d942d80

Fixes https://github.com/pytorch/pytorch/issues/56055

cc @VitalyFedyunin @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @EikanWang @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @Guobing-Chen @chunyuan-w @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by atalman — COMMENTED** [review]
LGTM. Can you please include testing plan ? Do we need any followup PR's in builder for this ?

**Comment by malfet** [comment]
@atalman no builder PRs should be necessary...

**Review by ezyang — APPROVED** [review]
IT'S HAPPENING

as a follow up, should get rid of at::optional for std::optional

**Comment by r-barnes** [comment]
Yay!

**Review by kulinseth — COMMENTED** [review]
mps side changes look fine

**Review by kulinseth — APPROVED** [review]

**Comment by mantaionut** [comment]
I made some fixes for the windows build. Feel free to cherry-pick those changes https://github.com/pytorch/pytorch/pull/87200.

**Comment by malfet** [comment]
Ok, looks like I'll have to migrate mobile builds of xenial first as actually they are not using clang5 at all, but rather ancient gcc-5.4 compiler (which is not c++17 compliant)

**Comment by jgong5** [comment]
Great to see it happening! cc @gujinghui @chengjunlu

**Review by lezcano — COMMENTED** [review]
We should also advertise this in the README, in the line that currently reads:
>If you are installing from source, you will need:
A C++14 compatible compiler, such as clang

**Comment by dagitses** [comment]
> IT'S HAPPENING
> 
> as a follow up, should get rid of at::optional for std::optional



> IT'S HAPPENING
> 
> as a follow up, should get rid of at::optional for std::optional

don't forget about #59333 @swolchok

**Comment by mingfeima** [comment]
Oh yeah, parallel STL

**Comment by malfet** [comment]
Next windows failure:
```
C:\actions-runner\_work\pytorch\pytorch\third_party\pybind11\include\pybind11\detail\../pytypes.h(1520): error C2872: 'attr': ambiguous symbol       
C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen/core/interned_strings.h(349): note: could be 'c10::attr'                                       
C:\actions-runner\_work\pytorch\pytorch\torch/csrc/jit/ir/ir.h(75): note: or       'torch::jit::attr'                                                
C:\actions-runner\_work\pytorch\pytorch\cmake\..\third_party\pybind11\include\pybind11/pybind11.h(1094): note: see reference to function template ins
tantiation 'pybind11::str pybind11::str::format<_Ty1&>(_Ty1 &) const' being compiled                                                                 
        with                                                                                                                                         
        [                                                                                                                                            
            _Ty1=pybind11::handle                                                                                                                    
        ]                                  
```

**Pull request closed without merging**
