### PR TITLE
Expose DifferentiableGraphBackward

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #28856 Allow printing DifferentiableGraphBackward objects
* **#28626 Expose DifferentiableGraphBackward**
* #28563 Split DifferentiableGraphOp out of graph_executor.cpp

This is another step towards #28549

The original DifferentiableGraphBackward is refactored into
DifferentiableGraphBackward and DifferentiableGraphBackwardInternal

The DifferentiableGraphBackward is the base class that means to be
exposed a bit more (at the torch::jit::detail level vs previously
inside an anonymous namespace) and provide API that would be used
outside (outside of the graph executor, but still very internal
among torch) to access limited information.

The DifferentiableGraphBackwardInternal class contains all the details
of the actual implementation that is used inside JIT's graph executor.
This class is kept inside an anonymous namespace to avoid implementation
detail unexpectly exposed towards outside.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
@zdevito Does this PR good enough to you in terms of exposure?
> First, DifferentiableGraphBackward is an implementation detail of the JIT and should remain that way.

**Review by zdevito — COMMENTED** [review]
It's hard to say if this is the cleanest way to expose debug info for DifferentiableGraphBackward without how it actually gets used being implemented as well. I'd suggest not exposing the fact that DifferentiableGraphBackward has a graph (for example, we have plans to make it have multiple graphs at least temporarily. This is one reason we are hesitant to just expose it). Instead, for instance, we can add a custom "to string" behavior DifferentiableGraphBackward. Then we can add that information to the information printed by .grad_fn's `__str__`. That way we can have the DifferentiableGraphBackward node explain itself (e.g. by printing the graph (s)). This makes it easy to update the information being dumped when we change how the internal implementation works.

**Comment by zasdfgbnm** [comment]
@zdevito 
- The bottom of this stack (https://github.com/pytorch/pytorch/pull/28563) is rebased after #28535 get landed.
- I have removed the `graph` and added a `toString`.
- And the use case for this PR is shown on the top of this stack (https://github.com/pytorch/pytorch/pull/28856).

**Review by zdevito — COMMENTED** [review]
I'd like to avoid making the class structure here more complicated just so that we can print it out. Is it possible just to introduce a repr method on `autograd::Node` and just allow those to be printed out using custom behavior in Python? Having to work through the pImpl pattern for this already-private type is going to make it harder to read.

**Comment by zasdfgbnm** [comment]
@zdevito That sounds good! will do it.

**Comment by zasdfgbnm** [comment]
@zdevito I will close this and #28856 and implement the printing in a separate PR. Please land #28563 itself separately.

**Pull request closed without merging**
