### PR TITLE
Add __all__ for torch.distributed and fx modules

### PR DESCRIPTION
**Pull request by anjali411**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #80460

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM
Will leave someone from distributed to do a final stamp.

**Comment by anjali411** [comment]
@rohan-varma can you confirm if this looks ok?

**Review by rohan-varma — APPROVED** [review]
LG, thanks!

**Pull request closed without merging**
