### PR TITLE
Migrate jobs from windows.8xlarge.nvidia.gpu to windows.8xlarge.nvidia.gpu.nonephemeral

### PR DESCRIPTION
**Pull request by jeanschmidt**
This is a follow up for #100377

# About this PR

Due to increased pressure over our windows runners, and the elevated cost of instantiating and bringing down those instances, we want to migrate instances from ephemeral to not ephemeral.

Possible impacts are related to breakages in or misbehaves on CI jobs that puts the runners in a bad state. Other possible impacts are related to exhaustion of resources, especially disk space, but memory might be a contender, as CI trash piles up on those instances.

As a somewhat middle of the road approach to this, currently nonephemeral instances are stochastically rotated as older instances get higher priority to be terminated when demand is lower.

Instances definition can be found here: https://github.com/pytorch/test-infra/pull/4072

This is a second step in a multi-step approach where we will migrate away from all ephemeral windows instances and follow the lead of the `windows.g5.4xlarge.nvidia.gpu` in order to help reduce queue times for those instances. The phased approach follows:

* ✅ migrate `windows.4xlarge` to `windows.4xlarge.nonephemeral` instances under `pytorch/pytorch`
* 📣 migrate `windows.8xlarge.nvidia.gpu` to `windows.8xlarge.nvidia.gpu.nonephemeral` instances under `pytorch/pytorch`
* ⏳ submit PRs to all repositories under `pytorch/` organization to migrate `windows.4xlarge` to `windows.4xlarge.nonephemeral`
* ⏳ submit PRs to all repositories under `pytorch/` organization to migrate `windows.8xlarge.nvidia.gpu` to `windows.8xlarge.nvidia.gpu.nonephemeral`
* ⏳ terminate the existence of `windows.4xlarge` and `windows.8xlarge.nvidia.gpu`
* ⏳ evaluate and start the work related to the adoption of `windows.g5.4xlarge.nvidia.gpu` to replace `windows.8xlarge.nvidia.gpu.nonephemeral` in other repositories and use cases (proposed by @huydhn)

The reasoning for this phased approach is to reduce the scope of possible contenders to investigate in case of misbehave of particular CI jobs.

# Copilot Summary

### <samp>🤖 Generated by Copilot at 734c3f0</samp>

This pull request migrates the Windows GPU workflow jobs for the binary builds to use non-ephemeral runners instead of ephemeral runners. This is done to improve test stability and reduce flakiness. The change involves updating the `rockset_mocks.json` file, the generated workflow files, and the template file that the `generate_ci_workflows.py` script uses.

# Copilot Poem

### <samp>🤖 Generated by Copilot at 734c3f0</samp>

> _`runs-on` changes_
> _non-ephemeral runners_
> _for CUDA jobs_

issue: #101209

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Can you please explain why changes to `gql.mocks` are necessary? I.e. those are still fetch automatically from github, arent' they? Otherwise, looks good to me.

**Review by huydhn — APPROVED** [review]

**Comment by huydhn** [comment]
Just FYI, that mock JSON file can be deleted completely and respawn by running `test_trymerge.py` https://github.com/pytorch/pytorch/blob/main/.github/scripts/test_trymerge.py#L7-L8

I'm looking into the failure in the PR here a bit as it seems to be the same issue I'm seeing in trunk.  Some step still tries to put VS2022 into the runner and causes subsequent jobs to reinstall VS2019 and fails flakily.

**Comment by huydhn** [comment]
I think I get it now.  In the example I have, VS2022 installation came from this job https://github.com/pytorch/pytorch/actions/runs/4948937908/jobs/8856578170 and this draft PR https://github.com/pytorch/pytorch/pull/100094.

Let me try to see if we can keep both VS2019 and VS2022 instead of removing the older version every time.  If it doesn't work out, I will ask the author of https://github.com/pytorch/pytorch/pull/100094 to stay with VS2019.

**Review by ZainRizvi — APPROVED** [review]

**Pull request closed without merging**
