### PR TITLE
[Submodule] update submodule onnx==1.17.0

### PR DESCRIPTION
**Pull request by ptrblck**
Follow-up PR of: https://github.com/pytorch/pytorch/pull/138719

CC @malfet @ezyang

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by ptrblck** [comment]
I think the build issues are real:
```
Could not find any of CMakeLists.txt in /pytorch/third_party/onnx/third_party/benchmark
Did you run 'git submodule update --init --recursive'?
```
and we might need to delete: https://github.com/pytorch/pytorch/blob/869d1ad0b4d85e0528920949162f1bdcf6536bc6/setup.py#L445-L447
as `onnx/third_party/benchmark` was removed: https://github.com/onnx/onnx/tree/v1.17.0/third_party.
Updating the PR in a sec.

**Pull request closed without merging**
