### PR TITLE
Support remote caching requiring redis auth

### PR DESCRIPTION
**Pull request by yasyf**
cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by masnesral — APPROVED** [review]

**Comment by yasyf** [comment]
@masnesral @mikaylagawarecki anything you need from me to get across the line or you got it?

**Comment by masnesral** [comment]
@yasf sry looks like you'll need to rebase?

**Comment by yasyf** [comment]
@masnesral sorry missed this, done now

**Comment by masnesral** [comment]
Pretty confident these failures in rocm tests have nothing to do with this change.

**Pull request closed without merging**
