### PR TITLE
[EZ] Update sympy to 1.13.3

### LINKED ISSUE #143907: update `sympy` version in `requirement.txt`
### 🐛 Describe the bug

Now, sympy version is `1.13.3`, but `torch` is hard required `sympy` version to be `1.13.1`, it will cause inconvenient in an environment which require `sympy` to be latest. 

### Versions

<https://github.com/pytorch/pytorch/blob/a20765a9c1e578beb5e53f9a3ef0c13ea6839768/requirements.txt#L19>

cc @malfet @seemethere @pytorch/pytorch-dev-infra @chauhang @penguinwu

### PR DESCRIPTION
**Pull request by malfet**
And remove python>=3.9 check as it currently covers all supported python versions

Fixes https://github.com/pytorch/pytorch/issues/143907

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
Also probably a good backport candidate for 2.6

**Comment by malfet** [comment]
> Also probably a good backport candidate for 2.6

Hmm, let me check meta information, I thought that requirements.txt are just for local development, while PyPI wheels has an unpinned dependency.

**Review by huydhn — APPROVED** [review]

**Comment by evan0greenup** [comment]
@malfet , is it possible to add wildcard in `sympy` version like `1.13.*` or `>=1.13`, because in the future when `sympy` release new version, this issue will arise again. And it is rare for `sympy` to have break change.

**Pull request closed without merging**
