### PR TITLE
Re-enable detectron2_maskrcnn on CI

### PR DESCRIPTION
**Pull request by yanboliang**
#99665 has been fixed, we can re-enable these models on CI.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Comment by desertfire** [comment]
Looks like hitting a different error now.

**Comment by huydhn** [comment]
Wow, this one has been failing since April 28th.  AFAICT, here is the first commit where it starts failing https://hud.pytorch.org/pytorch/pytorch/commit/d4bf76c2a4d764356632e3eaaa209234c7980951

**Comment by yanboliang** [comment]
Yes, it seems https://github.com/pytorch/pytorch/pull/100101 doesn't implement the dispatch for CUDA. @tugsbayasgalan Is this just missing feature or we can't support CUDA?

**Comment by huydhn** [comment]
> Yes, it seems #100101 doesn't implement the dispatch for CUDA. @tugsbayasgalan Is this just missing feature or we can't support CUDA?

@tugsbayasgalan I think this is also failing llama https://hud.pytorch.org/pytorch/pytorch/commit/7012600abea0073b746b340f100efa0b2cb249a6 re-enabled by https://github.com/pytorch/pytorch/pull/100877

```
NotImplementedError: Could not run 'aten::_assert_async.msg' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_assert_async.msg' is only available for these backends: [CPU, Meta, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].
```

**Comment by tugsbayasgalan** [comment]
Will forward fix this. Pls don't revert the original PR

**Pull request closed without merging**
