### PR TITLE
Enabled BFloat16 support for cumsum, logcumsumexp, cumprod, cummin & cummax on CUDA

### PR DESCRIPTION
**Pull request by imaginary-person**
Enabled BFloat16 support for `cumsum`, `logcumsumexp`, `cumprod`, `cummin` & `cummax` on CUDA

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Test errors are real, this PR doesn't enable cummin/cummax

**Comment by imaginary-person** [comment]
Sorry, @ngimel, I hadn't looked at the CI results until now. I'll take a look & will request you again after fixing the issue. Thanks!

**Comment by imaginary-person** [comment]
Hello @ngimel, they were previously enabled & all the CI checks had passed, but GitHub had disabled them again when you merged the master branch of the main repo with this PR -

https://github.com/pytorch/pytorch/pull/57904/commits/5eceda87de1009bc587ef886757c192cd3083374

GitHub probably did this because `checkSameGPU`'s syntax has changed since. However, it wasn't supposed to modify the next line as well, as it usually doesn't modify lines that are revised in a PR, without notifying about conflicts.

**Comment by imaginary-person** [comment]
Hello @ngimel, the current CI failures are unrelated.
I had re-enabled `cummin` & `cummax` for BFloat16. Thank you!

**Pull request closed without merging**
