### PR TITLE
Vectorized bfloat16 binary op

### PR DESCRIPTION
**Pull request by XiaobingSuper**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #35172 bfloat16: enable basic math function
* #35092 bfloat16: vectorized unary ops
* #35082 bfloat16: vectorized clamp, clamp_min and clmap_max
* **#35034 Vectorized bfloat16 binary op**

Differential Revision: [D20721068](https://our.internmc.facebook.com/intern/diff/D20721068)

### CODE REVIEW

**Comment by XiaobingSuper** [comment]
This PR is about vectorized bfloat16 binary ops using AVX,  and  only enable the existing bfloat16 ops for easily code review. Thanks!

**Comment by XiaobingSuper** [comment]
@uyongw, @Jianhui-Li, @jgong5, @hongzhen1

**Comment by XiaobingSuper** [comment]
Performance data:
test script:
```
 import torch

 import timeit

 torch.manual_seed(1)
 #torch.set_num_threads(1)

 device = "cpu"
 print(f'device: {device}')
 for op in ('add', 'sub', 'mul', 'div'):
     for n, t in [(20_000, 200000),
                  (200_000, 20000)]:
         print(f'a.{op}(), numel() == {n} for {t} times')
         print(timeit.timeit(f'a.{op}(b)', setup=f'import torch; a =(torch.torch.randn({n}) * 10).           bfloat16(); b = (torch.torch.randn({n}) * 10).bfloat16()', number=t))
```

Test device: skx-8180(2 sockets).
before:
```
device: cpu
a.add(), numel() == 20000 for 200000 times
14.710887099034153
a.add(), numel() == 200000 for 20000 times
3.060519974969793
a.sub(), numel() == 20000 for 200000 times
14.807527677970938
a.sub(), numel() == 200000 for 20000 times
3.038525498996023
a.mul(), numel() == 20000 for 200000 times
9.95522077899659
a.mul(), numel() == 200000 for 20000 times
1.9494166749645956
a.div(), numel() == 20000 for 200000 times
10.89301436895039
a.div(), numel() == 200000 for 20000 times
2.1804280770011246
```
After:
```
device: cpu
a.add(), numel() == 20000 for 200000 times
1.3812953309970908
a.add(), numel() == 200000 for 20000 times
0.5422487650066614
a.sub(), numel() == 20000 for 200000 times
1.434274684987031
a.sub(), numel() == 200000 for 20000 times
0.49490866297855973
a.mul(), numel() == 20000 for 200000 times
1.342454238969367
a.mul(), numel() == 200000 for 20000 times
0.500671340036206
a.div(), numel() == 20000 for 200000 times
1.4676644339924678
a.div(), numel() == 200000 for 20000 times
0.5351831539883278
```
**num_threads=1**:
Before:
```
a.add(), numel() == 20000 for 200000 times
14.75224875495769
a.add(), numel() == 200000 for 20000 times
14.472290759033058
a.sub(), numel() == 20000 for 200000 times
14.770362120994832
a.sub(), numel() == 200000 for 20000 times
14.494997254980262
a.mul(), numel() == 20000 for 200000 times
9.726326660020277
a.mul(), numel() == 200000 for 20000 times
9.523499229981098
a.div(), numel() == 20000 for 200000 times
11.201515975000802
a.div(), numel() == 200000 for 20000 times
10.534031618968584
```
After:
```
a.add(), numel() == 20000 for 200000 times
1.4201767159975134
a.add(), numel() == 200000 for 20000 times
1.095123034028802
a.sub(), numel() == 20000 for 200000 times
1.4656740950304084
a.sub(), numel() == 200000 for 20000 times
1.1058329530060291
a.mul(), numel() == 20000 for 200000 times
1.3267527349526063
a.mul(), numel() == 200000 for 20000 times
1.0273849689983763
a.div(), numel() == 20000 for 200000 times
1.442022307019215
a.div(), numel() == 200000 for 20000 times
1.1398367249639705
```

**Comment by XiaobingSuper** [comment]
@ngimel @VitalyFedyunin , please help review this code, thanks!

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Can you please rebase to see if test failures resolve?

**Comment by XiaobingSuper** [comment]
@ngimel, code rebased.

**Comment by XiaobingSuper** [comment]
@ngimel , could you help see the internal failed cases? I can't see them. Thanks!

**Comment by ngimel** [comment]
This PR has landed already, for some reason it does not show here, the linking between internal PRs and here is broken. https://github.com/pytorch/pytorch/commit/639c68b2feb0bf7411d71899db0362e00b2ada67

**Pull request closed without merging**
