### PR TITLE
Fix six broken tests in test_ops.py

### PR DESCRIPTION
**Pull request by rec**
## The problem.

[A commit from three weeks ago](https://github.com/pytorch/pytorch/commit/82d00acfee96d043c84514dcfe081979fe86844c) appears to have broken five tests but was not caught by CI. 

[A later commit](https://github.com/pytorch/pytorch/commit/e05ea2b1797) which added a decomposition of `transpose_copy` added another broken test, also seemingly not detected, making six total (listed below).

They came to my attention when I updated some pending decomposition pull requests which passed CI, and started getting failures like [this](https://hud.pytorch.org/pr/134319) for a test unrelated to any of these pull requests, `TestCommonCPU.test_out__refs_transpose_copy_cpu_float32`

Running `python test/test_ops.py -k _copy` on `viable/strict` found failures for six `_refs` ops: `copysign`, `expand_copy`, `index_copy`, `t_copy`, `transpose_copy`, `view_copy`

## The solution

The original commit did actually cause breakage by slightly changing user-visible behavior (in a special case involving scalar tensors being copied between different devices). 

This pull request fixes that breakage in a reasonable way, but I don't understand why this error didn't appear in CI until I made later changes in the same area.

## To reproduce

To reproduce the six cases in your own client:

```
PYTORCH_OPINFO_SAMPLE_INPUT_INDEX=5 python test/test_ops.py TestCommonCPU.test_out__refs_view_copy_cpu_float32
PYTORCH_OPINFO_SAMPLE_INPUT_INDEX=2 python test/test_ops.py TestCommonCPU.test_out__refs_t_copy_cpu_float32
PYTORCH_OPINFO_SAMPLE_INPUT_INDEX=0 python test/test_ops.py TestCommonCPU.test_out__refs_index_copy_cpu_float32
PYTORCH_OPINFO_SAMPLE_INPUT_INDEX=7 python test/test_ops.py TestCommonCPU.test_out__refs_expand_copy_cpu_float32
PYTORCH_OPINFO_SAMPLE_INPUT_INDEX=0 python test/test_ops.py TestCommonCPU.test_out__refs_copysign_cpu_float32
PYTORCH_OPINFO_SAMPLE_INPUT_INDEX=4 python test/test_ops.py TestCommonCPU.test_out__refs_transpose_copy_cpu_float32
```

@amjames

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #130944
* __->__ #136653

### CODE REVIEW

**Comment by rec** [comment]
@amjames I took this out of draft.

It does seem to fix the issue with the decomp commits: https://github.com/pytorch/pytorch/pull/130941 (though I still need to rebase a couple of them to be super-sure).

So it'd be great to get this in, it'd unblock three other pull requests (one of which is also blocked by executorch, which I'm going to look at today even).

**Comment by rec** [comment]
@zou3519, would you be interested in looking at this? It concerns this commit of yours: https://github.com/pytorch/pytorch/commit/82d00acfee96d043c84514dcfe081979fe86844c

**Review by zou3519 — APPROVED** [review]

**Comment by zou3519** [comment]
Do we know why the failing tests weren't running in CI?

**Pull request closed without merging**
