### PR TITLE
Fix torch.clamp in MPS to handle NaN correctly

### LINKED ISSUE #120899: Inconsistent Behavior of torch.clamp with NaN Values on MPS Device
### 🐛 Describe the bug

I have encountered an issue with the torch.clamp function in PyTorch when it is used on tensors that reside on the Metal Performance Shaders (MPS) device. Specifically, the function behaves differently with NaN values on tensors across different devices (mps vs. cpu/cuda). This inconsistency can lead to unexpected results when working with NaN values on MPS devices.

When using torch.clamp on a tensor with NaN values on an MPS device, If both min and max parameters are set, the function replaces NaN values with the min value. If only one of min and max parameters are set, the function replaces NaN values with the min value. If only one of the min and max parameters is set, the function replaces NaN values with the specified min or max parameter.

This behavior is inconsistent with how torch.clamp operates on the same tensor when it is on a CPU device, where NaN values remain unchanged.

```python
import torch

t_mps = torch.tensor([torch.nan, 1, 2], device="mps")
print(torch.clamp(t_mps, min=-100, max=100))
# tensor([-100.,    1.,    2.], device='mps:0')
print(torch.clamp(t_mps, min=-100))
# tensor([-100.,    1.,    2.], device='mps:0')
print(torch.clamp(t_mps, max=100))
# tensor([100.,   1.,   2.], device='mps:0')

t_cpu = torch.tensor([torch.nan, 1, 2], device="cpu")
print(torch.clamp(t_cpu, min=-100, max=100))
# tensor([nan, 1., 2.])
print(torch.clamp(t_cpu, min=-100))
# tensor([nan, 1., 2.])
print(torch.clamp(t_cpu, max=100))
# tensor([nan, 1., 2.])
```

Expected Behavior:
The behavior of torch.clamp should be consistent across different devices. When dealing with NaN values, torch.clamp should not replace NaN values.

### Versions

PyTorch version: 2.2.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.3.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:35:41)  [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-14.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.1
[pip3] torchaudio==2.2.1
[pip3] torchvision==0.17.1
[conda] numpy                     1.26.4           py39h7aa2656_0    conda-forge
[conda] pytorch                   2.2.1                   py3.9_0    pytorch
[conda] torchaudio                2.2.1                  py39_cpu    pytorch
[conda] torchvision               0.17.1                 py39_cpu    pytorch

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

### PR DESCRIPTION
**Pull request by lamroger**
Fixes #120899

So this is interesting. There are methods that specifically propagate NaN instead of clamping to real numbers. 
https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph/3857573-maximumwithnanpropagationwithpri

### CODE REVIEW

**Comment by lamroger** [comment]
Still need to write tests

**Review by malfet — DISMISSED** [review]
Thank you for the fix, LGTM

My only concearn, do you know anything about relative performance of `clampWithPrimaryTensor:` vs one that propagates NaNs?

**Comment by lamroger** [comment]
> My only concearn, do you know anything about relative performance of `clampWithPrimaryTensor:` vs one that propagates NaNs?

I don't - @kulinseth do you happen to know?

I tried a very simple test locally 
```
       t_mps = torch.ones(1000000000, device="mps")

        st = time.time()
        clamp_min_max_mps = torch.clamp(t_mps, min=-100, max=100)
        et = time.time()

        print("MPS time: ", et - st)
```
Old implementation: MPS time:  0.0034933090209960938
New implementation: MPS time:  0.004127025604248047

(i ran a few times and they're around the same times each time)

Better to know what happens under the hood though

**Comment by lamroger** [comment]
I booked an appt with the DevX team on Friday to figure out what to do next but if anyone can help with the CI tags (?) before that'd be cool too

**Comment by lamroger** [comment]
Thanks @huydhn ! 

Hi @malfet , I found the issue. When I overwrote the output tensor, I think it loses context so when someone tries to auto-differentiate,  it misses half of the clamp operations. I chained them together and 
`python test/test_mps.py -k test_output_grad_match_clamp_cpu_float16 `
passes now. Could you take another look and queue CI if it looks good? Thanks!

**Review by malfet — APPROVED** [review]
Applied some cleanup changes, looks good to me

**Comment by huydhn** [comment]
As @malfet calls out, it doesn't look right that MPS job is marked as unstable and skipped in the PR.  Let me take a closer look.  This is not related to the PR though, so no action is needed from @lamroger

**Comment by huydhn** [comment]
> As @malfet calls out, it doesn't look right that MPS job is marked as unstable and skipped in the PR. Let me take a closer look. This is not related to the PR though, so no action is needed from @lamroger

This is my fault.  I wrongly added `test-config/default` into the PR when I did the original review.  This stopped MPS job from running because it has `mps` instead of `default` config.  The output about the job being unstable is misleading and I'll push a fix for that.

**Comment by huydhn** [comment]
The PR to tweak the CI filter script is here https://github.com/pytorch/pytorch/pull/122155

**Pull request closed without merging**
