### PR TITLE
[PyTorch] Inline RecordFunctionCallback::shouldRun

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #48629 [PyTorch] Use plain old function pointer for RecordFunctionCallback
* #48620 [PyTorch] remove convenience RecordFunctionCallback interface
* **#48286 [PyTorch] Inline RecordFunctionCallback::shouldRun**

RecordFunction initialization is a hot path. shouldRun often does little enough work that the function prologue takes a significant proportion of its time. So, this diff forces it to be inline.

Differential Revision: [D25108879](https://our.internmc.facebook.com/intern/diff/D25108879/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D25108879/)!

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Thanks!

**Comment by dhruvbird** [comment]
@kimishpatel IIUC, this diff will make recording cheaper. Also @ilia-cher  has another change that by default restricts the recording to happen only for top level operator invocations. I think that is inline with what we want to do with mobile interpreter eh?

**Comment by kimishpatel** [comment]
> @kimishpatel IIUC, this diff will make recording cheaper. Also @ilia-cher has another change that by default restricts the recording to happen only for top level operator invocations. I think that is inline with what we want to do with mobile interpreter eh?

I dont know what ilia's diff gonna do. Once I see it I will have better understanding. It will definitely help to have some RecordFunction API that will do recording only for root ops. Then we can remove other hacks we have in lite interpreter.

**Comment by ilia-cher** [comment]
@dhruvbird @kimishpatel no, the diff is not about top-level functions, but a speed up for RecordFunction usage itself, it's not that interesting for you since you add a non-sampled callback, my PR improves the default case when we don't have callbacks like these
(https://github.com/pytorch/pytorch/pull/48289)
you don't need to change your observers

**Pull request closed without merging**
