### PR TITLE
remove overly restrictive checks for cudagraph

### PR DESCRIPTION
**Pull request by albanD**
Finish fixing https://github.com/pytorch/pytorch/issues/80809

### CODE REVIEW

**Review by jbschlosser — APPROVED** [review]
LGTM

**Comment by Equim-chan** [comment]
This issue #80809 exists in adam too. Is there a particular reason to apply the fix on adamw only?

**Comment by jbschlosser** [comment]
@Equim-chan I think this was addressed for Adam in #80222

**Pull request closed without merging**
