### PR TITLE
[2/N] [Dispatchable Collectives] Extract ProcessGroup::Work into a separate class and update references

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #84423 [8/N] [Dispatchable Collectives] Update allgather with CPU / CUDA implementations
* #83916 [7/N] [Dispatchable Collectives] Update reduce with CPU / CUDA implementations
* #83876 [6/N] [Dispatchable Collectives] Update recv with CPU / CUDA implementations
* #83859 [5/N] [Dispatchable Collectives] Update send with CPU / CUDA implementations
* #83810 [4/N] [Dispatchable Collectives] Update all_reduce_ with CPU / CUDA implementations
* #83735 [3/N] [Dispatchable Collectives] Update broadcast_ with CPU and CUDA implementations
* **#83680 [2/N] [Dispatchable Collectives] Extract ProcessGroup::Work into a separate class and update references**

### Changes
- Move ProcessGroup::Work into its own class and update all the references to it / header includes.

### Context
https://github.com/pytorch/pytorch/issues/86225

Differential Revision: [D38839212](https://our.internmc.facebook.com/intern/diff/D38839212)

### CODE REVIEW

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38839212).

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38839212).

**Review by kwen2501 — APPROVED** [review]
LGTM! Thanks!

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38839212).

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38839212).

**Pull request closed without merging**
