### PR TITLE
Abstract away git repo during tests

### PR DESCRIPTION
**Pull request by ZainRizvi**
### Description
During unit tests we want to return fake data for any methods that rely on a local git repository. Otherwise those tests will fail when run in an environment that doesn't have the pytorch repo checked out (such as fbinternal or a tarball download)

Also refactored existing tests to use the new DummyGitRepo

### Issue
N/A

### Testing
Validating old behavior:
Removed the `.git` folder locally to effectively delete the git repository. Then ran `python3 .github/scripts/test_trymerge.py` to ensure the test failed

Validating fix:
Ran `python3 .github/scripts/test_trymerge.py` both with and without the `.git` folder

### CODE REVIEW

**Review by zengk95 — APPROVED** [review]
lgtm pending lint

**Review by huydhn — APPROVED** [review]
LGTM! Just FYI that the OLD test before this PR could also fail when you do a shallow checkout, i.e. `git clone --depth 1`, which is used commonly in CI. It's still a git repo, but it wouldn't have the commit you are looking for :P

**Review by malfet — APPROVED** [review]
Please fix lint, otherwise LGTM
Consider nit

**Pull request closed without merging**
