### PR TITLE
TorchScript add check if quantized

### PR DESCRIPTION
**Pull request by z-a-f**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#32890 TorchScript add check if quantized**

Differential Revision: [D19673463](https://our.internmc.facebook.com/intern/diff/D19673463)

### CODE REVIEW

**Comment by jerryzh168** [comment]
Why? could you implement the required method?

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit e953fcc0:


**None of the build failures appear to be your fault**.

* **1/1** recognized as flaky :snowflake:
    * Re-run these jobs?


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=e953fcc0d90e0582438fb8443cb5c1753f4e35f3).

### :snowflake: 1 failure recognized as flaky
The following build failures have been detected as flaky and **may not be your fault**:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4394682) pytorch_linux_xenial_py3_6_gcc5_4_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=93952034) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=93952034)) :snowflake:
<details>
<summary>
<code>$<3>$<3> ae193ec89b35: Pushing   2.91GB/2.91GB $<3>$<3> ae193ec89b35: Pushing   2.91GB/2.91GB toomanyrequests: Rate exceeded</code>
</summary>

```
$<3>$<3> eea1661bdba1: Preparing   
$<3>$<3> 5bb9fbc1099e: Preparing   
$<3>$<3> 0d9b5dad09df: Preparing   
$<3>$<3> a80eb84c4169: Preparing   
$<3>$<3> 85775ce071b3: Preparing   
$<3>$<3> bfd07f554dc2: Preparing   
$<3>$<3> 00c6fc364d3a: Preparing   
$<3>$<3> 77008e118980: Preparing   
$<3>$<3> 6cb741cb00b7: Preparing   
$<3>$<3> f36b28e4310d: Preparing   
ae193ec89b35: Pushing   2.91GB/2.91GB $<3>$<3> ae193ec89b35: Pushing   2.91GB/2.91GB toomanyrequests: Rate exceeded 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by z-a-f** [comment]
> Why? could you implement the required method?

Do you mean the `.double`? If so, I could, it's just this seemed to be easier :)

**Comment by jerryzh168** [comment]
I see, I thought we also might want to compare the quantized info. Looks like this is just numeric comparison, then this should be fine.

**Review by jerryzh168 — APPROVED** [review]

**Pull request closed without merging**
