### PR TITLE
Implement adding bias vector into structured sparse linear operator

### PR DESCRIPTION
**Pull request by alexsamardzic**
Same as  #100881, but without ghstack.

cc @albanD

### CODE REVIEW

**Comment by cpuhrsch** [comment]
See https://github.com/pytorch/pytorch/issues/101804 for reference on size of this PR

**Comment by malfet** [comment]
@alexsamardzic are you checking in cutlass as is, or are you introducing some modifications?
And why can't you use the one already checked into `third_party/cutlass` folder?

**Review by malfet — CHANGES_REQUESTED** [review]
Please add a more detailed description that explains what changes were made to cutlass headers which are already available in `third_party/cutlass` folder

**Comment by alexsamardzic** [comment]
The rationale is provided in [following comment](https://github.com/pytorch/pytorch/pull/100881#discussion_r1189157086) on the original PR.  In short, linear operator in general implements $xW^{T}+b$ calculation, and this variation intends to provide faster calculation for the case when $W$ matrix has 2:4 sparsity pattern, by utilizing corresponding hardware support available on Ampere and newer GPUs, exposed through CUTLASS.  However, CUTLASS has a limitation that matrix having mentioned sparsity pattern must be the first operand of matrix multiplication, so the linear operator here has to be implemented as $(Wx^{T}+b^{T})^{T}$, which means that bias vector $b$ is to be added to each column of $Wx^{T}$ product.  CUTLASS has another limitation, that it supports adding a vector to each column of a product in column-major layout, and alternatively to each row of a product in row-major layout; however, at the moment it can produce product of sparse (in 2:4 sparsity format) and dense matrix in row-major layout only.  Thus, there is a need to extend CUTLASS to support adding bias vector to the product in a way that is needed here.  The files added are to implement this functionality, and they differ from corresponding files from CUTLASS source tree (that PyTorch keeps under `third_party/cutlass`).  The main difference is in `custom_predicated_tile_iterator.h` file, the rest of customized files is just to propagate the change upwards through the CUTLASS hierarchy of templates instantiation.

The changes made are according to suggestions from CUTLASS developers, and there is interest to have these changes included upstream.  Here is [PR](https://github.com/NVIDIA/cutlass/pull/951) opened in CUTLASS GitHub repo for this purpose (the CUTLASS repo PR has the same changes as ones introduced to PyTorch through this PR, but as PyTorch requires files added to be processed by linter, it's easier to examine the changes in the CUTLASS repo PR), and here is [issue](https://github.com/pytorch/pytorch/issues/101804) opened in PyTorch repo to track progress of this, and eventually to have customized CUTLASS files removed from PyTorch once when eventually appear upstream.  The rationale for still have this PR merged in PyTorch is to be able to utilize the functionality mentioned as soon as possible.

**Comment by alexsamardzic** [comment]
Closing, as original PR #100881 is re-opened, with latest updates.

**Pull request closed without merging**
