### PR TITLE
[dynamo] fix general attr on tensor for user-provided attributes

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #94332

**Problem**: For a tensor `x`, you can assign `x.my_attr = 3.14` and then later access it. Dynamo does not support this right now; it errors out with an AttributError (it was broken in #91840).

**Fix**: This fixes the problem by catching AttributeErrors in dynamo if we try to access an attr that does not exist on a standard torch.Tensor.

**Tests**: Added tests for accessing and setting attributes to make sure dynamo does not error out.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Comment by davidberard98** [comment]
mirroring offline discussion with Yanbo: he asked, "why did I add NameError previously, instead of AttributeError?". I'm not sure; I initially found by trial-and-error that NameError was the expected exception, but this is incorrect. Python docs for inspect.getattr_static show that catching an AttributeError is the correct way to handle this: https://docs.python.org/3/library/inspect.html#inspect.getattr_static.

**Pull request closed without merging**
