### PR TITLE
Add reduce arg to BCELoss

### PR DESCRIPTION
**Pull request by zou3519**
As per #264. When reduce is False, BCELoss outputs a loss per element of the input tensor. When reduce is True (default), the current behavior is kept.

### Test Plan
test/run_test.sh
Added unit test for the reduce=False case. Also added a reference function to the reduce=True unit test.

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by zou3519** [comment]
There seems to be some numeric errors in the tests (error is slightly greater than 0.0002 sometimes for BCELoss). I'm looking into it

**Comment by yogeshg** [comment]
Hi @zou3519, great work, thanks!! any updates on this?

**Comment by zou3519** [comment]
@yogeshg I'll take another look at this later today. The cuda kernel I wrote has some numeric error that passes the error threshold; after that's addressed this should be fine.

**Comment by zou3519** [comment]
Should be good now.

The module tests compares forward/backward of cpu double vs cuda float. When the value of the output (or gradInput) is too large (> 100) because of the input, target, and weights, this results in a precision error of > 2e-4 for some random initializations. To fix it, I reduced the size of the random input/weight in the test.

**Pull request merged**
