### PR TITLE
Add standalone torch._inductor.compile() API

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #95594

This fixes support for inductor compiling non-dynamo generated FX graphs.

cc @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by bertmaher — APPROVED** [review]
Cool, thanks for doing this!

**Review by desertfire — APPROVED** [review]
This would also benefit AOT Inductor. Thanks!

**Pull request closed without merging**
