### PR TITLE
Switch some more SymInt tests to TORCH_CHECK_ALWAYS_SHOW_CPP_STACKTRACE

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #112626

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Comment by albanD** [comment]
Why these ones?
We generally don't want to show cpp stack traces to users. And if you're in environment where you always want them you can globally define TORCH_SHOW_CPP_STACKTRACES in global env and it will always show up.

**Comment by ezyang** [comment]
The main one I wanted to get was https://github.com/pytorch/pytorch/pull/112626/files#diff-d1abff1613cdbe0f4572ae2a6f83080dc4d438720af6d69296b2eb5d218fd2b1R129 which is a supremely unhelpful error message when it gets triggered from calling into a custom op. The C++ backtrace really helps there.

The other two I haven't seen in the wild, but it seemed also helpful to see the C++ traces.

In general, the idea is that if an error is raised because some C++ code is written incorrectly, I want to show the cpp stacktrace by default.

**Review by bdhirsh — APPROVED** [review]

**Pull request closed without merging**
