### PR TITLE
[CUDNN NHWC CONVOLUTION] Re-stride input tensors for wgrad in cudnn_convolution

### PR DESCRIPTION
**Pull request by jjsjann123**

### CODE REVIEW

**Review by VitalyFedyunin — DISMISSED** [review]
Thanks for quick turn around!

**Comment by jjsjann123** [comment]
hmmm, even forward errors out on Windows build.
What is the cudnn version on Windows build? log doesn't give me anything.
```
======================================================================
ERROR: test_conv_cudnn_nhwc_support (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 318, in wrapper
    fn(*args, **kwargs)
  File "test_nn.py", line 7654, in test_conv_cudnn_nhwc_support
    o = torch.conv2d(input, weight, None, (2, 1), (1, 1), (1, 1), 1)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM```

**Comment by VitalyFedyunin** [comment]
`curl --retry 3 -O https://ossci-windows.s3.amazonaws.com/cudnn-10.1-windows10-x64-v7.6.4.38.zip`

**Comment by jjsjann123** [comment]
#33918 issue filed to track the failure.
Disabled the test to unblock the PR.

**Pull request closed without merging**
