### PR TITLE
[dynamo] Support reading attributes from pybind objects

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134630

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by jansel — APPROVED** [review]
I worry about side effects in C++ here... I wonder if there is a way we could check for them.

**Comment by anijain2305** [comment]
> I worry about side effects in C++ here... I wonder if there is a way we could check for them.

Yes, I was thinking about that. But, I couldn't think of a way. I am worried about global state changes. The only rationalization I have is that this is well-contained, property with instancemethod fget.

**Pull request closed without merging**
