### PR TITLE
UFMT  formatting on test/export

### PR DESCRIPTION
**Pull request by fffrog**
Partially addresses https://github.com/pytorch/pytorch/issues/123062

Ran lintrunner on:
test/export

Detail:
```Shell
$ lintrunner -a --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```

### CODE REVIEW

**Review by shink — DISMISSED** [review]

**Comment by ezyang** [comment]
needs rebase now

lintcheck.sh reveals this diff which is OK

```
diff --git a/test/export/test_passes.py b/test/export/test_passes.py
index c7240ec0ee2..79cfbd68086 100644
--- a/test/export/test_passes.py
+++ b/test/export/test_passes.py
@@ -657,8 +657,8 @@ def forward(self, arg_0):
     sub = torch.ops.aten.sub.Tensor(add_1, 1)
     sub_1 = torch.ops.aten.sub.Tensor(add_2, 1)
     return pytree.tree_unflatten((add_1, add_2, sub, sub_1), self._out_spec)
-    """,  # noqa: B950
-        )
+    """,
+        )  # noqa: B950
         mod, args = self.SET_GRAD_ENABLED_TESTS["ctx_manager_multi_dep_no_grad"]
         self.assertExpectedInline(
             mod.code.strip("\n"),
@@ -677,8 +677,8 @@ def forward(self, arg_0):
     sub = wrap_with_set_grad_enabled_1[0]
     sub_1 = wrap_with_set_grad_enabled_1[1];  wrap_with_set_grad_enabled_1 = None
     return pytree.tree_unflatten((add_1, add_2, sub, sub_1), self._out_spec)
-    """,  # noqa: B950
-        )
+    """,
+        )  # noqa: B950
 
     def test_sequential_split(self):
         for gm, args in self.SEQUENTIAL_SPLIT_INLINE_TESTS.values():
```

**Comment by FFFrog** [comment]
> lintcheck.sh

Done.
In the future, I will complete the preparation work first and then submit the PR.

**Comment by ezyang** [comment]
@FFFrog actually it's fine, I need to run lintcheck.sh anyway so it's not a big deal

**Review by ezyang — DISMISSED** [review]

**Comment by PaliC** [comment]
@pytorchbot revert -m "lint is still broken" -c nosignal

https://hud.pytorch.org/pytorch/pytorch/commit/ec7551d1b783e284cedddeb9aeabb285e653c480
Try running lintrunner -a  -m origin/main

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
