### PR TITLE
[ONNX] Run type promotion test in CI and update the table

### PR DESCRIPTION
**Pull request by justinchuby**
cc @gramalingam @xadupre

### CODE REVIEW

**Review by gramalingam — APPROVED** [review]

**Comment by xadupre** [comment]
It is difficult to guess the impact of this just based on the diff. Do you have a concrete case in mind you could share?

**Comment by justinchuby** [comment]
I don’t expect any significant impact. This just enables the test in CI so our type promotion rules are in sync with PyTorch core

**Review by xadupre — APPROVED** [review]

**Comment by linshokaku** [comment]
Could you please explain why the type promotion was removed from `aten::rsub`, as I am experiencing the effects of its removal?

**Comment by xadupre** [comment]
TypePromotion is not removed but we reduced its scope. The converter can handle that later and make a better decision. But one case may have gone through our unit tests. Can you share more details?

**Comment by linshokaku** [comment]
I'm sorry. I used a translation machine, so the text turned out differently than I intended.

https://github.com/pytorch/pytorch/pull/135915/files#diff-09ad6043386a0d653eec979ed59d0b59cb509c0f092ff5f966f128da90895925L927-L929
I am talking about the promotion rule of aten::rsub that was deleted in this line.

Due to this change, this type promotion is no longer performed. 
before:
```
    rsub = torch.ops.aten.rsub.Scalar(exp, 1);  exp = None
```
after type promotion:
```
    scalar_tensor_default = torch.ops.aten.scalar_tensor.default(1, dtype = torch.float32)
    rsub = torch.ops.aten.rsub.Tensor(exp, scalar_tensor_default);  exp = scalar_tensor_default = None
```
Could you please explain the reason for this?

**Comment by xadupre** [comment]
When you say after type promotion, it is before this PR or after? Anyway, we need to fix that case cc @justinchuby. The converter can also decide to cast results. It is usually more accurate to do that at that level.

**Comment by justinchuby** [comment]
Probably because the type promotion rule was removed by the op meta definition as the rules on the onnx side were generated from it. @xadupre i can fix rsub.Scalar in torchlib. 

@linshokaku could you share a short snippet where this op shows op and resulted in incorrect onnx model?

**Comment by justinchuby** [comment]
@linshokaku Please see https://github.com/microsoft/onnxscript/issues/2137#issuecomment-2754935929

**Comment by linshokaku** [comment]
https://github.com/microsoft/onnxscript/blob/1d5972fc64f55a74a780e449859afce362ba6a8a/onnxscript/function_libs/torch_lib/ops/core.py#L7495-L7499

Since I was using an old version of onnxscript, the decomposition of rsub was not applied and it was exported as-is. I have confirmed that everything works correctly by using the latest version. Thank you for your confirmation.

**Pull request closed without merging**
