### PR TITLE
Small typo fix in nn.utils.parametrizations

### LINKED ISSUE #79735: Typo in nn.utils.parametrizations.orthogonal
### 🐛 Describe the bug

Small typo report: in `torch.nn.utils.parametrizations.orthogonal.py` line 261 the error message reads:

            "Module '{}' has no parameter ot buffer with name '{}'".format(module, name)

I believe 'ot' should be 'or'. 

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-113-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: GPU 0: Tesla V100-PCIE-16GB
Nvidia driver version: 515.43.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.0.4
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.13
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.22.3           py39he7a7128_0  
[conda] numpy-base                1.22.3           py39hf524024_0  
[conda] pyg                       2.0.4           py39_torch_1.11.0_cu113    pyg
[conda] pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-cluster           1.6.0           py39_torch_1.11.0_cu113    pyg
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-scatter           2.0.9           py39_torch_1.11.0_cu113    pyg
[conda] pytorch-sparse            0.6.13          py39_torch_1.11.0_cu113    pyg
[conda] pytorch-spline-conv       1.2.1           py39_torch_1.11.0_cu113    pyg
[conda] torchaudio                0.11.0               py39_cu113    pytorch
[conda] torchvision               0.12.0               py39_cu113    pytorch

cc @svekars @holly1238

### PR DESCRIPTION
**Pull request by zazyzaya**
Fixes #79735

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
Thank you for correcting this!

**Comment by Lezcano** [comment]
@albanD could you approve this one and merge it?

**Review by albanD — APPROVED** [review]
Thanks for the fix!

**Pull request closed without merging**
