### PR TITLE
[ONNX] Apply patch for undefined behavior

### PR DESCRIPTION
**Pull request by abock**
Original ONNX PR: https://github.com/onnx/onnx/pull/4823

### CODE REVIEW

**Review by justinchuby — APPROVED** [review]
💪

**Comment by abock** [comment]
The four failures appear unrelated to this PR.

**Comment by BowenBao** [comment]
@malfet please take a look. The patch is derived from this ONNX PR: https://github.com/onnx/onnx/pull/4823

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Remove 2.0 milestone for now (not sure why should it go there)

**Comment by BowenBao** [comment]
> Remove 2.0 milestone for now: not sure why it's critical to pick for the release as there are no regression tests/user reports of the failure.

Actually there is. By tracing all the way back from the onnx PR, it seems it's reported in #93174. The thread derailed a bit to workarounds and other issues/aspects, but I believe this patch fixes the original issue. @justinchuby could comment more.

**Comment by justinchuby** [comment]
The patch fixes a meta specific use case as mentioned by @BowenBao

**Comment by kit1980** [comment]
> The patch fixes a Meta specific use case as mentioned by @BowenBao

It was a one-off request that is resolved now, so this is not urgent for the release.

**Comment by justinchuby** [comment]
Closed as obsolete.

**Pull request closed without merging**
