### PR TITLE
PyTorch makes friends with clang-tidy

### PR DESCRIPTION
**Pull request by goldsborough**
This PR introduces PyTorch to the wonderful world of [clang-tidy](http://clang.llvm.org/extra/clang-tidy/). More precisely it:

1. Adds a `.clang-tidy` configuration file with some warnings manually weeded out,
2. Adds a script called `tools/clang_tidy.py`

At a basic level, this script:

1. Allows you to run clang tidy on code within PyTorch,
2. Allows you to run clang tidy only on source changes from your most recent Git revision, so that you (almost) only see warnings from the source lines you touched, whose lint errors you are the direct perpetrator of.

# FAQ

### Q: I enjoy having bugs in my code, and would like to continue writing bugs in my code without disturbance. Will this PR prevent me from doing so?

A: No, this script is currently provided only for people interested in *removing* bugs from their code on a voluntary basis, at their own effort (of running the script). Everyone else can ignore it. 

### Q: What is the basic way I can try this out right now, on a Mac?

A: 
1. `brew install llvm`
2. `python tools/clang_tidy.py -c <clang-tidy-executable> -p <path-you-want-to-lint>`

Where:

1. `<clang-tidy-executable>` is `/usr/local/Cellar/llvm/<version>/bin/clang-tidy`
2. `<path-you-want-to-lint>` is e.g. `torch/csrc/api`
3. See what a mess our codebase is: https://gist.github.com/goldsborough/354b2f93c4e0b819fdc68c4633c9b221

### Q: How can I lint only the *lines of code* I am currently changing, or changed in my latest commit?

A: `python tools/clang_tidy.py -c <clang-tidy-executable> -p <path-you-want-to-lint> -r HEAD`

This will:

1. Perform a `git diff HEAD`
2. Find out *what lines you changed exactly*
3. Run clang tidy only on those lines.

Say I have this function:

```cpp
template <typename Derived>
void RNNBase<Derived>::reset_parameters() {
  auto stdv = 1.0 / std::sqrt(hidden_size_);
  for (auto& p : this->parameters()) {
    p.second.data().uniform_(-stdv, stdv);
  }
}
```

and all I change in my commit is to add a pointer that I assign `NULL` to (evil):

```cpp
template <typename Derived>
void RNNBase<Derived>::reset_parameters() {
  int* p = NULL; // added!
  auto stdv = 1.0 / std::sqrt(hidden_size_);
  for (auto& p : this->parameters()) {
    p.second.data().uniform_(-stdv, stdv);
  }
}
```

I only want lints for that line, not all lines in the file or project. So I run

`python tools/clang_tidy.py -c $CLANG_TIDY -p torch/csrc/api -d tools/cpp_build/build/libtorch -r HEAD`

and (only!) get

```
/home/psag/pytorch/pytorch/torch/csrc/api/src/nn/modules/rnn.cpp:69:12: warning: use nullptr [modernize-use-nullptr]
  int* p = NULL;
           ^~~~~
           nullptr
```

### Q: What are all the things I can do?

A:

```
usage: clang_tidy.py [-h] [-c CLANG_TIDY_EXE] [-e EXTRA_ARGS [EXTRA_ARGS ...]]
                     [-g GLOB [GLOB ...]] [-x REGEX [REGEX ...]]
                     [-d COMPILE_COMMANDS_DIR] [-r REVISION]
                     [-p PATHS [PATHS ...]] [-s] [-v]
                     [--config-file CONFIG_FILE] [--checks CHECKS]

Run Clang-Tidy (on your Git changes)

optional arguments:
  -h, --help            show this help message and exit
  -c CLANG_TIDY_EXE, --clang-tidy-exe CLANG_TIDY_EXE
                        {ath to clang-tidy executable
  -e EXTRA_ARGS [EXTRA_ARGS ...], --extra-args EXTRA_ARGS [EXTRA_ARGS ...]
                        Extra arguments to forward to clang-tidy
  -g GLOB [GLOB ...], --glob GLOB [GLOB ...]
                        File patterns as UNIX globs (no **)
  -x REGEX [REGEX ...], --regex REGEX [REGEX ...]
                        File patterns as regexes
  -d COMPILE_COMMANDS_DIR, --compile-commands-dir COMPILE_COMMANDS_DIR
                        Path to the folder containing compile_commands.json
  -r REVISION, --revision REVISION
                        Git revision to get changes from
  -p PATHS [PATHS ...], --paths PATHS [PATHS ...]
                        Lint only the given paths
  -s, --show-command-only
                        Only show the command to be executed, without running
                        it
  -v, --verbose         Verbose output
  --config-file CONFIG_FILE
                        Path to a clang-tidy config file. Defaults to '.clang-
                        tidy'.
  --checks CHECKS       Appends checks to those from the config file (if any)
```

### CODE REVIEW

**Review by ezyang — COMMENTED** [review]
How far is HEAD from being clang-tidy clean, and will we ever enforce this in CI?

**Comment by goldsborough** [comment]
Sort of far, see https://gist.github.com/goldsborough/354b2f93c4e0b819fdc68c4633c9b221 for the warnings emitted for all of `torch/csrc`. I think we'd have to clean up all the warnings first, and spend some more time using it locally to weed out warnings that we don't want. Once we are happy with that, we could add a CI job that runs clang tidy on the user's changes.

**Comment by goldsborough** [comment]
I would like to land this asap so that I can use it on my PRs and let others know how to use it. I think it does no harm to anyone not interested in this @ezyang @apaszke

**Review by soumith — APPROVED** [review]

**Comment by apaszke** [comment]
As long as clang-tidy doesn't complain about the actual code formatting, then I'd be very happy to add it as part of CI. It's kind of like `-Werror`.

**Pull request merged**
