### PR TITLE
use condition_variable and wait_until in nccl dump on timeout

### PR DESCRIPTION
**Pull request by jeffdaily**
Fixes test_c10d_nccl.py -k test_timeout_dumps_timing_enabled_True.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jeffdaily** [comment]
@huydhn @malfet @atalman this PR should fix some of our distributed tests.

**Review by atalman — APPROVED** [review]
Looks good. I do see this test is failing on periodic currently and passing on this PR

**Pull request closed without merging**
