### PR TITLE
Graph-break on FSDP in dynamo

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #87418
* __->__ #87420

Why we want to graph-break FSDP
- FSDP has communication ops during forward and backward which we currently can't trace into the graph but also want to ensure are overlapped with compute
- dynamo has issues tracing into or capturing a call to fsdp module without a break (see below)

How we graph-break on FSDP
- marking FSDP.forward code as skip means the code frames will graph-break; but in this case all of torch.* is listed in skipfiles.py anyway, so this is taken care of
- disallowing the FSDP module prevents dynamo trying to record a 'call_module(FSDPmodule)' node into a graph, which happens earlier than the graphbreak that would be caused by skip, and causes additional issues: dynamo deepcopies modules before call-module handling, and FSDP module isn't trivially deep-copyable

cc @jansel @lezcano @fdrocha @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
I think you updated the submodule ideep by mistake in this PR.

**Comment by aazzolini** [comment]
@wconstab , thanks for the fix, it looks like the right thing to do!
The one concern I have about this is discoverability -- reading the code it will be hard to figure out why fsdp is being skipped -- I wonder if there is opportunity here to add a docstring to these skip rules so that users and code readers don't get surprised?

**Review by aazzolini — APPROVED** [review]
Fix sounds good, just consider whether adding a comment somewhere in the code explaining the behavior is feasible.

**Comment by wconstab** [comment]
Thanks @jansel I hate submodules sometimes

@aazzolini I was discussing with @jansel, and we think the skipfiles+allowmodules infra needs a refresh.  The refresh would ideally make this a little less confusing.  But I'm gonna write some comments in those files at least reflecting what i've learned so far.

**Comment by wconstab** [comment]
@jansel i fixed the submodule, but if you could also review the correctness of my docstrings i'd appreciate it.

**Comment by wconstab** [comment]
@pytorchbot merge -f "Spurious CI failures (accuracy checks on inductor and macos builds, seem unlikely related to this PR)"

cc @jansel feel free to comment on my comments on skipfiles here and i'll update them

**Pull request closed without merging**
