### PR TITLE
Ordering placeholder and get_attr nodes in unflattened module

### PR DESCRIPTION
**Pull request by titaiwangms**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #116910

Previous to this PR, the generated unflattened module could mix up the order of `placeholder` and newly created `get_attr`. As `placeholder` is the input of a function, it should be placed ahead of `get_attr` nodes.

Before:
```bash
test/export/test_unflatten.py::TestUnflatten::test_placeholder_and_get_attr_ordering_after_unflattened opcode         name         target                    args                                                            kwargs
-------------  -----------  ------------------------  --------------------------------------------------------------  --------
get_attr       bias         bias                      ()                                                              {}
get_attr       weight       weight                    ()                                                              {}
placeholder    l_x_         l_x_                      ()                                                              {}
call_function  convolution  aten.convolution.default  (l_x_, weight, bias, [2, 2], [0, 0], [1, 1], False, [0, 0], 1)  {}
output         output       output                    (convolution,)                                                  {}
```

After:
```bash
test/export/test_unflatten.py::TestUnflatten::test_placeholder_and_get_attr_ordering_after_unflattened opcode         name         target                    args                                                            kwargs
-------------  -----------  ------------------------  --------------------------------------------------------------  --------
placeholder    l_x_         l_x_                      ()                                                              {}
get_attr       weight       weight                    ()                                                              {}
get_attr       bias         bias                      ()                                                              {}
call_function  convolution  aten.convolution.default  (l_x_, weight, bias, [2, 2], [0, 0], [1, 1], False, [0, 0], 1)  {}
output         output       output                    (convolution,)                                                  {}
```

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

### CODE REVIEW

**Review by thiagocrepaldi — COMMENTED** [review]
LGTM. Maybe @ezyang or @eellison could help us on this. Adding the export labels too

**Review by tugsbayasgalan — APPROVED** [review]

**Comment by thiagocrepaldi** [comment]
@titaiwangms FYI

**Comment by titaiwangms** [comment]
Hi @PaliC,

Sorry that I accidentally stacked unrelated PRs on top of https://github.com/pytorch/pytorch/pull/117500. Should I wat till https://github.com/pytorch/pytorch/pull/117500 is merged to merge this one? Thanks!

**Comment by PaliC** [comment]
@titaiwangms Please create a new PR, or wait until https://github.com/pytorch/pytorch/pull/117500 is fixed. I think at this point

**Comment by titaiwangms** [comment]
> @titaiwangms If it's actually unrelated it should be fine. However, please do not merge a pr in such a state again. As it's 1) overwriting metadata so proper author's don't get credit, 2) it wastes CI by testing unrelated changes and 3) in the case of reverts it ends up being a bit of a mess (ie. I had to revert #117500 3 times)

Sorry!

**Pull request closed without merging**
