### PR TITLE
Upstream utils in computation_client

### PR DESCRIPTION
**Pull request by desertfire**
There are two parts in this PR. One is also being upstream in https://github.com/pytorch/pytorch/pull/69621

### CODE REVIEW

**Review by alanwaketan — APPROVED** [review]
LGTM. Now it makes me wonder if we need a util sub dir.

**Review by wconstab — APPROVED** [review]
nice!
only issue is that i'm not sure if the gflags/c10-flags stuff does work with env vars.  Maybe we can still rescue it by somehow setting up env parsing for those flags, but i didn't figure out how to get it to work yet.

**Comment by desertfire** [comment]
> LGTM. Now it makes me wonder if we need a util sub dir.

Totally agree on the util sub directory idea. We can do a one-pass refactoring after all the pieces are upstreamed. The current two-step approach is quite annoying.

**Comment by desertfire** [comment]
> nice! only issue is that i'm not sure if the gflags/c10-flags stuff does work with env vars. Maybe we can still rescue it by somehow setting up env parsing for those flags, but i didn't figure out how to get it to work yet.

One way to solve this is to introduce some Python bindings for setting those flags.

**Comment by wconstab** [comment]
> 

yea, honestly most (all?) of the env vars are probably better as python bindings.  It's actually a nuisance to have to set them at the process level most of the time.  maybe with the exception of some of the dump-debug ones.  for those we could also just add std::getenvs back later.

**Pull request merged**
