### PR TITLE
Update sampler.py

### PR DESCRIPTION
**Pull request by vfdev-5**
Add argument's missing doc

### CODE REVIEW

**Comment by vfdev-5** [comment]
Inspecting available classes `SequentialSampler`, `RandomSampler`, `SubsetRandomSampler` and `WeightedRandomSampler` derived from `Sampler`. This inheritance looks rather artificial. I would suggest a small API modification :

- Sampler instead of being instanciated from data_source (Dataset), is instanciated from `num_samples` which is `len(data_source)`
```
class Sampler(object):
    def __init__(self, num_samples):
        self.num_samples = num_samples
    def __len__(self):
        raise self.num_samples
```
- Sequential sampler is then 
```
class SequentialSampler(Sampler):
    def __init__(self, data_source):
        super(SequentialSampler, self).__init__(len(data_source))

    def __iter__(self):
        return iter(range(self.num_samples))
```
- Random sampler is 
```
class RandomSampler(Sampler):
    def __init__(self, data_source):
        super(RandomSampler, self).__init__(len(data_source))

    def __iter__(self):
        return iter(torch.randperm(self.num_samples).long())
```

- Subset random sampler 
```
class SubsetRandomSampler(Sampler):
    def __init__(self, indices):
        super(SubsetRandomSampler, self).__init__(len(indices))
        self.indices = indices

    def __iter__(self):
        return (self.indices[i] for i in torch.randperm(self.num_samples))
```
and WeightedRandomSampler
```
class WeightedRandomSampler(Sampler):
    def __init__(self, weights, num_samples, replacement=True):
        super(WeightedRandomSampler, self).__init__(num_samples)
        self.weights = torch.DoubleTensor(weights)
        self.replacement = replacement

    def __iter__(self):
        return iter(torch.multinomial(self.weights, self.num_samples, self.replacement))
```

**Comment by soumith** [comment]
thanks for the PR.
What's the advantage of changing the API to what you proposed, they both look close enough.

**Comment by vfdev-5** [comment]
The advantage of this change is a better inheritance implication between derived classes and the base class `Sampler`: 
- usage of `super`
- less of code in derived classes: method `__len__` is factorized

**Comment by apaszke** [comment]
I agree that it's a bit of overkill now, but it might turn out useful at some point, and doesn't cost us anything. Some samplers might actually want to use the data_source, it's just that the core ones we have implemented don't take advantage of this.

**Comment by vfdev-5** [comment]
@apaszke I see your point. Sure that having data source might be useful at some point.
However, I think it would be rather difficult to get some stats for the sampler from `data_source` directly as it delivers x (e.g. image) and y (e.g. target).

**Pull request merged**
