### PR TITLE
Improve torch.utils.tensorboard docs

### PR DESCRIPTION
**Pull request by orionr**
This adds method details and corrects example on the page that didn't run properly. I've now confirmed that it runs in colab with nightly.

For those with internal access the rendered result can be seen at https://home.fburl.com/~orionr/pytorch-docs/tensorboard.html

cc @lanpa, @soumith, @ezyang, @brianjo

### CODE REVIEW

**Comment by fmassa** [comment]
quick question on `add_video`: it would be good to specify what is the format for the video which is expected. Should it be a uint8 tensor or can it be a float tensor? And if it's a float tensor, is the value expected to be between 0-1 or 0-255?

**Comment by orionr** [comment]
@lanpa, do you have an answer to @fmassa's question above? I can update the docs to reflect that. Thanks.

**Comment by orionr** [comment]
We should get these changes into master and 1.1 before tomorrow, so deferring @fmassa's comments for now. We can update later.

**Comment by lanpa** [comment]
https://github.com/lanpa/tensorboardX/blob/05b17d125cfd1a0dddb2ae599a2eb72b39bedcf3/tensorboardX/summary.py#L313

If `uint8` type is passed, then 0-255 is expected. If `float` type is passed, then 0-1 is expected.

**Pull request closed without merging**
