### PR TITLE
Delete torch::deploy from pytorch core

### PR DESCRIPTION
**Pull request by PaliC**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #85953

As we have migrated torch::deploy over to https://github.com/pytorch/multipy, we can now delete it from pytorch core as ongoing development will happen there.

This PR was created due to syncing issues with https://github.com/pytorch/pytorch/pull/85443 which is where the review history can be found.

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Reverting internal PR as opensource one can not be merge into trunk

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
