### PR TITLE
[tensorexpr] Add 'pre_alloc' argument in python API of tensorexpr kernel

### PR DESCRIPTION
**Pull request by huiguoo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #64718
* #64227
* #64226

Differential Revision: [D30826582](https://our.internmc.facebook.com/intern/diff/D30826582)

### CODE REVIEW

**Comment by huiguoo** [comment]
@huiguoo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30826582).

**Comment by navahgar** [comment]
Is this ready for review? It is still in draft state..

**Comment by huiguoo** [comment]
@huiguoo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30826582).

**Comment by huiguoo** [comment]
Yup, I converted it to draft yesterday for a small change. It's ready for review now :)

**Review by navahgar — APPROVED** [review]
LGTM

**Pull request closed without merging**
