### PR TITLE
enable double backward for non-cudnn LSTM and GRU

### PR DESCRIPTION
**Pull request by ngimel**
An attempt to enable double backward for non-cudnn LSTM and GRU (see #25315, #20449). RNN works already because it does not rely on fused kernels. 
This does not implement double backward function itself, because that is pretty hard to spell out. Instead, it implements backward using differentiable operations, so that double backward can be done automatically. 
The good: seems to work, no effect on performance on the usual case without double backward. because fused lstm backward is used.
The bad: Performance of backward and, especially, double backward, is pretty bad. Scripting would still be a preferred way if we want a performant solution. Performance and/or memory use can be slightly improved if in-place variants can be used for sigmoid_backward and tanh_backward to avoid cat in the end, but I'm not yet sure it's possible, and in any case it is only slight improvement.  
The ugly: I could not figure out a way to reuse workspace that contains the sum of the gates with the applied sigmoid and tanh operations, so that's probably another perf and memory hit. 
cc @soumith, @albanD. If you think this approach is viable, I can extend to GRU and RNN. 
Thanks to @mcarilli whose approach to double backward in weight norm I copied. 

Test plan: added tests to check gradgrad for GRU and LSTM with cudnn disabled.

### CODE REVIEW

**Comment by soumith** [comment]
this approach is totally viable. Please extend it to GRU and RNN and we shall pull it in.
Marking it for 1.3

**Comment by ngimel** [comment]
Added GRU and changed description accordingly, RNN works already.

**Review by albanD — APPROVED** [review]

**Comment by tengerye** [comment]
@ngimel Hi, my PyTorch version is 1.4.0, but I still encounter such problem, may I ask what might be the problem please?

**Comment by ngimel** [comment]
@tengerye please use discuss.pytorch.org for questions, and look at the test case in this PR to see how double backward for GRU is supported.

**Comment by tengerye** [comment]
@ngimel Sorry, my bad. I thought this PR is for the cudnn support.

**Pull request closed without merging**
