### PR TITLE
Disable all cu92 in scheduled-ci

### PR DESCRIPTION
**Pull request by walterddr**
since we no longer support cuda9.2 disabling scheduled ci for those

### CODE REVIEW

**Comment by janeyx99** [comment]
It looks like we can also remove 9.2 stuff in:
.circleci/cimodel/data/simple/docker_definitions.py
.circleci/docker/build.sh
.jenkins/pytorch/test.sh

**Review by janeyx99 — COMMENTED** [review]
Oh, also I think we can remove the docker build jobs for 9.2 in the normal workflow.

**Comment by walterddr** [comment]
good point. let me clean that up all together

**Comment by janeyx99** [comment]
> Oh, also I think we can remove the docker build jobs for 9.2 in the normal workflow.

Removing the references from docker_definitions should do this, I now realize.

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
