### PR TITLE
Update oneDNN submodule to v3.3.4

### PR DESCRIPTION
**Pull request by Xia-Weiwen**
As the title. For PyTorch release/2.2.
This update contains the fixes to the known issues brought by oneDNN v3.3.2 as we listed in #112700

For those issues, we have rerun validation with oneDNN v3.3.4, and results showed that regression has gone. The results are given below and compared with v3.1.1 (the oneDNN version in PyTorch before it was updated to v3.3.2).
1. A performance regression with 5.8% perf drop from `pytorch_stargan-train` (see https://github.com/pytorch/benchmark/issues/2076#issuecomment-1847545843)
Validation results with this patch: Latency increased by 0.60%
```
Tested on an Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz instance (IceLake)
oneDNN v3.1.1
metrics-1484287.json
{
    "name": "cpu",
    "environ": {
        "pytorch_git_version": "6c8c5ad5eaf47a62fafbb4a2747198cbffbf1ff0"
    },
    "metrics": {
        "latency": 418.851717
    }
}
oneDNN v3.3.4
{
    "name": "cpu",
    "environ": {
        "pytorch_git_version": "6c8c5ad5eaf47a62fafbb4a2747198cbffbf1ff0"
    },
    "metrics": {
        "latency": 421.381313
    }
}
```

2. Performance regression of FP32 rexnet_100 with Inductor, dynamic shape, multi-threads (see https://github.com/pytorch/pytorch/issues/115346#issue-2030859592)
Validation results with this patch: Latency reduced by 3.23%
```
Tested on an Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz instance (IceLake)
oneDNN v3.1.1
(inductor speedup over eager mode) 2.876x
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks
cpu,rexnet_100,128,2.875904,113.314765,18.455283,0.990437,1302.636134,1315.212902,351,1,0,0

oneDNN v3.3.4
(inductor speedup over eager mode) 3.003x
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks
cpu,rexnet_100,128,3.003012,109.653012,91.547260,0.990048,1302.532506,1315.625370,351,1,0,0
```

3. Performance regression of AMP hf_T5_generate and tinynet_a with Inductor, static shape, multi-threads (see https://github.com/pytorch/pytorch/issues/115346#issuecomment-1856029962)
Validation results with this patch: Latency reduced by 0.85%
```
Tested on an AWS spr metal instance
oneDNN v3.1.1
(inductor speedup over eager mode) 1.120x
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks
cpu,hf_T5_generate,1,1.120018,1197.807729,205.905466,0.442803,125.179904,282.698957,10550,48,8,4
 
oneDNN v3.3.4
(inductor speedup over eager mode) 1.134x
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks
cpu,hf_T5_generate,1,1.133594,1187.701514,205.855527,0.422012,128.405094,304.268493,10550,48,8,4
```

No other regression was found.

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen

### CODE REVIEW

**Comment by atalman** [comment]
Hi @Xia-Weiwen normally we accept only fixes to regressions and critical fixes for patch release. Submodule update can introduce other breakages.  Cherry-pick criteria specified here: https://github.com/pytorch/pytorch/issues/119295#issue-2121466027

Please post this PR to main instead. We should be able to introduce this to release 2.3

**Comment by Xia-Weiwen** [comment]
> Hi @Xia-Weiwen normally we accept only fixes to regressions and critical fixes for patch release. Submodule update can introduce other breakages. Cherry-pick criteria specified here: [#119295 (comment)](https://github.com/pytorch/pytorch/issues/119295#issue-2121466027)
> 
> Please post this PR to main instead. We should be able to introduce this to release 2.3

Got it. Thanks.

**Comment by Xia-Weiwen** [comment]
Hi @atalman. I thought in previous discussions, we decided to update oneDNN in PyTorch 2.2 patch release to fix the regressions caused by oneDNN v3.3.2. Just for double-check, you meant the fixes were not needed and better to have them in PyTorch 2.3. Is that correct?
If that is the case, we may close this PR because we will probably update oneDNN to a newer version for PyTorch 2.3, which is not decided yet.
Thanks!

**Review by jgong5 — APPROVED** [review]

**Comment by Xia-Weiwen** [comment]
Close as we won't upgrade oneDNN for PyTorch 2.2. Upgrade it for PT 2.3 instead.

**Pull request closed without merging**
