### PR TITLE
Reland D62220158

### PR DESCRIPTION
**Pull request by mengluy0125**
Summary: We fix the unit test test_pad_mm and reland the diff

Test Plan: See in D62220158

Differential Revision: D62891584

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by dshi7 — APPROVED** [review]

**Comment by jeanschmidt** [comment]
@mengluy0125 I believe we want to be more careful with PR names and descriptions.

**Comment by jeanschmidt** [comment]
```
FAILED [0.3743s] inductor/test_pad_mm.py::PadMMTest::test_pad_mm_bf16 - RuntimeError: Expected to find ".run(" but did not find it
```

on

`linux-focal-rocm6.1-py3.8 / test (default, 2, 6, linux.rocm.gpu.2)`

**Pull request closed without merging**
