### PR TITLE
don't allow alias dispatch keys to go in the DispatchKeySet

### PR DESCRIPTION
**Pull request by bdhirsh**
https://github.com/pytorch/pytorch/pull/61621 technically puts us at 65 dispatch keys. That should actually be fine, since the top 3 keys (Autograd, CompositeExplicitAutograd, CompositeImplicitAutograd) are alias keys - which means they should never enter the runtime dispatch keyset. So we technically have 2 runtime keys available after that PR lands.

It happens to not be fine because putting dispatch key 65 into a DispatchKeySet causes integer overflow here: https://github.com/pytorch/pytorch/blob/328606699fd0eb0ee85070907965de4beb125ff6/c10/core/DispatchKeySet.h#L56, which is caught by ASAN (see current failures in the linked PR).

We've been previously putting alias keys in the key set as part of the registration logic, mostly convenience, but I don't think that's necessary - so I moved a few things around to ensure that alias keys never enter a DispatchKeySet, even at registration time.

I tested by adding a print statement that detected the overflow mentioned in the above PR, and making tweaks in OperatorEntry.cpp until I stopped seeing the overflow detected.

We're gonna need open registration soon 😛 

Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#61771 don't allow alias dispatch keys to go in the DispatchKeySet**

Differential Revision: [D29736432](https://our.internmc.facebook.com/intern/diff/D29736432)

### CODE REVIEW

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29736432).

**Review by asuhan — APPROVED** [review]
Looks good modulo the formatting and lint suggestions (please apply them). I'm not aware of the full implications of doing this but it makes sense to me.

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29736432).

**Comment by bdhirsh** [comment]
Done.

It also might be worth adding a debug-only assert in the `DispatchKeySet()` constructors, just so the next time someone changes the registration logic and accidentally re-introduces the problem we don't have to catch it through ASAN. I didn't bother because I think I'd need a new macro (TORCH_INTERNAL_ASSERT_DEBUG_ONLY isn't constexpr, but the DispatchKeySet constructor is). But maybe I should add it next week.

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29736432).

**Pull request closed without merging**
