### PR TITLE
[distributed] add flock-based wrapper around built-in print

### PR DESCRIPTION
**Pull request by stas00**
This is a new function that helps to perform non-interleaved prints from multiple ranks. It uses `flock` to ensure exclusivity.

If you tried to print something (e.g. usually a debug print from even a few GPUs) you know that the result is often a useless mess of interleaved printed messages, which is hard to make sense of. This convenience wrapper helps to overcome this problem

This is my first time adding a new function to pytorch, so please kindly let me know what else I need to do - if there is a guide perhaps?

Thank you!

Here is the doc:

```
    This is a wrapper around the built-in Python ``print`` which calls ``flock``s before calling
    ``print`` and unlocks it immediately after. This wrapper is useful for when each rank needs to
    print a message without getting it interleaved with prints from other ranks.

    The lock file is the file this wrapper is defined in.

    The output order will be random per rank.

    Example:
        >>> # assuming 4 GPUs
        >>> world_size = dist.get_world_size()
        >>> rank = dist.get_rank()
        >>> dist.print(f"This is a very long message from rank {rank}/{world_size}")
       This is a very long message from rank 0/4
       This is a very long message from rank 2/4
       This is a very long message from rank 3/4
       This is a very long message from rank 1/4
```

Hmm, in pt-1.9.0's `torch.distributed.__init__` calls:
```
from .distributed_c10d import *
```
so this probably will be a problem as it'll result in overriding the built-in `print`. Suggestions?

(p.s. one other thing that would be great to tackle in the torch.dist world is the currently interleaved traceback exception messages which is a complete disaster when one has hundreds of GPUs, if you have ideas how to tackle this one I'm all ears.)

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

### CODE REVIEW

**Comment by stas00** [comment]
@pritamdamania, could you please have a look? Thank you!

**Comment by pritamdamania87** [comment]
@stas00 Could you show an example of what the interleaved messages looked like before? Even with this PR, the messages would still be interleaved since rank 0 would print one line then rank 1 would print one line and then rank 0 could again print another line?

**Comment by stas00** [comment]
I don't have a saved example, but let's create one

example of a problem
```
cat test
import torch;
def a(): torch.ones()
def b(): a()
def c(): b()
def d(): c()
def f(): d()
f()
```
a chunk of a resulting interleaved log entries on 64 GPUs:
```
  File "test", line 6, in d
  File "test", line 6, in d
    def a(): torch.ones()
TypeError: ones() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

    def d(): c()
  File "test", line 5, in c
    def d(): c()
      File "test", line 5, in c
def d(): c()
  File "test", line 5, in c
    def c(): b()
  File "test", line 4, in b
    def c(): b()
    def c(): b()  File "test", line 4, in b

    def b(): a()  File "test", line 4, in b

  File "test", line 3, in a
    def b(): a()    
def b(): a()      File "test", line 3, in a

def a(): torch.ones()
  File "test", line 3, in a
TypeError: ones() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

    def a(): torch.ones()    
def a(): torch.ones()
TypeErrorTypeError: ones() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
: 
ones() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

```

whereas instead each trace at a time would look like:

```
Traceback (most recent call last):
  File "test", line 9, in <module>
    f()
  File "test", line 7, in f
    def f(): d()
  File "test", line 6, in d
    def d(): c()
  File "test", line 5, in c
    def c(): b()
  File "test", line 4, in b
    def b(): a()
  File "test", line 3, in a
    def a(): torch.ones()
TypeError: ones() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

Granted, this PR doesn't fix the exception problem because we have no control over it.

what it does help with is when a developer needs to debug something printed from all ranks, and the same problem occurs as demonstrated above.

Let's look at a practical example: take this internode all-reduce bandwidth benchmark: https://gist.github.com/jeffra/9a635c1a0830f03b124c012f3e6d899c it generates a mess because the outputs are interleaved. And I have modified it to use `printflock`:
https://gist.github.com/stas00/ec5e197b15e2e7aea0153f54d2f97c15
and now the outputs are non-interleaved.


wrt the original exception problem, I think the solution is to give the user the ability to shut std streams for all but machine 0 rank 0 process. But that's a different story.

Thank you.

**Comment by stas00** [comment]
So it looks like this could be switched from `flock` to `fcntl`-based locking and then on GPFS (and potentially other shared filesystem) this could be used to sync some logs. Need to experiment.

**Pull request closed without merging**
