### PR TITLE
[ROCm] Changes not to rely on CUDA_VERSION or HIP_VERSION

### PR DESCRIPTION
**Pull request by pruthvistony**
- Replace HIP_PLATFORM_HCC with USE_ROCM
- Dont rely on CUDA_VERSION or HIP_VERSION and use USE_ROCM and ROCM_VERSION.

- In the next PR
   - Will be removing the mapping from CUDA_VERSION to HIP_VERSION and CUDA to HIP in hipify.
   - HIP_PLATFORM_HCC is deprecated, so will add HIP_PLATFORM_AMD to support HIP host code compilation on gcc.

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @amathews-amd

### CODE REVIEW

**Comment by ezyang** [comment]
Were the changes in this PR done mechanically or by hand? If mechanical, what commands were used to do the substitutions?

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
I see what is going on (you want HIP_VERSION tests to diverge from CUDA_VERSION tests) but we're going to need some sort of explainer on how to correctly write CUDA versions tests in the future, otherwise this is gonna regress as people add stuff and assume it works because CUDA worked.

**Comment by pruthvistony** [comment]
> I see what is going on (you want HIP_VERSION tests to diverge from CUDA_VERSION tests) but we're going to need some sort of explainer on how to correctly write CUDA versions tests in the future, otherwise this is gonna regress as people add stuff and assume it works because CUDA worked.

@ezyang, 
Yes. Please check this PR which was merged [62850](https://github.com/pytorch/pytorch/pull/62850) giving some explanation. Please let me know if anything more is required.

**Comment by ezyang** [comment]
Internal issue, probably I have to fix

```
buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/core/hip/common_gpu.h/caffe2/core/hip/common_gpu.h:40:9: error: 'CAFFE2_HIP_API' macro redefined [-Werror,-Wmacro-redefined]
#define CAFFE2_HIP_API TORCH_HIP_API
```

**Comment by pruthvistony** [comment]
> Internal issue, probably I have to fix
> 
> ```
> buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/core/hip/common_gpu.h/caffe2/core/hip/common_gpu.h:40:9: error: 'CAFFE2_HIP_API' macro redefined [-Werror,-Wmacro-redefined]
> #define CAFFE2_HIP_API TORCH_HIP_API
> ```

Yes, For ROCm builds, CAFFE2_HIP_API is redefined. It was same before my PR too. 
I am working on few more changes, which will remove the redefinition.

**Comment by pruthvistony** [comment]
> Internal issue, probably I have to fix
> 
> ```
> buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/core/hip/common_gpu.h/caffe2/core/hip/common_gpu.h:40:9: error: 'CAFFE2_HIP_API' macro redefined [-Werror,-Wmacro-redefined]
> #define CAFFE2_HIP_API TORCH_HIP_API
> ```

To avoid the redefinition error, the guard 
`#if !defined(USE_ROCM)`was present,
Is there  a build config when `USE_ROCM` is NOT defined and hipify triggered?

Also as per the below comments in `common_gpu.h`, I am working on few more changes to remove the below code.
```
//TODO: [ROCm] Need to remove this after CUDA->HIP mapping is updated.
#define CAFFE2_HIP_EXPORT C10_EXPORT
#define CAFFE2_HIP_API TORCH_HIP_API
```

**Comment by ezyang** [comment]
I don't see any occurrences of USE_ROCM in our internal build scripts, so there's a decent chance that USE_ROCM is just not defined intenrally

**Comment by ezyang** [comment]
I tried stuffing USE_ROCM in here:

```
hip_pp_flags = [
    "-DTORCH_HIP_VERSION=1",
    "-DUSE_ROCM=1",
    "-D__HIP_PLATFORM_HCC__=1",
    "-D__HIP_NO_HALF_OPERATORS__=1",
    "-D__HIP_NO_HALF_CONVERSIONS__=1",
    "-DCUDA_HAS_FP16=1",
    "-DCAFFE2_USE_MIOPEN",
    # clang with -fopenmp=libgomp (gcc's OpenMP runtime library) produces
    #      single threaded code and doesn't define -D_OPENMP by default.
    # clang with -fopenmp or -fopenmp=libomp (llvm's OpenMP runtime library)
    #      produces multi-threaded code and defines -D_OPENMP by default.
    #
    # hcc currently don't have llvm openmp runtime project builtin.
    # wrap_hip.py also drops -D_OPENMP if explicitly specified.
    "-U_OPENMP",
]

```

let's see if that works

**Comment by ezyang** [comment]
OK, that helped. Now I'm at

```
buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/core/hip/common_gpu.h/caffe2/core/hip/common_gpu.h:101:10: error: use of undeclared identifier 'ROCM_VERSION'; did you mean '_SC_VERSION'?
  return ROCM_VERSION;
         ^~~~~~~~~~~~
```

What should I be setting ROCM_VERSION to in the internal build?

**Comment by pruthvistony** [comment]
> OK, that helped. Now I'm at
> 
> ```
> buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/core/hip/common_gpu.h/caffe2/core/hip/common_gpu.h:101:10: error: use of undeclared identifier 'ROCM_VERSION'; did you mean '_SC_VERSION'?
>   return ROCM_VERSION;
>          ^~~~~~~~~~~~
> ```
> 
> What should I be setting ROCM_VERSION to in the internal build?

ROCM_VERSION should always be defined when building for ROCm platform.
The value is set based on the below 
`ROCM_VERSION = ROCM_VERSION_MAJOR * 10000 + ROCM_VERSION_MINOR * 100 + ROCM_VERSION_PATCH`
So for ROCm release 4.2 ==> 40200, and 4.1.1 ==> 40101.
Please set this variable in your internal builds based on the ROCm version used, I which I assume it is older.

**Comment by ezyang** [comment]
At a wild guess, the internal version is 3.1

**Comment by pruthvistony** [comment]
> At a wild guess, the internal version is 3.1

Please set ROCM_VERSION to 30100 in your builds.

**Comment by jithunnair-amd** [comment]
@pruthvistony completed performance regression checks for the changes in this PR: verified by running DLM models and by running few other models eg. LSTM.

**Pull request closed without merging**
