### PR TITLE
[MPS] LSTM fixes

### PR DESCRIPTION
**Pull request by kulinseth**
PR : #95137

- Fix LSTM backward and forward pass

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks for fixing this!

**Comment by kulinseth** [comment]
> Thanks for fixing this!

@AlexRoar , I think the backwards compat failures would need to be addressed.

**Comment by AlexRoar** [comment]
> > Thanks for fixing this!
> 
> 
> 
> @AlexRoar , I think the backwards compat failures would need to be addressed.

What does it specifically mean? Is it because forward now returns one more Tensor? If it is the case, what are the options? Backward pass cannot function correctly without data of all layers outputs, but this data not returned by forward, neither accepted by backward function in the previous implementation. 

Of course we can re-calculate forward pass in backward function, but I am sure that this isn't the right solution.

**Comment by kulinseth** [comment]
> > > Thanks for fixing this!
> > 
> > 
> > @AlexRoar , I think the backwards compat failures would need to be addressed.
> 
> What does it specifically mean? Is it because forward now returns one more Tensor? If it is the case, what are the options? Backward pass cannot function correctly without data of all layers outputs, but this data was not returned by forward, neither was accepted by backward function in the previous implementation.
> 
> Of course we can re-calculate forward pass in backward function, but I am sure that this isn't the right solution.

Right, i think there was a bug to begin with. This solution is the right approach and i think we can treat the breakage in backwards compatibility as the expected failure.

**Comment by albanD** [comment]
Yes, you can add it to https://github.com/pytorch/pytorch/blob/98c5921ed5f45b5eab24bd966bc941dbe185a362/test/forward_backward_compatibility/check_forward_backward_compatibility.py#L42

**Comment by kulinseth** [comment]
@albanD , can you take a [look](https://github.com/pytorch/pytorch/pull/95388/commits/2b47e5ebf70561003e44b38a141b80b3ab1062c0) ? I don't have linux machine, and i am not able to repro this on mac.

**Comment by AlexRoar** [comment]
Accordig to CI, other operations are also need to be listed:

```
Broken ops: [
[53548](https://github.com/pytorch/pytorch/actions/runs/4259041164/jobs/7410996038#step:11:53550)
	aten::lstm_mps_backward(Tensor grad_y, Tensor? grad_hy, Tensor? grad_cy, Tensor z_state, Tensor cell_state_fwd, Tensor input, Tensor[] hx, Tensor[] params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first) -> (Tensor, Tensor[], Tensor[])
[53549](https://github.com/pytorch/pytorch/actions/runs/4259041164/jobs/7410996038#step:11:53551)
	aten::_lstm_mps.out(Tensor input, Tensor[] hx, Tensor[] params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first, *, Tensor(a!) out0, Tensor(b!) out1, Tensor(c!) out2, Tensor(d!) out3, Tensor(e!) out4) -> (Tensor(a!), Tensor(b!), Tensor(c!), Tensor(d!), Tensor(e!))
[53550](https://github.com/pytorch/pytorch/actions/runs/4259041164/jobs/7410996038#step:11:53552)
	aten::_lstm_mps(Tensor input, Tensor[] hx, Tensor[] params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first) -> (Tensor, Tensor, Tensor, Tensor, Tensor)
[53551](https://github.com/pytorch/pytorch/actions/runs/4259041164/jobs/7410996038#step:11:53553)
]
```

**Comment by atalman** [comment]
@kulinseth @albanD 
There is still a failure on this cherry-pick:
```
The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not. 

Broken ops: [
	aten::lstm_mps_backward(Tensor grad_y, Tensor? grad_hy, Tensor? grad_cy, Tensor z_state, Tensor cell_state_fwd, Tensor input, Tensor[] hx, Tensor[] params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first) -> (Tensor, Tensor[], Tensor[])
	aten::_lstm_mps.out(Tensor input, Tensor[] hx, Tensor[] params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first, *, Tensor(a!) out0, Tensor(b!) out1, Tensor(c!) out2, Tensor(d!) out3, Tensor(e!) out4) -> (Tensor(a!), Tensor(b!), Tensor(c!), Tensor(d!), Tensor(e!))
	aten::_lstm_mps(Tensor input, Tensor[] hx, Tensor[] params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first) -> (Tensor, Tensor, Tensor, Tensor, Tensor)
]
```

**Comment by albanD** [comment]
You need to indeed add all the schemas that we changed to the allowlist. Not just one.

**Pull request merged**
