### PR TITLE
[Dynamo] Code refactor: move context managers out of misc.py

### PR DESCRIPTION
**Pull request by yanboliang**
misc.py and test_misc.py is too big, moving context managers to context.py and test_context.py.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
You may need to update test_dynamic_shapes if it referenced misc

**Review by anijain2305 — APPROVED** [review]

**Review by mlazos — APPROVED** [review]

**Review by voznesenskym — APPROVED** [review]

**Pull request closed without merging**
