### PR TITLE
Fix USE_ATEN flag in caffe2

### PR DESCRIPTION
**Pull request by orionr**
This will be improved with other changes I'm making, but putting this up so USE_ATEN works in caffe2 right now.

### CODE REVIEW

**Comment by orionr** [comment]
@ezyang and @pjh5 would you mind reviewing? Thanks.

**Comment by orionr** [comment]
Also, to test, run

```
mkdir build && cd build && cmake -DUSE_ATEN=ON .. && make -j 8`
```

**Comment by pjh5** [comment]
It looks fine to me but I'm not that familiar with this. I'll wait for Edward to review

**Review by pjh5 — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Pull request merged**
