### PR TITLE
[from RFC #122468] Implement autoload device extension mechanism 

### PR DESCRIPTION
**Pull request by bkowalskiINTEL**
This is a recast of PR #127228.

**Desc:**
These changes refer to RFC from https://github.com/pytorch/pytorch/issues/122468 issue. Early testing has been done against habana_frameworks extension, with the entry point exported according to the RFC discussion.
Things to do:

Documentation
Unit tests (we are open for suggestions)
More in-depth testing (in progress)
Looking forward for your review.

### CODE REVIEW

**Review by jgong5 — CHANGES_REQUESTED** [review]
Add UTs?

**Comment by shink** [comment]
> Add UTs?

I added an unit case at https://github.com/pytorch/pytorch/pull/127074. Please have a look and I can push the change to this PR if you want.

**Comment by bsochack** [comment]
> > Add UTs?
> 
> I added an unit case at #127074. Please have a look and I can push the change to this PR if you want.

The change in #127074 is aligned with this PR + adds tests. It looks good to me. I guess we can close this PR and continue in #127074

**Comment by bkowalskiINTEL** [comment]
The discussion has been moved to #127074. Please continue Your input there.

**Pull request closed without merging**
