### PR TITLE
Rename TensorTypeId to DispatchKey

### PR DESCRIPTION
**Pull request by pbelevich**
TensorTypeId -> DispatchKey
	c10/core/TensorTypeId.h -> c10/core/DispatchKey.h
	c10/core/TensorTypeId.cpp -> c10/core/DispatchKey.cpp
	TensorTypeId::* -> DispatchKey::*
	TensorTypeId type_id -> DispatchKey dispatch_key
		type_id -> dispatch_key
	TensorTypeId::NumTensorIds -> DispatchKey::NumDispatchKeys
	RealTensorTypeId -> RealDispatchKey
TensorTypeSet -> DispatchKeySet
	TensorTypeIds -> DispatchKeys
	c10/core/TensorTypeSet.h -> c10/core/DispatchKeySet.h
	c10/core/TensorTypeSet.cpp -> c10/core/DispatchKeySet.cpp
	type_set() -> key_set()
	type_set_ -> key_set_
	typeSet -> keySet
ExcludeTensorTypeIdGuard -> ExcludeDispatchKeyGuard
IncludeTensorTypeIdGuard -> IncludeDispatchKeyGuard
LocalTensorTypeSet -> LocalDispatchKeySet
	c10/core/impl/LocalTensorTypeSet.h -> c10/core/impl/LocalDispatchKeySet.h
	c10/core/impl/LocalTensorTypeSet.cpp -> c10/core/impl/LocalDispatchKeySet.cpp
	tls_local_tensor_type_set -> tls_local_dispatch_key_set
	tls_is_tensor_type_id_excluded -> tls_is_dispatch_key_excluded
	tls_set_tensor_type_id_excluded -> tls_set_dispatch_key_excluded
	tls_is_tensor_type_id_included -> tls_is_dispatch_key_included
	tls_set_tensor_type_id_included -> tls_set_dispatch_key_included
MultiDispatchTensorTypeSet -> MultiDispatchKeySet
	multi_dispatch_tensor_type_set -> multi_dispatch_key_set
tensorTypeIdToBackend -> dispatchKeyToBackend
backendToTensorTypeId -> backendToDispatchKey
initForTensorTypeSet -> initForDispatchKeySet
inferred_type_set -> inferred_key_set
computeTensorTypeId -> computeDispatchKey
PODLocalTensorTypeSet raw_local_tensor_type_set -> PODLocalDispatchKeySet raw_local_dispatch_key_set
get_default_tensor_type_id -> get_default_dispatch_key
inferred_type_id -> inferred_dispatch_key
actual_type_id -> actual_dispatch_key
typeSetToDispatchKey_ -> dispatchKeySetToDispatchKey_
get_type_id() -> get_dispatch_key()
legacyExtractTypeId -> legacyExtractDispatchKey
extractTypeId -> extractDispatchKey

Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#32154 Rename TensorTypeId to DispatchKey**

Differential Revision: [D19398900](https://our.internmc.facebook.com/intern/diff/D19398900)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit ab9ae633:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=ab9ae633c1e433ee93c3ab2e220ec320ddb69a7b).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4232615) pytorch_xla_linux_xenial_py3_6_clang7_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=84844269) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=84844269))
<details>
<summary>
<code>Jan 14 03:41:57 torch_xla/csrc/aten_xla_type_default.cpp:9339:103: error: no member named 'TensorTypeId' in namespace 'at'; did you mean 'TensorType'?</code>
</summary>

```
Jan 14 03:41:56 /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/jit_type.h:381:19: note: 'TensorType' declared here 
Jan 14 03:41:56 struct CAFFE2_API TensorType : public Type { 
Jan 14 03:41:56                   ^ 
Jan 14 03:41:56 torch_xla/csrc/aten_xla_type_default.cpp:9336:138: error: no member named 'TensorTypeId' in namespace 'at'; did you mean 'TensorType'? 
Jan 14 03:41:56       .impl_unboxedOnlyKernel<at::Tensor(const at::Tensor &, const at::Tensor &, bool), &AtenXlaTypeDefault::_cholesky_solve_helper>(at::TensorTypeId::XLATensorId) 
Jan 14 03:41:56                                                                                                                                      ~~~~^~~~~~~~~~~~ 
Jan 14 03:41:56                                                                                                                                          TensorType 
Jan 14 03:41:56 /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/jit_type.h:381:19: note: 'TensorType' declared here 
Jan 14 03:41:56 struct CAFFE2_API TensorType : public Type { 
Jan 14 03:41:56                   ^ 
Jan 14 03:41:57 torch_xla/csrc/aten_xla_type_default.cpp:9339:103: error: no member named 'TensorTypeId' in namespace 'at'; did you mean 'TensorType'? 
Jan 14 03:41:57       .impl_unboxedOnlyKernel<at::Tensor &(at::Tensor &, bool), &AtenXlaTypeDefault::_coalesced_>(at::TensorTypeId::XLATensorId) 
Jan 14 03:41:57                                                                                                   ~~~~^~~~~~~~~~~~ 
Jan 14 03:41:57                                                                                                       TensorType 
Jan 14 03:41:57 /opt/conda/lib/python3.6/site-packages/torch/include/ATen/core/jit_type.h:381:19: note: 'TensorType' declared here 
Jan 14 03:41:57 struct CAFFE2_API TensorType : public Type { 
Jan 14 03:41:57                   ^ 
Jan 14 03:41:57 fatal error: too many errors emitted, stopping now [-ferror-limit=] 
Jan 14 03:41:57 20 errors generated. 
/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/opt/conda/include/python3.6m -c torch_xla/csrc/view.cpp -o build/temp.linux-x86_64-3.6/torch_xla/csrc/view.o -std=c++14 -Wno-sign-compare -Wno-deprecated-declarations -Wno-return-type -Wno-macro-redefined -Wno-return-std-move -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_XLAC -D_GLIBCXX_USE_CXX11_ABI=1 
hon3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/opt/conda/include/python3.6m -c torch_xla/csrc/nll_loss.cpp -o build/temp.linux-x86_64-3.6/torch_xla/csrc/nll_loss.o -std=c++14 -Wno-sign-compare -Wno-deprecated-declarations -Wno-return-type -Wno-macro-redefined -Wno-return-std-move -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_XLAC -D_GLIBCXX_USE_CXX11_ABI=1 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by ezyang** [comment]
When putting up a codemod diff for review, it's always a good idea to say exactly what mechanical transformations you did. In this PR you did multiple transformations, so list them all down.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
CC'ing @ailzhang @dlibenzi this is a BC breaking change for XLA, the rename needs to be applied there. If you like, we might be able to stage this change, where we add a new API to the dispatcher that allows registering using `DeviceType::XLA` (which is the stable API), switch XLA to use that, and then land this patch.

**Comment by dlibenzi** [comment]
> CC'ing @ailzhang @dlibenzi this is a BC breaking change for XLA, the rename needs to be applied there. If you like, we might be able to stage this change, where we add a new API to the dispatcher that allows registering using `DeviceType::XLA` (which is the stable API), switch XLA to use that, and then land this patch.

If this is simply a one liner change here, should be trivial:

https://github.com/pytorch/xla/blob/705d130d466c8eef2892a24983c953678c5619f0/scripts/gen.py#L941

**Pull request closed without merging**
