### PR TITLE
Skip tests using uninitialized data

### PR DESCRIPTION
**Pull request by nkaretnikov**

### CODE REVIEW

**Comment by nkaretnikov** [comment]
as discussed offline, it's possible these tests might succeed, which will show up as failures on unrelated prs. this pr skips them

**Comment by nkaretnikov** [comment]
@Lezcano ptal

**Review by lezcano — APPROVED** [review]

**Comment by nkaretnikov** [comment]
@ngimel ptal

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
