### PR TITLE
add trunc_normal_ function to doc of torch.nn.init

### LINKED ISSUE #72517: trunc_normal_ not in Docs
In pytorch's official docs:https://pytorch.org/docs/stable/index.html or https://pytorch.org/docs/1.9.0/,i can not get any results when i search` trunc_normal_`.

Though i can use nn.init.trunc_normal_() in my code without reporting error,i can not find it's doc to get more information ,why?

### PR DESCRIPTION
**Pull request by baudzhou**
Fixes #72517

### CODE REVIEW

**Review by t-vi — APPROVED** [review]
LGTM. Thank you @baudzhou !

I don't think the CI failure is from the patch.

**Review by jbschlosser — APPROVED** [review]
LGTM, thanks for the update!

**Comment by jbschlosser** [comment]
@baudzhou even though the lint failure doesn't appear to be related to this PR, the bot isn't letting the merge go through. Would you mind rebasing?

**Comment by baudzhou** [comment]
> @baudzhou even though the lint failure doesn't appear to be related to this PR, the bot isn't letting the merge go through. Would you mind rebasing?

@jbschlosser sorry for late reply. I'll close this PR and create a new one.

**Pull request closed without merging**
