### PR TITLE
Add QHM and QHAdam optimizers

### PR DESCRIPTION
**Pull request by jma127**
Adds the quasi-hyperbolic momentum (QHM) and QHAdam optimization algorithms, based on [Ma and Yarats (2018)](https://arxiv.org/abs/1810.06801).

We also implement by proxy (adding convenience methods for parameterization) the following algorithms:

- PID optimizer [(Recht, 2018)](https://web.archive.org/web/20181027184056/http://www.argmin.net/2018/04/19/pid/)
- Synthesized Nesterov [(Lessard et al., 2016)](https://arxiv.org/abs/1408.3595)
- Robust Momentum [(Cyrus et al., 2018)](https://arxiv.org/abs/1710.04753)
- Triple Momentum [(Scoy et al., 2018)](http://www.optimization-online.org/DB_FILE/2017/03/5908.pdf)
- AccSGD [(Kidambi et al., 2018)](https://arxiv.org/abs/1803.05591)
- NAdam [(Dozat, 2016)](https://openreview.net/pdf?id=OM0jvwB8jIp57ZJjtNEZ)

### CODE REVIEW

**Review by apaszke — CHANGES_REQUESTED** [review]
I don't think we want to keep adding algos published 2 weeks ago to the core. It's usually a better strategy to wait a bit until there are actual papers that use them. If we really want them, we should put them in [`torchcontrib`](https://github.com/pytorch/contrib).

**Comment by jma127** [comment]
Got it @apaszke .

This does provide implementations of the algorithms above, in a strictly more efficient manner (save for NAdam, which has equal efficiency).

Suppose that we were instead to individually implement multiple of the above algorithms in PyTorch (I would surmise that algos 2-6 are candidates under the criteria you mentioned -- and there exists a [dormant PR](https://github.com/pytorch/pytorch/pull/5804) for 6). Would we write each of them in separate classes, using the respective original (less efficient and less accessible) implementations? To get a sense of the difference, compare lines 85-88 of qhm.py with lines 58-65 of [AccSGD.py](https://github.com/rahulkidambi/AccSGD/blob/master/AccSGD.py).

It seems to me that it's preferable to provide the single (well, times two) efficient and expressive method simply for this reason, irrespective of publication date or any direct usage of that method.

Happy to keep them in contrib or a separate repository, just wanted to make the above point to inform that decision.

Another option is to add the functionality for QHM to SGD, and for QHAdam to Adam. This was done with the ``amsgrad`` flag in Adam, well before the publication of that paper.

cc @soumith for input as well.

**Comment by apaszke** [comment]
I think the current implementation looks nice. If there are at least a few papers using *any* of the methods you implemented here then fine. Otherwise, I think we should wait.

**Comment by akaniklaus** [comment]
@jma127 Congratulations! Have you been able to compare QHM or QHAdam optimizers with Padam?

**Comment by soumith** [comment]
cc: @vincentqb can you review this and get it to completion if it makes sense. Use the guidelines that I shared with you separately.

Now that sufficient time has passed since the publication of the papers, we can re-evaluate whether the methods have been sufficiently cited and standardized in the field to warrant their acceptance into core.

**Comment by iramazanli** [comment]
Thank you @jma127  for opening this PR 🙂! Even though QHM and QHAdam are very interesting and well established algorithm, we currently do not have enough evidence of, if it aligns with the rule we consider  to add algorithms to PyTorch Core :    https://github.com/pytorch/pytorch/wiki/Developer-FAQ#i-have-implemented-an-algorithm--feature-from-a-research-paper-that-is-related-to-optimization-when-is-the-correct-time-to-add-it-to-pytorch-core- . Our reservation is that we want to include methods that the community uses as a standard, or else the code maintenance problem balloons up for us. We do show discretion based on what the paper and the community show as evidence of long-term success. I will therefore close this PR, but, if you have a differing opinion, please feel free let us know why, and we can re-evaluate.

**Pull request closed without merging**
