### PR TITLE
Remove expected failure in `test_eager_transforms.py`

### PR DESCRIPTION
**Pull request by eqy**
Seems to be supported now

CC @tinglvv @nWEIdia @Aidyn-A 

cc @zou3519 @Chillee @samdow @kshitij12345 @janeyx99

### CODE REVIEW

**Review by Chillee — APPROVED** [review]

**Review by Aidyn-A — APPROVED** [review]

**Comment by tinglvv** [comment]
Thanks for preparing this. I was previously checking if Triton is available then skip if not available. If it is supported by default now then we could remove the failure.

**Comment by nWEIdia** [comment]
> Thanks for preparing this. I was previously checking if Triton is available then skip if not available. If it is supported by default now then we could remove the failure.

Yes Ting, this test is shown as "unexpected success", indicating there is need for this PR. FYI.

**Comment by tinglvv** [comment]
@nWEIdia Thanks for the context, FYI I applied an internal fix to check if Triton is available to skip the test (as opposed to expected failure in the previous https://github.com/pytorch/pytorch/pull/112092).

**Pull request closed without merging**
