### PR TITLE
[CI] show doc coverage repro instructions

### PR DESCRIPTION
**Pull request by weifengpy**
remind devs they can reproduce the doc coverage error locally with following msg
```You can reproduce locally by running 'cd pytorch/docs && make coverage && cat build/coverage/python.txt'```

I spent 20min to figure out how to test locally so want to enrich the error msg 
Screenshot 2024-04-09 at 5 22 45 PM

### CODE REVIEW

**Review by clee2000 — APPROVED** [review]
I assume most people will already be in the pytorch folder so I dunno if it makes more sense to be cd docs or cd pytorch/docs, but seeing as you're the person who actually had to repro, I'll leave it up to you to decide

**Comment by weifengpy** [comment]
> I assume most people will already be in the pytorch folder so I dunno if it makes more sense to be cd docs or cd pytorch/docs, but seeing as you're the person who actually had to repro, I'll leave it up to you to decide

thanks for review. changed to `cd docs` to be accurate

**Pull request closed without merging**
