### PR TITLE
[nvfuser_upstream_push] nvfuser code base bump 052422

### PR DESCRIPTION
**Pull request by jjsjann123**
Syncing nvfuser devel branch to upstream master. https://github.com/csarofeen/pytorch/

A few bigger updates:
1. Initial support of cp.async and cp.async.wait: https://github.com/csarofeen/pytorch/pull/1619
2. Emulate ampere's mma 16816 with Turing's mma 1688, for a unified interface: https://github.com/csarofeen/pytorch/pull/1643
3. Extending the infrastructure to support mma operators on turing and ampere arch: https://github.com/csarofeen/pytorch/pull/1440
 
Commits that's actually in this PR from the csarofeen branch
```
* dd2325294e236c5082c642819a1103bcfe4561a3 (csarofeen/devel) Fusion Segmenter: Unify single kernel and multi-kernel runtime path (#1710)
* b3d1c3f446355a2d276bac8272e7aa8b5bb6b1f0 Fix missing cooperative launch (#1726)
* dc670a226cbe52be46cecef47001f38bf9a09433 Async gmem copy support on sm80+ (#1619)
* 5e6a8dab5a71aefe0548bbfa15d1a93c556d23fe Add turing mma support and test (#1643)
* d6d6b7d3f10dd91dafa4cdbd5e460bbb38173af4 Fix rFactor when there are indirect root domain(s), and refactor (#1723)
* 7093e39150c6d80e0f9f767d56654714a2e8a927 Mma op integration on ampere (#1440)
* fade8da55e60a118c5595378896d34b862b2fcc3 patch python test for bfloat16 (#1724)
* 8fbd0b18743a72ac10478857c3d2351204375685 Fine-grained kernel profiling (#1720)
* 77c1b4fa633f9e631d267923f4537336fa328939 Adding dry run mode to skip arch dependent checks (#1702)
* 151d95b97bebefc94199bb4a53423ede32b55451 More precise concretization analysis (#1719)
* f4d3630ed54d7069dd377a64be1f91013b285b66 Enable complex python tests (#1667)
* 4ceeee509774cc2ce6c834a4dc1e313f71d94503 Minor bugfix in transform_rfactor.cpp (#1715)
* 3675c70faf218e86d2c78dbd3874b175a3b0a203 Separate root domain and rfactor domain in TransformPrinter (#1716)
* f68b830d5def65dadfe29d4edf52fc703369c84a Fix scheduling with polymorphic broadcast (#1714)
* 4ab5ef7ae2cfd8fffad1e1d882ae7c50631211dc updating_ci_machine (#1718)
* 56585c58b1ff338704cafb0cd6be2b3d536bed5a Merge pull request #1711 from csarofeen/upstream_master_bump_0517
* 174d453d3be0c11a5acb0fff3b3f36e19cfdaf81 Allow using nvFuser on CUDA extension (#1701)
* 18bee67495454b9a79625799776e746bd5e81c4c Validate LOOP concrete IDs have complete IterDomains (#1676)
```

### CODE REVIEW

**Comment by jjsjann123** [comment]
hmmm... didn't see those warning coming from clang. I'll patch it....

**Comment by jjsjann123** [comment]
@davidberard98 @malfet Does the commit message in this PR looks reasonable?

This is the update bump of our code updates from last week (8 days). We have merged 2 relatively bigger PRs, which bumps the code change to ~[+5k][-1k]. Please ignore the long history listed in the PR. I've included all actual commits that are being merged in the comment.

cc'ing @csarofeen

**Review by csarofeen — APPROVED** [review]
Don't see any extraneous changes, looks good to me.

**Comment by davidberard98** [comment]
@jjsjann123 I see some some opinfo failures, can you take a look?

**Comment by jjsjann123** [comment]
> @jjsjann123 I see some some opinfo failures, can you take a look?

Yeah, those are from complex :cry: Opened an issue internally to track it while disabling them in python test for now.
^^^ It's safe to do that because fusion of complex currently is default off.

I'm verifying the fix in my local build right now (things running slow)

**Comment by eellison** [comment]
@davidberard98 could we get the results from microbenchmarks posted ? they should be accessible now right

**Comment by jjsjann123** [comment]
> @davidberard98 could we get the results from microbenchmarks posted ? they should be accessible now right

Is it also easy to compare perf before and after this PR? Should I hold on merging and wait until we sanity check benchmark numbers?

**Comment by davidberard98** [comment]
@jjsjann123 turns out we don't have that feature yet, but eventually there will be something you can comment on PRs to run the microbenchmarks.

Whether or not we should check microbenchmark perf results - I think that's up to you, depending on whether or not you expect perf to be affected by this

**Comment by jjsjann123** [comment]
> @jjsjann123 turns out we don't have that feature yet, but eventually there will be something you can comment on PRs to run the microbenchmarks.
> 
> Whether or not we should check microbenchmark perf results - I think that's up to you, depending on whether or not you expect perf to be affected by this

No worries then. We do have nightlies running benchmark numbers as well and I do not think our decision of merging PR would be largely affected by sanity checking on benchmarking number neither.
But if there is regression on perf, we'd like to be aware of it. So looking forward to it when the feature goes live.

Wondering if there's any objection on me merging this PR when CI goes all green?

**Comment by davidberard98** [comment]
We need to merge this with the old workflow (internal merge)

Also cc @malfet to verify the PR is okay

**Review by malfet — APPROVED** [review]

**Comment by jjsjann123** [comment]
looks like we got the approval stamp~~ Do I need to bump master on the PR before merging? @davidberard98

**Comment by davidberard98** [comment]
@jjsjann123 I think the PR is fine as it is, but let me merge it internally instead of using the bot.

**Comment by jjsjann123** [comment]
Wondering if there's any update :confused:

**Comment by davidberard98** [comment]
@jjsjann123 thanks for the reminder - I started the internal land on tuesday but it looks like it timed out, retrying it now

**Comment by davidberard98** [comment]
@jjsjann123 hey, sorry this is taking so long - but the land failed again and now build_variables.bzl has been moved, can you bump master to fix that merge issue?

**Comment by davidberard98** [comment]
@jjsjann123 sorry for the delays.. unfortunately I'm still trying to run the land internally, there's a few jobs that have been blocking me from landing

**Comment by jjsjann123** [comment]
Not sure if it's the same error: https://github.com/pytorch/pytorch/pull/77471#issuecomment-1130388983

**Comment by malfet** [comment]
This is weird, I can not reproduce the failure locally...

**Comment by malfet** [comment]
Merge failed due to list index out of range

**Comment by malfet** [comment]
> Not sure if it's the same error: [#77471 (comment)](https://github.com/pytorch/pytorch/pull/77471#issuecomment-1130388983)

Yes, it is the same error, looks like GitHub API can not return us more than first 250 commits. @jjsjann123 is it possible to create those PRs with fewer commits? I will file the support tickets against GH, an will manually merge, but this is not maintainable long term

**Comment by jjsjann123** [comment]
> > Not sure if it's the same error: [#77471 (comment)](https://github.com/pytorch/pytorch/pull/77471#issuecomment-1130388983)
> 
> Yes, it is the same error, looks like GitHub API can not return us more than first 250 commits. @jjsjann123 is it possible to create those PRs with fewer commits? I will file the support tickets against GH, an will manually merge, but this is not maintainable long term

errr... I personally hated divergent history but I lost the battle a while ago on that topic with our internal devs :stuck_out_tongue_closed_eyes: 

I can squash everything to a single commit for future PRs. I think that should be fine since we are logging all commits in the description as well.

**Pull request closed without merging**
