### PR TITLE
Bump up pytorch-triton build string to 2.1.0

### PR DESCRIPTION
**Pull request by weiwangmeta**
Fixes wild behaviour while installing nightly wheels: collecting torch 3 times! 

Collecting torch                    
  Using cached https://download.pytorch.org/whl/nightly/cu117/torch-2.1.0.dev20230303%2Bcu117-cp310-cp310-linux_x86_64.whl (1848.6 MB)           
Requirement already satisfied: torchvision in /fsx/users/weiwangmeta/conda/envs/test_nightly_wheel/lib/python3.10/site-packages (0.15.0.dev20230303+cu117)                                
Requirement already satisfied: TorchAudio in /fsx/users/weiwangmeta/conda/envs/test_nightly_wheel/lib/python3.10/site-packages (2.0.0.dev20230303+cu117)
Requirement already satisfied: filelock in /fsx/users/weiwangmeta/conda/envs/test_nightly_wheel/lib/python3.10/site-packages (from torch) (3.9.0)                                         
Requirement already satisfied: sympy in /fsx/users/weiwangmeta/conda/envs/test_nightly_wheel/lib/python3.10/site-packages (from torch) (1.11.1)                                           
Collecting pytorch-triton==2.0.0+b8b470bc59   
  Using cached https://download.pytorch.org/whl/nightly/pytorch_triton-2.0.0%2Bb8b470bc59-cp310-cp310-linux_x86_64.whl (66.5 MB)                                                          
Collecting torch                              
  Using cached https://download.pytorch.org/whl/nightly/cu117/torch-2.1.0.dev20230302%2Bcu117-cp310-cp310-linux_x86_64.whl (1850.4 MB)                                                    
  Using cached https://download.pytorch.org/whl/nightly/cu117/torch-2.0.0.dev20230301%2Bcu117-cp310-cp310-linux_x86_64.whl (1848.6 MB)

### CODE REVIEW

**Review by atalman — APPROVED** [review]
LGTM, will have to test this somehow.
Is pytorch-triton package published ?

**Comment by weiwangmeta** [comment]
> LGTM, will have to test this somehow. Is pytorch-triton package published ?

https://download.pytorch.org/whl/test/pytorch-triton/index.html 
and 
https://download.pytorch.org/whl/nightly/pytorch-triton/index.html 

Both have the commit pin: 

[pytorch_triton-2.0.0+b8b470bc59-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/pytorch_triton-2.0.0%2Bb8b470bc59-cp310-cp310-linux_x86_64.whl)
[pytorch_triton-2.0.0+b8b470bc59-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/pytorch_triton-2.0.0%2Bb8b470bc59-cp311-cp311-linux_x86_64.whl)
[pytorch_triton-2.0.0+b8b470bc59-cp38-cp38-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/pytorch_triton-2.0.0%2Bb8b470bc59-cp38-cp38-linux_x86_64.whl)
[pytorch_triton-2.0.0+b8b470bc59-cp39-cp39-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/pytorch_triton-2.0.0%2Bb8b470bc59-cp39-cp39-linux_x86_64.whl)

**Review by malfet — CHANGES_REQUESTED** [review]
Sorry, why is this necessary?

**Comment by weiwangmeta** [comment]
Closing this. As per offline discussion this is actually due to Jinja2 dependency, not triton version.

**Pull request closed without merging**
