### PR TITLE
[dynamo][higher order op] Relaxing too restrictive check for output to be a list/tuple of tensors

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104221

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78

### CODE REVIEW

**Review by voznesenskym — COMMENTED** [review]
How does this add support? Did we actually fix something?

**Comment by anijain2305** [comment]
> How does this add support? Did we actually fix something?

We did not have to fix anything. Its already supported. IIUC, the check was just too restrictive.

**Comment by voznesenskym** [comment]
> > How does this add support? Did we actually fix something?
> 
> We did not have to fix anything. Its already supported. IIUC, the check was just too restrictive.

Hmm, i thought it was broken when I added it. Maybe I made a mistake.

**Comment by voznesenskym** [comment]
> > > How does this add support? Did we actually fix something?
> > 
> > 
> > We did not have to fix anything. Its already supported. IIUC, the check was just too restrictive.
> 
> Hmm, i thought it was broken when I added it. Maybe I made a mistake.

Do you mind changing the title to reflect that?

**Comment by anijain2305** [comment]
> Do you mind changing the title to reflect that?

Done

**Review by ydwu4 — APPROVED** [review]
Looks great to me!

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
