### PR TITLE
.github: Add render test results step

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #64938
* __->__ #64937

Adds CLI output for rendered test results to go alongside test exeuction, users should be able to quickly diagnose test failures like so:
fdsfdsfdsfdsf

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

cc @ezyang @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra

Differential Revision: [D30917897](https://our.internmc.facebook.com/intern/diff/D30917897)

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]

**Comment by malfet** [comment]
I doesn't seem to detect any tests, does it?

**Comment by seemethere** [comment]
> I doesn't seem to detect any tests, does it?

Yeah I think I'm going to just remove the conditional and let the render_junit script just try and handle the test report discovery on its own

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30917897).

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30917897).

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30917897).

**Pull request closed without merging**
