### PR TITLE
[DCP] Fix duplicated logging messages when enable both c10d and dcp l…

### LINKED ISSUE #129951: Duplicated log messages after I manually replace the log handlers
### 🐛 Describe the bug

I noticed #121352 has added additional logging for improved observability in DCP. But there are duplicate log messages after I manually replace the `logging.NullHandler` in both https://github.com/pytorch/pytorch/blob/5c9d5272e43573269427cae5e38307faac3266f6/torch/distributed/logging_handlers.py#L16 and https://github.com/pytorch/pytorch/blob/5c9d5272e43573269427cae5e38307faac3266f6/torch/distributed/checkpoint/logging_handlers.py#L13 with `logging.StreamHandler()`.
```python
root@cambricon-PowerEdge-C4140:/workspace# python
Python 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torch.distributed.checkpoint as dcp
>>> dcp.save({'a': 123}, checkpoint_id='/tmp/test')
2024-07-02 09:24:54,138 logger.py:62 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'save', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'start', 'time': 1719912294138545328}
2024-07-02 09:24:54,138 logger.py:62 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'save', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'start', 'time': 1719912294138545328}
/opt/conda/lib/python3.11/site-packages/torch/distributed/checkpoint/state_dict_saver.py:143: UserWarning: torch.distributed is unavailable or uninitialized, assuming the intent is to save in a single process.
  warnings.warn(
2024-07-02 09:24:54,154 logger.py:62 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'local_step', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'start', 'time': 1719912294154763143}
2024-07-02 09:24:54,154 logger.py:62 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'local_step', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'start', 'time': 1719912294154763143}
/opt/conda/lib/python3.11/site-packages/torch/distributed/checkpoint/filesystem.py:490: UserWarning: Detected an existing checkpoint in /tmp/test/.metadata, overwriting since self.overwrite=True. Past version 2.5 of PyTorch, `overwrite` will default to False. Set this variable to True to maintain this functionality or False to raise when an existing checkpoint is found.
  warnings.warn(
2024-07-02 09:24:54,155 logger.py:80 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'local_step', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'end', 'time': 1719912294155306804, 'times_spent': 543397}
2024-07-02 09:24:54,155 logger.py:80 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'local_step', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'end', 'time': 1719912294155306804, 'times_spent': 543397}
2024-07-02 09:24:54,155 logger.py:62 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'global_step', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'start', 'time': 1719912294155493038}
2024-07-02 09:24:54,155 logger.py:62 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'global_step', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'start', 'time': 1719912294155493038}
2024-07-02 09:24:54,155 logger.py:80 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'global_step', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'end', 'time': 1719912294155642169, 'times_spent': 148935}
2024-07-02 09:24:54,155 logger.py:80 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'global_step', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'end', 'time': 1719912294155642169, 'times_spent': 148935}
2024-07-02 09:24:54,155 logger.py:62 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'write_data', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'start', 'time': 1719912294155730798}
2024-07-02 09:24:54,155 logger.py:62 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'write_data', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'start', 'time': 1719912294155730798}
2024-07-02 09:24:57,388 logger.py:80 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'write_data', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'end', 'time': 1719912297388358891, 'times_spent': 3232627787}
2024-07-02 09:24:57,388 logger.py:80 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'write_data', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'end', 'time': 1719912297388358891, 'times_spent': 3232627787}
2024-07-02 09:24:57,389 logger.py:62 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'finish_checkpoint', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'start', 'time': 1719912297389005211}
2024-07-02 09:24:57,389 logger.py:62 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'finish_checkpoint', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'start', 'time': 1719912297389005211}
2024-07-02 09:24:57,389 logger.py:80 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'finish_checkpoint', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'end', 'time': 1719912297389685299, 'times_spent': 679806}
2024-07-02 09:24:57,389 logger.py:80 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'finish_checkpoint', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'end', 'time': 1719912297389685299, 'times_spent': 679806}
2024-07-02 09:24:57,389 logger.py:80 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'save', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'end', 'time': 1719912297389828824, 'times_spent': 3251283319}
2024-07-02 09:24:57,389 logger.py:80 DEBUG p:MainProcess t:MainThread: {'checkpoint_id': '/tmp/test', 'func_name': 'save', 'args': "(), {'checkpoint_id': '/tmp/test'}", 'event': 'end', 'time': 1719912297389828824, 'times_spent': 3251283319}
Metadata(state_dict_metadata={'a': BytesStorageMetadata()}, planner_data={'a': ('a',)}, storage_data={MetadataIndex(fqn='a', offset=None, index=None): _StorageInfo(relative_path='__0_0.distcp', offset=0, length=864)}, storage_meta=StorageMeta(checkpoint_id=PosixPath('/tmp/test'), save_id='543b868c-b2e5-44e0-8163-11389d34e464', load_id=None))
```
The root cause is that when DCP and c10d use the same type of logging handler, they will share a logger instance and the handler will be added twice at  https://github.com/pytorch/pytorch/blob/5c9d5272e43573269427cae5e38307faac3266f6/torch/distributed/c10d_logger.py#L35
Not very sure is it expected behavior? Or DCP should not share the same logger instance with c10d and does the DCP logger need to be refactored like #99748 ？ 

### Versions

Collecting environment information...
PyTorch version: 2.5.0.dev20240617
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.4.131
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 535.104.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          64
On-line CPU(s) list:             0-63
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
Stepping:                        4
CPU max MHz:                     3700.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4200.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       1 MiB (32 instances)
L1i cache:                       1 MiB (32 instances)
L2 cache:                        32 MiB (32 instances)
L3 cache:                        44 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
NUMA node1 CPU(s):               1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.11.0
[pip3] torch==2.5.0.dev20240617
[pip3] torchaudio==2.4.0.dev20240617
[pip3] torchelastic==0.2.2
[pip3] torchvision==0.19.0.dev20240617
[pip3] triton==3.0.0
[conda] blas                      1.0                         mkl  
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch-nightly
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.8           py311h5eee18b_0  
[conda] mkl_random                1.2.4           py311hdb19cb5_0  
[conda] numpy                     1.26.4          py311h08b1b3b_0  
[conda] numpy-base                1.26.4          py311hf175353_0  
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] pillow                    9.3.0           py311h3fd9d12_2    pytorch-nightly
[conda] pytorch                   2.5.0.dev20240617 py3.11_cuda12.4_cudnn9.1.0_0    pytorch-nightly
[conda] pytorch-cuda              12.4                 hc786d27_6    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                2.4.0.dev20240617     py311_cu124    pytorch-nightly
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchtriton               3.0.0+45fff310c8           py311    pytorch-nightly
[conda] torchvision               0.19.0.dev20240617     py311_cu124    pytorch-nightly

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @chauhang @d4l3k @LucasLLC

### PR DESCRIPTION
**Pull request by cdzhan**
…ogger

Fixes #129951 . Would you take a moment to review it? @LucasLLC 

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @LucasLLC @MeetVadakkanchery @mhorowitz @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @chauhang

### CODE REVIEW

**Comment by janeyx99** [comment]
@LucasLLC who would be a good reviewer for this change now?

**Review by Skylion007 — APPROVED** [review]

**Comment by cdzhan** [comment]
Looks like unrelated error. Can you help merge this PR? @Skylion007

**Comment by LucasLLC** [comment]
Sorry for the late review this totally dropped through the cracks, thanks for the fix!

**Comment by cdzhan** [comment]
No worries at all! Thanks for taking the time to review it. I'm glad I could help with the fix.

**Pull request closed without merging**
