### PR TITLE
dbr quant: better fix for bug with recursion on dequantize

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70200 dbr quant: start recording ops which are not quantizeable
* #70196 dbr quant: start reusing static quant module mappings
* **#70128 dbr quant: better fix for bug with recursion on dequantize**
* #70115 dbr quant: stop overridding tensor getters
* #70114 dbr quant: clean up logging format
* #70109 dbr quant: add test for qconfig_dict and methods

Summary:

Previous code disabled torch_function when dequantizing arguments
to an unquantizeable function.  This PR blocklists the dequantize
method from the dequantize hook instead, so we can remove
the previous hack.

Test plan:

```
python test/test_quantization.py TestQuantizeDBR
```

Differential Revision: [D33194396](https://our.internmc.facebook.com/intern/diff/D33194396)

### CODE REVIEW

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33194396).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33194396).

**Review by jerryzh168 — APPROVED** [review]
I don't exactly understand the mechanisms, but as long as the test passes it should be OK

**Comment by vkuzo** [comment]
> I don't exactly understand the mechanisms, but as long as the test passes it should be OK

the issue was this:
1. define a hook which dequantizes the arguments to a non-quantizeable function, and run it for every function
2. dequantize itself is a non-quantizeable function
3. when that hook on some non-quantizeable function is called, it calls dequantize.  That leads to an infinite loop of (1) and (2), since the hook is then called for dequantize.

this is broken by disabling the hook for dequantize.

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33194396).

**Pull request closed without merging**
