### PR TITLE
Add cooperative_groups header to cuda_to_hip_mappings.py

### PR DESCRIPTION
**Pull request by rraminen**
This PR is to add hip/hip_cooperative_groups.h to avoid the hipify errors. 

cc: @jithunnair-amd 

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@malfet Straightforward one , CI is green

**Review by malfet — APPROVED** [review]
Looks good to me.
@jithunnair-amd please note, that for hipification only changes your or Jeffs's review should be sufficient

**Pull request closed without merging**
