### PR TITLE
[JIT] Add Type::repr_str to return human-readable str

### LINKED ISSUE #39449: [JIT] Inferred Tensor string representation should include the fact that it is inferred
In #38527, a boolean member `is_inferred_` was removed from `Argument` and added to `TensorType` and a separate singleton with this property set to `true` was created for use in all cases when a `TensorType` is inferred. However, the string representation of a `TensorType` with `is_inferred` still `"Tensor"`, which can lead to confusing error messages. An example is given below.

*Code*
```
def foo(x: torch.Tensor, y):  # Missing "y: int"
    for _ in range(y):
        x = x + 1
    return x
        
x = torch.ones(())

foo_script = torch.jit.script(foo)
print(foo_script(x, 2))
```
*Error*
```
RuntimeError: 
all inputs of range must be ints, found Tensor in argument 0:
  File "<ipython-input-13-8c4279680b35>", line 2
def foo(x: torch.Tensor, y):  # Missing "y: int"
    for _ in range(y):
             ~~~~~~~ <--- HERE
        x = x + 1
    return x
```

This error message should include the fact that the type of `y` was inferred.

### PR DESCRIPTION
**Pull request by gmagogsfm**
Clearly expressing a type is inferred by PyTorch instead of explicitly annotated by user makes many error messages more user-friendly

Currently Type has two string conversion methods. str() for IR printing and python_str() for serialization and error message generation. If we want to include more information in type printing while maintaining serialization/deserialization correctness, we need to split python_str() into annotation_str() and repr_str(). 

annotation_str is solely responsible for serialization, it strictly matches format of python type annotation. repr_str() is responsible for generating a human-readable error message that includes information like "this type is inferred, not explicitly annotated"

Closes #39449

### CODE REVIEW

**Comment by SplitInfinity** [comment]
I did not expect such a drastic change would be needed when I opened the issue because I was not thinking about serialization at all. Sorry about that!

Overall, I think this change makes sense. I would prefer to do it with less lines of code, but I don't think it's possible for the reasons you mentioned. But since there are a lot more changes than I thought, I'd like to get some second opinions.

@jamesr66a @eellison @robieta What do you think?

**Comment by SplitInfinity** [comment]
Also, can you add a unit test for this? Just something simple that tests that the error messages that are printed out say `Inferred Tensor` now instead of just `Tensor`.

**Comment by robieta** [comment]
At a high level, I think that this is a good change. As you pointed out, the `python_str` is currently pulling double duty as both `__repr__` and `__annotations__`. I have a strong suspicion that the textual representation will grow much richer as things like type promotion and shape inference also start to bubble up to error messages, so a bit of pain now to be able to easily support that later seems acceptable. Two thoughts:

1) The current names don't really make clear what're going on. Something like `repr_str()` and `annotations_str()` would be easier to read.
2) This doesn't necessarily have to happen in this PR, but in the spirit that "richer info about how things were inferred" will be desired down the line it probably makes sense to have a method that returns a struct that can be turned into a str rather than the str itself. That way you could call (I'm imagining names for demonstration since I'm new to the codebase.) 
```
->jit_metadata.repr_str()
```
but also something like:

```
if (type()->jit_metadata.raw_annotation == JIT_TYPES::Unannotated) {
  // Attempt to give some info about how things went wrong
}
```

**Comment by gmagogsfm** [comment]
> Also, can you add a unit test for this? Just something simple that tests that the error messages that are printed out say `Inferred Tensor` now instead of just `Tensor`.

Thanks. Noticed that there already is a test case overing the messaging of mismatched inferred tensor types, so I enhanced that test to cover it.

**Comment by gmagogsfm** [comment]
> At a high level, I think that this is a good change. As you pointed out, the `python_str` is currently pulling double duty as both `__repr__` and `__annotations__`. I have a strong suspicion that the textual representation will grow much richer as things like type promotion and shape inference also start to bubble up to error messages, so a bit of pain now to be able to easily support that later seems acceptable. Two thoughts:
> 
> 1. The current names don't really make clear what're going on. Something like `repr_str()` and `annotations_str()` would be easier to read.
> 2. This doesn't necessarily have to happen in this PR, but in the spirit that "richer info about how things were inferred" will be desired down the line it probably makes sense to have a method that returns a struct that can be turned into a str rather than the str itself. That way you could call (I'm imagining names for demonstration since I'm new to the codebase.)
> 
> ```
> ->jit_metadata.repr_str()
> ```
> 
> but also something like:
> 
> ```
> if (type()->jit_metadata.raw_annotation == JIT_TYPES::Unannotated) {
>   // Attempt to give some info about how things went wrong
> }
> ```

Good point, I was hesitant about the name as well. Now renamed readable_str to repr_str, and python_str to annotation_str.

Agree that 2nd point is better fit for another PR if needed. I am not familiar enough with the code base enough to judge whether adding another layer of indirection is beneficial. The trade off is subtle.

**Comment by gmagogsfm** [comment]
Friendly ping for review.

**Review by SplitInfinity — APPROVED** [review]

**Pull request closed without merging**
