### PR TITLE
Remove faulty process group agent logic

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#62409 Remove faulty process group agent logic**

This a reland of #61907 because removing faulty_process_group_agent.h / cpp broke facebook specific tests. I will remove the files and update the internal test code in a separate PR.

Differential Revision: [D29990001](https://our.internmc.facebook.com/intern/diff/D29990001)

### CODE REVIEW

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29990001).

**Review by mrshenli — APPROVED** [review]
LGTM. Test failures look irrelevant.

**Review by mrshenli — CHANGES_REQUESTED** [review]
I assume we should remove `test_faulty_agent.py` as well?

https://github.com/pytorch/pytorch/blob/a098160836f88ebfa40815be6a8fb5bcbdcf56f4/test/distributed/rpc/test_faulty_agent.py

**Comment by H-Huang** [comment]
@mrshenli The `test_faulty_agent.py` tests use the `FaultyRpcAgentTestFixture` which is now using `FAULTY_TENSORPIPE` backend as opposed to `FAULTY_PROCESS_GROUP` so we should keep the tests!

**Pull request closed without merging**
