### PR TITLE
OpInfo: Convert more sample_input_funcs to generators

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #69257
* #69256

These are sample functions that already use generators internally, this just moves the `yield` into the sample function itself.
Diff is best viewed ignoring whitespace changes https://github.com/pytorch/pytorch/pull/69257/files?diff=unified&w=1

Differential Revision: [D32942007](https://our.internmc.facebook.com/intern/diff/D32942007)

### CODE REVIEW

**Comment by mruberry** [comment]
@pytorchbot ciflow rerun -l ciflow/all

cc @Lezcano 

This looks a million times better! Thanks @peterbell10!

**Review by mruberry — APPROVED** [review]

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32942007).

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32942007).

**Comment by mruberry** [comment]
Ug -- even though GitHub is happy to merge this the internal FB tools aren't -- @peterbell10 would just rebase this stack and ping me and I'll try to land it ASAP?

**Comment by mruberry** [comment]
@mruberry has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32942007).

**Comment by suo** [comment]
unfortunately, this broke master (example failures: https://hud.pytorch.org/commit/pytorch/pytorch/d21646c4327b969a1d90cb8e8a6d59d37e94f25d). I am reverting

**Pull request closed without merging**
