### PR TITLE
Fix #6398, Add MKL threading support for Windows

### LINKED ISSUE #6398: torch.get_num_threads returns 1 on Windows
PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- PyTorch or Caffe2: PyTorch
- OS: Windows 10
- PyTorch version: master (67bbf585cda43fc63a8450421aaef24e2f7b3501)
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6
- CUDA/cuDNN version:
- GPU models and configuration: Intel 7700HQ with 8 threads
- GCC version (if compiling from source):
- CMake version:
- Build command you used (if compiling from source):
- Versions of any other relevant libraries:

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

It cannot auto detect the cores on the machine. And it ignores the environmental variables like `OMP_NUM_THREADS` and `MKL_NUM_THREADS`. But the MKL side seems to working. I guess there is sth wrong with OpenMP there.
```pycon
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 16:13:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.get_num_threads()
1
>>> import mkl
>>> mkl.get_max_threads()
4
```

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by peterjc123** [comment]
@yf225 According to my test, the rebuilding of the official MAGMA solves this issue. Please rebuild the MAGMA binaries and I'll try to retest this PR.

**Comment by yf225** [comment]
@peterjc123 I've rebuilt the MAGMA binaries with the MKL 2018.2.185 version. Could you try it out again?

**Comment by peterjc123** [comment]
The test failure on onnx seems unrelated.

**Comment by peterjc123** [comment]
Can we merge this please?

**Review by ezyang — APPROVED** [review]

**Pull request merged**
