### PR TITLE
Fixed Clang Compilation Warnings for THD by removing outdated C THD_API

### PR DESCRIPTION
**Pull request by teng-li**
Removed TensorDescriptor.h and DataChannelRequest.h since we don't need to use c linkage.

This will eliminate clang warnings like 
```
error: 'THDTensorDescriptor_newFromTHDoubleTensor' has C-linkage specified, but returns user-defined type 'THDTensorDescriptor' (aka 'at::Tensor') which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHDoubleTensor(THDoubleTensor *tensor);
```

### CODE REVIEW

**Review by goldsborough — APPROVED** [review]
As discussed offline, this fixes the clang warnings

**Comment by teng-li** [comment]
Ok. now should be good

**Review by apaszke — APPROVED** [review]

**Comment by goldsborough** [comment]
The builds work. Some of the test phases got aborted for some reason. This PR does not change any semantics, so I'll merge it so I can rebase my own PR on top of it.

**Pull request merged**
