### PR TITLE
Optimize sort kernel for contiguous tensors

### PR DESCRIPTION
**Pull request by abhishek-iitmadras**
Introduces enhancement for SortingKernel.cpp for cases where both the values and indices tensors have a stride 1, indicating contiguous memory layouts. 

The changes include:
1. A new function `sort_kernel_impl`, encapsulating the core sorting logic for distinct types of tensor accessors.
2. Modifications to the `sort_kernel` function to utilize `sort_kernel_impl`. It now checks for tensor strides and optimally handles contiguous and non-contiguous tensor scenarios.
3. The optimization aims to improve cache locality and efficiency in memory access for contiguous tensor sorts.
4. Enhanced Code Readability and Structure: The restructuring of the sorting process improves clarity and maintenance by clearly defining how different stride scenarios are handled, making the code more transparent and easier to understand.

Tests have been conducted across various tensor sizes and shapes to ensure stability and reliability of the change.

The result of running the `test/test_sort_and_select.py` test suite is consistent between the main branch, and this modified branch.

cc: @ezyang @mingfeima @nikitaved @malfet @ysiraichi @peterbell10 @ngimel 

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by maajidkhann** [comment]
@albanD @ezyang @mingfeima 
All the CI pipelines are passing now. Can you please review these changes whenever you get time.

**Comment by abhishek-iitmadras** [comment]
```
import torch
import timeit
import os

os.environ['OMP_NUM_THREADS'] = str(32)

# Seed the random number generator for reproducibility
torch.manual_seed(13)

# Define the sizes of the tensors to be created
sizes = [
    [10000, 10000],
    [1000, 1000, 100]
]

for size in sizes:
    t = torch.randn(*size)  # Create a random tensor of specified size
    dims = len(size)  # Determine the number of dimensions

    print(f"Tensor of size {size}")
    for dim in range(dims):
        print(f"Sorting for dim={dim}")
        print("float:")

        # Warm-up phase
        for _ in range(3):
            t.sort(dim=dim)

        time = timeit.timeit(lambda: t.sort(dim=dim), number=10)
        print(f"Time taken: {time} seconds")
    print()

```

Result:
Time in sec
Instance used for ARM: c7g.8xlarge , for x86 : c6i.8xlarge

image

cc @mingfeima

**Review by jgong5 — APPROVED** [review]

**Pull request closed without merging**
