### PR TITLE
Use cusolver potrs as the backend of cholesky_inverse for batch_size == 1 on CUDA

### PR DESCRIPTION
**Pull request by xwang233**
This PR adds the functionality to use cusolver potrs as the backend of cholesky_inverse for batch_size == 1 on CUDA.

Cusolver `potri` is **not** used, because

- it only returns the upper or lower triangular matrix as a result. Although the other half is zero, we may still need extra kernels to get the full Hermitian matrix
- it's no faster than cusolver potrs in most cases 
- it doesn't have a batched version or 64-bit version

`cholesky_inverse` dispatch heuristics:

- If magma is not installed, or batch_size is 1, dispatch to `cusolverDnXpotrs` (64 bit) and `cusolverDn<T>potrs` (legacy).
- Otherwise, use magma.

See also #42666 #47953

### CODE REVIEW

**Comment by xwang233** [comment]
r

**Comment by xwang233** [comment]
@mruberry This PR is ready for review. Test fails seem irrelevant.

**Comment by mruberry** [comment]
> @mruberry This PR is ready for review. Test fails seem irrelevant.

Awesome! Sorry for the delay. Please ping me if you don't get a response in 2 business days (that usually means a notification got lost).

**Review by mruberry — APPROVED** [review]
Thanks @xwang233!

@IvanYashchuk, would you like to take a look?

**Review by IvanYashchuk — APPROVED** [review]
Looks great! I like how concise the change for using cusolver is, given that we've got the potrs implemented.
Maybe implementing cholesky_inverse as a call to cholesky_solve on a higher level is something worth doing in the future.

**Pull request closed without merging**
