### PR TITLE
Add guard to use AMX for x86_64 only

### LINKED ISSUE #129443: Compilation failure on ARM
### 🐛 Describe the bug

There is a compilation failure when using the latest code from the main on ARM. It seems that PR https://github.com/pytorch/pytorch/pull/127195 which defined without an arch guard is only for x86?

```
[ 40%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/autocast_mode.cpp.o
[ 40%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/cpu/FlushDenormal.cpp.o
[ 40%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/cpu/Utils.cpp.o
/home/wuhy/pytorch_0625/aten/src/ATen/cpu/Utils.cpp: In function ‘bool at::cpu::init_amx()’:
/home/wuhy/pytorch_0625/aten/src/ATen/cpu/Utils.cpp:60:21: error: ‘SYS_arch_prctl’ was not declared in this scope; did you mean ‘SYS_prctl’?
   60 |   long rc = syscall(SYS_arch_prctl, ARCH_REQ_XCOMP_PERM, XFEATURE_XTILEDATA);
      |                     ^~~~~~~~~~~~~~
      |                     SYS_prctl
gmake[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/cpu/Utils.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
[ 40%] Linking CXX executable ../bin/vec_test_all_types_DEFAULT
gmake[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 40%] Built target vec_test_all_types_DEFAULT
gmake[1]: *** [caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
gmake: *** [all] Error 2
```

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (AltArch) (aarch64)
GCC version: (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)
Clang version: Could not collect
CMake version: version 3.29.3
Libc version: glibc-2.17

Python version: 3.8.19 (default, May 27 2024, 09:18:31)  [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] (64-bit runtime)
Python platform: Linux-4.18.0-80.7.2.el7.aarch64-aarch64-with-glibc2.17
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    1
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Model:                 0
CPU max MHz:           2600.0000
CPU min MHz:           2600.0000
BogoMIPS:              200.00
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              32768K
NUMA node0 CPU(s):     0-15
NUMA node1 CPU(s):     16-31
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] optree==0.11.0

### PR DESCRIPTION
**Pull request by atalman**
Trying to mitigate aarch64 and s390 nightly failures as per this comment:
https://github.com/pytorch/pytorch/pull/127195#issuecomment-2189177949

Fixes https://github.com/pytorch/pytorch/issues/129443

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by kiszk** [comment]
Looks good. I did not know aarch64 CI builds are also failing.

I am curious whether `&& !defined(__ANDROID__)` is still necessary.

**Review by nWEIdia — APPROVED** [review]
Thanks for the fix!

**Comment by swolchok** [comment]
build is still broken with this for me on mac:
```
pytorch/aten/src/ATen/cpu/Utils.cpp:37:34: error: use of undeclared identifier 'cpuinfo_has_x86_amx_tile'; did you mean 'cpuinfo_has_x86_mmx_plus'?
  return cpuinfo_initialize() && cpuinfo_has_x86_amx_tile();
```

**Review by malfet — APPROVED** [review]
LGTM

**Comment by malfet** [comment]
> build is still broken with this for me on mac:
> 
> ```
> pytorch/aten/src/ATen/cpu/Utils.cpp:37:34: error: use of undeclared identifier 'cpuinfo_has_x86_amx_tile'; did you mean 'cpuinfo_has_x86_mmx_plus'?
>   return cpuinfo_initialize() && cpuinfo_has_x86_amx_tile();
> ```

@swolchok you just need to update the submodule, this call is available for all arches, but is dummy false on everything but x86_64

**Pull request closed without merging**
