### PR TITLE
Make numpy/lib vendored tests dynamo traceable

### PR DESCRIPTION
**Pull request by ev-br**
Follow up https://github.com/pytorch/pytorch/pull/112146 and  #112141 : make numpy/lib vendored tests dynamo traceable

cc @mruberry @rgommers @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by lezcano — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting this again, but this is failing in trunk https://hud.pytorch.org/pytorch/pytorch/commit/190b6e4ba88f6cf00d0bd08d6212a3fe6bb76eaa' -c weird

The error is:

```
2023-10-26T22:10:07.4758959Z   File "torch_np/numpy_tests/lib/test_function_base.py", line 356, in test_basic_keepdims
2023-10-26T22:10:07.4760207Z     avg = np.average(x, axis=axis, keepdims=True)
2023-10-26T22:10:07.4761145Z   File "<__array_function__ internals>", line 4, in average
2023-10-26T22:10:07.4762558Z TypeError: _average_dispatcher() got an unexpected keyword argument 'keepdims'
```

I think there are multiple failures on your PR but they all look misleadingly flaky is because the `keep-going` label is added.  When this label is used, the job will continue even if a test already fails.  At the end, only the last failure is reported though, so you need to look at the raw log itself to find the failure.  May be it's a good idea to remove this label on this PR for now.

**Comment by huydhn** [comment]
Also feel free to ping me if you need an extra pair of eyes to review the failures on the PR

**Comment by ev-br** [comment]
@huydhn sorry for the churn this PR causes. Could you help me find out what are the numpy versions in the failing jobs please?

**Comment by lezcano** [comment]
@albanD do we have a minimum NumPy version we require? `requirements.txt` does not have one, which makes this a bit more difficult than needed.

**Comment by huydhn** [comment]
From what I see, the failed job is using `numpy==1.21.2` coming from here https://github.com/pytorch/pytorch/blob/main/.ci/docker/common/install_conda.sh#L55-L59

**Comment by ev-br** [comment]
Thank you @huydhn ! 
Let me separate the concerns: hammer this PR into shape to pass with this numpy version, and bump the numpy version separately. Speaking of which, what would be the target version?

**Comment by huydhn** [comment]
> Thank you @huydhn ! Let me separate the concerns: hammer this PR into shape to pass with this numpy version, and bump the numpy version separately. Speaking of which, what would be the target version?

Sounds good!  If possible, I would prefer `numpy==1.23.5` to match with that we have for 3.11 https://github.com/pytorch/pytorch/blob/main/.ci/docker/common/install_conda.sh#L55-L59

**Pull request closed without merging**
