### PR TITLE
correct spelling mistake

### PR DESCRIPTION
**Pull request by CCCCarpediem**
Fixes #ISSUE_NUMBER
correct spelling mistake

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
\easycla

**Comment by kit1980** [comment]
@CCCCarpediem please see the comment from linux-foundation-easycla about the CLA issue.

**Comment by CCCCarpediem** [comment]
> @CCCCarpediem please see the comment from linux-foundation-easycla about the CLA issue.

I already singned the cla, thanks for the reamind.

**Comment by kit1980** [comment]
@CCCCarpediem please follow the message linux-foundation-easycla. The email that was used for the PR needs to be added to your GitHub account.

**Comment by kit1980** [comment]
@CCCCarpediem Please don't spam merge. 
As I said, try to understand and follow the message from linux-foundation-easycla.

**Pull request closed without merging**
