### PR TITLE
[GHF] Add `Lint` to the list of mandatory checks

### PR DESCRIPTION
**Pull request by malfet**
Test that merge rules are geeen when CI is passing already exist, explicit failure test were added as well

### CODE REVIEW

**Comment by janeyx99** [comment]
How can we test this?

**Review by seemethere — APPROVED** [review]

**Review by janeyx99 — CHANGES_REQUESTED** [review]
Per our earlier discussion, please add a negative test case regarding mandatory checks :)

**Comment by malfet** [comment]
Added negative test (based on #74649), will land when lint is green

**Pull request closed without merging**
