### PR TITLE
.github: Adding configuration for backwards_compat

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #64218
* __->__ #64204
* #64201

Adds backwards_compat to our existing test matrix for github actions

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

cc @ezyang @seemethere @malfet @walterddr @lg20987 @pytorch/pytorch-dev-infra

Differential Revision: [D30646764](https://our.internmc.facebook.com/intern/diff/D30646764)

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30646764).

**Review by janeyx99 — COMMENTED** [review]
In the test logs, somehow the BUILD_ENVIRONMENT becomes linux-xenial-py3.6-gcc5.4-backwards_compat-backwards_compat, though at first glance at the file changes I don't see how that's happening

**Comment by seemethere** [comment]
> In the test logs, somehow the BUILD_ENVIRONMENT becomes linux-xenial-py3.6-gcc5.4-backwards_compat-backwards_compat, though at first glance at the file changes I don't see how that's happening

I believe it's because of these lines:

https://github.com/pytorch/pytorch/blob/f3e329cbec5f4f32e195bbe3b8b5b4d2b1323128/.jenkins/pytorch/test.sh#L22-L25

Which were added in https://github.com/pytorch/pytorch/pull/62896, instead of removing these lines I'm just going to remove this line here:

https://github.com/pytorch/pytorch/blob/master/.github/templates/linux_ci_workflow.yml.j2#L349

It'll be better for it to be in `.jenkins/pytorch/test.sh` so that it's more apparent where the environment variable is actually getting changed

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30646764).

**Comment by malfet** [comment]
Please delete the build from CircleCI

**Comment by seemethere** [comment]
> Please delete the build from CircleCI

There'll be follow up PRs to this that'll remove the builds from CircleCI

**Comment by seemethere** [comment]
> > Please delete the build from CircleCI
> 
> There'll be follow up PRs to this that'll remove the builds from CircleCI

Follow up PR: https://github.com/pytorch/pytorch/pull/64222

**Pull request closed without merging**
