### PR TITLE
Add ops.broadcast for nvFuser

### PR DESCRIPTION
**Pull request by IvanYashchuk**
Having nvFuser's `broadcast` available alongside `broadcast_in_dim` would allow easier experimentation.

cc @kevinstephano @jjsjann123

### CODE REVIEW

**Review by jjsjann123 — APPROVED** [review]
LGTM

**Review by kevinstephano — APPROVED** [review]
LGTM Hopefully, we can just remove the `broadcast_in_dim` fusion record in the future or replace it with an `expand`.

**Review by mruberry — APPROVED** [review]
Stamped!

**Pull request closed without merging**
