### PR TITLE
[HigherOrderOp] expose torch.cond

### PR DESCRIPTION
**Pull request by ydwu4**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #110293

This pr expose torch._higher_order_ops.cond as torch.cond.

1. Need to add #noqa: F811 to the _check calls in torch/__init__.py to address some confusing linter error "Redefinition of unused 'cond'" but only one cond is imported and for these lines that have this error, they don't define the cond but just use it as an argument.
2. Also add cond to the list that allows it to be traced through so as dynamo could trigger the CondHigherOrder logic instead of creating a TorchVariable.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Comment by huydhn** [comment]
@ydwu4 Sorry for the trouble.  This is not your mistake, but my fault instead.  Dr.CI has a new feature to detect similar flaky failures.  In this case, it has an false positive thinking a legit failure as flaky.  I'll create a follow up task to get this fixed.

**Pull request closed without merging**
