### PR TITLE
Assume sympy is always installed

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #94903

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by malfet — APPROVED** [review]
This feels a bit weird: aren't sympy a mandatory dependency of inductor?
Oh, but inductor is not available on Windows, ergo the exception

**Comment by ezyang** [comment]
I updated the PR to just require sympy all the time. Needs rereview

**Review by Skylion007 — APPROVED** [review]

**Review by malfet — COMMENTED** [review]
Hmm, please add it `requirements.txt` and may be to `setup.py` as well (as it is really need for pytorch core not just for CI)

**Comment by ezyang** [comment]
It's already in both

**Comment by BowenBao** [comment]
Is the update on onnx submodule accidental?

**Comment by ezyang** [comment]
yes gfd

**Pull request closed without merging**
