### PR TITLE
Replaced blacklist/whitelist in cmake/Codegen.cmakee 

### LINKED ISSUE #41747: Replace blacklist/whitelist in cmake/Codegen.cmake
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `cmake/Codegen.cmake`. See issue #41443 for more information.

### PR DESCRIPTION
**Pull request by ayanujju**
Fixes #41747 

Replaced all whitelist occurrences within the source with allowlist.

### CODE REVIEW

**Comment by ngimel** [comment]
Please fix CI errors.

**Comment by ljk53** [comment]
Please also rename https://github.com/pytorch/pytorch/blob/master/tools/code_analyzer/gen_op_registration_whitelist.py and update the param name and help message at: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/gen.py#L59-L62

There are some FB internal build files to be updated, too, which I can do after you fix the OSS CIs. Thanks!

**Comment by ayanujju** [comment]
Hi, I have proposed the changes but it goes into patch-3 and patch-4. So, should I create two more PR's?

**Comment by ljk53** [comment]
> Hi, I have proposed the changes but it goes into patch-3 and patch-4. So, should I create two more PR's?

Sorry I might have missed it - what is patch-3 / patch-4? Could you please merge these changes into a single PR? Because they need land together - if you rename the param on the caller side but not on the callee side then something will be broken...

**Pull request closed without merging**
