### PR TITLE
add description for unexpected case

### LINKED ISSUE #88547: `tensor(1) >> 64` will return 1 on CPU (`64 * n` is magic number)
### 🐛 Describe the bug

`tensor(1) >> 64` will return 1 on CPU, where `64 * n` is a magic number which means any other value except than `64*n` will return 0.

```py
import torch

cuda_output = torch.bitwise_right_shift(torch.tensor(1).cuda(), 1)
print(cuda_output)

cpu_output = torch.bitwise_right_shift(torch.tensor(1), 64)
print(cpu_output)
```

```
tensor(0, device='cuda:0')
tensor(1)
```

Any value than 64:

```py
for i in range(1, 1000):
    cpu_output = torch.bitwise_right_shift(torch.tensor(1), i)
    if cpu_output != 0:
        print(i, cpu_output)
```

```
64 tensor(1)
128 tensor(1)
192 tensor(1)
256 tensor(1)
320 tensor(1)
384 tensor(1)
448 tensor(1)
512 tensor(1)
576 tensor(1)
640 tensor(1)
704 tensor(1)
768 tensor(1)
832 tensor(1)
896 tensor(1)
960 tensor(1)
```

### Versions

torch: 1.13.0
cuda: 11.6

cc @svekars @carljparker @VitalyFedyunin @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### PR DESCRIPTION
**Pull request by ZhaoqiongZ**
Fixes #88547

### CODE REVIEW

**Review by mikaylagawarecki — COMMENTED** [review]
It seems like https://github.com/pytorch/pytorch/pull/96659 should have addressed this, however I do still see undefined behavior mentioned in the initial issue on 2.0.1

**Review by mingfeima — APPROVED** [review]

**Comment by mingfeima** [comment]
@svekars could you please help review this one ?

**Comment by mikaylagawarecki** [comment]
@ZhaoqiongZ  could you fix lint please

To fix the failing lint job running `setup_lint` and `quicklint` from your local pytorch directory and following the corresponding instructions should be sufficient, see [here](https://github.com/pytorch/pytorch/blob/4721553431e968ee5e90753346d92252cce98e84/Makefile#L25-L34)

**Comment by ZhaoqiongZ** [comment]
> @ZhaoqiongZ could you fix lint please
> 
> To fix the failing lint job running `setup_lint` and `quicklint` from your local pytorch directory and following the corresponding instructions should be sufficient, see [here](https://github.com/pytorch/pytorch/blob/4721553431e968ee5e90753346d92252cce98e84/Makefile#L25-L34)

Hi @mikaylagawarecki ， I tried lintrunner in my local repo but no specific instructions offered. So I try to fix the lint issue with the log generated by github

**Comment by mikaylagawarecki** [comment]
Did you run `lintrunner -a` after running lintrunner? There is still a whitespace that is failing lint

**Comment by ZhaoqiongZ** [comment]
> Did you run `lintrunner -a` after running lintrunner? There is still a whitespace that is failing lint

Hi @mabdullahsoyturk , fixed the lint issue.

**Review by mikaylagawarecki — APPROVED** [review]

**Pull request closed without merging**
