### PR TITLE
fix windows xpu build issue

### PR DESCRIPTION
**Pull request by guangyey**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #133845

# Motivation
If build XPU via oneAPI 2024.2, it will fail because `sycl-preview.lib` exists in windows. And linking the unexpected lib results in `error LNK2019: unresolved external symbol`.

# Solution
Use explicitly `sycl-preview` in linux build only.

# Additional Context
For `find_library`, please note that the variable will not be updated if it has been stored.
```
If the library is found the result is stored in the variable and the search will not be repeated unless the variable is cleared. 
```

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by min-jean-cho — APPROVED** [review]

**Comment by guangyey** [comment]
test pr

**Comment by guangyey** [comment]
@Skylion007 Thanks very much~
This PR needs to get approval first, could you help review it?

**Comment by guangyey** [comment]
This CI failure has been fix in https://github.com/pytorch/pytorch/pull/133843

**Review by EikanWang — APPROVED** [review]

**Comment by guangyey** [comment]
Hi @Skylion007, may I know if you could help review this PR?

**Review by atalman — APPROVED** [review]
lgtm, 1. please fix lint error before merging. 2. Lets get green signal for binary builds

**Comment by EikanWang** [comment]
Sure. Let me check it.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
