### PR TITLE
Replaced CHECK with TORCH_CHECK in order to not abort, but throw a Ru…

### LINKED ISSUE #117499: Using a non-lazy tensor on a lazy device leads to unhelpful abort and error message
### 🐛 Describe the bug

When writing PyTorch user code, sometimes we might forget to cast tensors to the right device, leading to a check that correctly errors out. However, on the lazy device setting, this leads to some hard debugging sessions as the current error handling is an abort that doesn't provide any helpful information.

For example, the following code:
```
import torch
import torch._lazy
import torch._lazy.ts_backend
torch._lazy.ts_backend.init()

torch.tensor([1], device="cpu") + torch.tensor([1], device="lazy")
```

leads to the error:
```
[F tensor.cpp:361] Check failed: lazy_tensor Input tensor is not a lazy tensor: CPULongType
Aborted
```
which doesn't have any helpful information on where this could occur. In very large code models, or someone who doesn't have much experience, this could lead to some hard debugging sessions.

This error comes from the `CHECK()` in https://github.com/pytorch/pytorch/blob/5c700f60a5ee588d32975fc0acd80dfc06e14425/torch/csrc/lazy/core/tensor.cpp#L361 whose definition is in https://github.com/pytorch/pytorch/blob/5c700f60a5ee588d32975fc0acd80dfc06e14425/torch/csrc/dynamo/eval_frame.c#L149 which calls the abort.

Changing this abort to an exception and being able to handle this in Python through pybind is one possible solution.

### Versions

Collecting environment information...
PyTorch version: 2.1.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: 3.4.2 (tags/RELEASE_34/dot2-final)
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.8.13 (default, Aug 16 2022, 12:16:29)  [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] (64-bit runtime)
Python platform: Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.2.5
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:              7
CPU MHz:               2500.000
BogoMIPS:              5000.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              36608K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single rsb_ctxsw fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 ida arat pku ospke

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.1.0
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] Could not collect

### PR DESCRIPTION
**Pull request by tringwald**
…ntimeError instead.

Fixes #117499.

### CODE REVIEW

**Review by antoniojkim — CHANGES_REQUESTED** [review]
Thanks for putting up this PR!

A quick search shows that there are other usages of `CHECK` inside `torch/csrc/lazy`. Can we at least change all of those in this PR?
```
$ rg -F " CHECK(" torch/csrc/lazy/
torch/csrc/lazy/core/tensor.cpp
361:  CHECK(lazy_tensor) << "Input tensor is not a lazy tensor: "

torch/csrc/lazy/core/tensor_impl.cpp
213:  CHECK(is_contiguous_) << "Non-contiguous storage for lazy tensor";

torch/csrc/lazy/ts_backend/ts_native_functions.cpp
72:    CHECK(dst_tensor);
79:    CHECK(self_tensor);
90:      CHECK(dst_tensor_data);
121:    CHECK(dst_tensor);
124:    CHECK(self_tensor);

torch/csrc/lazy/ts_backend/ts_node.cpp
94:  CHECK(!operands().empty());

torch/csrc/lazy/ts_backend/ts_backend_impl.cpp
223:      CHECK(

torch/csrc/lazy/ts_backend/ts_lowering_context.cpp
36:    CHECK(!ops.empty()) << "Failed to lower: " << *node;

torch/csrc/lazy/python/init.cpp
264:              CHECK(tsDataPtr->scalar.has_value());
```

**Comment by tringwald** [comment]
Do we want some more descriptive error messages for those cases? At the moment, they will just show some generic error message.
Do we also need additional tests for those `TORCH_CHECKS`? Up until now, they just `abort`ed, which probably nobody tested for.

**Review by antoniojkim — APPROVED** [review]

**Comment by antoniojkim** [comment]
> Do we want some more descriptive error messages for those cases? At the moment, they will just show some generic error message. Do we also need additional tests for those `TORCH_CHECKS`? Up until now, they just `abort`ed, which probably nobody tested for.

CC: @wconstab @JackCaoG @alanwaketan

**Review by JackCaoG — APPROVED** [review]

**Review by alanwaketan — APPROVED** [review]

**Comment by wconstab** [comment]
Ideally add a brief description msg to those calls with just tensors but no need to add a test for them. Lgtm

**Comment by antoniojkim** [comment]
@tringwald @malfet Is there any chance we'll be able to include this in 2.2.0 or even 2.2.1?

**Comment by antoniojkim** [comment]
Getting it into `2.2.1` would be very much appreciated. Trying to debug the aborts has been quite difficult for our users

**Pull request closed without merging**
