### PR TITLE
inductor: add conv+hardsigmoid fusion for cpu path

### PR DESCRIPTION
**Pull request by XiaobingSuper**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #91609
* __->__ #91433

cc @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @Guobing-Chen @chunyuan-w @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by mehtanirav** [comment]
This PR is causing internal builds to fail with the following errors:

```
 error: no member named 'eltwise_hardsigmoid' in 'dnnl::algorithm'; did you mean 'eltwise_logsigmoid'?
```

Please do not re-land this PR until ideep is upgraded to a newer version internally. @weiwangmeta  can you please provide guidance on when it is safe to reland this PR.

**Pull request closed without merging**
