### PR TITLE
Skip mutation tests on rocm

### LINKED ISSUE #118585: DISABLED test_find_mutations (__main__.MutationTests)
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22dynamo%2Ftest_triton_kernels.py%3A%3AMutationTests%3A%3Atest_find_mutations%22%5D)).

PR #117300 seems to have broken rocm ci.  CC @oulgen @jansel

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### PR DESCRIPTION
**Pull request by oulgen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #118588

Fixes #118585

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by aakhundov — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by oulgen** [comment]
@pytorch merge -f "rocm tests are queued too long, this pr skips them"

**Comment by jataylo** [comment]
Hey @oulgen I was curious if you had any initial indication on why this broke for ROCm (https://github.com/pytorch/pytorch/issues/118585)?

Logfile here for context
https://ossci-raw-job-status.s3.amazonaws.com/log/20961088321
```
AssertionError: Lists differ: ['in_ptr0', 'in_ptr1', 'out_ptr'] != ['out_ptr']
```

It seems that this indicates an incorrect result in output? I would guess we are best to start digging into the custom implementations e.g. `add_kernel` to triage this one to make sure they are working correctly for us? 

Thought I'd ask incase you have any additional insight here

**Comment by oulgen** [comment]
The test failed because this test checks whether a certain optimization worked but the optimization threw an exception so we bailed out on it. Something about triton autotune does not on ROCm. I have not been able to investigate it since I haven't been able to get a machine with a ROCm on my hand.

**Pull request closed without merging**
