### PR TITLE
use mutable_data_ptr after calls to at::empty in BatchLinearAlgebra

### PR DESCRIPTION
**Pull request by dagitses**
use mutable_data_ptr after calls to at::empty in BatchLinearAlgebra

Summary:
These are known to be safe since there's no data to read.

Test Plan: Rely on CI.

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/pytorch/pull/99358).
* #99361
* __->__ #99358

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
Fair enough

**Comment by dagitses** [comment]
accidentally merged this PR's commit with its Sapling descendent. No harm no foul since CI passed and this was approved.

**Pull request closed without merging**
