### PR TITLE
[ONNX] disable size optimizations

### PR DESCRIPTION
**Pull request by eellison**
Seeing which tests fail in the CI.

### CODE REVIEW

**Comment by BowenBao** [comment]
@eellison the failure in onnx test `test_dim` reveals an issue with jit, instead of onnx export. I have created a small repro for you to look at.

```python
import torch

class DimModel(torch.nn.Module):
    def forward(self, input):
        out = input * 2
        out *= out.dim()
        return out

m = torch.jit.script(DimModel())

input_1 = torch.arange(6).view(2, 3)
print(m(input_1))
"""
outputs tensor([[ 0,  4,  8],
        [12, 16, 20]])
"""

input_2 = torch.arange(6).view(1, 2, 3)
print(m(input_2))
"""
outputs tensor([[ 0,  4,  8],
        [12, 16, 20]])

but should be tensor([[[ 0,  6, 12],
         [18, 24, 30]]])
The correct result can also be produced if DimModel()(input_1) is commented
"""
```

**Comment by eellison** [comment]
@BowenBao when I check the results against eager I don't get any difference:
```
import torch

class DimModel(torch.nn.Module):
    def forward(self, input):
        out = input * 2
        out *= out.dim()
        return out

m = torch.jit.script(DimModel())
eager = DimModel()

input_1 = torch.arange(6).view(2, 3)
self.assertEqual(eager(input_1), m(input_1))

input_2 = torch.arange(6).view(1, 2, 3)
self.assertEqual(eager(input_2), m(input_2))
```

**Comment by BowenBao** [comment]
@eellison what is self in the snippet above? I changed `self.assertEqual` to `print` and got the following
```
tensor([[ 0,  4,  8],
        [12, 16, 20]]) tensor([[ 0,  4,  8],
        [12, 16, 20]])
tensor([[[ 0,  6, 12],
         [18, 24, 30]]]) tensor([[[ 0,  4,  8],
         [12, 16, 20]]])
```
Could you verify if you are using the pytorch build of this pr?

**Comment by eellison** [comment]
Yep, I ran it again on `3a9fc1265dad403479a35f405452853ae0ae6ed8`, no failure. 

```
import torch
class DimModel(torch.nn.Module):
    def forward(self, input):
        out = input * 2
        out *= out.dim()
        return out

m = torch.jit.script(DimModel())
eager = DimModel()

input_1 = torch.arange(6).view(2, 3)
print(eager(input_1), m(input_1))
# tensor([[ 0,  4,  8],
#        [12, 16, 20]]) tensor([[ 0,  4,  8],
#        [12, 16, 20]])

input_2 = torch.arange(6).view(1, 2, 3)
print(eager(input_2), m(input_2))
# tensor([[[ 0,  6, 12],
#         [18, 24, 30]]]) tensor([[[ 0,  6, 12],
#        [18, 24, 30]]])
```

**Comment by BowenBao** [comment]
@eellison that's strange, this is the repro I fetched from the CI failure.

```
Mar 27 00:10:14     def test_dim(self):
Mar 27 00:10:14         class DimModel(torch.jit.ScriptModule):
Mar 27 00:10:14             @torch.jit.script_method
Mar 27 00:10:14             def forward(self, input):
Mar 27 00:10:14                 out = input * 2
Mar 27 00:10:14                 out *= out.dim()
Mar 27 00:10:14                 return out
Mar 27 00:10:14         empty_input = torch.randn(0, requires_grad=True)
Mar 27 00:10:14         multi_dim_input = torch.randn(1, 2, 3, requires_grad=True)
Mar 27 00:10:14         self.run_test(DimModel(), empty_input)
Mar 27 00:10:14 >       self.run_test(DimModel(), multi_dim_input)
...
Mar 27 00:10:14 >   [np.testing.assert_allclose(out, ort_out, rtol=rtol, atol=atol) for out, ort_out in zip(outputs, ort_outs)]
Mar 27 00:10:14 E   AssertionError: 
Mar 27 00:10:14 E   Not equal to tolerance rtol=0.001, atol=1e-07
Mar 27 00:10:14 E   Mismatch: 100%
Mar 27 00:10:14 E   Max absolute difference: 8.715158
Mar 27 00:10:14 E   Max relative difference: 0.6666667
Mar 27 00:10:14 E    x: array([[[ 3.081992, -0.586858, -4.357579],
Mar 27 00:10:14 E           [ 1.136863, -2.169045, -2.797191]]], dtype=float32)
Mar 27 00:10:14 E    y: array([[[  9.245976,  -1.760573, -13.072737],
Mar 27 00:10:14 E           [  3.410588,  -6.507134,  -8.391573]]], dtype=float32)
```

**Pull request closed without merging**
