### PR TITLE
functionalization: skip meta reference compute for aot autograd

### PR DESCRIPTION
**Pull request by bdhirsh**
The context is that historically, XLA/LTC tensors haven't had accurate stride information, and functionalization would run "reference" meta kernels for view ops on the side to properly compute strides.

This is more complicated in symint tracing world - we have a `FunctionalTensorWrapper()` that wraps the underlying tensor and has its own set of sizes/strides metadata, but we never create proxy objects for the sizes/strides of the wrapper.

In symint tracing world with aot autograd, we're guaranteed that our underlying strides are accurate anyway, since aot autograd uses fake tensors to perform tracing. We encountered a few bugs with symint's from the `FunctionalTensorWrapper` making their way into `__torch_dispatch__`. To side-step that area of bugs completely (and marginally improve perf), this PR disables the meta tensor tracing for non XLA/LTC use cases.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #87255
* __->__ #87108
* #86611

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by bdhirsh** [comment]
@ezyang I'm seeing some interesting UBSAN errors, that seem to have been uncovered around `SymIntNodeImpl` (unrelated to functionalization) - I've been staring at them for a while but I'm wondering if you have any insight ([logs](https://github.com/pytorch/pytorch/actions/runs/3267845592/jobs/5373808935))

The error is:
```
/var/lib/jenkins/workspace/c10/util/intrusive_ptr.h:267:45: runtime error: upcast of misaligned address 0x1ebebebebebebebe for type 'c10::SymIntNodeImpl', which requires 8 byte alignment
0x1ebebebebebebebe: note: pointer points here
<memory cannot be printed>
    #0 0x7fa87c57392d in c10::intrusive_ptr<c10::SymIntNodeImpl, c10::detail::intrusive_target_default_null_type<c10::SymIntNodeImpl> >::retain_() (/opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so+0x12292d)
    #1 0x7fa87c569ca7 in c10::SymInt::toSymIntNodeImpl() const (/opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so+0x118ca7)
    #2 0x7fa889ed1b90 in c10::SymInt::SymInt(c10::SymInt const&) (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xd71cb90)
```

Some googling around led me [here](https://stackoverflow.com/questions/46474238/misaligned-address-using-virtual-inheritance), and I was wondering if something funky is going on around our subclassing of `intrusive_ptr`, but I'm not too sure yet.

**Comment by ezyang** [comment]
The bebebe pattern in the address suggests that you're reading out of some garbage memory that we memset to 0xBE but I don't actually see anywhere in our codebase where we use the 0xBE bit pattern.

Are you sure this isn't functionalization related? I feel that the aotdispatch tests will be calling functionalization? 

You should put your heads together with @anjali411, @albanD were investigating another memory error and I wonder if this is the same root cause.

**Comment by bdhirsh** [comment]
I don't think the ASAN failure is actually related to this change (original hypothesis from Horace's previous PR was that this PR might fix the skipped test), so I'm going to leave the test skipped and land this PR in the interest of fixing a few dynamic shapes models

**Review by wconstab — APPROVED** [review]
thanks for fixing!

**Comment by bdhirsh** [comment]
> Are you sure this isn't functionalization related? I feel that the aotdispatch tests will be calling functionalization?

Oh the segfault shows up in `test_proxy_tensor.py` (Horace added a [skip](https://github.com/pytorch/pytorch/blob/e4285f09b9993d4a17b755c74b68bed69f7473d0/test/test_proxy_tensor.py#L1315) for a segfaulting batch_norm test), which is why I think it's unrelated to functionalization.

**Pull request closed without merging**
