### PR TITLE
Fixed broken link and removed unfinished sentence from issue #126367

### LINKED ISSUE #126367: Broken Link and unfinished sentence in Frequently Asked Questions
### 📚 The doc issue

In the `torch.compiler_faq.rst` file, there is a sentence that reads: The basic strategy for optimizing DDP with Dynamo is outlined in [distributed.py](https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/optimizations/distributed.py) where the main idea will be to graph break on [DDP bucket boundaries](https://pytorch.org/docs/stable/notes/ddp.html#internal-design).

However, the hyperlink that should lead to `distributed.py` is not functioning correctly. When clicked, it does not redirect to the intended destination, it seems the file is no longer available at the specified location.

In the same file, there is an unfinished sentence that reads:
`For example, Inductor first takes care of fusing whatever it can and only then generates Triton kernels. It can also`

This sentence ends abruptly and does not provide complete information. 

### Suggest a potential alternative/fix

I believe the distributed.py file mentioned in the documentation might be located at `torch/_dynamo/backends/distributed.py`. If this is the correct file, updating the hyperlink to point to this location should resolve the issue. However, please verify this as I might be mistaken.

Regarding the unfinished sentence I believe the `It can also` can be removed, but if there is something more to be said it should be completed.

cc @svekars @brycebortree

### PR DESCRIPTION
**Pull request by ignaciobartol**
Fixes #126367. 

## Description

Fixed a broken link in the pytorch/docs/source/torch.compiler_faq.rst doc and deleted a few words that were extra according to the issue tagged above. 

## Checklist 
- [X] The issue that is being fixed is referred in the description
- [X] Only one issue is addressed in this pull request
- [X] Labels from the issue that this PR is fixing are added to this pull request
- [X] No unnecesary issues are included into this pull request

cc @svekars @brycebortree

### CODE REVIEW

**Review by msaroufim — APPROVED** [review]

**Comment by svekars** [comment]
Feel free to force merge with `@pytorchbot merge -f "Doc only change to an .rst file."`

**Comment by ignaciobartol** [comment]
> Feel free to force merge with `@pytorchbot merge -f "Doc only change to an .rst file."`

Should I go ahead a merge now or do I need to wait for all the tests to be completed? Sorry is my first PR in PyTorch so I wasn’t sure if should have done that before.

**Pull request closed without merging**
