### PR TITLE
[dynamo] Allow asserts to fail

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #126661

Currently if an assertion is statically known to be false, dynamo converts it to
`_assert_async` which inductor currently ignores. Instead this graph breaks to
raise the original assertion.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by lezcano — CHANGES_REQUESTED** [review]
I don't like this one. I think it should be:
- If we can prove that it's true or false, then act accordingly.
- Otherwise, process it as runtime assert

This way we can use asserts to add facts to our knowledge base (shape env).

cc @ezyang

**Comment by peterbell10** [comment]
> If we can prove that it's true or false, then act accordingly.

That's what this does. If we statically know it's true we graph break and let python raise the exception.

**Review by ezyang — APPROVED** [review]
Yeah, this LGTM, thanks @peterbell10

**Comment by lezcano** [comment]
uh, sorry, I had misread the code. I thought this was also handling the expression being equal to `None`.

**Pull request closed without merging**
