### PR TITLE
refactor KERNEL_MPS via resuing KERNEL

### PR DESCRIPTION
**Pull request by guangyey**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137831
# Motivation
Reuse `KERNEL` to simplify `KERNEL_MPS` for mps autocast code.

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Comment by guangyey** [comment]
@malfet and @albanD could you help review this PR?

**Review by malfet — APPROVED** [review]
Thank you for the refactor

**Pull request closed without merging**
