### PR TITLE
fix the error  UnicodeDecodeError: 'ascii' codec can't decode byte 

### PR DESCRIPTION
**Pull request by urandu**
Fixed bug on issue #25891 

ref https://stackoverflow.com/questions/42603373/how-do-i-change-the-environment-variable-lang-from-within-a-python-script

### CODE REVIEW

**Comment by sclarkson** [comment]
The issue with this is that Python 2 won't be able to print an exception with a UTF-8 message.

After making that change:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    extra_include_paths=["/usr/include/python2.7"])
  File "/home/sclarkson/.local/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 787, in load_inline
    is_python_module)
  File "/home/sclarkson/.local/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 827, in _jit_compile
    with_cuda=with_cuda)
  File "/home/sclarkson/.local/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 880, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/sclarkson/.local/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 973, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: <exception str() failed>
```

**Comment by urandu** [comment]
@sclarkson I will try a different approach. Do you have any pointers?

**Comment by cpuhrsch** [comment]
@urandu - you might get more visibility for your question in the main issue this PR references.

**Comment by ezyang** [comment]
How about, decode as utf-8 and ignore errors?

**Comment by sclarkson** [comment]
@ezyang You're saying give no output at all for a compilation error on Python 2? I still think the best solution is to set LC_ALL=C on Python 2 only. I'm not sure what to do about Windows, though. 

Another option would be to decode as ascii and ignore errors `error.output.decode('ascii', 'ignore')` on Python 2.

**Comment by ezyang** [comment]
> Another option would be to decode as ascii and ignore errors error.output.decode('ascii', 'ignore') on Python 2.

That's what I meant. You should still get legible error messages in that case.

**Comment by urandu** [comment]
I will implements @sclarkson `s suggestion then update the PR.

**Review by ezyang — APPROVED** [review]

**Review by ezyang — CHANGES_REQUESTED** [review]
Actually, on second thought, what I would like is for the decoding here to respect the current locale (so if I'm running in UTF-8 locale, I should be able to see UTF-8 data) but then ignore decoding errors if there any. As the code is written here, we will *unconditionally* nuke all UTF-8 characters even when everything would have been ok.

**Comment by sclarkson** [comment]
@ezyang I initially suggested against doing that here https://github.com/pytorch/pytorch/pull/25939#issuecomment-530097751 because that would require doing something like this to get the actual error output.

```
import torch.utils.cpp_extension

try:
    torch.utils.cpp_extension.load_inline(
            name="test", 
            cpp_sources="int main() { return 0 }",
            extra_include_paths=["/usr/include/python2.7"])
except RuntimeError as e:
    print(e.message)
```

Upon further consideration, maybe that's not an unreasonable expectation.

**Comment by urandu** [comment]
Closing this PR, it has been open for too long and python 2 is no longer supported

**Pull request closed without merging**
