### PR TITLE
[CI] Run periodic jobs only on pytorch/pytorch repo

### PR DESCRIPTION
**Pull request by malfet**
Github by default tries to not run periodic jobs on forks, see https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/disabling-and-enabling-a-workflow
But there is a special test repo called `pytorch/canary`, that will run those workflows for next 60 days, which is a waste of resources

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
Nice! Could you disable those perf benchmark jobs too, i.e. https://github.com/pytorch/pytorch/blob/main/.github/workflows/inductor-perf-test-nightly-aarch64.yml?

**Comment by malfet** [comment]
> Nice! Could you disable those perf benchmark jobs too, i.e. https://github.com/pytorch/pytorch/blob/main/.github/workflows/inductor-perf-test-nightly-aarch64.yml?

Wow, I've never realized how many periodic jobs we have... Almost every workflow has some periodic aspect to it

@ZainRizvi do we have numbers on resource utilization per github event type?

**Comment by huydhn** [comment]
> Wow, I've never realized how many periodic jobs we have... Almost every workflow has some periodic aspect to it

Yeah, it takes me by surprise too, I guess we just don't pay attention to canary.  I don't see a big monthly bill from canary though https://torchci-git-wdvr-costanalysis-fbopensource.vercel.app/cost_analysis?startDate=2023-10-26&endDate=2024-10-25&granularity=month&groupby=workflow_name&chartType=line&yAxis=cost, still a waste nonetheless.

**Pull request closed without merging**
