### PR TITLE
Fix the issue that run clang-tidy on the aten folder

### PR DESCRIPTION
**Pull request by chengjinfang1216**

### CODE REVIEW

**Comment by ShawnZhong** [comment]
I think we need to modify the pre-commit hook as well.

**Comment by chengjinfang1216** [comment]
Hi @ShawnZhong, thank you for your kind reminder, I modified the code and request the PR again, thanks a lot.

**Comment by SplitInfinity** [comment]
@mruberry 

I know things about `clang-format`, not `clang-tidy`, so I don't think I'm the right person to review this.

**Comment by mruberry** [comment]
> @mruberry
> 
> I know things about `clang-format`, not `clang-tidy`, so I don't think I'm the right person to review this.

In the interest of progressive approximation to the correct solution, would you like to recommend someone?

**Review by SplitInfinity — APPROVED** [review]
Looks fine to me

**Comment by chengjinfang1216** [comment]
Hi, @SplitInfinity, I found this PR‘s merge is blocked, is there anything else that needs to be modified, if there is, I'm glad to do that.

**Comment by mruberry** [comment]
Thanks for the ping, @chengjinfang1216, I've imported your pull request where it will run against some internal tests, and once those pass I'll be able to land this for you.

**Comment by mruberry** [comment]
This PR was successfully merged!

**Pull request closed without merging**
