### PR TITLE
Format generated structured kernels code better

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #55691 [PyTorch] Migrate add operators to borrow in TensorIteratorBase
* #55690 [PyTorch] Support borrowing in/out Tensors in TensorIterator
* #55940 [PyTorch] Always update op.current_dtype in TensorIteratorBase::set_output
* #55420 [PyTorch] Remove non-const TensorIterator::tensor() method
* **#55258 [PyTorch] Format generated structured kernels code better**
* #55351 [PyTorch] Fix const correctness for resize native functions

Prior to this diff, the generated code contained whitespace-only lines and odd indenting. Now, it is easier to read.

Differential Revision: [D27544604](https://our.internmc.facebook.com/intern/diff/D27544604/)

### CODE REVIEW

**Comment by ezyang** [comment]
I'm very sympathetic to what this diff is trying to solve and I don't like how the diff solves it XD

As a historical note, we used to not use f-strings and used a CodeTemplate class (still in use in the autograd codegen) which automatically handled proper indentation by detecting multiline substitutions and automatically indenting them based on the level of indentation in the template. I can't figure out a way to simulate this in f-strings (as the f-string mechanism is not overloadable). I suppose I can live with explicit function calls to indent but we're going to have do this patch a little differently, since the way you've set it up is failing lint. I think my preference is to just use multiline strings; if you hate the indentation being wrong we can just `textwrap.dedent` them (I think that's how @robieta likes to do it)

BTW, I also considered whether or not we should just botch the indenting and then fix it in the end by shelling out to clang-format (or implementing a faster but shitty indenter ourselves)... couldn't quite bring myself to do it, but it saves us from having to manually get it right at call sites.

**Comment by robieta** [comment]
I mostly lean on `textwrap.dedent` so my templates can match the rest of the body. e.g.

```
def foo():
    s = textwrap.dedent("""
        This text doesn't care about foo.
        And I can even **further** indent it!
    """)
  
def bar():
    s = """
This is very
ugly to me.
"""
```

Unfortunately it only works when you know there are no newlines.
```
def foo():
    x = "a\nb\nc"
    print(textwrap.dedent(f"""
        {x}
    """))
```

```
>>> foo()
        a
b
c
```

If we just want to make the code easier to read maybe we should write a helper that indents all lines but the first, so you could write:
```
def foo():
    x = "a\nb\nc"
    
    # f-string templating happens before dedent, so we have to match the indentation including indentation for `foo`
    print(textwrap.dedent(f"""
        {strawman_indent(x, 8)}
    """))
```

I don't have strong feelings one way or the other. I agree it would be awesome if we could override f-string behavior, but alas.

**Review by ezyang — APPROVED** [review]
not gonna bikeshed this too much

**Review by bhosmer — APPROVED** [review]

**Comment by swolchok** [comment]
test run for 0618524  is passing, sending new commit to fix flake8, if flake8 passes there I'm calling this landable

**Pull request closed without merging**
