### PR TITLE
Remove the legacy code about selective build

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by ezyang** [comment]
This is OK as a hotfix, but why don't we just delete all of this code entirely?

**Comment by peterjc123** [comment]
@ezyang What do you mean by `delete all of this code`?

**Comment by ezyang** [comment]
The logic which checks enabled-configs.txt and disabled-configs.txt and errors/passes the build accordingly. This was my attempt at making a way where you could selectively enable/disable configs when testing builds, but we now have better ways of doing this, and no one actually uses this knob. Let's just kill it.

**Comment by peterjc123** [comment]
Okay, BTW, may I know the preferred way of doing selective builds currently?

**Comment by ezyang** [comment]
There's some code in `.circleci/config.yml` for making `[slow ci]` and `[xla ci]` work, just grep for those strings. It's not applied everywhere else but it would be a reasonable enhancement work. also cc @zou3519

**Comment by peterjc123** [comment]
@ezyang I've deleted these code.

**Pull request closed without merging**
