### PR TITLE
[dtensor] move ops to private

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #131210
* __->__ #131211
* #131212

as titled

cc @XilunWu @H-Huang @awgu @kwen2501 @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

Differential Revision: [D60132519](https://our.internmc.facebook.com/intern/diff/D60132519)

### CODE REVIEW

**Review by XilunWu — APPROVED** [review]

**Comment by wz337** [comment]
Once this diff stack is imported to fbcode, there is one import in a unit test for apex dtensor support that needs to be updated as well. I could not import from UI now cuz the PR is using ghstack, but I have a forward fix diff ready internally.

**Review by wz337 — APPROVED** [review]

**Comment by wanchaol** [comment]
> Once this diff stack is imported to fbcode, there is one import in a unit test for apex dtensor support that needs to be updated as well. I could not import from UI now cuz the PR is using ghstack, but I have a forward fix diff ready internally.

Oh thanks for catching this! I'll try to ghimport this instead and include the changes to avoid being reverted

**Comment by wz337** [comment]
> > Once this diff stack is imported to fbcode, there is one import in a unit test for apex dtensor support that needs to be updated as well. I could not import from UI now cuz the PR is using ghstack, but I have a forward fix diff ready internally.
> 
> Oh thanks for catching this! I'll try to ghimport this instead and include the changes to avoid being reverted

Ye. I think as long as we stack the fix on top of your diff stacks so they can be landed together, it should be good. D60085859 Otherwise, you would need to ghimport to include the change and then do a ghexport. Whichever is easier for you works.

**Comment by wanchaol** [comment]
@wanchaol has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60132519).

**Pull request closed without merging**
