### PR TITLE
Add numpy like repeat as torch.repeat_interleave

### LINKED ISSUE #14093: [feature request] np.repeat like function
We have `tensor.repeat`, which is really `np.tile`. :)

It seems that it could be implemented via `expand`s + a `cat`, if `cat` doesn't contiguous-fy the inputs...

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fixes: https://github.com/pytorch/pytorch/issues/14093
cc: @SsnL

### CODE REVIEW

**Comment by SsnL** [comment]
Thanks for doing this! I think we should name it something other than `numpy_repeat`. @gchanan may have good suggestions!

**Comment by zasdfgbnm** [comment]
@SsnL I was thinking about `repeat2` but feeling bad...

**Review by apaszke — DISMISSED** [review]
`numpy_repeat` is not a good name. Maybe `repeat_interleave`?

**Comment by zasdfgbnm** [comment]
@apaszke `repeat_interleave` sounds better, I have renamed it to `repeat_interleave`

**Comment by gchanan** [comment]
CC @umanwizard.

**Review by ifedan — APPROVED** [review]

**Comment by zasdfgbnm** [comment]
Just resolved a merge conflict.

**Comment by ezyang** [comment]
It failed internal tests but it's not your fault.

**Comment by ezyang** [comment]
@umanwizard can you please rebase the internal diff and reland it?

**Comment by umanwizard** [comment]
Sorry, I have been trying to land this for the last few days and keep running into issues. Just commenting here @zasdfgbnm to let you know I haven't forgotten about it.

**Comment by zasdfgbnm** [comment]
@umanwizard Thanks for letting me know! Just take your time, and let me know if there is anything I can help.

**Pull request closed without merging**
