### PR TITLE
Don't materialize gradOut for outputs that don't require gradients

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #97428
* __->__ #98659
* #98657

### CODE REVIEW

**Review by ezyang — CHANGES_REQUESTED** [review]
I don't think you can do this without the second level cache in backwards. The set of None inputs passed to backward can vary from backward-call to call depending on what outputs actually end up getting used, and with this optimization you will need to recompile backwards when this happens.

I think recompiling is the correct choice, but we need the code to actually do it.

**Comment by Chillee** [comment]
@ezyang This is definitely a temp diff to gather perf results, but I don't think the approach here requires recompiling the backwards (in principle). The main tensors I want to avoid materializing are the gradOuts for tensors that don't require grad, which will never change in the backwards pass.

**Comment by ezyang** [comment]
Why do you need to call set_materialize_grads then 🤔

**Comment by ezyang** [comment]
If we have an output that doesn't require grad, we should mark it `mark_non_differentiable`, and we should never materialize grads for it. Also cc @albanD

**Comment by albanD** [comment]
Is what you want to do in spirit is change the compiled function to take Optional[Tensor] for each gradOutput. Then you can pass None and the compiled function will properly handle it?
And you disable materialization of gradients to make sure autograd doesn't materialize these grads.

**Comment by Chillee** [comment]
@ezyang we do mark it as `non_differentiable`, but I think autograd.Function is still materializing the tensors.

**Comment by ezyang** [comment]
Then we should just fix custom function!

**Comment by albanD** [comment]
That would be BC-breaking but we can do it I think.

**Comment by ezyang** [comment]
I mean, if you really want to, we can add a separate knob for this specific case. But it doesn't seem like you want zero filled tensors for nondifferentiable outputs ever

**Comment by albanD** [comment]
I agree we want to do it. It should still be marked as BC-breaking so that we can properly warn users in the release notes.

**Pull request closed without merging**
