### PR TITLE
[TEST ONLY] Test CUDA 8 build on Windows

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by peterjc123** [comment]
It seems that we have to implement a hash function for the struct type `TensorDesc`. The error `C2338: The C++ Standard doesn't provide a hash for this type` was thrown at `torch/csrc/jit/fusion_compiler.h(85)`.

**Comment by yf225** [comment]
@peterjc123 Do you want to open a PR for the Windows CUDA 8 fixes? We probably should fix those things to support Windows CUDA 8 properly.

**Comment by yf225** [comment]
@peterjc123 I found that there are more errors before the hash function error:

```
13:28:20 ..\torch\csrc\jit\interned_strings.cpp(30): error C2051: case expression not constant
13:28:20 ..\torch\csrc\jit\interned_strings.cpp(42): error C2051: case expression not constant

13:28:21 ..\torch\csrc\jit\autodiff.cpp(77): error C2051: case expression not constant
13:28:21 ..\torch\csrc\jit\autodiff.cpp(78): error C2051: case expression not constant
13:28:21 ..\torch\csrc\jit\autodiff.cpp(79): error C2051: case expression not constant
13:28:21 ..\torch\csrc\jit\autodiff.cpp(80): error C2051: case expression not constant
13:28:21 ..\torch\csrc\jit\autodiff.cpp(81): error C2051: case expression not constant
13:28:21 ..\torch\csrc\jit\autodiff.cpp(82): error C2051: case expression not constant
13:28:21 ..\torch\csrc\jit\autodiff.cpp(84): error C2051: case expression not constant

13:28:21 ..\torch\csrc\jit\export.cpp(51): error C2051: case expression not constant
```

I suspect that similar fixes to these files might be able to fix all errors.

**Comment by peterjc123** [comment]
@yf225 I think it will be a better idea to patch `NVCC_CCBIN` rather than changing the switch statements to if statements.

**Pull request closed without merging**
