### PR TITLE
Update rnnFusedPointwise.py to revert bias shape

### PR DESCRIPTION
**Pull request by ShigekiKarita**
related to this issue https://github.com/pytorch/pytorch/issues/1721

### CODE REVIEW

**Comment by soumith** [comment]
cc: @csarofeen looks okay?

**Comment by apaszke** [comment]
No, they shouldn't have been modified in-place. We should overwrite the references with a result of an out of place unsqueeze

**Comment by csarofeen** [comment]
I will do this and include it in my next version of https://github.com/pytorch/pytorch/pull/1683

**Comment by ShigekiKarita** [comment]
@csarofeen thanks!

**Comment by apaszke** [comment]
#1683 already fixes it so I'm closing this. Thank you!

**Pull request closed without merging**
