### PR TITLE
Small fixes for hipification

### PR DESCRIPTION
**Pull request by serhaty**
Summary: We do not hipify these files when doing out of place.

Test Plan: wait for CI to clear.

Differential Revision: D18963683

### CODE REVIEW

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit 9e1bcba:
* **1/1** broken upstream at merge base bcb0bb7 (see [grid view](https://dr.pytorch.org/master-timeline.html?count=1&sha1=bcb0bb7e0e03b386ad837015faba6b4b16e3bfb9&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35))
    * You may want to rebase on the `viable/strict` branch (see its [recency history](https://dr.pytorch.org/master-viable-commits.html)):
        * If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
          ```
          git fetch viable/strict
          git rebase --onto viable/strict $(git merge-base origin/master HEAD)
          ```
        * If your commit is older than `viable/strict`:
          ```
          git fetch viable/strict
          git rebase viable/strict
          ```
* **0/1** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=9e1bcbabd80baa0a40eb6b1bb56bdfcfc5372422).

### 1 failure *not* recognized by patterns:
| Job | Step |
| --- | --- |
| CircleCI <sup>pytorch_windows_build</sup> | <sup>Build</sup> |


---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Review by bddppq — COMMENTED** [review]
Can we hipify these files instead?

**Comment by serhaty** [comment]
@bddppq the changes to files used for cpu build only. I would rather keep it simple vs selectively hipifying cpu files. However, if we think this list will grow further, we can always fall back to hipify approach?

**Review by bddppq — APPROVED** [review]
Ok if there are only a few of such files I can live with these ifdefs :-)

**Pull request closed without merging**
