### PR TITLE
add numpy typing plugin to mypy config

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #92126
* #92931
* #90735
* #90734
* #90733
* __->__ #92930

This added the numpy typing plugin to mypy config so that we could
use it for DeviceMesh typing annotations

Please see https://github.com/pytorch/pytorch/pull/92931 about why we need this. For example, we are currently saving the DeviceMesh's mesh field as torch.Tensor, where when we do sth like:
```python
with FakeTensorMode():
    device_mesh = DeviceMesh("cuda", torch.arange(4))
```
It would throw error because FakeTensorMode or any TorchDispatchMode tracks every tensor creation and interactions. While DeviceMesh just want to save a nd-array to record the mesh topology, and would like to avoid the interaction with subsystems like FakeTensor, so we want to support saving `mesh` as numpy array instead.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
sure? Would be nice to know what this does

**Comment by wanchaol** [comment]
> sure? Would be nice to know what this does

Yeah thanks! Just updated the comment of the PR to include more concrete details. tl.dr is that we want DeviceMesh's mesh tensor field to avoid the interaction with our tensor subclass systems like FakeTensorMode.

**Comment by ezyang** [comment]
Saving device mesh as a numpy array... feels wrong. Tell me about why it wants to be a tensor/ndarray in the first place?

**Comment by wanchaol** [comment]
> Saving device mesh as a numpy array... feels wrong. Tell me about why it wants to be a tensor/ndarray in the first place?

Sure, the underlying rationale is that we want to use DeviceMesh to represent the cluster topology, where we could setup communicators base on the topology, it uses the mesh concept similar to other frameworks where it could possibly structure the devices into a n-d array, for example, we have two hosts and each host have four devices, we would like to save it as sth like
```
[[0, 1, 2, 3], 
 [4, 5, 6, 7]]
```
This represents the topology of the two hosts, and we want to know the shape/size on each dim of this n-d array easily, hence either torch.Tensor or numpy.array as the storage of the mesh works for this case. We were using torch.Tensor but later we realized it interacts with fake tensor or tracing (where we don't need to). So I would like to switch to use numpy array to avoid the subsystem interactions.

**Comment by ezyang** [comment]
cc @eellison 

But I feel like I would rather make a tensor subclass that denotes "don't fakify this ever"...

**Comment by eellison** [comment]
> But I feel like I would rather make a tensor subclass that denotes "don't fakify this ever"...

That works, and you can also do whatever non-module bookkeeping under a [disable_current_modes](https://github.com/pytorch/pytorch/blob/master/torch/utils/_python_dispatch.py#L87) context. This pattern is going to come up again, it does feel a bit weird to recommend numpy.

**Comment by ezyang** [comment]
I anti-recommend disable_current_modes. The subclass should be handled by FakeTensor and it shouldn't be necessary for the user to manually disable the mode.

**Comment by eellison** [comment]
> I anti-recommend disable_current_modes 

Why ? In general I think you'd prefer changes that don't require intrusive changes to other core classes

**Comment by wanchaol** [comment]
@ezyang @eellison for the tensor subclass approach or the disable mode approach, is it possible for user to do sth like the comment in the summary:

```python
with FakeTensorMode():
    device_mesh = DeviceMesh("cuda", torch.arange(4))
```
i.e. user create a plan tensor pass to FakeTensorMode and it will not be fakify by the mode?

**Comment by ezyang** [comment]
No, you would have to provide special factory functions or have the user turn on a separate mode that is "these are constants, don't fakeify them"

**Review by malfet — CHANGES_REQUESTED** [review]
Hmm, don't you need to add it to https://github.com/pytorch/pytorch/blob/master/.circleci/docker/requirements-ci.txt and https://github.com/pytorch/pytorch/blob/d9f0d148358eb2de69cbfd2a55546eee95732a95/.lintrunner.toml#L134 otherwise it will be a no-op?

**Comment by wanchaol** [comment]
> No, you would have to provide special factory functions or have the user turn on a separate mode that is "these are constants, don't fakeify them"

@ezyang I think that would be not ideal for the user, user need to use some special factory method and it might not be an intuitive UX. Another option maybe we can just make DeviceMesh a subclass of Tensor? would that make fake tensor and tracing happy?

**Comment by wanchaol** [comment]
> Hmm, don't you need to add it to https://github.com/pytorch/pytorch/blob/master/.circleci/docker/requirements-ci.txt and
> 
> https://github.com/pytorch/pytorch/blob/d9f0d148358eb2de69cbfd2a55546eee95732a95/.lintrunner.toml#L134
> 
> otherwise it will be a no-op?

@malfet it looks like lintrunner already have numpy in the [`init` command](https://github.com/pytorch/pytorch/blob/d9f0d148358eb2de69cbfd2a55546eee95732a95/.lintrunner.toml#L134), maybe I should only update requirements_ci.txt to uncomment numpy? https://github.com/pytorch/pytorch/blob/master/.circleci/docker/requirements-ci.txt#L109

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
> @malfet it looks like lintrunner already have numpy in the [`init` command](https://github.com/pytorch/pytorch/blob/d9f0d148358eb2de69cbfd2a55546eee95732a95/.lintrunner.toml#L134), maybe I should only update requirements_ci.txt to uncomment numpy? https://github.com/pytorch/pytorch/blob/master/.circleci/docker/requirements-ci.txt#L109


Sorry, I misunderstood where the plugin should me coming from. And CI preinstalls numpy, but from anaconda rather than PyPI, this is why it's commented out there

**Comment by ezyang** [comment]
> > No, you would have to provide special factory functions or have the user turn on a separate mode that is "these are constants, don't fakeify them"
> 
> 
> 
> @ezyang I think that would be not ideal for the user, user need to use some special factory method and it might not be an intuitive UX.

Is this not what you have done if you make people allocate numpy arrays?

> Another option maybe we can just make DeviceMesh a subclass of Tensor? would that make fake tensor and tracing happy?

Let's rewind a sec actually. In normal eager mode, there is no problem with fake tensor mode because people don't write code under fake tensor mode. So you can use regular tensor for mesh, no problem.

So the problem is when you trace through the model. If we can arrange the tracing process to not fakeify tensor computation that goes to the mesh, that's what we want. 

> edit: actually I think directly make DeviceMesh a tensor subclass also seems not gonna work, as we still need to pass the torch.Tensor to that tensor subclass.

Another possibility is to add a 'mesh' or 'const' device type, which is always small and OK to always materialize...

**Comment by wanchaol** [comment]
> Is this not what you have done if you make people allocate numpy arrays?

Yeah this make sense, let me think about how to make a custom factory method that provide a similar UX compare to numpy and Tensor. Regardless of the approach we are going to take, the numpy ndarray typing is still valuable as we want to accept both a n-d list directly (`i.e. [0, 1, 2, 3]`) or a tensor subclass instance/ndarray

> Let's rewind a sec actually. In normal eager mode, there is no problem with fake tensor mode because people don't write code under fake tensor mode. So you can use regular tensor for mesh, no problem.
> 
> So the problem is when you trace through the model. If we can arrange the tracing process to not fakeify tensor computation that goes to the mesh, that's what we want. 

Yep agreed that it's mostly tracing right now have issues. But I think most likely even eager mode would want the FakeTensorMode once FakeTensorMode supports deferred_init like torchdistx, as we would still want to lazy materialize the model (after tensor parallel), when the model is too large.

> 
> Another possibility is to add a 'mesh' or 'const' device type, which is always small and OK to always materialize...

Do you mean add a device type to core like `device=mesh` and inside the device type we always materialize the tensor? Yeah that would be good too if that avoids interaction with FakeTensor

**Pull request closed without merging**
