### PR TITLE
Remove noexecpt.patch workaround, it seems to be fixed upstream

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #106314
* __->__ #106318

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Is CI enough testing for this?

**Comment by ezyang** [comment]
I think so, the CI should use the new docker images

**Comment by ezyang** [comment]
obsoleted by https://github.com/pytorch/pytorch/pull/106312

**Pull request closed without merging**
