### PR TITLE
[Modes] remove inner constructor kwarg

### PR DESCRIPTION
**Pull request by samdow**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #83927
* __->__ #83925

### CODE REVIEW

**Comment by ezyang** [comment]
Thanks for redoing. If you remove the inner api you will run into some trouble because dynamo is calling this api directly too, but even if you fix dynamo you can't update the pin because of regressions from dynamo master. Cc @anijain2305

**Comment by samdow** [comment]
> If you remove the inner api you will run into some trouble because dynamo is calling this api directly too, but even if you fix dynamo you can't update the pin because of regressions from dynamo master

To check, are you referring to anywhere else except for [what was changed here](https://github.com/pytorch/torchdynamo/commit/5e7eae593e796d9d86bb2d7603aa1afb45dc6cc1), which is what's causing all the current failures in CI? Realize that this is still blocked on updating the dynamo pin, but I wanted to see if there were any other uses of inner that I should change while we're in here

**Comment by ezyang** [comment]
Nope, that PR should suffice. The pin update for pytorch is at https://github.com/pytorch/pytorch/pull/83829

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
I guess even after this lands, there are some bits from https://github.com/pytorch/pytorch/pull/83496/files we still want

**Comment by samdow** [comment]
> there are some bits from https://github.com/pytorch/pytorch/pull/83496/files we still want

Assuming you mean `enable_torch_dispatch_mode(FakeTensorMode(...))` -> `with FakeTensorMode()` in the tests. Happy to change that to match match #83496 for fewer merge conflicts

**Comment by ezyang** [comment]
it's fine, the merge conflicts are very gentle  :)

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
