### PR TITLE
Added call_hasattr to the TensorVariable class

### PR DESCRIPTION
**Pull request by Lazarus42**
Attempt at fixing issue #133253

The TensorVariable class did not have a call_hasattr method to check if a tensor variable had an attribute. 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Comment by ezyang** [comment]
This doesn't look quite right. If the tensor has attr on instance rather than class you will incorrectly report false?

**Comment by Lazarus42** [comment]
Right. I changed it to check on the instance rather than the class level. How does this look?

**Comment by Lazarus42** [comment]
@ezyang I changed the handling to check the proxy which works for the two test cases I uploaded. The tests check the case where the attribute is on instance as you mentioned and when the attribute belongs to the class.

**Comment by Lazarus42** [comment]
@ezyang I think I fixed the issue. Before, as you pointed out, if a tensor had an attribute on instance but not on class it failed. This passes the tests that I included in the recent commit. Do you see other issues?

**Review by ezyang — CHANGES_REQUESTED** [review]
This isn't quite right either. The problem is that exceptions thrown in Dynamo can potentially be due to internal errors in Dynamo, etc, but you unconditionally catch all of them and suppress them, even if Dynamo is saying "I don't know how to trace this, I don't know what the value is"

**Pull request closed without merging**
