### PR TITLE
Don't run test_torch in test_cuda and test_sparse

### PR DESCRIPTION
**Pull request by yf225**
Sandcastle doesn't run tests with `__name__ == '__main__'`, and we need a different way to skip `TestTorch` tests in `test_cuda` and `test_sparse`.

### CODE REVIEW

**Comment by SsnL** [comment]
This should work as long as `unittest.TestCase` is a new-style class, which I believe to be true in py2.7 and py3+.

**Comment by yf225** [comment]
CI seems to give:
```
20:15:36 Running test_cuda ...
20:15:38 Traceback (most recent call last):
20:15:38   File "test_cuda.py", line 1914, in <module>
20:15:38     TestTorch.__bases__ = (object, )
20:15:38 TypeError: __bases__ assignment: 'object' deallocator differs from 'TestCase'
20:15:38 Traceback (most recent call last):
20:15:38   File "test/run_test.py", line 345, in <module>
20:15:38     main()
20:15:38   File "test/run_test.py", line 337, in main
20:15:38     raise RuntimeError(message)
20:15:38 RuntimeError: test_cuda failed!
```
@SsnL How should we fix it?

**Comment by SsnL** [comment]
this doesn't seem to work :(. i'll find another way. 
the worst case we can create a wrapper for TestTorch.

**Comment by ezyang** [comment]
Can we just refactor the test files into some files that define utility stuff, and others which actually use it?

**Comment by weiyangfb** [comment]
@yf225 needs a rebase :( what's the decision on this now?

**Comment by yf225** [comment]
@SsnL Wanna take over this? :)

**Comment by SsnL** [comment]
Sure I’ll do th refactoring.

**Comment by SsnL** [comment]
this doesn't seem to work. we should just refactor the tests. feel free to reopen if needed

**Pull request closed without merging**
