### PR TITLE
[ONNX] Update embedding export wrt padding_idx

### PR DESCRIPTION
**Pull request by BowenBao**
To be in-sync with #53447

### CODE REVIEW

**Comment by BowenBao** [comment]
cc @spandantiwari @malfet

**Review by malfet — APPROVED** [review]

**Comment by BowenBao** [comment]
I'll take a look at the conflict files

**Comment by malfet** [comment]
@BowenBao I can resolve the conflict (had to revert #53053 to restore CI sanity)

**Comment by malfet** [comment]
Oh, thank you for the update!

**Pull request closed without merging**
