### PR TITLE
Make sure to properly pull the right submodule in BC test

### PR DESCRIPTION
**Pull request by albanD**
To unblock https://github.com/pytorch/pytorch/pull/93219

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Review by malfet — APPROVED** [review]
Wow, we hit it again?

**Comment by albanD** [comment]
Yes for the fmt update: https://github.com/pytorch/pytorch/pull/93219
We might as well fix it :D

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
@malfet Doesn't seem like it fixed the issue: https://github.com/pytorch/pytorch/actions/runs/4106599706/jobs/7085290447

**Pull request closed without merging**
