### PR TITLE
Don't throw tf32 warning if no nodes in graph are matmuls + fp32 + cuda

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #94572
* __->__ #94561
* #94500

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Review by eellison — APPROVED** [review]
lgtm

**Comment by eellison** [comment]
actually - doesn't it speed up convs too ?

**Review by malfet — APPROVED** [review]

**Comment by Chillee** [comment]
@eellison convs use tf32 by default already, just not matmuls.

**Pull request closed without merging**
