### PR TITLE
[sparse] Add `torch._C._sparse` namespace

### PR DESCRIPTION
**Pull request by IvanYashchuk**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #68084
* #68083
* __->__ #68006
* #68007

This PR adds `python_module: sparse` to `native_function.yaml`.
These functions would appear in `torch._C._sparse` namespace instead of
just `torch`.

cc @nikitaved @pearu @cpuhrsch @IvanYashchuk

Differential Revision: [D32291848](https://our.internmc.facebook.com/intern/diff/D32291848)

### CODE REVIEW

**Review by mruberry — APPROVED** [review]

**Review by cpuhrsch — APPROVED** [review]

**Comment by cpuhrsch** [comment]
@cpuhrsch has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32291730).

**Comment by cpuhrsch** [comment]
@cpuhrsch has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32291730).

**Comment by cpuhrsch** [comment]
@cpuhrsch has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32291848).

**Comment by cpuhrsch** [comment]
@cpuhrsch has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32291848).

**Comment by IvanYashchuk** [comment]
https://github.com/pytorch/pytorch/pull/68672 was merged instead of this PR.

**Pull request closed without merging**
