### PR TITLE
Trace `pytree` calls inside `vmap` implementation.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #109433
* __->__ #109107
* #108533
* #109201

This PR fixes the `expectedFailure` introduced in the previous PR.

**Problem:** container variables, such as `ConstDictVariable`, aren't registered nodes anymore. But, we have to process
the tensors inside them, anyway.

**Solution:** wrap the pytree functions in a `UserFunctionVariable`, and call it. This should inline the given pytree function, and return the expected processed arguments.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by ezyang** [comment]
@zou3519 can I defer this to you?

One thing that occurs to me is that maybe the easiest implementation of this would be to Dynamo through a pytree call that is mapping over Tensor *internally*

**Comment by ysiraichi** [comment]
@ezyang let me know if this is what you meant.

**Comment by ezyang** [comment]
Yes!

**Comment by zou3519** [comment]
Yeah I'll take a look soon

**Review by zou3519 — APPROVED** [review]
very cool!

**Comment by zou3519** [comment]
Test failures look real, though

**Pull request closed without merging**
