### PR TITLE
[ROCm][CI] upgrade CI and manywheel docker images to ROCm 6.2.4

### PR DESCRIPTION
**Pull request by jithunnair-amd**
Fixes issue of long docker build times in PRs which trigger the docker build in regular PyTorch build jobs eg. https://github.com/pytorch/pytorch/actions/runs/11751388838/job/32828886198. These docker builds take a long time for ROCm6.2 because:
1. They are run on less capable machines (`c5.2xlarge`) instead of the beefier ones on which [docker-build workflows](https://github.com/pytorch/pytorch/blob/924c1fe3f304aa599b823fb549c35b7809f61086/.github/workflows/docker-builds.yml#L50) run (`c5.12xlarge`)
2. ROCm6.2 docker builds enabled building of MIOpen from source, which runs into [timeout of 90mins](https://github.com/pytorch/test-infra/blob/9abd4d95bb0b86d78d1929abcd6046d07e8a5864/.github/actions/calculate-docker-image/action.yml#L171): https://github.com/pytorch/pytorch/actions/runs/11751388838/job/32828886198#step:7:160

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@huydhn While this might fix the issue of timeouts for ROCm docker builds, I feel like we have a logical discrepancy in our workflows vis-a-vis docker builds:
* The docker-builds.yml specifies a [timeout of 4hrs](https://github.com/pytorch/pytorch/blob/1fd4757fdccdd4755b9815045134453b5c7f8e25/.github/workflows/docker-builds.yml#L46), *and* runs on beefier machines `c5.12xlarge`
* If any PR tries to update anything that requires a new docker image tag (which doesn't already exist), it triggers `docker-builds` workflow as well as `pull` workflows.
* However, the `pull` workflow jobs require the new docker image that would be generated and pushed to ECR docker registery by the `docker-build` workflow
* Since they are kicked off at the same time, the `pull` workflow ends up deciding to build the docker image itself, since it's not yet available, and runs the docker image build on a weaker `c5.2xlarge` machine with a smaller timeout of 1.5hrs (90mins) as well
* This obviously doesn't go well for docker build jobs that need more time

Is there a way to make the PyTorch build job depend on the docker-build job to finish?

**Comment by huydhn** [comment]
> Is there a way to make the PyTorch build job depend on the docker-build job to finish?
 
The way I usually do is to ignore the build jobs at first and just let the docker build job to finish.  Once done, it will make the new image available on ECR.  Then, I will rerun the build jobs.  Because the new image is now available, they won't re-build the image again and should pull from ECR instead.  Let me know if you see a different behavior here.

**Comment by jithunnair-amd** [comment]
> > Is there a way to make the PyTorch build job depend on the docker-build job to finish?
> 
> The way I usually do is to ignore the build jobs at first and just let the docker build job to finish. Once done, it will make the new image available on ECR. Then, I will rerun the build jobs. Because the new image is now available, they won't re-build the image again and should pull from ECR instead. Let me know if you see a different behavior here.

Yes, I realized I could have done that here too, but I decided to take the opportunity to improve the ROCm docker build times anyway. It's just that it's a manual step, the reasoning for which might not be obvious to most devs.

**Comment by jithunnair-amd** [comment]
Only shard 6 of 6 failed in the `rocm` workflow for this test: `test_linalg.py::TestLinalgCUDA::test_matmul_small_brute_force_tunableop_cuda_float16`, which is [seen in 6.2.0 runs](https://hud.pytorch.org/failure?name=rocm%20%2F%20linux-focal-rocm6.2-py3.10%20%2F%20test%20(default%2C%206%2C%206%2C%20linux.rocm.gpu.2)&jobName=linux-focal-rocm6.2-py3.10%20%2F%20test%20(default%2C%206%2C%206%2C%20linux.rocm.gpu.2)&failureCaptures=%5B%22test_linalg.py%3A%3ATestLinalgCUDA%3A%3Atest_matmul_small_brute_force_tunableop_cuda_float16%22%5D) as well, so it's not a 6.2.4-specific issue.

**Comment by jithunnair-amd** [comment]
@jeffdaily `rocm`, `inductor-rocm` and `periodic` workflows ran successfully for ROCm, except that `test_linalg.py::TestLinalgCUDA::test_matmul_small_brute_force_tunableop_cuda_float16` test which is flaky. Can you please approve and force merge the PR?

**Comment by jithunnair-amd** [comment]
> @jeffdaily
> 
> * https://hud.pytorch.org/pr/140851#docker-builds shows ROCm CI base docker images built in 53m
> * https://hud.pytorch.org/pr/140851#build%20manywheel%20docker%20images shows ROCm manywheel docker images built in 1.3h or less
> * `rocm`, `inductor-rocm` and `periodic` workflows ran successfully for ROCm, except that `test_linalg.py::TestLinalgCUDA::test_matmul_small_brute_force_tunableop_cuda_float16` test which is flaky.
> 
> ~Can you please approve and force merge the PR?~ Please hold on, I need to move the manylinux images to build with 6.2.4 as well.

Updated the manylinux images to 6.2.4. @jeffdaily please review and merge

**Review by jeffdaily — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@huydhn Need ECR tag `libtorch-cxx11-builder-rocm6.2.4` to be created please

**Comment by jithunnair-amd** [comment]
> @huydhn Need ECR tag `libtorch-cxx11-builder-rocm6.2.4` to be created please

Libtorch ECR tag creation is having some issues. But I also see that the libtorch ECR images aren't really used anywhere currently: https://github.com/search?q=repo%3Apytorch%2Fpytorch%20libtorch-cxx11-builder-rocm&type=code

And the libtorch nightly builds jobs use the docker images from dockerhub: https://github.com/pytorch/pytorch/blob/a8ab6b0938ed1788b0cad8982bcafaeaa5dea77d/.github/workflows/generated-linux-binary-libtorch-pre-cxx11-nightly.yml#L449

Hence, in my understanding, merging this PR without the ECR tag being ready shouldn't break anything except the libtorch docker build jobs in any PRs.

**Pull request closed without merging**
