### PR TITLE
fix(docs): `torch.add` and `torch.mul`

### LINKED ISSUE #39425: `torch.add`  documentation refers `value` as an argument.
#### Link

https://pytorch.org/docs/stable/torch.html#torch.add

#### API

`torch.add`

#### Issue

In the "Parameters" section, there is an input `value` , but it is not in the signature, and it is not accepted by the function. It should be `other`

Running code :

~~~python
a = torch.randn(4)
torch.add(a, other=20, value=1)
~~~

gives exception 

~~~python
TypeError: add() got an unexpected keyword argument 'value'
~~~

#### **System information**

- OS: MacOS Mojave 10.14
- PyTorch version: 1.7.0.dev20200819+cpu
- Python version: 3.8.2

### PR DESCRIPTION
**Pull request by jeffydc**
fixes https://github.com/pytorch/pytorch/issues/39425
https://11813267-65600975-gh.circle-artifacts.com/0/docs/generated/torch.add.html
https://11813267-65600975-gh.circle-artifacts.com/0/docs/generated/torch.mul.html

### CODE REVIEW

**Comment by zou3519** [comment]
torch.mul doc looks wrong. From your link https://11813267-65600975-gh.circle-artifacts.com/0/docs/generated/torch.mul.html :
image

**Comment by zou3519** [comment]
That looks like a pre-existing problem though. @ydcjeff I'm happy to merge this as-is, but if you're interested in fixing this in this PR, please let me know :)

**Review by zou3519 — APPROVED** [review]
lgtm

**Comment by zou3519** [comment]
@ydcjeff could you rebase this PR when you get a chance please? It's a bit too stale for merge, my apologies for not merging it earlier. (I can also force-push to your branch to do the rebase if you'd like).

**Comment by ydcjeff** [comment]
@zou3519 Yes, please help rebase to my branch

**Comment by ydcjeff** [comment]
@zou3519 Any chance to merge?
Thank you!

**Comment by zou3519** [comment]
> @zou3519 Any chance to merge?
> Thank you!

Thanks for the ping! Let me rebase again, just trying to get tests green

**Pull request closed without merging**
