### PR TITLE
[qunat][fx] Remove "additional_quant_pattern" key from prepare_custom_config_dict

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #75521
* #75520
* #75469
* #75389
* #75388
* #75387
* __->__ #75386
* #75378

Summary:
This is now replaced with backend_config_dict, we don't want to expose the implementation detail to
users. We'll have docs for backend_config_dict later

Test Plan:
python test/test_quantization.py TestQuantizeFx
python test/test_quantization.py TestQuantizeFxOps

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D35451957](https://our.internmc.facebook.com/intern/diff/D35451957)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35451957).

**Comment by vkuzo** [comment]
since this is BC breaking, do you want to fill out the PR summary now to direct users what to do?  It will likely take less time now compared to doing it before the release notes.  Same for the other BC breaking PRs in this stack.

**Comment by jerryzh168** [comment]
> since this is BC breaking, do you want to fill out the PR summary now to direct users what to do? It will likely take less time now compared to doing it before the release notes. Same for the other BC breaking PRs in this stack.

yeah I plan to do it once for all the bc-breaking changes here, and we'll need to rely on the docs for backend_config_dict since it's replacing these apis.

**Comment by vkuzo** [comment]
> > since this is BC breaking, do you want to fill out the PR summary now to direct users what to do? It will likely take less time now compared to doing it before the release notes. Same for the other BC breaking PRs in this stack.
> 
> yeah I plan to do it once for all the bc-breaking changes here, and we'll need to rely on the docs for backend_config_dict since it's replacing these apis. it's hard to write bc-breaking notes for individual ones I think, some of them doesn't really have a immediate replacement, like this PR. it's just all of these apis will be replaced by the backend_config_dict api

I understand what you mean, but what do you think is the plan to make these PRs fit the release guidelines?  If I remember correctly, "bc-breaking" means "we need to explain in detail what is happening and what users need to do".

**Comment by jerryzh168** [comment]
> I thought you had to pick one, either a PR is bc-breaking and we write it up as such, or it's not bc breaking so we don't have the tags, etc.

My initial plan is to have one bc-breaking notes for everything here, a little bit later after we have backend_config_dict mostly ready.

I'm OK with not marking this as bc-breaking as well, I think we didn't really talk about these apis anywhere before, what do you think?

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35451957).

**Comment by vkuzo** [comment]
> My initial plan is to have one bc-breaking notes for everything here, a little bit later after we have backend_config_dict mostly ready.

from what I understand, the release notes have a strict rule that if a PR is BC breaking, it has to have the writeup.  I understand what you are saying, it just feels like it's not following the release rules.  I think marking this as non BC breaking (since this is for a prototype API and it's not something which was documented) makes sense.

**Comment by vkuzo** [comment]
maybe we can update the PR title too?

**Review by vkuzo — APPROVED** [review]

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35451957).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35451957).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35451957).

**Pull request closed without merging**
