### PR TITLE
Implement logsumexp (fixes #2591)

### LINKED ISSUE #2591: Feature request: logsumexp
The numerically stable version of `logsumexp` is simple but often useful. Thoughts on including this in PyTorch?

My thought is that it'd follow a call signature(s) that's similar to that of `sum`, but `logsumexp` wouldn't have the `out` keyword, and it'd also use the NumPy-consistent `keepdims` keyword instead of `sum`'s `keepdim` keyword. So

```
def logsumexp(inputs, dim=None, keepdims=False):
    ...
```

### PR DESCRIPTION
**Pull request by t-vi**
Maybe this is useful.

### CODE REVIEW

**Review by ssnl — COMMENTED** [review]
Thanks! Can you add `inf` cases in the test? This looks great otherwise.

**Review by ssnl — APPROVED** [review]
Good to merge if test passes

**Review by soumith — APPROVED** [review]
simon reviewed, so accepting

**Review by ssnl — DISMISSED** [review]
Actually could you write a custom backward? The autograd backward isn't very efficient. The formula should just be `exp(input) / output` for 1d case.

**Comment by ezyang** [comment]
Windows error seems legit, if a bit strange:

```
22:53:58 ======================================================================
22:53:58 ERROR: test_logsumexp (test_autograd.TestAutograd)
22:53:58 ----------------------------------------------------------------------
22:53:58 Traceback (most recent call last):
22:53:58   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test\test\test_autograd.py", line 3290, in do_test
22:53:58     check(name)
22:53:58   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test\test\test_autograd.py", line 3225, in check
22:53:58     output_variable, (self_variable,) + args_variable)
22:53:58   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test\test\test_autograd.py", line 3151, in run_grad_and_gradgrad_checks
22:53:58     test_case.assertTrue(gradcheck(apply_method, input_variables, eps=1e-6, atol=PRECISION))
22:53:58   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test\test\torch\autograd\gradcheck.py", line 182, in gradcheck
22:53:58     analytical, reentrant, correct_grad_sizes = get_analytical_jacobian(tupled_inputs, o)
22:53:58   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test\test\torch\autograd\gradcheck.py", line 94, in get_analytical_jacobian
22:53:58     jacobian = make_jacobian(input, output.numel())
22:53:58 RuntimeError: Attempted to cast a Tensor to a Variable, but the dynamic type of the value is not Variable.
22:53:58 
```

**Comment by ezyang** [comment]
I looked at the code and I don't see why this test would have triggered only on Windows. Looks like it will need debugging. Possibly an error elsewhere in PyTorch that is being exercised here.

**Comment by t-vi** [comment]
@ezyang Thank you for looking into that. Interestingly, I got failures on Linux (gcc 7.3) as well when I wanted to test the backward - incidentally it didn't yesterday before I did the backward. It turned out that I had forgotten to specify `variants: function` - given that the TestAutograd.test_logsumexp now runs fine, maybe that has to do with it.

**Comment by SsnL** [comment]
This need rebasing

**Comment by t-vi** [comment]
@ezyang I think now the PR has two spurious failures instead of one.

**Comment by t-vi** [comment]
Thank you! There seems to be a different failure now, but I'm afraid I'm not sure what is going on.

**Comment by zou3519** [comment]
thanks @t-vi for the contribution!

**Comment by vadimkantorov** [comment]
@t-vi @zou3519 The doc-string isn't shown in docs online: empty https://pytorch.org/docs/master/search.html?q=logsumexp&check_keywords=yes&area=default

Maybe `autofunction` is missing

**Pull request merged**
