### PR TITLE
[inductor] adjust sliceView limits

### PR DESCRIPTION
**Pull request by ngimel**
Fixes #ISSUE_NUMBER

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]

**Comment by ngimel** [comment]
@pytorcbot rebase -b main

**Pull request closed without merging**
