### PR TITLE
[ROCm] update Magma for 4.3 release

### PR DESCRIPTION
**Pull request by jaglinux**
Upstream magma fixes the cholesky issues.
Refer https://bitbucket.org/icl/magma/issues/48/parameter-4-was-incorrect-on-entry-to

Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>

Fixes #{issue number}

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
Kicked off a manual CI run to test with the new docker image: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.2-py3.6-trigger/20435/

**Review by jithunnair-amd — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@jaglinux I'm not sure why, but it looks like the empty commit didn't kick off the ROCm4.3 docker build CircleCI job. Maybe just close this PR in favour of another one (might need a different branch for github to treat it as a different PR)?

**Comment by jaglinux** [comment]
@jithunnair-amd plz refer https://github.com/pytorch/pytorch/pull/65203

**Comment by jithunnair-amd** [comment]
Closing in favour of #65203 to get ROCm4.3.1 CI to rebuild

**Pull request closed without merging**
