### PR TITLE
Adding documentation an diagram on code base

### PR DESCRIPTION
**Pull request by davidradl**
Fixes #104962

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @gujinghui @PenghuiCheng @jianyuh @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @mcarilli @ptrblck @leslie-fang-intel @EikanWang @voznesenskym @penguinwu @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @ngimel @anijain2305

### CODE REVIEW

**Comment by davidradl** [comment]
@malfet I have created a new pr for this change - I hopefully have addressed your feedback. I added some comments to the top of the ATen readme around the code base as well.

**Review by albanD — COMMENTED** [review]
I'll let @subramen review the content but the image doesn't seem to render properly?

**Comment by davidradl** [comment]
> I'll let @subramen review the content but the image doesn't seem to render properly?

@albanD it looked good to me locally - how are you seeing it not being rendered correctly?

**Comment by albanD** [comment]
You can see the rendered version of the .md file you updated: https://github.com/pytorch/pytorch/blob/ca42d426ef4e2015fb19f0c2350db6dcf96d5560/CONTRIBUTING.md#codebase-structure

**Comment by davidradl** [comment]
Looks like many extra merge commit have got into this pr - I will review

**Pull request closed without merging**
