### PR TITLE
[CUBLAS][CUDA GRAPHS] (re-re-open of #83461) Explicitly set the workspace for cuBLAS handles

### PR DESCRIPTION
**Pull request by eqy**
Now includes @dagitses 's optimizations and fixes for teardown

CC @ngimel @ptrblck

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by seemethere** [comment]
@eqy We've found that this PR is causing a memory leak for CUDA operations, as found by @xuzhao9.

Link to failure logs: https://app.circleci.com/pipelines/github/pytorch/benchmark/5273/workflows/8792c508-526d-4b42-af90-0e76ec818d64/jobs/5423

We're going to go ahead and revert this PR

**Comment by xuzhao9** [comment]
Error log link: https://app.circleci.com/pipelines/github/pytorch/benchmark/5273/workflows/8792c508-526d-4b42-af90-0e76ec818d64/jobs/5423

We measure `torch.cuda.memory_allocated()` before and after the model run, and they should both be zero (https://github.com/pytorch/benchmark/blob/main/torchbenchmark/__init__.py#L528). This PR breaks this test because after we deleted the model and garbage collection, still `torch.cuda.memory_allocated()` returns non-zero. These memory will be not available until the process exits.

**Comment by eqy** [comment]
@xuzhao9 
This is expected as we have effectively moved an allocation managed by cuBLAS to one that is managed by PyTorch, in both cases the memory is held until the process exits because it's not easy to anticipate when the last cuBLAS kernel will be run. In order to measure memory before and after the model run, `torch._C._cuda_clearCublasWorkspaces()` should be called to get a proper result.

**Comment by seemethere** [comment]
> @xuzhao9 @seemethere This is expected as we have effectively moved an allocation managed by cuBLAS to one that is managed by PyTorch, in both cases the memory is held until the process exits because it's not easy to anticipate when the last cuBLAS kernel will be run. In order to measure memory before and after the model run, `torch._C._cuda_clearCublasWorkspaces()` should be called to get a proper result.

If that is the case then we should modify tests to also use that. If we're sporadically seeing OOM issues for CUDA then it points to an issue that we should address.

**Comment by seemethere** [comment]
> > @xuzhao9 @seemethere This is expected as we have effectively moved an allocation managed by cuBLAS to one that is managed by PyTorch, in both cases the memory is held until the process exits because it's not easy to anticipate when the last cuBLAS kernel will be run. In order to measure memory before and after the model run, `torch._C._cuda_clearCublasWorkspaces()` should be called to get a proper result.
> 
> If that is the case then we should modify tests to also use that. If we're sporadically seeing OOM issues for CUDA then it points to an issue that we should address.

As well, we're trying to clean up the branch for the branch cut for 1.13 and having what appears to be a memory leak is too high of a risk to have in the release branch.

**Comment by eqy** [comment]
See also: https://github.com/pytorch/benchmark/pull/1226

**Pull request closed without merging**
