### PR TITLE
Upgrade nightly wheels to rocm6.2 - 1 of 2 (docker images)

### LINKED ISSUE #132570: Support for ROCm 6.2
### 🚀 The feature, motivation and pitch

With the [release](https://rocm.docs.amd.com/en/latest/about/release-notes.html) of ROCm 6.2, it is suitable for PyTorch to release a `.whl`  to accommodate the latest ROCm version. The release notes discuss improvements specifically for some PyTorch utilities, and it would be nice to take advantage of these as soon as possible.

Specifically, there needs to be a `.whl` pushed to `download.pytorch.org/whl/rocm6.2` that is built for ROCm 6.2.

### Alternatives

_No response_

### Additional context

_No response_

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### PR DESCRIPTION
**Pull request by jithunnair-amd**
Fixes https://github.com/pytorch/pytorch/issues/132570

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by atalman — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
> @jithunnair-amd can we include triton here too?
> 
> https://github.com/pytorch/pytorch/blob/947a446be4360994da3b11ef01a8bdfbfe812f49/.github/workflows/build-triton-wheel.yml#L42

Yes, of course! Sorry for forgetting (again!)

**Comment by jithunnair-amd** [comment]
> > @jithunnair-amd can we include triton here too?
> > https://github.com/pytorch/pytorch/blob/947a446be4360994da3b11ef01a8bdfbfe812f49/.github/workflows/build-triton-wheel.yml#L42
> 
> Yes, of course! Sorry for forgetting (again!)

@jataylo Turns out I didn't forget updating it, I just forgot that it's part of the second PR https://github.com/pytorch/pytorch/pull/133238 since it first needs the manylinux image to be pushed out.

**Pull request closed without merging**
