### PR TITLE
Don't auto request review for reopened PRs

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #132807
* __->__ #132681

This will clobber previous approves.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
I think this is done on purpose to re-request an accept for OSS contributors

**Comment by ezyang** [comment]
@albanD uhhhhh well I mean, I'm the dude who added the auto request review integration, and it was definitely not because that, it's because the default code had auto request review on reopened lol

**Review by albanD — APPROVED** [review]
Sounds good to me then!

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
