### PR TITLE
[Easy] Apply black to format _spmd files

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #97577
* #97416
* __->__ #97534
* #97533

No real changes. Format code to prepare for the PR on top.

Differential Revision: [D44376380](https://our.internmc.facebook.com/intern/diff/D44376380)

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44376380).

**Review by mrshenli — COMMENTED** [review]
Test failure is irrelevant:

```
ERROR: An error occurred during the fetch of repository 'rules_python':
   Traceback (most recent call last):
	File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/fdf6d09bf4b4f04a71e2a7dfceb40620/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz] to /var/lib/jenkins/.cache/bazel/_bazel_jenkins/fdf6d09bf4b4f04a71e2a7dfceb40620/external/rules_python/temp4146548182261617441/rules_python-0.0.1.tar.gz: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/var/lib/jenkins/.cache/bazel/_bazel_jenkins/fdf6d09bf4b4f04a71e2a7dfceb40620/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz] 
```

**Comment by mrshenli** [comment]
more irrelevant errors:

```
2023-03-24T21:02:55.8677053Z =================================== FAILURES ===================================
2023-03-24T21:02:55.8677408Z ______________________ TestCudaComm.test_memory_snapshot _______________________
2023-03-24T21:02:55.8677729Z Traceback (most recent call last):
2023-03-24T21:02:55.8678097Z   File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
2023-03-24T21:02:55.8678496Z     h.request(req.get_method(), req.selector, req.data, headers,
2023-03-24T21:02:55.8678877Z   File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1282, in request
2023-03-24T21:02:55.8679276Z     self._send_request(method, url, body, headers, encode_chunked)
2023-03-24T21:02:55.8679679Z   File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1328, in _send_request
2023-03-24T21:02:55.8680068Z     self.endheaders(body, encode_chunked=encode_chunked)
2023-03-24T21:02:55.8680447Z   File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1277, in endheaders
2023-03-24T21:02:55.8680847Z     self._send_output(message_body, encode_chunked=encode_chunked)
2023-03-24T21:02:55.8681253Z   File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1037, in _send_output
2023-03-24T21:02:55.8681567Z     self.send(msg)
2023-03-24T21:02:55.8681896Z   File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 975, in send
2023-03-24T21:02:55.8682214Z     self.connect()
2023-03-24T21:02:55.8682528Z   File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1454, in connect
2023-03-24T21:02:55.8682908Z     self.sock = self._context.wrap_socket(self.sock,
2023-03-24T21:02:55.8683282Z   File "/opt/conda/envs/py_3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
2023-03-24T21:02:55.8683632Z     return self.sslsocket_class._create(
2023-03-24T21:02:55.8683970Z   File "/opt/conda/envs/py_3.10/lib/python3.10/ssl.py", line 1071, in _create
2023-03-24T21:02:55.8684290Z     self.do_handshake()
2023-03-24T21:02:55.8684623Z   File "/opt/conda/envs/py_3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
2023-03-24T21:02:55.8684942Z     self._sslobj.do_handshake()
2023-03-24T21:02:55.8685456Z ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)
```

**Pull request closed without merging**
