### PR TITLE
Support Optional typehint without graph breaking

### PR DESCRIPTION
**Pull request by nakulcr7**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108970

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by nakulcr7** [comment]
Meant to be a partial fix for #108697

@anijain2305 even with supporting the `Optional` type, when I run `python benchmarks/dynamo/torchbench.py --bfloat16 --accuracy --inference --device cuda  --export-aot-inductor  --only cm3leon_generate`, I get the following error that's possibly because of the `if` clause at https://fburl.com/tjyo3thn.

```
torch._dynamo.exc.UserError: Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow
```

**Review by anijain2305 — APPROVED** [review]

**Comment by anijain2305** [comment]
> Meant to be a partial fix for #108697
> 
> @anijain2305 even with supporting the `Optional` type, when I run `python benchmarks/dynamo/torchbench.py --bfloat16 --accuracy --inference --device cuda --export-aot-inductor --only cm3leon_generate`, I get the following error that's possibly because of the `if` clause at https://fburl.com/tjyo3thn.
> 
> ```
> torch._dynamo.exc.UserError: Dynamic control flow is not supported at the moment. Please use functorch.experimental.control_flow.cond to explicitly capture the control flow
> ```

Thats fine. This PR is good.

**Pull request closed without merging**
