### PR TITLE
Delete Buck1 as it is no longer supported

### PR DESCRIPTION
**Pull request by mcr229**
Buck1 is no longer supported in favor of buck2. This CI tests the old buck1 flow, however it is difficult to maintain especially since buck1 doesn't support aarch64 mac.

I am suggesting that this CI be deprecated until a decision on buck2 is made, and buck2 support is added. As of now, there seems to be no push towards adding buck2 support.

### CODE REVIEW

**Comment by huydhn** [comment]
Just want to call out this from a recent comment from @malfet about this exact job https://docs.google.com/document/d/1laFSxVwLqTGitATWjMM2MDjJp9IukezQxTAB8N5aEKU/edit?disco=AAABXDl-hNg.  So if we can get the approval from Edge team, it would make sense to clean this up.

On the internal releng side, I have seen this catch a mobile build failure w.r.t caffe2 clean up that @r-barnes have been doing recently, https://github.com/pytorch/pytorch/actions/runs/11589761715/job/32265949532.  But that's the only case AFAIK.  I assume that caffe2 clean up is almost done (cc @r-barnes), so I think it's ok to clean this up (The job doesn't do a good job catching issue in OSS anyway as it runs only periodically)

**Review by malfet — CHANGES_REQUESTED** [review]
Please fix lint (i.e. your current PR breaks all periodic workflow by leaving the reference to `_build-build-test.yml` that you are deleting. Otherwise, I'm ok with the change (cc: @iseeyuan )

I.e. this must be deleted:
https://github.com/pytorch/pytorch/blob/1127c8259296235b164087bfb2442dcb6224fb2b/.github/workflows/periodic.yml#L166-L175

**Comment by mcr229** [comment]
> PR



> Just want to call out this from a recent comment from @malfet about this exact job https://docs.google.com/document/d/1laFSxVwLqTGitATWjMM2MDjJp9IukezQxTAB8N5aEKU/edit?disco=AAABXDl-hNg. So if we can get the approval from Edge team, it would make sense to clean this up.
> 
> On the internal releng side, I have seen this catch a mobile build failure w.r.t caffe2 clean up that @r-barnes have been doing recently, https://github.com/pytorch/pytorch/actions/runs/11589761715/job/32265949532 from #139217. But that's the only case AFAIK. I assume that caffe2 clean up is almost done (cc @r-barnes), so I think it's ok to clean this up (The job doesn't do a good job catching issue in OSS anyway as it runs only periodically)

Thinks for the releng context here huy, the issue caught in that job (wrong header path) feels like it should be caught by another CI, so I'm surprised if the buck build test is the only CI that caught it. For Internal, I would imagine that internal buck builds would catch this issue as well?

**Comment by huydhn** [comment]
> For Internal, I would imagine that internal buck builds would catch this issue as well? 

Yeah, the build failure was caught internally.  No damage done :)

**Review by huydhn — APPROVED** [review]
LGTM!

**Pull request closed without merging**
