### PR TITLE
[reland][quant] QuantizedCUDA implementation (#36936)

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#37081 [reland][quant] QuantizedCUDA implementation (#36936)**

Summary:
Closes https://github.com/pytorch/pytorch/issues/30813

Relanding of https://github.com/pytorch/pytorch/pull/35463

1. Tensor quantization logic(quantize_*) is moved to the aten/native/quantized. Previously all logic for tensor quantization lived in the aten/quantized/Quantizer.cpp file, and started to become complicated and hard to read. This problem should be addressed in refactoring PR. Still, I reworked this partially because I had to add tensor quantization logic for CUDA, and it was native to move everything to the aten/native/quantized.
2. Requirements to run CUDA_tensor_apply* was eased to process any tenser that lives on the CUDA device(QuantizedCUDA included).
3. All quantized data types now have a default constructor. NVCC refuses to compile any gpu_kernel or CUDA_tensor_apply* without them.
4. Minor changes in many files to register QuantizedCUDA backend.
5. test_quantized_tensor is extended to process QuantizedCUDA backend where possible.

Differential Revision: [D21206694](https://our.internmc.facebook.com/intern/diff/D21206694)

### CODE REVIEW

**Comment by alnfedorov** [comment]
@jerryzh168 I can verify that CUDA 10.0 build fails because of the problem with C10_UNUSED and old nvcc version(you found it already). Guess, it will not hurt to confirm once more.

**Comment by jerryzh168** [comment]
@alnfedorov yes, the build failed with 10.0 and 10.1, but since we don't have the CI jobs for these version CI still passes

**Comment by jerryzh168** [comment]
@alnfedorov can you verify this compiles in cuda 9.2, 10.0, 10.1, 10.2?

**Comment by jerryzh168** [comment]
@pbelevich verified that this compiles in cuda 9.2, 10.0, 10.1, 10.2 on devfair machines.

**Comment by pbelevich** [comment]
please run: tools/git-clang-format 6fcabf619d2aeacc9867f41af8b36ddac06c3d25

**Review by pbelevich — APPROVED** [review]
Approved, but I only checked that is compiles with CUDA 9.2, 10.0, 10.1, 10.2

**Comment by alnfedorov** [comment]
@jerryzh168 Sure, I will check today. 9.2 - 10.1 for compilation + 10.2 with tests.

**Pull request closed without merging**
