### PR TITLE
[10/N] Remove ST init ops

### PR DESCRIPTION
**Pull request by fduwjj**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96985
* #96989

Differential Revision: [D44158326](https://our.internmc.facebook.com/intern/diff/D44158326)

### CODE REVIEW

**Review by wz337 — APPROVED** [review]
LGTM! Thanks for cleaning it up!

**Review by wanchaol — APPROVED** [review]
Same, it would be good to have extra validation it's not failing any internal tests :)

**Comment by fduwjj** [comment]
@fduwjj has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44158326).

**Comment by fduwjj** [comment]
@fduwjj has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44158326).

**Comment by fduwjj** [comment]
@fduwjj has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44158326).

**Pull request closed without merging**
