### PR TITLE
Issue 68576 prefetch factor

### LINKED ISSUE #68576: When `num_workers=0`, `prefetch_factor` is enforced to be `2` but this is missing from documentation
## 📚 Documentation

While constructing a `DataLoader` with `num_workers=0`, it is currently enforced that `prefetch_factor` can only be set to the default value (which is `2`). I am not too sure why and whether this should be expected behavior, for example wouldn't it perhaps be better to also support `prefetch_factor` values of `0` or `1`?

https://github.com/pytorch/pytorch/blob/e56d3b023818f54553f2dc5d30b6b7aaf6b6a325/torch/utils/data/dataloader.py#L180-L182

In any way, even in the case where only `prefetch_factor=2` should be supported when `num_workers=0`, I think there should be a note about that in the related docstring section:

https://github.com/pytorch/pytorch/blob/e56d3b023818f54553f2dc5d30b6b7aaf6b6a325/torch/utils/data/dataloader.py#L117-L119

Please do let me know if this issue should be marked as a bug issue vs. a documentation one.

Otherwise, if an addition to the docstring is required, I am happy to submit a PR. 

cc @brianjo @mruberry @SsnL @VitalyFedyunin @ejguan @NivekT

### PR DESCRIPTION
**Pull request by blankstatic**
Fixes #68576
This PR allows set the `prefetch_factor=None` making it really optional according to the documentation

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Review by ejguan — COMMENTED** [review]
Thank you for adding this PR. Could you please add a follow up PR to Fix the docstring related to `prefetch_factor` -> Default is `None` when `num_workers=0` but default is 2 when `num_workers>0`

**Pull request closed without merging**
