### PR TITLE
Enable CUDA Fuser for ROCm

### PR DESCRIPTION
**Pull request by t-vi**
This enables the cuda fuser on ROCm and enables tests for them.

Part of this patch is based on work of Rohith Nallamaddi, thank you.
Errors are my own, of course.

### CODE REVIEW

**Comment by t-vi** [comment]
@jeffdaily  @rohithkrn @walterddr @malfet @sunway513 (in part based on https://github.com/ROCmSoftwarePlatform/pytorch/pull/712/ )

**Comment by t-vi** [comment]
Oh, and @csarofeen @jjsjann123 , I hope I didn't screw up your code too much.

**Review by csarofeen — APPROVED** [review]
Looks fine to me.

**Comment by jeffdaily** [comment]
The caffe2 ROCm CI is timing out due to an unrelated change to master, scheduled to be reverted.  Also, ROCm CI moved to the 3.8 image this morning, in case we want to verify this PR against the newer image, too.

**Comment by t-vi** [comment]
I think ROCm 3.8 should be relatively safe given that I'm running it with success there. But I can also push an empty commit to rerun the CI.

**Comment by jeffdaily** [comment]
No need to push empty commit.  We can use pytorchbot.

**Comment by jeffdaily** [comment]
Let's wait until the caffe2 PR is reverted, though.

**Comment by jeffdaily** [comment]
CI looks good.

**Comment by t-vi** [comment]
If I understand the messages correctly, this is about the Caffe2 breakage. If it helps, I can rebase again, just shout.

**Pull request closed without merging**
