### PR TITLE
Improve convolution benchmarking performance

### LINKED ISSUE #50190: Calling emptyCache in Conv_v7.cpp causes performance degradation
## 🐛 Bug

In `aten/src/ATen/native/cudnn/Conv_v7.cpp`, there are calls to `CUDACachingAllocator::emptyCache` when running an algorithm search during benchmarking. [The justification for the calls is](https://github.com/pytorch/pytorch/blob/25a8397bf3760d60bd754517d590f15cbd041e25/aten/src/ATen/native/cudnn/Conv_v7.cpp#L280-L283):

```cpp
      // Free the cached blocks in our caching allocator. They are
      // needed here because the above benchmarking uses a huge amount of memory,
      // e.g. a few GBs.
      c10::cuda::CUDACachingAllocator::emptyCache();
```

There are a few issues with this call:
1. It's not necessary because `CUDACachingAllocator` [flushes its own cache internally](https://github.com/pytorch/pytorch/blob/8aad66a7bd35782a0e662d133276830204499656/c10/cuda/CUDACachingAllocator.cpp#L243) on a memory allocation when required.
2. The workspace memory is managed by a `Workspace` instance ([using RAII pattern](https://github.com/pytorch/pytorch/blob/25a8397bf3760d60bd754517d590f15cbd041e25/aten/src/ATen/native/cudnn/Conv_v7.cpp#L101-L120)) which is [scope-local with the `emptyCache` call](https://github.com/pytorch/pytorch/blob/25a8397bf3760d60bd754517d590f15cbd041e25/aten/src/ATen/native/cudnn/Conv_v7.cpp#L267-L283). So we're attempting to empty the cache before releasing the memory, defeating the justification in the comment.
3. In the case where `emptyCache` is able to find segments to release back to the driver, the internal `cudaFree` calls will cause device synchronizations, limiting parallelism. But as explained in the previous two points, there is no benefit to this call but we could end up paying a performance penalty nonetheless.

The performance degradation is particularly notable when training with `torch.backends.cudnn.benchmarking=True` and variable batch sizes since this code path is executed for each new input size.

I'm happy to submit a PR for this change.

## Environment

```
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] haste-pytorch==0.5.0rc0
[pip3] numpy==1.18.5
[pip3] torch==1.6.0
[pip3] torchaudio==0.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] haste-pytorch             0.5.0rc0                 pypi_0    pypi
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.1.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchaudio                0.6.0                    pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi
```

### PR DESCRIPTION
**Pull request by sharvil**
Fixes #50190

### CODE REVIEW

**Review by zasdfgbnm — CHANGES_REQUESTED** [review]
Hi @sharvil, thanks for your contribution! However, I don't think we will accept this.

cuDNN benchmark is slow by design, and the expected use case is, you run the benchmark once, PyTorch will cache your benchmark result and later use that result without running the benchmark again when seeing the same configuration. The benchmarking process itself is already slow and contains synchronizations, and the time for emptying the cache is usually only a small portion of the whole benchmark process.

The purpose of emptying cache is not to ensure PyTorch have enough memory to use but to release the memory to the system so that other application could use it.

Considering the above two points, we believe making other applications to have enough memory to run is more important than a small performance improvement. So I don't think we will move forward.

**Comment by sharvil** [comment]
Thanks for the explanation; I understand the rationale better now. However, the `emptyCache` call does not actually release memory back to the system for other applications. The `Workspace` object prevents the benchmarking memory from being released until *after* the `emptyCache` call so, at best, `emptyCache` will release other memory which happened to be reserved.

**Comment by zasdfgbnm** [comment]
@sharvil Good catch! Then can you modify this PR to release the Workspace before emptying cache?

**Comment by sharvil** [comment]
I can definitely make that change. But before I do, maybe we can discuss why this `emptyCache` call is even necessary.

The intent was to release benchmarking workspace memory back to other applications, but this code didn't actually do that. For multiple PyTorch releases, it seems that nobody really had an issue with the current behavior. So I would argue that we don't even need this call – it's either not necessary because or some other mechanism achieves the goal or we don't need it because there's no user-visible impact.

**Comment by zasdfgbnm** [comment]
I don't know, I benchmarked emptyCache (after workspace destroyed) vs not emptyCache with resnet50 with the script attached below, and the result seems to support your argument. But I am still worried because we have seen some configuration that some algorithms could take huge workspace (for example, 20GB workspace on an 80GB GPU), and I don't know if this is the case, what would the conclusion be.

cc: @ngimel 

```python
import torch
import torchvision.models as models
import timeit
torch.backends.cudnn.benchmark = True
dtype = torch.float
m = models.resnet50(pretrained=True).to(device='cuda', dtype=dtype)
ipt = torch.randn((128, 3, 224, 224), dtype=dtype, device='cuda')
torch.cuda.synchronize()
start = timeit.default_timer()
m(ipt).sum().backward()
torch.cuda.synchronize()
end = timeit.default_timer()
print(end - start)
print(torch.cuda.max_memory_allocated())
```

**Comment by ngimel** [comment]
I'd vote for emptying the cache in the correct place. Perf penalty is insignificant, benchmarking codepath is already very slow and should not be bottleneck anywhere, and returning unused memory certainly seems safer.

**Comment by sharvil** [comment]
While I understand the sentiment of "seems safer", I don't see any concrete argument for it in this thread. There's evidence both in my experiments and in @zasdfgbnm's that indicate that calling `emptyCache` isn't necessary. And we've seen 2 major PyTorch releases with that behavior without anyone noticing so I'm having a hard time seeing how it would be unsafe. 

To be clear, I'm still open to making the change that @zasdfgbnm suggested of releasing the Workspace before emptying the cache. But I don't see why that's the right thing to do here.

**Comment by zasdfgbnm** [comment]
I don't think "we've seen 2 major PyTorch releases with that behavior without anyone noticing" is a good argument for removing the `emptyCache`. At its current state, the `emptyCache` is not completely useless. It is possible that the first layer uses 20GB workspace, and this workspace is released by the `emptyCache` at the second layer, and this could be the reason why no one is noticing an issue.

**Pull request closed without merging**
