### PR TITLE
Do not scale atol for fast gradcheck by default

### PR DESCRIPTION
**Pull request by soulitzer**
The adjusted atol for fast gradcheck is too lenient for vast majority of cases. In this PR:
 - do not scale atol by default for fast gradcheck
 - add parameter in case user needs to scale atol. This is useful when Jacobian is dense, e.g., for `sum`.
 - fix unrelated issue discovered: when we do `_run_slow_mode_get_error`, it forgets to pass in eps, so it produces different results from actual slow_mode

Context:
 - Currently we scale `atol` for fast gradcheck by `\sum_{i} \sum_{j} u_i * v_j`, but this assumes that every entry in the Jacobian is off by epsilon in the same direction. Since most entries in Jacobian are actually zero, this makes fast_gradcheck H * W times less sensitive than it could be, i.e., if there is an entry in the analytical Jacobian (with width W, and height H), we would actually tolerate an error of sqrt(H * W) * atol.
 - It is tested that removing adjusted atol here would allow fast gradcheck to successfully detect that renorm's grad is wrong.

### CODE REVIEW

**Comment by albanD** [comment]
Would that make it more flaky for functions that have dense Jacobian though?

**Comment by soulitzer** [comment]
In theory yes. I didn't recall there were many though. If necessary we could have another parameter to enable scaling atol by tensor size, but have it disabled by default.

**Comment by albanD** [comment]
I think it would be interesting to get that info actually.
By running slow gradcheck and dumping the sparsity for every Jacobian computed for example?

**Comment by soulitzer** [comment]
> I think it would be interesting to get that info actually.
> By running slow gradcheck and dumping the sparsity for every Jacobian computed for example?

https://gist.github.com/soulitzer/fa2ac7c8240d89a128f357f0ce96203c

**Comment by albanD** [comment]
Thanks for the numbers! It does look like the average is in the 10%
So you think no scaling at all is the right thing here?


Also should we review the ones with 0. nnz values? A couple of them like copy_, fill_ are expected to be there, but there are others that I'm not as confident :D

**Pull request closed without merging**
