### PR TITLE
[build] Split `.cu` to improve compile times

### PR DESCRIPTION
**Pull request by suo**
The goal is to speed up CUDA builds. I was looking at bulid times and found that we have large CUDA compilation units that take forever to compile and make parallelism less effective. This PR splits them up into different `.cu` files so we can parallelize compilation better. We've done this sort of thing in the past with some success.

With a cold build, timing before: 5m42.019s, timing after: 4m30.275s. That's a speedup of 18.1% for me.

Behaviorally this should be a no-op, I'm just moving code around. There is still more we can do here but I did most of the ones that are copypasta. The full list of remaining chonky compilation units is [here](https://gist.github.com/suo/0dc217733f40f59898a8cc4f60529d60).

## Details
Here's a screenshot from a ninja trace, with the following command:
```
MAX_JOBS=64 CCACHE_DISABLE=1 TORCH_CUDA_ARCH_LIST=Ampere BUILD_CAFFE2_OPS=0 USE_FBGEMM=0 USE_DISTRIBUTED=0 USE_MKLDNN=0 BUILD_TEST=0 USE_GOLD_LINKER=1 USE_OPENMP=1 USE_NCCL=0 DEBUG=0 python setup.py develop
```
image

([source trace](https://gist.github.com/suo/5f5458f2630f9ab6dcbea6989e892195), which you can visualize in [perfetto](https://ui.perfetto.dev/))

After this PR, we get somewhat better utilization (although there is plenty still left to do): 
image

([source trace](https://gist.github.com/suo/5607335bcd4bd412d42b0c9334259184))

### CODE REVIEW

**Comment by ngimel** [comment]
This looks fine, but might require some internal build changes.

**Comment by suo** [comment]
how exciting!

**Review by cpuhrsch — APPROVED** [review]

**Review by malfet — APPROVED** [review]
LGTM, can you please add binary size changes for this PR? (As we are not using device compilation, so this would increase number of times cudadev_rt  gets compiled into the binary)

**Comment by suo** [comment]
> LGTM, can you please add binary size changes for this PR? (As we are not using device compilation, so this would increase number of times cudadev_rt gets compiled into the binary)

I'm a noob, how should I measure this?

**Comment by Chillee** [comment]
Hell yeah.

**Comment by Lezcano** [comment]
This may be one of the reasons why tensorflow has one file per operator (besides having better control over what's included / used where).

**Pull request closed without merging**
