### PR TITLE
remove some code part never been called

### PR DESCRIPTION
**Pull request by huangzhiyuan**
At title. Found that  `THBlas_(swap)` was never be used. So I remove it from repo. Please help review patch, and any suggestions are welcomed.

### CODE REVIEW

**Comment by huangzhiyuan** [comment]
@gchanan please have a reivew, thanks~

**Comment by huangzhiyuan** [comment]
add @XiaobingSuper

**Comment by huangzhiyuan** [comment]
@albanD, @gchanan please take a view, the first PR contribute to the community waited too long : (

**Review by albanD — APPROVED** [review]
Hi,

Sorry for the delay, greg is very busy with preparing the 1.5 release.
This looks good, tests seem to be passing.
Thanks for the contribution.

**Pull request closed without merging**
