### PR TITLE
Tensor and device is_hpu methods

### PR DESCRIPTION
**Pull request by sujoysaraswati**
Add is_hpu() methods for Aten tensor and device

### CODE REVIEW

**Comment by soulitzer** [comment]
Thank you for the contribution! It would be helpful if you could create an issue so we have a place to discuss these changes?

**Comment by wconstab** [comment]
This look good to me.  I second the request to add an overall issue to talk about the plans for adding HPU device to pytorch, as a place we can have discussions that are bigger than the small PRs.  
@malfet any concerns? otherwise i'll land

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Looks good to me as well. And I 2nd the opinion, that it would be great to have an issue outlining the work and reference it from this PR as well as from https://github.com/pytorch/pytorch/pull/65409 and https://github.com/pytorch/pytorch/pull/65410

**Comment by wconstab** [comment]
I'm working on landing this; first attempt failed to land due to internal infra issues, had to rebase and try again..

**Comment by sujoysaraswati** [comment]
> This look good to me. I second the request to add an overall issue to talk about the plans for adding HPU device to pytorch, as a place we can have discussions that are bigger than the small PRs.
> @malfet any concerns? otherwise i'll land

Thanks, I will add am issue for the HPU device related tasks.

**Comment by sujoysaraswati** [comment]
> > This look good to me. I second the request to add an overall issue to talk about the plans for adding HPU device to pytorch, as a place we can have discussions that are bigger than the small PRs.
> > @malfet any concerns? otherwise i'll land
> 
> Thanks, I will add an issue for the HPU device related tasks.

I have submitted https://github.com/pytorch/pytorch/issues/65609.

**Pull request closed without merging**
