### PR TITLE
Enable test: distributed/algorithms/quantization/test_quantization

### PR DESCRIPTION
**Pull request by yhcharles**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #80097

fixes  https://github.com/pytorch/pytorch/issues/69017

topic: not user facing

### CODE REVIEW

**Comment by wanchaol** [comment]
Looks like this failed in CI, not sure if that's an involved error, is it also failed locally? If so, we can do some local debugging and see if the error is easy to fix?

**Comment by malfet** [comment]
Please rebase your PR against [`viable/strict`](https://github.com/pytorch/pytorch/tree/viable/strict) and add `ciflow/trunk` label. If CI is green it should be good to go.

**Review by rohan-varma — COMMENTED** [review]
thanks for the PR! Looks like quantization test failed: https://github.com/pytorch/pytorch/runs/7028400114?check_suite_focus=true#step:9:1298 but might be an easy fix if there are no further issues, are you planning to take this forward? Thank you!

**Review by wanchaol — APPROVED** [review]
looks good, thank for the fix!

Small tip: you can add `fixes https://github.com/pytorch/pytorch/issues/69017` to your PR description to automatically close the issue once your PR get landed.

**Pull request closed without merging**
