### PR TITLE
[Reland][3/N] Add -Wdeprecated and related fixes

### PR DESCRIPTION
**Pull request by cyyever**
Fixes the string_view errors and reland the work. The previous changes in torch/csrc/utils/invalid_arguments.cpp were too aggressive and not tested thoroughly. They are discarded.
cc @EikanWang @jgong5 @PaliC

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by Bycob** [comment]
Hello, in a6140a23b7b43fd6bdc16fd21a497a85014e2d67, the inheritance to torch::nn::Module of Cloneable is no longer `virtual`. This removes the possibility to create cloneable modules that inherit another module, because of the double inheritance. Is there any reason this `virtual` was removed? I see no better solution than patching it back for my use case.

**Comment by cyyever** [comment]
I can remember that virual inheritance in Cloneable prevents compiler generated copy/move functions.

**Comment by Bycob** [comment]
So to keep the ability of inherit classes extending Cloneable, I patched pytorch and had to remove the `default` operators in Module, like before this PR. As I understand, this may impact performances when we call the `move` operator, and may trigger some warnings ? Which in my case is not a big deal in exchange of keeping the inheritance feature. I wonder if other users have the same problem, and whether there would be a solution to this, with or without the virtual inheritance

**Comment by ezyang** [comment]
Oh oops, we should not have removed the virtual inheritance

**Comment by ezyang** [comment]
@Bycob do you mind sending us a patch that reverts this? That was my bad in code review

**Comment by cyyever** [comment]
Propose a PR? I remembered that using virtual inheritance may cause copy slicing. I need to recheck the warnings after enabling it.

**Pull request closed without merging**
