### PR TITLE
set workspace size to 4M

### PR DESCRIPTION
**Pull request by jianyuh**
Summary: Follow D34480690 (https://github.com/pytorch/pytorch/commit/3ec1dd9989ac5441c767f975f5e0fc46847400a2)

Test Plan: CI

Differential Revision: D34636039

### CODE REVIEW

**Comment by jianyuh** [comment]
According to https://docs.nvidia.com/cuda/cublas/index.html#cublassetworkspace  , the recommended size of user-provided workspace is at least 4MiB (to match cuBLAS' default workspace pool).

@xuzhao9 verified the perf in https://github.com/pytorch/pytorch/pull/74159 . It is subtle perf improvement or no regression.

**Comment by jianyuh** [comment]
`TorchBench CI` workflow is disabled as it can only run on a pytorch repo PR.

**Review by xuzhao9 — APPROVED** [review]
LGTM!

**Pull request closed without merging**
