### PR TITLE
Don't set requires_grad inside meta function

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108988

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Comment by lezcano** [comment]
Why don't we want to do this?

**Comment by ezyang** [comment]
Meta functions happen below autograd so they shouldn't set autograd metadata (requires_grad); that'll be handled by the autograd layer above. Concretely, I was working on our opcheck testing and noticed this was causing a problem.

**Review by lezcano — APPROVED** [review]

**Review by bdhirsh — APPROVED** [review]

**Pull request closed without merging**
