### PR TITLE
fix: invalid type annotaiton in lr_scheduler.pyi

### PR DESCRIPTION
**Pull request by tamuhey**
`epoch` in `_LRScheduler.step` is an optional argument, so I modified `epoch: int` to `epoch: Optional[int]`.

https://github.com/pytorch/pytorch/blob/f433ee149991fe2958a64f025d8bdeec5fa3d2a2/torch/optim/lr_scheduler.py#L83

### CODE REVIEW

**Comment by tamuhey** [comment]
It seems to be GitHub Action's internal error.

**Comment by yf225** [comment]
@vincentqb Would you like to take a look?

**Review by vincentqb — APPROVED** [review]
Good catch! This looks good to me, but let's retry the CI tests. Ideally, we should have a unit test to catch this.

**Comment by vincentqb** [comment]
Retrying tests in new PR: #26930

**Comment by vincentqb** [comment]
Landing from #26930.

**Pull request closed without merging**
