### PR TITLE
Breakup Test Misc (batch 1/2)

### PR DESCRIPTION
**Pull request by eellison**
Breakup test_misc so that a test for a file is in test_filename. I think we might want to wait on moving test files into the source directory, since that would involve moving some tests over to the C10 folder, and this goes 99% of the way for test discoverability IMO anyway. 

I added a file test_utils for common functions invoked in the tests.

### CODE REVIEW

**Review by suo — APPROVED** [review]
lgtm

**Comment by suo** [comment]
I think you should merge test_utils.h into test_base.h.

**Comment by eellison** [comment]
> I think you should merge test_utils.h into test_base.h.

will do in the second batch PR since CI is wonky right now & i would like to land

**Comment by suo** [comment]
@eellison, looks like this PR broke `pytorch_linux_trusty_py3_6_gcc7_test`:
```
Mar 15 23:08:18 *** Error in `/var/lib/jenkins/workspace/../cpp-build/caffe2/bin/test_jit': double free or corruption (!prev): 0x0000000002def190 ***
```

**Pull request closed without merging**
