### PR TITLE
[BC-breaking] Make `options.name_` private, and change all callsites to use `options.name()`

### PR DESCRIPTION
**Pull request by yf225**
The implementation of several modules in C++ frontend currently has calls to `options.name_`,  which is bad practice because `options.name_` should be a private options field and we should use `options.name()` to access its value. This PR makes `options.name_` actually private and changes all callsites of `options.name_` to `options.name()`.

After this change, we can change all module options to have a map as the underlying data structure, and require that all options must be able to be stored in `c10::IValue`. These changes together would make serializing module options much easier.

Note that this PR is BC-breaking in the following way:

Previously, calling `options.name_` in C++ module implementation works because `options.name_`  was a public field. After this PR, `options.name_` becomes private, and to get the value of `options.name_` we should call `options.name()`, and to set the value of `options.name_` we should call `options.name(new_value)`.

### CODE REVIEW

**Comment by yf225** [comment]
@ShahriarSS Would you like to review this PR?

**Review by ShahriarRezghi — COMMENTED** [review]
@yf225 I left some comments.

**Comment by yf225** [comment]
@ShahriarSS Thanks a lot for the review! I addressed the arg function inlining concerns, and I'll open another PR for fixing options moving.

**Comment by ShahriarSS** [comment]
@yf225 Then these changes look good to me. Also why do 5 or 6 tests always fail on PRs?

**Comment by yf225** [comment]
@ShahriarSS There is some CI infra issue going on now which causes those builds to fail. We will try to fix it as soon as possible.

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
