### PR TITLE
Fix lint after #93278

### PR DESCRIPTION
**Pull request by huydhn**
Per title

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by kit1980** [comment]
https://github.com/pytorch/pytorch/pull/93278 was merged without force, how did it pass lint on pull request?

**Comment by jansel** [comment]
Race condition with another PR?

**Comment by jansel** [comment]
I believe the race was between #93851 and #93278 both removed usage of config.

**Pull request closed without merging**
