### PR TITLE
Fix a grep-itself bug when checking for GPU healthcheck

### PR DESCRIPTION
**Pull request by huydhn**
The logic works https://github.com/pytorch/pytorch/actions/runs/4558327458, but it also grep itself due to `set -x` is set (Ugh, debug message)

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Sure, but IMO this is still a bandaid to a fix applied at the wrong place. We should some sort of health-check mechanism built into the runner (@seemethere mentioned we can configure pre-hooks of some sort)

**Comment by huydhn** [comment]
> Sure, but IMO this is still a bandaid to a fix applied at the wrong place. We should some sort of health-check mechanism built into the runner (@seemethere mentioned we can configure pre-hooks of some sort)

Yup, that would be nicer than this bandaid fix.  I chat with @jeanschmidt a bit on the matter and we agree that it's a patch I while we work toward the proper solution

**Review by weiwangmeta — APPROVED** [review]
LGTM. 
Does GHA provide re-scheduling if pre-job returns as "no-go"?

**Comment by huydhn** [comment]
> LGTM. Does GHA provide re-scheduling if pre-job returns as "no-go"?

GHA doesn't, but our retry bot does.  It retries cancelled jobs.  However, it depends on how GitHub retry works and has a drawback in which retry could only be done after every job in the workflow has completed

**Comment by huydhn** [comment]
After meditating a bit more on the logic, I don't think a Docker failure should be treated as an unrecoverable error.  That's too heavy-handed, so I completely remove that part, only the `nvidia-smi` check is qualified now.

**Pull request closed without merging**
