### PR TITLE
allow DataParallel to have tuple inputs on a single GPU

### PR DESCRIPTION
**Pull request by ngimel**
...for consistency with multi-GPU case, useful for rnns.

### CODE REVIEW

**Comment by apaszke** [comment]
Could you add it to replicate too? That would fix the issue with multiple GPUs.

**Comment by soumith** [comment]
and a small unit test to cover this

**Comment by ngimel** [comment]
@apaszke,  replicate replicates the module and does not care about inputs. Scatter already handles tuple input: 
https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/scatter_gather.py#L5-L13
so tuple input already works on multiple GPUs. Issue arises when you wrap a model in DataParallel and try to run it on a single GPU. Or did I misunderstand you?
@soumith, I'll add unit test.

**Comment by apaszke** [comment]
Sorry, my bad. Still, I don't think this fixes RNNs. They take in two arguments, one of which may be a tuple. However in the code, the module is always called with a single argument.

**Comment by ngimel** [comment]
Packing RNN arguments in a tuple is easy, e.g. replacing this
https://github.com/pytorch/examples/blob/master/word_language_model/model.py#L26
with
```
def forward(self, inptuple):
    input = inptuple[0]
    hidden = inptuple[1] #possibly a nested tuple
```
but if you wrap thus defined module in DataParallel, it will run fine on multi-GPU and will error out on a single GPU.

**Comment by apaszke** [comment]
Yeah, but I consider that a bug. Anyway, I'll merge this because it makes multi-GPU consistently broken 🙂 Thanks!

**Pull request merged**
