### PR TITLE
[WIP] Migrate distribution transform computations into functional.py + add unit tests (test_distributions.py) for functions

### PR DESCRIPTION
**Pull request by jamarshon**
T44448080 Refactor transforms.py into functional.py. 
Unit tests are added for the functions in test_distributions.py

### CODE REVIEW

**Comment by cpuhrsch** [comment]
@fritzo - I saw you frequently on the history of distributions.py - do you mind taking a look?

**Comment by fritzo** [comment]
cc @stefenwebb, related to https://github.com/pyro-ppl/pyro/issues/1869

**Comment by fritzo** [comment]
It seems reasonable to me to move the underlying math operations of `torch.distributions.transforms` into functional.py.

Note that `torch.distributions.transforms` intends to create extra metadata on top of the transform math so that `Transform`s are useful for probabilistic modeling. Specifically torch.distributions.transforms:
- bundles forward+psudoinverse+log_abs_det_jacobian methods together
- handles constraints (and we're planning to work on this further)
- handles sign of the jacobian
- knows about the torch.distributions batch_shape/event_shape split
- makes `Transform`s that are registered in the `ConstraintRegistry`.

**Comment by cpuhrsch** [comment]
Thanks @fritzo - I'll add you as a reviewer.

**Comment by fritzo** [comment]
@jamarshon can you help me understand the motivation behind this PR? While I understand that it is easier move the `.call` and `.inv` methods into functiona.py, this PR seems to go very far to move every bit of math into functional.py, and the extra layer of indirection comes at significant readability cost. Is the intention to improve jit support or eventually move implementations into C++/CUDA?

**Comment by jamarshon** [comment]
@fritzo I was mistaken in thinking that refactoring all the code into functional.py was for organizational benefits. Now that I realize that it is for performance (i.e. C++ etc.), I will move some code back into transforms.py that are non significant meaning those that do not optimizing.

**Comment by fritzo** [comment]
@jamarshon what's the motivation for this PR? Are you sure we should be creating a new torch.distributions.functional module rather than moving these operations into torch.nn.functional? Is somebody at facebook planning to move these operations into C++? Thanks for keeping me in the loop!

**Comment by jamarshon** [comment]
@fritzo I think that having torch.distributions.functional module is fine since the code (transforms.py) is in the distributions module. No for now, there are no current plans to move them to C++.

**Review by soumith — CHANGES_REQUESTED** [review]
the way this PR currently stands, it makes no sense.

things that should me moved to functional should be usable by themselves, and should make API sense.

functions like `affine_transform_call` and `affine_transform_inverse` dont make sense to be used by themselves (what is an `affine_transform_call` anyways?)

If you see `torch.nn.functional`, the functions in there have cleanly designed APIs and make sense to be used by themselves.
If the motivation of this PR is to move some parts to functional.py, then the API of the code to be moved has to be thought out

**Comment by cpuhrsch** [comment]
@soumith - I'll take over this PR, but with low priority. We'll revisit this later due to a change in priorities.

**Pull request closed without merging**
