### PR TITLE
Fix _dummy_type name typo

### LINKED ISSUE #15817: [QUESTION] Should _dummy_type use name instead of storage_name?
Should [_dummy_type](https://github.com/pytorch/pytorch/blob/55baca57d2af8b1f7268befd379aabeed165ff20/torch/cuda/__init__.py#L476) in `torch/cuda/__init__.py` use `name` instead of `storage_name` as the type name? I tried to make that change, but it leads to a 50% reproducible test failure in `test_dag_net_forking` on `py2-devtoolset7-rocmrpm-centos7.5` [[failed example](https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger-test/5439/)][[passed example](https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger-test/5460/)]. Error message is shown below:

```
21:05:50 ../../../../usr/local/caffe2/lib/python2.7/site-packages/caffe2/python/hypothesis_test.py::TestOperators::test_dag_net_forking ./.jenkins/caffe2/test.sh: line 96:  4908 Aborted                 (core dumped) "$PYTHON" -m pytest -x -v --disable-warnings --junit-xml="$pytest_reports_dir/result.xml" --ignore "$CAFFE2_PYPATH/python/test/executor_test.py" --ignore "$CAFFE2_PYPATH/python/operator_test/matmul_op_test.py" --ignore "$CAFFE2_PYPATH/python/operator_test/pack_ops_test.py" --ignore "$CAFFE2_PYPATH/python/mkl/mkl_sbn_speed_test.py" ${rocm_ignore_test[@]} "$CAFFE2_PYPATH/python" "${EXTRA_TESTS[@]}"
```

### PR DESCRIPTION
**Pull request by mrshenli**
closes #15817

### CODE REVIEW

**Comment by ezyang** [comment]
Test? :)

**Comment by mrshenli** [comment]
@ezyang 

Is this name mismatch expected (due to [this](https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/python_engine.cpp#L229) and [this](https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/python_engine.cpp#L282)):

```python
>>> import torch
>>> torch._C._ImperativeEngine
<class 'torch._C._EngineBase'>
```

**Comment by ezyang** [comment]
I don't know. But generally `torch._C` are considered purely implementation details and can change without warning.

**Comment by mrshenli** [comment]
`_ImperativeEngine` is the only exception. All other attr `xyz` under `torch._C` either uses name `xyz` or `torch._C.xyz`.

**Comment by mrshenli** [comment]
@colesbury is the name mismatch for `torch._C._ImperativeEngine` expected?

**Comment by colesbury** [comment]
I don't know. I don't think it matters.

**Comment by mrshenli** [comment]
OK. I will then limit the test scope to `_CudaStreamBase` and `_CudaEventBase` only.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
