### PR TITLE
Error messages for kernel selection

### PR DESCRIPTION
**Pull request by mikekgfb**
Summary: Error messages fro kernel selection

Test Plan: sandcastle & github

Differential Revision: D42008661

### CODE REVIEW

**Review by cpuhrsch — CHANGES_REQUESTED** [review]
Why turn all these checks into warnings?

**Comment by mikekgfb** [comment]
> Why turn all these checks into warnings?

Because we're reporting the first error for the first kernel today.  So, if you disable mem_efficient, and Flash predictaes do not work, you still get an answer why memory efficient kernel does not work.  That's straight up wrong because it's not actionable, and it's also misleading.

So, for the  case when there's not kernel, I changed it to dumping all the reasons for all kerbnels, and then error out "and hence you lose, and don't have an executable kernel".

This gives people a way to actually impact.

@drisspg had previously mentioned he could fix the current issue with some if-spaghetti logic to make sure we give the error for the enabled kernel, but also pointed out that it's just not scalable if we ever add more kernels coz combinatorial explosion.

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
