### PR TITLE
[wip] Removing arch 20 + 21

### PR DESCRIPTION
**Pull request by pjh5**
Testing if this solves the shfl_xor undefined problem on cuda8 with conda and aten

### CODE REVIEW

**Comment by pjh5** [comment]
Looks like it worked, but unsure if this change is desired. https://ci.pytorch.org/jenkins/job/caffe2-packages/job/conda2-cuda8.0-cudnn7-integrated-ubuntu16.04-build-upload/19/

**Comment by ezyang** [comment]
What's the change?

**Comment by pjh5** [comment]
This removes support for some older CUDA archs when building Caffe2. This is needed when building Caffe2 with ATen, as it seems that ATen has a higher minimum version requirement for CUDA.

**Comment by pjh5** [comment]
This PR has received Yangqing's blessing

**Review by ezyang — APPROVED** [review]

**Pull request merged**
