### PR TITLE
Try increasing realize_bytes_threshold

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #116692

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by isuruf** [comment]
cc @lezcano. There's one illegal memory access. Looking into it now.

**Comment by lezcano** [comment]
The errors indeed look real. I guess this flag was hiding some bugs. We should fix those, if the bugs are on PyTorch land, or triage and fill in triton issues if they are on triton.

**Comment by isuruf** [comment]
I increased the threshold to a really large number so that we don't realize and fuse always. Let's see how the benchmarks go.

**Comment by isuruf** [comment]
Benchmarks remain unchanged. See [here](https://hud.pytorch.org/benchmark/compilers?startTime=Wed%2C%2010%20Jan%202024%2013%3A53%3A58%20GMT&stopTime=Wed%2C%2017%20Jan%202024%2013%3A53%3A58%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=gh/isuruf/22/head&lCommit=a1ecf7787ded29f426f9dc2475d68992a1db6427&rBranch=main&rCommit=13473df0d770e67f92cb4bb1b728f3746f160b7c)

**Comment by isuruf** [comment]
This picked up a few recursion errors in CI though.

**Comment by lezcano** [comment]
It looks like moco failed to run:
https://hud.pytorch.org/benchmark/torchbench/inductor_dynamic?startTime=Wed%2C+10+Jan+2024+13%3A53%3A58+GMT&stopTime=Wed%2C+17+Jan+2024+13%3A53%3A58+GMT&granularity=hour&mode=training&dtype=amp&lBranch=gh%2Fisuruf%2F22%2Fhead&lCommit=a1ecf7787ded29f426f9dc2475d68992a1db6427&rBranch=main&rCommit=13473df0d770e67f92cb4bb1b728f3746f160b7c

If we can fix that, I think it'd be fine to land this PR.

My guess is that the iterative algorithm where we decrease the block size if there is register spilling is rendering this "kernel size" threshold unnecessary.
Thoughts @jansel ?

**Review by peterbell10 — CHANGES_REQUESTED** [review]
I'm not convinced that torchbench adequately exercises this heuristic. To run into this condition you need long sequence of operations that only read a single tensor and also don't realize due to fallbacks or template kernels which is going to be quite rare.

Can we see some synthetic benchmarks with e.g. a for loop that manually sums over a very large tensor. I suspect this would blow up completely.

**Pull request closed without merging**
