### PR TITLE
Device type test registration

### PR DESCRIPTION
**Pull request by mruberry**
Per title.

Creates a new file to hold the DeviceTypeTestBase to avoid recursive imports.

The documentation is updated to describe the new method of registering a device type for testing. Third parties copy a file into PyTorch's test folder that supports acquiring their test base. I have tested this e2e with XLA and will coordinate a follow-up PR to PyTorch/XLA once this lands.

Previously third parties had to edit common_device_type.py directly to add their test class, which is fragile, at best, and not a great extensibility point. Multiple device types, for example, would almost certainly break each other.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 6d51fa9:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=6d51fa9563bded87a106f0f7ded88ae42f53d816).

### :detective: 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4023655) pytorch_xla_linux_xenial_py3_6_clang7_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=77819236) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=77819236))
<details>
<summary>
<code>Dec 19 23:08:54 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff</code>
</summary>

```
Dec 19 23:08:54 + PTDIR=/var/lib/jenkins/workspace/xla/scripts/../.. 
Dec 19 23:08:54 + python /var/lib/jenkins/workspace/xla/scripts/cond_patch.py /var/lib/jenkins/workspace/xla/scripts/../torch_patches /var/lib/jenkins/workspace/xla/scripts/../.. 
Dec 19 23:08:54 3 out of 4 hunks FAILED 
Dec 19 23:08:54 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-clip_grad.diff 
Dec 19 23:08:54 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff 
Dec 19 23:08:54 Traceback (most recent call last): 
Dec 19 23:08:54   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 67, in <module> 
Dec 19 23:08:54     patch_repo(args) 
Dec 19 23:08:54   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 49, in patch_repo 
Dec 19 23:08:54     raise RuntimeError('Failed to apply patch: {}'.format(ppath)) 
Dec 19 23:08:54 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff 
Dec 19 23:08:54 + cleanup 
Dec 19 23:08:54 + retcode=1 
Dec 19 23:08:54 + set +x 
Dec 19 23:08:54 =================== sccache compilation log =================== 
Dec 19 23:08:54 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 19 23:08:54 Compile requests                 1 
Dec 19 23:08:54 Compile requests executed        0 
Dec 19 23:08:54 Cache hits                       0 
Dec 19 23:08:54 Cache misses                     0 
Dec 19 23:08:54 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by mruberry** [comment]
Importing to review tests.

**Comment by mruberry** [comment]
Addressed by https://github.com/pytorch/pytorch/pull/36321.

**Pull request closed without merging**
