### PR TITLE
[dynamo] Refactor OrderedDict to dict

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #113234

In Python3 all dicts are ordered.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by oulgen — APPROVED** [review]
There's a lot of dict copying, preexisting, i wonder whether we can reuse them to avoid all the copies.

**Review by lezcano — APPROVED** [review]
Yep, I wanted to do this in all that dictionary stack

**Comment by youkaichao** [comment]
Hey, there, although dicts are ordered in python3, there is still a difference: dict cannot be weak referenced, but OrderedDict can:

```python
from collections import OrderedDict
d1 = OrderedDict()
d2 = {}

import weakref
weakref.ref(d1) # no problem
weakref.ref(d2) # error
```

This affects the bytecode hook dict, whose handle uses weakref:

https://github.com/pytorch/pytorch/blob/eb1534027f371f5b6942841efc77d56a3921d587/torch/utils/hooks.py#L24

It is fortunate that I noticed this today ......

Maybe we should fix this (for `_bytecode_hooks`), and add a test case there.

WDYT, @jansel ?

**Comment by jansel** [comment]
Sure, feel free to submit a PR to change it back for the hooks dict.

**Pull request closed without merging**
