### PR TITLE
Revise error message for invalid Reduction

### PR DESCRIPTION
**Pull request by kiddyboots216**
Say the user inputs reduction=False. Of course, we can't add a bool and a string, so the ValueError itself will error -which is more confusing to the user. Instead, we should use string formatting. I would use `f"{reduction} is not..."` but unsure whether we are ok with using f"" strings.

### CODE REVIEW

**Review by zou3519 — COMMENTED** [review]
This is great, but please add a test to https://github.com/pytorch/pytorch/blob/master/test/test_nn.py . [Something that triggers the error and checks the error message like this](https://github.com/pytorch/pytorch/blob/a45898931c669baf3f49e1e8e9ac6523d517beb0/test/test_nn.py#L4917) would be great.

**Review by soumith — APPROVED** [review]
i'm approving it on the basis of triviality.

**Comment by soumith** [comment]
@kiddyboots216 if you can add a test and send it as a follow-up PR, that would be fantastic. thanks for the fix.

**Comment by kiddyboots216** [comment]
@soumith am planning on doing that -have just been trying to figure out the tests module, but it will happen this week.

**Comment by ailzhang** [comment]
cc: @soumith  this failed to land

**Pull request closed without merging**
