### PR TITLE
[Intel Triton] Update Intel Triton to release/2.5.0

### PR DESCRIPTION
**Pull request by Stonepia**
This PR relands https://github.com/pytorch/pytorch/pull/134053

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by alexbaden** [comment]
The build errors regarding the triton URL are from this line: https://github.com/pytorch/pytorch/blob/main/.github/scripts/build_triton_wheel.py#L59
I am surprised that change is in place vs picking up https://github.com/triton-lang/triton/commit/06e6799f4eba6035ec35c528e8fefd3d4d724b6f, which is a small commit.

**Comment by Stonepia** [comment]
Related issue: https://github.com/pytorch/pytorch/issues/134199

**Comment by Stonepia** [comment]
The "Build Triton Wheel" action failure is not related to this PR. It is addressed in this PR: https://github.com/pytorch/pytorch/pull/135201

**Review by EikanWang — APPROVED** [review]

**Pull request closed without merging**
