### PR TITLE
[5/N] [Dispatchable Collectives] Update send with CPU / CUDA implementations

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #86166 [9/N] [Dispatchable Collectives] Update reduce_scatter with CPU / CUDA implementations
* #84423 [8/N] [Dispatchable Collectives] Update allgather with CPU / CUDA implementations
* #83916 [7/N] [Dispatchable Collectives] Update reduce with CPU / CUDA implementations
* #83876 [6/N] [Dispatchable Collectives] Update recv with CPU / CUDA implementations
* **#83859 [5/N] [Dispatchable Collectives] Update send with CPU / CUDA implementations**

### Changes
- Updates for the send collective

### Context
https://github.com/pytorch/pytorch/issues/86225

Differential Revision: [D40044550](https://our.internmc.facebook.com/intern/diff/D40044550)

### CODE REVIEW

**Review by kwen2501 — APPROVED** [review]
LGTM! Thanks!

nit: missing _ at the end of function name ("send_cpu", "send_cuda").

**Comment by H-Huang** [comment]
> nit: missing _ at the end of function name ("send_cpu", "send_cuda").

The convention is that _ after operation means that the tensor is modified in-place. For barrier and send we do not modify the tensor, therefore those ops dont have "_" after

**Comment by kwen2501** [comment]
I see, thanks for the education!

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40044550).

**Pull request closed without merging**
