### PR TITLE
Avoid `__ne__` weakref comparison and use identity instead in cache_size.py

### PR DESCRIPTION
**Pull request by vmoens**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135000

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Comment by vmoens** [comment]
This change is needed because `weakref.ref(obj) != weakref.ref(obj)` falls back onto `obj != obj` which may not be a bool (eg if `obj` is a tensor). 
For instance:
```python
>>> obj = torch.randn((10,))
>>> ref1 = weakref.ref(obj)
>>> ref2 = weakref.ref(obj)
>>> print(ref1 == ref2)  # True
tensor([True, True, True, True, True, True, True, True, True, True])
>>> print(ref1 is ref2)  # False
True
```

**Review by anijain2305 — APPROVED** [review]
Can you add a test please?

**Comment by vmoens** [comment]
@anijain2305 I tried to find one simple test but couldn't so far. I'll let you know once I do

**Pull request closed without merging**
