### PR TITLE
set -Winconsistent-missing-override for builds

### PR DESCRIPTION
**Pull request by dagitses**
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/pytorch/pull/89851).
* #89852
* __->__ #89851

set -Winconsistent-missing-override for builds

Summary: This has triggered internally on some PyTorch code.

Test Plan: Rely on CI.

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
Adding `missing-override` sounds fine, but why do you need to change the initializer (and aren't you doing it already in the other PR on stack?)

**Comment by dagitses** [comment]
> Adding `missing-override` sounds fine, but why do you need to change the initializer (and aren't you doing it already in the other PR on stack?)

that's just an artifact of using Sapling. It sets up the stack to merge into main, rather than into the base branch (for some reason). ReviewStack understands to filter out commits appropriately.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
