### PR TITLE
fix norrow_copy correctness issue for non-contiguous input for cpu path

### LINKED ISSUE #91690: narrow_copy : silently incorrect for non-contiguous inputs on CPU
```python
import torch

device = 'cpu'
# device = 'cuda'  # This works
dtype = torch.float

inp = torch.randn(10, 2, device=device)
noncontig_input = inp.movedim(-1, 0)

args = (1, 0, 10)

expected = torch.narrow_copy(noncontig_input.contiguous(), 1, 0, 10)
actual = torch.narrow_copy(noncontig_input, 1, 0, 10)

torch.testing.assert_close(actual, expected)
```

Fails with 
```
AssertionError: Tensor-likes are not close!

Mismatched elements: 18 / 20 (90.0%)
Greatest absolute difference: 3.2289832830429077 at index (1, 8) (up to 1e-05 allowed)
Greatest relative difference: 18.178259409098075 at index (0, 9) (up to 1.3e-06 allowed)
```

cc @ezyang @gchanan @zou3519 @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @Chillee @samdow @soumith

### PR DESCRIPTION
**Pull request by XiaobingSuper**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #91789

Fix https://github.com/pytorch/pytorch/issues/91690.

cc @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
LGTM. Do you mind add the root cause and the resolution in brief in the description?

**Review by lezcano — APPROVED** [review]
What this is implicitly doing is forcing `narrow_copy_dense_cpu_out` to resize `output` into a *contiguous* tensor of the right shape. The solution is a bit indirect, and a comment would help, but LGTM.

**Comment by XiaobingSuper** [comment]
https://github.com/pytorch/pytorch/pull/91355 add narrow_copy failed case check which cause the CI failed, I create another PR to remove the failed case check, see https://github.com/pytorch/pytorch/pull/91883.

**Pull request closed without merging**
