### PR TITLE
dbr quant: start reusing static quant module mappings

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70372 dbr quant: add limited support for `torch.nn.ModuleList`
* #70349 dbr quant support for custom leaf modules, part 3/x
* #70335 dbr quant: support for custom leaf modules, part 2/x
* #70330 dbr quant: support for custom leaf modules, part 1/x
* #70329 dbr quant: unbreak case when child module not returning any outputs
* #70328 dbr quant: support functional linear without bias
* #70257 dbr quant: support dynamic linear
* #70256 dbr quant: do not attach auto_quant_state to observers
* #70247 dbr quant: stop calling eager quant convert
* #70246 dbr quant: break up test class into multiple classes
* #70200 dbr quant: start recording ops which are not quantizeable
* **#70196 dbr quant: start reusing static quant module mappings**

Summary:

Deletes the custom DBR static quant module mapping, and reuses
the global ones.

Test coverage for all the ops will be in future PRs.

Test plan:

```
python test/test_quantization.py TestQuantizeDBR
```

Differential Revision: [D33240998](https://our.internmc.facebook.com/intern/diff/D33240998)

### CODE REVIEW

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33240998).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33240998).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33240998).

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33240998).

**Review by jerryzh168 — APPROVED** [review]

**Pull request closed without merging**
