### PR TITLE
fix errors about mypy check in torch/_inductor/compile_fx.py

### PR DESCRIPTION
**Pull request by fffrog**
the `compile_fx.py` blocked the merging of [PR1 ](https://github.com/pytorch/pytorch/pull/107127)and [PR2](https://github.com/pytorch/pytorch/pull/107448)

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Comment by FFFrog** [comment]
@ezyang @eellison , please take a look at this, thank you.

**Review by ezyang — APPROVED** [review]
need rebase. Also, it would be much better to fix the ignores rather than ignore them, many of them look easily avoidable

**Pull request closed without merging**
