### PR TITLE
Corrected description of AMSGrad algorithm

### LINKED ISSUE #142323: Inconsistent description of AMSGrad with code
### 📚 The doc issue

https://github.com/pytorch/pytorch/blob/0bd7b7ae58970f565eb22766549ad9d6d2e23fe6/torch/optim/adam.py#L469-L476

In the code, the bias correction term $1-\beta_2^t$ is used after the max operation. However, [the documentation](https://pytorch.org/docs/main/generated/torch.optim.Adam.html#adam) describes that it is used before the max operation:
max operation

### Suggest a potential alternative/fix

amsgrad algo notes

cc @svekars @brycebortree @sekyondaMeta @AlannaBurke @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar

### PR DESCRIPTION
**Pull request by Tony-Y**
Fixes #142323

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
I'm going to approve the workflows, but can you link the updated before and after for one of these once the python docs are built?

**Comment by Tony-Y** [comment]
@janeyx99 Could you let me more clearly know what I do once the python docs are built?

**Comment by Tony-Y** [comment]
The docs have been built.

https://docs-preview.pytorch.org/pytorch/pytorch/142351/generated/torch.optim.Adam.html#adam

https://docs-preview.pytorch.org/pytorch/pytorch/142351/generated/torch.optim.AdamW.html#adamw

**Review by janeyx99 — APPROVED** [review]
Linking was what I was looking for!

**Pull request closed without merging**
