### PR TITLE
fit(...) method of nn.Module class

### PR DESCRIPTION
**Pull request by redradist**
## Description

Usually pytorch has too many boilerplate code for training model.
This PR brings `fit` method that allow to reduce a repeated boilerplate code

Instead of writing each time for new model:
```python
criterion = ...
optimizer = ...
for epoch in range(max_epochs):  # loop over the dataset multiple times
    running_loss = 0.0
    for i, data in enumerate(train_loader, 0):
        inputs, labels = data
    
        optimizer.zero_grad()
    
        logits = model.forward(inputs)
        loss = criterion(logits, labels)
        loss.backward()
    
        optimizer.step()
```
this method allows to write it in following way:
```python
model.fit(train_loader, loss="cross_entropy", optimizer="adam", max_epochs=max_epochs)
```

This function do not require user to use only `fit` method, user still could write code in old style.

For custom model, user could override method `fit`, to add custom training behavior. This would have also one additional benefit, model would encapsulate not only layers, but also training algorithm, which usually not separable from model

### CODE REVIEW

**Review by albanD — CHANGES_REQUESTED** [review]
We explicitly don't want to have this kind of code within the PyTorch core library and expect that ecosystems libraries https://pytorch.org/ecosystem/ do this and they already do this very well. For example https://github.com/Lightning-AI/pytorch-lightning provides this feature much better than what a naive implementation within core could do.

**Comment by redradist** [comment]
> We explicitly don't want to have this kind of code within the PyTorch core library and expect that ecosystems libraries https://pytorch.org/ecosystem/ do this and they already do this very well. For example https://github.com/Lightning-AI/pytorch-lightning provides this feature much better than what a naive implementation within core could do.

@albanD Why not ? This is very simple functionality, I do not think it should be delegated to the whole separate library

**Comment by redradist** [comment]
@albanD I though maybe it would be better to move algorithm of training which in separate class `Trainer`, something like this:
```python
class SimpleTrainer(Trainer):
    def __init__(self,
                 model: nn.Module,
                 loss: str,
                 loss_args: Optional[Dict[str, Any]] = None,
                 optimizer: Union[str, Optimizer] = 'adam',
                 optimizer_args: Optional[Dict[str, Any]] = None,
                 log_interval: Optional[int] = None):
        Trainer.__init__(self, model, log_interval)
        ...

    def fit(self, train_loader: DataLoader, max_epochs: int = 10):
        ...
```

**Comment by redradist** [comment]
> > This is very simple functionality
> 
> I would argue it is not. It requires quite a lot of features to be be complete and a lot of these features are up to personal preferences. You can see that in the large number of trainers like lightning, tnt, ignite, accelerate, etc that are all providing this feature with very different philosophy and approaches. I don't think we want to be in the business to be a tie-breakers between them and expect users to pick the library from this set that best match their personal preference, use case and expectations.


@albanD The issue is that :PyTorch has already sits on different levels of abstractions, but just do not what to complete a high level abstraction concepts because it requires design decisions ...

PyTorch covers the following levels of abstractions:
1) Low-level: supports the high performance neural networks operation
2) PyTorch Tensor implementation
3) High level wrappers around Neural Network training: Autograd, Loos function, Optimizers ...
4) More high level abstraction like nn.Module that wraps Neural Network, -- This implementation is missed -->>> Trainer implementation, that is for me crucial part of this level of abstraction

To make decision, it just require Core Team to gather together and applying core design Patterns to make a decision.

`tnt`, `ignite` - just like crutches, which not try to find solution that fits to architecture, but provide few opinionated variants of implementation

**Pull request closed without merging**
