### PR TITLE
[BE][1/N] Add deprecate msg to Sharded Partial and Replicate Tensor

### PR DESCRIPTION
**Pull request by fduwjj**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #94928

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]
lgtm

**Comment by fduwjj** [comment]
@pytrochbot rebase

**Comment by carmocca** [comment]
This change introduced #95623

**Comment by wanchaol** [comment]
@fduwjj I guess it's probably because we are adding those deprecation msg to the file level, and ShardedTensor API imports them (replicate/partial), I think what we can do to fix this is to move those deprecation msg to the class constructor instead.

We also probably need to check if this is in the 2.0 release already, if so, we should cherry pick the fix

**Pull request closed without merging**
