### PR TITLE
Restore use of OpenMP_EXE_LINKER_FLAGS

### PR DESCRIPTION
**Pull request by ezyang**
It was dropped in #11563, and I don't think we were supposed to drop it.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by ezyang** [comment]
cc @JerryShih

**Comment by JerryShih** [comment]
> @JerryShih Does this mean, for new cmake, I have to check if the variable is set or not? IIRC it's harmless enough to try to use an undefined variable?

@ezyang 
I check the cmake v2.6, 2.8, 3.0 and 3.5. There is no OpenMP_EXE_LINKER_FLAGS var in cmake.
So, we can add the OpenMP_EXE_LINKER_FLAGS back. But I think it's useless.

This comment shows that this pr can't fix the openmp linking problem.
https://github.com/pytorch/pytorch/pull/14569#issuecomment-443278190

**Comment by ezyang** [comment]
@JerryShih We had someone internally who repro'ed the error on cmake 3.13.0. Could you check that one too?

**Comment by JerryShih** [comment]
> @JerryShih We had someone internally who repro'ed the error on cmake 3.13.0. Could you check that one too?

@ezyang 

There is also no OpenMP_EXE_LINKER_FLAGS in cmake 3.13.0-rc3.

Does anyone add the OpenMP_EXE_LINKER_FLAGS var back and resolve the linking problem?

The version:
```
commit 8d70ed5a10362209d265a15d993f319235aea7e5 (HEAD -> v3.13.0-rc3, tag: v3.13.0-rc3)
Author: Brad King <brad.king@kitware.com>
Date:   Wed Nov 7 07:50:43 2018 -0500

    CMake 3.13.0-rc3
```

**Comment by ezyang** [comment]
@li-roy says it didn't solve the problem for him. Back to the drawing board!

**Pull request closed without merging**
