### PR TITLE
[AOTInductor] Rename model_runner to model_container_runner

### PR DESCRIPTION
**Pull request by muchulee8**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #111325
* __->__ #111324

Summary:
We rename the model_runner to model_container_runner to prepare for
adding tests of pure model without container.

Test Plan:
commit itself is a test.

Reviewers:

Subscribers:

Tasks:

Tags:

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @aakhundov @ColinPeppler

### CODE REVIEW

**Review by desertfire — APPROVED** [review]

**Review by chenyang78 — APPROVED** [review]

**Comment by muchulee8** [comment]
@muchulee8 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51375414).

**Pull request closed without merging**
