### PR TITLE
Create Cache for Fusion Reuse in NVFuser in Python Frontend for Primtorch

### PR DESCRIPTION
**Pull request by kevinstephano**
This PR does the following:

- Replaces the `FusionOwner` with a `FusionCache` and `FusionInterface`.  The `FusionCache` is a singleton that contains a cache of Fusions based on the `FusionDefinition`.  It replaces the TorchScript graph caching that looked up a Fusion based on a stringified and canonicalized representation of the TorchScript graph with a prefix tree of statements in the `FusionDefinition`.  The `FusionInterface` is an object that represents a Fusion in python.  It can also query the cache based on id.
- The ability to print out a mechanically derived definition, in python, for the user to use when debugging was added.
- Replaces the python `examples` directory with true python tests under `test/test_nvfuser_frontend.py`.
- Adds a set of C++ tests under the `test` directory to verify the `FusionCache`, `FusionDefinition`, and parts of the `RecordFunctor` child classes.
- Adds a README file to explain how to use the Python Frontend

While there are 3,000+ line edits, the bulk of the changes were repetitive line changes to the python bindings for each operation.

An identical PR to #83267 to avoid tooling issues.

### CODE REVIEW

**Comment by davidberard98** [comment]
(rebased it just to force the pr-sanity-checks check to pull the updated labels so that it will get skipped)

**Comment by davidberard98** [comment]
@kevinstephano  can you rebase this onto 94b67f4cd8dc1ab5f7add5f006f7f3fd988b8ecf ?

**Comment by kevinstephano** [comment]
> @kevinstephano can you rebase this onto [94b67f4](https://github.com/pytorch/pytorch/commit/94b67f4cd8dc1ab5f7add5f006f7f3fd988b8ecf) ?

Updated!

**Comment by kevinstephano** [comment]
Was this PR okay internally @davidberard98 ?

**Comment by davidberard98** [comment]
@kevinstephano I actually don't have a way to repro the failure (it was only failing on windows c++17 builds, and I don't have access to any windows machines). I'm currently asking around to try to find a repro, will update once I figure out whether it's been fixed

**Review by davidberard98 — APPROVED** [review]
LGTM. And it's passing internally.

**Pull request closed without merging**
