### PR TITLE
[c10d] Port queue reduction to C++

### PR DESCRIPTION
**Pull request by goldsborough**
This PR moves the `_queue_reduction` code from Python to C++. It is stacked on top of #9729 and #9805.

For this PR I had to do some more work:
1. Move `nccl::reduce` from `python_nccl.cpp` into `nccl.{h,cpp}`
2. Rewrite the `queue_reduction` function.

I also made a helper to convert `py::object` to a vector of `at::cuda::CUDAStream`, because there were now two places where we needed this.

@apaszke @teng-li @pietern

### CODE REVIEW

**Comment by pietern** [comment]
@mruberry This PR is where we'd add the stream awareness for autograd hooks. I.e. every tensor passed to the queue reduction function must have some associated stream object, or a CUDA event, such that we can synchronize with that prior to flattening.

**Comment by teng-li** [comment]
@goldsborough There are many test failing with this PR. I am gonna close this one and open up a new one.  And I would also like to add some additional stream perf work in the new PR.

**Pull request closed without merging**
