### PR TITLE
Handle meta['val'] for tuple of lists.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99724

Fixes https://github.com/pytorch/pytorch/issues/99356

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]
lgtm. Thanks for the quick fix @ezyang!

**Comment by ezyang** [comment]
@BowenBao do you think you could help diagnose the ONNX failure? Looking at the error message, it sounds like I am now populating meta['val'] with tuple of fake tensor, which beartyped does not understand. Do we need to relax beartype?

**Comment by BowenBao** [comment]
cc @titaiwangms looks like we just need to extend the type annotation to allow the new tuple of faketensors?

**Comment by BowenBao** [comment]
Haven't tried, but hope it unblocks
```diff
diff --git a/torch/onnx/_internal/fx/passes/fx_to_onnxscript.py b/torch/onnx/_internal/fx/passes/fx_to_onnxscript.py
index 91ece351df6..17efa6e085e 100644
--- a/torch/onnx/_internal/fx/passes/fx_to_onnxscript.py
+++ b/torch/onnx/_internal/fx/passes/fx_to_onnxscript.py
@@ -221,6 +221,7 @@ def _fill_tensor_meta(
         torch.SymInt,
         torch.SymFloat,
         List[fake_tensor.FakeTensor],
+        Tuple[fake_tensor.FakeTensor],
     ],
 ):
     """Fill the meta information of onnxscript_values with that from the fx FakeTensor."""

```

**Comment by ezyang** [comment]
Thanks!!

**Pull request closed without merging**
