### PR TITLE
MPS: Add amax and amin Ops with tests 

### PR DESCRIPTION
**Pull request by kulinseth**
* Add amax and amin with tests

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by kulinseth** [comment]
```
======================================================================
[912](https://github.com/pytorch/pytorch/runs/6912900173?check_suite_focus=true#step:9:913)
ERROR [0.007s]: test_dtypes__masked_amin_cuda (__main__.TestCommonCUDA)
[913](https://github.com/pytorch/pytorch/runs/6912900173?check_suite_focus=true#step:9:914)
----------------------------------------------------------------------
[914](https://github.com/pytorch/pytorch/runs/6912900173?check_suite_focus=true#step:9:915)
Traceback (most recent call last):
```
The failure seems unrelated to this change.

**Review by albanD — APPROVED** [review]
Sounds good.
But we should move to generic testing to avoid these one-off version that don't cover most usecases

**Comment by kulinseth** [comment]
> Sounds good.
> But we should move to generic testing to avoid these one-off version that don't cover most usecases

Makes sense.

**Pull request closed without merging**
