### PR TITLE
Allow 64bit indexing for channels-last upsample2d on CUDA

### PR DESCRIPTION
**Pull request by eqy**
#81665

CC @ngimel @ptrblck

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by rtaori** [comment]
Is this included in pytorch nightly yet? I am still not seeing the fix.

**Comment by ngimel** [comment]
Yes should be in the nightlies

**Comment by rtaori** [comment]
I ran `pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu117` as suggested on https://pytorch.org/ and the issue still seems to remain. Do I need to update my cuda binaries?

**Comment by ngimel** [comment]
cc @ptrblck, @eqy

**Comment by eqy** [comment]
@rtaori 

What output do you see when running the test that was checked in as part of this PR? 
```
        x = torch.rand((32, 64, 512, 512), dtype=dtype, device=device)
        out = torch.nn.functional.interpolate(x.to(memory_format=torch.channels_last), scale_factor=2, mode='nearest')
        out_ref = torch.nn.functional.interpolate(x, scale_factor=2, mode='nearest')
        del x
        self.assertTrue(torch.allclose(out, out_ref))
```

**Comment by rtaori** [comment]
```
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> dtype=torch.half
>>> device='cuda:0'
>>> x = torch.rand((32, 64, 512, 512), dtype=dtype, device=device)
>>> out = torch.nn.functional.interpolate(x.to(memory_format=torch.channels_last), scale_factor=2, mode='nearest')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/nlp/anaconda/main/anaconda3/envs/rohan-diffusion/lib/python3.8/site-packages/torch/nn/functional.py", line 3922, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: upsample_nearest_nhwc only supports output tensors with less than INT_MAX elements
>>>
```

**Comment by eqy** [comment]
That seems unexpected as installing a nightly should yield `1.14` in the version; could you check what happens after uninstalling and reinstalling?

**Comment by rtaori** [comment]
Ah, that seems to have fixed it, thanks!

**Comment by Parskatt** [comment]
@eqy This PR only seems to have fixed upsample2d for nearest-neighbour, and not for bilinear etc.
See here:
https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cuda/UpSampleBilinear2d.cu

**Pull request closed without merging**
