### PR TITLE
[export] Add math.* ops to pass base

### LINKED ISSUE #115209: math.ceil and math.floor cannot be exported by ExportedProgram.run_decompositions
### 🐛 Describe the bug

Maybe context: https://github.com/pytorch/pytorch/pull/113982 and https://github.com/pytorch/pytorch/pull/114762

Although both `math.ceil` or `math.floor` can be `torch.export.export`, when the resulting `ExportedProgram` is decomposed by `ep.run_decompositions`, a failure happens. 
Note: No dynamic shape is used in the following repro

```python
import math
import torch

def func(x):
    return (
        torch.tensor([math.ceil(x.item())]),
        torch.tensor([math.floor(x.item())]),
    )

x = torch.randn(1, dtype=torch.float32)
ep = torch.export.export(func, args=(x,))
ep_decomp = ep.run_decompositions()
```

The error is:

```bash
Traceback (most recent call last):
  File "/opt/pytorch/torch/fx/passes/infra/pass_manager.py", line 270, in __call__
    res = fn(module)
          ^^^^^^^^^^
  File "/opt/pytorch/torch/fx/passes/infra/pass_base.py", line 40, in __call__
    res = self.call(graph_module)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_export/passes/add_runtime_assertions_for_constraints_pass.py", line 140, in call
    val = super().call(graph_module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_export/pass_base.py", line 427, in call
    result = self.call_submodule(graph_module, tuple(inputs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_export/pass_base.py", line 390, in call_submodule
    interpreter.run(*inputs_data)
  File "/opt/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
                     ^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_export/pass_base.py", line 231, in run_node
    return super().run_node(n)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/_export/pass_base.py", line 208, in call_function
    raise ExportPassBaseError(f"Unsupported target type: {target}")
torch._export.pass_base.ExportPassBaseError: Unsupported target type: <built-in function floor>

While executing %floor : [num_users=1] = call_function[target=math.floor](args = (%_local_scalar_dense,), kwargs = {})
Original traceback:
  File "/opt/pytorch/test_ceil.py", line 6, in func
    torch.tensor([math.floor(x.item())]),


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pytorch/test_ceil.py", line 12, in <module>
    ep_decomp = ep.run_decompositions()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/export/exported_program.py", line 77, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/export/exported_program.py", line 486, in run_decompositions
    exported_program = exported_program._transform(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/export/exported_program.py", line 496, in _transform
    res = pm(self.graph_module)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pytorch/torch/fx/passes/infra/pass_manager.py", line 296, in __call__
    raise Exception(msg) from e
Exception: An error occurred when running the '_AddRuntimeAssertionsForInlineConstraintsPass' pass after the following passes: []
(ptca) root@e9b784a5c219:/opt/pytorch# 
```

### Versions

main

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

### PR DESCRIPTION
**Pull request by angelayi**
Fixes https://github.com/pytorch/pytorch/issues/115209

### CODE REVIEW

**Review by ydwu4 — APPROVED** [review]
Looks good!

**Comment by zhxchen17** [comment]
@angelayi I guess it's fine to do this but just want to let you know that @tugsbayasgalan subscribed to rewrite the entire pass without pass base which seems a better longer term fix. I feel next time we should stop piling hacks onto export pass base.

**Comment by angelayi** [comment]
@zhxchen17 Yeah, I just wanted to fix the issue first.

**Review by thiagocrepaldi — COMMENTED** [review]
thank you for the test :)

**Comment by thiagocrepaldi** [comment]
@angelayi Have you seen this PR was reverted? I am putting https://github.com/pytorch/pytorch/pull/114762 on hold until this is relanded. Thank you

**Pull request closed without merging**
