### PR TITLE
[inductor] force contiguous layout for implicit fallback

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #140996

Fix https://github.com/pytorch/pytorch/issues/140462 .

Horace found that when we implicitly fallback to eager, some eager kernels may not work correctly if Inductor provide non-contiguous inputs (due to padding etc.). The original issue is found for the backward op of weight_norm. The fix in this PR is a general one: we force inputs to all implicit fallback kernels to be contiguous.

I have to refactor the code a bit to make it work. Previously we apply layout constraint in `GraphLowering.run_node`. We looks for implicit fallback in `call_function`. The problem here is, when we setup the implicit fallback in `call_function` with a layout constraint, we don't have a chance to apply the constraints.. The refactor moves the code that applies layout constraints to `call_function`.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by Chillee** [comment]
Should we force them to be contiguous or force them to follow the FX strides?

**Comment by shunting314** [comment]
> Should we force them to be contiguous or force them to follow the FX strides?

The problem is we don't have the real FX strides. The strides stored in `meta['val']` may be the one after optimization for the bwd graph. 

Richard also mentioned that having the real eager strides is needed for custom-op. That gives use more motivation to pass the real eager strides to Inductor.

**Comment by Chillee** [comment]
@shunting314 If that's true then we need to avoid changing eager strides I think haha.

**Comment by shunting314** [comment]
> If that's true then we need to avoid changing eager strides I think haha.

But we should normally be free to change the strides of saved activations since they are not user visible. Keeping them following eager strides may be too restrictive and leaves little padding/layout-optimization opportunities.

**Comment by shunting314** [comment]
@pytorchbot merge -f 

Line error for nested tensors is unrelated.

**Comment by zou3519** [comment]
Btw, by default we want custom operators to match their strides in eager mode. Forcing .contiguous() is not the best

**Pull request closed without merging**
