### PR TITLE
Add prelu into Autocast CPU whitelist

### LINKED ISSUE #95365: prelu: type promoting not supported
### 🐛 Describe the bug

In the **latest master**, when runnning `vnet` model in `bf16` with `autocast`, it will got a RuntimeError:
```
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    train.main(params, args)
  File "/tmp/OOB-PyTorch-BF16-Inference-Weekly/241/pytorch-models/PT/vnet.pytorch/train.py", line 318, in main
    inference(params, args, inferLoader, model)
  File "/tmp/OOB-PyTorch-BF16-Inference-Weekly/241/pytorch-models/PT/vnet.pytorch/train.py", line 94, in inference
    model(data)
  File "/localdisk/mengfeil/miniconda3/envs/pytorch-nightly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/localdisk/mengfeil/miniconda3/envs/pytorch-nightly/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs, **kwargs)
  File "/localdisk/mengfeil/miniconda3/envs/pytorch-nightly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/OOB-PyTorch-BF16-Inference-Weekly/241/pytorch-models/PT/vnet.pytorch/vnet.py", line 178, in forward
    out32 = self.down_tr32(out16)
  File "/localdisk/mengfeil/miniconda3/envs/pytorch-nightly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/OOB-PyTorch-BF16-Inference-Weekly/241/pytorch-models/PT/vnet.pytorch/vnet.py", line 86, in forward
    down = self.relu1(self.bn1(self.down_conv(x)))
  File "/localdisk/mengfeil/miniconda3/envs/pytorch-nightly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/localdisk/mengfeil/miniconda3/envs/pytorch-nightly/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1304, in forward
    return F.prelu(input, self.weight)
RuntimeError: prelu: Type promoting not supported. Got BFloat16 and Float
```
### Reproduce
I select out the mininal unit test, as follows:
```
  1 import torch
  2 m = torch.nn.PReLU()
  3 a = torch.randn(2).to(torch.bfloat16)
  4 with torch.cpu.amp.autocast(enabled=True, dtype=torch.bfloat16):
  5     output = m(a)

```

### Versions

Collecting environment information...
PyTorch version: 2.0.0a0+gite5c2a35
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 8 (Core) (x86_64)
GCC version: (GCC) 9.2.1 20191120 (Red Hat 9.2.1-2)
Clang version: 11.0.1 (Red Hat 11.0.1-1.module_el8.4.0+966+2995ef20)
CMake version: version 3.22.4
Libc version: glibc-2.28

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.16.0-rc1-intel-next-00543-g5867b0a2a125-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              224
On-line CPU(s) list: 0-223
Thread(s) per core:  2
Core(s) per socket:  56
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               143
Model name:          Genuine Intel(R) CPU 0000%@
Stepping:            3
CPU MHz:             1900.000
CPU max MHz:         3700.0000
CPU min MHz:         800.0000
BogoMIPS:            3800.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            2048K
L3 cache:            107520K
NUMA node0 CPU(s):   0-55,112-167
NUMA node1 CPU(s):   56-111,168-223
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm avx512_vp2intersect md_clear serialize tsxldtrk pconfig arch_lbr avx512_fp16 amx_tile flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] torch==2.0.0a0+gitbc438af
[pip3] torch-ccl==1.2.0+44e473a
[conda] mkl                       2022.0.1           h06a4308_117
[conda] mkl-include               2022.0.1           h06a4308_117
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] torch                     2.0.0a0+gitbc438af           dev_0    <develop>
[conda] torch-ccl                 1.2.0+44e473a            pypi_0    pypi

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel

### PR DESCRIPTION
**Pull request by yanbing-j**
### Motivation
Add `prelu` to lower precision cast policy on AutocastCPU to fix https://github.com/pytorch/pytorch/issues/95365 :

Before: Within the scope of torch.cpu.amp.autocast(dtype=torch.bfloat16) , `prelu` cannot address the scenario of different datatypes of `input` and `weight`, will get a RuntimeError. This scenario is common in autocast, e.g, with `autocast` to `bf16`, if the `op` before `prelu` comes out a `bf16` output, which is the input of `prelu`, and `prelu's` weight is `fp32`, then it will get a RuntimeError.

After: Within the scope of torch.cpu.amp.autocast(dtype=torch.bfloat16) , prelu be forced to run with `bf16` data type.

Before https://github.com/pytorch/pytorch/pull/91238, when input is `bf16`, weight will be forced to cast to `bf16`.  After https://github.com/pytorch/pytorch/pull/91238, this kind of test scenario will raise a RuntimeError. There is no precision loss since the workable one is also casting to `bf16`.

And this also alighs with Autocast CUDA whitelist.

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by leslie-fang-intel** [comment]
@yanbing-j May I kindly know why we have to put `prelu` into whitelist? How much will it affect some model's performance?

**Comment by yanbing-j** [comment]
> @yanbing-j May I kindly know why we have to put `prelu` into whitelist? How much will it affect some model's performance?

I have updated the description, which will answer your questions.

**Comment by leslie-fang-intel** [comment]
Thanks for the comments. It looks like `PReLU` should support mixed precision input like `BN` instead of add it into whitellist?

**Comment by yanbing-j** [comment]
This is also align with CUDA whitelist.
Since https://github.com/pytorch/pytorch/pull/91238 rewrites all the code of `PReLU`, and merge CPU and CUDA code together, I think we don't need extra effert to split CPU and GUDA code to add the mixed precision support.

**Review by ngimel — APPROVED** [review]

**Review by jgong5 — COMMENTED** [review]
I'm wondering what is the design philosophy of adding ops to the autocast whitelist. My understanding is that we only explicitly downcast ops for those that we know they are very likely get perf benefit from low-precision compute even if there is downcast cost. These  compute-intensive dot-product ops that have HW acceleration support. From the autocast lists of CPU and CUDA, it seems "prelu" is the only exception. In my opinion, "prelu" is more like batch-norm and better fit "fall-through" policy instead.

Can we do type conversion on weights inside prelu just like batch-norm without throwing errors on type mismatch? @lezcano

**Comment by lezcano** [comment]
I didn't add support for type promotion in prelu in that PR just because it's a bit annoying to get that right so when implementing 2nd order derivatives by hand.
Should I implement this within the operation itself, or should this be done at the autocast level? @ngimel

**Comment by ngimel** [comment]
`prelu` doesn't follow standard type promotion rules, so it's indeed cumbersome to add the support at the op level. I don't think there's much harm done when prelu is just added to autocast allowlist (at worst an extra conversion of activations to low precision, but likely not that, because activations typically come out in low precision from the preceding gemm/convolution)

**Review by lezcano — APPROVED** [review]
Let's go with autocast then as per https://github.com/pytorch/pytorch/pull/95366#issuecomment-1446787578

**Review by leslie-fang-intel — APPROVED** [review]

**Pull request closed without merging**
