### PR TITLE
[Traceable FSDP2][3/n] Check all_gather_work is distributed_c10d.Work before calling .wait()

### PR DESCRIPTION
**Pull request by yf225**
In FSDP2, we have this:
```python
if all_gather_work is not None:  # async op
    all_gather_work.wait()
```

In eager, there are only two possible values for `all_gather_work`:
1. `distributed_c10d.Work` object (when `async_op=True`)
2. `None` (when `async_op=False`)

So the existing `if` statement is sufficient for eager mode.

In compile, there is one additional possible value for `all_gather_work` which is `FakeTensor` object (not None), because we return regular tensor for collective call in compile mode. If we use the existing `if` statement as-is, we will always call `.wait()` on `all_gather_work`, which is not the same semantics as eager.

There are a few ways to fix this:
Option 1: Properly support `distributed_c10d.Work` in Dynamo. This is the best long-term fix but it will take much more time to make it work.

Option 2: Allow calling `.wait()` on FakeTensor in compile mode (and just return None there) - this seems hacky because FakeTensor wouldn't normally have this method.

Option 3: Check whether `all_gather_work` is `distributed_c10d.Work` before calling `.wait()` on it. **<-- This PR**

Option 3 is chosen in this PR because it seems to also make the eager program semantics clearer (we don't need to think about whether `all_gather_work` can be `.wait()` on in all scenarios, as long as we know `distributed_c10d.Work` can be waited on).

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @chauhang

### CODE REVIEW

**Comment by awgu** [comment]
@yf225 Sorry for the confusion. The use case for that `async_op=True` code path in eager mode has not been exposed out to the user yet. This would happen in https://github.com/pytorch/pytorch/pull/120952. In that case, I think the `all_gather_work` should be a `distributed_c10d.Work` object.

I am not strongly opinionated against changing the `if` statement to exclude the `FakeTensor` case though.

**Comment by yf225** [comment]
> @yf225 Sorry for the confusion. The use case for that `async_op=True` code path in eager mode has not been exposed out to the user yet. This would happen in #120952. In that case, I think the `all_gather_work` should be a `distributed_c10d.Work` object.
> 
> I am not strongly opinionated against changing the `if` statement to exclude the `FakeTensor` case though.

@awgu Curious for the `async_op=True` case, should `all_gather_work` be a `AsyncCollectiveTensor` object instead? It seems all collective functions in this file returns `maybe_wrap_tensor(...)` https://github.com/pytorch/pytorch/blob/a2327d203b27e1aca03e7bf4d226350da3c90b50/torch/distributed/_functional_collectives.py#L301 and `maybe_wrap_tensor(...)` returns AsyncCollectiveTensor when not under compile: https://github.com/pytorch/pytorch/blob/a2327d203b27e1aca03e7bf4d226350da3c90b50/torch/distributed/_functional_collectives.py#L779

**Comment by awgu** [comment]
@yf225 I think you are only looking at functional collectives, but c10d collectives (e.g. `torch.distributed_c10d.all_gather_into_tensor`) do not use `AsyncCollectiveTensor`.

**Comment by yf225** [comment]
> @yf225 I think you are only looking at functional collectives, but c10d collectives (e.g. `torch.distributed_c10d.all_gather_into_tensor`) do not use `AsyncCollectiveTensor`.

@awgu Ah I see, thanks! Updated the PR to check `distributed_c10d.Work` instead.

**Review by awgu — APPROVED** [review]

**Pull request closed without merging**
