### PR TITLE
[Docs] Optimize parameter description to declare allowed type (1/N)

### PR DESCRIPTION
**Pull request by zeshengzong**
Inspired by issue #137422 and #103847

Optimize method parameter types in docs to given users a more clear about what expected to pass to methods.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec @albanD

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks for this!

**Comment by albanD** [comment]
Can you fix the lint please?

**Comment by zeshengzong** [comment]
> Can you fix the lint please?

@albanD Sorry about that, I think it works now :D

**Pull request closed without merging**
