### PR TITLE
Fix typo under docs directory

### PR DESCRIPTION
**Pull request by kiszk**
This PR fixes typo in `.rst` files under `docs` directory

### CODE REVIEW

**Review by drisspg — APPROVED** [review]
@pytorchbot merge

**Comment by kit1980** [comment]
Looks like this was already fixed in https://github.com/pytorch/pytorch/pull/92762

**Comment by kiszk** [comment]
Sorry for overlooking the status of this PR. Yes, these changes were already fixed. So, I agree with closing this PR.
Thank you.

**Pull request closed without merging**
