### PR TITLE
Fix `recursive_store` for smaller elementSize

### PR DESCRIPTION
**Pull request by malfet**
### <samp>🤖 Generated by Copilot at 8cbc54f</samp>

Add support for symbolic integers of different sizes in `tensor_new.cpp`. Use a switch statement to cast them to the appropriate fixed-width integer type. 

Fixes crash reported in https://github.com/pytorch/pytorch/issues/100455

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Comment by ngimel** [comment]
How can SymInts have different elementSize? cc @ezyang

**Comment by malfet** [comment]
> How can SymInts have different elementSize? cc @ezyang

SymInt size is the same, but when it's persisted into a byte tensor it should update only one element, not all of them. 

And we probably need similar change to SymFloats (we assume they are double and are stored to scalars)

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
