### PR TITLE
[inductor] Add test_ops_gradients running with inductor

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89792

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
How much does this increase the test time for inductor?

**Comment by desertfire** [comment]
> How much does this increase the test time for inductor?

This increases the `inductor` shard test time from 30min to 38min (https://github.com/pytorch/pytorch/actions/runs/3594587132/jobs/6053461790).

**Review by janeyx99 — APPROVED** [review]
Seems fine, but cc'ing @clee2000 @huydhn regarding the shard increase time as a heads up

**Review by clee2000 — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Pull request closed without merging**
