### PR TITLE
Update nightly wheels to ROCm5.0 for GHA

### PR DESCRIPTION
**Pull request by KyleCZH**
Depends on https://github.com/pytorch/builder/pull/941

Signed-off-by: Kyle Chen <kylechen@amd.com>

@jithunnair-amd @jeffdaily

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@jithunnair-amd can you please rebase your PR?

**Comment by KyleCZH** [comment]
> @KyleCZH please rebase your branch and regenerate the conflicting `.github/workflows/generated-linux-binary-manywheel.yml` file

rebased

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
