### PR TITLE
[torchgen][RFC] Override tensor namespace and container namespace

### PR DESCRIPTION
**Pull request by larryliu0820**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #81844

This PR adds support to let torchgen user to override tensor namespace from `at` to something else. Same for `c10` namespace.

Differential Revision: [D41293359](https://our.internmc.facebook.com/intern/diff/D41293359)

### CODE REVIEW

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41293359).

**Comment by ezyang** [comment]
what's the status on this?

**Comment by larryliu0820** [comment]
> what's the status on this?

Trying to figure out how to workaround the missing CLA issue... I ran `ghexport` several times from internal repo, since the email is unset there CLA doesn't like what I'm doing. Worst case I'll start a new PR.

**Comment by larryliu0820** [comment]
#89081 is the new one

**Pull request closed without merging**
