### PR TITLE
Change list striding kernel implementation to handle optional integers

### PR DESCRIPTION
**Pull request by tugsbayasgalan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #58537 List striding with arbitrary step size
* **#58536 Change list striding kernel implementation to handle optional integers**

Summary:
In order to update `aten::slice` to take optional start and end parameters, we first make sure the underlying kernel implementation can handle optional integer paraemeters for compatibily reasons. For example, if the model is scripted with newer `aten::slice` operator, the old runtime would fail because it would expect the inputs to be integer. 

Differential Revision: [D28531720](https://our.internmc.facebook.com/intern/diff/D28531720)

### CODE REVIEW

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28531720).

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28531720).

**Review by gmagogsfm — CHANGES_REQUESTED** [review]

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28531720).

**Review by gmagogsfm — APPROVED** [review]
Please wait for 2 weeks after this PR lands to land follow-up diff.

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28531720).

**Pull request closed without merging**
