### PR TITLE
[complex32] conv1d, conv2d : enable test

### PR DESCRIPTION
**Pull request by kshitij12345**
Ref: #74537

### CODE REVIEW

**Comment by kshitij12345** [comment]
Without the changes in `test_meta` was getting the following error:

Ref: https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17278


<details>

<summary>Log (not much readable better to check CI link) </summary>

```

======================================================================
[17278](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17279)
ERROR [0.150s]: test_dispatch_meta_nn_functional_conv1d_cuda_complex32 (__main__.TestMetaCUDA)
[17279](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17280)
----------------------------------------------------------------------
[17280](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17281)
Traceback (most recent call last):
[17281](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17282)
  File "test_meta.py", line 437, in run_meta_crossref
[17282](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17283)
    meta_rs = func(*meta_args, **meta_kwargs)
[17283](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17284)
  File "/opt/conda/lib/python3.7/site-packages/torch/_ops.py", line 48, in __call__
[17284](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17285)
    return self._op(*args, **kwargs or {})
[17285](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17286)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/_python_dispatch.py", line 69, in wrapped
[17286](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17287)
    return f(self, *args, **kwargs)
[17287](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17288)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/_python_dispatch.py", line 159, in __torch_dispatch__
[17288](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17289)
    return func(*args, **kwargs)
[17289](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17290)
  File "/opt/conda/lib/python3.7/site-packages/torch/_ops.py", line 48, in __call__
[17290](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17291)
    return self._op(*args, **kwargs or {})
[17291](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17292)
NotImplementedError: convolution_overrideable not implemented. You are likely triggering this with tensor backend other than CPU/CUDA/MKLDNN, if this is intended, please use TORCH_LIBRARY_IMPL to override this function 
[17292](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17293)

[17293](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17294)
The above exception was the direct cause of the following exception:
[17294](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17295)

[17295](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17296)
Traceback (most recent call last):
[17296](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17297)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1808, in wrapper
[17297](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17298)
    method(*args, **kwargs)
[17298](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17299)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 390, in instantiated_test
[17299](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17300)
    raise rte
[17300](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17301)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
[17301](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17302)
    result = test(self, **param_kwargs)
[17302](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17303)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 786, in test_wrapper
[17303](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17304)
    return test(*args, **kwargs)
[17304](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17305)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 943, in only_fn
[17305](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17306)
    return fn(slf, *args, **kwargs)
[17306](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17307)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 807, in wrapper
[17307](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17308)
    fn(*args, **kwargs)
[17308](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17309)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1158, in wrapper
[17309](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17310)
    fn(*args, **kwargs)
[17310](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17311)
  File "test_meta.py", line 1099, in test_dispatch_meta
[17311](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17312)
    expected = func(*args, **kwargs)
[17312](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17313)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/_python_dispatch.py", line 69, in wrapped
[17313](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17314)
    return f(self, *args, **kwargs)
[17314](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17315)
  File "test_meta.py", line 1059, in __torch_dispatch__
[17315](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17316)
    device_type=self.device_type,
[17316](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17317)
  File "test_meta.py", line 452, in run_meta_crossref
[17317](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17318)
    )""") from e
[17318](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17319)
RuntimeError: failed to run: aten.convolution.default(
[17319](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17320)
*(tensor(..., device='meta', size=(1, 3, 4), dtype=torch.float16) stride=(24, 8, 2), tensor(..., device='meta', size=(3, 3, 3), dtype=torch.float16) stride=(18, 6, 2), tensor(..., device='meta', size=(3,), dtype=torch.float16) stride=(2,), [2], [2], [1], False, [0], 1),
[17320](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17321)
**{}
[17321](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17322)
)
[17322](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17323)

[17323](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17324)
======================================================================
[17324](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17325)
ERROR [0.198s]: test_dispatch_meta_nn_functional_conv2d_cuda_complex32 (__main__.TestMetaCUDA)
[17325](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17326)
----------------------------------------------------------------------
[17326](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17327)
Traceback (most recent call last):
[17327](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17328)
  File "test_meta.py", line 437, in run_meta_crossref
[17328](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17329)
    meta_rs = func(*meta_args, **meta_kwargs)
[17329](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17330)
  File "/opt/conda/lib/python3.7/site-packages/torch/_ops.py", line 48, in __call__
[17330](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17331)
    return self._op(*args, **kwargs or {})
[17331](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17332)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/_python_dispatch.py", line 69, in wrapped
[17332](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17333)
    return f(self, *args, **kwargs)
[17333](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17334)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/_python_dispatch.py", line 159, in __torch_dispatch__
[17334](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17335)
    return func(*args, **kwargs)
[17335](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17336)
  File "/opt/conda/lib/python3.7/site-packages/torch/_ops.py", line 48, in __call__
[17336](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17337)
    return self._op(*args, **kwargs or {})
[17337](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17338)
NotImplementedError: convolution_overrideable not implemented. You are likely triggering this with tensor backend other than CPU/CUDA/MKLDNN, if this is intended, please use TORCH_LIBRARY_IMPL to override this function 
[17338](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17339)

[17339](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17340)
The above exception was the direct cause of the following exception:
[17340](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17341)

[17341](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17342)
Traceback (most recent call last):
[17342](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17343)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1808, in wrapper
[17343](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17344)
    method(*args, **kwargs)
[17344](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17345)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 390, in instantiated_test
[17345](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17346)
    raise rte
[17346](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17347)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
[17347](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17348)
    result = test(self, **param_kwargs)
[17348](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17349)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 786, in test_wrapper
[17349](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17350)
    return test(*args, **kwargs)
[17350](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17351)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 943, in only_fn
[17351](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17352)
    return fn(slf, *args, **kwargs)
[17352](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17353)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 807, in wrapper
[17353](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17354)
    fn(*args, **kwargs)
[17354](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17355)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1158, in wrapper
[17355](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17356)
    fn(*args, **kwargs)
[17356](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17357)
  File "test_meta.py", line 1099, in test_dispatch_meta
[17357](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17358)
    expected = func(*args, **kwargs)
[17358](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17359)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/_python_dispatch.py", line 69, in wrapped
[17359](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17360)
    return f(self, *args, **kwargs)
[17360](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17361)
  File "test_meta.py", line 1059, in __torch_dispatch__
[17361](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17362)
    device_type=self.device_type,
[17362](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17363)
  File "test_meta.py", line 452, in run_meta_crossref
[17363](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17364)
    )""") from e
[17364](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17365)
RuntimeError: failed to run: aten.convolution.default(
[17365](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17366)
*(tensor(..., device='meta', size=(1, 3, 4, 4), dtype=torch.float16) stride=(96, 32, 8, 2), tensor(..., device='meta', size=(3, 3, 3, 3), dtype=torch.float16) stride=(54, 18, 6, 2), tensor(..., device='meta', size=(3,), dtype=torch.float16) stride=(2,), [2, 2], [2, 2], [1, 1], False, [0, 0], 1),
[17366](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17367)
**{}
[17367](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17368)
)
[17368](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17369)

[17369](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17370)
======================================================================
[17370](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17371)
ERROR [0.012s]: test_meta_nn_functional_conv1d_cuda_complex32 (__main__.TestMetaCUDA)
[17371](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17372)
----------------------------------------------------------------------
[17372](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17373)
Traceback (most recent call last):
[17373](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17374)
  File "test_meta.py", line 437, in run_meta_crossref
[17374](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17375)
    meta_rs = func(*meta_args, **meta_kwargs)
[17375](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17376)
  File "/opt/conda/lib/python3.7/site-packages/torch/overrides.py", line 1737, in wrapped
[17376](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17377)
    return f(self, *args, **kwargs)
[17377](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17378)
  File "/opt/conda/lib/python3.7/site-packages/torch/overrides.py", line 1830, in __torch_function__
[17378](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17379)
    return func(*args, **kwargs)
[17379](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17380)
NotImplementedError: convolution_overrideable not implemented. You are likely triggering this with tensor backend other than CPU/CUDA/MKLDNN, if this is intended, please use TORCH_LIBRARY_IMPL to override this function 
[17380](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17381)

[17381](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17382)
The above exception was the direct cause of the following exception:
[17382](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17383)

[17383](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17384)
Traceback (most recent call last):
[17384](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17385)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1808, in wrapper
[17385](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17386)
    method(*args, **kwargs)
[17386](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17387)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 390, in instantiated_test
[17387](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17388)
    raise rte
[17388](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17389)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
[17389](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17390)
    result = test(self, **param_kwargs)
[17390](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17391)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 786, in test_wrapper
[17391](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17392)
    return test(*args, **kwargs)
[17392](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17393)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 943, in only_fn
[17393](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17394)
    return fn(slf, *args, **kwargs)
[17394](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17395)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 807, in wrapper
[17395](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17396)
    fn(*args, **kwargs)
[17396](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17397)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1158, in wrapper
[17397](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17398)
    fn(*args, **kwargs)
[17398](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17399)
  File "test_meta.py", line 1083, in test_meta
[17399](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17400)
    expected = func(*args, **kwargs)
[17400](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17401)
  File "/opt/conda/lib/python3.7/site-packages/torch/overrides.py", line 1737, in wrapped
[17401](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17402)
    return f(self, *args, **kwargs)
[17402](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17403)
  File "test_meta.py", line 780, in __torch_function__
[17403](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17404)
    kwargs, dtype=self.dtype, device_type=self.device_type
[17404](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17405)
  File "test_meta.py", line 452, in run_meta_crossref
[17405](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17406)
    )""") from e
[17406](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17407)
RuntimeError: failed to run: torch.nn.functional.conv1d(
[17407](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17408)
*(tensor(..., device='meta', size=(1, 3, 4), dtype=torch.complex32) stride=(12, 4, 1), tensor(..., device='meta', size=(3, 3, 3), dtype=torch.complex32) stride=(9, 3, 1), tensor(..., device='meta', size=(3,), dtype=torch.complex32) stride=(1,)),
[17408](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17409)
**{'stride': (2,), 'padding': 2, 'groups': 1}
[17409](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17410)
)
[17410](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17411)

[17411](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17412)
======================================================================
[17412](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17413)
ERROR [0.012s]: test_meta_nn_functional_conv2d_cuda_complex32 (__main__.TestMetaCUDA)
[17413](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17414)
----------------------------------------------------------------------
[17414](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17415)
Traceback (most recent call last):
[17415](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17416)
  File "test_meta.py", line 437, in run_meta_crossref
[17416](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17417)
    meta_rs = func(*meta_args, **meta_kwargs)
[17417](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17418)
  File "/opt/conda/lib/python3.7/site-packages/torch/overrides.py", line 1737, in wrapped
[17418](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17419)
    return f(self, *args, **kwargs)
[17419](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17420)
  File "/opt/conda/lib/python3.7/site-packages/torch/overrides.py", line 1830, in __torch_function__
[17420](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17421)
    return func(*args, **kwargs)
[17421](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17422)
NotImplementedError: convolution_overrideable not implemented. You are likely triggering this with tensor backend other than CPU/CUDA/MKLDNN, if this is intended, please use TORCH_LIBRARY_IMPL to override this function 
[17422](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17423)

[17423](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17424)
The above exception was the direct cause of the following exception:
[17424](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17425)

[17425](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17426)
Traceback (most recent call last):
[17426](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17427)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1808, in wrapper
[17427](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17428)
    method(*args, **kwargs)
[17428](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17429)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 390, in instantiated_test
[17429](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17430)
    raise rte
[17430](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17431)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
[17431](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17432)
    result = test(self, **param_kwargs)
[17432](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17433)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 786, in test_wrapper
[17433](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17434)
    return test(*args, **kwargs)
[17434](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17435)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 943, in only_fn
[17435](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17436)
    return fn(slf, *args, **kwargs)
[17436](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17437)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 807, in wrapper
[17437](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17438)
    fn(*args, **kwargs)
[17438](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17439)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1158, in wrapper
[17439](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17440)
    fn(*args, **kwargs)
[17440](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17441)
  File "test_meta.py", line 1083, in test_meta
[17441](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17442)
    expected = func(*args, **kwargs)
[17442](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17443)
  File "/opt/conda/lib/python3.7/site-packages/torch/overrides.py", line 1737, in wrapped
[17443](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17444)
    return f(self, *args, **kwargs)
[17444](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17445)
  File "test_meta.py", line 780, in __torch_function__
[17445](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17446)
    kwargs, dtype=self.dtype, device_type=self.device_type
[17446](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17447)
  File "test_meta.py", line 452, in run_meta_crossref
[17447](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17448)
    )""") from e
[17448](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17449)
RuntimeError: failed to run: torch.nn.functional.conv2d(
[17449](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17450)
*(tensor(..., device='meta', size=(1, 3, 4, 4), dtype=torch.complex32) stride=(48, 16, 4, 1), tensor(..., device='meta', size=(3, 3, 3, 3), dtype=torch.complex32) stride=(27, 9, 3, 1), tensor(..., device='meta', size=(3,), dtype=torch.complex32) stride=(1,)),
[17450](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17451)
**{'stride': (2, 2), 'padding': 2, 'groups': 1}
[17451](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17452)
)
[17452](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17453)

[17453](https://github.com/pytorch/pytorch/runs/6523878265?check_suite_focus=true#step:7:17454)

```
</details>

**Review by anjali411 — APPROVED** [review]
LGTM

**Pull request closed without merging**
