### PR TITLE
deprecating nvfuser c++ API

### PR DESCRIPTION
**Pull request by jjsjann123**
deprecating nvfuser c++ API

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Comment by jjsjann123** [comment]
bumping base branch. Hopefully the noisy rocm failure would go away.

**Comment by jjsjann123** [comment]
rocm failure looks persistent. Now I'm wondering if I did anything wrong. I'll take another look

**Comment by jeffdaily** [comment]
We're working on the ROCm CI failures.  Our CI was/is in unstable status so was not a blocking CI signal and there have been a number of PRs merged that further broke ROCm CI.  We have a fix for 

TestQuantizePT2EQAT.test_qat_conv_bn_relu_fusion_cuda

But working on the inductor test hang. 

I don't think your PR is to blame here.  Thanks for actually paying attention to the signal, though.  I really appreciate it.  Helps us a lot.

**Comment by jjsjann123** [comment]
> We're working on the ROCm CI failures. Our CI was/is in unstable status so was not a blocking CI signal and there have been a number of PRs merged that further broke ROCm CI. We have a fix for
> 
> TestQuantizePT2EQAT.test_qat_conv_bn_relu_fusion_cuda
> 
> But working on the inductor test hang.
> 
> I don't think your PR is to blame here. Thanks for actually paying attention to the signal, though. I really appreciate it. Helps us a lot.

Awesome. Thanks for comfirming this one.
In that sense this PR is good to go. Pinging @davidberard98 for a review

**Review by davidberard98 — APPROVED** [review]

**Comment by NicolasHug** [comment]
Hi @jjsjann123 @davidberard98 , this PR seems to be causing a lot of warnings in the torchvision test suite (https://github.com/pytorch/vision/issues/8030), even on tests that do not involve CUDA at all. Could you please take a look and advise on how to proceed to remove these warnings? Thanks!

**Comment by jjsjann123** [comment]
ha. sorry about the excessive warning. I'll switch to TORCH_WARN_ONCE instead.

**Pull request closed without merging**
