### PR TITLE
feat(optim): Add adadelta multi_tensor support for complex, with `has_complex` shortcut

### LINKED ISSUE #110606: [optim]: `NAdam`, `RAdam` and `_multi_tensor_adadelta` do not support complex types
### 🐛 Describe the bug

It is trivial to add support (by viewing params, grads and intermediates as real via `view_as_real`), but somehow, unlike other optim classes, they inconsistently do not support complex.

### Versions

main

### Tasks
- [ ] adadelta multitensor
- [ ] NAdam
- [ ] RAdam

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

### PR DESCRIPTION
**Pull request by jon-chuang**
Partial fix: https://github.com/pytorch/pytorch/issues/110606

More on `has_complex` shortcut: https://github.com/pytorch/pytorch/pull/110613#issuecomment-1749314805

CC: @janeyx99, @mlazos, @lezcano

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
Given that the pattern is the same in every optimiser, perhaps we want to factor it out into its own aux function?

**Comment by lezcano** [comment]
@jon-chuang what about https://github.com/pytorch/pytorch/pull/110631#pullrequestreview-1660938055?

**Comment by jon-chuang** [comment]
Hello, @lezcano I tried to respond at https://github.com/pytorch/pytorch/pull/110635#discussion_r1348136593

As mentioned, we are limited by the functional APIs. Given that it is specific to each optimizer and only used in multi_tensor case, I don't think it makes sense to have an aux function as there will be no shared logic nor object-oriented abstraction

**Comment by jon-chuang** [comment]
Anw, I might have some idea about what you mean, I'll ping you once the PR is up.

**Comment by lezcano** [comment]
I was thinking of something along the lines of
```python
def view_as_real(*params):
    assert len(params) > 0
    n = len(params[0])
    assert all(len(p) == n for p in params)

    for i in range(n):
        p = params[0][i]
        if torch.is_complex(p):
            for p_list in params:
                p_list[i] = torch.view_as_real(p_list[i])
```

If there can be empty lists, you can filter them out first, of course.

**Pull request closed without merging**
