### PR TITLE
[EASY] Add complex dtypes to partitioner

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96297

Also, delete some redundant dtype setting.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
Would probably be good to refactor this out to a separate utility at some point.

**Comment by ezyang** [comment]
@Chillee It would be better if these properties were just on the dtype objects...

**Pull request closed without merging**
