### PR TITLE
Adding Wunused-lambda-capture to Clang build flags

### PR DESCRIPTION
**Pull request by osalpekar**
Add `-Wunused-lambda-capture` to clang build flags to better align internal and OSS build systems. This flag is not supported in gcc so only adding for clang builds.

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!

**Comment by osalpekar** [comment]
The trunk failure is unrelated (gcc job failed, while this change only touches clang)

**Comment by osalpekar** [comment]
@huydhn Any ideas how we can make this merge successfully? I see one failure and it is unrelated

**Pull request closed without merging**
