### PR TITLE
add amp tests

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #85471
* __->__ #85434

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'This seems to cause memory leak in TestFakeTensorCUDA.test_fake_crossref_backward_amp_linalg_lstsq_grad_oriented_cuda_float32 and breaks trunk' -c weird

Here are some failed jobs for your reference

* https://hud.pytorch.org/pytorch/pytorch/commit/8dd45424eaf4ab39c8723efdec91a269c7eb9448
* https://hud.pytorch.org/pytorch/pytorch/commit/a876432aea11fd2c6e11b8397f4f89a30cd1e8ba
* https://hud.pytorch.org/pytorch/pytorch/commit/879ae45230d98e50250e9f8e704d78b5973bf227
* https://hud.pytorch.org/pytorch/pytorch/commit/913f5784d74bb69eff12b1cf9ac8c3d222750411

It seems to happen with both CUDA 11.6 and 10.2, and it's flaky AFAIK

**Pull request closed without merging**
