### PR TITLE
[export] Don't save example_inputs for now.

### PR DESCRIPTION
**Pull request by zhxchen17**
Summary:

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by angelayi — APPROVED** [review]
thanks! cc @qihqi that we won't serialize the arguments for now, as we haven't decided how to serialize the tensors yet.

**Comment by qihqi** [comment]
I am Ok with not saving it. 

Would appreciate more if the rename (original_traced_args -> example_inputs) didn't happen; but it fine either way. Please don't rename it again. Thanks.

**Pull request closed without merging**
