### PR TITLE
.github: Move windows back to default directory

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #64962

Moves windows builds / tests back to the default directory. Previously
we had moved them because checkout would sometimes fail due to file
handlers still being open on the working directory.

Moving back to the default directory also has the added bonus of sccache
working again so here's to hoping that this doesn't have any adverse
affects

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @ezyang @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra

Differential Revision: [D31250072](https://our.internmc.facebook.com/intern/diff/D31250072)

### CODE REVIEW

**Comment by seemethere** [comment]
Related issues:
* https://github.com/pytorch/pytorch/issues/61684
* https://github.com/pytorch/pytorch/issues/63036

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31250072).

**Review by zhouzhuojie — APPROVED** [review]
yes, let's try it out!

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31250072).

**Pull request closed without merging**
