### PR TITLE
[ROCm] Update HIP_VERSION to TORCH_HIP_VERSION

### PR DESCRIPTION
**Pull request by pruthvistony**
- HIP_VERSION semantic versioning will change in ROCm4.3. The changes essentially remove the dependency on HIP_VERSION provided in the hip header to keep code compatible with older and newer versions of ROCm.
- TORCH_HIP_VERSION is derived from HIP_VERSION_MAJOR and HIP_VERSION_MINOR

### CODE REVIEW

**Comment by pruthvistony** [comment]
@jeffdaily @jithunnair-amd 
Please review the changes.

**Comment by jeffdaily** [comment]
@pruthvistony need to fix lint checks.

**Comment by pruthvistony** [comment]
> @pruthvistony need to fix lint checks.

The lint errors were in different files and it is fixed by a different PR. So I have re-based my changes.

**Comment by pruthvistony** [comment]
The failing test - ci/circleci: pytorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_test2
seems flaky, it is failing in other open PRs too.

**Review by jeffdaily — CHANGES_REQUESTED** [review]
- aten/src/ATen/cuda/CUDABlas.cpp line 883, missed updating one instance of HIP_VERSION to TORCH_HIP_VERSION.
- c10/cuda/CUDAFunctions.h still has HIP_VERSION and includes hip_version.h
- aten/src/ATen/native/cuda/Copy.cu still includes hip_version.h
- In test/distributed/test_nccl.py, we define HIP_VERSION based on torch.version.hip.  Is torch.version.hip affected in any way by the semantic change to HIP_VERSION?

**Comment by jithunnair-amd** [comment]
>Is torch.version.hip affected in any way by the semantic change to HIP_VERSION?

@jeffdaily It is not, because the CMake HIP_VERSION variable comes from `/opt/rocm/hip/cmake/FindHIP.cmake`. So it still gives the correct value including the patch etc eg.: `4.3.21300-5bbc51d8`. It does raise the question of whether we should do something to change it.

**Comment by jithunnair-amd** [comment]
>aten/src/ATen/cuda/CUDABlas.cpp line 883, missed updating one instance of HIP_VERSION to TORCH_HIP_VERSION.
c10/cuda/CUDAFunctions.h still has HIP_VERSION and includes hip_version.h
aten/src/ATen/native/cuda/Copy.cu still includes hip_version.h

@jeffdaily Thanks for the eagle-eye catches! @pruthvistony I found the same missed spots. Please do another round of checks after you fix these, just to be sure.

**Comment by pruthvistony** [comment]
>     * aten/src/ATen/cuda/CUDABlas.cpp line 883, missed updating one instance of HIP_VERSION to TORCH_HIP_VERSION.
>>> I have updated this.

>     * c10/cuda/CUDAFunctions.h still has HIP_VERSION and includes hip_version.h
>>> Updated this
>     * aten/src/ATen/native/cuda/Copy.cu still includes hip_version.h
>>> Updated this

>     * In test/distributed/test_nccl.py, we define HIP_VERSION based on torch.version.hip.  Is torch.version.hip affected in any way by the semantic change to HIP_VERSION?
>>> I agree the new semantic change doesnt affect here. But I think it is good to update the check to ROCM_VERSION.

**Comment by jeffdaily** [comment]
@pruthvistony test_nccl.py is failing because the regular expression for HIP_VERSION no longer works.

```
08:44:42   File "distributed/test_nccl.py", line 13, in <module>
08:44:42     HIP_VERSION = 0.0 if torch.version.hip is None else float(re.search(r"^\d+\.\d+", torch.version.hip)[0])
08:44:42 TypeError: 'NoneType' object is not subscriptable
```

@jithunnair-amd that was your code originally, so if you have an idea how to fix and why it is breaking now?

**Comment by pruthvistony** [comment]
> @pruthvistony test_nccl.py is failing because the regular expression for HIP_VERSION no longer works.
> 
> ```
> 08:44:42   File "distributed/test_nccl.py", line 13, in <module>
> 08:44:42     HIP_VERSION = 0.0 if torch.version.hip is None else float(re.search(r"^\d+\.\d+", torch.version.hip)[0])
> 08:44:42 TypeError: 'NoneType' object is not subscriptable
> ```
> 
> @jithunnair-amd that was your code originally, so if you have an idea how to fix and why it is breaking now?

@jeffdaily , this broke due to the change in torch/cmakelists.txt. I have reverted this change. Now torch.version.hip is set "4.3.<patch>-<githash>" and so regex is good and local HIP_VERSION is set to 4.3 as expected.

**Comment by jithunnair-amd** [comment]
@pruthvistony Please rebase, the failing unit test was skipped: https://github.com/pytorch/pytorch/commit/9ee7dec681eb95257257f9c027f55e62f78493ad

**Comment by pruthvistony** [comment]
> @pruthvistony (Sorry, edited) Please rebase once this PR is merged: #63044

I have rebased the commits, hopefully all the tests pass.

**Review by jeffdaily — APPROVED** [review]

**Review by jithunnair-amd — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@malfet Please merge this PR, it's needed to avoid a breakage when we upgrade CI to ROCm4.3+

**Review by seemethere — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
