### PR TITLE
return state dict without optimized module

### LINKED ISSUE #123625: OptimizedModule should call _orig_mod's load_state_dict()/state_dict() methods.
### 🐛 Describe the bug

If a module has overridden load_state_dict()/state_dict(), the corresponding compiled module may not work. I'm currently use a workaround like the following:

```python
def my_load(self, state_dict, strict=True):
    self._orig_mod.load_state_dict(state_dict, strict)

model = torch.compile(model)
model.__class__.load_state_dict = my_load
```

### Error logs

```text
Traceback (most recent call last):
  File "mod.py", line 20, in <module>
    compiled.load_state_dict(sd)
  File "/Users/dengyao/miniconda3/envs/torch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for OptimizedModule:
	Missing key(s) in state_dict: "_orig_mod.linear.weight", "_orig_mod.linear.bias".
```

### Minified repro

```python
import torch


class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(3, 5)

    def state_dict(self):
        return {}

    def load_state_dict(self, state_dict):
        pass


module = M()
sd = module.state_dict()

compiled = torch.compile(module)
compiled.load_state_dict(sd)
```

### Versions

torch 2.2.1

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

### PR DESCRIPTION
**Pull request by mayank31398**
Fixes #123625

We should consider changing the current behaviour and make it similar to https://github.com/pytorch/pytorch/blob/1fb498d6e34e0e9b43b2c26dc0a18a4fc3a52605/torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py#L69-L101

cc @rec @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Comment by mayank31398** [comment]
Hi, any opinions about this?

**Review by williamwen42 — COMMENTED** [review]
Can you explain why this is necessary? (I'm not too familiar with distributed.) And please add a test.

**Comment by mayank31398** [comment]
it doesn't honestly make sense to have another field in the state dict simply because you have compiled the model.
Its the same thing as wrapping model with activation checkpointing.
Ill add a test :)

**Comment by mayank31398** [comment]
btw, where should I add the test?

**Comment by williamwen42** [comment]
Perhaps test/_dynamo/test_hooks.py or test/_dynamo/test_misc.py.

**Comment by mayank31398** [comment]
@williamwen42 I have added the test case
I have also added backwards compatibility support.
Also, as to why this is needed: to load a compiled model's state dict into a new model which might or might not be compiled.

**Review by williamwen42 — DISMISSED** [review]

**Comment by mayank31398** [comment]
Thanks, can we merge this :)

**Comment by mayank31398** [comment]
fixed the linting

**Review by williamwen42 — CHANGES_REQUESTED** [review]
Fix merge conflict

**Comment by mayank31398** [comment]
done @williamwen42

**Comment by mayank31398** [comment]
the linter caused an issue again
I have fixed

**Comment by mayank31398** [comment]
@williamwen42 I have fixed merge conflicts

**Comment by mayank31398** [comment]
lets merge this :)

**Review by williamwen42 — DISMISSED** [review]

**Comment by mayank31398** [comment]
@williamwen42 can you add the specific label asked by the bot?

**Comment by mayank31398** [comment]
haha, it failed again :/

**Comment by mayank31398** [comment]
@ZainRizvi is there a way to get around this issue?
I feel like this is an important PR
Its quite ridiculous to have the state dict of a compiled model be different from a non-compiled model

**Comment by williamwen42** [comment]
@mayank31398 can you check if that failure also happens locally? It looks like it could be related to your change.

**Comment by mayank31398** [comment]
@williamwen42 looks like this PR breaks quite a few things.
So, I am not sure what is the best path forward.
Ideally, we should do something about this but I am not sure how to fix this.

**Comment by williamwen42** [comment]
What exactly is breaking? What does the failing test reveal?

**Comment by mayank31398** [comment]
@williamwen42 I am not sure.
but looks like some issue here mentioned by @ZainRizvi https://github.com/pytorch/pytorch/pull/132626#issuecomment-2299190664

**Comment by williamwen42** [comment]
Do you fail the test `pytest test/distributed/checkpoint/test_state_dict.py::TestStateDict::test_fsdp2` locally?

**Comment by mayank31398** [comment]
yeah it fails @williamwen42 
```shell
04 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671] Traceback (most recent call last):
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/torch/testing/_internal/common_distributed.py", line 664, in run_test
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     getattr(self, test_name)()
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/torch/testing/_internal/common_distributed.py", line 543, in wrapper
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     fn()
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/torch/testing/_internal/common_utils.py", line 2926, in wrapper
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     method(*args, **kwargs)
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 378, in wrapper
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     raise e
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 375, in wrapper
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     func(self, *args, **kwargs)  # type: ignore[misc]
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/torch/testing/_internal/common_distributed.py", line 184, in wrapper
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     return func(*args, **kwargs)
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]            ^^^^^^^^^^^^^^^^^^^^^
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/test/distributed/checkpoint/test_state_dict.py", line 275, in test_fsdp2
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     self.run_subtests(
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 352, in run_subtests
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     return run_subtests(self, *args, **kwargs)
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/torch/testing/_internal/common_distributed.py", line 882, in run_subtests
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     test_fn(*test_args, **test_kwargs, **subtest_kwargs)
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/test/distributed/checkpoint/test_state_dict.py", line 270, in _test_fsdp2
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     self._test_save_load(init_model_optim)
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/test/distributed/checkpoint/test_state_dict.py", line 105, in _test_save_load
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     dist_msd, dist_osd = get_state_dict(
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]                          ^^^^^^^^^^^^^^^
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/torch/distributed/checkpoint/state_dict.py", line 1127, in get_state_dict
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     model_state_dict = _get_model_state_dict(model, info)
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/torch/utils/_contextlib.py", line 116, in decorate_context
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     return func(*args, **kwargs)
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]            ^^^^^^^^^^^^^^^^^^^^^
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/torch/distributed/checkpoint/state_dict.py", line 475, in _get_model_state_dict
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     fqns = _get_fqns(model, key)
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]            ^^^^^^^^^^^^^^^^^^^^^
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]   File "/proj/checkpoints/mayank/pytorch/torch/distributed/checkpoint/state_dict.py", line 214, in _get_fqns
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]     assert curr_obj_name == "_orig_mod"
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0904 23:11:55.857000 2685176 torch/testing/_internal/common_distributed.py:671] AssertionError
```

**Comment by williamwen42** [comment]
This failure looks related to your change - are you able to investigate and fix it?

**Pull request closed without merging**
