### PR TITLE
add alias to generate tensor with random uniform distribution

### PR DESCRIPTION
**Pull request by daspartho**
Fixes issue #67321 

Added alias `torch.random.uniform(low, high, size) for initiating a uniformly distributed tensor.

cc @pbelevich

### CODE REVIEW

**Comment by daspartho** [comment]
@mrshenli could you please review the code?
Thanks :)

**Comment by daspartho** [comment]
gently pinging @anjali411 
Could you please take a look at the PR?
Thanks =)

**Comment by kit1980** [comment]
@anjali411 please take a look if this is something we want to do.

**Comment by ezyang** [comment]
We will accept this. However, it needs tests, and some evidence that its implementation matches numpy.random.uniform.

**Comment by kit1980** [comment]
@daspartho Would you be willing to add a test as Edward suggested?

**Comment by JanFidor** [comment]
@kit1980  it seems the pr got stale, could I pick it up?

**Comment by kit1980** [comment]
@JanFidor sure, I've reopened it.

**Comment by JanFidor** [comment]
Thanks for the quick reply @kit1980 ! One question, should I stay on this one or make a new PR with this one referenced as superseded?

**Comment by kit1980** [comment]
> One question, should I stay on this one or make a new PR with this one referenced as superseded?

Up to you. Probably creating a new one is simpler.

**Pull request closed without merging**
