### PR TITLE
Remove cuda init patch

### PR DESCRIPTION
**Pull request by jithunnair-amd**
The below lines have been removed from `torch/cuda/__init__.py` anyway:
```
        _cudart = _load_cudart()	
        _cudart.cudaGetErrorName.restype = ctypes.c_char_p	
        _cudart.cudaGetErrorString.restype = ctypes.c_char_p
```

### CODE REVIEW

**Comment by ezyang** [comment]
We don't have anymore patches right? Can we just delete this logic entirely?

**Comment by jithunnair-amd** [comment]
You're right that we won't have any patches after this one is removed, but I was following the adage of 'Never say Never' 😁 However, if we feel that going forward, our CI/QA processes etc. will obviate any need for patches, I can certainly remove the hipify script logic dealing with patches.

**Comment by ezyang** [comment]
For any ROCm only C++ changes, preprocessor macro is far preferable. So the question is if you ever need to patch Python code in this way. In any such case, I would much rather prefer we work out a way to directly support the ROCm patch without doing a patch. Does that sound good?

**Comment by jithunnair-amd** [comment]
That sounds good to me. I'll take the patch logic out of the hipify script.

**Review by jeffdaily — APPROVED** [review]
LGTM.   Nice to get rid of.  I agree with the previous PR commentary.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
