### PR TITLE
Kill CUDA_tensor_apply4

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#33998 Kill CUDA_tensor_apply4**
* #33997 Migrate prelu_cuda_backward from CUDA_tensor_apply4 to TensorIterator

Differential Revision: [D20196787](https://our.internmc.facebook.com/intern/diff/D20196787)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
Please rebase stack

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin rebased

**Comment by VitalyFedyunin** [comment]
Sorry, we have high files contention, could you please rebase again.

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin rebased

**Review by VitalyFedyunin — APPROVED** [review]

**Pull request closed without merging**
