### PR TITLE
Enable ncclAvg for reductions

### PR DESCRIPTION
**Pull request by mcarilli**
[ncclAvg](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html?highlight=ncclavg#c.ncclAvg) is a new `ncclRedOpt_t` that fuses a div-by-world-size with ncclAllReduce, Reduce, or ReduceScatter. This PR adds support.

This PR and https://github.com/pytorch/pytorch/pull/62140 lay the foundation for to DDP allreduce+average grad tensors in place with a single nccl call without additional memory pass(es) to flatten or average or unflatten. I'll write the necessary DDP changes once this PR and https://github.com/pytorch/pytorch/pull/62140 land.

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Awesome, great to see ncclAvg enabled!

**Comment by rohan-varma** [comment]
Curious, per your PR description how can DDP adopt allreduce_coalesced today? In DDP we kick off allreduce for a single tensor corresponding to a bucket when a bucket is ready. I guess one use case of allreduce_coalesced is doing N buckets in one shot, but I'm not sure we would want to do that because it would decrease the comm./comp overlap?

**Comment by mcarilli** [comment]
> how can DDP adopt allreduce_coalesced today?

My plan is, a bucket will simply collect a vector of gradient references without flattening or predividing them. When the bucket is full (contains all expected gradient references) it will pass that vector to allreduce_coalesced and request a ncclAvg.  The nccl group will allreduce+avg all the separate-in-memory grads in place without any separate flattening, unflattening, or predivision memory passes.

This will be free perf IF the perf of the nccl group acting on the scattered tensors roughly matches the perf of a single allreduce on a flattened bucket. Ideally that should be true. Internal tests show for some param sets it is true, but for others the grouped call is slower (enough to wipe out the benefits of eliding explicit flattening/predivide). We're working with the nccl team to figure out when the grouped call is slower, by how much, and if there's a path to parity for all cases. Once we have a better idea of this I'll PR the DDP change.

**Comment by pbelevich** [comment]
Reverting because:
```
../torch/csrc/distributed/c10d/init.cpp:507:39: error: ‘AVG’ is not a member of ‘c10d::ReduceOp’
```
https://app.circleci.com/pipelines/github/pytorch/pytorch/360411/workflows/dd9d10fb-52ca-4596-82dc-a5e6022602ce/jobs/15200425

@mcarilli @rohan-varma

**Pull request closed without merging**
