### PR TITLE
Update xnnpack to the latest commit

### PR DESCRIPTION
**Pull request by iremyux**
After trying to update cpuinfo submodule to the latest, I saw that an update on xnnpack is also necessary.

Fixes the 2 failing checks on [#95379](https://github.com/pytorch/pytorch/pull/95379)

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]
LGTM assuming tests pass

**Comment by iremyux** [comment]
Syncing the branch with pytorch:master to retrigger the checks. This was necessary after disabling of a failing test. Related issue can be found [here](https://github.com/pytorch/pytorch/issues/88719)

**Comment by iremyux** [comment]
@Skylion007 can this be merged?

**Comment by malfet** [comment]
It would be good to provide a bit more context, what motivates the update (Platform support, performance, bugfixes, etc)

**Comment by kit1980** [comment]
Also please coordinate with @SS-JIA and @digantdesai because they are making frequent xnnpack-related changes.

**Comment by tiandiao123** [comment]
why do we need update xnnpack?

**Comment by Skylion007** [comment]
@tiandiao123 updating XNNPack allows us to update CPUInfo per https://github.com/pytorch/pytorch/pull/95379

**Comment by digantdesai** [comment]
XNNPACK [depends](https://github.com/google/XNNPACK/blob/master/cmake/DownloadCpuinfo.cmake#L15) on cpuinfo. So does PyTorch.
I guess, this XNNPACK submodule update for PyTorch is to pull a cpuinfo [update](https://github.com/google/XNNPACK/commit/1cce614a611be15ab2feb75587a96dc8d1f54a78) in XNNPACK? 
@iremyux, can you please clarify?

**Comment by iremyux** [comment]
@digantdesai 
cpuinfo submodule needs an update to support Windows on Arm64. For this purpose, first, at least [this commit ](https://github.com/google/XNNPACK/commit/1cce614a611be15ab2feb75587a96dc8d1f54a78) in the xnnpack repository needs to be merged. I did not fully examined the remaining of the commits on this repository but chose to update to the master instead.

**Review by malfet — APPROVED** [review]

**Comment by Blackhex** [comment]
[@pytorchbot](https://github.com/pytorchbot) rebase

**Comment by Blackhex** [comment]
First of all, sorry for the mess that just happened. I just wanted to rebase the branch to the latest master and I don't know what actually happened.

> If this is the case, should both XNNPACK and CPUINFO be updated in the same commit?

@iremyux @malfet, I guess it would make things much easier. Also, as @digantdesai pointed out, there is also XNNPACK dependency on pytorch/cpuinfo at [https://github.com/google/XNNPACK/blob/master/cmake/DownloadCpuinfo.cmake#L15](https://github.com/google/XNNPACK/blob/master/cmake/DownloadCpuinfo.cmake#L15) which should be updated as well in the same a "atomic" change. Furthermore, during development of pytorch/cpuinfo#144, I've noticed that there is also a dependency of [https://github.com/pytorch/FBGEMM](https://github.com/pytorch/FBGEMM) on cpuinfo at [https://github.com/pytorch/FBGEMM/blob/main/.gitmodules#L6](https://github.com/pytorch/FBGEMM/blob/main/.gitmodules#L6) so that should also be included in the change.

**Pull request closed without merging**
