### PR TITLE
More rigorous mixed overloads on SymInt

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #100008

Previously the change to aten/src/ATen/native/LossNLL.cpp eventually resulted in a double / SymInt division, which ended up calling the int64_t / SymInt overload, truncating the double (bad!) By adding overloads for all the int/float types, we avoid this situation from happening in the future.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM
I guess some test needs updating for the nll impl being fixed?

**Comment by ezyang** [comment]
yeah, I'm waiting for CI to tell me which

**Pull request closed without merging**
