### PR TITLE
Fix ProcessGroupMPITest.cpp Gather, Scatter and SendRecv. Enable ProcessGroupMPITest

### PR DESCRIPTION
**Pull request by agolynski**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#56709 Fix ProcessGroupMPITest.cpp Gather, Scatter and SendRecv. Enable ProcessGroupMPITest**

Right now, ProcessGroupMPITest testGather() fails with

 ```
what():  Gather: number of output tensors should be 0 for non-root
[devgpu025:429730] *** Process received signal ***

```

there is a similar issue with testScatter() where number of input/output tensors on source/destination respectively should be 0.

In addition testSendRecv(true); fails with

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  src rank is wrong for recvAnysource

```

since we never populate `srcRanks`

Differential Revision: [D28001963](https://our.internmc.facebook.com/intern/diff/D28001963)

### CODE REVIEW

**Comment by agolynski** [comment]
Seems like we don't run this on CI, here is manual run:

```
mpiexec -np 2 pytorch/build/bin/ProcessGroupMPITest
Test successful
Test successful
```

**Review by mrshenli — COMMENTED** [review]
Hey @agolynski, could you please update the PR summary to explain the bug and the fix? Thanks!

**Comment by agolynski** [comment]
@mrshenli done. PTAL?

**Review by mrshenli — COMMENTED** [review]
As we discussed offline let's enable those tests in CI. Below is how other C++ tests are invoked:

https://github.com/pytorch/pytorch/blob/3a44d269ac1eae5fdfb6655bcaa8fa8be589dbb3/.jenkins/pytorch/test.sh#L239-L254

**Review by sab-regime — APPROVED** [review]

**Review by sab-regime — APPROVED** [review]

**Comment by agolynski** [comment]
@mrshenli ci-all workflows are completed and green
https://github.com/pytorch/pytorch/pull/56780

**Review by mrshenli — APPROVED** [review]
LGTM

**Comment by mrshenli** [comment]
Looks like some MPI tests become flaky since this PR. See the following instances. Do we need to revert?

https://app.circleci.com/pipelines/github/pytorch/pytorch/311990/workflows/2b2fbb72-b613-4986-8842-eccd93e7cdae/jobs/12948992

https://app.circleci.com/pipelines/github/pytorch/pytorch/312185/workflows/1acc0928-0fb6-4472-b415-b324957d49da/jobs/12953722

**Comment by mrshenli** [comment]
Failed tests are already tracked in #56690

**Pull request closed without merging**
