### PR TITLE
support 0 size in any of the tensor dimensions in mkldnn

### PR DESCRIPTION
**Pull request by PenghuiCheng**
support 0 size in any of the tensor dimensions in mkldnn

### CODE REVIEW

**Comment by PenghuiCheng** [comment]
@yinghai ,Could you review this commit?

**Comment by yinghai** [comment]
Rebase to update the CI test results?

**Comment by PenghuiCheng** [comment]
@yinghai ，I had rebased. thanks!

**Review by yinghai — APPROVED** [review]
LGTM . Thanks!

**Pull request closed without merging**
