### PR TITLE
Add API usage to torch.RPC

### PR DESCRIPTION
**Pull request by pritamdamania87**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #67515

Adding API usage to torch.rpc to better understand usage of this API.

Differential Revision: [D32011465](https://our.internmc.facebook.com/intern/diff/D32011465/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D32011465/)!

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
LGTM, what about `rpc.init_rpc` as well?

**Review by mrshenli — APPROVED** [review]
LGTM! Do we also wanna include `distributed.autograd.backward`?

**Comment by pritamdamania87** [comment]
> LGTM, what about rpc.init_rpc as well?

Do we need `init_rpc` if the actual RPC methods are there? I didn't add `init_rpc` since it doesn't really show usage (ex: someone called init_rpc but never actually used RPC).

**Comment by pritamdamania87** [comment]
> LGTM! Do we also wanna include distributed.autograd.backward?

Sure, let me add a follow up PR for this.

**Pull request closed without merging**
