### PR TITLE
Add option to allow loading state dict with mismatching shapes.

### PR DESCRIPTION
**Pull request by hgaiser**
This PR adds an option to override the choice of loading weights or not and optionally to produce an error. This can be very useful if you want to do transfer learning, transferring weights from model A to model B where A and B have a different output (number of classes, for example).

Example usage:

```python
import torch

# Base model.
a = torch.nn.Sequential(
    torch.nn.Conv2d(7, 5, 1),
    torch.nn.Conv2d(5, 3, 1)
)

# Model with an additional layer, requires `strict=False`.
b = torch.nn.Sequential(
    torch.nn.Conv2d(7, 5, 1),
    torch.nn.Conv2d(5, 3, 1),
    torch.nn.Conv2d(3, 3, 1)
)

# Model with an additional layer and one of the layers has a different shape of weights,
# requires `strict=False` and the optional callback introduced in this PR: `tensor_check_fn`.
c = torch.nn.Sequential(
    torch.nn.Conv2d(7, 5, 1),
    torch.nn.Conv2d(3, 3, 1),
    torch.nn.Conv2d(3, 3, 1)
)

# This line works without this PR.
b.load_state_dict(a.state_dict(), strict=False)

# The next part doesn't work without this PR, because c has a layer that is of different shape.
def tensor_check_fn(param, input_param, error_msgs):
	if param.shape != input_param.shape:
		return False
	return True

c.load_state_dict(a.state_dict(), strict=False, tensor_check_fn=tensor_check_fn)
```

This change should be backwards compatible, unless some custom layer implements the `_load_from_state_dict` method, because an argument has been added there.

### CODE REVIEW

**Comment by gchanan** [comment]
Looks like the test are failing.  Also, could you open an issue to discuss whether we want to make this change?  Thanks.

**Comment by hgaiser** [comment]
> Looks like the test are failing. Also, could you open an issue to discuss whether we want to make this change? Thanks.

Apologies for the late reply, this has gone under my radar. I'll make an issue to discuss the topic.

**Comment by hgaiser** [comment]
@albanD  I updated the PR according to https://github.com/pytorch/pytorch/issues/40859 . Now the following script works (note: it requires a change in torchvision as well to include the `tensor_check_fn` argument):

```python
import torch
import torchvision

model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model_new = torchvision.models.detection.fasterrcnn_resnet50_fpn(num_classes=3)

def tensor_check_fn(param, input_param, error_msgs):
	if param.shape != input_param.shape:
		return False
	return True

model_new.load_state_dict(model.state_dict(), tensor_check_fn=tensor_check_fn)
```

This will load all params where the shape matches and skip all the params where the shape mismatches. Let me know what you think, then I will start on a unit test to test this functionality.

One thing I didn't like is that the error message before included the param name, but it is not available in the `tensor_check_fn` function. What are your thoughts on this?

**Comment by albanD** [comment]
> What are your thoughts on this?

Do you think it would be worth adding a `key` argument to the `tensor_check_fn` to make sure we can get the same error message? I would be happy with that.

> note: it requires a change in torchvision as well to include the tensor_check_fn argument

I am not sure to follow why you need to change torchvision here? The models in torchvision already have the proper shape and its just when you extract their content to load into your model that you need this extra function no?

**Comment by hgaiser** [comment]
> Do you think it would be worth adding a `key` argument to the `tensor_check_fn` to make sure we can get the same error message? I would be happy with that.

Sounds good to me. Is `key` the right name for this?



> I am not sure to follow why you need to change torchvision here? The models in torchvision already have the proper shape and its just when you extract their content to load into your model that you need this extra function no?

I had to change this:

```
diff --git a/torchvision/models/mnasnet.py b/torchvision/models/mnasnet.py
index c2479a8..61fe4e8 100644
--- a/torchvision/models/mnasnet.py
+++ b/torchvision/models/mnasnet.py
@@ -152,7 +152,8 @@ class MNASNet(torch.nn.Module):
                 nn.init.zeros_(m.bias)
 
     def _load_from_state_dict(self, state_dict, prefix, local_metadata, strict,
-                              missing_keys, unexpected_keys, error_msgs):
+                              missing_keys, unexpected_keys, error_msgs,
+                              tensor_check_fn):
         version = local_metadata.get("version", None)
         assert version in [1, 2]
 
@@ -189,7 +190,7 @@ class MNASNet(torch.nn.Module):
 
         super(MNASNet, self)._load_from_state_dict(
             state_dict, prefix, local_metadata, strict, missing_keys,
-            unexpected_keys, error_msgs)
+            unexpected_keys, error_msgs, tensor_check_fn)
 
 
 def _load_pretrained(model_name, model, progress):
diff --git a/torchvision/ops/misc.py b/torchvision/ops/misc.py
index 17e69c5..3b10e2f 100644
--- a/torchvision/ops/misc.py
+++ b/torchvision/ops/misc.py
@@ -75,6 +75,7 @@ class FrozenBatchNorm2d(torch.nn.Module):
         missing_keys: List[str],
         unexpected_keys: List[str],
         error_msgs: List[str],
+        tensor_check_fn,
     ):
         num_batches_tracked_key = prefix + 'num_batches_tracked'
         if num_batches_tracked_key in state_dict:
@@ -82,7 +83,7 @@ class FrozenBatchNorm2d(torch.nn.Module):
 
         super(FrozenBatchNorm2d, self)._load_from_state_dict(
             state_dict, prefix, local_metadata, strict,
-            missing_keys, unexpected_keys, error_msgs)
+            missing_keys, unexpected_keys, error_msgs, tensor_check_fn)
 
     def forward(self, x: Tensor) -> Tensor:
         # move reshapes to the beginning
```

**Comment by hgaiser** [comment]
Added the key argument, now it works like this:

```python
import torch
import torchvision

model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)

model_new = torchvision.models.detection.fasterrcnn_resnet50_fpn(num_classes=3)

def tensor_check_fn(key, param, input_param, error_msgs):
	print(key)
	if param.shape != input_param.shape:
		return False
	return True

model_new.load_state_dict(model.state_dict(), tensor_check_fn=tensor_check_fn)
```

**Comment by albanD** [comment]
The "key" change looks good!

I am a bit worried about the number of changes required to change `_load_from_state_dict` that should be an internal API :/ 
cc @fmassa is that ok to change this in torchvision as well and merge both PR at the same time? Or you think we should avoid changing this function's signature?

**Comment by mruberry** [comment]
Jumping in for a moment: make sure you update this PR's summary to reflect the current design and thinking and why there won't be any backward-compatibility impact from this approach.

**Comment by hgaiser** [comment]
@mruberry I updated the first post to reflect the current state of the PR. Thanks for the reminder!

**Comment by albanD** [comment]
Hey,

Sorry for the delay. 
Given the issue with modifying the signature of `_load_from_state_dict` which seems to be overwritten by many modules (and potentially in a lot of third party libraries), we are a bit weary of making this change. Changing torchvision could be done but breaking user code is not something we like to see in general.

Also the fact that this function is overwritten for so many modules means that this solution will not work in general and the user-provided function will actually end up being ignored in a lot of cases.

**Comment by hgaiser** [comment]
Hey @albanD ,

I completely understand, that was also my reaction when I noticed I had to change torchvision for this to work.. 

If we want to avoid breaking user code then it will become a bit more complicated. A method with a different name would work I suppose, but I wouldn't be a fan of adding a method with a slightly different name every time the signature of this method changes. I wouldn't be opposed to it, but it wouldn't be my preference :)

Maybe there won't be any other changes, but it sets a dangerous precedent and can clutter up an API in my opinion.

I'm not sure if the consideration is to drop the issue altogether, but I really think this is a feature that needs to be in pytorch. Personally I have been using this branch for loading weights until a definitive version lands.

**Comment by albanD** [comment]
I am wondering how hard would it be to create a third party lib with a load state dict that would do this?
Either by monkey-patching the loading or by doing a pre-processing on the state_dict (removing things your want to ignore) before giving it to the vanilla load_state_dict function?

**Comment by JulienMaille** [comment]
> I am wondering how hard would it be to create a third party lib with a load state dict that would do this?
> Either by monkey-patching the loading or by doing a pre-processing on the state_dict (removing things your want to ignore) before giving it to the vanilla load_state_dict function?

I was looking for something similar to this PR, Do you think this pre-processing is the right way to go?
https://github.com/PyTorchLightning/pytorch-lightning/issues/4690#issuecomment-731152036

**Comment by albanD** [comment]
I do think that pre-processing is going to be a less "magical" solution for sure and easy to add to any code just before you load the state dict.

**Comment by hgaiser** [comment]
I believe the consensus is to not make any changes to pytorch and instead rely on user code or third party libs to provide this functionality, correct?

I would like to express my opinion one more time that I think this should really be a part of the weight loading method inside pytorch itself, but I will respect your decision.

If you feel there is a way we can have this functionality in pytorch then I will be happy to hear it and possibly update this PR accordingly. If you see no way for this to be merged, then feel free to close this PR.

**Comment by mruberry** [comment]
> I believe the consensus is to not make any changes to pytorch and instead rely on user code or third party libs to provide this functionality, correct?
> 
> I would like to express my opinion one more time that I think this should really be a part of the weight loading method inside pytorch itself, but I will respect your decision.
> 
> If you feel there is a way we can have this functionality in pytorch then I will be happy to hear it and possibly update this PR accordingly. If you see no way for this to be merged, then feel free to close this PR.

I think that is the current consensus but I've added this to our review queue to check again. It may take a week or two to respond, however, as some people are taking vacation.

**Comment by hgaiser** [comment]
Any update on this @mruberry ?

For reference, I'm currently using a custom function to get the desired effect. Basically it filters out any states that would cause an issue in `load_state_dict`:

```python
def match_state_dict(
	state_dict_a: Dict[str, torch.Tensor],
	state_dict_b: Dict[str, torch.Tensor],
) -> Tuple[Dict[str, torch.Tensor], Dict[str, torch.Tensor]]:
	""" Filters state_dict_b to contain only states that are present in state_dict_a.

	Matching happens according to two criteria:
	    - Is the key present in state_dict_a?
	    - Does the state with the same key in state_dict_a have the same shape?

	Returns
	    (matched_state_dict, unmatched_state_dict)

	    States in matched_state_dict contains states from state_dict_b that are also
	    in state_dict_a and unmatched_state_dict contains states that have no
	    corresponding state in state_dict_a.

		In addition: state_dict_b = matched_state_dict U unmatched_state_dict.
	"""
	matched_state_dict = {
		key: state
		for (key, state) in state_dict_b.items()
		if key in state_dict_a and state.shape == state_dict_a[key].shape
	}
	unmatched_state_dict = {
		key: state
		for (key, state) in state_dict_b.items()
		if key not in matched_state_dict
	}
	return matched_state_dict, unmatched_state_dict
```

**Comment by mruberry** [comment]
> Any update on this @mruberry ?
> 
> For reference, I'm currently using a custom function to get the desired effect. Basically it filters out any states that would cause an issue in `load_state_dict`:
> 
> ```python
> def match_state_dict(
> 	state_dict_a: Dict[str, torch.Tensor],
> 	state_dict_b: Dict[str, torch.Tensor],
> ) -> Tuple[Dict[str, torch.Tensor], Dict[str, torch.Tensor]]:
> 	""" Filters state_dict_b to contain only states that are present in state_dict_a.
> 
> 	Matching happens according to two criteria:
> 	    - Is the key present in state_dict_a?
> 	    - Does the state with the same key in state_dict_a have the same shape?
> 
> 	Returns
> 	    (matched_state_dict, unmatched_state_dict)
> 
> 	    States in matched_state_dict contains states from state_dict_b that are also
> 	    in state_dict_a and unmatched_state_dict contains states that have no
> 	    corresponding state in state_dict_a.
> 
> 		In addition: state_dict_b = matched_state_dict U unmatched_state_dict.
> 	"""
> 	matched_state_dict = {
> 		key: state
> 		for (key, state) in state_dict_b.items()
> 		if key in state_dict_a and state.shape == state_dict_a[key].shape
> 	}
> 	unmatched_state_dict = {
> 		key: state
> 		for (key, state) in state_dict_b.items()
> 		if key not in matched_state_dict
> 	}
> 	return matched_state_dict, unmatched_state_dict
> ```

Thanks for checking in, @hgaiser, no update yet, I'm afraid. Let me see what I can do to get back to you by the end of this week or start of next week.

**Comment by mruberry** [comment]
Had a chance to follow-up with @albanD and @jbschlosser. While @jbschlosser is interested in better supporting transfer learning, we confirmed that we think this change is too disruptive, and that we should focus on supporting the behavior with custom mechanisms for loading tensors from state dicts, possibly with a tutorial or example.

**Comment by albanD** [comment]
Shifting this towards having more general state dict hooks. So you will be able to massage the content of the `mod` or the state dict to make sure the loading will work just fine.

**Comment by amitbcp** [comment]
@albanD  so do we have a tutorial or example for achieving this during transfer learning ?

**Comment by albanD** [comment]
Hi,

I'm afraid we don't as not all hooks are fully finalized yet. See https://github.com/pytorch/pytorch/issues/75287 for details.

**Pull request closed without merging**
