### PR TITLE
Only truncate leading 1s if the value is too big.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #94521

If it's just right, broadcasting will do the right thing
automatically.

This helps with unbacked SymInts as I can avoid testing one
equality on the inside.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]

**Review by ngimel — COMMENTED** [review]
Yeah hard to do it fully correctly, but this is better than before.

**Comment by ezyang** [comment]
better version at https://github.com/pytorch/pytorch/pull/95141

**Pull request closed without merging**
