### PR TITLE
[FSDP] Address comments on previous PR

### PR DESCRIPTION
**Pull request by rohan-varma**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #85490

Address follow ups on https://github.com/pytorch/pytorch/pull/85223/

Differential Revision: [D39740878](https://our.internmc.facebook.com/intern/diff/D39740878/)

### CODE REVIEW

**Review by awgu — APPROVED** [review]
Thanks for the quick turnaround!

**Comment by rohan-varma** [comment]
CI failure looks infra related: https://github.com/pytorch/pytorch/actions/runs/3108336709/jobs/5037417360#step:3:27

**Pull request closed without merging**
