### PR TITLE
[DO NOT MERGE] Test if sparse tensor `values_` can be a requires grad variable

### PR DESCRIPTION
**Pull request by yf225**

### CODE REVIEW

**Comment by SsnL** [comment]
This idea... is interesting. Does this mean that a sparse variable will be able to contain another variable :O?

**Comment by yf225** [comment]
@SsnL After the Variable/Tensor merge, there will be no distinction between a Variable and a Tensor (they have the same TensorImpl), and a requires-grad tensor will have AutogradMeta in its TensorImpl. @gchanan and I are trying to look at if we can allow a sparse tensor's `values_` to be a requires-grad tensor, to avoid shallow-copying the `values` when calling `VariableType::_sparse_coo_tensor_with_dims_and_tensors(sparse_dim, dense_dim, size, indices, values, options)`. My understanding is that this can work because we always ignore `values_`'s AutogradMeta and create a view with a new AutogradMeta when we call the public `sparse_tensor.values()` API.

**Comment by SsnL** [comment]
@yf225 Thanks for explanation! This is exactly what I was wondering. So a `values_` tensor will have the `AutogradMetaData`, but it is just ignored, for the computations the sparse tensor involves. That's great. But I wonder what happens if users later, say, `resize_` or `as_strided_` on the same value tensor that is also now kept in the SparseTensorImpl?

**Comment by yf225** [comment]
@SsnL Calling `resize_ `or `as_strided_` on the same value tensor is likely not a supported operation currently. Here are a few examples:
```python
# Calling resize_ on requires-grad value tensor
i1 = torch.zeros([1, 1])
v1 = torch.ones([1, 2, 3]).requires_grad_()
t1 = torch.sparse_coo_tensor(i1, v1, torch.Size([2, 2, 3]))
v1.resize_(4, 5) # throws "cannot resize variables that require grad"

# Calling resize_ on non-requires-grad value tensor
i2 = torch.zeros([1, 1])
v2 = torch.ones([1, 2, 3])
t2 = torch.sparse_coo_tensor(i2, v2, torch.Size([2, 2, 3]))
v2.resize_(4, 5) # breaks sparse shape invariant
t2.coalesce().values() # throws "indices and values must have same nnz, but got nnz from indices: 1, nnz from values: 4"

# Calling as_strided_ on requires-grad value tensor
i3 = torch.zeros([1, 1])
v3 = torch.ones([1, 2, 3]).requires_grad_()
t3 = torch.sparse_coo_tensor(i3, v3, torch.Size([2, 2, 3]))
v3.as_strided_((2, 3), (3, 1)) # throws "a leaf Variable that requires grad has been used in an in-place operation"

# Calling as_strided_ on non-requires-grad value tensor
i4 = torch.zeros([1, 1])
v4 = torch.ones([1, 2, 3])
t4 = torch.sparse_coo_tensor(i4, v4, torch.Size([2, 2, 3]))
v4.as_strided_((2, 3), (3, 1)) # breaks sparse shape invariant
t4.coalesce().values() # throws "indices and values must have same nnz, but got nnz from indices: 1, nnz from values: 2"
```

**Comment by SsnL** [comment]
@yf225 Thanks for the tests! I see now that `resize_` probably does not matter. However, if you `as_strided_` to a geometry with the same size (& different strides), does it break?

**Comment by yf225** [comment]
@SsnL I tried the following and it doesn't break
```python
i4 = torch.zeros([1, 1])
v4 = torch.ones([1, 2, 3])
t4 = torch.sparse_coo_tensor(i4, v4, torch.Size([2, 2, 3]))
v4.as_strided_((1, 2, 3), (1, 1, 1))
t4.coalesce().values()  # this works
```

And I think this will continue to work after the change because we are not making shallow copies of the value tensor.

**Comment by SsnL** [comment]
@yf225 My questions is, now that it does not shallow copy, if you change `v`'s geometry inplace, it also changes the contained value tensor's geometry. So it could return incorrect values. You can probably see this if your `v4` is not all zeros :P

**Comment by yf225** [comment]
@SsnL It actually isn't doing shallow-copy in current master either, and doing shallow-copy is one way to maintain the invariant that "sparse tensor's `values_` does not require grad" while being able to merge Variable and Tensor. However, if we can drop this invariant (since it actually doesn't affect the behavior we want), it will make the implementation of `_sparse_coo_tensor_with_dims_and_tensors` simpler.

**Pull request closed without merging**
