### PR TITLE
Don't change filelock log level by default

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99991

Fixes https://github.com/pytorch/pytorch/issues/99730

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by albanD — APPROVED** [review]
Should we add a lint that we never call setLevel() outside of our logging utility?

**Comment by mlazos** [comment]
Does this fix https://github.com/pytorch/pytorch/issues/99730?

**Comment by ezyang** [comment]
confirmed in CI that it does

**Comment by ezyang** [comment]
@albanD sigh, I'm not sure, I'm sure whoever added this had a good reason for it

**Pull request closed without merging**
