### PR TITLE
Connect Tensor.__ipow__ to pow_ method

### PR DESCRIPTION
**Pull request by amjames**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #76901
* __->__ #76900

The `pow_` method should be connected to `Tensor.__ipow__` so that the
operator `**=` works correctly.

Part of #58742

### CODE REVIEW

**Comment by kshitij12345** [comment]
Thanks for the PR @amjames!

However, I confirmed with @dbhasin1 that she plans to update her PR https://github.com/pytorch/pytorch/pull/71984. So it would be great if you can help review that one.

**Comment by Dbhasin1** [comment]
Hi @amjames, this looks good from the array API compliance point of view. I think we'll just need to add a test for ``**=`` in ``test_binary_ufuncs.py``

**Comment by amjames** [comment]
@Dbhasin1 Thanks for looking this over. I can add that test. It is worth mentioning for future reference, after #76901 it would be redundant.

**Review by mruberry — APPROVED** [review]
Cool!

**Pull request closed without merging**
