### PR TITLE
Don't allocate result Tensors in out overloads: at::kron_out()

### PR DESCRIPTION
**Pull request by smessmer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #53660 [experiment] AlwaysCall Backend Fallback
* #55321 Don't allocate result Tensors in out overloads: _linalg_solve_out_helper_cuda
* #53624 Boxing logic forwards arguments to stack
* #53556 Fix forwarding/move bug
* **#53640 Don't allocate result Tensors in out overloads: at::kron_out()**
* #53218 Don't allocate result Tensors in out overloads: Reduction Ops
* #53229 Fix Scalar formatting
* #53228 Fix boxing/unboxing for Scalar bool values

We have some operators that previously allowed you to pass in an undefined tensor to the out argument,
and then would go on to allocate that for you. This behavior is broken and doesn't work in JIT when things
are converted to/from IValues. Because of this, it blocks backend fallbacks because they force going
through IValue.

This PR is one in a series to remove that behavior and forces out arguments to be defined tensors.

It only looks at at::kron_out(), but there's more PRs for other ops.

BC Breaking: This breaks BC for the C++ frontend API since those ops previously allowed calling with undefined tensors and that isn't allowed anymore.

Differential Revision: [D26921165](https://our.internmc.facebook.com/intern/diff/D26921165/)

### CODE REVIEW

**Comment by ezyang** [comment]
Have you considered just porting this to structured? :o)

**Review by bhosmer — COMMENTED** [review]
I know it probably feels like a digression from the immediate goal (undefined tensor results) to suggest dogfooding here, but I agree w/@ezyang that this impl feels a lot like a back-pocket structured kernel. If this pattern is the right solution here, it'd would be a good opportunity to kick the tires on the official SK toolchain (like, if that way is more cumbersome, why? can we get it to the point where there's no motivation to do something like this instead?). 

OTOH if we can solve the immediate problem with something simpler, then it'd probably be better to just do that, so we don't have potentially confusing SK-lite code examples in tree.

**Comment by smessmer** [comment]
@ezyang @bhosmer The out variant here seems to do more work than the functional variant, there's for example an additional call to `at::mul_out`. In the old version of the code, this was somewhat implicit by the functional variant calling the out variant with an undefined result tensor and the functional variant taking a shortcut if result is undefined. In the new implementation in this PR, it's more explicit, but still the same logic. I don't want to rewrite it to structured and then rely on undefined tensor being passed, this seems like a bad way of dealing with it (even though it might work - we cannot pass undefined tensors across dispatcher calls anymore, but I think passing it from the structured functional variant to the structured out variant might be ok since that doesn't go through the dispatcher), and it would likely require a more in-depth rewrite of the op to solve this the right way. This is out of scope for my backend fallback work.

**Review by bhosmer — APPROVED** [review]
Per offline discussion, moving this to structured kernels is out of scope for the current work (though it's worth doing).

**Pull request closed without merging**
