### PR TITLE
Migrate frac from TH to ATen (CUDA)

### LINKED ISSUE #24566: Migrate `frac` and `frac_` from the TH to Aten (CUDA)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #29323 Migrate acos from TH to ATen (CUDA)
* #29046 Clean up many unused declaration/definitions in TH
* **#28953 Migrate frac from TH to ATen (CUDA)**

Close #24566

Benchmark (Debian Buster, CUDA 9.2, Quadro P400, turbo off, Release, gcc
7.4):

```python
import timeit

for n, t in [(10_000, 20000),
             (100_000, 20000)]:
    for dtype in ('torch.half', 'torch.float', 'torch.double'):
        print(f'torch.frac(a) a.numel() == {n} for {t} times {dtype}')
        print(timeit.timeit(f'torch.frac(a); torch.cuda.synchronize()', setup=f'import torch; a=torch.arange({n}, dtype={dtype}, device="cuda")', number=t))
```

Before:

```
torch.frac(a) a.numel() == 10000 for 20000 times torch.half
0.3608182370007853
torch.frac(a) a.numel() == 10000 for 20000 times torch.float
0.3647012189976522
torch.frac(a) a.numel() == 10000 for 20000 times torch.double
0.3889585220022127
torch.frac(a) a.numel() == 100000 for 20000 times torch.half
0.622635444997286
torch.frac(a) a.numel() == 100000 for 20000 times torch.float
0.9595754649999435
torch.frac(a) a.numel() == 100000 for 20000 times torch.double
1.5590267750012572
```

After:

```
torch.frac(a) a.numel() == 10000 for 20000 times torch.half
0.3675256470014574
torch.frac(a) a.numel() == 10000 for 20000 times torch.float
0.3703597319981782
torch.frac(a) a.numel() == 10000 for 20000 times torch.double
0.372184894993552
torch.frac(a) a.numel() == 100000 for 20000 times torch.half
0.60767333900003
torch.frac(a) a.numel() == 100000 for 20000 times torch.float
0.9645607889979146
torch.frac(a) a.numel() == 100000 for 20000 times torch.double
1.5542530329985311
```

Differential Revision: [D18302768](https://our.internmc.facebook.com/intern/diff/D18302768)

### CODE REVIEW

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit 4a5421e:
* 1/1 flaky



Here are the [reasons each build failed](https://dr.pytorch.org/commit-details.html?sha1=4a5421e3d711238291f29bc5c88eeb7dde28a88d).

---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by xuhdev** [comment]
@VitalyFedyunin Are you merging this? I'm going to rebase

**Comment by VitalyFedyunin** [comment]
Go ahead with rebase

**Comment by xuhdev** [comment]
Done

**Pull request closed without merging**
