### PR TITLE
[Inductor] improve the stride preservation logic of user-visible outputs

### PR DESCRIPTION
**Pull request by yifuwang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #138946
* __->__ #136732

## Context

Previously, the stride preservation of user-visible nodes worked as follows:

- After joint-graph tracing, we recorded the **names** of user-visible nodes and passed them to GraphLowering.
- In GraphLowering, we determined whether we needed to preserve the striding for a certain node by checking if the node's name was in `user_visible_outputs`.
- We obtained the original strides by checking `node.meta["val"].stride()`.

However, there's a problem with this approach: the nodes in output_node.args[0] and their strides could change between the completion of joint-graph tracing and the consumption of `user_visible_outputs` (e.g., during post-grad passes), making it unreliable.

## This PR

- After joint graph tracing:
  - Record the original strides for all nodes in `output_nodes.args[0]` as `output_node.meta["original_output_strides"]` (recording for all nodes in case we need the info for other purposes such as debugging).
  - Record the indices of user-visible outputs as `output_node.meta["user_visible_output_idxs"]`.
- Remove the original plumbing of `user_visible_outputs`.

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @rec

### CODE REVIEW

**Review by Chillee — CHANGES_REQUESTED** [review]
Can you add a more explicit test? Take a graph, run a custom FX graph pass on it that changes strides, ensure that the output still has the same stride.

**Review by eellison — COMMENTED** [review]
Nice! I had discussed this issue (post grad passes changing strides) with @zou3519 so great to see a fix for it. 

We also want to do this for custom_operators. Similar to @Chillee's comment, maybe it sense to have put the metadata on the output node of the graph corresponding to its inputs. We could put metadata on custom ops corresponding to their inputs in the same way. 

cc @zou3519 for thoughts

**Comment by zou3519** [comment]
I'm not sure if the metadata should go in the graph's metadata or directly on the output node. Putting the metadata on the node lines up with what we want to do with custom ops, but then it runs the risk that someone may not preserve the metadata. Putting the output metadata in the graph means that it'll always be there.

Also, one interesting case is what happens if the strides contain symints. Maybe this is already handled, but it seems tricky to ensure that the symints get codegenned correctly.

**Comment by eellison** [comment]
> I'm not sure if the metadata should go in the graph's metadata or directly on the output node. Putting the metadata on the node lines up with what we want to do with custom ops, but then it runs the risk that someone may not preserve the metadata. Putting the output metadata in the graph means that it'll always be there.

On the "node" here means the output node. The output node is more or less guaranteed to remain unchanged I think.

**Comment by eellison** [comment]
And @zou3519 symints should already be part of the lowering. Maybe there are fixes to be had but shouldn't be changing as part of this PR.

**Comment by zou3519** [comment]
Output node sounds good to me then

**Comment by yifuwang** [comment]
Thanks for the input @eellison @zou3519!

> Also, one interesting case is what happens if the strides contain symints.

It seems that in `GraphLowering`, we simply skip the fixing up for such tensors: https://github.com/pytorch/pytorch/blob/main/torch/_inductor/graph.py#L1426

> Output node sounds good to me then

Just to confirm - we want the metadata to be on the output node (i.e. the node whose op is "output"), not the args of output node, right?

**Comment by yifuwang** [comment]
> Can you add a more explicit test? Take a graph, run a custom FX graph pass on it that changes strides, ensure that the output still has the same stride.

@Chillee added `test_stride_preservation_with_stride_modifying_fx_pass`.

**Review by Chillee — APPROVED** [review]

**Comment by ezyang** [comment]
Slight compile time regression on hrnet_w18 training:

image

**Comment by yifuwang** [comment]
@ezyang have you confirmed if this PR caused the regression? If so, I guess the efficiency of `is_user_visible_output()` could be improved.

**Comment by ezyang** [comment]
The change in compile time looks pretty stable here, I have not reproed locally but it's probably not hard.

**Pull request closed without merging**
