### PR TITLE
[PyTorch] Support norm_first in nn.TransformerEncoderLayer fast path

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #78269

Straightforward after previous diffs in stack cleaning up code and adding test coverage.

Differential Revision: [D36564008](https://our.internmc.facebook.com/intern/diff/D36564008/)

### CODE REVIEW

**Review by jbschlosser — APPROVED** [review]
Changes look good once test coverage in previous PR lands

**Comment by swolchok** [comment]
XLA is an infra flake

**Pull request closed without merging**
