### PR TITLE
[ATen][Native] fixes sparse SPMV on aarch64

### LINKED ISSUE #127491: Multiplying a sparse CSR tensor by a strided vector nondeterministically fails on MacOS ARM64
### 🐛 Describe the bug

If `T` is a sparse CSR tensor of size `(r,c)` and `v` is a dense tensor of size `c`, `torch.mv(T, v)` (or `T @ v`) nondeterministically and incorrectly produces in `NaN` for some resulting values, but only on macOS ARM64.

Since this behavior is nondeterministic, it is difficult to provide a few-line reproducer. I discovered the bug with Hypothesis, which can reliably generate test cases that uncover it. It seems to be fully nondeterministic — the same inputs will sometimes produce a correct result and sometimes incorrect.

I originally discovered this through another code base, but have created a Git repo that contains a minimal test case + Hypothesis example generator to reproduce the bug: https://github.com/mdekstrand/torch-spmv-bug-repro

The failure is demonstrated (along with `collect_env.py` output) in the included GitHub Actions workflow: <https://github.com/mdekstrand/torch-spmv-bug-repro/actions/runs/9295087560/job/25581446413>

This test fails only on macOS on Apple Silicon. I can reproduce the failure both on GitHub Actions and on my MacBook. The test passes on x86-64 on Windows, Linux, and macOS. It also passes locally in Linux aarch64 (in Parallels on my MacBook).

These tests are using the official PyTorch Conda packages for Linux, Windows, and macOS x86-64, and the conda-forge PyTorch packages for macOS x86-64 and Linux aarch64.

COO tensors seem to work correctly; the bug reproduces with CSR tensors. I have also tested CSC and seen it fail, but the current docs do not indicate CSC is supposed to work. I have also tested (in my other codebase) using CUDA on Linux, and it also passes the tests. Only CPU on macOS arm64 seems to be affected.

### Versions

Collecting environment information...
PyTorch version: 2.3.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:34:54) [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.3.0
[conda] numpy                     1.26.4          py311h7125741_0    conda-forge
[conda] pytorch                   2.3.0                  py3.11_0    pytorch

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jcaip @malfet @snadampal

### PR DESCRIPTION
**Pull request by Aidyn-A**
Fixes #127491
In #127491 result was allocated as `result = at::empty(...)`, which does not guarantee `result` being filled by zeros, therefore `torch.mv` was producing non-finite values. This happened mainly because the corner case (`beta = 0`) of `addmv` was not taken care of, as it should be just like in any other `addmv`/`addmm`:
https://github.com/pytorch/pytorch/blob/923edef31c7f3e98a14625724f2019b1422dcb26/aten/src/ATen/native/mkl/SparseBlasImpl.cpp#L307-L311

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Review by malfet — COMMENTED** [review]
LGTM, though it would be nice to add regression test for it.

**Comment by Aidyn-A** [comment]
\easycla

**Pull request closed without merging**
