### PR TITLE
be: Remove unused docker folder

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #72884

These dockerfiles were old and unused so removing them to reduce the
amount of confusion we may have over what these actually do.

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

Differential Revision: [D34253509](https://our.internmc.facebook.com/intern/diff/D34253509)

### CODE REVIEW

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34253509).

**Review by janeyx99 — APPROVED** [review]
yayayayya BE

**Comment by janeyx99** [comment]
> @pytorchbot merge this please

this shouldn't work i don't think

**Comment by seemethere** [comment]
It shouldn't, since it's not covered under the merge rules

**Pull request closed without merging**
