### PR TITLE
Enable unary elementwise inplace ops for all sparse compressed layouts.

### LINKED ISSUE #84998: torch.zeros with CSC layout throws INTERNAL ASSERT exception
## Issue description

As in the title.

## Code example

```python
>>> torch.zeros((2, 3), layout=torch.sparse_csc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: self.is_sparse_csr() INTERNAL ASSERT FAILED at "../aten/src/ATen/native/sparse/SparseCsrTensorMath.cpp":166, please report a bug to PyTorch. 
```

Expecting a CSC tensor with valid metadata (nnz=0, etc).

- PyTorch version: the current master.

cc @nikitaved @cpuhrsch @amjames @bhosmer

### PR DESCRIPTION
**Pull request by pearu**
Fixes #84998
Unblocks #84897

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #85031
* #85030

### CODE REVIEW

**Comment by cpuhrsch** [comment]
Is it really necessary to turn on support for all zero preserving unary operators to resolve this? I don't think we have good tests for view semantics + autograd for sparse layouts. In particular I'm worried about transpose + <some in-place operation>.

**Comment by pearu** [comment]
> Is it really necessary to turn on support for all zero preserving unary operators to resolve this? I don't think we have good tests for view semantics + autograd for sparse layouts. In particular I'm worried about transpose + .

@cpuhrsch The question is OT because the unary operations that are affected here are element-wise operations such as `abs`, `sin`. These operations are defined by invariant `op(sparse).values() == op(sparse.values())` and are sparse layout independent. transpose + operations do not belong to this class of operations.

I have updated the PR title but I think this has been confusing because of the naming of `unary_op` templates in SparseCsrTensorMath.cpp. These should really read `unary_ufunc_out`,  `unary_ufunc_inplace`, etc, for instance, or similar. Do we want to rename these templates for clarity?

**Comment by cpuhrsch** [comment]
Ok, but the question still stands that this PR doesn't introduce tests for inplace unary ops for sparse compressed layouts. Do we have those somewhere, but they're just not enabled?

**Comment by amjames** [comment]
The only place where the unary_inplace_op template is used is for `zeros_` correct? We should verify there are tests for that, and expand them to cover all layouts.

**Comment by pearu** [comment]
> Ok, but the question still stands that this PR doesn't introduce tests for inplace unary ops for sparse compressed layouts. Do we have those somewhere, but they're just not enabled?

The PR does not introduce the tests because these already exist (see test_sparse_csr_unary_inplace in test_sparse_csr.py), however, the tests are run on CSR samples only. Because the `unary_op_inplace` implementation does not depend on the layout, it is not an issue. Notice that the original assert check was on the dispatch key (that we later turned to a check on layouts) was there for sanity and, in principle, now checking for all compressed sparse layouts in `unary_op_inplace` restores the original intent of the assert statement: make sure that the template is used on compressed sparse tensors only. In fact, the template is very general, it only requires that the input to it has `.values()` method defined, so, restricting the template to specific sparse layouts as it was before, has little sense.

> The only place where the unary_inplace_op template is used is for zeros_ correct?

Incorrect. The template is used for all unary elementwise ops that preserve zeros. In fact, after #85030, `zero_` does not use the `unary_inplace_op` template anymore. Moreover, `zero_` OpInfo definition does not define it as a unary operation and there are no samples with sparse layouts generated for `zero_` tests. The same problem exists for all other factory functions having the `layout` argument but, while it is an issue, it is OT here.

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
