### PR TITLE
Add None return type to init

### PR DESCRIPTION
**Pull request by oulgen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #132376
* #132352
* #132351
* __->__ #132335

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @LucasLLC @MeetVadakkanchery @mhorowitz

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Why not.
This will regress unless we add lint though.

**Comment by oulgen** [comment]
@albanD yeah, ideally we remove all the mypy ignores.

I did this via
```
fastmod "def __init__\(self\):$" "def __init__(self) -> None:" torch
```
so if this regresses, it is ok.

**Comment by XuehaiPan** [comment]
> I did this via
> 
> ```
> fastmod "def __init__\(self\):$" "def __init__(self) -> None:" torch
> ```
> 
> so if this regresses, it is ok.

You can try this:

```bash
ruff check --select=ANN204 --fix-only --fix --unsafe-fixes torch
```

It will add return type for `__init__`, `__eq__`, `__ne__`, `__len__`, `__hash__`, `__str__`, `__repr__`, `__int__`, `__float__`, `__setitem__`, `__setattr__`.

See also: <https://docs.astral.sh/ruff/rules/missing-return-type-special-method>

**Pull request closed without merging**
