### PR TITLE
Merging the implementations of ClearProfiling

### PR DESCRIPTION
**Pull request by Gamrix**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #67575
* #67500
* #66973
* #66948

Differential Revision: [D32497548](https://our.internmc.facebook.com/intern/diff/D32497548)

### CODE REVIEW

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Comment by Krovatkin** [comment]
@Gamrix  thanks for doing this!

**Comment by Gamrix** [comment]
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32175959).

**Comment by Gamrix** [comment]
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32175959).

**Comment by Gamrix** [comment]
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32175959).

**Comment by Gamrix** [comment]
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32497548).

**Pull request closed without merging**
