### PR TITLE
decomposition spectral ops fixes

### LINKED ISSUE #105986: Inconsistent behavior for _refs.fft.* operators when input is an empty tensor
### 🐛 Describe the bug

In eager mode when an empty tensor input is used for a torch.fft.* function it seems that the expectation is for it to fail as per this test:

https://github.com/pytorch/pytorch/blob/a361fceef39766e839fbfe813d195339c66b5391/test/test_spectral_ops.py#L236-L244

In eager mode this seems to be validated here:
https://github.com/pytorch/pytorch/blob/a361fceef39766e839fbfe813d195339c66b5391/aten/src/ATen/native/SpectralOps.cpp#L236

When trying to enable this test for the version of the operators under torch/_refs the behavior is inconsistent

```
FAILED [0.0393s] test/test_spectral_ops.py::TestFFTCPU::test_empty_fft__refs_fft_fft_cpu_complex64 - AssertionError: RuntimeError not raised
FAILED [0.0237s] test/test_spectral_ops.py::TestFFTCPU::test_empty_fft__refs_fft_fft_cpu_float32 - AssertionError: RuntimeError not raised
FAILED [0.0109s] test/test_spectral_ops.py::TestFFTCPU::test_empty_fft__refs_fft_hfft_cpu_complex64 - AssertionError: "Invalid number of data points \([-\...
FAILED [0.0404s] test/test_spectral_ops.py::TestFFTCPU::test_empty_fft__refs_fft_hfft_cpu_float32 - AssertionError: "Invalid number of data points \([-\d]...
FAILED [0.0115s] test/test_spectral_ops.py::TestFFTCPU::test_empty_fft__refs_fft_ifft_cpu_complex64 - ZeroDivisionError: division by zero
FAILED [0.0120s] test/test_spectral_ops.py::TestFFTCPU::test_empty_fft__refs_fft_ifft_cpu_float32 - ZeroDivisionError: division by zero
FAILED [0.0114s] test/test_spectral_ops.py::TestFFTCPU::test_empty_fft__refs_fft_ihfft_cpu_float32 - ZeroDivisionError: division by zero
FAILED [0.0109s] test/test_spectral_ops.py::TestFFTCPU::test_empty_fft__refs_fft_irfft_cpu_complex64 - AssertionError: "Invalid number of data points \([-...
FAILED [0.0111s] test/test_spectral_ops.py::TestFFTCPU::test_empty_fft__refs_fft_irfft_cpu_float32 - AssertionError: "Invalid number of data points \([-\d...
FAILED [0.0114s] test/test_spectral_ops.py::TestFFTCPU::test_empty_fft__refs_fft_rfft_cpu_float32 - AssertionError: RuntimeError not raised
```

Repro of the difference:
```
>>> t = torch.empty(1, 0, device='cpu', dtype=torch.float32)
>>> torch.fft.fft(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Invalid number of data points (0) specified
>>> torch._refs.fft.fft(t)
tensor([], size=(1, 0), dtype=torch.complex64)
>>> torch._refs.fft.hfft(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/d/Programming/pytorch/torch/_prims_common/wrappers.py", line 227, in _fn
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Programming/pytorch/torch/_refs/fft.py", line 238, in hfft
    return _fft_c2r("hfft", input, n, dim, norm, forward=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/Programming/pytorch/torch/_refs/fft.py", line 119, in _fft_c2r
    torch._check(
  File "/mnt/d/Programming/pytorch/torch/__init__.py", line 987, in _check
    _check_with(RuntimeError, cond, message)
  File "/mnt/d/Programming/pytorch/torch/__init__.py", line 970, in _check_with
    raise error_type(message_evaluated)
RuntimeError: Invalid number of data points (None) specified
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git45bcd74
Is debug build: True
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
Clang version: 15.0.7
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.11.3 (tags/v3.11.3:f3909b8bc8, May 16 2023, 16:08:28) [Clang 15.0.7 ] (64-bit runtime)
Python platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1060 6GB
Nvidia driver version: 531.61
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 2700X Eight-Core Processor
CPU family:                      23
Model:                           8
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        2
BogoMIPS:                        7386.26
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr virt_ssbd arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload
Virtualization:                  AMD-V
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       192 KiB (6 instances)
L1i cache:                       384 KiB (6 instances)
L2 cache:                        3 MiB (6 instances)
L3 cache:                        8 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+7d1a95b046
[pip3] torch==2.1.0a0+git2563111
[conda] magma-cuda121             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342
[conda] mkl-include               2023.1.0         h06a4308_46342

cc @ezyang @mruberry @Lezcano @peterbell10 @SherlockNoMad

### LINKED ISSUE #108204: Inconsistent dtype handling between eager mode and primtorch fft operators
### 🐛 Describe the bug

While enabling the test case below for primtorch:
https://github.com/pytorch/pytorch/blob/cd07214a41d9e160082d4f8070926f5b77a3d34e/test/test_spectral_ops.py#L321-L335

Some inconsistencies were found where in eager mode the error message printed is generic for most cases `Unsupported dtype` while for primtorch the message is dependent on the device matching the regex `(\w+)FFT doesn't support tensors* of type` where `(\w+)` can be `MKL ` incase of MKL implementation or `cu` for cuda implementation. The issue seems to stem from the fact that in eager mode the error is handled at a device independent layer here:
https://github.com/pytorch/pytorch/blob/cd07214a41d9e160082d4f8070926f5b77a3d34e/aten/src/ATen/native/SpectralOps.cpp#L74-L93

Which is done before calling the `at::fft*` functions. For primtorch the similarly named function doesn't do the check so it ends up falling through to the device level checks:

https://github.com/pytorch/pytorch/blob/cd07214a41d9e160082d4f8070926f5b77a3d34e/torch/_refs/fft.py#L57-L69

Some of the functions also don't throw any error since the type is promoted to a higher precision type first. This is any operator that calls ` _maybe_promote_tensor_fft(input, require_complex=True)` with `require_complex=True`. These include _refs.fft.(hfft|fftn|ifftn|irfftn|hfftn)

https://github.com/pytorch/pytorch/blob/cd07214a41d9e160082d4f8070926f5b77a3d34e/torch/_refs/fft.py#L445-L459

### Versions

PyTorch version: 2.1.0a0+git47f735a
Is debug build: True
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
Clang version: 15.0.7
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.11.3 (tags/v3.11.3:f3909b8bc8, May 16 2023, 16:08:28) [Clang 15.0.7 ] (64-bit runtime)
Python platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1060 6GB
Nvidia driver version: 531.61
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 2700X Eight-Core Processor
CPU family:                      23
Model:                           8
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        2
BogoMIPS:                        7386.25
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr virt_ssbd arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload
Virtualization:                  AMD-V
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       192 KiB (6 instances)
L1i cache:                       384 KiB (6 instances)
L2 cache:                        3 MiB (6 instances)
L3 cache:                        8 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+7d1a95b046
[pip3] torch==2.1.0a0+git47f735a
[conda] magma-cuda121             2.6.1                         1    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342
[conda] mkl-include               2023.1.0         h06a4308_46342

cc @ezyang @mruberry @Lezcano @peterbell10 @msaroufim @wconstab @bdhirsh @anijain2305

### LINKED ISSUE #108205: Inconsistent dim handling between eager mode and primtorch *fftn operators
### 🐛 Describe the bug

Issue identified while enabling this test case for primtorch operators:
https://github.com/pytorch/pytorch/blob/cd07214a41d9e160082d4f8070926f5b77a3d34e/test/test_spectral_ops.py#L442-L461

2 issues were found. The 1st is that while in eager mode the first two error messages are the same but for primtorch ops the messages are different. For primtorch ops the fist message is `dims must be unique` but the 2nd message is `duplicate value in the list of dims`. 

For eager mode the dims are checked here:
https://github.com/pytorch/pytorch/blob/cd07214a41d9e160082d4f8070926f5b77a3d34e/aten/src/ATen/native/SpectralOps.cpp#L285-L301

Whereas primtorch ops have a similar function, it doesn't seem to be correct, where the `torch.check` uses the uncanonical dims for comparison instead of the canonical ones: 

https://github.com/pytorch/pytorch/blob/cd07214a41d9e160082d4f8070926f5b77a3d34e/torch/_refs/fft.py#L257-L270

And most of the cases end up falling through to the `_fft_*_meta` functions which flag the error through a call to `utils.validate_no_repeating_dims` .

https://github.com/pytorch/pytorch/blob/cd07214a41d9e160082d4f8070926f5b77a3d34e/torch/_prims/__init__.py#L2888-L2901

In the case of `_refs.fft.hfftn` and `_refs.fft.ihfftn` the 2nd Runtime error is not flagged at all since the last dimension is not used when making the latter call.  Which makes it a more impactful mismatched product behavior and not just a mismatched message.

https://github.com/pytorch/pytorch/blob/cd07214a41d9e160082d4f8070926f5b77a3d34e/torch/_refs/fft.py#L464-L480

https://github.com/pytorch/pytorch/blob/cd07214a41d9e160082d4f8070926f5b77a3d34e/torch/_refs/fft.py#L385-L408

### Versions

PyTorch version: 2.1.0a0+git47f735a
Is debug build: True
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
Clang version: 15.0.7
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.11.3 (tags/v3.11.3:f3909b8bc8, May 16 2023, 16:08:28) [Clang 15.0.7 ] (64-bit runtime)
Python platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1060 6GB
Nvidia driver version: 531.61
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Address sizes: 48 bits physical, 48 bits virtual
Byte Order: Little Endian
CPU(s): 12
On-line CPU(s) list: 0-11
Vendor ID: AuthenticAMD
Model name: AMD Ryzen 7 2700X Eight-Core Processor
CPU family: 23
Model: 8
Thread(s) per core: 2
Core(s) per socket: 6
Socket(s): 1
Stepping: 2
BogoMIPS: 7386.25
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr virt_ssbd arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload
Virtualization: AMD-V
Hypervisor vendor: Microsoft
Virtualization type: full
L1d cache: 192 KiB (6 instances)
L1i cache: 384 KiB (6 instances)
L2 cache: 3 MiB (6 instances)
L3 cache: 8 MiB (1 instance)
Vulnerability Itlb multihit: Not affected
Vulnerability L1tf: Not affected
Vulnerability Mds: Not affected
Vulnerability Meltdown: Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1: Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2: Mitigation; Full AMD retpoline, IBPB conditional, STIBP disabled, RSB filling
Vulnerability Srbds: Not affected
Vulnerability Tsx async abort: Not affected

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-triton==2.1.0+7d1a95b046
[pip3] torch==2.1.0a0+git47f735a
[conda] magma-cuda121 2.6.1 1 pytorch
[conda] mkl 2023.1.0 h6d00ec8_46342
[conda] mkl-include 2023.1.0 h06a4308_46342

cc @ezyang @mruberry @Lezcano @peterbell10 @msaroufim @wconstab @bdhirsh @anijain2305

### PR DESCRIPTION
**Pull request by ekamiti**
Fixes https://github.com/pytorch/pytorch/issues/105986, Fixes https://github.com/pytorch/pytorch/issues/108204, Fixes https://github.com/pytorch/pytorch/issues/108205

Fix all issues flagged when making changes for https://github.com/pytorch/pytorch/pull/107421

cc @SherlockNoMad

### CODE REVIEW

**Comment by ekamiti** [comment]
@ezyang This PR fixes the issues highlighted by PR https://github.com/pytorch/pytorch/pull/107421 though since that previous PR has not yet merged the changes in it are contained in this PR as well. I'd like for the first PR to merge first before merging this one so the test changes and product changes can have clean separation but I'd like to get the review started on this one in case you have some feedback already. Thanks for all your reviews!

**Review by ezyang — APPROVED** [review]

**Comment by ekamiti** [comment]
@ezyang The failures blocking the merge seem unrelated to these changes, not sure how to bypass such failures and I'd appreciate a pointer. Thanks!

**Pull request closed without merging**
