### PR TITLE
CI Sev - pin docker images for A100 workers

### PR DESCRIPTION
**Pull request by atalman**
Pinning docker images, trying to address SEV : https://github.com/pytorch/pytorch/issues/108862

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
This looks good, but you probably want to cancel the nightly job and force merge it this case because it takes like 8 hours or something to finish that one.

**Comment by ezyang** [comment]
It seems like... it didn't work?

**Comment by atalman** [comment]
> It seems like... it didn't work?

I think I found the problem it did not worked. Manual remediation step is required. Worth giving it a shot. Will merge this now, and run manual remediation.

**Pull request closed without merging**
