### PR TITLE
Add zero padding module

### PR DESCRIPTION
**Pull request by andrewgiessel**
Addresses #1324 

Since `F.pad` simply wraps [`ConstantPad2d`](https://github.com/pytorch/pytorch/blob/master/torch/nn/_functions/padding.py), I used `ConstantPad2d` instead.

### CODE REVIEW

**Comment by fmassa** [comment]
Why restrict it to zero padding, and not just make a ConstantPad2d a module as well?

**Comment by andrewgiessel** [comment]
Sure, I can do that good idea

**Comment by andrewgiessel** [comment]
Added `ConstantPad2d()`.  There was a namespace conflict, and so I imported `ConstantPad2d` (the function) as `F_ConstantPad2d`.  Another option would have been to import the whole namespace as `F`.  Let me know what is preferred, and I'm happy to change.

Also the tests are failing for some import reason, even after @soumith's commit.  I assume I need to add the import someplace else, but I'm not sure where.

**Comment by andrewgiessel** [comment]
This is ready for review, I think.  Thanks!

@apaszke @soumith @fmassa

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
thanks Andrew!

**Comment by fmassa** [comment]
Hi, thanks for the PR!
One question: why add `ZeroPad2d` when we have `ConstantPad2d`?

**Comment by soumith** [comment]
had a discussion with @apaszke 

we think it's best to deprecate all padding layers to F.pad and nn.Pad and all crop layers to F.crop and nn.Crop

so please expect this pr to be deprecated soon.

**Comment by andrewgiessel** [comment]
@soumith sure, that seems like a good idea.  Can I do anything to help?

**Pull request merged**
