### PR TITLE
[ci] disable docs build

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #80313

This is flaky, which creates noisy signal and blocks merges. Disabling
as it while we investigate.

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
I don't think we can just disable the doc builds, we have to live with the flakiness, but this should be a hi-pri to fix it

**Review by malfet — APPROVED** [review]
Looks sad to me :(

And it looks it disables it for both PRs and nightlies (thanks to build system unification), please highlight that in PR description as well

**Review by seemethere — APPROVED** [review]

**Comment by malfet** [comment]
@pytorch merge -f

**Comment by suo** [comment]
don't merge this yet, I think something is wrong with it

**Pull request closed without merging**
