### PR TITLE
Functional bias_add

### PR DESCRIPTION
**Pull request by szagoruyko**
This is occasionally very useful to avoid slow expands. Added doc for F.linear too

Depends on https://github.com/pytorch/pytorch/pull/851

### CODE REVIEW

**Comment by soumith** [comment]
why have a separate function called bias_add? it's just an `expand over the mini-batch + add`

**Comment by szagoruyko** [comment]
@soumith expands are very slow on GPU, that's why we use sger in F.linear and not expand, for example.

**Comment by fmassa** [comment]
While I see that this is more efficient and expand + add, I think that we will (soon?) be adding automatic broadcast to torch tensors, so this might look weird. I wonder if there is a way to optimize the pointwise operations in THC for the stride 0 case... that might be the cleanest solution.

**Comment by szagoruyko** [comment]
@fmassa naive expand-broadcasting would prob be very slow, I guess it could be made to recognize CUBLAS ops and use them?

**Comment by fmassa** [comment]
@szagoruyko a **very dirty** hack for this specific case would be to add the code in this PR in [here](https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/generic/THCTensorMathPairwise.cu#L15), by asserting the dimensions of both tensors and that the stride of the 2nd tensor is 0, and calling the underlying cuBLAS routine.
But I wonder if we can do something in the pointwise kernels themselves...

**Comment by apaszke** [comment]
@fmassa I think it makes sense, because it won't be covered by the automatic broadcasting, and will allow for doing that in an efficient way. Broadcast can only unsqueeze additional dimensions at the front of the tensor, while in this case you actually want to unsqueeze one at the front and N-2 at the back.

**Comment by ngimel** [comment]
I must be missing something - why are expands slow on the GPU? Those are CPU operations setting the necessary dimensions and strides, without operations on the underlying GPU data. I was experimenting recently with replacing creating add_buffer and addr_ with expand and add for Linear, and while cublas ger_kernel is usually faster than torch's pointwiseApply2, overall time is on par or slightly less (because in the first case, input.new(1).resize().fill_ translates into cudaMemset, a bunch of cudaGetDevice/cudaSetDevice (why so many?), launching pointwiseApply1 kernel to fill, and only then launching cublas ger_kernel). There is no reason why torch's pointwiseApply kernels should be much slower than cublas - they can be improved by adding unrolls and handling 0 strides more efficiently, except bias_add is rarely a bottleneck, so no one is doing it. 
cudnn has addTensor and opTensor that handle addition with broadcasting, but they are a pain to use and have strange performance holes for some sizes.

**Comment by apaszke** [comment]
I'm not sure if it's the right way to use biases on the GPU. I just ran a quick benchmark and it seems that `addr_` is 20x slower than `expand_as` + `add_`. Here's the script (requires Python>=3.3):
```python
import torch
import time                             
                                    
x = torch.randn(4000).cuda()        
y = torch.zeros(128, 4000).cuda()   
                                    
                    
s = time.perf_counter()             
for i in range(1000):               
    add_buffer = x.new(128).fill_(1)
    y.addr_(add_buffer, x)          
torch.cuda.synchronize()            
print(time.perf_counter() - s)      
                                    
s = time.perf_counter()             
for i in range(1000):               
    y.add_(x.expand_as(y))          
torch.cuda.synchronize()            
print(time.perf_counter() - s)      
```

And the results are:
```
0.23105818685144186
0.01973715308122337
```

**Comment by ngimel** [comment]
Depends on the sizes. Also, once extra overhead of a dozen getDevice/setDevice for every pointwise kernel is taken care of, addr_ can be better. But overall you are right, for medium to small sizes, expand_as is faster than addr_ (expand_as + add is a single pointwise apply kernel, addr is create tensor (for some reason there is memcopy there), fill (overhead of starting a pointwise kernel), call cublas). Even though cublas ger kernel is usually faster than torch's pointwiseApply, when all overheads are taken into account expand_as + add wins.

**Comment by ngimel** [comment]
For backwards though expand_as becomes a sum, and there were some issues with the sum speed on CPU? (GPU is Ok there, though once again torch's reduce kernel is slower than cublas gemv, but overheads are less, for a net win).

**Comment by apaszke** [comment]
Actually I just realized that I forgot to synchronize after creating the input, so the addr time was skewed by the CPU copy. This is a new script, and it seems that addr is consistently faster 1.4x faster than expand + add 😕 

```python
import torch                                                             
import time                                                              
                                                                         
batch_size = 32                                                          
features = 128                                                           
                                                                         
for batch_size in (2 ** i for i in range(5, 11)):                        
    for features in (2 ** i for i in range(5, 11)):                      
        x = torch.randn(features).cuda()                                 
        y = torch.zeros(batch_size, features).cuda()                     
        torch.cuda.synchronize()                                         
                                                                         
        s = time.perf_counter()                                          
        for i in range(1000):                                            
            add_buffer = x.new(batch_size).fill_(1)                      
            y.addr_(add_buffer, x)                                       
        torch.cuda.synchronize()                                         
        addr_t = time.perf_counter() - s                                 
                                                                         
        s = time.perf_counter()                                          
        for i in range(1000):                                            
            y.add_(x.expand_as(y))                                       
        torch.cuda.synchronize()                                         
        expand_t = time.perf_counter() - s                               
        print('{}\t{}\t{:.4f}\t{:.4f}\t{:.2f}'.format(                   
              batch_size, features, addr_t, expand_t, addr_t / expand_t))
```

**Comment by ngimel** [comment]
Ha! In linear add bias is implemented as 
```
add_buffer=input.new(1).resize_(input.size(0)).fill_(1)
```
https://github.com/pytorch/pytorch/blob/master/torch/nn/_functions/linear.py#L13
and when I modify your script to do this, addr is 20% slower than expand_as. 
I guess linear should be fixed.

**Comment by soumith** [comment]
as discussed offline, this PR is kinda redundant. The speed benefits are negative (unlike what we originally thought).
So closing this out.

**Pull request closed without merging**
