### PR TITLE
Enable UFMT on test/test_public_bindings.py

### PR DESCRIPTION
**Pull request by dilililiwhy**
Part of: https://github.com/pytorch/pytorch/issues/123062

Ran lintrunner on:
> test/test_public_bindings.py

Detail:
```
$ lintrunner -a --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```
cc @albanD @ezyang

### CODE REVIEW

**Comment by dilililiwhy** [comment]
@ezyang Could you have a look at this PR? Thanks.

**Review by ezyang — DISMISSED** [review]

**Review by malfet — APPROVED** [review]

**Comment by jeanschmidt** [comment]
Hey, a headsup, it seems this PR introduced failures on windows testing: https://github.com/pytorch/pytorch/actions/runs/9730750763/job/26854679861

**Comment by dilililiwhy** [comment]
It seems that PR https://github.com/pytorch/pytorch/pull/129340 fix the test failure.
@pytorchbot merge -f "reland pr"

**Comment by dilililiwhy** [comment]
It seems that PR https://github.com/pytorch/pytorch/pull/129340 fix the test failure.
@pytorchbot merge

**Pull request closed without merging**
