### PR TITLE
[6/N] Replace c10::optional with std::optional

### PR DESCRIPTION
**Pull request by cyyever**
Follows #130408

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @chauhang

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]

**Comment by janeyx99** [comment]
Looked through changes, and they make sense to me (optional -> std::optional) following previous similar PRs. Question: is the goal to eventually get rid of c10::optional?

**Comment by cyyever** [comment]
@janeyx99 Yes, I want to get rid of c10::optional in the end.

**Pull request closed without merging**
