### PR TITLE
[ONNX] Enable onnx model tests for opset 11

### PR DESCRIPTION
**Pull request by BowenBao**
Add default value for flag `keep_initializers_as_inputs`. This is required for opset 11 tests.

### CODE REVIEW

**Comment by yf225** [comment]
@houseroad Would you like to review this PR? Thanks!

**Review by houseroad — APPROVED** [review]
Thanks for enabling it. Somehow, i lost the detection of this PR. Do you mind to rebase it to master, so I can land it.

**Comment by BowenBao** [comment]
@houseroad thanks for digging this up, rebasing now

**Comment by BowenBao** [comment]
closed due to completed in other PR.

**Pull request closed without merging**
