### PR TITLE
Generalize devices specific UTs  for dynamo

### PR DESCRIPTION
**Pull request by ankurneog**
## Motivation
This is follow up to PR:https://github.com/pytorch/pytorch/pull/126970, adding facility to run content for Intel Gaudi devices.
We intend to extend similar generalization for the rest of the content in test/dynamo  which is currently being written to work specifically for cuda devices. Other devices can add onto it if support is available.

## Changes
 carve out bert related content to another class
 use instantiate_device_type utility to instantiate this class for devices which support the functionality 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Comment by ankurneog** [comment]
@albanD  : Could you please help with this review. Thanks

**Comment by albanD** [comment]
@anijain2305 who's the right person on the Dynamo side to review this kind of PRs?

**Comment by ankurneog** [comment]
@anijain2305  : can you please help with the review , thanks.

**Review by anijain2305 — APPROVED** [review]

**Pull request closed without merging**
