### PR TITLE
ci: Move ssh setup to it's own action

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74774
* __->__ #74773

SSH setup was being hidden away in the setup step for both linux and
windows, this moves it out to it's own step so that users can know where
to click to get ssh details

Fixes https://github.com/pytorch/pytorch/issues/74476

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

### CODE REVIEW

**Comment by seemethere** [comment]
<details>
<summary> verified to work on linux </summary>

Screen Shot 2022-03-25 at 1 25 38 PM

</details>

<details>
<summary> verified to work on windows </summary>


</details>

**Review by suo — APPROVED** [review]

**Review by malfet — APPROVED** [review]
LGTM, but can we somehow keep this within setup-linux action, so that it is always present for all workflows?

**Comment by seemethere** [comment]
> LGTM, but can we somehow keep this within setup-linux action, so that it is always present for all workflows?

We actually can't without hiding it away, which is the original stem of the problem :/

**Pull request closed without merging**
