### PR TITLE
Verbose param for schedulers that don't have it #38726

### PR DESCRIPTION
**Pull request by guol-fnst**
Verbose param for schedulers that don't have it #38726

### CODE REVIEW

**Comment by guol-fnst** [comment]
Hi @vincentqb 
Since this issue(#38726) have not been fixed for months, so I'm trying to work on it.
Could you please help to review this PR? 
Much appreciate!

**Comment by vincentqb** [comment]
Awesome, thanks! Just in case someone was using the keyword parameters as positional, can you make verbose the last parameter `__init__`?

**Comment by guol-fnst** [comment]
> Awesome, thanks! Just in case someone was using the keyword parameters as positional, can you make verbose the last parameter `__init__`?

Hi @vincentqb, thanks for your patience!
I have modified the code, any other advice?

**Review by vincentqb — APPROVED** [review]
LGTM, thanks!

**Pull request closed without merging**
