### PR TITLE
[nnc] Fixed warning due to implicit parameter conversion

### PR DESCRIPTION
**Pull request by navahgar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #64118
* __->__ #64117

The `nullptr` in `ExprHandle(nullptr)` was being implicitly converted to `bool` resulting in lot of warnings. 

Differential Revision: [D30616945](https://our.internmc.facebook.com/intern/diff/D30616945)

### CODE REVIEW

**Review by ZolotukhinM — COMMENTED** [review]
What's the behavior now? Should we allow this constructor at all?

**Comment by navahgar** [comment]
> What's the behavior now? Should we allow this constructor at all?

Here is the warning we get now:
```
expr.h:322:28: warning: implicit conversion of nullptr constant to 'bool' [-Wnull-conversion]
  VarHandle() : ExprHandle(nullptr) {}
                ~~~~~~~~~~ ^~~~~~~
                           false
```
This warning appears multiple times if we touch some core NNC files..

Good question about if we should allow this constructor. I'm not sure, if we have any use for it.

**Comment by navahgar** [comment]
If we remove this constructor, there are some places like the following, which fail:

`std::vector<VarHandle> result(v.size());`

**Review by ZolotukhinM — APPROVED** [review]
> Here is the warning we get now:

By "now" I meant with this change :)

If we decide to keep this constructor (since it's used somewhere), do you mind adding a comment what exactly it produces and making sure that it's actually what we wanted at those use cases?

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30616945).

**Comment by navahgar** [comment]
> By "now" I meant with this change :)

Aah okay. :) It just creates an empty `VarHandle` whose base `NodePtr` is `nullptr`. This is useful in places where we creates these empty vectors of `VarHandle`s and initialize them later.

> 
> If we decide to keep this constructor (since it's used somewhere), do you mind adding a comment what exactly it produces and making sure that it's actually what we wanted at those use cases?

Added a comment.

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30616945).

**Pull request closed without merging**
