### PR TITLE
optionally zero infinite losses in CTCLoss

### PR DESCRIPTION
**Pull request by t-vi**
Here is a stab at implementing an option to zero out infinite losses (and NaN gradients).
It might be nicer to move the zeroing to the respective kernels.
The default is currently `False` to mimic the old behaviour, but I'd be half inclined to set the default to `True`, because the behaviour wasn't consistent between CuDNN and Native anyways and the NaN gradients aren't terribly useful.

This topic seems to come up regularly, e.g. in  #14335

### CODE REVIEW

**Comment by t-vi** [comment]
@jinserk , @SeanNaren in case it's of interest to you.

**Comment by jinserk** [comment]
Thank you for letting me know!! :D

**Comment by t-vi** [comment]
I managed to reproduce the CI failures, so I'm hopeful to find the root cause soonish.

**Comment by t-vi** [comment]
So the errors don't speak to me as something related to the patch and I would think it is good to go.

**Comment by soumith** [comment]
I'd love to merge it, but it says there's merge conflicts.

**Comment by t-vi** [comment]
The big IntList rename hit it. I'll rebase.

**Comment by t-vi** [comment]
I think it should be good now.

**Review by ezyang — APPROVED** [review]

**Comment by chrisemezue** [comment]
@t-vi a naive question please:
If I am using CPU (mistakenly forgot to change Colab runtime to GPU) and I installed torch for cuda (`Version: 1.10.0+cu111`) and I am using the `zero_infinity = True` on CTCLoss, will the CPU-GPU difference make it not work?

I was having issues with the NaN loss even with `zero_infinity = True`. However, when I now changed runtime to GPU, it stopped.

I just want to be sure that the GPU-CPU difference (installing torch+cu and using CPU runtime) was definitely the issue.

**Pull request closed without merging**
