### PR TITLE
cleanup chromium event log on dynamo exit rather than on entry

### PR DESCRIPTION
**Pull request by xmfan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #140964
* __->__ #143175
* #141907

clearing at dynamo start is an issue because it throws away events from compiled autograd

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Comment by masnesral** [comment]
I'm not sure this does what @jamesjwu originally intended. 

The reset used to live here: https://github.com/pytorch/pytorch/blob/ea7d1826a288eb0387d7c545bf7b8ea684859113/torch/_dynamo/convert_frame.py#L863. I changed the usage of the chromium event here to use a contextmanager which made it easier to log a final chromium event with all the CompilationMetrics in it (I'd previously introduced a bug because the finally logic tripped me up). So as part of that change, I just moved the reset call into the context manager.

The comment on reset says:
```
        # We this on every compile in case a compile crashes or restarts and we haven't
        # cleared the stack.
```

So are we getting the same result? I guess we guarantee the chromium stack is always empty when we exit the contextmanager here, so it should always be empty on next entry? @jamesjwu do you agree?

@xmfan why do you need to change it anyway? I presume it's because you've added some chromium event data earlier and this reset call wipes it out too soon?

**Comment by jamesjwu** [comment]
I think it's fine to do it on exit, but only if you put it in a finally clause so that, no matter what, it's called. Can you test by compiling with some unit test that throws multiple times and make sure the perfetto looks correct?

**Comment by ezyang** [comment]
Deferring to @jamesjwu

**Review by Skylion007 — APPROVED** [review]

**Comment by xmfan** [comment]
Yeah I need this because we're gonna have a top-level context that wraps the entirety of dynamo_timed:

compiled_autograd_timed enter
  dynamo_timed enter
  dynamo_timed exit
compiled_autograd_timed exit

I don't think we need to support an interleaving pattern. The next hierarchical id we add is probably for subgraphs, which would be fully contained within the dynamo_timed one

**Comment by xmfan** [comment]
@jamesjwu `TORCH_TRACE=nanogpt_tlparse/ python benchmarks/dynamo/torchbench.py --training --backend=inductor --only nanogpt --repeat 5 --performance --warm-start-latency` Visually the chrome trace looks correct

https://manifold.edge.x2p.facebook.net/v0/read/tree/logs/.tmpFYXBZ3/dedicated_log_torch_trace_sju1dm5d.log/index.html?bucketName=tlparse_reports&apiKey=tlparse_reports-key&withPayload=1&timeoutMsec=100

https://manifold.edge.x2p.facebook.net/v0/read/tree/logs/.tmpFYXBZ3/dedicated_log_torch_trace_8in3rcas.log/index.html?bucketName=tlparse_reports&apiKey=tlparse_reports-key&withPayload=1&timeoutMsec=100

**Review by jamesjwu — APPROVED** [review]
LGTM

**Comment by jamesjwu** [comment]
> Yeah I need this because we're gonna have a top-level context that wraps the entirety of dynamo_timed

You might run into an issue where you're currently clearing the stack on exit of the dynamo event, but compiled_autograd will be wrapped around it (and you don't want to reset the stack with the compiled_autograd event attached to it). So when compiled_autograd is turned on, you want to clear the stack at the topmost entrypoint.

**Comment by xmfan** [comment]
sounds like we want to always defer logging and log clearing to the top level context, so we should restrict ourselves to chain of context managers at a time

**Pull request closed without merging**
