### PR TITLE
Add symbolic_shape_specialization structured trace

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #126450

This is typically the information you want when diagnosing why something
overspecialized in dynamic shapes.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]

**Comment by DanilBaibak** [comment]
Hi @ezyang! Sorry, I need to revert your PR because it breaks the internal build. Here you can find more information about the issue - [D57518787](https://www.internalfb.com/diff/D57518787).

**Pull request closed without merging**
