### PR TITLE
Fix exp decomp numerics

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #129154

Our previous implementation would sometimes generate `inf` because we did not do the same numerics tricks as in eager:

See comment / [link](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/core/TransformationHelper.h#L123-L144) :
```
    # curand_uniform has (0,1] bounds. log(1) is 0 and exponential excludes 0.
    # we need log to be not 0, and not underflow when converted to half
    # fast __logf approximation can underflow, so set log to -epsilon/2 for 1 or close to 1 args
```

Fix for https://github.com/pytorch/pytorch/issues/127749. 

Added a test for non-inf, but it would be great to have more robust decomp distribution tests.

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
nice fix!!

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
