### PR TITLE
use Bazelisk to fetch Bazel in CI

### PR DESCRIPTION
**Pull request by dagitses**
use Bazelisk to fetch Bazel in CI

Summary:

Advantages:
1. this is cross-platform, no MacOS specific code
2. this lets us use define the version of Bazel succinctly in
   .bazelversion (already provided)

Note that this change will upgrade our version of Bazel to 6.1.1.

Test Plan: Rely on CI.

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/pytorch/pull/101424).
* #101406
* #101405
* #101445
* __->__ #101424
* #101411

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!  I'll keep an eye out to see if this introduces new flaky issue as `bazelisk.py` downloads and setups bazel from what I see.   If it's flaky, I think we could move it to be part of the Docker image.

**Comment by huydhn** [comment]
@vors Just FYI

**Review by vors — APPROVED** [review]
nice, that's what I use locally for working with PyTorch OSS bazel build as well. Great to see it! @dagitses can we include buildifier in the lint step in CI?

**Comment by dagitses** [comment]
> LGTM! I'll keep an eye out to see if this introduces new flaky issue as `bazelisk.py` downloads and setups bazel from what I see. If it's flaky, I think we could move it to be part of the Docker image.

Thanks! I appreciate that. Hopefully it won't be too bad given that it's being downloaded from github. Presumably we have enough other stuff that has shared fate with github where we won't notice it.

**Comment by dagitses** [comment]
> nice, that's what I use locally for working with PyTorch OSS bazel build as well. Great to see it! @dagitses can we include buildifier in the lint step in CI?

@vors Yeah I think it makes sense to include buildifier. I have a lot on my plate right now but i'll see about adding that.

**Pull request closed without merging**
