### PR TITLE
Enable failing diffs for regressions on basic_modules_ListOfLinears benchmarks

### PR DESCRIPTION
**Pull request by laithsakka**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137541
Note that basic_modules_ListOfLinears_inductor_gpu_force_shape_pad is flay with 8% detected variance, 
I set it up with 20% threshold (8*2)++ 
others are stable within +-1.5%

Screenshot 2024-10-08 at 4 19 03 PM

Screenshot 2024-10-08 at 4 18 56 PM

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by aorenste — APPROVED** [review]

**Comment by laithsakka** [comment]
rebase

**Pull request closed without merging**
