### PR TITLE
[codemod] Match parameter names and = default

### PR DESCRIPTION
**Pull request by goldsborough**
More clang tidy cleanups in `torch/csrc`. This time:

1. `hicpp-use-equals-default` recommends `= default` instead of `{}` for constructors/destructors. This is better practice because it expresses the intent better (https://stackoverflow.com/questions/6502828/what-does-default-mean-after-a-class-function-declaration)
2. `readability-inconsistent-declaration-parameter-name` enforces that parameter names in the declaration match parameter names in the definition. This is just generally useful and can prevent confusion and bugs.

Also updated my script a little bit.

@apaszke @ezyang

### CODE REVIEW

**Comment by goldsborough** [comment]
stamptopia

**Comment by goldsborough** [comment]
@ezyang are we ok to merge this once tests pass?

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
