### PR TITLE
export helper funcs in foreach ops

### PR DESCRIPTION
**Pull request by heidongxianhua**
Fixes #ISSUE_NUMBER
export some helper funcs in foreach ops

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]

**Comment by heidongxianhua** [comment]
@janeyx99  sorry, this pr needs to be reverted, I give the wrong command to pytorchbot. It will cause build error on windows, 

```
C:/actions-runner/_work/pytorch/pytorch/aten/src\ATen/native/ForeachUtils.h(164): error: a function declared "dllimport" may not be defined

C:/actions-runner/_work/pytorch/pytorch/aten/src\ATen/native/ForeachUtils.h(203): error: a function declared "dllimport" may not be defined

C:/actions-runner/_work/pytorch/pytorch/aten/src\ATen/native/ForeachUtils.h(211): error: a function declared "dllimport" may not be defined

```

**Pull request closed without merging**
