### PR TITLE
Add OpInfo entry for alias_copy (#127232)

### PR DESCRIPTION
**Pull request by rec**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #127231
* __->__ #128142

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

### CODE REVIEW

**Review by lezcano — APPROVED** [review]

**Review by lezcano — APPROVED** [review]

**Comment by rec** [comment]
@DanilBaibakL of course, understand completely. :-)

These two tests unfortunately did not seem to fail on the previous CI run, so I'm somewhat at a loss to see what might have happened!

I'll re-check the previous run and consult with others before continuing.

**Comment by rec** [comment]
Gosh darn it, I cannot reproduce the failing test ` python test/test_custom_ops.py -k TestCustomOp.test_autograd_function_backed_op` on commit ID 2386045e4f0 (on the `main` branch).

**Pull request closed without merging**
