### PR TITLE
Made exception message for torch.LongTensor() legacy constructor more readable

### LINKED ISSUE #46085: Confusing error message for torch.LongTensor([1], device = 'cuda')
```
torch.LongTensor([1], device = 'cuda')
# RuntimeError: legacy constructor for device type: cpu was passed device type: cuda, but device type must be: cpu
```
`device type: cpu was passed device type: cuda` is hard to pass. adding some punctuation would help!

### PR DESCRIPTION
**Pull request by partypyro**
Fixes #46085 

exception_screenshot

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Seems sth is wrong with the diff: 866 files changed :(

**Comment by heitorschueroff** [comment]
Hi @partypyro, thanks for you PR. To follow up on the previous comment, it seems like something went wrong with the commit. Could you please rebase with master and make sure that only your changes are added to the commit? Thank you!

**Comment by partypyro** [comment]
You can safely reject this PR, I made a new PR that got pulled where I rebased with the master and fixed the errors

**Comment by heitorschueroff** [comment]
> You can safely reject this PR, I made a new PR that got pulled where I rebased with the master and fixed the errors

Ok, thank you for letting us know. Closing this PR as per the comment.

**Pull request closed without merging**
