### PR TITLE
Automatically update the functorch pinned commit

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #81404
* #81403

In the short term we want to give people a mechanism to tell which
commit of functorch works with which commit of PyTorch. This PR adds a
job that updates the pinned commit of functorch daily.

Test Plan:
- code reading

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@zou3519 you probably want to add the pin to https://github.com/pytorch/pytorch/blob/85efdec0604c4f9a39bbe3867b429369b993544e/.github/merge_rules.json#L56 so that it will auto-update on green CI

**Comment by zou3519** [comment]
Good point, thanks @malfet

**Comment by zou3519** [comment]
xla failure is pre-existing (see https://github.com/pytorch/pytorch/runs/7330012170?check_suite_focus=true) so I'm ignoring it

**Pull request closed without merging**
