### PR TITLE
[JIT][Symbolic Shape Analysis] expose op shape functions

### PR DESCRIPTION
**Pull request by makslevental**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #68564

let's try this again...

fixes https://github.com/pytorch/pytorch/issues/68204

cc @silvasean @eellison

Differential Revision: [D32576909](https://our.internmc.facebook.com/intern/diff/D32576909)

### CODE REVIEW

**Review by eellison — APPROVED** [review]
good to me if tests pass

**Comment by makslevental** [comment]
@silvasean i'm having a hard time landing this because of the `#include`

https://github.com/pytorch/pytorch/runs/4246587671?check_suite_focus=true

if you know how I could include a `.py` file directly as a dep of a `cc_library` in bazel I'd be able to land.

**Comment by silvasean** [comment]
Ooof, that could get tricky, and I don't know a solution off-hand. One idea is to include it in the "data" of the cc_library: https://docs.bazel.build/versions/main/be/common-definitions.html#typical.data

If that doesn't work, I can ping some folks who might know.

**Comment by makslevental** [comment]
just in case anyone is curious here's how you get python to eat modules that don't have `.py` extensions

```
import os
from importlib.machinery import SourceFileLoader
shape_function_fp = f"{os.path.dirname(os.path.realpath(torch.__file__))}/include/torch/csrc/jit/runtime/shape_functions.h"
_shapes = SourceFileLoader("shape_functions", shape_function_fp)
_shapes.load_module(None)
```

**Comment by makslevental** [comment]
@makslevental has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32576909).

**Comment by makslevental** [comment]
@makslevental has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32576909).

**Pull request closed without merging**
