### PR TITLE
[ROCm] remove triton-rocm commit pin and merge pins with triton.txt

### PR DESCRIPTION
**Pull request by jataylo**
cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang

### CODE REVIEW

**Comment by jataylo** [comment]
Hmm looks like we are hitting this for the many wheel job cc: @nmacchioni 

https://hud.pytorch.org/pr/pytorch/pytorch/133438#29064198846
```
2024-08-21T16:56:46.0878306Z ERROR: Could not find a version that satisfies the requirement pytorch-triton==3.0.0+55a4ab051c; platform_system == "Linux" and platform_machine == "x86_64" and python_version < "3.13" (from torch) (from versions: 2.0.0+0d7e753227, 2.0.0+3aa3d7024e, 2.0.0+af76c989eb, 2.0.0+b8b470bc59, 2.0.0+c8bfe3f548, 2.0.0+d54c04abe2, 2.1.0, 2.1.0+2c32f43999, 2.1.0+3c400e7818, 2.1.0+440fd1bf20, 2.1.0+46672772b4, 2.1.0+6e4932cda8, 2.1.0+7d1a95b046, 2.1.0+9820899b38, 2.1.0+9e3e10c5ed, 2.1.0+bcad9dabe1, 2.1.0+e6216047b8, 2.1.0+e650d3708b, 2.2.0+e28a256d71, 3.0.0+45fff310c8, 3.0.0+901819d2b6, 3.0.0+989adb9a29, 3.0.0+a9bc1a3647, 3.0.0+dedb7bdf33)
2024-08-21T16:56:46.1309596Z ERROR: No matching distribution found for pytorch-triton==3.0.0+55a4ab051c; platform_system == "Linux" and platform_machine == "x86_64" and python_version < "3.13"
```

And for the other jobs they are just aborting.  Strange...

**Comment by jataylo** [comment]
@malfet @jithunnair-amd any idea on these cancelled build manywheel docker image jobs? It's happening still after a couple of rebases.

**Comment by atalman** [comment]
@jataylo Here is the issue https://github.com/pytorch/pytorch/issues/134236 for ``` No matching distribution found for pytorch-triton==3.0.0+55a4ab051c``` error

**Comment by jataylo** [comment]
Failures are unrelated, ready for review.

**Review by jithunnair-amd — APPROVED** [review]

**Review by malfet — APPROVED** [review]
LGTM

**Comment by jithunnair-amd** [comment]
@jeanschmidt @atalman I'm not sure if it was this PR or just the fact that the upload binary CI job didn't succeed for this PR (due to the xpu binary build job failing?): https://hud.pytorch.org/hud/pytorch/pytorch/f71c3d265ab52589f983dd252d61461db4e7dbbd/1?per_page=50&name_filter=Triton

**Comment by jithunnair-amd** [comment]
Converting this to Draft for now, as we would like to bump the triton-rocm.txt commit first to pull in a FlexAttention change. Once that's done, we can pursue the unification of CUDA and ROCm triton commits in this PR.

**Comment by jithunnair-amd** [comment]
Manywheel builds failing due to triton installation error due to this issue: https://github.com/pytorch/pytorch/issues/134236

**Comment by ZainRizvi** [comment]
Actually, the right workflows were included in trunk.  Not sure why they didn't fail on your PR...perhaps you need to rebase?

**Comment by jataylo** [comment]
@ZainRizvi IIUC this issue is known https://github.com/pytorch/pytorch/issues/134236, @atalman can we merge with error until the wheel is successfully pushed out?

**Pull request closed without merging**
