### PR TITLE
ATen symbolic for expand

### PR DESCRIPTION
**Pull request by jamesr66a**

### CODE REVIEW

**Comment by ezyang** [comment]
@jamesr66a, are you interested in adding a mode that does all unrecognized ops as ATen? Similar to what we discussed at https://github.com/pytorch/pytorch/pull/3325#issuecomment-340216407 (see Zach's comment, and my comment below)? If merging this is enough to block you, we haven't hit the magic three, but if there are going to be much more, this might be a good investment.

**Comment by jamesr66a** [comment]
@bddppq does the ConvTBCFunction ATen operator work?

Context for everyone else is that we have one more for the 1-d sequence convolution in fairseq-py that is using aten, so we might hit 3

**Comment by bddppq** [comment]
@jamesr66a I have only exported ConvTBCFunction to onnx as an ATen op, but not ported it to ATen (so the exported op can not be really executed).

**Comment by jamesr66a** [comment]
Ok so then for the purposes of finishing the fairseq-py project I think we're good with just doing this op manually

**Comment by ezyang** [comment]
Ignore the 'default' build indicator

**Pull request merged**
