### PR TITLE
fix: potential logic error in fx partitioner.

### PR DESCRIPTION
**Pull request by SanftMonster**
### What this PR does

`CapabilityBasedPartitioner.propose_partitions` is responsible for creating valid partitions for a GraphModule. This PR is mainly to fix a potential BUG of it. Besides, it also help to speed up this method slightly.

1. In all pytorch source code including unit test, `allowed_single_node_partition_ops` is actually never used, which why this bug is 'potential'.
2. Considering the original code, when the `node.target` is in `allowed_single_node_partition_ops`, it simply self-add `compute_node_count` again to make it valid when the node of the one-node partition is among `allowed_single_node_partition_ops`. At most of time it works well, but what if in a partition there're two nodes in both `non_compute_ops` and `allowed_single_node_partition_ops`? We'll found there's no valid node in this partition but we don't remove it. Though it sounds stupid to have an op in both these two lists, we couldn't expect the user to be always careful enough for it.
3. The only usage of `compute_node_count` is to check if we should remove this partition, therefore we actually don't need to complete this loop every time. When we detect the partition is already safe for this check, we could skip the loop.

### CODE REVIEW

**Comment by AsakusaRinne** [comment]
To PyTorch developers:

I don't know who is suitable for reviewing this PR. I will appreciate it if you'd like to help to ping the reviewers.

Sincerely, 
Rinne

**Comment by AsakusaRinne** [comment]
@Chillee Please let me know if I have to do something to move this PR on. :)

**Comment by AsakusaRinne** [comment]
@albanD Sorry for the bothering but May I ask what I need to do to move on? It's certainly okay to reject this PR if it's not reasonable, while I'm more than happy to complete it if someone would like to review. What I'm worrying about is that as time passed, the code of this PR might be outdated and cost me more time to complete it.

**Comment by albanD** [comment]
cc @SherlockNoMad as the owner of fx, can you review/find someone to review this please?

**Pull request closed without merging**
