### PR TITLE
Several enhancements for check_results.py

### PR DESCRIPTION
**Pull request by laithsakka**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137925

1) always generate expected_results.csv up to accuracy of first three digits 
ex: 112313212312 --> 1120000000 .. etc 
2) regenerate all record in  expected_results.csv and not just failed ones , why? because if we change something 
by 1.3% and noise 1.5% we want to reflect that. 
3) add "please update all results that changed significantly, and not only the failed ones"

```
(myenv) [lsakka@devgpu005.nha1 ~/pytorch/benchmarks/dynamo/pr_time_benchmarks (check_result_ehancements)]$ python check_results.py test_check_result/expected_test.csv te
st_check_result/result_test.csv out
WIN: benchmark ('a', 'instruction count') failed, actual result 9011111111 is -18.16% lower than expected 11011111111 ±1.00% please update the expected results. 

please update all results that changed significantly, and not only the failed ones
REGRESSION: benchmark ('b', 'memory') failed, actual result 20011111111 is 99.89% higher than expected 10011111111 ±+10.00% if this is an expected regression, please update the expected results.

please update all results that changed significantly, and not only the failed ones
REGRESSION: benchmark ('c', 'something') failed, actual result 107111111111 is 969.92% higher than expected 10011111111 ±+10.00% if this is an expected regression, please update the expected results.

please update all results that changed significantly, and not only the failed ones
MISSING REGRESSION TEST: benchmark ('d', 'missing-test') does not have a regression test enabled for it.

new expected results file content if needed:
a,instruction count,9011000000,0.01
b,memory,20010000000,0.1
c,something,107100000000,0.1

There was some failures you can use the new reference expected result stored at path:out and printed above

```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by aorenste — APPROVED** [review]

**Comment by ezyang** [comment]
Are you sure you want to regenerate all records? Sounds like merge conflict city

**Comment by laithsakka** [comment]
> Are you sure you want to regenerate all records? Sounds like merge conflict city

I assume people wont often change those, what would be a good other balanced solution ?
all benchmarks changed with in 0.03?
merge conflicts better than flakiness. 

I think eventually I want to pivot away from this whole test setup. This manual maintenance that I am doing is not pratical

**Comment by ezyang** [comment]
Since we haven't managed to make these metrics completely deterministic, the lesson I take is that we ought not to check in the numbers into the repo (despite the attractiveness of it). We can either rely exclusively on the monitoring to catch regressions, or figure out some extra datastore that can report egregious violations and rely on a post facto process for subtle regressions close to the noise window.

**Comment by laithsakka** [comment]
> Since we haven't managed to make these metrics completely deterministic, the lesson I take is that we ought not to check in the numbers into the repo (despite the attractiveness of it). We can either rely exclusively on the monitoring to catch regressions, or figure out some extra datastore that can report egregious violations and rely on a post facto process for subtle regressions close to the noise window.

I do really think the A/B testing is something we might want to reconsider in H1. but I am not bringing it up this half i promise . 

I got recent feedback that those actually blocked some legit regressions, I would like to keep monitering the overhead of dealing with them a bit more before deciding to cancel them out.

**Comment by laithsakka** [comment]
so i have some ideas actually to prevent merge conflicts also:
1. trim numbers if we have XXXXXXXXXX --> XXX00000000 (unlikel to change).
2. only generate new records for things with ration >0.25%

**Comment by laithsakka** [comment]
> so i have some ideas actually to prevent merge conflicts also:
> 
> 1. trim numbers if we have XXXXXXXXXX --> XXXX0000000 (unlikly to change).
>    200 -> 199 = 0.5%?
>    or
> 2. only generate new records for things with ratio >0.25%

i dont like 1 actually maybe its good for readility only will do both

**Pull request closed without merging**
