### PR TITLE
[ROCm] hipGraph support for pytorch mainline

### PR DESCRIPTION
**Pull request by dllehr-amd**
With the release of ROCm 5.3 hip now supports a hipGraph implementation.

All necessary backend work and hipification is done to support the same functionality as cudaGraph.

Unit tests are modified to support a new TEST_GRAPH feature which allows us to create a single check for graph support instead of attempted to gather the CUDA level in annotations for every graph test

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]
These changes have been tested in our fork of PyTorch with ROCm5.3.

**Comment by jithunnair-amd** [comment]
@dllehr-amd Let's take this PR back out of draft when the CI is green and it's ready to be reviewed and merged by PyTorch reviewers.

**Review by pruthvistony — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
