### PR TITLE
Fix potentially undefined behaviour in index_put sample input

### PR DESCRIPTION
**Pull request by GeorgeWigley**
From the [docs](https://pytorch.org/docs/stable/generated/torch.Tensor.index_put_.html) for index_put_: 

> If accumulate is True, the elements in values are added to self. If accumulate is False, the behavior is undefined if indices contain duplicate elements.

Currently the sample inputs for `index_put` generates 2 indices. Because they are generated randomly, they could be the same leading to undefined behaviour if `accumulate=False`.

This PR changes the input generation to only generate a single index if `accumulate=False` preventing duplicate indices and undefined behaviour.

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by GeorgeWigley** [comment]
MPS had an xfail for index_put because of the undefined behaviour this PR fixes.

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
