### PR TITLE
[profiler] Add cuda synchronization points

### PR DESCRIPTION
**Pull request by ilia-cher**
Summary:
Adding cuda synchronization when entering and exiting the profiler
context manager

Test Plan: CI

### CODE REVIEW

**Comment by mrshenli** [comment]
This commit breaks master, shall we revert?

**Comment by ilia-cher** [comment]
> This commit breaks master, shall we revert?

I reverted

**Comment by ngimel** [comment]
Is synchronization needed to record all the kernels in the scope (including those that just started?) Unconditional synchronization is likely to lead to deadlocks, as the tests show.

**Comment by ilia-cher** [comment]
> Is synchronization needed to record all the kernels in the scope (including those that just started?) Unconditional synchronization is likely to lead to deadlocks, as the tests show.

Chatted with Rohan about failing tests, it seems to be less a particular synchronization issue but rather an issue in the tests with a distributed forget not setting the current device right

**Comment by ilia-cher** [comment]
> Is synchronization needed to record all the kernels in the scope (including those that just started?) Unconditional synchronization is likely to lead to deadlocks, as the tests show.

Chatted with Rohan about failing tests, it seems to be not this particular synchronize() call issue but rather an issue in the distributed test workers that forget to set the current device

**Pull request closed without merging**
