### PR TITLE
[LTC] Auto-gen the 'mv' and 'mv.out' Op in the new lazy tensor core.

### PR DESCRIPTION
**Pull request by nkreeger**
Moves over the "mv" and the "mv_out" op to codegen. Also cleans up the `ir::ops::Dot()` reference from https://github.com/pytorch/pytorch/pull/65529.

Verified with the following scratch code:
```py
from lazy_tensor_core import debug
import torch
import lazy_tensor_core
import lazy_tensor_core.debug.metrics as metrics

lazy_tensor_core._LAZYC._ltc_init_ts_backend()

device = 'lazy'
dtype = torch.float32

mat = torch.randn(2, 3, device=device, dtype=dtype)
vec = torch.randn(3, device=device, dtype=dtype)
print(torch.mv(mat, vec))

print(metrics.metrics_report())
```

Output diff from metrics_report:
```diff
--- old-output.txt      2021-09-24 16:23:19.188545600 -0500
+++ new-output.txt      2021-09-24 16:22:27.418545600 -0500
@@ -1,32 +1,32 @@
-tensor([0.6081, 0.8017], device='lazy:0')
+tensor([-2.8513,  2.2631], device='lazy:0')
 Metric: DeviceLockWait
   TotalSamples: 12
-  Accumulator: 006.500us
-  ValueRate: 174.291us / second
-  Rate: 321.768 / second
-  Percentiles: 1%=000.400us; 5%=000.400us; 10%=000.400us; 20%=000.400us; 50%=000.500us; 80%=000.600us; 90%=000.700us; 95%=000.900us; 99%=000.900us
+  Accumulator: 007.000us
+  ValueRate: 184.251us / second
+  Rate: 315.859 / second
+  Percentiles: 1%=000.400us; 5%=000.400us; 10%=000.400us; 20%=000.400us; 50%=000.500us; 80%=000.700us; 90%=000.800us; 95%=001.000us; 99%=001.000us
 Metric: IrValueTensorToDataHandle
-  TotalSamples: 3
-  Accumulator: 013.200us
-  ValueRate: 398.869us / second
-  Rate: 90.652 / second
-  Percentiles: 1%=001.200us; 5%=001.200us; 10%=001.200us; 20%=001.200us; 50%=003.300us; 80%=008.700us; 90%=008.700us; 95%=008.700us; 99%=008.700us
+  TotalSamples: 4
+  Accumulator: 015.300us
+  ValueRate: 453.124us / second
+  Rate: 118.464 / second
+  Percentiles: 1%=001.600us; 5%=001.600us; 10%=001.600us; 20%=001.600us; 50%=003.500us; 80%=008.600us; 90%=008.600us; 95%=008.600us; 99%=008.600us
 Metric: TensorsGraphSize
   TotalSamples: 12
-  Accumulator: 40.00
-  ValueRate: 1176.04 / second
-  Rate: 352.813 / second
-  Percentiles: 1%=1.00; 5%=1.00; 10%=1.00; 20%=2.00; 50%=3.00; 80%=5.00; 90%=5.00; 95%=7.00; 99%=7.00
+  Accumulator: 48.00
+  ValueRate: 1384.53 / second
+  Rate: 346.133 / second
+  Percentiles: 1%=1.00; 5%=1.00; 10%=3.00; 20%=3.00; 50%=3.00; 80%=5.00; 90%=6.00; 95%=9.00; 99%=9.00
 Counter: CachedCompile
-  Value: 2
+  Value: 1
 Counter: CreateLtcTensor
   Value: 29
 Counter: DestroyLtcTensor
   Value: 27
 Counter: DeviceDataCacheMiss
-  Value: 6
+  Value: 7
 Counter: UncachedCompile
-  Value: 10
+  Value: 11
 Counter: aten::_local_scalar_dense
   Value: 6
 Counter: aten::abs.out
@@ -41,12 +41,10 @@
   Value: 1
 Counter: aten::min
   Value: 1
-Counter: aten::mv
-  Value: 1
 Counter: aten::normal_
   Value: 2
 Counter: lazy::_copy_from
-  Value: 29
+  Value: 26
 Counter: lazy::_copy_from_and_resize
   Value: 6
 Counter: lazy::div
@@ -59,6 +57,8 @@
   Value: 1
 Counter: lazy::mul
   Value: 1
+Counter: lazy::mv
+  Value: 1
 Counter: lazy::ne
   Value: 3
 Counter: lazy::select
```

### CODE REVIEW

**Comment by wconstab** [comment]
lgtm, ill let @alanwaketan approve/merge in case any conflicts with his work

**Review by alanwaketan — COMMENTED** [review]
LGTM. Let's merge.

**Review by alanwaketan — APPROVED** [review]

**Comment by alanwaketan** [comment]
@nkreeger Can you rebase your feature branch to the latest lazy_tensor_staging branch?

**Comment by nkreeger** [comment]
@alanwaketan it looks like it will merge cleanly into lazy_tensor_staging? I just tried pulling latest and pushing to the branch

**Comment by alanwaketan** [comment]
> @alanwaketan it looks like it will merge cleanly into lazy_tensor_staging? I just tried pulling latest and pushing to the branch

I was scared by the messy message produced by the "Squash and merge" action. And then realized I can probably update that myself. Hope you don't mind the truncated message. Thanks @wconstab for the pro-tip.

**Pull request merged**
