### PR TITLE
Add `multi_head_attention_forward` to functional rst docs

### LINKED ISSUE #72597: Functional version of `MultiheadAttention`, `torch.nn.functional.multi_head_attention_forward` has no documentation
### 📚 The doc issue

The functional version of https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html has no documentation, as can be seen when searching for it: https://pytorch.org/cppdocs/search.html?q=multi_head_attention_forward&check_keywords=yes&area=default

This issue appears to have been present for a while, as it this earlier issue was closed prematurely: https://github.com/pytorch/pytorch/issues/49296

The source code for the function also already has documentation written: https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L5049, so I'm not sure why it isn't showing up on the PyTorch site docs. The `in_proj_weight` variable should also be type hinted as `Optional[Tensor]` and not just `Tensor`

### Suggest a potential alternative/fix

Add documentation for `torch.nn.functional.multi_head_attention_forward`.

cc @brianjo @mruberry @jbschlosser @bhosmer @cpuhrsch

### PR DESCRIPTION
**Pull request by ProGamerGov**
Fixes #72597

### CODE REVIEW

**Comment by ProGamerGov** [comment]
Not sure if adding Optional to `in_proj_weight`'s type hint will cause any test failure, so I haven't done that in this PR.

**Review by jbschlosser — APPROVED** [review]
LGTM thanks!

**Comment by jbschlosser** [comment]
> Not sure if adding Optional to `in_proj_weight`'s type hint will cause any test failure, so I haven't done that in this PR.

Knowing TorchScript, I think that was a good call. IIRC this has been attempted before.

**Comment by mruberry** [comment]
Unlanding, as this appears to have broken several jobs on HUD CI. It looks like PR CI didn't run any tests?


Here's what I think the relevant part of the doc job logs is (from https://github.com/pytorch/pytorch/runs/5151144804?check_suite_focus=true): 
```
/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:docstring of torch.nn.functional.multi_head_attention_forward:41: WARNING: Unexpected indentation.
/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:docstring of torch.nn.functional.multi_head_attention_forward:42: WARNING: Block quote ends without a blank line; unexpected unindent.
/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:docstring of torch.nn.functional.multi_head_attention_forward:64: WARNING: Unexpected indentation.
/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:docstring of torch.nn.functional.multi_head_attention_forward:65: WARNING: Block quote ends without a blank line; unexpected unindent.
```

**Pull request closed without merging**
