### PR TITLE
Fix straggler logging.CODE

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #90575
* __->__ #90572

- logging.CODE was entirely removed, this was left behind

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Comment by wconstab** [comment]
someone else fixed it first

**Pull request closed without merging**
