### PR TITLE
Fixes bias not working when not qkv has diff size

### PR DESCRIPTION
**Pull request by ZhiyuanChen**
Fixes #{issue number}

### CODE REVIEW

**Review by jbschlosser — COMMENTED** [review]
Thanks for the fix! Do you mind adding a test as well in `test/test_nn.py` for the case of diff size qkv + bias?

**Comment by ZhiyuanChen** [comment]
> Thanks for the fix! Do you mind adding a test as well in `test/test_nn.py` for the case of diff size qkv + bias?

sure thing, i'll try to add it this week~

**Comment by ZhiyuanChen** [comment]
Hi @jbschlosser
Sorry this "week" is a bit toooo long ... Could you plz have a look if I get the test right?

**Comment by jbschlosser** [comment]
@ZhiyuanChen Haha no problem! Unfortunately, based on the CI checks, it does look like the test is failing

**Comment by ZhiyuanChen** [comment]
> @ZhiyuanChen Haha no problem! Unfortunately, based on the CI checks, it does look like the test is failing

could you please reopen this pr so that i can look into it?

**Pull request closed without merging**
