### PR TITLE
[dynamo] fix bug where trace_source and graph_sizes artifacts were not being printed with TORCH_LOGS='+dynamo'

### PR DESCRIPTION
**Pull request by williamwen42**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #104676
* __->__ #104912

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by mlazos — APPROVED** [review]

**Comment by lezcano** [comment]
This PR makes `output_code` spit the code as:
```python
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG] def call(args):
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]     arg0_1, = args
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]     args.clear()
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]     assert_size_stride(arg0_1, (10, ), (1, ))
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]     with torch.cuda._DeviceGuard(0):
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]         torch.cuda.set_device(0) # no-op to ensure context
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]         buf0 = empty_strided((10, ), (1, ), device='cuda', dtype=torch.int64)
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]         stream0 = get_cuda_stream(0)
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]         triton_poi_fused_pow_0.run(arg0_1, buf0, 10, grid=grid(10), stream=stream0)
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]         del arg0_1
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]         return (buf0, )
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG] 
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG] 
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG] def benchmark_compiled_module(times=10, repeat=10):
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]     from torch._dynamo.testing import rand_strided
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]     from torch._inductor.utils import print_performance
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]     arg0_1 = rand_strided((10, ), (1, ), device='cuda:0', dtype=torch.int64)
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]     return print_performance(lambda: call([arg0_1]), times=times, repeat=repeat)
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG] 
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG] 
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG] if __name__ == "__main__":
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]     from torch._inductor.utils import compiled_module_main
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG]     compiled_module_main('None', benchmark_compiled_module)
[2023-07-12 08:02:40,842] torch._inductor.graph.__output_code: [DEBUG] 
```

which is quite annoying, as it doesn't allow you to just copy the repro, and also takes *lots* of unnecessary terminal width.

Could we revert this PR or submit a forward fix for these issues?

**Comment by lezcano** [comment]
ping @williamwen42 @mlazos Re https://github.com/pytorch/pytorch/pull/104912#issuecomment-1632044883

**Pull request closed without merging**
