### PR TITLE
Migrate CPU_tensor_apply to TensorIterator

### LINKED ISSUE #24487: Migrate CPU_tensor_apply to TensorIterator in aten/src/ATen/native/Loss.cpp:80
Migrate CPU_tensor_apply to TensorIterator
https://github.com/pytorch/pytorch/blob/eabfca3577ea85df2d68bdf747c62dd4a5fff5cf/aten/src/ATen/native/Loss.cpp#L80
How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator
Additional Instructions:#24478
Blocked by:#24472

### LINKED ISSUE #24488: Migrate CPU_tensor_apply to TensorIterator in aten/src/ATen/native/Distributions.cpp:142
Migrate CPU_tensor_apply to TensorIterator
https://github.com/pytorch/pytorch/blob/eabfca3577ea85df2d68bdf747c62dd4a5fff5cf/aten/src/ATen/native/Distributions.cpp#L142
How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator
Additional Instructions:#24478
Blocked by:#24472

### LINKED ISSUE #24489: Migrate CPU_tensor_apply to TensorIterator in aten/src/ATen/native/Distributions.cpp:151
Migrate CPU_tensor_apply to TensorIterator
https://github.com/pytorch/pytorch/blob/eabfca3577ea85df2d68bdf747c62dd4a5fff5cf/aten/src/ATen/native/Distributions.cpp#L151
How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator
Additional Instructions:#24478
Blocked by:#24472

### LINKED ISSUE #24490: Migrate CPU_tensor_apply to TensorIterator in aten/src/ATen/native/Distributions.cpp:176
Migrate CPU_tensor_apply to TensorIterator
https://github.com/pytorch/pytorch/blob/eabfca3577ea85df2d68bdf747c62dd4a5fff5cf/aten/src/ATen/native/Distributions.cpp#L176
How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator
Additional Instructions:#24478
Blocked by:#24472

### LINKED ISSUE #24491: Migrate CPU_tensor_apply to TensorIterator in aten/src/ATen/native/Distributions.cpp:189
Migrate CPU_tensor_apply to TensorIterator
https://github.com/pytorch/pytorch/blob/eabfca3577ea85df2d68bdf747c62dd4a5fff5cf/aten/src/ATen/native/Distributions.cpp#L189
How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator
Additional Instructions:#24478
Blocked by:#24472

### LINKED ISSUE #24492: Migrate CPU_tensor_apply to TensorIterator in aten/src/ATen/native/Distributions.cpp:201
Migrate CPU_tensor_apply to TensorIterator
https://github.com/pytorch/pytorch/blob/eabfca3577ea85df2d68bdf747c62dd4a5fff5cf/aten/src/ATen/native/Distributions.cpp#L201
How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator
Additional Instructions:#24478
Blocked by:#24472

### LINKED ISSUE #24493: Migrate CPU_tensor_apply to TensorIterator in aten/src/ATen/native/Distributions.cpp:220
Migrate CPU_tensor_apply to TensorIterator
https://github.com/pytorch/pytorch/blob/eabfca3577ea85df2d68bdf747c62dd4a5fff5cf/aten/src/ATen/native/Distributions.cpp#L220
How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator
Additional Instructions:#24478
Blocked by:#24472

### LINKED ISSUE #24494: Migrate CPU_tensor_apply to TensorIterator in aten/src/ATen/native/Distributions.cpp:235
Migrate CPU_tensor_apply to TensorIterator
https://github.com/pytorch/pytorch/blob/eabfca3577ea85df2d68bdf747c62dd4a5fff5cf/aten/src/ATen/native/Distributions.cpp#L235
How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator
Additional Instructions:#24478
Blocked by:#24472

### LINKED ISSUE #24495: Migrate CPU_tensor_apply to TensorIterator in aten/src/ATen/native/Distributions.cpp:266
Migrate CPU_tensor_apply to TensorIterator
https://github.com/pytorch/pytorch/blob/eabfca3577ea85df2d68bdf747c62dd4a5fff5cf/aten/src/ATen/native/Distributions.cpp#L266
How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator
Additional Instructions:#24478
Blocked by:#24472

### LINKED ISSUE #24496: Migrate CPU_tensor_apply to TensorIterator in aten/src/ATen/native/Distributions.cpp:286
Migrate CPU_tensor_apply to TensorIterator
https://github.com/pytorch/pytorch/blob/eabfca3577ea85df2d68bdf747c62dd4a5fff5cf/aten/src/ATen/native/Distributions.cpp#L286
How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator
Additional Instructions:#24478
Blocked by:#24472

### PR DESCRIPTION
**Pull request by muthuArivoli**
Closes #24487
Closes #24488
Closes #24489
Closes #24490
Closes #24491
Closes #24492
Closes #24493
Closes #24494
Closes #24495
Closes #24496

### CODE REVIEW

**Comment by muthuArivoli** [comment]
@VitalyFedyunin This PR is ready for review, let me know if I need to do anything like benchmarking.

**Comment by muthuArivoli** [comment]
@mruberry  PTAL

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by muthuArivoli** [comment]
Hey @VitalyFedyunin, what's the status on this?

**Comment by VitalyFedyunin** [comment]
Hmm, landing failed. Will restart.

**Pull request closed without merging**
