### PR TITLE
[EASY] Generate uninplaced operators that don't have out-of-place counterparts

### PR DESCRIPTION
**Pull request by apaszke**
This is needed to unblock the thread-local tracing PR. We trace some in-place ops as out-of-place ops, but not all of them actually have ATen implementations. This is a simple change that adjusts our codemod to pretend that they exist by cloning the modified input and only then applying the inplace op.

For example we trace `x.zero_()` as `y = zero(x)`, which is pretty much `zeros_like`. At some point we should add a pass that translates it, because `zeros_like` would be more efficient than `x.clone().zero_()`, but I'm leaving that for later. Here's how the generated operator looks like:
```cpp
Operator(                                                 
    "aten::zero(Tensor self) -> Tensor",                  
    [](Node *node) {                                      
                                                          
      return Operation([=](Stack & stack) {               
        autograd::profiler::RecordFunction record("zero");
                                                          
        auto self = peek(stack, 0, 1).toTensor().clone(); 
        auto result = at::zero_(self);                    
        drop(stack, 1);                                   
        pack(stack, std::move(result));                   
        return 0;                                         
      });                                                 
    }                                                     
),                                                        
```

@zdevito

### CODE REVIEW

**Review by zdevito — APPROVED** [review]
I am OK with this only temporarily. We should instead just implement the missing out-of-place ops, for consistency. It is not a good idea for this behavior to be hidden inside of a binding generator because there will be all sorts of places that break because of it. For instance, this almost certainly breaks onnx export of aten ops since that binding-generator doesn't know to generate zero. If this unblocks you, then go ahead and merge but it needs a follow up task to remove it.

**Comment by apaszke** [comment]
Yes, I'll also need ONNX export for `zero`, but that's not really an issue I think. No matter if they're implemented in ATen or not, if we want the export to be ONNX-compliant, we'll still need to add symbolic descriptions in `symbolic.py`. `zero(x)` can be e.g. desugared into `x - x`.

**Comment by apaszke** [comment]
Also, I don't think we want to implement their counterparts in all cases `zero(x)` is really `zeros_like(x)`, which is the one people should usually use. We can have a desugaring pass instead if you'd prefer that (I can change this diff to that).

**Comment by zdevito** [comment]
I am fine with whatever is you want to do in the short term, but we have to have a long term consistency plan here. Adding these op has bad properties, like making `torch.zero` work in the script but not in python. I also believe that we have the automatic creation of ONNX "ATen" ops, even without symbolics, so it will try to export a `aten::zero` but because caffe2's ATen bindings do not know about these generated ops, they will not work.  We might want to teach the tracer about known equivalents (zero_ <-> zeros_like), and then actually implement the missing equivalents.

**Comment by apaszke** [comment]
Ok, I see your point. I really only care about `zero_()` at the moment, so I can just patch the tracer to emit `zeros_like` in this case.

**Pull request closed without merging**
