### PR TITLE
Make torch.backends.mkldnn usable without import

### PR DESCRIPTION
**Pull request by ssnl**

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 2104e445:


**None of the build failures appear to be your fault**.

* **1/1** recognized as flaky :snowflake:
    * Re-run these jobs?


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=2104e44509be7691e4f32f562aa8a8a37292d5fd).

### :snowflake: 1 failure recognized as flaky
The following build failures have been detected as flaky and **may not be your fault**:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4202424) caffe2_onnx_py3_6_clang7_ubuntu16_04_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=83264197) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=83264197)) :snowflake:
<details>
<summary>
<code>Jan 10 19:01:09 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_reshape Fatal Python error: Segmentation fault</code>
</summary>

```
Jan 10 19:01:09 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_constant_fold_slice_negative_index PASSED [ 99%] 
Jan 10 19:01:09 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_constant_fold_transpose PASSED [ 99%] 
Jan 10 19:01:09 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_constant_fold_transpose_matmul PASSED [ 99%] 
Jan 10 19:01:09 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_constant_fold_unsqueeze PASSED [ 99%] 
Jan 10 19:01:09 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_error_on_data_parallel PASSED [ 99%] 
Jan 10 19:01:09 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_is_in_onnx_export PASSED [ 99%] 
Jan 10 19:01:09 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_strip_doc_string PASSED [ 99%] 
Jan 10 19:01:09 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_validate_dynamic_axes_invalid_input_output_name PASSED [ 99%] 
Jan 10 19:01:09 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_concat PASSED [ 99%] 
Jan 10 19:01:09 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_lstm PASSED [ 99%] 
Jan 10 19:01:09 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_reshape Fatal Python error: Segmentation fault 
Jan 10 19:01:09  
Jan 10 19:01:09 Current thread 0x00007fd0cef24700 (most recent call first): 
Jan 10 19:01:09   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 43 in repr_instance 
Jan 10 19:01:09   File "/usr/lib/python3.6/reprlib.py", line 65 in repr1 
Jan 10 19:01:09   File "/usr/lib/python3.6/reprlib.py", line 55 in repr 
Jan 10 19:01:09   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 36 in repr 
Jan 10 19:01:09   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 67 in saferepr 
Jan 10 19:01:09   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 655 in repr_args 
Jan 10 19:01:09   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 736 in repr_traceback_entry 
Jan 10 19:01:09   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 777 in repr_traceback 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by vishwakftw — APPROVED** [review]

**Comment by vishwakftw** [comment]
How are we able to do `torch.backends.cudnn.enabled` though?

**Comment by SsnL** [comment]
@vishwakftw from here :)
https://github.com/pytorch/pytorch/blob/9ce15173fb0ef7f7e5497f4afad6b5d10c0e4c21/torch/backends/cudnn/rnn.py#L2

**Comment by vishwakftw** [comment]
Oh, thanks!

**Pull request closed without merging**
