### PR TITLE
Disable nnc/test_aot_compile.sh

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #81196

Deprecation: NNC backend for mobile is not being worked upon actively. It is slated to be deprecated.

@bypass-github-export-checks

Differential Revision: [D37746019](https://our.internmc.facebook.com/intern/diff/D37746019)

### CODE REVIEW

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37746019).

**Review by mruberry — APPROVED** [review]
Stamped!

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37746019).

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37746019).

**Pull request closed without merging**
