### PR TITLE
Check both ops and refs in test_strided_layout

### PR DESCRIPTION
**Pull request by isuruf**
cc @mruberry @ZainRizvi @lezcano

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
SGTM as long as CI agrees

**Comment by lezcano** [comment]
Once CLA is green feel free to trigger the merge

**Comment by lezcano** [comment]
Not sure what's going on here. Mind resubmitting this PR it see if it picks it up?

**Comment by isuruf** [comment]
Closing in favour of #112160

**Pull request closed without merging**
