### PR TITLE
Remove aten dispatch to empty in foreach_norm cuda kernel

### PR DESCRIPTION
**Pull request by janeyx99**
Saves significant time on aten dispatch. For 2k tensors, goes from 38ms to 58us.
Should shave some overhead mentioned in https://github.com/pytorch/pytorch/issues/133586

Before PR:
image

After: 
image

script:
```
import torch

# warm up caching allocator
a = torch.rand(200, 10, device="cuda")
b = torch.rand(200, 10, device="cuda")
c = a + b
del a, b, c

ts = [torch.rand(2, 3, device="cuda") for _ in range(2000)]

with torch.profiler.profile(
    activities=[
        torch.profiler.ProfilerActivity.CPU,
        torch.profiler.ProfilerActivity.CUDA,
    ]
) as p:
    torch._foreach_norm(ts)

print(p.key_averages().table(sort_by="cpu_time_total"))
```

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #133897

### CODE REVIEW

**Review by drisspg — COMMENTED** [review]
probably need to guard against subclasses right?

**Review by albanD — DISMISSED** [review]
Sounds good!
Would be amazing if we could check that these kernels are not called from non-backend kernels going forward.

**Review by albanD — APPROVED** [review]
Actually, if you got here (in the CUDA key impl), all subclass and modes must already have been handled. While you can technically make it happen (with with of private api only), it will most likely lead to segfault anyways.

**Comment by drisspg** [comment]
Ohh duhh I didnt see this was in the cuda impl

**Review by drisspg — APPROVED** [review]

**Comment by awgu** [comment]
Did you look into why `_foreach_norm` is still taking 200 ms on CPU side?

**Comment by janeyx99** [comment]
> Did you look into why `_foreach_norm` is still taking 200 ms on CPU side?

no but i suspect it could be device related; i can rerun tomorrow and see

**Comment by janeyx99** [comment]
image
This is the trace for the new foreach_norm. Not sure why it extends so long. The tiny sliver on the right is a cuda sync.

**Comment by crcrpar** [comment]
nice

**Pull request closed without merging**
