### PR TITLE
[CI] Add more tests to the numpy 2 CI

### PR DESCRIPTION
**Pull request by haifeng-jin**
Related to #107302 

This PR adds all the tests that failed with NumPy 2, which all have been fixed, to the CI to test with NumPy 2 to prevent regression.

### CODE REVIEW

**Comment by haifeng-jin** [comment]
This PR is blocked by https://github.com/pytorch/pytorch/pull/141986
Need to rebase after it is merged.

**Review by albanD — APPROVED** [review]
Thanks!

**Pull request closed without merging**
