### PR TITLE
Unhide at::unique from C++

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Currently we only have `at::_unique` and `at::_unique_dim`. It would be convenient to have a overloaded `at::unique` that handle both cases.

### CODE REVIEW

**Comment by ezyang** [comment]
I'm ambivalent about this. In Python land, this positional call is invalid:

```
>>> torch.unique(torch.zeros(2,2), 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/ezyang/pytorch-tmp/torch/functional.py", line 486, in unique
    return_inverse=return_inverse,
TypeError: _unique(): argument 'sorted' must be bool, not int
```

We don't have keyword arguments in C++, so it's hard to do this in a clear way. The existing positional booleans already make my skin crawl.

**Comment by ezyang** [comment]
cc @gchanan

**Comment by zasdfgbnm** [comment]
@ezyang Overloading it under the same name `unique` may or may not be a good idea, as you figure out. But at least we need to delete the `_` in front of its name to make it a public C++ API.

**Comment by t-vi** [comment]
I think part of the problem is that Python's torch.unique has a different argument ordering than _unique_dim, in the first, the dimension comes last.
Having deviations in the argument order might be confusing to users (like in @ezyang 's example above).

**Comment by zou3519** [comment]
Can you rebase onto master so we can retest this?

`git pull --rebase upstream master`

**Comment by zasdfgbnm** [comment]
So, what is the best way to provide a C++ API of unique?

**Comment by zasdfgbnm** [comment]
PS: I would suggest resolving this before release of 1.0, otherwise the user would start using `_unique` and future update might break user code.

**Comment by zasdfgbnm** [comment]
Closing this in favor of https://github.com/pytorch/pytorch/pull/15256

**Pull request closed without merging**
