### PR TITLE
[inductor] Deterministic kernel names

### PR DESCRIPTION
**Pull request by anijain2305**
`node.origins` is a set and does not have an order. Therefore, inductor w and w/o cudagraphs experiments generate different kernel names, making it hard to debug.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by ngimel** [comment]
Also, descriptive kernel names are now optional, so you can remove those altogether, and just leave the numbers.

**Comment by anijain2305** [comment]
> Also, descriptive kernel names are now optional, so you can remove those altogether, and just leave the numbers.

I just saw that. I did not rebase.

I think this fix is still ok. The edited function will be triggered only when we want descriptive names (flag `descriptive_kernel_names`). So, this PR is still ok?

**Review by mlazos — APPROVED** [review]

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Yes, of course, it's a good change (and it was approved)

**Pull request closed without merging**
