### PR TITLE
Updated invalid type error message to explicitly say only float types…

### LINKED ISSUE #82983: Setting torch.cfloat as default tensor type raises "invalid type" error
### 🐛 Describe the bug

Hello, I am working on complex valued neural networks, and the new complex tensor support is a welcome addition (thanks!). When I try to set `cfloat` as `default_tensor_type`, I get `TypeError: invalid type object`.

Steps to reproduce:
```
import torch
torch.set_default_tensor_type(torch.cfloat)
```

Error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [18], in <cell line: 3>()
      1 import torch
----> 3 torch.set_default_tensor_type(torch.cfloat)

File ~/miniforge3/envs/env_name/lib/python3.10/site-packages/torch/__init__.py:331, in set_default_tensor_type(t)
    329 if isinstance(t, _string_classes):
    330     t = _import_dotted_name(t)
--> 331 _C._set_default_tensor_type(t)

TypeError: invalid type object
```

Other troubleshooting: Doing complex tensor operations is fine. For example, 
```
x = torch.randn(2,2, dtype=torch.cfloat)
``` 
gives
```
tensor([[-0.0099-0.3028j, -0.5884+0.1538j],
        [-0.5426-0.9435j, -0.8310+0.4520j]])
```

### Versions

```
Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:07:06) [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchvision==0.13.1
[conda] numpy                     1.23.1          py310h0a343b5_0    conda-forge
[conda] pytorch                   1.12.1                 py3.10_0    pytorch
[conda] torchaudio                0.12.1                py310_cpu    pytorch
[conda] torchvision               0.13.1                py310_cpu    pytorch
```

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

### PR DESCRIPTION
**Pull request by karanprime**
… allowed

Fixes #82983

I added an error messages consistent with existing invalid type error messages (line 330 in torch/csrc/tensor/python_tensor.cpp).

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
just need a lint fix

**Comment by karanprime** [comment]
I have done the listing. Please merge it.

**Review by kit1980 — APPROVED** [review]

**Comment by ZainRizvi** [comment]
@pytorchmergebot revert -c 'nosignal' -m "This is causing the test_error_on_not_implemented test to fail since that test expects the old error message. Can you please fix the test as well?"

Example: https://hud.pytorch.org/pytorch/pytorch/commit/ccb1ff22333ed1d28ee5287d75a3322b12b93f6a

**Pull request closed without merging**
