### PR TITLE
[ONNX] Annotate all g as GraphContext

### LINKED ISSUE #84553: [ONNX] Change how context is given to symbolic functions
Current symbolic functions can take a context as an input, pushing graphs to the second argument. To support these functions, we need to annotate the first argument as symbolic context and tell them part in call time by examining the annotations. 

Checking annotations is slow and this process complicates the logic in the caller. 

Instead we can wrap the graph object in a GraphContext, exposing all methods used from the graph and include the context in the GraphContext. This way all the old symbolic functions continue to work and we do not need to do the annotation checking if we know the symbolic function is a "new function". 

We can edit a private field in the functions at registration time to tag them as "new style" symbolic functions that always takes a wrapped Graph with context object as input.

This also has the added benefit where we no longer need to monkey patch the Graph object to expose the g.op method. Instead the method can be defined in the graph context object.

### PR DESCRIPTION
**Pull request by justinchuby**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #85488
* #85487
* #85486
* #85350
* #85349
* #85312
* #85165
* __->__ #85491
* #84776
* #84728

- Use g.opset to test export opset version
- Annotate all `g` as GraphContext

### CODE REVIEW

**Comment by justinchuby** [comment]
One challenge for annotating all `g` as GraphContext is that Blocks passed in will be flagged by beartype. We can (1) disable beartype for those functions (2) annotate with Union (how many do we need to annotate; is this contagious?) (3) not annotate them (but the objects still propagate like in (2))

**Review by titaiwangms — APPROVED** [review]

**Comment by justinchuby** [comment]
@BowenBao PTAL

**Comment by BowenBao** [comment]
> One challenge for annotating all `g` as GraphContext is that Blocks passed in will be flagged by beartype. We can (1) disable beartype for those functions (2) annotate with Union (how many do we need to annotate; is this contagious?) (3) not annotate them (but the objects still propagate like in (2))
> 
> @thiagocrepaldi curious on what you think

I guess this is resolved with #84728?

**Review by BowenBao — APPROVED** [review]

**Comment by justinchuby** [comment]
> I guess this is resolved with #84728?

Yep!

**Pull request closed without merging**
