### PR TITLE
quote all of the regular expressions

### PR DESCRIPTION
**Pull request by dagitses**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #79327
* #79345
* #79306
* #79305
* #79414
* #79313
* __->__ #79312
* #79308

Summary:
Without the quote, the \ is not properly forwarded to Bazel.

Test Plan: Verify subcommands.

Reviewers: seemethere

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM, but on could have avoided it by using `\\`, wouldn't he?) Though I assume quotes are necessary to avoid early wildcards unrolling

**Comment by dagitses** [comment]
> LGTM, but on could have avoided it by using `\\`, wouldn't he?) Though I assume quotes are necessary to avoid early wildcards unrolling

Good question. It's really unclear how these files interact with a shell interpreter. I'm kinda just going by reverse engineering unfortunately.

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
