### PR TITLE
[quant] Rewriting the scalar add

### PR DESCRIPTION
**Pull request by z-a-f**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#25080 [quant] Rewriting the scalar add**

Differential Revision: [D16979377](https://our.internmc.facebook.com/intern/diff/D16979377)

### CODE REVIEW

**Comment by llyfacebook** [comment]
I saw some numeric issue of the new implementation when I debug the classification model. Could you write some test to benchmark the numeric? THanks.

**Review by lly-zero-one — CHANGES_REQUESTED** [review]
Saw some numeric issue of the operator.

**Review by lly-zero-one — CHANGES_REQUESTED** [review]

**Comment by zafartahirov** [comment]
Doesn't work yet -- need some time to debug

**Comment by zafartahirov** [comment]
Closing as outdated in favor of #25622

**Pull request closed without merging**
