### PR TITLE
[WIP] add kernel size vs input size check for AvgPool2d

### PR DESCRIPTION
**Pull request by Dorozhko-Anton**
add kernel size vs input size check similar to AvgPool3d (#15822) 

more details here:
https://github.com/pytorch/pytorch/issues/15822#issuecomment-539738235

### CODE REVIEW

**Comment by ezyang** [comment]
I suggest we change the hypothesis test to reject samples which fail the kernel size check.

**Comment by Dorozhko-Anton** [comment]
I get strange behavior by playing with `hu.array_shapes` and `assume`.

We have
```
@given(X=hu.tensor(shapes=hu.array_shapes(min_dims=3, max_dims=4,
                                              min_side=1, max_side=10),
                       qparams=hu.qparams()),
           kernel=st.sampled_from((3, 5, 7)),
           stride=st.sampled_from((None, 1, 2)),
           dilation=st.integers(1, 2),
           padding=st.integers(0, 2))
    def test_max_pool2d(self, X, kernel, stride, dilation, padding):
```
In this case we have `min_size = 1` and test will brake due to added check `kernel vs image size`


1) If I add 
```
iH, iW = X.shape[-2:]
assume((iH > kernel) and (iW > kernel)) # Reject examples where image is smaller than kernel
```
My tests failed with many outputs like this
```
Trying example: test_max_pool2d(self=<test_quantized.TestQuantizedOps testMethod=test_max_pool2d>, X=(array([[[ 3.7912389e-20,  3.7912389e-20],
         [ 3.7912389e-20,  3.7912389e-20],
         [-2.2514318e-20,  3.7912389e-20],
         [ 3.7912389e-20,  3.7912389e-20]],
 
        [[ 3.7912389e-20,  3.7912389e-20],
         [ 3.7912389e-20,  3.7912389e-20],
         [ 3.7912389e-20,  3.7912389e-20],
         [ 3.7912389e-20,  3.7912389e-20]],
 
        [[ 3.7912389e-20,  3.7912389e-20],
         [ 3.7912389e-20,  3.7912389e-20],
         [ 3.7912389e-20,  3.7912389e-20],
         [ 3.7912389e-20,  3.7912389e-20]]], dtype=float32),
 (1.1920928955078125e-07, 0, torch.qint32)), kernel=7, stride=None, dilation=1, padding=0)
```
So basically here one dimension is 4, that is less than kernel=7, but I don't understand how it was chosen with my `assume` statement.

But with `assume((iH >= kernel) and (iW >= kernel))` test won't fail. And it is confusing for me.

2. Or I can change `min_side = 7` which is bigger than the biggest kernel size tested.

I use `pytest test/test_quantized.py -k pool -p no:warnings` command to run tests.

@ezyang is `assume` modification better than `min_side`?

**Comment by ezyang** [comment]
> So basically here one dimension is 4, that is less than kernel=7, but I don't understand how it was chosen with my assume statement.

That is perplexing. Maybe the `shape[-2:]` slice isn't doing what you expect? Try printing the values?

**Comment by ezyang** [comment]
@jamesr66a, you added this test. Do you have any ideas about what's going on here?

**Comment by Dorozhko-Anton** [comment]
There is no problem with shapes.

Instead, having only changes that reduce the hypothesis size I got an error

Changes 
```
@settings(max_examples=500, report_multiple_bugs=False, suppress_health_check=HealthCheck.all())
assume((iH > kernel) and (iW > kernel)) 
```

Runned with
`pytest test/test_quantized.py -k test_max_pool2d -v -p no:warnings --hypothesis-seed=39762171245839440607525939898097434553 --hypothesis-show-statistics`

Output notes:
```python
 for name, op in ops_under_test.items():
            note(name)
            a_hat = op(qa, kernel_size=kernel, stride=stride, padding=padding,
                       dilation=dilation)
            note(a_hat.dequantize())
            note(a_ref)
            note(a_hat.dequantize() == a_ref)
            note(a_hat.dequantize() - a_ref)

            note(name)
            self.assertEqual(a_ref, a_hat.dequantize(),
                             message="{} results are off".format(name))
```

One of the falsifying examples
```
Falsifying example: test_max_pool2d(self=<test_quantized.TestQuantizedOps testMethod=test_max_pool2d>, X=(array([[[ 0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555]],
 
        [[-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555]],
 
        [[-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555]],
 
        [[-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555]],
 
        [[-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555]],
 
        [[-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555]],
 
        [[-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555],
         [-0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555, -0.00268555, -0.00268555,
          -0.00268555, -0.00268555]]], dtype=float32),
 (2.1063110918975344e-05, 128, torch.quint8)), kernel=3, stride=None, dilation=1, padding=0)
((7, 4, 10), 3, None, 1, 0)
(7, 4, 10)
torch
tensor([[[ 0.0027, -0.0027, -0.0027]],

        [[-0.0027, -0.0027, -0.0027]],

        [[-0.0027, -0.0027, -0.0027]],

        [[-0.0027, -0.0027, -0.0027]],

        [[-0.0027, -0.0027, -0.0027]],

        [[-0.0027, -0.0027, -0.0027]],

        [[-0.0027, -0.0027, -0.0027]]], dtype=torch.float32)
tensor([[[ 0.0027, -0.0027, -0.0027]],

        [[-0.0027, -0.0027, -0.0027]],

        [[-0.0027, -0.0027, -0.0027]],

        [[-0.0027, -0.0027, -0.0027]],

        [[-0.0027, -0.0027, -0.0027]],

        [[-0.0027, -0.0027, -0.0027]],

        [[-0.0027, -0.0027, -0.0027]]], dtype=torch.float32)
tensor([[[ True,  True,  True]],

        [[ True,  True,  True]],

        [[ True,  True,  True]],

        [[ True,  True,  True]],

        [[ True,  True,  True]],

        [[ True, False, False]],

        [[False, False, False]]])
tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 2.1063e-05, 2.1063e-05]],

        [[2.1063e-05, 2.1063e-05, 2.1063e-05]]], dtype=torch.float32)
torch
```

**Comment by ezyang** [comment]
Sounds like the test is busted then. I'd disable it and file an issue for quantization to fix it. cc @raghuramank100

**Pull request closed without merging**
