### PR TITLE
[state_dict][3/N] Cleanup StateDictOptions, make it more readable

### PR DESCRIPTION
**Pull request by fegin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #111111
* #111120
* #111110
* #111109
* __->__ #111108
* #111107
* #111106

1. Rename DistributedStateDictOptions to StateDictOptions.
2. Remove cpu_offload as we have not yet required this option.
3. Rename save_frozen_parameters to ignore_frozen_params.

### CODE REVIEW

**Review by wz337 — APPROVED** [review]
Accepted in phabricator.

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change. But the doc build failure is real https://hud.pytorch.org/pr/111108' -c nosignal

I'm fixing the misclassification on Dr.CI atm to prevent this from happening again

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change, but I think it is cleaner to reland this change' -c nosignal

So you could take your time fixing the issue next week.  You could include https://github.com/pytorch/pytorch/pull/111261 here or re-export the diff D50209711 with the fix to a new PR.  Ping me if you need a stamp.

**Pull request closed without merging**
