### PR TITLE
[distributed] Render `torch.distributed.optim` members in docs

### PR DESCRIPTION
**Pull request by jamesr66a**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #67885
* #67883
* #67882

I noticed that `optim.DistributedOptimizer` was missing from the docs, so I added that to the sphinx RST source. Also, I added `PostLocalSGDOptimizer` because it is also a public member of `optim`. The docs page looks like this now:

image
image
image
image
image

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

Differential Revision: [D32191952](https://our.internmc.facebook.com/intern/diff/D32191952)

### CODE REVIEW

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32191952).

**Comment by jamesr66a** [comment]
OK so I see now that `DistributedOptimizer` is documented in the `rpc.rst` page: https://pytorch.org/docs/stable/rpc.html#distributed-optimizer

@mrshenli @pritamdamania what do you all think about the organization? It was misleading to me that there was a namespace-based `torch.distributed.optim` where I expected to see the members of that namespace, but the members actually live in the non-namespace-based "Distributed RPC Framework" page. I think we could have both but cross-reference between them, so some options:

1) Keep the `DistributedOptimizer` classes in the `Distributed RPC Framework` page and have the `torch.distributed.optim` page reference the section anchor for `Distributed Optimizer` as I linked above
2) Move all of the `DistributedOptimizer` classes into the `torch.distributed.optim` page as in this PR, and have the `Distributed RPC Framework` page link to this

I think either of these options would help discoverability. What do you all think?

**Comment by jamesr66a** [comment]
I think the same thinking applies for things like `torch.distributed.autograd`; I would have expected a namespace doc section to document these things but they're in the RPC docs. Can we create an `autograd.rst` that either contains the references or links to the section of the RPC page?

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32191952).

**Review by mrshenli — APPROVED** [review]
> Move all of the DistributedOptimizer classes into the torch.distributed.optim page as in this PR, and have the Distributed RPC Framework page link to this

I'd vote for this option :)

The `rpc.html` page is also becoming too long overhead. This would help to make it easier to consume.

**Pull request closed without merging**
