### PR TITLE
Reland 2 of Merge more symbolic meta kernels and symint changes from branch (#86334)

### PR DESCRIPTION
**Pull request by albanD**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #86606
* #86605
* #86604
* #86603
* __->__ #86488
* #86487

symintify split_with_sizes, dropout, fused_fake_obs_quant. meta for padding_2d ops

add meta_bernoulli_

meta kernel for at::gather

get pytorch_struct to pass: meta for scatter_add, fix backward

symintify split ops

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by osalpekar** [comment]
Adding a link to the Phab diff for more details: [D40232598](https://www.internalfb.com/diff/D40232598). And the job that's failing: https://www.internalfb.com/intern/sandcastle/job/31525198185065069/

**Comment by bdhirsh** [comment]
Looks like the error has to do with a missing out= variant for `split.Tensor`: `RuntimeError: Missing out variant for functional op: aten::split.Tensor(Tensor(a -> *) self, SymInt split_size, int dim=0) -> Tensor(a)[] `

@larryliu0820 since that op doesn't exist in core - we could either fix it up internally (patch the schema to say `SymInt`), or we could delete it completely. Does deleting sound ok to you? (I remember we hit a similar issue with a different `view.out` op a few weeks ago).

**Comment by larryliu0820** [comment]
@bdhirsh it's not easy as that. Internally we have user using `split.Tensor` and needs its out variant. We will clean up these non-functional use cases altogether but it takes time. I guess for now we could add a hack to alias `SymInt` to `int`, since the runtime doesn't need to care about `SymInt`.

**Pull request closed without merging**
