### PR TITLE
[BE] Remove external testing of torch::deploy

### PR DESCRIPTION
**Pull request by PaliC**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #127952

As we don't expect external users of torch::deploy as the library is no longer supported, we will remove external testing.

### CODE REVIEW

**Review by malfet — APPROVED** [review]
cc: @seemethere

**Review by ZainRizvi — COMMENTED** [review]
> we don't expect external users of torch::deploy as the library is no longer supported

To clarify, are there still internal users/tests that we might regress accidentally?

**Comment by PaliC** [comment]
@ZainRizvi yes but internal testing should capture it

**Pull request closed without merging**
