### PR TITLE
Temporarily move ROCm to unstable

### PR DESCRIPTION
**Pull request by kit1980**
CI SEV https://github.com/pytorch/pytorch/issues/99578

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Review by orionr — APPROVED** [review]
LGTM

**Comment by heidongxianhua** [comment]
@kit1980  thank you to fix this, and I have got this error for my PR, and I want to konw how to merge again ? https://github.com/pytorch/pytorch/pull/99535

**Comment by kit1980** [comment]
> @kit1980 thank you to fix this, and I have got this error for my PR, and I want to konw how to merge again ? #99535

@heidongxianhua I posted a comment on your PR, should be merged soon if no other failures.

**Comment by jithunnair-amd** [comment]
@kit1980 Can your team explore a github-issue based method of moving jobs to unstable and back? It seems like that would be much easier than having to create multiple PRs? Something on the lines of how we disable certain UTs using github issues eg.: https://github.com/pytorch/pytorch/issues/99126

**Comment by kit1980** [comment]
> @kit1980 Can your team explore a github-issue based method of moving jobs to unstable and back? It seems like that would be much easier than having to create multiple PRs? Something on the lines of how we disable certain UTs using github issues eg.: #99126

@jithunnair-amd I can disable with issues now, but I wanted to move to unstable instead to have a signal immediately when the space issue resolves.
We probably can extend the issues functionality to move to unstable.

**Comment by heidongxianhua** [comment]
> > @kit1980 thank you to fix this, and I have got this error for my PR, and I want to konw how to merge again ? #99535
> 
> @heidongxianhua I posted a comment on your PR, should be merged soon if no other failures.

yeah, thank you,I got it. And in this PR, there is a stange error with macos ciflow, it failed because without triton 
 https://github.com/pytorch/pytorch/actions/runs/4748495785/jobs/8434993549

**Comment by huydhn** [comment]
> @kit1980 Can your team explore a github-issue based method of moving jobs to unstable and back? It seems like that would be much easier than having to create multiple PRs? Something on the lines of how we disable certain UTs using github issues eg.: #99126

@jithunnair-amd It's a feature that I have in my queue.  We have recently allowed job to be disabled with a github-issue as @kit1980 points out.  It's indeed the next phase in that project to allow job to be moved to unstable in a similar way.  So stay tuned :)

**Comment by kit1980** [comment]
> yeah, thank you,I got it. And in this PR, there is a stange error with macos ciflow, it failed because without triton

@heidongxianhua that we shouldn't probably ignored.
I've deleted my comment, the merge will not go through.
Please figure out how to fix the MacOS test, rebase, and merge again.

**Comment by kit1980** [comment]
F

**Pull request closed without merging**
