### PR TITLE
[OSS] Enable Flight Recorder buffer for all

### PR DESCRIPTION
**Pull request by c-p-i-o**
Summary: Enable collecting Flight Recorder data for all.

Test Plan: This has been rolled out internally for a while now.

Differential Revision: D66897635

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k

### CODE REVIEW

**Comment by kwen2501** [comment]
Just for our record, with this flag turned on, we are still leaving the following flags off:
1. ENABLE_TIMING
2. DUMP_ON_TIMEOUT
@c-p-i-o does that reflect the case?

**Review by kwen2501 — APPROVED** [review]
Great! Thanks for turning it on!

**Review by fduwjj — APPROVED** [review]
Yeah!!

**Comment by c-p-i-o** [comment]
> Just for our record, with this flag turned on, we are still leaving the following flags off:
> 
> 1. ENABLE_TIMING
> 2. DUMP_ON_TIMEOUT
> 
> @c-p-i-o does that reflect the case?

Yup - we're not touching ENABLE_TIMING and DUMP_ON_TIMEOUT with this change @kwen2501

**Review by wconstab — APPROVED** [review]

**Pull request closed without merging**
