### PR TITLE
Revert "Revert "Nvfuser code removal (#111093)""

### PR DESCRIPTION
**Pull request by jjsjann123**
This reverts commit 715dfced72657e5adacd5bef16e3d458cd94851b.

The original PR #111093 is reverted due to broken internal build.

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Comment by jjsjann123** [comment]
So public CI looks green. 
@davidberard98 feel free to drag me if anything shows up during internal CI that I can be of help. :bow:

**Review by davidberard98 — APPROVED** [review]
Patched some internal builds and seems like test are passing now.

**Comment by malfet** [comment]
@jjsjann123 @davidberard98 please please please please do not title PRs Revert "Revert ...., as it makes them hard to read. Reland is much better term imo

**Comment by jjsjann123** [comment]
> @jjsjann123 @davidberard98 please please please please do not title PRs Revert "Revert ...., as it makes them hard to read. Reland is much better term imo

Sorry about this one~~ I'll be more cautious on this next time :bow:

**Pull request closed without merging**
