### PR TITLE
Add all 3.12 binary build for wheel. Let's see how it goes. V2

### PR DESCRIPTION
**Pull request by albanD**
Fixes #ISSUE_NUMBER

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by albanD** [comment]
@pytorchbot merge

It's all green!

**Review by sammcj — APPROVED** [review]

**Comment by Kenshiro-28** [comment]
I tested torch 2.1.1 (released yesterday on Pypi) with Docker image python:3.12-slim

https://pypi.org/project/torch/

Still can't install it, I get this error:

ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

**Comment by albanD** [comment]
@Kenshiro-28 not until this is merged and the nightly build is triggered to get it for the nightly install.
For release install, it will be included in the upcoming 2.2 in Jan (see dev-discuss forum for details on the timing).

**Comment by Kenshiro-28** [comment]
> @Kenshiro-28 not until this is merged and the nightly build is triggered to get it for the nightly install. For release install, it will be included in the upcoming 2.2 in Jan (see dev-discuss forum for details on the timing).

Ok, thank you! :)

**Pull request closed without merging**
