### PR TITLE
[docs] Fix broken links in `contribution_guide.rst` and `governance.rst`

### LINKED ISSUE #37716: Broken link from "Contribution Guide" to "Governance"
## 📚 Documentation

The link to [PyTorch Governance](https://pytorch.org/docs/source/community/governance.rst) seems to be broken, when accessed from PyTorch Contribution Guide (both on the [master version](https://pytorch.org/docs/master/community/contribution_guide.html#the-pytorch-contribution-process) and the [stable version](https://pytorch.org/docs/stable/community/contribution_guide.html#the-pytorch-contribution-process)).

Though, when [viewing from Github](https://github.com/pytorch/pytorch/blob/master/docs/source/community/contribution_guide.rst#the-pytorch-contribution-process), it does seem to work. But it leads to the [Github `*.rst` version](https://github.com/pytorch/pytorch/blob/master/docs/source/community/governance.rst).

Is this a bug or a desired behaviour?

### PR DESCRIPTION
**Pull request by ShawnZhong**
Fix #37716

Fix three broken links in the documentation: 
- [PyTorch Governance](https://pytorch.org/docs/source/community/governance.rst) in the [Contribution Guide page](https://pytorch.org/docs/master/community/contribution_guide.html#the-pytorch-contribution-process)
- [PyTorch Governance | Persons of Interest](https://pytorch.org/docs/source/community/persons_of_interest.rst) under the [Core Developer section](https://pytorch.org/docs/master/community/governance.html#core-developers)
- [PyTorch Contributor Guide](https://pytorch.org/docs/source/community/contribution_guide.rst) under the [FAQ session of the Governance Page](https://pytorch.org/docs/master/community/governance.html#faq)

The old link leads to the `.rst` source file, which does not exist on the server. 

It's now fixed using the [document cross-referencing syntax](https://www.sphinx-doc.org/en/1.8/usage/restructuredtext/roles.html#cross-referencing-documents)

### CODE REVIEW

**Comment by ShawnZhong** [comment]
See fixed version at:
- https://5346602-65600975-gh.circle-artifacts.com/0/docs/community/governance.html
- https://5346602-65600975-gh.circle-artifacts.com/0/docs/community/contribution_guide.html

**Comment by mruberry** [comment]
Thanks for the fix! Running it through our internal tests now.

**Comment by ShawnZhong** [comment]
@mruberry Is there a chance I can know why the internal test is failing?

**Comment by mruberry** [comment]
> @mruberry Is there a chance I can know why the internal test is failing?

Just a glitch in how the results are reported to Github. Landing your PR now!

**Pull request closed without merging**
