### PR TITLE
Spectral norm value test

### PR DESCRIPTION
**Pull request by redwrasse**
Spectral norm implementation has extensive tests, but there doesn't appear to be any checking that indeed the spectral norm (= top singular value) is correctly calculated. There should at least be one such testcase.

This adds one such testcase for the parameterizations.py implementation of spectral norm.

### CODE REVIEW

**Comment by redwrasse** [comment]
Also does the spectral norm work on complex-valued networks? Tried changing type to `torch.cfloat` in the same test in this PR and got non-deterministic updated complex weights, rather than the expected `diag(1., 0.5)`.

**Review by soulitzer — APPROVED** [review]
Thanks!

**Comment by soulitzer** [comment]
> Also does the spectral norm work on complex-valued networks? Tried changing type to torch.cfloat in the same test in this PR and got non-deterministic updated complex weights, rather than the expected diag(1., 0.5).

Looks like it doesn't. And thanks I see that you've already filed an issue.

**Comment by soulitzer** [comment]
@redwrasse looks like test failures are real, you need to skip the dynamo variant of the test in `torch/testing/_internal/dynamo_test_failures.py`

**Comment by redwrasse** [comment]
@soulitzer thanks for pointing out the test failure, I'll add in the skip.

**Pull request closed without merging**
