### PR TITLE
Add missing ceil for libdevice in triton

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96709

Towards fixing pnasnet5large

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by ezyang** [comment]
I vaguely remember ngimel mentioning that she didn't want to add in this libdevice so that she could figure out some better way of solving the problem. Feel free to NACK this if necessary. (Also I will add tests if people agree this is fine.)

**Comment by ngimel** [comment]
That's fine I guess, @nkaretnikov's PR also needed to convert result to int64, but if you don't need this `ceiling` use is likely legit.

**Review by jansel — APPROVED** [review]

**Comment by ezyang** [comment]
This doesn't completely fix pnasnet5large, it still fails compiling:

```
def triton_(in_ptr0, out_ptr0, ks0, ks1, ks2, xnumel, XBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x1 = (xindex // ks0) % ks0
    x0 = xindex % ks0
    x2 = (xindex // ks2)
    x4 = xindex
    tmp0 = (-1) + x1 + ((-1)*((((-1)*((((-3) + ks1) // 2))) // 2))) + ((-1)*(tl.libdevice.ceil(((1/2) + ((1/2)*((((-3) + ks1) // 2)))))))
    tmp1 = 0
    tmp2 = tmp0 >= tmp1
    tmp3 = 165
    tmp4 = tmp0 < tmp3
    tmp5 = (-1) + x0 + ((-1)*((((-1)*((((-3) + ks1) // 2))) // 2))) + ((-1)*(tl.libdevice.ceil(((1/2) + ((1/2)*((((-3) + ks1) // 2)))))))
    tmp6 = tmp5 >= tmp1
    tmp7 = tmp5 < tmp3
    tmp8 = tmp2 & tmp4
    tmp9 = tmp8 & tmp6
    tmp10 = tmp9 & tmp7
    tmp11 = tl.load(in_ptr0 + ((-2) + x0 + x1 + x2 + ((-1)*((((-3) + ks1) // 2))) + ((-2)*((((-1)*((((-3) + ks1) // 2))) // 2))) + ((-2)*(tl.libdevice.ceil(((1/2) + ((1/2)*((((-3) + ks1) // 2))))))) + (x1*((((-3) + ks1) // 2))) + (x2*(((((-3) + ks1) // 2))*((((-3) + ks1) // 2)))) + ((-1)*((((-1)*((((-3) + ks1) // 2))) // 2))*((((-3) + ks1) // 2))) + ((-1)*((((-3) + ks1) // 2))*(tl.libdevice.ceil(((1/2) + ((1/2)*((((-3) + ks1) // 2))))))) + (2*x2*((((-3) + ks1) // 2))) + tl.zeros([XBLOCK], tl.int32)), tmp10 & xmask, other=0)
```

looks like our printing of Half is incorrect, at least

**Comment by ezyang** [comment]
> The computed pad value (where libdevice is coming from) should be hoisted, the exansion in tl.store is super confusing

How does the hoisting you added previously work? I'm wondering if we need a fancier algorithm for it.

> I thought x0 + x1 + x2 can't possibly be right, because conceptually the code should be x0 + stride_1 * x1 + stride_2 * x2 (and it's generated like this for static shapes), but turns out the expression is correct, just awkwardly expanded

I have always thought it weird that we prefer the expansion of (x + 1) * (x + 1), rather than keeping it factored. If I had my way, I wouldn't actually do expanding...

**Comment by ngimel** [comment]
Yeah we need a fancier algorithm. I hoisted values that are shapes of the participating tensors, but padding is not a shape per se, so it doesn't get matched. I'll try to adjust it to match padding too.

**Comment by ngimel** [comment]
I'll send a PR soon to hoist out padding values, I'm looking into what's causing expands.

**Pull request closed without merging**
