### PR TITLE
[pipelining] refactor schedule to remove num_microbatches arg

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #127979

Remove `n_microbatches` argument from our public `Schedule` constructors since this value can be inferred from the stage(s).

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

### CODE REVIEW

**Comment by kwen2501** [comment]
Good intention on cleaning up API args!
I don't have a clear preference at this point.

`num_microbatches` seems closer to schedule if we put code aside, because a schedule is defined by a number of microbatches crossing a number of stages.

In future we may allow user to create a new schedule or reconfigure the `num_microbatches` of an existing schedule, without recreating a stage.

Today the stage needs the `num_microbatches` information because we pre-allocate this many recv buffers. I wonder if this reliance could go away by using ping-pong buffers.

**Comment by kwen2501** [comment]
In the spirit of reducing API arg redundancy, do you mind creating a PR that does something similar but on the other side?

1. remove `num_microbatches` from stage's API surface.
2. delay stage's buffer creation till schedule's instantiation, i.e. schedule's `__init__` will make a call to stage to create buffers. In that ask, `num_microbatches` information will be passed.
3. move backward's recv buffer creation to that ask too. Today we don't create the backward buffer till the first backward call, because stage does not know whether this is backward or not, till the schedule triggers a backward call. But that is arguably too lazy (not ideal for CUDA Graph). So we can use this chance to move it ahead of run time.

Wdyt?

Cc @wconstab

**Comment by wconstab** [comment]
> In the spirit of reducing API arg redundancy, do you mind creating a PR that does something similar but on the other side?

remove num_microbatches from stage's API surface.
delay stage's buffer creation till schedule's instantiation, i.e. schedule's __init__ will make a call to stage to create buffers. In that call, num_microbatches information will be passed.
move backward's recv buffer creation to that call too. Today we don't create the backward buffer till the first backward call, because stage does not know whether this is backward or not, till the schedule triggers a backward call. But that is arguably too lazy (not ideal for CUDA Graph). So we can use this chance to move it ahead of run time. Schedule will pass has_backward flag in that call too.


yea, that does sound better to me.

**Comment by H-Huang** [comment]
Based on feedback, closing this and doing https://github.com/pytorch/pytorch/pull/128201 instead

**Pull request closed without merging**
