### PR TITLE
Implement double backwards cumprod, fix double backwards prod

### PR DESCRIPTION
**Pull request by gchanan**

### CODE REVIEW

**Comment by gchanan** [comment]
This may conflict with https://github.com/pytorch/pytorch/pull/1884 because of the list of excluded double backwards tests.

**Comment by gchanan** [comment]
previous version was missing "@staticmethod" which caused it to fail on python2.

**Comment by gchanan** [comment]
In addition to "cumprod", this now fixes double backwards "prod" and enables "norm" testing by lowering the precision requirements.

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
this brings to complete implementing double-backwards for all torch.* functions

**Pull request merged**
