### PR TITLE
[DataPipe] Adding ShufflerMapDataPipe

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #68606

Implements part of #57031

cc @VitalyFedyunin @ejguan @NivekT

Differential Revision: [D32813290](https://our.internmc.facebook.com/intern/diff/D32813290)

### CODE REVIEW

**Review by ejguan — COMMENTED** [review]
Why not just permutate the indices?

**Comment by NivekT** [comment]
> Why not just permutate the indices?

By that, do you mean calling `random.shuffle(indices)` once upfront?

The current implementation does the same thing lazily whenever a new index is called. If an index has been called before then it just returns the value. The behavior is the same, but it is executed lazily and looks slightly more complicated.

**Comment by ejguan** [comment]
> The current implementation does the same thing lazily whenever a new index is called. If an index has been called before then it just returns the value. The behavior is the same, but it is executed lazily and looks slightly more complicated.

Yeah. It's lazily executed. But, the memory for indices is not lazily initialized. I am not sure how much it will benefit from lazy execution

Can you run some simple runtime tests with different size for two implementations? 
- Initialization time
- Time per iteration
- Total time

**Comment by NivekT** [comment]
> > The current implementation does the same thing lazily whenever a new index is called. If an index has been called before then it just returns the value. The behavior is the same, but it is executed lazily and looks slightly more complicated.
> 
> Yeah. It's lazily executed. But, the memory for indices is not lazily initialized. I am not sure how much it will benefit from lazy execution
> 
> Can you run some simple runtime tests with different size for two implementations?
> 
> * Initialization time
> * Time per iteration
> * Total time

The current implementation is about 10x faster when initializing but slower per iteration. When the number of elements is large, the random.shuffle method is clearly better.

```
Current implementation speed:
Initialization time: 0.0005209445953369141
Total time: 0.7119569778442383
Average iteration time: 7.09010362625122e-05

random.shuffle speed:
Initialization time: 0.004917144775390625
Total time: 0.013039827346801758
Average iteration time: 5.932807922363281e-07
```

Based on this we should go with `random.shuffle` and ignore the requirement to lazily `__getitem__` for this DataPipe, unless we still worry about the initialization time. I will update the PR with the new implementation unless you have further objections.

For reference, below is the code snippet that I used:
```
import time
import numpy as np
n_elements = 10000
input_dp = dp.map.SequenceWrapper(range(n_elements))
start = time.time()
shuffler_dp = input_dp.shuffle()
init_time = time.time()
print()
print("Current implementation speed:")
print(f"Initialization time: {init_time - start}")
iter_time = []
for i in range(len(shuffler_dp)):
    curr_iter_start_time = time.time()
    value = shuffler_dp[i]
    curr_iter_end_time = time.time()
    iter_time.append(curr_iter_end_time - curr_iter_start_time)
end = time.time()
print(f"Total time: {end - start}")
print(f"Average iteration time: {np.average(iter_time)}")

print()
print("random.shuffle speed:")
start = time.time()
shuffler_dp = input_dp.shuffle_two()
init_time = time.time()
print(f"Initialization time: {init_time - start}")
iter_time = []
for i in range(len(shuffler_dp)):
    curr_iter_start_time = time.time()
    value = shuffler_dp[i]
    curr_iter_end_time = time.time()
    iter_time.append(curr_iter_end_time - curr_iter_start_time)
end = time.time()
print(f"Total time: {end - start}")
print(f"Average iteration time: {np.average(iter_time)}")
```

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32813290).

**Review by ejguan — APPROVED** [review]
LGTM

**Pull request closed without merging**
