### PR TITLE
guard on flash attention SymFloat scale instead of incorrectly casting to float

### PR DESCRIPTION
**Pull request by bdhirsh**
Fixes https://github.com/pytorch/pytorch/issues/141710. Previously, if we called flash attention with a `SymFloat` scale that was properly symbolic, we would unsafely cast its raw `SymFloat._data` into a `float`, which is pretty much guaranteed to give `NaN`.

This avoids the NaNs in the linked issue, but I'm not sure if it's worth landing yet because we'll start specializing and recompiling for every distinct `scale` that is passed in (which in the dynamic shapes case, is some function of `query.size(-1)`).

The real fix would be to ensure that the flash attention (and related) ops all accept a symbolic version of the `scale`. I'm not sure if we should use `SymFloat` or `Scalar` though - more discussion in the issue

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #141728
* __->__ #141725

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Use __FILE__ and __LINE__

Specializing is better than silently wrong. Time to audit all other sites of this...

Need test.

**Comment by ezyang** [comment]
There are a lot of other sites that need to be fixed.

```
aten/src/ATen/native/cpu/FlashAttentionKernel.cpp:      sdp::calculate_scale(query, scale).as_float_unchecked();
aten/src/ATen/native/cpu/FlashAttentionKernel.cpp:      sdp::calculate_scale(query, scale).as_float_unchecked();
aten/src/ATen/native/mps/operations/Attention.mm:  auto scale_factor = sdp::calculate_scale(query, scale).as_float_unchecked();
aten/src/ATen/native/transformers/attention.cpp:            query_padded, key_padded, value_padded, dropout_p, is_causal, false /*return_debug_mask*/, og_scale.as_float_unchecked());
aten/src/ATen/native/transformers/cuda/attention.cu:  const auto softmax_scale = sdp::calculate_scale(query, scale).as_float_unchecked();
aten/src/ATen/native/transformers/cuda/attention.cu:      sdp::calculate_scale(query, scale).as_float_unchecked();
aten/src/ATen/native/transformers/cuda/attention.cu:  const auto softmax_scale = sdp::calculate_scale(query, scale).as_float_unchecked();
aten/src/ATen/native/transformers/cuda/attention.cu:    p.scale = sdp::calculate_scale(query, scale).as_float_unchecked();
aten/src/ATen/native/transformers/cuda/attention_backward.cu:  const auto softmax_scale = sdp::calculate_scale(query, scale).as_float_unchecked();
aten/src/ATen/native/transformers/cuda/attention_backward.cu:    const auto softmax_scale = sdp::calculate_scale(query, scale).as_float_unchecked();
aten/src/ATen/native/transformers/cuda/attention_backward.cu:  const auto softmax_scale = sdp::calculate_scale(query, scale).as_float_unchecked();
aten/src/ATen/native/transformers/cuda/attention_backward.cu:    p.scale = sdp::calculate_scale(query, scale).as_float_unchecked();
```

cc @drisspg

**Comment by bdhirsh** [comment]
I can audit the sites as part of this PR, thanks for the links. And landing specialization first sounds good

**Comment by drisspg** [comment]
For my understanding, if the size is a true float and not symbolic this returns the correct result? 

It is much less common in a user program (that isn't doing benchmarking) to vert the head dim size, which is way this hasn't shown up earlier

**Comment by bdhirsh** [comment]
> For my understanding, if the size is a true float and not symbolic this returns the correct result?

yup that's right - that basically maps to this code: https://github.com/pytorch/pytorch/blob/main/c10/core/SymFloat.h#L41 (it is only safe to treat `_data` as a `float` if `!is_symbolic()`)

**Comment by bdhirsh** [comment]
Looks like all of the other sites are inside of kernels (registered to backend dispatch keys), so `as_float_unchecked()` should be ok

**Comment by ezyang** [comment]
> Looks like all of the other sites are inside of kernels (registered to backend dispatch keys), so as_float_unchecked() should be ok

Nah, we should use the guard in that case. I don't want `as_float_unchecked` except in core framework code.

**Comment by bdhirsh** [comment]
sgtm, will update. (I'll try to land this PR tomorrow)

**Pull request closed without merging**
