### PR TITLE
[MPS] Handle scalar input for scatter and gather

### PR DESCRIPTION
**Pull request by abhudev**
Issue noticed in test consistency - "Indexing dim 0 is out of bounds of tensor"

### CODE REVIEW

**Review by kulinseth — APPROVED** [review]

**Comment by kulinseth** [comment]
```
File "fake_numpy/numpy.py", line 1, in <module>
[372](https://github.com/pytorch/pytorch/actions/runs/3153608229/jobs/5130419950#step:10:373)
    raise ModuleNotFoundError("Sorry PyTorch, but our NumPy is in the other folder")
[373](https://github.com/pytorch/pytorch/actions/runs/3153608229/jobs/5130419950#step:10:374)
ModuleNotFoundError: Sorry PyTorch, but our NumPy is in the other folder
```
Errors seem unrelated.

**Comment by abhudev** [comment]
pytorchbot merge -f "MPS tests are green"

**Pull request closed without merging**
