### PR TITLE
Quantization kernals renamed in native_functions.yaml

### LINKED ISSUE #40315: Rename all "quantization" kernels in the native_functions.yaml
Current naming convention for the quantized ops is `quantized_...`. However, with the introduction of different devices, such as quantized cuda, this will become a little hard to maintain. Need to rename all the `quantized_...` names into `..._quantized_cpu`, which is the pattern for the non-quantized kernels.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @dzhulgakov

### PR DESCRIPTION
**Pull request by harshvardhan2707**
Updated from format ```quantized_...``` to ```..._quantized_cpu``` for some cpu kernels.
Fixes #40315

### CODE REVIEW

**Comment by albanD** [comment]
Hey!
Is there any quantization maintainer that you're working with on this?  Not sure who to add as a reviewer tbh.

**Comment by harshvardhan2707** [comment]
> Hey! Is there any quantization maintainer that you're working with on this? Not sure who to add as a reviewer tbh.

I'm not working with a quantization maintainer, although #40315 is the issue I was fixing so people involved in that can be of help

**Comment by harshvardhan2707** [comment]
@albanD what's the status of merging and do I require any more changes in this?

**Comment by supriyar** [comment]
> #40315

I think so, @jerryzh168 can you confirm this and help review this PR?

**Comment by jerryzh168** [comment]
yeah I can review this, looks like we need changes to the function names in these files as well: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/Normalization.cpp#L382

**Review by jerryzh168 — CHANGES_REQUESTED** [review]
need to change the function names in C++ files as well, e.g. https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/Normalization.cpp#L382

**Comment by harshvardhan2707** [comment]
> need to change the function names in C++ files as well, e.g. https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/Normalization.cpp#L382

Similar to the changes that I've made right? Just changing the names from ```quantized_...``` to ```..._quantized_cpu```?

**Comment by jerryzh168** [comment]
> > need to change the function names in C++ files as well, e.g. https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/Normalization.cpp#L382
> 
> Similar to the changes that I've made right? Just changing the names from `quantized_...` to `..._quantized_cpu`?

yes, please find the corresponding definition for each of the functions you changed in C++ files and change them, also please make sure the CI is all green as well

**Pull request closed without merging**
