### PR TITLE
Scopes 0.3.1 backport

### PR DESCRIPTION
**Pull request by lantiga**
This PR addresses the request for backporting scopes to 0.3.1 in #4821.

### CODE REVIEW

**Comment by ezyang** [comment]
FYI, CI is failing because the Jenkins job has changed since 0.3.0. To get CI working again we'll have to backport most of the changes to `.jenkins`, e.g.

e93ece90a5c9addf7e1b14e88223b35acd126b68
e776f69ddd1c9f3765a3fb8cd65d6f4ea1ec554c
390d542db2bcc884c33c3a81d56576b56ede72cd
e22095b09d19f2b9aa964ea10139eb11340624fd

**Comment by lantiga** [comment]
Thanks @ezyang, I was wondering what was going on...

**Comment by soumith** [comment]
@lantiga is this locally passing all tests? (including onnx tests) if so this is good enough for me.

**Comment by lantiga** [comment]
Yep, I ran all tests from the sh script on my Mac.

**Pull request merged**
