### PR TITLE
[BE] Merge with statements together

### PR DESCRIPTION
**Pull request by Skylion007**
Saves some unnecessary indentation by merging with statements together if they are of equivalent scope. Makes the code more readable and potentially more performant / modern. Follow up to #94419 

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by Skylion007** [comment]
Hmm, darn it's showing all the changes of #94419 as well. :/

**Comment by ezyang** [comment]
You can use ghstack to solve this problem https://github.com/ezyang/ghstack

**Comment by Skylion007** [comment]
@ezyang Would you take a look now that the other PR is merged?

**Comment by ezyang** [comment]
Hmm. For some of these it's not obviously an improvement, because the context manager expr is quite long. Find someone for a second opinion. @malfet maybe?

**Comment by Skylion007** [comment]
> Hmm. For some of these it's not obviously an improvement, because the context manager expr is quite long. Find someone for a second opinion. @malfet maybe?

2 reasons this is better.

1. Less indentation
2. it makes it clear which context managers share the same scope

**Comment by malfet** [comment]
> 2. it makes it clear which context managers share the same scope

But it makes the combined statement harder to read, especially if it's a multiline one.
I.e. following is not nice, but parseable
```
        ) if throw_on_early_termination else contextlib.suppress():
            with Join(
```
while following is downright confusing
```
        ) if throw_on_early_termination else contextlib.suppress(), Join(
```

Is there some linter that argues that one is better then the other?

IMO it's akin to replacing:
```
 a = 1
 b = 2
 c = 3 
```
with
```
a, b, c = 1, 2, 3
```
, which is nice when variable names, statements are short, but quite confusing when it's something like
```
(odd_numbers,
 even_numbers,
 prime_numbers) = 
(
  [1 , 3, 5, 7],
  [2, 4, 6, 8],
  [1, 3, 5, 7]
)
```

**Comment by ezyang** [comment]
It's still contextual though; if the inside is relatively simple like

```

            for _ in inputs:
                for allreducer in allreducers:
                    allreduce_total += allreducer(num_allreduces)
```

the saved indentation is just not buying that much

**Pull request closed without merging**
