### PR TITLE
Run mypy over test/test_utils.py

### PR DESCRIPTION
**Pull request by rgommers**
This caught one incorrect annotation in `cpp_extension.load`. 

xref gh-16574.

### CODE REVIEW

**Comment by rgommers** [comment]
All CI failures are unrelated (all are "missing `boto3`"). This should be good to go.

**Review by ezyang — APPROVED** [review]

**Comment by rgommers** [comment]
@walterddr where can I see the reason for this revert? I assume it was a cross-merge conflict in `test_utils.py` and I can resubmit this PR unchanged, but would be good to be sure.

**Comment by walterddr** [comment]
correct. this was a cross merge conflict. i think the revert has been reverted by 3ce539881a

**Comment by rgommers** [comment]
Thanks! Commit 3ce539881a was for a different PR, so I'll resubmit this one now.

**Pull request closed without merging**
