### PR TITLE
Add a RemoteException class to show exceptions with more than one arguments in ExceptionWrapper

### LINKED ISSUE #34130: ExceptionWrapper cannot handle exceptions with more than one argument
## 🐛 Bug

_utils.py: ExceptionWrapper cannot handle exceptions with more than one argument

## To Reproduce

1. Create a DataLoader
2. Raise an error that takes multplie arguments in the constructor, eg. `urllib.error.HTTPError`

```
/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 4 required positional arguments: 'code', 'msg', 'hdrs', and 'fp'
```

## Expected behavior

ExceptionWrapper shouldn't throw in reraise. The exception should be wrapped in a generic Exception or initialized with all arguments (not sure if that's possible? Perhaps passing the exception object from the worker would be better)

## Environment

Please copy and paste the output from our
PyTorch Version (e.g., 1.0): 1.4.0
OS (e.g., Linux): CentOS 6.3
How you installed PyTorch (conda, pip, source): pip
Build command you used (if compiling from source):
Python version: 3.6.5
CUDA/cuDNN version: 10.0, 7.5
GPU models and configuration: P4

### PR DESCRIPTION
**Pull request by ydaiming**
@SsnL
Fix #34130
#30147
#25522
(Open a new PR to avoid merging issues.)

I added a RemoteException class to save a stringification of the exception for later reraise.
I reproduced the problem with code given in #30147. Now the output will traceback to the RemoteException, which provides the original traceback.

The traceback before:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/miniconda3/envs/openai/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/miniconda3/envs/openai/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/miniconda3/envs/openai/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 1 required positional argument: 'b'
```
The new experience will be:
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    next(iter(d))
  File "/home/ubuntu/reraise/pytorch/torch/utils/data/dataloader.py", line 354, in __next__
    data = self._next_data()
  File "/home/ubuntu/reraise/pytorch/torch/utils/data/dataloader.py", line 980, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/reraise/pytorch/torch/utils/data/dataloader.py", line 1005, in _process_data
    data.reraise()
  File "/home/ubuntu/reraise/pytorch/torch/_utils.py", line 407, in reraise
    raise self.exc
torch._utils.RemoteTraceback: 
"""
Caught E in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/reraise/pytorch/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/reraise/pytorch/torch/utils/data/_utils/fetch.py", line 28, in fetch
    data.append(next(self.dataset_iter))
  File "test.py", line 10, in __iter__
    raise E(a=1, b=2)
E: Special exception message
"""
```

Not sure if the change fails any check. Also, maybe we can remove the special case for "KeyError" as well.

### CODE REVIEW

**Comment by ydaiming** [comment]
I looked into the failing tests in the PR. The reason is:
Original tests expect the original exception (e.g. `RuntimeError`) to be raised, but with the new `RemoteException` class, only `RemoteException` will be raised.
I'll change these tests if @SsnL confirms my addition of the new RemoteException class. Other suggestions are also welcome.

**Review by ssnl — CHANGES_REQUESTED** [review]
Hi! Thanks for working on this!  However, we should still raise the original exception type. The Python code I linked in the original issue this does this. And it achieves so by changing the `__cause__` to include the remote traceback. Could you also use that pattern?

**Comment by ydaiming** [comment]
> Hi! Thanks for working on this! However, we should still raise the original exception type. The Python code I linked in the original issue this does this. And it achieves so by changing the `__cause__` to include the remote traceback. Could you also use that pattern?

I think the problem remains as, the arguments for the original exception won't be saved, so the original exception type couldn't be re-constructed. 

The open issues I link in the description (#34130, #30147, #25522), not only relate to specific exception types, but also self-defined exceptions. Therefore, a work around like for `KeyError` (https://github.com/ydaiming/pytorch/blob/8f28a0774e249750e9ebbf8d30a4f9ed17cf9ec6/torch/_utils.py#L392)
won't work generally for self-defined exception (#30147).

Maybe I misunderstood something about `__cause__()` or `__reduce__()`, could you please elaborate more on your point? 

Thanks!
@SsnL

**Comment by SsnL** [comment]
@ydaiming Sorry for not being clear. What I meant is that we should just serialize the exception, and abort this `type + args` hack (which was introduced to handle traceback https://github.com/pytorch/pytorch/pull/44#discussion_r81016475, but we should just set `__cause__` similar to [this](https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/concurrent/futures/process.py#L129-L131))

**Comment by ejguan** [comment]
Hey @ydaiming, thanks for your PR.
Since it's been a while, I am wondering if you are still working on it?

**Comment by ydaiming** [comment]
> Hey @ydaiming, thanks for your PR.
> Since it's been a while, I am wondering if you are still working on it?

Yeah, it's been a while, I had to move on to something else. You're welcome to take some ideas here and port it to your own PR. I don't expect myself to work on this issue in at least a month.

**Pull request closed without merging**
