### PR TITLE
Split rnn primitive for inference and training

### PR DESCRIPTION
**Pull request by yanbing-j**
## Description
Currently, both inference and training will use `forward_training` in rnn primitive, which will bring performance downgrade for inference (The performance drop is from rnn primitive and unnecessary creation of `pd` and `workspace`). This PR is to split them into `forward_inference` and `forward_training` seperately.

## Performance
With this fix PR, in RNN-T inference, the throughput reduction is 167 ms, which increases `3.7%` of E2E time.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
LGTM. I suppose we have tests to cover both paths, right?

**Comment by yanbing-j** [comment]
> LGTM. I suppose we have tests to cover both paths, right?

Yes. The tests can cover both paths.

**Comment by mingfeima** [comment]
cool!

**Pull request closed without merging**
