### PR TITLE
[HOO][dynamo] Contextual hints for torch.compile backends

### LINKED ISSUE #118181: [HOO][torch.compile] Contexts and passing forward node meta to backward node
### 🚀 The feature, motivation and pitch

Hello,
I have implemented some feature that allows to wrap "contexts" of operations using Higher Order Ops. It basically implements wrap-example-like HOO and variable with some minor differences, namely one causing all ops generated within an HOO to have access to a stack of HOO's that wrapped it, effectively allowing to feed nodes with additional metadata specified by the user and passing this data through functionalization of FWD graph within aot_autograd.

For example, you can consider this pseudocode:

```
def some_subcode_part1(in1, in2, hint):
    tmp1 = in1 * in2 #node A
    tmp2 = in1 / in2 #node B

    return tmp1, tmp2

def some_subcode_part2(tmp1, tmp2, hint):
    out1 = tmp1 + tmp2 #node C
    out2 = tmp1 - tmp2 #node D

    return out1, out2

def some_code(in1, in2, hint):
    tmp1, tmp2 = torch.ops.higher_order.hinted_context(some_subcode_part1, in1, torch.max(in2), hint='{"mode": "1"}')
    out1, out2 = torch.ops.higher_order.hinted_context(some_subcode_part2, tmp1, tmp2, hint='{"mode": "2"}')
    
    return out1, out2

_(...somewhere within torch.compiled model...)_
out1, out2 = torch.ops.higher_order.hinted_context(some_code, out, x, hint='{"tune": "True"}')
```
Feature I have implemented causes nodes A and B to have meta of {tune: True, mode:1} and nodes C and D to have meta of {tune: True, mode:2} as visible in FX graph provided to user fw_compiler. This meta creation happens during creation of joint graph to be precise.

Now, I'd like to extend this feature so that it will also pass this metadata to backward graph created by autograd (BWD nodes should take this metadata from corresponding FWD nodes they were created from). Could you recommend the best approach here to pass it?

### Alternatives

_No response_

### Additional context

_No response_

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @ydwu4

### LINKED ISSUE #126393: Allowing topology writer to pass hints to accelerator backends
### 🚀 The feature, motivation and pitch

**High level idea:**
We would sometimes like the end user to be allowed to add additional context into our backend. Ideally, we would do that in a way that could allow him to attach this information to specific operations of his choice. Later in the flow, backend can utilize this information to provide better optimization or execution scheme resembling more what user expected. It allows more versatile programmability. Examples are, but are not limited to: choosing the streams, deciding on order of execution, hinting slicing schemes, bundling sets of operations together, and so on. In the case of scheduling we have various options, like BFS, DFS, or even more custom execution order (strict scheduling) provided by the user to satisfy his needs. These "hints" can be optional to be supported by the backend, or they might be supported but backend might decide to ignore them if they cannot be fullfilled or fullfilling them would break other mechanisms functional-wise or performance-wise.

**Specific use case:**
For purpose of this ticket, let's focus on very specific use case that we have currently in our Gaudi stack. For flash attention operation, we can execute its' batch*num_heads parallel slices either in DFS or BFS manner. For various operations, it is quite often more performant to go with BFS because it gives more parallel paths that can be executed simultaneously at a given time, thus making it easier to parallelize the work across the execution engines. But in the case of flash attention, where the size of memory needed might be a significant issue, up to the point where topology cannot fit on the accelerator, it might be better to go DFS, because that way we only need to allocate memory for a single parallel slice at a time, and then we can reuse all the intermediate tensors for next paths. That way we might sacrifice some of the raw performance, but also reduce the amount of memory needed to compute this operation almost linearly with the amount of slices available. Such trade-off might be critical for other accelerators with smaller amount of memory.

**Limitation to solve:**
Unfortunately, backend compilers usually can't be completely sure what is the best approach to compute arbitrary subgraph because they don't know what is important for the user, and they don't know what are the expected constraints E2E-workload-wise. This is why sometimes it is good to allow user to provide some kind of "hints". And those "hints" would benefit also other backends that would like to give user this kind of choices.

**Design considerations:**
_First consideration is_ - from end-user point of view, to achieve this kind of programmability, he could either:

1. For every chunk of operations user would like to hint, wrap their inputs and outputs with custom OPs containing those hints and let backend graph analysis infer the hints regions from those based on data flow. Somewhat similarly to what partitioner is doing.
2. Reuse Higher Order OP (HOO) mechanism to wrap groups, possibly nested, of operations with specific hints and provide them via meta field for these ops.

Our recommendation is the second option, because first one would require either backend or pytorch to implement tricky graph analysis to automagically wrap the nodes, while HOO does that by design during the tracing. Also, user experience is much better when using HOO, because one does not have to track the unobvious data flow to correctly wrap more complicated cases with nested hinting.

_Second consideration is_ - if we go into the HOO option, we need to choose between the flavor we would use it:

1. Fully generic *hinted_context* HOO.
**pros:**
everyone can use it for everything
**cons:**
hints could be easily lost in graph transformations due to many possible hints in such generic case

2. Set of dedicated ops, for presented use case it would be *graph_schedule* HOO as an example.
**pros:**
clear purpose of specific OP
easier to track such OP inside transformations
still can be used by everyone
**cons:**
need to create such OP for every usage, could prove tedious and hard to maintain at some point
there is still some risk of losing the hints somewhere on the way

3. Accelerator-specific (e.g. Gaudi only) custom HOO that can be registered by backends at runtime.
**pros:**
every backend need to care only about its own custom HOOs
**cons:**
end-user need to track and use different OPs depending on accelerator he wants to use
migrating workloads between accelerators would become harder
there is no such custom HOO registration mechanism anyway

Our recommendation is to go with first option. It is easiest to implement, maintain and use. But let's discuss its' only caveat of losing the hints on the way:

First risk is losing those in torch.compile implementation in the framework itself. This can be mitigated by allowing these OPs only in autograd.Function custom implementations which are traced only at stage of AOT, which is quite far in the stack and there are no (at least I'm not aware of those) other transformations that could pose significant risk from that point.

Second risk is losing hints in the accelerator backend. As this is optional feature, every backend is free to opt-in by implementing safe graph transformations with the hints it declares it supports. There is no risk at all for backends that do not want to support hints at all, it is free to ignore them.

_Third consideration is_ - how to emit "hint" information to the accelerator backend:

1. Using nodes metadata field.
**pros:**
easy to implement
easy to use if wanted
easy to ignore if not wanted
**cons:**
easy to lose

2. Injecting additional "hint" nodes into graph that would tie closely with hinted nodes.
**pros:**
harder to lose
**cons:**
much harder to implement
going to be visible in backends that do not want this feature at all

Our recommendation is to go with the metadata option, as it is easiest and can be completely transparent for backends not interested in the feature or not ready for it. But backends using this feature would need to pay close attention to nodes metadata.

Feature PR that goes along with our recommendations: https://github.com/pytorch/pytorch/pull/121639

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kbadz-pl**
**Idea:**
Described in ticket attached to this PR.

**Design proposition:**
Implemented **hinted_context** higher-order-op that allows to specify function, arguments and a **hint**.

The **hint** currently is a JSON string that is going to be propagated into all ops within specified function. Such hints can be nested to provide even more structure to the operations. In that case, JSON objects are going to be automatically merged and presented as a string, again.

Hints can be specified in two manners: 
- **hints only inside the FWD code**, in that scenario hints are going to be visible in FWD only (this is optional path and we can choose to disallow it as explained in the ticket)
- **hints inside autograd overridden ops**, in that scenario user can specify hints for FWD and BWD separately (preferred path)

Provided test shows various usages, including nested annotations for both cases above. Each test runs on dummy backend that just prints the hint metadata from the nodes:
image

Fixes #126393

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by ydwu4** [comment]
Thank you for your contribution! The HOP feature seems useful in certain cases, but it's important to consider the potential uncertainties it could create and handle them carefully in different places. For example, when exporting, we need to serialize and deserialize the metadata, but hints can be of arbitrary type and may not be serializable. Additionally, we need to preserve the hint across transformations to avoid accidentally dropping it during the process, but the correct way of dealing with the hint might depend on the specific transformation and we can never be sure it's always correct because we don't know what kind of hint users can provide us.

Also cc @ezyang @zou3519 @bdhirsh for comments.

**Comment by kbadz-pl** [comment]
Hello @ydwu4 @tugsbayasgalan - any update on the review or additional feedback? Thanks.

**Comment by ydwu4** [comment]
Hi @kbadz-pl, we had some discussion on this recently. Our feeling is that we don't want user-defined meta on node in general cause they're fragile and easy to be mutated/ be lost in transformations.

The alternative proposal is 1. we preserve the HOP after aot_autograd (in contrast to current PR, where we inline the context manager in `__call__` of `HintedContext`). Examples of doing this include while_loop.py/cond.py 2. run a separate pass that that inlines the context managers by appending the hint of enclosing context managers to the nodes' meta (e.g. in the customized backend). This approach allows the context to be explicitly preserved in the graph (which is the starting point of export users) and allows more customizability for where to inline the metadata. Does this proposal sound reasonable to you?

**Comment by wuxun-zhang** [comment]
> we preserve the HOP after aot_autograd (in contrast to current PR, where we inline the context manager in __call__ of HintedContext). Control flow operators such as while_loop and cond do it in this way.

@ydwu4 A question here - does this mean there will be nested submodules with different HintedContext args? Is there any code reference for cond/while_loop? Thanks.

**Comment by ydwu4** [comment]
yeah,  there will be nested submodules with different HintedContext args

The implementation of while_loop and cond can be found in torch/_higher_order_ops/cond.py and while_loop.py.

**Comment by kbadz** [comment]
> Hi @kbadz-pl, we had some discussion on this recently @zou3519. Our feeling is that we don't want user-defined meta on node in general cause they're fragile and easy to be mutated/ be lost in transformations.
> 
> The alternative proposal is:
> 
> 1. we preserve the HOP after aot_autograd (in contrast to current PR, where we inline the context manager in `__call__` of `HintedContext`). Control flow operators such as while_loop and cond do it in this way.
> 2. run a separate pass that that inlines the context managers by appending the hint of enclosing context managers to the nodes' meta (e.g. in the customized backend).
> 
> This approach allows the context to be explicitly preserved in the graph (which is the starting point of export users) and allows more customizability of where to inline the metadata. Does this proposal sound reasonable to you?

It sounds reasonable.

Your proposal basically shifts the responsibility to work properly with the hints from dynamo to the user backend that want to actually use the feature, which could lower the availability of the feature and make hints more backend-specific, but on the other hand it should give more control to the user backends and make it safer to the overall system. Assuming we won't encounter any serious issues while implementing "tracing into" recursive HOPs inside the backend to inline them, as opposed to the original idea, then it should be fine.

We will try doing that, thank you for you reply.

**Comment by wuxun-zhang** [comment]
Hi @ydwu4, I am trying to extend `torch._higher_order_ops.wrap` for hints propagation. As `speculate_subgraph` will automatically (by default) set subgraph inputs, if there is an input (for example `hints`) without usage inside fn, it looks `speculate_subgraph` will not preserve it as subgraph input. In this way, we may need make hints into submodule's meta. Any thoughts here? Thanks.

```python
def wrap_fn(x):
    def outer_body_fn(x, hints):
      return res.mul(2)

    return wrap_with_hints(outer_body_fn, x, hints={"outer_body": True})
```

**Comment by ydwu4** [comment]
It's would be more explicit if we keep hint as a kwarg. After speculate_subgraph, can we try adding hint to the p_kwargs of the call_function proxy?

**Comment by wuxun-zhang** [comment]
@ydwu4 Thanks for advice, now I can get below graph module with nested hints.

```python
class GraphModule(torch.nn.Module):
    def forward(self, L_x_: "f32[4, 2]", L_y_: "f32[2]"):
        l_x_ = L_x_
        l_y_ = L_y_

         # File: /home/wzhang/workspace/pytorch-upstream/test/test_cond.py:53 in wrap_fn, code: return wrap_with_hints(outer_body_fn, x, y, hints={"outer_body": True})
        wrap_body_1 = self.wrap_body_1
        wrap_with_hints = torch.ops.higher_order.wrap_with_hints(wrap_body_1, l_x_, l_y_, hints = {'outer_body': True});  wrap_body_1 = l_x_ = l_y_ = None
        getitem: "f32[4, 2]" = wrap_with_hints[0];  wrap_with_hints = None
        return (getitem,)

    class GraphModule(torch.nn.Module):
        def forward(self, l_x_: "f32[4, 2]", l_y_: "f32[2]"):
             # File: /home/wzhang/workspace/pytorch-upstream/test/test_cond.py:48 in outer_body_fn, code: res = wrap_with_hints(inner_body_fn, x, y, hints={"inner_body": True})
            wrap_body_0 = self.wrap_body_0
            wrap_with_hints = torch.ops.higher_order.wrap_with_hints(wrap_body_0, l_x_, l_y_, hints = {'inner_body': True});  wrap_body_0 = l_x_ = None
            getitem: "f32[4, 2]" = wrap_with_hints[0];  wrap_with_hints = None

             # File: /home/wzhang/workspace/pytorch-upstream/test/test_cond.py:50 in outer_body_fn, code: return res.mul(y)
            mul: "f32[4, 2]" = getitem.mul(l_y_);  getitem = l_y_ = None
            return (mul,)

        class GraphModule(torch.nn.Module):
            def forward(self, l_x_: "f32[4, 2]", l_y_: "f32[2]"):
                 # File: /home/wzhang/workspace/pytorch-upstream/test/test_cond.py:46 in inner_body_fn, code: return x.add(y)
                add: "f32[4, 2]" = l_x_.add(l_y_);  l_x_ = l_y_ = None
                return (add,)
```

**Comment by kbadz** [comment]
Final approved version implemented and merged by @wuxun-zhang in his PR: https://github.com/pytorch/pytorch/pull/132860 

Thanks everyone. Closing.

**Pull request closed without merging**
