### PR TITLE
[quant] conv_transpose1d / conv_transpose2d

### PR DESCRIPTION
**Pull request by z-a-f**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #43199 [quant] conv_transpose graph patterns
* #40371 [quant] ConvTranspose1d / ConvTranspose2d
* **#40370 [quant] conv_transpose1d / conv_transpose2d**

Differential Revision: [D22158979](https://our.internmc.facebook.com/intern/diff/D22158979)

### CODE REVIEW

**Comment by z-a-f** [comment]
There is a weird bug, that I was tracking the whole weekend -- would appreciate if someone could tell me what's wrong.

Here is repro code

```python

import numpy as np
import torch
from torch import nn

torch.backends.quantized.engine = 'qnnpack'

B = 2
L = 24

iC = 1
oC = 2
kL = 1

strides = (1,)
pads = (0,)
o_pads = (0,)
dilations = (1,)
groups = 1

X = torch.randn(B, iC, L).to(torch.float)
W = torch.randn(iC, oC // groups, kL)

X_s = 1.2
X_zp = 0
X_dtype = torch.quint8

W_s = 0.2
W_zp = 0
W_dtype = torch.qint8

b = None

y_s = 4.2
y_zp = 0

#################

X_q = torch.quantize_per_tensor(X, X_s, X_zp, X_dtype)
W_q = torch.quantize_per_tensor(W, W_s, W_zp, W_dtype)

#################

kernel_size = kL,

conv_ref = nn.ConvTranspose1d(iC, oC, kernel_size, stride=strides, padding=pads,
                              output_padding=o_pads, groups=groups,
                              bias=(b is not None), dilation=dilations)

conv_ref.weight = nn.Parameter(W)
if b is not None:
  conv_ref.bias = nn.Parameter(b)

y_ref = conv_ref(X)
y_ref_dq = torch.quantize_per_tensor(y_ref, y_s, y_zp, X_dtype).int_repr()

#################
W_prepack = torch.ops.quantized.conv_transpose1d_prepack(W_q, b, strides, pads,
                                                         o_pads, dilations,
                                                         groups)
W_unpacked, bias = torch.ops.quantized.conv_transpose1d_unpack(W_prepack)

print(W_q.dequantize() - W_unpacked.dequantize())


#################

y_q = torch.ops.quantized.conv_transpose1d(X_q, W_prepack, y_s, y_zp).int_repr()

#################

print(y_ref_dq.to(torch.float) - y_q.to(torch.float))

print(
  f'''
    iC: {W.shape[0]}
    oC: {W.shape[1] * groups}
    k: {W.shape[2:]}
  '''
)
```

result for the difference is expected to have maximum 1-off (actually >1-off due to deconv), but it looks like the only the first `iC` channels in the output are correct. That means that if `oC > iC`, the rest of the channels are off :'(

Output:

```console
tensor([[[0.],
         [0.]]])
tensor([[[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.],
         [  0., -36.,   0.,   0.,   0., -36., -36.,   0., -36.,   0.,   0.,
            0.,   0.,   0., -36.,   0., -73., -73.,   0.,   0., -36., -36.,
            0.,   0.]],

        [[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
            0.,   0.],
         [  0., -36.,   0.,   0.,   0., -36.,   0.,   0.,   0.,   0.,   0.,
            0.,   0., -36.,   0.,   0., -36.,   0., -36.,   0.,   0.,   0.,
          -36.,   0.]]])

    iC: 1
    oC: 2
    k: torch.Size([1])

```

**Comment by kimishpatel** [comment]
@z-a-f, I can't say without knowing the details of the op. I am assuming this does not fail with fbgemm backend.
One thing I can suggest is: Can you print raw y_q result and see what is there in the second channel? I am wondering if second channel is not populated at all. Additionally in your implementation you can perhaps zero out the output tensor to confirm if the second is not populated at all vs populated with wrong data.

**Review by vkuzo — COMMENTED** [review]
would it make sense to add a numerical correctness test in this PR?

**Comment by z-a-f** [comment]
> would it make sense to add a numerical correctness test in this PR?

Oh actually the tests somehow became part of the previous PR (#40360). I think after moving files around, tests for this PR became parts of its parent.

**Review by vkuzo — COMMENTED** [review]
looks good.  Should we add a numerical correctness test in this PR?

**Comment by z-a-f** [comment]
> looks good. Should we add a numerical correctness test in this PR?

Yes -- I had the tests, they accidentally were submitted as part of a different PR -- I will migrate them here

**Review by vkuzo — APPROVED** [review]
lg as long as CI passes.  Can we include the context and the test plan in the PR summary before landing, since this is non-trivial?

**Pull request closed without merging**
