### PR TITLE
adding IterableDataset to utils.data.__init__

### PR DESCRIPTION
**Pull request by DuckSoft**
this shall fix issue #27820 again

### CODE REVIEW

**Review by ssnl — COMMENTED** [review]
could you add ChainDataset, get_worker_info too?

**Comment by DuckSoft** [comment]
Sure! I will do that!

**Review by vincentqb — APPROVED** [review]
LGTM, also with @SsnL's requested change if possible.

**Comment by DuckSoft** [comment]
> could you add ChainDataset, get_worker_info too?

@SsnL I have added those! Have a check please!

**Review by ssnl — APPROVED** [review]
Thanks! LGTM

**Pull request closed without merging**
