### PR TITLE
Make GPU loops support mutable lambda

### PR DESCRIPTION
**Pull request by zasdfgbnm**
I will need it for https://github.com/pytorch/pytorch/pull/34004

The `mutable` qualifier allows a lambda to capture some values, and modify its own copy. This would be useful for random kernels: we capture a `state` of RNG, initialize it when it first run, and the initialized stated will be used later:

```C++
gpu_kernel(iter, [state, initialized](scalar_t arg) mutable -> scalar_t {
  if (!initialized) {
    curand_init(..., state);
    initialized = true;
  }
  return some_math(curand_uniform(state), arg);
}
```

The `operator()` of `mutable` lambda is not `const`, so we can not pass it as constant reference. It can not be called inside a non-`mutable` lambda either. 

Example usage:

```C++
auto t = at::empty({4096}, kCUDA);
float thread_work_index_ = 0;
auto iter = TensorIterator::nullary_op(t);
gpu_kernel(iter, [thread_work_index_]GPU_LAMBDA() mutable -> float {
  return thread_work_index_++;
});
```

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Windows failure is flaky:
```
C:\Users\circleci\project\torch\csrc\api\include\torch/optim/optimizer.h(62): error C2201: 'const torch::optim::OptimizerCloneableOptions<`private: virtual void __cdecl OptimTest_OldInterface_Test::TestBody(void)'::`2'::MyOptimizerOptions>::`vftable'': must have external linkage in order to be exported/imported
..\test\cpp\api\optim.cpp(191): note: see reference to class template instantiation 'torch::optim::OptimizerCloneableOptions<OptimTest_OldInterface_Test::TestBody::MyOptimizerOptions>' being compiled
Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28610.4 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

**Comment by zasdfgbnm** [comment]
@VitalyFedyunin or @ngimel Could you take a look at this?

**Review by ngimel — APPROVED** [review]
lgtm

**Comment by ngimel** [comment]
Can you please rebase to see if failures go away?

**Comment by zasdfgbnm** [comment]
@ngimel Sure

**Comment by zasdfgbnm** [comment]
Just resolved a conflict

**Pull request closed without merging**
