### PR TITLE
Codegen: Fix operator::name on windows

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #62188
* #62187
* #62186
* __->__ #62278
* #62185
* #62184

In `Operators.h` we're using `str(BaseOperatorName)`, while in
`OperatorsEverything.cpp` we're using `str(OperatorName)`. e.g.
```
STATIC_CONSTEXPR_STR_INL_EXCEPT_WIN_CUDA(name, "aten::abs")
```
vs
```
STATIC_CONST_STR_OUT_OF_LINE_FOR_WIN_CUDA(abs_out, name, "aten::abs.out")
```

Differential Revision: [D29962047](https://our.internmc.facebook.com/intern/diff/D29962047)

### CODE REVIEW

**Comment by bdhirsh** [comment]
Good catch! We probably didn't catch this in CI before because the codegen wasn't directly using `name` and `overload_name` from each struct to invoke the dispatcher, and the only user of that metadata currently is pytorch/xla (which doesn't build with windows in CI afaik).

Looks like there are CI failures, not sure if they're due to failures further down the stack?

**Comment by peterbell10** [comment]
>Looks like there are CI failures, not sure if they're due to failures further down the stack?

The errors in the asan build are coming from the stack. Forward mode AD errors are coming from master though I think.

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29962047).

**Review by bdhirsh — APPROVED** [review]

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29962047).

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29962047).

**Pull request closed without merging**
