### PR TITLE
Remove torch distributed from CODEOWNERS

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #112813

After adding support for labeler, we don't need CODEOWNERS.

This change will cause the distributed team members previously listed in
CODEOWNERS to stop being auto-added as reviewers on PRs touching these
files.  The preceding PR adds labeler support for these same sets of
files, and contains instructions for adding yourself to be cc'd for that
label.

It is preferable to be auto-cc'd rather than auto-tagged as reviewer, so
that there is more signal in the reviewers list (either someone opted in
which shows the PR author someone is likely looking at it, or the PR
author added someone specifically which is a stronger notification to
the tagged reviewer than the blanket CODEOWNERS behavior.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @yf225 @kiukchung @d4l3k @lucasllc

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]
lgtm

**Review by fduwjj — APPROVED** [review]

**Comment by fegin** [comment]
Should we just let users to remove themselves from the CODEOWNERS? Some people may still want to get the notifications under distributed?

**Comment by wconstab** [comment]
> Should we just let users to remove themselves from the CODEOWNERS? Some people may still want to get the notifications under distributed?

**Comment by wconstab** [comment]
y

**Comment by wconstab** [comment]
@mrshenli @zhaojuanmao @rohan-varma @kiukchung @d4l3k I hesitated about whether to migrate you from CODEOWNERS over to labeler.  In the end i did add all of you to labeler, so you'll be CC'd on all the same PRs you used to be tagged on as reviewer.  If you are no longer interested in these notifications you can just remove yourself by editing the summary of https://github.com/pytorch/pytorch/issues/24422 directly, no need for a stamp or approval.

**Pull request closed without merging**
