### PR TITLE
[pytorch] Update docstring for FSDP.set_state_dict_type

### PR DESCRIPTION
**Pull request by daniellepintz**
Summary: I noticed optim_state_dict_config was missing from the Args section

Test Plan: N/A

Reviewed By: rohan-varma

Differential Revision: D46670165

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]

**Comment by rohan-varma** [comment]
pls fix lint before landing

**Review by fegin — APPROVED** [review]
LGTM

**Comment by daniellepintz** [comment]
Hi, how do I land this?

**Review by fduwjj — APPROVED** [review]

**Comment by fduwjj** [comment]
@daniellepintz you can use pytorchbot to rebase and merge on Github first. Then the diff will be landed in a diff train which you don't need to worry about.

**Comment by daniellepintz** [comment]
@rohan-varma @fduwjj @fegin Could someone pls help me land this PR?

**Pull request closed without merging**
