### PR TITLE
Fix cudnn ctc loss backward

### LINKED ISSUE #49046: Backward pass fails due to CTCLoss in case zero_infinity=True and torch.backends.cudnn.enabled=True
## 🐛 Bug

When I use CTCLoss with `zero_infinity=True` and at the same time `torch.backends.cudnn.enabled=True`, and run backward() on its result, the script crashes with the following error:

```
Traceback (most recent call last):
  ...
  File ".../new_ctc_loss_bug.py", line 29, in <module>
    loss.backward()
  File "...\Anaconda3\envs\my-env\lib\site-packages\torch\tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "...\Anaconda3\envs\my-env\lib\site-packages\torch\autograd\__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: The size of tensor a (0) must match the size of tensor b (177) at non-singleton dimension 2
Exception raised from infer_size at ..\aten\src\ATen\ExpandUtils.cpp:24 (most recent call first):
00007FFAED8175A200007FFAED817540 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFAC311B0EB00007FFAC311AED0 torch_cpu.dll!at::infer_size [<unknown file> @ <unknown line number>]
00007FFAC338617400007FFAC3385DC0 torch_cpu.dll!at::native::DispatchStub<void (__cdecl*)(at::Tensor & __ptr64,at::Tensor & __ptr64,at::Tensor const & __ptr64,__int64,bool),at::native::min_stub>::choose_cpu_impl [<unknown file> @ <unknown line number>]
00007FFAC338902400007FFAC3388F00 torch_cpu.dll!at::native::where [<unknown file> @ <unknown line number>]
00007FFAC36AF6A700007FFAC361D060 torch_cpu.dll!at::zeros_out [<unknown file> @ <unknown line number>]
00007FFAC49AB50E00007FFAC485E010 torch_cpu.dll!torch::autograd::GraphRoot::apply [<unknown file> @ <unknown line number>]
00007FFAC3150BFF00007FFAC3146470 torch_cpu.dll!torch::nn::functional::BatchNormFuncOptions::~BatchNormFuncOptions [<unknown file> @ <unknown line number>]
00007FFAC35BC66600007FFAC35B8FA0 torch_cpu.dll!at::bucketize_out [<unknown file> @ <unknown line number>]
00007FFAC361CBF400007FFAC361CB90 torch_cpu.dll!at::where [<unknown file> @ <unknown line number>]
00007FFAC479D46A00007FFAC479CE80 torch_cpu.dll!torch::autograd::Node::`default constructor closure' [<unknown file> @ <unknown line number>]
00007FFAC47AB75B00007FFAC47AB5B0 torch_cpu.dll!torch::autograd::generated::CudnnCtcLossBackward::apply [<unknown file> @ <unknown line number>]
00007FFAC4797E9100007FFAC4797B50 torch_cpu.dll!torch::autograd::Node::operator() [<unknown file> @ <unknown line number>]
00007FFAC4CFF9BA00007FFAC4CFF300 torch_cpu.dll!torch::autograd::Engine::add_thread_pool_task [<unknown file> @ <unknown line number>]
00007FFAC4D003AD00007FFAC4CFFFD0 torch_cpu.dll!torch::autograd::Engine::evaluate_function [<unknown file> @ <unknown line number>]
00007FFAC4D04FE200007FFAC4D04CA0 torch_cpu.dll!torch::autograd::Engine::thread_main [<unknown file> @ <unknown line number>]
00007FFAC4D04C4100007FFAC4D04BC0 torch_cpu.dll!torch::autograd::Engine::thread_init [<unknown file> @ <unknown line number>]
00007FFA66C9090700007FFA66C69FE0 torch_python.dll!THPShortStorage_New [<unknown file> @ <unknown line number>]
00007FFAC4CFBF1400007FFAC4CFB780 torch_cpu.dll!torch::autograd::Engine::get_base_engine [<unknown file> @ <unknown line number>]
00007FFB1C9F10B200007FFB1C9F0F70 ucrtbase.dll!beginthreadex [<unknown file> @ <unknown line number>]
00007FFB1E3B7C2400007FFB1E3B7C10 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
00007FFB1EC0D4D100007FFB1EC0D4B0 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]
```

## To Reproduce

1. Download the file with variables  https://drive.google.com/file/d/1eltV2WjDVTuRBXO0n6E5t5dkQ3GEW6Qj/view?usp=sharing
1. Run the code:
``` python
import torch
import pickle


assert torch.cuda.is_available() and torch.backends.cudnn.enabled

# https://drive.google.com/file/d/1eltV2WjDVTuRBXO0n6E5t5dkQ3GEW6Qj/view?usp=sharing
with open('ctc_bug.pkl', 'rb') as f:
    variables = pickle.load(f)

log_probs = variables['log_probs'].cuda()
targets = variables['targets'].cpu()
target_lengths = variables['target_lengths'].cuda()

# with `zero_infinity=False` it works well
ctc_loss = torch.nn.CTCLoss(zero_infinity=True).cuda()

assert torch.isfinite(log_probs.max()) and torch.isfinite(log_probs.min())

# with `torch.backends.cudnn.enabled = False` it works well
T, N, C = log_probs.shape
loss = ctc_loss(
    log_probs=log_probs,
    targets=targets,
    input_lengths=torch.full(size=(N,), fill_value=T, dtype=torch.int32).cuda(),
    target_lengths=target_lengths
)
assert torch.isfinite(loss)
loss.backward()

```

## Expected behavior

No crash

## Environment

```
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A
OS: Microsoft Windows 10 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce MX150
Nvidia driver version: 451.67
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] numpydoc==0.8.0
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              h74a9793_1  
[conda] libblas                   3.8.0                    16_mkl    conda-forge
[conda] libcblas                  3.8.0                    16_mkl    conda-forge
[conda] liblapack                 3.8.0                    16_mkl    conda-forge
[conda] mkl                       2020.1                      216  
[conda] numpy                     1.19.1           py36h12ee977_2    conda-forge
[conda] numpydoc                  0.8.0                    py36_0  
[conda] pytorch                   1.6.0           py3.6_cuda102_cudnn7_0    pytorch
[conda] torchvision               0.2.1                    pypi_0    pypi

Python 3.6.8
print(torch.cuda.get_device_properties(0))
_CudaDeviceProperties(name='GeForce MX150', major=6, minor=1, total_memory=2048MB, multi_processor_count=3)
print('CUDA version:', torch.version.cuda)
CUDA version: 10.2
print('CUDNN version:', torch.backends.cudnn.version())
CUDNN version: 7605
```

## Additional context

I am also able to reproduce the error with the following configuration:
```
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A
OS: Њ ©Єа®б®дв Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 441.28
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0
[pip3] torchaudio==0.7.0
[pip3] torchvision==0.8.1
[conda] Could not collect

Python 3.7.9
print(torch.cuda.get_device_properties(0))
_CudaDeviceProperties(name='GeForce GTX 1080', major=6, minor=1, total_memory=8192MB, multi_processor_count=20)
print('CUDA version:', torch.version.cuda)
CUDA version: 10.2
print('CUDNN version:', torch.backends.cudnn.version())
CUDNN version: 7605

```

__But (!) with the following configuration everything works fine:__
```
PyTorch version: 1.1.0
Is debug build: False
CUDA used to build PyTorch: 10.0
ROCM used to build PyTorch: N/A
OS: Њ ©Єа®б®дв Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 441.28
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.1.0
[conda] Could not collect

Python 3.6.8
print(torch.cuda.get_device_properties(0))
_CudaDeviceProperties(name='GeForce GTX 1080', major=6, minor=1, total_memory=8192MB, multi_processor_count=20)
print('CUDA version:', torch.version.cuda)
CUDA version: 10.0
print('CUDNN version:', torch.backends.cudnn.version())
CUDNN version: 7401

```

cc @csarofeen @ptrblck

### PR DESCRIPTION
**Pull request by xwang233**
Fix cudnn ctc loss backward

Fix https://github.com/pytorch/pytorch/issues/49046, which was working in pytorch 1.1

Originally modified in this PR in Oct 2019, https://github.com/pytorch/pytorch/pull/27039/files#diff-25ec2c1108ee03e2167622588ec31d167897ef1cccb12a4cfe77eb98777316daR2383-R2392

According to the original code 

https://github.com/pytorch/pytorch/blob/90ffab6e3713a40f47f4c9d3d3b16d56e83f97c4/tools/autograd/derivatives.yaml#L1387-L1388

and the code after PR

https://github.com/pytorch/pytorch/blob/f461184505149560803855f3a40d9e0e54c64826/tools/autograd/templates/Functions.cpp#L2456-L2465

This `at::zeros({0}, raw_grad.options())` in line 2460 seems suspicious, and is causing `infer_size` runtime error

```
RuntimeError: The size of tensor a (0) must match the size of tensor b (177) at non-singleton dimension 2
Exception raised from infer_size at ..\aten\src\ATen\ExpandUtils.cpp:24 (most recent call first):
```

I've modified that to `at::zeros_like(raw_grad)`, which looks more accurate.

### CODE REVIEW

**Comment by t-vi** [comment]
The 0 size seems wrong, but would legitimate broadcasing work?

On April 22, 2021 12:02:04 AM GMT+02:00, X Wang ***@***.***> wrote:
***@***.*** requested your review on: pytorch/pytorch#56639 Fix cudnn ctc

**Comment by t-vi** [comment]
First, thank you for spotting and fixing this!
In more detail: I think creating a 0 element tensor is wrong here. :facepalm: 
However, I would also have a tendency to only create a dimensionless (shape `{}`-tensor, a scalar) and use broadcasting.
The memory/performance impact likely isn't large, but it always irks me to create large 0 tensors when they aren't strictly needed.

**Comment by albanD** [comment]
Ho, I thought that `at::where` would support broadcasting of the arguments? I feels common to do things like this `torch.where(a > 0, a, 0)` ?

**Comment by t-vi** [comment]
Yes, but a zero-element tensor is clearly an error.

**Comment by albanD** [comment]
Ho, I would read this as "create a Tensor with a single 0 element". But this is indeed the size...
So I would agree with @t-vi here that the right fix is to change it to properly generate a scalar Tensor with a single 0.

**Comment by xwang233** [comment]
@albanD Thanks for the suggestion. I'm not familiar with

> the right fix is to change it to properly generate a scalar Tensor with a single 0

Can you please suggest a change?

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
