### PR TITLE
Default on green

### PR DESCRIPTION
**Pull request by zengk95**
Reopens https://github.com/pytorch/pytorch/pull/78771

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]

**Comment by suo** [comment]
We should fast follow with a bot comment that actually tells people what's going on, otherwise people will be confused when `@pytorchbot merge` doesn't appear to do anything. 

For example, on this PR, the contributor used `merge -g` but then resorted to `merge` repeatedly because it looked like it didn't do anything: https://github.com/pytorch/pytorch/pull/78801

**Comment by Lezcano** [comment]
@suo fwiw, I have no idea what's going on in my PR. Could any of you get it merged? Otherwise, could you give me pointers on what I'm doing wrong?

**Pull request closed without merging**
