### PR TITLE
Delete lazy ddp optimizer

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #120727

This is no longer necessary now that the normal ddp optimizer works correctly with inductor strides.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @aakhundov

Differential Revision: [D54858819](https://our.internmc.facebook.com/intern/diff/D54858819)

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Review by yf225 — APPROVED** [review]
Should we do a gradual rollout of this PR internally (maybe via JustKnobs, cc. @wconstab), or do we feel confident that it will replace all existing lazy_compile use cases?

**Comment by eellison** [comment]
Sure, happy to do a gradual roll out. is there any example I can follow of how to use justknobs ?

**Comment by wconstab** [comment]
> Sure, happy to do a gradual roll out. is there any example I can follow of how to use justknobs ?

well, i have examples for how to do it for controlling an ENV that's checked anytime after `init_process_group`.  But in your case you need to update the dynamo config, so you'll have to do slightly more plumbing.  You can probably adapt the PT-D one (its in _utils_internal.py) but @ezyang has another one for general pytorch knobs that might be easier for you to use.

**Comment by ezyang** [comment]
`justknobs_check` in utils_internal is literally goes to justknobs.check and defaults to True in OSS. No bells or whistles.

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54858819).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54858819).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D54858819).

**Pull request closed without merging**
