### PR TITLE
[test] Add gtest dependency on aten tests.

### PR DESCRIPTION
**Pull request by Yangqing**
@ezyang delivering my promise to you :)

Basically, now aten tests can use gtest as part of our test harness unification effort. I also converted one test (atest.cpp) to show how one can do this.

### CODE REVIEW

**Comment by Yangqing** [comment]
Some inclusion path seems to be not working, can take a look later, but python setup.py build_deps should work for now.

**Comment by ezyang** [comment]
Unfortunately, we can't merge this as is because Caffe2 tries to run all the ATen tests as gtests, and that won't work until they're all ported.

**Review by zrphercule — COMMENTED** [review]
I guess so far we should better to keep both catch and gtest on stack, and slightly remove catch file by file? Aten is not the only place using catch, there are many catch tests in torch as well.
Check T32009899

**Comment by Yangqing** [comment]
I agree, let me see removing the explicit gtest arg in the test.sh works. In more strict terms, we probably also want to make the main function in libgtest_main.a a weak symbol, but I think by definition the main function defined by Catch2 will be used as it is in the object file.

**Review by ezyang — APPROVED** [review]

**Comment by Yangqing** [comment]
Looks like all jenkins are passing with 2 unrelated test errors - let me land then.

**Pull request closed without merging**
