### PR TITLE
Avoid configuring ROCm if USE_CUDA is on.

### PR DESCRIPTION
**Pull request by xuhdev**
Move the resolution of conflict between `USE_CUDA` and `USE_ROCM` to CMake as to effectuate:

- `USE_CUDA=ON` and CUDA is found, `USE_ROCM=ON` and ROCM is found --> fatal error
- Either `USE_CUDA=ON` and CUDA is found or `USE_ROCM=ON` and ROCM is found --> The respective GPU feature is ON
- Otherwise no GPU support

### CODE REVIEW

**Comment by xuhdev** [comment]
Any chance to get this reviewed? :)

**Comment by zdevito** [comment]
I don't have any context here and do not understand the ROCM build system so I am not a good person to review this.

**Comment by ezyang** [comment]
cc @iotamudelta @bddppq. I'm indifferent to the behavior in this patch

**Comment by ezyang** [comment]
@xuhdev do you think you could explain in what case this is helpful?

**Comment by xuhdev** [comment]
This should help with the case in which both CUDA and ROCm are present. This can well be the case since both `USE_CUDA` and `USE_ROCM` default to ON. As far as I understand, PyTorch cannot build with both libraries. This used to be (somewhat hackily) handled in `cuda.py` (which I'm in the process of deleting it). I now updated the PR to remove the relevant part in `cuda.py`.

**Comment by iotamudelta** [comment]
So will the silent assumption if both ROCm and CUDA are present be that the user wants to build for CUDA? Or will it be configurable and this just ensures that ROCm would not override a CUDA selection?

**Comment by xuhdev** [comment]
@iotamudelta Your first assumption is correct.

**Comment by iotamudelta** [comment]
Unsurprisingly, in that case I'll be against this change and would advocate going for option no 2.

**Comment by xuhdev** [comment]
@iotamudelta There seems to be a lot of confusion. Both `USE_CUDA` and `USE_ROCM` default to `ON`. The effect is:

- `USE_CUDA=ON` and CUDA is found, `USE_ROCM=ON` and ROCM can be found --> CUDA
- `USE_CUDA=OFF`, `USE_ROCM=ON` and ROCM can be found --> ROCM
- `USE_CUDA=ON` and CUDA is found, `USE_ROCM=OFF` --> CUDA
- Otherwise no GPU support

Which line do you think need to be changed in the above table?

**Comment by iotamudelta** [comment]
`USE_CUDA=ON` and `USE_ROCM=ON` should probably generate an error condition until compiling for both simultaneously is supported.

**Comment by xuhdev** [comment]
@iotamudelta Could you clarify a bit? Is it the first line, or the second line, or both?

**Comment by iotamudelta** [comment]
Here are the combinations I think should be valid (and I understand there is currently a discrepancy, but you are trying to fix that, yes?):
* `USE_ROCM=1` and `USE_CUDA=1` -> error "Choose either ROCm or CUDA"
* `USE_ROCM=1` and `USE_CUDA=0`, ROCm install found -> ROCm
* `USE_ROCM=1` and `USE_CUDA=0`, no ROCm install -> error
* ... equivalent CUDA cases ...
* `USE_ROCM=0` and `USE_CUDA=0` -> no GPU code

Would you agree?

**Comment by xuhdev** [comment]
@iotamudelta The situation is probably much more complicated than you thought :) The PR was intended to move some of the processing from the Python script to CMake (as a preparation for removing `cuda.py`), but we can also use the opportunity to fix the discrepancy issue.

* `USE_ROCM=1` and `USE_CUDA=1` -> error "Choose either ROCm or CUDA"

This is the default. That means, we would emit such an error by default if the user does not specify any GPU related build options.

* `USE_ROCM=1` and `USE_CUDA=0`, ROCm install found -> ROCm

Yep.

* `USE_ROCM=1` and `USE_CUDA=0`, no ROCm install -> error

This (the CUDA equivalent) was something that has been discussed in #24939: We prefer silently turning off a build option if the underlying library is not found, instead of forcing user to explicitly turn off.

* `USE_ROCM=0` and `USE_CUDA=0` -> no GPU code

Yep.

**Comment by iotamudelta** [comment]
@xuhdev Then I must have misunderstood your earlier comment. I understood it as "if CUDA and ROCm are both found and specified, go for CUDA" - that's the opposite of ejecting an error in that case.

**Comment by xuhdev** [comment]
I've updated the PR and its corresponding description in the original comment box.

**Review by ezyang — APPROVED** [review]
Great

**Review by iotamudelta — APPROVED** [review]
Thank you!

**Comment by trougnouf** [comment]
Any chance that both ROCm and CUDA will be supported simultaneously in the future ?

**Pull request closed without merging**
