### PR TITLE
Fix resize matrix_power.out dynamic shapes

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #113695

Fixes https://github.com/pytorch/pytorch/issues/113003

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]

**Review by lezcano — APPROVED** [review]

**Comment by ezyang** [comment]
bruh, the ci failures are real

**Comment by lezcano** [comment]
oops, sorry, I thought it was the CI just being the CI

**Pull request closed without merging**
