### PR TITLE
Add forward AD support for as_strided

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #68631
* __->__ #68629

Differential Revision: [D32899680](https://our.internmc.facebook.com/intern/diff/D32899680)

This PR and subsequent PRs in the stack will fail CI until this fix lands https://github.com/pytorch/pytorch/pull/69558. A reasonable alternative to that would be to not test batched forward grad for inplace ops at all (this functionality is currently tested and passing).

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
This is also in your forward AD PR no? 
And the changed tests are not the same. Which one is correct?

**Comment by soulitzer** [comment]
This one was before the OpInfo was added, so it is a bit out of date. The changes should be the same once I update, so if that one lands first, we can just remove this PR. Otherwise, this PR just guarantees the PRs above in the stack can use as_strided.

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32899680).

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32899680).

**Review by albanD — APPROVED** [review]
Sounds ok then

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32899680).

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32899680).

**Pull request closed without merging**
