### PR TITLE
Unfuse bias add before pointwise ops

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #107003
* #107004
* __->__ #106912
* #106911

I get a 2% inference speedup in HF with this PR. I checked to see if there any models where unfusing was slower than the cublas gelu fusion, and I did not see any, which was surprising to me. Sorry for the cublas-activation api churn 😬

Kicking off another run in cublas 12, it's possible that the results have changed since.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Comment by vadimkantorov** [comment]
for some ops, cublasLt can do mm+add+relu by itself, right?

**Review by jansel — APPROVED** [review]

**Comment by ZainRizvi** [comment]
> @pytorchbot merge -f "unrelated failure"

Hi @eellison, fyi this merge didn't need the `-f` flag.  If the [Dr. CI comment up top]https://github.com/pytorch/pytorch/pull/106912#issuecomment-1672193129) shows you the green checkmark, it means it's detected that the failures are not your fault and pytorchbot will let the regular `merge` command succeed

**Comment by ezyang** [comment]
@eellison can you link your perf runs on the PRs? Thanks

**Comment by ezyang** [comment]
Do you expect this to always be a win? It seems to fairly unambiguously regress [basic_gnn_edgecnn](https://hud.pytorch.org/benchmark/torchbench/inductor_with_cudagraphs?startTime=Sun,%2013%20Aug%202023%2023:25:52%20GMT&stopTime=Sun,%2020%20Aug%202023%2023:25:52%20GMT&granularity=hour&mode=inference&model=basic_gnn_edgecnn&dtype=bfloat16&lBranch=gh/eellison/513/head&lCommit=3f14bcd1aefba2cd2fbac622669381e2bcc45b26&rBranch=main&rCommit=2b1058c54273a73ed407f2a6495063e9ef18b54f)

image

which also agrees with your local run https://hud.pytorch.org/benchmark/torchbench/inductor_with_cudagraphs?startTime=Sun%2C%2013%20Aug%202023%2023%3A25%3A52%20GMT&stopTime=Sun%2C%2020%20Aug%202023%2023%3A25%3A52%20GMT&granularity=hour&mode=inference&dtype=bfloat16&lBranch=gh/eellison/513/head&lCommit=3f14bcd1aefba2cd2fbac622669381e2bcc45b26&rBranch=main&rCommit=2b1058c54273a73ed407f2a6495063e9ef18b54f

**Comment by ezyang** [comment]
It looks like sam also does worse with this change.

**Comment by eellison** [comment]
@ezyang on master I benchmarked with and without this commit and could not repro a sam regression, but I could repro an gnn_edgecnn regression.

**Pull request closed without merging**
