### PR TITLE
fix op not scriptable

### PR DESCRIPTION
**Pull request by terrychenism**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #70958

Differential Revision: [D33467184](https://our.internmc.facebook.com/intern/diff/D33467184)

### CODE REVIEW

**Comment by terrychenism** [comment]
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33467184).

**Review by jerryzh168 — APPROVED** [review]
lg

**Comment by terrychenism** [comment]
@terrychenism has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33467184).

**Comment by jerryzh168** [comment]
should this PR be closed?

**Comment by terrychenism** [comment]
> should this PR be closed?

Yes, already merged.

**Pull request closed without merging**
