### PR TITLE
move kernel launch checks from `torch.testing` to `torch.testing._internal.check_kernel_launches`

### PR DESCRIPTION
**Pull request by pmeier**
The fact that these functions are only used in a single test might be a good enough reason to move them to that module.

### CODE REVIEW

**Comment by mruberry** [comment]
As best I can tell this check is used exclusively in that test, but we might as well deprecating importing it from torch.testing like other functions

**Comment by pmeier** [comment]
> we might as well deprecating importing it from torch.testing like other functions

After some more offline discussion, we decided not to deprecate it, but to simply the functionality to `test/test_kernel_launch_checks.py`. @mruberry confirmed that there is no FB usage outside of this repository.

**Comment by mruberry** [comment]
cc @r-barnes and @ngimel 

Our goal with PRs like this is to make everything in the torch.testing module public-facing and documented, but if we'd like to maintain the runnability of this script maybe we could move it to a folder like testing/scripts and not import it as part of torch.testing by default?

**Comment by mruberry** [comment]
Update from offline discussion with @ngimel: it should be OK to make this private, we should do it after the 1.10 branch cut for safety

**Review by mruberry — APPROVED** [review]
Cool!

**Pull request closed without merging**
