### PR TITLE
[FSDP] remove unused flat_param_part_view

### PR DESCRIPTION
**Pull request by weifengpy**
flat_param_part_view is unused in pytorch repo: https://fburl.com/ssaomd7x

it became unused since refactoring in https://github.com/pytorch/pytorch/pull/115497

before that, the original code is below. Since flat_param is 1D, we do
not need .view for reshaping

```
self.flat_param.data = padded_unsharded_flat_param[
    : unsharded_size.numel()
].view(
    unsharded_size
)
```

unit test: pytest test/distributed/fsdp/test_fsdp_core.py

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Review by awgu — APPROVED** [review]
Thanks for the fix!

**Review by wconstab — APPROVED** [review]

**Comment by wconstab** [comment]
Fix lint

**Comment by awgu** [comment]
Lint failures looks unrelated 🤔 
Maybe rebasing will resolve it.

**Review by Skylion007 — APPROVED** [review]

**Comment by weifengpy** [comment]
> Fix lint

it's resolved in the trunk by others https://github.com/pytorch/pytorch/pull/117080 
test/quantization/pt2e/test_xnnpack_quantizer.py

**Pull request closed without merging**
