### PR TITLE
C++/CMake / Only link gcc_s library when making a shared library build (caffe only)

### PR DESCRIPTION
**Pull request by bsergean**
We are making a static build of libtorch for a static executable, and this is getting in our way.

The link fails with "gcc_s not found". I just found out that the _s version of libgcc is a shared library, so we can't bring in in a static build.

This fix just add a conditional to bring in gcc_s. The existing code only affect the caffe build.

cc @malfet @seemethere

### CODE REVIEW

**Comment by cyyever** [comment]
Sounds convincing

**Comment by bsergean** [comment]
Does this change make sense ?

**Comment by bsergean** [comment]
@cyyever or @drisspg can someone take another look at this please ?

It's going stale ... (to the trash ?) :)

**Review by cyyever — DISMISSED** [review]

**Review by desertfire — APPROVED** [review]

**Comment by desertfire** [comment]
@bsergean  please rebase as the auto-rebase failed.

**Comment by bsergean** [comment]
@desertfire I used the github UI in my fork to 'sync' my branch, with commit [96903ba](https://github.com/pytorch/pytorch/pull/126621/commits/96903ba22bfc01657edadbaf74be29671f4fb8cf)

(a merge commit thought). Is that enough ?

**Pull request closed without merging**
