### PR TITLE
[Caffe2] Use FixedDivisor in Reduce and Broadcast CUDA kernels

### PR DESCRIPTION
**Pull request by xiaomengy**
Summary: Use FixedDivisor in Reduce and Broadcast CUDA kernels

Differential Revision: D8710243

### CODE REVIEW

**Comment by BIT-silence** [comment]
For reduce ops, it can speed up for about 50%.
For elementwise binary ops it can speed up for about 40%.

**Review by houseroad — APPROVED** [review]
This change significantly improves the computation efficiency on indices. The only concern is that FixDivisor only supports 32bits. Then we may have problem if the input blob is larger than 2G. We probably need to confirm that.

**Pull request closed without merging**
