### PR TITLE
Fix div by fp64 scalar issue on xla device

### LINKED ISSUE #4574: Unexpected f64 div
## 🐛 Bug
We observed unexpected f64 div in the backward pass of `nn.MultiheadAttention`.

## To Reproduce
```py
import torch_xla
import torch_xla.core.xla_model as xm
from torch import nn

device = xm.xla_device()
mod = nn.MultiheadAttention(768, 12, batch_first=True)
mod.to(device)

x = torch.rand(24,512,768).to(device)
y,_ = mod(x,x,x,need_weights=False)
y.sum().backward()

print(torch_xla._XLAC._get_xla_tensors_text([y]))
print(torch_xla._XLAC._get_xla_tensors_text([p.grad for p in mod.parameters() if p.requires_grad]))
```
In the forward pass IR:
```llvm
%31 = f32[] xla::device_data(), xla_shape=f32[], device=GPU:0
%35 = f32[24,12,512,64]{3,2,1,0} aten::div(%34, %31), xla_shape=f32[24,12,512,64]{3,2,1,0}
```
In the backward pass IR
```
%73 = f64[] xla::device_data(), xla_shape=f64[], device=GPU:0
%78 = f64[24,12,512,64]{3,2,1,0} aten::div(%77, %73), xla_shape=f64[24,12,512,64]{3,2,1,0}
```

One interesting I noticed is the `aten::div` in the forward pass is through the `at::Scalar& other` signature:
```
at::Tensor XLANativeFunctions::div(const at::Tensor& self,
                                   const at::Scalar& other) {
```
while the `aten::div` in the backward pass is through the `at::Tensor& other` signature:
```
at::Tensor XLANativeFunctions::div(
    const at::Tensor& self, const at::Tensor& other,
    c10::optional<c10::string_view> rounding_mode) {
```
and in both cases `other.scalar_type()` is f64.

## Expected behavior

There should not be f64 div as it's very costly on some GPUs.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: GPU
 - torch_xla version: master

## Additional context

The div is coming from [here](https://github.com/pytorch/pytorch/blob/878f4f09d211f4c24f210999cf64b24506732915/aten/src/ATen/native/transformers/attention.cpp#L775). 

I'm not sure if this is an issue of pytorch or it should be fixed in torch_xla.

### PR DESCRIPTION
**Pull request by ymwangg**
This PR fixes https://github.com/pytorch/xla/issues/4574. I'll create a separate test PR in pytorch/xla repo.

cc @JackCaoG @ezyang

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
The XPASS may be real, please remove them from the xfails list

**Comment by ymwangg** [comment]
All tests have passed except one seems to get stuck somehow.

**Pull request closed without merging**
