### PR TITLE
Rename pyro.distributions.Multinomial -> .Categorical

### LINKED ISSUE #3764: Rename distributions.Multinomial -> .Categorical
`Multinomial` commonly refers to a distribution over counts, and is a multivariate generalization of the `Binomial` distribution. However PyTorch's `Multinomial` implements what is more commonly referred to as a `Discrete` or `Categorical` distribution, a distribution over vectors of indices. I suggest renaming `torch.distributions.Multinomial` to `.Categorical` or `.Discrete` so as to make way for a true `.Multinomial` implementation (e.g. [this one](https://github.com/uber/pyro/blob/dev/pyro/distributions/multinomial.py) from Pyro).

## Why?

This PR follows the naming convention used by:
- Tensorflow: [Categorical](https://www.tensorflow.org/api_docs/python/tf/distributions/Categorical) vs [Multinomial](https://www.tensorflow.org/api_docs/python/tf/distributions/Multinomial)
- PyMC3: [Categorical](http://docs.pymc.io/api/distributions/discrete.html#pymc3.distributions.discrete.Categorical) vs [Multinomial](http://docs.pymc.io/api/distributions/multivariate.html#pymc3.distributions.multivariate.Multinomial)
- Scipy: [multinomial](https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.stats.multinomial.html) operates on counts rather than values

## How these distributions relate to each other
| | Binary | Multi-class |
| -: | - | - |
| values | `Bernoulli` | `Categorical` aka `Discrete` |
| counts | `Binomial` | `Multinomial` |
| conjugate prior | `Beta` | `Dirichlet` |

### PR DESCRIPTION
**Pull request by fritzo**
Fixes #3764

### CODE REVIEW

**Comment by fritzo** [comment]
CC @apaszke @colesbury

**Comment by apaszke** [comment]
I don't really have a strong preference for either name. Minimizing the number of breaking changes is nice, but I guess that categorical really fits the semantics better 😕

BTW if we're changing this, we should definitely backport this to 0.3 (@soumith), so we don't do breaking changes twice!
Additionally, we should deprecate `.multinomial` function in favor of `.categorical`

**Comment by soumith** [comment]
we dont need to backport this to 0.3, but we definitely need to deprecate multinomial, not abruptly remove it.

**Comment by apaszke** [comment]
The point is `torch.distributions.Multinomial` was never part of the standard API in any of our releases, so if we ever want to change it then now is the time. I never said I want to remove `.multinomial()`, but rather deprecate it.

**Comment by soumith** [comment]
after discussing this with Adam, we decided that it's okay to merge and deprecate (and backport to 0.3.0) because we haven't made a major release with torch.distributions yet.

**Pull request merged**
