### PR TITLE
Remove torch._bmm and remove torch.bmm deterministic arg documentation

### LINKED ISSUE #61571: Can't set deterministic=True  in torch.bmm() in Torch 1.9.0 with Cuda 11.1 and A100 GPU
I want to enable deterministic=True  in 

    out = torch.bmm(reshaped_x, self.weight1, deterministic=True)

But got :   **TypeError: bmm() got an unexpected keyword argument 'deterministic'**

## Code example

 _out = torch.bmm(reshaped_x, self.weight1, deterministic=True)_

## System Info

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

root@d93c8a2d8eae:/tmp# python collect_env.py
Collecting environment information...
PyTorch version: 1.9.0a0+git4f50fdc
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.27

Python version: 3.8.8 (default, Feb 24 2021, 21:46:12)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-77-generic-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0a0+git4f50fdc
[pip3] torchelastic==0.2.2
[pip3] torchtext==0.9.0
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] magma-cuda111             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-include               2021.2.0           h06a4308_296
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.3.0            py38h54f3939_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] torch                     1.9.0a0+git4f50fdc          pypi_0    pypi
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchtext                 0.9.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu111    pytorch

### PR DESCRIPTION
**Pull request by kurtamohler**
Fixes #61571

### CODE REVIEW

**Review by albanD — APPROVED** [review]
LGTM
Thanks for fixing this

**Comment by albanD** [comment]
Could you fix the backward compatibility tests by adding an entry in the allowlist in check_backward_compatibility.py please?

**Comment by anjali411** [comment]
@kurtamohler this broke `pytorch_linux_backward_compatibility_check_test`. 
```
Jul 16 17:30:46 The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not. 
Jul 16 17:30:46 
Jul 16 17:30:46 Broken ops: [
Jul 16 17:30:46 	aten::_bmm(Tensor self, Tensor mat2, *, bool deterministic=False) -> (Tensor)
Jul 16 17:30:46 	aten::_bmm.out(Tensor self, Tensor mat2, *, bool deterministic=False, Tensor(a!) out) -> (Tensor(a!))
Jul 16 17:30:46 ]
```
I think adding those ops to the list here: https://github.com/pytorch/pytorch/blob/287603f51cd0303f267f1f978bcab71aa07e3d77/test/backward_compatibility/check_backward_compatibility.py#L28 should fix it

**Comment by kurtamohler** [comment]
@anjali411, thanks for letting me know! I did add these entries to the `allow_list`:
```
    ("aten::_bmm", datetime.date(2021, 7, 14)),
    ("aten::_bmm.out", datetime.date(2021, 7, 14)),
```

However, I didn't realize until now that the date is supposed to be _after_ the date when the diff is merged. I'll fix that

**Comment by kurtamohler** [comment]
@anjali411, should be fixed now

**Comment by albanD** [comment]
I can take care of landing this.

**Pull request closed without merging**
