### PR TITLE
Remove caffe2 contrib and experiments

### PR DESCRIPTION
**Pull request by cyyever**
This PR tries to decompose #122527 into a smaller one. 
To be noted, this was inspired and is co-dev with @r-barnes.
cc @malfet @seemethere @jbschlosser @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @albanD

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM if it passes the CI, but it should be landed as co-dev
cc: @r-barnes @izaitsevfb

**Comment by cyyever** [comment]
@r-barnes It is ready.

**Comment by cyyever** [comment]
@r-barnes You mentioned that META has been not synced with Caffe2, so it may be safe to merge without breaking META builds.

**Pull request closed without merging**
