### PR TITLE
Enable cache action for windows and other minor workflows

### PR DESCRIPTION
**Pull request by huydhn**
Following up on https://github.com/pytorch/pytorch/pull/84026, these are the rest of pip dependencies that I can find.

@diff-train-skip-merge

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Just curios, how the caching would work for our own libraries?

**Comment by huydhn** [comment]
> Just curios, how the caching would work for our own runners?

This uses https://github.com/actions/cache behind the scene. When python is setup `using setup-python` with caching turning on, it would also setup a local cache directory on the runner itself, i.e. our [Windows runner](https://github.com/pytorch/pytorch/runs/8041673465).  For pip, this cache directory is the same as its cache directory https://github.com/pypa/pip/blob/main/docs/html/topics/caching.md, i.e. `~/.cache/pip` for Linux.  As you can see, there is no different in principal between GitHub runners and our self-hosted runners

The cache data itself is stored in GitHub infrastructure per their [doc](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy).

> GitHub will remove any cache entries that have not been accessed in over 7 days. There is no limit on the number of caches you can store, but the total size of all caches in a repository is limited to 10 GB. If you exceed the limit, GitHub will save the new cache but will begin evicting caches until the total size is less than the repository limit.

There is also two other catches from what I see:

* Different tools have different way of caching, so conda won't be the same as pip. Although they might just try to install the same pyyaml package for example
* It makes no difference if pip installation is executed inside a Docker container, which makes sense.  Luckily, our Docker container image already have all it needs

**Pull request closed without merging**
