### PR TITLE
[aoti] fix typo in codegen_dynamic_scalar

### PR DESCRIPTION
**Pull request by henrylhtsang**
Summary: appears to be a typo

Test Plan: ci

Differential Revision: D64867271

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by henrylhtsang** [comment]
@ezyang I think it is a typo. Can you confirm?

**Review by ezyang — APPROVED** [review]
if you have a test that would be great but i won't let that stop me from accepting this

**Comment by henrylhtsang** [comment]
will add a test next pr

**Comment by henrylhtsang** [comment]
here is a repro (you need https://github.com/pytorch/pytorch/pull/138765)

```
class M(torch.nn.Module):
    def forward(self, dilate_flag):
        return dilate_flag.item()

input1 = (torch.tensor([1], dtype=torch.bool, device="cuda"),)
model = M().cuda()

ep = torch.export.export(model, input1, strict=True)
path = torch._inductor.aot_compile(ep.module(), input1)
aot_model = torch._export.aot_load(path, device="cuda")
actual_output = aot_model(*input1)
```

**Pull request closed without merging**
