### PR TITLE
Add current FSDP2 path to old composable FSDP1 warning

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #139759
* #139650

cc @H-Huang @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by weifengpy — APPROVED** [review]

**Review by wz337 — APPROVED** [review]
LG

**Pull request closed without merging**
