### PR TITLE
Added negative alias to neg opinfo

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:
- Added negative alias to neg opinfo

Refactored from https://github.com/pytorch/pytorch/pull/49158

### CODE REVIEW

**Comment by mruberry** [comment]
Hey @vfdev-5! You and @kshitij12345 may want to coordinate these alias PRs. See https://github.com/pytorch/pytorch/pull/51944, which also adds the negative alias. Maybe get together for a few minutes and split the aliases between you?

When we do add an alias in the OpInfo we should also remove the AliasInfo like this PR does, @kshitij12345.

**Comment by kshitij12345** [comment]
@mruberry Thanks for the heads up. I will remove those alias entries from that PR for now.

**Comment by vfdev-5** [comment]
Ops, sorry about that.

**Comment by vfdev-5** [comment]
Seems like it is already done. Close it.

**Pull request closed without merging**
