### PR TITLE
Accept min / max sequence length in nested_tensor_from_jagged() constructor

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #130183
* __->__ #130175

This PR updates the public API for NJT construction `torch.nested.nested_tensor_from_jagged()` to accept values for min / max sequence length. It's useful to provide these ahead of time to avoid GPU -> CPU syncs from on-demand computation later on.

NB: The test changes are extensive because I reworked the existing `_validate_nt()` helper function used throughout our NJT construction tests to verify more (specifically: expected cached min / max seq len and contiguity).

API design question: should we additionally provide an option to compute these from `offsets` at construction time? I can think of three possible cases during construction:
1. Min / max seq len has already been obtained from *somewhere* (manual calculation, static values, etc.) and they should be used in the cache
2. Min / max seq len should be computed immediately at construction time for use in the cache (ideally, the caller wouldn't have to do this computation manually)
3. Min / max seq len are not needed at all (i.e. SDPA isn't ever called) and computation should be skipped

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]
awesome, thanks!

**Comment by davidberard98** [comment]
> API design question: should we additionally provide an option to compute these from offsets at construction time? I can think of three possible cases during construction:

another idea (and I feel like we've discussed this in the past / it's a bit connected to @soulitzer's work on equality) - an option to put the offsets on CPU (or pass in CPU offsets) upon construction; for more complicated use cases (like truncation, which @YuqingJ has been discussing), you might need the full offsets on CPU - and when we look at some jagged tensor usage in torchrec/ads, we often see that they carry around offsets on both CPU and GPU for this reason.

**Comment by jbschlosser** [comment]
> another idea (and I feel like we've discussed this in the past / it's a bit connected to @soulitzer's work on equality) - an option to put the offsets on CPU (or pass in CPU offsets) upon construction; for more complicated use cases (like truncation, which @YuqingJ has been discussing), you might need the full offsets on CPU - and when we look at some jagged tensor usage in torchrec/ads, we often see that they carry around offsets on both CPU and GPU for this reason.

Good points, and yes I'd expect that we'd need @soulitzer's union find implementation to determine equality between cpu offsets and the corresponding GPU offsets without a sync. It's good to have some concrete use cases on the need for offsets on both devices, thanks!

**Review by soulitzer — APPROVED** [review]

**Pull request closed without merging**
