### PR TITLE
Upgrade to tlparse 0.3.7

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #121772

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Comment by ezyang** [comment]
cc @tinglvv

**Review by Skylion007 — APPROVED** [review]

**Comment by snadampal** [comment]
this is the first version with aarch64 linux wheels support. required for the ci tests. thanks @ezyang

**Pull request closed without merging**
