### PR TITLE
[Caffe2] Add hip and miopen options to caffe2 python API

### PR DESCRIPTION
**Pull request by rohithkrn**
The goal of this PR is to add hip and miopen options to python API in parallel to cuda/cudnn.

This is still WIP.
@bddppq Please review if this approach is fine. Changes to other files will be made based on the comments.

/cc @petrex @ashishfarmer

### CODE REVIEW

**Review by bddppq — CHANGES_REQUESTED** [review]
I would prefer not to do the python api change at this point. Let's focus on the C++ runtime and make it stable first before pushing it out to the python interface.
For now if users want to experiment using HIP/ROCM, they can manually change the `device_option` field in their model files.

**Comment by rohithkrn** [comment]
Ok. We can stall it for now. 
@petrex do you have a different opinion?

**Comment by petrex** [comment]
@rohithkrnNo, we follow your lead.

**Comment by bddppq** [comment]
Let's not touch the python api part for now.

**Pull request closed without merging**
