### PR TITLE
remove _to_copy decomp and add a meta impl

### PR DESCRIPTION
**Pull request by anjali411**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #86917
* #86916
* #86915

### CODE REVIEW

**Comment by bdhirsh** [comment]
@ngimel might want to weigh in (wrote the [initial decomp](https://github.com/pytorch/pytorch/pull/84108)).

It looks like we have a decomp cycle, with `aten._to_copy` -> `prims.device_put` -> `aten.to` -> `aten._to_copy`.

Making `_to_copy()` the "prim" seems like a reasonable way to break the cycle, but lmk if you disagree.

**Comment by ngimel** [comment]
You are not supposed to decompose past prims, so the buck stops at `aten._to_copy -> prims.device_put` ? Reference prim implementation uses `to` but who cares. Why do we need to remove `_to_copy` decomp? I was actually planning on switching inductor to using it instead of a home-grown one, and nvfuser might be using it also.

**Comment by anjali411** [comment]
> You are not supposed to decompose past prims, so the buck stops at `aten._to_copy -> prims.device_put` ? Reference prim implementation uses `to` but who cares. Why do we need to remove `_to_copy` decomp? I was actually planning on switching inductor to using it instead of a home-grown one, and nvfuser might be using it also (I originally wrote it for them).

I see, that makes sense. Currently, it does get decomposed while running:
```
TORCH_SHOW_CPP_STACKTRACES=1 TORCHDYNAMO_DYNAMIC_SHAPES=1 AOT_DYNAMIC_SHAPES=1 python benchmarks/huggingface.py --only ElectraForQuestionAnswering --accuracy --backend aot_eager --training
```
for instance (you can repro it by reverting this commit on the symbolic shapes branch). Maybe it's a dynamo issue?

**Comment by ngimel** [comment]
That's weird, @Chillee do you have an idea what's going on here? Perhaps we should add `prims.device_put` lowering in inductor?

**Comment by ngimel** [comment]
@anjali411 can you try the following 1-line diff in dynamo
```
diff --git a/torchinductor/lowering.py b/torchinductor/lowering.py
index 3e2b1123..71ad251d 100644
--- a/torchinductor/lowering.py
+++ b/torchinductor/lowering.py
@@ -322,7 +322,7 @@ def to_dtype(x: TensorBox, dtype: torch.dtype):
 
     return make_pointwise(_to_dtype, override_return_dtype=dtype)(x)
 
-
+@register_lowering(prims.device_put)
 def to_device(x: TensorBox, device: torch.device):
     device = decode_device(device)
     if x.get_device() == device:
```

**Comment by anjali411** [comment]
> @register_lowering(prims.device_put)

Hmm still getting the same inf recursion

**Comment by ezyang** [comment]
Is more help needed on this?

**Comment by Chillee** [comment]
I promised to look at this, looking at it now.

**Comment by Chillee** [comment]
Here's a minimal repro (on the branch after reverting this change).

```
def f(a, b):
    return torch.ops.aten.nll_loss_forward(a, b, None, 1, a.shape[1])

make_fx(f, tracing_mode="symbolic")(torch.randn(1, 10), torch.zeros(1, dtype=torch.long))
```

**Comment by Chillee** [comment]
Ok, this is the problem.

For _to_copy, what's going on is that we're hitting this code for FakeTensor (https://github.com/pytorch/pytorch/blob/symbolic-shapes/torch/_subclasses/fake_tensor.py#L813), which turns off dispatch and calls into FakeTensor's special handling for to.device.

This calls aten.to, which (as a compositeimplicitautograd op) dispatches to _to_copy internally. And since _to_copy is registered as a decomposition (and thus a meta function), we go into the decomposition.

Then, that decomposition calls prims.device_put => since dispatch is disabled, we call the aten impl for device_put (which calls aten.to) => aten._to_copy (since compositeimplicitautograd) => decomposition (since registered to meta)

There are 2 conditions that are required for this bug to get triggered:

1. You can't have already decomposed aten.to by the time we get to faketensor (satisfied by calling aten.to in a decomposition).
2. You can't manually decompose aten.to with our faketensor logic for that: https://github.com/pytorch/pytorch/blob/symbolic-shapes/torch/_subclasses/fake_tensor.py#L778 (satisfied by the fact that there are no symbolic shapes on this tensor since we've summed it into a scalar lol)

**Comment by Chillee** [comment]
And here's a repro that doesn't depend on the branch.

```
from torch._meta_registrations import register_meta

@register_meta(torch.ops.aten.cos.default)
def cos_decomp(a):
    return torch.ops.aten.to.device(a.sum(), device="cuda", dtype=torch.long)

def f(a):
    return a.cos()

make_fx(f, tracing_mode="symbolic")(torch.randn(1, 10))
```

**Comment by wconstab** [comment]
so the tradeoff is simpler code that always uses py decomps vs sometimes using faster c++ but with more complexity/bugs?

**Comment by Chillee** [comment]
@wconstab  in this case, my change simply unified the path of “this is a compositeimplicitautograd op”, so that we always use the C++ dispatcher implementation.

before, FakeTensor could sometimes interject on a compositeimplicitautograd op, which always seems wrong to me?

cc: @ezyang @eellison

**Comment by ezyang** [comment]
@Chillee's proposed action sgtm

**Comment by Chillee** [comment]
Btw, I already landed this PR: https://github.com/pytorch/pytorch/pull/87254

**Comment by Chillee** [comment]
@ezyang Do we still need this PR since my PR is landed? Which I believe fixes the underlying issue.

**Comment by ezyang** [comment]
I guess not? Unless @anjali411 has something else she wants it for.

**Comment by anjali411** [comment]
No I think Horace's fix resolves the issue and we can keep _to_copy as is.

**Pull request closed without merging**
