### PR TITLE
report an error if num_channels is not divisible by num_groups for nn.GroupNorm

### PR DESCRIPTION
**Pull request by XiaobingSuper**
For a GroupNorm module, if num_channels is not divisible by num_groups, we need to report an error when defining a module other than at the running step.

example:
```
import torch
m = torch.nn.GroupNorm(5, 6)
x = torch.randn(1, 6, 4, 4)
y = m(x)
```
before:

```
Traceback (most recent call last):
  File "group_norm_test.py", line 8, in <module>
    y = m(x)
  File "/home/xiaobinz/miniconda3/envs/pytorch_mater/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xiaobinz/miniconda3/envs/pytorch_mater/lib/python3.7/site-packages/torch/nn/modules/normalization.py", line 271, in forward
    input, self.num_groups, self.weight, self.bias, self.eps)
  File "/home/xiaobinz/miniconda3/envs/pytorch_mater/lib/python3.7/site-packages/torch/nn/functional.py", line 2500, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Expected number of channels in input to be divisible by num_groups, but got input of shape [1, 6, 4, 4] and num_groups=5
```

after:

```
Traceback (most recent call last):
  File "group_norm_test.py", line 6, in <module>
    m = torch.nn.GroupNorm(5, 6)
  File "/home/xiaobinz/miniconda3/envs/pytorch_test/lib/python3.7/site-packages/torch/nn/modules/normalization.py", line 251, in __init__
    raise ValueError('num_channels must be divisible by num_groups')
```

This PR also update the doc of num_groups.

### CODE REVIEW

**Review by jbschlosser — APPROVED** [review]
Thanks for the fix! I'm good with this.

Do you mind rebasing on master - that should hopefully fix the failing checks.

**Comment by jbschlosser** [comment]
@XiaobingSuper Looks like the entry for `torch.nn.quantized.GroupNorm` in `test/test_module_init.py` is wrong since it passes (2, 3) for (num_groups, num_channels). I think it should be an easy fix to pass (2, 4) instead.

**Comment by osalpekar** [comment]
Hey @XiaobingSuper, thanks for making this change! It seems like this PR may have broken some tests in the PyTorch Opacus project, however (see tests here: https://github.com/pytorch/opacus/tree/main/opacus/tests). We'd love it if you could help address some of these test failures. Looping in @JohnlNguyen from the Opacus team who could provide some context. 

Going forward, we'd love to find a way to provide this signal to you in advance.

**Comment by JohnlNguyen** [comment]
Hey @XiaobingSuper, Do you mind sending in the fix for Opacus?

The issue is here https://github.com/pytorch/opacus/blob/6a3e9bd99dca314596bc0313bb4241eac7c9a5d0/opacus/validators/batch_norm.py#L88

I think it should be a quick fix.

**Comment by XiaobingSuper** [comment]
> @JohnlNguyen



> Hey @XiaobingSuper, Do you mind sending in the fix for Opacus?
> 
> The issue is here https://github.com/pytorch/opacus/blob/6a3e9bd99dca314596bc0313bb4241eac7c9a5d0/opacus/validators/batch_norm.py#L88
> 
> I think it should be a quick fix.

Yes, there has a fix for Opacus: https://github.com/pytorch/opacus/pull/390/

**Pull request closed without merging**
