### PR TITLE
Set min supported Python version to 3.8

### LINKED ISSUE #80513: Drop Python 3.7 support (following NEP 29)
According to the [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) schedule Python 3.7 should have been dropped on Dec 26, 2021. PyTorch adopted this depreciation policy in #74203, and with PyTorch 1.12 released (which still supports Python 3.7), this seems like a good moment to drop Python 3.7 and make the minimum required Python version 3.8, in preparation of PyTorch 1.13.

### PR DESCRIPTION
**Pull request by malfet**
Also, grep for `if sys.version_info .cond. (3, 8)` and replaces them with appropriate action.

This is a last in a series of PRs that moved CI/CD away from testing PyTorch behavior against Python-3.7. 

Fixes https://github.com/pytorch/pytorch/issues/80513

cc @albanD @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by ZainRizvi — CHANGES_REQUESTED** [review]
And the CI validates that your check is working :) 

https://github.com/pytorch/pytorch/actions/runs/4026325254/jobs/6920691212 fails with:
`You are using Python 3.7.15. Python >=3.8.0 is required.`

**Review by huydhn — APPROVED** [review]

**Comment by huydhn** [comment]
For the context, here is the PR I submitted to XLA https://github.com/pytorch/xla/pull/4489

**Comment by Skylion007** [comment]
@malfet Did you intent to change the LibKineto submodule?

**Comment by malfet** [comment]
@Skylion007 no, it was not intentional. Let me revert and reland without the kineto change

**Comment by malfet** [comment]
@Skylion007 actually, do you mind giving a stamp on https://github.com/pytorch/pytorch/pull/93237

**Pull request closed without merging**
