### PR TITLE
Run inductor benchmark test for every PR

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #90808
* __->__ #90773
* #90762

### CODE REVIEW

**Comment by desertfire** [comment]
@ZainRizvi  @malfet, I have made some revert which fixes recent flakiness in inductor benchmark tests. I propose to make the inductor tests run for every PR now, which will prevent regression and make triaging easier if regression does happen. As I am the pt2 oncall this week, I will closely monitor the status and solve any flakiness issue if they exist.

**Review by huydhn — APPROVED** [review]
LGTM! Inductor tests look more stable now since Monday https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=inductor.  So I think we can merge this and monitor.  Also please keep monitor the queuing time https://hud.pytorch.org/metrics and inductor jobs TTS https://hud.pytorch.org/tts too as they are also important criteria.

**Comment by ZainRizvi** [comment]
This will start blocking all PRs, including PRs that haven't opted into ciflow/inductor.

Two of the last 6 inductor runs failed with flaky errors, I'm hesitant to call that reliable enough to risk being a general block.

Instead of running this as part of trunk, what about setting up this workflow to run after every push to master?

You'll get results from every PR, but it won't block people from merging

Something like:

```
  push:
    branches:
      - master
      - main
 ```

**Review by ZainRizvi — CHANGES_REQUESTED** [review]
This will start blocking all PRs, including PRs that haven't opted into ciflow/inductor.

One of the last 6 inductor runs failed with flaky errors, I'm hesitant to call that reliable enough to risk being a general block.

Instead of running this as part of trunk, what about setting up this workflow to run after every push to master?

You'll get results from every PR, but it won't block people from merging in case things act flaky

Something like:

```
on:
  push:
    branches:
      - master
      - main
    tags:
      - ciflow/inductor/*
 ```

**Comment by desertfire** [comment]
> This will start blocking all PRs, including PRs that haven't opted into ciflow/inductor.
> 
> One of the last 6 inductor runs failed with flaky errors, I'm hesitant to call that reliable enough to risk being a general block.
> 
> Instead of running this as part of trunk, what about setting up this workflow to run after every push to master?
> 
> You'll get results from every PR, but it won't block people from merging in case things act flaky
> 
> Something like:
> 
> ```
> on:
>   push:
>     branches:
>       - master
>       - main
>     tags:
>       - ciflow/inductor/*
> ```

Sounds good to me.

> This will start blocking all PRs, including PRs that haven't opted into ciflow/inductor.
> 
> One of the last 6 inductor runs failed with flaky errors, I'm hesitant to call that reliable enough to risk being a general block.
> 
> Instead of running this as part of trunk, what about setting up this workflow to run after every push to master?
> 
> You'll get results from every PR, but it won't block people from merging in case things act flaky
> 
> Something like:
> 
> ```
> on:
>   push:
>     branches:
>       - master
>       - main
>     tags:
>       - ciflow/inductor/*
> ```

Sounds good. What I really wanted is to collect more signals at this point. Let me make the change.

**Comment by ZainRizvi** [comment]
Thanks for making the change!

**Comment by clee2000** [comment]
### Merge started
Your change will be merged once all checks pass (ETA 0-4 Hours).

Learn more about merging in the [wiki](https://github.com/pytorch/pytorch/wiki/Bot-commands).

Questions? Feedback? Please reach out to the [PyTorch DevX Team](https://github.com/pytorch/pytorch/wiki/Dev-Infra-Office-Hours)<details><summary>Advanced Debugging</summary>
Check the merge workflow status 
<a href="None">here</a>
</details>

**Pull request closed without merging**
