### PR TITLE
[ROCm] Add extra cuda_to_hip_mappings.py

### PR DESCRIPTION
**Pull request by amoskvic**
Adding extra mappings discovered when hipifying the backward CUDA kernel of the Mamba model (https://github.com/state-spaces/mamba/).

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by jeffdaily — APPROVED** [review]
Fix lint, otherwise LGTM.

**Comment by jeffdaily** [comment]
pytorchbot merge didn't close this automatically.  Closing manually.

**Comment by amoskvic** [comment]
@jeffdaily thanks for fixing the trailing whitespace issue!

**Pull request closed without merging**
