### PR TITLE
Add device id to ConvolutionParams

### LINKED ISSUE #50844: Hash key of cudnn conv benchmark cache should include device id
## 🐛 Bug

Currently, the cudnn conv benchmark cache hash key is `ConvolutionParams`, which does not include the device information as part of it.  See: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cudnn/ConvShared.h#L18

As a result, kernels selected on one device will be used on the other device if it has the same shape, causing errors.

## To Reproduce

```python
import torch
import torchvision.models as models

torch.backends.cudnn.benchmark = True

dtype = torch.float
m0 = models.resnet50(pretrained=True).to(device='cuda:0', dtype=dtype)
ipt0 = torch.randn((128, 3, 224, 224), dtype=dtype, device='cuda:0')

m1 = models.resnet50(pretrained=True).to(device='cuda:1', dtype=dtype)
ipt1 = torch.randn((128, 3, 224, 224), dtype=dtype, device='cuda:1')

m0(ipt0).sum().backward()
m1(ipt1).sum().backward()
```

on my machine, `cuda:0` is 3090 and `cuda:1` is 2080ti. And running the above script will create an error

```
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
```

## Expected behavior

Heuristics should rerun, and select different kernels for different devices.

## Environment

```
Collecting environment information...
PyTorch version: 1.8.0a0+5e24d88
Is debug build: True
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: 11.0.1
CMake version: version 3.18.4

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.0.5
/usr/lib/libcudnn_adv_infer.so.8.0.5
/usr/lib/libcudnn_adv_train.so.8.0.5
/usr/lib/libcudnn_cnn_infer.so.8.0.5
/usr/lib/libcudnn_cnn_train.so.8.0.5
/usr/lib/libcudnn_ops_infer.so.8.0.5
/usr/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.8.0a0
[pip3] torchvision==0.8.2
[conda] Could not collect
```

## Additional context

cc @ngimel @csarofeen @ptrblck @xwang233

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fixes https://github.com/pytorch/pytorch/issues/50844

### CODE REVIEW

**Comment by ngimel** [comment]
Can you please rebase?

**Comment by zasdfgbnm** [comment]
@ngimel rebased

**Comment by ngimel** [comment]
Hm, windows error looks real.

**Comment by zasdfgbnm** [comment]
@ngimel After rerun, the error is gone. The failing test was testing a race condition, and it relies on timing, so maybe it was just bad luck at the last run.

**Pull request closed without merging**
