### PR TITLE
Dynamo support for collective broadcast op

### PR DESCRIPTION
**Pull request by zpcore**
Add dynamo path for `torch.distributed.boardcast`.

This PR is a requirement for https://github.com/pytorch/xla/pull/7956.

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Comment by zpcore** [comment]
Add @JackCaoG in the review.

**Comment by JackCaoG** [comment]
@wconstab wondering if you can find anyone in your team can help review this pr?

**Comment by zpcore** [comment]
The failing test job seems didn't get launched.

**Comment by zpcore** [comment]
PyTorch/XLA is still requesting the feature, reopen. cc @bfolie

**Pull request closed without merging**
