### PR TITLE
[PyTorch] Move FP16 dot and GEMV kernels to new file in ATen/native/cpu/

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #139220
* #139208
* #139159
* #139090
* #139084
* #139083
* #139082
* #139081
* #138275
* #138005
* #137918
* #137917
* #137916
* #137915
* __->__ #137914
* #137913
* #137912
* #137911
* #137661

This is in preparation for supporting x86 as well; we need to
be in this directory so that we can get rebuilt with different
CPU_CAPABILITY settings (AVX2/AVX-512). Also incidentally starts
fulfilling request from @malfet to split the ARM64 fast path stuff
into its own file. BFloat16 will be in a later diff.

Differential Revision: [D64265755](https://our.internmc.facebook.com/intern/diff/D64265755/)

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by malfet — APPROVED** [review]
LGTM, but would be good to have a test plan of sorts, i.e. run a benchmark and make sure results are the same

**Comment by swolchok** [comment]
> test plan

there's test coverage for FP16 GEMV (and in fact it caught a bad rebase that I just fixed)

**Review by malfet — COMMENTED** [review]
`ReducedPrecisionFloatGemvFastPathKernel.cpp` feels a bit long, how about `Float16Gemv.cpp`

**Pull request closed without merging**
