### PR TITLE
add BFloat16 support for AdaptiveMaxPool2d on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #61015
* #58297
* #66927
* __->__ #66929

Differential Revision: [D33353199](https://our.internmc.facebook.com/intern/diff/D33353199)

### CODE REVIEW

**Comment by mingfeima** [comment]
update with benchmark data on both avx512 and avx2 CPU:

* avx512 CPU: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz, 20 cores per socket, dual sockets
* avx2 CPU: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz, 12 cores per socket, dual sockets

#### avx512 CPU single core run
```bash
AdaptiveMaxPool2d(contiguous): input_size [1, 2048, 7, 7] ; output_size:  [2, 2] torch.float32 time: 0.448 ms
AdaptiveMaxPool2d(channels_last): input_size [1, 2048, 7, 7] ; output_size:  [2, 2] torch.float32 time: 0.038 ms
AdaptiveMaxPool2d(contiguous): input_size [1, 2048, 7, 7] ; output_size:  [2, 2] torch.bfloat16 time: 0.562 ms
AdaptiveMaxPool2d(channels_last): input_size [1, 2048, 7, 7] ; output_size:  [2, 2] torch.bfloat16 time: 0.037 ms

AdaptiveMaxPool2d(contiguous): input_size [128, 2048, 7, 7] ; output_size:  [2, 2] torch.float32 time: 55.831 ms
AdaptiveMaxPool2d(channels_last): input_size [128, 2048, 7, 7] ; output_size:  [2, 2] torch.float32 time: 6.426 ms
AdaptiveMaxPool2d(contiguous): input_size [128, 2048, 7, 7] ; output_size:  [2, 2] torch.bfloat16 time: 71.147 ms
AdaptiveMaxPool2d(channels_last): input_size [128, 2048, 7, 7] ; output_size:  [2, 2] torch.bfloat16 time: 4.746 ms

AdaptiveMaxPool2d(contiguous): input_size [1, 2048, 7, 7] ; output_size:  [1, 1] torch.float32 time: 0.188 ms
AdaptiveMaxPool2d(channels_last): input_size [1, 2048, 7, 7] ; output_size:  [1, 1] torch.float32 time: 0.029 ms
AdaptiveMaxPool2d(contiguous): input_size [1, 2048, 7, 7] ; output_size:  [1, 1] torch.bfloat16 time: 0.263 ms
AdaptiveMaxPool2d(channels_last): input_size [1, 2048, 7, 7] ; output_size:  [1, 1] torch.bfloat16 time: 0.028 ms

AdaptiveMaxPool2d(contiguous): input_size [128, 2048, 7, 7] ; output_size:  [1, 1] torch.float32 time: 23.605 ms
AdaptiveMaxPool2d(channels_last): input_size [128, 2048, 7, 7] ; output_size:  [1, 1] torch.float32 time: 4.359 ms
AdaptiveMaxPool2d(contiguous): input_size [128, 2048, 7, 7] ; output_size:  [1, 1] torch.bfloat16 time: 32.906 ms
AdaptiveMaxPool2d(channels_last): input_size [128, 2048, 7, 7] ; output_size:  [1, 1] torch.bfloat16 time: 2.996 ms
```

#### avx2 CPU single core run
```bash
AdaptiveMaxPool2d(contiguous): input_size [1, 2048, 7, 7] ; output_size:  [2, 2] torch.float32 time: 0.569 ms
AdaptiveMaxPool2d(channels_last): input_size [1, 2048, 7, 7] ; output_size:  [2, 2] torch.float32 time: 0.060 ms
AdaptiveMaxPool2d(contiguous): input_size [1, 2048, 7, 7] ; output_size:  [2, 2] torch.bfloat16 time: 0.635 ms
AdaptiveMaxPool2d(channels_last): input_size [1, 2048, 7, 7] ; output_size:  [2, 2] torch.bfloat16 time: 0.067 ms

AdaptiveMaxPool2d(contiguous): input_size [128, 2048, 7, 7] ; output_size:  [2, 2] torch.float32 time: 73.171 ms
AdaptiveMaxPool2d(channels_last): input_size [128, 2048, 7, 7] ; output_size:  [2, 2] torch.float32 time: 12.497 ms
AdaptiveMaxPool2d(contiguous): input_size [128, 2048, 7, 7] ; output_size:  [2, 2] torch.bfloat16 time: 80.319 ms
AdaptiveMaxPool2d(channels_last): input_size [128, 2048, 7, 7] ; output_size:  [2, 2] torch.bfloat16 time: 8.298 ms

AdaptiveMaxPool2d(contiguous): input_size [1, 2048, 7, 7] ; output_size:  [1, 1] torch.float32 time: 0.246 ms
AdaptiveMaxPool2d(channels_last): input_size [1, 2048, 7, 7] ; output_size:  [1, 1] torch.float32 time: 0.051 ms
AdaptiveMaxPool2d(contiguous): input_size [1, 2048, 7, 7] ; output_size:  [1, 1] torch.bfloat16 time: 0.278 ms
AdaptiveMaxPool2d(channels_last): input_size [1, 2048, 7, 7] ; output_size:  [1, 1] torch.bfloat16 time: 0.053 ms

AdaptiveMaxPool2d(contiguous): input_size [128, 2048, 7, 7] ; output_size:  [1, 1] torch.float32 time: 31.866 ms
AdaptiveMaxPool2d(channels_last): input_size [128, 2048, 7, 7] ; output_size:  [1, 1] torch.float32 time: 8.666 ms
AdaptiveMaxPool2d(contiguous): input_size [128, 2048, 7, 7] ; output_size:  [1, 1] torch.bfloat16 time: 36.153 ms
AdaptiveMaxPool2d(channels_last): input_size [128, 2048, 7, 7] ; output_size:  [1, 1] torch.bfloat16 time: 5.281 ms

```

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33353199).

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33353199).

**Comment by VitalyFedyunin** [comment]
Please rebase, and lets check if it clears tests.

**Comment by mingfeima** [comment]
The stack is newly rebased!

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33353199).

**Pull request closed without merging**
