### PR TITLE
[JIT] allow reading numeric types and tensor attribute objects from all module

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Currently JIT can only resolve from `torch` and `torch.nn.functional`. This allow JIT to resolve references from other modules. Such as, to allow `@script` functions like:
```python
import torch
import math
import numpy

a = torch.tensor(1.0)

@torch.jit.script
def f(x):
    return math.pi * x

@torch.jit.script
def g(x):
    return numpy.pi * x

print(f(a))
print(g(a))
```

### CODE REVIEW

**Comment by ezyang** [comment]
@zasdfgbnm Thanks for the contribution. Can you add a test for it? Adapting the code you pasted in the PR should do the charm.

**Comment by zasdfgbnm** [comment]
@ezyang I have added the unit tests. One problem found was, for program like:
```python
import torch
import math

a = torch.tensor(1.0, dtype=torch.double)

def f(x):
    return math.pi * x

g = torch.jit.script(f)

print(f(a))
print(g(a))
```
gives
```
tensor(3.1416, dtype=torch.float64)
Traceback (most recent call last):
  File "test_.py", line 12, in <module>
    print(g(a))
  File "/home/gaoxiang/pytorch-dev/pytorchdev/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: 
Expected object of type CPUFloatType but found type CPUDoubleType for argument #2 'other' (checked_cast_tensor at ../aten/src/ATen/Utils.h:42)
```
This is because in `ConstantPythonValue::create`, all floating python values are converted to `at::CPU(at::kFloat).scalarTensor`.

Not sure how to fix this yet, will look deep into that.

**Comment by apaszke** [comment]
I'm not sure if we really want to resolve those members. `math.pi` will probably remain a constant, but I can easily imagine people using module members for mutable state. Accepting such code doesn't seem right, since the member will effectively be accessed only once, which is not equivalent to what the Python code does.

It's a reasonable assumption for our builtin functions, and we make it. It's not a reasonable assumption for arbitrary modules.

**Comment by zasdfgbnm** [comment]
@apaszke How about only whitelisting a few modules, like `math` and `numpy`, `scipy`?

**Comment by apaszke** [comment]
Not sure if having a hardcoded list of constant modules is a good idea. We could do something in the lines of the `__constant__` annotation we use in our scripted modules. Here are two interfaces I can think of
```python
# Tell the JIT that you it should work with the assumption that values from this module never change.
# It's on you if it's actually mutable, and we don't need to account for this. Using this module in any
# scripted context is no longer an error.
torch.jit.assume_const_module(math)

######################################################################

@torch.jit.script(const_modules=[math, scipy])
def fn(...):
    return ...
```

@zdevito wdyt?

**Comment by zdevito** [comment]
Hmm, I guess we can:

1. Have an inline annotation that is basically a escape operator that evaluates the python code an drops the evaluated result in:

@torch.jit.script
def fn(x):
   return x + const(math.pi + 3)
                               ~~~~~~~~  <- evaluated as python during compilation, if you change math.pi it is on you to fix it

2. Wrap modules:
 ```
math = constify(math, ['pi'])
```
This would ensure pi does not change in the module. However, it doesn't check that math isn't re-assigned. So it is not safe anyway. Because of this I don't really like this version.

3. Make some generic, but reasonable, assumptions about what will and won't be constant. For instance, we can assume that a global variable that is a module will not be reassigned, and the fields of modules will not be reassigned. In this world `math.pi` would work, but only because math is a global module, and `math.pi` is a field of that module. Other globals, like raw numbers, would not be considered constants by default. This one seems pretty reasonable, except in the case where you violate the assumption and get a very hard-to-find error.

Aside: we already do a form of (3) for any python function. Anything that resolves to a python function is assumed to be a constant, even though you can trivial break it:

```
def foo(x):
  print "hi"
  return x

@torch.jit.script
def bar(x):
  foo(x)

foo = 3

bar(3) # still prints "hi", the resolution to the function was done at compile time.
``` 

My vote, reluctantly, is for (3)

A global that is a subclass of python module is assumed to not change. Its fields are also assumed to not change and so can become constants. Functions are generally assumed to be constants.

**Comment by zasdfgbnm** [comment]
No longer a problem now

**Pull request closed without merging**
