### PR TITLE
[ROCm] upgrade ROCm CI builds to py3.10

### PR DESCRIPTION
**Pull request by jataylo**
Upgrade ROCm CI builds to py3.10

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang

### CODE REVIEW

**Review by jeffdaily — APPROVED** [review]

**Comment by jataylo** [comment]
I don't believe any of these failures are new and the b2b-gemm tests are passing:
```
2024-08-21T21:58:17.8609540Z Running inductor/test_b2b_gemm 1/1 ... [2024-08-21 21:58:17.860331]
2024-08-21T21:58:17.8610134Z SCRIBE_GRAPHQL_ACCESS_TOKEN is NOT set
2024-08-21T21:58:17.8615244Z Executing ['/opt/conda/envs/py_3.10/bin/python', '-bb', 'inductor/test_b2b_gemm.py', '-m', 'serial', '--shard-id=1', '--num-shards=1', '-v', '-vv', '-rfEX', '-p', 'no:xdist', '--use-pytest', '-x', '--reruns=2', '--import-slow-tests', '--import-disabled-tests'] ... [2024-08-21 21:58:17.860949]
2024-08-21T21:58:21.6348271Z 
2024-08-21T21:58:21.6350603Z inductor/test_b2b_gemm 1/1 was successful, full logs can be found in artifacts with path test/test-reports/inductor.test_b2b_gemm_1.1_56d822e46ac72b2e_.log
2024-08-21T21:58:21.6352427Z Running 0 items in this shard:
```

**Comment by jataylo** [comment]
@malfet could you take a look at this. Should resolve these b2b-gemm issues we pointed out related to py3.8

**Comment by pruthvistony** [comment]
Waiting for this PR https://github.com/pytorch/pytorch/pull/132895 to merge before this PR.

**Comment by malfet** [comment]
@jithunnair-amd just curious if you consider this one to be ready for review

**Comment by jithunnair-amd** [comment]
> @jithunnair-amd just curious if you consider this one to be ready for review

Not yet, resolving conflicts. Also want to see a full CI run to see impact of py3.10 on ROCm test CI jobs.

**Comment by jataylo** [comment]
@jithunnair-amd are we looking to merge this now?

**Comment by jataylo** [comment]
Failures seem unrelated. Opening for review

**Comment by jataylo** [comment]
cc: @malfet

**Review by jithunnair-amd — APPROVED** [review]

**Review by atalman — APPROVED** [review]
lgtm. Please followup on [periodic / linux-focal-rocm6.1-py3.10 / test (distributed, 3, 3, linux.rocm.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/134108#30190335885)

**Comment by jithunnair-amd** [comment]
> lgtm. Please followup on [periodic / linux-focal-rocm6.1-py3.10 / test (distributed, 3, 3, linux.rocm.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/134108#30190335885)

@atalman Yes, we're looking into the timeouts seen in the distributed job. However, it is not an issue related to the python version, so it shouldn't be a blocker for this PR.

**Pull request closed without merging**
