### PR TITLE
[dynamo] constant fold torch.cuda.get_device_properties to avoid graph break

### PR DESCRIPTION
**Pull request by ydwu4**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #118422

Before the PR, we have a graph break for code like this,
```python
    def test_get_device_properties_tensor_device(a):
        x = a.to("cuda")
        prop = torch.cuda.get_device_properties(x.device)
        if prop.major == 8:
            return x + prop.multi_processor_count
        return x + prop.max_threads_per_multi_processor
```
This PR constant folds the torch.cuda.get_device_properties and we'll get a following dynamo graph:
```python
[2024-01-26 13:28:13,253] [0/0] torch._dynamo.output_graph.__graph: [DEBUG]  <eval_with_key>.0 class GraphModule(torch.nn.Module):
[2024-01-26 13:28:13,253] [0/0] torch._dynamo.output_graph.__graph: [DEBUG]     def forward(self, L_a_ : torch.Tensor):
[2024-01-26 13:28:13,253] [0/0] torch._dynamo.output_graph.__graph: [DEBUG]         l_a_ = L_a_
[2024-01-26 13:28:13,253] [0/0] torch._dynamo.output_graph.__graph: [DEBUG]         
[2024-01-26 13:28:13,253] [0/0] torch._dynamo.output_graph.__graph: [DEBUG]         # File: /home/yidi/local/pytorch/test/dynamo/test_functions.py:544 in test_get_device_properties_tensor_device, code: x = a.to("cuda")
[2024-01-26 13:28:13,253] [0/0] torch._dynamo.output_graph.__graph: [DEBUG]         x = l_a_.to('cuda');  l_a_ = None
[2024-01-26 13:28:13,253] [0/0] torch._dynamo.output_graph.__graph: [DEBUG]         
[2024-01-26 13:28:13,253] [0/0] torch._dynamo.output_graph.__graph: [DEBUG]         # File: /home/yidi/local/pytorch/test/dynamo/test_functions.py:547 in test_get_device_properties_tensor_device, code: return x + prop.multi_processor_count
[2024-01-26 13:28:13,253] [0/0] torch._dynamo.output_graph.__graph: [DEBUG]         add = x + 108;  x = None
[2024-01-26 13:28:13,253] [0/0] torch._dynamo.output_graph.__graph: [DEBUG]         return (add,)
[2024-01-26 13:28:13,253] [0/0] torch._dynamo.output_graph.__graph: [DEBUG]         
```

The signature of get_device_properties is:
```python
def get_device_properties(device: _device_t) -> _CudaDeviceProperties:
```
I think it's safe to constant fold get_device_properties():
1. torch.cuda.get_device_properties(tensor.device). In this case, tensor.device.index is guarded in _check_tensor
2. torch.cuda.get_device_properties(device_int_id). We don't expect the GPU properties for a particular index changes during a torch.compile run and it make sense to specialize the properties for a concrete device_int_id.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Comment by zou3519** [comment]
Do we require (for torch.export) that if a user exports a program, they load it onto a machine with the same type of GPU? If not, then we need a guard on the device properties

**Comment by ydwu4** [comment]
> Do we require (for torch.export) that if a user exports a program, they load it onto a machine with the same type of GPU? If not, then we need a guard on the device properties

Yes, that's a good point. We do need to load the exported program into a GPU with possibly different properties. There are two aspects to answer the question:
1. all guards are ignored in export as of today so even if we added a device properties guard, it won't matter for export. @avikchaudhuri @suo 
2. From torch.compile's point of view, it's safe without the guards but need to do the redundant check for every graph break.(probably can be done in C++ to reduce the overhead or have some export-only flag that only guard under export).

I'm open to the c++ device properties guard hidden behind an export-only flag though.

**Comment by ydwu4** [comment]
The other thing that comes into my mind is that we can have multiple device property guards since users could call get_device_properties(0/1/2/3) etc. All these things doesn't need to be in dynamo and probably we should do that in export, dynamo could just record the device indices encoutered/specialized during tracing and later on export uses this information or bake in this information as part of the exported_program.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
