### PR TITLE
Avoid cuda stubs libraries being RPATHed

### PR DESCRIPTION
**Pull request by casparvl**
For targets that require linking to the CUDA drivers, set explicit RPATHs where any CUDA stubs directories have been filtered out, instead of relying on CMAKE to set RPATHs automatically based on the linker search directories.

The fix here should be more targetted than the one proposed in https://github.com/pytorch/pytorch/pull/37737 The downside of a more targetted fix like this is that if more targets are added later that link to CUDA drivers, they should implement the same logic for filtering CUDA stubs directories.

I'm building from sources myself, and with this patch, that works fine (without it, my `libcaffe2_nvrtc.so` gets an `RPATH` set that points to the CUDA stubs direcotries). I cannot check if the issue that triggered the revert of https://github.com/pytorch/pytorch/pull/37737 is solved by my (more targetted) fix, but I think that is something that popped up in CI on the PyTorch side, so we'll see that automatically I suppose?

Fixes #35418

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

### CODE REVIEW

**Comment by casparvl** [comment]
I added a test inspired on the one from https://github.com/pytorch/pytorch/pull/37737 , but less strict. With this patch, CMake still sets RPATH to `libcaffe2_nvrtc.so`, whereas the previous patch did _not_ set an RPATH at all anymore. It's just that we exclude any CUDA `stubs` directories from it. Thus, the test now specifically (and only) checks for the existence of `stubs` directories in the RPATH. If they are there, the test fails.

I also took out the previous condition that made it only check the `RPATH` _after_ the `$ORIGIN` statement. We no longer set `$ORIGIN`, plus, it is irrelevant _where_ a `stubs` library ended up in the `RPATH`: if it's there, your PyTorch installation will not work properly on GPUs. Ergo, the test _should_ fail.

**Comment by casparvl** [comment]
The two failing CI's are probably on `cmake` versions older than 3.20. Before that, `cmake_path` didn't exist yet. Before that, I think `get_filename_component` would be used, but since that is deprecated, I didn't want to introduce that in a new patch...

Is this a blocker for mergin the fix? It will be resolved at some point when the CIs start using newer `cmake` versions...

**Comment by casparvl** [comment]
@rohan-varma @mrshenli Could this PR be reviewed? Is there anything I can do to help the process from my side? The original issue (https://github.com/pytorch/pytorch/issues/35418) still seems to persist, I think it would be good to have a fix...

**Comment by kumpera** [comment]
The changes to the distributed test suite look ok.
Can't say about the Caffe2 one but there's some leftover debug messages on it that should be removed.
If the Caffe2 changes can be split from this PR we can move with the distributed part of this PR.

**Comment by casparvl** [comment]
@kumpera Thanks for your comment, you're right: I erroneously left some (commented) debugging messages in there which should have been removed. I updated the PR to remove these.

I'd prefer not to split off the Caffe2 part: the issue is the same (stubs libraries getting RPATHed to a shared library) and so is the solution (essentially, the loop that strips the stubs libraries from the RPATH that will be used is the same). If you really think that's the only way to get it merged, I can do it, but it feels 'wrong' to fix the issue only in some places of the code and not in others... :)

Do I understand correctly that another dev might be responsible for the `caffe2` part and that he/she needs to look at that to approve it?

**Pull request closed without merging**
