### PR TITLE
Swap to ID guard for optimizer Variable

### PR DESCRIPTION
**Pull request by mlazos**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #123469
* #123406
* #123476
* #123405
* #123498
* #123404
* #123324
* #123323
* #123322
* #123497
* __->__ #123496

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]

**Comment by mlazos** [comment]
Chatted with Sahan, this test was failing before this PR

**Pull request closed without merging**
