### PR TITLE
Fall back to eager mode when viewing with differing bitwidths (#120998)

### LINKED ISSUE #120998: torch.compile fails with .view(dtype)
### 🐛 Describe the bug
``` torch.compile ``` fails when there's a dtype view call from float to int:

Here's a minimal code to reproduce it:
``` Python
import torch
@torch.compile()
def call(data):
	return data.view(torch.uint8) + 1

data = torch.randint(0, 2**4, [4096, 4096], device='cuda', dtype=torch.uint8)
out = call(data) #OK 
out = call(data.view(torch.float16)) #Error 
``` 
``` Python
BackendCompilerFailed: backend='inductor' raised:
LoweringException: NotImplementedError: bitcast torch.float16 to different bitwidth type torch.uint8 is not supported yet.
```

Wrapping the view call inside another function with ```torch.jit.ignore``` doesn't work either. 

Is there by any chance a way to avoid this without converting types back and forth?
Thanks a lot in advance!

### Versions
```
Versions of relevant libraries:
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

Nvidia driver version: 535.129.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY

[pip3] numpy==1.26.4
[pip3] onnxruntime==1.17.1
[pip3] open-clip-torch==2.24.0
[pip3] pytorch-triton==2.2.0+e28a256d71
[pip3] torch==2.1.2
[pip3] torchaudio==2.2.0.dev20231221+cu121
[pip3] torchvision==0.16.2
[pip3] triton==2.1.0
[conda] Could not collect
```

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire

### PR DESCRIPTION
**Pull request by tfiala**
The inductor lowering code for viewing a tensor as a type with a different bitwidth currently doesn't generate valid triton code. This change looks for a source and destination dtype and, if different sizes, falls back to the eager mode aten implementation.  Prior to this change, this condition would throw an exception.

Fixes #120998.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by tfiala** [comment]
I'll be adding appropriate testing. This is my first draft pull request and I just want to see what runs.

**Review by peterbell10 — COMMENTED** [review]
Looks good, just needs a test in `test/inductor/test_torchinductor.py` to confirm this is working.

**Comment by tfiala** [comment]
I am seeing some dynamic shape tests fail. I don't think they're related. I'll sync up to top of tree and see if this changes things.

**Comment by tfiala** [comment]
Looks like I need to lint the formatting.  And figure out what the dynamic shapes piece is. This is directly related to this diff. Scanning through the errors as they were occurring earlier, I did not catch that the DynamicShapesCodegen piece was some kind of mode of running the code.

**Comment by tfiala** [comment]
Fixed the lint formatter bug.

I am not sure what the DynamicShapesCodegen{GPU,CPU}Tests represent or how to run them locally.  This sounds like some kind of test variant?  Being totally new to PyTorch, I don't have any idea how to run those or why they might be failing, or even if they make sense to run.

**Comment by tfiala** [comment]
This looks like it is simply that the test shouldn't be run with dynamic shapes -- it doesn't use any for loops with dynamic variables in them.  I will look to mark this as a non-dynamic-shape test as soon as I find how to do that.

**Review by peterbell10 — APPROVED** [review]

**Review by bertmaher — APPROVED** [review]

**Comment by tfiala** [comment]
It looks like one or more tensor_board tests are failing.  These don't look related to the change if I'm looking at it right.

**Pull request closed without merging**
