### PR TITLE
Changes incorrect "overlappingIndices" call to correct "maybeOverlappingIndices"

### PR DESCRIPTION
**Pull request by mruberry**
THE PROBLEM

The current overlappingIndices() is meant to detect if a tensor defines multiple valid indices for the same data element. There are two significant issues with this function:

(1) The algorithm it attempts to implement cannot do this.

(2) That algorithm is not implemented correctly.

This call is used by pointwiseApply() and scatter(). If a tensor is readable/writable and detected as overlapped these algorithms will create a non-overlapped copy of it to work on. When tensors are improperly identified as overlapped this causese extra work. If tensors are improperly identified as non-overlapped then this would cause the operations to exhibit unexpected behavior.

For example,

ref = torch.arange(0, 32 * 5).view(4, 8, 5).cuda().double()
p = ref[:,:,::2]
p += 1

Results in a call to pointwiseApply1, which detects p as an overlapped tensor (it is not), causing a call to pointwiseApply2 that copies it into a non-overlapped temporary, and then another call to pointwiseApply2 later that copies it back to the original tensor. If, however, the original tensor is given dimensions of (4, 8, 4), instead, it is correctly detected as non-overlapped and only a single pointwiseApply1 call is made. (This is due to an "off-by-one" error in overlappingIndices().) 

DISCUSSION + FIX

The algorithm that overlappingIndices() attempts to implement tests for a sufficient but not necessary condition of a tensor to be non-overlapping. That is, if its algorithm were implemented properly then it would be a conservative check that would ensure all overlapped tensors were copied (as desired), but also that some non-overlapped tensors were copied too.

The algorithm can be thought of as trying to test whether the dimensions can be ordered like "nesting dolls," with each dimension fitting within the next one larger than it. If this is true then the tensor is non-overlapping, but if it's false the tensor may or may not be overlapped. For example, a tensor with dims (2, 3) and strides (4, 3) cannot be "nested," but is non-overlapping. (The tensor looks like [[0, 3, 6], [4, 7, 10]].)

The algorithm is currently implemented improperly, as can be seen in the example above. The tensor p has dimensions [4, 8, 3] and strides [40, 5, 2]. This confuses the current implementation, which thinks the innermost dimension needs a stride of 6, which is incorrect. The first row is [0, 2, 4] and the next row begins with 5. The current implementation also improperly implemented its sorting behavior. (qsort comparators require -1, 0, and 1, not true/false return values.)

Fixing the existing algorithm is straightforward (and what this PR does, see below), but it is important to note that the algorithm never performed as intended, so its name and the documentation around it has been updated, too. A natural question is if it's possible to write an efficient overlappingIndices(), and I believe the answer is "no." Disambiguating overlapping from non-overlapping tensors is equivalent to finding a nonzero solution to a linear Diophantine equation with restricted coefficients, that is, an equation of the form x_0s_0 + x_1s_1 ... = 0 where s_X is the stride in dimension X and x_X is an integer from [-size_X + 1, size_X - 1].

Another note is that the CPU does not perform this check. For example, if we run:

a = torch.FloatTensor([[0,1], [10, 11]])
b = torch.FloatTensor([[0,0],[0,0]])
b = b.set_(a.storage(), storage_offset=0, size=a.size(), stride=(1,1))
b += 1

Then b is [[1, 3], [3, 11]] because the operation is applied twice to the second element of the original tensor. This causes no warning.

Since the CPU does not perform a similar check, another question is whether the GPU code should remove its check. While it may seem that writing to overlapping tensors is an error state, running test_cuda.py reveals 171 instances of possibly overlapped tensors being copied by pointwiseApply(). (The prior incorrect version has 176 copies.) Allowing writing to overlapped tensors on the GPU may violate assumptions about memory accesses, too. In fairness, these assumptions may be violated on the CPU already.

Leaving the CPU vs GPU behavior question for the future, this fix corrects the current intended GPU behavior. This means that there will be fewer unnecessary copies and no chance of an overlapped tensor sneaking through on the GPU. The CPU behavior remains unchanged. The fix also adds a test to test_cuda.py to ensure that overlapped tensors on the GPU are written to as expected.

Automated testing: test_cuda.py (OK), run_test.py (no regression from PyTorch/Master)

### CODE REVIEW

**Comment by mruberry** [comment]
The failure on Trusty is:

17:55:11 ======================================================================
17:55:11 ERROR: test_all_any_with_dim (test_torch.TestTorch)
17:55:11 ----------------------------------------------------------------------
17:55:11 Traceback (most recent call last):
17:55:11   File "/var/lib/jenkins/workspace/test/test_torch.py", line 794, in test_all_any_with_dim
17:55:11     [1, 1, 1]]))
17:55:11   File "/var/lib/jenkins/workspace/test/test_torch.py", line 784, in test
17:55:11     self.assertTrue((r1 == r2).all())
17:55:11 RuntimeError: Expected object of type torch.LongTensor but found type torch.ByteTensor for argument #2 'other'
17:55:11 
17:55:11 ----------------------------------------------------------------------
17:55:11 Ran 310 tests in 29.465s
17:55:11 
17:55:11 FAILED (errors=1, skipped=21)

which appears to be unrelated.

**Comment by soumith** [comment]
@mruberry i've fixed the failure, it's not your fault. master was briefly broken: https://ezyang.github.io/pytorch-ci-hud/build/pytorch-master

**Comment by ezyang** [comment]
This is very nice work, thank you!

**Review by ezyang — APPROVED** [review]

**Pull request merged**
