### PR TITLE
[torchgen][RFC] Override tensor namespace and container namespace

### PR DESCRIPTION
**Pull request by larryliu0820**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #89081

This PR adds support to let torchgen user to override tensor namespace from `at` to something else. Same for `c10` namespace.

Differential Revision: [D41293359](https://our.internmc.facebook.com/intern/diff/D41293359/)

### CODE REVIEW

**Comment by larryliu0820** [comment]
@larryliu0820 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41293359).

**Comment by ezyang** [comment]
I don't really like it. It makes the code quite a bit more complicated, when it seems to me like you can just define the namespaces appropriately at the use site to line up the namespaces to what you want. Can you tell me more about the motivation? If you, e.g., would prefer us to consistently say at:: or c10::, this probably can be arranged

**Comment by larryliu0820** [comment]
> I don't really like it. It makes the code quite a bit more complicated, when it seems to me like you can just define the namespaces appropriately at the use site to line up the namespaces to what you want. Can you tell me more about the motivation? If you, e.g., would prefer us to consistently say at:: or c10::, this probably can be arranged

```cpp
namespace at = custom_at;
namespace c10 = custom_c10;
```

That's what we are doing right now. But don't you agree it's a hack? Another problem I'm seeing here is that the namespace aliasing thing can't really be apply globally, otherwise a lot of places will have undefined symbols, because `at` is so widely used. That leads to a problem we will have to redefine the namespace within each use case's scope, like:

```cpp
namespace user1 {

namespace at = custom_at;
namespace c10 = custom_c10;

} // namespace user1

namespace user2 {

namespace at = custom_at;
namespace c10 = custom_c10;

} // namespace user2
```

Which is quite unacceptable, since it's mixing up infra and product code. Check [kernel_types.h](https://fburl.com/code/cn4n1r4g).

IMO this is a valid use case for `torchgen` to support.

**Comment by ezyang** [comment]
> That's what we are doing right now. But don't you agree it's a hack?

Hack or not, it's a lot less lines of code than this PR. But no, I don't really agree that it's a hack. You could say that the codegen has some C++ API requirement, which includes defining appropriate entities in appropriate namespaces. If you want to target a different C++ API, that's a different torchgen.api module.

> Another problem I'm seeing here is that the namespace aliasing thing can't really be applied globally, otherwise a lot of places will have undefined symbols, because at is so widely used.

I don't understand this problem. If custom_at doesn't actually define a symbol, then it should complain "hey, blah is not defined". Undefined symbol suggests... some sort of forward declaration shenanigans? Is that your real problem?

**Comment by larryliu0820** [comment]
> You could say that the codegen has some C++ API requirement, which includes defining appropriate entities in appropriate namespaces. If you want to target a different C++ API, that's a different torchgen.api module.

I think this is a good way to summarize the problem, yes we want `torchgen` to satisfy some special C++ API requirement, where `at::Tensor` can actually be `custom::Tensor`. Can you teach me how does a different torchgen.api module work? From my understanding, torchgen.api.types are widely used everywhere in `torchgen`, if we have a separate module, how do we swap out torchgen.api.types?

> I don't understand this problem. If custom_at doesn't actually define a symbol, then it should complain "hey, blah is not defined". Undefined symbol suggests... some sort of forward declaration shenanigans? Is that your real problem?

Hmm I can't repro that issue anymore. Though I still think if we want to use `torchgen` in this use case, I would expect it to generate the exact code I need, not something else, to reduce some level of confusion. So if you have a better approach to let `torchgen` generate `custom::Tensor` code, I'm happy to follow your suggestion.

**Comment by ezyang** [comment]
> I think this is a good way to summarize the problem, yes we want torchgen to satisfy some special C++ API requirement, where at::Tensor can actually be custom::Tensor. Can you teach me how does a different torchgen.api module work? From my understanding, torchgen.api.types are widely used everywhere in torchgen, if we have a separate module, how do we swap out torchgen.api.types?

To talk about this, we need a clear picture of what you want to codegen, and what you don't need. After all, it doesn't matter if api.types is used in places that are irrelevant to executorch.

> ok so the issue is where we have a python binding that takes in a at::Tensor and converts it to custom::Tensor and send it to custom runtime. Now the binding needs to depend on at::Tensor as well as custom::Tensor but if we do global namespace aliasing it blows up.

So essentially, you are mixing both at:: and custom:: in the same program? Well yes, aliasing is a bad idea in that case.

**Comment by larryliu0820** [comment]
> To talk about this, we need a clear picture of what you want to codegen, and what you don't need. After all, it doesn't matter if api.types is used in places that are irrelevant to executorch.

Right, I think the codegen should be able to generate `executorch::Tensor`. We should also be able to generate other types with `custom` namespace, like `at::ArrayRef` or `c10::optional`, we should generate Executorch counter parts of them. 

> So essentially, you are mixing both at:: and custom:: in the same program? Well yes, aliasing is a bad idea in that case.

In some use cases yes, but we don't have to **codegen** both, we just need to codegen `executorch::Tensor` and that shouldn't blocking us from writing `at::Tensor` at C++ source level (which is the case for aliasing).

**Comment by larryliu0820** [comment]
Talked offline, we agreed that we need a different approach to fork types and signature to support tensor in a different namespace. Closing.

**Pull request closed without merging**
