### PR TITLE
ROCm: Use correct device type when exporting tensors to DLPack

### PR DESCRIPTION
**Pull request by t-vi**
Before this PR, DLPack export was tricked by the CUDA masquerading of the HIP backend into thinking that it was exporting a CUDA tensor. We change that to use the ROCM device type instead.

### CODE REVIEW

**Comment by t-vi** [comment]
I found the tests, but there will be things to do yet.

**Comment by t-vi** [comment]
@ezyang Might I interest you in this.
The gist is the `DLConvertor.cpp`, but I wanted a test on ROCm so bad that I enabled this.
Full disclosure: The ROCm tests don't fully work yet because gtest will not use tests from .hip, but I would fix this in a next PR (this one is crowded already).

The DLPack is very dear to me.

**Comment by xw285cornell** [comment]
cc. @jeffdaily

**Comment by ezyang** [comment]
I'm doubtful this actually works. `__HIP_PLATFORM_HCC__` should only be defined when you compile with hcc; with a cpp file it shouldn't be compiled there.

**Comment by ezyang** [comment]
(Concept of the PR is fine and worth doing)

**Comment by t-vi** [comment]
@ezyang curiously, it does seem to work (I tried with exporting tensors and reading them in TVM, which is my immediate usecase).
What is the right define? AT_ROCM_ENABLED()? AT_CUDA_IS_REALLY_ROCM?

**Comment by jeffdaily** [comment]
Does this reference help?
https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_porting_guide.md#compiler-defines-summary

**Comment by t-vi** [comment]
@jeffdaily  Yes and no. We need to tell whether we are in the "CUDA is really HIP" case regardless of whether the code is compiled with the device-enabled compiler (in which case `__HIP_PLATFORM_HCC__` would be good for detection) or a host-only compiler (which, as @ezyang remarked, is a perhaps more natural choice, even if it appears that `__HIP_PLATFORM_HCC__` worked for my particular build).
So we're back to where detecting something about the PyTorch configuration, and it would seem `AT_ROCM_ENABLED()` is a the most plausible choice even if it speaks less than something directly indicating that it's the mimicry in the name (and we have to watch out if we ever enable parallel compiles).

**Comment by t-vi** [comment]
So USE_ROCM was better.  @ezyang: Would that work?

I don't think the CI failure is from me.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
