### PR TITLE
[BE]: Add PYI files to ruff lintrunner

### PR DESCRIPTION
**Pull request by Skylion007**
Due to a bug with the lintrunner yaml, PYI files were not convered. This PR builds off #107519 covers all PYI files and adds one noqa to fix a B006 bugprone error.

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Comment by ezyang** [comment]
If you want to stack like this use ghstack. I'll review after the dep merges and you rebase past it

**Comment by Skylion007** [comment]
> If you want to stack like this use ghstack. I'll review after the dep merges and you rebase past it

Yeah, I need to figure how to get this setup.

**Comment by Skylion007** [comment]
@ezyang Deps are merged and PR is rebased.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
