### PR TITLE
Upgrade submodule oneDNN to v3.5

### PR DESCRIPTION
**Pull request by Xia-Weiwen**
Upgrade submodule oneDNN to v3.5.

**New features and bug fixes**
(to be filled)

**Validation results on CPU**
(to be filled)

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @snadampal

### CODE REVIEW

**Comment by Guobing-Chen** [comment]
@milpuz01, could you take a look at the UT failures on AARCH64, we don't have this platform in hand.

**Comment by Guobing-Chen** [comment]
@snadampal, @vpirogov, could you also help take a look at this AARCH64 CI failures?

**Comment by milpuz01** [comment]
@snadampal @Guobing-Chen we have reproduced the error and do not expect that change in oneDNN will be required. The failure is due to one path in the test implementing bias as post-op sum in oneDNN matmul primitive where on AArch64 this post-op is implemented as in-place summation during matrix multiplication, while the other path is doing oneDNN matmul first and the adding bias to the output resulting in floating point rounding error. This either can be fixed by providing tolerance to be within floating point epsilon or the other path (if possible) also doing bias as post-op sum. We are working to find out what would be the best approach before raising PR and as soon as we have PR we will link it against this issue.

**Comment by Guobing-Chen** [comment]
> @snadampal @Guobing-Chen we have reproduced the error and do not expect that change in oneDNN will be required. The failure is due to one path in the test implementing bias as post-op sum in oneDNN matmul primitive where on AArch64 this post-op is implemented as in-place summation during matrix multiplication, while the other path is doing oneDNN matmul first and the adding bias to the output resulting in floating point rounding error. This either can be fixed by providing tolerance to be within floating point epsilon or the other path (if possible) also doing bias as post-op sum. We are working to find out what would be the best approach before raising PR and as soon as we have PR we will link it against this issue.

Thanks for the analysis and potential solution, @milpuz01, then we will wait for your PR to unblock this.

**Comment by robert-hardwick** [comment]
I've created PR #130618 which should unblock the AArch64 CI failures. 

The problem, as @milpuz01 mentioned, is due to the a difference in the order of the summation in the oneDNN primitives causing a floating point rounding difference. The PR swaps torch.allclose for utility method with a lower tolerance.

**Pull request closed without merging**
