### PR TITLE
Remove hotpatches that circumvent MAGMA bug

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:
- The magma implementation of small singular square batch matrices had a bug that resulted in nan values in the LU factorization result. This has been fixed in MAGMA 2.5.2. This PR removes the existing patch that was a temporary workaround for this bug.

Test Plan:
- Existing tests for det and lu should pass

### CODE REVIEW

**Comment by vishwakftw** [comment]
cc: @seemethere @soumith 

This PR requires that the CI images have the updated MAGMA binaries as well.

**Review by yf225 — APPROVED** [review]
Thanks a lot for the fix! @seemethere Wondering do you mind checking if our CI has MAGMA >= 2.5.2? Thanks!

**Comment by seemethere** [comment]
CI should now be updated with the latest version of magma

**Comment by vishwakftw** [comment]
@seemethere thank you for confirming!

**Review by seemethere — APPROVED** [review]

**Comment by ezyang** [comment]
We're still running CUDA 9 on master with the old version on MAGMA, which means this breaks master. You'll need to do something about that first before we can land this.

**Comment by vishwakftw** [comment]
@seemethere I believe we don't have MAGMA binaries for CUDA 9 on Anaconda either.

**Pull request closed without merging**
