### PR TITLE
[caffe2] Enable int8 inference for MKLDNN

### PR DESCRIPTION
**Pull request by gujinghui**
1. depends on #11853 to fix build issues
2. pre-convert filters in optimize_ideep
3. support group filter in fusion
4. support int8 inference
5. upgrade mkldnn to support int8 inference

### CODE REVIEW

**Comment by gujinghui** [comment]
@jgong5

**Comment by jspisak** [comment]
cc @Maratyszcza - have we benchmarked this against QNNPACK?

**Comment by Maratyszcza** [comment]
@jspisak QNNPACK is for mobile. FBGEMM/DNNLOWP is the proper baseline for INT8 on server-side

**Comment by jspark1105** [comment]
@gujinghui and @jgong5, what the images/sec throughput of resnet50 if you run a single batch using a single core?

**Comment by jspisak** [comment]
Thanks @Marat..

**Comment by ezyang** [comment]
Hi, any update on this PR? It has merge conflicts now.

**Comment by gujinghui** [comment]
@ezyang 
Will rebase and update soon.

**Comment by gujinghui** [comment]
INT8 inference for mkl-dnn. Depends on #9488  #9767  #12164  #12170 
Will be rebased after above PR merged.

**Pull request closed without merging**
