### PR TITLE
Add C++ nn::functional pad

### PR DESCRIPTION
**Pull request by yf225**
This PR adds `torch::nn::functional::pad` to C++ API (which mirrors the Python version), and clean up a few places in `torch::nn`.

After this, we will be able to implement the padding and conv modules.

### CODE REVIEW

**Comment by yf225** [comment]
@ShahriarSS Would you like to review this PR?

**Comment by ShahriarSS** [comment]
@yf225 There are some major problems here. Let me address those and then I can review the PR in detail. 
1. I think that we should have test cases to check the validity of ```TORCH_CHECK```s.
2. I think that we shouldn't use string for the mode in options. We should use enum classes.
3. I've had problems with using ```IntArrayRef``` as class members. Can we replace it with something else?

**Comment by yf225** [comment]
@ShahriarSS Thanks a lot for the comments! I will address them in https://github.com/pytorch/pytorch/pull/26601.

**Comment by yf225** [comment]
Closed in favor of #26601.

**Pull request closed without merging**
