### PR TITLE
Turn on anomaly detection for AOTAutograd backward tracing

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #101047

Previously, anomaly detection was only enabled on the inner forward function, and not on the overall joint function that calls backward. I believe this impeded us from printing "this is the forward that triggered the backward" because that printing only happens if anomaly mode is enabled when you run backward(). This PR fixes it.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Ho yes anomaly mode was only enabled to track metadata into the graph, not for the error message.

I would expect that, to get this nice error message, the end user would enable anomaly mode themselves around the call to compile?

**Comment by ezyang** [comment]
> I would expect that, to get this nice error message, the end user would enable anomaly mode themselves around the call to compile?

Why would we not always track this info when running AOTAutograd? We only run the anomaly enabled autograd once (when compiling) and don't run it that way otherwise.

**Review by albanD — APPROVED** [review]
If you think that it's not too expensive, sure!

**Review by bdhirsh — APPROVED** [review]

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45738652).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45738652).

**Comment by davidberard98** [comment]
I re-ghimported in case that fixes anything

**Comment by albanD** [comment]
Are there internal changes for this? If not, we should just unlink the Diff to be able to land this PR.

**Comment by davidberard98** [comment]
@albanD yeah, no internal changes - I unlinked it

**Pull request closed without merging**
