### PR TITLE
[Quant][docs] Move parts of BackendConfig tutorial

### PR DESCRIPTION
**Pull request by andrewor14**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #91999

Summary: This commit moves the API specification section of
the BackendConfig tutorial to the docstrings, which is a more
suitable place for this content. This change also reduces some
duplication. There is no new content added in this change.

Reviewers: jerryzh168, vkuzo

Subscribers: jerryzh168, vkuzo

### CODE REVIEW

**Comment by andrewor14** [comment]
Please also review: https://github.com/pytorch/tutorials/pull/2169

**Review by vkuzo — APPROVED** [review]

**Review by jerryzh168 — APPROVED** [review]
thanks!

**Comment by jerryzh168** [comment]
I think we can move `Data Type Restrictions` section from tutorial to the docstring of `DTypeWithConstraints` as well

**Pull request closed without merging**
