### PR TITLE
[dynamo] Remove some files from `dynamo_expected_failures`

### PR DESCRIPTION
**Pull request by StrongerXi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #138935

Some tests in `test/dynamo` are marked as "expected failure when testing
with `PYTORCH_TEST_WITH_DYNAMO=1`, i.e., we added files of those test
names in the `dynamo_expected_failures` folder.

However, a lot of those dynamo tests seem to be passing with
`PYTORCH_TEST_WITH_DYNAMO=1`, so this patch removes them from
`dynamo_expected_failures`.

### CODE REVIEW

**Comment by StrongerXi** [comment]
Checking what CI says.

**Comment by StrongerXi** [comment]
All green, I'll try removing more.

**Review by anijain2305 — APPROVED** [review]

**Comment by StrongerXi** [comment]
@torchbot merge

**Comment by StrongerXi** [comment]
> All green, I'll try removing more.

Will send a separate PR for this investigation.

**Pull request closed without merging**
