### PR TITLE
Fix test_create_store_multi flaky test

### LINKED ISSUE #66641: DISABLED test_create_store_multi (__main__.DistributedUtilTest)
This job is non-deterministically failing on master. 

Failures in the last 30 days: https://fburl.com/scuba/opensource_ci_jobs/s5voanjn.

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#66953 Fix test_create_store_multi flaky test**

Fixes #66641, #66319

The issue is a race condition where free port is determined by `get_free_port`, but before that port is actually used by the server store it could have been used by another process leading to a `port already in use` error. The fix is to switch the order of the server store creation and have the server store specify port 0 (choose an unallocated port during its creation), then have the worker processes use the port that was allocated to the server store by accessing `store.port`.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

Differential Revision: [D31802767](https://our.internmc.facebook.com/intern/diff/D31802767)

### CODE REVIEW

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31802767).

**Review by mrshenli — COMMENTED** [review]
This LGTM, but please check with @kiukchung regarding the API change. 

BTW, since we plan to move elastic out of the distributed package, any guidelines for handling future elastic flaky tests?

**Comment by kiukchung** [comment]
> This LGTM, but please check with @kiukchung regarding the API change.
> 
> BTW, since we plan to move elastic out of the distributed package, any guidelines for handling future elastic flaky tests?

@mrshenli while r2p will own elastic going forward, i think we won’t be able to pull elastic out of the distributed package any time soon. We’ve already changed contbuild configs internally to change the oncall for caffe2/torch/distributed/elastic. We probably need to create a triage tag for r2p and make everything in distributed/elastic be triaged to us in oss as well

**Review by kiukchung — APPROVED** [review]
awesome thanks so much for working on the fix!

**Pull request closed without merging**
