### PR TITLE
Speed up cpp extensions re-compilation

### LINKED ISSUE #68066: Caching for cpp_extension load_inline seems not working
Original post: https://discuss.pytorch.org/t/cpp-extension-load-inline-uses-nvrtc-or-spins-processes-caches-output/136154

I got the following lines witnessing compilation at every run of the program (at import of roipool_contextlocnet.py):
```
Using /home/kantorov/.cache/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/kantorov/.cache/torch_extensions/roipooling_contextlocnet/build.ninja...
Building extension module roipooling_contextlocnet...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=roipooling_contextlocnet -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/include -isystem /home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/include/TH -isystem /home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/vadim/prefix/miniconda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/kantorov/.cache/torch_extensions/roipooling_contextlocnet/main.cpp -o main.o

[2/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=roipooling_contextlocnet -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/include -isystem /home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/include/TH -isystem /home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/vadim/prefix/miniconda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/kantorov/.cache/torch_extensions/roipooling_contextlocnet/cuda.cu -o cuda.cuda.o
/home/kantorov/.cache/torch_extensions/roipooling_contextlocnet/cuda.cu(82): warning: variable "is_empty" was declared but never referenced

[3/3] c++ main.o cuda.cuda.o -shared -L/home/vadim/prefix/miniconda/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart -o roipooling_contextlocnet.so
Loading extension module roipooling_contextlocnet...
```

[roipool_contextlocnet.py.txt](https://github.com/pytorch/pytorch/files/7506717/roipool_contextlocnet.py.txt)

Also, can we do something to avoid specifying cpp_sources for this trivial case? And also, can it use only nvrtc for this trivial case? I think it should be much faster, no? (and avoid creating files on file system, avoid touching gcc compiler binaries etc)

@goldsborough 

cc @malfet @zou3519

### PR DESCRIPTION
**Pull request by albanD**
Fixes https://github.com/pytorch/pytorch/issues/68066 to a large extend.

This is achieved by not touching files that don't need changing to make sure the ninja caching works as expected.

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Does this require having `ninja` installed on the machine? This might not be fulfilled...

**Comment by albanD** [comment]
cpp_extensions do AFAIK yes.
That is a pretty simple `pip install` away though so I don't expect it to be a problem.

**Review by fmassa — APPROVED** [review]
LGTM, thanks!

**Pull request closed without merging**
