### PR TITLE
Fix exception causes all over the codebase

### PR DESCRIPTION
**Pull request by cool-RR**
This is the continuation to #90134 and hopefully the final PR in this series.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by cool-RR** [comment]
@kit1980

**Review by kit1980 — APPROVED** [review]

**Comment by malfet** [comment]
A bit curious: what benefit does it have above implicit exception chaining?

**Comment by kit1980** [comment]
> A bit curious: what benefit does it have over implicit exception chaining? (I.e. it looks like a more verbose variant of what is already available, isn't it?)

The traceback will be a bit better: 
https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with

**Comment by malfet** [comment]
> > A bit curious: what benefit does it have over implicit exception chaining? (I.e. it looks like a more verbose variant of what is already available, isn't it?)
> 
> The traceback will be a bit better: https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with

It's a bit subjective, imo single backtrace is better for debugging (though in `pdb` it will work regardless)

**Comment by kit1980** [comment]
> It's a bit subjective, imo single backtrace is better for debugging (though in `pdb` it will work regardless)

I agree about subjective. I don't have a strong preference. Some people did care enough to create and pass https://peps.python.org/pep-3134/
We can revert the changes if you think it's not a good idea.

**Comment by cool-RR** [comment]
> imo single backtrace is better for debugging

You'll get a double traceback regardless of this PR. This just changes the message between the two tracebacks.

**Comment by malfet** [comment]
> I agree about subjective. I don't have a strong preference. Some people did care enough to create and pass https://peps.python.org/pep-3134/ We can revert the changes if you think it's not a good idea.

My point is that if we want to stick to that policy, it would probably be wise to tweak linters to trigger an error if somebody adds `raise` without `from`

**Comment by kit1980** [comment]
> My point is that if we want to stick to that policy, it would probably be wise to tweak linters to trigger an error if somebody adds `raise` without `from`

Only when `raise` inside `except`. I'll look if there is a linter for that already somewhere.

**Comment by cool-RR** [comment]
Not only does it exist, I wrote it :)

https://pylint.pycqa.org/en/latest/user_guide/messages/warning/raise-missing-from.html

You'll need to use PyLint. The warning code is W0707, so you could either filter only for these, or use some of PyLint's other filters too.

**Comment by kit1980** [comment]
> Not only does it exist, I wrote it :)
> 
> https://pylint.pycqa.org/en/latest/user_guide/messages/warning/raise-missing-from.html
> 
> You'll need to use PyLint. The warning code is W0707, so you could either filter only for these, or use some of PyLint's other filters too.

That's great! We don't use PyLint in CI currently because there is too much noise. But I run it locally for specific things form time to time. Maybe we can add PyLint with very limited configuration in the future.

**Comment by cool-RR** [comment]
I don't think there's anything stopping you from running PyLint with just one rule. The only caveat is having to set up another CI job; but you'll have that caveat with any linter you use, even if it's just a special-purpose one.

**Comment by kit1980** [comment]
> I don't think there's anything stopping you from running PyLint with just one rule. The only caveat is having to set up another CI job; but you'll have that caveat with any linter you use, even if it's just a special-purpose one.

Would you like to try yourself to add pylint with only that rule enabled to the CI?

**Pull request closed without merging**
