### PR TITLE
Fix test_decomp test for ops with py_impl(CompositeImplicitAutograd)

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #116832

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
We should add the same logic for the gradient pass in the paragraph before this one, but in the case the where the it has a kernel for the `Autograd` key.

**Review by lezcano — COMMENTED** [review]
What happened with this PR? @isuruf

**Comment by isuruf** [comment]
The second part of the test added here resulted in
```
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed)
```
any ideas on how to fix this?

**Review by lezcano — APPROVED** [review]
Thanks!

**Pull request closed without merging**
