### PR TITLE
handle SymInt shape/input when debugging in dynamic shape

### LINKED ISSUE #96272: [Dynamo] handle SymInt shape/input when debugging in dynamic shape
### 🐛 Describe the bug

Hi, I encounter two problems when debugging dynamo.optimize in dynamic shape.

1. the produced ```fx_graph_runnable.py``` with 'SymInt' is not quite runnable. i.e. the 's0', 's1' are not defined.

```python
# fx_graph_runnable.py
...
args = [((2304, 768), (768, 1), torch.float32, 'cuda'), ((2304,), (1,), torch.float32, 'cuda'), ((s0, s1, 768), (768*s1, 768, 1), torch.float32, 'cuda')]
args = [rand_strided(sh, st, dt, dev) for (sh, st, dt, dev) in args]
...
```

2. When dynamic shape enabled, I notice that the inputs of a graph could be SymInt instead of Tensor in some cases, incurring error when minifying or generating repro string.

```python
# fx_graph_readable.py
class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: Sym(s0), arg1_1: Sym(s1), arg2_1: f32[s0*s1, s3], arg3_1: f32[s0, s4, s1, s5]):
...
```

i. error message for generating repro string:

```
...
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 339, in save_graph_repro
    fd.write(generate_compiler_repro_string(gm, args))
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 283, in generate_compiler_repro_string
    model_str += f"args = {[(tuple(a.shape), tuple(a.stride()), a.dtype, a.device.type) for a in args]!r}\n"
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 283, in <listcomp>
    model_str += f"args = {[(tuple(a.shape), tuple(a.stride()), a.dtype, a.device.type) for a in args]!r}\n"
AttributeError: 'SymInt' object has no attribute 'shape'
```

ii. error message for minifying:

```
...
File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 555, in deferred_for_real_inputs
    copy_tensor_attrs = [fake_mode.from_tensor(x) for x in real_inputs]
  File "/opt/conda/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 555, in <listcomp>
    copy_tensor_attrs = [fake_mode.from_tensor(x) for x in real_inputs]
  File "/opt/conda/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1398, in from_tensor
    return self.fake_tensor_converter(
  File "/opt/conda/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 314, in __call__
    return self.from_real_tensor(
  File "/opt/conda/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 246, in from_real_tensor
    maybe_memo = self._get_memo(t)
  File "/opt/conda/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 213, in _get_memo
    if WeakIdRef(t) in self.tensor_memo:
TypeError: cannot create weak reference to 'int' object
```

Please refer to https://gist.github.com/ZhongYingMatrix/5f4f3107e592c7f9a99eaa3de093b437 to repro bug.

And could I create a PR to fix it? It will turn out to be like:

```python
# fx_graph_runnable.py

# before
...
args = [((2304, 768), (768, 1), torch.float32, 'cuda'), ((2304,), (1,), torch.float32, 'cuda'), ((s0, s1, 768), (768*s1, 768, 1), torch.float32, 'cuda')]
args = [rand_strided(sh, st, dt, dev) for (sh, st, dt, dev) in args]
...

# after
...
args = []
args.append(rand_strided((2304, 768), (768, 1), torch.float32, 'cuda'))  # shape (2304, 768), stride (768, 1)
args.append(rand_strided((2304,), (1,), torch.float32, 'cuda'))  # shape (2304,), stride (1,)
args.append(rand_strided((160, 49, 768), (37632, 768, 1), torch.float32, 'cuda'))  # shape (s0, s1, 768), stride (768*s1, 768, 1)
...

# bw that inputs have SymInt
...
args = []
args.append(160)  # s0
args.append(49)  # s1
args.append(rand_strided((7840, 768), (768, 1), torch.float32, 'cuda'))  # shape (s0*s1, s3), stride (s3, 1)
args.append(rand_strided((160, 6, 49, 128), (37632, 6272, 128, 1), torch.float32, 'cuda'))  # shape (s0, s4, s1, s5), stride (s1*s4*s5, s1*s5, s5, 1)
...


```
Thx~ @ezyang @bdhirsh @wconstab @ngimel @msaroufim 

### Versions

output of collect_env
```
Collecting environment information...
PyTorch version: 2.1.0.dev20230306+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Alibaba Group Enterprise Linux Server 7.2 (Paladin) (x86_64)
GCC version: (GCC) 8.3.1 20190604 (Alibaba 8.3.1-1 2.24)
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.24

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.9.151-015.ali3000.alios7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                96
On-line CPU(s) list:   0-95
Thread(s) per core:    2
Core(s) per socket:    24
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
Stepping:              4
CPU MHz:               2500.000
CPU max MHz:           3100.0000
CPU min MHz:           1000.0000
BogoMIPS:              5000.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              33792K
NUMA node0 CPU(s):     0-95
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single cdp_l3 ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke flush_l1d

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.0.0+b8b470bc59
[pip3] torch==2.1.0.dev20230306+cu117
[pip3] torchaudio==2.0.0.dev20230103+cu117
[pip3] torchvision==0.15.0.dev20230103+cu117
[conda] atorch                    0.1.0                    pypi_0    pypi
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.23.5           py38h14f4228_0  
[conda] numpy-base                1.23.5           py38h31eccc5_0  
[conda] pytorch-triton            2.0.0+b8b470bc59          pypi_0    pypi
[conda] torch                     2.1.0.dev20230306+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230103+cu117          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230103+cu117          pypi_0    pypi
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

### PR DESCRIPTION
**Pull request by ZhongYingMatrix**
Handle SymInt shape/input when debugging in dynamic shape. Fixes #96272 

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
These fixes seem reasonable + strictly better than what we have today. Thanks @ZhongYingMatrix ! (and the minifier not always working with dynamic shapes has been a real papercut).

**Comment by ZhongYingMatrix** [comment]
Thx @bdhirsh ! Anything I can do with the check Failures?

**Comment by bdhirsh** [comment]
@ZhongYingMatrix can you sign the CLA?

**Comment by ZhongYingMatrix** [comment]
> @ZhongYingMatrix can you sign the CLA?

@bdhirsh already signed :)

**Pull request closed without merging**
