### PR TITLE
[FSDP][optim_state_dict][11/N] Let FSDP support NamedOptimizer/KeyedOptimizer when use_orig_params is False

### PR DESCRIPTION
**Pull request by fegin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #92184

Current design of FSDP only support NamedOptimizer/KeyedOptimizer when use_orig_params is True this PR adds the support even if use_orig_params if False. This PR also adds the support for user-defined optimizer states -- states that are not associated with any particular parameters.

Differential Revision: [D42497416](https://our.internmc.facebook.com/intern/diff/D42497416/)

### CODE REVIEW

**Review by colin2328 — APPROVED** [review]
LGTM! thanks @fegin

**Review by rohan-varma — COMMENTED** [review]
Implementation LGTM overall but we should discuss if we absolutely need to support this. I'd vote for just testing + landing use_orig_params=True support into this specific use case, and reducing the complexity here to just add support for arbitrary states (in both paths). WDYT?

**Comment by fegin** [comment]
Will land this PR to unblock the use case of NamedOptimizer. This will also include the support of `NamedOptimizer` + `use_orig_params=False`. We can remove the part to support `use_orig_param=False` later if that's way too complicated.

**Review by rohan-varma — APPROVED** [review]

**Comment by fegin** [comment]
The failing tests are not related.

**Pull request closed without merging**
