### PR TITLE
Remove tensor storage_offset/storage_bytes from the cache key

### PR DESCRIPTION
**Pull request by oulgen**
Summary: We observed differences in these fields and inductor does not specialize on them so it is safe to remove them from the key.

Test Plan: CI

Reviewed By: masnesral

Differential Revision: D57871276

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by masnesral — APPROVED** [review]

**Comment by eellison** [comment]
cc @davidberard98  - should should be sound, right ? Do we also need to exclude parameters from this ?

**Review by davidberard98 — COMMENTED** [review]
hmm, I _think_ this should probably fine, although it does technically introduce a potential regression:

within a single graph, I think this is fine:
* AFAIK, there _can_ be failures if parameters somehow change storage_offset
* however, this was also the case before, because we wouldn't trigger inductor recompilation if storage_offset changed

however, I suppose it's possible that we have the following:
* graph 1 and graph 2 are identical except their parameters have different storage_offset
* previously, due to different cache key, we would actually generate different code for the two graphs; but after we land this, we might incorrectly use the "tensor is already aligned" codepath for both graphs

This is the line where this could be a concern:
https://github.com/pytorch/pytorch/blob/0a9d73a81461f1dc605efb7a444c9e3e29a3c90f/torch/_inductor/compile_fx.py#L883

**Comment by eellison** [comment]
@davidberard98 it's okay to generate slightly different graphs so long as the correctness is there (small fluctuations in alignment are why we don't guard in the first place). but i guess in this case, we won't actually discover if a parameter has become no longer aligned, correct ? 

a couple solutions:

- in the cache key, only include whether storage_offset is aligned, not full value. in repro we looked at it was unaligned for both values. I don't love that this is a little tied to the current logic and if someone changes inductor lowering wonder how it will propagate back. Still i think we could do it.
- include storage_offset only for the static_input idxs

@davidberard98 any thoughts?

**Comment by davidberard98** [comment]
responding to @eellison :

> we won't actually discover if a parameter has become no longer aligned, correct ?

correct

> a couple solutions:

these both sound like good ideas - I guess they're both sort of tied into the current logic, but the current logic is also already sort of repeated in a few places. I guess I have a slight preference for the second one (include storage_offset only for the static_input idxs) since it seems less likely to change?

**Comment by davidberard98** [comment]
not a major concern: but I was thinking about this again, and guarding/caching on storage_offset alignment actually might be preferrable, for performance in the case where we start doing caching across different machines.

the scenario that I'm thinking of is that we have two identical graphs coming from different models - one where the inputs are aligned, and one where the inputs are not aligned. 

In the local-caching scenario, this will probably be handled correctly; machine A, running model X, will specialize on the unguarded alignment; machine B, running model Y, will do the same; and restarts/recompiles/etc. on those machines will find the correct cache entry that gives good performance.

But in the global-caching scenario, model X (say, with aligned inputs) might populate the cache first; but model Y (say, with unaligned inputs) will read the same cache entry and get an implementation that copies the inputs.

**Comment by eellison** [comment]
@davidberard98 I think it is pretty unlikely to have huge performance differences because of alignment for a model. You would need to generate the same exact shape/strides for all of the inputs, and have the same graph, but have radically different alignment on tensors. That seems hard to do. Almost all of the inputs we expect to be aligned, anyway.

For a little context here - we were were seeing a cache miss because two tensors had slightly different alignment across ranks. One was misaligned by 3 and the other misaligned by 2 (both misaligned). 

We could also do the thing I mentioned above where we include alignment in the cache key instead of the full stride. this would also generalize to parameters/static inputs.

**Comment by davidberard98** [comment]
@eellison agree, I just meant to point out that your other suggestion ("We could also do the thing I mentioned above where we include alignment in the cache key instead of the full stride") might be slightly better than caching on storage_offset for only parameters

**Comment by oulgen** [comment]
@eellison @davidberard98 could you take a look at the code changes?

**Pull request closed without merging**
