### PR TITLE
Vectorize floating point floor_divide

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #50438 Support JIT shape analysis for div with rounding_mode argument
* #55225 grad_fn getter for optional strings
* #51989 Sparse support for division rounding_mode argument
* #56893 Update floor_divide behavior in line with NumPy 1.20
* **#55380 Vectorize floating point floor_divide**

Differential Revision: [D27993499](https://our.internmc.facebook.com/intern/diff/D27993499)

### CODE REVIEW

**Comment by peterbell10** [comment]
@mruberry PTAL

**Review by mruberry — APPROVED** [review]
Cool!

**Comment by mruberry** [comment]
Android builds are upset about the "unused" alias:

```
aten/src/ATen/native/cpu/BinaryOpsKernel.cpp:169:13: error: unused type alias 'vec_t' [-Werror,-Wunused-local-typedef]
      using vec_t = Vec256<scalar_t>;
```

**Comment by peterbell10** [comment]
@mruberry I removed the duplicate `vec_t` alias. Should be good now.

**Comment by mruberry** [comment]
> @mruberry I removed the duplicate `vec_t` alias. Should be good now.

Looks like the issue has been addressed. Landing now.

**Pull request closed without merging**
