### PR TITLE
[inductor] CI improvments

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #91283

Summary:
1) Setting torch.backends.cudnn.deterministic to True helps to
eliminate the eager_variance failures seen on CI
2) Skip Triton failure instead of retry
3) Some minor script cleanup is also included in this PR.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

### CODE REVIEW

**Comment by ngimel** [comment]
cc @anijain2305. We can't set eval mode for timm models because that would disable bn testing, and we had serious bugs when we didn't test bn. 
Instead, we should leave the mode as training, but set dropout to 0 to avoid non-determinism (also, my impression was that dropout is already 0 for most timm models by default)

**Comment by desertfire** [comment]
> cc @anijain2305. We can't set eval mode for timm models because that would disable bn testing, and we had serious bugs when we didn't test bn. Instead, we should leave the mode as training, but set dropout to 0 to avoid non-determinism (also, my impression was that dropout is already 0 for most timm models by default)

Discussed offline. Dropout is not the root cause here since it is already 0 for those failing models we have seen on CI. Setting `torch.backends.cudnn.deterministic = True` works, at least for the models I tried. Let's see if it solves all the `eager_variance` failures on CI.

**Review by anijain2305 — APPROVED** [review]

**Pull request closed without merging**
