### PR TITLE
INT8 SDPA API

### PR DESCRIPTION
**Pull request by Valentine233**
1. To support int8 type, extend the SDPA API with 5 pairs of scale and zero point.
2. Add the reference path of int8 sdpa in math backend.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by Valentine233** [comment]
Encountered three failures in CI, two related to android building and one related to windows building.

For android building failure, I try to reproduce locally according to https://pytorch.org/mobile/android/#building-pytorch-android-from-source, but it is stuck during gradle building:
image

The command line is: `ANDROID_HOME=/opt/android-sdk/platforms/android-33/ ANDROID_NDK=/opt/android-sdk/ndk/21.3.6528147/ GRADLE_HOME=/opt/gradle/gradle-8.10/ JAVA_HOME=/opt/java-jdk/jdk-22.0.2/ ./scripts/build_pytorch_android.sh`.

@drisspg Could you help to take a look at the CI failures? Does the PR forget to modify certain files related to android/windows building?

**Comment by drisspg** [comment]
TBH I am hesitant to land this in core since the blast radius is quite high and the usage is not generic for all users, e.g. int8 seems to only be useful on cpu and for inference today. Is it possible to land this work in torchao and once the API is hardened and the quant flow is fully fledged we can revisit bringing this to core

**Comment by jgong5** [comment]
> TBH I am hesitant to land this in core since the blast radius is quite high and the usage is not generic for all users, e.g. int8 seems to only be useful on cpu and for inference today. Is it possible to land this work in torchao and once the API is hardened and the quant flow is fully fledged we can revisit bringing this to core

@drisspg Thanks for the feedbacks. BTW, the int8 SDPA quantization recipe by itself also benefits GPU since it speeds up the computing of BMM. Landing it to torchao first sounds good to me. At least, we'd better create a new op for it instead of complicating existing ones.

**Comment by Valentine233** [comment]
@drisspg Thanks! Is it acceptable to create a new op for int8 SDPA CPU in PyTorch? If not, I would try to land it in torchao then.

**Comment by drisspg** [comment]
Lets first land the cpu/gpu variant in torchao. I think that it will have better discoverability since the TorchAO  project is targeted for quantized/kernel specific performance optimizations. As well we can land this in the prototype section first and have less concerns over BC while we iterate

**Comment by Valentine233** [comment]
@drisspg Thanks very much! It is possible to implement the int8 sdpa op and the kernel itself in torchao. However, there would be some problems for the pattern match. Previously, we can replace with `return _scaled_dot_product_attention(…)` and then dispatch to int8 sdpa cpu kernel. But now, we have to replace with a torchao op, for example `return torchao.ops. _scaled_dot_product_flash_attention_int8_for_cpu(…)`, which is not feasible due to the dependency circle.

**Comment by Valentine233** [comment]
> @drisspg Thanks very much! It is possible to implement the int8 sdpa op and the kernel itself in torchao. However, there would be some problems for the pattern match. Previously, we can replace with `return _scaled_dot_product_attention(…)` and then dispatch to int8 sdpa cpu kernel. But now, we have to replace with a torchao op, for example `return torchao.ops. _scaled_dot_product_flash_attention_int8_for_cpu(…)`, which is not feasible due to the dependency circle.

Hi @drisspg , do you have any comment on the above issue? If the issue is not easy to be resolved, I suppose it is better for now to create a new op for int8 SDPA CPU in PyTorch, as a prototype feature.

**Comment by drisspg** [comment]
Hey sorry, I thought I responded. Is the the expectation for this OP that there will be no user side code changes and that this will be a pure pattern matching pass? 

I am planning to put up an RFC on Torchao about `low-preicsion` attention for both training and inference where I am grouping fp8 + int8 and hope that the api would support both

**Comment by Valentine233** [comment]
@drisspg Thanks very much for the comment.

> Hey sorry, I thought I responded. Is the the expectation for this OP that there will be no user side code changes and that this will be a pure pattern matching pass?

Yes. In PyTorch, I plan to add a new OP `func: _scaled_dot_product_flash_attention_int8_for_cpu(Tensor query, Tensor key, Tensor value, float dropout_p=0.0, bool is_causal=False, *, Tensor? attn_mask=None, float? scale=None, int q_zp=0, float q_scale=1.0, int k_zp=0, float k_scale=1.0, int v_zp=0, float v_scale=1.0, int a_zp=0, float a_scale=1.0, int o_zp=0, float o_scale=1.0) -> (Tensor output, Tensor logsumexp)`. This is only for the internal call from the pattern matching pass. I would start to do it if you have no other doubt.

> I am planning to put up an RFC on Torchao about `low-preicsion` attention for both training and inference where I am grouping fp8 + int8 and hope that the api would support both

Sure. Could you please elaborate more about the design, or is there already a drafted RFC? Do you mean to support both PyTorch and Torchao by saying "support both"? As the API and kernel implementation are in PyTorch, I suppose we could just call the API of PyTorch from Torchao.

**Pull request closed without merging**
