### PR TITLE
add from_pretrained method to EmbeddingBag

### PR DESCRIPTION
**Pull request by dhpollack**
The `EmbeddingBag` module does not include a `from_pretrained` method like the `Embedding` module.  I added it for consistency between the two modules.

### CODE REVIEW

**Comment by weiyangfb** [comment]
changes look legit to me, wondering why not passing in args like `max_norm`, `norm_type`, `mode` etc to `from_pretrained` as well. cc @SsnL @soumith

**Comment by dhpollack** [comment]
I can make those changes as well

**Comment by SsnL** [comment]
LGTM too, but please also add the other options @weiyangfb mentioned.

**Comment by dhpollack** [comment]
@ezyang let me know if that is what you are looking for.

**Review by soumith — APPROVED** [review]

**Pull request closed without merging**
