### PR TITLE
Make c10::ComplexHalf a template specialization of c10::complex

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Issue: https://github.com/pytorch/pytorch/issues/35284

~This depends on and contains https://github.com/pytorch/pytorch/pull/35524. Please review after the dependency gets merged and I will rebase to get a clean diff.~

This PR basically makes `c10::ComplexHalf` a template specialization of `c10::complex`. Since `c10::ComplexHalf` is not used much, this does not include much change.

Due to the fact that `c10::Half` does not have much `constexpr` methods, it is impossible to keep the same API. Currently, we are just completely reusing the old implementation. It is just the name getting changed from `c10::ComplexHalf` to `c10::complex<c10::Half>`. We can always change the implementation in the future when needed. But for now, I think this is OK.

### CODE REVIEW

**Comment by vincentqb** [comment]
Adding @ezyang as in #35524

**Comment by ezyang** [comment]
Whoopee!

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
It looks like there are some compatibility problems with our mobile builds.

```
xplat/caffe2/c10/util/complex_type.h:437:10: error: no member named 'hypot' in namespace 'std'; did you mean simply 'hypot'?
  return std::hypot(std::real(z), std::imag(z));
```

This is on Android. You might be able to repro in OSS if you push to a `ci-all/` branch in `pytorch/pytorch`

**Comment by zasdfgbnm** [comment]
Let's land https://github.com/pytorch/pytorch/pull/37274 first, then I will work on fixing the issue here.

**Comment by zasdfgbnm** [comment]
close this in favor of https://github.com/pytorch/pytorch/pull/37426 which has all CI enabled.

**Pull request closed without merging**
