### PR TITLE
[Inductor] Support loop split at given depth in CPP codegen

### PR DESCRIPTION
**Pull request by jgong5**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #91532
* __->__ #91397

This PR refactors the loop related data structure to support the loop split at a given depth. Before this PR, the loop split is always supported at the inner-most level. With this PR, it is possible to support tiling at outer levels and at more than one levels. The `LoopNest` data structure is extended to support loop splits at various levels and renamed to `LoopNestWithSplit`. The `codegen_loops` function is also rewritten to be general to support arbitrary kernels set at the leaves of the loop structure.

This PR also improves the handling of reduction loops with split. The main loop and tail loop now work on their own reduction variables in parallel without data dependency as previous do. With this, two workarounds can be removed in the `CppVecKernel`.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by EikanWang — APPROVED** [review]

**Review by desertfire — COMMENTED** [review]
This is a big refactoring. Do we expect to see any codegen difference from it?

**Comment by jgong5** [comment]
> This is a big refactoring. Do we expect to see any codegen difference from it?

No, there shouldn't be any codegen difference (semantically, not syntactically). It would be a bug otherwise.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
