### PR TITLE
[ONNX] Bump onnxscript version in CI; temporarily remove op test

### PR DESCRIPTION
**Pull request by justinchuby**
Bump onnxscript version in CI to 0.1.0.dev20240831, and temporarily remove the fx consistency test. We will add a better version back later.

### CODE REVIEW

**Comment by justinchuby** [comment]
There is some py38 typing we need to fix in onnxscript @titaiwangms

**Review by titaiwangms — APPROVED** [review]

**Comment by justinchuby** [comment]
arange dynamic input:

```pytb
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/onnx/_internal/diagnostics/infra/decorator.py", line 130, in wrapper
    return_values = fn(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/onnx/_internal/fx/fx_onnx_interpreter.py", line 440, in run_node
    self.call_function(
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/onnx/_internal/fx/fx_onnx_interpreter.py", line 656, in call_function
    ) = symbolic_fn(*onnx_args, **onnx_kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/onnxscript/values.py", line 583, in __call__
    return self.func(*args, **kwargs)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/onnxscript/function_libs/torch_lib/ops/core.py", line 597, in aten_arange_start
    start = float(start)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/onnxscript/tensor.py", line 67, in __float__
    return float(self.value)
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by ZainRizvi** [comment]
@pytorchbot revert -m "The version bump appears to be pulling in an unavailable numpy version? [GH job link](https://github.com/pytorch/pytorch/actions/runs/10686076754/job/29620426371) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/6eed63c8b9c4f54a573bb51960d252cd42bfab0c)" -c nosignal

If this PR is being falsely blamed, my apologies and feel free to remerge

**Comment by justinchuby** [comment]
@ZainRizvi the numpy issue is unrelated. It is supposed to be fixed by https://github.com/pytorch/pytorch/pull/134875

**Pull request closed without merging**
