### PR TITLE
TorchInductor Opinfo fixes for rng ops

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108170

Tests rng ops both with
- fallback_random=True, assertEqual=True
- fallback_random=False, assertEqual=False

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @Xia-Weiwen @ngimel

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]
LGTM!

only comment is that it seems like it might be hard to figure out what's happening if one of these starts failing? it might be slightly nicer if we could have a different test name for the different configs; but on the other hand IDK if there's a nice way to do that without hard-coding a list of random ops or spawning a bunch of extra unnecessary tests (feel free to land without changes, just brought it up in case you have ideas)

**Comment by eellison** [comment]
@davidberard98 it's a good point, but yea would prefer to automatically detect the rng ops instead of having a list that might get outdated or have unnecessary tests. going to keep as is for now.

**Comment by eellison** [comment]
cc @jbschlosser this pr is causing test_nestedtensor to fail with dynamo even though it's unrelated. any thoughts on fixes ? Not sure if https://github.com/pytorch/pytorch/issues/110641 is related.

**Comment by eellison** [comment]
cc @cpuhrsch. I'm not sure what the point of those tests are if we don't really support NT in pt2. Example failure:


```
> 2023-10-12T00:45:01.3452658Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2023-10-12T00:45:01.3452829Z ____________ TestNestedTensorDeviceTypeCPU.test_narrow_cpu_float64 _____________
2023-10-12T00:45:01.3452930Z Traceback (most recent call last):
2023-10-12T00:45:01.3453057Z   File "test_nestedtensor.py", line 2104, in test_narrow
2023-10-12T00:45:01.3453164Z     self.assertTrue(narrowed._base is nt)
2023-10-12T00:45:01.3453325Z   File "/opt/conda/envs/py_3.8/lib/python3.8/unittest/case.py", line 765, in assertTrue
2023-10-12T00:45:01.3453429Z     raise self.failureException(msg)
2023-10-12T00:45:01.3453520Z AssertionError: False is not true
2023-10-12T00:45:01.3453527Z 
2023-10-12T00:45:01.3453667Z To execute this test, run the following from the base repo dir:
2023-10-12T00:45:01.3453906Z     PYTORCH_TEST_WITH_DYNAMO=1 python test_nestedtensor.py -k test_narrow_cpu_float64
2023-10-12T00:45:01.3453914Z 
2023-10-12T00:45:01.3454075Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2023-10-12T00:45:01.3454247Z ____________ TestNestedTensorDeviceTypeCPU.test_narrow_cpu_float64 _____________
```

More log
```
2023-10-12T00:45:01.3422112Z [2023-10-12 00:45:00,218] torch._dynamo.convert_frame: [WARNING] 
2023-10-12T00:45:01.3422439Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING] WON'T CONVERT compare_metadata test_nestedtensor.py line 2933 
2023-10-12T00:45:01.3422635Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING] due to: 
2023-10-12T00:45:01.3422878Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING] Traceback (most recent call last):
2023-10-12T00:45:01.3423291Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 648, in _convert_frame
2023-10-12T00:45:01.3423586Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     result = inner_convert(frame, cache_entry, hooks, frame_state)
2023-10-12T00:45:01.3423952Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 142, in _fn
2023-10-12T00:45:01.3424173Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     return fn(*args, **kwargs)
2023-10-12T00:45:01.3424570Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
2023-10-12T00:45:01.3424787Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     return _compile(
2023-10-12T00:45:01.3425159Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 594, in _compile
2023-10-12T00:45:01.3425452Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     raise InternalTorchDynamoError(str(e)).with_traceback(
2023-10-12T00:45:01.3425827Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 575, in _compile
2023-10-12T00:45:01.3426128Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     guarded_code = compile_inner(code, one_graph, hooks, transform)
2023-10-12T00:45:01.3426499Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 221, in time_wrapper
2023-10-12T00:45:01.3426726Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
2023-10-12T00:45:01.3427106Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 497, in compile_inner
2023-10-12T00:45:01.3427365Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     out_code = transform_code_object(code, transform)
2023-10-12T00:45:01.3427818Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
2023-10-12T00:45:01.3428116Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     transformations(instructions, code_options)
2023-10-12T00:45:01.3428534Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 450, in transform
2023-10-12T00:45:01.3428789Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     tracer = InstructionTranslator(
2023-10-12T00:45:01.3429167Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2051, in __init__
2023-10-12T00:45:01.3429451Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     self.symbolic_locals = collections.OrderedDict(
2023-10-12T00:45:01.3429832Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2054, in <genexpr>
2023-10-12T00:45:01.3430082Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     VariableBuilder(
2023-10-12T00:45:01.3430460Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 232, in __call__
2023-10-12T00:45:01.3430753Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     vt = self._wrap(value).clone(**self.options())
2023-10-12T00:45:01.3431116Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 373, in _wrap
2023-10-12T00:45:01.3431364Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     return type_dispatch(self, value)
2023-10-12T00:45:01.3431754Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1069, in wrap_tensor
2023-10-12T00:45:01.3432000Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     tensor_variable = wrap_fx_proxy(
2023-10-12T00:45:01.3432392Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1304, in wrap_fx_proxy
2023-10-12T00:45:01.3432624Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     return wrap_fx_proxy_cls(
2023-10-12T00:45:01.3433021Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1419, in wrap_fx_proxy_cls
2023-10-12T00:45:01.3433289Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     example_value = wrap_to_fake_tensor_and_record(
2023-10-12T00:45:01.3433705Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1726, in wrap_to_fake_tensor_and_record
2023-10-12T00:45:01.3433922Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING]     tuple(e.shape),
2023-10-12T00:45:01.3434353Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING] torch._dynamo.exc.InternalTorchDynamoError: Internal error: NestedTensorImpl doesn't support sizes. Please file an issue.
2023-10-12T00:45:01.3434525Z [2023-10-12 00:45:00,223] torch._dynamo.convert_frame: [WARNING] 
```

**Comment by cpuhrsch** [comment]
cc @jbschlosser @soulitzer

**Comment by soulitzer** [comment]
> I'm not sure what the point of those tests are if we don't really support NT in pt2.

I think these are important to make sure that if someone uses NT in their program, it would prefer to fallback to eager rather than produce silently incorrect results.

Also, I was not able to repro this. Sounds like just a flaky test?

**Comment by eellison** [comment]
@soulitzer do you have any ideas of how to move forward ?

**Comment by soulitzer** [comment]
@eellison rerun the test (the failure should go away) or just force merge, since your PR seems unrelated

**Comment by eellison** [comment]
I've rebased multiple times and I'm getting the same error. This is the run from the prior rebase: https://pipelinesghubeus21.actions.githubusercontent.com/mBh68xKhi8LyM7tp3vECvYXNFvuV4gyVGgmYCteuEZP9JH92QN/_apis/pipelines/1/runs/3454975/signedlogcontent/356?urlExpires=2023-10-13T19%3A38%3A44.7482690Z&urlSigningMethod=HMACV1&urlSignature=YXgciB%2Bt3a0TY2KsnzNf%2BLjGnHr%2FLw9lDa4pLALqVIs%3D.

**Comment by soulitzer** [comment]
hmmm thats interesting. let's just go ahead and land this for now? 
but it sounds like we definitely should disable the flaky tests, and not sure why they aren't getting disabled automatically?

**Pull request closed without merging**
