### PR TITLE
Update foxi version

### PR DESCRIPTION
**Pull request by zrphercule**
Update foxi to the latest version for group quantization.

### CODE REVIEW

**Review by jackm321 — APPROVED** [review]
LGTM

**Review by houseroad — APPROVED** [review]
shipit

**Review by yinghai — COMMENTED** [review]
I don't want to block the fix to land but .DS_Store shouldn't be committed. We should probably add it to .gitignore.

**Comment by jackm321** [comment]
@yinghai it's in there, not sure why it's changed

**Comment by jackm321** [comment]
Looks like it needs to be removed from git also

**Comment by zrphercule** [comment]
@yinghai @jackm321  Let's merge this first to unbreak master, and remove it using another pr, since this one has been landing for a while now.

**Comment by houseroad** [comment]
we need to update the foxi, and update the submodule again

**Pull request closed without merging**
