### PR TITLE
Add at::optional from https://github.com/akrzemi1/Optional

### PR DESCRIPTION
**Pull request by colesbury**
This adds at::optional which matches the API of std::optional from C++17. For details about the implementation, see https://github.com/akrzemi1/Optional.

I've moved the types from `std::experimental` to the `at` namespace. This seems less likely to cause conflicting definitions, especially since PyTorch symbols are currently loaded with `RTLD_GLOBAL`.

I've verified that it compiles, but I haven't added any uses as part of this PR. I plan to use internally within ATen to implement `reshape`. We may also want to use it in place of undefined tensors in the public API.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Consider also leaving a URL breadcrumb to upstream

**Comment by gchanan** [comment]
roughly how do you plan to use it for reshape?

**Comment by colesbury** [comment]
@gchanan reshape needs to compute the strides of the reshaped tensor. It's convenient to implement this as a function that returns `optional<vector<int64_t>>`

**Pull request merged**
