### PR TITLE
Disable more of the pragma warning stuff

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #64923
* __->__ #64899

Differential Revision: [D30893691](https://our.internmc.facebook.com/intern/diff/D30893691/)

### CODE REVIEW

**Comment by ngimel** [comment]
Unfortunately, seeming success of CI cannot be trusted, as target determinator skipped test_reductions (that were failing on master with #64870)

**Comment by ezyang** [comment]
In https://github.com/pytorch/pytorch/pull/64899/checks?check_run_id=3582228836 we see:

```
Determination is skipping test_reductions
```

**Comment by ezyang** [comment]
In the downstream PR I disabled determination and verified reductions and ops are passing. So this is good to go.

**Comment by ezyang** [comment]
cc @peterbell10

**Comment by peterbell10** [comment]
What build errors are happening? If removing the hanging `pop` didn't work then my though would be that the warning exists for `TensorBase` as well, so the correct fix would be to add the corresponding disable just before the assignment operator:

```cpp
  void reset() {
    impl_.reset();
  }

  // Silence C4522: 'at::TensorBase': multiple assignment operators specified
  // We purposefully delete the r-value overload.
  #ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning( disable : 4522 )
  #endif

  TensorBase& operator=(const TensorBase& x) & {
```

**Comment by ngimel** [comment]
There were no build errors, but tests (test_argminmax_multiple_cuda_uint8) was mysteriously failing on cuda 11.3 linux build when pragma warning was removed from TensorBase.h only (note, #ifdef is on _MSC_VER, so it's unclear how it could have affected linux build at all).

**Pull request closed without merging**
