### PR TITLE
[quant][pt2e] Support setting qconfig by module_type

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #92355

Summary:
This PR supports the following feature for QConfigMapping:
```
qconfig_mapping = QConfigMapping().set_object_type(torch.nn.Conv2d, qconfig)
backend_config = get_qnnpack_pt2e_backend_config()
m = prepare_pt2e(m, qconfig_mapping, example_inputs, backend_config)
```
which means users want to set the qconfig for all calls to `torch.nn.Conv2d` to use `qconfig`, note this is only verified for the case when the module is broken down to a single aten op right now, e.g. torch.nn.Conv2d will be torch.ops.aten.convolution op when traced through. will need to support more complicated modules that is broken down to multiple operators later, e.g. (MaxPool)

Test Plan:
python test/test_quantization.py TestQuantizePT2E.test_qconfig_module_type

Reviewers:

Subscribers:

Tasks:

Tags:

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by jcaip — COMMENTED** [review]
There's some unused imports the linter is complaining about.

Also does `att` mean something special for the summary? If not I think you should update with something more descriptive.

**Comment by jerryzh168** [comment]
> There's some unused imports the linter is complaining about.
> 
> Also does `att` mean something special for the summary? If not I think you should update with something more descriptive.

will fix the lint, `att` means `as the title`, I don't have much to say, please let me know if we need to add any more descriptions to make it clearer

**Review by jcaip — APPROVED** [review]
Thanks for adding more info!

**Pull request closed without merging**
