### PR TITLE
We should not be in kernel invocation before we restore fake mode

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #124762
* #124760

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by eellison — APPROVED** [review]

**Comment by ezyang** [comment]
I'll resubmit this for CI after I get the PR before this (which fixes this invariant violation) is green

**Comment by ezyang** [comment]
\easycla

**Pull request closed without merging**
