### PR TITLE
fused qconv2d+relu kernel

### PR DESCRIPTION
**Pull request by dskhudia**
Summary: Adding support for fused qconv2d + relu

Differential Revision: D16473318

### CODE REVIEW

**Comment by jianyuh** [comment]
LGTM! Please land after it passes the OSS test.

**Review by jianyuh — APPROVED** [review]

**Comment by jianyuh** [comment]
Sorry, I only checked the internal Phabricator version. Could you check why this OSS version is different from the internal Diff version?

**Comment by jerryzh168** [comment]
@dskhudia there is a lint error: https://travis-ci.org/pytorch/pytorch/jobs/563343785

**Comment by jerryzh168** [comment]
please fix the error and land

**Comment by dskhudia** [comment]
@jerryzh168 I don't see the lint in my local file and it's in one of the files I haven't touched with this diff.

**Comment by jerryzh168** [comment]
I see, it's probably from master then

**Pull request closed without merging**
