### PR TITLE
Turn on expanded index path for Half on CPU

### PR DESCRIPTION
**Pull request by CaoE**
cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by CaoE** [comment]
Half seems to have been overlooked

**Comment by CaoE** [comment]
@yanbing-j @jgong5 Could you please review this PR ? Thanks.

**Review by yanbing-j — APPROVED** [review]
LGTM

**Comment by CaoE** [comment]
@jgong5 Could you please review this PR ? Thanks.

**Review by jgong5 — APPROVED** [review]

**Comment by CaoE** [comment]
@cpuhrsch Could you please review this PR ? Thank you.

**Review by peterbell10 — APPROVED** [review]

**Pull request closed without merging**
