### PR TITLE
Support str() on user defined functions

### PR DESCRIPTION
**Pull request by nakulcr7**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108973

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @jgong5 @mingfeima @sanchitintel @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @voznesenskym @penguinwu @EikanWang @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by nakulcr7** [comment]
Fixed part of #108699

@anijain2305 on running ` python benchmarks/dynamo/torchbench.py --bfloat16 --accuracy --inference --device cuda  --export-aot-inductor  --only hf_T5_generate`, I now see a different error

```
torch._dynamo.exc.Unsupported: call_function deepcopy in skip_files /home/nakulcr7/local/miniconda3/envs/pytorch-3.10/lib/python3.10/copy.py
```

**Comment by anijain2305** [comment]
> Fixed part of #108699
> 
> @anijain2305 on running ` python benchmarks/dynamo/torchbench.py --bfloat16 --accuracy --inference --device cuda --export-aot-inductor --only hf_T5_generate`, I now see a different error
> 
> ```
> torch._dynamo.exc.Unsupported: call_function deepcopy in skip_files /home/nakulcr7/local/miniconda3/envs/pytorch-3.10/lib/python3.10/copy.py
> ```

This is fine for now. We should treat this as a separate error.

**Comment by anijain2305** [comment]
Changes look good to me. 

On CI failures

(1) For the graph_breaks, this is actually an improvement. You can run this cmd

```
python benchmarks/dynamo/ci_expected_accuracy/update_expected.py 0810155ee1ca5b863004914462410e50444529de
```

copied from here 

image

(2) 
image

This might be an issue. Can you run this locally to check?

**Review by anijain2305 — APPROVED** [review]

**Comment by nakulcr7** [comment]
Rebased

**Comment by nakulcr7** [comment]
Reverted accidentally updated submodules

**Pull request closed without merging**
