### PR TITLE
Fixing dispatch error in windows debug builds

### PR DESCRIPTION
**Pull request by rje**
nullptr initialization values for dispatch pointers were overwriting values set using the REGISTER_DISPATCH macro.

Relevant issue: #22681

### CODE REVIEW

**Comment by ezyang** [comment]
I think we're obligated to initialize these in the constructor now, since the code inside relies on it being null to see if it it's registered or not. Does adding a constructor that zero initializes these fields still solve the problem for you? (Can we add a comment so someone doesn't helpfully "optimize" this away?)

**Comment by ezyang** [comment]
Hmm, based on the bug peterjc linked this might not be good though 
https://stackoverflow.com/questions/53196700/inline-variable-is-initialized-more-than-once

**Comment by rje** [comment]
I'll try it and report back

**Comment by rje** [comment]
I tried adding a constructor that sets the ptr values to nullptr and the issue reappeared.

As you mentioned in the original issue, these structs aren't declared inline so I'm not entirely sure it's the same issue mentioned in that stackoverflow post. But it feels like it's related given the similar behavior.

I'm going to try to think of an alternative approach, but it's a tricky problem! Let me know if you have any other ideas to try.

**Comment by ezyang** [comment]
Maybe we can fix this problem by switching to a function to access the struct in question. So instead of:

```
#define DECLARE_DISPATCH(fn, name)         \
  struct name : DispatchStub<fn, name> {}; \
  extern CAFFE2_API struct name name

#define DEFINE_DISPATCH(name) struct name name
```

Something like

```
#define DECLARE_DISPATCH(fn, name)         \
  struct name : DispatchStub<fn, name> {}; \
 CAFFE2_API struct name& get ## name

#define DEFINE_DISPATCH(name) \
  struct name& get ## name { \
    static struct name singleton; \
    return singleton; \
  }
```

Another quick fix I would try, is replace `CAFFE2_API` with `C10_IMPORT`, following guidance in `c10/util/Registry.h`

**Comment by rje** [comment]
Great idea, thanks for the suggestion! I'll try these when I'm back at my desk early next week, Hopefully adding a function will do the trick.

**Comment by peterjc123** [comment]
@rje Any updates?

**Comment by rje** [comment]
@peterjc123 - sorry, I got pulled away on some tasks at work that are high priority. I'm hoping to revisit this next week.

**Comment by peterjc123** [comment]
@ezyang Is this one still needed?

**Comment by ezyang** [comment]
Yes I think so, I didn't see any changes which would have eliminated this problem.

**Comment by peterjc123** [comment]
@ezyang Sadly, it doesn't work.

**Comment by ezyang** [comment]
@peterjc123 ugh this is so annoying. Maybe we can disable the nullptr initialization in DEBUG mode and yolo it in that case (would just be a strict improvement then.)

**Comment by peterjc123** [comment]
@ezyang Done!

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
