### PR TITLE
[test][docs] Fix doctest warnings for syntax errors

### PR DESCRIPTION
**Pull request by XuehaiPan**
Fixes some syntax errors in doctest find in CI tests.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by albanD** [comment]
Failures are real though right?

**Comment by XuehaiPan** [comment]
> Failures are real though right?

Yes. I fixed them in the last comment (I tested the doctests locally). Because the custom op does not allow registering functions with the same qualname, I changed 4 examples with `sin` to `sin`, `cos`, `sinh`, and `cosh`.

**Pull request closed without merging**
