### PR TITLE
Enable centos pytorch rocm CI

### PR DESCRIPTION
**Pull request by bddppq**

### CODE REVIEW

**Comment by bddppq** [comment]
Triggered run https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger/11/

**Review by houseroad — APPROVED** [review]

**Comment by iotamudelta** [comment]
@bddppq there is a bunch of MIOpen errors concerning wrong locale's before that already, I would assume that's also causing the SIGILL ultimately. When I did the original port to CentOS, I also saw similar problems but ultimately fixed them by setting LOCALE in the docker images. I'll look into this more.

**Comment by bddppq** [comment]
ping @iotamudelta

**Comment by bddppq** [comment]
New triggered run: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger/17/

**Comment by bddppq** [comment]
New triggered run: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger/22

**Comment by bddppq** [comment]
New triggered run: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger/23

**Comment by bddppq** [comment]
New triggered run: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger/26

**Comment by bddppq** [comment]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger/27/

**Comment by bddppq** [comment]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger/28/

**Comment by bddppq** [comment]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger/29/

**Pull request closed without merging**
