### PR TITLE
[ROCm] Fix circular recursion issue in hipification 

### PR DESCRIPTION
**Pull request by lcskrishna**
This PR fixes the circular issue during hipification process by introducing current_state to track whether a file is processed for hipification. (Iterative DFS) 
The issue arises when two header files try to include themselves, which leads to a circular recursion or an infinite loop. 

Fixes the related issues such as :
https://github.com/pytorch/pytorch/issues/93827
https://github.com/ROCmSoftwarePlatform/hipify_torch/issues/39

Error log:
```
  File "/opt/conda/lib/python3.8/posixpath.py", line 471, in relpath
    start_list = [x for x in abspath(start).split(sep) if x]
  File "/opt/conda/lib/python3.8/posixpath.py", line 375, in abspath
    if not isabs(path):
  File "/opt/conda/lib/python3.8/posixpath.py", line 63, in isabs
    sep = _get_sep(s)
  File "/opt/conda/lib/python3.8/posixpath.py", line 42, in _get_sep
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

cc: @jithunnair-amd 

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by lcskrishna** [comment]
@jithunnair-amd Could you please review and add the respective reviewers from upstream. I'm unable to add you as a reviewer.

**Review by jithunnair-amd — APPROVED** [review]
This has been a long time coming! Thank you!

**Comment by jithunnair-amd** [comment]
@kit1980 @malfet Please review and merge. This fixes some community-reported issues with using hipify for flash-attention/xformers.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
