### PR TITLE
[CD] Enable python 3.13 for xpu nightly build

### LINKED ISSUE #130543: XPU bundle environment variables setup scripts can't work with `set -u`
### 🐛 Describe the bug

Currently, the latest PyTorch development bundle for XPU environment variables setup scripts can't work with `set -u` caused by unbound variable. It can be reproduced by 
```
set -u
source /opt/intel/oneapi/pytorch-gpu-dev-0.5/oneapi-vars.sh
```
and will get below error message
```
/opt/intel/oneapi/pytorch-gpu-dev-0.5/etc/mkl/vars.sh: line 56: __mkl_tmp_MOD: unbound variable
```
This issue will be fixed in future bundle release and please avoid to use `set -u` if we meet this issue.

### Versions

```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.0
Libc version: glibc-2.35

Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-6.5.0-41-generic-x86_64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A
```

cc @gujinghui @EikanWang @fengyuan14 @guangyey

### PR DESCRIPTION
**Pull request by chuanqi129**
Enable python 3.13 for XPU nightly build, it depends on https://github.com/pytorch/pytorch/pull/133454 land. Also update the xpu nightly wheel test env.

Works for https://github.com/pytorch/pytorch/issues/114850
Fixes #130543

### CODE REVIEW

**Review by atalman — APPROVED** [review]
lgtm. Thank you for test PR

**Comment by chuanqi129** [comment]
Hi @atalman could you please help to land this PR also? The current test failures are not related with this PR change

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
