### PR TITLE
Use `std::abs` instead of `abs` in lbfgs.cpp

### PR DESCRIPTION
**Pull request by malfet**
`abs` is a C-style function that takes only integral argument
`std::abs` is polymorphic and can be applied to both integral and floating point types

Test Plan: CI

### CODE REVIEW

**Review by anjali411 — APPROVED** [review]
LGTM :) thanks! @yf225 I think we should merge this in 1.5 release

**Comment by EscapeZero** [comment]
Another really weird thing to be caught all the way in ovrsource sync. `-Wabsolute-value` should probably be enforced in CircleCI!

**Comment by malfet** [comment]
Replaced one `std::abs` with `at::abs`

**Comment by yf225** [comment]
@anjali411 Merging this into 1.5 release branch sounds great :D Would you like to drive this process? (i.e. opening a PR against `release/1.5` branch for this, and commenting in https://github.com/pytorch/pytorch/issues/35009) Thanks!

**Comment by zou3519** [comment]
This PR broke the previously passing ASAN test so I am reverting it. The build failure is https://circleci.com/gh/pytorch/pytorch/5007029?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link .

**Comment by malfet** [comment]
@zou3519 thank you for revert. I will look into it.

**Comment by yf225** [comment]
@malfet I opened a PR at https://github.com/pytorch/pytorch/pull/35974 which should also fix the ASAN issue :)

**Pull request closed without merging**
