### PR TITLE
Provide default value None for the attn_bias parameter(#133981)

### LINKED ISSUE #133981: Provide default value None for the attn_bias parameter of _scaled_dot_product_fused_attention_overrideable
### 🚀 The feature, motivation and pitch

For third-party vendors, we use the tests in the pytorch/test directory to verify the correctness of the third-party kernel. The reason we added attn_bias=None is to allow the testing of third-party `torch.ops.aten._scaled_dot_product_fused_attention_overrideable(q, k, v)` through the monkey patch mechanism during the tests for `torch.ops.aten._scaled_dot_product_flash_attention(q, k, v)`.

### Alternatives

_No response_

### Additional context

_No response_

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

### PR DESCRIPTION
**Pull request by 1274085042**
Fixes #133981
cc @drisspg @albanD @soulitzer  @cpuhrsch

### CODE REVIEW

**Comment by ezyang** [comment]
I'm going to defer to @drisspg but this looks like it should be safe. Holler again if you're still stuck.

**Comment by 1274085042** [comment]
@ezyang holler

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
