### PR TITLE
[vulkan] Disable shader optimization to avoid Validation Errors

### PR DESCRIPTION
**Pull request by SS-JIA**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #69332 Allow build_android.sh to forward Vulkan args
* **#69331 [vulkan] Disable shader optimization to avoid Validation Errors**
* #69330 [vulkan] Add image format qualifier to glsl files

---

## Context

When the optimization flag is turned on, some SPIR-V modules produced from the Vulkan compute shaders were invalid. The Vulkan Validation layer raises the following error for these modules:

```
[ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: Header block 52[%52] is contained in the loop construct headed by 44[%44], but it's merge block 47[%47] is not
%52 = OpLabel
```

Turning off the optimization flag, the SPIR-V modules produced no longer reports these errors in the Validation layer.

## Changes

Turns off optimization when generating SPIR-V modules to ensure correctness of the modules.

**Note that disabling SPIR-V optimization did not regress inference latency for the several models I tested**.

Differential Revision: [D32840910](https://our.internmc.facebook.com/intern/diff/D32840910)

### CODE REVIEW

**Review by beback4u — APPROVED** [review]
LGTM

**Comment by SS-JIA** [comment]
@SS-JIA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32840910).

**Comment by SS-JIA** [comment]
@SS-JIA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32840910).

**Comment by SS-JIA** [comment]
@SS-JIA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32840910).

**Pull request closed without merging**
