### PR TITLE
Use a FutureFactoryRegistry to allow libtorch_cpu files to create CUDAFuture

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#56984 Use a FutureFactoryRegistry to allow libtorch_cpu files to create CUDAFuture**
* #56973 Remove unnecessary noCuda arg from AtomicJitFuture

This is a preparation PR before we can create CUDAFuture in rref_impl.cpp.

The solution is adding a `FutureFactoryRegistry` in `rpc/utils.*`. The
TensorPipe RPC agent is responsible for registering `CUDAFuture` factory
and `ivalue::Future` factory. The reason that we need this change instead
of directly using `USE_CUDA` macro in RRef files is as follows. There are
three build targets: `torch_cpu`, `torch_cuda`, and `torch_python`.
`torch_python` is built on top of the other two. `torch_cpu` is CPU-only,
which contains no CUDA-related code, and hence no `USE_CUDA` macro.
`tensorpipe_*` files are in `torch_python` which does have access to CUDA.
However RRef source files are in `torch_cpu`, which cannot contain CUDA
code. The recommended solution is to allow dynamic dispatching. Therefore,
we had this PR.

Differential Revision: [D28020917](https://our.internmc.facebook.com/intern/diff/D28020917)

### CODE REVIEW

**Review by lw — APPROVED** [review]
The change itself looks fine to me. I find it unfortunate that we need to add this extra abstraction but if it's needed then this is a good way to go about it. One thing I don't understand is why we can't just use `#ifdef USE_CUDA` in rref_impl.cpp to control which type of future to create. We already do it in tensorpipe_agent.cpp, what is the difference?

I do see another alternative, which could however be much harder to pursue: we could merge CUDAFuture and ivalue::Future into a single class. (This would also remove all those weird fooHook protected methods we have now). The key to achieve this would be the `DeviceGuardImplInterface` class I mentioned yesterday, which would allow ivalue::Future to manipulate events and streams in a generic way without ever mentioning CUDA explicitly. There is however a catch: CUDAFuture needs two operations that are not yet offered by `DeviceGuardImplInterface`: getting a stream from the pool, and recording a DataPtr with the caching allocator. Unless there are good reasons to avoid them, we could add these methods to `DeviceGuardImplInterface`, merge ivalue::Future with CUDAFuture, and then all our RPC code could simply always instantiate an ivalue::Future and it would do the right thing under the hood.

**Comment by mrshenli** [comment]
> One thing I don't understand is why we can't just use #ifdef USE_CUDA in rref_impl.cpp to control which type of future to create. We already do it in tensorpipe_agent.cpp, what is the difference?

There are three build targets: `torch_cpu`, `torch_cuda`, and `torch_python`. `torch_python` is built on top of the other two. `torch_cpu` is CPU-only, which contains no CUDA-related code, and hence no `USE_CUDA` macro. `tensorpipe_*` files are in `torch_python` which does have access to CUDA. However source files listed below are in `torch_cpu`, which cannot contain CUDA code. @pbelevich and I discussed with @malfet 2 weeks ago, and the conclusion is that we still want to keep `torch_cpu` and `torch_cuda` build targets separate. The recommended solution is to allow dynamic dispatching. Therefore, we had this PR. 


https://github.com/pytorch/pytorch/blob/f7fba854bfd3ba01b30aef943c0732a069e352a5/tools/build_variables.bzl#L294-L331

**Comment by mrshenli** [comment]
Let me add the above description to the PR summary.

**Comment by mrshenli** [comment]
Test failures below is already on master:

```
Apr 27 16:09:47 ======================================================================
Apr 27 16:09:47 ERROR [83.073s]: test_all_gather_multigpu (__main__.TestDistBackendWithSpawn)
Apr 27 16:09:47 ----------------------------------------------------------------------
Apr 27 16:09:47 Traceback (most recent call last):
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 374, in wrapper
Apr 27 16:09:47     self._join_processes(fn)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 566, in _join_processes
Apr 27 16:09:47     self._check_return_codes(elapsed_time)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 609, in _check_return_codes
Apr 27 16:09:47     raise RuntimeError(error)
Apr 27 16:09:47 RuntimeError: Process 1 exited with error code 10 and exception:
Apr 27 16:09:47 Traceback (most recent call last):
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 492, in run_test
Apr 27 16:09:47     getattr(self, test_name)()
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 376, in wrapper
Apr 27 16:09:47     fn()
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 57, in wrapper
Apr 27 16:09:47     return func(*args, **kwargs)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 2979, in test_all_gather_multigpu
Apr 27 16:09:47     self._test_all_gather_multigpu_helper(group, group_id, rank, rank_to_GPU)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 2972, in _test_all_gather_multigpu_helper
Apr 27 16:09:47     self._barrier()
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 471, in _barrier
Apr 27 16:09:47     Barrier.sync(*args, **kwargs)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 388, in sync
Apr 27 16:09:47     raise RuntimeError("barrier timeout")
Apr 27 16:09:47 RuntimeError: barrier timeout
Apr 27 16:09:47 
Apr 27 16:09:47 
Apr 27 16:09:47 
Apr 27 16:09:47 ======================================================================
Apr 27 16:09:47 ERROR [83.075s]: test_all_gather_multigpu_complex (__main__.TestDistBackendWithSpawn)
Apr 27 16:09:47 ----------------------------------------------------------------------
Apr 27 16:09:47 Traceback (most recent call last):
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 374, in wrapper
Apr 27 16:09:47     self._join_processes(fn)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 566, in _join_processes
Apr 27 16:09:47     self._check_return_codes(elapsed_time)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 609, in _check_return_codes
Apr 27 16:09:47     raise RuntimeError(error)
Apr 27 16:09:47 RuntimeError: Process 1 exited with error code 10 and exception:
Apr 27 16:09:47 Traceback (most recent call last):
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 492, in run_test
Apr 27 16:09:47     getattr(self, test_name)()
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 376, in wrapper
Apr 27 16:09:47     fn()
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 57, in wrapper
Apr 27 16:09:47     return func(*args, **kwargs)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 2986, in test_all_gather_multigpu_complex
Apr 27 16:09:47     self._test_all_gather_multigpu_helper(group, group_id, rank, rank_to_GPU, dtype=torch.cfloat)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 2972, in _test_all_gather_multigpu_helper
Apr 27 16:09:47     self._barrier()
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 471, in _barrier
Apr 27 16:09:47     Barrier.sync(*args, **kwargs)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 388, in sync
Apr 27 16:09:47     raise RuntimeError("barrier timeout")
Apr 27 16:09:47 RuntimeError: barrier timeout
Apr 27 16:09:47 
Apr 27 16:09:47 
Apr 27 16:09:47 
Apr 27 16:09:47 ======================================================================
Apr 27 16:09:47 ERROR [105.114s]: test_broadcast_cuda (__main__.TestDistBackendWithSpawn)
Apr 27 16:09:47 ----------------------------------------------------------------------
Apr 27 16:09:47 Traceback (most recent call last):
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 374, in wrapper
Apr 27 16:09:47     self._join_processes(fn)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 566, in _join_processes
Apr 27 16:09:47     self._check_return_codes(elapsed_time)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 614, in _check_return_codes
Apr 27 16:09:47     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Apr 27 16:09:47 RuntimeError: Process 1 terminated or timed out after 105.09147000312805 seconds
Apr 27 16:09:47 
Apr 27 16:09:47 ======================================================================
Apr 27 16:09:47 ERROR [110.116s]: test_nccl_high_priority_stream (__main__.TestDistBackendWithSpawn)
Apr 27 16:09:47 ----------------------------------------------------------------------
Apr 27 16:09:47 Traceback (most recent call last):
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 374, in wrapper
Apr 27 16:09:47     self._join_processes(fn)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 566, in _join_processes
Apr 27 16:09:47     self._check_return_codes(elapsed_time)
Apr 27 16:09:47   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 614, in _check_return_codes
Apr 27 16:09:47     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Apr 27 16:09:47 RuntimeError: Process 0 terminated or timed out after 110.09352159500122 seconds
Apr 27 16:09:47 
Apr 27 16:09:47 ----------------------------------------------------------------------
```

**Pull request closed without merging**
