### PR TITLE
Handle the case when a derived SymNodeImpl does not extend PythonSymNodeImpl.

### LINKED ISSUE #4171: Fix dynamic shape test (xla/test/test_dynamic_shapes.py) and add it to pytorch/xla's CI.
## 🐛 Bug

xla/test/test_dynamic_shapes.py is currently failing and not included in the CI.

## To Reproduce

```
$ export XLA_EXPERIMENTAL=nonzero:masked_select:masked_scatter
$ python3 test/test_dynamic_shapes.py
======================================================================
ERROR: test_wrap (__main__.TestDynamicShapes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_dynamic_shapes.py", line 14, in test_wrap
    self.assertTrue(a2.shape[0] == 3)
RuntimeError: py_node INTERNAL ASSERT FAILED at "/workspace/pytorch/torch/csrc/utils/pybind.cpp":31, please report a bug to PyTorch
```
## Expected behavior

The test should pass and be included in the CI.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: CPU
 - torch_xla version: latest

### PR DESCRIPTION
**Pull request by vanbasten23**
Fixes [#ISSUE_NUMBER](https://github.com/pytorch/xla/issues/4171)

This is to make PyTorch/XLA [PR](https://github.com/pytorch/xla/pull/4180) compile.

### CODE REVIEW

**Comment by ezyang** [comment]
Doesn't seem right haha

**Review by ezyang — APPROVED** [review]
Assuming it works these changes look right. You don't need the default ctor anymore

**Comment by vanbasten23** [comment]
The test is still failing, but with a different error segfault:
```
(base) jenkins@c76438fd460f:/workspace/pytorch/xla$ export XLA_EXPERIMENTAL=nonzero:masked_select:masked_scatter
(base) jenkins@c76438fd460f:/workspace/pytorch/xla$ python3 test/test_dynamic_shapes.py
2022-11-11 01:48:24.422599: W  862128 tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2022-11-11 01:48:24.422650: W  862128 tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
Segmentation fault (core dumped)
```

Using gdb, I found
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fc37ea9bd71 in c10::SafePyObject::ptr(c10::impl::PyInterpreter const*) const ()
   from /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so
(gdb) bt
#0  0x00007fc37ea9bd71 in c10::SafePyObject::ptr(c10::impl::PyInterpreter const*) const ()
   from /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so
#1  0x00007fc38bbcb0af in pybind11::detail::type_caster<c10::SymInt, void>::cast(c10::SymInt, pybind11::return_value_policy, pybind11::handle) () from /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#2  0x00007fc38b1690a1 in pybind11::object pybind11::cast<c10::SymInt&, 0>(c10::SymInt&, pybind11::return_value_policy, pybind11::handle) () from /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#3  0x00007fc38b7001da in THPSize_NewFromSymSizes(at::Tensor const&) ()
   from /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#4  0x00007fc38b7922e1 in THPVariable_get_shape(THPVariable*, void*) ()
   from /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#5  0x000055921a41f9ec in getset_get () at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/descrobject.c:156
#6  0x000055921a3ff844 in _PyObject_GenericGetAttrWithDict ()
    at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/object.c:1238
```
It seems pybind11 is failing to cast the object. Any ideas on why the casting would fail?

**Comment by ezyang** [comment]
I reproed the failed casting and... I have no idea, it's so weird. :( And pybind11's error message is useless

**Comment by ezyang** [comment]
OK, I figured it out; it's because of a faulty assert in the constructor. For some reason pybind11 is suppressing the error.

```
diff --git a/torch/__init__.py b/torch/__init__.py
index ae55f59755..2b113d8529 100644
--- a/torch/__init__.py
+++ b/torch/__init__.py
@@ -204,8 +204,6 @@ class SymInt:
     """
 
     def __init__(self, node):
-        from torch.fx.experimental.symbolic_shapes import SymNode
-        assert isinstance(node, SymNode)
         # This field MUST be named node; C++ binding code assumes that this
         # class has a field named node that stores SymNode
         self.node = node
```

this gets me to 

```
======================================================================
ERROR: test_wrap (__main__.TestDynamicShapes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_dynamic_shapes.py", line 15, in test_wrap
    self.assertTrue(a2.shape[0] == 3)
  File "/raid/ezyang/pytorch-scratch-sidea/torch/fx/experimental/symbolic_shapes.py", line 366, in binary_magic_impl
    other_node = self.node.to_node(other)
AttributeError: 'torch._C._SymNode' object has no attribute 'to_node'
```

which is "we need to bind more methods"

**Comment by ezyang** [comment]
bigger patch comin soon

**Pull request closed without merging**
