### PR TITLE
add basic regex test to detect invalid CompositeExplicitAutograd ops that are implemented with DispatchStub

### PR DESCRIPTION
**Pull request by bdhirsh**
`ghstack` fat-finger, this is a re-do of https://github.com/pytorch/pytorch/pull/61134 with the PR feedback addressed. Reposting the original description:

------

This is a quick-and-dirty test that tries to parse the `aten/` folder to find ops that are implemented using DispatchStub, but are incorrectly marked as `CompositeExplicitAutograd` in native_functions.yaml. It should prevent bugs like https://github.com/pytorch/pytorch/issues/60892.

If we want to land this, I need to wait for <> to land to fix the existing bugs with `linalg_eigh` and `lu_solve`. The test correctly catches them and prints out:
```
AssertionError: 0 != 2 : Attempted to compare the lengths of [iterable] types: Expected: 0; Actual: 2.

Detected an operator that is marked as CompositeExplicitAutograd in native_functions.yaml, but appears to
be implemented using DispatchStub.

detected operators:
lu_solve
linalg_eigh

If you think that this is a false positive add the operator name to IGNORED_OPS in the file test/test_incorrect_dispatch_key_ops.py.
A common false positive is if you wrote your operator `at::native::{op}` as a wrapper that calls into
`at::native::{_op}` to do the real, backend-specific work. In this case, marking {op} with
CompositeExplicitAutograd and {_op} with CPU,CUDA is completely valid.
```

Quick note about the false positives: I added some more detail in the test comments, but an example false positive is `cumprod`. `at::native::cumprod` is correctly marked as `CompositeExplicitAutograd`, because (a) is has a derivative formula defined, and (b) `at::native::cumprod` is implemented by calling into `at::_cumprod` for the "real" work, making it backend-agnostic.

`_cumprod` is correctly marked as CPU/CUDA in native_functions.yaml, since it uses DispatchStub - but the function it calls is `cumprod_stub` - and since I'm relying on naming conventions to parse for problems, that shows up as a false positive.

Right now I have an allow list of false positives for the test to ignore.

Maybe... I should just update those false positive ops to follow the naming convention, e.g. call `_cumprod_stub`? Or detect the weird case where `{op}` is composite, but `_{op}` is not, and ignore that?

Either way, if this test goes into CI, there's some likelihood that it'll pick up false positives - The hope is that this catches enough bugs to be worth any of the flakiness.

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #62000 avoid needing to clear cache in gen_backend_stubs tests
* **#61295 add basic regex test to detect invalid CompositeExplicitAutograd ops that are implemented with DispatchStub**
* #61133 fix eig.e bug - it uses DispatchStub and therefore isn't backend agnostic

Differential Revision: [D29561063](https://our.internmc.facebook.com/intern/diff/D29561063)

### CODE REVIEW

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29561063).

**Review by ezyang — APPROVED** [review]

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29561063).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29561063).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29561063).

**Pull request closed without merging**
