### PR TITLE
cleanup unused include

### PR DESCRIPTION
**Pull request by cyyever**
Using `include-what-you-use` tool to find out and remove some unused includes

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Looks good to me, though it would be good to add an explanation what tool/methodology was used to decide that those are unused (by branch name I guess it was include-what-you-use? )
Also, would be really great to add it as a linter rule in the followup PR

**Comment by cyyever** [comment]
Of course I use include what you use. Lint option is being considered. Once I have time to do it..

**Comment by malfet** [comment]
> Of course I use "include what you use". Lint option is being considered. Once I have time to do it..

It would be good to include in PR description, so that folks looking at it a few years from now would not how it is done.

**Pull request closed without merging**
