### PR TITLE
add python binding for _get_current_graph_task_keep_graph

### PR DESCRIPTION
**Pull request by bdhirsh**
Inductor would like a way to have activations that do not escape the backward graph marked as "donated", so we can re-use their memory during memory planning here: https://github.com/pytorch/pytorch/pull/130580

For this to be safe though, we need to know at runtime that autograd does not plan to retain the current autograd graph (either for another call to .backward() later, or if double backward is being used). In the linked PR, the current plan is to error when we detect this situation, and ask the user to turn off the donated buffer config (although if/once we get to the point of always delaying backward compilation to runtime, we can just wait until we know the runtime value to compile).

There isn't a way to know if the currently running backward is run with `retain_graph=True` from python - @soulitzer helped me figure out where to grab it so I added a python binding for it under `ctx.is_retain_graph()`

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #131481
* #131554
* #131665
* #131482
* #131403
* __->__ #131038

### CODE REVIEW

**Review by soulitzer — COMMENTED** [review]
Thanks for the update! The idea sounds good - 

But I would prefer this to be a general API like `torch._C._get_current_graph_task_keep_graph()` rather than something autograd Function specific (since retain_graph relates to backward execution in general rather than autograd Function specifically).

**Comment by albanD** [comment]
btw another thing we could do here is to have a `ctx.access_saved_tensors_once = False` that, when the user sets it to true, will assume a single call to `ctx.saved_tensors` will happen.
It would thus be safe to clear the saved_tensors instantly on the Node if retains graph is False.

That might be a more user friendly API for custom Function writers :)

**Comment by bdhirsh** [comment]
> btw another thing we could do here is to have a ctx.access_saved_tensors_once = False that, when the user sets it to true, will assume a single call to ctx.saved_tensors will happen.
It would thus be safe to clear the saved_tensors instantly on the Node if retains graph is False.

@albanD I don't think I follow - if a user then specifies `retain_graph=True`, wouldn't that **require** the saved tensors to be accessed more than once, if the user calls backward multiple times (overriding the user's intent)? It seems like whoever is calling backward gets to choose how many times saved variables are accessed, not the author of the custom autograd.Function. LMK if I misunderstood.

> But I would prefer this to be a general API like torch._C._get_current_graph_task_keep_graph()

sounds good - I can update to this later this week!

**Comment by albanD** [comment]
@bdhirsh the multiple use we're worried about here is if the user does:
```
def backward(ctx, ...)
   x, = ctx.saved_tensors
   ...
   y = ctx.saved_tensors
   ...
   return ...
```

If the user guarantees that within a single call to their custom backward there is a single call to saved_tensors. Then we can safely free things once they've been accessed (when not in retain_graph).

**Comment by soulitzer** [comment]
> btw another thing we could do here is to have a `ctx.access_saved_tensors_once = False` that, when the user sets it to true, will assume a single call to `ctx.saved_tensors` will happen. It would thus be safe to clear the saved_tensors instantly on the Node if retains graph is False.
> 
> That might be a more user friendly API for custom Function writers :)

This is would be a nice API to reduce peak memory! I guess the idea is that even though our docs do specify that users should not call ctx.saved_tensors twice, it would be somewhat BC breaking to change this behavior now.

I'm not sure I have enough context about the donated buffers use case to understand whether that can be used there though.

**Comment by albanD** [comment]
Ho @soulitzer if you want to make that the default with a flag to allow multiple calls, that sounds fair to me as well. I do expect it to work for most people for sure and give quite a bit of benefit. But it will be BC-breaking. But if you're happy to make that change in a smooth way, sounds good to me!

**Review by soulitzer — APPROVED** [review]
LGTM, thanks!

**Pull request closed without merging**
