### PR TITLE
Fix some tensor operators to return `NotImplemented` for invalid inputs

### LINKED ISSUE #57719: Some `torch.Tensor` operators don’t return `NotImplemented` for invalid inputs
## 🐛 Bug

Some torch.Tensor operators
1. don’t return `NotImplemented` and raise `TypeError`, or
2. are not defined whereas expected to be defined.

(cc/ @mruberry, @emcastillo, @kmaehashi)

## To Reproduce

1. For example, in the following case, we expect `torch.Tensor.__pow__` returns `NotImplemented` and `A.__rpow__` is called
```py
>>> class A:
...     def __init__(self, x):
...         self.x = x
...     def __radd__(self, other):
...         print('A.radd')
...     def __rpow__(self, other):
...         print('A.rpow')
...
>>> torch.tensor([1]) + A(1)
A.radd
>>> torch.tensor([1]) ** A(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: pow() received an invalid combination of arguments - got (A), but expected one of:
 * (Tensor exponent)
      didn't match because some of the arguments have invalid types: (A)
 * (Number exponent)
      didn't match because some of the arguments have invalid types: (A)
```

The expected behavior is:
```py
>>> torch.tensor([1]) + A(1)
A.radd
>>> torch.tensor([1]) ** A(1)
A.rpow
```

2. The following example shows that `torch.Tensor.__rand__` is not registered
```py
>>> torch.tensor([1]) & 1
tensor([1])
>>> 1 & torch.tensor([1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for &: 'int' and 'Tensor'
```

The expected behavior is:
```py
>>> torch.tensor([1]) & 1
tensor([1])
>>> 1 & torch.tensor([1])
tensor([1])
```

## Environment

 - PyTorch 1.8.1+cu102 installed via pip
 - OS: Linux
 - Python version: 3.9.1

## Additional context

This issue is found on https://github.com/pytorch/pytorch/pull/56997.

### PR DESCRIPTION
**Pull request by asi1024**
Fixes #57719.

This PR fixes `torch.Tensor{__rsub__, __rdiv__, __rtruediv__, __pow__, __rmatmul__}` to return `NotImplemented` instead of raising a `TypeError`.

cc/ @mruberry: The first commit of this PR is the same as https://github.com/pytorch/pytorch/pull/56997/commits/1d209db1cc624fbbe99eee5c82b7b68273c1666e excepts the commit message.

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Thanks for the PR that looks quite good.
I am not sure what test_binary_ufuncs is testing for these. In particular, does it properly cover all the reverse cases and make sure they return the right value?

**Comment by asi1024** [comment]
@albanD Thank you for your review!
I implemented `__rmatmul__` method in `_tensor.py` to handle the reverse version properly, and also add a test! Could you take another look? :smiley:

**Comment by albanD** [comment]
Thanks for the update.
I think you can leave it here as it is not too big.

Could you make sure that the CI in green (in particular, flake is not happy with the assert False, you can replace it with raise RuntimeError...).
Also looks like your rmatmul implementation goes into an infinite recursion.

**Comment by mruberry** [comment]
I suggest just updating those that are easiest for the tests to pass and leaving a comment in the code about the remainders. This is a nice code cleanup but few users will appreciate the change

**Review by albanD — APPROVED** [review]
LGTM thanks for the tests

**Comment by asi1024** [comment]
Thanks!

**Comment by albanD** [comment]
I'm afraid this broke some master-only CI builds: https://app.circleci.com/pipelines/github/pytorch/pytorch/320932/workflows/2a61be9b-ecad-475b-bb9a-0c03b6c97d71/jobs/13402438

I think bfloat16 should be added to the cuda types.

Could you send a new PR with the same content as this one + the bfloat16 dtype on cuda?

**Comment by asi1024** [comment]
@albanD I reopened a PR in #58216!

**Pull request closed without merging**
