### PR TITLE
[quantization] Adding aliased modules from nn to nn.quantized

### PR DESCRIPTION
**Pull request by z-a-f**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#27351 [quantization] Adding aliased modules from nn to nn.quantized**

Differential Revision: [D17755356](https://our.internmc.facebook.com/intern/diff/D17755356)

### CODE REVIEW

**Comment by zafartahirov** [comment]
This is just the pooling -- still need to do other parts (i.e. upsampliing)

**Review by dzhulgakov — COMMENTED** [review]
hm, I'm not sure we actually want to create separate class types if the original nn.Modules were working just fine. Since they are different classes - which one should I use? Why not just update docstrings for the original classes?

@gchanan for opinion

**Comment by zafartahirov** [comment]
> hm, I'm not sure we actually want to create separate class types if the original nn.Modules were working just fine. Since they are different classes - which one should I use? Why not just update docstrings for the original classes?
> 
> @gchanan for opinion

The idea was that we separate the quantized layers into their own namespace even if they are just aliases to the original nn modules. That allows for more control over the documentation. At the same time, I don't have a strong opinion about that -- I can leave it as `QuantizedModule = nn.Module`

**Comment by raghuramank100** [comment]
> > hm, I'm not sure we actually want to create separate class types if the original nn.Modules were working just fine. Since they are different classes - which one should I use? Why not just update docstrings for the original classes?
> > @gchanan for opinion
> 
> The idea was that we separate the quantized layers into their own namespace even if they are just aliases to the original nn modules. That allows for more control over the documentation. At the same time, I don't have a strong opinion about that -- I can leave it as `QuantizedModule = nn.Module`

The issue is that the numerics are different for quantized tensors, i.e
nn.AvgPool2d(xq.dequantize()) is not the same as nn.AvgPool2d(xq).dequantize(), as there is quantization occuring within the module as part of average calculation.  Are we ok with having a single module that has different numerical behavior depending on input dtype?

**Comment by dzhulgakov** [comment]
Same is true for other dtypes - float and double would produce different precision. I don't see really strong argument on why they'd be separate modules. If we really want, we can alias it, but I wouldn't create a separate class, just bind it in another namespace.

**Comment by zafartahirov** [comment]
> Same is true for other dtypes - float and double would produce different precision. I don't see really strong argument on why they'd be separate modules. If we really want, we can alias it, but I wouldn't create a separate class, just bind it in another namespace.

How would we bind it to another namespace? I don't know of any good way. If we do `Module = nn.Module` in quantized folder, inspecting the element will still show that the module is `nn.Module`, not `nn.quantized.Module`

**Comment by dzhulgakov** [comment]
I just don't feel it's right to have two modules that are identical. @gchanan - want to be a tie breaker? :)

**Comment by z-a-f** [comment]
@gchanan friendly bump

**Pull request closed without merging**
