### PR TITLE
[NVFuser] Enable E2E BCast-PWise-Reduction fusions

### PR DESCRIPTION
**Pull request by csarofeen**
Had a bunch of merged commits that shouldn't have been there, reverted them to prevent conflicts. Lots of new features, highlights listed below.

**Overall:**

- Enables pointwise fusion, single (but N-D) broadcast -- pointwise fusion, single (but N-D) broadcast -- pointwise -- single (but N-D) reduction fusion.

**Integration:**

- Separate "magic scheduler" logic that takes a fusion and generates code generator schedule
- Reduction fusion scheduling with heuristics closely matching eagermode (unrolling supported, but no vectorize support)
- 2-Stage caching mechanism, one on contiguity, device, type, and operations, the other one is input size->reduction heuristic

**Code Generation:**

- More generic support in code generation for computeAt
- Full rework of loop nest generation and Indexing to more generically handle broadcast operations
- Code generator has automatic kernel launch configuration (including automatic allocation of grid reduction buffers)
- Symbolic (runtime) tilling on grid/block dimensions is supported
- Simplified index generation based on user-defined input contiguity
- Automatic broadcast support (similar to numpy/pytorch semantics)
- Support for compile time constant shared memory buffers
- Parallelized broadcast support (i.e. block reduction -> block broadcast support)

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by jjsjann123** [comment]
Is it still failing the internal build, looks like it's stuck there.

**Comment by soumith** [comment]
no, it was landing, it's done now.

**Comment by ezyang** [comment]
It seems like this broke https://circleci.com/gh/pytorch/pytorch/6775624?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

**Comment by jjsjann123** [comment]
Looks like it's the hash on enum class.
I can try to patch it. How can I verify a fix as I don't have a repro on my machine (nor in the CI)?

**Comment by jjsjann123** [comment]
PR issued. #43222

**Pull request closed without merging**
