### PR TITLE
[pytorch] add new macro TORCH_MOBILE for libtorch mobile build

### PR DESCRIPTION
**Pull request by ljk53**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #19762 [pytorch] CMakeLists changes to enable libtorch for Android
* #19942 [pytorch] rename BUILD_ATEN_MOBILE to INTERN_BUILD_MOBILE and make it private
* **#19761 [pytorch] add new macro TORCH_MOBILE for libtorch mobile build**
* #19760 [pytorch] fix labs warning in THTensorMoreMath.cpp

Summary:
Libtorch mobile build needs (aten_)interned_strings to support all aten operators, which
is currently disabled by C10_MOBILE macro.

C10_MOBILE macro is defined for all mobile builds, including caffe2 mobile build used in
facebook production and libtorch mobile build we are currently working on, so choices are:
1. Remove C10_MOBILE macro from (aten_)interned_strings, which might regress production build size;
2. Add a new macro to override C10_MOBILE in this specific case, which will increase codebase complexity;

We decided to take #2 for now and commit to limit its uses and eventually remove it when things
like interned_strings can be modularized.

Test Plan:
- Make sure this diff doesn't regress any internal build size;
- Build with stacked diffs;

Differential Revision: [D15087652](https://our.internmc.facebook.com/intern/diff/D15087652)

### CODE REVIEW

**Comment by dzhulgakov** [comment]
There are other places where C10_MOBILE is used. Maybe a cleaner solution is to make C10_MOBILE mean any mobile build (or come up with another name) and introduce C10_MOBILE_MINIMAL that strips off more parts.

**Comment by ljk53** [comment]
> There are other places where C10_MOBILE is used. Maybe a cleaner solution is to make C10_MOBILE mean any mobile build (or come up with another name) and introduce C10_MOBILE_MINIMAL that strips off more parts.

In this diff the new marco is adding to (instead of removing from) what C10_MOBILE normally builds, so it should be called C10_MOBILE_FULL if we want to use C10 naming. Or are you suggesting to rename existing C10_MOBILE to C10_MOBILE_MINIMAL?

**Review by dzhulgakov — APPROVED** [review]
It'd be nice to distinguish "platform" flags (C10_MOBILE) and "build features" flags (TORCH_MOBILE) in naming. Maybe prepend it with FEATURE_ or something?

But otherwise, it's good to go. Renaming C10_MOBILE (suggested earlier) is probably fine to skip to avoid confusion

**Comment by ljk53** [comment]
@dzhulgakov renamed to "FEATURE_TORCH_MOBILE"; also commented its purpose per request by @dreiss.

**Pull request closed without merging**
