### PR TITLE
Support bool input tensors for argmax and other functions

### LINKED ISSUE #35529: Support bool input tensors for argmax and other functions
argmax and other functions make sense for finding position of True element

```
In [16]: torch.__version__
Out[16]: '1.5.0.dev20200310'
```

```
In [11]: torch.ones(3, dtype = torch.bool).argmax()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/convasr/ot/vis.py in <module>
----> 1 torch.ones(3, dtype = torch.bool).argmax()

RuntimeError: "argmax_cpu" not implemented for 'Bool'

In [12]: torch.ones(3, dtype = torch.bool).argmin()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/convasr/ot/vis.py in <module>
----> 1 torch.ones(3, dtype = torch.bool).argmin()

RuntimeError: "argmin_cpu" not implemented for 'Bool'

In [13]: torch.ones(3, dtype = torch.bool).argsort()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/convasr/ot/vis.py in <module>
----> 1 torch.ones(3, dtype = torch.bool).argsort()

RuntimeError: _th_sort not supported on CPUType for Bool

In [14]: torch.ones(3, dtype = torch.bool).topk(1)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/convasr/ot/vis.py in <module>
----> 1 torch.ones(3, dtype = torch.bool).topk(1)

RuntimeError: "topk_cpu" not implemented for 'Bool'

In [15]: torch.ones(3, dtype = torch.bool).sort()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/convasr/ot/vis.py in <module>
----> 1 torch.ones(3, dtype = torch.bool).sort()

RuntimeError: _th_sort not supported on CPUType for Bool
```

### PR DESCRIPTION
**Pull request by Kiyosora**
Fixes #35529
This PR aims to remove the restrictions on Boolean input tensors for the following operators:
`torch.sort` / `torch.msort` / `torch.argsort` / `torch.argmax` / `torch.argmin` / `torch.topk`

cc @ngimel

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Related: https://github.com/pytorch/pytorch/issues/35529

**Comment by Kiyosora** [comment]
> Fixes #35529 ?

Yes, I'm trying to fix it 😃

**Comment by vadimkantorov** [comment]
@gchanan would be unfortunate if simply un-reviewed PRs get closed because of false-staleness....

**Comment by ngimel** [comment]
Now that there's `view(dtype)` all these requests have an easy workaround.

**Comment by vadimkantorov** [comment]
Yep, now it's less problematic, but for consistency it'd be much better for these ops to support booltensors natively...

**Comment by CloudyDory** [comment]
> Now that there's `view(dtype)` all these requests have an easy workaround.

@ngimel But it seems that `view(dtype)` changes the size of the tensor, if the element size of `dtype` is different from the original dtype. So how can the correct index be obtained in this case?

**Pull request closed without merging**
