### PR TITLE
[NVFuser] Upstream push 0714

### PR DESCRIPTION
**Pull request by jjsjann123**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #81861

Syncing nvfuser devel branch to upstream master. https://github.com/csarofeen/pytorch/

Code changes includes:

- codegen improvements:
  1. Indexing refactor -> Remove reference tensor in predicate indexing logic
  2. MMA Rfactor support for cross-warp and cross-CTA split on K dimension
  3. Grouping grid allreduces across iterations
  4. Swizzle op formulation for non-affine swizzles
  5. Use scheduler_utils to cache inputs and outputs in schedulePointwise
- scheduler refactor
  1. New compute at interface
- transformation propagation refactor on MaxInfoSpanningTree
  1. Added sibling path that is required to generate consistent replay for some cases where `MaxInfoSpanningTree` is used with a selector.
  2. Optimization to skip Transform propagator
  3. SpanningTreePrinter for debugging
- parser update
  1. Fixes `div`
  2. Added `_to_copy`
  3. Broadcast in dim with expand to support expanding to concrete size
  4. Dropout prob extremal patch
- executor patch on caching strides for output allocation

Squashed commits to WAR github API
Commits that's actually in this PR from the devel branch:

```
3b87896706fc98aa4d5b5c811af034cc4dddfbab Fix allocation of work buffers and `fused_reduction::ParallelReduce` with unswitch (#1818)
4cae1227f666b68d275144afd6e4be1fa7aa0786 schedulePointwise cleanup: - computeAt + InlinePropagator (#1815)
3df97426adfb5ecc6fe2c12c43d56d59670e5020 Use scheduler_utils to cache inputs and outputs in schedulePointwise (#1811)
03180aa8facde51237dffa29f6632ffa870cf923 improve broadcast resolution (#1792)
bee6c69979d8c34d6d6ef7514f8886cf1416d64f bug fix (#1819)
4413c8f43a5a64dd0a6ddb0763523bbc7314f4b5 Support PYTORCH_NVFUSER_DUMP=transform_propagator (#1812)
de6b7ca5ce755061ae0d26e006c4403653627ab5 Fix negative position in InlinePropagator (#1813)
10a996cb4dce5d514f09fd0d49ffcd3b88869a28 Remove redundant check in schedulePointwise (#1810)
acd5ed4df825d4c25999e8c9041e0f8ca1a3448f Swizzle op formulation for non-affine swizzles (#1441)
3ed8330f881f429fe2df0e5af9000b91355a96da Kernel args patch to show zero_init buffer (#1809)
037a75a42048f1d8a9c30efb466f1ffbfd2894ad Dropout prob extremal patch (#1804)
282c42902bff07f759cddbbe619249cf5e7c5281 spam nvrtc options (#1783)
3ba6a5fe0a47044179cd36b5b62e628c75180da5 Broadcast in dim with expand (#1794)
fd4be1236ddfeb31ca0659e1b0df36546424c979 remove dead indexing code (#1806)
fa4e6a4739a9daaa0e4111fb4730704d79c91010 Check siblings in getMaxPosAll (#1805)
025c840c76d89b0d032b65a78a375719cab78d46 Grouping grid allreduces across iterations (#1755)
37c579e64f8145fc292273cdebb6519edeb9cf76 Temporarily disable test requring large shared memory. (#1802)
5f375d074524ab65cb78282eff7abe5846cc4203 More cleanup on InlinePropagator (#1800)
8d384da0cfb50a7c5082e91585c12f4c3a775e6c Indexing refactor stage 2 : Remove reference tensor in predicate indexing logic (#1784)
f008140e26335584a143f71c2cb9e91fd61ec530 MMA Rfactor support for cross-warp and cross-CTA split on K dimension (#1554)
76b3cca5cc9a18a56db8107d2f6c8e94851bb85c Add parsing support for `_to_copy` to handle AMP casts. (#1756)
ef04f6c4c0ee043979ac7aad4e5be6f22faeb547 Coding style cleanups (#1798)
38c7f3cf69ea58cc9480b0621506bbfd90a7c9d3 InlinePropagator please don't replay (#1797)
3f2c263ade35017be2d99fe8e4ec97fd0f14f754 validateDomain in TransformPropagator (#1796)
c07708520d99ef815ce15ec367bf7e98797d602b Use TransformPropagatorWithCheck in many tests (#1795)
d0d0908aee2e2b7615c28d04ee80a54b01a02bcd Some further cleanup for the new computeAt interface (#1793)
45f5203b5744cd3512d83263b3fb07c99795a271 Fix TransformReplay::getMatchedLeafPosWithoutReplay* (#1791)
28cbaf931870086cf59807dd60ce412d6dfad0fd New compute at interface (#1743)
635ebfc79bc016eea94d4cbde2c12324171b908b Add SpanningTreePrinter (#1786)
59f3c3223c48ea89549fe7d323f17cbecbebede0 Output allocate patch (#1790)
fe93bf5a6485696ffb36751606a84080349967b5 Transform propagator skip replay when possible (#1782)
ebf23a50f3adf3d28e824c3b3b4ed6ea6f9cf483 Fix isIntegralType error msg (#1789)
0c82ecf04d12b9fe5428af6824a7a978cf5e0ddd Disable register reuse across serial broadcast ops (#1787)
33a824d8d9ace7790a4a58d497e525a7a059579d Adding sibling path for MaxInfoSpanningTree (#1776)
86f46aad83cbb2aa06943419a7335d71a8798f2a Fix div(Val, TensorView) (#1778)
d3de227ade763bdac9e9df15ba8671be78565ee9 Fix FusionMaxRootDomainInfoSpanningTreePrintTwice_CUDA (#1781)
ecc7a87cdaaed66672d08bf819ad58d2980384cb Extend mma dimension and layout checking to support strided batched matmul and tensor contractions (#1761)
```

RUN_TORCHBENCH: nvfuser

Differential Revision: [D38043938](https://our.internmc.facebook.com/intern/diff/D38043938)

### CODE REVIEW

**Comment by jjsjann123** [comment]
Hopefully this time it will allow me to run torchbench~~~

**Comment by davidberard98** [comment]
@jjsjann123 looks like there are some failures in the prim executor tests

and - not sure why the torchbench test got skipped here...

**Comment by jjsjann123** [comment]
> @jjsjann123 looks like there are some failures in the prim executor tests
> 
> and - not sure why the torchbench test got skipped here...

I've been looking at those failures and they do seem real. Need to repro and fix them before merging.
torchbench skip is strange... maybe because i started the PR with ghstack and only put the torchbench in description after the CI started?
Would need to rebase for the fix later, we'll see if torchbench would be triggered then.

**Comment by davidberard98** [comment]
@jjsjann123 good idea, try adding the torchbench tag to the commit message

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38043938).

**Comment by jjsjann123** [comment]
turns out it's my bug in broadcast_in_dim.... have that patched and verified the fix locally~

**Comment by jjsjann123** [comment]
hmmm... why is this same test still failing in MSVC??!?!?! I have it patched and the test passed locally already....


```
022-07-21T20:53:07.7768504Z ================================== FAILURES ===================================
2022-07-21T20:53:07.7768978Z _ TestCommonCUDA.test_python_ref_executor__refs_nn_functional_layer_norm_executor_nvfuser_cuda_float32 _
2022-07-21T20:53:07.7769459Z [gw2] win32 -- Python 3.8.13 C:\Jenkins\Miniconda3\python.exe
2022-07-21T20:53:07.7769765Z Traceback (most recent call last):
2022-07-21T20:53:07.7784267Z   File "C:\actions-runner\_work\pytorch\pytorch\test\test_ops.py", line 541, in test_python_ref_executor
2022-07-21T20:53:07.7784828Z     self._ref_test_helper(
2022-07-21T20:53:07.7785259Z   File "C:\actions-runner\_work\pytorch\pytorch\test\test_ops.py", line 400, in _ref_test_helper
2022-07-21T20:53:07.7785796Z     ref_result = op(sample.input, *sample.args, **sample.kwargs)
2022-07-21T20:53:07.7786771Z   File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_methods_invocations.py", line 953, in __call__
2022-07-21T20:53:07.7787525Z     return self.op(*args, **kwargs)
2022-07-21T20:53:07.7787980Z   File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\_prims\executor.py", line 70, in _traced
2022-07-21T20:53:07.7788752Z     return execute(gm, all_args, executor=executor)
2022-07-21T20:53:07.7789235Z   File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\_prims\executor.py", line 21, in execute
2022-07-21T20:53:07.7789647Z     return nvfuser_execute(gm, *args)
2022-07-21T20:53:07.7790120Z   File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\_prims\nvfuser_executor.py", line 122, in nvfuser_execute
2022-07-21T20:53:07.7790611Z     fusion.execute(concrete_fusion_inputs),  # type: ignore[has-type]
2022-07-21T20:53:07.7791151Z RuntimeError: Attempting to bind 1 to 2but it's already set to 1
2022-07-21T20:53:07.7791656Z ============================== warnings summary ===============================


2022-07-21T20:53:10.6570690Z RuntimeError: test_ops failed!
```

**Comment by davidberard98** [comment]
restarted the trunk jobs

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38043938).

**Comment by jjsjann123** [comment]
Win failure seems real... I have it reproed on my local machine, where I see the fix in effect and changing the fusion graph, but hitting the same failure while ubuntu build succeeded...
Let me try to figure out why...

**Comment by jjsjann123** [comment]
patched the failure. Still not quite sure about the root cause of inconsistent segmentation on MSVC, I'm tracking that here: https://github.com/csarofeen/pytorch/issues/1859

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38043938).

**Comment by jjsjann123** [comment]
> Warning: Failed to download action 'https://api.github.com/repos/pytorch/pytorch/tarball/0985188c8fa2ffe8cba7c8a1bd32ec6d045940d3'. Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Warning: Back off 18.91 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/pytorch/pytorch/tarball/0985188c8fa2ffe8cba7c8a1bd32ec6d045940d3'. Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Warning: Back off [26](https://github.com/pytorch/pytorch/runs/7483421285?check_suite_focus=true#step:1:27).655 seconds before retry.

failed cases were saying some timeout issue, I guess it's not related?!

**Comment by davidberard98** [comment]
@jjsjann123 11% regression on nvfuser:autogen-5 (see the torchbench CI job) - can you take a look? (I can land it first if that's easier). Could just be flaky.

**Review by davidberard98 — APPROVED** [review]

**Comment by jjsjann123** [comment]
I'm surprised that I don't see any conflict with #81578 merged. :crossed_fingers:

**Comment by davidberard98** [comment]
@jjsjann123 I tried manually and it fails with a merge conflict, so it would probably fail when trying to merge. Can you rebase? (& ping me when it is ready so I can re-import to internal codebase)

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38043938).

**Comment by jjsjann123** [comment]
Thx for the quick import.
I'm still awaiting on my build to finish, will post if I found any issue locally~~

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38043938).

**Comment by jjsjann123** [comment]
Local tests passed~~ yay~~ we should be good this time.

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38043938).

**Comment by davidberard98** [comment]
started the merge internally

**Pull request closed without merging**
