### PR TITLE
[ROCm] Fix error in torch.cuda initialisation if amdsmi is not available

### PR DESCRIPTION
**Pull request by jataylo**
Reported in https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15874 

When nvml_count is set via https://github.com/pytorch/pytorch/blob/9f73c65b8f644d599ff3ff53927b738cfbb7d191/torch/cuda/__init__.py#L834

If amdsmi is not available this will throw an error
```
File "python3.10/site-packages/torch/cuda/__init__.py", line 634, in _raw_device_count_amdsmi
    except amdsmi.AmdSmiException as e:
NameError: name 'amdsmi' is not defined
```

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang

### CODE REVIEW

**Comment by jataylo** [comment]
Hey @jithunnair-amd this will resolve the issue that was raised. There are still APIs that if used will throw an error if amdsmi is not installed but need to be called explicitly from the workload e.g. https://github.com/pytorch/pytorch/blob/9f73c65b8f644d599ff3ff53927b738cfbb7d191/torch/cuda/__init__.py#L994, similar handling is already done on nvml side.

**Review by jeffdaily — APPROVED** [review]

**Comment by jataylo** [comment]
Hey @eqy, @malfet could we get some upstream approval for this bug fix?

**Review by eqy — APPROVED** [review]

**Comment by jataylo** [comment]
Ahh I thought @eqy's approval was enough to merge. @malfet, @ngimel could you take a look at this when possible.

**Comment by jataylo** [comment]
Rebasing for unrelated failures

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
@malfet @atalman 
Can you please review and approve this PR.

**Review by atalman — APPROVED** [review]

**Pull request closed without merging**
