### PR TITLE
fix mkldnn quantization issue for weight reorder error

### PR DESCRIPTION
**Pull request by XiaobingSuper**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #86876

Differential Revision: [D40351062](https://our.internmc.facebook.com/intern/diff/D40351062)

For mkldnn quantization path, we will do weight prepack using dummy data to query the expected weight format, the packed weight's format may differ from the real input case(the weight format depends on the input's shape), and there will have a block weight to block weight reorder if the packed weight format differs with the expected weight format.  The mkldnn may meet the following issue when doing such reorder(test on ICX machine):

```
test_conv_reorder_issue_onednn
    torch.ops.quantized.conv2d(qx, w_packed, output_scale=1.0, output_zero_point=0)
  File "/home/weiwen/.conda/envs/int8-dev/lib/python3.9/site-packages/torch/_ops.py", line 472, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: could not create a primitive descriptor for a reorder primitive
```

This PR will fix it: if the block weight to block weight reorder is failed, we will reorder the block weight to plain weight first, and then reorder the plain weight to the target block weight.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @VitalyFedyunin @mingfeima @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40351062).

**Comment by jerryzh168** [comment]
@XiaobingSuper I have confirmed with my colleague that we can land this first, could you publish this draft PR?

**Comment by jerryzh168** [comment]
could you 1. clean up the fix 2. split the changes to default to a separate PR?

**Comment by XiaobingSuper** [comment]
> could you 1. clean up the fix 2. split the changes to default to a separate PR?

Done, please help review it.

**Review by jgong5 — APPROVED** [review]
The change LGTM but could you please add the description the suspected issue and how the change addresses it?

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40351062).

**Comment by XiaobingSuper** [comment]
@jerryzh168 , could you help see the internal failed test case? I can't access it.

**Comment by jerryzh168** [comment]
@XiaobingSuper can you add a test for this?

**Comment by Xia-Weiwen** [comment]
> @XiaobingSuper can you add a test for this?

Hi @jerryzh168 . We cannot reproduce the issue on our side thus difficult to create a case here. Could you share the case from the customer?

**Comment by XiaobingSuper** [comment]
> reproduce

A test case is added. @@jerryzh168

**Comment by vkuzo** [comment]
Could we add some more context on what the issue was, which hardware the issue affects, and how this PR is fixing it?  Also, to clarify, the test fails before this PR and passes after?

**Comment by XiaobingSuper** [comment]
> Could we add some more context on what the issue was, which hardware the issue affects, and how this PR is fixing it? Also, to clarify, the test fails before this PR and passes after?

@vkuzo , I add more context to descript the issue, please help see it.

**Comment by XiaobingSuper** [comment]
@jerryzh168, could we land it?

**Comment by jerryzh168** [comment]
sure, will try landing this again

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40351062).

**Review by jerryzh168 — APPROVED** [review]

**Comment by jerryzh168** [comment]
@XiaobingSuper could you rebase the PR on master?

**Comment by XiaobingSuper** [comment]
> @XiaobingSuper could you rebase the PR on master?

rebased.

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40351062).

**Comment by XiaobingSuper** [comment]
@jerryzh168 , please help land it if it is ok for you.

**Comment by jerryzh168** [comment]
> @jerryzh168 , please help land it if it is ok for you.

trying to land, just need to make sure CI is green

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40351062).

**Pull request closed without merging**
