### PR TITLE
[export] Support torch.sym* ops

### LINKED ISSUE #108830: torch._export.pass_base.ExportPassBaseError: Unsupported target type: <function sym_min at 0x7ff25dd10670>
### 🐛 Describe the bug

sym_min/sym_max appear not to be supported by torch.export.export (but they are supported by torch._dynamo.export)

```
  File "/data/users/ezyang/b/pytorch/torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "/data/users/ezyang/b/pytorch/torch/_export/pass_base.py", line 232, in run_node
    return super().run_node(n)
  File "/data/users/ezyang/b/pytorch/torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/data/users/ezyang/b/pytorch/torch/_export/pass_base.py", line 209, in call_function
    raise ExportPassBaseError(f"Unsupported target type: {target}")
torch._export.pass_base.ExportPassBaseError: Unsupported target type: <function sym_min at 0x7ff25dd10670>

While executing %sym_min : [num_users=1] = call_function[target=torch.sym_min](args = (%sym_size, 1000), kwargs = {})
Original traceback:
  File "/data/users/ezyang/b/torchvision/torchvision/models/detection/retinanet.py", line 660, in forward
    detections = self.postprocess_detections(split_head_outputs, split_anchors, images.image_sizes)
  File "/data/users/ezyang/b/torchvision/torchvision/models/detection/retinanet.py", line 536, in postprocess_detections
    scores_per_level, idxs = scores_per_level.topk(num_topk)
```

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi 

### Versions

main

### PR DESCRIPTION
**Pull request by angelayi**
Fixes https://github.com/pytorch/pytorch/issues/108830 and https://github.com/pytorch/executorch/issues/1379#issuecomment-1853322866

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by zhxchen17 — APPROVED** [review]
We should seriously consider moving things off ExportPassBase!

**Comment by angelayi** [comment]
> We should seriously consider moving things off ExportPassBase!

Executorch still uses it tho

**Comment by atalman** [comment]
@angelayi Please rebase your pr and wait for signal
I see following errors on HUD:
```
_____________ RetraceExportTestExport.test_sym_sqrt_retraceability _____________
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/export/test_export.py", line 1944, in test_sym_sqrt
    ep = export(M(), (torch.ones(16, 4),), dynamic_shapes={'x': {0: Dim("dim")}})
  File "/var/lib/jenkins/workspace/test/export/test_retraceability.py", line 12, in mocked_retraceability_export
    ep = export(ep, *(args[1:]), **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/export/__init__.py", line 185, in export
    constraints = _process_dynamic_shapes(f, args, kwargs, dynamic_shapes)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/export/dynamic_shapes.py", line 465, in _process_dynamic_shapes
    for tensor, shape in tree_zip(combined_args, dynamic_shapes):
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/export/dynamic_shapes.py", line 370, in tree_zip
    yield from tree_zip(combined_args[k], shape)
KeyError: 'x\n\nTo execute this test, run the following from the base repo dir:\n     python test/export/test_retraceability.py -k test_sym_sqrt_retraceability\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'
```

**Pull request closed without merging**
