### PR TITLE
[tools] Parallelize tools/clang_format_new.py

### PR DESCRIPTION
**Pull request by SplitInfinity**
**Summary**
This commit parallelizes the invocation of `clang-format` on all files
in `tools/clang_format_new.py` using `asyncio`.

**Testing**
Ran and timed the script.

*Before*
```
$ time ./tools/clang_format_new.py  --diff
...
real	0m7.615s
user	0m6.012s
sys	0m1.634s
```

*After*
```
$ time ./tools/clang_format_new.py  --diff
...
Some files not formatted correctly

real	0m2.156s
user	0m8.488s
sys	0m3.201s
```

### CODE REVIEW

**Comment by SplitInfinity** [comment]
Uhh, I must be doing something weird because I'm seeing this in the regular, non-diff mode:
```
/opt/anaconda3/lib/python3.7/asyncio/unix_events.py:867: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
  RuntimeWarning)
```

**Comment by suo** [comment]
ready for review?

**Comment by SplitInfinity** [comment]
Yes. There is that one warning I couldn't figure out how to address. I'm sure it's `asyncio` related because it doesn't happen in `--diff` mode.

**Comment by suo** [comment]
this is my output when I run: https://gist.github.com/suo/47015d5b20c35799d1571a91125faf45

**Comment by SplitInfinity** [comment]
What do you see when you run with `--diff`? Same problem?

For some reason I don't see that on my end but it looks like there are too many processes being created. I guess it makes sense to cap the maximum number of subprocesses?

**Comment by suo** [comment]
yeah, using a semaphore works.

Your other warning is because you don't call `communicate()` on the subprocess shell in `run_clang_format_on_file` so the main program exits with hanging subprocesses

**Review by suo — CHANGES_REQUESTED** [review]
going to request changes to clear this from my queue

**Comment by SplitInfinity** [comment]
- Added `wait` for subprocess in `run_clang_format_on_file`
- Added `asyncio.Semaphore` to cap the maximum number of concurrent formatting processes

**Review by suo — APPROVED** [review]
lgtm

**Pull request closed without merging**
