### PR TITLE
[ROCM] Enable Sparse Pickle Test

### PR DESCRIPTION
**Pull request by jpvillam-amd**
Missed stream context for serialization

### Description
Missing ROCm stream context on memory operations for serialization 

### Testing
Ran the sparse pickle test

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
Lint is still real though?

**Comment by jithunnair-amd** [comment]
@jpvillam-amd Please rebase (bot command may not work since source branch is from your fork) and then try the bot merge command

**Comment by jpvillam-amd** [comment]
hmm some CI seems to be stuck after the rebase yesterday

**Comment by jpvillam-amd** [comment]
@jithunnair-amd  There you go, after enough rebasing 😆

**Comment by jpvillam-amd** [comment]
This is the error from the failed test:    
``` torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
FINISHED PRINTING LOG FILE of inductor/test_torchinductor_opinfo (/var/lib/jenkins/workspace/test/test-reports/inductor-test_torchinductor_opinfo_97r3yha2)
```

**Pull request closed without merging**
