### PR TITLE
[Torch] Default to IPv6 on listen

### PR DESCRIPTION
**Pull request by osalpekar**
Summary: Updating PyTorch Distributed network utilities to try binding to IPv6 addresses by default and then falling back on IPv4.

Differential Revision: D24969149

### CODE REVIEW

**Comment by Babar** [comment]
@gunandrose4u: I'm having a really hard time debugging this through CircleCI, and I do not have access to a window machine where I could debug this easily. As you wrote this support in the first place, maybe you can help me debug it?
My guess is that I've now fixed the listening part of the store, but not the client part, therefore we time out waiting to connect as it never manages to. When this happened on Linux, it was because `getaddrinfo` returned yet another error code I had not considered (`EAI_ADDRFAMILY` iirc). I've added that one as per the doc, but...

**Comment by gunandrose4u** [comment]
> @gunandrose4u: I'm having a really hard time debugging this through CircleCI, and I do not have access to a window machine where I could debug this easily. As you wrote this support in the first place, maybe you can help me debug it?
> My guess is that I've now fixed the listening part of the store, but not the client part, therefore we time out waiting to connect as it never manages to. When this happened on Linux, it was because `getaddrinfo` returned yet another error code I had not considered (`EAI_ADDRFAMILY` iirc). I've added that one as per the doc, but...

Sure, let me pull your PR and debug on it.

**Comment by gunandrose4u** [comment]
> > @gunandrose4u: I'm having a really hard time debugging this through CircleCI, and I do not have access to a window machine where I could debug this easily. As you wrote this support in the first place, maybe you can help me debug it?
> > My guess is that I've now fixed the listening part of the store, but not the client part, therefore we time out waiting to connect as it never manages to. When this happened on Linux, it was because `getaddrinfo` returned yet another error code I had not considered (`EAI_ADDRFAMILY` iirc). I've added that one as per the doc, but...
> 
> Sure, let me pull your PR and debug on it.

@Babar , I get the code from TcpStore out and implement two different projects, server and client. With IpV6 address hard coded, the connection success and quick. Can you double check that firewall is allow connection and also ipv6 address and port is right. I met wait to connect till timeout by given a wrong port number.

**Comment by Babar** [comment]
> @Babar , I get the code from TcpStore out and implement two different projects, server and client. With IpV6 address hard coded, the connection success and quick. Can you double check that firewall is allow connection and also ipv6 address and port is right. I met wait to connect till timeout by given a wrong port number.

And can you try running the unit tests? Specifically:
https://github.com/pytorch/pytorch/blob/master/test/distributed/test_c10d.py#L501

Or I guess you should be able to replicate in your test projects by setting the IP address to `127.0.0.1`

**Comment by malfet** [comment]
Windows tests hang while running `python test_c10d.py -v RendezvousEnvTest.test_nominal`
Applying following change fixes the hang:
```
diff --git a/test/distributed/test_c10d.py b/test/distributed/test_c10d.py
index 1ee009ead4..265e1c13d0 100755
--- a/test/distributed/test_c10d.py
+++ b/test/distributed/test_c10d.py
@@ -500,7 +500,7 @@ class RendezvousEnvTest(TestCase):
     @retry_on_connect_failures
     def test_nominal(self):
         os.environ["WORLD_SIZE"] = "1"
-        os.environ["MASTER_ADDR"] = "127.0.0.1"
+        os.environ["MASTER_ADDR"] = "::1"
         os.environ["MASTER_PORT"] = str(common.find_free_port())

         # Single rank
```

**Comment by rohan-varma** [comment]
Looks like this diff is approved internally, is there anything blocking landing this change? I see that windows tests are failing but those should be fixed with @malfet's suggestion?

**Comment by malfet** [comment]
At this point change is pretty old, and should probably be retested against latest trunk

**Comment by kiukchung** [comment]
@osalpekar , @rohan-varma - any ETAs to land this?

**Comment by ss7pro** [comment]
This problem could be solved by chaning /etc/gai.conf so it always puts IPV6 socket data first:

cat /etc/gai.conf

label ::1/128       0
label ::/0          1
label 2002::/16     2
label ::/96         3
label ::ffff:0:0/96 4
label fec0::/10     5
label fc00::/7      6
label 2001:0::/32   7
label ::ffff:7f00:1/128 8

**Comment by Babar** [comment]
See #68225

**Pull request closed without merging**
