### PR TITLE
Improve optimizations for DNNLOWP support on MKL-DNN

### PR DESCRIPTION
**Pull request by gujinghui**
In this PR, the fusion alogrithms are improved to support DNNLOWP.
1. Enabled conv fusions for DNNLOWP
2. Fused order switch op into following quantize op
3. Improve conv+sum fusion to parse larger scope/window
4. re-org fusion code to fix random crash issue due to changing graph

### CODE REVIEW

**Comment by gujinghui** [comment]
@yinghai 
This PR is to improve optimize_ideep for DNNLOWP support.
Pls help review.

@Jiaming-Liu
@jgong5
@uyongw

**Comment by gujinghui** [comment]
@yinghai
This PR is to improve optimize_ideep for DNNLOWP support.
Pls help review.

@Jiaming-Liu
@jgong5
@uyongw

**Comment by gujinghui** [comment]
just rebased

**Comment by gujinghui** [comment]
@yinghai 
All failures are caused by test_zero case.
It should be not related to this PR.
Pls help review it.

Thanks


> Apr 11 06:20:48 test_zeros (__main__.TestScript) ... ok
Apr 11 06:20:48 
Apr 11 06:20:48 ======================================================================
Apr 11 06:20:48 ERROR: test_module_copy_with_attributes (__main__.TestScript)
Apr 11 06:20:48 ----------------------------------------------------------------------
Apr 11 06:20:48 Traceback (most recent call last):
Apr 11 06:20:48   File "test_jit.py", line 3545, in test_module_copy_with_attributes
Apr 11 06:20:48     v = Vocabulary(list('uabcdefg'))
Apr 11 06:20:48   File "/opt/conda/lib/python2.7/site-packages/torch/jit/__init__.py", line 987, in init_then_register
Apr 11 06:20:48     original_init(self, *args, **kwargs)
Apr 11 06:20:48   File "test_jit.py", line 3519, in __init__
Apr 11 06:20:48     super().__init__()
Apr 11 06:20:48 TypeError: super() takes at least 1 argument (0 given)
Apr 11 06:20:48 
Apr 11 06:20:48 ----------------------------------------------------------------------
Apr 11 06:20:48 Ran 1852 tests in 211.712s
Apr 11 06:20:48 
Apr 11 06:20:48 FAILED (errors=1, skipped=22, expected failures=2)
Apr 11 06:20:48 Traceback (most recent call last):
Apr 11 06:20:48   File "test/run_test.py", line 459, in <module>
Apr 11 06:20:48     main()
Apr 11 06:20:48   File "test/run_test.py", line 451, in main
Apr 11 06:20:48     raise RuntimeError(message)
Apr 11 06:20:48 RuntimeError: test_jit failed!

@Jianhui-Li
@jgong5
@uyongw

**Comment by gujinghui** [comment]
@yinghai 
rebased. pls help review.
Thanks a lot.

**Review by yinghai — APPROVED** [review]
LGTM

**Pull request closed without merging**
