### PR TITLE
allow external backend codegen to be used without autograd kernels

### PR DESCRIPTION
**Pull request by bdhirsh**
This should fix a longstanding issue with the external backend codegen: right now it also expects the backend to provide both `backend` and `autograd` kernels.

Intel would like to start using the codegen API, so we should clean this up.

I tested locally by removing the `autograd` entry from XLA and re-running their codegen.

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #69686
* #68531
* #68530
* __->__ #68529

Differential Revision: [D32498572](https://our.internmc.facebook.com/intern/diff/D32498572)

### CODE REVIEW

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32498572).

**Comment by guoyejun** [comment]
I verified this change is correct when there's no autograd in yaml file.

btw, happen to find a typo near the code, and https://github.com/pytorch/pytorch/pull/68562 is created to fix the typo, could you have a look? thanks.

**Review by wconstab — APPROVED** [review]

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32498572).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32498572).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32498572).

**Comment by alanwaketan** [comment]
@bdhirsh This commit breaks the lazy_tensor_staging branch, and we have the fix here: https://github.com/pytorch/pytorch/pull/69928/commits/1c23355da96c153612a90961cdad2a8ecf618def. I'm not sure if I should just upstream the fix or there is a better solution.

**Comment by bdhirsh** [comment]
@alanwaketan yep, I already reverted internally here (diff D33109899). CI is still running but hopefully LTC should be fixed now.

**Comment by alanwaketan** [comment]
Thanks, Brian. Then I won't upstream the fix.

**Pull request closed without merging**
