### PR TITLE
[NHWC] cudnn grouped convolution nhwc patch

### PR DESCRIPTION
**Pull request by jjsjann123**
Earlier cudnn version doesn't support grouped convolution in NHWC well. Legit
configuration in later cudnn version might return CUDNN_STATUS_NOT_SUPPORTED.
We are falling back to NCHW when runtime check of cudnn version is < 7.6.0 to
keep the logic simple.

Note:
We might update the heuristics, 7.6.0 is very conservative.

### CODE REVIEW

**Comment by jjsjann123** [comment]
I'd like to further clean the NHWC logic when we merge the other PR #30174, which is currently waiting on #31139....

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit abb797e:
* **1/1** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=abb797e636e068ebdcecef6b9013c7bc409709ca).

### :detective: 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4008011) pytorch_xla_linux_xenial_py3_6_clang7_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=76935973) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=76935973))
<details>
<summary>
<code>Dec 18 22:07:27 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-serialization.diff</code>
</summary>

```
Dec 18 22:07:27 + python /var/lib/jenkins/workspace/xla/scripts/cond_patch.py /var/lib/jenkins/workspace/xla/scripts/../torch_patches /var/lib/jenkins/workspace/xla/scripts/../.. 
Dec 18 22:07:27 1 out of 1 hunk FAILED 
Dec 18 22:07:27 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-clip_grad.diff 
Dec 18 22:07:27 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff 
Dec 18 22:07:27 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-serialization.diff 
Dec 18 22:07:27 Traceback (most recent call last): 
Dec 18 22:07:27   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 67, in <module> 
Dec 18 22:07:27     patch_repo(args) 
Dec 18 22:07:27   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 49, in patch_repo 
Dec 18 22:07:27     raise RuntimeError('Failed to apply patch: {}'.format(ppath)) 
Dec 18 22:07:27 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-serialization.diff 
Dec 18 22:07:27 + cleanup 
Dec 18 22:07:27 + retcode=1 
Dec 18 22:07:27 + set +x 
Dec 18 22:07:27 =================== sccache compilation log =================== 
Dec 18 22:07:27 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 18 22:07:27 Compile requests                 1 
Dec 18 22:07:27 Compile requests executed        0 
Dec 18 22:07:27 Cache hits                       0 
Dec 18 22:07:27 Cache misses                     0 
Dec 18 22:07:27 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by jjsjann123** [comment]
Didn't handle the guard properly. Also apprently 7.6.0 is **not** conservative at all.

Let me update this shortly

**Comment by jjsjann123** [comment]
CI failures seem to be not related. Should be good for review now.

**Review by VitalyFedyunin — APPROVED** [review]
This will convert channels last input to contiguous, if cudnn < 7.6, we are fine about it for now (as it is default for all other kernels) but should review it later.

**Pull request closed without merging**
