### PR TITLE
[TorchElastic] Support for overprovisioning in C10 based rendezvous

### PR DESCRIPTION
**Pull request by kurman**
Summary:
Allow TorchElastic to manage more nodes than a maximum nnodes specifed in a job. It will be used as a spare capacity/warm nodes for schedulers that support elasticity.

RFC: https://github.com/pytorch/pytorch/issues/114097

Test Plan: Integration tests

Differential Revision: D52343874

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Review by zdevito — APPROVED** [review]
I think it's good -- I read the code a bunch mostly to figure out how the whole state machine works. I can't say I completely understand it, but the changes go where I'd expect them to. Is it really the case that each participant essentially races to update a global state that gets reshared to each participant on each update? It seems easy to get slowed down by collisions.

**Comment by kurman** [comment]
> I think it's good -- I read the code a bunch mostly to figure out how the whole state machine works. I can't say I completely understand it, but the changes go where I'd expect them to. Is it really the case that each participant essentially races to update a global state that gets reshared to each participant on each update? It seems easy to get slowed down by collisions.

@zdevito Correct - all the participants attempt to update the state and collisions are very likely due to atomicity requirements. Actor model would be a better option especially given that joining and leaving rendezvous is a commutative operation.

**Comment by Lucine94** [comment]
Shutdown of _rdzv_handler was added in function _shutdown in this commit, but  this shutdown will turn the closed flag in _RendezvousState into TRUE, and the joinOp in next_rendezvous return action ERROR_CLOSED. It seems that the rendezvous can not restart again. So why we need self._rdzv_handler.shutdown() here? Looking forward to your reply.

def _shutdown(self, death_sig: signal.Signals = signal.SIGTERM) -> None:
        if self._worker_watchdog is not None:
            self._worker_watchdog.stop()
            self._worker_watchdog = None
        if self._pcontext:
            self._pcontext.close(death_sig)
        **if self._rdzv_handler:
            self._rdzv_handler.shutdown()**

**Pull request closed without merging**
