### PR TITLE
[GH1] Fix pending/not run conditional and add a way to test new merge_rules

### PR DESCRIPTION
**Pull request by janeyx99**
Addressing confusing developer experience here https://github.com/pytorch/pytorch/pull/69828#issuecomment-1112451260

Also adds a way to test merge rules.

### CODE REVIEW

**Comment by janeyx99** [comment]
@zengk95 This is likely relevant for your PR to parse when jobs are pending.

**Review by seemethere — APPROVED** [review]

**Review by albanD — APPROVED** [review]
The change to the trymerge script looks good.
I guess the mock json update is just automatic?

**Comment by janeyx99** [comment]
> The change to the trymerge script looks good. I guess the mock json update is just automatic?

Yea, so the tests requery every time they're modified so the new cached version of the results become different.

**Pull request closed without merging**
