### PR TITLE
gcc 13 porting - standard headers included

### PR DESCRIPTION
**Pull request by atupone**
cc @malfet @seemethere

### CODE REVIEW

**Comment by dagitses** [comment]
Hey Alfredo can you put a little more description in this PR. What does this have to do with gcc 13?

**Comment by dagitses** [comment]
Hey Alfredo can you put a little more description in this PR. What does this have to do with gcc 13?

**Comment by atupone** [comment]
> Hey Alfredo can you put a little more description in this PR. What does this have to do with gcc 13?

if you use a type declared in cstdint or stdexept you cannot count on system headers to include it for you.

with gcc-12 pytorch found these headers already included by using other gcc-12 system headers.

That is not standard so it breaks build with other gcc version .

See [gcc 13 porting](https://gcc.gnu.org/gcc-13/porting_to.html)

**Comment by dagitses** [comment]
> > Hey Alfredo can you put a little more description in this PR. What does this have to do with gcc 13?
> 
> if you use a type declared in cstdint or stdexept you cannot count on system headers to include it for you.
> 
> with gcc-12 pytorch found these headers already included by using other gcc-12 system headers.
> 
> That is not standard so it breaks build with other gcc version .
> 
> See [gcc 13 porting](https://gcc.gnu.org/gcc-13/porting_to.html)

can you amend the description and title please?

**Review by Skylion007 — APPROVED** [review]

**Pull request closed without merging**
