### PR TITLE
Makes uint8 indexing and masking warn once

### PR DESCRIPTION
**Pull request by mruberry**
Addresses https://github.com/pytorch/pytorch/issues/37065.

Warning once is often preferable to warning every time a behavior occurs, which can lead to the excessive clutter that #37065 complains of.

### CODE REVIEW

**Review by gchanan — APPROVED** [review]

**Comment by ilia-cher** [comment]
Outputting warnings only once can make it hard to automatically detect problems by scanning production logs cc. @ngimel @dzhulgakov

**Comment by ilia-cher** [comment]
Can we maybe use LOG_EVERY_N or similar?

**Comment by ngimel** [comment]
Deprecation warnings should not be WARN_ONCE imo - 
- it's easy to miss them in the initialization spew if they are WARN_ONCE, 
- people are getting what they deserve, and thus are more likely to fix the cause if there's a lot of warnings

**Comment by mruberry** [comment]
Some context is that currently we don't have any standard and are warnings are a mix of WARN and WARN_ONCE. Users seem to dislike WARN, and our recent deprecation of integer division used WARN_ONCE. 

Seems like it makes sense to pick one way and stick with it.

**Comment by mruberry** [comment]
See https://github.com/pytorch/pytorch/issues/37315 to discuss warning behavior.

**Comment by gchanan** [comment]
> people are getting what they deserve, and thus are more likely to fix the cause if there's a lot of warnings

I disagree, these are deprecations -- the users didn't do anything wrong, that was literally the only way to do mask indexing before.

**Pull request closed without merging**
