### PR TITLE
[ONNX] Enable new scripting passes for functionalization and remove_mutation 

### PR DESCRIPTION
**Pull request by neginraoof**
Duplicate of #41413 
This PR initiates the process of updating the torchsciprt backend interface used by ONNX exporter.

Replace jit lower graph pass by freeze module pass

Enable ScriptModule tests for ONNX operator tests (ORT backend) and model tests by default.

Replace jit remove_inplace_ops pass with remove_mutation and consolidation all passes for handling inplace ops.

### CODE REVIEW

**Review by BowenBao — APPROVED** [review]
LGTM, identical to the approved #41413. This PR is created since the old one cannot be imported due to pipeline issue.

**Review by bzinodev — APPROVED** [review]

**Comment by neginraoof** [comment]
@bzinodev CI is green. Would you please help us merge this PR?

**Comment by neginraoof** [comment]
@bzinodev 
The failure in Jenkins: pr/pytorch-linux-bionic-rocm3.7-py3.6
is unrelated. I see this failure on other recent PR's as well.

**Comment by neginraoof** [comment]
@bzinodev I have rebased and resolved conflicts here. Jenkins failures persist.
Would you please help us merge this PR?

**Comment by neginraoof** [comment]
@bzinodev 
I rebased the PR with Jenkins failures again last night and now there is an additional failure on CI: https://github.com/pytorch/pytorch/pull/43791
This is an important PR for using new jit APIs by exporter, and I'm trying to implement on top of this.
Can you help us merge this one?

**Pull request closed without merging**
