### PR TITLE
[5/N] Reconcile barrier and NaN checker

### PR DESCRIPTION
**Pull request by kwen2501**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134707
* #134701
* #134357
* #134345

By using a zeros() tensor instead of empty() tensor.

cc @XilunWu @H-Huang @awgu @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by shuqiangzhang — APPROVED** [review]

**Review by wconstab — APPROVED** [review]
agree the test is lackluster becuase of not having control over the empty tensor and likely passing (or being flaky).

i think its still worth having since we'd probably get notified via flaky-test behavior if the fix got reverted..

i wonder if we can allocate and free a NaN tensor right before calling .barrier() and trick the allocator into giving back the same memory to raise the chance of hitting the case.

**Pull request closed without merging**
