### PR TITLE
at::Generator refactoring: extracting MT19937CPUGenerator from CPUGenerator

### PR DESCRIPTION
**Pull request by pbelevich**
The purpose of this PR is to enable custom RNGs by separating CPUGenerator abstract class and MT19937CPUGenerator implementation.
* CPUGenerator became abstract class with some virtual methods
* THTensor_(getRNGState) and THTensor_(setRNGState) methods are now free of THGeneratorState/THGeneratorStateNew dependencies(which are specific to MT19937RNGEngine)

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #31376 torch.Generator(int64_t impl)
* **#31440 at::Generator refactoring: extracting MT19937CPUGenerator from CPUGenerator**

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 49338aa:
* **1/1** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=49338aa5741b9b3736dc4b400e78e18772d1a637).

### :detective: 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4006543) binary_linux_libtorch_2_7m_cpu_gcc5_4_cxx11-abi_shared-with-deps_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=76885101) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=76885101))
<details>
<summary>
<code>Dec 18 21:04:51 FAILED: caffe2/torch/CMakeFiles/torch_python.dir/csrc/Generator.cpp.o</code>
</summary>

```
Dec 18 21:04:47         ^ 
Dec 18 21:04:47 [2855/3001] Linking CXX executable bin/ProcessGroupGlooTest 
Dec 18 21:04:47 [2856/3001] Linking CXX executable bin/TCPStoreTest 
Dec 18 21:04:47 [2857/3001] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/DataLoader.cpp.o 
Dec 18 21:04:50 [2858/3001] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/Dtype.cpp.o 
Dec 18 21:04:50 [2859/3001] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/Layout.cpp.o 
Dec 18 21:04:50 [2860/3001] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/Device.cpp.o 
Dec 18 21:04:50 [2861/3001] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/MemoryFormat.cpp.o 
Dec 18 21:04:51 [2862/3001] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/Exceptions.cpp.o 
Dec 18 21:04:51 [2863/3001] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/Generator.cpp.o 
Dec 18 21:04:51 FAILED: caffe2/torch/CMakeFiles/torch_python.dir/csrc/Generator.cpp.o  
AFFE2_USE_GLOO -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -fno-strict-aliasing -Wno-write-strings -Wno-strict-aliasing -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unknown-pragmas -Wno-missing-braces -fopenmp -std=gnu++14 -MD -MT caffe2/torch/CMakeFiles/torch_python.dir/csrc/Generator.cpp.o -MF caffe2/torch/CMakeFiles/torch_python.dir/csrc/Generator.cpp.o.d -o caffe2/torch/CMakeFiles/torch_python.dir/csrc/Generator.cpp.o -c ../torch/csrc/Generator.cpp 
Dec 18 21:04:51 ../torch/csrc/Generator.cpp: In function ‘PyObject* THPGenerator_pynew(PyTypeObject*, PyObject*, PyObject*)’: 
Dec 18 21:04:51 ../torch/csrc/Generator.cpp:73:36: error: invalid new-expression of abstract class type ‘at::CPUGenerator’ 
Dec 18 21:04:51      self->cdata = new CPUGenerator(); 
Dec 18 21:04:51                                     ^ 
Dec 18 21:04:51 In file included from ../aten/src/ATen/Context.h:8:0, 
Dec 18 21:04:51                  from ../aten/src/ATen/ATen.h:5, 
Dec 18 21:04:51                  from ../torch/csrc/Generator.h:4, 
Dec 18 21:04:51                  from ../torch/csrc/Generator.cpp:1: 
Dec 18 21:04:51 ../aten/src/ATen/CPUGenerator.h:10:19: note:   because the following virtual functions are pure within ‘at::CPUGenerator’: 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by vishwakftw** [comment]
Is there any perf regression due to virtualization?

**Comment by nairbv** [comment]
> Is there any perf regression due to virtualization?

I asked Pavel about this Friday, his response from chat:
```
master without my change:

In [2]: t = torch.empty(1000000)
In [3]: %timeit t.random_()
7.94 ms ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

with my change:

In [10]: t = torch.empty(1000000)
In [11]: %timeit t.random_()
7.95 ms ± 98.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by zou3519** [comment]
> > Is there any perf regression due to virtualization?
> 
> I asked Pavel about this Friday, his response from chat:
> 
> ```
> master without my change:
> 
> In [2]: t = torch.empty(1000000)
> In [3]: %timeit t.random_()
> 7.94 ms ± 11.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
> 
> with my change:
> 
> In [10]: t = torch.empty(1000000)
> In [11]: %timeit t.random_()
> 7.95 ms ± 98.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
> ```

What about on smaller input sizes? (maybe size 1)

**Comment by pbelevich** [comment]
```
master without my change:

In [2]: t = torch.empty(1)
In [3]: %timeit t.random_()
1.25 µs ± 3.91 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

with my change:

In [2]: t = torch.empty(1)
In [3]: %timeit t.random_()
1.23 µs ± 8.22 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by ezyang** [comment]
I feel this may be because there is a mistake in the current implementation of Generator that is preventing the Mersenne Twister from getting inlined. Running an experiment.

**Comment by ezyang** [comment]
@pbelevich could you rerun your before benchmark with this patch:

```
diff --git a/aten/src/ATen/CPUGenerator.cpp b/aten/src/ATen/CPUGenerator.cpp
index c0b6e30d7c..f1290952b6 100644
--- a/aten/src/ATen/CPUGenerator.cpp
+++ b/aten/src/ATen/CPUGenerator.cpp
@@ -91,15 +91,6 @@ DeviceType CPUGenerator::device_type() {
   return DeviceType::CPU;
 }
 
-/**
- * Gets a random 32 bit unsigned integer from the engine
- * 
- * See Note [Acquire lock when using random generators]
- */
-uint32_t CPUGenerator::random() {
-  return engine_();
-}
-
 /**
  * Gets a random 64 bit unsigned integer from the engine
  * 
diff --git a/aten/src/ATen/CPUGenerator.h b/aten/src/ATen/CPUGenerator.h
index f41142a395..d1ec52b7ac 100644
--- a/aten/src/ATen/CPUGenerator.h
+++ b/aten/src/ATen/CPUGenerator.h
@@ -18,7 +18,7 @@ struct CAFFE2_API CPUGenerator : public Generator {
   uint64_t current_seed() const override;
   uint64_t seed() override;
   static DeviceType device_type();
-  uint32_t random();
+  inline uint32_t random() { return engine_(); }
   uint64_t random64();
   c10::optional<float> next_float_normal_sample();
   c10::optional<double> next_double_normal_sample();
```

**Comment by pbelevich** [comment]
@ezyang I double-checked that `t.random_()` goes to `random()`, not `random64()`
pure master results:
```
t = torch.empty(1)
%timeit t.random_()
1.26 µs ± 14.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
t = torch.empty(1000000)
%timeit t.random_()
7.93 ms ± 7.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
master with your patch:
```
t = torch.empty(1)
%timeit t.random_()
2.11 µs ± 55.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
t = torch.empty(1000000)
%timeit t.random_()
7.08 ms ± 9.78 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
results are pretty stable, I run them multiple times

**Comment by ezyang** [comment]
How are you building PyTorch for the performance tests?

**Comment by pbelevich** [comment]
```
python setup.py clean
python setup.py develop
```

**Comment by zou3519** [comment]
Here's a second opinion: I have a dedicated benchmarking machine and benchmarked a CPU build of pytorch:

On master:
```
In [1]: import torch

In [2]: t = torch.empty(1)

In [3]: tt = torch.empty(1000000)

In [4]: %timeit t.random_()
The slowest run took 360.43 times longer than the fastest. This could mean that an interm
ediate result is being cached.
1000000 loops, best of 3: 658 ns per loop

In [5]: %timeit t.random_()
The slowest run took 72.41 times longer than the fastest. This could mean that an interme
diate result is being cached.
1000000 loops, best of 3: 649 ns per loop

In [6]: %timeit t.random_()
The slowest run took 71.08 times longer than the fastest. This could mean that an interme
diate result is being cached.
1000000 loops, best of 3: 661 ns per loop

In [7]: %timeit tt.random_()
100 loops, best of 3: 4.55 ms per loop

In [8]:  %timeit tt.random_()
100 loops, best of 3: 4.55 ms per loop

In [9]:  %timeit tt.random_()
100 loops, best of 3: 4.55 ms per loop
```

On master with @ezyang's patch
```
In [1]: import torch

In [2]: t = torch.empty(1)

In [3]: tt = torch.empty(1000000)

In [4]: %timeit t.random_()
The slowest run took 355.29 times longer than the fastest. This could mean that an interm
ediate result is being cached.
1000000 loops, best of 3: 653 ns per loop

In [5]: %timeit t.random_()
The slowest run took 73.60 times longer than the fastest. This could mean that an interme
diate result is being cached.
1000000 loops, best of 3: 654 ns per loop

In [6]: %timeit t.random_()
The slowest run took 66.11 times longer than the fastest. This could mean that an interme
diate result is being cached.
1000000 loops, best of 3: 653 ns per loop

In [7]:  %timeit tt.random_()
100 loops, best of 3: 3.95 ms per loop

In [8]:  %timeit tt.random_()
100 loops, best of 3: 3.95 ms per loop

In [9]:  %timeit tt.random_()
100 loops, best of 3: 3.95 ms per loop

```

**Comment by ezyang** [comment]
Richard's numbers make more sense to me :) (I was inspecting the assembly for `random_` and I still see a pile of indirect jumps which I am not entirely sure where they came from. I'll look at this some more after PSC is done.)

**Pull request closed without merging**
