### PR TITLE
Quick fix for #18215, the CPU case

### PR DESCRIPTION
**Pull request by zh217**
The bug is that when target_length == 0, there is no preceding BLANK state and the original implementation will lead to out of bound pointer access.

### CODE REVIEW

**Comment by t-vi** [comment]
Thank you!

Looks good at first sight, could you add a test (under `test/test_nn.py`; or amend an existing one) and maybe also add a small comment in the code? Thanks!

**Comment by zh217** [comment]
Done.

**Review by t-vi — APPROVED** [review]
Looks good. Thank you!

**Pull request closed without merging**
