### PR TITLE
[ROCm] AMDSMI memory usage unification

### LINKED ISSUE #140638: torch.cuda.memory_usage() returns percent of time over the past sample period global memory being read/written for Nvidia and MegaBytes for AMD
### 🐛 Describe the bug

torch.cuda.memory_usage source code: https://github.com/pytorch/pytorch/blob/2f1dbfea020e8db7fbeaf0767962055d8ce0779b/torch/cuda/__init__.py#L1153C5-L1153C17

For AMD, amdsmi_get_gpu_vram_usage() API "Returns the VRAM usage (both total and used memory) in MegaBytes."
https://rocm.docs.amd.com/projects/amdsmi/en/docs-5.7.1/doxygen/docBin/html/group__gpumon.html#ga1408b9ef1dcc59bea2ce3e37fb1d19e2

On the other hand, for Nvidia, nvmlDeviceGetUtilizationRates(handle)
https://github.com/pytorch/pytorch/blob/2f1dbfea020e8db7fbeaf0767962055d8ce0779b/torch/cuda/__init__.py#L1169
actually returns the "
Percent of time over the past sample period during which global (device) memory was being read or written." from https://docs.nvidia.com/deploy/nvml-api/structnvmlUtilization__t.html#structnvmlUtilization__t

It seems that we need to use nvmlDeviceGetMemoryInfo instead. 
https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1g2dfeb1db82aa1de91aa6edf941c85ca8

If we do return the size of used memory, the used memory is in bytes instead, e.g., https://docs.nvidia.com/deploy/nvml-api/structnvmlMemory__t.html#structnvmlMemory__t

### Versions

main branch

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

### PR DESCRIPTION
**Pull request by jataylo**
Fixes https://github.com/pytorch/pytorch/issues/140638

Old implementation used vram_used, which is not the correct equivalent API for pynvml memory utilization.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang @naromero77amd

### CODE REVIEW

**Comment by jataylo** [comment]
I had attempted to write a unit test as part of this PR, it appears it can take a little bit of time for umc activity to spike on AMD, I will waive adding the unit test rather than adding a longer UT.

**Comment by xw285cornell** [comment]
Can we publish this PR please?

**Comment by jataylo** [comment]
> Can we publish this PR please?

Opened for review

**Review by jeffdaily — APPROVED** [review]

**Review by eqy — APPROVED** [review]

**Pull request closed without merging**
