### PR TITLE
Add Batch Rule for aten::native_dropout_backward

### LINKED ISSUE #100801: There is a performance drop because we have not yet implemented the batching rule for aten::native_dropout_backward
### 🐛 Describe the bug

On Google Colab when using vmap. Unlike #97425, this is not using torch.compile.
Example: https://colab.research.google.com/drive/1g7pqIrVJkr8uB0wb9nR18Ak_rHO01xO0?usp=sharing
```
/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py:303: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::native_dropout_backward. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at ../aten/src/ATen/functorch/BatchedFallback.cpp:82.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py:303: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::_thnn_fused_lstm_cell_backward. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at ../aten/src/ATen/functorch/BatchedFallback.cpp:82.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
```

### Versions

PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.147+-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.85.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           63
Model name:                      Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:                        0
CPU MHz:                         2299.998
BogoMIPS:                        4599.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        256 KiB
L3 cache:                        45 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==2.0.0+cu118
[pip3] torchaudio==2.0.1+cu118
[pip3] torchdata==0.6.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.1
[pip3] torchvision==0.15.1+cu118
[pip3] triton==2.0.0
[conda] Could not collect

### PR DESCRIPTION
**Pull request by isdanni**
Summary: Add batch rule for ` aten::native_dropout_backward`

Fix: #100801 

Test Plan: Please see GitHub pipelines.

Differential Revision: D45640369

### CODE REVIEW

**Comment by isdanni** [comment]
Hey @kshitij12345 , wanna check two things with u :)
1. Is `BatchRulesReduceOps.cpp` the correct place to include dropout related batch functions?
2. For testing `native_dropout_backend`, which class in `test_vmap` is more suitable? `class TestVmapOperators`?

**Comment by kshitij12345** [comment]
@isdanni 

I would suggest that we leverage existing decomposition and just register it for vmap using `_register_python_decomposition_vmap`.

Ref to the existing decomposition:
https://github.com/pytorch/pytorch/blob/4c3b52a5a99e8aed2576773829e6a353a65aa2b4/torch/_decomp/decompositions.py#L947-L948

Also, we should have a comment below the following line to mention batching rule is registered via decomposition.
https://github.com/pytorch/pytorch/blob/4c3b52a5a99e8aed2576773829e6a353a65aa2b4/aten/src/ATen/functorch/BatchRulesRandomness.cpp#L480

PR for reference that added decomposition and registered it for vmap: https://github.com/pytorch/pytorch/pull/99429

--------

As for testing, I would suggest adding a test to `TestVmapOperatorsOpInfo` as tests under that class run on both CPU and CUDA.

Also, make sure you add test case where `grad_output` is batched/unbatched and `mask` is batched/unbatched (4 cases).
And use `DisableVmapFallback` context manager so that we will also ensure that the batch rule is implemented (and we don't fallback to for-loop).

Let me know if anything is unclear! Thanks for the PR.

**Comment by isdanni** [comment]
> @isdanni
> 
> I would suggest that we leverage existing decomposition and just register it for vmap using `_register_python_decomposition_vmap`.
> 
> Ref to the existing decomposition:
> 
> https://github.com/pytorch/pytorch/blob/4c3b52a5a99e8aed2576773829e6a353a65aa2b4/torch/_decomp/decompositions.py#L947-L948
> 
> Also, we should have a comment below the following line to mention batching rule is registered via decomposition.
> 
> https://github.com/pytorch/pytorch/blob/4c3b52a5a99e8aed2576773829e6a353a65aa2b4/aten/src/ATen/functorch/BatchRulesRandomness.cpp#L480
> 
> PR for reference that added decomposition and registered it for vmap: #99429
> 
> As for testing, I would suggest adding a test to `TestVmapOperatorsOpInfo` as tests under that class run on both CPU and CUDA.
> 
> Also, make sure you add test case where `grad_output` is batched/unbatched and `mask` is batched/unbatched (4 cases). And use `DisableVmapFallback` context manager so that we will also ensure that the batch rule is implemented (and we don't fallback to for-loop).
> 
> Let me know if anything is unclear! Thanks for the PR.

Thanks for the detailed explanation! I will update accordingly.

**Comment by isdanni** [comment]
Closing as this change would affect other functions

**Pull request closed without merging**
