### PR TITLE
Remove OptionsGuard from ATen

### PR DESCRIPTION
**Pull request by goldsborough**
Deletes the `OptionsGuard` from ATen. This works towards the goal of reworking `DefaultTensorOptions`. `OptionsGuard` is troublesome because it relies on mutating thread local state. This PR fixes those code locations and then deletes the `OptionsGuard`.

@ezyang @gchanan

### CODE REVIEW

**Comment by ezyang** [comment]
cc @gchanan

**Comment by goldsborough** [comment]
@ezyang @gchanan ping

**Comment by goldsborough** [comment]
Actually, huh, this is missing some commits that fix the `TODO`s. They must be in some other branch.

**Comment by goldsborough** [comment]
@ezyang @gchanan ping

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
