### PR TITLE
Error when jit.trace/script is used with torch.compile

### LINKED ISSUE #93485: Torch.jit.trace don't support torchdynamo model
I was trying Pytorch 2.0 and found that torch. jit.trace could not be convert torch.compile’s model. For example:
```
import torch
from torchvision.models import resnet50

model = resnet50(weights=None)
compile_model = torch.compile(model)
example_forward_input = torch.rand(1, 3, 224, 224)
c_model_traced = torch.jit.trace(compile_model, example_forward_input)
torch.jit.save(c_model_traced, "c_trace_model.pt")
```

### PR DESCRIPTION
**Pull request by msaroufim**
Fixes https://github.com/pytorch/pytorch/issues/93485

```python
import torch
from torchvision.models import resnet50

model = resnet50(weights=None)
compile_model = torch.compile(model)
print(type(compile_model))
example_forward_input = torch.rand(1, 3, 224, 224)
c_model_traced = torch.jit.trace(compile_model, example_forward_input) # or torch.jit.script
torch.jit.save(c_model_traced, "c_trace_model.pt")
```

Should I raise a warning if a user tries to compile a scripted or traced model as well? It works just fine now on resnet but not sure if it's that something we want to explicitly discourage

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Comment by soumith** [comment]
> Should I raise a warning if a user tries to compile a scripted or traced model as well?

IMO not yet. Maybe eventually we can make this a warning but there are legitimate uses such as export (and `torch.export` is not ready yet)

**Comment by msaroufim** [comment]
Main error in CI seems to be     

```
if isinstance(obj, torch._dynamo.eval_frame.OptimizedModule):
AttributeError: module 'torch' has no attribute '_dynamo'
```

@desertfire is it the case that some machines in CI have dynamo installed and some don't? I can add a `try import torch._dynamo` but that doesnt' feel right

**Comment by desertfire** [comment]
> Main error in CI seems to be
> 
> ```
> if isinstance(obj, torch._dynamo.eval_frame.OptimizedModule):
> AttributeError: module 'torch' has no attribute '_dynamo'
> ```
> 
> @desertfire is it the case that some machines in CI have dynamo installed and some don't? I can add a `try import torch._dynamo` but that doesnt' feel right

I think you do have to add `import` here.

**Comment by msaroufim** [comment]
Thank you for the patience folks, this is finally fixed

**Review by desertfire — APPROVED** [review]

**Pull request closed without merging**
