### PR TITLE
Deprecate `torch._utils.is_compiling()`

### PR DESCRIPTION
**Pull request by XuehaiPan**
This PR is split from PR #126898.

- #126898

------

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #127690

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @XilunWu @rec @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @tianyu-l @peterbell10

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by clee2000** [comment]
@XuehaiPan Do you mind rebasing your PR? We think that https://github.com/pytorch/FBGEMM/pull/2716 should help with the internal failure

**Comment by XuehaiPan** [comment]
> Do you mind rebasing your PR?

Done.

**Comment by clee2000** [comment]
> Done. You can trigger a merge if the internal migration is done.

Sorry a bunch of stuff started failing after rebase, could you take a look at them?

**Review by malfet — APPROVED** [review]

**Comment by kit1980** [comment]
@pytorchbot @pytorchbot revert -m "breaking internal builds" -c ghfirst
 
 Apparently `torch._dynamo.is_compiling()` is used internally at Meta
 cc @PaliC

**Comment by kit1980** [comment]
@pytorchbot revert -m "breaking internal builds" -c ghfirst
 
 Apparently `torch._dynamo.is_compiling()` is used internally at Meta
 cc @PaliC

**Comment by kit1980** [comment]
> Apparently `torch._dynamo.is_compiling()` is used internally at Meta

Or maybe the actual issue shows in JIT-compiled user code:

RuntimeError: 
undefined value torch:
return torch.compiler.is_compiling()
           ~~~~~ <--- HERE

**Comment by ZainRizvi** [comment]
@pytorchbot revert -c ghfirst -m "Sorry but this is breaking internally. More details in D65483292"

@davidberard98, might you be able to help get the internal failures resolved here?

**Comment by davidberard98** [comment]
The reason for the revert is that there's some internal tests where code containing `torch._dynamo.is_compiling` (or other `is_compiling`) is getting TorchScripted.

These tests trigger this bug https://github.com/pytorch/pytorch/issues/136654 where TorchScript gets confused by decorators.

If you can mark as deprecated without `@deprecated`, that would be one solution.

Another option is to try to fix TorchScript. If you want to go this route, I'd be willing to spend like ~1hr seeing how doable this is, but if it ends up being hard to fix the TorchScript bug, I'd lean towards the "not using `@deprecated`" solution if possible

**Comment by XuehaiPan** [comment]
> If you can mark as deprecated without `@deprecated`, that would be one solution.

I changed `@deprecated` decorator to `warnings.warn` inside the function. Hope it does not break TorchScript.

**Pull request closed without merging**
