### PR TITLE
[pytorch][sparse] modified code layout for consistency

### PR DESCRIPTION
**Pull request by aartbik**
@pearu to review

https://github.com/pytorch/pytorch/issues/117188

### CODE REVIEW

**Review by pearu — COMMENTED** [review]
I cannot spot any change in this PR other than line indention. Am I missing something?

**Comment by aartbik** [comment]
> I cannot spot any change in this PR other than line indention. Am I missing something?

Oh, that's it :-) I fixed the layout of the code to be consistent (since I did that in my other PR but it is a non-functional-changing PR). Let me know if that is not common in pytorch-dev community.

**Comment by pearu** [comment]
> > I cannot spot any change in this PR other than line indention. Am I missing something?
> 
> Oh, that's it :-) I fixed the layout of the code to be consistent (since I did that in my other PR but it is a non-functional-change, so I pulled it out into this NFC PR). Let me know if that is not common in pytorch-dev community.

Typically, we use lint to format code. Since the code style requirements tend to be in-flux, the current main branch always contains some source code that does not meet the latest version of code style requirements. Fixing the style of such code is OK when changing its function, otherwise, one must be careful with the style-only-fixes because when another developer is working with the same code, merge conflicts become very likely. So, the style-only-fixes usually do not pay off because it may trigger conflicts that can be avoided (by doing nothing) and these can be annoying and a time waster for another developer who commits substantial changes.

In this particular case, I think the suggested changes are fine.

**Comment by amjames** [comment]
This looks fine from my end. I don't know if we have a label to skip functional testing and only apply the linter job, but as long as the linter clears LGTM.

**Comment by pearu** [comment]
@aartbik could you address the failures like
```
RuntimeError: Unexpected success, please remove `test/dynamo_expected_failures/TestAOTAutograd.test_some_output_requires_grad_input_doesnt`
```
according to the exception message?

**Pull request closed without merging**
