### PR TITLE
Add meta function for _upsample_bilinear2d_aa

### PR DESCRIPTION
**Pull request by gmagogsfm**
Differential Revision: D43353000

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Gotta finish sweating the failing tests, but this all structurally looks good

**Comment by gmagogsfm** [comment]
> Gotta finish sweating the failing tests, but this all structurally looks good

Any tips to programmatically find all failing tests and disable them? Right now, my workflow is downloading logs archive and search for a few patterns like "ERROR [". But this is really time consuming with a long turn-around time.

Or is there a way to "just" test decomposition and meta kernel without adding OpInfo, which enables every test?

**Comment by Chillee** [comment]
One thing I often do is run a broad swathe of tests with `-k <op>`. That will allow you to run more tests that specifically test your OpInfo.

**Comment by gmagogsfm** [comment]
False alarm, it is not a real breakage. I am fixing forward instead, no need to revert

**Pull request closed without merging**
