### PR TITLE
add step rate to adadelta

### PR DESCRIPTION
**Pull request by edouardelasalles**
Scales `delta` before it is applied to the parameters in order to control the learning rate of the optimizer (inspired from climin optim lib for theano).
Also changed the link to the Adadelta paper to point to the right location.

### CODE REVIEW

**Comment by soumith** [comment]
thanks!

**Comment by apaszke** [comment]
Can we call it lr to be consistent with other optimizers, or doesn't it make sense?

**Comment by edouardelasalles** [comment]
Yes, I think that makes sense.

**Comment by soumith** [comment]
made the change in #569

**Pull request merged**
