### PR TITLE
generate C++ API for meta functions using at::meta::

### PR DESCRIPTION
**Pull request by bdhirsh**
**What the PR does**
Generate a fast-path `at::meta::{op}` API for calling meta functions without having to go through the dispatcher. This will be important for perf for external backends that want to use meta functions for shape checking (which seems likely to be what we end up doing for LazyTensorCore).

**Details**
In order to avoid naming collisions I had to make two small changes:
- rename `MetaFunctions.h` template -> `NativeMetaFunctions.h` (this is the file that declares the impl() function for every structured operator).
- rename the meta class: `at::meta::{op}::meta()` -> `at::meta::structured_{op}::meta()`

I also deleted a few unnecessary includes, since any file that includes NativeFunctions.h will automatically include NativeMetaFunctions.h.

**Why I made the change**
This change isn't actually immediately used anywhere; I already started writing it because I thought it would be useful for structured composite ops, but that isn't actually true (see [comment](https://github.com/pytorch/pytorch/pull/58266#issuecomment-843213147)). The change feels useful and unambiguous though so I think it's safe to add. I added explicit tests for C++ meta function calls just to ensure that I wrote it correctly - which is actually how I hit the internal linkage issue in the PR below this in the stack.

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #59839 move all external kernels into a class for better compiler error messages
* #58065 add a boxed CPU fallback kernel
* #59115 beef up at::_ops API
* **#58570 generate C++ API for meta functions using at::meta::**
* #58569 bugfix: ensure that at::{dispatch_key}:: API gets external linkage

Differential Revision: [D28711299](https://our.internmc.facebook.com/intern/diff/D28711299)

### CODE REVIEW

**Comment by bdhirsh** [comment]
Looks like this made the bezel build unhappy

**Review by ezyang — APPROVED** [review]
One q I have is whether or not we can easily make `at::meta` operators overloaded, in the sense that you can directly pass them CPU/CUDA tensors and it will still give you a meta tensor in the end. Food for thought...

**Comment by ezyang** [comment]
Looks like functional is safe because we just unconditionally ignore the device specified in options of the set_output call

```
            if self.backend_index.dispatch_key == DispatchKey.Meta:
                # TODO: dedupe this with below
                return """
if (strides.empty()) {
    outputs_[output_idx] = at::empty(sizes, options.device(at::kMeta));
} else {
    outputs_[output_idx] = at::empty_strided(sizes, strides, options.device(at::kMeta));
}
"""         

```

the out variant may need some rejiggering, it seems to always test the provided tensor is consistent

```
TORCH_CHECK(options.device() == out.device(),
    "Expected out tensor to have device ", options.device(), ", but got ", out.device(), " instead");
```

(this is just a bug, easy enough to fix)

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28711299).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28711299).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28711299).

**Comment by bdhirsh** [comment]
> the out variant may need some rejiggering, it seems to always test the provided tensor is consistent
> 
> ```
> TORCH_CHECK(options.device() == out.device(),
>     "Expected out tensor to have device ", options.device(), ", but got ", out.device(), " instead");
> ```
> 
> (this is just a bug, easy enough to fix)

I played around with this locally. For TI ops, I don't think that fixing up that torch check for at::meta:: helps because TI has its own checks ([here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/TensorIterator.cpp#L397)) for a common device, and it looks like the check includes the out tensor if you provide one.

```
>>> a = torch.ones(2, dtype=torch.float)
>>> b = torch.ones(2, dtype=torch.float)
>>> out = torch.tensor(0, device='meta', dtype=torch.float)
>>> torch.add(a, b, out=out)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, meta and cpu!
```

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28711299).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28711299).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28711299).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28711299).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28711299).

**Pull request closed without merging**
