### PR TITLE
Re-add Tensor.T

### PR DESCRIPTION
**Pull request by umanwizard**
Something flaky is going on with `test_inplace_view_saved_output` on Windows.

With my PR #20598 applied, the test fails, even though there is no obvious reason it should be related, so the PR was reverted.

Based on commenting out various parts of my change and re-building, I think the problem is with the name -- renaming everything from `T` to `asdf` seems to make the test stop failing. I can't be sure that this is actually the case though, since I could just be seeing patterns in non-deterministic build output...

I spoke with @colesbury offline and we agreed that it is okay to just disable this test on Windows for now and not block landing the main change. He will look into why it is failing.

**Test Plan:** I will wait to make sure the Windows CI suite passes before landing this.

### CODE REVIEW

**Review by colesbury — APPROVED** [review]

**Comment by ezyang** [comment]
Hypothesis: Windows is sorting capitalized names differently than uncapitalized names. If this is true, any `test_A` (where A is a capital letter) will trigger the problem, while `test_a` will not.

**Comment by umanwizard** [comment]
@ezyang I don't think it is related to the order of tests executing, since running `test_inplace_view_saved_output` in isolation exhibits the same behavior.

On the other hand, I wouldn't be surprised if capitalization is involved somehow, e.g. with symbols in the binary being sorted in a different order and invoking some kind of non-determinism.

**Review by gchanan — CHANGES_REQUESTED** [review]
you have onnx changes, otherwise looks good.

**Pull request closed without merging**
