### PR TITLE
[NNC] Adding more python bindings for missing operators

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #66612

Summary: For op authoring project, we want to expose the python bindings
to create Expr. These are the missing bindings.

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D31667852](https://our.internmc.facebook.com/intern/diff/D31667852)

### CODE REVIEW

**Review by ZolotukhinM — APPROVED** [review]
Might be worth adding a couple of tests for this, but otherwise looks good! Thanks for adding those :)

**Comment by anijain2305** [comment]
@anijain2305 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31667852).

**Review by bertmaher — COMMENTED** [review]
LGTM.  Kind of a comment for next time, but there's a lot of unrelated formatting changes in this PR, and it makes it hard to review the functionality changes.  In the future it'd be good to separate formatting into its own PR.  If you want them on the same branch (which totally makes sense), use ghstack to create stacked PRs.

(A sort of second-best option is to have the formatting contained in one commit in the PR, but stacked PRs is a better reviewer UX, as far as I'm concerned anyways).

**Comment by anijain2305** [comment]
> LGTM. Kind of a comment for next time, but there's a lot of unrelated formatting changes in this PR, and it makes it hard to review the functionality changes. In the future it'd be good to separate formatting into its own PR. If you want them on the same branch (which totally makes sense), use ghstack to create stacked PRs.
> 
> (A sort of second-best option is to have the formatting contained in one commit in the PR, but stacked PRs is a better reviewer UX, as far as I'm concerned anyways).

Thanks for the suggestion :) I will keep that in mind.

**Pull request closed without merging**
