### PR TITLE
Add optimal triton kernel parameters to bsr_dense_mm and scatter_mm for bfloat16 and float32 dtypes

### PR DESCRIPTION
**Pull request by pearu**
As in the title.

This PR is a follow-up to PR https://github.com/pytorch/pytorch/pull/112737 to address bfloat16 and float32 dtype cases. The performance increase is as follows (`NVIDIA A100-SXM4-80GB`):

- bsr_scatter_mm and bfloat16
  - for blocksize 16x16, the average/maximum speed up is about 29/75 %.
  - for blocksize 32x32, the average/maximum speed up is about 23/58 %.
  - for blocksize 64x64, the average/maximum speed up is about 27/66 %.
  - for blocksize 128x128, the average/maximum speed up is about 33/72 %.
- bsr_dense_mm and bfloat16
  - for blocksize 16x16, the average/maximum speed up is about 47/61 %.
  - for blocksize 32x32, the average/maximum speed up is about 29/43 %.
  - for blocksize 64x64, the average/maximum speed up is about 21/41 %.
  - for blocksize 128x128, the average/maximum speed up is about 12/29 %.
- bsr_dense_mm and  float32
  - for blocksize 16x16, the average/maximum speed up is about 35/49 %.
  - for blocksize 32x32, the average/maximum speed up is about 2/5 %.
  - for blocksize 64x64, the average/maximum speed up is about 2/21 %.
  - for blocksize 128x128, the average/maximum speed up is about 79/84 %.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #113553

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]
Great!

**Comment by malfet** [comment]
I wonder if it'll be better to keep those weights in `.json/.csv` file to keep code and data separate...

**Comment by pearu** [comment]
> I wonder if it'll be better to keep those weights in `.json/.csv` file to keep code and data separate...

@malfet Yes, this makes sense. Note that these weights are needed in runtime. It appears that currently pytorch does not exercise installing json or csv files as data files. Hence, storing the data in a python module was chosen.
If I was mistaken, pointers about acceptable approach to store data that is available in runtime, are appreciated.

**Pull request closed without merging**
