### PR TITLE
[quant][fix] Fix quantization for sub_scalar

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #64623
* __->__ #64603

Summary:
We'll insert observer only when both the operator and dtype is supported, both in reference and non-reference path

Test Plan:
python test/test_quantization.py TestQuantizeFx.test_sub_scalar

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D30797025](https://our.internmc.facebook.com/intern/diff/D30797025)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30797025).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30797025).

**Review by vkuzo — APPROVED** [review]
thank you!

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30797025).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30797025).

**Pull request closed without merging**
