### PR TITLE
[inductor] Triton codegen: Use scalar when creating f64 constant instead of 1-element tensor

### PR DESCRIPTION
**Pull request by masnesral**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136594

Summary: We have an internal report of a Triton compiler error `ValueError: Cannot broadcast, rank mismatch: [1], [1, 2048]` coming from a line like this:

`tmp25 = tl.broadcast_to(((tl.full([1], 1.00000000000000, tl.float64)) + ((ks0 // 3278).to(tl.float64))) / (((tl.full([1], 0.500000000000000, tl.float64))*(libdevice.sqrt((1 + ((ks0 // 3278)*(ks0 // 3278)) + ((-2)*(ks0 // 3278))).to(tl.float64).to(tl.float32)))) + ((tl.full([1], 0.500000000000000, tl.float64))*((1 + (ks0 // 3278)).to(tl.float64)))), [XBLOCK, RBLOCK])
`

https://github.com/pytorch/pytorch/pull/135260 is the cause, presumably because we turn a constant into a 1-element tensor with: `(tl.full([1], const, tl.float64))`. It looks like changing the syntax to `(tl.full([], const, tl.float64))` gives us what we want?

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

Differential Revision: [D63465169](https://our.internmc.facebook.com/intern/diff/D63465169)

### CODE REVIEW

**Comment by masnesral** [comment]
@masnesral has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D63360293).

**Review by mengluy0125 — APPROVED** [review]

**Comment by masnesral** [comment]
@jansel would you mind taking a look? mengluy0125 verified this fixes the internal usage. Also, I've so far failed to reverse what PyTorch code would generate this particular pattern of a broadcast_to with an fp64 arg. If you know what would do that, I could also add a unit test.

**Review by jansel — APPROVED** [review]

**Comment by masnesral** [comment]
@masnesral has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D63465169).

**Review by mengluy0125 — APPROVED** [review]

**Comment by masnesral** [comment]
Starting fresh with: https://github.com/pytorch/pytorch/pull/136858

**Pull request closed without merging**
