### PR TITLE
[doc] scale parameter notation for torch.Tensor.cauchy_ is misleading

### LINKED ISSUE #113426: [doc] scale parameter notation for torch.Tensor.cauchy_ is misleading
### 📚 The doc issue

Scale parameter notation currently used for torch.Tensor.cauchy_ is misleading.
Sigma (σ) is usually used to denote square root of variance. Variance is undefined in Cauchy distribution.
Replace sigma (σ) with gamma (γ).

Background: https://github.com/pytorch/pytorch/pull/37984#discussion_r1059551749

cc @fritzo @neerajprad @alicanb @nikitaved @svekars @carljparker

Implemented by https://github.com/pytorch/pytorch/pull/113178

### Suggest a potential alternative/fix

_No response_

### PR DESCRIPTION
**Pull request by min-jean-cho**
Fixes https://github.com/pytorch/pytorch/issues/113426.

Scale parameter notation currently used for `torch.Tensor.cauchy_` is misleading. 
Sigma (σ) is usually used to denote square root of variance. Variance is undefined in Cauchy distribution. 
Replace sigma (σ) with gamma (γ). 

Background: https://github.com/pytorch/pytorch/pull/37984#discussion_r1059551749

cc @svekars @carljparker

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Hey!
Thanks for suggesting the update.

I do think we should preserve the name in the formula to match the function argument though.
Adding a note mentioning that sigma can be surprising here and actually only represents the scaling. It would be great to update the note here to only talk about that and explaining the history (of it being sigma before and now gamma) is not useful.

**Comment by min-jean-cho** [comment]
Thanks @albanD! How about like this?

**Comment by min-jean-cho** [comment]
Or would just `Sigma(σ) is used to denote the scale parameter in Cauchy distribution.` be better for simplicity?

**Comment by albanD** [comment]
> Or would just Sigma(σ) is used to denote the scale parameter in Cauchy distribution. be better for simplicity?

Yes that sounds good.

**Comment by min-jean-cho** [comment]
Thanks, updated!

**Comment by carljparker** [comment]
@albanD: Could you approve; this change looks good to me.

**Review by mingxzhao — APPROVED** [review]

**Review by albanD — APPROVED** [review]
Thanks!

**Pull request closed without merging**
