### PR TITLE
Add typing return value to init in nn.Module

### LINKED ISSUE #45497: torch.Module typing __init__ no return value
__init__ return value should be specified as None. Now it doesn't have any
https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L223

https://www.python.org/dev/peps/pep-0484/#the-meaning-of-annotations

cc @albanD @mruberry @ezyang @malfet @rgommers @xuzhao9 @gramster

### PR DESCRIPTION
**Pull request by Vozf**
Fixes #45497

### CODE REVIEW

**Review by mrshenli — APPROVED** [review]
Thanks for fixing!

**Comment by rgommers** [comment]
@mrshenli was there an issue with internal CI in landing this?

**Comment by DavidMChan** [comment]
This is still an issue as of Jul 6, 2021 - Is there any plan to look deeper into this?

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Had to revert PR as it broke mypy checks, proper fix is in  https://github.com/pytorch/pytorch/pull/61334

**Pull request closed without merging**
