### PR TITLE
Add comparison operators to Vec256<BFloat16>

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#36106 Add comparison operators to Vec256<BFloat16>**
* #35844 Use templates instead of macro when defining Vec256<BFloat16> bin operators

Differential Revision: [D20927638](https://our.internmc.facebook.com/intern/diff/D20927638)

### CODE REVIEW

**Comment by XiaobingSuper** [comment]
@xuhdev , there has PR https://github.com/pytorch/pytorch/pull/35092 doing this, in progress of landing. Thanks!

**Comment by xuhdev** [comment]
@XiaobingSuper I've resolved conflicts. Please review, thanks!

**Comment by ngimel** [comment]
@xuhdev @XiaobingSuper I'm confused, the previous PR in this stack enables +-/* operations for bfloat16 which are already enabled in one of @XiaobingSuper's PRs? If the previous PR is not actually needed can you close it and have this PR unstacked?

**Comment by xuhdev** [comment]
@ngimel The previous PR is a cleanup of the operators -- it did not add the operators

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
