### PR TITLE
Fix The Error of TypeError: list indices must be integers or slices, not list 

### PR DESCRIPTION
**Pull request by kaiyuyue**
When using the customized batch sampler for the dataloader, the `batch_indices` maybe be wrapped again in a list. This behavior will cause the `TypeError: list indices must be integers or slices, not list` like this:

```bash
Traceback (most recent call last):
  File "train.py", line 402, in <module>
    main()
  File "train.py", line 137, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 259, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "train.py", line 293, in train
    for i, (input, target) in enumerate(train_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 778, in __next__
    return self._process_data(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 810, in _process_data
    raise data.exc_type(data.exc_msg)
TypeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 177, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/lib/dataloader.py", line 55, in __getitem__
    idx = self.idxs[index]
TypeError: list indices must be integers or slices, not list
```

This PR will add some lines of code to clean the `possibly_batched_index` in `fetch.py`.

### CODE REVIEW

**Review by zou3519 — CHANGES_REQUESTED** [review]
Tests are failing

**Comment by KaiyuYue** [comment]
> Tests are failing

On GPU? The original `fetch.py` works well with using CPU, but will fail on GPU.

**Comment by zou3519** [comment]
Getting
```
Jul 16 13:22:39 ======================================================================
Jul 16 13:22:39 ERROR: test_builtin_collection_conversion (__main__.TestDataLoader)
Jul 16 13:22:39 ----------------------------------------------------------------------
Jul 16 13:22:39 Traceback (most recent call last):
Jul 16 13:22:39   File "test_dataloader.py", line 826, in test_builtin_collection_conversion
Jul 16 13:22:39     fetched = coll_ty(DataLoader(dataset, batch_size=None, num_workers=num_workers))
Jul 16 13:22:39   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 310, in __next__
Jul 16 13:22:39     data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
Jul 16 13:22:39   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/_utils/fetch.py", line 45, in fetch
Jul 16 13:22:39     if len(possibly_batched_index) == 1 and isinstance(possibly_batched_index[0], list):
Jul 16 13:22:39 TypeError: object of type 'int' has no len()
Jul 16 13:22:39 
Jul 16 13:22:39 ======================================================================
Jul 16 13:22:39 ERROR: test_sequential_nonbatch (__main__.TestDataLoader)
Jul 16 13:22:39 ----------------------------------------------------------------------
Jul 16 13:22:39 Traceback (most recent call last):
Jul 16 13:22:39   File "test_dataloader.py", line 714, in test_sequential_nonbatch
Jul 16 13:22:39     self._test_sequential(DataLoader(self.dataset, batch_size=None))
Jul 16 13:22:39   File "test_dataloader.py", line 654, in _test_sequential
Jul 16 13:22:39     for idx, (sample, target) in enumerate(loader):
Jul 16 13:22:39   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 310, in __next__
Jul 16 13:22:39     data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
Jul 16 13:22:39   File "/opt/python/2.7.9/lib/python2.7/site-packages/torch/utils/data/_utils/fetch.py", line 45, in fetch
Jul 16 13:22:39     if len(possibly_batched_index) == 1 and isinstance(possibly_batched_index[0], list):
Jul 16 13:22:39 TypeError: object of type 'int' has no len()
```
 on https://circleci.com/gh/pytorch/pytorch/2201311?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link , which sounds like it is related to your change but I am not sure.

**Comment by zou3519** [comment]
Cool, tests look fine now, thank you @KaiyuYue.

I'm not very familiar with the rest of the code, though. @SsnL could you take a look at this when you get a chance?

**Review by ssnl — CHANGES_REQUESTED** [review]
No this isn't right. Did you pass the custom sampler correctly as `batch_sampler`? It should work correctly.

**Comment by KaiyuYue** [comment]
Oh. Shit. Yeah, it's my bad. I pass the 'batch_sampler' into `sampler` not `batch_sampler`. Sorry about this.

**Pull request closed without merging**
