### PR TITLE
ROCm enable sparse_sampled_addmm

### PR DESCRIPTION
**Pull request by jpvillam-amd**
Enables:
test_comprehensive_sparse_sampled_addmm_cuda_complex128
test_comprehensive_sparse_sampled_addmm_cuda_complex64
test_comprehensive_sparse_sampled_addmm_cuda_float32
test_comprehensive_sparse_sampled_addmm_cuda_float64
test_dispatch_meta_sparse_sampled_addmm_cuda_complex128
test_dispatch_meta_sparse_sampled_addmm_cuda_complex64
test_dispatch_meta_sparse_sampled_addmm_cuda_float32
test_dispatch_meta_sparse_sampled_addmm_cuda_float64
test_meta_sparse_sampled_addmm_cuda_complex128
test_meta_sparse_sampled_addmm_cuda_complex64
test_meta_sparse_sampled_addmm_cuda_float32
test_meta_sparse_sampled_addmm_cuda_float64

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
Lint errors are real, otherwise lgtm

**Comment by jpvillam-amd** [comment]
```
    test_comprehensive_sparse_sampled_addmm_cuda_complex128 (__main__.TestDecompCUDA) ... ok (0.187s)
    test_comprehensive_sparse_sampled_addmm_cuda_complex64 (__main__.TestDecompCUDA) ... ok (0.091s)
    test_comprehensive_sparse_sampled_addmm_cuda_float32 (__main__.TestDecompCUDA) ... ok (0.072s)
    test_comprehensive_sparse_sampled_addmm_cuda_float64 (__main__.TestDecompCUDA) ... ok (0.074s)
``` 
From: https://github.com/pytorch/pytorch/actions/runs/3201111231/jobs/5228949868#step:8:22000



```
    test_dispatch_meta_sparse_sampled_addmm_cuda_complex128 (__main__.TestMetaCUDA) ... ok (0.029s)
    test_dispatch_meta_sparse_sampled_addmm_cuda_complex64 (__main__.TestMetaCUDA) ... ok (0.010s)
    test_dispatch_meta_sparse_sampled_addmm_cuda_float32 (__main__.TestMetaCUDA) ... ok (0.009s)
    test_dispatch_meta_sparse_sampled_addmm_cuda_float64 (__main__.TestMetaCUDA) ... ok (0.009s)
```

From: https://github.com/pytorch/pytorch/actions/runs/3201111231/jobs/5228949868#step:8:6521



```
    test_meta_sparse_sampled_addmm_cuda_complex128 (__main__.TestMetaCUDA) ... ok (0.010s)
    test_meta_sparse_sampled_addmm_cuda_complex64 (__main__.TestMetaCUDA) ... ok (0.010s)
    test_meta_sparse_sampled_addmm_cuda_float32 (__main__.TestMetaCUDA) ... ok (0.009s)
    test_meta_sparse_sampled_addmm_cuda_float64 (__main__.TestMetaCUDA) ... ok (0.010s)
```

From: https://github.com/pytorch/pytorch/actions/runs/3201111231/jobs/5228949868#step:8:11747

**Comment by jpvillam-amd** [comment]
I think the 1 failed check is from a XML reporting tool segfault
```

OK (skipped=12, expected failures=2)

Generating XML reports...
Generated XML report: test-reports/python-unittest/test_autograd/TEST-TestAutograd-20221007003900.xml
Generated XML report: test-reports/python-unittest/test_autograd/TEST-autograd.test_complex.TestAutogradComplex-20221007003900.xml
Generated XML report: test-reports/python-unittest/test_autograd/TEST-TestAutogradDeviceTypeCUDA-20221007003900.xml
Generated XML report: test-reports/python-unittest/test_autograd/TEST-TestAutogradForwardMode-20221007003900.xml
Generated XML report: test-reports/python-unittest/test_autograd/TEST-TestAutogradForwardModeBatchedGrad-20221007003900.xml
Generated XML report: test-reports/python-unittest/test_autograd/TEST-autograd.test_functional.TestAutogradFunctional-20221007003900.xml
Generated XML report: test-reports/python-unittest/test_autograd/TEST-TestAutogradInferenceMode-20221007003900.xml
Generated XML report: test-reports/python-unittest/test_autograd/TEST-TestAutogradMultipleDispatchCUDA-20221007003900.xml
Generated XML report: test-reports/python-unittest/test_autograd/TEST-TestMultithreadAutograd-20221007003900.xml
[db1a429837ff:11768:0:11842] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x9)

FINISHED PRINTING LOG FILE of test_autograd (/var/lib/jenkins/workspace/test/test-reports/test_autograd_u5hojsgw)

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/run_test.py", line 1236, in <module>
    main()
  File "/var/lib/jenkins/workspace/test/run_test.py", line 1211, in main
    raise RuntimeError(err_message)
RuntimeError: test_autograd failed! Received signal: SIGSEGV
```

Don't think that is related to this PR. @jithunnair-amd

**Pull request closed without merging**
