### PR TITLE
Move Sympy printers to torch/utils/_sympy/printers.py

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #140756
* #139899
* #140968
* __->__ #140597

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @SherlockNoMad @EikanWang @wenzhe-nrv @voznesenskym @penguinwu @Guobing-Chen @zhuhaozhe @blzheng @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Review by anijain2305 — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but I think it fails inductor/test_padding in trunk. This is a target determination miss and that failed test was not run in your PR' -c nosignal

inductor/test_padding.py::PaddingTest::test_nobias_LinearAndSoftmax_codegen [GH job link](https://github.com/pytorch/pytorch/actions/runs/11941195446/job/33287461307) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/aefcdb3c9fa787f9d43864f6f99a3590c914324a)

**Comment by huydhn** [comment]
cc @clee2000 Is this expected to see more tests being excluded than selected in https://ossci-raw-job-status.s3.amazonaws.com/log/33277389840?  test_padding was one of the excluded one

**Comment by isuruf** [comment]
Thanks @huydhn for linking the test failures. I've fixed these tests now. Do I need to add some more labels before we try to re-land the PR?

**Comment by huydhn** [comment]
> Thanks @huydhn for linking the test failures. I've fixed these tests now. Do I need to add some more labels before we try to re-land the PR?

It should be good to land now.  Just FYI, when a PR is reverted, a label call `ci-no-td` is automatically added to it so that all tests will be run on the reland PR

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Trunk is sad again after this lands, this looks like a landrace this time, so please do a rebase' -c landrace 

export/test_cpp_serdes.py::CppSerdesTestExport::test_automatic_dynamic_shapes_linear_relation_cpp_serdes [GH job link](https://github.com/pytorch/pytorch/actions/runs/11965103059/job/33363817713) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/c25b201583fc28243b87c460a2f18e2531a676e7)

**Pull request closed without merging**
