### PR TITLE
[EZ] Fix simple bug in torchdynamo

### PR DESCRIPTION
**Pull request by tugsbayasgalan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #87821

cc @jansel @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by tugsbayasgalan** [comment]
@pytorch merge -f "flaky test"

**Comment by kit1980** [comment]
> @pytorchbot merge -f "flaky test"

@tugsbayasgalan the failures on the PR look very related, with lots of these in the logs:

```
2022-10-27T05:02:53.8752022Z [2022-10-27 05:01:59,264] torch._dynamo.convert_frame: [ERROR] WON'T CONVERT __init__ test_jit.py line 9077 
2022-10-27T05:02:53.8752091Z due to: 
2022-10-27T05:02:53.8752182Z Traceback (most recent call last):
2022-10-27T05:02:53.8752443Z   File "/opt/conda/lib/python3.7/site-packages/torch/_dynamo/variables/base.py", line 137, in as_python_constant
2022-10-27T05:02:53.8752554Z     raise NotImplementedError(f"{self} is not a constant")
2022-10-27T05:02:53.8752718Z NotImplementedError: UserDefinedObjectVariable(ScriptMeta) is not a constant
2022-10-27T05:02:53.8752724Z 
2022-10-27T05:02:53.8752792Z from user code:
2022-10-27T05:02:53.8752893Z    File "test_jit.py", line 9078, in __init__
2022-10-27T05:02:53.8752976Z     super(Sub, self).__init__()
```

**Comment by malfet** [comment]
> @pytorchbot merge -f "flaky test"

Hmm, a bit curios why dynamo specific change that causes failure in dynamo shard only is considered a flaky failure?

**Pull request closed without merging**
