### PR TITLE
[AOTI] Add standalone version of TORCH_CHECK

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #136534
* __->__ #136873

Summary: In the standalone mode, TORCH_CHECK throws std::runtime_error, instead of c10::Error. The goal is to cut dependency on libtorch. Specifically, AOTI generates CPU code which may call ATen vectorization ops and we need to make sure those ops are self-contained.

Differential Revision: [D63911928](https://our.internmc.facebook.com/intern/diff/D63911928)

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @chauhang

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
I'm a bit surprised by this change. c10::Error gives a lot of niceties like stack traces tracking, internal logging, TORCH_SHOW_CPP_STACKTRACES, etc
Also this is going to change the error we give to the python users?

**Comment by desertfire** [comment]
> I'm a bit surprised by this change. c10::Error gives a lot of niceties like stack traces tracking, internal logging, TORCH_SHOW_CPP_STACKTRACES, etc Also this is going to change the error we give to the python users?

I think we have to give up some properties if we want to make Vectorized ABI-compatible. The first attempt I made was to make c10::Error header-only, but it is not easy with something like https://github.com/pytorch/pytorch/blob/2b329d3bf1a23cef96e2ffd1cd45f542a95daf5f/c10/util/Exception.h#L61-L63 . I am open to other suggestion if you have a better idea.

**Comment by albanD** [comment]
Making this particular call go through the capi shim should be relatively simple though given the types involved right?

**Comment by desertfire** [comment]
> Making this particular call go through the capi shim should be relatively simple though given the types involved right?

If we give up on supporting varargs for this one, then yes.

**Comment by albanD** [comment]
Ho we were actually chatting about this one with Jane earlier, wouldn't we be able to do the conversion vararg -> string in a header-only c++ layer and make the raw c api take a single raw string?

**Review by albanD — APPROVED** [review]
Sounds ok as a temporary unblock, let's discuss offline for broader plan and how to ensure this is preserved.

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D63911928).

**Review by chenyang78 — APPROVED** [review]

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D63911928).

**Pull request closed without merging**
