### PR TITLE
Fix public binding to actually traverse modules

### PR DESCRIPTION
**Pull request by albanD**
The current call passes in `['/actual/path']` to os.walk which is a string pointing to no path and thus silently leads to and empty traversal.
There is an unused function just above that handles that, so I guess this is what was supposed to be called.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @ezyang @gchanan @LucasLLC

### CODE REVIEW

**Review by suo — APPROVED** [review]

**Comment by albanD** [comment]
``
@pytorchbot merge

**Comment by kit1980** [comment]
This is actually bc-breaking as it removed `torch.cuda.amp.grad_scaler.OptState` API

**Pull request closed without merging**
