### PR TITLE
Add windows docs for the binaries

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by ezyang** [comment]
Good start. Let me know when you want to merge.

**Review by ezyang — APPROVED** [review]
I'm OK to merge this whenever you want.

**Comment by ezyang** [comment]
Updates on this one? :) Shall I just merge it as is

**Comment by peterjc123** [comment]
@ezyang Sorry,I just don't have time to update it these days.

**Comment by ezyang** [comment]
OK I'll merge as is

**Comment by VitalyFedyunin** [comment]
Needs rebase

**Comment by peterjc123** [comment]
Rebased!

**Pull request closed without merging**
