### PR TITLE
[Fix]: Update CPUINFO submodule to fix support for NON-SVE ARM Hardware

### PR DESCRIPTION
**Pull request by nikhil-arm**
Regression PR : https://github.com/pytorch/cpuinfo/pull/255

Change-Id: I56cec061072be11ec33ccb661114360b979fc7aa

cc @malfet @snadampal @milpuz01

### CODE REVIEW

**Comment by ng-05** [comment]
cc: @malfet @maajidkhann @digantdesai can we please add aarch64 ci label to it. I dont have permission to do it

**Comment by ng-05** [comment]
CPUINFO Fix PR: https://github.com/pytorch/cpuinfo/pull/258

**Review by digantdesai — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by ng-05** [comment]
Please merge this

**Comment by maajidkhann** [comment]
> We still see the timeout issue on test cases. @maajidkhann as I suspected before, this will not fix the timeout issue

I think this PR https://github.com/pytorch/cpuinfo/pull/258 fixed the error we were getting in these pipelines.

**Error:**
https://github.com/pytorch/pytorch/actions/runs/10777650193/job/29891036346?pr=119571#step:20:6914

upp

we don't see this error anymore in these pipelines.

I am not sure of the reason why this timeout issue is coming now in these pipelines.

**Pull request closed without merging**
