### PR TITLE
Migrate update-commit-hash to test-infra

### PR DESCRIPTION
**Pull request by huydhn**
After https://github.com/pytorch/test-infra/pull/4885, the GHA is now reusable on `test-infra`.  This tests the change and we can also land it after https://github.com/pytorch/test-infra/pull/4885 lands.

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Review by atalman — APPROVED** [review]

**Review by malfet — COMMENTED** [review]
From security PoV my concern with this change(and others), is that pytorch/pytorch trust pytorch/test-infra@main to always to be "safe", i.e. not misuse/steal the tokens, which I don't think is spelled anywhere

**Comment by huydhn** [comment]
> From security PoV my concern with this change(and others), is that pytorch/pytorch trust pytorch/test-infra@main to always to be "safe", i.e. not misuse/steal the tokens, which I don't think is spelled anywhere

This requires a bit more dev works, so let me create an issue to track that.  In short, we want:

* Versioning of shareable GHA on test-infra like Nova
* Carter for the use case of pinning release branch there, i.e. `@release/2.2`

**Pull request closed without merging**
