### PR TITLE
[DeviceMesh] Add get_all_submeshes in _MeshEnv

### PR DESCRIPTION
**Pull request by wz337**
Adding a private helper method for Shampoo HSDP use cases. 

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by XilunWu — APPROVED** [review]
quick stamp to unblock. Any further plan on this functionality?

**Comment by wz337** [comment]
> quick stamp to unblock. Any further plan on this functionality?

Just to add to help the user for now. If we don’t see common use case, maybe I’ll remove it and make it an internal util from the user side instead.

**Pull request closed without merging**
