### PR TITLE
[dynamo] Cache _dynamo.disable results

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134272

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by yf225 — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by anijain2305** [comment]
Closing this because it resulted in major peak memory increase, and this would have been hard to find. User can use torch._disable_dynamo, which has caching layer

**Comment by albanD** [comment]
btw the memory leak is because you now have a strong reference to the function being disabled in this global dict. So if this function happened to capture Tensor or any other object, you are leaking these. This leads to memory explosion in FlexAttention for example

**Pull request closed without merging**
