### PR TITLE
Added aten.bernoulli.p and aten.bernoulli.default decompositions

### LINKED ISSUE #105519: aten.bernoulli.p is missing in core aten IR opset but does not get decomposed
### 🐛 Describe the bug

`aten.bernoulli.p` should either be decomposed or should be in core IR opset.

```python
import torch
from torch._functorch.aot_autograd import aot_module_simplified
from torch._decomp import core_aten_decompositions

decompositions = core_aten_decompositions()

def toy_backend(gm, sample_inputs):
    def my_compiler(gm, sample_inputs):
        gm.print_readable()
        return gm

    # Invoke AOTAutograd
    return aot_module_simplified(
        gm,
        sample_inputs,
        decompositions=decompositions,
        fw_compiler=my_compiler
    )

def run(input):
  return torch.bernoulli(input, 0.5)

input = torch.randn(8, 32)

out = run(input)
print("EAGER OK")

fn = torch.compile(backend=toy_backend)(run)
out = fn(input)
```

produces the following graph

```
EAGER OK
class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: f32[8, 32]):
        # File: bug_bernoull.py:26, code: return torch.bernoulli(input, 0.5)
        bernoulli: f32[8, 32] = torch.ops.aten.bernoulli.p(arg0_1, 0.5);  arg0_1 = None
        return (bernoulli,)
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230718+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       12
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz
Stepping:                        0
CPU MHz:                         2194.843
BogoMIPS:                        4389.68
Virtualization:                  VT-x
Hypervisor vendor:               VMware
Virtualization type:             full
L1d cache:                       384 KiB
L1i cache:                       384 KiB
L2 cache:                        12 MiB
L3 cache:                        429 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX flush not necessary, SMT disabled
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xsaves arat pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] torch==2.1.0.dev20230718+cpu
[pip3] triton==2.0.0
[conda] Could not collect

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @SherlockNoMad @wconstab

### PR DESCRIPTION
**Pull request by zero000064**
Fixes #105519

Added aten.bernoulli.p decomposition and moved/rewrote aten.bernoulli.deafult to make them included in core aten decomposition. 

Tested the sample code in [105519](https://github.com/pytorch/pytorch/issues/105519), torch.bernoulli could be decomposed by the code snippet.

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @gujinghui @PenghuiCheng @jianyuh @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal @voznesenskym @penguinwu @EikanWang @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @xmfan

### CODE REVIEW

**Comment by zero000064** [comment]
@eellison @mlazos could you review this pull request?

**Comment by zero000064** [comment]
@eellison @mlazos 
I messed up the branch and recovered it, but there're many new reviewers and label added by pytorchbot,
how to remove them?

```
@[zero000064](https://github.com/zero000064) zero000064 requested review from [eqy](https://github.com/eqy), [syed-ahmed](https://github.com/syed-ahmed), [mikaylagawarecki](https://github.com/mikaylagawarecki), [avikchaudhuri](https://github.com/avikchaudhuri), [tugsbayasgalan](https://github.com/tugsbayasgalan), [zhxchen17](https://github.com/zhxchen17) and [ydwu4](https://github.com/ydwu4) as [code owners](https://github.com/pytorch/pytorch/blob/99c8d5af278edf14aab168f3c98fa67b601b1b62/CODEOWNERS#L167) [51 minutes ago](https://github.com/pytorch/pytorch/pull/139141#event-15292933512)
@[zero000064](https://github.com/zero000064) zero000064 requested review from [angelayi](https://github.com/angelayi), [EikanWang](https://github.com/EikanWang), [gujinghui](https://github.com/gujinghui), [jeffdaily](https://github.com/jeffdaily), [jithunnair-amd](https://github.com/jithunnair-amd), [ezyang](https://github.com/ezyang), [Chillee](https://github.com/Chillee), [sraikund16](https://github.com/sraikund16), [egienvalue](https://github.com/egienvalue), [kulinseth](https://github.com/kulinseth), [malfet](https://github.com/malfet), [bdhirsh](https://github.com/bdhirsh), [zou3519](https://github.com/zou3519), [kshitij12345](https://github.com/kshitij12345), [mruberry](https://github.com/mruberry), [lezcano](https://github.com/lezcano) and [nikitaved](https://github.com/nikitaved) as [code owners](https://github.com/pytorch/pytorch/blob/99c8d5af278edf14aab168f3c98fa67b601b1b62/CODEOWNERS#L154) [51 minutes ago](https://github.com/pytorch/pytorch/pull/139141#event-15292933595)
@[zero000064](https://github.com/zero000064) zero000064 requested review from [IvanYashchuk](https://github.com/IvanYashchuk), a team, [titaiwangms](https://github.com/titaiwangms), [shubhambhokare1](https://github.com/shubhambhokare1), [justinchuby](https://github.com/justinchuby), [wschin](https://github.com/wschin), [jiayisuse](https://github.com/jiayisuse), [osalpekar](https://github.com/osalpekar), [lw](https://github.com/lw), [jerryzh168](https://github.com/jerryzh168), [salilsdesai](https://github.com/salilsdesai), [kimishpatel](https://github.com/kimishpatel), [digantdesai](https://github.com/digantdesai), [jianyuh](https://github.com/jianyuh), [albanD](https://github.com/albanD), [janeyx99](https://github.com/janeyx99), [jbschlosser](https://github.com/jbschlosser) and [soulitzer](https://github.com/soulitzer) as [code owners](https://github.com/pytorch/pytorch/blob/99c8d5af278edf14aab168f3c98fa67b601b1b62/CODEOWNERS#L80) [51 minutes ago](https://github.com/pytorch/pytorch/pull/139141#event-15292933757)
@[pytorch-bot](https://github.com/apps/pytorch-bot) pytorch-bot bot added [module: compiled autograd](https://github.com/pytorch/pytorch/labels/module%3A%20compiled%20autograd) [module: cpu](https://github.com/pytorch/pytorch/labels/module%3A%20cpu) [module: dynamo](https://github.com/pytorch/pytorch/labels/module%3A%20dynamo) [module: mkldnn](https://github.com/pytorch/pytorch/labels/module%3A%20mkldnn) [oncall: distributed](https://github.com/pytorch/pytorch/labels/oncall%3A%20distributed) [release notes: quantization](https://github.com/pytorch/pytorch/labels/release%20notes%3A%20quantization) labels [50 minutes ago](https://github.com/pytorch/pytorch/pull/139141#event-15292935881)
@[zero000064](https://github.com/zero000064) zero000064 [force-pushed](https://github.com/pytorch/pytorch/compare/ce2f4521fb80976245051598925219970ff65384..e5cf99543f66aed629dfb5be37bad698faa6bf0b) the decomposition branch from [ce2f452 ](https://github.com/pytorch/pytorch/commit/ce2f4521fb80976245051598925219970ff65384)to [e5cf995 ](https://github.com/pytorch/pytorch/commit/e5cf99543f66aed629dfb5be37bad698faa6bf0b)
[24 minutes ago](https://github.com/pytorch/pytorch/pull/139141#event-15293136276)
@[pytorch-bot](https://github.com/apps/pytorch-bot) pytorch-bot bot added the [ciflow/inductor](https://github.com/pytorch/pytorch/labels/ciflow%2Finductor) label [24 minutes ago](https://github.com/pytorch/pytorch/pull/139141#event-15293136686)
```

**Comment by zero000064** [comment]
@eellison Unable to reproduce the triton failure in my local machine, my triton doesn't have CPU backend, how to enable that?
```
{'nvidia': Backend(compiler=<class 'nvi.CUDABackend'>, driver=<class 'nvi.CudaDriver'>), 'amd': Backend(compiler=<class '.HIPBackend'>, driver=<class '.HIPDriver'>)}
```

**Comment by eellison** [comment]
@zero000064 @int3 is on pto for the week. triton cpu is still in early stages so I would suggest just skipping and landing.

**Comment by zero000064** [comment]
@eellison that sounds good, could you review the change and let me know what to change?

**Comment by eellison** [comment]
add `skip_if_triton_cpu` around failing test

**Comment by zero000064** [comment]
@eellison added skip_if_triton_cpu for the failed test, no test failure.

**Review by eellison — APPROVED** [review]

**Comment by zero000064** [comment]
@eellison given [the trunk failure](https://hud.pytorch.org/pytorch/pytorch/pull/139141?sha=2c21783de01fa709337561a5b4525c3ab9bb611f), I relaxed the contraint.
I use two sigma of which one sigma is 0.03.
Could you review this change?
```
2024-11-19T21:05:51.9025290Z - generated xml file: /Users/ec2-user/runner/_work/pytorch/pytorch/test/test-reports/python-pytest/test_decomp/test_decomp-bc5a7edc17b38950.xml -
2024-11-19T21:05:51.9026190Z =========================== short test summary info ============================
2024-11-19T21:05:51.9027160Z FAILED [0.0023s] test_decomp.py::TestDecompCPU::test_bernoulli_p_cpu - AssertionError: Scalars are not close!
```

**Comment by zero000064** [comment]
Checked test failures from https://hud.pytorch.org/pr/pytorch/pytorch/139141#33249051301, none of them looks related to my change.

**Comment by zero000064** [comment]
@eellison checked those 3 test failures, they fail by 
```
upload the benchmark results to OSS benchmark database: error: test/test-reports is not a valid directory
```
Looks unrelated to my change.

**Pull request closed without merging**
