### PR TITLE
Add Block-wise Pruning function

### PR DESCRIPTION
**Pull request by shimoshida**
Provides the implementation for feature request issue #39765.

One of the main-stream pruning techniques is "Block-wise Pruning", 
which eliminate weights such that the number of non-zero weights in each block is equal. 

For example, the following papers use block-wise pruning
- (Block-size) Conference Paper name
- (Layer)NIPS15 Learning both Weights and Connections for Efficient
Neural Networks
- (Vector-Inch)FPGA19, Efficient and Effective Sparse LSTM on FPGA with
Bank-Balanced Sparsity
- (Vector-Inch)IEEE Trans. on Circuits and Systems for Video Technology, Accelerator-aware pruning for convolutional neural networks

The block-wise pruning improve imbalanced loading problem occurred by pruning without constraints, 
and I believe the block-wise pruning might be helpful. 
Thus, I have developed the block-wise pruning function and class, 
"blockwise_unstructured", "BlockwiseUnstructured". 
Supporting block sizes are as follows:
- layer
- filter
- kernel
- vector(inch, kernel y-axis, kernel x-axis)

How to use is shown as following: 
```
>>> from torch import nn
>>> import torch.nn.utils.prune as prune
>>> module = nn.Conv2d(4, 6, 3)
>>> print(list(module.named_buffers()))
[]
>>> prune.blockwise_unstructured(module, name="weight", amount=0.5, block_type="vector-inch", block_size=2)
Conv2d(4, 6, kernel_size=(3, 3), stride=(1, 1))
>>> list(module.named_buffers())[0][1].sum(1)
tensor([[[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]])
```

### CODE REVIEW

**Comment by pbelevich** [comment]
I believe that @mickypaganini is the best candidate for reviewer, but I can't assign it to them because they are not a member of this repo :(

**Comment by mickypaganini** [comment]
@pbelevich I was just added to the team and can now review. I added myself as reviewer.

**Comment by he-y** [comment]
@shimoshida 
Do you think adding the related publication and the difference of the implement and the publication, to the function header, is helpful? 

For example, [ResNet bottleneck code](https://github.com/pytorch/vision/blob/7c077f6a986f05383bcb86b535aedb5a63dd5c4b/torchvision/models/resnet.py#L75-L80) add the publication and the detailed variant. Besides,[DenseNet](https://github.com/pytorch/vision/blob/f8e2291df81aa4e395b1caf919c2e43ebf30c127/torchvision/models/densenet.py#L126-L140) also add corresponding paper and variant method.

**Comment by shimoshida** [comment]
@he-y 
Thanks for the comments. 
Yes, I believe that the illustrations in the related papers help beginners to understand what is block-wise pruning. 
Unfortunately, my implementation is difficult to understand intuitively. 

Ideally, I would like to show a paper and how to implement the paper's pruning in pytorch as samples in the function header.

**Pull request closed without merging**
