### PR TITLE
Use int64 in pdist kernel to handle batches >= 46342 #30583

### PR DESCRIPTION
**Pull request by ptrblck**
Currently `torch.pdist` yields an illegal CUDA memory access for batch sizes >= 46342 as reported by @SsnL in #30583.
Thanks for the minimal code reproduction, btw! ;)

Reason for this bug:
The calculation if `i` in the [`pdist_kerne_cuda_impl`](https://github.com/pytorch/pytorch/blob/46ad80c8395379be5ba17624fd5dbad8e7a8e8d2/aten/src/ATen/native/cuda/DistanceKernel.cu#L112) might overflow, if a tensor with a `batch size >= 46342` is passed to `torch.pdist`.

Detailed description:
* `result` is resizes as ` n * (n - 1) / 2 = 1073767311` ([line of code](https://github.com/pytorch/pytorch/blob/46ad80c8395379be5ba17624fd5dbad8e7a8e8d2/aten/src/ATen/native/Distance.cpp#L140))
* `grid` is initialized as `result.numel()` ([line of code](https://github.com/pytorch/pytorch/blob/46ad80c8395379be5ba17624fd5dbad8e7a8e8d2/aten/src/ATen/native/cuda/DistanceKernel.cu#L246))
* `k` is assigned to the `blockIdx.x` as an `int32` ([line of code](https://github.com/pytorch/pytorch/blob/46ad80c8395379be5ba17624fd5dbad8e7a8e8d2/aten/src/ATen/native/cuda/DistanceKernel.cu#L108))
* `i` is calculated using `2 * k >= 2147534622` ([line of code](https://github.com/pytorch/pytorch/blob/46ad80c8395379be5ba17624fd5dbad8e7a8e8d2/aten/src/ATen/native/cuda/DistanceKernel.cu#L112)), which overflows, since `2147534622 > 2147483647 (int32_max)`.

Using `const int64_t k = blockIdx.x;` would solve the illegal memory access. This seems also be done for [`cdist_kernel_cuda_impl`](https://github.com/pytorch/pytorch/blob/46ad80c8395379be5ba17624fd5dbad8e7a8e8d2/aten/src/ATen/native/cuda/DistanceKernel.cu#L198-L201).

However, we might expect a slowdown, so I've timed the current PyTorch master vs. this PR:
(tested with `x = torch.randn(x.size(0), 128)` on a V100)

 |x.size(0) | int32 idx | int64 idx | slowdown |
 |----------|-----------|-----------|----------|
| 50000 | -              | 4.4460 | - |
| 25000 | 1.02522 | 1.10869 | 7.53% |
| 12500 | 0.25182 | 0.27277 | 7.68% |
| 6250 | 0.06291 | 0.06817 | 7.72% |
| 3125 | 0.01573 | 0.01704 | 7.69% |
| 1562 | 0.00393 | 0.00426 | 7.75% |

While checking the backward kernel, it seems I'm triggering another error with a size limit of
```python
x = torch.randn(1449, 1, device='cuda', requires_grad=True)
out = torch.pdist(x)
out.mean().backward()
> RuntimeError: CUDA error: invalid configuration argument
```
, while `[<=1448, 1]` works.

I'll take another look at this issue. Let me know, if the potential fix should go into this PR or if I should open a new issue.

CC @ngimel, @csarofeen

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 43cd34b0:


* **1/1** broken upstream at merge base 446e9af5 (see [grid view](https://dr.pytorch.org/master-timeline.html?count=1&sha1=446e9af5b97a2eb22f88d7983518bdaf5250ec6c&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35))
  <details>
  <summary>
  You may want to rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch origin viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  
* **0/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=43cd34b0fbe872a5e5fd0e31a70596ddf7a7b656).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably caused by upstream breakages:
* [pytorch_linux_xenial_py3_clang5_asan_test](https://dr.pytorch.org/build-details.html?build_id=78614440)



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by ptrblck** [comment]
It seems the backward error comes from a wrong CUDA launch config triggered by `grid_y >= 65535` (for an input tensor of `[1449, 1]` it will be `65568`, which is invalid according to [the programming guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#features-and-technical-specifications__technical-specifications-per-compute-capability)) in [this line of code](https://github.com/pytorch/pytorch/blob/46ad80c8395379be5ba17624fd5dbad8e7a8e8d2/aten/src/ATen/native/cuda/DistanceKernel.cu#L285).

A similar issue is thrown for `cdist` (but for another size, neet to triage this bug also).

I'll open a new issue and try to fix the launch configs there.

**Comment by ngimel** [comment]
@ptrblck 8% perf regression is acceptable. Please fix backward in this PR also. We can leave cdist separate for now.

**Comment by ngimel** [comment]
And add tests please

**Comment by ptrblck** [comment]
I've added tests for the failed use cases and kept the sizes "reasonably" small, but let me know, if I should expand the test cases.

Benchmarking for the backward pass on V100-SXM2 32GB (time in ms/iter):

Using `input = torch.randn(size, 128, device='cuda')`:

| x.size(0) | before PR | after PR | 
|-----------|-----------|-----------|
| 5600    | -         | 78.8309    |
| 2800     | -  | 19.9385  | 
| 1400 | 6.0119 | 5.0028 | 
| 700 | 1.5210 | 1.2706 |
| 350 | 0.4104 | 0.3429 | 
| 175 | 0.1673 | 0.1648 |

Using `input = torch.randn(size, 1, device='cuda')`:

| x.size(0) | before PR | after PR | 
|-----------|-----------|-----------|
| 50000    | -         | 4541.2841 |
| 25000     | -  | 1133.9128 | 
| 12500 | - | 283.3532 | 
| 6250 | - | 70.8232 |
| 3125 | - | 17.7395 | 
| 1562 | - | 4.4551 |
| 781 | 1.3270 | 1.1294 |
| 390 | 0.3595 | 0.3087 |
| 195 | 0.1651 | 0.2168 |

Code used for benchmarking:
```python
import torch
import torch.nn as nn
import time

nb_iters = 10
sizes = [int(50000/2**i) for i in range(10)]

for size in sizes:
    x = torch.randn(size, 1, device='cuda', requires_grad=True)
    # warmup
    for _ in range(nb_iters):
        out = torch.pdist(x)
        out.mean().backward()
    #print(torch.cuda.memory_allocated()/1024**3)

    torch.cuda.synchronize()
    t0 = time.time()
    for _ in range(nb_iters):
        out = torch.pdist(x)
        out.mean().backward()
    torch.cuda.synchronize()
    t1 = time.time()
    print('size {}, time {:.4f}ms/iter'.format(size, 1000*(t1 - t0)/nb_iters))
```

**Comment by ngimel** [comment]
1) Test failure are real
2) tests are smoke tests not testing correctness
3) and this is concerning, because I don't see how just flipping grid dimensions without changing the actual kernels can work.

**Comment by ptrblck** [comment]
Sorry for the confusion, but kernel changes weren't in the commit. :confused: 
I'll add correctness tests and commit the kernel changes.

**Comment by ptrblck** [comment]
The forward test for `[50000, 1]` uses approx. 23GB when comparing with `brute_pdist`.
Just the smoke test without the comparison ~4.66GB.
Should we fall back to the smoke test for this shape? I could decorate this test with `LARGE_TENSOR` and try to run it on our CI.

I've added the gradient check for the other, smaller shapes as well.
Let me know, if I should remove them and just keep it for backward pass for `[1500, 1]`.

**Comment by ngimel** [comment]
at least rocm failure is real, have not looked at other ones.

**Comment by ngimel** [comment]
@ptrblck can you please split pdist test into 2, one testing forward, and another testing backward that would be completely skipped on ROCm using @skipIfRocm decorator? We try to deprecate TEST_WITH_ROCM thing.

**Comment by ptrblck** [comment]
@ngimel Sure, I'll split the tests and skip the backward for Rocm.
However, Rocm now also seems to fail in the forward pass for a tensor of `[50000, 1]` (initial commit to fix the forward pass size limitation by using `const int64_t k = blockIdx.x;`) with
```
00:38:18 ======================================================================
00:38:18 FAIL: test_pdist_norm_cuda (__main__.TestTorchDeviceTypeCUDA)
00:38:18 ----------------------------------------------------------------------
00:38:18 Traceback (most recent call last):
00:38:18   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 681, in wrapper
00:38:18     method(*args, **kwargs)
00:38:18   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 180, in instantiated_test
00:38:18     return test(self, device_arg)
00:38:18   File "test_torch.py", line 11002, in test_pdist_norm
00:38:18     self.assertTrue(torch.allclose(expected_cpu, actual_gpu.cpu()))
00:38:18 AssertionError: False is not true
```
This test checks the GPU result for `p=2` with the CPU result.

Should I skip this test as well for rocm or wait for a review?

**Comment by ngimel** [comment]
@ptrblck please skip the forward test also and file an issue for ROCm

**Review by ngimel — CHANGES_REQUESTED** [review]
The things I'd like to see in the test
1) no TEST_WITH_ROCM, only decorators
2) separate test for the large size you are adding
3) disable ROCm tests as needed (as long as you are not breaking anything, and those are the tests that you are adding), but file an issue for ROCm detailing the failures.

**Comment by ptrblck** [comment]
I've removed the `TEST_WITH_ROCM` usage and added the decorators.
`test_pdist_norm_forward` is applied for all devices, while `test_pdist_norm_backward` and `test_pdist_norm_large` is skipped for rocm. 
I've also moved `pdist_single` to `common_utils` (where `brute_pdist` is also located) to avoid code duplication.

I'll create a new issue with the information about the failing rocm tests.

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
