### PR TITLE
Aarch64 cd upgrade

### PR DESCRIPTION
**Pull request by snadampal**
Fixes #https://github.com/pytorch/builder/issues/1774

### CODE REVIEW

**Comment by snadampal** [comment]
Hi @atalman , this change requires the manylinux 2_28 docker for aarch64, the current one is manylinux 2014. 

> DOCKER_IMAGE: pytorch/manylinuxaarch64-builder:cpu-aarch64-main

Can you please update the image in the PyTorch account?

**Comment by snadampal** [comment]
This PR is mainly to test the pytorch/builder CD script update PR: https://github.com/pytorch/builder/pull/1781
I'm not sure how to read the CI test results in this case, the CI shows no issues, but it didn't test any of the generated workflows.
@malfet , can you please comment on this or https://github.com/pytorch/builder/pull/1781

**Comment by malfet** [comment]
>  I'm not sure how to read the CI test results in this case, the CI shows no issues, but it didn't test any of the generated workflows. 

You need to add `ciflow/binaries_wheel` label to trigger binary builds on PR

**Comment by snadampal** [comment]
This PR is blocked till the manylinux 2_28 docker workflow is merged, this is the PR# https://github.com/pytorch/builder/pull/1784

**Pull request closed without merging**
