### PR TITLE
rename Half.x to be clearer

### PR DESCRIPTION
**Pull request by nairbv**
Seems like it would be clearer to use a more descriptive name for the variable holding the underlying data in Half.h. Open to other suggestions.

### CODE REVIEW

**Comment by colesbury** [comment]
Ehhh... it's effectively part of the public API. I don't see a good enough reason to change it

**Comment by colesbury** [comment]
It's also the naming that both Eigen and CUDA use

**Comment by nairbv** [comment]
> Ehhh... it's effectively part of the public API. I don't see a good enough reason to change it

yeah I was kinda wondering if that was the case. We likely have uses of half.x outside the pytorch codebase?

**Comment by nairbv** [comment]
closing since not desirable due to inconsistency with cuda etc.

**Pull request closed without merging**
