### PR TITLE
Update cu124 dynamo benchmark expected values

### PR DESCRIPTION
**Pull request by clee2000**
I believe this corresponds to changes in https://github.com/pytorch/pytorch/pull/127780

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by nWEIdia — APPROVED** [review]
LGTM! Thank you for maintaining two copies. I am working on https://github.com/pytorch/pytorch/pull/128423 to hopefully reduce the burden of maintaining two (slightly-different currently) copies. 
https://github.com/pytorch/pytorch/commit/85eeb90d2c4b4bd5a75450f2ff3f25796f73f5a7 did great work improving graph breaks but did not realize cu124 had to be adjusted too.

**Review by DanilBaibak — APPROVED** [review]

**Pull request closed without merging**
