### PR TITLE
Migrate AT_DISPATCH_ALL_TYPES_AND_COMPLEX_AND3 to c10::complex

### PR DESCRIPTION
**Pull request by zasdfgbnm**
`AT_DISPATCH_ALL_TYPES_AND_C10_COMPLEX_AND3` is removed
`AT_DISPATCH_ALL_TYPES_AND_COMPLEX_AND3` is now using `c10::complex`

### CODE REVIEW

**Review by anjali411 — APPROVED** [review]

**Comment by zasdfgbnm** [comment]
Strange, the failure is real

**Comment by zasdfgbnm** [comment]
@anjali411 The test failure was caused by the wrong implementation of `std::abs`. It should be fixed now.

**Comment by anjali411** [comment]
> @anjali411 The test failure was caused by the wrong implementation of `std::abs`. It should be fixed now.

which test was failing?

**Comment by anjali411** [comment]
> > @anjali411 The test failure was caused by the wrong implementation of `std::abs`. It should be fixed now.
> 
> which test was failing?

oh I see `is_close` test was failing in `test_torch.py`

**Comment by mruberry** [comment]
Unlanding. Unfortunately this appears to have broken pytorch_linux_xenial_cuda9_2_cudnn7_py3_gcc7_build. Copy of relevant portion of the log:

```
May 08 06:43:58 [ 80%] Building NVCC (Device) object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/torch_cuda_generated_ConvolutionMM2d.cu.o
May 08 06:44:00 /usr/local/cuda/include/thrust/detail/complex/complex.inl(64): error: no suitable conversion function from "const c10::complex<float>" to "float" exists
May 08 06:44:00           detected during:
May 08 06:44:00             instantiation of "thrust::complex<T>::complex(const R &) [with T=float, R=c10::complex<float>]" 
May 08 06:44:00 /var/lib/jenkins/workspace/c10/util/complex_type.h(441): here
May 08 06:44:00             instantiation of "T std::abs(const c10::complex<T> &) [with T=float]" 
May 08 06:44:00 /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/UnarySignKernels.cu(16): here
May 08 06:44:00             instantiation of "scalar_t at::native::abs_wrapper(scalar_t) [with scalar_t=c10::complex<float>]" 
May 08 06:44:00 /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/UnarySignKernels.cu(28): here
May 08 06:44:00 
May 08 06:44:00 /usr/local/cuda/include/thrust/detail/complex/complex.inl(64): error: no suitable conversion function from "const c10::complex<double>" to "double" exists
May 08 06:44:00           detected during:
May 08 06:44:00             instantiation of "thrust::complex<T>::complex(const R &) [with T=double, R=c10::complex<double>]" 
May 08 06:44:00 /var/lib/jenkins/workspace/c10/util/complex_type.h(441): here
May 08 06:44:00             instantiation of "T std::abs(const c10::complex<T> &) [with T=double]" 
May 08 06:44:00 /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/UnarySignKernels.cu(16): here
May 08 06:44:00             instantiation of "scalar_t at::native::abs_wrapper(scalar_t) [with scalar_t=c10::complex<double>]" 
May 08 06:44:00 /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/UnarySignKernels.cu(28): here
May 08 06:44:00 
May 08 06:44:00 2 errors detected in the compilation of "/tmp/tmpxft_00003ebf_00000000-6_UnarySignKernels.cpp1.ii".
May 08 06:44:00 CMake Error at torch_cuda_generated_UnarySignKernels.cu.o.Release.cmake:281 (message):
May 08 06:44:00   Error generating file
May 08 06:44:00   /var/lib/jenkins/workspace/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/./torch_cuda_generated_UnarySignKernels.cu.o
May 08 06:44:00 
May 08 06:44:00 
```

**Pull request closed without merging**
