### PR TITLE
Slightly improve AOTAutograd logging with ViewAndMutationMeta

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105702

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Sure

**Comment by albanD** [comment]
Ho? How is this breaking?

**Review by SherlockNoMad — APPROVED** [review]

**Pull request closed without merging**
