### PR TITLE
Fix for rand_like as well.

### PR DESCRIPTION
**Pull request by bpstark**
This is a followup PR to #32830 This solves the same issue for RandLike which we saw in RandNLike

### CODE REVIEW

**Review by BowenBao — APPROVED** [review]
LGTM, thanks.

**Comment by bpstark** [comment]
@houseroad can you please take a look at this PR.

**Comment by bpstark** [comment]
rebased to keep up to date with master

**Review by houseroad — APPROVED** [review]
Looks good. Resubmitted CI jobs, and let's see.

**Comment by houseroad** [comment]
Why the ci is failing? 

Feb 12 04:51:25 test/onnx/test_operators.py::TestOperators::test_mean_dtype
Feb 12 04:51:25 test/onnx/test_operators.py::TestOperators::test_reduced_mean_dtype
Feb 12 04:51:25   /var/lib/jenkins/.local/lib/python3.6/site-packages/torch/onnx/symbolic_helper.py:176: UserWarning: ONNX export failed on mean because dtype not supported
Feb 12 04:51:25     warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")

Can you rebase again?

**Pull request closed without merging**
