### PR TITLE
[dynamo] Turn on guard_nn_modules

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #124975
* __->__ #125202

Turning on guard_nn_modules adds large number of guards, so we are bound to take a perf hit. But the perf hit is small. These are the numbers 

image

First we observe that compared to Python guards, C++ guards give around 6x speedup. This reduces the total time spent in guards. This is shown in the last column (cpp_guards/inductor_optimized_latency). The worst model is around 1.61%, with most of the models below 1%. I think this is good enough signal to turn the config on.

One might also wonder how much guard slowdown occurs with `guard_nn_modules=True`. This is the table 
image

For most models, the guard overhead with nn module guards is under 2x. There are a few outliers, where the slowdown is really high and for those models we spend 1%-2% time in C++ guards as shown in first table.

cc @ezyang @msaroufim @bdhirsh @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

### CODE REVIEW

**Review by ezyang — COMMENTED** [review]
You want a JK for internal rollout to killswitch it

**Comment by ezyang** [comment]
🤔 which we don't have precedent for in this module

**Comment by ezyang** [comment]
You want to call `torch._utils_internal.justknobs_check` to read out the default, but you can't do the obvious thing of doing it in the config module as that will cause the JK check to happen at module import time and @oulgen and I know that you can't do that because it will poison the process for forks. So you want this to happen on the first time the config is accessed. The low tech way is to default this to None, and then at the read site, if it is None, pong the JK for the real value. The high tech way is to add some capability to the config module getter (I think we've got a accessor function where you can customize) so that it is able to lazily query JK.

**Comment by ezyang** [comment]
Another deployment strategy that doesn't involve JKs is to turn it on in OSS only but not fbcode, then enable it on a per PG basis by twiddling it, and then later switch the fbcode default to true.

**Comment by anijain2305** [comment]
Going with fbcode off and OSS on for now. Will figure out internal rollout strategy.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
