### PR TITLE
[functorch] Fix proxy unwrapping for cond().

### PR DESCRIPTION
**Pull request by zhxchen17**
In control_flow.cond(), we unwrap arguments' proxy by using
get_proxy_slot() call which call a lambda in the end to get the stored
proxy. For SymInt and SymFloat we hide the proxy under a thunk instead
of storing proxy on .proxy attribute diretly, therefore we need to
special case SymInt for unwrapping here.

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
nyegh, I'll approve this but this definitely feels like there should be a helper function in proxy_tensor.py that we're supposed to be using. 

Where's the test.

**Comment by zhxchen17** [comment]
> nyegh, I'll approve this but this definitely feels like there should be a helper function in proxy_tensor.py that we're supposed to be using.
> 
> Where's the test.

I just use the internal model as the test. I'll add one in this PR.

**Comment by ezyang** [comment]
Please add a test to OSS otherwise people who break it will only find out when they import to fbcode

**Comment by zhxchen17** [comment]
Addressed comment:
1. Added a `unwrap_proxy` helper to proxy_tensor.py
2. Added a unittest which fails without the change here representing the use case we saw internally.

**Pull request closed without merging**
