### PR TITLE
Add missing conversion functions between half and float for ppc64le

### PR DESCRIPTION
**Pull request by vinithakv**
Fixes compilation error on ppc64-le resulting from missing conversion functions 'convert_half_float' and 'convert_float_half'.
These functions are implemented by this commit.

Started failing compilation  from the following commit onwards: ced5c89b6fbe827a538b7ada96b2f9a5989871c7.

Fixes #ISSUE_NUMBER

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by ezyang** [comment]
This seems to be in the wrong file. This is the bfloat16 header?

**Comment by ChipKerchner** [comment]
Just for clarity, these are conversions between float32 and float16 (different from bfloat16)?

**Comment by vinithakv** [comment]
> Just for clarity, these are conversions between float32 and float16 (different from bfloat16)?

Hi Chip,
You are right. These conversions are between float16 and float32. They should be in vex-common or vex-float* headers. 
I will make  the changes.

**Review by jgong5 — APPROVED** [review]

**Comment by vinithakv** [comment]
Hi,
@ezyang  @ChipKerchner 
I have moved the changes to a vsx common header.
Let me know if you have any comments.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
