### PR TITLE
Enable CUPTI for kineto by default on windows

### PR DESCRIPTION
**Pull request by cloudhan**
Retry of #62175

### CODE REVIEW

**Comment by cloudhan** [comment]
@gdankel

**Review by malfet — CHANGES_REQUESTED** [review]
The idea of `on_cpu` tests is to verify that PyTorch wheel packages are hermetic, i.e. do not have any external dependencies. Right fix for the problem is to package cupti64.dll  into the package

Also `torch_cpu` should not depend on neither cupti nor CUDA runtime, if it does it's a bug that needs to be fixed. @gdankel I remember you planned to look into this one

**Comment by seemethere** [comment]
> > `win-vs2019-cuda11.3-py3 / test (force_on_cpu, 1, 1, windows.4xlarge)`
> > Failed with
> > ```
> > Traceback (most recent call last):
> >   File "test_utils.py", line 824, in test_load_standalone
> >     self.assertEqual(r.returncode, 0)
> >   File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 1957, in assertEqual
> >     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
> > AssertionError: False is not true : Scalars failed to compare as equal! 3221225781 != 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `3221225781` is `0xC0000135` which is `STATUS_DLL_NOT_FOUND`.
> > This problem is kinda hard to solve. [Kineto cause `torch_cpu` library link to `cudart` and `cupti`](https://github.com/pytorch/kineto/issues/356#issuecomment-883347782).
> > 
> > 1. In the test environment of `win-vs2019-cuda11.3-py3 / test (force_on_cpu, 1, 1, windows.4xlarge)`, no cuda is present.
> > 2. pytorch is installed via download build artificat, so cuda related libraries are not packaged, unlike installing via whl.
> > 3. The `TestStandaloneCPPJIT.test_load_standalone` produce a `standalone_load_test.exe` in tmp dir. Originally it does not transitively rely on any cuda libraries. After this PR
> >    ```
> >    standalone_load_test.exe -------> torch_cpu.dll ----┬----> cudart*.dll
> >                                                        └----> cupti*.dll
> >    ```
> 
> Thank you very much for the detailed explanation. I believe @seemethere made changes few days back to use `whl` package as artifact for CI across all the platforms. In that case, please adjust `setup.py` to package cupti and cudart into the package when building on Windows

This isn't finished just yet, although I'm hoping I can have it done within the next couple of days

https://github.com/pytorch/pytorch/pull/65587

**Pull request closed without merging**
