### PR TITLE
prune back configs

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #126570

We had a previous PR that added configs for an internal model. Running the below script on output from autotuning, we can prune back the added configs with negligible perf loss: P1365917790.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by nmacchioni — APPROVED** [review]
Great! Wondering if you got a perf run with this new set of configs?

**Comment by eellison** [comment]
Yea, just did inference since training wasn't as affected when in your benchmark run:

image

Note - base commit slightly different, but at very least, don't expect slowdowns.

**Comment by nmacchioni** [comment]
@eellison force merge should be alright here, we know perf is good and I don't see how this could break things.

**Comment by eellison** [comment]
@pytorcbot merge --force "already tested, no risk of causing ci errors"

**Pull request closed without merging**
