### PR TITLE
[FORMAT] format test_symbolic_shape_analysis.py using black

### PR DESCRIPTION
**Pull request by Gamrix**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #71627
* #71626
* __->__ #71625
* #71343

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
is this worth messing up the blame ?

**Comment by Gamrix** [comment]
I generally consider it worth it. Autoformat makes it easier to then autoformat in the future as the rest of the file won't change. Also, given that this diff only has formatting changes, it should be clear to go past this diff when you see this diff in a blame.

**Comment by eellison** [comment]
Since you closed the diff on top of this, let's wait at least until you make changes to this file since I would prefer not to do this and (as of now) am only one touching this code

**Comment by eellison** [comment]
image


I just really don't think this is making it more readable... we already have a linter that runs on python that conforms a certain amount of standards. Can you just run black on your changes ? there has to be a relatively easy way to do that in the same way that clang format ahs

**Pull request closed without merging**
