### PR TITLE
Fix index truncation in argmin/max for large tensors

### PR DESCRIPTION
**Pull request by peterbell10**
Fixes the `TensorIterator` parts of #32863 (THC is still broken)

`TensorIterator::split` now keeps track of the `view_offsets` into the full tensor range. With this, I can take the base offset for the reduced dimension and translate partial results from the sub-iter into the index range of the full tensor. This happens only once for each intermediate result, so we should still benefit from the performance of 32-bit indexing in loops.

### CODE REVIEW

**Comment by ezyang** [comment]
nifty. @VitalyFedyunin do you think you can take full reviewership on this or should I look?

**Comment by ezyang** [comment]
Or maybe Natalia is the best reviewer here.

**Comment by peterbell10** [comment]
Test failure looks genuine, but for some reason it's the CPU version that failed:
```
Feb 14 01:40:27 FAIL [8.918s]: test_argminmax_large_axis_cpu (__main__.TestTorchDeviceTypeCPU)
Feb 14 01:40:27 ----------------------------------------------------------------------
Feb 14 01:40:27 Traceback (most recent call last):
Feb 14 01:40:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 180, in instantiated_test
Feb 14 01:40:27     return test(self, device_arg)
Feb 14 01:40:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 382, in wrapper
Feb 14 01:40:27     fn(*args, **kwargs)
Feb 14 01:40:27   File "test_torch.py", line 8411, in test_argminmax_large_axis
Feb 14 01:40:27     self.assertEqual(x.argmin(1), [x.shape[1] - 1] * 2)
Feb 14 01:40:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 883, in assertEqual
Feb 14 01:40:27     allow_inf=allow_inf)
Feb 14 01:40:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 785, in assertEqual
Feb 14 01:40:27     allow_inf=allow_inf)
Feb 14 01:40:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 893, in assertEqual
Feb 14 01:40:27     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
Feb 14 01:40:27 AssertionError: 1 not less than or equal to 1e-05 : 
```

**Review by ngimel — APPROVED** [review]
Approving, modulo failing test. Do you need help with debugging it?

**Comment by peterbell10** [comment]
It looks like there are places where the cpu reduction also splits iterators. I'll see if the same fix will help for there.

**Comment by peterbell10** [comment]
I applied the fix to the CPU reduction but it turns out the actual cause here was just that I was assigning `-1` to a `uint8` value.

**Comment by vadimkantorov** [comment]
I hope https://github.com/pytorch/pytorch/pull/33370 doesn't intervene with this one

**Comment by ngimel** [comment]
#33370 is unrelated.

**Comment by vadimkantorov** [comment]
Are there any consequences about this mixed 64bit/32bit indexing? e.g. is it faster to do argmax across a contiguous small chunk vs a discontiguous small chunk that may require 64bit indexing?

**Comment by peterbell10** [comment]
>Are there any consequences about this mixed 64bit/32bit indexing?

This PR only introduces 1 extra add per reduced element in each kernel, so I don't expect performance to change much. 

>is it faster to do argmax across a contiguous small chunk vs a discontiguous small chunk that may require 64bit indexing

There is a potential cost from splitting the operation over multiple kernel launches; it will limit the parallelism available within each kernel. For large contiguous chunks, that's inconsequential but, in the extreme, I suppose a slice `x[0::2**32].argmax()` would launch a new kernel for every element in the input. That would be terrible for performance.

However, I'd note that this has always been the case for `TensorIterator` reductions.

**Comment by vadimkantorov** [comment]
So in theory there is tradeoff between multiple kernel launches that support 32-bit indexing and a single kernel launch that must do 64-bit indexing?

**Comment by peterbell10** [comment]
In theory, yes. In practice I don't think it matters much. 32-bit indexing covers ~2GB of memory so you could only have 10-20 tensor splits before you've covered all the memory in a top of the line Quadro card.

**Pull request closed without merging**
