### PR TITLE
Implement python API for AdaBelief optimizer

### LINKED ISSUE #47571: Add Adabelief optimizer to the C++ API
## 🚀 Feature
Add Adabelief optimizer to the C++ API

## Motivation
I have been using this new optimizer recently with the Python API and found out it worked extremely well (for my use cases at least). I also find the paper and theory behind it pretty neat. I would be ready to work on it (although with no guarantee since this would be done on my free time) if you consider this is worth adding to the API.

Thank you for reading this far. Cheers. :)

Link to the paper: https://arxiv.org/abs/2010.07468

cc @albanD @mruberry @jbschlosser @vincentqb @yf225 @glaringlee

### PR DESCRIPTION
**Pull request by juntang-zhuang**
Fixes #47571 partially, add python API for AdaBelief optimizer.

### CODE REVIEW

**Comment by glaringlee** [comment]
@juntang-zhuang 
Hey Juntang, please see the comment from my colleague who is working on python side of pytorch. It seems we have an adoption rule for new features on python side which I am not aware of. Sry about this, but I think this is a good feature as the paper is already there, more and more people will use it and we can adopt this into pytorch main branch later this year I think.

**Comment by juntang-zhuang** [comment]
@glaringlee Thanks a lot for the update. I'll just keep the changes in my local repository so we can consider merging it later.

**Comment by glaringlee** [comment]
> @glaringlee Thanks a lot for the update. I'll just keep the changes in my local repository so we can consider merging it later.

Sure, let's revisit this in the middle of the year see whether more you have more citations, or if you optimizer is used by a large facility (eg, some big companies?), I think that would be a big plus. let's see.

**Review by iramazanli — COMMENTED** [review]
Thanks for proposing AdaBelief implementation to PyTorch Core Library.

We would want to refer to rulebook for adding optimizers to PyTorch Core:
 https://github.com/pytorch/pytorch/wiki/Developer-FAQ#i-have-implemented-an-algorithm--feature-from-a-research-paper-that-is-related-to-optimization-when-is-the-correct-time-to-add-it-to-pytorch-core-

Which implies although AdaBelief is a very promising algorithm, given that it's relatively new algorithm we cannot add it to Core Library yet.

It can be interesting discussion to return back to this issue in the following years.

**Pull request closed without merging**
