### PR TITLE
Delete batch tensor

### PR DESCRIPTION
**Pull request by eellison**
Deleting batch tensor since we are no longer maintaining the project and keeping it functional is blocking other improvements.

### CODE REVIEW

**Review by driazati — APPROVED** [review]

**Comment by ezyang** [comment]
This broke lint on master

**Comment by Strasser-Pablo** [comment]
Hi, I have some code that is using BatchTensor and the automatic batching from c++. Are some alternative mechanism into consideration.

Do you also have a reference of what part of pytorch has problem with BatchTensor.
I think I may keep part of BatchTensor just for my use case.

**Comment by eellison** [comment]
@Strasser-Pablo when I added this line https://github.com/pytorch/pytorch/blob/20b63aa9776c7dbe8358daf1111464cb30ce08b6/torch/csrc/jit/passes/peephole.cpp#L226 the batch tensor tests broke. I didn't look into it any further, so use at your own risk.

**Comment by Strasser-Pablo** [comment]
Thanks for the info.

**Pull request closed without merging**
