### PR TITLE
Fix adapative pooling kernel size bug on Power

### PR DESCRIPTION
**Pull request by charleshofer**
The functions that PyTorch provides for doing adaptive pooling
on the CPU compute the kernel size based off of the size of the
input and output matrices. Rounding differences on Power cause
the results to be slightly off for these computations. This
results in pooling kernels that go over the edge of the matrix
and pick up junk data. Use doubles rather than floats for more
consistent behavior.

This bug was discovered by seeing failing tests in
test/onnx/test_models.py. The result given by VGG models were
different when run on the CPU with PyTorch vs. ONNX.

### CODE REVIEW

**Review by zhangguanheng66 — CHANGES_REQUESTED** [review]
Could you add some unit tests to cover the change. The PR looks good to me.

**Comment by charleshofer** [comment]
Yeah, I can get some unit tests in there. This is my first PR. Any guidance on where they should go?

**Comment by zhangguanheng66** [comment]
I think it can go to test/test_nn.py

**Review by houseroad — COMMENTED** [review]
I am also wondering which edge case can cause different results.

**Review by houseroad — COMMENTED** [review]
This change will change the behavior of pytorch:

1) https://github.com/pytorch/pytorch/blob/master/test/test_nn.py#L3989, you can add some tests to cover this change.

2) https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_caffe2.py and https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_onnxruntime.py for onnx part to add the tests.

**Comment by charleshofer** [comment]
The adaptive pooling functions are giving funny outputs on Power when both the input and output matrix sizes are 7, 13, 14, and 26 at least. I didn't check anything higher than that until today, but it looks like switching those floats to a double type just staves off the problem. Once we hit 93, 99, 105, 117, etc. `end_index` starts showing up again.

**Comment by charleshofer** [comment]
Rather than worry about floating point inconsistencies, I removed the floating point computations completely. They're not needed to do the calculations for the start and end index of the kernel.

I've also added a test case to handle handle some of the values were x86 and Power were inconsistent.

**Comment by charleshofer** [comment]
The lint output doesn't seem to be relevant to any changes I've made, or I'm not understanding it's output:

```
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/876d4e50-7c95-4d4a-aec1-fde7c709ef09.sh
./torch/onnx/symbolic_opset8.py:6:1: F401 'torch.onnx.symbolic_opset9.wrap_logical_op_with_cast_to' imported but unused
##[error]Bash exited with code '1'.
##[section]Finishing: CmdLine
```

Is this a problem for my PR?

**Pull request closed without merging**
