### PR TITLE
add mixed data type mode for LayerNorm forward path

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74410
* #69067
* __->__ #73844
* #71376

Differential Revision: [D35782873](https://our.internmc.facebook.com/intern/diff/D35782873)

### CODE REVIEW

**Comment by frank-wei** [comment]
Could you fix this issue? 
stderr: caffe2/aten/src/ATen/native/cpu/layer_norm_kernel.cpp:39:5: error: variable of non-literal type 'google::CheckOpString' cannot be defined in a constexpr function
    DCHECK_EQ(X.numel(), M * N);
    ^
caffe2/aten/src/ATen/native/cpu/layer_norm_kernel.cpp:104:5: error: variable of non-literal type 'google::CheckOpString' cannot be defined in a constexpr function
    DCHECK_EQ(X.numel(), M * N);
    ^
caffe2/aten/src/ATen/native/cpu/layer_norm_kernel.cpp:207:56: error: no member named 'apply' in 'at::native::(anonymous namespace)::LayerNormKernelImplInternal<double, double>'
      LayerNormKernelImplInternal<scalar_t, scalar_t>::apply(
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

**Comment by mingfeima** [comment]
Working on the failures @frank-wei

**Comment by mingfeima** [comment]
> @CaoE Could you fix this issue? stderr: caffe2/aten/src/ATen/native/cpu/layer_norm_kernel.cpp:39:5: error: variable of non-literal type 'google::CheckOpString' cannot be defined in a constexpr function DCHECK_EQ(X.numel(), M * N); ^ caffe2/aten/src/ATen/native/cpu/layer_norm_kernel.cpp:104:5: error: variable of non-literal type 'google::CheckOpString' cannot be defined in a constexpr function DCHECK_EQ(X.numel(), M * N); ^ caffe2/aten/src/ATen/native/cpu/layer_norm_kernel.cpp:207:56: error: no member named 'apply' in 'at::native::(anonymous namespace)::LayerNormKernelImplInternal<double, double>' LayerNormKernelImplInternal<scalar_t, scalar_t>::apply( ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

I have moved the `DCHECK_EQ` to non constexpr functions of upper level, please review if this will solve the above issue @frank-wei thanks!

**Comment by frank-wei** [comment]
> > @CaoE Could you fix this issue? stderr: caffe2/aten/src/ATen/native/cpu/layer_norm_kernel.cpp:39:5: error: variable of non-literal type 'google::CheckOpString' cannot be defined in a constexpr function DCHECK_EQ(X.numel(), M * N); ^ caffe2/aten/src/ATen/native/cpu/layer_norm_kernel.cpp:104:5: error: variable of non-literal type 'google::CheckOpString' cannot be defined in a constexpr function DCHECK_EQ(X.numel(), M * N); ^ caffe2/aten/src/ATen/native/cpu/layer_norm_kernel.cpp:207:56: error: no member named 'apply' in 'at::native::(anonymous namespace)::LayerNormKernelImplInternal<double, double>' LayerNormKernelImplInternal<scalar_t, scalar_t>::apply( ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
> 
> I have moved the `DCHECK_EQ` to non constexpr functions of upper level, please review if this will solve the above issue @frank-wei thanks!

Thanks, will try.

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35782873).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35782873).

**Comment by mingfeima** [comment]
updated: add test case for mixed dtype mode (when input is bfloat16 and the model parameters are float32).

**Comment by mingfeima** [comment]
updated: add test case for mixed dtype mode (when input is bfloat16 and the model parameters are float32).

**Review by frank-wei — APPROVED** [review]

**Pull request closed without merging**
