### PR TITLE
[FSDP] Dequeue one instead of flush

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#86165 [FSDP] Dequeue one instead of flush**
* #85039 [FSDP] Add `FSDPExtensions` for TP support

For the rate limiter, I initially implemented the approach of only dequeueing a single event, but there was concern about blocking the CPU _every_ iteration. The landed approach instead blocks every `_max_num_inflight_all_gathers` iterations and flushes the entire queue.

However, upon further analysis, the approach of dequeueing a single event should be more performant with the same memory usage -- as the name suggests, both have `_max_num_inflight_all_gathers` concurrently inflight all-gathers. The cost of blocking the CPU thread is not important compared to the duration the CPU thread is actually blocked. This PR's approach reduces the latter quantity.

**Fast Communication; Slow Computation**
Screen Shot 2022-10-06 at 9 59 37 AM

**Slow Communication; Fast Computation**
Screen Shot 2022-10-04 at 4 34 15 PM

**T5-11B**
2 nodes / 16 40 GB A100s with EFA and batch size 6:
- [Old] 5.81 s / batch; 24 and 20 CUDA malloc retries on local rank 0s; 35.234 GB peak active; 38.806 GB peak reserved
- [New] 5.10 s / batch; 25 and 29 CUDA malloc retries on local rank 0s; 35.234 GB peak active; 38.868 GB peak reserved

4 nodes / 32 40 GB A100s with EFA and batch size 7:
- [Old] 5.21 s / batch; 0, 0, 0, 0 CUDA malloc retries on local rank 0s; 33.695 GB peak active; 38.494 GB peak reserved
- [New] 4.93 s / batch; 1, 0, 0, 0 CUDA malloc retries on local rank 0s; 33.678 GB peak active; 38.792 GB peak reserved

The new version changes the fragmentation in the allocator. It is possible that by blocking the CPU thread more in the old approach, the initial blocks used to serve the all-gather stream allocations are different compared to the new approach. Even though the number of CUDA malloc retries increases slightly, the net result is a speedup with the new approach.

### CODE REVIEW

**Review by zhaojuanmao — APPROVED** [review]

**Comment by zhaojuanmao** [comment]
oh, the old approach actually waits for all the pending events done, which means calling "torch.cuda.synchronize()" every 2 all gathers? the new (original) approach is really implementing "inflight" all gathers, CPU thread only waits for 1 event done and then start to schedule new kernels, it just slows down CPU thread scheduling, not really blocking CPU thread.... 

Thanks for the figures, I think I mixed event.synchronize() with "torch.cuda.synchronize()" that is used in fairscale fix..

**Comment by zhaojuanmao** [comment]
oh, the old approach actually waits for all the pending events done, which means calling "torch.cuda.synchronize()" every 2 all gathers? the new (original) approach is really implementing "inflight" all gathers, CPU thread only waits for 1 event done and then start to schedule new kernels, it just slows down CPU thread scheduling, not really blocking CPU thread.... 

Thanks for the figures, I think I mixed event.synchronize() with "torch.cuda.synchronize()" that is used in fairscale fix..

**Comment by awgu** [comment]
> it just slows down CPU thread scheduling, not really blocking CPU thread....

For limit of 2, the new approach blocks the CPU thread until the last last all-gather's computation finishes. For the old approach, it always blocks until the last all-gather's computation finishes, but only does that every other all-gather. For both, we still block the CPU thread.

**Comment by zhaojuanmao** [comment]
> yes, yes, you are right, for "it just slows down CPU thread scheduling, not really blocking CPU thread....", what I mean is "it just slows down CPU thread scheduling, not really do a device sync..."

**Pull request closed without merging**
