### PR TITLE
Remove isScalar() from TensorImpl.

### PR DESCRIPTION
**Pull request by gchanan**
This is an implementation detail that is going away soon, it doesn't need to be part of the API.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by colesbury** [comment]
I remember this having a measurable perf difference because `dim()` was a virtual function, while `isScalar()` is an inline function in the header.

**Comment by gchanan** [comment]
We only have 1 THTensor type now, so the function doesn't need to be virtual, except we haven't fully dealt with dense + sparse yet.  So IMO the right thing to do is to create a blocker issue on 1.0 that the function can't be virtual (or we measure that it doesn't matter) and we don't force an order-of-operations refactor yet.

**Comment by ezyang** [comment]
We fully intend for dim to be non-virtual at the end

**Comment by gchanan** [comment]
Closing in favor of https://github.com/pytorch/pytorch/pull/9765.

**Pull request closed without merging**
