### PR TITLE
[Feature Request] Noisy SGD

### PR DESCRIPTION
**Pull request by vishwakftw**
Based on the paper [Adding Gradient Noise Improves Learning for Very Deep Networks](https://arxiv.org/abs/1511.06807), I have added functionality to incorporate gradient noise.

Please let me know what you think about this.

### CODE REVIEW

**Comment by Kaixhin** [comment]
This seems quite specific - adding noise to SGD, not including any forms of momentum, and not for any other optimisers, despite the fact that the paper just requires adding noise directly to the gradients. It's not particularly complex - even the time-dependent version here - so it's questionable whether implementing this extra code path (along with tests) is worth it for a technique which is not quite uncommon.

**Comment by vishwakftw** [comment]
@Kaixhin Thank you for the comment. I will retract the pull request if you would like me to.

**Comment by Kaixhin** [comment]
@vishwakftw I would wait until a maintainer makes a decision on this. You can save yourself some work by waiting until they respond, as if they do want to accept it you will also need to write unit tests.

**Comment by apaszke** [comment]
Since the technique is quite simple and not specific to the optimizer responsibilities, and is very simple to implement yourself, I think it's better to avoid adding this patch to the core. I'd encourage you to post issues before you start implementing features, so we can avoid situations like these. Thanks for the PR!

**Comment by vishwakftw** [comment]
Thanks for the feedback @apaszke @Kaixhin .

**Pull request closed without merging**
