### PR TITLE
[inductor] update triton pin (may not land due to holiday)

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #115881
* #115878

### CODE REVIEW

**Comment by jataylo** [comment]
Hey @shunting314 will this change [#115878](https://github.com/pytorch/pytorch/pull/115878/files) to support the new triton compile interface be backwards compatible with older Triton versions? (based on the comments that seems to be the intention). On ROCm triton side we haven't adopted this change yet, and would need some time to do so. 

cc: @jithunnair-amd

**Comment by shunting314** [comment]
@jataylo yea, [#115878](https://github.com/pytorch/pytorch/pull/115878/files) should maintain BC.

**Comment by shunting314** [comment]
Current status of this pin update. 

1. we fixed a bunch of BC issues in the stacked PR
2. pass rate does not regress in the perf run in CI now [link](https://hud.pytorch.org/benchmark/compilers?startTime=Wed%2C%2013%20Dec%202023%2018%3A38%3A32%20GMT&stopTime=Wed%2C%2020%20Dec%202023%2018%3A38%3A32%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=gh/shunting314/87/head&lCommit=befd854499b90b97ac3e0e13cd0d2cef1ecb2658&rBranch=main&rCommit=34fe850d0083688abf0a27f3e864723f0858aab1). And we see decent perf wins across all benchmark suites: TB 3%+, HF 2%+, TIMM 1%+ . But we also see big compilation time regress..:  TB +7s, HF +6s, timm +10s . We might need find which triton PR cause the compilation time regress and talk to openai triton team.
3. there are still a few CI failures (besides wheels related) on this PR that I'll fix

cc @jansel  , @bertmaher , @yuguo68  (internal pin update oncall)

**Comment by shunting314** [comment]
I did some bisecting to debug the compilation time regression. I pick AlbertForMaskedLM as the model for testing and run it 5 times for each triton commit I tested.

It shows that the compilation time regress started exactly at https://github.com/openai/triton/pull/2701 . cc @ptillet any idea how to mitigate the compilation time regression?

**Pull request closed without merging**
