### PR TITLE
Add unit test for nested_tensor input to nn.TransformerEncoder

### PR DESCRIPTION
**Pull request by mikekgfb**
Summary: Add unit test for nested_tensor input & fix

Test Plan: sandcastle

Differential Revision: D45580393

### CODE REVIEW

**Review by jbschlosser — CHANGES_REQUESTED** [review]
Why not just move the `output.size()` call here:
https://github.com/pytorch/pytorch/blob/8994d9e6109c541a1d581c383e4de9ed68205d91/torch/nn/modules/transformer.py#L318-L319

`output_size` isn't used anywhere else AFAICT.

**Comment by mikekgfb** [comment]
> Why not just move the `output.size()` call here:
> 
> https://github.com/pytorch/pytorch/blob/8994d9e6109c541a1d581c383e4de9ed68205d91/torch/nn/modules/transformer.py#L318-L319
> 
> `output_size` isn't used anywhere else AFAICT.

That is correct.  What change are you suggesting?

**Comment by jbschlosser** [comment]
> That is correct. What change are you suggesting?

Maybe something like this:

```python
if convert_to_nested: 
     output = output.to_padded_tensor(0., src.size()) 
```

**Comment by mikekgfb** [comment]
> > That is correct. What change are you suggesting?
> 
> Maybe something like this:
> 
> ```python
> if convert_to_nested: 
>      output = output.to_padded_tensor(0., src.size()) 
> ```

Yes, this makes sense - would increasing the defined-use range for src across TransformerEncoder be a concern? 
Other than that, great point and simplifies code!

**Review by jbschlosser — APPROVED** [review]

**Pull request closed without merging**
