### PR TITLE
[TensorExpr] Add NNC lowerings for `aten::view`, `aten::reshape` and `aten::expand_as`.

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#59157 [TensorExpr] Add NNC lowerings for `aten::view`, `aten::reshape` and `aten::expand_as`.**

Currently view is represented as a copy since we don't support inplace
operations in NNC (similar to `aten::reshape`).  Lowering for
`aten::expand_as` is exactly the same as for the `aten::expand`, since
we're building the TE expression basing on the output shape anyway.

Differential Revision: [D28774224](https://our.internmc.facebook.com/intern/diff/D28774224)

### CODE REVIEW

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28774224).

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28774224).

**Review by Chillee — APPROVED** [review]
LGTM - tbh, I didn't spend the time to understand all the logic, but if it passes the tests then seems fine to me :)

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28774224).

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28774224).

**Pull request closed without merging**
