### PR TITLE
Added torch::cuda::manual_seed(_all) to mirror torch.cuda.manual_seed(_all)

### PR DESCRIPTION
**Pull request by heitorschueroff**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#42638 Added torch::cuda::manual_seed(_all) to mirror torch.cuda.manual_seed(_all)**

Differential Revision: [D23030317](https://our.internmc.facebook.com/intern/diff/D23030317)

### CODE REVIEW

**Comment by glaringlee** [comment]
@ezyang 
Hi, Ed, would CUDAUtils.h be a good place to put this function? Can you advise?

**Comment by ezyang** [comment]
This probably doesn't belong in the cuda/ folder because it doesn't actually have any direct dependencies on CUDA headers (everything is indirected through Context). Is there a bug report / issue corresponding to this? That would help me assess.

**Comment by heitorschueroff** [comment]
> This probably doesn't belong in the cuda/ folder because it doesn't actually have any direct dependencies on CUDA headers (everything is indirected through Context). Is there a bug report / issue corresponding to this? That would help me assess.

https://github.com/pytorch/pytorch/issues/40361

**Comment by glaringlee** [comment]
> This probably doesn't belong in the cuda/ folder because it doesn't actually have any direct dependencies on CUDA headers (everything is indirected through Context). Is there a bug report / issue corresponding to this? That would help me assess.

@ezyang 
We want to have a c++ equivalent api for torch.cuda.manual_seed, since we do have equivalent api for torch.manual_seed, but not torch.cuda.manual_seed.

**Comment by ezyang** [comment]
Thanks, the issue helps.

There are few things you have to be careful about when writing C++ API ports of PyTorch functionality. (This is mostly directed at @glaringlee, but hopefully this also gives you some useful context @heitorschueroff).

The function of directory structure in Python is different than in C++. In Python, `torch.cuda` structure is just for organization purposes. In C++, the `ATen/cuda` folder structure has a very specific purpose, which is to demarcate what goes into the `torch_cpu` shared library versus the `torch_cuda` shared library. Because the dependency relationship between these libraries is unidirectional (torch cuda depends on torch cpu, but not vice versa), it means that code in `torch_cpu` cannot directly call `torch_cuda`; it must indirect through a dynamic dispatch of some sort. (Python doesn't have this problem, because everything is indirected there!)

Furthermore, we must be careful about distinguishing the `ATen/cuda` from the `torch/csrc/api/include/torch/cuda.h`. ATen/cuda are files put in `torch_cuda`; but `torch/cuda.h` is shipped with `torch_cpu` library and is available even if PyTorch wasn't compiled with CUDA (because it does dynamic dispatches). Finally, `torch/cuda.h` is what actually constitutes the public C++ API; headers in ATen are more private (they just happen to frequently get reexported in torch namespace, and our "official" API is often spotty so people go to ATen to find the stuff they actually need.)

So what does this mean for this issue? The user is requesting  `torch::cuda::manual_seed` in the public C++ API. To me, that indicates that it should go in `torch/csrc/api/include/torch/cuda.h`. The API should be available even if you didn't build with CUDA support. You should make sure that the new functions are implemented equivalently to their Python counterparts.

**Comment by glaringlee** [comment]
@ezyang Thanks a lot, Ed, very useful info to me.

**Review by glaringlee — APPROVED** [review]
LGTM now.

**Review by glaringlee — APPROVED** [review]
LGTM now

**Pull request closed without merging**
