### PR TITLE
Move functorch/_src to torch/_functorch

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #88756

This will be the last disruptive functorch internals change.

Why are we moving these files?
- As a part of rationalizing functorch we are moving the code in
functorch/_src to torch/_functorch
- This is so that we can offer the functorch APIs as native PyTorch APIs
(coming soon) and resolve some internal build issues.

Why are we moving all of these files at once?
- It's better to break developers all at once rather than many times

Test Plan:
- wait for tests

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
I know it's a bit late for bikeshedding, but are you sure you want `torch` twice in the module path? `torch/_func` is a lot shorter to type

**Comment by ezyang** [comment]
torch._functional very close to torch.nn.functional, if you like the crosstalk here then it is fine.

**Comment by zou3519** [comment]
Discussed this a bit offline with @Chillee and @samdow, here was the resolution:
- We'll keep the functorch internals named as `_functorch` or `ATen/functorch` or `torch/csrc/functorch`. Renaming the internals to `func` or `functional` will cause confusion among developers
- The public name for functorch will be different. Currently we're leaning towards torch.func (thanks Ed for the initial suggestion! we hadn't considered it). Horace did a twitter poll where users looked mostly split, but many users thought that crosstalk between torch.nn.functional and a hypothetical torch.functional wasn't good.

**Comment by zou3519** [comment]
Note to diff train operator: this likely doesn't break any internal changes (I checked), but if it does, please let me fix up the diff train diff.

This PR changes some functorch internals that are NOT public API, so internal libraries should not be relying on it. Those that are recognize that these APIs aren't public and have no stability guarantees.

**Pull request closed without merging**
