### PR TITLE
Trace asserts with fx by looking at byte code

### PR DESCRIPTION
**Pull request by zdevito**
This patch uses some bytecode introspection logic to see if a boolean is being used as an assert condition and if so, it records the assert in the fx graph and allows the trace to continue.
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #70960

Differential Revision: [D33570397](https://our.internmc.facebook.com/intern/diff/D33570397)

### CODE REVIEW

**Review by jamesr66a — COMMENTED** [review]
Seems pretty OK. Can you comment on:
* False positives. I doubt it, but is there anyway this would incorrectly allow tracing of code that's not an assert?
* False negatives. I think from chat you verified that this bytecode pattern shows up for `assert` statements from an empirical test, but I wonder if there are cases where an assert shows up differently. Do we know the path CPython takes when converting the assert statement to bytecode?

Also do you think we can put this behind a feature flag? I've been putting those here https://github.com/pytorch/pytorch/blob/e6befbe85cd0d0237c585e75c45a43735bdfa780/torch/fx/proxy.py#L19

**Comment by zdevito** [comment]
False positives -- it will detect this as an assertion:
```
if not x:
  raise AssertionError
```
It is functionally equivalent to an assertion however, so I don't think it would be a problem if it were handled.

Something like this doesn't match because AssertionError isn't loaded right after the if:
```
def foo(x):
  if not x:
    if x > 4:
      raise AssertionError
```
But this pattern is an actual false positive, which results in a ValueError rather than an AssertionError:
```
def raise_v():
    raise ValueError

def foo(x):
    if not x:
        raise AssertionError(raise_v())
```
Of course, the same behavior can happen in any assert statement: by ignoring the code in the message formatting part, we might be ignoring edges that result in another type of exception getting thrown and potentially later caught.

This situation seems very rare.

False negatives: There are lots of boolean expressions that we cannot override, so they will still trigger the control flow error pathway: `(x and ...)`, `(x or ...)` will try to convert the Proxy to a bool before it is used as a condition statement. In the benchmark suite only 9/309 assertions use these patterns. `if not x` will swap the byte code to `POP_JUMP_IF_FALSE`, which I suppose we can handle, but it might be easier to say we support assertions on bools but not forming boolean expressions in proxies as a clean cut point.

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33570397).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33570397).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33570397).

**Review by jamesr66a — APPROVED** [review]

**Pull request closed without merging**
