### PR TITLE
port glu to use structured kernel approach

### PR DESCRIPTION
**Pull request by makslevental**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #61824
* #61821
* #61802
* #61801
* __->__ #61800

resubmitting because the [last one](https://github.com/pytorch/pytorch/pull/61433) was unrecoverable due to making changes incorrectly in the stack

Differential Revision: [D29812492](https://our.internmc.facebook.com/intern/diff/D29812492)

### CODE REVIEW

**Comment by makslevental** [comment]
@makslevental has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29812492).

**Comment by makslevental** [comment]
@desertfire , @hlu1 , @eellison and @Krovatkin  any blockers here?

**Review by desertfire — APPROVED** [review]

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Comment by makslevental** [comment]
@makslevental has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29812492).

**Pull request closed without merging**
