### PR TITLE
[Distributed] Do not expose `nlohmann/json.hpp` in public headers

### PR DESCRIPTION
**Pull request by malfet**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #131925
* #131922

Move `<hlohmann/json.hpp>` dependency as well as `NCCLTraceBuffer::getCollectiveTraceJson` and `NCCLTraceBuffer::dump_json` implementation introduced by https://github.com/pytorch/pytorch/pull/129505 from the header into .cpp file. This relaxes the requirement on all downstream client to depend on the library

Fixes https://github.com/pytorch/pytorch/issues/130678

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Lint needs fixing but sounds good otherwise!

**Review by d4l3k — APPROVED** [review]
LGTM

**Review by fduwjj — APPROVED** [review]
thanks for the fix.

**Comment by c-p-i-o** [comment]
Sorry for the break @malfet @xwang233 !

**Review by c-p-i-o — APPROVED** [review]

**Pull request closed without merging**
