### PR TITLE
Fix btrifact for variables

### LINKED ISSUE #4217: btrifact fails with Variable arguments
I'm having trouble getting `torch.btrifact` to work with Variable arguments; either I'm doing something wrong or there's a bug. The trouble seems to be with the `info` argument; there is no plausible type I can think of for `info` that works in the Variable case.

With Tensors, we can either ignore the `info` argument or set it to be an `IntTensor`:

```python
import torch
from torch.autograd import Variable

N, M = 2, 3
A = torch.randn(N, M, M)

# A as FloatTensor, no info
A_LU, pivots = torch.btrifact(A)

# A as FloatTensor, info as IntTensor
info = torch.IntTensor(M)
A_LU, pivots = torch.btrifact(A, info=info)
```

Making A a Variable and not passing `info` crashes:
```python
A_var = Variable(A)
A_LU, pivots = torch.btrifact(A_var)
# RuntimeError: Expected a Tensor of type Variable[torch.FloatTensor]
# but found an undefined Tensor for argument #1 'info'
```

Making A a Variable and `info` a `Variable[IntTensor]` crashes:
```python
A_var = Variable(A)
info = Variable(torch.IntTensor(M))
A_LU, pivots = torch.btrifact(A_var, info=info)
# RuntimeError: Expected object of type Variable[torch.FloatTensor]
# but found type Variable[torch.IntTensor] for argument #1 'info'
```

Making A a Variable and `info` a `Variable[FloatTensor]` crashes:
```python
A_var = Variable(A)
info = Variable(torch.FloatTensor(M))
A_LU, pivots = torch.btrifact(A_var, info=info)
# RuntimeError: Expected object of type torch.IntTensor
# but found type torch.FloatTensor for argument #1 'info'
```

Going crazy and making A a Variable and `info` an `IntTensor` also crashes:
```python
A_var = Variable(A)
info = torch.IntTensor(M)
A_LU, pivots = torch.btrifact(A_var, info=info)
# RuntimeError: btrifact(): argument 'info' must be Variable, not torch.IntTensor
```
(Full test script here: https://gist.github.com/jcjohnson/0ae6b433e07d0117016361d8ed9b0410)

Is this a bug, or am I misunderstanding how `torch.btrifact` should be used?

I'm using PyTorch version 0.3.0.post4 installed via pip with Python 3.5.2 on Ubuntu 16.04.

### PR DESCRIPTION
**Pull request by ssnl**
Fixes #4217 

This PR breaks `btrifact` into `btrifact` and `btrifact_with_info`. The cwrap declarations for for tensor and variable are different in that the `tensor.btrifact` in `TensorMath.cwrap` still allows `info` optional argument, and `var.btrifact` in `Decalaration.cwrap` always sets `info` as NULL. In `variable.py`, a python method `btrifact` is added to support old `info` optional argument behavior, but I added deprecation warning in favor of `btrifact_with_info`.

I also modified `preprocess_declarations.py`'s `is_nullable` for optional tensor arguments with NULL default values. An example of input declarations is the old `btrifact`in `Declaration.cwrap`:
```[[
  name: btrifact
  cname: btrifact
  types:
    - floating_point
  backends:
    - CPU
    - CUDA
  variants:
    - method
    - function
  return: argument 0,1
  arguments:
    - arg: THTensor* result
      output: True
    - arg: THIntegerTensor* pivots
      output: True
    - arg: THIntegerTensor* info
      kwarg_only: True
      default: NULL
    - arg: bool pivot
      kwarg_only: True
      default: "true"
    - THTensor* self
]]
```

, which gets parsed into the following:

```
{..., 'options': [{'arguments': [..., 
{'kwarg_only': True, 'default': None, 'type': 'THInteger Tensor*', 'name': 'info'}, 
...] ...}
```

### CODE REVIEW

**Review by colesbury — APPROVED** [review]
looks good. can you make sure there's a test that calls `btrifact_with_info`?

**Comment by SsnL** [comment]
Added tests with `btrifact_with_info`, doc for `btriunpack` and `tensor.btrifact*`.

**Comment by ezyang** [comment]
Protip: if you want to pretty print the structs, use

```
import pprint
pprint.prrint(foo)
```

**Comment by apaszke** [comment]
cc: @bamos @zkolter as this might be breaking for qpth or some other projects

**Comment by SsnL** [comment]
This doesn’t change the existing btrifact behavior, except for printing a
deprecate warning if info is used in variable case. So I guess it shouldn’t
break other projects?

**Comment by apaszke** [comment]
Not in the short term, but it will be removed at some point

**Pull request merged**
