### PR TITLE
Fix build error in c10 on Windows

### PR DESCRIPTION
**Pull request by peterjc123**
Targets https://github.com/pytorch/pytorch/issues/20635#issuecomment-496265510
Reference:
1. https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2015#microsoft-specific-predefined-macros
2. https://docs.microsoft.com/en-us/cpp/cpp/deprecated-cpp?view=vs-2019

### CODE REVIEW

**Comment by ezyang** [comment]
Hmm, I'm not convinced by this change. `C10_DEPRECATED_USING` itself is supposed to be a portable macro, so if you ifdef the use sites we've sort of missed the point.

Perhaps we should just rewrite the macro to be `C10_DEFINE_DEPRECATED_USING(TypeName, TypeThingy)` so that you can stick the equality sign in the correct place in that case.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Waiting for CI.

**Comment by peterjc123** [comment]
@ezyang Did you forget to get it merged?

**Comment by ezyang** [comment]
Trying again

Excerpts from peterjc123's message of 2019-05-30 21:20:27 -0700:
> @ezyang Did you forget to get it merged?
>

**Comment by peterjc123** [comment]
@ezyang Should be good to go.

**Pull request closed without merging**
