### PR TITLE
moved logit to use torch ops instead of refs + added a couple more decompositions

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #79000
* #78994
* #78991
* __->__ #78984
* #78978

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by osalpekar** [comment]
This seems to break functorch tests, so will need to revert. I'd recommend holding off on merging the rest of the stack since this may cause conflicts. Errors can be seen at D36980635. One example failure:

```
=================================== FAILURES ===================================
_______ TestFunctionalizeCPU.test_functionalize_fx_transpose_simple_cpu ________

self = <test_eager_transforms.TestFunctionalizeCPU testMethod=test_functionalize_fx_transpose_simple_cpu>
device = 'cpu'

    def test_functionalize_fx_transpose_simple(self, device):
    
        def f(x: torch.Tensor) -> torch.Tensor:
            return x.transpose(1, 0)
>       out = make_fx(functionalize(f, remove='mutations_and_views'))(torch.zeros(4, 2, device=device))

buck-out/dev/gen/pytorch/functorch/test/test_eager_transforms#binary,link-tree/test_eager_transforms.py:2919: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
buck-out/dev/gen/pytorch/functorch/test/test_eager_transforms#binary,link-tree/functorch/_src/python_key.py:206: in wrapped
    t = pythonkey_trace(wrap_key(f, args), concrete_args=tuple(phs))
buck-out/dev/gen/pytorch/functorch/test/test_eager_transforms#binary,link-tree/functorch/_src/python_key.py:169: in pythonkey_trace
    graph = tracer.trace(root, concrete_args)
buck-out/dev/gen/pytorch/functorch/test/test_eager_transforms#binary,link-tree/torch/fx/_symbolic_trace.py:587: in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
buck-out/dev/gen/pytorch/functorch/test/test_eager_transforms#binary,link-tree/functorch/_src/python_key.py:188: in wrapped
    out = f(*tree_args)
buck-out/dev/gen/pytorch/functorch/test/test_eager_transforms#binary,link-tree/functorch/_src/eager_transforms.py:1255: in wrapped
    func_outputs = func(*func_args, **func_kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = FunctionalTensor(lvl=1, value=\
PythonTensor(tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])))

    def f(x: torch.Tensor) -> torch.Tensor:
>       return x.transpose(1, 0)
E       RuntimeError: self__storage_saved.value().is_alias_of(result.storage()) INTERNAL ASSERT FAILED at "buck-out/dev/gen/caffe2/generate-code/torch/csrc/autograd/generated/VariableType_3.cpp":12231, please report a bug to PyTorch.

buck-out/dev/gen/pytorch/functorch/test/test_eager_transforms#binary,link-tree/test_eager_transforms.py:2918: RuntimeError
```

**Pull request closed without merging**
