### PR TITLE
Enable mypy checking in torch/_inductor/__init__.py

### PR DESCRIPTION
**Pull request by jennychristopher**
Fixes #105230 

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Comment by Skylion007** [comment]
This file needs to be added to .lintrunner's include list.

**Comment by jennychristopher** [comment]
> This file needs to be added to .lintrunner's include list.

All the files which are under torch/__inductor__ were already added in linter's include patterns previously
[[linter]]
code = 'MYPYNOFOLLOW'
include_patterns = [
    'torch/_dynamo/eval_frame.py',
    'torch/_dynamo/convert_frame.py',
    'torch/_dynamo/symbolic_convert.py',
    'torch/_dynamo/types.py',
    'torch/_dynamo/output_graph.py',
    'torch/_dynamo/guards.py',
    'torch/_dynamo/side_effects.py',
    'torch/_dynamo/optimizations/__init__.py',
    'torch/_dynamo/optimizations/backends.py',
    'torch/_dynamo/optimizations/training.py',
    'torch/_dynamo/debug_utils.py',
    'torch/_dynamo/repro/**/*.py',
    'torch/_inductor/**/*.py',                                        --------> Added here
    'torch/_C/_dynamo/**/*.py',
    'test/test_utils.py',  # used to by in MYPY but after importing op_db it took 10+ minutes
]

**Comment by Skylion007** [comment]
If there were included before, why didn't the previous type errors make MyPy complain?

**Comment by ezyang** [comment]
you need to remove it from excludes

**Comment by jennychristopher** [comment]
> you need to remove it from excludes

Sure will remove

**Comment by ezyang** [comment]
I went ahead and pushed the necessary change

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
