### PR TITLE
[2/N] Replace c10::sv with std::sv

### PR DESCRIPTION
**Pull request by cyyever**
Follows  #139453

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ZainRizvi** [comment]
@pytorchbot revert -c ghfirst -m "Sorry but this breaks internally. @ezyang can you please help get this landed? See D65546398 for more details"

Errors have the shape:

```
error: no matching conversion for static_cast from 'std::vector<c10::basic_string_view<char>>' to 'std::vector<std::basic_string_view<char>>'
```

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
