### PR TITLE
[GH1] Refuse to merge PRs with internal changes

### PR DESCRIPTION
**Pull request by malfet**
If PR has associated differential revision, and "Meta Internal-Only Changes Check" status is not successful, it must be merged via Phabricator rather than GH Workflow.

Add test to validate this workflow

### CODE REVIEW

**Comment by bigfootjon** [comment]
Don't we want to allow this for co-development purposes?

We already have a "Meta internal-only changes" checkrun. Can we use that as the metric instaed?

**Review by bigfootjon — CHANGES_REQUESTED** [review]
Don't we want to allow this for co-development purposes?

We already have a "Meta internal-only changes" checkrun. Can we use that as the metric instead?

**Comment by malfet** [comment]
@bigfootjon I don't think mergebot should at all be used for co-development purposes. Also "Meta internal-only changes" can be lagging, whereas "Differential Revision" clearly indicates that there is an associated diff

**Review by seemethere — APPROVED** [review]

**Comment by bigfootjon** [comment]
@malfet Another scenario: What happens when we've finished with full GH1 and we block internal lands? For users that create a Diff they'll receive an error when they try to land telling them to export. Once they export should they be required to manually remove the "Differential Revision" line?

**Comment by bigfootjon** [comment]
> Probably when internal lands are 100% blocked we should not leave any reference to diff as all reviews should happen on GitHub

I'm against this, as right now there might be context in the Diff that's not available publicly (e.g. internal Tasks) or historical context (e.g. Diff did not originally interact with pytorch core in its first version, but then does later in a new version)

**Review by bigfootjon — APPROVED** [review]
Sorry for the late review, but this LGTM

**Pull request closed without merging**
