### PR TITLE
Fix Upsample/EmbeddingBag module printing

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #93850

The fix generalizes but I want someone else to holistically figure this out.

Fixes https://github.com/pytorch/pytorch/issues/93233
Fixes https://github.com/pytorch/pytorch/issues/93512

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
These are not fstring so that doesn't work

**Comment by ezyang** [comment]
f'ing lol

**Review by albanD — APPROVED** [review]
SGTM

**Pull request closed without merging**
