### PR TITLE
Process inputs and outputs in fx interpreter

### PR DESCRIPTION
**Pull request by 842974287**
Summary: The inputs and outputs of the graph module might be different from the graph inputs and outputs if users are using custom codegen. In interpreter, it runs the graph instead of the generated forward function so it might not work if user provides the inputs to the graph module. To fill the gap, we call `process_inputs` and `process_outputs` inside interpreter.

Test Plan: unit test: test_interpreter_with_codegen

Differential Revision: D34898108

### CODE REVIEW

**Review by jamesr66a — APPROVED** [review]
Seems fine to me, but @Chillee should probably take a look as well

**Review by jamesr66a — COMMENTED** [review]
BC test is fine, since you've added a kwarg with default it should be BC (however there is a BC breaking vector where someone overrides that method, but I don't think we have any mitigation possible for it). Feel free to `--accept` the change

**Comment by suo** [comment]
Looks like this broke the BC tests on master (didn't run `--accept`?) I am reverting

**Comment by suo** [comment]
cc @malfet for error, reverting in phab

**Comment by malfet** [comment]
> cc @malfet for error, reverting in phab

Already fixed by https://github.com/pytorch/pytorch/pull/74570 , but shouldn't we always revert on phab for changes that already landed?

**Pull request closed without merging**
