### PR TITLE
[tensorboard] Remove dependence on torch.onnx

### PR DESCRIPTION
**Pull request by justinchuby**
### Description

The `graph` function takes a dependency on `torch.onnx.select_model_mode_for_export`, which was used because it implicitly patches `torch._C.Node` to allow for key access. This change removed the need for the patch and decoupled the tensorboard util from `torch.onnx`.

This is needed to unblock #82511 because we are removing the monkey patch

### Testing

cc @ezyang @orionr @BowenBao

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
sure

**Comment by justinchuby** [comment]
thanks for the review!

**Pull request closed without merging**
