### PR TITLE
skip test_out_of_memory for jetson

### PR DESCRIPTION
**Pull request by Fuzzkatt**
Skip test_out_of_memory in test/test_cuda.py on Jetson as OOM reporting in Jetson has issues due to partially missing NVML support. cc @eqy

### CODE REVIEW

**Review by eqy — APPROVED** [review]

**Comment by Fuzzkatt** [comment]
@malfet ready for review

**Review by albanD — APPROVED** [review]
For cuda related PRs, @eqy 's accept means you can merge without the need for another approve :D

**Comment by ZainRizvi** [comment]
This branch is based on a commit that's more than a month old and is no longer compatible with the entire CI suite.  Please rebase your changes onto the latest `viable/strict` branch and resolve the conflicts to get a proper CI run

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
