### PR TITLE
renable test_scalar_fusion

### PR DESCRIPTION
**Pull request by zou3519**

### CODE REVIEW

**Review by ezyang — DISMISSED** [review]
spurious onnx update is spurious

**Comment by yf225** [comment]
@zou3519 Should we remove the onnx submodule update?

**Comment by zou3519** [comment]
Well the problem hasn't been fixed yet :)

**Comment by SsnL** [comment]
closing this. feel free to reopen if you still want to test.

**Comment by zou3519** [comment]
still testing

**Comment by zou3519** [comment]
We fixed the main cause of this (the high memory usage) in #10981 so this should be good to go now

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
