### PR TITLE
Adds __getattr__ to DataParallel to forward to self.module

### PR DESCRIPTION
**Pull request by elistevens**
Helps keep the use of `DataParallel` transparent to other code.

### CODE REVIEW

**Comment by elistevens** [comment]
I should note that the Travis builds will skip the relevant test, since it depends on CUDA.

**Comment by apaszke** [comment]
We've discussed that and decided that we'd rather keep attr access explicit. If you like that you can always subclass `DataParallel` and implement `__getattr__` there. Thanks!

**Comment by elistevens** [comment]
Given the somewhat odd/obscure spelling, would a PR with the explicit subclass be accepted?

**Comment by soumith** [comment]
no, the subclassed pr won't be accepted into the core.

**Comment by elistevens** [comment]
Ah, bummer. Thanks for letting me know.

**Comment by fmassa** [comment]
@elistevens Note that an implicit getattr there could be very misleading in some cases. For example, when serializing a model with DataParallel, you save the `module.` name of it in the parameters, so if you want to load these parameters in a model without DataParallel, it will error out. But using the indirect getattr, it would be harder to debug it.

**Pull request closed without merging**
