### PR TITLE
[reland][dynamo][guards] Consider tensors as immutable for dict tag matches

### PR DESCRIPTION
**Pull request by anijain2305**
Reland - https://github.com/pytorch/pytorch/pull/139560

As mentioned in https://github.com/pytorch/pytorch/pull/130341, using `static py::object` can lead to segfaults. I suspect this is the reason for the import system error seen internally (https://www.internalfb.com/sevmanager/view/469592). In this PR, I am removing the `static` part. This is fine and also the right thing to do because this will catch if user changes the flag in the same process for compiling two different functions.

Unfortunately, there is no easy way to trigger this segfault, so I can't write a test.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by anijain2305** [comment]
For some reason, this causes large regression for an internal model.

**Comment by williamwen42** [comment]
@pytorch@pytorchbot revert -m "internal regression" -c nosignal

**Comment by williamwen42** [comment]
The added test fails when inline_inbuilt_nn_modules is False.

**Pull request closed without merging**
