### PR TITLE
[BE][CUDA][Bugfix]: Enable extended MMA shapes in CUTLASS. 

### LINKED ISSUE #133695: CUTLASS does not build with extended MMA shape kernels in PyTorch
### 🐛 Describe the bug

As far as I can tell, we never use the CMakeLists.txt in the third_party/cutlass which means we never enable the special MMA shape kernels in CUTLASS which increase performance on H100.

We should make sure to compile all these shape kernels as it's a onetime cost and can help any CUTLASS matmuls used by other ops like SPDA and Flash Attention

### Versions

master as of 8/16/2024

cc @malfet @seemethere

### PR DESCRIPTION
**Pull request by Skylion007**
* This fixes a major CMake/Bazel configuration bug where we were leaving CUTLASS performance on the table, especially with FlashAttention. This now enables using MMA instructions on SM90+, which should close the gap between SDPA and the external FA2. Note these operations only affect H100 and newer GPUs. Thankfully, this seems to have been updated recently into being a noop on the CUTLASS side. Still better set the CMake variable properly.
*  Also enables additional new shape kernels added in the recent CUTLASS 3.5.1+ update. This was the original motivatin of the PR before I realized the basic MMA kernels were accidentally disabled since we didn't go through the submodule's CMake/Bazels. 
* Adds a bit to compile time and code size, but well worth it considering it speeds up our internal flash attention significantly on H100s at the cost of some minor additional compile time.
* These kernels and settings will be needed for Flash Attention 3 whenever we add that too.

Fixes #133695 

cc @ptrblck @msaroufim @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by stas00** [comment]
`s/SPDA/SDPA/` in the OP?

**Comment by Skylion007** [comment]
> `s/SPDA/SDPA/` in the OP?

Fixed

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
