### PR TITLE
[Inductor] New Triton Attrs Descriptor Fixups

### PR DESCRIPTION
**Pull request by alexbaden**
Fixes additional areas where we need to use the new Triton AttrsDescriptor if it is available.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by alexbaden** [comment]
@jansel this PR contains a few areas where I missed support for the new `AttrsDescriptor`. Sorry about that.

There were some additional changes added to the `AttrsDescriptor` that I am working on incorporating, but I think any PyTorch related changes there could be another PR.

**Review by jansel — DISMISSED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change, but it still has another lint error' -c nosignal

[GH job link](https://github.com/pytorch/pytorch/actions/runs/11470014069/job/31918397592) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/215999452eb5517213b3a31f72eb9a7e843d12a0)

Please help fix and reland this.

**Review by huydhn — APPROVED** [review]
Stamped because it is reverted due to lint failure.  The change has already been approved

**Comment by alexbaden** [comment]
Thx. Looks like https://github.com/pytorch/pytorch/pull/138230 removed the global no-untyped-def from `triton_kernel_wrap.py` and I had not rebased over that change yet, which is why the lintrunner was passing locally for me.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
