### PR TITLE
Move intraop_launch_future from Parallel.h

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #64499
* #64173
* #64172
* #64171
* #64170
* #64169
* #64168
* #64167
* __->__ #64166

Differential Revision: [D30728585](https://our.internmc.facebook.com/intern/diff/D30728585)

### CODE REVIEW

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30728585).

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30728585).

**Comment by peterbell10** [comment]
Since #64899 was merged, will you continue landing this stack?

**Comment by ezyang** [comment]
yes but it looks like #64165 may get reverted so need to resolve that first

**Comment by ezyang** [comment]
looks like I managed to avert the revert but need to wait for the fix to go in

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30728585).

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30728585).

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30728585).

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30728585).

**Pull request closed without merging**
