### PR TITLE
add conv_transpose2d pointwise(unary) fusion kernel

### PR DESCRIPTION
**Pull request by chunyuan-w**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #90267
* #90266
* #90265
* __->__ #90264

This PR adds `torch.ops.mkldnn._convolution_transpose_pointwise` that supports ConvTranspose fusion with the below unary pointwise OPs:

- relu
- sigmoid
- tanh
- hardswish
- leaky_relu
- hardtanh
- gelu

cc @VitalyFedyunin @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
LGTM.

**Comment by chunyuan-w** [comment]
> @chunyuan-w , I think it will be better to separate this code from the convolution code, the current code is huge.

I'll submit another PR in this stack to move the code to a new file.

**Review by jansel — APPROVED** [review]

**Comment by osalpekar** [comment]
Seeing build breakages of the form blocking multifeed aggregator:
```
aten/src/ATen/native/mkldnn/Conv.cpp:664:5: error: no matching function for call to 'compute'
```
More details at: [D42081754](https://www.internalfb.com/diff/D42081754).

**Comment by chunyuan-w** [comment]
@osalpekar May I know the commit of the internal `pytorch/third_party/ideep`?
I'll check if the internal building failure is due to different ideep commits on the public master branch and the internal branch.

**Comment by weiwangmeta** [comment]
@chunyuan-w We will need to update the ideep and/or onednn submodule. Please pause the PR merging process till this update process is done. 
Other relevant PRs should similarly pause.

**Comment by chunyuan-w** [comment]
> @chunyuan-w We will need to update the ideep and/or onednn submodule. Please pause the PR merging process till this update process is done. Other relevant PRs should similarly pause.

Sure, we'll wait until the internal update is done.

**Comment by weiwangmeta** [comment]
Thanks. The ideep module update is almost done - using pytorch-rls-v2.7.2 
I wonder which mkl-dnn version should be used to go with this ideep version?

**Comment by weiwangmeta** [comment]
Link https://github.com/pytorch/pytorch/pull/87061 

Not sure which mkl-dnn to use: the one in ideep directory? or v2.7.2?

**Comment by malfet** [comment]
Have the double-checkout of oneDNN repo been resolved as mentioned in https://github.com/pytorch/pytorch/pull/87061#issuecomment-1284384276? 
If not, then I'm suggest we pause all further ideep/oneDNN/oneAPI updates.

**Comment by jgong5** [comment]
> Have the double-checkout of oneDNN repo been resolved as mentioned in [#87061 (comment)](https://github.com/pytorch/pytorch/pull/87061#issuecomment-1284384276)?
> If not, then I'm suggest we pause all further ideep/oneDNN/oneAPI updates.

> Not sure which mkl-dnn to use: the one in ideep directory? or v2.7.2?

@weiwangmeta @malfet Thanks for comments and help on the issue. Let us discuss internally and get back to you.

**Comment by chunyuan-w** [comment]
Re-opened in https://github.com/pytorch/pytorch/pull/91953

**Comment by weiwangmeta** [comment]
> > Have the double-checkout of oneDNN repo been resolved as mentioned in [#87061 (comment)](https://github.com/pytorch/pytorch/pull/87061#issuecomment-1284384276)?
> > If not, then I'm suggest we pause all further ideep/oneDNN/oneAPI updates.
> 
> > Not sure which mkl-dnn to use: the one in ideep directory? or v2.7.2?
> 
> @weiwangmeta @malfet Thanks for comments and help on the issue. Let us discuss internally and get back to you.

Hi @jgong5 , do you have any updates? Do you see the issue we are currently facing? Future Intel PRs are at risk of being reverted again if ideep does not get updated. Does ideep expect one commit from oneDNN repo or two commits from oneDNN repo?

**Comment by jgong5** [comment]
> Hi @jgong5 , do you have any updates? Do you see the issue we are currently facing? Future Intel PRs are at risk of being reverted again if ideep does not get updated. Does ideep expect one commit from oneDNN repo or two commits from oneDNN repo?

Yes. Thanks for the ask @weiwangmeta . We will share the proposal for single commit from oneDNN repo this week.

**Comment by jgong5** [comment]
@weiwangmeta We will create a new branch to avoid the double checkout issue. It is being validated internally now. Will keep you posted with the latest progress.

**Comment by chunyuan-w** [comment]
@weiwangmeta FYI I've reopened the PRs in this ghstack into a new one https://github.com/pytorch/pytorch/pull/91953 since I failed to rebase these PRs that have been reverted.

**Comment by weiwangmeta** [comment]
> @weiwangmeta FYI I've reopened the PRs in this ghstack into a new one #91953 since I failed to rebase these PRs that have been reverted.

Thanks @chunyuan-w  let me close this PR.

**Pull request closed without merging**
