### PR TITLE
Fixes in-order test flakiness

### LINKED ISSUE #142343: DISABLED test_out_of_order_index_ds (__main__.TestOutOfOrderDataLoader)
Platforms: linux, rocm, win, windows, mac, macos

This test was disabled because it is failing in CI. See [recent examples](https://hud.pytorch.org/flakytest?name=test_out_of_order_index_ds&suite=TestOutOfOrderDataLoader&limit=100) and the most recent trunk [workflow logs](https://github.com/pytorch/pytorch/runs/34099965281).

Over the past 3 hours, it has been determined flaky in 15 workflow(s) with 20 failures and 15 successes.

**Debugging instructions (after clicking on the recent samples link):**
DO NOT ASSUME THINGS ARE OKAY IF THE CI IS GREEN. We now shield flaky tests from developers so CI will thus be green but it will be harder to parse the logs.
To find relevant log snippets:
1. Click on the workflow logs linked above
2. Click on the Test step of the job so that it is expanded. Otherwise, the grepping will not work.
3. Grep for `test_out_of_order_index_ds`
4. There should be several instances run (as flaky tests are rerun in CI) from which you can study the logs.

<details><summary>Sample error message</summary>

```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_dataloader.py", line 3567, in test_out_of_order_index_ds
    self.assertEqual(expected_order, output)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 4016, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: Scalars are not equal!

Expected 1 but got 0.
Absolute difference: 1
Relative difference: 1.0

The failure occurred for item [0]

To execute this test, run the following from the base repo dir:
    python test/test_dataloader.py TestOutOfOrderDataLoader.test_out_of_order_index_ds

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

</details>

Test file path: `test_dataloader.py`

cc @andrewkho @divyanshk @SsnL @VitalyFedyunin @dzhulgakov @clee2000 @wdvr

### PR DESCRIPTION
**Pull request by andrewkho**
Fixes #142343

### CODE REVIEW

**Comment by andrewkho** [comment]
cc @michael-diggin

**Review by michael-diggin — APPROVED** [review]
Thank you for the quick PR and fix!

**Review by divyanshk — APPROVED** [review]
LGTM!

**Pull request closed without merging**
