### PR TITLE
Add AutocastHPU support

### PR DESCRIPTION
**Pull request by australopitek**
New dispatch key and necessary functions are added to PyTorch. Backend implementation will be added in the external library.

### CODE REVIEW

**Comment by bdhirsh** [comment]
Hey! Right now adding a new autocast key requires taking up an extra slot in the runtime dispatchkey bitset, but I have a PR up that will make autocast a "per-backend functionality key", which makes it (mostly) free for other backends to add their own autocast dispatch keys.

Let me know if you need this change in urgently - otherwise, you can wait for https://github.com/pytorch/pytorch/pull/85043 to land (it'll probably be another ~ week), and you can rebase on top of that change.

**Comment by australopitek** [comment]
> Hey! Right now adding a new autocast key requires taking up an extra slot in the runtime dispatchkey bitset, but I have a PR up that will make autocast a "per-backend functionality key", which makes it (mostly) free for other backends to add their own autocast dispatch keys.
> 
> Let me know if you need this change in urgently - otherwise, you can wait for #85043 to land (it'll probably be another ~ week), and you can rebase on top of that change.

@bdhirsh , sure, I'll wait and adjust my current change later. Thanks for the information.

**Comment by australopitek** [comment]
Hi @bdhirsh ,
I see there was a discussion in your PR https://github.com/pytorch/pytorch/issues/85559 and there has been no update for the last 2 weeks.
When do you think it will be merged?

**Comment by bdhirsh** [comment]
Hey @australopitek! Sorry for the wait. That PR doesn't look like it'll land in the next week or two, since there are still some issues around composite ops that need to be worked out.

I don't want to block you, so it seems reasonable to land the stuff in this PR for now, and unwind it later when we're able to make autocast more generic (in that PR). So I'll go ahead and land!

**Review by bdhirsh — APPROVED** [review]

**Comment by australopitek** [comment]
@bdhirsh 
Thank you for merging.
One more thing - I've got message from github-actions bot https://github.com/pytorch/pytorch/pull/84927#issuecomment-1276651269 about labels I should add.
However, I can't see any option to add labels. Is it possible I have no permission?

**Comment by bdhirsh** [comment]
@australopitek added! No action needed on your side

**Pull request closed without merging**
