### PR TITLE
as_strided_scatter storage offset defaults to None not 0

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #87481

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
lgtm

**Comment by albanD** [comment]
This is true for as_strided as well btw: https://github.com/pytorch/pytorch/issues/87365

**Comment by ezyang** [comment]
I checked `as_strided` but it seems to be None

**Comment by albanD** [comment]
Ho nice, I guess it was updated recently!

**Pull request closed without merging**
