### PR TITLE
Revert "Revert D21089648: Put TORCH_LIBRARY in torch/library.h; add custom class API"

### PR DESCRIPTION
**Pull request by ezyang**
This reverts commit 2ccdc39dce91a1821ede9bfdea26b30d66e1554f.

Original PR: https://github.com/pytorch/pytorch/pull/36742

### CODE REVIEW

**Review by ailzhang — APPROVED** [review]
Thanks!

**Comment by ezyang** [comment]
This one needs to unrevert the XLA side PR too

**Comment by ailzhang** [comment]
The companioned xla diff is also reverted.(in fact it didn't work with this patch). So it'll be safer to validate it again with `.torch_pin` next time this relands. :D

**Comment by ezyang** [comment]
@ailzhang somehow the diff that actually landed only had the fix, and not all of the contents here. Weird.

**Pull request closed without merging**
