### PR TITLE
[ROCm] Pyt 2.0 rocm staging

### PR DESCRIPTION
**Pull request by dllehr-amd**
Add triton support for ROCm builds of PyTorch.

* Enables inductor and dynamo when rocm is detected
* Adds support for pytorch-triton-mlir backend
* Adds check_rocm support for verify_dynamo.py

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by ngimel** [comment]
This generally looks good, but please resolve conficts

**Comment by malfet** [comment]
Changes as is look fine to me (as they affect only ROCM)

Though not sure if we have capacity to run those

**Review by pruthvistony — COMMENTED** [review]
All checks have passed.
https://hud.pytorch.org/pr/94660

**Pull request closed without merging**
