### PR TITLE
Add Work to distributed docs

### PR DESCRIPTION
**Pull request by H-Huang**
Summary:
Documenting the `Work` object

For a collective (broadcast, all_reduce, etc.) when async_op=True we return a `Work` object to which users can call `.wait()`, `.is_success()`, among other things but this class is not documented

Test Plan: Preview the docs build in OSS

Differential Revision: D51854974

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @kiukchung @lucasllc

### CODE REVIEW

**Comment by crcrpar** [comment]
it doesn't seem like the `class Work` has any docstring -- https://docs-preview.pytorch.org/pytorch/pytorch/115172/distributed.html#torch.distributed.Work

image

**Review by wconstab — APPROVED** [review]
nice! can you confirm the doc is rendering correctly before merging? (stamp to unblock)

**Review by wanchaol — COMMENTED** [review]
I recalled that we had this looong standing issue that we were trying to migrate from `Work` to `Future`, and that might be one reason why we don't have docs for `Work`. 

Curious are we giving up this migration and standardize on `Work` going forward?

**Comment by wanchaol** [comment]
> well we can still migrate even if we document it right?

yeah that's true, what I mean is that if we still want to do "Future" migration, maybe we can check the docs and see if we should ignore documenting certain methods on the Work object, so that the later migration might become easier (as less user would use those methods without docs)

**Comment by H-Huang** [comment]
> I recalled that we had this looong standing issue that we were trying to migrate from Work to Future, and that might be one reason why we don't have docs for Work.

This is true. I guess we can hold off on documenting any methods lest we have to commit to supporting those methods if we want to migrate to `Future.`

Currently for all of our collective operations documentation we already write we are returning "Work", so we should at least have a place in our docs mentioning what `torch.distributed.Work` is.

**Pull request closed without merging**
