### PR TITLE
[Submodule] Remove deprecated USE_TBB option and TBB submodule

### PR DESCRIPTION
**Pull request by cyyever**
cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @gujinghui @PenghuiCheng @jianyuh @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal

### CODE REVIEW

**Comment by ezyang** [comment]
@cpuhrsch, as our old TBB stan, could you pull the trigger (or not) on this?

**Review by cpuhrsch — APPROVED** [review]
Sad to see this go. I thought TBB was great and potentially an amazing solution to cleaner code (because it supports nested parallelism) and better performances in heterogenous environments. A task based parallelism engine seems more adaptable to busy environments and CPU cores with different performance characteristics (perhaps as seen on mobile CPUs).

**Review by malfet — APPROVED** [review]

**Comment by cyyever** [comment]
@cpuhrsch At the present TBB is used only as a parallel wrapper so that its potential is not fully utilized. It is possible to re-introduce TBB in the future once there are more use cases.

**Comment by PaliC** [comment]
@pytorchbot revert -m "This PR needs to be synced using the import button as there is a bug in our diff train" -c "ghfirst"

The import did not go through last time. Will try again (+ force merge)

**Comment by PaliC** [comment]
Unfortunately, it looks like syncing this PR is a bit nontrivial. I will take responsibility over importing and merging this PR. I am extremely sorry about this.

**Pull request closed without merging**
