### PR TITLE
Move Pixel Shuffle to ATen

### PR DESCRIPTION
**Pull request by ssnl**
<del>#9692 </del>

### CODE REVIEW

**Comment by fmassa** [comment]
needs a rebase @SsnL

**Review by ezyang — APPROVED** [review]

**Comment by eelregit** [comment]
We need 3D VoxelShuffle, and have implemented a generic nd PixelShuffle based on #6340, after fixing a bug [recently noticed there](https://github.com/pytorch/pytorch/pull/6340#discussion_r313784497).

We wonder why moving the 2d pixelshuffle to Aten, what's the benefits?

And for PR should we translate our generic python code to ATen?

If so, is it possible/straightforward to remain generic, or does it have to be specific for each ndim?

**Comment by ezyang** [comment]
We move code from TH/THC to ATen because: (1) it lets us avoid writing code in the crazy "this c file is included multiple times with different macro settings", (2) we can use smart pointers to avoid manual refcounting and (3) the API calls in C++ are nicer than C-style API calls.

Moving code from Python to ATen is a different set of tradeoffs. You might move this code because you need it to be available from the C++ frontend, or you need it to be runnable from multiple threads without the GIL.

I am not too sure about dim-generic-ness, as I have not looked at your implementation, but usually all Python code can be transliterated into C++ without loss of fidelity.

**Comment by eelregit** [comment]
Thanks for the explanation!

Our implementation is the following:

```python
def pixel_shuffle(input, upscale_factor):
    batch_size, channels, *input_sizes = list(input.size())
    dim = len(input_sizes)

    channels //= (upscale_factor ** dim)
    output_sizes = [input_size * upscale_factor for input_size in input_sizes]

    input_view = input.contiguous().view(batch_size, channels,
            *([upscale_factor] * dim), *input_sizes)

    axes = torch.arange(2, 2 + 2 * dim).reshape(2, dim)
    axes = axes[[1, 0]]
    axes = axes.transpose(0, 1).flatten()
    shuffle_out = input_view.permute(0, 1, *axes).contiguous()

    return shuffle_out.view(batch_size, channels, *output_sizes)
```

Looks transliteratible?

**Comment by rainwoodman** [comment]
@eelregit Instead of hard coding the shape array [here](https://github.com/zdevito/ATen/commit/72e318972d47f601b99dfab106fa80288c0b9da6#diff-281a70e827fb3768726cb310a84cce84R29),
you'll need to create a std::vector, or the equivalent in Aten. Probably something like [this](https://github.com/zdevito/ATen/blob/master/aten/src/ATen/native/Linear.cpp#L80)?

**Pull request closed without merging**
