### PR TITLE
Set MAX_JOBS to nproc - 1 if using sccache to compile CUDA

### PR DESCRIPTION
**Pull request by yf225**
By default `MAX_JOBS` is set to `multiprocessing.cpu_count()`, which will cause sccache to be stuck and then fail (https://github.com/mozilla/sccache/issues/248):
```
19:15:13 error: failed to execute compile
19:15:13 caused by: error reading compile response from server
19:15:13 caused by: Failed to read response header
19:15:13 caused by: failed to fill whole buffer
```

Setting `MAX_JOBS` to `$(nproc)-1` fixes the issue.

### CODE REVIEW

**Comment by ezyang** [comment]
LOOOL. Don't forget to link to the upstream bug :)

**Comment by yf225** [comment]
The NVCC patch is not in the upstream repo yet. I commented on [this issue](https://github.com/mozilla/sccache/issues/248).

**Comment by yf225** [comment]
@ezyang I tried to debug it but still haven’t figured out how to avoid doing -1 to the number of cores used. We probably need to merge this PR in order to use sccache for Linux CUDA builds.

**Review by ezyang — APPROVED** [review]

**Comment by yf225** [comment]
Possible reason for the need to do `nproc - 1` (copied from https://github.com/pytorch/pytorch/pull/7547#discussion_r188048707):

I suspect that it's because `sccache nvcc` is using `sccache gcc` as host compiler by default (because of the `CC` and `CXX` settings, or because `/opt/cache/bin` is the first path in the `PATH` env var), but if all cores are already used up by the `sccache nvcc` invocations, there will be no core available to the `sccache gcc` invocations and the compilation will be stuck. As a comparison, on Windows we explicitly specify `cl.exe` as CUDA_HOST_COMPILER and this issue doesn't appear.

There is probably a way to fix it e.g. by forcing NVCC to use `/usr/bin/cc` as host compiler regardless of `-ccbin` settings, but I haven't figured out a nice way to do so yet.

**Pull request merged**
