### PR TITLE
[DOC] Fix Optimizer state_dict docs

### LINKED ISSUE #60121: Optimizer state_dict documentation
## 📚 Documentation

Refer to: https://pytorch.org/docs/stable/generated/torch.optim.Optimizer.state_dict.html#torch.optim.Optimizer.state_dict
The `Optimizer.state_dict` consists of `state` and `param_groups`. `param_groups` is a list of dict, where each dict in the list is a param group (see [here](https://github.com/pytorch/pytorch/blob/84688b0c40abf23cf4d6f2f03f285e8ad1bc4da5/torch/optim/optimizer.py#L117)). The documentation incorrectly states that `param_groups` is a dict containing all parameter groups; rather, it is a list containing all parameter groups (where each parameter group is a dict). 

cc @brianjo @mruberry @vincentqb @iramazanli

### PR DESCRIPTION
**Pull request by bharatr21**
Fixes #60121 by correcting the `state_dict` docs
Tagging @mruberry @vincentqb @brianjo for review since they were originally mentioned in the issue

### CODE REVIEW

**Comment by mruberry** [comment]
@iramazanli -- would you review this?

**Comment by iramazanli** [comment]
Fix looks good, but a rebase to the latest master is needed.

**Review by iramazanli — COMMENTED** [review]
Fix looks good, but a rebase to the latest master is needed.

**Review by iramazanli — APPROVED** [review]

**Comment by iramazanli** [comment]
Thanks, looks pretty good now.

**Comment by jbschlosser** [comment]
@Bharat123rox can you please rebase onto master and I can get this in finally :)

**Pull request closed without merging**
