### PR TITLE
Remove deprecated factory functions from Type.

### PR DESCRIPTION
**Pull request by ezyang**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#11583 Remove deprecated factory functions from Type.**&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D9792800/)

Differential Revision: [D9792800](https://our.internmc.facebook.com/intern/diff/D9792800/)

### CODE REVIEW

**Comment by cpuhrsch** [comment]
Blocked on https://github.com/pytorch/pytorch/pull/11489 ?

**Review by gchanan — APPROVED** [review]
There might also be codegen we can remove...

**Comment by gchanan** [comment]
what about here: https://github.com/pytorch/pytorch/blob/739e6af86940f558f384a4a8922df8dc660d5660/aten/src/ATen/function_wrapper.py#L1083-L1092?  Can that go?

**Comment by SsnL** [comment]
@ezyang this seems mergeable

**Pull request closed without merging**
