### PR TITLE
Update cpuinfo submodule

### PR DESCRIPTION
**Pull request by malfet**
To suppress error on ARM systems where PR_SVE_GET_VL is missing

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by kit1980** [comment]
This is resolved for 2.5.1 by https://github.com/pytorch/pytorch/pull/138600

**Comment by kit1980** [comment]
Removing 2.5.1 from the PR as we have https://github.com/pytorch/pytorch/issues/138333 with the milestone

**Comment by kavikode** [comment]
What is the compatible torchvision repository for this version of pytorch?

Wishing to understand how to install from binary so that everything works out any error.

**Pull request closed without merging**
