### PR TITLE
[refactor] Renaming ao.sparsity to ao.pruning

### PR DESCRIPTION
**Pull request by z-a-f**
`Sparsity` as a term doesn't reflect the tools that are developed by the AO. The `torch/ao/sparsity` also has utilities for structured pruning, which internally we always referred to as just "pruning". To avoid any confusion, we renamed `Sparsity` to `Prune`. We will not be introducing the backwards compatibility, as so far this toolset was kept under silent development.

This change will reflect the changes in the documentation as well.

**TODO:**
- [ ] Change the tutorials
- [ ] Confirm no bc-breakages
- [ ] Reflect the changes in the trackers and RFC docs

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by supriyar** [comment]
should this be called `ao.pruning` instead of `ao.prune`? We generally use the term pruning in ML nomenclature. It also seems more aligned with the `ao.quantization` as opposed to `ao.quantize`. Thoughts?

**Comment by z-a-f** [comment]
> should this be called `ao.pruning` instead of `ao.prune`? We generally use the term pruning in ML nomenclature. It also seems more aligned with the `ao.quantization` as opposed to `ao.quantize`. Thoughts?

I agree -- was on the fence on that up until now. Will change

**Review by supriyar — APPROVED** [review]

**Comment by vkuzo** [comment]
should this be imported to Meta, to ensure internal callsites do not break?

**Comment by z-a-f** [comment]
> should this be imported to Meta, to ensure internal callsites do not break?

I will create a separate internal diff, once this is in the diff train

**Pull request closed without merging**
