### PR TITLE
Improve testing of logical_not.

### PR DESCRIPTION
**Pull request by gchanan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#38505 Improve testing of logical_not.**

This takes the testing of https://github.com/pytorch/pytorch/pull/38275, but doesn't include the kernel changes which are still being worked out.

Differential Revision: [D21580574](https://our.internmc.facebook.com/intern/diff/D21580574)

### CODE REVIEW

**Comment by vadimkantorov** [comment]
NumPy seems now to be [in requirements](https://github.com/pytorch/pytorch/blob/master/requirements.txt#L2). So I wonder if `skipIfNumPyNotFound` kind of skips are still meaningful

**Comment by gchanan** [comment]
that's a good question, I don't really know.  @mruberry do you know?

**Comment by mruberry** [comment]
> that's a good question, I don't really know. @mruberry do you know?

It looks like we will be OK taking a NumPy dependency in the tests, but let's leave the skips for now.

**Review by mruberry — APPROVED** [review]
A million times better! Also a good candidate for torch.testing.fixture when that's in.

**Pull request closed without merging**
