### PR TITLE
Updated sum() logic to properly deal with bool tensor

### PR DESCRIPTION
**Pull request by izdeby**
`torch.tensor([True, False, True], dtype=torch.bool).sum()` should return **2** instead of **True** as it does now. 

Tested via unit tests

### CODE REVIEW

**Review by colesbury — APPROVED** [review]
Please do a quick audit of isIntegralType. There's only ~14 usages. In Python `bool` is a subclass of `int`. I'm not sure if we want isIntegralType to reflect that, but we should at least check if there are other similar issues like this one.

For example, you may want this behavior in `cumsum` too.

**Comment by gchanan** [comment]
fwiw in NumPy boolean isn't considered an integer type.

**Review by gchanan — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
