### PR TITLE
CPUBlas: Use mkldnn optimized BFloat16 matmul for gemm

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #80977
* __->__ #65840

### CODE REVIEW

**Comment by mruberry** [comment]
Hey @peterbell10 -- just checking in on older PRs. What's the plan for this stack?

**Review by malfet — APPROVED** [review]

**Comment by CaoE** [comment]
Hi @peterbell10
This PR will lead to more reorders for computing bfloat16 using mkldnn. 
Small code example:
```
ln = torch.nn.Linear(1024, 786, True).to(torch.bfloat16)
input = torch.randn((1, 512, 1024)).to(torch.bfloat16)
out = ln(input)
```
We can see there are 2 reorder before and after matmul.
```
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_bf16::blocked:ba:f0 dst_bf16::blocked:ab:f0,attr-scratchpad:user ,,786x512,4.41797
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx_bf16,undef,src_bf16::blocked:ab:f0 wei_bf16::blocked:ba:f0 dst_bf16::blocked:ab:f0,attr-scratchpad:user attr-post-ops:sum ,,786x1024:1024x512:786x512,5.03906
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_bf16::blocked:ab:f0 dst_bf16::blocked:ba:f0,attr-scratchpad:user ,,786x512,0.0439453
```
Revert this PR:
```onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx_bf16,undef,src_bf16::blocked:ab:f0 wei_bf16::blocked:ba:f0 dst_bf16::blocked:ab:f0,attr-scratchpad:user attr-post-ops:sum ,,512x1024:1024x786:512x786,5.38208
```
Reorder will be removed.

**Comment by peterbell10** [comment]
@CaoE can you check if #82968 changes anything? I don't have AVX512 hardware to test on atm.

**Comment by CaoE** [comment]
> @CaoE can you check if #82968 changes anything? I don't have AVX512 hardware to test on atm.

Yes, with https://github.com/pytorch/pytorch/pull/82968 the reorder will be removed.
```
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx_bf16,undef,src_bf16::blocked:ab:f0 wei_bf16::blocked:ba:f0 dst_bf16::blocked:ab:f0,attr-scratchpad:user attr-post-ops:sum ,,512x1024:1024x786:512x786,5.396
```

**Pull request closed without merging**
