### PR TITLE
Enhance error message for dependency check

### PR DESCRIPTION
**Pull request by wangxiyuan**
If python development library is missing when building pytorch from source, cmake will raise the error like:
```
CMake Error at cmake/Dependencies.cmake:1079 (if):
  if given arguments:

    "VERSION_LESS" "3"

  Unknown arguments specified
```

it's quite a misleading information that user would consider it's a syntax error or cmake version problem.

This PR add a check to ensure `PYTHONLIBS_VERSION_STRING` exist before using.

Related  #87993

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
Which CMake version? 
`PYTHONLIBS_VERSION_STRING` is only available since CMake 2.8.8 - https://github.com/Kitware/CMake/blob/master/Modules/FindPythonLibs.cmake, maybe that's the problem?

**Comment by kit1980** [comment]
And if `PYTHONLIBS_VERSION_STRING` is empty because of old CMake, the error message is very misleading.

**Comment by wangxiyuan** [comment]
> 

pytorch requires cmake 3.18 at least. https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L1

So it's impossbile that if `PYTHONLIBS_VERSION_STRING` is empty because of old CMake

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
