### PR TITLE
[BE] Move upload logic to shared template

### PR DESCRIPTION
**Pull request by malfet**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #72427
* __->__ #72426
* #72425

Differential Revision: [D34050483](https://our.internmc.facebook.com/intern/diff/D34050483)

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
I trust your copying/pasting :)

**Comment by malfet** [comment]
> I trust your copying/pasting :)

I've checked that there are no changes in generated workflows other than newline

**Comment by malfet** [comment]
> I trust your copying/pasting :)

I've checked that there are no changes in generated workflows other than newline

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34050483).

**Pull request closed without merging**
