### PR TITLE
[ROCm] Enable test_filtering_env_var

### PR DESCRIPTION
**Pull request by jaglinux**
The test "test_filtering_env_var" requires CPU device_type along with GPU.
Hence enable both device_types for ROCm, since the PYTORCH_TESTING_DEVICE_ONLY_FOR env var will have the same effect as the code being removed, making the latter redundant anyway:
https://github.com/pytorch/pytorch/blob/9e81c0c3f46a36333e82b799b4afa79b44b6bb59/.jenkins/pytorch/test.sh#L54-L59
https://github.com/pytorch/pytorch/blob/9e81c0c3f46a36333e82b799b4afa79b44b6bb59/torch/testing/_internal/common_device_type.py#L626-L634

Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>

Enables the test disabled by #56178

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Comment by jaglinux** [comment]
cc @jeffdaily @jithunnair-amd

**Review by jeffdaily — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@jaglinux I triggered single-GPU unit tests using trunk workflow. Please post a snippet of the passing log for the unit test.

**Comment by jaglinux** [comment]
2023-01-31T04:50:58.8964905Z   test_filtering_env_var (__main__.TestFrameworkUtils) ... ok (17.269s)
[(source)](https://pipelines.actions.githubusercontent.com/serviceHosts/7d146c05-69c3-4c20-a0e7-818111670117/_apis/pipelines/1/runs/2595572/signedlogcontent/281?urlExpires=2023-01-31T06%3A21%3A30.4045629Z&urlSigningMethod=HMACV1&urlSignature=hWhJ%2FxA1%2BJ3AgGn%2FOCQqLWji2cc3aGdlpDCdtPJhmf0%3D)

**Comment by jaglinux** [comment]
@jithunnair-amd good to merge.

**Review by malfet — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@malfet I added the "topic: not user facing" label to make the bot happy. Please change it to "release notes:" label if you think that's appropriate.

**Pull request closed without merging**
