### PR TITLE
make functorch CSE respect mutations as barriers (like fsdp.set_)

### PR DESCRIPTION
**Pull request by bdhirsh**
Fixes https://github.com/pytorch/pytorch/issues/132200

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #132338
* #132524
* #132322
* #132337
* __->__ #132243

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Sounds good!

**Review by zou3519 — APPROVED** [review]

**Review by eellison — COMMENTED** [review]
I'm not sure this is sound: what about :

```
y = x + 1
y2 = x + 1 
fsdp.set_.default(y, z)
```

I guess we have the invariant that we're only mutating inputs, so we can't induce alias relationships to them ?

**Comment by bdhirsh** [comment]
Good catch. I tested locally, and we assert that mutations in the graph (just `set_` and `copy_` today) are only allowed on placeholders here: https://github.com/pytorch/pytorch/blob/main/torch/_functorch/_aot_autograd/functional_utils.py#L421. So we could beef up the CSE pass, although it would be hard to write a proper test for it since we'll hit that assert anyway.

**Comment by eellison** [comment]
@bdhirsh as long as we have that invariant no need to beef up.

**Review by yf225 — APPROVED** [review]
Thanks @bdhirsh!

**Pull request closed without merging**
