### PR TITLE
update test_libtorch

### PR DESCRIPTION
**Pull request by tktrungna**
Fixes #62380

* update test functions to call wheel install folder {sitepackages}/torch instead of build/ folder
* add symbolic link for shared libraries which are called by the tests (this is a bit hacky and should be fixed the rpath before compiling -- similar to https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/test.sh#L204-L208).

### Test plan
check if all ci workflows pass

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #62838
* __->__ #62797
* #62796
* #62795
* #62781

Differential Revision: [D30193140](https://our.internmc.facebook.com/intern/diff/D30193140)

### CODE REVIEW

**Comment by tktrungna** [comment]
@tktrungna has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30193140).

**Comment by tktrungna** [comment]
@tktrungna has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30193140).

**Comment by tktrungna** [comment]
@tktrungna has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30193140).

**Review by walterddr — APPROVED** [review]

**Comment by tktrungna** [comment]
@tktrungna has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30193140).

**Pull request closed without merging**
