### PR TITLE
added pixel shuffle layer + tests

### PR DESCRIPTION
**Pull request by alykhantejani**
Added the PixelShuffle layer which rearranges elements in a tensor of shape `[B, C*r, H, W]` to a tensor of shape `[B, C, H*r, W*r]`.

This is useful for implementing efficient sub-pixel convolution with a stride of 1/r, which can be used for tasks such as super-resolution (see "Real-Time Single Image and Video Super-Resolution Using an Efficient Sub-Pixel Convolutional Neural Network" - Shi et al.).

### CODE REVIEW

**Review by apaszke — CHANGES_REQUESTED** [review]
Looks good, but please save the output for backward and don't keep the grad buffer around.

**Review by apaszke — CHANGES_REQUESTED** [review]
Sorry, I misread the code last time 😕

**Review by apaszke — CHANGES_REQUESTED** [review]
Last minor thing

**Review by apaszke — APPROVED** [review]

**Comment by danieltudosiu** [comment]
Is it possible to generalize it to 5D tensors (B, C, D, W, H)?

**Pull request merged**
