### PR TITLE
Increase number of shards for linux aarch64 jobs

### PR DESCRIPTION
**Pull request by atalman**
Related to a SEV: https://github.com/pytorch/pytorch/issues/136192

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!

**Review by malfet — CHANGES_REQUESTED** [review]
Please do not merge unless it fixes the timeout. And I think it's important to investigate, why test time increase so drastically.  
And perhaps another idea: why testing on T4 rather than on C7?

**Comment by atalman** [comment]
Yes Agree. If the timeout is not resolved. We should try to use t4 machines!

**Comment by atalman** [comment]
not required anymore

**Pull request closed without merging**
