### PR TITLE
Fix formatting of scalar tensors (don't call item)

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #74376

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D35063740](https://our.internmc.facebook.com/intern/diff/D35063740)

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
lgtm

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35063740).

**Pull request closed without merging**
