### PR TITLE
[IntraNodeComm] refactor rendezvous into a separate method for better code organization and error handling

### PR DESCRIPTION
**Pull request by yifuwang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #122163
* #118038
* __->__ #120968

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]
sgtm!

**Review by wconstab — COMMENTED** [review]
@shuqiangzhang @kwen2501 Please TAL.
I didn't review this but just from the desc, it sounds like it's going the opposite direction -  we wanted to steer people towards using device_id up front and doing eager init, not more lazy init.  Please align here

**Comment by yifuwang** [comment]
Hey @wconstab, thanks for the heads up. I didn't know about the eager init direction but I'm all for it! `IntraNodeComm` can already detect conflicting devices among ranks and abort gracefully. We'll just keep it that way.

The PR makes things cleaner so I'd like to keep it. But I'll modify the description to make it not about lazy init.

**Pull request closed without merging**
