### PR TITLE
[inductor] update triton pin

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104303

### CODE REVIEW

**Review by desertfire — APPROVED** [review]
Stamp to unblock, but please sync with internal oncall to verify.

**Comment by shunting314** [comment]
> Stamp to unblock, but please sync with internal oncall to verify.

Will do. What's the internal oncall name?

**Comment by shunting314** [comment]
NVM, I found the internal oncall and updated the OSS oncall run book.

**Comment by shunting314** [comment]
Perf looks [neutral](https://hud.pytorch.org/benchmark/compilers?startTime=Wed%2C%2021%20Jun%202023%2017%3A44%3A03%20GMT&stopTime=Wed%2C%2028%20Jun%202023%2017%3A44%3A03%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=shunting-new-triton-pin&lCommit=f0002335e31f2452eaa9daafcdf9e11fba65222e&rBranch=main&rCommit=7cef7195f616f75bf25a48cf5692f704d35ac4b2) . The [dynamic] set of models has a perf drop from 2.02 -> 1.98x . But since there are only 8 models in this set, I think it's likely some noise.

**Pull request closed without merging**
