### PR TITLE
cast return of cudaGetLastError() to void when discarding

### LINKED ISSUE #62511: Internal builds are failing with HIP errors
```
stderr: In file included from buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/operators/hip/concat_split_op_gpu.cc/caffe2/operators/hip/concat_split_op_gpu.cc:2:
In file included from buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/core/hip/context_gpu.h/caffe2/core/hip/context_gpu.h:9:
In file included from buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/core/hip/common_gpu.h/caffe2/core/hip/common_gpu.h:27:
In file included from buck-out/dev/gen/caffe2/c10/fb_c10_hipify_gen/c10/hip/HIPGuard.h:8:
In file included from buck-out/dev/gen/caffe2/c10/fb_c10_hipify_gen/c10/hip/impl/HIPGuardImpl.h:9:
In file included from buck-out/dev/gen/caffe2/c10/fb_c10_hipify_gen/c10/hip/HIPCachingAllocator.h:5:
In file included from buck-out/dev/gen/caffe2/c10/fb_c10_hipify_gen/c10/hip/HIPGraphsC10Utils.h:4:
buck-out/dev/gen/caffe2/c10/fb_c10_hipify_gen/c10/hip/HIPStream.h:123:7: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
      hipGetLastError();
      ^~~~~~~~~~~~~~~
In file included from buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/operators/hip/concat_split_op_gpu.cc/caffe2/operators/hip/concat_split_op_gpu.cc:2:
In file included from buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/core/hip/context_gpu.h/caffe2/core/hip/context_gpu.h:9:
In file included from buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/core/hip/common_gpu.h/caffe2/core/hip/common_gpu.h:27:
In file included from buck-out/dev/gen/caffe2/c10/fb_c10_hipify_gen/c10/hip/HIPGuard.h:8:
buck-out/dev/gen/caffe2/c10/fb_c10_hipify_gen/c10/hip/impl/HIPGuardImpl.h:173:7: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
      hipGetLastError();
      ^~~~~~~~~~~~~~~
In file included from buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/operators/hip/concat_split_op_gpu.cc/caffe2/operators/hip/concat_split_op_gpu.cc:2:
buck-out/dev/gen/caffe2/caffe2/fb_caffe2_hipify_gen=caffe2/core/hip/context_gpu.h/caffe2/core/hip/context_gpu.h:317:7: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
      hipGetLastError();
      ^~~~~~~~~~~~~~~
3 errors generated.
```
this is due to #61554, afaiu. cc @malfet @seemethere @walterddr @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### PR DESCRIPTION
**Pull request by jeffdaily**
Fixes #62511.

### CODE REVIEW

**Comment by malfet** [comment]
Unfortunately it does not fix all the issues, digging further...

**Comment by jeffdaily** [comment]
Let me know how I can help, if there is any sort of build log I could access.

**Comment by malfet** [comment]
@jeffdaily do you know if older version of hipcc could generate following error:
```
caffe2/aten/src/ATen/core/TensorAccessor.h:160:5: error: throw is prohibited in AMP-restricted functions
    TORCH_CHECK_INDEX(
    ^
```
Can workaround it by disabling this check for HIP code, but wonder if better fix would be to just make this function CPU-only

**Comment by malfet** [comment]
Reduced the PR to change in only 4 files: `c10/cuda/impl/CUDAGuardImpl.h`, `c10/cuda/CUDAStream.h`, `caffe2/core/context_gpu.h` and `caffe2/core/event_gpu.cc`, landing it now

**Pull request closed without merging**
