### PR TITLE
[DO NOT REVIEW] Debugging mysterious handle pool hang on Windows

### PR DESCRIPTION
**Pull request by mcarilli**
attempting to figure out why the heck my threading logic is inducing nondeterministic hangs on test_rnn_backward_to_input_but_not_parameters_cuda in pytorch-win-ws2016-cuda9-cudnn7-py3-test2.  

The CI scripts are hopefully figured to run the build and test for that config alone.

### CODE REVIEW

**Comment by mcarilli** [comment]
@mcarillibot tell pytorch bot to retest this please

**Comment by varkonyidavid91** [comment]
Did you figure out the cause of the hang? I'm facing the same issue, cudnnCreate non-deterministically hangs. My app isn't multithreaded though, so mutexing it doesn't help, but I think the root issue might be the same, cause I couldn't find anybody else with this problem (cudnnCreate hanging).

I'm on Win 10, CUDA 10.1, CUDNN 7.5, and I tried creating the handle in a DllMain, which caused the hang. Moving it out of the DllMain seems to solve the hang itself, but if I do that, the first time the handle is used I get a CUDNN_STATUS_BAD_PARAM, also non-deterministically.

I think all of this is caused by the same thing, I just have no idea what.

**Comment by ezyang** [comment]
No, we never figured it out. In the end, @mcarilli found a workaround which seemed to perturb timing or something to make the hang not happen, and we shipped it.

Are you running on PyTorch, or is this your on Windows CuDNN app? If the latter, it is well worth to file a bug with NVIDIA on the issue. We're pretty sure it's an obscure CuDNN bug on Windows.

**Comment by varkonyidavid91** [comment]
It's my own windows CuDNN app. I'll try to file a bug report with NVIDIA, cause I think too that it's on their side.

**Pull request closed without merging**
