### PR TITLE
[Feature] storage resize_ support custom device.

### LINKED ISSUE #99326: Contribute to storage for the privateuse1 backend.
### 🚀 The feature, motivation and pitch

Hi, 
```class _StorageBase``` is mainly used for the CUDA backend and CPU backend.  Currently  I want to contribute to storage for the privateuse1 backend.  The content to be modified consists of two parts: 

part a: python API, just like  ```pin_memory```

part b: C++ API, just like ```THPStorage_resize```

I don't know if it's better to add a function branch for privateuse1 backend or extract it into a function with distribution capabilities by dispatch.

### Alternatives

For  func  ```def pin_memory(self, device="cuda"):```  to support privateuse1 backend,  an backend-related allocator is need . The possible modification is as follows(example).  

```
    def pin_memory(self, device="cuda"):
        if device == "cuda":
            import torch.cuda
            allocator = torch.cuda.memory._host_allocator()  # type: ignore[attr-defined]
            return type(self)(self.size(), allocator=allocator).copy_(self)
        elif device == torch._C._get_privateuse1_backend_name():
            allocator = torch.privateuse1.memory._host_allocator()
            return type(self)(self.size(), allocator=allocator).copy_(self)
       else:
            raise error
```
In privateuse1.memory:
```
def _host_allocator():
    return torch._C._privateuse1_HostAllocator()

And the completed implementation is implemented by the specific backend, and an allocator is returned.
```

<br/>
<br/>
On the other hand,  <br/>
I want to wrap the cpu storage to a cpu tensor, and use this parameter the param ```device``` as dispatch key for different backbend, such as ```cuda, privateuse1```. just like the fellowing example.

```
    def pin_memory(self, device="cuda"):
            cpu_tensor = empty([]).set_(self)
            set cpu_tensor  dispatch key by device
            return type(self)(cpu_tensor.pin_memory().storage())
```
By this way, no need more function branch for new backend.

### Additional context

Would you please give me some advice? Thanks a lot.  @smessmer  @bdhirsh @ezyang @zou3519

### PR DESCRIPTION
**Pull request by wbigat**
Fixes #99326 

Support storage resize_ for custom device, by calling dispatched tensor operations.

@ezyang  this pr is another case  that was brought up in issue #99326,  please take a moment to review this change.

### CODE REVIEW

**Comment by wbigat** [comment]
For custom device,  a interface ```resize_bytes_xxx```  is needed for  ```THPStorage_resize_```.
But some subfunctions in ```resize_bytes_xxx```  are device-related, such as memory_copy from device to device.
As a result, it is inconvenient for privateuse1 backend to provide an interface for all custom devices.

  When trying to use ```resize_```  to replace  ```resize_bytes_xxx```,  in some cases,  the original memory pointer is still returned, which is an inconsistent behavior when compared to  ```resize_bytes_xxx```.  For these cases, an additional memory copy and DataPtr  updat for storage are required.

**Comment by ezyang** [comment]
Why not *always* do the copy path, and then swizzle the data pointer from the fresh storage?

**Comment by wbigat** [comment]
> Why not _always_ do the copy path, and then swizzle the data pointer from the fresh storage?

In the implementation of  ```resize_bytes_cuda```  and  ```resize_bytes_cpu```, when the ```nbytes``` of  target size  is larger than the original size's , a new data pointer will be created and updated to storage.   Therefore, no need to do the copy patch in those cases.

Is this the key point that you care about ?  Looking forward to your reply.  @ezyang

**Comment by ezyang** [comment]
> In the implementation of resize_bytes_cuda and resize_bytes_cpu, when the nbytes of target size is larger than the original size's , a new data pointer will be created and updated to storage. Therefore, no need to do the copy patch in those cases.

This is purely from a simplifying implementation perspective. The copy patch always works, so why bother with the resize (which sometimes works and sometimes doesn't.)

**Comment by wbigat** [comment]
> This is purely from a simplifying implementation perspective. The copy patch always works, so why bother with the resize (which sometimes works and sometimes doesn't.)

Okey，your suggestion is that we can always do the copy to simplify implementation , regardless of whether a new data ptr is created in the ```resize_``` implementation.   Just like the following.

```
else if (device_type == at::kPrivateUse1) {
    ptrdiff_t size_bytes_i = newsize;
    TORCH_CHECK(
        !c10::overflows<size_t>(size_bytes_i),
        "Requested storage size (",
        size_bytes_i,
        ") cannot be represented as a size_t");
    const auto size_bytes = static_cast<size_t>(size_bytes_i);
    auto src_option =
        c10::TensorOptions().device(storage.device()).dtype(at::kByte);
    auto src_tensor = at::empty({0}, {}, src_option).set_(storage);
    src_tensor.resize_({size_bytes});
    auto new_tensor = at::empty(src_tensor.sizes(), src_tensor.options());
    new_tensor.copy_(src_tensor);
    storage.set_data_ptr_noswap(
        std::move(const_cast<at::DataPtr&>(new_tensor.storage().data_ptr())));
    storage.unsafeGetStorageImpl()->set_allocator(
        new_tensor.storage().unsafeGetStorageImpl()->allocator());
    storage.set_nbytes(new_tensor.storage().nbytes());
  }
```

**Comment by ezyang** [comment]
Yes. You can shorten the code more by directly allocating a byte tensor at needed size instead if setting in the storage. Also if we still have a Storage move assignment you can use that to update fields (but maybe @kurtamohler deleted it)

**Comment by wbigat** [comment]
> shorten the code more by directly allocating a byte tensor at needed size instead if setting in the stora

**Comment by wbigat** [comment]
> Yes. You can shorten the code more by directly allocating a byte tensor at needed size instead if setting in the storage. Also if we still have a Storage move assignment you can use that to update fields (but maybe @kurtamohler deleted it)

I'm sorry I haven't seen an existing method to complete the storage move.

**Comment by ezyang** [comment]
Oh it looks like you have done the simplification

**Comment by ezyang** [comment]
Actually, I am looking and I see why you think it is worse. Let's go back to the old implementation.

**Comment by kurtamohler** [comment]
I don't remember the history of storage move assignment. I will check on it, but I'm on PTO this week, so I'll follow up next week

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
need to fix build

**Comment by kurtamohler** [comment]
> Also if we still have a Storage move assignment you can use that to update fields (but maybe @kurtamohler deleted it)

Just to follow up on this, I did have to remove the StorageImpl move assignment operator in #93342 in order to add the PyObjectSlot to it, because it has a `std::atomic`

**Pull request closed without merging**
