### PR TITLE
#8518 Support for empty tuples

### PR DESCRIPTION
**Pull request by jramseyer**
Fixing #8518

Sorry for the pile of commits; I forgot to rebase.

### CODE REVIEW

**Comment by jramseyer** [comment]
I will figure out what is wrong with the build.

**Comment by jramseyer** [comment]
Looks like one failure is a known test case problem, seen here: https://github.com/pytorch/pytorch/pull/10049  Once that lands, should fix one bug.  

The other failure is in test_cuda, I'll look at that

**Comment by goldsborough** [comment]
You may want to set `--rebase` as default for the future to avoid merging by accident. You'll really only ever need the `--rebase` option to be true: `git config --global pull.rebase true`

**Comment by jramseyer** [comment]
Thanks!  I will do that!

**Review by zdevito — APPROVED** [review]
Looks good, thanks!

**Pull request closed without merging**
