### PR TITLE
[DataLoader] Close byte stream explicitly

### PR DESCRIPTION
**Pull request by ejguan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #59464 [DataLoader] Switch NotImplementedError to TypeError for len
* **#58938 [DataLoader] Close byte stream explicitly**

When run `test_datapipe.py`, python `gc` would report lots of `ResourceWarning`s due to unclosed stream. It's not only annoying, there are two potential problems:
- Performance regression because `gc` requires additional memory and computation to track reference
- Python `gc` runs periodically so we many encountered an error of too many open files due to OS limitation
To reduce the warning:
- Explicitly close byte stream 
- Modify `test_datapipe.py` to use context manager

Small fix:
- Reorder import in `test_datapipe.py`

Further investigation:
Can we directly use context manager in `LoadFileFromDisk` and `ReadFileFromTar` to eliminate this Error?
- Probably no. It's feasible only if the pipeline is synchronized and without prefetching. When we enable these two features, the scope guard of the context manager doesn't work.
- We may need to implement some reference counter attached to these file byte stream to close by itself.

Differential Revision: [D28689862](https://our.internmc.facebook.com/intern/diff/D28689862)

### CODE REVIEW

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28689862).

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28689862).

**Review by pmeier — APPROVED** [review]
Should we have a test that asserts that a file handle is closed after it has been processed by the decoder? Otherwise LGTM, thanks @ejguan!

**Comment by pmeier** [comment]
On a side note: we should document somewhere that it is the users responsibility to close the opened file handles if he doesn't use the builtin decoder.

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28689862).

**Pull request closed without merging**
