### PR TITLE
Cudnn conv cache key patch

### LINKED ISSUE #81106: torchvision.transforms.functional.rgb_to_grayscale() + torch.nn.Conv2d() don`t work on 1080 GPU
### 🐛 Describe the bug

Code to reproduce bug:
```
import gc

import torch
import torchvision


def bench(model, device, memory_format):

    model = model.to(device=device, dtype=torch.float, memory_format=memory_format, non_blocking=False)
    model.eval()

    batch = torch.rand(8,3,256,256, device=device).to(device=device, dtype=torch.float, memory_format=memory_format, non_blocking=False)

    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.synchronize()

    with torch.inference_mode():
        with torch.autocast(device.type, enabled=True):
            model(batch)

    del batch



class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()

        self.conv1 = torch.nn.Conv2d(1, 8, kernel_size=5, stride=1, bias=False)


    def forward(self, x):
        print('before', x.device, x.dtype, x.layout, x.is_contiguous())
        x = torchvision.transforms.functional.rgb_to_grayscale(x, num_output_channels=1)
        print('after', x.device, x.dtype, x.layout, x.is_contiguous())

        x = self.conv1(x)

        return x


def main_worker():

    device = torch.device("cuda")


    bench_model = MyModel()
    bench_model.eval()

    bench(bench_model, device, torch.contiguous_format)
    bench(bench_model, device, torch.torch.channels_last)


if __name__ == '__main__':

    main_worker()
```

Output:
```
before cuda:0 torch.float32 torch.strided True
after cuda:0 torch.float32 torch.strided True
before cuda:0 torch.float32 torch.strided False
after cuda:0 torch.float32 torch.strided True
Traceback (most recent call last):
  File "1.py", line 57, in <module>
    main_worker()
  File "1.py", line 52, in main_worker
    bench(bench_model, device, torch.torch.channels_last)
  File "1.py", line 20, in bench
    model(batch)
  File "/home/xxxxx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "1.py", line 38, in forward
    x = self.conv1(x)
  File "/home/xxxxx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxxxx/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/xxxxx/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.


import torch
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([8, 1, 256, 256], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(1, 8, kernel_size=[5, 5], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_HALF
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x4f4374d0
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 8, 1, 256, 256,
    strideA = 65536, 1, 256, 1,
output: TensorDescriptor 0x4f448120
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 8, 8, 252, 252,
    strideA = 508032, 1, 2016, 8,
weight: FilterDescriptor 0x4f1b6720
    type = CUDNN_DATA_HALF
    tensor_format = CUDNN_TENSOR_NHWC
    nbDims = 4
    dimA = 8, 1, 5, 5,
Pointer addresses:
    input: 0x7f9abe800800
    output: 0x7f9abf800000
    weight: 0x7f9abe800000
Forward algorithm: 1
```

### Versions

```
~$ python3 collect_env.py
Collecting environment information...
PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-66-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1080
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] torch==1.12.0+cu116
[pip3] torchaudio==0.12.0+cu116
[pip3] torchvision==0.13.0+cu116
[conda] Could not collect
```

```
~$ nvidia-smi
Fri Jul  8 16:16:27 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 38%   56C    P2    40W / 180W |   5261MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   1740557      C   /usr/bin/python3                 5259MiB |
+-----------------------------------------------------------------------------+
```

cc @ngimel @fmassa @vfdev-5 @pmeier

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #81106 

Patches on cudnn algo cache to consider the right memory_format used in descriptors, instead of blindly copy the memory_format on inputs.
Note that to be on the safe side, we could actually cache on all tensor strides instead. But given how we short-cut and align memory_format from pytorch tensor to cudnn descriptor, it suffice to have a single field in the cache.

### CODE REVIEW

**Comment by xwang233** [comment]
cc @eqy  for v8 changes

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Is it possible to add a test for this? Unfortunately it looks like the repro in torchvision fails only on some GPUs.

**Comment by eqy** [comment]
@jjsjann123 just wanted to check that the intent for the V8 changes is to add a almost always-correct memory layout hint in the cache key---as V8 won't use this memory layout to select a kernel (I believe these constraints are inferred from strides, etc.), and there is no guarantee that the weight and input tensors share the same layout. In the extremely unlikely and worst case where a cached kernel is incompatible with the current workload (e.g., weight layout was previously the same as input layout but now different), `CUDNN_STATUS_BAD_PARAM` is recoverable and with the current V8 implementation just incur the cost of finding another candidate kernel. As you say the safest solution would be to cache on the layouts of all tensors, but it could be overkill from a fault-tolerance perspective in V8.

**Comment by jjsjann123** [comment]
The change for v8 in this PR is just a side effect of update to `setConvolutionParams`. It didn't change any behavior, as we don't see v8 using that stride descriptor any way so I don't see a need to update it. :shrug: 

> there is no guarantee that the weight and input tensors share the same layout
IIRC, weight and input should always be in the same format for convolution. This was an unfortunate compromise when we first plumbed channels last support for convolution, due to the poor coverage of cudnn support on mixed memory format.

**Comment by jjsjann123** [comment]
> Is it possible to add a test for this? Unfortunately it looks like the repro in torchvision fails only on some GPUs.

I can try to add a test to make us feel better. I don't know how useful that would be tho.
The issue we run into only repros on P100 (with cudnn v7 APIs). Do upstream CI runs on sm_6x cards?

**Pull request closed without merging**
