### PR TITLE
Move ThreadLocalDebugInfo to c10

### PR DESCRIPTION
**Pull request by ilia-cher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #37587 RecordFunction in Dispatcher
* #37639 Use TensorMethods.cpp
* #37775 Memory profiling
* **#37774 Move ThreadLocalDebugInfo to c10**

Summary:
Move ThreadLocalDebugInfo from ATen to C10

Differential Revision: [D21384249](https://our.internmc.facebook.com/intern/diff/D21384249)

### CODE REVIEW

**Review by dzhulgakov — APPROVED** [review]
Sure

**Comment by dzhulgakov** [comment]
Actually - seems like there are some missing annotations, the build is broken

**Comment by ilia-cher** [comment]
yes, looking

**Comment by ilia-cher** [comment]
fixing build error for older gcc versions

**Pull request closed without merging**
