### PR TITLE
[logging] Add dynamo_compile fields for pre-dispatch/joint/post-dispatch times

### PR DESCRIPTION
**Pull request by masnesral**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #140306

Tested internally: P1679622670

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

Differential Revision: [D65986059](https://our.internmc.facebook.com/intern/diff/D65986059)

### CODE REVIEW

**Review by ezyang — CHANGES_REQUESTED** [review]
Pending potential field rename

**Review by ezyang — APPROVED** [review]

**Comment by masnesral** [comment]
@masnesral has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D65986059).

**Comment by masnesral** [comment]
@masnesral has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D65986059).

**Pull request closed without merging**
