### PR TITLE
Test torch._refs with aten and nvfuser executors

### PR DESCRIPTION
**Pull request by IvanYashchuk**
This PR adds testing of references with "aten" and "nvfuser" executors using `torch._prims.executor.make_traced`.

Many tests are skipped even for "aten" executor because of https://github.com/pytorch/pytorch/issues/78923.

I limited the dtypes for the nvfuser executor tests because it's slow due to compilation overhead (it took about 30 mins in total). With `float32` and `int32` types nvfuser tests take 5 minutes.
```
58 passed, 2507 skipped, 28162 deselected, 79 xfailed, 5 warnings in 297.58s (0:04:57)
```
58 tests passed means that 29 references work correctly with nvfuser executor now.

### CODE REVIEW

**Comment by mruberry** [comment]
This is brilliant, @IvanYashchuk! Let's get this merged once the tests pass

**Comment by IvanYashchuk** [comment]
@mruberry, could you please approve this PR?

**Review by mruberry — APPROVED** [review]
Stamped!

**Comment by IvanYashchuk** [comment]
> @pytorchbot revert -m "breaks rocms, see https://hud.pytorch.org/pytorch/pytorch/commit/d4eebca7bc14b28688914577f690b68313cb846f" -c "ignoredsignal"

@malfet, are ROCm jobs not run on PRs normally anymore? How can they be enabled?

**Pull request closed without merging**
