### PR TITLE
[DataPipe] Remove Typing for DataPipe

### PR DESCRIPTION
**Pull request by ejguan**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Review by malfet — CHANGES_REQUESTED** [review]
@ejguan can you please explain why this change is release specific?

**Comment by ejguan** [comment]
@malfet 
We want to disable the typing system for `IterDataPipe` because two reasons:
- It's a prototype feature and not stable for new release
- It's not well supporting python 3.10 that we haven't fully tested. We rely on Python typing system, which has a few BC breaking changes in python 3.10. IIRC, we are going to support Python 3.10, it's better to exclude it from PyTorch 1.11

**Comment by ejguan** [comment]
@malfet 

It's actually landed into master branch. But, I will re-enable it on master branch after I fully test it with Python 3.10. So, I think this is more related to release branch specific change. wdyt?

**Comment by ejguan** [comment]
NVM, the PR has been merged into release. I am closing this PR.

**Pull request closed without merging**
