### PR TITLE
fallback operators to CPU for onnx support

### PR DESCRIPTION
**Pull request by gujinghui**
fallback operators to CPU for onnx support

### CODE REVIEW

**Comment by gujinghui** [comment]
@yinghai 
pls help review

**Comment by gujinghui** [comment]
@yinghai 
Customers and end-users have topologies in ONNX format, which are converted from other frameworks.
They found ONNX topo cannot run on caffe2 with MKLDNN directly. So we need to support ONNX on their demands.

BTW, the convert tool for ONNX-to-caffe2 will generate some bad pattern at the end of topo graph, which is only trying to impl a FC. Do we have plan to optimize it?

**Comment by gujinghui** [comment]
Looks like below...
capture

**Comment by gujinghui** [comment]
@yinghai 
rebased. pls help review.

**Comment by gujinghui** [comment]
@yinghai 

The failure should not be caused by this PR.

> Jan 11 07:52:38 Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /var/lib/jenkins/.torch/models/resnet18-5c106cde.pth
Jan 11 07:52:38 ERROR
Jan 11 07:52:38 test_check_onnx_broadcast (__main__.TestONNXUtils) ... ok
Jan 11 07:52:38 test_prepare_onnx_paddings (__main__.TestONNXUtils) ... ok
Jan 11 07:52:38 
Jan 11 07:52:38 ======================================================================
Jan 11 07:52:38 ERROR: setUpClass (__main__.TestHub)
Jan 11 07:52:38 ----------------------------------------------------------------------
Jan 11 07:52:38 Traceback (most recent call last):
Jan 11 07:52:38   File "/opt/conda/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
Jan 11 07:52:38     (self._dns_host, self.port), self.timeout, **extra_kw)
Jan 11 07:52:38   File "/opt/conda/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
Jan 11 07:52:38     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
Jan 11 07:52:38   File "/opt/conda/lib/python3.6/socket.py", line 745, in getaddrinfo
Jan 11 07:52:38     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Jan 11 07:52:38 socket.gaierror: [Errno -3] Temporary failure in name resolution
Jan 11 07:52:38 
Jan 11 07:52:38 During handling of the above exception, another exception occurred:

**Comment by gujinghui** [comment]
@yinghai
rebased. pls help review.

**Comment by gujinghui** [comment]
@yinghai
rebased. pls help review.

**Review by yinghai — COMMENTED** [review]
Rebase?

**Comment by gujinghui** [comment]
rebased. pls help review. @yinghai

**Comment by gujinghui** [comment]
hi @yinghai 
rebased. pls help review.

**Comment by gujinghui** [comment]
@yinghai
most of all failures are caused by below issue.
should not be related to this PR.

> Feb 13 21:08:13 /Users/distiller/pytorch-ci-env/clang++  -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -DUSE_GCC_ATOMICS=1 -D_FILE_OFFSET_BITS=64 -D_THP_CORE -Dtorch_EXPORTS -I../aten/src -I. -I../ -I../third_party/protobuf/src -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -I../torch/csrc/api -I../torch/csrc/api/include -I../torch/../aten/src/TH -Icaffe2/torch/../aten/src/TH -I../torch/../aten/src -Icaffe2/torch/../aten/src -Iaten/src -Icaffe2/torch/../aten/src/ATen -I../torch/csrc -I../torch/../third_party/miniz-2.0.8 -I../c10/.. -isystem /Users/distiller/pytorch-ci-env/miniconda3/include -isystem ../third_party/ideep/include -isystem ../third_party/ideep/mkl-dnn/include -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /Users/distiller/pytorch-ci-env/miniconda3/include/python3.7m -isystem /Users/distiller/pytorch-ci-env/miniconda3/lib/python3.7/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -Xpreprocessor -fopenmp -I/usr/local/include -DUSE_FBGEMM -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -faligned-new -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -isysroot /Applications/Xcode-9.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9 -fPIC   -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings -Wno-unknown-pragmas -Wno-missing-braces -std=gnu++11 -MD -MT caffe2/torch/CMakeFiles/torch.dir/csrc/jit/netdef_converter.cpp.o -MF caffe2/torch/CMakeFiles/torch.dir/csrc/jit/netdef_converter.cpp.o.d -o caffe2/torch/CMakeFiles/torch.dir/csrc/jit/netdef_converter.cpp.o -c ../torch/csrc/jit/netdef_converter.cpp
Feb 13 21:08:13 ../torch/csrc/jit/netdef_converter.cpp:51:29: error: no viable conversion from 'vector<long>' to 'vector<long long>'
Feb 13 21:08:13       node->is_(attrSymbol, is);
Feb 13 21:08:13                             ^~
Feb 13 21:08:13 /Applications/Xcode-9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:530:5: note: candidate constructor not viable: no known conversion from 'std::vector<long>' to 'initializer_list<value_type>' (aka 'initializer_list<long long>') for 1st argument
Feb 13 21:08:13     vector(initializer_list<value_type> __il);
Feb 13 21:08:13     ^
Feb 13 21:08:13 /Applications/Xcode-9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:542:5: note: candidate constructor not viable: no known conversion from 'std::vector<long>' to 'const std::__1::vector<long long, std::__1::allocator<long long> > &' for 1st argument
Feb 13 21:08:13     vector(const vector& __x);
Feb 13 21:08:13     ^
Feb 13 21:08:13 /Applications/Xcode-9.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:548:5: note: candidate constructor not viable: no known conversion from 'std::vector<long>' to 'std::__1::vector<long long, std::__1::allocator<long long> > &&' for 1st argument
Feb 13 21:08:13     vector(vector&& __x)
Feb 13 21:08:13     ^
Feb 13 21:08:13 ../torch/csrc/jit/ir.h:685:3: note: passing argument to parameter 'v' here
Feb 13 21:08:13   CREATE_ACCESSOR(Ints, is)
Feb 13 21:08:13   ^
Feb 13 21:08:13 ../torch/csrc/jit/ir.h:672:60: note: expanded from macro 'CREATE_ACCESSOR'
Feb 13 21:08:13   Node* method##_(Symbol name, Kind##Attr::ConstructorType v) { \
Feb 13 21:08:13                                                            ^
Feb 13 21:08:13 1 error generated.

**Review by yinghai — APPROVED** [review]
Thanks!

**Review by yinghai — CHANGES_REQUESTED** [review]
Could you rebase to master to flush out the errors?

**Comment by gujinghui** [comment]
@yinghai 
rebased. pls help review.

The failure is caused by timeout.

> Feb 17 14:14:46 [ RUN      ] DataLoaderTest.ChunkDataSetWithBatchSizeMismatch
Feb 17 14:14:46 [       OK ] DataLoaderTest.ChunkDataSetWithBatchSizeMismatch (8 ms)
Feb 17 14:14:46 [ RUN      ] DataLoaderTest.ChunkDataSetWithEmptyBatch
Too long with no output (exceeded 1h30m0s)

**Comment by gujinghui** [comment]
@yinghai 
pls help review it.

Thanks.

**Review by yinghai — APPROVED** [review]
LGTM. Please rebase again to resolve merge conflict.

**Comment by gujinghui** [comment]
@yinghai 
rebased. pls review.

**Comment by gujinghui** [comment]
@yinghai 
pls help review and merge. :)

**Pull request closed without merging**
