### PR TITLE
Support boolean key in dictionary

### LINKED ISSUE #41449: [jit] support boolean in dictionary
Currently jit does not support the case where boolean value is used as dict key:
```
class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.x = {True: 1}

model = MyModule()
model_s = torch.jit.script(model)
```
we will get:
```
RuntimeError: Cannot create dict for key type 'bool', only int, float, Tensor and string keys are supported
```
we must convert **boolean** to **int** as a workaround, but it will lose the semantic meanings of the key value and make the codes comfusing which may lead to a bad user experience.

cc @suo @gmagogsfm

### PR DESCRIPTION
**Pull request by asuhan**
Fixes #41449 .

### CODE REVIEW

**Review by gmagogsfm — APPROVED** [review]

**Comment by fra-luc** [comment]
@asuhan is this in pytorch 1.6? thanks!

**Comment by asuhan** [comment]
@fra-luc No, it's not.

**Comment by fra-luc** [comment]
@asuhan Thank you, will this be in 1.7?

**Comment by asuhan** [comment]
@fra-luc Yes, it will be.

**Pull request closed without merging**
