### PR TITLE
Allow unicode (char32_t) einsum equation characters

### PR DESCRIPTION
**Pull request by emprice**
Following a discussion [here](https://github.com/dgasmith/opt_einsum/issues/92), I thought having a wider character set available for `einsum` equations would be a nice feature for those of us doing quantum mechanics with PyTorch, where the number of indices in a tensor contraction can become quite large. In the master branch, one is limited to the character set `[a-z]`, but, with this PR, one can use a much wider character set, so long as it can be interpreted as a `char32_t`.

These edits do not appear to break the existing behavior with my simple test code, below. I am showing that, with the update, one can use Greek index symbols instead of just Latin letters.
```
import torch

x = torch.randn(2, 3, 4)
y = torch.randn(3, 4, 5)
ein1 = torch.einsum('abc,bcd->ad', x, y)
ein2 = torch.einsum('αβγ,βγδ->αδ', x, y)
assert (ein1 == ein2).all() 
```
However, I do not claim that this code is necessarily bulletproof. As this is my first time contributing, I welcome constructive criticism or more guidance on how to improve.

### CODE REVIEW

**Comment by soumith** [comment]
thanks a lot for what seems to be a great PR. I requested reviews from some relevant core devs.

**Comment by t-vi** [comment]
Thank you for the patch! It adds a much-desired feature.

But there are a few caveats:
- This extension is incompatible with (stable) numpy. Do we want that or is NumPy also getting unicode support? (The breakage is not subtle, but an exception, so it looks OK for me.)
- As far as I know, Python strings are [converted to UTF8 in C++](https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/python_strings.h#L35). This would suggest to me that the simplest (and possibly best) course of action might be keep einsum take strings and decode the UTF8 `std::string` to a `std::u32string`.
- Changing IValues has fairly wide-reaching implications for the JIT. I am sceptical that the patch would work as desired in the JIT interactions. (Don't feel bad about it, though, I remember when I first added strings for einsum and knew zero about the JIT and just tried to beat the (then much simpler) code with a hammer until it fit, it was absolutely scary and possibly much harder than einsum itself.)

**Comment by ezyang** [comment]
I like the functionality. I do not like the implementation. Agreeing with @t-vi, we should just teach the einsum parser to handle UTF-8. This does mean that we'll need a miniature UTF-8 decoder so we can at least figure out how many bytes make up an actual character--I can help review something like that. Additionally, the current implementation accepts ANYTHING with Unicode codepoint higher than 'A'... and that includes Unicode punctuation, which seems very questionable to me. Usually, you figure out what character class it is using a library like libicu. I'm not so sure we want to actually add a libicu dep to PyTorch. If you only want Greek letters you could just hardcode the codepoint range. (That might also simplify the decoder.)

**Review by ezyang — CHANGES_REQUESTED** [review]
Requesting different implementation strategy

**Comment by emprice** [comment]
@t-vi and @ezyang thanks for the feedback! I have a little time I can devote to making this better, but I could use some more detail on what is needed here.

I suppose my original philosophy in writing this code was to keep it as close as possible to what was already in the repo, hence mirroring the `std::string` functions with the `std::u32string` counterparts. I did think about alternative ways to approach this, including requesting [this library](https://github.com/ledger/utfcpp) as a possible dependency, but I wasn't sure about doing that on my first PR. I think writing a dedicated UTF-8 library just for PyTorch is a little out of my depth and out of the scope of the PR.

As a side note, Greek letters were just supposed to be a (readable) example. I am generating very complicated contractions using [`opt_einsum`](https://github.com/dgasmith/opt_einsum) and need > 26 letters; the letters are generated by just looping over the Unicode characters (I think), which inspired me to make this patch in the first place. An example of the full contraction I am attempting is [here](https://github.com/dgasmith/opt_einsum/issues/92), though it gets broken up into smaller contractions by `opt_einsum`.

@ezyang What alternative implementation strategy did you have in mind? While I've done a bit of digging into the code, I'm by no means an expert.

**Comment by t-vi** [comment]
If you're after better flexibility for *generated* contractions, I'd probably recommend to follow the [numpy API for this](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.einsum.html):
> In alternative way to provide the subscripts and operands is as einsum(op0, sublist0, op1, sublist1, ..., [sublistout]). The examples below have corresponding einsum calls with the two parameter methods.

**Comment by ezyang** [comment]
Hi @emprice, makes sense; I certainly would not recommend adding a large amount of utf-8 handling in your first PR :)

A very simple change which might help your use case is to accept capital letters (which are accepted by Numpy). That should be a one liner. Do you want to submit a PR for that first?

**Comment by veya2ztn** [comment]
To avoid change the type from `string` to `u32string`, my idea is transfer the 
`letter string` "...ab,...bc,...cd -> ...ad" to 
`number string` like "...<0><1>,...<1><2>,...<2><3> -> ...<0><3>".  

So that only need change 2 places. 
- aten/src/ATen/native/Linear.cpp.
  For example,  to identity the `label`, need an extra string buffer 
```
      case '<':
        num_string="";
        break;
      case '>':
        TORCH_CHECK(
            to_label(num_string)<TOTAL_LABELS,
            "einsum(): expected subscripts to be small than",TOTAL_LABELS,
            "but got ",num_string
          );
        op_labels.back().push_back(to_label(num_string));
        ++label_count[to_label(num_string)];
        break;
      default:
        num_string+=string(1,*it);
        break;
```
- torch/functional.py
   The newest pytorch support `sublist` as input, which is great. 
   Such supporting is realized by converting `sublist` to `letter string`, the limitation still in [a-zA-Z].
   However, if we use `number string` idea,   the limit is the size of unit8_t (255). 
  And we can do `alpha_canonicalize` like in https://github.com/dgasmith/opt_einsum/blob/master/opt_einsum/parser.py. 
So it is potential to support any letter include Greek
 (Unless the number of  used letters smaller than  255)

I do test this idea for pytorch-branch `heitorschueroff/einsum/optimize`. 
However, when test on contration which involed more than 64 tensors ,  it appear 
```
    return _VF.einsum(equation, operands, optimize=optimize)  # type: ignore[attr-defined]
RuntimeError: only tensors with up to 64 dims are supported
```
From my obersevation, the `Linear.cpp/einsum` will unsqueeze all input tensor to `# of label` dim.
So this error may not be avoided when `sublist` longer than 64. 
Is that true?

**Pull request closed without merging**
