### PR TITLE
Make all of new_/_like factory functions composite explicit autograd

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #82333
* #82332
* #82251
* #82311
* __->__ #82238

Once CompositeImplicitAutograd gets registered to Python key, this will
ensure that tensor subclasses can interpose on these functions directly
rather than getting decomposed.  We prefer not decomposing as these
functions are functional, but their implementations use inplace
operations (and are thus more difficult to deal with, unless you use
functionalization.)

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Review by albanD — DISMISSED** [review]
Not sure about this?
We explicitly made these such that all factory functions are CompositeImplicit except for the lowest level ones. For example all the *_like will decompose to empty_like (similar for new_ and others).
This was done on purpose to make backend implementations easier.
Do you actually want to change that?

I think doing this would break quite a few things no?

**Comment by ezyang** [comment]
Well, as you can see from the CI, it hasn't broken anything. To be clear, these are still *composite* registrations, so for non Python key backends, they still have the option of only implementing `empty_like` and getting everything for free.

So your question really is, "Will it break Python key backends if they have to implement each of the factory functions individually?" And the answer to that is, no, because it is *already* broken today (try it! You will see each of the versions of the factory functions show up individually). And the claim we are making in #81984 is that it is better to give them to the user before they are decomposed; and give the user the option to manually decompose the operation themselves if they so desire.

**Review by albanD — COMMENTED** [review]
Sounds good.
Is the plan for this to move the "autograd implementation" for these from the python binding and into the Autograd key as well?

**Comment by ezyang** [comment]
> Is the plan for this to move the "autograd implementation" for these from the python binding and into the Autograd key as well?

I don't think that's so easy to do? Because of the `requires_grad` bool special casing.

**Review by bdhirsh — APPROVED** [review]

**Pull request closed without merging**
