### PR TITLE
Fix linter warning: replace f-strings with str.format for Py2 compat

### PR DESCRIPTION
**Pull request by drdarshan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#35492 Fix linter warning: replace f-strings with str.format for Py2 compat**

Differential Revision: [D20998727](https://our.internmc.facebook.com/intern/diff/D20998727)

### CODE REVIEW

**Comment by drdarshan** [comment]
Hello @mrshenli - sorry I must have done something wrong with the squash. If this final version looks good I will abandon the other PRs.

**Review by mrshenli — APPROVED** [review]
Looks great! Thanks for fixing! :)

**Comment by mrshenli** [comment]
@drdarshan let's wait for all tests to make sure no failures are relevant this change before landing. Thanks!

**Comment by drdarshan** [comment]
> @drdarshan let's wait for all tests to make sure no failures are relevant this change before landing. Thanks!

Hello @mrshenli - looks like the failures in Jenkins are unrelated to this PR. Is it safe to merge? Thank you!

**Comment by mrshenli** [comment]
Hey @drdarshan, yes, failures are irrelevant. Let's land.

**Pull request closed without merging**
