### PR TITLE
add BFloat16 support for UpSample on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74410
* #69067
* #73953
* #73845
* #73844
* #71376
* __->__ #58297

Differential Revision: [D28836788](https://our.internmc.facebook.com/intern/diff/D28836788)

### CODE REVIEW

**Comment by mingfeima** [comment]
TODO:
- [ ] specialize channels last linear forward path of BFloat16, use float as acc type;

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836788).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836788).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836788).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836788).

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836788).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836788).

**Comment by VitalyFedyunin** [comment]
Could you please rebase (retriggering tests)

**Comment by mingfeima** [comment]
working on the CI failure.

**Comment by VitalyFedyunin** [comment]
rocm test failures seems to be related to upsampling

**Comment by mingfeima** [comment]
@VitalyFedyunin , the CI failure is cleared, please help review!

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836788).

**Comment by mingfeima** [comment]
This stack has been rebased recently!

**Comment by mingfeima** [comment]
This stack has been rebased recently! Please help review~

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836788).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836788).

**Comment by malfet** [comment]
Reverting, as this change depends on now unavailable `dtypesIfCPU`, see https://hud.pytorch.org/pytorch/pytorch/commit/1399d83bc09d9396afc169e6c134fa3bddd6faa5

Please rebase and try landing it again

**Comment by mingfeima** [comment]
> Reverting, as this change depends on now unavailable `dtypesIfCPU`, see https://hud.pytorch.org/pytorch/pytorch/commit/1399d83bc09d9396afc169e6c134fa3bddd6faa5
> 
> Please rebase and try landing it again

@malfet Thanks for the remainder! Re-submit this one at #76935. `dtypesIfCPU` is removed.

**Pull request closed without merging**
