### PR TITLE
Back out "[pytorch][PR] Optimization of the Embedding and Embedding-Bag CUDA Kernel"

### PR DESCRIPTION
**Pull request by chenyangyu1988**
Summary:
Original commit changeset: 398d5f48826a

f123389994, P68573646
During FP16 training, we found char_embeddings.weight get NAN or INF grads

Differential Revision: D16067446

### CODE REVIEW

**Comment by mrshenli** [comment]
CC @madsbk

Looks like #22016 sometimes leads NAN or INF in embedding grads for FP16 training. @chenyangyu1988 Could you please share some context here?

**Comment by ngimel** [comment]
It's possible that truncating `grad_weight_per_segment` to fp16 is causing this.

**Comment by madsbk** [comment]
@ngimel, yes that could be the problem and easy fixable. I will look at it tomorrow.

@chenyangyu1988, do we have an example code that triggers the error?

**Comment by chenyangyu1988** [comment]
@madsbk I don't have a OSS example here, but if you have a FP16 training example, you could check the loss_scale after 1k iterations, it is correct if the loss_scale is much larger than 1. In our case, we still get NAN or INF in the embedding layer grad even loss_scale is some 2.2e-16

**Comment by chenyangyu1988** [comment]
Do we have a target time for this, it is currently block our training. Or could we revert first?

**Comment by ngimel** [comment]
Yes, it should be reverted, #22016 has other problems that need to be fixed first.

**Comment by chenyangyu1988** [comment]
@mrshenli so let's revert it for now?

**Comment by madsbk** [comment]
@chenyangyu1988, can I get you to test #22401?

**Comment by chenyangyu1988** [comment]
@madsbk There are 3 commits in #22401, should I patch all of them?

**Comment by madsbk** [comment]
> @madsbk There are 3 commits in #22401, should I patch all of them?

Yes

**Comment by jbschlosser** [comment]
Closing as out-of-date; feel free to reopen if still relevant.

**Pull request closed without merging**
