### PR TITLE
[aarch64] Fix libcusparselt format for CUDA sbsa docker

### PR DESCRIPTION
**Pull request by tinglvv**
Corrects https://github.com/pytorch/pytorch/pull/141433/

Error whe building arm wheel https://github.com/pytorch/pytorch/actions/runs/12226514901/job/34101913511
`/opt/rh/gcc-toolset-11/root/usr/bin/ld: /usr/local/cuda/lib64/libcusparseLt.so: error adding symbols: file in wrong format`

cc @ptrblck @msaroufim @eqy @malfet @snadampal @milpuz01 @atalman @Skylion007 @nWEIdia

### CODE REVIEW

**Review by Aidyn-A — APPROVED** [review]
Checked locally, the paths are correct.

**Comment by Aidyn-A** [comment]
The build was able to find and link against cuSPARSELt https://github.com/pytorch/pytorch/actions/runs/12234159744/ :

```
2024-12-09T11:15:38.3817946Z -- Found CUSPARSELT: /usr/local/cuda/lib64/libcusparseLt.so
...
2024-12-09T11:16:13.5670543Z --     cuDNN version       : 9.1.0
2024-12-09T11:16:13.5670848Z --     cuSPARSELt version  : 0.6.2
...
2024-12-09T11:16:13.5674757Z --     cuSPARSELt library  : /usr/local/cuda/lib64/libcusparseLt.so
```

**Review by Skylion007 — APPROVED** [review]
Whoops my bad on the copy paste error

**Review by atalman — APPROVED** [review]
lgtm

**Pull request closed without merging**
