### PR TITLE
update sphinx to 3.5.1

### PR DESCRIPTION
**Pull request by mattip**
Related to  #8817

Sphinx is pinned to 2.4.4. Update it to ~3.4.3~, 3.5.1 the latest release.

### CODE REVIEW

**Comment by mattip** [comment]
There are lots of warnings that fail the docs build. Most of them are `WARNING: duplicate object description of ...`, there are also some `Failed to get a method signature for...`



<details>

```
Feb 05 08:01:29 =========================
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.any:23: WARNING: duplicate object description of torch.any, other instance in generated/torch.any, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.argmax:22: WARNING: duplicate object description of torch.argmax, other instance in generated/torch.argmax, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.clamp:26: WARNING: duplicate object description of torch.clamp, other instance in generated/torch.clamp, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.clamp:46: WARNING: duplicate object description of torch.clamp, other instance in generated/torch.clamp, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.dequantize:6: WARNING: duplicate object description of torch.dequantize, other instance in generated/torch.dequantize, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.std:19: WARNING: duplicate object description of torch.std, other instance in generated/torch.std, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.std_mean:19: WARNING: duplicate object description of torch.std_mean, other instance in generated/torch.std_mean, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.sum:19: WARNING: duplicate object description of torch.sum, other instance in generated/torch.sum, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.trapz:28: WARNING: duplicate object description of torch.trapz, other instance in generated/torch.trapz, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.repeat_interleave:36: WARNING: duplicate object description of torch.repeat_interleave, other instance in generated/torch.repeat_interleave, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.normal:32: WARNING: duplicate object description of torch.normal, other instance in generated/torch.normal, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.normal:50: WARNING: duplicate object description of torch.normal, other instance in generated/torch.normal, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.normal:68: WARNING: duplicate object description of torch.normal, other instance in generated/torch.normal, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.pow:45: WARNING: duplicate object description of torch.pow, other instance in generated/torch.pow, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.prod:19: WARNING: duplicate object description of torch.prod, other instance in generated/torch.prod, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.quantile:18: WARNING: duplicate object description of torch.quantile, other instance in generated/torch.quantile, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/nn/modules/flatten.py:docstring of torch.nn.modules.module.Module.to:5: WARNING: duplicate object description of torch.nn.Unflatten.to, other instance in generated/torch.nn.Unflatten, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/nn/modules/flatten.py:docstring of torch.nn.modules.module.Module.to:7: WARNING: duplicate object description of torch.nn.Unflatten.to, other instance in generated/torch.nn.Unflatten, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/nn/modules/flatten.py:docstring of torch.nn.modules.module.Module.to:9: WARNING: duplicate object description of torch.nn.Unflatten.to, other instance in generated/torch.nn.Unflatten, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/nn/modules/flatten.py:docstring of torch.nn.modules.module.Module.to:11: WARNING: duplicate object description of torch.nn.Unflatten.to, other instance in generated/torch.nn.Unflatten, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.var:20: WARNING: duplicate object description of torch.var, other instance in generated/torch.var, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.var_mean:19: WARNING: duplicate object description of torch.var_mean, other instance in generated/torch.var_mean, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.where:52: WARNING: duplicate object description of torch.where, other instance in generated/torch.where, use :noindex: for one of them
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.bernoulli.Bernoulli.logits: <torch.distributions.utils.lazy_property object at 0x7f5db724a400> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.bernoulli.Bernoulli.probs: <torch.distributions.utils.lazy_property object at 0x7f5db724a470> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.binomial.Binomial.logits: <torch.distributions.utils.lazy_property object at 0x7f5db726ecc0> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.binomial.Binomial.probs: <torch.distributions.utils.lazy_property object at 0x7f5db726ed30> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.categorical.Categorical.logits: <torch.distributions.utils.lazy_property object at 0x7f5db7276438> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.categorical.Categorical.probs: <torch.distributions.utils.lazy_property object at 0x7f5db72764a8> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.continuous_bernoulli.ContinuousBernoulli.logits: <torch.distributions.utils.lazy_property object at 0x7f5db7219f60> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.continuous_bernoulli.ContinuousBernoulli.probs: <torch.distributions.utils.lazy_property object at 0x7f5db7219f98> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.geometric.Geometric.logits: <torch.distributions.utils.lazy_property object at 0x7f5db7236198> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.geometric.Geometric.probs: <torch.distributions.utils.lazy_property object at 0x7f5db72361d0> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.lowrank_multivariate_normal.LowRankMultivariateNormal.covariance_matrix: <torch.distributions.utils.lazy_property object at 0x7f5db71d9fd0> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.lowrank_multivariate_normal.LowRankMultivariateNormal.precision_matrix: <torch.distributions.utils.lazy_property object at 0x7f5db71e3048> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.lowrank_multivariate_normal.LowRankMultivariateNormal.scale_tril: <torch.distributions.utils.lazy_property object at 0x7f5db71d9e10> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.lowrank_multivariate_normal.LowRankMultivariateNormal.variance: <torch.distributions.utils.lazy_property object at 0x7f5db71d97b8> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.multivariate_normal.MultivariateNormal.covariance_matrix: <torch.distributions.utils.lazy_property object at 0x7f5db71d9f28> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.multivariate_normal.MultivariateNormal.precision_matrix: <torch.distributions.utils.lazy_property object at 0x7f5db71d9f98> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.multivariate_normal.MultivariateNormal.scale_tril: <torch.distributions.utils.lazy_property object at 0x7f5db71d9ef0> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.negative_binomial.NegativeBinomial.logits: <torch.distributions.utils.lazy_property object at 0x7f5db717bcc0> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.negative_binomial.NegativeBinomial.probs: <torch.distributions.utils.lazy_property object at 0x7f5db717bcf8> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.relaxed_bernoulli.LogitRelaxedBernoulli.logits: <torch.distributions.utils.lazy_property object at 0x7f5db7183550> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.relaxed_bernoulli.LogitRelaxedBernoulli.probs: <torch.distributions.utils.lazy_property object at 0x7f5db7183588> is not a callable object
Feb 05 08:01:29 WARNING: Failed to get a method signature for torch.distributions.von_mises.VonMises.variance: <torch.distributions.utils.lazy_property object at 0x7f5db71895c0> is not a callable object
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.add:26: WARNING: duplicate object description of torch.add, other instance in generated/torch.add, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.all:20: WARNING: duplicate object description of torch.all, other instance in generated/torch.all, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py:docstring of torch.nn.modules.module.Module.to:5: WARNING: duplicate object description of torch.nn.Module.to, other instance in generated/torch.nn.Module, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py:docstring of torch.nn.modules.module.Module.to:7: WARNING: duplicate object description of torch.nn.Module.to, other instance in generated/torch.nn.Module, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py:docstring of torch.nn.modules.module.Module.to:9: WARNING: duplicate object description of torch.nn.Module.to, other instance in generated/torch.nn.Module, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py:docstring of torch.nn.modules.module.Module.to:11: WARNING: duplicate object description of torch.nn.Module.to, other instance in generated/torch.nn.Module, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.max:17: WARNING: duplicate object description of torch.max, other instance in generated/torch.max, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.max:53: WARNING: duplicate object description of torch.max, other instance in generated/torch.max, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.mean:14: WARNING: duplicate object description of torch.mean, other instance in generated/torch.mean, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.median:22: WARNING: duplicate object description of torch.median, other instance in generated/torch.median, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.min:17: WARNING: duplicate object description of torch.min, other instance in generated/torch.min, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.min:53: WARNING: duplicate object description of torch.min, other instance in generated/torch.min, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.mul:24: WARNING: duplicate object description of torch.mul, other instance in generated/torch.mul, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.nanmedian:19: WARNING: duplicate object description of torch.nanmedian, other instance in generated/torch.nanmedian, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.nansum:17: WARNING: duplicate object description of torch.nansum, other instance in generated/torch.nansum, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/nn/modules/flatten.py:docstring of torch.nn.modules.module.Module.to:5: WARNING: duplicate object description of torch.nn.Flatten.to, other instance in generated/torch.nn.Flatten, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/nn/modules/flatten.py:docstring of torch.nn.modules.module.Module.to:7: WARNING: duplicate object description of torch.nn.Flatten.to, other instance in generated/torch.nn.Flatten, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/nn/modules/flatten.py:docstring of torch.nn.modules.module.Module.to:9: WARNING: duplicate object description of torch.nn.Flatten.to, other instance in generated/torch.nn.Flatten, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/nn/modules/flatten.py:docstring of torch.nn.modules.module.Module.to:11: WARNING: duplicate object description of torch.nn.Flatten.to, other instance in generated/torch.nn.Flatten, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.Tensor.bernoulli_:1: WARNING: duplicate object description of torch.Tensor.bernoulli_, other instance in tensors, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.Tensor.bernoulli_:7: WARNING: duplicate object description of torch.Tensor.bernoulli_, other instance in tensors, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.Tensor.to:13: WARNING: duplicate object description of torch.Tensor.to, other instance in tensors, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.Tensor.to:21: WARNING: duplicate object description of torch.Tensor.to, other instance in tensors, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.Tensor.to:35: WARNING: duplicate object description of torch.Tensor.to, other instance in tensors, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/__init__.py:docstring of torch.Tensor.view:49: WARNING: duplicate object description of torch.Tensor.view, other instance in tensors, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/jit/_script.py:docstring of torch.nn.modules.module.Module.to:5: WARNING: duplicate object description of torch.jit.ScriptModule.to, other instance in generated/torch.jit.ScriptModule, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/jit/_script.py:docstring of torch.nn.modules.module.Module.to:7: WARNING: duplicate object description of torch.jit.ScriptModule.to, other instance in generated/torch.jit.ScriptModule, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/jit/_script.py:docstring of torch.nn.modules.module.Module.to:9: WARNING: duplicate object description of torch.jit.ScriptModule.to, other instance in generated/torch.jit.ScriptModule, use :noindex: for one of them
Feb 05 08:01:29 /opt/conda/lib/python3.6/site-packages/torch/jit/_script.py:docstring of torch.nn.modules.module.Module.to:11: WARNING: duplicate object description of torch.jit.ScriptModule.to, other instance in generated/torch.jit.ScriptModule, use :noindex: for one of them
Feb 05 08:01:29 =========================
```

**Comment by brianjo** [comment]
@mattip Do you know why that's failing the doc tests.

**Comment by mattip** [comment]
@brianjo: I think it is sphinx being more picky about weird documentation [sections like these](https://github.com/pytorch/pytorch/blob/master/torch/_torch_docs.py#L1913), which repeat the torch.clamp docstring (twice!)

**Comment by mattip** [comment]
Closing in favor of #61601

**Pull request closed without merging**
