### PR TITLE
[Submodule] Remove glog dependency

### PR DESCRIPTION
**Pull request by cyyever**
There is no reason to keep two logging systems now.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @peterbell10

### CODE REVIEW

**Comment by ezyang** [comment]
I need to check because I think internally we use the glog integration

**Comment by cyyever** [comment]
Our immigration works well and removing glog can reduce maintenance burden and installation issues.

**Comment by ezyang** [comment]
the import keeps failing 🤔

**Comment by cyyever** [comment]
> the import keeps failing 🤔

What are the possible reasons?  I can't see the log because not in meta.

**Comment by ezyang** [comment]
There is some sort of conflict on c2_defs.bzl

**Comment by ezyang** [comment]
manually imported diff https://www.internalfb.com/diff/D58204156

**Comment by malfet** [comment]
cc: @kiukchung I remember you were talking something about G3 using/not-using glog internally

**Comment by ezyang** [comment]
Yes, everything broke internally. Stuff like

```
In file included from fbcode/caffe2/caffe2/core/logging.h:2:
In file included from fbcode/caffe2/c10/util/Logging.h:25:
fbcode/caffe2/c10/util/logging_is_not_google_glog.h:92:9: error: 'LOG' macro redefined [-Werror,-Wmacro-redefined]
#define LOG(n)                                 \
        ^
buck-out/v2/gen/fbcode/fbee18c42329445d/third-party-buck/platform010/build/glog/__glog__/buck-headers/glog/logging.h:564:9: note: previous definition is here
#define LOG(severity) COMPACT_GOOGLE_LOG_ ## severity.stream()
        ^
```

**Comment by cyyever** [comment]
> LOG

Should remove glog from the internal BUCK build system?

**Comment by ezyang** [comment]
Well, in fbcode, we want to use glog to actually do logging, since that's the standard logger we're using internally. So, uh.... no?

**Comment by cyyever** [comment]
> Well, in fbcode, we want to use glog to actually do logging, since that's the standard logger we're using internally. So, uh.... no?

I see, so the better way is to rename LOG macros in PyTorch to avoid conflicts?

**Comment by ezyang** [comment]
now errors like

```
fbcode/caffe2/caffe2/utils/math-detail.h:33:5: error: use of undeclared identifier 'TORCH_DCHECK_EQ'
    TORCH_DCHECK_EQ(N, 1);
    ^
fbcode/caffe2/caffe2/utils/math-detail.h:59:5: error: use of undeclared identifier 'TORCH_DCHECK_EQ'
    TORCH_DCHECK_EQ(N, 1);
    ^
```

**Comment by cyyever** [comment]
> now errors like
> 
> ```
> fbcode/caffe2/caffe2/utils/math-detail.h:33:5: error: use of undeclared identifier 'TORCH_DCHECK_EQ'
>     TORCH_DCHECK_EQ(N, 1);
>     ^
> fbcode/caffe2/caffe2/utils/math-detail.h:59:5: error: use of undeclared identifier 'TORCH_DCHECK_EQ'
>     TORCH_DCHECK_EQ(N, 1);
>     ^
> ```

It's better to restore glog macros and use FBCODE_CAFFE2 to control META builds.

**Comment by cyyever** [comment]
@ezyang Can merge?

**Comment by ezyang** [comment]
```
Actions failed:
    Action failed with a user error. See Workflow UI for full details. Failure message: exception 'SandcastleUserException' with message 'xplat/caffe2/c10/util/logging_is_not_google_glog.h:92:9: error: 'LOG' macro redefined [-Werror,-Wmacro-redefined]
   92 | #define LOG(n)                                 \
      |         ^
xplat/caffe2/c10/util/logging_is_not_google_glog.h:95:9: error: 'VLOG' macro redefined [-Werror,-Wmacro-redefined]
   95 | #define VLOG(n)                   \
      |         ^
xplat/caffe2/c10/util/logging_is_not_google_glog.h:99:9: error: 'LOG_IF' macro redefined [-Werror,-Wmacro-redefined]
   99 | #define LOG_IF(n, condition)                                  \
      |         ^
xplat/caffe2/c10/util/logging_is_not_google_glog.h:102:9: error: 'VLOG_IF' macro redefined [-Werror,-Wmacro-redefined]
  102 | #define VLOG_IF(n, condition)                    \
      |         ^
xplat/caffe2/c10/util/logging_is_not_google_glog.h:106:9: error: 'VLOG_IS_ON' macro redefined [-Werror,-Wmacro-redefined]
  106 | #define VLOG_IS_ON(verboselevel) (CAFFE2_LOG_THRESHOLD <= -(verboselevel))
      |         ^
xplat/caffe2/c10/util/logging_is_not_google_glog.h:121:9: error: 'CHECK' macro redefined [-Werror,-Wmacro-redefined]
  121 | #define CHECK(condition) FATAL_IF(condition) << "Check failed: " #condition " "
      |         ^
xplat/caffe2/c10/util/logging_is_not_google_glog.h:129:9: error: 'DCHECK' macro redefined [-Werror,-Wmacro-redefined]
  129 | #define DCHECK(condition) \
      |         ^
xplat/caffe2/c10/util/logging_is_not_google_glog.h:133:9: error: 'DLOG' macro redefined [-Werror,-Wmacro-redefined]
  133 | #define DLOG(n)                   \
      |         ^
xplat/caffe2/c10/util/logging_is_not_google_glog.h:92:9: error: 'LOG' macro redefined [-Werror,-Wmacro-redefined]
   92 | #define LOG(n)                                 \
      |         ^
```

**Comment by ezyang** [comment]
```
2024-08-21 12:02:23,408 [PID 4262] ERROR    ...
2024-08-21 12:02:23,408 [PID 4262] ERROR          |                      ^
2024-08-21 12:02:23,408 [PID 4262] ERROR    fbcode/caffe2/c10/util/Logging.cpp:298:30: error: use of undeclared identifier 'GLOG_FATAL'; did you mean 'google::GLOG_FATAL'?
2024-08-21 12:02:23,408 [PID 4262] ERROR      298 |     FLAGS_caffe2_log_level = GLOG_FATAL;
2024-08-21 12:02:23,408 [PID 4262] ERROR          |                              ^~~~~~~~~~
2024-08-21 12:02:23,408 [PID 4262] ERROR          |                              google::GLOG_FATAL
2024-08-21 12:02:23,408 [PID 4262] ERROR    buck-out/v2/gen/fbcode/0686d4de00a72e66/third-party-buck/platform010/build/glog/__glog__/buck-headers/glog/log_severity.h:52:22: note: 'google::GLOG_FATAL' declared here
2024-08-21 12:02:23,408 [PID 4262] ERROR       52 |   GLOG_CRITICAL = 4, GLOG_FATAL = 5, GLOG_SHUTDOWN = 6, NUM_SEVERITIES = 7;
2024-08-21 12:02:23,409 [PID 4262] ERROR          |                      ^
2024-08-21 12:02:23,409 [PID 4262] ERROR    fbcode/caffe2/c10/util/Logging.cpp:306:28: error: use of undeclared identifier 'GLOG_INFO'; did you mean 'google::GLOG_INFO'?
2024-08-21 12:02:23,409 [PID 4262] ERROR      306 |   FLAGS_caffe2_log_level = GLOG_INFO;
2024-08-21 12:02:23,409 [PID 4262] ERROR          |                            ^~~~~~~~~
2024-08-21 12:02:23,409 [PID 4262] ERROR          |                            google::GLOG_INFO
```

**Comment by ezyang** [comment]
From my last import, error is

```
In file included from arvr/libraries/neural_net_inference/Caffe2/NNCaffe2Backend.cpp:30:
In file included from xplat/caffe2/caffe2/core/init.h:6:
In file included from xplat/caffe2/caffe2/core/logging.h:2:
xplat/caffe2/c10/util/Logging.h:60:15: error: redefinition of 'MessageLogger'
class C10_API MessageLogger {
              ^
xplat/caffe2/c10/util/logging_is_not_google_glog.h:29:15: note: previous definition is here
class C10_API MessageLogger {
              ^
1 error generated.
```

**Comment by ppwwyyxx** [comment]
Non-glog version has a missing functionality: https://github.com/pytorch/pytorch/issues/135135

**Comment by ezyang** [comment]
latest import has errors like

```
Stderr:
clang-15: warning: argument unused during compilation: '-nostdinc++' [-Wunused-command-line-argument]
ld.lld: error: duplicate symbol: fLI::FLAGS_v
>>> defined at Logging.cpp
>>>            __objects__/Logging.cpp.o:(fLI::FLAGS_v) in archive buck-out/v2/gen/fbcode/d0f37af3a4633fe0/caffe2/c10/util/__base__/libbase.a
>>> defined at logging.h:347 (src/glog/logging.h:347)
>>>            libglog_la-vlog_is_on.o:(.bss+0x8) in archive fbcode/third-party-buck/platform010/build/glog/lib/libglog.a

ld.lld: error: duplicate symbol: fLI::FLAGS_minloglevel
>>> defined at Logging.cpp
>>>            __objects__/Logging.cpp.o:(fLI::FLAGS_minloglevel) in archive buck-out/v2/gen/fbcode/d0f37af3a4633fe0/caffe2/c10/util/__base__/libbase.a
>>> defined at logging.h:337 (src/glog/logging.h:337)
>>>            libglog_la-logging.o:(.bss+0x2D4) in archive fbcode/third-party-buck/platform010/build/glog/lib/libglog.a

ld.lld: error: duplicate symbol: fLB::FLAGS_logtostderr
>>> defined at Logging.cpp
>>>            __objects__/Logging.cpp.o:(fLB::FLAGS_logtostderr) in archive buck-out/v2/gen/fbcode/d0f37af3a4633fe0/caffe2/c10/util/__base__/libbase.a
>>> defined at logging.h:316 (src/glog/logging.h:316)
>>>            libglog_la-logging.o:(.bss+0x2F2) in archive fbcode/third-party-buck/platform010/build/glog/lib/libglog.a
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

I think it's incredibly unlikely you'll be able to remote control this into passing, unless you slavishly follow whatever the old code was doing.

**Pull request closed without merging**
