### PR TITLE
Fix for addcdiv contiguous problem

### PR DESCRIPTION
**Pull request by jhavukainen**
Fixes issue number #118115

### CODE REVIEW

**Review by kulinseth — APPROVED** [review]
Please add a test case.

**Review by malfet — APPROVED** [review]
Hmm, actually, this would not fix it for all use-cases would it?

**Review by malfet — CHANGES_REQUESTED** [review]
Can you add a better explanation on how it supposed to work? 
As far as I understand the current code, you fixed it for transposed tensor when all arguments are transposed, but you never check that tensor1 or tensor2 have the same layout as self, aren't you? So If I modify testcase a bit it will still generate wrong results, wouldn't it?

**Comment by jhavukainen** [comment]
> Can you add a better explanation on how it supposed to work? As far as I understand the current code, you fixed it for transposed tensor when all arguments are transposed, but you never check that tensor1 or tensor2 have the same layout as self, aren't you? So If I modify testcase a bit it will still generate wrong results, wouldn't it?

@malfet: You're absolutely right that was a mistake in the code due to my oversight. I added tests for specifically checking if only some of the tensors are transposed and handling of each input and the output individually to get them pass. Thanks for the diligence in the review to help catch the issue.

**Pull request closed without merging**
