### PR TITLE
[DONOTMERGE][ROCm]Test MI210 CI Nodes

### PR DESCRIPTION
**Pull request by amdfaa**
Fixes #ISSUE_NUMBER

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
Timeout in https://github.com/pytorch/pytorch/actions/runs/6502934521/job/17663115456 seems to have been a transient issue in CI which is not being seen on HUD now, so rebasing.

@pytorchbot rebase

**Comment by jithunnair-amd** [comment]
CI runs for commit https://github.com/pytorch/pytorch/commit/72ac4a01f29e190becd280c11a2c2c8738e76912 at: https://hud.pytorch.org/commit/72ac4a01f29e190becd280c11a2c2c8738e76912

**Comment by jeffdaily** [comment]
MI210 nodes are added to CI pool.  No longer need this PR for testing purposes.

**Pull request closed without merging**
