### PR TITLE
Add mem_eff_attention

### PR DESCRIPTION
**Pull request by cpuhrsch**
Summary: Importing xFormers fused attention kernel

Test Plan: Unit tests

Reviewed By: mikekgfb

Differential Revision: D39590955

### CODE REVIEW

**Comment by vadimkantorov** [comment]
is it similar to flash attention kernels?

**Review by drisspg — APPROVED** [review]

**Comment by fmassa** [comment]
@vadimkantorov it's a different implementation that follows a similar spirit of the flashattention implementation.

See https://github.com/facebookresearch/xformers/pull/362 and all the other PRs that follows for latest optimizations

**Comment by cpuhrsch** [comment]
Resolved by https://github.com/pytorch/pytorch/pull/85017

**Comment by chrjxj** [comment]
> @vadimkantorov it's a different implementation that follows a similar spirit of the flashattention implementation.
> 
> See [facebookresearch/xformers#362](https://github.com/facebookresearch/xformers/pull/362) and all the other PRs that follows for latest optimizations
w/o reading thru changes.. is this a replacement for previous attention kernel or will be exposed as a separate layer/op?

**Pull request closed without merging**
