### PR TITLE
Make it clearer that current selective AC is PT2-only and private

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #115081

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!
FYI @yf225

**Comment by wanchaol** [comment]
hmm why we rename this to sth with `_pt2_` prefix? the selective AC works in eager mode too. cc @yf225

**Pull request closed without merging**
