### PR TITLE
Partial revert of #38144 to fix ROCm CI.

### PR DESCRIPTION
**Pull request by jeffdaily**
CC @ezyang @xw285cornell

### CODE REVIEW

**Comment by jeffdaily** [comment]
Is the one cuda CI failure transient?

```
May 13 00:54:46 unknown file: Failure
May 13 00:54:46 C++ exception with description "v >= 0 && v < 1 INTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/test/cpp/tensorexpr/test_cuda.cpp":268, please report a bug to PyTorch. invalid value: 1010, 1
May 13 00:54:46 Exception raised from testCudaTestRand01 at /var/lib/jenkins/workspace/test/cpp/tensorexpr/test_cuda.cpp:268 (most recent call first):
May 13 00:54:46 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7feda074b1ab in /var/lib/jenkins/workspace/build/lib/libc10.so)
May 13 00:54:46 frame #1: torch::jit::testCudaTestRand01() + 0x857 (0x4925f7 in build/bin/test_tensorexpr)
May 13 00:54:46 frame #2: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 0x4a (0x60676a in build/bin/test_tensorexpr)
May 13 00:54:46 frame #3: build/bin/test_tensorexpr() [0x5fc486]
May 13 00:54:46 frame #4: build/bin/test_tensorexpr() [0x5fca75]
May 13 00:54:46 frame #5: build/bin/test_tensorexpr() [0x5fcd15]
May 13 00:54:46 frame #6: testing::internal::UnitTestImpl::RunAllTests() + 0xbf9 (0x5fdd59 in build/bin/test_tensorexpr)
May 13 00:54:46 frame #7: testing::UnitTest::Run() + 0x8f (0x5fdfff in build/bin/test_tensorexpr)
May 13 00:54:46 frame #8: main + 0xc8 (0x46f728 in build/bin/test_tensorexpr)
May 13 00:54:46 frame #9: __libc_start_main + 0xf0 (0x7feda005e830 in /lib/x86_64-linux-gnu/libc.so.6)
May 13 00:54:46 frame #10: _start + 0x29 (0x480919 in build/bin/test_tensorexpr)
May 13 00:54:46 " thrown in the test body.
May 13 00:54:46 [  FAILED  ] TensorExprTest.CudaTestRand01_CUDA (122 ms)
```

**Comment by zasdfgbnm** [comment]
@jeffdaily It doesn't look related to me.

**Comment by ezyang** [comment]
```
01:09:07 ======================================================================
01:09:07 FAIL: test_activations_bfloat16_cuda (__main__.TestNNDeviceTypeCUDA)
01:09:07 ----------------------------------------------------------------------
01:09:07 Traceback (most recent call last):
01:09:07   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 743, in wrapper
01:09:07     method(*args, **kwargs)
01:09:07   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 210, in instantiated_test
01:09:07     return test(self, device_arg)
01:09:07   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 465, in only_fn
01:09:07     return fn(slf, device, *args, **kwargs)
01:09:07   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 404, in dep_fn
01:09:07     return fn(slf, device, *args, **kwargs)
01:09:07   File "test_nn.py", line 11063, in test_activations_bfloat16
01:09:07     self._test_bfloat16_ops(torch.nn.ReLU(), device, inp_dims=(5), prec=1e-2)
01:09:07   File "test_nn.py", line 11057, in _test_bfloat16_ops
01:09:07     self.assertEqual(out1, out2, atol=prec)
01:09:07   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 979, in assertEqual
01:09:07     assertTensorsEqual(x, y)
01:09:07   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 914, in assertTensorsEqual
01:09:07     self.assertEqual(a.dtype, b.dtype)
01:09:07   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1012, in assertEqual
01:09:07     super().assertEqual(x, y, message)
01:09:07 AssertionError: torch.float32 != torch.bfloat16 : 
01:09:07 
```

but I suppose this can be fixed in follow up

**Review by ezyang — APPROVED** [review]

**Comment by jeffdaily** [comment]
bfloat16 errors will be fixed in follow up PR.  Author has been notified @rohithkrn

**Pull request closed without merging**
