### PR TITLE
[package] merge test_torchscript into test_package_script

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #61807
* #61805
* #61806

These shouldn't be separate files, they test the same thing

Differential Revision: [D29748967](https://our.internmc.facebook.com/intern/diff/D29748967)

### CODE REVIEW

**Comment by suo** [comment]
@suo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29748967).

**Comment by suo** [comment]
@suo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29748967).

**Review by lobstergrindset — APPROVED** [review]
Woot better engineering at its finest 🚀

**Comment by suo** [comment]
@suo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29748967).

**Pull request closed without merging**
