### PR TITLE
[TorchTidy] Adding testing for size and dtype capture

### PR DESCRIPTION
**Pull request by Gamrix**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #81155
* __->__ #80071

Differential Revision: [D37571571](https://our.internmc.facebook.com/intern/diff/D37571571)

### CODE REVIEW

**Review by robieta — APPROVED** [review]
LGTM.

**Comment by Gamrix** [comment]
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37571571).

**Comment by Gamrix** [comment]
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37571571).

**Pull request closed without merging**
