### PR TITLE
Use TORCH_DECLARE_XXX

### PR DESCRIPTION
**Pull request by cyyever**
Because those files use TORCH_API

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

### CODE REVIEW

**Review by ezyang — CHANGES_REQUESTED** [review]
No I don't really understand the point of this change. Why isn't this just a macro that is from C10 library

**Comment by cyyever** [comment]
@ezyang C10_DECLARE_XXX use C10_API, which makes sense only in libc10.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
