### PR TITLE
Fix get_default_qat_qconfig for PT 1.13

### PR DESCRIPTION
**Pull request by peterjc123**
See https://github.com/pytorch/pytorch/pull/84329/files#r1019916766 for more context

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
Add tests to avoid such issues in the future?

**Comment by peterjc123** [comment]
@jgong5 I'm glad to add a test but I don't see where to put them.

**Comment by jerryzh168** [comment]
you can add tests here: https://github.com/pytorch/pytorch/blob/master/test/quantization/core/test_top_level_apis.py as a separate TestCase like TestQConfig or something I think, this feels like a big problem, but probably we are not using version == 0 since version defaults to 1 so it's doesn't have much impact

**Comment by peterjc123** [comment]
@jerryzh168 @jgong5 Test added.

**Review by jgong5 — APPROVED** [review]

**Review by vkuzo — APPROVED** [review]

**Pull request closed without merging**
