### PR TITLE
[c10d] Barrier uses stream sync instead of device sync

### PR DESCRIPTION
**Pull request by kwen2501**
Resubmitting #96785

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Review by wconstab — APPROVED** [review]

**Comment by awgu** [comment]
I think this change might be BC breaking. Should we call this out?

I have previously used `dist.barrier()` for timing code where I relied on it doing a device sync, not just a stream sync.

**Comment by kwen2501** [comment]
@awgu Good idea. I added a note to the documentation. Thanks!

**Comment by malfet** [comment]
@kwen2501 why this PR updated PocketFFT submodule?

**Pull request closed without merging**
