### PR TITLE
[functorch] Simplify BatchedTensorImpl

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #84648
* __->__ #84642

Three changes:
- deleted an unused constructor
- simplified an implementation from the old days when a
BatchedTensorImpl could have multiple bdims
- added a comment about getKeysToPropagateToWrapper

Differential Revision: [D39315049](https://our.internmc.facebook.com/intern/diff/D39315049)

@diff-train-skip-merge

### CODE REVIEW

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39315049).

**Review by samdow — APPROVED** [review]

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39315049).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39315049).

**Comment by izaitsevfb** [comment]
@diff-train-skip-merge

**Pull request closed without merging**
