### PR TITLE
directly add_subdirectory(nanopb) from torch CMakeLists

### PR DESCRIPTION
**Pull request by anderspapitto**
currently torch/CMakeLists doesn't know how to find nanopb without
some higher-level script (setup.py or build_all.sh) telling it where
to look, which is an obstacle towards fully CMake-ifying libtorch.so.
This change removes that dependency.

### CODE REVIEW

**Review by orionr — APPROVED** [review]
If tests pass, looks like a good intermediate step until we move this into cmake/Dependencies.cmake with a `BUILD_TORCH` flag.

**Comment by anderspapitto** [comment]
@soumith can I get a codeowner stamp?

**Review by ezyang — APPROVED** [review]
OK sure.

**Pull request merged**
