### PR TITLE
Add support for reduce-scatter in c10d

### PR DESCRIPTION
**Pull request by mxw**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #19631 Fix CUDA stream syncing bug in allgather and reduce_scatter
* **#18844 Add support for reduce-scatter in c10d**
* #18820 Refactor ProcessGroupNCCL collective primitives

Differential Revision: [D14768369](https://our.internmc.facebook.com/intern/diff/D14768369)

### CODE REVIEW

**Review by mrshenli — COMMENTED** [review]
Shall we add some Python tests to `test_c10d.py`?

**Comment by mxw** [comment]
Added Python tests.  In doing so, I realized I'd forgotten to add a reduce op argument, and also that we need to explicitly forge the C++/Python bindings, so I added all that.

**Review by mrshenli — APPROVED** [review]

**Pull request closed without merging**
