### PR TITLE
Use clang for Android build by default

### PR DESCRIPTION
**Pull request by dreiss**
Summary:
GCC is deprecated in the Android NDK, and the old version of GCC
that they ship can't build the latest Caffe2.  Switch to Clang instead.

Differential Revision: D14428450

### CODE REVIEW

**Comment by ezyang** [comment]
@dreiss Do you happen to know why the Android NDK we test against is so old?

**Comment by ezyang** [comment]
cc @t-vi

**Comment by t-vi** [comment]
I don't have much insight into why and how caffe2 does things, but here are a few things that I think I know:
- I think I mentioned gcc vs. clang to @Maratyszcza , who said that gcc generated faster code for NNPack. I have no idea whether that is still the case.
- It might be that to maximize compatibility with older devices, building on older android is good. But as that hasn't been relevant to me, I didn't investigate.
- In #15509 @soumith also changed the compiler to clang (based on my bad example, I guess) but that doesn't build with the old NDK.
- For PyTorch #16242 , I need newer clang (I think NDK 18 or so started supporting thread local). Based on @ezyang's advice, I do have a patch to the docker that allows image names with `-android19c-` to select an NDK version. But obviously if caffe2 would update Android, that would resolve my need to do that. I was going to add a test for PyTorch based on that somewhere.

So while I clang + update of the NDK would trivially make the caffe2 tests work, I would assume that they have reasons for not doing so.

**Comment by dreiss** [comment]
I don't know why we test against an old NDK.  I can't even tell from the failure what version it is using.

gcc probably still generates faster numerical code than clang (though maybe not if you're comparing gcc 4.9 against modern clang, which is what's in the NDK).

New NDK's can still build code for old Android versions with no issues that I'm aware of.  (As long as you select an old target platform.)

> So while I clang + update of the NDK would trivially make the caffe2 tests work, I would assume that they have reasons for not doing so.

Who is "they"?  All of our Android builds within Facebook use Buck and are decoupled from this change.

**Comment by ezyang** [comment]
Paging @pietern who I believe setup this contbuild configuration originally

**Comment by pietern** [comment]
After setting it up 1+ years ago, where I just copied the versions required by the Caffe2 build, I haven't touched it, so can't comment on the consequences of an upgrade here. That said, if the current one is deprecated in upstream, it should be safe to upgrade IMO.

**Comment by t-vi** [comment]
As far as I can tell, this can be closed because it has long been implemented.
Please reopen if you disagree.

**Pull request closed without merging**
