### PR TITLE
lu_backward: more numerically stable and with complex support.

### LINKED ISSUE #52891: RunTimeError: torch.det and torch.lu does not support automatic differentiation for outputs with complex dtype
## 🐛 There are two bugs:
Error 1: RunTimeError: torch.det does not support automatic differentiation for outputs with complex dtype. 
Error 2: To avoid Error 1, I also tried to calculate determinant of a complex matrix by using LU-Decomposition. However, lu.backforward() only supports floating data type. I am sure that my matrix has full rank. That problems only occur if input matrix is a tensor which requires auto_grad.

Just wondering if there is any plan for supporting complex auto_grad in the future. Thanks a lot for your help!!!

### Steps to reproduce Error 1:
x = torch.randn(4, 4, requires_grad=True, dtype=torch.cdouble)
torch.det(x)

Error messages for Error 1:
RuntimeError: det does not support automatic differentiation for outputs with complex dtype.

### Steps to reproduce Error 2:
A = torch.ones(4, 4, requires_grad=True, dtype=torch.cdouble)
A_LU, pivots = A.lu()

Error messages for Error 2:
ValueError: lu.backward works only with batches of squared full-rank matrices of floating types.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): nightly 1.9.0
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: CUDA 10.2, CUDNN 8
 - GPU models and configuration: GTX 1080Ti
 - Any other relevant information:

## Additional context

cc @ezyang @anjali411 @dylanbespalko @mruberry @jianyuh @nikitaved @pearu @heitorschueroff @walterddr @IvanYashchuk

### PR DESCRIPTION
**Pull request by nikitaved**
As per title.

Numerical stability increased by replacing inverses with solutions to systems of linear triangular equations.

Unblocks computing `torch.det` for FULL-rank inputs of complex dtypes via the LU decomposition once https://github.com/pytorch/pytorch/pull/48125/files is merged:
```
LU, pivots = input.lu()
P, L, U = torch.lu_unpack(LU, pivots)
det_input = P.det() * torch.prod(U.diagonal(0, -1, -2), dim=-1)  # P is not differentiable, so we are fine even if it is complex.
```

Unfortunately, since `lu_backward` is implemented as `autograd.Function`, we cannot support both autograd and scripting at the moment.
The solution would be to move all the lu-related methods to ATen, see https://github.com/pytorch/pytorch/issues/53364.

Resolves https://github.com/pytorch/pytorch/issues/52891
TODOs:
* extend lu_backward for tall/wide matrices of full rank.
* move lu-related functionality to ATen and make it differentiable.
* handle rank-deficient inputs.

### CODE REVIEW

**Review by anjali411 — APPROVED** [review]
LGTM! thanks @nikitaved please ping me once the merge conflicts are resolved and the PR is ready for merge.

**Comment by nikitaved** [comment]
Thank you, @anjali411 , the PR is ready.

**Comment by anjali411** [comment]
@nikitaved #48125 is merged. could you rebase this PR?

**Comment by anjali411** [comment]
@nikitaved The PR failure looks legit:
```
Mar 19 20:04:55 ERROR [0.004s]: test_get_torch_func_signature_exhaustive_lu_cpu_float32 (__main__.TestOperatorSignaturesCPU)
Mar 19 20:04:55 ----------------------------------------------------------------------
Mar 19 20:04:55 Traceback (most recent call last):
Mar 19 20:04:55   File "test_fx.py", line 2177, in test_get_torch_func_signature_exhaustive
Mar 19 20:04:55     assert op.name in known_no_schema
Mar 19 20:04:55 AssertionError
Mar 19 20:04:55 
Mar 19 20:04:55 During handling of the above exception, another exception occurred:
Mar 19 20:04:55 
Mar 19 20:04:55 Traceback (most recent call last):
Mar 19 20:04:55   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 287, in instantiated_test
Mar 19 20:04:55     result = test_fn(self, *args)
Mar 19 20:04:55   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
Mar 19 20:04:55     return fn(slf, device, *args, **kwargs)
Mar 19 20:04:55   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
Mar 19 20:04:55     return fn(slf, device, *args, **kwargs)
Mar 19 20:04:55   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 584, in dep_fn
Mar 19 20:04:55     return fn(slf, device, *args, **kwargs)
Mar 19 20:04:55   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 265, in test_wrapper
Mar 19 20:04:55     return test(*args, **kwargs)
Mar 19 20:04:55   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 696, in only_fn
Mar 19 20:04:55     return fn(slf, device, *args, **kwargs)
Mar 19 20:04:55   File "test_fx.py", line 2194, in test_get_torch_func_signature_exhaustive
Mar 19 20:04:55     assert op.name in known_failing_tests
Mar 19 20:04:55 NameError: name 'known_failing_tests' is not defined
Mar 19 20:04:55 
Mar 19 20:04:55 ----------------------------------------------------------------------
```

**Comment by nikitaved** [comment]
Oh, I have never dealt with these tests! Could it be a rebase issue? It complaints about undefined name

**Comment by nikitaved** [comment]
@anjali411 , that seems like a bug not related to this PR:
```
(pytorch-cuda-dev) nik@qgpu3:~/git/pytorch$ git grep known_failing_tests
test/test_fx.py:            assert op.name in known_failing_tests
```
Shall I just delete this assertion? As you see, `known_failing_tests` is just nowhere defined.

**Comment by anjali411** [comment]
> @anjali411 , that seems like a bug not related to this PR:
> 
> ```
> (pytorch-cuda-dev) nik@qgpu3:~/git/pytorch$ git grep known_failing_tests
> test/test_fx.py:            assert op.name in known_failing_tests
> ```
> 
> Shall I just delete this assertion? As you can see, `known_failing_tests` is just nowhere defined.

yeah, although it's not failing on master so probably an exception is being thrown with the changes made in this PR, in which case we should investigate why that is. cc: @jamesr66a who added the respective test in https://github.com/pytorch/pytorch/pull/53830

**Comment by mruberry** [comment]
> > @anjali411 , that seems like a bug not related to this PR:
> > ```
> > (pytorch-cuda-dev) nik@qgpu3:~/git/pytorch$ git grep known_failing_tests
> > test/test_fx.py:            assert op.name in known_failing_tests
> > ```
> > 
> > 
> > As you can see, `known_failing_tests` is just nowhere defined.
> 
> yeah, we should initiate it before.
> 
> > Shall I just delete this assertion?
> 
> Although you are write, `known_failing_tests ` should have been defined before, this test is not failing on master so probably an exception is being thrown with the changes made in this PR, in which case we should investigate why that is. cc: @jamesr66a who added the respective test in #53830

It would be helpful if this test makes suggestions for how to handle failures, too. For example, it could recommend that the OpInfo skip the test, or suggest how to update the op to pass the test.

**Comment by jamesr66a** [comment]
> @anjali411 , that seems like a bug not related to this PR:
> 
> ```
> (pytorch-cuda-dev) nik@qgpu3:~/git/pytorch$ git grep known_failing_tests
> test/test_fx.py:            assert op.name in known_failing_tests
> ```
> 
> Shall I just delete this assertion? As you can see, `known_failing_tests` is just nowhere defined.

The test failure is true-positive. *do not delete the assertion*. The fact that the name was not defined is an artifact of having to refactor that test to use OpInfo and can be fixed separately

**Comment by jamesr66a** [comment]
Here's a fix for the test: https://github.com/pytorch/pytorch/pull/54510

I don't have LAPACK so I can't reproduce the failure, but if you base on top of that, you should see the same failure. If it goes through the `raise RuntimeError('No Schemas Returned')` path, add the op name to `known_no_schemas`. Otherwise, we have to dig into what the failure is

**Comment by jamesr66a** [comment]
BTW, even if we add the operator to `known_no_schemas`, we should figure out why we cannot find a TorchScript schema for this op. That may indicate further problems, e.g. TorchScript cannot find this op and would suggest incompatibility down the line

**Comment by jamesr66a** [comment]
OK, I got LAPACK working on my build. It seems that the issue is that `torch.lu` is actually a `torch.functional` Python function aliased onto the base `torch` namespace. @mruberry are functionals admissible to `OpInfo`? If so, can we have a way to distinguish between these things?

In the meantime, I think the "correct" solution is the following:
```
diff --git a/torch/testing/_internal/common_methods_invocations.py b/torch/testing/_internal/common_methods_invocations.py
index 4c47c330441..bf53cdd5774 100644
--- a/torch/testing/_internal/common_methods_invocations.py
+++ b/torch/testing/_internal/common_methods_invocations.py
@@ -2671,6 +2671,9 @@ op_db: List[OpInfo] = [
                # we skip jit tests because lu_backward is impelemented as autograd.Function,
                # which does not support autograd with scripting
                SkipInfo('TestCommon', 'test_variant_consistency_jit'),
+               # Skip operator schema test because this is a functional and not
+               # an operator
+               SkipInfo('TestOperatorSignatures', 'test_get_torch_func_signature_exhaustive'),
            )),
     OpInfo('masked_scatter',
            dtypes=all_types_and_complex_and(torch.bool, torch.half, torch.bfloat16),
```

**Comment by mruberry** [comment]
> OK, I got LAPACK working on my build. It seems that the issue is that `torch.lu` is actually a `torch.functional` Python function aliased onto the base `torch` namespace. @mruberry are functionals admissible to `OpInfo`? If so, can we have a way to distinguish between these things?

Yes and yes. 

To be clear, you mean you'd like ops specified here: 

https://github.com/pytorch/pytorch/blob/ba9f12d2353b775ea272f0658e0c8f12b2bf4dc0/torch/functional.py#L19

to have some metadata, like, "is_torch_functional", and then that class of ops can be filtered out when running this test, right?


> In the meantime, I think the "correct" solution is the following:
> 
> ```
> diff --git a/torch/testing/_internal/common_methods_invocations.py b/torch/testing/_internal/common_methods_invocations.py
> index 4c47c330441..bf53cdd5774 100644
> --- a/torch/testing/_internal/common_methods_invocations.py
> +++ b/torch/testing/_internal/common_methods_invocations.py
> @@ -2671,6 +2671,9 @@ op_db: List[OpInfo] = [
>                 # we skip jit tests because lu_backward is impelemented as autograd.Function,
>                 # which does not support autograd with scripting
>                 SkipInfo('TestCommon', 'test_variant_consistency_jit'),
> +               # Skip operator schema test because this is a functional and not
> +               # an operator
> +               SkipInfo('TestOperatorSignatures', 'test_get_torch_func_signature_exhaustive'),
>             )),
>      OpInfo('masked_scatter',
>             dtypes=all_types_and_complex_and(torch.bool, torch.half, torch.bfloat16),
> ```

Adding a SkipInfo for the moment sounds good.

**Comment by jamesr66a** [comment]
> To be clear, you mean you'd like ops specified here to have some metadata, like, "is_torch_functional", and then that class of ops can be filtered out when running this test, right?

Yes, that's correct

**Comment by mruberry** [comment]
https://github.com/pytorch/pytorch/issues/54574 for the OpInfo skip issue.

**Pull request closed without merging**
