### PR TITLE
[functional collective] parameterize allreduce tests

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #105642
* #105614
* #105605
* __->__ #105604

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]

**Comment by xwang233** [comment]
Hi @wanchaol , we have seen test error after this PR. Any idea why this could happen?
```python
root@3a200820ad75:/opt/pytorch/pytorch# python test/distributed/test_functional_api.py -v -k TestTraceableCollectives.test_all_reduce_coalesced_eager_device_cuda
test_all_reduce_coalesced_eager_device_cuda (__main__.TestTraceableCollectives) ... INFO:numba.cuda.cudadrv.driver:init
/opt/pytorch/pytorch/torch/distributed/distributed_c10d.py:2083: UserWarning: torch.distributed.all_reduce_coalesced will be deprecated. If you must use it, please revisit our documentation later at https://pytorch.org/docs/master/distributed.html#collective-functions
  warnings.warn(
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] Caught exception: 
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] Traceback (most recent call last):
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 1034, in run_test_with_threaded_pg
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     getattr(self, test_name)()
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 953, in wrapper
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     fn()
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2362, in wrapper
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     method(*args, **kwargs)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 356, in instantiated_test
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     test(self, **param_kwargs)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/test/distributed/test_functional_api.py", line 256, in test_all_reduce_coalesced_eager
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     res = ft_c.all_reduce_coalesced([t0, t1], "sum", mesh)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/distributed/_functional_collectives.py", line 231, in all_reduce_coalesced
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     tensor_list = torch.ops.c10d_functional.all_reduce_coalesced(self, reduceOp, tag, rankset, group_size)  # type: ignore[attr-defined]
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/_ops.py", line 681, in __call__
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     return self._op(*args, **kwargs or {})
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/distributed/_functional_collectives_impl.py", line 122, in _all_reduce_coalesced
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     work = dist.all_reduce_coalesced(inplace_tensor_list, op=op, group=group, async_op=True)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/distributed/c10d_logger.py", line 47, in wrapper
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     return func(*args, **kwargs)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/distributed/distributed_c10d.py", line 2105, in all_reduce_coalesced
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     work = group.allreduce_coalesced(tensors, opts)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/multi_threaded_pg.py", line 299, in allreduce_coalesced
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     res = coll.join(self._rank, tensor_list)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/multi_threaded_pg.py", line 224, in join
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     self._collective.work(self._data)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/utils/_contextlib.py", line 115, in decorate_context
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     return func(*args, **kwargs)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/multi_threaded_pg.py", line 91, in work
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     res = _reduce_ops[self.op](tensors)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]   File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/multi_threaded_pg.py", line 47, in binop_reduce
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]     res = op(torch.stack(tensors), dim=0)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] Exception raised from common_device_check_failure at /opt/pytorch/pytorch/aten/src/ATen/core/adaption.cpp:7 (most recent call first):
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xae (0x7f9389bb177e in /opt/pytorch/pytorch/torch/lib/libc10.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7f9389b679ef in /opt/pytorch/pytorch/torch/lib/libc10.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #2: c10::impl::common_device_check_failure(c10::optional<c10::Device>&, at::Tensor const&, char const*, char const*) + 0x3a7 (0x7f935a5174c7 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #3: <unknown function> + 0x30639e1 (0x7f933ae1d9e1 in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #4: <unknown function> + 0x2eac8ca (0x7f933ac668ca in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #5: <unknown function> + 0x2eac9c8 (0x7f933ac669c8 in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #6: at::_ops::cat::call(c10::IListRef<at::Tensor> const&, long) + 0x1a5 (0x7f935ae73de5 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #7: at::native::stack(c10::ArrayRef<at::Tensor>, long) + 0x1df (0x7f935a9cdf6f in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #8: <unknown function> + 0x25177bb (0x7f935b6c47bb in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #9: at::_ops::stack::redispatch(c10::DispatchKeySet, c10::ArrayRef<at::Tensor>, long) + 0x95 (0x7f935afca2a5 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #10: <unknown function> + 0x3a4e98e (0x7f935cbfb98e in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #11: <unknown function> + 0x3a4edbe (0x7f935cbfbdbe in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #12: at::_ops::stack::call(c10::ArrayRef<at::Tensor>, long) + 0x196 (0x7f935b014b76 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #13: <unknown function> + 0x55a9df (0x7f936423c9df in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] <omitting python frames>
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #36: <unknown function> + 0xb5fffb (0x7f9364841ffb in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #37: <unknown function> + 0x4c48547 (0x7f935ddf5547 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #38: torch::jit::invokeOperatorFromPython(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, pybind11::args, pybind11::kwargs const&, c10::optional<c10::DispatchKey>) + 0x4f3 (0x7f93645b8353 in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #39: torch::jit::_get_operation_for_overload_or_packet(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, c10::Symbol, pybind11::args, pybind11::kwargs const&, bool, c10::optional<c10::DispatchKey>) + 0x620 (0x7f93645b8cb0 in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #40: <unknown function> + 0x7ab9e6 (0x7f936448d9e6 in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] frame #41: <unknown function> + 0x3c246f (0x7f93640a446f in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] 
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] 
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] To execute this test, run the following from the base repo dir:
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]      python test/distributed/test_functional_api.py -k test_all_reduce_coalesced_eager_device_cuda
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] 
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR] This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
[2023-08-11 15:27:02,511] torch.testing._internal.common_distributed: [ERROR]  exiting thread 0
ERROR

======================================================================
ERROR: test_all_reduce_coalesced_eager_device_cuda (__main__.TestTraceableCollectives)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 951, in wrapper
    self._join_threads(self.threads, fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 1070, in _join_threads
    cls._check_return_codes(failed_ranks, timeout, fn)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 1107, in _check_return_codes
    raise RuntimeError(error_msg)
RuntimeError: Thread 0 exited with exception:
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 1034, in run_test_with_threaded_pg
    getattr(self, test_name)()
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_distributed.py", line 953, in wrapper
    fn()
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2362, in wrapper
    method(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 356, in instantiated_test
    test(self, **param_kwargs)
  File "/opt/pytorch/pytorch/test/distributed/test_functional_api.py", line 256, in test_all_reduce_coalesced_eager
    res = ft_c.all_reduce_coalesced([t0, t1], "sum", mesh)
  File "/opt/pytorch/pytorch/torch/distributed/_functional_collectives.py", line 231, in all_reduce_coalesced
    tensor_list = torch.ops.c10d_functional.all_reduce_coalesced(self, reduceOp, tag, rankset, group_size)  # type: ignore[attr-defined]
  File "/opt/pytorch/pytorch/torch/_ops.py", line 681, in __call__
    return self._op(*args, **kwargs or {})
  File "/opt/pytorch/pytorch/torch/distributed/_functional_collectives_impl.py", line 122, in _all_reduce_coalesced
    work = dist.all_reduce_coalesced(inplace_tensor_list, op=op, group=group, async_op=True)
  File "/opt/pytorch/pytorch/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/distributed/distributed_c10d.py", line 2105, in all_reduce_coalesced
    work = group.allreduce_coalesced(tensors, opts)
  File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/multi_threaded_pg.py", line 299, in allreduce_coalesced
    res = coll.join(self._rank, tensor_list)
  File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/multi_threaded_pg.py", line 224, in join
    self._collective.work(self._data)
  File "/opt/pytorch/pytorch/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/multi_threaded_pg.py", line 91, in work
    res = _reduce_ops[self.op](tensors)
  File "/opt/pytorch/pytorch/torch/testing/_internal/distributed/multi_threaded_pg.py", line 47, in binop_reduce
    res = op(torch.stack(tensors), dim=0)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)
Exception raised from common_device_check_failure at /opt/pytorch/pytorch/aten/src/ATen/core/adaption.cpp:7 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xae (0x7f9389bb177e in /opt/pytorch/pytorch/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7f9389b679ef in /opt/pytorch/pytorch/torch/lib/libc10.so)
frame #2: c10::impl::common_device_check_failure(c10::optional<c10::Device>&, at::Tensor const&, char const*, char const*) + 0x3a7 (0x7f935a5174c7 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x30639e1 (0x7f933ae1d9e1 in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x2eac8ca (0x7f933ac668ca in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x2eac9c8 (0x7f933ac669c8 in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
frame #6: at::_ops::cat::call(c10::IListRef<at::Tensor> const&, long) + 0x1a5 (0x7f935ae73de5 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #7: at::native::stack(c10::ArrayRef<at::Tensor>, long) + 0x1df (0x7f935a9cdf6f in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x25177bb (0x7f935b6c47bb in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #9: at::_ops::stack::redispatch(c10::DispatchKeySet, c10::ArrayRef<at::Tensor>, long) + 0x95 (0x7f935afca2a5 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x3a4e98e (0x7f935cbfb98e in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x3a4edbe (0x7f935cbfbdbe in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #12: at::_ops::stack::call(c10::ArrayRef<at::Tensor>, long) + 0x196 (0x7f935b014b76 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x55a9df (0x7f936423c9df in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
<omitting python frames>
frame #36: <unknown function> + 0xb5fffb (0x7f9364841ffb in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
frame #37: <unknown function> + 0x4c48547 (0x7f935ddf5547 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #38: torch::jit::invokeOperatorFromPython(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, pybind11::args, pybind11::kwargs const&, c10::optional<c10::DispatchKey>) + 0x4f3 (0x7f93645b8353 in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
frame #39: torch::jit::_get_operation_for_overload_or_packet(std::vector<std::shared_ptr<torch::jit::Operator>, std::allocator<std::shared_ptr<torch::jit::Operator> > > const&, c10::Symbol, pybind11::args, pybind11::kwargs const&, bool, c10::optional<c10::DispatchKey>) + 0x620 (0x7f93645b8cb0 in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
frame #40: <unknown function> + 0x7ab9e6 (0x7f936448d9e6 in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
frame #41: <unknown function> + 0x3c246f (0x7f93640a446f in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)


To execute this test, run the following from the base repo dir:
     python test/distributed/test_functional_api.py -k test_all_reduce_coalesced_eager_device_cuda

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0



----------------------------------------------------------------------
Ran 1 test in 1.433s

FAILED (errors=1)
```

We tested on a 8-GPU machine. I added a `print(tensors)` on the first line of `def binop_reduce` above `torch.stack`, and it prints
```python
[tensor([1., 1., 1., 1.], device='cuda:0'), tensor([1., 1., 1., 1.], device='cuda:1'), tensor([1., 1., 1., 1.], device='cuda:2'), tensor([1., 1., 1., 1.], device='cuda:3')]
```

cc @ptrblck @eqy

**Comment by xwang233** [comment]
In fact, there are 4 tests failing, not sure if those are relevant
```
TestTraceableCollectives.test_all_reduce_coalesced_eager_device_cuda
TestTraceableCollectives.test_all_reduce_eager_device_cuda
TestTraceableCollectives.test_reduce_scatter_into_tensor_coalesced_device_cuda
TestTraceableCollectives.test_reduce_scatter_tensor_device_cuda
```

**Comment by wanchaol** [comment]
> Thanks for reporting @xwang233! After some investigation I think there're some issues with the Multithreaded PG's allreduce and reduce_scatter implementation, in particular I think the current implementation does not respect different cuda devices on different ranks. I'll try to see how to fix it tomorrow. cc @kumpera

@xwang233 the fix is out https://github.com/pytorch/pytorch/pull/107152 I'll try to land it by today

**Comment by xwang233** [comment]
Thanks for the fix @wanchaol ! The tests are passed now in the latest main commit.

**Pull request closed without merging**
