### PR TITLE
get rid of choco install

### PR DESCRIPTION
**Pull request by mingbowan**
7zip and cmake are part of base image, no need to re-install. Remove the install step can make build/test more stable.

### CODE REVIEW

**Review by suo — APPROVED** [review]

**Review by orionr — APPROVED** [review]
Double approval. :)

**Review by peterjc123 — APPROVED** [review]
LG, but why are there so many errors like `RuntimeError: CUDA error: unspecified launch failure`?

**Comment by mingbowan** [comment]
> LG, but why are there so many errors like `RuntimeError: CUDA error: unspecified launch failure`?

@peterjc123  I'm confused too. any idea?

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit 9cc6e57:
* **1/1** broken upstream at merge base 6ab2d1b (see [grid view](https://dr.pytorch.org/master-timeline.html?count=1&sha1=6ab2d1b1a49de255da11d80772a0dd7ec9e9bae2&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35))
    * You may want to rebase on the `viable/strict` branch (see its [recency history](https://dr.pytorch.org/master-viable-commits.html)):
        * If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
          ```
          git fetch viable/strict
          git rebase --onto viable/strict $(git merge-base origin/master HEAD)
          ```
        * If your commit is older than `viable/strict`:
          ```
          git fetch viable/strict
          git rebase viable/strict
          ```
* **0/1** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=9cc6e5731208ce97d196b9d9cfaa027949e818f2).

### 1 failure *not* recognized by patterns:
| Job | Step |
| --- | --- |
| CircleCI <sup>pytorch_xla_linux_xenial_py3_6_clang7_build</sup> | <sup>Build</sup> |


---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Review by pietern — DISMISSED** [review]
The PR now includes unrelated reverts (and added a bunch more people as code reviewer).

**Comment by peterjc123** [comment]
@pietern Well, that revert should be there, otherwise the VS 2017 build will break. Anyway, we are just testing and will do this revert in a separate PR if we really need to. As for the code reviewers, I have no idea because I am not the author of the PR.

**Comment by pietern** [comment]
I see, thanks for clarifying.

**Comment by mingbowan** [comment]
the problem has finally been "fixed" by moving to visual studio 2017.

**Review by peterjc123 — APPROVED** [review]

**Pull request closed without merging**
