### PR TITLE
Skip MeanVarianceNormalization onnx tests

### PR DESCRIPTION
**Pull request by houseroad**
Make sure that CI is happy

### CODE REVIEW

**Comment by houseroad** [comment]
https://github.com/onnx/onnx/pull/1335 Skip the test

**Review by bddppq — APPROVED** [review]
LG. But probably better to fold it into the next onnx submodule bump commit.

**Comment by houseroad** [comment]
@bddppq sure, will bump up when I push all the version converter commits in :-)

**Comment by bddppq** [comment]
Let's fold this into #10961?

**Pull request closed without merging**
