### PR TITLE
Revert "Dont clone unmutated args in triton autotuning (#89519)"

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89652

This reverts commit f18f0c70ab10c400947e71be30794e04dcc22acf.

Testing to see if this fixes gmixer_24_224 mixer_b16_224

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by ezyang** [comment]
This fixes two of the timm model failures!!! Please consider approving it.

**Comment by eellison** [comment]
`dm_nfnet_f0                        fail_accuracy` on this pr. but happy to revert and try to reland later

**Review by eellison — APPROVED** [review]

**Comment by ezyang** [comment]
Yeah I think that one is a different culprit

**Pull request closed without merging**
