### PR TITLE
Move torch/autograd/grad_mode.pyi stubs inline

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #38211 Move all torch.nn.modules type annotations inline
* **#38201 Move torch/autograd/grad_mode.pyi stubs inline**
* #38173 Device and torch._C function cleanup
* #38157 Delete torch/__init__.pyi, deferring to direct extension stubs

- Add torch._C bindings from torch/csrc/autograd/init.cpp
- Renamed torch._C.set_grad_enabled to torch._C._set_grad_enabled
  so it doesn't conflict with torch.set_grad_enabled anymore

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D21497398](https://our.internmc.facebook.com/intern/diff/D21497398)

### CODE REVIEW

**Comment by rgommers** [comment]
CI failures are `ModuleNotFoundError: No module named 'typing_extensions'`. `typing_extensions` is a non-optional for `mypy 0.770`. I'll have a look at that.

**Review by rgommers — APPROVED** [review]
Changes LGTM. May want to revert the use of `Literal` if you want to land this before getting `typing_extensions` into all CI jobs.

**Comment by rgommers** [comment]
Ah okay, we need to make it a hard dependency of pytorch itself. Which IIRC we discussed somewhere else and you were fine with. Will submit a PR.

Also, there are some CI jobs where mypy isn't installed. I don't think think there's much platform-specific behavior in mypy, but can't hurt to run the tests in a macOS and a Windows job.

**Comment by rgommers** [comment]
> Ah okay, we need to make it a hard dependency of pytorch itself. Which IIRC we discussed somewhere else and you were fine with. Will submit a PR.

This also requires changes to `builder`, the docs, and perhaps other places. Opening an issue for visibility and motivate the need a bit more.

**Comment by ezyang** [comment]
I'm going to unhook this PR from the stack for now, and properly add `typing_extensions`. mypy complains about the typing of context managers without Literal, so the correct thing to do is just actually install `typing_extensions` everywhere.

**Pull request closed without merging**
