### PR TITLE
Virtualize `<type>Storage` classes

### LINKED ISSUE #66228: Virtualize `FloatStorage` and other `<type>Storage` classes
This is a follow up from #47442.

* Storage should be similar to Tensor
  * FloatTensor is not a real class, floating point tensors returned from PyTorch API aren’t FloatTensor, you can still use FloatTensor as a constructor and do isinstance checks
    * Should simplify the Storage binding code
* Removal of torch.Storage and torch.cuda.Storage as separate concepts
  * torch.cuda.Storage is not a real thing, it just tests that it’s a CUDA storage
  * Untyped storage know the device, just not part of device type
* Simplifies register storage ptype stuff
* Simplifies `torch/__init__.py` storage class definitions
* No more cartesian product of device x dtype storages

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

### PR DESCRIPTION
**Pull request by kurtamohler**
Fixes #66228

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

### CODE REVIEW

**Comment by kurtamohler** [comment]
Note that TypedStorage and UntypedStorage are still not documented yet. I will post a PR soon to add that

**Comment by kurtamohler** [comment]
I've added documentation updates to this PR

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
A lot of internal tests are failing with 
```
TypeError: _new_shared() missing 1 required positional argument: 'size'
```
seems like it's caused by 
```
in allocate_shared_tensor
    storage = tensor.storage_type()._new_shared(size.numel())
```
There are also other failures where process doesn't exit with 0 exit code, but I haven't tracked what's causing it.

**Comment by kurtamohler** [comment]
@ngimel, the `_new_shared` error comes from the fact that `TypedStorage._new_shared` can currently only be used as an instance method, because it needs to access the dtype and device of the instantiated `TypedStorage` object. For the legacy storage types, `<type>Storage._new_shared` is a classmethod--the dtype and device are constant for a given legacy storage class.

Maybe we could consider making `TypedStorage._new_shared` work as both a class method and an instance method (although I'm not sure how to do that at the moment). If it's called as a class method, we could use the default dtype and device. However, I'm not sure if this is a good idea. I have a feeling that it would be better to avoid calling `_new_shared` as a classmethod entirely. For instance, consider this:

```python
s = torch.TypedStorage(dtype=torch.int)

s._new_shared(size)             # This returns a correct TypedStorage with dtype=torch.int
type(s)._new_shared(size)       # This returns an incorrect TypedStorage with the default dtype=torch.float
```

Before this PR, the `type(s)._new_shared(size)` call would have returned the proper `<type>Storage` object, with matching dtype and device. But if we decided allow `TypedStorage._new_shared` to be called as a classmethod, we would have no way to know what the correct dtype and device were.

**Comment by ezyang** [comment]
Status on this?

**Comment by ngimel** [comment]
> Status on this?

Lots of internal errors that I didn't look into.

**Comment by kurtamohler** [comment]
Note: This PR will need to be updated after #72540

**Comment by ezyang** [comment]
is extra help needed on this?

**Comment by ezyang** [comment]
Hmm, it seems easiest to make FloatStorage._new_shared work, in the same way IntTensor([1,2]) works and gives you an IntTensor. Then we can do some more things:

* storage_type() returns something like FloatStorage, but we deprecate it
* Introduce a better API for `_new_shared`

WDYT?

**Comment by kurtamohler** [comment]
> Hmm, it seems easiest to make FloatStorage._new_shared work, in the same way IntTensor([1,2]) works and gives you an IntTensor.

I'm not sure I understand, are you suggesting that all `<type>Storage._new_shared` and `TypedStorage._new_shared` calls should return an IntTensor?

> * storage_type() returns something like FloatStorage, but we deprecate it
> * Introduce a better API for `_new_shared`

That seems like a good idea

**Comment by ezyang** [comment]
I think your confusion is because I misunderstood the current state. I was specifically suggesting that FloatStorage._new_shared should return a FloatStorage, but it sounds like this is already true. So all we need to do is make storage_type return one of the typed legacy storages, which we both agree is a good idea at this point.

Also, sorry about the merge conflicts :(

**Comment by kurtamohler** [comment]
> So all we need to do is make storage_type return one of the typed legacy storages

Done. `Tensor.storage_type()` now returns the `<type>Storage` (ie, a child class of `_LegacyStorage`) corresponding with the tensor's dtype

**Comment by ezyang** [comment]
Seems like we're pretty close. Need to look at this internal failure.

```
    File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/buck-out/dev/gen/caffe2/torch/fb/distributed/model_parallel/tests/test_rpc_shared_memory#binary,link-tree/torch/distributed/rpc/internal.py", line 203, in _run_function
      raise python_udf
  AttributeError: 'torch._UntypedStorage' object has no attribute 'dtype' Default RPC pickler does not serialize
              function code. Ensure that UDFs are defined on both caller and
              callee modules.
```

**Comment by ezyang** [comment]
I got the backtrace, it's an obviously bad call site.

**Comment by ezyang** [comment]
Here is the full backtrace:

```
Traceback (most recent call last):                                                                                                                   
  File "/data/users/ezyang/fbsource-tmp/fbcode/buck-out/dev/gen/caffe2/torch/fb/distributed/model_parallel/tests/test_rpc_shared_memory#binary,link-t
ree/torch/distributed/rpc/internal.py", line 159, in deserialize                                                                                     
    ret = unpickler.load()                                                                                                                           
  File "/data/users/ezyang/fbsource-tmp/fbcode/buck-out/dev/gen/caffe2/torch/fb/distributed/model_parallel/tests/test_rpc_shared_memory#binary,link-t
ree/torch/multiprocessing/reductions.py", line 90, in rebuild_tensor                                                                                 
    t = torch._utils._rebuild_tensor(storage, storage_offset, size, stride)                            
  File "/data/users/ezyang/fbsource-tmp/fbcode/buck-out/dev/gen/caffe2/torch/fb/distributed/model_parallel/tests/test_rpc_shared_memory#binary,link-t
ree/torch/_utils.py", line 134, in _rebuild_tensor                                                                                                   
    t = torch.tensor([], dtype=storage.dtype, device=storage.device)       
```

The problem is the unpickler in torch.distributed.rpc.internal; they are apparently using the stock unpickler, and it seems like stock pickling/unpickling  doesn't work (this should be easy enough to write a test case for). I guess you have to somehow teach this pickler site to know how to do the legacy serialization/deserialization format...

I guess I have questions about why RPC is using the stock unpickler, I'll ask about this.

**Comment by ezyang** [comment]
Based on discussion in the linked issue, I regret to inform you that you will have to update the rpc pickler/unpickler logic as well. You can probably jump straight to the untyped storage format as there is no BC/FC need for the on-the-wire format.

**Comment by kurtamohler** [comment]
@ezyang, I'm not exactly sure how to reproduce the RPC error you posted.

I tried a few different things:
* Send a tensor to a worker, the worker sends back the tensor's `_TypedStorage`
* Send a tensor, send back `_UntypedStorage`
* Send a tensor, send back a tensor
* Send a `_TypedStorage`, send it back
* Send an `_UntypedStorage`, send it back

I only get an error for the last one, sending an `_UntypedStorage` back and forth. The error I get for this case is different than the one you posted above--it happens during serialization, so it never even gets to the `_rebuild_tensor` call during the deserialization step. Furthermore, I get the same result whether I run these cases on this branch or on master.

Here are my scripts:

<details>
<summary>
worker0.py (click to expand/collapse):
</summary>

```python
import torch
import torch.distributed.rpc as rpc 

rpc.init_rpc('worker0', rank=0, world_size=2)

def get_storage(a):
    return a.storage()

def get_untyped_storage(a):
    return a.storage()

def passthrough(*args):
    return args

ret = rpc.rpc_sync(
    'worker1',
    get_storage,
    args=(
        torch.arange(10),
    ))  

print(f'0: {ret}')

ret = rpc.rpc_sync(
    'worker1',
    get_untyped_storage,
    args=(
        torch.arange(10),
    ))  

print(f'1: {ret}')

ret = rpc.rpc_sync(
    'worker1',
    passthrough,
    args=(
        torch.arange(10),
    ))  

print(f'2: {ret}')

ret = rpc.rpc_sync(
    'worker1',
    passthrough,
    args=(
        torch.arange(10).storage(),
    ))

print(f'3: {ret}')

ret = rpc.rpc_sync(
    'worker1',
    passthrough,
    args=(
        torch._UntypedStorage(10),
    ))

print(f'4: {ret}')

rpc.shutdown()
```

</details>

<details>
<summary>
worker1.py (click to expand/collapse):
</summary>

```python
import torch.distributed.rpc as rpc 


def passthrough(*args):
    return args

def get_storage(a):
    return a.storage()

def get_untyped_storage(a):
    return a.storage()

rpc.init_rpc('worker1', rank=1, world_size=2)

rpc.shutdown()
```

</details>

And here's what I see when I run them:

<details>
<summary>
Output of worker0.py (click to expand/collapse):
</summary>

```
0:  0
 1
 2
 3
 4
 5
 6
 7
 8
 9
[torch.storage._TypedStorage(dtype=torch.int64, device=cpu) of size 10]
1:  0
 1
 2
 3
 4
 5
 6
 7
 8
 9
[torch.storage._TypedStorage(dtype=torch.int64, device=cpu) of size 10]
2: (tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)
3: ( 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
[torch.storage._TypedStorage(dtype=torch.int64, device=cpu) of size 10],)
Traceback (most recent call last):
  File "/work2/kurtamohler/development/pytorch-perf-test-scripts/rpc/worker0.py", line 51, in <module>
    ret = rpc.rpc_sync(
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/distributed/rpc/api.py", line 77, in wrapper
    return func(*args, **kwargs)
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/distributed/rpc/api.py", line 766, in rpc_sync
    fut = _invoke_rpc(to, func, RPCExecMode.SYNC, args, kwargs, timeout)
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/distributed/rpc/api.py", line 675, in _invoke_rpc
    (pickled_python_udf, tensors) = _default_pickler.serialize(
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/distributed/rpc/internal.py", line 133, in serialize
    p.dump(obj)
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/storage.py", line 79, in __reduce__
    torch.save(self, b, _use_new_zipfile_serialization=False)
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/serialization.py", line 382, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/serialization.py", line 516, in _legacy_save
    pickler.dump(obj)
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/serialization.py", line 429, in persistent_id
    storage_dtype = storage.dtype
AttributeError: 'torch._UntypedStorage' object has no attribute 'dtype'
```

</details>


<details>
<summary>
Output of worker1.py (click to expand/collapse):
</summary>

```
[W tensorpipe_agent.cpp:682] RPC agent for worker1 encountered error when reading incoming request from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)
```

</details>

We should fix this error, but I assume the error you posted is more urgent since it's introduced by this PR. Can you help me reproduce it?

**Comment by ezyang** [comment]
Sorry about sending you on a good chase, it looks like the internal test is defining yet another pickler.

**Comment by ezyang** [comment]
This is their pickler implementation:

```
import copyreg
            
import torch
import torch.multiprocessing.reductions as TorchMpReductions
from torch.distributed.rpc.internal import _InternalRPCPickler


class ShareMemoryRPCPickler(_InternalRPCPickler):
    def __init__(self) -> None:
        super().__init__()
        self._dispatch_table
        # pyre-fixme[4]: Attribute must be annotated.
        self._dispatch_table = copyreg.dispatch_table.copy()

        for t in torch._storage_classes:
            self._dispatch_table[t] = TorchMpReductions.reduce_storage

        for t in torch._tensor_classes:
            self._dispatch_table[t] = TorchMpReductions.reduce_tensor
        self._dispatch_table[torch.Tensor] = TorchMpReductions.reduce_tensor
        self._dispatch_table[
            torch.nn.parameter.Parameter
        ] = TorchMpReductions.reduce_tensor
```

and in their test they set it up as

```
from torch.distributed.rpc.api import _use_rpc_pickler

...


    with _use_rpc_pickler(ShareMemoryRPCPickler()):
        for idx, worker in enumerate(workers):
            # pyre-fixme[16]: Module `rpc` has no attribute `remote`.
            rref_to_remote_param[worker] = rpc.remote(
                worker,
                mock_worker_function,
                kwargs={
                    "module": module,
                    # !!Important!! Only set parameter in ONE worker.
                    "parameter_val": parameter_val if idx == 0 else None,
                },
            )

```

**Comment by kurtamohler** [comment]
@ezyang, thanks for the extra info. I'm still having trouble catching the goose though.

I have the following files:

<details>
<summary>utils.py</summary>

```python
import copyreg
import torch
import torch.multiprocessing.reductions as TorchMpReductions
from torch.distributed.rpc.internal import _InternalRPCPickler

class ShareMemoryRPCPickler(_InternalRPCPickler):
    def __init__(self) -> None:
        super().__init__()
        self._dispatch_table
        # pyre-fixme[4]: Attribute must be annotated.
        self._dispatch_table = copyreg.dispatch_table.copy()

        for t in torch._storage_classes:
            self._dispatch_table[t] = TorchMpReductions.reduce_storage

        for t in torch._tensor_classes:
            self._dispatch_table[t] = TorchMpReductions.reduce_tensor
        self._dispatch_table[torch.Tensor] = TorchMpReductions.reduce_tensor
        self._dispatch_table[
            torch.nn.parameter.Parameter
        ] = TorchMpReductions.reduce_tensor
```

</details>

<details>
<summary>worker0.py</summary>

```python
import torch
import torch.distributed.rpc as rpc
from torch.distributed.rpc.api import _use_rpc_pickler
from utils import ShareMemoryRPCPickler, passthrough

with _use_rpc_pickler(ShareMemoryRPCPickler()):
    rpc.init_rpc(
        'worker0',
        rank=0,
        world_size=2,
    )
    rref = rpc.remote(
        'worker1',
        passthrough,
        args=(
            torch.arange(10),
        )
    )
    print(rref.to_here())
```

</details>

<details>
<summary>worker1.py</summary>

```python
import torch
import torch.distributed.rpc as rpc
from torch.distributed.rpc.api import _use_rpc_pickler
from utils import ShareMemoryRPCPickler, passthrough

# Not sure if this `_use_rpc_pickler` call is actually doing anything
# in this script
with _use_rpc_pickler(ShareMemoryRPCPickler()):
    rpc.init_rpc('worker1', rank=1, world_size=2)
    rpc.shutdown()
```

</details>

When I run `worker0.py` and `worker1.py` at the same time, I still don't get the same error as the one you posted. I get this instead:

<details>
<summary>Click to expand/collapse</summary>

```
Traceback (most recent call last):
  File "/home/kurtamohler/.conda/envs/pytorch-storage-virt/lib/python3.9/multiprocessing/resource_sharer.py", line 138, in _serve
    with self._listener.accept() as conn:
  File "/home/kurtamohler/.conda/envs/pytorch-storage-virt/lib/python3.9/multiprocessing/connection.py", line 470, in accept
    deliver_challenge(c, self._authkey)
  File "/home/kurtamohler/.conda/envs/pytorch-storage-virt/lib/python3.9/multiprocessing/connection.py", line 750, in deliver_challenge
    raise AuthenticationError('digest received was wrong')
multiprocessing.context.AuthenticationError: digest received was wrong
[E thread_pool.cpp:113] Exception in thread pool task: Error on Node 1: AuthenticationError: digest sent was rejected

At:
  /home/kurtamohler/.conda/envs/pytorch-storage-virt/lib/python3.9/multiprocessing/connection.py(764): answer_challenge
  /home/kurtamohler/.conda/envs/pytorch-storage-virt/lib/python3.9/multiprocessing/connection.py(513): Client
  /home/kurtamohler/.conda/envs/pytorch-storage-virt/lib/python3.9/multiprocessing/resource_sharer.py(86): get_connection
  /home/kurtamohler/.conda/envs/pytorch-storage-virt/lib/python3.9/multiprocessing/resource_sharer.py(57): detach
  /work2/kurtamohler/development/pytorch-storage-virtualization/torch/multiprocessing/reductions.py(295): rebuild_storage_fd
  /work2/kurtamohler/development/pytorch-storage-virtualization/torch/distributed/rpc/internal.py(169): deserialize
  /work2/kurtamohler/development/pytorch-storage-virtualization/torch/distributed/rpc/internal.py(190): deserialize

Exception raised from handleException at /work2/kurtamohler/development/pytorch-storage-virtualization/torch/csrc/distributed/rpc/rref_context.cpp:113 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x55 (0x7f6e3bb95125 in /work2/kurtamohler/development/pytorch-storage-virtualization/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xdb (0x7f6e3bb74979 in /work2/kurtamohler/development/pytorch-storage-virtualization/torch/lib/libc10.so)
frame #2: torch::distributed::rpc::RRefContext::handleException(c10::ivalue::Future const&) + 0xd9 (0x7f6e480a89c9 in /work2/kurtamohler/development/pytorch-storage-virtualization/torch/lib/libtorch_cpu.so)
frame #3: torch::distributed::rpc::RRef::handleError(torch::distributed::rpc::RPCErrorType, c10::ivalue::Future const&) + 0xb4 (0x7f6e480b3764 in /work2/kurtamohler/development/pytorch-storage-virtualization/torch/lib/libtorch_cpu.so)
frame #4: torch::distributed::rpc::callback::confirmPendingUser(c10::ivalue::Future const&, torch::distributed::rpc::GloballyUniqueId const&) + 0x10f (0x7f6e480abcdf in /work2/kurtamohler/development/pytorch-storage-virtualization/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x977ffa (0x7f6e4c03fffa in /work2/kurtamohler/development/pytorch-storage-virtualization/torch/lib/libtorch_python.so)
frame #6: void c10::ivalue::Future::invokeCallback<std::function<void (c10::ivalue::Future&)> >(std::function<void (c10::ivalue::Future&)>) + 0x192 (0x7f6e4bd03a92 in /work2/kurtamohler/development/pytorch-storage-virtualization/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0xf506b3 (0x7f6e4586c6b3 in /work2/kurtamohler/development/pytorch-storage-virtualization/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x37a7728 (0x7f6e480c3728 in /work2/kurtamohler/development/pytorch-storage-virtualization/torch/lib/libtorch_cpu.so)
frame #9: c10::ThreadPool::main_loop(unsigned long) + 0x285 (0x7f6e3bb86215 in /work2/kurtamohler/development/pytorch-storage-virtualization/torch/lib/libc10.so)
frame #10: <unknown function> + 0xcc9d4 (0x7f6e57c1b9d4 in /home/kurtamohler/.conda/envs/pytorch-storage-virt/lib/libstdc++.so.6)
frame #11: <unknown function> + 0x76db (0x7f6e777e56db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #12: clone + 0x3f (0x7f6e76b6161f in /lib/x86_64-linux-gnu/libc.so.6)
```

</details>

I get this same error whether I try to send a tensor, typed storage, or untyped storage. Also, I get the same error on master. I am able to send a native Python serializable type, like a `list` without error.

I also tried setting the world size to 1 and send to `worker0` instead, and only run the `worker0.py` script. I get this error if I try to send either a tensor or typed storage:

<details>
<summary>click to expand/collapse</summary>

```
On WorkerInfo(id=0, name=worker0):
AttributeError("type object 'torch.storage._TypedStorage' has no attribute '_new_shared_fd' Default RPC pickler does not serialize\n            function code. Ensure that UDFs are defined on both caller and\n            callee modules.")
Traceback (most recent call last):
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/distributed/rpc/internal.py", line 203, in _run_function
    raise python_udf
AttributeError: type object 'torch.storage._TypedStorage' has no attribute '_new_shared_fd' Default RPC pickler does not serialize
            function code. Ensure that UDFs are defined on both caller and
            callee modules.

Traceback (most recent call last):
  File "/work2/kurtamohler/development/pytorch-perf-test-scripts/rpc/worker0.py", line 19, in <module>
    print(rref.to_here())
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/distributed/rpc/internal.py", line 218, in _handle_exception
    raise result.exception_type(result.msg.encode("utf-8").decode("unicode_escape"))
AttributeError: On WorkerInfo(id=0, name=worker0):
AttributeError("type object 'torch.storage._TypedStorage' has no attribute '_new_shared_fd' Default RPC pickler does not serialize
            function code. Ensure that UDFs are defined on both caller and
            callee modules.")
Traceback (most recent call last):
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/distributed/rpc/internal.py", line 203, in _run_function
    raise python_udf
AttributeError: type object 'torch.storage._TypedStorage' has no attribute '_new_shared_fd' Default RPC pickler does not serialize
            function code. Ensure that UDFs are defined on both caller and
            callee modules.
```

</details>

But it works if I send an untyped storage. And again, the behavior is basically the same on master.

It seems like these are probably genuine issues, but again, they don't seem to be introduced by this PR, and I still haven't been able to reproduce the one you posted.

Can you see anything obvious that I'm doing wrong? Or any extra details that might help?

**Comment by ezyang** [comment]
digest received was wrong sounds like there's a problem in the overall multiprocessing setup (but I'm not terribly familiar with this API so I'm not sure how to fix it)

**Comment by ezyang** [comment]
It looks like the missing ingredient was:

```
torch.multiprocessing.set_sharing_strategy("file_system")
```

without it, indeed the test fails. Here is now a complete test, and I also fixed your auth problem (you have to spawn the processes from the same parent process or auth will fail)

```
1	
import torch
import torch.distributed.rpc as rpc
from torch.distributed.rpc.api import _use_rpc_pickler
from utils import ShareMemoryRPCPickler, passthrough
import torch.multiprocessing as mp
import copyreg
import torch
import torch.multiprocessing.reductions as TorchMpReductions
from torch.distributed.rpc.internal import _InternalRPCPickler
from torch.nn import Linear
from torch import multiprocessing, nn


multiprocessing.set_sharing_strategy("file_system")

class ShareMemoryRPCPickler(_InternalRPCPickler):
    def __init__(self) -> None:
        super().__init__()
        self._dispatch_table
        # pyre-fixme[4]: Attribute must be annotated.
        self._dispatch_table = copyreg.dispatch_table.copy()

        for t in torch._storage_classes:
            self._dispatch_table[t] = TorchMpReductions.reduce_storage

        for t in torch._tensor_classes:
            self._dispatch_table[t] = TorchMpReductions.reduce_tensor
        self._dispatch_table[torch.Tensor] = TorchMpReductions.reduce_tensor
        self._dispatch_table[
            torch.nn.parameter.Parameter
        ] = TorchMpReductions.reduce_tensor

def worker_loop(a):
    rpc.init_rpc('worker1', rank=1, world_size=2)
    rpc.shutdown()

def _flatten_parameter(parameters):
    r"""
    Flatten the module parameters into a 1D tensor 
    """
    return torch.cat([p.reshape(-1) for p in parameters])

def worker_fn(m):
    return _flatten_parameter(m.parameters())

if __name__ == '__main__':
    r = mp.spawn(
        worker_loop,
        join=False
        )

    try:
        with _use_rpc_pickler(ShareMemoryRPCPickler()):
            rpc.init_rpc(
                'worker0',
                rank=0,
                world_size=2,
            )
            m = Linear(1, 2)
            m.share_memory()
            rref = rpc.remote(
                'worker1',
                worker_fn,
                args=(
                    m,
                )
            )
            print(rref.to_here())
    finally:
        rpc.shutdown()
        r.join()
```

run as

```
MASTER_ADDR=localhost MASTER_PORT=29500 python worker0.py
```

I get this on master

```
(/home/ezyang/local/pytorch-tmp-env) [ezyang@devvm066.ash0 ~/local/labs] MASTER_ADDR=localhost MASTER_PORT=29500 python worker0.py  
tensor([-0.6383,  0.2935,  0.6883, -0.9899], requires_grad=True)
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f15538914c0>
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/data/users/ezyang/pytorch-tmp/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <function StorageWeakRef.__del__ at 0x7f15538914c0>
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/data/users/ezyang/pytorch-tmp/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
(/home/ezyang/local/pytorch-tmp-env) [ezyang@devvm066.ash0 ~/local/labs] echo $?
0
```

and I'm guessing it fails on this PR

**Comment by ezyang** [comment]
Confirmed it fails on the PR and not on master.

**Comment by kurtamohler** [comment]
Awesome, thanks @ezyang! I'll get started fixing it

**Comment by ezyang** [comment]
It's possible I need to patch the FB, code, it just wasn't obvious to me who was in the wrong. It's probably the RPC picklers fault though haha

**Comment by kurtamohler** [comment]
There's definitely a problem with the multiprocessing pickler when the sharing strategy is "file_system". When a `_TypedStorage` is serialized, the deserialization step is always creating an `_UntypedStorage`. So when that's passed to the `rebuild_tensor` function, we get an `AttributeError` because that function expects a `_TypedStorage` and it's trying access the `dtype` attribute. I'll try to fix it today or this weekend, but if I can't, just FYI, I'm on PTO next week

**Comment by ezyang** [comment]
This has been in the works for a while, what's a little more time :o)

**Comment by kurtamohler** [comment]
Ok I think I've fixed the issue. At least the `AttributeError` for `storage.dtype` within `rebuild_tensor` doesn't happen anymore.

The other error (`AttributeError: 'NoneType' object has no attribute '_free_weak_ref'`), which was also showing up in master, is still happening. I don't 100% understand what's going on with that. It looks like `_TypedStorage._free_weak_ref()` is getting called after the `torch` module is deleted at the end of the script, and I'm not sure why

**Comment by ezyang** [comment]
I filed a tracking issue for it at. https://github.com/pytorch/pytorch/issues/74016 We don't have to fix it here.

**Comment by ezyang** [comment]
Bruh internal tests are passing. Let's GOOOO

**Pull request closed without merging**
