### PR TITLE
[FlexAttention] Fix max-autotune bug with captured buffer grads

### PR DESCRIPTION
**Pull request by drisspg**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #141531

# Summary
Fix tensor argument ordering for autotuning flex attention, change how we enabled scatters codegen for triton. We used to go through the existing store_output triton codegen but now we just short circuit and generate the correct expression earlier on.

This enables us to instead of relying on arg.python_defs to thread arguments through via input_buffers we can instead reuse the exact same mutated buffer infra as we did for multiple outputs before. 

Test cases added for both default and max-autotune-no-cudagraphs modes.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @Chillee @yanboliang @BoyuanFeng

### CODE REVIEW

**Review by Chillee — APPROVED** [review]

**Comment by drisspg** [comment]
The problem here is that we are passing in the node an input That in the non-autotune case ends up being the last buffer argument while generating the args in max-autotune it ends up being the second to last because we have an explicit output node. I need to figure out how to reorder the output nodes from the kernel.

**Review by Chillee — APPROVED** [review]
Could we add a couple more tests? Specifically I'd like a test with multiple captured grads.

**Comment by drisspg** [comment]
Yeah, we have this test for default compile, but can add for autotuning

**Pull request closed without merging**
