### PR TITLE
[BatchNorm update]

### PR DESCRIPTION
**Pull request by jjsjann123**
Removing in-place operator for num_batches_tracked increment. The in-place
operator used here turns out to block many optimization opportunities due to
alias assumption for inputs.

### CODE REVIEW

**Comment by jjsjann123** [comment]
Progressive improvements on BN to unblock graph fusion across BN layers used in optimization passes.

**Comment by jjsjann123** [comment]
cc'ing @ngimel @csarofeen @ptrblck

**Comment by jjsjann123** [comment]
Error doesn't seem to be related. Feel free to point me to where I should look at.

**Comment by gchanan** [comment]
@ngimel: can you approve the PR before merging? :).

**Pull request closed without merging**
