### PR TITLE
[ci] some improvements to buck workflow

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #78287

- Don't have special-cased standalone workflow but use the same reusable workflow
scheme that everything else does.
- Add retries to network calls.

### CODE REVIEW

**Comment by suo** [comment]
There are other issues with this workflow; it installs unpinned versions of all conda dependencies instead of building a docker image like our other workflows.

@kit1980 you are listed as the original author; is there are specific reason why we are not using a docker image here?

**Review by kit1980 — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
