### PR TITLE
Update doc copyrights to 2024

### LINKED ISSUE #138630: Documentation copyright year is 2023
### 📚 The doc issue

https://pytorch.org/docs/stable/index.html, etc.:
```
© Copyright 2023, PyTorch Contributors.
```

### Suggest a potential alternative/fix

_No response_

### PR DESCRIPTION
**Pull request by malfet**
Spiritual successor of https://github.com/pytorch/pytorch/pull/119413 + CPP docs copyright update as well
Fixes https://github.com/pytorch/pytorch/issues/138630

cc @svekars @brycebortree @sekyondaMeta

### CODE REVIEW

**Review by atalman — APPROVED** [review]
lgtm

**Comment by svekars** [comment]
There was a PR for this back in Feb FWIW: https://github.com/pytorch/pytorch/pull/119413

**Comment by malfet** [comment]
> There was a PR for this back in Feb FWIW: #119413

You should have pinged more people about it

**Pull request closed without merging**
