### PR TITLE
[Inductor][Quant] Change the schema of QLinear Binary

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #129470
* #129221
* #129220
* #129103
* __->__ #129049
* #129048
* #128825

**Summary**
We change the schema of QLinear Binary, so it will be easier to enable the corresponding gemm template. 

- Extra input of binary post-op is a tensor which needs to be an input node of autotuning, we need to move it at front of `output_scale` which is a scalar.
- We also move it at front of `bias`, since `bias` is optional tensor for this fusion, but `other` is a must to have for linear binary fusion.

**Test Plan**
```
python -u -m pytest -s -v test/quantization/core/test_quantized_op.py -k qlinear
python -u -m pytest -s -v test/inductor/test_mkldnn_pattern_matcher.py -k qlinear
```

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
Please elaborate on why it is easier to be handled by template?

**Comment by leslie-fang-intel** [comment]
> Please elaborate on why it is easier to be handled by template?

Thanks for the comment. Add the elaboration in this PR summary.

**Comment by leslie-fang-intel** [comment]
Hi @jansel, this PR may also need your approval.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
