### PR TITLE
Package `torch/*.pyi` type hints

### PR DESCRIPTION
**Pull request by lkct**
Including `torch._VF` and `torch.return_types`

These are generated by:
https://github.com/pytorch/pytorch/blob/4003e96ca1e54df58772870eb779c66e4b6e51fb/tools/pyi/gen_pyi.py#L1139-L1155

Ref #99541

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by Skylion007 — COMMENTED** [review]
Wait, I couldn't find the .pyi this is referring to in the git repo, are they autogenerated?

**Review by Skylion007 — CHANGES_REQUESTED** [review]
Hold on, both the files in the comment are .py files already, am I missing something? Not sure what additional files are captured by this glob?

**Comment by lkct** [comment]
> Wait, I couldn't find the .pyi this is referring to in the git repo, are they autogenerated?

Updated comments in first floor.

**Review by Skylion007 — APPROVED** [review]

**Comment by lkct** [comment]
Just to note: I took a look at the artifacts. The two `torch/*.pyi` files are packed as expected.

**Pull request closed without merging**
