### PR TITLE
[ROCm] Install Composable Kernel for ROCm CI

### PR DESCRIPTION
**Pull request by tenpercent**
In order to run the unit test `tests/inductor/test_ck_backend.py` to test the correctness of the Composable Kernel backend for GEMM max autotune in Inductor (introduced in #125453), Composable Kernel includes and library examples need to be pip-installed. 

This PR enables running the unit test in ROCm CI

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jeffdaily** [comment]
Is there a reason we aren't using git submodule to add ck to pytorch/third_party?

**Comment by tenpercent** [comment]
> Is there a reason we aren't using git submodule to add ck to pytorch/third_party?

In order to avoid the issue of CK backend not available when pytorch is installed with pip

https://github.com/pytorch/pytorch/pull/125453#issuecomment-2121686999
https://github.com/pytorch/pytorch/pull/125453#issuecomment-2125641755

**Comment by jeffdaily** [comment]
This PR looks like it will fix the CI.  Long-term I think CK will be a git submodule, but that doesn't fix your problem of a pip install of torch won't get the third_party/composable_kernel as part of it.  So you'll still need to install CK separately.  

How does the cutlass inductor backend handle this situation?

**Comment by petrex** [comment]
maybe I am overthinking... but what if we need different branch of CK, say for some new features, how do we handle that?

**Comment by tenpercent** [comment]
> maybe I am overthinking... but what if we need different branch of CK, say for some new features, how do we handle that?

`pip install git+https://github.com/rocm/composable_kernel@branch-or-hash` should do the job

**Comment by petrex** [comment]
just notice we have CK include path in the makefile... so did we have CK as submodule before??https://github.com/pytorch/pytorch/blob/b6f781e433f1de045ba3ee9c671a135fde049a44/aten/src/ATen/CMakeLists.txt#L310

**Comment by tenpercent** [comment]
> just notice we have CK include path in the makefile... so did we have CK as submodule before??
> 
> https://github.com/pytorch/pytorch/blob/b6f781e433f1de045ba3ee9c671a135fde049a44/aten/src/ATen/CMakeLists.txt#L310

It looks like it got added in #115981, but I don't see the PR adding CK as submodule

**Comment by tenpercent** [comment]
> This PR looks like it will fix the CI. Long-term I think CK will be a git submodule, but that doesn't fix your problem of a pip install of torch won't get the third_party/composable_kernel as part of it. So you'll still need to install CK separately.
> 
> How does the cutlass inductor backend handle this situation?

I think CUTLASS does something similar with pip-ifying the repository
https://pypi.org/project/nvidia-cutlass/

**Comment by tenpercent** [comment]
Tests are failing but failures look unrelated, so rebasing on fresh main

**Pull request closed without merging**
