### PR TITLE
[inductor] Add retry after benchmark test fails on CI

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #90808

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Looks fine if you are to add a high-pri issue to fix that before PT-2.0 release (imo its a pretty bad user story for inductor to fail 50% of times)

**Comment by desertfire** [comment]
> Looks fine if you are to add a high-pri issue to fix that before PT-2.0 release (imo its a pretty bad user story for inductor to fail 50% of times)

There is https://github.com/pytorch/torchdynamo/issues/1989 I am investigating. I will hold this commit, waiting to see the stats from the previous PR (running inductor shards after every commit). If the `compile_fx raised KeyError: 'cubin'` problem persists, I will use this PR as a temp fix and  continue to fix the root cause.

**Pull request closed without merging**
