### PR TITLE
[aot_inductor] move CudaWrapperCodeGen into a separate file

### PR DESCRIPTION
**Pull request by chenyang78**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #119491
* __->__ #119448

wrapper.py is getting more complex. Let's first split it
into smaller pieces. Will have another PR to move CppWrapperCodeGen.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by desertfire — APPROVED** [review]
I would recommend take one step further by doing some class/file renaming. They are really cpp_wrapper_cpu and cpp_wrapper_cuda.

**Comment by chenyang78** [comment]
> I would recommend take one step further by doing some class/file renaming. They are really cpp_wrapper_cpu and cpp_wrapper_cuda.

Good point. I will rename the files in this PR and change class names in separate ones. Thanks.

**Comment by jeffdaily** [comment]
Pretty sure this PR broke ROCm.

https://hud.pytorch.org/pytorch/pytorch/commit/0597dab523c0a341e136452a8f723f12700164c0

**Comment by DanilBaibak** [comment]
Hi @chenyang78! Sorry, I need to revert your PR because it broke ROCm. Here you can find more information about the issue - https://hud.pytorch.org/pytorch/pytorch/commit/0597dab523c0a341e136452a8f723f12700164c0

**Comment by chenyang78** [comment]
> Hi @chenyang78! Sorry, I need to revert your PR because it broke ROCm. Here you can find more information about the issue - https://hud.pytorch.org/pytorch/pytorch/commit/0597dab523c0a341e136452a8f723f12700164c0

No problem. Thanks for reverting it, @DanilBaibak. I will look into it. Looks like AMD CI is not enabled by default? Do you know how I could run my diffs against AMD CI? Thanks!

**Comment by desertfire** [comment]
> > Hi @chenyang78! Sorry, I need to revert your PR because it broke ROCm. Here you can find more information about the issue - [hud.pytorch.org/pytorch/pytorch/commit/0597dab523c0a341e136452a8f723f12700164c0](https://hud.pytorch.org/pytorch/pytorch/commit/0597dab523c0a341e136452a8f723f12700164c0)
> 
> No problem. Thanks for reverting it, @DanilBaibak. I will look into it. Looks like AMD CI is not enabled by default? Do you know how I could run my diffs against AMD CI? Thanks!

Adding the `ciflow/rocm` label will do it.

**Comment by jeffdaily** [comment]
> > > Hi @chenyang78! Sorry, I need to revert your PR because it broke ROCm. Here you can find more information about the issue - [hud.pytorch.org/pytorch/pytorch/commit/0597dab523c0a341e136452a8f723f12700164c0](https://hud.pytorch.org/pytorch/pytorch/commit/0597dab523c0a341e136452a8f723f12700164c0)
> > 
> > 
> > No problem. Thanks for reverting it, @DanilBaibak. I will look into it. Looks like AMD CI is not enabled by default? Do you know how I could run my diffs against AMD CI? Thanks!
> 
> Adding the `ciflow/rocm` label will do it.

We have a subset of ROCm tests that are part of all PRs, but it doesn't have great coverage of inductor.  Our CI resources are too limited to run all ROCm tests with every PR.  For the time being, if you have further inductor PRs, add the ciflow/rocm label.  Given our resource constraints, you might end up waiting longer for a CI signal but perhaps that is still better than having to revert later.

**Comment by chenyang78** [comment]
> > > > Hi @chenyang78! Sorry, I need to revert your PR because it broke ROCm. Here you can find more information about the issue - [hud.pytorch.org/pytorch/pytorch/commit/0597dab523c0a341e136452a8f723f12700164c0](https://hud.pytorch.org/pytorch/pytorch/commit/0597dab523c0a341e136452a8f723f12700164c0)
> > > 
> > > 
> > > No problem. Thanks for reverting it, @DanilBaibak. I will look into it. Looks like AMD CI is not enabled by default? Do you know how I could run my diffs against AMD CI? Thanks!
> > 
> > 
> > Adding the `ciflow/rocm` label will do it.
> 
> We have a subset of ROCm tests that are part of all PRs, but it doesn't have great coverage of inductor. Our CI resources are too limited to run all ROCm tests with every PR. For the time being, if you have further inductor PRs, add the ciflow/rocm label. Given our resource constraints, you might end up waiting longer for a CI signal but perhaps that is still better than having to revert later.

Thanks for the instruction, @jeffdaily @desertfire

**Comment by chenyang78** [comment]
Closing it as the move was committed in another PR.

**Pull request closed without merging**
