### PR TITLE
Enable UFMT on test/quantization/core

### PR DESCRIPTION
**Pull request by hipudding**
Part of: https://github.com/pytorch/pytorch/issues/123062

1. delete test/quantization/core in `.lintrunner.toml`
2. execute lintrunner:
```shell
lintrunner -a --take UFMT --all-files

ok No lint issues.
Successfully applied all patches.
```

### CODE REVIEW

**Review by kadeng — APPROVED** [review]
Looks good to me, thanks for your contribution. I assume there are no functional changes. I quickly scanned over the changed lines and did not see any changes beyond formatting and those in .lintrunner.toml

**Comment by kadeng** [comment]
@albanD @seemethere would it make sense to skip the PR LOC limit for this PR which is just applying formatting to thousands of lines? ( Assuming all other tests pass, of course )

**Comment by hipudding** [comment]
@kadeng Thanks for your review. Could you please re-run ci jobs? Fix some issue caused by UFMT format just now.
Some test cases are not stable, but it seems not related with this PR.

**Comment by albanD** [comment]
I am happy to skip if this was generated automatically as long as the reviewers are happy with it.
Otherwise, doing it one file at a time sounds like the way to go.

**Comment by hipudding** [comment]
> I am happy to skip if this was generated automatically as long as the reviewers are happy with it. Otherwise, doing it one file at a time sounds like the way to go.

Thanks for your review. Most of the change is made by lintrunner. I add the second commit to fix lint issue caused by UFMT format.
I don't think any logic will be affected, and I think the failing test case is not related to this PR. Could you please merge this PR? Thanks.

**Comment by kadeng** [comment]
> > I am happy to skip if this was generated automatically as long as the reviewers are happy with it. Otherwise, doing it one file at a time sounds like the way to go.
> 
> Thanks for your review. Most of the change is made by lintrunner. I add the second commit to fix lint issue caused by UFMT format. I don't think any logic will be affected, and I think the failing test case is not related to this PR. Could you please merge this PR? Thanks.

I agree that the tests are most likely unrelated, but it would be pretty dangerous to merge right away. Even lintrunner can cause issues, for example by reordering imports or removing imports that are called through non-standard mechanisms ( say via getattr or such ). So I would re-run the tests and see where that gets us..

**Comment by kadeng** [comment]
Tests failed three times now. I fear this likely has to be rebased and checked, we can't merge this as-is. Since a vanilla rebase is likely to run into a merge conflict, I would propose to reapply the changes file by file as @albanD also suggested to a recent checkout. If problems occur they are easier to pinpoint.

What makes these kinds of diffs hard to handle is that they can easily trigger large-scale edit conflicts, so doing it file by file is hopefully easier to land.

**Comment by hipudding** [comment]
> Tests failed three times now. I fear this likely has to be rebased and checked, we can't merge this as-is. Since a vanilla rebase is likely to run into a merge conflict, I would propose to reapply the changes file by file as @albanD also suggested to a recent checkout. If problems occur they are easier to pinpoint.
> 
> What makes these kinds of diffs hard to handle is that they can easily trigger large-scale edit conflicts, so doing it file by file is hopefully easier to land.

Thanks, I will.

**Pull request closed without merging**
