### PR TITLE
[ROCm] Move ROCm CI build to python 3.8 version

### PR DESCRIPTION
**Pull request by pruthvistony**
Currently it is python 3.7 want to upgrade to python 3.8

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### CODE REVIEW

**Comment by malfet** [comment]
Created pytorch-linux-focal-rocm5.2-py3.8 and pytorch-linux-focal-rocm5.1-py3.8 ecr containers

**Comment by pruthvistony** [comment]
> * linux-bionic-cuda11.7-py3.7-gcc7-debug / test (default, 3, 4, linux.4xlarge.nvidia.gpu)

All the failing jobs are due to UT failure 
======================================================================
ERROR [0.002s]: test_nn_functional_group_norm (__main__.TestFunctionalTracing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_fx.py", line 4075, in functional_test
    symbolic_trace(fn)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 1070, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/functional.py", line 2523, in group_norm
    _verify_batch_size([input.size(0) * input.size(1) // num_groups, num_groups] + list(input.size()[2:]))
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/proxy.py", line 274, in __iter__
    return self.tracer.iter(self)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/proxy.py", line 183, in iter
    raise TraceError('Proxy object cannot be iterated. This can be '
torch.fx.proxy.TraceError: Proxy object cannot be iterated. This can be attempted when the Proxy is used in a loop or as a *args or **kwargs function argument. See the torch.fx docs on pytorch.org for a more detailed explanation of what types of control flow can be traced, and check out the Proxy docstring for help troubleshooting Proxy iteration errors


This change is ROCm specific and NOT related to above cuda failures.

**Review by malfet — APPROVED** [review]

**Comment by pruthvistony** [comment]
@seemethere @malfet ,
See the below failures in few CUDA jobs
======================================================================
ERROR [0.003s]: test_nn_functional_group_norm (__main__.TestFunctionalTracing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/test_fx.py", line 4075, in functional_test
    symbolic_trace(fn)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 1070, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/functional.py", line 2523, in group_norm
    _verify_batch_size([input.size(0) * input.size(1) // num_groups, num_groups] + list(input.size()[2:]))
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/proxy.py", line 274, in __iter__
    return self.tracer.iter(self)
  File "/opt/conda/lib/python3.10/site-packages/torch/fx/proxy.py", line 183, in iter
    raise TraceError('Proxy object cannot be iterated. This can be '
torch.fx.proxy.TraceError: Proxy object cannot be iterated. This can be attempted when the Proxy is used in a loop or as a *args or **kwargs function argument. See the torch.fx docs on pytorch.org for a more detailed explanation of what types of control flow can be traced, and check out the Proxy docstring for help troubleshooting Proxy iteration errors

----------------------------------------------------------------------
Ran 1031 tests in 4.241s

As I understand this PR triggers a rebuild of all CI images for ROCm but not sure how CUDA image is changing, can you please help on why the CUDA images are failing. Checking on the error it is related to python version (https://github.com/pytorch/pytorch/issues/60069).

**Comment by huydhn** [comment]
> # See the below failures in few CUDA jobs
> ## ERROR [0.003s]: test_nn_functional_group_norm (**main**.TestFunctionalTracing)
> Traceback (most recent call last): File "/var/lib/jenkins/workspace/test/test_fx.py", line 4075, in functional_test symbolic_trace(fn) File "/opt/conda/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 1070, in symbolic_trace graph = tracer.trace(root, concrete_args) File "/opt/conda/lib/python3.10/site-packages/torch/fx/_symbolic_trace.py", line 739, in trace (self.create_arg(fn(*args)),), File "/opt/conda/lib/python3.10/site-packages/torch/nn/functional.py", line 2523, in group_norm _verify_batch_size([input.size(0) * input.size(1) // num_groups, num_groups] + list(input.size()[2:])) File "/opt/conda/lib/python3.10/site-packages/torch/fx/proxy.py", line 274, in **iter** return self.tracer.iter(self) File "/opt/conda/lib/python3.10/site-packages/torch/fx/proxy.py", line 183, in iter raise TraceError('Proxy object cannot be iterated. This can be ' torch.fx.proxy.TraceError: Proxy object cannot be iterated. This can be attempted when the Proxy is used in a loop or as a *args or **kwargs function argument. See the torch.fx docs on pytorch.org for a more detailed explanation of what types of control flow can be traced, and check out the Proxy docstring for help troubleshooting Proxy iteration errors
> 
> As I understand this PR triggers a rebuild of all CI images for ROCm but not sure how CUDA image is changing, can you please help on why the CUDA images are failing. Checking on the error it is related to python version (#60069).

Surprisingly, I'm also seeing exactly the same failure on my "benign" PR https://github.com/pytorch/pytorch/pull/86993 to update docker image. So it's not a coincidence, let me try to dig a bit deeper to understand what's going on here

**Comment by huydhn** [comment]
Rebase the PR works for me https://github.com/pytorch/pytorch/pull/86993. So I suspect some unrelated test failures (either flaky or they have been fixed)

**Pull request closed without merging**
