### PR TITLE
Prefer at::detail::empty_cuda to the native function

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #71640
* __->__ #70618
* #70617

`at::native::empty_cuda` is called directly in some places to avoid
the extra dispatch, however it's missing features like device guards and a
`TensorOptions` overload.

Differential Revision: [D33623676](https://our.internmc.facebook.com/intern/diff/D33623676)

### CODE REVIEW

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33623676).

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33623676).

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33623676).

**Review by ngimel — APPROVED** [review]
This is a cool stack! Can you please post instruction count benchmarks for empty/empty_strided calls and some op using structured kernels comparing master prior to this stack and after, so that we know perf impact? There are some benchmarks on previous PRs, but it'll be good to see total impact.

**Comment by peterbell10** [comment]
I collected some numbers and saw improvements in all cases except `empty_cpu`. I've tracked the regression down to `check_size_nonnegative` not being an `inline` function so have a new PR fixing it.  

| Function            | Device | 7b9fff9 | This PR |
|---------------------|--------|--------:|--------:|
| `at::empty`         | CPU    |   77389 |    7792 |
| `at::empty`         | CUDA   | 291887  | 213557  |
| `at::empty_strided` | CPU    |   89361 |   82191 |
| `at::empty_strided` | CUDA   | 331341  | 217311  |
| `at::add`           | CPU    | 219737  | 220067  |
| `at::add`           | CUDA   | 729884  | 650174  |

**Comment by ngimel** [comment]
Cool, is `7792` for this stack cpu a typo and should be 77K-something? How many repeats is your benchmark script using, can you maybe post it for future reference?

**Comment by peterbell10** [comment]
Yes, that was a typo. edited to 77929.

empty script:
```
import torch
from torch.utils.benchmark import Timer
import timeit
timer = Timer(
    "at::empty({2048}, at::kCPU);",
    language="c++",
    timer=timeit.default_timer)
stats = timer.collect_callgrind(number=30, repeats=3)
counts = stats[1].as_standardized().stats(inclusive=False)
```
empty_strided script:
```
import torch
from torch.utils.benchmark import Timer
import timeit
timer = Timer(
    "at::empty({1024}, {2}, at::kCPU);",
    language="c++",
    timer=timeit.default_timer)
stats = timer.collect_callgrind(number=30, repeats=3)
counts = stats[1].as_standardized().stats(inclusive=False)
```

add script:
```
import torch
from torch.utils.benchmark import Timer
import timeit
timer = Timer(
    "at::add(a, a);",
    setup="at::Tensor a = at::ones({2048}, at::kCPU);",
    language="c++",
    timer=timeit.default_timer)
stats = timer.collect_callgrind(number=30, repeats=3)
counts = stats[1].as_standardized().stats(inclusive=False)
```

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33623676).

**Pull request closed without merging**
