### PR TITLE
[ROCm] Remove installation of ca-certificates and apt-transport-https in test.sh

### PR DESCRIPTION
**Pull request by iotamudelta**
These packages are now part of the base docker image.

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by iotamudelta** [comment]
@malfet works now, failing node was removed

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
can you install the rest in the base image too? :)

**Comment by iotamudelta** [comment]
@ezyang - absolutely. I also want to clean the stages up as you requested.

**Comment by iotamudelta** [comment]
however, that'll require a respin of the docker images... ;-)

**Pull request closed without merging**
