### PR TITLE
[primtorch] Added `native_group_norm` decomp

### PR DESCRIPTION
**Pull request by Chillee**
cc: @jansel @bertmaher 

More or less identical in spirit to the layer norm and batch norm ones.

One annoying thing about all 3 of these is that layer_norm has slightly different `mean/var` semantics than batch norm and group norm. After normalization, `layer_norm` keeps them unsqueezed (so they're something like [1, 5, 1, 1]) while batch norm and group norm squeeze out the 1-dims.

### CODE REVIEW

**Review by bertmaher — APPROVED** [review]

**Comment by Chillee** [comment]
There seems to be an issue with registering a meta decomposition for operators that have a "Math" `CompositeImplicitAutograd` defined on them.

```
RuntimeError: 0 INTERNAL ASSERT FAILED at "/scratch/chilli/fresh/pytorch/aten/src/ATen/core/boxing/KernelFunction.cpp":31, please report a bug to PyTorch. aten::native_group_norm has kernels registered to both CompositeImplicitAutograd and a backend mapped to AutogradOther. This makes the backend kernel unreachable; the dispatcher will always prefer the CompositeImplicitAutograd lowering (see Note [Ambiguity in AutogradOther kernel]). If you want to override CompositeImplicitAutograd, please open an issue to request a dedicated Autograd dispatch key for the backend.
If you only want to run inference instead of training, add `c10::InferenceMode mode;` before model.forward(). Note this guard is only available in C++ but not Python at present.
```

cc: @ezyang

**Comment by ezyang** [comment]
> There seems to be an issue with registering a meta decomposition for operators that have a "Math" CompositeImplicitAutograd defined on them.

I ran into a similar problem with addr. My current thinking is we should just get rid of all of these.

**Comment by Chillee** [comment]
@ngimel mentioned that XLA uses them for generating backwards passes?

**Comment by ngimel** [comment]
That was the original intent for math dispatch, but I don't know if it ever happened for real.

**Comment by ezyang** [comment]
The thing is that we have backward formulas, and if the backward functions have decompositions I can't think of any reason XLA wouldn't want to use those.

**Pull request closed without merging**
