### PR TITLE
Don't uselessly recompute axiom dict every static eval call

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135429

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by isuruf — APPROVED** [review]

**Comment by malfet** [comment]
@ezyang do you want to `merge -f` it if you are confident it'll fix the problem? (I'm still not sure if it was caused by this or previous PR in the stack"

**Comment by ezyang** [comment]
Notes on the executorch failure: It's whack. This is what the logs should be:

```
INFO:torch.fx.experimental.symbolic_shapes:create_symbol s1 = 2 for __meta_utils_unknown_tensor105.size()[0] [2, int_oo] (executorch/exir/pass_base.py:238 in make_val), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="s1"
INFO:torch.fx.experimental.symbolic_shapes:create_symbol s2 = 3 for __meta_utils_unknown_tensor105.size()[2] [2, int_oo] (executorch/exir/pass_base.py:238 in make_val), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="s2"
INFO:torch.fx.experimental.symbolic_shapes:set_replacement s1 = 2 (range_refined_to_singleton) VR[2, 2]
INFO:torch.fx.experimental.symbolic_shapes:eval Eq(2, s1) [guard added] (_subclasses/fake_impls.py:715 in conv), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Eq(2, s1)"
INFO:torch.fx.experimental.symbolic_shapes:eval 6 >= s2 [guard added] (_subclasses/fake_impls.py:715 in conv), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="6 >= s2"
INFO:torch.fx.experimental.symbolic_shapes:eval Ne(7 - s2, 1) [guard added] (_prims_common/__init__.py:457 in compute_elementwise_output_logical_to_physical_perm), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Ne(7 - s2, 1)"
INFO:torch.fx.experimental.symbolic_shapes:eval Ne(-2*s0*s2 + 14*s0, 0) [guard added] (_prims_common/__init__.py:454 in compute_elementwise_output_logical_to_physical_perm), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Ne(-2*s0*s2 + 14*s0, 0)"
INFO:torch.fx.experimental.symbolic_shapes:eval Ne(7 - s2, 1) [guard added] (_prims/__init__.py:1285 in _broadcast_in_dim_meta), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Ne(7 - s2, 1)"
INFO:torch.fx.experimental.symbolic_shapes:eval 9 - s2 >= s2 [guard added] (_subclasses/fake_impls.py:715 in conv), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="9 - s2 >= s2"
INFO:torch.fx.experimental.symbolic_shapes:eval Ne(-2*s0*s2 + 14*s0, 0) [guard added] (_subclasses/fake_impls.py:715 in conv), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Ne(-2*s0*s2 + 14*s0, 0)"
INFO:torch.fx.experimental.symbolic_shapes:runtime_assert 10 - 2*s2 >= 0 [guard added] (_refs/__init__.py:4758 in new_empty), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="10 - 2*s2 >= 0"
INFO:torch.fx.experimental.symbolic_shapes:eval Ne(10 - 2*s2, 0) [guard added] (_meta_registrations.py:2273 in meta_conv), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Ne(10 - 2*s2, 0)"
INFO:torch.fx.experimental.symbolic_shapes:eval 1 < 20 - 4*s2 [guard added] (_meta_registrations.py:2273 in meta_conv), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="1 < 20 - 4*s2"
INFO:torch.fx.experimental.symbolic_shapes:eval Ne(-4*s0*s2 + 20*s0, 0) [guard added] (_prims_common/__init__.py:454 in compute_elementwise_output_logical_to_physical_perm), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Ne(-4*s0*s2 + 20*s0, 0)"
INFO:torch.fx.experimental.symbolic_shapes:runtime_assert Eq(7 - s2, 10 - 2*s2) [guard added] (_subclasses/fake_impls.py:817 in infer_size), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Eq(7 - s2, 10 - 2*s2)"
INFO:torch.fx.experimental.symbolic_shapes:set_replacement s2 = 3 (range_refined_to_singleton) VR[3, 3]
INFO:torch.fx.experimental.symbolic_shapes:eval Eq(s2, 3) [guard added] (executorch/exir/pass_base.py:678 in migrate_meta_val), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Eq(s2, 3)"
E 00:00:17.357053 executorch:method.cpp:941] Output 0 is memory planned, or is a constant. Cannot override         the existing data pointer.
```

after this PR, the logs become

```
INFO:torch.fx.experimental.symbolic_shapes:create_symbol s0 = 8 for __meta_utils_unknown_tensor12.size()[0] [2, int_oo] (utils/_pytree.py:803 in unflatten), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="s0"      
INFO:torch.fx.experimental.symbolic_shapes:create_symbol s1 = 16 for __meta_utils_unknown_tensor12.size()[1] [2, int_oo] (utils/_pytree.py:803 in unf
latten), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="s1"                                                                        INFO:torch.fx.experimental.symbolic_shapes:create_symbol s2 = 32 for __meta_utils_unknown_tensor12.size()[2] [2, int_oo] (utils/_pytree.py:803 in unf
latten), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="s2"       
INFO:torch.fx.experimental.symbolic_shapes:create_symbol s3 = 64 for __meta_utils_unknown_tensor12.size()[3] [2, int_oo] (utils/_pytree.py:803 in unflatten), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="s3"      
INFO:torch.fx.experimental.symbolic_shapes:set_replacement s2 = 32 (range_refined_to_singleton) VR[32, 32]
INFO:torch.fx.experimental.symbolic_shapes:eval Eq(32, s2) [guard added] (<eval_with_key>.560:9 in forward), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Eq(32, s2)"                                                                                                                   
INFO:torch.fx.experimental.symbolic_shapes:create_symbol s1 = 2 for __meta_utils_unknown_tensor105.size()[0] [2, int_oo] (executorch/exir/pass_base.p
y:238 in make_val), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="s1"                                                             INFO:torch.fx.experimental.symbolic_shapes:create_symbol s2 = 3 for __meta_utils_unknown_tensor105.size()[2] [2, int_oo] (executorch/exir/pass_base.p
y:238 in make_val), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_CREATE_SYMBOL="s2"
INFO:torch.fx.experimental.symbolic_shapes:set_replacement s1 = 2 (range_refined_to_singleton) VR[2, 2]                                              INFO:torch.fx.experimental.symbolic_shapes:eval Eq(2, s1) [guard added] (_subclasses/fake_impls.py:715 in conv), for more info run with TORCHDYNAMO_E
XTENDED_DEBUG_GUARD_ADDED="Eq(2, s1)"                               
INFO:torch.fx.experimental.symbolic_shapes:eval 6 >= s2 [guard added] (_subclasses/fake_impls.py:715 in conv), for more info run with TORCHDYNAMO_EXT
ENDED_DEBUG_GUARD_ADDED="6 >= s2"                                         
INFO:torch.fx.experimental.symbolic_shapes:eval Ne(7 - s2, 1) [guard added] (_prims_common/__init__.py:457 in compute_elementwise_output_logical_to_physical_perm), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Ne(7 - s2, 1)"
INFO:torch.fx.experimental.symbolic_shapes:eval Ne(-2*s0*s2 + 14*s0, 0) [guard added] (_prims_common/__init__.py:454 in compute_elementwise_output_lo
gical_to_physical_perm), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Ne(-2*s0*s2 + 14*s0, 0)"                                     INFO:torch.fx.experimental.symbolic_shapes:eval 9 - s2 >= s2 [guard added] (_subclasses/fake_impls.py:715 in conv), for more info run with TORCHDYNAM
O_EXTENDED_DEBUG_GUARD_ADDED="9 - s2 >= s2"                    
INFO:torch.fx.experimental.symbolic_shapes:runtime_assert 10 - 2*s2 >= 0 [guard added] (_refs/__init__.py:4758 in new_empty), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="10 - 2*s2 >= 0"                                                                                              
INFO:torch.fx.experimental.symbolic_shapes:eval Ne(10 - 2*s2, 0) [guard added] (_meta_registrations.py:2273 in meta_conv), for more info run with TOR
CHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Ne(10 - 2*s2, 0)"                                                                                               
INFO:torch.fx.experimental.symbolic_shapes:eval 1 < 20 - 4*s2 [guard added] (_meta_registrations.py:2273 in meta_conv), for more info run with TORCHD
YNAMO_EXTENDED_DEBUG_GUARD_ADDED="1 < 20 - 4*s2"                                                                                                     INFO:torch.fx.experimental.symbolic_shapes:eval Ne(-4*s0*s2 + 20*s0, 0) [guard added] (_prims_common/__init__.py:454 in compute_elementwise_output_lo
gical_to_physical_perm), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Ne(-4*s0*s2 + 20*s0, 0)"
INFO:torch.fx.experimental.symbolic_shapes:runtime_assert Eq(7 - s2, 10 - 2*s2) [guard added] (_subclasses/fake_impls.py:817 in infer_size), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="Eq(7 - s2, 10 - 2*s2)"      
INFO:torch.fx.experimental.symbolic_shapes:eval -2*s0*s2 + 14*s0 >= 2 [guard added] (_prims_common/__init__.py:236 in is_contiguous), for more info r
un with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="-2*s0*s2 + 14*s0 >= 2"                                                                               INFO:torch.fx.experimental.symbolic_shapes:eval -4*s0*s2 + 20*s0 >= 2 [guard added] (_prims_common/__init__.py:236 in is_contiguous), for more info r
un with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="-4*s0*s2 + 20*s0 >= 2"
INFO:torch.fx.experimental.symbolic_shapes:eval 20 - 4*s2 > 2 [guard added] (_prims_common/__init__.py:479 in should_swap), for more info run with TORCHDYNAMO_EXTENDED_DEBUG_GUARD_ADDED="20 - 4*s2 > 2"
```

and then it fails because we never manage the replacement on s2. Strange strange...

https://fb.workplace.com/groups/pytorch.edge.users/permalink/1605864123617208/

**Comment by ezyang** [comment]
gonna chat with @angelayi about the high level pass structure

**Comment by laithsakka** [comment]
looking at this now

**Pull request closed without merging**
