### PR TITLE
[dtensor] enable op db tests by using multithreaded test case

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #92198
* #92197
* #91650
* #91649

Time comparison between using MultithreadedTestCase and MultiProcessTestCase on op db tests is amazing!

using MultiThreadTestCase on a AWS dev node:
```
time pytest test/distributed/_tensor/test_dtensor_ops.py

============= 175 passed, 42 skipped, 397 xfailed in 80.30s (0:01:20) =======

real    1m22.330s
user    1m38.782s
sys     0m18.762s
```
MultiProcessTestCase spends from 40mins to more than 1h, even if using pytest parallel testing tools.

### CODE REVIEW

**Review by XilunWu — APPROVED** [review]
good to see that op db tests are now enabled!! Is there a way to see how much time more spent on CI now?

**Comment by wanchaol** [comment]
> good to see that op db tests are now enabled!! Is there a way to see how much time more spent on CI now?

updated in the summary.

**Comment by XilunWu** [comment]
The speedup of testing is quite impressive!! Congrats!

**Pull request closed without merging**
