### PR TITLE
Enable bitwise shift operations tests

### PR DESCRIPTION
**Pull request by bjhargrave**
With #70904 fixed, we can remove the skips for the bitwise shift tests.

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
Looks like now it fails [linux-focal-rocm5.4.2-py3.8 / test (distributed, 2, 2, linux.rocm.gpu)](https://github.com/pytorch/pytorch/actions/runs/4622657882/jobs/8175936556?pr=97150#logs)

I've re-run the test to see if it fails again.

**Pull request closed without merging**
