### PR TITLE
Allow disabling cache in autocast (automatic mixed precision)

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
In this PR, we want to exclude these 2 cases in the `Autocast` weight cache usages:

- Using `torch.jit.trace` under the `Autocast` 
As report in https://github.com/pytorch/pytorch/issues/50231 and several other discussions, using `torch.jit.trace` under the `Autocast`, the trace process would hit Autocast's weight cache and fails. So we should disable weight cache under the trace process.
- Using `Autocast` with `Grad mode`

  - Usually we are using `Grad mode` for training. Since in the training phase, the weight will change in every step. So we doesn't need to cache the weight.
  - For the recommended `Autocast` training case in the [doc](https://pytorch.org/docs/stable/amp.html), `Autocast` will clear the cache every step leaving the context. We should disable it to save the clear operations.
    ```
    model = Net().cuda()
    optimizer = optim.SGD(model.parameters(), ...)
    
    for input, target in data:
        optimizer.zero_grad()
        with autocast():
            output = model(input)
            loss = loss_fn(output, target)
        loss.backward()
        optimizer.step()
    ```

Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #63552

Differential Revision: [D30644913](https://our.internmc.facebook.com/intern/diff/D30644913)

### CODE REVIEW

**Comment by ezyang** [comment]
> Usually we are using Grad mode for training. Since in the training phase, the weight will change in every step. So we doesn't need to cache the weight.

No, this is not valid. First, the *primary* use case of AMP is for training; see for example, https://pytorch.org/docs/stable/amp.html . Second, the weight cache is intended to handle cases when a weight is used multiple times; the original motivating reason for the weight cache was handling RNN cells used in a loop, without the caching the weights would be casted over and over.

In cases when the weight is used only once, the cache is somewhat wasteful, but it's at least a predictable multiplicative factor. I suppose it might be OK to provide a knob to disable the cache; curious what @mcarilli thinks.

----

The fix for JIT tracing also looks suspect: you will end up with an "incorrect" trace where casts are carried out multiple times (whereas in a true trace, the cast would only get carried out once and then be propagated to each use site.) It feels like the problem is that we are not tracing the cast itself (which, if it were traced, would make it not a constant in this case); because you do not print the traced module in your tests I cannot easily see if this is the case.

**Review by ezyang — CHANGES_REQUESTED** [review]
not right

**Comment by leslie-fang-intel** [comment]
Thanks for the review, @ezyang. Let's split it into 2 discussions. The first one here is for `disabling cache in training`.  And thanks for providing the detail use case of `RNN cells`.
> 
> No, this is not valid. First, the _primary_ use case of AMP is for training; see for example, https://pytorch.org/docs/stable/amp.html . Second, the weight cache is intended to handle cases when a weight is used multiple times; the original motivating reason for the weight cache was handling RNN cells used in a loop, without the caching the weights would be casted over and over.
> 
> In cases when the weight is used only once, the cache is somewhat wasteful, but it's at least a predictable multiplicative factor. I suppose it might be OK to provide a knob to disable the cache; curious what @mcarilli thinks.

I understand the reason to keep it and agree we should provide a knob to disable it. Looking for the feedback from @mcarilli.

**Comment by leslie-fang-intel** [comment]
The second one discussed here is for `disabling cache` in `JIT Trace`. Take this as example:
```
import torch
import torch.nn as nn

class TestModel(nn.Module):
    def __init__(self, input_size, num_classes):
        super(TestModel, self).__init__()
        self.fc1 = nn.Linear(input_size, num_classes)
    def forward(self, x):
        return self.fc1(x)
input_size = 2
num_classes = 2
model = TestModel(input_size, num_classes).eval()
with torch.cpu.amp.autocast():
    model = torch.jit.trace(model, torch.randn(1, input_size))
```
From my previous experiment, there are 2 issues which will fail the `jit trace` when we enable `autocast cache` (Note, if we take `check_trace=False`, the trace will success).
1. The first issue is 
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    model = torch.jit.trace(model, torch.randn(1, input_size))
  File "/home/lesliefang/pytorch_1_7_1/Autocast_Pytorch/pytorch/torch/jit/_trace.py", line 749, in trace
    _module_class,
  File "/home/lesliefang/pytorch_1_7_1/Autocast_Pytorch/pytorch/torch/jit/_trace.py", line 990, in trace_module
    _module_class,
  File "/home/lesliefang/pytorch_1_7_1/Autocast_Pytorch/pytorch/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/lesliefang/pytorch_1_7_1/Autocast_Pytorch/pytorch/torch/jit/_trace.py", line 337, in _check_trace
    _compilation_unit=torch._C.CompilationUnit(),
  File "/home/lesliefang/pytorch_1_7_1/Autocast_Pytorch/pytorch/torch/jit/_trace.py", line 964, in trace_module
    argument_names,
  File "/home/lesliefang/pytorch_1_7_1/Autocast_Pytorch/pytorch/torch/nn/modules/module.py", line 1064, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lesliefang/pytorch_1_7_1/Autocast_Pytorch/pytorch/torch/nn/modules/module.py", line 1052, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "test.py", line 11, in forward
    return self.fc1(x)
  File "/home/lesliefang/pytorch_1_7_1/Autocast_Pytorch/pytorch/torch/nn/modules/module.py", line 1064, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lesliefang/pytorch_1_7_1/Autocast_Pytorch/pytorch/torch/nn/modules/module.py", line 1052, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/lesliefang/pytorch_1_7_1/Autocast_Pytorch/pytorch/torch/nn/modules/linear.py", line 99, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/lesliefang/pytorch_1_7_1/Autocast_Pytorch/pytorch/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
```
2.  I remember somehow we can workaround the first issue. Then we will meet another issue as that `JIT check trace` fails. Looks like the first traced graph is using the weight in module. And the second traced graph (Inside the `check trace` for comparison) will use the weight in cache. So these 2 graphs will fail to compare as the same.

Generally, as discussed above, if we can provide a knob to disable `cache in Autocast`. It will be fine.

**Comment by ezyang** [comment]
> But can you elaborate more about this comment:

Imagine there is multiple use of parameter:

```
param = Parameter(...)
x0 = ...
x1 = cell(x0, param)
x2 = cell(x1, param)
...
```

The trace should look like this (when weight caching is turned on)

```
param = Parameter(...)
x0 = ...
cached_param = param.half()
x1 = cell(x0, cached_param)
x2 = cell(x1, cached_param)
...
```

not

```
param = Parameter(...)
x0 = ...
x1 = cell(x0, param.half())
x2 = cell(x1, param.half())
...
```

Yes your compiler might be able to CSE the param.half() but it is better to generate accurate IR in the first place.

> And the second traced graph (Inside the check trace for comparison) will use the weight in cache. So these 2 graphs will fail to compare as the same.

I think know how to fix this: turn on AMP *inside* the model being traced, not around the trace itself.

**Comment by leslie-fang-intel** [comment]
> I think know how to fix this: turn on AMP inside the model being traced, not around the trace itself.

Thank you for the elaboration. Can you give us a piece of pesudo code for this use case `turn on AMP inside the model being traced`?
BTW, when we talk about add a knob to disable `Cache` inside `Autocast`, it should be a extra parameter of `torch.cpu.amp.autocast`, right?

**Comment by jgong5** [comment]
> Yes your compiler might be able to CSE the param.half() but it is better to generate accurate IR in the first place.

@ezyang I think the problem here is that the weight cache feature breaks the assumption of `torch.jit.trace` and makes the autocast and `torch.jit.trace` features not composable. While in fact, the weight cache feature is just an optimization, i.e. keeping the semantics and making things faster, no difference from the graph optimization passes in JIT. Both of them are transparent to the users. So, I don't understand why we can't just disable the weight cache in the JIT trace mode and let the graph passes to optimize out the redundant casts. Alternatively, I'm not sure if it is possible to improve `torch.jit.trace` to handle the cases like weight cache. In general, it is caused by the need of extra initialization in the first forward run. The second and later runs should keep the trace unchanged. I'm also OK with an explicit knob to disable the weight cache but the con is extra complexity added to the user API.

> First, the primary use case of AMP is for training

Oh, I was not aware of the original intention. But for inference, AMP does help too, right?

> In cases when the weight is used only once, the cache is somewhat wasteful

If we think about AMP in inference, the weight cache can also save extra type casting cost, right?

**Comment by ezyang** [comment]
Pseudocode for AMP on inside something like:

```
import torch
import torch.nn as nn

class TestModel(nn.Module):
    def __init__(self, input_size, num_classes):
        super(TestModel, self).__init__()
        self.fc1 = nn.Linear(input_size, num_classes)
    def forward(self, x):
        return self.fc1(x)

class AMPModel(nn.Module):
    def __init__(self, module):
        super(AMPModel, self).__init__()
        self.module = module
    def forward(self, x):
        with torch.cpu.amp.autocast():
            self.module(x)

input_size = 2
num_classes = 2
model = TestModel(input_size, num_classes).eval()
wrapped_model = AMPModel(model)

model = torch.jit.trace(wrapped_model, torch.randn(1, input_size))
```

**Comment by ezyang** [comment]
> BTW, when we talk about add a knob to disable Cache inside Autocast, it should be a extra parameter of torch.cpu.amp.autocast, right?

Yes, seems reasonable.

> I think the problem here is that the weight cache feature breaks the assumption of torch.jit.trace and makes the autocast and torch.jit.trace features not composable. While in fact, the weight cache feature is just an optimization, i.e. keeping the semantics and making things faster, no difference from the graph optimization passes in JIT. Both of them are transparent to the users. So, I don't understand why we can't just disable the weight cache in the JIT trace mode and let the graph passes to optimize out the redundant casts. Alternatively, I'm not sure if it is possible to improve torch.jit.trace to handle the cases like weight cache. In general, it is caused by the need of extra initialization in the first forward run. The second and later runs should keep the trace unchanged. I'm also OK with an explicit knob to disable the weight cache but the con is extra complexity added to the user API.

I think my pseudocode above fixes this problem.

> If we think about AMP in inference, the weight cache can also save extra type casting cost, right?

I guess. But in inference if you really didn't need high precision weights you can downcast them as a postprocessing step; you don't need AMP at all! This is basically what quantization is about...

**Comment by jgong5** [comment]
> I guess. But in inference if you really didn't need high precision weights you can downcast them as a postprocessing step; you don't need AMP at all! This is basically what quantization is about...

@ezyang Then the postprocessing step has to take care of the similar things as what AMP provides since not all ops or weights can compute with low precision without sacrificing the accuracy, i.e. 1) users have to insert upcast/downcast around ops that prefer high precision compute; 2) users have to keep weights in high precision where needed (e.g. normalization layers). That is why I think AMP helps inference too.

**Comment by leslie-fang-intel** [comment]
Thanks for the Pseudocode. It fixes the issue. To summary, basically we have 3 choices now:
1. Turn on AMP inside the model being traced, not around the trace itself. 
     - The pros is we don't need to change any pytorch code. 
     - The cons is user has to write a extra `AMP Warp Module`.

2. Provide a extra knob to disable the cache inside `Autocast`. 
     - The pros is it can also help to save the unnecessary cache for some training cases. 
     - The cons is extra complexity added to the user API.

3. Just as this PR did, we automatically disable the cache inside `Autocast` when `jit trace` is enabled.
     - The pros is it's not user aware and keep the user API simple.
     - The cons is we have to add every condition inside `Autocast` when we need to disable the cache.

Hi @ezyang, do you think which solution we should pick as the formal solution to customers using `jit trace` with `Autocast`?

**Comment by ezyang** [comment]
I'm still OK with "Provide a extra knob to disable the cache inside Autocast", if you want to send this patch. I mostly don't want to do (3).

**Comment by leslie-fang-intel** [comment]
> I'm still OK with "Provide a extra knob to disable the cache inside Autocast", if you want to send this patch. I mostly don't want to do (3).

Thanks for the comment, added a extra knob `cache_enabled` to control the cache status inside Autocast. To work with `jit trace`, we can use autocast as below now:
```
with torch.cpu.amp.autocast(cache_enabled=False):
    traced_model = torch.jit.trace(model, input)
```
-------------------------------------------------
There is a cache behavior inside the nested region I want to discuss @ezyang. Think about this case:
```
with torch.cpu.amp.autocast():
    model1(input1)
    with torch.cpu.amp.autocast(cache_enabled=False):
        model2(input2)
```
For the `model2` region, we will disable the usage of cache, but we will not clear the cache. Since I think when we come back the `model1` region, we still want to use the cache. Do you think this behavior make sense?

**Comment by leslie-fang-intel** [comment]
I find new added UT `test_nchw_autocast_jit_trace_model` failed in preCI `pytorch_linux_xenial_py3_6_gcc5_4_test` but success in preCI `pytorch_linux_bionic_py3_6_clang9_noarch_test` and my local ENV. Any clues about how can I reproduce the error?

**Comment by ezyang** [comment]
> I find new added UT test_nchw_autocast_jit_trace_model failed in preCI pytorch_linux_xenial_py3_6_gcc5_4_test but success in preCI pytorch_linux_bionic_py3_6_clang9_noarch_test and my local ENV. Any clues about how can I reproduce the error?

Can you please link to the failure

**Comment by leslie-fang-intel** [comment]
> > cc @bertmaher
> 
> Thank you, after rebase to latest master. Several other PreCI fails. But I still can't reproduce the error in my local ENV😂.

After I move these UTs from `test_autocast.py` to `test_jit.py`, it seems passed the PreCI.

**Comment by bertmaher** [comment]
Sorry about the "unsupported dtype" error.  I take it it's gone now (I'm not sure exactly what I've done to fix it, but I've been cleaning up the jit's internal type system the last few days so it's entirely possible I've fixed this problem too).  Let me know if it reappears and I'll debug.

**Comment by ezyang** [comment]
Implementation LGTM. I'll bug mcarilli to give the high level functionality a once over.

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30644913).

**Comment by leslie-fang-intel** [comment]
Rebase to master. Hi @ezyang @mcarilli, Do we need further following up?

**Comment by ezyang** [comment]
mcarilli is cool with it, although the extra TLS fetch sux. Gonna merge

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30644913).

**Pull request closed without merging**
