### PR TITLE
Fix typo under test directory

### PR DESCRIPTION
**Pull request by kiszk**
This PR fixes typo in comments and messages under `test` directory. This PR also fixes related typo in messages under `torch` directory.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
You need to update the typo which is matched for in the test. Search for "ocurred" sic

**Comment by kiszk** [comment]
Thanks for pointing out my overlooked update.

**Pull request closed without merging**
