### PR TITLE
Half fixes for ATen

### PR DESCRIPTION
**Pull request by csarofeen**
Fixes for CUDA 9

### CODE REVIEW

**Comment by csarofeen** [comment]
@soumith Is there a reason why in torch/lib/ATen/Half.h cuda_runtime.h was included instead of cuda.h?

**Comment by soumith** [comment]
@csarofeen i dont remember. Maybe @zdevito remembers.

**Comment by soumith** [comment]
@csarofeen GPU contbuilds are failing on this PR: https://build.pytorch.org/job/pytorch-PR-py2-linux/405//console

**Comment by zdevito** [comment]
No reason, cuda.h is fine.

**Comment by csarofeen** [comment]
I wanted to get rid of cuda_runtime include but turns out I not only needed that but cuda.h as well for the version check on CUDA.

**Comment by soumith** [comment]
this was merged into master.

**Pull request closed without merging**
