### PR TITLE
[release/1.5] Trying pinning pyyaml and setuptools on macos to older version

### PR DESCRIPTION
**Pull request by seemethere**
Should hopefully resolve macOS timeouts

Cherry picked from https://github.com/pytorch/pytorch/pull/35296

(cherry picked from commit 4d36b8187b0a3e8696d67ba9729cdfd972a3640e, )
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
@seemethere I'm not sure if this fix is sufficient to fix the binary packaging process though!!

**Comment by seemethere** [comment]
> @seemethere I'm not sure if this fix is sufficient to fix the binary packaging process though!!

I don't think there's currently an issue building any of the binary packages right now on `release/1.5`

**Comment by ezyang** [comment]
What @albanD observed is that with the newest version of setuptools the executable bit was not preserved when copying the shm executable. It's worth checking that our OS X binaries appropriately have the executable bit set. Maybe we are pinned in the binary build process which is saving us.

**Comment by seemethere** [comment]
So @ezyang would the fix for the binaries be to pin `setuptools `in `pytorch/builder`?

**Pull request merged**
