### PR TITLE
enable NVFuser by default

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #76006
* #76937

Enable NVFuser in OSS.
Tests are passing, and we've also run tests in [torchvision](https://github.com/pytorch/vision/pull/5959) and [torchaudio](https://github.com/pytorch/audio/pull/2372)

Differential Revision: [D35736977](https://our.internmc.facebook.com/intern/diff/D35736977)

### CODE REVIEW

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35736977).

**Comment by davidberard98** [comment]
cc @jjsjann123 did you have a plan on how to flip the switch? I was trying to test it here, but looks like this strategy doesn't work (I think it's due to static initialization order where CUDAHooks needs to get registered before at::globakContext().hasCUDA() will work in cuda_graph_fuser.h)

Do you have another idea on how to do this? I think we could probably try to wrap the registration in some functions and call the functions to enforce registration order... but not sure if there's a nicer way to do it

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35736977).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35736977).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35736977).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35736977).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35736977).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35736977).

**Comment by bigfootjon** [comment]
Apologies for the spam here. For Meta engineers the fix is D36284533

**Comment by davidberard98** [comment]
retrying in #77213

**Pull request closed without merging**
