### PR TITLE
Register SymInt-aware meta function for mm out, symintify resize

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #113202

Fixes https://github.com/pytorch/pytorch/issues/112489

Fixes https://github.com/pytorch/pytorch/issues/112494

New OpInfo tests for out variants added, since these were not exercised previously.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Ok!
We definitely have things like test_out_warning in test_ops.py that check some out variants.

**Comment by ezyang** [comment]
Now with OpInfo tests. I confirmed that the matmul test failed before this change and passes after.

**Pull request closed without merging**
