### PR TITLE
[caffe2] Add typing dependency to caffe2 CI

### PR DESCRIPTION
**Pull request by smessmer**
This is needed to run mypy on CI

### CODE REVIEW

**Comment by smessmer** [comment]
cc @pietern @ezyang @pjh5

**Comment by ezyang** [comment]
OK, remember you have to manually trigger a Caffe2 docker image build from the CI to get new images.

**Comment by smessmer** [comment]
CI errors are unrelated as the change is trivial and the error isn't about pip.
Can someone merge this? I guess it has to be merged before I rebuild the docker images?

**Comment by Yangqing** [comment]
So the caffe2-docker-trigger setup is still referring to the caffe2/caffe2 repo, and as a result it cannot find the PR: https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/94/

Could someone update the jenkins setup to properly trace the pytorch repo now? cc @pietern @ezyang @orionr .

**Comment by Yangqing** [comment]
@smessmer after the jenkins update is done, you can rebuild the docker with the following steps:

(1) go to https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/
(2) make sure you are logged into jenkins.
(3) click "build with parameters"
(4) for git commit, use "origin/pr/6195/head" - replace with your own pr number.

**Comment by smessmer** [comment]
Rebuild passed, see https://ci.pytorch.org/jenkins/job/caffe2-docker-trigger/97/
Can we merge this?

**Pull request merged**
