### PR TITLE
remove unnecessary import introduced in PR 106535

### PR DESCRIPTION
**Pull request by XilunWu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #107440
* #106535

### CODE REVIEW

**Review by fduwjj — APPROVED** [review]
Wondering why this was not captured by the lint rule (mypy for example)..

**Review by wanchaol — COMMENTED** [review]
Can you add the `randn` too (either in this PR or in follow up PRs)?

**Comment by XilunWu** [comment]
> Wondering why this was not captured by the lint rule (mypy for example)..

same question!! I was quite surprised when finding the it. Should I report this to dev team? @wanchaol @fduwjj

**Comment by XilunWu** [comment]
> Can you add the `randn` too (either in this PR or in follow up PRs)?

will do in another PR

**Pull request closed without merging**
