### PR TITLE
Fix SpectralNorm with DataParallel

### LINKED ISSUE #11476: DataParallel replicates network object for device 0
This makes some hooks just not work, e.g., if your hook sets some attribute on the `module` input, they are lost. E.g., spectral norm. This makes DataParallel + spectral norm not converging.

Also DataParallel + spectral norm doesn't work in eval mode because we don't properly broadcast buffers that require grad. See the following repro:

```
import torch
import torch.nn as nn
from torch.nn.utils import spectral_norm

net = nn.Conv2d(3, 3, 3).cuda()
net = spectral_norm(net)
net = nn.DataParallel(net)

inp = torch.randn(2, 3, 4, 4).cuda()

net(inp)

net.eval()
net(inp)
```

I'll fix both.

### PR DESCRIPTION
**Pull request by ssnl**
There were two problems with SN + DP:

1. In SN, the updated _u vector is saved back to module via a `setattr`. However, in DP, everything is run on a replica, so those updates are lost.
2. In DP, the buffers are broadcast via a `broadcast_coalesced`, so on replicas they are all views. Therefore, the `detach_` call won't work.

Fixes are:
1. Update _u vector in-place so, by the shared storage between 1st replica and the parallelized module, the update is retained
2. Do not call `detach_`.
3. Added comments in SN about the subtlety.
4. Added a note to the DP doc on this particular behavior of DP.

cc @crcrpar @taesung89 @t-vi @yaoshengfu

Fixes https://github.com/pytorch/pytorch/issues/11476

### CODE REVIEW

**Comment by SsnL** [comment]
Still need to fix eval code, probably involves saving _v and figuring out BC.

**Comment by SsnL** [comment]
@t-vi or @crcrpar  Wanna review this one? :)

**Comment by crcrpar** [comment]
@SsnL I read thru this and seems solid! 👍

**Comment by t-vi** [comment]
Looks all reasonable to me, but I lack the Distributed expertise for that to mean much.
One bit I'm not sure about is the following: Do we / should we test that the weight_orig/weight are do get nonzero gradients on backward if they require grad?

Out of curiosity: What is the BC breaking when you recompute the weight in eval mode instead of detaching?

**Comment by SsnL** [comment]
@crcrpar @t-vi Thanks for looking!

@t-vi The problem with recomputing eval mode is that we only store `weight_orig`, and `weight_u`. But we need `weight_v` to also recompute `weight` graph. Note that `weight_v` is not uniquely determined even if we store `weight_orig`. And because our power iteration updates `v` vector first and `u` vector second, it can't be computed from `u` either. Therefore, I want to also register `weight_v` as a buffer. Additionally, I want to not register `weight` as a buffer, but as a plain attribute. Registering as buffer makes the state dict redundant, and it is not really a buffer. To make all these changes, I need to figure out a way to add hook into `load_state_dict` when people register `spectral_norm`.

**Review by colesbury — APPROVED** [review]

**Comment by YaoshengFu** [comment]
I updated my code with the latest spectral_norm implementation (I just replaced spectral_norm.py and function.py), but I got the following error:

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

This error disappeared if I switch back to the old spectral_norm implementation.

**Comment by SsnL** [comment]
@YaoshengFu I can't reproduce the error you see. Could you install the nightly and check if the error still happens?

**Comment by SsnL** [comment]
@YaoshengFu Thanks. I will do!

**Pull request closed without merging**
