### PR TITLE
[Caffe2 multi-nodes] Enhance cpu support on gloo based multi-nodes mode.

### PR DESCRIPTION
**Pull request by manofmountain**
1. Add some gloo communication operators into related fallback list;
2. Work around to avoid compiling errors while using fallback operator whose CPU operator inherits from 'OperatorBase' directly like PrefetchOperator;
3. Add new cpu context support for some python module files and resnet50 training example file.

### CODE REVIEW

**Comment by manofmountain** [comment]
@wesolwsk , hello, could you help review this?

thanks,
Shane

**Comment by manofmountain** [comment]
@wesolwsk  Hi Lucasz, have you reviewd this PR?  any comments from you would be very welcomed. :)

thanks,
Shane

**Comment by manofmountain** [comment]
@wesolwsk  this is a PR on some caffe2 python module which doesn't change anything on torch side. The fail build test of torch on 'test_all_reduce_group_product' seems not reasonable as no related torch codes changed within this PR. Do you kindly have any comments on this?

**Comment by jgong5** [comment]
This PR depends on the upgrade of MKL-DNN bridge: PR #12164.

**Comment by wesolwsk** [comment]
@PenghuiCheng, could you please rebase?

**Comment by jspisak** [comment]
cc @yinghai - please take a look..

**Comment by wesolwsk** [comment]
Sorry @PenghuiCheng, can you rebase again? I am getting a conflict in caffe2/caffe2/ideep/operators/operator_fallback_ideep.cc

**Comment by manofmountain** [comment]
@wesolwsk  have rebased it, but don't see any conflicts on 'caffe2/ideep/operators/operator_fallback_ideep.cc'.

If it only happens on internal repository, you can share me the conflict files, then i'll make a fix on it.

**Comment by wesolwsk** [comment]
@manofmountain Was there a good reason to delete caffe2/python/examples/lmdb_create_example.py?

**Comment by manofmountain** [comment]
> @manofmountain Was there a good reason to delete caffe2/python/examples/lmdb_create_example.py?

thanks for catching this. And i think it's a mistake to remove this python file while rebasing. :(

BTW, i have added it back to this PR and fixed the conflicts with the latest commit.

**Pull request closed without merging**
