### PR TITLE
[Quant][core][devs] Removed support for non-quantized tensors in reflection_pad1d_cpu

### PR DESCRIPTION
**Pull request by dzdang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #72485

Summary: This PR is part of a series of PRs addressing https://github.com/pytorch/pytorch/issues/54150,
related to using dispatcher for calls to quantized backends as opposed to if/else conditionals.
This particular PR removes the support for non-quantized tensors in reflection_pad1d_cpu because the current dispatch table for the 2 argument reflection_pad1d_cpu only has a QuantizedCPU entry that routes to reflection_pad1d_cpu; all other backends are routed through structured_delegate's desgination which then through through the out variant overload

Differential Revision: [D34085104](https://our.internmc.facebook.com/intern/diff/D34085104)

### CODE REVIEW

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34085104).

**Comment by jerryzh168** [comment]
the lint error looks relevant

**Review by jerryzh168 — APPROVED** [review]

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34085104).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34085104).

**Pull request closed without merging**
