### PR TITLE
Port masked_select cuda from TH to ATen

### PR DESCRIPTION
**Pull request by kurtamohler**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#34604 Port masked_select cuda from TH to ATen**
* #34603 adjust warning in masked_select.out
* #34602 port masked_select from TH to ATen and optimize perf on CPU

Issue #33054

Depends on PR #33269.

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
Hi! Can you please rebase to master, thanks.

**Comment by kurtamohler** [comment]
> Hi! Can you please rebase to master, thanks.

I'm not really sure how to do that since this is a dependent PR. Does the PR this depends on have to be rebased first?

**Comment by zou3519** [comment]
@kurtamohler on the branch that you ran ghstack on, you can run `git pull --rebase upstream master`, check that this commit is on top of master after that git command with `git log`, and then re-run ghstack.

**Comment by ngimel** [comment]
@kurtamohler, do you know if  the performance problems you pointed out in #33269 are resolved?

**Comment by kurtamohler** [comment]
Thanks @zou3519 ! Currently working on fixing merge conflicts.

@ngimel, no, #33269 still gives a performance decrease on my machine. @mingfeima 's hardware showed a different story, a performance increase.

Long story short, I'm not sure what would explain that difference. @mingfeima seemed to suggested that jemalloc configuration could be an explanation, but I don't know enough about that to understand why. He also suggested that cache size differences could be the explanation, and I disagree but am willing to accept evidence that shows he's right.

**Comment by kurtamohler** [comment]
@zou3519 , AT_WARN was recently removed, and PR #33269 uses it. I can replace it with TORCH_WARN on my local checkout, but my PR should not make that replacement. I'm not sure exactly what I can do, aside from asking @mingfeima to make that change it in his PR. Or could I just add that change to his commit within my branch?

**Comment by ngimel** [comment]
But that means we won't be merging #33269 until perf issues are resolved, and this will stall your PR? This is not an ideal situation.

**Comment by kurtamohler** [comment]
@ngimel , it would be possible for me to remove my dependencies on #33269. The only reason there are dependencies is because we both touch Declarations.cwrap. He removed the TH CPU dispatch from it, and then I removed the declarations entirely. But I could change mine to keep the TH CPU dispatch. If I do that, then whichever one of our PRs comes in last will have to be updated to remove the declarations. Do you think that's a better route?

**Comment by ngimel** [comment]
Yes, please do that!

**Comment by kurtamohler** [comment]
@ngimel , ok then I think it will make sense for me to close this PR and reopen one that isn't created with ghstack.

**Pull request closed without merging**
