### PR TITLE
[ROCM] Enable custom tests on rocm

### PR DESCRIPTION
**Pull request by jpvillam-amd**
Enables custom test building and testing on ROCm.

### CODE REVIEW

**Comment by janeyx99** [comment]
This looks good on the scripting side + CI passes, but would appreciate an approve from @jeffdaily.

**Review by jeffdaily — APPROVED** [review]
LGTM

**Comment by jpvillam-amd** [comment]
@lw @janeyx99 Sorry for the ping, Jeff has approved the PR and I am looking to move it along.

**Review by janeyx99 — APPROVED** [review]

**Comment by janeyx99** [comment]
> @lw @janeyx99 Sorry for the ping, Jeff has approved the PR and I am looking to move it along.

Sorry was out for a few days!

**Comment by janeyx99** [comment]
Hey @jpvillam-amd could you rebase this PR? 

Once lint passes, feel free to comment `@pytorchbot merge this please` yourself to merge it!

**Pull request closed without merging**
