### PR TITLE
Add windows CUDA 12.6 nightly builds

### PR DESCRIPTION
**Pull request by atalman**
Windows AMI was published to prod. This PR adds CUDA 12.6 nightly builds

cc @albanD

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
@atalman I just want to make sure that CUDNN is upgraded on Windows and CUTLASS is set to 12.6.3

**Comment by atalman** [comment]
Hi @Skylion007 cudnn is updated, yes. Cutlass maybe different which is acceptable. Windows builds can be a little behind Linux builds, since in General Windows AMI publishing process is quite long, we can't move as fast as Linux at this time.

**Comment by Skylion007** [comment]
@atalman Ah sorry, typo'd meant CUDA. We are actually still way behind on CUTLASS and need to update it for all our backends. See @cutlass https://github.com/pytorch/pytorch/pull/131493

**Pull request closed without merging**
