### PR TITLE
Test profiler on ARM

### PR DESCRIPTION
**Pull request by robieta**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #82942

Just saw that profiler tree tests had to be disabled, and figuring out if it's fundamental.

Differential Revision: [D38487443](https://our.internmc.facebook.com/intern/diff/D38487443/)

### CODE REVIEW

**Comment by robieta** [comment]
@albanD Looks like these are passing on all ARM platforms. What failures were you seeing?

**Review by albanD — APPROVED** [review]
Ho that is interesting. The massive strings were not matching and so I had to skip these.
But I guess that might have been due to something else..

It is very hard to debug issues with these btw

**Comment by robieta** [comment]
> Ho that is interesting. The massive strings were not matching and so I had to skip these. But I guess that might have been due to something else..
> 
> It is very hard to debug issues with these btw

If you have an example I'd be happy to take a look. (Still tweaking to surface changes as ergonomically as possible.)

**Comment by albanD** [comment]
I was looking for it but the CI logs are not available any more :/

**Comment by robieta** [comment]
> I was looking for it but the CI logs are not available any more :/

:(

**Pull request closed without merging**
