### PR TITLE
Move thnvrtc and DynamicLibrary to ATen

### PR DESCRIPTION
**Pull request by ssnl**
Having the NVRTC stub in ATen is necessary to call driver APIs in ATen. This is currently blocking https://github.com/pytorch/pytorch/pull/22229.

`DynamicLibrary` is also moved as it is used in the stub code, and seems general enough.

### CODE REVIEW

**Comment by SsnL** [comment]
The test error is from #22052 , not from this PR.

**Review by zdevito — COMMENTED** [review]
Code changes look fine to me. I didn't review the build changes because I do not have the context for how they work anymore.

**Comment by vadimkantorov** [comment]
Does this open a way to custom fast user-provided CUDA-snippets? (like element-wise fused ops)

**Comment by SsnL** [comment]
@vadimkantorov could you elaborate a bit on what you mean exactly?

**Comment by vadimkantorov** [comment]
I mean providing a wrapper that, given a user-provided CUDA expresion like ```x => sin(cos(x))```, can in runtime generate a kernel (without saving it to disk, like `cpp_extension.load_inline` would do, and I think there are also some restrictions on ABI matching the compiler that was used for compiling PyTorch) that applies over a CUDA tensor (inplace or outplace). Probably binary apply functions could exist as well. Even if this would exist only in contrib, an example of NVRTC runtime compilation and creation of a function for dense contiguous float CUDA tensors can be helpful.

**Comment by SsnL** [comment]
@vadimkantorov I see. 

Let me explain a bit. This PR adds nothing new (unless you are using ATena and only ATen). The NVRTC stub currently lives in `libtorch`, being used by jit exactly. The PR only moves it to ATen. Technically what you described could be a feature implemented in `libtorch` without this PR, and using the existing stub there. But maybe moving the stub to ATen makes bindings easier, idk. :)

**Comment by SsnL** [comment]
I think it would be great if this is also reviewed by a build person :)

**Comment by zou3519** [comment]
I'm not sure if this is relevant, but I think you can call libtorch code from ATen.

**Comment by SsnL** [comment]
@zou3519 fascinating! Are there examples on how to do that?

**Comment by zou3519** [comment]
You can include a torch header from any ATen file: https://github.com/pytorch/pytorch/blob/b76877728a1f06c936a63e7028651561ca3248fc/aten/src/ATen/NamedTensor.cpp#L4.

This will definitely break the ATen standalone library though, if it still exists and if it hasn't been broken already. I don't know what our plan on that is.

**Comment by SsnL** [comment]
@zou3519 Oh that's cool. Good to know that. Thanks! :)

**Comment by SsnL** [comment]
Hey @kostmo , can you review this? Thank you :)

**Review by kostmo — APPROVED** [review]

**Comment by ezyang** [comment]
It looks like this diff need some internal build updates.

**Comment by SsnL** [comment]
@ezyang Let me know if there is any thing I can help. I am more than happy to!

**Comment by ezyang** [comment]
The internal CI error is

```
caffe2/aten/src/ATen/cuda/detail/CUDAHooks.cpp: included an untracked header: 
caffe2/aten/src/ATen/cuda/nvrtc_stub/ATenNVRTC.h
```

I'm waiting for my internal source copy to check out and I'll look some more.

**Comment by ezyang** [comment]
I got a simple fix. Testing.

**Comment by ezyang** [comment]
Internally, users are reporting this error:

```
Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory
```

**Comment by SsnL** [comment]
@ezyang  hmmm I know that internal builds are not using CMake. Maybe some build changes are needed for it to build the library?

**Comment by ezyang** [comment]
So, what I'm kind of thinking right now, is that all I need to do is turn `USE_DIRECT_NVRTC` back on for the internal build. Because fbcode has its own strategy for lazy loading of CUDA libraries, so the thing you did here isn't necessary in that case. Unfortunately, I didn't actually review this PR, so I am not sure.

**Comment by SsnL** [comment]
@ezyang Ah I see. So the fbcode build just puts everything in one library, including the `libcaffe2_nvrtc` bits. Let me know how I can help with this!

also cc @kostmo who reviewed :)

**Pull request closed without merging**
