### PR TITLE
[LTC] Use DataCache in GetIrValueForScalarFromCodegen

### LINKED ISSUE #4213: Seeing a roughly 25% slow down with torch-xla=1.13 because of the addcdiv_ and addcmul_ ops
## 🐛 Bug

For BERT large model, we are seeing around 25% slow down with the latest torch-xla=1.13. The slow down seems to happen because of the addcdiv_ and addcmul_ operations transferring scalars synchronously to device. These are the operations which causes slow down:
1. `exp_avg_sq.mul_(beta2).addcmul_(grad, grad, value=1.0 - beta2)`
2. ` p.data.addcdiv_(exp_avg, denom, value=-step_size)`
(Taken from: https://github.com/huggingface/transformers/blob/v4.6.0/src/transformers/optimization.py#L346)
Note, here the scalars are not special scalars as the value is not 0 or 1 as in this case: https://github.com/pytorch/xla/pull/3953

As the model size grows the number of scalars transfered to device also grows and we end up with a profile that looks like this:

Screen Shot 2022-11-17 at 9 19 59 AM
## To Reproduce
Run the following example:

```
t = torch.randn(1, 3)
t1 = torch.randn(3, 1)
t2 = torch.randn(1, 3)
t.addcdiv_(t1, t2, value=0.1) 
xm.mark_step()
```

This should produce a transfer of scalar synchronously.

1.
4.
5.

## Expected behavior

We didn't see such a transfer with torch-xla 1.12. 

## Environment

 - Reproducible on XLA backend [CPU/TPU]:
 - torch_xla version: 1.13

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
XLA expects GetIrValueForScalarFromCodegen to use DataCache such that not every scalar will request a data transfer to the backend device.

This needs pytorch/xla#4447 to verify.

Test Plan:
PJRT_DEVICE=CPU python xla/test/test_operations.py -v -k test_cached_addcdiv

Fixes pytorch/xla#4213.

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]
Thanks Jiewen!

**Comment by alanwaketan** [comment]
Thanks for reviewing.

**Pull request closed without merging**
