### PR TITLE
Refactor multigpu tests to  `test_cuda_multigpu`

### PR DESCRIPTION
**Pull request by malfet**
Mostly refactor, that moves all the tests from `test_cuda` that benefit from multiGPU environment into its own file.

- Add `TestCudaMallocAsync` class for Async tests ( to separate them from `TestCudaComm`)
- Move individual tests from `TestCuda` to `TestCudaMultiGPU`
- Move `_create_scaling_models_optimizers` and `_create_scaling_case` to `torch.testing._internal.common_cuda`
- Add newly created `test_cuda_multigpu` to the multigpu periodic test

### <samp>🤖 Generated by Copilot at f4d46fa</samp>

This pull request fixes a flaky test and improves the testing of gradient scaling on multiple GPUs. It adds verbose output for two CUDA tests, and refactors some common code into helper functions in `torch/testing/_internal/common_cuda.py`.

cc @albanD

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
I guess this is ok as long as the test passes.  But its current TTS looks concerning https://github.com/pytorch/pytorch/actions/runs/5360531419/jobs/9725908665 (3h+ and going).  I'm not sure if it's a problem in the test or if we need more shards.  I think the current run is going to time out soon (4h)

**Comment by malfet** [comment]
> I guess this is ok as long as the test passes. But its current TTS looks concerning https://github.com/pytorch/pytorch/actions/runs/5360531419/jobs/9725908665 (3h+ and going). I'm not sure if it's a problem in the test or if we need more shards. I think the current run is going to time out soon (4h)

This was because _linux-test.yml has a logic of calling `.ci/pytorch/multigpu-test.sh`, that has not been changed since CircleCI days and contained all distributed tests in one shard.

**Comment by malfet** [comment]
Running on i-06e3e360b045be0ac failed with:
```
 5176.776425] ------------[ cut here ]------------
[ 5176.781148] kernel BUG at drivers/pci/msi.c:358!
[ 5176.785771] invalid opcode: 0000 [#1] SMP PTI
[ 5176.790198] Modules linked in: nvidia_modeset(POE) backlight nvidia_uvm(POE) veth nvidia(POE) drm i2c_core xt_conntrack ipt_MASQUERADE nf_nat_masquerade_ipv4 nf_conntrack_netlink nfnetlink xfrm_user xfrm_algo iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack xt_addrtype iptable_filter br_netfilter bridge stp llc overlay sunrpc dm_mirror dm_region_hash dm_log dm_mod dax sb_edac crc32_pclmul ata_piix ghash_clmulni_intel pcbc libata aesni_intel aes_x86_64 crypto_simd mousedev pcc_cpufreq glue_helper psmouse cryptd scsi_mod evdev button ena xen_blkfront crc32c_intel autofs4 [last unloaded: backlight]
[ 5176.851590] CPU: 61 PID: 10372 Comm: nvidia-smi Tainted: P           OE   4.14.252-195.483.amzn2.x86_64 #1
[ 5176.866047] Hardware name: Xen HVM domU, BIOS 4.11.amazon 08/24/2006
[ 5176.875769] task: ffff88f93f304c00 task.stack: ffffc9000d488000
[ 5176.884929] RIP: 0010:free_msi_irqs+0x180/0x1b0
[ 5176.891867] RSP: 0018:ffffc9000d48bb30 EFLAGS: 00010282
[ 5176.900046] RAX: ffff88bb9e280a00 RBX: ffff88bc12065a80 RCX: 000000000000003e
[ 5176.910612] RDX: 0000000000000000 RSI: 00000000000001be RDI: ffff888187805fa0
[ 5176.920901] RBP: 0000000000000000 R08: ffff888187805d88 R09: ffff88bb9e280a00
[ 5176.931267] R10: 0000000000000000 R11: 0000000000000040 R12: ffff88bc8a3732a0
[ 5176.941892] R13: ffff88bc8a373000 R14: ffff88f9881d8000 R15: ffff88bc8810e000
[ 5176.952826] FS:  00007f1123b5b040(0000) GS:ffff88f98ad40000(0000) knlGS:0000000000000000
[ 5176.965268] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 5176.974090] CR2: 000000c001533000 CR3: 0000003a15530003 CR4: 00000000001606e0
[ 5176.984923] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[ 5176.995431] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[ 5177.005945] Call Trace:
[ 5177.010473]  pci_disable_msi+0xf9/0x120
[ 5177.017019]  nv_open_device+0x33d/0x930 [nvidia]
[ 5177.024564]  nvidia_open+0x41b/0x600 [nvidia]
[ 5177.031547]  nvidia_frontend_open+0x53/0x90 [nvidia]
[ 5177.039289]  chrdev_open+0xc4/0x1d0
[ 5177.045121]  ? cdev_put.part.1+0x20/0x20
[ 5177.051340]  do_dentry_open+0x1ef/0x330
[ 5177.057502]  ? __inode_permission+0x85/0xc0
[ 5177.063989]  path_openat+0x6a1/0x16f0
[ 5177.069906]  ? terminate_walk+0x8c/0x100
[ 5177.076293]  ? path_parentat+0x3e/0x80
[ 5177.082378]  ? filename_parentat+0x10b/0x190
[ 5177.089256]  ? memcg_kmem_get_cache+0x50/0x160
[ 5177.096365]  do_filp_open+0x9b/0x110
[ 5177.102329]  ? __d_instantiate+0xac/0xd0
[ 5177.108746]  ? __check_object_size+0xb4/0x190
[ 5177.115723]  ? do_sys_open+0x1bd/0x250
[ 5177.121787]  do_sys_open+0x1bd/0x250
[ 5177.127758]  do_syscall_64+0x67/0x110
[ 5177.133922]  entry_SYSCALL_64_after_hwframe+0x41/0xa6
[ 5177.141679] RIP: 0033:0x7f1123737e8e
[ 5177.147667] RSP: 002b:00007ffd2ff65d30 EFLAGS: 00000246 ORIG_RAX: 0000000000000101
[ 5177.159080] RAX: ffffffffffffffda RBX: 00007ffd2ff66a70 RCX: 00007f1123737e8e
[ 5177.169567] RDX: 0000000000080002 RSI: 00007ffd2ff65dd0 RDI: ffffffffffffff9c
[ 5177.179972] RBP: 00007ffd2ff65dd0 R08: 0000000000000001 R09: 0000000000000000
[ 5177.190559] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000003
[ 5177.200988] R13: 00007ffd2ff65eec R14: 00007f1122c2bda0 R15: 00007f1122c2bda0
[ 5177.211914] Code: 43 14 85 c0 0f 84 d5 fe ff ff 31 ed eb 0f 83 c5 01 39 6b 14 0f 86 c5 fe ff ff 8b 7b 10 01 ef e8 67 a0 c7 ff 48 83 78 70 00 74 e3 <0f> 0b 49 8d b5 a0 00 00 00 e8 52 39 c8 ff e9 c7 fe ff ff 48 8b 
[ 5177.239172] RIP: free_msi_irqs+0x180/0x1b0 RSP: ffffc9000d48bb30
[ 5177.248966] ---[ end trace bd0623e46eee40d0 ]---

```

**Pull request closed without merging**
