### PR TITLE
[Release/2.1.1][DCP] Remove _shard_tensor() call in load_sharded_optimizer_state_dict in optimizer.py #111096

### PR DESCRIPTION
**Pull request by wz337**
Cherry pick into 2.1.1

[original PR: #111096](https://github.com/pytorch/pytorch/pull/111096)
`_shard_tensor()` calls into `dist.all_gather_object()` and this is causing optimizer state dict loading to be super slow.  `dist.all_gather_object()` could be extremely expensive in communication when world_size becomes large. This is reported by users:
image
> We have wrapped this function in logs, and we see that it seems to scale very very poorly with number of GPUs. While it is very fast on 1-2 nodes, it slows down to nearly an hour at scale (480 GPUs). This slowdown increases as we increase GPU count, and it is gradual. This is becoming a major problem for us.
During this period, we see no network activity on wandb so it is not blocked by downloading. I've attached a screenshot of the network graph. You can see it is flat during this period it is idling. The blue line picks up again when it starts downloading data for training after loading the checkpoint is complete.

Workaround: call `FSDP._shard_utils._create_chunk_sharded_tensor()` to construct ShardedTensor without any communication.
With the workaround, user reported drastic improvement:
> btw, we switched to using the version which does not require all-gather and it is SO much faster. Thanks!

Update test for `load_sharded_optimizer_state_dict` so it can potentially test for performance improvements. 
[[load_sharded_optimizer_state_dict](https://github.com/pytorch/pytorch/pull/112825/files)](https://github.com/pytorch/pytorch/pull/112825)

### CODE REVIEW

**Review by fegin — APPROVED** [review]
The original PR is already approved.

**Comment by huydhn** [comment]
One thing that @malfet and @albanD points out with this cherry pick is that it has no regression test, so we are not sure if this should be selected.  Given that 2.2. release will come soon in one month https://dev-discuss.pytorch.org/t/pytorch-release-2-2-0-call-for-features/1629, is this still a required change to include in 2.1.1 patch release?

**Comment by fegin** [comment]
@wz337 what do you think about wait until 2.2?

**Comment by albanD** [comment]
Note that 2.2 branch cut will happen in a little bit more than a month.

**Comment by wz337** [comment]
@fegin, @huydhn, @albanD 
Added more context and updated the unit test to make it potentially able to test performance improvements at scale.
Personally, I have no preference whether it is going in 2.1.1 or 2.2, but it was strongly requested by users.

**Review by atalman — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request merged**
