### PR TITLE
Always unspecialize float in OSS

### PR DESCRIPTION
**Pull request by bobrenjc93**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #138922

Fixes https://github.com/pytorch/pytorch/issues/107277

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @rec

### CODE REVIEW

**Comment by ezyang** [comment]
this no longer draft

**Review by ezyang — APPROVED** [review]
@bobrenjc93 and then I will have to talk to you about deploying in fbcode :)

**Comment by ezyang** [comment]
We need to do a perf run too

**Comment by ezyang** [comment]
image

**Comment by ezyang** [comment]
oh oops we gotta do new benchmark

**Comment by ezyang** [comment]
head run: https://github.com/pytorch/pytorch/actions/runs/11961258248
base run: https://github.com/pytorch/pytorch/actions/runs/11961261664

**Comment by ezyang** [comment]
This doesn't look good:

image

**Comment by ezyang** [comment]
oh it's fake, it's because many torchbench benches failed

**Comment by bobrenjc93** [comment]
@zxd1997066 can you help us run the intel benchmarks on this PR?

**Comment by bobrenjc93** [comment]
I kicked off another run

base: https://github.com/pytorch/pytorch/actions/runs/11966688469
head: https://github.com/pytorch/pytorch/actions/runs/11966690795

**Comment by leslie-fang-intel** [comment]
Hi @ezyang, did it mean the value of float changes will also cause graph recompilation after this PR?

**Comment by leslie-fang-intel** [comment]
> @zxd1997066 @leslie-fang-intel can either of you help us run the intel benchmarks on this PR?

Hi @bobrenjc93, thanks for letting us know. @zxd1997066 could you kindly help to schedule testing to compare the speedup/pass rate number with this PR on 3 suites? cc @chuanqi129

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but there is some slow tests failing after this land' -c nosignal

inductor/test_efficient_conv_bn_eval.py::EfficientConvBNEvalCpuTests::test_basic_cpu [GH job link](https://github.com/pytorch/pytorch/actions/runs/11977626510/job/33396885723) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/6d779d05492813da1c19ac0c562d0d5f8473f27e)

**Comment by leslie-fang-intel** [comment]
> Opposite. We will recompile less. But because all float inputs are now treated as arguments, previously where we could inline constant into compiled code, now it's another argument load. This matters more on CPU I think.

Thanks for the reply. 

- To better understand the changes of behavior: 
   - Is the previous behavior that we wrap the float scalar value into a float tensor (based on the description of this flag: https://github.com/pytorch/pytorch/blob/2e7ba0b194cdb9e1120c88ffc338d88bfcd7beab/torch/_dynamo/config.py#L65-L67) and inline the float tensor as a constant into the compiled code? 
   - But for now, the behavior is the float will be a input argument of compiled function. 
- If the float value is input argument, shouldn't we add some guard to its value? I remember the case of input  integer as argument, when the integer values changed, it will causes recompilation like this one: https://github.com/pytorch/pytorch/issues/132849

**Comment by bobrenjc93** [comment]
@leslie-fang-intel I'd recommend reading this design doc https://docs.google.com/document/d/1HswUSp9H6mg8Vg27mhRk8YzC9q_uf63b6wz-gwx65BQ/edit?pli=1&tab=t.0#heading=h.xvyiqp8tuje6

> inline the float tensor as a constant into the compiled code?

Previously we just inline the float. There is no tensorfication.

> shouldn't we add some guard to its value

If for whatever reason we need to guard, we'll actually fall back specialization. See https://github.com/pytorch/pytorch/pull/140346

**Comment by yf225** [comment]
@bobrenjc93 I believe this might be causing perf regression on torchbench: https://hud.pytorch.org/benchmark/torchbench/inductor_no_cudagraphs?dashboard=torchinductor&startTime=Mon,%2018%20Nov%202024%2022:00:43%20GMT&stopTime=Mon,%2025%20Nov%202024%2022:00:43%20GMT&granularity=hour&mode=training&dtype=amp&deviceName=cuda%20(a100)&lBranch=gh/bobrenjc93/90/head&lCommit=e67d26992e8a473aec6ede13b8cb928208c3df34&rBranch=main&rCommit=1bdb92cbff6f8f6fd1842e8fd9969bca688eaea3

I also bisected on torchbench llama model:
`python benchmarks/dynamo/torchbench.py  --performance --cold-start-latency --inductor --disable-cudagraphs --device cuda --inference --bfloat16 --print-memory --output output.csv --only llama --batch-size 32`
5268754e (11/22 nightly): 2.177902x
995e3079c96: 2.196x
c513f015166: 2.198x
11c786dcb59: 2.160x
ba5253da: 1.748x
51b6126f (11/23 nightly): 1.781900x

**Comment by yf225** [comment]
Discussed in Inductor group chat and the group agrees to revert this PR

**Comment by bobrenjc93** [comment]
new benchmark runs as of 11/25

base: https://github.com/pytorch/pytorch/actions/runs/12023899968
head: https://github.com/pytorch/pytorch/actions/runs/12023903827

**Comment by ezyang** [comment]
Endorsing the NN module spec changes, although we will have to carefully check if this actually fixes all the benchmarks

**Pull request closed without merging**
