### PR TITLE
Update TorchBench pinned commit

### PR DESCRIPTION
**Pull request by huydhn**
~~To match their recent v4.36.2 release https://github.com/huggingface/transformers/commits/v4.36.2.  This is to fix the KeyError showing on release branch https://github.com/pytorch/pytorch/actions/runs/7451512288/job/20279117324#step:16:1336.  I think this can be updated in main too because the current pinned commit is already 4-month old.~~

Check with @desertfire, trying to update TorchBench pinned commit instead.

The test is also failing in main https://github.com/pytorch/pytorch/actions/runs/7467073391/job/20320251143#step:16:1120, but for some reason, it doesn't surface as a failure.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by atalman — APPROVED** [review]
LGTM, given that inductor tests are passing

**Comment by huydhn** [comment]
@desertfire Do you have any insight on why the same failure is silent in main https://github.com/pytorch/pytorch/actions/runs/7467073391/job/20320251143#step:16:1120 while shows up on release branch https://github.com/pytorch/pytorch/actions/runs/7451512288/job/20279117324#step:16:1336?  May be we need to cherry pick something from main to reproduce the same behavior.

**Review by thiagocrepaldi — APPROVED** [review]

**Review by desertfire — APPROVED** [review]
More expected file update is needed.

**Pull request closed without merging**
