### PR TITLE
Document `f` parameter of `torch.save`

### LINKED ISSUE #104359: Behaviour of `ScriptModule.save()`'s `f` parameter is undocumented
The following docstring: https://github.com/pytorch/pytorch/blob/044a8e3305bdff28780cdab757b859abf2fc76d9/torch/jit/_script.py#L711 implies the method works the same as `torch.jit.save`, but it does not: the latter accepts a file-like object, whilst the former silently converts any object to a string and treats it as a path. This should be fixed or documented.

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

### PR DESCRIPTION
**Pull request by ghost**
Fixes #104359
Changing the documentation for a better description of the function torch.save() compared to torch.jit.save()

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by kit1980** [comment]
@JaredLevi18 Please rebase the PR on the latest main: there were some formatting changes in the file recently that may affect the this.

**Pull request closed without merging**
