### PR TITLE
Add autodiff support for a few additional operators

### PR DESCRIPTION
**Pull request by asuhan**
Added aten::{avg_pool2d, log_softmax, max_pool2d_with_indices, threshold},
enabled aten::{expand, view}.

### CODE REVIEW

**Review by apaszke — DISMISSED** [review]
The expect tests are not very robust tests for this functionality. This should go through the gradcheck logic we use for our automated tests.

**Comment by asuhan** [comment]
Agreed, we do need something beyond trace comparison. As far as I can tell https://github.com/pytorch/pytorch/blob/master/torch/autograd/gradcheck.py doesn't hit the autodiff in the JIT, though. What's the canonical way of doing this?

**Comment by asuhan** [comment]
I've added comparisons for the actual values. Still, I assume there's an existing way which might be reused, but couldn't find it.

**Comment by apaszke** [comment]
All of the grad checks are auto-generated based on test specs from other files. See e.g. [those lines](https://github.com/pytorch/pytorch/blob/master/test/test_jit.py#L9598-L9605) and follow the implementation of those functions. It would be better to just add grad checks to nn module tests that you care about. Can you please also remove the expect files? They don't serve any purpose in this case really...

**Review by soumith — APPROVED** [review]
landing with the `ConstantPropagation` pass to unblock. Will fix the formulas to not require ConstantPropagation tomorrow.

**Comment by asuhan** [comment]
Thanks!

**Pull request closed without merging**
