### PR TITLE
[DeviceMesh] Allow flatten API to take in a name for the flatten dim

### PR DESCRIPTION
**Pull request by wz337**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #132779
* #132632

The main motivation for allowing a custom mesh dim name is that the name combining the mesh_dim_names might not be intuitive to users if users want to re-use the flatten result through slicing. 

```
mesh_3d = init_device_mesh("cuda", (2,2,2), mesh_dim_names=("dp","cp","tp")
fsdp_mesh = mesh_3d["dp", "cp"].flatten()

# Without the ability of naming the flatten mesh, users could do:
model = Model(...)
fully_shard(model, device_mesh=fsdp_mesh)
fully_shard(model, device_mesh=mesh_3d["dp_cp"]

# if we allow naming for flatten mesh
fsdp_mesh = mesh_3d["dp", "cp"].flatten(mesh_dim_name="fsdp")
fully_shard(model, device_mesh=mesh_3d["fsdp"]

# For an EP use case:
mesh_3d = init_device_mesh("cuda", (2,2,2), mesh_dim_names=("dp","ep0","ep1")
tp_mesh = mesh_3d["ep0", "ep1"].flatten()

# Without the ability of naming the flatten mesh, users could do:
parallelize(model, device_mesh=tp_mesh)
parallelize(model, device_mesh=mesh_3d["ep0_ep1"]

# if we allow naming for flatten mesh
tp_mesh = mesh_3d["ep0", "ep1"].flatten(mesh_dim_name="tp")
parallelize(model, device_mesh=mesh_3d["tp"])
```

Keeping this change in a separate PR, since there are some questions that need to be resolved for allowing users to pass in a flatten mesh dim name. 

1. Two flattened mesh with the same mesh tensor would be considered different, because `mesh_dim_names` is a part of the equal check for DeviceMesh. 
2. Because of 1, do we want to create new pg for two flattened mesh with the same mesh tensor with different mesh_dim_names? 

If we want to align with the overall DeviceMesh assumption, then the two flattened mesh with two different mesh_dim_name would be considered different, and they would have different underlying pgs. 

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by fegin — APPROVED** [review]

**Review by wanchaol — CHANGES_REQUESTED** [review]
Could we please add some motivation on this PR? I don't feel it's necessary to add this functionality given the tricky facts in the summary. My stand was the same: we should only add a public facing feature when it's absolute necessary to reduce maintainance burden

**Comment by fegin** [comment]
@wanchaol The motivation is from the internal use case. Right now EP use a separate device mesh. We think flatten() can be used to solve the case where we can support EP, (EP1, EP2), which is later flattened for TP. EP1_EP2 will be a confusing name for TP. If this doesn't seem to be a good use case, there are no other use cases in my mind.

**Comment by wz337** [comment]
> Could we please add some motivation on this PR? I don't feel it's necessary to add this functionality given the tricky facts in the summary. My stand was the same: we should only add a public facing feature when it's absolute necessary to reduce maintainance burden

Added an example in the motivation section for discussion.

**Comment by wanchaol** [comment]
Thanks for adding the examples @wz337 and @fegin. I think those looks reasonable and it seems a better UX to users. However I am a little worried about future extensibility of this `flatten` API with this `mesh_dim_name`. Although we decided to restrict `flatten` API to not taking in `start_dim` and `end_dim`, I wonder if we would potentially need them again in the future, and if that's the case, `mesh_dim_name` would need to become `mesh_dim_names`, which is a BC breaking change. Any thoughts on this?

**Comment by wz337** [comment]
> Thanks for adding the examples @wz337 and @fegin. I think those looks reasonable and it seems a better UX to users. However I am a little worried about future extensibility of this `flatten` API with this `mesh_dim_name`. Although we decided to restrict `flatten` API to not taking in `start_dim` and `end_dim`, I wonder if we would potentially need them again in the future, and if that's the case, `mesh_dim_name` would need to become `mesh_dim_names`, which is a BC breaking change. Any thoughts on this?

The current behavior is to have flatten always return a 1D mesh. We will flatten out the mesh no matter whether it's 2D or 3D, but even if we take a `start_dim` and `end_dim`, we should only take a mesh_dim_name for the flatten dim, cuz the rest of the dim should still be the same as the root mesh. To have flatten() as a separate API is a bit more explicit in terms of UX and would allow users to name the flatten mesh dim. Otherwise, we could simply do it through slicing if we don't allow renaming but default naming only. Let me show the 3 UX differences thru the examples below.


```
# 1. HSDP case with flatten() not allowing naming and not taking start_dim and end_dim
mesh_3d = init_device_mesh("cuda", (2,2,2), mesh_dim_names=("replicate", "shard", "cp")
# users need to explicitly flatten before slicing
fsdp_mesh = mesh["shard", "cp"].flatten() 
# assigning this to a variable is a bit weird cuz we don't really use it, but just to allow slicing "shard_cp" in the next line.
fully_shard(model, device_mesh=mesh_3d["replicate", "shard_cp"])

# 2. HSDP case with flatten() allowing naming but not taking start_dim and end_dim
mesh_3d = init_device_mesh("cuda", (2,2,2), mesh_dim_names=("replicate", "shard", "cp")
# users need to explicitly flatten before slicing
fsdp_mesh = mesh["shard", "cp"].flatten(mesh_dim_name="fsdp")
# allow naming for the flatten mesh dims
fully_shard(model, device_mesh=mesh_3d["replicate", "fsdp"])

# 3. HSDP case with flatten() taking start_dim and end_dim
mesh_3d = init_device_mesh("cuda", (2,2,2), mesh_dim_names=("replicate", "shard", "cp")
# users need to explicitly flatten before slicing
hsdp_mesh = mesh["replicate", "shard", "cp"].flatten(start_dim=1, end_dim=2, mesh_dim_name="fsdp")
fully_shard(model, device_mesh=mesh_3d["replicate", "fsdp"])
# or 
fully_shard(model, device_mesh=hsdp_mesh)

# 4. HSDP case without flatten(). Most restricted options but the fewest lines. 
mesh_3d = init_device_mesh("cuda", (2,2,2), mesh_dim_names=("replicate", "shard", "cp")
# flatten is done implicitly through mesh_3d["replicate", "shard_cp"]
fully_shard(model, device_mesh=mesh_3d["replicate", "shard_cp"])
```

Personally, I like #4 but it might be too implicit for users so I want to discuss it with folks. On the other hand, by allowing naming I would imagine we would need quite a few checks (naming needs to be unique).

**Comment by fegin** [comment]
@wz337 the item 4 seems to disappear can you check again?

**Comment by wz337** [comment]
> > Thanks for adding the examples @wz337 and @fegin. I think those looks reasonable and it seems a better UX to users. However I am a little worried about future extensibility of this `flatten` API with this `mesh_dim_name`. Although we decided to restrict `flatten` API to not taking in `start_dim` and `end_dim`, I wonder if we would potentially need them again in the future, and if that's the case, `mesh_dim_name` would need to become `mesh_dim_names`, which is a BC breaking change. Any thoughts on this?
> 
> The current behavior is to have flatten always return a 1D mesh. We will flatten out the mesh no matter whether it's 2D or 3D, but even if we take a `start_dim` and `end_dim`, we should only take a mesh_dim_name for the flatten dim, cuz the rest of the dim should still be the same as the root mesh. To have flatten() as a separate API is a bit more explicit in terms of UX and would allow users to name the flatten mesh dim. Otherwise, we could simply do it through slicing if we don't allow renaming but default naming only. Let me show the 3 UX differences thru the examples below.
> 
> ```
> # 1. HSDP case with flatten() not allowing naming and not taking start_dim and end_dim
> mesh_3d = init_device_mesh("cuda", (2,2,2), mesh_dim_names=("replicate", "shard", "cp")
> # users need to explicitly flatten before slicing
> fsdp_mesh = mesh["shard", "cp"].flatten() 
> # assigning this to a variable is a bit weird cuz we don't really use it, but just to allow slicing "shard_cp" in the next line.
> fully_shard(model, device_mesh=mesh_3d["replicate", "shard_cp"])
> 
> # 2. HSDP case with flatten() allowing naming but not taking start_dim and end_dim
> mesh_3d = init_device_mesh("cuda", (2,2,2), mesh_dim_names=("replicate", "shard", "cp")
> # users need to explicitly flatten before slicing
> fsdp_mesh = mesh["shard", "cp"].flatten(mesh_dim_name="fsdp")
> # allow naming for the flatten mesh dims
> fully_shard(model, device_mesh=mesh_3d["replicate", "fsdp"])
> 
> # 3. HSDP case with flatten() taking start_dim and end_dim
> mesh_3d = init_device_mesh("cuda", (2,2,2), mesh_dim_names=("replicate", "shard", "cp")
> # users need to explicitly flatten before slicing
> hsdp_mesh = mesh["replicate", "shard", "cp"].flatten(start_dim=1, end_dim=2, mesh_dim_name="fsdp")
> fully_shard(model, device_mesh=mesh_3d["replicate", "fsdp"])
> # or 
> fully_shard(model, device_mesh=hsdp_mesh)
> 
> # 4. HSDP case without flatten(). Most restricted options but the fewest lines. 
> mesh_3d = init_device_mesh("cuda", (2,2,2), mesh_dim_names=("replicate", "shard", "cp")
> # flatten is done implicitly through mesh_3d["replicate", "shard_cp"]
> fully_shard(model, device_mesh=mesh_3d["replicate", "shard_cp"])
> ```
> 
> Personally, I like #4 but it might be too implicit for users so I want to discuss it with folks. On the other hand, by allowing naming I would imagine we would need quite a few checks (naming needs to be unique).



> @wz337 the item 4 seems to disappear can you check again?

Oh I just meant the 4th option, somehow it gets linked to an issue.

**Comment by wz337** [comment]
Based on the discussion, I am gonna go with ._flatten() without taking in a mesh_dim_name for now, but keeping ._flatten() as a separate API would provide with extensibility later.

**Pull request closed without merging**
