### PR TITLE
[export][serde] Allow dynamo to trace through sym_size.int

### PR DESCRIPTION
**Pull request by larryliu0820**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #104235
* #104227

Add `sym_size.int` in `builder.py` to allow dynamo to trace through sym_size.int.
Also fix a small issue in `exported_program.py`.

This enables retrace for `ExportedProgram`.

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78

### CODE REVIEW

**Review by angelayi — APPROVED** [review]

**Comment by zhxchen17** [comment]
@larryliu0820 before this is landed, I'm a bit confused why this works. So the value returned from sym_size() could be a SymInt, which means if we use ConstVariable we are gonna bake in the value in the dynamo generated graph? What's the difference between ConstaVariable and SymNodeVariable here?

**Review by ezyang — CHANGES_REQUESTED** [review]
I agree with the confusion, though for a different reason.

To answer your question, this branch only triggers when sym_size returns an int, meaning that it was already specialized. No extra specialization happening.

However, there is no reason to record sym_size into the graph here. It has no side effects!

**Comment by zhxchen17** [comment]
@larryliu0820 I also chatted with @tugsbayasgalan a bit and to me a better solution is to simply not insert extra ops after tracing. we will eventually make _runtime_assertions=False default, so I think you don't need to go with particular solution rn.

**Comment by larryliu0820** [comment]
ok so this is due to sym_size checks introduced into the graph. Creating https://github.com/pytorch/pytorch/issues/104882 to track that and closing this PR.

**Pull request closed without merging**
