### PR TITLE
Make jit version of layer_norm work with empty tensor on cuda

### PR DESCRIPTION
**Pull request by ggoossen**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#29292 Make jit version of layer_norm work with empty tensor on cuda**

n == 0 requires special logic as .view(1, n, -1) gives an error if n == 0

Not sure how the specific code is reached, after tracing on cpu, I was only getting the error when running with no_grad on cuda.

Differential Revision: [D18350915](https://our.internmc.facebook.com/intern/diff/D18350915/)

### CODE REVIEW

**Comment by ggoossen** [comment]
@apaszke  / @wanchaol  can you take a look at this . test_fuse_decompose_normalization is failing, but I'm not sure what exactly it is testing.

**Comment by wanchaol** [comment]
@ggoossen can you give more info on how this is exactly failing? `n` couldn't be 0  here as i could see so I am not sure if this really fix the problem.

**Comment by ggoossen** [comment]
@wanchaol  if input.size(0) == 0 then n will be zero. (I'm trying to get this to work for something with variable size, include in some cases 0, which currently doesn't work, but this change fixes that.

**Review by wanchaol — APPROVED** [review]
This make sense to me. There's a ongoing executor change that might affect the failing test for test_fuse_decompose_normalization, let's wait for the new ci to see if it works

**Comment by ggoossen** [comment]
@wanchaol test_fuse_decompose_normalization is still failing: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-test2/55384/console
any ideas what is causing it?

**Comment by wanchaol** [comment]
Seems like windows is still in profilingmode.legacy, we should turn the profiling on windows as well. cc @Krovatkin

**Comment by wanchaol** [comment]
@ggoossen https://github.com/pytorch/pytorch/pull/29782 this will ensure that windows don't complain about this test. Let's try rebasing after it landed.

**Review by wanchaol — CHANGES_REQUESTED** [review]
OK. I know what's happened here. There is some fundamental limitation if fusion happening with control flow. You are adding a early return inside the JIT graph, the early return in the compiler will be changed from
```python
def foo():
   if blah():
        return 5
   BLOCK 1
   return 3
```
to
```python
def foo():
   if blah():
        ret = 5
   else:
     BLOCK 1
     ret = 3
  return ret
```
Previously BLOCK1 can be fused together with other ops outside `foo`, but if we have early return, it will make BLOCK1 into the else branch and we could not fuse an outer scope operation with BLOCK1 then, like the below could not be fused.

```python
def try_fuse_fail():
    # we could not fuse these two together since BLOCK1
    # if inside the ELSE block of the early returned IF
    ret = foo()
    ret + 2 * 5 + 3
```

This triggered the failure in the CI now and will likely to regress the existing performance. We will need to think of a way that express `layernorm` in a way that works with `n==0`. 

I will try to see what we could do here. Request changes for now until we clear how to solve this problem. To make it work on variable size, can we avoid the `size(0)` case for now? it does not make too much sense to apply layernorm on an empty tensor anyway.

**Comment by ggoossen** [comment]
@wanchaol Another way of handling this would be not use -1 in the view, but actually calculate this value (maybe `_ncf_view` also needs some adjustments).
I can make my own wrapper around layer_norm handling the 0 case.

**Pull request closed without merging**
