### PR TITLE
Use expecttest from PyPI

### PR DESCRIPTION
**Pull request by samestep**
This PR removes `torch/testing/_internal/expecttest.py` in favor of https://github.com/ezyang/expecttest. See also https://github.com/ezyang/ghstack/pull/71.

**Test plan:**

CI.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Review by walterddr — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by samestep** [comment]
> If you make a change to any file that would result in a new docker image, please let us know so that we can make the corresponding update to Jenkins. Thanks.

@jeffdaily Oh! My apologies, I didn't realize this was the case. I'm guessing this also applies to #60697 then, for instance?

Also, is this something that would be useful to automate? That is, when a PR is opened that touches `.circleci/docker` (or is modified to touch `.circleci/docker`), notify you somehow?

**Comment by jeffdaily** [comment]
Unfortunately, yes, this would also apply to #60697.  Any automation would be welcome.  We are merely limping along until a better solution exists (GitHub Actions perhaps).

What we've tried to do in the past is to trigger a manual job on Jenkins with the new docker image tag once the docker build is successful here.

**Comment by VitalyFedyunin** [comment]
ROCM builds fails with 
```
ModuleNotFoundError: No module named 'expecttest'
```

**Comment by samestep** [comment]
> ROCM builds still fails with
> 
> ```
> ModuleNotFoundError: No module named 'expecttest'
> ```

@jeffdaily

**Comment by jeffdaily** [comment]
> ROCM builds still fails with
> 
> ```
> ModuleNotFoundError: No module named 'expecttest'
> ```

@VitalyFedyunin I updated Jenkins CI 3 hours back -- when did your ROCm CI job start?  There are other ROCm CI jobs that have gotten beyond the expecttest failure since then.  On your PR, try using `@pytorchbot retest this please` and see if the new ROCm CI signal is better.

**Pull request closed without merging**
