### PR TITLE
Avoid copies in matmul (no ghstack)

### PR DESCRIPTION
**Pull request by lezcano**
Resubmit of https://github.com/pytorch/pytorch/pull/76828 without using ghstack so that @ngimel can import it and help me debug the issue why it was reverted.

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Internal tests look good but require mobile models reexport, I'll check who's doing it now.

**Review by malfet — APPROVED** [review]

**Comment by ngimel** [comment]
I don't know why merge failed.

**Comment by ngimel** [comment]
ok internal PR unlinked, should be mergeable now

**Pull request closed without merging**
