### PR TITLE
[jiterator] neg: complex

### PR DESCRIPTION
**Pull request by khushi-411**
Follows: #74748

cc @kshitij12345!

### CODE REVIEW

**Comment by khushi-411** [comment]
Hi, @kshitij12345!
That worked!! Rebasing resolved the failures. Thanks for your input! :)

Please take a look :)

**Review by kshitij12345 — APPROVED** [review]
LGTM

Thanks @khushi-411 

cc: @anjali411

**Comment by khushi-411** [comment]
Hi, @anjali411! Gentle ping :)

**Review by anjali411 — APPROVED** [review]

**Pull request closed without merging**
