### PR TITLE
Update release note bot to actually ping people

### PR DESCRIPTION
**Pull request by albanD**

### CODE REVIEW

**Comment by xsacha** [comment]
What if the user doesn't have the ability to change labels? I get pinged but can't actually resolve the issue.

**Comment by seemethere** [comment]
We could probably add functionality to probot to actually allow people to use chatops to apply release notes labels.

Similar to

```
@pytorchbot label {label_name}
```

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
> We could probably add functionality to probot to actually allow people to use chatops to apply release notes labels.
> 
> Similar to
> 
> ```
> @pytorchbot label {label_name}
> ```

Good idea, filed https://github.com/pytorch/test-infra/issues/190

**Comment by anjali411** [comment]
thanks!

**Pull request closed without merging**
