### PR TITLE
[MPS] Specialized memory pool for scalar values.

### PR DESCRIPTION
**Pull request by kulinseth**
- Add buffer usage and debug verbosity flags to MPSAllocator
- Add high_watermark_ration to limit the memory allocation

### CODE REVIEW

**Comment by malfet** [comment]
Hmm, why this is needed?

**Comment by malfet** [comment]
Hmm, can it be split into 2 PRs: one that adds all those new allocator options and another than changes scalar allocations for ops

**Review by razarmehr — APPROVED** [review]
Looks good.

**Comment by kulinseth** [comment]
> Hmm, can it be split into 2 PRs: one that adds all those new allocator options and another than changes scalar allocations for ops

Actually they are both related and needed to enable this feature .

**Pull request closed without merging**
