### PR TITLE
[caffe2][nomnigraph] Make conv relu fusion more generic

### PR DESCRIPTION
**Pull request by bwasti**
@jerryzh168 This should help with various non-conv activation fusion transformations

### CODE REVIEW

**Comment by jerryzh168** [comment]
can we have the Conv + Relu = ConvRelu helper functions as well?

**Review by yinghai — APPROVED** [review]
Great! 

You can do 
`using fuseConvRelu = fuseActivation<repr::Conv, repr::Relu>;` if this is the kind of helper you mean.

**Comment by jerryzh168** [comment]
@yinghai I'm talking about fusing Conv and Relu into a new operator called ConvRelu actually.
I believe the existing code only fuses Conv Relu into Conv + some arguments.

**Comment by yinghai** [comment]
@jerryzh168 Oh, it does. The trick is in the postprocessing. Check an example here: https://github.com/pytorch/pytorch/blob/master/caffe2/opt/optimize_ideep.cc#L33

**Comment by jerryzh168** [comment]
@yinghai Oh I see, thanks!

**Comment by jerryzh168** [comment]
Still, can we create a helper to do that? I can add a PR later

**Pull request merged**
