### PR TITLE
Add Full block support to flex_decoding

### PR DESCRIPTION
**Pull request by joydddd**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #132157
* #131559
* __->__ #131404

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by joydddd** [comment]
Decoding speed on noop: 
1.121 (no block sparsity) 
-> https://github.com/pytorch/pytorch/pull/130884 1.076 (full mask 128x128 blocks) / 1.094 (empty mask)
-> (This PR) 1.067 (full mask 128x128 blocks) / 1.087(empty mask)


| Type    |   Speedup | score_mod     | mask_mod   | dtype          | shape(B,Hq,M,Hkv,N,D)     |
|---------|-----------|---------------|------------|----------------|---------------------------|
| Average |     1.087 |               |            |                |                           |
| Max     |     1.412 | noop_gqa      |            | torch.bfloat16 | (1, 16, 1, 2, 32768, 128) |
| Min     |     0.853 | head_bias_gqa |            | torch.bfloat16 | (32, 16, 1, 1, 4096, 64)  |

**Review by yanboliang — APPROVED** [review]
LGTM for me, but I'd let @Chillee to make the final call.

**Pull request closed without merging**
