### PR TITLE
[dynamo] reland map/zip iterator related changes

### PR DESCRIPTION
**Pull request by williamwen42**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135074

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

Differential Revision: [D62211019](https://our.internmc.facebook.com/intern/diff/D62211019)

### CODE REVIEW

**Comment by williamwen42** [comment]
@williamwen42 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D62211019).

**Review by jansel — APPROVED** [review]

**Comment by anijain2305** [comment]
Can you add a test or a comment on why it failed internally?

**Review by anijain2305 — APPROVED** [review]

**Review by mlazos — APPROVED** [review]

**Comment by williamwen42** [comment]
Ran the previously hanging internal command and the dynamo logs don't reveal any significant issues (i.e. large number of graph breaks or recompiles). Also ran the commit before and after the original revert PR (https://github.com/pytorch/pytorch/pull/132528) and discovered that compile time is approximately the same (~1.5 hours) when inductor cache is disabled (`TORCHINDUCTOR_FORCE_DISABLE_CACHES=1`). This leads me to believe that the original stack of PRs resulted in increased compile times because Dynamo traced slightly different graphs, leading to differing caching behavior.

**Pull request closed without merging**
