### PR TITLE
Padding in lp pool

### PR DESCRIPTION
**Pull request by calvinleenyc**
Right now, when I want to use this layer, I manually pad it myself beforehand, which seems silly.

### CODE REVIEW

**Comment by ezyang** [comment]
This gonna need a test.

@pytorchbot test this please

**Comment by ryanneph** [comment]
Forgive me if I'm missing something obvious, but why wasn't this feature ever merged? It seems like it would be useful to obtain parity between the interfaces for all of the pooling functions.

**Comment by calvinleenyc** [comment]
You're not missing anything - feel free to open an identical PR!  (Unfortunately, I deleted the original repository, so I can't just reopen this one.)

**Pull request closed without merging**
