### PR TITLE
Adding Compare in torch.utils.benchmark documentation

### PR DESCRIPTION
**Pull request by Ghelfi**
`torch.utils.benchmark.Compare` is not directly exposed in torch.utils.benchmark documentation.

I think this is a valuable resource to add since it can help people embracing the torch benchmark way of doing things, and help people building documentation towards it.

### CODE REVIEW

**Review by mikaylagawarecki — APPROVED** [review]
Thanks

edit: Actually it looks like there are [no docstrings for this class](https://github.com/pytorch/pytorch/blob/main/torch/utils/benchmark/utils/compare.py?fbclid=IwAR3AoMfw9O06QV5CanOe-Y_kD_N4k6Y-_34kPTEd8ZstXyM87kz3oBNdtzk#L269). Would you be willing to add them?

**Comment by Ghelfi** [comment]
Added a docstring.

**Review by mikaylagawarecki — COMMENTED** [review]
Could you also add a docstring for all the non private methods of compare please

**Comment by mikaylagawarecki** [comment]
You might need to run lintrunner to fix lint

**Comment by Ghelfi** [comment]
Sorry for that, my pre-commit was not activated...

**Pull request closed without merging**
