### PR TITLE
Added a check in combinations to avoid memory allocation

### LINKED ISSUE #71082: `torch.combinations` will allocate large memory when `r` is greater than the length of input
### 🐛 Describe the bug

`torch.combinations` will malloc large memory when `r` is greater than the length of input. In fact, it will an empty tensor since `r` is greater than the length. Therefore, I think it should not allocate a very large memory.

```python
import torch
input_tensor = torch.randint(-1,1,[3], dtype=torch.int64)
input = input_tensor.clone()
r = 100
print(torch.combinations(input, r=r))
# killed
```

### Versions

pytorch: 1.10.1

### PR DESCRIPTION
**Pull request by vitrioil**
Fixes #71082

### CODE REVIEW

**Comment by cpuhrsch** [comment]
@zasdfgbnm @pmeier - I'm relying on your to review this and can follow up on an accept to merge this.

**Comment by zasdfgbnm** [comment]
Test failures are real

**Comment by pmeier** [comment]
@cpuhrsch Not sure how selected me for review, but I don't recall any connection to this op.

**Comment by vitrioil** [comment]
@zasdfgbnm I understood the mistake I am making. I am severing the graph and hence grad_fn is not preserved. What I am wondering now is how do I 'somehow' convert tensor to an empty tensor while preserving the `requires_grad` and `grad_fn`?

Or in this case it doesn't make sense to add this check?

**Pull request closed without merging**
