### PR TITLE
Fix index overflow in ConvTranspose3d

### LINKED ISSUE #32866: CUDA error: an illegal memory access was encountered when using output_padding in nn.ConvTranspose3d
I'm building a simple Encoder-Decoder architecture for video with 3D Convolutions and TransposedConv. The aim is make it fully convolutional so it would work with any video size.
The Encoder looks like this:
```  
    padding = int((kernel_size - 1)/2) #kernel_size = 5
    self.network = nn.Sequential(    
       nn.Conv3d(3, 128, kernel_size=kernel_size, stride=1, padding=padding),
       nn.BatchNorm3d(128, affine=False),
       nn.ReLU(True),

       nn.Conv3d(128, 64, kernel_size=kernel_size, stride=2, padding=padding),
       nn.BatchNorm3d(64, affine=False),
       nn.ReLU(True),

       nn.Conv3d(64, 64, kernel_size=kernel_size, stride=2, padding=padding),
       nn.BatchNorm3d(64, affine=False),
       nn.ReLU(True),

       nn.Conv3d(64, 24, kernel_size=kernel_size, stride=1, padding=padding),
       nn.BatchNorm3d(output_channels, affine=False),
       nn.ReLU(True)
    )
````
And here is the Decoder:
```
    padding = int((kernel_size - 1)/2) #kernel_size = 5
    self.network = nn.Sequential( 
       nn.ConvTranspose3d(self.input_channels, 64, kernel_size=kernel_size, stride=1, padding=padding),
       nn.BatchNorm3d(64, affine=False),
       nn.ReLU(True),
    
       nn.ConvTranspose3d(64, 64, kernel_size=kernel_size, stride=2, padding=padding, output_padding=1),
       nn.BatchNorm3d(64, affine=False),
       nn.ReLU(True),

       nn.ConvTranspose3d(64, 128, kernel_size=kernel_size, stride=2, padding=padding, output_padding=1),
       nn.BatchNorm3d(128, affine=False),
       nn.ReLU(True),

       nn.Conv3d(128, self.output_channels, kernel_size=kernel_size, stride=1, padding=padding),
    )
````
I trained the model with input size of (NxCxHxW) = (16x3x112x112). The outputs of each layer looks like this:

```
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
================================================================
            Conv3d-1    [-1, 128, 16, 112, 112]          48,128
       BatchNorm3d-2    [-1, 128, 16, 112, 112]               0
              ReLU-3    [-1, 128, 16, 112, 112]               0
            Conv3d-4        [-1, 64, 8, 56, 56]       1,024,064
       BatchNorm3d-5        [-1, 64, 8, 56, 56]               0
              ReLU-6        [-1, 64, 8, 56, 56]               0
            Conv3d-7        [-1, 64, 4, 28, 28]         512,064
       BatchNorm3d-8        [-1, 64, 4, 28, 28]               0
              ReLU-9        [-1, 64, 4, 28, 28]               0
           Conv3d-10        [-1, 24, 4, 28, 28]         192,024
      BatchNorm3d-11        [-1, 24, 4, 28, 28]               0
             ReLU-12        [-1, 24, 4, 28, 28]               0
        Encoder3D-13        [-1, 24, 4, 28, 28]               0
   
  ConvTranspose3d-16        [-1, 64, 4, 28, 28]         192,064
      BatchNorm3d-17        [-1, 64, 4, 28, 28]               0
             ReLU-18        [-1, 64, 4, 28, 28]               0
  ConvTranspose3d-19        [-1, 64, 8, 56, 56]         512,064
      BatchNorm3d-20        [-1, 64, 8, 56, 56]               0
             ReLU-21        [-1, 64, 8, 56, 56]               0
  ConvTranspose3d-22    [-1, 128, 16, 112, 112]       1,024,128
      BatchNorm3d-23    [-1, 128, 16, 112, 112]               0
             ReLU-24    [-1, 128, 16, 112, 112]               0
           Conv3d-25      [-1, 3, 16, 112, 112]          48,003
        Decoder3D-26      [-1, 3, 16, 112, 112]               0
================================================================
````
After the the model got trained, I tested in on a UCF-101 video sequence of size (Frames x Width x Height) = (16 x 342 x 256) with `os.environ["CUDA_LAUNCH_BLOCKING"] = "1"` and got this error:
```
Traceback (most recent call last):
  File "reconstruct.py", line 80, in <module>
    torchsummary.summary(model, dataloader.dataset[0].shape)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/namle/VCM/E2E/Model/model.py", line 57, in forward
    x_hat = self.decoder(y)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/namle/VCM/E2E/AutoEncoder/model3d.py", line 84, in forward
    x = self.network(x)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/namle/anaconda3/envs/condapy3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 921, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: CUDA error: an illegal memory access was encountered
````
However if I ran the code on CPU and not using CUDA it will output a frame sequence of size (344 x 256) which is 2 pixels more in its width.
Another way to make to code run is at inference time change the output_padding in both TransposedConv layers in the Decoder to 0. Then I would get this sequence of size (341 x 253)

I hope this has something to do with the arithmetic as in this paper https://arxiv.org/pdf/1603.07285.pdf, rather than a bug. I'd appreciate if you can point me into the right direction, so that my model can take in any video size and reconstruct it to the same size automatically.

cc @ezyang @gchanan @zou3519 @ngimel

### PR DESCRIPTION
**Pull request by peterbell10**
Fixes #32866

The memory error in the issue is caused by `int` overflowing in `col2vol`. This version using mixed 32-bit and 64-bit indexing calculation lifts the maximum indexing possible without compromising the performance of `ConvTranspose3d`. vs 20-30% regression with pure 64-bit indexing.

This requires that `input.numel() <= UINT_MAX`, and `channels * kernel.numel() <= UINT_MAX` otherwise it raises an error. Previously, the code would crash or give incorrect results unless `input.numel() * kernel.numel() <= INT_MAX`.

Note that the test is a minimised reproducer for the issue.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Could you post your perf numbers to this PR? Thanks!

**Comment by ezyang** [comment]
Your test is failing in ASAN:

```
4s)
May 25 20:03:07   test_conv_transposed_large_cpu (__main__.TestTorchDeviceTypeCPU) ... Traceback (most recent call last):
May 25 20:03:07   File "test/run_test.py", line 691, in <module>
May 25 20:03:07     main()
May 25 20:03:07   File "test/run_test.py", line 684, in main
May 25 20:03:07     raise RuntimeError(message)
May 25 20:03:07 RuntimeError: test_torch failed! Received signal: SIGKILL
```

**Comment by peterbell10** [comment]
I used this simple `timeit` benchmark:
```python
In [1]: conv = torch.nn.ConvTranspose3d( 
   ...:             32, 128, kernel_size=5, 
   ...:             stride=2, padding=2, output_padding=1).cuda()                         

In [2]: x = torch.rand([1, 32, 8, 64, 172]).cuda() 

In [3]: %timeit conv(x); torch.cuda.synchronize()
```

master: 39.3 ms
This PR: 36.3 ms

**Comment by rohan-varma** [comment]
I think this PR may be breaking ASAN tests on master: https://app.circleci.com/pipelines/github/pytorch/pytorch/174414/workflows/a09cc4b2-6af1-4cac-af9d-a95c874ca328/jobs/5602961/steps,
https://app.circleci.com/pipelines/github/pytorch/pytorch/174429/workflows/589ea76b-f16f-46bd-b6c8-094bcd25f429/jobs/5603295/steps
https://app.circleci.com/pipelines/github/pytorch/pytorch/174593/workflows/73c8b764-27c9-4e72-a687-5d82d2c3fe15/jobs/5605892/steps

**Comment by ngimel** [comment]
It's likely just oom'ing on cpu. @peterbell10 you can skip this test on the cpu to fix the failure.

**Pull request closed without merging**
