### PR TITLE
Do not use FixedDivisor in ROCM order switch op

### PR DESCRIPTION
**Pull request by bddppq**
Fix the recent order_switch_test failure in ROCM CI

### CODE REVIEW

**Comment by bddppq** [comment]
Triggered ROCM build here https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang3.8-rocm1.7.1-ubuntu16.04-trigger-test/12441/

**Comment by bddppq** [comment]
Hmm doesn't fix the failure, I guess the issue is not in the magic bits operations but rather passing a non-pod struct to kernel function. @petrex Does it ring a bell?

**Comment by bddppq** [comment]
New trigger https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang3.8-rocm1.7.1-ubuntu16.04-trigger-test/12450/

**Review by xiaomengy — APPROVED** [review]
LGTM

**Comment by petrex** [comment]
@rohithkrn

**Pull request closed without merging**
