### PR TITLE
Fix test_det_logdet_slogdet_batched on PowerPC

### LINKED ISSUE #25172: test_det_logdet_slogdet_batched (in test_cuda.py) fails on ppc64le
## 🐛 Bug

```
    @unittest.skipIf(not TEST_MAGMA, "no MAGMA library detected")
    def test_det_logdet_slogdet_batched(self):
        _TestTorchMixin._test_det_logdet_slogdet_batched(self, 'cuda')
```

https://github.com/pytorch/pytorch/blob/v1.2.0/test/test_cuda.py#L2224 fails for me on ppc64le.

On following the test through to https://github.com/pytorch/pytorch/blob/v1.2.0/test/test_torch.py#L6558 and then testing all the different possible combinations, the failures are seen for all combinations of `matsize` and `batchdims` in both `run_test(matsize, batchdims, mat_chars=['sing'])` and `run_test(matsize, batchdims, mat_chars=['sing', 'non_sing'])` (the other tests in there are fine).

I went through and commented out the assert statements and printed out the tensors that were being compared for each of the combinations:
```
3
(3,)
    run_test(matsize, batchdims, mat_chars=['sing'])
        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([-2.5175e-35, -1.5868e-38, -9.0737e-36], device='cuda:0')
tensor([-4.0940e-35,  0.0000e+00,  0.0000e+00], device='cuda:0')

        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([nan, nan, nan], device='cuda:0')
tensor([nan, -inf, -inf], device='cuda:0')

        self.assertEqual(sign_value, actual_value[0], allow_inf=True)
tensor([-1.,  0.,  0.], device='cuda:0')
tensor([-1., -1., -1.], device='cuda:0')

        self.assertEqual(expected_value, actual_value[1], allow_inf=True)
tensor([-79.1810,     -inf,     -inf], device='cuda:0')
tensor([-79.6672, -87.0365, -80.6877], device='cuda:0')

    run_test(matsize, batchdims, mat_chars=['sing', 'non_sing'])
        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([ 3.8190e-34, -3.9619e-01, -3.5083e-33], device='cuda:0')
tensor([ 6.4256e-34, -3.9619e-01, -1.0143e-32], device='cuda:0')

        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([-76.9479,      nan,      nan], device='cuda:0')
tensor([-76.4276,      nan,      nan], device='cuda:0')

        self.assertEqual(sign_value, actual_value[0], allow_inf=True)
tensor([ 1., -1., -1.], device='cuda:0')
tensor([ 1., -1., -1.], device='cuda:0')

        self.assertEqual(expected_value, actual_value[1], allow_inf=True)
tensor([-76.4276,  -0.9259, -73.6685], device='cuda:0')
tensor([-76.9479,  -0.9259, -74.7302], device='cuda:0')


3 
(5, 3)
    run_test(matsize, batchdims, mat_chars=['sing'])
        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([[ 1.7500e-33, -3.9282e-36,  4.5183e-36],
        [ 9.6257e-34,  8.1698e-35, -1.6681e-40],
        [ 1.2369e-34,  1.6281e-35, -1.5470e-33],
        [ 2.4720e-33, -2.6346e-33, -6.8148e-35],
        [ 3.7382e-35, -1.8944e-33,  5.6313e-35]], device='cuda:0')
tensor([[ 0.0000e+00,  0.0000e+00, -0.0000e+00],
        [ 1.0046e-33,  6.8543e-35, -0.0000e+00],
        [-0.0000e+00, -0.0000e+00,  0.0000e+00],
        [ 2.3483e-33,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -2.2742e-33,  0.0000e+00]], device='cuda:0')
  
        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([[-75.4257,      nan, -81.3849],
        [-76.0235, -78.4900,      nan],
        [-78.0753, -80.1031,      nan],
        [-75.0803,      nan,      nan],
        [-79.2719,      nan, -78.8621]], device='cuda:0')
tensor([[    -inf,     -inf,     -inf],
        [-75.9808, -78.6656,     -inf],
        [    -inf,     -inf,     -inf],
        [-75.1316,     -inf,     -inf],
        [    -inf,      nan,     -inf]], device='cuda:0')
  
        self.assertEqual(sign_value, actual_value[0], allow_inf=True)
tensor([[ 0.,  0., -0.],
        [ 1.,  1., -0.],
        [-0., -0.,  0.],
        [ 1.,  0.,  0.],
        [ 0., -1.,  0.]], device='cuda:0')
tensor([[ 1., -1.,  1.],
        [ 1.,  1., -1.],
        [ 1.,  1., -1.],
        [ 1., -1., -1.],
        [ 1., -1.,  1.]], device='cuda:0')
  
        self.assertEqual(expected_value, actual_value[1], allow_inf=True)
tensor([[    -inf,     -inf,     -inf],
        [-75.9808, -78.6656,     -inf],
        [    -inf,     -inf,     -inf],
        [-75.1316,     -inf,     -inf],
        [    -inf, -75.1637,     -inf]], device='cuda:0')
tensor([[-75.4257, -81.5249, -81.3849],
        [-76.0235, -78.4900, -91.5917],
        [-78.0753, -80.1031, -75.5490],
        [-75.0803, -75.0166, -78.6714],
        [-79.2719, -75.3464, -78.8621]], device='cuda:0')

    run_test(matsize, batchdims, mat_chars=['sing', 'non_sing'])
        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([[-7.2073e-35, -9.6858e-01,  2.1245e-34],
        [-2.1929e-02, -3.3690e-33,  8.4981e-02],
        [ 2.3438e-36,  8.2995e-01, -4.4813e-33],
        [ 2.1107e+00,  3.5198e-34, -1.5583e+00],
        [ 1.3380e-36,  2.1991e+00, -2.2806e-34]], device='cuda:0')
tensor([[-0.0000e+00, -9.6858e-01,  0.0000e+00],
        [-2.1929e-02, -2.5940e-33,  8.4981e-02],
        [-0.0000e+00,  8.2995e-01, -0.0000e+00],
        [ 2.1107e+00,  3.0731e-34, -1.5583e+00],
        [ 2.6372e-36,  2.1991e+00, -0.0000e+00]], device='cuda:0')

        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([[     nan,      nan, -77.5343],
        [     nan,      nan,  -2.4653],
        [-82.0413,  -0.1864,      nan],
        [  0.7470, -77.0295,      nan],
        [-82.6019,   0.7880,      nan]], device='cuda:0')
tensor([[    -inf,      nan,     -inf],
        [     nan,      nan,  -2.4653],
        [    -inf,  -0.1864,     -inf],
        [  0.7470, -77.1652,      nan],
        [-81.9234,   0.7880,     -inf]], device='cuda:0')

        self.assertEqual(sign_value, actual_value[0], allow_inf=True)
tensor([[-0., -1.,  0.],
        [-1., -1.,  1.],
        [-0.,  1., -0.],
        [ 1.,  1., -1.],
        [ 1.,  1., -0.]], device='cuda:0')
tensor([[-1., -1.,  1.],
        [-1., -1.,  1.],
        [ 1.,  1., -1.],
        [ 1.,  1., -1.],
        [ 1.,  1., -1.]], device='cuda:0')

        self.assertEqual(expected_value, actual_value[1], allow_inf=True)
tensor([[       -inf, -3.1922e-02,        -inf],
        [-3.8199e+00, -7.5032e+01, -2.4653e+00],
        [       -inf, -1.8638e-01,        -inf],
        [ 7.4703e-01, -7.7165e+01,  4.4361e-01],
        [-8.1923e+01,  7.8803e-01,        -inf]], device='cuda:0')
tensor([[-7.8615e+01, -3.1922e-02, -7.7534e+01],
        [-3.8199e+00, -7.4771e+01, -2.4653e+00],
        [-8.2041e+01, -1.8638e-01, -7.4485e+01],
        [ 7.4703e-01, -7.7029e+01,  4.4361e-01],
        [-8.2602e+01,  7.8803e-01, -7.7463e+01]], device='cuda:0')


5
(3,)
    run_test(matsize, batchdims, mat_chars=['sing'])
        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([ 1.0570e-49, -1.6987e-49,  9.0382e-51], device='cuda:0')
tensor([ 0.0000e+00, -4.2903e-49,  3.6495e-50], device='cuda:0')

        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([-112.7712,       nan, -115.2304], device='cuda:0')
tensor([     -inf,       nan, -113.8347], device='cuda:0')

        self.assertEqual(sign_value, actual_value[0], allow_inf=True)
tensor([ 0., -1.,  1.], device='cuda:0')
tensor([ 1., -1.,  1.], device='cuda:0')
  
        self.assertEqual(expected_value, actual_value[1], allow_inf=True)
tensor([     -inf, -111.3703, -113.8347], device='cuda:0')
tensor([-112.7712, -112.2968, -115.2304], device='cuda:0')
  
    run_test(matsize, batchdims, mat_chars=['sing', 'non_sing'])
        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([-7.0089e-49, -2.0986e+00,  6.3015e-51], device='cuda:0')
tensor([-6.6740e-49, -2.0986e+00,  1.0697e-49], device='cuda:0')
  
        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([      nan,       nan, -115.5911], device='cuda:0')
tensor([      nan,       nan, -112.7593], device='cuda:0')
  
        self.assertEqual(sign_value, actual_value[0], allow_inf=True)
tensor([-1., -1.,  1.], device='cuda:0')
tensor([-1., -1.,  1.], device='cuda:0')
  
        self.assertEqual(expected_value, actual_value[1], allow_inf=True)
tensor([-110.9285,    0.7413, -112.7593], device='cuda:0')
tensor([-110.8795,    0.7413, -115.5911], device='cuda:0')


5 
(5, 3)
    run_test(matsize, batchdims, mat_chars=['sing'])
        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([[-5.4639e-49,  1.0809e-48, -1.4355e-48],
        [ 4.0162e-50, -1.6792e-49, -1.4588e-49],
        [ 4.5016e-49, -6.4845e-49,  4.9028e-49],
        [ 8.8669e-49, -1.1956e-50, -9.0934e-50],
        [ 1.0180e-50, -2.3492e-49,  2.9704e-50]], device='cuda:0')
tensor([[-0.0000e+00,  1.0751e-48,  5.9039e-49],
        [ 0.0000e+00, -4.9508e-50,  0.0000e+00],
        [ 5.8240e-49, -1.3868e-48,  0.0000e+00],
        [ 8.6981e-49, -1.3410e-49,  0.0000e+00],
        [-6.8240e-51, -1.2646e-48, -3.6321e-49]], device='cuda:0')
  
        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([[      nan, -110.4463,       nan],
        [-113.7389,       nan,       nan],
        [-111.3222,       nan, -111.2369],
        [-110.6443,       nan,       nan],
        [-115.1115,       nan, -114.0406]], device='cuda:0')
tensor([[     -inf, -110.4516, -111.0511],
        [     -inf,       nan,      -inf],
        [-111.0647,       nan,      -inf],
        [-110.6636,       nan,      -inf],
        [      nan,       nan,       nan]], device='cuda:0')
  
        self.assertEqual(sign_value, actual_value[0], allow_inf=True)
tensor([[-0.,  1.,  1.],
        [ 0., -1.,  0.],
        [ 1., -1.,  0.],
        [ 1., -1.,  0.],
        [-1., -1., -1.]], device='cuda:0')
tensor([[-1.,  1., -1.],
        [ 1., -1., -1.],
        [ 1., -1.,  1.],
        [ 1., -1., -1.],
        [ 1., -1.,  1.]], device='cuda:0')
  
        self.assertEqual(expected_value, actual_value[1], allow_inf=True)
tensor([[     -inf, -110.4516, -111.0511],
        [     -inf, -113.5297,      -inf],
        [-111.0647, -110.1971,      -inf],
        [-110.6636, -112.5332,      -inf],
        [-115.5114, -110.2894, -111.5369]], device='cuda:0')
tensor([[-111.1285, -110.4463, -110.1625],
        [-113.7389, -112.3083, -112.4491],
        [-111.3222, -110.9573, -111.2369],
        [-110.6443, -114.9506, -112.9217],
        [-115.1115, -111.9726, -114.0406]], device='cuda:0')
  
    run_test(matsize, batchdims, mat_chars=['sing', 'non_sing'])
        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([[ 2.0255e-49, -4.7865e-01,  5.8494e-50],
        [-3.8510e+00,  2.4657e-49,  4.6330e-01],
        [-9.1485e-51,  2.4230e-02, -5.0224e-49],
        [ 7.1769e-01, -1.7340e-49, -4.0999e+00],
        [-1.5233e-48, -5.1991e-01,  1.5723e-49]], device='cuda:0')
tensor([[ 4.0698e-49, -4.7865e-01,  0.0000e+00],
        [-3.8510e+00, -4.9829e-49,  4.6330e-01],
        [ 0.0000e+00,  2.4230e-02,  0.0000e+00],
        [ 7.1769e-01,  0.0000e+00, -4.0999e+00],
        [ 0.0000e+00, -5.1991e-01, -2.2120e-49]], device='cuda:0')
  
        self.assertEqual(actual_value, expected_value, allow_inf=True)
tensor([[-112.1209,       nan, -113.3629],
        [      nan, -111.9242,   -0.7694],
        [      nan,   -3.7202,       nan],
        [  -0.3317,       nan,       nan],
        [      nan,       nan, -112.3741]], device='cuda:0')
tensor([[-111.4231,       nan,      -inf],
        [      nan,       nan,   -0.7694],
        [     -inf,   -3.7202,      -inf],
        [  -0.3317,      -inf,       nan],
        [     -inf,       nan,       nan]], device='cuda:0')
  
        self.assertEqual(sign_value, actual_value[0], allow_inf=True)
tensor([[ 1., -1.,  0.],
        [-1., -1.,  1.],
        [ 0.,  1.,  0.],
        [ 1.,  0., -1.],
        [ 0., -1., -1.]], device='cuda:0')
tensor([[ 1., -1.,  1.],
        [-1.,  1.,  1.],
        [-1.,  1., -1.],
        [ 1., -1., -1.],
        [-1., -1.,  1.]], device='cuda:0')
  
        self.assertEqual(expected_value, actual_value[1], allow_inf=True)
tensor([[-111.4231,   -0.7368,      -inf],
        [   1.3483, -111.2207,   -0.7694],
        [     -inf,   -3.7202,      -inf],
        [  -0.3317,      -inf,    1.4110],
        [     -inf,   -0.6541, -112.0328]], device='cuda:0')
tensor([[-112.1209,   -0.7368, -113.3629],
        [   1.3483, -111.9242,   -0.7694],
        [-115.2183,   -3.7202, -111.2128],
        [  -0.3317, -112.2762,    1.4110],
        [-110.1032,   -0.6541, -112.3741]], device='cuda:0')
```

## To Reproduce

1. Build from source on ppc64le
1. Run the tests

## Expected behavior

The test should pass

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.1.105

OS: Red Hat Enterprise Linux
GCC version: (GCC) 8.2.0
CMake version: version 3.13.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB

Nvidia driver version: 418.67
cuDNN version: 7.4.2.24
magma version: 7.5.1

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.2.0
[conda] Could not collect

PyTorch built from source
Build command: PYTORCH_BUILD_VERSION=1.2.0 PYTORCH_BUILD_NUMBER=1 VERBOSE=1 LDFLAGS="$LDFLAGS -ldl" CFLAGS="" CXXFLAGS="" USE_FFMPEG=ON USE_GLOO_IBVERBS=1 USE_GFLAGS=ON USE_GLOG=ON CUDNN_LIB_DIR=$EBROOTCUDNN/lib64 CUDNN_INCLUDE_DIR=$EBROOTCUDNN/include TORCH_CUDA_ARCH_LIST="3.5 6.0 7.0"  /rds/bear-apps/devel/2019a/branfosj-eb-pytorch/EL7/EL7-power9/software/Python/3.7.2-GCCcore-8.2.0/bin/python setup.py build

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:
- Simplify generation of singular matrices to just constructing a constant matrix instead of a random singular matrix using random_square_matrix_of_rank, which is susceptible to numerical issues

Test Plan:
- test_det_logdet_slogdet_batched should pass

Fixes #25172

cc: @branfosj @hartb 

Apologies for the delay.

### CODE REVIEW

**Comment by vishwakftw** [comment]
@hartb is there a way to check if this fix works on PowerPC machines?

**Review by ssnl — COMMENTED** [review]
can we instead fix `random_square_matrix_of_rank`?

**Comment by vishwakftw** [comment]
In `random_square_matrix_of_rank`, this is what we do:
- generate a random square matrix
- assign 1s for the first `rank` number of the singular values, and 0s for the rest
- use the left and right singular vectors to construct a new matrix.

This seems like a very logical way to construct a random square matrix of a given rank. An alternative would be to provide `rank` distinct singular values, but I don't see how it would be better than the current scenario, because I see a similar problem locally.

**Comment by vishwakftw** [comment]
Windows tests broke :-/

**Comment by hartb** [comment]
Thank you @vishwak!

FWIW, the version with `torch.ones()` fails for me on Power with:

```
FAIL: test_det_logdet_slogdet_batched (__main__.TestCuda)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/builder/25773/test/common_utils.py", line 456, in wrapper
    method(*args, **kwargs)
  File "test_cuda.py", line 2225, in test_det_logdet_slogdet_batched
    _TestTorchMixin._test_det_logdet_slogdet_batched(self, 'cuda')
  File "/home/builder/25773/test/test_torch.py", line 6562, in _test_det_logdet_slogdet_batched
    run_test(matsize, batchdims, mat_chars=['sing'])
  File "/home/builder/25773/test/test_torch.py", line 6558, in run_test
    self.assertEqual(actual_value, expected_value, allow_inf=True)
  File "/home/builder/25773/test/common_utils.py", line 619, in assertEqual
    assertTensorsEqual(x, y)
  File "/home/builder/25773/test/common_utils.py", line 588, in assertTensorsEqual
    self.assertTrue(torch.equal(nan_mask, torch.isnan(b)), message)
AssertionError: False is not true :
```

Investigating why.

**Comment by hartb** [comment]
Should fail on x86 as well. Isolated testcase:

```
$ cat testcase
import torch
import math

matsize = 3

t = torch.ones(matsize, matsize, matsize)
t *= (math.factorial(matsize - 1) ** (-1.0 / (2 * matsize)))

print('On CPU:')
print(t.det())
print(torch.stack([m.det() for m in t]))

print('On GPU:')
t = t.cuda()
print(t.det())
print(torch.stack([m.det() for m in t]))
```

Shows matching actual/expected on CPU, but 0 vs nan on GPU. And on both Power and x86:

```
$ python testcase
On CPU:
tensor([0., 0., 0.])
tensor([0., 0., 0.])
On GPU:
tensor([nan, nan, nan], device='cuda:0')
tensor([0., 0., 0.], device='cuda:0')
```

So for some reason GPU is returning `nan` as the determinant only in the batched case.

**Comment by vishwakftw** [comment]
I've found out the issue, it's because of the inconsistency in the returned matrix from the `getrf` and `getrf_batched` routines. When you perform `getrf` on a 2-D matrix which is singular: the diagonal elements are `0`, while when you perform `getrf` on a 3-D matrix (which is effectively unsqueezed in the first dimension), you have `nan`s on diagonal.

This inconsistency affects the result right here:

https://github.com/pytorch/pytorch/blob/748436a51451c205bbebab7e70fdcca94dd3a27e/aten/src/ATen/native/LinearAlgebra.cpp#L41

I'll think of efficient ways to circumvent this issue.

**Comment by vishwakftw** [comment]
I've reported this on the MAGMA forum [here](https://icl.cs.utk.edu/magma/forum/viewtopic.php?f=2&t=1951#p8104), working on a patch nonetheless locally.

**Comment by hartb** [comment]
FYI @vishwak, these latest changes (with fix to diagonal call) work for me on Power.

**Comment by vishwakftw** [comment]
Thank you for confirming @hartb

**Review by soumith — APPROVED** [review]

**Pull request closed without merging**
