### PR TITLE
Updated functions for benchmark test

### PR DESCRIPTION
**Pull request by jcatana**
Fixed benchmark test to work with updated gather and scatter functions.

### CODE REVIEW

**Comment by soumith** [comment]
thanks. fyi gloo is the most performant backend. tcp is kinda crappy, and MPI depends on the underlying MPI

**Comment by jcatana** [comment]
Thanks. I'm trying to get distributed working with MPI and cuda. I have a quite fast Mellanox Infiniband installation I would like to test it on. I keep running into compilation errors when enabling WITH_DISTRIBUTED=1.
I'm using mvapich2-gdr and cuda 8.0 and able to run their benchmarks connecting GPUs over MPI.
Is this the same packages this was developed with? Any tips for getting this to work?

**Comment by apaszke** [comment]
`WITH_DISTRIBUTED` has no effect now (it's always built by default). That's not what we used during development, but any implementation of MPI standard should work fine. Can you paste the build log somewhere?

**Comment by soumith** [comment]
@jcatana there's a WIP PR to enable infiniband support: https://github.com/pytorch/pytorch/pull/2903
Let us know what exact issue you are running into, we can help. cc: @ailzhang

**Pull request merged**
