### PR TITLE
Modify symmetric eigendecomposition derivative

### PR DESCRIPTION
**Pull request by vishwakftw**
The derivative of the symmetric eigendecomposition was previously a triangular matrix.

Changelog:
- Modify the derivative of symeig from a triangular matrix to a symmetric matrix with reason specified as a comment.

Test Plan:
- Existing gradcheck and gradgradchecks are ported to test_autograd to verify that the change is correct. Input to symeig is symmetrized before passing

### CODE REVIEW

**Comment by vishwakftw** [comment]
cc: @calincru

**Comment by jeffreyksmithjr** [comment]
I get _what_ was done, @vishwakftw , but I think some folks might benefit from even a single sentence about _why_ it was done. Could you clarify?

**Comment by vishwakftw** [comment]
@jeffreyksmithjr I have added a comment in Functions.cpp about this change. Hope it clarifies the reason for the change.

**Comment by calincru** [comment]
Thanks for solving this, @vishwakftw!

**Comment by vishwakftw** [comment]
@fmassa this is ready for review.

**Comment by ezyang** [comment]
@fmassa is on vacation so I'm unsubscribing him from this issue and kicking this back into triage

**Comment by vishwakftw** [comment]
Thanks!

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
