### PR TITLE
fix topk with k=0 on cuda

### PR DESCRIPTION
**Pull request by bdhirsh**
Fixes https://github.com/pytorch/pytorch/issues/49205.

Thanks @guol-fnst for the initial attempt, which I drew some inspiration from. That PR changed the legacy TH version of the operator, while this PR updates the new, native kernel.

Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#58086 fix topk with k=0 on cuda**

Differential Revision: [D28364964](https://our.internmc.facebook.com/intern/diff/D28364964)

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
Thanks for the fix

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28364964).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28364964).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28364964).

**Pull request closed without merging**
