### PR TITLE
[decomp] Fix baddbmm decomposition

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #109714

The decomposition is currently registered without the pw_cast_for_opmath
decorator, due to the ordering of decorators being meaningful.

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
Is there any other decomposition that does not have the decorator `register_decomposition` last?

**Comment by peterbell10** [comment]
I ran `grep -rPz "@[^\n]*\n@register_decomposition"` on relevant files and only found `py_impl` registrations happening before `register_decomposition` which is fine.

**Comment by peterbell10** [comment]
@yanboliang @jijiew could you share any details about the test failures?

**Comment by jijiew** [comment]
It's model training NE test

**Comment by lezcano** [comment]
@jijiew we do not have access to internal Meta tests. Could you give us enough information to debug the issue, or could you help us landing this internally?

cc @yanboliang @desertfire

**Comment by lezcano** [comment]
ping @jijiew

**Comment by jijiew** [comment]
@lezcano we tested internal for our production job, just got the result back, it turns out to be fine. Feel free to reland the PR, I will let the oncall know and modify out unit test.

**Comment by lezcano** [comment]
Great, thank you!

**Pull request closed without merging**
