### PR TITLE
remove fp16 support from cpu linalg functions

### PR DESCRIPTION
**Pull request by ngimel**
fp16 on cpu produces slow and inaccurate results, see #69969

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
LGTM if the CI is green and @mruberry is fine with this as well.

This has bitten enough people as we just have a rather naïve implementation of matmul-related operations on fp16, so it's only fair to disable it IMO.

**Review by mruberry — APPROVED** [review]
Stamped!

**Comment by suo** [comment]
Looks like this broke XLA? https://hud.pytorch.org/pytorch/pytorch/commit/de18c28a4cfee826a4b11b4c37db23ac1ea53f6a

**Comment by ngimel** [comment]
@JackCaoG we want to disable fp16 support for matmul ops on the cpu, but XLA tests are failing, can you please disable the corresponding tests?

**Comment by JackCaoG** [comment]
Hmm it is
```
2022-04-13T19:38:19.1959420Z ======================================================================
2022-04-13T19:38:19.1960708Z ERROR: test_autocast_torch_fp16 (__main__.TestAutocast)
2022-04-13T19:38:19.1961208Z ----------------------------------------------------------------------
2022-04-13T19:38:19.1961492Z Traceback (most recent call last):
2022-04-13T19:38:19.1961755Z   File "test/test_autocast.py", line 169, in test_autocast_torch_fp16
2022-04-13T19:38:19.1962028Z     self._run_autocast_outofplace(op, args, torch.float16)
2022-04-13T19:38:19.1962314Z   File "test/test_autocast.py", line 102, in _run_autocast_outofplace
2022-04-13T19:38:19.1962762Z     output = getattr(module, op)(*args, **add_kwargs)
2022-04-13T19:38:19.1963084Z RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
```

It is one of test I copied from pytorch autocast. @wonjoolee95 Could you take this one? I think we want to delete this test from our end and verify if there is any other test failed when pin to this upstream pr.

**Comment by wonjoolee95** [comment]
> Hmm it is
> 
> ```
> 2022-04-13T19:38:19.1959420Z ======================================================================
> 2022-04-13T19:38:19.1960708Z ERROR: test_autocast_torch_fp16 (__main__.TestAutocast)
> 2022-04-13T19:38:19.1961208Z ----------------------------------------------------------------------
> 2022-04-13T19:38:19.1961492Z Traceback (most recent call last):
> 2022-04-13T19:38:19.1961755Z   File "test/test_autocast.py", line 169, in test_autocast_torch_fp16
> 2022-04-13T19:38:19.1962028Z     self._run_autocast_outofplace(op, args, torch.float16)
> 2022-04-13T19:38:19.1962314Z   File "test/test_autocast.py", line 102, in _run_autocast_outofplace
> 2022-04-13T19:38:19.1962762Z     output = getattr(module, op)(*args, **add_kwargs)
> 2022-04-13T19:38:19.1963084Z RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
> ```
> 
> It is one of test I copied from pytorch autocast. @wonjoolee95 Could you take this one? I think we want to delete this test from our end and verify if there is any other test failed when pin to this upstream pr.

Sure thing, I'll post a PR to fix it on our end.

**Comment by wonjoolee95** [comment]
Opened https://github.com/pytorch/xla/pull/3499. Waiting on CI tests to be completed.

**Comment by jianyuh** [comment]
Maybe we should still provide a FP16 CPU implementation for linalg (matmul, baddbmm, etc.): we can convert the FP16 input into FP32, do the FP32 computation (accumulation), and then convert the output back to FP16. It's a good reference implementation for unit test purposes. It looks like the PR is causing several unit test failures (which compare GPU vs. CPU op numerical results) by directly disabling the FP16 CPU implementation.

**Pull request closed without merging**
