### PR TITLE
Change torch::Tensor to at::Tensor to fix build failure

### LINKED ISSUE #62416: Build failing when only building parts of PyTorch
I am getting the following errors when trying to build PyTorch with only a minimal set of features.

```
[1352/1410] Building CXX object caffe2/torch/CMakeFiles/nnapi_backend.dir/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp.o
FAILED: caffe2/torch/CMakeFiles/nnapi_backend.dir/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp.o 
/data/home/heitorschueroff/.local/ccache/bin/ccache /data/home/heitorschueroff/.local/ccache/bin/clang++ -DFMT_HEADER_ONLY=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -DUSE_EXTERNAL_MZCRC -D_FILE_OFFSET_BITS=64 -Dnnapi_backend_EXPORTS -Iaten/src -I../aten/src -I. -I../ -I../third_party/onnx -Ithird_party/onnx -I../third_party/foxi -Ithird_party/foxi -I../torch/csrc/api -I../torch/csrc/api/include -I../c10/.. -I../torch/.. -I../torch/../aten/src -I../torch/../aten/src/TH -Icaffe2/aten/src -Ithird_party -I../torch/../third_party/valgrind-headers -I../torch/../third_party/gloo -I../torch/../third_party/onnx -I../torch/csrc -I../torch/lib -I../torch/lib/libshm -I../torch/lib/libshm/../../../torch/lib -I../third_party/fmt/include -isystem ../third_party/protobuf/src -isystem /fsx/users/heitorschueroff/.conda/envs/pytorch/include -isystem ../cmake/../third_party/eigen -isystem /fsx/users/heitorschueroff/.conda/envs/pytorch/include/python3.9 -isystem /fsx/users/heitorschueroff/.conda/envs/pytorch/lib/python3.9/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp=libomp -DNDEBUG -DUSE_PYTORCH_QNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -DHAVE_AVX512_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -fPIC -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -pthread -std=gnu++14 -MD -MT caffe2/torch/CMakeFiles/nnapi_backend.dir/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp.o -MF caffe2/torch/CMakeFiles/nnapi_backend.dir/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp.o.d -o caffe2/torch/CMakeFiles/nnapi_backend.dir/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp.o -c ../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:78:17: error: no type named 'Tensor' in namespace 'torch'
    for (torch::Tensor inpElem : inp.toTensorList()) {
         ~~~~~~~^
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:87:44: error: no member named 'Tensor' in namespace 'torch'
  dict.insert("ser_model", py::cast<torch::Tensor>(nnapi_processed[1]));
                                    ~~~~~~~^
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:97:20: error: no member named 'Tensor' in namespace 'torch'
  c10::List<torch::Tensor> weights(
            ~~~~~~~^
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:98:35: error: no member named 'Tensor' in namespace 'torch'
      py::cast<std::vector<torch::Tensor>>(nnapi_processed[2]));
                           ~~~~~~~^
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:98:64: error: expected a type
      py::cast<std::vector<torch::Tensor>>(nnapi_processed[2]));
                                                               ^
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:97:28: error: unknown type name 'weights'
  c10::List<torch::Tensor> weights(
                           ^
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:98:35: error: no member named 'Tensor' in namespace 'torch'
      py::cast<std::vector<torch::Tensor>>(nnapi_processed[2]));
                           ~~~~~~~^
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:98:64: error: expected a type
      py::cast<std::vector<torch::Tensor>>(nnapi_processed[2]));
                                                               ^
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:98:11: error: expected unqualified-id
      py::cast<std::vector<torch::Tensor>>(nnapi_processed[2]));
          ^
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:98:64: error: expected ')'
      py::cast<std::vector<torch::Tensor>>(nnapi_processed[2]));
                                                               ^
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:97:35: note: to match this '('
  c10::List<torch::Tensor> weights(
                                  ^
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:103:26: error: use of undeclared identifier 'weights'; did you mean 'c10::attr::weights'?
  dict.insert("weights", weights);
                         ^~~~~~~
                         c10::attr::weights
../aten/src/ATen/core/interned_strings.h:598:1: note: 'c10::attr::weights' declared here
FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
^
../aten/src/ATen/core/interned_strings.h:431:3: note: expanded from macro 'FORALL_NS_SYMBOLS'
  FORALL_ATTR_BASE_SYMBOLS(_)        \
  ^
../aten/src/ATen/core/aten_interned_strings.h:1079:9: note: expanded from macro 'FORALL_ATTR_BASE_SYMBOLS'
_(attr, weights) \
        ^
In file included from ../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:2:
In file included from ../torch/csrc/jit/backends/backend.h:3:
In file included from ../aten/src/ATen/core/builtin_function.h:3:
In file included from ../aten/src/ATen/core/function.h:2:
In file included from ../aten/src/ATen/core/function_schema.h:4:
In file included from ../aten/src/ATen/core/jit_type.h:8:
In file included from ../aten/src/ATen/core/ivalue.h:1177:
In file included from ../aten/src/ATen/core/ivalue_inl.h:7:
In file included from ../aten/src/ATen/core/Dict.h:392:
../aten/src/ATen/core/Dict_inl.h:132:3: error: static_assert failed due to requirement 'std::is_constructible<c10::IValue, const c10::Symbol &>::value' "Wrong type for the value argument of Dict::insert"
  static_assert(std::is_constructible<Value, Value_>::value, "Wrong type for the value argument of Dict::insert");
  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:103:8: note: in instantiation of function template specialization 'c10::Dict<c10::IValue, c10::IValue>::insert<char const (&)[8], const c10::Symbol &>' requested here
  dict.insert("weights", weights);
       ^
In file included from ../torch/csrc/jit/backends/nnapi/nnapi_backend_preprocess.cpp:2:
In file included from ../torch/csrc/jit/backends/backend.h:3:
In file included from ../aten/src/ATen/core/builtin_function.h:3:
In file included from ../aten/src/ATen/core/function.h:2:
In file included from ../aten/src/ATen/core/function_schema.h:4:
In file included from ../aten/src/ATen/core/jit_type.h:8:
In file included from ../aten/src/ATen/core/ivalue.h:1177:
In file included from ../aten/src/ATen/core/ivalue_inl.h:7:
In file included from ../aten/src/ATen/core/Dict.h:392:
../aten/src/ATen/core/Dict_inl.h:135:5: error: ambiguous conversion for functional-style cast from 'const c10::Symbol' to 'c10::IValue'
    Value(std::forward<Value_>(value))});
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../aten/src/ATen/core/ivalue.h:471:3: note: candidate constructor
  IValue(double d) : tag(Tag::Double), is_intrusive_ptr(false) {
  ^
../aten/src/ATen/core/ivalue.h:513:3: note: candidate constructor
  IValue(int64_t i) : tag(Tag::Int), is_intrusive_ptr(false) {
  ^
../aten/src/ATen/core/ivalue.h:518:3: note: candidate constructor
  IValue(int32_t i) : IValue(static_cast<int64_t>(i)) {}
  ^
../aten/src/ATen/core/ivalue.h:530:3: note: candidate constructor
  IValue(bool b) : tag(Tag::Bool), is_intrusive_ptr(false) {
  ^
../aten/src/ATen/core/ivalue.h:770:3: note: candidate constructor
  IValue(at::Dimname dimname) : IValue(dimname.symbol().toQualString()) {}
  ^
13 errors generated.
```

It appears that the following PR might be related https://github.com/pytorch/pytorch/pull/62225/files#diff-35e4508343bdd5e34936cc981334a81d605fdc2348fa2135c4f23a03bbdb83e0R78

## Build Environment Variables

export BUILD_TEST=0
export BUILD_CAFFE2=0
export USE_CUDA=0
export USE_MKLDNN=0
export USE_FBGEMM=0
export USE_NNPACK=0
export USE_QNNPACK=0
export USE_XNNPACK=0
export USE_KINETO=0
export USE_DISTRIBUTED=0
export USE_SYSTEM_NCCL=0

cc @malfet @seemethere @walterddr

### PR DESCRIPTION
**Pull request by heitorschueroff**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #62425

Fixes https://github.com/pytorch/pytorch/issues/62416

Differential Revision: [D30000948](https://our.internmc.facebook.com/intern/diff/D30000948)

### CODE REVIEW

**Comment by heitorschueroff** [comment]
@Amyh11325 Could you review this please? I'm not sure if this is the correct fix. What was the intention with changing at:: to torch:: in here https://github.com/pytorch/pytorch/pull/62225/files#diff-35e4508343bdd5e34936cc981334a81d605fdc2348fa2135c4f23a03bbdb83e0R78. Were there missing includes that's causing the build to fail as in the linked issue?

**Comment by Amyh11325** [comment]
> @Amyh11325 Could you review this please? I'm not sure if this is the correct fix. What was the intention with changing at:: to torch:: in here https://github.com/pytorch/pytorch/pull/62225/files#diff-35e4508343bdd5e34936cc981334a81d605fdc2348fa2135c4f23a03bbdb83e0R78. Were there missing includes that's causing the build to fail as in the linked issue?

My intention was just to make the variables match the class returned by the python function more closely. I didn't know it would make a difference. I don't think switching to at::Tensor will cause any problems, but I can test it quickly.

**Review by Amyh11325 — APPROVED** [review]
LGTM Thank you for fixing it, and sorry for making the build error.

**Comment by heitorschueroff** [comment]
> LGTM Thank you for fixing it, and sorry for making the build error.

No problem! Thank you for reviewing it so quickly.

**Comment by heitorschueroff** [comment]
@heitorschueroff has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30000948).

**Pull request closed without merging**
