### PR TITLE
Added logic for pushing docker images to ghcr.io

### LINKED ISSUE #79323: [build] push containers used for PyTorch build in CI to GitHub container registry
### 🚀 The feature, motivation and pitch

When trying to reproduce build / test problems from CI locally, one of the challenges it to get the same image that is used in CI worker. At the moment the images are stored in private registry. Although one could re-build them locally, this is both time-consuming and potentially error prone. It would be much easier to grab container with the same sha256 as the CI one and run the code inside of it.

cc @malfet 

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DanilBaibak**
Fixes https://github.com/pytorch/pytorch/issues/79323

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM, but please take care of TODO before landing :)

**Review by seemethere — APPROVED** [review]
LGTM

**Comment by seemethere** [comment]
If you're looking to revert this due to failed android builds then don't because those should be fixed with the next commit on master (https://github.com/pytorch/pytorch/pull/81038)

**Pull request closed without merging**
