### PR TITLE
[BE] Make ONNX imports lazy

### PR DESCRIPTION
**Pull request by malfet**
This reduces total number of imported modules by default from 1419 to 1322 according to
```
time python -c "import sys;before=len(sys.modules);import torch;after=len(sys.modules);print(f'torch-{torch.__version__} imported {after-before} modules')"
```

and slightly reduces import time, while having no effect on UX (i.e. `torch.onnx.` submodule is kept intact)

Suppress lint errors that appear after mypy accidentally starts listing more files, for more details see: https://github.com/pytorch/pytorch/issues/104940

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Review by albanD — APPROVED** [review]
Sounds good!
Hopefully there are no side effect of this import that we want to preserve (like op registration)?

**Comment by malfet** [comment]
@albanD hopefully testing should detect that. Though lintrunner failures suggest that some of the modules depended on imports which now became lazy... Looking into those

**Comment by malfet** [comment]
Hmm, lintrunner hides internal mypy error:
```
mypy torch/_export/exported_program.py
torch/_export/exported_program.py:248:17: error: List comprehension has incompatible type List[str]; expected List[FQN]  [misc]
torch/_export/exported_program.py:266:37: error: Invalid index type "GraphOutputName" for "Dict[FQN, FQN]"; expected type "FQN"  [index]
torch/_export/exported_program.py:268:21: error: Invalid index type "GraphOutputName" for "Dict[FQN, FQN]"; expected type "FQN"  [index]
/var/lib/jenkins/pytorch/torch/_dynamo/variables/tensor.py:362: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.960
```

**Comment by justinchuby** [comment]
@BowenBao @thiagocrepaldi does this mean we can un-hide some dependencies?

**Comment by thiagocrepaldi** [comment]
> @BowenBao @thiagocrepaldi does this mean we can un-hide some dependencies?

Yup, that probably affects onnx tutorials too. now we will need to add a `import torch.onnx` before using onnx exporter apis

**Comment by justinchuby** [comment]
Do we need `import torch.onnx`? I understand this mechanism is designed to support the direct `torch.onnx` usage

**Comment by albanD** [comment]
> Do we need import torch.onnx?

No you don't! The point here is that you can still access `torch.onnx` as before and it will automatically import it as needed.
If it doesn't behave transparently, do report it here!

**Comment by thiagocrepaldi** [comment]
my bad, misread. `onnx` was added to `_lazy_modules`

**Comment by BowenBao** [comment]
> @BowenBao @thiagocrepaldi does this mean we can un-hide some dependencies?

I think we can. However if we do, the dependency will be introduced to the old torchscript exporter as well. Plus anywhere that uses `torch.onnx`.

**Comment by justinchuby** [comment]
> > @BowenBao @thiagocrepaldi does this mean we can un-hide some dependencies?
> 
> I think we can. However if we do, the dependency will be introduced to the old torchscript exporter as well. Plus anywhere that uses `torch.onnx`.

I see. NVM

**Comment by malfet** [comment]
@thiagocrepaldi , @BowenBao There should be no changes whatsoever, everything should work as is, if you see any changes in behaviour please let me know and I would revert the change and work on a revision that would be side effects free.

**Comment by BowenBao** [comment]
I'm observing changes to pylance behavior in vscode. There is no intellisense now for `torch.onnx.` unless explicitly importing `torch.onnx` on top level. @malfet do you have suggestions?

**Comment by malfet** [comment]
@BowenBao do you know if pylance accepts any kind of hint (for example, mypy allows one to guard extra type checking functionality behind `if TYPE_CHECKING:`)

**Comment by BowenBao** [comment]
Not sure. But tried putting below into `torch/__init__.py` and intellisense is back. Maybe we should do this for _inductor and _dynamo as well?
```
if TYPE_CHECKING:
    from torch import onnx as onnx
```

**Pull request closed without merging**
