### PR TITLE
Add .boxed() to c10d::ProcessGroup and c10d::Work's pybind

### PR DESCRIPTION
**Pull request by yifuwang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #111997

Summary:
When passed from C++ to Python, `c10d::ProcessGroup` and `c10d::Work` are automatically converted to their pybind class which can't be used for dispatcher ops. `.boxed()` exposes `c10d::ProcessGroup` and `c10d::Work` as boxed custom class object to Python.

```python
import tempfile

import torch
import torch.distributed as dist


if __name__ == "__main__":
    with tempfile.NamedTemporaryFile(delete=False) as tmpf:
        dist.init_process_group(
            backend="nccl", init_method=f"file://{tmpf.name}", rank=0, world_size=1
        )
        group = dist.group.WORLD
        print(group)
        print(group.boxed())
``` 

```
<torch.distributed.distributed_c10d.ProcessGroup object at 0x7fe42fb78d30>
ScriptObject <__torch__.torch.classes.c10d.ProcessGroup>
```

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Review by lw — APPROVED** [review]
Thanks for getting this out so promptly!

I have a hard time building PyTorch from source, but I copied that code into my own C++ extensions and it works!

I have however noticed that, inside my operator, I'm now receiving an instance of `torch.classes.c10d.ProcessGroup`, and I need to convert it back to a regular `ProcessGroup`, thus I also need an "unboxing" function.

Do you think it would be possible to add this as a static method to the pybind of c10d::ProcessGroup?

Based on my own trial and error, this would be the code:
```
c10::intrusive_ptr<c10d::ProcessGroup> unbox_process_group(
    const py::object& obj) {
  return torch::jit::toIValue(
             obj,
             c10::getCustomClassType<c10::intrusive_ptr<c10d::ProcessGroup>>())
      .toCustomClass<c10d::ProcessGroup>();
}
```

**Comment by yifuwang** [comment]
>> I copied that code into my own C++ extensions and it works!

That's great to know! Thanks for testing it out!

>> Do you think it would be possible to add this as a static method to the pybind of c10d::ProcessGroup?

This is possible. I understand you want a convenient unboxing function on cpp side, or unboxing `c10d::Work` on python side (since you might want to wait from python). Curious if/why you want to unbox a `c10d::ProcessGroup` on python side since the unboxed version is already available.

**Comment by lw** [comment]
My end-to-end use case is something like this:
```
def my_op(tensor, boxed_process_group):
    process_group = torch.distributed.ProcessGroup.unbox(boxed_process_group)
    torch.distributed.all_reduce(tensor, group=process_group)

lib = torch.library.Library("my_lib", "DEF")
lib.define("my_op(Tensor tensor, __torch__.torch.classes.c10d.ProcessGroup process_group) -> Tensor")
lib.impl("my_op", my_op, "CUDA")

def main():
    torch.distributed.init_process_group("nccl")
    group = torch.distributed.new_group()
    input_ = torch.ones((1,), device="cuda")
    output = torch.ops.my_lib.my_op(input_, group.boxed())
```

In short: I have a Python function, which I need to invoke from some other Python code, however I need this call to go though the dispatcher, thus I need to register my function as an operator. Therefore I need to box the PG when invoking the operator, and I need to unbox it within the operator.

The reason I need the function to be an operator is because I want it to be intercepted by xFormers's selective activation checkpointing mechanism.

**Comment by yifuwang** [comment]
@lw Got it! I overlooked the part where the custom kernels could be in Python. Will add unbox before landing.

**Pull request closed without merging**
