### PR TITLE
Update TwoTensor impl. to accept `outer_size/outer_stride`

### PR DESCRIPTION
**Pull request by guilhermeleobas**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #125941
* __->__ #133337

cc @ezyang @albanD

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
There's one failure when `PYTORCH_TEST_WITH_DYNAMO` is on:

```python
test/functorch/test_aotdispatch.py::TestAOTAutograd::test_input_mutation_false_aliasing W0813 15:14:01.417000 53641 torch/fx/experimental/symbolic_shapes.py:4179] [12/5_1] Failing guard allocated at:
W0813 15:14:01.417000 53641 torch/fx/experimental/symbolic_shapes.py:4179] [12/5_1]
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1] Error while creating guard:
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1] Name: ''
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     Source: shape_env
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     Create Function: SHAPE_ENV
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     Guard Types: None
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     Code List: None
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     Object Weakref: None
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     Guarded Class Weakref: None
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1] Traceback (most recent call last):
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]   File "/home/guilhermeleobas/git/pytorch/torch/_guards.py", line 280, in create
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     return self.create_fn(builder, self)
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]   File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/guards.py", line 1781, in SHAPE_ENV
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     guards = output_graph.shape_env.produce_guards(
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]   File "/home/guilhermeleobas/git/pytorch/torch/fx/experimental/symbolic_shapes.py", line 4188, in produce_guards
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     issue_guard(guard)
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]   File "/home/guilhermeleobas/git/pytorch/torch/fx/experimental/symbolic_shapes.py", line 4153, in issue_guard
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     guard_expr = ShapeGuardPrinter(symbol_to_source, source_ref, self.var_to_sources).doprint(expr)
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]   File "/home/guilhermeleobas/micromamba/envs/pytorch-cuda/lib/python3.10/site-packages/sympy-1.13.1-py3.10.egg/sympy/printing/printer.py", line 292, in doprint
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     return self._str(self._print(expr))
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]   File "/home/guilhermeleobas/micromamba/envs/pytorch-cuda/lib/python3.10/site-packages/sympy-1.13.1-py3.10.egg/sympy/printing/printer.py", line 331, in _print
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     return printmethod(expr, **kwargs)
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]   File "/home/guilhermeleobas/micromamba/envs/pytorch-cuda/lib/python3.10/site-packages/sympy-1.13.1-py3.10.egg/sympy/printing/str.py", line 776, in _print_Relational
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     self._print(expr.rhs))
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]   File "/home/guilhermeleobas/micromamba/envs/pytorch-cuda/lib/python3.10/site-packages/sympy-1.13.1-py3.10.egg/sympy/printing/printer.py", line 331, in _print
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     return printmethod(expr, **kwargs)
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]   File "/home/guilhermeleobas/git/pytorch/torch/fx/experimental/symbolic_shapes.py", line 1588, in _print_Symbol
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1]     assert self.symbol_to_source.get(expr), (
E0813 15:14:01.417000 53641 torch/_guards.py:282] [12/5_1] AssertionError: s0 (could be from ["L['t'].size()[0]"]) not in {s2: ["L['t'].a.size()[0]", "L['t'].b.size()[0]", "L['t'].a.size()[0]", "L['t'].b.size()[0]"], s3: ["L['t'].a.size()[1]", "L['t'].a.stride()[0]", "L['t'].b.size()[1]", "L['t'].b.stride()[0]", "L['t'].a.size()[1]", "L['t'].a.stride()[0]", "L['t'].b.size()[1]", "L['t'].b.stride()[0]"], s6: ["L['t'].size()[0]", "L['t'].a.size()[0]", "L['t'].b.size()[0]"]}.  If this assert is failing, it could be due to the issue described in https://github.com/pytorch/pytorch/pull/90665
E0813 15:14:01.418000 53641 torch/_guards.py:284] [12/5_1] Created at:
E0813 15:14:01.418000 53641 torch/_guards.py:284] [12/5_1]   File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/convert_frame.py", line 603, in transform
E0813 15:14:01.418000 53641 torch/_guards.py:284] [12/5_1]     tracer = InstructionTranslator(
E0813 15:14:01.418000 53641 torch/_guards.py:284] [12/5_1]   File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/symbolic_convert.py", line 2631, in __init__
E0813 15:14:01.418000 53641 torch/_guards.py:284] [12/5_1]     output=OutputGraph(
E0813 15:14:01.418000 53641 torch/_guards.py:284] [12/5_1]   File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/output_graph.py", line 316, in __init__
E0813 15:14:01.418000 53641 torch/_guards.py:284] [12/5_1]     self.init_ambient_guards()
E0813 15:14:01.418000 53641 torch/_guards.py:284] [12/5_1]   File "/home/guilhermeleobas/git/pytorch/torch/_dynamo/output_graph.py", line 455, in init_ambient_guards
E0813 15:14:01.418000 53641 torch/_guards.py:284] [12/5_1]     self.guards.add(ShapeEnvSource().make_guard(GuardBuilder.SHAPE_ENV))
SKIPPED [0.7462s] (s0 (could be from ["L['t'].size()[0]"]) not in {s2: ["L['t'].a.size()[0]", "L['t'].b.size()[0]", "L['t'].a.size()[0]", "L['t'].b.size()[0]"], s3...)
```

**Comment by bdhirsh** [comment]
sounds good to me, but why the new test CI skip?

**Comment by bdhirsh** [comment]
It would be nice to understand why this that test is failing (although running that test under dynamo is probably not common user behavior, since it adds a bunch of graph breaks due to testing framework code). But np if you don't want to go down that rabbit hole, happy to stamp.

Can we make the xskip into an xfail instead? Or does the test fail flakily (that would be more concerning)

**Comment by ezyang** [comment]
The error is means t isn't a tracked fake. How exactly does Dynamo decide what tensors to track when it gets a subclass? That's the bug. And yeah, we should fix this before landing this.

**Comment by guilhermeleobas** [comment]
One of the guards refers to a symbol (`s0`) which doesn't exist in the list of placeholders.

```python
(Pdb++) placeholders
[FakeTensor(..., size=(s2, s3)), FakeTensor(..., size=(s2, s3)), TwoTensor(FakeTensor(..., size=(s6, 4)), FakeTensor(..., size=(s6, 4))), FakeTensor(..., size=(s2, s3)), FakeTensor(..., size=(s2, s3))]

(Pdb++) self.guards[4]
ShapeGuard(expr=Eq(s1, 4) & Eq(s6, s0), stack=<torch.utils._traceback.CapturedTraceback object at 0x7f22dff07ac0>)
```

**Comment by ezyang** [comment]
I see TwoTensor in the placeholders; naively, I was expecting its outer size to be s0? Is this wrong?

**Comment by bdhirsh** [comment]
Stared at this some more, this test is enough to repro:
```
import torch
from torch.testing._internal.two_tensor import TwoTensor

@torch.compile(backend="eager", dynamic=True)
def f(t):
    tmp = t._base if t._is_view() else t
    return tmp + 1


x_a = torch.randn(4, 4, requires_grad=True)
x = TwoTensor(x_a, x_a.clone())
out = f(x[3])
```

It looks like:

(1) `x` is a differentiable view, so we go down the view_func that constructs a SymInt with "ephemeral source" path in meta_utils (`view_from_base`, [link](https://github.com/pytorch/pytorch/blob/main/torch/_subclasses/meta_utils.py#L953))

(2) when we first generate sizes when fakeifying `x` ([here](https://github.com/pytorch/pytorch/blob/main/torch/_subclasses/meta_utils.py#L957)), we allocate and give `fake_x` a first dim of `s0`

(3)  we then fakeify `x._base` (with static sizes), and then run `view_from_base` to regenerate our `fake_x` as a differentiable view off of the fake base

(4) in doing so, we have a `symint_visitor_fn` that creates SymInts with EphemeralSources for every int arg that our view funcs close over ([here](https://github.com/pytorch/pytorch/blob/main/torch/_subclasses/meta_utils.py#L1001))

(5) In the repro I put above, we the view func we replay is the `[3]` slice, and `3` gets closed over and turned into a SymInt with an `EphemeralSource`, `s2`

(6) we then have an assertion that `s0 == s2` [here](https://github.com/pytorch/pytorch/blob/main/torch/_subclasses/meta_utils.py#L1076).

IIRC, when @jbschlosser added it the goal was to use the equality to "remove" the epherally-created symint, so all we have left is the original symints that we used to construct the view (`s0` in this case). But that doesn't really end up happening here: the result of result of `fake_t = t.view_func(...)` ([code](https://github.com/pytorch/pytorch/blob/main/torch/_subclasses/meta_utils.py#L1071)) is exactly what we return back to dynamo, and this FakeTensor has the `s2` symint in its shape (because... comparing `s0 == s2` won't magically swap out our tensor's shape).

So we end up returning a FakeTensor back to dynamo with an `s2` symint on it (ephemeral source), and we end up with an `s0 == s2` guard, where dynamo never had a chance to track `s0`.

**Comment by bdhirsh** [comment]
The easiest/dumbest solution to me is to slam-in-and-replace `s2` with `s0` in the final FakeTensor we return, since we've statically proven that they are equal, and `s0` is the SymInt with the "non-epheral-source" that we want dynamo to track.

We would need some kind of "unsafe swap symints" API on the TensorImpl though, which feels bad. cc @ezyang if you think there are any better alternatives?

**Comment by ezyang** [comment]
I don't understand. Wasn't the point of ephemeral sources that when we perform equality on them, we preferentially eliminate them, so that there should never be ephemeral sources left? You can "eliminate" a symbol by ensuring it has a replacement to another (in this case, s2 to s0). 

This is what the is_ephemeral logic is about:

```
torch/fx/experimental/symbolic_shapes.py:            if not source.is_ephemeral() and r_sources[0].is_ephemeral():
torch/fx/experimental/symbolic_shapes.py:                x in self.var_to_sources and all(s.is_ephemeral() for s in self.var_to_sources[x])
```

So if it is not working, it seems more direct to try to fix it.

Or if we want to rip up the sidewalks, figure out how to get rid of ephemeral sources entirely.

**Comment by bdhirsh** [comment]
I agree with the assessment above, although I'm not sure if in practice we should try to fix the EphemeralSource logic or "rip up the sidewalk".

cc @jbschlosser in case you have any ideas? (I'm on PTO next week but I can think about it more when I get back too)

**Comment by guilhermeleobas** [comment]
Given this problem is reproducible without the changes introduced here. Could I merge this PR and work on a fix for this problem on a separate PR?

**Comment by jbschlosser** [comment]
> cc @jbschlosser in case you have any ideas? (I'm on PTO next week but I can think about it more when I get back too)

I believe #128649 is related. That issue mentions `view(-1)` but PR #128659 that uncovered that issue mentions slicing being problematic as well. I've done a little bit of [investigation](https://github.com/pytorch/pytorch/issues/128649#issuecomment-2168705732) into why the ephemerally-sourced symbols aren't being simplified out but this needs more work.

@bdhirsh / @guilhermeleobas How high-pri is this - are there real use cases hitting this problem?

**Comment by guilhermeleobas** [comment]
> @bdhirsh / @guilhermeleobas How high-pri is this - are there real use cases hitting this problem?

No real use case as far as I know. This bug doesn't affect my work that much.

**Review by bdhirsh — APPROVED** [review]
nvm, it's an xfail so it should error / flag that we need to update it once someone properly figures out the EphemeralSource situation (I do think this is hi-pri though)

**Pull request closed without merging**
