### PR TITLE
Run CompositeImplicit on torch fns during dynamo tracing

### PR DESCRIPTION
**Pull request by JackCaoG**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125808

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @gujinghui @PenghuiCheng @jianyuh @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal @voznesenskym @penguinwu @EikanWang @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Comment by JackCaoG** [comment]
@anijain2305 I am trying to inline `torch.nn.Functional` in this pr, let me know if the idea make sense to you. The motivation is similar, I need to do inlining in the fwd so intermediate tensor that's used by the backward can be seen in the forward.

@yanboliang I noticed that a bunch of `nn.Functional` is in skiplist in https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/trace_rules.py#L2664-L2675 . However in some cases I am still able to inline into them. If you have any insights that would be very helpful. The example I used is 
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch_xla.utils.utils as xu

class MNIST(nn.Module):

  def __init__(self):
    super(MNIST, self).__init__()
    self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
    self.dropout = nn.Dropout(p=0.5, inplace=True)

  def forward(self, x):
    x = F.relu(F.max_pool2d(self.conv1(x), 2))
    x = self.dropout(x)
    return x
  
device = 'cpu'
batch_size = xu.getenv_as('BATCH_SIZE', int, defval=8)
sample_count = xu.getenv_as('SAMPLE_COUNT', int, defval=10)
loader = xu.SampleGenerator(
    data=(torch.zeros(batch_size, 1, 28,
                        28), torch.zeros(batch_size, dtype=torch.int64)),
    sample_count=sample_count)

mnist = MNIST()
breakpoint()
mnist_compiled = torch.compile(mnist, backend="eager")

for data, target in loader:
  #pred = mnist(data)
  pred_2 = mnist_compiled(data)
```

post decomp inline fx looks like
```
GraphModule(
  (L__self___conv1): Conv2d(1, 10, kernel_size=(5, 5), stride=(1, 1))
  (L__self___dropout): Dropout(p=0.5, inplace=True)
)



def forward(self, L_x_ : torch.Tensor):
    l_x_ = L_x_
    child = self.L__self___conv1(l_x_);  l_x_ = None
    max_pool2d_with_indices_default = torch.ops.aten.max_pool2d_with_indices.default(child, [2, 2]);  child = None
    getitem = max_pool2d_with_indices_default[0];  max_pool2d_with_indices_default = None
    relu = torch.ops.aten.relu.default(getitem);  getitem = None
    x = self.L__self___dropout(relu);  relu = None
    return (x,)
```
note that `max_pool2d` turn into `torch.ops.aten.max_pool2d_with_indices.default`

**Comment by yanboliang** [comment]
> I noticed that a bunch of nn.Functional is in skiplist in https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/trace_rules.py#L2664-L2675 . However in some cases I am still able to inline into them. If you have any insights that would be very helpful.

They are in ```torch_non_c_binding_in_graph_functions``` list, which means these functions should be put in graph. I think this is expected and aligned with output of your example.

**Comment by JackCaoG** [comment]
Running into an issue where `batch_norm` will be decompose into
```
def forward(self, arg, kwargs):
    arg_1, arg_2, arg_3, arg_4, arg_5, arg_6, arg_7, arg_8, = fx_pytree.tree_flatten_spec([arg, kwargs], self._in_spec)
    empty = torch.ops.aten.empty.memory_format([0], dtype = torch.uint8, layout = torch.strided, device = device(type='cpu'))
    _native_batch_norm_legit_no_training = torch.ops.aten._native_batch_norm_legit_no_training.default(arg_1, arg_4, arg_5, arg_2, arg_3, 0.1, 1e-05);  arg_1 = arg_4 = arg_5 = arg_2 = arg_3 = None
    getitem = _native_batch_norm_legit_no_training[0]
    getitem_1 = _native_batch_norm_legit_no_training[1]
    getitem_2 = _native_batch_norm_legit_no_training[2];  _native_batch_norm_legit_no_training = None
    return pytree.tree_unflatten([getitem], self._out_spec)
```

in test `PYTORCH_TEST_WITH_DYNAMO=1 python test/test_mkldnn.py -k TestMkldnnCPU.test_resnext50_32x4d_cpu`, it will first convert the model into mkldnn format by
```
mkldnn_model = mkldnn_utils.to_mkldnn(copy.deepcopy(model))
```

then the test will fail with `RuntimeError: 'memory_format' argument is incompatible with mkldnn tensor`. Trying to find a way to not decompose when input tensor is `mkldnn` format..

**Comment by JackCaoG** [comment]
Hmm not sure what I can do besides disabling this test for now. I verified that during dynamo compiling, all of the input tensor is with layout `torch.strided`. The tensors during execution are with layout `layout=torch._mkldnn`...

**Comment by ezyang** [comment]
@JackCaoG It sounds like we're missing a guard on layout, you can probably file a bug for it

**Pull request closed without merging**
