### PR TITLE
[WIP][DataLoader] Prototype of SamplerIterableDataset

### PR DESCRIPTION
**Pull request by ejguan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#49363 [WIP][DataLoader] Prototype of SamplerIterableDataset**
* #49186 [WIP][DataLoader] Prototype of BatchIterableDataset
* #48933 [WIP][DataLoader] CollateIterableDataset prototype

Differential Revision: [D25623637](https://our.internmc.facebook.com/intern/diff/D25623637)

### CODE REVIEW

**Comment by ejguan** [comment]
I am thinking Sampler can be eliminated as containers can be any position in sequence. We can shuffle or make different batch before or after fetching data.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
I suggest we need to put one more example on how to implement sampler as pure IterDataset and without old Sampler class.

**Comment by ejguan** [comment]
> I suggest we need to put one more example on how to implement sampler as pure IterDataset and without old Sampler class.

It makes sense. I will update our RFC.

**Comment by VitalyFedyunin** [comment]
Ready to land

**Pull request closed without merging**
