### PR TITLE
Added OptionalArrayRef template class

### PR DESCRIPTION
**Pull request by heitorschueroff**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #64092
* __->__ #64084
* #64020

closes https://github.com/pytorch/pytorch/issues/63645

**TODO**

- [ ] add non-member functions
- [ ] add tests
- [ ] update codegen to map []? to OptionalArrayRef

### CODE REVIEW

**Comment by ezyang** [comment]
we discussed this in person and I was hoping we could simplify the optional implementation to remove some of the unnecessary genericism. Hopefully doing this is not too high risk.

**Comment by ezyang** [comment]
@gchanan says you can skip reimplementing all of optional by just storing an `optional<ArrayRef>` internally and then writing a bunch of methods that forward to the internal implementations. Much better than copy pasting!

**Comment by heitorschueroff** [comment]
> @gchanan says you can skip reimplementing all of optional by just storing an `optional<ArrayRef>` internally and then writing a bunch of methods that forward to the internal implementations. Much better than copy pasting!

That would work for now, but once we start using `std::optional` this solution would lose the optimization added by @swolchok  in `c10::optional`. Moreover, the implementation of `optional` is quite simple, and can be made simpler since we are restricting T to `ArrayRef`. The complexity is in the template metaprogramming which would still be required with this proposed solution.

**Comment by ezyang** [comment]
Oh right, the optimization. Carry on then

**Pull request closed without merging**
