### PR TITLE
use flake8-mypy

### PR DESCRIPTION
**Pull request by eellison**
Use flake8 installed with mypy checks so that our linter matches fbcode. Mypy type errors also provide valuable signal

### CODE REVIEW

**Review by driazati — APPROVED** [review]
We should file an issue to get rid of all the new `T484`s

**Comment by eellison** [comment]
> We should file an issue to get rid of all the new `T484`s

What are the new T484s?

**Comment by driazati** [comment]
sorry, the `# noqa: T484`s

**Comment by eellison** [comment]
> sorry, the `# noqa: T484`s

All of the ones in test_jit are intentional errors that we're testing for. the stuff in torch/_jit_internal.py is polyfills on our side / internal-only untyped dictionary. So nothing that pressing IMO.

**Pull request closed without merging**
