### PR TITLE
[EZ] Fix typos in RELEASE.md

### PR DESCRIPTION
**Pull request by kiszk**
This PR fixes typo in `RELEASE.md`

### CODE REVIEW

**Review by ymzai — APPROVED** [review]

**Review by mikaylagawarecki — APPROVED** [review]
Thanks

**Comment by kiszk** [comment]
[mikaylagawarecki](https://github.com/mikaylagawarecki) Thank you. These failures may not be related to this change. Do we need to rerun the merge process again?

**Comment by kiszk** [comment]
thank you

**Pull request closed without merging**
