### PR TITLE
Move autocast op list to autocast_mode.h to make sure other backends can reuse it.

### PR DESCRIPTION
**Pull request by PHLens**
This PR refactors the op list added in #124051. To make sure other backends can reuse it.
cc @mcarilli @ptrblck @leslie-fang-intel @jgong5 @guangyey

### CODE REVIEW

**Comment by FFFrog** [comment]
In my opinion, it would be better to leave it as is. Because each backend supports Autocast differently

**Comment by PHLens** [comment]
> In my opinion, it would be better to leave it as is. Because each backend supports Autocast differently

Yes, if the backend has different autocast support list, it can just do not use these macros. For those who support the same op list, they can reuse these macros.

**Comment by kevint324** [comment]
> In my opinion, it would be better to leave it as is. Because each backend supports Autocast differently

Moving the list to .h can improves reusability and make it a less backend specific thing.
On the contrary, keeping the list inside .cc is just implying that this list is designed for specific backend and not supposed to be shared among backends.

**Review by albanD — APPROVED** [review]
That sounds fair since it won't change compile time and we don't expect this structure to move in the future.

**Pull request closed without merging**
