### PR TITLE
Add activation functions (ReLU  and SiLU for now) for structured sparse linear operator

### PR DESCRIPTION
**Pull request by alexsamardzic**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #101339

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer

Differential Revision: [D46453476](https://our.internmc.facebook.com/intern/diff/D46453476)

### CODE REVIEW

**Comment by cpuhrsch** [comment]
Overall the changes look reasonable. Can you check how much this increases our binary size? You can look at the size of libtorch_cuda.so. I'm worried we'll start adding a lot of size.

**Comment by alexsamardzic** [comment]
It doesn't seem too much of a difference: without my PRs, the size of `libtorch_cuda.so` is 152.51MB, and with them it's 153.15 MB.

**Review by cpuhrsch — APPROVED** [review]

**Comment by izaitsevfb** [comment]
@izaitsevfb has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D46453476).

**Pull request closed without merging**
