### PR TITLE
Kill MessageType::SHUTDOWN related logic in pg agent

### PR DESCRIPTION
**Pull request by rohan-varma**
https://github.com/pytorch/pytorch/pull/30330 got rid of the need to send a `MessageType::SHUTDOWN` message, so we can now remove the logic/utils for this type of message. 

I think we can also delete the enum entry in the `enum MessageType`, but we may want to keep it in case the logic in https://github.com/pytorch/pytorch/pull/30710 is ever moved to C++.

Test plan: All existing unit tests pass

### CODE REVIEW

**Review by xush6528 — APPROVED** [review]
make sense to me. This message type is not used now.

**Comment by pritamdamania87** [comment]
Let's kill the enum as well (and bring it back later if needed). Otherwise accidentally using that enum might cause some unintended behavior since the message type is not handled.

**Review by pritamdamania87 — CHANGES_REQUESTED** [review]
Let's kill the enum as well (and bring it back later if needed). Otherwise accidentally using that enum might cause some unintended behavior since the message type is not handled.

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 3c3d587:
* **1/1** broken upstream at merge base 47766e6 (see [grid view](https://dr.pytorch.org/master-timeline.html?count=1&sha1=47766e648ff16d4b1175d04710caed566de14ab4&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35))
  <details>
  <summary>
  You may want to rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  
* **0/1** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=3c3d587fd1042ae9d0e684bc0d53c4fdc4073ec8).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably caused by upstream breakages:
* [pytorch_xla_linux_xenial_py3_6_clang7_build](https://dr.pytorch.org/build-details.html?build_id=76750101)



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by rohan-varma** [comment]
Failures and lint are unrelated, landing.

**Pull request closed without merging**
