### PR TITLE
[PyTorch] Add attribute version of C10_ALWAYS_INLINE

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #136331
* __->__ #136445

Sometimes (such as on a lambda), you need `__attribute__((always_inline))` but not `inline`.

Differential Revision: [D63266917](https://our.internmc.facebook.com/intern/diff/D63266917/)

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
I'm not super familiar with these. But does this mean that for a bunch of compilers, `C10_ALWAYS_INLINE_ATTRIBUTE` is actually not going to inline? That sounds surprising?

**Comment by swolchok** [comment]
> I'm not super familiar with these. But does this mean that for a bunch of compilers, `C10_ALWAYS_INLINE_ATTRIBUTE` is actually not going to inline? That sounds surprising?

which compilers? it does just as much inlining as C10_ALWAYS_INLINE. (The C++ `inline` keyword is a misnomer; what it actually means is "multiple definitions are permitted". See https://en.cppreference.com/w/cpp/language/inline )

**Review by malfet — APPROVED** [review]
This sounds fine, though not entirely sure why is it important

**Comment by albanD** [comment]
> which compilers? 

The ones that don't have `__has_attribute(always_inline)`.
If the goal is to make it work on lambdas, why not call it `C10_ALWAYS_INLINE_LAMBDA` ?

**Comment by swolchok** [comment]
> The ones that don't have `__has_attribute(always_inline)`.

C10_ALWAYS_INLINE works exactly the same way.

> If the goal is to make it work on lambdas, why not call it `C10_ALWAYS_INLINE_LAMBDA` ?

Because it is not lambda-specific.

We could alternatively attempt to replace `C10_ALWAYS_INLINE`'s definition with this one; I'm not sure why `C10_ALWAYS_INLINE` includes `inline`. I'd expect that to break bc (somebody will have used `C10_ALWAYS_INLINE` and left `inline` out) but I haven't tried.

**Pull request closed without merging**
