### PR TITLE
Port `mean` kernel to structured kernels.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #62711 Port `norm` kernel to structured kernels.
* #62024 Port `prod` kernel to structured kernels.
* **#61643 Port `mean` kernel to structured kernels.**

Tracking issue: #55070

Differential Revision: [D29783866](https://our.internmc.facebook.com/intern/diff/D29783866)

### CODE REVIEW

**Comment by ysiraichi** [comment]
`mean` only worked for floating and complex types, even though their kernel implementation supported other data types. Should I keep it that way?

**Comment by ezyang** [comment]
> mean only worked for floating and complex types, even though their kernel implementation supported other data types. Should I keep it that way?

Mean on integers needs to be treated specially as you should promote to floating point, if you support it at all.

```
>>> numpy.mean(numpy.random.randint(4,size=4))
1.25
>>> import torch
>>> torch.mean(torch.tensor([1,2,3,4]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Can only calculate the mean of floating types. Got Long instead.
```

@mruberry I don't see a numpy compat task for mean; is this something we should do?

**Comment by mruberry** [comment]
> > mean only worked for floating and complex types, even though their kernel implementation supported other data types. Should I keep it that way?
> 
> Mean on integers needs to be treated specially as you should promote to floating point, if you support it at all.
> 
> ```
> >>> numpy.mean(numpy.random.randint(4,size=4))
> 1.25
> >>> import torch
> >>> torch.mean(torch.tensor([1,2,3,4]))
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> RuntimeError: Can only calculate the mean of floating types. Got Long instead.
> ```
> 
> @mruberry I don't see a numpy compat task for mean; is this something we should do?

I think type promotion for reductions is covered by the reduction tracking issue: https://github.com/pytorch/pytorch/issues/61417#issue-939965087.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29783866).

**Comment by ysiraichi** [comment]
So, meanwhile, should I revert the check for complex and floating point types?

**Comment by ezyang** [comment]
> So, meanwhile, should I revert the check for complex and floating point types?

Err, how come? If the old code had a check the new code should to (do I misunderstand?º

**Comment by ysiraichi** [comment]
Ah, forgive my broken English. I meant whether I should revert the check back (i.e. undelete it). Anyway, I will do it.

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29783866).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29783866).

**Comment by ysiraichi** [comment]
Rebased.

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29783866).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29783866).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29783866).

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29783866).

**Pull request closed without merging**
