### PR TITLE
Update operator list for AutocastCPU

### PR DESCRIPTION
**Pull request by CaoE**
Update operator list for AutocastCPU.

### CODE REVIEW

**Comment by CaoE** [comment]
This PR depends on:
Optimize PReLU (float32) and enable PReLU BFloat16 support in CPU : https://github.com/pytorch/pytorch/pull/63634
add BFloat16 support for UpSample on CPU: https://github.com/pytorch/pytorch/pull/58297
opitimze ConvTransposedND with mkldnn float32 and bfloat16 on CPU : https://github.com/pytorch/pytorch/pull/58348
enable BFloat16 mkldnn_convolution on both contiguous and channels last memory format: https://github.com/pytorch/pytorch/pull/55864

**Comment by CaoE** [comment]
- The update for conv_transposeNd depends on the PR: opitimze ConvTransposedND with mkldnn float32 and bfloat16 on CPU https://github.com/pytorch/pytorch/pull/58348 
- The update for PReLU depends on the PR: Optimize PReLU (float32) and enable PReLU BFloat16 support in CPU https://github.com/pytorch/pytorch/pull/63634
- The update for UpSample depends on the PR: add BFloat16 support for UpSample on CPU https://github.com/pytorch/pytorch/pull/58297

@samdow  @ngimel  could you please help review this PR? Thanks.

**Comment by CaoE** [comment]
@VitalyFedyunin  could you please help review this PR? Thanks.

**Comment by CaoE** [comment]
> #77060 is the dependence. Will wait for it.

Hi @frank-wei I have removed the dependence of ConvTransposedND. This PR is ready to be merged.

**Review by frank-wei — APPROVED** [review]

**Pull request closed without merging**
