### PR TITLE
[Dynamo] More robust pyop support, module properties as args

### PR DESCRIPTION
**Pull request by voznesenskym**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by voznesenskym** [comment]
This PR is fine, its a flaky test:

> AssertionError: Scalars are not close!

**Comment by voznesenskym** [comment]
> Mismatched elements: 1 / 256 (0.4%)

**Comment by voznesenskym** [comment]
> @pytorchbot revert -m "This appears to have caused two periodic tests to fail" -c "nosignal"
> 
> Please add the `ciflow/periodic` label to this PR before resubmitting it to verify the periodic tests all pass
> 
> Logs showing the failing tests: https://hud.pytorch.org/pytorch/pytorch/commit/a0c2a7f2eda788a48f1d243940297f1467faf138
> 
> Apologies if it wasn't your PR that caused this regression. Candidates for the failure were either this PR or #86988, and this one seemed more likely. Can you please add a PR description to your PR to make reversions like this less of a guess-and-check operation in the future?
> 
> Specifically, the failing tests are:
> 
> ```
> 2022-10-16T05:48:45.7754229Z ======================================================================
> 2022-10-16T05:48:45.7754367Z FAIL [0.031s]: test_dense_mask_index_cpu (__main__.CpuTests)
> 2022-10-16T05:48:45.7754584Z ----------------------------------------------------------------------
> 2022-10-16T05:48:45.7754690Z Traceback (most recent call last):
> 2022-10-16T05:48:45.7754974Z   File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor.py", line 3214, in test_dense_mask_index
> 2022-10-16T05:48:45.7755108Z     self.common(fn, [torch.randn(102400), torch.randn(3)])
> 2022-10-16T05:48:45.7755264Z   File "/opt/conda/lib/python3.10/unittest/mock.py", line 1369, in patched
> 2022-10-16T05:48:45.7755376Z     return func(*newargs, **newkeywargs)
> 2022-10-16T05:48:45.7755564Z   File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor.py", line 256, in check_model
> 2022-10-16T05:48:45.7755652Z     self.assertEqual(
> 2022-10-16T05:48:45.7755940Z   File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2472, in assertEqual
> 2022-10-16T05:48:45.7756023Z     assert_equal(
> 2022-10-16T05:48:45.7756287Z   File "/opt/conda/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
> 2022-10-16T05:48:45.7756392Z     raise error_metas[0].to_error(msg)
> 2022-10-16T05:48:45.7756505Z AssertionError: Scalars are not close!
> 2022-10-16T05:48:45.7756513Z 
> 2022-10-16T05:48:45.7756700Z Absolute difference: 0.0002899169921875 (up to 1e-05 allowed)
> 2022-10-16T05:48:45.7756900Z Relative difference: 1.3709022109477941e-06 (up to 1.3e-06 allowed)
> 2022-10-16T05:48:45.7756905Z 
> 2022-10-16T05:48:45.7757017Z ======================================================================
> 2022-10-16T05:48:45.7757162Z FAIL [0.026s]: test_expanded_reduction_cpu (__main__.CpuTests)
> 2022-10-16T05:48:45.7757369Z ----------------------------------------------------------------------
> 2022-10-16T05:48:45.7757465Z Traceback (most recent call last):
> 2022-10-16T05:48:45.7757662Z   File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor.py", line 766, in test_expanded_reduction
> 2022-10-16T05:48:45.7757807Z     self.common(fn, (torch.randn(2, 197, 256), torch.randn(2, 1, 256)))
> 2022-10-16T05:48:45.7757959Z   File "/opt/conda/lib/python3.10/unittest/mock.py", line 1369, in patched
> 2022-10-16T05:48:45.7758070Z     return func(*newargs, **newkeywargs)
> 2022-10-16T05:48:45.7758305Z   File "/var/lib/jenkins/workspace/test/inductor/test_torchinductor.py", line 256, in check_model
> 2022-10-16T05:48:45.7758397Z     self.assertEqual(
> 2022-10-16T05:48:45.7758708Z   File "/opt/conda/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2472, in assertEqual
> 2022-10-16T05:48:45.7758782Z     assert_equal(
> 2022-10-16T05:48:45.7759056Z   File "/opt/conda/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
> 2022-10-16T05:48:45.7759155Z     raise error_metas[0].to_error(msg)
> 2022-10-16T05:48:45.7759317Z AssertionError: Tensor-likes are not close!
> 2022-10-16T05:48:45.7759323Z 
> 2022-10-16T05:48:45.7759424Z Mismatched elements: 1 / 256 (0.4%)
> 2022-10-16T05:48:45.7759657Z Greatest absolute difference: 2.002716064453125e-05 at index (36,) (up to 1e-05 allowed)
> 2022-10-16T05:48:45.7759892Z Greatest relative difference: 4.907013266928203e-06 at index (36,) (up to 1.3e-06 allowed)
> 2022-10-16T05:48:45.7759903Z 
> 2022-10-16T05:48:45.7760111Z ----------------------------------------------------------------------
> ```

Spoke offline. Test is 100% unrelated. This PR adds support for module functions as inputs into pyoperators, specifically cond. This test is not for that, at all.

All this code has been in pytorch/pytorch only a couple days - this was actually the first torchdynamo PR in the new repo. It is expected that some tests are flaky. We should put up a PR to relax the tensor comparison constraint on those test.

**Comment by ezyang** [comment]
I want to ask, why do we want to support NN module inputs to the subgraphs? This sounds difficult for potential backend compilers to handle; ordinarily we only create graphs with Tensor inputs. Why should this be any different?

**Comment by zhxchen17** [comment]
> I want to ask, why do we want to support NN module inputs to the subgraphs? This sounds difficult for potential backend compilers to handle; ordinarily we only create graphs with Tensor inputs. Why should this be any different?

@ezyang This was originally proposed as a workaround to the following use case:
```
class ModuleA(Module):
    submodule_b: Module
    def forward(self):
        def true_fn(x):
            return self.submodule_b.method_true(x)
        def false_fn(x):
            return self.submodule_b.method_false(x)
        return cond(pred, true_fn, false_fn, args)
```
In this case, we are capturing a branch which has to branch to different submodule calls eventually. Unfortunately, we don't seem to support closure in Dynamo soon, so a workaround is proposed to directly pass modules to branches, we can do submodule calls there.

This pattern so far occurred twice in the real models we want to export. If you want I can send you the internal link and diffs to look at.

What's the best way to capture these in your mind?

**Pull request closed without merging**
