### PR TITLE
enable device index check for all device types

### PR DESCRIPTION
**Pull request by garfield1997**
enable device index check for all device types for grad setter.

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
Looks fine to me, needs test though

**Comment by albanD** [comment]
The blast radius is pretty large but that sounds ok to me as any device with single hw should just return 0 all the time. Will let @soulitzer give the final stamp if he's happy with it.

Also agreed that we need test to make sure it works fine.

**Comment by garfield1997** [comment]
I believe there are already some tests in place. https://github.com/pytorch/pytorch/blob/main/test/test_autograd.py#L11299
```
# Tests cross-device assignment raises
        if len(devices) > 1:
            x = torch.randn(5, 5, device=devices[0])
            with self.assertRaises(RuntimeError):
                x.grad = torch.randn(5, 5, device=devices[1])
```
Do we need additional testing?  @albanD @janeyx99

**Comment by albanD** [comment]
Do we run this test on non-cuda devices? I would expect that this was failing before and would be fixed with this PR for non-cuda devices?

**Comment by garfield1997** [comment]
I am adding a custom backend for PyTorch. This test case used to fail and will be fixed by this PR.  @albanD

**Comment by garfield1997** [comment]
If you have the time, could you give me some feedback on this PR? @albanD @janeyx99

**Review by soulitzer — COMMENTED** [review]
Sounds reasonable to me

Though also on testing, @albanD, do you know what our general testing strategy is for non-cuda devices, for things like this

**Comment by albanD** [comment]
The best Plan On Record for testing these is what is described in this rfc: https://github.com/pytorch/rfcs/pull/64 but it is not done yet I'm afraid.

**Review by albanD — APPROVED** [review]
Sounds good then!

**Comment by garfield1997** [comment]
The CI failure seems unrelated to the changes in the PR, and I am unable to reproduce it locally.

**Comment by FFFrog** [comment]
> The best Plan On Record for testing these is what is described in this rfc: [pytorch/rfcs#64](https://github.com/pytorch/rfcs/pull/64) but it is not done yet I'm afraid.

cc @albanD @soulitzer @garfield1997

[pytorch/rfcs#64](https://github.com/pytorch/rfcs/pull/64) is currently in the design and development stage. We will do our best to speed up the development and open source it as soon as possible.

As stated in the RFC, we plan to abstract and standardize the third-party device access mechanism and in theory, it can provide the following benefits:
1. Code abstract reuse to accelerate the integration of new elements
2. Standardized integration to improve integration quality of  third-party devices
3. Streamlined backend and unified test coverage ensure the availability of third-party device integration mechanisms
4. End-to-end full process documentation and official DEMO

**Comment by garfield1997** [comment]
Could you please help trigger the merge again? @albanD

**Pull request closed without merging**
