### PR TITLE
Parse version directly instead of using parse_version in cpp extensions

### LINKED ISSUE #61036: Torchvision binary wheel building is broken
Looks like https://github.com/pytorch/pytorch/pull/59665 broke some of torchvision's jobs which are now failling with

```
  File "/opt/python/cp36-cp36m/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 776, in _check_cuda_version
    if cuda_ver.major != torch_cuda_version.major:  # type: ignore[attr-defined]
AttributeError: 'Version' object has no attribute 'major'
```

see e.g.: https://app.circleci.com/pipelines/github/pytorch/vision/9349/workflows/769175ff-6f3b-4298-b6ab-e85d44cc54be/jobs/686628

CC @andfoy 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @yf225 @glaringlee @fmassa @vfdev-5 @pmeier

### PR DESCRIPTION
**Pull request by andfoy**
Fixes #61036

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
I think this fixup is obsoleted by #61053. @andfoy do you agree?

**Comment by andfoy** [comment]
I agree

**Comment by malfet** [comment]
Going to land this change, as default version of setup tools shipped with all currently released version of python is too old:
```
% python3.8 -c "from pkg_resources import packaging;print(packaging.__version__, dir(packaging.version.Version))"
16.8 ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_compare', '_regex', 'base_version', 'is_postrelease', 'is_prerelease', 'local', 'public']
% python3.7 -c "from pkg_resources import packaging;print(packaging.__version__, dir(packaging.version.Version))"
16.8 ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_compare', '_regex', 'base_version', 'is_postrelease', 'is_prerelease', 'local', 'public']
```
And it still affects torchvision, see https://app.circleci.com/pipelines/github/pytorch/vision/9348/workflows/bc08d4ba-f6cb-464c-bf5a-6cc977e154c5/jobs/686678

**Comment by malfet** [comment]
Actually, slightly better approach: https://github.com/pytorch/pytorch/pull/61484 (just using comparison ops without diving into major and minors)

**Pull request closed without merging**
