### PR TITLE
[jiterator, complex32] tanh_backward : complex

### PR DESCRIPTION
**Pull request by khushi-411**
Follows #74748 and #74537

cc @kshitij12345!

### CODE REVIEW

**Comment by kshitij12345** [comment]
> There are no OpInfo's for backward kernels, so I haven't added the tests. Is that okay?

Yes. It should be ok. Given that `tanh` has OpInfo entry, then `tanh_backward` will be tested in `test_ops_gradients.py`.

**Review by kshitij12345 — COMMENTED** [review]
Thanks for the PR @khushi-411 

Can you please add a benchmark for `complex32` and `complex64` before and after jiterating. Thanks to @anjali411 , we noticed that jiterating an op may lead to perf regression in some cases.

Following gist could be helpful.
Link: https://gist.github.com/kshitij12345/6581f0aab6f2fc16648bbf0c4c3219fa

**Comment by khushi-411** [comment]
Sure, will update it soon!

**Comment by khushi-411** [comment]
Hi, @kshitij12345! Thanks for sharing the `gist`. Here's the benchmark.
```
[---------------------------------- torch.tanh(x) Benchmark ----------------------------------]
                                                                 |  jiterated  |  non_jiterated
1 threads: ------------------------------------------------------------------------------------
      dtype torch.complex64 - shape : torch.Size([])             |       9.0   |         9.2   
      dtype torch.complex64 - shape : torch.Size([5])            |       8.9   |         9.4   
      dtype torch.complex64 - shape : torch.Size([10, 10])       |       9.2   |         9.5   
      dtype torch.complex64 - shape : torch.Size([64, 64])       |       9.1   |         9.5   
      dtype torch.complex64 - shape : torch.Size([512, 256])     |      13.8   |        13.8   
      dtype torch.complex64 - shape : torch.Size([1024, 1024])   |      99.8   |        99.8   
      dtype torch.complex128 - shape : torch.Size([])            |       8.9   |         9.2   
      dtype torch.complex128 - shape : torch.Size([5])           |       9.0   |         9.4   
      dtype torch.complex128 - shape : torch.Size([10, 10])      |       9.0   |         9.5   
      dtype torch.complex128 - shape : torch.Size([64, 64])      |      16.1   |        16.1   
      dtype torch.complex128 - shape : torch.Size([512, 256])    |     234.0   |       234.8   
      dtype torch.complex128 - shape : torch.Size([1024, 1024])  |    1847.1   |      1853.6   

Times are in microseconds (us).
```
As discussed offline, `torch.tanh` is not implemented for complex32, so I haven't updated it. Thanks!

**Review by anjali411 — APPROVED** [review]
LGTM thanks @khushi-411

**Pull request closed without merging**
