### PR TITLE
Skip cpp_extensions test when possible on Windows

### PR DESCRIPTION
**Pull request by peterjc123**
We should make sure the test pass even if the test conditions are not satisfied.

### CODE REVIEW

**Review by goldsborough — CHANGES_REQUESTED** [review]
Just some nits.

**Comment by peterjc123** [comment]
@goldsborough Done!

**Comment by peterjc123** [comment]
Can we merge this please?

**Comment by goldsborough** [comment]
Please use single quotes when the majority of the file already uses single quotes, in the future.

**Review by goldsborough — APPROVED** [review]

**Review by apaszke — APPROVED** [review]

**Pull request merged**
