### PR TITLE
Use intrusive_ptr for LazyTensor

### PR DESCRIPTION
**Pull request by wconstab**
Refactors the whole codebase to use LazyTensorPtr (defined as c10::intrusive_ptr<LazyTensor>) to enable XLA to use a derived class XlaLazyTensor and override functionality.

* this PR is just the first step, and we will need to add a factory class that XLA can override in their backend to actually hook up their derived tensor class.

RUN_TORCHBENCH: ALL
TORCHBENCH_BRANCH: wconstab/ltc

### CODE REVIEW

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Review by JackCaoG — APPROVED** [review]
Thanks!

**Comment by antoniojkim** [comment]
@wconstab are you aware of this build error?
```
../torch/csrc/lazy/core/lazy_graph_executor.cpp: In member function ‘torch::lazy::hash_t torch::lazy::LazyGraphExecutor::GetGraphHash(const std::vector<torch::lazy::LazyTensor>&)’:
../torch/csrc/lazy/core/lazy_graph_executor.cpp:1103:49: error: no matching function for call to ‘torch::lazy::LazyGraphExecutor::CollectSyncTensors(const std::vector<torch::lazy::LazyTensor>&, torch::lazy::LazyGraphExecutor::SyncTensorsConfig&)’
   auto coll = CollectSyncTensors(tensors, config);
                                                 ^
../torch/csrc/lazy/core/lazy_graph_executor.cpp:606:41: note: candidate: ‘torch::lazy::LazyGraphExecutor::SyncTensorCollection torch::lazy::LazyGraphExecutor::CollectSyncTensors(const std::vector<c10::intrusive_ptr<torch::lazy::LazyTensor> >&, const torch::lazy::LazyGraph
Executor::SyncTensorsConfig&)’
 LazyGraphExecutor::SyncTensorCollection LazyGraphExecutor::CollectSyncTensors(
                                         ^~~~~~~~~~~~~~~~~
../torch/csrc/lazy/core/lazy_graph_executor.cpp:606:41: note:   no known conversion for argument 1 from ‘const std::vector<torch::lazy::LazyTensor>’ to ‘const std::vector<c10::intrusive_ptr<torch::lazy::LazyTensor> >&’
```
It looks to be a direct consequence of this PR.

I got the above error after pulling the latest changes from the `lazy_tensor_staging` branch and building like I normally do.

**Comment by wconstab** [comment]
I think I did break something, but @desertfire fixed it already.  Did you try pulling again?  If you already have his change lmk.

**Comment by antoniojkim** [comment]
seems to work now with latest changes

**Pull request merged**
