### PR TITLE
inlining tensor.device()

### PR DESCRIPTION
**Pull request by bdhirsh**
From some previous benchmarking, I noticed that `tensor.device()` gets called a lot during benchmarks, and currently cannot be inlined since it lives in a cpp file.

Updated instruction counts: P171378514

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #52009 update tracing codegen to use redispatch API
* #51363 update autograd kernels to use redispatch
* #52008 codegen'd API for redispatching
* **#50848 inlining tensor.device()**

Differential Revision: [D25984136](https://our.internmc.facebook.com/intern/diff/D25984136)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
You might need to force inline rather than fake inline as you are doing here.

**Comment by bdhirsh** [comment]
> You might need to force inline rather than fake inline as you are doing here.

@ezyang 
Weirdly enough, callgrind_annotate is still showing me function-call overhead on both `wrap_kernel_functor_unboxed_::call` and FunctionRef::callback_fn` even when I force-inline it. So the wins I'm seeing in my benchmarks are all just from my inlining `Tensor::device()`.

I'm not too sure what's causing the overhead in the two examples but I'm tempted to land the PR with only inline `device()` for the quick win.

callback_fn():
```
    .           template<typename Callable>
    .           // benchmarks have shown that this function was not getting inlined in calls to at::add (scalar overload)
6,700 ( 0.36%)  static C10_ALWAYS_INLINE Ret callback_fn(intptr_t callable, Params ...params) {
  400 ( 0.02%)      return (*reinterpret_cast<Callable*>(callable))(
    .                   std::forward<Params>(params)...);
4,900 ( 0.26%)  }
```


call():
```
    .               // benchmarks have shown that this function was not getting inlined in calls to at::empty
2,000 ( 1.24%)      static C10_ALWAYS_INLINE ReturnType call(OperatorKernel* functor, DispatchKeySet, ParameterTypes... args) {
    .                 KernelFunctor* functor_ = static_cast<KernelFunctor*>(functor);
    .                 // Note [Plumbing Keys Through The Dispatcher 2]
    .                 // See Note [Plumbing Keys Through The Dispatcher] for the background.
    .                 // This functor explicitly takes in a dispatchKeySet and drops it on the floor- it does not forward it to the regis
    .                 //
    .                 // This is due to the calling convention within the dispatcher, which expects all registered kernels to have a firs
    .                 // DispatchKeySet.
    .                 // This is not the case for pretty much all manually written kernels, however- this functor serves to separate the
    .                 // of the dispatcher from the calling convention of manually written kernels.
  400 ( 0.25%)        return (*functor_)(std::forward<ParameterTypes>(args)...);
1,400 ( 0.87%)      }
    .             };
```

**Review by bhosmer — APPROVED** [review]
It's interesting that the heavily templated functions are the ones where you're seeing apparent function call overhead even with always-inline. Regardless though I'd be in favor of landing the device win separately, just to keep the history tight.

**Comment by swolchok** [comment]
I only see Tensor::device() and a white space change? Is the GitHub app misleading me?

**Comment by bdhirsh** [comment]
> I only see Tensor::device() and a white space change? Is the GitHub app misleading me?

Sorry, I still need to update the description.

I originally tried inlining those other two functions as well (`wrap_kernel_functor_unboxed::call()` and `function_ref::callback_fn()`) using `C10_ALWAYS_INLINE`, but I found that I was still seeing function call overhead in callgrind (I have an example in a comment further up in this PR).

If you happen to know why, that would be interesting. But you also have a PR here that messes with `wrap_kernel_functor_unboxed::call()`. If your PR is getting that function inlined then I'll just forget about it here. https://github.com/pytorch/pytorch/pull/51164
(between the two functions, that one had a bigger impact on benchmarks than `callback_fn()`).

**Pull request closed without merging**
