### PR TITLE
[Distributed] [2/N] Fix clang-tidy warnings in torch/csrc/distributed/c10d

### PR DESCRIPTION
**Pull request by cyyever**
This PR continues to fix some clang-tidy warnings in distributed code, following #122884.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]
LGTM

**Comment by atalman** [comment]
Breakage is here:
https://github.com/pytorch/pytorch/actions/runs/8547448441/job/23420620163#step:19:1424

```
FError: 
Tried to access or call an operator with a wrong signature.
  operator: _c10d_functional::reduce_scatter_tensor(Tensor input, str reduce_op, int group_size, str group_name) -> Tensor
    registered at /var/lib/jenkins/workspace/torch/csrc/distributed/c10d/Functional.cpp:290
  correct signature:  at::Tensor (at::Tensor const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    registered at /var/lib/jenkins/workspace/torch/csrc/distributed/c10d/Functional.cpp:290
  accessed/called as: at::Tensor (at::Tensor const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
This likely happened in a call to OperatorHandle::typed<Return (Args...)>(). Please make sure that the function signature matches the signature in the operator registration call.
```

**Pull request closed without merging**
