### PR TITLE
fixed pyi file for ReduceLROnPlateau

### LINKED ISSUE #63143: ReduceLROnPlateau is not a subclass of _LRScheduler
## 🐛 Bug

This is probably just a small oversight, but I noticed that [`lr_schedulers.ReduceLROnPlateau`](https://pytorch.org/docs/stable/_modules/torch/optim/lr_scheduler.html#ReduceLROnPlateau) is, contrary to all other `lr_scheduler` classes, not a subclass of `lr_schedulers._LRScheduler`

cc @vincentqb @jbschlosser @albanD @iramazanli

### PR DESCRIPTION
**Pull request by randolf-scholz**
Fixes #63143 

Issue reappeared due to subclassing not present in stub file.

cc @ezyang @malfet @xuzhao9 @gramster

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
Looks like this fix triggers
> Error: Signature of "step" incompatible with supertype "LRScheduler"

**Comment by randolf-scholz** [comment]
It seems that a bunch of the LRScheduler subclasses simply violate LSP.

- Base class: `def step(self, epoch=None)`
- `SequentialLR`: `def step(self)`  (missing epoch argument!)
- `ChainedScheduler`: `def step(self)`  (missing epoch argument!)
- `ReduceLROnPlateau`: `def step(self, metrics, epoch=None)`  extra mandatory `metrics` argument.

For `SequentialLR` and  `ChainedScheduler`, it would make sense to simply pass the `epoch` argument through. (better open a separate issue?)

For `ReduceLROnPlateau`, I'd suggest adding a `type: ignore[override]`, I don't really see a better solution right now.

**Comment by randolf-scholz** [comment]
Alternatively, one could set a default value like `float('nan')`.

**Comment by ezyang** [comment]
type: ignore as necessary, IMO

**Comment by janeyx99** [comment]
Agreed with Ed for ReduceLROnPlateau, and yes for propagating epoch for the others.

**Comment by randolf-scholz** [comment]
I added the type-ignore here and a put some educated guesses on how to pass epoch into a second pull request: https://github.com/pytorch/pytorch/pull/113675

**Pull request closed without merging**
