### PR TITLE
Add missing LTC headers to setup.py

### LINKED ISSUE #81423: [LTC] Missing header `ltc_ops.h`
### 🐛 Describe the bug

There is an LTC header missing in the packaged version of PyTorch (nightly):
https://github.com/pytorch/pytorch/blob/master/torch/csrc/lazy/core/internal_ops/ltc_ops.h

I think this may have just been an oversight. @wconstab Can you please confirm?

There is also another a few other (LTC unrelated) header missing as well that I noticed when trying to build Torch-MLIR with the latest PyTorch nightly wheel
```
In file included from torch/include/torch/csrc/THP.h:23,
                 from torch/include/torch/csrc/jit/python/pybind.h:9,
                 from torch-mlir/python/torch_mlir/csrc/reference_lazy_backend/reference_lazy_backend_pybind.cpp:10:
torch/include/torch/csrc/utils.h:180:10: fatal error: torch/csrc/generic/utils.h: No such file or directory
 #include <torch/csrc/generic/utils.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
          
 In file included from torch/include/torch/csrc/jit/python/pybind.h:12,
                 from torch-mlir/python/torch_mlir/csrc/reference_lazy_backend/reference_lazy_backend_pybind.cpp:10:
torch/include/torch/csrc/jit/python/pybind_utils.h:29:10: fatal error: torch/csrc/distributed/rpc/py_rref.h: No such file or directory
 #include <torch/csrc/distributed/rpc/py_rref.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I will put up a quick PR that adds these header to the `setup.py` if there are no objections.

CC: @wconstab @desertfire @ke1337 @henrytwo 

### Versions

N/A

### PR DESCRIPTION
**Pull request by antoniojkim**
A number of headers that are not packaged but required for building vendor lazy tensor backends

Fixes #81423

CC: @wconstab @desertfire @ke1337 @henrytwo

### CODE REVIEW

**Comment by wconstab** [comment]
I think this looks good, at least the 'lazy' part of it is fine, @malfet  @wanchaol any idea about the distributed part?

**Comment by malfet** [comment]
@wconstab isn't it weird that we want to re-distributed headers clearly marked as `internal_`?

**Review by malfet — APPROVED** [review]
Looks ok, but we really need an umbrella task to understand what APIs are expected to be used by extensions and PyTorch should maintain backward compatibility there vs ones that are purely experimental

**Comment by antoniojkim** [comment]
> isn't it weird that we want to re-distributed headers clearly marked as `internal_`?

If you're referring to `internal_ops/ltc_ops.h`, I think that's just poor naming. It is something that can be used commonly amongst different LTC vendor backends

**Comment by wconstab** [comment]
> If you're referring to internal_ops/ltc_ops.h, I think that's just poor naming.

Yes.. haha. It refers to 'internal to LTC' as opposed to 'from ATEN', so in a way it is an OK name but in this context clearly confusing.  Not intended to be 'internal' from the perspective of users of LTC...

**Pull request closed without merging**
