### PR TITLE
Allow opt-einsum to be a real dependency now as v3.4 is numpy-free

### PR DESCRIPTION
**Pull request by janeyx99**
Partially addresses #127109 

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137138

### CODE REVIEW

**Comment by lezcano** [comment]
Removing my review request, as I'm probably not the right person to review this

**Comment by Skylion007** [comment]
Looks like this is related to dynamo / torch compile numpy backend issues passing incorrect args to opt_einsum

**Comment by lezcano** [comment]
You can probably ping @amjames once the PR passes CI.

**Comment by janeyx99** [comment]
For some reason 3.4 opt-einsum breaks dynamo tracing :/ likely due to kwargs usage. Sigh

**Pull request closed without merging**
