### PR TITLE
Set bash shell on Windows

### PR DESCRIPTION
**Pull request by huydhn**
Attempt to fix the missing python3 command on the new Windows AMI https://github.com/pytorch/pytorch/actions/runs/9551494945/job/26325922503.  I added the logic to copy python to python3 to make the command available, it worked with the previous AMI, but start to fail now and the cause is not clear (maybe it's not the AMI, but a new GitHub runner version)

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by huydhn** [comment]
I'll land this once windows build and test jobs finish successfully

**Review by malfet — APPROVED** [review]
LGTM, should we specify it as default one for the platform?

**Review by atalman — APPROVED** [review]

**Comment by nWEIdia** [comment]
Has https://github.com/pytorch/pytorch/pull/124613 been tested with Windows AMI before merging?

**Comment by huydhn** [comment]
> Has #124613 been tested with Windows AMI before merging?

cc @atalman

**Pull request closed without merging**
