### PR TITLE
Revert "Implement backend fallback fallthrough (#32439)"

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#32650 Revert "Implement backend fallback fallthrough (#32439)"**

This reverts commit 248f6d0485bc2344e1f339d2b0572f1e02ab6515.

### CODE REVIEW

**Comment by ezyang** [comment]
I'm a little loathe to revert here, because this PR unblocks some other folks workstreams. An alternative is to disable the flaky test while I investigate

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit fae88c46:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=fae88c466b64147492b438dd224f87739c97cb77).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4346947) pytorch_linux_xenial_py3_6_gcc5_4_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=91308603) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=91308603))
<details>
<summary>
<code>Jan 27 16:59:42 RuntimeError: test_quantization failed!</code>
</summary>

```
Jan 27 16:59:41 Ran 36 tests in 50.331s 
Jan 27 16:59:41  
Jan 27 16:59:41 FAILED (errors=1, skipped=1) 
Jan 27 16:59:41  
Jan 27 16:59:41 Generating XML reports... 
Jan 27 16:59:42 Traceback (most recent call last): 
Jan 27 16:59:42   File "test/run_test.py", line 456, in <module> 
Jan 27 16:59:42     main() 
Jan 27 16:59:42   File "test/run_test.py", line 449, in main 
Jan 27 16:59:42     raise RuntimeError(message) 
Jan 27 16:59:42 RuntimeError: test_quantization failed! 
Jan 27 16:59:42 + cleanup 
Jan 27 16:59:42 + retcode=1 
Jan 27 16:59:42 + set +x 
Jan 27 16:59:42 =================== sccache compilation log =================== 
Jan 27 16:59:42 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 27 16:59:42 Compile requests                  7 
Jan 27 16:59:42 Compile requests executed         6 
Jan 27 16:59:42 Cache hits                        0 
Jan 27 16:59:42 Cache misses                      6 
Jan 27 16:59:42 Cache timeouts                    0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by izdeby — APPROVED** [review]
Approving in order to unblock. 
Due to personal interest - I would disable flaky test :)

**Comment by ezyang** [comment]
@albanD is going to submit the real fix in our vectorized implementations.

**Pull request closed without merging**
