### PR TITLE
[dynamo][disable] Move disable impl to its own __call__ method

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #124501
* __->__ #125486

There were internal cases where calling disable in distributed causes trace_rules to be generated, which imports distributed and causes circular import errors.

The code has also gone bulky. I think it is time for disable code to exist separately.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Review by williamwen42 — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by anijain2305** [comment]
Closing in favor of https://github.com/pytorch/pytorch/pull/126191

**Pull request closed without merging**
