### PR TITLE
Fix Eigen issue on OS X with CUDA and nvcc compile

### PR DESCRIPTION
**Pull request by orionr**
Breaking this out of #8338

This takes care of the Eigen failure we saw on Mac CUDA builds when BUILD_CAFFE2 and BUILD_ATEN were removed. Fix is to isolate Eigen from headers included by cu files and processed by nvcc. This was worked on with @smessmer.

cc @mingzhe09088 @smessmer @BIT-silence @Yangqing

### CODE REVIEW

**Comment by orionr** [comment]
Manual run of the Android test passed at https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-android-ubuntu16.04-build/9231/console so going to declare victory on the tests here.

**Review by mingzhe09088 — APPROVED** [review]
LGTM

**Review by xiaomengy — APPROVED** [review]
Please make sure the failed test are not related to this change.

**Comment by orionr** [comment]
@BIT-silence - yup, test failures are not related, although a retest never hurts. I am seeing internal test failures, so working through those.

**Pull request closed without merging**
