### PR TITLE
Revert "Change convolution to use symbolic shapes for propagation (#92397)"

### PR DESCRIPTION
**Pull request by nkaretnikov**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #92768
* #92767
* #91952
* #92667
* __->__ #92766

This reverts commit 5c4f0fd72ccf647c41555a7d65ad05590dbe610d.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by nkaretnikov** [comment]
See https://github.com/pytorch/pytorch/pull/92397/files#r1083500462 for context

**Comment by ezyang** [comment]
I'm going to let @Chillee handle these

**Comment by Chillee** [comment]
I think this should be fixed by the follow up Pr.

**Comment by nkaretnikov** [comment]
Resolved: https://github.com/pytorch/pytorch/pull/92768#issuecomment-1399625698. Closing.

**Pull request closed without merging**
