### PR TITLE
Add a hack for RNN export to ONNX

### PR DESCRIPTION
**Pull request by apaszke**
The export itself is not implemented yet (it's that `symbolic` that raises an error at the moment), but the whole framework is in place.

### CODE REVIEW

**Comment by ezyang** [comment]
This looks OK for now.

**Comment by dzhulgakov** [comment]
Can we merge it then and figure out weights export story separately?

**Comment by dzhulgakov** [comment]
Yeah, it's a hack - it doesn't export the RNN yet. Maybe disable the test for now until we implement export properly? In current form word_language_model is not very useful as it just unrolls the loop.

**Comment by apaszke** [comment]
Sorry, it was all green, but the JIT tests must have been disabled. Anyway, it’s been sitting there for a long time and I didn’t want to let the code rot again. I already rebased and fixed conflicts twice.

**Pull request merged**
