### PR TITLE
Fix and test for issue "DataParallel does not work with sparse parameters" #32444 .

### PR DESCRIPTION
**Pull request by madlag**
- Fixed DataParallel tests that were just missing some imports
- Added test for the issue https://github.com/pytorch/pytorch/issues/32444
- Added the fix for the issue itself

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 27b2792e:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=27b2792e996514f092f53b1a5b23a0be3a9e6f0d).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4314724) pytorch_linux_xenial_py3_6_gcc5_4_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=89361449) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=89361449))
<details>
<summary>
<code>Automatic merge failed; fix conflicts and then commit the result.</code>
</summary>

```
do so (now or later) by using -b with the checkout command again. Example: 
 
  git checkout -b <new-branch-name> 
 
HEAD is now at 27b2792e99 Adding new test for DataParallel issue 32444 (https://github.com/pytorch/pytorch/issues/32444). 
+ git reset --hard 27b2792e996514f092f53b1a5b23a0be3a9e6f0d 
HEAD is now at 27b2792e99 Adding new test for DataParallel issue 32444 (https://github.com/pytorch/pytorch/issues/32444). 
+ git merge --allow-unrelated-histories --no-edit --no-ff 44b270d892176d6526801bdfa5227a8caa9852bf 
Auto-merging test/test_data_parallel.py 
CONFLICT (content): Merge conflict in test/test_data_parallel.py 
Automatic merge failed; fix conflicts and then commit the result. 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by madlag** [comment]
test_data_parallel.py was moved to the test/distributed  directory, should I close this PR and make another one, or change the content of my forked repo ?

**Review by zhaojuanmao — COMMENTED** [review]
@madlag thanks for working on this. please see my inline comments. I think your fix works, because it does not return a sparse tensor view, so auto grad function does not complain. 

So the actual root cause of this issue is probably because Broadcast.forward() returns sparse tensor view that is not supported by autograd function, comm.broadcast_coalesced() actually works fine based on my local debugging. 

more comments in #32444

**Comment by zhaojuanmao** [comment]
> test_data_parallel.py was moved to the test/distributed directory, should I close this PR and make another one, or change the content of my forked repo ?

usually you can just pull latest trunk and rebase your PR on top of the trunk

**Pull request closed without merging**
