### PR TITLE
add BFloat16 operators on CPU: diag, fmod, cumsum, cumprod

### PR DESCRIPTION
**Pull request by jiayisunx**
Added BFloat16 support for searchsorted, diag, fmod, cumsum, and cumprod on CPU, and collected the benchmark data of these OPs (searchsorted, diag, fmod, cumsum, cumprod) for BFloat16 and Float32 data type by using the operator_benchmark tool of PyTorch on the platform of Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz

Number of cores: 1 core, 28 cores(1 socket)
[cumsum_cumprod_benchmark.txt](https://github.com/pytorch/pytorch/files/6980232/cumsum_cumprod_benchmark.txt)
[diag_benchmark.txt](https://github.com/pytorch/pytorch/files/6980233/diag_benchmark.txt)
[fmod_benchmark.txt](https://github.com/pytorch/pytorch/files/6980234/fmod_benchmark.txt)
[searchsorted_benchmark.txt](https://github.com/pytorch/pytorch/files/6980328/searchsorted_benchmark.txt)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
With exception of relevant Windows build failures, code looks good, please include benchmarks comparing float and bfloat16 for different input sizes.

**Review by VitalyFedyunin — CHANGES_REQUESTED** [review]
Please fix windows builds

**Comment by jiayisunx** [comment]
@VitalyFedyunin , thanks, I have attached the benchmark data.

**Comment by jiayisunx** [comment]
@VitalyFedyunin

**Comment by jiayisunx** [comment]
@VitalyFedyunin , please help to review it, thanks.

**Comment by jiayisunx** [comment]
@VitalyFedyunin , please help to review it, thanks.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Please rebase

**Comment by jiayisunx** [comment]
Thank you, @VitalyFedyunin , I have rebased it.

**Comment by jiayisunx** [comment]
@VitalyFedyunin

**Comment by jiayisunx** [comment]
@VitalyFedyunin

**Comment by jiayisunx** [comment]
@VitalyFedyunin

**Comment by frank-wei** [comment]
@jiayisunx  could you check the CI failure?

**Comment by jiayisunx** [comment]
@frank-wei

**Pull request closed without merging**
