### PR TITLE
Enabled force_shape_pad for test_pad_mm and test_slice_mm_bandwidth_computation

### PR DESCRIPTION
**Pull request by iupaikov-amd**
Some tests fail for ROCm build on navi arch because of this check: https://github.com/pytorch/pytorch/blob/f83361b2745e0f3232a211f5d2e5a464e02f6c1f/torch/_inductor/fx_passes/pad_mm.py#L211

There is no need to determine if mm is compute bound for most of the padding tests since they don't specifically test compute bound behavior. We don't have enough empirical data to fine tune this check for AMD gpus yet. I propose to force the shape padding for the tests that we had trouble with to avoid this unnecessary logic path.

Please correct me if I didn't add other tests that can potentially fail with this issue or if I added a test that is dependent on logic below the `force_shape_pad` check here: https://github.com/pytorch/pytorch/blob/f83361b2745e0f3232a211f5d2e5a464e02f6c1f/torch/_inductor/fx_passes/pad_mm.py#L444

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by davidberard98** [comment]
@iupaikov-amd can you rebase onto the `viable/strict` branch? Although the failures do seem unrelated, they also prevent the rocm CI from running (which are probably important for these changes?).

**Comment by iupaikov-amd** [comment]
Hello @davidberard98 !

I completed the required rebase, but it won't help the workflows to run probably.
Here is more info on why it happens: https://github.com/pytorch/pytorch/issues/142016
PR that was merged ignoring the failures: https://github.com/pytorch/pytorch/pull/143283

Regards, Iurii.

**Review by jeffdaily — APPROVED** [review]

**Comment by jataylo** [comment]
@davidberard98 @jeffdaily likely need to force here as we're hitting the inductor-rocm credentials issue https://github.com/pytorch/pytorch/issues/142016

**Pull request closed without merging**
