### PR TITLE
[nnc] Modified the semantics of reorder in using permutation

### PR DESCRIPTION
**Pull request by navahgar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #61293
* #61087
* **#61085**

Earlier, the semantics of `reorder` was that the parameter `permutation` referred to the position of the loop in the reordered output. Modified that to be consistent with the semantics of `torch.permute`.

Differential Revision: [D29506679](https://our.internmc.facebook.com/intern/diff/D29506679)

### CODE REVIEW

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29506679).

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29506679).

**Review by ZolotukhinM — APPROVED** [review]
👍

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29506679).

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29506679).

**Pull request closed without merging**
