### PR TITLE
Clean-up removed TH from BUCK

### PR DESCRIPTION
**Pull request by kit1980**
Differential Revision: D42981979

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Review by izaitsevfb — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Review by malfet — COMMENTED** [review]
BONUS points if you'll also remove references to THC from ATen's README

**Comment by kit1980** [comment]
> BONUS points if you'll also remove references to THC from ATen's README

Probably in a separate change.

**Comment by kit1980** [comment]
dynamic_aot_eager_timm previously failed with the same error here:
https://github.com/pytorch/pytorch/actions/runs/4084338097/jobs/7041310615

**Pull request closed without merging**
