### PR TITLE
Add functions from `torch.masked._ops` to `__all__` for `torch.masked`

### PR DESCRIPTION
**Pull request by ringohoffman**
Add the non-private operations imported in this file to `__all__` so that pyright considers them to be publicly exported. Solves this error:

```
"mean" is not exported from module "torch.masked" Pylance[reportPrivateImportUsage]
```

Related: https://github.com/pytorch/pytorch/pulls?q=pyright+export

cc: @ezyang

### CODE REVIEW

**Comment by ringohoffman** [comment]
@cpuhrsch how's this looking? Hopefully you find it pretty straightforward. Can we kick off CI?

**Review by ezyang — DISMISSED** [review]

**Comment by ringohoffman** [comment]
Okay, sorry about the failures d.t. tracking an old version of main and the lint failure. I think it's good to go now.

**Comment by ringohoffman** [comment]
Can we get a re-attempt? Not sure what happened

**Comment by kit1980** [comment]
Looks like this broke test_public_bindings.py::TestPublicBindings::test_correct_module_names [GH job link](https://github.com/pytorch/pytorch/actions/runs/10172945925/job/28136657243) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/78020ea55d1bc06898577887b80c15d6d2b967dc)

**Comment by ringohoffman** [comment]
Related:

* https://github.com/pytorch/pytorch/issues/90284#issue-1479286015

`torch.masked._ops` being private caused [`python test/test_public_bindings.py -k TestPublicBindings.test_correct_module_names`](https://github.com/pytorch/pytorch/blob/89da94594e0b5d575a0edbeacb32b9267e2b4b82/test/test_public_bindings.py#L440) to fail.

A solution is to add an entry to [`test/allowlist_for_publicAPI.json`](https://github.com/pytorch/pytorch/blob/89da94594e0b5d575a0edbeacb32b9267e2b4b82/test/allowlist_for_publicAPI.json).

**Comment by ringohoffman** [comment]
Oh... I definitely did not expect that. Thanks

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
