### PR TITLE
Don't check for linalg errors on meta tensors

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #78469
* #78468
* __->__ #78467
* #78466
* #78465
* #78464
* #78463
* #78462
* #78461
* #78460
* #78459

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by IvanYashchuk — COMMENTED** [review]
Currently `_linalg_check_errors` is registered with the `CompositeExplicitAutograd` dispatch key, a more appropriate choice probably would be `CPU, CUDA`, and now with this PR also `Meta`.
```
  dispatch:
    CPU, CUDA, Meta: _linalg_check_errors
```

**Comment by Lezcano** [comment]
I do not quite understand why these tests were not passing before. `linalg.lu_factor` is a structured kernel, and this function is just called in the `IMPL` side of things. I thought that a meta tensor would just execute the META part of the function and not the IMPL part. What's going on there?

**Comment by ezyang** [comment]
@IvanYashchuk disagree; this kernel calls item so it will work for any backend

@Lezcano what you said is not quite true; lu_factor isn't the structured kernel; linalg_lu_factor_ex is structured. The outer function calls the inner and then check for errors; that's why it matters

**Review by lezcano — APPROVED** [review]

**Review by mruberry — APPROVED** [review]
Cool

**Review by anjali411 — APPROVED** [review]

**Pull request closed without merging**
