### PR TITLE
[jit] fix duplicated module input and output values in tracing module

### PR DESCRIPTION
**Pull request by nihui**
remap shall record the original inp pointers instead of remapped ones

testcase

```python
import torch
import torch.nn as nn
import torch.nn.functional as F

class Normalize(nn.Module):
    def __init__(self):
        super().__init__()

        self.norm = nn.GroupNorm(num_groups=32, num_channels=32)

    def forward(self, x, y):
        if y is None:
            y = x
        else:
            y = self.norm(y)

        y = y * 2

        return y

class G(nn.Module):
    def __init__(self):
        super().__init__()

        self.norm = Normalize()

    def forward(self, x):

        A = self.norm(x, None)
        B = F.relu(A)

        return A, B

class Net(nn.Module):
    def __init__(self):
        super().__init__()

        self.g = G()

        self.norm_1 = Normalize()

    def forward(self, x):
        hs = self.g(x)

        A, B = hs

        h = self.norm_1(B, A)
        return h

net = Net()
net = net.eval()

x = torch.randn(1, 32, 16, 16)

traced = torch.jit.trace(net, x)

print(traced.graph)
```

without this patch, there are duplicated lifted values, %80, %81, %82, %83, %84, %85
```
graph(%self.1 : __torch__.Net,
      %x : Float(1, 32, 16, 16, strides=[8192, 256, 16, 1], requires_grad=0, device=cpu)):
  %norm_1 : __torch__.___torch_mangle_1.Normalize = prim::GetAttr[name="norm_1"](%self.1)
  %g : __torch__.G = prim::GetAttr[name="g"](%self.1)
  %86 : (Tensor, Tensor, Tensor, Tensor, Tensor, Tensor, Tensor) = prim::CallMethod[name="forward"](%g, %x)
  %79 : Float(1, 32, 16, 16, strides=[8192, 256, 16, 1], requires_grad=0, device=cpu), %80 : Float(1, 32, 16, 16, strides=[8192, 256, 16, 1], requires_grad=0, device=cpu), %81 : Float(1, 32, 16, 16, strides=[8192, 256, 16, 1], requires_grad=0, device=cpu), %82 : Float(1, 32, 16, 16, strides=[8192, 256, 16, 1], requires_grad=0, device=cpu), %83 : Float(1, 32, 16, 16, strides=[8192, 256, 16, 1], requires_grad=0, device=cpu), %84 : Float(1, 32, 16, 16, strides=[8192, 256, 16, 1], requires_grad=0, device=cpu), %85 : Float(1, 32, 16, 16, strides=[8192, 256, 16, 1], requires_grad=0, device=cpu) = prim::TupleUnpack(%86)
  %87 : Tensor = prim::CallMethod[name="forward"](%norm_1, %79, %80, %81, %82, %83, %84, %85)
  return (%87)

```

with this patch
```
graph(%self.1 : __torch__.Net,
      %x : Float(1, 32, 16, 16, strides=[8192, 256, 16, 1], requires_grad=0, device=cpu)):
  %norm_1 : __torch__.___torch_mangle_1.Normalize = prim::GetAttr[name="norm_1"](%self.1)
  %g : __torch__.G = prim::GetAttr[name="g"](%self.1)
  %71 : Tensor = prim::CallMethod[name="forward"](%g, %x)
  %72 : Tensor = prim::CallMethod[name="forward"](%norm_1, %71)
  return (%72)

```

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

### CODE REVIEW

**Comment by nihui** [comment]
@jamesr66a hi, does it need a unit test here ?

**Comment by davidberard98** [comment]
@nihui a test would be great if possible - you could put it in test/jit/test_tracer.py

**Comment by davidberard98** [comment]
otherwise looks good! I'll accept once you add the test.

**Comment by nihui** [comment]
test added 😄

**Review by davidberard98 — APPROVED** [review]
thanks!

**Pull request closed without merging**
