### PR TITLE
Fix dynamo subgraph fragmentation over graph breaks with better reconstruction

### PR DESCRIPTION
**Pull request by voznesenskym**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #117906

cc @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @aakhundov

### CODE REVIEW

**Comment by voznesenskym** [comment]
90% credit to Jon, still far from done tho, added a failing test and am currently looking at some of the buggier edge cases.

**Review by Fidget-Spinner — COMMENTED** [review]
Just nits for now, I'll take a deep look at the reconstructed function soon.

**Comment by voznesenskym** [comment]
> Just nits for now, I'll take a deep look at the reconstructed function soon.

A lot of this doesn't work, and is not worth nitting - in particular, the tests have name ferrying issues masked by it all being x ;)

**Comment by voznesenskym** [comment]
In fact - I question the entire prelude strategy as it is done here - there's a ton of sus stuff that just doesn't work with this approach. The bones of it are vaguely sound, and relatively obvious as a start:

1) sub tx (inlining) should have continuation function insts produced via create_call_resume
2) we want to pick up where we left off via combining the result of (1) carefuly

However - the scope story does not work out yet... consider:

```
def h(x):
            a = x.cos()
            print(a)
            a = a.sin()
            return a

        def fn(x):
            x = x.tan()
            x = h(x)
            x = x.tan()
            return x
```

if (h) was handled as a top-level base interpreter (not inlining) - it's continuation function would look like:

(truncated for brevity)
```
[('PUSH_NULL', <class 'torch._dynamo.bytecode_transformation._NotProvided'>), 
('SWAP', <class 'torch._dynamo.bytecode_transformation._NotProvided'>), 
('LOAD_GLOBAL', '__resume_at_70_1'), 
('SWAP', <class 'torch._dynamo.bytecode_transformation._NotProvided'>), 
('LOAD_FAST', 'a'), 
('PRECALL', <class 'torch._dynamo.bytecode_transformation._NotProvided'>), 
('CALL', <class 'torch._dynamo.bytecode_transformation._NotProvided'>)]
```
This is basically doing `__resume_at_70_1(a)` ... but because of how prelude works, this is getting blapped into the ContinueExecutionCache of `fn`! The raw original bytecode of fn is

```
(Pdb) dis.dis(self.f_code)
               0 COPY_FREE_VARS           1

2158           2 RESUME                   0

2159           4 LOAD_FAST                0 (x)
               6 LOAD_METHOD              0 (tan)
              28 PRECALL                  0
              32 CALL                     0
              42 STORE_FAST               0 (x)

2160          44 PUSH_NULL
              46 LOAD_DEREF               1 (h)
              48 LOAD_FAST                0 (x)
              50 PRECALL                  1
              54 CALL                     1
              64 STORE_FAST               0 (x)

2161          66 LOAD_FAST                0 (x)
              68 LOAD_METHOD              0 (tan)
              90 PRECALL                  0
              94 CALL                     0
             104 STORE_FAST               0 (x)

2162         106 LOAD_FAST                0 (x)
             108 RETURN_VALUE
```
BLAPPING THE RESUME CALL INTO THIS IS NOT SOUND! Prior versions of this PR in @jon-chuang's tests masked the bug by having everything be called `x`! I discovered this just by reading how the prelude stuff works.

I have an alternate version of this that actually grafts the lower (inlining)(sub)tracer's code_options (aka the objects to make a codetype) up the stack of tx's to make a new CodeType to replace self.f_code with.

This *does* work for the most part - but the problem now arises in remapping the original interpreter source and the rewritten one - we still end up with places referencing the original code, and the whole thing just ends up feeling sus as hell.

So, I think I am going way back to the drawing board on this one, here is where I am at:

1) All instruction translators know how to resume
2) create_call_resume IS necessary for subtracers
3) TBD if it needs to be the same for base vs inlining
4) We need some new structures for marshalling around scope properly - specifically, if we consider the case above we need `a` to not only exist, we need it to be in the same exact state as if we had a top level non inlining instruction translator enter on `h` and graph break! That is to say - it needs to be identical to us running our graph up to that point, which in the direct-to-h case is `cos(x)` or in the `fn` call case is `cos(cos(x))`. For the latter, this *should* be possible because ostensibly our stitching has provided us with a graph that is `cos(cos(x))` - the problem is now in how to properly associate that with the LOAD_FAST a - this feels like an inverse of our output codegen, wherein we produce a postamble to our user-defined-callback-returned-callable that maps the outputs to variables in the user calling scope. This needs more thinking.

**Comment by ezyang** [comment]
A lot of the discussion in your most recent comment is around managing scope, but it's not clear to me why scope is the lynchpin of the entire affair. In particular, as you observe, if we were to have graph break in h as top-level, we already know how to generate code that sets up the 'a' local so the subsequent bytecode accessing it has something valid. So it doesn't seem like we need anything new, we've already got what we need.

Let's talk about the inner graph break from fn. Ordinarily (pre this patch), I would generate the following bytecode sequence:

1. Call FX graph for fn prefix only
2. Call resume function
  a. Restore local state
  b. Do the rest of the bytecode (starting off with a call to h)

What do I want out of the modified sequence? First, the FX graph is now for prefix of fn and prefix of h, and has a bunch of extra outputs which will be useful for restoring h's local state. I think I would still prefer to call it up front. Then, I want to call not into a vanilla h, but a modified h which can take the extra outputs, restore local state, and go straight to the graph break point. So in the end, I have this:

1. Call FX graph for fn prefix and h prefix, returning fn and h intermediates
2. Restore local state for fn using fn intermediates
3. Call into semi-compiled h, passing h intermediates
  a. Restore local state for h, using h intermediates
  b. Do the rest of h suffix bytecode
  c. Return
4. Do rest of fn suffix bytecode

**Comment by voznesenskym** [comment]
> A lot of the discussion in your most recent comment is around managing scope, but it's not clear to me why scope is the lynchpin of the entire affair. In particular, as you observe, if we were to have graph break in h as top-level, we already know how to generate code that sets up the 'a' local so the subsequent bytecode accessing it has something valid. So it doesn't seem like we need anything new, we've already got what we need.
> 
> Let's talk about the inner graph break from fn. Ordinarily (pre this patch), I would generate the following bytecode sequence:
> 
> 1. Call FX graph for fn prefix only
> 2. Call resume function
>    a. Restore local state
>    b. Do the rest of the bytecode (starting off with a call to h)
> 
> What do I want out of the modified sequence? First, the FX graph is now for prefix of fn and prefix of h, and has a bunch of extra outputs which will be useful for restoring h's local state. I think I would still prefer to call it up front. Then, I want to call not into a vanilla h, but a modified h which can take the extra outputs, restore local state, and go straight to the graph break point. So in the end, I have this:
> 
> 1. Call FX graph for fn prefix and h prefix, returning fn and h intermediates
> 2. Restore local state for fn using fn intermediates
> 3. Call into semi-compiled h, passing h intermediates
>    a. Restore local state for h, using h intermediates
>    b. Do the rest of h suffix bytecode
>    c. Return
> 4. Do rest of fn suffix bytecode

This is similar to my current approach as hinted at in "this feels like an inverse of our output codegen" - I am using the subtracer output graph output as a prelude to the prelude.

**Comment by voznesenskym** [comment]
> A lot of the discussion in your most recent comment is around managing scope, but it's not clear to me why scope is the lynchpin of the entire affair.

Ehh - scope was the major issue in the current PR. It is not necessarily the lynchpin of anything.

**Comment by voznesenskym** [comment]
I rewrote the bytecode stitching algorithm - it now works, partially - in the cos x 6 motivating example described in #111003 - it produces a solution about halfway to where we want it

Before we would basically have

```
graph:
   cos()
```  

6 times over

Now, with my latest fix, we have
```
graph:
   cos()
   cos()
   cos()
```
And then the 
```
graph:
   cos()
```  
3 times over! So a huge improvement in that we correctly stitch together the initial pre-graph break code, BUT once we hit the graph break, we don't cascade the returns up to their parent graph - we re-enter recursively allowing the returns to do their thing.

It is resilient to name changes, etc.

This is still a huge improvement over the status quo, imo, and a good stepping stone. Going to keep playing with it.

**Comment by voznesenskym** [comment]
Current state:

(1) python example.py works
(2) python example2.py does not

This is due to scope / nesting name issues.

**Comment by voznesenskym** [comment]
> Current state:
> 
> (1) python example.py works (2) python example2.py does not
> 
> This is due to scope / nesting name issues.

batsignal @jansel !!!

**Comment by voznesenskym** [comment]
Spoke to Jansel, made some progress.

This state of the PR passes all the same tests, but fails assert code.co_freevars == out_code.co_freevars - this is progress as it is no longer failing when generating the code at reconstruction creation time as we graph break.

AssertionError: ("free var mismatch: old code object has free var ('g',), new code object has free var ('g', 'h')", <code object f at 0x7f026d14e9c0, file "/data/users/voz/pytorch/example2.py", line 19>, None)

I'm not sure this is everything we need. Hitting that exception makes sense, and its a good exception, it segfaults if we comment it out (look like attempt to deref null cause bytecode is wrong?).

Going to sleep on it, and bat signal @jansel  again.

**Comment by jansel** [comment]
I gave some pointers via workchat -- is there something you want me to look at in this PR?  It doesn't seem ready yet.

**Pull request closed without merging**
