### PR TITLE
Allow user to disable built-in fuser when using TorchDynamo

### PR DESCRIPTION
**Pull request by wschin**
Pytorch's built-in fuser seems have higher priority than my fuser registered via
```cpp
  torch::jit::RegisterPass pass([accelerator_symbol](std::shared_ptr<torch::jit::Graph>& g) {
    OrtFuseGraph(g, Accelerator::Supported, accelerator_symbol);
  });
```
With this PR, I can reuse `aot_autograd` backend in TorchDynamo with my own JIT fuser. My custom context is
```python
class AOTAutogradOrtFusionWithContext:
    """Pass nvfuser context to TorchDynamo"""

    def __init__(self):
        self.backend_ctx_ctor = lambda: torch.jit.fuser("none")

    def __call__(self, gm: torch.fx.GraphModule, example_inputs):
        return AOTAutogradMemoryEfficientFusion.compile_fn(gm, example_inputs)


aot_autograd_ort_strategy = AOTAutogradOrtFusionWithContext()
```

### CODE REVIEW

**Comment by bdhirsh** [comment]
@eellison tagging you for the JIT fuser changes, but feel free to re-tag if you think someone else should take a look

**Comment by wschin** [comment]
@davidberard98, gentle ping for review. Thanks.

**Review by davidberard98 — APPROVED** [review]
looks good, thanks for the PR!

**Pull request closed without merging**
