### PR TITLE
specializeGradSumToSize patch - propagate profile_none through profile_ivalue

### PR DESCRIPTION
**Pull request by jjsjann123**
simply propagate profile_none_ value through profile_ivalue nodes inserted by nvfuser.

Without the propagation, profile_ivalue inserted by other passes would block the optimization on no-op sum_to_size.

cc @gmagogsfm

### CODE REVIEW

**Comment by jjsjann123** [comment]
bump for review :bow:

**Review by eellison — COMMENTED** [review]
Do you have a small test or repro I can look at for this ?

**Comment by jjsjann123** [comment]
Here's quick example:
```
import torch                                                                                                                                                                                                       
from torch.testing._internal.jit_utils import disable_autodiff_subgraph_inlining                                           
                                                                                                                           
with disable_autodiff_subgraph_inlining(True):                                                                             
  with torch.jit.fuser("fuser2"):                                                                                          
    @torch.jit.script                                                                                                      
    def t(t0: torch.Tensor, t1: torch.Tensor):                                                                             
      return t0 + t1                                                                                                       
                                                                                                                           
    t0 = torch.randn(5, 10).requires_grad_()                                                                               
    t1 = torch.randn(5, 10).requires_grad_()                                                                               
    o = t(t0, t1)                                                                                                          
    o.sum().backward()                                                                                                     
    o = t(t0, t1)                                                                                                          
    o.sum().backward()                                                                                                     
    o = t(t0, t1)                                                                                                          
    o.sum().backward()
```

We are profiling the List[int] input to `_grad_sum_to_size` op on backwards, because nvfuser would want to get a static reduction axes for backwards. That inserted nodes is breaking the no-op optimization on the op.

Instrumented graph looks like:
```
Profiled Graph:                                                                                                            
graph(%0 : Tensor,                                                                                                         
      %self_size.2 : int[]?,                                                                                               
      %other_size.2 : int[]?):                                                                                             
  %39 : int[]? = prim::profile_ivalue[none_counts={"num_none": 0, "num_present": 0}](%self_size.2)                         
  %38 : int[]? = prim::profile_ivalue[none_counts={"num_none": 0, "num_present": 0}](%other_size.2)                        
  %3 : int = prim::Constant[value=1]()                                                                                     
  %21 : Tensor = prim::profile[profiled_type=Tensor](%0)                                                                   
  %4 : int = prim::AutogradAnyNonZero(%21)                                                                                 
  %5 : Tensor = prim::If(%4)                                                                                               
    block0():                                                                                                              
      %22 : Tensor = prim::profile[profiled_type=Tensor](%0)                                                               
      -> (%22)                                                                                                             
    block1():                                                                                                              
      %6 : Tensor = prim::AutogradZero()                                                                                   
      %23 : Tensor = prim::profile[profiled_type=Tensor](%6)                                                               
      -> (%23)                                                                                                             
  %24 : Tensor = prim::profile[profiled_type=Tensor](%5)                                                                   
  %7 : int = prim::AutogradAnyNonZero(%24)                                                                                 
  %grad_self.4 : Tensor, %grad_other.4 : Tensor = prim::If(%7)                                                             
    block0():                                                                                                              
      %25 : Tensor = prim::profile[profiled_type=Tensor](%5)                                                               
      %10 : Tensor = aten::mul(%25, %3) # <string>:12:30                                                                   
      %26 : Tensor = prim::profile[profiled_type=Tensor](%10)                                                              
      %40 : int[]? = prim::profile_ivalue(%38)                                                                             
      %grad_other.3 : Tensor = aten::_grad_sum_to_size(%26, %40) # <string>:12:30                                          
      %27 : Tensor = prim::profile[profiled_type=Tensor](%5)                                                               
      %41 : int[]? = prim::profile_ivalue(%39)                                                                                                                                                                     
      %grad_self.3 : Tensor = aten::_grad_sum_to_size(%27, %41) # <string>:13:29                                           
      %28 : Tensor = prim::profile[profiled_type=Tensor](%grad_self.3)                                                     
      %29 : Tensor = prim::profile[profiled_type=Tensor](%grad_other.3)                                                    
      -> (%28, %29)                                                                                                        
    block1():                                                                                                              
      %13 : Tensor = prim::AutogradZero()                                                                                  
      %30 : Tensor = prim::profile[profiled_type=Tensor](%13)                                                              
      %31 : Tensor = prim::profile[profiled_type=Tensor](%13)                                                              
      -> (%30, %31)                                                                                                        
  %32 : Tensor = prim::profile[profiled_type=Tensor](%grad_other.4)                                                        
  %14 : int = prim::AutogradAnyNonZero(%32)                                                                                
  %grad_other.1 : Tensor = prim::If(%14)                                                                                   
    block0():                                                                                                              
      %33 : Tensor = prim::profile[profiled_type=Tensor](%grad_other.4)                                                    
      -> (%33)                                                                                                             
    block1():                                                                                                              
      %16 : Tensor = prim::AutogradZero()                                                                                  
      %34 : Tensor = prim::profile[profiled_type=Tensor](%16)                                                              
      -> (%34)                                                                                                             
  %35 : Tensor = prim::profile[profiled_type=Tensor](%grad_self.4)                                                         
  %17 : int = prim::AutogradAnyNonZero(%35)                                                                                
  %grad_self.1 : Tensor = prim::If(%17)                                                                                    
    block0():                                                                                                              
      %36 : Tensor = prim::profile[profiled_type=Tensor](%grad_self.4)                                                     
      -> (%36)                                                                                                             
    block1():                                                                                                              
      %19 : Tensor = prim::AutogradZero()                                                                                  
      %37 : Tensor = prim::profile[profiled_type=Tensor](%19)                                                              
      -> (%37)                                                                                                             
  %20 : (Tensor, Tensor) = prim::TupleConstruct(%grad_other.1, %grad_self.1)                                               
   = prim::profile()                                                                                                       
  return (%20)
```

**Review by eellison — APPROVED** [review]
lgtm but waiting on @Krovatkin review as well

**Review by Krovatkin — APPROVED** [review]
:shipit:

lmao, what did we insert `%41 : int[]? = prim::profile_ivalue(%39)` for?

**Pull request closed without merging**
