### PR TITLE
[Pytorch] Build lite interpreter as default for iOS

### PR DESCRIPTION
**Pull request by cccclai**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#55733 [Pytorch] Build lite interpreter as default for iOS**

Summary:
Two changes:
1. Build lite interpreter as default for iOS
2. Switch the previous lite interpreter test to full jit build test
Test Plan:
image

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D27698039](https://our.internmc.facebook.com/intern/diff/D27698039)

### CODE REVIEW

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by xta0** [comment]
Commented in Phabricator.

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27698039).

**Comment by bigfootjon** [comment]
Internal commit was malformed, which left this PR open. Closing manually

**Comment by cccclai** [comment]
Closing, merged in with https://github.com/pytorch/pytorch/commit/b5a834a73904b61185c09e41d4e711afc12c8b87

**Pull request closed without merging**
