### PR TITLE
Port `tril` and `triu` to structured kernels

### PR DESCRIPTION
**Pull request by cbalioglu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #67055

This PR ports `tril` and `triu` operations to structured kernels.

Differential Revision: [D31844638](https://our.internmc.facebook.com/intern/diff/D31844638/)

### CODE REVIEW

**Review by IvanYashchuk — DISMISSED** [review]
This is a nice fix, but I think a better way to get the `'meta'` device support for these functions is to port them to be structured. Example [PRs can be found with `module: structured kernels` label](https://github.com/pytorch/pytorch/pulls?q=is%3Aopen+is%3Apr+label%3A%22module%3A+structured+kernels%22). General information about it is available here https://github.com/pytorch/rfcs/blob/rfc-0005/RFC-0005-structured-kernel-definitions.md.

**Review by IvanYashchuk — COMMENTED** [review]
The change for structured kernels looks great! I think a few `skipMeta` are unnecessary and having a test that just verifies the shape of the output would be useful.

Unfortunately, the test failure is real.
See `# test stride 0 cases` in `test_trilu_indices`. Previously it would raise an error:
> unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.
Now there is no error. Could you please verify whether the new behavior makes sense?

**Review by lezcano — COMMENTED** [review]
Note that the body of these two functions is the same, so it can be factored out to a `_tril_triu_impl` that is templated by a boolean and then forwards that boolean to `apply_triu_tril`. This way we could avoid all the repeated code.

**Review by IvanYashchuk — APPROVED** [review]
CI build failure is real though.

**Review by lezcano — APPROVED** [review]
Wow, that was some really heavy lifting with those classes there. In my head I had thought about doing a if-else and repeat the dispatcher code, but this repeats even less code :D

**Review by bdhirsh — APPROVED** [review]
structured kernel changes look good :)

**Pull request closed without merging**
