### PR TITLE
Sync from FBCode

### PR DESCRIPTION
**Pull request by xiaomengy**

### CODE REVIEW

**Comment by orionr** [comment]
@ezyang, @soumith, @apaszke  - looks like insertion of Python 2 compatibility to `setup.py` is what triggered review from you all.

**Review by soumith — APPROVED** [review]
approved setup.py changes

**Comment by orionr** [comment]
Let's land https://github.com/pytorch/pytorch/pull/6378 instead of this one, since I think it adds some things back that were missed. Can you work with @yinghai? Thanks.

**Comment by yinghai** [comment]
Closing as we are dealing it with https://github.com/pytorch/pytorch/pull/6378

**Pull request closed without merging**
