### PR TITLE
Revise CPU vectorization ISA support API

### PR DESCRIPTION
**Pull request by sanchitintel**
Revising (mostly renaming) CPU vectorization ISA support API (non-frontend-user-facing). Also added AVX512_BF16 ISA detection API.

cc @jgong5 @mingfeima @XiaobingSuper @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @rec

### CODE REVIEW

**Review by leslie-fang-intel — APPROVED** [review]

**Review by jgong5 — APPROVED** [review]

**Comment by sanchitintel** [comment]
Hi @ezyang, due to a few files this PR modifies, it requires approval from a core-reviewer/core-maintainer. Can you please help review this PR? BTW, the CI failures are unrelated. Thanks!

**Review by ezyang — APPROVED** [review]
okey dokey

**Pull request closed without merging**
