### PR TITLE
Expose onnx_shape_inference option in torch.onnx.export

### PR DESCRIPTION
**Pull request by take-cheeze**
Some model export fails when it's `True` so I need this for a workaround

### CODE REVIEW

**Comment by SplitInfinity** [comment]
cc: @BowenBao

**Comment by BowenBao** [comment]
@take-cheeze thanks for submitting the PR. We are in the progress of actually deprecating this flag, and fixing some known issues with current shape inference (e.g. https://github.com/pytorch/pytorch/pull/60335). Could you share a few simple repro if possible?

cc @jiafatom

**Comment by take-cheeze** [comment]
@BowenBao 
Sorry for late answer.
The main problem I'm facing is when there is too many onnx models to export, constant folding in shape inference takes too much time and it exceeded maximum time of CI I was running.
And Thank you for suggesting `torch.onnx._export`. I'm actually using pytorch-pfn-extras and it will call that so I'm not directly facing the problem: https://github.com/pfnet/pytorch-pfn-extras/blob/2f9819fcfdea4c7ca3c8780584849dc4ca944c79/pytorch_pfn_extras/onnx/export_testcase.py#L16
Though I still would like this feature to be configurable since it's not always effective in model exporting.

**Comment by BowenBao** [comment]
@take-cheeze since it is using `_export` api it should have `onnx_shape_inference` argument available. Does it unblock the issue in your case? If so is it ok to close this PR? 
Not having shape inference has a high chance of getting incorrect model when model and inputs are dynamically shaped. That's why we want to keep it as internal flag for advanced users if they know what they are doing. Could you provide roughly how much longer it takes for the model to export when `onnx_shape_inference` is turned on?

**Pull request closed without merging**
