### PR TITLE
[quant] Guard against copying from quantized Tensor to non-quantized Tensor

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#29660 [quant] Guard against copying from quantized Tensor to non-quantized Tensor**

Summary:
att

Test Plan:
python test/test_quantized_tensor.py

Reviewers:
pt1quant

Subscribers:

Tasks:

Tags:

Differential Revision: [D18799897](https://our.internmc.facebook.com/intern/diff/D18799897)

### CODE REVIEW

**Review by gchanan — COMMENTED** [review]
why isn't it allowed?

**Comment by jerryzh168** [comment]
> why isn't it allowed?

don't we want to make this more explicit?

**Comment by z-a-f** [comment]
Is this a one-way check only?

**Comment by jerryzh168** [comment]
> Is this a one-way check only?

copying from non-quantized to quantized is supported, although we only support copying from float, we should probably add assert for that as well

**Review by jamesr66a — APPROVED** [review]
Was this causing issues for users somewhere? I suppose this is fine to be more explicit

**Comment by jerryzh168** [comment]
> Was this causing issues for users somewhere? I suppose this is fine to be more explicit

no, just found this when I'm changing other code

**Pull request closed without merging**
