### PR TITLE
typo

### PR DESCRIPTION
**Pull request by stas00**
a small grammar fix

@jspisak - thank you!

### CODE REVIEW

**Review by jspisak — APPROVED** [review]

**Comment by jspisak** [comment]
@brianjo - since this one is in core, do you want to land it in phabricator? Otherwise, happy to support.

**Comment by stas00** [comment]
looks like this one fell between the cracks

**Comment by jspisak** [comment]
imported and will land it. Thanks!!

**Comment by stas00** [comment]
ping

**Comment by brianjo** [comment]
I thought I merged this one. It doesn't show up with any action for me. I'll give it another go. Thanks!

**Comment by stas00** [comment]
Normally the bot auto-closes the PR when this happens.

**Pull request closed without merging**
