### PR TITLE
[pytorch][ci] add LLVM-dev package to android docker image

### PR DESCRIPTION
**Pull request by ljk53**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #30866 [pytorch] generate op dependency graph as python code
* #30937 [pytorch] integrate op dependency analysis process into CI
* **#31215 [pytorch][ci] add LLVM-dev package to android docker image**

Summary:
Install LLVM-dev package for code analysis CI job: #30937

LLVM-dev package is not related to android NDK but the whole code
analysis thing is for mobile custom build so choose this docker image.

Test Plan:
- wait docker image to build?

Differential Revision: [D19193223](https://our.internmc.facebook.com/intern/diff/D19193223)

### CODE REVIEW

**Comment by ljk53** [comment]
@ezyang - I haven't updated docker image since you migrated it from jenkins to circleci. How can I force it to create docker images before landing this PR?
The next step is to change all "docker_image: ... :405" to the new docker image version, right?

**Comment by ezyang** [comment]
Oops. @mingbowan I forgot to ask you if there's a way to manually trigger builds when you moved these to https://github.com/pytorch/pytorch/pull/29932 . Do you know?

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit f6ee875:


* **1/1** broken upstream at merge base 4c34158 (see [grid view](https://dr.pytorch.org/master-timeline.html?count=1&sha1=4c341582ea18f241628c6e1756633bc9f897b76d&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35))
  <details>
  <summary>
  You may want to rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  
* **0/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=f6ee875f655661962c6928bcb47073a3f0e511df).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably caused by upstream breakages:
* [pytorch_linux_xenial_py3_clang5_asan_test](https://dr.pytorch.org/build-details.html?build_id=78141431)



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by ljk53** [comment]
shall I go ahead land this directly?

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
