### PR TITLE
Add missing ChainDataset to dataset.pyi

### PR DESCRIPTION
**Pull request by bryant1410**

### CODE REVIEW

**Review by ssnl — APPROVED** [review]
LGTM. Thank you!

**Comment by ejguan** [comment]
Thanks for submitting this PR.
It seems we are no longer using the stub file for dataset.

**Comment by bryant1410** [comment]
@ejguan should we close this PR then?

**Comment by ejguan** [comment]
Closing it since stub files are no longer needed.
Thank you so much @bryant1410

**Pull request closed without merging**
