### PR TITLE
Removed hip call hipDeviceSynchronize

### PR DESCRIPTION
**Pull request by BLOrange-AMD**
Similar to CUDA, fixed test_profiler_tree.py::TestProfilerTree unit test suites by DeviceSynchronize call removal.

@jithunnair-amd @pruthvistony

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
Maybe add a comment like the CUDA part has?

**Review by jithunnair-amd — APPROVED** [review]

**Pull request closed without merging**
