### PR TITLE
Replace calls to _aminmax and add deprecation warning

### PR DESCRIPTION
**Pull request by heitorschueroff**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #62432

Differential Revision: [D30072245](https://our.internmc.facebook.com/intern/diff/D30072245)

### CODE REVIEW

**Comment by heitorschueroff** [comment]
@heitorschueroff has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30072245).

**Comment by heitorschueroff** [comment]
@heitorschueroff has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30072245).

**Comment by heitorschueroff** [comment]
@heitorschueroff has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30072245).

**Review by ngimel — APPROVED** [review]

**Comment by heitorschueroff** [comment]
@heitorschueroff has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30072245).

**Comment by mruberry** [comment]
fyi @vkuzo, @dhruvbird 

@dhruvbird, is this going to break any mobile models? Is there some reasonable way we could identify possible mobile breaks in advance?

**Comment by mruberry** [comment]
Mooted by a more recent PR.

**Pull request closed without merging**
