### PR TITLE
[Inductor] Use sleef implementation for CPP backend asinh codegen

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #142360

**Summary**
Fix https://github.com/pytorch/pytorch/issues/142345. Previously, we use `asinh(x) = log(x + sqrt(1 + x**2))` to calculate the result of `asinh`, the issue happens when input with `-10000.1`, which makes `x + sqrt(1 + x**2)` close to 0 and log(0) is invalid. We use the `sleef` implementation in this PR to fix this issue.

**Test Plan**
```
python -u -m pytest -s -v test/inductor/test_cpu_repro.py -k test_asinh_with_corner_inputs
```

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Comment by jeanschmidt** [comment]
@pytorchbot revert -m "seems to have broken macos tests" -c nosignal

example of a broken ci job https://github.com/pytorch/pytorch/actions/runs/12290557650/job/34298356770

**Comment by malfet** [comment]
@leslie-fang-intel please rebase your PR and figure out the failures

**Comment by leslie-fang-intel** [comment]
From the error msg: https://github.com/pytorch/pytorch/actions/runs/12290557650/job/34298356770, probably due to I didn't add the corresponding implementation for MacOS. I have rebased this PR and adding corresponding implementation for other platforms. Check the CI now.

**Comment by leslie-fang-intel** [comment]
Thanks @malfet, the macos related testing passes. I am going to re-land this PR.

**Pull request closed without merging**
