### PR TITLE
[profiler] add enabled API to autograd profiler

### PR DESCRIPTION
**Pull request by rohan-varma**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#31380 [profiler] add enabled API to autograd profiler**

For being able to profile async RPCs, we attach a `RecordFunction` object to the future that is created during the RPC to persist it across the lifetime of the RPC (this is implemented in the next PR:#31381  ). Since we'd only like to do this when profiling is enabled, this PR adds an enabled API to the autograd profiler.

Differential Revision: [D19050391](https://our.internmc.facebook.com/intern/diff/D19050391/)

### CODE REVIEW

**Comment by pritamdamania87** [comment]
Don't we already check if the profiler is enabled in #31381 and attach the RecordFunction only in those cases? Otherwise the rf_ pointer is nullptr?

**Comment by rohan-varma** [comment]
@pritamdamania87 : That check relies on this change, in particular, it uses `torch.autograd._profiler_enabled()` here: https://github.com/pytorch/pytorch/pull/31381/files#diff-5e438ccfe0d61a53077ec02243a79f07R277

**Review by pritamdamania87 — APPROVED** [review]

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit d48610b4:


* **1/2** broken upstream at merge base 3a19980b (see [grid view](https://dr.pytorch.org/master-timeline.html?count=1&sha1=3a19980b78b6638235edef367784ecc3dc37e364&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35))
  <details>
  <summary>
  You may want to rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch origin viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  
* **1/2** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=d48610b4596eb578d61e0850828b4ad882e22092).

### :detective: 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4043698) pytorch_linux_xenial_cuda9_cudnn7_py3_slow_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=78526151) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=78526151))
<details>
<summary>
<code>Dec 21 01:42:10 RuntimeError: test_torch failed!</code>
</summary>

```
Dec 21 01:42:09 Ran 2875 tests in 74.847s 
Dec 21 01:42:09  
Dec 21 01:42:09 FAILED (errors=3, skipped=2861) 
Dec 21 01:42:09  
Dec 21 01:42:09 Generating XML reports... 
Dec 21 01:42:10 Traceback (most recent call last): 
Dec 21 01:42:10   File "test/run_test.py", line 456, in <module> 
Dec 21 01:42:10     main() 
Dec 21 01:42:10   File "test/run_test.py", line 449, in main 
Dec 21 01:42:10     raise RuntimeError(message) 
Dec 21 01:42:10 RuntimeError: test_torch failed! 
Dec 21 01:42:11 + cleanup 
Dec 21 01:42:11 + retcode=1 
Dec 21 01:42:11 + set +x 
Dec 21 01:42:11 =================== sccache compilation log =================== 
Dec 21 01:42:11 ERROR:sccache::server: Compilation failed: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "/tmp/torch_extensions/test_compilation_error_formatting/main.cpp: In function \'int main()\':\n/tmp/torch_extensions/test_compilation_error_formatting/main.cpp:2:23: error: expected \';\' before \'}\' token\n int main() { return 0 }\n                       ^\n" } 
Dec 21 01:42:11  
Dec 21 01:42:11 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 21 01:42:11 Compile requests               128 
Dec 21 01:42:11 Compile requests executed       47 
Dec 21 01:42:11 Cache hits                      36 
```

</details>

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably caused by upstream breakages:
* [pytorch_linux_xenial_py3_clang5_asan_test](https://dr.pytorch.org/build-details.html?build_id=78518271)



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by rohan-varma** [comment]
Test failures are unrelated:

```
Dec 21 11:16:48 self = <[MemoryError("std::bad_alloc") raised in repr()] SafeRepr object at 0x7f634539b5f0>
Dec 21 11:16:48 k = 'Y_scale'
Dec 21 11:16:48 
Dec 21 11:16:48     def _node_getitem(self, k):
Dec 21 11:16:48         r"""
Dec 21 11:16:48         Accessor for attributes of a node which is polymorphic over
Dec 21 11:16:48         return type.
Dec 21 11:16:48     
Dec 21 11:16:48         NB: This is monkey-patched onto Node.
Dec 21 11:16:48         """
Dec 21 11:16:48 >       sel = self.kindOf(k)
Dec 21 11:16:48 E       RuntimeError: required keyword attribute 'Y_scale' is undefined
Dec 21 11:16:48 
Dec 21 11:16:48 ../.local/lib/python2.7/site-packages/torch/onnx/utils.py:836: RuntimeError
```

and 

```
Dec 21 11:36:57 SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /var/lib/jenkins/workspace/third_party/fbgemm/src/QuantUtilsAvx2.cc:98:14 in 
Dec 21 11:36:57 Traceback (most recent call last):
Dec 21 11:36:57   File "test/run_test.py", line 456, in <module>
Dec 21 11:36:57     main()
Dec 21 11:36:57   File "test/run_test.py", line 449, in main
Dec 21 11:36:57     raise RuntimeError(message)
Dec 21 11:36:57 RuntimeError: test_quantization failed!
Dec 21 11:36:57 + cleanup
Dec 21 11:36:57 + retcode=1
Dec 21 11:36:57 + set +x
```

**Pull request closed without merging**
