### PR TITLE
fix sccache issue on Windows CPU

### LINKED ISSUE #68796: Figure out why sccache is not working for Windows CPU builds
build with cu113
```
Compile requests                   4677
Compile requests executed          4495
Cache hits                         4449
Cache hits (C/C++)                 4449
```
https://app.circleci.com/pipelines/github/pytorch/pytorch/413452/workflows/4b08afe6-6af0-4dc2-9e43-6092b599f13f/jobs/16762126?invite=true#step-104-5010

build with cpu
```
Compile requests                   4312
Compile requests executed            48
Cache hits                            4
Cache hits (C/C++)                    4
```
https://app.circleci.com/pipelines/github/pytorch/pytorch/413452/workflows/4b08afe6-6af0-4dc2-9e43-6092b599f13f/jobs/16762048?invite=true#step-104-4967

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm

### PR DESCRIPTION
**Pull request by mszhanyi**
Fixes #68796

```
2021-11-24T10:12:40.7634007Z Compile requests                   4312
2021-11-24T10:12:40.7634484Z Compile requests executed          4300
2021-11-24T10:12:40.7634823Z Cache hits                         4227
2021-11-24T10:12:40.7635122Z Cache hits (C/C++)                 4227
2021-11-24T10:12:40.7636139Z Cache misses                         62
2021-11-24T10:12:40.7636930Z Cache misses (C/C++)                 62
2021-11-24T10:12:40.7637333Z Cache timeouts                        0
2021-11-24T10:12:40.7637839Z Cache read errors                     0
2021-11-24T10:12:40.7638161Z Forced recaches                       0
2021-11-24T10:12:40.7638489Z Cache write errors                    0
2021-11-24T10:12:40.7638828Z Compilation failures                  1
2021-11-24T10:12:40.7639180Z Cache errors                         10
2021-11-24T10:12:40.7639490Z Cache errors (C/C++)                 10
2021-11-24T10:12:40.7639856Z Non-cacheable compilations            0
2021-11-24T10:12:40.7640244Z Non-cacheable calls                   0
2021-11-24T10:12:40.7640601Z Non-compilation calls                12
2021-11-24T10:12:40.7640987Z Unsupported compiler calls            0
2021-11-24T10:12:40.7641426Z Average cache write               0.104 s
2021-11-24T10:12:40.7641763Z Average cache read miss           6.000 s
2021-11-24T10:12:40.7642110Z Average cache read hit            0.046 s
2021-11-24T10:12:40.7642485Z Failed distributed compilations       0
```
https://github.com/pytorch/pytorch/runs/4310176911?check_suite_focus=true

cc @seemethere @malfet @pytorch/pytorch-dev-infra

### CODE REVIEW

**Comment by mszhanyi** [comment]
There was a bug in https://github.com/pytorch/pytorch/blob/7d8a79b6f31eccb94aa8ce38935917f476b534d5/CMakeLists.txt#L670-L678

If it was built on CPU, CMAKE_CUDA_COMPILER_VERSION is null (null < 10.2), so `CMAKE_CUDA_COMPILER_VERSION VERSION_LESS 10.2 `is always TRUE on Windows CPU.

As a result, cmake will always use response_file on Windows CPU machine.
@ is used to  specify Response File, but sccache doesn't know it.
That is the reason of 
```
Non-cacheable reasons:
@                                   4253
```

**Comment by mszhanyi** [comment]
It could save 20 more minutes to finish the build

**Review by janeyx99 — APPROVED** [review]

**Comment by janeyx99** [comment]
Thanks so much @mszhanyi--this is awesome!

**Comment by seemethere** [comment]
Thanks so much for this @mszhanyi! 😃

**Pull request closed without merging**
