### PR TITLE
_force_original_view_tracking to work as both context manager and function

### PR DESCRIPTION
**Pull request by poseljacob**
Fix _force_original_view_tracking to work as a function as well as a context manager, as stated by documentation. 

Applied similar fixes to PR: https://github.com/pytorch/pytorch/pull/105291

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Sounds good to me, thanks for the fix!
Should we just remove _ViewReplayEnabled binding now?

cc @zou3519 who was looking at some of these context managers.

**Comment by poseljacob** [comment]
> Sounds good to me, thanks for the fix! Should we just remove _ViewReplayEnabled binding now?
> 
> cc @zou3519 who was looking at some of these context managers.

Happy to remove _ViewReplayEnabled binding. Would you like me to go ahead and do that or wait for @zou3519's opinion?

**Comment by albanD** [comment]
Hey!
Just had a quick chat with him, the get/set is good. Let's remove the un-used bindings here and `_MultithreadingEnabled` from the other PR just to keep things as simple as possible.

**Comment by poseljacob** [comment]
Cool, thanks for checking up!

**Review by albanD — APPROVED** [review]
Thanks for the quick update!

**Pull request closed without merging**
