### PR TITLE
Remove c10::either

### PR DESCRIPTION
**Pull request by cyyever**
Time to remove it.

cc @albanD

### CODE REVIEW

**Comment by cyyever** [comment]
@albanD  A missing change was submitted, have to re-import

**Comment by albanD** [comment]
@pytorchbot merge

Fixed internal failures in the linked diff.

**Review by albanD — APPROVED** [review]

**Comment by albanD** [comment]
I have to reapply internal patch and everything. Please don't merge

**Comment by cyyever** [comment]
@albanD Should we merge it?

**Comment by albanD** [comment]
@pytorchbot merge

Sorry for the delay, take forever to get my internal env setup again every time. Should be good now

**Pull request closed without merging**
