### PR TITLE
[Cherrypick] Support parsing Ellipsis in JIT frontend 

### PR DESCRIPTION
**Pull request by gmagogsfm**
This fixes a bug in FX+TorchScript integration

Link to landed master PR (if applicable): #53576
Link to release branch PR: self
Criteria Category:`3. Fixes to new features introduced in the most recent minor release (e.g. 1.8.1 for 1.8.x release)

### CODE REVIEW

**Comment by ezyang** [comment]
looks like the merge on this pr was botched

**Comment by gmagogsfm** [comment]
> looks like the merge on this pr was botched

Hmm, that's strange the files showing merge conflicts are not really touched by this PR. Maybe I can help with manually resolving the conflicts? Not sure if I have permission to do it with a release branch though

**Comment by ezyang** [comment]
my guess is you took a commit based off master, and then opened a PR to release/1.8. GitHub is not smart, it will think your commit *plus every single commit in master before it* is part of the PR request

**Comment by gmagogsfm** [comment]
> my guess is you took a commit based off master, and then opened a PR to release/1.8. GitHub is not smart, it will think your commit _plus every single commit in master before it_ is part of the PR request


Yeah, that would explain it, I will try rebase my change on top of release/1.8 and create a PR out of it

**Comment by gmagogsfm** [comment]
Made a new PR to address merge conflicts: #53766

**Pull request closed without merging**
