### PR TITLE
[quant][graphmode][fx] Use the new convert function instead of the old one in quant-fx2trt tests

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #67132
* #67131
* #67129
* #67070
* #67067
* #67066
* __->__ #67065

Summary:
Switching to use _convert_fx_do_not_use in the tests

Test Plan:
python test/test_quantization.py TestQuantizeFxTRTOps

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D31849077](https://our.internmc.facebook.com/intern/diff/D31849077)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31849077).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31849077).

**Review by vkuzo — APPROVED** [review]
nit, would it be possible to fill out the test plan?  It's a good practice and will also set a good example for other engineers who might see this diff later.

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31849077).

**Pull request closed without merging**
