### PR TITLE
[dynamo][pytree][1/N] make CXX pytree traceable: `tree_iter` / `tree_leaves`

### PR DESCRIPTION
**Pull request by XuehaiPan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #138056
* #130141
* #137884
* #137400
* #113258
* #113257
* #137399
* #130140
* #137398
* __->__ #137397

cc @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Review by jansel — CHANGES_REQUESTED** [review]
Could we use the python version of pytree that already exists rather than having a new implementation in polyfils?

**Comment by XuehaiPan** [comment]
> Could we use the python version of pytree that already exists rather than having a new implementation in polyfils?

@jansel We can do this for functions that do not return the `treespec` variable. E.g.:

```python
generator = tree_iter(tree)
leaves    = tree_leaves(tree)
newtree   = tree_map(func, tree)
tree_map_(func, tree)
```

I'd implement new polyfills to ensure behavior consistency between polyfill and C++ for the following functions that return/access the `treespec` variable.

```python
leaves, treespec = tree_flatten(tree)
treespec         = tree_structure(tree)
tree             = tree_unflatten(leaves, treespec)
```

In most cases, the new polyfill is identical to the already existing Python pytree.

**Comment by XuehaiPan** [comment]
Any update? cc @zou3519

**Review by jansel — APPROVED** [review]

**Comment by atalman** [comment]
HI @XuehaiPan looks like its failing on: https://github.com/pytorch/pytorch/blob/main/test/dynamo/test_trace_rules.py#L328

**Comment by XuehaiPan** [comment]
> HI @XuehaiPan looks like its failing on: [`main`/test/dynamo/test_trace_rules.py#L328](https://github.com/pytorch/pytorch/blob/main/test/dynamo/test_trace_rules.py#L328)

Updated.

**Comment by XuehaiPan** [comment]
@jansel @zou3519 Could you take a look at this and the follow-up PRs?

**Comment by weifengpy** [comment]
I am seeing error in latest trunk, likely due to this PR. Is it possible to take a 2nd look if this breaks the trunk?

error about `is_dict_insertion_ordered`:
```
ERROR test/distributed/_tensor/test_math_ops.py - ValueError: Duplicate dispatch rule for <built-in method is_dict_insertion_ordered of PyCapsule object at 0x7f343d2b2910>: already registered in VariableBuilder's id dispatch map
```

how to repro:
```
pytest test/distributed/_tensor/test_math_ops.py -s -k test_softmax_fwd

Traceback (most recent call last):
  File "/home/local/miniconda3/envs/torchtitan/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/home/local/miniconda3/envs/torchtitan/lib/python3.10/site-packages/_pytest/runner.py", line 372, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/home/local/miniconda3/envs/torchtitan/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/home/local/miniconda3/envs/torchtitan/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/home/local/miniconda3/envs/torchtitan/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/home/local/miniconda3/envs/torchtitan/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/home/local/miniconda3/envs/torchtitan/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/home/local/miniconda3/envs/torchtitan/lib/python3.10/site-packages/_pytest/pathlib.py", line 565, in import_path
    importlib.import_module(module_name)
  File "/home/local/miniconda3/envs/torchtitan/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/users/oss/pytorch/test/distributed/_tensor/test_math_ops.py", line 25, in <module>
    from torch.testing._internal.common_utils import run_tests
  File "/data/users/oss/pytorch/torch/testing/_internal/common_utils.py", line 1814, in <module>
    condition=torch._dynamo.config.inline_inbuilt_nn_modules,
  File "/data/users/oss/pytorch/torch/__init__.py", line 2647, in __getattr__
    return importlib.import_module(f".{name}", __name__)
  File "/home/local/miniconda3/envs/torchtitan/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data/users/oss/pytorch/torch/_dynamo/__init__.py", line 42, in <module>
    from .polyfills import loader as _  # usort: skip # noqa: F401
  File "/data/users/oss/pytorch/torch/_dynamo/polyfills/loader.py", line 24, in <module>
    POLYFILLED_MODULES: Tuple["ModuleType", ...] = tuple(
  File "/data/users/oss/pytorch/torch/_dynamo/polyfills/loader.py", line 25, in <genexpr>
    importlib.import_module(f".{submodule}", package=polyfills.__name__)
  File "/home/local/miniconda3/envs/torchtitan/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data/users/oss/pytorch/torch/_dynamo/polyfills/pytree.py", line 31, in <module>
    def _(*args: Any, **kwargs: Any) -> bool:
  File "/data/users/oss/pytorch/torch/_dynamo/decorators.py", line 356, in wrapper
    raise ValueError(
ValueError: Duplicate dispatch rule for <built-in method is_dict_insertion_ordered of PyCapsule object at 0x7f343d2b2910>: already registered in VariableBuilder's id dispatch map
=========================================================================================================== short test summary info ===========================================================================================================
ERROR test/distributed/_tensor/test_math_ops.py - ValueError: Duplicate dispatch rule for <built-in method is_dict_insertion_ordered of PyCapsule object at 0x7f343d2b2910>: already registered in VariableBuilder's id dispatch map
```

**Pull request closed without merging**
