### PR TITLE
Have __sizeof__ account for size of stored elements

### PR DESCRIPTION
**Pull request by lantiga**
This PR addresses #3655.

`__sizeof__` now accounts for the size of data in `Tensor` as well as `Storage`:
```
s0 = torch.randn(0).__sizeof__()           # 80L
s10 = torch.randn(10).__sizeof__()        # 120L
s100 = torch.randn(100).__sizeof__()   # 480L
(s100 - s0) / (s10 - s0)                          # 10

s0 = torch.randn(0).storage().__sizeof__()           # 40L
s10 = torch.randn(10).storage().__sizeof__()        # 80L
s100 = torch.randn(100).storage().__sizeof__()   # 440L
(s100 - s0) / (s10 - s0)                                          # 10
```

Note that the reported size is indicative: it only accounts for the size of the data and disregards other attributes (e.g. `Size`).

### CODE REVIEW

**Comment by colesbury** [comment]
This includes the size of the Storage in the tensor, but the documentation for sizeof says:

```
Only the memory consumption directly attributed to the object is accounted for, not the memory consumption of objects it refers to.
```

That means that the recipe for computing memory referenced in the Python documentation will overstate the memory usage:

https://code.activestate.com/recipes/577504/

I don't think this will change the code snippet from the original PyTorch discussion either:
https://discuss.pytorch.org/t/data-type-when-change-tensor-array-to-numpy-array/9786
```
test0 = torch.rand(100, 100)
test1 = test0.numpy()
print(sys.getsizeof(test1))
```

`test1` is a NumPy array. It's size is reported as 112 because it's a view and `test1.base` is intentionally not included in `__sizeof__`.

**Comment by colesbury** [comment]
On the other hand, perhaps including the `Storage` size in the `Tensor` is useful enough for debugging that it's not worth trying to strictly adhere to Python documentation spec.

**Comment by lantiga** [comment]
Thank you @colesbury. I'm good with sticking to the specification. 
However storage is so seldom used explicitly in PyTorch, contrarily to Lua Torch, that it feels like the analogous of the `data` buffer in NumPy.

**Comment by lantiga** [comment]
Done

**Review by apaszke — APPROVED** [review]

**Pull request merged**
