### PR TITLE
Compare Triton vs. CUTLASS 3xTF32 precision

### PR DESCRIPTION
**Pull request by alexsamardzic**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #133090

### CODE REVIEW

**Comment by alexsamardzic** [comment]
(cc @amjames)

This PR is to compare Triton vs. CUTLASS precision for 3xTF32 MM implementation, and eventually make some related changes.  The first stab is `check-prec-3xtf32.py` script, included for now in the PR, for comparing the precision.  In order to do head-to-head comparison, from within PyTorch source tree, the script is organized as follows:

1. For CUTLASS, the CUTLASS Python interface (that is under `third_party/cutlass/python/cutlass` in the PyTorch source tree) is used, to generate, compile and run 3xTF32 CUTLASS kernel.  To properly import `cutlass` library, that represents mentioned Python interface, the script should be run as follows (form top-level directory of PyTorch source tree local copy): `PYTHONPATH=third_party/cutlass/python python check-prec-3xtf32.py`.  The CUTLASS Python interface is caching info about compiled kernels in `compiled_cache.db`, stored in the current directory.  This file is Sqlite3 database, so corresponding CUTLASS GEMM template instantiation, and other information about the compiled kernel, could be acquired through opening this database through Sqlite3 command line interface, and issuing SQL command `select * from compiled_operations;`.
2. For Triton, the code from Triton [MM tutorial](https://triton-lang.org/main/getting-started/tutorials/03-matrix-multiplication.html) is copied, with auto-tuning removed, and `input_precision="tf32x3"` added to `tl.dot()` call, that should activate 3xTF32 in Triton.  The block sizes and other config parameters, like the number of warps per block, are set to match what is used by CUTLASS, as read from compile cache (as described above).

The results produced by NumPy are used as a reference, for comparing precision.  The run of the script above, as is, shows that CUTLASS provides more precise results than Triton, here is the script output:
```
    dims  CUTLASS loss  Triton loss
0    256  6.400885e-11     0.000011
1    384  1.007811e-10     0.000017
2    512  1.452675e-10     0.000022
3    640  1.879968e-10     0.000028
4    768  2.109953e-10     0.000033
5    896  2.606520e-10     0.000039
6   1024  3.007491e-10     0.000044
7   1152  3.454600e-10     0.000050
8   1280  3.979735e-10     0.000055
9   1408  4.197015e-10     0.000061
10  1536  4.798573e-10     0.000067
11  1664  5.160879e-10     0.000072
12  1792  5.618200e-10     0.000077
13  1920  6.053382e-10     0.000083
14  2048  6.386631e-10     0.000088
15  2176  7.015808e-10     0.000094
16  2304  7.377219e-10     0.000100
17  2432  7.893334e-10     0.000105
18  2560  8.343605e-10     0.000111
19  2688  8.766834e-10     0.000117
20  2816  9.321028e-10     0.000123
21  2944  9.697767e-10     0.000128
22  3072  1.012939e-09     0.000134
23  3200  1.070393e-09     0.000140
24  3328  1.116303e-09     0.000146
25  3456  1.173347e-09     0.000152
26  3584  1.213757e-09     0.000158
27  3712  1.258777e-09     0.000165
28  3840  1.325544e-09     0.000171
29  3968  1.364243e-09     0.000177
```

It is [mentioned](https://github.com/triton-lang/triton/pull/3234#issue-2159510430) for the Triton 3xTF32 PR that the rounding used is different than in CUTLASS, so after re-checking results produced by the script, this is going to be investigated further...

**Comment by amjames** [comment]
Changed this over to a draft as not to make noise while experimenting. 

@alexsamardzic the initial results here make me think that modifying the rounding method used in triton's implementation to match CUTLASS might be needed. It might be a good idea to make two changes to the accuracy check script: 

1) Make the baseline eager mode `torch.mm` CUBLAS with tf32 disabled. That will give us a better idea if/when `input_precision=tf32x3` can be used by with inductor templates.
2) Including a column for `input_precision=ieee` would also be helpful as that option should match the behavior of what is currently used we can get a sense for what loss is acceptable.  

Did you have to use a source build of triton to get access to that feature? With the churn around release time I can't remember if it was included in the release base commit. I know we did not cherry pick the feature though.

**Comment by alexsamardzic** [comment]
An update pushed. (BTW, what was the way to disable CI, as for this PR it won't be needed for while?)

Here is the output:
```
    dims  CUTLASS 3xTF32 loss  Triton 3xTF32 loss  Triton IEEE loss
0    256         5.250094e-11            0.000011          0.000011
1    384         8.871717e-11            0.000017          0.000017
2    512         1.252155e-10            0.000022          0.000022
3    640         1.640167e-10            0.000027          0.000027
4    768         2.073220e-10            0.000033          0.000033
5    896         2.507618e-10            0.000038          0.000038
6   1024         2.854130e-10            0.000044          0.000044
7   1152         3.543335e-10            0.000050          0.000050
8   1280         8.008746e-10            0.000056          0.000055
9   1408         4.630717e-10            0.000061          0.000061
10  1536         5.227396e-10            0.000066          0.000066
11  1664         5.856923e-10            0.000072          0.000071
12  1792         6.526216e-10            0.000077          0.000077
13  1920         1.015859e-09            0.000083          0.000083
14  2048         1.800478e-09            0.000089          0.000088
15  2176         1.999618e-09            0.000094          0.000093
16  2304         2.219712e-09            0.000100          0.000099
17  2432         2.445643e-09            0.000105          0.000104
18  2560         2.678626e-09            0.000111          0.000110
19  2688         2.930960e-09            0.000117          0.000115
20  2816         3.184238e-09            0.000123          0.000121
21  2944         3.453182e-09            0.000129          0.000126
22  3072         3.729608e-09            0.000134          0.000132
23  3200         4.018395e-09            0.000140          0.000137
24  3328         4.324384e-09            0.000146          0.000143
25  3456         4.637772e-09            0.000152          0.000149
26  3584         4.960742e-09            0.000158          0.000154
27  3712         5.299885e-09            0.000164          0.000160
28  3840         5.654739e-09            0.000171          0.000166
29  3968         5.999949e-09            0.000177          0.000171
```

There are several things to investigate further here: Triton "ieee" precision seems to be just slightly more precise than "tf32x3", while 3xTF32 in CUTLASS version just seems "too precise".  I'm looking further into this...

**Comment by amjames** [comment]
The precision numbers here do raise eyebrows. Curious if `input_precision=ieee` and `allow_tf32=False` actually do produce the same results my read of the docs suggests they are aliases, but these results seem to suggest that is not the case. 

> BTW, what was the way to disable CI, as for this PR it won't be needed for while?

I don't know if there is one, probably best to just avoid pushing more often than needed until CI becomes useful.

**Comment by alexsamardzic** [comment]
Fixed bug in the testing script that was causing Triton kernels to produce results with seemingly very low precision.  Triton 3xTF32 implementation is still consistently being less precise than the CUTLASS version.  Looking further into this.

**Comment by alexsamardzic** [comment]
After some additional examination (matching Triton and CUTLASS rounding modes, verifying that small-big, big-small and big-big TF32 dot products match in this case, and finally comparing PTX generated from Triton and CUTLASS code), the conclusion is that CUTLASS generates PTX code that is performing additions of individual TF32 dot products on the regular CUDA cores, while Triton is doing these additions of tensor cores.  Because of more appropriate rounding, CUTLASS results get closer to the reference.  If following patch applied to Triton, it would bring it to the same ballpark as CUTLASS (and cuBLAS) regarding the precision (note that applying `f32ToTF32` to `aSmall` and `bSmall` is not critical here):
```
diff --git a/lib/Dialect/TritonGPU/Transforms/F32DotTC.cpp b/lib/Dialect/TritonGPU/Transforms/F32DotTC.cpp
index f701634d..cdc6a5b6 100644
--- a/lib/Dialect/TritonGPU/Transforms/F32DotTC.cpp
+++ b/lib/Dialect/TritonGPU/Transforms/F32DotTC.cpp
@@ -45,6 +45,15 @@ public:f32ToTF32(
                                           ArrayRef<Value>{value})
           .getResult()[0];
     };
+    auto zero_like = [&](Value c) -> Value {
+      return rewriter.create<SplatOp>(
+          dotOp->getLoc(), c.getType(),
+          rewriter.create<arith::ConstantOp>(dotOp->getLoc(),
+                                             rewriter.getF32FloatAttr(0)));
+    };
+    auto add = [&](Value a, Value b) -> Value {
+      return rewriter.create<arith::AddFOp>(dotOp.getLoc(), a, b);
+    };
     auto sub = [&](Value a, Value b) -> Value {
       return rewriter.create<arith::SubFOp>(dotOp.getLoc(), a, b);
     };
@@ -55,16 +64,22 @@ public:
     };
 
     auto aBig = f32ToTF32(dotOp.getA());
-    auto aSmall = sub(dotOp.getA(), aBig);
+    auto aSmall = f32ToTF32(sub(dotOp.getA(), aBig));
 
     auto bBig = f32ToTF32(dotOp.getB());
-    auto bSmall = sub(dotOp.getB(), bBig);
+    auto bSmall = f32ToTF32(sub(dotOp.getB(), bBig));
+
+    auto zero = zero_like(dotOp.getC());
+
+    auto dot1 = dot(aSmall, bBig, zero);
+    auto dot2 = dot(aBig, bSmall, zero);
+    auto dot3 = dot(aBig, bBig, zero);
 
-    auto dot1 = dot(aSmall, bBig, dotOp.getC());
-    auto dot2 = dot(aBig, bSmall, dot1);
-    auto dot3 = dot(aBig, bBig, dot2);
+    auto sum1 = add(dot1, dot2);
+    auto sum2 = add(sum1, dot3);
+    auto sum3 = add(sum2, dotOp.getC());
 
-    rewriter.replaceOp(dotOp, dot3);
+    rewriter.replaceOp(dotOp, sum3);
     return success();
   }
 };
```

**Comment by alexsamardzic** [comment]
Closing as the summary of findings is presented [here](https://github.com/triton-lang/triton/issues/4603), and eventual further discussion also belongs there.

**Pull request closed without merging**
