### PR TITLE
Enable simd and loop vectorizer with MSVC

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by peterjc123** [comment]
From the log, it seems that it is a long way to go. https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda10-cudnn7-py3-dev-build/3/consoleText

**Comment by peterjc123** [comment]
The reason codes for vectorization failures: https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/vectorizer-and-parallelizer-messages?view=vs-2019

**Comment by peterjc123** [comment]
The auto-vectorization report for VS 2017: https://gist.github.com/peterjc123/714c40634ceeb9c5a533e8d78b5f24c4.

**Comment by peterjc123** [comment]
Let's enable it first. Fixing the non-vectorized loops could be done later.

**Review by ezyang — APPROVED** [review]

**Comment by peterjc123** [comment]
@ezyang Actually I hope someone that knows/manages the vectorization of TH/THNN may look into these vectorization reports because I'm not sure which ones of those functions should be vectorized and which ones are not.

**Pull request closed without merging**
