### PR TITLE
[pt2] add `SymInt` support for `linalg.pinv`

### PR DESCRIPTION
**Pull request by nkaretnikov**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #102367

### CODE REVIEW

**Review by lezcano — APPROVED** [review]

**Comment by huydhn** [comment]
@nkaretnikov I think some slow tests start failing after this change https://hud.pytorch.org/pytorch/pytorch/commit/3469f100f333a4332ca51cccf81585f4088d06a0 (CPU and ASAN).  Could you help take a look or mark them as XFAIL if the failures are expected?  These tests are considered slow, so they only run periodically with `ciflow/slow`, thus there wasn't any signals in the PR

**Comment by kit1980** [comment]
I've verified that this PR broke the slow tests.
I'm going to revert is so we don't have the tests broken over the long weekend.

**Comment by kit1980** [comment]
Copying the error here:

FAILED [8.8357s] functorch/test_aotdispatch.py::TestEagerFusionOpInfoCPU::test_aot_autograd_exhaustive_linalg_pinv_singular_cpu_float32 - AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 6 (16.7%)
Greatest absolute difference: 1.6927719116210938e-05 at index (0, 0, 0, 1) (up to 1e-05 allowed)
Greatest relative difference: 7.0342543949664105e-06 at index (0, 0, 0, 1) (up to 1.3e-06 allowed)

**Comment by nkaretnikov** [comment]
I guess this might be due to the following. I'll take a closer look shortly.

```
    skip('linalg.pinv', 'singular'),  # likely needs updated tolerance
```

**Comment by lezcano** [comment]
@nkaretnikov can you put up a follow up removing the skips and just bumping the tolerance of this function and the other function that also failed the accuracy tests? Something loose like 1e-5 in both atol and rtol would do it I think

**Pull request closed without merging**
