### PR TITLE
fix forward and backward for norm/renorm with infty norm (fixes #6817)

### LINKED ISSUE #6817: [PyTorch] Infinity norm gives 1
Both `torch.renorm` and `torch.norm` always computes infinity norm as `1` because they actually computes ``norm = (\sum_i x_i^p)^(1/p)` as `\infty^0 = 1``.

relevant post: https://discuss.pytorch.org/t/weird-behavior-in-torch-renorm-for-l-infinity-norms/16731

### PR DESCRIPTION
**Pull request by t-vi**
So here is an implementation of infinity norm for norm and renorm, also doing backwards.
I also added tests against numpy / for the gradient.

Best regards

Thomas

### CODE REVIEW

**Comment by elanmart** [comment]
`numpy` also supports `-inf`, perhaps it would be nice to add it to this PR as well?

**Review by ezyang — APPROVED** [review]
Seems legit.

**Comment by ezyang** [comment]
CI error looks real though.

**Review by apaszke — APPROVED** [review]

**Comment by apaszke** [comment]
Thanks @t-vi!

**Pull request merged**
