### PR TITLE
Removed whitelist references

### LINKED ISSUE #41752: Replace blacklist/whitelist in tools/clang_format_all.py
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `tools/clang_format_all.py`. See issue #41443 for more information.

### PR DESCRIPTION
**Pull request by superkirill**
Removed whitelist and blacklist references
Fixes #41752.

### CODE REVIEW

**Review by suo — APPROVED** [review]
Looks lie there are flake8 errors on this PR, mind fixing them before I merge? Thanks!

**Comment by superkirill** [comment]
@suo

> Looks lie there are flake8 errors on this PR, mind fixing them before I merge? Thanks!

Yes, sure! I'll look into that.

**Comment by SplitInfinity** [comment]
@superkirill 

Looks like some jobs have failed? I think these errors should disappear after a rebase.

**Comment by SplitInfinity** [comment]
Hi @superkirill, do you mind rebasing this? Other than the merge conflicts, this looks good to land.

**Pull request closed without merging**
