### PR TITLE
[CI][dashboard][reland] Collect PT2 cpu perf nightly

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #131560

Summary: Add a workflow similar to inductor-perf-test-nightly.yml but use x86 metal instances for perf measurement. The data processing and dashboard update will come next.

### CODE REVIEW

**Comment by desertfire** [comment]
Reland of https://github.com/pytorch/pytorch/pull/131369 and https://github.com/pytorch/pytorch/pull/131467

**Comment by desertfire** [comment]
Fixed an environment variable setting issue

**Review by huydhn — APPROVED** [review]
LGTM pending inductor test jobs

**Pull request closed without merging**
