### PR TITLE
[C10D] Change PGNCCL logs to prefix [PG {} Rank {}]

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #115807
* #115803
* __->__ #115801
* #115800
* #115798
* #115771

Adds a PG {process group uid} prefix component to logs.

This is helpful in situations where there are multiple processgroups,
and rank information by itself is confusing.  (For example rank0 on PG1
may correspond to rank3 on PG0.  People may assume 'rank0' references
the global (PG0) world, but it may reference a sub-pg.  Prefacing the PG
helps clarify this.

Does NOT change logs from inside WorkNCCL functions, since WorkNCCL
doens't know what PG ID it corresponds to. Will address these logs
separately.

Example:

```
[I ProcessGroupNCCL.cpp:787] [PG 0 Rank 0] ProcessGroupNCCL initialization ...
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @yf225

### CODE REVIEW

**Review by XilunWu — COMMENTED** [review]
Sure, using PG id sounds good to me.

**Review by fduwjj — APPROVED** [review]
Nice, thanks for making the logging better. Do you think we also want to print out PG size in the constructor so that we know which `_uid` refers to which sub-PG?

**Pull request closed without merging**
