### PR TITLE
fix build table for ppc64le

### LINKED ISSUE #39461: pytorch README build table cleanup for ppc64le
## 🐛 Bug
The current top level README.md has a table that lists CI builds and python versions.  The versions are listed as 3.6, 3.7, and 3.8.
The ppc64le builds are listed under the 3.8 column, even though we have been building it on 3.7 for a while.  This happened when the columns were renamed under #35677 (but the ppc64le build links weren't moved to stay under 3.7).

A second related issue with the ppc64le links in this table is that the GPU link points to our nightly CI build titled "pytorch-linux-cuda92-cudnn7-py3-mpi-build-test-gpu".  This is misleading as
we are building with cuda 10.2, not 9.2.  The action I will take here is to remove the cuda version
from the URL link by renaming the actual build job.  However, once I do that, the link URL in the README will be incorrect and thus broken.  So, I will prepare a PR here and submit it, first; I will then rename the job soon after, so that the window of time when the link is wrong will be minimal.

The CPU link is named `pytorch-master-nightly-py3-linux-ppc64le` so I think I'll just add a `-gpu` suffix to the same name to indicate the GPU build.

cc @ezyang @seemethere @malfet

### PR DESCRIPTION
**Pull request by dncliss**
This corrects the build info for ppc64le in the main README.

I am opening this PR before renaming the build job.  (So, the "live" master README has the correct "live" link and the PR does not.)
Immediately after submitting the PR, I will correct the name of the build job.  This will make the new PR link correct, and the current "master" link will briefly appear broken until this PR gets merged.

### CODE REVIEW

**Comment by dncliss** [comment]
PR is submitted for issue #39461.
The build rename has now been made; thus, the existing link name is briefly a broken link until the new version here is merged.  (Not that many people probably click on it often....)

**Comment by dncliss** [comment]
Oh rats, hang on; the "badge" icon needs to be updated too.....

**Comment by dncliss** [comment]
OK -- it's good to go, pending review.

**Comment by dncliss** [comment]
With no change here but a couple README lines, I'm fairly sure that the above `test_optimize_for_mobile` test failures couldn't actually have anything to do with this PR.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
