### PR TITLE
[dynamo] Missing guard source keys for corner case of NNModuleVariabl…

### PR DESCRIPTION
**Pull request by anijain2305**
Potentially fixes - https://fb.workplace.com/groups/1286739428954016/permalink/1319662695661689/

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
This should be relatively simple to write a UT for, I suspect.

**Comment by ezyang** [comment]
Model the unit test off of the existing FSDP Dynamo tests, probably

**Comment by anijain2305** [comment]
I tried to but I am unable to find a case where this could happen. Basically there is a FSDPModuleVariable which has a submodule that is marked specialized NNModuleVariable. This .. can't happen. FSDPModuleVariable is UnspecializedNNModuleVariable, and therefore it just traces the innards of everything it its path, never creating a NNModuleVariable. 

The stack trace in question is weird too - https://www.internalfb.com/phabricator/paste/view/P1565255229. Its coming from export/flatten.py. So, I don't know if this PR is really addressing the root of the problem.

**Pull request closed without merging**
