### PR TITLE
Updating test_jit_cuda_fuser.py with faster print statements

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
Updating `test_jit_cuda_fuser.py` with faster print statements for faster code.

### CODE REVIEW

**Review by jjsjann123 — APPROVED** [review]
LGTM

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
@SmashedFrenzy16 I'm sorry this wasn't merged faster.
I see the file has been changed, if you're willing to resolve the conflicts, I'll make sure this is merged in a timely manner.

**Comment by SmashedFrenzy16** [comment]
@kit1980 I have resolved the conflicts.

**Comment by kit1980** [comment]
> @kit1980 I have resolved the conflicts.

Hm, but now the PR has no changes.
Were the changes already merged by some other PR?

**Pull request closed without merging**
