### PR TITLE
docker: Remove the docker directory

### PR DESCRIPTION
**Pull request by seemethere**
Couldn't see anything from our current CI that actually uses these so
I'm just going to go ahead and remove it.

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 9fe07595:


**None of the build failures appear to be your fault**.

* **1/1** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=b565d9b35696259f9ab7d5dfd3814c82d40aaa84&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base b565d9b3 since Jan 29
  <details>
  <summary>
  Please rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch origin viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=9fe0759560665c41a86550f83848f1d46128e165).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [pytorch_linux_backward_compatibility_check_test](https://dr.pytorch.org/build-details.html?build_id=92894550) from Jan 29



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by ezyang — CHANGES_REQUESTED** [review]
The Docker is not tested in CI but it is certainly used. cc @ngimel

**Comment by seemethere** [comment]
@ezyang I refactored the official docker image process in https://github.com/pytorch/pytorch/pull/32515, this is the follow up PR to remove the files I made obsolete.

**Comment by ngimel** [comment]
Removing the docker directory is ok, pytorch docker functionality is now expanded and improved in the Dockerfile in the root. But I'd suggest to put "how to build" instructions that are currently in #32515 commit message into the root README.md

**Comment by seemethere** [comment]
@ngimel have update the PR to include a commit for the README.md as well to update the Docker section to highlight the new build process more and describe what's actually included in the image.

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Approving parts related to removing docker/pytorch, but would wait for someone who knows more than me to comment on docker/caffe2.

**Comment by ezyang** [comment]
docker/caffe2/jenkins are the docker images that were historically used for Caffe2 CI. If we've killed all those jobs (don't we still have the onnx job?) that directory can be removed.

I took a quick look at the other Docker files top level and they seem to be hopelessly out of date. Deleting them SGTM.

**Pull request closed without merging**
