### PR TITLE
[BE][Easy] apply autofix for ruff rule unnecessary-literal-set (C405) and unnecessary-map (C417)

### PR DESCRIPTION
**Pull request by XuehaiPan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #130207
* #130206
* #130205
* #130204
* #130203
* #130202
* #130199
* __->__ #130198

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by XuehaiPan** [comment]
ruff rule unnecessary-comprehension-in-call (C419) breaks dynamo. Remove it from the commit.

**Pull request closed without merging**
