### PR TITLE
[Dynamo][Megatron] Supports os.environ.get

### PR DESCRIPTION
**Pull request by yanboliang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #132085

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by Skylion007 — DISMISSED** [review]

**Review by williamwen42 — APPROVED** [review]

**Review by mlazos — CHANGES_REQUESTED** [review]
Sorry to block, but shouldn't we introduce guards on the environment?

Edit for clarity: I think we should introduce guards on the _value_ accessed

**Comment by yanboliang** [comment]
@mlazos Which guards are you referring to, I think there are guards for both ```os``` and ```os.environ```, so we guarantee re-compile if they are changed. This are the guards generated from one simple example:
```
TREE_GUARD_MANAGER:
+- RootGuardManager
| +- DEFAULT_DEVICE: utils_device.CURRENT_DEVICE == None                           # _dynamo/output_graph.py:463 in init_ambient_guards
| +- GLOBAL_STATE: ___check_global_state()
| +- GuardManager: source=L['x'], accessed_by=DictGetItemGuardAccessor(x)
| | +- TENSOR_MATCH: check_tensor(L['x'], Tensor, DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), torch.float32, device=None, requires_grad=False, size=[2, 3], stride=[3, 1])  # return x - 1  # ata/users/ybliang/debug/debug8.py:10 in fn
| | +- NO_HASATTR: hasattr(L['x'], '_dynamo_dynamic_indices') == False           # return x - 1  # ata/users/ybliang/debug/debug8.py:10 in fn
| +- GuardManager: source=G, accessed_by=GlobalsGuardAccessor
| | +- GuardManager: source=G['os'], accessed_by=DictGetItemGuardAccessor(os)
| | | +- ID_MATCH: ___check_obj_id(G['os'], 140143204011200)                     # if os.environ.get('CUDA_DEVICE_MAX_CONNECTIONS') != "1":  # ata/users/ybliang/debug/debug8.py:7 in fn
| | | +- GuardManager: source=G['os'].environ, accessed_by=GetAttrGuardAccessor(environ)
| | | | +- TYPE_MATCH: ___check_type_id(G['os'].environ, 8062704)                    # if os.environ.get('CUDA_DEVICE_MAX_CONNECTIONS') != "1":  # ata/users/ybliang/debug/debug8.py:7 in fn
```

**Comment by mlazos** [comment]
> @mlazos Which guards are you referring to, I think there are guards for both `os` and `os.environ`, so we guarantee re-compile if they are changed. This are the guards generated from one simple example:
> 
> ```
> TREE_GUARD_MANAGER:
> +- RootGuardManager
> | +- DEFAULT_DEVICE: utils_device.CURRENT_DEVICE == None                           # _dynamo/output_graph.py:463 in init_ambient_guards
> | +- GLOBAL_STATE: ___check_global_state()
> | +- GuardManager: source=L['x'], accessed_by=DictGetItemGuardAccessor(x)
> | | +- TENSOR_MATCH: check_tensor(L['x'], Tensor, DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), torch.float32, device=None, requires_grad=False, size=[2, 3], stride=[3, 1])  # return x - 1  # ata/users/ybliang/debug/debug8.py:10 in fn
> | | +- NO_HASATTR: hasattr(L['x'], '_dynamo_dynamic_indices') == False           # return x - 1  # ata/users/ybliang/debug/debug8.py:10 in fn
> | +- GuardManager: source=G, accessed_by=GlobalsGuardAccessor
> | | +- GuardManager: source=G['os'], accessed_by=DictGetItemGuardAccessor(os)
> | | | +- ID_MATCH: ___check_obj_id(G['os'], 140143204011200)                     # if os.environ.get('CUDA_DEVICE_MAX_CONNECTIONS') != "1":  # ata/users/ybliang/debug/debug8.py:7 in fn
> | | | +- GuardManager: source=G['os'].environ, accessed_by=GetAttrGuardAccessor(environ)
> | | | | +- TYPE_MATCH: ___check_type_id(G['os'].environ, 8062704)                    # if os.environ.get('CUDA_DEVICE_MAX_CONNECTIONS') != "1":  # ata/users/ybliang/debug/debug8.py:7 in fn
> ```

It's only guarding on the type id right? it should also guard on the value

**Comment by mlazos** [comment]
Hmm at a higher level though, shouldn't we just treat `os.environ` like any other `dict`?

**Review by anijain2305 — APPROVED** [review]

**Review by anijain2305 — CHANGES_REQUESTED** [review]
Actually, @mlazos is right. `os.environ` derives from MutableMapping, and therefore `get` is just directly looking at the underlying dict.

```
>>> isinstance(os.environ, MutableMapping)
True
```

So, maybe a more generic way is to find out where the `.get` is eventually called. And then inline the `__getitem__` method of os.environ

image


This will remove the concern of guards as well.

**Comment by yanboliang** [comment]
> It's only guarding on the type id right? it should also guard on the value

Because ```os``` is guarded on ID, and there is only one ```environ``` variable whose type is ```__Environ``` under os module, so it's equivalent to id match on ```os_environ```. 

> Hmm at a higher level though, shouldn't we just treat os.environ like any other dict?
I was thinking about this at the very beginning, but it seems not a perfect match of dict behavior. ```os.environ``` seems a wrapper of a dict, where there are encode/decode functions which may be implemented by C. One of the ways we can try is to iterate ```os.environ``` to cache the result as a dict, but I'm not sure if this works well for all cases. I think most of the functions of ```os.environ``` can be constant folded, so I proposed this solution.

**Comment by yanboliang** [comment]
> So, maybe a more generic way is to find out where the .get is eventually called. And then inline the __getitem__ method of os.environ

@anijain2305 I think for this case, inline and constant fold has no difference? Because users won't have any tensors inside of the ```__getitem__``` function.

**Comment by mlazos** [comment]
> > So, maybe a more generic way is to find out where the .get is eventually called. And then inline the **getitem** method of os.environ
> 
> @anijain2305 I think for this case, inline and constant fold has no difference? Because users won't have any tensors inside of the `__getitem__` function. BTW, I think my change is for all functions/methods of `os.environ`, some of them may not be inlined due to C implementation.



> > It's only guarding on the type id right? it should also guard on the value
> 
> Because `os` is guarded on ID, and there is only one `environ` variable whose type is `__Environ` under os module, so it's equivalent to id match on `os_environ`.
> 
> > Hmm at a higher level though, shouldn't we just treat os.environ like any other dict?
> 
> I was thinking about this at the very beginning, but it seems not a perfect match of dict behavior. `os.environ` seems a wrapper of a dict, where there are encode/decode functions which may be implemented by C. One of the ways we can try is to iterate `os.environ` to cache the result as a dict, but I'm not sure if this works well for all cases. I think most of the functions of `os.environ` can be constant folded, so I proposed this solution.

Even though we guard on the id of `os.environ`, the value at a given key could be changed, and we should recompile in that case. I don't believe this code will today.

**Comment by yanboliang** [comment]
> Even though we guard on the id of os.environ, the value at a given key could be changed, and we should recompile in that case. I don't believe this code will today.

Oh, this is right, we should have id_match for this.

**Review by jansel — CHANGES_REQUESTED** [review]
I think we need to add a guard here.  Can you add a test where you change the env var and call the function again.

**Comment by yanboliang** [comment]
After thinking about this more carefully, I found we should have a dedicated variable for ```os.environ```:
* ```os.environ``` is similar to dict, but not exact dict, ```type(os.environ)``` returns ```os._Environ``` rather than ```dict```.
* We should add guards properly, since we only care about the elements used in the compiled region, so we should only add guards to these elements rather than aggressively adding guards like for ```dict```.

Please check my new implementation at #132123

**Pull request closed without merging**
