### PR TITLE
[CUBLAS][CUDA GRAPHS] (re-re-re-open of #83461) Explicitly set the workspace for cuBLAS handles

### PR DESCRIPTION
**Pull request by eqy**
Based on discussion with @xuzhao9 it's suspected that the observed leak in `torchbenchmark` is expected (with a planned fix), so I'm reopening the PR to see if reducing the number of parallel tests from 3 to 2 would also fix the OOM.

CC @ptrblck @huydhn @ngimel

### CODE REVIEW

**Comment by weiwangmeta** [comment]
Curious why do we still have the @skipCUDAMemoryLeakCheckIf(True)
as found in 
https://github.com/pytorch/pytorch/pull/86167/files#diff-893b1eea27352f336f4cd832919e48d721e4e90186e63400b8596db6b82e7450R3241
cc @seemethere

**Comment by eqy** [comment]
> Curious why do we still have the @skipCUDAMemoryLeakCheckIf(True) as found in https://github.com/pytorch/pytorch/pull/86167/files#diff-893b1eea27352f336f4cd832919e48d721e4e90186e63400b8596db6b82e7450R3241 cc @seemethere

Good catch, this was originally removed in a follow up PR but I forgot to include it in the original one after it was reverted.

**Comment by eqy** [comment]
Closing and re-opening (again) in hopes of working around failed CLA check.

**Pull request closed without merging**
