### PR TITLE
[doc] clarify the range of sampled rv for torch.tensor.exponential_

### LINKED ISSUE #113428: [doc] clarify the range of sampled rv for torch.tensor.exponential_
### 📚 The doc issue

Range of sampled random variable needs to be clarified for torch.tensor.exponential_ whose supported interval is (0, inf) is different from [0, inf] of exponential distribution.

Background: https://github.com/pytorch/pytorch/pull/37984#discussion_r1059527457, https://github.com/pytorch/pytorch/issues/48841#issuecomment-1530439039, https://github.com/pytorch/pytorch/pull/91673#discussion_r1069955813

cc @fritzo @neerajprad @alicanb @nikitaved @svekars @carljparker

Implemented by https://github.com/pytorch/pytorch/pull/113195

### Suggest a potential alternative/fix

_No response_

### PR DESCRIPTION
**Pull request by min-jean-cho**
Fixes https://github.com/pytorch/pytorch/issues/113428.

Range of sampled random variable needs to be clarified for `torch.tensor.exponential_` whose supported interval is (0, inf) is different from [0, inf] of exponential distribution.

Background: https://github.com/pytorch/pytorch/pull/37984#discussion_r1059527457, https://github.com/pytorch/pytorch/issues/48841#issuecomment-1530439039, https://github.com/pytorch/pytorch/pull/91673#discussion_r1069955813

cc @svekars @carljparker

### CODE REVIEW

**Comment by svekars** [comment]
Can you please link the issue you are fixing?

**Comment by kit1980** [comment]
@min-jean-cho Please fix Line too long.

**Review by albanD — APPROVED** [review]
The change sounds good but please double check the rendering and fix the lint!

**Comment by min-jean-cho** [comment]
Thanks! Checked rendering looks good, fixed lint.

**Pull request closed without merging**
