### PR TITLE
Make Openxla dynamo backend take boxed input

### LINKED ISSUE #5454: Openxla Dynamo backend throw a warning message about boxed argument
## 🐛 Bug

currently with the new `openxla` backend it will throw a 
```
/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py:1511: UserWarning: Your compiler for AOTAutograd is returning a function that doesn't take boxed arguments. Please wrap it with functorch.compile.make_boxed_func or handle the boxed arguments yourself. See https://github.com/pytorch/pytorch/pull/83137#issuecomment-1211320670 for rationale.
```

warning.

### PR DESCRIPTION
**Pull request by JackCaoG**
Fixes https://github.com/pytorch/xla/issues/5454

Also adding the inference(non-aot) backend back since we see a speed regression when using the aot-backend compared to the non-aot openxla backend. It is being tracked in https://github.com/pytorch/xla/issues/5430

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

### CODE REVIEW

**Comment by JackCaoG** [comment]
hmm.. I don't think test failure is related to my change..

**Review by shunting314 — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by JackCaoG** [comment]
a bunch of error are related to 
```
+ add-apt-repository ppa:ubuntu-toolchain-r/test
gpg: error running '/usr/bin/gpg-agent': probably not installed
```
I don't think this change should break any xla side stuff, tests are all in pytorch/xla. @jansel do you mind if I do a merge -f(not sure I have the right access to do that)

**Comment by JackCaoG** [comment]
Let me rebase and give it another try

**Pull request closed without merging**
