### PR TITLE
[ONNX] Allow opset 21 for ONNXRuntime==1.18 compatibility (#127167)

### LINKED ISSUE #127167: [feature request]: Update max onnx opset to 21 for onnxruntime==1.18 compatability
## Description
[Onnxruntime==1.18 supports onnx opset 21](https://onnxruntime.ai/docs/reference/compatibility.html).

Pytorch currently does not support conversion to onnx opset 21.

## Proposed implementation
The change seems simple:
Just update the `ONNX_MAX_OPSET` constant from [/torch/onnx/_constants.py](https://github.com/pytorch/pytorch/blob/ba3b05fdf37ddbc3c301294d6a560a816335e717/torch/onnx/_constants.py#L7).

```
"""Constant values used in ONNX."""

ONNX_ARCHIVE_MODEL_PROTO_NAME = "__MODEL_PROTO"

ONNX_BASE_OPSET = 9
ONNX_MIN_OPSET = 7
ONNX_MAX_OPSET = 21
```

**Limitations:**
Using constants shifts the responsibility of updating constants to `pytorch`. Is there an alternative way of detecting that an `OPSET` is not supported without maintenance?

## Workarounds
Currently, the way to workaround this issue is to use some additional code after exporting an onnx file from pytorch:

```
import onnx

opset=21
upgradedModel = onnx.version_converter.convert_version(modelFromTorch, opset)
onnx.save(upgradedModel, modelPath)
```

### PR DESCRIPTION
**Pull request by MengLinMaker**
Note: these constants would need to be updated again once newer opsets are supported.

One workaround is to use the `onnx` python package to upgrade opset versions:
```
import onnx

opset=21
upgradedModel = onnx.version_converter.convert_version(modelFromTorch, opset)
onnx.save(upgradedModel, modelPath)
```

Fixes #127167

Previous PR for supporting upgraded opset as source of inspiration: #118828

### CODE REVIEW

**Comment by MengLinMaker** [comment]
Ok. Maybe this isn't the fix to the issue.
I think `torch.onnx.symbolic_opset21` will need to be implemented.

**Comment by justinchuby** [comment]
There is a constant in one of the cpp files that needs to be updated too. Could you check?

**Comment by justinchuby** [comment]
https://github.com/pytorch/pytorch/blob/main/torch/csrc/jit/serialization/export.cpp here

**Comment by MengLinMaker** [comment]
https://github.com/pytorch/pytorch/blob/26aea277f7f5adf16d5dc0cc7371535b753fd010/torch/csrc/jit/serialization/export.cpp#L94

**Comment by justinchuby** [comment]
Please also add to the kOpsetVersionToIRVersion entry. IR version for opset21 is `10`.

**Comment by MengLinMaker** [comment]
Yep, according to: https://github.com/onnx/onnx/blob/main/docs/Versioning.md#released-versions

**Pull request closed without merging**
