### PR TITLE
benchmark: higher tolerance for RobertaForQuestionAnswering

### PR DESCRIPTION
**Pull request by blzheng**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #107376
* #107375

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Review by kit1980 — COMMENTED** [review]
@pytorchbot merge

**Review by kit1980 — COMMENTED** [review]
@pytorchbot merge

**Review by kit1980 — APPROVED** [review]
@pytorchbot merge

**Review by XiaobingSuper — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
