### PR TITLE
[export] Add device and dtype fields to assert_tensor_metadata

### PR DESCRIPTION
**Pull request by angelayi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #141285
* #141072
* __->__ #141071

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv

Differential Revision: [D66321128](https://our.internmc.facebook.com/intern/diff/D66321128)

### CODE REVIEW

**Comment by yushangdi** [comment]
LGTM. Maybe also add tests in `test/test_comparison_utils.py`?

**Review by yushangdi — APPROVED** [review]
LGTM

**Comment by angelayi** [comment]
@angelayi has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D66321128).

**Comment by angelayi** [comment]
@angelayi has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D66321128).

**Comment by angelayi** [comment]
@angelayi has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D66321128).

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
