### PR TITLE
fix a typo

### PR DESCRIPTION
**Pull request by Krovatkin**
Fixes #{issue number}

### CODE REVIEW

**Review by eellison — APPROVED** [review]

**Comment by xsacha** [comment]
Although it corrects the behaviour, breaks this test somehow:
https://github.com/pytorch/pytorch/blob/211bac53ef6deefd1e613eb4b341bf5de220badc/test/cpp/jit/test_module_api.cpp#L357

**Review by xsacha — APPROVED** [review]
Fixes the issue properly. Thank you very much. There was about 4 PRs open for this.

**Comment by Krovatkin** [comment]
@xsacha, curious, are you using only freezing or also `optimize_for_inference` ?

**Comment by xsacha** [comment]
> @xsacha, curious, are you using only freezing or also `optimize_for_inference` ?

Trying to do optimize_for_inference in C++.

**Review by eellison — APPROVED** [review]

**Comment by Krovatkin** [comment]
@xsacha that's a great data point. we have been really focusing on freezing from python and scripted modules there seem to have the `training` attr.

**Pull request closed without merging**
