### PR TITLE
[WIP] Update AT_API logic to match CAFFE2_API

### PR DESCRIPTION
**Pull request by orionr**

### CODE REVIEW

**Comment by ezyang** [comment]
```
13:39:25 wrapdim_test.cpp.obj : error LNK2019: unresolved external symbol "private: static struct at::UndefinedTensor at::UndefinedTensor::_singleton" (?_singleton@UndefinedTensor@at@@0U12@A) referenced in function "public: __cdecl at::Tensor::~Tensor(void)" (??1Tensor@at@@QEAA@XZ)
```

**Comment by ezyang** [comment]
There should probably be a test added to ensure that hidden symbols are actually hidden.

**Comment by orionr** [comment]
@ezyang might land a variant of this, but I'm closing this PR.

**Pull request closed without merging**
