### PR TITLE
[READY TO MERGE] Enable tests that use DataLoader with multiple workers on Windows

### PR DESCRIPTION
**Pull request by yf225**

### CODE REVIEW

**Review by apaszke — COMMENTED** [review]
We should still use `TEST_CUDA` in the skips, there's no need to modify all of them. You can just assign `torch.cuda.is_available()` to it where it used to be defined. Also, what's the issue with `common_nn`?

**Comment by yf225** [comment]
We need to loop the Windows CI test multiple times to make sure this won't cause OOM error.

**Comment by ezyang** [comment]
@pytorchbot retest this please

What's the status of this?

**Comment by yf225** [comment]
@ezyang I looped it over 100 times and didn't see any OOM error. I think this should be good to merge.

**Review by ezyang — APPROVED** [review]

**Pull request merged**
