### PR TITLE
Add --jobs 0 for git submodule update

### PR DESCRIPTION
**Pull request by zhouzhuojie**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#61152**

Some related docs about `submodule.fetchJobs`
https://git-scm.com/docs/git-config#Documentation/git-config.txt-submodulefetchJobs

```
time git submodule update --init --recursive 
________________________________________________________
Executed in  243.20 secs    fish           external
   usr time   49.64 secs  213.00 micros   49.64 secs
   sys time   29.27 secs  795.00 micros   29.27 secs
```

```
time git submodule update --init --recursive --jobs 4  
________________________________________________________
Executed in  143.04 secs    fish           external
   usr time   51.06 secs  246.00 micros   51.06 secs
   sys time   30.96 secs  742.00 micros   30.96 secs
```

```
time git submodule update --init --recursive --jobs 8 
________________________________________________________
Executed in  124.64 secs    fish           external
   usr time   51.76 secs  264.00 micros   51.76 secs
   sys time   30.49 secs  739.00 micros   30.49 secs

```

```
time git submodule update --init --recursive --jobs 0 # use all online cpus
 ________________________________________________________
Executed in  129.75 secs    fish           external
   usr time   51.64 secs  181.00 micros   51.64 secs
   sys time   31.49 secs  781.00 micros   31.49 secs

```

### CODE REVIEW

**Review by driazati — APPROVED** [review]
Looks good (it'd be nice if we could do the same thing for our actions checkout too but it'd require waiting for this or forking our own: https://github.com/actions/checkout/pull/323). Looks like support for this [was added in 2016](https://github.blog/2016-06-13-git-2-9-has-been-released/#faster-and-more-flexible-submodules) which is plenty of lead time for us to be requiring it imo.

We could even be more aggressive since submodule updates aren't really CPU blocking, they're probably just yielding a bunch since they're waiting for the network (i'm just guessing here), but maybe we could dial this up to 10 or something?

**Comment by zhouzhuojie** [comment]
> Looks good (it'd be nice if we could do the same thing for our actions checkout too but it'd require waiting for this or forking our own: [actions/checkout#323](https://github.com/actions/checkout/pull/323)). Looks like support for this [was added in 2016](https://github.blog/2016-06-13-git-2-9-has-been-released/#faster-and-more-flexible-submodules) which is plenty of lead time for us to be requiring it imo.
> 
> We could even be more aggressive since submodule updates aren't really CPU blocking, they're probably just yielding a bunch since they're waiting for the network (i'm just guessing here), but maybe we could dial this up to 10 or something?

good point! seems that `--jobs 0` is even better. from their [doc](https://git-scm.com/docs/git-config#Documentation/git-config.txt-submodulefetchJobs)

**Comment by seemethere** [comment]
> Looks good (it'd be nice if we could do the same thing for our actions checkout too but it'd require waiting for this or forking our own: [actions/checkout#323](https://github.com/actions/checkout/pull/323)). Looks like support for this [was added in 2016](https://github.blog/2016-06-13-git-2-9-has-been-released/#faster-and-more-flexible-submodules) which is plenty of lead time for us to be requiring it imo.
> 
> We could even be more aggressive since submodule updates aren't really CPU blocking, they're probably just yielding a bunch since they're waiting for the network (i'm just guessing here), but maybe we could dial this up to 10 or something?

If there’s a big performance gain we can just stop pulling submodules using `actions/checkout` and pull them in a separate step

**Comment by zhouzhuojie** [comment]
> > Looks good (it'd be nice if we could do the same thing for our actions checkout too but it'd require waiting for this or forking our own: [actions/checkout#323](https://github.com/actions/checkout/pull/323)). Looks like support for this [was added in 2016](https://github.blog/2016-06-13-git-2-9-has-been-released/#faster-and-more-flexible-submodules) which is plenty of lead time for us to be requiring it imo.
> > We could even be more aggressive since submodule updates aren't really CPU blocking, they're probably just yielding a bunch since they're waiting for the network (i'm just guessing here), but maybe we could dial this up to 10 or something?
> 
> If there’s a big performance gain we can just stop pulling submodules using `actions/checkout` and pull them in a separate step

the action checkout is pretty fast, only 5s

image

**Comment by zhouzhuojie** [comment]
close in favor of #61311

**Pull request closed without merging**
