### PR TITLE
Double resnet50 batch size in benchmark script

### PR DESCRIPTION
**Pull request by bddppq**
The benchmarks are now running on gpu cards with more memory

### CODE REVIEW

**Comment by bddppq** [comment]
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger-test/18087/
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-trigger-test/11093/

**Comment by petrex** [comment]
Is it going to be on benchmark node only?

**Review by houseroad — APPROVED** [review]
looks good.

**Comment by bddppq** [comment]
@petrex The bench script should be only running on our bench node.

**Pull request closed without merging**
