### PR TITLE
Simplify _calculate_fan_in_and_fan_out

### PR DESCRIPTION
**Pull request by nzmora**
The code checking `if dimensions == 2` is not needed
because the case of a 2D tensor (Linear) is already handled
by the statement:
`receptive_field_size = 1`
and this conditional:
`if tensor.dim() > 2:`

### CODE REVIEW

**Review by vishwakftw — COMMENTED** [review]
The permissions of the file seems to be have been changed.

**Review by albanD — APPROVED** [review]
Thanks for the PR !

@nzmora could you rebase on top of master please? It seems that you were on a master that was broken :/

**Comment by nzmora** [comment]
Well, I seem to have messed things up with this rebase attempt.
Let me know if you want a new PR.

**Comment by nzmora** [comment]
It seems like I did something wrong with the rebase, but I'm not sure what.
Let me know if you want a new PR.

**Comment by vishwakftw** [comment]
Can you try `git pull —rebase upstream master` and then `git push -f origin master`?

**Pull request closed without merging**
