### PR TITLE
Fix C++20 build

### PR DESCRIPTION
**Pull request by cyyever**
Currently C++20 fails because of incorrect template initialization order. This PR adjusted the order of theses classes and a constructor to address the issue.

### CODE REVIEW

**Review by albanD — APPROVED** [review]
I'm ok with this kind of fix but if you want to enable c++ 20, I think we should have a clear plan to have CI for it. Otherwise we might spend a lot of time fixing things people break again.

**Comment by cyyever** [comment]
@albanD It is time to test C++20 build in some CI

**Pull request closed without merging**
