### PR TITLE
add new build files to gitignore; test that build does not leave git repo checkout dirty

### PR DESCRIPTION
**Pull request by ssnl**
These appear when I run
```
MACOSX_DEPLOYMENT_TARGET=10.13 CC=clang CXX=clang++ NO_CUDA=1 NO_DISTRIBUTED=1 BUILD_CAFFE2_OPS=0 DEBUG=1 python3 setup.py develop --cmake
```

### CODE REVIEW

**Comment by SsnL** [comment]
Okay these dirs appear to be from https://github.com/pytorch/pytorch/pull/16414

**Comment by ezyang** [comment]
Sorry, I already started the unland of the other patch before I saw this PR.

**Comment by SsnL** [comment]
@ezyang No worries. I can update this PR to include that patch when the unland finishes.

**Comment by ezyang** [comment]
XLA build (master only at the moment) appears to apply a patch to files, making them show up as dirty. Sample failing build: https://circleci.com/gh/pytorch/pytorch/683127?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

CC @ailzhang

**Comment by ailzhang** [comment]
Yea I can make a patch to skip the assert on xla.

**Pull request closed without merging**
