### PR TITLE
[3/3] Update `.pyi` Python stub files and enable `'UFMT'` linter

### PR DESCRIPTION
**Pull request by XuehaiPan**
Changes:

- #95200

1. Recognize `.py.in` and `.pyi.in` files as Python in VS Code for a better development experience.
2. Fix deep setting merge in `tools/vscode_settings.py`.

- #95267

3. Use `Namedtuple` rather than `namedtuple + __annotations__` for `torch.nn.utils.rnn.PackedSequence_`:

    `namedtuple + __annotations__`:

    ```python
    PackedSequence_ = namedtuple('PackedSequence_',
                                 ['data', 'batch_sizes', 'sorted_indices', 'unsorted_indices'])

    # type annotation for PackedSequence_ to make it compatible with TorchScript
    PackedSequence_.__annotations__ = {'data': torch.Tensor, 'batch_sizes': torch.Tensor,
                                       'sorted_indices': Optional[torch.Tensor],
                                       'unsorted_indices': Optional[torch.Tensor]}
    ```

    `Namedtuple`: Python 3.6+

    ```python
    class PackedSequence_(NamedTuple):
        data: torch.Tensor
        batch_sizes: torch.Tensor
        sorted_indices: Optional[torch.Tensor]
        unsorted_indices: Optional[torch.Tensor]
    ```

- => this PR: #95268

4. Sort import statements and remove unnecessary imports in `.pyi`, `.pyi.in` files.
5. Format `.pyi`, `.pyi.in` files and remove unnecessary ellipsis `...` in type stubs.

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
Were these changes generated by a linter?

**Comment by XuehaiPan** [comment]
> Were these changes generated by a linter?

@janeyx99 Yes. I manually removed some unnecessary ellipsis `...` and added/removed some commas. Then run `black` to format the stub files. All these modifications do not change the semantic.

**Comment by janeyx99** [comment]
cc @pytorch/pytorch-dev-infra and @huydhn to review regarding this specific lint change

**Comment by XuehaiPan** [comment]
No CI linters are enabled for `.pyi` files currently. But we enable the lintrunner to run `'UFMT'` for `.pyi` files.

**Comment by huydhn** [comment]
> No CI linters are enabled for `.pyi` files currently. But we enable the lintrunner to run `'UFMT'` for `.pyi` files.

Should this change to cover `*.pyi` file be added into https://github.com/pytorch/pytorch/blob/master/.lintrunner.toml#L825 as part of this PR?

**Review by huydhn — APPROVED** [review]
LGTM!

**Pull request closed without merging**
