### PR TITLE
[Don't merge] fix dynamic size array(vla) build error on msvc v3

### PR DESCRIPTION
**Pull request by xuhancn**
MSVC don't support dynamic array.
Ref: https://stackoverflow.com/questions/56555406/creating-dynamic-sized-array-using-msvc-c-compiler 

We tried to solutions:
1. use std::vector to instead of it in previous PR: https://github.com/pytorch/pytorch/pull/134140, but it changed variable's type and failed at UTs.
2. Use `std::unique_ptr` to instead of it in PR: https://github.com/pytorch/pytorch/pull/134156, @jansel reviewed and give comments:  https://github.com/pytorch/pytorch/pull/134156#pullrequestreview-2253091693. It is make sense, allocation memory maybe make code run slower.

**Changes:**
1. Use fixed size array to instead of VLA.
2. Fixed size should bigger than current top process number, we setup it as 1024. I think CPU core number should not larger than 1024 for long time.
3. Select min of fixed size and max CPU core number as real `max_threads`.
4. Warning once to user, if reserved fixed size smaller than max_threads.

Reproduce UT:
```cmd
pytest test/inductor/test_cpu_repro.py -v -k test_reduction_with_dynamic_threads
```

Error msg:
```cmd
C:/Users/Xuhan/AppData/Local/Temp/tmpncykej5v/a4/ca4534cazplidnf7vopaaxaifqkjiyhxm3h2gsylgztputbaeybx.cpp(13): error C2131: expression did not evaluate to a constant
C:/Users/Xuhan/AppData/Local/Temp/tmpncykej5v/a4/ca4534cazplidnf7vopaaxaifqkjiyhxm3h2gsylgztputbaeybx.cpp(13): note: failure was caused by a read of a variable outside its lifetime
C:/Users/Xuhan/AppData/Local/Temp/tmpncykej5v/a4/ca4534cazplidnf7vopaaxaifqkjiyhxm3h2gsylgztputbaeybx.cpp(13): note: see usage of 'max_threads'
C:/Users/Xuhan/AppData/Local/Temp/tmpncykej5v/a4/ca4534cazplidnf7vopaaxaifqkjiyhxm3h2gsylgztputbaeybx.cpp(16): error C3863: array type 'float [max_threads]' is not assignable
```
Genarated code:
```c++

#include "C:/Users/Xuhan/AppData/Local/Temp/tmpt6mxcjzi/j2/cj22tgrdgh42wbunl7gdptg2lintcziox2kmr7rdbcc6n2njrhgx.h"
extern "C" __declspec(dllexport) void kernel(const float* in_ptr0,
                       const float* in_ptr1,
                       float* out_ptr0,
                       float* out_ptr1)
{
    {
        {
            float tmp_acc0 = 0;
            at::vec::Vectorized<float> tmp_acc0_vec = at::vec::Vectorized<float>(0);
            int max_threads = omp_get_max_threads();
            float tmp_acc0_arr[max_threads];
            for (int tid = 0; tid < max_threads; tid++)
            {
                tmp_acc0_arr[tid] = 0;
            }
            at::vec::Vectorized<float> tmp_acc0_vec_arr[max_threads];
            for (int tid = 0; tid < max_threads; tid++)
            {
                tmp_acc0_vec_arr[tid] = at::vec::Vectorized<float>(0);
            }
            #pragma omp parallel
```

Fixed by fixed size array:
```c++

#include "C:/Users/Xuhan/AppData/Local/Temp/tmp76cgece4/j2/cj22tgrdgh42wbunl7gdptg2lintcziox2kmr7rdbcc6n2njrhgx.h"
extern "C" __declspec(dllexport) void kernel(const float* in_ptr0,
                       const float* in_ptr1,
                       float* out_ptr0,
                       float* out_ptr1)
{
    {
        {
            float tmp_acc0 = 0;
            at::vec::Vectorized<float> tmp_acc0_vec = at::vec::Vectorized<float>(0);
            int max_threads = omp_get_max_threads();
            if (1024 < max_threads)
            {
                TORCH_WARN_ONCE("Reserved fixed_thread_pool_size(1024) is smaller than num_threads: %d, it will limited performance.", max_threads);
            }
            max_threads = std::min(max_threads, 1024);
            float tmp_acc0_arr[1024];
            for (int tid = 0; tid < max_threads; tid++)
            {
                tmp_acc0_arr[tid] = 0;
            }
            at::vec::Vectorized<float> tmp_acc0_vec_arr[1024];
            for (int tid = 0; tid < max_threads; tid++)
            {
                tmp_acc0_vec_arr[tid] = at::vec::Vectorized<float>(0);
            }
            #pragma omp parallel
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by zhuhaozhe** [comment]
Hi, @xuhancn.
From my understand, if `max_thread > 1024`. We should not only warn users but also use a dynamic length array. I guess current codes will be wrong if `max_thread > 1024` since we indeed need a buffer > 1024 for that case.

We might expect something like
```
float* tmp_acc0_arr;
float fix_len_arr[1024];
tmp_acc0_arr = &fix_len_arr[0];
std::vector<float> var_len_arr;
if (max_thread > 1024){
    Warn(xxx);
     var_len_arr.reserve(max_threads);
     init_var_len_arr();
    tmp_acc0_arr = &var_len_arr[0];
}
```

**Comment by xuhancn** [comment]
> ```c++
> max_threads = std::min(max_threads, 1024);
> ```

```c++
max_threads = std::min(max_threads, 1024);
```
Please check the genarated code. We always use the `min` value of fixed size and CPU num.
if `max_thread > 1024`, it will set max_thread to 1024.

**Comment by xuhancn** [comment]
> Hi, @xuhancn. From my understand, if `max_thread > 1024`. We should not only warn users but also use a dynamic length array. I guess current codes will be wrong if `max_thread > 1024` since we indeed need a buffer > 1024 for that case.
> 
> We might expect something like
> 
> ```
> float* tmp_acc0_arr;
> float fix_len_arr[1024];
> tmp_acc0_arr = &fix_len_arr[0];
> std::vector<float> var_len_arr;
> if (max_thread > 1024){
>     Warn(xxx);
>      var_len_arr.reserve(max_threads);
>      init_var_len_arr();
>     tmp_acc0_arr = &var_len_arr[0];
> }
> ```

Hi @zhuhaozhe 
```c++
max_threads = std::min(max_threads, 1024);
```
Please check the genarated code. We always use the `min` value of fixed size and CPU num.
if `max_thread > 1024`, it will set max_thread to 1024.

**Comment by xuhancn** [comment]
@zhuhaozhe I modified fixed size to 4, and did local test. It seems failed.
image

**Pull request closed without merging**
