### PR TITLE
[JIT] Fix return types of inputs/outputs method in Graph

### PR DESCRIPTION
**Pull request by take-cheeze**
The C++ definition return `ArrayRef<Value*>` but in python binding it returns iterator instead: https://github.com/pytorch/pytorch/blob/d04889323e2bc0b7321b76e564292565c88b9a5e/torch/csrc/jit/python/python_ir.cpp#L631

I've had hard time with mypy and there is also fixed version of stubs in pytorch-pfn-extras for my project: https://github.com/pfnet/pytorch-pfn-extras/blob/beeab3f30381fd1ed313bc09d561c567482784a1/stubs/torch/_C/__init__.pyi#L458

### CODE REVIEW

**Comment by bdhirsh** [comment]
@take-cheeze  if you sign the CLA, I can land this change!

**Comment by take-cheeze** [comment]
@bdhirsh Thank you for reviewing! CLA should be signed now

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
