### PR TITLE
Fix the check for can_use_expanded_index_path

### LINKED ISSUE #129093: take_along_dim or gather unstable results on cpu with stride 1
### 🐛 Describe the bug

Hello,

In an experiment, I got wrong results after a gather. the issue seems to come from the strides of the index.
I have reproduced the bug here, the tensor operations does not follow my true data pipeline.
I tried to tweak the tensors to get the same representation as in my original crash.

At the end I have 2 almost equal indices, the gather is OK for the first one but not for the second that has strides of 1.

The test is failing only on cpu, not on cuda.

````Python
import torch

def describe(x):
    return f"dtype: {x.dtype}, shape: {tuple(x.shape)}, stride: {x.stride()}, contiguous: {x.is_contiguous()}, storage offset: {x.storage_offset()}, device: {x.device}"

def check_take_along_dim(x, index):
    a = torch.take_along_dim(x, index, dim=0)
    b = torch.take_along_dim(x, index.contiguous(), dim=0)
    return torch.equal(a, b)
    
def check_gather(x, index):
    a = torch.gather(x, dim=0, index=index)
    b = torch.gather(x, dim=0, index=index.contiguous())
    return torch.equal(a, b)

def contiguous_test(device="cpu"):
    x = torch.randn(10, 100, 4).to(torch.float64).to(device)
    print("x =", describe(x))

    i = torch.randint(10, (100,)).to(device)

    j = i.unsqueeze(0).unsqueeze(2).expand(-1, -1, x.shape[2])
    print("j =", describe(j))

    # always OK
    print("gather j:", "OK" if check_gather(x, j) else "!!KO!!")
    print("take along dim j:", "OK" if check_take_along_dim(x, j) else "!!KO!!")

    k = i.unsqueeze(1).t().unsqueeze(2).expand(-1, -1, x.shape[2])
    print("k =", describe(k))

    # KO on cpu, OK on cuda
    print("gather k:", "OK" if check_gather(x, k) else "!!KO!!")
    print("take along dim k:", "OK" if check_take_along_dim(x, k) else "!!KO!!")
````
results:
````Shell
x = dtype: torch.float64, shape: (10, 100, 4), stride: (400, 4, 1), contiguous: True, storage offset: 0, device: cpu
j = dtype: torch.int64, shape: (1, 100, 4), stride: (100, 1, 0), contiguous: False, storage offset: 0, device: cpu
gather j: OK
take along dim j: OK
k = dtype: torch.int64, shape: (1, 100, 4), stride: (1, 1, 0), contiguous: False, storage offset: 0, device: cpu
gather k: !!KO!!
take along dim k: !!KO!!
````

### Versions

Collecting environment information...
PyTorch version: 2.2.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.10.0-20-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 545.23.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Stepping:                        10
CPU MHz:                         3120.280
CPU max MHz:                     5000.0000
CPU min MHz:                     800.0000
BogoMIPS:                        7999.96
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        1.5 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Vulnerable: No microcode
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d

Versions of relevant libraries:
[pip3] botorch==0.9.5
[pip3] gpytorch==1.11
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] onnx==1.15.0
[pip3] onnxruntime==1.16.3
[pip3] torch==2.2.1+cu121
[pip3] torch_geometric==2.5.0
[pip3] triton==2.2.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### PR DESCRIPTION
**Pull request by CaoE**
Fixes #129093

### CODE REVIEW

**Review by mingfeima — APPROVED** [review]

**Comment by CaoE** [comment]
@cpuhrsch Could you please review this PR ? Thanks.

**Review by cpuhrsch — APPROVED** [review]
LGTM, but seems like this constraints the fast path to less inputs. I assume this doesn't cause a perf regression, because it excludes unsupported inputs.

**Pull request closed without merging**
