### PR TITLE
WIP Remove named tensors

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #82158

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

### CODE REVIEW

**Comment by IvanYashchuk** [comment]
Another draft for removing named tensors: https://github.com/pytorch/pytorch/pull/76093.

**Comment by ezyang** [comment]
whoops, wish I knew about that PR lol

**Comment by crcrpar** [comment]
Is it planned to remove named tensors?
It doesn't seem like the first draft PR will land

**Comment by ezyang** [comment]
Yes, this is still planned; not sure when we'll get around to it though

**Pull request closed without merging**
