### PR TITLE
Move x86 binaries builder to macos-12 to enable MPS build

### PR DESCRIPTION
**Pull request by albanD**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #77662

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Comment by albanD** [comment]
Testing the binaries on Bigsur 11.6.5 leads to a segfault when `import torch`. The current nightly do work just fine on the same machine.

Collect env of the failing machine:
```python
PyTorch version: 1.12.0.dev20220518
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.6.5 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.4 (main, Apr 26 2022, 19:43:24) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-11.6.5-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] torch==1.12.0.dev20220518
[conda] Could not collect
```

**Comment by albanD** [comment]
We can't reproduce this segfault locally. So trying to merge this and see if we can get more info from broader testing on nightly.

**Comment by datumbox** [comment]
We are observing breakages on TorchVision for the macOS builds and suspect this PR might be related. See https://github.com/pytorch/vision/issues/6070

**Comment by pmeier** [comment]
Here is a workflow on GitHub Actions that does nothing more than installing PyTorch and try to import it: https://github.com/pytorch/vision/runs/6555576108. It runs on `macos-latest`, which is [`macOS Big Sur 11 `](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners). Switching to `macos-12` eliminates the error: https://github.com/pytorch/vision/runs/6555658933

Currently all of `torchvision`'s CI infrastructure is based on macos-11 and thus is completely broken.

**Comment by malfet** [comment]
Just to close on this one: crashes were fixed by #78136

**Pull request closed without merging**
