### PR TITLE
Improve TORCH_LOGS settings error msg

### LINKED ISSUE #97244: Should print list of valid log names when invalid name is passed
### 🐛 Describe the bug

```
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/a/pytorch (85112b0d)]$ TORCH_LOGS="aot_autograd,torch.fx.experimental.symbolic_shapes" python mnist.py --epochs 1
Traceback (most recent call last):
  File "/data/users/ezyang/a/pytorch/mnist.py", line 4, in <module>
    import torch
  File "/data/users/ezyang/a/pytorch/torch/__init__.py", line 1645, in <module>
    _logging._init_logs()
  File "/data/users/ezyang/a/pytorch/torch/_logging/_internal.py", line 391, in _init_logs
    _update_log_state_from_env()
  File "/data/users/ezyang/a/pytorch/torch/_logging/_internal.py", line 319, in _update_log_state_from_env
    log_state = _parse_log_settings(log_setting)
  File "/data/users/ezyang/a/pytorch/torch/_logging/_internal.py", line 264, in _parse_log_settings
    raise ValueError(
ValueError: Invalid log settings: aot_autograd,torch.fx.experimental.symbolic_shapes, must be a comma separated list of registerered log or artifact names.
```

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos 

### Versions

master

### PR DESCRIPTION
**Pull request by mlazos**
Lists registered loggable entities if an invalid settings string is passed via TORCH_LOGS
[before](https://gist.github.com/mlazos/91fcbc3d577f874bcb3daea44f8b41f2)
[after](https://gist.github.com/mlazos/815ea9e76aca665602228f960e0eb0d6)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
nit: in your PR description, you should post what this looks like. Also, it might be helpful to carefully distinguish between module names and registered names, since module names won't be on the list. Something like "\n\nTip: Any valid PyTorch module name is also accepted as a log name, even if it is not listed in the list above!"

**Comment by mlazos** [comment]
> nit: in your PR description, you should post what this looks like. Also, it might be helpful to carefully distinguish between module names and registered names, since module names won't be on the list. Something like "\n\nTip: Any valid PyTorch module name is also accepted as a log name, even if it is not listed in the list above!"

Oh I did this in the message already, I'll post what it looks like.

**Review by jansel — APPROVED** [review]

**Comment by ezyang** [comment]
err, what message

**Comment by mlazos** [comment]
> err, what message
in _internal.py:
        f"Invalid log settings: {settings}, must be a comma separated list of fully qualified module names, "
        f"registered log names or registered artifact names.\nCurrently registered names: {entities}"

**Pull request closed without merging**
