### PR TITLE
Create Tensor::options

### PR DESCRIPTION
**Pull request by goldsborough**
`tensor.options()` instead of `TensorOptions(tensor)` makes some code nicer.

@ezyang @colesbury @gchanan

### CODE REVIEW

**Comment by ezyang** [comment]
Are we going to add this to the Python API?

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Also, as of this commit, when should I type `x.options()` versus `x.type()`?

**Comment by goldsborough** [comment]
`x.options()` should always be preferred when something expects `TensorOptions`, since `x.type()` will not have knowledge of device-y things

**Pull request merged**
