### PR TITLE
Stop checking in VmapGeneratedPlumbing.h

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #82319
* __->__ #82236
* #82314

This PR changes VmapGeneratedPlumbing.h to be generated by torchgen. The
output file is ATen/VmapGeneratedPlumbing.h.

Why generate this file inside PyTorch codegen instead of a separate step
in functorch?
- I can't figure out how to get functorch's fbcode target to generate
- functorch's build system will, in the mid-term, be absorbed into
pytorch's build system, so I don't want to do the extra work of adding
a step to the functorch build process.

This PR also autoformats gen_vmap_plumbing to make lintrunner happy.
Aside from the autoformating there were no changes.

Test Plan:
- build pytorch, build functorch

Differential Revision: [D38169914](https://our.internmc.facebook.com/intern/diff/D38169914)

### CODE REVIEW

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38169914).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38169914).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38169914).

**Review by ezyang — APPROVED** [review]

**Review by bdhirsh — APPROVED** [review]

**Comment by zou3519** [comment]
merged in another PR

**Pull request closed without merging**
