### PR TITLE
automatic dynamic unspecialize float

### PR DESCRIPTION
**Pull request by bobrenjc93**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #141647

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by bobrenjc93** [comment]
base: https://github.com/pytorch/pytorch/actions/runs/12043279790
head: https://github.com/pytorch/pytorch/actions/runs/12043282667

**Review by ezyang — APPROVED** [review]

**Comment by bobrenjc93** [comment]
Inference: https://hud.pytorch.org/benchmark/compilers?dashboard=torchinductor&startTime=Wed%2C%2027%20Nov%202024%2015%3A49%3A48%20GMT&stopTime=Thu%2C%2028%20Nov%202024%2015%3A49%3A48%20GMT&granularity=hour&suite=torchbench&mode=inference&dtype=bfloat16&deviceName=cuda%20(a100)&lBranch=gh/bobrenjc93/142/head&lCommit=17e28b692fa0e290a3f6cf03908ba0b72f8db9b1&rBranch=gh/bobrenjc93/142/base&rCommit=345256f66fafc87adf3e2d6ce040f4d37f20402f

Training: https://hud.pytorch.org/benchmark/compilers?dashboard=torchinductor&startTime=Wed%2C%2027%20Nov%202024%2015%3A49%3A48%20GMT&stopTime=Thu%2C%2028%20Nov%202024%2015%3A49%3A48%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&deviceName=cuda%20(a100)&lBranch=gh/bobrenjc93/142/head&lCommit=17e28b692fa0e290a3f6cf03908ba0b72f8db9b1&rBranch=gh/bobrenjc93/142/base&rCommit=a5951b21102b54490c254a113916877644cad0d5

**Comment by bobrenjc93** [comment]
Training looks good, inference looks a tad bit wobbly. I'll rebase and kick off another inference run.

Base: https://github.com/pytorch/pytorch/actions/runs/12072365582
Head: https://github.com/pytorch/pytorch/actions/runs/12072368674

**Comment by bobrenjc93** [comment]
Ah since @jameswu added his one off flag that turns off cache if specialize_float=False AND turned on autograd cache on tests in the same diff (D66556085), it also means I'll need to squash https://github.com/pytorch/pytorch/pull/141521 into this PR before landing.

**Pull request closed without merging**
