### PR TITLE
Replace CUDA 11.1 Linux CI with CUDA 11.2

### PR DESCRIPTION
**Pull request by janeyx99**
Also enables BUILD_SPLIT_CUDA on these builds

### CODE REVIEW

**Comment by janeyx99** [comment]
Closed in favor of #51905 as that's on master and not my own fork

**Comment by Gelassen** [comment]
@janeyx99 , what is the status of this issue? It seems this issue is the only blocker for release 11.2 for linux as it mentioned [here](https://github.com/pytorch/pytorch/issues/50232). If you close this issue does it mean release for linux is ready?

**Comment by janeyx99** [comment]
We closed the issue for the reason mentioned in this [comment](https://github.com/pytorch/pytorch/issues/50232#issuecomment-777703998). This code was actually merged in #51905 but we decided to roll it back.

**Comment by Gelassen** [comment]
Thank you for clarification. The intent behind this ticket was to keep community updated regarding status of release for linux and manage their expectations. As this ticket is closed there is no more source of relevant information about your work. 

Could you please update your [origin ticket](https://github.com/pytorch/pytorch/issues/50232) with release preparation summary?

**Comment by janeyx99** [comment]
> Could you please update your [origin ticket](https://github.com/pytorch/pytorch/issues/50232) with release preparation summary?

I'd like to keep the community updated with our status as best as I can, but I'm not sure what else to add on that tracker that would be more descriptive than the comment I mentioned. I've updated the PR linked for 11.2 CI on linux.

**Pull request closed without merging**
