### PR TITLE
Replace all CHECK_ and DCHECK_ with TORCH_* macros

### LINKED ISSUE #81415: `CHECK_*` macro signatures break downstream pytorch/xla build
### 🐛 Describe the bug

Tensorflow recently upgraded to C++17. PyTorch/XLA is upgrading its TF pin and by extension building its TF dependency with C++17. PyTorch/XLA continues to build its own source code in C++14 to stay consistent with the upstream PyTorch.

It turns out the compiler confuses this [definition](https://github.com/tensorflow/tensorflow/blame/master/tensorflow/core/platform/default/logging.h#L456) of `CHECK_NE` in Tensorflow with that of PyTorch in [c10/util/logging_is_not_google_glog.h](https://github.com/pytorch/pytorch/blob/master/c10/util/logging_is_not_google_glog.h#L139-L145). This leads to the following error. This issue occurs because it is not possible to place macros in a namespace. I get similar errors for `DCHECK_NE`, `CHECK_EQ`, etc. 

```
/sw/pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/service/hlo_module.h: In member function ‘const xla::Shape& xla::HloModule::result_shape() const’:
/sw/pytorch/c10/util/logging_is_not_google_glog.h:141:30: error: ambiguous overload for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘std::nullptr_t’)
  141 |                              << (val1) << " vs. " << (val2) << ") "
      |                              ^
/sw/pytorch/c10/util/logging_is_not_google_glog.h:141:30: note: in definition of macro ‘CHECK_OP’
  141 |                              << (val1) << " vs. " << (val2) << ") "
      |                              ^~
/usr/local/<redact>/sw/pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/service/hlo_module.h:137:5: note: in expansion of macro ‘CHECK_NE’
  137 |     CHECK_NE(nullptr, entry_computation_);
      |     ^~~~~~~~
In file included from /usr/include/c++/11/iostream:39,
                 from /usr/local/google/home/miladmo/sw/pytorch/xla/torch_xla/csrc/debug_util.h:3,
                 from /usr/local/google/home/miladmo/sw/pytorch/xla/torch_xla/csrc/debug_util.cpp:1:
```

To check if the issue partially resolves by changing the `CHECK_*` macro names, I commented out CHECK_NE (only) and renamed CHECK_OP to CHECK_OPS in PyTorch. This was possible because `CHECK_NE` is not used in PT source code. I am happy to see CHECK_NE errors disappear.

**Request**

Previously, this name collision has been a compiler warning in PyTorch/XLA. Now, with the change in C++ compiler version, this has become a blocking error. At the same time, FWIW, I understand [PT migration to C++17](https://github.com/pytorch/pytorch/issues/56055) is not in the immediate term horizon. 

I'd propose to rename these macros to resolve the macro names collision. Wdyt?

CC @wconstab @ezyang @JackCaoG 

### Versions

Collecting environment information...
PyTorch version: 1.12.0a0+git6e292f1
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux rodete (x86_64)
GCC version: (Debian 11.3.0-3) 11.3.0
Clang version: 13.0.1-4
CMake version: version 3.19.6
Libc version: glibc-2.33

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.17.11-1rodete2-amd64-x86_64-with-glibc2.33
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] numpydoc==1.1.0
[pip3] torch==1.12.0a0+gitde18c28
[pip3] torch-xla==1.12
[pip3] torchvision==0.13.0a0+08cc9a7
[conda] blas                      1.0                         mkl
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-include               2022.0.1           h06a4308_117
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.20.3           py39hf144106_0
[conda] numpy-base                1.20.3           py39h74d4b33_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] torch                     1.12.0a0+gitcaa1177          pypi_0    pypi
[conda] torch-xla                 1.12                     pypi_0    pypi
[conda] torchvision               0.13.0a0+08cc9a7          pypi_0    pypi

cc @bdhirsh

### PR DESCRIPTION
**Pull request by wconstab**
Avoid exposing defines that conflict with google logging, since this blocks external usage of libtorch in certain cases.

All the 'interesting' changes should be in these two files, and the rest should just be mechanical changes via sed.
c10/util/logging_is_not_google_glog.h
c10/util/logging_is_google_glog.h

Fixes https://github.com/pytorch/pytorch/issues/81415

cc @miladm @malfet

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by wconstab** [comment]
OSS CI failures seem transient/unrelated:

pull / linux-bionic-cuda11.6-py3.7-gcc7 / test (functorch, 1, 1, linux.4xlarge.nvidia.gpu)
 - this test doesn't seem to have run on most of the master commits between friday and now, and the failure logs look unrelated
 
pull / linux-focal-rocm5.2-py3.7 / build
 - network issue
 
might wait on being able to run internal CI to land if I can, but otherwise looks ready to land.

**Review by miladm — APPROVED** [review]
LGTM. 
Thanks for providing this support @wconstab! My local build of PyTorch/XLA is unblocked by this change (i.e. running into new errors unrelated to these macros - lol).

Reference PyTorch/XLA PR: https://github.com/pytorch/xla/pull/3745

CC @JackCaoG

**Comment by fmassa** [comment]
Hi @wconstab ,

I have the impression that the `DCHECK_*` and `CHECK_*` macros now have the same behavior, which means that `CHECK_*` macros are compiled away in release mode (which was [not the behavior of GLOG](https://github.com/google/glog#check-macros)). Was this intended?

cc @datumbox

**Comment by datumbox** [comment]
+1

This caused issues on some of the tests on TorchVision which used the idiom:
`CHECK_EQ(buffer.size(), fread(buffer.data(), 1, buffer.size(), f));`

You can see additional info at: https://www.internalfb.com/diff/D38383266

**Comment by wconstab** [comment]
> Hi @wconstab ,
> 
> I have the impression that the `DCHECK_*` and `CHECK_*` macros now have the same behavior, which means that `CHECK_*` macros are compiled away in release mode (which was [not the behavior of GLOG](https://github.com/google/glog#check-macros)). Was this intended?
> 
> cc @datumbox

Hey @fmassa, sorry for the trouble.

A bit of background first, which someone may correct me on as I am not familiar with the history or intention behind this.  PyTorch is sometimes built with google log (glog) and sometimes without it.

[logging_is_not_google_glog.h](https://github.com/pytorch/pytorch/blob/master/c10/util/logging_is_not_google_glog.h#L151) defines CHECK macros that are compiled away in release builds. My diff simply renames CHECK_ to TORCH_CHECK here.

[logging_is_google_glog.h](https://github.com/pytorch/pytorch/blob/master/c10/util/logging_is_google_glog.h#L68) defines CHECK_ so that it always runs with or without release builds.  My diff changes the semantics here, making them match `logging_is_not_google_glog` as well as providing the name wrapper to map TORCH_CHECK to CHECK.

So, the question I would have is, going forward do we want to have different behavior for TORCH_CHECK depending on whether we use glog under the hood, or do we want consistent behavior?  I'm missing the context of why the inconsistency was there in the first place- perhaps it was intentional, or perhaps it was an oversight.  cc @ezyang

**Comment by wconstab** [comment]
After chatting with @ezyang I realized that this diff incorrectly set CHECK_ macros to be optimized out in the 'is_glog' file, while in the 'is_not_glog' file only the DCHECK macros get optimized out.

I have opened https://github.com/pytorch/pytorch/pull/83216 to fix this.

Additionally, we were discussing the merits of maintaining TORCH_CHECK_* and TORCH_DCHECK_* macros in the first place, which are implemented as aborts under the hood in contrast with the `TORCH_CHECK` macro defined in `c10/util/Exception.h` which is implemented as an exception.  It seems like it would be better to reimplement TORCH_CHECK_EQ  and friends so they call into TORCH_CHECK and become exceptions instead of aborts.  This would subtly change behavior though.

**Pull request closed without merging**
