### PR TITLE
Update xla.txt

### PR DESCRIPTION
**Pull request by JackCaoG**
XLA CI is currently broken in PyTorch, I think there are 2 reasons causing that
1. There is an offending Pytorch PR https://github.com/pytorch/pytorch/commit/c393b2f1ee9a1c9a367a74df1066311f94f328ba. Han is working on a fix in https://github.com/pytorch/xla/pull/6345
2. Commit that pytorch pin to 2990cb38c17e06d0dbe25437674ca40130d76a8f was not a valid commit. I think this is because we tried to help them to land a breaking pr in https://github.com/pytorch/xla/pull/6307. However I think we did a rebase which vanish that commit. now the CI failed 
```
fatal: reference is not a tree: 2990cb38c17e06d0dbe25437674ca40130d76a8f
585
```
Let me first update the pin to the master so it at least run some test, this way we can discover if there is any additional issue. I will rebase after @qihqi 's fix passed all CI

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by clee2000** [comment]
You're going to get signal in a bit but if you want it earlier I tried updating the pin and got https://hud.pytorch.org/pr/117980

**Comment by JackCaoG** [comment]
Yea I plan to merge https://github.com/pytorch/xla/pull/6351 to disable tests and then update pin again while we fix the errors properlly.

**Comment by JackCaoG** [comment]
ok xla side change is merged, let's see if CI will start passing again.

**Comment by JackCaoG** [comment]
@clee2000 xla test passed, can you take a look at this pr? It should unblock CI.

**Review by clee2000 — APPROVED** [review]

**Pull request closed without merging**
