### PR TITLE
Add new device HPU to test base

### PR DESCRIPTION
**Pull request by jeejakp12**
1. Created a new "TestBase" extending DeviceTypeTestBase for HPU
 2. Define the "device_type" attribute for HPU.
 3. Add logic to this file that appends your base class to
    device_type_test_bases when your device type is available.
 4. Add setUpClass to set the hpu primary device to test.
 5. Add interface to check if hpu is_availble

Signed-off-by: Jeeja KP <jeejakp@habana.ai>

Fixes #{issue number}

### CODE REVIEW

**Comment by mruberry** [comment]
The lint errors are real. This looks generally correct but you don't actually need to add the test base in PyTorch itself. The PyTorch/XLA project, for example, defines their XLA test base here:

https://github.com/pytorch/xla/blob/master/test/pytorch_test_base.py

The instructions for how to get this added as a test base are here:

https://github.com/pytorch/pytorch/blob/7e7be526c9d9179f35084e9cca5b5c5ad5172100/torch/testing/_internal/common_device_type.py#L512

Maintaining their test base in their repo makes it easy for PyTorch/XLA to make updates. Is that a solution that you'd prefer, @jeejakp12?

**Review by malfet — CHANGES_REQUESTED** [review]
Please fix linter errors
Also, consider @mruberry's comment: wouldn't keeping `HPUTestBase` in your code repository be a better solution than keeping it in PyTorch core?

**Comment by sujoysaraswati** [comment]
> The lint errors are real.
> 
> This looks generally correct otherwise but you don't actually need to add the test base in PyTorch itself. The PyTorch/XLA project, for example, defines their XLA test base here:
> 
> https://github.com/pytorch/xla/blob/master/test/pytorch_test_base.py
> 
> The instructions for how to get this added as a test base are here:
> 
> https://github.com/pytorch/pytorch/blob/7e7be526c9d9179f35084e9cca5b5c5ad5172100/torch/testing/_internal/common_device_type.py#L512
> 
> Maintaining their test base in their repo makes it easy for PyTorch/XLA to make updates. Is that a solution that you'd prefer, @jeejakp12?



> The lint errors are real.
> 
> This looks generally correct otherwise but you don't actually need to add the test base in PyTorch itself. The PyTorch/XLA project, for example, defines their XLA test base here:
> 
> https://github.com/pytorch/xla/blob/master/test/pytorch_test_base.py
> 
> The instructions for how to get this added as a test base are here:
> 
> https://github.com/pytorch/pytorch/blob/7e7be526c9d9179f35084e9cca5b5c5ad5172100/torch/testing/_internal/common_device_type.py#L512
> 
> Maintaining their test base in their repo makes it easy for PyTorch/XLA to make updates. Is that a solution that you'd prefer, @jeejakp12?

@mruberry - since HPU is a closed source development. If we later want to add the HPU tests as part of the PyTorch CI, we will not have a counterpart of the pytorch/xla repo from where the CI can pick up the pytorch_test_base.py for HPU. Hence, we are trying to see if these infrastructural changes can be added to PyTorch main. Do you have any advice if/how this can be done?

**Comment by wconstab** [comment]
@sujoysaraswati I think before we determine where to put this testbase file, it would be best to document the overall plans for CI.  I'm not a pytorch CI infra expert, so we should probably discuss with @malfet and get an idea how other backends have approached this.  I realize that pytorch/xla has an open source repo while you don't plan to, but I'm not sure if an open source repo is a requirement or not for having a custom test base in your backend.

**Comment by mruberry** [comment]
Was there a resolution on this PR? We should close it if it's not moving forward.

**Comment by wconstab** [comment]
I believe @sujoysaraswati and @jeejakp12 are discussing options internally; can you let us know if you have concluded to use an external public repo for these API and test-base components?

**Comment by sujoysaraswati** [comment]
> I believe @sujoysaraswati and @jeejakp12 are discussing options internally; can you let us know if you have concluded to use an external public repo for these API and test-base components?

Right, we are discussing to keep this external. I will ask @jeejakp12 to close this PR.

**Comment by jeejakp12** [comment]
As per the discussion, we keep this externally for now. So closing this request.

**Pull request closed without merging**
