### PR TITLE
[test_nn] move init tests from test_nn

### PR DESCRIPTION
**Pull request by kshitij12345**
Ref: https://github.com/pytorch/pytorch/issues/63085

Note: Doesn't need corresponding XLA PR as the migrated tests were not run on XLA (as they weren't in TestNNDeviceType).

### CODE REVIEW

**Comment by kshitij12345** [comment]
Gentle ping @albanD

**Review by albanD — APPROVED** [review]
The move looks good.
Is the xla side PR ready?

**Comment by kshitij12345** [comment]
This doesn't require XLA side PR as these tests were not part of TestNNDevice and hence didn't run on XLA.

**Comment by albanD** [comment]
Sorry, read your comment too quickly... Sounds good then!

**Pull request closed without merging**
