### PR TITLE
[quant] Remove assert for weight since it could be non-Tensor

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #74365

Summary:
att

Test Plan:
Meta-Internal tests with fx2trt

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D34952754](https://our.internmc.facebook.com/intern/diff/D34952754)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34952754).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34952754).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34952754).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34952754).

**Review by andrewor14 — APPROVED** [review]

**Pull request closed without merging**
