### PR TITLE
Output peak memory stats from dynamo torchbench perf CI

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #95666

Adds absolute memory usage numbers (in addition to compression ratio) to performance jobs.

Example output:
image

cc @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Comment by wconstab** [comment]
@williamwen42 Do you know if this change will break nightly dashboard stuff?  It adds columns to the .csv.  If I need to update some parser or something, let me know.

**Review by ezyang — APPROVED** [review]

**Review by williamwen42 — APPROVED** [review]

**Pull request closed without merging**
