### PR TITLE
[cuDNN V8 API] Enable building cuDNN v8 API by default

### PR DESCRIPTION
**Pull request by eqy**
Testing via CI

### CODE REVIEW

**Comment by ngimel** [comment]
Should we for now just enable build, and enable runtime use of cudnn8 apis in the separate PR?

**Comment by eqy** [comment]
> Should we for now just enable build, and enable runtime use of cudnn8 apis in the separate PR?

Sure, we can do that. I believe the failing tests due to `dtype` are due to a missing check for compute capability when trying to use cuDNN BFloat16. Will open a separate PR to track.

**Comment by eqy** [comment]
Build failure on Windows
```
2022-04-08T19:21:15.9251708Z C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\quantized\cudnn\conv_prepack.cpp(25): error C2491: 'PackedConvWeightCudnn<kSpatialDim>::prepack': definition of dllimport function not allowed
2022-04-08T19:21:16.9097857Z C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\quantized\cudnn\conv_unpack_impl.cpp(19): error C2491: 'PackedConvWeightCudnn<kSpatialDim>::unpack': definition of dllimport function not allowed
```
looks real, but not sure of the cause here.

**Comment by ngimel** [comment]
cc @jerryzh168, what's David's github name?

**Comment by jerryzh168** [comment]
> cc @jerryzh168, what's David's github name?

it's @dzdang

**Comment by dzdang** [comment]
@eqy 
sorry, just saw this PR today. can you stack your PR on top of this PR: https://github.com/pytorch/pytorch/pull/75934
and see if that fixes the issue. I'm not totally sure this is the problem, but let's give it a try

**Comment by eqy** [comment]
Windows test seems OK now but a new build failure might be related?
```
/var/lib/jenkins/workspace/c10/util/Optional.h:595:7: error: destructor called on non-final 'cudnn_frontend::Operation_v8' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
      dataptr()->~T();
      ^
/var/lib/jenkins/workspace/c10/util/Optional.h:695:5: note: in instantiation of member function 'c10::optional<cudnn_frontend::Operation_v8>::clear' requested here
    clear();
    ^
/var/lib/jenkins/workspace/aten/src/ATen/native/quantized/cudnn/Conv.cpp:205:18: note: in instantiation of function template specialization 'c10::optional<cudnn_frontend::Operation_v8>::emplace<cudnn_frontend::Operation_v8>' requested here
    bias_mult_op.emplace(cudnn_frontend::OperationBuilder(CUDNN_BACKEND_OPERATION_POINTWISE_DESCRIPTOR)
                 ^
/var/lib/jenkins/workspace/aten/src/ATen/native/quantized/cudnn/Conv.cpp:337:3: note: in instantiation of function template specialization 'PackedConvWeightCudnn<2>::apply_impl_helper<false>' requested here
  apply_impl_helper<kReluFused>(
  ^
/var/lib/jenkins/workspace/aten/src/ATen/native/quantized/cudnn/Conv.cpp:347:10: note: in instantiation of function template specialization 'PackedConvWeightCudnn<2>::apply_impl<false>' requested here
  return apply_impl<false>(input, output_scale, output_zero_point);
         ^
/var/lib/jenkins/workspace/c10/util/Optional.h:595:19: note: qualify call to silence this warning
      dataptr()->~T();
                  ^
                  cudnn_frontend::Operation_v8::
1 error generated.
```

**Comment by dzdang** [comment]
> destructor called on non-final 'cudnn_frontend::Operation_v8' that has virtual functions but non-virtual destructor

@eqy @jerryzh168  
hmm I think this seems like an issue with cudnn? seems it's saying `cudnn_frontend::Operation_v8` has virtual functions but no virtual destructor. wonder why gnu compilers didn't pick this up. 

also, it looks like the Conv_v7.cpp file has the same issue: https://github.com/pytorch/pytorch/runs/6070406134?check_suite_focus=true

**Comment by eqy** [comment]
> 

Thanks for checking on your end! My understanding is that the issue is `BackendDescriptor` (the class that both `ExecutionPlan_v8` and `Operation_v8` inherit from) needs a virtual destructor; I'll forward this issue to cuDNN. Thanks!

**Comment by eqy** [comment]
@dzdang looks like rebasing on top of `viable/strict` somehow exposed some more warnings that are stopping the clang build?

**Comment by dzdang** [comment]
> @dzdang looks like rebasing on top of `viable/strict` somehow exposed some more warnings that are stopping the clang build?

hmm I see. it looks like it's just unused variable warnings? I think we can probably just remove where those variables are defined for now. do you want me to create a PR for this or do you want to embed it in yours?

**Comment by eqy** [comment]
> > @dzdang looks like rebasing on top of `viable/strict` somehow exposed some more warnings that are stopping the clang build?
> > @eqy
> > hmm I see. it looks like it's just unused variable warnings? I think we can probably just remove where those variables are defined for now. do you want me to create a PR for this or do you want to embed it in yours?

If you're OK with it I'll abate what warnings and I can and recheck CI status.

**Comment by dzdang** [comment]
> > > @dzdang looks like rebasing on top of `viable/strict` somehow exposed some more warnings that are stopping the clang build?
> > > @eqy
> > > hmm I see. it looks like it's just unused variable warnings? I think we can probably just remove where those variables are defined for now. do you want me to create a PR for this or do you want to embed it in yours?
> 
> If you're OK with it I'll abate what warnings I see and recheck CI status.

yup, no problem with us

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
