### PR TITLE
[CUDA] `sm_87` / Jetson Orin support

### PR DESCRIPTION
**Pull request by eqy**
Surfaced from #94438 CC @ptrblck @ngimel

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
rubberstamp

**Comment by malfet** [comment]
Err, shouldn't that be guard with `platform.processor() == "arm"`? Otherwise it will build stuff for sm_87 on x86, which is simply a waste of CPU cycles?

**Comment by eqy** [comment]
That's a good point, I'll work on a follow up for this.

**Comment by ptrblck** [comment]
Maybe a guard could work or adding the `Tegra` tag as in:
```
('Maxwell+Tegra', '5.3'),
```
Btw. `('Volta+Tegra', '7.2')` seems to be missing, too.

**Pull request closed without merging**
