### PR TITLE
[dynamo] guard for global fn

### LINKED ISSUE #108898: [dynamo] Missing guard on global function
### 🐛 Describe the bug

```python
import torch

def some_fn(x):
    return torch.sin(x) + 20

def foo(x, y):
    x = some_fn(x)

    def add(x, y):
        return x + y

    return add(x, y)

x = torch.ones(1,)
y = torch.ones(1,)

opt = torch.compile(foo, fullgraph=True, backend='aot_eager')
print("ACTUAL:", opt(x, y), " EXPECTED:", foo(x, y))

# Change some_fn
some_fn = lambda x: torch.cos(x)

print("ACTUAL:", opt(x, y), " EXPECTED:", foo(x, y))
```

Output
```
ACTUAL: tensor([21.8415])  EXPECTED: tensor([21.8415])
ACTUAL: tensor([21.8415])  EXPECTED: tensor([1.5403])
```

Output: `TORCH_LOGS="+guards" python test.py` (no guards for `some_fn`)
```
[2023-09-08 20:33:41,833] [0/0] torch._dynamo.guards.__guards: [DEBUG] GUARDS:
[2023-09-08 20:33:41,834] [0/0] torch._dynamo.guards.__guards: [DEBUG] hasattr(L['x'], '_dynamo_dynamic_indices') == False           # _dynamo/variables/builder.py:1273 in wrap_fx_proxy_cls
[2023-09-08 20:33:41,834] [0/0] torch._dynamo.guards.__guards: [DEBUG] hasattr(L['y'], '_dynamo_dynamic_indices') == False           # _dynamo/variables/builder.py:1273 in wrap_fx_proxy_cls
[2023-09-08 20:33:41,834] [0/0] torch._dynamo.guards.__guards: [DEBUG] ___is_grad_enabled()                                          # _dynamo/output_graph.py:359 in init_ambient_guards
[2023-09-08 20:33:41,834] [0/0] torch._dynamo.guards.__guards: [DEBUG] not ___are_deterministic_algorithms_enabled()                 # _dynamo/output_graph.py:355 in init_ambient_guards
[2023-09-08 20:33:41,834] [0/0] torch._dynamo.guards.__guards: [DEBUG] ___is_torch_function_enabled()                                # _dynamo/output_graph.py:363 in init_ambient_guards
[2023-09-08 20:33:41,834] [0/0] torch._dynamo.guards.__guards: [DEBUG] utils_device.CURRENT_DEVICE == None                           # _dynamo/output_graph.py:361 in init_ambient_guards
[2023-09-08 20:33:41,834] [0/0] torch._dynamo.guards.__guards: [DEBUG] check_tensor(L['x'], Tensor, DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), torch.float32, device=None, requires_grad=False, size=[1], stride=[1])  # _dynamo/variables/builder.py:1273 in wrap_fx_proxy_cls
[2023-09-08 20:33:41,834] [0/0] torch._dynamo.guards.__guards: [DEBUG] check_tensor(L['y'], Tensor, DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), torch.float32, device=None, requires_grad=False, size=[1], stride=[1])  # _dynamo/variables/builder.py:1273 in wrap_fx_proxy_cls
ACTUAL: tensor([21.8415])  EXPECTED: tensor([21.8415])
ACTUAL: tensor([21.8415])  EXPECTED: tensor([1.5403])
```

cc: @zou3519

### Versions

main

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @wconstab @Xia-Weiwen

### PR DESCRIPTION
**Pull request by kshitij12345**
Fixes https://github.com/pytorch/pytorch/issues/108898

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by jon-chuang** [comment]
@kshitij12345 why did you close this? And why are so many tests failing?

**Comment by jon-chuang** [comment]
I can reproduce your original issue.

**Comment by jon-chuang** [comment]
However, I can't see the use-case. Could you explain why someone would want to do this? It's also not clear users should expect that modifying a global function ought to trigger recompilation.

**Comment by kshitij12345** [comment]
> why did you close this? 

I won't have bandwidth in coming weeks to work on it, so closed the issue so that someone can have a look.

> And why are so many tests failing?

I am not sure, I didn't get a chance to properly investigate the failure.

> However, I can't see the use-case. Could you explain why someone would want to do this?

I think the main issue is that it is divergent from same eager code and returns incorrect result silently. So if user ever does this they would have to know that this diverging behaviour occurs.

**Comment by jon-chuang** [comment]
@kshitij12345 do you think that this guard can be exported? It seems it would be hard to export a guard on global function? :thinking:

**Comment by jon-chuang** [comment]
Right, so it seems the tests are failing _precisely_ because these guards cannot be exported.

**Pull request closed without merging**
