### PR TITLE
Support more foreach ops for tensor beta support

### PR DESCRIPTION
**Pull request by mlazos**
Add more foreach ops so we don't have fallbacks.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #134171
* __->__ #134170

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
wonder if we could do this more programatically..

**Comment by mlazos** [comment]
> wonder if we could do this more programatically..

Hmm I'm not sure, I think for testing I could use the op info tests for for each. For this I'm not sure mainly because there might be patterns or weird overloads that aren't support yet. Which is why we've incrementally added. This is kind of a consequence of the foreach API itself which has been incrementally updated as needed and not all overloads are supported for every op.

**Review by eellison — APPROVED** [review]
meant to accept

**Comment by eellison** [comment]
Like, would it be sufficient to register 
```
for op in foreach:
    equiv_aten_op = op.name[op.name.find("aten._foreach_"):]
    register_foreach_pointwise(op, lowerings[getattr(aten, equiv_aten_op)])
```

**Comment by mlazos** [comment]
> Like, would it be sufficient to register 
> 
> ```
> 
> for op in foreach:
> 
>     equiv_aten_op = op.name[op.name.find("aten._foreach_"):]
> 
>     register_foreach_pointwise(op, lowerings[getattr(aten, equiv_aten_op)])
> 
> ```
> 
> 

The issue is I also need to generate tests for them, but let me see if I can use some sort of operator schema to generate the tests (which would be pretty cool)

**Pull request closed without merging**
