### PR TITLE
Update deprecated torch.lu_solve

### PR DESCRIPTION
**Pull request by kit1980**

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
All these tests should be removed. Now, they should be removed together with the deprecated operation, if we want to go down that road.
There's a precedent for this in https://github.com/pytorch/pytorch/pull/70986

**Comment by kit1980** [comment]
> All these tests should be removed. Now, they should be removed together with the deprecated operation, if we want to go down that road. There's a precedent for this in #70986

I can remove the op together with the test.
Don't we want to repurpose the old tests for the new op, like I did in this PR so far? They seem to be testing different things that current tests for `torch.linalg.lu_solve`?

I was actually thinking of doing 1 op myself and bootcamp the other ops, do you think it's a good idea?

**Comment by albanD** [comment]
In general, I think we should simply follow the policies from https://github.com/pytorch/pytorch/wiki/PyTorch's-Python-Frontend-Backward-and-Forward-Compatibility-Policy

If the deprecation period has been followed already and we don't have evidence that the function is still widely used, then yes we can remove it (and indeed someone on our end might need to cleanup some internal code but that shouldn't be a blocker).

In this particular case, I think the function is still quite popular: https://github.com/search?q=torch.lu_solve&type=code so I'm not sure we want to remove it just now (especially because it is not a big issue to keep it).

**Comment by kit1980** [comment]
Closing this for now.

**Comment by Lezcano** [comment]
For what is worth `torch.lu` and `torch.lu_solve` were deprecated in https://github.com/pytorch/pytorch/pull/77636 just 2 weeks ago. Now, there are plenty of others that have been deprecated for 3+ versions but that would need help from someone within META to remove them. See:
https://github.com/pytorch/pytorch/pull/70978

**Comment by Lezcano** [comment]
They have been deprecated for over a year now, so well over what it's suggested in https://github.com/pytorch/pytorch/wiki/PyTorch's-Python-Frontend-Backward-and-Forward-Compatibility-Policy

**Comment by IvanYashchuk** [comment]
Thanks, Sergii, I will rebase those PRs and ping you there.

**Pull request closed without merging**
