### PR TITLE
Turn on GraphTransformObserver for inductor

### PR DESCRIPTION
**Pull request by shengfukevin**
The FX graphs for some PT2 models are very complicated, Inductor usually goes through many passes of graph optimization to generate the final FX graph. It’s very difficult to see the change in each pass, and check if the optimized graph is correct and optimal. 

GraphTransformObserver is an observer listening to all add/erase node events on GraphModule during a graph transform pass, and save the changed nodes. When the pass is done and if there is any change in the graph, GraphTransformObserver will save the SVG files of the input graph and the output graph for that pass. 

This PR is to enable GraphTransformObserver for inductor.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
@oulgen since we should check if this has any impact on compile times.

@shengfukevin have you benchmarked compile times?

Can we add some tests?

**Comment by shengfukevin** [comment]
> @oulgen since we should check if this has any impact on compile times.
> 
> @shengfukevin have you benchmarked compile times?
> 
> Can we add some tests?

I just ran a few local tests for the compile time, not the nightly run. I will rebase and test it. 

Thanks

**Comment by shengfukevin** [comment]
Added a unit test in test/test_graph_transform_observer.py

These are the output files:

pass_9_pattern_matcher_input_graph
pass_9_pattern_matcher_output_graph

**Comment by shengfukevin** [comment]
GraphTransformObserver itself has been tested in caffe2/test/fx/test_fx_xform_observer.py

**Review by jansel — APPROVED** [review]

**Comment by oulgen** [comment]
Did you not rebase this diff correctly? The perf numbers are all over the place
image

**Comment by shengfukevin** [comment]
> Did you not rebase this diff correctly? The perf numbers are all over the place image

Do you mean the red numbers?

**Comment by shengfukevin** [comment]
Jason said it is because some tests are not done yet.

**Pull request closed without merging**
