### PR TITLE
Support postponed annotations in JIT

### PR DESCRIPTION
**Pull request by LoicGrobol**
Fix for #30965 

Not mergeable for now, since I have not added a test for this yet because I couldn't figure out if/how annotations are tested, considering [test_recursive_script.py#L161](https://github.com/pytorch/pytorch/blob/b8f50d9cc860460c7e9b6d3b370cab546e9f9583/test/jit/test_recursive_script.py#L161)

cc @suo

### CODE REVIEW

**Comment by suo** [comment]
I think test/test_jit_py3.py is probably the best place

**Comment by LoicGrobol** [comment]
Thanks, my issue was that the future import works at the file level, so I can't really integrate it with the rest of the test suite, but now that I think of it, I can still fake it by manually setting `__annotations__`. I'll try that :-)

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit dca604c1:


* **2/2** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=dca604c1c9edc1840782132263af13a16bffb500).

### :detective: 2 new failures recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4100872) pytorch_linux_xenial_py3_6_gcc5_4_build (1/2)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=79363490) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=79363490))
<details>
<summary>
<code>Automatic merge failed; fix conflicts and then commit the result.</code>
</summary>

```
CONFLICT (add/add): Merge conflict in .circleci/verbatim-sources/docker_jobs.yml 
Auto-merging .circleci/verbatim-sources/docker_jobs.yml 
CONFLICT (add/add): Merge conflict in .circleci/scripts/python_doc_push_script.sh 
Auto-merging .circleci/scripts/python_doc_push_script.sh 
CONFLICT (add/add): Merge conflict in .circleci/ecr_gc_docker/gc.py 
Auto-merging .circleci/ecr_gc_docker/gc.py 
CONFLICT (add/add): Merge conflict in .circleci/docker/common/install_conda.sh 
Auto-merging .circleci/docker/common/install_conda.sh 
CONFLICT (add/add): Merge conflict in .circleci/config.yml 
Auto-merging .circleci/config.yml 
Automatic merge failed; fix conflicts and then commit the result. 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4100864) pytorch_xla_linux_xenial_py3_6_clang7_build (2/2)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=79363820) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=79363820))
<details>
<summary>
<code>Jan 02 17:45:00 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-serialization.diff</code>
</summary>

```
Jan 02 17:45:00 + python /var/lib/jenkins/workspace/xla/scripts/cond_patch.py /var/lib/jenkins/workspace/xla/scripts/../torch_patches /var/lib/jenkins/workspace/xla/scripts/../.. 
Jan 02 17:45:00 1 out of 1 hunk FAILED 
Jan 02 17:45:00 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-clip_grad.diff 
Jan 02 17:45:00 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff 
Jan 02 17:45:00 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-serialization.diff 
Jan 02 17:45:00 Traceback (most recent call last): 
Jan 02 17:45:00   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 67, in <module> 
Jan 02 17:45:00     patch_repo(args) 
Jan 02 17:45:00   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 49, in patch_repo 
Jan 02 17:45:00     raise RuntimeError('Failed to apply patch: {}'.format(ppath)) 
Jan 02 17:45:00 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-serialization.diff 
Jan 02 17:45:00 + cleanup 
Jan 02 17:45:00 + retcode=1 
Jan 02 17:45:00 + set +x 
Jan 02 17:45:00 =================== sccache compilation log =================== 
Jan 02 17:45:00 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 02 17:45:00 Compile requests                 1 
Jan 02 17:45:00 Compile requests executed        0 
Jan 02 17:45:00 Cache hits                       0 
Jan 02 17:45:00 Cache misses                     0 
Jan 02 17:45:00 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by eellison** [comment]
@LoicGrobol as far as I can tell, patch looks good - do you mind rebasing and adding a test and we'll try to merge this?

**Comment by Evpok** [comment]
Hey @eellison I don't mind at all but I have absolutely no time to spare at the moment and I have not yet found the time to find out how to test this. I will get back to it as soon as I can, sorry for the inconvenience!

**Comment by eellison** [comment]
@evpok, no problem, sounds good!

**Comment by LoicGrobol** [comment]
Closing since it has become a mess due to multiple rebasing (sorry) and https://github.com/pytorch/pytorch/issues/32544 supersedes it

**Pull request closed without merging**
