### PR TITLE
Reformat run_test.py

### PR DESCRIPTION
**Pull request by driazati**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #63809
* **#63808**

`black run_test.py`

Differential Revision: [D30497437](https://our.internmc.facebook.com/intern/diff/D30497437)

### CODE REVIEW

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30497437).

**Comment by janeyx99** [comment]
Do we want to use black for all our python files/what are our plans for maintaining this in the future?

**Comment by driazati** [comment]
> Do we want to use black for all our python files/what are our plans for maintaining this in the future?

We don't have a recommended linter and I think formatter lint jobs are overkill. We could automate things like this PR for certain files (i.e. a bot pushes a format PR every monday or something)

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30497437).

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30497437).

**Pull request closed without merging**
