### PR TITLE
Add decomposition for addbmm

### PR DESCRIPTION
**Pull request by amjames**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #117495

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @desertfire @chauhang

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
It's not entirely clear to me whether we want to have this decomposition. `torch.bmm` is implemented via a template, so we will not be able to fuse the `sum` and the `add` into it and we may end up generating two kernels rather than one. It should be easy to generalise the `bmm` to implement `addbmm` tho.

**Comment by peterbell10** [comment]
It's probably worth benchmarking though, as I was surprised to see that `bmm` just does repeated inplace addmm calls.
https://github.com/pytorch/pytorch/blob/5c700f60a5ee588d32975fc0acd80dfc06e14425/aten/src/ATen/native/LinearAlgebra.cpp#L1573-L1576

This method would use more memory though.

**Comment by lezcano** [comment]
Yeah, I think that if we want to lower this op properly, we should either:
- Implement a triton kernel for it (pretty much copying that of `aten.bmm`)
- Lower it as it's implemented in eager and teach `torch.` how to reinplace `addmm_`

Both approaches are comparable when it comes to difficulty, but I think the first one should yield much better results. @peterbell10 thoughts?

**Comment by peterbell10** [comment]
> Implement a triton kernel for it (pretty much copying that of aten.bmm)

Dedicated triton kernel is probably the best option, but note it's more complicated than `bmm` because the matmul results need to be summed, making it no longer trivially parallel in the batch dim. I think you could express it as a matmul of `[n, b * k] @ [b * k, m]` and adapt the triton matmul kernel to perform that operation, though you would probably need the `SPLIT_K` version. 

> Lower it as it's implemented in eager and teach torch. how to reinplace addmm_

This wouldn't work well for dynamic shapes since it would require the batch size to be a static shape. Reinplacing `addmm_` would be very valuable on its own though.

**Comment by lezcano** [comment]
Actually, now that I think about it, I think we already have `addmm_` reinplacing implemented.
And yes, we would need to guard on the inner dimension, but that's not too bad. Perhaps it's best to implement this approach and leave a note discussing the dedicated kernel, given that this op is not used too much.

**Comment by peterbell10** [comment]
> yes, we would need to guard on the inner dimension, but that's not too bad.

Compared to the eager implementation we would be introducing a new guard without introducing any new fusion opportunities, so that does seem bad to me. Though perhaps it's worth it if the matmul perf improvements are significant enough.

**Comment by lezcano** [comment]
We could use the decomposition if the dimension is not dynamic, for example.

**Pull request closed without merging**
