### PR TITLE
[GHF] Changing the ordering in merge rules to allow more appropriate messages to be raised first

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #84359

Changing the ordering in merge rules to allow more appropriate messages to be raised first.

Context: [#84279](https://github.com/pytorch/pytorch/pull/84279#issuecomment-1233130498)
@janeyx99: "Approving to unblock, but modifying the merge rules to move the Core maintainers rule to last would be a good idea."

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
woo

**Review by ZainRizvi — APPROVED** [review]
🚀🚀🚀

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
