### PR TITLE
Fix race conditions on SpatialConvolutionMM

### LINKED ISSUE #1380: Huge precision errors in ppc64le tests
At least these tests fail randomly due to a huge precision error (approximately 1 fail every 100 executions):

`test_Conv1d`:
```
FAIL: test_Conv1d (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_nn.py", line 2330, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/brosa/pytorch/test/common_nn.py", line 571, in __call__
    self._do_test(test_case, module, input)
  File "test/test_nn.py", line 69, in _do_test
    test_case.check_jacobian(module, input, self.jacobian_input)
  File "/home/brosa/pytorch/test/common_nn.py", line 459, in check_jacobian
    PRECISION
AssertionError: 597828.9410372106 not less than or equal to 1e-05
```
`test_Conv2d_groups_thnn`:
```
FAIL: test_Conv2d_groups_thnn (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_nn.py", line 2330, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/brosa/pytorch/test/common_nn.py", line 571, in __call__
    self._do_test(test_case, module, input)
  File "test/test_nn.py", line 69, in _do_test
    test_case.check_jacobian(module, input, self.jacobian_input)
  File "/home/brosa/pytorch/test/common_nn.py", line 459, in check_jacobian
    PRECISION
AssertionError: 512396.96441206516 not less than or equal to 1e-05
```
`test_Conv2d_padding`:

```
FAIL: test_Conv2d_padding (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 2330, in <lambda>
    setattr(TestNN, test_name, lambda self, test=test: test(self))
  File "/home/brosa/pytorch/test/common_nn.py", line 571, in __call__
    self._do_test(test_case, module, input)
  File "test_nn.py", line 69, in _do_test
    test_case.check_jacobian(module, input, self.jacobian_input)
  File "/home/brosa/pytorch/test/common_nn.py", line 459, in check_jacobian
    PRECISION
AssertionError: 1149022.966940353 not less than or equal to 1e-05
```
Summary list of failing NN tests with similat outputs:
```
FAIL: test_Conv1d_groups (__main__.TestNN)
FAIL: test_Conv1d (__main__.TestNN)
FAIL: test_Conv1d_pad1 (__main__.TestNN)
FAIL: test_Conv1d_pad2 (__main__.TestNN)
FAIL: test_Conv1d_stride (__main__.TestNN)
FAIL: test_Conv2d_groups (__main__.TestNN)
FAIL: test_Conv2d_groups_thnn (__main__.TestNN)
FAIL: test_Conv2d (__main__.TestNN)
FAIL: test_Conv2d_no_bias (__main__.TestNN)
FAIL: test_Conv2d_padding (__main__.TestNN)
FAIL: test_Conv2d_strided (__main__.TestNN)
```

I'll update the issue if/when I find more failing tests.

### PR DESCRIPTION
**Pull request by brunoalr**
In ppc64le, when running testNN's convolution tests sometimes a precision assertion failed.
Fixes #1380

### CODE REVIEW

**Comment by gut** [comment]
Maintainer: By the way, are there any other similar spots where this kind of issue might be happening?

@brunoalr: I guess that this particular spot was only caught by chance, right?

**Comment by brunoalr** [comment]
@gut that is correct. I saw that some tests fail randomly by chance. Then I proceeded to run those tests for a long time and check if they failed.

**Comment by pavanky** [comment]
Reiterating my comment from #1380 to ask the `#pragma omp critical` be at a more granular level or `#pragma omp parallel` be removed instead of the current solution.

**Comment by brunoalr** [comment]
@pavanky cc @soumith 
As we discussed in the related issue, we can either

1) Use `critical` more granularly
2) Remove the `parallel` pragma

Option 2 is easier to implement. Regarding option 1, can you help me finding the "most atomic" critical sections?

**Comment by ngimel** [comment]
Start by putting THVector_(fill) in the critical section, as this seems to be the only architecture-dependent part? https://github.com/PPC64/pytorch/blob/89dc368aae5710610045de4020048f743fd361b6/torch/lib/THNN/generic/SpatialConvolutionMM.c#L99-L102

**Comment by soumith** [comment]
i think the solution here is to move the `critical` call only around the BLAS operations (which will use multicore anyways). They are likely the ones causing races. everything else should be good.

**Comment by brunoalr** [comment]
@ngimel thanks for pointing it out. @gut and I tried it before and that didn't solve the issue.

**Comment by brunoalr** [comment]
@soumith now I remember why I didn't use `critical` in another function: because that would generate an orphaned critical construct, which seems to be a mistake (see https://pdfs.semanticscholar.org/4e60/37127e85445079272e1cb5574cbcce2e175e.pdf )

So, I'm more inclined to remove the `parallel` constructs altogether.

**Comment by pavanky** [comment]
@brunoalr Are you talking about this:

> 3. Use of orphaned construct outside parallel region: When using a combined
worksharing construct, sometimes our students would forget to put down the
parallel, producing an orphaned construct. In other cases, the parallel region
was forgotten altogether, leading e. g. to orphaned critical constructs.

**Comment by brunoalr** [comment]
@pavanky exactly.

**Comment by pavanky** [comment]
@brunoalr I don't think that matters here. The critical section will still be inside the parallel section.

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
this makes sense now. There's no way unfortunately to check if your BLAS uses OpenMP, so let's go with this.

**Comment by brunoalr** [comment]
@soumith awesome, thanks! can you ping your other CI, please?

**Comment by soumith** [comment]
this is now merged into master

**Pull request closed without merging**
