### PR TITLE
[ROCm][CI] upgrade CI to ROCm 6.1

### PR DESCRIPTION
**Pull request by jeffdaily**
cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jeffdaily** [comment]
@malfet or @huydhn or @atalman can you help us land this PR?  The remaining ROCm CI failures are unrelated to the upgrade from 6.0 to 6.1 and are present on the HUD already or are flaky.  The main 6 shards are passing.  Worst case, we can move periodic and/or slow to unstable if I'm wrong, but I've rebased this PR many times now and gotten different results each time.  We have some unit tests unskipping PRs blocked by our upgrade to 6.1.

**Review by malfet — APPROVED** [review]
LGTM

**Pull request closed without merging**
