### PR TITLE
Add docstring type guidelines for list & tuple to `CONTRIBUTING.md`

### PR DESCRIPTION
**Pull request by ProGamerGov**
Minor followup to: https://github.com/pytorch/pytorch/pull/83536

For Google style docstrings, `list` and `tuple` should be completely lowercase.

### CODE REVIEW

**Comment by ProGamerGov** [comment]
cc @H-Huang

**Comment by ProGamerGov** [comment]
At some point we should decide on the proper docstring type formatting of the `torch.Tensor` and `torch.nn.Module`.

I've seen people using `torch.nn.Module`, `nn.Module`, & `Module`. I've also seen both `torch.Tensor` and simply `Tensor` being used. I think that we should standardize which one is used.

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
@ProGamerGov you can merge after CI is green

**Comment by ProGamerGov** [comment]
Thank you @ngimel !

**Pull request closed without merging**
