### PR TITLE
[ROCm] [ROCm2.9+] enable rocTX API

### PR DESCRIPTION
**Pull request by iotamudelta**
ROCm 2.9 brings support for the rocTX API through rocTracer.

### CODE REVIEW

**Comment by bddppq** [comment]
When will ROCm 2.9 be available? :-)

**Comment by iotamudelta** [comment]
@bddppq reached GA just a few hours ago. see: http://repo.radeon.com/rocm/apt/ :-)

**Comment by bddppq** [comment]
lol I should wait for this before doing the 2.8 upgrade

**Comment by bddppq** [comment]
lint failures are real:
```
cmake/Dependencies.cmake
The above files have tabs; please convert them to spaces
```

**Comment by iotamudelta** [comment]
@bddppq the `clang-tidy` error seems weird - this PR only undef's the code in question for ROCm.

**Comment by bddppq** [comment]
Yep I think the clang-tidy check is trying to lint the whole file instead of just the changed lines. We can ignore those in this PR.

**Comment by bddppq** [comment]
Upgrading to ROCm 2.9 in https://github.com/pytorch/pytorch/pull/27417

**Pull request closed without merging**
