### PR TITLE
[c++] use constexpr instead of const

### PR DESCRIPTION
**Pull request by khushi-411**
As discussed in https://github.com/pytorch/pytorch/pull/93199#discussion_r1089777684.

cc: @Skylion007!

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by khushi-411** [comment]
Thanks for reviewing, @Skylion007!

@pytorchbot label ciflow/trunk

**Comment by malfet** [comment]
Hmm, this will break some ancient Windows builds(internally people report ICEs with old CUDA/VC++), but also, I remember there was a warning not to use `constexpr` with JITerated kernels. @ngimel do you remember the context?

**Comment by malfet** [comment]
Can we replace those with `CONSTEXPR_EXCEPT_WIN_CUDA`? (Looks ugly, but fixes the problem)
cc: @Skylion007

**Comment by Skylion007** [comment]
@malfet Seems reasonable to me, the constexpr is just a general C++ safety recomendation (making it constexpr allows for more compile time checks etc).

**Comment by ngimel** [comment]
Sorry, don't remember, I see that constexpr is used in the jiterator templates, so should be fine.

**Comment by seemethere** [comment]
> @malfet Seems reasonable to me, the constexpr is just a general C++ safety recomendation (making it constexpr allows for more compile time checks etc). Does CONSTEXPR_EXCEPT_WIN_CUDA make it as const on win CUDA? If so, that looks like a good candidate.

I think this is what we want

**Comment by malfet** [comment]
Here is the fix for VS2017 compiler exception: https://github.com/pytorch/pytorch/pull/94091

**Pull request closed without merging**
