### PR TITLE
Wconstab/fallback infra

### PR DESCRIPTION
**Pull request by wconstab**
This PR is part one of two, which adds utilities and benchmarks for fallback improvement but should not change actual performance.

RUN_TORCHBENCH: ALL
TORCHBENCH_BRANCH: wconstab/ltc

### CODE REVIEW

**Comment by wconstab** [comment]
@desertfire i looked at torchbench and I didn't see any issue on this PR so we can land it if it looks good to you.  Then i'll pick up on wconstab/fallback2 and debug the issues there.

**Review by Krovatkin — APPROVED** [review]
:shipit: 

nit: @wconstab I'd consider adding an option to not generate the forced eager fallback path at all.

**Comment by wconstab** [comment]
> :shipit:
> 
> nit: @wconstab I'd consider adding an option to not generate the forced eager fallback path at all.

you mean a codegen option?  and your reasoning is to optimize the if-statement out of the production codepath?

**Comment by Krovatkin** [comment]
> you mean a codegen option? and your reasoning is to optimize the if-statement out of the production codepath?

👍 , I should've elaborated. This is pretty minor though

**Comment by wconstab** [comment]
> 👍 , I should've elaborated. This is pretty minor though
ok, yea i agree. but maybe we can add it later.

**Pull request merged**
