### PR TITLE
[pt2] Add reference implementations of torch.{stft,istft}

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #106631
* __->__ #106400
* #106319

This allows symbolic shapes to be traced through `torch.stft` and `torch.istft`.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Also, stft can be (maybe less efficiently) in many cases implemented as a Conv1d op. This might be useful for backends that do not ship a fft functionality yet but support convolutions

**Comment by peterbell10** [comment]
@vadimkantorov I tried out your suggestion but there seems to be some severe performance and precision losses from performing the stft this way.

**Review by lezcano — APPROVED** [review]
Ah, yes, the glorified unfold.

**Pull request closed without merging**
