### PR TITLE
[ROCm] add 4.1 to nightly builds

### PR DESCRIPTION
**Pull request by jeffdaily**
Depends on https://github.com/pytorch/builder/pull/685.

### CODE REVIEW

**Review by walterddr — APPROVED** [review]

**Review by seemethere — CHANGES_REQUESTED** [review]
If we're going to add this should we remove `4.0.1`?

**Comment by walterddr** [comment]
good question. what's the policy here? should we keep 2 minor version for each major? (and when do we remove rocm3?)

**Comment by jeffdaily** [comment]
> good question. what's the policy here? should we keep 2 minor version for each major? (and when do we remove rocm3?)

We would like to keep N, N-1, and N-2 versions available to users.  This is in line with CI image policy.

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
I agree with idea of keeping 3 most recent versions, but considering that first RoCM release was made against 4.0.1 (and there there are no torchvision for 3.10), we should keep building nightlies only for 4.0.1 and 3.10

**Pull request closed without merging**
