### PR TITLE
Read via FileAdapter when loading files in torch if not flatbuffer

### PR DESCRIPTION
**Pull request by Rittzz**
Summary: This will optimize memory usage at the small cost of loading time when loading mobile models restoring the behavior before D36926217 (https://github.com/pytorch/pytorch/commit/fed12ff680813c0fab7dba7232f6b4cd8b33b8d3).

Test Plan: Signals

Reviewed By: qihqi

Differential Revision: D38998858

@diff-train-skip-merge

### CODE REVIEW

**Review by qihqi — APPROVED** [review]

**Comment by cccclai** [comment]
LGTM. Thanks! Also update the pr title from "Use istream when loading files in torch if not flatbuffer" to "Use FileAdapter when loading files in torch if not flatbuffer"

**Review by cccclai — APPROVED** [review]
LGTM. Thanks! Also update the pr title from "Use istream when loading files in torch if not flatbuffer" to "Use FileAdapter when loading files in torch if not flatbuffer" if possible

**Comment by zengk95** [comment]
@pytorchbot revert -m 'asdfas' -c 'ignoredsignal'
  
  
  # Additional Information

  @Ian Graves This PR is being reverted. The following jobs failed on this PR: 
  - Update viable/strict / do_update_viablestrict,- macos-12-py3-x86-64-test-1-2-default / build,- trunk / macos-12-py3-arm64 / test (default, 2, 2, macos-m1-12)
  
  For more information, check the [HUD](https://hud.pytorch.org/pytorch/pytorch/commit/3fae89d4a468a02be501357eb123ce2bf7086d2f).

**Pull request closed without merging**
