### PR TITLE
Update device_mesh.py docs imports

### PR DESCRIPTION
**Pull request by carmocca**
These are not importable from `torch.distributed`, at least today.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Comment by wz337** [comment]
Thanks for catching this.

Will need to rebase after this doc fix PR lands. https://github.com/pytorch/pytorch/pull/116053

**Review by wz337 — APPROVED** [review]

**Review by fegin — APPROVED** [review]

**Pull request closed without merging**
