### PR TITLE
Updates assertEqual to require atol and rtol, removes positional atol

### PR DESCRIPTION
**Pull request by mruberry**
This updates assertEqual and assertEqual-like functions to either require both or neither of atol and rtol be specified. This should improve clarity around handling precision in the test suite, and it allows us to remove the legacy positional atol argument from assertEqual. In addition, the "message" kwarg is replace with a kwarg-only "msg" argument whose name is consistent with unittest's assertEqual argument. 

In the future we could make "msg" an optional third positional argument to be more consistent with unittest's assertEqual, but requiring it be specified should be clear, and we can easily update the signature to make "msg" an optional positional argument in the future, too.

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by rohan-varma** [comment]
Reverting this, as it breaks some master-only tests such as https://app.circleci.com/pipelines/github/pytorch/pytorch/173693/workflows/13915dff-ca6c-4763-a1b6-f7b0211160bc/jobs/5581006/steps, https://app.circleci.com/pipelines/github/pytorch/pytorch/173692/workflows/98c9fc2b-0baf-490f-bd12-603531a38b58/jobs/5580707/steps, https://app.circleci.com/pipelines/github/pytorch/pytorch/173722/workflows/8615add6-e336-490d-bea9-5d20a2af3f30/jobs/5581312/steps

**Comment by malfet** [comment]
Hmm, sorry for the late comment, but this change violates Liskov Substitution Principle. That is, if we want to make `msg` kwarg-only we should rename `assertEqual` and `assertNotEqual` to something else

**Comment by mruberry** [comment]
> Hmm, sorry for the late comment, but this change violates Liskov Substitution Principle. That is, if we want to make `msg` kwarg-only we should rename `assertEqual` and `assertNotEqual` to something else

That's true, but the correct fix is to allow msg to be positional again, which we can now safely do (since we know atol is never specified positionally). Should be a one line PR.

**Comment by malfet** [comment]
@mruberry I'll do it in https://github.com/pytorch/pytorch/pull/39075 along with other typing changes

**Comment by mruberry** [comment]
> @mruberry I'll do it in #39075 along with other typing changes

Awesome!

**Pull request closed without merging**
