### PR TITLE
[ONNX] Support ListConstruct in quantized_args

### LINKED ISSUE #91303: Exporting quantized model with `torch.cat` operators to onnx fails
### 🐛 Describe the bug

I have this simple model:

```python
class TestModel(nn.Module):
    def __init__(self, in_features, out_features):
        super(TestModel, self).__init__()
        self.conv = nn.Conv2d(in_features, out_features, kernel_size=3)
        self.relu = nn.ReLU()

    def forward(self, x):
        out = self.relu(self.conv(x))
        out = torch.cat([out, out], 1)
        return out

model = TestModel(3,1)
```

I am quantizing it as follows using either mode:

1. Eager mode:
```python
model.eval()
qconfig = torch.quantization.get_default_qconfig('fbgemm')
model.qconfig = qconfig

# Fuse modules here if required

model = nn.Sequential(torch.quantization.QuantStub(qconfig), 
                      model, 
                      torch.quantization.DeQuantStub(qconfig))

torch.quantization.prepare(model, inplace=True)

with torch.inference_mode():
    for _ in range(100):
        model(torch.randn(1,3,32,32))

torch.quantization.convert(model, inplace=True)
```

2. FX Graph mode
```python
model.eval()
qconfig_dict = {"": torch.quantization.get_default_qconfig('fbgemm')}
model = quantize_fx.prepare_fx(model, qconfig_dict, example_inputs=(torch.randn(1,3,32,32),))

with torch.inference_mode():
    for _ in range(100):
        model(torch.randn(1,3,32,32))

model = quantize_fx.convert_fx(model)
```

Then I am trying to export it to onnx as follows:
`torch.onnx.export(model, torch.randn(1,3,32,32), 'model_quantized.onnx', opset_version=16)`

This gives me the following output:
```
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\ao\quantization\fx\prepare.py:1530: UserWarning: Passing a QConfig dictionary to prepare is deprecated and will not be supported in a future version. Please pass in a QConfigMapping instead.
  warnings.warn(
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\ao\quantization\observer.py:214: UserWarning: Please use quant_min and quant_max to specify the range for observers.
       reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\_internal\jit_utils.py:258: UserWarning: The shape inference of prim::TupleConstruct type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
Traceback (most recent call last):
  File "c:/Users/fortm/Desktop/cv/t.py", line 54, in <module>
    torch.onnx.export(model, torch.randn(1,3,32,32), out_model_path, opset_version=16)
  File "C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\utils.py", line 504, in export
    _export(
  File "C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\utils.py", line 663, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\utils.py", line 1867, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\symbolic_opset10.py", line 629, in dequantize
    return symbolic_helper.dequantize_helper(g, input)[0]
  File "C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\symbolic_helper.py", line 1533, in dequantize_helper
    unpacked_qtensors = _unpack_quantized_tensor(qtensor)
  File "C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\symbolic_helper.py", line 213, in _unpack_quantized_tensor
    raise errors.SymbolicValueError(
torch.onnx.errors.SymbolicValueError: ONNX symbolic expected the output of `%cat : Tensor = onnx::Concat[axis=1](%conv, %conv), scope: torch.fx.graph_module.GraphModule:: # <eval_with_key>.6:9:0
` to be a quantized tensor. Is this likely due to missing support for quantized `onnx::Concat`. Please create an issue on https://github.com/pytorch/pytorch/issues  [Caused by the value 'cat defined in (%cat : Tensor = onnx::Concat[axis=1](%conv, %conv), scope: torch.fx.graph_module.GraphModule:: # <eval_with_key>.6:9:0
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Concat'.]
    (node defined in <eval_with_key>.6(9): forward
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\nn\modules\module.py(1178): _slow_forward
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\nn\modules\module.py(1190): _call_impl
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\fx\graph_module.py(267): __call__
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\fx\graph_module.py(658): call_wrapped
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\jit\_trace.py(976): trace_module
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\jit\_trace.py(759): trace
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\utils.py(1065): _pre_trace_quant_model
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\utils.py(1110): _model_to_graph
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\utils.py(1529): _export
C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\onnx\utils.py(504): export
c:/Users/fortm/Desktop/cv/t.py(54): <module>
)

    Inputs:
        #0: conv defined in (%conv : Tensor = prim::TupleConstruct(%44, %42, %43), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::conv # C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\_ops.py:442:0
    )  (type 'Tensor')
        #1: conv defined in (%conv : Tensor = prim::TupleConstruct(%44, %42, %43), scope: torch.fx.graph_module.GraphModule::/torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d::conv # C:\Users\fortm\miniconda3\envs\cv\lib\site-packages\torch\_ops.py:442:0
    )  (type 'Tensor')
    Outputs:
        #0: cat defined in (%cat : Tensor = onnx::Concat[axis=1](%conv, %conv), scope: torch.fx.graph_module.GraphModule:: # <eval_with_key>.6:9:0
    )  (type 'Tensor')
```
Removing the line `out = torch.cat([out, out], 1)` and rerunning the script successfully export to onnx.

I would be grateful for any advice on how to solve this issue. Thanks!

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.8.15 (default, Nov 24 2022, 14:38:14) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1070
Nvidia driver version: 522.06
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.0+cu117
[pip3] torchaudio==0.13.0+cu117
[pip3] torchinfo==1.7.1
[pip3] torchvision==0.14.0+cu117
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] torch                     1.13.0+cu117             pypi_0    pypi
[conda] torchaudio                0.13.0+cu117             pypi_0    pypi
[conda] torchinfo                 1.7.1                    pypi_0    pypi
[conda] torchvision               0.14.0+cu117             pypi_0    pypi
```

### PR DESCRIPTION
**Pull request by titaiwangms**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #92009

Fixes #91303 

quantized_args didn't support ListConstruct leading to an error when user uses quantized op with list inputs, ex: aten::cat. After this PR, converter can successfully export the issued model and pass ONNX checker. However, ORT doesn't seem to support it with the very same error as https://github.com/microsoft/onnxruntime/issues/12131. 

Update:
I find test_quantized_cat_when_concatinating_the_same_tensor is even similar to the new case we have in here. The only difference is whether the inputs are already quantized. ONNX graphs both seem to be valid.
[test_quantized_cat_when_concatinating_the_same_tensor.zip](https://github.com/pytorch/pytorch/files/10396798/test_quantized_cat_when_concatinating_the_same_tensor.zip)
[test_quantized_list_of_inputs_with_cat.zip](https://github.com/pytorch/pytorch/files/10396799/test_quantized_list_of_inputs_with_cat.zip)

issue raised https://github.com/microsoft/onnxruntime/issues/14245

### CODE REVIEW

**Comment by justinchuby** [comment]
lgtm

**Comment by BowenBao** [comment]
What is the difference between graph produced by the new test case and `test_quantized_cat`?

**Comment by titaiwangms** [comment]
> What is the difference between graph produced by the new test case and `test_quantized_cat`?

I find `test_quantized_cat_when_concatinating_the_same_tensor` is even similar to the new case we have in here. The only difference is whether the inputs are already quantized. ONNX graphs both seem to be valid.
[test_quantized_cat_when_concatinating_the_same_tensor.zip](https://github.com/pytorch/pytorch/files/10396798/test_quantized_cat_when_concatinating_the_same_tensor.zip)
[test_quantized_list_of_inputs_with_cat.zip](https://github.com/pytorch/pytorch/files/10396799/test_quantized_list_of_inputs_with_cat.zip)

**Review by BowenBao — APPROVED** [review]

**Pull request closed without merging**
