### PR TITLE
[DataPipe] Add generated docstring to functional form DataPipe

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #100503

This PR modified the generation process of `datapipe.pyi` to include the doc strings for each DataPipe in functional form.

The new generated `.pyi` file will look like [this](https://gist.github.com/NivekT/95095f14da85a837a0727a19a5ba367c). I have confirmed the doc string will be visible in PyCharm.

You can copy this [file](https://gist.github.com/NivekT/95095f14da85a837a0727a19a5ba367c) and overwrite your local `datapipe.pyi` to validate this change as well.

Note: We need to create a similar change in TorchData to allow DataPipes in that library to show the doc strings as well.

cc: @weiji14

### CODE REVIEW

**Review by ejguan — APPROVED** [review]
The result looks good to me. Is this change is going to break TorchData's PYI generation?

**Comment by NivekT** [comment]
> The result looks good to me. Is this change is going to break TorchData's PYI generation?

I have made a small update to this PR and ran locally to confirm that it doesn't break TorchData's pyi generation. 

It should look like [this](https://gist.github.com/NivekT/bbcf23d617ff36f15ddc48cba0408f99) (no change needed in TorchData).

**Pull request closed without merging**
