### PR TITLE
UFMT formatting on test/distributions, test/error_messages, test/forward_backward_compatability

### PR DESCRIPTION
**Pull request by arunppsg**
Partiall addresses #123062

UFMT formatting on
- test/distributions
- test/error_messages, test/forward_backward_compatability

cc @albanD

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Comment by arunppsg** [comment]
fixed the following lint [errors](https://github.com/pytorch/pytorch/actions/runs/8590139252/job/23576060777?pr=123527#step:11:300) in e29c8ec

**Comment by ezyang** [comment]
export will conflict with https://github.com/pytorch/pytorch/pull/123520

**Comment by ezyang** [comment]
has nontrivial changes

```
diff --git b/test/export/test_passes.py a/test/export/test_passes.py
index 79cfbd68086..dae9e203747 100644
--- b/test/export/test_passes.py
+++ a/test/export/test_passes.py
@@ -651,7 +651,7 @@ def forward(self, arg_0):
     cos = torch.ops.aten.cos.default(add);  add = None
     sum_2 = torch.ops.aten.sum.default(cos);  cos = None
     submod_3 = self.submod_1
-    wrap_with_set_grad_enabled = torch._higher_order_ops.wrap.wrap_with_set_grad_enabled(False, submod_3, sum_1, sum_2);  submod_3 = sum_1 = sum_2 = None
+    wrap_with_set_grad_enabled = torch._higher_order_ops.wrap.wrap_with_set_grad_enabled(False, submod_3, sum_1, sum_2);  submod_3 = sum_1 = sum_2 = None  # noqa: B950
     add_1 = wrap_with_set_grad_enabled[0]
     add_2 = wrap_with_set_grad_enabled[1];  wrap_with_set_grad_enabled = None
     sub = torch.ops.aten.sub.Tensor(add_1, 1)
@@ -667,13 +667,13 @@ def forward(self, arg_0):
     x, = fx_pytree.tree_flatten_spec(([arg_0], {}), self._in_spec)
     add = torch.ops.aten.add.Tensor(x, 1);  x = None
     submod_5 = self.submod_1
-    wrap_with_set_grad_enabled = torch._higher_order_ops.wrap.wrap_with_set_grad_enabled(True, submod_5, add);  submod_5 = add = None
+    wrap_with_set_grad_enabled = torch._higher_order_ops.wrap.wrap_with_set_grad_enabled(True, submod_5, add);  submod_5 = add = None  # noqa: B950
     sum_1 = wrap_with_set_grad_enabled[0]
     sum_2 = wrap_with_set_grad_enabled[1];  wrap_with_set_grad_enabled = None
     add_1 = torch.ops.aten.add.Tensor(sum_1, 1);  sum_1 = None
     add_2 = torch.ops.aten.add.Tensor(sum_2, 1);  sum_2 = None
     submod_6 = self.submod_3
-    wrap_with_set_grad_enabled_1 = torch._higher_order_ops.wrap.wrap_with_set_grad_enabled(True, submod_6, add_1, add_2);  submod_6 = None
+    wrap_with_set_grad_enabled_1 = torch._higher_order_ops.wrap.wrap_with_set_grad_enabled(True, submod_6, add_1, add_2);  submod_6 = None  # noqa: B950
     sub = wrap_with_set_grad_enabled_1[0]
     sub_1 = wrap_with_set_grad_enabled_1[1];  wrap_with_set_grad_enabled_1 = None
     return pytree.tree_unflatten((add_1, add_2, sub, sub_1), self._out_spec)
```

You can't put the noqa directly in multistring line, has to go at end.

**Review by ezyang — CHANGES_REQUESTED** [review]
will fail ci

**Comment by arunppsg** [comment]
dropped changes to export as it is already covered on https://github.com/pytorch/pytorch/pull/123520

**Comment by ezyang** [comment]
Diff is now

```
diff --git b/test/distributions/test_distributions.py a/test/distributions/test_distributions.py
index 3bb3e4fa5ae..01c598b427d 100644
--- b/test/distributions/test_distributions.py
+++ a/test/distributions/test_distributions.py
@@ -2787,9 +2787,7 @@ class TestDistributions(DistributionsTestCase):
             scipy.stats.multivariate_normal(
                 mean.detach().numpy(), cov.detach().numpy()
             ),
-            "LowRankMultivariateNormal(loc={}, cov_factor={}, cov_diag={})".format(
-                mean, cov_factor, cov_diag
-            ),
+            f"LowRankMultivariateNormal(loc={mean}, cov_factor={cov_factor}, cov_diag={cov_diag})",
             multivariate=True,
         )
 
@@ -5959,9 +5957,7 @@ class TestNumericalStability(DistributionsTestCase):
             expected_value,
             atol=atol,
             rtol=0,
-            msg="Incorrect value for tensor type: {}. Expected = {}, Actual = {}".format(
-                type(x), expected_value, log_pdf
-            ),
+            msg=f"Incorrect value for tensor type: {type(x)}. Expected = {expected_value}, Actual = {log_pdf}",
         )
         if expected_gradient is not None:
             self.assertEqual(
@@ -5969,9 +5965,7 @@ class TestNumericalStability(DistributionsTestCase):
                 expected_gradient,
                 atol=atol,
                 rtol=0,
-                msg="Incorrect gradient for tensor type: {}. Expected = {}, Actual = {}".format(
-                    type(x), expected_gradient, p.grad
-                ),
+                msg=f"Incorrect gradient for tensor type: {type(x)}. Expected = {expected_gradient}, Actual = {p.grad}",
             )
 
     def test_bernoulli_gradient(self):
```

which looks acceptable

**Pull request closed without merging**
