### PR TITLE
generate set_device call to ensure context existence

### LINKED ISSUE #2026: MMCLS Resnet-50 failed training, got 'Triton Error [CUDA]: invalid device context'
### 🐛 Describe the bug

Training MMCLS resnet-50 model with `inductor` backend got `RuntimeError: Triton Error [CUDA]: invalid device context` during backward.

PyTorch version: 2.0.0.dev20230109+cu116

### Error logs

image

### Minified repro

Minifier failed to reproduce the problem. Have tried to locate the function and below are steps to reproduce.

1. Install dependencies of OpenMMLab

```text
ninja
git+https://github.com/open-mmlab/mmengine@experimental/compile
git+https://github.com/open-mmlab/mmcv@2.x
```

2. Install MMCLS from source

```bash
git clone https://github.com/open-mmlab/mmclassification.git
cd mmclassification
git checkout -b 1.x origin/1.x
pip install -r requirements.txt
pip install -e .
```

3. Launch training

```bash
# Seems like errors come from this function
export TORCHDYNAMO_DEBUG_FUNCTION='update_params'
python tools/train.py configs/resnet/resnet50_8xb32_in1k.py --cfg-options compile.target='train_step'
```

### PR DESCRIPTION
**Pull request by ngimel**
Hopefully Fixes https://github.com/pytorch/torchdynamo/issues/2026

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by wconstab — COMMENTED** [review]
i don't follow this, but i will try to test it out tmrw.

why does the set_device call matter?  i gather it is like a no-op since it happens right after `line.codegen` when line is `EnterCudaDeviceContextManagerLine` which will issue a `code.writeline(f"with torch.cuda.device({self.device_idx}):")`.  But why isn't that good enough on its own and how does the `set_device` fix anything?

**Comment by ngimel** [comment]
The test I've added fails without this. The problem is in backward, where the new thread spawned for the backward doesn't have a context associated with it at first. The device guard `with torch.cuda.device(0)` doesn't do anything if current device is the same as requested, so we need additional `set_device` call to bind the thread to already existing primary context. Again, in most cases it's not needed (and that's why we didn't see it), it only happens when the very first kernel in backward is a triton kernel. `set_device` is a cheap call so it doesn't make sense to add complicated logic just to avoid making it always (and we are doing it just once per graph in most cases).

**Review by wconstab — APPROVED** [review]

**Comment by wconstab** [comment]
ok, that makes sense. thanks!

**Pull request closed without merging**
