### PR TITLE
Grammatically updated the tech docs

### PR DESCRIPTION
**Pull request by ashishpandey2600**
Screenshot 2020-11-04 at 1 07 21 PM

small grammatical update to the torch tech docs.

### CODE REVIEW

**Comment by ejguan** [comment]
LGTM.
Can you please rebase this PR against viable/strict branch to make sure all CI green?

**Comment by ashishpandey2600** [comment]
can, please can anybody help me , i m new to this

**Comment by ashishpandey2600** [comment]
it is showing merging is block

**Comment by ashishpandey2600** [comment]
> LGTM.
> Can you please rebase this PR against viable/strict branch to make sure all CI green?

please, sir can u explain i have not understood.

**Comment by ejguan** [comment]
> it is showing merging is block

Thanks for the update, I think it looks great now. I will merge this PR.

**Review by ejguan — APPROVED** [review]

**Pull request closed without merging**
