### PR TITLE
Initial implementation of AdaRound

### PR DESCRIPTION
**Pull request by kwanghoon-meta**
Summary:
This is an implementation of AdaRound from a paper https://arxiv.org/abs/2004.10568

This algorithm is going to be used by multiple people, hence we need make it official implementation.

Differential Revision: D57227565

### CODE REVIEW

**Comment by kwanghoon-meta** [comment]
@pytorchmergebot 

Linterror is not related to this PR

**Review by jerryzh168 — APPROVED** [review]

**Comment by kwanghoon-meta** [comment]
Again, keeps failing with non-related code

**Review by huydhn — APPROVED** [review]
Lint jobs looks green now

**Pull request closed without merging**
