### PR TITLE
[ROCm] Remove usage of deprecated ROCm component header includes

### PR DESCRIPTION
**Pull request by pruthvistony**
- clang parameter 'amdgpu-target' changed to 'offload-arch' 
- HIP and MIOpen includes path updated for extensions

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
image

**Comment by jithunnair-amd** [comment]
@ezyang Please hold off on the merge, I need to clarify a question regarding this PR before we merge this.

**Comment by pruthvistony** [comment]
We decided to push few more changes into this PR, mainly changes to the include path file reorganization on ROCm + clang parameter deprecation, all are related changes and better to keep then together in one PR.

**Review by jithunnair-amd — APPROVED** [review]
LGTM

**Pull request closed without merging**
