### PR TITLE
[logging] Use aot_graph_name for the metrics key for backward compilation.

### PR DESCRIPTION
**Pull request by masnesral**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #138339

Summary: We have an accounting problem when gathering timing during backwards compilation. In the case that we have multiple backwards compilations from the same CompileContext, as is the case with DDPOptimizer, we log an entry for each compile of the backward, but consecutive logs accumulate the times from the previous entries. The issue is that we use the same key to index into the dict holding the metrics (CompileContext.current_compile_id()). This diff changes the index for the backward to use the aot graph name which is guaranteed to be unique.

Test Plan:

**Manually re-enabled logging for unit tests**

```
diff --git a/torch/_dynamo/test_case.py b/torch/_dynamo/test_case.py
index 1a9ebac3adf..1c2ad8447a2 100644
--- a/torch/_dynamo/test_case.py
+++ b/torch/_dynamo/test_case.py
@@ -54,7 +54,7 @@ class TestCase(TorchTestCase):
             config.patch(
                 raise_on_ctx_manager_usage=True,
                 suppress_errors=False,
-                log_compilation_metrics=False,
+                #log_compilation_metrics=False,
             ),
         )
```

**Before this PR:**

```
$ TORCH_LOGS=+torch._utils_internal python test/distributed/test_dynamo_distributed.py TestFakeDistributedSingleProc.test_hf_bert_ddp_inductor 2>&1 | grep BwdCompilationMetrics | awk '{print $7}'
inductor_compile_time_s=1.7937920093536377,
inductor_compile_time_s=4.242283821105957,
inductor_compile_time_s=5.709432125091553,
inductor_compile_time_s=5.759031057357788,
inductor_compile_time_s=5.803919315338135,
inductor_compile_time_s=5.8475987911224365,
inductor_compile_time_s=5.892357110977173,
inductor_compile_time_s=5.935748815536499,
inductor_compile_time_s=5.9808125495910645,
inductor_compile_time_s=6.026893377304077,
inductor_compile_time_s=6.077519416809082,
inductor_compile_time_s=6.121384382247925,
inductor_compile_time_s=6.167155504226685,
inductor_compile_time_s=7.265817880630493,
```

**After this PR:**

```
$ TORCH_LOGS=+torch._utils_internal python test/distributed/test_dynamo_distributed.py TestFakeDistributedSingleProc.test_hf_bert_ddp_inductor 2>&1 | grep BwdCompilationMetrics | awk '{print $7}'
inductor_compile_time_s=1.8151755332946777,
inductor_compile_time_s=2.7222461700439453,
inductor_compile_time_s=1.374084234237671,
inductor_compile_time_s=0.048270463943481445,
inductor_compile_time_s=0.043238162994384766,
inductor_compile_time_s=0.04548001289367676,
inductor_compile_time_s=0.04541802406311035,
inductor_compile_time_s=0.045737266540527344,
inductor_compile_time_s=0.04360318183898926,
inductor_compile_time_s=0.045416831970214844,
inductor_compile_time_s=0.05005931854248047,
inductor_compile_time_s=0.04618215560913086,
inductor_compile_time_s=0.0427088737487793,
inductor_compile_time_s=1.0441086292266846,
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Comment by masnesral** [comment]
@jamesjwu assuming we go with the approach here, I noticed there are other utilities in this file that use compile_id. I think you wrote most or all of them. I wonder if we'd consider changing those as well.

**Comment by jamesjwu** [comment]
Yes, I think we should change those too. In general, I think I would like a single helper function that gets me a "run id" or "compile id" that's unique per inductor compile, and to call it in all relevant places.

**Comment by masnesral** [comment]
Actually @jamesjwu there's a difference in usage here that I didn't catch at first... this PR is changing how we aggregate various timing data. Typically we use the current frame counter as the key, which is incremented by dynamo. So all timing data underneath dynamo (tracing, inductor, triton, etc.) would be aggregated for a given frame. But for backwards, dynamo is has already finished (minus corner case that we're ignoring for now). So these utils were previously using the compile_id as an alternative key _only when compiling the backward_, presumably because the current frame counter is not reliable when we're not "in" dynamo.  But your usages below use compile_id for everything (not frame counter). Given that update, can you double check your advice here?

**Comment by jamesjwu** [comment]
Hmm when I checked, compile id and frame key were always 1-1 in the forwards, and I think frame key is a legacy thing when I asked @ezyang about it. The goal for me was that the compile id was always matching that of tlparse. But maybe I didn't check properly back then for DDP examples in the forward. 

I think I would still say the same thing here: having compile id be the default for forwards and this new id for backwards makes sense for me.

**Comment by masnesral** [comment]
> Hmm when I checked, compile id and frame key were always 1-1 in the forwards

Ok, just experimenting, it seems they're not the same value. Though they may be equally viable as a key for the forward. I'll dig s'more.

**Comment by ezyang** [comment]
> Hmm when I checked, compile id and frame key were always 1-1 in the forwards

Well they're definitely not the same value. But the increment on frame key and compile id all happen at the same place so yes, I think James is right.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Oh yeah, one more thought, since the semantics of fields has changed (to bugfix), it might be helpful to have a dedicated field which you can use to distinguish entries that are before and after the fix)

**Comment by masnesral** [comment]
> it might be helpful to have a dedicated field which you can use to distinguish entries that are before and after the fix)

@ezyang: D64760627

**Comment by masnesral** [comment]
This was fixed a different way in https://github.com/pytorch/pytorch/pull/139849

**Pull request closed without merging**
