### PR TITLE
Support negative indices in ndarray.__getitem__

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #107689
* #107746
* #107711
* #107710
* __->__ #107688
* #107687

In this case, we copy, but this is part of the set of divergences
described in https://github.com/Quansight-Labs/numpy_pytorch_interop/issues/73.

This does not work with dynamic shapes, but it's not clear to me what
would be the best fix

cc @mruberry @rgommers @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

### CODE REVIEW

**Comment by lezcano** [comment]
@ezyang what's the best way to support this for dynamic shapes?

**Review by ezyang — APPROVED** [review]
The reason it doesn't work with dynamic shapes is because Python slice() is dumb and forces an `__index__` call. You just need to rewrite the code to not use slice. This usually means calling some lower level PyTorch API like `tensor.narrow`; you can figure out what the getitem call desugared to by looking at the resulting ops in the graph.

**Comment by lezcano** [comment]
I think the issue here is that I'm just doing an unguarded "if slice.step < 0" within the function. Now, I don't know whether we should start putting guards in the decomposition... that doesn't sound right.

**Comment by ezyang** [comment]
Oh, you have another problem which is that you can't actually call `__getitem__` translation function with ndarray. For this you should probably just do the conversion manually in Dynamo.

If you think my advice is not relevant, you should post the errors.

**Comment by lezcano** [comment]
https://github.com/pytorch/pytorch/pull/107689 calls our custom `__getitem__`. I'll post a more detailed repro tomorrow.

**Pull request closed without merging**
