### PR TITLE
[Dynamo] Replace `torch._dynamo.optimize()` with `torch.compile()` [1/N]

### PR DESCRIPTION
**Pull request by shink**
``torch._dynamo.optimize()`` is wrapped for convenience by ``torch.compile()``.

related commits:

- #139706
- #140238
- #140247
- #140253

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Comment by shink** [comment]
@ezyang Could you please help review this? Should we use `torch.compile()` instead of `torch._dynamo.optimize()` in our codebase?

**Review by jansel — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
