### PR TITLE
Modify repeat_interleave docs to highlight potential overloading

### LINKED ISSUE #99259: torch.repeat_interleave works when there is no input
### 🐛 Describe the bug

```
import torch
arg_1 = torch.randint(0,512,[2], dtype=torch.int64)
res = torch.repeat_interleave(repeats=arg_1,)
print(res)
# res: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,......
```
Above code works, when there is no input tensor. But according to [doc](https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html), `input` is needed，not optional. 

### Versions

pytorch version: 2.0.0+cu118

cc @svekars @carljparker

### PR DESCRIPTION
**Pull request by tfsingh**
Fixes #99259 , drawing to attention that input is optional by putting a variation of the method signature at the top of the file and by modifying the input arguments.

Note that I'm not certain how to get the additional signature at the same level of indentation as the first one, but I think this change does a good job of highlighting the change is optional.

Would be happy to iterate on this if there are any issues.

cc @jbschlosser

### CODE REVIEW

**Review by kit1980 — CHANGES_REQUESTED** [review]
Hm, I look at the docs generated from this PR https://docs-preview.pytorch.org/99650/generated/torch.repeat_interleave.html
I don't see this fixes the original issue of the wrong indentation for the overload at the bottom.
Am I missing something?

**Comment by tfsingh** [comment]
This doesn't seem to be the case when I built the docs, but perhaps I'm missing something too. I think the changes I made do more to position the overloading in a more relevant place (while also changing the params to reflect the optionality of the input argument) as I didn't see other examples of overloads on the outer levels of indentation. I'm very confused as to why the rendered docs don't reflect the changes, has this happened before?

**Review by mikaylagawarecki — COMMENTED** [review]
Yea the changes are oddly not rendering, including those to `input` which should definitely render. rebasing to see whether this helps.

**Comment by tfsingh** [comment]
I think they've rendered correctly now cc @mikaylagawarecki @kit1980

**Review by mikaylagawarecki — COMMENTED** [review]
Yes it renders now! Appreciate the fix but I am hesitant to accept this as it is inconsistent with the documentation for other functions (e.g. [`torch.sum`](https://pytorch.org/docs/stable/generated/torch.sum.html), [` torch.prod`](https://pytorch.org/docs/stable/generated/torch.prod.html?highlight=torch+prod#torch.prod)) that have multiple signatures. For consistency it might be better to document the arguments for the second signature separately at the bottom instead. What do you think of this?

I agree that the indentation problem is still an issue however.

**Comment by tfsingh** [comment]
@mikaylagawarecki I agree, I think consistency is probably the best approach (thank you for the pointers to .sum and .prod). I've updated the docs in a way that I think makes sense, please let me know if you need me to iterate on them!

**Comment by tfsingh** [comment]
I'm also curious if the indentation issue is something you'd like me to take a look at/implement -- I'd be happy to if so.

**Review by mikaylagawarecki — APPROVED** [review]
Thanks @tfsingh , this LGTM!

If you are interested in looking into the indentation issue in a separate PR that would be great :)

**Pull request closed without merging**
