### PR TITLE
Add triton to CI

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #87026
* #87025
* __->__ #86988

### CODE REVIEW

**Review by malfet — APPROVED** [review]
How long does it take to build triton from source?

**Comment by jansel** [comment]
> How long does it take to build triton from source?
110 seconds

**Review by voznesenskym — APPROVED** [review]

**Review by soumith — APPROVED** [review]

**Pull request closed without merging**
