### PR TITLE
[ONNX] remove raw export type

### LINKED ISSUE #52261: Impossible to export ONNX as RAW
## 🐛 Bug

The OperatorExportTypes.RAW export type always fail during ONNX export, no matter how complex or simple the model.

## To Reproduce

1. Copy and run the code below
2. It fails with "RuntimeError: unexpected attribute kind"
3. It won't fail if you comment the operator_export_type line, or set any other export type than RAW

```
import torch
import torch.nn as nn

class SimpleConv(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 8, 3)

    def forward(self, x):
        return self.conv1(x)

import os
import torch.onnx
from torch.onnx import OperatorExportTypes
torch.onnx.export(SimpleConv(),
                  torch.zeros((1,1,16,16)),
                  open(os.devnull,"wb"),
                  verbose=True,
                  operator_export_type=OperatorExportTypes.RAW
                 )
```

The error message comes from here: https://github.com/pytorch/pytorch/blob/v1.7.1/torch/csrc/jit/serialization/export.cpp#L665

## Expected behavior

Proper RAW export as documented here:
https://pytorch.org/docs/stable/onnx.html#raw

## Environment

 - PyTorch 1.7.1
 - Windows 10
 - Miniconda

## Additional context

NB: ONNX RAW export is particularly important for proper PyTorch model graph analysis. The ONNX export verbose provides much more details (comprehensive list of tensor sizes) than the jit trace graph. Hence a working ONNX RAW export would be much appreciated. Other ONNX export types don't match PyTorch modules 1:1.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

### PR DESCRIPTION
**Pull request by garymm**
[ONNX] remove raw export type

It doesn't work in most cases, and I can't see how it would be useful even if it did.

Fixes #52261

### CODE REVIEW

**Comment by garymm** [comment]
@SplitInfinity could you please import this to Phabricator so we can see if it passes FB internal tests?

**Comment by SplitInfinity** [comment]
> @SplitInfinity could you please import this to Phabricator so we can see if it passes FB internal tests?

There is one internal use of the raw export type. Can you provide more detail about the PR (perhaps in the description) so that I can fix it myself internally or provide the context to the owners of this internal code?

**Comment by garymm** [comment]
@SplitInfinity I want to remove it because:

* I don't understand how it could be useful. But perhaps you could help me understand and document this after consulting with the owners of the internal code.
* There are many extremely simple models where it simply doesn't work at all. E.g. #52261, but I have found even simpler ones.

So ideally we'd remove it, OR document what it's good for and its limitations.
As the maintainer of the code I'd prefer to remove it.

Will update the PR description once we get to the bottom of this.

Thanks for your help!

**Comment by SplitInfinity** [comment]
@garymm 

I messaged them, I'll let you know what I find out.

**Comment by SplitInfinity** [comment]
Ok, it seems like the test that breaks is no longer needed. If you are happy with your changes, I can amend them internally to disable these tests and land them.

**Comment by SplitInfinity** [comment]
Ok, internal tests are passing now with my small change. Could you get someone on your team to review this PR?

**Review by BowenBao — APPROVED** [review]
LGTM, thanks for the PR!

**Pull request closed without merging**
