### PR TITLE
Vectorized memory access in TensorIterator GPU loop for 1d contiguous case, without ROCm regression

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Basically https://github.com/pytorch/pytorch/pull/32383, but vectorization disabled on ROCm to avoid regression.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit eda0fc2c:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=eda0fc2c3313314af985870cb0354f2695a582eb).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4355106) pytorch_macos_10_13_py3_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=91687863) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=91687863))
<details>
<summary>
<code>Jan 27 18:14:17 RuntimeError: test_autograd failed!</code>
</summary>

```
Jan 27 18:14:16 Ran 1047 tests in 265.773s 
Jan 27 18:14:16  
Jan 27 18:14:16 FAILED (errors=1, skipped=13, expected failures=1) 
Jan 27 18:14:16  
Jan 27 18:14:16 Generating XML reports... 
Jan 27 18:14:17 Traceback (most recent call last): 
Jan 27 18:14:17   File "test/run_test.py", line 456, in <module> 
Jan 27 18:14:17     main() 
Jan 27 18:14:17   File "test/run_test.py", line 449, in main 
Jan 27 18:14:17     raise RuntimeError(message) 
Jan 27 18:14:17 RuntimeError: test_autograd failed! 
Jan 27 18:14:17 + cleanup 
Jan 27 18:14:17 + retcode=1 
Jan 27 18:14:17 + set +x 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by zasdfgbnm** [comment]
@ngimel This is ready except for the ROCm fail due to `sccache`. I have guarded the vectorized code with `#ifndef __HIP_PLATFORM_HCC__`, so it is not enabled on ROCm. There shouldn't be any perf regression on ROCm any more. In ROCm build, the compiler is still complaining of unable to unroll, but the complaint was for file `SoftMax.hip` and `TriangularOps.hip` which is not related to this PR.

**Comment by ngimel** [comment]
cc @iotamudelta

**Comment by zasdfgbnm** [comment]
ROCm build is fixed by increasing the timeout.

**Comment by zasdfgbnm** [comment]
@iotamudelta Could you check if this PR introduce any regression on ROCm?

**Comment by iotamudelta** [comment]
Still regressed. Not as badly as the previous attempt but still significant.

**Comment by zasdfgbnm** [comment]
@iotamudelta Are you comparing against the master branch with the unrolling, or before the unrolling?

**Comment by iotamudelta** [comment]
`Loops.cuh` is on `5bc44fb6ea65c711c818ea82dc66afee9ad48f78` + changing the `launch_sizes` as my baseline

**Pull request closed without merging**
