### PR TITLE
Added original sources/references and corrected typos for Wishart.py in torch.distribution

### PR DESCRIPTION
**Pull request by jimku9**
@fritzo As discussed, original sources/references are added to the Wishart.py in distributions. Some typos in the error message are corrected.

### CODE REVIEW

**Review by fritzo — APPROVED** [review]
LGTM.

@neerajprad would you be able to merge this?

**Comment by neerajprad** [comment]
Thank you @jimku. Do you mind signing the CLA?

**Comment by jimku9** [comment]
My apologies for not linking the commit to my Github ID and hence the CLA check seems to be prevented even though I have signed the CLA several times. Do I need to re PR with a new commit?

**Pull request closed without merging**
