### PR TITLE
Workaround for super() calls in test_torchinductor_dynamic_shapes

### PR DESCRIPTION
**Pull request by clee2000**
Info about super in dynamic classes:
https://stackoverflow.com/questions/71879642/how-to-pass-function-with-super-when-creating-class-dynamically
https://stackoverflow.com/questions/43782944/super-does-not-work-together-with-type-supertype-obj-obj-must-be-an-i

Calling super(TestCase) actually calls TestCase's parent's functions, bypassing TestCase itself's functions

Mainly doing this because it's making disable bot spam

Test: checked locally and check that https://github.com/pytorch/pytorch/issues/117954 actually got skipped

Logs for `inductor/test_torchinductor_dynamic_shapes.py::TestInductorDynamicCUDA::test_unbacked_index_select_cuda`
https://ossci-raw-job-status.s3.amazonaws.com/log/21083466405
Afaik this PR doesn't actually cause the test to fail, it just surfaces the error since the mem leak check wasn't running previously

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
TIL!  Do you know if `super().setUp()` work instead from this part https://github.com/pytorch/pytorch/blob/main/test/inductor/test_torchinductor_dynamic_shapes.py#L114?

**Comment by clee2000** [comment]
> TIL! Do you know if `super().setUp()` work instead from this part https://github.com/pytorch/pytorch/blob/main/test/inductor/test_torchinductor_dynamic_shapes.py#L114?

I'm pretty sure it will fail with `super(type, obj): obj must be an instance or subtype of type` due to dynamically creating test classes

**Comment by clee2000** [comment]
This PR doesn't actually cause the slow test to fail, it just surfaces the error since the mem leak check wasn't running previously

**Pull request closed without merging**
