### PR TITLE
[jit] support torch._C._get_tracing_state in script

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #23266 [jit] Support nn.GRU in script
* #23249 [jit] Support pack_padded_sequence and pad_packed_sequence
* **#23248 [jit] support torch._C._get_tracing_state in script**
* #23247 [jit] support torch.as_tensor in script

Differential Revision: [D16466588](https://our.internmc.facebook.com/intern/diff/D16466588)

### CODE REVIEW

**Comment by eellison** [comment]
What is the use case for this ?

**Comment by wanchaol** [comment]
> What is the use case for this ?

This is needed to support `pack_padded_sequence`. There're also bunch of internal functions that check if it's in the tracing state, and this can unblock them from scripting.

**Comment by eellison** [comment]
> > What is the use case for this ?
> 
> This is needed to support `pack_padded_sequence`. There're also bunch of internal functions that check if it's in the tracing state, and this can unblock them from scripting.

You could also move that call to a function with `torch.jit.ignore`. I think it would be better to advocate people to reuse existing apis then add to a list of special cases

**Comment by wanchaol** [comment]
> > > What is the use case for this ?
> > 
> > 
> > This is needed to support `pack_padded_sequence`. There're also bunch of internal functions that check if it's in the tracing state, and this can unblock them from scripting.
> 
> You could also move that call to a function with `torch.jit.ignore`. I think it would be better to advocate people to reuse existing apis then add to a list of special cases

I tried your approach, it unfortunately not working because of the `torch.jit` and `torch.nn` initialization order issue... I think this could considered to be an `op` as we already have different special ops.

**Comment by driazati** [comment]
You can do `@torch._jit_internal.ignore` (the one in `jit` just aliases this), but I don't see how that would help since the function would still be run (even if it returns `False` every time), so places that use it couldn't be exported.

**Review by eellison — APPROVED** [review]

**Pull request closed without merging**
