### PR TITLE
Move the CUDA implementation of log10 to ATen.

### LINKED ISSUE #24587: Migrate `log10` and `log10_` from the TH to Aten (CUDA)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #26923 Move the CUDA implementation of log1p to ATen.
* #26769 Move the CUDA implementation of log2 to ATen.
* **#26733 Move the CUDA implementation of log10 to ATen.**

Close #24587

Differential Revision: [D17606981](https://our.internmc.facebook.com/intern/diff/D17606981)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
Please rebase

**Comment by xuhdev** [comment]
Done!

**Comment by VitalyFedyunin** [comment]
ROCM rests failures seems to be related `FAIL: test_DoubleTensor_log10 (__main__.TestCuda)`

**Comment by xuhdev** [comment]
Will look into this on Monday. Thanks!

**Comment by xuhdev** [comment]
@VitalyFedyunin Should be resolved now. It turned out to be a dumb typo in the CUDA code

**Review by VitalyFedyunin — APPROVED** [review]

**Pull request closed without merging**
