### PR TITLE
[AI Accelerators] GPU Unit test for at::_scaled_dot_product_self_attention

### PR DESCRIPTION
**Pull request by hefeiumich**
Summary:
- 1. Create a seperate folder for cuda unit test: fbcode/caffe2/test/RE_tests
         - 2. Put (write) cuda unit test, TARGET file and dependencies in above folder
         - 3. Update contbuild config file accordingly:
         - 4. Opt out of GPU sections removal for CUDA (GPU) tests

Test Plan:
1. arc lint for all the newly added files (ok No lint issues):
              fbcode/caffe2/test/RE_tests/test_cuda_sdpa.py
              fbcode/caffe2/test/RE_tests/TARGETS
              fbcode/contbuild/configs/pytorch_core_cuda
           2. Remote test excution requesting CUDA:
              buck2 test @//mode/dev-nosan -c test.external_runner=tpx :test_cuda_sdpa -- --use-remote-execution --force-tpx
              10 tests passed: 
[
](https://www.internalfb.com/intern/testinfra/testconsole/testrun/1688849987899027/)

           3. Local test is skipped because config set it up to skip local test as CUDA doesn't work with ASAN:
              buck2 test :test_cuda_sdpa
              10 tests skipped:  [
](https://www.internalfb.com/intern/testinfra/testconsole/testrun/3377699845391150/)
Differential Revision: D39276148

### CODE REVIEW

**Comment by janeyx99** [comment]
Is the intention here to add 2 test files to open source testing? Do you know how long these new files take to run? test_torch here looks redundant to our other existing tests.

**Comment by hefeiumich** [comment]
> Is the intention here to add 2 test files to open source testing? Do you know how long these new files take to run? test_torch here looks redundant to our other existing tests.

Hi Jane, test_cuda_sdpa.py is the intended new test only. test_torch.py is the dependencies file for test_cuda_spda.py. I don't plan to run test_torch again. test_cuda_sdpa takes about 2-3 minutes to complete based on buck2 test. I don't plan to run test_torch again here, and didn't specify it to run.

**Comment by hefeiumich** [comment]
> Oh, I don't think you want to include test_torch changes then--it should not be a dependency for the new tests you're adding.

Why test_torch.py should not be a dependency for the new test? This is what I saw from previously developed unit test files. They did the same thing, using test_torch.py as dependency for python library.

**Comment by hefeiumich** [comment]
> > Oh, I don't think you want to include test_torch changes then--it should not be a dependency for the new tests you're adding.
> 
> Why test_torch.py should not be a dependency for the new test? This is what I saw from previously developed unit test files. They did the same thing, using test_torch.py as dependency for python library. Thank you very much for your questions. Sorry, I indeed have many things not understood. It was my third week bootcamp task. Will it be better if there is anytime for a quick chat?

**Comment by hefeiumich** [comment]
> Oh, I don't think you want to include test_torch changes then--it should not be a dependency for the new tests you're adding.

I got your point now. I could just import the library directly without using test_torch.py. Thank you!

**Pull request closed without merging**
