### PR TITLE
[inductor] Add an aot_inductor class in inductor config

### PR DESCRIPTION
**Pull request by desertfire**
Summary: Introduce an aot_inductor class to group AOTInductor specific configs

Differential Revision: D48880684

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by frank-wei — APPROVED** [review]
LGTM

**Comment by huydhn** [comment]
@pytorchbot drci

(Please ignore this comment, I'm trying to debug Dr.CI a bit)

**Pull request closed without merging**
