### PR TITLE
[DataPipe] Fix deepcopy filehandle for Mapper and in-place modification for IterableWrapper

### LINKED ISSUE #65221: [DataPipe] Mapper DataPipe should not deepcopy when index specified
## 🐛 Bug

I was adding the following line to prevent in-place modification of the data from source DataPipe. 
https://github.com/pytorch/pytorch/blob/d37c02be08dfc022daf2ee1ddeda2a37b4551cac/torch/utils/data/datapipes/iter/callable.py#L102-L103

But, in fact, this would break when input includes file handle, because file handle can not be serialized.

So, in order to support file handle, we need to remove deepcopy. But, for the sake of preventing in-place modification, we need to add documentation to wiki about remove data attached to DataPipe instance. We prefer using iterator to generate data.

Then, we need to also change the `IterableWrapper` to do a `deepcopy` if possible. https://github.com/pytorch/pytorch/blob/a49907f984670781a718ef6aa0046709886eae5a/torch/utils/data/datapipes/iter/utils.py#L12-L17

cc @VitalyFedyunin @ejguan

### PR DESCRIPTION
**Pull request by ejguan**
Fixes #65221

Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #65220

- Remove deepcopy from Mapper to support file handles
- Convert `IterableWrapper` to deepcopy iterable instance within each iterator to prevent in-place modification (different data per epoch)
- Convert `IDP` to `IterableWrapper` in test_datapipe.py
- Refine the variable names (prevent using `dp` that is module reference)

Differential Revision: [D31021886](https://our.internmc.facebook.com/intern/diff/D31021886)

### CODE REVIEW

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31021886).

**Review by pmeier — APPROVED** [review]
I was mostly concerned about the deepcopy in `Mapper`, so for that this PR LGTM!

One question though: I was under the impression that `IterableWrapper`'s purpose was to serve as datapipe source that start from an iterable. What if deepcopy of an iterable is not desired since it would be to expensive? Should we make this a flag on `IterableWrapper` that can be turned off?

**Comment by ejguan** [comment]
> One question though: I was under the impression that `IterableWrapper`'s purpose was to serve as datapipe source that start from an iterable. What if deepcopy of an iterable is not desired since it would be to expensive? Should we make this a flag on `IterableWrapper` that can be turned off?

When we use `IterableWrapper`, the iterable object won't be a giant array then it's fine to do deepcopy. I am more afraid of user would reach the unexpected behavior that the source data would be modified.
For better flexibility, I think adding a flag makes sense, but I would prefer making `deeepcopy` as default and raise warning when users explicitly disable `deepcopy` option.

**Comment by pmeier** [comment]
> For better flexibility, I think adding a flag makes sense, but I would prefer making `deeepcopy` as default and raise warning when users explicitly disable `deepcopy` option.

+1 for keeping deepcopy as default, but why do you want to raise a warning if a user explicitly turns it off? IMO, the warning should be emitted if the user omitted the `deepcopy` flag and the deepcopy fails.

**Comment by ejguan** [comment]
> > For better flexibility, I think adding a flag makes sense, but I would prefer making `deeepcopy` as default and raise warning when users explicitly disable `deepcopy` option.
> 
> +1 for keeping deepcopy as default, but why do you want to raise a warning if a user explicitly turns it off? IMO, the warning should be emitted if the user omitted the `deepcopy` flag and the deepcopy fails.

Understood. Users should understand it if they explicitly turn it off. I will add inline doc to explain it.

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31021886).

**Pull request closed without merging**
