### PR TITLE
Make Context to be Device-agnostic Step by Step (2/N)

### PR DESCRIPTION
**Pull request by fffrog**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136526

----

- add new method(getDefaultGenerator, getNewGenerator) into AcceleratorHooksInterface

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Review by EikanWang — APPROVED** [review]
LGTM

**Comment by EikanWang** [comment]
@FFFrog , regarding the XPU failures, they are due to a particular pull request that breaks Intel GPU Inductor test cases because Intel GPU Inductor test cases are not enabled in CI by default. It is not a regression regarding the Intel GPU Inductor. But we need to refine the test case a little bit. In terms of your PR, I think you can merge it w/ the fixing that latest torch-xpu-ops commit pin if xpu-related cases are the only failures.

**Comment by ezyang** [comment]
1/N has landed, please rebase this stack on main

**Comment by FFFrog** [comment]
> 1/N has landed, please rebase this stack on main

Done lol.

**Comment by FFFrog** [comment]
@ezyang This pr had been reverted, but I am not sure which introduced BC or commit conflicts.

**Comment by ezyang** [comment]
rebase it on master and I'll import it, the pr doesn't seem to be clean anymore

**Comment by FFFrog** [comment]
> rebase it on master and I'll import it, the pr doesn't seem to be clean anymore

Have rebased it lol

**Comment by laithsakka** [comment]
you might want to rebase and update
WIN: benchmark ('update_hint_regression', 'compile_time_instruction_count') failed, actual result 1739251632 is -3.12% lower than expected 1795333141 ±2.00% please update the expected results. 

?

**Comment by laithsakka** [comment]
you might want to rebase and update this if it persist. 

WIN: benchmark ('update_hint_regression', 'compile_time_instruction_count') failed, actual result 1739251632 is -3.12% lower than expected 1795333141 ±2.00% please update the expected results. ?

on the latest run the test was disabled due to some infra issue that is fixed
2024-10-31T16:55:48.9373666Z ModuleNotFoundError: No module named 'boto3'

**Comment by FFFrog** [comment]
> you might want to rebase and update this if it persist.
> 
> WIN: benchmark ('update_hint_regression', 'compile_time_instruction_count') failed, actual result 1739251632 is -3.12% lower than expected 1795333141 ±2.00% please update the expected results. ?
> 
> on the latest run the test was disabled due to some infra issue that is fixed 2024-10-31T16:55:48.9373666Z ModuleNotFoundError: No module named 'boto3'

So sorry for the late response, have rebased it now.

**Comment by ZainRizvi** [comment]
@pytorchbot revert -c ghfirst -m "This fails to build internally. See D65604944 for more details"

@ezyang could you please help get this PR merged? It seems to be missing internal imports.

The error looks like:
```
ATen/detail/AcceleratorHooksInterface.h:67:7: error: unknown type name 'C10_UNUSED'
   67 |       C10_UNUSED DeviceIndex device_index = -1) const {```

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D65754110).

**Comment by ezyang** [comment]
@FFFrog the C10_UNUSED macro is deprecated replace it with [[maybe_unused]] and I can land you

**Comment by ezyang** [comment]
See also https://github.com/pytorch/pytorch/pull/140302

**Comment by FFFrog** [comment]
> @FFFrog the C10_UNUSED macro is deprecated replace it with [[maybe_unused]] and I can land you

So sorry for the late respone, I have replaced the C10_UNUSED with [[maybe_unused]], please help to reland it.

**Pull request closed without merging**
