### PR TITLE
[DTensor] Register replication strategy for a few upsampling interpolate ops

### PR DESCRIPTION
**Pull request by wz337**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137201

To unblock Llama 3.2 vision's use case to resize positional embeddings for fine-tuning. Context in [workplace post](https://fb.workplace.com/groups/319878845696681/permalink/1271172040567352/).

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wconstab @d4l3k @c-p-i-o @tianyu-l

### CODE REVIEW

**Review by XilunWu — APPROVED** [review]
Replicate strategy should be fine for now.

**Comment by awgu** [comment]
How would the replicated DTensor get converted back to sharded in the state dict load flow?

**Comment by wz337** [comment]
> How would the replicated DTensor get converted back to sharded in the state dict load flow?

Ah. Thanks for raising it. We won't be able to define the layout for the output, since it is determined by the next op. 

In order to shard it back, the user would have to do a ```DTensor.from_local(..., placements=[Replicate(]).redistribute(placements=[Shard(0)])```. This way there is no communication compared with using `distribute_tensor()`.

**Pull request closed without merging**
