### PR TITLE
[RFC] add is_python_module to CppExtension/CUDAExtension

### PR DESCRIPTION
**Pull request by t-vi**
So this would add a keyword argument `is_python_module` to CppExtension/CUDAExtension.
This would be handy to build extensions and non-Python custom op libraries and have the latter not get the python version bits as part of the filename. (In https://github.com/pytorch/vision/pull/1267 we tried to get rid of the funny filename but gave up.)

It also unifies the CppExtension/CUDAExtension linking (possibly adding options in the pure C++ case), I'm not 100% sure this is acceptable, but the duplication did feel wrong.

### CODE REVIEW

**Comment by ezyang** [comment]
The desired feature seems reasonable. Anyone else have comments?

**Review by soumith — APPROVED** [review]
looks great!

**Review by soumith — CHANGES_REQUESTED** [review]
test failures are legit

**Comment by t-vi** [comment]
In addition to fixing the failures, I don't yet have a good plan to load those modules - is there a mechanism to get the file extension of the modules (.so/.dll/.dylib) from somewhere?

**Comment by ezyang** [comment]
> is there a mechanism to get the file extension of the modules (.so/.dll/.dylib) from somewhere?

I don't know if we have some existing code that lets you get this info (@peterjc123, maybe you know?) but generally it's fine to case over the platform to do this determination.

**Comment by peterjc123** [comment]
The name of the generated binary could be retrieved through `self.get_ext_filename(ext_name)` when `self` is an instance that inherits `build_ext`.

**Comment by t-vi** [comment]
Well, that's at compile time. For loading it would be neat to have the extension at runtime. But I'll probably try the casing route until I know better... :)

**Comment by t-vi** [comment]
Looking into the Python tooling needed to do this makes me miserable. So I'll probably not fix it.

**Pull request closed without merging**
