### PR TITLE
make sure windows tests get triggered

### PR DESCRIPTION
**Pull request by mingbowan**
we prefer "_" over "-" in build names, so change checks in test script

### CODE REVIEW

**Comment by suo** [comment]
Will this not break the jenkins windows tests?

**Comment by mingbowan** [comment]
good point! let me rename new test

**Review by ezyang — APPROVED** [review]
This dashes underscores thing is a disaster. We should probably just make everything uniformly underscores... would require a lot of faffing about though.

**Comment by mingbowan** [comment]
agreed. we should make this a rule, esp. for reviewers.

**Pull request closed without merging**
