### PR TITLE
[dynamo x fsdp] Simplify stream logic handling

### PR DESCRIPTION
**Pull request by voznesenskym**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #103102
* #103386
* #103456
* #103450
* #103445

cc @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78

### CODE REVIEW

**Review by awgu — APPROVED** [review]
LGTM!

**Review by rohan-varma — COMMENTED** [review]
Is the motivation of converting it from a dict to explicit streams to make tracing easier?

**Comment by voznesenskym** [comment]
> Is the motivation of converting it from a dict to explicit streams to make tracing easier?

That and this is just better in the sense that if you have a finite number of things, you can avoid hashing k extra times, and this is also easier to read. Its strictly better.

**Comment by voznesenskym** [comment]
I effed up rebasing this, will redo.

**Pull request closed without merging**
