### PR TITLE
Improved backward tracking and attribution, fixed typing for python < 3.10

### LINKED ISSUE #129390: DISABLED test_tracker_multi_group_eager (__main__.TestTrackerFullyShard1DTrainingCore)
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22distributed%2F_tools%2Ftest_fsdp2_mem_tracker.py%3A%3ATestTrackerFullyShard1DTrainingCore%3A%3Atest_tracker_multi_group_eager%22%5D)).

This is a new test coming from https://github.com/pytorch/pytorch/pull/125323, it's failing on ROCm distributed job.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @jataylo @hongxiayang @naromero77amd @pragupta @jerrymannil @xinyazhang @dllehr-amd

### LINKED ISSUE #129692: DISABLED test_tracker_non_root_forward_backward (__main__.TestTrackerFullyShard1DTrainingCore)
Platforms: rocm

This test was disabled because it is failing on main branch ([recent examples](https://torch-ci.com/failure?failureCaptures=%5B%22distributed%2F_tools%2Ftest_fsdp2_mem_tracker.py%3A%3ATestTrackerFullyShard1DTrainingCore%3A%3Atest_tracker_non_root_forward_backward%22%5D)).

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### PR DESCRIPTION
**Pull request by sanketpurandare**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #129400

For #125323 
* Fixes typing for python < 3.10
* Fixes #129390
* Fixes #129692 

For #124688 
* Improved attribution by registering `register_hook` and `post_accumulate_grad_hook` on params.
* Fixed pre-mature per module bw peak state initialization for AC.
* This improves per-module stats, global `peak_mem` was already accurate and remains unaffected.

For #128508 
* When AC is applied to a `mod (nn.Module)` the backward order of execution is `pre-bw -> pre-fw -> post-fw -> post-bw`. Since the `ModTracker` maintains the `parents` attribute as set, the `post-fw` during backward was prematurely removing it from parents.
* With the fix we now maintain a per-module counter and only remove a module from `parents` when its counter goes to 0.
* Added tests to ensure this.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

### CODE REVIEW

**Comment by awgu** [comment]
Should we separate the typing changes?

**Comment by sanketpurandare** [comment]
> Should we separate the typing changes?

The other changes also affect the `FSDPMemTracker`, hence running combined tests for them will ensure that we won't break CI again.

**Review by awgu — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Pull request closed without merging**
