### PR TITLE
Nvfuser code bump 12 5

### PR DESCRIPTION
**Pull request by jjsjann123**
Things added in this PR that requires review:
1. cuLaunchCooperativeKernel driver API added
aten/src/ATen/cuda/detail/LazyNVRTC.cpp
aten/src/ATen/cuda/nvrtc_stub/ATenNVRTC.h

nvfuser code update:
1. perf turning on codegen scheduler that improves performance.
2. permutation support has been extended beyond contiguous/channels-last. (The improvements could be observed on PW benchmark)

Things reverted from local changes:
1. aten::gelu with approximation
2. local changes that is upstreamed in PR #68804

### CODE REVIEW

**Comment by ngimel** [comment]
cuLaunchCooperativeKernel looks fine to me

**Comment by jjsjann123** [comment]
Sounds great, can we import this to start the CI pipeline :pray:

**Comment by ngimel** [comment]
Sorry, I'm not the one handling those.

**Comment by jjsjann123** [comment]
Since we got Natalia confirming changes outside of codegen/nvfuser, can we start the import & internal CI to work towards a landing?

cc'ing @wconstab to track the status of `aten::_softmax` parsing for LTC.

**Review by ngimel — APPROVED** [review]
Approving cuLaunchKernel related changes.

**Pull request closed without merging**
