### PR TITLE
Remove ExclusivelyOwned from register_dispatch_key

### LINKED ISSUE #106790: Issue when throwing errors from python decompositions
### 🐛 Describe the bug

When an operation is intercepted in the c++ code in pytorch the outputs a created as ExclusivelyOwned<at::Tensor>s. Later on when it dispatches back to python for the decomposition these tensors have their ownership shared with python. In a normal use case the exclusively owned tensor is released and it's value returned as a non-exclusively owned tensor from the operation. However if the python decomposition throws an error the ExclusivelyOwned wrapper destroys the at::Tensor leading to a python reference to a tensor which isn't alive (and meaning pytorch falls over in debug mode). I can see two potential fixes for this:
Attempt to destroy any tensors in python when returning from a decomposition wrapper (I don't actually know how to do this)
Get rid of the ExclusivelyOwned wrapper for outputs in pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp (perhaps there are other places this would need to be done too).

The following should reproduce my issue however it doesn't get called from C++ for the cpu key. Does anyone know of an op that gets redispatched in c++ on the CPU? I reckon I can make a reproducer from that.
```
import torch

def clamp_tensor(self, min=None, max=None, *, out):
    print("custom clamp")
    if self.dtype is torch.bool:
        raise Exception()
    self.copy_(out)
    if min is not None:
        out = torch.maximum(out, min)
    if max is not None:
        out = torch.minimum(out, max)
    return out

_aten_lib = torch.library.Library("aten", "IMPL")
_aten_lib.impl("clamp.Tensor_out", clamp_tensor, "CPU")

out = torch.empty((), dtype=torch.bool)
print(torch.clamp(torch.tensor(True), min=torch.tensor(False), max=torch.tensor(False), out=out))
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git232b96b
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: 14.0.6 (https://github.com/conda-forge/clangdev-feedstock ceeebe884c3cfd7160cf5a43e147f94439fafee3)
CMake version: version 3.23.3
Libc version: glibc-2.35

Python version: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          60
On-line CPU(s) list:             0-59
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7742 64-Core Processor
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              30
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4491.56
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr wbnoinvd arat npt nrip_save umip rdpid arch_capabilities
Virtualization:                  AMD-V
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.9 MiB (30 instances)
L1i cache:                       1.9 MiB (30 instances)
L2 cache:                        15 MiB (30 instances)
L3 cache:                        16 MiB (1 instance)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-29
NUMA node1 CPU(s):               30-59
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] torch==2.1.0a0+git232b96b
[pip3] torchvision==0.16.0.dev20230730+cpu
[conda] numpy                     1.25.2          py310ha4c1d20_0    conda-forge
[conda] torch                     2.1.0a0+git232b96b          pypi_0    pypi
[conda] torchvision               0.16.0.dev20230730+cpu          pypi_0    pypi

cc @ezyang @gchanan @zou3519 @bhosmer @smessmer @ljk53 @bdhirsh @msaroufim @wconstab @anijain2305

### PR DESCRIPTION
**Pull request by Anstow**
This fixes a bug that could occur with python decompositions.

When an operation is intercepted in the c++ code in pytorch the outputs a created as `ExclusivelyOwned<at::Tensor>`s. Later on when it dispatches back to python for the decomposition these tensors have their ownership shared with python. In a normal use case the exclusively owned tensor is released and it's value returned as a non-exclusively owned tensor from the operation. However if the python decomposition throws an error the `ExclusivelyOwned` wrapper destroys the `at::Tensor` leading to a python reference to a tensor which isn't alive (and meaning pytorch falls over in debug mode).

Note this will be a performance hit when handling errors.

Fixes #106790

### CODE REVIEW

**Comment by zou3519** [comment]
This sounds like pyobject preservation/resurrection, so requesting review from @ezyang

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@Anstow I need you to rebase this PR for me

**Comment by ezyang** [comment]
sorry, can you give maintainers rights to update your branch? I think you hit another bad master commit again, need another rebase

**Comment by Anstow** [comment]
I'll ask for permissions. In the meantime I've rebased the branch again

**Comment by Anstow** [comment]
Would you like me to rebase again!

**Pull request closed without merging**
