### PR TITLE
[14/N] Fix clang-tidy warnings in aten/src/ATen 

### PR DESCRIPTION
**Pull request by cyyever**
Follows #133807

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
It seems like you did double code size here though :P

**Comment by cyyever** [comment]
> It seems like you did double code size here though :P

It is interesting. Each time we use if constexpr, the code size will be doubled...

**Pull request closed without merging**
