### PR TITLE
[fake_impls] Fix seed/offset device for attention kernels

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #120839

1) Fix fake_impls to return the correct device for these attention
   kernels.
2) Remove special-casing and test file xfails

### CODE REVIEW

**Review by drisspg — APPROVED** [review]
🚀

**Comment by davidberard98** [comment]
ah nice, catching more amd errors now that we unskip these tests!

**Comment by drisspg** [comment]
One other thing I forgot to mention is that these tensors will live on cpu during normal execution but if we are using Cuda graphs then they will live on gpu, have no idea how this should be expressed in the fake impl

**Pull request closed without merging**
