### PR TITLE
Add duplicate parameter warning to optimizers in C++ API

### PR DESCRIPTION
**Pull request by mariosasko**
Adds duplicate parameter warning to the optimizers in C++ API.

### CODE REVIEW

**Comment by glaringlee** [comment]
@mariosasko saw u closed this PR, let me know if you need help on this.

**Comment by mariosasko** [comment]
@glaringlee In Python API, if the same parameter appears twice in the same param group the warning gets raised (relevant PR #41597). I would like to do the same for C++ API. 

Is it possible to do some sort of identity check (the same memory address) between Tensors in C++ API. My knowledge of C++ is  limited, but it seems we need pointers for that and OptimizerParamGroup.params() returns Tensors (`std::vector<Tensor>`), not pointers to Tensors(`std::vector<Tensor*>`)?

**Comment by glaringlee** [comment]
@mariokostelac 
Tensor itself is actually a wrapper to a storage pointer. No need to return `std::vector<Tensor*>`.
eg. If you have `Tensor a` and you do `Tensor b = a`, b is actually point to the same storage as `a`.
I looked at your previous code. You were trying to create a `set` of tensor, I guess your purpose is to filter out the duplicated tensor, but in c++, `set` will sort the item in it, so you need to have a `operator <` implemented for Tensor which is not the case for class Tensor. What you can do is to use `std::unordered_set`, it will filter out the duplicated tensor without any problem IMO.

**Comment by glaringlee** [comment]
@mariosasko It seems Tensor is not hashable as well, unordered_set can not be used directly, sry, I should check first. I think in this case, there might be no easy way to check this without just compare them one by one.

**Comment by mariosasko** [comment]
@glaringlee Thank you for helping me with this PR. 

In Pytorch >1.7, if you do smth like this:
```python
x = torch.randn(3, 3, requires_grad=True)
y = x
optim.SGD([x, y], lr=0.1)
```
you get a warning about duplicate parameters, because x and y **point to the same object** i.e. x is y (we don't care about the actual values or semantic equality)

In C++ API, I'm not sure if it's valid to compare only storages, e.g what about this (in Python API):
```python
x = torch.randn(3, 3)
y = x.view(-1)
```
Here x and y should share the same storage, but they don't actually point to the same objects. Maybe this is not the best example, since y isn't a leaf node, it can't be passed to the optimizer. So my question is _is it enough to compare only storages_?

This is why I mentioned pointers earlier, because I'm interested whether they point to the same object or not. In Python, there is the notion of names that point to some objects. In C++, if we use variables (stack-allocated), and do `Tensor a = b`, the semantics are somewhat different so I'm not exactly sure what to compare in that case to forbid putting a and b in the same optimizer group.

**Comment by mariosasko** [comment]
@glaringlee Ready for review.

**Pull request closed without merging**
