### PR TITLE
Add ccol_indices and row_indices methods.

### PR DESCRIPTION
**Pull request by pearu**
Implements Proposal 1 from https://github.com/pytorch/pytorch/issues/76638

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #77512
* #77508
* #77504
* __->__ #77503

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]
Great! Thanks @pearu!

**Comment by cpuhrsch** [comment]
Related to this: We'll still need to update [_tensor_str.py](https://github.com/pytorch/pytorch/blob/master/torch/_tensor_str.py#L363-L392) for CSC and BSC. It might be worthwhile adding smoke tests for printing sparse tensors.

**Comment by pearu** [comment]
> Related to this: We'll still need to update [_tensor_str.py](https://github.com/pytorch/pytorch/blob/master/torch/_tensor_str.py#L363-L392) for CSC and BSC. It might be worthwhile adding smoke tests for printing sparse tensors.

This is addressed in https://github.com/pytorch/pytorch/pull/77530 .

**Pull request closed without merging**
