### PR TITLE
Add Half support for aminmax on CPU

### PR DESCRIPTION
**Pull request by CaoE**
Add Half support for aminmax on CPU.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by CaoE** [comment]
@mruberry Could you please review this PR ? Thanks.

**Comment by CaoE** [comment]
@kulinseth Could you please review this PR ? Thanks.

**Comment by CaoE** [comment]
@ngimel Could you please review this PR ? Thank you.

**Comment by CaoE** [comment]
@cpuhrsch Could you please review this PR ? Thank you.

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
