### PR TITLE
Fix linspace dtype replacement in docs

### LINKED ISSUE #81370: Incorrect type replacement in torch.linspace docs
### 📚 The doc issue

See the [linspace](https://pytorch.org/docs/1.12/generated/torch.linspace.html) documentation. The type of the `dtype` parameter is listed as "torch.dpython:type".

I tracked this down to [this line of code](https://github.com/pytorch/pytorch/blob/v1.12.0/docs/source/conf.py#L649) but this code has been there since the beginning of time (https://github.com/pytorch/pytorch/pull/400, https://github.com/pytorch/pytorch/pull/457, https://github.com/pytorch/pytorch/commit/58a88d1ac053d009111d09eb32f88ea66d7285df).

The docs first break with the 1.9.0 release, and are still broken on master.

### Suggest a potential alternative/fix

Is `patched_make_field` still needed in Sphinx 5? Sphinx has changed quite a bit since Sphinx 1.5 when this [was written](https://stackoverflow.com/questions/31784830/sphinx-ivar-tag-goes-looking-for-cross-references/41184353#41184353).

We could try something like this to fix it:
```python
types = ['int', 'long', 'float', 'bool', 'type']
for type in types:
    if typename == type:
        typename = 'python:' + type
```
This checks the entire string instead of just partial strings. Will submit a PR to try this solution.

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #81370

### CODE REVIEW

**Comment by adamjstewart** [comment]
Any idea why "Python docs build was skipped"?

**Comment by ngimel** [comment]
Doc build errors are real
```
/opt/conda/lib/python3.7/site-packages/torch/__init__.py:docstring of torch._VariableFunctionsClass.repeat_interleave:: WARNING: more than one target found for cross-reference 'int': torch.Tensor.int, torch._TypedStorage.int
```

**Comment by adamjstewart** [comment]
Alright, that fixes [torch.linspace](https://docs-preview.pytorch.org/81371/generated/torch.linspace.html#torch.linspace).

However, I'm not sure if this is a complete solution. Previously, things like `torch.dtype` would be replaced by `torch.dpython:type`, but this still doesn't cover a situation like `torch.int` which would be replaced by `torch.python:int`. Let me see if I can get something safer working.

**Comment by adamjstewart** [comment]
Alright, latest commit should skip both `torch.dtype` AND `torch.int` during replacement. Last remaining question is whether or not this causes a significant slowdown in doc generation time. We may be able to compile the regex higher up in the code to speed things up.

**Comment by adamjstewart** [comment]
Okay, comparing https://github.com/pytorch/pytorch/runs/7331032532 to https://github.com/pytorch/pytorch/runs/7311634860, it seems like there is no change in the time it takes to build the docs (this PR is actually 5 sec faster, prob noise). So this PR should now be good to go.

**Comment by adamjstewart** [comment]
@ngimel can you review this when you get a chance?

**Review by ngimel — APPROVED** [review]
Awesome, thanks!

**Pull request closed without merging**
