### PR TITLE
Update jvp to support symbolic execution.

### PR DESCRIPTION
**Pull request by guilhermeleobas**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #121830
* #121665
* #121410
* #121254
* __->__ #120338

Previously, all jvp tests under dynamo/test_dynamic_shapes would fail because symbolic execution wasn't supported in some autograd functions.

List of changes:
- Update`_has_same_storage_numel` to use `sym_nbytes`
- Symintify `_efficientzerotensor_meta`
- Introduce `empty_generic_symint` with the first argument `size` as symbolic integer
- Update gen_variable_type.py script to call the symint version of zeros_fn function (zeros_symint / _efficientzerotensor_symint)
- Update `has_same_meta` to call `sym_*` functions

cc @zou3519 @Chillee @samdow @kshitij12345 @janeyx99 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @aakhundov

### CODE REVIEW

**Review by soulitzer — APPROVED** [review]

**Comment by guilhermeleobas** [comment]
> @pytorchbot revert -m "lots of breakages in pull jobs, checking if reverting this one will help" -c weird

@jeanschmidt, was this PR that broke CI? Am I free to try to merge it again in the near future?

**Comment by jeanschmidt** [comment]
sure, lets wait to see if this was the one. For now most jobs are red

**Comment by guilhermeleobas** [comment]
Thanks for letting me know. Can I revert it now or I need to wait the bot to finish merging it first?

**Pull request closed without merging**
