### PR TITLE
Enable BLIS from the FLAME project as a BLAS choice.

### PR DESCRIPTION
**Pull request by iotamudelta**
BLIS is AMD's official recommendation for BLAS.

Mimicks my ancient
https://gitlab.kitware.com/cmake/cmake/commit/f5bc78263e15f07fc1fed15d970d7ecf9e84f7cc
in cmake upstream

BLIS WWW: https://github.com/flame/blis

### CODE REVIEW

**Review by bddppq — COMMENTED** [review]
Looks reasonable to me. Do you plan to add a CI job to test it?

**Comment by bddppq** [comment]
CI failure is related to a master breakage earlier today, it was later reverted. Could you rebase?

**Comment by iotamudelta** [comment]
@bddppq yeah, we can add a CI target (assuming there is enough capacity)

Something went wrong in my rebase, sorry...

**Comment by iotamudelta** [comment]
@bddppq if this could go in, my idea is to also enable libflame (the companion LAPACK) and then use BLIS+libflame on the ROCm CI instead of the currently used OpenBLAS.

**Comment by iotamudelta** [comment]
@bddppq ping :-)

**Review by bddppq — APPROVED** [review]

**Pull request closed without merging**
