### PR TITLE
Make torch::jit::module movable

### PR DESCRIPTION
**Pull request by cyyever**
This PR makes torch::jit::module movable to improve performance.

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @huydhn

### CODE REVIEW

**Comment by cyyever** [comment]
@huydhn This change may be related to reversion of #113608, import and check?

**Comment by huydhn** [comment]
Sure, let me import this

**Comment by huydhn** [comment]
Sorry, let me take a look today, last week was meta code freeze, so no diff was landed

**Comment by huydhn** [comment]
I have been able to submit a diff to fix the internal build, so this can be landed now

**Review by huydhn — APPROVED** [review]

**Comment by cyyever** [comment]
@huydhn Thank you, can I try to reland PR https://github.com/pytorch/pytorch/pull/113608?

**Pull request closed without merging**
