### PR TITLE
Avoid dynamic dispatch inside the omp loop in AdaptiveAvgPool2d

### PR DESCRIPTION
**Pull request by crcrpar**
This PR changes CPU implementation of `AdaptiveAveragePool2D` by
- move dispatch to outside the OpenMP loop
- support fp16

### CODE REVIEW

**Comment by zou3519** [comment]
@crcrpar tests are failing:
```
May 10 16:11:22 ======================================================================
May 10 16:11:22 FAIL: test_nn_adaptive_avg_pool2d (__main__.TestJitGeneratedFunctional)
May 10 16:11:22 ----------------------------------------------------------------------
May 10 16:11:22 Traceback (most recent call last):
May 10 16:11:22   File "test_jit.py", line 14058, in wrapper
May 10 16:11:22     return fn(*args, **kwargs)
May 10 16:11:22   File "test_jit.py", line 14108, in do_test
May 10 16:11:22     run_test()
May 10 16:11:22   File "test_jit.py", line 14100, in run_test
May 10 16:11:22     check_against_reference(self, script_fn, fn, f_args_variable, kwargs_variable, no_grad=no_grad)
May 10 16:11:22   File "test_jit.py", line 13357, in check_against_reference
May 10 16:11:22     self.assertEqual(grads, grads_test)
May 10 16:11:22   File "/var/lib/jenkins/workspace/test/common_utils.py", line 498, in assertEqual
May 10 16:11:22     self.assertEqual(x_, y_, prec, message)
May 10 16:11:22   File "/var/lib/jenkins/workspace/test/common_utils.py", line 483, in assertEqual
May 10 16:11:22     assertTensorsEqual(x, y)
May 10 16:11:22   File "/var/lib/jenkins/workspace/test/common_utils.py", line 475, in assertTensorsEqual
May 10 16:11:22     self.assertLessEqual(max_err, prec, message)
May 10 16:11:22 AssertionError: tensor(2.) not less than or equal to 1e-05 : 
```

**Comment by crcrpar** [comment]
@zou3519 Sorry, I forgot the existence of JIT tests.

**Review by ezyang — DISMISSED** [review]
CI is failing

**Comment by crcrpar** [comment]
I had a bit busy weekdays and am sorry for being late.

I think I fixed the problem and the `asan` test failure seems unrelated to this because it occurred in DataLoader test as follows.

```
...
May 18 02:17:46 test_proper_exit (__main__.TestDataLoader)
May 18 02:17:51 There might be ConnectionResetError or leaked semaphore warning (due to dirty process exit), but they are all safe to ignore ... Process ErrorTrackingProcess-17:
May 18 02:17:51 Traceback (most recent call last):
May 18 02:17:51   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
May 18 02:17:51     self.run()
May 18 02:17:51   File "/var/lib/jenkins/workspace/test/test_dataloader.py", line 227, in run
May 18 02:17:51     super(ErrorTrackingProcess, self).run()
May 18 02:17:51   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
May 18 02:17:51     self._target(*self._args, **self._kwargs)
May 18 02:17:51   File "/var/lib/jenkins/workspace/test/test_dataloader.py", line 439, in _test_proper_exit
May 18 02:17:51     raise RuntimeError('Loader error')
May 18 02:17:51 RuntimeError: Loader error
May 18 02:17:58 /opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
May 18 02:17:58   len(cache))
May 18 02:18:01 Process ErrorTrackingProcess-19:
...
```

**Comment by crcrpar** [comment]
@zou3519 @ezyang Could you check this?

**Comment by crcrpar** [comment]
I found https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide#dispatch-and-openmp is a bit outdated because now ATen has `parallel_for` function.

**Comment by ezyang** [comment]
Quick tip: you have to "dismiss" the review for it to show up in my review inbox

**Comment by ezyang** [comment]
I think the problem discussed in the porting guide is obsolete now, because lambdas work inside lambdas. So you don't need to make separate functions anymore.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
But I won't tell you to fix it! No problem with more functions.

**Comment by crcrpar** [comment]
OK, thank you very much.

**Pull request closed without merging**
