### PR TITLE
[DTensor] Cached hash for `DTensorSpec`

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #114140
* __->__ #113915
* #114141
* #113930
* #113925
* #114134
* #113924
* #113919

**Overview**
Generally, I think we can try to freeze as many of these classes used in DTensor sharding propagation as possible so that we can cache hashes. This PR targets hashing `DTensorSpec`, which turns out to be relatively expensive.

**Details**
It looks like `tensor_meta` is only updated in `_wrap_output_spec_tensor_meta`, which only runs if the propagation was not cached:
https://github.com/pytorch/pytorch/blob/ae94c7e491e22f58d3df66571c1a568e51d70acd/torch/distributed/_tensor/sharding_prop.py#L137
https://github.com/pytorch/pytorch/blob/ae94c7e491e22f58d3df66571c1a568e51d70acd/torch/distributed/_tensor/sharding_prop.py#L153
In that case, I think we can cache the hash for the `DTensorSpec` and only update it when one of the hashed attributes changes, which we only really expect to happen for `tensor_meta`.

To ensure correctness, we need that all hashed attributes are immutable.
- `DeviceMesh` caches its hash: https://github.com/pytorch/pytorch/blob/a9134fa99a8986adf478a12db2ea5729d24554db/torch/distributed/_device_mesh.py#L181
- This PR makes each `Placement` a frozen `dataclass`, making them immutable (relying on the fact that they do not have references to any mutable objects).
- `TensorMeta` is a `NamedTuple` of `torch.Size`, `Tuple[int, ...]`, and `torch.dtype`, so it is immutable: https://github.com/pytorch/pytorch/blob/9916d8a9eaaf2c05c131f2a2dbe9eabeeaa9dffc/torch/distributed/_tensor/placement_types.py#L369-L375

**Example**
For some simple small GPT model:
Before: 0.125 ms
Screenshot 2023-11-16 at 10 08 05 PM

After: 0.048 ms
Screenshot 2023-11-16 at 10 08 47 PM

The overall Adam CPU step time decreases from 7.647 ms to 6.451 ms.

### CODE REVIEW

**Comment by awgu** [comment]
Letting CI run to see if it complains...

**Comment by awgu** [comment]
```
CUDA_VISIBLE_DEVICES=2,3 python -m pytest test/distributed/_tensor/test_tensor_ops.py -k test_index
```

```
RuntimeError: Process 0 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/data/users/andgu/pytorch/torch/testing/_internal/common_distributed.py", line 658, in run_test
    getattr(self, test_name)()
  File "/data/users/andgu/pytorch/torch/testing/_internal/common_distributed.py", line 544, in wrapper
    fn()
  File "/data/users/andgu/pytorch/torch/testing/_internal/common_utils.py", line 2536, in wrapper
    method(*args, **kwargs)
  File "/data/users/andgu/pytorch/torch/testing/_internal/distributed/_tensor/common_dtensor.py", line 193, in wrapper
    func(self, *args, **kwargs)  # type: ignore[misc]
  File "/data/users/andgu/pytorch/test/distributed/_tensor/test_tensor_ops.py", line 307, in test_index
    self._test_op(
  File "/data/users/andgu/pytorch/test/distributed/_tensor/test_tensor_ops.py", line 279, in _test_op
    self.assertEqual(d_out.full_tensor(), out)
  File "/data/users/andgu/pytorch/torch/testing/_internal/common_utils.py", line 3439, in assertEqual
    raise error_metas.pop()[0].to_error(
AssertionError: The values for attribute 'shape' do not match: torch.Size([12, 16, 32]) != torch.Size([12, 32, 16]).
```

**Review by wanchaol — APPROVED** [review]
Awesome! great to see we can precompute DTensorSpec hash and save a such big CPU overhead!

**Pull request closed without merging**
