### PR TITLE
AOTInductor: error: ‘c10::Dispatcher’ has not been declared for CPU model

### PR DESCRIPTION
**Pull request by hl475**
Differential Revision: D48675055

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by houseroad — APPROVED** [review]
Looks good. Wondering why the unittest didn't catch it.

**Comment by hl475** [comment]
> Looks good. Wondering why the unittest didn't catch it.

Previously there is a similar fix on GPU side https://github.com/pytorch/pytorch/pull/104742 , but I guess no one ever looked into CPU models...

**Pull request closed without merging**
