### PR TITLE
[functorch] fix possible overflow

### PR DESCRIPTION
**Pull request by cyyever**
Fix some errors detected by static analysis.

### CODE REVIEW

**Comment by kit1980** [comment]
@zou3519 Please take a look if this something we want to do.

**Review by zou3519 — APPROVED** [review]
LGTM. My apologies for the delayed review. @cyyever, would it be possible to rebase this PR? If not, I can do the manual rebase and merge this.

**Comment by kit1980** [comment]
@zou3519 Could you merge this?

**Pull request closed without merging**
