### PR TITLE
Change ADD to COPY in Dockerfiles

### PR DESCRIPTION
**Pull request by kit1980**
Docker docs says "For other items (files, directories) that do not require ADD’s tar auto-extraction capability, you should always use COPY": https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy

I've found this by running https://github.com/hadolint/hadolint

This is a follow-up after https://github.com/pytorch/pytorch/pull/81944

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Comment by jeffdaily** [comment]
Are the CI failures real or transient?

**Review by jeffdaily — APPROVED** [review]
LGTM, pending a clean CI run.

**Comment by kit1980** [comment]
> Are the CI failures real or transient?

Not transient but unrelated, I've created a separate issue https://github.com/pytorch/pytorch/issues/82174

**Review by ZainRizvi — APPROVED** [review]
This is pretty cool!

**Pull request closed without merging**
