### PR TITLE
[ONNX] Fix for constant folding flaky tests

### PR DESCRIPTION
**Pull request by neginraoof**
Fix for constant folding flaky tests
Looks like the constant folding test modules are sometimes exported with ONNX_ATEN op export type, which is causing the CI failures.
I'm unable to repro this issue locally, but my guess is that the op export param is being overwritten on CI build at some point.
This PR sets the op export type and hopefully fixes the issue.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 388bd3e2:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=388bd3e2097606a7b9a02c703a1d264326b122b4).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4326350) pytorch_xla_linux_xenial_py3_6_clang7_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=89976549) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=89976549))
<details>
<summary>
<code>Jan 23 19:53:54 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff</code>
</summary>

```
Jan 23 19:53:54 File to patch:  
Jan 23 19:53:54 Skip this patch? [y]  
Jan 23 19:53:54 4 out of 4 hunks ignored 
Jan 23 19:53:54 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-clip_grad.diff 
Jan 23 19:53:54 Applying patch file: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff 
Jan 23 19:53:54 Traceback (most recent call last): 
Jan 23 19:53:54   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 67, in <module> 
Jan 23 19:53:54     patch_repo(args) 
Jan 23 19:53:54   File "/var/lib/jenkins/workspace/xla/scripts/cond_patch.py", line 49, in patch_repo 
Jan 23 19:53:54     raise RuntimeError('Failed to apply patch: {}'.format(ppath)) 
Jan 23 19:53:54 RuntimeError: Failed to apply patch: /var/lib/jenkins/workspace/xla/torch_patches/X10-device_test.diff 
Jan 23 19:53:54 + cleanup 
Jan 23 19:53:54 + retcode=1 
Jan 23 19:53:54 + set +x 
Jan 23 19:53:54 =================== sccache compilation log =================== 
Jan 23 19:53:54 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 23 19:53:54 Compile requests                 1 
Jan 23 19:53:54 Compile requests executed        0 
Jan 23 19:53:54 Cache hits                       0 
Jan 23 19:53:54 Cache misses                     0 
Jan 23 19:53:54 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by BowenBao — APPROVED** [review]
LGTM, thanks!

**Comment by neginraoof** [comment]
@houseroad Can we merge this? Thanks!

**Review by houseroad — APPROVED** [review]
Hopefully this will work.

**Pull request closed without merging**
