### PR TITLE
update kineto to XPU Windows fixed PR. [submodule kineto]

### PR DESCRIPTION
**Pull request by xuhancn**
Include XPU Windows Fixed PR: https://github.com/pytorch/kineto/pull/1012 

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by xuhancn** [comment]
FYI: @zejun-chen

**Comment by xuhancn** [comment]
Hi @sraikund16 Could you please review this PR?

**Comment by sraikund16** [comment]
@xuhancn Looks like there is some CI issue. Can you look into it and fix on the Kineto side?

**Comment by xuhancn** [comment]
> @xuhancn Looks like there is some CI issue. Can you look into it and fix on the Kineto side?

I tested a dummy PR it seems un-related: https://github.com/pytorch/pytorch/pull/143468

**Comment by sraikund16** [comment]
> @pytorchbot merge

oops meant to do @pytorchbot rebase

**Comment by xuhancn** [comment]
Hi The two issue is not `kineto` related, we can ignore them. The fixing PR: https://github.com/pytorch/pytorch/pull/143491

**Comment by xuhancn** [comment]
@sraikund16 DRCI updated: the two failure were unrelated.

**Review by sraikund16 — APPROVED** [review]

**Pull request closed without merging**
