### PR TITLE
Remove dynamo+nvfuser

### PR DESCRIPTION
**Pull request by IvanYashchuk**
This PR removes unmaintained Dynamo+nvFuser.

cc @albanD @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
Looks like tests are failing

**Review by jjsjann123 — APPROVED** [review]
stamp for emotional support :partying_face:

**Review by jansel — APPROVED** [review]

**Review by albanD — APPROVED** [review]

**Comment by DanilBaibak** [comment]
Hi @IvanYashchuk! Unfortunately, I need to revert your PR because it breaks a lot of tests in the main branch. Here you can find more information about the issue - https://github.com/pytorch/pytorch/actions/runs/5797600008/job/15713480613

**Comment by IvanYashchuk** [comment]
> Hi @IvanYashchuk! Unfortunately, I need to revert your PR because it breaks a lot of tests in the main branch. Here you can find more information about the issue - https://github.com/pytorch/pytorch/actions/runs/5797600008/job/15713480613

CI fails with Error: Could not find file '/home/ec2-user/actions-runner/_work/_actions/_temp_1657549b-d5f7-40ae-87b8-b88b73737a7a/_staging/pytorch-pytorch-6030151/test/_nvfuser/test_dynamo.py'.
This file was deleted intentionally. What is missing to make these jobs pass?

**Comment by IvanYashchuk** [comment]
What ciflow label is missing to run all of the main CI jobs on this PR?

**Comment by IvanYashchuk** [comment]
Okay it seems I should have deleted `test/_nvfuser
/test_dynamo.py`.

**Pull request closed without merging**
