### PR TITLE
[Traceable FSDP2] Allow tracing through FSDP2 impl in trace_rules.py

### PR DESCRIPTION
**Pull request by yf225**
Test commands:
- `python test/distributed/_composable/fsdp/test_fully_shard_training.py TestFullyShard1DTrainingCompose.test_train_parity_with_activation_checkpointing`

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #133657
* #133635
* #133636
* #133531
* __->__ #133532

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Comment by yf225** [comment]
TODO: gate the changes with `_dynamo.config.skip_fsdp_hooks=False` to prevent regression on current Ads models.

**Pull request closed without merging**
