### PR TITLE
[inductor] Use _unsafe_view decompostion

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #109669
* #109668
* #109667

As per the old comment, decomposing is better than lowering because patterns for
`view` would apply to `_unsafe_view` as well.

https://github.com/salilsdesai/pytorch/blob/fc47ba2794564592a243b8b3484b5cfee1e72fda/torch/_inductor/decomposition.py#L89

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by lezcano — APPROVED** [review]

**Comment by clee2000** [comment]
@pytorchbot revert -m "failing internally" -c ghfirst

cc @bertmaher as pt oncall?
<details><summary>logs</summary>
Here's the error logs were getting internally, I've omitted some stuff (mostly file paths)

```
======================================================================
ERROR: test_batch_linear_pre_grad_fusion (test.inductor.test_group_batch_fusion.TestGroupBatchFusion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/inductor/test_group_batch_fusion.py", line 370, in test_batch_linear_pre_grad_fusion
    res = traced(*input)
  File "torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 406, in _fn
    return fn(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 554, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "torch/_dynamo/convert_frame.py", line 632, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "torch/_dynamo/convert_frame.py", line 140, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 380, in _convert_frame_assert
    return _compile(
  File "torch/_dynamo/convert_frame.py", line 559, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 481, in compile_inner
    out_code = transform_code_object(code, transform)
  File "torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "torch/_dynamo/convert_frame.py", line 451, in transform
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 2094, in run
    super().run()
  File "torch/_dynamo/symbolic_convert.py", line 739, in run
    and self.step()
  File "torch/_dynamo/symbolic_convert.py", line 702, in step
    getattr(self, inst.opname)(inst)
  File "torch/_dynamo/symbolic_convert.py", line 2204, in RETURN_VALUE
    self.output.compile_subgraph(
  File "torch/_dynamo/output_graph.py", line 867, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_dynamo/output_graph.py", line 995, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/output_graph.py", line 1062, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "torch/_dynamo/output_graph.py", line 1047, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "torch/__init__.py", line 1583, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "torch/_inductor/compile_fx.py", line 1159, in compile_fx
    return aot_autograd(
  File "torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3894, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3432, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/aot_autograd.py", line 2215, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/aot_autograd.py", line 2395, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/aot_autograd.py", line 2920, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_inductor/compile_fx.py", line 1096, in fw_compiler_base
    return inner_compile(
  File "torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "torch/_inductor/debug.py", line 227, in inner
    return fn(*args, **kwargs)
  File "lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_inductor/***", line 101, in newFunction
    return old_func(*args, **kwargs)
...
...
...
  File "torch/_dynamo/symbolic_convert.py", line 2094, in run
    super().run()
  File "torch/_dynamo/symbolic_convert.py", line 739, in run
    and self.step()
  File "torch/_dynamo/symbolic_convert.py", line 702, in step
    getattr(self, inst.opname)(inst)
  File "torch/_dynamo/symbolic_convert.py", line 2204, in RETURN_VALUE
    self.output.compile_subgraph(
  File "torch/_dynamo/output_graph.py", line 867, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_dynamo/output_graph.py", line 995, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/output_graph.py", line 1062, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "torch/_dynamo/output_graph.py", line 1047, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "torch/__init__.py", line 1583, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "torch/_inductor/compile_fx.py", line 1159, in compile_fx
    return aot_autograd(
  File "torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3894, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3432, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/aot_autograd.py", line 2215, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/aot_autograd.py", line 2395, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/aot_autograd.py", line 2920, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_inductor/compile_fx.py", line 1096, in fw_compiler_base
    return inner_compile(
  File "torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "torch/_inductor/debug.py", line 227, in inner
    return fn(*args, **kwargs)
  File "lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_inductor/***", line 101, in newFunction
    return old_func(*args, **kwargs)
  File "torch/_inductor/compile_fx.py", line 340, in compile_fx_inner
    compiled_graph: CompiledFxGraph = fx_codegen_and_compile(
  File "torch/_inductor/compile_fx.py", line 535, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_inductor/graph.py", line 462, in run
    return super().run(*args)
  File "torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "torch/_inductor/graph.py", line 732, in run_node
    result = super().run_node(n)
  File "torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "torch/_inductor/graph.py", line 623, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "torch/_inductor/graph.py", line 620, in call_function
    out = lowerings[target](*args, **kwargs)
  File "torch/_inductor/lowering.py", line 278, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "torch/_inductor/lowering.py", line 1475, in handler
    TensorBox.create, ir.FallbackKernel.create(kernel, *args, **kwargs)
  File "torch/_inductor/ir.py", line 3850, in create
    ) = cls.process_kernel(kernel, *args, **kwargs)
  File "torch/_inductor/ir.py", line 3062, in process_kernel
    example_output = kernel(*new_args, **new_kwargs)
  File "torch/_ops.py", line 458, in __call__
    return self._op(*args, **kwargs or {})
  File "torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "torch/_subclasses/fake_tensor.py", line 1304, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "torch/_subclasses/fake_tensor.py", line 1510, in dispatch
    return decomposition_table[func](*args, **kwargs)
  File "torch/_decomp/decompositions.py", line 3112, in _reshape_alias
    return aten.view(x, shape)
  File "torch/_ops.py", line 702, in __call__
    return self._op(*args, **kwargs or {})
  File "torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "torch/_subclasses/fake_tensor.py", line 1304, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "torch/_subclasses/fake_tensor.py", line 1601, in dispatch
    r = func(*args, **kwargs)
  File "torch/_ops.py", line 458, in __call__
    return self._op(*args, **kwargs or {})
  File "torch/_refs/__init__.py", line 4450, in view
    return _reshape_view_helper(a, *shape, allow_copy=False)
  File "torch/_refs/__init__.py", line 3668, in _reshape_view_helper
    raise ValueError(msg)
```
</details>

**Comment by clee2000** [comment]
@pytorchbot revert -m "failing internally" -c ghfirst

cc @bertmaher as pt2 oncall?
<details><summary>logs</summary>
Here's the error logs were getting internally, I've omitted some stuff (mostly file paths)

```
======================================================================
ERROR: test_batch_linear_pre_grad_fusion (test.inductor.test_group_batch_fusion.TestGroupBatchFusion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/inductor/test_group_batch_fusion.py", line 370, in test_batch_linear_pre_grad_fusion
    res = traced(*input)
  File "torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 406, in _fn
    return fn(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 554, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "torch/_dynamo/convert_frame.py", line 632, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "torch/_dynamo/convert_frame.py", line 140, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 380, in _convert_frame_assert
    return _compile(
  File "torch/_dynamo/convert_frame.py", line 559, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 481, in compile_inner
    out_code = transform_code_object(code, transform)
  File "torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "torch/_dynamo/convert_frame.py", line 451, in transform
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 2094, in run
    super().run()
  File "torch/_dynamo/symbolic_convert.py", line 739, in run
    and self.step()
  File "torch/_dynamo/symbolic_convert.py", line 702, in step
    getattr(self, inst.opname)(inst)
  File "torch/_dynamo/symbolic_convert.py", line 2204, in RETURN_VALUE
    self.output.compile_subgraph(
  File "torch/_dynamo/output_graph.py", line 867, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_dynamo/output_graph.py", line 995, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/output_graph.py", line 1062, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "torch/_dynamo/output_graph.py", line 1047, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "torch/__init__.py", line 1583, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "torch/_inductor/compile_fx.py", line 1159, in compile_fx
    return aot_autograd(
  File "torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3894, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3432, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/aot_autograd.py", line 2215, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/aot_autograd.py", line 2395, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/aot_autograd.py", line 2920, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_inductor/compile_fx.py", line 1096, in fw_compiler_base
    return inner_compile(
  File "torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "torch/_inductor/debug.py", line 227, in inner
    return fn(*args, **kwargs)
  File "lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_inductor/***", line 101, in newFunction
    return old_func(*args, **kwargs)
...
...
...
  File "torch/_dynamo/symbolic_convert.py", line 2094, in run
    super().run()
  File "torch/_dynamo/symbolic_convert.py", line 739, in run
    and self.step()
  File "torch/_dynamo/symbolic_convert.py", line 702, in step
    getattr(self, inst.opname)(inst)
  File "torch/_dynamo/symbolic_convert.py", line 2204, in RETURN_VALUE
    self.output.compile_subgraph(
  File "torch/_dynamo/output_graph.py", line 867, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_dynamo/output_graph.py", line 995, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/output_graph.py", line 1062, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "torch/_dynamo/output_graph.py", line 1047, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "torch/__init__.py", line 1583, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "torch/_inductor/compile_fx.py", line 1159, in compile_fx
    return aot_autograd(
  File "torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3894, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3432, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/aot_autograd.py", line 2215, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/aot_autograd.py", line 2395, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "torch/_functorch/aot_autograd.py", line 2920, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_inductor/compile_fx.py", line 1096, in fw_compiler_base
    return inner_compile(
  File "torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "torch/_inductor/debug.py", line 227, in inner
    return fn(*args, **kwargs)
  File "lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_inductor/***", line 101, in newFunction
    return old_func(*args, **kwargs)
  File "torch/_inductor/compile_fx.py", line 340, in compile_fx_inner
    compiled_graph: CompiledFxGraph = fx_codegen_and_compile(
  File "torch/_inductor/compile_fx.py", line 535, in fx_codegen_and_compile
    graph.run(*example_inputs)
  File "torch/_dynamo/utils.py", line 190, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_inductor/graph.py", line 462, in run
    return super().run(*args)
  File "torch/fx/interpreter.py", line 138, in run
    self.env[node] = self.run_node(node)
  File "torch/_inductor/graph.py", line 732, in run_node
    result = super().run_node(n)
  File "torch/fx/interpreter.py", line 195, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "torch/_inductor/graph.py", line 623, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "torch/_inductor/graph.py", line 620, in call_function
    out = lowerings[target](*args, **kwargs)
  File "torch/_inductor/lowering.py", line 278, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "torch/_inductor/lowering.py", line 1475, in handler
    TensorBox.create, ir.FallbackKernel.create(kernel, *args, **kwargs)
  File "torch/_inductor/ir.py", line 3850, in create
    ) = cls.process_kernel(kernel, *args, **kwargs)
  File "torch/_inductor/ir.py", line 3062, in process_kernel
    example_output = kernel(*new_args, **new_kwargs)
  File "torch/_ops.py", line 458, in __call__
    return self._op(*args, **kwargs or {})
  File "torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "torch/_subclasses/fake_tensor.py", line 1304, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "torch/_subclasses/fake_tensor.py", line 1510, in dispatch
    return decomposition_table[func](*args, **kwargs)
  File "torch/_decomp/decompositions.py", line 3112, in _reshape_alias
    return aten.view(x, shape)
  File "torch/_ops.py", line 702, in __call__
    return self._op(*args, **kwargs or {})
  File "torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "torch/_subclasses/fake_tensor.py", line 1304, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "torch/_subclasses/fake_tensor.py", line 1601, in dispatch
    r = func(*args, **kwargs)
  File "torch/_ops.py", line 458, in __call__
    return self._op(*args, **kwargs or {})
  File "torch/_refs/__init__.py", line 4450, in view
    return _reshape_view_helper(a, *shape, allow_copy=False)
  File "torch/_refs/__init__.py", line 3668, in _reshape_view_helper
    raise ValueError(msg)
```
</details>

**Comment by bertmaher** [comment]
@peterbell10 I'm not sure why this failed on internal CI but not on Github CI; here's the reported error from test_split_cat_fx_passes.py - test_unbind_stack:
```
  File "/dev/shm/uid-30083/78e0cf18-seed-nspid4026534226_cgpid16112607-ns-4026534567/torch/_subclasses/fake_tensor.py", line 1510, in dispatch
    return decomposition_table[func](*args, **kwargs)
  File "/dev/shm/uid-30083/78e0cf18-seed-nspid4026534226_cgpid16112607-ns-4026534567/torch/_decomp/decompositions.py", line 3112, in _reshape_alias
    return aten.view(x, shape)
  File "/dev/shm/uid-30083/78e0cf18-seed-nspid4026534226_cgpid16112607-ns-4026534567/torch/_ops.py", line 702, in __call__
    return self._op(*args, **kwargs or {})
  File "/dev/shm/uid-30083/78e0cf18-seed-nspid4026534226_cgpid16112607-ns-4026534567/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/dev/shm/uid-30083/78e0cf18-seed-nspid4026534226_cgpid16112607-ns-4026534567/torch/_subclasses/fake_tensor.py", line 1304, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/dev/shm/uid-30083/78e0cf18-seed-nspid4026534226_cgpid16112607-ns-4026534567/torch/_subclasses/fake_tensor.py", line 1601, in dispatch
    r = func(*args, **kwargs)
  File "/dev/shm/uid-30083/78e0cf18-seed-nspid4026534226_cgpid16112607-ns-4026534567/torch/_ops.py", line 458, in __call__
    return self._op(*args, **kwargs or {})
  File "/dev/shm/uid-30083/78e0cf18-seed-nspid4026534226_cgpid16112607-ns-4026534567/torch/_refs/__init__.py", line 4450, in view
    return _reshape_view_helper(a, *shape, allow_copy=False)
  File "/dev/shm/uid-30083/78e0cf18-seed-nspid4026534226_cgpid16112607-ns-4026534567/torch/_refs/__init__.py", line 3668, in _reshape_view_helper
    raise ValueError(msg)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: ValueError: Cannot view a tensor with shape torch.Size([2, 32, 32, 16]) and strides (16384, 16, 512, 1) as a tensor with shape (2, 32, 512)!
  target: aten._unsafe_view.default
  args[0]: TensorBox(StorageBox(
    ComputedBuffer(name='buf0', layout=FixedLayout('cpu', torch.float32, size=[2, 32, 32, 16], stride=[16384, 16, 512, 1]), data=Pointwise(
      'cpu',
      torch.float32,
      def inner_fn(index):
          i0, i1, i2, i3 = index
          tmp0 = ops.load(arg0_1, i3 + 16 * i1 + 512 * i2 + 16384 * i0)
          return tmp0
      ,
      ranges=[2, 32, 32, 16],
      origin_node=clone,
      origins={clone}
    ))
  ))
  args[1]: [2, 32, 512]
```

**Comment by peterbell10** [comment]
This doesn't reproduce in OS, so I'm guessing something is broken in meta-internal. However, the extra lowering registration isn't causing any issues so I'll just drop this. The main part of this PR was already handled in #109663 anyway.

**Pull request closed without merging**
