### PR TITLE
Unify TEST_CUDNN definition

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105594

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by larryliu0820 — APPROVED** [review]

**Review by voznesenskym — APPROVED** [review]

**Comment by PaliC** [comment]
Sorry I jumped the gun, seems like the specific workflow that was broken on this PR wasn't actually run on the earlier PR.
@pytorchbot merge

**Comment by pruthvistony** [comment]
@ezyang ,
Seeing few failures on ROCm jobs
https://github.com/pytorch/pytorch/actions/runs/5613792988/job/15211197611
```
=================================== FAILURES ===================================
_________________ TestCppExtensionJIT.test_jit_cudnn_extension _________________
...
ImportError: /var/lib/jenkins/.cache/torch_extensions/py38_cpu/torch_test_cudnn_extension/torch_test_cudnn_extension.so: cannot open shared object file: No such file or directory
```

Added skip https://github.com/pytorch/pytorch/pull/105805

**Pull request closed without merging**
