### PR TITLE
Remove caffe2 image and video

### PR DESCRIPTION
**Pull request by cyyever**
This PR tries to decompose https://github.com/pytorch/pytorch/pull/122527 into a smaller one. Caffe2 image and video folders are removed along with the related CMake code.
To be noted, this was inspired and is co-dev with @r-barnes.

cc @albanD

### CODE REVIEW

**Review by eqy — APPROVED** [review]

**Comment by cyyever** [comment]
@r-barnes Do you mind if I merge this first?

**Comment by cyyever** [comment]
@ezyang Need your approval before merge.

**Comment by ezyang** [comment]
we're discussing with @r-barnes what the best way to coordinate this with internal diff train is right now

**Review by albanD — APPROVED** [review]

**Comment by kit1980** [comment]
@cyyever @r-barnes In future please try to have all changes outside of caffe2 in separate PR, like CMakeLists.txt changes.

Because this PR can not be imported to fbcode, now all changes outside of caffe2 needs to be applied manually.

**Comment by cyyever** [comment]
@kit1980  I see.

**Pull request closed without merging**
