### PR TITLE
Make emit_metrics importable without having boto3 installed

### PR DESCRIPTION
**Pull request by ZainRizvi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #107071
* __->__ #107070

Make it so that scripts can import and run the `emit_metrics` function even if they don't have boto3 installed, in which case it will still validate the inputs but skip the actual metric emission part.

It's purely a refactor without any real logic changes

Motivation: So that run_test.py and the target determination code can use this library easily without worrying about if it was imported or if it's dependencies are installed.

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Review by ZainRizvi — COMMENTED** [review]
@pytorchbot merge

**Pull request closed without merging**
