### PR TITLE
Remove unused code from old Caffe2 iOS library

### PR DESCRIPTION
**Pull request by jmdetloff**
I believe this is all dead code. The caffe2/mobile directory, which is a parent of the directory removed in this PR, is only added to build when INTERN_BUILD_MOBILE is false. But the contents of this directory are only linked when IOS is true. There is no build where both these conditions are met (INTERN_BUILD_MOBILE is set to IOS or ANDROID)

I believe this is code that used to be linked into the Caffe2 ios library, which no longer exists.

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Deleted code is tested code :)

**Comment by malfet** [comment]
@jmdetloff please import the change to make sure it does not regress any internal workflows.

**Comment by jmdetloff** [comment]
I was a casualty of yesterdays cuts I'm afraid, so I can't import anything. This is a PR from a while back.

**Comment by kit1980** [comment]
Currently multiple Meta-internal builds are failing with this change, need to figure out what to do.

**Comment by kit1980** [comment]
This change breaks a lot of Meta-internal mobile builds with errors like "mobile/contrib/ios/ios_caffe.cc" file not found.
So it looks like the assumption that the code is not used at all is not correct.
Closing this PR.

**Pull request closed without merging**
