### PR TITLE
Add a unit test for negative torch.arange() incorrect numerical behavior with dynamic shapes

### PR DESCRIPTION
**Pull request by ani300**
This unit test is for the fix in #97777 for issue #96971

cc: @ezyang 

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
You manually tested that reverting the fix causes this test to fail right? Great!

**Comment by ani300** [comment]
Are the windows testing machines broken or is it my code? The test outputs show nothing

**Comment by ezyang** [comment]
looks like outage

**Pull request closed without merging**
