### PR TITLE
generate_torch_version: Print exception info when get_sha fails

### PR DESCRIPTION
**Pull request by dreiss**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#78664**

Summary:
See #78659.  We want more information on why this is happening.

Test Plan:
Will run nightlies in CI.

### CODE REVIEW

**Comment by dreiss** [comment]
https://github.com/pytorch/pytorch/runs/6696867312?check_suite_focus=true

```
2022-06-01T20:52:34.6870701Z [4839/6294] Generating ../../../torch/version.py[K
2022-06-01T20:52:34.6873229Z fatal: unsafe repository ('/pytorch' is owned by someone else)
2022-06-01T20:52:34.6873966Z To add an exception for this directory, call:
2022-06-01T20:52:34.6875685Z 
2022-06-01T20:52:34.6876029Z 	git config --global --add safe.directory /pytorch
2022-06-01T20:52:34.6876422Z Traceback (most recent call last):
2022-06-01T20:52:34.6876878Z   File "/pytorch/torch/../tools/generate_torch_version.py", line 13, in get_sha
2022-06-01T20:52:34.6877549Z     subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=pytorch_root)
2022-06-01T20:52:34.6878239Z   File "/opt/python/cp37-cp37m/lib/python3.7/subprocess.py", line 411, in check_output
2022-06-01T20:52:34.6878825Z     **kwargs).stdout
2022-06-01T20:52:34.6879366Z   File "/opt/python/cp37-cp37m/lib/python3.7/subprocess.py", line 512, in run
2022-06-01T20:52:34.6879814Z     output=stdout, stderr=stderr)
2022-06-01T20:52:34.6880498Z subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
2022-06-01T20:52:34.7453501Z 
```

**Review by seemethere — APPROVED** [review]

**Comment by malfet** [comment]
err, this is a draft pr isn't it?

**Review by malfet — CHANGES_REQUESTED** [review]
this is just for debug purposes, isn't it? and as such not supposed to be merged?

**Comment by dreiss** [comment]
Might as well land it, right?  If something like this happens again (maybe some other sort of exception), it will be nice to have the full traceback.

**Pull request closed without merging**
