### PR TITLE
[ROCm] enable HIP IPC

### PR DESCRIPTION
**Pull request by jeffdaily**
Enables code paths that use hipIpc* functions.  Also enables test_multiprocessing.py.

### CODE REVIEW

**Review by osalpekar — APPROVED** [review]
Looks good to me!

**Comment by jithunnair-amd** [comment]
@jeffdaily Which ROCm version onwards is this support available?

**Comment by jeffdaily** [comment]
> @jeffdaily Which ROCm version onwards is this support available?

ROCm 4.5.2.

**Pull request closed without merging**
