### PR TITLE
Install torchtune and ao when testing ExecuTorch llama3

### PR DESCRIPTION
**Pull request by huydhn**
A follow-up on https://github.com/pytorch/pytorch/pull/139700, it's good that ET already pins ao, which makes this step much easier on PT CI.

### CODE REVIEW

**Comment by huydhn** [comment]
Something is still not right, this setup works locally for me which makes sense, but it fails on CI, which is weird.  I need to dig a bit deeper.

**Comment by huydhn** [comment]
I just find out that the test passes on nightly build PyTorch but failed on the wheel built from source.  Nothing obvious stands out yet, but let me compare these wheel to see what is the difference

**Review by malfet — CHANGES_REQUESTED** [review]
Are torchtune and torchao are mandatory dependencies of ExecuTorch?
If they are not, and just needed for some additional testing, we should restrict the test running in PT to set of subtests

**Comment by huydhn** [comment]
> Are torchtune and torchao are mandatory dependencies of ExecuTorch? If they are not, and just needed for some additional testing, we should restrict the test running in PT to set of subtests

They are not atm, but ExecuTorch team is working on adding them as mandatory dependency https://fb.workplace.com/groups/222849770514616/posts/534780649321525/?comment_id=534820722650851&reply_comment_id=535663095899947, so this change anticipates that.  I have another PR on ExecuTorch to skip the failed tests when ao is not installed.

Nevertheless, the tricky issue that I'm still trying to debug with this one is that the test fails only with the CPU wheel built from source but it works with nightly wheel.  Other components including ao and executorch are installed in the same way, so it's puzzling me on what causes the difference

**Comment by huydhn** [comment]
We also don't need to explicitly pin ao on PyTorch.  Instead, we just need to call `https://github.com/pytorch/executorch/blob/main/.ci/scripts/setup-linux.sh` to setup ExecuTorch, then run the test

**Comment by huydhn** [comment]
I found the root cause for the failures in https://github.com/pytorch/executorch/pull/6744 and should have pay more attention to the warning in the build log about `_GLIBCXX_USE_CXX11_ABI`.  So, I will close this as the main fix is on ET.

@malfet Do you know why PyTorch nightly binaries unset `_GLIBCXX_USE_CXX11_ABI` while PyTorch CI sets it.  This difference is the reason why the test couldn't find these quantized symbol. The missing torchao and torchtune was a red herring.

**Pull request closed without merging**
