### PR TITLE
Eliminate c10::guts::make_unique_base

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by clee2000** [comment]
@pytorchbot revert -m "Sorry its me again, I'm getting that this caused an instruction count regression internally" -c ghfirst

cc @ezyang

**Comment by ezyang** [comment]
@clee2000 you gotta give more deets lol

**Comment by clee2000** [comment]
Apparently it makes compile time of the file on clang15 worse.  Please let me know what other information you need and I will try to get it

**Pull request closed without merging**
