### PR TITLE
Stop last usage of newWithSize.

### PR DESCRIPTION
**Pull request by gchanan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #34403 Port set_ to ATen.
* #34389 Stop creating unnecessary Storage with newWithStorage1d.
* #34388 Kill newWithStorage.
* #34387 Get rid of newWithSize.
* **#34386 Stop last usage of newWithSize.**

Differential Revision: [D20311061](https://our.internmc.facebook.com/intern/diff/D20311061)

### CODE REVIEW

**Review by bhosmer — APPROVED** [review]
Not for this PR but: no shortcutting?

**Comment by gchanan** [comment]
what do you mean by no shortcutting?

**Comment by bhosmer** [comment]
> what do you mean by no shortcutting?

Sorry, that was supposed to be an inline comment re [this here](https://github.com/pytorch/pytorch/pull/34386/files#diff-dcae165dc82a38f7ac9f1adb6870649bR14-R16) - i.e. just noticing the lack of boolean shortcutting. But I guess the answer has to be that it's faster to blast out the whole Tensor-wide computation on a GPU...

**Comment by gchanan** [comment]
I can't actually see that link (it just opens up the PR) -- maybe just copy paste the code in question here?

**Comment by gchanan** [comment]
discussed offline -- this is about why we implement equals as a two-pass min followed by checking the value.  There are probably more performant ways of implementing but this is the easiest.

**Comment by gchanan** [comment]
this is failing windows builds in ways I don't understand, e.g.:
```
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.h(51): error C2993: 'T': illegal type for non-type template parameter '__formal'
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.h(51): note: see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_propagate_on_container_copy_assignment<T>' being compiled
C:/Users/circleci/project\c10/core/MemoryFormat.h(56): note: see reference to class template instantiation 'c10::ArrayRef<__int64>' being compiled
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.h(51): error C2065: 'U1': undeclared identifier
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.h(51): error C2923: 'std::_Select<__formal>::_Apply': 'U1' is not a valid template type argument for parameter '<unnamed-symbol>'
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.h(51): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.h(51): error C2144: syntax error: 'unknown-type' should be preceded by ')'
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.h(51): error C2144: syntax error: 'unknown-type' should be preceded by ';'
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.h(51): error C2238: unexpected token(s) preceding ';'
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.h(51): error C2059: syntax error: ')'
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.h(51): error C2988: unrecognizable template declaration/definition
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.h(51): error C2059: syntax error: '<end Parse>'
-- Removing C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorMaskedChar.cu.obj
C:/Jenkins/Miniconda3/Library/bin/cmake.exe -E remove C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorMaskedChar.cu.obj
CMake Error at torch_cuda_generated_THCTensorMaskedChar.cu.obj.Release.cmake:281 (message):
  Error generating file
  C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorMaskedChar.cu.obj
```

**Comment by gchanan** [comment]
I moved out the changes from THTensor.hpp because that's my best guess at what the problem is.

**Pull request closed without merging**
