### PR TITLE
[PyTorch] Check `defined(__aarch64__) && !defined(CPU_CAPABILITY_SVE256)` instead of `defined(CPU_CAPABILITY_NEON)`

### LINKED ISSUE #137704: CPU_CAPABILITY_NEON isn't defined for PyTorch core builds, only via inductor
### 🐛 Describe the bug

We have code in aten/src/ATen/cpu/vec/ gated on CPU_CAPABILITY_NEON, such as https://github.com/pytorch/pytorch/blob/bcf15d1bb415f5df30037a2c3f3ea9375e812e54/aten/src/ATen/cpu/vec/vec256/vec256_convert.h#L302 . Nothing except torchinductor appears to define this macro, and it's certainly not defined during `python setup.py install` on my Mac (as determined by putting an `#error` in one of the blocks gated on `#if defined(CPU_CAPABILITY_NEON)`.

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 14.7 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.3)
CMake version: version 3.30.4
Libc version: N/A

Python version: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.7-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] executorch==0.4.0a0+9d9cda0
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] optree==0.12.1
[pip3] torch==2.6.0a0+gitccca3de
[pip3] torchao==0.5.0+git0916b5b
[pip3] torchaudio==2.4.0.dev20240716
[pip3] torchsr==1.0.4
[pip3] torchvision==0.20.0.dev20240716
[conda] executorch                0.4.0a0+9d9cda0          pypi_0    pypi
[conda] numpy                     2.0.1                    pypi_0    pypi
[conda] numpy-base                1.26.4          py312he047099_0
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] torch                     2.6.0a0+gitccca3de          pypi_0    pypi
[conda] torchao                   0.1                      pypi_0    pypi
[conda] torchaudio                2.4.0.dev20240716          pypi_0    pypi
[conda] torchsr                   1.0.4                    pypi_0    pypi
[conda] torchvision               0.20.0.dev20240716          pypi_0    pypi

cc @malfet @seemethere @snadampal @milpuz01 @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #138022
* #138014
* __->__ #137722

The CPU_CAPABILITY system is for rebuilding kernels multiple times with different vector ISA targets. CPU_CAPABILITY_NEON was not being used for that, just as an extra flag for inductor. As a result, CPU_CAPABILITY_NEON-gated code was unnecessarily unavailable outside inductor. Fixes #137704

Differential Revision: [D64197046](https://our.internmc.facebook.com/intern/diff/D64197046/)

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by swolchok** [comment]
looks like this needs to be identical to the gating surrounding vec128_float_neon

**Comment by swolchok** [comment]
> looks like this needs to be identical to the gating surrounding vec256_float_neon

specifically, 1) we just use __aarch64__ to gate that implementation, so we should follow suit here
2) we also need to check !defined(CPU_CAPABILITY_SVE256) because this apparently messes with SVE

**Comment by swolchok** [comment]
hooray for green tests

**Review by jgong5 — APPROVED** [review]

**Comment by abhishek-iitmadras** [comment]
Hi @swolchok 
Wouldn't it be better to define `CPU_CAPABILITY_SVE` instead of just `CPU_CAPABILITY_SVE256`?

**Comment by swolchok** [comment]
> Hi @swolchok Wouldn't it be better to define `CPU_CAPABILITY_SVE` instead of just `CPU_CAPABILITY_SVE256`?

it is CPU_CAPABILITY_SVE256 because that is the gating surrounding vec256_float_neon.h: https://www.internalfb.com/code/fbsource/[0660504a24502363bb08b1b37504bc3ef6d878eb]/fbcode/caffe2/aten/src/ATen/cpu/vec/vec256/vec256.h?lines=10-15

**Review by malfet — CHANGES_REQUESTED** [review]
This strips the ability of generating non-NEON accelerated code in torch.comple, which feels like a regression... 
I.e. please undo changes to `cpp_prefix.h`/cpu_vec_isa.py

**Review by malfet — APPROVED** [review]
Looks good to me, thank you for the update

**Pull request closed without merging**
