### PR TITLE
Don't #define NUM_THREADS

### PR DESCRIPTION
**Pull request by zasdfgbnm**
PyTorch doesn't compile with the latest `main` branch of cub again. The root cause is, PyTorch defines a macro `NUM_THREADS`, and cub added some code like
```C++
template<...., int NUM_THREADS, ...>
```
and these two mess up with each other.

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Misaligned address still failing, probably needs to be kept disabled.

**Comment by zasdfgbnm** [comment]
skipped

**Comment by ngimel** [comment]
Interestingly, I didn't get internal failures w/o skip, so must be driver version.

**Comment by janeyx99** [comment]
Sorry, reverting as it seems to have broken trunk 10.2 builds https://hud.pytorch.org/commit/pytorch/pytorch/f70e8064f4e6266ab945bc24345c622dc7933d0e

**Comment by ngimel** [comment]
I've added ciflow/cuda label https://github.com/pytorch/pytorch/pull/67258#issuecomment-961328918, why weren't 10.2 tests run?

**Comment by zasdfgbnm** [comment]
Why this is reverted? This is a pretty old PR.

**Comment by janeyx99** [comment]
@zasdfgbnm it’s not reverted again, but the facebook github bot just seems to have gone back in time and comment on old previously reverted PRs. This isn’t intentional

**Pull request closed without merging**
