### PR TITLE
jit trace will fail for parameter check if it contains param whose ki…

### PR DESCRIPTION
**Pull request by sywangyi**
…nd is _ParameterKind.VAR_KEYWORD

### CODE REVIEW

**Comment by sywangyi** [comment]
the jit failure for bloom model whose forward contains “**deprecated_arguments” see https://github.com/huggingface/transformers/blob/main/src/transformers/models/bloom/modeling_bloom.py#L880

the return of [] of this function cause failure in check https://github.com/pytorch/pytorch/blob/master/torch/jit/_trace.py#L1036

**Comment by sywangyi** [comment]
@yao-matrix @jgong5 please help review

**Review by davidberard98 — COMMENTED** [review]
@sywangyi do you think you could add a test for the behavior that previously would fail? you can add it in test/jit/test_tracer.py

**Comment by sywangyi** [comment]
> @sywangyi do you think you could add a test for the behavior that previously would fail? you can add it in test/jit/test_tracer.py

Hi. @davidberard98  thanks for the review. I have added it.

**Comment by davidberard98** [comment]
@sywangyi can you take a closer look at the test failures? I think this change looks okay but please fix the test failures first.

**Comment by davidberard98** [comment]
adding my thoughts on why this change is reasonable, in case I forget later.

First, why I initially thought this might be concerning: we silently allow users to proceed in cases where the function takes `**kwargs`, which we don't support. It may not be obvious to the user why the failure is occuring.

Counterpoint (why this change is okay): This PR doesn't change the fact that `**kwargs` is silent; it just increases support for that scenario. In addition, this problem only occurs with example_kwarg_inputs (where you provide kwargs input to jit.trace, instead of a list of args when you use the usual example_inputs) so this improves the user experience.

**Review by qihqi — APPROVED** [review]

**Review by davidberard98 — APPROVED** [review]

**Review by davidberard98 — CHANGES_REQUESTED** [review]
actually I retract my approval based on the test failures... can you take a look at those?

**Comment by sywangyi** [comment]
> actually I retract my approval based on the test failures... can you take a look at those?

Hi. @davidberard98 . I check the failure case, one is test_coalesce_reference_cycle_cpu_float64 in test_sparse.py. I run all the test_sparse.py case in my env. all success. and even it does not enter the logic I change, I place a breakpoint there.
same as the failure case under "linux-bionic-py3.11-clang9"

**Comment by davidberard98** [comment]
`test_coalesce_reference_cycle_cpu_float64` looks unrelated, it is failing in a number of PRs. I am more concerned about `test_empty_class_serialization`, it sounds vaguely related.

Let's see if a rebase fixes the issues.

**Review by davidberard98 — APPROVED** [review]

**Pull request closed without merging**
