### PR TITLE
Skips failing ROCm test

### PR DESCRIPTION
**Pull request by mruberry**
ROCm and CUDA type promotion are slightly divergent and need to be updated.

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

### CODE REVIEW

**Review by anjali411 — APPROVED** [review]

**Review by albanD — APPROVED** [review]
SGTM

**Review by janeyx99 — APPROVED** [review]

**Comment by jeffdaily** [comment]
Can we get more info on this one?  And an issue to track?  When did it start failing?  Was it a result of some other commit?

**Comment by mruberry** [comment]
> Can we get more info on this one? And an issue to track? When did it start failing? Was it a result of some other commit?

I just added the test all of 10 minutes ago, it's just because gcd goes through a different path is all. The correct fix is to just xfail the gcd cuda test instead of xfailing the gcd cuda and ROCm tests. I just wanted to fix the CI.

**Comment by jithunnair-amd** [comment]
@mruberry Thanks for the skip to fix the CI temporarily! Where are we tracking the proper fix to this issue though: "The correct fix is to just xfail the gcd cuda test instead of xfailing the gcd cuda and ROCm tests". We should avoid skipping unit tests for all the ops if the issue is just with gcd, right?

**Comment by mruberry** [comment]
https://github.com/pytorch/pytorch/issues/69464 has a subitem to track this, too

**Comment by mruberry** [comment]
> @mruberry Thanks for the skip to fix the CI temporarily! Where are we tracking the proper fix to this issue though: "The correct fix is to just xfail the gcd cuda test instead of xfailing the gcd cuda and ROCm tests"? We should avoid skipping unit tests for all the ops if the issue is just with gcd, right?

Yes you are correct, that's just a riskier/more time consuming fix to make because we should be sure there aren't other test failures with this new test. I'll probably get started on it soon (following #69464).

**Pull request closed without merging**
