### PR TITLE
Add basic mypy annotations to inductor

### PR DESCRIPTION
**Pull request by oulgen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #132416
* #132415

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
honest question - what is the point of annotating `-> None` from` __init__` ? doesn't everyone know how `__init__` works ?

**Review by XuehaiPan — APPROVED** [review]

**Comment by oulgen** [comment]
> honest question - what is the point of annotating `-> None` from` __init__` ? doesn't everyone know how `__init__` works ?

While I agree with you, mypy does not, this is the only way to make it happy.

**Comment by oulgen** [comment]
@eellison yeah, I'm all for finding something better. In fact a better programming language :D

I see a lot of people including me waste time adding these annotations when trying to add more important ones, so I'm just programmatically cleaning up the easy stuff.

**Comment by eellison** [comment]
@oulgen, where specifically, are you getting a mypy error for no annotate `__init__` ? all of these files are working today.

**Comment by oulgen** [comment]
@eellison 

mypy has some rules

```
# error, needs -> None
def __init__(self):
  pass

# no error because there's an argument that's type checked, so that's enough
def __init__(self, x : int):
  pass
```

so instead of catering to particular rules, I used
```
ruff check --select=ANN204 --fix-only --fix --unsafe-fixes
```
to add anything it can add

Are you against add these?

**Comment by eellison** [comment]
From https://stackoverflow.com/questions/74818864/does-mypy-require-init-to-have-none-annotation:

> I don't particularly like this approach, but that is the way they decided to handle it.

Makes sense. i'm good landing this, but it's annoying we have to. extra, unnecessary code is not "free", it reduces readability.

**Review by jamesjwu — APPROVED** [review]

**Pull request closed without merging**
