### PR TITLE
TensorIterator: Check memory overlap in all `unary_op`s

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #43423 Check for internal memory overlap in some indexing-type functions
* #43422 TensorIteratorConfig: Check memory overlap by default
* #43421 TensorIterator: Check for memory overlap in all `nullary_op`s
* #43420 TensorIterator: Check for memory overlap in all `compare_op`s
* #43419 TensorIterator: Check for memory overlap in all `binary_op`s
* **#43418 TensorIterator: Check memory overlap in all `unary_op`s**

Differential Revision: [D23298651](https://our.internmc.facebook.com/intern/diff/D23298651)

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]
Thanks, submitting the PRs like this makes it easier to review :). 

Could you rebase the stack so that we get signal on some of the builds below?

**Comment by peterbell10** [comment]
`ghstack` seems to have gotten messed up after I rebased on master. @ezyang any idea if this is fixable?

**Comment by zou3519** [comment]
I'm not sure what happened with the rebase. But one way to save it could be to:
- check out a new branch off of master
- cherry-pick the PRs in the stack to the new branch
- run ghstack on that branch

**Comment by peterbell10** [comment]
Thanks, that did the trick.

**Comment by zou3519** [comment]
@peterbell10 we should skip the softshrink and softplus inplace overlap tests on XLA : 

> Aug 26 00:53:11 FAIL [0.181s]: test_softplus_inplace_overlap_xla (__main__.TestNNDeviceTypeXLA) 
Aug 26 00:53:11 ---------------------------------------------------------------------- 
Aug 26 00:53:11 Traceback (most recent call last): 
Aug 26 00:53:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 257, in instantiated_test 
Aug 26 00:53:11     result = test(self, *args) 
Aug 26 00:53:11   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 11899, in test_softplus_inplace_overlap 
Aug 26 00:53:11     F.softplus(x, out=x) 
Aug 26 00:53:11 AssertionError: RuntimeError not raised 
Aug 26 00:53:11  
Aug 26 00:53:11 ====================================================================== 
Aug 26 00:53:11 FAIL [0.004s]: test_softshrink_inplace_overlap_xla (__main__.TestNNDeviceTypeXLA) 
Aug 26 00:53:11 ---------------------------------------------------------------------- 
Aug 26 00:53:11 Traceback (most recent call last): 
Aug 26 00:53:11   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 257, in instantiated_test 
Aug 26 00:53:11     result = test(self, *args) 
Aug 26 00:53:11   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 11904, in test_softshrink_inplace_overlap 
Aug 26 00:53:11     F.softshrink(x, out=x) 
Aug 26 00:53:11 AssertionError: RuntimeError not raised 
Aug 26 00:53:11  
Aug 26 00:53:11 ---------------------------------------------------------------------- 
Aug 26 00:53:11 Ran 126 tests in 605.253s

**Pull request closed without merging**
