### PR TITLE
Add symmetric version of gpu_kernel_with_scalars

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #78990
* __->__ #78989

`gpu_kernel_with_scalars` produces 3 calls to `gpu_kernel` for
`f(a, b)` where either of a or b can be cpu scalars. If `f` happens to
be symmetric (i.e. `f(a, b) == f(b, a)`) then we only need 2 calls to
`gpu_kernel` thus reducing the cuda context size.

On my build for 1 cuda architecture, this reduces `torch_cuda_cu.so`
by 24.5 MB.

### CODE REVIEW

**Comment by peterbell10** [comment]
@ngimel ping

**Review by ngimel — APPROVED** [review]
Sorry, was on PTO. This looks great, I have a minor question about device guard placement

**Pull request closed without merging**
