### PR TITLE
[BE] minor logging cleanup in distributed

### PR DESCRIPTION
**Pull request by c-p-i-o**
Summary:
    Minor logging cleanup in distributed library
    1. Don't use "f" formatted strings - address linter issues.
    2. Nits: Make use of unused `e` (error) in a few logs.
    3. Change info->debug as asked in issue #113545
    4. Nit: rename log -> logger in a few files for consistency
    5. Fix a linter error.

    Test Plan:
    1. Local build passes.
    2. Linter is happy.

    Reviewers: wanchaol

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]

**Comment by c-p-i-o** [comment]
@pytorch merge

**Comment by c-p-i-o** [comment]
[.github/workflows/pull.yml / linux-focal-rocm6.0-py3.8 / build](https://github.com/pytorch/pytorch/actions/runs/8473595047/job/23218282985) is flaky

**Pull request closed without merging**
