### PR TITLE
Improve zero sized input for addmv

### LINKED ISSUE #41340: Error in test suite: an illegal memory access was encountered
## 🐛 Bug

Running the test suite fails on our system. The issue seems to be with `TestTorchDeviceTypeCUDA` where starting with `test_blas_alpha_beta_empty_cuda_float16` all tests fail with `RuntimeError: CUDA error: an illegal memory access was encountered`

## To Reproduce

1. python run_tests.py

One of the traceback is:
```
Traceback (most recent call last):
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 777, in wrapper
    method(*args, **kwargs)
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 777, in wrapper
    method(*args, **kwargs)
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 241, in instantiated_test
    result = test(self, device_arg, dtype)
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_torch.py", line 13909, in test_blas_alpha_beta_empty
    torch.addmv(input=input, mat=mat, vec=vec, alpha=alpha, beta=beta))
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1080, in assertEqual
    exact_device=exact_device)
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 971, in _compareTensors
    return _compare_tensors_internal(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan)
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/__init__.py", line 122, in _compare_tensors_internal
    if torch.allclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan):
RuntimeError: CUDA error: an illegal memory access was encountered
```

Maybe related to #21819 or #36722

## Environment

PyTorch version: 1.6.0-rc2
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Red Hat Enterprise Linux Server release 7.8 (Maipo)
GCC version: (GCC) 8.3.0
CMake version: version 3.15.3

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80

Nvidia driver version: 450.36.06
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.3

cc @ezyang @gchanan @zou3519 @csarofeen @ptrblck @ngimel

### PR DESCRIPTION
**Pull request by zasdfgbnm**
fixes https://github.com/pytorch/pytorch/issues/41340

Unfortunately, I still can not get a K80 to verify the fix, but it should be working.

### CODE REVIEW

**Comment by ngimel** [comment]
I don't think this is the right fix, because the root cause of that failing test case was fp16 gemm for fp16, not fp16 gemmv
```
device="cuda"
dtype=torch.float16
mat = torch.ones((2, 0), dtype=dtype, device=device)
vec = torch.ones((0,), dtype=dtype, device=device)
print(torch.mm(mat,vec.view(0,1))) #errors out on K80
```
This fix will mask gemm failure because gemv for degenerate case won't go through gemm, but gemm failure will still remain.

**Comment by zasdfgbnm** [comment]
(Just realize that I put the wrong issue number. It is fixed now)

@ngimel I think both addmm and addmv are wrong? And in the issue, the author says addmv:

```python
Traceback (most recent call last):
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 777, in wrapper
    method(*args, **kwargs)
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 777, in wrapper
    method(*args, **kwargs)
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 241, in instantiated_test
    result = test(self, device_arg, dtype)
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
    return fn(slf, device, *args, **kwargs)
  File "test_torch.py", line 13909, in test_blas_alpha_beta_empty
    torch.addmv(input=input, mat=mat, vec=vec, alpha=alpha, beta=beta))
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1080, in assertEqual
    exact_device=exact_device)
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 971, in _compareTensors
    return _compare_tensors_internal(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan)
  File "/tmp/easybuild-tmp/eb-1Ebm0K/tmpcR9xV8/lib/python3.7/site-packages/torch/testing/__init__.py", line 122, in _compare_tensors_internal
    if torch.allclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan):
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by ngimel** [comment]
Yeah, the failing test is addmv. Addmv/mv call `at::cuda::blas::gemv`, however, if you remember, for fp16 `at::cuda::blas::gemv` does not call cublas gemv (because there's no such thing), instead it calls `at:cuda::blas::gemm`, which, in turn, calls `cublasSgemmEx`, which finally throws an error. fp16 mm/addmm also call cublasSgemmEx, so even though the empty calls with them are not tested in the test suite, they would still be affected, as demonstrated in the snippet above. So both mv and mm are affected with the same rootcause.

**Comment by zasdfgbnm** [comment]
@ngimel addmm is fixed too

**Comment by zasdfgbnm** [comment]
ping @ngimel

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Thank you for the fix!

**Pull request closed without merging**
