### PR TITLE
[skip ci] Remove unused outdated .circleci bazel_definitions file

### PR DESCRIPTION
**Pull request by janeyx99**
Small clean-up, realized this file isn't necessary after migrating to GHA, so removing this file

Test plan: running .circleci/regenerate.sh yields no config changes

### CODE REVIEW

**Review by suo — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Comment by janeyx99** [comment]
> Cross-repo merges are not supported at the moment

what does this mean

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@janeyx99 you've authored this PR from your repo(https://github.com/janeyx99/pytorch), rather than from a branch in https://github.com/pytorch/pytorch. Right now merges are only supported for branches within pytorch/pytorch

**Comment by janeyx99** [comment]
Ah, good to know for the future, thanks @malfet

**Pull request closed without merging**
