### PR TITLE
[Dynamo][Forward fix] Add torch.ao back to is_allowed list

### PR DESCRIPTION
**Pull request by yanboliang**
Summary: As title

Test Plan: Sandcastle

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by drisspg — APPROVED** [review]
✅

**Review by voznesenskym — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Pull request closed without merging**
