### PR TITLE
Upgrade MKL-DNN to version 0.17 and static build MKL-DNN

### PR DESCRIPTION
**Pull request by gujinghui**
Upgrade MKl-DNN to 0.17 and static build MKL-DNN to fix the potentail build error due to old mkldnn version in host system.

### CODE REVIEW

**Comment by gujinghui** [comment]
@ezyang @yinghai 
This PR is trying to static build MKL-DNN into caffe2.
It aims to fix the potential build error which reported by users these days.
The reason of such error is caused by old mkl-dnn installed in user system before.

@soumith 
With static build MKL-DNN, the size of libcaffe2.so is increased from 43M to 53M, about 10M is added.
Pls help review it. If any problem, pls kindly give your suggestion.

@jgong5 @Jianhui-Li

**Comment by soumith** [comment]
@gujinghui thanks a lot for switching to static linking, this will solve many issues that the users have been seeing because of older MKLDNN in the system.

**Comment by gujinghui** [comment]
rebased & passed all cases.
Pls help review.
@yinghai @soumith @ezyang

**Review by soumith — APPROVED** [review]
reviewed and looks good to me

**Pull request closed without merging**
