### PR TITLE
Use correct standard when compiling NVCC on Windows

### PR DESCRIPTION
**Pull request by r-barnes**
Test Plan: Sandcastle

Reviewed By: malfet

Differential Revision: D45108690

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Comment by malfet** [comment]
@r-barnes as it has an associated diff, perhaps the right approach would be to land it via CoDev (slapping `accept2ship` on the diff and landing it)

**Review by malfet — CHANGES_REQUESTED** [review]
Idea is good, but alas needs more work

**Pull request closed without merging**
