### PR TITLE
Autocast `vdot`

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125697

Fixes https://github.com/pytorch/pytorch/issues/125544

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Review by jbschlosser — COMMENTED** [review]
Thanks for the quick fix! Much easier than I expected. Do you mind adding a quick test as well

**Comment by lezcano** [comment]
roger

**Review by jbschlosser — APPROVED** [review]

**Pull request closed without merging**
