### PR TITLE
Only update momentum buffers for SGD if momentum is enabled

### PR DESCRIPTION
**Pull request by mlazos**
As title

[benchmark](https://gist.github.com/mlazos/1171f035a2392c33778aaa3d7bf24370)

Helps compiled vanilla SGD execution time by 2x on certain models with large number of small params (ex. 
ElectraForQuestionAnswering goes from 1090us -> 554us)

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
Looks safe to do since we guard on accessing the list in the implementations for when momentum is nonzero anyway.

Have you tried also limiting the momentum_buffer_list buildup in line 56 for _init_group? Could we also gate that (do the tests pass)?

**Comment by mlazos** [comment]
> Looks safe to do since we guard on accessing the list in the implementations for when momentum is nonzero anyway.
> 
> Have you tried also limiting the momentum_buffer_list buildup in line 56 for _init_group? Could we also gate that (do the tests pass)?

Yup looks like it works

**Review by janeyx99 — COMMENTED** [review]
do you have numbers for why this is not a trivial change? Could you include in PR desc for why we want this?

**Review by janeyx99 — APPROVED** [review]
looks great!

**Comment by mlazos** [comment]
@JackCaoG looks like an XLA test is failing, can someone on your side submit a PR to point to this branch?

**Comment by JackCaoG** [comment]
Hey I think this pr changes the SGD + dynamo integration somehow. Let me send a pr to Pytorch/xla to make this check more general and we can pin that XLA commit in this pr.

**Comment by mlazos** [comment]
> Hey I think this pr changes the SGD + dynamo integration somehow. Let me send a pr to Pytorch/xla to make this check more general and we can pin that XLA commit in this pr.

Yeah I think it changes the number of kernels/graphs generated, should be okay to update that constant

**Comment by JackCaoG** [comment]
I will try to send out the pr by the end of the day.. too many meetings today.

**Comment by mlazos** [comment]
> I will try to send out the pr by the end of the day.. too many meetings today.

Nw, thank you!

**Comment by JackCaoG** [comment]
Ok if https://github.com/pytorch/xla/pull/6802 passed all CI, I can merge it and you can update the XLA pin to the new PyTorch/XLA master commit(I will share detail steps when it is merged).

**Comment by JackCaoG** [comment]
OK I think if you update the hash in https://github.com/pytorch/pytorch/blob/main/.github/ci_commit_pins/xla.txt to `42ecc295a8ba0c675eeb598acf25461cfaaf7e5d` which points to https://github.com/pytorch/xla/commit/42ecc295a8ba0c675eeb598acf25461cfaaf7e5d, XLA CI should start passing. Then you can merge with the new XLA pin.

**Comment by mlazos** [comment]
> OK I think if you update the hash in [`main`/.github/ci_commit_pins/xla.txt](https://github.com/pytorch/pytorch/blob/main/.github/ci_commit_pins/xla.txt?rgh-link-date=2024-03-22T22%3A22%3A32Z) to `42ecc295a8ba0c675eeb598acf25461cfaaf7e5d` which points to [pytorch/xla@42ecc29](https://github.com/pytorch/xla/commit/42ecc295a8ba0c675eeb598acf25461cfaaf7e5d), XLA CI should start passing. Then you can merge with the new XLA pin.

Updated

**Comment by mlazos** [comment]
@JackCaoG I noticed there was a conflict with the pin, are we still good to merge this once CI is green?

**Comment by JackCaoG** [comment]
Sorry can you update it to `134f5b628c12e290afefc0df7f4022b92a844e0d` and let mergebot to merge? There was another XLA breaking PR merge in and got reverted which result in pin conflicts. We also need to revert the corresponding pr on our end..

**Comment by mlazos** [comment]
@JackCaoG I'm working on relanding this after the revert, do you need to redo the pin fix?

**Comment by JackCaoG** [comment]
I think XLA CI should just pass, if it failed let me know

**Pull request closed without merging**
