### PR TITLE
Remove redundant code for unsupported Python versions

### PR DESCRIPTION
**Pull request by hugovk**
Remove code for Python 3.5 and lower.

There's more that can be removed/modernised, but sticking mainly to redundant version checks here, to keep the diff/PR smaller.

### CODE REVIEW

**Comment by hugovk** [comment]
I'm not quite sure what the actual `clang-tidy` error is, please could someone help point it out? Thanks!

**Comment by hugovk** [comment]
Actually, `clang-tidy` also fails for https://github.com/pytorch/pytorch/pull/32389, which only edited two `.py` files. Problem with the CI itself?

**Review by mrshenli — COMMENTED** [review]
changes in `benchmarks/distributed` LGTM

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Some CI still failing though

```
Oct 20 09:15:50 + python -c 'import torch; print(torch.__version__, torch.version.git_version)'
Oct 20 09:15:52 Traceback (most recent call last):
Oct 20 09:15:52   File "<string>", line 1, in <module>
Oct 20 09:15:52   File "/opt/conda/lib/python3.6/site-packages/torch/__init__.py", line 561, in <module>
Oct 20 09:15:52     import torch.multiprocessing
Oct 20 09:15:52   File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/__init__.py", line 38, in <module>
Oct 20 09:15:52     from .spawn import spawn, SpawnContext, _supports_context, start_processes, ProcessContext, \
Oct 20 09:15:52 ImportError: cannot import name '_supports_context'
```

needs a rebase as well

**Comment by hugovk** [comment]
Thanks, rebased to resolve conflicts and fixed the import error.

**Comment by ezyang** [comment]
Unfortunately this seems to be breaking internal builds. The error looks like:

```

  File "REDACTED", line 6, in <module>
    from caffe2.python.compatibility import container_abcs
ModuleNotFoundError: No module named 'caffe2.python.compatibility'
```

So it looks like other people were relying on this compatibility module :(

**Comment by ezyang** [comment]
Probably the right fix is to fix the internal code.

**Comment by ezyang** [comment]
Internal fix was pretty easy, fingers crossed.

**Pull request closed without merging**
