### PR TITLE
Expand bitwise ops to unsigned types

### LINKED ISSUE #135436: bitwise_xor  does not work for uint32
### 🐛 Describe the bug

The following code snipper produces an error when run on my MacBook Pro using Apple M2 Pro chip:
```python
a = torch.tensor(1, dtype=torch.uint32)
b = torch.tensor(2, dtype=torch.uint32)
torch.bitwise_xor(a, b)
```
The error I'm getting is:
```
Traceback (most recent call last):
  File "/Users/ashtoff/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
RuntimeError: "bitwise_xor_cpu" not implemented for 'UInt32'
```
The same for uint64 and uint16.

### Versions

Collecting environment information...
PyTorch version: 2.4.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.6.1 (arm64)
GCC version: Could not collect
Clang version: 18.1.8
CMake version: version 3.29.3
Libc version: N/A

Python version: 3.9.6 (default, Feb  3 2024, 15:58:27)  [Clang 15.0.0 (clang-1500.3.9.4)] (64-bit runtime)
Python platform: macOS-14.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] numpy==2.0.2
[pip3] torch==2.4.1
[conda] No relevant packages

### PR DESCRIPTION
**Pull request by malfet**
Fixes https://github.com/pytorch/pytorch/issues/135436

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by ezyang** [comment]
So, I will defer to you if you aren't convinced, but one of the reasons why the new macro type exists is to avoid having to define separate new macros for every new class of types like INTEGRAL. So the intended usage is AT_DISPATCH_V2, and then a list of all supported type / typesets. WDYT

**Comment by malfet** [comment]
> So, I will defer to you if you aren't convinced, but one of the reasons why the new macro type exists is to avoid having to define separate new macros for every new class of types like INTEGRAL. So the intended usage is AT_DISPATCH_V2, and then a list of all supported type / typesets. WDYT

Reason for the helper macro is to avoid repetitions (i.e. bitwise OPS should be defined for the same dtypes) and also to avoid binary size increase for mobile builds)

**Comment by vadimkantorov** [comment]
Also for bit shifts, support for unsigned dtypes makes a lot of sense, as it is more "defined" for unsigned types

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
