### PR TITLE
[dynamo] Accurately identify mutated cells captured by multiple functions

### LINKED ISSUE #138112: Dynamo fails to propagate updates to nonlocal variables across different functions
### 🐛 Describe the bug

When two functions, `A` and `B`, share a `nonlocal` variable `z`, an update in one function does not always propagate to the other. For instance, in the reproducer below, `run_fn` updates `z` to `3`. However, when `fn` assigns `k = z`, it references the old value of `z.

### Reproducer

```python
import torch

def nonlocal_test():
    z = 1
    k = 2

    def create_fn():
        def fn(x):
            nonlocal k, z
            k = z
        return fn

    def run_fn(fn, x):
        nonlocal z
        z = 3
        fn(x)
        return x.cos()

    @torch.compile(backend="eager", fullgraph=True)
    def foo(x):
        fn = create_fn()
        return run_fn(fn, x)

    x = torch.randn(2, 3)
    foo(x)
    print(f'{z=} - {k=}')
    assert z == 3
    assert k == 3  # `k` still references the previous value of `z` (1)

nonlocal_test()
```

This seems to be ok for globals.

### Versions

main

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @amjames @rec

### PR DESCRIPTION
**Pull request by StrongerXi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #138632
* #138639

This patch changes `mutated_closure_cell_contents: Set[str]` to
`mutated_closure_cell_ids: Set[int]` so that Dynamo can more accurately
identify closure cells across different instances of
`UserFunctionVariable`. This prevents Dynamo from mistakenly treat a
cell as immutable, despite it'll be mutated when referenced as closure
cell from another function.

More context in
https://github.com/pytorch/pytorch/issues/138112#issuecomment-2420580779.

Fixes #138112.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Comment by StrongerXi** [comment]
Remove obsolete documentation (addresses https://github.com/pytorch/pytorch/pull/138268#discussion_r1805504404)

**Comment by StrongerXi** [comment]
Rebase.

**Comment by StrongerXi** [comment]
Rebase.

**Comment by ezyang** [comment]
yeah imma defer to @jansel on this one

**Review by jansel — APPROVED** [review]

**Comment by StrongerXi** [comment]
Rebase

**Comment by StrongerXi** [comment]
Adding a `original_cell` field to `VariableTracker` isn't always sound, it could break `VariableTracker.clone`. So I'm using a per-instruction-translator `Dict[VariableTracker, CellType]` instead.

**Pull request closed without merging**
