### PR TITLE
Revert "Revert "Added {logical_not, trace} refs, moved logical ops to use method overloads""

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #79226
* #79225
* __->__ #79224

This reverts commit d67309aefb435930c77d45935181b3238cf5772e.

### CODE REVIEW

**Review by mruberry — APPROVED** [review]
Cool

**Comment by Chillee** [comment]
:(

**Pull request closed without merging**
