### PR TITLE
[quant][be] Add TestPT2ERepresentation test case

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #109158
* #108925
* #108924
* __->__ #108923

Summary:
att

Test Plan:
python test/test_quantization.py TestPT2ERepresentation
Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Review by andrewor14 — APPROVED** [review]

**Comment by andrewor14** [comment]
For the future, I wonder if we should even separate out these test classes into separate files (like one for QAT, one for representation)

**Review by kimishpatel — COMMENTED** [review]
Can you put this in a separate test file

**Review by kimishpatel — DISMISSED** [review]
requesting change to put it in separate file

**Comment by jerryzh168** [comment]
OK I'll split this to a separate file. for QAT since @andrewor14 has some PRs that's changing the tests so I'm not doing it yet, I can refactor that a bit later

**Pull request closed without merging**
