### PR TITLE
Use pybind11::gil_scoped_* functions instead of AutoGIL/AutoNoGIL

### LINKED ISSUE #29065: PyTorch deadlocks when freeing memory in embedded Pybind interpreter
## 🐛 Bug

When running a function that uses a PyTorch in an embedded pybind11 interpreter, freeing tensors constructed from NumPy deadlocks.

## To Reproduce
```cpp
#include <pybind11/embed.h>
#include <thread>

namespace py = pybind11;

int main() {
    py::scoped_interpreter guard{};
    auto thread = std::thread([]() {
      auto hello = py::module::import("hello");
      py::object a =  hello.attr("A")();
      a.attr("run")();
    });
    thread.join();
}
```

with `hello.py`

```python
import torch
import numpy as np
class A:
    def run(self):
        print("HELLO")
        tinput = torch.tensor(np.random.rand(100, 15))
        print("GOODBYE")
        return 5
```

Then running the binary will print `HELLO` and hang. Going into GDB, I see:

```
Thread 2 (Thread 0x7f3ceb320700 (LWP 26179)):
#0  0x00007f3ceccc0f85 in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7f3ceb31f5d0, expected=0, futex_word=0x7f3ced1f0ce8 <gil_cond+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  __pthread_cond_wait_common (abstime=0x7f3ceb31f5d0, mutex=0x7f3ced1f0d40 <gil_mutex>, cond=0x7f3ced1f0cc0 <gil_cond>) at pthread_cond_wait.c:539
#2  __pthread_cond_timedwait (cond=0x7f3ced1f0cc0 <gil_cond>, mutex=0x7f3ced1f0d40 <gil_mutex>, abstime=0x7f3ceb31f5d0) at pthread_cond_wait.c:667
#3  0x00007f3cecf9843e in take_gil () from /opt/anaconda/envs/ctrldev/lib/libpython3.6m.so.1.0
#4  0x00007f3cecf9be2a in PyEval_RestoreThread () from /opt/anaconda/envs/ctrldev/lib/libpython3.6m.so.1.0
#5  0x00007f3cecf8ca48 in PyGILState_Ensure () from /opt/anaconda/envs/ctrldev/lib/libpython3.6m.so.1.0
#6  0x00007f3ce38139ce in std::_Function_handler<void (void*), torch::utils::tensor_from_numpy(_object*)::{lambda(void*)#1}>::_M_invoke(std::_Any_data const&, void*&&) ()
   from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#7  0x00007f3ce2fc77bc in c10::deleteInefficientStdFunctionContext(void*) () from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/torch/lib/libc10.so
#8  0x00007f3ce2fd0e9d in c10::TensorImpl::release_resources() [clone .localalias.187] () from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/torch/lib/libc10.so
#9  0x00007f3ce33acd99 in c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::reset_() () from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#10 0x00007f3ce380c401 in torch::utils::(anonymous namespace)::internal_new_from_data(c10::TensorTypeId, c10::ScalarType, c10::optional<c10::Device>, _object*, bool, bool, bool, bool) ()
   from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#11 0x00007f3ce380da4a in torch::utils::tensor_ctor(c10::TensorTypeId, c10::ScalarType, _object*, _object*) () from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#12 0x00007f3ce33efb70 in torch::autograd::THPVariable_tensor(_object*, _object*, _object*) () from /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#13 0x00007f3ced0b4c1b in _PyCFunction_FastCallDict () from /opt/anaconda/envs/ctrldev/lib/libpython3.6m.so.1.0
#14 0x00007f3cecf9b9e9 in call_function () from /opt/anaconda/envs/ctrldev/lib/libpython3.6m.so.1.0
#15 0x00007f3cecf9f531 in _PyEval_EvalFrameDefault () from /opt/anaconda/envs/ctrldev/lib/libpython3.6m.so.1.0
#16 0x00007f3cecf99d80 in _PyFunction_FastCall () from /opt/anaconda/envs/ctrldev/lib/libpython3.6m.so.1.0
#17 0x00007f3cecf9b660 in _PyFunction_FastCallDict () from /opt/anaconda/envs/ctrldev/lib/libpython3.6m.so.1.0
#18 0x00007f3ced0c03af in _PyObject_FastCallDict () from /opt/anaconda/envs/ctrldev/lib/libpython3.6m.so.1.0
#19 0x00007f3ced0c0f3e in _PyObject_Call_Prepend () from /opt/anaconda/envs/ctrldev/lib/libpython3.6m.so.1.0
#20 0x00007f3ced0c0fb8 in PyObject_Call () from /opt/anaconda/envs/ctrldev/lib/libpython3.6m.so.1.0
#21 0x000055a2dfb73d82 in pybind11::detail::simple_collector<(pybind11::return_value_policy)1>::call (this=0x7f3ceb31fd70, ptr=0x7f3ceb539988)
    at /home/alan/.conan/data/pybind11/2.3.0/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/cast.h:1953
#22 0x000055a2dfb70b7c in pybind11::detail::object_api<pybind11::detail::accessor<pybind11::detail::accessor_policies::str_attr> >::operator()<(pybind11::return_value_policy)1> (this=0x7f3ceb31fdd0)
    at /home/alan/.conan/data/pybind11/2.3.0/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11/cast.h:2108
#23 0x000055a2dfb62447 in <lambda()>::operator()(void) const (__closure=0x55a2dfe70798) at /home/alan/workspace/scratch/main.cpp:12
#24 0x000055a2dfb627a8 in std::__invoke_impl<void, main()::<lambda()> >(std::__invoke_other, <lambda()> &&) (__f=...) at /usr/include/c++/8/bits/invoke.h:60
#25 0x000055a2dfb625cc in std::__invoke<main()::<lambda()> >(<lambda()> &&) (__fn=...) at /usr/include/c++/8/bits/invoke.h:95
#26 0x000055a2dfb633c8 in std::thread::_Invoker<std::tuple<main()::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x55a2dfe70798) at /usr/include/c++/8/thread:244
#27 0x000055a2dfb63389 in std::thread::_Invoker<std::tuple<main()::<lambda()> > >::operator()(void) (this=0x55a2dfe70798) at /usr/include/c++/8/thread:253
#28 0x000055a2dfb6335e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<main()::<lambda()> > > >::_M_run(void) (this=0x55a2dfe70790) at /usr/include/c++/8/thread:196
#29 0x00007f3ced37e19d in std::execute_native_thread_routine (__p=0x55a2dfe70790) at /home/nwani/m3/conda-bld/compilers_linux-64_1560109574129/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#30 0x00007f3ceccba6db in start_thread (arg=0x7f3ceb320700) at pthread_create.c:463
#31 0x00007f3cec9e388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
****
```

In our actual application, I was able to hack around this by using the following function instead of `torch.tensor` or `torch.as_tensor`:
```python
def copy_without_deadlock(xs: np.ndarray) -> torch.Tensor:
    out = torch.zeros(xs.shape)
    for index in np.ndindex(*xs.shape):
        out[index] = float(xs[index])
    return out
```

which "works" fine.

## Expected behavior

Deallocating the data does not deadlock.

## Environment

```
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.3
[pip] torch==1.3.0
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.3.0               py3.7_cpu_0  [cpuonly]  pytorch
```

cc @ezyang @gchanan @zou3519 @jerryzh168

### PR DESCRIPTION
**Pull request by alanhdu**
Given that pybind11 implements these gil functions, I don't think it makes sense for Pytorch to have its own bespoke versions.

Fixes #29065

### CODE REVIEW

**Comment by ezyang** [comment]
For reference, old versions:

```
// Acquires the GIL on construction
struct AutoGIL {
  AutoGIL() : gstate(PyGILState_Ensure()) {
  }
  ~AutoGIL() {
    PyGILState_Release(gstate);
  }

  PyGILState_STATE gstate;
};

// Releases the GIL on construction
struct AutoNoGIL {
  AutoNoGIL() : save(PyEval_SaveThread()) {
  }
  ~AutoNoGIL() {
    PyEval_RestoreThread(save);
  }

  PyThreadState* save;
};
```

New versions:

```
/* The functions below essentially reproduce the PyGILState_* API using a RAII
 * pattern, but there are a few important differences:
 *
 * 1. When acquiring the GIL from an non-main thread during the finalization
 *    phase, the GILState API blindly terminates the calling thread, which
 *    is often not what is wanted. This API does not do this.
 *
 * 2. The gil_scoped_release function can optionally cut the relationship
 *    of a PyThreadState and its associated thread, which allows moving it to
 *    another thread (this is a fairly rare/advanced use case).
 *
 * 3. The reference count of an acquired thread state can be controlled. This
 *    can be handy to prevent cases where callbacks issued from an external
 *    thread would otherwise constantly construct and destroy thread state data
 *    structures.
 *
 * See the Python bindings of NanoGUI (http://github.com/wjakob/nanogui) for an
 * example which uses features 2 and 3 to migrate the Python thread of
 * execution to another thread (to run the event loop on the original thread,
 * in this case).
 */

class gil_scoped_acquire {
public:
    PYBIND11_NOINLINE gil_scoped_acquire() {
        auto const &internals = detail::get_internals();
        tstate = (PyThreadState *) PYBIND11_TLS_GET_VALUE(internals.tstate);

        if (!tstate) {
            /* Check if the GIL was acquired using the PyGILState_* API instead (e.g. if
               calling from a Python thread). Since we use a different key, this ensures
               we don't create a new thread state and deadlock in PyEval_AcquireThread
               below. Note we don't save this state with internals.tstate, since we don't
               create it we would fail to clear it (its reference count should be > 0). */
            tstate = PyGILState_GetThisThreadState();
        }

        if (!tstate) {
            tstate = PyThreadState_New(internals.istate);
            #if !defined(NDEBUG)
                if (!tstate)
                    pybind11_fail("scoped_acquire: could not create thread state!");
            #endif
            tstate->gilstate_counter = 0;
            PYBIND11_TLS_REPLACE_VALUE(internals.tstate, tstate);
        } else {
            release = detail::get_thread_state_unchecked() != tstate;
        }

        if (release) {
            /* Work around an annoying assertion in PyThreadState_Swap */
            #if defined(Py_DEBUG)
                PyInterpreterState *interp = tstate->interp;
                tstate->interp = nullptr;
            #endif
            PyEval_AcquireThread(tstate);
            #if defined(Py_DEBUG)
                tstate->interp = interp;
            #endif
        }

        inc_ref();
    }

    void inc_ref() {
        ++tstate->gilstate_counter;
    }

    PYBIND11_NOINLINE void dec_ref() {
        --tstate->gilstate_counter;
        #if !defined(NDEBUG)
            if (detail::get_thread_state_unchecked() != tstate)
                pybind11_fail("scoped_acquire::dec_ref(): thread state must be current!");
            if (tstate->gilstate_counter < 0)
                pybind11_fail("scoped_acquire::dec_ref(): reference count underflow!");
        #endif
        if (tstate->gilstate_counter == 0) {
            #if !defined(NDEBUG)
                if (!release)
                    pybind11_fail("scoped_acquire::dec_ref(): internal error!");
            #endif
            PyThreadState_Clear(tstate);
            PyThreadState_DeleteCurrent();
            PYBIND11_TLS_DELETE_VALUE(detail::get_internals().tstate);
            release = false;
        }
    }

    PYBIND11_NOINLINE ~gil_scoped_acquire() {
        dec_ref();
        if (release)
           PyEval_SaveThread();
    }
private:
    PyThreadState *tstate = nullptr;
    bool release = true;
};

class gil_scoped_release {
public:
    explicit gil_scoped_release(bool disassoc = false) : disassoc(disassoc) {
        // `get_internals()` must be called here unconditionally in order to initialize
        // `internals.tstate` for subsequent `gil_scoped_acquire` calls. Otherwise, an
        // initialization race could occur as multiple threads try `gil_scoped_acquire`.
        const auto &internals = detail::get_internals();
        tstate = PyEval_SaveThread();
        if (disassoc) {
            auto key = internals.tstate;
            PYBIND11_TLS_DELETE_VALUE(key);
        }
    }
    ~gil_scoped_release() {
        if (!tstate)
            return;
        PyEval_RestoreThread(tstate);
        if (disassoc) {
            auto key = detail::get_internals().tstate;
            PYBIND11_TLS_REPLACE_VALUE(key, tstate);
        }
    }
private:
    PyThreadState *tstate;
    bool disassoc;
};
```

Thus, this diff has substantive changes to GIL behavior.

#23490 may be related.

**Comment by ezyang** [comment]
@alanhdu Would you mind doing a quick benchmark to show that there is no regression in performance from using the pybind11? GIL acquire/release is very important and it doesn't look like this is bit-for-bit the same.

**Comment by alanhdu** [comment]
I don't have access to a CUDA machine (we do all our GPU training in the cloud, which isn't great for benchmarking), so I wasn't able to run the Pytorch benchmark suite. Instead, I did a super unscientific benchmark using the `cifar10_tutorial` (code is https://gist.github.com/alanhdu/b2e16348f1faccde4f21fa45420e4534). This is run against `USE_CUDA=0 python setup.py develop` with Turboboost turned off and the CPU governor set to performance.

On the current branch, I get:

``
$ python cifar10_tutorial.py 
Files already downloaded and verified
Files already downloaded and verified
100%|███████████████████████| 12500/12500 [01:17<00:00, 160.89it/s]
```

and on 496d23224f45b58dc95eddd3ccee3e00cda1ae1a, I get

```
$ python cifar10_tutorial.py 
Files already downloaded and verified
Files already downloaded and verified
100%|███████████████████████| 12500/12500 [01:19<00:00, 156.31it/s]
Finished Training
```

I ran each benchmark 3 times, and the difference seems to be within noise range (although I didn't get enough to do actual statistics).

This isn't super scientific, but this at least suggests that the patch isn't going to totally kill performance. @ezyang -- do you have a more rigorous benchmark that you'd like to see?

**Comment by ezyang** [comment]
No, that seems sufficient to me.

**Review by ezyang — APPROVED** [review]
There may be external to PyTorch uses of AutoGIL/AutoNoGIL. If so, we will have to retain the structs for BC (with a deprecated warning on them). I will test on our internal codebase to see if this is the case.

**Comment by ezyang** [comment]
This is going to need some internal fixes.

**Comment by alanhdu** [comment]
@ezyang: I've filed https://github.com/pytorch/xla/pull/1290 against the XLA repository -- is there anything else I can do to make life easier?

**Review by zdevito — COMMENTED** [review]
Nothing seems obviously wrong to me. Scoped release looks like it does the same thing. Scoped acquire is making different calls, so I don't know if it does the same thing, but both AutoGIL and scoped_aquire are documented to do the same thing. Agree about leaving the structs for clients that were using it.

**Comment by ezyang** [comment]
@alanhdu Yes, if you can bring back the old structs, and just mark them as deprecated using `C10_DEPRECATED`, I'd probably able to land this directly. Otherwise I will need to find time to fix the internal call sites, but we have 1.3.1 release coming up and our Windows builds are on fire, so it won't be for a bit.

**Comment by alanhdu** [comment]
@ezyang Done!

**Comment by alanhdu** [comment]
I've rebased onto master and fixed the merge conflicts.

**Comment by soumith** [comment]
apparently the CI tests were failing on this PR as it was landed (and hence it broke master), so it was reverted.

**Comment by mruberry** [comment]
Reopening (since this was reverted)

**Comment by heiner** [comment]
Thanks for this! This seems to fix an issue about threads started in C++ calling Python functions calling into PyTorch calling into CUDA. There's something about `gil_scoped_acquire` that works better than `AutoGIL`.

**Pull request closed without merging**
