### PR TITLE
Optimizer Limited Symmetric Rank 1

### PR DESCRIPTION
**Pull request by EddyB1337**
a new optimizer with an implementation of the Limited Symmetric rank 1 update.

Its very efficient and fast. Its like torch.optim.LBFGS but better. I hope you will share this.

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by ezyang** [comment]
This PR cannot be merged as is (eg the ipynb check in needs to be removed). I don't know if we're likely to merge it with fixes either.

**Comment by albanD** [comment]
For new optimizers, we would ask if there is some publication that explain the benefit of the given optimizer and if we can show that it is used widely within the community?
@EddyB1337 could you share more details on this by any chance?

**Comment by EddyB1337** [comment]
Hello @alban, yeah I get the code from https://optimization-online.org/2022/01/8760/. Im not sure if its widely used, but the results are okay and the runtime is good for the fact that it use a approximate hessian matrix.

I am a noob with github and merging. Maybe the new version is working. Can you help me with the technical details?

**Comment by EddyB1337** [comment]
Im very sorry that I dont post a documentation yet. I need more time cause this is lot mathematic staff.

**Comment by lezcano** [comment]
I think this sort of contribution would be much better suited as an external package on an external repo with its own testing and docs. As Alban said, we usually just add optimisers to core that are widely used. 
If this package then gets enough traction, we can then reconsider adding it to core. How does this sound @EddyB1337?

**Pull request closed without merging**
