### PR TITLE
move median to ATen

### PR DESCRIPTION
**Pull request by t-vi**
This moves median to ATen.

- median with dimension reduces to kthvalue
- median without dimension (aka medianall) is implemented in parallel to kthvalue because we would not want to reshape (copying for non-contiguous) and then copy again in kthvalue. We can sue the helper functions we moved from kthvalue.
- `median_cuda` was accidentally already put into ATen in #17544.
- The quickselect algorthm without indices for CPU in TH is now obsolete and removed.

### CODE REVIEW

**Comment by izdeby** [comment]
@t-vi, im pretty new to the project so i'm a bit confused with your choice of where the 'new' methods should be placed.

I see that there are 'cpu' and 'cuda' folders under aten/src/Aten/native/... and in your previous [PR #17544](https://github.com/pytorch/pytorch/pull/17544), you've placed 'median_cuda' in  aten/src/ATen/native/**cuda**/SortingKthValue.cu while in this one you are putting most of the stuff in native folder while i would expect it to be in native/cpu, for the cpu related code. So here are couple questions: 

1. why not put median_cpu under Aten/native/cpu? 
2. i should have caught it in the previous PR, but why is median_cuda placed in SortingKthValue.cu? Should all median related logic be places in its own file?

**Comment by t-vi** [comment]
As far as I know, we do have "plain" cpu versions in `native/` and accelerated (AVX etc.) cpu versions in the `native/cpu` folder (that seems to be consistent with the comments at the top of the [native/cpu/README.md](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/README.md)).

For `median_cuda` not getting its own file: In ATen we do seem to accumulate functions topically - e.g. ReduceOps.* has lots of reduce ops. Now I would have loved to do a single Sorting.cu (and indeed I did that in the beginning), but that 1) would have been extraordinarily large compared to the files in the same directory, 2) ran into compile problems on ROCm that I didn't fully analyse but which seemed to be related to overly large files. Thus I ended splitting up the Sorting.cu into smaller units. To me, `median` is mostly a special case of KthValue, so I left it there.

**Comment by izdeby** [comment]
I see, thanks for clarifying!

**Review by izdeby — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Comment by t-vi** [comment]
Thanks for looking at this. I'll do a proper rebase tomorrow or so.

**Comment by ezyang** [comment]
@gchanan, do you know off the top of your head why this code is still failing to compile after the BC-fix?

**Comment by gchanan** [comment]
@ezyang looking into it.

**Comment by gchanan** [comment]
oh, it's not related to the dispatch macro, the problem is inside the dispatch macro.  The `quick_select_template` got another parameter in the meantime but it's not updated in this PR.

**Comment by t-vi** [comment]
@gchanan Thanks for looking at this. I should have known...
@ezyang I'm inclined to say the build failures are unrelated, so we might merge this to get the next bit.

**Comment by t-vi** [comment]
Hmhm. Did landing this did go wrong a second time?

**Comment by ezyang** [comment]
I'll kick it tomorrow

**Pull request closed without merging**
