### PR TITLE
[Easy] Refactor post grad application of passes

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #139295
* __->__ #139293
* #139292

Refactors GraphTransformObserver to hook into the bisect manager pass application. And reworks post grad passes to use it.

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv @voznesenskym @penguinwu @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by exclamaforte — APPROVED** [review]
nice, lgtm

**Comment by ezyang** [comment]
@exclamaforte you need to add yourself to the metamate group

**Comment by exclamaforte** [comment]
Done mb

**Pull request closed without merging**
