### PR TITLE
Update MultiHeadAttention docstring

### PR DESCRIPTION
**Pull request by vfdev-5**
Fixes MultiHeadAttention docstring.

Currently, https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html#torch.nn.MultiheadAttention
is 

Screen Shot 2020-12-29 at 21 06 43

and with the fix will be

Screen Shot 2020-12-29 at 22 41 35

### CODE REVIEW

**Review by zhangguanheng66 — CHANGES_REQUESTED** [review]
I prefer the "note" out of the bullets and start as a separate paragraph. You might remove the indent of the original.

**Comment by vfdev-5** [comment]
> I prefer the "note" out of the bullets and start as a separate paragraph. You might remove the indent of the original.

I was thinking about that in the begining and my reasoning is that this note is about input arguments and its special behaviour and not the function itself and its behaviour... I do not have a strong opinion about that and can submit a fix with 
```python
    Args:
        ...
        kdim: total number of features in key. Default: None.
        vdim: total number of features in value. Default: None.

    Note: 
        If kdim and vdim are None, they will be set to embed_dim such that 
        query, key, and value have the same number of features.
```

**Comment by zhangguanheng66** [comment]
> > I prefer the "note" out of the bullets and start as a separate paragraph. You might remove the indent of the original.
> 
> I was thinking about that in the begining and my reasoning is that this note is about input arguments and its special behaviour and not the function itself and its behaviour... I do not have a strong opinion about that and can submit a fix with
> 
> ```python
>     Args:
>         ...
>         kdim: total number of features in key. Default: None.
>         vdim: total number of features in value. Default: None.
> 
>     Note: 
>         If kdim and vdim are None, they will be set to embed_dim such that 
>         query, key, and value have the same number of features.
> ```

The note is talking about kdim and vdim so technically it shouldn't stay with the bullet of vdim. You can just start with a plain paragraph for the note.

**Comment by vfdev-5** [comment]
@zhangguanheng66 how about that ?

Screen Shot 2021-01-01 at 21 43 38

**Comment by zhangguanheng66** [comment]
> @zhangguanheng66 how about that ?
> 
> Screen Shot 2021-01-01 at 21 43 38

Yup. LGTM.

**Review by zhangguanheng66 — APPROVED** [review]

**Pull request closed without merging**
