### PR TITLE
Add mock.patch() to clear environment for test

### LINKED ISSUE #53526: test/distributed/test_c10d.py::RendezvousEnvTest::test_common_errors is failing sometimes
Error message (from [this job](https://app.circleci.com/pipelines/github/pytorch/pytorch/281757/workflows/3cb10958-9cbb-456a-a7ac-820ff52028ea/jobs/11350539)):

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1492, in wrapper
    return func(*args, **kwargs)
  File "distributed/test_c10d.py", line 507, in test_common_errors
    next(gen)
AssertionError: ValueError not raised
```

According to [the HUD](https://ezyang.github.io/pytorch-ci-hud/build2/pytorch-master), this is the timeline:

- c0adabe172935030bf748157965a9899b88f68f1 test started failing
- f595ba1bae9a75c6403e4624e7294b5635acd40c test stopped failing
- 8c798e062216278673a75bac0848ea69a8bd3f03 test started failing again
- 1fe6a6507e6a38534f0dc6265fd44cd26c80e5b0 test switched from shard 2 to shard 1

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#53537 Add mock.patch() to clear environment for test**

fixes #53526

This fixes the issue of the one of the environment variables being tested is somehow set by a previous test. For example:
`WORLD_SIZE=1 python test/distributed/test_c10d.py RendezvousEnvTest.test_common_errors` would have previously failed but now passes

Differential Revision: [D26891207](https://our.internmc.facebook.com/intern/diff/D26891207)

### CODE REVIEW

**Comment by samestep** [comment]
Context: this is meant to resolve #53526.

**Review by samestep — APPROVED** [review]

**Review by samestep — CHANGES_REQUESTED** [review]
Actually, could you rebase this onto `master` and then remove the `skipIf` to reenable this test?

**Review by samestep — APPROVED** [review]

**Comment by H-Huang** [comment]
Going to wait for CI tests to pass. I'm not sure if clearing the environment for this test case will cause any unexpected behavior

**Comment by malfet** [comment]
@H-Huang can you also please add asserts to the test body to validate that  `os.getenv("WORLD_SIZE") == None` and so on?

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
