### PR TITLE
[AMD] use rccl.h instead of rccl/rccl.h

### PR DESCRIPTION
**Pull request by xw285cornell**
Summary: We hipify NCCLUtils.h from nccl.h to rccl/rccl.h. This follows the format of the rocm rpm suite (the header is in include/rccl/rccl.h), however the source code is just src/rccl.h. Using the rccl/rccl.h will make us find the rpm's header but not the src code's header.

Test Plan:
buck run mode/opt-amd-gpu -c hpc_comms.use_rccl=develop -c fbcode.split-dwarf=True  --config rccl.build_rdma_core=true --config rccl.adhoc_brcm=true  //aps_models/ads/icvr:icvr_launcher -- mode=local_ctr_cvr_cmf_rep_1000x_v1_no_atom   data_loader.dataset.table_ds=[2024-09-04]   data_loader.dataset.batch_size=512  max_ind_range=10

w/o this diff, it'll show 2.18 nccl version

Differential Revision: D62371434

### CODE REVIEW

**Comment by houseroad** [comment]
rocm ci is failing?

**Comment by jithunnair-amd** [comment]
@xw285cornell Can you provide a link to the file you refer to in your comment "the source code is just src/rccl.h"?

**Comment by xw285cornell** [comment]
@jithunnair-amd i think it's generated from https://github.com/ROCm/rccl/blob/develop/src/nccl.h.in

**Review by jeffdaily — APPROVED** [review]

**Review by cenzhaometa — APPROVED** [review]
lgtm

**Pull request closed without merging**
