### PR TITLE
Parallel for quantize_tensor/dequantize_tensor

### PR DESCRIPTION
**Pull request by liangan1**
The dequantize/quantize op is implemented with single thread  and these dequantize/quantize ops will be the performance bottleneck when they are frequently used in int8 model.  We have submitted an [ issue](https://github.com/pytorch/FBGEMM/issues/142) to FBGEMM and @dskhudia  agreed with our analysis. 
We fixed this issue by using at::parallel_for  and  the performance get much improvement. We are enabling BERT int8 model. The CPU avg time  reduced to 113us from 1.926ms for dequantize and reduced to 43us from 572us for quantize.  The profile details can be found in the attach files. 
[before_parallel_MRPC_bs8_clx.log](https://github.com/pytorch/pytorch/files/3869311/before_parallel_MRPC_bs8_clx.log)
[parallel_MRPC_bs8_clx.log](https://github.com/pytorch/pytorch/files/3869312/parallel_MRPC_bs8_clx.log)

### CODE REVIEW

**Comment by liangan1** [comment]
@jerryzh168  @z-a-f Please help to review our PR. Thanks.

**Comment by liangan1** [comment]
@jerryzh168 @z-a-f Please help to review our PR. Thanks.

**Comment by z-a-f** [comment]
I literally just saw this PR. Please, click on the `Reviewers` on the right of the page -- that notifies us :) Sorry about that.

image

**Comment by zou3519** [comment]
@z-a-f I'm not sure most contributors have the permissions to add reviewers so I think the current workflow is to listen for github notifications

**Comment by z-a-f** [comment]
> @z-a-f I'm not sure most contributors have the permissions to add reviewers so I think the current workflow is to listen for github notifications

Oh, my bad! I was not monitoring the mentions at all. Will do from now on.

**Comment by z-a-f** [comment]
LGTM, will wait for @jerryzh168 before landing

**Comment by dskhudia** [comment]
@z-a-f This PR looks fine as is. Anothe alternative is to make fbgemm::Quantize/fbgemm::Dequantize take thread_id/num_threads argument and parallelize.

**Comment by z-a-f** [comment]
> @z-a-f This PR looks fine as is. Anothe alternative is to make fbgemm::Quantize/fbgemm::Dequantize take thread_id/num_threads argument and parallelize.

I will land it as is -- we can create an issue with your suggestion. it could be low-pri. What do you think?

**Review by z-a-f — APPROVED** [review]
LGTM

**Comment by dskhudia** [comment]
> > @z-a-f This PR looks fine as is. Anothe alternative is to make fbgemm::Quantize/fbgemm::Dequantize take thread_id/num_threads argument and parallelize.
> 
> I will land it as is -- we can create an issue with your suggestion. it could be low-pri. What do you think?

Sounds good.

**Comment by jerryzh168** [comment]
LGTM but I think it will be better to support this in fbgemm since that's the lower level library and it's cleaner to delegate as much perf optimizations to it as possible so in case there are other libraries using fbgemm they will get the benefit as well.

**Comment by jerryzh168** [comment]
Do we have benchmarking tests for this @z-a-f ?

**Comment by z-a-f** [comment]
> LGTM but I think it will be better to support this in fbgemm since that's the lower level library and it's cleaner to delegate as much perf optimizations to it as possible so in case there are other libraries using fbgemm they will get the benefit as well.

I agree -- I created an issue #32006 to factor this out into fbgemm (assigned to @dskhudia). Meanwhile, I think we can benefit from some parallelization. The benchmarks are provided by the OP:
- https://github.com/pytorch/pytorch/files/3869311/before_parallel_MRPC_bs8_clx.log
- https://github.com/pytorch/pytorch/files/3869312/parallel_MRPC_bs8_clx.log

**Comment by jerryzh168** [comment]
yeah I mean do we have benchmarks for this in PyTorch? I remember you were creating benchmarks for quantized kernels before

**Comment by hongzhen1** [comment]
> LGTM but I think it will be better to support this in fbgemm since that's the lower level library and it's cleaner to delegate as much perf optimizations to it as possible so in case there are other libraries using fbgemm they will get the benefit as well.

@jerryzh168 @z-a-f thanks for your reply, per Jerry's suggestion, alternative solution is to support this parallel_for in fbgemm, while this PR aligns with qconv, qlinear currently, so there will be plans to support full parallel_for for all fbgemm kernels, right?

**Comment by jamesr66a** [comment]
Can we get some benchmarks for this with threads set to 1 to ensure we don't regress the single-thread performance? Most of our use cases are single-threaded and we need to ensure the parallel_for overhead isn't too great

**Comment by z-a-f** [comment]
@hongzhen1 @liangan1 Can you run the same benchmarks but for a single thread?

**Comment by hongzhen1** [comment]
> @hongzhen1 @liangan1 Can you run the same benchmarks but for a single thread?

OK, we will attach single thread performance data. 
there is no difference between this PR and qconv and qlinear design, right ？
so from your side, according to the context, do you have any plan to enable parallel in FBGEMM?

**Comment by liangan1** [comment]
@z-a-f 
 The average CPU time  w/o parallel_for using single thread on bert_large int8 model(MRPC) are as follows(repeated 5 times) :

| operator  | with parallel_for |without parallel_for 
| ------------- | ------------- |---------------|
| quantize_per_tensor  |   54.5994us|52.9634us|
|  dequantize | 194.961us|193.255us|

From the above result, we can see that there is additional less than 2us workload with parallel_for function for quantize/dequantize op when we use single thread. 


 
[parallel_for_single_thread_mrpc_profiler.log](https://github.com/pytorch/pytorch/files/4057725/parallel_for_single_thread_mrpc_profiler.log)
[no_parallel_for_single_thread_mrpc_profiler.log](https://github.com/pytorch/pytorch/files/4057726/no_parallel_for_single_thread_mrpc_profiler.log)

**Comment by z-a-f** [comment]
> > @hongzhen1 @liangan1 Can you run the same benchmarks but for a single thread?
> 
> OK, we will attach single thread performance data.
> there is no difference between this PR and qconv and qlinear design, right ？
> so from your side, according to the context, do you have any plan to enable parallel in FBGEMM?

I think @jianyuh was working on that.

**Comment by hongzhen1** [comment]
> > > @hongzhen1 @liangan1 Can you run the same benchmarks but for a single thread?
> > 
> > 
> > OK, we will attach single thread performance data.
> > there is no difference between this PR and qconv and qlinear design, right ？
> > so from your side, according to the context, do you have any plan to enable parallel in FBGEMM?
> 
> I think @jianyuh was working on that.

thank you @z-a-f

**Comment by z-a-f** [comment]
@jianyuh Can you please, take a look at the conflict, and resolve it if possible? Otherwise, we can close it as resolved.

**Comment by jianyuh** [comment]
@z-a-f Sorry I just saw this PR. Please check https://github.com/pytorch/pytorch/pull/33765, as @dskhudia just merged the similar PR to parallelize quantize_tensor / dequantize_tensor.

**Comment by jianyuh** [comment]
This PR is partially merged through https://github.com/pytorch/pytorch/pull/33765. Closing.

**Pull request closed without merging**
