### PR TITLE
[DO NOT DELETE OR MERGE] Nightly release

### PR DESCRIPTION
**Pull request by ezyang**
See https://github.com/pytorch/pytorch/issues/26817 for what this is

FB only: Chronos job page: https://our.internmc.facebook.com/intern/chronos/job?smc=chronos_gp_admin_client&jobname=nightly_trigger (click "Run Now" to manually trigger a nightly)

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @malfet @seemethere @svekars @carljparker @bhosmer @smessmer @ljk53 @bdhirsh @jbschlosser @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @Xia-Weiwen @leslie-fang-intel @albanD @mruberry @walterddr @mikaylagawarecki @mingfeima @XiaobingSuper @ashokei @jingxu10 @pytorch/pytorch-dev-infra @mcarilli @ptrblck @soumith @voznesenskym @penguinwu @anijain2305 @Guobing-Chen @zhuhaozhe @blzheng @jiayisunx @desertfire @kshitij12345 @saketh-are @VitalyFedyunin @mlazos @yanboliang @chunyuan-w @jansel @lezcano @fdrocha

### CODE REVIEW

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit 4e8f1b5:
* 0/71 flaky
* 34/71 broken upstream



Here are the [reasons each build failed](https://dr.pytorch.org/commit-details.html?sha1=4e8f1b5ee3c58e9937e01475313ca0250813c98e).

---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Comment by ezyang** [comment]
Example log: https://app.circleci.com/pipelines/github/pytorch/pytorch/190074/workflows/bf36ca5c-50f4-45ae-ae0f-d1c5d38f7e52/jobs/6217176/steps

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/41144 removed nvidia runtime installs and I'm guessing it's the culprit.

**Comment by malfet** [comment]
Actually, I wonder if time have come to delete this one, as we've fully migrated to GHA and there are no need for CircleCI secrets provisioning.
cc: @seemethere , @izaitsevfb

**Comment by malfet** [comment]
Closing, as this should no longer be necessary with GHA nighly builds

**Pull request closed without merging**
