### PR TITLE
Re-enable xla workflow

### PR DESCRIPTION
**Pull request by yeounoh**
Re-enables xla workflow after addressing https://github.com/pytorch/xla/issues/4535. The pytorch/xla repo is [green](https://app.circleci.com/pipelines/github/pytorch/xla/16130/workflows/aabf6879-b510-47e1-8abb-b3cf8398957a/jobs/38162) again after GitHub resolved the outage.

cc @bdhirsh

### CODE REVIEW

**Comment by yeounoh** [comment]
We started seeing a new test failure (an existing test):
```
ERROR: test_view_copy_out_xla (__main__.TestViewOpsXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 401, in instantiated_test
    result = test(self, **param_kwargs)
  File "/tmp/pytorch/xla/test/../../test/test_view_ops.py", line 949, in test_view_copy_out
    torch.split_copy(a, 2, out=(out1, out2))
RuntimeError: Expected out tensor to have device cpu, but got xla:0 instead
```

This is pytorch test we run, and likely also fail in the upstream. @clee2000 @malfet maybe should we reinstate the xla worfklow so to block/prevent this kind of regression, or you prefer fixing this first before?

**Comment by clee2000** [comment]
> We started seeing a new test failure (an existing test):
> 
> ```
> ERROR: test_view_copy_out_xla (__main__.TestViewOpsXLA)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
>     raise rte
>   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_device_type.py", line 401, in instantiated_test
>     result = test(self, **param_kwargs)
>   File "/tmp/pytorch/xla/test/../../test/test_view_ops.py", line 949, in test_view_copy_out
>     torch.split_copy(a, 2, out=(out1, out2))
> RuntimeError: Expected out tensor to have device cpu, but got xla:0 instead
> ```
> 
> This is pytorch test we run, and likely also fail in the upstream. @clee2000 @malfet maybe should we reinstate the xla worfklow so to block/prevent this kind of regression, or you prefer fixing this first before?

I see it failing on pytorch/pytorch right now, the cause seems to be https://github.com/pytorch/pytorch/pull/91194 and I've asked @JacobSzwejbka to submit a forward fix.  I would prefer to fix the test first before moving xla back to pull

**Review by malfet — APPROVED** [review]

**Comment by yeounoh** [comment]
Hi @clee2000 @malfet we've disabled the test for now, https://github.com/pytorch/xla/pull/4540. I think without the xla workflow re-enabled, we run the risk of more breaking PRs to land.

**Comment by clee2000** [comment]
I assume that will require the xla pin in pytorch/pytorch to change?

**Pull request closed without merging**
