### PR TITLE
Make linalg.inv composite of linalg.solve

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #80074

The `getri` kernel calls inside `getrs` so we can do so explicitly
ourselves and save ourselves from having to maintain an extra kernel.
This way we just need to optimise `lu_factor` and `lu_solve` and `inv`
will be as efficient as it can be, as it'll be choosing the best backend
to perform the factorisation and the best backend (not necessarily the
same) to perform the solve.

Fixes https://github.com/pytorch/pytorch/issues/77498

The benchmarks: https://github.com/pytorch/pytorch/pull/80074#issuecomment-1164309071

### CODE REVIEW

**Comment by Lezcano** [comment]
I run some benchmarks, and it almost always faster than the previous implementation, there's only a small regression for large batches. I'll try to fix that tomorrow and post the updated benchmarks.

**Comment by Lezcano** [comment]
The benchmarks:
We see that on CPU is almost strictly better.
On CUDA it's better for smaller matrices, but we're leaving some performance (roughly 20%) on the table from going from `gestri` to our in-house implementation of `lu_solve` via `solve_triangular`.
After looking into the implementation of `gestri` in MAGMA, which is the one that was being used, we realised that `gestri` and `gestrs` (inverse vs lu_solve) call different triangular solvers behind the scene. We see that our in-house implementation of `gestrs` via `linalg.solve_triangular` does better than `gestrs`, and it still does better than `gestri` for smaller matrices, but not for larger matrices. This means that we can potentially improve this by improving our heuristics for `solve_triangular`. Even more, MAGMA has plenty of triangular solvers. We should have bindings for more of them to have more efficient triangular solvers, which are the basis of most solvers really.

<details>
<summary>
Benchmark Results
</summary>

```
[------------ linalg.inverse cpu ------------]
                        |   master  |  this_pr
4 threads: -----------------------------------
      (1, 1, 1)         |        6  |        7
      (2, 1, 1)         |        6  |        7
      (4, 1, 1)         |        7  |        7
      (8, 1, 1)         |        8  |        7
      (16, 1, 1)        |        9  |        8
      (32, 1, 1)        |       13  |        8
      (64, 1, 1)        |       20  |       10
      (128, 1, 1)       |       35  |       10
      (512, 1, 1)       |      120  |       32
      (1024, 1, 1)      |      237  |
      (1, 2, 2)         |        6  |        7
      (2, 2, 2)         |        6  |        8
      (4, 2, 2)         |        7  |        8
      (8, 2, 2)         |        8  |        8
      (16, 2, 2)        |       10  |        8
      (32, 2, 2)        |       14  |       10
      (64, 2, 2)        |       22  |       10
      (128, 2, 2)       |       39  |       20
      (512, 2, 2)       |      140  |       42
      (1024, 2, 2)      |      264  |
      (1, 8, 8)         |        7  |        9
      (2, 8, 8)         |        8  |        9
      (4, 8, 8)         |        9  |       10
      (8, 8, 8)         |       12  |       10
      (16, 8, 8)        |       20  |       20
      (32, 8, 8)        |       32  |       33
      (64, 8, 8)        |       57  |       59
      (128, 8, 8)       |      100  |      100
      (512, 8, 8)       |      422  |      432
      (1024, 8, 8)      |      820  |
      (1, 16, 16)       |        9  |       11
      (2, 16, 16)       |       13  |       15
      (4, 16, 16)       |       19  |       22
      (8, 16, 16)       |       31  |       36
      (16, 16, 16)      |       57  |       63
      (32, 16, 16)      |      110  |      120
      (64, 16, 16)      |      205  |      229
      (128, 16, 16)     |      408  |      450
      (512, 16, 16)     |     2000  |     2000
      (1024, 16, 16)    |     3192  |
      (1, 32, 32)       |       20  |       28
      (2, 32, 32)       |       31  |       48
      (4, 32, 32)       |       55  |       90
      (8, 32, 32)       |      100  |      200
      (16, 32, 32)      |      200  |      368
      (32, 32, 32)      |      382  |      707
      (64, 32, 32)      |      800  |     1000
      (128, 32, 32)     |     2000  |     2704
      (512, 32, 32)     |     6200  |    10000
      (1024, 32, 32)    |    12000  |
      (1, 64, 64)       |       51  |       66
      (2, 64, 64)       |       90  |      110
      (4, 64, 64)       |      180  |      230
      (8, 64, 64)       |      360  |      426
      (16, 64, 64)      |      700  |      900
      (32, 64, 64)      |     1000  |     2000
      (64, 64, 64)      |     2869  |     3180
      (128, 64, 64)     |     5670  |     6100
      (512, 64, 64)     |    22900  |    24600
      (1024, 64, 64)    |    45600  |
      (1, 128, 128)     |      278  |      214
      (2, 128, 128)     |      550  |      417
      (4, 128, 128)     |     1000  |      900
      (8, 128, 128)     |     2162  |     2000
      (16, 128, 128)    |     4434  |     3809
      (32, 128, 128)    |     9000  |     9000
      (64, 128, 128)    |    20000  |    20000
      (128, 128, 128)   |    33790  |    27990
      (512, 128, 128)   |   150000  |   160000
      (1024, 128, 128)  |   288900  |
      (1, 256, 256)     |     1000  |      700
      (2, 256, 256)     |     2540  |     1000
      (4, 256, 256)     |     5000  |     2695
      (8, 256, 256)     |    10000  |     6100
      (16, 256, 256)    |    20240  |    13000
      (32, 256, 256)    |    40240  |    29190
      (64, 256, 256)    |    80000  |    60000
      (128, 256, 256)   |   160000  |   100000
      (512, 256, 256)   |   648300  |   433000
      (1024, 256, 256)  |  1294000  |
      (1, 512, 512)     |     4371  |     3679
      (2, 512, 512)     |     9000  |     8000
      (4, 512, 512)     |    17000  |    10000
      (8, 512, 512)     |    35030  |    30660
      (16, 512, 512)    |    70000  |    70000
      (32, 512, 512)    |   140000  |   100000
      (64, 512, 512)    |   288900  |   325300
      (128, 512, 512)   |   568300  |   506100
      (512, 512, 512)   |  2265000  |  1876000
      (1024, 512, 512)  |  4533000  |

Times are in microseconds (us).

[----------- linalg.inverse cuda -----------]
                        |  master  |  this_pr
4 threads: ----------------------------------
      (1, 1, 1)         |      84  |       66
      (2, 1, 1)         |      99  |       52
      (4, 1, 1)         |      76  |       52
      (8, 1, 1)         |      67  |       54
      (16, 1, 1)        |      70  |       52
      (32, 1, 1)        |      74  |       52
      (64, 1, 1)        |      80  |       53
      (128, 1, 1)       |      93  |       54
      (512, 1, 1)       |     170  |       54
      (1024, 1, 1)      |     281  |
      (1, 2, 2)         |      76  |       80
      (2, 2, 2)         |     102  |       57
      (4, 2, 2)         |      67  |       57
      (8, 2, 2)         |      71  |       57
      (16, 2, 2)        |      71  |       69
      (32, 2, 2)        |      76  |       54
      (64, 2, 2)        |      84  |       66
      (128, 2, 2)       |      90  |       56
      (512, 2, 2)       |     180  |       58
      (1024, 2, 2)      |     286  |
      (1, 8, 8)         |      90  |       59
      (2, 8, 8)         |     110  |       56
      (4, 8, 8)         |      71  |       70
      (8, 8, 8)         |      70  |       54
      (16, 8, 8)        |      74  |       56
      (32, 8, 8)        |      79  |       90
      (64, 8, 8)        |      85  |       54
      (128, 8, 8)       |     100  |       53
      (512, 8, 8)       |     180  |       54
      (1024, 8, 8)      |     297  |
      (1, 16, 16)       |      90  |       56
      (2, 16, 16)       |     120  |       56
      (4, 16, 16)       |      80  |       54
      (8, 16, 16)       |      78  |       55
      (16, 16, 16)      |      80  |       56
      (32, 16, 16)      |      84  |       53
      (64, 16, 16)      |      92  |       56
      (128, 16, 16)     |     106  |       54
      (512, 16, 16)     |     203  |       90
      (1024, 16, 16)    |     332  |
      (1, 32, 32)       |     130  |      100
      (2, 32, 32)       |     200  |      100
      (4, 32, 32)       |     315  |      100
      (8, 32, 32)       |     327  |      100
      (16, 32, 32)      |     322  |      100
      (32, 32, 32)      |     341  |      143
      (64, 32, 32)      |     343  |      128
      (128, 32, 32)     |     366  |      200
      (512, 32, 32)     |     590  |      367
      (1024, 32, 32)    |     930  |
      (1, 64, 64)       |     216  |      168
      (2, 64, 64)       |     378  |      157
      (4, 64, 64)       |     526  |      199
      (8, 64, 64)       |     536  |      282
      (16, 64, 64)      |     561  |      201
      (32, 64, 64)      |     584  |      594
      (64, 64, 64)      |     621  |      536
      (128, 64, 64)     |     720  |      700
      (512, 64, 64)     |    1900  |     2011
      (1024, 64, 64)    |    3566  |
      (1, 128, 128)     |     425  |      361
      (2, 128, 128)     |     795  |      423
      (4, 128, 128)     |    1000  |      514
      (8, 128, 128)     |    1000  |      697
      (16, 128, 128)    |    1100  |      596
      (32, 128, 128)    |    1200  |     1100
      (64, 128, 128)    |    1550  |     1000
      (128, 128, 128)   |    2277  |     2366
      (512, 128, 128)   |    7310  |     8500
      (1024, 128, 128)  |   13900  |
      (1, 256, 256)     |     985  |      845
      (2, 256, 256)     |    1920  |     1600
      (4, 256, 256)     |    2066  |     1940
      (8, 256, 256)     |    2256  |     2682
      (16, 256, 256)    |    2699  |     2394
      (32, 256, 256)    |    3411  |     3305
      (64, 256, 256)    |    5190  |     5343
      (128, 256, 256)   |    9420  |     9000
      (512, 256, 256)   |   33140  |    44070
      (1024, 256, 256)  |   64800  |
      (1, 512, 512)     |    2475  |     2232
      (2, 512, 512)     |    4950  |     3915
      (4, 512, 512)     |    5680  |     5008
      (8, 512, 512)     |    6542  |     7200
      (16, 512, 512)    |    8372  |     7400
      (32, 512, 512)    |   12100  |    12200
      (64, 512, 512)    |   19900  |    21500
      (128, 512, 512)   |   36060  |    40640
      (512, 512, 512)   |  131900  |   200000
      (1024, 512, 512)  |  259400  |

Times are in microseconds (us).
```

</details>

<details>
<summary>
Benchmark Script
</summary>

```
import torch
import pickle
import itertools
from functools import partial
from torch.utils.benchmark import Timer, Compare

name = "this_pr"
shapes = [1, 2, 8, 16, 32, 64, 128, 256, 512]
batches = [(1,), (2,), (4,), (8,), (16,), (32,), (64,), (128,), (512,)]
results = []
make_arg = partial(torch.randn, dtype=torch.float32)
devices = ("cpu", "cuda")

for device, n, batch in itertools.product(devices, shapes, batches):
    A = make_arg(batch + (n, n), device=device)
    print(A.shape)
    timer = Timer("torch.linalg.inv_ex(A)",
                  globals=globals(),
                  label=f"linalg.inverse {device}",
                  description=name,
                  sub_label=f"{tuple(A.shape)}",
                  num_threads=4)
    results.append(timer.blocked_autorange())


compare = Compare(results)
compare.trim_significant_figures()
compare.print()

with open("{}_inverse.pickle".format(name), 'wb') as f:
    pickle.dump(results, f)
```

</details>

**Comment by Lezcano** [comment]
@BowenBao  this PR is failing in an ONNX test that you wrote. Perhaps you know the cause of the failure?

**Comment by IvanYashchuk** [comment]
> The getri kernel calls inside getrs 

Why do you think so? It's certainly not true for LAPACK implementations on CPU (see [the graph of operations in Netlib's docs](http://www.netlib.org/lapack/explore-html/dd/d9a/group__double_g_ecomputational_ga56d9c860ce4ce42ded7f914fdb0683ff.html) it's completely different algorithm than just calling getrs). And I don't see `getrs` calls in MAGMA's implementation of `getri`: https://bitbucket.org/icl/magma/src/master/src/zgetri_gpu.cpp, https://bitbucket.org/icl/magma/src/master/src/zgetri_outofplace_batched.cpp

Maybe matrix of size 512x512 is too small to see the advantage of using `getri` over `getrs`. There could be also differences in the amount of required memory.

Here are the result using the script from https://github.com/pytorch/pytorch/pull/80074#issuecomment-1164309071 and this PR's branch for larger inputs on CPU:
```
|                | master | this PR |
|----------------|--------|---------|
| (512, 512)     | 2      | 2       |
| (1024, 1024)   | 8      | 8       |
| (2048, 2048)   | 48     | 50      |
| (4096, 4096)   | 336    | 332     |
| (8192, 8192)   | 2230   | 2322    |
| (16384, 16384) | 16140  | 17200   |

Times are in milliseconds (ms).
```

**Review by IvanYashchuk — APPROVED** [review]
The stats "+63 −814" well justify the removal of `getri`. Now it would make `torch.linalg.inv` even more close to NumPy because there it's implemented with the `gesv` helper function from LAPACK, that is LU factor + LU solve. If someone actually finds out the reason `getri` exists and in what situations it's better we might reconsider this decision.
Thank you very much for doing the performance checks and other investigations!

Also, there's no `getri` function in cuSOLVER.

**Comment by Lezcano** [comment]
ping @BowenBao for the failing ONNX tests

**Review by albanD — APPROVED** [review]

**Comment by Lezcano** [comment]
@wconstab This test for TensorLazy started failing:
https://github.com/pytorch/pytorch/runs/7150289165?check_suite_focus=true
any idea why?

**Comment by wconstab** [comment]
> @wconstab This test for TensorLazy started failing: https://github.com/pytorch/pytorch/runs/7150289165?check_suite_focus=true any idea why?

Not off the top of my head, would have to debug it.

The stacktrace seems to implicate functionalization though? 

```
++ exception with description "!assert_functional INTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/aten/src/ATen/FunctionalTensorWrapper.cpp":389, please report a bug to PyTorch. 
Exception raised from from_functional_tensor at /var/lib/jenkins/workspace/aten/src/ATen/FunctionalTensorWrapper.cpp:389 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x7d (0x7f2bfaae96fd in /opt/conda/lib/python3.7/site-packages/torch/bin/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0xdd (0x7f2bfaae7f3d in /opt/conda/lib/python3.7/site-packages/torch/bin/libc10.so)
frame #2: /opt/conda/lib/python3.7/site-packages/torch/bin/test_lazy() [0x4f0486]
frame #3: at::functionalization::functionalize_op_helper(c10::OperatorHandle const&, std::vector<c10::IValue, 
```

cc @bdhirsh in case he he has an idea what's going on here, otherwise let me know if you need more help.

**Comment by Lezcano** [comment]
@bdhirsh could you have a look at this one, as I'm completely stuck with those errors.

**Comment by bdhirsh** [comment]
Oh sorry I missed this @Lezcano.

Can you try removing the entry for `linalg_inv_ex` for LTC here? https://github.com/pytorch/pytorch/blob/b4e342928b85aa53a62fd3194c9aa761e7352c8a/aten/src/ATen/native/ts_native_functions.yaml#L200

And then delete the corresponding kernel here: https://github.com/pytorch/pytorch/blob/b4e342928b85aa53a62fd3194c9aa761e7352c8a/torch/csrc/lazy/ts_backend/ts_native_functions.cpp#L495

**Comment by Lezcano** [comment]
Thank you @bdhirsh! Let's see how it goes.

@BowenBao @shubhambhokare1 I'm removing the offending ONNX test due to lack of activity. It can be added again in a later PR.

**Comment by Lezcano** [comment]
CC @justinchuby @AllenTiTaiWang about the ONNX test failure in case they can help and we can fix it rather than remove it.

**Comment by justinchuby** [comment]
Could you add a unittest.skip to the test and create an issue for it? This way the PR can be unblocked, and we can take a closer look after. Thanks!

**Comment by Lezcano** [comment]
@JackCaoG this one also needs a companion PR in XLA lol

**Comment by JackCaoG** [comment]
I think the change would be pretty similar to LTC one. PyTorch/XLA lowers both `inverse` and `linalg_inv_ex`. It seem like inverse is fine (PyTorch/XLA can still lower it), but `linalg_inv_ex` can be removed since it is composite? 

If that's the case you want to 
1. remove https://github.com/pytorch/xla/blob/master/xla_native_functions.yaml#L348
2. remove https://github.com/pytorch/xla/blob/master/torch_xla/csrc/aten_xla_type.cpp#L3544

I think this op is added by @bdhirsh for the functionalization pass but I think we can remove it for now. That should be all you need to do for this pr. If you can create the pr, CI should let us know if everything else works.

**Comment by Lezcano** [comment]
`linalg_inv_ex` is not composite, but a structured kernel. Does that change anything?

**Comment by JackCaoG** [comment]
The xla failure in this pr was caused by something else, can you rerun the xla CI and see if it will fail?

**Comment by Lezcano** [comment]
@JackCaoG there's still the same failure: https://github.com/pytorch/pytorch/runs/7373639568?check_suite_focus=true

**Comment by JackCaoG** [comment]
Ah OK, I think the error is
```
at::native::linalg_inv_ex
```

which can be solved if you remove if you follow my comment in https://github.com/pytorch/pytorch/pull/80074#issuecomment-1186001382 and remove the corresponding lowering.

**Review by malfet — APPROVED** [review]
xla commit pin changes are temporary, aren't they? (I.e. it should be a hash sum of the commit not the tag name, isn't it?)

**Comment by Lezcano** [comment]
@JackCaoG mentioned in https://github.com/pytorch/xla/pull/3901#pullrequestreview-1079257289 that it'd be enough to put the branch name, but I guess it is not? :/

**Comment by JackCaoG** [comment]
I think newest hash of the pt/xla pr or branch name of pt/xla pr should both work.

**Comment by JackCaoG** [comment]
FYI https://github.com/pytorch/pytorch/pull/83586#issuecomment-1224200299 also tries to merge and update xla pin, whichever pr merge later would need to rebase both pytorch pr and pytorch/xla pr.

**Comment by JackCaoG** [comment]
I think we need to rebase again to pr to avoid merge conflict.

**Comment by malfet** [comment]
> xla commit pin changes are temporary, aren't they? (I.e. it should be a hash sum of the commit not the tag name, isn't it?)

@Lezcano just curious, why did you ignore this comment? Shouldn't XLA pin always be a hash sum?

**Comment by JackCaoG** [comment]
@malfet  It is about https://github.com/pytorch/pytorch/issues/82033, pytorch pr can pin to a pt/xla fix pr's branch name or newest hash of that pr(both should work). This way we don't need to leave xla head broken for a couple hours.

**Comment by JackCaoG** [comment]
@malfet What's the reason that this pr being reverted? My guess is you want to revert https://github.com/pytorch/pytorch/pull/83628 but this pr caused some revert conflict?

**Comment by malfet** [comment]
> @malfet What's the reason that this pr being reverted? My guess is you want to revert #83628 but this pr caused some revert conflict?

Correct, 83628 modified xla-pin, then auto-update happened, then this PR modified the pin, so I can not revert old PR without reverting other two the modified the same file. Let's reopen, re-base and re-land this one

**Comment by JackCaoG** [comment]
@Lezcano I can not reopen the original pt/xla pr for some reason, so I revert the revert in https://github.com/pytorch/xla/pull/3933, you can rebase and update the pin to `9b2f7929c2dae841888a836449c25b04c8cf4045` or `revert-3931-revert-3918-inv_ex` then merge this pr.

**Comment by JackCaoG** [comment]
This is something we might need to think about, every pr that modify the xla hash is very hard to auto-rebase and auto-revert...

**Comment by malfet** [comment]
@Lezcano can you please rebase again (if it was not a ghstacked PR, I could have used GH UI to rebase)

**Comment by Lezcano** [comment]
git merge -f "Reland"

**Pull request closed without merging**
