### PR TITLE
[BE] Handle errors in `set_num_threads`

### PR DESCRIPTION
**Pull request by malfet**
and `set_num_interop_threads`

Before that, call `torch.set_num_threads(2**65)` resulted in segmentation fault, afterwards it becomes a good old runtime error:
```
% python -c "import torch;torch.set_num_threads(2**65)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: Overflow when unpacking long
```

Similar to https://github.com/pytorch/pytorch/pull/60073

cc @albanD

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by malfet** [comment]
Let me add a quick regression test before landing...

**Review by albanD — APPROVED** [review]
Sounds good once we have test!

**Pull request closed without merging**
