### PR TITLE
Add Half support for poisson and use float for Half cumulative distribution on CPU

### PR DESCRIPTION
**Pull request by CaoE**
Add Half support for poisson and use float for Half cumulative distribution on CPU

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by cpuhrsch — CHANGES_REQUESTED** [review]
This needs a test for the extended functionality

**Comment by CaoE** [comment]
@cpuhrsch Added Half tests for poisson and there is already Half tests for multinomial https://github.com/pytorch/pytorch/blob/main/test/test_torch.py#L5003.

**Comment by cpuhrsch** [comment]
Hm, @CaoE - if the test already exists (and presumably runs and succeeds?) then I'm surprised that we stiil need to add coverage for it? Can I ask you to check whether it already runs? Maybe this change already happened? I want to avoid potentially having multiple implementations for the same op + device + dtype combo.

**Comment by CaoE** [comment]
@cpuhrsch It already runs. Half support for multinomial is added by https://github.com/pytorch/pytorch/pull/104178. This PR is not to add Half support for multinomial. It uses float for Half (like bfloat16) to cumulate.

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
