### PR TITLE
[BE] put "show_dispatch_trace()" print logic in .cpp file

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #132717

I find myself occasionally trying to modify this to get additional debug info. Recompiling takes forever after modifying these lines, because the .h file is depended on by a huge number of files.

If we move this logic into a helper function and put it in the .cpp file, recompilation will be a lot faster when adding debug here.

Tested with a local DEBUG=1 build (which is needed to use `TORCH_SHOW_DISPATCH_TRACE=1`) and verified basic sanity - i.e. it still prints `[call]`, etc.

Differential Revision: [D60804331](https://our.internmc.facebook.com/intern/diff/D60804331)

### CODE REVIEW

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60804331).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60804331).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60804331).

**Review by soulitzer — APPROVED** [review]

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D60804331).

**Comment by bdhirsh** [comment]
> I find myself occasionally trying to modify this to get additional debug info

out of curiosity, what do you usually add? (is it worth committing it?)

**Review by bdhirsh — APPROVED** [review]

**Comment by davidberard98** [comment]
@bdhirsh For a kernel that was being dispatched with a `PythonDispatcher` key, I wanted to see what other keys were in the DispatchKeySet. It's kind of verbose if you have a lot of keys, so I'm not sure it would be worth adding as a default

**Pull request closed without merging**
