### PR TITLE
[inductor] don't fuse two nodes if likely increase peak memory

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #136702
* #138429
* __->__ #138756
* #139136

Partially fixing https://github.com/pytorch/pytorch/issues/138685 

Add a (relatively safe?) heuristics to skip fusion if we can potentially increasing peak memory.

The doc string mainly explains what this PR is doing:
```
        The implementation is more like a heuristic since we don't really know if we are at peak
        or not when trying to fuse these two ndoes. The order of nodes may change later which makes the
        peak memory estimation hard.
        Here is how we decide the LOWER BOUND of extra memory allocation if we fuse these 2 nodes:
        1. find all buffers read by each node with a single user. These buffers are supposed to
           be reused if we don't fuses these 2 nodes
        2. find the intersection of these buffers for the two node and sum the total buffer size.
           If we don't fuse these two nodes, we can at lease avoid this much memory allocation.
           Note that the extra memory allocation is not necessarily causing peak memory increase.
           This is just a heuristic.
        We return true only if the saving for fusion can not trade off the extra memory allocation.
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by shunting314** [comment]
The perf of revision 6a7fa5043e62ab2b645ca7bcbf74a064228bed8a [here](https://hud.pytorch.org/benchmark/compilers?dashboard=torchinductor&startTime=Thu%2C%2017%20Oct%202024%2018%3A22%3A25%20GMT&stopTime=Thu%2C%2024%20Oct%202024%2018%3A22%3A25%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&deviceName=cuda%20(a100)&lBranch=gh/shunting314/180/head&lCommit=6a7fa5043e62ab2b645ca7bcbf74a064228bed8a&rBranch=main&rCommit=84e5f34fd13a3db276087b11a84232702e67bef1) is neutral. But I probably need change how we decide skipping fusion here. Filtering inputs with a single user seems too restrictive.

**Review by jansel — CHANGES_REQUESTED** [review]
Failing tests

Does this impact compile time at all?

**Review by eellison — COMMENTED** [review]
We have seen other cases of inductor increasing memory use, recently, see [internal link](https://fb.prod.workplace.com/groups/1075192433118967/posts/1530547787583427). I would rather we do the full solution, i.e., with tensor liveness ranges, peak memory calculation, etc.

**Comment by shunting314** [comment]
> Does this impact compile time at all?

Compilation time looks fine: 
Screenshot 2024-10-25 at 10 44 18 AM

I'll fix the tests.

**Comment by shunting314** [comment]
> I would rather we do the full solution, i.e., with tensor liveness ranges, peak memory calculation, etc.

I imagine the fully solution can be INCREMENTALLY built upon this one.
1. right now the check in this PR is very strict (but safe). We consider two inputs can be reused when they both have a single user. But this can be extended to check if the transitive user set of these inputs have overlapping. If not, there live-range can be non-overlapping and we can reuse the memory
2. The estimation of the current peak memory can be an parameter when we decide fusing or not.

**Review by jansel — CHANGES_REQUESTED** [review]
Is that compile time regression CI real?

**Comment by laithsakka** [comment]
> Is that compile time regression CI real?
if you are taking about the pr_time benchamrks 
its 1.5% not a huge jump but its real add_loop benchmarks are very stable.
```
2024-10-29T00:57:30.6097670Z REGRESSION: benchmark ('add_loop_inductor', 'compile_time_instruction_count') failed, actual result 24428182108 is 1.51% higher than expected 24064639114 ±+1.50% if this is an expected regression, please update the expected results.
2024-10-29T00:57:30.6099173Z 
2024-10-29T00:57:30.6099662Z please update all results that changed significantly, and not only the failed ones
2024-10-29T00:57:30.6101303Z PASS: benchmark ('add_loop_inductor_dynamic_gpu', 'compile_time_instruction_count') pass, actual result 40517874538 -1.16% is within expected 40992578178 ±2.50%
2024-10-29T00:57:30.6102305Z 
2024-10-29T00:57:30.6103789Z REGRESSION: benchmark ('add_loop_inductor_gpu', 'compile_time_instruction_count') failed, actual result 23173449187 is 1.54% higher than expected 22822864522 ±+1.50% if this is an expected regression, please update the expected results.
2024-10-29T00:57:30.6105262Z 
```

**Review by jansel — APPROVED** [review]

**Comment by laithsakka** [comment]
@shunting314 you want to update the expected result file before landing , you can get the new content of the new file from the test logs.

**Comment by shunting314** [comment]
@laithsakka thanks, I was working on a PR higher on the stack. Will revisit this one.

**Comment by laithsakka** [comment]
@shunting314 curios if the error went by itself after rebase or if you had to change something in the code. 
trying to evaluate the effectiveness of this test vs how bothering it is and weather i shall keep it.

**Comment by shunting314** [comment]
@laithsakka the error gone by itself after rebasing.

**Comment by laithsakka** [comment]
sounds good seems like the diff regressed two benchmarks by 1% which is less than threshold 
I will put a pr though to increment expected value for those to avoid flakiness, I will add for
 review. 
 
Screenshot 2024-11-04 at 6 00 44 PM

Screenshot 2024-11-04 at 6 00 11 PM

**Comment by laithsakka** [comment]
PASS: benchmark ('add_loop_inductor', 'compile_time_instruction_count') pass, actual result 24603225123 +1.41% is within expected 24260000000 ±1.50%

PASS: benchmark ('add_loop_inductor_dynamic_gpu', 'compile_time_instruction_count') pass, actual result 40744976754 +0.90% is within expected 40380000000 ±2.50%

PASS: benchmark ('add_loop_inductor_gpu', 'compile_time_instruction_count') pass, actual result 23331151962 +1.40% is within expected 23010000000 ±1.50%

**Comment by laithsakka** [comment]
https://github.com/pytorch/pytorch/pull/139703

**Pull request closed without merging**
