### PR TITLE
Make MHA Query Scaling Behaviors Consistent

### PR DESCRIPTION
**Pull request by leimao**
The multi-head attention (MHA) query scaling behaviors are not consistent when [`need_weights`](https://github.com/pytorch/pytorch/blob/8ac9b20d4b090c213799e81acf48a55ea8d437d6/torch/nn/modules/activation.py#L1073) values are different.

On the current main, when `need_weights = True`, the query scaling was performed using a [division](https://github.com/pytorch/pytorch/blob/8ac9b20d4b090c213799e81acf48a55ea8d437d6/torch/nn/functional.py#L5434) and it will be exported as a `Div` operator in ONNX. When `need_weights = False`, the query scaling was performed using a [multiplication](https://github.com/pytorch/pytorch/blob/422b4271aeb0d5998fd439711abf881ac8788478/aten/src/ATen/native/transformers/attention.cpp#L711) and it will be exported as a `Mul` operator in ONNX defined in the [PyTorch ONNX Symbolics](https://github.com/pytorch/pytorch/blob/422b4271aeb0d5998fd439711abf881ac8788478/torch/onnx/symbolic_opset14.py#L177).

We should make the query scaling behaviors consistent. On most of the platforms, multiplication performs no worse than division. Therefore, we should use multiplication consistently for both `need_weights = True` and `need_weights = False`.

### CODE REVIEW

**Comment by leimao** [comment]
@albanD @jbschlosser @mikaylagawarecki Could you please take a lot at this one-line mathematically equivalent change? Thanks.

**Review by mikaylagawarecki — APPROVED** [review]
Thanks!

**Review by albanD — APPROVED** [review]
Pretty sad that there isn't a `rsqrt` on the math lib. But sounds good.

**Comment by albanD** [comment]
@ezyang are we doing something bad here to make SymFloat so mad at us?

**Comment by leimao** [comment]
> @ezyang are we doing something bad here to make SymFloat so mad at us?

Thanks @albanD. I also saw this error from the tests.

```
    q_scaled = q * math.sqrt(1.0 / E)
TypeError: must be real number, not SymFloat
```

How could I fix this? I actually have no clue why the implementation on the main works where this one does not.

**Comment by leimao** [comment]
@albanD This implementation should fix the problem.
```
q_scaled = q * math.sqrt(1.0 / float(E))
```

**Comment by albanD** [comment]
@pytorchbot merge

Ho interesting, let's see how that goes! Thanks for checking

**Pull request closed without merging**
