### PR TITLE
Fix shape function for transpose convolution

### LINKED ISSUE #98129: Shape function for transpose convolution is incorrect
### 🐛 Describe the bug

The shape function for transposed convolution defined here  https://github.com/pytorch/pytorch/blob/master/torch/jit/_shape_functions.py#L805

```
if transposed:
            kernel = dilation_ * (weight[d] - 1)
            output_size.append((input[d] - 1) * stride[d - 2] - 2 * padding[d - 2] + kernel + 1)
```

does not include `output_padding`, whereas the shape function for this op, as defined by the documentation here https://pytorch.org/docs/stable/generated/torch.nn.ConvTranspose2d.html#torch.nn.ConvTranspose2d, includes `output_padding`. That looks like a bug. 

### Versions

This was observed while using the latest TorchMLIR, which in turn refers to these shape functions.

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

### PR DESCRIPTION
**Pull request by CaoE**
Fixes #98129.
Fixes the shape function for jit conv_transpose, as defined by the documentation https://pytorch.org/docs/stable/generated/torch.nn.ConvTranspose2d.html#torch.nn.ConvTranspose2d, includes output_padding.

### CODE REVIEW

**Review by davidberard98 — COMMENTED** [review]
@CaoE Thanks for these fixes - however I'm not confident I check these changes are correct just by looking at them :)

Do you think you could add tests for these changes to show that they do work? You could add manual tests to test_symbolic_shape_analysis.py - or you could figure out how to un-skip the test_variant_consistency_jit tests here: https://github.com/pytorch/pytorch/blob/72ed22e8060e46a4daa368a105c5d9bef686a042/torch/testing/_internal/common_methods_invocations.py#L12199

Another option is to cherry-pick https://github.com/pytorch/pytorch/pull/99129 onto this see if you can un-skip the convolution ops (if you can get that to work and post excerpts from the log, that would be great!) We were thinking about landing this but we decided it wasn't worth the testing cost...

**Comment by mingfeima** [comment]
> @CaoE Thanks for these fixes - however I'm not confident I check these changes are correct just by looking at them :)
> 
> Do you think you could add tests for these changes to show that they do work? You could add manual tests to test_symbolic_shape_analysis.py - or you could figure out how to un-skip the test_variant_consistency_jit tests here:
> 
> https://github.com/pytorch/pytorch/blob/72ed22e8060e46a4daa368a105c5d9bef686a042/torch/testing/_internal/common_methods_invocations.py#L12199
> 
> Another option is to cherry-pick #99129 onto this see if you can un-skip the convolution ops (if you can get that to work and post excerpts from the log, that would be great!) We were thinking about landing this but we decided it wasn't worth the testing cost...

@CaoE can we have the skipped test case fixed ?

**Review by mingfeima — APPROVED** [review]

**Comment by CaoE** [comment]
@davidberard98 Added a test to test_symbolic_shape_analysis.py.

**Comment by CaoE** [comment]
> @CaoE can we have the skipped test case fixed ?

It is hard to un-skip the test_variant_consistency_jit tests, since they are not only related to shape computing errors.

**Review by davidberard98 — APPROVED** [review]
awesome, thanks for the test!

**Pull request closed without merging**
