### PR TITLE
[BE] Dockerize PyTorch docs jobs

### PR DESCRIPTION
**Pull request by huydhn**
Saw some connection error to pip in docs jobs today, so let's dockerize it:

* https://github.com/pytorch/pytorch/actions/runs/4877612277/jobs/8702572072
* https://github.com/pytorch/pytorch/actions/runs/4877612277/jobs/8702572072

Some additional fixes:
* Moving the docs script from under `.circleci` to under `.ci` as they should be
* Linter (as scripts under .ci are subjected to shellcheck)
* Fix some minor Sphinx warnings in functorch docs

### Testing
Docs previews look fine:

* https://docs-preview.pytorch.org/100601/index.html
* https://docs-preview.pytorch.org/100601/cppdocs/index.html
* https://docs-preview.pytorch.org/100601/functorchdocs/index.html

### CODE REVIEW

**Review by clee2000 — APPROVED** [review]

**Comment by kit1980** [comment]
I think this was also a cause of failures on PR: https://github.com/pytorch/pytorch/actions/runs/4888273854/jobs/8725937451?pr=95816

**Comment by huydhn** [comment]
> I think this was also a cause of failures on PR: https://github.com/pytorch/pytorch/actions/runs/4888273854/jobs/8725937451?pr=95816

I guess for this type of change, a rebase would eventually needed, I could keep those script as a symlinks for backward compatible in the meantime, then cleaning them update later

**Pull request closed without merging**
