### PR TITLE
extract //c10/macros into its own package

### PR DESCRIPTION
**Pull request by dagitses**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70183
* #69995
* __->__ #69994
* #69993

Differential Revision: [D33141011](https://our.internmc.facebook.com/intern/diff/D33141011/)

Differential Revision: [D33141011](https://our.internmc.facebook.com/intern/diff/D33141011)

### CODE REVIEW

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33141011).

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33141011).

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33141011).

**Review by malfet — APPROVED** [review]
LGTM, but please consider adding a bit more descriptive comment

**Comment by dagitses** [comment]
> LGTM, but please consider adding a bit more descriptive comment

good call, done.

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33141011).

**Pull request closed without merging**
