### PR TITLE
Update torch-xpu-ops pin (ATen XPU implementation)

### PR DESCRIPTION
**Pull request by fengyuan14**
Regular bi-weekly pin update. New 85 ATen operators are implemented in XPU backend.
https://github.com/intel/torch-xpu-ops/blob/release/2.4/yaml/xpu_functions.yaml

cc @frank-wei @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @gujinghui @EikanWang @guangyey

### CODE REVIEW

**Review by EikanWang — APPROVED** [review]

**Comment by EikanWang** [comment]
Please add some descriptions of why we need to update the pin.

**Comment by fengyuan14** [comment]
> Please add some descriptions of why we need to update the pin.

Regular bi-weekly pin update. New 85 ATen operators are implemented in XPU backend.

**Comment by fengyuan14** [comment]
Irrelevant failure,
image

**Pull request closed without merging**
