### PR TITLE
correct BLAS input

### LINKED ISSUE #32407: Build without MKL is not possible when MKL is installed
Hello,

I was planning to make some benchmark with different BLAS implementation on CPU so I built several Pytorch package with BLAS=Eigen/OpenBLAS/ATLAS/MKL.
Sadly something unexpected occurred: All version are linked to libmkl!

Here is an example with the Eigen flavor:

```
python3 -c 'import torch; print(torch.__config__.show())'

PyTorch built with:
  - GCC 8.3
  - Intel(R) Math Kernel Library Version 2019.0.2 Product Build 20190118 for Intel(R) 64 architecture applications
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - Build settings: BLAS=Eigen, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS=-g -O2 -fdebug-prefix-map=/home/acecile/packaging/pytorch/pytorch-1.3.1+debian=. -fstack-protector-strong -Wformat -Werror=format-security -DOMPI_SKIP_MPICXX=1 -I/usr/include/mkl -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=False, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=OFF, USE_NNPACK=1, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

```
ldd /usr/lib/python3/dist-packages/torch/lib/libtorch.so | grep -i mkl

	libmkl_intel_lp64.so => /usr/lib/x86_64-linux-gnu/libmkl_intel_lp64.so (0x00007f43c8dea000)
	libmkl_gnu_thread.so => /usr/lib/x86_64-linux-gnu/libmkl_gnu_thread.so (0x00007f43c7596000)
	libmkl_core.so => /usr/lib/x86_64-linux-gnu/libmkl_core.so (0x00007f43c340a000)
```

I look at all environment variable and found none to explicitely disable the use of MKL. Any help would be appreciated !

Regards, Adam.

### PR DESCRIPTION
**Pull request by rmast**
Fixes #32407

With this little correction to Dependencies.cmake it is possible to build an MKL-free version of Pytorch up from version v2.0.0 by explicitly choosing another MKL-free BLAS.

This pullrequest fulfills the "if not already present" part of the original comment in  Dependencies.cmake:
"setting default preferred BLAS options if not already present." 

It's tested with this Action-.yml:
```
name: Build PyTorch v2.0.0 without AVX

on:
  push:
    branches:
      - v2.0.0
  pull_request:
    branches:
      - v2.0.0

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -el {0}
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        #repository: 'pytorch/pytorch'
        #ref: 'v2.3.0'
        submodules: 'recursive'

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        activate-environment: true
        python-version: 3.10.13

    - name: Install Dependencies - Common - Linux 2
      run: |
        conda info
        conda list
        conda install nomkl
        conda install astunparse numpy ninja pyyaml setuptools cmake cffi typing_extensions future six requests dataclasses
        export PYTORCH_CPU_CAPABILITY=cpu
        export ATEN_CPU_CAPABILITY_DEFAULT=cpu
        export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
        export ATEN_CPU_CAPABILITY=default
        export USE_NNPACK=0
        export MAX_JOBS=4
        export USE_CUDA=0
        export USE_ROCM=0
        export BLAS=OpenBLAS
        export CMAKE_ARGS="-D CMAKE_BUILD_TYPE=Release -D USE_AVX=OFF -D USE_NNPACK=OFF -D C_HAS_AVX_2=OFF -D C_HAS_AVX2_2=OFF -D CXX_HAS_AVX_2=OFF -D CXX_HAS_AVX2_2=OFF -D CAFFE2_COMPILER_SUPPORTS_AVX512_EXTENSIONS=OFF -DPYTHON_INCLUDE_DIR=$(python -c "import sysconfig; print(sysconfig.get_path('include'))") -DPYTHON_LIBRARY=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))") -DPYTHON_EXECUTABLE:FILEPATH=`which python`"
        pip install build wheel typing_extensions
        python setup.py bdist_wheel
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: |
          dist
          !dist/**/*.md
```

### CODE REVIEW

**Comment by rmast** [comment]
I watched the test-run. The only failing test was 
RuntimeError: CUDA error: out of memory
I can't see any reason why that could be related to my change. Is there a way to resubmit that single test?

**Review by jgong5 — DISMISSED** [review]
Do we have UTs to cover the case where BLAS is set to libraries other than MKL?

**Comment by rmast** [comment]
As BLAS=MKL was fixed forcefully outside mobile apparently no builds test it otherwise.

When such a test build delivers a build with another BLAS-choice, shouldn't there just be Actions that just build with for example OpenBLAS?

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rmast** [comment]
> Didn't find following labels among repository labels: topic: bug

@pytorchbot label "bug"

**Review by kit1980 — DISMISSED** [review]

**Comment by malfet** [comment]
Reopening the pull-request, as it broke nighly builds, see https://github.com/pytorch/pytorch/actions/runs/9336605978/job/25698069272 adding ciflow/binaries_wheel to the PR

**Comment by rmast** [comment]
I made the false assumption that MKLDNN would need MKL to operate properly, but the AARCH64 build proves it doesn't.
I'll remove that assumption from my code.

**Comment by rmast** [comment]
CMake Error at third_party/ideep/mkl-dnn/cmake/ACL.cmake:61 (message):
  Detected ACL version 24.04, but maximum supported is 23.08
  
 That's not caused by me is it?

**Comment by rmast** [comment]
I also don't recognize this:
[ 88%] Linking CXX executable ../../../../bin/torch_shm_manager
../../../../lib/libc10.so: error: undefined reference to 'pthread_setname_np'
../../../../lib/libc10.so: error: undefined reference to 'pthread_join'
../../../../lib/libc10.so: error: undefined reference to 'pthread_create'
collect2: error: ld returned 1 exit status
gmake[2]: *** [caffe2/torch/lib/libshm/CMakeFiles/torch_shm_manager.dir/build.make:99: bin/torch_shm_manager] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:7941: caffe2/torch/lib/libshm/CMakeFiles/torch_shm_manager.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....

**Comment by rmast** [comment]
@malfet can you take a look at the errors in the faulty runs? I doubt I caused them.

**Pull request closed without merging**
