### PR TITLE
Graph break within check_kwargs for higher order ops #108597

### PR DESCRIPTION
**Pull request by nakulcr7**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108730

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by nakulcr7** [comment]
Fix for https://github.com/pytorch/pytorch/issues/104884

**Comment by nakulcr7** [comment]
Fix for #104884

**Comment by nakulcr7** [comment]
@anijain2305 A few points regarding the unit test that I've added
1. I couldn't test against grad because it isn't meant to support kwargs in the first place: https://github.com/pytorch/pytorch/blob/232759c5d7fdfe212ec6d4813d74ea697ee28e5a/torch/_dynamo/variables/higher_order_ops.py#L655
2. Same as above for vmap https://github.com/pytorch/pytorch/blob/232759c5d7fdfe212ec6d4813d74ea697ee28e5a/torch/_dynamo/variables/higher_order_ops.py#L829
3. kwargs aren't even passed into cond. So I actually think the line https://github.com/pytorch/pytorch/blob/232759c5d7fdfe212ec6d4813d74ea697ee28e5a/torch/_dynamo/variables/higher_order_ops.py#L319 might be redudant.
4. Even for the unit test that I've added for map, the way I call it is wrong since control_flow.map should not take additional args/kwargs. The check_kwargs call in its implementation might be redundant too https://github.com/pytorch/pytorch/blob/232759c5d7fdfe212ec6d4813d74ea697ee28e5a/torch/_dynamo/variables/higher_order_ops.py#L514

**Comment by anijain2305** [comment]
@ydwu4 @kshitij12345 Does @nakulcr7 analysis make sense? Do we really need kwargs check? If not, we can probably remove it.

**Comment by ydwu4** [comment]
Yeah, we probably can remove check_kwargs call for cond and map: 1. for these two, kwargs will most likely be empty  2. If in the future we want to extend some kwargs , we don't want to fallback to eager for control flow operators so we'll probably use the UncapturedHigherOrderOpError instead of unimplemented.

**Comment by nakulcr7** [comment]
@ydwu4  Please see https://github.com/pytorch/pytorch/pull/108821

**Pull request closed without merging**
