### PR TITLE
[jit] move casting ops from prim to aten

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #21046 [jit] bake constants into the traced graph, get rid of getNestedValueTrace
* #21003 [jit] remove constant pooling expect
* **#21002 [jit] move casting ops from prim to aten**

Summary:
Currently we are messed up with `prim` and `aten` namespace when we register prim and builtin ops, lots of the ops that have schema should go into the `aten` namespace rather than `prim`, `prim` namespace should only be reserved for the ops that does not have a schema.

Differential Revision: [D15523444](https://our.internmc.facebook.com/intern/diff/D15523444)

### CODE REVIEW

**Review by driazati — COMMENTED** [review]
What's the backwards compatibility strategy for stuff like this? Models saved in 1.1 wouldn't work here, should we keep the old ones around in `legacy_ops.cpp` or something?

**Comment by wanchaol** [comment]
> What's the backwards compatibility strategy for stuff like this? Models saved in 1.1 wouldn't work here, should we keep the old ones around in `legacy_ops.cpp` or something?

@driazati fortunately, all of our casting ops are serializing as python syntax like `float(), int()`, etc. So this PR should be fine on backward compatability. For other ops like `abs`, there're indeed bc issues and I think we should probably make a more concrete design on deprecating them.

**Comment by suo** [comment]
Can you explain why we are making this change?

**Comment by wanchaol** [comment]
> Can you explain why we are making this change?

@suo sorry for not adding the summary, I will update. The reason of making the change is, currently we are messed up with `prim` and `aten` namespace when we register prim and builtin ops, lots of the ops that have schema should go into the `aten` namespace rather than `prim`, `prim` namespace should only be reserved for the ops that does not have a schema.

**Review by zdevito — APPROVED** [review]
Yep, our goal should be that prim:: is only used for non-schematizable ops

**Comment by ezyang** [comment]
This looks like it crossed over a merge resulting in master failure:

```
May 29 20:18:59 /var/lib/jenkins/workspace/torch/csrc/jit/script/python_sugared_value.cpp: In member function 'virtual std::shared_ptr<torch::jit::script::SugaredValue> torch::jit::script::ModuleValue::attr(const torch::jit::SourceRange&, torch::jit::script::Function&, const string&)':
May 29 20:18:59 /var/lib/jenkins/workspace/torch/csrc/jit/script/python_sugared_value.cpp:262:41: error: 'Bool' is not a member of 'torch::jit::prim'
May 29 20:18:59      Value* the_bool = m.graph()->insert(prim::Bool, {the_tensor});
May 29 20:18:59                                          ^
May 29 20:18:59 /var/lib/jenkins/workspace/torch/csrc/jit/script/python_sugared_value.cpp:262:41: note: suggested alternatives:
May 29 20:18:59 In file included from /var/lib/jenkins/workspace/aten/src/ATen/core/ivalue_inl.h:7:0,
May 29 20:18:59                  from /var/lib/jenkins/workspace/aten/src/ATen/core/ivalue.h:409,
May 29 20:18:59                  from /var/lib/jenkins/workspace/torch/csrc/jit/pybind_utils.h:3,
May 29 20:18:59                  from /var/lib/jenkins/workspace/torch/csrc/jit/script/python_sugared_value.h:4,
May 29 20:18:59                  from /var/lib/jenkins/workspace/torch/csrc/jit/script/python_sugared_value.cpp:1:
May 29 20:18:59 /var/lib/jenkins/workspace/aten/src/ATen/core/interned_strings.h:81:11: note:   'c10::aten::Bool'
May 29 20:18:59    _(aten, Bool)                    \
May 29 20:18:59            ^
May 29 20:18:59 /var/lib/jenkins/workspace/aten/src/ATen/core/interned_strings.h:331:35: note: in definition of macro 'DEFINE_SYMBOL'
May 29 20:18:59    namespace ns { constexpr Symbol s(static_cast<unique_t>(_keys::ns##_##s)); }
May 29 20:18:59                                    ^
May 29 20:18:59 /var/lib/jenkins/workspace/aten/src/ATen/core/interned_strings.h:332:1: note: in expansion of macro 'FORALL_NS_SYMBOLS'
May 29 20:18:59  FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
May 29 20:18:59  ^
May 29 20:18:59 /var/lib/jenkins/workspace/aten/src/ATen/core/interned_strings.h:81:11: note:   'c10::aten::Bool'
May 29 20:18:59    _(aten, Bool)                    \
May 29 20:18:59            ^
May 29 20:18:59 /var/lib/jenkins/workspace/aten/src/ATen/core/interned_strings.h:331:35: note: in definition of macro 'DEFINE_SYMBOL'
May 29 20:18:59    namespace ns { constexpr Symbol s(static_cast<unique_t>(_keys::ns##_##s)); }
May 29 20:18:59                                    ^
May 29 20:18:59 /var/lib/jenkins/workspace/aten/src/ATen/core/interned_strings.h:332:1: note: in expansion of macro 'FORALL_NS_SYMBOLS'
May 29 20:18:59  FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
```

**Comment by wanchaol** [comment]
@ezyang reverting in progress.

**Pull request closed without merging**
