### PR TITLE
[Quant][fx] Refactor lowering code (part 1)

### PR DESCRIPTION
**Pull request by andrewor14**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #74128

**Summary:** This commit is the first step towards refactoring the 
lowering code in _lower_to_native_backend.py. The main changes
included in this commit are:

(1) Remove the use of the subgraph rewriter in lowering
(2) Replace the use of `is_match` with manual pattern matching

The motivation behind (2) is it simplifies the lowering code
significantly; previously we had many different but similar
patterns for slightly different models. There should be no
change in behavior with this PR.

Note that this is only part 1 of the refactoring. Part 2
will merge the static and dynamic lowering code paths
and refactor the currently duplicate pattern matching /
cleanup code into common helper functions.

**Test Plan:**
python test/test_quantization.py TestQuantizeFx
python test/test_quantization.py TestQuantizeFxOps

**Reviewers:** jerryzh168

**Subscribers:** jerryzh168

Differential Revision: [D34910597](https://our.internmc.facebook.com/intern/diff/D34910597)

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]
thanks, looks good! ideally we should separate them to multiple PRs I think, but maybe you can try to do that next time

**Comment by jerryzh168** [comment]
maybe also add some more details for the refactors in the summary?

**Comment by andrewor14** [comment]
Ok, how about I just do the removing subgraph rewriter and `is_match` in this PR and leave the merging duplicate code to the next PR?

**Comment by andrewor14** [comment]
@andrewor14 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34910597).

**Comment by andrewor14** [comment]
Ok, I updated the PR description with more details about the refactor. Provided that the tests pass this PR is ready from my side

**Pull request closed without merging**
