### PR TITLE
Fix pytorch-triton nightly checksum shorthash

### PR DESCRIPTION
**Pull request by huydhn**
Binary build is failing in trunk after https://github.com/pytorch/pytorch/pull/139206 lands, for example, https://github.com/pytorch/pytorch/actions/runs/11981181986/job/33410250461#step:17:539.  It's a bit tricky to spot the issue but the difference is between `3.2.0+35c6c7c628` set by PyTorch and `3.2.0+git35c6c7c6` from triton (look closely one has the length of 10, the other of 8 characters)

Triton now has its own nightly build logic in https://github.com/triton-lang/triton/pull/4812 that takes only 8 characters by default while the original logic from PT took 10. So, PT nightly couldn't find the dependency.

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by bertmaher** [comment]
@huydhn Thank you for fixing this! 🙏

**Pull request closed without merging**
