### PR TITLE
Revert "Update nccl submodule to 2.18.5 (#107883)"

### PR DESCRIPTION
**Pull request by ptrblck**
This reverts commit a41d15e45887c9da23f853e15d72badb454a3199.

Follow-up on: https://github.com/pytorch/builder/pull/1526

Cross-posting:
`pytorch/pytorch` updated NCCL in https://github.com/pytorch/pytorch/pull/107883 which also landed in the `2.1.0` release candidates. E.g.: https://github.com/pytorch/pytorch/tree/v2.1.0-rc3/third_party

Since the `2.18.5` binaries are not released yet we would diverge in `torch==2.1.0` between the binaries and a source build.
Should we revert https://github.com/pytorch/pytorch/pull/107883 in v2.1.0-rc3?

CC @atalman @malfet

### CODE REVIEW

**Comment by ptrblck** [comment]
Related to: https://github.com/pytorch/builder/pull/1527

**Comment by Skylion007** [comment]
@ptrblck Is there any reason to revert this besides Nvidia not putting out a changelog + binaries? They already cut a tag, and it only contains community bugfixes over the previous version. Can we ping someone at NVidia to ask when they are going to release the binaries? The NCCL updates are fixing a lot of bugs we encountered with Infiniband / Sharp when used with H100s.

**Comment by ptrblck** [comment]
@Skylion007 
>  Is there any reason to revert this besides Nvidia not putting out a changelog + binaries?

Yes, I've created the PR as we are currently diverging between the source for `release/2.1`, which uses NCCL 2.18.5 and the binaries we will build, which can currently only use NCCL<=2.18.3.
My proposal was to use the same libs in source builds as well as the binaries.

> Can we ping someone at NVidia to ask when they are going to release the binaries? 

Yes, I've already asked and it seem the release is currently slipping.
However, we also won't update the binaries to 2.18.5 without testing the builds, so it's irrelevant for the 2.1.0 binaries (NCCL 2.18.5 in `main` is of course good and should stay).

@atalman suggested to kill the PR and to stick to NCCL=2.18.1 for the 2.1.0 release as this version was already used for some time, which might also be fine.
See these PRs as a proposal to align the binaries with source builds. It's not reverting NCCL from `main` (and thus source builds and the nightly binaries). 

If we are OK with different library version used in binaries vs. the source branch, let's close the PRs.

**Comment by ptrblck** [comment]
Discussed it with @atalman in our sync again and we won't align the binaries to source builds in this release, so closing it.

**Pull request closed without merging**
