### PR TITLE
Bundle lazy ts backend

### PR DESCRIPTION
**Pull request by yeounoh**
### Description

`libtorch.so` is missing `lazy/ts_backend`, which is breaking the XLA build/test pipeline.

### Issue

This currently blocks #82342 and #78182 

### Testing

https://github.com/pytorch/pytorch/runs/7551019518?check_suite_focus=true

### CODE REVIEW

**Comment by JackCaoG** [comment]
@Krovatkin Is there any concern of adding ts_backend header to `libtorch `? We can either do this, or remove the `ts_node` include from `dynamic_ir.h`

```
2022-07-28T00:23:40.5628551Z [1m/opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/lazy/core/dynamic_ir.h:19:10: [0m[0;1;31mfatal error: [0m[1m'torch/csrc/lazy/ts_backend/ts_node.h' file not found[0m
2022-07-28T00:23:40.5629189Z #include <torch/csrc/lazy/ts_backend/ts_node.h>
2022-07-28T00:23:40.5629680Z [0;1;32m         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by JackCaoG** [comment]
Let's retrigger the CI, xla test failure is caused by something else.

**Comment by yeounoh** [comment]
> Let's retrigger the CI, xla test failure is caused by something else.

This PR should resolve the missing `lazy/ts_backend` header issue. The new error ("something else") could be related to [this](https://github.com/pytorch/xla/pull/3745):
```
2022-07-28T01:41:22.6978873Z [1A[K[31m[1mERROR: [0m/var/lib/jenkins/workspace/xla/third_party/tensorflow/tensorflow/compiler/xla/service/cpu/BUILD:780:11: Compiling tensorflow/compiler/xla/service/cpu/runtime_custom_call_status.cc failed: (Exit 1): clang failed: error executing command /usr/lib/llvm-8/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 31 arguments skipped)
2022-07-28T01:41:22.6979960Z 
2022-07-28T01:41:22.6980314Z Use --sandbox_debug to see verbose messages from the sandbox
2022-07-28T01:41:22.7007201Z In file included from tensorflow/compiler/xla/service/cpu/runtime_custom_call_status.cc:18:
2022-07-28T01:41:22.7008358Z [1m./tensorflow/compiler/xla/service/custom_call_status_internal.h:26:8: [0m[0;1;31merror: [0m[1mno template named 'optional' in namespace 'std'[0m
2022-07-28T01:41:22.7009009Z   std::optional<std::string> message;
2022-07-28T01:41:22.7009426Z [0;1;32m  ~~~~~^
2022-07-28T01:41:22.7010208Z [0m[1m./tensorflow/compiler/xla/service/custom_call_status_internal.h:34:6: [0m[0;1;31merror: [0m[1mno template named 'optional' in namespace 'std'[0m
2022-07-28T01:41:22.7010923Z std::optional<absl::string_view> CustomCallStatusGetMessage(
2022-07-28T01:41:22.7011863Z [0;1;32m~~~~~^
```

I've re-triggered the run, following the [revert](https://github.com/pytorch/xla/pull/3789). We should test in both downstream & upstream before revert revert the tensorflow pin update. cc @miladm

**Review by albanD — APPROVED** [review]
SGTM

**Pull request closed without merging**
