### PR TITLE
Android oss fixes

### PR DESCRIPTION
**Pull request by soumith**
Two main fixes were needed to build with latest Android NDK:

- AVX needed to be disabled on Android x86 configuration, because it looks like the compiler shipped with Android NDK didn't have all of the intrinsics defined that we use
- Latest NDK prefers `clang`, so switched to that
- `make install` wasn't working because of cmake's insistence on finding `protoc`, but we built host `protoc`. So I faked it for the script

Somewhat addresses the following issues:

- https://github.com/pytorch/pytorch/issues/14354
- https://github.com/pytorch/pytorch/issues/15427
- https://github.com/pytorch/pytorch/issues/14280
- https://github.com/pytorch/pytorch/issues/14258
- https://github.com/pytorch/pytorch/issues/13116
- https://github.com/pytorch/pytorch/issues/9752
- https://github.com/pytorch/pytorch/issues/7589

The only work I did was to test the whole thing, add some cmake fixes and send a PR.
Pretty much all the hard work was done by @t-vi as part of his heroic effort to get AICamera working again on PyTorch master.

Updated the README of https://github.com/soumith/AICamera to make it clear what exactly has to be done to make it work. Sent a PR to https://github.com/t-vi/AICamera/pull/2

cc: @bwasti @dreiss @t-vi @Suhail

### CODE REVIEW

**Comment by t-vi** [comment]
Thanks, Soumith!

**Comment by h6197627** [comment]
@soumith, could you also fix the issue of not copying libcaffe2_protos.a library during running **make install**, please?
Originally reported there #14317

**Comment by t-vi** [comment]
I'm not sure what I'm doing wrong, but
https://github.com/pytorch/pytorch/blob/77de69867ac6ca737f2ec670e0f02b07279d6880/caffe2/perfkernels/adagrad.cc#L188
and the similar lines seem to lead to unresolved symbols if AVX isn't available.

**Comment by t-vi** [comment]
So I tried to stare down the android build failure a bit and my hypothesis is that the Android SDK used is too old (in particular the clang version).
As far as I understand, at least the older clang versions produce less efficient code than gcc for the convolutions, but I wonder whether recent clang might have mitigated that.

**Comment by yxchng** [comment]
I am getting this error using your fix:
`
 fatal error: 'foxi/onnxifi_loader.h'
      file not found
#include "foxi/onnxifi_loader.h"
`

**Comment by yxchng** [comment]
I fix the error by removing foxi. However, another error occurs:

`
Build command failed.
Error while executing process /home/yxchng/Android/Sdk/cmake/3.10.2.4988404/bin/cmake with arguments {--build /home/yxchng/git/new3/pytorch-android/app/.externalNativeBuild/cmake/debug/armeabi-v7a --target native-lib}
[1/4] Building C object CMakeFiles/cpufeatures.dir/home/yxchng/Android/Sdk/ndk-bundle/sources/android/cpufeatures/cpu-features.c.o
[2/4] Linking C static library libcpufeatures.a
[3/4] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o
FAILED: CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o 
/home/yxchng/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi22 --gcc-toolchain=/home/yxchng/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/yxchng/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -Dnative_lib_EXPORTS -I/home/yxchng/Android/Sdk/ndk-bundle/sources/android/cpufeatures -I../../../../src/main/cpp -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mfpu=vfpv3-d16 -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -stdlib=libc++ -frtti -fexceptions -std=c++11 -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -MF CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -c ../../../../src/main/cpp/native-lib.cpp
In file included from ../../../../src/main/cpp/native-lib.cpp:8:
In file included from ../../../../src/main/cpp/caffe2/core/operator.h:18:
In file included from ../../../../src/main/cpp/caffe2/core/operator_gradient.h:7:
../../../../src/main/cpp/caffe2/utils/proto_utils.h:58:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
In file included from ../../../../src/main/cpp/native-lib.cpp:16:
In file included from ../../../../src/main/cpp/ATen/ATen.h:11:
../../../../src/main/cpp/ATen/Functions.h:3441:66: error: too few arguments to function call, expected 4, have 3
    return detail::infer_type(self).as_strided(self, size, stride);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ^
../../../../src/main/cpp/ATen/core/Type.h:208:3: note: 'as_strided' declared here
  virtual Tensor as_strided(const Tensor & self, IntList size, IntList stride, c10::optional<int64_t> storage_offset) const = 0;
  ^
In file included from ../../../../src/main/cpp/native-lib.cpp:16:
In file included from ../../../../src/main/cpp/ATen/ATen.h:11:
../../../../src/main/cpp/ATen/Functions.h:3444:67: error: too few arguments to function call, expected 4, have 3
    return detail::infer_type(self).as_strided_(self, size, stride);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ^
../../../../src/main/cpp/ATen/core/Type.h:209:3: note: 'as_strided_' declared here
  virtual Tensor & as_strided_(Tensor & self, IntList size, IntList stride, c10::optional<int64_t> storage_offset) const = 0;
  ^
In file included from ../../../../src/main/cpp/native-lib.cpp:16:
In file included from ../../../../src/main/cpp/ATen/ATen.h:11:
../../../../src/main/cpp/ATen/Functions.h:5243:37: error: no member named 'potrs' in 'at::TypeExtendedInterface'
    return detail::infer_type(self).potrs(self, input2, upper);
           ~~~~~~~~~~~~~~~~~~~~~~~~ ^
1 warning and 3 errors generated.
ninja: build stopped: subcommand failed.
`

**Comment by soumith** [comment]
fixed by Jiakai's PRs

**Pull request closed without merging**
