### PR TITLE
[dynamo] attempt run only mode when dynamo cache limit is hit

### PR DESCRIPTION
**Pull request by williamwen42**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136655

Implement https://github.com/pytorch/pytorch/issues/135458.

Try run-only mode when dynamo cache limit is hit. If no valid cache entries are found, then skip code recursively.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Comment by bhack** [comment]
To summarize Is this  N (the cache limit limit) + 1 the cache hit test?

**Comment by williamwen42** [comment]
@bhack please clarify what you mean?

**Comment by bhack** [comment]
Is run only just an extra step for cache hit check after the recompilation limit is exhausted? Or is it something else?

**Comment by williamwen42** [comment]
Run only mode is where we do not ever trace bytecode. We try to run previously compiled code and if all guard checks for previously compiled code fail, we run eager. In the case that cache limit is hit and there is no valid previously compiled code, we also disable the eval frame callback so we skip tracing any recursive calls.

**Review by jansel — APPROVED** [review]

**Comment by anijain2305** [comment]
Just to understand. Earlier, if we hit cache size limit, we fully go back to eager.
Now at runtime, we will still try to use those compiled 8 graphs. But if there is a recompilation, we decide to recursively skip.

**Pull request closed without merging**
