### PR TITLE
Make ghstack merge check workflow more readable on hud

### PR DESCRIPTION
**Pull request by PaliC**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #117581

The gha steps' names didn't really make sense on hud, now they make a bit more sense, example
https://hud.pytorch.org/pytorch/pytorch/pull/117410?sha=01a99f1071346d71e39831ba20468e0b7bdf66d5

### CODE REVIEW

**Comment by janeyx99** [comment]
image
Could this name be more conciser? Maybe by removing "and dependencies"?

**Review by janeyx99 — APPROVED** [review]
Thanks! One more nit on the naming of the workflow

**Review by izaitsevfb — APPROVED** [review]

**Review by malfet — APPROVED** [review]
LGTM, but please check annotations

**Pull request closed without merging**
