### PR TITLE
[dynamo] Refactor TensorVariable method handling

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #119111

This should slightly improve compile times and be easier to maintain.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Review by anijain2305 — APPROVED** [review]
How does it help compile time? Is giant if block slower than dispatch based impl?

**Comment by jansel** [comment]
@anijain2305 

```
if ...

elif ...

elif ...
```
is `O(n)`

While
```
getattr(self, f"method_{name}")(...)
```
or
```
dispatch_table[type(value)](...)
```
is `O(1)`.

This pattern actually appears in tons of places in the codebase.  We should update them all.

**Comment by jansel** [comment]
@anijain2305 I created an issue to track more of these refactors if others want to help.

**Pull request closed without merging**
