### PR TITLE
[BE]: Update NCCL submodule to 2.21.5

### PR DESCRIPTION
**Pull request by Skylion007**
Update NCCL to the latest version. This release is mostly bugfixes with a few new minor features.

### CODE REVIEW

**Comment by Skylion007** [comment]
I think this may require a minor change on the https://github.com/pytorch/builder side too.

**Review by eqy — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
To test the builder companion changes, modify .github/templates/common.yml.j2 to point builder branch to your PR

**Comment by Skylion007** [comment]
@nWEIdia Mind adding a builder PR here as well?

**Comment by nWEIdia** [comment]
@Skylion007 Yes, I will give it a try today.

**Comment by Skylion007** [comment]
@nWEIdia This PR is now read for CUDA 12.4

**Comment by nWEIdia** [comment]
@bryantbiggs created companion NCCL update in https://github.com/pytorch/builder/pull/1780 

Per https://github.com/pytorch/pytorch/pull/124014#issuecomment-2058144686, this should be modified to point to 1780 branch to test?

**Comment by Skylion007** [comment]
Looks like the tests are ready assuming we can get the builder PR merged.

**Review by nWEIdia — APPROVED** [review]
The change looks great! 
The failures are in test phase, which is expected to pass when companion builder PR gets merged. 
Please undo common.yml.j2 changes and re-run regenerate.sh to point to pytorch/builder main branch.

**Review by malfet — APPROVED** [review]

**Comment by nWEIdia** [comment]
The binary test failure is complaining about nccl wheel, which is available in pypi, but not available in AWS S3 index. cc @atalman

**Comment by Skylion007** [comment]
Fix merge conflict

**Comment by Skylion007** [comment]
@malfet @nWEIdia @atalman How do I resolve the subgroup issue on this PR? It just appeared on a recent rebase and I'm a bit unsure how to tackle it. NCCL has a major deadlock regression on 2.3 so I really would ilke to get this PR into 2.4

**Comment by nWEIdia** [comment]
> @malfet @nWEIdia @atalman @eqy How do I resolve the subgroup issue on this PR? It just appeared on a recent rebase and I'm a bit unsure how to tackle it. NCCL has a major deadlock regression on 2.3 so I really would ilke to get this PR into 2.4

Last Friday we discussed the possibility of cherry-picking this after branch cut. Since today is branch cut date, merging this may blur the branch cut signals. But @malfet and @atalman of course can decide to pull this in earlier. The deadlock regression sounds a critical bug that is worthy of at least a cherry-picking.

**Comment by atalman** [comment]
@Skylion007 @nWEIdia  do we have test against pytorh/pytorch that test this builder change https://github.com/pytorch/builder/pull/1780 ? So that we are sure when both PRs merged we don't have any CI or nightly failures ?

**Comment by nWEIdia** [comment]
Yeah, we should redo https://github.com/pytorch/pytorch/pull/124014/commits/0aa2e3acea3d5d1f586288ed230ea2f9bb6a4869 
and please remember to run ./regenerate.sh (it does not hurt, just in case).

**Comment by Skylion007** [comment]
All tests passed with the previous commit so waiting on folks to merge

**Review by atalman — APPROVED** [review]

**Pull request closed without merging**
