### PR TITLE
[pytorch] Add storageHasDeleter() to Pickler's WriteableTensor class

### PR DESCRIPTION
**Pull request by jjlilley**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#31958 [pytorch] Add storageHasDeleter() to Pickler's WriteableTensor class**

Add a signal to Pickler's WriteableTensor to distinguish between
scope-limited Tensors (e.g. torch::from_blob(tmpData, numel)) and
more typical memory-managed Tensors.

The goal is to use this signal in some serialization cases.

Differential Revision: [D19317308](https://our.internmc.facebook.com/intern/diff/D19317308/)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit a0a928ad:


* **6/6** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=a0a928ad4b7a70a15545875c842e7fb42e33445d).

### :detective: 4 new failures recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4170826) caffe2_onnx_py3_6_clang7_ubuntu16_04_build (1/4)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=82036303) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=82036303))
<details>
<summary>
<code>Jan 08 19:34:01 jit.cpp:(.text+0x69be): undefined reference to `torch::jit::Pickler::~Pickler()'</code>
</summary>

```
Jan 08 19:34:00 [ 94%] Linking CXX executable ../bin/test_api 
Jan 08 19:34:00 [ 94%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_netdef_converter.cpp.o 
Jan 08 19:34:01 Scanning dependencies of target TCPStoreTest 
Jan 08 19:34:01 [ 94%] Building CXX object caffe2/lib_c10d/test/CMakeFiles/TCPStoreTest.dir/TCPStoreTest.cpp.o 
Jan 08 19:34:01 CMakeFiles/test_api.dir/jit.cpp.o: In function `TorchScriptTest_TestPicklerUnpicklerTensor_Test::TestBody()': 
Jan 08 19:34:01 jit.cpp:(.text+0x5a19): undefined reference to `torch::jit::Pickler::protocol()' 
Jan 08 19:34:01 jit.cpp:(.text+0x5a5f): undefined reference to `torch::jit::Pickler::pushIValue(c10::IValue const&)' 
Jan 08 19:34:01 jit.cpp:(.text+0x5af9): undefined reference to `torch::jit::Pickler::stop()' 
Jan 08 19:34:01 jit.cpp:(.text+0x5f06): undefined reference to `torch::jit::Unpickler::parse_ivalue()' 
Jan 08 19:34:01 jit.cpp:(.text+0x628a): undefined reference to `torch::jit::Pickler::~Pickler()' 
Jan 08 19:34:01 jit.cpp:(.text+0x69be): undefined reference to `torch::jit::Pickler::~Pickler()' 
Jan 08 19:34:01 clang: error: linker command failed with exit code 1 (use -v to see invocation) 
Jan 08 19:34:01 test_api/CMakeFiles/test_api.dir/build.make:803: recipe for target 'bin/test_api' failed 
Jan 08 19:34:01 make[2]: *** [bin/test_api] Error 1 
Jan 08 19:34:01 CMakeFiles/Makefile2:11399: recipe for target 'test_api/CMakeFiles/test_api.dir/all' failed 
Jan 08 19:34:01 make[1]: *** [test_api/CMakeFiles/test_api.dir/all] Error 2 
Jan 08 19:34:01 make[1]: *** Waiting for unfinished jobs.... 
Jan 08 19:34:01 [ 94%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_lite_interpreter.cpp.o 
Jan 08 19:34:02 In file included from /var/lib/jenkins/workspace/torch/lib/c10d/test/TCPStoreTest.cpp:10: 
Jan 08 19:34:02 In file included from /var/lib/jenkins/workspace/torch/lib/c10d/../c10d/TCPStore.hpp:8: 
Jan 08 19:34:02 /var/lib/jenkins/workspace/torch/lib/c10d/../c10d/Utils.hpp:225:21: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare] 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4170834) caffe2_onnx_py2_gcc5_ubuntu16_04_build (2/4)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=82037437) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=82037437))
<details>
<summary>
<code>Jan 08 19:35:01 jit.cpp:(.text+0x6474): undefined reference to `torch::jit::Pickler::~Pickler()'</code>
</summary>

```
Jan 08 19:34:59    bool is_variable() const noexcept { 
Jan 08 19:34:59         ^ 
Jan 08 19:34:59 [ 93%] Building CXX object test_api/CMakeFiles/test_api.dir/torch_include.cpp.o 
Jan 08 19:35:00 [ 93%] Linking CXX executable ../bin/test_api 
Jan 08 19:35:01 CMakeFiles/test_api.dir/jit.cpp.o: In function `TorchScriptTest_TestPicklerUnpicklerTensor_Test::TestBody()': 
Jan 08 19:35:01 jit.cpp:(.text+0x58aa): undefined reference to `torch::jit::Pickler::protocol()' 
Jan 08 19:35:01 jit.cpp:(.text+0x5902): undefined reference to `torch::jit::Pickler::pushIValue(c10::IValue const&)' 
Jan 08 19:35:01 jit.cpp:(.text+0x591f): undefined reference to `torch::jit::Pickler::stop()' 
Jan 08 19:35:01 jit.cpp:(.text+0x6015): undefined reference to `torch::jit::Unpickler::parse_ivalue()' 
Jan 08 19:35:01 jit.cpp:(.text+0x61ff): undefined reference to `torch::jit::Pickler::~Pickler()' 
Jan 08 19:35:01 jit.cpp:(.text+0x6474): undefined reference to `torch::jit::Pickler::~Pickler()' 
Jan 08 19:35:01 collect2: error: ld returned 1 exit status 
Jan 08 19:35:01 test_api/CMakeFiles/test_api.dir/build.make:802: recipe for target 'bin/test_api' failed 
Jan 08 19:35:01 make[2]: *** [bin/test_api] Error 1 
Jan 08 19:35:01 CMakeFiles/Makefile2:11134: recipe for target 'test_api/CMakeFiles/test_api.dir/all' failed 
Jan 08 19:35:01 make[1]: *** [test_api/CMakeFiles/test_api.dir/all] Error 2 
Jan 08 19:35:01 make[1]: *** Waiting for unfinished jobs.... 
Jan 08 19:35:01 [ 93%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_alias_analysis.cpp.o 
Jan 08 19:35:02 [ 93%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_subgraph_rewriter.cpp.o 
Jan 08 19:35:02 [ 93%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_netdef_converter.cpp.o 
Jan 08 19:35:03 [ 93%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_lite_interpreter.cpp.o 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4170819) pytorch_linux_xenial_py3_6_gcc5_4_build (3/4)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=82037454) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=82037454))
<details>
<summary>
<code>Jan 08 19:35:09 jit.cpp:(.text+0x6894): undefined reference to `torch::jit::Pickler::~Pickler()'</code>
</summary>

```
Jan 08 19:35:07    bool is_variable() const noexcept { 
Jan 08 19:35:07         ^ 
Jan 08 19:35:07 [ 93%] Building CXX object test_api/CMakeFiles/test_api.dir/torch_include.cpp.o 
Jan 08 19:35:08 [ 93%] Linking CXX executable ../bin/test_api 
Jan 08 19:35:09 CMakeFiles/test_api.dir/jit.cpp.o: In function `TorchScriptTest_TestPicklerUnpicklerTensor_Test::TestBody()': 
Jan 08 19:35:09 jit.cpp:(.text+0x5cca): undefined reference to `torch::jit::Pickler::protocol()' 
Jan 08 19:35:09 jit.cpp:(.text+0x5d22): undefined reference to `torch::jit::Pickler::pushIValue(c10::IValue const&)' 
Jan 08 19:35:09 jit.cpp:(.text+0x5d3f): undefined reference to `torch::jit::Pickler::stop()' 
Jan 08 19:35:09 jit.cpp:(.text+0x6435): undefined reference to `torch::jit::Unpickler::parse_ivalue()' 
Jan 08 19:35:09 jit.cpp:(.text+0x661f): undefined reference to `torch::jit::Pickler::~Pickler()' 
Jan 08 19:35:09 jit.cpp:(.text+0x6894): undefined reference to `torch::jit::Pickler::~Pickler()' 
Jan 08 19:35:09 collect2: error: ld returned 1 exit status 
Jan 08 19:35:09 test_api/CMakeFiles/test_api.dir/build.make:807: recipe for target 'bin/test_api' failed 
Jan 08 19:35:09 make[2]: *** [bin/test_api] Error 1 
Jan 08 19:35:09 make[1]: *** [test_api/CMakeFiles/test_api.dir/all] Error 2 
Jan 08 19:35:09 make[1]: *** Waiting for unfinished jobs.... 
Jan 08 19:35:09 CMakeFiles/Makefile2:11107: recipe for target 'test_api/CMakeFiles/test_api.dir/all' failed 
Jan 08 19:35:09 [ 93%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_alias_analysis.cpp.o 
Jan 08 19:35:10 [ 93%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_subgraph_rewriter.cpp.o 
Jan 08 19:35:10 [ 93%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_netdef_converter.cpp.o 
Jan 08 19:35:11 [ 94%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_lite_interpreter.cpp.o 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4170836) pytorch_linux_xenial_py2_7_9_build (4/4)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=82038250) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=82038250))
<details>
<summary>
<code>Jan 08 19:35:39 jit.cpp:(.text+0x6f20): undefined reference to `torch::jit::Pickler::~Pickler()'</code>
</summary>

```
Jan 08 19:35:37    bool is_variable() const noexcept { 
Jan 08 19:35:37         ^~~~~~~~~~~ 
Jan 08 19:35:37 [ 95%] Building CXX object test_api/CMakeFiles/test_api.dir/torch_include.cpp.o 
Jan 08 19:35:38 [ 95%] Linking CXX executable ../bin/test_api 
Jan 08 19:35:39 CMakeFiles/test_api.dir/jit.cpp.o: In function `TorchScriptTest_TestPicklerUnpicklerTensor_Test::TestBody()': 
Jan 08 19:35:39 jit.cpp:(.text+0x6212): undefined reference to `torch::jit::Pickler::protocol()' 
Jan 08 19:35:39 jit.cpp:(.text+0x6263): undefined reference to `torch::jit::Pickler::pushIValue(c10::IValue const&)' 
Jan 08 19:35:39 jit.cpp:(.text+0x6284): undefined reference to `torch::jit::Pickler::stop()' 
Jan 08 19:35:39 jit.cpp:(.text+0x682f): undefined reference to `torch::jit::Unpickler::parse_ivalue()' 
Jan 08 19:35:39 jit.cpp:(.text+0x69a7): undefined reference to `torch::jit::Pickler::~Pickler()' 
Jan 08 19:35:39 jit.cpp:(.text+0x6f20): undefined reference to `torch::jit::Pickler::~Pickler()' 
Jan 08 19:35:39 collect2: error: ld returned 1 exit status 
Jan 08 19:35:39 test_api/CMakeFiles/test_api.dir/build.make:807: recipe for target 'bin/test_api' failed 
Jan 08 19:35:39 make[2]: *** [bin/test_api] Error 1 
Jan 08 19:35:39 CMakeFiles/Makefile2:11372: recipe for target 'test_api/CMakeFiles/test_api.dir/all' failed 
Jan 08 19:35:39 make[1]: *** [test_api/CMakeFiles/test_api.dir/all] Error 2 
Jan 08 19:35:39 make[1]: *** Waiting for unfinished jobs.... 
Jan 08 19:35:39 [ 95%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_alias_analysis.cpp.o 
Jan 08 19:35:40 [ 95%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_subgraph_rewriter.cpp.o 
Jan 08 19:35:40 [ 95%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_netdef_converter.cpp.o 
Jan 08 19:35:41 [ 95%] Building CXX object test_jit/CMakeFiles/test_jit.dir/test_lite_interpreter.cpp.o 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by jjlilley** [comment]
Note: this just adds an accessor that I wanted to be able to use from the fb-side serialization code (not needed in non-fb version, since IOBuf support is fb-only)

I did have an accompanying unittest case in the initial upload, though this would require marking Pickler/Unpickler TORCH_API, which wasn't clear whether it made sense...

**Review by zdevito — COMMENTED** [review]
It's a little difficult to review this in isolation of the follow up changes to serialization. Since it is only three lines, can it just be folded into that PR?

**Comment by jjlilley** [comment]
> It's a little difficult to review this in isolation of the follow up changes to serialization. Since it is only three lines, can it just be folded into that PR?

Thanks, I was debating what the most appropriate review approach would be here.

I can easily merge and re-upload with the stacked/dependent change. The reason that I've hesitated is that the stack change is quite distinct  from this 3-line change:
    D19306682 [pytorch] Elide more Thrift Tensor send copies

(it felt a little bit odd combing a 3-line github change with a 176-line fb-only change...)

Should I combine - or what do we normally do in this situation?

**Comment by zdevito** [comment]
Combined I think would be better, since it would be clearer in context (e.g. are the alternate designs? etc.)

**Comment by jjlilley** [comment]
> Combined I think would be better, since it would be clearer in context (e.g. are the alternate designs? etc.)

Thanks for the feedback. I'll do that then.

**Pull request closed without merging**
