### PR TITLE
Revise error reporting when TorchInductor cannot access /tmp folder

### PR DESCRIPTION
**Pull request by Guobing-Chen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #91385

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by ezyang** [comment]
I have some nits but I'm just going to push changes directly

**Review by jgong5 — APPROVED** [review]

**Comment by ezyang** [comment]
I reworded the error message and made it rethrow, rather than immediately SystemExit

**Review by ezyang — APPROVED** [review]

**Review by anijain2305 — APPROVED** [review]

**Pull request closed without merging**
