### PR TITLE
[sym_shapes][perf] Use sympy xreplace instead of subs

### PR DESCRIPTION
**Pull request by IvanKobzarev**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #124208

https://github.com/sympy/sympy/issues/22240

Differential Revision: [D56207553](https://our.internmc.facebook.com/intern/diff/D56207553)

### CODE REVIEW

**Comment by IvanKobzarev** [comment]
@IvanKobzarev has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D56207553).

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
cc @asmeurer

**Comment by ezyang** [comment]
looks like you need to make the xreplace dicts

**Comment by IvanKobzarev** [comment]
@IvanKobzarev has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D56207553).

**Review by lezcano — APPROVED** [review]
Would it be too mad to write a regression test that looks at the source of `symbolic_shapes.py` and perhaps the files under the `utils/_sympy` folder and makes sure we are not using `sub`?

**Comment by lezcano** [comment]
This is a dupe of https://github.com/pytorch/pytorch/pull/124207. Which one are we going with?

**Pull request closed without merging**
