### PR TITLE
[build] Have PyTorch depend on minimal libcaffe2.so instead of libATen.so

### PR DESCRIPTION
**Pull request by orionr**
* ATen will be included as a part of Caffe2 with this pull request
* This will let us share code between Caffe2 and ATen for operator library work

Tested with

```
python setup.py build_deps
python setup.py develop
cd test && python run_test.py
```
as well as

```
tools/cpp_build/build_all.sh
```

cc @ezyang, @pjh5, @Yangqing for review once I figure out the test failure.

### CODE REVIEW

**Comment by ezyang** [comment]
I had an in person chat with @orionr.

The context is that, eventually, we want to have a single `python setup.py install` which gives you all the functionality you want for PyTorch 1.0 (subject to splitting only for dependencies, e.g. _cpu.so, _cuda.so, _amd.so). Our code is not really in the state where this library actually eixsts, but @orionr is trying to move the process along by proposing that `libcaffe2.so` fill this role (but have `BUILD_CAFFE2`/`BUILD_ATEN` flags which modulate what actually goes in the library.) The intent is to make it easier to move code around inside this library, since if all code is being built in the same compilation unit you have less to worry about when you move things around.

However, talking to @orionr, there may be a fatal problem with this patch, which is that we can't reflect this dependency structure in fbcode without turning on a Caffe2->ATen dependency (which we are not equipped to do right now, because ATen is too big and needs to be slimmed down first.)

**Comment by orionr** [comment]
Thanks, @ezyang, for the good recap. Also cc @Yangqing.

I'm investigating the fbcode side a bit myself while waiting for @dzhulgakov's thoughts. Will report back on this.

**Comment by apaszke** [comment]
I actually don't fully understand this plan. IIRC the initial sketch was that we'd basically have a bunch of dynamically loaded modules that would be implementing different functionalities. Most notably, `libcaffe2.so` (with the C2 graph executors, etc.) was meant to be used by the production module, and not the basic package. Has that changed?

**Comment by orionr** [comment]
@apaszke fair and good questions.

We originally talked about having separate installs for eager, hybrid, and graph, but this doesn't really make sense in the real world. Hybrid is really just the decorators you use to get from eager to graph mode. For including graph mode, the disadvantage is really binary size and dependencies. We decided that binary size was a reasonable tradeoff for a single "batteries included" install and our biggest dependency (protobuf) is now internally built and therefore removed.

Given that, there was general agreement that we should have a single install minus _cuda, _amd, etc. variants and some dependencies like LMDB and LevelDB, which we don't want in the core install.

I'll add you to an internal document we have discussing this, but likely we should create an external one as well.

**Comment by soumith** [comment]
Tracking regression vs master:

- This PR does not respect `NCCL_ROOT_DIR` environment variable anymore.
  - i'll look into it.

**Review by soumith — APPROVED** [review]

**Comment by avmgithub** [comment]
This breaks ppc64le builds.  Error is
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
CMake Error at cmake/Modules/FindMKL.cmake:278 (MESSAGE):
  MKL library not found.  Please specify library location
Call Stack (most recent call first):
  cmake/Dependencies.cmake:65 (find_package)
  CMakeLists.txt:187 (include)

**Comment by avmgithub** [comment]
@orionr Can you please give a suggestion on how to fix ppc64le builds?  It looks like in this https://github.com/pytorch/pytorch/blob/master/cmake/Dependencies.cmake#L44-L45  ,  it just assumes MKL is the default when building ATEN.

**Comment by soumith** [comment]
@avmgithub that doesn't look right, I'll take a look at fixing it today.

**Comment by avmgithub** [comment]
maybe I found the problem , its a typo in https://github.com/pytorch/pytorch/blob/master/tools/build_pytorch_libs.sh#L4

**Comment by xkszltl** [comment]
@orionr 
This PR overwrites `FindMKL.cmake` and the default Windows location for MKL is gone.
Should we put is back?

Thanks

**Comment by xkszltl** [comment]
There was a `set(INTEL_ROOT_DEFAULT "C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows")` in `FindMKL.cmake` for Windows.

After the commit, Linux path `/opt/intel` is still there but the Windows version got removed.

**Comment by pjh5** [comment]
@yf225 you know much more about Windows than I. Can you addres @xkszltl 's comments?

**Comment by yf225** [comment]
@peterjc123 Do you mind testing current master with the default MKL installation in `C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows`? I think we might want to add back the default MKL location in `FindMKL.cmake` in some way.

**Comment by peterjc123** [comment]
@yf225 Yes, we should add them back.

**Comment by orionr** [comment]
Thank you @peterjc123 - I'm guessing this was due to `FindMKL.cmake` being unified. Also cc @yinghai, since he's been working on MKL.

**Comment by xkszltl** [comment]
Any schedule for putting that Windows path back?

**Comment by peterjc123** [comment]
@xkszltl I'm on this!

**Pull request merged**
