### PR TITLE
[Inductor][CPP] Add ne with VecMask

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #128825
* #128808
* #128804
* #128824
* #126504
* __->__ #126940
* #126841

**Summary**
Fix https://github.com/pytorch/pytorch/issues/126824#issuecomment-2125039161 which is missing the support of `ne` with `VecMask`.

**Test Plan**
```
python test/inductor/test_torchinductor_opinfo.py -k test_comprehensive_ne_cpu_bool
```

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by isuruf — APPROVED** [review]

**Review by jgong5 — APPROVED** [review]

**Review by peterbell10 — APPROVED** [review]

**Comment by isuruf** [comment]
Merge?

**Comment by leslie-fang-intel** [comment]
> Merge?

Landed, sorry for the delay land of these 2 PRs.

**Pull request closed without merging**
