### PR TITLE
[reland][inductor] Enable CudaWrapperCodeGen for non-AOT mode

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #98534

Summary: This is a reland of #98264.

When _inductor.config.cpp_wrapper is specified, we run a
two-pass wrapper codegen to generate wrapper code in cpp which calls
cuLaunchKernel to launch pre-compiled cuda kernels, and then call
load_inline to load that generated wrapper back into the python world.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10

### CODE REVIEW

**Comment by desertfire** [comment]
@huydhn , fixed with a utility function name change.

**Comment by desertfire** [comment]
> @huydhn , fixed with a utility function name change.

Said it too soon. Needs more work.

**Review by huydhn — APPROVED** [review]
Thank you for the fix!

**Pull request closed without merging**
