### PR TITLE
Revert "Revert D32498569: allow external backend codegen to toggle whether to generate out= and inplace kernels"

### PR DESCRIPTION
**Pull request by bdhirsh**
Re-land of https://github.com/pytorch/pytorch/pull/68530

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #69951
* __->__ #69950
* #69949

This reverts commit f6cad53443704dfe5a20cc62bee14d91e3bffcaa.

Differential Revision: [D33113545](https://our.internmc.facebook.com/intern/diff/D33113545)

### CODE REVIEW

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33113545).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33113545).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33113545).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33113545).

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
