### PR TITLE
[nnc] Expose vectorized math functions to jit fuser.

### PR DESCRIPTION
**Pull request by bertmaher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #51252 [nnc] Don't fuse intrinsics on cpu if they are slower
* #51246 [nnc] Don't use sleef where it's slower
* **#51190 [nnc] Expose vectorized math functions to jit fuser.**
* #51187 [nnc] Use sleef if its symbols are available
* #51186 [nnc][trivial] Refactor llvm_jit so the wrapper class doesn't depend on ifdefs
* #51125 [nnc] Refactor generation of intrinsics to reduce the amount of macro-hell

We want to be able to call fast vectorized functions from sleef inside
the jit fuser, but only when they're supported by the host processor.  Enabling
this feature has two parts:

1. Record the addresses of the symbols, assuming they're defined.  Sleef only
defines vectorized functions if AVX is enabled, so we need to define __AVX__ to
get access to those symbols.  We don't actually need to compile anything with
AVX; the symbols just have to be present.

2. Before emitting a call to sleef, check if the host processor actually has
AVX.  LLVM makes this easy since we can just check the target feature string
for "+avx".

Differential Revision: [D26096170](https://our.internmc.facebook.com/intern/diff/D26096170/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D26096170/)!

### CODE REVIEW

**Comment by bertmaher** [comment]
Damn, no luck here either.  Back to the drawing board.

**Comment by bertmaher** [comment]
Getting closer, I think.  The perf results look nice too:
```
op             before    after  speedup
hardswish        3.45     3.50     1.01
hardswish        1.00     0.99     0.99
sigmoid          0.26     0.98     3.77
reciprocal       0.98     0.98     1.00
neg              1.05     0.99     0.94
relu             1.01     1.02     1.01
isnan            5.14     5.17     1.01
log              0.15     0.31     2.07
log10            0.12     0.58     4.83
log1p            0.14     0.76     5.43
log2             0.25     0.51     2.04
exp              0.12     0.58     4.83
expm1            0.28     1.03     3.68
erf              0.18     0.18     1.00
erfc             0.16     0.17     1.06
cos              0.16     0.54     3.38
sin              0.16     0.60     3.75
tan              0.16     0.70     4.38
acos             0.12     0.35     2.92
asin             0.11     0.45     4.09
cosh             0.24     1.02     4.25
sinh             0.17     1.07     6.29
atan             0.16     0.69     4.31
tanh             0.12     0.64     5.33
sqrt             0.64     0.18     0.28
rsqrt            0.98     0.99     1.01
abs              1.04     0.58     0.56
ceil             1.05     0.54     0.51
floor            0.97     0.58     0.60
round            0.12     0.48     4.00
trunc            1.00     0.54     0.54
lgamma           0.93     1.01     1.09
```

**Review by ZolotukhinM — APPROVED** [review]
Looks reasonable!

**Comment by bertmaher** [comment]
Ugh, so this majestic diff stack to enable sleef has a very fundamental problem, in that it fails to link if Sleef's AVX functions aren't linked in.  I *thought* it was always going to be available in the "static" binary but simply not called, but in fact we have some builds that completely elide AVX.  So, I've got to do some significant re-work here.

**Comment by bertmaher** [comment]
The fix here ended up being trivial.  Exposing these symbol addresses is only needed by the NNC LLVM backend, and I wasn't guarding the new file with `#ifdef TORCH_ENABLE_LLVM`.  I'm pretty comfortable with use of the LLVM backend depending on building with a modern instruction set.

**Pull request closed without merging**
