### PR TITLE
Add explicit schema for quantized conv/conv_prepack

### LINKED ISSUE #36511: quantized::conv2d and variants don't have explicit schema
```
    c10::RegisterOperators()
        .op("quantized::conv2d",
            c10::RegisterOperators::options().kernel<QConvInt8<2, false>>(
                DispatchKey::QuantizedCPU))
        .op("_quantized::conv2d",
            c10::RegisterOperators::options().kernel<QConvInt8<2, false>>(
                DispatchKey::QuantizedCPU))
        .op("quantized::conv2d_relu",
            c10::RegisterOperators::options().kernel<QConvInt8<2, true>>(
                DispatchKey::QuantizedCPU))
        .op("_quantized::conv2d_relu",
            c10::RegisterOperators::options().kernel<QConvInt8<2, true>>(
                DispatchKey::QuantizedCPU))
        .op("quantized::conv3d",
            c10::RegisterOperators::options().kernel<QConvInt8<3, false>>(
                DispatchKey::QuantizedCPU))
        .op("quantized::conv3d_relu",
            c10::RegisterOperators::options().kernel<QConvInt8<3, true>>(
                DispatchKey::QuantizedCPU));
```

While omitting the schema is a reasonable thing that can be done for user-defined operators, all operators in core PyTorch should have explicit schema.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #36536 Functionalize qconcat and register with new registration API
* #36535 Convert qclamp to new operator registration API.
* #36534 Convert qbatch_norm to new operator registration API.
* #36531 Update quantized README for registering operators with new API.
* #36527 Functionalize qadd and register with new registration API.
* #36520 Add a centralized TORCH_LIBRARY declaration for quantized and xnnpack ops.
* **#36513 Add explicit schema for quantized conv/conv_prepack**
* #36512 Port detach/detach to new registration API
* #36390 Port Resize to use new registration API.
* #36389 Update reference to RegisterOperators in error message in Convolution
* #36258 Switch to pybind11 style registration function API.

Fixes #36511

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D21002536](https://our.internmc.facebook.com/intern/diff/D21002536)

### CODE REVIEW

**Review by jerryzh168 — CHANGES_REQUESTED** [review]
I'll incorporate this in my PR: https://github.com/pytorch/pytorch/pull/35923

**Comment by ezyang** [comment]
@jerryzh168 You need the stack diff #36258. Just do your PR and I'll handle merge conflicts around it.

**Comment by ezyang** [comment]
(the dep diff is blocked on some @ljk53 stuff)

**Comment by jerryzh168** [comment]
> @jerryzh168 You need the stack diff #36258. Just do your PR and I'll handle merge conflicts around it.

OK, sounds good, thanks! I should be landing the PR in a few days

**Comment by ezyang** [comment]
This will be rolled up into #36389

**Pull request closed without merging**
