### PR TITLE
Test type hints using tutorials

### PR DESCRIPTION
**Pull request by csvoss**
Incremental progress towards #16574.

Create a unit test in `test_type_hints.py` which runs `mypy` over all Python files found in `tutorials/beginner_source`, `tutorials/intermediate_source`, and `tutorials/advanced_source`, skipping a blacklist comprised of any such files which were found not to successfully pass at the time of this PR's writing.

Of the files not specified in this test's blacklist, there are exactly eight from `beginner_source` which mypy currently successfully runs over! So this adds a marginal amount of coverage.

Uses a git submodule in order to get access to https://github.com/pytorch/tutorials. How sketchy is this approach? The submodule approach seems to allow us to pin to a specific commit (https://github.com/pytorch/tutorials/commit/8081dd7b67cd01180cb1b2033cfeda34a51ff6a3, in particular) so that new tutorials don't suddenly cause test failures here.

In future work, we could remove individual files off of this blacklist, see what their deal is, and fix them.

Tested using `pytest test/test_type_hints.py`.

### CODE REVIEW

**Comment by ezyang** [comment]
@csvoss sorry this fell off the wagon. I'll take a look at it soon

**Comment by ezyang** [comment]
OK, let's talk about the submodule. This is sort of intimately related to #32004

The most important thing to know about submodules is what happens when you have a PR to PyTorch that requires an update to the tutorial (because otherwise the tutorial tests will fail). Submodules make this possible, albeit kind of painful: you first submit an upstream PR to the tutorial repo, get it merged, then update the PR here and merge. However, I feel we don't break tutorials too frequently, so this might be the right tradeoff in this situation, and it would pave the way to running tutorials in CI. There's an aesthetic objection to having tutorials always get checked out when people clone PyTorch, but this could be fixed by just hard-coding a hash (similar to how we test against torchvision in our CI).

**Comment by ezyang** [comment]
Reviewing the rest of the PR, I like the approach. Going to add some more peeps for second opinions.

**Comment by soumith** [comment]
as discussed offline with Edward, I think submoduling `tutorials` is too heavy-weight, and we need to move to something like hash-recording (a text file in .circleci folder that has hashes, and the hashes get updated by a bot that checks for stable).

**Comment by ezyang** [comment]
If you want a suggestion about where to put the submodule hashes, the most lightweight way to do this is checkout tutorials at a hash in `.jenkins/pytorch/test.sh` (similar to vision, except you're not pip installing it ) and then in the test script assume that there is a checkout of tutorials at some well known location. There's better / more sustainable ways to do this, but this is the most surgical change

**Pull request closed without merging**
