### PR TITLE
only run the circleci mac/ios jobs on prs

### PR DESCRIPTION
**Pull request by clee2000**
as in title, since they were being run on nightly when they dont need to be (and they were failing), also dont run on master b/c the github actions version already exists for that

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Review by janeyx99 — APPROVED** [review]
Seems okay, but it is also at this time when I think about just using config.yml instead of all these scripts 😛

**Review by huydhn — APPROVED** [review]

**Comment by seemethere** [comment]
> Seems okay, but it is also at this time when I think about just using config.yml instead of all these scripts stuck_out_tongue

I would generally agree with this centiment

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Hmm, shouldn't those only run on pull request to begin with?

**Pull request closed without merging**
