### PR TITLE
Added base parameter to math.log

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #21131 Added degrees, radians, ldexp
* #21130 Added frexp, isinf, isnan, isfinite
* #21129 Added factorial
* #21128 Finished trigonometric functions
* #21127 Finished the high-priority functions
* #21126 Added remainder of high-priority trigonometric math ops
* #21125 Added better tests for math ops and unified them
* #21124 made floor/ceil return ints
* **#21151 Added base parameter to math.log**

Differential Revision: [D15563185](https://our.internmc.facebook.com/intern/diff/D15563185)

### CODE REVIEW

**Comment by Chillee** [comment]
Sorry for continually remaking this PR, but I think I messed up something small with ghstack that causes this PR to be constantly remade. Can someone stamp this quickly so I can hopefully stop constantly remaking this PR?

**Review by ailzhang — COMMENTED** [review]
Here might fail the lint check

**Comment by Chillee** [comment]
It passes the precommit lint check - I think it's fine.

That code is also removed in a couple commits later in the stack.

**Review by ailzhang — APPROVED** [review]
LGTM

**Comment by xuhdev** [comment]
What happens if `b == 1`? Perhaps we should at least add a test for that case?

**Comment by Chillee** [comment]
@xuhdev I've done that later up in the stack (I unified all the math tests and added much more exhaustive checkign): https://github.com/pytorch/pytorch/pull/21125 

But to answer your question, we return `inf`, which isn't ideal. Unluckily, there doesn't seem to be any easy way to handle these errors, so we've decided to just fail silently (+ `inf` is a natural value to return, although it doesn't conform exactly with the python API)

**Pull request closed without merging**
