### PR TITLE
Update version strings to 1.2

### PR DESCRIPTION
**Pull request by gchanan**

### CODE REVIEW

**Review by bddppq — APPROVED** [review]

**Review by ezyang — APPROVED** [review]
cc @pjh5

**Review by pjh5 — APPROVED** [review]
This is all the correct places for the binaries. Not sure about everything else.

**Comment by ezyang** [comment]
onnx is still going to fail without https://github.com/pytorch/pytorch/pull/20836

**Comment by gchanan** [comment]
I see, I'll wait for https://github.com/pytorch/pytorch/pull/20836.

**Pull request closed without merging**
