### PR TITLE
[CI] Switch to check against expected result files for dynamo_eager and aot_eager benchmark tests

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #113668
* __->__ #113559
* #113446
* #113575
* #113574

cc @albanD @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by desertfire** [comment]
@albanD, [pr-sanity-checks](https://hud.pytorch.org/pr/pytorch/pytorch/113559#18675795087) ([gh](https://github.com/pytorch/pytorch/actions/runs/6867445998/job/18675795087)) failure msg suggests to contact you. What should I do next, given the large amount of added lines are coming from expected result files?

**Comment by ezyang** [comment]
I'm not reviewing any of these until the csv formatting is fixed

**Comment by desertfire** [comment]
> I'm not reviewing any of these until the csv formatting is fixed

https://github.com/pytorch/pytorch/pull/113446#discussion_r1393198464

**Review by albanD — COMMENTED** [review]
If the PR is above the limit due to generated files that we expect to be long, We can ignore. If it is real code, the PR should be broken down.

Since this is generated code I can add the ignore flag.

**Review by ezyang — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
