### PR TITLE
[doc] caution torch.multinomial usage 

### LINKED ISSUE #107406: Problems of torch.multinomial
### 🐛 Describe the bug

There are few theoretical problems with sampling from multinomial distribution using `torch.multinomial`.

**Multinomial distribution**
x ~ Multinomial(n, p)
 

- n: the number of independent trials (e.g., n=100 rolls of a dice)

- K: the number of classes (e.g., K=6 for a dice, K=2 for a coin)
the outcome of each trial falls into one of K classes

- p: [p_1, p_2, …, p_k, …, p_K], probabability parameter, a vector 
p_k = the probability that the outcome of a single trial falls into class k 
p_1 + p_2 + ... + p_K = 1

- x: [x_1, x_2, …, x_k, …, x_K], a sample point, a vector
x_k = the number of trials for which the outcome falls into class k
x_1 + x_2 + … + x_K = n

**Problem 1**
The sample point x of multinomial distribution is a vector [x_1, x_2, …, x_K] as noted above.
However, `torch.multinomial(replacement=True)` generates "outcomes of n trials" instead of random variable x that consists of "the number of trial for which the outcome falls into class k". This is very confusing as exemplified here, https://discuss.pytorch.org/t/trying-to-understand-the-torch-multinomial/71643. 

**Example**
```python
import torch

p = torch.tensor([2/10, 3/10, 5/10])
n = 10
out = torch.multinomial(p, n, replacement=True)
print(out) # tensor([1, 2, 1, 2, 2, 2, 1, 2, 0, 2])
 
# User needs to convert out (the outcomes of n trials) 
# to random variable using method as suggested here, 
# https://discuss.pytorch.org/t/trying-to-understand-the-torch-multinomial/71643/4
# This leads to unsound sampling from multinomial distribution
# without requiring user's further understanding and care
x = out.unique(return_counts=True)[1]
print(x) # tensor([1, 3, 6])
```

**Problem 2**
`replacement` option should be removed. `torch.multinomial(replacement=False)` by default. Sampling without replacement makes no sense here.

**Example**
```python
import torch
 
p = torch.tensor([2/10, 3/10, 5/10])
n = 3
out = torch.multinomial(p, n)
print(out) # tensor([1, 0, 2])
 
x = out.unique(return_counts=True)[1]
print(x) # tensor([1, 1, 1])
```

1. By definition of multinomial probability distribution, each trial is independent. Thus, we can observe any outcomes (according to p_k) at any trials. If `replacement=False`, then each trial is not independent (e.g., we cannot observe eye 3 after we once observe eye 3).
2. By definition of multinomial probability distribution, n > 0 and there is no constraint on n. If `replacement=False`, then n is constrained to n <= K.
3. If `replacement=False`, the sample point x, [x_1, ..., x_K], is always [1, …, 1]. In other words, regardless of the values of the parameter p, [p_1, …, p_K], `torch.multinomial(replacement=False)` always behaves in a uniform fashion as if p were [1/K, …, 1/K].
 
Above reasons simply make no sense to multinomial distribution.

### Versions

master

cc @fritzo @neerajprad @alicanb @nikitaved @svekars @carljparker @pbelevich

### PR DESCRIPTION
**Pull request by min-jean-cho**
Fixes #107406 

cc @svekars @carljparker

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
I'm not sure about this.
The current doc already states explicitly on the first line "contains :attr:`num_samples` indices sampled from the multinomial probability distribution". 
So saying that it 'generates "outcomes of n trials" instead of random variable x that consists of "the number of trial for which the outcome falls into class k".' in a note at the end feels redundant. You can rephrase that first sentence if you think it could be made clearer.

Also every single sampling function in pytorch has this behavior, so I'm not sure we want to say that this function is special in any way.

For a more probability-focused view on this, I would recommend to use the torch.distributions.* submodule which might be better for you?

**Comment by min-jean-cho** [comment]
Hi there @albanD,

The most important point that I wanted to add and explain in the doc is that multinomial distribution is multivariate. 
The sampled point is a vector, not a single value. I believe this is the root source of some confusion such as `replacement=False`.

> The current doc already states explicitly on the first line "contains :attr:num_samples indices sampled from the multinomial probability distribution".
So saying that it 'generates "outcomes of n trials" instead of random variable x that consists of "the number of trial for which the outcome falls into class k".' in a note at the end feels redundant. You can rephrase that first sentence if you think it could be made clearer.

I initially wanted to explain at the end (kind of like a further reading section for those interested), first by giving a definition of the multinomial distribution, then explaining the difference that `torch.multinomial` has from the definition. Surely, we can rephrase the first sentence if that's a better place.

> Also every single sampling function in pytorch has this behavior, so I'm not sure we want to say that this function is special in any way.

Here, the source of the confusion is univariate vs. multivariate. For univariate distributions (e.g., bernoulli, normal, poisson), sampled point x is a single value, and the output shape is _num_samples_. Hence makes sense that the behavior of `torch.bernoulli`, `torch.normal`, `torch.poisson` is out_i ~ Distribution(input_i). For multivariate distributions (e.g., multinomial), the sampled point **x** is a vector, and the output shape is (_num_samples_, _k_). Hence I wanted to explain the distinction with the behavior of `torch.multinomial` whose output shape is (_m_, _num_samples_).

> For a more probability-focused view on this, I would recommend to use the torch.distributions.* submodule which might be better for you?

Indeed `torch.distributions.multinomial.Multinomial` more directly follows the definition of multinomial distribution. I thought stating the distinction with `torch.multinomial` may help caution the users.

What do you think? I'm very open to changes and suggestions :D

**Comment by min-jean-cho** [comment]
Hi @albanD, wondering if there's any udpate/comment on this! Thanks!
Also cc., @fritzo @neerajprad  @alicanb

**Comment by albanD** [comment]
Hey!
I still don't think that such an extensive "note" after the current doc is great as it partially overlaps with the current doc and tries to explain concepts that needs a lot more space to explain.

> The most important point that I wanted to add and explain in the doc is that multinomial distribution is multivariate.

Adding this at the beginning of the docstring sounds like a good aside to make there.
For a precise definition of these distributions, please use an outside link to some source (or the distributions.* doc if you think that one is good).

**Comment by min-jean-cho** [comment]
> The most important point that I wanted to add and explain in the doc is that multinomial distribution is multivariate.
> 
> Adding this at the beginning of the docstring sounds like a good aside to make there.

Hi! How does this sound:

_Aside_: Multinomial distribution is multivariate. Refer to `torch.distributions.multinomial.Multinomial` for more details.

**Comment by albanD** [comment]
Yes that sounds good, I think the right place to add it is something like the following:
```
Returns a tensor where each row contains :attr:`num_samples` indices sampled
from the multinomial (a stricter name here would be multivariate. Refer to torch.distributions.multinomial.Multinomial for more details) probability distribution located in the corresponding row
of tensor :attr:`input`.
```

**Comment by min-jean-cho** [comment]
Thanks @albanD for the suggest, how does the change look?

**Review by albanD — APPROVED** [review]
SGTM

**Pull request closed without merging**
