### PR TITLE
[jit] move batchnorm and layernorm fusion to decompose

### LINKED ISSUE #20099: RuntimeError: input->node()->kind() == prim::Constant ASSERT FAILED at /opt/conda/conda-bld/pytorch-cpu_1556653093101/work/torch/csrc/jit/passes/graph_fuser.cpp:483, please report a bug to PyTorch. (mergeNodeIntoGroup at /opt/conda/conda-bld/pytorch-cpu_1556653093101/work/torch/csrc/jit/passes/graph_fuser.cpp:483)
## To Reproduce

```
import torch.nn as nn
import torch.nn.functional as F
import torch

class Net(torch.jit.ScriptModule):

    def __init__(self):
        super(Net,self).__init__()

        kernel_size = 3
        stride = 1
        filters = 1

        self.conv1 = nn.Conv2d(1, filters, kernel_size, stride)
        self.bn1 = nn.BatchNorm2d(filters)

    @torch.jit.script_method
    def forward(self, x):
        x = self.bn1(F.relu(self.conv1(x)))
        return x


m = Net()

m.eval()
with torch.no_grad():
    output = m(torch.zeros((1,1,10,10)))

```

## Expected behavior

Return a tensor of rank (1,1,8,8).

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.14.2
[pip3] numpydoc==0.7.0
[pip3] torch==1.1.0
[pip3] torchvision==0.2.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2018.0.1             h19d6760_4
[conda] mkl-dnn                   0.14                          2    intel
[conda] mkl-service               1.1.2            py36h17a0993_4
[conda] pytorch-cpu               1.1.0               py3.6_cpu_0    pytorch
[conda] torchvision-cpu           0.2.2                      py_3    pytorch

## Additional context

Works fine without `@torch.jit.script_method`

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#20337 move batchnorm and layernorm to decompose**

Summary:
The term `isFusableNorm` is confusing, since we partially fusing batchnorm and layernorm, the `isFusable` check should actually be false for these two, otherwise we will try to merge/move these two ops into FusionGroup when there's no fusion group already (createSingletonFusionGroup will try to move these two ops into a newly created FusionGroup), which is wrong in the first place. This causes some error when we put the `batchnorm` as the last op of the graph because we want to move `batchnorm` to fusion group but its inputs are not valid to move to. 

This PR move these two from fuser to decomposition pass, and only decompose when the input is on a GPU device, which still enables the faster CPU inference batchnorm op by not decomposing them. It will also not changing the previous semantics, fusion will still happen after the decomposition.

This fixes #20099

Differential Revision: [D15448596](https://our.internmc.facebook.com/intern/diff/D15448596)

### CODE REVIEW

**Comment by t-vi** [comment]
So unless I'm mistaken, the build-failures are legit?

**Comment by wanchaol** [comment]
@t-vi yeah, looks like the input does not get specialized to dimensioned tensor type due to some reason, will fix the tests :)

**Comment by wanchaol** [comment]
It looks like shape analysis aliasing accidentally erase the input shape information, which we could preserve for decomposition and more optimization on graph inputs, #20661 will fix this.

**Review by ngimel — APPROVED** [review]
Generally looks good, small nits

**Pull request closed without merging**
