### PR TITLE
Disable torchdynamo in backwards compiler harder

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #88132

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

### CODE REVIEW

**Comment by ezyang** [comment]
If NVIDIA could take point on adding the test case for this, if it does fix the problem, I'd greatly appreciate it.

**Comment by IvanYashchuk** [comment]
It doesn't fix the problem. Adding `disable` for `fw_compiler` doesn't fix it either.

**Comment by jjsjann123** [comment]
> It doesn't fix the problem. Adding single, double, or triple `disable` for `fw_compiler` doesn't fix it either.

Let's open an upstream issue with a concrete example on this~~

**Comment by IvanYashchuk** [comment]
Here's a test:
```py
import torch
import torch._dynamo as torchdynamo
from warnings import catch_warnings

@torchdynamo.optimize("nvprims_nvfuser")
def func(a, b):
    return a.sin() + b.cos()
a = torch.randn(3, 4, device="cuda")
b = torch.randn(3, 4, device="cuda")
with catch_warnings(record=True) as w:
    func(a, b)
    assert len(w) == 1
    assert "Your compiler for AOTAutograd" in str(w[-1].message)

```

**Comment by ezyang** [comment]
OK, I confirmed in the repro there is no live dynamo callback at the point nvfuser is invoked, so this isn't the fix. @suo bouncing this back to your court, but let's yank the PR first.

**Comment by ezyang** [comment]
Also, nvfuser is suppressing too many errors, I had to unpeel this to get useful stack traces

```
     with torch_function_mode:
-        try:
-            gm = get_isolated_graphmodule(func, args, kwargs)
-        except Exception as e:
-            warn(
-                "get_isolated_graphmodule failed on decomposition: "
-                + func.__name__
-                + " with error message: "
-                + str(e)
-            )
-            # returns unsupported when tracing fails.
-            return True
+        gm = get_isolated_graphmodule(func, args, kwargs)
 
     supported_ops = NvfuserPrimOperatorSupport()
     call_function_nodes = filter(lambda n: n.op == "call_function", gm.graph.nodes)
```

suggest reporting the full internal backtrace in this situation

**Review by bertmaher — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
