### PR TITLE
Add repo-specific scale config files

### PR DESCRIPTION
**Pull request by ZainRizvi**
Part of moving pytorch/pytorch CI infra to a Linux foundation run AWS account.

For self-hosted runners that can run jobs from just a single repo, the runner scalers expect them to be stored in the repo itself.

These scale-config files define how the linux foundation's self-hosted runners are configured. These will apply to runners that only are available to the pytorch/pytorch and pytorch/pytorch-canary repos

### CODE REVIEW

**Review by zxiiro — APPROVED** [review]

**Review by zxiiro — APPROVED** [review]

**Review by huydhn — APPROVED** [review]
LGTM! I guess we have decided to keep the scale config here?

**Review by atalman — APPROVED** [review]

**Comment by ZainRizvi** [comment]
> LGTM! I guess we have decided to keep the scale config here?

At least for now. This is how the pre-existing code expects per-repo level runners to be configured.  A config in test-infra is expected for org-wide runners

**Pull request closed without merging**
