### PR TITLE
[docs] document dim argument to tensor.size()

### PR DESCRIPTION
**Pull request by garymm**
[docs] document dim argument to tensor.size()

### CODE REVIEW

**Comment by garymm** [comment]
Rendered doc:
image

**Review by zou3519 — APPROVED** [review]

**Comment by garymm** [comment]
@zou3519 thanks for reviewing. Pretty sure the failures are not my fault but I don't have permissions to rerun the failed checks. Could you rerun them for me?
Thanks

**Comment by zou3519** [comment]
I hit rerun on https://github.com/pytorch/pytorch/pull/58777/checks?check_run_id=2643776762

**Comment by garymm** [comment]
@zou3519 sorry to keep bothering you but I guess all remaining failures are probably due to flakiness. Could you please help me get this merged?

**Pull request closed without merging**
