### PR TITLE
[MPS] Support torch.Event for MPS

### PR DESCRIPTION
**Pull request by guangyey**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #137493
* #140138
* #138677
* #133572
* __->__ #142468

# Motivation
Support `torch.Event` on mps backend.

### CODE REVIEW

**Comment by guangyey** [comment]
@malfet May I know if this PR is reasonable to you?

**Comment by kulinseth** [comment]
Don't we have this support here ?
https://github.com/pytorch/pytorch/blob/main/torch/mps/event.py

**Comment by kulinseth** [comment]
@guangyey can you take a look and see what's missing ?

**Review by malfet — COMMENTED** [review]
Thank you very much for the prompt fix

**Comment by malfet** [comment]
> Don't we have this support here ? https://github.com/pytorch/pytorch/blob/main/torch/mps/event.py

This PR is step forward towards the idea of being able to write accelerator agnostic code and replace neverending
```python
event = torch.cuda.Event() if torch.cuda.is_available() else torch.mps.Event() if torch.mps.is_available() else DummyEvent()
```
with something `torch.Event()`

**Review by malfet — APPROVED** [review]

**Comment by guangyey** [comment]
> @guangyey can you take a look and see what's missing ?

As @malfet explained, this PR will support device-agnostic `torch.Event("MPS")` on the MPS backend. This will make it easier for the user to write device-agnostic code.

**Review by kulinseth — COMMENTED** [review]
Looks good to me.

**Comment by guangyey** [comment]
> Looks good to me.

Thanks.

**Pull request closed without merging**
