### PR TITLE
[pt2-bench] fix accuracy failure for beit_base_patch16_224 during training

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #130005
* #129941
* #129996

This model's accuracy test recently regressed. I have a quite smooth debugging process to figure out the cause. So I'd like to write it down just in case it can be helpful.

Clicking the model name beit_base_patch16_224 on the dashboard, we are able to see the pass status of the model in e.g. the past month. For this model, we can see that it starts to fail on June 08:

Screenshot 2024-07-02 at 5 36 35 PM

What's nice is the dashboard shows the nightly commits for each run.

Running
```
git log --oneline a448b3ae9537c0ae233fb9199a4a221fdffbb..0e6c204642a571d5a7cd60be0caeb9b50faca030 torch/_inductor/
```
Gives us the list of Inductor PRs between the good and bad commit: https://gist.github.com/shunting314/eb57965688fc9e1746fcfa9b7b6b02df 

Roughly looking thru the PRs, I feel 
```
ffc202a1b91 Added remove_noop_ops to joint_graph_passes (#124451)
```
can change numerics so I disable it locally by this one line change: https://gist.github.com/shunting314/13aec768bda986056d0fb40dce53396e  . And then the accuracy test pass. (Command: time python benchmarks/dynamo/timm_models.py --accuracy --training --amp --backend inductor --disable-cudagraphs --device cuda --only beit_base_patch16_224  )

Horace's PR (https://github.com/pytorch/pytorch/pull/124451) itself is valid. It removes no-op ops in joint-graph. I think maybe the graph get changed and cause the partitioner do different recomputation decisions. That can cause some numerics change.

Since this is not a real issue, I'll raise the tolerance to make it pass.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by eellison — APPROVED** [review]

**Comment by eellison** [comment]
cc @chillee any reason you would expect recomputation changes to have real numerics issues ?

**Comment by Chillee** [comment]
@shunting314 I wonder whether we start pattern-matching `F.scaled_dot_product_attention` in this case?

**Review by jansel — APPROVED** [review]

**Comment by shunting314** [comment]
> I wonder whether we start pattern-matching F.scaled_dot_product_attention in this case?

I checked the wrapper generated with and without the remove_noop_ops call, in either case, the wrapper contains 12 calls for the scaled_dot_product_attention kernel in fwd wrapper and the corresponding backward kernel in the backward wrapper.

Here are some pastes for reference
- without the remove_noop_ops call: https://gist.github.com/shunting314/df21af4ed4c4e1bb9b329cbc6cf64102
- with the remove_noop_ops call: https://gist.github.com/shunting314/4ea8ac8fbd5c0de9addfc5368ae501d2

**Pull request closed without merging**
