### PR TITLE
[MPS] Fix cat with non-contiguous memory layout

### LINKED ISSUE #89353: cat with channels-last memory layout is incorrect on MPS
### 🐛 Describe the bug

Added a new sample input for channels last in https://github.com/pytorch/pytorch/pull/89332 and MPS started failing https://github.com/pytorch/pytorch/actions/runs/3504224099/jobs/5869876607

```
2022-11-19T16:36:42.9229520Z ======================================================================
2022-11-19T16:36:42.9229620Z FAIL [0.061s]: test_output_match_cat_cpu_int32 (__main__.TestConsistencyCPU)
2022-11-19T16:36:42.9229740Z ----------------------------------------------------------------------
2022-11-19T16:36:42.9229800Z Traceback (most recent call last):
2022-11-19T16:36:42.9230030Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_3504224099/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
2022-11-19T16:36:42.9230100Z     result = test(self, **param_kwargs)
2022-11-19T16:36:42.9230320Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_3504224099/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 828, in test_wrapper
2022-11-19T16:36:42.9230380Z     return test(*args, **kwargs)
2022-11-19T16:36:42.9230540Z   File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/test_mps.py", line 7900, in test_output_match
2022-11-19T16:36:42.9230580Z     raise e
2022-11-19T16:36:42.9230730Z   File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/test_mps.py", line 7896, in test_output_match
2022-11-19T16:36:42.9230820Z     self.assertEqual(cpu_out, mps_out, atol=atol, rtol=rtol)
2022-11-19T16:36:42.9231030Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_3504224099/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2561, in assertEqual
2022-11-19T16:36:42.9231140Z     assert_equal(
2022-11-19T16:36:42.9231350Z   File "/Users/ec2-user/runner/_work/_temp/conda_environment_3504224099/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1118, in assert_equal
2022-11-19T16:36:42.9231410Z     raise error_metas[0].to_error(msg)
2022-11-19T16:36:42.9231500Z AssertionError: Tensor-likes are not equal!
2022-11-19T16:36:42.9231510Z 
2022-11-19T16:36:42.9231560Z Mismatched elements: 15 / 16 (93.8%)
2022-11-19T16:36:42.9231640Z Greatest absolute difference: 16 at index (1, 0, 0, 0)
2022-11-19T16:36:42.9231720Z Greatest relative difference: inf at index (0, 0, 1, 1)
```

I'm going to xfail the test for now.

### Versions

master

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

### PR DESCRIPTION
**Pull request by qqaatw**
1. If the output layout is non-contiguous, we create a temporary tensor to store the computation's output and then copy it back to the original output tensor.
2. Clean up unnecessary comments.
3. Clean up unnecessary checks as they have been checked in the precompute function.

Fixes #89353

### CODE REVIEW

**Comment by razarmehr** [comment]
The copy is not required. The issue is already fixed without copying and will be upstreamed soon.
https://github.com/kulinseth/pytorch/pull/212

**Comment by qqaatw** [comment]
Hi @razarmehr, I see. Can you please mention the issue addressed next time when you propose a PR in a downstream repo so others won't rework on the same issue, thank you.

**Comment by razarmehr** [comment]
Hi @qqaatw. I found out about the problem in our internal testing, and not from Github. So at the time of fixing, I wasn't aware about that Github issue, otherwise I would've linked my PR to it.

**Comment by qqaatw** [comment]
> Hi @qqaatw. I found out about the problem in our internal testing, and not from Github. So at the time of fixing, I wasn't aware about that Github issue, otherwise I would've linked my PR to it. Anyway it should be fixed now. Thanks.

Okay, understood. Thanks.

**Pull request closed without merging**
