### PR TITLE
Update pytorch-triton-rocm wheel to use ROCm5.7

### PR DESCRIPTION
**Pull request by jataylo**
Changes:
- Enables bfloat16 support in MFMA dot on MI200 (https://github.com/ROCmSoftwarePlatform/triton/commit/23979098c881536a52ba3edf8164e12296ecfe7b)
- Add support for int8 to bfloat16 conversion (https://github.com/ROCmSoftwarePlatform/triton/commit/2d3e38e182e7b9b21aadb90bc2ab0d6514b3c760) fixing a bug in bf16 triton gemm workloads.
- Enable scanOp lowering by adding shfl_up support https://github.com/ROCmSoftwarePlatform/triton/pull/324
- MFMA16 support - support for the mfma_16x16xX instructions - these help perf on smaller sized GEMMs - https://github.com/ROCmSoftwarePlatform/triton/commit/7e34c244c284a84191a1a7bb0cd484c6345de650
- configurable wavefront-per-eu - this helps us increase our occupancy in certain use cases such as Flash Attention - https://github.com/ROCmSoftwarePlatform/triton/commit/e801638b40dac4fd511f973d9899f033ae94dbec
- Support for f8 types https://github.com/ROCmSoftwarePlatform/triton/commit/e8a35b3968780e48df1374482d56cc6cdbb9e351
- Update pytorch-triton-rocm wheel to use ROCm5.7
- Many bug fixes and optimisations

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang

### CODE REVIEW

**Comment by jataylo** [comment]
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: ../../triton/third_party/hip/lib/hsa/libhsa-runtime64.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'` with latest pin attempt

**Comment by jataylo** [comment]
Trying another rebase as there are many observed failures that are coming from the commit pin change.

**Comment by jataylo** [comment]
In a rebase cycle from upstream failures, hoping this is the final rebase :)

**Review by malfet — APPROVED** [review]

**Comment by jataylo** [comment]
Hi @malfet looks like this is the failure, but I don't this test failing in the HUD and seems unrelated to our change. Should we try to rebase again?
```
2023-11-06T17:57:53.8237819Z =========================== short test summary info ============================
2023-11-06T17:57:53.8240407Z FAILED [0.0141s] test_meta.py::TestMetaCPU::test_meta_outplace_vdot_cpu_complex64 - RuntimeError: failed to run: torch.vdot(
2023-11-06T17:57:53.8243810Z *(tensor(..., device='meta', size=(5,), dtype=torch.complex64) stride=(1,), tensor(..., device='meta', size=(5,), dtype=torch.complex64) stride=(1,)),
2023-11-06T17:57:53.8246475Z **{'out': tensor(..., device='meta', size=(), dtype=torch.complex64) stride=()}
2023-11-06T17:57:53.8247855Z )
2023-11-06T17:57:53.8248213Z 
```

**Review by pruthvistony — APPROVED** [review]

**Pull request closed without merging**
