### PR TITLE
[ONNX] Export quantized::layer_norm to LayerNormalization in opset >=17

### LINKED ISSUE #126160: [ONNX] Export quantized::layer_norm to LayerNormalization in opset >=17
### 🐛 Describe the bug

When exporting a PyTorch model containing float32 `aten::layer_norm` ops to ONNX opset >17, these layers are translated to ONNX `LayerNormalization`s as expected. However, `quantized::layer_norm`s still fall through to the definition given in [symbolic_opset10.py](https://github.com/pytorch/pytorch/blob/9dec41b684a4284c4e052e295314c23f0f942fec/torch/onnx/symbolic_opset10.py#L922), producing an unnecessarily complicated graph (with `ReduceMean`s, `div`s and `sqrt`s).

I added
```py
@_onnx_symbolic("quantized::layer_norm")
def quantized_layer_norm(
    g: jit_utils.GraphContext,
    x,
    normalized_shape,
    weight,
    bias,
    eps,
    op_scale,
    op_zero_point,
):
    x, _, _, _ = symbolic_helper.dequantize_helper(g, x)

    output = layer_norm(g, x, normalized_shape, weight, bias, eps, False)

    return symbolic_helper.quantize_helper(g, output, op_scale, op_zero_point)
```
to [symbolic_offset17.py](https://github.com/pytorch/pytorch/blob/9dec41b684a4284c4e052e295314c23f0f942fec/torch/onnx/symbolic_opset17.py) and this now produces the graph I would expect (not submitting a PR because I'm not confident about details like where/when to use `@symbolic_helper.parse_args`/`@_beartype.beartype` etc...)

### Versions

```
nathaniel@R9128537:~/dev$ python collect_env.py
Collecting environment information...
PyTorch version: 2.2.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Quadro T2000 with Max-Q Design
Nvidia driver version: 538.18
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz
CPU family:                      6
Model:                           165
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        2
BogoMIPS:                        5616.01
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi ept vpid ept_ad fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        1.5 MiB (6 instances)
L3 cache:                        12 MiB (1 instance)
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] onnx==1.16.0
[pip3] onnx-graphsurgeon==0.5.2
[pip3] onnx2tf==1.21.1
[pip3] onnxruntime-gpu==1.17.1
[pip3] onnxsim==0.4.36
[pip3] pytorch3d==0.7.6
[pip3] sng4onnx==1.0.4
[pip3] torch==2.2.0
[pip3] torch_cluster==1.6.3+pt22cu121
[pip3] torch_geometric==2.5.3
[pip3] torch_scatter==2.1.2+pt22cu121
[pip3] torch_sparse==0.6.18+pt22cu121
[pip3] torch_spline_conv==1.2.2+pt22cu121
[pip3] torchaudio==2.1.2+cu121
[pip3] torchvision==0.16.2+cu121
[pip3] triton==2.2.0
[conda] Could not collect
```

### PR DESCRIPTION
**Pull request by NathanielB123**
Fixes #126160

### CODE REVIEW

**Comment by titaiwangms** [comment]
Hi @NathanielB123 Please sign CLA as it suggests.

**Comment by NathanielB123** [comment]
> Hi @NathanielB123 Please sign CLA as it suggests.

I *think* I count as corporate contributor given I am interning at Arm working on ML stuff right now. I sent the email to the CLA manager so I guess I just have to wait now (will also ask on Monday to double check how this stuff works).

**Comment by titaiwangms** [comment]
> > Hi @NathanielB123 Please sign CLA as it suggests.
> 
> I _think_ I count as corporate contributor given I am interning at Arm working on ML stuff right now. I sent the email to the CLA manager so I guess I just have to wait now (will also ask on Monday to double check how this stuff works).

I remember it's easier to sign as individual contributor.

**Review by titaiwangms — DISMISSED** [review]

**Comment by NathanielB123** [comment]
Oops sorry I forgot about this. I asked around a bit at work and it sounds like the process for getting open-source contributions approved is stupidly complicated and the standard approach in my team is to sidestep this by only opening GH issues, not PRs. Very dumb but ¯\_(ツ)_/¯, companies gotta be paranoid about their IP I guess, closing.

If someone was to create their own PR fixing the same root issue in perhaps a vaguely similar way (because this fix really is quite obvious) I feel like there would be no problems, but IANAL.

**Comment by titaiwangms** [comment]
> Oops sorry I forgot about this. I asked around a bit at work and it sounds like the process for getting open-source contributions approved is stupidly complicated and the standard approach in my team is to sidestep this by only opening GH issues, not PRs. Very dumb but ¯\_(ツ)_/¯, closing.
> 
> If someone was to create their own PR fixing the same root issue in perhaps a vaguely similar way (because the fix really is quite obvious) I assume there would be no problems, but IANAL.

Thanks for trying! I will open another PR for this.

**Pull request closed without merging**
