### PR TITLE
[ONNX] Add export of prim::data

### PR DESCRIPTION
**Pull request by KsenijaS**
Add export of prim::data

### CODE REVIEW

**Review by neginraoof — APPROVED** [review]
LGTM. Thanks.

**Review by bzinodev — APPROVED** [review]

**Comment by KsenijaS** [comment]
@bzinodev can this PR be merged?

**Comment by KsenijaS** [comment]
@bzinodev this PR is ready to be merged. Thanks!

**Comment by KsenijaS** [comment]
@bzinodev can we merge this PR? Thanks

**Pull request closed without merging**
