### PR TITLE
[ROCm] Fix compiler unwrapping step in jenkins build scripts for Caffe2/PyTorch on ROCm

### PR DESCRIPTION
**Pull request by iotamudelta**
Fix the regex (requires enabling extglob) for two digit clang releases.

While there, also fix it for three digit releases with the hope that I
do not need to touch it for some time.

Unfortunately, this regex requires extglob to be enabled in the shell.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
lol

**Comment by ezyang** [comment]
Kinnae have a rebase

**Comment by ezyang** [comment]
```

Aug 29 20:10:03 ./.jenkins/caffe2/build.sh: line 282: syntax error near unexpected token `('
```

**Review by zou3519 — CHANGES_REQUESTED** [review]
Builds appear to be failing

**Comment by iotamudelta** [comment]
yes, the failures seem real. they fall through to the ROCm line (?!) and since shopt extglob was not enabled, the syntax is unknown.

@ezyang any ideas/suggestions here?

**Comment by ezyang** [comment]
Maybe shopt has to be placed in the actual source file itself, as it affects parsing?

**Comment by iotamudelta** [comment]
the ROCm tests which should be the only ones affected by the change pass though

**Comment by ezyang** [comment]
Oh, I bet it's something dumb like, we're running different versions of bash/sh in the CI jobs, and ROCm's is new enough to understand the syntax, but the other ones aren't. Are you sure you can't rewrite this test to do something else?

**Comment by iotamudelta** [comment]
I've moved it into a helper script that enables `extglob` - let's see if that does the trick!

**Comment by iotamudelta** [comment]
@zou3519 can you revisit? Thanks!

**Review by bddppq — APPROVED** [review]

**Pull request closed without merging**
