### PR TITLE
Fix options usage in C++ module / optimizer constructors

### PR DESCRIPTION
**Pull request by yf225**
With this PR, we establish the following conventions:
1. Options in C++ module / optimizer constructors should always be `const SomeOptions&` type, not `SomeOptions` type.
2. The options constructor arg should always be named `options_`, not `options`, to not be confused with the module / optimizer's internal field `options`.
3. We never use `std::move` to assign `options_` to the module / optimizer's internal field `options` in the constructor definition. Instead, we simply use `options(options_)`.

Here is the reasoning:
We might be tempted to declare the constructor as `SomeModule(SomeOptions options_)` and have `options(std::move(options_))` in the member initialization list. However, this can be a dangerous design because the constructor might use `options_` to set values for other member fields in the member initialization list (e.g. https://github.com/pytorch/pytorch/blob/8317f75b79fb78ceeeb928aa23a901d57274b9e1/torch/csrc/api/include/torch/optim/lbfgs.h#L30-L34), and use-after-move can cause hard-to-debug problems.
Instead, we choose to explicitly use `const SomeOptions&` type for `options_`, and never use `std::move` to assign it to the internal `options` field. This way we have stronger guarantee on the validity of `options_` at any point in the constructor.

Notable exceptions to the above conventions:
1. C++ Embedding module doesn't adhere to the conventions now, which will be fixed after https://github.com/pytorch/pytorch/pull/26358 is landed.
2. C++ dataloader and dataset classes likely need similar changes. We will do it when we start to work on dataloader/dataset parity.

Thanks @ShahriarSS for discovering the options usage inconsistency! 🚀

### CODE REVIEW

**Comment by ShahriarSS** [comment]
@yf225 the code looks good to me but there are 22 CI errors. Just one thing: Can you please move ```nn::Fold```'s constructor to ```.cpp``` to be consistent with the rest of the modules?

**Comment by yf225** [comment]
@ShahriarSS I believe the CI error should be unrelated (I am re-running CI to validate). I also made the changes to `nn::Fold`'s constructor.

**Review by vincentqb — APPROVED** [review]
This looks good to me!

**Pull request closed without merging**
