### PR TITLE
Propagate full autocast state to CheckpointFunction's forward-inside-backward

### LINKED ISSUE #71124: Activation checkpointing breaks bfloat16 AMP
### 🐛 Describe the bug

When bfloat16 AMP is enabled, the backward passes of modules within activation checkpoints run as if float16 AMP is enabled instead. Here's some minimal reproduction code:

```
import torch
from torch.utils.checkpoint import checkpoint

def main():
    class Linear(torch.nn.Module):
        def __init__(self, c_in, c_out):
            super().__init__()
            self.l = torch.nn.Linear(c_in, c_out)

        def forward(self, x):
            out = self.l(x)
            print(f"Output dtype: {out.dtype}")
            return out

    class LinearStack(torch.nn.Module):
        def __init__(self):
            super().__init__()
            self.stack = torch.nn.ModuleList()
            for _ in range(10):
                self.stack.append(Linear(10, 10))

        def forward(self, x):
            for b in self.stack:
                x = checkpoint(b, x)

            return x

    model = LinearStack().cuda()
    x = torch.rand(10, 10, requires_grad=True).cuda()

    with torch.cuda.amp.autocast(dtype=torch.bfloat16):
        y = model(x)
        print("End of forward pass...")
    
    loss = torch.mean(y)
    loss.backward()

if __name__ == '__main__':
    main()
```

Running this yields the following output:
```
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
End of forward pass...
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
```

During the forward pass, the output is of type `torch.bfloat16`, as expected. During the backward pass, the output ends up as a `torch.float16`.

Workarounds would be appreciated.

### Versions

PyTorch version: 1.10.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.9

Python version: 3.7.0 (default, Oct  9 2018, 10:31:47)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.163.1.fi-x86_64-with-centos-7.9.2009-Core
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 470.82.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.5.0
[pip3] torch==1.10.1+cu113
[pip3] torchaudio==0.10.1+cu113
[pip3] torchmetrics==0.6.2
[pip3] torchvision==0.11.2+cu113
[conda] cudatoolkit               11.2.2               he111cf0_8    conda-forge
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] pytorch-lightning         1.5.0                    pypi_0    pypi
[conda] torch                     1.10.1+cu113             pypi_0    pypi
[conda] torchaudio                0.10.1+cu113             pypi_0    pypi
[conda] torchmetrics              0.6.2                    pypi_0    pypi
[conda] torchvision               0.11.2+cu113             pypi_0    pypi

Tagging @jisaacso

### PR DESCRIPTION
**Pull request by mcarilli**
Should fix https://github.com/pytorch/pytorch/issues/71124 (implements https://github.com/pytorch/pytorch/issues/71124#issuecomment-1009436056).

cc @mcarilli @ptrblck

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
lgtm, let's see what @albanD says

**Comment by mcarilli** [comment]
In https://github.com/pytorch/pytorch/issues/71124#issuecomment-1010418773 @gahdritz says:

That fixed the casting issue, but the fix seems to cause a strange warning to appear at the beginning of the backward pass:

```
lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/autocast_mode.py:156: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
CPU Autocast only supports dtype of torch.bfloat16 currently.
  warnings.warn(error_message)
```

I printed out the CPU AMP kwargs, and they're:

```
{'enabled': False, 'dtype': torch.bfloat16, 'cache_enabled': True}
```

I took a look at autocast_mode.py, and I don't understand why the check on line 153 is failing---both sides seem to be `torch.bfloat16`

**Comment by mcarilli** [comment]
@gahdritz Are you manually using CPU autocast at all in your forward pass that calls the checkpoint function?

**Comment by gahdritz** [comment]
No. I enable `torch.cuda.amp.autocast(dtype=torch.bfloat16)`, but I don't touch CPU autocasting.

**Comment by mcarilli** [comment]
Out of curiosity, do you also see any (potentially different) warnings if your autocast dtype in calling code is `torch.half`?

**Comment by gahdritz** [comment]
Yes, same warning.

**Comment by mcarilli** [comment]
Can you try
```
print(self._enabled, self.fast_dtype, self._cache_enabled)
```
[here](https://github.com/pytorch/pytorch/blob/410e91adee19121f2cae76274d735fe441d8f5c7/torch/autocast_mode.py#L188)?

**Comment by gahdritz** [comment]
It prints:

```
False torch.bfloat16 True
```

**Comment by mcarilli** [comment]
Weird, it seems like everything works as expected, aside from the warning itself. Can you post a minimal (synthetic model, synthetic data) repro that triggers the warning?

**Comment by gahdritz** [comment]
I tried ablating stuff from the repro code from the issue (including checkpointing), and it looks like all of that is required to trigger the warning.

**Comment by mcarilli** [comment]
I can't reproduce the warning using a fresh build of the PRed branch `mcarilli:checkpoint_autocast_dtype`. On an A100, https://github.com/pytorch/pytorch/pull/71169#issuecomment-1010531713 runs without warnings, regardless if I set `dtype=torch.bfloat16` or `dtype=torch.float16`.

Maybe you're on an earlier version of Pytorch that has some unrelated bugs in checkpointing or dtype-object comparison.
Can you try either
- building my PRed branch from source
- or (probably easier) applying my diffs to the install path** of a recent pytorch master build

and see if the warnings persist?

**to find the install path:
```
>>> import torch
>>> import sys
>>> sys.modules["torch"]
```
and edit utils/checkpoint.py at the path `sys.modules["torch']` provides. I usually include a random print statement to confirm my later runs actually picked up the changes.

**Comment by gahdritz** [comment]
Your second suggestion is actually what I did---I installed torch 1.10.1+cu113 and then applied the diff.

**Comment by mcarilli** [comment]
Well, I can't reproduce the warning with a source build of the PRed branch :(
I do think it would help to try applying the diffs onto a nightly build, or if you're set up to build from source, try `mcarilli:checkpoint_autocast_dtype` directly.

**Comment by albanD** [comment]
I am not 100% sure why autocast needs to be special cased here (agreed that this PR is not really adding this special case, just making it worse). I would have some clarifying questions about the expected behavior here:

```python

with autocast(bfloat16):
  out = my_fn1(inp)
  loss = checkpoint(my_fn2)(out)

  # Q1: All backward and re-computation should run with autocast bfloat16?
  loss.backward()
  
# Q2: Is that even allowed?
# Q3: Should the backward of `my_fn1` run with autocast enabled or not?
# Q4: Should the recomputation of `my_fn2` due to checkpointing run with autocast enabled or not?
# Q5: Should the backward of `my_fn2` within checkpointing run with autocast enabled or not?
loss.backward()

with autocast(float16):
  # Q6: Is that even allowed?
  # Q7: Should the backward of `my_fn1` run with autocast float16 or bfloat16?
  # Q8: Should the recomputation of `my_fn2` due to checkpointing run with autocast float16 or bfloat16?
  # Q9: Should the backward of `my_fn2` within checkpointing run with autocast float16 or bfloat16?
  loss.backward()
```

And Q10: Which of these use cases is currently broken today? And this PR is aiming to fix?

**Comment by ngimel** [comment]
I'll take a crack at answering those, @mcarilli can correct me as needed
Q1: this is a discouraged usage, however, if someone were to write this it would run under autocast bfloat16, not sure if it should. Should we explicitly error out in this case? Maybe.
Q2: Not only allowed, but this is recommended usage 
Q3, Q5: Backward shouldn't run under autocast manager, backward should rely on casts recorded by autograd to produce correct results
Q4: Recomputation should run under autocast
Q6-Q9: discouraged use, backward should not run under autocast context manager.

**Comment by mcarilli** [comment]
Clarification to Q1 and Q6-9:
Autocast state is thread-local and internally, backward() forks a side thread to run the ops. In other words
```
with autocast(whatever):
    loss.backward()
```
has no effect on what backward() does internally: backward just reverses whatever casts occurred during forward whether or not it appears under the context manager in your script.

If CheckpointFunction.forward detects it ran under autocast, CheckpointFunction.backward internally locally enables autocast for its forward-in-backward. You don't need to run backward() under an autocast context for CheckpointFunction to do this. The point of this PR is to make sure CheckpointFunction.backward's internal local autocast faithfully imitates the autocast state detected in CheckpointFunction.forward.

**Comment by mcarilli** [comment]
Q10: The simple "correct" pattern
```python
with autocast(bfloat16):
    out = my_fn1(inp)
    loss = checkpoint(my_fn2)(out)
loss.backward()
```
is currently broken, because CheckpointFunction.backward's internal autocast for the forward-in-backward just uses the default autocast dtype, which is torch.float16 (when it SHOULD use remember that the forward pass used bfloat16, and use bfloat16 imitate what non-checkpointed code would do).

```python
with autocast(bfloat16):
    out = my_fn1(inp)
    loss = checkpoint(my_fn2)(out)
    loss.backward()
```
would NOT fix this, because like I said, `with autocast(bfloat16)` does not toggle the thread-local dtype on the backward side thread on which CheckpointFunction.backward runs.

**Comment by mcarilli** [comment]
@gahdritz i CAN reproduce the warning by adding my diffs to 1.10.1.
At the site of the warning in torch/autocast_mode.py:
```python
print(self.fast_dtype, supported_dtype[0], self.fast_dtype == supported_dtype[0])
```
yields
```
torch.bfloat16 torch.bfloat16 False (!!!!)
```
So 1.10.1 appears to have unrelated bug comparing against dtype objects returned by `torch.get_autocast_cpu_dtype()`.
Here's a fun mini example (again, with 1.10.1):
```python
>>> torch.get_autocast_cpu_dtype()
torch.bfloat16
>>> torch.get_autocast_cpu_dtype() == torch.bfloat16
False
```
A more recent master build yields the expected result:
```python
>>> torch.get_autocast_cpu_dtype()
torch.bfloat16
>>> torch.get_autocast_cpu_dtype() == torch.bfloat16
True
```

In other words, I think the comparison problem is unrelated to the PR's diffs, fixed now, and the warning on 1.10.1 shouldn't block the PR.

**Comment by gahdritz** [comment]
I was just about to come back to say that the warning does not appear using the nightly build. Looks like this is all squared away.

**Comment by albanD** [comment]
Thanks the for details @mcarilli and @ngimel !

I wanted to avoid discussing the current tls handling as that is what I suspect to be unexpected.
So 6-9 is discouraged but work-ish today I guess. Following Natalia's question: should this be an error?

> Backward shouldn't run under autocast manager, backward should rely on casts recorded by autograd to produce correct results

Makes sense. So I agree that it is good to make this change to make the checkpoint restore this state properly

> backward() forks a side thread

This is not true anymore for cpu work ;) So today I would expect it to be set for CPU work but not for GPU work.
That being said, we are actually propagating TLS during that backward pass that are registered [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/ThreadLocalState.h#L19).

I am wondering:
- Should autocast state be in that TLS state class so that it gets propagated across threads properly (in autograd backward but also c10 worker thread pool IIRC)?
- We could expose getting / setting this TLS state to python and have checkpoint use this to ensure that we are actually propagating things well.


This would be beyond the asks for this PR though and I agree that this PR is a good targeted fix for the issue at hand. So happy to have this landed now if we want a more targetted fix @ngimel

**Comment by mcarilli** [comment]
I considered propagating autocast state to backward TLS, but had some concerns (https://github.com/pytorch/pytorch/issues/71124#issuecomment-1009436056):
- propagating a full-thread state wouldn't account for different functions in forward potentially using different autocast dtypes, which is something the user is allowed to do.
- Right now the API recommendation is to call backward() outside the autocast context so the backward() call wouldn't see an active autocast state to propagate at all.
 
Tbh I don't think propagating autocast state to backward TLS is better than the present fix unless someday we want the backward pass to receive autocasting that's independent and asymmetric from the forward pass.

> Should autocast state be in that TLS state class so that it gets propagated across threads properly (in autograd backward but also c10 worker thread pool IIRC)?

I don't think so, I want autocast to stay thread-local so the user can set autocast state in different python threads flexibly. There are some special cases (like propagating autocast to side threads spawned by DataParallel, which we do explicitly in Python).

> We could expose getting / setting this TLS state to python and have checkpoint use this to ensure that we are actually propagating things well.

I'm not sure what you mean, afaict that's what the autocast context manager and this PR's approach do.

**Comment by albanD** [comment]
What I mean is that if autocast is part of this set of propagated TLS. We can simply make checkpoint, DP, etc propagate that set of TLS of and not worry about it any more :D
It will also solve by side effect things like: saved variable hooks not being respected by DP. Or python mode not being respected by DP, etc

**Pull request closed without merging**
