### PR TITLE
[pt2] improve error logs for torch.cond and aoti package

### PR DESCRIPTION
**Pull request by henrylhtsang**
cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by ydwu4 — APPROVED** [review]

**Review by angelayi — APPROVED** [review]

**Comment by henrylhtsang** [comment]
@pytorch merge -i

**Comment by henrylhtsang** [comment]
@pytorch merge -i

**Pull request closed without merging**
