### PR TITLE
ptype propagation on numpy functions

### LINKED ISSUE #17249: Proposal: Add __tensor_wrap__ method similar to numpy __array_wrap__
## 🚀 Feature
Add the ability to subclass torch.Tensor so that you can use `isinstance(tensor, CustomTensor)` to determine the "context" of the data stored in the subclass object. I think #9515 describes the need for **dtype** promotion logic, but this proposal is for **python type** promotion logic. 

The __array__wrap__ method already exists in numpy and ensures that the following ufunc preserves the custom tensor type:
```python
custom_tensor = CustomTensor(torch.tensor([1, 2, 3, 4])
new_tensor = np.add(custom_tensor, 1.0) -> CustomTensor
new_tensor = np.add(1.0, custom_tensor) -> CustomTensor (Hmmm...)
isinstance(new_tensor, CustomTensor) #  returns True
```

**The __tensor_wrap__ method does not exist**. As a result, the custom type information is easily lost:
custom_tensor = CustomTensor(torch.tensor([1, 2, 3, 4])
new_tensor = custom_tensor.add(1.0) -> Tensor
isinstance(new_tensor, CustomTensor) #  returns False

## Motivation

The torch.Tensor class provides a dynamically typed wrapper of statically typed Torch Classes (FloatTensor, DoubleTensor, HalfTensor, etc) using the numpy dtype. While this should save us from ever wanting to subclass the Tensor class, it would be nice to use the subclass of a Tensor to provide custom methods specific to the context of the data. 

For example: 
```python
class TimeDomainTensor(torch.Tensor)

    def __repr__()
        return 'Time Information:\n' + super(Parameter, self).__repr__()
```
```python
class FrequencyDomainTensor(torch.Tensor)
   
    def __repr__()
        return 'Frequency Information:\n' + super(Parameter, self).__repr__()
```
```python
class SurfaceTensor(torch.Tensor)
   
    def __repr__()
        return 'Surface Information:\n' + super(Parameter, self).__repr__()
```

## Pitch

Custom subclassing is already utilized by the torch.nn.Parameter Class, so most of the heavy lifting is already done. Note that performing a math operation on a Parameter also downcasts the Parameter to a Tensor.

## Alternatives

Numpy provides the following methods for customizing the output behaviour of a ufunc.

1. def __array_wrap__(self, array):
    A subclass can override what happens when executing numpy ufuncs **after** the ufunc is called.

2. def __array_ufunc__(ufunc, method, *inputs, **kwargs):
    A subclass can override what happens when executing numpy ufuncs **before and after** the ufunc is called. New in version 1.13.
 
3. def __array_finalize__(self, obj): 
    The ability to insert any kind of custom attributes, events, io, etc.  This may not work on GPU because this would open up the ability to define highly customized data containers.
        a. explicit constructor call (obj = MySubClass(params)).
        b. View casting
        c. Creating new from template

4. Do Nothing:
   Revert to functional implementation. Simply replace all custom_tensor.method(*args, **kwargs) with method(custom_tensor, *args, **kwargs).

The __array_wrap__ method is sufficient for this problem because we want to cast the tensor **after** the function has been performed. The __array_ufunc__ would also work but could result in compatibility  problems with older versions of numpy. The __array_finalize method may add too much customization that could create a wide range of gotchas and incompatibility between CPU and GPU.

## Example

Sample code that partially works for add(custom_tensor, other):

```python
from collections import OrderedDict
import torch as th


def _rebuild_custom_tensor(data, requires_grad, backward_hooks):
    param = CustomTensor(data, requires_grad)
    # NB: This line exists only for backwards compatibility; the
    # general expectation is that backward_hooks is an empty
    # OrderedDict.  See Note [Don't serialize hooks]
    param._backward_hooks = backward_hooks

    return param

class CustomTensor(th.Tensor):
    r"""A kind of Tensor that has time, freq as its inner-most dimensions.

    Arguments:
        data (Tensor): parameter tensor.
        requires_grad (bool, optional): if the parameter requires gradient. See
            :ref:`excluding-subgraphs` for more details. Default: `True`
    """

    def __new__(cls, data=None, requires_grad=False):
        if data is None:
            data = th.Tensor()
        return th.Tensor._make_subclass(cls, data, requires_grad)

    def __deepcopy__(self, memo):
        if id(self) in memo:
            return memo[id(self)]
        else:
            result = type(self)(self.data.clone(), self.requires_grad)
            memo[id(self)] = result
            return result

    def __repr__(self):
        return 'Custom Message:\n' + super(CustomTensor, self).__repr__()

    def __reduce_ex__(self, proto):
        # See Note [Don't serialize hooks]
        return (
            _rebuild_custom_tensor,
            (self.data, self.requires_grad, OrderedDict())
        )

    def add(self, value):
        tensor = super().add(value)
        return self.__tensor_wrap__(tensor)

    def __add__(self, other):
        tensor = super().__add__(other)
        return self.__tensor_wrap__(tensor)

    # Wrap Numpy array again in a suitable tensor when done, to support e.g.
    # `numpy.sin(tensor) -> tensor` or `numpy.greater(tensor, 0) -> ByteTensor`
    def __array_wrap__(self, array):
        if array.dtype == bool:
            # Workaround, torch has no built-in bool tensor
            array = array.astype('uint8')
            return th.from_numpy(array)
        else:
            return th.Tensor._make_subclass(CustomTensor, th.from_numpy(array), self.requires_grad)

    # Same as __array_wrap__ but for Tensors
    def __tensor_wrap__(self, tensor):
        return th.Tensor._make_subclass(CustomTensor, tensor, self.requires_grad)
```

Sample Results:
```python
import torch
from custom import CustomTensor
x = torch.tensor([1.0, 2.0, 3.0], dtype=torch.double)
custom_x = CustomTensor(x)
custom_x + 1   # -> CustomTensor
1 + custom_x   # -> **Tensor** :(
torch.add(1, custom_tensor) -> **Tensor** :(
torch.add(custom_tensor, 1) -> **Tensor** :(
```

## Conclusions
The above example demonstrates how numpy goes beyond binary operator overloading to ensure that all operations return the highest derived subclass of the ndarray. This is not how pytorch is organized. I think #9515 describes the need for dtype promotion logic, but this proposal is for python type promotion logic.

### PR DESCRIPTION
**Pull request by dylanbespalko**
Fixes issue #17249

Added support for python subclass (ptype) propagation when calling numpy functions on Tensors (Parameters are unaffected).

I have addressed and responded to the comments on the previous PR. #18610. Please visit this link to see that issues that were resolved. As suggested the changes have been broken in to two PR:

1. ptype propagation on torch functions. #22235
2. **ptype propagation on numpy functions.**

A simple python script demonstrating ptype propagation is as follows:
```python
import sys
import pickle
import copy
import unittest
from collections import OrderedDict

import numpy as np
from numpy.testing import *

import torch
import torch.multiprocessing as mp


def _rebuild_subclass(type_, data, requires_grad, backward_hooks):
    param = type_(data, requires_grad)
    # NB: This line exists only for backwards compatibility; the
    # general expectation is that backward_hooks is an empty
    # OrderedDict.  See Note [Don't serialize hooks]
    param._backward_hooks = backward_hooks

    return param


class TensorSubclass(torch.Tensor):

    def __new__(cls, data=None, requires_grad=False):
        if data is None:
            data = torch.Tensor()
        self = torch.Tensor._make_subclass(cls, data, requires_grad)
        return self

    def __deepcopy__(self, memo):
        if id(self) in memo:
            return memo[id(self)]
        else:
            result = type(self)(self.data.clone(), self.requires_grad)
            memo[id(self)] = result
            return result

    def __reduce_ex__(self, proto):
        # See Note [Don't serialize hooks]
        return _rebuild_subclass, (self.__class__, self.data, self.requires_grad, OrderedDict())


class A(TensorSubclass):
    pass


class B(TensorSubclass):
    pass


class C(A, B):
    pass


if __name__ == '__main__':
    a_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.double, requires_grad=True)
    b_tensor = torch.tensor([4.0, 5.0, 6.0], dtype=torch.double, requires_grad=True)
    c_tensor = torch.tensor([7.0, 8.0, 9.0], dtype=torch.double, requires_grad=True)
    d_tensor = torch.ones((4, 3, 2), dtype=torch.double, requires_grad=True)
    a = A(a_tensor, requires_grad=True)
    b = B(b_tensor, requires_grad=True)
    c = C(c_tensor, requires_grad=True)
    d = C(d_tensor, requires_grad=True)

    print("Numpy ptype propagation")
    print(type(np.add(a, b)))
    print(np.add(a, b).requires_grad)
    print(type(np.add(a, c)))
    print(np.add(a, c).requires_grad)

    print("Numpy ptype propagation, out_args")
    print(type(np.add(a, b, out=a)))
    print(np.add(a, b, out=a).requires_grad)
    print(type(np.add(a, c, out=a)))
    print(np.add(a, c, out=a).requires_grad)
```

### CODE REVIEW

**Comment by dylanbespalko** [comment]
Looks like some builds failed (likely Python 2 compatibility issues). I'll get this fixed and submit another PR.

**Comment by colesbury** [comment]
I am not convinced that this is an API behavior that we should commit to supporting. I'm also concerned about the performance implications of  THPVariable_result_ptype

**Comment by ezyang** [comment]
> I am not convinced that this is an API behavior that we should commit to supporting

The actual diff here is a little confused, because it's mixed up with changes from #22235 which I definitely agree need some discussion about what exactly we want to support.

However, the goal of this patch is just to make it so that you can pass a PyTorch tensor straight to numpy operations, and get out (non-backwards-supporting) PyTorch tensors at the end. This seems like a pretty harmless affordance that end users might like. Do you have an objection to this bit?

**Comment by ezyang** [comment]
@dylanbespalko I'm not sure I can properly review this PR if it also contains changes from #22235. Can these two PRs be setup so that they don't have any dependency on each other?

**Comment by rgommers** [comment]
Hi, NumPy maintainer here. Interesting PR, thanks for the ping @ezyang. I'll just make some high-level comments for now:

> the goal of this patch is just to make it so that you can pass a PyTorch tensor straight to numpy operations, and get out (non-backwards-supporting) PyTorch tensors at the end. This seems like a pretty harmless affordance that end users might like.

A variation of this works for ufuncs with `__numpy_ufunc__` (new in numpy 1.13), and for other numpy functions with `__array_function__` (new in numpy 1.17). CuPy and Dask already support both, it would be nice indeed for PyTorch to support these protocols too. However, I don't think that this PR provides the full answer. In general there are some behavior differences and API mismatches between NumPy and PyTorch, and this PR doesn't really deal with that. So things will only work for matching function names and parameters/keywords for now. It would be useful to document explicitly what is expected to work and what isn't.

More importantly, the logic in this PR seems exactly reversed from what it should be. This PR does something like:
1. Create `ndarray` instance out of `Tensor` instance.
2. Call numpy `ufunc` with that `ndarray`
3. Transform the result back into `Tensor` (or a `Tensor` subclass)

It should be:
1. Pass `Tensor` instance to numpy `ufunc`
2. numpy detects the presence of `Tensor.__array_ufunc__` and delegates execution to it.
3. The `Tensor.__array_ufunc__` implementation then should forward that function call to the right implementation (`torch.sum` or `Tensor.sum`).

The whole idea of the NumPy array protocols here is to allow using the NumPy API with minimal overhead, so users can write generic functions with only numpy calls in them, and those then work for `ndarray`s as well as for other array-like objects like `torch.Tensor`. There is not supposed to be any coercion to/from ndarrays (that's very expensive).

**Comment by dylanbespalko** [comment]
@rgommers, @ezyang,

Thanks for your much needed perspective on Numpy architecture. I think `__numpy_ufunc__` was renamed to `__array_ufunc__` when released in v1.13. As for `__array_function__`, I had not heard of this one and I've been reading [NEP 18](https://www.numpy.org/neps/nep-0018-array-function-protocol.html). It looks like a proposal for super-universal functions that perform cross-compatible operations on the following type:
- gpu arrays (CuPy),
- scipy.sparse, pydata/sparse
-  and parallel arrays (Dask array)
- numpy
- tensors TensorFlow  and PyTorch.

I'm someone who is more likely to apply this stuff, rather than design it. My original goal here was to create two functions:
1. `__tensor_ufunc__` to perform **torch universal functions** on tensors.
2. `__array_ufunc__` to perform **numpy universal functions** on tensors (by converting inputs to ndarray and outputs back to tensor).

Since these types are not related by inheritance, neither solution is indeed "universal" in that:
1. torch.Tensor + np.NDArray will call torch.add
2. np.NDArray + torch.Tensor will call numpy.add

`__array_function__` looks like it would handle this case by maintaining a mapping between torch functions and numpy functions so that you could "redirect" all function calls to torch or numpy. This is well beyond my abilities as it requires:
    1. A mapping between numpy and torch function names.
**2. A mapping between numpy and torch function arguments.**

The latter problem was the bottleneck for me. I decided that I needed to maintain a 90/10 torch/numpy mix in my own code, because it is impossible to deal with compatibility issues on a daily basis. I'm sure that the age of distributed hardware will make these decisions very tough, so any compatibility between these frameworks would be highly appreciated.

**Comment by rgommers** [comment]
> Thanks for your much needed perspective on Numpy architecture. I think __numpy_ufunc__ was renamed to __array_ufunc__ when released in v1.13.

yes indeed. that was a typo, I've edited by comment.


>  `__tensor_ufunc__` to perform torch universal functions on tensors.

The question this raises is why you need a protocol for that. The `__array_ufunc__` is needed for things that are *not* ndarrays (we call them "duck arrays" for now, as in ducktyping arrays). So I'd expect `__tensor_ufunc__` to be for things that are not `Tensor`s or `Tensor` subclasses. I.e. using the PyTorch API but dispatching to outside `torch` (is there a need for that?).

>  `__array_ufunc__` to perform numpy universal functions on tensors (by converting inputs to ndarray and outputs back to tensor).

Okay then I understood your PR right. I think it's just not something that you should want - there's likely a better solution. 

> Since these types are not related by inheritance, neither solution is indeed "universal" in that:
>
>    torch.Tensor + np.NDArray will call torch.add
>    np.NDArray + torch.Tensor will call numpy.add

Mixing types of arrays/tensors like that is going to be inherently messy and inefficient. You're probably better off converting explicitly.

**Comment by ezyang** [comment]
> There is not supposed to be any coercion to/from ndarrays (that's very expensive).

Just a quick clarification: an ndarray can be converted into a Tensor without necessitating a data copy. So it's not as expensive as you seem to imply here.

**Comment by rgommers** [comment]
> Just a quick clarification: an ndarray can be converted into a Tensor without necessitating a data copy. So it's not as expensive as you seem to imply here.

I was thinking mainly about tensors that live on the GPU. The `__array_ufunc__` protocol as intended should work for those too without data copies, and they're probably the more interesting use case (cause the performance benefits are larger).

but yes, point taken: should have said "potentially expensive"

**Comment by t-vi** [comment]
I'm late to the party, but isn't the method @perone explores in http://blog.christianperone.com/2019/07/numpy-dispatcher-when-numpy-becomes-a-protocol-for-an-ecosystem/ a way good to implement many of the functions without needing much from PyTorch?

**Comment by rgommers** [comment]
@t-vi indeed, and that's discussed in gh-22402 as you already discovered.

**Pull request closed without merging**
