### PR TITLE
Add ATen usable from CSRC

### PR DESCRIPTION
**Pull request by zdevito**
This pull-request uses git subtree to add ATen into PyTorch, and then modifies PyTorch so that ATen and PyTorch will use the same THCState, and adds support for ATen objects to Dynamic Types.  Later modifications will remove THPP from modules and replace with ATen.

### CODE REVIEW

**Comment by soumith** [comment]
quick nit in terminology before someone is confused: this PR uses `git subtree`, not a `git submodule`

**Comment by colesbury** [comment]
This looks good. Can you fix the lint errors from the travis-ci build?

https://travis-ci.org/pytorch/pytorch/jobs/251877269

**Comment by colesbury** [comment]
If you want the tests to run in the contbuild, you can add them to `test/run_test.sh`

**Comment by zdevito** [comment]
closing/reopening to rerun tests.

**Comment by zdevito** [comment]
Reopen..

**Comment by zdevito** [comment]
This is ready to go, assuming the py2.7-osx-cpu build failure is spurious. I can't get something similar to happen on my mac.

**Comment by soumith** [comment]
this is now merged into master.

**Pull request closed without merging**
