### PR TITLE
Enable stateless XNNPACK linear.

### PR DESCRIPTION
**Pull request by AshkanAliabadi**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #36202 Enable torch_speed_benchmark to accept different memory formats.
* **#35791 Enable stateless XNNPACK linear.**
* #35790 Enable stateless XNNPACK convolutions.
* #36032 Mobile CPU allocator.

Optimal usage of the linear operator would require weight prepacking. If we have done our job properly, JIT must have caught and replaced linear operations on mobile with their corresponding prepacked versions, hence enabling said optimal usage.  Still, if we somehow end up in at::native::linear for whatever reason, it is still more efficient to go through XNNPACK than the alternatives of at::addmm and at::matmul.

Differential Revision: [D20821863](https://our.internmc.facebook.com/intern/diff/D20821863)

### CODE REVIEW

**Comment by dreiss** [comment]
Need to see a test plan for this.  Are we sure this is a win on desktop/server mkldnn is available?

**Comment by AshkanAliabadi** [comment]
@dreiss Thanks, will limit to mobile only.  Test test plan would be passing the CI but the thing is that this would not get much mobile coverage after I limit it to mobile only.  How do you suggest I go about testing it more thoroughly?

**Comment by dreiss** [comment]
As long as it's gated to mobile-only, maybe running a convolutional model on the speed benchmark and verifying that it's faster?

**Review by kimishpatel — APPROVED** [review]
LGTM.

**Review by dreiss — APPROVED** [review]

**Pull request closed without merging**
