### PR TITLE
Disable test_inductor_timm_shard

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #87710

Summary: tests are flaky. Need more time for investigation.

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]

**Review by malfet — CHANGES_REQUESTED** [review]
You can keep that logic in place, but need to remove the shards from inductor.yaml, otherwise it will run some other tests in those shards

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
