### PR TITLE
Added ATen exported targets for consuming projects

### PR DESCRIPTION
**Pull request by willyd**
I added basic support for exported targets to make it easier for consuming projects to link to ATen. This is especially useful on Windows since both Release and Debug will work with the same install tree.

We may want to use `target_link_libraries(ATen PRIVATE ...)` with some dependencies but this is a start to make ATenConfig.cmake more complete.

### CODE REVIEW

**Comment by willyd** [comment]
I fixed the build error. This was caused by the THD_deps.txt file getting the name of the ATen target instead of the path to the library itself. Should be fixed now.

**Comment by ezyang** [comment]
@lantiga Is this PR still relevant?

**Comment by lantiga** [comment]
I think so, e.g. we can use this to load the aten cmake vars in the libtorch build instead of guessing.
Right now we just assume standard *nix install locations, which means that libtorch won’t build on Windows.

**Comment by willyd** [comment]
Sorry I did not notice that the CI builds were failing. I rebased on master once more and I believe I fixed all the issues the previous commits had.

**Comment by willyd** [comment]
@ezyang I believe the CI builds should pass with the latest commit.

**Pull request closed without merging**
