### PR TITLE
Modified lstsq_helper to accept rank and singular_values

### PR DESCRIPTION
**Pull request by IvanYashchuk**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #54725 Added cuBLAS path for torch.linalg.lstsq
* #54724 Replaced _lstsq_helper with internal dispatch
* #54723 Updated linalg.lstsq with NumPy compatible kwarg rcond
* #54722 Modified batched residuals return of torch.linalg.lstsq
* #54721 Added out= variant for torch.linalg.lstsq
* #54720 Modified lstsq_helper to accept lapack error codes tensor
* **#54719 Modified lstsq_helper to accept rank and singular_values**

lstsq_helper now takes rank and singular_values that are modified in-place.
This is required for adding out= variant.

Differential Revision: [D27439197](https://our.internmc.facebook.com/intern/diff/D27439197)

### CODE REVIEW

**Comment by IvanYashchuk** [comment]
@heitorschueroff could you also take a look at this stack of PRs if you're available?

It adds out= variant support, renames one keyword argument to be NumPy compatible, bring `infos` tensor closer to ATen frontend so that it's easier in the future to add a variant without error checks and adds cuBLAS path.

**Comment by mruberry** [comment]
I'm incline to just stamp this in but it looks like the build failures are real.

Is the plan to eventually hide the helper from users by removing it from native_functions.yaml?

**Comment by IvanYashchuk** [comment]
I decided to try splitting out modifications to torch.linalg.lstsq into multiple PRs with gradual changes that are potentially easier to review.

> Is the plan to eventually hide the helper from users by removing it from native_functions.yaml?

Yes, the helper is removed in https://github.com/pytorch/pytorch/pull/54724.

I'm fixing the build failures, I'll ping you once CI is green.

**Comment by mruberry** [comment]
Is this ready to be merged, @IvanYashchuk?

**Comment by IvanYashchuk** [comment]
@mruberry, yes. The whole stack except the last PR "#54725 Added cuBLAS path for torch.linalg.lstsq" is ready for review and merge.

**Review by mruberry — APPROVED** [review]
LGTM!

**Pull request closed without merging**
