### PR TITLE
Enable output allocation cache

### PR DESCRIPTION
**Pull request by jjsjann123**
Cherry-picked from devel branch: https://github.com/csarofeen/pytorch/pull/2010

turns on accidentally disabled output allocation cache [#2002](https://github.com/csarofeen/pytorch/issues/2002)
Updated check for safety regarding allocation cache by iterating all IterDomain on outputs and enables cache re-use only when no extent value is a consumer of fusion inputs (output sizes is not dependent on scalar inputs).

### CODE REVIEW

**Comment by jjsjann123** [comment]
There's an XLA failure with this PR. Which doesn't seem to be remotely related..

I thought I used a viable/strict tag on this one. Shouldn't that have cleared all tests cleared, or is it just a flaky run?
I'm re-running the test :crossed_fingers: . Will try a master bump if that doesn't fix it.

**Comment by jjsjann123** [comment]
merged the revert that should handle vmap unexpected success. hunting for a legit master. :eyes:

**Comment by davidberard98** [comment]
@jjsjann123 have you seen https://hud.pytorch.org/? could be helpful in identifying a good base revision

**Comment by jjsjann123** [comment]
> @jjsjann123 have you seen https://hud.pytorch.org/? could be helpful in identifying a good base revision

Looks like I'm just one commit away from the promised land. Thx for pointing me to that.

**Comment by jjsjann123** [comment]
Hahaha, CI passed now CLA is red. :expressionless:

**Comment by jjsjann123** [comment]
cc'ing @ptrblck for CLA.

**Comment by jjsjann123** [comment]
bumping threads since CLA is addressed now.

**Comment by jjsjann123** [comment]
Looks like another flaky test.
```


Mismatched elements: 1 / 392 (0.3%)
Greatest absolute difference: 1.52587890625e-05 at index (0, 4, 4, 4) (up to 1e-05 allowed)
Greatest relative difference: 4.917992475471512e-05 at index (0, 4, 4, 4) (up to 1.3e-06 allowed)
```

Will rerun after it finishes

**Comment by jjsjann123** [comment]
Can I get a stamp here? @csarofeen

**Review by csarofeen — APPROVED** [review]
LGTM, cherry pick from already reviewed PR.

**Comment by jjsjann123** [comment]
re-running the failed job. Log was complaining about driver issue on the ci runner.

**Pull request closed without merging**
