### PR TITLE
Fix test_extension_backend on non-AVX systems

### PR DESCRIPTION
**Pull request by Flamefire**
The test checks for a substring "loadu" in generated code. On AVX systems that line is:
> auto tmp0 = at::vec::Vectorized<float>::loadu(in_ptr0 + static_cast<long>(i0))
however on non-AVX systems it is
> auto tmp0 = in_ptr0[static_cast<long>(i0)];

the difference depends on `codecache.valid_vec_isa_list()` being non-empty. See torch/_inductor/codegen/cpp.py:2639

Modify the test to account for that.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by colesbury** [comment]
@EikanWang would you please review this PR?

**Review by jgong5 — APPROVED** [review]

**Comment by Flamefire** [comment]
@jgong5 I rebased this to fix the conflict but needs a new approval

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
