### PR TITLE
[testing] update supported dtypes test to run once per op (to improve test running time)

### PR DESCRIPTION
**Pull request by kshitij12345**
Test timings:

Existing around 20 mins
```
pytest test/test_ops.py -k test_supported_dtypes
================================================== 4989 passed, 2481 skipped, 20794 deselected, 17 warnings in 1277.39s (0:21:17) ==================================================
```

New around 2 mins
```
pytest test/test_ops.py -k _device_only_su
============================================== 5 failed, 555 passed, 295 skipped, 27409 deselected, 11 warnings in 149.26s (0:02:29) ===============================================
```

NOTE: Failing tests are the ones which are skipped by `test_supported_dtypes`. (Was lazy to update them)

@mruberry 
Want to know what you think of this?

Also if we don't like the idea of this dummy `allowed_dtypes` (which I don't), then we can update the test infra to support `test(self, device, op)` this new signature. But this might require more significant changes in `common_device_type`.

If you think this approach is ok, then we can work on actually improving the message when test fails, so that user knows all the dtypes that are failing. (We can also integrate the OpInfoHelper tool here since it fetches all supported dtypes for given device type)

### CODE REVIEW

**Comment by mruberry** [comment]
This is super interesting.

First, what's going on with the performance difference? 

Second, support tests like this is a good thing to do, but it's lame we have to hack a dtype. Maybe we should update the test generator with a new decorator, `@opsNoDtypes`, that doesn't instantiate a test per dtype?

**Comment by kshitij12345** [comment]
> First, what's going on with the performance difference?

I am not sure, but maybe related to setup and tearing of the tests. Will need to investigate more.

> Second, support tests like this is a good thing to do, but it's lame we have to hack a dtype. Maybe we should update the test generator with a new decorator, @opsNoDtypes, that doesn't instantiate a test per dtype?

Agreed. This is totally hacky! But wanted to confirm that this made sense before making changes to `common_device_type`.
@opsNoDtypes sounds good.

Thanks!!

**Comment by mruberry** [comment]
> > First, what's going on with the performance difference?
> 
> I am not sure, but maybe related to setup and tearing of the tests. Will need to investigate more.
> 

That could be; it's probably worth investigating a little more. It's important we understand the performance trade-off of more vs. fewer tests. We're currently generating a lot of tests!

> > Second, support tests like this is a good thing to do, but it's lame we have to hack a dtype. Maybe we should update the test generator with a new decorator, @opsNoDtypes, that doesn't instantiate a test per dtype?
> 
> Agreed. This is totally hacky! But wanted to confirm that this made sense before making changes to `common_device_type`.
> @opsNoDtypes sounds good.
> 
> Thanks!!

Cool!

**Comment by kshitij12345** [comment]
@mruberry 

Profile Analysis

**Conclusion** : More test -> More `CudaMemoryLeakCheck` -> More gc.collect -> More time

Possible Options:
1. We should work on reducing the number of tests if to mitigate the time spent on leak check (like we are planning to do here).
2. Have an independent test suite to do the leak check (which doesn't grow in test size when new OpInfo are added).

(Did not expect gc.collect to be culprit 🤯)

It turns out that `gc.collect` is the main culprit for slow-down. It is used in `CudaMemoryLeakCheck`
https://github.com/pytorch/pytorch/blob/8845cbabf0e7e5bfa3857c5c5bdfe5dcc02fe9de/torch/testing/_internal/common_utils.py#L756

`test_supported_dtypes` spends staggering `1548.975s out of 1568.361s` in gc.collect (output from prof files below)
while the new `test_device_only_supported_dtypes` spends `160.204s out of 167.830s`.

[multiple_test_prof_out.txt](https://github.com/pytorch/pytorch/files/6626775/multiple_test_prof_out.txt)
[single_test_prof_out.txt](https://github.com/pytorch/pytorch/files/6626776/single_test_prof_out.txt)

To verify that `gc.collect` and `CudaMemoryLeakCheck` are the culprit, I tried the following patch.
```patch
diff --git a/test/test_ops.py b/test/test_ops.py
index ecec417017..d5fbc8685b 100644
--- a/test/test_ops.py
+++ b/test/test_ops.py
@@ -1,3 +1,6 @@
+import gc
+gc.disable()
+
 from functools import partial, wraps
 import warnings
 
diff --git a/torch/testing/_internal/common_device_type.py b/torch/testing/_internal/common_device_type.py
index 73b6b59a4e..8c3b236490 100644
--- a/torch/testing/_internal/common_device_type.py
+++ b/torch/testing/_internal/common_device_type.py
@@ -366,7 +366,7 @@ class MetaTestBase(DeviceTypeTestBase):
 
 class CUDATestBase(DeviceTypeTestBase):
     device_type = 'cuda'
-    _do_cuda_memory_leak_check = True
+    _do_cuda_memory_leak_check = False
     _do_cuda_non_default_stream = True
     primary_device: ClassVar[str]
     cudnn_version: ClassVar[Any]
```

With this, the total test time for both approaches drop drastically. But the `device_only_supported_dtypes` test (variant with lower number of test takes almost half the time) (check the prof outputs below)

[multiple_test_leak_check_disabled_prof_out.txt](https://github.com/pytorch/pytorch/files/6626782/multiple_test_leak_check_disabled_prof_out.txt)
[single_test_leak_check_disabled_prof_out.txt](https://github.com/pytorch/pytorch/files/6626783/single_test_leak_check_disabled_prof_out.txt)

**Comment by mruberry** [comment]
This is incredibly interesting. fyi @walterddr 

If we stopped performing the CUDA memory leak check (and the garbage collection before it), how much would e2e CI time decline? Like, if we submit a PR just disabling that check after each test, how much faster are pytorch_linux_bionic_cuda10_2_cudnn7_py3_9_gcc7_test1, pytorch_linux_bionic_cuda10_2_cudnn7_py3_9_gcc7_test2, pytorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_test1 and pytorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_test2?

**Comment by walterddr** [comment]
very interesting idea. I guess several interesting issue that I can think of --> 

1. I think we added the early terminate if cuda device failure occurred in https://github.com/pytorch/pytorch/pull/52126. wasn't sure if checking cuda memory leak is still "that important"
2. i am not 100% sure the exact intention as why we do `_do_cuda_memory_leak_check` for each test cases within each TestCase class. if we do we might be able to relax the constrain to - say per TestCase class. that should have the same effect as what @kshitij12345 is doing

**Comment by kshitij12345** [comment]
Just to confirm, @walterddr you are checking the e2e time change in CI after the update right? Otherwise, I'll do it :) Thanks!

**Comment by walterddr** [comment]
btw I created #59804 and #59805

**Comment by mruberry** [comment]
> btw I created #59804 and #59805 and #59808 for testing.
> 
> Based on some of the preliminary results test time was reduced on all cases. (eyeballed around 20-30% based on last several master runs)
> 
> * #59804 obviously shown we can't just disable gc.collect() as expected.
> * #59805 should be the most accurate because it still honors per-test-method mem leak check
> * #59808 is my initial attempt to at least do a per TestCase class method setup/teardown mem leak check but seems like still need some fine-tuning.
> 
> Reasonable next step:
> 
> 1. collect more concrete stats: I am going make sure to use fail-at-end option and let all tests ran pass before failing the CI job to collect a more accurate improvement in CI time on these cases
> 2. i still think we should at least do a per TestCase class level mem leak check --> it doesn't take too long, and if there's mem leak detected, we could alwasy reenable the per-method flag to dig deeper into exactly which test method causes the mem leak.
> 
> Thoughts @kshitij12345 @mruberry ?

This is extremely interesting!

Would you submit a PR disabling the collect and the memory leak check so we can see the CI pass (would it pass?) and what effect it has on the time?

Why did test_graph_cudnn_dropout fail on PR #59805?

Ultimately I agree that per test case with an optional to enable per test sounds ideal. If the time difference from disabling the garbage collection and memory leak check is significant we may want to disable it pre-emptively while we develop that feature.

**Comment by walterddr** [comment]
> 
> This is extremely interesting!
> 
> Would you submit a PR disabling the collect and the memory leak check so we can see the CI pass (would it pass?) and what effect it has on the time?

Created #59942 to verify that. I suspect there might be some issue, let's see the CI results.
> 
> Why did test_graph_cudnn_dropout fail on PR #59805?

I dunno if the error message reports the correct test that fails leak check since we are only doing it "on-demand". (also i cant repro on dev). Will try to dig deeper. 

> 
> Ultimately I agree that per test case with an optional to enable per test sounds ideal. If the time difference from disabling the garbage collection and memory leak check is significant we may want to disable it pre-emptively while we develop that feature.

+1. If CI passes, we can always ONLY enable mem leak check on say "slow_test" CI on master. and disable it on PRs. what do you think?

**Comment by ngimel** [comment]
>CC @malfet @ngimel: how often does cuda mem leak check catches PR issues? can we disable it and/or move it to master?
These days pretty rarely, it was more important in THC. We cannot disable it, but we can move it to master (and it still should report the exact test that failed, not TestCase)

**Comment by kshitij12345** [comment]
Closing in favour of https://github.com/pytorch/pytorch/pull/60157

**Pull request closed without merging**
