### PR TITLE
[C++ API] Add OptimizerBase::add_parameters

### PR DESCRIPTION
**Pull request by goldsborough**
@ebetica asked for a way to add parameters to `Optimizer`s after they are created.

@ebetica @ezyang

### CODE REVIEW

**Review by ebetica — APPROVED** [review]
Note: one minor issue is that if any of the optimizers does significant work in its constructor, this might not work. Thus, add_parameters should definitely be virtual (and one of them should call the other so we don't have to implement two different add_parameter functions).

**Comment by goldsborough** [comment]
I think making them virtual makes sense. To make one call the other, I'll have to update `Cursor` to have a method that yields a new vector with only the values, since currently a cursor is effectively a `vector<pair<string, tensor>>` which does't cooperate well with the tensor-only method. Should be a quick addition

**Comment by apaszke** [comment]
FWIW this is not supported by the Python API (we do have `add_param_group`)

**Comment by ezyang** [comment]
@apaszke Are you saying that the Python API should have this functionality, or that the C++ API shouldn't? ;)

**Comment by goldsborough** [comment]
I didn't implement the whole parameter grouping functionality to begin with. It wasn't in autogradpp, and it seemed the better decision to start with only one parameter group than to have the added complexity of multiple parameter groups. Also, it can always be replicated with multiple optimizers right? TF doesn't have this parameter grouping behavior in their optimizers for example

**Comment by apaszke** [comment]
@ezyang I'm saying that they're inconsistent :)

Yeah, multiple optimizers give you the same results, they're just more annoying to maintain. I guess it's ok to leave it like that for now.

**Comment by ebetica** [comment]
@apaszke I guess the core issue is that state_dict() and load_state_dict() are not present. Implement those would make me happy too. Just any way to load an optimizier's state.

**Pull request closed without merging**
