### PR TITLE
Delete denseTypeIdWithDefault and toDense

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #53973 Add some trivial meta functions for commonly used inplace operations
* #54127 Fix inaccurate dispatch tables
* #54079 Add Tensor::is_cpu, genericize TensorIterator
* #54034 Refactor tensor_new.cpp to use TensorOptions instead of DispatchKey
* #54126 Fix bug in assertRaises NotImplemented handling when no exception is thrown
* **#54016 Delete denseTypeIdWithDefault and toDense**

I managed to convince myself that typeIdWithDefault was sufficient for
the sparse constructor case.  Here is the reasoning.

The surface reading of the use site of denseTypeIdWithDefault is
to convert what could be a sparse dispatch key into the dense version
so we can properly allocate underlying dense tensors for the sparse
constructor call.  But WHERE does this dispatch key come from?
Inspection of call sites reveals that dispatch key is provided by
torch::tensors::get_default_dispatch_key().  This key is NEVER
sparse, as that would correspond to setting sparse tensors to be
the default tensor via torch.set_default_tensor_type() (which is
forbidden, and even if it worked most of everything in PyTorch would
break).  That means that typeIdWithDefault is a sufficient replacmenet.

With denseTypeIdWithDefault removed, we can also delete toDense
as this was the sole use of that function.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D27109511](https://our.internmc.facebook.com/intern/diff/D27109511)

### CODE REVIEW

**Comment by ezyang** [comment]
cc @gchanan

**Review by ailzhang — APPROVED** [review]
Nice!

**Review by bhosmer — APPROVED** [review]
Would it be worth adding an assertion that the passed `dispatch_key` isn't sparse? It seems as though the code must have been written with that possibility in mind, so would be nice to fail fast in that case.

**Comment by ezyang** [comment]
@bhosmer Due to some diffs stacked on top this is a little difficult to do in this PR directly; I will add the asserts in #54034

**Pull request closed without merging**
