### PR TITLE
Fix all pep8 lint

### LINKED ISSUE #3: PEP8
I have an unhealthy obsession with PEP8... Could `viewAs`, `expandAs` be renamed to `view_as`, `expand_as`, etc.?

I might even volunteer to make everything pass flake8 if you guys are okay with accepting a PR that does that.

### PR DESCRIPTION
**Pull request by lukeyeager**
*Close https://github.com/pytorch/pytorch/pull/3*

This is a follow-up to https://github.com/pytorch/pytorch/pull/575. This is that terrifying diff I was talking about.

To reduce the terror, I've split this up into several commits:

1. Fix most lint automatically with autopep8 (as I did with https://github.com/NVIDIA/DIGITS/pull/1207)
2. Manually fix all the lint with an obvious fix
3. Manually fix lint in the docstrings that could potentially break the auto-generated documentation
    - I think I got it right, but I'd like for someone who understand the documentation generation tool to have a look

### CODE REVIEW

**Comment by lukeyeager** [comment]
I'd like to wait for https://github.com/pytorch/pytorch/pull/614 before merging this.

**Comment by apaszke** [comment]
Can you rebase the PR to have the new travis config?

**Comment by desimone** [comment]
Big fan of pep8'ing things. The less mental space assigned to formatting -- whatever defaults are chosen -- the better in my opinion.

That said,  since this is probably as good of a time as any to ask, why 120 vs 79 for column limit?

**Comment by apaszke** [comment]
I could never understand why is it 79, not 80...

**Comment by lukeyeager** [comment]
> why 120 vs 79 for column limit?

I like the GitHub rule: GitHub has a max line length of ~120 when displaying diffs.

Happy to change to whichever value the @pytorch folks like.

**Comment by soumith** [comment]
let's not discuss 120 vs 79 anymore :D 
120 sounds fine, thanks.

**Comment by apaszke** [comment]
@lukeyeager I've pushed a fix for a flaky Sqrt test and it's conflicting with your changes now. Can you reabse them once more please?

**Comment by lukeyeager** [comment]
Rebased. I discarded my conflicting changes, took yours, then ran autopep8 on top of them again.

**Comment by apaszke** [comment]
Thanks!

**Comment by apaszke** [comment]
@lukeyeager Does the config have to be in `setup.cfg`? It's annoying because it creates a terminal autocomplete conflict with `setup.py` and that's used a lot.

**Comment by lukeyeager** [comment]
I know, it bugs me too. Here are the [other options](http://pep8.readthedocs.io/en/release-1.7.x/intro.html#configuration):

* `./tox.ini`
* `./.pep8` (deprecated)

So maybe `tox.ini`? I've seen major libraries [use](https://github.com/Theano/Theano/blob/master/setup.cfg) [either](https://github.com/scipy/scipy/blob/master/tox.ini) one.

**Comment by apaszke** [comment]
Hmmm ok, we're not using `tox` (SciPy is), so maybe let's keep it like that.

**Comment by ngimel** [comment]
@lukeyeager, would putting setup.cfg into tools directory and passing --config=tools to autopep8 be an option?

**Comment by lukeyeager** [comment]
Good point, that's an option too. The advantage of keeping a config file is that you can call `pep8 .` from anywhere in the tree and it will pick up the config for the project.

**Comment by apaszke** [comment]
It's not that bad, let's keep it in the root for now. We'll have to start using `pep8` a lot from now on.

**Comment by colesbury** [comment]
If `tox.ini` works with pep8 let's just change the name. (It sounds like it's officially supported from the pep8 docs). The autocomplete for setup has been bugging me all day.

**Pull request merged**
