### PR TITLE
Be compatible with SYCL 2020 and SYCL1.2.1 for sycl.hpp

### PR DESCRIPTION
**Pull request by cchheennhhaaoo**
- In SYCL2020, SYCL provides one standard header file: <sycl/sycl.hpp>, which needs to be included in every translation unit that uses the SYCL programming API.

- For compatibility with SYCL 1.2.1, SYCL provides another standard header file: <CL/sycl.hpp>, which can be included in place of <sycl/sycl.hpp>.

- SYCL documents this change in [doc](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:headers-and-namespaces)(4.3).

- SYCL_LANGUAGE_VERSION substitutes an integer reflecting the version number and revision of the SYCL language being supported by the implementation in SYCL 2020. In SYCL1.2.1, the macro name is CL_SYCL_LANGUAGE_VERSION. So these two macros can be used to distinguish SYCL1.2.1 and SYCL2020.

- SYCL 2020 doc: https://registry.khronos.org/SYCL/specs/sycl-2020/pdf/sycl-2020.pdf
- SYCL 1.2.1 doc: https://registry.khronos.org/SYCL/specs/sycl-1.2.1.pdf

### CODE REVIEW

**Comment by cchheennhhaaoo** [comment]
Hi, @malfet, could you please review this PR?

**Comment by malfet** [comment]
Hmm, so how users of older dpc++ are supposed to compile then?
Can you please put some sort of version guard?

**Comment by cchheennhhaaoo** [comment]
@malfet Have confirmed nobody will use older compiler later.

**Comment by cchheennhhaaoo** [comment]
Hi @malfet, help to review?
Have confirmed nobody will use older compiler.

**Comment by malfet** [comment]
> @malfet Have confirmed nobody will use older compiler later.

Can you please elaborate how did you do that? Are users of dpc++ a closed set?

**Comment by cchheennhhaaoo** [comment]
Hi, @malfet 

1. This change will not break old compiler. As long as include path is corrected, the old compiler can work, as well. We have verified it in intel extension framework for PyTorch with: 1) using old DPC++ compiler, 2) adding this change in PyTorch source code and build, 3)changing default SYCL include directory in our framework, it works well.

2. There should be no real user, who are using old DPC++ version for PyTorch implementation for now. And DPC++ compiler will not backward compatible with CL/sycl path. Therefore, the CL/sycl path will be dead code in PyTorch.

**Comment by malfet** [comment]
According https://intel.github.io/llvm-docs/doxygen/sycl_2sycl_8hpp.html correct include path is `CL/syncl.hpp`, isn't it?
image

**Review by malfet — CHANGES_REQUESTED** [review]
Looks like the current usage is correct per Intel's documentation, if there is a document explanting the plans to move the header and backward compatibility story, please reference this in the PR

**Comment by cchheennhhaaoo** [comment]
Hi, @malfet, PR updated, please help to review.

**Comment by cchheennhhaaoo** [comment]
@malfet

**Review by malfet — APPROVED** [review]
Thank you for the updates, now it looks reasonable to me.

**Pull request closed without merging**
