### PR TITLE
Remove HSDP validation check 

### PR DESCRIPTION
**Pull request by mvpatel2000**
Currently, HSDP validates that all intra/inter node PGs are the same. This makes sense if you are only using HSDP with no other forms of parallelism and is a nice but not necessary sanity check.

However, if you want to mix HSDP with other forms, say tensor parallelism on the FFN of a transformer block, the intra/inter node PGs will be different for that layer. This check raises errors in this scenario, so we need to remove this assumption.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Comment by awgu** [comment]
If I understand correctly, there is still some value in the check; however, it is currently overly strict and is problematic for manual wrapping + HSDP. I think there was someone internally working on relaxing the check.

The check that is valuable is that if you are using HSDP, then each HSDP instance should use the same process groups if using the same ranks. We do not want to create a different pair of process groups per HSDP instance.

**Comment by mvpatel2000** [comment]
@awgu got it! If someone is working on it, feel free to close this PR then :)

**Comment by awgu** [comment]
Let me follow-up on the progress on that PR and get back to you!

**Comment by awgu** [comment]
@fegin @wz337 Is there anything from the checkpointing side that requires each FSDP instance to use the HSDP process groups?

If not, then I think removing this requirement/check sounds good to me (and we would need to remove the unit test). https://github.com/pytorch/pytorch/blob/b8b3c26d3dd6da301d7331b25e3208f4d9e8faa3/test/distributed/fsdp/test_fsdp_hybrid_shard.py#L119-L157

**Comment by mvpatel2000** [comment]
> @fegin @wz337 Is there anything from the checkpointing side that requires each FSDP instance to use the HSDP process groups?
> 
> If not, then I think removing this requirement/check sounds good to me (and we would need to remove the unit test).
> 
> https://github.com/pytorch/pytorch/blob/b8b3c26d3dd6da301d7331b25e3208f4d9e8faa3/test/distributed/fsdp/test_fsdp_hybrid_shard.py#L119-L157

@awgu @fegin @wz337 bumping this request! would love to have this issue resolved

**Comment by mvpatel2000** [comment]
@awgu @fegin @wz337 bumping this please!

**Comment by fegin** [comment]
I think it is okay to remove the check. Will let @wz337 to review again.

**Comment by wz337** [comment]
> @fegin @wz337 Is there anything from the checkpointing side that requires each FSDP instance to use the HSDP process groups?
> 
> If not, then I think removing this requirement/check sounds good to me (and we would need to remove the unit test).
> 
> https://github.com/pytorch/pytorch/blob/b8b3c26d3dd6da301d7331b25e3208f4d9e8faa3/test/distributed/fsdp/test_fsdp_hybrid_shard.py#L119-L157

We are relying on the DTensor to do all_gather and chunk so we don't use the HSDP process groups directly. So I think it should be fine removing this requirement.

**Review by wz337 — APPROVED** [review]
I think it's ok to remove this check. 

Could you also include removing the unit test in the PR as @awgu mentioned so CI doesn't break? 

https://github.com/pytorch/pytorch/blob/main/test/distributed/fsdp/test_fsdp_hybrid_shard.py#L120

**Comment by wconstab** [comment]
@mvpatel2000 can i request that you update the PR desc to have a more detailed summary of why the change is OK (taking the above discussions into account) -- I'd like it to be clear what assumptions we're making and what conditions we're relaxing intentionally (and why).

**Comment by mvpatel2000** [comment]
@wz337 test removed!

@wconstab sorry -- updated to be more clear :)

**Review by Skylion007 — APPROVED** [review]

**Pull request closed without merging**
