### PR TITLE
[BE] enable UFMT for `torch/nn/*.py`

### PR DESCRIPTION
**Pull request by XuehaiPan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #128865
* #128592
* __->__ #128593

Part of #123062

- #123062

### CODE REVIEW

**Review by mikaylagawarecki — APPROVED** [review]

**Comment by fbgheith** [comment]
@pytorchbot revert -m "breaking internal builds" -c ghfirst

because of failure in 128594

**Pull request closed without merging**
