### PR TITLE
[Don't merge] Add FX docs

### PR DESCRIPTION
**Pull request by jlin27**
Don't merge yet. This PR is to test if we get the same errors from https://github.com/pytorch/pytorch/pull/48814

### CODE REVIEW

**Comment by jamesr66a** [comment]
FWIW the errors/warnings that appear hear have been present since before my PR:

pytorch_python_doc_build
--------------------------

```
Dec 08 01:16:35 LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
Dec 08 01:16:36 /usr/local/share/.config/yarn/global/node_modules/katex/dist/katex.js:17167
Dec 08 01:16:36     throw error;
Dec 08 01:16:36     ^
Dec 08 01:16:36 
Dec 08 01:16:36 ParseError: KaTeX parse error: Expected '}', got '_' at position 13: (N*\text{num_̲heads}, L, S)
Dec 08 01:16:36     at new ParseError (/usr/local/share/.config/yarn/global/node_modules/katex/dist/katex.js:265:14)
Dec 08 01:16:36     at Parser.expect (/usr/local/share/.config/yarn/global/node_modules/katex/dist/katex.js:16039:13)
Dec 08 01:16:36     at Parser.parseGroup (/usr/local/share/.config/yarn/global/node_modules/katex/dist/katex.js:16798:12)
Dec 08 01:16:36     at Parser.parseGroupOfType (/usr/local/share/.config/yarn/global/node_modules/katex/dist/katex.js:16497:21)
Dec 08 01:16:36     at Parser.parseArguments (/usr/local/share/.config/yarn/global/node_modules/katex/dist/katex.js:16452:22)
Dec 08 01:16:36     at Parser.parseFunction (/usr/local/share/.config/yarn/global/node_modules/katex/dist/katex.js:16392:37)
Dec 08 01:16:36     at Parser.parseGroup (/usr/local/share/.config/yarn/global/node_modules/katex/dist/katex.js:16818:21)
Dec 08 01:16:36     at Parser.parseAtom (/usr/local/share/.config/yarn/global/node_modules/katex/dist/katex.js:16267:21)
Dec 08 01:16:36     at Parser.parseExpression (/usr/local/share/.config/yarn/global/node_modules/katex/dist/katex.js:16132:23)
Dec 08 01:16:36     at Parser.parse (/usr/local/share/.config/yarn/global/node_modules/katex/dist/katex.js:16097:22) {
Dec 08 01:16:36   position: 12
Dec 08 01:16:36 }
```

This refers to this line:

https://github.com/pytorch/pytorch/blob/54f0556ee453d1c4a9c6756bfcdce1e0d62867a8/torch/nn/modules/activation.py#L953

which was added in https://github.com/pytorch/pytorch/pull/48577. The CI job on that PR succeeded even with that KaTeX error: https://app.circleci.com/pipelines/github/pytorch/pytorch/243550/workflows/7ed03a17-c4f6-41a1-9a13-3c80900ad89a/jobs/9198905

pytorch_doc_test
-----------------

The warnings here:

```
Dec 08 01:07:00 build finished with problems, 7 warnings.
Dec 08 01:07:00 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
Dec 08 01:07:00 	%13 : Float(4, strides=[1], requires_grad=0, device=cpu) = aten::rand(%8, %9, %10, %11, %12) # <doctest default[0]>:2:0
Dec 08 01:07:00 This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
Dec 08 01:07:00   _module_class,
Dec 08 01:07:00 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Dec 08 01:07:00 With rtol=1e-05 and atol=1e-05, found 4 element(s) (out of 12) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.394145667552948 (0.21437418460845947 vs. 0.6085198521614075), which occurred at index (0, 3).
Dec 08 01:07:00   _module_class,
Dec 08 01:07:00 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
Dec 08 01:07:00 	%14 : Float(1, 4, strides=[4, 1], requires_grad=0, device=cpu) = aten::rand(%9, %10, %11, %12, %13) # <doctest default[0]>:2:0
Dec 08 01:07:00 This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
Dec 08 01:07:00   _module_class,
Dec 08 01:07:00 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Dec 08 01:07:00 With rtol=1e-05 and atol=1e-05, found 4 element(s) (out of 8) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.36097317934036255 (0.38661420345306396 vs. 0.7475873827934265), which occurred at index (0, 1).
Dec 08 01:07:00   _module_class,
Dec 08 01:07:00 /opt/conda/lib/python3.6/site-packages/torch/jit/_recursive.py:197: UserWarning: 'mods' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
Dec 08 01:07:00   " but it is a non-constant {}. Consider removing it.".format(name, hint))
Dec 08 01:07:00 Makefile:38: recipe for target 'doctest' failed
```

Are also present on master in the CI, e.g. https://app.circleci.com/pipelines/github/pytorch/pytorch/248775/workflows/154664eb-65c3-4855-ab95-22bcd982053b/jobs/9498645. Is there a difference in configuration for PR v.s. master builds for `pytorch_doc_test`?

OTOH it may be nontrivial to remove these warnings

**Comment by jlin27** [comment]
> ## pytorch_doc_test
> The warnings here:
> 
> ```
> Dec 08 01:07:00 build finished with problems, 7 warnings.
> Dec 08 01:07:00 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
> Dec 08 01:07:00 	%13 : Float(4, strides=[1], requires_grad=0, device=cpu) = aten::rand(%8, %9, %10, %11, %12) # <doctest default[0]>:2:0
> Dec 08 01:07:00 This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
> Dec 08 01:07:00   _module_class,
> Dec 08 01:07:00 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
> Dec 08 01:07:00 With rtol=1e-05 and atol=1e-05, found 4 element(s) (out of 12) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.394145667552948 (0.21437418460845947 vs. 0.6085198521614075), which occurred at index (0, 3).
> Dec 08 01:07:00   _module_class,
> Dec 08 01:07:00 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
> Dec 08 01:07:00 	%14 : Float(1, 4, strides=[4, 1], requires_grad=0, device=cpu) = aten::rand(%9, %10, %11, %12, %13) # <doctest default[0]>:2:0
> Dec 08 01:07:00 This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
> Dec 08 01:07:00   _module_class,
> Dec 08 01:07:00 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
> Dec 08 01:07:00 With rtol=1e-05 and atol=1e-05, found 4 element(s) (out of 8) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.36097317934036255 (0.38661420345306396 vs. 0.7475873827934265), which occurred at index (0, 1).
> Dec 08 01:07:00   _module_class,
> Dec 08 01:07:00 /opt/conda/lib/python3.6/site-packages/torch/jit/_recursive.py:197: UserWarning: 'mods' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
> Dec 08 01:07:00   " but it is a non-constant {}. Consider removing it.".format(name, hint))
> Dec 08 01:07:00 Makefile:38: recipe for target 'doctest' failed
> ```
> 
> Are also present on master in the CI, e.g. https://app.circleci.com/pipelines/github/pytorch/pytorch/248775/workflows/154664eb-65c3-4855-ab95-22bcd982053b/jobs/9498645. Is there a difference in configuration for PR v.s. master builds for `pytorch_doc_test`?
> 
> OTOH it may be nontrivial to remove these warnings

The ci test setup should be the same for this PR and master. @brianjo Do you know if there've been any recent changes that could be causing these?

**Comment by mattip** [comment]
The warning in master is a little different and does not fail the build. It is due to some warnings from doctests, which are snippets of code pulled out of documenation and run to make sure the documented result is the same as the actual result. Someone needs to [run the doctests](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#adding-documentation-tests) and figure out which snippet(s) is/are emitting warnings.

<detail>

```
Dec 10 16:19:01 Doctest summary
Dec 10 16:19:01 ===============
Dec 10 16:19:01    26 tests
Dec 10 16:19:01     0 failures in tests
Dec 10 16:19:01     0 failures in setup code
Dec 10 16:19:01     0 failures in cleanup code
Dec 10 16:19:01 build succeeded.
Dec 10 16:19:01 
Dec 10 16:19:01 Testing of doctests in the sources finished, look at the results in build/doctest/output.txt.
Dec 10 16:19:01 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
Dec 10 16:19:01 	%13 : Float(4, strides=[1], requires_grad=0, device=cpu) = aten::rand(%8, %9, %10, %11, %12) # <doctest default[0]>:2:0
Dec 10 16:19:01 This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
Dec 10 16:19:01   _module_class,
Dec 10 16:19:01 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Dec 10 16:19:01 With rtol=1e-05 and atol=1e-05, found 4 element(s) (out of 12) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.3594818711280823 (0.5629010200500488 vs. 0.9223828911781311), which occurred at index (0, 0).
Dec 10 16:19:01   _module_class,
Dec 10 16:19:01 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Trace had nondeterministic nodes. Did you forget call .eval() on your model? Nodes:
Dec 10 16:19:01 	%14 : Float(1, 4, strides=[4, 1], requires_grad=0, device=cpu) = aten::rand(%9, %10, %11, %12, %13) # <doctest default[0]>:2:0
Dec 10 16:19:01 This may cause errors in trace checking. To disable trace checking, pass check_trace=False to torch.jit.trace()
Dec 10 16:19:01   _module_class,
Dec 10 16:19:01 /opt/conda/lib/python3.6/site-packages/torch/jit/_trace.py:804: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Dec 10 16:19:01 With rtol=1e-05 and atol=1e-05, found 4 element(s) (out of 8) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.7350203990936279 (0.8313918709754944 vs. 0.09637147188186646), which occurred at index (0, 3).
Dec 10 16:19:01   _module_class,
Dec 10 16:19:01 /opt/conda/lib/python3.6/site-packages/torch/jit/_recursive.py:197: UserWarning: 'mods' was found in ScriptModule constants,  but it is a non-constant submodule. Consider removing it.
Dec 10 16:19:01   " but it is a non-constant {}. Consider removing it.".format(name, hint))
Dec 10 16:19:02 + cleanup
Dec 10 16:19:02 + retcode=0
Dec 10 16:19:02 + set +x
```

**Comment by brianjo** [comment]
> The warning in master is a little different and does not fail the build. It is due to some warnings from doctests, which are snippets of code pulled out of documenation and run to make sure the documented result is the same as the actual result. Someone needs to [run the doctests](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#adding-documentation-tests) and figure out which snippet(s) is/are emitting warnings.
> 
Thanks for the clarification Matti! I'll dig into this and see if we can get to the bottom of it.

**Comment by brianjo** [comment]
@jlin27 Can we close this one now?

**Pull request closed without merging**
