### PR TITLE
Replaced CHECK with TORCH_CHECK in order to not abort, but throw a RuntimeError instead

### PR DESCRIPTION
**Pull request by antoniojkim**
Porting over changes from #117653 

Cherry-picked: bc9cb04822d5bad565816db818aa87d091332ebf

CC: @tringwald @atalman

### CODE REVIEW

**Comment by antoniojkim** [comment]
@atalman @malfet Any updates on whether this will be approved to make it into 2.2.1?

**Comment by malfet** [comment]
@antoniojkim can you please elaborate how user might encounter this crash?

**Review by malfet — APPROVED** [review]

**Comment by antoniojkim** [comment]
> @antoniojkim can you please elaborate how user might encounter this crash?

For instance, if they do an operation with a mix of lazy tensors and cpu tensors
```python
In [1]: import torch

In [2]: import torch._lazy.ts_backend

In [3]: torch._lazy.ts_backend.init()

In [4]: t = torch.ones((2, 2), device="lazy")

In [5]: z = torch.zeros_like(t, device="cpu")

In [6]: t + z
[F tensor.cpp:361] Check failed: lazy_tensor Input tensor is not a lazy tensor: CPUFloatType
Aborted
```
In this case its obvious where the mistake is. But suppose there was a mistake in some model definition with hundreds or even thousands of lines of code. The fact that we abort here makes it very difficult to track down which line is the problematic one. Versus if a `RuntimeError` is thrown, then we get a nice python stacktrace that can point the user to exactly which line is problematic.

**Comment by antoniojkim** [comment]
> unless lazy tensors are commonly used for tracing

@malfet We rely very heavily on lazy tensors for tracing. We do plan to eventually migrate to dynamo. But even in that future, I'm not sure that we will ever be able to completely rely on dynamo for all our tracing needs.

**Pull request merged**
