### PR TITLE
[mobile] Fix lightweight dispatch OOM error by introducing selective build

### PR DESCRIPTION
**Pull request by larryliu0820**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #78983

issue: #78540

This PR introduces selective build to lightweight dispatch CI job. By doing so we can't run the `test_lite_intepreter_runtime` test suite anymore because it requires some other operators.

From now on, if we are adding a new unit test in `test_codegen_unboxing`, we will have to export the operators for the unit test model and add them into `lightweight_dispatch_ops.yaml`. This can be automated by introducing tracing based selective build, but that's for next PR to do.

### CODE REVIEW

**Comment by suo** [comment]
Should this PR also re-enable the disabled CI job?

**Comment by kit1980** [comment]
LGTM. Please rebase on master.

**Review by kit1980 — APPROVED** [review]

**Comment by malfet** [comment]
@larryliu0820 can you please explain how it fixes the OOM?

**Comment by larryliu0820** [comment]
@osalpekar can you share what exactly is broken?

**Comment by kit1980** [comment]
@larryliu0820 looks like the issue is that when `TEST_ONLY_op_registration_allowlist_yaml_path` is not provided, this code crashes on TypeError:

```
    with open(options.TEST_ONLY_op_registration_allowlist_yaml_path, "r") as f:
        op_registration_allowlist = yaml.safe_load(f)
```

It would be nice to have a test for that also.

**Pull request closed without merging**
