### PR TITLE
Various fix for memory leak in test autograd and dataloader

### PR DESCRIPTION
**Pull request by albanD**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #143204
* __->__ #143323
* #143225

### CODE REVIEW

**Review by andrewkho — APPROVED** [review]
LGTM, out of curiosity, how did this issue manifest and get caught?

**Comment by albanD** [comment]
The PR just above in the stack!
It detects Tensor objects being left around during testing

**Review by soulitzer — APPROVED** [review]
Nice fixes!

**Pull request closed without merging**
