### PR TITLE
Add version selector back to functorch docs

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #86602

I accidentally deleted it in
https://github.com/pytorch/pytorch/pull/85856/ . This brings the version
selector back.

### CODE REVIEW

**Comment by zou3519** [comment]
Note to self: this also needs to be cherry-picked to release branch

**Comment by zou3519** [comment]
Docs preview available at https://docs-preview.pytorch.org/86602/functorchdocs/index.html , note the version selector: (the triangle is clickable)

image

**Review by samdow — APPROVED** [review]

**Comment by samdow** [comment]
Wait I might have been premature in my approve haha
Is this what we're trying to fix? I still see this in the docs build from this PR?

No dropdown
Screen Shot 2022-10-11 at 10 42 04 AM
Previous version has dropdown
Screen Shot 2022-10-11 at 10 42 53 AM

**Comment by zou3519** [comment]
Yeah, the previous version of the nightly docs have no dropdown. In the preview for this PR, there is a dropdown.

All the stable docs (0.2.1, etc) are built a single time and never updated so they aren't affected.

**Pull request closed without merging**
