### PR TITLE
[testing] Add OpInfo for rad2deg and deg2rad

### PR DESCRIPTION
**Pull request by kshitij12345**
Reference: #50006

We should probably add aliases for these operators to be consistent with NumPy names i.e. `np.degrees` and `np.radians`.

### CODE REVIEW

**Comment by kshitij12345** [comment]
**Reason for disabling BFloat16**

```python
>>> import torch
>>> t = torch.tensor(-500., dtype=torch.bfloat16)
>>> t
tensor(-500., dtype=torch.bfloat16)
>>> torch.rad2deg(t)
tensor(-28672., dtype=torch.bfloat16)
>>> torch.rad2deg(t.to(torch.float))
tensor(-28647.8906)
>>>
>>>
>>> t = torch.tensor(-4980736.0, dtype=torch.bfloat16)
>>> torch.deg2rad(t)
tensor(-87040., dtype=torch.bfloat16)
>>> torch.deg2rad(t.to(torch.float))
tensor(-86930.2422)
```

**Comment by mruberry** [comment]
> We should probably add aliases for these operators to be consistent with NumPy names i.e. `np.degrees` and `np.radians`.

We ran into an issue while doing this because Torchscript defines the builtins "degrees" and "radians." See https://github.com/pytorch/pytorch/pull/42910. This is definitely fixable, but we haven't bothered pursuing it.

**Review by mruberry — APPROVED** [review]
Awesome! Thanks @kshitij12345!

We're getting close to being done with _TorchMathTestMeta!

**Comment by kshitij12345** [comment]
@mruberry Gentle Ping :)

**Comment by ngimel** [comment]
> **Reason for disabling BFloat16**
> 
> ```python
> >>> import torch
> >>> t = torch.tensor(-500., dtype=torch.bfloat16)
> >>> t
> tensor(-500., dtype=torch.bfloat16)
> >>> torch.rad2deg(t)
> tensor(-28672., dtype=torch.bfloat16)
> >>> torch.rad2deg(t.to(torch.float))
> tensor(-28647.8906)
> >>>
> >>>
> >>> t = torch.tensor(-4980736.0, dtype=torch.bfloat16)
> >>> torch.deg2rad(t)
> tensor(-87040., dtype=torch.bfloat16)
> >>> torch.deg2rad(t.to(torch.float))
> tensor(-86930.2422)
> ```

Why is this a reason for disabling bfloat16 testing? It's ~1e-3 relative error, which is about as good as you can ever expect for bfloat16.

**Comment by mruberry** [comment]
> Why is this a reason for disabling bfloat16 testing? It's ~1e-3 relative error, which is about as good as you can ever expect for bfloat16.

We need to extend the precision decorator to allow specifying relative, not just absolute, tolerance. I've updated https://github.com/pytorch/pytorch/issues/50006 with this task.

**Pull request closed without merging**
