### PR TITLE
Revert "make native/cuda/EmbeddingBackwardKernel.cu data_ptr-correct (#99027)"

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99244

This reverts commit 27049f3ff2c8b00cfa67cf5adb9037b00e9d8130.

See discussion in #99027

### CODE REVIEW

**Comment by dagitses** [comment]
@jansel do you mind testing #99245?

**Review by malfet — APPROVED** [review]
Sounds fine to me, but why not call `@pytorchbot revert`?

**Comment by jansel** [comment]
> Sounds fine to me, but why not call `@pytorchbot revert`?

Trying to be polite by allowing review (and possibly a forward fix), given we don't officially support CUDA 12 yet.

**Comment by jansel** [comment]
Closing in favor of https://github.com/pytorch/pytorch/pull/99245

**Pull request closed without merging**
