### PR TITLE
Do not pass down USE_GLOO_IBVERBS to CMake

### PR DESCRIPTION
**Pull request by xuhdev**
It doesn't seem to be used anywhere once down to CMake in this repo or any submodules

### CODE REVIEW

**Comment by pietern** [comment]
Can you also remove it from `tools/setup_helpers/dist_check.py`?

**Comment by pietern** [comment]
FWIW, this was left over from the original THD bindings.

When we find we need to re-enable this we can bring it back. You're right that this is currently unused.

**Comment by xuhdev** [comment]
The one in dist_check.py is still used in cmake.py for enabling distribution build in general.

**Review by ezyang — APPROVED** [review]
okey dokey (waiting on CI)

**Pull request closed without merging**
