### PR TITLE
[pytorch][perf] Disable threading on convolutions going through NNPACK.

### PR DESCRIPTION
**Pull request by AshkanAliabadi**
There is a problem with our integration of NNPACK and the threading library of our choice that results in suboptimal performance on mobile platforms.  This commit disables NNPACK threading on mobile builds as a temporary solution to boost performance.  Other multi-threaded code paths are not affected.  Single-threaded performance and behavior is unchanged.

Test: CI

Performance:

All timings on Pixel 2.

Before:

 Single-threaded: 

> ./speed_benchmark_torch
>   --model=./xraymobilev3.pt
>   --input_dims="1,3,224,224"
>   --input_type=float
>   --warmup=5
>   --iter=25
>   --caffe2_threadpool_force_inline=true
> 
> Main run finished. Milliseconds per iter: **354.586**. Iters per second: 2.82019

> ./speed_benchmark_torch
>   --model=./xraymobilev3.pt
>   --input_dims="1,3,224,224"
>   --input_type=float
>   --warmup=5
>   --iter=25
>   --caffe2_threadpool_force_inline=true
> 
> Multi-threaded: Main run finished. Milliseconds per iter: **366.644**. Iters per second: 2.72744

After 

Single-threaded:

> ./speed_benchmark_torch
>   --model=./xraymobilev3.pt
>   --input_dims="1,3,224,224"
>   --input_type=float
>   --warmup=5
>   --iter=25
>   --caffe2_threadpool_force_inline=true
> Single-threaded: Main run finished. Milliseconds per iter: **353.525**. Iters per second: 2.82865

> ./speed_benchmark_torch
>   --model=./xraymobilev3.pt
>   --input_dims="1,3,224,224"
>   --input_type=float
>   --warmup=5
>   --iter=25
>   --caffe2_threadpool_force_inline=true
> 
> Multi-threaded: Main run finished. Milliseconds per iter: **338.088**. Iters per second: 2.95781

### CODE REVIEW

**Comment by AshkanAliabadi** [comment]
@ljk53 I am curious to know how this performs on your other phones.  I'll abandon this change if the net is negative.

**Comment by ljk53** [comment]
> @ljk53 I am curious to know how this performs on your other phones. I'll abandon this change if the net is negative.

Sure, here you go:

Before patching your PR:
```
S9 - single: 336.788
S9 - multi: 334.131
OnePlus5 - single: 285.454
OnePlus5 - multi: 259.118
```
After patching your PR:
```
S9 - single: 337.024
S9 - multi: 462.867  // slower
OnePlus5 - single: 283.426
OnePlus5 - multi: 252.801  // roughly the same
```

I feel it would be helpful to compare per-op performance before/after your PR, like what I did on #26702. It would be clear where the multithreading perf hit comes from.

**Comment by dzhulgakov** [comment]
unrelated: why do we need to pass `caffe2_threadpool_force_inline`? we should make it default

**Comment by ljk53** [comment]
> unrelated: why do we need to pass `caffe2_threadpool_force_inline`? we should make it default

We used the flag to compare multi-thread v.s. single-thread perf. I think there was typo - 2 of them should be false.

**Comment by AshkanAliabadi** [comment]
Right, copy paste error. :)

**Pull request closed without merging**
