### PR TITLE
Value range refinement using multi-variate expressions.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #97964
* #97963
* #103611
* #102563

### CODE REVIEW

**Comment by ysiraichi** [comment]
As is, the only difference (benchmark-wise) is that `pytorch_unet` goes from `9/73/73` (univariate only) to `9/70/70`. Still have to run the whole benchmark set, though.

**Review by lezcano — COMMENTED** [review]
In this case, when refining the bounds, it could be the case that `rhs_vr.lower/upper` are variables. In that case, the refinement could then be `lower = max(lower, rhs_vr.lower)`, right?

**Review by lezcano — COMMENTED** [review]
At any rate, this needs some testing.

**Review by ezyang — APPROVED** [review]
Giving you the cursory stamp since all the heavy lifting happened in prev PR.

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your PR, but it is breaking an internal test' -c ghfirst

The fail tests are `pye/model_inventory/inside_out_tracking_model:inside_out_tracking_model_test - test_executorch_e2e_output_consistency_aten (pye.model_inventory.inside_out_tracking_model.InsideOutTrackingModelTest.InsideOutTrackingModelTest)` and `pye/model_inventory/inside_out_tracking_model:inside_out_tracking_model_test - test_export_to_backend_dynamic (pye.model_inventory.inside_out_tracking_model.InsideOutTrackingModelTest.InsideOutTrackingModelTest)`

Here is the error I see in the logs:

```
line 316, in _fx
    res_data = getattr(interpreter, kind)(target, args_data, kwargs_data)
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/torch/fx/interpreter.py", line 267, in call_function
    return target(*args, **kwargs)
IndexError: list index out of range

While executing %getitem_2 : [num_users=1] = call_function[target=operator.getitem](args = (%split_copy, 2), kwargs = {})
Original traceback:
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/frldistml/scaffold/model.py", line 99, in forward
    x = self.model_base(input)
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/torch/nn/modules/module.py", line 1514, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/handtracking/common/models/unet.py", line 443, in forward
    list_x = torch.chunk(input_imgs_stacked, self.n_views, dim=1)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/pye/lib/UnitTestBase.py", line 314, in test_export_to_backend_dynamic
    *self._export_model(
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/pye/lib/UnitTestBase.py", line 240, in _export_model
    multi_method_program = model_gen.compile(
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/pye/lib/EagerModelBase.py", line 327, in compile
    multi_export_prog = multi_export_prog.to_edge(
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/executorch/exir/__init__.py", line 753, in to_edge
    method_name_to_edge_prog = {
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/executorch/exir/__init__.py", line 754, in <dictcomp>
    method_name: prog.to_edge(config)
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/executorch/exir/__init__.py", line 219, in to_edge
    return _to_edge(self, config)
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/executorch/exir/__init__.py", line 157, in _to_edge
    new_ep = ep.transform(*passes)
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/executorch/exir/__init__.py", line 194, in transform
    ep = super().transform(*passes)
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/torch/_export/exported_program.py", line 178, in transform
    res = pm(self.graph_module)
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/inside_out_tracking_model_test#link-tree/torch/fx/passes/infra/pass_manager.py", line 296, in __call__
    raise Exception(msg) from e
Exception: An error occurred when running the 'NormalizeTransposePass' pass after the following passes: ['ReplaceSymSizeOpPass']

----------------------------------------------------------------------
Ran 1 test in 38.429s

FAILED (errors=1)
```

**Comment by ysiraichi** [comment]
@ezyang @huydhn 
Best guess I have is: multi-variate range refinement is not sound. Could you try running it while setting `torch._dynamo.config.translation_validation = True`? Or, is there an example I can try to reproduce the error?

**Comment by lezcano** [comment]
This implementations looks good to me, so I don't think it's "not sound" by itself. 

My gut tells me that the issue is lurking in the value range analysis. I already found a number of bugs in it, so I wouldn't be entirely surprised that there were more issues lurking there.

**Comment by ysiraichi** [comment]
@lezcano I think the translation validator should be able to catch that.

**Comment by ysiraichi** [comment]
@ezyang @huydhn
This is a friendly reminder. If you have some time, could you try and run the failing test with TV on?

**Comment by ezyang** [comment]
going to attempt this, might be tricky because i'm not sure we have z3 on our internal

**Comment by ezyang** [comment]
Patching this

```
diff --git a/fbcode/caffe2/torch/_dynamo/config.py b/fbcode/caffe2/torch/_dynamo/config.py
--- a/fbcode/caffe2/torch/_dynamo/config.py
+++ b/fbcode/caffe2/torch/_dynamo/config.py
@@ -237,7 +237,7 @@
 numpy_ndarray_as_tensor = False
 
 # Uses z3 for validating the guard optimizations transformations.
-translation_validation = False
+translation_validation = True
 
 
 def is_fbcode():
```

and rerunning the test, I still get the same error as before:

```
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/
inside_out_tracking_model_test#link-tree/torch/_dynamo/eval_frame.py", line 1012, in graph_with_interpreter                                                      return torch.fx.Interpreter(graph).run(*args)                                                                                                            
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/
inside_out_tracking_model_test#link-tree/torch/fx/interpreter.py", line 138, in run                                                                              self.env[node] = self.run_node(node)                                                                                                                     
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/
inside_out_tracking_model_test#link-tree/torch/fx/interpreter.py", line 195, in run_node                                                                         return getattr(self, n.op)(n.target, args, kwargs)                                                                                                       
  File "/data/users/ezyang/fbsource/buck-out/v2/gen/fbcode/8c7462494077df89/pye/model_inventory/inside_out_tracking_model/__inside_out_tracking_model_test__/
inside_out_tracking_model_test#link-tree/torch/fx/interpreter.py", line 267, in call_function                                                                
    return target(*args, **kwargs)                                                                                                                           
IndexError: tuple index out of range                                                                                                                         
                                                                                                                                                             
While executing %getitem_6 : [num_users=1] = call_function[target=operator.getitem](args = (%chunk, 2), kwargs = {})   
```

which suggests that we don't get to TV (which makes sense, TV only runs all the way at the end of execution, but we're erroring midway through.

I have a live session failing, lmk what kind of debugging instrumentation you want.

**Comment by ysiraichi** [comment]
@ezyang 

This is really odd. AFAIU, this PR modifies `var_to_range` which affects what guards are issued. So, if there was a problem with it, I would expect it to be executing a wrong compiled function (i.e. we should not have eliminated some guards).

Just to be completely sure, could you try commenting these lines at the end of `refine_ranges` and check that it passes the test?

```python
# Updates the range and the guards corresponding to each bound of the symbol.
self.var_to_range[symbol] = ValueRanges(lower, upper)
self.var_to_guards[symbol] = (lower_guard, upper_guard)
```

**Comment by ezyang** [comment]
Applying this patch

```
diff --git a/fbcode/caffe2/torch/fx/experimental/symbolic_shapes.py b/fbcode/caffe2/torch/fx/experimental/symbolic_shapes.py
--- a/fbcode/caffe2/torch/fx/experimental/symbolic_shapes.py
+++ b/fbcode/caffe2/torch/fx/experimental/symbolic_shapes.py
@@ -3467,8 +3467,8 @@
                 continue
 
             # Updates the range and the guards corresponding to each bound of the symbol.
-            self.var_to_range[symbol] = ValueRanges(lower, upper)
-            self.var_to_guards[symbol] = (lower_guard, upper_guard)
+            #self.var_to_range[symbol] = ValueRanges(lower, upper)
+            #self.var_to_guards[symbol] = (lower_guard, upper_guard)
             # Clears the cache, since this update can change the result.
             self._maybe_evaluate_static.cache_clear()
 

```

and confirmed the test passes afterwards.

**Pull request closed without merging**
