### PR TITLE
optimize dim reduce performance on norm, argmax and argmin

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #64726
* __->__ #64479
* #64478

### CODE REVIEW

**Comment by mingfeima** [comment]
- [ ] add benchmark data

**Comment by mingfeima** [comment]
This PR improves some dim reduce OPs (`norm`, `argmax`, `argmin`) when the reduction is done on the last dimension when we have chance to vectorize the kernel.

For instance, `norm(p=2)` should share similar perf as `sum` since the payload is pretty much the same, but originally `norm(p=2)` is far slower than `sum`. With this patch,  `norm(p=2)` and `sum` are even.

`argmax` and `argmin` goes to scalar compare (since pytorch needs to propagate NaN, manually vectorize the code would take too much effort). so `argmax` and `argmin` are slower than `norm`. Same reason that bfloat16 is slower than float32. Anyway, `argmax` and `argmin` are still much faster than original version.



#### avx512 single socket
```bash
### before:
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 34.283 ms
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 34.628 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 0.532 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 0.290 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 34.223 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 34.416 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 34.465 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 34.446 ms

### after:
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 0.576 ms
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 0.266 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 0.541 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 0.286 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 2.266 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 4.392 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 2.274 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 4.412 ms
```

#### avx512 single core
```bash
### before:
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 67.025 ms
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 141.807 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 5.985 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 4.574 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 88.981 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 122.613 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 88.236 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 123.291 ms

### after:
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 5.998 ms
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 4.204 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 6.169 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 4.530 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 36.471 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 71.375 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 36.602 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 71.172 ms
```

#### avx2 single socket
```bash
### before:
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 50.393 ms
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 55.708 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 0.988 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 0.870 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 49.589 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 49.651 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 54.183 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 55.447 ms

### after:
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 1.730 ms
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 1.560 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 1.006 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 0.857 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 6.668 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 11.750 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 5.258 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 10.323 ms
```

#### avx2 single core
```bash
### before:
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 93.797 ms
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 154.342 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 8.135 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 6.619 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 89.208 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 153.091 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 92.109 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 159.411 ms

### after:
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 10.016 ms
##  norm : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 7.415 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 8.379 ms
##  sum : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 6.627 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 40.076 ms
##  argmax : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 106.484 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.float32 ; time = 40.594 ms
##  argmin : size:  torch.Size([16, 256, 64, 64]) ; dtype:  torch.bfloat16 ; time = 102.603 ms
```

**Review by frank-wei — APPROVED** [review]
Passed tests in D33862408

**Comment by VitalyFedyunin** [comment]
You need to use `ghimport -s` command line tool to import it properly

**Pull request closed without merging**
