### PR TITLE
S390x clang fixes for SIMD

### PR DESCRIPTION
**Pull request by AlekseiNikiforovIBM**
S390x clang fixes for SIMD

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
I'm fine with the fix. But I'm wondering how CI can be help validate these changes and avoid breaks in the future. cc @malfet

**Comment by AlekseiNikiforovIBM** [comment]
I've manually rebased and dropped second commit because similar change was merged.

Maybe this change can be merged? For CI discussion there exists an open issue: https://github.com/pytorch/pytorch/issues/99305

**Pull request closed without merging**
