### PR TITLE
Remove backward ops for miopen convolution

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70064
* #70063
* __->__ #69987

Differential Revision: [D33170379](https://our.internmc.facebook.com/intern/diff/D33170379)

### CODE REVIEW

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33136054).

**Comment by jbschlosser** [comment]
@albanD ping for review :) this one should be even easier than the cudnn one

**Review by albanD — APPROVED** [review]
LGTM

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33136054).

**Review by albanD — APPROVED** [review]

**Comment by jbschlosser** [comment]
Reverted due to ROCm breakage; reopening for a fix.

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33170379).

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33170379).

**Pull request closed without merging**
