### PR TITLE
make `to` properly support permutation

### LINKED ISSUE #77600: torch.to() does not preserve stride permutation
```
a = torch.testing.make_tensor((2, 2), dtype=torch.long, device='cpu', noncontiguous=True).transpose(0, -1)
a.stride()
: (2, 4)

a.to(torch.double).stride()
: (2, 1)
```

The tensor produced should have a stride of (1, 2), consistent with the permutation of the input tensor.

cc @ezyang @mruberry @ngimel

### PR DESCRIPTION
**Pull request by ngimel**
Fixes #77600 (tests to come from #77585)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ngimel** [comment]
@JackCaoG do you know if xla failure is real? It doesn't look like this PR should have affected it.

**Comment by JackCaoG** [comment]
```
2022-05-17T01:23:06.0450755Z 
2022-05-17T01:23:06.0450830Z Running tests...
2022-05-17T01:23:06.0451164Z ----------------------------------------------------------------------
2022-05-17T01:23:06.1189722Z   test_advancedindex_big_xla (__main__.TestIndexingXLA) ... ok (0.073s)
2022-05-17T01:23:06.1473126Z   test_advancedindex_xla_float16 (__main__.TestIndexingXLA) ... skip: XLA does not support dtype torch.float16 (0.028s)
2022-05-17T01:23:06.1748380Z   test_advancedindex_xla_float64 (__main__.TestIndexingXLA) ... skip: onlyNativeDeviceTypes: doesn't run on xla (0.027s)
2022-05-17T01:23:06.2435804Z   test_basic_advanced_combined_xla (__main__.TestIndexingXLA) ... ok (0.069s)
2022-05-17T01:23:07.9555601Z   test_bool_indices_accumulate_xla (__main__.TestIndexingXLA) ... ./test/run_tests.sh: line 35: 12604 Segmentation fault      (core dumped) "$@"
2022-05-17T01:23:07.9562496Z + cleanup
```
Seems to be a segfault. I can try to repro it tmr. I am guessing it is related, let me rerun test at pytorch/xla master to confirm.

**Comment by ngimel** [comment]
Thanks! Please let me know if I should do some fixes. This PR changes output layout of `to` operation for a pretty rare case where input is not memory dense (e.g. some tensor slice), that I don't think is even encountered in that test.

**Comment by JackCaoG** [comment]
xla test passed on master, if it fail again in this pr I will try to debug it.

**Review by mruberry — APPROVED** [review]
Cool!

**Comment by ngimel** [comment]
> xla test passed on master, if it fail again in this pr I will try to debug it.

The test failed again, @JackCaoG can you please look into it?

**Comment by JackCaoG** [comment]
sg, will do today

**Comment by JackCaoG** [comment]
I am able to repo this failure on my end, looking at my GDB I think this change caused a stackoverflow by recursively calling some function. If I check the backtrace I saw
```
#26559 0x00007ffff7e0709b in __libc_start_main (main=0x55555564a0a0 <main>, argc=3, argv=0x7fffffffe8c8, init=<optimized
out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe8b8) at ../csu/libc-start.c:308
#26560 0x0000555555730e90 in _start () at ../sysdeps/x86_64/elf/start.S:103
``` 

trying to find the pattern

**Comment by ngimel** [comment]
I've pushed another attempt at workaround that restored logic to what it used to be for xla tensors, but if xla uses cpu fallback for this op, it won't work (because we do want cpu tensors to take new permutation-preserving path).

**Comment by JackCaoG** [comment]
Yea, I think the issue is there is a stride we do not support so we fallback to CPU and cause all of the recursive calls
```
as_stride is not supported
 676│ at::Tensor XLANativeFunctions::as_strided(
 677│     const at::Tensor& self, at::IntArrayRef size, at::IntArrayRef stride,
 678│     c10::optional<int64_t> storage_offset) {
 679│   XLA_FN_COUNTER("xla::");
 680│   XLATensor self_tensor = bridge::GetXlaTensor(self);
 681│   auto xsize = XlaHelpers::I64List(size);
 682│   auto xstride = XlaHelpers::I64List(stride);
 683│   if (!AsStrided::StrideIsSupported(self_tensor.shape(), xsize, xstride,
 684│                                     storage_offset.value_or(0))) {
 685├>    return at::native::call_fallback_fn<
 686│         &xla_cpu_fallback, ATEN_OP(as_strided)>::call(self, size, stride,
 687│                                                       storage_offset);
 688│   }
 689│   return bridge::AtenFromXlaTensor(
 690│       XLATensor::as_strided(self_tensor, std::move(xsize), std::move(xstride),
 691│                             XlaHelpers::I64Optional(storage_offset)));
 692│ }
```

**Comment by JackCaoG** [comment]
I think the call stack is
`at::empty_like` -> `at::empty_strided` -> `XLANativeFunctions::empty_strided` -> `XLANativeFunctions::as_strided` -> `fallback` -> `at::_to_copy` -> ....

**Comment by ngimel** [comment]
Hm, but I don't know how to avoid `empty_like` for cpu tensors, that's kinda the point of this PR.

**Pull request closed without merging**
