### PR TITLE
Support non-standard bools in CUDA unique

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #79393
* #81898
* __->__ #79392

For the thrust version of unique, this just uses `c10::load`. However,
the cub implementation is a bit more complicated since the values are
pointers are dereferenced inside of the `cub` library.

For the consecutive values path, I user `cub::TransformInputIterator`
to read the values as a `uint8_t` then cast to `bool`. But for the
path requiring a sort, this doesn't work because `cub`'s radix sorts
don't support iterators. Instead, I've written a special case for
`bool` which avoids the sorting step entirely.

### CODE REVIEW

**Comment by mruberry** [comment]
@ngimel would you like to review this PR in the stack?

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
@peterbell10 can you please rebase and land?

**Pull request closed without merging**
