### PR TITLE
[ROCm] Fix TunableOp UTs: Rotating Buffer

### PR DESCRIPTION
**Pull request by naromero77amd**
TunableOp's rotating buffer feature cannot be properly tested because the environment variable that controls this feature is sticky. A Python API is introduced to modify this value.

Additional items in this PR:
* UT for rotating buffer API
* Clean up UTs that were setting the rotating buffer via the environment variable
* Align behavior of environment variable and Python API when a negative value (< 0) is set.
* Update documentation.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by naromero77amd** [comment]
Confirming that the new tests ran in `linux-focal-rocm6.2-py3.10 / test (default, 2, 6, linux.rocm.gpu.2)` 
```
test/test_linalg.py::TestLinalgCUDA::test_renorm_ps_cuda, test/test_linalg.py::TestLinalgCUDA::test_rotating_buffer_tunableop_cuda_float32, 
```

**Review by jeffdaily — APPROVED** [review]

**Pull request closed without merging**
