### PR TITLE
[Caffe2] Turning on ATEN for Caffe2 in integrated builds

### PR DESCRIPTION
**Pull request by pjh5**
This is being used for a one-off at the moment

### CODE REVIEW

**Comment by pjh5** [comment]
That test failure is a separate area. First I have noticed it

**Comment by pjh5** [comment]
Actually I'll just fix the error here. Test fails cause there is no leveldb, but leveldb has been removed for now to avoid all the gcc issues surrounding it so that integrated builds can be cleaner and so we don't need as many CI builds

**Comment by pjh5** [comment]
The name change is a bug but won't actually make a difference right now b/c I removed all the gcc buidls

**Review by orionr — APPROVED** [review]

**Pull request merged**
