### PR TITLE
fix print tensor in cpp for privateuse1

### PR DESCRIPTION
**Pull request by heidongxianhua**
Fixes #ISSUE_NUMBER
1、fix lintrunnr in `test/inductor/test_cuda_repro.py`
2、In Libtorch, if we rename the `privateuseone` backend to `foo`, and when we print tensor with `std::cout << tensor`, we will get the output like this, 
```
1.0, 2.0 ...
[PrivateUse1FloatType{2,3}]
```
and it should be like this 
```
1.0, 2.0 ...
[fooFloatType{2,3}]
```

cc @soumith @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by heidongxianhua** [comment]
@ezyang  could you take a look for my changes, thank you hha?

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
