### PR TITLE
Fix a docstring of resolve_neg

### PR DESCRIPTION
**Pull request by kato8966**
cc @svekars @carljparker

### CODE REVIEW

**Comment by kit1980** [comment]
@kato8966 please sign the CLA

**Comment by kato8966** [comment]
@kit1980 Ok. I signed it and sent it to the PyTorch team.

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@kato8966 you need to sign CLA using the same email as commit you've authored, and this email also must be registered with your github account.

**Comment by kato8966** [comment]
@malfet Sorry, I didn't sign a CLA with an email address used for the merge commit. I resent the PyTorch team a signed CLA with the address.

**Comment by kit1980** [comment]
@kato8966 The CLA check is still failing.
Did you click "[Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/29311126/65600975/104151/#/?version=2)" link and followed the steps?

**Comment by kato8966** [comment]
@kit1980 I proceeded to the link, filled out the form, printed it out, signed it, and emailed it to the PyTorch team. Maybe they hadn't checked the email yet?

**Comment by kato8966** [comment]
EasyCLA check was passed.

**Pull request closed without merging**
