### PR TITLE
Align formula in Impl::General mode with Impl::Contiguous mode in batch_norm_elementwise_cuda op.

### LINKED ISSUE #106941: batch_norm_elemt op have different result in Impl::Contiguous and Impl::General mode on cuda device.
### 🐛 Describe the bug

batch_norm_elemt op have different result in Impl::Contiguous and Impl::General mode on cuda device.

**Code**
`import torch

x = torch.Tensor([[[[[-6.8167e+35]]]]]).cuda()
mean = torch.Tensor([4.8408]).cuda()
invsted = torch.Tensor([0.1174]).cuda()
weight = torch.Tensor([-2281.7122]).cuda()
bias = torch.Tensor([1.9951]).cuda()
out_cuda=torch.batch_norm_elemt(x, weight, bias, mean, invsted, 0)
print(out_cuda)`

**result:**
1) In Contiguous mode:
python test_bn.py
tensor([[[[[inf]]]]], device='cuda:0')
2) in Not Contiguous mode: (U can modify batch_norm_choose_impl function for always return Impl::General )
python test_bn.py
tensor([[[[[1.8260e+38]]]]], device='cuda:0')

### Versions

Collecting environment information...
PyTorch version: 1.13.0a0+gitd922c29
Is debug build: True
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.17.3
Libc version: glibc-2.17

Python version: 3.7.16 (default, Jan 17 2023, 22:20:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-161-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.6.55
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB
GPU 2: Tesla V100-PCIE-32GB
GPU 3: Tesla V100-PCIE-32GB
GPU 4: Tesla V100-PCIE-32GB
GPU 5: Tesla V100-PCIE-32GB
GPU 6: Tesla V100-PCIE-32GB
GPU 7: Tesla V100-PCIE-32GB

Nvidia driver version: 510.85.02
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.6
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              104
On-line CPU(s) list: 0-103
Thread(s) per core:  2
Core(s) per socket:  26
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz
Stepping:            7
CPU MHz:             3000.033
CPU max MHz:         4000.0000
CPU min MHz:         1000.0000
BogoMIPS:            4200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-25,52-77
NUMA node1 CPU(s):   26-51,78-103
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==1.6.5
[pip3] torch==1.13.0a0+gitd922c29
[pip3] torchaudio==0.9.0
[pip3] torchmetrics==0.11.0
[pip3] torchvision==0.10.0+cu111
[conda] cudatoolkit               11.3.1               h2bc3f7f_2    defaults
[conda] cudatoolkit-dev           11.6.0               h72bdee0_5    conda-forge
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] pytorch-lightning         1.6.5                    pypi_0    pypi
[conda] torch                     1.13.0a0+gitd922c29          pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchvision               0.10.0+cu111             pypi_0    pypi

cc @ptrblck

### PR DESCRIPTION
**Pull request by Shan19900305**
Fixes #106941

### CODE REVIEW

**Comment by Shan19900305** [comment]
After align formula, the results of batch_norm_elementwise_cuda are same in those mode, include Impl::Contiguous, Impl::General and Impl::ChannelsLast.

`import torch

x = torch.Tensor([[[[[-6.8167e+35]]]]]).cuda()
mean = torch.Tensor([4.8408]).cuda()
invsted = torch.Tensor([0.1174]).cuda()
weight = torch.Tensor([-2281.7122]).cuda()
bias = torch.Tensor([1.9951]).cuda()
out_cuda=torch.batch_norm_elemt(x, weight, bias, mean, invsted, 0)
print(out_cuda)`

**result:**
python test_bn.py 
tensor([[[[[inf]]]]], device='cuda:0')

**Comment by colesbury** [comment]
@Shan19900305, what is the equivalent code for `Impl::Contiguous`? It's not clear to me that this makes the two cases behave the same.

In general, we don't necessarily produce the same bitwise exact result for contiguous and non-contiguous inputs.

**Comment by Shan19900305** [comment]
> @Shan19900305, what is the equivalent code for `Impl::Contiguous`? It's not clear to me that this makes the two cases behave the same.
----Shan： The original cuda code is below, the position of gamma(weight) may cause different result of same inputs.
`In Impl::Contiguous
    for (index_t feature = threadIdx.x; feature < fs; feature += blockDim.x) { o[feature] = static_cast<input_scalar_t>(gamma * (i[feature] - mean) * invstd + beta); }
In Impl::General
      gpu_kernel(iter, [] GPU_LAMBDA (scalar_t input, acc_t weight, acc_t bias, acc_t mean, acc_t invstd) -> scalar_t { return ((input - mean) * invstd) * weight + bias; });`

> In general, we don't necessarily produce the same bitwise exact result for contiguous and non-contiguous inputs.
----Shan： Why?  In this  case,inf or 1.8260e+38 are very different for trainning.
`In Contiguous mode:
python test_bn.py
tensor([[[[[inf]]]]], device='cuda:0')
In General mode: (U can modify batch_norm_choose_impl function for always return Impl::General )
python test_bn.py
tensor([[[[[1.8260e+38]]]]], device='cuda:0')`

**Review by colesbury — APPROVED** [review]
OK, I guess this is fine...?

We don't normally care about getting the bitwise exact same results from contiguous and non-contiguous inputs because we prioritize performance and it's frequently not possible for complex operations without first making non-contiguous inputs contiguous.

In this case, the operation seems simple enough that this suffices.

**Pull request closed without merging**
