### PR TITLE
Move Allocator and Device to ATen/core

### PR DESCRIPTION
**Pull request by ezyang**
Differential Revision: D9466602

### CODE REVIEW

**Review by gchanan — APPROVED** [review]
would git be able to track the file moves if you didn't rename at the same time?

**Comment by ezyang** [comment]
> would git be able to track the file moves if you didn't rename at the same time?

Yeah, I think if it's exactly the same contents, it tracks it.

**Comment by ezyang** [comment]
Commandeered by @jerryzh168

**Comment by ezyang** [comment]
obsoleted by #10798

**Pull request closed without merging**
