### PR TITLE
[build] Remove setup_requires and tests_require from setup.py for FULL_CAFFE2

### PR DESCRIPTION
**Pull request by orionr**
In my environment, it looks like setup.py hangs when running

```
FULL_CAFFE2=1 python setup.py build_deps
```

Removing this fixes things, but we might also want to look at `tests_require`, which came over from `setup_caffe2.py`.

cc @pjh5

### CODE REVIEW

**Comment by ezyang** [comment]
This is on a devserver? Usually a hang is because your proxy settings are wrong.

(Anyway, I agree: cool build systems don't connect to the network when you run them.)

**Review by ezyang — APPROVED** [review]

**Comment by pjh5** [comment]
I think @ezyang is right, it'll try to install these packages before it starts building. But this wasn't buying us much anyways

**Comment by Yangqing** [comment]
Which packages is it trying to install? Is it due to the NNPACK dependency?

**Comment by Yangqing** [comment]
Also, I am a bit curious why we need pytest-runner for setup, since we don't run test during setup time I think...?

**Comment by orionr** [comment]
Good point @ezyang - likely proxy in this case. git should be setup correctly, so hopefully NNPACK is a non-issue. Generally, I would like to avoid network calls when running this, though, since it's a bit weird to do so. @bddppq and @pjh5 should I remove test_requires as well?

**Comment by ezyang** [comment]
A few points:

1. PyTorch *does* work with pytest, at least if you use pytest to invoke tests individually. I've used it in the past because it's test filtering is superior to the default Python test runner

2. There isn't really any reason we should force pytest-runner on users on install: it's just for tests (so, if a user is not interested in running tests, it will still try to install it), and it's not even essential to run tests (you can always use the default runner)

So, I support this patch as written, just not for the reasons originally proffered.

**Comment by bddppq** [comment]
@ezyang `pytest` does not work in PyTorch when invoking from the root directory if tests are not invoked individually.

**Comment by orionr** [comment]
At this point I'm going to remove `test_requires` too. I'm a bit concerned about all of the additional deps in `install_requires` as well, especially since we want to have FULL_CAFFE2=1 in all cases shortly. Is it better to just not have these (similar to PyTorch) and just have the user install them as needed. Or, alternatively, have them in requirements.txt. I like that last option, honestly.

**Comment by pjh5** [comment]
I think that install_requires affects wheel installs, causing pip to install the needed dependencies before installing the wheel. It can be moved to requirements.txt as well, though I think requirements.txt is simply convention and not used by pip itself

**Pull request closed without merging**
