### PR TITLE
[jit] Cloning constants in ClassType

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#32371 [jit] Cloning constants in ClassType**

Summary:
After we add constants to ClassType, we didn't update clone to
clone the constants, this PR adds the support
fixes: https://github.com/pytorch/pytorch/issues/32368

Test Plan:
python test/test_jit.py

Reviewers:
suo
Subscribers:

Tasks:

Tags:

Differential Revision: [D19564378](https://our.internmc.facebook.com/intern/diff/D19564378)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit ff18647d:


**None of the build failures appear to be your fault**.

* **1/1** recognized as flaky :snowflake:
    * Re-run these jobs?


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=ff18647d7c03ed82f67ac2236a805c80e2a4ad0c).

### :snowflake: 1 failure recognized as flaky
The following build failures have been detected as flaky and **may not be your fault**:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4293423) caffe2_onnx_py3_6_clang7_ubuntu16_04_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=87924721) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=87924721)) :snowflake:
<details>
<summary>
<code>Jan 17 21:59:44 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_reshape Fatal Python error: Segmentation fault</code>
</summary>

```
Jan 17 21:59:44 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_constant_fold_transpose_matmul PASSED [ 99%] 
Jan 17 21:59:44 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_constant_fold_unsqueeze PASSED [ 99%] 
Jan 17 21:59:44 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_error_on_data_parallel PASSED [ 99%] 
Jan 17 21:59:44 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_is_in_onnx_export PASSED [ 99%] 
Jan 17 21:59:44 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_strip_doc_string PASSED [ 99%] 
Jan 17 21:59:44 test/onnx/test_utility_funs.py::TestUtilityFuns_opset11::test_validate_dynamic_axes_invalid_input_output_name PASSED [ 99%] 
Jan 17 21:59:44 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_concat PASSED [ 99%] 
Jan 17 21:59:44 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_div PASSED [ 99%] 
Jan 17 21:59:44 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_lstm PASSED [ 99%] 
Jan 17 21:59:44 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_mul PASSED [ 99%] 
Jan 17 21:59:44 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_reshape Fatal Python error: Segmentation fault 
Jan 17 21:59:44  
Jan 17 21:59:44 Current thread 0x00007f367b5bc700 (most recent call first): 
Jan 17 21:59:44   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 43 in repr_instance 
Jan 17 21:59:44   File "/usr/lib/python3.6/reprlib.py", line 65 in repr1 
Jan 17 21:59:44   File "/usr/lib/python3.6/reprlib.py", line 55 in repr 
Jan 17 21:59:44   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 36 in repr 
Jan 17 21:59:44   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 67 in saferepr 
Jan 17 21:59:44   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 655 in repr_args 
Jan 17 21:59:44   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 736 in repr_traceback_entry 
Jan 17 21:59:44   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 777 in repr_traceback 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by suo — CHANGES_REQUESTED** [review]
see my comment on https://github.com/pytorch/pytorch/issues/32519, I feel we need to rethink the clone/copy interface to be more clear and consistent.

**Comment by jerryzh168** [comment]
@suo I think you are talking about `clone_instance`, `clone` is more of an internal API, we should probably hide this from user
This PR is needed for https://github.com/pytorch/pytorch/pull/32379, can we unblock that first and make the API correct in a separate PR?

**Comment by suo** [comment]
@jerryzh168 By what measure is `clone()` more internal than `clone_instance()`? `clone()` is public on `script::Module`, it is what is invoked by `ScriptModule.copy()`, and `clone_instance()` isn't bound into Python at all. 

In the future we need to be much more careful about making correct public APIs.

**Review by suo — APPROVED** [review]
accepting to unblock, the changes look fine

**Comment by jerryzh168** [comment]
> @jerryzh168 By what measure is `clone()` more internal than `clone_instance()`? `clone()` is public on `script::Module`, it is what is invoked by `ScriptModule.copy()`, and `clone_instance()` isn't bound into Python at all.
> 
> In the future we need to be much more careful about making correct public APIs.

Oh I see, I thought it was just for quantization

**Pull request closed without merging**
