### PR TITLE
Fix TypeError when itering NoneType in instantiate_device_type_tests()

### LINKED ISSUE #134454: TypeError occurs for newly added changes in ``instantiate_device_type_tests()``
### 🐛 Describe the bug

After commit [cdb9c7d](https://github.com/pytorch/pytorch/commit/cdb9c7d2283a31d3a7f96c4c7c12c0620feb9242) has been merged, it results in some errors for our 3rd-party downstream devices when running testing cases using ``instantiate_device_type_tests()`` method.

The sample demo as follows:
```Python
import torch
import torch_backend  # Your 3rd-party device's extension

from torch.testing._internal.common_device_type import (
    instantiate_device_type_tests,
)
from torch.testing._internal.common_utils import (
    run_tests,
    TestCase,
)


class TestBinaryUfuncs(TestCase):
    def test_abc(self,):
        pass


instantiate_device_type_tests(TestBinaryUfuncs, globals())

if __name__ == "__main__":
    run_tests()
```

Then running the demo will throws: `TypeError: 'NoneType' object is not iterable`:
```
  File "/test/test_binary_ufuncs_copy.py", line 18, in <module>
    instantiate_device_type_tests(TestBinaryUfuncs, globals())
  File "/venv/main/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 902, in instantiate_device_type_tests
    for base in get_desired_device_type_test_bases(
  File "/venv/main/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 815, in get_desired_device_type_test_bases
    desired_device_type_test_bases = filter_desired_device_types(
  File "/venv/main/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 753, in filter_desired_device_types
    except_for = [
TypeError: 'NoneType' object is not iterable

```

The reason is that using iter for ``except_for`` and ``only_for`` but they are ``None`` by default in https://github.com/shink/pytorch/blob/main/torch/testing/_internal/common_device_type.py#L754.

### Versions

torch: 2.5.0.dev20240825+cpu

cc @NmomoN @mengpenghui @fwenguang @cdzhan @1274085042 @PHLens

### PR DESCRIPTION
**Pull request by wizzniu**
Fixes #134454 

Fix TypeError introduced by https://github.com/pytorch/pytorch/pull/133082, which uses iter for NoneType of default args ``except_for`` and ``only_for``.

cc @shink @FFFrog @albanD

### CODE REVIEW

**Review by shink — APPROVED** [review]

**Comment by shink** [comment]
Thanks!

**Review by albanD — APPROVED** [review]
SGTM

**Pull request closed without merging**
