### PR TITLE
std_mean, var_mean : update skip message

### PR DESCRIPTION
**Pull request by kshitij12345**
Reference : https://github.com/pytorch/pytorch/issues/69991

~~It just worked :)~~ (but not on ASAN :( )

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
Fair play.

Now, I think that all these composite compliance tests should be xfails. I reckon that we'd find that many of them are just fixed when we fix other tests and so on.

**Review by lezcano — CHANGES_REQUESTED** [review]
Actually, no, Asan is failing:
https://github.com/pytorch/pytorch/runs/6365731885?check_suite_focus=true
we just need to make this test either not go through asan or put the correct asan flag somewhere in the backward of this function.

**Comment by kshitij12345** [comment]
Ah I see. Looks like this is why it was skipped instead.

**Comment by ngimel** [comment]
Please leave a comment about why these tests must be skipped instead of xfailed, so that next persons doesn't have to go through this

**Comment by kshitij12345** [comment]
@ngimel have updated the skip message. PTAL

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
