### PR TITLE
(torch/elastic) add fqdn hostname to error printout

### LINKED ISSUE #63174: [dist] log node's hostname plus rank in the exception message
## 🚀 Feature

Would it be possible to log (1) the hostname and (2) the rank with the exceptions?

## Motivation

Currently it's very difficult to diagnose which node is faulty and remove it from the slurm pool.

For example a multi-node training has crashed with:

```
    torch.autograd.backward(tensors=(outputs, ), grad_tensors=(grad_tensors, ))
  File "/gpfswork/rech/six/commun/conda/tr1-13B/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: transform: failed to synchronize: cudaErrorECCUncorrectable: uncorrectable ECC error encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: uncorrectable ECC error encountered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1616554793803/work/c10/cuda/CUDACachingAllocator.cpp:733 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x1500fb4d42f2 in /gpfswork/rech/six/commun/conda/tr1-13B/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x1500fb4d167b in /gpfswork/rech/six/commun/conda/tr1-13B/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x809 (0x1500fb72d219 in /gpfswork/rech/six/commun/conda/tr1-13B/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x1500fb4bc3a4 in /gpfswork/rech/six/commun/conda/tr1-13B/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x6e0e5a (0x150152432e5a in /gpfswork/rech/six/commun/conda/tr1-13B/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x6e0ef1 (0x150152432ef1 in /gpfswork/rech/six/commun/conda/tr1-13B/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x1a6b5a (0x56434fce9b5a in /gpfswork/rech/six/commun/conda/tr1-13B/bin/python)
frame #7: <unknown function> + 0x110b7c (0x56434fc53b7c in /gpfswork/rech/six/commun/conda/tr1-13B/bin/python)
frame #8: <unknown function> + 0x1105b9 (0x56434fc535b9 in /gpfswork/rech/six/commun/conda/tr1-13B/bin/python)
frame #9: <unknown function> + 0x1105a3 (0x56434fc535a3 in /gpfswork/rech/six/commun/conda/tr1-13B/bin/python)
frame #10: <unknown function> + 0x1105a3 (0x56434fc535a3 in /gpfswork/rech/six/commun/conda/tr1-13B/bin/python)
frame #11: <unknown function> + 0x177917 (0x56434fcba917 in /gpfswork/rech/six/commun/conda/tr1-13B/bin/python)
frame #12: PyDict_SetItemString + 0x4c (0x56434fcbd86c in /gpfswork/rech/six/commun/conda/tr1-13B/bin/python)
frame #13: PyImport_Cleanup + 0xac (0x56434fd2f0ec in /gpfswork/rech/six/commun/conda/tr1-13B/bin/python)
frame #14: Py_FinalizeEx + 0x79 (0x56434fd95589 in /gpfswork/rech/six/commun/conda/tr1-13B/bin/python)
frame #15: Py_RunMain + 0x1bc (0x56434fd988fc in /gpfswork/rech/six/commun/conda/tr1-13B/bin/python)
frame #16: Py_BytesMain + 0x39 (0x56434fd98ce9 in /gpfswork/rech/six/commun/conda/tr1-13B/bin/python)
frame #17: __libc_start_main + 0xf3 (0x150183467873 in /lib64/libc.so.6)
frame #18: <unknown function> + 0x1f7847 (0x56434fd3a847 in /gpfswork/rech/six/commun/conda/tr1-13B/bin/python)
```

After restarting the training it failed again in a different code path, this time with:

```
    torch.distributed.barrier()
  File "/gpfswork/rech/six/commun/conda/tr1-13B/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: CUDA error: out of memory
```

I suspect that that one gpu on one of the nodes went bunkers on the hardware level, which crashed the training. And of course since the node hasn't been rebooted, it was still unusable. So the next training most likely hit the same node (this is slurm env) and of course it was still broken, hence the breakage again, just happened at a different code path.

In this circumstance it'd have been good to know if the exception happened on the same hostname + rank, as it'd then help us to exclude that node from future trainings  and not hit it again., or request its reboot

Otherwise, we are very likely to hit that node again and again.

Thank you!

p.s. I wonder if some of this info I'm asking for would have showed up in the 1.9's elastic version of the launcher. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

### PR DESCRIPTION
**Pull request by kiukchung**
Summary:
closes https://github.com/pytorch/pytorch/issues/63174

Does a few things:

1. adds hostname to the error report
2. moves the "root cause" section to the end (presumably since the logs are being "tailed" we want the root cause to appear at the end)
3. moves redundant error info logging to debug
4. makes the border max 60 char in length and justifies left for the header

NOTE: YOU HAVE TO annotate your main function with torch.distributed.elastic.multiprocessing.errors.record, otherwise no traceback is printed (this is because python exception propagation does NOT work out of the both for IPC - hence the extra record annotation).

Test Plan:
Sample

```
============================================================
run_script_path FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2021-10-05_17:37:22
  host      : devvm4955.prn0.facebook.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3296201)
  error_file: /home/kiuk/tmp/elastic/none_3_lsytqe/attempt_0/0/error.json
  traceback :
  Traceback (most recent call last):
    File "/tmp/jetter.xr3_x6qq/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 372, in wrapper
      return f(*args, **kwargs)
    File "main.py", line 28, in main
      raise RuntimeError(args.throws)
  RuntimeError: foobar

============================================================
```

Differential Revision: D31416492

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

### CODE REVIEW

**Review by cbalioglu — APPROVED** [review]
LGTM

**Comment by stas00** [comment]
Thank you for working on that, @kiukchung - this is great!

Could we please add a cl arg then to enable `torch.distributed.elastic.multiprocessing.errors.record`?

**Comment by kiukchung** [comment]
> Could we please add a cl arg then to enable torch.distributed.elastic.multiprocessing.errors.record and not need to modify the code?

Its not something we can enable from commandline unfortunately. the launcher now launches the training script copies via `subprocess.Popen`. So you'd have to actually do this in the training script main function. If you don't have access to it, then the tracebacks won't be available but it does not affect the correctness. Instead it'll print something like:

```
============================================================
run_script_path FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2021-10-05_17:37:22
  host      : devvm4955.prn0.facebook.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3296201)
  error_file: /home/kiuk/tmp/elastic/none_3_lsytqe/attempt_0/0/error.json
  traceback :
  Process failed with exitcode 1
============================================================
```

You could run the script with `$ python -m torch.distributed.run --run_path script.py` which uses the `runpy` module to run the script from within the main interpreter in which case it'll annotate the wrapper function but the downside is that you'll get a longer stack trace:

```
============================================================
run_script_path FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2021-10-05_18:02:08
  host      : devvm4955.prn0.facebook.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3417837)
  error_file: /home/kiuk/tmp/elastic/none_mi6drml2/attempt_0/0/error.json
  traceback :
  Traceback (most recent call last):
    File "/tmp/jetter.myl31u5c/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 372, in wrapper
      return f(*args, **kwargs)
    File "/tmp/jetter.myl31u5c/torch/distributed/run.py", line 673, in run_script_path
      runpy.run_path(sys.argv[0], run_name="__main__")
    File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 265, in run_path
      return _run_module_code(code, init_globals, run_name,
    File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 97, in _run_module_code
      _run_code(code, mod_globals, init_globals,
    File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "main.py", line 34, in <module>
      main()
    File "main.py", line 28, in main
      raise RuntimeError(args.throws)
  RuntimeError: foobar
```

> Could we please document this feature?

1. https://pytorch.org/docs/stable/elastic/errors.html
2. the launcher has been fitted with a warning message with detailed information on how to add @record to their main:

```
CHILD PROCESS FAILED WITH NO ERROR_FILE

Child process 3421311 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
```

If you have additional suggestions, please feel free to send us a PR.

**Comment by stas00** [comment]
> > Could we please add a cl arg then to enable torch.distributed.elastic.multiprocessing.errors.record and not need to modify the code?
[...]

Thank you for clarifying that host/rank printing has nothing to do with `record` decoration.

Won't this decorator be a problem if the program isn't run under distributed?

- Should there be a way to activate it dynamically if the programs knows it's being run under dist?
- And additionally it's an issue with backward compatibility, how do you add a decorator which may or may not exist?

> > Could we please document this feature?
> 
>     1. https://pytorch.org/docs/stable/elastic/errors.html

It'd help users a lot if https://pytorch.org/docs/stable/distributed.html included a section linking to various elastic docs like the above. Otherwise, the switch was done, and it feels like the user should somehow know that they should be searching for detailed docs of elastic, but not knowing they exist or where to find those.
 
>     2. the launcher has been fitted with a warning message with detailed information on how to add @record to their main:

> CHILD PROCESS FAILED WITH NO ERROR_FILE
> 
> Child process 3421311 (local_rank 0) FAILED (exitcode 1)
> Error msg: Process failed with exitcode 1
> Without writing an error file to <N/A>.
> While this DOES NOT affect the correctness of your application,
> no trace information about the error will be available for inspection.
> Consider decorating your top level entrypoint function with
> torch.distributed.elastic.multiprocessing.errors.record. Example:

Please don't tell it'll print this warning on each process, since at times all child processes will fail - multiple that 1024... ouch!

**Comment by kiukchung** [comment]
yeah - having thought about this last night - this is an interesting point. We typically operate with the assumption that the end pytorch user owns their training script (at least the main module) and hence knows what pytorch version they will be running the script with. If the script author/owner is different from the script invoker then it does raise the question as to whether the script's dev (knowing that they don't control the run environment) needs to author the script with BC in mind or perhaps just check `torch.__version__` and fail fast if the versions don't match.

**Comment by stas00** [comment]
A concrete example is [HF Transformers example scripts](https://github.com/huggingface/transformers/tree/master/examples/pytorch) that many users use as is - and while we call those examples, they are used as production code by many users. Surely they can modify these scripts if they want to.

But the script is the same otherwise, and it can be invoked in many different ways - w/ dist or w/o and it dynamically figures out which right thing to do at run time.

We also use those scripts as is in the test suite, e.g. I have a whole set of these being called to test the Deepspeed integration, and the test suite should be able to work not just with pt-1.9.0 - that's why if I were to use that decorator I'd have to use a conditional wrapper to make it not fail for pt<1.9. So the workaround would do.

I'm thinking that if files are used to communicate tracebacks, the perhaps the same approach can be used to distribute configuration across nodes? Then each process will know of any nuances... Potentially something for the future discussions and not for 1.10.

**Pull request closed without merging**
