### PR TITLE
functionalization: update is_up_to_date() logic

### PR DESCRIPTION
**Pull request by bdhirsh**
See more details at the comment [here](https://github.com/pytorch/functorch/pull/235/files#r753556480).

In the functionalization pass, we need to sync updates to each tensor input before calling out-of-place operators, so they don't run on stale data. There's an `is_up_to_date()` function that checks if a tensor is eligible to be synced, which previously had two criteria:
- Does it have any live aliases (`FunctionalTensorWrapper::is_aliased()`)
- is the current tensor's "generation" staler than its backing storage

We don't actually need the first of the two checks - the second should be sufficient. The first check is also problematic - it's implemented by checking the `use_count` on the underlying `Storage` object, which means that it only tracks live views. It will incorrectly return False if we take out a view, mutate the view, and then let the view tensor go out of scope.

Confirmed that tests pass + conditional functionalization still works after this change.

Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#68881 functionalization: update is_up_to_date() logic**

Differential Revision: [D32647614](https://our.internmc.facebook.com/intern/diff/D32647614)

### CODE REVIEW

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32647614).

**Review by zou3519 — APPROVED** [review]
LGTM, but could we add some C++ unit tests to prevent regressions? (Or figure out how to expose this logic to Python)

I think what we want to test here is the following (pseudocode):
```
import torch
from functionalize

def bar(y):
    y_view = y.view(-1)
    y_view.add_(1)

def foo(x):
    bar(x)
    # Test that x.is_up_to_date() is false
    z = x + 1
    return z

print(functionalize(foo)(torch.ones(2)))
```

**Comment by bdhirsh** [comment]
```
import torch
from functionalize

def bar(y):
    y_view = y.view(-1)
    y_view.add_(1)

def foo(x):
    bar(x)
    # Test that x.is_up_to_date() is false
    z = x + 1
    return z
```
print(functionalize(foo)(torch.ones(2)))


Agreed. If you're okay with an end-to-end test that tests this behavior, we should be able to exercise that logic directly from python in `test/test_functionalization.py`. If `x.is_up_to_date()` incorrectly returned true in that scenario above, then the output of the program would be wrong because we'd use the old, stale value of x to compute z.

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32647614).

**Comment by zou3519** [comment]
> Agreed. If you're okay with an end-to-end test that tests this behavior, we should be able to exercise that logic directly from python in test/test_functionalization.py. If x.is_up_to_date() incorrectly returned true in that scenario above, then the output of the program would be wrong because we'd use the old, stale value of x to compute z.

End-to-end test in Python sounds good

**Pull request closed without merging**
