### PR TITLE
Docs: fix docstring errors in ddp_comm_hooks

### PR DESCRIPTION
**Pull request by mingxzhao**
ddp_zero_hook

Pre

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:1 at module level:
        D100: Missing docstring in public module
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:26 in private function `_perform_local_step`:
        D401: First line should be in imperative mood (perhaps 'Perform', not 'Performs')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:100 in private function `_save_ddp_bucket_info`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:100 in private function `_save_ddp_bucket_info`:
        D400: First line should end with a period (not 'e')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:100 in private function `_save_ddp_bucket_info`:
        D401: First line should be in imperative mood (perhaps 'Save', not 'Saves')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:132 in private function `_hook_with_zero_step_setup`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:132 in private function `_hook_with_zero_step_setup`:
        D400: First line should end with a period (not 'd')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:132 in private function `_hook_with_zero_step_setup`:
        D401: First line should be in imperative mood (perhaps 'Encapsulate', not 'Encapsulates')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:174 in public function `hook_with_zero_step`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:174 in public function `hook_with_zero_step`:
        D400: First line should end with a period (not '`')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:174 in public function `hook_with_zero_step`:
        D401: First line should be in imperative mood (perhaps 'Modify', not 'Modifies')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:246 in private nested function `hook_with_zero_fn`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:246 in private nested function `hook_with_zero_fn`:
        D400: First line should end with a period (not 'd')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:246 in private nested function `hook_with_zero_fn`:
        D401: First line should be in imperative mood (perhaps 'Return', not 'Returns')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:333 in public function `hook_with_zero_step_interleaved`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:333 in public function `hook_with_zero_step_interleaved`:
        D400: First line should end with a period (not '`')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:333 in public function `hook_with_zero_step_interleaved`:
        D401: First line should be in imperative mood (perhaps 'Modify', not 'Modifies')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:406 in private nested function `hook_with_zero_interleaved_fn`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:406 in private nested function `hook_with_zero_interleaved_fn`:
        D400: First line should end with a period (not 'd')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:406 in private nested function `hook_with_zero_interleaved_fn`:
        D401: First line should be in imperative mood (perhaps 'Return', not 'Returns')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:421 in private nested function `zero_step`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:421 in private nested function `zero_step`:
        D400: First line should end with a period (not '`')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:421 in private nested function `zero_step`:
        D401: First line should be in imperative mood (perhaps 'Perform', not 'Performs')
23

Post

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/ddp_zero_hook.py:1 at module level:
        D100: Missing docstring in public module
1

debugging_hooks.py

Pre

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/debugging_hooks.py:1 at module level:
        D100: Missing docstring in public module
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/debugging_hooks.py:10 in public function `noop_hook`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/debugging_hooks.py:10 in public function `noop_hook`:
        D400: First line should end with a period (not ',')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/debugging_hooks.py:10 in public function `noop_hook`:
        D401: First line should be in imperative mood; try rephrasing (found 'This')
4

Post

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/debugging_hooks.py:1 at module level:
        D100: Missing docstring in public module
1

default_hooks.py 

Pre

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py:1 at module level:
        D100: Missing docstring in public module
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py:11 in private function `_allreduce_fut`:
        D300: Use """triple double quotes""" (found "-quotes)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py:27 in public function `allreduce_hook`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py:27 in public function `allreduce_hook`:
        D400: First line should end with a period (not '`')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py:27 in public function `allreduce_hook`:
        D401: First line should be in imperative mood; try rephrasing (found 'This')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py:46 in public function `fp16_compress_hook`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py:46 in public function `fp16_compress_hook`:
        D400: First line should end with a period (not 'n')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py:46 in public function `fp16_compress_hook`:
        D401: First line should be in imperative mood; try rephrasing (found 'This')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py:115 in public function `fp16_compress_wrapper`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py:115 in public function `fp16_compress_wrapper`:
        D400: First line should end with a period (not 'n')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py:115 in public function `fp16_compress_wrapper`:
        D401: First line should be in imperative mood; try rephrasing (found 'This')
11

Post 

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py:1 at module level:
        D100: Missing docstring in public module
1

__init__.py

Pre

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/__init__.py:1 at module level:
        D104: Missing docstring in public package
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/__init__.py:27 in private function `_powerSGD_comm_hook_wrapper`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/__init__.py:27 in private function `_powerSGD_comm_hook_wrapper`:
        D400: First line should end with a period (not ',')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/__init__.py:40 in public class `DDPCommHookType`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/__init__.py:40 in public class `DDPCommHookType`:
        D400: First line should end with a period (not '`')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/__init__.py:91 in public function `register_ddp_comm_hook`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/__init__.py:91 in public function `register_ddp_comm_hook`:
        D400: First line should end with a period (not '`')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/__init__.py:91 in public function `register_ddp_comm_hook`:
        D401: First line should be in imperative mood (perhaps 'Register', not 'Registers')
8

Post

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/__init__.py:1 at module level:
        D104: Missing docstring in public package
1

mixed_precision_hooks.py

Pre

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/mixed_precision_hooks.py:1 at module level:
        D100: Missing docstring in public module
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/mixed_precision_hooks.py:11 in private class `_AllreduceUpcastHookState`:
        D204: 1 blank line required after class docstring (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/mixed_precision_hooks.py:11 in private class `_AllreduceUpcastHookState`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/mixed_precision_hooks.py:24 in private function `_reducer_allreduce_and_upcast_hook`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/mixed_precision_hooks.py:24 in private function `_reducer_allreduce_and_upcast_hook`:
        D400: First line should end with a period (not 'n')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/mixed_precision_hooks.py:24 in private function `_reducer_allreduce_and_upcast_hook`:
        D401: First line should be in imperative mood (perhaps 'Perform', not 'Performs')
6

Post

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/mixed_precision_hooks.py:1 at module level:
        D100: Missing docstring in public module
1

optimizer_overlap_hooks.py

Pre

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/optimizer_overlap_hooks.py:1 at module level:
        D100: Missing docstring in public module
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/optimizer_overlap_hooks.py:14 in private class `_OptimizerHookState`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/optimizer_overlap_hooks.py:47 in private function `_apply_optim_in_backward_hook`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/optimizer_overlap_hooks.py:47 in private function `_apply_optim_in_backward_hook`:
        D400: First line should end with a period (not 'p')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/optimizer_overlap_hooks.py:126 in private function `_hook_then_optimizer`:
        D200: One-line docstring should fit on one line with quotes (found 3)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/optimizer_overlap_hooks.py:126 in private function `_hook_then_optimizer`:
        D401: First line should be in imperative mood (perhaps 'Run', not 'Runs')
6

Post

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/optimizer_overlap_hooks.py:1 at module level:
        D100: Missing docstring in public module
1

post_localSGD_hook.py

Pre

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/post_localSGD_hook.py:1 at module level:
        D100: Missing docstring in public module
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/post_localSGD_hook.py:12 in public class `PostLocalSGDState`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/post_localSGD_hook.py:12 in public class `PostLocalSGDState`:
        D400: First line should end with a period (not ',')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/post_localSGD_hook.py:31 in public method `__init__`:
        D107: Missing docstring in __init__
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/post_localSGD_hook.py:53 in public method `maybe_increase_iter`:
        D102: Missing docstring in public method
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/post_localSGD_hook.py:68 in public function `post_localSGD_hook`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/post_localSGD_hook.py:68 in public function `post_localSGD_hook`:
        D400: First line should end with a period (not ',')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/post_localSGD_hook.py:68 in public function `post_localSGD_hook`:
        D401: First line should be in imperative mood; try rephrasing (found 'This')
8

Post

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/post_localSGD_hook.py:1 at module level:
        D100: Missing docstring in public module
1

powerSGD_hook.py

Pre
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:1 at module level:
        D100: Missing docstring in public module
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:20 in private function `_orthogonalize`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:41 in private function `_orthogonalize_gram_schmidt`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:41 in private function `_orthogonalize_gram_schmidt`:
        D401: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:75 in private function `_should_compress`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:75 in private function `_should_compress`:
        D400: First line should end with a period (not ',')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:75 in private function `_should_compress`:
        D401: First line should be in imperative mood (perhaps 'Return', not 'Returns')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:100 in private function `_report_compression_stats`:
        D200: One-line docstring should fit on one line with quotes (found 3)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:116 in public class `PowerSGDState`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:172 in public method `__init__`:
        D107: Missing docstring in __init__
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:268 in public method `__getstate__`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:268 in public method `__getstate__`:
        D401: First line should be in imperative mood (perhaps 'Return', not 'Returns')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:282 in public method `__setstate__`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:282 in public method `__setstate__`:
        D401: First line should be in imperative mood (perhaps 'Take', not 'Takes')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:294 in public method `maybe_increase_iter`:
        D102: Missing docstring in public method
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:306 in public method `compression_stats`:
        D400: First line should end with a period (not ':')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:306 in public method `compression_stats`:
        D401: First line should be in imperative mood (perhaps 'Return', not 'Returns')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:330 in public function `powerSGD_hook`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:330 in public function `powerSGD_hook`:
        D400: First line should end with a period (not 'n')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:330 in public function `powerSGD_hook`:
        D401: First line should be in imperative mood; try rephrasing (found 'This')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:638 in public function `batched_powerSGD_hook`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:638 in public function `batched_powerSGD_hook`:
        D400: First line should end with a period (not 'n')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:638 in public function `batched_powerSGD_hook`:
        D401: First line should be in imperative mood; try rephrasing (found 'This')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:753 in private nested function `create_low_rank_tensor`:
        D300: Use """triple double quotes""" (found "-quotes)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:753 in private nested function `create_low_rank_tensor`:
        D401: First line should be in imperative mood (perhaps 'Return', not 'Returns')
25

Post

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:1 at module level:
        D100: Missing docstring in public module
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py:175 in public method `__init__`:
        D107: Missing docstring in __init__
2

quantization_hooks.py

Pre

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/quantization_hooks.py:1 at module level:
        D100: Missing docstring in public module
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/quantization_hooks.py:48 in public function `quantization_pertensor_hook`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/quantization_hooks.py:48 in public function `quantization_pertensor_hook`:
        D400: First line should end with a period (not '`')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/quantization_hooks.py:48 in public function `quantization_pertensor_hook`:
        D401: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/quantization_hooks.py:122 in public function `quantization_perchannel_hook`:
        D205: 1 blank line required between summary line and description (found 0)
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/quantization_hooks.py:122 in public function `quantization_perchannel_hook`:
        D400: First line should end with a period (not '`')
/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/quantization_hooks.py:122 in public function `quantization_perchannel_hook`:
        D401: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
7

Post

/workspaces/pytorch/torch/distributed/algorithms/ddp_comm_hooks/quantization_hooks.py:1 at module level:
        D100: Missing docstring in public module
1
cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @kiukchung @lucasllc @svekars

### CODE REVIEW

**Review by wconstab — APPROVED** [review]

**Comment by mingxzhao** [comment]
Apologies I missed the error on my end, will fix asap.

**Comment by mingxzhao** [comment]
Apologies I seem to have made a mistake and force pushed into my branch. Is there any way to reverse this and re open the PR?

**Comment by mingxzhao** [comment]
@PaliC

**Comment by awgu** [comment]
@mingxzhao If it is not convenient to fix here, feel free to reopen a new PR, and I can approve that.

**Pull request closed without merging**
