### PR TITLE
[Quant][core][improvement] Separated implementations for quantized & non-quantized tensors in item

### PR DESCRIPTION
**Pull request by dzdang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #72333

Summary: 

This PR is part of a series of PRs addressing https://github.com/pytorch/pytorch/issues/54150,
related to using dispatcher for calls to quantized backends as opposed to if/else conditionals.
This particular PR separates the calls to quantized & non-quantized backends for item
using a dispatcher.

Test plan:
There are numerous tests in the suite that make use of torch.Tensor.item.
```
python test/run_test.py
```
can be used for comprehensive evaluation, or alternatively, b/c this PR should not affect torch.Tensor.item calls on non-quantized tensors,
we can specifically test on quantized tensors:
```
python test/test_quantization.py
```

Differential Revision: [D35517808](https://our.internmc.facebook.com/intern/diff/D35517808)

### CODE REVIEW

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34004298).

**Review by jerryzh168 — APPROVED** [review]

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34004298).

**Review by ezyang — CHANGES_REQUESTED** [review]
This looks wrong. The original seems to be a composite so you should use CompositeImplicitAutograd instead of CPU, CUDA, SparseCPU, SparseCUDA

**Comment by dzdang** [comment]
Closing this PR until dispatch keys become available

**Comment by ezyang** [comment]
@bdhirsh  's thing landed, dispatch keys available now

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35517808).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35517808).

**Pull request closed without merging**
