### PR TITLE
[CI] Upgrade xpu driver to LTS_803.29

### PR DESCRIPTION
**Pull request by mengfei25**
Upgrade xpu driver from 647.21  to LTS 803.29

Works for #114850

### CODE REVIEW

**Comment by mengfei25** [comment]
@chuanqi129 @EikanWang Please help have a review

**Review by chuanqi129 — APPROVED** [review]

**Review by EikanWang — APPROVED** [review]
LGTM

**Comment by chuanqi129** [comment]
Hi @huydhn could you please help to review this PR? And the current failure seems not relate with this PR change

**Review by huydhn — APPROVED** [review]
LGTM as the XPU jobs have passed, I will do a rebase as the base commit is a bit old and merge the change

**Pull request closed without merging**
