### PR TITLE
[S382174] Fix distributed debug w/ non-equal split

### PR DESCRIPTION
**Pull request by xw285cornell**
Summary:
In collectives, it's possible to have non-equal split that has a different implementation and the output tensor size will be different, e.g. https://www.internalfb.com/code/fbsource/[460afb1172b5]/fbcode/caffe2/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp?lines=3104. However, TORCH_DISTRIBUTED_DEBUG=DETAIL will assume the output tensor size is the same and does the check and will fail the job if they don't: https://fburl.com/code/mhte9ty8. c10d code should handle this.

Ideally we should check the input size across ranks and make sure they're the same. Maybe for next diff.

Test Plan: Test torchrec's TWRW w/ non-even split and it's working now.

Reviewed By: zhangruiskyline

Differential Revision: D52010942

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Review by kwen2501 — APPROVED** [review]
LGTM.
`dist.all_gather` supporting tensors of different shapes is a newer feature than `ProcessGroupWrapper`, thus this update looks reasonable to me.

**Review by fegin — APPROVED** [review]
Thanks for the fix!

**Review by XilunWu — APPROVED** [review]
lgtm. Curious why we forbid un-even split. Was it not supported by then and later on we added the support but forgot to remove the check? Is this SEV the first time we hit uneven split?

**Comment by XilunWu** [comment]
> LGTM. `dist.all_gather` supporting tensors of different shapes is a newer feature than `ProcessGroupWrapper`, thus this update looks reasonable to me.

I see, so we forgot to change `PGWrapper` after adding `all_gather` support. But it has been a while since we have uneven `all_gather` right? Why don't we see the issue until now?

**Comment by xw285cornell** [comment]
i think because no one has combined detail debug + non even shard I guess.. :)

**Pull request closed without merging**
