### PR TITLE
Supporting old-style classes in torch.is_tensor and torch.is_storage

### PR DESCRIPTION
**Pull request by vadimkantorov**
This change makes `torch.is_tensor` and `torch.is_storage` resilient to inputs of old-style class instances (still may be common in Python 2 codebases) that do not have `__class__` attribute.

Very welcoming the feedback :) It's somehow my first PR ever.

Details how the old behavior broke serialization is here: https://github.com/pytorch/pytorch/issues/1003

### CODE REVIEW

**Comment by apaszke** [comment]
Doesn't `type(obj)` do the same for old style classes?

**Comment by vadimkantorov** [comment]
In Python 2.7.6:

```python
class A(object):
     pass

class B:
     pass
```

```
>>> type(B)
<type 'classobj'>
>>> type(A)
<type 'type'>
>>> A.__class__
<type 'type'>
>>> B.__class__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: class B has no attribute '__class__'
```

The problem in serializer seems to be that it called torch.is_storage on class itself, not class instance.

**Comment by vadimkantorov** [comment]
Tested locally, now works:
```python
class A:
    pass

torch.save(A(), 'a.pth')
```

Should I add any tests?

**Comment by apaszke** [comment]
Yes please! Just add a test case that opens a temporary file, saves an old-style class to it, and loads it again.

**Comment by soumith** [comment]
vadim, your git history on this PR is also massively screwed up....

**Comment by vadimkantorov** [comment]
@soumith I will add the test and will try to rebase + squash the commits.

**Comment by soumith** [comment]
fixed in #1226

**Comment by vadimkantorov** [comment]
@soumith I'll learn how to rebase on another pr! promise!

**Comment by vadimkantorov** [comment]
@soumith I learned how to rebase a pr: https://github.com/pytorch/pytorch/pull/27621 :) big thanks to @ezyang for help with that pr

**Pull request closed without merging**
