### PR TITLE
[inductor] Enable FX graph caching in OSS by default

### PR DESCRIPTION
**Pull request by masnesral**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125863

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by eellison — APPROVED** [review]
🚀 🚀 🚀

What bugs do we still have remaining ? @oulgen was looking into a strides one, right, but I guess that's it ?

**Comment by oulgen** [comment]
@masnesral yep, I still havent looked at the stride one and removing cache disable from more unit tests revealed bugs too, so perhaps lets hold off on this until we prove the cache internally?

**Comment by eellison** [comment]
Okay, good with me. let's fix the remaining unittest bugs. although typically @oulgen we enable in oss first then do internally

**Comment by masnesral** [comment]
@oulgen if you want to point me to any other known failures you've surfaced I'll gladly investigate

**Comment by oulgen** [comment]
Clarifying: The only real problem that we are aware of is
```
[trainer0]:    assert_size_stride(bmm_9, (17, s0, 512), (4081152, 512, 1))
[trainer0]:AssertionError: expected size 17==17, stride 4022784==4081152 at dim=0
```
I do not yet have a repro..

**Review by oulgen — APPROVED** [review]

**Review by eellison — APPROVED** [review]

**Pull request closed without merging**
