### PR TITLE
add script to run custom_op_tests manually

### PR DESCRIPTION
**Pull request by zdevito**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#18806 add script to run custom_op_tests manuall**

Addresses #18805

Differential Revision: [D14751862](https://our.internmc.facebook.com/intern/diff/D14751862)

### CODE REVIEW

**Comment by ezyang** [comment]
It would be good to make this more discoverable in some way.

**Comment by zdevito** [comment]
I feel like the way to make it discoverable, like for most of our tests, would be to have the CI report how run the failing test. I think that is way out of scope for this PR though.

**Comment by ezyang** [comment]
I think the bare minimum discoverability is to make the CI use this script to run the test. Otherwise it will bitrot the moment any aspect of this changes.

**Comment by yf225** [comment]
@zdevito Would it be possible to also change https://github.com/pytorch/pytorch/blob/4d676d53a67e610689afbb34deabcac6ba8b8c50/.jenkins/pytorch/test.sh#L179-L193 to use this script? This way can make this script the official way to run custom_op_tests, and we will be able to commit to maintaining it for the long term.

**Pull request closed without merging**
