### PR TITLE
Inherit 'torch.distributions.exp_family.ExponentialFamily' in MultivariateNormal Class

### LINKED ISSUE #69077: Why the `torch.distributions.MultivariateNormal` did not inherited `torch.distributions.ExponentialFamily`?
Should we apply it?

cc @fritzo @neerajprad @alicanb @nikitaved

### PR DESCRIPTION
**Pull request by nonconvexopt**
Fixes #69077
Made a PR to test CI.

### CODE REVIEW

**Comment by nonconvexopt** [comment]
@neerajprad Can you review this PR?

**Comment by neerajprad** [comment]
@nonconvexopt: Sorry for a late reply. From what I understand, the [ExponentialFamily](https://pytorch.org/docs/stable/_modules/torch/distributions/exp_family.html#ExponentialFamily) inheritance is only useful if we want to automatically get an implementation of the `entropy` by implementing the abstract methods - `_natural_params`, `_log_normalizer` and `_mean_carrier_measure`. This class already has an explicit entropy method implemented, so there's no advantage to inheriting from `ExponentialFamily` (we are not implementing the other methods as well). There are other distributions like Binomial which similarly don't inherit from `ExponentialFamily` for the same reason.

**Comment by nonconvexopt** [comment]
> 

Thank you for your detailed explanation. There are not much advantages of inheriting `ExponentialFamily`. I just thought that since MVN is exponential family distribution, it might be sensible to in herit `ExponentialFamily` class.

I hope to take a analysis on the codes and try to fit the requirements for `ExponentialFamily` in this PR later. Please consider it to merge it if it is acceptable.

**Comment by nonconvexopt** [comment]
Why only the `pr/pytorch-linux-bionic-rocm4.3.1-py3.6` keep fails?

**Comment by nonconvexopt** [comment]
@neerajprad This is a trivial change and I think you can merge it if it is beneficial to PyTorch.
If you don't think so, I will close and work on other thing.

**Pull request closed without merging**
