### PR TITLE
[dynamo] Bugfix for nn parameter construction

### PR DESCRIPTION
**Pull request by anijain2305**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #127721
* #126578
* #127972
* #127823
* __->__ #127806
* #127802
* #127785

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by jansel — APPROVED** [review]
Add test?

**Comment by anijain2305** [comment]
Test will be enabled with https://github.com/pytorch/pytorch/pull/126578

**Comment by anijain2305** [comment]
Closing in favor of https://github.com/pytorch/pytorch/pull/128001

**Pull request closed without merging**
