### PR TITLE
Use export_import=False in a specific test_ge_optimized() section.

### PR DESCRIPTION
**Pull request by skrah**
On Ubuntu 16.04, CUDA 9.2 with GeForce 1060, test_jit fails:

```
  ======================================================================
FAIL: test_ge_optimized (__main__.TestJit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_jit.py", line 241, in wrapper
    fn(*args, **kwargs)
  File "test_jit.py", line 1426, in test_ge_optimized
    self.run_ge_tests(True, False)
  File "test_jit.py", line 1418, in run_ge_tests
    optimize=optimize)
  File "test_jit.py", line 491, in checkTrace
    self.assertEqual(grads, grads_ge)
  File "/home/stefan/pytorch/test/common_utils.py", line 443, in assertEqual
    self.assertEqual(x_, y_, prec, message)
  File "/home/stefan/pytorch/test/common_utils.py", line 428, in assertEqual
    assertTensorsEqual(x, y)
  File "/home/stefan/pytorch/test/common_utils.py", line 420, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(1.5259e-05, dtype=torch.float32) not less than or equal to 1e-05
```

Allowing for a larger error (the magic `prec=3e-5` is already used in `test_fuse_batch_norm`) fixes the issue.

### CODE REVIEW

**Comment by soumith** [comment]
cc: @suo @zdevito are you comfortable with this?

**Comment by zdevito** [comment]
That function already has a `check_tolerance` input. If those checks need to change the tolerance, they should use that field, and then the specific test that is failing can have its tolerance raised. I don't think we should raise it universally.

**Comment by skrah** [comment]
Yes, it is a good idea to raise the tolerance locally.  I just saw that the offending test does not use the GPU, so it's a bit of a mystery why the test fails only here -- I have pretty standard hardware, (i5-8600K), standard compiler (gcc-5.4.0).

**Comment by skrah** [comment]
It turns out that the precision issue only happens in a specific test when `export_import=True`.

This is a short reproducer that reliably fails on my system:

```python
import math, io
import torch


def getExportImportCopy(m):
    buffer = io.BytesIO()
    torch.jit.save(m, buffer)
    buffer.seek(0)
    return torch.jit.load(buffer)

def allSum(vs):
    return sum(math.log(i + 2) * v.sum() for i, v in enumerate(vs) if v is not None)

def func(a, b):
    return a * b / (a - 2 * b) + b

torch.set_printoptions(precision=30)

tensor = torch.tensor
recording_inputs = [tensor([0.55619788169860839844], dtype=torch.float32, requires_grad=True),
                    tensor([0.25947844982147216797], dtype=torch.float32, requires_grad=True)]

ge1 = torch.jit.trace(func, recording_inputs, optimize=True)
ge2 = getExportImportCopy(ge1)

outputs_ge1 = ge1(*recording_inputs)
outputs_ge2 = ge2(*recording_inputs)
print(outputs_ge1, outputs_ge1.dtype)
print(outputs_ge2, outputs_ge2.dtype)

grad_ge1 = torch.autograd.grad(allSum(outputs_ge1), recording_inputs)
grad_ge2 = torch.autograd.grad(allSum(outputs_ge2), recording_inputs)
print(grad_ge1)
print(grad_ge2)
```

Output:

```
tensor([4.134815692901611328125000000000],
       grad_fn=<DifferentiableGraphBackward>) torch.float32
tensor([4.134815692901611328125000000000],
       grad_fn=<DifferentiableGraphBackward>) torch.float32
(tensor([-67.300117492675781250000000000000]), tensor([155.304672241210937500000000000000]))
(tensor([-67.300117492675781250000000000000]), tensor([155.304687500000000000000000000000]))
```

I see that `export_import` has been disabled in a couple of other locations. Of course it would be nice to find the exact cause. In case that's part of a larger issue, the latest PR just sets `export_import=False` so that the tests pass here.

**Comment by zdevito** [comment]
Thanks for looking into this, I am able to reproduce this with your example. 

This is possibly a bug and if so it should be fixed.

Other places where export_import is disabled are to work around issues where the code exports correctly but produces slightly different variable names. We should **not** disable the export import test in this case because it would cover up this potential bug.

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
whoops, i queued this for land, but will not actually land it, because of @zdevito 's comment.
I expect he's working on finding the bug.

**Comment by zdevito** [comment]
It is actually a bug, so we should leave the test as is. Here is the fix for the bug #17557 .

**Comment by SsnL** [comment]
Close as this is fixed in #17557. Feel free to reopen if you can still reproduce with the patch. @skrah

**Pull request closed without merging**
