### PR TITLE
[testing] Update dispatch macros

### PR DESCRIPTION
**Pull request by khushi-411**
Hi,
This PR is the follow-up PR of #71561. (the previous PR had a couple of merge conflicts and was reverted, this PR resolves that).
Please take a look. Thanks!

cc: @pmeier @mruberry @kshitij12345

### CODE REVIEW

**Review by pmeier — APPROVED** [review]
Thanks @khushi-411. LGTM when CI is green.

**Comment by khushi-411** [comment]
Hi, @mruberry!
Gentle ping :)

**Comment by khushi-411** [comment]
Hi, @mruberry!
Gentle ping :)

**Comment by IvanYashchuk** [comment]
@mruberry, this PR needs to be approved by you so that the bot can merge it. Philip's approval is not enough.

**Review by mruberry — APPROVED** [review]
Cool!

**Comment by malfet** [comment]
Will revert this change shortly, and then reland it, as I need to revert #74542

**Pull request closed without merging**
