### PR TITLE
[DCP] Supporting resolve_bytes in LoadPlanner

### PR DESCRIPTION
**Pull request by LucasLLC**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #122700

1. Supporting resolve bytes, similar to resolve_tensor.
2. This will allow us to load the bytes, directly on to the user provided ioBytes buffer.

This essentially mirrors the existing pattern we have for tensors, where the user is expected to follow some version of:

```
1. resolve_tensor 
2. copy to target tensor
3. commit_tensor
```

Differential Revision: [D55259699](https://our.internmc.facebook.com/intern/diff/D55259699/)

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by wz337 — APPROVED** [review]
LGTM!

**Comment by wz337** [comment]
Seems the linter error is real.

**Review by pradeepfn — APPROVED** [review]

**Pull request closed without merging**
