### PR TITLE
[ROCm] Update CI docker images and jobs to rocm5.2

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@kit1980 We will need new ECR entries created in the registry for rocm5.2 please:
`pytorch/pytorch-linux-focal-rocm5.2-py3.7`

**Review by janeyx99 — APPROVED** [review]
Looks good, merge whenever the images are ready and the CI is green.

Looks like there's currently a merge conflict too so a rebase may be in order, but feel free to merge this in yourself with commenting `@pytorchbot merge -g` when it is ready

**Comment by kit1980** [comment]
> @kit1980 We will need new ECR entries created in the registry for rocm5.2 please:
> `pytorch/pytorch-linux-focal-rocm5.2-py3.7`

Added pytorch/pytorch-linux-focal-rocm5.2-py3.7

**Comment by jithunnair-amd** [comment]
Docker builds as well as CI runs passed. Merging ...

@pytorchbot merge

**Comment by jithunnair-amd** [comment]
@janeyx99 The only pull job that failed was unrelated to ROCm: https://github.com/pytorch/pytorch/runs/7455984927?check_suite_focus=true .... Can I request a `merge -f`?

**Pull request closed without merging**
