### PR TITLE
Separate AOTI Eager utils as a single file

### PR DESCRIPTION
**Pull request by EikanWang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125819

The key change is code movement. We just moved aoti eager related code from `torch._inductor.utils` to `torch._inductor.aoti_eager`

cc @voznesenskym @penguinwu @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Review by jgong5 — APPROVED** [review]

**Review by desertfire — APPROVED** [review]

**Comment by fbgheith** [comment]
@pytorchbot revert -m "test failures when run by meta" -c ghfirst

part of ghstack staring with 125308 which needs to be reverted because of test failures when run by meta

**Pull request closed without merging**
