### PR TITLE
Fix failed type cast in Windows Debug Build

### LINKED ISSUE #15330: (VS2017) error C2397: conversion from 'long' to 'uint32_t' requires a narrowing conversion on Debug env
## 🐛 Bug
The same issue #14961(windows libtorch1.0 : cpp_export in Visual studio 2015: error C2397: conversion from 'long' to 'uint32_t' requires a narrowing conversion) was closed, but it happens the same on most recent Visual Studio 2017, version 15.9.4.
It only occurs on Debug environment, and runs fine on Release.

## To Reproduce
```
#pragma once
#include "torch/nn.h"
```

Detailed code explanation below

## Environment
 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Windows 10 x64
 - How you installed PyTorch (`conda`, `pip`, source): Libtorch
 - CUDA/cuDNN version: 10, 7.3
 - GPU models and configuration: 1050
 - Any other relevant information:

## Additional context

According to MSDN, error C2397 happens when narrowing down occurs on uniform initialization.
So I digged down the code and found the code which causes this error.

```
// c10/util/Exception.h
// Line 49
Error(SourceLocation source_location, const std::string& msg);

// Line 120
#define AT_ERROR(...) \
  throw ::c10::Error({__func__, __FILE__, __LINE__}, ::c10::str(__VA_ARGS__))

// c10/util/StringUtil.h
// Line 69
struct C10_API SourceLocation {
  const char* function;
  const char* file;
  uint32_t line;
};
```

It seems that \_\_LINE\_\_ macro value is treated as long type, so it tries to narrow down to the 'uint32_t line' constructor parameter, which causes this error.

### PR DESCRIPTION
**Pull request by peterjc123**
Fixes #15330

### CODE REVIEW

**Comment by ezyang** [comment]
Hey @peterjc123, this is good, thank you. Can we cast to the actual type that the constructor takes, which is `int`? Also, a little comment pointing to the issue / explaining why would also be great.

**Comment by peterjc123** [comment]
From the discussion in #15330, the class it tries to construct is `SourceLocation`. And its definition in `c10/util/StringUtil.h` implies that it is actually unsigned int (uint32_t). I'll add the explanation in the comments ASAP.

**Comment by peterjc123** [comment]
@ezyang Done!

**Review by ezyang — APPROVED** [review]

**Comment by peterjc123** [comment]
@soumith @ezyang Please remember to merge this PR.

**Comment by peterjc123** [comment]
@soumith And this one, please.

**Review by soumith — APPROVED** [review]

**Comment by peterjc123** [comment]
@BusterChung Which CUDA version?

**Comment by BusterChung** [comment]
@peterjc123 it's CUDA 9.1

**Comment by BusterChung** [comment]
@peterjc123 Oh, okay I got it. Thank you a lot!

**Comment by peterjc123** [comment]
I think you have mixed up the concept `Stable` and `Preview`.
The stable version is not changed because it is distributed with the main release 1.0.0. The preview one is generated every night so it will contain fixes for an issue quickly. You'll have to try the nightly one. We'll fix the download links for LibTorch in the frontend quickly, but you could download it through the links [here](https://github.com/pytorch/pytorch/issues/13227#issuecomment-445140508).

**Pull request closed without merging**
