### PR TITLE
[quant][pt2] Add test for prepare_qat Conv + BN numerics

### PR DESCRIPTION
**Pull request by andrewor14**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99846

Summary: This adds the test to compare the numerics of PT2 vs
FX after the Conv + BN fusion in prepare_qat.

Test Plan:
python test/test_quantization.py TestQuantizePT2E.test_prepare_qat_conv_bn_numerics

Reviewers: kimishpatel, jerryzh168

Differential Revision: [D45360706](https://our.internmc.facebook.com/intern/diff/D45360706)

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]

**Comment by andrewor14** [comment]
@andrewor14 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45360706).

**Comment by jerryzh168** [comment]
@andrewor14 I just checked out this PR and tested locally, looks like the weight fake quant parameters does not match and also the per tensor result does not match either, could you add a test for per tensor weight quant?

**Comment by andrewor14** [comment]
> @andrewor14 I just checked out this PR and tested locally, looks like the weight fake quant parameters does not match and also the per tensor result does not match either, could you add a test for per tensor weight quant?

Ok, let me look further into this. However, for this PR, the corresponding diff already landed so we need to merge this PR as is to avoid divergence. I can follow up in a future PR.

**Pull request closed without merging**
