### PR TITLE
[Typing] Fix PEP 484 Violation

### PR DESCRIPTION
**Pull request by malfet**
Not sure, how it worked before, but if arguments must be annotated is optional if they are defaulted to None

Towards enabling mypy-1.4.1 in lintrunner

### <samp>🤖 Generated by Copilot at 5e1b9f4</samp>

> _We annotate the arguments of doom_
> _To show the `None` values of gloom_
> _We improve the type checking and readability_
> _With `Optional` annotations of metal-ity_

cc @ezyang @rgommers @xuzhao9 @gramster

### CODE REVIEW

**Review by izaitsevfb — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Comment by Skylion007** [comment]
@malfet I opened a PR to do this a while ago, but never got around to fixing the bc-breaking errors.

**Review by Skylion007 — APPROVED** [review]

**Comment by Skylion007** [comment]
The reason it worked before is old versions of MyPy had implicit optional support enabled by default. This was changed as this behavior is very bug prone and causes bad type inference

**Comment by malfet** [comment]
@Skylion007 i really need to get it fixed, as my pay-0.960 crashes while type checking PyTorch, which occluded bunch of those errors.

**Comment by Skylion007** [comment]
@malfet If you want to follow up on this PR, we should enable RUF013 which will fix the remaining broken Optionals in the torch codebase.

**Pull request closed without merging**
