### PR TITLE
(non-batch) BSR/BSC to COO performance improvement.

### PR DESCRIPTION
**Pull request by nikitaved**
This PR improves the aforementioned conversions by reducing memory footprint and the number of kernels run, and also by removing the sync imposed by `at::where(condition)`.

cc @pearu @cpuhrsch @amjames @bhosmer

### CODE REVIEW

**Review by pearu — APPROVED** [review]
LGTM! Thanks, @nikitaved!

**Comment by nikitaved** [comment]
@kit1980 , could you please approve?

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
