### PR TITLE
[PT2] [Quant] Change the QConv2d Binary post op name from add to sum

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #115613
* #115809
* #115153
* __->__ #115329

**Summary**
Change the QConv2d Binary fusion post op name from `add` to `sum`, since we are actually using OneDNN `post op sum` instead of `Binary_Add` for now.

**TestPlan**
```
python -m pytest test_quantized_op.py -k test_qconv2d_sum_pt2e
python -m pytest test_quantized_op.py -k test_qconv2d_sum_relu_pt2e
python -m pytest test_quantized_op.py -k test_qconv2d_sum_relu_float_output_pt2e
```

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Comment by leslie-fang-intel** [comment]
Hi @jerryzh168, could you help to take a look of this PR? Looks like it needs your approve to get merged.
However, based on the https://github.com/pytorch/pytorch/blob/1cc456def3df9732d292cbb8dccc3975c3f89ed0/.github/merge_rules.yaml, the changed files in this PR should only need to get approved by Jiong. Not sure what's the gap here.

**Review by jerryzh168 — APPROVED** [review]

**Comment by jerryzh168** [comment]
> @pytorchbot revert -m "Breaking internal builds, please check internal diff to get the list and logs, @jerryzh168 please support the author in order to get these changes merged and landed" -c nosignal

are you sure it's related to this diff? doesn't look like the internal error message is related

**Comment by leslie-fang-intel** [comment]
> > @pytorchbot revert -m "Breaking internal builds, please check internal diff to get the list and logs, @jerryzh168 please support the author in order to get these changes merged and landed" -c nosignal
> 
> are you sure it's related to this diff? doesn't look like the internal error message is related

yean, looks strange how this diff causes internal build failure. @jeanschmidt @jerryzh168 Could you show me how to reproduce the failure? I can take a double check.

**Pull request closed without merging**
