### PR TITLE
[LTC] Sync LazyGraphExecutor and LazyTensor with the staging branch

### PR DESCRIPTION
**Pull request by alanwaketan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #70867

Summary:
This commit syncs LazyGraphExecutor and LazyTensor with the staging branch's
latest changes.

Test Plan:
CI in the lazy_tensor_staging branch.

Differential Revision: [D33440005](https://our.internmc.facebook.com/intern/diff/D33440005)

### CODE REVIEW

**Review by wconstab — APPROVED** [review]
LGTM! thanks!

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33440005).

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33440005).

**Review by desertfire — APPROVED** [review]

**Comment by alanwaketan** [comment]
@alanwaketan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33440005).

**Pull request closed without merging**
