### PR TITLE
[inductor] Make generated kernels deterministic

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #143951

`"compile_id"` had slipped into our generated Triton code (in the
metadata), which will defeat caching because the same kernels generated
in a different order would not cache hit with eachother.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by oulgen — APPROVED** [review]
@masnesral FYI -- looks like compile id & backwards were causing cache misses

**Comment by wdvr** [comment]
@pytorchmergebot revert -m "failing tests on trunk" -c nosignal

dynamo/test_structured_trace.py::StructuredTraceTest::test_cudagraphs [GH job link](https://github.com/pytorch/pytorch/actions/runs/12538270295/job/34963884532) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/79b354ee37b7d8a06a48ca8cc4e19a3fd006b433)

**Pull request closed without merging**
