### PR TITLE
Update fbgemm submodule

### LINKED ISSUE #85956: Pytorch fails to compile on Intel Mac
### 🐛 Describe the bug

Pytorch fails to compile on Intel Mac computers. [See this traceback in the Homebrew repo for a full traceback with error messages.](https://github.com/Homebrew/homebrew-core/pull/111718) I believe that this error started occurring with the release of LLVM 14 (macOS Command Line Tools version 2395). When running `cmake`, we get the following error messages:

```
 [ 20%] Building C object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-vlrelu/gen/vlrelu-avx-x16.c.o
  cd /tmp/libtorch-20220926-10919-1nu5egq/build/confu-deps/XNNPACK && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DCPUINFO_SUPPORTED_PLATFORM=1 -DFXDIV_USE_INLINE_ASSEMBLY=0 -DXNN_ENABLE_ASSEMBLY=1 -DXNN_ENABLE_JIT=0 -DXNN_ENABLE_MEMOPT=1 -DXNN_ENABLE_SPARSE=1 -DXNN_LOG_LEVEL=0 -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/XNNPACK/include -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/XNNPACK/src -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/cpuinfo/deps/clog/include -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/cpuinfo/include -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/pthreadpool/include -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/FXdiv/include -I/tmp/libtorch-20220926-10919-1nu5egq/third_party/FP16/include -isystem /tmp/libtorch-20220926-10919-1nu5egq/third_party/gemmlowp -isystem /tmp/libtorch-20220926-10919-1nu5egq/third_party/neon2sse -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -fPIC -std=gnu99  -fno-math-errno  -mavx  -O2  -MD -MT confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-vlrelu/gen/vlrelu-avx-x16.c.o -MF CMakeFiles/XNNPACK.dir/src/f32-vlrelu/gen/vlrelu-avx-x16.c.o.d -o CMakeFiles/XNNPACK.dir/src/f32-vlrelu/gen/vlrelu-avx-x16.c.o -c /tmp/libtorch-20220926-10919-1nu5egq/third_party/XNNPACK/src/f32-vlrelu/gen/vlrelu-avx-x16.c
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:14:7: error: unknown use of instruction mnemonic without a size suffix
        "mov r14, %[gp]\t\n"
        ^
  <inline asm>:1:2: note: instantiated into assembly here
          mov r14, -48(%rbp)      
          ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:22:8: error: brackets expression not supported on this target
        "mov r8, [r14 + 0]\t\n"
         ^
  <inline asm>:2:9: note: instantiated into assembly here
  mov r8, [r14 + 0]       
          ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:23:8: error: ambiguous instructions require an explicit suffix (could be 'decb', 'decw', 'decl', or 'decq')
        "dec r8\t\n"
         ^
  <inline asm>:3:1: note: instantiated into assembly here
  dec r8  
  ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:25:8: error: brackets expression not supported on this target
        "mov r9, [r14 + 8]\t\n"
         ^
  <inline asm>:4:9: note: instantiated into assembly here
  mov r9, [r14 + 8]       
          ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:27:8: error: brackets expression not supported on this target
        "mov r10, [r14 + 16]\t\n"
         ^
  <inline asm>:5:10: note: instantiated into assembly here
  mov r10, [r14 + 16]     
           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:29:8: error: brackets expression not supported on this target
        "lea r15, [r14 + 24]\t\n"
         ^
  <inline asm>:6:10: note: instantiated into assembly here
  lea r15, [r14 + 24]     
           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:31:8: error: brackets expression not supported on this target
        "mov r12, [r14 + 32]\t\n"
         ^
  <inline asm>:7:10: note: instantiated into assembly here
  mov r12, [r14 + 32]     
           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:33:8: error: brackets expression not supported on this target
        "mov r13, [r14 + 40]\t\n"
         ^
  <inline asm>:8:10: note: instantiated into assembly here
  mov r13, [r14 + 40]     
           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:35:8: error: brackets expression not supported on this target
        "mov rdi, [r14 + 48]\t\n"
         ^
  <inline asm>:9:10: note: instantiated into assembly here
  mov rdi, [r14 + 48]     
           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:37:8: error: brackets expression not supported on this target
        "mov rsi, [r14 + 56]\t\n"
         ^
  <inline asm>:10:10: note: instantiated into assembly here
  mov rsi, [r14 + 56]     
           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:40:8: error: unknown use of instruction mnemonic without a size suffix
        "mov rax, r9\t\n"
         ^
  <inline asm>:11:1: note: instantiated into assembly here
  mov rax, r9     
  ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:41:8: error: unknown use of instruction mnemonic without a size suffix
        "mov rcx, r12\t\n"
         ^
  <inline asm>:12:1: note: instantiated into assembly here
  mov rcx, r12    
  ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:43:8: error: unknown use of instruction mnemonic without a size suffix
        "xor ebx, ebx\t\n"
         ^
  <inline asm>:13:1: note: instantiated into assembly here
  xor ebx, ebx    
  ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:45:8: error: unknown use of instruction mnemonic without a size suffix
        "mov r14, r8\t\n"
         ^
  <inline asm>:15:1: note: instantiated into assembly here
  mov r14, r8     
  ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:46:8: error: unexpected token in argument list
        "vbroadcastss zmm31,DWORD PTR [r15]\t\n"
         ^
  <inline asm>:16:26: note: instantiated into assembly here
  vbroadcastss zmm31,DWORD PTR [r15]      
                           ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:47:8: error: unexpected token in argument list
        "vcvtph2ps zmm3,YMMWORD PTR [r10 + 0]\t\n"
         ^
  <inline asm>:17:24: note: instantiated into assembly here
  vcvtph2ps zmm3,YMMWORD PTR [r10 + 0]    
                         ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:48:8: error: unexpected token in argument list
        "vcvtph2ps zmm4,YMMWORD PTR [r10 + 32]\t\n"
         ^
  <inline asm>:18:24: note: instantiated into assembly here
  vcvtph2ps zmm4,YMMWORD PTR [r10 + 32]   
                         ^
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:49:8: error: invalid operand for instruction
        "vxorps xmm0, xmm0, xmm0\t\n"
         ^
  <inline asm>:19:14: note: instantiated into assembly here
  vxorps xmm0, xmm0, xmm0 
               ^~~~~
  /tmp/libtorch-20220926-10919-1nu5egq/third_party/fbgemm/src/FbgemmFP16UKernelsAvx512.cc:50:8: error: invalid operand for instruction
        "vcomiss xmm31, xmm0\t\n"
         ^
  <inline asm>:20:16: note: instantiated into assembly here
  vcomiss xmm31, xmm0     
                 ^~~~
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
```

### Versions

This is when trying to compile the latest stable Pytorch: version 1.12.1, Git commit 664058fa83f1d8eede5d66418abff6e20bd76ca8.

cc @malfet @seemethere @albanD

### PR DESCRIPTION
**Pull request by malfet**
Reland of https://github.com/pytorch/pytorch/commit/481def752cc001ff8ac7e3b723ece11aa1110c77
Fixes https://github.com/pytorch/pytorch/issues/85956

### CODE REVIEW

**Comment by malfet** [comment]
Updating fbgemm repo  to https://github.com/pytorch/fbgemm/commit/ce307888590cbc8447c7a191997a046b7e8ed0f6 seems to uncover a valid misaligned access problem. From the [log](https://github.com/pytorch/pytorch/actions/runs/3165471823/jobs/5154619624):
```
 test_quantized_embedding (quantization.eager.test_quantize_eager_ptq.TestQuantizeEagerPTQStatic)
Test the post-training quantization flow, serialization and scripting ... /var/lib/jenkins/workspace/third_party/fbgemm/src/RefImplementations.cc:1291:28: runtime error: load of misaligned address 0x610006151492 for type 'const float', which requires 4 byte alignment
0x610006151492: note: pointer points here
 f7 bc  91 9b ea 8f 70 c4 6a 32  5c c0 46 7c 4c 83 0f 07  44 32 dd bc be be be be  be be be be be be
              ^ 
    #0 0x7f567b305fbb in bool fbgemm::EmbeddingSpMDM_ref<unsigned char, long, long, float>(long, long, long, long, unsigned char const*, long const*, long const*, float const*, bool, float*, bool, bool, long, long, bool, bool) (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0x1f45cfbb)
    #1 0x7f567aca7e75 in fbgemm::EmbeddingSpMDMKernelSignature<unsigned char, long, long, float>::Type fbgemm::GenerateEmbeddingSpMDMWithStrides<unsigned char, long, long, float, true>(long, bool, bool, int, bool, bool, long, long, bool, bool)::'lambda'(long, long, long, unsigned char const*, long const*, long const*, float const*, float*)::operator()(long, long, long, unsigned char const*, long const*, long const*, float const*, float*) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0x1edfee75)
    #2 0x7f567aca7997 in std::_Function_handler<bool (long, long, long, unsigned char const*, long const*, long const*, float const*, float*), fbgemm::EmbeddingSpMDMKernelSignature<unsigned char, long, long, float>::Type fbgemm::GenerateEmbeddingSpMDMWithStrides<unsigned char, long, long, float, true>(long, bool, bool, int, bool, bool, long, long, bool, bool)::'lambda'(long, long, long, unsigned char const*, long const*, long const*, float const*, float*)>::_M_invoke(std::_Any_data const&, long&&, long&&, long&&, unsigned char const*&&, long const*&&, long const*&&, float const*&&, float*&&) (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0x1edfe997)
    #3 0x7f566b13b6a3 in std::function<bool (long, long, long, unsigned char const*, long const*, long const*, float const*, float*)>::operator()(long, long, long, unsigned char const*, long const*, long const*, float const*, float*) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xf2926a3)
    #4 0x7f566b12dd26 in at::Tensor& (anonymous namespace)::embedding_bag_byte_impl<long, long>(at::Tensor&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, bool)::'lambda'(long, long)::operator()(long, long) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xf284d26)
    #5 0x7f5669510df7 in std::function<void (long, long)>::operator()(long, long) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xd667df7)
    #6 0x7f56694fa542 in std::_Function_handler<void (int, unsigned long), at::internal::invoke_parallel(long, long, long, std::function<void (long, long)> const&)::$_1>::_M_invoke(std::_Any_data const&, int&&, unsigned long&&) (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xd651542)
    #7 0x7f56694fc801 in std::function<void (int, unsigned long)>::operator()(int, unsigned long) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xd653801)
    #8 0x7f5652f0da50 in c10::ThreadPool::main_loop(unsigned long) (/opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so+0x166a50)
    #9 0x7f569c804de3  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6de3)
    #10 0x7f569cb0c608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608)
    #11 0x7f569ca31132 in clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /var/lib/jenkins/workspace/third_party/fbgemm/src/RefImplementations.cc:1291:28 in 
```
cc: @jianyuh

**Review by xuzhao9 — APPROVED** [review]

**Comment by jianyuh** [comment]
> Updating fbgemm repo to [pytorch/FBGEMM@ce30788](https://github.com/pytorch/FBGEMM/commit/ce307888590cbc8447c7a191997a046b7e8ed0f6) seems to uncover a valid misaligned access problem. From the [log](https://github.com/pytorch/pytorch/actions/runs/3165471823/jobs/5154619624):
> 
> ```
>  test_quantized_embedding (quantization.eager.test_quantize_eager_ptq.TestQuantizeEagerPTQStatic)
> Test the post-training quantization flow, serialization and scripting ... /var/lib/jenkins/workspace/third_party/fbgemm/src/RefImplementations.cc:1291:28: runtime error: load of misaligned address 0x610006151492 for type 'const float', which requires 4 byte alignment
> 0x610006151492: note: pointer points here
>  f7 bc  91 9b ea 8f 70 c4 6a 32  5c c0 46 7c 4c 83 0f 07  44 32 dd bc be be be be  be be be be be be
>               ^ 
>     #0 0x7f567b305fbb in bool fbgemm::EmbeddingSpMDM_ref<unsigned char, long, long, float>(long, long, long, long, unsigned char const*, long const*, long const*, float const*, bool, float*, bool, bool, long, long, bool, bool) (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0x1f45cfbb)
>     #1 0x7f567aca7e75 in fbgemm::EmbeddingSpMDMKernelSignature<unsigned char, long, long, float>::Type fbgemm::GenerateEmbeddingSpMDMWithStrides<unsigned char, long, long, float, true>(long, bool, bool, int, bool, bool, long, long, bool, bool)::'lambda'(long, long, long, unsigned char const*, long const*, long const*, float const*, float*)::operator()(long, long, long, unsigned char const*, long const*, long const*, float const*, float*) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0x1edfee75)
>     #2 0x7f567aca7997 in std::_Function_handler<bool (long, long, long, unsigned char const*, long const*, long const*, float const*, float*), fbgemm::EmbeddingSpMDMKernelSignature<unsigned char, long, long, float>::Type fbgemm::GenerateEmbeddingSpMDMWithStrides<unsigned char, long, long, float, true>(long, bool, bool, int, bool, bool, long, long, bool, bool)::'lambda'(long, long, long, unsigned char const*, long const*, long const*, float const*, float*)>::_M_invoke(std::_Any_data const&, long&&, long&&, long&&, unsigned char const*&&, long const*&&, long const*&&, float const*&&, float*&&) (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0x1edfe997)
>     #3 0x7f566b13b6a3 in std::function<bool (long, long, long, unsigned char const*, long const*, long const*, float const*, float*)>::operator()(long, long, long, unsigned char const*, long const*, long const*, float const*, float*) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xf2926a3)
>     #4 0x7f566b12dd26 in at::Tensor& (anonymous namespace)::embedding_bag_byte_impl<long, long>(at::Tensor&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, c10::optional<at::Tensor> const&, c10::optional<at::Tensor> const&, bool, bool)::'lambda'(long, long)::operator()(long, long) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xf284d26)
>     #5 0x7f5669510df7 in std::function<void (long, long)>::operator()(long, long) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xd667df7)
>     #6 0x7f56694fa542 in std::_Function_handler<void (int, unsigned long), at::internal::invoke_parallel(long, long, long, std::function<void (long, long)> const&)::$_1>::_M_invoke(std::_Any_data const&, int&&, unsigned long&&) (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xd651542)
>     #7 0x7f56694fc801 in std::function<void (int, unsigned long)>::operator()(int, unsigned long) const (/opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so+0xd653801)
>     #8 0x7f5652f0da50 in c10::ThreadPool::main_loop(unsigned long) (/opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so+0x166a50)
>     #9 0x7f569c804de3  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6de3)
>     #10 0x7f569cb0c608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608)
>     #11 0x7f569ca31132 in clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f132)
> 
> SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /var/lib/jenkins/workspace/third_party/fbgemm/src/RefImplementations.cc:1291:28 in 
> ```
> 
> cc: @jianyuh

Thanks @malfet for rolling back the commit! Looks like this is related to src/EmbeddingSpMDM.cc changes in https://github.com/pytorch/FBGEMM/pull/1357/files . cc @jiyuanzFB 

https://github.com/pytorch/pytorch/pull/86054#issuecomment-1264456154

**Pull request closed without merging**
