### PR TITLE
Print ref on win

### PR DESCRIPTION
**Pull request by janeyx99**
Previously, the parse_ref.py script was not run at all with the default powershell in windows. Using bash + installing python on windows fixes the issue.

### CODE REVIEW

**Review by atalman — APPROVED** [review]
This PR is trying to fix an issue on windows and power shell, however I see that all of the linux workflows also has changed. Should we just keep this change local to windows ?

**Comment by janeyx99** [comment]
> This PR is trying to fix an issue on windows and power shell, however I see that all of the linux workflows also has changed. Should we just keep this change local to windows ?

I think bash is already the default for linux so this shouldn't change. parse_ref is currently abstracted out into common.yml and I like that it's platform independent.

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
