### PR TITLE
[ROCm] Bump kineto submodule commit to clear kineto cache to avoid memory leaks

### LINKED ISSUE #103999: DISABLED test_cuda_memory_leak_detection (__main__.TestCuda)
Platforms: rocm

Disabling this unit test since it showed up in CI testing for ROCm5.5 CI upgrade PR: https://github.com/pytorch/pytorch/pull/103092: https://github.com/pytorch/pytorch/actions/runs/5316942376/jobs/9630407771?pr=103092

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @seemethere @malfet @pytorch/pytorch-dev-infra @BLOrange-AMD

### PR DESCRIPTION
**Pull request by ramcherukuri**
Fixes #103999

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@ramcherukuri I triggered ROCm CI on this PR. Please check the CI logs to make sure the test in question passes and post a snippet of the passing test as a PR comment. Then we should be good to merge the PR.

**Comment by ramcherukuri** [comment]
Test passed based on entry into XML report shard 2-3. 
<testcase classname="TestProfilerCUDA" name="test_mem_leak" time="4.214" file="profiler/test_profiler.py" />

**Pull request closed without merging**
