### PR TITLE
Add private user tensor type IDs for experimentation.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#31830 Add private user tensor type IDs for experimentation.**

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D19330312](https://our.internmc.facebook.com/intern/diff/D19330312)

### CODE REVIEW

**Review by zdevito — APPROVED** [review]

**Comment by jgong5** [comment]
@ezyang Thanks for adding this. I'm trying to understand how to play around these private type IDs with CPU optimization as an example. Suppose I want to implement an optimized CPU path in a PyTorch extension (say "torch_abc") with its own `ABCTensorImpl` and a set of optimized kernels. Below is something I should do:
1. Register kernels for all tensor factory ops with `BackendSelect` dispatch key since they do not have `Tensor` input. Inside these kernels, I would create my own Tensor with `ABCTensorImpl` based on CPU `DeviceType` and `Storage` and I would attach two keys: `PrivateUse1` (or `PrivateUse1_PreAutograd` if needed) and `CPU`, the latter for fallback redispatch.
2. Register kernels for all other ops with `PrivateUse1` inside which, I would do redispatch with `CPU` key for those ops I haven't added special optimizations. (BTW: does it apply when a CUDA tensor is converted to CPU tensor with `to(device="cpu")` )?

To leverage my optimizations, users only need to do `import torch_abc` and no other changes are needed to the existing model code.

Is my understanding correct? Thanks.
@hongzhen1 @EikanWang @uyongw

**Comment by ezyang** [comment]
Your description seems a little suspect. It will be easiest for me to help you if I can clarify: do ABCTensorImpls have exactly the same structure as CPUTensorImpls? If they are different, how are they different?

**Comment by jgong5** [comment]
> It will be easiest for me to help you if I can clarify: do ABCTensorImpls have exactly the same structure as CPUTensorImpls? If they are different, how are they different?

Thanks ahead for the help. ABCTensorImpl might contain more stuff to support further optimizations with better user experiences. For example, it might hide the complexity of blocked layout inside and allows automatic layout conversion. At the user level, it behaves as a strided tensor, same as original CPU tensor. It might also hold states to support lazy execution that allows fusions in eager mode.

I'm listing these points just as examples to understand the new PyTorch dispatch mechanism and how it can be leveraged by an extension.

**Comment by ezyang** [comment]
In general, if your tensor has all of this extra stuff, you can't just "fallback" to CPU implementations; you'll need to actually explicitly allocate a CPU tensor with the materialized data and then call the operation on that tensor. Which means there is no reason to put CPU on the new tensor implementation.

But to answer the original question, the way you would use the dispatcher in this place is something like:

1. Create your own special factory function for creating ABCTensorImpls. Don't bother with BackendSelect or the existing factory functions, these are not pluggable. Just have a brand new function that constructs your ABCTensorImpl and returns it
2. Register kernels for ABCTensorImpl. If you need to fallback to CPU operations, materialize good old fashioned CPU tensors and then call the operation on them.

**Comment by jgong5** [comment]
> if your tensor has all of this extra stuff, you can't just "fallback" to CPU implementations; you'll need to actually explicitly allocate a CPU tensor with the materialized data and then call the operation on that tensor. Which means there is no reason to put CPU on the new tensor implementation.

Thanks for the suggestions. Yes, we are supposed to create a new CPU tensor before falling back to the existing CPU ops, just like what you suggested in point 2.

> Create your own special factory function for creating ABCTensorImpls. Don't bother with BackendSelect or the existing factory functions, these are not pluggable. Just have a brand new function that constructs your ABCTensorImpl and returns it

Does that mean users have to modify their existing model code to change the factory function calls to the new ones? Something like `torch.randn` -> `abc.randn`? If so, is it possible to make factory functions pluggable to avoid extra code changes? By reading the code comments on `BackendSelect`, I thought that it meant for factory functions since they do not have tensor arguments. Is my understanding correct?

**Pull request closed without merging**
