### PR TITLE
GHF: Add clickable usernames for Approved / Reverted By

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #73677

Should make the usernames clickable in the Github UI

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
I don't think we should do it, as it will notify the person when commit is landed, cherry-picked or copied into the fork

**Comment by seemethere** [comment]
I wasn't thinking about the forked scenario, don't really want to be notified for people's forks

**Comment by seemethere** [comment]
Tested that this approach doesn't generate new notifications with this commit: https://github.com/seemethere/test-repo/commit/dd4f2186ac8462aaa2b4e1c191ea9885f948b087

**Review by malfet — APPROVED** [review]
Looks good to me, but can you please make similar change to "Reverted on behalf of"?

**Pull request closed without merging**
