### PR TITLE
add default device function interface

### PR DESCRIPTION
**Pull request by Bin1024**
Fixes #ISSUE_NUMBER
Currently, the default device for some functions on the python side and c++ side of the community is cuda. To use other devices, you need to add other device parameters such as pin_memory("foo"). In this pr, I added an interface that can set the default device. By set_the_default_device function , you can use pin_memory() directly for "foo" device, without adding "foo" to every function that calls pin_memory. This extends native code compatibility

### CODE REVIEW

**Comment by Bin1024** [comment]
@albanD @ezyang Please take a moment to review my PR. Thanks!

**Comment by ezyang** [comment]
Not accepting this, this runs afoul "no unrestricted global state in C++".

You may be able to piggy back this on top of TorchFunctionMode. Check out how torch/utils/_device.py is implemented

**Comment by Bin1024** [comment]
> Not accepting this, this runs afoul "no unrestricted global state in C++".
> You may be able to piggy back this on top of TorchFunctionMode. Check out how torch/utils/_device.py is implemented

Thanks for your advice.
I understand that you mean that the default device can only be modified from the python side, but the default dispatchkey of some c++ functions is cuda, how should we solve it?
In this pr, we ensured that the default device is cuda. At the same time, it can provide an interface for setting the default device, which can make the original code better compatible with the third-party device during the third-party device adaptation process.
Can you give some more specific advice on this? @ezyang

**Review by mikaylagawarecki — COMMENTED** [review]
Hi @Bin1024 could you file an issue that describes the need for this new feature please. That would help for discussion on whether this feature should be added :)

**Comment by ezyang** [comment]
To solve the pin_memory problem specifically, I would create a TorchFunctionMode that lets you override it the device argument there OR modify the torch/utils/_device.py context manager to handle this too.

**Comment by ezyang** [comment]
Can you give a small example of the code that you would like to work unchanged with the third party device? I am unconvinced that you cannot use TorchFunctionMode to implement equivalent functionality. In particular, take a look at how the global `set_default_device` is implemented; it doesn't require an explicit with block.

**Comment by Bin1024** [comment]
image

**Comment by Bin1024** [comment]
We want to maintain that for functions that can be used directly by cuda, third-party devices can also be used directly without the need to set device parameters.For example fork_rng function, as shown in the picture below. 
image

**Comment by ezyang** [comment]
Based on the code you posted, TorchFunctionMode can do it. Or, if it can't do it, that's solely because some Python API needs to support torch function'ification.

**Comment by Bin1024** [comment]
1

**Pull request closed without merging**
