### PR TITLE
Fix RNN class constructor signature

### LINKED ISSUE #114617: RNN argument order
### 🐛 Describe the bug

The documentation states
```
torch.nn.RNN(self, input_size, hidden_size, num_layers=1, nonlinearity='tanh', bias=True, batch_first=False, dropout=0.0, bidirectional=False, device=None, dtype=None)
```
besides the impossible `self`, I try to send the arguments in the order suggested
```
rnn = nn.RNN(2, 3, 1, 'relu')
x = torch.randn(5, 1, 2)
rnn(x)
```
which complains
```
TypeError: rnn_tanh() received an invalid combination of arguments - got (Tensor, Tensor, list, str, int, float, bool, bool, bool), but expected one of:
 * (Tensor data, Tensor batch_sizes, Tensor hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, !list of [Parameter, Parameter, Parameter, Parameter]!, !str!, !int!, !float!, !bool!, bool, bool)
 * (Tensor input, Tensor hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, !list of [Parameter, Parameter, Parameter, Parameter]!, !str!, int, float, bool, bool, bool)
```

### Versions

Latest.

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### PR DESCRIPTION
**Pull request by linus-md**
Fixes #114617

### CODE REVIEW

**Review by mikaylagawarecki — COMMENTED** [review]
Thank you! Would you mind updating LSTM and GRU as well

**Review by mikaylagawarecki — APPROVED** [review]

**Comment by Atcold** [comment]
I'm curious about how the `__init__()` works when `self` is missing.

**Comment by mikaylagawarecki** [comment]
@Atcold it was just the docstring that had the `self` removed, the actual `__init__` function still has it


https://github.com/linus-md/pytorch/blob/09e2c2df378f68e9bd755d2ab1f0cb38c34fd72a/torch/nn/modules/rnn.py#L469-L480

**Pull request closed without merging**
