### PR TITLE
Attempt to pin opencv-python version

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #106876
* __->__ #106900

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by voznesenskym — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Review by malfet — APPROVED** [review]
In the long run, can we move it from the code to .env/pip-freeze files?

**Comment by ezyang** [comment]
The torchbench install process is a bit of a mess, will be tricky to do

**Pull request closed without merging**
