### PR TITLE
[AARCH64] Fall back to GEMM if mkldnn_matmul fails

### LINKED ISSUE #114750: [aarch64] `nn.Linear(20, 1)` inference fails
### 🐛 Describe the bug

Hi,

As the title indicates, I have a model created with `TorchScript` and saved with the `.pt` extension under `torch==1.13.1` but when I load it back in another env using `torch==2.1.1` it fails to infer.

The error is the following:
```
I'm also having errors when running a pt fail saved with TorchScript that was implemented with torch==1.13.1, but torch==2.1.1 raises the following:

249, in forward
        x = self.fc1(x)
        x = torch.nn.functional.relu(x)
        x = self.fc2(x)
            ~~~~~~~~ <--- HERE
        return x
  File "/Users/panagiotisvardanis/miniconda3/envs/mac-pytorch/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    def forward(self, input: Tensor) -> Tensor:
        return F.linear(input, self.weight, self.bias)
               ~~~~~~~~ <--- HERE
RuntimeError: could not create a primitive descriptor for a matmul primitive
```

### Versions

Pip requirements from the environment where the model was created:
```
[pip3] torch==1.13.1
[pip3] torchvision==0.14.0
```

Pip requirements from the environment where the model is failing to infer:
```
[pip3] torch==2.1.1
[pip3] torchvision==0.16.1
```

cc @ezyang @gchanan @zou3519 @kadeng @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @mingfeima @ashokei @jingxu10 @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @malfet @snadampal

### PR DESCRIPTION
**Pull request by malfet**
- Add call to `at::globalContext().userEnabledMkldnn()` to `apply_mkldnn_matmul_heur`
- Surround calls to `mkldnn_matmul` with `try {} catch {}`
- Print warning and fall back to BLAS (by calling  `at::globalContext().setUserEnabledMkldnn()`) if `mkldnn_matmul()` fails

Test plan: On Linux arm run: 
```shell
$ sudo chmod 400 /sys; python -c "import torch;m=torch.nn.Linear(1, 32);print(torch.__version__);print(m(torch.rand(32, 1)))"
Error in cpuinfo: failed to parse the list of possible processors in /sys/devices/system/cpu/possible
Error in cpuinfo: failed to parse the list of present processors in /sys/devices/system/cpu/present
Error in cpuinfo: failed to parse both lists of possible and present processors
2.3.0.dev20231215
bad err=11 in Xbyak::Error
bad err=11 in Xbyak::Error
/home/ubuntu/miniconda3/envs/py311/lib/python3.11/site-packages/torch/nn/modules/linear.py:116: UserWarning: mkldnn_matmul failed, switching to BLAS gemm:internal error (Triggered internally at /pytorch/aten/src/ATen/native/LinearAlgebra.cpp:1509.)
  return F.linear(input, self.weight, self.bias)
tensor([[-0.5183,  0.2279, -0.4035,  ..., -0.3446,  0.0938, -0.2113],
        [-0.5111,  0.2362, -0.3821,  ..., -0.3536,  0.1011, -0.2159],
        [-0.6387,  0.0894, -0.7619,  ..., -0.1939, -0.0282, -0.1344],
        ...,
        [-0.6352,  0.0934, -0.7516,  ..., -0.1983, -0.0247, -0.1366],
        [-0.4790,  0.2733, -0.2862,  ..., -0.3939,  0.1338, -0.2365],
        [-0.5702,  0.1682, -0.5580,  ..., -0.2796,  0.0412, -0.1782]],
       grad_fn=<AddmmBackward0>)
```
Fixes https://github.com/pytorch/pytorch/issues/114750

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
Do we test this in CI? If so, can we add a regression test?

**Comment by malfet** [comment]
@lezcano we can only test it in nightlies, but I will add it later (and do some manual testing right now)

**Comment by malfet** [comment]
@jgong5 FYI, is it safe to assume that `mkldnn_matmul` should never raise an exception and if it does, it safe to fallback to BLAS GEMM? Also, would be nice to check perf impact (should be near zero as `try` which do not raise are generally safe)

**Pull request closed without merging**
