### PR TITLE
[reland][quant][pt2e][xnnpack_quantizer] Add support for mul and mul_relu (#107930)

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #107992

Summary: att

Test Plan: buck2 run executorch/examples/quantization:example -- -m=mv3 --verify

Differential Revision: D48588121

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by digantdesai — APPROVED** [review]
LGTM

**Review by mcr229 — APPROVED** [review]
Nice! hopefully this gets pulled in to nightly and I can test the examples tomorrow

**Pull request closed without merging**
