### PR TITLE
Raise error for int64 and bool dtypes in nanmean, even for empty tensors

### PR DESCRIPTION
**Pull request by axsseldz**
This PR ensures that the `nanmean()` function raises a `RuntimeError` when using `int64` or `bool` dtypes, even for empty tensors. Previously, non-empty tensors correctly raised errors for unsupported dtypes, while empty tensors did not. This change brings consistent error handling for both cases.

addressing the need raised in an issue by @hyperkai  (Issue [#131043](https://github.com/pytorch/pytorch/issues/131043)).

### Changes

- Added checks in `nanmean_out()` to raise errors for `int64` and `bool` dtypes regardless of tensor size.

### CODE REVIEW

**Comment by axsseldz** [comment]
Hi! @ezyang , what do you think about the changes? :)

**Review by ezyang — CHANGES_REQUESTED** [review]
Good start. Needs a test. All integral types should be excluded, not just long. Don't enumerate the integral types, use an appropriate helper function.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
oops, can you submit this against main?

**Comment by axsseldz** [comment]
> oops, can you submit this against main?

Ohh I see, yes definitely

**Comment by ezyang** [comment]
Fix lint and you are good to go

**Comment by axsseldz** [comment]
@ezyang this last error is related to the labels of this pr isn't it?

**Pull request closed without merging**
