### PR TITLE
[GHF][BE] Move merge rules to yaml

### PR DESCRIPTION
**Pull request by malfet**
To allow comments

Update `trymerge.yaml`, `revert.yaml` and `tryrebase.yaml` to use v4 setup-python action and install pyyaml

Reformat json to yaml by running:
```
 python -c "import yaml;print(yaml.dump(yaml.safe_load(open('.github/merge_rules.yaml')), sort_keys=False))"
```

### CODE REVIEW

**Review by b0noI — APPROVED** [review]

**Comment by huydhn** [comment]
Missing git add for the new yaml file?

**Review by ZainRizvi — CHANGES_REQUESTED** [review]
Nice! It's just missing the merge_rules.yaml file :)

**Comment by malfet** [comment]
I swear I did `git mv`, but somehow it didn't get picked up after `git stash; git stash pop`

**Comment by malfet** [comment]
And it needs a yaml deps to the workflow file (see failure in https://github.com/malfet/deleteme/runs/8021735648?check_suite_focus=true )

**Review by huydhn — APPROVED** [review]

**Review by ZainRizvi — COMMENTED** [review]
Do you want to also change merge_rules.yaml to look like a normal yaml file?

I get that json is technically valid yaml, but that's not what folks expect to see when opening a yaml file!

**Comment by malfet** [comment]
> Do you want to also change merge_rules.yaml to look like a normal yaml file?

Imo we should do it in followup PR after collecting some feedback from folks

**Pull request closed without merging**
