### PR TITLE
[Reland] Use missing-prototypes in torch_cpu

### PR DESCRIPTION
**Pull request by cyyever**
This PR enables Wmissing-prototypes in torch_cpu except some generated cpp files and the mps and metal,vulkan backends and caffe2 sources.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @gujinghui @PenghuiCheng @jianyuh @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @EikanWang

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Sounds good!

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
