### PR TITLE
[Dynamo] SizeVariable supports hasattr

### PR DESCRIPTION
**Pull request by yanboliang**
Fixes #ISSUE_NUMBER

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by williamwen42 — APPROVED** [review]

**Review by anijain2305 — CHANGES_REQUESTED** [review]
This might be wrong for named tuples.
Can you add a test with named tuple where the field is present? I think it will incorrectly return `False`.

**Comment by yanboliang** [comment]
@anijain2305 NamedTuple has been fixed at #124531

**Review by anijain2305 — APPROVED** [review]
Aplologize. For some reason, I thought NamedTupleVariable is a subclass of SizeVariable. My bad. This is good.

**Pull request closed without merging**
