### PR TITLE
Graph break cleanly in Dynamo for module parametrization

### LINKED ISSUE #118795: 24 Dynamo test are failing with "<weakref at 0xDEADBEEF; to 'Tensor' at 0xDEADBEEF".
## Repro

`PYTORCH_TEST_WITH_DYNAMO=1 pytest test_jit.py -v -k test_scriptable`

You will need to remove the skip or expectedFailure before running the repro command.
This may be just removing a line in
[dynamo_test_failures.py](https://github.com/pytorch/pytorch/blob/main/torch/testing/_internal/dynamo_test_failures.py)

## Failing tests

Here's a comprehensive list of tests that fail (as of this issue) with the above message:
<details>
<summary>Click me</summary>
```
test_jit.py::TestParametrization.test_scriptable
test_jit.py::TestParametrization.test_traceable
test_ao_sparsity.py::TestFakeSparsity.test_masking_logic
test_ao_sparsity.py::TestBaseStructuredSparsifier.test_constructor
test_ao_sparsity.py::TestBaseStructuredSparsifier.test_prepare_conv2d
test_ao_sparsity.py::TestBaseStructuredSparsifier.test_prepare_linear
test_ao_sparsity.py::TestBaseStructuredSparsifier.test_step_linear
test_ao_sparsity.py::TestFxComposability.test_q_prep_fx_before_s_prep
test_ao_sparsity.py::TestFxComposability.test_q_prep_fx_s_prep_ref_conv
test_ao_sparsity.py::TestFxComposability.test_s_prep_before_q_prep_fx
test_ao_sparsity.py::TestFxComposability.test_s_prep_before_qat_prep_fx
test_ao_sparsity.py::TestFxComposability.test_s_prep_q_prep_fx_ref
test_stateless.py::TestStatelessFunctionalAPI.test_reparametrize_module_fail_reset_to_original_stateless
test_stateless.py::TestStatelessFunctionalAPI.test_reparametrize_module_fail_reset_to_original_torch_func
test_stateless.py::TestStatelessFunctionalAPI.test_reparametrized_module_change_parametrization_original_stateless
test_stateless.py::TestStatelessFunctionalAPI.test_reparametrized_module_change_parametrization_original_torch_func
test_subclass.py::TestSubclass.test_parametrization_base_tensor_leave_parametrized_False
test_subclass.py::TestSubclass.test_parametrization_base_tensor_leave_parametrized_True
test_autograd.py::TestAutograd.test_custom_autograd_no_early_free
test_autograd.py::TestAutograd.test_custom_autograd_repeated_grad_grad
test_autograd.py::TestAutograd.test_saved_tensor_hooks_custom_function_intermediates
nn/test_parametrization.py::TestNNParametrization.test_new_spectral_norm
nn/test_parametrization.py::TestNNParametrization.test_new_spectral_norm_dim
nn/test_parametrization.py::TestNNParametrization.test_new_spectral_norm_forward
```
</details>

cc @ezyang @msaroufim @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #121041

Fixes #118795

This is a graph breaking partial fix for #120914. We still need -actual- module parametrization tracing support, but at least it doesn't blow up hard now.

**Background**: Module parametrization injects a property as the module parameter attribute that calls a `nn.Module` whose forward takes in a module parameter and returns a reparametrized module parameter.
Example:
```
class MyParametrization(nn.Module):
    def forward(X):
        # This reparametrization just negates the original parameter value
        return -X

m = nn.Linear(...)
p = MyParametrization()
register_parametrization(m, "weight", p)

# Accessing the "weight" attribute will invoke p's forward() on m's original weight and return the output as the new weight.
# m.weight here is now an injected property that does the above instead of an actual Parameter.
# This property is defined in torch/nn/utils/parametrize.py.
m.weight

# NB: Parametrization changes the module type (e.g. torch.nn.utils.parametrize.ParametrizedLinear)
print(type(m))
```

**Problem 1**: Dynamo has special tracing rules for things in `torch.nn`. Parametrizing a module changes the type of the module and the parametrized attribute, so now these rules wrongly affect tracing here. To fix this:
* For parametrized modules, call `convert_to_unspecialized()` to restart analysis where Dynamo starts inlining the module.

**Problem 2**: The issue seen in #118795 is that Dynamo will see a dynamically constructed tensor when `m.weight` is called and introduce that to its `tensor_weakref_to_sizes_strides` cache during fake-ification. This tensor is also made to be a graph input, since it's a module parameter. When guards are created for this module parameter input, the logic calls `m.weight` again and tries to look the result up in the cache, but this is a different tensor now, giving the `KeyError` symptom. To fix this:
* Replace Dynamo's `tensor_weakref_to_sizes_strides` cache with a `input_source_to_sizes_strides` cache.
    * This cache was originally introduced in #100128.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by anijain2305** [comment]
Can we try converting the NNModuleVariable to unspecialized and restart tracing? I am sure that Dynamo will have graph breaks inside the reparameterization but conceptually it will start inlining the internals of inbuilt nn modules.

This is an example - if user add hooks on inbuilt nn modules, we mark the nn module unspecialized, restart analysis where Dynamo starts inlining the nn module.

https://github.com/pytorch/pytorch/blob/360761f7d039445e7b00493c2990ace9f94a5a9e/torch/_dynamo/variables/nn_module.py#L258-L262

**Comment by jbschlosser** [comment]
@anijain2305 cool that's much nicer :)

**Review by anijain2305 — APPROVED** [review]
Apologize for the late review ... But LGTM.

**Pull request closed without merging**
