### PR TITLE
[inductor] More fixes on the keys of `constants` and `signature` dictionaries

### PR DESCRIPTION
**Pull request by Jokeren**
Previous PR forgets to change two other places that also create `constants` and `signature`. https://github.com/pytorch/pytorch/pull/135170

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by shunting314 — COMMENTED** [review]
Would there be any backward compatibility issue?
i.e., if PyTorch is running with an older version of triton, with triton still handle the new metadata format properly?

**Comment by Jokeren** [comment]
> Would there be any backward compatibility issue?
i.e., if PyTorch is running with an older version of triton, with triton still handle the new metadata format properly?

Are you asking about whether old triton could handle the new format? I think it happened about 6 months ago.

https://github.com/triton-lang/triton/blame/5aaddb8b497181744992face03a825173da4806c/python/triton/runtime/jit.py

**Review by jansel — DISMISSED** [review]

**Comment by jansel** [comment]
Seems fine, though maybe we need some sort of triton version check.

**Comment by Jokeren** [comment]
I think there also need to be some tests on the triton side to check the key type of the dictionaries. I'll go add them soon.

**Comment by Jokeren** [comment]
Triton PR: https://github.com/triton-lang/triton/pull/4693

**Comment by Jokeren** [comment]
Can someone help me kick off the CI again? Thanks

**Comment by Jokeren** [comment]
Is it good to merge? I probably don't have the permission to ask the pytorchbot to merge

**Comment by jansel** [comment]
@jfix71 how hard would it be to update MTIA Triton to use this new API?

**Comment by jfix71** [comment]
@jansel I think it should be a pretty reasonable change, but we'd want to import the PR and update the diff internally to tag on our changes before landing, if that's a possibility. What's the standard workflow expected for these sorts of changes, so we don't have to fix forward?

**Comment by Myrthan** [comment]
> @jfix71 how hard would it be to update MTIA Triton to use this new API?

We fixed MTIA yesterday check [D62887579](https://www.internalfb.com/diff/D62887579)and [D62896747](https://www.internalfb.com/diff/D62896747). Could you please try recreate fbsource Phabricator diff out of this pr? It should be all green for you, I tested it on your changes from this Github PR [D62888678](https://www.internalfb.com/diff/D62888678).

**Comment by Myrthan** [comment]
@jfix71 cause there was no update for some time, do you think it is wise to use "@ pytorchbot merge"? will the bot merge it on top of fresh changes? Or this PR has to be rebased first? Otherwise I have to recreate the new github PR, but I don't want to take the ownership from @Jokeren

**Comment by Jokeren** [comment]
> 
@jfix71 cause there was no update for some time, do you think it is wise to use "@ pytorchbot merge"? will the bot merge it on top of fresh changes? Or this PR has to be rebased first? Otherwise I have to recreate the new github PR, but I don't want to take the ownership from @Jokeren

Thanks. It's fine to create a new PR. In terms of tracing issues in the future if needed, you can just add me as a co-author in the PR so that I will be notified.

**Comment by Myrthan** [comment]
> > 
> 
> @jfix71 cause there was no update for some time, do you think it is wise to use "@ pytorchbot merge"? will the bot merge it on top of fresh changes? Or this PR has to be rebased first? Otherwise I have to recreate the new github PR, but I don't want to take the ownership from @Jokeren
> 
> Thanks. It's fine to create a new PR. In terms of tracing issues in the future if needed, you can just add me as a co-author in the PR so that I will be notified.

Great, let me do this right now.

**Comment by Jokeren** [comment]
Thanks. I think it should work

**Comment by Myrthan** [comment]
https://github.com/pytorch/pytorch/pull/136514 has been merged, we can abandon this PR I believe. Thank you!

**Pull request closed without merging**
