### PR TITLE
Disable flaky ROCm multi-gpu tests

### PR DESCRIPTION
**Pull request by bddppq**
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/3426/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/3513/
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/3706/

### CODE REVIEW

**Comment by bddppq** [comment]
cc @jithunnair-amd

**Review by houseroad — APPROVED** [review]
LG

**Review by xw285cornell — APPROVED** [review]

**Review by iotamudelta — APPROVED** [review]

**Review by mrshenli — APPROVED** [review]
Thanks!

**Comment by bddppq** [comment]
These tests don't seem be flaky on master any more, closing for now.

**Comment by mrshenli** [comment]
hmm, AFAIK, we haven't make any changes to them yet. Has anything changed in ROCm multi-gpu test env?

**Comment by bddppq** [comment]
@mrshenli rocm kernel drivers on the CI boxes have been upgraded to the newest version (2.9) in ~1 week ago

**Pull request closed without merging**
