### PR TITLE
functionalization <> LTC integration (take 3)

### PR DESCRIPTION
**Pull request by bdhirsh**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #80251

new PR for https://github.com/pytorch/pytorch/pull/75527.

It looks like there's a bug in the windows CI scripts that was causing
flaky failures, that disappear when I create a new PR. example failure:
https://github.com/pytorch/pytorch/runs/6999272635?check_suite_focus=true

### CODE REVIEW

**Comment by bdhirsh** [comment]
FYI @wconstab I made this PR as a re-make of the last one (see the comment at https://github.com/pytorch/pytorch/pull/80043#issuecomment-1165959842). If this is fully green on Monday morning and windows CI looks fine then I'll go ahead and land it.

**Review by wconstab — APPROVED** [review]
ugh making a new PR for each windows CI failure seems nonideal... but fingers crossed :)

**Pull request closed without merging**
