### PR TITLE
[BE] fix type annotation for `*args` and `**kwargs`

### PR DESCRIPTION
**Pull request by XuehaiPan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #133075

The annotation for `*args` and `**kwargs` should be the element type rather than `Tuple[T, ...]` and `Dict[str, T]`.

You can verify this via:

```python
# test.py

from typing import Dict, reveal_type, Tuple, TypeVar


ElemInArgs = TypeVar("ElemInArgs")
ElemInKwargs = TypeVar("ElemInKwargs")


def wrongly_annotated(*args: Tuple[ElemInArgs, ...], **kwargs: Dict[str, ElemInKwargs]) -> None:
    reveal_type(args)  # E: Tuple[Tuple[ElemInArgs, ...], ...]
    reveal_type(kwargs)  # E: Dict[str, Dict[str, ElemInKwargs]]


def correctly_annotated(*args: ElemInArgs, **kwargs: ElemInKwargs) -> None:
    reveal_type(args)  # E: Tuple[ElemInArgs, ...]
    reveal_type(kwargs)  # E: Dict[str, ElemInKwargs]
```

```console
$ mypy test.py
test.py:11:17: note: Revealed type is "builtins.tuple[builtins.tuple[ElemInArgs`-1, ...], ...]"
test.py:12:17: note: Revealed type is "builtins.dict[builtins.str, builtins.dict[builtins.str, ElemInKwargs`-2]]"
test.py:16:17: note: Revealed type is "builtins.tuple[ElemInArgs`-1, ...]"
test.py:17:17: note: Revealed type is "builtins.dict[builtins.str, ElemInKwargs`-2]"
Success: no issues found in 1 source file
```

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o @LucasLLC @MeetVadakkanchery @mhorowitz @pradeepfn

### CODE REVIEW

**Review by oulgen — CHANGES_REQUESTED** [review]
I think Any type is actively worse than that dict/tuple as it is disables any type checking. I’d prefer keeping the dict/tuple types

**Comment by XuehaiPan** [comment]
> I think Any type is actively worse than that dict/tuple as it is disables any type checking. I’d prefer keeping the dict/tuple types

@oulgen It is not a preference but about correctness. If you type `*args: tuple[...]` and `**kwargs: dict[str, ...]`, they are `tuple of tuple` and `dict of dict`.

You can verify this via:

```python
# test.py

from typing import Dict, reveal_type, Tuple, TypeVar


ElemInArgs = TypeVar("ElemInArgs")
ElemInKwargs = TypeVar("ElemInKwargs")


def wrongly_annotated(*args: Tuple[ElemInArgs, ...], **kwargs: Dict[str, ElemInKwargs]) -> None:
    reveal_type(args)  # E: Tuple[Tuple[ElemInArgs, ...], ...]
    reveal_type(kwargs)  # E: Dict[str, Dict[str, ElemInKwargs]]


def correctly_annotated(*args: ElemInArgs, **kwargs: ElemInKwargs) -> None:
    reveal_type(args)  # E: Tuple[ElemInArgs, ...]
    reveal_type(kwargs)  # E: Dict[str, ElemInKwargs]
```

```console
$ mypy test.py
test.py:11:17: note: Revealed type is "builtins.tuple[builtins.tuple[ElemInArgs`-1, ...], ...]"
test.py:12:17: note: Revealed type is "builtins.dict[builtins.str, builtins.dict[builtins.str, ElemInKwargs`-2]]"
test.py:16:17: note: Revealed type is "builtins.tuple[ElemInArgs`-1, ...]"
test.py:17:17: note: Revealed type is "builtins.dict[builtins.str, ElemInKwargs`-2]"
Success: no issues found in 1 source file
```

**Comment by Skylion007** [comment]
We should be using `from typing_extensions import Unpack` to type the args

**Comment by XuehaiPan** [comment]
> We should be using `from typing_extensions import Unpack` to type the args

Maybe `ParamSpec` is the best solution.

**Pull request closed without merging**
