### PR TITLE
[quant] Adding tests for qconv output shapes

### PR DESCRIPTION
**Pull request by z-a-f**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #77927

Because the shape of the output of the conv module depends on several
parameters, it is worth adding tests specifically for it.
This is also a precursor to make sure the `same` and `valid` paddings
are producing correct results.

Test Plan:

```python
python test/test_quantzation.py TestInputOutputShapes
```

Differential Revision: [D36536581](https://our.internmc.facebook.com/intern/diff/D36536581)

### CODE REVIEW

**Comment by z-a-f** [comment]
@z-a-f has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36536581).

**Comment by z-a-f** [comment]
@z-a-f has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36536581).

**Review by HDCharles — APPROVED** [review]
looks good

**Comment by z-a-f** [comment]
@z-a-f has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36536581).

**Pull request closed without merging**
