### PR TITLE
Add env var PYTORCH_TEST_RUN_EVERYTHING_IN_SERIAL=1 that allows running unit test suites in serial

### PR DESCRIPTION
**Pull request by xwang233**
Running unit test suites in parallel sometimes creates unexpected errors. This PR adds an option that allows unit test suites to be executed in serial, by setting PYTORCH_TEST_RUN_EVERYTHING_IN_SERIAL=1.

### CODE REVIEW

**Comment by huydhn** [comment]
cc @clee2000 Do we already have option for this in the CI? I guess this toggle can be added if there is a need for it

**Review by malfet — APPROVED** [review]
LGTM, but please consider extending the functionality similar to how it was done in https://github.com/pytorch/pytorch/pull/90902 (also, having a CLI option in addition to envvar would be great)

**Review by ptrblck — APPROVED** [review]

**Comment by clee2000** [comment]
> cc @clee2000 Do we already have option for this in the CI? I guess this toggle can be added if there is a need for it

setting the env var PYTORCH_TEST_CUDA_MEM_LEAK_CHECK should do pretty much the same with the addition of getting cuda mem leak checks

**Comment by xwang233** [comment]
Thanks @clee2000 for the suggestions. It indeed lets unit tests run in serial, but sometimes we don't want to introduce the extra cuda memory leak check, which may take too much extra time.

**Pull request closed without merging**
