### PR TITLE
Convert profiler schedule to a functor for serialization

### LINKED ISSUE #64492: AttributeError: Can't pickle local object 'schedule.<locals>.schedule_fn'
## To Reproduce

When using PyTorch Kineto Profiler with PyTorch Lightning and ddp_spawn accelerator, 
the schedule_fn is not pickable https://github.com/pytorch/pytorch/blob/master/torch/profiler/profiler.py#L24.

Solution, take it out of the function.

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by robieta**
Fixes #64492

Functions generated from factories are not pickleable, but classes are. The one behavior change from this PR is that we no longer enforce kwargs for the ctor. Dataclasses are getting keyword-only support, but only in 3.10. (Which means we won't be able to use it until 3.13 or 3.14...)

Test plan: existing unit tests, plus a line for pickling.

### CODE REVIEW

**Comment by robieta** [comment]
The windows test failure does not appear to be caused by this PR.

**Review by gdankel — APPROVED** [review]

**Comment by Data-drone** [comment]
Just wondering has there been any progress on this?

**Comment by fshart** [comment]
it seems, that this PR was closed despite having one approval.
Furthermore, the code could be merged.

Therefore I would like to know, what would be needed to revive this PR?

**Comment by fshart** [comment]
@robieta I re-implemented your changes into a pytorch version from yesterday to work around merge conflicts.

The only difference should be, that i kept the following code block
`        assert self.wait >= 0 and self.warmup >= 0 and self.active > 0 and \
           self.repeat >= 0 and self.skip_first >= 0, "Invalid profiler schedule arguments"`

**Pull request closed without merging**
