### PR TITLE
linalg_solve_triangular should not be a method

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #74054

Fix a function that was incorrectly exposed.

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Thanks!

I am curious how the codegen handes this case where there is a `python_module` and a method?
Is that something we should programmatically forbid?

**Comment by Lezcano** [comment]
I think module + method should be forbidden by the codegen. cc @ezyang

**Comment by ezyang** [comment]
yeah agreed. Should be easy, anyone wanna send us the PR?

**Comment by Lezcano** [comment]
I'm currently on PTO. I could send a fix in 2 weeks if that works

**Pull request closed without merging**
