### PR TITLE
[EASY] Adding virtual to the isUnionType op

### PR DESCRIPTION
**Pull request by Gamrix**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #69554

Differential Revision: [D33750966](https://our.internmc.facebook.com/intern/diff/D33750966)

### CODE REVIEW

**Comment by Gamrix** [comment]
Basically this function returns the wrong result if is not virtual.

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Comment by Gamrix** [comment]
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33750966).

**Comment by Gamrix** [comment]
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33750966).

**Comment by Gamrix** [comment]
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33750966).

**Pull request closed without merging**
