### PR TITLE
[LT] Store OpKind for each IR subclass in a static field

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #76738
* __->__ #76711

Summary: Currently OpKind is stored as an object field called op_ for each IR
node, and one usage of op_ is to avoid dynamic_cast in NodeCast when we
need to downcast a base-node pointer into a concrete sub-node pointer.
As a result, we need to construct and pass in an op when downcasting
nodes, and this becomes quite anonnying when we start to implement the
trie-based IR node reusing. More importantly, the op for each subclass
should be unique for that subclass and thus making it a const static field
is a more logical design.

In this PR, we still keep the object-level op_ for easier XLA adoption. As
furture work, we can come back to remove op_, make the op() method
virtual, and get rid of OpKind in all the node constructors.

### CODE REVIEW

**Comment by desertfire** [comment]
@wconstab and @JackCaoG ,  this PR is ready to be reviewed. I am keeping op_ in the base Node and the original NodeCast in this version.

**Review by wconstab — APPROVED** [review]
this looks good to me.

@JackCaoG wdyt? you will have to make sure your build system captures new LazyIr.cpp.

side note for later, I have been meaning to move some of the generated IR stuff into .cpp, it should be better for compile time, so at some point we could expand your LazyIr.cpp to include method bodies too.

**Comment by JackCaoG** [comment]
I will take a look today

**Comment by JackCaoG** [comment]
If I understand correctly, nothing needs to be done for pt/xla right now. Gerenated op with have static class memeber `class_op_kind`. When PyTorch/XLA migrate to GraphExecutor, we also need to define `class_op_kind` for all of the remaining ops. I guess this also means I need to drop all of the `GenericOp` too.

**Review by JackCaoG — APPROVED** [review]
Thanks Bin!

**Comment by wconstab** [comment]
> If I understand correctly, nothing needs to be done for pt/xla right now. Gerenated op with have static class memeber `class_op_kind`. When PyTorch/XLA migrate to GraphExecutor, we also need to define `class_op_kind` for all of the remaining ops. I guess this also means I need to drop all of the `GenericOp` too.

I don't think you should have to drop generic ops to migrate to GraphExecutor.  If GraphExecutor calls the new interface today I think we could change that temporarily to smooth your transition. @desertfire wdyt?

**Comment by desertfire** [comment]
> > If I understand correctly, nothing needs to be done for pt/xla right now. Gerenated op with have static class memeber `class_op_kind`. When PyTorch/XLA migrate to GraphExecutor, we also need to define `class_op_kind` for all of the remaining ops. I guess this also means I need to drop all of the `GenericOp` too.
> 
> I don't think you should have to drop generic ops to migrate to GraphExecutor. If GraphExecutor calls the new interface today I think we could change that temporarily to smooth your transition. @desertfire wdyt?

TrieCache is to be implemented in a way that we can simply ignore unsupported ops. So Generic shouldn't really be a problem here. But for future cleanup, we do need to take care of that.

**Pull request closed without merging**
