### PR TITLE
Add AMP support to linalg.vecdot.

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108165

We follow the same rules as matmul.

Fixes https://github.com/pytorch/pytorch/issues/108127

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Do we have any testing for these?

**Comment by lezcano** [comment]
We just have generic tests for CPU, not for GPU... Is it alright if I leave it like this?

**Pull request closed without merging**
