### PR TITLE
[DataPipe] Change interface generation process to revert back to original working process

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #75602

Fixes one part of https://github.com/pytorch/data/issues/343

### CODE REVIEW

**Review by ejguan — COMMENTED** [review]
Is there way not to change directory to cover the same functionality. Changing cwd is kind dangerous IMHO.

**Comment by NivekT** [comment]
> Is there way not to change directory to cover the same functionality. Changing cwd is kind dangerous IMHO.



> Is there way not to change directory to cover the same functionality. Changing cwd is kind dangerous IMHO.

I see, I just got rid of all the changes to working directory. Let me know if this is better.

**Review by ejguan — APPROVED** [review]
Thanks, LGTM

**Pull request closed without merging**
