### PR TITLE
Update torch-xpu-ops commit pin

### PR DESCRIPTION
**Pull request by guangyey**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #139041

# Motivation
This PR intends to update torch-xpu-ops commit pin. It mainly includes the following two highlighted changes:
1. split the DLL library into 4 smaller libraries to avoid the 2G limitation on Windows;
2. some new operators added, for example, `cdist`, `pdist`, `maxunpool2d`, `maxunpood3d`, `upsample_trilinear3d, `Bessel operators`, etc...

# Additional Context
We have to supply XPU device check logic in `cdist` and `pdist` ops.
This PR depends on https://github.com/pytorch/pytorch/pull/139050 to fix Windows build issue.

### CODE REVIEW

**Review by EikanWang — APPROVED** [review]

**Comment by guangyey** [comment]
@malfet and @atalman May I know if you could help review this PR?

**Review by EikanWang — APPROVED** [review]

**Comment by EikanWang** [comment]
https://github.com/pytorch/pytorch/pull/139050 landed.

**Comment by ZzEeKkAa** [comment]
Please include this fix https://github.com/intel/torch-xpu-ops/pull/1032 to the PR

**Review by ezyang — APPROVED** [review]

**Comment by guangyey** [comment]
> Please include this fix [intel/torch-xpu-ops#1032](https://github.com/intel/torch-xpu-ops/pull/1032) to the PR

This is not must to have. Let's include this PR in the next commit update.

**Comment by guangyey** [comment]
@ezyang Thanks very much~

**Pull request closed without merging**
