### PR TITLE
[Docs] Update links

### LINKED ISSUE #128774: Link https://pytorch.org/docs/stable/nn.html#torch.nn.EmbeddingBag may not exist anymore
### 📚 The doc issue

In https://pytorch.org/docs/stable/generated/torch.ao.nn.quantized.EmbeddingBag.html it says "please see https://pytorch.org/docs/stable/nn.html#torch.nn.EmbeddingBag for documentation".

https://pytorch.org/docs/stable/nn.html#torch.nn.EmbeddingBag  may not exist anymore as it opens to https://pytorch.org/docs/stable/nn.html.

Happy to make a PR to fix this.

### Suggest a potential alternative/fix

Remove that snippet?

Find the updated link?

cc @svekars @brycebortree

### PR DESCRIPTION
**Pull request by malfet**
From 
https://pytorch.org/docs/stable/nn.html#torch.nn.Embedding to 
https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html

And from 
https://pytorch.org/docs/stable/nn.html#torch.nn.EmbeddingBag  to 
https://pytorch.org/docs/stable/generated/torch.nn.EmbeddingBag.html

Fixes https://github.com/pytorch/pytorch/issues/128774

### CODE REVIEW

**Comment by vadimkantorov** [comment]
@malfet might also be good to have just a JavaScript hack in nn.html which would redirect to the new pages for a pre-fixed bunch of old window.location.hash, there must be a lot of "old" links lying around the internet...

**Comment by malfet** [comment]
@vadimkantorov that's a good point, let me find out which PR did that and file an issue to track the problem (and perhaps get them fixed/avoid making such changes in the future)

**Review by atalman — APPROVED** [review]

**Comment by malfet** [comment]
@vadimkantorov let me reopen this issue and it it to a triage review today. Though I guess, as 4 years have passed there are probably not that much urgency to it (I though it was a recent regression)

**Pull request closed without merging**
