### PR TITLE
[PyTorch] Update SmallVector from LLVM

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #68483
* #68412
* __->__ #69110

I pasted the current LLVM code, reapplied the modifications listed in the code comments, caught a few more in the diff/build process. The trivially copyable detection is different now; if gcc builds fail, will try reverting to C10_IS_TRIVIALLY_COPYABLE or copying what LLVM is doing.

The motivation for this change is that, as noted in an existing comment, C10_IS_TRIVIALLY_COPYABLE did the wrong thing for std::unique_ptr, which caused problems with D32454856 / #68412.

Differential Revision: [D32733017](https://our.internmc.facebook.com/intern/diff/D32733017/)

### CODE REVIEW

**Comment by bhosmer** [comment]
At a high level this seems like it heavily churns some critical-path code, and I'm not clear what the benefit is. Are there specific improvements in the new implementation that would be hard to backport? 

Adding more eyeballs - @ngimel @bdhirsh interested in your thoughts.

**Comment by swolchok** [comment]
> At a high level this seems like it heavily churns some critical-path code, and I'm not clear what the benefit is. Are there specific improvements in the new implementation that would be hard to backport?
> 
> Adding more eyeballs - @ngimel @bdhirsh interested in your thoughts.

I don't think there is a difference in outcomes between backporting all changes LLVM has made since we synced and re-syncing + reapplying the changes we made. Where I think we may disagree is that I don't see why we should reject any upstream changes.

**Comment by bhosmer** [comment]
> I don't think there is a difference in outcomes between backporting all changes LLVM has made since we synced and re-syncing + reapplying the changes we made. Where I think we may disagree is that I don't see why we should reject any upstream changes.

I guess choosing to reject or accept depends on understanding what all the changes even are - that's my main concern, given how prominently SmallVector figures in the hottest parts of the setup. Backporting would force that understanding, though admittedly at the risk of introducing bugs.

If you've gone through the new version and have a sense of what all the changes are, it would be great if you could write up a brief description of them, otherwise this PR feels basically just like blindly dumping in a new implementation of something that wasn't a problem, and hoping our tests catch any issues.

**Comment by swolchok** [comment]
> wasn't a problem

it was definitely a problem. There is a doc comment that it did the wrong thing for std::unique_ptr; now it works (and is why I'm dropping in the fix).

**Comment by swolchok** [comment]
>  blindly dumping in a new implementation 

it's from LLVM. this code sees production use all over the world. we're more likely to have problems by blindly snapshotting some random old version of a project and never importing known fixes.

**Comment by swolchok** [comment]
>  Backporting would force that understanding, 

I had to do a significant amount of manual fixing to merge in our changes (see updates to comment listing the changes for some that weren't listed). There weren't any scary conflicts.

**Comment by swolchok** [comment]
I'll go ahead and import https://github.com/llvm-mirror/llvm/blob/master/unittests/ADT/SmallVectorTest.cpp as well. Hopefully, that will help demonstrate that the merged component is working fine.

**Comment by bhosmer** [comment]
> There is a doc comment that it did the wrong thing for std::unique_ptr; now it works (and is why I'm dropping in the fix).

AH ok - that info is definitely worth putting in the PR description :) 

Of course you're right that an LLVM class like this is gonna be vetted by heavy real-world use. My worry was more about sneaky ways PT might be depending on particular behavior of the earlier version, plus bugs introduced by our own changes. We'll have to rely on our own tests for the former, which'll give us some fairly high coverage level but clearly not 100% (witness whatever the problem was with unique_ptr going undetected). But I think the latter is well covered by the LLVM tests, thanks for adding them.

Oh adjacent question - do we have any visibility into perf changes in either direction? I tried looking up a couple of the experiments in phab but they all errored out on fetching experiment data.

Assuming perf isn't affected, I'm comfortable with this given the addition of the LLVM tests (though please do motivate the change with a sentence or two in the PR description). But ideally somebody who's going to be living with the change more closely than me will make sure they're comfortable with it too - if one of the reviewers in PT core wouldn't mind taking a pass to check comfort level, that'd be good. I'll accept If nobody's raised any concerns in the next day or so. cc @ngimel @bdhirsh @albanD @mruberry

**Comment by albanD** [comment]
It would be nice to have some basic benchmark to make sure nothing horribly wrong happened no?

**Comment by swolchok** [comment]
> perf

I spot-checked an internal use case I've been working on; looks neutral. Also started a framework overhead benchmark run on the Phabricator diff.

I can't imagine a world where we end up not taking this change. We'd have to find a perf bug in upstream LLVM that was specifically a regression from the last 3-5 years.

**Comment by albanD** [comment]
> We'd have to find a perf bug in upstream LLVM that was specifically a regression from the last 3-5 years.

It is possible that we use it in a way that they explicitly don't expect this to be used and so don't care about perf regression.
But this is not a blocker I was just asking as a sanity check.
SGTM otherwise.

**Comment by swolchok** [comment]
framework overhead result is now available on the Phabricator diff. It looks fine to me.

**Review by bhosmer — APPROVED** [review]

**Review by mruberry — APPROVED** [review]
Always great to modernize the code base -- I kicked off a broader test run just in case

**Comment by albanD** [comment]
@swolchok https://github.com/pytorch/pytorch/issues/69722 is still ongoing I think. That would cause some random build failures.

**Comment by swolchok** [comment]
OK, I'm going to go ahead and bypass the failures since all the normal stuff & internal tests are green.

**Pull request closed without merging**
