### PR TITLE
[aot_inductor] move CppWrapperCodeGen into a separate file

### PR DESCRIPTION
**Pull request by chenyang78**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #119871
* #119870

This reverts commit d8e319a961bb872027f0abdc413d6beb7502ac9b.

cc @albanD @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @kadeng @muchulee8 @aakhundov @ColinPeppler

Differential Revision: [D53817853](https://our.internmc.facebook.com/intern/diff/D53817853)

### CODE REVIEW

**Comment by chenyang78** [comment]
@albanD This PR does the same refactoring as the one that you approved (https://github.com/pytorch/pytorch/pull/119491), which was reverted. Could you help approve this one? Thanks!

**Comment by albanD** [comment]
All the PRs in the stack have the same name? Could you clean this up because I'm not sure what this is?

**Comment by chenyang78** [comment]
> All the PRs in the stack have the same name? Could you clean this up because I'm not sure what this is?

@albanD They look similar but not the same. One is "move CppWrapperCodeGen", and the other is "move CudaWrapperCodeGen". The CppWrapperCodeGen one exceeds the line limit. Thanks.

**Comment by albanD** [comment]
I think think that you should remove the revert revert ... 
This doesn't really makes the PR readable (or the commit that is going to end up in main).
That is in particular confusing when we work on release notes!

**Comment by chenyang78** [comment]
> I think think that you should remove the revert revert ... This doesn't really makes the PR readable (or the commit that is going to end up in main). That is in particular confusing when we work on release notes!

Done. I wasn't very sure about the protocol :) Thanks for the suggestion, which makes sense.

**Review by albanD — APPROVED** [review]
Sounds good to skip PR sanity check as this is a code move

**Comment by chenyang78** [comment]
@chenyang78 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D53817853).

**Review by khabinov — APPROVED** [review]

**Comment by chenyang78** [comment]
@chenyang78 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D53817853).

**Pull request closed without merging**
