### PR TITLE
[Pytorch][ATEN] Enable FP8 NCCL in Pytorch ATEN

### PR DESCRIPTION
**Pull request by jiawenliu64**
Summary: Enable FP8 NCCL in Pytorch ATEN to unblock FP8 collective communication such as FP8 all-to-all

Test Plan: CI & D64374424

Differential Revision: D64866426

cc @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by eqy — APPROVED** [review]
Does this need a test?

**Comment by jiawenliu64** [comment]
> Does this need a test?

Yeah, added new tests to cover changes

**Review by jianyuh — APPROVED** [review]

**Pull request closed without merging**
