### PR TITLE
Add decompositions for copy variants of view ops

### PR DESCRIPTION
**Pull request by rec**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128400

### CODE REVIEW

**Comment by rec** [comment]
NOTE: I folded into this commit the changes from https://github.com/pytorch/pytorch/pull/128142 and https://github.com/pytorch/pytorch/pull/127231, because there is considerable overlap between those pull requests and this one.

Once those two pull requests have been merged, I'll rebase this one to make those changes go away.

**Comment by peterbell10** [comment]
> NOTE: I folded into this commit the changes from https://github.com/pytorch/pytorch/pull/128142 and https://github.com/pytorch/pytorch/pull/127231, because there is considerable overlap between those pull requests and this one.

This is really what `ghstack` is meant for. You submit all the changes in one big stacked diff and they can depend on each other without polluting each PR with changes from PRs it depends on.

**Comment by rec** [comment]
Ach, yes, I "knew" that but didn't actually know it as in using it.

Question - if you have three commits, ABC, and you find an issue with A, you can just rebase the delta/fixup commit back into A and it will all flow through?

**Comment by peterbell10** [comment]
Yes, use `git rebase -i` to adjust the commits in any way you like and as long as the `ghstack` metadata is preserved at the bottom of the commit message then the next time you run `ghstack` all the PRs will be updated to match your local branch.

**Pull request closed without merging**
