### PR TITLE
[inductor] Enable subprocess-based parallel compile as the default

### PR DESCRIPTION
**Pull request by masnesral**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #127401
* __->__ #126817
* #128086
* #128037

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

Differential Revision: [D58239826](https://our.internmc.facebook.com/intern/diff/D58239826)

### CODE REVIEW

**Review by eellison — APPROVED** [review]

**Comment by masnesral** [comment]
@masnesral has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D58056502).

**Comment by huydhn** [comment]
@pytorchbot revert -m 'There are lots of flaky inductor failure showing up in trunk after this commit https://hud.pytorch.org/pytorch/pytorch/commit/cf77e7dd9770caf65e898ac2ee82045aa0408e30, so I am trying to revert this to see if this helps' -c weird

https://hud.pytorch.org/hud/pytorch/pytorch/3bcc3cddb580bf0f0f1958cfe27001f236eac2c1/1?per_page=50&name_filter=inductor%20%2F%20

**Comment by huydhn** [comment]
It's highly likely, you can see that inductor jobs recovered after the change was reverted here https://hud.pytorch.org/hud/pytorch/pytorch/9a25ff77af932b59899f337a7a8dffbaab166ecf/1?per_page=50&name_filter=inductor

**Comment by masnesral** [comment]
@masnesral has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D58239826).

**Pull request closed without merging**
