### PR TITLE
Optimize reduce ops for 2d and 3d

### PR DESCRIPTION
**Pull request by xiaomengy**
Summary: Optimize reduce ops for 2d and 3d

Differential Revision: D9042505

### CODE REVIEW

**Comment by houseroad** [comment]
Seems hip still has compilation errors, and incurs segmentation fault on `caffe2/python/convnet_benchmarks_test.py::TestConvnetBenchmarks::testConvnetBenchmarks`

**Comment by bddppq** [comment]
@petrex @ashishfarmer @rohithkrn We probably should also hipify math_hip, otherwise we can never catch up the speed of @BIT-silence

**Comment by petrex** [comment]
thanks, we will look into this PR

**Comment by BIT-silence** [comment]
I will update this PR to make build and test passed. But I cannot guarantee they can be optimized as well as the CUDA side.

**Review by houseroad — APPROVED** [review]
LGTM, thanks

**Pull request closed without merging**
