### PR TITLE
[DistAutograd x JIT] Capture global state, dist autograd current context id, before thread switching triggered by JIT future.wait()

### PR DESCRIPTION
**Pull request by xush6528**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#36395 [DistAutograd x JIT] Capture global state, dist autograd current context id, before thread switching triggered by JIT future.wait()**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D7857991/)

titled

Differential Revision: [D7857991](https://our.internmc.facebook.com/intern/diff/D7857991/)

### CODE REVIEW

**Comment by xush6528** [comment]
TODO: add a unit test to guard this use case.

**Review by pritamdamania87 — APPROVED** [review]
Can we also add a unit test that would've failed without this fix?

**Comment by jjlilley** [comment]
@xush6528 - thanks for fixing this!

Re: a test case - if it's straightforward to construct something, let's do it. My only concern is making this a hard requirement and delaying a straightforward correctness fix like this for a week. The existing c++ test coverage is frankly fairly weak - not that it shouldn't be fixed, but it's not unreasonable to do that out-of-band.

**Comment by xush6528** [comment]
@jjlilley 

It's an easy test case. make 2 rpcs in torch script and check every time we get gradients back.

Without this fix, only for the tensors passed in the first rpc can get gradients back.

**Pull request closed without merging**
