### PR TITLE
[reland] add numpy typing plugin to mypy config

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #94526
* __->__ #94525

reland of https://github.com/pytorch/pytorch/pull/92930

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by Skylion007 — CHANGES_REQUESTED** [review]
Hmm, to not fail on reland, I think it needs to have a minimum numpy version (1.20) for numpy typing.

**Comment by wanchaol** [comment]
> Hmm, to not fail on reland, I think it needs to have a minimum numpy version (1.20) for numpy typing.

@Skylion007 Thanks! I updated the old CI to a newer numpy version, it's ready for another review :)

**Review by huydhn — APPROVED** [review]
LGTM! If you wonder where the heck Windows numpy comes from, it's from here https://github.com/pytorch/test-infra/blob/main/aws/ami/windows/scripts/Installers/Install-Conda-Dependencies.ps1#L17

**Comment by wanchaol** [comment]
> LGTM! If you wonder where the heck Windows numpy comes from, it's from here https://github.com/pytorch/test-infra/blob/main/aws/ami/windows/scripts/Installers/Install-Conda-Dependencies.ps1#L17

thanks @huydhn! Shall we worry about windows numpy version, I saw the version is < 1.23 so I think it should still looks good to us?

**Comment by huydhn** [comment]
> thanks @huydhn! Shall we worry about windows numpy version, I saw the version is < 1.23 so I think it should still looks good to us?

I think we are good.  I double check.  Windows has `numpy==1.21.5`

**Pull request closed without merging**
