### PR TITLE
Update PyTorch/XLA git clone branch name for 1.12

### PR DESCRIPTION
**Pull request by wonjoo-wj**
Update PyTorch/XLA git clone branch name for 1.12 as we prepare for PT/XLA 1.12 release.

### CODE REVIEW

**Comment by wonjoolee95** [comment]
Seems like an unrelated test failing, related to https://github.com/pytorch/pytorch/issues/77944. @malfet, can I get a quick review when you have the time? Thanks!

**Review by malfet — APPROVED** [review]
LGTM

**Comment by wonjoolee95** [comment]
Local git history got messed up, will open a new one.

**Comment by wonjoolee95** [comment]
Opened instead -- https://github.com/pytorch/pytorch/pull/78315.

**Comment by malfet** [comment]
Wow, this is a nice bug <- merge bot should not be used for release branches...

**Comment by wonjoolee95** [comment]
Oh didn't know about that..

**Pull request closed without merging**
