### PR TITLE
[MPS] Add support for autocast (#376)

### LINKED ISSUE #88415: Enable AMP for MPS devices
### 🚀 The feature, motivation and pitch

https://github.com/pytorch/pytorch/issues/78168 States that fp16 support for mps devices in general should be possible, but autocas only works with `cpu` and `cuda` device types. When enabling it manually, on mps it does not show any additional conversions:

```python
>>> torch.set_autocast_enabled(True)
>>> with capture_logs(is_mode=True) as logs, LoggingTensorMode():
...     a = torch.rand(10, 10, dtype=torch.float, device='mps')
...     b = torch.rand(10, 10, dtype=torch.float, device='mps')
...     c = torch.addmm(a, a, b)
>>> for l in logs:
...     print(l)
```

prints the following:
```
$0 = torch._ops.aten.rand.default([10, 10], dtype=torch.float32, device=device(type='mps'), pin_memory=False)
$1 = torch._ops.aten.rand.default([10, 10], dtype=torch.float32, device=device(type='mps'), pin_memory=False)
$2 = torch._ops.aten.addmm.default($0, $0, $1)
```

given the fp16 support, it would be nice to have autocast and amp in general working on MPS devices as well

### Alternatives

_No response_

### Additional context

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5 @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev as per our discussion on slack.

### PR DESCRIPTION
**Pull request by janboeye**
This is based on https://github.com/pytorch/pytorch/pull/99272

Fixes #88415 

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Comment by AugustDev** [comment]
Is this ready to be merged @janboeye ?

**Comment by kulinseth** [comment]
@skotapati , is updating the PR with rebase and test fixes:
https://github.com/pytorch/pytorch/pull/99272

can we wait for that before we merge this ?

**Review by kulinseth — CHANGES_REQUESTED** [review]
https://github.com/pytorch/pytorch/pull/99272
There is an original PR we are using to land the feature

**Comment by janboeye** [comment]
> #99272 There is an original PR we are using to land the feature

@kulinseth I'm ok to wait for you to merge the original PR. Thanks for your work!

**Pull request closed without merging**
