### PR TITLE
Port torch.range to aten and parallelize on CPU.

### PR DESCRIPTION
**Pull request by gchanan**

### CODE REVIEW

**Comment by gchanan** [comment]
performance numbers to follow.

**Comment by vadimkantorov** [comment]
This seems to also have this bug about checking the bounds for inf/nan/large values: https://github.com/pytorch/pytorch/pull/13915

**Comment by gchanan** [comment]
@vadimkantorov looks like you are right, but this function is deprecated.  arange which I will port shortly has the correct behavior.

**Comment by gchanan** [comment]
I don't know if that's the best idea -- it checking code in arange changes calculations on integer types.  I just added some very minimal checking and filed https://github.com/pytorch/pytorch/issues/15493.

**Review by colesbury — APPROVED** [review]

**Pull request closed without merging**
