### PR TITLE
New Helper Class for Optimization Passes

### PR DESCRIPTION
**Pull request by Gamrix**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #63198
* #64251
* __->__ #64250

This helper class includes common patterns, such as getting the AliasDb
and iterating over the blocks of a Torchscript IR.

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
Unless we want to do the work of migrating over every optimization pass to this common infrastructure, I do not think we should land this. Having the code base be half and half is not a good state to be in. Common pass infastructure could be generically good but IMO there are more pressing better engineering type work to do.

**Comment by Gamrix** [comment]
I don't see the big harm in being in a half-half state. Currently the compiler passes are all a hodge podge of copy-pasted code from other optimization passes. Having some optimization passes that share common code would mean that we would have less copies of the compiler pass boilerplate around everywhere.

**Comment by eellison** [comment]
For one, the pass here you've added changes the iteration order of other passes.  Most of them are previously depth-first search, and now they are no longer. It would be very easy to use this wrong unintentionally, and it would be even easier if this is only used in one or two optimization passes. The `hodge podge of copy-pasted code` amounts to `getOrCreateAliasDb`, which does not apply to all optimizations, and the iteration through the sunblocks, which would be unintentionally altered and is what ~5 lines of code? CC @ZolotukhinM  and @Krovatkin for other opinions but I really do not want to be in a half - state, or in a state where some passes use abstractions that make the code harder to read

**Review by eellison — COMMENTED** [review]
If you want to get rid of the Block iterating copy-pasta I suggest you use https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/runtime/graph_iterator.h, which is an abstraction which someone added and used once but didn't integrate into the codebase and now mostly picks up dust

**Pull request closed without merging**
