### PR TITLE
Add PR number to metrics when available

### PR DESCRIPTION
**Pull request by ZainRizvi**
### <samp>🤖 Generated by Copilot at 780bfa6</samp>

Add a new metric for pull request number in `tools/stats/upload_metrics.py`. This allows tracking the CI performance of pull requests.

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Review by malfet — APPROVED** [review]
Why do we need a number, rather than just `true`/`false` value?

**Comment by ZainRizvi** [comment]
> Why do we need a number, rather than just `true`/`false` value?

This is adding the pr number to th emetric. It's in string form as an env_var, and the "int" param says to convert that string into an int before emitting it

**Review by clee2000 — APPROVED** [review]

**Pull request closed without merging**
