### PR TITLE
[FX] Prototype for guarding against mutable operations in tracing

### PR DESCRIPTION
**Pull request by jamesr66a**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #64295

This adds functionality to `TracerBase` that will throw if a mutating operation (e.g. `out` variant) is traced. This is currently gated behind a feature flag `check_mutable_operations`. Example error:
```
RuntimeError: Tried to trace mutable operation aten::sigmoid.out(Tensor self, *, Tensor(a!) out) -> (Tensor(a!)). FX only supports functional code, so operations that mutate operands in-place (e.g. via `out` arguments) are not supported
```

Differential Revision: [D30675780](https://our.internmc.facebook.com/intern/diff/D30675780)

### CODE REVIEW

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30675780).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30675780).

**Review by jfix71 — APPROVED** [review]
🚀

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30675780).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30675780).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30675780).

**Comment by jamesr66a** [comment]
@jamesr66a has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30675780).

**Pull request closed without merging**
