### PR TITLE
Fixed type hints for CosineAnnealingWarmRestarts

### PR DESCRIPTION
**Pull request by vfdev-5**
Fixed type hints for CosineAnnealingWarmRestarts:
- `T_mult` is not `Optional[int]` but just `int`
- `eta_min` is not `Optional[float]` but just `float`
- removed `step` method specific annotation as it is compatible with the base class

https://github.com/pytorch/pytorch/blob/e132f09e8878418fb98a4b76a441a324452354ec/torch/optim/lr_scheduler.py#L1365-L1375

Otherwise, computation like this `self.T_i * self.T_mult` in `self.step` is not possible:
```
error: Unsupported operand types for * ("int" and "None")
```

### CODE REVIEW

**Comment by janeyx99** [comment]
Thanks for the change! I’m curious about the impact of removing the step annotation—how exactly is not having an annotation better?

**Comment by vfdev-5** [comment]
@janeyx99 removing incorrect annotation for `step` method is not removing completely the function annotation but removes the incorrect override as CosineAnnealingWarmRestarts inherits from LRScheduler. If you put `reveal_type` into stub file, mypy will report the following for this PR:
```
torch/optim/lr_scheduler.pyi:216:17: note: Revealed type is "builtins.int"
torch/optim/lr_scheduler.pyi:217:17: note: Revealed type is "builtins.float"
torch/optim/lr_scheduler.pyi:218:17: note: Revealed type is "def (self: torch.optim.lr_scheduler.LRScheduler, epoch: Union[builtins.int, None] =)"
```
and this is for `main`:
```
torch/optim/lr_scheduler.pyi:217:17: note: Revealed type is "Union[builtins.int, None]"
torch/optim/lr_scheduler.pyi:218:17: note: Revealed type is "Union[builtins.float, None]"
torch/optim/lr_scheduler.pyi:219:17: note: Revealed type is "def (self: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts, epoch: Union[Any, None] =) -> Any"
```

**Review by janeyx99 — APPROVED** [review]
Ah, understood. Thanks!

**Pull request closed without merging**
