### PR TITLE
[Pytorch] Build lite interpreter as default for Android

### PR DESCRIPTION
**Pull request by cccclai**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#55734 [Pytorch] Build lite interpreter as default for Android**

Summary:
Build lite interpreter as default for android, should wait until https://github.com/pytorch/pytorch/pull/56002 lands
Mainly two changes:
1. Use lite interpreter as default for Android
2. Switch the lite interpreter build test to full jit build test
Test Plan:
image
Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D27695530](https://our.internmc.facebook.com/intern/diff/D27695530)

### CODE REVIEW

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27695530).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27695530).

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27695530).

**Comment by ljk53** [comment]
Are lite interpreter and full JIT mutually exclusive? i.e. if the flag is set then will it stop run full JIT model?

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27695530).

**Comment by cccclai** [comment]
> Are lite interpreter and full JIT mutually exclusive? i.e. if the flag is set then will it stop run full JIT model?

After this flag is set, the libtorch deployed in Android device will be libtorch_lite. It can run model generated by `__save_for_mobile()`. As a mitigation, user can still build full jit from source by switching the flag, and deploy it on device. If it's helpful, we can also have nightly builds for both jit and lite interpreter. Do you have any concern about it?

**Review by IvanKobzarev — APPROVED** [review]

**Comment by cccclai** [comment]
@cccclai has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27695530).

**Comment by bigfootjon** [comment]
Internal commit was malformed, which left this PR open. Closing manually

**Comment by cccclai** [comment]
Closing, merged in with https://github.com/pytorch/pytorch/commit/0c3db1cb33cda1de61c754f14e7bfd2c53ea6d07

**Pull request closed without merging**
