### PR TITLE
Allow TensorMethods.h to include Dispatcher.h

### PR DESCRIPTION
**Pull request by smessmer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #23695 [wip] Fixed size arrays
* #23668 [wip] Call aten ops through c10 dispatcher
* **#23684 Allow TensorMethods.h to include Dispatcher.h**
* #23667 [wip] Register ATen ops with c10
* #23748 Disambiguate tensor and string ops
* #23694 toString(FunctionSchema) shows overload name
* #23666 [wip] c10 dispatcher stores autograd kernels
* #23665 Allow kernels that don't have a boxed version
* #23447 Unboxed kernels in c10
* #23834 Open up AliasAnalysisKind for any ops

This is not doing any functional changes, only moving code around.

Just including Dispatcher.h from TensorMethods.h without the changes from this PR triggers quite a few include cycles unfortunately.
This PR fixes these cycles, mostly by splitting some headers into a pure header and an "_impl.h" header.

Differential Revision: [D16607523](https://our.internmc.facebook.com/intern/diff/D16607523/)

### CODE REVIEW

**Review by dzhulgakov — COMMENTED** [review]
Hm, that's a lot of code movement. Is it all because Tensor.h class is quite at the bottom of dependency chain whereas TensorMethods.h are at the top (e.g. depends on dispatcher).

Similar problems will probably occur in the future with other files, and splitting all headers into .h and _inl.h is quite annoying. I wonder whether we can do the following:
- rename core/Tensor.h into TensorBody.h
- be diligent about importing only TensorBody.h in any parts of the library that are internal - IValue, Dispatcher, FunctionSchema, etc
- create Tensor.h for compatibility reasons that imports TensorBody.h and TensorMethods.h

If I understand the dependency chain correctly, in this case you won't need movement of majority of the code here and it'd be more maintainable in the future. But I might be missing something.

Also, cc @ezyang who looked at it last year I think

**Comment by ezyang** [comment]
Can you explain what the previous structure is, and what the new structure is, conceptually speaking?

**Comment by smessmer** [comment]
The issue is this dependency chain:

- Tensor includes TensorMethods because we want the methods to be inline
- TensorMethods includes Dispatcher because it calls into the dispatcher
- Dispatcher includes FunctionSchema because it uses it to store operator schemas
- FunctionSchema includes IValue because it uses it to store default arguments
- IValue includes Tensor because it can hold Tensor objects

There have been some other similar include chains, but the basic problem is that these things all somehow depend on each other.

We could say we don't make TensorMethods inline but move them to a .cpp file as an alternative solution if we think that's better, but as long as we don't want to give up any of the goals above, we cannot break the dependency cycle.

Most of these dependencies, however, are towards the declaration and not the definition of a class. TensorMethods needs the declaration of the dispatcher, not its definition. The dispatcher declaration depends on the function schema declaration, but only the dispatcher definition depends on the function schema definition...
The classic solution to this problem (given that we don't have c++20's modules yet) is to split header files into declaration and definition files and only include things where they're needed. This is what this PR is doing.

Structurally, each header file got split into a declaration and definition file, and the includes that are only needed for the definition are now only included in the definition file and not in the declaration file.

I'll try the TensorBody approach as an alternative, but I'm not sure if it actually will cause less code to be moved.

**Comment by ezyang** [comment]
> TensorMethods needs the declaration of the dispatcher, not its definition

Err, you won't get inlining if you don't have the definition though, no?

> The dispatcher declaration depends on the function schema declaration, but only the dispatcher definition depends on the function schema definition...

Looking at the overall dependency structure you described, this is the dependency that I would have expected to not exist. Function schema shouldn't be involved when you actually do dispatch, right? So I expect that you don't need to reference it in inline definitions; they can all be out-of-line. Do you agree with this line of reasoning?

**Comment by smessmer** [comment]
> > TensorMethods needs the declaration of the dispatcher, not its definition
> 
> Err, you won't get inlining if you don't have the definition though, no?
> 

For calling into a dependency, the dependency must be included above the call site. For getting inlining, it's enough to include it anywhere in the same translation unit, i.e. it's enough to include it from the definition header file which in turn is included at the end of the declaration header file.

> > The dispatcher declaration depends on the function schema declaration, but only the dispatcher definition depends on the function schema definition...
> 
> Looking at the overall dependency structure you described, this is the dependency that I would have expected to not exist. Function schema shouldn't be involved when you actually do dispatch, right? So I expect that you don't need to reference it in inline definitions; they can all be out-of-line. Do you agree with this line of reasoning?

That might work. When calling an op through the dispatcher, the dispatcher needs to know which argument it has to look at to get the dispatch key and it needs the function schema for that., but that part could probably be precomputed and stored without storing the full schema.
The dispatcher also also needs the function schema for things like looking up an operator or registering a new operator and error checking the schema against the kernel signature. So it definitely needs to store a FunctionSchema. But I could maybe get away with moving everything that depends on the FunctionSchema definition into a .cpp file and having the header only depend on the FunctionSchema declaration if I store a unique_ptr<FunctionSchema> instead of a FunctionSchema by value - I'll see if that works.

**Comment by smessmer** [comment]
@ezyang it doesn't work unfortunately. The dispatcher doesn't necessarily need the function schema on the hot path (i.e. inline path), but it needs IValue on the hot path because it needs to look into the IValue to find the tensor dispatch key. That just shortens the cycle above, but it's still the same cycle.

I'll try @dzhulgakov 's idea of writing a `TensorBody` header now.

**Comment by ezyang** [comment]
> it needs IValue on the hot path because it needs to look into the IValue to find the tensor dispatch key

This sounds... wrong? I don't see why default argument should ever participate in dispatch resolution...

**Comment by smessmer** [comment]
> > it needs IValue on the hot path because it needs to look into the IValue to find the tensor dispatch key
> 
> This sounds... wrong? I don't see why default argument should ever participate in dispatch resolution...

I'm not talking about the default argument. Dispatch depends on IValue because it needs to look at the tensor argument that it is supposed to dispatch on.

**Comment by smessmer** [comment]
@dzhulgakov 's idea would work, see https://github.com/pytorch/pytorch/pull/23888 . It requires fewer changes, but is a less well known pattern. I'm fine to land either, not sure which is better.

**Comment by ezyang** [comment]
OK, let's go with @dzhulgakov's plan. (You're not actually turning on boxing for tensor method dispatch, are you?)

**Comment by smessmer** [comment]
@ezyang no, this is all still unboxed

**Comment by ezyang** [comment]
Then I find this comment confusing:

> Dispatch depends on IValue because it needs to look at the tensor argument that it is supposed to dispatch on.

Because there should be nary an IValue in sight if you're doing unboxed dispatch

**Comment by ezyang** [comment]
cc @bwasti

**Review by ezyang — APPROVED** [review]
Approving under the assumption this implements @dzhulgakov's plan (there's a lot of fuzz in this patch and I haven't reviewed it very closely)

**Comment by smessmer** [comment]
https://github.com/pytorch/pytorch/pull/23888 was landed as an alternative

**Pull request closed without merging**
