### PR TITLE
Fixed logsumexp ref for scalar case + made it a decomp

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #80023
* __->__ #80021

image

### CODE REVIEW

**Comment by Chillee** [comment]
@ngimel it's actually already being tested in one of the decomp tests, but I'll add it to the OpInfo.

**Comment by Chillee** [comment]
Added test case @ngimel

**Review by ngimel — APPROVED** [review]

**Comment by Chillee** [comment]
xla failure looks unrelated.

**Pull request closed without merging**
