### PR TITLE
[CI] Move CPU-only jobs to xenial

### PR DESCRIPTION
**Pull request by jamesr66a**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#24506 [CI] Move CPU-only jobs to xenial**

Differential Revision: [D16862005](https://our.internmc.facebook.com/intern/diff/D16862005)

Trusty is out of standard support, and a mismatch in the binutils version causes FBGEMM to not build in pytorch even with a compiler that supports AVX512. This makes it so we build all that stuff in the CPU CI jobs (and otherwise brings us into <current year>-3 instead of <current year>-5)

Built on top of https://github.com/pytorch/pytorch/pull/24795 (thanks @kostmo!)

### CODE REVIEW

**Review by ezyang — DISMISSED** [review]

**Comment by jamesr66a** [comment]
@ezyang FYI this still doesn't build with FBGEMM ostensibly due to a binutils version mismatch in 14.04. I think i'm just going to enable a Xenial CPU configuration instead

**Comment by jamesr66a** [comment]
Currently getting this error in the regen script:

```
+ ./generate_config_yml.py
Traceback (most recent call last):
  File "./generate_config_yml.py", line 127, in <module>
    stitch_sources(sys.stdout)
  File "./generate_config_yml.py", line 122, in stitch_sources
    f.write(output_filehandle)
  File "./generate_config_yml.py", line 43, in write
    self.function(build_dict)
  File "/home/jamesreed/pytorch/.circleci/cimodel/data/pytorch_build_definitions.py", line 272, in add_build_env_defs
    d = c.gen_yaml_tree(phase)
  File "/home/jamesreed/pytorch/.circleci/cimodel/data/pytorch_build_definitions.py", line 80, in gen_yaml_tree
    ("DOCKER_IMAGE", self.gen_docker_image_path()),
  File "/home/jamesreed/pytorch/.circleci/cimodel/data/pytorch_build_definitions.py", line 59, in gen_docker_image_path
    base_build_env_name = "-".join(parms_source.get_parms(True))```

**Comment by ezyang** [comment]
I updated the ECRs for the renaming to remove gcc7.3 to gcc7

**Comment by ezyang** [comment]
@kostmo on the regen script

**Comment by jamesr66a** [comment]
I just updated the regen script to use the old logic if the compiler is CUDA or android (and the asan special case). Seems to be producing the correct results now

**Review by ezyang — APPROVED** [review]
Thank you, this work is greatly appreciated.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
This Docker version upgrade did NOT update https://github.com/pytorch/ossci-job-dsl/blob/master/src/main/groovy/ossci/pytorch/DockerVersion.groovy . When you fail to update this file, the new stable Docker image will get deleted after it becomes two weeks old. Please update this file!

**Pull request closed without merging**
