### PR TITLE
Fix Dispatching not considering List[Optional[Tensor]] for dispatch

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#66506 Fix Dispatching not considering List[Optional[Tensor]] for dispatch**

Followup to https://github.com/pytorch/pytorch/pull/60787

It turns out that the original PR was wrong for unboxed kernels. We
recently ran into this in
https://github.com/facebookresearch/functorch/issues/124

For unboxed kernels, the correct type for a Tensor?[] argument is
actually `List<optional<Tensor>>`, not `ArrayRef<optional<Tensor>>`

Test Plan:
- assert that https://github.com/facebookresearch/functorch/issues/124
actually works

Differential Revision: [D31609714](https://our.internmc.facebook.com/intern/diff/D31609714)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
sure, but maybe should do a test this time? :)

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31609714).

**Comment by NivekT** [comment]
I just reverted this PR because it breaks [pytorch_xla_linux_bionic_py3_6_clang9_test](https://app.circleci.com/pipelines/github/pytorch/pytorch/405355/workflows/778a4241-3af1-4151-9f6a-7644669eccc9/jobs/16671305).

**Comment by NivekT** [comment]
> I just reverted this PR because it breaks [pytorch_xla_linux_bionic_py3_6_clang9_test](https://app.circleci.com/pipelines/github/pytorch/pytorch/405355/workflows/778a4241-3af1-4151-9f6a-7644669eccc9/jobs/16671305).

Please ignore this comment. This PR will remain merged and there is an XLA fix incoming.

**Pull request closed without merging**
