### PR TITLE
Move the OpInfo same-storage error to the autograd test

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #88306

This check was previously located at the `non_contiguous` test (quite
and odd location). Even more, at https://github.com/pytorch/pytorch/pull/86378#discussion_r993658395, Kshiteej found that this assert was not doing anything really.

We move it to the autograd test and make it a proper `self.assert`. We also disallow returning 1-tuples from sample_input functions, as they were breaking this assert.

### CODE REVIEW

**Comment by peterbell10** [comment]
>We also disallow returning 1-tuples from sample_input functions, as they were breaking this assert.

No objection to the change, but can you explain how it breaks this check?

**Comment by lezcano** [comment]
That's a good point.  I tried reproducing this issue and I was not able to, so I'm not sure now what was going there really.

I'm leaving them all as generators for simplicity and consistency of the code though.

**Review by mruberry — APPROVED** [review]
Cool! cc @peterbell10 @pmeier

**Pull request closed without merging**
