### PR TITLE
removed gelu from autocast fp32 list

### PR DESCRIPTION
**Pull request by Fuzzkatt**
Fixes #{issue number}

### CODE REVIEW

**Comment by ezyang** [comment]
@Fuzzkatt thanks for sending the PR, could you send us more motivation about why this is better?

**Comment by Fuzzkatt** [comment]
Gelu runs properly with pure fp16 inputs, so if there are no numerical issues, then it should be safe to remove from the autocast fp32 list.

**Comment by ezyang** [comment]
I guess, I will leave @mcarilli to make the final call, I don't see why the fact that gelu can run with pure fp16 inputs implies that you should remove it from the fp32 list.

**Comment by ezyang** [comment]
need cLA

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
