### PR TITLE
[quant][pt2e] Skip quantizing {add/mul} scalar

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #110308
* __->__ #110261

Summary:
otherwise delegation does not work and we'll need extra workaround to change scalar to tensor first, right now
we do not have an API for it in quantizer, we may add it in the future and re-enable quantization for {add/mul} scalar

Test Plan:
python test/test_quantization.py TestQuantizePT2E.test_add_scalar_not_quantized
python test/test_quantization.py TestQuantizePT2E.test_mul_scalar_not_quantized

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D49850004](https://our.internmc.facebook.com/intern/diff/D49850004)

### CODE REVIEW

**Review by kimishpatel — APPROVED** [review]
This one i have some concerns with because it can be very easily handled outside but will stamp for unblock.

cc: @mcr229

**Comment by mcr229** [comment]
I can add the pass in the quantizer_utils and handle outside instead. I've become less ambivalent about this decision, and if you feel it is fine to add the pass usage in the example, then I can go ahead and do it.

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D49850004).

**Comment by jerryzh168** [comment]
abandoning this one since we decided to use quant_utils to convert scalar to tensor

**Pull request closed without merging**
