### PR TITLE
Remove backward for im2col and col2im

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #85542

`im2col` is a linear map, and `col2im` is its adjoint. As such, the
adjoint to `col2im` is `im2col` (the adjoint of the adjoint is the
original function.

There's no point having explicit derivatives in ATen for these
functions, so this PR deletes all these.

Furthermore, along the way, we fix an error for the derivative of im2col
for non-batched inputs.

### CODE REVIEW

**Comment by lezcano** [comment]
@albanD @soulitzer could you have a look?

**Review by soulitzer — APPROVED** [review]
Thanks for the clean up!

**Review by ngimel — APPROVED** [review]
Awesome!

**Pull request closed without merging**
