### PR TITLE
Update DALLE2_pytorch expected accuracy result on CPU

### PR DESCRIPTION
**Pull request by huydhn**
I suspect that the issue shows up because of the new version of https://pypi.org/project/pyarrow/16.1.0/#history released yesterday.  The package is a dependency of DALLE2_pytorch https://github.com/pytorch/benchmark/blob/main/torchbenchmark/models/DALLE2_pytorch/install.py#L22.

I'll just update the expected accuracy result on CPU benchmark because the model fails to run there anyway.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by huydhn** [comment]
### Cherry picking #128718
The cherry pick PR is at https://github.com/pytorch/pytorch/pull/128920 and it is linked with issue DEBUG DEBUG

**Comment by huydhn** [comment]
### Cherry picking #128718
The cherry pick PR is at https://github.com/pytorch/pytorch/pull/128921 and it is linked with issue DEBUG DEBUG

**Comment by huydhn** [comment]
### Cherry picking #128718
The cherry pick PR is at https://github.com/pytorch/pytorch/pull/128923 and it is linked with issue DEBUG DEBUG. The following tracker issues are updated:
* https://github.com/pytorch/pytorch/issues/128436#issuecomment-2174846757

**Pull request closed without merging**
