### PR TITLE
Add generator for dropout

### PR DESCRIPTION
**Pull request by junjihashimoto**
This PR provides a functional dropout by adding generator argument.

### CODE REVIEW

**Comment by junjihashimoto** [comment]
image
Fix it to pass the test.

**Comment by mruberry** [comment]
@pbelevich Are you the right person to review this?

**Comment by junjihashimoto** [comment]
I intended to press the request for a review 2 minutes ago. It is an operation mistake.

**Comment by pbelevich** [comment]
@junjihashimoto  thanks for working on this feature! It seems that jit tests failed, could you please fix them?
Also, can you please add `test_dropout_generator` to `test_torch.py` and test that if you pass two instances of generators created with the same seed to `dropout` they return the same tensors? Similar to [test_generator_cpu](https://github.com/pytorch/pytorch/blob/bee97d5be0fc89e415c611054d1f6645a35e5577/test/test_torch.py#L2741-L2770)

**Review by pbelevich — CHANGES_REQUESTED** [review]
@junjihashimoto  thanks for working on this feature! It seems that jit tests failed, could you please fix them?
Also, can you please add `test_dropout_generator` to `test_torch.py` and test that if you pass two instances of generators created with the same seed to `dropout` they return the same tensors? Similar to [test_generator_cpu](https://github.com/pytorch/pytorch/blob/bee97d5be0fc89e415c611054d1f6645a35e5577/test/test_torch.py#L2741-L2770)

**Comment by junjihashimoto** [comment]
Thank you for your comments! I will fix jit error and add the test.

**Comment by junjihashimoto** [comment]
This pr still needs some tweaks to add GeneratorType annotation for jit.

**Pull request closed without merging**
