### PR TITLE
Upgrade CI to ROCm5.6

### PR DESCRIPTION
**Pull request by jithunnair-amd**
... in conjunction with https://github.com/pytorch/pytorch/pull/105516

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @zstreet87

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@huydhn We have test_decomp timing out in https://github.com/pytorch/pytorch/actions/runs/5338693121/jobs/9682282418. The reason is that the `BUILD_ENVIRONMENT` is now `linux-focal-rocm5.5-py3.8`, which doesn't have an entry in https://raw.githubusercontent.com/pytorch/test-infra/generated-stats/stats/test-times.json, thus resorting to default sharding plan:

https://github.com/pytorch/pytorch/actions/runs/5338693121/jobs/9682282418#step:11:1054

and uses a single shard for all tests including test_decomp, which is a VERY LONG running test suite. How do we handle this scenario when we are introducing a new `BUILD_ENVIRONMENT` eg. in case of upgrading CI to new ROCm/CUDA version?

**Comment by malfet** [comment]
@jithunnair-amd default sharding plan should be to split test evenly between shards... You can temporary increase the timeout to make testing finish.

**Comment by jithunnair-amd** [comment]
> @jithunnair-amd default sharding plan should be to split test evenly between shards... If you see otherwise, we need to fix it. You can also temporary increase the timeout to make testing finish.

I think the issue here is that the "default sharding plan" results in 1 shard at the file level eg. `ShardedTest(name='test_decomp', shard=1, num_shards=1, time=None)`, instead of 10 shards like it usually does for ROCm.

How about a temporary change to increase the default file-level sharding to use 4 shards?

**Comment by huydhn** [comment]
> @huydhn We have test_decomp timing out in https://github.com/pytorch/pytorch/actions/runs/5338693121/jobs/9682282418. The reason is that the `BUILD_ENVIRONMENT` is now `linux-focal-rocm5.5-py3.8`, which doesn't have an entry in https://raw.githubusercontent.com/pytorch/test-infra/generated-stats/stats/test-times.json, thus resorting to default sharding plan:
> 
> https://github.com/pytorch/pytorch/actions/runs/5338693121/jobs/9682282418#step:11:1054
> 
> and uses a single shard for all tests including test_decomp, which is a VERY LONG running test suite. How do we handle this scenario when we are introducing a new `BUILD_ENVIRONMENT` eg. in case of upgrading CI to new ROCm/CUDA version?

cc @clee2000

**Comment by huydhn** [comment]
TIL, it turns out that the missing entries can be bootstrapped by copying them directly into the file https://github.com/pytorch/test-infra/commit/7fb2f69574406f5fc374752228d9057f07aa535c.  Thank @clee2000 for the setup.  I'm retrying ROCm jobs now

**Comment by jithunnair-amd** [comment]
@BLOrange-AMD Please take note: PyTorch team is trying to resolve the timeout by seeding the `stats/test-times.json` file: https://github.com/pytorch/test-infra/commit/7fb2f69574406f5fc374752228d9057f07aa535c.

**Comment by jithunnair-amd** [comment]
Compiling the list of UT failures observed in ROCm CI runs for this PR: 

[shard 1](https://github.com/pytorch/pytorch/actions/runs/5527567640/jobs/10083707389):
- test_linalg.py::TestLinalgCUDA::test_svd_cuda_float64 (cc @alugorey)
- test_linalg.py::TestLinalgCUDA::test_svd_cuda_float32 (cc @alugorey)
- test_tensorexpr.py::TestTensorExprFuser::test_unary_ops

[shard 2](https://github.com/pytorch/pytorch/actions/runs/5527567640/jobs/10083707499):
- test_quantization.py::TestQuantizeJit::test_nested

[shard 3](https://github.com/pytorch/pytorch/actions/runs/5527567640/jobs/10083707569):
- test_quantization.py::TestQuantizeJit::test_single_linear
- test_quantization.py::TestQuantizeJit::test_observer_with_ignored_function
- test_quantization.py::TestQuantizeJit::test_conv_transpose
- test_quantization.py::TestQuantizeJit::test_conv

The above should be the complete list of failures since we are running with `CONTINUE_THROUGH_ERROR=True`. All the above tests seem to pass on current CI with ROCm5.4.2, so these all look like regressions on ROCm5.6.

cc @BLOrange-AMD, please let me know if I missed any failures.

**Comment by jithunnair-amd** [comment]
Latest CI runs passed for ROCm:
[Shard1](https://github.com/pytorch/pytorch/actions/runs/5547289134/jobs/10130610098)
[Shard 2](https://github.com/pytorch/pytorch/actions/runs/5547289134/jobs/10130610268)
[Shard 3](https://github.com/pytorch/pytorch/actions/runs/5547289134/jobs/10130610388)

**Comment by jithunnair-amd** [comment]
@malfet @kit1980 Please review and merge.

**Review by malfet — APPROVED** [review]
ROCm builds/tests are passing...

**Pull request closed without merging**
