### PR TITLE
[ROCm] Build Triton in Centos for ROCm

### PR DESCRIPTION
**Pull request by pragupta**
Triton build for centos-based ROCm Dockerfile was missing. This brings centos Dockerfile up-to-date with ubuntu Dockerfile. No CI job covers this change; this change is independently verified by ROCm QA team.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Comment by jeffdaily** [comment]
Lint failure is unrelated to the single file changed by this PR.

**Review by jataylo — APPROVED** [review]
LGTM, the install_triton stage is still functioning as expected after the change.

**Comment by jataylo** [comment]
Hi @malfet @kit1980 could we get some help to merge this, there is no CI job that uses the change but we have verified locally.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
