### PR TITLE
Populate download.pytorch.org IP to container

### PR DESCRIPTION
**Pull request by malfet**
Follow up after https://github.com/pytorch/pytorch/pull/100436 to disable download.pytorch.org access over ipv6 access problems.

Why not copy `/etc/hosts` from host to the container? Because it would break container ip resolution in distributed tests, that relies on `socket.gethostbyname(socket.gethostname())` to work.

### <samp>🤖 Generated by Copilot at 756d0b1</samp>

Propagate `download.pytorch.org` IP address to docker containers in `test-pytorch-binary` action and workflow. This fixes DNS issues when downloading PyTorch binaries inside the containers.

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
Eli's suggestion to mount /etc/hosts as a read-only makes sense

**Comment by huydhn** [comment]
Could you also apply the same fix for Linux binary build and test workflow?  As I can see some recent failures there w.r.t. download.pytorch.org too, for example https://github.com/pytorch/pytorch/actions/runs/4861305449/jobs/8671272133

```
+ pip install /final_pkgs/torch-2.1.0.dev20230502+cu118-cp38-cp38-linux_x86_64.whl --index-url https://download.pytorch.org/whl/nightly/cu118
Looking in indexes: https://download.pytorch.org/whl/nightly/cu118
Processing /final_pkgs/torch-2.1.0.dev20230502+cu118-cp38-cp38-linux_x86_64.whl
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0430ed2220>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/nightly/cu118/filelock/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0430ed2580>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/nightly/cu118/filelock/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0430ed2760>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/nightly/cu118/filelock/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0430ed2910>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/nightly/cu118/filelock/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0430ed2a90>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/nightly/cu118/filelock/
```

**Comment by malfet** [comment]
Ok, mounting `/etc/hosts` break host IP resolution (which is usually done by calling `socket.gethostbyname(socket.gethostname()`:
```shell
$ docker run  --rm 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-py3.8-gcc7:9148fcb287a4285dfaacbfba502b8c249cdb51cd python -c "import socket;print(socket.gethostbyname(socket.gethostname()))"
172.17.0.3
$ docker run -v /etc/hosts:/etc/hosts:ro  --rm 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-py3.8-gcc7:9148fcb287a4285dfaacbfba502b8c249cdb51cd python -c "import socket;print(socket.gethostbyname(socket.gethostname()))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known

```

**Pull request closed without merging**
