### PR TITLE
[1/N] Cleanup header inclusions in torch_cpu by iwyu

### PR DESCRIPTION
**Pull request by cyyever**
Following our previous IWYU work  #100304 on C10, it makes more sense to try IWYU on torch_cpu. This PR does exactly that. Meanwhile, it fixes issue #48684.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel @EikanWang @ezyang

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Any chance we can get this in CI?

**Comment by cyyever** [comment]
> Any chance we can get this in CI?

It is hard because  IWYU rewriting may not handle platform specific #if #else #endif branches properly.

**Comment by ezyang** [comment]
tag me again when you're ready

**Comment by cyyever** [comment]
> tag me again when you're ready

c10::to_string and c10::stoi need to be removed first before it is ready to merge. If you are interest, help review our other PRs.

**Comment by cyyever** [comment]
> tag me again when you're ready

I am ready

**Review by ezyang — APPROVED** [review]

**Comment by atalman** [comment]
This breaks  multiple internal jobs:
```
TensorDumpWriter.h:24:25: error: no member named 'Tensor' in namespace 'caffe2'; did you mean 'at::tensor'?
[CONTEXT] [2023-09-25T10:44:50.927-07:00]       const std::vector<caffe2::Tensor*>& tensors,
[CONTEXT] [2023-09-25T10:44:50.927-07:00]                         ^~~~~~~~~~~~~~
```

**Pull request closed without merging**
