### PR TITLE
[BE]: Try TCH autofixes on torch/

### PR DESCRIPTION
**Pull request by Skylion007**
Tries TCH autofixes and see what breaks

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @LucasLLC

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
sure why not

**Comment by albanD** [comment]
I guess this is part of the work to enable typing in more modules and the testing for this will happen once we can enable typing there?

**Pull request closed without merging**
