### PR TITLE
add BFloat16 support for BatchNorm on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #74410
* #69067

Differential Revision: [D36395422](https://our.internmc.facebook.com/intern/diff/D36395422)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35782876).

**Comment by mingfeima** [comment]
Updates: add test cases for bfloat16 on both mixed_dtype true and false.

todo: use vec_reduce_all fast path when #73953 is settled.

**Comment by mingfeima** [comment]
Update: removed unused variables:
```
// aten/src/ATen/native/cpu/batch_norm_kernel.cpp:732
  using Vec = Vectorized<float>;
```

**Review by frank-wei — APPROVED** [review]
LGTM！

**Comment by frank-wei** [comment]
@frank-wei has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35782876).

**Comment by frank-wei** [comment]
@frank-wei has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35782876).

**Comment by frank-wei** [comment]
@frank-wei has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35782876).

**Comment by frank-wei** [comment]
@frank-wei has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35782876).

**Comment by frank-wei** [comment]
@frank-wei has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36395422).

**Pull request closed without merging**
