### PR TITLE
Fix `torch.lerp` RuntimeError when `weight` is CPU scalar while `input` & `end` are CUDA tensor

### LINKED ISSUE #141811: `torch.lerp()` CUDA does not support scalar CPU weight
### 🐛 Describe the bug

```python
import torch

torch.lerp(torch.randn(10).cuda(), torch.randn(10).cuda(), torch.tensor(0.5)) # this doesn't work
# torch.compile(torch.lerp)(torch.randn(10).cuda(), torch.randn(10).cuda(), torch.tensor(0.5))  # this works
```
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

It was mentioned to me by @janeyx99 that scalar CPU tensor should work with CUDA tensors, since the CPU scalar will be passed as simple `float` to CUDA kernel. Most other ops work as expected e.g.

```python
torch.add(torch.randn(10).cuda(), torch.randn(10).cuda(), alpha=torch.tensor(0.5))
```

So it seems like this is a bug for `torch.lerp`

### Versions

2.6.0.dev20241102+cu124 (1-month old but I believe main branch should have the issue too)

cc @albanD

### PR DESCRIPTION
**Pull request by Kattos**
Fixes #141811

cc @albanD

### CODE REVIEW

**Comment by eqy** [comment]
Please add a test

**Comment by Kattos** [comment]
> Is there a generic way to covert single-value tensors as cpu scalars in gpu kernels? Other operators may have similar bugs.

It looks like that [PowKernel.cu](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cuda/PowKernel.cu) and [CompareKernels.cu](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cuda/CompareKernels.cu) are similar examples, where it's also necessary to determine whether an argument is a cpu scalar. I'm currently looking to see if there is a generic way to do this.

**Comment by cpuhrsch** [comment]
cc @gau-nernst as OP of https://github.com/pytorch/pytorch/issues/141811

**Comment by janeyx99** [comment]
@Kattos lmk when you'd like a review. It looks like you need a rebase for the CI btw

**Comment by Kattos** [comment]
Thank you @janeyx99, this branch has been rebased. Could you please review this PR when it's convenient?

**Review by eqy — APPROVED** [review]

**Comment by Kattos** [comment]
Maybe there exists some CI problems?

**Review by janeyx99 — APPROVED** [review]
LGTM thanks!

**Pull request closed without merging**
