### PR TITLE
Enable ONNX constant folding for opset 11.

### PR DESCRIPTION
**Pull request by spandantiwari**
Currently ONNX constant folding (`do_constant_folding=True` arg in `torch.onnx.export` API) supports only opset 9 and 10 of ONNX. Opset 11 support was recently introduced in the ONNX exporter. For opset 11, it is currently a no-op. This change enables ONNX constant folding for opset 11. Specifically there are three main changes:
1) Turn on constant folding ONNX pass for opset 11.
2) Enable constant folding tests in `test/onnx/test_utility_funs.py` and `test/onnx/test_pytorch_onnx_onnxruntime.py` for opset 11.

### CODE REVIEW

**Review by houseroad — APPROVED** [review]
Looks good, thanks!

**Comment by spandantiwari** [comment]
Thanks @houseroad .

**Comment by houseroad** [comment]
@spandantiwari could you fix the linter: https://github.com/pytorch/pytorch/pull/29011/checks?check_run_id=284168171

**Comment by houseroad** [comment]
And other linters

**Comment by spandantiwari** [comment]
> And other linters

@houseroad - updated based on your feedback. Fixed the C++ linter issues.

**Comment by houseroad** [comment]
rebase again?

**Comment by spandantiwari** [comment]
> rebase again?

I just rebased before submitting. I am not seeing this build failure locally. Will try again.

**Comment by spandantiwari** [comment]
Rebased and started CI again.

**Comment by spandantiwari** [comment]
Thanks @houseroad .

**Pull request closed without merging**
