### PR TITLE
[12/N] Update scatter with CPU/CUDA implementations

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #88330 Allow Process Group to support multiple backends and move PG specfic implementations to backend class
* #87088 Remove ProcessGroupRoundRobin
* #88351 [14/N] Refactor _new_process_group_helper() to remove repeated code
* #86409 [13/N] Update gather with CPU/CUDA implementations
* **#86408 [12/N] Update scatter with CPU/CUDA implementations**

### Changes
- Updates for the scatter collective

### Context
https://github.com/pytorch/pytorch/issues/86225

Differential Revision: [D40181613](https://our.internmc.facebook.com/intern/diff/D40181613)

### CODE REVIEW

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40181613).

**Review by kwen2501 — APPROVED** [review]
LGTM

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40181613).

**Pull request closed without merging**
