### PR TITLE
Adding a step to start docker if it is not running.

### PR DESCRIPTION
**Pull request by mehtanirav**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #73987

### CODE REVIEW

**Comment by mehtanirav** [comment]
Fixes #73859

Adding a step in EC2 linux setup, to start docker if docker is not already running.

**Comment by janeyx99** [comment]
The lint failure is legit as changes to the templates require regeneration.

**Comment by mehtanirav** [comment]
> The lint failure is legit as changes to the templates require regeneration.

**Review by janeyx99 — APPROVED** [review]
LGTM

**Comment by janeyx99** [comment]
@pytorch merge this

**Pull request closed without merging**
