### PR TITLE
Multiple fixes to test_c10d.py.

### PR DESCRIPTION
**Pull request by pritamdamania87**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#25334 Multiple fixes to test_c10d.py.**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D17003555/)

1) There was a bug in https://github.com/pytorch/pytorch/pull/25012, where the
tests which needed to be skipped for return code checking was incorrect.
2) Added proper setup and teardown for the nccl_error tests.
3) Ensure AssertionError is not ignored for tests that skip return code
checking.

Differential Revision: [D17003555](https://our.internmc.facebook.com/intern/diff/D17003555/)

### CODE REVIEW

**Review by pietern — APPROVED** [review]

**Comment by ezyang** [comment]
Broke master?

```
Aug 29 19:10:51 ======================================================================
Aug 29 19:10:51 FAIL: test_allreduce_coalesced_checks (__main__.ProcessGroupGlooTest)
Aug 29 19:10:51 ----------------------------------------------------------------------
Aug 29 19:10:51 Traceback (most recent call last):
Aug 29 19:10:51   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 107, in wrapper
Aug 29 19:10:51     self._join_processes(fn)
Aug 29 19:10:51   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 163, in _join_processes
Aug 29 19:10:51     self._check_return_codes(elapsed_time)
Aug 29 19:10:51   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 187, in _check_return_codes
Aug 29 19:10:51     self.assertEqual(first_process.exitcode, 0)
Aug 29 19:10:51   File "/var/lib/jenkins/workspace/test/common_utils.py", line 705, in assertEqual
Aug 29 19:10:51     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
Aug 29 19:10:51 AssertionError: 10 not less than or equal to 1e-05 : 
```

**Comment by ezyang** [comment]
I think it is only breaking master-only builds. Example https://circleci.com/gh/pytorch/pytorch/2624100?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

Please advise if you would like to revert or debug.

**Comment by pietern** [comment]
The `10` there indicates the `allreduce_coalesced` tests are segfaulting (code 11).

**Comment by pietern** [comment]
These tests were added in #24949.

**Comment by mrshenli** [comment]
@ezyang I am debugging #24949, if cannot figure out why in 1H, let's revert

**Comment by mrshenli** [comment]
@ezyang, see fix in #25419

**Comment by pritamdamania87** [comment]
Looks like this was reverted, I've resubmitted in https://github.com/pytorch/pytorch/pull/25441.

**Pull request closed without merging**
