### PR TITLE
Avoid OOM when running ASAN by splitting nn tests.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
Some more back story is in #5522 but this does not fix it, it just makes the error less likely to occur.

**Review by apaszke — COMMENTED** [review]
I’d rather exclude the nn tests from asan entirely instead of doing this temporary hack. I don’t think it will save you a lot because TestNN is 95% of our tests. Also, it’s likely that someone will add a new test case at the bottom without reading this notice, we’ll forget that we need to update test scripts (it’s an exception), but everything will be looking just fine - no skips, nn tests running.

**Comment by apaszke** [comment]
Unless you know what’s wrong with the tests and are planning to fix it in the coming days

**Comment by ezyang** [comment]
I'd prefer not to skip NN during the ASAN tests, because the bug (segfault for col2im based kernels) that sent me down this road was in our NN code. I did more investigating and there does seem to be a red flag allocation which might offer us an alternative way to solve this problem. See https://github.com/pytorch/pytorch/issues/5522#issuecomment-369961444

**Comment by apaszke** [comment]
Just to be clear, I never wanted to say that we should stop running nn tests in asan forever. They’re great. I just meant that adding this patch could add a false sense that we’re still ok, and we could leave it for a while, but we really shouldn’t.

**Comment by ezyang** [comment]
I plan on investigating the memory problem. So I will merge this to make CI stop failing for people.

**Pull request merged**
