### PR TITLE
Migrate `tan` from TH to ATen (CUDA)

### LINKED ISSUE #24641: Migrate `tan` and `tan_` from the TH to Aten (CUDA)
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

### PR DESCRIPTION
**Pull request by kshitij12345**
Closes #24641

Benchmark with same build settings on same system.
gcc : version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
CUDA : 10.1
GPU : 1050ti

```python
import timeit

for n, t in [(10_000, 20000),
             (100_000, 20000)]:
    for dtype in ('torch.half', 'torch.float', 'torch.double'):
        print(f'torch.tan(a) a.numel() == {n} for {t} times {dtype}')
        print(timeit.timeit(f'torch.tan(a); torch.cuda.synchronize()',
                              setup=f'import torch; a=torch.arange({n}, dtype={dtype}, device="cuda")',
                              number=t))
```

Before:

```
torch.tan(a) a.numel() == 10000 for 20000 times torch.half
0.28325206200003095
torch.tan(a) a.numel() == 10000 for 20000 times torch.float
0.28363607099998944
torch.tan(a) a.numel() == 10000 for 20000 times torch.double
0.43924326799998425
torch.tan(a) a.numel() == 100000 for 20000 times torch.half
0.3754699589999859
torch.tan(a) a.numel() == 100000 for 20000 times torch.float
0.38143782899999223
torch.tan(a) a.numel() == 100000 for 20000 times torch.double
1.7672172019999834
```

After:

```
torch.tan(a) a.numel() == 10000 for 20000 times torch.half
0.28982524599996395
torch.tan(a) a.numel() == 10000 for 20000 times torch.float
0.29121579000002384
torch.tan(a) a.numel() == 10000 for 20000 times torch.double
0.4599610559998837
torch.tan(a) a.numel() == 100000 for 20000 times torch.half
0.3557764019997194
torch.tan(a) a.numel() == 100000 for 20000 times torch.float
0.34793807599999127
torch.tan(a) a.numel() == 100000 for 20000 times torch.double
1.7564662459999454
```

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
Test failure seems to be real for me:

```
Apr 21 21:06:05 ERROR:sccache::server: Compilation failed: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "/var/lib/jenkins/workspace/aten/src/ATen/native/cuda/UnaryGeometricKernels.cu(102): error: identifier \"scalar_t\" is undefined\n\n/var/lib/jenkins/workspace/aten/src/ATen/native/cuda/UnaryGeometricKernels.cu(101): error: identifier \"AT_DISPATCH_FLOATING_AND1\" is undefined\n\n/usr/include/c++/7/type_traits(915): error: class \"std::__is_default_constructible_atom<<error-type>>\" has no member class \"type\"\n          detected during:\n            instantiation of class \"std::__is_default_constructible_safe<_Tp, fa
```

**Review by VitalyFedyunin — CHANGES_REQUESTED** [review]
Fails tests

**Comment by VitalyFedyunin** [comment]
Can you please rebase, there are a lot of conflicts

**Comment by kshitij12345** [comment]
@VitalyFedyunin Sure will do that once #36653 is in as there would probably be conflicts again.

**Review by VitalyFedyunin — APPROVED** [review]

**Pull request closed without merging**
