### PR TITLE
[ROCm] restore autograd tests

### LINKED ISSUE #30845: Many functions fail gradcheck on ROCm
In #30821 I started running a bunch of gradchecks on CUDA. A lot of tests are failing on ROCm due to numerical precision issues. I'm going to blanket turn off all these tests for now, but here's the log with all of the failures: https://gist.github.com/ezyang/bbb8c322912785e92a9c8595620ab9a8

### PR DESCRIPTION
**Pull request by jeffdaily**
Fixes #30845.

### CODE REVIEW

**Comment by jeffdaily** [comment]
2 CI runs passed.  Running again.

**Comment by jeffdaily** [comment]
3 CI runs passed. Running again.

**Comment by jeffdaily** [comment]
Need some help reviewing if these tests are still problems.  I removed the ROCm skip decorator from each, and CI passed 3 consecutive runs.  Do you all recall how flaky these tests were?  I'm trying to understand if they are fixed now, or if I just got lucky in the runs.

@gchanan you had skipped `test_leaky_relu_inplace_with_neg_slope` as part of #35816.  

@ngimel you had skipped `test_cdist` (back on Sep 19 2019) as part of #26254.

@lixinyu you had skipped `test_leaky_relu_inplace_with_neg_slope` as part of #37559.

@mruberry you had skipped `test_sparse_ctor_getter_backward` (back on Sep 16 2019) as part of #26248.

**Comment by mruberry** [comment]
The lint failure is real, so we'll get another signal.

If these test pass the Github CI 4 times in a row then I think we're OK to merge them.

**Comment by jeffdaily** [comment]
@mruberry lint fixed.  4th CI run passed on ROCm.

**Review by mruberry — APPROVED** [review]
Thanks @jeffdaily!

**Pull request closed without merging**
