### PR TITLE
Implement deterministic scan

### LINKED ISSUE #89492: Feature Request: deterministic CUDA cumsum
### 🚀 The feature, motivation and pitch

There is no deterministic implementation for `cumsum_cuda_kernel`. It would be nice to have this!

### Alternatives

_No response_

### Additional context

This can currently still be used by setting the `warn_only` flag to `True`.
Warning:
`cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:82.)`

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @ptrblck @mruberry @kurtamohler @ngimel

### PR DESCRIPTION
**Pull request by ngimel**
Fixes #89492
Uses block-wise cub primitives
On large inputs, this implementation is approximately 25% slower than device cub implementation, so it's turned on only in cases where cub would have been (floating point inputs, cumsum that is effectively 1d)
cc @kurtamohler

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
stampy

**Review by kurtamohler — APPROVED** [review]

**Pull request closed without merging**
