### PR TITLE
add inplace_view tag to resize_as_()

### PR DESCRIPTION
**Pull request by blzheng**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #100786

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]
Is there UT to cover the change?

**Comment by blzheng** [comment]
> Is there UT to cover the change?

Yes. It is covered by https://github.com/pytorch/pytorch/pull/100787/files#diff-0daa64329e2d8648fc119f7809dc810c744508d345ea023116614ccc17e57dbeR1202

**Review by bdhirsh — APPROVED** [review]
looks ok!

**Review by eellison — APPROVED** [review]

**Pull request closed without merging**
