### PR TITLE
Use CUTLASS GEMM for NT bmm

### PR DESCRIPTION
**Pull request by cpuhrsch**
Copy of https://github.com/pytorch/pytorch/pull/85710

### CODE REVIEW

**Comment by hwu36** [comment]
Haicheng from cutlass team.  Help to help.

**Comment by hwu36** [comment]
This is actually not bmm (batch matmul). It is cutlass group gemm, a more general version does not require every batch to have the same problem sizes.

**Review by drisspg — APPROVED** [review]
Do you have benchmark numbers?

**Comment by cpuhrsch** [comment]
@drisspg - Yes, but in context of an immediate follow up that furthers the performance.

**Pull request closed without merging**
