### PR TITLE
add BFloat16 operators on CPU: logaddexp, logaddexp2, remainder

### PR DESCRIPTION
**Pull request by jiayisunx**
Fixes #{issue number}

### CODE REVIEW

**Comment by jiayisunx** [comment]
@mruberry @kshitij12345 , please help to review it, thanks.

**Comment by kshitij12345** [comment]
Hey @jiayisunx,
I will try but I am not sure if I'll be able to review it before next week. Thanks for understanding :)

**Comment by jiayisunx** [comment]
@kshitij12345

**Comment by kshitij12345** [comment]
@jiayisunx sorry couldn't review it last week. Will certainly have a look this coming Monday. Thanks for the ping :)

**Comment by mruberry** [comment]
> @jiayisunx sorry couldn't review it last week. Will certainly have a look this coming Monday. Thanks for the ping :)

ping @kshitij12345 (I'm also going through my reviews!)

**Review by kshitij12345 — APPROVED** [review]
@jiayisunx Overall looks good! Just a few minor nits.

Thank you very much! (and apologies for the delay)

**Comment by jiayisunx** [comment]
@kshitij12345 , have modified according to the comments, thanks!

**Comment by kshitij12345** [comment]
@mruberry Gentle ping :)

**Review by mruberry — APPROVED** [review]
Thanks for the ping, @kshitij12345! And thank you for the PR, @jiayisunx!

**Pull request closed without merging**
