### PR TITLE
add sm80orlater check for bfloat test in test_torchinductor

### PR DESCRIPTION
**Pull request by Fuzzkatt**
small fix to add sm80orlater check for bfloat test in test_torchinductor since bfloat16 is not supported in sm < 80

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by Fuzzkatt** [comment]
Ready for review

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
