### PR TITLE
[Dynamo] Code refactor: moving variables related unit tests to a separate folder

### PR DESCRIPTION
**Pull request by yanboliang**
After this, the only left thing is to further split ```test_misc.py```.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by jansel — COMMENTED** [review]
What is the motivation here?

Having to type an extra `variables/` on every `pytest` command I run sounds annoying.

**Comment by yanboliang** [comment]
Oh, the motivation is planning to split ```test_misc.py``` into multiple files(tests for variables/guards/python_version/etc). Then I found there are too many files in the current folder, and it's a bit hard for developers(especially freshman) to find out where they should add new unit tests. But I don't have strong opinion on this.

**Comment by jansel** [comment]
I support spitting things into smaller files, that sounds great.  Not sure moving most stuff to the `variables` directory makes sense though since most of the tests being moved aren't actually specific to variables.  Maybe there are more topical names we could use, though I'm not sure...

I wonder if we could reduce the amount of tests importing other test files and catching exceptions on import.  That is kind of a mess.  I think a lot of the stuff being cross imported should be moved into a utils module.

**Comment by yanboliang** [comment]
SG, I'll do:
* Removing cross imports in dynamo test files.
* split ```test_misc.py``` into small files.

**Pull request closed without merging**
