### PR TITLE
expand the coverage of conv folding

### PR DESCRIPTION
**Pull request by jiayisunx**
Expand the coverage of conv folding, such as conv->mul->add->bn etc.

### CODE REVIEW

**Review by eellison — APPROVED** [review]
nice!

**Comment by jiayisunx** [comment]
@eellison , I have modified the code to solve the problem of UT failure, could you please review it again?

**Comment by jiayisunx** [comment]
@eellison

**Comment by eellison** [comment]
@jiayisunx do you mind rebasing ? sorry

**Comment by jiayisunx** [comment]
> @jiayisunx do you mind rebasing ? sorry

Done, sorry for late reply.

**Pull request closed without merging**
