### PR TITLE
[dynamo] Error when user nests FX with dynamo

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #87797

Today, this doesn't work and dynamo errors out in a very non-obvious way (see:
https://gist.github.com/suo/dde04830372ab51a4a34ea760f14200a).

Here, we detect the error early and exit with a nicer msg. Also add a
config option to just no-op dynamo (which need to unblock internal
enablement).

cc @jansel @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

### CODE REVIEW

**Review by yf225 — APPROVED** [review]

**Review by soumith — APPROVED** [review]

**Comment by suo** [comment]
@pytorch merge

**Review by jansel — APPROVED** [review]

**Comment by ngimel** [comment]
Per discussion, let's revert this PR because it breaks nvfuser stack. Follow-up is for nvfuser to add a test that would catch these breaking changes, because @skipIfDynamo is a benign skip, and something should be breaking other than that.

**Comment by ezyang** [comment]
My fix doesn't work, we're yanking this.

**Comment by ezyang** [comment]
repro at https://github.com/pytorch/pytorch/pull/88132#issuecomment-1297688065

**Comment by suo** [comment]
The issue was that nvfuser will sometimes use `make_fx` inside the `nvprims_nvfuser` backend (see: `get_isolated_graphmodule`). The nvfuser backend takes care to turn disable proxy tensor modes and detach the arguments, so torchdynamo is running with real tensors.

I fixed the issue by narrowing the check, instead of using `is_fx_tracing()` (which is on even though nvfuser has temporarily disabled proxy tensor mode), just check whether any of the args is an `torch.fx.Proxy` and bail out if so.

**Comment by suo** [comment]
Confirmed that the repro here: https://github.com/pytorch/pytorch/pull/88132#issuecomment-1297688065 passes

**Review by soumith — APPROVED** [review]

**Comment by ezyang** [comment]
I'm not sure I understand the fix explanation. Why is dynamo getting called again inside the backend compiler implementation?

**Comment by suo** [comment]
Here is a representative stack trace: https://gist.github.com/suo/f08680927c6fa4e6811d96c6e368152f

Basically, it goes: dynamo -> AOTAutograd -> nvfuser backend -> calls make_fx to perform decomps -> calls make_fx nested to test whether a function is supported (or something?)

**Comment by ezyang** [comment]
I guess what I don't understand is, at the point we went from user code to dynamo eval frame, dynamo should have been turned off, and stay off for the entirety of the compiler stack. It being on while we are chundering through aot autograd, proxy tensor and the backend compiler seems wrong

**Comment by suo** [comment]
> I guess what I don't understand is, at the point we went from user code to dynamo eval frame, dynamo should have been turned off, and stay off for the entirety of the compiler stack. It being on while we are chundering through aot autograd, proxy tensor and the backend compiler seems wrong

This is weird to me too, but it's def happening. I'll look into why this is going on, but landing now to unblock the internal stuff.

**Pull request closed without merging**
