### PR TITLE
Port torch/csrc/jit/runtime/register_distributed_ops.cpp to new operator registration API

### LINKED ISSUE #37579: Port torch/csrc/jit/runtime/register_distributed_ops.cpp to new operator registration API
This issue is similar to #37348 and #37008, handling the registrations in torch/csrc/jit/runtime/register_distributed_ops.cpp with new API.

cc @suo

### PR DESCRIPTION
**Pull request by RockingJavaBean**
Port register_distributed_ops.cpp with the new registration API introduced in #36258.

resolve #37579

Signed-off-by: Xiong Wei <xiongw.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by RockingJavaBean** [comment]
The CI passed after I upgraded my `Circle CI` account.
This pull request is to handle #37579

**Comment by RockingJavaBean** [comment]
@ezyang @suo @SplitInfinity kindly request for review.

**Review by ezyang — APPROVED** [review]

**Comment by RockingJavaBean** [comment]
@ezyang thanks for reviewing the pull request.

The `Facebook Internal - Build & Tests` failed after running for 4 hours and 40 minutes.
My guess is the commit cf20d936404bc7208bad661bf414296bc07d87bf led to the failure of the Internal CI checks.

I tried to re-trigger the CI checks by manually closing and opening the PR.
The PR added the following two checks and these checks are still pending.
- pr/caffe2-py3.6-devtoolset7-rocmrpm-centos7-test
- pr/py3.6-clang7-rocmdeb-ubuntu16.04

However, Facebook internal CI checks are not being re-triggered.
Please kindly help confirm whether the internal CI checks will run automatically once the pending checks are completed, or additional efforts are required for re-triggering the internal CI checks?

**Comment by ezyang** [comment]
I have to trigger them. But don't worry, they're usually spurious, and I'll let you know if there is a real problem

**Pull request closed without merging**
