### PR TITLE
[DataLoader] Rename transform DataPipe to legacy_transform

### PR DESCRIPTION
**Pull request by VitalyFedyunin**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #60840 [WIP] Example of DataPipes and DataFrames integration
* #60680 [DataLoader] Add notebook with DataPipes API example
* #60679 [DataLoader] Add Example Only `fork` DataPipe
* #60678 [DataLoader] Decorate ZipDataPipe as `zip`
* #60675 [DataLoader] Add simple `groupby` DataPipe
* #60672 [DataLoader] Make `batch` DataPipe sensitive to unbatch_level argument
* #60671 [DataLoader] Make `shuffle`  DataPipe sensitive to unbatch_level argument
* **#60670 [DataLoader] Rename transform DataPipe to legacy_transform**

Differential Revision: [D29461081](https://our.internmc.facebook.com/intern/diff/D29461081)

### CODE REVIEW

**Review by ejguan — APPROVED** [review]
LGTM

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29461081).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29461081).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29461081).

**Pull request closed without merging**
