### PR TITLE
Revert "[jit] Add c++ stacktraces for jit::ErrorReport (#94842)"

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #95886

This reverts commit 70029214f300f611e7dd816b5f64426224f6ab96.

It broke some internal tests.

Differential Revision: [D43735833](https://our.internmc.facebook.com/intern/diff/D43735833)

### CODE REVIEW

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D43735833).

**Review by malfet — APPROVED** [review]

**Comment by davidberard98** [comment]
Going to land it now despite remaining tests, because it broke many internal tests.

As of the time I commented this, the 1 failing check is unrelated: [linux-bionic-py3.8-clang9 / test (dynamo, 2, 2, linux.2xlarge)](https://github.com/pytorch/pytorch/actions/runs/4315664006/jobs/7530778766#logs)
```
2023-03-02T16:36:07.1385370Z ERROR [0.024s]: test_versioned_div_tensor_inplace (jit.test_save_load_for_op_version.TestSaveLoadForOpVersion)
2023-03-02T16:36:07.1385606Z ----------------------------------------------------------------------
2023-03-02T16:36:07.1385685Z Traceback (most recent call last):
2023-03-02T16:36:07.1385875Z   File "/var/lib/jenkins/workspace/test/jit/test_save_load_for_op_version.py", line 112, in test_versioned_div_tensor_inplace
2023-03-02T16:36:07.1385939Z     @given(
2023-03-02T16:36:07.1386195Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/hypothesis/core.py", line 1094, in wrapped_test
2023-03-02T16:36:07.1386285Z     raise the_error_hypothesis_found
2023-03-02T16:36:07.1386474Z   File "/var/lib/jenkins/workspace/test/jit/test_save_load_for_op_version.py", line 152, in test_versioned_div_tensor_inplace
2023-03-02T16:36:07.1386594Z     _helper(current_mobile_module, torch.Tensor.div_)
2023-03-02T16:36:07.1386743Z   File "/var/lib/jenkins/workspace/test/jit/test_save_load_for_op_version.py", line 139, in _helper
2023-03-02T16:36:07.1386818Z     def _helper(m, fn):
2023-03-02T16:36:07.1387075Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 94, in __call__
2023-03-02T16:36:07.1387199Z     return self.dynamo_ctx(self._orig_mod.__call__)(*args, **kwargs)
2023-03-02T16:36:07.1387446Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 235, in _fn
2023-03-02T16:36:07.1387529Z     return fn(*args, **kwargs)
2023-03-02T16:36:07.1387786Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/fx/graph_module.py", line 662, in call_wrapped
2023-03-02T16:36:07.1387895Z     return self._wrapped_call(self, *args, **kwargs)
2023-03-02T16:36:07.1388137Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/fx/graph_module.py", line 279, in __call__
2023-03-02T16:36:07.1388222Z     raise e.with_traceback(None)
2023-03-02T16:36:07.1388426Z RuntimeError: result type Double can't be cast to the desired output type Long
```.

It has 7 failures in other branches and 1 on master.

**Review by qihqi — APPROVED** [review]

**Comment by davidberard98** [comment]
@pytorchbot merge 

(phabricator diff has merged)

**Pull request closed without merging**
