### PR TITLE
Typo fix

### LINKED ISSUE #85074: A tiny typo in the README file
I found a small typo in the README file. The word "of" should be removed from this sentence "You get the best of speed and flexibility for your crazy research." It should be like the following: "You get the best speed and flexibility for your crazy research.". I checked this typo with Grammarly. 

cc @svekars @holly1238

### PR DESCRIPTION
**Pull request by muhaksim**
I removed "of" from this sentence. You get the best of speed and flexibility for your crazy research. You can check it with Grammarly to see that it should be removed.

Fixes #85074

### CODE REVIEW

**Comment by muhaksim** [comment]
@facebook-github-bot, I signed the CLA.

**Review by lezcano — APPROVED** [review]
Thank you!

**Comment by Lezcano** [comment]
cc @ezyang mind approving and merging?

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
I was about to stamp it, but to be frank, I'm not sure it needs any changes. English is not my native, but I guess this phrase is an allusion to "the best of both worlds" idiom.

**Comment by muhaksim** [comment]
I get your point and it is a valid one. Should it be like this: "You get the best of both speed and flexibility for your crazy research", @malfet? This is correct syntactically because I checked it with Grammarly and it conveys the meaning you pointed out.

**Review by svekars — APPROVED** [review]
LGTM

**Comment by malfet** [comment]
> You get the best of both speed and flexibility for your crazy research.

@muhaksim sure, this sounds fine by me, but as I've said before, I'm not a native speaker.
@mruberry what do you think?

**Comment by mruberry** [comment]
I think change is unnecessary and "too small", see https://github.com/pytorch/pytorch/wiki/Developer-FAQ#my-pr-was-rejected-for-being-too-small--what-gives.

**Comment by muhaksim** [comment]
You are right on this one. No problem. I think I can close this pull request as well as the issue. Is that ok, @mruberry?

**Comment by dagitses** [comment]
I agree with malfet and mruberry both. The text is understandable to me as-is.

**Comment by kit1980** [comment]
Closing this as per discussion in the comments.

**Pull request closed without merging**
