### PR TITLE
Pytorchify numpy vendored tests in torch_np/lib/

### PR DESCRIPTION
**Pull request by ev-br**
1. Inherit from TestCase
2. Use pytorch parametrization
3. Use unittest.expectedFailure to mark xfails, also unittest skips

All this to make pytest-less invocation work:

$ python test/torch_np/test_basic.py

cross-ref https://github.com/pytorch/pytorch/pull/109593, https://github.com/pytorch/pytorch/pull/109775

cc @mruberry @rgommers @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by lezcano** [comment]
There's a test that's passing on macos?

**Comment by ev-br** [comment]
> There's a test that's passing on macos?

The test s sensitive to integer overlow (https://github.com/pytorch/pytorch/pull/109718/commits/76badf021a5277a2b23104a14d4e320abb7f04fc#diff-ea0270fd31202668214bf58e09d4293f0eaa4bd87f55663c7a56ed831ca288e0R549) 

We're skipping a few tests for the exact details numpy handles int overflows (and it differs from pytorch), so let's just skip it.

**Comment by ev-br** [comment]
@lezcano : CI is green and tests in torch_np/lib/ are OK under the checker script from https://github.com/pytorch/pytorch/pull/109815

**Pull request closed without merging**
