### PR TITLE
[jit][AD] Don't do dropout if training=True

### PR DESCRIPTION
**Pull request by driazati**
Differential Revision: [D15232342](https://our.internmc.facebook.com/intern/diff/15232342/)

### CODE REVIEW

**Comment by ailzhang** [comment]
What’s the reason for this change? @driazati

Thanks,
Ailing

________________________________

**Comment by driazati** [comment]
It’s to match the behavior of the aten dropout implementation (eval() wasn’t working with this op correctly without it)

**Review by apaszke — CHANGES_REQUESTED** [review]
Backward is incorrect at the moment. We should ensure that `train = False` doesn't save the mask for no reason, because that will be a memory regression.

**Comment by driazati** [comment]
Abandoned for #20760

**Pull request closed without merging**
