### PR TITLE
Delete THCStreamGuard in favor of CUDAGuard, also c10d code cleanup

### PR DESCRIPTION
**Pull request by ezyang**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#12849 Delete THCStreamGuard in favor of CUDAGuard, also c10d code cleanup**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D10457671/)

I got annoyed at waiting for OSS to tell me my c10d builds were busted, so
I also added support for building the test scripts in fbcode and fixed the
warnings this uncovered.

Differential Revision: [D10457671](https://our.internmc.facebook.com/intern/diff/D10457671/)

### CODE REVIEW

**Review by pietern — APPROVED** [review]
@ezyang Does `at::cuda::createCUDAStream` actually create a new stream or pull one from the pool?

cc @mruberry

**Comment by teng-li** [comment]
@ezyang can you also run clang-format -i on all the c10d file touched?

**Comment by teng-li** [comment]
And also, please run make test in c10d build folder

**Comment by ezyang** [comment]
> And also, please run make test in c10d build folder

Why isn't this covered by CI?

**Comment by ezyang** [comment]
@pietern It retrieves streams from the pool

**Comment by ezyang** [comment]
```
[0/1] Running tests...
Test project /home/ezyang/Dev/pytorch-tmp/torch/lib/build/c10d
    Start 1: FileStoreTest
1/5 Test #1: FileStoreTest ....................   Passed    0.06 sec
    Start 2: TCPStoreTest
2/5 Test #2: TCPStoreTest .....................   Passed    0.92 sec
    Start 3: ProcessGroupGlooTest
3/5 Test #3: ProcessGroupGlooTest .............   Passed    3.93 sec
    Start 4: ProcessGroupGlooAsyncTest
4/5 Test #4: ProcessGroupGlooAsyncTest ........   Passed   12.16 sec
    Start 5: ProcessGroupNCCLTest
5/5 Test #5: ProcessGroupNCCLTest .............   Passed   12.99 sec

100% tests passed, 0 tests failed out of 5

Total Test time (real) =  30.07 sec
```

**Pull request closed without merging**
