### PR TITLE
Eliminate the use of CUDA_HOME in setup.py.

### LINKED ISSUE #28365: setup.py: TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Traceback (most recent call last):
  File "setup.py", line 761, in <module>
    extensions, cmdclass, packages, entry_points = configure_extension_build()
  File "setup.py", line 639, in configure_extension_build
    cuda_lib_path = os.path.join(CUDA_HOME, lib_dir)
  File "/home/ezyang/Dev/pytorch-tmp-env/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
````

was just doing a normal build

### PR DESCRIPTION
**Pull request by xuhdev**
Variables read from CMakeCache.txt are more reliable.

Close #28365

### CODE REVIEW

**Review by albanD — CHANGES_REQUESTED** [review]
Could you also update the list of "Environment variables we respect" line 120 of setup.py to reflect this change?

**Comment by xuhdev** [comment]
> Could you also update the list of "Environment variables we respect" line 120 of setup.py to reflect this change?

It's still respected. The current issue is subsequent run after the first run, in which case variables in CMakeCache.txt should has a higher priority.

**Review by albanD — APPROVED** [review]
Ok, makes sense.
How are you testing this?

**Comment by xuhdev** [comment]
I'm waiting for @ezyang to test in his reproducing setup...

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
