### PR TITLE
as_strided: Fix default storage_offset for reference implementation

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89513

This fixes the default storage_offset to take it from the input. This was
previously untested, so I've also added a new OpInfo which includes samples with
non-zero storage_offsets on the input tensor.

### CODE REVIEW

**Comment by ezyang** [comment]
wow that's a lot of xfails lol

**Review by ezyang — APPROVED** [review]

**Review by ngimel — APPROVED** [review]

**Comment by malfet** [comment]
> @pytorchbot merge -f "land bot is not working"

PR has been reopened, so there is no way for me to debug what went wrong :(

**Pull request closed without merging**
