### PR TITLE
Fix issue 38095 TODO in test_multiprocessing.py

### PR DESCRIPTION
**Pull request by kit1980**
Fix TODO related to https://github.com/pytorch/pytorch/issues/38095

### CODE REVIEW

**Review by clee2000 — APPROVED** [review]

**Comment by kit1980** [comment]
> somehow caused test_multiprocessing to timeout 

I suspect what happened is that the types are different and `assertEqualIgnoreType` wants to fail, but instead hangs because of some multiprocessing quirks.

**Pull request closed without merging**
