### PR TITLE
[WIP] Let torch.load load memory-mapped tensors

### PR DESCRIPTION
**Pull request by mikaylagawarecki**
This PR adds an `_mmap` kwarg to `torch.save`, when this option is turned on, instead of using zipfile serialization, the object will be saved as a tarball with the following directory structure (pretty much the same as the current structure save for the fact that we don't use a zipfile). The numbers in the `storage_data/` directory are keys mapping to tensor storages .

```
state_dict.tar
│  data.pkl
│
└─── storage_data
│   │   0
│   │   1
│   │  {...}
```

When such a `.tar` object is `torch.load`ed, in `persistent_load` storages will be constructed using  `torch.UntypedStorage.from_file` which ensures that they are memory mapped.

Simple illustration of the effects of this memory mapped behavior for the following script that saves an 8GB tensor

<details close>
<summary><b>Simple script (click me!) </b></summary>
<br>

```

import torch
from memory_profiler import profile
import time

state_dict_name = "state_dict_mmap.pt"
tensor_size = 1_000_000_000

@profile
def f():
    # should be 1_000_000_000 * 8 bytes = 8 GB
    print("generating weight")
    state_dict = {'weight': torch.randn(tensor_size, dtype=torch.float64)}
    print("generation of weight done")
    saving_start = time.time()
    torch.save(state_dict, state_dict_name, _mmap=True)
    saving_end = time.time()
    print(f"saving done, time={saving_end - saving_start}")
    loading_start = time.time()
    state_dict_loaded = torch.load(state_dict_name, _mmap=True)
    loading_end = time.time()
    print(f"loading done, time={loading_end - loading_start}")
    x = state_dict_loaded['weight']
    y = x[:1000]
    assert torch.equal(state_dict['weight'], x)
    print("loading done")
    
```
</details>

Observe that the line that corresponds to `torch.load` no longer increments memory. However when we access a slice of the tensor `y = x[:10000] * 2` at that point the memory is incremented by the size of the slice.

Before:
Screenshot 2023-05-15 at 5 39 57 PM

`_mmap=True`:
Screenshot 2023-05-15 at 5 40 06 PM

Pending TODOs:

- [ ] Testing
- [ ] Cleanup API, ensure proper error handling
- [ ] Profile loading/saving time of some [tbd] checkpoints that fit on one GPU

Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #101446

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Related: https://github.com/pytorch/pytorch/issues/87033#issuecomment-1279984574

**Comment by vadimkantorov** [comment]
If mmap tensors become a reality, also some sort of fast TarDataset may become nice. Also, this might be nice for avoiding costly deserialization of huge metadata files for datasets (i.e. mmap-loading a tensor from tar might faster than parsing a giant json / creating a ton of python objects)

**Comment by mikaylagawarecki** [comment]
Hey @vadimkantorov, thanks for the detailed thoughts! :) If you are interested, you can check out the conclusion section of [this post](https://dev-discuss.pytorch.org/t/state-of-model-creation-initialization-seralization-in-pytorch-core/1240) for the intended improvements to model loading that we had intended to make!

 Here are some thoughts/questions I have wrt your comment

> So the question is we can have mmap-backed torch.Storage

 We currently have an [`torch.UntypedStorage.from_file() API` ](https://github.com/pytorch/pytorch/blob/main/torch/csrc/StorageMethods.cpp#L378-L416)that is able to load a memory-mapped storage from file. 
 
 For context, our current serialization logic [mostly uses default pickle logic](https://github.com/pytorch/pytorch/blob/main/torch/serialization.py#L715-L719) to serialize the object passed to `torch.save`, with the exception of `Storage` objects for which there is [special handling](https://github.com/pytorch/pytorch/blob/main/torch/serialization.py#L728-L739). This PR tries to use the memory-mapped storage API in `torch.load`. 
 
 I think what we were trying to do here was to make sure that the entire state dict is not loaded into memory by `torch.load` via memory mapped storages so that processing of the state_dict will be more friendly to CPU RAM constraints as mentioned in https://github.com/pytorch/pytorch/issues/64327 which you linked. Is that in line with what you were thinking?

> If mmap tensors become a reality, also some sort of fast TarDataset may become nice. Also, this might be nice for avoiding costly deserialization of huge metadata files for datasets (i.e. mmap-loading a tensor from tar might faster than parsing a giant json / creating a ton of python objects)

This is a good point which seems to relate to dataloader (might be out of scope for this specific `torch.load` and `torch.save` work that we are trying to do right now :) Nevertheless, I am curious what you mean by 

> mmap-loading a tensor from tar might faster than parsing a giant json / creating a ton of python objects

Are you suggesting that we have one file on disk that contains all the binary tensor storages (with some form of metadata recording start/end offsets for each storage) and our mmap function takes these offsets into account? I am also curious whether you have any thoughts on the implications of having to keep this one fd open?

**Comment by vadimkantorov** [comment]
Very faithful description of related problems is your dev-duscuss post :) Thank you! The text below on the contrary is quite unstructured bag of thoughts. Hope it's still helpful!

Regarding dataset/serialization: yeah, if data records can be represented as tensors (as array of structs or a collection of columns). This strategy is probably implemented by HF datasets / tfrecords / hdf5 / apache arrow. Where we can simply mmap a few raw binary storages representing int64 ids, int16 bbox etc. And then if we ensure the reading pattern is consecutive enough, this would allow to skip deserialization of jsons (at least for development time where we can cache the original jsons / original formats). For that it would also be useful to introduce some sort of StringTensor/StringArray to core pytorch: https://gist.github.com/vadimkantorov/86c3a46bf25bed3ad45d043ae86fff57, these are also important for wasteless tensor copies across threads. Maybe a step forward could be introducing some sort of DataFrame directly in PyTorch which can be stored/loaded in mmap-friendly way (both formats make sense: array-of-structs and column-based, and ideally we should have a choice of how they are stored. for the column-based, it might make sense to mmap these regions separately?)

About the mmap solution: I think it's quite practical and solves most of problems implicitly. I discuss below some more explicit ways (which might be applicable for some other data storage formats -e.g. compressed formats where mmap isn't sufficient):

Yeah, I think untyped mmap storage is great! No typo in `I think what we were trying to do here was to make sure that the entire state dict is not loaded into memory by torch.load via memory mapped storages.`? As loading the entire state dict backed with one or more mmap'd storages does not incur load to RAM per se, right? Another point to consider is that we typically want that tensor metadata/shape is still available in state_dict without triggering the data blob load from disk to RAM.

A relevant issue on resetting parameters: https://github.com/pytorch/pytorch/issues/71404

I think @stas00 can chime in with the current state of affairs of crazy hacks HF had to do for workarounds of loading huge models without duplicating CPU ram.

There should also be a way to directly load from disk to GPU ram (especially if the model works on a single GPU) skipping reading all of params to CPU memory at once. This might not be an issue via mmap'd solution, load_state_dirct with reuse_tensors could work if somehow torch.load can support both mmap and map_location = 'cuda'. Maybe also worth some bikeshedding on the naming of reuse_tensors. Making it clear that the tensors are not copied. Maybe `copy=False`? Or `move=True` which would replace tensors in state_dict with None or some stubbed empty tensors (just some ideas).

Being able to save/replace only a portion of state_dict on disk is also useful. Especially if different processes are somehow writing to the same checkpoint file their parameter shards. Can this be achieved with mmap?

Lazy torch.load can also be interesting with a prospect of fusing load with some basic user-provided preprocessing function (like quantization or the other way - decompression), but might require prototypes/design.

Also, some very practical things to improve torch.load might be accepting a lambda to filter in/filter out dict keys. Often, we need to load only the encoder or only some layers from a giant checkpoint file and can save time on loading the tensors we are not interested in.

**Comment by vadimkantorov** [comment]
Another related issue: https://github.com/pytorch/pytorch/issues/48559

There are many ways how this could work, e.g. one way could be to accept an `out=` argument which would contain some preallocated tensors

Or maybe

**Comment by vadimkantorov** [comment]
Also, maybe it's worth to have a more semantic equivalent argument to torch.save, e.g. `format="tar"`. Sometimes people may want to save as tar+binary for some simple interop in other languages. Then it would also be useful to save in tar as the first file some index file which contains all files in tar, along with their offsets and byte counts (and maybe dtype/shapes as well). Then e.g. in Python we can extract this first file, and then directly read the weight tensors in binary format at the specified offsets.

**Comment by vadimkantorov** [comment]
Also, maybe an alternative to rolling a custom tar+binary-based format (especially for the purpose of weights checkpoint storage) could be writing to a subset of HDF5 or parquet file format which do likely handle these paddings / mmap-enabled storage in a more standardized way (and libraries for reading them exist in other frameworks)

(mmap-support for tarfile + is still interesting, but maybe more for simple dataset packing in tars)

**Comment by vadimkantorov** [comment]
About "LazyTensors" with custom loading post processing, one could easier implement loading in 4bit if this exists: https://twitter.com/younesbelkada/status/1661402298252423169

**Comment by vadimkantorov** [comment]
@mikaylagawarecki Also this exists apparently: https://pytorch.org/rl/tensordict/saving.html#saving-memmory-mapped-tensordicts

maybe this should be considered as a basis for a similar functionality in core

**Comment by stas00** [comment]
Could someone add the no-stale tag - I wonder why this was abandoned. If it's intentional, then someone please close it with the reason why it was closed?

stale-bot just buries work, so there are less open Issues/PRs but if they have been unresolved how does that do any good?

**Comment by mikaylagawarecki** [comment]
@stas00 support for the mmap option was actually added in https://github.com/pytorch/pytorch/pull/102549 and is available in PyTorch 2.1, this PR was for experimental purposes before I noticed that our zip file format was actuall mmap-able

**Comment by stas00** [comment]
Thank you for updating this PR, @mikaylagawarecki!

I was concerned you work was killed by stale-bot.

**Pull request closed without merging**
