### PR TITLE
add channels last (2d) support for mkldnn_convolution

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74023
* #70897
* #70665
* #68101
* #58348
* #55864
* __->__ #55584

Differential Revision: [D27941368](https://our.internmc.facebook.com/intern/diff/D27941368)

### CODE REVIEW

**Comment by mingfeima** [comment]
@ezyang could you please tell me how can i reproduce test case failures from `test_xnnpack_integration.py`?

**Comment by ezyang** [comment]
python test/test_xnnpack_integration.py TestXNNPACKOps. test_conv2d

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27941368).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27941368).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27941368).

**Comment by mingfeima** [comment]
TODO:
* add a design doc on how memory format propagates in mkldnn convolution path
* add end2end benchmark data
* fix test case failures

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27941368).

**Comment by mingfeima** [comment]
- [ ] add end2end performance data
- [ ] add doc to demonstrate design principle of mkldnn memory format propagation rules
- [ ] fix test case failures of xnnpack

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27941368).

**Comment by mingfeima** [comment]
- [ ] update with backend_memory_format

**Comment by mingfeima** [comment]
- [ ] update this one with `backend_memory_format` on par with cudnn and miopen.

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27941368).

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Just to be clear, non-mkldnn conv do not support channels last? Can we add PR implementing such support?

**Comment by mingfeima** [comment]
> Just to be clear, non-mkldnn conv do not support channels last? Can we add PR implementing such support?

The whole picture of CPU convolution is like:

#### when `mkldnn` is enabled at build time
```bash
if (use_mkldnn())
    mkldnn_convolution()
else
    if (dilated)
        at::slow_conv_dilated2d()
    else
        at::thnn_conv2d()
```
And when mkldnn is built, `use_mkldnn()` will always return true for dilated conv, #68101 is there for `at::thnn_conv2d()`. So the channels last feature is always supported when mkldnn is built.

#### when `mkldnn` is not built
```bash
 if (dilated)
   at::slow_conv_dilated2d()
 else
   at::thnn_conv2d()
```
Since `at::slow_conv_dilated2d()` did not have channels last support yet, dilated conv will have different behavior when pytorch is built with/without mkldnn at the current moment.

@VitalyFedyunin are you suggesting that we should have CL support when mkldnn is not built? while in that case i will enable CL on `at::slow_conv_dilated2d()`.

**Comment by VitalyFedyunin** [comment]
Ideally, I would love to see CL code for both these branches (as separate PRs).

```python
 if (dilated)
   at::slow_conv_dilated2d()
 else
   at::thnn_conv2d()
```

**Comment by mingfeima** [comment]
> Ideally, I would love to see CL code for both these branches (as separate PRs).
> 
> ```python
>  if (dilated)
>    at::slow_conv_dilated2d()
>  else
>    at::thnn_conv2d()
> ```

#70665 has been added to add channels last support for `at::slow_conv_dilated2d()`.

**Comment by mingfeima** [comment]
The following CI failure is real:

```bash
python test_xnnpack_integration.py TestXNNPACKOps.test_conv2d
```
oneDNN gave wrong result when:
* ISA = avx2 (avx512 result is correct)
* memory format is channels last (channels first is correct)
* groups > 1
* pad_h != pad_w

We will have it fixed in early January.

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27941368).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27941368).

**Comment by mingfeima** [comment]
separate un-related PRs to other stack. now this stack only consists of convolution related changes.

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D27941368).

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
