### PR TITLE
[JIT] run frozen optimizations on methods other than forward

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #69367
* __->__ #68668

This updates run_frozen_optimizations so that it will run on additional methods other than forward

Differential Revision: [D32567857](https://our.internmc.facebook.com/intern/diff/D32567857/)

### CODE REVIEW

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32567857).

**Review by eellison — APPROVED** [review]
Hmm, looks good to me... We should consider looking at the call-graph dependency in freezing/optimize for inference as a follow up

**Review by eellison — COMMENTED** [review]
Hmm, we should also be updating optimize_for_inference to run on the other methods as well. Do you mind bucketing that change here ?

**Comment by eellison** [comment]
And if it's not too much to ask to bucket this change in as well ? https://github.com/pytorch/pytorch/issues/68582 ? maybe as a stack

**Comment by davidberard98** [comment]
@eellison 
* sure, I'll add the optimize_for_inference change as well
* afaik nothing needs to be done in #68582, the check was fixed in #61061

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32567857).

**Pull request closed without merging**
