### PR TITLE
Fix TensorPipe submodule

### PR DESCRIPTION
**Pull request by lw**
Not sure what happened, but possibly I landed a PR on PyTorch which updated the TensorPipe submodule to a commit hash of a *PR* of TensorPipe. Now that the latter PR has been merged though that same commit has a different hash. The commit referenced by PyTorch, therefore, has become orphaned. This is causing some issues.

Hence here I am updating the commit, which however does not change a single line of code.

### CODE REVIEW

**Review by houseroad — APPROVED** [review]
Looks good. Thanks

**Comment by malfet** [comment]
@lw f015d698006c4a11be15b1ebb75b3b9bb317b914 was head of `gh/lw/7/head`, while 42033c5437fc9c181dc9d0a32df600484e2b0685 is hash of the same commit when it got merged to master

**Comment by lw** [comment]
I'm getting very confused, are you saying I messed up this pull request here as well or are you confirming the theory I had on what had happened?

**Comment by malfet** [comment]
@lw, I'm confirming your theory (hash you've committed before this change belonged to PR)

**Pull request closed without merging**
