### PR TITLE
[FSDP] Separate shared code into hooks

### PR DESCRIPTION
**Pull request by rohan-varma**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #75424
* #75422

All load_state_dict implementations call synchronize(), so put this into hook for preparation of doing all FSDP-specific state_dict loading logic in pre/post hooks.

Differential Revision: [D35439351](https://our.internmc.facebook.com/intern/diff/D35439351/)

### CODE REVIEW

**Review by awgu — APPROVED** [review]
Nice refactor!

**Review by zhaojuanmao — APPROVED** [review]
some lint error

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Manually edited `orig` branch to match with internal ordering changes

**Pull request closed without merging**
