### PR TITLE
[aot autograd] fix de-dupping metadata computation bug

### PR DESCRIPTION
**Pull request by bdhirsh**
Fixes https://github.com/pytorch/pytorch/issues/100224

There was a bug in the way that metadata was computed when going from "metadata before-removing-dupes" to "metadata after-removing-dupes". In fact, when I ran the repro with `functorch.config.debug_assert = True`, that immediately signaled to me that the metadata was incorrect.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #100115
* __->__ #100431
* #100430

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Comment by ngimel** [comment]
ooc, why `mul_(.5)` was fine, but `*=` wasn't? Thanks for the fix!

**Review by ngimel — APPROVED** [review]

**Comment by bdhirsh** [comment]
The fact that there were duplicate inputs in the graph was pretty suspicious. It seems like dynamo was doing something strange with the ‘x[x > 0] *= 0.5’ line (that’s maybe not incorrect but just makes the graph more complicated)

**Comment by ezyang** [comment]
Dynamo not handling `*=` correctly smells like Dynamo isn't desugaring op-assignment correctly. That code is worth a closer look.

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
