### PR TITLE
added nbytes and itemsize functions of tensor

### LINKED ISSUE #12728: Add Tensor.nbytes() / `Tensor.itemsize()`
## 🚀 Feature
Add `nbytes` and `itemsize` methods to Tensor. It has the same semantics as https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.nbytes.html and https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.itemsize.html (though, in keeping with PyTorch style, it is a function call, not a property).

## Motivation

The primary motivation is that caffe2::Tensor has these two methods, it's used somewhat frequently in the Caffe2 codebase, and it seems like a generally useful thing to have around.

## Alternatives

* Don't add them, and make users do the computation themselves. This might be a little annoying to do, because if we don't have `itemsize()` the user has to compute it themselves from the dtype.

### PR DESCRIPTION
**Pull request by JohnNesbit**
Fixes #12728 

Adds both of these functions to the tensor class in _tensor.py.

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Should these be properties instead? as in NumPy: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.itemsize.html

**Comment by JohnNesbit** [comment]
There was some debate in the issue thread about that, but the original issue post calls for function calls and not properties, as torch tends to use function calls to retrieve data. If it needs to be a property, however, I can change it.

**Comment by mruberry** [comment]
Hey @JohnNesbit, thanks for this PR! Sorry for not getting back to you earlier but I was on vacation.

Having these as properties, consistent with NumPy, would be great, as @vadimkantorov suggests. In addition to adding the properties this would also need to add tests for the new properties to test_torch.py.

**Comment by JohnNesbit** [comment]
Ok! I will be sure to change these into properties as well as write a test.

**Comment by JohnNesbit** [comment]
It looks like someone has already written a fix to this that works: https://github.com/pytorch/pytorch/pull/29524

**Pull request closed without merging**
