### PR TITLE
[DTensor][XLA] refactor DTensor _xla API

### PR DESCRIPTION
**Pull request by yeounoh**
In response to the change pytorch/xla#5776 and #92909 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @bdhirsh @kiukchung @d4l3k @lucasllc

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]
looks great, thanks for refactoring!

**Review by wanchaol — COMMENTED** [review]
Actually a quick q: do you think we should also move the test_xla_integration.py to torch/xla directly or we still keep it in dtensor?

**Comment by yeounoh** [comment]
> Actually a quick q: do you think we should also move the test_xla_integration.py to torch/xla directly or we still keep it in dtensor?

I think it would be good to have a safeguard here as well, basically testing if we can call the DTensor API with xla backend.

**Comment by yeounoh** [comment]
```
======================================================================
FAIL: test_set (__main__.TestAtenXlaTensor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/xla/test/test_operations.py", line 1007, in test_set
    self.assertEqual(met.counter_value('DestroyXlaTensor'), 6)
  File "/var/lib/jenkins/workspace/xla/test/test_utils.py", line 301, in assertEqual
    super(XlaTestCase, self).assertLessEqual(abs(x - y), prec, message)
AssertionError: 1 not less than or equal to 1e-05 : 

----------------------------------------------------------------------
```
this is a known issue, the test is disabled in the downstream and should be reflected after tonight's pin update.

**Comment by yeounoh** [comment]
```
Error: Cannot find implementation or library stub for module named "torch_xla.distributed.spmd" 
```
have to wait til the next nightly pin update.

**Comment by wanchaol** [comment]
any updates on this @yeounoh?

**Comment by yeounoh** [comment]
> any updates on this @yeounoh?

This slipped out of my hand, let's land this so we can fix & land https://github.com/pytorch/pytorch/pull/121355

**Comment by wanchaol** [comment]
> This slipped out of my hand, let's land this so we can fix & land #121355

Yes let's go for it!

**Pull request closed without merging**
