### PR TITLE
Fix github branch prefix v

### LINKED ISSUE #15519: `torch.hub` cannot download if branch name starts with `v`
GitHub renames archived zip files of branch or tag whose names start with `vX.Y.zip` to `REPONAME-X.Y.zip`. Thus `torch.hub` cannot find the downloaded files.

For example, https://github.com/pytorch/pytorch/archive/v1.0.0.zip is automatically renamed to `pytorch-1.0.0.zip`, not `pytorch-v1.0.0.zip` as `torch.hub` expects.

### PR DESCRIPTION
**Pull request by ailzhang**
Fixes #15519 .

### CODE REVIEW

**Review by soumith — APPROVED** [review]
add a test maybe?

**Comment by ailzhang** [comment]
@soumith  We don't have a release/branch in pytorch/vision with `hub.py` except `master` branch. I tested on my own fork of `vision`, but I think it might be a bad idea to 
- let CI depend on my fork of `vision`
- create a new branch `v0.x.x` in `pytorch/vision` when it's not a release, it might confuses users. :( 
I would prefer to wait until we have next release of `torchvision` and then add a test for it?

**Comment by soumith** [comment]
@ailzhang ok that sounds good

**Comment by ailzhang** [comment]
@soumith  Can we include this in the next minor release? (Couldn't find the right label for it :P

**Pull request closed without merging**
