### PR TITLE
fix random output issue on index_select when src is scalar and index is empty

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96408

Fix https://github.com/pytorch/pytorch/issues/94340

### CODE REVIEW

**Comment by ezyang** [comment]
test?

**Comment by mingfeima** [comment]
> test?

Test case updated, please review! @ezyang

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
