### PR TITLE
shard `win-vs2019-cuda11.3-py3 / test` from 2 shards to 5 shards

### PR DESCRIPTION
**Pull request by clee2000**
Fixes #ISSUE_NUMBER
shard `win-vs2019-cuda11.3-py3 / test` from 2 shards to 5 shards
helps w/ #76838

Notes:
- avg tts for the past week as of May 5 is 4.7 and 4.5 hours for 1st and 2nd shard on master, around 4 hours for all branches (but I don't think the changes from removing distributed tests + moving testing off of pull have come into effect yet)
- high overhead
- hope that tts doesn't explode

Sharding spreadsheet: https://docs.google.com/spreadsheets/d/1BdtVsjRr0Is9LXMNilR02FEdPXNq7zEWl8AmR3ArsLQ/edit#gid=1153012347

### CODE REVIEW

**Review by suo — APPROVED** [review]
accepting, but let's eyeball the shards in CI before merging

**Review by janeyx99 — APPROVED** [review]
lannnnnnnnnd :D

**Comment by janeyx99** [comment]
Though, looking at CI:
image

Looks decently even, but not short enough

**Pull request closed without merging**
