### PR TITLE
Remove input tracker from runtime assertion pass

### PR DESCRIPTION
**Pull request by tugsbayasgalan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #100956
* __->__ #100955

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by ydwu4 — APPROVED** [review]
Looks great!

**Comment by guangy10** [comment]
@tugsbayasgalan Thanks for the fix! Is it imported in fbcode? I'd like to patch it locally for the demo

**Comment by tugsbayasgalan** [comment]
@tugsbayasgalan has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45730312).

**Pull request closed without merging**
