### PR TITLE
Corrected erroneous docstring for MultiLabelSoftMarginLoss

### PR DESCRIPTION
**Pull request by varunagrawal**
Fix for #1320

### CODE REVIEW

**Comment by soumith** [comment]
thanks!

**Comment by fmassa** [comment]
@varunagrawal just a heads-up: the docs were right.
```
1 / (1 + exp(-x)) == exp(x) / (1 + exp(x))
```
(to see that, just multiply the left hand by `exp(x) / exp(x)`)

**Comment by varunagrawal** [comment]
Oh blimey. Missed that somehow.

**Comment by varunagrawal** [comment]
On the plus side, the formula is more in line with what you see in other places. A good thing for folks new to deep learning and pytorch. :)

**Pull request merged**
