### PR TITLE
[functorch] add batch rule for linalg.lu_solve

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #85175

Fixes https://github.com/pytorch/functorch/issues/1022

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
Nice :) I didn't know so many of our operators use this under the hood.

**Comment by zou3519** [comment]
> Nice :) I didn't know so many of our operators use this under the hood.

I don't know the math behind it, but the linalg folks (thanks @Lezcano!) refactored many of the functions to use lu_solve. This also fixed many of the problems we had where the backward pass used to do data-dependent control flow but no longer does

**Comment by Lezcano** [comment]
Happy to know those changes helped :)  We also got a 10x (!!) speed-up on the fwd+bwd `linalg.solve` along the way.

**Pull request closed without merging**
