### PR TITLE
[Bazel] Add CUDA build to CI

### LINKED ISSUE #35316: Bazel Support
## 🚀 Feature
Support a Bazel build of pytorch, equal in capacity to the cmake build

## Motivation

pytorch integration with bazel projects is substantially easier with a bazel ruleset and target surface. Additional uses include from-source build capacity, with unique global configurations like sanitizers.

## Pitch

bazel building and testing with clear instructions for using pytorch as an external repository without patches, direct from release/git commit.

## Alternatives

Using binary-only releases and rules_foreign_cc

## Additional context

This is currently in use at Uber ATG, where a successful build and test of cpu and gpu (nvcc) targets occurs on a daily basis. The changes required for this will be adapted, improved, and released as the starting point. Further work should be detailed in additional tasks.

### PR DESCRIPTION
**Pull request by thuyen**
Fixes #35316
On master, bazel cuda build is disabled due to lack of a proper `cu_library` rule. This PR:
- Add `rules_cuda` to the WORKSPACE and forward `cu_library` to `rules_cuda`. 
- Use a simple local cuda and cudnn repositories (adopted from TRTorch) for cuda 11.3.
- Fix current broken cuda build.
- Enable cuda build in CI, not just for `:torch` target but all the test binaries to catch undefined symbols.

### CODE REVIEW

**Comment by thuyen** [comment]
clang build failures seem unrelated. CI was green on the first commit and the second commit only changes `BUILD.bazel`. 
cc @malfet

**Review by seemethere — COMMENTED** [review]
Overall looks mostly good to me, wanted to ask if we should consider keeping both the original CPU workflow as well as adding a new GPU based workflow for this since I think both would be valid test cases

**Comment by seemethere** [comment]
> clang build failures seem unrelated. CI was green on the first commit and the second commit only changes `BUILD.bazel`. cc @malfet

I re-kicked the jobs so hopefully that should resolve the issues there

**Review by seemethere — APPROVED** [review]

**Review by malfet — CHANGES_REQUESTED** [review]

**Review by vors — APPROVED** [review]
overall lgtm, thank you for this foundational work!

**Review by malfet — APPROVED** [review]

**Review by wayi1 — APPROVED** [review]

**Comment by vors** [comment]
This PR was inactive for 2 weeks, what is blocking it from progressing? We (cruise) would love to see it merged so we can start collaborate on top of it.

**Comment by thuyen** [comment]
@seemethere @malfet Did we see anything blocking this from being merged after the last import? Please let me know.

**Comment by vors** [comment]
Still some conflicts with master
"This branch has conflicts that must be resolved"

**Comment by thuyen** [comment]
I have updated this PR many times. Can someone from pytorch team take a look and merge this?

**Comment by vors** [comment]
@thuyen I pinged @malfet on pytorch slack
image

**Comment by thuyen** [comment]
> @thuyen I pinged @malfet on pytorch slack image

Conflicts are resolved. At the moment we're only BUIDING codes on cpu-only nodes, not running any tests with bazel (still `test_runner_type=LINUX_CPU_TEST_RUNNER`).

**Comment by thuyen** [comment]
@malfet I am updating the PR since https://github.com/pytorch/pytorch/pull/69796 introduces new conflicts.

**Pull request closed without merging**
