### PR TITLE
[WIP] Add batched version of potrf

### PR DESCRIPTION
**Pull request by ethanluoyc**
This PR intends to add batched version of potrf (see #7500). 

On CPU, this is implemented as a for loop which then calls MKL's potrf. On the GPU, MAGMA has 
a batched version of potrf so we use that.

Currently there is still some cleanup to do. I am putting this up here so that nobody else will duplicate the effort.

### CODE REVIEW

**Comment by zou3519** [comment]
@ethanluoyc thanks for the contribution! I can review this after you're done with it; feel free to ping with any questions;

**Comment by ethanluoyc** [comment]
@zou3519 one very general question though.
Ideally, there will be a bunch of batched operators. (batched gesv, cholesky etc). 
How do you suggest we encourage reuse the code for batching when we implement these operators?

**Comment by zou3519** [comment]
I implemented batch gesv a while ago as a part of `torch.gesv`: https://github.com/pytorch/pytorch/pull/6100

For API cleanliness, it would be nice for the batched operations and unbatched operations to be a part of the same function, like `torch.gesv`.

**Comment by vishwakftw** [comment]
What is the status of this PR?

**Comment by t-vi** [comment]
Hi.
I accidentally wrote out a batch potrf without being aware of this PR.
On the up side, I think I have a working batch `potrf` forward based on top of @vishwakftw batched inverse #9949 , and also batched `tril` and `triu` to go with it (which I think you would have hit soonish). I am currently testing the backward (mainly working around no batched `vector->diagonal matrix` function and batchifying ops).

My apologies for not checking before going this far.

**Comment by vishwakftw** [comment]
This can be closed since batched cholesky is merged into master.

**Pull request closed without merging**
