### PR TITLE
[Pytorch][ONNX][C2] Fix erase_number_type pass, negative indices in c2 and some onnx symbolics

### PR DESCRIPTION
**Pull request by wanchaol**
The PR did two things:

1. fix the bug in erase_number_type on node inputs
2. handle negative indices for dim-reduce in caffe2

### CODE REVIEW

**Review by houseroad — COMMENTED** [review]
Can we add some tests to cover this change?

**Comment by wanchaol** [comment]
After some discussion, We decide to fix the expand systematically in tracer and add it correctly in symbolic. So this PR will only include the test for implicit expand (in the onnx peephole pass that we are trying to remove it).

**Comment by wanchaol** [comment]
@houseroad PR is ready, can you take a look?

**Review by houseroad — APPROVED** [review]
checked, I think it's good to go.

**Pull request closed without merging**
