### PR TITLE
[BE] Update numpy version to 2.0.2

### PR DESCRIPTION
**Pull request by malfet**
It's long time to abandon pre-release version

Partially addresses https://github.com/pytorch/pytorch/issues/134868

### CODE REVIEW

**Review by justinchuby — APPROVED** [review]

**Review by clee2000 — APPROVED** [review]

**Review by kit1980 — APPROVED** [review]

**Review by atalman — APPROVED** [review]

**Comment by malfet** [comment]
@atalman by the way, I don't think adding `ciflow/binaries` to this PR has any effect, as change is specific to CI (.ci/pytorch/build.sh should not at all be called during the binary build)

**Review by Skylion007 — APPROVED** [review]

**Comment by ZainRizvi** [comment]
@pytrochbot merge -f

**Pull request closed without merging**
