### PR TITLE
Sort requirements.txt

### PR DESCRIPTION
**Pull request by Raymo111**

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Not sure what's the benefit, especially if we don't lint it to make sure it remains clean?

**Comment by Raymo111** [comment]
> Not sure what's the benefit, especially if we don't lint it to make sure it remains clean?

It's just cleaner IMO, plus even if we don't lint people adding new requirements will see the sorted list and add theirs sorted. Reviewers will catch it too.

I'm not sure if there's a trivial way to lint for it, isort is only for imports not requirements.txt. but I don't see any harm in doing it?

**Review by albanD — APPROVED** [review]
> people adding new requirements will see the sorted list and add theirs sorted.

I would bet that this is not gonna happen haha

But sure we can do this.

**Pull request closed without merging**
