### PR TITLE
[Hotfix] Bring back warnings and -Werror to ATen

### PR DESCRIPTION
**Pull request by goldsborough**
The recent cmake change has:
1. Removed all warnings we had manually enabled for ATen
2. Removed the ability to pass `WERROR=1`  to your local build to enable `-Werror`

This PR undoes these two things. Please merge this ASAP, otherwise code with warnings gets pushed to master and will annoy everyone whose CI subsequently breaks.

@orionr @soumith

### CODE REVIEW

**Review by orionr — APPROVED** [review]
Nice.

**Review by yinghai — COMMENTED** [review]
`pr/pytorch-linux-trusty-py3.6-gcc7.2` failed to build on some tbb code.

**Comment by soumith** [comment]
@goldsborough we might have to switch these options off when building third-party directory.

Exact error:

```
00:20:48 /var/lib/jenkins/workspace/third_party/tbb/src/tbb/concurrent_vector.cpp:341:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
00:20:48          case 0: throw_exception(eid_out_of_range);
00:20:48                  ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
00:20:48 /var/lib/jenkins/workspace/third_party/tbb/src/tbb/concurrent_vector.cpp:342:9: note: here
00:20:48          case 1: throw_exception(eid_segment_range_error);
00:20:48          ^~~~
00:20:48 /var/lib/jenkins/workspace/third_party/tbb/src/tbb/concurrent_vector.cpp:342:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
00:20:48          case 1: throw_exception(eid_segment_range_error);
00:20:48                  ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
00:20:48 /var/lib/jenkins/workspace/third_party/tbb/src/tbb/concurrent_vector.cpp:343:9: note: here
00:20:48          case 2: throw_exception(eid_index_range_error);
00:20:48          ^~~~
00:20:48 At global scope:
00:20:48 cc1plus: error: unrecognized command line option '-Wno-absolute-value' [-Werror]
00:20:48 cc1plus: error: unrecognized command line option '-Wno-unknown-warning-option' [-Werror]
00:20:48 cc1plus: error: unrecognized command line option '-Wno-invalid-partial-specialization' [-Werror]
00:20:48 cc1plus: all warnings being treated as errors
00:20:48 make[2]: *** [caffe2/aten/src/ATen/cpu/tbb/CMakeFiles/tbb_static.dir/__/__/__/__/__/third_party/tbb/src/tbb/concurrent_vector.cpp.o] Error 1
00:20:48 make[1]: *** [caffe2/aten/src/ATen/cpu/tbb/CMakeFiles/tbb_static.dir/all] Error 2
00:20:48 make[1]: *** Waiting for unfinished jobs....
```

**Comment by goldsborough** [comment]
The asan test failure is unrelated to this PR

**Review by zdevito — APPROVED** [review]
(stamping since this was already approved)

**Pull request merged**
