### PR TITLE
Use `cub::FutureValue` to simplify 64bit indexing split of cub scan

### PR DESCRIPTION
**Pull request by zasdfgbnm**
https://github.com/NVIDIA/cub/pull/305 has landed to cub 1.15. This is ready to review and land. This PR contains https://github.com/pytorch/pytorch/pull/66219, please land that PR first before review.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
@ngimel This should be ready.

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Sorry it's conflicting again, can you please rebase and I'll land promptly.

**Comment by zasdfgbnm** [comment]
@ngimel Should be ready

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
A lot of internal errors like
```
          detected during instantiation of "void at::cuda::cub::inclusive_sum_truncating(const input_t *, output_t *, int64_t) [with input_t=int32_t, output_t=int32_t]" 
caffe2/aten/src/ATen/cuda/cub.cu(136): here
caffe2/aten/src/ATen/cuda/cub.cuh(277): error: template parameter "max_cub_size" may not be redeclared in this scope
```

**Comment by zasdfgbnm** [comment]
Sorry, I didn't rebase correctly. Should be working now.

**Pull request closed without merging**
