### PR TITLE
[CI] Use sccache-0.8.2 for CUDA builds

### PR DESCRIPTION
**Pull request by malfet**
Instead of an ancient prebuilt binary

This is a followup from https://github.com/pytorch/pytorch/pull/121323
For some reason, newer `sccache` does not work when `gcc` is invoked with `-E` option, so one have to special-case `-E` case in `/opt/ccache/bin/gcc` wrapper, which had to be special cased to work with  `nvcc` by checking whether `-E` is passed not only as first or second, but as 3rd argument as well(to be followed up by a generic https://github.com/pytorch/pytorch/pull/142813 ), i.e. to generate following wrapper:
```shell
#!/bin/sh

if [ "$1" = "-E" ] || [ "$2" = "-E" ] || [ "$3" = "-E" ]; then
  exec /usr/bin/gcc "$@"
elif [ $(env -u LD_PRELOAD ps -p $PPID -o comm=) != sccache ]; then
  exec sccache /usr/bin/gcc "$@"
else
  exec /usr/bin/gcc "$@"
fi
```

Without it `sccache nvcc hello.cu` failed with no-descriptive  
```
    sccache: error: failed to execute compile
    sccache: caused by: Compiler not supported: ""
```

### CODE REVIEW

**Review by wdvr — APPROVED** [review]

**Comment by ZainRizvi** [comment]
Does this mean that for `ggc -E` commands we do not use sccache at all? What kind of a perf hit are we expecting when building the jobs?

**Comment by wdvr** [comment]
@ZainRizvi yes, but that was already like that, sccache doesn't play nicely with the preprocessor.

**Comment by malfet** [comment]
> @pytorchmergebot revert -c nosignal -m "Some build jobs are timing out, I'm guessing because they aren't using the cache. [GH job link](https://github.com/pytorch/pytorch/actions/runs/12267291369/job/34227116152) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/b94a20641459b295573617b97916a09b284dccfd)"

Those timeouts have resolved itself..

**Pull request closed without merging**
