### PR TITLE
Revert "Revert D32498570: make codegen'd device guards not cuda-specific. Allow them to be used in external codegen"

### PR DESCRIPTION
**Pull request by bdhirsh**
Re-land of https://github.com/pytorch/pytorch/pull/68531

Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #69951
* #69950
* #69949

This reverts commit 0ef523633fddf2d63e97d5028b00af10ff344561.

Differential Revision: [D33113543](https://our.internmc.facebook.com/intern/diff/D33113543)

### CODE REVIEW

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33113543).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33113543).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33113543).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33113543).

**Comment by albanD** [comment]
What's the difference with the original PRs?

**Comment by bdhirsh** [comment]
This PR and the one above it both haven't changed. The bottom PR (#69949) is the one that caused a failure on the first land, so that's the only one that needed changing.

**Review by albanD — APPROVED** [review]
Ok!

**Pull request closed without merging**
