### PR TITLE
[MPS] Allow saved models to be loaded directly to MPS through torch.jit.load

### LINKED ISSUE #88820: RuntimeError: supported devices include CPU, CUDA and HPU, however got MPS when mapping to MPS in `torch.jit.load`
### 🐛 Describe the bug

Mapping a traced model to the Apple Silicon MPS device during loading (`torch.jit.load(..., map_location=torch.device("mps"))`) does not appear to be implemented as of pytorch version `1.14.0.dev20221104`.

```py
File "/opt/homebrew/lib/python3.10/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: supported devices include CPU, CUDA and HPU, however got MPS
```

### Versions

```plaintext
Collecting environment information...
PyTorch version: 1.14.0.dev20221104
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0 (arm64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)] (64-bit runtime)
Python platform: macOS-13.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] condor-pytorch==1.1.0
[pip3] numpy==1.23.2
[pip3] torch==1.14.0.dev20221104
[pip3] torch-lr-finder==0.2.1
[pip3] torchaudio==0.14.0.dev20221104
[pip3] torchmetrics==0.10.0
[pip3] torchvision==0.15.0.dev20221104
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.21.5           py39h42add53_3  
[conda] numpy-base                1.21.5           py39hadd41eb_3  
[conda] numpydoc                  1.2                pyhd3eb1b0_0  
[conda] pytorch                   1.13.0.dev20220826         py3.9_0    pytorch-nightly
[conda] torchaudio                0.13.0.dev20220826        py39_cpu    pytorch-nightly
[conda] torchvision               0.14.0.dev20220826        py39_cpu    pytorch-nightly
```

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

### PR DESCRIPTION
**Pull request by DenisVieriu97**
### <samp>🤖 Generated by Copilot at 94eed69</samp>

This pull request adds support for serializing and deserializing tensors on the `mps` device using JIT. It includes a test case in `test/test_mps.py` and a device handling logic in `torch/csrc/jit/serialization/unpickler.cpp`. 

Fixes https://github.com/pytorch/pytorch/issues/88820, https://github.com/pytorch/pytorch/issues/87504

### CODE REVIEW

**Review by kulinseth — APPROVED** [review]

**Review by malfet — CHANGES_REQUESTED** [review]
Looks good to me, but please add a test.
Something like:
```python
m = torch.nn.Module()
m.x = torch.rand(3, 3, device='mps')
buffer = io.BytesIO()
torch.jit.save(torch.jit.script(m), buffer)
buffer.seek(0)
n = torch.jit.load(buffer)
self.assertEqual(n.x, m.x)
```

**Comment by DenisVieriu97** [comment]
> Looks good to me, but please add a test. Something like:
> 
> ```python
> m = torch.nn.Module()
> m.x = torch.rand(3, 3, device='mps')
> buffer = io.BytesIO()
> torch.jit.save(torch.jit.script(m), buffer)
> buffer.seek(0)
> n = torch.jit.load(buffer)
> self.assertEqual(n.x, m.x)
> ```

Thanks @malfet - I've updated the PR. Could you please take a look?

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Looks good to me.

**Pull request closed without merging**
