### PR TITLE
[ROCm] skip test_fp8_cast_and_t on non-MI300 machines

### PR DESCRIPTION
**Pull request by pragupta**
Fixes #ISSUE_NUMBER

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@malfet Please stamp, this is just to skip a failing unit test for ROCm to get ROCm CI back to green.

**Review by malfet — APPROVED** [review]
LGTM

**Comment by malfet** [comment]
@jithunnair-amd done, but would be nice to mark PR ready for review :)

**Pull request closed without merging**
