### PR TITLE
Move type casting to c10/util/TypeCast.h

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #28428 Simplify copy kernel
* #28427 Make TensorIterator stop promoting types by copying
* **#28426 Move type casting to c10/util/TypeCast.h**

Type casting is used in copy, and will be used also in tensor iterator
in the next stacked diff. I move it to c10 to make it serve as an common
util for different things.

I also add two dynamic casting functions
- fetch_and_cast
- cast_and_store

fetch_and_cast fetch a value with dynamic type specified by a ScalarType
from a void pointer and cast it to a static type.

cast_and_store casts a static typed value into dynamic type specified
by a ScalarType, and store it into a void pointer.

Differential Revision: [D18170996](https://our.internmc.facebook.com/intern/diff/D18170996)

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
@ezyang Sorry I messed up with https://github.com/pytorch/pytorch/pull/28343, so I resubmit it here

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
I'm going to wait on reviews for the next diff in the stack before landing this, if you don't mind

**Comment by zasdfgbnm** [comment]
@ezyang That works for me.

**Comment by zasdfgbnm** [comment]
@ezyang Then tensoriterator PR has been approved, and this could be landed now.

**Pull request closed without merging**
