### PR TITLE
[BE] Add sharding data by default to metrics

### PR DESCRIPTION
**Pull request by ZainRizvi**
Extend metric library to allow setting global metrics on a process level which will always be emitted.

Current use case for them is to include shard information every time a metric is emitted by run_test.py

### <samp>🤖 Generated by Copilot at 0cae92c</samp>

> _`run_test` refactored_
> _Sharding metrics in Rockset_
> _Autumn of testing_

### CODE REVIEW

**Review by clee2000 — APPROVED** [review]
can i also petition to add the job_id in the global metrics? then you could get a lot of information by joining with the workflow_job table, but it would probably need a lot of changes tho

**Comment by ZainRizvi** [comment]
> can i also petition to add the job_id in the global metrics? then you could get a lot of information by joining with the workflow_job table, but it would probably need a lot of changes tho

I do want that, but it seemed surprisingly tricky to figure out which variable is hiding that value.  It's gotta be around here somewhere though, so I do plan to take a closer look at it and add it into a future PR

**Pull request closed without merging**
