### PR TITLE
Make integer parameters and buffers immune to float(), double() and half()

### PR DESCRIPTION
**Pull request by lantiga**
This PR addresses #3810

### CODE REVIEW

**Comment by soumith** [comment]
can you add tests please.

**Comment by lantiga** [comment]
Yep, I'm on it

**Review by apaszke — APPROVED** [review]
It would be nice to be able to retrieve this from the type somehow (e.g. to have sth like NumPy dtype objects), but this probably needs some more discussion. Looks good.

**Comment by soumith** [comment]
thanks a lot Luca!

**Pull request merged**
