### PR TITLE
Prep PR for cutlass 3.5 update

### PR DESCRIPTION
**Pull request by drisspg**
# Summary
These changes are needed for the upgrade to cutlass 3.5
#123458

cc @Skylion007

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by nWEIdia — APPROVED** [review]
The change looks good! 
I verified that this change, coupled with cutlass post 3.5.0 version (3.5.1RC), went past the errors and built successfully.

**Comment by drisspg** [comment]
Hmmm this error doesnt look very good, @nWEIdia

**Comment by nWEIdia** [comment]
@drisspg is it possible to get  the artifact of the build?  I tried gh run download 8744175937 but it only returns a json file. 

```
Uploading to s3 prefix: pytorch/pytorch/8744175937/linux-focal-cuda12.1-py3.10-gcc9-sm86
2024-04-18T21:01:16.4745473Z Starting upload of artifacts.zip
2024-04-18T21:01:21.0882735Z Finished upload of artifacts.zip
2024-04-18T21:01:21.1048690Z ##[group]Run seemethere/upload-artifact-s3@v5
2024-04-18T21:01:21.1049123Z with:
2024-04-18T21:01:21.1049454Z   s3-prefix: pytorch/pytorch/8744175937/1/artifact
```

**Comment by nWEIdia** [comment]
> @drisspg is it possible to get the artifact of the build? I tried gh run download 8744175937 but it only returns a json file.
> 
> ```
> Uploading to s3 prefix: pytorch/pytorch/8744175937/linux-focal-cuda12.1-py3.10-gcc9-sm86
> 2024-04-18T21:01:16.4745473Z Starting upload of artifacts.zip
> 2024-04-18T21:01:21.0882735Z Finished upload of artifacts.zip
> 2024-04-18T21:01:21.1048690Z ##[group]Run seemethere/upload-artifact-s3@v5
> 2024-04-18T21:01:21.1049123Z with:
> 2024-04-18T21:01:21.1049454Z   s3-prefix: pytorch/pytorch/8744175937/1/artifact
> ```

Looks like I can access https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/8744175937/linux-focal-cuda12.1-py3.10-gcc9-sm86/artifacts.zip I will give it a try.

**Comment by nWEIdia** [comment]
The CUDA failure was a OOM around 30 minutes according to the raw log https://github.com/pytorch/pytorch/actions/runs/8744175937/job/23997905500#step:19:1649

```
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I tested this binary on RTX 3090 (24GB) and the test was passing with 100 trials. 

I restarted this test pipeline, it is running for 1.5 hours in comparison.

**Review by malfet — APPROVED** [review]

**Comment by drisspg** [comment]
@nWEIdia  Thank you for taking a look at this! I really appreciate it!

**Pull request closed without merging**
