### PR TITLE
Fix -g not passed to nvcc when DEBUG=1

### PR DESCRIPTION
**Pull request by ssnl**
1. See title. Basically deletes `set(CUDA_PROPAGATE_HOST_FLAGS OFF)`, which is a line from 2 yrs ago. Locally it doesn't break things.

2. Reworked a bit how `CUDA_DEBUG` works, and renamed it to `CUDA_DEVICE_DEBUG` to be clearer. Now it is a cmake flag. `build_torch_libs.sh` fetches its value from env.

3. Disable debug mode when `DEBUG=0`. Same for `REL_WITH_DEB_INFO`.

### CODE REVIEW

**Comment by ezyang** [comment]
```
00:41:55 caffe2/CMakeFiles/caffe2_gpu.dir/build.make:70: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCBlas.cu.o' failed
00:41:55 make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCBlas.cu.o] Error 1
00:41:55 cc1: error: command line option '-fvisibility-inlines-hidden' is valid for C++/ObjC++ but not for C [-Werror]
00:41:55 cc1: error: unrecognized command line option '-Wno-aligned-allocation-unavailable' [-Werror]
00:41:55 cc1: error: unrecognized command line option '-Wno-inconsistent-missing-override' [-Werror]
00:41:55 cc1: error: unrecognized command line option '-Wno-unused-private-field' [-Werror]
00:41:55 cc1: error: unrecognized command line option '-Wno-unknown-warning-option' [-Werror]
00:41:55 cc1: error: unrecognized command line option '-Wno-typedef-redefinition' [-Werror]
00:41:55 cc1: error: unrecognized command line option '-Wno-invalid-partial-specialization' [-Werror]
00:41:55 cc1: all warnings being treated as errors
00:41:55 CMake Error at caffe2_gpu_generated_THCReduceApplyUtils.cu.o.Release.cmake:279 (message):
00:41:55   Error generating file
```

Probably need to avoid passing `-Werror` as part of the propagation.

**Comment by ezyang** [comment]
Ignore the ROCM build failure, it's not your fault.

**Comment by SsnL** [comment]
let's test again to be safe

@pytorchbot retest this please

**Review by ezyang — APPROVED** [review]
But this is adding a nontrivial cmake gadget so flagging @orionr and @pjh5

**Comment by Yangqing** [comment]
Actually, guys, flagging this one... cmake/FindCUDA.cmake and Modules_CUDA_FIx are supposed to be backports of the main cmake repo master, do you know if it possible for us to keep consistency with it? Otherwise, the local change we made in FindCUDA.cmake may be overridden by the backport next time.

**Comment by orionr** [comment]
@SsnL can you put up a pull request against the upstream at https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA.cmake ?

**Comment by SsnL** [comment]
@Yangqing @orionr Sorry about this. I will submit a PR to upstream.

**Comment by SsnL** [comment]
upstream patch submitted at https://gitlab.kitware.com/cmake/cmake/merge_requests/2167

**Pull request merged**
