### PR TITLE
[distributed_test_c10d]: Enable disabled ROCm tests.

### PR DESCRIPTION
**Pull request by jaglinux**
Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>

### CODE REVIEW

**Comment by jaglinux** [comment]
cc: @jeffdaily

**Review by rohan-varma — APPROVED** [review]
Thanks for this! I assume that the CI jobs passing such as `ci/circleci: docker-pytorch-linux-bionic-rocm3.9-py3.6 ` indicates that the tests are running as expected? 

Also, could you fix the lint issue:
 {
    path: 'test/distributed/test_c10d.py',
    start_line: 28,
    end_line: 28,
    start_column: 1,
    end_column: 1,
    annotation_level: 'failure',
    message: "[F401] 'torch.testing._internal.common_distributed.skip_if_rocm_single_process' imported but unused"
  }

Will land after that.

**Comment by jaglinux** [comment]
> Thanks for this! I assume that the CI jobs passing such as `ci/circleci: docker-pytorch-linux-bionic-rocm3.9-py3.6 ` indicates that the tests are running as expected?
> 
> Also, could you fix the lint issue:
> {
> path: 'test/distributed/test_c10d.py',
> start_line: 28,
> end_line: 28,
> start_column: 1,
> end_column: 1,
> annotation_level: 'failure',
> message: "[F401] 'torch.testing._internal.common_distributed.skip_if_rocm_single_process' imported but unused"
> }
> 
> Will land after that.

Thanks for the review comments. 
Yes, it should affect only ROCm tests which is passing.

**Comment by rohan-varma** [comment]
Failure looks unrelated - `RuntimeError: test_tensor_creation_ops failed!`

**Pull request closed without merging**
