### PR TITLE
[dynamo] wrap GraphModule exceptions in dynamo-wrapped tests

### PR DESCRIPTION
**Pull request by williamwen42**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #126341

Better approach to https://github.com/pytorch/pytorch/pull/126197 to catch issues like https://github.com/pytorch/pytorch/issues/125568.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @gujinghui @PenghuiCheng @jianyuh @min-jean-cho @yanbing-j @Guobing-Chen @Xia-Weiwen @snadampal @voznesenskym @penguinwu @EikanWang @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]
Though wondering if our eager backend should be just this.

**Comment by williamwen42** [comment]
We should be allowing certain exceptions through, such as OOM. eager_noexcept should only be used when we're sure that the GraphModule is not expected to error - e.g. most dynamo (-wrapped) unittests.

**Review by jansel — APPROVED** [review]
Seems reasonable, but fix errors before landing

**Comment by anijain2305** [comment]
If graph has mutation, it can lead to wrong results.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
