### PR TITLE
[ROCm] Enable bf16-related tests in test_c10d_nccl.py and test_grad_layout_1devicemodule_1replicaperprocess

### PR DESCRIPTION
**Pull request by hubertlu-tw**
### Description
Enable bf16-related unit tests in test_c10d_nccl.py and test_grad_layout_1devicemodule_1replicaperprocess as follows:

- distributed/test_c10d_nccl test_bf16_compress_wrapper_is_view (main.DistributedDataParallelTest)
- distributed/test_c10d_nccl test_bf16_compress_wrapper_nccl (main.DistributedDataParallelTest)
- distributed/test_c10d_nccl test_grad_layout_1devicemodule_1replicaperprocess (main.DistributedDataParallelTest)

### CODE REVIEW

**Comment by hubertlu-tw** [comment]
cc @jithunnair-amd

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
blegh, can you reopen this PR from a public fork lol

**Comment by hubertlu-tw** [comment]
@ezyang could you please help merge this PR? Thanks.

**Comment by hubertlu-tw** [comment]
@ezyang Could you please help me review this PR? Thanks.

**Comment by ezyang** [comment]
need CLA

**Pull request closed without merging**
