### PR TITLE
Enable closure tests

### PR DESCRIPTION
**Pull request by mlazos**
Follow up to https://github.com/pytorch/pytorch/issues/116494

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
I'm expecting 34 instances to be removed--how come there are only 9?

**Comment by mlazos** [comment]
> I'm expecting 34 instances to be removed--how come there are only 9?

Yeah I'm just trying this out first, I'll update with the rest.

**Comment by mlazos** [comment]
> > I'm expecting 34 instances to be removed--how come there are only 9?
> 
> Yeah I'm just trying this out first, I'll update with the rest.

So looks like I can get forloop goes right direction to pass with a call to torch._dynamo.reset(), but deterministic_state_dict still fails. I attempted to move the closures out of the call to optim and it still failed even after doing that, so I think this is possibly something else in dynamo. I also tried peppering torch._dynamo.disable on various areas and it will wouldn't pass. I think it's safe to say it's not the closure issue.

**Comment by janeyx99** [comment]
Yea, not surprised that there may be other issues. A reasonable next step would be to update this PR such that:
- for every test that now passes, just remove the skip 
- for every test that fails with a new error, keep it skipped but link it to a new issue.

**Pull request closed without merging**
