### PR TITLE
Fix a link in the compiler backend doc

### LINKED ISSUE #125961: Link broken in compiler custom backends docs
### 🐛 Describe the bug

The link [canonical Aten ops](https://pytorch.org/docs/main/ir.html#canonical-aten-ir) in [Custom Backends after AOTAutograd](https://pytorch.org/docs/stable/torch.compiler_custom_backends.html#custom-backends-after-aotautograd) section is not found.

### Versions

stable

cc @svekars @brycebortree @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

### PR DESCRIPTION
**Pull request by spzala**
The core aten is the core subset of aten and seems the corrent link to replace the broken link.

Fixes #125961

### CODE REVIEW

**Comment by spzala** [comment]
cc @malfet - thanks!

**Review by svekars — APPROVED** [review]

**Comment by spzala** [comment]
@svekars thanks for the quick review!! :-)

**Comment by spzala** [comment]
> ## Merge failed
> 
> **Reason**: 1 jobs have failed, first few of them are: [trunk / win-vs2019-cpu-py3 / test (default, 1, 3, windows.4xlarge.nonephemeral)](https://github.com/pytorch/pytorch/actions/runs/9163715193/job/25194243374)
> Details for Dev Infra team
> Raised by [workflow job](https://github.com/pytorch/pytorch/actions/runs/9163886338)

The build error is,`Error: The action 'Test' has timed out after 210 minutes.` on Windows. Rerunning the bot..

**Pull request closed without merging**
