### PR TITLE
[vulkan] Create separate BUCK target for command buffer recording

### PR DESCRIPTION
**Pull request by SS-JIA**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #92994
* #92993
* __->__ #92157

Differential Revision: [D42502843](https://our.internmc.facebook.com/intern/diff/D42502843/)

**NOTE FOR REVIEWERS**: This PR has internal Meta-specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D42502843/)!

### CODE REVIEW

**Review by salilsdesai — APPROVED** [review]
Lgtm

**Comment by malfet** [comment]
@clee2000 I think the check is wrong , see:
```
% git diff origin/gh/SS-JIA/206/base..origin/gh/SS-JIA/206/head|shasum 
99ca94eecdaebadc2e0d3978744b0da1b7eaa54d  -
% git diff origin/gh/SS-JIA/206/orig~1..origin/gh/SS-JIA/206/orig|shasum
99ca94eecdaebadc2e0d3978744b0da1b7eaa54d  -
```

Going to disable it in the mergebot for the time being

**Comment by ezyang** [comment]
Yup, agreed with the verification

**Pull request closed without merging**
