### PR TITLE
Updates NCCL to 2.17.1

### PR DESCRIPTION
**Pull request by syed-ahmed**
Re-open of #97407. NCCL 2.17.1 sometimes fails to send a FIN packet and causes hangs. This PR updates NCCL to 2.17.1 that includes a patch for socket shutdown. NCCL 2.18 will also include this patch.

### CODE REVIEW

**Comment by ptrblck** [comment]
The reported memory leak (https://github.com/pytorch/pytorch/actions/runs/4549833473/jobs/8040348962?pr=97843) in `test_function_returns_input_inner_requires_grad_True_save_for_vjp_save_tensors_output_mark_dirty_True_cuda` seems to be related to https://github.com/pytorch/pytorch/pull/97799.

**Comment by malfet** [comment]
> should it have the 2.0.1 milestone tag to be added to 2.0.1 #97272

Point-releases are for regression/bugfixes only. This PR does not mention anything about fixing a regression.

**Comment by stas00** [comment]
It is a regression fix. The included NCCL version since pt-1.13 hangs with `CUDA_LAUNCH_BLOCKING=1`. It has been fixed in nccl-2.17, which was released a month ago.

Not being able to use `CUDA_LAUNCH_BLOCKING=1` is a huge problem for some pytorch users.

Context:

- https://github.com/NVIDIA/nccl/issues/750
- https://github.com/pytorch/pytorch/pull/97407
- https://pytorch.slack.com/archives/C3PDTEV8E/p1677648772020229

**Comment by ngimel** [comment]
cc @kwen2501, @awgu, distributed team is in charge of nccl updates.

**Review by kwen2501 — APPROVED** [review]

**Comment by syed-ahmed** [comment]
@stas00 I think we should not include this commit in 2.0.1 because there are more changes (improved fault tolerance, socket code refactor etc.) in NCCL 2.17.1 than just the fix for `CUDA_LAUNCH_BLOCKING=1`. Given that it's more than just one change affecting different parts of the execution, I believe it doesn't fit the criteria for this release. I would suggest using the nightlies until the next release.

**Comment by stas00** [comment]
That works, @syed-ahmed - I appreciate you checking in and explaining why it's not safe to push not well tested code in the last moment. 

Thank you for trying to get it into 2.0.1 in the first place.

**Comment by Skylion007** [comment]
NCCL 2.18.1 is released now as well. @kwen2501 @awgu Anything preventing us from updating to that version?

**Comment by awgu** [comment]
@apoorvkh It looks like 2.1 will use NCCL 2.18.5: https://github.com/pytorch/pytorch/tree/release/2.1/third_party/nccl

**Pull request closed without merging**
