### PR TITLE
Use cub 1.15's latest scan-by-key algorithm to replace thrust for Embedding.cu and EmbeddingBag.cu

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
@ngimel This is ready

**Comment by zasdfgbnm** [comment]
ping @ngimel

**Comment by ngimel** [comment]
Ok, I trust it that your internal 11.6 tests are passing?

**Review by ngimel — APPROVED** [review]

**Comment by zasdfgbnm** [comment]
I run tests locally many times, both with CUDA 11.6 and with nightly cub. After merging, our nightly CI will start testing this daily with CUDA 11.6.

**Pull request closed without merging**
