### PR TITLE
[DO NOT MERGE] [CUDA12] Conditionally set device in device guard

### PR DESCRIPTION
**Pull request by Aidyn-A**
CUDA 12 introduces behavioral changes in `cudaSetDevice`. In the old version it would just set the device to be used for kernel launches and memory allocations without creating a CUDA context. Now, in CUDA 12, every time cudaSetDevice is called for the first time it creates a CUDA context. See issue #91122. 
This PR introduces a workaround for cases like:
```python
import torch
x = torch.randn(1, device="cuda:1")
```
in which the primary context would be allocated on devices 0 and 1 because device 0 the default one.
The real danger would have happened in distributed jobs where all ranks set device to 0 in the destructor of CUDA guard creating `nproc_per_node` CUDA contexts.

### CODE REVIEW

**Comment by Aidyn-A** [comment]
cc @ngimel

**Comment by lezcano** [comment]
This is the only PR left to close https://github.com/pytorch/pytorch/issues/91122. PTAL @ngimel

**Comment by Aidyn-A** [comment]
The usage of aten in c10 is not preferred. Would it be make more sense to use CUDA Driver API in c10: #94864

**Comment by jjsjann123** [comment]
looks like c10 bzl rule is still setting `USE_CUDA`, while cmake is not using that any more. Seems like a consistency issue that we should patch and remove?! https://github.com/pytorch/pytorch/blob/master/c10/cuda/build.bzl#L28

cc'ing @vors

**Pull request closed without merging**
