### PR TITLE
Update base docker image tags for ROCm CI

### PR DESCRIPTION
**Pull request by jithunnair-amd**
to make them agnostic of ubuntu version, ROCm version and python minor version.

This should help avoid frequent updates to the docker image tags when upgrading ROCm version in PyTorch CI, which has creation of new ECR tags as a blocking step.

Reference: https://github.com/pytorch/pytorch/pull/88297#issuecomment-1307873280

The BUILD_ENVIRONMENT flag will continue to specify the exact versions for the above, in case it is needed for debug. @malfet @seemethere Hope that's not going away, otherwise we might have a harder time debugging issues where we need to figure out these environment details.

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@kit1980 @malfet Need your help to create ECR tags:
308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-rocm-n-py3
308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-rocm-n-1-py3

**Comment by malfet** [comment]
> pytorch/pytorch-linux-focal-rocm-n-1-py3

Done

**Comment by jithunnair-amd** [comment]
@malfet Thank you! The ROCm docker build jobs succeeded:
image

`docker push 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-rocm-n-1-py3:1645d5fe0ebeec59b92e8b3f9cb9ce73bbd8c9a3`
`docker push 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-rocm-n-py3:1645d5fe0ebeec59b92e8b3f9cb9ce73bbd8c9a3`

This PR is good to merge now.

**Review by malfet — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@malfet Oops, noticed a stupid mistake I made in the PR. Fixing it ....

**Comment by jithunnair-amd** [comment]
Docker builds succeeded again:
ROCm5.2: `308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-rocm-n-1-py3:82d9d2b1e97524ec4988a070c31f4a2655ef32a3`
ROCm5.3: `308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-rocm-n-py3:82d9d2b1e97524ec4988a070c31f4a2655ef32a3`

**Pull request closed without merging**
