### PR TITLE
Adding CUDA version for C2 operators generate proposals and nms

### PR DESCRIPTION
**Pull request by hugovbraun**
Related to issue #13684

### CODE REVIEW

**Comment by hugovbraun** [comment]
I've just rebased on upstream. Please let me know if I can help on the 3 unit tests failing. 
For the windows error, it looks like it's a linking error - Do you have an idea of what could be wrong ? Other windows builds look ok.
For the ROCm errors, it looks like there's something wrong with the ROCm scripts triggered on build (missing file in the rocm directory)

**Comment by ezyang** [comment]
cc @bddppq @petrex @rohithkrn on the ROCm build failures.

**Comment by ezyang** [comment]
Hey @newstzpz what's the status on this diff

**Comment by newstzpz** [comment]
Hi @ezyang, I have landed the diff.

**Pull request closed without merging**
