### PR TITLE
equal_quantized_cpu requires both inputs are quantized tensor

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #95875

**Summary**
Fix the issue https://github.com/pytorch/pytorch/issues/95291, `equal_quantized_cpu` requires both inputs are quantized tensor.

**Test Plan**
```
python -m pytest test_quantization.py -k test_quantized_equal
```

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by leslie-fang-intel** [comment]
@supriyar @vkuzo Please help to take a look.

**Review by vkuzo — APPROVED** [review]
lg, thank you!

**Review by jgong5 — APPROVED** [review]
Add a test case per https://github.com/pytorch/pytorch/issues/95291?

**Comment by leslie-fang-intel** [comment]
> Add a test case per #95291?

Thanks and added.

**Pull request closed without merging**
