### PR TITLE
[ONNX] Guard xfail tests with error messages

### PR DESCRIPTION
**Pull request by titaiwangms**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #117425
* #117218
* #117553
* #116910
* #117500
* #117591
* #116667
* #117409

Previous to this PR, xfail tests didn't provide (1) guarantee of error message/reason (**could be outdated**), and (2) execution of the test (`xfail_if_model_type_is_not_exportedprogram`). Therefore, the tests are less robust with xfail labeled, as we can't be sure if it's still failing with the same reason, and if it's even still failing. This PR fixes the issue with try/except with error message matching to consolidate the xfail truth and reason.

Fixes: #117425

### CODE REVIEW

**Review by thiagocrepaldi — APPROVED** [review]
Thanks

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but it is failing in trunk https://hud.pytorch.org/pytorch/pytorch/commit/1993956da33376f34125306209930ed00c486abd' -c landrace

I suspect that the landrace comes from https://github.com/pytorch/pytorch/pull/117378, but not entirely sure.

**Comment by PaliC** [comment]
reopened temporarily as I need to revert https://github.com/pytorch/pytorch/pull/117425, and this pr is already reverted.

**Comment by titaiwangms** [comment]
@PaliC Really sorry for the trouble!

**Pull request closed without merging**
