### PR TITLE
Let Python build scripts accept both CMAKE_BUILD_TYPE and the oldschool DEBUG and REL_WITH_DEB_INFO variables.

### PR DESCRIPTION
**Pull request by xuhdev**
Currently the build type is decided by the environment variable DEBUG
and REL_WITH_DEB_INFO. This commit also lets CMAKE_BUILD_TYPE be
effective. This makes the interface more consistent with CMake. This
also prepares #22776.

### CODE REVIEW

**Review by ezyang — DISMISSED** [review]

**Comment by ezyang** [comment]
I think the Windows error is real:

```
08:40:21        "C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\build\install.vcxproj" (default target) (1) ->
08:40:21        "C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\build\ALL_BUILD.vcxproj" (default target) (3) ->
08:40:21        "C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\build\caffe2\Dict_test.vcxproj" (default target) (10) ->
08:40:21        "C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\build\caffe2\torch.vcxproj" (default target) (47) ->
08:40:21        (ClCompile target) -> 
08:40:21          cl : Command line error D8016: '/Ox' and '/RTC1' command-line options are incompatible [C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\build\caffe2\torch.vcxproj]
08:40:21 
```

**Comment by xuhdev** [comment]
@ezyang The reason it failed before is that the CI uses an IDE project file (i.e., VStudio) on Windows, which is a multi-configuration native build system. For such a project file, `CMAKE_BUILD_TYPE` set in `CMakeCache.txt` won't be effective, while it is effective for single-configuration native build system such as Makefile. For a multi-configuration native build system, `--config` must be passed to determine which build type to use. Previously, I removed `--config` in the build command, and that's why on Windows things are messed.

Here is a useful explanation for the underlying story: https://stackoverflow.com/a/24470998/1150462

**Comment by xuhdev** [comment]
The latest error doesn't seem related (although I'm not sure why numa test was run on Windows CI)

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
