### PR TITLE
Remove shebang from non-executable files in torch.distributed

### PR DESCRIPTION
**Pull request by pietern**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #27531 Run clang-format for torch/distributed/rpc
* #27530 Rename PythonUDF{Call,Resp}
* #27529 Scope pybind11 functions to torch.distributed.{autograd,rpc}
* #27290 Move RPC API to torch.distributed.rpc
* #27289 Move internal functions to torch.distributed.rpc
* #27288 Move RPC backend registry to torch.distributed.rpc
* #27287 Remove torch.distributed.rpc function
* #27286 Rename variables and add comments
* **#27285 Remove shebang from non-executable files in torch.distributed**
* #27284 Fix pybind11 warnings in python_rpc_handler.cpp

Differential Revision: [D17808207](https://our.internmc.facebook.com/intern/diff/D17808207)

### CODE REVIEW

**Review by xuhdev — COMMENTED** [review]
These shebangs might be used to indicate they must run on Python 3, not Python 2

**Comment by zhaojuanmao** [comment]
right, they are used to indicate codes run on python3 only

**Comment by mrshenli** [comment]
`rpc_test.py` also has this shebang, which is not a runnable either. @pietern 

@xuhdev @zhaojuanmao 

> These shebangs might be used to indicate they must run on Python 3, not Python 2

IIUC, this shebang won't print warning or error messages even if it is executed using PY2. If the shebang is only used for documentation purpose, shall we just use normal comments instead? I checked how jit handled this. Instead of adding a shebang, `jit_test_py3.py` explicitly added that in the name.

**Comment by pietern** [comment]
I agree -- the hash bang is an intent to make a file executable.

@mrshenli Can you stamp this one?

**Review by mrshenli — APPROVED** [review]

**Comment by xuhdev** [comment]
@mrshenli A normal comment is fine. I'm just pointing out that using shebang is one kind of convention. You can also enable lint checks against such style in `.flake8` by removing `EXE001`.

**Pull request closed without merging**
