### PR TITLE
Add more canonical way of adding runtime pass

### PR DESCRIPTION
**Pull request by tugsbayasgalan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #100956
* #100955
* #100955

### CODE REVIEW

**Review by ydwu4 — APPROVED** [review]

**Review by guangy10 — APPROVED** [review]
It looks nicer! Users don't have to create the pass instance and pass it to the transform() explicitly. I noticed that there are other post-export passes to apply. Instead of letting users do the pass in any arbitrary order, e.g. `export(...).transform(pass_1()).transform(pass_2())...`, etc, which may end up with UB if passes have dependencies and need to run one prior to the other. Maybe it's cleaner and less error-prone by exposing post-export passes as additional args to the export API, and pass infra takes care of how to apply these passes correctly. Any thoughts?

**Comment by tugsbayasgalan** [comment]
> It looks nicer! Users don't have to create the pass instance and pass it to the transform() explicitly. I noticed that there are other post-export passes to apply. Instead of letting users do the pass in any arbitrary order, e.g. `export(...).transform(pass_1()).transform(pass_2())...`, etc, which may end up with UB if passes have dependencies and need to run one prior to the other. Maybe it's cleaner and less error-prone by exposing post-export passes as additional args to the export API, and pass infra takes care of how to apply these passes correctly. Any thoughts?

I wonder how adding additional args to the export API will solve the problem of users running the passes in incorrect order. In my opinion, enforcing the ordering for user defined passes will be extremely difficult as we don't know anything about what they might do. But instead, I think it is better if all ExportBase passes individually check for export invariants prior executing the pass and after executing the pass. I think ExportBase today does that by making sure metadata etc is still preserved in the graph module.

**Comment by guangy10** [comment]
@tugsbayasgalan  I guess there will be a separation between user defined passes and compiler defined passes. I agree with you about user defined passes, but I'm referring to the compiler defined passes here. For example, we currently have `ReplaceBrokenOpsWithFunctionalOpsPass`, `ConstPropPass` and `AddRuntimeAssertionsForConstraintsPass`. I don't know when I will need to run the first two passes, and which one should run first, but I know that for export I want the exported graph to be functional w/o broken ops _(also no idea what broken ops mean here)_. So basically, if we completely hide compiler defined passes from users, that's fine; if we allow users to opt-in these passes explicitly, running these passes should end up with a deterministic result consistently, in that case, it will be easier to just ask users whether or not they want to opt-in these compiler passes via some arguments.

**Comment by tugsbayasgalan** [comment]
> @tugsbayasgalan I guess there will be a separation between user defined passes and compiler defined passes. I agree with you about user defined passes, but I'm referring to the compiler defined passes here. For example, we currently have `ReplaceBrokenOpsWithFunctionalOpsPass`, `ConstPropPass` and `AddRuntimeAssertionsForConstraintsPass`. I don't know when I will need to run the first two passes, and which one should run first, but I know that for export I want the exported graph to be functional w/o broken ops _(also no idea what broken ops mean here)_. So basically, if we completely hide compiler defined passes from users, that's fine; if we allow users to opt-in these passes explicitly, running these passes should end up with a deterministic result consistently, in that case, it will be easier to just ask users whether or not they want to opt-in these compiler passes via some arguments.

For `ReplaceBrokenOpsWithFunctionalOpsPass` and `ConstPropPass`, they are kind of like edge specific passes, so in a way they are user defined passes. `ReplaceBrokenOpsWithFunctionalOpsPass` actually means that we are replacing all the view operators with view_copy variants which is necessary for Executorch for memory planning. It originally was used as a way to work around some early functionalization issues and then repurposed to more general view -> view_copy pass. I actually have a diff to make this little more clear. As for the dependency between passes, I think we discussed this in EXIR long time ago but i forgot what the conclusion was. cc : @angelayi  who might remember better. For these two passes tho, the order shouldn't matter.

**Comment by angelayi** [comment]
> As for the dependency between passes, I think we discussed this in EXIR long time ago but i forgot what the conclusion was.

Yeah we have a way to specify dependency of passes ([through this function](https://fburl.com/gh3vem99)) but we haven't run into a specific use case in export which requires it yet so it's not downstreamed to exir.

**Pull request closed without merging**
