### PR TITLE
[MPS] Add support for Mish to MPS backend

### LINKED ISSUE #77764: General MPS op coverage tracking issue
### This issue is to have a centralized place to list and track work on adding support to new ops for the MPS backend.

[**PyTorch MPS Ops Project**](https://github.com/users/kulinseth/projects/1/views/1) : Project to track all the ops for MPS backend. There are a very large number of operators in pytorch and so they are not all yet implemented. We will be prioritizing adding new operators based on user feedback. If possible, please also provide link to the network or use-case where this op is getting used.

As Ops are requested we will add " *To Triage*" pool. If we have 3+ requests for an operation and given its complexity/need the operation will be moved "*To be implemented*" pool. If you want to work on adding support for such op, feel free to comment below to get assigned one. Please avoid pickup up an op that is already being worked on tracked in "*In progress*" pool. 

[Link to the wiki for details](https://github.com/pytorch/pytorch/wiki/MPS-Backend) on how to add these ops and example PRs.

[**MPS operators coverage matrix**](https://qqaatw.github.io/pytorch-mps-ops-coverage/) - The matrix covers most of the supported operators but is not exhaustive. Before you comment below, please take a look at this matrix to make sure the operator you're requesting has not been implemented in nightly.  More details can be found on the [readme](https://github.com/qqaatw/pytorch-mps-ops-coverage).

### PR DESCRIPTION
**Pull request by igm503**
Fixes [#ISSUE_NUMBER](https://github.com/pytorch/pytorch/issues/77764#issuecomment-1712894444)

Adds the mish activation function to the mps backend.

### CODE REVIEW

**Review by kulinseth — APPROVED** [review]
Nice.

**Comment by khari998** [comment]
@igm503  Thank you so much

**Comment by chenhuiapp** [comment]
is aten::mish.out supported on MPS now?

**Comment by igm503** [comment]
@chenhuiapp I believe it's currently only available in the nightlies. It should be available in the normal distribution the next time there's an update.

**Comment by chenhuiapp** [comment]
@igm503 thank you! I will try nightly.

**Comment by aleksandrsuslov** [comment]
Any updates? Is mish supported now in pytorch 2.3?

**Comment by khari998** [comment]
> Any updates? Is mish supported now in pytorch 2.3?

It is for me. Have you tried it?

**Pull request closed without merging**
