### PR TITLE
[aoti][reland] clear precomputed symbol replacements before cpp wrapper compilation

### PR DESCRIPTION
**Pull request by chenyang78**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #123136

After we codegen a triton kernel in the triton codegen backend,
we cache the generated triton source code in the wrapper to avoid
producing multiple triton kernels with the same content.

In AOTI compilation flow, this caching mechanism imposes a strong requirement
on the codegen that we must generate the same triton source code
for the same schedule node in both python and cpp codegen phases.
Otherwise, we would end up with a mismatch between the kernel name
formed in the cpp codegen and the cuda kernel key produced from
the python codegen. Consequently, we would hit an missing-cuda-kernel
error.

The precomputed symbol replacements saved in V.graph.sizevars
can cause such source-code inconsistency related to the code for indexing
tensors. For example, let's say in the python codegen phase,
we produce "ks2\*48" as part of indexing an input for schedule
node A while yielding a replacement pair "ks0 -> ks2\*48" in
the precomputed replacements. In the second cpp codegen phase,
we would produce "ks0" for the same indexing code of schedule
node A due to the "ks0 -> ks2*48" replacement pair.

This PR fixed the issue by clearing precomputed_replacements
and inv_precomputed_replacements before cpp wrapper codegen.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by desertfire — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@chenyang78 I'm not sure why this PR was filed; the original PR was reopened and I commented on it suggesting how to avoid the ROCm CI breakages: https://github.com/pytorch/pytorch/pull/122882#discussion_r1546575595. Please update the original PR and reland it.

**Comment by chenyang78** [comment]
> @chenyang78 I'm not sure why this PR was filed; the original PR was reopened and I commented on it suggesting how to avoid the ROCm CI breakages: [#122882 (comment)](https://github.com/pytorch/pytorch/pull/122882#discussion_r1546575595). Please update the original PR and reland it.

@jithunnair-amd I am really sorry that I missed your comment! I made the suggested changes in this PR and will close the original one. BTW, the original PR was reverted because it caused some internal issue.

**Comment by chenyang78** [comment]
@jithunnair-amd Hmm, seems the ROCM CI is currently broken. Just want to check if you are aware of this. I see the following failure, (which is unlikely related to my changes in the PR)

```
024-04-04T20:54:07.8252520Z FAILED: caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/sparse/hip/torch_hip_generated_SparseSemiStructuredTile.hip.o /var/lib/jenkins/workspace/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/sparse/hip/torch_hip_generated_SparseSemiStructuredTile.hip.o 
2024-04-04T20:54:07.8259039Z cd /var/lib/jenkins/workspace/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/sparse/hip && /opt/conda/envs/py_3.8/bin/cmake -E make_directory /var/lib/jenkins/workspace/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/sparse/hip/. && /opt/conda/envs/py_3.8/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=/var/lib/jenkins/workspace/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/sparse/hip/./torch_hip_generated_SparseSemiStructuredTile.hip.o -P /var/lib/jenkins/workspace/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/sparse/hip/torch_hip_generated_SparseSemiStructuredTile.hip.o.cmake
2024-04-04T20:54:07.8264043Z In file included from /var/lib/jenkins/workspace/aten/src/ATen/native/sparse/hip/SparseSemiStructuredTile.hip:6:
2024-04-04T20:54:07.8265380Z In file included from /var/lib/jenkins/workspace/aten/src/ATen/native/sparse/hip/ComputeSparseTile.h:4:
2024-04-04T20:54:07.8266695Z In file included from /var/lib/jenkins/workspace/aten/src/ATen/native/sparse/hip/SparseSemiStructuredPack.h:4:
2024-04-04T20:54:07.8268355Z /var/lib/jenkins/workspace/aten/src/ATen/native/sparse/hip/StaticSort.h:3:10: fatal error: 'cutlass/cutlass.h' file not found
2024-04-04T20:54:07.8269378Z #include <cutlass/cutlass.h>
2024-04-04T20:54:07.8269722Z          ^~~~~~~~~~~~~~~~~~~
2024-04-04T20:54:07.8270145Z 1 error generated when compiling for host.
2024-04-04T20:54:07.8270845Z CMake Error at torch_hip_generated_SparseSemiStructuredTile.hip.o.cmake:146 (message):
2024-04-04T20:54:07.8271521Z   Error generating
2024-04-04T20:54:07.8272598Z   /var/lib/jenkins/workspace/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/sparse/hip/./torch_hip_generated_SparseSemiStructuredTile.hip.o
```

**Pull request closed without merging**
