### PR TITLE
Nvfuser code bump 030122

### PR DESCRIPTION
**Pull request by jjsjann123**
Things changed in this PR that requires review:

test/forward_backward_compatibility/check_forward_backward_compatibility.py

Our previous function overload extension names were wrong and has been updated in this PR, hence the compatibility list updated.

nvfuser code updates with bug fixes towards failures we encountered in OpInfoTests as well as failures reported by AOTAutograd team.

### CODE REVIEW

**Comment by Krovatkin** [comment]
@jjsjann123 to double check `prim::infer_squeeze_size` and `prim::infer_squeeze_size.dim` are internal, non-serializable ops that are never exposed to a user?

**Comment by jjsjann123** [comment]
> @jjsjann123 to double check `prim::infer_squeeze_size` and `prim::infer_squeeze_size.dim` are internal, non-serializable ops that are never exposed to a user?

That's the intention at least.
We have a few defined here: https://github.com/jjsjann123/pytorch/blob/nvfuser_code_bump_030122/torch/csrc/jit/codegen/cuda/interface.cpp#L666-L725
I'm pretty surprised updating those also requires updating compatibility list. Did I do something wrong there or is there a better way to define an internal op?

**Review by csarofeen — APPROVED** [review]
LGTM

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Comment by csarofeen** [comment]
@malfet is there a way to look at the merge rules, there was one file I thought would trigger it but I wanted to make sure there wasn't another reason it failed to go through.

**Comment by malfet** [comment]
@csarofeen rules are specified in https://github.com/pytorch/pytorch/blob/39470387cf17896cf38f3e04b5b81d4647734275/.github/merge_rules.json#L20-L25

and it looks like they could be extended to include `torch/csrc/jit/cuda`, but I need a confirmation from somebody from the JIT team that it is the case. But this one modifies top level CMakeLists.txt, which is not something that can go without validating against internal builds system yet (also, it's quite surprising that those kinds of changes are needed for nvfuser only PR)

**Comment by jjsjann123** [comment]
@malfet Updated the build to move these cmake bits & cpp tests into nvfuser folder.
remaining questions regarding the rule here https://github.com/pytorch/pytorch/blob/39470387cf17896cf38f3e04b5b81d4647734275/.github/merge_rules.json#L22:

1. We'll need to add our python tests in the list as well `test/test_jit_cuda_fuser.py`
2. There are bits in the bazel file `tools/build_variables.bzl`. Not sure how that could be moved into our fuser..... Any guidance there?

**Comment by jjsjann123** [comment]
Wondering if there's any update~

**Comment by eellison** [comment]
@jjsjann123 looks like merge conflict :/

**Comment by eellison** [comment]
Maybe https://github.com/pytorch/pytorch/blob/2d110d514f9611dd00bf63ae5ef7d5ce017c900f/test/cpp/jit/test_gpu_shift.cpp#L31 should use full include path ?

**Comment by jjsjann123** [comment]
> Maybe
> 
> https://github.com/pytorch/pytorch/blob/2d110d514f9611dd00bf63ae5ef7d5ce017c900f/test/cpp/jit/test_gpu_shift.cpp#L31
> 
> should use full include path ?

Thought I have fixed that already.. Let me take another pass.

**Comment by jjsjann123** [comment]
Per the readme file here https://github.com/pytorch/pytorch/blob/4537f6c9eba4d016f31f352f97056a7594d83142/test/cpp/jit/README.md, cpp jit tests should be placed under that given folder, is that a hard requirement? I don't see anything requires that in the `CMakeLists.txt`

I'm trying to move our specific test files to a different folder, which works for me locally (relevant changes are here):
https://github.com/pytorch/pytorch/pull/73627/commits/29693a6ff1aef3abaa553d4beee53e2850728f84
I've also changed include header test_gpu_validator.h to use the full path
`#include <torch/csrc/jit/codegen/cuda/test/test_gpu_validator.h>`.

But somehow this still fails on internal build with
> the error is references non-existing file or directory 'caffe2/test/cpp/jit/test_gpu_validator.h'

Wondering if there's some internal build file that should be udpated? cc'ing @malfet @eellison

**Pull request closed without merging**
