### PR TITLE
[Quant][devs] Changed empty_quantized call for quantized tensor to resize_output

### PR DESCRIPTION
**Pull request by dzdang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #71899

Summary: This PR is part of a series of PRs addressing https://github.com/pytorch/pytorch/issues/54150,
related to using dispatcher for calls to quantized backends as opposed to if/else conditionals.
This particular PR removes the call to empty_quantized for quantized tensors and substitutes
it for resize_output, which works for quantized tensors, based on current understanding.
Using the dispatcher for this function was determined to be not practical as it would entail
a significant amoutn of duplicate code

Differential Revision: [D33809138](https://our.internmc.facebook.com/intern/diff/D33809138)

### CODE REVIEW

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33809138).

**Review by jerryzh168 — APPROVED** [review]

**Comment by jerryzh168** [comment]
please make sure lint check succeeds before landing

**Comment by dzdang** [comment]
> please make sure lint check succeeds before landing

i've seen this linting issue in several of my PRs and it appears to have been introduced by someone else as it's an issue attributed to a python file I haven't touched. can I ignore this?

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33809138).

**Pull request closed without merging**
