### PR TITLE
switching NNC as default for TorchScript support

### PR DESCRIPTION
**Pull request by jjsjann123**
Disable nvfuser by default in TorchScript
Add deprecation warning for nvfuser usage via TorchScript and PrimTorch

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM (though not sure if NNC would be default in this case)

**Review by davidberard98 — APPROVED** [review]
I think this looks like the right way to make NNC the default

**Comment by davidberard98** [comment]
although the failing test looks legitimate, may need to skip it?

**Comment by jjsjann123** [comment]
I'll try to take a look at the failing tests, but I also noticed some message from bot on that test: https://github.com/pytorch/pytorch/issues/103440

**Comment by jjsjann123** [comment]
Looks like the error is just coming from warning message I added :laughing: skipped that part.

**Comment by jjsjann123** [comment]
failure coming from inductor and ROCM I'm not sure if they are relevant or not.:
```
2023-07-17T19:13:40.5706312Z Running inductor/test_cuda_repro 1/1 ... [2023-07-17 19:13:39.883309]
2023-07-17T19:13:40.5706447Z test_unary_ufuncs 1/1 failed! Received signal: SIGSEGV
2023-07-17T19:13:40.5707152Z Executing ['/opt/conda/envs/py_3.8/bin/python', '-bb', 'inductor/test_cuda_repro.py', '--shard-id=0', '--num-shards=1', '-v', '-vv', '-rfEX', '-p', 'no:xdist', '--use-pytest', '--sc=inductor/test_cuda_repro_0', '-x', '--reruns=2', '--import-slow-tests', '--import-disabled-tests'] ... [2023-07-17 19:13:39.883653]
2023-07-17T19:13:40.5707267Z Traceback (most recent call last):
2023-07-17T19:13:40.5707447Z   File "test/run_test.py", line 1683, in <module>
2023-07-17T19:13:40.5707565Z     main()
2023-07-17T19:13:40.5707692Z   File "test/run_test.py", line 1656, in main
2023-07-17T19:13:40.5707799Z     failure_messages += run_tests(
2023-07-17T19:13:40.5707927Z   File "test/run_test.py", line 1561, in run_tests
2023-07-17T19:13:40.5708017Z     raise RuntimeError(
2023-07-17T19:13:40.5708184Z RuntimeError: test_unary_ufuncs 1/1 failed! Received signal: SIGSEGV
```

**Comment by jjsjann123** [comment]
Looks like CI is clean now.

But there's an EasyCLA that I need to sign? is this something new or should I have pushed the branch to pytorch/pytorch and start the PR directly there?

cc'ing @davidberard98

**Comment by davidberard98** [comment]
looks like that might have fixed it

**Comment by jjsjann123** [comment]
> looks like that might have fixed it

Awesome~~ I guess this PR is good to go then.

**Pull request closed without merging**
