### PR TITLE
WIP:: Cuda strided complex binary unary ops

### PR DESCRIPTION
**Pull request by dylanbespalko**

### CODE REVIEW

**Comment by dylanbespalko** [comment]
@zasdfgbnm, @iotamudelta, @ezyang,

Hello, I could use a little help. I am having a problem with the code in `TypeCast.h` since #29612 
```C++
// Fetch a value with dynamic type src_type from ptr, and cast it to static type dest_t.
#define FETCH_AND_CAST_CASE(type, scalartype) case ScalarType::scalartype: return static_cast_with_inter_type<dest_t>(*(const type *)ptr);
template<typename dest_t>
C10_HOST_DEVICE inline dest_t fetch_and_cast(const ScalarType src_type, const void *ptr) {
  switch (src_type) {
    AT_FORALL_SCALAR_TYPES_WITH_COMPLEX_EXCEPT_COMPLEX_HALF(FETCH_AND_CAST_CASE)
    default:
      ERROR_UNSUPPORTED_CAST
  }
  return dest_t(0); // just to avoid compiler warning
}

// Cast a value with static type src_t into dynamic dest_type, and store it to ptr.
#define CAST_AND_STORE_CASE(type, scalartype) case ScalarType::scalartype: *(type *)ptr = static_cast_with_inter_type<type>(value); return;
template<typename src_t>
C10_HOST_DEVICE inline void cast_and_store(const ScalarType dest_type, void *ptr, src_t value) {
  switch (dest_type) {
    AT_FORALL_SCALAR_TYPES_WITH_COMPLEX_EXCEPT_COMPLEX_HALF(CAST_AND_STORE_CASE)
    default:;
  }
  ERROR_UNSUPPORTED_CAST
}
```

My Goal is to:
Replace `std::complex<T>` with `thrust::complex<T>` to call the `thrust::complex` [API](https://thrust.github.io/doc/group__complex__numbers.html).

This appears to be supported by [CUDA](https://thrust.github.io/doc/group__complex__numbers.html) and [ROCm](https://github.com/ROCmSoftwarePlatform/Thrust/blob/master/thrust/complex.h).

A sample implementation is: 

```C++
// We manually overload log because std::log does not work with thrust types.
template<typename scalar_t>
__host__ __device__ static inline scalar_t log_wrapper(scalar_t v) {
  return ::log(v);
}

template<typename T>
__host__ __device__ static inline thrust::complex<T> log_wrapper(thrust::complex<T> v) {
  return thrust::log(v);
}

void log_kernel_cuda(TensorIterator& iter) {
  AT_DISPATCH_FLOATING_AND_COMPLEX_TYPES_AND1(ScalarType::Half, iter.dtype(), "log_cuda", [&]() {
    using thrust_t = typename ztype_cuda<scalar_t>::thrust_t;
    gpu_kernel(iter, []GPU_LAMBDA(thrust_t a) -> thrust_t {
      return log_wrapper(a);
    });
  });
}
```

Where `ztype_cuda<scalar_t>::thrust_t` returns thrust::complex<T> for complex types and is a no-op for other types. Unfortunately since #29612, I get a lot of warnings about static casting `std::complex` to `thrust::complex` not supporting ` __host__ __device__` because it is only defined on the `__host__` device (see `__host__  thrust::complex< T >::complex (const std::complex< T > &z)` in  [API](https://thrust.github.io/doc/group__complex__numbers.html)).

**It looks like to avoid host only complex numbers I would have to replace `std::complex<T>` with `thrust::complex<T>` in the ScalarType enumeration. Is there anyway to modify `ScalarType::ComplexFloat/ScalarType::ComplexDouble` (defined in `c10/core/ScalarType.h`) for CUDA/ROCm?**

I have attached a sample of the warnings that I get.

[thrust_warnings.txt](https://github.com/pytorch/pytorch/files/3858425/thrust_warnings.txt)

**Comment by ezyang** [comment]
@dylanbespalko I didn't follow the problem exactly, but if I understand correctly, `thrust::complex` and `std::complex` have exactly the same bit representation, is that right? In that case, to me it feels like it should be possible to directly reinterpret cast the bits between the two, rather than going through the normal cast that goes through the host-only function that is giving you trouble. Am I misunderstanding something?

**Comment by zasdfgbnm** [comment]
From C++ reference, I see that `std::complex` provide Array-oriented access behavior:

> For any object `z` of type `complex<T>`, `reinterpret_cast<T(&)[2]>(z)[0]` is the real part of `z` and `reinterpret_cast<T(&)[2]>(z)[1]` is the imaginary part of `z`. For any pointer to an element of an array of `complex<T>` named `p` and any valid array index `i`, `reinterpret_cast<T*>(p)[2*i]` is the real part of the complex number `p[i]`, and `reinterpret_cast<T*>(p)[2*i + 1]` is the imaginary part of the complex number `p[i]`. The intent of this requirement is to preserve binary compatibility between the C++ library complex number types and the C language complex number types (and arrays thereof), which have an identical object representation requirement.

See: https://en.cppreference.com/w/cpp/numeric/complex
But I didn't see any guarantee of this on thrust document. I guess this is a UB, but let me ask.

If it is guaranteed, then we might just need to specialize `c10::static_cast_with_inter_type` for these two dtypes.

**Comment by dylanbespalko** [comment]
@ezyang,

Great idea. I think I need to specialize as follows:

```C++
template <typename dest_t, typename src_t>
C10_HOST_DEVICE inline dest_t static_cast_with_inter_type(src_t src) {
...
}

template <T>
C10_HOST_DEVICE inline dest_t static_cast_with_inter_type<thrust::complex<T>, std::complex<T>>(std::complex<T> src) {
  return reinterpret_cast<thrust::complex<T>>(src);
}

template <T>
C10_HOST_DEVICE inline dest_t static_cast_with_inter_type<std::complex<T>, thrust::complex<T>>(thrust::complex<T> src) {
  return reinterpret_cast<std::complex<T>>(src);
}
``` 

I'll give it a try.

**Comment by zasdfgbnm** [comment]
Let's see: https://github.com/thrust/thrust/issues/1033

**Comment by dylanbespalko** [comment]
@ezyang, @zasdfgbnm,

`reinterpret_cast` appears to be working between thrust::complex and std::complex. I don't get the warning anymore. Thanks.

**Comment by ezyang** [comment]
Great! I see this is still labeled WIP so lemme know when it's time to review.

**Comment by zasdfgbnm** [comment]
@dylanbespalko @ezyang Instead of using reinterpret cast, should we do the following instead? I am worried that assuming `thrust::complex` to be `{real, imag}` internally causes UB.

```C++
template <T>
C10_HOST_DEVICE inline dest_t static_cast_with_inter_type<thrust::complex<T>, std::complex<T>>(std::complex<T> src) {
  return thrust::complex<T>(src.real(), src.imag());
}

template <T>
C10_HOST_DEVICE inline dest_t static_cast_with_inter_type<std::complex<T>, thrust::complex<T>>(thrust::complex<T> src) {
  return reinterpret_cast<std::complex<T>>(T[2] {src.real(), src.imag()});
}
```
The first is defined because `.real` and `.imag` is `constexpr`, the second is defined because `std::complex` internally is `T[2]`.

**Comment by dylanbespalko** [comment]
@zasdfgbnm, 

I agree. There is also a situation where I have to cast between `float` and `double` precision:

std::complex<double> -> thrust::complex<float>
thrust::complex<double> -> std::complex<double>

Your solution would handle that correctly. I'll try it out.

**Comment by dylanbespalko** [comment]
Continued at #30295

**Pull request closed without merging**
