### PR TITLE
Preserve specialize_int_float during export

### PR DESCRIPTION
**Pull request by tugsbayasgalan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #95741

In the next PR, i will error when dynamo tries to add "implicit" input so that it doesn't fail during sanity check. 

cc @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by yanboliang — COMMENTED** [review]
If you want to preserve a config for export mode only, can you patch the config here?
https://github.com/pytorch/pytorch/blob/88a31f4be62c0197402f25475186740f0d1821af/torch/_dynamo/eval_frame.py#L620-L626

I think this is less change compared with yours, and more important, it makes a lot of sense to patch a config when calling this function rather than passing as an argument. I think this is different from dynamic shape, which is a general feature rather than for ```export``` only.

**Comment by tugsbayasgalan** [comment]
> If you want to preserve a config for export mode only, can you patch the config here?
> 
> https://github.com/pytorch/pytorch/blob/88a31f4be62c0197402f25475186740f0d1821af/torch/_dynamo/eval_frame.py#L620-L626
> 
> 
> 
> I think this is less change compared with yours, and more important, it makes a lot of sense to patch a config when calling this function rather than passing as an argument. I think this is different from dynamic shape, which is a general feature rather than for ```export``` only.

I think enable_dynamic happens later so it will override whatever the config we supply here. I agree it is kind of lot of code change for this small change.

**Review by yanboliang — APPROVED** [review]

**Pull request closed without merging**
