### PR TITLE
Fix pickling for Tensor subclasses.

### LINKED ISSUE #47051: Tensor subclasses lose type when pickling
## 🐛 Bug

Pickling and then unpickling a subclass of `Tensor` should result in an object of the same class as what was pickled. However, it doesn't - instead it always creates something of class `Tensor`.

## To Reproduce

The following prints `torch.Tensor`, however it should print `_T`.

```
class _T(torch.Tensor): ...
t = tensor([1]).as_subclass(_T)
print(type(pickle.loads(pickle.dumps(t))))
```

## Expected behavior

It should print `_T`.

## Environment

`torch.__version__` == 1.7.0, running on Ubuntu.

## Additional context

Placing the following method in the base class resolves the problem:

```
    def __reduce_ex__(self,proto):
        torch.utils.hooks.warn_if_has_hooks(self)
        args = (type(self), self.storage(), self.storage_offset(), tuple(self.size()), self.stride())
        if self.is_quantized: args = args + (self.q_scale(), self.q_zero_point())
        f = _fa_rebuild_qtensor if self.is_quantized else  _fa_rebuild_tensor
        return (f, args + (self.requires_grad, OrderedDict()))
```

Perhaps something like this could be used to fix this issue.

cc @hameerabbasi @rgommers @mruberry

### PR DESCRIPTION
**Pull request by hameerabbasi**
Fixes #47051

### CODE REVIEW

**Comment by ezyang** [comment]
@hameerabbasi what if the subclass tensor has extra data? Are these preserved?

**Comment by hameerabbasi** [comment]
> @hameerabbasi what if the subclass tensor has extra data? Are these preserved?

Good catch @ezyang. I added something that will also pickle the `__dict__`.

**Review by ezyang — APPROVED** [review]
I hope `__dict__` is enough. I guess people will tell us if it isn't...

**Comment by ezyang** [comment]
There's a chance this broke crypten, I'm investigating.

**Comment by hameerabbasi** [comment]
Does it rely on unpickling something pickled from older PyTorch versions? Pickling is usually not considered binary stable, and I assumed as such here.

**Comment by ezyang** [comment]
That's probably what's going on here. When I reverted I got a report that the revert also broke pickling XD. I'll need to rereview this more closely.

**Comment by ezyang** [comment]
@hameerabbasi To get the ball rolling, if you could reopen a PR resubmitting this, that would be very helpful.

**Comment by hameerabbasi** [comment]
Done in #47732.

**Pull request closed without merging**
