### PR TITLE
Revert per overload torch.ops API change

### PR DESCRIPTION
**Pull request by anjali411**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #71435

Differential Revision: [D33641371](https://our.internmc.facebook.com/intern/diff/D33641371)

### CODE REVIEW

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33641371).

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33641371).

**Comment by albanD** [comment]
Some tests will need to be updated for this to pass CI right>

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33641371).

**Pull request closed without merging**
