### PR TITLE
update mkldnn-bridge to avoid mem leak

### PR DESCRIPTION
**Pull request by gujinghui**
fix the memory leak issue exposed by #21537

### CODE REVIEW

**Comment by gujinghui** [comment]
@Jianhui-Li @uyongw @XiaobingSuper @jgong5

**Comment by gujinghui** [comment]
@bddppq @yinghai 
pls help review.

**Comment by bddppq** [comment]
@gujinghui Thanks for the fix!
Could you elaborate a little bit about the fix? (e.g. where were the threads created? Is `default_stream` still thread-safe after this change?)

**Review by bddppq — APPROVED** [review]

**Comment by bddppq** [comment]
foo

**Comment by uyongw** [comment]
> Could you elaborate a little bit about the fix? (e.g. where were the threads created? Is `default_stream` still thread-safe after this change?)

It is still thread-safe because `stream ` is now a temporal stack variable, instead of a _static_ thread-local storage that can hold internal state. That internal state may cause memory bloat. @bddppq

**Pull request closed without merging**
