### PR TITLE
[dynamo] simplify polyfill registration for `builtins.all` and `builtins.any`

### PR DESCRIPTION
**Pull request by XuehaiPan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #133895
* #133875
* #133876
* #133894
* #133864
* #133779
* #133778
* __->__ #133769

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec @xmfan

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by ZainRizvi** [comment]
@pytorchbot revert -c ghfirst -m "Sorry but this has been discovered to be causing a performance regression internally"

A potential cause has been theorized to be the added import for substitute_in_graph. @jansel can you please help fix the perf regression?  See the comments on D61717931 for more details

**Comment by ZainRizvi** [comment]
@pytorchbot revert -c ghfirst -m "Sorry but this has been discovered to be causing a performance regression internally"

A potential cause has been theorized to be the added import for substitute_in_graph. @jansel can you please help fix the perf regression?  See the comments on D61717931 for more details

**Comment by ZainRizvi** [comment]
closing the PR so that mergebot can revert and reopen it

**Comment by ZainRizvi** [comment]
@pytorchbot revert -c ghfirst -m "Sorry but this has been discovered to be causing a performance regression internally"

A potential cause has been theorized to be the added import for substitute_in_graph. @jansel can you please help fix the perf regression?  See the comments on D61717931 for more details

**Comment by XuehaiPan** [comment]
> A potential cause has been theorized to be the added import for substitute_in_graph. @jansel can you please help fix the perf regression? See the comments on D61717931 for more details

I added the logic for constant fold through for the `substitute_in_graph` API, hope it works this time. cc @jansel to request a re-review. Thanks!

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
