### PR TITLE
[dynamo 3.11] enable other torch 3.11 dynamo-related tests

### PR DESCRIPTION
**Pull request by williamwen42**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99180

Notes:
- No segfaults observed in any CI tests: dynamo unittests, inductor unittests, dynamo-wrapped pytorch tests. So we remove the warning that using dynamo 3.11 may result in segfaults.
- Fixed a weakreflist copying bug that caused a few dynamo-wrapped tests to hang.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @soumith @anijain2305 @Xia-Weiwen @peterbell10

### CODE REVIEW

**Comment by johnnynunez** [comment]
Python 3.11 support added via https://github.com/conda/conda/pull/12256, this will be included in the May release of conda 23.5.0

**Comment by johnnynunez** [comment]
Will be merged in the next release?

**Comment by williamwen42** [comment]
We're aiming to include this for 2.1 but we probably can't make it for 2.0.1

**Review by malfet — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting this, but linux-bionic-py3.11-clang9 test starts to timeout after this taking more than 3h30m. This is probably a landrace' -c landrace

The timeout test is `test_spectral_ops.py`

**Review by TamirFriedman-RecoLabs — APPROVED** [review]

**Pull request closed without merging**
