### PR TITLE
Remove code for using our own build cudnn image, use nvidia image

### PR DESCRIPTION
**Pull request by atalman**
Remove code for using our own build cudnn image, use nvidia imag

### CODE REVIEW

**Comment by xsacha** [comment]
I don't understand. 8.3.2 is available for CUDA 11.5. What was the problem?

**Comment by atalman** [comment]
> I don't understand. 8.3.2 is available for CUDA 11.5. What was the problem?

Yes, its available now via docker hub here:
https://hub.docker.com/layers/nvidia/cuda/11.5.0-cudnn8-devel-ubuntu18.04/images/sha256-cc7eeae1829e555aeca5149c8f63aaa729ca2d163859392e0607a5f2edc2c7d5?context=explore

Hence using this code rather our in house built image

**Review by malfet — APPROVED** [review]

**Comment by suo** [comment]
Try rebasing on latest master to make the build errors go away.

**Comment by atalman** [comment]
> Try rebasing on latest master to make the build errors go away.

Thanks Michael! Trying to rebase

**Pull request closed without merging**
