### PR TITLE
Add trigonometry functions for ONNX export

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Trigonometry functions are newly added to ONNX in a recent PR https://github.com/onnx/onnx/pull/869

This PR makes pytorch support exporting graphs with trigonometry functions.

This PR might need to wait until it is ready to change
```python
_onnx_opset_version = 6
```
to
```python
_onnx_opset_version = 7
```

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
I'm just trying to make the support for these functions faster. Feel free to close this if it is more convenient to implement all ONNX opset version bump together rather than in separate PRs.

**Comment by ezyang** [comment]
These seem pretty low risk, even if we don't bump the opset version.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@bddppq It should be easy to add in tree tests for these now, is that right?

**Comment by bddppq** [comment]
@ezyang yes in test/onnx/test_operators.py

But note caffe2 currently does not suppory asin, acos, atan and tan yet. Should be easy to add though.

**Comment by bddppq** [comment]
@ezyang these are new ops added in the newest opset, so the pytorch export opset has to be bumped

**Comment by zasdfgbnm** [comment]
I think if we add test, we have to bump up the op set version. Otherwise the test will not pass. If needed, I can bump up the version and take care of the other ops changed as specified in [ONNX/Changelog.md](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#version-7-of-the-default-onnx-operator-set).

But, is it safe to do this now, since ONNX opset version 7 is not stable yet? (In the future, if some changes happens on ONNX, then pytorch exporter might fail automatically, and changes are required to make unit tests pass.)

**Comment by ezyang** [comment]
Alright, sounds good, let's wait. (BTW, this is one of the reasons why I originally advocated for having all opset versions in ONNX be stable.)

**Comment by zou3519** [comment]
@zasdfgbnm  is this good to merge now?

**Review by bddppq — DISMISSED** [review]
This PR requires bumping the opset version in pytorch exported onnx models from 6 to 7. onnx has introduced some breaking changes (most notably broadcasting semantics) that caffe2 does not fully support at this moment. We are expecting to get the bump in around 1 week, until then we can not merge this PR.

**Comment by zasdfgbnm** [comment]
@zou3519 
I don't think it it good to merge now, because we still have  in `_onnx_opset_version = 6` in https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py#L93

But I do think it is time to bump up this version to 7, because [ONNX has just released 1.2 with opset version 7](https://github.com/onnx/onnx/issues/1023). The opset version 7 should be considered stable now, since by @linkerzhang:
> Operator Changes
Latest operator set version is 8 for ONNX domain and 1 for ONNX_ML domain.

Wait me for a couple of days and let me see if I can bump up that version.

**Comment by ezyang** [comment]
@bddppq Are we ready for opset version bump?

**Comment by sgarcia22** [comment]
How long is the expected time that it will be bumped to version 7?

**Comment by fmassa** [comment]
Opset version has been bumped to 7 https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py#L146

**Comment by bddppq** [comment]
@zasdfgbnm could you rebase to master and add test cases in tests/onnx/test_pytorch_onnx_caffe2.py? (test_operators only check the export successfully, it's better to also test the real computation).

**Comment by bddppq** [comment]
Need to update the expect files: https://ci.pytorch.org/jenkins/job/caffe2-builds/job/onnx-py2-gcc5-ubuntu16.04-test/2003/console

**Comment by bddppq** [comment]
```
17:35:10 >       test_func('acos')
...
17:35:10 E               AssertionError: 
17:35:10 E               Not equal to tolerance rtol=0.001, atol=1e-07
17:35:10 E               
17:35:10 E               (mismatch 100.0%)
17:35:10 E                x: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
17:35:10 E                      nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
17:35:10 E                      nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,...
17:35:10 E                y: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
17:35:10 E                      nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
17:35:10 E                      nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,...
```
Need to choose better test input data :-)

**Comment by zasdfgbnm** [comment]
@bddppq all fixed

**Review by bddppq — APPROVED** [review]
LG. Thanks!

**Pull request closed without merging**
