### PR TITLE
Cast device index to int before logging

### PR DESCRIPTION
**Pull request by kunalb**
int8_t = DeviceIndex is interpreted by cout as a char, which then shows up as a control character in logs (eg. ^A) etc.

Explicitly casting to int to have the numbers printed out correctly.

Fixes #ISSUE_NUMBER

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Comment by kunalb** [comment]
image

**Review by wconstab — APPROVED** [review]
lgtm. 

however this gives me dejavu. i may have fixed one of these before, but missed this one? or did we never land mine...

anyways, thanks!

**Comment by Skylion007** [comment]
Nit: could we static cast instead?

**Comment by kunalb** [comment]
but that's so much more typing! :(

**Comment by Skylion007** [comment]
@kunalb You need to run clang-format with lintrunner

**Pull request closed without merging**
