### PR TITLE
[CUDA] [CI] Disable flash attention for sm87 architecture when the head dim > 192

### PR DESCRIPTION
**Pull request by nWEIdia**
Head dim > 192 requires A100/H100 (sm80 or sm90) per TORCH_CHECK [here](https://github.com/pytorch/pytorch/blob/0c26565d5d76c371529320fd6176268028516a10/aten/src/ATen/native/transformers/cuda/flash_attn/flash_api.cpp#L760).

cc @eqy @ptrblck @malfet

### CODE REVIEW

**Review by eqy — APPROVED** [review]

**Comment by nWEIdia** [comment]
@malfet Could you please help review and approve the workflow runs? Thank you!

**Review by malfet — APPROVED** [review]
Sure, though name perhaps be changed to like isSM8X

**Comment by nWEIdia** [comment]
> Sure, though name perhaps be changed to like isSM8X

Thank you for your prompt response! I will do the variable name simplification.

**Comment by nWEIdia** [comment]
Variable renaming done. Looks like approval to run workflows is required again.

**Comment by nWEIdia** [comment]
@malfet Could you please help approve the workflow again? Thank you!

**Comment by nWEIdia** [comment]
Finally, @pytorchmergebot merge!

**Comment by nWEIdia** [comment]
It is in, thank you @eqy and @malfet !

**Pull request closed without merging**
