### PR TITLE
Remove native_functions.yaml dependency from DistributionBernoulli.cu

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #67875
* #67874
* __->__ #67721
* #66980
* #66979

This moves the operator calls (`expand_inplace` and `to(kCUDA)`) into
`bernoulli_impl_` which is shared between CPU and CUDA. So that the
cuda code only needs to generates random numbers and nothing else.

The other changes are just rearranging includes to avoid including
`Tensor.h`.

Differential Revision: [D32500426](https://our.internmc.facebook.com/intern/diff/D32500426)

### CODE REVIEW

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32500426).

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32500426).

**Review by dagitses — APPROVED** [review]

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32500426).

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32500426).

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32500426).

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32500426).

**Comment by peterbell10** [comment]
@dagitses I had to modify this PR because bernoulli was updated to cast `p` to a specific dtype on CUDA, which needs to come before the broadcast to avoid materializing the full expanded tensor. So, moving the `expand_inplace` call out of the cuda templates was no longer an option.

**Comment by dagitses** [comment]
@dagitses has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32500426).

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32500426).

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32500426).

**Comment by malfet** [comment]
@malfet has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32500426).

**Pull request closed without merging**
