### PR TITLE
[easy][DCP] make BroadcastingTorchSaveReader device generic

### PR DESCRIPTION
**Pull request by cdzhan**
Test test/distributed/checkpoint/test_format_utils.py on GPU and othor device pass.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @LucasLLC @MeetVadakkanchery @mhorowitz

### CODE REVIEW

**Comment by wz337** [comment]
This looks good to me. Leave to @LucasLLC to approve.

**Review by fegin — APPROVED** [review]
Thanks for the fix!

**Pull request closed without merging**
