### PR TITLE
[ci] disable flaky mobile-lightweight-dispatch-build

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #78557

As title, fixing it is tracked in
https://github.com/pytorch/pytorch/issues/78540.

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Review by janeyx99 — APPROVED** [review]

**Review by malfet — CHANGES_REQUESTED** [review]
Why not use `if: false` ?

**Comment by malfet** [comment]
Why wasn't it landed?

**Comment by janeyx99** [comment]
> Why wasn't it landed?

Cuz the cpp docs build is still going

**Comment by malfet** [comment]
I've quickly looked into cpp build times, but could not figure out what is going on

**Pull request closed without merging**
