### PR TITLE
fixing flag to skip nvfuser_tests build

### PR DESCRIPTION
**Pull request by jjsjann123**
Slowly pushing cmake cleanup to upstream.

avoids building nvfuser_tests when BUILD_TEST is disabled.
nvfuser_tests uses googletest from pytorch, which is only dragged when BUILD_TEST is enabled.

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]
Thanks!!

**Comment by davidberard98** [comment]
cc @huydhn @malfet

**Review by huydhn — APPROVED** [review]

**Comment by jjsjann123** [comment]
Looks like CI is struggling to pull images.. I'll try re-run tests.

**Comment by davidberard98** [comment]
@jjsjann123 i heard a suggestion to rebase past ca2a23c24331edfac84b0224732abf5571b89e00

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
