### PR TITLE
Mark PyTorch module as no-gil valid and pythoncapi_compat.h

### PR DESCRIPTION
**Pull request by albanD**
PyList_GetItem are audited but not other APIs yet (they will be done in a follow up PR to keep this one small enough).

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @rec

### CODE REVIEW

**Review by colesbury — APPROVED** [review]

**Comment by albanD** [comment]
Added back this old function we don't need because our c++ only build actually build with cpython 3.8 which we don't support and should never use.
But fixing the build is trickier so I'll just defer removing PyObject_CallMethodNoArgs to after this is done.

**Comment by albanD** [comment]
libtorch build should have been fixed in https://github.com/pytorch/builder/pull/2000 so this should go through now !

**Review by atalman — APPROVED** [review]
lgtm

**Pull request closed without merging**
