### PR TITLE
[Dynamic Shapes] fixed dynamic shape inference 

### LINKED ISSUE #122307: ConstraintViolationError not thrown when constraining dynamic dim to static int
### 🐛 Describe the bug

The following code section does not throw, despite the fact that x.shape[0] is constrained to a static value at the end of the function and x.shape[0] is marked as dynamic.

According to @lezcano the correct behavior would be to throw a ConstraintViolationError
See comment thread in https://github.com/pytorch/pytorch/pull/121808 

```python
import torch
import torch._dynamo.testing
import torch._inductor.ops_handler
import torch._inductor.utils
import torch._inductor
import torch._dynamo

def test_repro():
 
     def fn_2(x):
         # constrain in two directions
         if x.shape[0] > 5:
             return x.cos()
         if x.shape[0] < 5:
             return x * 2
         # x.shape[0] == 5 at this point
         return x.sin()

     torch._dynamo.reset()
     _x = torch.randn([5, 3, 3])
     torch._dynamo.mark_dynamic(_x, 0)
     torch.compile(backend="inductor", dynamic=None)(fn_2)(_x)

test_repro()
```

### Versions

Collecting environment information...
PyTorch version: 2.3.0a0+git1079f56
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: CentOS Stream 9 (x86_64)
GCC version: (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Clang version: 17.0.6 (CentOS 17.0.6-5.el9)
CMake version: version 3.26.4
Libc version: glibc-2.34

Python version: 3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-0_fbk12_zion_11583_g0bef9520ca2b-x86_64-with-glibc2.34
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA H100
GPU 1: NVIDIA H100

Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          92
On-line CPU(s) list:             0-91
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 9654 96-Core Processor
CPU family:                      25
Model:                           17
Thread(s) per core:              1
Core(s) per socket:              92
Socket(s):                       1
Stepping:                        1
BogoMIPS:                        4792.23
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 clzero xsaveerptr wbnoinvd arat npt lbrv nrip_save tsc_scale vmcb_clean pausefilter pfthreshold v_vmsave_vmload vgif avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities
Virtualization:                  AMD-V
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       5.8 MiB (92 instances)
L1i cache:                       5.8 MiB (92 instances)
L2 cache:                        46 MiB (92 instances)
L3 cache:                        1.4 GiB (92 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-91
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable, IBPB: conditional, IBRS_FW, STIBP: disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.6.0
[pip3] CoCa-pytorch==0.1.0
[pip3] dalle2-pytorch==1.14.2
[pip3] ema-pytorch==0.3.2
[pip3] flake8==3.8.2
[pip3] flake8-bugbear==20.1.4
[pip3] flake8-coding==1.3.3
[pip3] flake8-comprehensions==3.3.0
[pip3] flake8-executable==2.0.4
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==20.5.0
[pip3] flake8-simplify==0.19.3
[pip3] functorch==1.14.0a0+b71aa0b
[pip3] mypy==1.6.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] onnx==1.15.0
[pip3] onnxruntime-gpu==1.15.1
[pip3] open-clip-torch==2.24.0
[pip3] optree==0.10.0
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.3.3
[pip3] torch==2.3.0a0+git1079f56
[pip3] torch-fidelity==0.3.0
[pip3] torch_geometric==2.4.0
[pip3] torchaudio==2.2.0.dev20240119+cu121
[pip3] torchbench==0.1
[pip3] torchmetrics==1.0.3
[pip3] torchmultimodal==0.1.0b0
[pip3] torchrec==0.5.0
[pip3] torchvision==0.18.0.dev20240119+cu121
[pip3] torchvision==0.18.0a0+6f0deb9
[pip3] torchx==0.6.0
[pip3] triton==3.0.0
[pip3] triton-nightly==2.1.0.post20240108192258
[pip3] vector_quantize_pytorch==1.12.12
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] blas                      1.0                         mkl
[conda] clip-anytorch             2.6.0                    pypi_0    pypi
[conda] coca-pytorch              0.1.0                    pypi_0    pypi
[conda] dalle2-pytorch            1.14.2                   pypi_0    pypi
[conda] ema-pytorch               0.3.2                    pypi_0    pypi
[conda] functorch                 1.14.0a0+b71aa0b          pypi_0    pypi
[conda] mkl                       2023.1.0         h6d00ec8_46342
[conda] mkl-include               2023.1.0         h06a4308_46342
[conda] mkl-service               2.4.0           py311h5eee18b_1
[conda] mkl_fft                   1.3.6           py311ha02d727_1
[conda] mkl_random                1.2.2           py311ha02d727_1
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] open-clip-torch           2.24.0                   pypi_0    pypi
[conda] optree                    0.10.0                   pypi_0    pypi
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-warmup            0.1.1                    pypi_0    pypi
[conda] rotary-embedding-torch    0.3.3                    pypi_0    pypi
[conda] torch                     2.3.0a0+git1079f56           dev_0    <develop>
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torchaudio                2.2.0.dev20240119+cu121          pypi_0    pypi
[conda] torchbench                0.1                       dev_0    <develop>
[conda] torchfix                  0.2.0                    pypi_0    pypi
[conda] torchmetrics              1.0.3                    pypi_0    pypi
[conda] torchmultimodal           0.1.0b0                  pypi_0    pypi
[conda] torchrec                  0.5.0                    pypi_0    pypi
[conda] torchvision               0.18.0a0+6f0deb9          pypi_0    pypi
[conda] torchx                    0.6.0                    pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi
[conda] triton-nightly            2.1.0.post20240108192258          pypi_0    pypi
[conda] vector-quantize-pytorch   1.12.12                  pypi_0    pypi

cc @ezyang

### PR DESCRIPTION
**Pull request by zero000064**
Made dynamic dimension indirectly bound to an integer constrained.
After each ShapeEnv._refine_ranges, check if the new ValueRange is singleton, if it is, replace the symbol.

Fixes #122307

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @ezyang

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by zero000064** [comment]
Here's the information related to the failure, [inductor / linux-jammy-cpu-py3.8-gcc11-inductor / test (dynamic_cpu_inductor_torchbench, 1, 2, linux.12xlarge)](https://github.com/pytorch/pytorch/actions/runs/9557946267/job/26346263926).

This error comes from DALLE2_pytorch unable to be loaded on CPU, doesn't look like related to my code change.

> cpu  eval  DALLE2_pytorch                     
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/benchmarks/dynamo/common.py", line 4149, in run
    ) = runner.load_model(
  File "benchmarks/dynamo/torchbench.py", line 327, in load_model
    benchmark = benchmark_cls(
  File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/util/model.py", line 24, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/DALLE2_pytorch/__init__.py", line 21, in __init__
    raise NotImplementedError("DALL-E 2 Not Supported on CPU")
NotImplementedError: DALL-E 2 Not Supported on CPU

> DALLE2_pytorch                      FAIL:     accuracy=model_fail_to_load, expected=eager_fail_to_run

> Error: 1 models have accuracy status regressed:
    DALLE2_pytorch
    
> Error: Process completed with exit code 1.

**Comment by zero000064** [comment]
DALLE2_pytorch doesn't look related to the code change, its error is NotImplementedError: DALL-E 2 Not Supported on CPU.
Checking the first and the last to see if there's connection between the change and them.

`[inductor / cuda12.1-py3.12-gcc9-sm86 / test (inductor, 1, 1, linux.g5.4xlarge.nvidia.gpu)](https://hud.pytorch.org/pr/pytorch/pytorch/128807#26346794677) ([gh](https://github.com/pytorch/pytorch/actions/runs/9557946267/job/26346794677))
'Test' 
[inductor / linux-jammy-cpu-py3.8-gcc11-inductor / test (cpu_inductor_torchbench_freezing, 1, 2, linux.12xlarge)](https://hud.pytorch.org/pr/pytorch/pytorch/128807#26346263190) ([gh](https://github.com/pytorch/pytorch/actions/runs/9557946267/job/26346263190))
DALLE2_pytorch
[inductor / linux-jammy-cpu-py3.8-gcc11-inductor / test (cpu_inductor_torchbench, 1, 2, linux.12xlarge)](https://hud.pytorch.org/pr/pytorch/pytorch/128807#26346262516) ([gh](https://github.com/pytorch/pytorch/actions/runs/9557946267/job/26346262516))
DALLE2_pytorch
[inductor / linux-jammy-cpu-py3.8-gcc11-inductor / test (dynamic_cpu_inductor_torchbench, 1, 2, linux.12xlarge)](https://hud.pytorch.org/pr/pytorch/pytorch/128807#26346263926) ([gh](https://github.com/pytorch/pytorch/actions/runs/9557946267/job/26346263926))
DALLE2_pytorch
[trunk / macos-py3-arm64 / test (default, 1, 3, macos-m1-stable)](https://hud.pytorch.org/pr/pytorch/pytorch/128807#26356646373) ([gh](https://github.com/pytorch/pytorch/actions/runs/9557971266/job/26356646373))
export/test_serdes.py::SerDesExportTestExport::test_derived_dim_1_2_serdes`

**Comment by zero000064** [comment]
Just checked export/test_serdes.py::SerDesExportTestExport::test_derived_dim_1_2_serde, the following codes in export/test_export.py give some flexibility on input shape. But my code change ruins this flexibility, need to think about how to keep this flexibility. Luckily, it's Juneteenth tmr, I have some free time to investigate.
`        dx = Dim("dx", min=1, max=2)
        ep = export(
            Bar(),
            (torch.randn(2, 2), torch.randn(3, 2)),
            dynamic_shapes=({0: dx, 1: None}, {0: dx + 1, 1: None}),
        )`

**Comment by zero000064** [comment]
After investigation, the change doesn't deter exporting a graph module in test_derived_dim_1_2 in test_export.
`        ep = export(
            Bar(),
            (torch.randn(2, 2), torch.randn(3, 2)),
            dynamic_shapes=({0: dx, 1: None}, {0: dx + 1, 1: None}),
        )`
        
But it only allows the usage of a tensor with dim 2 and blocks the usage of tensor with any other dim figure. This scenario is not the intention because the change intends to block graph compliling.
`ep.module()(torch.randn(1, 2), torch.randn(2, 2))`
If the graph module is compiled sucessfully and the the usage meets the min-max requirement, the usage should be allowed. 
There might be something incorrectly set in the graph module, so it could be only used with dim 2.

**Comment by zero000064** [comment]
Before this code change, the graph's first placeholder node represents a fake tensor, `FakeTensor(..., size=(s0, 2)`.
After the code change, the graph's first placeholder node represents a fake tensor`FakeTensor(..., size=(2, 2)`.
The first dimension transforms into a number instead of a SymInt, which causes RuntimeError.
Need to investigate the placeholder node construction to make it turn back to SymInt.

**Comment by zero000064** [comment]
_update_var_to_range() is also called in constrain_symbol_range() when deserializing the the graph in _export, the potential solution might be avoiding code change in _update_var_to_range. Instead, move the code change to ShapeEnv._refine_ranges().
`  File "/home/zero064/Downloads/pytorch_fork/pytorch/test/export/test_serdes.py", line 53, in <module>
    run_tests()
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/_dynamo/test_case.py", line 36, in run_tests
    run_tests()
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/testing/_internal/common_utils.py", line 1174, in run_tests
    unittest.main(argv=argv)
  File "/home/zero064/anaconda3/envs/pytorch_dev/lib/python3.9/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/home/zero064/anaconda3/envs/pytorch_dev/lib/python3.9/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/home/zero064/anaconda3/envs/pytorch_dev/lib/python3.9/unittest/runner.py", line 184, in run
    test(result)
  File "/home/zero064/anaconda3/envs/pytorch_dev/lib/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/zero064/anaconda3/envs/pytorch_dev/lib/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/home/zero064/anaconda3/envs/pytorch_dev/lib/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/zero064/anaconda3/envs/pytorch_dev/lib/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/home/zero064/anaconda3/envs/pytorch_dev/lib/python3.9/unittest/case.py", line 651, in __call__
    return self.run(*args, **kwds)
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/testing/_internal/common_utils.py", line 2883, in run
    self._run_custom(
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/testing/_internal/common_utils.py", line 2855, in _run_custom
    super_run(result=result)
  File "/home/zero064/anaconda3/envs/pytorch_dev/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/home/zero064/anaconda3/envs/pytorch_dev/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/testing/_internal/common_utils.py", line 2754, in wrapper
    method(*args, **kwargs)
  File "/home/zero064/Downloads/pytorch_fork/pytorch/test/export/testing.py", line 40, in _fn
    return fn(*args, **kwargs)
  File "/home/zero064/Downloads/pytorch_fork/pytorch/test/export/test_export.py", line 1178, in test_derived_dim_1_2
    ep = export(
  File "/home/zero064/Downloads/pytorch_fork/pytorch/test/export/test_serdes.py", line 21, in mocked_serder_export
    loaded_ep = load(buffer)
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/export/__init__.py", line 300, in load
    return load(
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/_export/__init__.py", line 336, in load
    ep = deserialize(artifact, expected_opset_version)
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/_export/serde/serialize.py", line 2368, in deserialize
    ExportedProgramDeserializer(expected_opset_version)
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/_export/serde/serialize.py", line 2247, in deserialize
    GraphModuleDeserializer()
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/_export/serde/serialize.py", line 1849, in deserialize
    self.deserialize_graph(serialized_graph_module.graph)
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/_export/serde/serialize.py", line 1586, in deserialize_graph
    meta_val = self.deserialize_tensor_meta(tensor_value)
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/_export/serde/serialize.py", line 1553, in deserialize_tensor_meta
    tuple(self.deserialize_sym_int(val) for val in tensor_meta.sizes),  # type: ignore[misc]
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/_export/serde/serialize.py", line 1553, in <genexpr>
    tuple(self.deserialize_sym_int(val) for val in tensor_meta.sizes),  # type: ignore[misc]
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/_export/serde/serialize.py", line 1500, in deserialize_sym_int
    self.shape_env.constrain_symbol_range(
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/fx/experimental/recording.py", line 245, in wrapper
    return fn(*args, **kwargs)
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/fx/experimental/symbolic_shapes.py", line 5465, in constrain_symbol_range
    self._update_var_to_range(s, upd_vr)
  File "/home/zero064/Downloads/pytorch_fork/pytorch/torch/fx/experimental/symbolic_shapes.py", line 4722, in _update_var_to_range
    log.warning("traceback:%s", traceback.print_stack())`

**Comment by zero000064** [comment]
Moved the replacement logic to ShapeEnv._refine_ranges.

Tested these test cases including reported failure ones.
`TORCH_LOGS="+dynamic,+dynamo" python test/dynamo/test_misc.py -k test_raise_guard_indirect_full_constraint

TORCH_LOGS="+dynamic,+dynamo" python test/dynamo/test_misc.py -k test_guard_failure_fn_shape_control

TORCH_LOGS="+dynamic,+dynamo" python test/dynamo/test_subclasses.py -k test_wrapper_subclass_guards_on_inner_tensor

TORCH_LOGS="+dynamic,+dynamo" python test/export/test_serdes.py -k test_derived_dim_1_2_serdes
`

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
