### PR TITLE
Add HIPSolver backend to `linalg.eigh`

### PR DESCRIPTION
**Pull request by jeffdaily**
cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
SGTM provided CI agrees

**Comment by lezcano** [comment]
You'll probably need to put together some heuristics for HIP against magma. Not for this function but for everything in linalg. The current heuristics were benchmarked on CUDA devices.

**Comment by jeffdaily** [comment]
> You'll probably need to put together some heuristics for HIP against magma. Not for this function but for everything in linalg. The current heuristics were benchmarked on CUDA devices.

You were spot on, absolutely correct.  hipSolver's syevj is significantly faster than its syevd.  Let's see how CI behaves with this change.

**Pull request closed without merging**
