### PR TITLE
doc: `torch.utils.data.Sampler`: `__len__` is optional

### PR DESCRIPTION
**Pull request by kuraga**
Fixes #ISSUE_NUMBER

cc @andrewkho , @gokulavasan , @ejguan

### CODE REVIEW

**Comment by kuraga** [comment]
Ping.

**Review by andrewkho — APPROVED** [review]
LGTM, we can land this once the CI is finished

**Review by xmfan — APPROVED** [review]

**Comment by kuraga** [comment]
Thanks!

**Pull request closed without merging**
