### PR TITLE
Allow torchdispatch to customize dim()

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #78691
* #78646

This follows the template in
https://github.com/pytorch/pytorch/pull/77396

### CODE REVIEW

**Comment by suo** [comment]
I still need to thread symints through this, but will do that in a followup

**Review by ezyang — APPROVED** [review]
BTW I kind of wondered if we should have one more policy distinction between custom sizes and custom dim; e.g., maybe the sizes are symbolic but the dim is fixed. IDK, maybe not worth.

**Comment by suo** [comment]
We only have 2 bits for it, so that would be the last policy unless we wanted to make it bigger (our bitfield is currently 14 bits so I guess we could probably stick 2 more in there).

**Comment by ezyang** [comment]
isn't -g the wrong flag, you should use -a?

**Comment by suo** [comment]
yes oops

**Pull request closed without merging**
