### PR TITLE
Cleaner implementation of bitwise operations of integeral types

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #34104 Remove the use of macros when defining division between integers
* **#33849 Cleaner implementation of bitwise operations of integeral types**
* #33835 Use templates instead of macros when defining bitwise operators.

For integral types, there is no need to manipulate with
`reinterpret_cast` and therefore a cleaner implementation is available.
This might also be helpful on some less optimized compilers or on a less optimized arch (while a
test on gcc 8.3 x64 shows no difference in performance).

Differential Revision: [D20222675](https://our.internmc.facebook.com/intern/diff/D20222675)

### CODE REVIEW

**Comment by ailzhang** [comment]
cc @cpuhrsch, can you help review this PR? ;) 
(Please feel free to remove yourself if it's not a good fit).

**Comment by cpuhrsch** [comment]
Pinging @VitalyFedyunin - let me know if I can help

**Comment by VitalyFedyunin** [comment]
Code looks good, my only concern is how much 'cleaner' it is in compare to the current version.

**Comment by xuhdev** [comment]
@VitalyFedyunin This might be a bit arguable -- The integer version is separated out and is potentially open to future optimization, and the general version is limited to non-integers.

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
CC @ezyang as he needs to import/land whole stack

**Comment by ezyang** [comment]
@VitalyFedyunin if you're going to do the entire stack, just commandeer my diff and land it

**Pull request closed without merging**
