### PR TITLE
[inductor] enable fx graph cache on torchbench

### PR DESCRIPTION
**Pull request by masnesral**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128239

Summary: We've already enabled for timm and huggingface, but we had failures saving cache entries for moco. It looks like https://github.com/pytorch/pytorch/pull/128052 has fixed that issue, so we can enable for torchbench.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by oulgen — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but it seems to surface a bunch of inductor failures in trunk https://hud.pytorch.org/pytorch/pytorch/commit/734e8f6ad7e7f0fa0341fb658f1f986225173f5f' -c weird

The error is, so maybe a landrace?

```
2024-06-11T01:38:22.4791538Z torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
2024-06-11T01:38:22.4792308Z NameError: name 'FloatTrueDiv' is not defined
```

**Comment by huydhn** [comment]
Thank you for the fix.  I don't think you missed anything with both `ciflow/inductor` and `ciflow/trunk` and no force merge.  However, trunk failures could still occur in the event of a landrace with another change (https://github.com/pytorch/pytorch/pull/126905).  So, fixing the race, rebase, and reland the PR is the correct way to address it.

**Pull request closed without merging**
