### PR TITLE
Add validator to ensure runner determinator script is kept in sync

### PR DESCRIPTION
**Pull request by ZainRizvi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #134816
* __->__ #134800
* #134796

We keep two copies of the runner-determinator script:
1. In runner_determinator.py, for ease of testing.  This however is not actually executed during CI
2. Embedded in _runner-determinator.yml.  This is what CI uses.

Why the duplication? Short version: Because of how github CI works, during a given CI run the workflow yml files could actually come from the main branch, while the remaining files get read from the local commit.
This can lead to a newer version of _runner-determinator.yml trying to invoke an older version of runner_determintor.py than it was actually designed for. Chaos ensues.

We mitigate this by embedding the script into the yml file.  But we still keep the script around because it's much easier to run tests against.

This workflow's job is to ensure that if one edits the script in one of those two locations then they remember to update it in the other location as well

### CODE REVIEW

**Comment by malfet** [comment]
If script is embedded into the workflow file, why keep it around at all?

**Review by zxiiro — APPROVED** [review]

**Comment by zxiiro** [comment]
> If script is embedded into the workflow file, why keep it around at all?

Locally we can test by running `python script.py` which is useful when developing the script without having to push to GitHub to trigger CI for quick testing.

**Comment by ZainRizvi** [comment]
> If script is embedded into the workflow file, why keep it around at all?

Like @zxiiro said, it's really annoying to test the script otherwise. Plus this lets us run the linter against it.

**Review by PaliC — APPROVED** [review]

**Pull request closed without merging**
