### PR TITLE
Add squeeze, unsqueeze, transpose shape functins

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #64323 Add embedding shape analysis
* #64121 Max Pool with indices
* #63530 Add Maxpool to shape analysis / Opinfo
* #64300 Add symbolic shape comparison optimization
* #64299 Refactor to use shape arguments
* #63516 Add view with negative dim
* #63615 Generalize expand logic
* #63407 Add permute, arange
* #63365 Add support for slice, selec twith int, index_select
* **#63099 Add squeeze, unsqueeze, transpose shape functins**
* #63050 Add batch of unary functions

These are checked by OpInfos, which represent all of the inputs and semantics of the operators so it should be an easy stamp

Differential Revision: [D30347514](https://our.internmc.facebook.com/intern/diff/D30347514)

### CODE REVIEW

**Review by ZolotukhinM — APPROVED** [review]
Nice!

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30347514).

**Review by desertfire — APPROVED** [review]

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30347514).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30347514).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30347514).

**Pull request closed without merging**
