### PR TITLE
Revert D59842197

### PR DESCRIPTION
**Pull request by eellison**
Summary:
This diff reverts D59842197
(The context such as a Sandcastle job, Task, SEV, etc. was not provided.)

Test Plan: NA

Reviewed By: oulgen, eellison

Differential Revision: D59983321

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

@diff-train-skip-merge
Reverted https://github.com/pytorch/pytorch/pull/125264 using mergebot.

### CODE REVIEW

**Review by oulgen — APPROVED** [review]

**Comment by izaitsevfb** [comment]
Reverted #125264 using mergebot.

**Pull request closed without merging**
