### PR TITLE
[FSDP] Make summon_full_params a public method

### PR DESCRIPTION
**Pull request by fegin**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #73553
* #73530
* __->__ #73116

Users may need summon_full_params() to get the original parameters.

Differential Revision: [D34353034](https://our.internmc.facebook.com/intern/diff/D34353034/)

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
I think we can do this as long as we have consensus on name, API, defaults, etc. 

The main thing I think will be the default setting of `writeback` which is currently `True`, users will have to explicitly pass in `writeback=False` to get better perf. However summon_full_params is mostly for debugging, or checkpointing and I think the usability improvement is worth the tradeoff here. We can also always flip the param if need be before the release.

**Comment by fegin** [comment]
@rohan-varma agree. The default value of write_back should be False.

**Review by rohan-varma — COMMENTED** [review]
@fegin Maybe I miscommunicated, but why should it be `False` over the current `True`? From what I understand `summon_full_params` is not currently on a perf critical path, and writeback=True by default is nice because modifications will persist by default (or perhaps modifying state by default is not great?)

**Comment by fegin** [comment]
Okay, I misunderstood your original comment. My thought was that `summon_full_params` and many other functions in FSDP create copies of the original parameters. With copy, writeback gives me an impression that it is not the default behavior. This is not a strong argument. So either way works for me.

**Pull request closed without merging**
