### PR TITLE
[ONNX] Opset 17 STFT support

### PR DESCRIPTION
**Pull request by justinchuby**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #83944

#81075 

TODO: 
- Split complex input into real
- Test

### CODE REVIEW

**Comment by nateanl** [comment]
Hi @justinchuby, thanks for working on the STFT support. Is the PR ready for review?

**Comment by justinchuby** [comment]
@nateanl thanks for asking! The PR is not ready yet. I started it and got distracted.

**Comment by mravanelli** [comment]
Thank you @justinchuby. Is there any news? It would be really great to have in in the next version of pytorch. This is something we actually need for [SpeechBrain](https://speechbrain.github.io/) because we need the feature extraction pipeline to be ONN-exportable.

**Comment by justinchuby** [comment]
@mravanelli A more realistic issue I realized is ONNX doesn't have the appropriate ops to handle complex <-> real matrix conversion. Since the STFT op in python operates on complex numbers and onnx STFT operates on real numbers, I will need to think harder about how this is possible.

Assuming onnx does support the operator, you can always implement and register a custom symbolic function (https://pytorch.org/docs/stable/onnx.html#adding-support-for-operators) and not have to worry about pytorch release cycles.

**Pull request closed without merging**
