### PR TITLE
refactor autocast to be extensible for devices

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#57104 refactor autocast to be extensible for devices**

Differential Revision: [D28094173](https://our.internmc.facebook.com/intern/diff/D28094173)

### CODE REVIEW

**Comment by leslie-fang-intel** [comment]
@ezyang reopen the one with ghstack. cc @jgong5

**Comment by ezyang** [comment]
hmm, I'm pretty sure the CUDA failures are not your fault, but it's still a little concerning. Can you rebase to origin/master and then resubmit it on ghstack?

**Review by ezyang — APPROVED** [review]

**Comment by leslie-fang-intel** [comment]
Rebased~

**Comment by leslie-fang-intel** [comment]
> hmm, I'm pretty sure the CUDA failures are not your fault, but it's still a little concerning. Can you rebase to origin/master and then resubmit it on ghstack?

Thanks @ezyang  It has passed all the UT. Should this get merged firstly and I ghstack a new commit?

**Comment by ezyang** [comment]
You can stack another PR on top of this while I work on landing this :)

**Comment by leslie-fang-intel** [comment]
Looks like there are some internal Builds/Tests Error, But I can't see the details.

**Pull request closed without merging**
