### PR TITLE
[Profiler] Move python tracing to unified event type (Part 2)

### PR DESCRIPTION
**Pull request by robieta**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #78164
* #78163
* #78162

This PR finishes moving over the python tracer to use the unified event type. Things that changed:

1) The hacky after-the-fact splicing of python events in profiler_kineto.cpp is gone and python events now simply fold into the rest. (Yay!!!) This is a major BE win.
2) Added `ExtraFields<EventType::PyCall>` and `ExtraFields<EventType::PyCCall>`
3) The enter events (time + TraceKey) are now handled by RecordQueue for performance.
4) Python tracing now uses TSC for lower overhead.

Simplifications in profiler_python WRT part 1:
1) Rather than ValueCache emitting an intermediate value_t that gets further converted, load methods can now directly emit ExtraFields<...>
2) The complicated replay in profiler_python.cpp is replaced with a much simpler (and safer) pass to just pair start and end times.
3) During post processing we can now use `CallTypeHelper::map` to automatically pull in all events instead of having to loop over each the entries for each type manually. This will make it simpler to add new types of Python event later.

Differential Revision: [D36515869](https://our.internmc.facebook.com/intern/diff/D36515869/)

### CODE REVIEW

**Review by aaronenyeshi — APPROVED** [review]
LGTM, reviewed internally.

**Comment by robieta** [comment]
This PR is showing some stubborn platform dependent failures on the newly introduced test cases. In some respects that makes me happy as it means the code is being thoroughly tested. However the debug process is rather painful since the diffs are too large to render and as a result you have to SSH into a CI machine. To help with this I'm beefing up the helpers in `test_profiler.py`

**Comment by malfet** [comment]
@pytorchbbot revert -m "Broke cuda-on-cpu tests, see https://hud.pytorch.org/pytorch/pytorch/commit/c2a3c8186c3f3798684cecd60d62a991c223eeef" -c "missingsignal"

**Comment by malfet** [comment]
@pytorchbbot revert -m "Broke cuda-on-cpu tests, see https://hud.pytorch.org/pytorch/pytorch/commit/c2a3c8186c3f3798684cecd60d62a991c223eeef" -c "nosignal"

**Pull request closed without merging**
