### PR TITLE
Do not convert BatchNorm1d to mkldnn

### LINKED ISSUE #61223: optimize_for_inference does not handle MKLDNN for BatchNorm1d
## 🐛 Bug

The process to convert frozen ops to MKLDNN has checks for Linear and Conv dimensions but none for BatchNorm.

See: https://github.com/pytorch/pytorch/blob/b162d95e461a5ea22f6840bf492a5dbb2ebbd151/torch/csrc/jit/passes/frozen_ops_to_mkldnn.cpp#L946

## To Reproduce

1. Model that has BatchNorm1d
2. torch.jit.optimize_for_inference(model)
3. RuntimeError: mkldnn_batch_norm: currently mkldnn inference only support 2d and 3d batchnorm

## Expected behavior

Does not convert the op

## Environment

 - PyTorch Version (e.g., 1.0): 1.10
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information:

### PR DESCRIPTION
**Pull request by xsacha**
It is unsupported within Mkldnn

Fixes #61223

Edit: Changes appear not to work

### CODE REVIEW

**Comment by eellison** [comment]
hey @xsacha, thanks for the patch. Would it be possible to add batchnorm1d support to mkldnn instead ? We are working on [shape inference](https://github.com/pytorch/pytorch/issues/54982) and it should ready as a dependency for checking stuff like within a month, but it's not quite ready yet.

**Comment by xsacha** [comment]
That would be ideal. I tried to do unsqueeze and view and it told me the mkldnn tensor doesn't support strides. If that's coming soon, I'll wait for it.
Also, from what I can tell mkldnn does operate on 1d for batch norm already so I'm not sure if the limit is artificially set from ideep.

**Comment by eellison** [comment]
Do you mind posting a snippet of the subgraph that produces batchnorm1d ?

**Comment by xsacha** [comment]
It doesn't matter what the subgraph looks like. Even a module containing only BatchNorm1d produces this, but I'll give an example anyway.

```
  (output_layer): Sequential(
    (0): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (1): Dropout(p=0.4, inplace=False)
    (2): Flatten()
    (3): Linear(in_features=25088, out_features=512, bias=True)
    (4): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=False, track_running_stats=True)
  )
```
```
.output_layer.0
  %1592 : int = aten::size(%input.397, %29), scope: __module.output_layer/__module.output_layer.2
  %1593 : int[] = prim::ListConstruct(%1592, %1575), scope: __module.output_layer/__module.output_layer.2
  %input.401 : Tensor = aten::reshape(%input.397, %1593), scope: __module.output_layer/__module.output_layer.2
  %input : Tensor = aten::linear(%input.401, %self.output_layer.3.weight, %self.output_layer.3.bias), scope: __module.output_layer/__module.output_layer.3
  %1600 : Tensor = aten::batch_norm(%input, %26, %26, %self.output_layer.4.running_mean, %self.output_layer.4.running_var, %28, %24, %25, %30), scope: __module.output_layer/__module.output_layer.4
```

**Comment by eellison** [comment]
Gotcha. You could try replacing BatchNorm1d with its decomposed ops as a temporary workaround...

**Comment by xsacha** [comment]
How does that work? You mean aten::batch_norm?
That's the op that optimize_for_inference looks for when converting to MKL already.
My aim is to optimize MKL at runtime because the weights can't be serialised to disk still.

**Pull request closed without merging**
