### PR TITLE
[PyTorch] make InstanceNorm1d raise an error if the input is 2D

### LINKED ISSUE #11991: [PyTorch] InstanceNorm1d does not work to 2D tensor as we expect.
This issue is related to #9776 and #9924.

## Issue description
When applying `InstanceNorm1d` to 2D tensor, all the outputs are 0.
This is because the variance corresponding to the input is always 0.
Also, I think there are no appropriate tests for 2D tensor.
https://github.com/pytorch/pytorch/blob/76ab26cc3eff1d7ba822d8db93723f5c9598eead/test/test_nn.py#L2299-L2316

I think there is no way to avoid this error.

## Code example
Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

```
In [1]: import torch, torch.nn as nn

In [2]: x = torch.randn(10, 3)

In [3]: in1d = nn.InstanceNorm1d(3)

In [4]: y = in1d(x)

In [5]: y
Out[5]:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]: in1d = nn.InstanceNorm1d(3, affine=True, track_running_stats=True)

In [7]: y = in1d(x)

In [8]: in1d.bias
Out[8]:
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)

In [9]: in1d.weight
Out[9]:
Parameter containing:
tensor([0.1409, 0.7195, 0.9171], requires_grad=True)

In [10]: in1d.running_mean
Out[10]: tensor([-0.0082,  0.0239,  0.0048])

In [11]: in1d.running_var
Out[11]: tensor([nan, nan, nan])
```

## System Info
```shell
miniconda3-latest ❯ python collect_env.py
Collecting environment information...
PyTorch version: 1.0.0.dev20180921
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.1.3
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn_static.a
/usr/local/lib/libcudnn.so.7.0.5
/usr/local/lib/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.8.0)
[pip] torch (1.0.0.dev20180921)
[conda] pytorch-nightly           1.0.0.dev20180921 py3.6_cuda9.0.176_cudnn7.1.2_0    pytorch
```

### PR DESCRIPTION
**Pull request by crcrpar**
Resolves #11991 .

Any comment is welcome.

### CODE REVIEW

**Comment by dhpollack** [comment]
@soumith this should probably be merged.  InstanceNorm with 2d inputs always returns a tensor of zeros which is not a desirable, albeit mathematically correct, outcome.

**Review by soumith — APPROVED** [review]
sorry for the delay, yes this seems reasonable.

**Comment by 00sapo** [comment]
Maybe the documentation should be corrected. It still reports that the input can be 2D: 

  num_features – CC from an expected input of size (N,C,L)(N, C, L) or LL from input of size (N,L)(N, L)

**Pull request closed without merging**
