### PR TITLE
Generate patterns in fp16 and fp32

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #109066
* #109156
* __->__ #109142
* #108917
* #108894
* #109663

aten.softmax will generate a different decomposition for fp16/bf16 and fp32 because when invoked in lower precision it will upcast the inputs to fp32 and then downcast after. This has been causing us to miss bf16 patterns. For example, Camembert improves 20% with this PR (as do I'm sure many other models).

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Comment by eellison** [comment]
cc @drisspg, after rebasing past fv2, meta stride propagation is incorrect.

```
FAIL: test_sdpa_rewriter_1_cuda (__main__.SDPAPatternRewriterCudaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/eellison/work/pytorch/torch/testing/_internal/common_utils.py", line 1283, in wrapper
    return fn(*args, **kwargs)
  File "test/inductor/test_fused_attention.py", line 115, in _test_sdpa_rewriter_1
    self._check_common(dot_prod_attention, dtype=dtype, atol=0.001, rtol=rtol)
  File "test/inductor/test_fused_attention.py", line 70, in _check_common
    result2, (source_code,) = run_and_get_code(
  File "/scratch/eellison/work/pytorch/torch/_inductor/utils.py", line 829, in run_and_get_code
    result = fn(*args, **kwargs)
  File "/scratch/eellison/work/pytorch/torch/_dynamo/eval_frame.py", line 397, in _fn
    return fn(*args, **kwargs)
  File "test/inductor/test_fused_attention.py", line 100, in dot_prod_attention
    def dot_prod_attention(
  File "/scratch/eellison/work/pytorch/torch/_dynamo/eval_frame.py", line 397, in _fn
    return fn(*args, **kwargs)
  File "/scratch/eellison/work/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/scratch/eellison/work/pytorch/torch/_functorch/aot_autograd.py", line 3905, in forward
    return compiled_fn(full_args)
  File "/scratch/eellison/work/pytorch/torch/_functorch/aot_autograd.py", line 1482, in g
    return f(*args)
  File "/scratch/eellison/work/pytorch/torch/_functorch/aot_autograd.py", line 2533, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/scratch/eellison/work/pytorch/torch/_functorch/aot_autograd.py", line 1506, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/scratch/eellison/work/pytorch/torch/_functorch/aot_autograd.py", line 1594, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "/scratch/eellison/work/pytorch/torch/_inductor/codecache.py", line 396, in __call__
    return self.get_current_callable()(inputs)
  File "/scratch/eellison/work/pytorch/torch/_inductor/compile_fx.py", line 616, in run
    return model(new_inputs)
  File "/scratch/eellison/work/pytorch/torch/_inductor/codecache.py", line 423, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/torchinductor_eellison/2m/c2mkma5h4mw3jpc2ixso7f6ccno2vqe3oqdzr3j7pkvtnc55lh6o.py", line 39, in call
    assert_size_stride(buf1, (4, 2, 16, 32), (1024, 512, 32, 1))
AssertionError: expected size 2==2, stride 32==512 at dim=1
```

**Comment by drisspg** [comment]
@eellison Do you have a repro/test I can use to fix this?

**Comment by eellison** [comment]
```
import torch
from torch._dynamo.testing import rand_strided
arg0_1 = rand_strided((4, 2, 16, 32), (1024, 512, 32, 1), device='cuda:0', dtype=torch.float16)
arg1_1 = rand_strided((4, 2, 16, 32), (1024, 512, 32, 1), device='cuda:0', dtype=torch.float16)
arg2_1 = rand_strided((4, 2, 16, 32), (1024, 512, 32, 1), device='cuda:0', dtype=torch.float16)
with torch._subclasses.fake_utils.CrossRefFakeMode():
    torch.ops.aten._scaled_dot_product_flash_attention(arg0_1, arg1_1, arg2_1, scale=0.17677669529663687)
```

**Comment by drisspg** [comment]
https://github.com/pytorch/pytorch/pull/109346/ I am confused this isn't reproing for me locally

**Pull request closed without merging**
