### PR TITLE
GHA: make obvious when we are running smoke tests to user

### PR DESCRIPTION
**Pull request by janeyx99**
This PR clarifies what's run on PRs by explicitly stating when it runs smoke tests for windows CUDA and makes the logic so that user defined labels override other workflow logic.

1. Move smoke tests to its own config.

2. Make sure that when a user specifies a ciflow label that is not the default, the workflow runs as if it is on trunk.

Test plan: the default on PRs would generate this matrix (default replaced by smoke_tests)
image
But when retriggered with a label, it looks like (note that there's no smoke_tests config):
image

### CODE REVIEW

**Comment by janeyx99** [comment]
> Move smoke tests to its own config.
> 
> Make sure that when a user specifies a ciflow label that is not the default, the workflow runs as if it is on trunk.

**Review by seemethere — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
