### PR TITLE
Remove symbol export annotations in THC/generic/*.cu

### PR DESCRIPTION
**Pull request by peterjc123**
We use these annotations during function declarations, not definitions. See the description of compiler error [C2491](https://msdn.microsoft.com/en-us/library/62688esh.aspx) for more details.

### CODE REVIEW

**Review by Yangqing — APPROVED** [review]

**Comment by Yangqing** [comment]
@peterjc123 since THC_API also includes the THC_EXTERN (aka extern "C") - maybe we need to change it to THC_EXTERN instead of removing it?

**Review by Yangqing — DISMISSED** [review]
(see comment above)

**Comment by peterjc123** [comment]
@Yangqing Sorry, I don't quite get the reasons to change them to `THC_EXTERN`. I removed them because these functions are already annotated as `THC_API` in the header files. So the annotations in the source file are duplicated and sometimes cause compiling errors like C2491. Current build failed due to some missing function declarations.

**Comment by peterjc123** [comment]
The missing of the export symbols `sort`, `sortKeyValueInplace` and `topk` is caused by the broken reference link. It seems these header files have been referenced in `THC/THCTensorMath.h` and then `THC/THC.h`. But no file has the reference to `THC/THC.h` during the build. May I know how to fix this reference link?

**Comment by Yangqing** [comment]
Ah makes sense, I'll leave the symbol issues for the original TH authors to deal with then...

**Comment by peterjc123** [comment]
cc. @ezyang @fmassa

**Comment by yf225** [comment]
@peterjc123 probably need a rebase

@ezyang @fmassa Any suggestions for this PR?

**Comment by peterjc123** [comment]
@ezyang @soumith Could you please take a look and merge this PR, please?

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
