### PR TITLE
disable attn_mask for mha because crash

### LINKED ISSUE #97409: nn.MultiheadAttention breaks for mask_type=2 when fast path is enabled (e.g. with batched attn_mask)
### 🐛 Describe the bug

**TLDR:** When `nn.MultiheadAttention` is used with a batched `attn_mask` which [should be](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html) shape (N*H, L, S) (where S=L for self-attn) **_and_** fast path is enabled it crashes.

_It works as expected when fast path is **not** enabled_

### Minimal example to reproduce:

```python
import torch
import torch.nn as nn


with torch.no_grad():
    B = 8
    L = 100
    D = 512
    H = 8

    mha = nn.MultiheadAttention(D, H, batch_first=True)

    X = torch.randn(B, L, D)
    M = torch.randn(B * H, L, L) > 0

    mha.train()  # disable fast path
    out, _ = mha(X, X, X, attn_mask=M, need_weights=False)  # works
    mha.eval()  # enable fast path
    out, _ = mha(X, X, X, attn_mask=M, need_weights=False)  # crashes
```

Gives:
```
RuntimeError: For mask_type == 2 mask shape should match input shape
```

I did a little debugging in the torch code around [here](https://github.com/pytorch/pytorch/blob/fe0afc58529bdf148bfda580a60e3d778b5b8f1d/torch/nn/modules/activation.py#L1176) and it seems that when `self.merge_masks` is called the `mask_type` returned is 0. However, when `torch._native_multi_head_attention` is called with `mask_type=0` but a (N*H, L, S) `attn_mask`, it seems to ignore the `mask_type` flag (see error above).

I'm on pytorch 2.0 (conda) on M2 Max macOS 13.2.1.

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.16 (main, Jan 11 2023, 10:02:19)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] lion-pytorch==0.0.4
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.0.0
[pip3] pytorch-wavelets==1.3.0
[pip3] torch==2.0.0
[pip3] torch-yin==0.1.3
[pip3] torchaudio==2.0.0
[pip3] torchmetrics==0.11.1
[pip3] xitorch==0.4.0.dev0+3327cc0
[conda] lion-pytorch              0.0.4                    pypi_0    pypi
[conda] numpy                     1.23.5           py39h1398885_0  
[conda] numpy-base                1.23.5           py39h90707a3_0  
[conda] pytorch                   2.0.0                   py3.9_0    pytorch
[conda] pytorch-lightning         2.0.0                    pypi_0    pypi
[conda] pytorch-wavelets          1.3.0                    pypi_0    pypi
[conda] torch-yin                 0.1.3                    pypi_0    pypi
[conda] torchaudio                2.0.0                  py39_cpu    pytorch
[conda] torchmetrics              0.11.1                   pypi_0    pypi
[conda] xitorch                   0.4.0.dev0+3327cc0          pypi_0    pypi

cc @ezyang @gchanan @zou3519 @jbschlosser @bhosmer @cpuhrsch @erichan1

### PR DESCRIPTION
**Pull request by erichan1**
Fixes https://github.com/pytorch/pytorch/issues/97409

Added test case

cc @jbschlosser @bhosmer @cpuhrsch @drisspg

### CODE REVIEW

**Comment by drisspg** [comment]
While this prevents the bug does this really fix the problem?

**Comment by erichan1** [comment]
> While this prevents the bug does this really fix the problem?
> 
> It seems like the problem is stemming from:
> 
> https://github.com/pytorch/pytorch/blob/11890156e7d10d1fb72c41a38a1b94fc27004d2b/aten/src/ATen/native/SoftMax.cpp#L599
> 
> The mask type passed in is 0 but it isn't 4 dim so this then switches it to back to 2. This mask 0 though doesn't align with the assumption that it is LxL. If it expanded the (N*H, L, S) into (N,H,L,S) and was type 2 then I think it would work. But hoenstly didn't trace through all the mask mergeing shennagins.
> 
> If we are just removing it though does the masked_softmax path ever get exercised from this PR: https://github.com/pytorch/pytorch/pull/87377/files#diff-fa020f1f5fbaaade906225ece79758e020492f144e596338ad6ad9e693059657?

No, it's more of a mitigation rather really fixing the problem at the root. But from discussion with @cpuhrsch we're going to refactor transformer/mha to be based on torch compile soon. I don't have much bandwidth to fix this beyond what I've done here. If you'd like to take this over and get a complete fix, happy to hand this PR off.

**Comment by jbschlosser** [comment]
The problem is in [`merge_masks()`](https://github.com/pytorch/pytorch/blob/3b6e94cb8ceda68b81a220462d4c01bf26fb6f9a/torch/nn/modules/activation.py#L1263); it doesn't properly support a 3D `attn_mask`.

From the [nn.MHA docs](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html), we have these 6 documented cases:
* No `attn_mask`, no `src_key_padding_mask` -> `merged_mask=None`, `mask_type=None`
* No `attn_mask`, 2D `src_key_padding_mask` of size `(N, S)` -> `merged_mask=key_padding_mask`, `mask_type=1`
* 2D `attn_mask` of size `(L, S)`, no `src_key_padding_mask` -> `merged_mask=attn_mask`, `mask_type=0`
* 2D `attn_mask` of size `(L, S)`, 2D `src_key_padding_mask` of size `(N, S)` -> `merged_mask` combines expanded masks, `mask_type=2`
* 3D `attn_mask` of size `(N, L, S)`, no `src_key_padding_mask` -> `merged_mask=attn_mask`, `mask_type=0`
    * **This is wrong**; instead we should expand `attn_mask` to be 4D and pass `mask_type=2`
* 3D `attn_mask` of size `(N, L, S)`, 2D `src_key_padding_mask` of size `(N, S)` -> `merged_mask` combines expanded masks, `mask_type=2`

(NB: we're assuming self attention to enter this fast-path-specific logic at all, so `L=S`)

As demonstrated in the issue repro, the broken case is when a 3D `attn_mask` is specified and there is no `src_key_padding_mask`. A simple fix is to always expand `attn_mask` to 4D, matching input, and return `mask_type=2`.

We should always have had test cases extensively covering the above possibilities. This is the downside to adding new functionality to these APIs where the interactions among them are multiplicative.

**Comment by erichan1** [comment]
Stale and solved by other PRs.

**Pull request closed without merging**
