### PR TITLE
add ring all reduce

### PR DESCRIPTION
**Pull request by srQ-cpc**
add ring all reduce method

### CODE REVIEW

**Comment by srQ-cpc** [comment]
> Hi @srQ-cpc. Allreduce is already implemented directly. Why the need for a Python implementation?

This is the Implementation of  ring-Allreduce. It may be more efficient.

**Comment by pietern** [comment]
@srQ-cpc Have you tested it against the default implementation to check?

For the common case algorithms we should stick to a C++ implementation not only because driving it from Python adds a bit of overhead but also because it means it won't be usable for C++ only programs.

**Comment by teng-li** [comment]
I was gonna ask the same, why do we need such an implementation, we have already had all-reduce implemented

**Comment by srQ-cpc** [comment]
> For the common case algorithms we should stick to a C++ implementation not only because driving it from Python adds a bit of overhead but also because it means it won't be usable for C++ only programs.

OK. Thank you for answer.

**Comment by ezyang** [comment]
@srQ-cpc, are you interested in writing this in C++?

In any case, we can't accept this patch without tests.

**Comment by pietern** [comment]
FWIW, with a ring allreduce already being supported natively I don't think maintaining a separate implementation, either in Python or C++, makes sense.

**Pull request closed without merging**
