### PR TITLE
Add Opinfos for the Tensor overload of linspace/logspace

### PR DESCRIPTION
**Pull request by qqaatw**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #105451
* #104889
* __->__ #107958

### CODE REVIEW

**Comment by zou3519** [comment]
Probably just needs some expected failures?

**Comment by qqaatw** [comment]
> Probably just needs some expected failures?

These tests are passing in the second PR, so I think if we merge the stack all together everything should be fine? (Probably problematic if we want to revert the second PR only in the future.)

**Review by zou3519 — DISMISSED** [review]
LGTM, but the PR must stand on its own. It's possible we could revert the next PR in the stack (if it ends up breaking FC) and we would like this PR to stay in, so we should add all the necessary expected failures in this PR.

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
