### PR TITLE
assertEquals is deprecated, use assertEqual instead

### PR DESCRIPTION
**Pull request by zasdfgbnm**

### CODE REVIEW

**Review by z-a-f — APPROVED** [review]
LGTM

**Comment by zasdfgbnm** [comment]
@z-a-f Should we land this?

**Comment by ngimel** [comment]
@zasdfgbnm can you please rebase (pytorchbot is not doing it for some reason)?

**Comment by zasdfgbnm** [comment]
@ngimel Rebased

**Comment by zasdfgbnm** [comment]
Lots of unrelated failure...

**Comment by ngimel** [comment]
Yeah, master was broken at the time, and rebase is not working :-( Can you please rebase again?

**Comment by zasdfgbnm** [comment]
@ngimel rebased, hope it works this time...

**Pull request closed without merging**
