### PR TITLE
[quant][fx][graphmode] Refactor the dtype inference and handling in prepare_fx

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #68229
* #68228
* #68227
* #68042
* #67537
* __->__ #67536

Summary:
This PR:
1. Refactors the prepare_fx step, no changes to convert_fx
2. Added weight dtype and bias dtype in the node_name_to_target_dtype dictionary, which is used for checking if the configured weight/bias
dtype is supported by the backend or not (in future PR)
3. Added a node_name_to_current_dtype dictionary to record the current dtype of a node, which will make the logic of deciding whether to
insert an observer or not clearer
4. changed node_name_to_target_dtype to be a map from a node to a dictionary from user node to target dtype
node_name_to_target_dtype[node.name][node.name] will be the original output dtype for the node, node_name_to_target_dtype[arg.name][node.name] will be the dtype for the specific `use` of (arg -> node), since the dtype configuration is actually `per-use`

Example:
```
x -> conv1 (qint8) -> conv2 (quint8)
             \ ----- conv3 (fp16)

```
Previous:
```
1. dtypes
node_name_to_target_dtype[conv1] = qint8
node_name_to_target_dtype[conv2] = quint8
node_name_to_target_dtype[conv3] = fp16

2. Observers
1). we insert observer for conv1 because of https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/fx/prepare.py#L580, this part of logic does not change.
2). we insert observer for input of conv2 because of the arg(conv1) dtype is not the same as the node(conv2) dtype https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/fx/prepare.py#L378
3). similarly for input of conv3
```

Now:
```
1. Original:
node_name_to_target_dtype[conv1][conv1] will be qint8 (observed as part of the output of the conv1)
node_name_to_target_dtype[conv1][conv2] will be quint8 (observed as part of the input of conv2)
node_name_to_target_dtype[conv1][conv3] will be fp16 (observed as part of the input of conv3)

We also maintain a node_name_to_current_dtype map which records the dtype currently for each node, so initially we have
node_name_to_current_dtype[conv1] = torch.float
node_name_to_current_dtype[conv2] = torch.float
node_name_to_current_dtype[conv3] = torch.float

2. After we insert observers, we will have
node_name_to_current_dtype[conv1_observer] = torch.qint8
node_name_to_current_dtype[conv2_observer] = torch.quint8
node_name_to_current_dtype[conv3_observer] = torch.float16
(we also update the node_name_to_target_dtype map to include the observer to node map, since the argument of node became observers after we insert observers)
node_name_to_target_dtype[conv1_observer][conv2] = torch.quint8
node_name_to_target_dtype[conv1_observer][conv3] = torch.float16

3. Observers
1). for output of conv1 the logic is the same.
2). we insert observer for conv2 because the node_name_to_current_dtype[conv1_observer] did not match 
node_name_to_target_dtype[conv1_observer][conv2] 
(btw, here we'll have a node_name_to_current_dtype[conv1_observer_observer] = torch.quint8 since node_name_to_current_dtype[conv_observer] (torch.qint8) did not have the expected dtype (torch.quint8) and we need to insert one extra observer for that
3). similar logic for conv3

```

Test Plan:
Regression tests:
```
python test/test_quantization.py TestQuantizeFx
python test/test_quantization.py TestQuantizeFxOps
python test/test_quantization.py TestQuantizeFxModels
```
Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D32014997](https://our.internmc.facebook.com/intern/diff/D32014997)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32014997).

**Comment by vkuzo** [comment]
just so it's easier to read the code, any chance you could add an annotated example to the PR summary?  For example, given a graph of 

```
// prepare
x0 -> conv1 -> x1 -> conv2 -> x2
                            \
                             -> conv3 -> x3

// convert
x0 -> conv1_fp32 -> x1 -> conv2_fp16 -> x2
                                     \
                                      -> conv3_int8 -> x3

```

what are the contents of the new data structures introduced in this PR?

**Comment by vkuzo** [comment]
> changed node_name_to_target_dtype to be a map from a node to a dictionary from user node to target dtype
node_name_to_target_dtype[node.name][node.name] will be the original output dtype for the node, node_name_to_target_dtype[arg.name][node.name] will be the dtype for the specific use of (arg -> node), since the dtype configuration is actually per-use

Would it make sense to consider framing this as dtype of input of the node and dtype of output of the node instead, without considering other nodes?  This would ensure that the current node does need any knowledge of its users in order to model it properly.

**Comment by jerryzh168** [comment]
> > changed node_name_to_target_dtype to be a map from a node to a dictionary from user node to target dtype
> > node_name_to_target_dtype[node.name][node.name] will be the original output dtype for the node, node_name_to_target_dtype[arg.name][node.name] will be the dtype for the specific use of (arg -> node), since the dtype configuration is actually per-use
> 
> Would it make sense to consider framing this as dtype of input of the node and dtype of output of the node instead, without considering other nodes? This would ensure that the current node does need any knowledge of its users in order to model it properly.

This is framed in this way already I think: (node_name_to_target_dtype[node.name][node.name] is the output of previous node and node_name_to_target_dtype[arg.name][node.name] is the input of the node using the arg.

Consider the following case:

x -> conv1 (qint8) -> conv2 (quint8)
             \ ----- conv3 (fp16)
node_name_to_target_dtype[conv1][conv1] will be qint8 (observed as part of the output of the conv1)

node_name_to_target_dtype[conv1][conv2] will be quint8 (observed as part of the input of conv2)
node_name_to_target_dtype[conv1][conv3] will be fp16 (observed as part of the input of conv3)

**Comment by jerryzh168** [comment]
@vkuzo please let me know if the example makes sense

**Comment by vkuzo** [comment]
Thoughts about this?

```
# original
node_name_to_target_dtype[conv1][conv1] will be qint8 (observed as part of the output of the conv1)
node_name_to_target_dtype[conv1][conv2] will be quint8 (observed as part of the input of conv2)
node_name_to_target_dtype[conv1][conv3] will be fp16 (observed as part of the input of conv3)

# proposed
node_name_to_dtypes = {
  'conv1': {
    'input': torch.qint8,
    'output': torch.qint8,
  },
  'conv2': {
    'input': torch.qint8,   # from conv1
    'output': torch.quint8,
  },
  'conv3': {
    'input': torch.qint8,  # from conv1
    'output': torch.float16,
  }
}
```

It's the same information, except modeled with "what is the dtypes of input and output of current node" instead of "what are the dtypes of uses of the current node".

**Comment by jerryzh168** [comment]
> Thoughts about this?
> 
> ```
> # original
> node_name_to_target_dtype[conv1][conv1] will be qint8 (observed as part of the output of the conv1)
> node_name_to_target_dtype[conv1][conv2] will be quint8 (observed as part of the input of conv2)
> node_name_to_target_dtype[conv1][conv3] will be fp16 (observed as part of the input of conv3)
> 
> # proposed
> node_name_to_dtypes = {
>   'conv1': {
>     'input': torch.qint8,
>     'output': torch.qint8,
>   },
>   'conv2': {
>     'input': torch.qint8,   # from conv1
>     'output': torch.quint8,
>   },
>   'conv3': {
>     'input': torch.qint8,  # from conv1
>     'output': torch.float16,
>   }
> }
> ```
> 
> It's the same information, except modeled with "what is the dtypes of input and output of current node" instead of "what are the dtypes of uses of the current node".

oh OK, yeah that sounds good

**Comment by vkuzo** [comment]
> I feel how a node is quantized is related to how the node is used

It is possible to have an invariant that the current subgraph's quantization strategy is not dependent on its future uses.  This enables us to build the modified graph incrementally node by node, without looking ahead.

For example,

```
# original graph
x0 -> conv1 -> conv2 -> x2

# desired quantized graph
x0 -> conv1_fp32 -> fp32_to_int8 -> conv2_int8 -> x2

# prepared graph
x0 -> conv1 -> obs1 -> conv2 -> obs2 -> x2
```

In the example above, we have two choices on how to treat obs1: it's observing the output `conv1` and observing the input of `conv2`.  Both of these statements are true, but if we choose to think about it as "observing the input of conv2", that allows us to make the assumption above that a single subgraph's quantization strategy is not dependent on its future uses.  https://github.com/pytorch/pytorch/pull/57519 is a real world example of how choosing to think about it the second way can simplify things.

I would highly recommend that we try to keep this assumption of building up the quantized graph node by node without looking ahead whenever possible.

**Comment by jerryzh168** [comment]
> > I feel how a node is quantized is related to how the node is used
> 
> It is possible to have an invariant that the current subgraph's quantization strategy is not dependent on its future uses. This enables us to build the modified graph incrementally node by node, without looking ahead.
> 
> For example,
> 
> ```
> # original graph
> x0 -> conv1 -> conv2 -> x2
> 
> # desired quantized graph
> x0 -> conv1_fp32 -> fp32_to_int8 -> conv2_int8 -> x2
> 
> # prepared graph
> x0 -> conv1 -> obs1 -> conv2 -> obs2 -> x2
> ```
> 
> In the example above, we have two choices on how to treat obs1: it's observing the output `conv1` and observing the input of `conv2`. Both of these statements are true, but if we choose to think about it as "observing the input of conv2", that allows us to make the assumption above that a single subgraph's quantization strategy is not dependent on its future uses. #57519 is a real world example of how choosing to think about it the second way can simplify things.
> 
> I would highly recommend that we try to keep this assumption of building up the quantized graph node by node without looking ahead whenever possible.

I think we are thinking of it as "observing the input of conv2", we query node_name_to_target_dtype[arg.name][node.name] while inserting input observer for the argument `arg` of the `node`, can you clarify the concern here?

**Comment by vkuzo** [comment]
> I think we are thinking of it as "observing the input of conv2", we query node_name_to_target_dtype[arg.name][node.name] while inserting input observer for the argument arg of the node, can you clarify the concern here?

I see, I think it's confusing (to me, maybe not to others) because the first key is the previous arg and the second key is the current node, I think if it was in reverse order it could map to the mental model I'm hoping for better.

**Comment by vkuzo** [comment]
how about

```
node_name_to_dtypes: {
  'input_args': [dtype1, ..., dtypen],
  'input_kwargs': {key1: dtype1, ...}
  'outputs': arbitrary_nested_structure_of_dtypes,  # matches output structure
}
```

**Comment by vkuzo** [comment]
> I think we are thinking of it as "observing the input of conv2", we query node_name_to_target_dtype[arg.name][node.name] while inserting input observer for the argument arg of the node, can you clarify the concern here?

Thinking about it a bit more, I think my confusion stems that the first key here is always the node being observed by the observer, so if I look at the contents of this data structure this looks like "how are all uses of the current node observed", so this makes it easy to think about thinks in terms of "current node and its uses" and not "current node and its inputs and outputs".

**Comment by jerryzh168** [comment]
> how about
> 
> ```
> node_name_to_dtypes: {
>   'input_args': [dtype1, ..., dtypen],
>   'input_kwargs': {key1: dtype1, ...}
>   'outputs': arbitrary_nested_structure_of_dtypes,  # matches output structure
> }
> ```

I would prefer not to worry about the structure, both input_args and kwargs can have complicated structures (not just plain Tensors) I think.

Does reversing node and arg sound good?

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32014997).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32014997).

**Comment by jerryzh168** [comment]
deprecated by https://github.com/pytorch/pytorch/pull/68317

**Pull request closed without merging**
