### PR TITLE
Add python and C++ support for LPPool3d

### LINKED ISSUE #114114: Why there is no nn.LPPool3d?
### 🚀 The feature, motivation and pitch

Other pooling layers all have 3d pool, except for `nn.LPPool`?
I find it when writing a neural network for 3d data, don't know why?

### Alternatives

_No response_

### Additional context

_No response_

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### PR DESCRIPTION
**Pull request by wang-jinbo**
Add python and C++ support for LPPool3d to Fixes #114114

### CODE REVIEW

**Review by jbschlosser — COMMENTED** [review]
Thanks for the contribution! It's looking good, and I see you even added the C++ API side of things as well :)

I approved the checks to run so we'll see if the tests pass. I think we'll want a few more housekeeping updates:
* Register the new module into `__all__` in torch/nn/modules/pooling.py
* Python tests: add a `ModuleInfo` entry in `torch/testing/_internal/common_modules.py` and ensure tests in `test/test_modules.py` pass
* Ensure the module shows up in the doc pages (`docs/source/nn.rst`)
* Probably other stuff I'm forgetting but I imagine failing tests will catch. I'm going to pass this off to @mikaylagawarecki to finish up the review

Thanks again!

**Comment by Wongboo** [comment]
I've amended the commit to add more fix about doc and test.

**Comment by Wongboo** [comment]
try to fix warning of `lintrunner`.

**Comment by Wongboo** [comment]
fix `testing_overrides`

**Comment by Wongboo** [comment]
fix `test_modules` and `test_module_init`

**Comment by Wongboo** [comment]
Is there something about implementation of `LPPool2d` in C++?
According to documentation, [C++](https://pytorch.org/cppdocs/api/classtorch_1_1nn_1_1_l_p_pool2d.html) points to [python](https://pytorch.org/docs/master/generated/torch.nn.LPPool2d.html#torch.nn.LPPool2d) the input and output of `LPPool2d`'s `operator()` should be 4D shape.
But the [test](https://github.com/pytorch/pytorch/blob/8cfc95368f7de569f03844e7c89561c0d45d434b/test/cpp/api/modules.cpp#L530) is 3D shape, but `AvgPool2d` guarantees 3D and 4D shape, so the test passes.

**Comment by Wongboo** [comment]
I'm sorry I have to fix something.

**Review by mikaylagawarecki — APPROVED** [review]
Looks good, thank you for your meticulous work adding this! Please fix the small nits

**Comment by Wongboo** [comment]
> Looks good, thank you for your meticulous work adding this! Please fix the small nits

Thanks for your suggestions!👍 I amend commits based your suggestions.

**Comment by Wongboo** [comment]
You are right, unlike `AvgPool2d`, `LPPool3d`'s backend `AvgPool3d` doesn't work for MPS at all.
I amend the commit to fix.

**Pull request closed without merging**
