### PR TITLE
Back out "[kineto] add SOFT_ASSERT when logging metdata"

### PR DESCRIPTION
**Pull request by christ1ne**
Summary:
Original commit changeset: 1089c4d95c54

Original Phabricator Diff: D44513152

Test Plan: signals

Reviewed By: eeggl

Differential Revision: D44804013

### CODE REVIEW

**Comment by christ1ne** [comment]
signed CLA with meta plaforms

**Review by weiwangmeta — APPROVED** [review]
Approve to unblock

**Pull request closed without merging**
