### PR TITLE
[dynamo] Refactor TorchInGraphFunctionVariable for compile time

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #121784
* __->__ #121616
* #121615

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by oulgen — APPROVED** [review]

**Comment by oulgen** [comment]
@jansel you might have had a bad merge since your PR now contains a bunch of code that i assume isn't meant to be on the PR

**Comment by jansel** [comment]
Thanks I split that out into another PR.  Looks like the fix for graph breaking on invalid args fixes a lot of dynamo-mode tests.

**Pull request closed without merging**
