### PR TITLE
[MPS] Fix std/var cache issue

### LINKED ISSUE #80499: std() is incorrect on "mps" backend
### 🐛 Describe the bug

I was wondering why normalization was different on the mps backend. It turns out that `std()` produces different results:
```python
x = torch.eye(2)
print(x.std(), x.to("mps").std())
# tensor(0.5774) tensor(0.5000, device='mps:0')
```

I also tried `x.to("mps").std(unbiased=False)` but it produced the same result for the mps backend.

### Versions

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.8.9 (default, Apr 13 2022, 08:48:06)  [Clang 13.1.6 (clang-1316.0.21.2.5)] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.0
[pip3] numpydoc==1.4.0
[pip3] pytorch-lightning==1.5.10
[pip3] torch==1.13.0.dev20220628
[pip3] torchaudio==0.14.0.dev20220603
[pip3] torchmetrics==0.7.2
[pip3] torchvision==0.14.0.dev20220628
[conda] Could not collect

cc @kulinseth @albanD

### PR DESCRIPTION
**Pull request by qqaatw**
Use `getTensorsStringKey` which has tensor shape info added as part of the key to prevent cache lookup issue when the shape of input tensor is changed.

Fixes #80499

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
Please add short explanation why do you think this fixes the problem.

Also, to prevent further regression it would be good to add the test

**Review by kulinseth — COMMENTED** [review]
Agree with @malfet , please add the test-case in `test_mps.py` to make sure it doesn't regress. Overall the change looks good.

**Comment by qqaatw** [comment]
The tests and short explanation have been added.

**Review by kulinseth — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
