### PR TITLE
[CI] Add Compiled DDP / Compiled FSDP2 / compute-comm reordering tests to test_inductor_distributed

### PR DESCRIPTION
**Pull request by yf225**
`test_replicate_with_compiler.py` and `test_fully_shard_compile.py` requires bf16, so needs to be run within test_inductor_distributed job (which uses A10G (SM80) and has bf16 support).

This allows us to migrate distributed jobs to T4 machines in https://github.com/pytorch/pytorch/pull/137161, as the compiled distributed jobs are the only blocking ones now.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #137763
* #135273
* #137161
* __->__ #138178

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by xmfan — APPROVED** [review]

**Review by kwen2501 — COMMENTED** [review]
LGTM

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change, but the new tests are failing inductor distributed jobs' -c nosignal

distributed/_composable/test_replicate_with_compiler.py::ReplicateTest::test_compile_backward_only [GH job link](https://github.com/pytorch/pytorch/actions/runs/11383464418/job/31671181653) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/20af56d4359c3f5fed2e8f94e111a8502f2ebeb3)

Let me add `ciflow/inductor` to the PR to get that signals

**Comment by yf225** [comment]
Depends on https://github.com/pytorch/pytorch/pull/138174

**Review by fduwjj — APPROVED** [review]

**Review by fegin — APPROVED** [review]

**Review by kwen2501 — APPROVED** [review]

**Comment by yf225** [comment]
I will squash this PR into https://github.com/pytorch/pytorch/pull/138174 to make it easier to land

**Pull request closed without merging**
