### PR TITLE
Inductor cpp wrapper: support LinearUnary

### PR DESCRIPTION
**Pull request by chunyuan-w**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #97655

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your PR, but it looks like the change causes a regression on CPU test time https://hud.pytorch.org/pytorch/pytorch/commit/d03003ab8e0e00ff4c9e2b80065cf90a8fcef92d  (inductor/test_cpp_wrapper.py)' -c weird

For example, `inductor/test_cpp_wrapper.py` from `linux-bionic-py3.8-clang9 / test (default, 1, 3, linux.2xlarge)` in https://hud.pytorch.org/pr/97655 took 3070.14s (0:51:10) to finish ([log](https://ossci-raw-job-status.s3.amazonaws.com/log/12416619924)) while it used to take less than a minute before

**Comment by chunyuan-w** [comment]
@huydhn I added `@slow()` to it since it is indeed a slow one. The CI could pass now.

**Comment by huydhn** [comment]
> @huydhn I added `@slow()` to it since it is indeed a slow one. The CI could pass now.

Thank you for the fix.  I quickly check one CPU job `[linux-bionic-py3.8-clang9 / test (default, 1, 3, linux.2xlarge)](https://github.com/pytorch/pytorch/actions/runs/4597105301/jobs/8119722785)` and the number looks good to me `17 passed, 1 skipped in 311.09s (0:05:11)`.  The slow one was skipped correctly.  Please feel free to merge the change once you're ready.

**Pull request closed without merging**
