### PR TITLE
pytest - check for build env

### PR DESCRIPTION
**Pull request by clee2000**
### Description
quick fix for https://github.com/pytorch/pytorch/pull/79898#discussion_r932847642

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Comment by huydhn** [comment]
I'm trying to see if there is an accept2ship label to test with this one. It's probably not here yet :)

**Comment by clee2000** [comment]
> I'm trying to see if there is an accept2ship label to test with this one (like [pytorch/pytorch-canary#131](https://github.com/pytorch/pytorch-canary/pull/131)). It's probably not here yet :)

I think its out, but you might have to add the label before approving

**Review by malfet — CHANGES_REQUESTED** [review]
It wouldn't fix all the issue reported in https://github.com/pytorch/pytorch/issues/82492

And conventional way of doing is is just running `os.environ.get("FOO")`

**Comment by clee2000** [comment]
closing this in favor of https://github.com/pytorch/pytorch/pull/82495

**Pull request closed without merging**
