### PR TITLE
test_memory_format test now passes on rocm

### PR DESCRIPTION
**Pull request by pragupta**
cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by pruthvistony — APPROVED** [review]
Waiting for CI to successfully execute the enabled UT.

**Review by albanD — APPROVED** [review]
SGTM if CI is happy!

**Comment by jithunnair-amd** [comment]
@pragupta Please post a snippet of the passing unit test from the CI logs for ROCm once you have them. Thanks!

**Comment by pruthvistony** [comment]
> @pragupta Please post a snippet of the passing unit test from the CI logs for ROCm once you have them. Thanks!

The UT is disabled by - https://github.com/pytorch/pytorch/issues/95172.
So merging this PR as CI is green and next close above issue and monitor the CI.

**Pull request closed without merging**
