### PR TITLE
Simplify the Registration of Hooks for PrivateUse1

### PR DESCRIPTION
**Pull request by fffrog**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #134999

### CODE REVIEW

**Review by cyyever — APPROVED** [review]

**Review by shink — APPROVED** [review]

**Comment by FFFrog** [comment]
Hey! Can @albanD help to review this changes?

As far as I know, `XXXHooksArgs` has no meaning in the Hook Registry, whether for CUDA or other backends, because `XXXHooksArgs` of `XXXHooks` is passed in statically.

After refactoring, it can greatly increase the ease of use; the new backend only needs to inherit `PrivateUse1HooksInterface` to implement the custom class `FooHooks`, and then call `REGISTER_PRIVATEUSE1_HOOKS(FooHooks)` to register.

If the new backend based on PrivateUse1 wants to implement the function of `PrivateUse1HooksArgs`, it can be statically initialized directly in the `XXXHooks` class.

**Pull request closed without merging**
