### PR TITLE
[inductor] Add explicit fmas in variance formulas

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #122915
* #115435
* __->__ #123269

The `dx = x - mean` calculation in the variance is a classic
big - big = small scenario where precision is at a premium.

Calculating it with an fma as `fma(sum, 1/N, -x)` results in 1 fewer rounding
and so we can expect greater accuracy overall.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by lezcano** [comment]
I'm a bit worried that the user does not have access to these. I wonder whether the cure is worse than the disease...

**Comment by peterbell10** [comment]
Would you prefer there to be a `torch.fma` and `aten.fma` which is a core ATen op?

**Comment by lezcano** [comment]
What I wonder is whether it makes more sense to have FMA on by default and then have a `torch.nofma` op for when it may be an issue. That is, performant and accurate by default unless asked otherwise.

**Comment by peterbell10** [comment]
> What I wonder is whether it makes more sense to have FMA on by default and then have a torch.nofma op for when it may be an issue. That is, performant and accurate by default unless asked otherwise.

This isn't feasible. The original issue with division before softmax doesn't even include a multiplication! It's only inside the ptx assembler that the dvision is decomposed into multiple ops including a multiply which can then be fused with another op.

**Comment by peterbell10** [comment]
One thing worth mentioning is that this manual `fma` insertion actually makes inductor closer to eager.  Eager kernels are compiled generating `fma` instructions, but only for ops within a given kernel. On the other hand when inductor fuses and recalculates values in larger kernels it introduces new opportunities for `fma` generation and thus greater numerical divergence from eager.

Another idea might be to insert `fma` ops as joint graph level pass. This would mean we get the accuracy improvements without the need to manually add `fma` to decompositions. By changing it at the aten graph level we should ensure that all fusions will take the same numerical route to get to the result.

**Review by lezcano — APPROVED** [review]

**Pull request closed without merging**
