### PR TITLE
TorchDynamo: always convert tensor to fake tensor at fake_mode path for ShapeProp

### PR DESCRIPTION
**Pull request by XiaobingSuper**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #90685

This PR will fix https://github.com/pytorch/torchdynamo/issues/1978, for HF models, there is always report a ShapeProp error, the root cause is that we use fake tensor mode to do the ShapeProp, but for **torch.ones**, it always gets a none fake tensor and introduces an operation with non-fake tensors with fake tensors.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by XiaobingSuper** [comment]
I converted this PR to a draft, although this PR can improve the HF models' pass rate, some models still failed(BartForCausalLM) which have the following error:

```
/home/xiaobing/vision/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension:
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/home/xiaobing/pytorch-offical/torch/fx/passes/shape_prop.py", line 143, in run_node
    result = super().run_node(n)
  File "/home/xiaobing/pytorch-offical/torch/fx/interpreter.py", line 185, in run_node
    return getattr(self, n.op)(n.target, new_args, kwargs)
  File "/home/xiaobing/pytorch-offical/torch/fx/interpreter.py", line 257, in call_function
    return target(*args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_inductor/overrides.py", line 37, in __torch_function__
    return func(*args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_subclasses/fake_tensor.py", line 581, in __torch_dispatch__
    return func(*args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_ops.py", line 285, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/xiaobing/pytorch-offical/torch/_subclasses/fake_tensor.py", line 848, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/xiaobing/pytorch-offical/torch/_subclasses/fake_tensor.py", line 351, in data_dep
    raise DataDependentOutputException(func)
torch._subclasses.fake_tensor.DataDependentOutputException: aten._local_scalar_dense.default
```

**Comment by ezyang** [comment]
@jansel can we just stop using ShapeProp in inductor, and rely on make_fx's shape annotations? My brain hurts trying to figure out how to correctly implement ShapeProp in gneeral.

**Comment by XiaobingSuper** [comment]
@ezyang , the current implementation works now, and all HF models can pass for CPU path(```python benchmarks/dynamo/huggingface.py --ci --accuracy --device cpu --inductor --float32```), please help see whether the current implementation is ok for you or not. Thanks!

**Comment by ezyang** [comment]
Ok new change is better, willing to do this. I think my main Q is what if ShapeProp is called in a context where there is already fake tensor mode. @samdow if ci passes we should land this for now, but it may need more tweaking

**Review by ezyang — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Comment by ngimel** [comment]
> @jansel can we just stop using ShapeProp in inductor, and rely on make_fx's shape annotations? My brain hurts trying to figure out how to correctly implement ShapeProp in gneeral.

Yes we should, ShapeProp is not used in inductor in general, it's only used in an ad-hoc fuse_fx override, that can and should be written better.

**Comment by jansel** [comment]
Agreed.

**Pull request closed without merging**
