### PR TITLE
ROCM: Reenable test_eig_with_eigvec_cuda_float64

### PR DESCRIPTION
**Pull request by arindamroy-eng**
After PR #56279 was merged, disabling gradgradcheck, the test is not flaky now. Hence re-enabling the test.

### CODE REVIEW

**Comment by arindamroy-eng** [comment]
@jeffdaily

**Comment by ngimel** [comment]
ROCM tests still failed with this PR.

**Comment by jeffdaily** [comment]
@arindamroy-eng looks like the test you re-enabled is still busted.

**Review by malfet — APPROVED** [review]

**Review by malfet — CHANGES_REQUESTED** [review]
Sorry, I should have checked the log. Please fix the test first.

**Comment by arindamroy-eng** [comment]
Sorry for the failure. Dropping the PR for now. Will enable it once the next version of ROCM is released for CI nodes.

**Pull request closed without merging**
