### PR TITLE
[17/N] Add _reduce_scatter_base custom op with CPU/CUDA implementation

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #88330 Allow Process Group to support multiple backends and move PG specfic implementations to backend class
* #87088 Remove ProcessGroupRoundRobin
* #89318 [19/N] Add monitored_barrier custom op with CPU implementation
* #89317 [18/N] Add allgather_coalesced custom op with CPU/CUDA implementations
* **#88903 [17/N] Add _reduce_scatter_base custom op with CPU/CUDA implementation**

### Context
https://github.com/pytorch/pytorch/issues/86225

Differential Revision: [D41415325](https://our.internmc.facebook.com/intern/diff/D41415325)

### CODE REVIEW

**Review by kwen2501 — APPROVED** [review]
LGTM! Thanks!

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41415325).

**Pull request closed without merging**
