### PR TITLE
[PyTorch] Disable transformer/MHA fast path when autocast is enabled

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #76934

We need predictable Tensor dtypes because we call data_ptr. Autocast messes with this

Differential Revision: [D36190109](https://our.internmc.facebook.com/intern/diff/D36190109/)

### CODE REVIEW

**Comment by swolchok** [comment]
argh, `torch.is_autocast_enabled` does not work with JIT, how is that even possible

**Review by cpuhrsch — APPROVED** [review]

**Comment by ngimel** [comment]
cc @jjsjann123 for jit autocast

**Comment by swolchok** [comment]
> query that one for jit instead.

am I supposed to branch on some sort of torch.is_jit thing? I'm missing a piece I think

**Comment by swolchok** [comment]
> is_scripting

that's not going to help. I need to make the exact same check (is autocast enabled) regardless of whether the JIT is involved or not. need the JIT folks to fix this, and ideally need to not have to do extra stuff to make perfectly normal functions work in TorchScript.

**Pull request closed without merging**
