### PR TITLE
Ported nn.functional functions to use torch calls instead of ref calls

### PR DESCRIPTION
**Pull request by Chillee**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #78994
* #78991
* #78984
* __->__ #78978

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
But I know Mike likes using refs so let's make sure he approves before we get into a tug-of-war

**Comment by Chillee** [comment]
@ezyang I think Mike wrote his opinion here, which I think this follows: https://github.com/pytorch/pytorch/pull/78689#discussion_r889159026

**Comment by ezyang** [comment]
ship ship ship

**Pull request closed without merging**
