### PR TITLE
Refactor lift_subgraph_as_module as a fx.passes.util function

### PR DESCRIPTION
**Pull request by SherlockNoMad**
lift_subgraph_as_module can be shared between fuser_utils.py and spliter_utils.py

### CODE REVIEW

**Review by jjsjann123 — APPROVED** [review]
LGTM

**Review by 842974287 — COMMENTED** [review]
Code looks good! Maybe add some unit tests for those functions?

**Comment by SherlockNoMad** [comment]
> Code looks good! Maybe add some unit tests for those functions?

Thanks for reviewing this! This is covered by test_fuser_util in test_fx_passes.py.

**Review by 842974287 — APPROVED** [review]

**Pull request closed without merging**
