### PR TITLE
Quote arguments only when possible

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by ezyang** [comment]
Mmmm, this looks really dodgy. Does `_nt_quote_args` just not work?

**Comment by peterjc123** [comment]
@ezyang It works, but on some systems, the string may be quoted before. So doing this will lead to a second quote, which causes build failures.

**Comment by ezyang** [comment]
...ewwww... this reminds me of the bad old PHP days, when someone decided it would be a good idea to `addslashes` to all `_GET` parameters, and then everyone was perpetually confused as to whether or not their variables had backslashes or not.

I'll accept this patch assuming (1) it says what it does and (2) explains what specific situation you've noticed where it is double escaped.

**Comment by peterjc123** [comment]
Can we merge this please?

**Review by ezyang — APPROVED** [review]

**Pull request merged**
