### PR TITLE
Fix docs for pointwise ops (#845)

### PR DESCRIPTION
**Pull request by alykhantejani**
Removed type of `float` from the docs and replaced with `Number` which should be same type as input tensors (issue #845 )

### CODE REVIEW

**Comment by apaszke** [comment]
Actually they don't have to be of the same type. We accept ints as floats, just not the other way. Not sure how to write that :/

**Comment by alykhantejani** [comment]
hmm, ok. Yeah it's a bit hard to write this concisely. Maybe "Real or Integral depending on type of input" or something along those lines?

**Comment by soumith** [comment]
hmmm, how about just: `(Number, optional)` and leave it at that...

**Comment by alykhantejani** [comment]
Yeah, maybe that's best. @apaszke Let me know if that's ok with you and I'll update the PR

**Comment by apaszke** [comment]
I think that's ok. Can you add a note at the top saying what types of numbers are acceptable for different tensor types? If you can think of any concise way of referring to it, you could also add it to the arg descriptions.

**Comment by alykhantejani** [comment]
@apaszke is this sufficient for the docs "Args `beta` and `alpha` must be real numbers for FloatTensor and DoubleTensor, and integers for other tensor types" (obviously switching `alpha` and `beta` out)

**Comment by apaszke** [comment]
Yeah sure! Sounds good.

**Comment by alykhantejani** [comment]
Changes have now been made

**Comment by soumith** [comment]
Thanks!

**Pull request merged**
