### PR TITLE
[CI][ROCm] always stop all docker containers

### PR DESCRIPTION
**Pull request by jeffdaily**
We observed multiple running docker containers on several ROCm self-hosted runners. This commit ensures all containers are stopped prior to starting the tests. This commit also fixes setup/teardown differences between various ROCm workflows.

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!

**Review by malfet — APPROVED** [review]
Looks good to me, but please consider the followup PR that moves added actions to https://github.com/pytorch/test-infra/tree/main/.github/actions (so that they could eventually be used by torchvision and others.

**Comment by jeffdaily** [comment]
> Looks good to me, but please consider the followup PR that moves added actions to https://github.com/pytorch/test-infra/tree/main/.github/actions (so that they could eventually be used by torchvision and others.

Can this be one single follow-up PR to the test-infra repo that syncs up all rocm actions?

**Review by ZainRizvi — COMMENTED** [review]
How does this deal with the scenario where other workflows have containers running on the same host? Or do we no longer run multiple jobs in parallel on a single runner now?

**Pull request closed without merging**
