### PR TITLE
[SparseCompressed] support csc layout for add sparse/dense.

### PR DESCRIPTION
**Pull request by amjames**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #115433
* #115432

`add` when passed one sparse and one dense argument  will error if the
sparse argument does not have  csr layout. This PR modifies the
underlying algorithm to be generic on the compressed dimension handling
both csr and csc. The functions are renamed to use the
`sparse_compressed` qualifier rather than `sparse_csr`

Fixes: #114807

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @bhosmer @jcaip

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]
Awesome!

**Review by pearu — APPROVED** [review]
LGTM!

**Pull request closed without merging**
