### PR TITLE
Revert "Revert D32498572: allow external backend codegen to be used without autograd kernels"

### PR DESCRIPTION
**Pull request by bdhirsh**
Reland of https://github.com/pytorch/pytorch/pull/68529. I confirmed locally that the xla codegen workflow builds successfully. It also maintains @alanwaketan 's patch here for LTC: https://github.com/pytorch/pytorch/pull/68529#issuecomment-994176441

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #69951
* #69950
* __->__ #69949

This reverts commit 33363cea64fd4be16975c32cf57e9eb123af371d.

Differential Revision: [D33113544](https://our.internmc.facebook.com/intern/diff/D33113544)

### CODE REVIEW

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33113544).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33113544).

**Comment by bdhirsh** [comment]
@wconstab @alanwaketan would one of you mind re-approving?

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33113544).

**Review by alanwaketan — APPROVED** [review]
LGTM. Thanks.

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33113544).

**Pull request closed without merging**
