### PR TITLE
Use Vectorized Half for eager and compile

### PR DESCRIPTION
**Pull request by malfet**
Using implementation added by https://github.com/pytorch/pytorch/pull/122918

Adapt `convert_half_float`/`convert_half_float` to work when better APIs are available
Fix `Vectorized<Half>::reciprocal()` and `::rsqrt()` implementation do use proper divisions rather than `vrecpeq_f16` which computes the estimate, rather than true division. Please note that this pattern already present in `Vectorized<Float>` for NEON, see:
https://github.com/pytorch/pytorch/blob/05289a278c3eaca271061649982f38c435b50674/aten/src/ATen/cpu/vec/vec256/vec256_float_neon.h#L618-L622

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by mikekgfb — APPROVED** [review]
LGTM

**Comment by malfet** [comment]
Though performance gains are very minimal with torch.compile: 1.59 token/sec before vs 1.61 tokens/sec after (unless I've made mistake in rebuilding it somewhere)

**Pull request closed without merging**
