### PR TITLE
Add `GRAPH_UPDATE` for `x.size()` in Peephole Optimize

### PR DESCRIPTION
**Pull request by standbyme**
Fix #31820

### CODE REVIEW

**Comment by yf225** [comment]
@suo Do you know who would be the best person to review this PR? Thanks!

**Comment by standbyme** [comment]
@yf225 The orginal PR(#31820) is reviewed by @Krovatkin : )

**Review by suo — APPROVED** [review]
already stamped by @Krovatkin  :)

**Pull request closed without merging**
