### PR TITLE
[primTorch] Add docstring and promotion for `l1_loss` ref

### PR DESCRIPTION
**Pull request by nkaretnikov**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #83805
* #83804
* __->__ #83803

cc @ezyang @mruberry @ngimel @Lezcano @peterbell10

### CODE REVIEW

**Comment by nkaretnikov** [comment]
the python frontend code has a warning when `target` and `input` are not of the same size. not sure if those are necessary in refs at all, i don't see them used anywhere so decided not to add it

**Comment by nkaretnikov** [comment]
@Lezcano ptal

**Review by lezcano — APPROVED** [review]
Thank you!

**Comment by nkaretnikov** [comment]
@ngimel ptal

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
