### PR TITLE
Refactoring named tensor handling

### PR DESCRIPTION
**Pull request by narang99**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #67342
* #66193
* __->__ #65912

Description:
- Before this named tensor handling in copy_ was done by putting the handler in every backend function of the kernel
- Use dispatcher now

NOTE: would add the direct dispatch link (take out sparse_copy_wrapper_)
in the next iteration once this passes the CI

Differential Revision: [D31960014](https://our.internmc.facebook.com/intern/diff/D31960014)

### CODE REVIEW

**Comment by ezyang** [comment]
RIP, we broke named tensor. @narang99 are you able to debug?

**Comment by narang99** [comment]
> RIP, we broke named tensor. @narang99 are you able to its stra

> RIP, we broke named tensor. @narang99 are you able to debug?

😂😂😂😂
I havent started debugging yet. Will work on it tomorrow.

**Comment by narang99** [comment]
@ezyang 
Seems like `Named` has lesser priority than `CompositeExplicitAutograd`, its never taking the `copy_named_` path and going directly to `copy_` even for named tensors.

I also confirmed that the dispatch key sets inside the `copy_` function do contain the `Named` Dispatch key in case named tensors are passed, so thats also out of question.

**Comment by ezyang** [comment]
Use `torch.C._dispatch_dump("aten::copy_")` to take a look at the dispatch table, Named is a specific dispatch key and supposed to have higher precedence than any composite, so I am a little skeptical about the proferred explanation here.

I see the test is failing in a lot of CI configs, so it is more likely to be a local problem if you can't reproduce.

**Comment by narang99** [comment]
Yea you are right, the entry is not in the dispatch table itself.   
Is this file:  `/Users/orange/codes/open_source/pytorch/aten/src/ATen/core/NamedRegistrations.cpp` not generated using CodeGen? Then I'm guessing a manual entry is required here

**Comment by narang99** [comment]
Yes you are right, the named tensor function is not registered in the table itself
The table
```
name: aten::copy_
schema: aten::copy_(Tensor(a!) self, Tensor src, bool non_blocking=False) -> (Tensor(a!))
debug: registered at /Users/orange/codes/open_source/pytorch/build/aten/src/ATen/RegisterSchema.cpp:20
alias analysis kind: FROM_SCHEMA
MkldnnCPU: registered at /Users/orange/codes/open_source/pytorch/build/aten/src/ATen/RegisterMkldnnCPU.cpp:612 :: (Tensor _0, Tensor _1, bool _2) -> (Tensor _0) [ boxed unboxed ]
SparseCPU: registered at /Users/orange/codes/open_source/pytorch/build/aten/src/ATen/RegisterSparseCPU.cpp:986 :: (Tensor _0, Tensor _1, bool _2) -> (Tensor _0) [ boxed unboxed ]
Named: registered at /Users/orange/codes/open_source/pytorch/aten/src/ATen/core/NamedRegistrations.cpp:11 :: (none) [ fallthrough boxed ]
Conjugate: registered at /Users/orange/codes/open_source/pytorch/aten/src/ATen/ConjugateFallback.cpp:31 :: (none) [ fallthrough boxed ]
Negative: registered at /Users/orange/codes/open_source/pytorch/aten/src/ATen/native/NegateFallback.cpp:31 :: (none) [ fallthrough boxed ]
ADInplaceOrView: registered at /Users/orange/codes/open_source/pytorch/torch/csrc/autograd/VariableTypeManual.cpp:315 :: (Tensor _0, Tensor _1, bool _2) -> (Tensor _0) [ boxed unboxed ]
Tracer: registered at /Users/orange/codes/open_source/pytorch/torch/csrc/autograd/TraceTypeManual.cpp:129 :: (Tensor _0, Tensor _1, bool _2) -> (Tensor _0) [ boxed unboxed ]
Autograd[alias]: registered at /Users/orange/codes/open_source/pytorch/torch/csrc/autograd/VariableTypeManual.cpp:252 :: (Tensor _0, Tensor _1, bool _2) -> (Tensor _0) [ boxed unboxed ]
CompositeExplicitAutograd[alias]: registered at /Users/orange/codes/open_source/pytorch/build/aten/src/ATen/RegisterCompositeExplicitAutograd.cpp:12906 :: (Tensor _0, Tensor _1, bool _2) -> (Tensor _0) [ boxed unboxed ]
```

I'm guessing I need to make a manual entry inside `NamedRegistrations.cpp`.  I've done that but I don't know if it is the correct way to do so, so please check that

**Review by ezyang — APPROVED** [review]
cool story

**Pull request closed without merging**
