### PR TITLE
[TensorExpr] Clean-up logic for copying input tensors and remove some dead code.

### PR DESCRIPTION
**Pull request by ZolotukhinM**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #70475
* #70375
* #70374
* #66847
* __->__ #70535
* #66515
* #66514

This also fixes handling of inputs that happen to be outputs (they
require copy).

Differential Revision: [D33399116](https://our.internmc.facebook.com/intern/diff/D33399116)

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
Can we just make it an invariant that we don't return input tensors instead ? Either as a transformation in the beginning of compile or as an assert. It doesn't happen organically in fuser and the trimming pass could updated to avoid this. 

This will also conflict with my pr https://github.com/pytorch/pytorch/pull/70464

**Comment by ZolotukhinM** [comment]
> Can we just make it an invariant that we don't return input tensors instead ? Either as a transformation in the beginning of compile or as an assert. It doesn't happen organically in fuser and the trimming pass could updated to avoid this.

Honestly I don't see a strong technical reason to prohibit such cases and supporting them would make the system more consistent. Graphs where inputs are returned as outputs are perfectly valid TS IR and not very difficult to support (as shown in this PR), so I think we should overcome one-off technical inconvenience of adding this. The trimming pass just exposed this inconsistency, but even without it I would vote for supporting this.

Apart from it, I think the code there has become spaghetti already and needs some refactoring anyway :) Adding a copy for inputs tensors is just a simple if in the beginning.

**Comment by ZolotukhinM** [comment]
Also, regarding this:

>  trimming pass could updated to avoid this

That would mean that we're getting bigger graphs (since we will have at least one node in the graph for each input) than we would get if inputs can directly be used as outputs.

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33399116).

**Comment by eellison** [comment]
We don't have any other instances where we return an alias of an input, I think that adding here an inconsistency. Perfectly valid TS IR != have to error. In the compile phase the graph can just be rewritten. And this just adds extra inconvenience for #70464, which will not have this part of the code be spaghetti.

**Comment by ZolotukhinM** [comment]
> We don't have any other instances where we return an alias of an input

As I mentioned earlier, it is a perfectly valid IR and one can get it with:
```python
import torch
@torch.jit.script
def foo(a):
    return a
print(foo.graph)
```
Output:
```
graph(%a.1 : Tensor):
  return (%a.1)
```

Even if we're not getting it anywhere now, in the AOT workflow that's an input we can get from a user.

One might argue that generating an implicit copy for the input is not the right way to handle this and we should instead generate an explicit copy on the graph level. That could be a valid point, but we've already taken an approach of implicit copies (and I think it's a better one) for other cases, such as non-contiguous inputs, and I'm convinced we should use the same approach for this case too.

Also, as I mentioned previously - adding a copy for inputs is only a small portion of this PR. The main part is cleaning up the existing code that handles copying/flattening buffers (it was requested by @navahgar in #66847) - there was some code duplication which now is resolved.

**Review by navahgar — APPROVED** [review]
LGTM

**Comment by ZolotukhinM** [comment]
@ZolotukhinM has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33399116).

**Pull request closed without merging**
