### PR TITLE
[build] Fix for old cmake versions

### PR DESCRIPTION
**Pull request by ssnl**
Strategy:
1. Move all upstream files to `Module_CUDA_fix/upstream/*`. 
2. Create a custom `Module_CUDA_fix/FindCUDA.cmake` that first includes `upstream/CMakeInitializeConfigs.cmake` and then `upstream/FindCUDA.cmake` so it can be used by submodules too.
3. Remove all instances of `include(CMakeInitializeConfigs)`.

For easier review process, [here](https://github.com/SsnL/pytorch/tree/findcuda_wrapper/cmake/Modules_CUDA_fix)'s how `cmake/Module_CUDA_fix` looks like after this patch. 

@ezyang @soumith @orionr 

cc @li-roy @zdevito

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Review by orionr — APPROVED** [review]

**Review by teng-li — APPROVED** [review]

**Comment by ngimel** [comment]
Thanks for fixing the build! May be it is time to just require newer CMake? (3.10 or whichever has all the FindCUDA stuff).

**Comment by SsnL** [comment]
@ngimel IIRC @soumith said we want to keep cmake 3.5 (3.9?) support.

**Comment by ngimel** [comment]
Then may be cmake 3.5 builds should be added to CI?

**Comment by SsnL** [comment]
@soumith @ezyang should we use older cmake versions in CI to prevent such regressions?

**Comment by ezyang** [comment]
Yes.

**Pull request merged**
