### PR TITLE
Add totalGlobalMemory in CUDACachingAllocator

### PR DESCRIPTION
**Pull request by junjihashimoto**
This PR adds the function getting total global memory of GPU.
It is useful to control and monitor cache-rate.

### CODE REVIEW

**Review by ssnl — COMMENTED** [review]
It is unclear why this needs to live in the caching allocator device stats... Also, python bindings and tests are needed.

**Review by apaszke — COMMENTED** [review]
@SsnL while I agree that the caching allocator is not the best place for this (perhaps CUDA context? Doesn’t this live in device properties which we already have there?), the main purpose for this PR is to make it easier for c10/ATen users to get this information (Junji is one of the authors of Hasktorch). Hence I don’t think we necessarily have to have a Python binding in this PR and honestly I don’t know how to test this function reliably.

**Comment by SsnL** [comment]
@apaszke 
> I don’t think we necessarily have to have a Python binding

It is really really easy to add a python binding, so I don't think why we can't keep the parity of c++ and python API functionalities here. That the author of this PR only uses it in c++ context is not a good reason to decide that our python users can't have it.

> honestly I don’t know how to test this function reliably.

I would love to see some sanity tests, if possible, e.g., assert this value >= max memory cached.

**Comment by ezyang** [comment]
Yeah, the design here seems a bit questionable. Not only the fact that it has nothing to do with the caching allocator, but because the stat itself is cached so it could be out of date if you forget to subsequently initialize it. @junjihashimoto, what do you think?

**Review by ezyang — CHANGES_REQUESTED** [review]
Design considerations

**Comment by junjihashimoto** [comment]
@apaszke Thanks for your comment.

Is the stat this global memory? 
In our use-case, we will call the API every second like short term. 
I want to reduce the cost calling it. So the value is cached.

Making python's API is OK, if you verify the function easily.

**Comment by junjihashimoto** [comment]
If we already have common interface to show stats and the stats does not have the metrics of both currentMemoryCached and totalGlobalMemory, I want to add the metrics for the interface.

**Comment by SsnL** [comment]
I have another question. Why can't you just use `at::cuda::getDeviceProperties()` and get total memory from there? Python API also has the counterpart.

**Comment by junjihashimoto** [comment]
Thx! `at::cuda::getDeviceProperties()` may be OK.

BTW, We use `ATen/ATen.h` and `torch/csrc/autograd/*.h` with prebuild-libtorch. 
These files do not depend on `cuda_runtime_api.h`. 
So, we can compile a program using CUDA without installing CUDA-library.

If we use `at::cuda::getDeviceProperties()` depending on `cuda_runtime_api.h`,
we need to install CUDA-library.

I do not want to use `at::cuda::getDeviceProperties()` directly if possible.

**Comment by ezyang** [comment]
That seems legitimate to me.

Excerpts from junji hashimoto's message of 2019-06-28 00:51:33 -0700:
> Thx! `at::cuda::getDeviceProperties()` may be OK.
> 
> BTW, We use `ATen/ATen.h` and `torch/csrc/autograd/*.h` with prebuild-libtorch. 
> These files do not depend on `cuda_runtime_api.h`. 
> So, we can compile a program using CUDA without installing CUDA-library.
> 
> If we use `at::cuda::getDeviceProperties()` depending on `cuda_runtime_api.h`,
> we need to install CUDA-library.
> 
> I do not want to use `at::cuda::getDeviceProperties()` directly if possible. 
>

**Comment by junjihashimoto** [comment]
I'm going to update this PR to get global and allocated memory-size without `cuda_runtime_api.h`.

**Comment by junjihashimoto** [comment]
@SsnL 
Using "at::cuda::getDeviceProperties()" is not so good, because the data-format of cudaDeviceProp  does not keep backward compatibility completely. (I was surprised.)

Python API wraps cudaDeviceProp here. It is good, because it wraps the data-format and user can not access it directly.
https://github.com/pytorch/pytorch/blob/master/torch/csrc/cuda/Module.cpp#L371-L392
But libtorch does not have a such function to access cudaDeviceProp.

**Comment by junjihashimoto** [comment]
Sorry for bothering you.
I've get these total memory usage from cudaMemGetInfo by using dlsym directly.
So this pr is not needed for me.

**Pull request closed without merging**
