### PR TITLE
[dynamo] Remove dead code path for capturing `__class__` in `UserFunctionVariable`

### PR DESCRIPTION
**Pull request by StrongerXi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #140034

This was introduced in https://github.com/pytorch/torchdynamo/commit/d0c10341
as limited support for pre-existing cells, since we know `__class__` wouldn't be modified
in most cases. It's no longer needed now that we have much more support for these cells.

Example:
```python
class Foo():
    def __init__(self):
        super().__init__()

print(Foo.__init__.__code__.co_freevars) # ('__class__',)
print(Foo.__init__.__closure__)          # (<cell at 0x1011fb310: type object at 0x10fe185b0>,)
```

This patch also exposed and fixes a bug in
`NNModuleVariable.var_getattr`, where Dynamo wasn't propagating source
correctly.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Review by williamwen42 — APPROVED** [review]

**Review by anijain2305 — APPROVED** [review]

**Comment by StrongerXi** [comment]
Rebase

**Review by jansel — APPROVED** [review]

**Comment by StrongerXi** [comment]
Internal has `inline_inbuilt_nn_modules = False`, and this patch exposed a small bug in `NNModuleVariable.var_getattr`; I'll update this PR with a quick fix, after some local testing.

**Pull request closed without merging**
