### PR TITLE
Fix MKL status check wrong to MKLDNN.

### PR DESCRIPTION
**Pull request by xuhancn**
Fix check MKL status wrong to MKLDNN.

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Review by malfet — APPROVED** [review]
Thank you for the fix!

**Pull request closed without merging**
