### PR TITLE
[ROCm] allow PYTORCH_ROCM_ARCH in cpp_extension.py

### PR DESCRIPTION
**Pull request by jeffdaily**
Allows extensions to override ROCm gfx arch targets.  Reuses the same env var used during cmake build for consistency.

### CODE REVIEW

**Comment by jeffdaily** [comment]
CC @sunway513

**Review by heitorschueroff — APPROVED** [review]

**Comment by heitorschueroff** [comment]
Thank you for this update

**Comment by heitorschueroff** [comment]
@ngimel I got ahead of myself and imported this PR, feel free to commandeer it or let me know if you'd like me to land it.

**Review by ngimel — APPROVED** [review]
lgtm, @heitorschueroff please land

**Pull request closed without merging**
