### PR TITLE
[modcmake 1/N] Create avx_mathfun interface library for shared TH/ATen code

### PR DESCRIPTION
**Pull request by ezyang**
avx_mathfun is used by both TH and ATen code; if we want to turn
TH into a standalone library, we need a common dependency for the
two libraries.  That's this package.

This patch is part of a series. The individual changes here may make more sense when seen in context; the full context is at #6188. I am splitting this patch series into separate CI-able PRs because I made a mistake that affects Windows only, and I am trying to figure out where the mistake is.

### CODE REVIEW

**Comment by apaszke** [comment]
Are we planning to always be able to build TH without ATen? I got a feeling like we were shifting towards putting everything there, and TH was going to disappear?

**Comment by fmassa** [comment]
Yes, I thought that ATen and TH were a single thing now? https://github.com/pytorch/pytorch/pull/6078#discussion_r178104865

**Comment by ezyang** [comment]
When we do C10, we are necessarily going to introduce a new abstraction barrier between the operator definitions, and the core infrastructure code. This split won't be the traditional TH/ATen; we will need to move bits around, but it's helpful to have more cmake hygiene so it's easier to move things around (otherwise, ATen must be built and compiled as one piece. This is NOT the eventual desired end goal.)

Happy to debate if this is a good idea or not though :)

**Comment by ezyang** [comment]
I'm happy to skip this patch and remove `avx_mathfun` instead. This patch wasn't that much work to do either though, and doesn't make the removal any harder ;)

**Pull request closed without merging**
