### PR TITLE
.circleci: Add workflows for Python 3.8

### PR DESCRIPTION
**Pull request by seemethere**
Done by just editing `.circleci/cimodel/data/dimensions.py` to include `3.8` and then regenerated using `.circleci/regenerate.sh`

cc @kostmo, @mingbowan, @ezyang, @soumith 

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

### CODE REVIEW

**Review by soumith — APPROVED** [review]
if things pass, shipit!

**Comment by seemethere** [comment]
After a second glance through at these changes I don't think any python 3.8 specific tests will be run on PRs and that these changes only apply to the `nightly`/`postnightly` branches.

@kostmo where would the other places to change be so that we can have full Python 3.8 coverage?

**Comment by kostmo** [comment]
Yes, Python version lists are scattered in a few different places.  I think this will find the ones that matter:
```
kostmo@ubuntu:~/github/pytorch-repos/pytorch$ git grep --name-only '3.6' -- .circleci/cimodel/**/*.py
.circleci/cimodel/data/binary_build_data.py
.circleci/cimodel/data/caffe2_build_data.py
.circleci/cimodel/data/caffe2_build_definitions.py
.circleci/cimodel/data/dimensions.py
.circleci/cimodel/data/pytorch_build_data.py
.circleci/cimodel/data/pytorch_build_definitions.py
```
I wish it was as simple as a single list!

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 5f04e580:


**None of the build failures appear to be your fault**.

* **1/1** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=f0072b3af5f4bb49a4f4efa13b9de92ceeb2ccc9&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base f0072b3a since Jan 08
  <details>
  <summary>
  You may want to rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch origin viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=5f04e5805127b02eec1aa1eee0abe40033886c9f).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [pytorch_linux_backward_compatibility_check_test](https://dr.pytorch.org/build-details.html?build_id=82139071) from Jan 08



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by seemethere** [comment]
Whoo! macOS builds are ready to go:
* https://circleci.com/gh/pytorch/pytorch/4354608?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Pull request closed without merging**
