### PR TITLE
[structural binding][1/N] Replace std::tie with structural binding

### PR DESCRIPTION
**Pull request by cyyever**
This PR replaces some std::tie calls with structural binding from C++17.  This not only makes the code more compact, but also has some performance gain.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

### CODE REVIEW

**Review by albanD — APPROVED** [review]
If our CI version of MSVC is happy with this, I'm happy :D 

Very nice cleanup btw!

**Review by malfet — APPROVED** [review]

**Comment by cyyever** [comment]
> > If our CI version of MSVC is happy with this, I'm happy :D
> 
> Internally we use older MSVC, so it might be tricky. I would split this change in two: one that modifies cpp only file and another that tries to do the same with CUDA ones

No problem, let's split it.

**Pull request closed without merging**
