### PR TITLE
Enhance exporting torch.minimum() function to ONNX so it can handle parameters with different dtype.

### LINKED ISSUE #76022: [ONNX] torch.minimum() could not be exported successfully if given parameters have different dtypes.
### 🐛 Describe the bug

If the parameters of torch.minimum() are two different integer formats, like int16 and int32. The final ONNX file could not be inferenced by ORT successfully. Because the Min op in ONNX needs the two parameters has the exact same data format.

### Versions

torch=1.11.0
onnxruntime=1.11.0

### PR DESCRIPTION
**Pull request by fatcat-z**
Handle the case that the parameters of torch.minimum() have different dtypes. Add tests as well.

Fixes #76022

### CODE REVIEW

**Comment by garymm** [comment]
Please reference the GitHub issue this is fixing in the PR description.

**Comment by thiagocrepaldi** [comment]
```
022-04-15T07:04:37.8473620Z   self._warn("No data was collected.", slug="no-data-collected")
2022-04-15T07:04:38.5487969Z 
2022-04-15T07:04:38.5487980Z 
2022-04-15T07:04:38.5490703Z =================================== FAILURES ===================================
2022-04-15T07:04:38.5491294Z [31m[1m_________________ TestONNXRuntime_opset14.test_minimum_dtypes __________________[0m
2022-04-15T07:04:38.5491560Z Traceback (most recent call last):
2022-04-15T07:04:38.5491844Z   File "/var/lib/jenkins/workspace/test/onnx/test_pytorch_common.py", line 54, in wrapper
2022-04-15T07:04:38.5492210Z     return func(self)
2022-04-15T07:04:38.5492502Z   File "/var/lib/jenkins/workspace/test/onnx/test_pytorch_onnx_onnxruntime.py", line 7885, in test_minimum_dtypes
2022-04-15T07:04:38.5495104Z     self.run_test(MinimumModel(), (x, y))
2022-04-15T07:04:38.5495665Z   File "/var/lib/jenkins/workspace/test/onnx/test_pytorch_onnx_onnxruntime.py", line 333, in run_test
2022-04-15T07:04:38.5496218Z     _run_test(script_model, scripting_remained_onnx_input_idx, flatten=False)
2022-04-15T07:04:38.5496549Z   File "/var/lib/jenkins/workspace/test/onnx/test_pytorch_onnx_onnxruntime.py", line 322, in _run_test
2022-04-15T07:04:38.5496808Z     flatten=flatten)
2022-04-15T07:04:38.5497096Z   File "/var/lib/jenkins/workspace/test/onnx/test_pytorch_onnx_onnxruntime.py", line 176, in run_model_test
2022-04-15T07:04:38.5498047Z     output_names=output_names, fixed_batch_size=fixed_batch_size, training=training)
2022-04-15T07:04:38.5498447Z   File "/var/lib/jenkins/workspace/test/onnx/test_pytorch_onnx_onnxruntime.py", line 100, in convert_to_onnx
2022-04-15T07:04:38.5498867Z     ort_sess = onnxruntime.InferenceSession(f.getvalue(), so, providers=_ORT_PROVIDERS)
2022-04-15T07:04:38.5499398Z   File "/var/lib/jenkins/.local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
2022-04-15T07:04:38.5499779Z     self._create_inference_session(providers, provider_options, disabled_optimizers)
2022-04-15T07:04:38.5500273Z   File "/var/lib/jenkins/.local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 381, in _create_inference_session
2022-04-15T07:04:38.5500672Z     sess.initialize_session(providers, provider_options, disabled_optimizers)
2022-04-15T07:04:38.5501536Z onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for Min(13) node with name 'Min_1'
```
@fatcat-z CI is failing with this change, please address it

**Review by thiagocrepaldi — APPROVED** [review]

**Comment by thiagocrepaldi** [comment]
@fatcat-z could you rebase this PR with upstream master? We just got a change checked in that allow us to modify          "aten/src/ATen/core/interned_strings.h" and merge it quickly

**Review by garymm — APPROVED** [review]
@pytorchbot merge this

**Pull request closed without merging**
