### PR TITLE
Enable type-checking of torch.nn.quantized.* modules

### LINKED ISSUE #43029: Enable torch.nn.quantized typechecks during CI
`TestTypeHints.test_run_mypy_strict` should pass with `[mypy-torch.nn.quantized.*]` deleted from mypy.ini

cc @albanD @mruberry @ezyang @malfet @rgommers

### PR DESCRIPTION
**Pull request by guilhermeleobas**
Fixes #43029 

I am not changing the following files in this PR:
* `torch/nn/quantized/dynamic/modules/rnn.py` due to https://github.com/pytorch/pytorch/issues/43072
* `torch/nn/quantized/modules/conv.py`

### CODE REVIEW

**Comment by rgommers** [comment]
@guilhermeleobas did you somehow open this PR by mistake? It's the same as gh-43068.

**Comment by guilhermeleobas** [comment]
@rgommers I couldn't revert the submodule update in the other PR. I will close the old one in favor of this.

**Review by rgommers — CHANGES_REQUESTED** [review]
Thanks @guilhermeleobas. One thing to fix - splitting annotations between a `.py` and a `.pyi` file isn't a good idea.

**Review by rgommers — APPROVED** [review]
LGTM

**Pull request closed without merging**
