### PR TITLE
[complex] torch.sqrt: fix edge values

### LINKED ISSUE #47358: [complex] torch.{sqrt, abs}: does not match numpy
Happens only on CPU

**torch.cfloat**
```python
>>> import torch
>>> torch.__version__
'1.8.0a0+73e121d'
>>> import numpy as np
>>> x = torch.tensor(0.-1.0000e+20j)
>>> x.sqrt()
tensor(inf-infj)
>>> np.sqrt(x.numpy())
(7071067600-7071067600j)
```

**torch.cdouble**
```python
>>> import torch
>>> x = torch.tensor(-1.0000e+20-4988429.2000j, dtype=torch.complex128)
>>> x.sqrt()
tensor(0.-1.0000e+10j, dtype=torch.complex128)
>>> import numpy as np
>>> np.sqrt(x.numpy())
(0.00024942146-10000000000j)
>>> x.cuda().sqrt().cpu().numpy() == np.sqrt(x.numpy())
True
```

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @anjali411 @dylanbespalko @mruberry @vishwakftw @jianyuh @nikitaved @pearu

### PR DESCRIPTION
**Pull request by kshitij12345**
Fixes #47358 

Replace the optimized path with a slower but correct `map(std::sqrt)`

Benchmark posted below in comments.

cc: @dylanbespalko (original author of fast-path)

### CODE REVIEW

**Comment by kshitij12345** [comment]
Benchmark

Before the change :
```
[-------- sqrt torch.complex64 --------]
                       |  torch.sqrt CPU
8 threads: -----------------------------
      (32,)            |        3.0     
      (32, 32)         |        4.3     
      (2, 16, 32)      |        4.3     
      (2, 16, 32, 32)  |       13.2     

Times are in microseconds (us).
 
Using pytorch 1.8.0a0+f19637e
10 / 10[------- sqrt torch.complex128 --------]
                       |  torch.sqrt CPU
8 threads: -----------------------------
      (32,)            |        3.0     
      (32, 32)         |        7.1     
      (2, 16, 32)      |        7.1     
      (2, 16, 32, 32)  |       24.4     

Times are in microseconds (us).
```

After the change:
```
[-------- sqrt torch.complex64 --------]
                       |  torch.sqrt CPU
8 threads: -----------------------------
      (32,)            |        3.7     
      (32, 32)         |       37.8     
      (2, 16, 32)      |       38.4     
      (2, 16, 32, 32)  |      160.6     

Times are in microseconds (us).

[------- sqrt torch.complex128 --------]
                       |  torch.sqrt CPU
8 threads: -----------------------------
      (32,)            |        3.5     
      (32, 32)         |       26.9     
      (2, 16, 32)      |       26.7     
      (2, 16, 32, 32)  |      115.9     

Times are in microseconds (us).
```

Benchmark Script
```python
import torch
import itertools
import time
from torch.utils.benchmark import Timer
from torch.utils.benchmark import Compare
import sys

print('Using pytorch %s' % (torch.__version__))

shapes = [(32,), (32, 32), (2, 16, 32), (2, 16, 32, 32)]
results = []
num_threads = 8
dtype = torch.cdouble
repeats = 10

for mat1_shape in shapes:
    mat1 = torch.rand(*mat1_shape, dtype=dtype, device='cpu')

    tasks = [("torch.sqrt(mat1)", "torch.sqrt CPU")]
    timers = [Timer(stmt=stmt, num_threads=num_threads, label=f"sqrt {dtype}", sub_label=f"{(mat1_shape)}", description=label, globals=globals()) for stmt, label in tasks]

    for i, timer in enumerate(timers * repeats):
        results.append(
            timer.blocked_autorange()
        )
        print(f"\r{i + 1} / {len(timers) * repeats}", end="")
        sys.stdout.flush()
comparison = Compare(results)
comparison.print()
```

**Comment by kshitij12345** [comment]
> https://github.com/pytorch/pytorch/issues/47358#issuecomment-722252021
> Issue looks to arise from use of `abs`,
> 
> ```python
> import numpy as np
> import torch
> 
> print(torch.__version__)
> x = torch.tensor([0.-1.0000e+20j] * 10)
> print("ABS:", x.abs())
> print("ABS:", np.abs(x.numpy()))
> ```
> 
> Output
> 
> ```
> 1.8.0a0+f19637e
> ABS: tensor([       inf,        inf,        inf,        inf,        inf,        inf,
>                inf,        inf, 1.0000e+20, 1.0000e+20])
> ABS: [1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20]
> ```



> Issue looks to arise from use of `abs`,
> 
> ```python
> import numpy as np
> import torch
> 
> print(torch.__version__)
> x = torch.tensor([0.-1.0000e+20j] * 10)
> print("ABS:", x.abs())
> print("ABS:", np.abs(x.numpy()))
> ```
> 
> Output
> 
> ```
> 1.8.0a0+f19637e
> ABS: tensor([       inf,        inf,        inf,        inf,        inf,        inf,
>                inf,        inf, 1.0000e+20, 1.0000e+20])
> ABS: [1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20]
> ```

**Comment by samestep** [comment]
It looks like your PR broke a few other tests (besides the performance regressions you documented); these are the ones I'm seeing from the [pytorch_linux_xenial_py3_6_gcc5_4_test](https://app.circleci.com/pipelines/github/pytorch/pytorch/235495/workflows/ffd1d7bc-87a3-407f-912f-81988cc6a9f8/jobs/8718910) job:
```
Nov 05 08:21:01 [  FAILED  ] 4 tests, listed below:
Nov 05 08:21:01 [  FAILED  ] SqrtAndReciprocal/2.Sqrt, where TypeParam = at::vec256::(anonymous namespace)::Vec256<c10::complex<float> >
Nov 05 08:21:01 [  FAILED  ] SqrtAndReciprocal/3.Sqrt, where TypeParam = at::vec256::(anonymous namespace)::Vec256<c10::complex<double> >
Nov 05 08:21:01 [  FAILED  ] InverseTrigonometric/2.Asin, where TypeParam = at::vec256::(anonymous namespace)::Vec256<c10::complex<float> >
Nov 05 08:21:01 [  FAILED  ] InverseTrigonometric/2.ACos, where TypeParam = at::vec256::(anonymous namespace)::Vec256<c10::complex<float> >
Nov 05 08:21:01 
Nov 05 08:21:01  4 FAILED TESTS
```
Could you fix all the broken tests to give better context of the scope of your proposed change?

**Comment by kshitij12345** [comment]
@samestep Thanks for looking at it and catching the failed tests. 

I thought, those failures were related to torch.distributed from the dr-ci comment.

**Comment by samestep** [comment]
@kshitij12345 That's quite possible, I didn't look too closely; if so then I apologize for the noise.

**Comment by kshitij12345** [comment]
@samestep You were indeed correct. The snippet was pointing at some noisy error. But the errors, you mentioned were real. Thanks!

**Comment by kshitij12345** [comment]
Not sure. What is happening with `macos` failure. 
https://app.circleci.com/jobs/github/pytorch/pytorch/8729272

Also I don't have a mac on me to verify. Should I mark it for skipping.

**Comment by mruberry** [comment]
The failure on MacOS looks real, the failure on Windows seems unrelated.

The test should go in test_unary_ufuncs.py and have a comment linking the issue it's testing for. 

You can file a new issue for the fail on MacOS, skip the test on MacOS, and add a comment linking to THAT issue to explain the skip. 

The performance regression is regrettable but it's better to be correct than fast and wrong.

**Comment by kshitij12345** [comment]
>  The test should go in test_unary_ufuncs.py and have a comment linking the issue it's testing for.

Done

> You can file a new issue for the fail on MacOS, skip the test on MacOS, and add a comment linking to THAT issue to explain > the skip.

Done

**Review by mruberry — APPROVED** [review]
Cool! Thanks @kshitij12345!

**Review by walterddr — APPROVED** [review]

**Comment by mruberry** [comment]
Now that this has been merged we should review speeding it up again in a way that doesn't have numeric issues.

**Comment by kshitij12345** [comment]
> Now that this has been merged we should review speeding it up again in a way that doesn't have numeric issues.

Yes.
Probably doing something based on the following comment might help.

> Did a bit of digging. seems like this has nothing to do with the vec256 but more of the fact that std::sqrt was implemented as (aa + bb)^0.5 where as the it should've been using something similar to hypot, e.g. |a| * (1+(b/a)^2)^0.5 .

Reference to comment : https://github.com/pytorch/pytorch/issues/47500#issuecomment-723504390

**Pull request closed without merging**
