### PR TITLE
Fix copy_ forward AD to handle broadcasting

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #69727
* #69740
* #69690
* #69661
* #69597
* #69384
* __->__ #69592
* #69558

Currently, forward AD function for`copy_` (in `VariableTypeManual`) does not handle the broadcasting case. ~EDIT: but that is not a design decision, not a bug. In this PR, we make that clear as a comment.~

Note: `broadcast_to` does not have a batching rule in core, so the ops that rely on `copy_` to broadcast will still fail batched forward grad computation.

Differential Revision: [D33020603](https://our.internmc.facebook.com/intern/diff/D33020603)

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
So we are moving to have the forward ad formula that do the same as the backward: they do not handle broadcasting and the autograd does it for them?

**Comment by soulitzer** [comment]
Ahh... I did not make this connection when I wrote this. I'm not sure we do want to implicitly broadcast, so I will close this.
I will fix the composite failures that rely on `copy_` by just broadcasting at the call site.

**Comment by albanD** [comment]
Not sure to follow your dashed comments here?
The answer is that the "engine" handles broadcasting and we can ignore it in the formula?

**Review by albanD — APPROVED** [review]
Ho the impl is in copy_. My bad!
This sounds good!

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020603).

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020603).

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020603).

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33020603).

**Pull request closed without merging**
