### PR TITLE
Implement consistent dispatch order for custom functions

### PR DESCRIPTION
**Pull request by zhuhaozhe**
Hi, I am working on dev some custom ops.

And I found this issue:

Cause of the logical here: https://github.com/pytorch/pytorch/compare/master...zhuhaozhe:customer-op-trace?expand=1#diff-d7ade8589773904745c0cf965a19f24c940f1d36038f4c0ce85af2f3d89991dcL173-L177.
For all custom ops, "Tracer" dispatch key got the highest priority.

This make custom-ops and non-custom-ops get different behavior during dispatch. I do not understand whether there exist some special reason to let custom-ops "trace" first then begin to "dispatch".

### CODE REVIEW

**Comment by zhuhaozhe** [comment]
This PR is trying to remove the special trace logical for custom ops, and make the ops without registered under "Tracer" fall through to the general trace logic written by https://github.com/pytorch/pytorch/pull/60251/files#diff-d7ade8589773904745c0cf965a19f24c940f1d36038f4c0ce85af2f3d89991dcL30-L152

**Comment by zhuhaozhe** [comment]
If customer ops "traced" first, the tracer dispatch key will be removed. And the "to" taken place under "AutoCast" function will not be record on graph. For example:

Here is graph under autocast context, the **"weight" is casted to "bfloat16" but this dose not showed on graph**.
graph(%self : __torch__.torch.nn.modules.sparse.EmbeddingBag,
      %input : Long(8, strides=[1], requires_grad=0, device=cpu),
      %offsets : Long(8, strides=[1], requires_grad=0, device=cpu)):
  %33 : Tensor = prim::GetAttr[name="weight"](%self)
  %6 : bool = prim::Constant[value=1]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/intel_pytorch_extension/ops/embeddingbag.py:9:0
  %7 : bool = prim::Constant[value=0]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/intel_pytorch_extension/ops/embeddingbag.py:9:0
  %8 : BFloat16(8, 3, strides=[3, 1], requires_grad=0, device=cpu) = torch_ipex::embedding_bag(%33, %input, %offsets, %6, %7) # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/intel_pytorch_extension/ops/embeddingbag.py:9:0
  return (%8)

**which expected graph might be:**
graph(%self : __torch__.torch.nn.modules.sparse.EmbeddingBag,
      %input : Long(8, strides=[1], requires_grad=0, device=cpu),
      %offsets : Long(8, strides=[1], requires_grad=0, device=cpu)):
  **_%38 : Tensor = prim::GetAttr[name="weight"](%self)
  %6 : int = prim::Constant[value=15]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/intel_pytorch_extension/ops/embeddingbag.py:9:0
  %7 : bool = prim::Constant[value=0]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/intel_pytorch_extension/ops/embeddingbag.py:9:0
  %8 : bool = prim::Constant[value=0]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/intel_pytorch_extension/ops/embeddingbag.py:9:0
  %9 : NoneType = prim::Constant()
  %10 : BFloat16(10, 3, strides=[3, 1], requires_grad=0, device=cpu) = aten::to(%38, %6, %7, %8, %9) # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/intel_pytorch_extension/ops/embeddingbag.py:9:0_**
  %11 : bool = prim::Constant[value=1]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/intel_pytorch_extension/ops/embeddingbag.py:9:0
  %12 : bool = prim::Constant[value=0]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/intel_pytorch_extension/ops/embeddingbag.py:9:0
  %13 : BFloat16(8, 3, strides=[3, 1], requires_grad=0, device=cpu) = torch_ipex::embedding_bag(%10, %input, %offsets, %11, %12) # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/intel_pytorch_extension/ops/embeddingbag.py:9:0
  return (%13)

**Comment by zhuhaozhe** [comment]
@jgong5 @leslie-fang-intel any comment here?

**Comment by zhuhaozhe** [comment]
This UT failure https://circleci.com/gh/pytorch/pytorch/14510165?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link seems not introduced by this PR. I revert my 2 commits and still meet this failure.

**Comment by ezyang** [comment]
I'm generally optimistic on this approach. Need to review.

**Review by ezyang — APPROVED** [review]
Long overdue, thanks a lot for sending this in.

**Pull request closed without merging**
