### PR TITLE
Require inductor to match stride order

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #90563

Fix for https://github.com/pytorch/pytorch/issues/90454. 

```
import torch
import torch._dynamo

def fn(x):
    y = x.permute(0, 2, 3, 1).contiguous()
    torch._dynamo.graph_break()
    return y.view(-1, 4)

opt_fn = torch._dynamo.optimize("inductor")(fn)
x = torch.rand([4, 4, 4, 4])
print(opt_fn(x))
```

would error because `y` didn't preserve the stride. The long term the solution proposed has been infallible strides, so this is more of a short term thing.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
Please run some perf tests on this, stride manipulation PRs have been known to regress perf (convnext would be a good smoketest)

**Review by jansel — APPROVED** [review]

**Comment by eellison** [comment]
closing in favor of https://github.com/pytorch/pytorch/pull/91185

**Pull request closed without merging**
