### PR TITLE
Raise an error for unsupported ctx managers

### PR DESCRIPTION
**Pull request by nakulcr7**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108272

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov

### CODE REVIEW

**Comment by nakulcr7** [comment]
This PR is in response to #102339

**Review by anijain2305 — APPROVED** [review]

**Comment by anijain2305** [comment]
@pytochbot merge

**Pull request closed without merging**
