### PR TITLE
Run onnx integration tests in caffe2 CI

### PR DESCRIPTION
**Pull request by bddppq**
Currently only `py2-gcc5-ubuntu16.04` has been enabled to run integration tests.

### CODE REVIEW

**Review by pjh5 — COMMENTED** [review]
Do you want to turn this on for conda builds too? If so you'd need to change line 93

**Comment by bddppq** [comment]
@pjh5 You mean installing pytorch? I think that has been handled in build_anaconda.sh (with environment variable `INTEGRATED=1`

**Comment by pjh5** [comment]
I mean installing onnx in the same way '''pip install --user -b /tmp/pip_install_onnx "file://${ROOT_DIR}/third_party/onnx#egg=onnx" '''

**Comment by bddppq** [comment]
@pjh5 I'm not sure whether this will work with conda. And the main reason I'm doing user install here is to avoid using sudo, and conda doesn't have this problem because it has its own virtual environment.

**Comment by bddppq** [comment]
@pjh5 added the compilation cache trick to conda builds

**Comment by pjh5** [comment]
Conda-builds unfortunately don't use the cache yet, as the prefix of the temp environment is different every time. I tried adding a flag to ccache a while ago to account for it, but it didn't seem to improve performance at all.

**Comment by bddppq** [comment]
@pjh5 the cache trick for onnx installation does seem to be working https://ci.pytorch.org/jenkins/job/caffe2-builds/job/conda2-ubuntu16.04-build/1961/console

**Comment by bddppq** [comment]
@onnxbot retest this please

**Review by ezyang — APPROVED** [review]

**Pull request merged**
