### PR TITLE
[LTC] Metrics can be reset too

### PR DESCRIPTION
**Pull request by alanwaketan**
Summary:
This change allow MetricsArena to ResetMetrics too. And then rename Reset to ResetCounters given that's what it does for real.

This matches pytorch/xla#4109, and is paired with pytorch/xla#4245.

Test Plan:
CI.

### CODE REVIEW

**Review by JackCaoG — APPROVED** [review]
Do we need metrics outside of computation client? I guess we need it eventually.

**Comment by alanwaketan** [comment]
> Do we need metrics outside of computation client? I guess we need it eventually.

We actually use that in a lot of places. See https://github.com/pytorch/xla/pull/4245.

**Pull request closed without merging**
