### PR TITLE
[c10d] Add option structs and timeout field

### PR DESCRIPTION
**Pull request by pietern**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #14294 [c10d] Use new style barrier support in c10d/gloo&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13111509/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #14295 [c10d] Remove algorithm caching in ProcessGroupGloo&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13111781/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #14296 [c10d][easy] Refer to all work with ProcessGroup prefix&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13128977/)
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#14297 [c10d] Add option structs and timeout field**&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13158474/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #14298 [c10d] Make ProcessGroup::Work::wait() throw&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13158475/)
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #14386 [c10d] Barrier synchronizes with prior work before completing&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D13205022/)

Adds option structs for allgather and barrier such that we have one
for every collective. Add timeout member field to every one of these
such that we can support per operation timeouts.

Use default constructed options struct for every collective process
group function exposed to Python.

Differential Revision: [D13158474](https://our.internmc.facebook.com/intern/diff/D13158474/)

### CODE REVIEW

**Comment by teng-li** [comment]
@pietern How do you want to expose timeout eventually to the front-end API, we should document this better since now only Gloo supports timeout, the other twos do not. Maybe adding a comment somewhere making this a TODO for other two backends.

**Comment by pietern** [comment]
We can add a timeout kwarg to all collectives in `torch.distributed`. What do you think?

Added issues #14371 and #14372 to track timeout for NCCL and MPI backends.

**Comment by pietern** [comment]
Added issue #14376 for adding the timeout kwarg to `torch.distributed`.

**Review by teng-li — APPROVED** [review]
Thanks for making these tracking issues.

**Comment by teng-li** [comment]
@pietern Yep, as we discussed in the tracking issue. I would also like these to be well documented, when we don't have timeout option for the other two backends. Can you open another issue tracking this documentation just in case we forget?

**Comment by pietern** [comment]
@teng-li Updated the tracking issue for the timeout kwarg to match what we'll do.

**Pull request closed without merging**
