### PR TITLE
Fix torch.utils.benchmark API while use privateuse1.

### PR DESCRIPTION
**Pull request by QiuKaida163**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by QiuKaida163** [comment]
release notes: profiler

**Comment by QiuKaida163** [comment]
I hope to synchronize PrivateUse1 device while using the torch.utils.benchmark modules.

**Comment by colesbury** [comment]
@bdhirsh - are you familiar with "_get_privateuse1_backend_name"? Can you look at this?

**Comment by QiuKaida163** [comment]
@colesbury Sorry to bother. Can you tell me what should I do next. Thanks!

**Comment by QiuKaida163** [comment]
@bdhirsh @colesbury Sorry to bother. Can you tell me what should I do next. Thanks!

**Comment by QiuKaida163** [comment]
@bdhirsh Hi, Can you help me re-run my pr. Tnanks!

**Pull request closed without merging**
