### PR TITLE
Dropout update in autodiff take2

### PR DESCRIPTION
**Pull request by jjsjann123**
restore reverted PR #66273

### CODE REVIEW

**Review by malfet — COMMENTED** [review]
Please note, that previous iteration of this diff caused crashes in torchvision profilier analyzer, which makes me suspicious of unconditional attempts to  `n->input(2)` calls, see https://github.com/pytorch/vision/issues/4616

**Review by eellison — COMMENTED** [review]
@jjsjann123 did we figure out the bug here ?

**Comment by jjsjann123** [comment]
Thanks for pointing me to the bt. It's indeed concerning.

I don't have repro on debug build. Let me switch to release.

**Comment by jjsjann123** [comment]
Tried to run with ASAN build, but that doesn't give much information.

Running tests are fine, but exiting python throws out quite a lot of MemoryLeaks, and that behavior is about the same with & without our PR.
```
==33270==ERROR: LeakSanitizer: detected memory leaks
```

**Review by malfet — APPROVED** [review]

**Comment by jjsjann123** [comment]
The old problem is properly fixed in #63937
Closing this one.

**Pull request closed without merging**
