### PR TITLE
[doc] Add overflow notice for cuFFT on half precision 

### LINKED ISSUE #33485: torch.rfft returns NaNs for some half precision CUDA inputs
## 🐛 Bug

When using half precision and CUDA, torch.rfft sometimes returns NaNs.

## To Reproduce

```Python3
size = 64
wn = torch.rand(size, size, size, dtype = torch.half, device = "cuda")
assert torch.isfinite(wn).all()
wn_freq = torch.rfft(wn, 3, onesided = True)
assert torch.isfinite(wn_freq).all() # <- FAILS
```

Setting `size` to 32 or smaller seem to work fine, 64 or bigger seems to fail. I haven't tested this rigorously. I'm 80% sure that I was running the same code on the same setup with the same version without hitting this error a few days ago, but I can't be sure. The issue survives a restart of the machine.

## Expected behavior

Not NaNs.

## Environment
Google Colab.

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.17.5
[pip3] torch==1.4.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.5.0
[conda] Could not collect
```

cc @ngimel

### PR DESCRIPTION
**Pull request by xwang233**
This would fix #33485. 

cc @ptrblck

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Is NaN/Inf-issue related to "training on CUDA" per se?

From what I understood it can happen in any setting, just related to cuFFT functioning.

**Comment by xwang233** [comment]
Thanks for the comment. I have reworded that.

**Review by ngimel — APPROVED** [review]

**Comment by xwang233** [comment]
@ngimel I found this PR was reverted at https://github.com/pytorch/pytorch/commit/a15a4a5cafb0aef1f4381e8c193c8af327562f83. Is it because of the lint? Can I reland it if I fix the lint?

**Comment by ngimel** [comment]
Yeah, it was because of the lint. Sure, you can reland.

**Pull request closed without merging**
