### PR TITLE
improve eager overhead of _disable_dynamo

### PR DESCRIPTION
**Pull request by bdhirsh**
it seems like `_disable_dynamo` actually has a fair amount of overhead (especially when it was added to `DTensor.__new__`: this change speeds up @wanchaol 's repro from 0.380 -> 0.312s: P1378202570 (that repro runs a vanilla MLP using 2D parallelism, and calls the DTensor constructor 1280 times).

It looks like most of the slowndown is in the fact that we are repeatedly running `import torch._dynamo` and constructing an instance of `torch._dynamo.disable(fn, recursive)` on every call to the constructor - this PR caches it on the first invocation.

~~Update: I realized I cannot use `torch.compiler.is_compiling` to know when to fast-path, because when we hit a graph break, cpython will be running so it will return False.~~

~~As a test / potential fix, I added a new config, `torch._dynamo.config._is_compiling` that is set to True **always** inside a compiled region (even on frames that are run by cpython). This definitely seems to do what I want in terms of knowing when to fastpath and avoid overhead - although interested in feedback on how reasonable this is~~

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #126784
* #126541
* __->__ #127325

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]
This looks great! thanks for addressing it!

**Comment by bdhirsh** [comment]
@wanchaol @anijain2305 I talked to Animesh some more and ended up making this PR much simpler; most of the slowdown was in the fact that we were constructing the `disable()` context manager on every invocation, so I cached it instead.

**Review by anijain2305 — APPROVED** [review]

**Pull request closed without merging**
