### PR TITLE
Add ci binary test for windows

### PR DESCRIPTION
**Pull request by guyang3532**
Tested in https://github.com/pytorch/pytorch/pull/38316.

### CODE REVIEW

**Comment by ezyang** [comment]
Un-WIP this when you're ready for review

**Review by peterjc123 — APPROVED** [review]

**Comment by peterjc123** [comment]
Waiting for the merge of https://github.com/pytorch/builder/pull/442.

**Comment by peterjc123** [comment]
@guyang3532 https://github.com/pytorch/builder/pull/442 is merged. Could you please trigger a retest?

**Comment by guyang3532** [comment]
> @guyang3532 [pytorch/builder#442](https://github.com/pytorch/builder/pull/442) is merged. Could you please trigger a retest?

ok

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
