### PR TITLE
Rename SymbolicIntNode to SymIntNodeImpl

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #82355
* __->__ #82350

Done via

```
git grep -l 'SymbolicIntNode' | xargs sed -i 's/SymbolicIntNode/SymIntNodeImpl/g'
```

Reasoning for the change:

* Sym is shorter than Symbolic, and consistent with SymInt
* You usually will deal in shared_ptr<...>, so we're going to
  reserve the shorter name (SymIntNode) for the shared pointer.

But I don't want to update the Python name, so afterwards I ran

```
 git grep -l _C.SymIntNodeImpl | xargs sed -i 's/_C.SymIntNodeImpl/_C.SymIntNode/'
```

and manually fixed up the binding code

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
Hmph, it looks like this also wobbles the name in Python

**Review by Krovatkin — APPROVED** [review]
this will probably break XLA?

:shipit:

**Comment by ezyang** [comment]
Seems like xla is ok, oddly enough

**Comment by miladm** [comment]
The downstream pytorch/xla blocker is fixed https://github.com/pytorch/xla/pull/3793

**Review by miladm — COMMENTED** [review]
The downstream pytorch/xla blocker is fixed https://github.com/pytorch/xla/pull/3793

**Pull request closed without merging**
