### PR TITLE
Upgrade mkldnn bridge to reduce overhead of bridge itself

### PR DESCRIPTION
**Pull request by gujinghui**
Upgrade mkldnn bridge to reduce overhead of bridge itself

### CODE REVIEW

**Comment by gujinghui** [comment]
@yinghai @jgong5 

Pls review

**Comment by gujinghui** [comment]
@yinghai  have no idead on the failure of "ci/circleci: Config Processing Error"
Pls help review

**Comment by gujinghui** [comment]
@wesolwsk 
Is there any blocking issue for this PR?
If any, pls contact us anytime.

**Comment by jgong5** [comment]
@wesolwsk Please let us know anything that we can help. We are glad to help.

**Comment by gujinghui** [comment]
@wesolwsk 
We submit latest ideep update for this PR.
There is no change for mkldnn. We just fix some bugs in ideep for training.

**Comment by gujinghui** [comment]
@wesolwsk 
Just submit a new version of ideep itself to fix a bug in ideep, instead of mkl-dnn. :)

**Comment by yinghai** [comment]
@gujinghui Which commit of the bug fix is it?

**Comment by wesolwsk** [comment]
@yinghai, do we still need this after the mkl-dnn an ideep upgrades?

**Comment by yinghai** [comment]
@wesolwsk Yeah, we still need this. But @gujinghui seems to have force push this PR to update the IDEEP version again. We need to check whether it's in our internal repo first.

**Comment by jgong5** [comment]
@yinghai @wesolwsk We may keep the IDEEP version with the one you are validating internally and rollback some commits if needed. We plan to PR the IDEEP header files into the PyTorch repo soon so that IDEEP changes can be easier to merge in the future.

**Comment by yinghai** [comment]
@wesolwsk ok to merge?

**Comment by yinghai** [comment]
@gujinghui  I'm reverting this as it's breaking the master. It probably needs a rebase and resubmission. 

https://github.com/pytorch/pytorch/pull/14040

**Comment by gujinghui** [comment]
@yinghai 
Sure. Will resubmit when done.

**Pull request closed without merging**
