### PR TITLE
[ROCm] enable cudagraph inductor UTs on ROCm

### PR DESCRIPTION
**Pull request by jataylo**
These tests can now be enabled after a hipGraph fix landed in 5.6.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @anijain2305

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@jataylo please post the log link and a snippet of the relevant passing unit tests once you have it

**Comment by jataylo** [comment]
Relevant logs cc: @jithunnair-amd 

```
inductor/test_torchinductor
-------------------------------
1/4: https://ossci-raw-job-status.s3.amazonaws.com/log/15231010643 
2023-07-21T10:10:18.1621708Z - generated xml file: /var/lib/jenkins/pytorch/test/test-reports/python-pytest/inductor.test_torchinductor/inductor.test_torchinductor-c7b0a19cf327bea5.xml -
2023-07-21T10:10:18.1622199Z ================== 245 passed, 8 skipped in 527.41s (0:08:47) =================
2/4: https://ossci-raw-job-status.s3.amazonaws.com/log/15231010643 
023-07-21T10:09:19.7833799Z - generated xml file: /var/lib/jenkins/pytorch/test/test-reports/python-pytest/inductor.test_torchinductor/inductor.test_torchinductor-5afcc01b1a295c62.xml -
2023-07-21T10:09:19.7834383Z ================= 206 passed, 11 skipped in 478.25s (0:07:58) ==================
3/4: https://ossci-raw-job-status.s3.amazonaws.com/log/15231010643 
2023-07-21T10:10:59.6513531Z - generated xml file: /var/lib/jenkins/pytorch/test/test-reports/python-pytest/inductor.test_torchinductor/inductor.test_torchinductor-94549d9a6661babb.xml -
2023-07-21T10:10:59.6514138Z ================= 233 passed, 12 skipped in 573.54s (0:09:33) ==================
4/4: https://ossci-raw-job-status.s3.amazonaws.com/log/15231011023
2023-07-21T10:09:54.6618162Z - generated xml file: /var/lib/jenkins/pytorch/test/test-reports/python-pytest/inductor.test_torchinductor/inductor.test_torchinductor-8e545cd72c8b5e67.xml -
2023-07-21T10:09:54.6618683Z ================= 200 passed, 15 skipped in 540.17s (0:09:00) ==================

inductor/test_cudagraph_trees - https://ossci-raw-job-status.s3.amazonaws.com/log/15231010643
-----------------------------------------------------------------------------------------------
2023-07-21T10:02:24.6532022Z - generated xml file: /var/lib/jenkins/pytorch/test/test-reports/python-pytest/inductor.test_cudagraph_trees/inductor.test_cudagraph_trees-f7714188e48cb169.xml -
2023-07-21T10:02:24.6532503Z =================== 40 passed, 4 skipped in 68.06s (0:01:08) ===================

inductor/test_cuda_repro - https://ossci-raw-job-status.s3.amazonaws.com/log/15231011023
-----------------------------------------------------------------------------------------------
2023-07-21T10:03:11.2690177Z - generated xml file: /var/lib/jenkins/pytorch/test/test-reports/python-pytest/inductor.test_cuda_repro/inductor.test_cuda_repro-96eee3cee967d647.xml -
2023-07-21T10:03:11.2690661Z ======================== 37 passed in 141.27s (0:02:21) ========================

inductor/test_smoke - https://ossci-raw-job-status.s3.amazonaws.com/log/15231010643
-----------------------------------------------------------------------------------------------
2023-07-21T10:02:36.7536820Z Running 3 items in this shard: test/inductor/test_smoke.py::SmokeTest::test_compile_decorator, test/inductor/test_smoke.py::SmokeTest::test_compile_invalid_options, test/inductor/test_smoke.py::SmokeTest::test_mlp
2023-07-21T10:02:36.7537635Z 
2023-07-21T10:02:36.7538029Z inductor/test_smoke.py::SmokeTest::test_compile_decorator PASSED [5.9028s] [ 33%]
2023-07-21T10:02:36.7538888Z inductor/test_smoke.py::SmokeTest::test_compile_invalid_options PASSED [0.0005s] [ 66%]
2023-07-21T10:02:36.7539712Z inductor/test_smoke.py::SmokeTest::test_mlp PASSED [1.9105s]             [100%]
2023-07-21T10:02:36.7540131Z 
2023-07-21T10:02:36.7540971Z - generated xml file: /var/lib/jenkins/pytorch/test/test-reports/python-pytest/inductor.test_smoke/inductor.test_smoke-a1c0f7674dec9417.xml -
```

**Comment by jataylo** [comment]
Hey @malfet would you be able to help review this PR to enable the cudagraph relevant inductor UTs 

There are a few failures that are unrelated to this PR and look to have now been disabled.

**Review by malfet — APPROVED** [review]

**Comment by kit1980** [comment]
This broke https://github.com/pytorch/pytorch/actions/runs/5731758643/job/15534573718 and others with

```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/inductor/test_cuda_repro.py", line 44, in <module>
    class CudaReproTests(TestCase):
  File "/var/lib/jenkins/workspace/test/inductor/test_cuda_repro.py", line 924, in CudaReproTests
    @skipIfRocm
NameError: name 'skipIfRocm' is not defined
```

**Comment by kit1980** [comment]
Looks like a landrace with https://github.com/pytorch/pytorch/pull/105439
I'll try to forward fix

**Comment by kit1980** [comment]
A forward fix attempt https://github.com/pytorch/pytorch/pull/106416

**Pull request closed without merging**
