### PR TITLE
Build Python module and tests CPU mode with Bazel in CI

### PR DESCRIPTION
**Pull request by dreiss**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#78221**

This can potentially catch issues like #77002 before they hit
Meta-internal CI, because Bazel is more strict about header visibility
than (our current setup of) CMake.

### CODE REVIEW

**Comment by dreiss** [comment]
CI should fail initially because #77002 is currently in viable/strict, which I'm based on.

**Review by malfet — APPROVED** [review]

**Comment by dreiss** [comment]
Okay, I finally got this version to fail with the proper error ("torch/csrc/Module.cpp:10:10: fatal error: ATen/cuda/CUDAConfig.h: No such file or directory"). https://github.com/pytorch/pytorch/runs/6596140899?check_suite_focus=true

Now I'm going to rebase, make sure it passes, and see what the perf impact is.

**Comment by dreiss** [comment]
@pytorchbot merge -g

please

**Pull request closed without merging**
