### PR TITLE
Hipify caffe2/core

### PR DESCRIPTION
**Pull request by bddppq**
@petrex @ashishfarmer @iotamudelta

### CODE REVIEW

**Comment by petrex** [comment]
thanks @bddppq 
Just want to make sure we are able to get pre-hipified files back when we need them; for platform-specific optimization/tweaking.

**Comment by bddppq** [comment]
@petrex Yes the build infra is still there. When we need special logic (so far we don't have any) we can add it back by simply dropping the file to caffe2/core and add an exclude rule in the hipify script.

**Pull request closed without merging**
