### PR TITLE
Rename elementwise_mean to mean

### LINKED ISSUE #12459: Rename elementwise_mean to size_average
cc @li-roy @weiyangfb @zou3519

### PR DESCRIPTION
**Pull request by ssnl**
Closes #12459

### CODE REVIEW

**Review by li-roy — APPROVED** [review]
Thanks for the PR.

I'm okay with this, my only concern is NLLLoss (and maybe some others?), which does some sort of weighted average. SizeAverage was never a good name for it, but other ones such as "Normalize" might also not be that good.

**Comment by SsnL** [comment]
@li-roy How about just `average`? :)

**Comment by li-roy** [comment]
Yeah, I like that

**Comment by SsnL** [comment]
This is BC breaking in C++ API (since I removed Reduction::ElementwiseMean) so cc @goldsborough

**Pull request closed without merging**
