### PR TITLE
clamping the return value of uniform.cdf() to [0..1]

### LINKED ISSUE #7532: torch.distributions.uniform.Uniform.cdf() can return negative values or values above one
## Issue description

`torch.distributions.uniform.Uniform.cdf()` can return negative values or values above one because it does not do a range check like `log_prob()` in the same class does.

Relevant code in `cdf()`:

https://github.com/pytorch/pytorch/blob/825c3ca2d6deb505b39b6b988d28f28a7bd15f4d/torch/distributions/uniform.py#L70-L74

Range checking in `log_prob()`:

https://github.com/pytorch/pytorch/blob/825c3ca2d6deb505b39b6b988d28f28a7bd15f4d/torch/distributions/uniform.py#L63-L68

I can provide a pull request based on the range checking as done in the `log_prob()` method of the same class (although `log_prob()` throws an exception with scalar arguments because of these range checks while `cdf()` accepts scalar arguments).

## Code example

```
import torch
from torch.distributions.uniform import Uniform
uniform = Uniform(1,2)
print uniform.cdf(0), uniform.cdf(5)
```
will give

```
tensor(-1.) tensor(4.)
```

## System Info
```
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Mac OSX 10.13.4
GCC version: Could not collect
CMake version: version 3.11.0

Python version: 2.7
Is CUDA available: No
CUDA runtime version: 9.1.128
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.14.2)
[pip] root-numpy (4.4.0)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] Could not collect

```

### PR DESCRIPTION
**Pull request by andreh7**
fixes #7532

### CODE REVIEW

**Comment by ezyang** [comment]
Can we get a test for this?

**Comment by andreh7** [comment]
@ezyang where would such a (unit) test have to go ?

**Comment by ezyang** [comment]
`test_distributions.py`

**Comment by andreh7** [comment]
thanks, I have added a corresponding test for arguments outside the boundaries for `uniform.cdf()` , similar to the test for `uniform.log_prob()` in 5f1f34c

**Review by fritzo — APPROVED** [review]
Thanks for fixing this!

**Review by ezyang — APPROVED** [review]

**Pull request merged**
