### PR TITLE
Test xla llvm_build_cache patch

### PR DESCRIPTION
**Pull request by yeounoh**
Addresses #80034

### CODE REVIEW

**Comment by JackCaoG** [comment]
PyTorch/XLA head is broken by a pytorch pr since test was disabled.. we need to reenable it ASAP. @seemethere @malfet. I will try to make a fix on xla end.. or we can revert offending pytorch pr https://github.com/pytorch/pytorch/pull/80334

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Can we disable the offending test instead? Also, do we know what have caused the CI outage?

**Comment by JackCaoG** [comment]
@malfet It is the pytorch/xla build itself failed due to the change to the `native_function.yaml`

**Comment by JackCaoG** [comment]
Let me do a quick test locally.. If I can make a quick change to unblock the build by removing the `kl_div` lowering on pytorch/xla side I will force a merge

**Comment by malfet** [comment]
@JackCaoG sorry, I were referring to the original issue (when llvm could not be downloaded all of sudden)

**Comment by JackCaoG** [comment]
The llvm issue should be fixed, we merged https://github.com/pytorch/xla/commit/8f0f0d3ea0818f2fc8c7a81a17d60fdf95c956d0 and @yeounoh  has tested the fix(he pointed this pr to his llvm pr). LLVM download is part of building the tensorflow. PyTorch/XLA builds the xla part of the tensorflow. I don't think we can disable that.

**Comment by JackCaoG** [comment]
try to fix the build issue in https://github.com/pytorch/xla/issues/3682

**Comment by JackCaoG** [comment]
@malfet There are actually one more breaking pr  https://github.com/pytorch/pytorch/commit/0a5123a75265a0a62b38873aad66b13144e8a2d8 I am trying to hot fix. https://github.com/pytorch/pytorch/pull/74234 might also be breaking I need to verify. I will let you know when I am confident that head is green again.

**Comment by malfet** [comment]
@JackCaoG still does not pass CI, reverting

**Comment by JackCaoG** [comment]
@malfet I think we need to wait for xla hash to be updated. Well I guess we can just wait for today(so bot will auto update hash) and reland this. If that doesn't happen I can manually update xla hash in this pr.

**Comment by JackCaoG** [comment]
@yeounoh Can you reopen this pr, rebase, update hash in https://github.com/pytorch/pytorch/blob/master/.github/ci_commit_pins/xla.txt to latest xla commit? We should try to reenable the ci. (not sure why xla hash update stop working)

**Comment by yeounoh** [comment]
Created a new [PR](https://github.com/pytorch/pytorch/pull/81070) with the latest XLA hash.

**Comment by yeounoh** [comment]
It's green again, https://github.com/pytorch/pytorch/pull/81070#issuecomment-1178624356

**Comment by yeounoh** [comment]
Hi @malfet , do you know if the nightly hash updater is enabled or blocked? cc @seemethere @JackCaoG

**Pull request closed without merging**
