### PR TITLE
[pytree] cpp pytree functionality

### PR DESCRIPTION
**Pull request by IvanKobzarev**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #75822

### CODE REVIEW

**Comment by suo** [comment]
hey @Chillee, @zou3519: want to take a look at this from the functorch-pytree perspective? If it looks good to you, @IvanKobzarev will try to integrate

**Comment by ezyang** [comment]
I see this is directly done as an implementation inside pytorch itself. In the original issue, there was some discussion about whether or not pytree could be done in a small standalone library that lots of folks in the ecosystem could use. Do you think this is a goal worth pursuing?

**Comment by Chillee** [comment]
Does this support custom pytrees? That's fairly important for the functorch use cases.

**Comment by IvanKobzarev** [comment]
@ezyang ,
> Does this support custom pytrees? That's fairly important for the functorch use cases.

No, custom types are not supported at the moment. 

It was mostly designed for the purpose of embedded runtime, where main requirements were:
 -  C++ API to represent containers in the way as they work in python/torchscript
 -  TreeSpec is Serializable to be part of the model meta data

I will think how to support custom types. 

I checked vmap and torch.fx use cases.
Could you please point where in functorch it is used and requires custom types. What are other use cases that I miss?

Do you know about some places where this functionality can be needed by C++ side?

> whether or not pytree could be done in a small standalone library

Yes, we can do it as a separate library. 
In that case, do you think it should be done in a separate repository?

**Comment by zou3519** [comment]
> I checked vmap and torch.fx use cases.
> Could you please point where in functorch it is used and requires custom types.

There isn't a specific place in the codebase we use custom types, but:
- torch.utils._pytree is a slow python-only implementation of JAX's [pytrees](https://jax.readthedocs.io/en/latest/pytrees.html#extending-pytrees)
- JAX's pytree allow [users to extend](https://jax.readthedocs.io/en/latest/pytrees.html#extending-pytrees) the set of Python objects that can be considered to be PyTrees. A user may come along with their own class type and want to register it as a pytree.

**Comment by ezyang** [comment]
This PR is still legit but I don't know how we are pushing it forward

**Pull request closed without merging**
