### PR TITLE
Try seeding individual foreach tests

### PR DESCRIPTION
**Pull request by janeyx99**
A first easy attempt to deflake foreach

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128220

### CODE REVIEW

**Review by ZainRizvi — APPROVED** [review]

**Review by crcrpar — APPROVED** [review]
lgtm but curious to know the motivation

**Review by huydhn — APPROVED** [review]

**Comment by janeyx99** [comment]
@crcrpar this is just the easiest thing to do to try to see if this would deflake the recently very flaky foreach tests :/

**Comment by clee2000** [comment]
Heads up I don't think this worked https://hud.pytorch.org/pytorch/pytorch/commit/e3093849e5530dbb93a35462d3fd248a2dd7efe0 https://github.com/pytorch/pytorch/actions/runs/9549935522/job/26322924851

**Comment by janeyx99** [comment]
ah sigh...i had suspected this wasn't going to fix the whole thing. I'll look into it.

**Pull request closed without merging**
