### PR TITLE
[ci] Save various json files from test infra into folder

### PR DESCRIPTION
**Pull request by clee2000**
We pull a lot of files from https://github.com/pytorch/test-infra/blob/generated-stats/stats and name them separately when we add them to the artifacts in the build, so stick them in a folder and just add that instead.

Slow test and disabled test jsons remain as they were since they are pulled during the test step and do not need to be included in the artifacts during build since they are not used for sharding.

Sanity checked that test times could be found for linux, mac, windows, and rocm.

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM! I notice that https://github.com/pytorch/pytorch/tree/main/.additional_ci_files shows up on main, is that accidentally added?

**Comment by huydhn** [comment]
> LGTM! I notice that https://github.com/pytorch/pytorch/tree/main/.additional_ci_files shows up on main, is that accidentally added?

FYI, @malfet has removed them in https://github.com/pytorch/pytorch/pull/111668

**Review by ZainRizvi — APPROVED** [review]

**Comment by clee2000** [comment]
> > LGTM! I notice that https://github.com/pytorch/pytorch/tree/main/.additional_ci_files shows up on main, is that accidentally added?
> 
> FYI, @malfet has removed them in #111668

Oops that was an accident, branch switched caused gitignore to change and they got added

**Pull request closed without merging**
