### PR TITLE
[CircleCI] Store build artifacts for python docs

### PR DESCRIPTION
**Pull request by ShawnZhong**
This PR allows the build artifacts for python docs to be stored on CircieCI, which helps the reviewer to preview doc changes before merging. 

The artifacts can be found in the [`ARTIFACTS` tab](  https://app.circleci.com/pipelines/github/pytorch/pytorch/162986/workflows/a969f256-3243-414f-8a02-1234b9dac149/jobs/5320907/artifacts) of the test **pytorch_cpp_doc_push**, and the website is served at https://5320907-65600975-gh.circle-artifacts.com/0/docs/index.html

This PR is inspired by @rgommers's comment under https://github.com/pytorch/pytorch/pull/37419#issuecomment-621420500

> There's a CircleCI job pytorch_python_doc_push that builds the docs, however it doesn't store any artifacts for PRs. Controlled by .circleci/scripts/python_doc_push_script.sh. I think that's the only doc build (?). Not sure why it doesn't store the artifacts, that would be useful.

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Nice, thanks @ShawnZhong!

This works, I have a small possible improvement suggestion:
```
    - store_artifacts: 
        path: ~/workspace/build_artifacts/master
        destination: docs
```
should change the full path of all files under the artifacts tab from `~/workspace/build_artifacts/master/*` to `docs/*` so it's easier to read.

**Review by rgommers — APPROVED** [review]
Looks great, good to merge.

**Comment by ezyang** [comment]
This is nice, I will merge it. However, it is not very discoverable right now. Is there some way we can give more information to users when they modify docs that their docs are viewable at some spot?

@kostmo maybe this is something Dr. CI could do?

**Comment by rgommers** [comment]
> it is not very discoverable right now. Is there some way we can give more information to users when they modify docs that their docs are viewable at some spot?

SciPy has a little GitHub app (https://github.com/apps/circleci-artifacts-redirector/) that adds a direct link as a separate CI result after the docs build job has completed:

image

It does require some permissions to install on this repo of course, not sure if that's desirable.

Otherwise it may be a matter of just teaching people. I'm personally not a fan of posting a comment after each CI run, that's way too noisy.

**Comment by ezyang** [comment]
Unfortunately if this adds a link for every circleci artifact, we'll probably need to do some tweaking, as I think we do a lot of these right now

**Comment by rgommers** [comment]
> Unfortunately if this adds a link for every circleci artifact, we'll probably need to do some tweaking, as I think we do a lot of these right now

Ah yes, SciPy uses CircleCI only to build the docs. That app may need a tweak to work here, to take into account the job name. And since it's a Heroku app, it may need to be cloned and tweaked for PyTorch. Too much trouble at this point probably.

Permissions not too bad:
image

**Comment by kostmo** [comment]
> [...] Is there some way we can give more information to users when they modify docs that their docs are viewable at some spot?
> 
> @kostmo maybe this is something Dr. CI could do?

@ezyang , yes, sounds doable.  The necessary ingredients would be associations of file glob patterns with jobs names, to determine which job artifacts link(s) we should surface through Dr. CI based on the files modified in the diff.

We could either store these associations as a text file in the pytorch repo or hard-code them in the Dr. CI app.

**Comment by rgommers** [comment]
> The necessary ingredients would be associations of file glob patterns with jobs names, to determine which job artifacts link(s)

- Job name: `pytorch_python_doc_push`
- Artifact link: `https://xxxxxxx-xxxxxxxx-gh.circle-artifacts.com/0/docs/index.html`

**Comment by kostmo** [comment]
> > The necessary ingredients would be associations of file glob patterns with jobs names, to determine which job artifacts link(s)
> 
> * Job name: `pytorch_python_doc_push`
> * Artifact link: `https://xxxxxxx-xxxxxxxx-gh.circle-artifacts.com/0/docs/index.html`

Is there a simple way to determine which files edited constitute changes to documentation?  Is it as straightforward as any file that ends in the `*.rst` extension?  Or perhaps any file underneath a certain directory in the repo?

**Comment by ShawnZhong** [comment]
> Is there a simple way to determine which files edited constitute changes to documentation? Is it as straightforward as any file that ends in the *.rst extension? Or perhaps any file underneath a certain directory in the repo?

Like all the *.rst files under `docs` and all the *.py files under `torch`?

**Comment by rgommers** [comment]
I don't think there's a good way to do that. Touching `.py` files may or may not result in changes to the docs (docstrings get extracted), and can result in changes in multiple places in the docs (e.g. in the autosummary table and in the page for the function(s) touched).

I'd just always link to the top-level `index.html` and let the reviewer figure it out. Saving an extra couple of clicks here isn't worth a complicated and possible incomplete link-generation exercise imho.

**Comment by ezyang** [comment]
Yes, I agree. If it rolls into an existing comment the CI bot makes, it's NBD.

**Pull request closed without merging**
