### PR TITLE
clang8=>clang9 in CI jobs

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by Skylion007** [comment]
@cyyever @malfet been working on a similar PR for a month: https://github.com/pytorch/pytorch/pull/105260

**Comment by malfet** [comment]
I have it almost done except for one functorch failure, which I'm inclined to just skip

**Review by malfet — CHANGES_REQUESTED** [review]
First of all, please don't just `sed` (i.e. there shouldn't be any changes in mocks)

Also, it will fail unless you do few other minor changes

**Comment by cyyever** [comment]
@malfet Still have some jobs to upgrade after your work.

**Review by malfet — APPROVED** [review]
LGTM, though I think XLA renaming is somewhat misguided, as it uses XLA's docker container, rather than ours

**Comment by cyyever** [comment]
@malfet  failed to "docker push 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-focal-py3-clang9-android-ndk-r19c:7fb812a19eedbb32eb8308292cbf52d0ef509724"

**Comment by cyyever** [comment]
@malfet I can't push the docker image in tests due to security reasons, see pytorch/builder#1174. That means merging  by force is required.

**Pull request closed without merging**
