### PR TITLE
allow nn.Sequential to take multiple inputs

### PR DESCRIPTION
**Pull request by zasdfgbnm**
The number of inputs would be the same as the first module

### CODE REVIEW

**Comment by soumith** [comment]
looks good. Can you add a test and this is good to go.

**Comment by fmassa** [comment]
If I understand correctly, only the first layer would accept multiple inputs, while all the other layers would receive a tuple of a single element as input (which can in turn be a tuple), is that right?

I'm not sure this behavior is very natural. Actually, I'd say it's more consistent to always take a tuple and return a tuple (which is the current behavior btw).

Ultimately, having anything that takes more than one input depends quite a lot on the application, so I'd rather not have `nn.Sequential` special-case for one use-case.

Not sure what the others think about it.

**Comment by zasdfgbnm** [comment]
@fmassa Yes, you are right. All layers except the first are assumed to to take a single input.

There are some ambiguities for hidden layer. For example, if the first layer returns `(a, b)`, it is not clear to `nn.Sequential` whether we should call the second layer by `layer2(a, b)` or `layer2((a,b))`. In this case, we are manually enforcing the second way.

For the first layer, allowing multiple inputs is just a simple trick to make it a bit more convenient for user codes.

**Comment by fmassa** [comment]
Given what I mentioned before and this (unintuitive) behavior, I'm not sure I'd vote for be merging this PR.

@soumith what do you think?

**Review by soumith — CHANGES_REQUESTED** [review]
putting a requested changes around francisco's concerns.

Defining the semantics of intermediate modules is a bit tricky.

My feeling is, just like inputs are unpacked, all intermediate outputs are implicitly unpacked and given to the next module.

For example:

```

for module in _modules:
    if type(inputs) == tuple:
       inputs = module(*inputs)
    else:
       inputs = module(inputs)
```

But needs discussion.

**Comment by yf225** [comment]
@soumith @fmassa Any thoughts on this PR?

**Comment by apaszke** [comment]
I don't think this is a good extension for `nn.Sequential`. It surely complicates the types we accept, and I don't think that's worth it.

**Comment by zasdfgbnm** [comment]
If there are more down vote than up vote, feel free to close this. @soumith

**Pull request closed without merging**
