### PR TITLE
[lint] fix lint broken by #131912

### PR DESCRIPTION
**Pull request by nmacchioni**
lint

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by nmacchioni** [comment]
@zhxchen17 can you stamp + merge this, your PR https://github.com/pytorch/pytorch/pull/131912 broke the linter (signal was missed on PR, coincidentally the linter was broken by a different PR at the same time so it showed up as broken on trunk)

**Review by aaronenyeshi — APPROVED** [review]
LGTM

**Pull request closed without merging**
