### PR TITLE
[nnc] Updated sliceHead to do inplace mutation

### PR DESCRIPTION
**Pull request by navahgar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #63532
* __->__ #63531

Differential Revision: [D30412183](https://our.internmc.facebook.com/intern/diff/D30412183)

### CODE REVIEW

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30412183).

**Comment by navahgar** [comment]
I was looking to remove the `tail` parameter from this interface, but that seems to lead to a weird situation when the input `factor` results in the case of `tail` loop becoming empty (and hence set to `nullptr`).

**Review by ZolotukhinM — APPROVED** [review]
LGTM!

> I was looking to remove the tail parameter from this interface, but that seems to lead to a weird situation when the input factor results in the case of tail loop becoming empty (and hence set to nullptr).

Isn't `tail` always non-null in the current implementation? Judging from these two lines:
```
f->set_start(head_end);
*tail = f;
```

**Comment by navahgar** [comment]
> Isn't `tail` always non-null in the current implementation? Judging from these two lines:
> 
> ```
> f->set_start(head_end);
> *tail = f;
> ```

The problem is the case above in that function:
```
    if (factor >= size_val) {
      *head = f;
      *tail = nullptr;
      return;
    }
```

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30412183).

**Pull request closed without merging**
