### PR TITLE
Enable QNNPACK for POWER/VSX (ppc64le)

### PR DESCRIPTION
**Pull request by rafaelcfsousa**
This PR enables QNNPACK for POWER/VSX (ppc64le).

Today, when one tries to execute a quantized model with Convolutional Layers and/or Fully Connected Layers on any POWER architecture, the inference fails and the following error message is shown:

```
 RuntimeError: Didn't find engine for operation quantized::linear_prepack NoQEngine
```

This PR adds a QEngine (QNNPACK) for POWER to allow the execution of models with the layers mentioned above using either Dynamic or Static quantization.

See below the list of operators that have been added to this PR:
- q8conv (Convolution)
- q8dwconv (Depthwise Convolution)
- q8gavgpool (Global Average Pooling)
- q8gemm (GEMM)
- q8vadd
- u8clamp (ReLU/ReLu6)
- u8maxpool (Max Pooling)
- u8rmax
- x8zip (Channel Shuffle)

The operators above have been tested on POWER8, POWER9 and POWER10 through the unittests available in QNNPACK and also with the following computer vision models:
- AlexNet
- DensetNet121 and 201
- InceptionV3
- ResNet18 and 50
- ShuffleNetV2
- SqueezeNet
- VGG11 and 19

Thanks.

### CODE REVIEW

**Comment by rafaelcfsousa** [comment]
I have just submitted the `Missing Contributor License Agreement`

**Comment by kimishpatel** [comment]
This is a pretty big PR so will likely take a while to review. But at a high level I want to highlight a few things.

- We might be moving away from QNNPACK and use XNNPACK for quantized inference. Thus we may deprecate and/or remove qnnpack entirely.
- For the reasons mentioned above and the fact that QNNPACK is really intended for mobile inference, I am not sure if QNNPACK is the right place to add support of POWERPC.
- One alternative might be "clone" QNNPACK to something like POWERPCPACK or such, where support for vectorized powerpc implementation for quantized ops is added. This would be a separate repo and dependency on that can be added to pytorch, conditionally. Conditionally because we can add a separate qengine similar to qnnpack and compile the code only when support for this engine is requested. However there are few consequences to this: 1) we need to add separate qengine 2) because of 1 we have to make a lot of changes to pytorch codebase to dispatch ops to this new qengine for optimized ops when possible. 3) alternatively, and this might be in general spirit of how new backend specific optimizations are added for quantized models, we can do 3.a) have POWEPCPACK as separate repo 3.b) register new quantized ops such as "quantized_powerpc::conv2d", "quantized_powerpc::linear" etc. This can also be done out-of-tree while adding pytorch as dependency. 3.c) subsequently do a graph rewrite pass that replace "quantized::conv2d" with "quantized_powerpc::conv2d" and so on.
- Note that 3 is cleaner in the sense that it lives entirely out-of-tree of pytorch and removes any dependency of adding code to pytorch. Generally for different quantization backends, we are trying approaches which dont require making knowledge of backends, such as fbgemm/qnnpack even though they are there today, explicit in pytorch repo. This way backend specific optimization can live independent of pytorch.

cc: @jerryzh168 and @vkuzo for any inputs.

**Comment by rafaelcfsousa** [comment]
About XNNPACK, if I enabled this library for POWER, would it be possible to use it without QNNPACK enabled? I'm not sure, but at first glance, it looks like XNNPACK is only enabled if and only if QNNPACK is also enabled. Am I correct?

(the `#ifdef` directives of XNNPACK are defined within USE_PYTORCH_QNNPACK)

**Comment by RajalakshmiSR** [comment]
> * We might be moving away from QNNPACK and use XNNPACK for quantized inference. Thus we may deprecate and/or remove qnnpack entirely.

@kimishpatel Do you have any timeline to move to XNNPACK?

**Comment by RajalakshmiSR** [comment]
> @kimishpatel Do you have any timeline to move to XNNPACK?

@kimishpatel Do you have any timeline to move to XNNPACK?

**Comment by kimishpatel** [comment]
> > @kimishpatel Do you have any timeline to move to XNNPACK?
> 
> @kimishpatel Do you have any timeline to move to XNNPACK?

Hi. Sorry for the late response. Missed my inbox. It is going to be a slow process, but we have moved to using XNNPACK for some ops already. That is if we are using symmetric quantization. cc: @digantdesai

**Comment by RajalakshmiSR** [comment]
@kimishpatel We will plan to work on XNNPACK support for PowerPC. Meanwhile, adding this patch will help applications that use quantization till we get a PyTorch release with XNNPACK PowerPC support.

**Pull request closed without merging**
