### PR TITLE
empty input

### PR DESCRIPTION
**Pull request by cccclai**
Summary:
asr model in executorch is failing and looks like we miss this case
```
def g():
    return torch.zeros(1, 2)

exported_module = torch._export.capture_pre_autograd_graph(g, ())
```

Test Plan:
```
 buck run mode/dev-nosan //pye/model_inventory/asr_models/milan_dictation:export_models -- --dqlinear_qconfig_flavor symmetric_xnnpack  --output_path /data/sandcastle/boxes/fbsource/fbcode/pye/model_inventory/asr_models/milan_dictation/asr.pte
```

re-launch skycastle job
```
chenlai@168417.od /data/sandcastle/boxes/fbsource/fbcode (071a6201d)]$ arc skycastle schedule //tools/skycastle/workflows2/pytorch_edge/executorch_transcribe_bin.sky:main

19:51:41.081 [INFO] Invocation ID: l8BuIotf
19:51:41.084 [INFO] Version: 55680ae1ec0746ceecae3459f3a40c00378ec9cf
19:51:41.084 [INFO] Protocol: 8
19:51:41.084 [INFO] Build date: 20231204_035433
19:51:41.088 [INFO] Debug log: /var/tmp/skycastle/invocations/1701748301_l8BuIotf/logs/skycastle.log
19:51:41.516 [WARN] Add JVM option for faster UTF-8 validation. --add-opens java.base/java.lang=ALL-UNNAMED
19:51:42.869 [INFO] Feature 'use_new_thrift_over_interngraph_client' evaluated to: false
19:51:47.667 [INFO] Successfully scheduled workflow

Success!
    Duration: 6 secs
    Invocation ID: l8BuIotf
    Debug logs:
        /var/tmp/skycastle/invocations/1701748301_l8BuIotf/logs/skycastle.log
        /var/tmp/skycastle/invocations/1701748301_l8BuIotf/logs/starlark.log
    Workflow run ID: 58546795169668403
    Workflow run URL: https://www.internalfb.com/sandcastle/workflow/58546795169668403
    Workflow Name: pytorch-edge-run-executorch-transcribe-bin
    Workflow Oncall: executorch
    Execution Platform: sandcastle
    Execution Job(s): https://www.internalfb.com/intern/sandcastle/job/36028798147194184/
    Sandcastle nonce: 4258238068229021
```

Reviewed By: tugsbayasgalan, ydwu4

Differential Revision: D51837625

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @kiukchung @lucasllc

### CODE REVIEW

**Review by tugsbayasgalan — APPROVED** [review]

**Comment by cccclai** [comment]
hmmm somehow I mess up the stack...will try to push another commit

**Review by zhxchen17 — CHANGES_REQUESTED** [review]
hmm sorry the changeset still doesn't look correct. @tugsbayasgalan why you approved this lol.

**Review by zhxchen17 — APPROVED** [review]

**Review by malfet — APPROVED** [review]
LGTM (not sure why I'm asked to review this one though)

**Comment by zhxchen17** [comment]
I guess this PR is redundant after we land https://github.com/pytorch/pytorch/pull/115280 (Sorry I thought your PR will be landed first so I stamped this, but I didn't tell you I have a similar PR from last week as well and I'm landing it to fix some other issues as well, thanks a lot anyway!)

**Comment by cccclai** [comment]
abandon

**Pull request closed without merging**
