### PR TITLE
Correctly use real boolean operators, not bitwise in shape guard prints

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #113927

Fixes https://github.com/pytorch/pytorch/issues/113875

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by jon-chuang** [comment]
What does the guard look like now?

**Comment by ezyang** [comment]
```
not (Eq(L['x'].size()[0], 5) and Eq(L['x'].size()[2], 2) and Eq(L['x'].size()[3], 3))
```

**Review by voznesenskym — APPROVED** [review]

**Pull request closed without merging**
