### PR TITLE
Removed direct doc formatting

### LINKED ISSUE #76034: python3 -OO option does not work
### 🐛 Describe the bug

My scripts depend on PyTorch, although I do not use it at the moment. 
When I try optimization options, the **python3 -OO ...** fails but **python3 -O ...** is fine.
This was checked on MacOS and RedHat 7, Anaconda environment 4.12, python 3.9.12, **pytorch 1.10.2**.
The output:
```
python3 -OO my_script
Traceback (most recent call last):
 ...................................
    import torch as th
  File "/Users/albert/miniconda3/envs/qu/lib/python3.9/site-packages/torch/__init__.py", line 643, in <module>
    from .functional import *  # noqa: F403
  File "/Users/albert/miniconda3/envs/qu/lib/python3.9/site-packages/torch/functional.py", line 6, in <module>
    import torch.nn.functional as F
  File "/Users/albert/miniconda3/envs/qu/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/albert/miniconda3/envs/qu/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/Users/albert/miniconda3/envs/qu/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 6, in <module>
    from .. import functional as F
  File "/Users/albert/miniconda3/envs/qu/lib/python3.9/site-packages/torch/nn/functional.py", line 2231, in <module>
    embedding_bag.__doc__ = embedding_bag.__doc__.format(**reproducibility_notes)
AttributeError: 'NoneType' object has no attribute 'format'
```

### Versions

Collecting environment information...
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] torch==1.10.2
[conda] blas                      1.0                         mkl
[conda] libblas                   3.9.0              13_osx64_mkl    conda-forge
[conda] libcblas                  3.9.0              13_osx64_mkl    conda-forge
[conda] liblapack                 3.9.0              13_osx64_mkl    conda-forge
[conda] mkl                       2022.0.0           hecd8cb5_105
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.22.2           py39h9d9ce41_0    conda-forge
[conda] pytorch                   1.10.2                  py3.9_0    pytorch

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

### PR DESCRIPTION
**Pull request by vitrioil**
Fixes #76034

This does not make python remove all `__doc__` because in some places `__doc__` is assigned to a string.

Example:
https://github.com/pytorch/pytorch/blob/04b3313379712098183dfe5bea002a5e43b5af48/torch/nn/modules/conv.py#L174-L233

Since there are quite a few of these, I will add all of them together in this PR later. (Basically still a lot of docstring will persist even with `-OO` enabled.)

### CODE REVIEW

**Review by mrshenli — COMMENTED** [review]
Changes in `distributed/rpc` folder LGTM.

**Review by albanD — APPROVED** [review]
Thanks for fixing this!

**Comment by albanD** [comment]
> Basically still a lot of docstring will persist even with -OO enabled.

I would be curious to know if there is a significant perf hit with leaving these?

**Pull request closed without merging**
