### PR TITLE
Fix submodule naming in ONNX quantized test

### PR DESCRIPTION
**Pull request by dreiss**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #60242 Swich qconv serialization to format version 3
* #60241 Introduce quantized convolution serialization format 3
* #60576 Remove unnecessary temporary fix in quant bc test
* **#60240 Fix submodule naming in ONNX quantized test**

Summary:
This is a conv, not an fc.

Test Plan:
CI

Differential Revision: [D29349782](https://our.internmc.facebook.com/intern/diff/D29349782)

### CODE REVIEW

**Review by vkuzo — APPROVED** [review]

**Comment by dreiss** [comment]
@dreiss has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29349782).

**Comment by garymm** [comment]
@dreiss would you please merge this?

**Review by thiagocrepaldi — APPROVED** [review]

**Comment by thiagocrepaldi** [comment]
@BowenBao @garymm This PR is agains master and was already approved by Facebook. Who to mention to get it merged?

**Comment by garymm** [comment]
I think @dreiss probably doesn't care about this anymore. Closing to get it out of our "needs review" query results.
dreiss feel free to re-open if you want.

**Pull request closed without merging**
