### PR TITLE
Hipify fixes for a successful DeepSpeed build 

### PR DESCRIPTION
**Pull request by rraminen**
These commits are required to build DeepSpeed on ROCm without the hipify errors.

https://github.com/ROCmSoftwarePlatform/pytorch/commit/a41829d9edd576775b68ca330799158960a8b766
https://github.com/ROCmSoftwarePlatform/pytorch/commit/663c7184629a0a721df540b74bcb78b1a66d0310

cc: @jeffdaily

### CODE REVIEW

**Review by jeffdaily — CHANGES_REQUESTED** [review]
@rraminen please fix the lint errors reported by CI.  Otherwise LGTM.

**Review by jeffdaily — APPROVED** [review]

**Comment by albanD** [comment]
The xla failure is unrelated right?
It would be best to do a quick rebase to make sure we have fresh CI (current one is a week old) before merging.

**Comment by rraminen** [comment]
Triggered a new CI

**Review by pruthvistony — APPROVED** [review]
LGTM

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
