### PR TITLE
add complex support to `reciprocal_cuda` kernel

### PR DESCRIPTION
**Pull request by kshitij12345**
@dylanbespalko @anjali411 

Not sure if the test should be added to `test_torch` or `test_complex`.

### CODE REVIEW

**Comment by dylanbespalko** [comment]
Great job, I would put your test in test_complex. #36029 discusses blockers that prevent us from implementing unit tests for complex numbers in test_torch.py.

**Comment by anjali411** [comment]
great job @kshitij12345 I agree with Dylan, however in this case I don't think there are any blockers to adding test(s) to test_torch.py. did you run into any issue?

**Comment by kshitij12345** [comment]
@anjali411
Even the current `test_reciprocal` checks for both `cpu and cuda`. The existing tests in `test_complex` were only on `cpu` so have kept it that way.

Also note that, I tried the following test in `test_torch.py`  under `TestTorchDeviceType` and it passed.

```python
    @unittest.skipIf(not TEST_NUMPY, "Numpy not found")
    @dtypes(torch.complex64, torch.complex128)
    def test_reciprocal_complex(self, device, dtype):
        def reciprocal_fn(device, dtype):
            x = torch.randn(10, 10, dtype=dtype, device=device)
            if device != 'cpu':
                expected = np.reciprocal(x.cpu().numpy())
            else:
                expected = np.reciprocal(x.numpy())
            actual = torch.reciprocal(x)
            self.assertEqual(actual, torch.from_numpy(expected))

        reciprocal_fn(device, dtype)
```

So we can have it either way.

@dylanbespalko @anjali411 Let me know where it should belong

**Comment by anjali411** [comment]
> @anjali411
> Even the current `test_reciprocal` checks for both `cpu and cuda`. The existing tests in `test_complex` were only on `cpu` so have kept it that way.
> 
> Also note that, I tried the following test in `test_torch.py` under `TestTorchDeviceType` and it passed.
> 
> ```python
>     @unittest.skipIf(not TEST_NUMPY, "Numpy not found")
>     @dtypes(torch.complex64, torch.complex128)
>     def test_reciprocal_complex(self, device, dtype):
>         def reciprocal_fn(device, dtype):
>             x = torch.randn(10, 10, dtype=dtype, device=device)
>             if device != 'cpu':
>                 expected = np.reciprocal(x.cpu().numpy())
>             else:
>                 expected = np.reciprocal(x.numpy())
>             actual = torch.reciprocal(x)
>             self.assertEqual(actual, torch.from_numpy(expected))
> 
>         reciprocal_fn(device, dtype)
> ```
> 
> So we can have it either way.
> 
> @dylanbespalko @anjali411 Let me know where it should belong

we can probably add this test in the class where other numpy comparison tests are being added. cc. @mruberry 
I think you should also add tests [here](https://github.com/pytorch/pytorch/blob/3e3498cf03b6ea7becf34597eea7ff350d718f95/test/test_torch.py#L12772) and [here](https://github.com/pytorch/pytorch/blob/3e3498cf03b6ea7becf34597eea7ff350d718f95/test/test_torch.py#L14827).

**Comment by mruberry** [comment]
Definitely update test_torch.py, not test_complex.py. There is an existing reciprocal test [here](https://github.com/pytorch/pytorch/blob/3e3498cf03b6ea7becf34597eea7ff350d718f95/test/test_torch.py#L14756) that can be updated, too. The new test might look like this:

```
@unittest.skipIf(not TEST_NUMPY, "NumPy not found")
@dtypes(torch.float, torch.double, torch.complex64, torch.complex128)
def test_reciprocal(self, device, dtype):
  t = torch.randn(10, 10, dtype=dtype, device=device)
  expected = torch.from_numpy(np.reciprocal(t.cpu().numpy()))
  actual = torch.reciprocal(x).cpu()
  self.assertEqual(expected, actual)
```

You don't need an internal helper function or a test for whether you're working on CPU or not. (The correct test would be `if self.device_type != 'cpu'`.)

@anjali411 is correct you can also extend the existing tests that rely (internally) on reciprocal to run on both CPU and CUDA and to use complex dtypes. That'd be cool. 

In addition to the above test, you should add an additional test for extremal values like -inf, 0, inf, and NaN. That test would go next to the above and look like this:

```
@unittest.skipIf(not TEST_NUMPY, "NumPy not found")
@dtypes(torch.complex64, torch.complex128)
def test_reciprocal_complex_extremal(self, device, dtype):
  vals = (complex(float('inf'), float('inf')), ...)  # populate some interesting extremal values here
  self._np_compare('reciprocal', vals, device, dtype)
```

`_np_compare` is a helper defined [here](https://github.com/pytorch/pytorch/blob/3e3498cf03b6ea7becf34597eea7ff350d718f95/test/test_torch.py#L5854). 

Testing aside, I'm a little surprised we have a kernel for reciprocal instead of just using division to implement it. Is a custom reciprocal kernel really faster than just performing the division on CUDA?

**Comment by mruberry** [comment]
> Great job, I would put your test in test_complex. #36029 discusses blockers that prevent us from implementing unit tests for complex numbers in test_torch.py.

I don't think there are any blockers? If anything we should move what's in test_complex.py to test_torch.py.

**Comment by kshitij12345** [comment]
```python
import numpy as np
vals = (
    # Inf and Zeros
    complex(float('inf'), float('inf')), 
    complex(float('inf'), 0.),
    complex(0., float('inf')),
    complex(0., 0.),

    # Nans and Zeros
    complex(float('nan'), 0.),
    complex(0., float('nan')),
    complex(float('nan'), float('nan')),

    # Inf and Nans
    complex(float('nan'), float('inf')),
    complex(float('inf'), float('nan')),

    # Extremal and Normal Number
    complex(float('nan'), 2.0),
    complex(float('inf'), 2.0),
    complex(2.0, float('nan')),
    complex(2.0, float('inf')),
    complex(2.0, 0.0),
    complex(0.0, 2.0))
vals_arr = np.array(vals)
print(1/vals_arr)
```

Output:
```
[nan+nanj 0. +0.j  0. -0.j  inf+nanj nan+nanj nan+nanj nan+nanj nan+nanj
 nan+nanj nan+nanj 0. +0.j  nan+nanj 0. -0.j  0.5+0.j  0. -0.5j]
```

Seems odd?

**Comment by mruberry** [comment]
Yikes! That is a great set of extremal values, @kshitij12345! Nice work.

Is that so weird? What if you work out 1 / (inf + infi) by hand?

**Comment by kshitij12345** [comment]
The case which I found odd was `1/complex(float('inf'), 2.0) = 0` or `1/complex(2.0, float('inf')) = 0` . Though it must be correct. Will have to sit on it :)

**Comment by mruberry** [comment]
> The case which I found odd was `1/complex(float('inf'), 2.0) = 0` or `1/complex(2.0, float('inf')) = 0` . Though it must be correct. Will have to sit on it :)

I would not assume it's correct. NumPy has bugs like any other project, and I agree those look strange (although I guess there is a mathematical interpretation where it's correct). NumPy's just using C++ here, though. For example, 

```
int main() {
  const auto inf = std::numeric_limits<double>::infinity();
  std::complex<double> a = 1 + 0j;
  std::complex<double> b = inf + 2i;
  std::cout << a / b << std::endl;
}
```

prints `(0,0)`. PyTorch should be using C++ for this computation, too.

**Comment by anjali411** [comment]
> The case which I found odd was `1/complex(float('inf'), 2.0) = 0` or `1/complex(2.0, float('inf')) = 0` . Though it must be correct. Will have to sit on it :)

This looks fine to me. If you write it in the form (a-bj)/(a^2 + b^2) and divide it by a^2 for the first case and b^2 for the second, using limit it equals 0. 

And all the other results also look fine to me except 1/ complex(0., 0.) = inf+nanj. I would have expected both real and imags to be nan.

**Comment by kshitij12345** [comment]
@mruberry @anjali411 Thanks. It makes more sense now.

**Comment by kshitij12345** [comment]
The error on Windows CI looks real. 

@peterjc123 Can you please check if there is anything suspicious in the changes that is causing this? Below is the suspicious part of the change.

Thanks.

https://github.com/pytorch/pytorch/blob/76362408dfde47545781b5abbfe894ea63646779/aten/src/ATen/native/cuda/UnaryFractionKernels.cu#L65-L81

**Comment by peterjc123** [comment]
> The error on Windows CI looks real.
> 
> @peterjc123 Can you please check if there is anything suspicious in the changes that is causing this? I can't test the change as I don't have a Windows System on me. Below is the suspicious part of the change.
> 
> Thanks.
> 
> https://github.com/pytorch/pytorch/blob/76362408dfde47545781b5abbfe894ea63646779/aten/src/ATen/native/cuda/UnaryFractionKernels.cu#L65-L81

It seems that you'll need to use `isinf` and `isnan` instead of the ones in the `std` namespace.

**Comment by kshitij12345** [comment]
@peterjc123 Thanks. That was indeed the issue.

**Comment by kshitij12345** [comment]
@anjali411 @mruberry @dylanbespalko PTAL:)
The faillure looks irrelevant.

**Review by anjali411 — APPROVED** [review]
LGTM :)

**Pull request closed without merging**
