### PR TITLE
Python 3.13 CI add crossref test to existing linux-focal-py3_13-clang10-build 

### PR DESCRIPTION
**Pull request by atalman**
Add  linux-jammy-py3_13-gcc11-build and test - similar to Py 3.9
Add crossref test to existing linux-focal-py3_13-clang10-build

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by atalman** [comment]
@malfet please note I separated adding linux-jammy-py3_13-gcc11-build here in separate PR: https://github.com/pytorch/pytorch/pull/143087 since I believe more work is required for it. crossref change should be green. Signal is from this PR: https://github.com/pytorch/pytorch/pull/142870

**Pull request closed without merging**
