### PR TITLE
[utils][foreach] Add group tensor by device and dtype util

### PR DESCRIPTION
**Pull request by janeyx99**
Add util that will be commonly used throughout optim

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM

**Comment by janeyx99** [comment]
@pytorchbot merge -f "force merging because i think xla and nvfuser test are just flaky but there are no nice options to let me set + go as of right now"

To elaborate:
- I would liek to rerun the 11.6 test failure + comment @pytorchbot merge, but I can't do that cuz xla is still running.
- I could cancel xla and then rerun both, but sunk cost fallacy and the fact that it's been going for over an hour makes me not want to do that
- I could wait for xla to finish and then rerun just 11.6, but I want to eat dinner and have this merge sooner rather than later
- I could force merge 😛 

If we are autorerunning failed workflows now, it might be nice to not cancel the merge job, but I suspect that would run into timeouts. :/

**Pull request closed without merging**
