### PR TITLE
Temporarily disable ROCm tests on pull request

### PR DESCRIPTION
**Pull request by kit1980**
See https://github.com/pytorch/pytorch/pull/91217

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Comment by clee2000** [comment]
is this necessary? i dont think the builds run on rocm machines?

**Comment by kit1980** [comment]
> is this necessary? i dont think the builds run on rocm machines?

But it's just named build, and actually does tests, no?

      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 2, runner: "linux.rocm.gpu" },
          { config: "default", shard: 2, num_shards: 2, runner: "linux.rocm.gpu" },
        ]}

**Comment by clee2000** [comment]
> > is this necessary? i dont think the builds run on rocm machines?
> 
> But it's just named build, and actually does tests, no?
> 
> ```
>   test-matrix: |
>     { include: [
>       { config: "default", shard: 1, num_shards: 2, runner: "linux.rocm.gpu" },
>       { config: "default", shard: 2, num_shards: 2, runner: "linux.rocm.gpu" },
>     ]}
> ```

i think these are just for filtering/selecting which test configs

**Comment by kit1980** [comment]
> i think these are just for filtering/selecting which test configs

OK, I misunderstood it.
No need for this PR then.

**Pull request closed without merging**
