### PR TITLE
added CUDA tensor to numpy compability

### PR DESCRIPTION
**Pull request by atopheim**
Edit on line 458 and 460.
Copying tensor to host memory before performing numpy operation.

### CODE REVIEW

**Comment by vadimkantorov** [comment]
This implicit conversion was removed in https://github.com/pytorch/pytorch/issues/9934. If the opposite is now decided, it'd be good to have this documented.

**Comment by umanwizard** [comment]
cc @fmassa and @ailzhang  who were discussing this behavior on #9934 .

Personally I don't think we should do implicit, silent GPU->CPU conversions, but I will defer to others' opinions.

**Comment by soumith** [comment]
yes, we do not want this implicit behavior (an accident in fact introduced it briefly on master at some point, and we removed it right after)

**Comment by umanwizard** [comment]
@atopheim I would be interested in knowing what your specific use-case is, such that you would have found this behavior useful.

**Pull request closed without merging**
