### PR TITLE
Add NCCL PreMul Sum to c10d `redce` ops

### PR DESCRIPTION
**Pull request by crcrpar**
This is based on #81272 but this conforms to TorchScript Compiler

cc @ptrblck @kwen2501 @aazzolini 
cc @zasdfgbnm for visibility to the TODO above

### CODE REVIEW

**Comment by crcrpar** [comment]
if this works at least on the public CI, I'll close https://github.com/pytorch/pytorch/pull/84059

**Comment by crcrpar** [comment]
Regarding the failure

```console
2022-08-30T02:10:49.9879118Z The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not. 
2022-08-30T02:10:49.9879135Z 
2022-08-30T02:10:49.9879245Z Broken ops: [
2022-08-30T02:10:49.9879772Z 	c10d::reduce_(Tensor[] _0, __torch__.torch.classes.c10d.ProcessGroup _1, int _2, int _3, int _4, int _5) -> __torch__.torch.classes.c10d.Work _0
2022-08-30T02:10:49.9880297Z 	c10d::reduce_scatter_(Tensor[] _0, Tensor[][] _1, __torch__.torch.classes.c10d.ProcessGroup _2, int _3, int _4) -> __torch__.torch.classes.c10d.Work _0
2022-08-30T02:10:49.9880791Z 	c10d::allreduce_(Tensor[] _0, __torch__.torch.classes.c10d.ProcessGroup _1, int _2, int _3) -> __torch__.torch.classes.c10d.Work _0
2022-08-30T02:10:49.9880884Z ]
```

Should I add c10d reduce ops to ALLOW_LIST like https://github.com/crcrpar/pytorch/blob/a0c6e7499ea81fb0da4858a7ebf27a88c0612493/test/forward_backward_compatibility/check_forward_backward_compatibility.py#L123?

**Comment by kwen2501** [comment]
> Regarding the failure
> 
> ```
> 2022-08-30T02:10:49.9879118Z The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not. 
> 2022-08-30T02:10:49.9879135Z 
> 2022-08-30T02:10:49.9879245Z Broken ops: [
> 2022-08-30T02:10:49.9879772Z 	c10d::reduce_(Tensor[] _0, __torch__.torch.classes.c10d.ProcessGroup _1, int _2, int _3, int _4, int _5) -> __torch__.torch.classes.c10d.Work _0
> 2022-08-30T02:10:49.9880297Z 	c10d::reduce_scatter_(Tensor[] _0, Tensor[][] _1, __torch__.torch.classes.c10d.ProcessGroup _2, int _3, int _4) -> __torch__.torch.classes.c10d.Work _0
> 2022-08-30T02:10:49.9880791Z 	c10d::allreduce_(Tensor[] _0, __torch__.torch.classes.c10d.ProcessGroup _1, int _2, int _3) -> __torch__.torch.classes.c10d.Work _0
> 2022-08-30T02:10:49.9880884Z ]
> ```
> 
> Should I add c10d reduce ops to ALLOW_LIST like https://github.com/crcrpar/pytorch/blob/a0c6e7499ea81fb0da4858a7ebf27a88c0612493/test/forward_backward_compatibility/check_forward_backward_compatibility.py#L123?

@H-Huang seems to have encounter a similar warning. Maybe he knows how to respond to it.

**Comment by crcrpar** [comment]
I ran test/test_proxy_tensor.py locally and I got 
```
FAILED test/test_proxy_tensor.py::TestProxyTensorOpInfoCPU::test_make_fx_symbolic_exhaustive_nanmean_cpu_float32
```
I don't know how this could be related to my PR

**Comment by H-Huang** [comment]
> Regarding the failure
> 
> ```
> 2022-08-30T02:10:49.9879118Z The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not. 
> 2022-08-30T02:10:49.9879135Z 
> 2022-08-30T02:10:49.9879245Z Broken ops: [
> 2022-08-30T02:10:49.9879772Z 	c10d::reduce_(Tensor[] _0, __torch__.torch.classes.c10d.ProcessGroup _1, int _2, int _3, int _4, int _5) -> __torch__.torch.classes.c10d.Work _0
> 2022-08-30T02:10:49.9880297Z 	c10d::reduce_scatter_(Tensor[] _0, Tensor[][] _1, __torch__.torch.classes.c10d.ProcessGroup _2, int _3, int _4) -> __torch__.torch.classes.c10d.Work _0
> 2022-08-30T02:10:49.9880791Z 	c10d::allreduce_(Tensor[] _0, __torch__.torch.classes.c10d.ProcessGroup _1, int _2, int _3) -> __torch__.torch.classes.c10d.Work _0
> 2022-08-30T02:10:49.9880884Z ]
> ```
> 
> Should I add c10d reduce ops to ALLOW_LIST like https://github.com/crcrpar/pytorch/blob/a0c6e7499ea81fb0da4858a7ebf27a88c0612493/test/forward_backward_compatibility/check_forward_backward_compatibility.py#L123?

@crcrpar @kwen2501  FYI: I am going to update the allow list in this PR to allow all changes to all ops for the dispatchable collectives feature https://github.com/pytorch/pytorch/pull/83735/files#diff-236fbde71e59cb1597cac177a83e49fb62b30770eec55c4e7a0f2650b9eb6203R274-R275. PR will be merged in the next day or 2. Feel free to also include this change.

**Comment by crcrpar** [comment]
Failures of https://app.circleci.com/pipelines/github/pytorch/pytorch/559687/workflows/c323160d-ae56-4ada-a891-50ad050199b3/jobs/17073409 and https://app.circleci.com/pipelines/github/pytorch/pytorch/559687/workflows/c323160d-ae56-4ada-a891-50ad050199b3/jobs/17073412 look unrelated

**Review by kwen2501 — APPROVED** [review]
LGTM! Thanks for the contribution!

**Pull request closed without merging**
