### PR TITLE
Get rid of tabular and sizes, beef up verbosity of output graph

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125507

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by ezyang** [comment]
@Chillee you get what you wanted, stride by default :P

**Comment by Chillee** [comment]
Did I want stride by default? 🤔

**Review by Chillee — APPROVED** [review]
Why is the test being deleted?

**Review by jansel — APPROVED** [review]

**Comment by ezyang** [comment]
> Why is the test being deleted?

The test is testing that there is a separate log for sizes, but now that they're all in the graph we don't need this log.

**Comment by ezyang** [comment]
> Did I want stride by default? 🤔

I distinctly remember you complaining to me about it :)

**Pull request closed without merging**
