### PR TITLE
Add onnx / test to required merge rules

### PR DESCRIPTION
**Pull request by justinchuby**
Add two `linux-xenial-py3.7-clang7-onnx / test` checks to required merge rules for `torch.onnx`

~~Question: Do I need to full name (`linux-xenial-py3.7-clang7-onnx / test (default, 1, 2, linux.2xlarge)`) or will the bot match the prefix?~~

### CODE REVIEW

**Comment by BowenBao** [comment]
@suo for question in PR description.

**Comment by suo** [comment]
cc @janeyx99

**Comment by janeyx99** [comment]
Hey @justinchuby! You'll need to match the full name, unfortunately :/

To give you more context, we want to eventually turn all of the pull CI jobs (including ONNX) to be required so there will be a day where the mandatory checks will just be Lint and pull instead of the long lists we have today.

**Review by BowenBao — APPROVED** [review]

**Comment by justinchuby** [comment]
@janeyx99 could you help approve? Thanks

**Review by janeyx99 — APPROVED** [review]

**Comment by suo** [comment]
wait, do we want to do this? @janeyx99 the onnx tests do not use any of our test infra and automation

**Review by suo — CHANGES_REQUESTED** [review]
imo we should discuss what our policy should be for tests that do not share the same test infra as the rest of pytorch

**Comment by janeyx99** [comment]
> wait, do we want to do this? @janeyx99 the onnx tests do not use any of our test infra and automation

I thought this should be ok since it only affects the onnx merge rule, and not everyone else.

**Comment by suo** [comment]
ooooh they can be different per module? Didn't realize. That seems fine then

**Pull request closed without merging**
