### PR TITLE
[inductor] a script to benchmark the perf impact from tensor layout

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99583

Follow up on Jason's idea of tensor layout tuning. Add a script to show the perf impact of layout to convolution (will add more cases like batch/layer norm, reduction to the scripts).

For convolution, a quick test shows using channels last layout, we get 1.4x speedup for convolution:
```
baseline 4.509183883666992 test 3.178528070449829 speedup 1.419x
```

The speedup definitely also depends on input/weight shapes. E.g., change input channel from 3 in the test to 8, we see speedup to be 2.1x

The trace shows cudnn calls different kernels when input layout changes to channels last.

Screenshot 2023-04-19 at 5 27 54 PM

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
This looks correct, though I am not sure if it needs to be checked in.

If there is a reason to check it in, it should go in `./benchmarks/dynamo/microbenchmarks/`

**Comment by shunting314** [comment]
Moved the script to the microbenchmarks folder. I don't have very strong motivation to land this either. But just feel that this kind of micro-benchmark can be a bit helpful to understand heuristics behind optimizations.

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
