### PR TITLE
Correct _validate_sparse_compressed_tensor_args signature

### PR DESCRIPTION
**Pull request by pearu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #75585
* #75962
* __->__ #76635

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]

**Comment by cpuhrsch** [comment]
Test failure is real

**Review by cpuhrsch — CHANGES_REQUESTED** [review]
Test failure is real

**Comment by pearu** [comment]
@cpuhrsch notice that this PR is about getting approval for ignoring the following failure
```
The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not. 

Broken ops: [
	aten::_validate_sparse_compressed_tensor_args(Tensor crow_indices, Tensor col_indices, Tensor values, int[] size, int layout) -> ()
]
```
that is, the BC breakage issue is minor: the PR just changes the argument names, the function has existed only a couple of weeks, the function is private, and the function is a part of a beta feature.

**Review by cpuhrsch — APPROVED** [review]

**Comment by b0noI** [comment]
this time we are not going to revert this PR, however next time please add your operator to the ALLOW_LIST with the reasonable expiration date (example: https://github.com/pytorch/pytorch/pull/76837 ), we do not allow any explicit build breaks on master

**Pull request closed without merging**
