### PR TITLE
[XPU][Kineto Submodule] Introduce kineto-based XPU profiler

### PR DESCRIPTION
**Pull request by zejun-chen**
As XPU became a PyTorch built-in device, the profiler support is indispensable part of functionality completeness. This PR is associated with the PR to introduce XPU profiler plugin into the kineto. When USE_XPU is enabled, the LIBKINETO_NOXPUPTI option will be suppressed accordingly, which allows kineto to build with XPU profiler plugin.

Associated PR to introduce kineto-based XPU profiler into kineto:
https://github.com/pytorch/kineto/pull/961

Also updates the Kineto Submodule to include XPU changes.

### CODE REVIEW

**Comment by zejun-chen** [comment]
Hi, @aaronenyeshi 

Could you help review the PR? :)

Thank you.

**Review by aaronenyeshi — APPROVED** [review]
LGTM, but you may need to update the kineto submodule hash to the most recent commit. In this folder: https://github.com/pytorch/pytorch/tree/main/third_party

**Comment by aaronenyeshi** [comment]
I've pushed another commit with the kineto submodule update. let's wait for CI now.

**Comment by aaronenyeshi** [comment]
@pytorchbot merge -f "Landed internally, and passed all CI signals"

image

**Comment by aaronenyeshi** [comment]
Landed: https://github.com/pytorch/pytorch/commit/26b0011fb86f1686b98d6fad41e7cbc020db7aa5

Closing this PR.

**Comment by zejun-chen** [comment]
> Landed: [26b0011](https://github.com/pytorch/pytorch/commit/26b0011fb86f1686b98d6fad41e7cbc020db7aa5)
> 
> Closing this PR.

Thank you so much @aaronenyeshi 👍 
We will enable the kineto UTs for xpu backend to make sure the quality.

**Pull request closed without merging**
