### PR TITLE
[MPS] Adding lgamma, digamma, and polygamma implementations

### PR DESCRIPTION
**Pull request by igm503**
Fixes issue mentioned in #77764 

e.g. https://github.com/pytorch/pytorch/issues/77764#issuecomment-1654111744

Adds MPS support for the following ops:

- lgamma
- mvlgamma
- digamma
- polygamma

The lgamma fucntion does not yet have an MPS backend implementation. I've added one using a custom metal kernel (following John D. Cook's c++ implementation of the log gamma function: https://www.johndcook.com/blog/cpp_gamma/). For the backward pass op, I've added a digamma kernel that follows the cpu+cuda digamma implementation, and for the backward pass of the digamma op, I've added a polygamma + trigamma kernel following, again, the cpu+cuda implementations.

NOTE:

The cpu implementation of the polygamma function incorrectly (as far as I can tell) outputs a finite number for order = 1 and x in the negative integers. The mps implementation correctly outputs infinite. (see https://github.com/pytorch/pytorch/issues/106692)

The polygamma tests currently don't pass because of the error in the cpu+cuda kernels, but also because there are smallish discrepancies near the negative integers between the cpu+cuda and the mps polygamma and trigamma kernels. I'm not sure exactly why this is, but let me know if the discrepancies are too big.

### CODE REVIEW

**Comment by igm503** [comment]
@kulinseth Any chance you can give this a look and advise about whether the test failures are a problem?

**Comment by kulinseth** [comment]
```
=================================== FAILURES ===================================
______________ TestFallbackWarning.test_error_on_not_implemented _______________
Traceback (most recent call last):
  File "/Users/ec2-user/runner/_work/pytorch/pytorch/test/test_mps.py", line 10438, in test_error_on_not_implemented
    fn(*args, **kwargs)
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_5983090866/lib/python3.9/unittest/case.py", line 226, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_5983090866/lib/python3.9/unittest/case.py", line 163, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: NotImplementedError not raised
```
This issue seems unrelated to the PR. Can you @igm503 please rebase the PR?

**Comment by kulinseth** [comment]
> @kulinseth Any chance you can give this a look and advise about whether the test failures are a problem?


@igm503  the assertion is coming from not implemented test . Can you check if lgamma tests are not in that category class  in test_mps .

**Comment by igm503** [comment]
@kulinseth I've fixed the assertion error by swapping another not-yet-implemented op for lgamma in the not_implemented test.

**Comment by igm503** [comment]
@kulinseth So, at least as I'm typing this, the test errors are now those that I mentioned in the pull request body: in some cases, they're precision issues, but in other cases, I think the cpu implementation is incorrect.

**Comment by kulinseth** [comment]
> @kulinseth So, at least as I'm typing this, the test errors are now those that I mentioned in the pull request body: in some cases, they're precision issues, but in other cases, I think the cpu implementation is incorrect.

@igm503 , I see, we can add these tests to XFAILLIST [here.](https://github.com/pytorch/pytorch/blob/main/test/test_mps.py#L354)

**Comment by igm503** [comment]
> > @kulinseth So, at least as I'm typing this, the test errors are now those that I mentioned in the pull request body: in some cases, they're precision issues, but in other cases, I think the cpu implementation is incorrect.
> 
> @igm503 , I see, we can add these tests to XFAILLIST [here.](https://github.com/pytorch/pytorch/blob/main/test/test_mps.py#L354)

Since there are precision issues with test_output_grad_match_polygamma_polygamma_n_0_cpu_float32 on macos 12 as well, where should I put that exception?

**Comment by igm503** [comment]
@kulinseth I went ahead and added the failing tests to the MACOS_BEFORE_13_3_XFAILLIST as well. Let me know if there's a more appropriate place to put them.

**Review by kulinseth — APPROVED** [review]
Looks good

**Pull request closed without merging**
