### PR TITLE
[ao][fx] fixing public v private prepare.py

### PR DESCRIPTION
**Pull request by HDCharles**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #88398
* #88397

Summary: made _DO_NOT_OBS_DTYPE_LIST, _add_matched_node_name_to_set,
_get_arg_target_is_dynamic_as_input_to_node, _get_arg_target_is_dynamic_as_input_to_node,
_get_arg_target_dtype_as_input_to_node,
_get_arg_target_dtype_as_output,
_get_target_activation_dtype_for_node,
_get_standalone_module_configs,
_insert_observer,
_is_activation_post_process_node,
_is_input_arg_dtype_supported_by_backend,
_is_observer_in_same_graph,
_is_output_dtype_supported_by_backend,
_maybe_insert_input_equalization_observers_for_node,
_maybe_insert_input_observer_for_arg_or_kwarg,
_maybe_insert_input_observers_for_node,
_maybe_insert_observers_before_graph_output,
_maybe_insert_output_observer_for_node,
_maybe_make_input_output_share_observers,
_maybe_propagate_dtype_for_node,
_qat_swap_modules,
_remove_output_observer,
_run_prepare_fx_on_standalone_modules,
_save_state,
_swap_custom_module_to_observed private

Test Plan: python test/test_public_bindings.py

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D41015542](https://our.internmc.facebook.com/intern/diff/D41015542)

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

### CODE REVIEW

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41015542).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41015542).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41015542).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41015542).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41015542).

**Review by jcaip — APPROVED** [review]
lgtm

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41015542).

**Pull request closed without merging**
