### PR TITLE
[Traceable FSDP2] Add compiled_autograd_enabled helper function

### PR DESCRIPTION
**Pull request by yf225**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #138113
* __->__ #138105

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by awgu — APPROVED** [review]
Thanks for cleaning this up!

**Review by xmfan — APPROVED** [review]

**Pull request closed without merging**
