### PR TITLE
Define macro for DispatchKey::toString.

### PR DESCRIPTION
**Pull request by ailzhang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#44993 Define macro for DispatchKey::toString.**
* #45150 Resolve comments in #44354.

Differential Revision: [D23796258](https://our.internmc.facebook.com/intern/diff/D23796258)

### CODE REVIEW

**Comment by ailzhang** [comment]
fixes https://github.com/pytorch/pytorch/issues/44657

**Review by bhosmer — COMMENTED** [review]
Cool! But actually I'd go even further and use this macro to define the DispatchKey enum itself - that way the macro is literally the single source of truth. (I haven't looked but there might be other definitions that could be converted to using this macro as well.) 

[Edit: the `ScalarType` setup in ScalarType.h is a good example of this technique, although it's actually more complicated than this would need to be, bc that macro also needs to define the association between the enum and the C++ types]

Aside: one minor consideration is that we definitely don't want to lose the excellent comments in the current definition. I'm not sure the easiest way to preserve them - if they stay inline we'd need to change them into `/* ... */` style and add line continuations, which is annoying. We could also move them out of line, which might make the keys themselves easier to see as a whole, at the cost of the extra hop from key to description during reading. Not sure which is least bad, or if there are other choices...

**Comment by ezyang** [comment]
One thing that the new hierarchical macro structure makes me nervous about is that it is no longer obvious what the global ordering of all entries in the enum. It easy to cause it to be not textual order by, e.g., reordering the macro references in `FOR_EACH_PUBLIC_BACKEND_DISPATCH_KEY_WITH_AUTOGRAD_KEY`. 

I'm also not sure how much the macros are buying us. Outside of the enum, `FOR_EACH_BACKEND_DISPATCH_KEY_MAPPED_TO_AUTOGRAD_OTHER`, `FOR_EACH_RUNTIME_AUTOGRAD_DISPATCH_KEY` and `FOR_EACH_BACKEND_DISPATCH_KEY` are used exactly once, and `FOR_EACH_BACKEND_DISPATCH_KEY_WITH_AUTOGRAD_KEY` is used twice but only because you need to map to and from autograd. Maybe there are other places in the code you are thinking of using the macros, but to me, it implies to me that there isn't that much redundancy in the current representation: once you've stuffed everything in a dispatch key set, you can mostly just rely on that to tell you if something is in a set or not.

**Comment by ailzhang** [comment]
Hmmm I reordered the commits in ghstack but not sure why it's shown as merged here :P

**Pull request merged**
