### PR TITLE
[Caffe2][Training performance]Implementation MomentumSGD/MomentumSGDUpdate operators for mkl-dnn

### PR DESCRIPTION
**Pull request by PenghuiCheng**
the speed-up of a single operation is up to 6X on BDW.

### CODE REVIEW

**Comment by wesolwsk** [comment]
Getting lots of errors as follows: 

caffe2/caffe2/core/operator.h: In instantiation of ‘const T& caffe2::OperatorBase::Input(int) [with T = caffe2::Tensor]’:
caffe2/caffe2/ideep/operators/momentum_sgd_op.cc:55:55:   required from here
caffe2/caffe2/core/operator.h:68:5: error: static assertion failed: You should use Input<Tensor>(int, DeviceType) for Tensor.
     static_assert(
     ^

**Comment by PenghuiCheng** [comment]
@wesolwsk ,I had updated code. Please review it.
Thanks!
cheng,Penghui

**Comment by wesolwsk** [comment]
please make the following fixes and rebase

screen shot 2018-09-19 at 2 12 28 pm

**Comment by PenghuiCheng** [comment]
@wesolwsk ,for line 37 and line78,ShadowingClass warning,I didn't know how to change it,do you have some suggestions for this?
Thanks!

**Pull request closed without merging**
