### PR TITLE
[quant][graphmode][fx] Fork subgraph_rewriter from torch.fx to quantization

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #68770
* #68769
* #68229
* __->__ #68228

Summary:
Forking this for now so that we can make changes as we need, the changes can be merged back to torch.fx
later

Test Plan:
```
python test/test_quantization.py TestQuantizeFx
python test/test_quantization.py TestQuantizeFxOps
```

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D32537713](https://our.internmc.facebook.com/intern/diff/D32537713)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32537713).

**Comment by vkuzo** [comment]
> Forking this for now so that we can make changes as we need, the changes can be merged back to torch.fx
later

Can we spell out the strategy in a bit more detail?  Specifically, can we use something like `SubgraphRewriter_FORKED_DO_NOT_DEPEND_ON_THIS` as the class name, and spell out the temporary nature of the fork and the promise to eventually revert the fork before releasing to prototype?

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32537713).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32537713).

**Review by vkuzo — APPROVED** [review]
should test coverage be imported as well?

**Comment by jerryzh168** [comment]
> should test coverage be imported as well?

yeah that sounds like a good idea, will do

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32537713).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32537713).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32537713).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32537713).

**Pull request closed without merging**
