### PR TITLE
[build] Remove FULL_CAFFE2 flag

### PR DESCRIPTION
**Pull request by orionr**
Continuing @pjh5's work to remove FULL_CAFFE2 flag completely.

With these changes you'll be able to also do something like

```
NO_TEST=1 python setup.py build_deps
```
and this will skip building tests in caffe2, aten, and c10d. By default the tests are built.

Also, BUILD_BINARIES and USE_OPENCV are OFF by default and BUILD_TEST is ON by default.

cc @mingzhe09088 @Yangqing

### CODE REVIEW

**Comment by SsnL** [comment]
What exactly will the `BUILD_TEST=0` flag do? Does it turn off aten tests, torch tests, c10d tests, and c10d examples? I'm asking because I'm unable to build pytorch on devfair anymore, unless I disable all those tests/examples. FWIW, I was seeing
```
//usr/lib/x86_64-linux-gnu/libSM.so.6: undefined reference to `uuid_generate@UUID_1.0'
```
even with uuid-dev installed.

**Comment by orionr** [comment]
@SsnL I'll make sure the environment flag can be set and that it applies to all of those.

**Review by soumith — APPROVED** [review]
lgtm. what is "Build C++ binaries", what are the C++ binaries that we build apart from tests?

**Comment by Yangqing** [comment]
@soumith the binaries are the native C++ binaries that C2 had, such as speed_benchmark etc. Might not be much useful in the python releases so we can probably turn it off by default.

**Comment by apaszke** [comment]
Another downside of the binaries is that they are installed in `torch/lib`, but are not in `.gitignore`, so one needs to be careful when checking in files.

**Comment by Yangqing** [comment]
non-blocking: #11388 fixes googletest issue.

**Comment by orionr** [comment]
The pytorch-linux-xenial-cuda9 error looks like it's the same as one on master. Going to ignore that.

**Comment by SsnL** [comment]
Can confirm that this fixes the build on devfair (with NO_TEST=1)! Thanks!

**Pull request closed without merging**
