### PR TITLE
Catch Flake8 error codes with multiple letters

### PR DESCRIPTION
**Pull request by samestep**
The Flake8 job has been passing on `master` despite giving warnings for [over a month](https://github.com/pytorch/pytorch/runs/1716124347). This is because it has been using a regex that doesn't recognize error codes starting with multiple letters, such as those used by [flake8-executable](https://pypi.org/project/flake8-executable/). This PR corrects the regex, and also adds another step at the end of the job which asserts that Flake8 actually gave no error output, in case similar regex issues appear in the future.

Tagging the following people to ask what to do to fix these `EXE002` warnings:

- #50629 authored by @jaglinux, approved by @rohan-varma
  - `test/distributed/test_c10d.py`
- #51262 authored by @glaringlee, approved by @ejguan
  - `torch/utils/data/datapipes/__init__.py`
  - `torch/utils/data/datapipes/iter/loadfilesfromdisk.py`
  - `torch/utils/data/datapipes/iter/listdirfiles.py`
  - `torch/utils/data/datapipes/iter/__init__.py`
  - `torch/utils/data/datapipes/utils/__init__.py`
  - `torch/utils/data/datapipes/utils/common.py`
- #51398 authored by @glaringlee, approved by @ejguan
  - `torch/utils/data/datapipes/iter/readfilesfromtar.py`
- #51599 authored by @glaringlee, approved by @ejguan
  - `torch/utils/data/datapipes/iter/readfilesfromzip.py`
- #51704 authored by @glaringlee, approved by @ejguan
  - `torch/utils/data/datapipes/iter/routeddecoder.py`
  - `torch/utils/data/datapipes/utils/decoder.py`
- #51709 authored by @glaringlee, approved by @ejguan
  - `torch/utils/data/datapipes/iter/groupbykey.py`

Specifically, the question is: for each of those files, should we remove the execute permissions, or should we add a shebang? And if the latter, which shebang?

**Test plan:**

The **Lint / flake8-py3** job in GitHub Actions:

- [this run](https://github.com/pytorch/pytorch/runs/1972039886) failed, showing that the new regex catches these warnings properly
- [this run](https://github.com/pytorch/pytorch/runs/1972393293) succeeded and gave no output in the "Run flake8" step, showing that this PR fixed all Flake8 warnings
- [this run](https://github.com/pytorch/pytorch/pull/52755/checks?check_run_id=1972414849) (in #52755) failed, showing that the new last step of the job successfully catches Flake8 warnings even without the regex fix

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]
good catch!

**Comment by samestep** [comment]
> good catch!

@janeyx99 lol don't approve yet, the Flake8 failures are still present :P

**Comment by janeyx99** [comment]
> @janeyx99 lol don't approve yet, the Flake8 failures are still present :P

Can still approve cuz your code can be landed, and the fixes can happen independently. :p

**Review by walterddr — COMMENTED** [review]
looks good but cant we fix all those EXE002 in the same PR. those are just permission issues right. getting rid of it by `chmod -x <file>` should be good enough?

**Comment by samestep** [comment]
> looks good but cant we fix all those EXE002 in the same PR. those are just permission issues right. getting rid of it by `chmod -x <file>` should be good enough?

@walterddr Yes, the intention is to fix them all in this PR; as stated in the PR description, I want to hear from the code authors in case it would be better to add shebangs instead of just removing executable permissions.

**Comment by walterddr** [comment]
thanks. i dont think any of these datapipe utils are meant to be used as executable since there's no even `__main__` defined. for test_c10d.py it seems should be invoked via run_tests (and of which is executable)

**Comment by ejguan** [comment]
Thanks for catching the error. But, do you have any suggestion to solve it for DataPipes? They should not be considered as executable which means shebang is not required.
I am trying to figure it out and will let you know if I find anything.

**Comment by samestep** [comment]
> Thanks for catching the error. But, do you have any suggestion to solve it for DataPipes? They should not be considered as executable which means shebang is not required.
> I am trying to figure it out and will let you know if I find anything.

@ejguan Currently this PR just removes those executable permissions, so we should be good to go. Thanks for confirming!

**Review by walterddr — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
