### PR TITLE
[Inductor] Make codecache CUDA compilation more robust & flexible

### PR DESCRIPTION
**Pull request by kadeng**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #121491
* __->__ #121490

Minor changes which make the CUDA compilation within _inductor/codecache.py
more robust and flexible.

Test plan:
CI
Additional test in test_codecache.py

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by aakhundov** [comment]
@kadeng this PR has failed to run due to failing CI jobs. Mind taking a look?

**Comment by kadeng** [comment]
> @kadeng this PR has failed to run due to failing CI jobs. Mind taking a look?

Can't reproduce the failure locally. Will rebase and re-run ..

**Comment by kadeng** [comment]
There's still a torchbench test failing, but I suspect that's unrelated.

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting you change but I think it is failing on ROCm, i.e. https://hud.pytorch.org/pytorch/pytorch/commit/700c92e1b9cb6fae2610d08e5a960273c4dd1697' -c nosignal

```
2024-03-22T12:51:38.6187818Z ______________ TestFxGraphCacheHashing.test_cuda_compile_command _______________
2024-03-22T12:51:38.6188442Z Traceback (most recent call last):
2024-03-22T12:51:38.6189017Z   File "inductor/test_codecache.py", line 529, in test_cuda_compile_command
2024-03-22T12:51:38.6189645Z     cmd_no_extra_args: str = cuda_compile_command(
2024-03-22T12:51:38.6190626Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 2347, in cuda_compile_command
2024-03-22T12:51:38.6191473Z     cuda_lib_options = _cuda_lib_options()
2024-03-22T12:51:38.6192501Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 2271, in _cuda_lib_options
2024-03-22T12:51:38.6193517Z     cpp_extension._join_cuda_home(extra_lib_dir)
2024-03-22T12:51:38.6194581Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2419, in _join_cuda_home
2024-03-22T12:51:38.6195644Z     raise OSError('CUDA_HOME environment variable is not set. '
2024-03-22T12:51:38.6196419Z OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```

Adding `ciflow/rocm` will help catch this failure on pR

**Comment by aakhundov** [comment]
@kadeng add `@skipIfRocm` to the unit test?

**Comment by kadeng** [comment]
Thanks, I added @skipIfRocm to the test and tagged the PR with ciflow/rocm - I guess it should pass now.

**Comment by kadeng** [comment]
I still get test failures for rocm, but these appear completely unrelated. They are marked as new failures nevertheless. I'm trying to ensure they are definitively unrelated before I merge again.

**Pull request closed without merging**
