### PR TITLE
Enable default workflow PyT 2.0 UTs on ROCm stack 

### PR DESCRIPTION
**Pull request by jataylo**
PR to enable default workflow PyTorch 2.0 unit tests for the ROCm stack.

- Enables all the dynamo unit test suites
- Enables some of the inductor unit test suites
       - `test_config`
       - `test_cpp_wrapper` (cpu only)
       - `test_minifier`
       - `test_standalone_compile`
       - `test_torchinductor_dynamic_shapes`
       - `test_torchinductor_opinfo`
       - `test_torchinductor`
       - `test_triton_wrapper`
- Introduces TEST_WITH_ROCM conditions for unit test skip/fail dictionaries in test_torchinductor_dynamic_shapes.py and test_torchinductor_opinfo.py

Note this PR follows on from the discussions for the previous UT enablement PR https://github.com/pytorch/pytorch/pull/97988, we have opted to only enable a few inductor suites at the moment to ease the upstreaming effort as these files are changing very quickly.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire @anijain2305 @soumith

### CODE REVIEW

**Comment by jataylo** [comment]
@kit1980 @malfet @jithunnair-amd 
This follows from the previous UT enablement attempt https://github.com/pytorch/pytorch/pull/97988, we have opted to only enable a handful of the inductor UTs at the moment to ease the upstreaming effort. All failures seem to be unrelated either flakey models in dynamo-benchmarks and some workflows never seemed to kick off.

**Comment by jithunnair-amd** [comment]
@malfet @kit1980 Please help merge this, we have been chasing this moving target for a while now, stuck in a tedious loop of rebases and merge conflicts.

**Review by jithunnair-amd — APPROVED** [review]

**Comment by jataylo** [comment]
Fixed merge conflict

**Review by malfet — APPROVED** [review]
It feels like it enables a very limited testing, but sure, why not

**Pull request closed without merging**
