### PR TITLE
Added scientific notation on set_printoptions

### LINKED ISSUE #15683: Allow scientific notation to be enabled or disabled
## 🚀 Feature

I would request that `torch.set_printoptions` add a flag so that scientific notation can be enabled or disabled.

## Motivation

PyTorch printing has a limitation: the end user cannot force scientific mode printing to be enabled or disabled. (Currently, `sci_mode` is chosen based on logic in [_tensor_str.py](https://github.com/pytorch/pytorch/blob/master/torch/_tensor_str.py#L69).)

This would give end-users more control, and it would be an easy change.

## Pitch

One possible implementation would involve adding a named argument `sci_mode` to `set_printoptions`. Perhaps:

* `sci_mode=None` would allow `sci_mode` to be determined by the current logic (the current default)
* `sci_mode=True` would force `sci_mode` to be True
* `sci_mode=False` would force `sci_mode` to be False

This would be easy to implement: based on the argument, `sci_mode` in class `_Formatter` could be unaffected or forced to be `True` or `False`.

## Alternatives

I'm open to other implementations that would satisfy the same problem.

For example, Numpy's `suppress` argument to its `set_printoption` affects the printing of scientific notation.  (Note: In my opinion, Numpy's approach (with `suppress`) is a bit harder to reason about than my proposal, above. My proposal is orthogonal to the other feature flags. I often consider orthogonality to be a desirable property when it comes to configuration.)

## Additional context

* https://en.wikipedia.org/wiki/Orthogonality_(programming)

## Related Issues

* https://github.com/pytorch/pytorch/issues/13446

### PR DESCRIPTION
**Pull request by xmnlab**
This PR fixes #15683

### CODE REVIEW

**Comment by xmnlab** [comment]
It seems it is done for a review. I am just not sure where should I add this for this and how to test it. I just find one usage of `torch.set_printoptions` one time and in just one file `test_nn`.

any thoughts?

**Review by fmassa — APPROVED** [review]
This looks good to me, thanks a lot!

Could you just add some tests for this?
Probably following the same as in
https://github.com/pytorch/pytorch/blob/f03296299b4f39ffed00d94c1adb12255b6d74c0/test/test_torch.py#L8900-L8903

**Comment by xmnlab** [comment]
thanks @fmassa for the feedback! I just added the tests for the scientific notation options.

**Comment by ezyang** [comment]
Test failures llook legit:

```
Feb 10 00:22:38 ======================================================================
Feb 10 00:22:38 FAIL: test_print (__main__.TestTorch)
Feb 10 00:22:38 ----------------------------------------------------------------------
Feb 10 00:22:38 Traceback (most recent call last):
Feb 10 00:22:38   File \"test_torch.py\", line 8937, in test_print
Feb 10 00:22:38     self.assertExpectedInline(str(x), expected_str)
Feb 10 00:22:38   File \"/var/lib/jenkins/workspace/test/expecttest.py\", line 195, in assertExpectedInline
Feb 10 00:22:38     self.assertMultiLineEqual(expect, actual, msg=help_text)
Feb 10 00:22:38 AssertionError: 'tensor([ 0.0000e+00, 9.8813e-324, 9.8813e-323, 1.0[62 chars]t64)' != 'tensor([     0.0000,      0.0000,      0.0000, 999[666 chars]t64)'
Feb 10 00:22:38 - tensor([ 0.0000e+00, 9.8813e-324, 9.8813e-323, 1.0000e+307, 1.0000e+308,
Feb 10 00:22:38 + tensor([     0.0000,      0.0000,      0.0000, 9999999999999999860310597602564577717002641838126363875249660735883565852672743849064846414228960666786379280392654615393353172850252103336275952370615397010730691664689375178569039851073146339641623266071126720011020169553304018596457812688561947201171488461172921822139066929851282122002676667750021070848.0000, 100000000000000001097906362944045541740492309677311846336810682903157585404911491537163328978494688899061249669721172515611590283743140088328307009198146046031271664502933027185697489699588559043338384466165001178426897626212945177628091195786707458122783970171784415105291802893207873272974885715430223118336.0000,
Feb 10 00:22:38                   inf], dtype=torch.float64) : To accept the new output, re-run test with envvar EXPECTTEST_ACCEPT=1 (we recommend staging/committing your changes before doing this)
Feb 10 00:22:38
```

**Comment by xmnlab** [comment]
thanks for the feedback @ezyang . It seems it is working now!

**Review by fmassa — APPROVED** [review]
Thanks a lot!

**Pull request closed without merging**
