### PR TITLE
Enable CircleCI for Linux jobs

### PR DESCRIPTION
**Pull request by yf225**
Changes in this PR:
1. Intermediate Docker image is shared from build stage to test stage through ECR, in order to fix the Caffe2 flaky CUDA tests.
2. There are ~7 Caffe2 operator tests that are only flaky in `caffe2_py2_gcc4_8_ubuntu14_04_test` on CPU. Disabling those tests on that config only, which is okay to do because we are still running those tests in other test jobs.

After this PR is merged, CircleCI will be running on master automatically, and will be running on PRs if the author rebased their PR onto the newest master (which we will ask all the authors to do when we switch off Jenkins for Linux).

### CODE REVIEW

**Comment by ezyang** [comment]
I can't do a proper review of the yml, because it's already checked in, but we're due for one.

https://github.com/pytorch/pytorch/blob/63b8ac1ff168089026201e11a113bb8b5d0b91cf/.circleci/config.yml#L12

This seems like an outlandishly large timeout for a git merge

https://github.com/pytorch/pytorch/blob/63b8ac1ff168089026201e11a113bb8b5d0b91cf/.circleci/config.yml#L22

Use `git rev-parse origin/master` instead. Much shorter, and it's appropriate use of Git plumbing. https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain

> https://github.com/pytorch/pytorch/blob/63b8ac1ff168089026201e11a113bb8b5d0b91cf/.circleci/config.yml#L27

Shouldn't you already be checked out at this point?

> https://github.com/pytorch/pytorch/blob/63b8ac1ff168089026201e11a113bb8b5d0b91cf/.circleci/config.yml#L28

And if you just checked out that commit, why do you need to do a hard reset?

> https://github.com/pytorch/pytorch/blob/63b8ac1ff168089026201e11a113bb8b5d0b91cf/.circleci/config.yml#L34

LOL. I guess it will be forever immortalized in our Docker images haha.

> https://github.com/pytorch/pytorch/blob/63b8ac1ff168089026201e11a113bb8b5d0b91cf/.circleci/config.yml#L41

`no_output_timeout` here is appropriate, but it still seems ludicrously high. There are a bunch more of these which I will no longer comment on.

https://github.com/pytorch/pytorch/blob/63b8ac1ff168089026201e11a113bb8b5d0b91cf/.circleci/config.yml#L116

I'd quite like to get rid of this ASAP.

https://github.com/pytorch/pytorch/blob/63b8ac1ff168089026201e11a113bb8b5d0b91cf/.circleci/config.yml#L119

You're pushing Docker now. Do you need this?

https://github.com/pytorch/pytorch/blob/63b8ac1ff168089026201e11a113bb8b5d0b91cf/.circleci/config.yml#L132

Hmm?

https://github.com/pytorch/pytorch/blob/63b8ac1ff168089026201e11a113bb8b5d0b91cf/.circleci/config.yml#L142

The copypasta BUUURNS

https://github.com/pytorch/pytorch/blob/63b8ac1ff168089026201e11a113bb8b5d0b91cf/.circleci/config.yml#L338

WTF! (No action needed)

https://github.com/pytorch/pytorch/blob/63b8ac1ff168089026201e11a113bb8b5d0b91cf/.circleci/config.yml#L472

Doesn't this mean DockerVersion updates are broken now?

**Comment by ezyang** [comment]
So, what's the deployment plan? How long will we run them side-by-side before switching Jenkins off?

**Review by ezyang — APPROVED** [review]
I'd quite like to see the copy-pasting reduced dramatically, but I'm giving approval to land.

**Comment by yf225** [comment]
@ezyang Remaining issues are tracked in https://github.com/pytorch/pytorch/issues/12396. 

For deployment, I am thinking of making an internal post on Monday, and then make a clean switch from Jenkins to CircleCI on the same day (probably at a set time such as 4pm PT).

**Comment by yf225** [comment]
@ezyang Yes DockerVersion will be broken and we will need to open a PR to update the Docker image version. It might be a good idea to have the Jenkins Docker image build job automatically open a PR to test the new image on PyTorch master.

**Comment by yf225** [comment]
@ezyang  Yes DockerVersion will be broken and in the short term we will need to open a PR to update the Docker image version. In the long term we might want to make the following change:

Right now the Docker image push flow is "create a new image" -> "test against master" -> "push to ECR" -> "update DockerVersion.groovy". But once all Linux jobs are removed from Jenkins, we might want to do "create a new image" -> "push to ECR" -> "open PR to test against master" -> "merge new image version number into master config.yml". For the ECR clean up job in Jenkins, we will let it check the newest version number from PyTorch repo and do the clean up accordingly.

**Pull request closed without merging**
