### PR TITLE
Simplify by using yield from

### PR DESCRIPTION
**Pull request by kit1980**
The issues were found by SIM104 flake8-simplify in a local run.

I'll take a look on adding the check to the CI separately.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by Skylion007** [comment]
Hmm, I did a sweep with ruff a few weeks ago using it's pyupgrade rules. Surprised it missed so many of them.

**Comment by Skylion007** [comment]
@kit1980 Was planning on adding this check to the CI as well along with SIM101.

**Review by Skylion007 — APPROVED** [review]

**Comment by kit1980** [comment]
> @kit1980 Was planning on adding this check to the CI as well along with SIM101.

Feel free to go ahead, mention me on the PRs.

**Pull request closed without merging**
