### PR TITLE
torchbench mfu mem bandwidth+ refactors

### PR DESCRIPTION
**Pull request by msaroufim**
```
(sourcetorch) ubuntu@ip-172-31-1-136:~/pytorch$ ./benchmarks/dynamo/torchbench.py --inference --performance --no-skip --inductor --freezing --only stable_diffusion

cuda eval  stable_diffusion                   
Average memory bandwidth per image over 1 samples: 107.47 GB/s
Model FLOPS: 0.48736161619492085 TF/s
```

EDIT: 

I'm angrily refactoring, we can probably just merge by rebasing at https://github.com/pytorch/pytorch/pull/108296/commits/6019d5a559d9a7ef167e5b151614057f5619f5e4

or I might just do https://github.com/pytorch/pytorch/pull/108296/commits/34145b169ac234ca64ca2cd669101a699245521d in a seperate PR

EDIT 2: These numbers are quite low so either its well known for stable diffusion or a bug in my measurement, will baseline with llama instead

EDIT 3: I will research and summarize other implementations of the metric, try to find a denominator for MFU and finally run a larger sweep, it is expected for most blueberries models that mfu will be low since we are doing bs=1 so need to find other things

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @anijain2305 @Xia-Weiwen

### CODE REVIEW

**Comment by msaroufim** [comment]
Hi @huydhn I have a csv now generated here in `inductor.csv`, still need to figure out how to populate the right values in here but FWIW there is another csv called `speedup.csv` that I don' see generated but presumably having extra metrics be `inductor.csv` should be fine?

```
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,mfu,memory_bandwidth,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks
cuda,stable_diffusion,1,3.399763,3.503325,28.994158,0.903388,2.735140,3.027649,,,824,1,0,0

```

**Comment by huydhn** [comment]
> Hi @huydhn I have a csv now generated here in `inductor.csv`, I'm still verifying the correctness of the metrics but we can talk about dashboarding now
> 
> ```
> dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,mfu,memory_bandwidth,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks
> cuda,stable_diffusion,1,3.557110,3.501880,29.101869,0.903388,2.735140,3.027649,0.510545,107.332520,824,1,0,0
> ```

This looks good to me. The two new field `mfu` and `memory_bandwidth` will be ingested automatically into https://console.rockset.com/collections/details/inductor.torch_dynamo_perf_stats.  The current dashboard can pick them up.  I will start working on that using some dummy data for these two fields.

To actually populate them with real data, we will need to run one around of perf benchmark with this PR using your dev branch `msaroufim/mfu2` https://github.com/pytorch/pytorch/actions/workflows/inductor-perf-test-nightly.yml.  Only results from that workflow is uploaded to Rockset.

**Review by cpuhrsch — APPROVED** [review]

**Comment by msaroufim** [comment]
The numbers are low but i suspect this might be expected for stable diffusion so running https://github.com/pytorch/pytorch/actions/runs/6303288952 to see if this applies to all models

**Comment by msaroufim** [comment]
I'm no longer spending time on the compilers dashboard so gonna close this in case someone else wants to pick this up, the main issue was the numbers seemed too low but that might be expected behavior

**Pull request closed without merging**
