### PR TITLE
[ONNX] Add constant folding to ONNX graph during export

### PR DESCRIPTION
**Pull request by spandantiwari**
This PR adds the ability to do constant folding on ONNX graphs during PT->ONNX export. This is done mainly to optimize the graph and make it leaner. The two attached snapshots show a multiple-node LSTM model before and after constant folding. 
A couple of notes:
1. Constant folding is by default turned off for now. The goal is to turn it on by default once we have validated it through all the tests.
2. Support for folding in nested blocks is not in place, but will be added in the future. 

**Original Model:**
multiple_lstm_original
**Constant-folded model:**
multiple_lstm_constant_folded

### CODE REVIEW

**Comment by suo** [comment]
Thanks for this PR! We actually prefer optimization passes to be written in C++, for consistency and so that we can track/evolve them in sync with each other. Do you think you could take a crack at that?

**Comment by spandantiwari** [comment]
Hi @suo - we have been working with @houseroad on this for a while and it was deliberate decision to write this in Python (first thought was to write in C++), mainly so that we can easily leverage the backend op implementations without core headers leaking into the ONNX passes. Maybe @houseroad can comment more?

**Comment by eellison** [comment]
In addition to what Michael said - it might be helpful to look at the existing constant_propagation pass. That pass covers a few edge cases that aren't handled here, like non deterministic ops & ops with side effects.

**Comment by spandantiwari** [comment]
@eellison - Thanks for the feedback. IIRC, constant_propagation handles the non-deterministic and side-effect ops by bypassing them. If my understanding is correct, then it is the same way these ops are handled in this pass as well.

**Review by suo — CHANGES_REQUESTED** [review]
flipping back to you pending the changes we discussed.

**Comment by BowenBao** [comment]
Closing as outdated.

**Pull request closed without merging**
