### PR TITLE
Determine the amount of memory to be allocated by `CUDACachingAllocator` prior to allocation and expose `cudaMemGetInfo`

### PR DESCRIPTION
**Pull request by coreylammie**
This PR aims to address two issues:

1. The exact amount of memory required to store a tensor/object using CUDA cannot easily be determined prior to allocation using `CUDACachingAllocator`. This can be problematic if a user would like to check if a tensor/object is able to fit on a given device, or would like to check how much memory a tensor/object requires (using the Python API).
2. The free usable memory of a CUDA device cannot easily be determined without raising an out-of-memory error. While `total_memory`, `reserved_memory`, and `allocated_memory` are easily accessible, these do not reflect the free usable memory of a device, on which new tensors/objects can be stored.

`torch.cuda.caching_allocator_det_malloc` can be used to determine how many bytes will be allocated by `CUDACachingAllocator` for a tensor/object of a specified size. The optional boolean argument `warn_if_exceeds_free_memory_capacity` is used to (if set to `true`) raise a warning if the number of bytes required to store the object/tensor on a device is larger than the free usable memory of the device.

`torch._C._cuda_cudaDetDeviceFreeMemory` exposes `cudaMemGetInfo` and determines the free usable memory of a CUDA device.

While various third party tools, such as https://github.com/Stonesjtu/pytorch_memlab and https://github.com/Oldpan/Pytorch-Memory-Utils can be used to track memory usage, they are unable to accurately account the `reserved_memory` on CUDA devices, and cannot accurately report the free usable memory of a CUDA device and consequently, the maximum size of a tensor/object that can be stored.

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Related: https://github.com/pytorch/pytorch/issues/50722

**Comment by ezyang** [comment]
While I am somewhat sympathetic to the stated goals in the PR, this PR is going to need some work (for example, it looks like this is leaking Block allocations when called) and I'd like to first figure out why some of the other options didn't work. In your particular case, why does catching OOMs get you in trouble? Does #44742 help solve whatever problem you have?

**Comment by coreylammie** [comment]
@ezyang catching OOMs does work, however, it is far from ideal. Currently (to the best of my knowledge), to determine the exact amount of memory required to store a object/tensor using CUDA, a user would have to:

1. Determine the total amount of allocated bytes using `torch.cuda.memory_stats_as_nested_dict`.
2. Instantiate/define the tensor/object to determine the memory usage of.
3. Determine the memory used by re-determining the total amount of allocated bytes using `torch.cuda.memory_stats_as_nested_dict`, and subtracting it from that prior to instantiating/defining the tensor/object.
4. Delete the tensor/object.
5. Empty the cuda cache.

An example is provided below for a tensor with 1,000,000 elements for `torch.device('cuda:0')`:

```
memory_init = torch.cuda.memory_stats_as_nested_dict(0)["allocated_bytes"]["all"]["current"]
try:
    t = torch.zeros(size=(1000 ,1000), device=torch.device('cuda:0'))
    memory_used = (torch.cuda.memory_stats_as_nested_dict(0)["allocated_bytes"]["all"]["current"] - memory_init)
    del t
except:
    memory_used = None # The tensor/object does not fit on the currently selected device.
torch.cuda.empty_cache()
```

I agree that creating a new block object in `size_t det_malloc(int device, size_t size, cudaStream_t stream)` should be avoided if possible. My current understanding is that `params.block` cannot easily be freed, as `free` depends on and alters some properties of `params`, which has not been updated as in `malloc`. `params.block` should be deletable, as it is simply an instance of `Block`.

#44742 looks like it would definitely help with fragmentation! Predicting the behaviour of the CUDA Caching Allocator efficiently using the Python API may be possible if #44742 is integrated, however, some additional functions may have to be exposed. 

The free usable memory of a CUDA device would still not be entirely predictable without using external approaches, such as that discussed in #50722.

**Comment by ezyang** [comment]
A binding for cudaMemGetInfo is reasonably easy sell for me (though I probably would bikeshed where you'd put it and how you'd name it; no det in the name, it is an independent concept), maybe you want to split that into its own PR.

Maybe this can be implemented in a more accurate and less likely to break way by having this be some sort of "dry run" flag in the allocator, where it runs through the same logic but then when it comes to actually making changes to the blocks it bails out.

**Comment by coreylammie** [comment]
I have created a second pull request, as suggested (#58635) to bind `cudaMemGetInfo`. Feel free to advise if any further changes are required there. I'm happy to continue working on the first issue using this pull request, or for this pull request to be closed and to create another solely for the first issue. Please advise what is preferred.

In your opinion, would it be best to add another (optional) input argument (bool) to `Block* malloc(int device, size_t size, cudaStream_t stream)` on line 370 of `c10.cuda.CUDACachingAllocator.cpp`? There are multiple possible entry points to use.

**Comment by ngimel** [comment]
I'm also unconvinced what problem determining "the exact amount of memory required to store a object/tensor using CUDA" is solving. Even given this knowledge subsequent allocation may or may not succeed, and the amount calculated may or may not be correct, depending on what other allocations happened between the "dry run" call and actual allocation call.

**Pull request closed without merging**
