### PR TITLE
[RESUBMIT] [pytorch] Migrating index_add cuda to ATen

### PR DESCRIPTION
**Pull request by gchanan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#33548 [RESUBMIT] [pytorch] Migrating index_add cuda to ATen**

Summary:
Mostly just moved code.
Index dim and number of indices checks are added to make checks idential to index_add_cpu_

This is a resubmit of #30573, which got reverted.

Differential Revision: [D20002248](https://our.internmc.facebook.com/intern/diff/D20002248)

### CODE REVIEW

**Comment by albanD** [comment]
What is the difference with the original PR, why was it reverted?

**Comment by gchanan** [comment]
@albanD: I don't know, that's what I'm trying to figure out :).

One thing I noticed from the original diff is that it deletes too much code...

**Comment by gchanan** [comment]
ok it looks like the other problem (besides deleting too much code) was that canUse32BitIndexing doesn't work with 0-numel tensors -- that should be fixed now.

**Comment by gchanan** [comment]
@VitalyFedyunin can you review this since you reviewed https://github.com/pytorch/pytorch/pull/30573?

**Review by VitalyFedyunin — APPROVED** [review]

**Pull request closed without merging**
