### PR TITLE
[TEST] update NVIDIA driver in CI to 525.105.17

### PR DESCRIPTION
**Pull request by ptrblck**
Updates the NVIDIA driver to `525.105.17` (the current Datacenter driver) for CUDA 12.x

CC @malfet @atalman

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!  This driver has proven to be quite stable in the pass few days after we start to use it in the CI https://github.com/pytorch/test-infra/pull/3968

**Review by atalman — APPROVED** [review]
LGTM

**Comment by atalman** [comment]
Not sure if this code is used now at all. I think it was migrated to: https://github.com/pytorch/test-infra/blob/main/.github/actions/setup-nvidia/action.yml#L10

**Comment by kit1980** [comment]
@atalman Should we merge this?

**Pull request closed without merging**
