### PR TITLE
[dynamo] Add missing _nonvar_fields annotations

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #122219
* #122218

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Review by anijain2305 — APPROVED** [review]
How does this help?

**Comment by jansel** [comment]
It makes VariableTracker.visit/apply/realize_all not need to inspect certain attributes.

**Pull request closed without merging**
