### PR TITLE
match sdpa patterns from HF

### PR DESCRIPTION
**Pull request by ngimel**
Adds sdpa patterns seen in HF models. 

To actually make the patterns match, we need constant folding to remove addition of all-zeros mask, and figure out what to do with low mem dropout. 

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by izaitsevfb** [comment]
@ngimel, I'm terribly sorry for reverting it again, please feel free to reland after #100064 is reverted. Please coordinate with @jansel regarding inductor test failures, looks like the issues you had previously are the same his change is having.

**Comment by izaitsevfb** [comment]
Hi @ngimel, I'm sorry for reverting this again, please check the D45973031 for the revert context (`inductor:split_cat_fx_passes` failures). Please ping me tomorrow, I'll help re-testing your changes internally so we can finally land them safely.

**Pull request closed without merging**
