### PR TITLE
Temporary fix for determinant bug on CPU

### LINKED ISSUE #34061: Incorrect det value on CPU
## 🐛 Bug

Incorrect det value on CPU

## To Reproduce

```
import torch

torch.manual_seed(0)

for N in [100,350,400,401]:
    W = torch.qr(torch.FloatTensor(N, N).normal_())[0]
    print('C = {}, det on cpu/gpu = {:.6f} / {:.6f}'.format(N,W.det(),W.cuda().det()))
```

## Expected behavior

```
C = 100, det on cpu/gpu = -0.999999 / -0.999999
C = 350, det on cpu/gpu = -173.111664 / -1.000001
C = 400, det on cpu/gpu = -0.000000 / -1.000002
C = 401, det on cpu/gpu = 0.000000 / 1.000001
```

## Environment

```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: 
GPU 0: GeForce GTX 1060 6GB
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 440.44
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.4.0
[pip3] torchaudio==0.5.0a0+ac5dd79
[pip3] torchvision==0.5.0
[pip3] warpctc-pytorch==0.1
[conda] Could not collect
```

cc @VitalyFedyunin @vishwakftw @SsnL @jianyuh

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:
- Make diagonal contiguous

Temporarily Fixes #34061

### CODE REVIEW

**Comment by vishwakftw** [comment]
@ezyang @gchanan could you please review this PR?

**Comment by ezyang** [comment]
Sure. But can we get a test?

**Comment by vishwakftw** [comment]
Sure, I'll add it, and ping you.

**Comment by ezyang** [comment]
rebase on master to fix the docker problems

**Comment by vishwakftw** [comment]
ROCM test failure is unrelated. cc: @ezyang

**Review by ezyang — APPROVED** [review]

**Comment by mruberry** [comment]
Unlanding. This appears to have broken the slow test build. You can likely reproduce this failure locally by setting PYTORCH_TEST_WITH_SLOW=1 before running test_torch.py. Failing log:

Jul 15 06:19:32 ======================================================================
Jul 15 06:19:32 ERROR [0.018s]: test_det_logdet_slogdet_cpu_float64 (__main__.TestTorchDeviceTypeCPU)
Jul 15 06:19:32 ----------------------------------------------------------------------
Jul 15 06:19:32 Traceback (most recent call last):
Jul 15 06:19:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 241, in instantiated_test
Jul 15 06:19:32     result = test(self, device_arg, dtype)
Jul 15 06:19:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 463, in wrapper
Jul 15 06:19:32     fn(*args, **kwargs)
Jul 15 06:19:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
Jul 15 06:19:32     return fn(slf, device, *args, **kwargs)
Jul 15 06:19:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
Jul 15 06:19:32     return fn(slf, device, *args, **kwargs)
Jul 15 06:19:32   File "test_torch.py", line 7570, in test_det_logdet_slogdet
Jul 15 06:19:32     test_single_det(q, ref_det, ref_logabsdet, 'orthogonal')
Jul 15 06:19:32 TypeError: test_single_det() takes 3 positional arguments but 4 were given
Jul 15 06:19:32 
Jul 15 06:19:32 ======================================================================
Jul 15 06:19:32 ERROR [0.081s]: test_det_logdet_slogdet_cuda_float64 (__main__.TestTorchDeviceTypeCUDA)
Jul 15 06:19:32 ----------------------------------------------------------------------
Jul 15 06:19:32 Traceback (most recent call last):
Jul 15 06:19:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 777, in wrapper
Jul 15 06:19:32     method(*args, **kwargs)
Jul 15 06:19:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 241, in instantiated_test
Jul 15 06:19:32     result = test(self, device_arg, dtype)
Jul 15 06:19:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 463, in wrapper
Jul 15 06:19:32     fn(*args, **kwargs)
Jul 15 06:19:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
Jul 15 06:19:32     return fn(slf, device, *args, **kwargs)
Jul 15 06:19:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 411, in dep_fn
Jul 15 06:19:32     return fn(slf, device, *args, **kwargs)
Jul 15 06:19:32   File "test_torch.py", line 7570, in test_det_logdet_slogdet
Jul 15 06:19:32     test_single_det(q, ref_det, ref_logabsdet, 'orthogonal')
Jul 15 06:19:32 TypeError: test_single_det() takes 3 positional arguments but 4 were given
Jul 15 06:19:32 
Jul 15 06:19:33 ----------------------------------------------------------------------

**Comment by vishwakftw** [comment]
Oh sorry about that, I know where the bug is.

**Comment by vishwakftw** [comment]
@mruberry is there some way to run the slow tests for a PR?

**Comment by vishwakftw** [comment]
@mruberry this is my test log

```
PYTORCH_TEST_WITH_SLOW=1 pytest test/test_torch.py -k det_logdet_slogdet -v
================================================ test session starts ================================================
platform linux -- Python 3.7.3, pytest-5.0.1, py-1.8.1, pluggy-0.13.1 -- /home/vishwak/miniconda3/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/media/vishwak/Official-1/pytorch/.hypothesis/examples')
rootdir: /media/vishwak/Official-1/pytorch
plugins: hypothesis-4.23.6
collected 5973 items / 5969 deselected / 4 selected                                                                 

test/test_torch.py::TestTorchDeviceTypeCPU::test_det_logdet_slogdet_batched_cpu_float64 PASSED                [ 25%]
test/test_torch.py::TestTorchDeviceTypeCPU::test_det_logdet_slogdet_cpu_float64 PASSED                        [ 50%]
test/test_torch.py::TestTorchDeviceTypeCUDA::test_det_logdet_slogdet_batched_cuda_float64 PASSED              [ 75%]
test/test_torch.py::TestTorchDeviceTypeCUDA::test_det_logdet_slogdet_cuda_float64 PASSED                      [100%]
```

**Comment by mruberry** [comment]
@ezyang Do you want to reimport or for me to commandeer?

**Comment by ezyang** [comment]
you are always welcome to commandeer oss, no need to ask (but now that I am here, I have reimported)

**Comment by vishwakftw** [comment]
@ezyang could you please reland this PR? Thank you.

**Pull request closed without merging**
