### PR TITLE
Pin Pillow to v6 as PILLOW_VERSION is removed in v7

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #31794 Pin hypothesis package to 4.57.1 to avoid test failures
* **#31777 Pin Pillow to v6 as PILLOW_VERSION is removed in v7**

Differential Revision: [D19264247](https://our.internmc.facebook.com/intern/diff/D19264247)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Probably ok?

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit a7c21f95:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=a7c21f95f1a335fc3e49e3228ee03b52ccaf5372).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4100658) pytorch_linux_backward_compatibility_check_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=79359287) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=79359287))
<details>
<summary>
<code>Jan 02 17:28:42 The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not.</code>
</summary>

```
Jan 02 17:28:42 processing existing schema:  aten::values(Dict(str, t) self) -> (t[](*)) 
Jan 02 17:28:42 processing existing schema:  aten::values(Dict(int, t) self) -> (t[](*)) 
Jan 02 17:28:42 processing existing schema:  aten::values(Dict(float, t) self) -> (t[](*)) 
Jan 02 17:28:42 processing existing schema:  aten::values(Dict(Tensor, t) self) -> (t[](*)) 
Jan 02 17:28:42 processing existing schema:  aten::view(Tensor(a) self, int[] size) -> (Tensor(a)) 
Jan 02 17:28:42 processing existing schema:  aten::where(Tensor condition) -> (Tensor[]) 
Jan 02 17:28:42 processing existing schema:  aten::where.self(Tensor condition, Tensor self, Tensor other) -> (Tensor) 
Jan 02 17:28:42 processing existing schema:  aten::zeros_like(Tensor self, *, int? memory_format=None) -> (Tensor) 
Jan 02 17:28:42 processing existing schema:  aten::zeros_like.dtype(Tensor self, *, int dtype, int layout, Device device, bool pin_memory=False, int? memory_format=None) -> (Tensor) 
Jan 02 17:28:42 processing existing schema:  quantized::add(Tensor qa, Tensor qb, float scale, int zero_point) -> (Tensor qc) 
Jan 02 17:28:42 The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not.  
Jan 02 17:28:42  
Jan 02 17:28:42 Broken ops: [ 
Jan 02 17:28:42 	aten::_test_optional_float(Tensor self, *, float? scale=None) -> (Tensor) 
Jan 02 17:28:42 ] 
Jan 02 17:28:42 + cleanup 
Jan 02 17:28:42 + retcode=1 
Jan 02 17:28:42 + set +x 
Jan 02 17:28:42 =================== sccache compilation log =================== 
Jan 02 17:28:42 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 02 17:28:42 Compile requests                 0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by hugovk** [comment]
This is fixed in the next torchvision release, due out early next week  (https://github.com/pytorch/vision/issues/1712):

> We will be releasing a new version of PyTorch and torchvision early next week, so this should be soon fixed.

In the meantime, it's better to use Pillow 6.2.2 rather than 6.2.1, it contains security fixes.

Or `pip install "pillow<7"`

**Comment by hugovk** [comment]
[torchvision v0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0) has been released with the fix:

1. Require `torchvision>=0.5.0`
2. If Pillow was temporarily pinned, remove the pin

**Comment by ezyang** [comment]
It's still generally a good idea to pin, but we can update the pin to a newer version of pillow. @hugovk do you think you could send in a PR to do this?

**Comment by hugovk** [comment]
Sure, please see PR #32290.

**Pull request closed without merging**
