### PR TITLE
Fix wrong committer when rebase and merge

### PR DESCRIPTION
**Pull request by huydhn**
When using in the context of the merge workflow, the committer's name and email have already been set as part of the workflow, i.e. https://github.com/pytorch/pytorch/actions/runs/3754075933/jobs/6377965897:

```
git config --global user.email "pytorchmergebot@users.noreply.github.com"
git config --global user.name "PyTorch MergeBot"
```

Trying to overwrite this in tryrebase's ghstack logic would lead to the wrong committer showing up.  The fix check if the email and name have already been set so that the code doesn't overwrite them.

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by clee2000** [comment]
wont this cause https://github.com/pytorch/pytorch/issues/80635 to become an issue again?

**Comment by huydhn** [comment]
> wont this cause #80635 to become an issue again?
> 
> actually i think this is a revert + rebase issue where pr got merged -> reverted -> tried to rebase the pr but git believes that its already in the branch -> rebase results in commit "disappearing"/head to point at the branch head -> git log gets the branch head shas author (I guess it was zou in this case)

Let me figure out a way to test this before merging to confirm that it wouldn't regress #80635

**Comment by clee2000** [comment]
any reason we couldnt just reset the identity between tryrebase and trymerge? like storing the original identity and setting it back to them after running ghstack in tryrebase?

**Comment by huydhn** [comment]
> any reason we couldnt just reset the identity between tryrebase and trymerge? like storing the original identity and setting it back to them after running ghstack in tryrebase?

That sounds like a good idea.  That should be safe to do regardless of what tryrebase is doing

**Review by clee2000 — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
