### PR TITLE
[quant][core][gpu][improvement] Made plan and run for quantized cudnn conv op conform with Conv_v8.cpp

### PR DESCRIPTION
**Pull request by dzdang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #76788
* #76787
* #76518

Summary:
The workspace and plan in Conv_v8.cpp diverged from Conv.cpp after
https://github.com/pytorch/pytorch/pull/60755 landed. This PR conforms
the two files in regards to the workspace and plan.

Test Plan:
```
python test/test_quantization.py -k test_qconv2d_cudnn
```

Differential Revision: [D36121582](https://our.internmc.facebook.com/intern/diff/D36121582)

### CODE REVIEW

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36121582).

**Review by jerryzh168 — APPROVED** [review]
probably want to make the same changes to other ops as well if they are not already aligned

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36121582).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36121582).

**Comment by dzdang** [comment]
@dzdang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36121582).

**Pull request closed without merging**
