### PR TITLE
[ROCm] TunableOp more unit test follow-up - Part 2

### PR DESCRIPTION
**Pull request by naromero77amd**
More unit tests to cover TunableOp functionality.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by jeffdaily — APPROVED** [review]

**Comment by naromero77amd** [comment]
rocblas and hipblaslt test were removed since they will only work in isolation in a separate process.

**Pull request closed without merging**
