### PR TITLE
[ONNX] fixed random gerenation export

### PR DESCRIPTION
**Pull request by neginraoof**
Fixed random generator symbolics, and added rand_like.

### CODE REVIEW

**Comment by neginraoof** [comment]
@houseroad I fixed the failure in tests and resubmitted this. There was an update in the jit outplace tracing PR that needed updates in this PR. I'll watch the CI.

**Comment by neginraoof** [comment]
Failure is:
Can NOT find backward compatible schemas after changes for schema aten::_batch_norm_impl_index
This does not look related

**Comment by neginraoof** [comment]
@houseroad This PR is the re-submission of https://github.com/pytorch/pytorch/pull/28470
Tests look fine. Please review. Thanks

**Review by houseroad — APPROVED** [review]
Looks good.

**Pull request closed without merging**
