### PR TITLE
add input dim check for conv2d

### PR DESCRIPTION
**Pull request by alykhantejani**
fix for #1606

### CODE REVIEW

**Comment by soumith** [comment]
```
ERROR: test_Conv2d_missing_argument (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 1359, in test_Conv2d_missing_argument
    self.assertRaises(RuntimeError, lambda: c(None))
  File "/opt/python/3.6.1/lib/python3.6/unittest/case.py", line 728, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/opt/python/3.6.1/lib/python3.6/unittest/case.py", line 177, in handle
    callable_obj(*args, **kwargs)
  File "test_nn.py", line 1359, in <lambda>
    self.assertRaises(RuntimeError, lambda: c(None))
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 244, in forward
    self.padding, self.dilation, self.groups)
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/torch/nn/functional.py", line 41, in conv2d
    if input.dim() != 4:
AttributeError: 'NoneType' object has no attribute 'dim'
```

**Comment by alykhantejani** [comment]
I had to add the check below

```python
    if input is not None and input.dim() != 4:
        raise ValueError("Expected 4D tensor as input, got {}D tensor instead.".format(input.dim()))
```

as the usual check for None happens in the call to ConvNd, where it's too late to assert that the input should be 4D. Not super happy with this, but can't think of another, clean, way to do this.

**Comment by apaszke** [comment]
Can you add dim checks to other conv functions too?

**Comment by alykhantejani** [comment]
sure thing

**Comment by alykhantejani** [comment]
Done for convxD and conv_transposedxD.

**Review by soumith — APPROVED** [review]

**Pull request merged**
