### PR TITLE
Add support for subscripts in Python frontend

### PR DESCRIPTION
**Pull request by apaszke**

### CODE REVIEW

**Comment by ezyang** [comment]
@onnxbot retest this please

**Comment by ezyang** [comment]
Test where.

**Review by zdevito — APPROVED** [review]
Looks good. I don't see tests here so my assumption is that the other PR which merges the tests actually exercises this code.

**Comment by apaszke** [comment]
Yes, this was motivated by the next PR that unifies the tests (and is checked there)

**Pull request merged**
