### PR TITLE
Use __getattribute__ instead of __getattr__ in nn.Module

### LINKED ISSUE #13981: misleading error message for custom torch.nn.Module property (incorrect property reported as missing)
## 🐛 Bug

Properties defined in classes that inherit from `torch.nn.Module` raise a misleading error message if non-existent properties are used inside the property definition. The error message reports the incorrect property as missing.

## To Reproduce

Run the following code snippet:

```py
import torch.nn as nn

class CustomModule(nn.Module):
    def __init__(self):
        super().__init__()
    
    @property
    def property_a(self):
        return self.property_b

m = CustomModule()
print(m.property_a)
```

## Expected behavior

Running the code snippet results in the following error message:

```
AttributeError: 'CustomModule' object has no attribute 'property_a'
```

This is misleading because the missing attribute is actually `property_b`. If the same code is implemented in a class that doesn't inherit from `torch.nn.Module`, the resulting error message is more appropriate since it reports `property_b` as missing. For example:

```py
class CustomModule2:
    def __init__(self):
        pass

    @property
    def property_a(self):
        return self.property_b

m2 = CustomModule2()
print(m2.property_a)
```

Displays the following error message:

```
AttributeError: 'CustomModule2' object has no attribute 'property_b'
```

## Environment

```
PyTorch version: 1.0.0.dev20181018
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.9.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: TITAN Xp
Nvidia driver version: 390.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy (1.15.2)
[pip3] numpydoc (0.8.0)
[pip3] torch (1.0.0.dev20181018)
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.1.85_cudnn7.1.2_1  [cuda91]  pytorch
[conda] pytorch-nightly           1.0.0.dev20181018 py3.7_cuda9.0.176_cudnn7.1.2_0    pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch
```

### PR DESCRIPTION
**Pull request by asmeurer**
This allows for more informative error messages when `@property` methods raise
`AttributeError`. This is because the default behavior is to assume an
`AttributeError` means the property does not exist, and to fall back to
`__getattr__`. Hence something like

```py
    @property
    def property_a(self):
        return self.property_b # does not exist
```

on `nn.Module` or a subclass of `nn.Module` will raise an error stating that
`property_a` does not exist, because `'property_a'` is what gets passed as the
`name` to `__getattr__`. By using `__getattribute__`, we can control this behavior
(by falling back to `object.__getattribute__`), and get a more informative error
message stating that `property_b` does not exist.

The downside of this change is a performance degradation for normal attribute
lookups (by about 3x) and dynamic attribute lookups (by about 2x). Failing
attribute lookups are about the same speed. It is also possible to optimize
for dynamic attribute lookups by moving the call to `object.__getattribute__` to
the end, making them as fast as they are with `__getattr__`, but this makes
normal attribute lookups about 10x slower than with `__getattr__`. I do not know
which should be optimized for, or if the performance of attribute lookups on
`nn.Module` and its subclasses is more important than this improved error
reporting.

Fixes #13981.

I would love to get some confirmation on the performance benchmarks, and an idea if this is acceptable or not (I don't actually know how important nn.Module attribute lookups would be for performance). As far as I know, if this is not acceptable, then issue #13981 is not fixable, unless there is some other way to make my `__getattribute__` faster.

### CODE REVIEW

**Comment by fmassa** [comment]
This looks great to me, thanks for the detailed explanation!

ccing @apaszke for the performance regression on attribute lookups.

**Review by apaszke — CHANGES_REQUESTED** [review]
I understand the problem, but it's really more of a Python issue and not a PyTorch issue. In particular fixing it only in `nn.Module` subclasses won't prevent the same kind of error in all other cases (e.g. if you were to implement a custom `Dataset` or `Transform`). I think we should just live with that as there's not much we can do.

Unfortunately the attribute lookup time is *crucial* to getting good perf out of Python code, and any kind of a slow down shows up as a significant drag in the benchmarks I've been running. Thanks a lot for your patch, but I really think this shouldn't get merged 😞

**Comment by apaszke** [comment]
I'd recommend opening an issue in the Python tracker, because it's clearly an error message which should be improved.

I'm pretty confident that those changes would come with a significant performance hit for our users. I once tried messing around with changing how attribute lookups work and had to abandon my patch, because Python dict performance is quite fragile if you start doing more advanced things, and it turned out to be absolutely critical.

I'm ok with marking #13981 as wontfix.

**Comment by asmeurer** [comment]
OK. Let me know if you want anything else done around this issue.

**Pull request closed without merging**
