### PR TITLE
[ROCm] Update nightly triton-rocm pin to release branch

### PR DESCRIPTION
**Pull request by jataylo**
Update pin to tip of https://github.com/triton-lang/triton/commits/release/3.0.x/ following upstream strategy here https://github.com/pytorch/pytorch/pull/126098

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @hongxiayang

### CODE REVIEW

**Comment by jataylo** [comment]
@atalman @huydhn Do we need to worry about the upload-conda and upload-wheel failures here?
https://github.com/pytorch/pytorch/actions/runs/9704484834/job/26801889463
https://github.com/pytorch/pytorch/actions/runs/9704484834/job/26801889799

**Review by peterbell10 — COMMENTED** [review]
> .circleci/scripts/binary_upload.sh: line 28: USE_SPLIT_BUILD: unbound variable

Not your fault but the failure looks real

**Review by amjames — COMMENTED** [review]
Looks like the `USE_SPLIT_BUILD` is related to a more recent change. cc @PaliC for advice on that front.

**Comment by jataylo** [comment]
Will rebase once https://github.com/pytorch/pytorch/pull/129774 is merged

**Comment by jataylo** [comment]
@amjames @peterbell10 Issue is resolved as of https://github.com/pytorch/pytorch/pull/129774

Looks like CUDA jobs are queueing but ROCm jobs and triton wheel build jobs are passing now, would you mind approving this?

**Review by peterbell10 — APPROVED** [review]

**Pull request closed without merging**
