### PR TITLE
remove obsolete MPS compat in torch.testing.assert_close

### LINKED ISSUE #77144: Add Tensor compare support for MPS backend
### 🐛 Describe the bug

Currently the MPS backend doesn't support all the operations needed for assertEqual. So currently the tensors on `mps` are mapped to cpu and the Equal operation is performed on CPU. This issue tracks enabling all the necessary operations for MPS backend and not-falling back to CPU. This issue was currently identified [here.](https://github.com/pytorch/pytorch/pull/76725/files#r866238060)

### Versions

Python version: 3.8.11 (default, Aug  6 2021, 08:56:27)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.0
[pip3] torch==1.12.0a0+gitcfd4b64
[conda] mkl                       2021.4.0           hecd8cb5_637
[conda] mkl-include               2022.0.0           hecd8cb5_105
[conda] mkl-service               2.4.0            py38h9ed2024_0
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] nomkl                     3.0                           0
[conda] numpy                     1.21.2           py38h0fa1045_0
[conda] numpy-base                1.21.2           py38hbbe2e76_0
[conda] torch                     1.12.0a0+gitcfd4b64          pypi_0    pypi

### PR DESCRIPTION
**Pull request by pmeier**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96132
* #96131

According to https://github.com/pytorch/pytorch/issues/77144#issuecomment-1454863354, the only remaining blocker for removing the compat code was the lack of support for `torch.float64`. The previous commit in this stack removed the need for that in `torch.testing.assert_close`. Thus, this closes #77144.

### CODE REVIEW

**Review by kulinseth — APPROVED** [review]
Looks good.

**Review by kulinseth — COMMENTED** [review]
Change looks good. I added the ciflow/mps tag to enable testing

**Comment by pmeier** [comment]
The MPS failures look unrelated. @kulinseth can you confirm?

**Comment by kulinseth** [comment]
> The MPS failures look unrelated. @kulinseth can you confirm?

Trying locally.

**Comment by kulinseth** [comment]
@pmeier , unfortunately, there is a [bug](https://github.com/pytorch/pytorch/issues/95538) in MPS with reduction (`all`) for >4 dimensions, its currently crashing. In this test cdist is doing assertClose on 5 dims, leading to this crash.. I will priortize fixing this , then we can unblock this .

**Comment by pmeier** [comment]
We can probably close this in favor of the PR that fixes #95538, since that will trigger 

https://github.com/pytorch/pytorch/blob/238b06086fd2ccdbe93f863437041db9507cbc55/test/test_mps.py#L10083-L10084

@kulinseth feel free to copy my patch from this PR into your fix.

**Pull request closed without merging**
