### PR TITLE
Test if descriptions of args are in the template

### PR DESCRIPTION
**Pull request by kianasun**
As in #23439, some descriptions of arguments in `_torch_docs.py` have been replaced by `common_args`, it would be helpful to check if any descriptions can be replaced for new docs in the future.

### CODE REVIEW

**Comment by kianasun** [comment]
@ezyang any chance to be reviewed? Thanks :)

**Comment by ezyang** [comment]
This looks generally good, but before merging I'd like to know: if I'm adding a doc for an argument, and for some reason, I *don't* want the default to be used. Is there any recourse in this situation? (A valid answer is no; I just want this to be acknowledged, so that if it happens, the victim knows what to do.) Is this situation impossible to occur?

**Comment by kianasun** [comment]
@ezyang If the added doc for this argument has an exactly match in the common(default) docs, then the answer is no. But if they are exactly same, why don't we use the default one.

**Review by ezyang — APPROVED** [review]

**Comment by cpuhrsch** [comment]
Needs a rebase because of a mismatch between pyro versions

**Comment by ezyang** [comment]
@cpuhrsch Pyro versions?

**Pull request closed without merging**
