### PR TITLE
[sparse][semi-structured] enable fp32 support, separate sparse and dense constraints

### PR DESCRIPTION
**Pull request by jcaip**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #115550

Summary:

Both cuSPASRELt and CUTLASS support 1:2 semi-structured sparsity for
fp32, which this PR enables.(thanks @alexsamardzic).

Furthermore, this PR also updates the sparse_config to take into account
the different shape constraints for sparse and dense matrices.

Technically, cuSPARSELt supports smaller sparse matrix constraints as it
seens to pad to the CUTLASS constraints under the hood. However, in
practice small sparse matrices are not commonly used and we care more
about the dense constraints for LLM inference.

For now, we keep the CUTLASS constraints in place for both cuSPARSELt
and CUTLASS tensors

This PR also reconnects the _FUSE_TRANSPOSE flag for cuSPARSELt tensors.

Test Plan:
```
python test/test_sparse_semi_structured.py
```

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Review by cpuhrsch — APPROVED** [review]

**Comment by alexsamardzic** [comment]
It should be simple to enable float32 support for CUTLASS back-end, so let me check if we can include it through this PR too.

Also, eventual input shapes limitations should be dictated by hardware, thus common between the two libraries.  I mean: as far as I know, CUTLASS is not doing any padding - what about cuSPARSELt?  In any case, let's re-check this too.

**Comment by jcaip** [comment]
@alexsamardzic CUTLASS fp32 woudl be great :) Does CUTLASS have shape constraints on the dense matrix? That's the only case where we pad currently, for both cutlass and cusparselt.

**Comment by alexsamardzic** [comment]
Yes, CUTLASS has various constraints for both dense and sparse case (for the record, these are encapsulated in `can_implement()` method overrides for various classes [here](https://github.com/NVIDIA/cutlass/tree/main/include/cutlass/gemm/kernel)).  The constraints are mostly about the alignment of operands, but some are related to the shapes (`m`,`n`,`k`) of operands too - but as mentioned above, these are dictated by the size of tiles that corresponding tensor core PTX instructions can handle, so should be common between both libraries.  This is what we should check.  I tried to consolidate these tests, and put them in my PyTorch implementation of the sparse linear operator, to be executed before CUTLASS checks for them - namely, CUTLASS error messages are rather cryptic, so I tried to provide more elaborate error messages.  Maybe I made some of these checks too strict.

**Comment by alexsamardzic** [comment]
OK, I have patch adding float32 in C++ code ready.  I need to implement the conversion routines now, which includes shuffling of metadata values into appropriate layout - I'll need some time for this, please bear with me.

**Comment by jcaip** [comment]
Ah I forgot, but there is an additional bit of padding that cuSPARSELt does for the metadata when the sparse rows/cols is not a 128x64 multiple, which I think accounts for the supported shape discrepancy. I think it's also why we can't use the simple 9/16th ratio for all our compressedSize calculations.

I do think your CUTLASS shape constraints are correct, but I don't think our test cases hit the small sparse matrix case. This is also unlikely to be used in the wild. 

For cuSPARSELt, the shape constrains are:

```
SPARSE:
rows, cols, and ld must be a multiple of

32 if valueType is CUDA_R_I8
16 if valueType is CUDA_R_16F, or CUDA_R_16BF
8 if valueType is CUDA_R_32F
The total size of the matrix cannot exceed:

2^{32}-1 elements for CUDA_R_8I
2^{31}-1 elements for CUDA_R_16F or CUDA_R_16BF
2^{30}-1 elements for CUDA_R_32F

DENSE:
rows, cols, and ld must be a multiple of

16 if valueType is CUDA_R_I8
8 if valueType is CUDA_R_16F or CUDA_R_16BF
4 if valueType is CUDA_R_32F
The total size of the matrix cannot exceed:

2^{32}-1 elements for CUDA_R_8I
2^{31}-1 elements for CUDA_R_16F or CUDA_R_16BF
2^{30}-1 elements for CUDA_R_32F

```
Also, I didn't realize that there were different constraints for the sparse and dense matrix respectively, which I have updated the PR to reflect.

**Comment by jcaip** [comment]
Thanks, this patch appears to be working for me and I've included it in the PR. Regarding the shapes: that sounds good to me. Let's make them consistent for now and if someone requests we can turn on cuSPARSELt for the smaller shapes.

**Comment by alexsamardzic** [comment]
Thanks @jcaip.  After lots of runs, I see`test_linear_cutlass` failing in couple cases, so please let me investigate it before you merge.

**Comment by alexsamardzic** [comment]
Haven't found anything wrong with my updates yet, but was able to reproduce the problem within sparse GEMM example from CUTLASS source tree, so reported an [issue](https://github.com/NVIDIA/cutlass/issues/1270) there.

**Comment by alexsamardzic** [comment]
> @jcaip: Would you mind to run [bug.txt](https://github.com/pytorch/pytorch/files/13674712/bug.txt) on your setup (please rename to .py)? It's a minimal reproducer, but for me it reports the same error both for cuSPARSELt and CUTLASS.

Ah, sorry - never mind: just learned about `torch.backends.cuda.matmul.allow_tf32`, that make it possible to confirm that sparse GEMM result matches with dense GEMM result if dense GEMM force to use tf32 precision; so it makes sense that both cuSPARSELt and CUTLASS produced results are different from dense GEMM result in the same way.  Let me update the test, and we should be fine...

**Comment by alexsamardzic** [comment]
Corrections/clarifications regarding updated commit message:

1. The hardware requires 1:2 sparsity for FP32, so it's not about that anything misses in FP32 support that I added for CUTLASS back-end.  Same requirement has to hold for cuSPARSELt.  The `test_sparsity_semi_structured.py` was already creating 1:2 sparse inputs, so there was not need to change anything there (1:2 is stricter requirement than 2:4, namely 1:2 pattern is always 2:4, while 2:4 pattern doesn't have to be 1:2).
2. My suggestion was to change size constraints to those that cuSPARSELt support, and test this.  I can do that, as soon as I update FP32 test for CUTLASS back-end.

**Comment by alexsamardzic** [comment]
Here is [patch](https://github.com/pytorch/pytorch/files/13675744/diff.txt) with my latest FP32 updates for CUTLASS (including fixing the tests, that I mentioned above), to be applied on top of this PR (please let me know if you'd prefer that I try to make updates to this PR myself - I'm not sure is it allowed to push to stacks to other people, so this is why I'm sending patches instead.)

I'll now try to change size constraints to these required to cuSPARSELt, and see what happens.

**Comment by jcaip** [comment]
cc @alexsamardzic I just updated the PR and added in a test for the min shapes, see `test_min_sparse_shape`, It looks like this is failing for CUTLASS on conversion functions, even when I remove the checking.

**Comment by jcaip** [comment]
> Here is [patch](https://github.com/pytorch/pytorch/files/13675744/diff.txt) with my latest FP32 updates for CUTLASS (including fixing the tests, that I mentioned above), to be applied on top of this PR (please let me know if you'd prefer that I try to make updates to this PR myself - I'm not sure is it allowed to push to stacks to other people, so this is why I'm sending patches instead.)

Feel free to update the PR.

**Comment by alexsamardzic** [comment]
> cc @alexsamardzic I just updated the PR and added in a test for the min shapes, see `test_min_sparse_shape`, It looks like this is failing for CUTLASS on conversion functions, even when I remove the checking.

Thanks, am looking into failures.

**Comment by alexsamardzic** [comment]
So, as far as CUTLASS min shape constraints concerned, here is the configuration that would make it pass the test:
```
_DTYPE_TO_SEMI_STRUCTURED_SPARSE_CONFIG = {
    torch.int8: _SEMI_STRUCTURED_SPARSE_CONFIG(16, 128, 16, 16),
    torch.float16: _SEMI_STRUCTURED_SPARSE_CONFIG(32, 64, 8, 8),
    torch.bfloat16: _SEMI_STRUCTURED_SPARSE_CONFIG(32, 64, 8, 8),
    torch.float32: _SEMI_STRUCTURED_SPARSE_CONFIG(32, 32, 4, 4)
}
```
Thus, I guess we need to split these after all?

Sparse matrix constraints for CUTLASS are the same as what we had before this PR, except that I found that the number of rows for int8 could be twice smaller.  The dense matrix constraints are the same between CUTLASS and cuSPARSELt.

For our record: Number of rows of sparse matrix in CUTLASS is limited by metadata shuffling (that they claim is needed for performance reasons) - cuSPARSELt apparently keeps metadata in different layout, so the difference in constraints here is understandable.  Number of columns constraint in CUTLASS come from alignment requirements, again for metadata matrix; for cuSPARSELT this number seem to be minimal number of columns so that one value per column in metadata matrix is produced, and I guess CUTLASS is requiring more for better alignment, again for performance reasons.  (Note that by "for performance reasons" I don't mean that CUTLASS is actually faster, but that CUTLASS team made these design decisions striving for better performance).

**Comment by jcaip** [comment]
@alexsamardzic  Let's just use the CUTLASS constraints and keep them combined for now. I think we can add support for the smaller cuSPARSELt shapes if someone asks or when we separate out the CUTLASS and cuSPARSELt subclass. 

The different shape constraints are not as pressing now that we've separated out the dense and sparse shape constraints. When we were using the same constraints for both the dense and sparse matrix, I was concerned that LLM text generation performance would be negatively affected. (As the shapes for that use case are `[1, hidden] dense @ [hidden, output] sparse`. But given we have the same dense constraints that's not as important now.

**Comment by alexsamardzic** [comment]
OK, did that - please re-check that constraint now work for cuSPARSELt.

Pushed all of my latest changes, this is now good to go as far as I'm concerned.  I'll keep working on remaining FP32 related stuff for CUTLASS (`to_dense()` conversion etc.), will keep pushing to this PR, or will create new PR if this one merged.

**Comment by alexsamardzic** [comment]
It seems last two commits reverted my changes in [c75e77d](https://github.com/pytorch/pytorch/pull/115550/commits/c75e77d315d0e75ba3608fa35394be58819093bc), and then added some small edits - was that intentional?

**Comment by jcaip** [comment]
No, feel free to force push your local to restore them. I can remake my changes.

**Comment by alexsamardzic** [comment]
Just to check: you're making changes by adding commits to [gh/jcaip/56/head](https://github.com/pytorch/pytorch/tree/gh/jcaip/56/head), right?

**Comment by jcaip** [comment]
Ah I'm using [ghstack](https://github.com/ezyang/ghstack), I thought you were too. Something probably got messed up with the non-ghstack <> ghstack workflow. I'll just copy them over your changes manually then.

**Comment by alexsamardzic** [comment]
It's ok, I was using it too. I just force pushed it back to my commit, you can now re-apply your changes.

**Pull request closed without merging**
