### PR TITLE
Removed tri[lu]* tests, superseeded by OpInfos

### PR DESCRIPTION
**Pull request by fdrocha**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #84256

triu, tril, triu_indices and tril_indices had some
tests in test_tensor_creation_ops.py and test_cuda.py
that are redudant with the ones done by OpInfos for those ops.

### CODE REVIEW

**Comment by fdrocha** [comment]
@ngimel FYI, this is removing some obsoleted tests, like we discussed in https://github.com/pytorch/pytorch/pull/82819

**Review by lezcano — APPROVED** [review]
+0 −293 great stats

**Comment by fdrocha** [comment]
@ngimel could you PTAL?

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
