### PR TITLE
[ROCm] upgrade CI distributed test to ROCm 5.0

### PR DESCRIPTION
**Pull request by jeffdaily**
This change was missed by earlier CI upgrade #73105.

### CODE REVIEW

**Comment by jeffdaily** [comment]
@seemethere is there a way to trigger the rocm distributed job before it lands on master?  Also, the 1 workflow failure is not related to this PR.

**Comment by jeffdaily** [comment]
@seemethere  or @malfet can we land this one?  The recent change of having rocm distributed tests to run only against master meant our upgrade to rocm 5.0 was only partial; the upgrade PR missed editing some new files.

**Comment by jeffdaily** [comment]
@suo perhaps you could land this?

**Review by suo — APPROVED** [review]

**Comment by suo** [comment]
running the trunk CI just to check it

**Comment by suo** [comment]
image
looks like queue times are rearing their heads again :/

**Review by malfet — APPROVED** [review]
Considering that https://hud.pytorch.org/hud/pytorch/pytorch/master/0?name_filter=rocm4.5-py3.7-distr is red half of the time we should just land it and see what will happen

**Pull request closed without merging**
