### PR TITLE
[quant] Refactor to allow running tests individually from python

### PR DESCRIPTION
**Pull request by z-a-f**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#37284 [quant] Refactor to allow running tests individually from python**

Differential Revision: [D21253415](https://our.internmc.facebook.com/intern/diff/D21253415)

### CODE REVIEW

**Comment by z-a-f** [comment]
Tested using `find ./test/quantization/ -iname test_* | xargs -L1 python`

**Comment by jerryzh168** [comment]
We shouldn’t run test from individual files. You can take a look at how other PyTorch tests are structured in the folder(for example jit). You can run individual tests through test cases. E.g. python test/test_quantization.py SomeTestCase.some_test

Sent from my iPhone

On Apr 25, 2020, at 01:40, dr-ci[bot] <notifications@github.com> wrote:

﻿

💊 Build failures summary and remediations

As of commit 2d9d52b<https://github.com/pytorch/pytorch/commit/2d9d52bf0861c597cffa058bd232cc0951d20902> (more details on the Dr. CI page<https://urldefense.proofpoint.com/v2/url?u=https-3A__dr.pytorch.org_commit-2Ddetails.html-3Fsha1-3D2d9d52bf0861c597cffa058bd232cc0951d20902&d=DwMFaQ&c=5VD0RTtNlTh3ycd41b3MUw&r=INI9JSWPArivfXwmuthx0g&m=fWsxnpD1346kcyZfT9EB2IxwQcBfzwfoIMpSuoMXxS0&s=qt7t198JBEgeQER0XiP1S3pHgcnAvrguGo9n2Dj9ZKU&e=>):

________________________________

  *   1/1 failures possibly*<https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment/LIMITATIONS.md> introduced in this PR
     *   1/1 non-CircleCI failure(s)

________________________________
ci.pytorch.org: 1 failed

  *   Failed: pr/caffe2-py3.6-devtoolset7-rocmrpm-centos7-test<https://urldefense.proofpoint.com/v2/url?u=https-3A__ci.pytorch.org_jenkins_job_caffe2-2Dbuilds_job_py3.6-2Ddevtoolset7-2Drocmrpm-2Dcentos7-2Dtrigger-2Dtest_26682_&d=DwMFaQ&c=5VD0RTtNlTh3ycd41b3MUw&r=INI9JSWPArivfXwmuthx0g&m=fWsxnpD1346kcyZfT9EB2IxwQcBfzwfoIMpSuoMXxS0&s=LU6G_pJCvM2emBb88iaOZ8gzh2GILSSkonKksrlftHs&e=>

________________________________
This comment was automatically generated by Dr. CI<https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment/README.md> (expand for details).Follow this link to opt-out<https://urldefense.proofpoint.com/v2/url?u=https-3A__dr.pytorch.org_admin_comments-2Dopt-2Dout.html&d=DwMFaQ&c=5VD0RTtNlTh3ycd41b3MUw&r=INI9JSWPArivfXwmuthx0g&m=fWsxnpD1346kcyZfT9EB2IxwQcBfzwfoIMpSuoMXxS0&s=IJK5Jq_qXzTVHMqf2ADHwyZD6mYGXdSLksAK5-2xUP4&e=> of these comments for your Pull Requests.

Please report bugs/suggestions on the GitHub issue tracker<https://github.com/kostmo/circleci-failure-tracker/issues>.

See how this bot performed<https://urldefense.proofpoint.com/v2/url?u=https-3A__dr.pytorch.org_posted-2Dcomment-2Ddetails.html-3Fpr-3D37284&d=DwMFaQ&c=5VD0RTtNlTh3ycd41b3MUw&r=INI9JSWPArivfXwmuthx0g&m=fWsxnpD1346kcyZfT9EB2IxwQcBfzwfoIMpSuoMXxS0&s=5kCq251RF4gSAhzFYhodwvjPBN-8kUg42U93GaYM28k&e=>.

**Comment by z-a-f** [comment]
> We shouldn’t run test from individual files. You can take a look at how other PyTorch tests are structured in the folder(for example jit). You can run individual tests through test cases. E.g. python test/test_quantization.py SomeTestCase.some_test

But sometimes you want to run the tests within a specific file, while debugging. Also this change does not introduce any overhead, while removing some of the convenience of running specific family of tests.

For example, if I make changes to the QAT, I would want to test all qat tests, while ignoring all other ones. Currently, I will need to run all tests or dig in the `test_qat_module.py` to find the names of all the classes related to the QAT.

**Comment by vkuzo** [comment]
+1, it's convenient to run tests from files or run all tests in a file during my usual workflows.  @jerryzh168 , thoughts on what are the downsides of doing this?

**Comment by jerryzh168** [comment]
There are two ways to structure tests, one is test case, the other is file. I think we can just use TestCase instead of increasing the complexity here. previously we don't have a top level `test/test_quantization.py` so we have to call individual test files, but now we have that, we can just call `test/test_quantization.py SomeTestCase`. Otherwise, we have to specify both the file and TestCase. It might not be the case here, but think about all the tests we might be running, there will be cases we just want to run one test in one test case in a given file, and in that case we don't want to remember the file and the test case and the test name. I think it will be as convenient when we get used to specifying a test case to do test?

Also I feel if we find we need to run tests on all test cases in a given file then we probably need to structure the test cases better, there are some TODOs in https://github.com/pytorch/pytorch/blob/master/test/test_quantization.py as well.

**Pull request closed without merging**
