### PR TITLE
Switch static dispatch to use extractLegacyTypeId.

### LINKED ISSUE #26764: "type id is VariableTensorId" runtime error for some mobile models
## Summary
Since PR #25597 landed some models started failing to run with mobile build with the following error:
```
type id is VariableTensorId
terminate called after throwing an instance of 'std::runtime_error'
  what():  false CHECK FAILED at ../c10/core/Backend.h
```

For the specific model the problem can be workaround if we use AutoGradMode guard + AutoNonVariableTypeMode guard around torch::jit::load().

But setting AutoNonVariableTypeMode guard before torch::jit::load() will cause some other models to fail:
```
terminating with uncaught exception of type
c10::Error: !v.defined() || v.is_variable()
INTERNAL ASSERT FAILED at../torch/csrc/jit/ir.h (t_ at ../torch/csrc/jit/ir.h:718)
```

We need find root cause and figure out a more robust solution to address both cases.

Edit 1:
PR #25597 is not the root cause. I analyzed root cause and proposed a solution on #26868 .

Edit 2:
We decided to solve this problem with #26908 + #26868.

Edit 3:
In 1.3 release we solve this problem with #27274 + #26868, we replaced #26908 with #27274 due to perf regression.

Edit 4:
We need add guard to TensorMethods.h as revealed by pytorch/android-demo-app#19.

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#26813 Switch static dispatch to use extractLegacyTypeId.**

Attempt to fix #26764

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by supriyar** [comment]
I got a chance to quickly test this out with my changes that run a quantized model. Seems like the flow now hits assertions in the code where it expects to not get a variable.

First hit - 
`abort_message: assertion "terminating with uncaught exception of type std::runtime_error: !self.is_variable() INTERNAL ASSERT FAILED at../aten/src/ATen/quantized/Quantizer.cpp`

Second hit
`abort_message: assertion "terminating with uncaught exception of type std::runtime_error: !options.is_variable() INTERNAL ASSERT FAILED at../aten/src/ATen/native/TensorFactories.cpp`

I was able to run the model after commenting out both those assert statements. I'm guessing there may be other parts of the code where similar change needs to be made.

**Comment by ezyang** [comment]
OK. So basically, this patch is a bandaid: the real problem is there is Tensor-Variable confusion somewhere in the code here, and that is triggering the asserts. While I don't feel too bad about unblocking by removing the asserts on mobile only, if this is reproducible server side it indicates a very real problem. My guess would be in the new quantization code :)

Is it at all possible to run these mobile models, but on server? That would help diagnose further,.

**Comment by ljk53** [comment]
> Is it at all possible to run these mobile models, but on server? That would help diagnose further,.

fyi, it is possible with the "scripts/build_mobile.sh" script I recently created, for exactly this purpose.
But for this specific problem it involves some other not-yet-landed changes from others so it's more complicated debugging process. I updated the issue with some new findings.

**Review by ljk53 — APPROVED** [review]
Although this along doesn't solve the root issue, it allows variable type goes through static dispatcher and fails at CHECK(!is_variable()) in ATen kernel.
I don't know what it should be ultimately after we unify variable and tensor - can TypeId ever be VariableTensorId then or there will still be some barrier to make sure it won't happen?

**Comment by ezyang** [comment]
I think this is subsumed by #26908.

**Pull request closed without merging**
