### PR TITLE
[1/N] Dynamic Shape: To enable export.aot_compile to switch between static shape and dynamic shape

### PR DESCRIPTION
**Pull request by EikanWang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #126517

cc @voznesenskym @penguinwu @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Comment by zhxchen17** [comment]
cc @angelayi

**Review by angelayi — CHANGES_REQUESTED** [review]
Hi sorry, what is the context around this change? If you want all inputs to be dynamic, you should be passing in fields to `dynamic_shapes`. Also bump on removing the `same_signature` flag. We plan to get rid of `_export_to_torch_ir`, so those flags won't be available.

**Comment by EikanWang** [comment]
> Hi sorry, what is the context around this change? If you want all inputs to be dynamic, you should be passing in fields to `dynamic_shapes`. Also bump on removing the `same_signature` flag. We plan to get rid of `_export_to_torch_ir`, so those flags won't be available.

Hi, sorry for the late reply. @angelayi Do you think it is a valid usage to produce a kernel for symbolic shapes without `dynamic_shaping` being given?

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
