### PR TITLE
[pytorch] move type_derived_methods out of anonymous namespace

### PR DESCRIPTION
**Pull request by ljk53**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #32451 [pytorch] codegen flags to whitelist op registrations / generate to separate files
* **#32275 [pytorch] move type_derived_methods out of anonymous namespace**

Summary:
Currently TypeDerived (e.g. `CPUType::`) methods are declared and
defined in anonymous namespace as they are only called from c10
dispatcher - except for STATIC_DISPATCH mode, where they can be directly
called from Functions.h.

We plan to generate c10 op registration into separate files for internal
xplat/BUCK build, thus we need declare these methods in non-anonymous
namespace.

I feel it's easier to simply change it unconditionally, unless there are
some side effect I'm not aware of - `TypeDefault::` methods are in
non-anonymous namespace anyway.

Test Plan:
- CI

Differential Revision: [D19426692](https://our.internmc.facebook.com/intern/diff/D19426692)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit ac2f4ce1:


**None of the build failures appear to be your fault**.

* **1/1** recognized as flaky :snowflake:
    * Re-run these jobs?


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=ac2f4ce191b82e82bee24b2640fa8f56601fa835).

### :snowflake: 1 failure recognized as flaky
The following build failures have been detected as flaky and **may not be your fault**:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4267668) caffe2_onnx_py3_6_clang7_ubuntu16_04_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=86874380) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=86874380)) :snowflake:
<details>
<summary>
<code>Jan 16 07:51:13 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_transpose_matmul Fatal Python error: Segmentation fault</code>
</summary>

```
Jan 16 07:51:11 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_concat PASSED [ 99%] 
Jan 16 07:51:11 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_div PASSED [ 99%] 
Jan 16 07:51:11 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_lstm PASSED [ 99%] 
Jan 16 07:51:11 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_mul PASSED [ 99%] 
Jan 16 07:51:11 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_reshape PASSED [ 99%] 
Jan 16 07:51:11 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_slice PASSED [ 99%] 
Jan 16 07:51:13 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_slice_index_exceeds_dim FAILED [ 99%] 
Jan 16 07:51:13 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_slice_negative_index PASSED [ 99%] 
Jan 16 07:51:13 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_sqrt PASSED [ 99%] 
Jan 16 07:51:13 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_transpose PASSED [ 99%] 
Jan 16 07:51:13 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_transpose_matmul Fatal Python error: Segmentation fault 
Jan 16 07:51:13  
Jan 16 07:51:13 Current thread 0x00007faa793f3700 (most recent call first): 
Jan 16 07:51:13   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 43 in repr_instance 
Jan 16 07:51:13   File "/usr/lib/python3.6/reprlib.py", line 65 in repr1 
Jan 16 07:51:13   File "/usr/lib/python3.6/reprlib.py", line 55 in repr 
Jan 16 07:51:13   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 36 in repr 
Jan 16 07:51:13   File "/usr/local/lib/python3.6/dist-packages/_pytest/_io/saferepr.py", line 67 in saferepr 
Jan 16 07:51:13   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 655 in repr_args 
Jan 16 07:51:13   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 736 in repr_traceback_entry 
Jan 16 07:51:13   File "/usr/local/lib/python3.6/dist-packages/_pytest/_code/code.py", line 777 in repr_traceback 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by ezyang — APPROVED** [review]
I'll accept this to unblock. But some context: we don't really consider the functions defined in `CPUType` namespace to be public API. I agree that they are useful functions to have on hand, since they represent how to call a backend-specific function after dispatch has already happened (maybe this means we should deify them as an API for real), but as they are right now ideally treated as an implementation detail. The use of these automatically generated wrappers for native implementations is also an anti-pattern when we consider custom extensions, which can't operate the codegen to generate these wrappers.

**Comment by ljk53** [comment]
> I'll accept this to unblock. But some context: we don't really consider the functions defined in `CPUType` namespace to be public API. I agree that they are useful functions to have on hand, since they represent how to call a backend-specific function after dispatch has already happened (maybe this means we should deify them as an API for real), but as they are right now ideally treated as an implementation detail. The use of these automatically generated wrappers for native implementations is also an anti-pattern when we consider custom extensions, which can't operate the codegen to generate these wrappers.

Thanks for the context. I can make another PR to move these APIs to at::CPUType::internal:: namespace; another option is to move these APIs to per-op-registration file as well - this way we can keep them in anonymous namespace, but it will require bigger change to the codegen.
Either way, unless we add C10_API macro they are still invisible to custom code I guess? They are visible to ATen code where we have more control to disallow using them directly.

**Comment by ezyang** [comment]
I don't think I actually have a recommended course of action here, per se. I think my main constraint is that if someone needs to do some refactoring work later that changes how CPUType works or removes it entirely, they can do so in a reasonable way. A little bit of fbcode only code depending directly here doesn't seem like a big obstacle for this kind of thing. Renaming it to `internal` seems like busy work :)

I agree that externally, if we don't mark these `C10_API`, external code can't access them. So the downside seems limited.

**Review by smessmer — APPROVED** [review]

**Pull request closed without merging**
