### PR TITLE
Remove unnecessary typing dependency.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
Companion PR for master: #16777

**Review by zou3519 — APPROVED** [review]
lgtm. @soumith should we rebuild the binaries with this?

**Comment by kevlar1818** [comment]
Maybe I'm missing something, but it looks like the setup.py still requires typing?

https://github.com/pytorch/pytorch/blob/v1.0.1/setup.py#L331

**Comment by soumith** [comment]
@kevlar1818 that's required for build-time (i.e. when compiling), but not runtime.

**Comment by fmassa** [comment]
@soumith isn't this PR the reason why the tests in https://github.com/pytorch/vision/pull/736 are failing?

**Comment by ezyang** [comment]
@fmassa  Yes, it looks exactly like this. If you manually install `typing` in your environments, that should unbreak vision CI.

**Comment by soumith** [comment]
new binaries uploaded, this should be fixed now.

**Pull request merged**
