### PR TITLE
Fix potential deadlock when recording memory traces

### PR DESCRIPTION
**Pull request by zdevito**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #95541
* #95357
* #95356
* #91336
* #90587
* __->__ #95273

See comment in the diff

Differential Revision: [D43490668](https://our.internmc.facebook.com/intern/diff/D43490668)

### CODE REVIEW

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D43490668).

**Review by eellison — APPROVED** [review]
This makes sense to me, but would it be simpler to hold the GIL on any of the APIs that interact with snapshotting ? The disclaimer on snapshotting is that is potentially very slow anyway, so we shouldn't be doing it on the hot path / in performance sensitive code.

**Comment by zdevito** [comment]
Gathering snapshots is slow, but recording trace information is fast and happens any time a tensor is allocated, freed, etc. Those pathways typically do not have the GIL on entry to the allocator and it is hard to modify them to do that even if we wanted to.

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D43490668).

**Comment by zdevito** [comment]
@zdevito has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D43490668).

**Pull request closed without merging**
