### PR TITLE
Remove backward ops for NNPACK spatial convolution

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #70305

These backward ops are currently **unused** since the backward pass for NNPACK calls `slow_conv_dilated2d` instead.

I decided to leave in the functions (not as ops) since I believe mobile may want to use them in the future, but I could be convinced to remove them entirely instead.

Differential Revision: [D33279223](https://our.internmc.facebook.com/intern/diff/D33279223)

### CODE REVIEW

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33279223).

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33279223).

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33279223).

**Review by zou3519 — APPROVED** [review]
Are the functions tested at all? If not they're probably going to bitrot (if they haven't already) so it might be better to remove them entirely. I'm fine with deleting it or keeping it

**Comment by jbschlosser** [comment]
> Are the functions tested at all? If not they're probably going to bitrot (if they haven't already) so it might be better to remove them entirely. I'm fine with deleting it or keeping it

Nope, not AFAICT. There's one test in `test_nn.py` that calls the forward `_nnpack_spatial_convolution`, but again it doesn't use these backward functions for its backward pass. I didn't see any tests internally either.

I'm happy to remove these functions. If for some reason they're needed in the future, they can be added in then.

**Comment by jbschlosser** [comment]
@jbschlosser has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33279223).

**Pull request closed without merging**
