### PR TITLE
Exposing mahalanobis distance method for the multivariate normal

### PR DESCRIPTION
**Pull request by perone**
This is just a small refactor of the `MultivariateNormal` distribution to expose the squared Mahalanobis distance API.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 26a900c2:


**None of the build failures appear to be your fault**.

* **1/1** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=462bfc7fe79be1dfca083e77ad067ea8abf48050&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base 462bfc7f since Jan 08
  <details>
  <summary>
  You may want to rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch origin viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=26a900c24cade19e3b75dff6167f979e26f0ee2e).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [pytorch_macos_10_13_py3_test](https://dr.pytorch.org/build-details.html?build_id=82294399) from Jan 08



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Review by fritzo — APPROVED** [review]

**Comment by fritzo** [comment]
Test failure appears unrelated

**Comment by perone** [comment]
Please let me know if there is anything else I should do on my side to get ir merged. Thanks !

**Comment by fritzo** [comment]
@pytestbot retest this please

**Comment by perone** [comment]
Please do not merge this yet, there is an issue in the way the testing is done that might fail randomly (singular matrix). I'll fix it and request a new review.

**Comment by perone** [comment]
Fixed, just added a multiple of the identity matrix to avoid singularities in the cov matrix.

**Review by fritzo — APPROVED** [review]

**Comment by perone** [comment]
Is there anything else required from my side ? It looks like the errors on the CI are from other modules.

**Pull request closed without merging**
