### PR TITLE
Add const modifier for lazy shape inference for boolean logic ops

### PR DESCRIPTION
**Pull request by wonjoo-wj**
Follow up to https://github.com/pytorch/pytorch/pull/78004. 

---

Trying to fully codegen these boolean logic ops on pt/xla's side, saw errors:
```
Exception: Missing shape inference function.

Please add declare this function in /workspace/pytorch/torch/csrc/lazy/core/shape_inference.h:

and implement it in the the corresponding shape_inference.cpp file.

TORCH_API std::vector<torch::lazy::Shape> compute_shape_logical_and(const at::Tensor & self, const at::Tensor & other);
TORCH_API std::vector<torch::lazy::Shape> compute_shape_logical_not(const at::Tensor & self);
TORCH_API std::vector<torch::lazy::Shape> compute_shape_logical_or(const at::Tensor & self, const at::Tensor & other);
TORCH_API std::vector<torch::lazy::Shape> compute_shape_logical_xor(const at::Tensor & self, const at::Tensor & other);
Failed to generate lazy files: ['python', '/workspace/pytorch/xla/scripts/gen_lazy_tensor.py']
```

Add const modifier for lazy shape inference for boolean logic ops

### CODE REVIEW

**Comment by wonjoolee95** [comment]
@wconstab A small follow-up to a previous PR, missed `const` qualifier before. Thanks!

**Review by wconstab — APPROVED** [review]
thanks @wonjoolee95 !

**Comment by wonjoolee95** [comment]
@wconstab I'm unable to merge this due to permission I believe (which is weird because I was able to merge PRs before in the past). Do you know if I need to be added to some extra permission? Thanks!

**Comment by wconstab** [comment]
umm, no idea, what makes you think it's due to your permissions?  iiuc there aren't really 'permissions' for use of pytorchbot, but it may be that it failed to merge due to some CI checks failing.  I do see in the logs of your failed pytorchbot merge that it complained about:

```
RuntimeError: Refusing to merge as mandatory check(s) [pull](https://github.com/pytorch/pytorch/commit/994d14562d583a66ab2ddc509d16b84bd9c2196c/checks?check_suite_id=7115224961) failed for rule superuser
```

which is not clear to me, but i suggest doing a rebase and trying again. i'll kick off the rebase now, once CI passes you can try merge again and ping me if it doesn't go through

**Pull request closed without merging**
