### PR TITLE
Remove istft python functional wrapper

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #71993

I've kept the symbol `torch.functional.istft` because it looks like public API,
but it could just as easily be moved to `_torch_docs.py`.

Moving this into its own PR until TorchScript starts recognizing `input`
as a keyword argument.

Differential Revision: [D34461399](https://our.internmc.facebook.com/intern/diff/D34461399)

### CODE REVIEW

**Comment by albanD** [comment]
cc @eellison this is breaking some models because torchscript doesn't know that the `self` argument in native_functions is actually automatically changed to `input` in the python API. See https://github.com/pytorch/pytorch/pull/61608#discussion_r794594424 for more details.

What is a way forward for this one?

**Comment by eellison** [comment]
@albanD @peterbell10 is this the same issue as https://github.com/pytorch/pytorch/issues/71994 ?

**Comment by peterbell10** [comment]
Yes, that's the one.

**Review by anjali411 — APPROVED** [review]

**Comment by anjali411** [comment]
@anjali411 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34461399).

**Pull request closed without merging**
