### PR TITLE
Pass device_type argument to do_bench as per changes to do_bench

### PR DESCRIPTION
**Pull request by anishsarum**
Recent versions of Triton's `do_bench` support passing in `device_type` such that they can use the device agnostic `DeviceInterface` provided by Torch.

This PR also moves the Triton pin forward to catch the change to `do_bench`.

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov

### CODE REVIEW

**Review by nmacchioni — CHANGES_REQUESTED** [review]
There are many calls to `benchmark.benchmark_gpu`, instead of passing the device type in each of these callsites could you instead pass it in the single call to Triton's `do_bench`? This should be located in `torch._inductor.runtime.benchmarking`

**Comment by jataylo** [comment]
Will we bring this change into release/3.0.x of triton instead of using a new commit of main?

**Comment by nmacchioni** [comment]
Yeah actually can we prefer pin updating in the process of https://github.com/pytorch/pytorch/pull/133438 @jataylo

**Comment by AnthonyBarbier** [comment]
> Yeah actually can we prefer pin updating in the process of #133438 @jataylo

The problem is that PR doesn't bring the pin forward enough: that's [the commit](https://github.com/triton-lang/triton/commit/36789d2e2ee8053f7d512a7302ea078bf5629637) we need for the `device_type` in `do_bench`

**Comment by AnthonyBarbier** [comment]
> There are many calls to `benchmark.benchmark_gpu`, instead of passing the device type in each of these callsites could you instead pass it in the single call to Triton's `do_bench`? This should be located in `torch._inductor.runtime.benchmarking`

The problem is the whole benchmarking.py module needs refactoring: it's not device agnostic, it assumes CPUs all use a callable + wallclock for timing and that everything else is a GPU.

It would probably make more sense to have some `benchmark()` method in the Inductor device interface so that each device type is free to use Triton or something else. (And provide the benchmark function that goes with whatever implementation they use)

Note: the Triton update to `do_bench()` makes the device_type optional (And it defaults to `cuda`) so not all the callsites need updating. (This PR only updates the callsites which are in the "core" part of Torch, we can start looking into refactoring benchmarking in a follow up PR if that's useful?)

**Comment by nmacchioni** [comment]
> > Yeah actually can we prefer pin updating in the process of #133438 @jataylo
> 
> The problem is that PR doesn't bring the pin forward enough: that's [the commit](https://github.com/triton-lang/triton/commit/36789d2e2ee8053f7d512a7302ea078bf5629637) we need for the `device_type` in `do_bench`

cc @jataylo any objections to using this commit instead?

**Comment by nmacchioni** [comment]
> > There are many calls to `benchmark.benchmark_gpu`, instead of passing the device type in each of these callsites could you instead pass it in the single call to Triton's `do_bench`? This should be located in `torch._inductor.runtime.benchmarking`
> 
> The problem is the whole benchmarking.py module needs refactoring: it's not device agnostic, it assumes CPUs all use a callable + wallclock for timing and that everything else is a GPU.

I would argue that the current benchmarking is device-agnostic-enough, at least until a real use case that would benefit from having customized benchmarking materializes (if you have such a use case I'd be interested to hear more!).

> It would probably make more sense to have some `benchmark()` method in the Inductor device interface so that each device type is free to use Triton or something else. (And provide the benchmark function that goes with whatever implementation they use)

Sounds good to me, although I am still in favor of having as many use cases covered in the benchmarking module. We can implement edge-case-benchmarking in the device interface, and figure out some dispatch from the benchmarking module.

> Note: the Triton update to `do_bench()` makes the device_type optional (And it defaults to `cuda`) so not all the callsites need updating. (This PR only updates the callsites which are in the "core" part of Torch, we can start looking into refactoring benchmarking in a follow up PR if that's useful?)

I'd consider anything in Inductor "core"; there are [eight](https://github.com/search?q=repo%3Apytorch%2Fpytorch+benchmarker.benchmark_gpu+path%3A%2F%5Etorch%5C%2F_inductor%5C%2F%2F&type=code) callsites to `benchmarker.benchmark_gpu` lets get them all at once.

**Comment by AnthonyBarbier** [comment]
> > > There are many calls to `benchmark.benchmark_gpu`, instead of passing the device type in each of these callsites could you instead pass it in the single call to Triton's `do_bench`? This should be located in `torch._inductor.runtime.benchmarking`
> > 
> > 
> > The problem is the whole benchmarking.py module needs refactoring: it's not device agnostic, it assumes CPUs all use a callable + wallclock for timing and that everything else is a GPU.
> 
> I would argue that the current benchmarking is device-agnostic-enough, at least until a real use case that would benefit from having customized benchmarking materializes (if you have such a use case I'd be interested to hear more!).

There is literally nothing device agnostic about the current benchmarking...
It hardcodes a ```if device_type == "cpu" then use_wallclock() else use a triton-cuda specific method``` it literally only works for 2 device types and doesn't work for any Inductor codegen other than Triton.

To make it half-agnostic (i.e device agnostic but still dependent on Triton) we'd at least need to be able to configure a device type from somewhere.

> 
> > It would probably make more sense to have some `benchmark()` method in the Inductor device interface so that each device type is free to use Triton or something else. (And provide the benchmark function that goes with whatever implementation they use)
> 
> Sounds good to me, although I am still in favor of having as many use cases covered in the benchmarking module. We can implement edge-case-benchmarking in the device interface, and figure out some dispatch from the benchmarking module.
> 
> > Note: the Triton update to `do_bench()` makes the device_type optional (And it defaults to `cuda`) so not all the callsites need updating. (This PR only updates the callsites which are in the "core" part of Torch, we can start looking into refactoring benchmarking in a follow up PR if that's useful?)
> 
> I'd consider anything in Inductor "core"; there are [eight](https://github.com/search?q=repo%3Apytorch%2Fpytorch+benchmarker.benchmark_gpu+path%3A%2F%5Etorch%5C%2F_inductor%5C%2F%2F&type=code) callsites to `benchmarker.benchmark_gpu`, let's get them all in one PR.

Actually thinking some more about it, it really depends if we think the benchmark function is device specific or codegen specific. (Right now it's a bit dodgy because `do_bench` lives in Triton which makes it codegen specific, but the content of the function doesn't contain anything Triton specific, so maybe it should be pulled into Torch instead?)
From the Torch perspective there is nothing preventing you from having different Inductor codegens for a given device type, so if the benchmark function is codegen specific then it should probably live in the Codegen interface, if we think it's just device specific then it should be pulled out of Triton into torch's device_interface?

**Comment by jataylo** [comment]
> > > Yeah actually can we prefer pin updating in the process of #133438 @jataylo
> > 
> > 
> > The problem is that PR doesn't bring the pin forward enough: that's [the commit](https://github.com/triton-lang/triton/commit/36789d2e2ee8053f7d512a7302ea078bf5629637) we need for the `device_type` in `do_bench`
> 
> cc @jataylo any objections to using this commit instead?

I thought the plan was for the triton commit to now stay on the release branch and only move to a new commit of main every other pytorch release? If we're following this strategy we'd need to get the required changes into release/3.0.x cc: @bertmaher

**Comment by nmacchioni** [comment]
> > > > Yeah actually can we prefer pin updating in the process of #133438 @jataylo
> > > 
> > > 
> > > The problem is that PR doesn't bring the pin forward enough: that's [the commit](https://github.com/triton-lang/triton/commit/36789d2e2ee8053f7d512a7302ea078bf5629637) we need for the `device_type` in `do_bench`
> > 
> > 
> > cc @jataylo any objections to using this commit instead?
> 
> I thought the plan was for the triton commit to now stay on the release branch and only move to a new commit of main every other pytorch release? If we're following this strategy we'd need to get the required changes cherry picked into release/3.0.x cc: @bertmaher

Yeah that is a good point, not sure...

**Comment by nmacchioni** [comment]
> > > > There are many calls to `benchmark.benchmark_gpu`, instead of passing the device type in each of these callsites could you instead pass it in the single call to Triton's `do_bench`? This should be located in `torch._inductor.runtime.benchmarking`
> > > 
> > > 
> > > The problem is the whole benchmarking.py module needs refactoring: it's not device agnostic, it assumes CPUs all use a callable + wallclock for timing and that everything else is a GPU.
> > 
> > 
> > I would argue that the current benchmarking is device-agnostic-enough, at least until a real use case that would benefit from having customized benchmarking materializes (if you have such a use case I'd be interested to hear more!).
> 
> There is literally nothing device agnostic about the current benchmarking... It hardcodes a `if device_type == "cpu" then use_wallclock() else use a triton-cuda specific method` it literally only works for 2 device types and doesn't work for any Inductor codegen other than Triton.

FYI the "cuda-specific" method works on both NVidia and ROCm, and I believe also XPU.

> To make it half-agnostic (i.e device agnostic but still dependent on Triton) we'd at least need to be able to configure a device type from somewhere.
> 
> > > It would probably make more sense to have some `benchmark()` method in the Inductor device interface so that each device type is free to use Triton or something else. (And provide the benchmark function that goes with whatever implementation they use)
> > 
> > 
> > Sounds good to me, although I am still in favor of having as many use cases covered in the benchmarking module. We can implement edge-case-benchmarking in the device interface, and figure out some dispatch from the benchmarking module.
> > > Note: the Triton update to `do_bench()` makes the device_type optional (And it defaults to `cuda`) so not all the callsites need updating. (This PR only updates the callsites which are in the "core" part of Torch, we can start looking into refactoring benchmarking in a follow up PR if that's useful?)
> > 
> > 
> > I'd consider anything in Inductor "core"; there are [eight](https://github.com/search?q=repo%3Apytorch%2Fpytorch+benchmarker.benchmark_gpu+path%3A%2F%5Etorch%5C%2F_inductor%5C%2F%2F&type=code) callsites to `benchmarker.benchmark_gpu`, let's get them all in one PR.
> 
> Actually thinking some more about it, it really depends if we think the benchmark function is device specific or codegen specific. (Right now it's a bit dodgy because `do_bench` lives in Triton which makes it codegen specific, but the content of the function doesn't contain anything Triton specific, so maybe it should be pulled into Torch instead?) From the Torch perspective there is nothing preventing you from having different Inductor codegens for a given device type, so if the benchmark function is codegen specific then it should probably live in the Codegen interface, if we think it's just device specific then it should be pulled out of Triton into torch's device_interface?

We will probably keep benchmarking in the benchmarking module. Benchmarking is not codegen specific, so the codegen interface is not the proper place for this; and since having to implement custom benchmarkers for certain devices (I have still not heard your use case) is most definitely the odd cause, I would be opposed to moving everything to the device interface.

**Comment by AnthonyBarbier** [comment]
> > > > > There are many calls to `benchmark.benchmark_gpu`, instead of passing the device type in each of these callsites could you instead pass it in the single call to Triton's `do_bench`? This should be located in `torch._inductor.runtime.benchmarking`
> > > > 
> > > > 
> > > > The problem is the whole benchmarking.py module needs refactoring: it's not device agnostic, it assumes CPUs all use a callable + wallclock for timing and that everything else is a GPU.
> > > 
> > > 
> > > I would argue that the current benchmarking is device-agnostic-enough, at least until a real use case that would benefit from having customized benchmarking materializes (if you have such a use case I'd be interested to hear more!).
> > 
> > 
> > There is literally nothing device agnostic about the current benchmarking... It hardcodes a `if device_type == "cpu" then use_wallclock() else use a triton-cuda specific method` it literally only works for 2 device types and doesn't work for any Inductor codegen other than Triton.
> 
> FYI the "cuda-specific" method works on both NVidia and ROCm, and I believe also XPU.
> 
```
>>> import torch
>>> torch.cuda.synchronize()
[18:32:01.594] [gpex::python] [critical] AssertionError: Torch not compiled with CUDA enabled

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nethome/anthonyb/gpex/build/buildenv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 947, in synchronize
    _lazy_init()
  File "/nethome/anthonyb/gpex/build/buildenv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 305, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```
--> It doesn't work if cuda is not present, therefore it is cuda specific...


> > To make it half-agnostic (i.e device agnostic but still dependent on Triton) we'd at least need to be able to configure a device type from somewhere.
> > > > It would probably make more sense to have some `benchmark()` method in the Inductor device interface so that each device type is free to use Triton or something else. (And provide the benchmark function that goes with whatever implementation they use)
> > > 
> > > 
> > > Sounds good to me, although I am still in favor of having as many use cases covered in the benchmarking module. We can implement edge-case-benchmarking in the device interface, and figure out some dispatch from the benchmarking module.
> > > > Note: the Triton update to `do_bench()` makes the device_type optional (And it defaults to `cuda`) so not all the callsites need updating. (This PR only updates the callsites which are in the "core" part of Torch, we can start looking into refactoring benchmarking in a follow up PR if that's useful?)
> > > 
> > > 
> > > I'd consider anything in Inductor "core"; there are [eight](https://github.com/search?q=repo%3Apytorch%2Fpytorch+benchmarker.benchmark_gpu+path%3A%2F%5Etorch%5C%2F_inductor%5C%2F%2F&type=code) callsites to `benchmarker.benchmark_gpu`, let's get them all in one PR.
> > 
> > 
> > Actually thinking some more about it, it really depends if we think the benchmark function is device specific or codegen specific. (Right now it's a bit dodgy because `do_bench` lives in Triton which makes it codegen specific, but the content of the function doesn't contain anything Triton specific, so maybe it should be pulled into Torch instead?) From the Torch perspective there is nothing preventing you from having different Inductor codegens for a given device type, so if the benchmark function is codegen specific then it should probably live in the Codegen interface, if we think it's just device specific then it should be pulled out of Triton into torch's device_interface?
> 
> We will probably keep benchmarking in the benchmarking module. Benchmarking is not codegen specific, so the codegen interface is not the proper place for this; and since having to implement custom benchmarkers for certain devices (I have still not heard your use case) is most definitely the odd cause, I would be opposed to moving everything to the device interface.

Right, so benchmarking is not device specific or codegen specific, yet there is a `Benchmarker` (Which isn't used anywhere other than as a base for the Triton class?) and a `TritonBenchmarker` with two hardcoded methods: `benchmark_cpu` and `benchmark_gpu`?

This won't work for anything which is not a `cpu` and doesn't use Triton as an inductor codegen. (e.g an out of tree "ipu" backend with an interface similar to the openmp / c++ codegen?)

**Comment by nmacchioni** [comment]
> > > > > > There are many calls to `benchmark.benchmark_gpu`, instead of passing the device type in each of these callsites could you instead pass it in the single call to Triton's `do_bench`? This should be located in `torch._inductor.runtime.benchmarking`
> > > > > 
> > > > > 
> > > > > The problem is the whole benchmarking.py module needs refactoring: it's not device agnostic, it assumes CPUs all use a callable + wallclock for timing and that everything else is a GPU.
> > > > 
> > > > 
> > > > I would argue that the current benchmarking is device-agnostic-enough, at least until a real use case that would benefit from having customized benchmarking materializes (if you have such a use case I'd be interested to hear more!).
> > > 
> > > 
> > > There is literally nothing device agnostic about the current benchmarking... It hardcodes a `if device_type == "cpu" then use_wallclock() else use a triton-cuda specific method` it literally only works for 2 device types and doesn't work for any Inductor codegen other than Triton.
> > 
> > 
> > FYI the "cuda-specific" method works on both NVidia and ROCm, and I believe also XPU.
> 
> ```
> >>> import torch
> >>> torch.cuda.synchronize()
>     raise AssertionError("Torch not compiled with CUDA enabled")
> AssertionError: Torch not compiled with CUDA enabled
> ```
> 
> --> It doesn't work if cuda is not present, therefore it is cuda specific...

Not sure what more to say on this; we've been using this benchmarking format on multiple types of GPUs with no problem.

> > > To make it half-agnostic (i.e device agnostic but still dependent on Triton) we'd at least need to be able to configure a device type from somewhere.
> > > > > It would probably make more sense to have some `benchmark()` method in the Inductor device interface so that each device type is free to use Triton or something else. (And provide the benchmark function that goes with whatever implementation they use)
> > > > 
> > > > 
> > > > Sounds good to me, although I am still in favor of having as many use cases covered in the benchmarking module. We can implement edge-case-benchmarking in the device interface, and figure out some dispatch from the benchmarking module.
> > > > > Note: the Triton update to `do_bench()` makes the device_type optional (And it defaults to `cuda`) so not all the callsites need updating. (This PR only updates the callsites which are in the "core" part of Torch, we can start looking into refactoring benchmarking in a follow up PR if that's useful?)
> > > > 
> > > > 
> > > > I'd consider anything in Inductor "core"; there are [eight](https://github.com/search?q=repo%3Apytorch%2Fpytorch+benchmarker.benchmark_gpu+path%3A%2F%5Etorch%5C%2F_inductor%5C%2F%2F&type=code) callsites to `benchmarker.benchmark_gpu`, let's get them all in one PR.
> > > 
> > > 
> > > Actually thinking some more about it, it really depends if we think the benchmark function is device specific or codegen specific. (Right now it's a bit dodgy because `do_bench` lives in Triton which makes it codegen specific, but the content of the function doesn't contain anything Triton specific, so maybe it should be pulled into Torch instead?) From the Torch perspective there is nothing preventing you from having different Inductor codegens for a given device type, so if the benchmark function is codegen specific then it should probably live in the Codegen interface, if we think it's just device specific then it should be pulled out of Triton into torch's device_interface?
> > 
> > 
> > We will probably keep benchmarking in the benchmarking module. Benchmarking is not codegen specific, so the codegen interface is not the proper place for this; and since having to implement custom benchmarkers for certain devices (I have still not heard your use case) is most definitely the odd cause, I would be opposed to moving everything to the device interface.
> 
> Right, so benchmarking is not device specific or codegen specific, yet there is a `Benchmarker` (Which isn't used anywhere other than as a base for the Triton class?) and a `TritonBenchmarker` with two hardcoded methods: `benchmark_cpu` and `benchmark_gpu`?
> 
> This won't work for anything which is not a `cpu` and doesn't use Triton as an inductor codegen. (e.g an out of tree "ipu" backend with an interface similar to the openmp / c++ codegen?)

If you have a specific use case in mind that you can't share then you are welcome to implement your own benchmarking.

**Comment by galexite** [comment]
I think the crux of the matter is that this implementation is unnecessarily tied to GPUs that are CUDA-compatible. In fact, it's pretty generic and would work fine for Triton devices with just the generic device interface.

We (as a non-GPU device with a Triton implementation) would otherwise be compatible with this method, but we are not a GPU, and thus we cannot use this. We'd like to refactor it so that it no longer is tied to the "cuda" device type so that we can (and other Triton compatible devices can use this same method in the future).

So our use-case is: we are introducing Triton support to our device, we are not a GPU and therefore to make `torch.compile` available on our device we must resolve the use of GPU-specific code within Inductor where possible, like this.

We're happy to implement some of the refactoring to make this a Triton-specific (rather than a GPU-specific) method, but the simplest way of doing this for now would be to keep the code as-is but pass in the device type at the callsite.

**Comment by nmacchioni** [comment]
> I think the crux of the matter is that this implementation is unnecessarily tied to GPUs that are CUDA-compatible. In fact, it's pretty generic and would work fine for Triton devices with just the generic device interface.
> 
> We (as a non-GPU device with a Triton implementation) would otherwise be compatible with this method, but we are not a GPU, and thus we cannot use this. We'd like to refactor it so that it no longer is tied to the "cuda" device type so that we can (and other Triton compatible devices can use this same method in the future).

Just a couple questions and clarifications for my understanding; for your non-GPU device, what would the device type be? For example, in,

```
tensor = torch.randn(1024, device=foo)
```

what is `foo`? Also, am I understanding correctly that the general benchmarking scheme that works generically for all GPU types (i.e. the algorithm itself) would also be correct for your non-GPU device?

If `foo != "gpu"`, then I think we can handle this for you fairly easily. I'd propose that we redirect all uses of `benchmarker.benchmark_cpu(...)` or `benchmarker.benchmark_gpu(...)` to the more generic `benchmarker.benchmark(...)`, which is just a glorified dispatcher. This would be trivial to extend with support for new device types that are not `"cpu"` or `"gpu"`.

Also, if my assumption is correct in that you want to keep the algorithm the same then yes we absolutely can switch any `torch.cuda.*` calls to use the device interface instead; this should also be trivial to implement, and will allow use to reuse that code nicely.

If this all sounds good to you lmk; there is a lot of work in progress specifically focused on the benchmarking module (we're writing our own implementation of `do_bench`) so I'd prefer to add any changes to my stack to avoid merge conflicts where possible.

**Comment by galexite** [comment]
> Just a couple questions and clarifications for my understanding; for your non-GPU device, what would the device type be?

For us it would be `"ipu"`. (Note, as an additional example, that there is a CPU backend for Triton in the works, and they'd be able to use this too in the future.)

> Also, am I understanding correctly that the general benchmarking scheme that works generically for all GPU types (i.e. the algorithm itself) would also be correct for your non-GPU device?
> 
> If foo != "gpu", then I think we can handle this for you fairly easily. I'd propose that we redirect all uses of benchmarker.benchmark_cpu(...) or benchmarker.benchmark_gpu(...) to the more generic benchmarker.benchmark(...), which is just a glorified dispatcher. This would be trivial to extend with support for new device types that are not "cpu" or "gpu".
> 
> Also, if my assumption is correct in that you want to keep the algorithm the same then yes we absolutely can switch any torch.cuda.* calls to use the device interface instead; this should also be trivial to implement, and will allow use to reuse that code nicely.

Yep, this should be okay for us. If the benchmark method remains 'warm up, record the start event, run, then record the end event, then collect the difference between the two events', the only thing which might vary is the implementation of `Event`, which we can override. Currently though, to my understanding, this is just wall clock time, no hardware counters etc. are in use, so it should just work for any device without any changes.

> If this all sounds good to you lmk; there is a lot of work in progress specifically focused on the benchmarking module (we're writing our own implementation of do_bench) so I'd prefer to add any changes to my stack to avoid merge conflicts where possible.

This sounds good to me!

We have an additional complication that we are an out-of-tree backend, so it would be great if this was implemented in a way such that we could substitute in our own method from our out-of-tree backend in the future. But for now, this'll do.

**Comment by nmacchioni** [comment]
You'll need to cherry pick the commit onto the `release/3.0.x` branch, we won't pull in the main branch. cc @jataylo again, this is one commit that if cherry picked maybe you could just include in https://github.com/pytorch/pytorch/pull/133438? Small change and squashing into one PR would probably be best. Otherwise we'd have to wait until https://github.com/pytorch/pytorch/pull/133438 lands

**Comment by galexite** [comment]
@nmacchioni I have opened a new pull request (https://github.com/pytorch/pytorch/pull/136189) for this pointing at a commit on Triton's `release/3.1.x` branch.

This PR can be closed in favour of that one.

**Pull request closed without merging**
