### PR TITLE
restore USE_C10D_NCCL

### PR DESCRIPTION
**Pull request by anderspapitto**

### CODE REVIEW

**Review by teng-li — APPROVED** [review]

**Comment by teng-li** [comment]
@pietern  We used to check if the NCCL version is good for c10d, now we don't, which means as long as USE_NCCL is on, libc10d will always be built with NCCL since we know we will not be using nccl 1 anywhere. So in turn, when we build csrc, the same thing should apply, that's what I told @anderspapitto yesterday about this fix.

**Comment by pietern** [comment]
@anderspapitto Is there a check that we don't compile with NCCL1?

The check that we did for c10d before should now be executed at the top level, just to be sure IMO.

**Comment by teng-li** [comment]
@pietern good thought

**Comment by teng-li** [comment]
@anderspapitto why did the NCCL version check go away?

**Pull request closed without merging**
