### PR TITLE
Add Distributed merge rules

### PR DESCRIPTION
**Pull request by kiukchung**
Adds merge rule for the distributed sub-module.

### CODE REVIEW

**Review by osalpekar — APPROVED** [review]
LGTM.

Going forward, I'd suggest having a GH team for the distributed approvers list (so that it's a more comprehensive list and a single source of truth in case the same list is needed in CODEOWNERS, etc.) but that can happen in a separate PR. cc @zengk95

**Comment by kiukchung** [comment]
> LGTM.
> 
> Going forward, I'd suggest having a GH team for the distributed approvers list (so that it's a more comprehensive list and a single source of truth in case the same list is needed in CODEOWNERS, etc.) but that can happen in a separate PR. cc @zengk95

Good point, looks like I don't have access to create teams under the pytorch GH org:
image

Per GH [docs](https://docs.github.com/en/organizations/organizing-members-into-teams/creating-a-team) I'm supposed to see a "New Team" button on the top RHS.

image

Happy to make changes to this PR if someone can help me create a team for distributed maintainers.

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
