### PR TITLE
Use reduced precision switch in `test_addmm_baddbmm_overflow`

### LINKED ISSUE #68125: DISABLED test_addmm_baddbmm_overflow_cuda_float16 (__main__.TestLinalgCUDA)
This test is failing consistently on _win-vs2019-cuda11.3-py3 / test (default, 2, 2, windows.8xlarge.nvidia.gpu) but apparently no other jobs. Failure snippet:

```
❌ Failure: TestLinalgCUDA.test_addmm_baddbmm_overflow_cuda_float16
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 891, in only_fn
    return fn(slf, *args, **kwargs)
  File "test_linalg.py", line 6139, in test_addmm_baddbmm_overflow
    self.assertTrue((out == 10000.).all())
AssertionError: tensor(False, device='cuda:0') is not true
```

Platforms: windows

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry @jianyuh @nikitaved @pearu @walterddr @IvanYashchuk @xwang233 @Lezcano

### PR DESCRIPTION
**Pull request by eqy**
Fixes #68125
Checking to see if actually using the switch fixes the test...

CC @mruberry @ngimel @ptrblck

### CODE REVIEW

**Comment by ngimel** [comment]
It's weird that test was failing on windows only

**Comment by eqy** [comment]
> It's weird that test was failing on windows only
Could it be that the other GPU tests are more likely to run on other architectures? AFAIK the overflow was only observed on Volta.

**Comment by ngimel** [comment]
YEp, windows tests are run on V100

**Comment by ngimel** [comment]
So the test is currently disabled, so we won't see anything on the CI. I'm going to land this nevertheless. 
cc @janeyx99, @mruberry, we should not be disabling tests via issues, and instead should use proper skips for this. Issues interface is exceedingly confusing.

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
