### PR TITLE
[OpInfo Hackathon] Parcel (1/2): OpInfo for `max_pool1d`, `max_pool3d` and `max_poolNd_with_indices`

### PR DESCRIPTION
**Pull request by krshrimali**
~This PR adds OpInfo for `max_pool1d` and `max_pool3d`.~ The scope of this PR was increased to include testing for the following ops:

`max_pool1d, max_pool3d, max_pool1d_with_indices, max_pool2d_with_indices, max_pool3d_with_indices`

Also has a minor whitespace fix for `MaxPool3d` documentation.

Issue Tracker: https://github.com/pytorch/pytorch/issues/54261

cc: @mruberry

### CODE REVIEW

**Comment by krshrimali** [comment]
Hi, @mruberry - Can you please take a look whenever you find the time? :) Thanks!

**Comment by mruberry** [comment]
Hey @krshrimali!

Thanks for the update!

Looks like this and https://github.com/pytorch/pytorch/pull/68075 overlap, and that's OK. Would you review https://github.com/pytorch/pytorch/pull/68075 and ensure it covers the cases this PR does for max_poolNd OpInfos, then we can land that PR, then this PR's fixes to test_nn and nn/functional.py can go in, and the `_with_indices` variants, too, possibly with tweaks based upon your review of #68075.

Does that make sense?

**Comment by krshrimali** [comment]
> Hey @krshrimali!
> 
> Thanks for the update!
> 
> Looks like this and #68075 overlap, and that's OK. Would you review #68075 and ensure it covers the cases this PR does for max_poolNd OpInfos, then we can land that PR, then this PR's fixes to test_nn and nn/functional.py can go in, and the `_with_indices` variants, too, possibly with tweaks based upon your review of #68075.
> 
> Does that make sense?

Thanks, @mruberry - it's my bad - I had a discussion with @nikitaved and we both agreed for going forward with his PR. I'll make the changes in this PR once the other is merged. Thanks!

**Comment by mruberry** [comment]
Ping on this @krshrimali -- are there some planned changes here?

**Comment by krshrimali** [comment]
@nikitaved has kindly agreed to help on this, in a separate PR. Closing this :) Thank you!

**Pull request closed without merging**
