### PR TITLE
Fix Vec256<T>::abs() for floating point when applied on -0.0

### PR DESCRIPTION
**Pull request by xuhdev**
Currently when a Vec256<T> (base) object contains -0.0, Vec256<T>::abs()
would not produce 0.0, but -0.0 instead. This commit fixes this issue.
This bug will mostly affect CPUs without AVX support, such as ARM,
PowerPC,  and older Intel models.

### CODE REVIEW

**Comment by colesbury** [comment]
Can you use std::abs instead?

**Comment by xuhdev** [comment]
@colesbury Updated

**Comment by resistor** [comment]
Is it possible to write a unit test for this?

**Comment by resistor** [comment]
Build errors are because `std::abs` has no overload for `char`.  Maybe you should keep the original definition in `Vec256_base` and only override to `std::abs` for floating point types?

**Comment by resistor** [comment]
Or you could use `std::is_floating_point`: https://en.cppreference.com/w/cpp/types/is_floating_point

**Comment by xuhdev** [comment]
@resistor Thank you for pointing out this issue. I've changed the implementation to overload floating point version and non-floating point version individually.

I look around the codebase a bit, but I'm not aware of unit test for functions in vector_base.h though. Do you know where might be the best place to add the unit test? Currently we have a guard in test_torch.py, but that has not triggered a failure probably because we never tested in an env without AVX:

https://github.com/pytorch/pytorch/blob/f75c1e493985c19fa587c32d02718671df546bb2/test/test_torch.py#L4308-L4312

**Comment by resistor** [comment]
> I look around the codebase a bit, but I'm not aware of unit test for functions in vector_base.h though. Do you know where might be the best place to add the unit test? Currently we have a guard in test_torch.py, but that has not triggered a failure probably because we never tested in an env without AVX:

Hrm, that's exactly the kind of test I was imagining.  I'm surprised it's not failing on an ARM target, for instance.  It might be worth stepping through the execution of that test to figure out if it's broken in some way.  Or at least build PyTorch without AVX and confirm that the test does fail as expected (before this commit).

**Comment by xuhdev** [comment]
@resistor It turned out that the vectorized version of abs was never tested. I can manually reproduce the bug on master, with AVX disabled, and I have added this to the test:

    >>> a = -torch.zeros(10000)
    >>> a.abs()
    tensor([-0., -0., -0.,  ..., -0., -0., -0.])

**Review by resistor — APPROVED** [review]

**Pull request closed without merging**
