### PR TITLE
Don't run reshape pattern match on dynamic shape size tensor

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136100

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by ezyang** [comment]
@mengluy0125 as original author of this code could you take an action item for writing a test for this? https://fb.workplace.com/groups/1075192433118967/permalink/1501925720445634/

**Review by mengluy0125 — APPROVED** [review]
Thanks for working on this.

**Comment by mengluy0125** [comment]
> @mengluy0125 as original author of this code could you take an action item for writing a test for this? https://fb.workplace.com/groups/1075192433118967/permalink/1501925720445634/

Sure.

**Comment by mengluy0125** [comment]
Thanks @ezyang for the quick fix on the reshape node normalization on dynamic shapes to unblock MC experiments!

**Pull request closed without merging**
