### PR TITLE
Fix typo on torch.frombuffer() documentation

### LINKED ISSUE #114345: Incorrect line in description of torch.frombuffer() method
### 📚 The doc issue

As per the documentation on `frombuffer` method of `torch`:
```
torch.frombuffer(buffer, *, dtype, count=-1, offset=0, requires_grad=False) → [Tensor](https://pytorch.org/docs/stable/tensors.html#torch.Tensor)
```
As per the documentation, either of the following conditions should be true:

```
1. count is a positive non-zero number, and the total number of bytes in the buffer is less than offset plus count times the size (in bytes) of [dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype).

2. count is negative, and the length (number of bytes) of the buffer subtracted by the offset is a multiple of the size (in bytes) of [dtype](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype).
```

In condition number 1, it seems that it is wrongly written that `total number of bytes in the buffer is less than offset plus count times the size (in bytes) of dtype`. This should be changed to say that `total number of bytes in the buffer is **more** than offset plus count times the size (in bytes) of dtype`, so that when we read the buffer, there is ample data to read taking into account the `(offset + count) * dtype`, and we don't accidentally end up reading memory slots dedicated to something else than the buffer.

### Suggest a potential alternative/fix

_No response_

cc @svekars @carljparker @albanD

### PR DESCRIPTION
**Pull request by mdevino**
Fixes #114345

### CODE REVIEW

**Comment by mdevino** [comment]
Hello,

I currently work for IBM and will need to wait a couple of days to get added to the Corporate CLA. This PR will need to remain on hold until then.

**Comment by albanD** [comment]
No problem, you can ping me once this is through!

**Comment by mdevino** [comment]
Hi @albanD. My CLA request has been approved. When you have the chance, could you take a look at this PR and let me know if I need to change anything?

**Review by albanD — APPROVED** [review]
Thanks!

**Pull request closed without merging**
