### PR TITLE
Revert "Add check for x64 Python before setup (#17707)"

### PR DESCRIPTION
**Pull request by peterjc123**
This reverts commit 08fb9021da32e73bd7dec73104eea6a76dd44439.

### CODE REVIEW

**Comment by t-vi** [comment]
Is there a reason to revert this completely as opposed to limiting it to windows?

**Comment by peterjc123** [comment]
If it works on Linux, then it should be okay on Windows, too. I'm trying this with https://github.com/pytorch/pytorch/pull/17865/files. If it is not the case, then I'll limit this to Windows only.

**Comment by peterjc123** [comment]
I have tested it and apparently, it was blocked by the missing functions like `_mm256_extract_epi64`. So I'll add this limitation. I just wonder if this function is available under Linux i386.

**Comment by t-vi** [comment]
Yes, "AVX creep" is a problem for linux 32 bit, too, I added something to disable AVX for the android emulator build in that PR. For some reason AVX is detected and all, even though vanilla x86 (i.e. 32 bit) doesn't have it. On arm32 this should be "automatically".
So how about we open an issue "should disable AVX on 32bit x86 / refine AVX availability tests" and revert disabling 32bit.

**Comment by peterjc123** [comment]
@t-vi Sounds good. Would you please open the issue and I'll revert the changes here?

**Comment by peterjc123** [comment]
@t-vi I've opened one here: https://github.com/pytorch/pytorch/issues/17901.

**Pull request closed without merging**
