### PR TITLE
improve sort cpu bfloat16 perf by directly comparing on acc_type

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #76279
* #74899
* __->__ #74898
* #74897

Differential Revision: [D37441442](https://our.internmc.facebook.com/intern/diff/D37441442)

### CODE REVIEW

**Comment by frank-wei** [comment]
@frank-wei has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37441442).

**Comment by frank-wei** [comment]
https://github.com/pytorch/vision/blob/main/test/test_models.py seems failed due on this PR.
```
python3.8: caffe2/c10/util/SmallVector.h:338: c10::SmallVectorTemplateCommon::reference c10::SmallVectorTemplateCommon<long>::operator[](c10::SmallVectorTemplateCommon::size_type) [T = long]: Assertion `idx < size()' failed.
Fatal Python error: Aborted
Current thread 0x00007f1f15e541c0 (most recent call first):
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/torchvision/ops/boxes.py", line 112 in _batched_nms_vanilla
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/torch/jit/_trace.py", line 1127 in wrapper
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/torchvision/ops/boxes.py", line 73 in batched_nms
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/torchvision/models/detection/ssd.py", line 451 in postprocess_detections
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/torchvision/models/detection/ssd.py", line 402 in forward
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/torch/nn/modules/module.py", line 1147 in _call_impl
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/test_models.py", line 713 in test_detection_model
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/python.py", line 183 in pytest_pyfunc_call
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/callers.py", line 187 in _multicall
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/manager.py", line 84 in <lambda>
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/manager.py", line 93 in _hookexec
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/hooks.py", line 286 in __call__
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/python.py", line 1641 in runtest
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/runner.py", line 162 in pytest_runtest_call
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/callers.py", line 187 in _multicall
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/manager.py", line 84 in <lambda>
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/manager.py", line 93 in _hookexec
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/hooks.py", line 286 in __call__
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/runner.py", line 255 in <lambda>
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/runner.py", line 311 in from_call
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/runner.py", line 254 in call_runtest_hook
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/runner.py", line 215 in call_and_report
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/runner.py", line 126 in runtestprotocol
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/runner.py", line 109 in pytest_runtest_protocol
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/callers.py", line 187 in _multicall
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/manager.py", line 84 in <lambda>
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/manager.py", line 93 in _hookexec
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/hooks.py", line 286 in __call__
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/main.py", line 348 in pytest_runtestloop
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/callers.py", line 187 in _multicall
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/manager.py", line 84 in <lambda>
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/manager.py", line 93 in _hookexec
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/hooks.py", line 286 in __call__
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/main.py", line 323 in _main
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/main.py", line 269 in wrap_session
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/callers.py", line 187 in _multicall
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/manager.py", line 84 in <lambda>
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/manager.py", line 93 in _hookexec
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/pluggy/hooks.py", line 286 in __call__
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/_pytest/config/__init__.py", line 162 in main
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/testinfra/testpilot/integration/python/adapters/pytest.py", line 454 in execute_tests
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/testinfra/testpilot/integration/python/adapters/base.py", line 82 in _execute_tests
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/testinfra/testpilot/integration/python/adapters/base.py", line 123 in run
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/testinfra/testpilot/integration/python/adapters/base.py", line 245 in run
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/testinfra/testpilot/integration/python/adapters/pytest.py", line 475 in main
  File "/re_cwd/fbcode/buck-out/dev/gen/pytorch/vision/test/torchvision_models#binary,link-tree/testinfra/testpilot/integration/python/adapters/pytest.py", line 479 in <module>
  File "/usr/local/fbcode/platform010/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/local/fbcode/platform010/lib/python3.8/runpy.py", line 194 in _run_module_as_main
```

**Comment by frank-wei** [comment]
Can you also check failed CI?

**Comment by mingfeima** [comment]
working on it!

**Pull request closed without merging**
