### PR TITLE
Enable UFMT on `test_decomp.py`, `test_expanded_weights.py` and some files

### PR DESCRIPTION
**Pull request by shink**
Part of: #123062 

Ran lintrunner on:

- test/test_decomp.py
- test/test_deploy.py
- test/test_determination.py
- test/test_dlpack.py
- test/test_dynamic_shapes.py
- test/test_expanded_weights.py

Detail:

```bash
$ lintrunner -a --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```

### CODE REVIEW

**Review by jansel — CHANGES_REQUESTED** [review]
Looks good, but seems like there are merge conflicts that need to be resolved.

**Comment by shink** [comment]
@jansel all conflicts are resolved, please take a look, thanks!

**Review by jansel — APPROVED** [review]

**Comment by shink** [comment]
fixed:

```diff
--- a/test/test_dynamic_shapes.py
+++ b/test/test_dynamic_shapes.py
@@ -838,8 +838,8 @@ class f(torch.nn.Module):
         native_dropout = torch.ops.aten.native_dropout.default(new_empty, 0.5, True);  new_empty = None
         getitem: "f32[s0 + s2, 2*s1]" = native_dropout[0]
         getitem_1: "b8[s0 + s2, 2*s1]" = native_dropout[1];  native_dropout = None
-        return (getitem, getitem_1)""",
-        )  # noqa: B950
+        return (getitem, getitem_1)""",  # noqa: B950
+        )
```

**Pull request closed without merging**
