### PR TITLE
update triton pin

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #108104
* #107722

### CODE REVIEW

**Comment by shunting314** [comment]
This is split out from https://github.com/pytorch/pytorch/pull/107722 and incorporate a few triton side fixes mentioned in https://github.com/openai/triton/issues/2156

**Review by desertfire — APPROVED** [review]

**Review by amjames — CHANGES_REQUESTED** [review]
Now that openai/triton#2262 has landed we can move this along with a new commit pin. 

@shunting314 we should also be able to remove the `skip` added to the problematic test [here](https://github.com/pytorch/pytorch/pull/107722/files#diff-ee9917f2665422eb0840197fb632f86b6c69b0e7a618123852de337038e5e3a1R3588)

**Comment by shunting314** [comment]
> Now that [openai/triton#2262](https://github.com/openai/triton/pull/2262) has landed we can move this along with a new commit pin.
> 
> @shunting314 we should also be able to remove the `skip` added to the problematic test [here](https://github.com/pytorch/pytorch/pull/107722/files#diff-ee9917f2665422eb0840197fb632f86b6c69b0e7a618123852de337038e5e3a1R3588)

@amjames  I think we should still go with this pin first. Updating a pin require not only CI & perf tests in OSS, we also have complex tests in FBCode. @shintaro-iwasaki  has already done a lot of tests in FBCode and we are almost ready to push this pin update out. This upgrade contains the initial hopper support from triton side, pushing this one out will make future upgrading easier. We can take the fix you mentioned in the next upgrade.

**Pull request closed without merging**
