### PR TITLE
Revert "Default to not build Caffe2 operators on Windows. (#29061)"

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#30740 Revert "Default to not build Caffe2 operators on Windows. (#29061)"**

This reverts commit 7102aceaf88ab71781c6019458bd7a07e86a532f.

Differential Revision: [D18834315](https://our.internmc.facebook.com/intern/diff/D18834315)

### CODE REVIEW

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit 459e1a7:
* **1/1** broken upstream at merge base f73cd28 (see [grid view](https://dr.pytorch.org/master-timeline.html?count=10&sha1=f73cd280827b78991fe95366e823cfadb3f00ebc&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35))
    * You may want to rebase on the `viable/strict` branch (see its [recency history](https://dr.pytorch.org/master-viable-commits.html)):
        * If your commit is older than `viable/strict`:
          ```
          git fetch viable/strict
          git rebase viable/strict
          ```
        * If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
          ```
          git fetch viable/strict
          git rebase --onto viable/strict $(git merge-base origin/master HEAD)
          ```
* **0/1** failures introduced in this PR



## Detailed failure analysis (WIP)

Here are the [reasons each build failed](https://dr.pytorch.org/commit-details.html?sha1=459e1a7681b1574882c482629bfe43e3cfdd813b):

### 1 failures recognized by patterns:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/3777231) pytorch_xla_linux_xenial_py3_6_clang7_build
**Step:** Build
```
Dec 04 18:55:44 FAILED: Build did NOT complete successfully (61 packages loaded, 1246 targets configured)
```


---
This comment was automatically generated by [Dr. CI](https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment).
Follow [this link to opt-out](https://dr.pytorch.org/admin/comments-opt-out.html) of these comments for your Pull Requests.


Please report bugs/suggestions on the [GitHub issue tracker](https://github.com/kostmo/circleci-failure-tracker/issues).

**Review by peterjc123 — APPROVED** [review]
Let's assume it's working fine first.

**Comment by ezyang** [comment]
Jeez, I can't turn this build off for a month! It's already bitrotten.

```
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/repeated_field.h(384): error C2993: 'T': illegal type for non-type template parameter '__formal'
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/repeated_field.h(391): note: see reference to class template instantiation 'google::protobuf::internal::TypeImplementsMergeBehaviorProbeForMergeFrom<T>' being compiled
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/repeated_field.h(384): error C2065: 'RetType': undeclared identifier
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/repeated_field.h(384): error C2923: 'std::_Select<__formal>::_Apply': 'RetType' is not a valid template type argument for parameter '<unnamed-symbol>'
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/repeated_field.h(384): error C2062: type 'unknown-type' unexpected
-- Removing C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/operators/./torch_cuda_generated_softsign_op.cu.obj
"C:/Program Files/CMake/bin/cmake.exe" -E remove C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/operators/./torch_cuda_generated_softsign_op.cu.obj
CMake Error at torch_cuda_generated_softsign_op.cu.obj.Release.cmake:281 (message):
  Error generating file
  C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/operators/./torch_cuda_generated_softsign_op.cu.obj
```

**Comment by ezyang** [comment]
Error might be fake. Triggering rebuild

**Comment by peterjc123** [comment]
@ezyang Test passed.

**Pull request closed without merging**
