### PR TITLE
add process group UCX

### PR DESCRIPTION
**Pull request by Sergei-Lebedev**
Introducing process group UCX that supports isend, irecv, alltoall and alltoallv operations for host and gpu buffers. Process group is based on UCX library https://github.com/openucx/ucx.
alltoall collectives is pairwise alltoall implemented directly using point to point primitives 
Config parameters
TORCH_UCX_THREAD_ENABLE controls internal progress thread, UCX library has to be built with multithreading support to use this feature.
TORCH_UCX_CHUNK number of outstanding requests in alltoall
TORCH_UCX_REVERSE - order of ranks for send/recv in alltoall
TORCH_UCX_MAX_POLLS - number of times to test request in alltoall before exit progress function

### CODE REVIEW

**Comment by osalpekar** [comment]
cc: @jiayisuse @srinivas212

**Comment by mrshenli** [comment]
cc @agolynski

**Review by mrshenli — COMMENTED** [review]
Hey @Sergei-Lebedev @srinivas212 @agolynski 

Regarding plans on this PR, are we going to get this in as one builtin c10d backend, or should we start from a 3rd-party c10d extension? The latter might allow a faster iteration speed as we don't need to worry about PyTorch code review and CI tests.

**Comment by srinivas212** [comment]
> Hey @Sergei-Lebedev @srinivas212 @agolynski
> 
> Regarding plans on this PR, are we going to get this in as one builtin c10d backend, or should we start from a 3rd-party c10d extension? The latter might allow a faster iteration speed as we don't need to worry about PyTorch code review and CI tests.

@mrshenli Agreed. We are already working on a 3rd-party c10d plugin. This PR is mainly for quick testing.

**Comment by mrshenli** [comment]
RI am removing `oncall: distributed` tag, as the oncall person does not need to review this.

**Pull request closed without merging**
