### PR TITLE
Supports symbolic diff for silu

### PR DESCRIPTION
**Pull request by yueyericardo**
As per title

### CODE REVIEW

**Review by jjsjann123 — APPROVED** [review]
LGTM

**Comment by yueyericardo** [comment]
ping @davidberard98

**Comment by yueyericardo** [comment]
ping @davidberard98 @ngimel could someone help merge this?

**Review by davidberard98 — COMMENTED** [review]
@yueyericardo thanks for the PR, can you take a look at the failures on test_jit_fuser_te.py and test_jit_cuda_fuser.py? (I just added the tests recently, which is why you probably didn't see them when you last checked the PR)

**Comment by yueyericardo** [comment]
@davidberard98 the failed test seems unrelated to this PR?

**Comment by davidberard98** [comment]
Rerunning the test, I agree it should be an unrelated failure @yueyericardo 

I will accept, please wait to make sure the test passes before merging

**Review by davidberard98 — APPROVED** [review]
Looks good, thanks for the PR!

Please wait to make sure the other test ([libtorch-linux-bionic-cuda11.6-py3.7-gcc7 / build](https://github.com/pytorch/pytorch/runs/7696304347?check_suite_focus=true#logs)) passes

**Comment by yueyericardo** [comment]
@davidberard98 all tests have passed

**Pull request closed without merging**
