### PR TITLE
Add some logging statements to graph_fuser.cpp

### PR DESCRIPTION
**Pull request by Krovatkin**
I started adding some logging to `graph_fuser.cpp`. Please let me know what other spots/decision points might benefit from logging.
Thanks!

### CODE REVIEW

**Comment by mruberry** [comment]
Some of this logging seems more like debugging. Do we really want to PR it?

**Comment by Krovatkin** [comment]
> Some of this logging seems more like debugging. Do we really want to PR it?

We have two levels of logging: `GRAPH_UPDATE` to report transformations to a graph and `GRAPH_DEBUG` to tell us how a pass arrives at those transformations.
It allows someone new to a pass to quickly identify the most important decision-making logic. I often find `GRAPH_DEBUG` to be very useful, as it can be used to explain why certain transformations do not occur and show exactly how other new passes or extensions to the existing ones break a particular optimization.

What would you think the downsides of this approach?

**Review by mruberry — APPROVED** [review]
Per offline conversation. Logging helpful information sounds good, and we should perform a holistic logging review later to ensure we're logging what's necessary in a principled way.

**Pull request closed without merging**
