### PR TITLE
[ONNX] Look at owningBlock instead of graph when recording autograd subgraph

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #82040
* #82039
* #82038
* __->__ #82852
* #82767

Small adjustment to ensure the node always exists. `graph->nodes()` might not contain
the autograd node, if it resides in additional subgraphs.

### CODE REVIEW

**Review by shubhambhokare1 — APPROVED** [review]
LGTM

**Comment by BowenBao** [comment]
cc @abock for merge approval

**Review by abock — APPROVED** [review]

**Comment by BowenBao** [comment]
@malfet Could you help take a look? This is a small tweak on #74765, I hope it won't need a full import.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
