### PR TITLE
Convert `ForeachFuncInfo` to `dataclass`

### PR DESCRIPTION
**Pull request by crcrpar**
- `ForeachFuncInfo` to `dataclass` for smaller diff from `OpInfo`
- `skips` to `decorators` and `skip` to `xfail`

### CODE REVIEW

**Review by janeyx99 — APPROVED** [review]

**Comment by crcrpar** [comment]
The number of test cases doesn't change with this pr.

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your change but I think it is breaking on ROCm https://hud.pytorch.org/pytorch/pytorch/commit/9466335ae4cb049efd3f4c2b32b2115ba00694f3' -c nosignal

Let me add `ciflow/rocm` to run the tests on PR.

**Comment by jeffdaily** [comment]
ciflow/rocm is added to this PR.  It should provide a ROCm signal now.  Thank you @huydhn for the revert and adding of the label.

**Comment by crcrpar** [comment]
hmm, I thought `dtypesIfROCM` was set to `dtypes` if it's not specified but it doesn't appear to be so. filed https://github.com/pytorch/pytorch/issues/125295

**Comment by crcrpar** [comment]
@jeffdaily would this look better to you now?

**Review by jeffdaily — APPROVED** [review]
All ROCm CI is passing now, thank you!  Also, thanks for filing https://github.com/pytorch/pytorch/issues/125295.  I too expected dtypesIfROCM to default to dtypesIfCUDA unless specified.  We shouldn't need to copy/paste duplicate all those lines, but for the sake of landing this PR I approve and hopefully a future PR can clean up the code.

**Pull request closed without merging**
