### PR TITLE
Preserve storage offset on meta conversions.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #135498
* #135237
* #135497

This PR modifies the `to_meta` function present in the functionalization layer, so that it
also preserves the storage offset.

It does so by creating a base tensor, with enough elements for a view with the source
tensor's metadata to live. Then, we follow that by calling `as_strided`, resulting in a
tensor with the expected metadata.

cc @bdhirsh @ezyang

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
test?

**Review by bdhirsh — APPROVED** [review]
+1 test

**Comment by ysiraichi** [comment]
Will add some tests. Also waiting for @alanwaketan to take a look at this stack of PRs. In summary, this is the state of things in this stack:

- Mutating the XLA tensor metadata (sizes, strides, and storage offset) at the end of each functionalization kernel
- Removed the `is_contiguous_` assertion that lived in `LTCTensorImpl::is_contiguous_custom`.
    - This is also necessary for fixing the PyTorch/XLA CI failure

These changes mean that the XLA tensor will have metadata that reflects on what it would look like if we were running on PyTorch eager. That is, until `setup_size_properties` is called (e.g. in a `sizes_custom` call) after a generation bump. Which, in that case, the metadata will be reset to reflect the actual XLA data.

While this does work, I think it's not the ideal solution. In my opinion, XLA tensors' metadata should reflect on eager execution, always. The main reason being that that would make a program written for eager work with PyTorch/XLA (e.g. even when the program contains operations such as `as_strided`, and other view operations). Also, I believe that's usually what the user expects. For more discussion on this, I have opened [an issue on PyTorch/XLA](https://github.com/pytorch/xla/issues/7983).

**Comment by miladm** [comment]
@jiawenliu64 can you please have a look at this PR?

**Comment by ysiraichi** [comment]
After offline discussion with @miladm, we decided to go ahead and merge this PR. We will have @alanwaketan (currently out) take a look at it afterwards. 

@bdhirsh @ezyang XLA CI seems to be failing (as expected) due to the previous PR in this stack #135237. I have a PR open https://github.com/pytorch/xla/pull/7998 for fixing that (not yet merged). What is the protocol for merging this stack of PRs?

**Comment by ezyang** [comment]
Land xla, and then land pytorch with xla pin update, I think? @JackCaoG

**Comment by alanwaketan** [comment]
No concerns on the change.

**Comment by ysiraichi** [comment]
This PR is blocked by https://github.com/pytorch/xla/pull/8032. Basically, there are some CI failures related to `is_contiguous(memory_format)` calls.

**Pull request closed without merging**
