### PR TITLE
[DataPipe] Changing StreamWrapper API to handle more subclass behaviors

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #67718

Fixes additional issues pointed out in #66715.

### CODE REVIEW

**Review by ejguan — COMMENTED** [review]
Please correct me if I am wrong. The best behavior in this case would be `Wrapper` shares same interface with `fileobj`. And, `Wrapper` instance can also achieve the same result with `isinstance(wrapper, type(file_obj))` and `isinstance(file_obj, type(file_obj))`..

**Comment by NivekT** [comment]
> Please correct me if I am wrong. The best behavior in this case would be `Wrapper` shares same interface with `fileobj`. And, `Wrapper` instance can also achieve the same result with `isinstance(wrapper, type(file_obj))` and `isinstance(file_obj, type(file_obj))`..

I agree those behaviors will be the most ideal. I attempted to change the `type` or `__bases__` of `StreamWrapper` but I am unsure if that is possible because I think the underlying C data structures are different. Perhaps we will need to dynamically inherit the type based on the input.

You can see the details [here](https://github.com/pytorch/pytorch/pull/66715#issuecomment-958297213).

**Comment by ejguan** [comment]
Let me try something and get back to you.

**Comment by ejguan** [comment]
Add a PR to show what in my mind.
https://github.com/pytorch/pytorch/pull/67915

**Pull request closed without merging**
