### PR TITLE
[NCCL][CUDA][CUDA Graphs] Change capture mode to thread local to handle watchdogs cleaning straggling work

### PR DESCRIPTION
**Pull request by eqy**
An alternative to #104487 where we relax the capture mode to allow watchdogs to clean up (via `cudaEventQuery`) previously enqueued work.

CC @kwen2501 who proposed this alternative @bottler 
@Aidyn-A @ptrblck 

cc @ptrblck @mcarilli @ezyang

### CODE REVIEW

**Comment by kwen2501** [comment]
I can share another place where `cudaStreamCaptureModeThreadLocal` is used: nccl-tests.
https://github.com/NVIDIA/nccl-tests/blob/1a5f551ffd6e3271982b03a9d5653a3f6ba545fa/src/common.cu#L422-L429

It documents two other reasons:
(i) For NCCL multi-thread mode to work with CUDA Graph; 
(ii) For the first P2P operation to work with CUDA Graph (because P2P's on-demand connect may call CUDA malloc APIs).

Case (i) is less common to PyTorch users who use Python APIs. However, there can be still users who use the C++ `ProcessGroupNCCL` APIs and run it in multi-thread mode (1 thread per GPU, multiple threads per process).

Case (ii) can be hidden if user does a warm-up of the P2P operation before the graph capture. But I think over time it may be good to relax this assumption.

**Review by kwen2501 — APPROVED** [review]
Giving an approval from c10d/NCCL side. (It is a needed change for `ProcessGroupNCCL` to work with CUDA Graph.)
Would be great if someone can evaluate the impact of this change on general operations captured by CUDA Graph.

**Comment by eqy** [comment]
Some context for @eellison in case you see this PR first before https://github.com/pytorch/pytorch/pull/104487, this is being considered as an alternative to the fix in #104487. Our current main concern is that using a thread local capture mode will affect the visibility of what is included in the capture, and a trivially bad case of this would be excluding some kernel launches that happen in other threads (such as in the case of autograd/backward?). I'm also asking internally at NVIDIA about the implications of the thread local capture mode.

**Comment by eqy** [comment]
Asked around NV regarding this issue and the response is that thread local captures wouldn't affect visibility so I think we're good on that end.

**Review by eellison — COMMENTED** [review]
Cool! Have a question or two before I am sure I understand the change. 

Just to repost from the [docs](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html), this PR is making it so that when another thread does something which is not CUDAGraph-capturable in other threads we will no longer error. As you have asked around, I don't think it affects what is actually captured.

What part of the watchdog cleanup was not capturable ?

**Comment by eqy** [comment]
In general, `cudaEventQuery` calls are not allowed for events created during the capture. #103503 addressed this case by gating the work to be queried by the watchdog behind a check of the current capture status.

However, it appears that in the global capture mode, `cudaEventQuery` is also disallowed when called by other threads, even on events created before the capture. So this change in mode is meant to allow the watchdog thread to cleanup straggling work that was created _before_ the capture, a case not handled by #103503. The alternative would be to force all watchdogs to "finish" in order to prevent any future `cudaEventQuery` calls before starting a capture, but this change appears to be cleaner.

**Comment by eellison** [comment]
Would it be worth adding a ctor arg to CudaGraphs to specify capture mode, or have some other way of changing the capture mode? As you've mentioned in the other thread, if we're capturing the backward or doing other multithreading, this might lead to a regression in detected bad cudagraph events.

**Comment by eqy** [comment]
If the constructor would use the strictest "global" mode by default we would be breaking existing user code that was written before recent changes to the watchdog e.g.,  #97066 which introduces places where `cudaEventQuery` could be called where it previously would not (I believe this is caused by calling `workEnquque` by default where it was not called previously).

The response I got from the graphs team is that thread local capture mode isn't the default because CUDA doesn't have visibility into whether there isn't any synchronization happening between threads in a capture. We might consider adding a debugging mode where the graph capture mode can be set to global, but for this approach I think it might be too strict to use as a default.

**Comment by eellison** [comment]
CUDAGraphs is already very difficult to debug. I would lean against making it even more difficult to debug in the general case (can't detect if another thread in the backward does something that would throw) because of new NCCL changes. 

cc @albanD, any thoughts here ?

**Comment by albanD** [comment]
> cc @albanD, any thoughts here ?

First, I expect that this PR will break anyone capturing the fw+bw jointly. So it doesn't sound good as-is for sure. I'm surprised our CI didn't catch that btw!
We could add this to the TLS states we preserve across worker threads: https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/ThreadLocalState.h to fix this particular problem.

It is not clear to me though how to preserve this state across threads? Especially with the non-trivial wrapper we have above cudagraph to make it work with multiple cudagraphs! 

In general, I agree with @eellison concern that we are not the best citizens in terms of careful state preservation when threading is used, so making this the new default is likely to break quite a few things. Keeping the default as global and having this as an opt-in for some users that have issues with side threads sounds a lot safer for sure.

**Comment by eqy** [comment]
@albanD Do you have an explanation as to what would be broken by the thread local capture mode? Note that the capture mode does not control the _visibility_ of kernels launched on other threads to the capture, but rather just what is disallowed by the API.

However, if the main concern is that we could be opening a previously unopened can of worms debugging-wise, then please also have a look at #104487 which is an alternative that lets us keep global capture mode as the default. (also CC @eellison )

**Comment by albanD** [comment]
The definition for this function is non-trivial so I'm going to try and repeat here so you can tell me if it is correct.
In this world, each thread can be in either Global/ThreadLocal/Relaxed mode and, independently, each call to captureBegin can also be tagged with Global/ThreadLocal/Relaxed.
You end up with 2x (if the call is in the local thread or not) 3x3 (for the cross product of thread state and captureBegin state) possibility (18 total!). We could do two tables of all cases but I assume that was clear in your head from the beginning and my ascii art foo is bad.

So my understanding of what this changes do is as follows:
- For any unsafe API call within the current thread: nothing changes: it will still raise
- For any other thread that is running with the default setting (Global): nothing changes: it will still raise
- For any other thread where the user changed the setting to Relaxed: nothing changes: it still doesnt raise.
- For any other thread where the user changed the setting to ThreadLocal: THIS CHANGED: it used to raise and now will pass just fine.

So I assume that the background NCCL thread is configured in ThreadLocal mode and that's why this fixes your issue?
Also we don't want to change that thread to Relaxed as that would be too unsafe in general for a NCCL thread?

I am understanding this properly?

**Comment by eellison** [comment]
> Do you have an explanation as to what would be broken by the thread local capture mode in a combined fw+bwd capture? Note that the capture mode does not control the visibility of kernels launched on other threads to the capture, but rather just what is disallowed by the API

I don't think anything will break, it just makes it possible for a multithread backward to capture a CUDAGraph that isn't valid without error, where it was not before.

**Comment by albanD** [comment]
> I don't think anything will break, it just makes it possible for a multithread backward to capture a CUDAGraph that isn't valid without error, where it was not before.

But if my understanding is correct, since we don't change the state of our autograd worker thread, they should have the default state (Global) and thus will still error out in this case! (the second case in my comment above is not changed).

**Comment by eellison** [comment]
> But if my understanding is correct, since we don't change the state of our autograd worker thread, they should have the default state (Global) and thus will still error out in this case! (the second case in my comment above is not changed).

My interpretation of the docs was that if the local thread is instantiated with ThreadLocal it will not error on bad events for threads that are ThreadGlobal. That is why this PR fixes their use case.

**Comment by albanD** [comment]
Ok, I'm not sure if my interpretation in https://github.com/pytorch/pytorch/pull/104555#issuecomment-1631553124 is correct or not, @eqy could you please correct me here? Are the 4 cases described there properly identified?

**Comment by eqy** [comment]
Yes, I think @albanD 's understanding is basically how I am interpreting things as well.

Empirically with this PR:
1. The watchdog thread is probably started before any graph capture (so it operates in "global mode").
2. Another thread (the main thread)? starts a capture with thread local mode.
3. The watchdog thread issues a `cudaEventQuery`, but now ```or if any other thread has a concurrent capture sequence initiated with cudaStreamCaptureModeGlobal, this thread is prohibited from potentially unsafe API calls.``` does not apply, so we are still OK. 
3a. The local thread is not the watchdog thread is still not issuing `cudaEventQuery` calls, so that's why we are safe on that end.

**Comment by albanD** [comment]
> The watchdog thread is probably started before any graph capture (so it operates in "global mode").

Does this imply that if the watchdog thread was started after the graph capture started, it would not be in Global mode?

> My interpretation of the docs was that if the local thread is instantiated with ThreadLocal it will not error on bad events for other threads that are ThreadGlobal. That is why this PR fixes their use case.

Sounds like @eqy you agree with @eellison statement here? After this change, any other threads will be able to call into unsafe APIs.

@eqy what do you think about changing the watchdog thread to put it in Relaxed mode instead of changing the capture setting?

**Comment by eqy** [comment]
@albanD I will investigate whether changing the capture mode of just the watchdog thread resolves the issue. Is there a reason you would prefer changing the mode to relaxed vs. just thread local which in theory would also resolve the issue?

**Comment by kwen2501** [comment]
Quick question: what does applying a capture mode to the watchdog thread mean? The watchdog thread is not capturing anything.

**Comment by eqy** [comment]
@kwen2501 that's a great question and hopefully I can summarize the path of reasoning that got us here.
1. The crash is caused by the watchdog thread calling `cudaEventQuery` on work that was enqueued before a graph capture.
2. The initial proposal was to change the capture mode of the thread performing the capture to the "thread local" mode, so that other threads querying events (the watchdog) don't crash as the events in question were created before the actual capture and therefore shouldn't interfere with the capture.
3. Many such as @eellison and @albanD were concerned with how we changed the capture mode of the capturing thread in this PR (by globally changing the constructor), and potentially missed errors/failures caused by always using this more lenient mode.
4. @albanD pointed out that it is really just the watchdog thread that we are concerned with issuing a disallowed `cudaEventQuery` call, so another potential solution is to just have the watchdog thread operate in a more lenient mode. This seems to be fairly minimal change that shouldn't have unexpected effects on the correctness or debuggability of code involving graph captures. To clarify, while the watchdog thread itself is not capturing anything, since the watchdog thread never calls `cudaThreadExchangeStreamCaptureMode`, it is operating with the "global" mode when another thread is in the middle of a capture, and hence crash the capture because `cudaEventQuery` is disallowed in this scenario.
4a. Our current understanding is the following (assuming the `cudaEventQuery` is for an event outside of a capture).

capturing thread mode | watchdog thread mode | watchdog event query allowed |
--------------------------+--------------------------+-----------------------------------|
global (default)             | global (default)              | no                                                |
global (default)             | thread local                    | yes  (proposed new solution)     |
thread local                   | global (default)              | yes  (this PR)                               |
thread local                   |thread local                     | yes                                              |

I will try out the approach in #4 tomorrow and open a PR if it appears to work. We would implement this by e.g., calling `cudaThreadExchangeStreamCaptureMode` to change its mode to the thread local mode at the start of the watchdog thread.

**Comment by albanD** [comment]
@eqy thanks for the detailed writeup!
My understanding from the doc is that if the capturing thread is global and the watchdog thread is thread local then it WILL fail!
You need to have the watchdog thread in relaxed mode for its call to cudaEventQuery to be ignored by our global capturing thread.

**Comment by eqy** [comment]
@albanD I did test that thread local seems to work without crashing, opened #105182

**Review by albanD — CHANGES_REQUESTED** [review]
Isnt https://github.com/pytorch/pytorch/pull/105182 the plan on record to fix this?

**Comment by bottler** [comment]
> Isnt #105182 the plan on record to fix this?

I think so, if we can get to the bottom of the SyncBatchNorm test failure on it. (I just tried to rebase this one as I thought it had had interesting test failures which I can no longer see.)

**Comment by kwen2501** [comment]
> Isnt #105182 the plan on record to fix this?

Yes, #105182 is the plan on record. 
@eqy do you mind if I close this PR in favor of #105182? They use the same methodology so I figure we can keep just one of them. Feel free to reopen if needed.

**Pull request closed without merging**
