### PR TITLE
[inductor] Flip custom_op_default_layout_constraint

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #135530
* __->__ #135239
* #135391

By default, Inductor should respect the stride order of input Tensors to
custom operators.

Test Plan:
- new tests

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM if we can land it!

**Comment by zou3519** [comment]
I'm planning on landing this after the branch cut because it is relatively risky

**Comment by FindHao** [comment]
This config will only affect custom ops written by users, right? it will not have performance or correctness influence on the benchmarks in our dashboard, right?

**Comment by zou3519** [comment]
> This config will only affect custom ops written by users, right? it will not have performance or correctness influence on the benchmarks in our dashboard, right?

I don't know if there are custom ops in our dashboard. If there are any then it may affect them. So we can also watch the dashboard after merging this.

**Pull request closed without merging**
