### PR TITLE
ci: Add documentation for github actions

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #72943

Adds some documentation about our github actions setup and examples on
how to add workflows / regenerate workflows

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

Differential Revision: [D34283475](https://our.internmc.facebook.com/intern/diff/D34283475)

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by seemethere** [comment]
Will try to merge this with the mergebot

**Comment by seemethere** [comment]
> Merge failed due to PR 72943 does not match merge rules Raised by [pytorch/pytorch/actions/runs/1855301562](https://github.com/pytorch/pytorch/actions/runs/1855301562)

<details>
<summary> pain </summary>

pain

</details>

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34283475).

**Pull request closed without merging**
