### PR TITLE
Composite compliance for gather_backward

### PR DESCRIPTION
**Pull request by zou3519**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #71766
* #71765
* #71751
* #71750

No need for a tensorSubclassLike check here (for functorch at least),
changing the zeros to new_zeros is sufficient.

Test Plan:
- tested with functorch

Differential Revision: [D33772752](https://our.internmc.facebook.com/intern/diff/D33772752)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33772752).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33772752).

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33772752).

**Pull request closed without merging**
