### PR TITLE
Make SharedCache thread-safe

### LINKED ISSUE #53731: RuntimeError in multiprocessing/reductions.py when using multiprocessing.Queue with tensors and multiple threads
## 🐛 Bug

I have a system in which multiple background processes generate tensors and put them on individual `multiprocessing.Queue`s, one queue per process. In the main process, I have one thread for each of these queues responsible for getting the tensors from the respective queue and processing them further. I occasionally get the following error in one of the consuming threads (full stack trace below):

`RuntimeError: dictionary changed size during iteration`
in `torch.multiprocessing.reductions.SharedCache.free_dead_references`, specifically [this line](https://github.com/pytorch/pytorch/blob/a0652c8f08f5257735f87106363258d1c14a2b52/torch/multiprocessing/reductions.py#L65)

Looking at the implementation of `SharedCache`, I noticed that it makes assumption on the atomicity of certain operations:
It assumes that `list(self.items())` in the line I reference above is atomic, so that the dictionary (`self`) cannot change during its execution. However, the `RuntimeError` I'm getting suggests otherwise. I think what happens is that another thread modifies the dictionary via `SharedCache.__setitem__` while `list(self.items())` is executed (note that all threads share the same global instance of `SharedCache` even though they operate on distinct queues). `SharedCache.free_dead_references` already uses a mutex to avoid race conditions when deleting items from the dictionary. However, this mutex does not cover `SharedCache.__setitem__`. To fix this issue, I would suggest to move the mutex to the latter function as follows:

```python
def __setitem__(self, key, storage_ref):
    with self.lock:
        dict.__setitem__(self, key, storage_ref)
        if len(self) > self.limit:
            self.free_dead_references()
```

This would implicitly also provide mutual exclusion for `SharedCache.free_dead_references`. If this makes sense, I'm happy to create a PR for this change.

## To Reproduce

Reproducing this issues seems to be tricky because it seems to depend on thread scheduling. I haven't had any luck reproducing it with a minimal example. Here is the stack trace from an actual training job:

```
[1,1]<stderr>:Exception in thread Thread-2:
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
[1,1]<stderr>:    self.run()
[1,1]<stderr>:  File "/usr/lib/python3.6/threading.py", line 864, in run
[1,1]<stderr>:    self._target(*self._args, **self._kwargs)
[1,1]<stderr>:  File "<removed>", line 1262, in _queue_fetcher_thread_fn
[1,1]<stderr>:    msg = self._inter_process_queue.get()
[1,1]<stderr>:  File "/usr/lib/python3.6/multiprocessing/queues.py", line 113, in get
[1,1]<stderr>:    return _ForkingPickler.loads(res)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py", line 300, in rebuild_storage_fd
[1,1]<stderr>:    shared_cache[fd_id(fd)] = StorageWeakRef(storage)
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py", line 60, in __setitem__
[1,1]<stderr>:    self.free_dead_references()
[1,1]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py", line 67, in free_dead_references
[1,1]<stderr>:    for key, storage_ref in list(self.items()):
[1,1]<stderr>:RuntimeError: dictionary changed size during iteration
```

## Expected behavior

PyTorch's custom reduction implementation for sending tensors over `multiprocessing.Queue`s should be thread-safe. The RuntimeError should not occur.

## Environment

PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 450.80.02
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] pytorch-crf==0.7.2
[pip3] torch==1.5.1
[pip3] torchvision==0.6.1
[conda] Could not collect

## Additional context

I also posted about this issue on the PyTorch Forums [here](https://discuss.pytorch.org/t/runtimeerror-in-pytorchs-reductions-py-when-using-multiprocessing-queues-with-multiple-threads/114246) but haven't received any response.

### PR DESCRIPTION
**Pull request by gmyr**
Fixes #53731 

Make SharedCache thread-safe by using explicit locks instead of relying on atomicity of certain Python operations

### CODE REVIEW

**Comment by albanD** [comment]
cc @colesbury  can you review this? Or do you know who would be best suited to review it?

**Review by colesbury — APPROVED** [review]
Looks good! Thanks for tracking down and fixing this.

**Comment by albanD** [comment]
@gmyr could you fix the CI please? Let me know if you need help with that.

**Comment by gmyr** [comment]
@albanD Sure. I just signed the CLA. To fix the CI, do I just rebase to viable/strict?

**Comment by gmyr** [comment]
Well, that didn't work as intended. @albanD Help would be appreciated.

**Comment by albanD** [comment]
What I would do is create a new branch based on current master.
Then you can `git cherry-pick 4f45a54` to add your commit on top of that.
Then you can push this new branch here. That should clean everything up.

If you have issues doing that, let me know if you prefer I take over and push the commit myself ?

**Comment by gmyr** [comment]
@albanD If you don't mind, could you take over?

**Comment by albanD** [comment]
There you go.
I'll wait for CI and land :)

**Comment by albanD** [comment]
If you're curious, this is what I ran in my local terminal:
```
git checkout master
git pull
git co -b tmp_shared_cache
git remote add gmyr git@github.com:gmyr/pytorch.git
git fetch gmyr
git cherry-pick 4f45a54
git push gmyr HEAD:master # This failed as expected but I checked it tried to push on the right repo and branch
git push -f gmyr HEAD:master
```

**Comment by gmyr** [comment]
Looks like the thing I was missing was the forced push. :-)

Thanks for the help @albanD !

**Pull request closed without merging**
