### PR TITLE
Disable cudagraphs by default

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #93878
* #93871
* #93870
* #93863
* #93822
* #93821
* #93818
* #93409
* #93408
* #93389
* #93382
* #93381
* #93279
* #93278
* #93254
* #93375
* __->__ #93253
* #93252

`torch.compile` used to disable cudagraphs by default (removed one PR up in this stack), which was a bit confusing because it caused the config setting to be ignored. 

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by albanD** [comment]
@jansel Is it expected that this reduces the perf of the benchmarks https://github.com/pytorch/pytorch/issues/93794#issuecomment-1414454494 ?
Or we should force it on for the benchmark scripts?

**Comment by jansel** [comment]
We should force it on in benchmarks.  Our benchmarks have two lines: 1) with cudagraphs 2) without cudagraphs.

**Comment by albanD** [comment]
Do you know where these scripts are / can you send a PR for it? Or should I look into it?

**Pull request closed without merging**
