### PR TITLE
Fix jit/pass/peephole.cpp fuse addmm

### LINKED ISSUE #26328: [ONNX] Regression in nightly exporting aten::addmm
## 🐛 Bug

This issue starts to occur in recent versions of PyTorch nightly. 

## To Reproduce

```
import torch

class MatMulModel(torch.nn.Module):
    def forward(self, x):
        return torch.mm(x, x) + x

x = torch.ones(3, 3)
```

### PR DESCRIPTION
**Pull request by BowenBao**
Fix #26328. Reversing the order of inserting nodes. Previously the IR graph looks like

```
graph(%0 : Float(3, 3)):
  %5 : Float(3, 3) = aten::addmm(%0, %0, %0, %6, %6)
  %6 : int = prim::Constant[value=1]()
  return (%5)
```
where %6 is used before created. Now
```
graph(%0 : Float(3, 3)):
  %5 : int = prim::Constant[value=1]()
  %6 : Float(3, 3) = aten::addmm(%0, %0, %0, %5, %5)
  return (%6)
```

### CODE REVIEW

**Comment by resistor** [comment]
Fix LGTM.  Why are the tests in ONNX files?

**Review by houseroad — APPROVED** [review]
Looks good. The problem is detected when we try to export the addmm to ONNX.

@BowenBao feel free to add one test here: https://github.com/pytorch/pytorch/blob/master/test/test_jit.py#L427

**Comment by resistor** [comment]
> Looks good. The problem is detected when we try to export the addmm to ONNX.

The issue is not ONNX specific, so I would strongly prefer that put the test in a location that is not ONNX specific.

**Comment by houseroad** [comment]
@resistor Of course.

@BowenBao could you please add a test to test_jit.py to cover this?

**Comment by BowenBao** [comment]
@resistor @houseroad Makes sense, I'll add a test there.

**Comment by BowenBao** [comment]
> @resistor Of course.
> 
> @BowenBao could you please add a test to test_jit.py to cover this?

Test added

**Pull request closed without merging**
