### PR TITLE
Add flag to completely disable aarch32 & aarch64 assembly in QNNPACK

### PR DESCRIPTION
**Pull request by skyline75489**
Supports #49406

### CODE REVIEW

**Comment by mruberry** [comment]
@dreiss @malfet Are one of you the appropriate reviewer for this?

**Review by malfet — APPROVED** [review]
Thank you for the PR @skyline75489 
Code overall looks good to me, but can you please make a few changes:
_ `PYTORCH_QNNPACK_ENABLE_ASSEMBLY` option name is a bit misleading, as it only affects ARM builds, perhaps it could be renamed to `PYTORCH_QNNPACK_ENABLE_ARM_ASSEMBLY`
- Instead of adding the define for both enable and disable case, perhaps it could be defined only when it is enabled (and then use `#if defined(PYTORCH_QNNPACK_ENABLE_ARM_ASSEMBLY)` instead of `#if PYTORCH_QNNPACK_ENABLE_ARM_ASSEMBLY`
- Make this a negative option(i.e. PYTORCH_QNNPACK_DISABLE_ARM_ASSEMBLY), so it would play nicely with other build systems that do not support this option yet (for example Bazel)
- Automatically define it to false if USE_BITCODE option is passed.

**Comment by skyline75489** [comment]
Thanks @malfet for the feedback. I really appreciate it. 

I'm new to CMake programming. This PR is basically a ripoff of the option in XNNPACK https://github.com/google/XNNPACK/blob/master/CMakeLists.txt#L17 . To answer your questions:

1. The naming is based on the on in XNNPACK, which is `XNNPACK_ENABLE_ASSEMBLY`. Yeah I guess we can do better.
1. In `init.c` there's `#ifndef ... #define QNN_ENABLE_ASSEMBLY` so I think that other build system would be just fine. Nothing really changes. This is also what `init.c` from XNNPACK did.
1. To actually make Bitcode working, we also need to add `-DXNNPACK_ENABLE_ASSEMBLY=0`, which I think is out of the context of this PR. I plan to make another PR that will enable bitcode for real and probably modify some of the tests.

**Comment by skyline75489** [comment]
Also, quick question. Why do we still have the old [QNNPACK](https://github.com/pytorch/QNNPACK) included as a submodule? The changes only affect the internal QNNPACK. I'm not sure what I can do with the submodule.

**Comment by skyline75489** [comment]
@malfet I've address 1 and 3 in your comments. I've personally tested the build with bitcode enabled. It works as expected on my iPhone. In the future I think maybe we can add test cases.

**Comment by skyline75489** [comment]
Closed because it's out of date.

**Pull request closed without merging**
