### PR TITLE
Update preserve_node_meta to reset torch.fx.traceback.current_meta

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #125500

Fixes https://github.com/pytorch/pytorch/issues/122766

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by xmfan** [comment]
should we also add this to torch._dynamo.reset()?

**Comment by soulitzer** [comment]
wdyt about only having it being reset for testing to be safe (also happy to add it to torch._dynamo.reset() if you don't think that's a risk)

**Review by xmfan — APPROVED** [review]
I interpret torch._dynamo.reset()'s goal to be the same as starting a new process, but even if that's true, we probably need more user facing notes before enforcing it

**Comment by ezyang** [comment]
Wouldn't it be better to clear it at the end of torch.fx.Interpreter?

**Comment by soulitzer** [comment]
> Wouldn't it be better to clear it at the end of torch.fx.Interpreter?

Maybe not enough since it is possible to set it outside of fx.Interpreter, e.g. with setup_stacktrace_preservation_hooks, but along that line of thinking, since you can only set it outside of fx.Interpreter when the preserve_node_meta context manager is enabled... just making sure preserve_node_meta properly resets it should do the trick.

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
