### PR TITLE
Upgrade ROCm wheels to manylinux2_28 - 1a of 2 (docker images)

### LINKED ISSUE #140631: [DomainsOnly] Jobs fail with GLIBC version not found
## Current Status
ongoing

## Error looks like
```
Run actions/checkout@v3
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.[25](https://github.com/pytorch/torchtune/actions/runs/11826665430/job/32953216074#step:5:26)' not found (required by /__e/node20/bin/node)
```
[failure example](https://github.com/pytorch/torchtune/actions/runs/11826665430/job/32953216074)

## Incident timeline (all times pacific)
started: Wed Nov 13 ≈12pm
detected: Wed Nov 13 ≈3pm

## User impact
Some Nova workflows may fail with the error above. Domain libraries affected torchvision, torchaudio, data, torchtune.

## Root cause
Github removed Node 16 in [2.321.0 release](https://github.com/actions/runner/releases/tag/v2.321.0).
> FYI, a new runner release is created v2.321.0. I am going to rollout this runner slowly through all the rings.
> What's special about this runner release is we removed node16 from this runner package and upgrade the dotnet sdk from dotnet 6 to dotnet 8
> We need to fully remove node16 from our actions runner to secure our ecosystems and upgrade .net to version 8. Both of these break support with older clib versions of linux, mainly centos7

## Mitigation
ongoing

## Prevention/followups
TBD

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

### PR DESCRIPTION
**Pull request by jithunnair-amd**
Fixes #140631

Highlights:
* Use `cpu_final` base for ROCm in `.ci/docker/manywheel/Dockerfile_2_28`
* Cleans up install_miopen.sh to remove old ROCm references
* Install `gcc-gfortran` package to build magma for ROCm on almalinux

Needs builder PR https://github.com/pytorch/builder/pull/2043 (merged) so that GCC_ABI expected value is updated.

cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@huydhn @atalman Got this error for the rocm6.1 docker build job:
```
2024-11-19T01:39:33.9350341Z denied: User: arn:aws:sts::391835788720:assumed-role/ghci-lf-github-action-runners-runner-role/i-015cfa06d20e93248 is not authorized to perform: ecr:InitiateLayerUpload on resource: arn:aws:ecr:us-east-1:308535385114:repository/pytorch/manylinux2_28-builder-rocm6.1 because no resource-based policy allows the ecr:InitiateLayerUpload action
```

**Comment by huydhn** [comment]
I have created the missing ECR record ` arn:aws:ecr:us-east-1:308535385114:repository/pytorch/manylinux2_28-builder-rocm6.1`, let retry to see if it works now

**Comment by jithunnair-amd** [comment]
> I have created the missing ECR record ` arn:aws:ecr:us-east-1:308535385114:repository/pytorch/manylinux2_28-builder-rocm6.1`, let retry to see if it works now

Thanks, can you please do it for rocm6.2 as well? That will also need an ECR record.

**Comment by jithunnair-amd** [comment]
> > I have created the missing ECR record ` arn:aws:ecr:us-east-1:308535385114:repository/pytorch/manylinux2_28-builder-rocm6.1`, let retry to see if it works now
> 
> Thanks, can you please do it for rocm6.2 as well? That will also need an ECR record.

@huydhn Also, I suppose this means we will need to request you to create a new ECR record for every ROCm upgrade?

**Comment by huydhn** [comment]
> @huydhn Also, I suppose this means we will need to request you to create a new ECR record for every ROCm upgrade?

That's the current process.

Also, due to https://github.com/pytorch/pytorch/issues/140958 earlier today, I haven't been able to deploy the ECR change yet.  I will need to check with @jeanschmidt when we can resume infra deployment.

We could use `no-runner-experiments` to make this work for now I think.

**Comment by jithunnair-amd** [comment]
@huydhn @atalman Since we [upgraded to ROCm6.2.4](https://github.com/pytorch/pytorch/pull/140851), please help create ECR tag `manylinux2_28-builder-rocm6.2.4`.

**Review by jeffdaily — APPROVED** [review]

**Pull request closed without merging**
