### PR TITLE
Remove more build options not needed to be explicitly set in Python build scripts.

### PR DESCRIPTION
**Pull request by xuhdev**
Following up cd0d8480d3ad261b175a77f5b72c7d6181b92173

### CODE REVIEW

**Comment by xuhdev** [comment]
@ezyang  Mind a quick review? I missed two options in #21877

**Comment by xuhdev** [comment]
@ezyang Hold on one sec. Will ping you again when ready

**Review by ezyang — CHANGES_REQUESTED** [review]
WIP; dismiss this review when un-WIP

**Comment by xuhdev** [comment]
Closed in favor of   #22153 and  #22154

**Pull request closed without merging**
