### PR TITLE
Revert PR 66818 (Updated SearchSorted)

### LINKED ISSUE #68047: Windows Libtorch nightly tests have failed since last Saturday.
## 🐛 Bug

All windows libtorch with cuda nightly tests failed since last Saturday.
Looks like a regression.

The error message is 
```
LINK : error LNK2001: unresolved external symbol "class at::Tensor __cdecl at::native::searchsorted_cuda(class at::Tensor const &,class at::Tensor const &,bool,bool)" (?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z)
check-torch-cuda.exe : fatal error LNK1120: 1 unresolved externals
```

## To Reproduce

It could been in hud.pytorch.org
example link:
https://app.circleci.com/pipelines/github/pytorch/pytorch/406199/workflows/192425bf-fd0c-4aad-8128-fbb3501caa9a/jobs/16684849

## Expected behavior

All tests should be passed

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @jbschlosser

### PR DESCRIPTION
**Pull request by mszhanyi**
Fixes #68047

@samdow, your PR #66818 breaks windows libtorch nightly build. 

The test could be passed by reverting the PR.
https://app.circleci.com/jobs/github/pytorch/pytorch/16693802?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

cc
@malfet @seemethere @janeyx99

### CODE REVIEW

**Comment by samdow** [comment]
cc @janeyx99 this looks like the same error that we were seeing before your fixing change. Not sure if that one didn't make it to a certain branch or something

**Comment by malfet** [comment]
Hmm, this sounds suspicious. Let me have a look at what's going on

**Comment by janeyx99** [comment]
> cc @janeyx99 this looks like the same error that we were seeing before your fixing change. Not sure if that one didn't make it to a certain branch or something

Yea I can take a look at this instead @malfet I think I know what's going on

**Comment by janeyx99** [comment]
Should be fixed by https://github.com/pytorch/builder/pull/883

**Comment by malfet** [comment]
Testing it now in https://app.circleci.com/pipelines/github/pytorch/pytorch/406724/workflows/24bc19f7-1ee3-4747-828c-2e321caf8987/jobs/16699204 , will close the revert PR if it works

**Comment by malfet** [comment]
CI is green, closing this one

**Pull request closed without merging**
