### PR TITLE
Update xpu CD used driver to rolling version

### PR DESCRIPTION
**Pull request by chuanqi129**
The main purpose of this PR is change the XPU CD use rolling driver to support more clients GPU AOT build and enable Kineto. And also plan to enable python 3.13 for xpu CD.

Works for https://github.com/pytorch/pytorch/issues/114850

### CODE REVIEW

**Comment by atalman** [comment]
hi @chuanqi129 The docker file was built here:
https://github.com/pytorch/pytorch/actions/runs/10407300892/job/28822291034#step:4:7188
And uploaded here:
```
308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/manylinux2_28-builder-xpu:caa32808dfc5a143d185d4b80ef328f5e22c172a
```

Could you please post test PR to test this docker image ?

**Comment by chuanqi129** [comment]
> hi @chuanqi129 The docker file was built here: https://github.com/pytorch/pytorch/actions/runs/10407300892/job/28822291034#step:4:7188 And uploaded here:
> 
> ```
> 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/manylinux2_28-builder-xpu:caa32808dfc5a143d185d4b80ef328f5e22c172a
> ```
> 
> Could you please post test PR to test this docker image ?

Thanks @atalman , the test PR in https://github.com/pytorch/pytorch/pull/133775

**Review by atalman — DISMISSED** [review]
lgtm

**Comment by ZainRizvi** [comment]
@pytorchbot revert -c weird -m "Sorry, there's [an outage](https://github.com/triton-lang/triton/issues/4527) that's preventing triton from being installed correctly, which has the side effect of breaking our docker builds. Reverting this PR since it requires a docker rebuild (which now fails) to give us more time to properly fix the docker builds."

It's not your fault, but reverting this PR until docker builds are working again will help us reduce the impact of this outage on everyone else

**Comment by atalman** [comment]
@chuanqi129 I am working on triton Docker build fix. Once this is landed will reland this PR

**Comment by atalman** [comment]
Docker build landed: https://github.com/pytorch/pytorch/pull/133878 will reland this PR now

**Review by atalman — APPROVED** [review]

**Pull request closed without merging**
