### PR TITLE
[quant] Add quantized LeakyReLU module

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #45885 [quant][fx][graphmode] Add support for sigmoid
* #45884 [quant][eagermode] Add support for sigmoid module
* #45883 [quant] Add quantized Sigmoid module
* #45882 [quant] Add quantized::sigmoid that take output_scale/output_zero_point as input
* #45714 [quant][graphmode][fx] Add warning for unsupported case
* #45712 [quant][graphmode][fx][eagermode] Add leaky relu support in quantization workflows
* **#45711 [quant] Add quantized LeakyReLU module**
* #45702 [quant] Add quantized::leaky_relu that takes scale/zero_point as input

Summary:

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D24069960](https://our.internmc.facebook.com/intern/diff/D24069960)

### CODE REVIEW

**Comment by vkuzo** [comment]
just curious, what's the plan for the existing leaky relu code, would it be deleted after this stack of PRs lands?

**Comment by jerryzh168** [comment]
> just curious, what's the plan for the existing leaky relu code, would it be deleted after this stack of PRs lands?

we will still keep them, see next PR for details

**Comment by vkuzo** [comment]
> > just curious, what's the plan for the existing leaky relu code, would it be deleted after this stack of PRs lands?
> 
> we will still keep them, see next PR for details

thoughts about just keeping one of them and deleting the other, to minimize the # of code we maintain?

**Review by z-a-f — APPROVED** [review]

**Comment by jerryzh168** [comment]
> > > just curious, what's the plan for the existing leaky relu code, would it be deleted after this stack of PRs lands?
> > 
> > 
> > we will still keep them, see next PR for details
> 
> thoughts about just keeping one of them and deleting the other, to minimize the # of code we maintain?

this is to increase coverage/keep BC, removing old one will break the models that uses functional ops and requires users to rewrite the functional to module in order to statically quantize the model in eager mode.

This becomes less important if we decide to deprecate eager mode some time in the future. I think we can remove that at that time.

**Comment by vkuzo** [comment]
> > > > just curious, what's the plan for the existing leaky relu code, would it be deleted after this stack of PRs lands?
> > > 
> > > 
> > > we will still keep them, see next PR for details
> > 
> > 
> > thoughts about just keeping one of them and deleting the other, to minimize the # of code we maintain?
> 
> this is to increase coverage/keep BC, removing old one will break the models that uses functional ops and requires users to rewrite the functional to module in order to statically quantize the model in eager mode.
> 
> This becomes less important if we decide to deprecate eager mode some time in the future. I think we can remove that at that time.

correct, I understand the tradeoffs, my question is whether in this case breaking BC is the right thing to do.  Do we know how many people are using the old code and whether we should just go through the pain now?  It's not ideal to have multiple ways to quantize an op alive at the same time, and while quantization is in prototype we have the freedom to make the call to break BC when appropriate.

**Comment by vkuzo** [comment]
> requires users to rewrite the functional to module in order to statically quantize the model in eager mode.

my concern is less the function vs module (which is just how the code looks), and more the fact that leaky_relu can be both unobserved or observed (which changes the numerics).  Ideally we can pick one and delete the other.

**Comment by jerryzh168** [comment]
I'm not sure how many people are using functional leaky_relu. eager mode quantization is in beta I think, not sure if it's OK to break BC for that.

**Comment by jerryzh168** [comment]
@raghuramank100 do you know if it's OK to break BC for eager mode quantization?

**Comment by jerryzh168** [comment]
> > requires users to rewrite the functional to module in order to statically quantize the model in eager mode.
> 
> my concern is less the function vs module (which is just how the code looks), and more the fact that leaky_relu can be both unobserved or observed (which changes the numerics). Ideally we can pick one and delete the other.

yeah I agree ideally we don't want to quantize the same op in multiple ways. the point for the above comment is that it requires user to rewrite the functional to module, in other words, the functional does not work anymore, which means it's BC-breaking.

**Pull request closed without merging**
