### PR TITLE
[NNC] Fixing a bug in simplifier

### PR DESCRIPTION
**Pull request by navahgar**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#58291 [NNC] Fixing a bug in simplifier**

This bug manifests when multiplying a polynomial by a term. It was because the scalar from the polynomial was not multiplied by the entire term, instead it was multiplied only by the scalar in the term.

Differential Revision: [D28435393](https://our.internmc.facebook.com/intern/diff/D28435393)

### CODE REVIEW

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435393).

**Review by bertmaher — APPROVED** [review]

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435393).

**Review by ZolotukhinM — APPROVED** [review]

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435393).

**Comment by navahgar** [comment]
@navahgar has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28435393).

**Pull request closed without merging**
