### PR TITLE
[BE] Use CamelCase for enum class members

### PR DESCRIPTION
**Pull request by malfet**
Per many C++ code-style guides members(for [example](https://google.github.io/styleguide/cppguide.html#Enumerator_Names) ) members of `enum` should be CamelCased,
and only defines should be ALL_CAPS

Changes `MemOverlap`, `MemOverlapStatus` and `CmpEvalResult` enum values

Also, `YES`, `NO`, `TRUE` and `FALSE` are often system defines

Fixes among other things, current iOS build regression, see, which manifests as follows (see [this](https://hud.pytorch.org/pytorch/pytorch/commit/6e90572bb9443266e1abe5c7d737b028926d9b6b): 
```
/Users/runner/work/pytorch/pytorch/aten/src/ATen/MemoryOverlap.h:19:29: error: expected identifier
enum class MemOverlap { NO, YES, TOO_HARD };
                            ^
/Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/usr/include/objc/objc.h:89:13: note: expanded from macro 'YES'
#define YES __objc_yes
```

### CODE REVIEW

**Review by drisspg — APPROVED** [review]
LGTM

**Comment by drisspg** [comment]
Looks like a few more uses of the enums: 
pytorch/aten/src/ATen/native/cpu/SerialStackImpl.h
pytorch/aten/src/ATen/native/mps/operations/Shape.mm

**Review by kulinseth — APPROVED** [review]
Looks good.

**Pull request closed without merging**
