### PR TITLE
Migrate THCAtomics to ATen

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #65492
* #65491
* #65472
* #65471
* __->__ #65470

Differential Revision: [D31148184](https://our.internmc.facebook.com/intern/diff/D31148184)

### CODE REVIEW

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31148184).

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
A lot of other projects (e.g. vision and fbgemm_gpu) directly include THC/THCAtomics.cuh, can we temporarily restore it (and make it just include <ATen/cuda/Atomic.cuh>) until we can fix those projects to include ATen/cuda/Atomic.cuh?

**Comment by peterbell10** [comment]
>A lot of other projects (e.g. vision and fbgemm_gpu) directly include THC/THCAtomics.cuh, can we temporarily restore it (and make it just include <ATen/cuda/Atomic.cuh>) until we can fix those projects to include ATen/cuda/Atomic.cuh?

This PR already does that :) some `torchvision` stuff that's built as part of the rocm build was failing.

**Comment by ngimel** [comment]
Oh, great, didn't notice that. There are still internal breakages related to the new include that I thought were caused by file removal, but apparently not, I'll try to figure out what's going on (something about hipify, the error is 
```
caffe2/aten/src/THC/THCAtomics.cuh:6:10: fatal error: ATen/hip/Atomic.cuh: No such file or directory
```
which indicates that THCAtomics is hipified, but the paths in the ATen are not?

**Comment by ngimel** [comment]
Trying a tentative fix
```
diff --git a/fbcode/caffe2/aten/src/THC/THCAtomics.cuh b/fbcode/caffe2/aten/src/THC/THCAtomics.cuh
--- a/fbcode/caffe2/aten/src/THC/THCAtomics.cuh
+++ b/fbcode/caffe2/aten/src/THC/THCAtomics.cuh
@@ -2,6 +2,6 @@
 // TODO: Remove once torchvision has been updated to use the ATen header
 #ifdef __CUDACC__
 #include <ATen/cuda/Atomic.cuh>
-#else
+#elif defined(__HIP_PLATFORM_HCC__)
 #include <ATen/hip/Atomic.cuh>
 #endif
```

**Comment by ngimel** [comment]
Yeah, just removing manual hipification is better, and rocm is passing.

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31148184).

**Pull request closed without merging**
