### PR TITLE
[nnc] Strides to Tensor

### PR DESCRIPTION
**Pull request by IvanKobzarev**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #72962

Differential Revision: [D34589306](https://our.internmc.facebook.com/intern/diff/D34589306)

### CODE REVIEW

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34589306).

**Review by navahgar — COMMENTED** [review]
The changes in the PR look good to me. But I have a more high-level question. What is the usecase we are trying to target here?

**Comment by IvanKobzarev** [comment]
> The changes in the PR look good to me. But I have a more high-level question. What is the usecase we are trying to target here?

The reason here is to remove assumptions of output memory format in our lowerings which is based on knowledge of internal implementation of the ops.
E.g. for 
add(lhs, rhs):
if (isNHWC(lhs) || is NHWC(rhs)) -> output memory format NHWC else NCHW

But take the output format from the outputStrides of result of tracing graph for shapes (which also traces for strides). In that case for all the lowerings we need to add outputStrides where we had outputShapes.

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34589306).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34589306).

**Comment by EikanWang** [comment]
@ZolotukhinM @navahgar this PR is a part of NHWC support.

**Review by navahgar — APPROVED** [review]
Sorry, I missed this earlier. 

LGTM. Can you please check the failures?

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34589306).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34589306).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34589306).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34589306).

**Review by ZolotukhinM — APPROVED** [review]

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34589306).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34589306).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34589306).

**Comment by datumbox** [comment]
This PR is likely to have broken TorchVision. See https://github.com/pytorch/vision/issues/5873 for details.

**Comment by vfdev-5** [comment]
Minimal code to reproduce the issue:
```python
import torch
from torchvision.transforms import ColorJitter


meth_kwargs = {"brightness": 0.2, "contrast": 0.2, "saturation": 0.2, "hue": 0.2}

print("-")
channels = 3
device = "cpu"

torch.random.manual_seed(0)
t = ColorJitter(**meth_kwargs)
scripted_fn = torch.jit.script(t)
batch_tensor = torch.randint(0, 256, (4, channels, 23, 34), dtype=torch.uint8, device=device)
torch.manual_seed(12)
scripted_fn(batch_tensor)

print("--")
channels = 1
device = "cpu"

torch.random.manual_seed(0)
t = ColorJitter(**meth_kwargs)
scripted_fn = torch.jit.script(t)
batch_tensor = torch.randint(0, 256, (4, channels, 23, 34), dtype=torch.uint8, device=device)
torch.manual_seed(12)
scripted_fn(batch_tensor)


print("---")
channels = 3
device = "cuda"

torch.random.manual_seed(0)
t = ColorJitter(**meth_kwargs)
scripted_fn = torch.jit.script(t)
batch_tensor = torch.randint(0, 256, (4, channels, 23, 34), dtype=torch.uint8, device=device)
torch.manual_seed(12)
scripted_fn(batch_tensor)


print("----")
channels = 1
device = "cuda"

torch.random.manual_seed(0)
t = ColorJitter(**meth_kwargs)
scripted_fn = torch.jit.script(t)
batch_tensor = torch.randint(0, 256, (4, channels, 23, 34), dtype=torch.uint8, device=device)
torch.manual_seed(12)
scripted_fn(batch_tensor)
```
Output:
```
Traceback (most recent call last):
  File "temp/check_torchscript_colorjitter_all_flakiness.py", line 51, in <module>
    scripted_fn(batch_tensor)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: is_tensor_creation || ((is_contiguous ^ is_channels_last_contiguous) && (is_contiguous || is_channels_last_contiguous)) INTERNAL ASSERT FAILED at "../torch/csrc/jit/tensorexpr/kernel.cpp":519, please report a bug to PyTorch. 
```

Surprisingly, changing order of test channels : 3,1,3,1 -> 1,3,1,3 and there is no error...

**Comment by zengk95** [comment]
@pytorchbot revert this

@IvanKobzarev @datumbox we believe this is causing errors in. torch audio so going to try to revert. If this is wrongfully reverted, please just re open and re land.

**Comment by datumbox** [comment]
@zengk95 It is causing errors on Torch Video as well, so I'm fine to have it reverted. I don't think that worked though judging from the bot's message.

**Comment by IvanKobzarev** [comment]
@vfdev-5 
Thanks for repro steps.

**Pull request closed without merging**
