### PR TITLE
Advanced Indexing: Allow skipping wrapping indices if all index tensors are returned from nonzero

### PR DESCRIPTION
**Pull request by zasdfgbnm**
This is an improved version of https://github.com/pytorch/pytorch/pull/10378 that complicate the code much less, but can still handle special cases like using advanced indexing as `masked_select`.

This PR reduce the time for `tensor.index` in the example at https://github.com/pytorch/pytorch/pull/10378 from ~1800us to ~1000us.

### CODE REVIEW

**Comment by zou3519** [comment]
cc @colesbury, you had some concerns about the complexity in #10378. How does this look now?

**Comment by colesbury** [comment]
@zasdfgbnm, I thought you were going to just use `masked_select` which is faster than this?

**Comment by zasdfgbnm** [comment]
@colesbury Yes, I was planning to use `masked_select`, but I changed my mind and decide to do it this way, because in my personal opinion, this seems to have comparable complication on codes, but have less impact on cases that is not a simple `masked_selected`. Not seriously tested on performance. What is your opinion on special casing like this or using `masked_select`? Which is better?

BTW, I remember I didn't see `indices[0].sizes() == self.sizes()`, so we have to write a for loop to compare every element of the int list.

**Comment by fmassa** [comment]
ping @colesbury on this. I think that our indexing code will be improved in the future, but Sam knows better about this

**Comment by zasdfgbnm** [comment]
@colesbury Will this be merged? If not, please close this.

**Comment by soumith** [comment]
i think not, as colesbury has upcoming PR to speed up differently

**Pull request closed without merging**
