### PR TITLE
Implementation quantize operation for mkldnn tensor.

### PR DESCRIPTION
**Pull request by PenghuiCheng**
Implemented:
- quantize_linear/dequantize for mkldnn tensor
- get q_scale/q_zero_point for mkldnn tensor
- support to convert quantized mkldnn tensor to dense tensor
- support to convert quantized dense tensor to mkldnn tensor

### CODE REVIEW

**Comment by PenghuiCheng** [comment]
@jgong5 
@gujinghui 
@uyongw
@Jianhui-Li

**Review by bddppq — COMMENTED** [review]
Do I understand correctly that quantized vs. non-quantized ideep tensor differ only on dtypes? If that 's the case we should avoid adding another tensor type id. Currently mkldnn tensor is an opaque tensor that wraps an ideep tensor, so it's capable of carrying ideep tensor with different data types. Since we have different functions names (e.g. linear vs. quantize_linear) for ops, dispatching wouldn't be a problem either.

**Comment by bddppq** [comment]
The build errors are real:

```
Jul 01 10:21:52 /var/lib/jenkins/workspace/build/lib/libtorch.so: undefined reference to `at::native::empty_mkldnn(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>)'
Jul 01 10:21:52 collect2: error: ld returned 1 exit status
Jul 01 10:21:52 caffe2/CMakeFiles/conv_to_nnpack_transform_test.dir/build.make:100: recipe for target 'bin/conv_to_nnpack_transform_test' failed
Jul 01 10:21:52 make[2]: *** [bin/conv_to_nnpack_transform_test] Error 1
Jul 01 10:21:52 CMakeFiles/Makefile2:3361: recipe for target 'caffe2/CMakeFiles/conv_to_nnpack_transform_test.dir/all' failed
Jul 01 10:21:52 make[1]: *** [caffe2/CMakeFiles/conv_to_nnpack_transform_test.dir/all] Error 2
Jul 01 10:21:52 make[1]: *** Waiting for unfinished jobs....
Jul 01 10:21:54 [ 87%] Linking CXX executable ../bin/depthwise3x3_conv_op_test
Jul 01 10:21:55 /var/lib/jenkins/workspace/build/lib/libtorch.so: undefined reference to `at::native::empty_mkldnn(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>)'
Jul 01 10:21:55 collect2: error: ld returned 1 exit status
Jul 01 10:21:55 make[2]: *** [bin/depthwise3x3_conv_op_test] Error 1
Jul 01 10:21:55 caffe2/CMakeFiles/depthwise3x3_conv_op_test.dir/build.make:100: recipe for target 'bin/depthwise3x3_conv_op_test' failed
Jul 01 10:21:55 CMakeFiles/Makefile2:3443: recipe for target 'caffe2/CMakeFiles/depthwise3x3_conv_op_test.dir/all' failed
Jul 01 10:21:55 make[1]: *** [caffe2/CMakeFiles/depthwise3x3_conv_op_test.dir/all] Error 2
Jul 01 10:21:56 [ 87%] Linking CXX executable ../bin/pattern_net_transform_test
Jul 01 10:21:57 /var/lib/jenkins/workspace/build/lib/libtorch.so: undefined reference to `at::native::empty_mkldnn(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>)'
Jul 01 10:21:57 collect2: error: ld returned 1 exit status
Jul 01 10:21:57 caffe2/CMakeFiles/pattern_net_transform_test.dir/build.make:100: recipe for target 'bin/pattern_net_transform_test' failed
Jul 01 10:21:57 make[2]: *** [bin/pattern_net_transform_test] Error 1
Jul 01 10:21:57 make[1]: *** [caffe2/CMakeFiles/pattern_net_transform_test.dir/all] Error 2
Jul 01 10:21:57 CMakeFiles/Makefile2:3402: recipe for target 'caffe2/CMakeFiles/pattern_net_transform_test.dir/all' failed
```

**Comment by Jianhui-Li** [comment]
@bddppq  Thanks for the feedback.  This does make mkldnn integration less intrusive to pytorch dispatch mechanism. 

Copy @raghuramank100 @jerryzh168  so that you are aware of this PR.

**Comment by PenghuiCheng** [comment]
@bddppq , in c10/core/TensorImpl.h, there is "is_quantized" function,it used type id to Judge whether the tensor  is a quantized tensor. So we add this type id. If "is_quantized" function don't use type id,but use data type to judge the tensor type,then we don't need to add this type id.

**Comment by PenghuiCheng** [comment]
We also can change "is_quantized" function like below, then we don't need type id for mkldnn.
bool is_quantized() const {
    if (is_mkldnn())
        return isQIntType(typeMetaToScalarType(dtype()));
    auto tid = type_id();
    // NB: At the moment, variables have the same TensorTypeId as their
    // corresponding tensor, but if this ever changes, we need to modify this.
    return tid == QuantizedCPUTensorId() || tid == QuantizedMkldnnCPUTensorId();
  }

**Comment by Jianhui-Li** [comment]
@bddppq In order to hide the data type within mkldnn tensor, we need to change is_quantized() as Penghui proposed above.  The modification makes is_quantized() less general since it needs to handle mkldnn int8 tensor as a special case not according to a general type id.  The dispatch to mkldnn int8 operation will happen within mkldnn operations, not as dispatched according to first level tensor type id.     *** We don't have particular issue with this. Just to double check with you - If you don't see any issue on this, we are ready to make the change as you requested. ***    @raghuramank100 @jerryzh168  You are welcome to give feedback if you see things differently.

**Comment by jerryzh168** [comment]
I feel it's OK to specialize `is_quantized` for mkldnn considering it is using same tensor representation for both quantized and non-quantized tensor.

regarding dispatch, just talked to @bddppq yesterday, there are two cases, 
1). quantized function has a different name as the non-quantized function, for example, if we have
quantized_linear() and linear(), then we can add MKLDNN dispatch key under these two functions and do extra datatype check in the implementation:
linear (...):
  Cpu: linear
  MkldnnCpu: mkldnn_linear

quantized_linear (...):
  QuantizedCpu: fbgemm_quantized_linear
  MkldnnCpu: mkldnn_quantized_linear

2). quantized function has the same name as non-quantized function, we will have to check the data type and dispatch inside the function
linear (...):
  CPU: linear
  QuantizedCPU: fbgemm_quantized_linear
  MKLDNNCPU: mkldnn_linear

**Comment by jgong5** [comment]
> I feel it's OK to specialize `is_quantized` for mkldnn considering it is using same tensor representation for both quantized and non-quantized tensor.

@jerryzh168 Thanks for the consideration. Then we will go ahead to amend the PR accordingly. On the other hand, may I know why we don't just check the data type (i.e. `kQInt8`, `kQUInt8`, `kQInt32`) in `is_quantized`? Checking data type sounds more general to me considering there might be more devices (or even layouts) supporting quantized tensors in the future.

**Comment by jerryzh168** [comment]
@jgong5 it's just all other `is_*` functions are using tensor type id. but for mkldnn you are using int8/uint8 rather than qint8/quint8 right? It's a special case anyway..

To be fully consistent with how things are used right now, I think we'll add `QuantizedMKLDNNCPU` and also use `qint8` quint8` `qint32` for mkldnn as well. But since MKLDNN is implemented differently we can special case that..

**Comment by jgong5** [comment]
> it's just all other `is_*` functions are using tensor type id. but for mkldnn you are using int8/uint8 rather than qint8/quint8 right? It's a special case anyway..

@jerryzh168 MKL-DNN quantized tensor also uses `qint8` or `quint8` data types so as to be consistent with CPU quantized tensor. We use `int8` and `uint8` inside ideep::tensor but that is implementation details. Anyway, it is not a big deal what to be checked, just thought that checking data types would make the code simpler and easier to maintain in the future. :)

**Comment by PenghuiCheng** [comment]
@bddppq ,I had removed QuantizedMkldnnCPU type id in this patch,please review it again.
Thanks!

**Comment by jerryzh168** [comment]
What's the plan on this PR? cc @bddppq

**Comment by Jianhui-Li** [comment]
> What's the plan on this PR? cc @bddppq

We plan to change our current integration (on mkl-dnn path) to integrate to the CPU fpgemm integration path (taking Qtensor as input/output), so user doesn't worry about the tensor format conversion and op semantics difference. User may need to have an option to override the framework's default choice on int8 library.  Framework may have decide which library to choose based on performance and function availability.  Mkl-dnn is working toward AQ support, and will submit PR again. I think we can close this for now.

**Pull request closed without merging**
