### PR TITLE
Adding DataLoader2 class as future replacement of DataLoader

### PR DESCRIPTION
**Pull request by VitalyFedyunin**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#63742 Adding DataLoader2 class as future replacement of DataLoader**
Supports sharding and batching on loader level**

Supports sharding and batching on loader level

Differential Revision: [D30494506](https://our.internmc.facebook.com/intern/diff/D30494506)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
Fixed `dill` problems

**Review by ejguan — COMMENTED** [review]
Emmm, I don't think the issue from `dill`. It's the issue for windows.
Multiprocessing on Windows  uses `spawn` as default, which requires to pickling/unpickling objects. But, it's `fork` on Unix as default, there won't be this issue except specifying `spawn` explicitly.

I would say the test should pass as long as we change the `collate_fn`

**Comment by VitalyFedyunin** [comment]
New version of DataLoader using `map` internally and fails when unpickable lambda passed. Which is solvable by having dill.

**Comment by ejguan** [comment]
> New version of DataLoader using `map` internally and fails when unpickable lambda passed. Which is solvable by having dill.

Understood `map` will call `collate_fn`. But even with dill, `multiprocessing` doesn't know to use `dill` to serialize objects. Am I right?

**Comment by VitalyFedyunin** [comment]
`map` knows how to serialize lambdas via dill

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30494506).

**Review by ejguan — APPROVED** [review]

**Pull request closed without merging**
