### PR TITLE
Check for incompatible versions between CUDA and MSVC

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by shkit** [comment]
CUDA 10.1 supports MSVC 19.2x.

(from https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#system-requirements)

**Comment by peterjc123** [comment]
@shkit That's true and I didn't do any check for CUDA 10.1 because it will be supported until the new major release of MSVC 2019, which is very far away from now.

**Comment by shkit** [comment]
@peterjc123 I've misunderstood an aim of this check. Sorry for noise.

**Review by ezyang — APPROVED** [review]
Nice. I wonder if these can be somehow upstreamed to cmake proper, but that doesn't have to block this PR.

**Pull request closed without merging**
