### PR TITLE
Skip test_svd_lowrank on rocm

### LINKED ISSUE #102629: DISABLED test_svd_lowrank_cuda_float64 (__main__.TestLinalgCUDA)
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_linalg.py%3A%3ATestLinalgCUDA%3A%3Atest_svd_lowrank_cuda_float64)).

Seems like introduced by https://github.com/pytorch/pytorch/pull/97370. cc @jeffdaily @sunway513 @pruthvistony @ROCmSupport @dllehr-amd @jataylo @alugorey

### PR DESCRIPTION
**Pull request by alugorey**
Fixes #102629 

@jithunnair-amd 

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]
Skipping for now. Not caught as part of PR https://github.com/pytorch/pytorch/pull/97370 because test_linalg.py was not run as part of the last round of CI runs for some reason.

**Review by lezcano — APPROVED** [review]

**Comment by kit1980** [comment]
@alugorey is this still needed? Let's merge?

**Comment by jithunnair-amd** [comment]
Closing because svd tests fixed by https://github.com/pytorch/pytorch/pull/103540

**Comment by jithunnair-amd** [comment]
Reopening because it looks like svd tests are only working with ROCm5.5, so need the CI upgrade to happen first.

@alugorey will also add a skip for test_pca_lowrank to this PR.

**Comment by jithunnair-amd** [comment]
@alugorey CI is upgraded to ROCm5.6 now. Can we close this PR?

**Comment by alugorey** [comment]
test_svd_lowrank now passes on rocm5.6

**Pull request closed without merging**
