### PR TITLE
Add `device_idx` to `free_fn` in `CUDAPluggableAllocator`

### PR DESCRIPTION
**Pull request by emcastillo**
cc @shwina @leofang 

This was requested by nvidia folks, track also the device_id in the free function.

### CODE REVIEW

**Comment by leofang** [comment]
Actually, we wonder if it's better to remove device id from the signature, and just honor the current device 🙂 Was there any historical or technical reason that required device id to be an argument of malloc/free?

**Comment by shwina** [comment]
> Actually, we wonder if it's better to remove device id from the signature, and just honor the current device

+1, although this feels like a larger API question for PyTorch. For example, it's possible to set a particular device as "current" in PyTorch while allocating memory on a different device (looking at the first example [here](https://pytorch.org/docs/stable/notes/cuda.html#cuda-semantics)).

For the shorter term, I'd be happy to see this PR merged! Thank you, @emcastillo!

**Review by albanD — APPROVED** [review]
Ok let's go with this then!

cc @zdevito in case you have an opinion for the larger question above.

**Comment by emcastillo** [comment]
@albanD Can you give me permission to merge this?
Thanks!!

**Comment by albanD** [comment]
@emcastillo it is approved so everyone has permission to merge it by asking the bot!

**Comment by emcastillo** [comment]
> @emcastillo it is approved so everyone has permission to merge it by asking the bot!

Sorry, My brain was in CuPy mode and desperately try to click the `Merge pull request` button 😂

**Comment by yiakwy-xpu-ml-framework-team** [comment]
hi @emcastillo cc @shwina @leofang, what's follow up of this PR, I am doing cu mem tracer for imperative graph, for multiple GPUS, I want to count how memory (segments, blocks) allocated totally for each device (GPU).

Any new progress ?

**Comment by zdevito** [comment]
https://pytorch.org/docs/stable/torch_cuda_memory.html#torch.cuda.memory._snapshot should have the information you want.

**Pull request closed without merging**
