### PR TITLE
SparseCsrCUDA: cuSolverSP backend for linalg.solve

### LINKED ISSUE #69538: cuSOLVER backend for Sparse CSR direct linear solvers
## 🚀 Feature

cuSolverSP (part of cuSOLVER) provides linear solver, least-square solver routines for matrices in CSR format. We can use it as a backend for `torch.linalg.solve` and `torch.linalg.lstsq`.

We are working on improving coverage of Sparse CSR matrices in PyTorch. Solving systems of linear equations is one of the fundamental operations in computational linear algebra.

From cuSOLVER docs:
> The high-level API is designed for ease-of-use, so it allocates any required memory under the hood automatically. If the host or GPU system memory is not enough, an error is returned.

Unfortunately, it means these functions do not allow passing externally allocated buffers, and paths with inputs on GPU are not implemented (there remarks for relevant functions "only CPU (Host) path is provided").

- [ ] `torch.linalg.solve`
    Use [`cusolverSp<t>csrlsvlu`](https://docs.nvidia.com/cuda/cusolver/index.html#cusolver-lt-t-gt-csrlsvlu). 

- [ ] `torch.linalg.lstsq`
    Use [`cusolverSp<t>csrlsqvqr`](https://docs.nvidia.com/cuda/cusolver/index.html#cusolver-lt-t-gt-csrlsqvqr)

cc @nikitaved @pearu @cpuhrsch @IvanYashchuk @ngimel @jianyuh @mruberry @walterddr @xwang233 @Lezcano

### PR DESCRIPTION
**Pull request by zitongzhan**
This PR picks up the incomplete progress of #71399 and fix #69538

### CODE REVIEW

**Comment by zitongzhan** [comment]
Looking for help regarding a linking issue. 
Below is the error message:
```
[333/338] Linking CXX executable bin/test_jit
FAILED: bin/test_jit 
: && /usr/bin/c++ -D_GLIBCXX_USE_CXX11_ABI=1 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow -DHAVE_AVX512_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -g -fno-omit-frame-pointer -O0 -rdynamic -Wl,-rpath-link,/home/csgrad/zzhan4/miniforge3/envs/dev/lib     -Wl,--no-as-needed test_jit/CMakeFiles/test_jit.dir/__/common/main.cpp.o test_jit/CMakeFiles/test_jit.dir/test_add_if_then_else.cpp.o test_jit/CMakeFiles/test_jit.dir/test_alias_analysis.cpp.o test_jit/CMakeFiles/test_jit.dir/test_argument_spec.cpp.o test_jit/CMakeFiles/test_jit.dir/test_autodiff.cpp.o test_jit/CMakeFiles/test_jit.dir/test_load_upgraders.cpp.o test_jit/CMakeFiles/test_jit.dir/test_op_replacement.cpp.o test_jit/CMakeFiles/test_jit.dir/test_upgrader_utils.cpp.o test_jit/CMakeFiles/test_jit.dir/test_backend.cpp.o test_jit/CMakeFiles/test_jit.dir/test_class_import.cpp.o test_jit/CMakeFiles/test_jit.dir/test_class_parser.cpp.o test_jit/CMakeFiles/test_jit.dir/test_class_type.cpp.o test_jit/CMakeFiles/test_jit.dir/test_code_template.cpp.o test_jit/CMakeFiles/test_jit.dir/test_concat_opt.cpp.o test_jit/CMakeFiles/test_jit.dir/test_constant_pooling.cpp.o test_jit/CMakeFiles/test_jit.dir/test_cleanup_passes.cpp.o test_jit/CMakeFiles/test_jit.dir/test_create_autodiff_subgraphs.cpp.o test_jit/CMakeFiles/test_jit.dir/test_custom_class.cpp.o test_jit/CMakeFiles/test_jit.dir/test_custom_class_registrations.cpp.o test_jit/CMakeFiles/test_jit.dir/test_custom_operators.cpp.o test_jit/CMakeFiles/test_jit.dir/test_dce.cpp.o test_jit/CMakeFiles/test_jit.dir/test_fuser.cpp.o test_jit/CMakeFiles/test_jit.dir/test_graph_executor.cpp.o test_jit/CMakeFiles/test_jit.dir/test_graph_iterator.cpp.o test_jit/CMakeFiles/test_jit.dir/test_cs_debug_info_serialization.cpp.o test_jit/CMakeFiles/test_jit.dir/test_inliner.cpp.o test_jit/CMakeFiles/test_jit.dir/test_interface.cpp.o test_jit/CMakeFiles/test_jit.dir/test_interpreter.cpp.o test_jit/CMakeFiles/test_jit.dir/test_ir.cpp.o test_jit/CMakeFiles/test_jit.dir/test_irparser.cpp.o test_jit/CMakeFiles/test_jit.dir/test_jit_type.cpp.o test_jit/CMakeFiles/test_jit.dir/test_lite_interpreter.cpp.o test_jit/CMakeFiles/test_jit.dir/test_lite_interpreter_direct.cpp.o test_jit/CMakeFiles/test_jit.dir/test_lite_trainer.cpp.o test_jit/CMakeFiles/test_jit.dir/test_memory_dag.cpp.o test_jit/CMakeFiles/test_jit.dir/test_misc.cpp.o test_jit/CMakeFiles/test_jit.dir/test_mobile_type_parser.cpp.o test_jit/CMakeFiles/test_jit.dir/test_module_api.cpp.o test_jit/CMakeFiles/test_jit.dir/test_peephole_optimize.cpp.o test_jit/CMakeFiles/test_jit.dir/test_qualified_name.cpp.o test_jit/CMakeFiles/test_jit.dir/test_save_load.cpp.o test_jit/CMakeFiles/test_jit.dir/test_schema_info.cpp.o test_jit/CMakeFiles/test_jit.dir/test_schema_matching.cpp.o test_jit/CMakeFiles/test_jit.dir/test_stack_opt.cpp.o test_jit/CMakeFiles/test_jit.dir/test_subgraph_matcher.cpp.o test_jit/CMakeFiles/test_jit.dir/test_subgraph_rewriter.cpp.o test_jit/CMakeFiles/test_jit.dir/test_subgraph_utils.cpp.o test_jit/CMakeFiles/test_jit.dir/test_union.cpp.o test_jit/CMakeFiles/test_jit.dir/test_utils.cpp.o test_jit/CMakeFiles/test_jit.dir/test_script_profile.cpp.o test_jit/CMakeFiles/test_jit.dir/test_shape_analysis.cpp.o test_jit/CMakeFiles/test_jit.dir/test_jit_logging_levels.cpp.o test_jit/CMakeFiles/test_jit.dir/test_file_format.cpp.o test_jit/CMakeFiles/test_jit.dir/test_flatbuffer.cpp.o -o bin/test_jit  -Wl,-rpath,/home/csgrad/zzhan4/dev/pytorch/build/lib:/usr/local/cuda/lib64:  lib/libgtestd.a  lib/libjitbackend_test.so  lib/libbackend_with_compiler.so  -Wl,--no-as-needed,/home/csgrad/zzhan4/dev/pytorch/build/lib/libjitbackend_test.so,/home/csgrad/zzhan4/dev/pytorch/build/lib/libbackend_with_compiler.so,--as-needed  lib/libdnnl.a  -ldl  lib/libtorch.so  -Wl,--no-as-needed,"/home/csgrad/zzhan4/dev/pytorch/build/lib/libtorch_cpu.so" -Wl,--as-needed  lib/libprotobufd.a  -Wl,--no-as-needed,"/home/csgrad/zzhan4/dev/pytorch/build/lib/libtorch_cuda.so" -Wl,--as-needed  lib/libc10_cuda.so  lib/libc10.so  /usr/local/cuda/lib64/libcudart.so  /usr/local/cuda/lib64/libnvToolsExt.so && /home/csgrad/zzhan4/miniforge3/envs/dev/bin/cmake -E __run_co_compile --lwyu="ldd;-u;-r" --source=bin/test_jit && :
/usr/bin/ld: /home/csgrad/zzhan4/dev/pytorch/build/lib/libtorch_cuda.so: undefined reference to `void at::cuda::solver::lsvchol<double, double>(cusolverSpContext*, int, int, cusparseMatDescr*, double const*, int const*, int const*, double const*, double, int, double*, int*)'
/usr/bin/ld: /home/csgrad/zzhan4/dev/pytorch/build/lib/libtorch_cuda.so: undefined reference to `void at::cuda::solver::lsvchol<float, float>(cusolverSpContext*, int, int, cusparseMatDescr*, float const*, int const*, int const*, float const*, float, int, float*, int*)'
/usr/bin/ld: /home/csgrad/zzhan4/dev/pytorch/build/lib/libtorch_cuda.so: undefined reference to `void at::cuda::solver::lsvchol<c10::complex<float>, float>(cusolverSpContext*, int, int, cusparseMatDescr*, c10::complex<float> const*, int const*, int const*, c10::complex<float> const*, float, int, c10::complex<float>*, int*)'
/usr/bin/ld: /home/csgrad/zzhan4/dev/pytorch/build/lib/libtorch_cuda.so: undefined reference to `void at::cuda::solver::lsvchol<c10::complex<double>, double>(cusolverSpContext*, int, int, cusparseMatDescr*, c10::complex<double> const*, int const*, int const*, c10::complex<double> const*, double, int, c10::complex<double>*, int*)'
/usr/bin/ld: /home/csgrad/zzhan4/dev/pytorch/build/lib/libtorch_cuda.so: undefined reference to `at::cuda::getCurrentCUDASolverSpHandle()'
collect2: error: ld returned 1 exit status
```

**Comment by nWEIdia** [comment]
Actually, do you mind us asking you to try with cuDSS? 
cuDSS is supposed to cover all cuSolveSP can do, but with better performance. A good side-effect might be that you will no longer encounter these ld issues. 

Details of cuDSS: https://developer.nvidia.com/cudss

**Comment by zitongzhan** [comment]
> Actually, do you mind us asking you to try with cuDSS? cuDSS is supposed to cover all cuSolveSP can do, but with better performance. A good side-effect might be that you will no longer encounter these ld issues.
> 
> Details of cuDSS: https://developer.nvidia.com/cudss

Yea we are aware of cuDSS. @IvanYashchuk also suggested that. We want to evaluate perf benchmark for cuDSS first before switching to the new project.

**Comment by zitongzhan** [comment]
> Actually, do you mind us asking you to try with cuDSS? cuDSS is supposed to cover all cuSolveSP can do, but with better performance. A good side-effect might be that you will no longer encounter these ld issues.
> 
> Details of cuDSS: https://developer.nvidia.com/cudss

Btw, looks like nvidia is not yet shipping the cuDSS lib with CUDA. Do you know when will cuDSS move on to GA release?

**Comment by kvoronin** [comment]
> > Actually, do you mind us asking you to try with cuDSS? cuDSS is supposed to cover all cuSolveSP can do, but with better performance. A good side-effect might be that you will no longer encounter these ld issues.
> > Details of cuDSS: https://developer.nvidia.com/cudss
> 
> Btw, looks like nvidia is not yet shipping the cuDSS lib with CUDA. Do you know when will cuDSS move on to GA release?

Hi!
There are two separate questions in your question, I believe.
1) cuDSS is not part of CUDA CTK. There are reasons (beyond cuDSS being still 0.x) to keep cuDSS outside CTK. E.g., if we add distributed support, then cuDSS will not fit into the world view where distributed libraries live outside CTK (e.g., cuSolverMp, cuBLASMp, cuFFTMp).
2) cuDSS is in EA with 0.x versions. We are actively working on creating the GA release (1.0). A short answer to "when" is "as soon as we reach desired functional and performance completeness". There are features to be added before we want to do this, hence several intermediate releases after the current cudss 0.2.0 can be expected.
In terms of API, we follow semantic versioning and leave to ourselves the ability to make API changes before 1.0 but most of them which are planed are non-breaking additions with a very few exceptions based on the feedback about cudss 0.x.

**Review by lezcano — COMMENTED** [review]
This does not seem to be hooked to the Python frontend?
Also, this needs comprehensive tests.

**Pull request closed without merging**
