### PR TITLE
[RELAND] XPUHooksInterface inherits from AcceleratorHooksInterface

### PR DESCRIPTION
**Pull request by guangyey**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #129119
* #129363
* #129205
* __->__ #129463

cc @gujinghui @EikanWang @fengyuan14

### CODE REVIEW

**Review by gujinghui — APPROVED** [review]

**Comment by guangyey** [comment]
@albanD the CI failure is unrelated. Could you help review this series of PRs.

**Review by albanD — APPROVED** [review]
SGTM!

**Comment by kit1980** [comment]
@pytorchbot revert -m "breaking internal builds" -c ghfirst

```
aten/src/ATen/detail/XPUHooksInterface.h:14:11: error: '~XPUHooksInterface' overrides a destructor but is not marked 'override' [-Werror,-Winconsistent-missing-destructor-override]
   14 |   virtual ~XPUHooksInterface() = default;
      |           ^
```

**Comment by guangyey** [comment]
Unrelated failures.
@pytorchbot merge -i

**Pull request closed without merging**
