### PR TITLE
Back out "Fixing a bug where allocating a 4GB block results in using 8GB of memory (#95827)"

### PR DESCRIPTION
**Pull request by jaewonlee-fb**
Summary:
Original commit changeset: a19273017a2a

Original Phabricator Diff: D43969564

-----------------------------------------------------------------------------------------------------------------------

Test Plan: unlandayc

Reviewed By: terrycsy

Differential Revision: D44080273

### CODE REVIEW

**Comment by ngimel** [comment]
cc @akamali, looks like 32MB caching threshold is too aggressive - can you make the thresholds configurable via env vars, similarly to how it's done for cuda caching allocators?

**Review by jianyuh — APPROVED** [review]
I will stamp to unblock and then let @akamali / @jaewonlee-fb  to figure out more proper approach to land the original PR.

**Review by davidberard98 — APPROVED** [review]

**Pull request closed without merging**
