### PR TITLE
Manual submodule update: kineto (#82609)

### PR DESCRIPTION
**Pull request by aaronenyeshi**
Summary:
This is a manual pull request to update the first-party submodule for [pytorch/kineto](https://github.com/pytorch/kineto).

New submodule commit: https://github.com/pytorch/kineto/commit/0a2af89149ce2103281bfc995f0c250bd801c506

Test Plan: Ensure that CI jobs succeed on GitHub before landing.

Differential Revision: D38322833

Pulled By: aaronenyeshi

### CODE REVIEW

**Review by robieta — APPROVED** [review]

**Comment by aaronenyeshi** [comment]
Weird, when I run the test locally, it is passing.
```
test_bottleneck_cuda (__main__.TestBottleneck) ... ok
```

**Pull request closed without merging**
