### PR TITLE
Don't recompute numel and contiguous in detach

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #112785
* #112890
* __->__ #112689

When symolic shapes are involved, `refresh_numel` and `refresh_contiguous` are
fairly expensive since they dispatch to python for SymInt handling. However, in
the case of detach we can just copy the existing values instead.

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
Looks reasonable to me, but let me tag @ezyang  and @albanD  in case they have any concerns.

**Review by ezyang — APPROVED** [review]
Thanks, much appreciated.

**Pull request closed without merging**
