### PR TITLE
[Nested Tensor][easy] Add softmax backward support

### PR DESCRIPTION
**Pull request by YuqingJ**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #130602

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @soulitzer @davidberard98

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]

**Review by jbschlosser — APPROVED** [review]
LGTM thanks for the fix!

**Pull request closed without merging**
