### PR TITLE
Factor out Submod compilers

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #120727
* #120523
* __->__ #120527

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by kadeng — APPROVED** [review]
It's a bit hard to track the differences between the original SubmoduleCompiler and the refactored version ( the diff tool does not help much there), but if I did not overlook anything, there is no functional change, right? You copied the classes to the outer scope and made fake mode an attribute of the SubmoduleCompiler, because it's not provided by the enclosing scope anymore. 

So, looks good to me. Thanks ...

**Comment by eellison** [comment]
Right, no functional changes here

**Pull request closed without merging**
