### PR TITLE
Let add, sub, mul, and div on CPU support Half type.

### PR DESCRIPTION
**Pull request by xuhdev**
Their CUDA counterparts do not have this issue.

### CODE REVIEW

**Comment by zou3519** [comment]
Are we supporting CPU Half? cc @gchanan

**Comment by gchanan** [comment]
I don't think we should do this, at least not without good copy logging in place.  The implementation is convert -> op -> convert, which is slow, especially if you have a number of these ops in a chain.  And we don't have good logging/debugging around where we do copies/conversions, so this would mainly be silent to user.  It is clearer and faster as it is now to just force the user to do a conversion.

**Comment by xuhdev** [comment]
OK. It then might be better to inform users about this? I have two solutions in mind:

- We add support for Half on CPU, but instead of silently doing so, we let PyTorch emit a warning on its performance and the expense behind the scene.
- We do not support Half on CPU, but let PyTorch emit a more meaningful error instead of a generic error.

**Comment by colesbury** [comment]
I'm in favor of this sort of change. The conversion in-place is can be much faster than the current copy-add-copy style workflow.

I don't see logging as a necessary requirement for basic functionality. For example, double arithmetic on many GPUs is more than an order of magnitude slower than float32 but we still support it.

Note that to do this efficiently on x86-64 you'll want to use _mm256_cvtps_ph which requires FP16C support.
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm256_cvtps_ph&expand=1769

**Comment by gchanan** [comment]
> Note that to do this efficiently on x86-64 you'll want to use _mm256_cvtps_ph which requires FP16C support.

Do we have a benchmark using this?  Last time @nairbv did a benchmark (note: I believe this was without use of the intrinsic) I believe the results weren't much better (if any) than copy-and-copy.

**Comment by xuhdev** [comment]
Maybe I missed something, but seems to be that _mm256_cvtps_ph should have already been used in `_cast_Half` regardless of this PR. Is `_cast_Half` already using it? I don't seem to be able to find its definition.

**Comment by nairbv** [comment]
I'm confused. I see this build succeeded and tests passed, but if I try applying these same changes on a dev server I'm getting:
```
../aten/src/ATen/cpu/vec256/vec256_base.h:87:17: error: invalid initializer for array member ‘c10::Half at::vec256::{anonymous}::Vec256<c10::Half>::values [16]’
   Vec256(T val) {
                 ^
../aten/src/ATen/cpu/vec256/vec256_base.h: In instantiation of ‘at::vec256::{anonymous}::Vec256<T>::Vec256() [with T = c10::Half]’:
../aten/src/ATen/cpu/vec256/vec256_base.h:304:27:   required from ‘at::vec256::{anonymous}::Vec256<T> at::vec256::{anonymous}::operator*(const at::vec256::{anonymous}::Vec256<T>&, const at::vec256::{anonymous}::Vec256<T>&) [with T = c10::Half]’
aten/src/ATen/native/cpu/BinaryOpsKernel.cpp.AVX.cpp:40:5:   required from here
```

Here's an example of an (abandoned, different) change I had made that performed far more slowly in testing:

https://github.com/pytorch/pytorch/pull/20061/commits/4e6618e86394a729a84f39f1b9d396a2412470af

IIRC, using that code was on the order of about 20-30x slower than converting a tensor to float, performing an operation, then converting back to half.

This diff seems to be relying on the vectorized vec256::fmadd, but I would expect that to require a vec256_half.h? But again I see the tests pass so I'm not sure what I'm missing here.

**Comment by xuhdev** [comment]
@nairbv I updated the patch that attempts to fix your issue. Could you try again?

**Comment by nairbv** [comment]
> @nairbv I pushed an update that attempts to fix your issue. Could you try again?

Compilation still fails for me, but, given that it's building on circle ci it seems like the issue should be something on my end. Not sure what I'm missing or what could be different between my env and circleci.

**Comment by ezyang** [comment]
It is probably an issue with an old version of GCC. @nairbv what is your GCC version? I'm pretty sure CircleCI runs newer GCCs than the default on our devgpus.

**Comment by nairbv** [comment]
> It is probably an issue with an old version of GCC. @nairbv what is your GCC version? I'm pretty sure CircleCI runs newer GCCs than the default on our devgpus.

I'm on 4.8.5

**Comment by xuhdev** [comment]
> > It is probably an issue with an old version of GCC. @nairbv what is your GCC version? I'm pretty sure CircleCI runs newer GCCs than the default on our devgpus.
> 
> I'm on 4.8.5

Hmm, comments in torch/utils/cpp_extension.py actually warns about GCC < 4.9...

**Comment by nairbv** [comment]
> > I'm on 4.8.5
> 
> Hmm, comments in torch/utils/cpp_extension.py actually warns about GCC < 4.9...

Interesting. I think many of us our using 4.8.5 for development. @goldsborough, it looks like you added this warning, are there any issues this causes?

**Comment by gchanan** [comment]
but those warnings are about ABI compatibility on extensions, and these errors are compile time in core, right?

**Comment by xuhdev** [comment]
> but those warnings are about ABI compatibility on extensions, and these errors are compile time in core, right?

Yes. What I meant is that PyTorch does not seem to intend to support gcc < 4.9

**Comment by gchanan** [comment]
> Yes. What I meant is that PyTorch does not seem to intend to support gcc < 4.9

ah, okay, I get your point.  FYI a bunch of the core devs use machines with out-of-the-box gcc 4.8, so it would take some work to move them over :).

**Comment by xuhdev** [comment]
> > Yes. What I meant is that PyTorch does not seem to intend to support gcc < 4.9
> 
> ah, okay, I get your point. FYI a bunch of the core devs use machines with out-of-the-box gcc 4.8, so it would take some work to move them over :).

OK. I smell RHEL :)

**Comment by izdeby** [comment]
I have the same problem as @nairbv. We should fix this issue before landing this PR as It will block us all once its merged.

**Comment by xuhdev** [comment]
I tried this on g++ 4.8.5. Surprisingly, I got a gcc bug:

```
In file included from /home/hong/wsrc/pytorch/aten/src/ATen/cpu/vec256/vec256.h:5:0,                                          
                 from /home/hong/wsrc/pytorch/build/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp.AVX2.cpp:5:                  
/home/hong/wsrc/pytorch/aten/src/ATen/cpu/vec256/vec256_base.h: In instantiation of ‘at::vec256::{anonymous}::Vec256<T>::Vec25
6(T) [with T = c10::Half]’:                                                                                                   
/home/hong/wsrc/pytorch/build/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp.AVX2.cpp:20:5:   required from here                
/home/hong/wsrc/pytorch/aten/src/ATen/cpu/vec256/vec256_base.h:87:17: internal compiler error: Segmentation fault             
   Vec256(T val) {         
```

**Comment by gchanan** [comment]
ouch.  Is this reproducible on godbolt?

**Comment by nairbv** [comment]
I also get that segfault on a dev server

**Comment by xuhdev** [comment]
@nairbv I added some workaround (which essentially modernizes vec256 a bit), and it seems working for me. Could you give it a try?

**Pull request closed without merging**
