### PR TITLE
[MPS] Fix mps to cpu casting from a smaller dtype to a bigger dtype

### LINKED ISSUE #82566: MacOS MPS: src_total_size >= storage_byte_offset
### 🐛 Describe the bug

When converting a result from MPS backend to CPU, I get this error:

src_total_size >= storage_byte_offset INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Copy.mm":129, please report a bug to PyTorch. 

This is the code that fails:
```C++
        if (!o.device().is_cpu())
        {
            if (o.dtype() != torch::kFloat)
            {
                o = o.to(torch::kCPU, torch::kFloat);
            }
            else
            {
                o = o.to(torch::kCPU);
            }
        }
```
This, as a workaround, appears to not fail (note: the tensor is already a float):
```
if (!o.device().is_cpu())
{
    o = o.to(torch::kCPU);
}
```

It says to report it so I have put it here.

### Versions

Nightly pip for 1st August

cc @kulinseth @albanD

### PR DESCRIPTION
**Pull request by kulinseth**
Fixes #82566 , #80800 

- mps->cpu casts from a smaller dtype to a bigger dtype mps->mps cast from smaller/bigger dtype to another dtype in case of scatter 
- For mps->cpu copies where we don't have a source/destination offset, we can save the cast result directly in the destTensor, so we can skip the additional overhead of the blit. 
- In case we can return the data without doing the blit, we need to check if it's blocking call, case in which we'd need a synchronize(SyncType::COMMIT_AND_WAIT); call (previously this was done by the blit).

### CODE REVIEW

**Review by razarmehr — APPROVED** [review]
Looks good.

**Comment by kulinseth** [comment]
> The following jobs have failed:
> * [Test collect_env (older_python_version)](https://github.com/pytorch/pytorch/actions/runs/3048724514/jobs/4914089726)
> * [Test tools](https://github.com/pytorch/pytorch/actions/runs/3048724514/jobs/4914089120)
> 
> This comment was automatically generated by Dr. CI and updates every 15 minutes.

'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcb3dbf5a60>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/ca/87/bf1fab5dc5d8ecd30fab4ecb6114881b5cc3859e5d4a6c9b2c48f7d70276/certifi-2022.6.15.2-py3-none-any.whl
[54](https://github.com/pytorch/pytorch/actions/runs/3048724514/jobs/4914089120#step:4:55)
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcb3dbf5c10>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/ca/87/bf1fab5dc5d8ecd30fab4ecb6114881b5cc3859e5d4a6c9b2c48f7d70276/certifi-2022.6.15.2-py3-none-any.whl
[55](https://github.com/pytorch/pytorch/actions/runs/3048724514/jobs/4914089120#step:4:56)
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcb3dbf5dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/ca/87/bf1fab5dc5d8ecd30fab4ecb6114881b5cc3859e5d4a6c9b2c48f7d70276/certifi-2022.6.15.2-py3-none-any.whl
[56](https://github.com/pytorch/pytorch/actions/runs/3048724514/jobs/4914089120#step:4:57)
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcb3dbf5c70>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/ca/87/bf1fab5dc5d8ecd30fab4ecb6114881b5cc3859e5d4a6c9b2c48f7d70276/certifi-2022.6.15.2-py3-none-any.whl
[57](https://github.com/pytorch/pytorch/actions/runs/3048724514/jobs/4914089120#step:4:58)
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/ca/87/bf1fab5dc5d8ecd30fab4ecb6114881b5cc3859e5d4a6c9b2c48f7d70276/certifi-2022.6.15.2-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcb3dbff220>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[58](https://github.com/pytorch/pytorch/actions/runs/3048724514/jobs/4914089120#step:4:59)

Failure are un-related.

**Pull request closed without merging**
