### PR TITLE
[core IR] Add glu as a core decomposition

### PR DESCRIPTION
**Pull request by SS-JIA**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #110102
* __->__ #110043
* #110046

## Context

Add the decomposition for `aten.glu` as a decomposition in the core ATen decomposition table. Don't use it in the Inductor decomposition table since Inductor has a lowering for it.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by peterbell10 — APPROVED** [review]

**Review by lezcano — APPROVED** [review]
At some point we should audit whether we can remove some of those lowerings form Inductor, but this is already a first step :)

**Comment by SS-JIA** [comment]
```
PYTORCH_TEST_WITH_DYNAMO=1 python test_ops.py -k test_out_warning__refs_clamp_cpu
```

The failing test is reproducible on the base commit. Likely not related to these changes.

**Pull request closed without merging**
