### PR TITLE
[dynamo] Fix an error in _dynamo.compiled_autograd.reset()

### PR DESCRIPTION
**Pull request by rec**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137889

----

* From https://github.com/pytorch/pytorch/pull/133492

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Comment by rec** [comment]
A minimal version.

I thought of hiding that mutable, global variable entire behind a pair of module-level getter/setter functions which would also force us to clean up rough ideas like [this one](https://github.com/pytorch/pytorch/blob/0e4d42634e08ef67fa5e2ad0cb721b8e7eea26f1/torch/distributed/_composable/fsdp/_fsdp_param.py#L29-L33) but decided it wasn't important enough...

**Review by Skylion007 — APPROVED** [review]

**Comment by kit1980** [comment]
2.5.1 is an emergency patch release to address known large regressions, moving this to 2.6.0

**Comment by kit1980** [comment]
Verified for PyTorch 2.6 release candidate:

```
import torch
from torch._dynamo import compiled_autograd
compiled_autograd.compiled_autograd_enabled = True
compiled_autograd.reset()
assert(compiled_autograd.compiled_autograd_enabled == False)
```

**Pull request closed without merging**
