### PR TITLE
Install missing VSX headers (POWER)

### PR DESCRIPTION
**Pull request by Flamefire**
E.g. `test_cpp_extensions_aot_ninja` fails as it includes `vec.h` which requires the vec/vsx/* headers and `sleef.h`. The latter is also required for AVX512 builds on non MSVC compilers.

### CODE REVIEW

**Review by kit1980 — APPROVED** [review]

**Comment by kit1980** [comment]
@Flamefire Are you still interested in merging this? Can you sign the CLA and resolve merge conflicts?

**Comment by Flamefire** [comment]
@kit1980 Sorry took a while to get the new CLA approved going through company processes...

Rebased, CLA signed, merge conflict resolved.

**Comment by kit1980** [comment]
Let me import this to check that Meta-internal builds are ok.

**Pull request closed without merging**
