### PR TITLE
[ONNX] Remove argument _retain_param_name from torch.onnx.export() function.

### PR DESCRIPTION
**Pull request by fatcat-z**
As of now, the "_retain_param_name" parameter has no description in PyTorch docs website. According to code, this argument determines if we keep the original parameter names of PyTorch model in the final ONNX graph. If this is False, those original parameter names will be replaced with a series of integers starting from 1.

Since setting numbers as parameter names make no sense to users, we remove this argument from the torch.onnx.export() function to increase user experience of calling this function.

This PR will still keep it in torch.onnx.export() function for backward support while all backend logic has been changed to work as _retain_param_name is set to True.

### CODE REVIEW

**Review by jiafatom — COMMENTED** [review]
Do we have a unit test to compare the param name and verify the param name are indeed retained? (since `_retain_param_name=True`)

**Comment by fatcat-z** [comment]
> Do we have a unit test to compare the param name and verify the param name are indeed retained? (since `_retain_param_name=True`)



> Do we have a unit test to compare the param name and verify the param name are indeed retained? (since `_retain_param_name=True`)

No



> Do we have a unit test to compare the param name and verify the param name are indeed retained? (since `_retain_param_name=True`)

No we don't. Will add one.

**Comment by fatcat-z** [comment]
> Do we have a unit test to compare the param name and verify the param name are indeed retained? (since `_retain_param_name=True`)

Just found out TestONNXRuntime.test_initializer_sequence could do this.

**Review by jiafatom — APPROVED** [review]
LGTM!

**Pull request merged**
