### PR TITLE
[Caffe2] Remove unused AVX512 code

### PR DESCRIPTION
**Pull request by cyyever**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
SGTM
cc @r-barnes what's the right way to merge this one?

**Comment by cyyever** [comment]
@albanD Import into META to check their builds?

**Review by albanD — COMMENTED** [review]
Internal diff looked clean enough

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
