### PR TITLE
[Easy][FSDP] Minor doc fixes

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74215 [FSDP] Add full optim state dict
* **#74214 [Easy][FSDP] Minor doc fixes**

Differential Revision: [D35045122](https://our.internmc.facebook.com/intern/diff/D35045122)

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Thank you for improving our documentation!

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35045122).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35045122).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35045122).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35045122).

**Comment by awgu** [comment]
@awgu has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35045122).

**Comment by janeyx99** [comment]
Reverting--broke docs job as can be seen in PR CI as well. Please make sure the docs job passes when relanding this PR.

**Pull request closed without merging**
