### PR TITLE
Add step to report code coverage from GHA

### LINKED ISSUE #63366: codecoverage reporting does not work in GHA
After https://github.com/pytorch/pytorch/pull/61050 was merged, coverage reporting logic defined in
https://github.com/pytorch/pytorch/blob/b2069e7d01814d776c417042e28133c6b0e5082f/.circleci/verbatim-sources/job-specs/pytorch-job-specs.yml#L197-L201
ceased to work

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

### PR DESCRIPTION
**Pull request by malfet**
Similar to the logic provided in https://github.com/pytorch/pytorch/blob/b2069e7d01814d776c417042e28133c6b0e5082f/.circleci/verbatim-sources/job-specs/pytorch-job-specs.yml#L197-L201

Fixes https://github.com/pytorch/pytorch/issues/63366

### CODE REVIEW

**Review by walterddr — APPROVED** [review]
good catch. although i wonder why we don't just do it in https://github.com/pytorch/pytorch/blob/e60f7e3ecf94942dcf64c888c68a3ca2f2dcddde/.jenkins/pytorch/test.sh#L537

**Comment by malfet** [comment]
@walterddr it wouldn't work in CircleCI, as this script is executed inside docker container, which does not have credentials needed to report it back to codecov

**Comment by seemethere** [comment]
Are we sure this is running correctly, looks like `gcov` isn't on the host machines but it's still silently passing,
     
```
Error running `['gcov', '-pb', '/home/ec2-user/actions-runner/_work/pytorch/pytorch/build/modules/observers/CMakeFiles/caffe2_observers.dir/perf_observer.cc.gcno']`: returncode=None, output=[Errno 2] No such file or directory: 'gcov': 'gcov'
```

**Comment by malfet** [comment]
@seemethere thank you for highlighting. We technically don't need `gcov` as we are running it inside the docker, but can install it on the host machine as well.

**Pull request closed without merging**
