### PR TITLE
Correct dynamo logging docs

### LINKED ISSUE #105657: dynamo logging not documented correctly in the deep dive
### 🐛 Describe the bug

As per documentation [https://pytorch.org/docs/stable/dynamo/deep-dive.html](https://pytorch.org/docs/stable/dynamo/deep-dive.html) it says to activate logging you should

```
import torch._dynamo.config
import logging

torch._dynamo.config.log_level = logging.INFO
torch._dynamo.config.output_code = True 
```

I have a working program : 

```
import torch
import torch._dynamo

def g(x):
    return (x + x)

x = torch.tensor(12)
print(torch.compile(g)(x))
```

I add the the snippet from the document after my existing imports and get this error: 
```
Traceback (most recent call last):
  File "/Users/davidradley/pytorch/test/test2.py", line 7, in <module>
    torch._dynamo.config.output_code = True
  File "/Users/davidradley/pytorch/torch/_dynamo/config_utils.py", line 72, in __setattr__
    raise AttributeError(f"{self.__name__}.{name} does not exist")
AttributeError: torch._dynamo.config.output_code does not exist
(base) davidradley@Davids-MBP-2 pytorch % python test/test2.py
Traceback (most recent call last):
  File "/Users/davidradley/pytorch/test/test2.py", line 4, in <module>
    torch._dynamo.config.log_level = logging.INFO
  File "/Users/davidradley/pytorch/torch/_dynamo/config_utils.py", line 72, in __setattr__
    raise AttributeError(f"{self.__name__}.{name} does not exist")
AttributeError: torch._dynamo.config.log_level does not exist
(base) davidradley@Davids-MBP-2 pytorch % python test/test2.py
tensor(256)
(base) davidradley@Davids-MBP-2 pytorch % python test/test2.py
tensor(24)
(base) davidradley@Davids-MBP-2 pytorch % python test/test2.py
Traceback (most recent call last):
  File "/Users/davidradley/pytorch/test/test2.py", line 7, in <module>
    torch._dynamo.config.log_level = logging.INFO
  File "/Users/davidradley/pytorch/torch/_dynamo/config_utils.py", line 72, in __setattr__
    raise AttributeError(f"{self.__name__}.{name} does not exist")
AttributeError: torch._dynamo.config.log_level does not exist
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git6ca3d7e
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.6
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ] (64-bit runtime)
Python platform: macOS-13.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.1.0a0+gitf353d17
[pip3] torchgen==0.0.1
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] torch                     2.1.0a0+git6ca3d7e           dev_0    <develop>
[conda] torchgen                  0.0.1                    pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

### PR DESCRIPTION
**Pull request by davidradl**
Fixes #105657

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

### CODE REVIEW

**Comment by zou3519** [comment]
PR looks fine, but the docs tests appear to be failing.

**Comment by davidradl** [comment]
> PR looks fine, but the docs tests appear to be failing.

I made another change which it is still processing, the links were not right. Hopefully that will solve the docs build issue.

**Comment by davidradl** [comment]
@zou3519 looks clean - are you ok to approve ?

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
