### PR TITLE
Remove ignore shapes arg

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #71173
* #71138
* #70656
* #70464
* __->__ #71144

This wasn't being used anywhere. It was originally intended for the SR flow but we're doing something else now.

Differential Revision: [D33521061](https://our.internmc.facebook.com/intern/diff/D33521061)

### CODE REVIEW

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33521061).

**Review by ZolotukhinM — APPROVED** [review]
LGTM!

**Review by Neilblaze — APPROVED** [review]

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33521061).

**Review by navahgar — APPROVED** [review]
Thanks for removing this.

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33521061).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33521061).

**Comment by eellison** [comment]
@eellison has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33521061).

**Pull request closed without merging**
