### PR TITLE
Correctly propagate compiler kwargs to aot minifier

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #93308

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Comment by ezyang** [comment]
No test yet, I also need to check if the other sites in this file make the same bug. Putting it up in case it unblocks anyone.

**Review by Chillee — APPROVED** [review]

**Review by voznesenskym — APPROVED** [review]

**Comment by mlazos** [comment]
cc @williamwen42 can you check if your tests are running and if this would cause them to fail or not?

**Pull request closed without merging**
