### PR TITLE
Support eager mode use of torch.jit.isinstance with multiple types

### LINKED ISSUE #60095: `torch.jit.isinstance` doesn't account for tuple literals in eager mode
## 🐛 Bug

In Python, `isinstance` can be used with a single element or a tuple of elements. `torch.jit.isinstance` doesn't consider the case that we want to compare against a tuple of elements.

## Example

```python
import torch
from typing import List

def fn(x: int):
    if torch.jit.isinstance(x, (List[str], str)):
        z = x + "bar"
        return z
    else:
        return "baz"
```

The above example errors out with:
```
Traceback (most recent call last):
  File "test/tinytest.py", line 11, in <module>
    print(fn(1))
  File "test/tinytest.py", line 5, in fn
    if torch.jit.isinstance(x, (List[str], str)):
  File "/home/ansley/local/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/__init__.py", line 185, in isinstance
    return _isinstance(obj, target_type)
  File "/home/ansley/local/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/_jit_internal.py", line 1145, in _isinstance
    return isinstance(obj, target_type)
  File "/home/ansley/local/miniconda3/envs/pytorch/lib/python3.8/typing.py", line 769, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/home/ansley/local/miniconda3/envs/pytorch/lib/python3.8/typing.py", line 777, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

Note that this is only a problem in eager (Python) mode. If you run it in script (`torch.jit.script`) mode, it will be fine.

## Notes

This would be a nice introduction to the PyTorch codebase. I'm writing notes here with the idea that this would be an OSS project or a Bootcamp task.

Our implementation of `torch.jit.isinstance` is at `torch/_jit_internal.py:_isinstance`. In `_isinstance`, if `target_type` is a tuple literal, the logic falls through to the line `return isinstance(obj, target_type)`, which fails for "subscripted generics". A "subscripted generic" is a type annotation that has other types inside it, e.g. `List[int]`, `Dict[str, int]`, `Optional[int]`. (Some examples of types that are NOT subscripted generics are `int`, `str`, etc.)

What we want to do is: Check if current element is a tuple literal containing types. If we do have a tuple literal, try calling `_isinstance` on all types in the tuple. If any of the elements in the tuple are subtypes of the current element, return `true`, else return `false`.

I haven't coded this up myself. If my suggested algorithm breaks everything and you want to yell at me, reach out at `ansley@fb.com`

cc @gmagogsfm

### PR DESCRIPTION
**Pull request by karolsputo**
Fixes #60095

### CODE REVIEW

**Comment by suo** [comment]
@ansley are you going to look at this or should I?

**Comment by ansley** [comment]
Sorry I missed this! I think this notification got buried under a big pile of CI failure emails.

@karolsputo This implementation overall looks great. Can you also add some test cases? They should be put in `test/jit/test_isinstance`. You can use our helper method `checkScript(<function-name>, <tuple of args>)` to test that the output of the TorchScript'ed function is the same as the vanilla Python. Here's an example of a test case:

```python
# This is part of the `TestIsinstance` class, which is why we need
# the `self` argument
def test_tuple_rhs(self):
    # Function to test. Note that we don't decorate it with
    # `torch.jit.script` since we'll be using `checkScript` later
    def fn(x: int):
        if torch.jit.isinstance(x, (List[str], str)):
            z = x + "bar"
            return z
        else:
            return "baz"

    # Compare the output of the normal Python function to the output of
    # the torch.jit.script'd function
    self.checkScript(fn, (1,))
```

If you want to assert that a certain function throws a RuntimeError, use `with self.assertRaisesRegex(RuntimeError, <expected message>`. You can see `test_list_no_contained_type` in `TestIsinstance` as an example of this.

**Review by ansley — APPROVED** [review]
Looks good. I tested it on my machine with py3.8, and it works well, though I did see your note about there being discrepancies between Python versions. Add some test cases and we'll be ready to go

**Comment by karolsputo** [comment]
@ansley
Sorry for the wait, I've added a few test cases and it passes fine and fails without the change.

If that's ok with you I think we should go ahead.

Do you have any idea about my next steps? I'd like to do more, so if you have something at the back of your head that you would love to get done let me know, if not I'll just search through the open issues.

**Comment by ansley** [comment]
@karolsputo Thanks so much for your contribution! Sorry again that I missed the original notification. [This](https://github.com/pytorch/pytorch/issues/54873) is an easy issue in the same area of the codebase that you could take. We can't fix it right now without introducing slow code/tech debt, but we would love it if someone could add a warning. Otherwise, you can look at issues tagged "bootcamp", "good first issue", and perhaps even "days" (signifies that a full-time PyTorch engineer would take days--note that this might be a weeks project for someone unfamiliar with our system!) or "jit-backlog" (low-pri tasks that we haven't gotten around to). If you take one tagged jit-backlog, please tag me so that I can make sure the issue is still relevant. 

Do you have an email address? I can keep my eye open for good small tasks and send them to you if you'd like to contribute regularly.

**Comment by karolsputo** [comment]
Thanks, I'll take a look. 

If you find something I might be able to tackle feel free to email me at karol.sputo@gmail.com and I'll try 😀

**Pull request closed without merging**
