### PR TITLE
Revert "Revert "Add `_foreach_clamp` (#106574)""

### PR DESCRIPTION
**Pull request by crcrpar**
This reverts commit 354484ea6d85ce2da90fd3e1e5fa9524987bcfe6.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @Xia-Weiwen @ngimel

### CODE REVIEW

**Comment by crcrpar** [comment]
@kit1980 would you happen to have the entire error message of https://github.com/pytorch/pytorch/pull/106574#issuecomment-1675397781?

**Comment by kit1980** [comment]
> @kit1980 would you happen to have the entire error message of [#106574 (comment)](https://github.com/pytorch/pytorch/pull/106574#issuecomment-1675397781)?

@crcrpar That's all I see (despite bunch of unrelated warnings before that).
If you have an idea what to try, I can import your PR and try to build internally.

**Comment by ptrblck** [comment]
Could [this](https://stackoverflow.com/a/7035078) be related? Did we see similar issues before on Windows?

**Comment by crcrpar** [comment]
hmm, not sure as this PR use max and min as an argument name

**Comment by crcrpar** [comment]
@kit1980 @janeyx99 would you mind sharing the errors of that "import" (if any) with me?

**Comment by kit1980** [comment]
@crcrpar I see bunch of failures. I've started a re-run and will investigate.

**Comment by crcrpar** [comment]
would you have any updates?

**Comment by kit1980** [comment]
> would you have any updates?

I'm trying to understand what's going on. Bunch of builds failed, but I can't find actual errors...

**Comment by crcrpar** [comment]
@kit1980 is there anything I can help you?

**Comment by kit1980** [comment]
@crcrpar I see this ClampFunctor-related error (warning treated as an error) now on Windows builds:

D:\full-fbsource\xplat\caffe2\aten\src\ATen\native\cuda\MultiTensorApply.cuh(103): warning: parameter "args" was declared but never referenced
          detected during:
            instantiation of "void at::native::<unnamed>::multi_tensor_apply_kernel(T, U, ArgTypes...) [with T=at::native::<unnamed>::TensorListMetadata<1>, U=at::native::ClampFunctor<c10::impl::ScalarTypeToCPPTypeT<c10::ScalarType::Double>, 1, 1, 0>, ArgTypes=<double, double, at::native::detail::ClampLimits>]" 
(250): here
            instantiation of "void at::native::multi_tensor_apply<depth,T,ArgTypes...>(std::vector<std::vector<at::Tensor, std::allocator<at::Tensor>>, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor>>>> &, T, ArgTypes...) [with depth=1, T=at::native::ClampFunctor<c10::impl::ScalarTypeToCPPTypeT<c10::ScalarType::Double>, 1, 1, 0>, ArgTypes=<double, double, at::native::detail::ClampLimits>]" 
D:\full-fbsource\xplat\caffe2\aten\src\aten\native\cuda\foreachbinaryopscalar.cu(386): here

**Comment by crcrpar** [comment]
@kit1980 could you re-import this pull request?

**Comment by kit1980** [comment]
@crcrpar Re-imported and I'll check it later as internal CI needs time to run.

**Comment by kit1980** [comment]
@crcrpar Still the same exact issue as before, 

> parameter "args" was declared but never referenced

**Comment by kit1980** [comment]
@crcrpar Still the same exact issue :-(

**Comment by janeyx99** [comment]
:(

**Comment by janeyx99** [comment]
@crcrpar if you'd like, feel free to rebase this PR and I'll import internally to see if the error has gone away. It'd be awesome to get this in still.

**Comment by janeyx99** [comment]
@pytorch/pytorch-dev-infra do we yet know why there's a discrepancy between internal and external windows builds? It'd be useful to have parity here for OSS devs landing PRs such as this one.

**Comment by kit1980** [comment]
> do we yet know why there's a discrepancy between internal and external windows builds?

Meta-internal and OSS builds use completely different build systems: buck vs cmake.
There are also several different build flavors internally.
There was an attempt to unify the build systems: that's why we have an OSS buck build and some build-related files are shared between the build systems, but the unification is very incomplete.

**Comment by awgu** [comment]
+1 to this!

I would like this for horizontally fusing an fp8 saturated cast.

**Pull request closed without merging**
