### PR TITLE
[RELAND] Remove patches that circumvent MAGMA bug

### PR DESCRIPTION
**Pull request by vishwakftw**
Changelog:
- The magma implementation of small singular square batch matrices had a bug that resulted in nan values in the LU factorization result. This has been fixed in MAGMA 2.5.2. This PR removes the existing patch that was a temporary workaround for this bug.

Test Plan:
- Existing tests for det and lu should pass

This is a re-submit of #34357

### CODE REVIEW

**Review by seemethere — CHANGES_REQUESTED** [review]
It might be better to just cherry pick your change onto the current `viable/strict`

The way I would do this is by:

```bash
git checkout upstream/viable/strict
git cherry-pick 10f2b5b
git branch -D remove-hotfix-lu-det # remove old branch
git checkout -b remove-hotfix-lu-det # checkout current commit as old PR branch
git push -uf origin remove-hotfix-lu-det # push cherry picked branch
```

This will get rid of all the merge commits that are currently in your branch.

**Comment by vishwakftw** [comment]
@seemethere seems like there are no PR specific failures on CI.

**Comment by seemethere** [comment]
@vishwakftw sorry for not giving this a lot of attention, would you be able to rebase onto `viable/strict` and try to run tests again?

Now that the 1.5.0 release is over I have more time to review PRs

**Comment by vishwakftw** [comment]
@seemethere I've rebased, sorry about the delay.

**Review by seemethere — APPROVED** [review]

**Pull request closed without merging**
