### PR TITLE
new_qtensor support privateuseone allocator.

### PR DESCRIPTION
**Pull request by huihoaan**
I want to create a quant tensor through `PerTensorAffineQuantizer`. But I found that it will throw error because of the lake of judgment for PrivateUse1.

### CODE REVIEW

**Comment by huihoaan** [comment]
@supriyar Could you take a look at this pr?

**Comment by supriyar** [comment]
can you add relevant testing to accompany this code change? cc @jerryzh168  to help review

**Comment by huihoaan** [comment]
> can you add relevant testing to accompany this code change? cc @jerryzh168 to help review

I've added a unittest for this case. Because quantize's calculations are complex and are registered elsewhere, I've just written an empty function for `quantize_tensor_per_tensor_affine_stub`.

**Comment by huihoaan** [comment]
@supriyar @jerryzh168  please take a look at this pr.

**Comment by jerryzh168** [comment]
@huihoaan what is use case for this? we are actually moving away from having native quantized tensor in pytorch core going forward

**Comment by huihoaan** [comment]
> @huihoaan what is use case for this? we are actually moving away from having native quantized tensor in pytorch core going forward

Our customer has a strong will to use this interface，the first step is to allow us to create a quantized tenser. So `new_qtensor` need to allow to get `privateuse1 allocator`. @jerryzh168

**Comment by jerryzh168** [comment]
without more information about how this is going to be used I don't know how to review this, I've talked about the plan from our team on these things, I'm not sure how open we are to accept extensions to things that we plan to deprecate from pytorch core side, cc @ezyang @albanD

**Comment by ezyang** [comment]
when it's something innocuous like this I just accept it

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
