### PR TITLE
[export] require Module to be passed to export

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #115222
* __->__ #117528

This PR changes torch.export to require an nn.Module as input, rather than taking an arbitrary callable.

The rationale for this is that we have several invariants the ExportedProgram that are ambiguous if the top-level object being traced is a function:
1. We "guarantee" that every call_function node has an `nn_module_stack` populated.
2. We offer ways to access the state_dict/parameters/buffers of the exported program.

We'd like torch.export to offer strong invariants—the value proposition of export is that you can trade flexibility for stronger guarantees about your model.

An alternative design would be to implicitly convert the top-level function into a module, rather than require that the user provide a module. I think that's reasonable (it's what we did in TorchScript), but in the spirit of being explicit (another design tenet of export) I avoid that here.

Differential Revision: [D52789321](https://our.internmc.facebook.com/intern/diff/D52789321/)

### CODE REVIEW

**Review by thiagocrepaldi — APPROVED** [review]
Nice!

**Review by zhxchen17 — APPROVED** [review]

**Review by avikchaudhuri — APPROVED** [review]

**Review by tugsbayasgalan — APPROVED** [review]

**Comment by qihqi** [comment]
Hi @suo 

I would like to challenge this rationale

> An alternative design would be to implicitly convert the top-level function into a module, rather than require that the user provide a module. I think that's reasonable (it's what we did in TorchScript), but in the spirit of being explicit (another design tenet of export) I avoid that here.

Although I do agree that this is better longer term. But this change currently is BC-breaking. We should put up with a warning message before making this change right away. Implicitly converting to nn.Module for now, with a warning message of later removing this behavior, is a more prudent choice.

**Comment by suo** [comment]
I know it sucks/is annoying, but we don't promise BC for export so that we have flexibility to harden invariants like this. Our warning is here 😛 :
image

**Comment by qihqi** [comment]
haha that's true, fair enough

**Comment by suo** [comment]
sorry about that—hmm…I thought we XLA tests ran in our CI? I would have fixed the upstream had I known about it.

**Comment by JackCaoG** [comment]
lol no worry, after a closer look I think xla test was broken for a different reason which hide the issue caused by this pr. I will follow up.

**Comment by yiliu30** [comment]
Hi @suo, Could you update the docstring and documentation to reflect this change? It can be a bit confusing for newcomers lol

https://github.com/pytorch/pytorch/blob/38d9bb5abcc31ba97927a5399b88afe2cf60bf64/torch/export/__init__.py#L83-L84

**Comment by suo** [comment]
Do you have a link to the actual class handy? Off the top of my head, I would suggest creating a wrapper module like:
```
class Wrapper(torch.nn.Module):
    def __init__(self, sdxl):
        self.sdxl = sdxl
    def forward(self, *args, **kwargs):
        self.sdxl(*args, **kwargs)
```

**Comment by thiagocrepaldi** [comment]
Yeah, that probably work, I was thinking in `torch.export` doing this under the hood to prevent code changes on user side. say

```python
def export(model):

   if isinstance(model, Callable):
      model = wrap_callable_into_model(model):

   ...
```

By the way, this is a repro:

```python
import contextlib
import torch
from diffusers import DiffusionPipeline
from accelerate import init_empty_weights


model_name = "stabilityai/stable-diffusion-xl-base-1.0"
# with init_empty_weights():
# with torch._subclasses.FakeTensorMode() as ctx:
with contextlib.nullcontext() as ctx:
    print("Loading model")
    fake_model = DiffusionPipeline.from_pretrained(model_name, low_cpu_mem_usage=False)

    random_input = torch.randn(1, 4, 256, 256)
    timestep = torch.tensor([1.0])
    encoder_hidden_states = torch.randn(1, 1, 2048)
    added_cond_kwargs = {
        "text_embeds": torch.randn(1, 2560),
        "time_ids": torch.tensor([1]),
    }
    fake_args = (random_input, timestep, encoder_hidden_states, None, None, None, None, added_cond_kwargs)

prompt = "Tell me a joke"
torch.export.export(fake_model, args=(), kwargs={"prompt": prompt})
```

**Comment by playertr** [comment]
FYI, it looks like the [current docs](https://pytorch.org/docs/stable/export.html#torch.export.export:~:text=torch.export.export()%20takes%20an%20arbitrary%20Python%20callable) may not reflect this PR's change to require nn.Module in `export`:

> [torch.export.export()](https://pytorch.org/docs/stable/export.html#torch.export.export) takes an arbitrary Python callable (a [torch.nn.Module](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module), a function or a method) and produces a traced graph

**Comment by laithsakka** [comment]
This was landed with out updating the docs 
see 
https://pytorch.org/docs/stable/export.html
probably we need to follow up with that?
cc @angelayi @pianpwk @avikchaudhuri

**Comment by angelayi** [comment]
It should be updated on main already: https://pytorch.org/docs/main/export.html

**Pull request closed without merging**
