### PR TITLE
[Pytorch] Update FuseLinear to map source range information

### PR DESCRIPTION
**Pull request by kimishpatel**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#58492 [Pytorch] Update FuseLinear to map source range information**
* #58300 [Pytorch] Provide API to preserve source range and callstack information during graph rewrite

Summary:
Update graph rewrite to specify how values in replacement pattern should
map to values in original pattern for fuse_linear pass

Test Plan:
python test/test_quantization.py TestQuantizeJitPasses.test_fuse_linear

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D28512464](https://our.internmc.facebook.com/intern/diff/D28512464)

### CODE REVIEW

**Comment by kimishpatel** [comment]
@kimishpatel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28512464).

**Review by jerryzh168 — APPROVED** [review]
lg, please fix lint errors before land

**Comment by kimishpatel** [comment]
@kimishpatel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28512464).

**Comment by kimishpatel** [comment]
@kimishpatel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28512464).

**Comment by kimishpatel** [comment]
@kimishpatel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28512464).

**Pull request closed without merging**
