### PR TITLE
Add `scalarType` to JitType pyi

### PR DESCRIPTION
**Pull request by justinchuby**
Fixes mypy errors when calling `.type().scalarType()` on an `_C.Value` object.

Reference

https://github.com/pytorch/pytorch/blob/28776c45e393ec7d6731a5613f5d79d309036d3a/torch/csrc/jit/python/python_ir.cpp#L891-L896

### CODE REVIEW

**Review by BowenBao — APPROVED** [review]

**Comment by justinchuby** [comment]
@eellison could you help take a look? thanks

**Comment by justinchuby** [comment]
@kit1980 could you help take a look? Thanks!

**Pull request closed without merging**
