### PR TITLE
Fix whenRegisteringAutogradKernelWithCatchAllKernel_thenCanCallAutogradKernel

### PR DESCRIPTION
**Pull request by fffrog**
Both test cases should call catchallkernel

### CODE REVIEW

**Comment by bdhirsh** [comment]
@FFFrog what's the motivation for this change? (is the test failing today?)

**Comment by FFFrog** [comment]
> @FFFrog what's the motivation for this change? (is the test failing today?)

The name and behavior of this test case (`whenRegisteringAutogradKernelWithCatchAllKernel_thenCanCallAutogradKernel`) do not match, it should be `CatchallKernel` instead of `CallAutogradKernel`, which is easy to cause ambiguity (the test result itself has no problems)

**Review by bdhirsh — APPROVED** [review]

**Pull request closed without merging**
