### PR TITLE
Always invoke decomps in fake tensors

### PR DESCRIPTION
**Pull request by eellison**
Use the prims layer_norm to workaround https://github.com/pytorch/pytorch/issues/83362.. Maybe we should be using the prims/decomps over math kernels?

### CODE REVIEW

**Comment by Chillee** [comment]
> Maybe we should be using the prims/decomps over math kernels?

I think this would make sense.

**Comment by eellison** [comment]
The decomps will be used for sym int tracing, so we might as well get coverage now since they will be turned on down the road.

**Comment by ezyang** [comment]
I guess I'm confused why you don't just test if there is a decomposition at the top of `__torch_dispatch__`, and if so, call that directly.

**Comment by eellison** [comment]
> I guess I'm confused why you don't just test if there is a decomposition at the top of __torch_dispatch__, and if so, call that directly.

That doesn't work atm - I think I need re-entrant modes or something along those lines because when I invoke decompositions directly from `__torch_dispatch__` the mode isnt active / called for newly constructed tensors within decompositions.

**Comment by eellison** [comment]
Changed to always using decomps..

**Comment by ezyang** [comment]
reentrant modes is working on master; the incant is:

```
    if func_overload in CURRENT_DECOMPOSITION_TABLE:
        with proxy_mode.restore():
            return CURRENT_DECOMPOSITION_TABLE[func_overload](*args, **kwargs)
            
    # Some of these are not "real" aten ops and will fail if we
    # call _dispatch_has_kernel_for_dispatch_key on them.
    # This list is probably incomplete
    if func_overload not in [torch.ops.aten.size.default]:
        with proxy_mode.restore():
            r = func_overload.decompose(*args, **kwargs)
            if r is not NotImplemented:
                return r

```

**Review by ezyang — APPROVED** [review]
you may also want to reapply CompositeImplicitAutograd as well, when they exist

**Comment by eellison** [comment]
Actually, enabling this more generally gives errors when I run it. I'm going to leave that as a follow up TODO but for now just invoke layer norm.

**Comment by eellison** [comment]
```
        with proxy_mode.restore():
            return CURRENT_DECOMPOSITION_TABLE[func_overload](*args, **kwargs)
```

- I got some variant of "No ancestor" error when trying to add this and running Torchbench models with fake tensors

**Comment by ezyang** [comment]
> I got some variant of "No ancestor" error when trying to add this and running Torchbench models with fake tensors

This means when you created the mode, you should quickly do `with mode: pass`

**Comment by ezyang** [comment]
> Actually, enabling this more generally gives errors when I run it. I'm going to leave that as a follow up TODO but for now just invoke layer norm.

We definitely want this, because lack of reentrant dispatch is leading to bypassing Python implementations when we do symint stuff.

**Comment by ezyang** [comment]
I've got the restore() change patched into my WC and I'm working through the failures

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/83496/

**Pull request closed without merging**
