### PR TITLE
Conservative-ish persistent RNN heuristics for compute capability 8.0+

### PR DESCRIPTION
**Pull request by mcarilli**
Based on https://github.com/pytorch/pytorch/pull/43165#issuecomment-697033663 and tests by Vasily Volkov ([persistentRNN-speedup.xlsx](https://github.com/pytorch/pytorch/files/5298001/persistentRNN-speedup.xlsx)).  See comments in code.

### CODE REVIEW

**Comment by ptrblck** [comment]
Changes looks alright.
We are additionally using this check in lines590++:
```python
              #if CUDNN_VERSION >= 7600
                if(rnn.hidden_size == 1024
                   && (bsize == 32 || bsize == 64 || bsize == 128 
                       || (bsize == 256 && tensors.seq_length > 18)
                       || (bsize == 192 && tensors.seq_length > 12))) {
                  return CUDNN_RNN_ALGO_PERSIST_STATIC;
                }
              #endif // CUDNN_VERSION >= 7600
```
for CUDNN>=7.6.

The new Ampere heuristic is not done yet and Vasily has to recheck it, as there seem to be bad interactions.

**Comment by mcarilli** [comment]
> The new Ampere heuristic is not done yet and Vasily has to recheck it, as there seem to be bad interactions.

Tagging as WIP until we sort out...whatever this is.

**Comment by xwang233** [comment]
I have done a quick profiling. The results and the diff I used are at https://gist.github.com/xwang233/8d5ecfcd53dabc6966e46d5cf6306d86. 

Basically, I just changed the Volta-only heuristic to Volta+Ampere, and kept everything else the same. I also tested the extra heuristic mentioned by @ptrblck . It overall looks perfect, except that `bsize=192` and `bsize=256` are regressed. 

I think it would be nice that we have this Ampere heuristic enabled in the next release. I assume there will be many people using RTX 3080 in the next few months.

**Comment by ngimel** [comment]
Looks like 20,256 is miserable on Ampere and is about the same on Volta, so probably disable persistent for batch 256 altogether? Otherwise looks good.

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
