### PR TITLE
Allow returned tensor impls in fallback

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #80545
* #80544

Previously, we had disallowed any reused storages in fallback kernels because the correct aliasing relationships weren't set up correctly. However, we can support the case of a reused TensorImpl by just returning the input FakeTensor it corresponds to. Additionally, we have `inplace_view` as a tag which will prevent us from running fallback kernels for kernels that mutate metadata. (thanks @ezyang who originally suggested I do this).

Fix for https://github.com/pytorch/torchdynamo/issues/467

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
lol this test

**Comment by suo** [comment]
oh oops, @malfet already did

**Comment by malfet** [comment]
> oh oops, @malfet already did

I won the race this time :P

**Pull request closed without merging**
