### PR TITLE
disable mypystrict on some files under  /benchmarks/** and address other lint errors.

### PR DESCRIPTION
**Pull request by laithsakka**
title.
Those are blocking https://github.com/pytorch/pytorch/pull/133109 from landing.
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #133109

### CODE REVIEW

**Review by aorenste — CHANGES_REQUESTED** [review]
I don't like the idea of disabling mypy on any of the code. Let's chat to see if we can come up with an alternative.

**Review by aorenste — COMMENTED** [review]
Are these in the wrong order (#133109 and #131475)? I would expect you to need these to land first. Also I think the PR number in the subject is wrong (it says it's blocking itself).

**Review by aorenste — APPROVED** [review]

**Comment by laithsakka** [comment]
I will rebase before landing i put it initially on top to make sure it fix the issues

**Comment by laithsakka** [comment]
rebase on mian

**Comment by laithsakka** [comment]
ahh looks like i need to land this as part of my diff actually because expected order of imports actually change with my diff

**Comment by laithsakka** [comment]
landed as part of differen tdiff

**Pull request closed without merging**
