### PR TITLE
add cudnn.cu

### PR DESCRIPTION
**Pull request by ArutyunovG**

### CODE REVIEW

**Review by bddppq — DISMISSED** [review]
oops good catch!

**Comment by bddppq** [comment]
Actually, we need to skip this line as well (if USE_CUDNN is true) https://github.com/pytorch/pytorch/blob/ac09f93a8f30b44e298aed13e5d7dae8be4319b2/caffe2/operators/CMakeLists.txt#L20

**Comment by ArutyunovG** [comment]
We'll have them twice then?

**Comment by ArutyunovG** [comment]
@bddppq As far as I see, they are added twice and excluded once now. Before the change, they were added once and excluded once and not available in build.

**Comment by bddppq** [comment]
@ArutyunovG Oh I didn't realize it's "adding twice and exclude once".

**Review by bddppq — APPROVED** [review]

**Pull request closed without merging**
