### PR TITLE
Add Bfloat16 support to CrossKernel.cu

### LINKED ISSUE #108940: cross_cuda is not implemented for BFloat16
### 🐛 Describe the bug

As the title reports, the kernel for `torch.cross` is not exposed for `BFloat16` on cuda, but is available on CPU. Steps for reproduction:

```
import torch

x = torch.rand(100, 3, dtype=torch.bfloat16)
y = torch.rand(100, 3, dtype=torch.bfloat16)

torch.cross(x, y, dim=-1)  # Works

torch.cross(x.cuda(), y.cuda(), dim=-1)  # Fails
```

In the comments, I have a one-line proposed fix PR, just making `BFloat16` available at dispatch.

### Versions

[pip3] torch-sparse==0.6.17+pt20cu117
[pip3] torch-spline-conv==1.2.2+pt20cu117
[pip3] torchaudio==2.0.1+cu118
[pip3] torchvision==0.15.1+cu118
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] mkl                       2023.1.0         h213fc3f_46343
[conda] mkl-service               2.4.0            py39h5eee18b_1
[conda] mkl_fft                   1.3.6            py39h417a72b_1
[conda] mkl_random                1.2.2            py39h417a72b_1
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] numpy-base                1.25.2           py39hb5e798b_0
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     2.0.0+cu118              pypi_0    pypi
[conda] torch-cluster             1.6.1+pt20cu117          pypi_0    pypi
[conda] torch-geometric           2.3.1                    pypi_0    pypi
[conda] torch-radon               1.0.0                    pypi_0    pypi
[conda] torch-scatter             2.1.1+pt20cu117          pypi_0    pypi
[conda] torch-sparse              0.6.17+pt20cu117          pypi_0    pypi
[conda] torch-spline-conv         1.2.2+pt20cu117          pypi_0    pypi
[conda] torchaudio                2.0.1+cu118              pypi_0    pypi
[conda] torchvision               0.15.1+cu118             pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @ptrblck

### PR DESCRIPTION
**Pull request by jamaliki**
Fixes #108940

### CODE REVIEW

**Review by mikaylagawarecki — COMMENTED** [review]
Thanks!

**Review by mikaylagawarecki — APPROVED** [review]

**Comment by jamaliki** [comment]
Hey @mikaylagawarecki , there appear to be some test failures that don't seem to be relevant to this change. Do you know what is the issue here?

**Pull request closed without merging**
