### PR TITLE
RFC Allow fake tensors to be backed by not meta tensor

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #82362

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
@eellison I'm curious what you think about this. The basic idea is that sometimes we can't represent a tensor via meta; similar to how we allow cpu/cuda fallback for operations, what if we allow fallback to non-meta representation when we can't represent the tensor in meta? Alternately, we could ensure we support meta for all tensor types but there is a pretty long tail that we will need to hit.

**Comment by ezyang** [comment]
tests are known failing, I'll figure it out if we agree to do this

**Comment by eellison** [comment]
Hmmmm, so I guess this is for SparseTensors ? The main reasons to use fake tensor instead of real tensors are:

1. Simulate running your model without taking up real memory usage (this is needed to realize AOT Autograd memory savings and train larger models without OOMing)
2. Don't mutate real tensors when doing analysis 
3. Safety with not tracing dynamic shape operators
4. (forthcoming) tracing dynamic shape computation and setting up guards
5. (minor) do analysis faster without running kernels

For 1. - could we store the metadata of these tensors and re-materialize them whenever we're running kernels ? This might require a has-a relationship. Separately, if it weren't for (4/5), this seems like something we could have done much more generally and saved us a lot of work lol. 

For 4. - I don't see really see a path forward here, but maybe for more esoteric use cases starting with static shapes makes sense.


CC @Chillee thoughts ?

**Comment by ezyang** [comment]
The motivation is more like a gradual onboarding path. Similar to cpu fallback, where things work (but less well) even when you don't have a meta kernel, a fake tensor backed by a real tensor represents when we have a tensor that we don't know how to convert to meta. I don't think it makes sense to define yet another metadata format; defining that format is about as much work as making the meta tensor work. But it would be nice to have an easy way to just not get any meta tensor benefits, but have functional correctness, and that's what this PR does.

Otherwise, we have "use fake tensors" or "don't use fake tensors at all" and if you run into one of the cases where support doesn't work, you have no choice but to turn fake tensors off globally.

**Comment by ezyang** [comment]
@eellison and I discussed this and we decided not to do it, because fake tensors are likely to get retained very long, so the downside of having them not be memory efficient is very bad

**Pull request closed without merging**
