### PR TITLE
[AOTInductor] Support many outputs aliasing the same tensor

### PR DESCRIPTION
**Pull request by ColinPeppler**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #122846

fixes https://github.com/pytorch/pytorch/issues/122826

# Problem
When the model returns multiple outputs which alias the same tensor, we get a SEGFAULT. Because we try to release the same buffer twice.
```
def forward(x):
  x_out = x + 1
  contig = x_out.contiguous()   # alias of same tensor as x_out
  return x_out, contig

run_impl() {
  output_handles[0] = buf0.release();
  output_handles[1] = buf0.release();   # SEGFAULT
}

# if we try to workaround this by assign aliases without creating a new tensor, 
# then, we'll get a double free error during handle clean-up.
output_handles[1] = output_handles[0];    # assign without creating a new tensor
...
alloc_tensors_by_stealing_from_handles(){
  aoti_torch_delete_tensor_object(handles[0]);
  aoti_torch_delete_tensor_object(handles[1]);   # Double free
}
```

# Solution
~~Instead, we use the first `output_handle` that shares the same tensor and alias it.~~
```
output_handles[0] = buf0.release();
aoti_torch_alias_tensor(output_handles[0], &output_handles[1]);  # No SEGFAULT & No double free!
```

A simpler approach is to figure out which handles are duplicate. Then we simply copy all duplicate except the last one. The last one will use `std::move` and free the tensor owned by the model instance.
```
output_handles[0] = buf0.release();
output_handles[1] = output_handles[0];
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @amjames @desertfire @chauhang

Differential Revision: [D55455344](https://our.internmc.facebook.com/intern/diff/D55455344)

### CODE REVIEW

**Comment by ColinPeppler** [comment]
@ColinPeppler has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D55455344).

**Review by desertfire — DISMISSED** [review]
This is likely over-engineered. We can first scan all the outputs, and if there are duplicates, we only generate free for that last appearance.

BTW, you will need to remove some existing skips, e.g. https://github.com/pytorch/pytorch/blob/12116aee6852df2b040255b8fcc7deb52b897792/test/inductor/test_aot_inductor.py#L2308

**Comment by ColinPeppler** [comment]
@desertfire yeah the simpler approach seems to work for my case :)

but CPU needs a revisit since output handles are created in thread local branch.

**Comment by ColinPeppler** [comment]
@ColinPeppler has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D55455344).

**Review by ColinPeppler — COMMENTED** [review]
switched approach from calling `torch::ops::call::alias` to running a pass to figure out which handles are duplicate and handling them accordingly

**Review by chenyang78 — APPROVED** [review]
Please fix the linting issue. Otherwise, LGTM. Thanks!

**Review by desertfire — APPROVED** [review]

**Review by jingsh — APPROVED** [review]
lgtm

thanks for fixing this!

**Pull request closed without merging**
