### PR TITLE
Add CI builds for TBB and native parallel builds

### PR DESCRIPTION
**Pull request by ilia-cher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#27357 Add CI builds**

Summary:
Add extra CI builds for TBB and native builds

Test Plan:
check CI

Differential Revision: [D17757197](https://our.internmc.facebook.com/intern/diff/D17757197)

### CODE REVIEW

**Comment by ilia-cher** [comment]
This is to avoid build breakages like https://github.com/pytorch/pytorch/issues/26721

**Review by suo — COMMENTED** [review]
Do these need to be run on every PR? Every build we add to the PR-time runs imposes a cost on developer velocity. Could these be run on master only?

**Review by ezyang — APPROVED** [review]
Suggestion: Run these builds on master only, not all PRs. Most PRs are pretty unlikely to break these alternate configs. You can keep them as XImportant configs so that it's easy to trigger them with `[test all]` or `[test parallel]`

**Comment by ilia-cher** [comment]
@suo do you suggest this is less important than, e,g. namedtensor builds?
I think we need to run this in CI, yes, this is important functionality that we don't want to break

**Comment by suo** [comment]
@ilia-cher We weigh master vs. PR-time builds as a balance between how likely all PRs across the project are to break it vs. importance in functionality. Honestly, I may have argued against the inclusion of NamedTensor builds at the time too 😛.

As @ezyang says, it is unlikely that most PRs will break the functionality being tested here, but it will cause potentially extra time waiting + the possibility of flakiness. I think a decent compromise is what he suggested, where you can manually run the tests by including a special command in your PR description.

**Comment by ilia-cher** [comment]
@suo TBB build was broken.. I think at least twice in the last few months

**Comment by ilia-cher** [comment]
In addition, there're external users who specifically rely on these features and these features are not compiled by default.

I can decrease number of builds to alleviate concerns about build time.

**Comment by suo** [comment]
Let's find some time to chat after the devcon about this. I appreciate the desire to get this tested, but like I said, I'd like to balance this against the overall developer experience on the project. Typically for other non-default configurations we are content with testing them continuously on master and having the OSS CI oncall revert diffs that break them, rather than testing them against on every PR. 

The standard for putting a job in PR time should be: "if this job is failing, does it block the majority of other developers of PyTorch?". In practice, this is not super well-enforced, but we should trying to decrease the number of jobs run on PRs, not increase.

**Comment by ilia-cher** [comment]
If oncalls are doing their job reverting diffs then I'm okay :)

**Comment by ezyang** [comment]
cc @zou3519 re namedtensor builds, we can delete them now right?

**Comment by zou3519** [comment]
We can't delete the named tensor builds yet; named tensor tests aren't enabled on the other CI. Once they're enabled on every CI we can delete the named tensor builds

**Comment by ilia-cher** [comment]
Updated

**Comment by suo** [comment]
Unfortunately, the newly-added CI builds are failing on master. I am reverting.

**Comment by ilia-cher** [comment]
Resending https://github.com/pytorch/pytorch/pull/27925

**Comment by ilia-cher** [comment]
Ok, apparently someone managed to break TBB build while I was landing this PR..

**Comment by gchanan** [comment]
the title of this PR isn't clear at all; the summary is fine, that should be in the title.

**Comment by ilia-cher** [comment]
> the title of this PR isn't clear at all; the summary is fine, that should be in the title.

@gchanan, updated the title of https://github.com/pytorch/pytorch/pull/27925

**Comment by zou3519** [comment]
@ilia-cher could you also update the commit message in that pull request? The commit message is different and most people will be reading the commit title.

**Pull request closed without merging**
