### PR TITLE
migrating deprecated calls without abc module for containers

### PR DESCRIPTION
**Pull request by jeffreyksmithjr**
Implementing #10540.

### CODE REVIEW

**Comment by apaszke** [comment]
The reason why we used those is that `.abc` modules are unavailable in Python 2. We should probably add `Iterable`, `Mapping` and whatever else we use to `torch/_six.py`

**Review by ssnl — APPROVED** [review]
LGTM! Thanks!

**Comment by jeffreyksmithjr** [comment]
The Circle tests all flaked (but I think that's a more global issue). The ROCM tests failed, which is also a known issue.

With @SsnL 's LGTM do we call this mergeable or are we going to try to get any of those failed builds to pass?

**Review by apaszke — APPROVED** [review]

**Comment by apaszke** [comment]
@jeffreyksmithjr one of the builds has been broken for at least a day, another one has timed out, but it's unlikely that it failed. CircleCI is experimental, so you can ignore any failures for now. Go ahead and merge this

**Comment by apaszke** [comment]
(Although it might be good to get a review of the C2 bits from someone working on C2)

**Comment by jeffreyksmithjr** [comment]
Makes sense. There is some tiny amount of Caffe2 impact.

Could any Caffe2 experts review this PR?

**Review by Yangqing — APPROVED** [review]
Looks great - are we planning to unify _six and six?

**Comment by jeffreyksmithjr** [comment]
Paraphrasing what @apaszke told me, the reason for `_six` was to not pick up the whole dependency on `six` as a runtime dependency. 

Clearly, the current approach does create a bit of obvious redundancy, though.

**Pull request closed without merging**
