### PR TITLE
[DeviceMesh][Test] Add 3d unit test for `get_local_rank()`

### PR DESCRIPTION
**Pull request by wz337**
Fixes #ISSUE_NUMBER

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @tianyu-l @wconstab @yf225 @chauhang @d4l3k

### CODE REVIEW

**Review by xunnanxu — APPROVED** [review]

**Review by fegin — APPROVED** [review]

**Review by XilunWu — APPROVED** [review]

**Comment by malfet** [comment]
See https://github.com/pytorch/pytorch/actions/runs/8728471591/job/23948923385 not sure why it was not caught by PR CI

**Pull request closed without merging**
