### PR TITLE
faketensor: prevent deepcopy from cloning FakeTensorMode

### PR DESCRIPTION
**Pull request by bdhirsh**
fixes https://github.com/pytorch/pytorch/issues/104465

A more detailed repro is here, which uses `nn.TransformerLayer` (this breaks with AOTAutograd today, due to the presence of multiple FakeTensorMode objects lying around) https://github.com/pytorch/pytorch/issues/103505#issuecomment-1614817132

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #104793
* __->__ #104476

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
If you want to land this as is I will not complain too much, but here is an alternate possible implementation: modify FakeTensor __deepcopy__ to avoid recursing into fake mode. The benefit is that if someone directly tries to deepcopy a fake tensor mode, they will get the logical behavior (actually getting a copy).

**Review by eellison — COMMENTED** [review]
I'm also a little bit worried about not copying FakeTensorMode, and hard to detect bugs that might pop up. An alternative to get the same behavior today is with FakeCopyMode:

```
import torch
from torch._subclasses.fake_tensor import FakeTensorMode
import copy

with FakeTensorMode() as m:
    lin1 = torch.nn.Linear(2, 2)

with torch._subclasses.fake_tensor.FakeCopyMode(m):
    lin2 = copy.deepcopy(lin1)
    print(lin1.weight.fake_mode)
    print(lin1.bias.fake_mode)
    # all same address
    print(lin2.weight.fake_mode)
    print(lin2.bias.fake_mode)
```

This isn't exactly the same as this PR, because it will also copy over eager tensors to fake tensors in the copy. But you could add an arg to the FakeCopyMode ctor to only copy over fake tensors.

**Comment by bdhirsh** [comment]
hmm @eellison that would mean that anyone who uses `deepcopy()` inside of code that they want to `torch.compile` would need to explicitly run it under something like `FakeCopyMode(torch._guards.detect_fake_mode())`, right?

It feels like there's a risk of confusing behavior either way:

(1) we make `deepcopy()` work by default (via Ed' suggestion, so FakeTensor deepcopy doesn't clone the mode). Downside: confusing behavior if someone tries to deepcopy a fake tensor, and actually expects to get two distinct FakeTensorModes.

(2) we require `deepcopy()` to be used with some other API like `FakeCopyMode()`. Downside: anyone using `deepcopy()` in their user code will hit confusing errors about multiple FakeTensorModes floating around, unless they know to use the API.

The main reason I thought (1) would be a bit more acceptable is that I don't know if any use cases today where someone actually wants to have two FakeTensorModes floating around (if anything, I think we've experienced multiple bugs in the last year due to accidentally having multiple fake modes floating around). Does that sound right to you?

**Comment by ezyang** [comment]
If we want some deepcopy alternative that has the "right" semantics this is fine by me. The CPython standard library deepcopy implementation is quite simple and would be easy to reproduce. But I also think that not copying fake mode when copying fake tensor has relatively few failure modes, since it is ALREADY the case that deepcopy doesn't guarantee you everything gets copied (in fact, the Python documentation explicitly talks about how you would avoid deepcopying in some cases lol.) So the semantics of deepcopy aren't very well defined and I don't mind jettisoning consistency for usefulness.

**Comment by eellison** [comment]
land ?

**Comment by bdhirsh** [comment]
Just got back from PTO - I'll try to land this week. From the feedback above, I'm going to at least take a stab at trying to move this logic into `FakeTensor.__deepcopy__` first.

**Pull request closed without merging**
