### PR TITLE
adding symbolic link to get CI to run tests where cmake is not run on CI node

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #95155 which breaks CI and no nvfuser python tests are run on CI nodes.

Thanks to @davidberard98 for noticing this.

### CODE REVIEW

**Comment by davidberard98** [comment]
(and thanks @clee2000 who sent it to me :) )

**Comment by jjsjann123** [comment]
err.. no it's still not running those tests. So looks like the soft link doesn't work neither. I guess I'm ok with leaving the old tests in the folder as-is. I'll just copy tests back in our internal nightly CI.

```
2023-02-25T02:48:32.0802514Z Running test_jit_cuda_fuser ... [2023-02-25 02:48:31.991188]
2023-02-25T02:48:32.0803156Z Executing ['/opt/conda/envs/py_3.10/bin/python', '-bb', 'test_jit_cuda_fuser.py', '-v', '--import-slow-tests', '--import-disabled-tests'] ... [2023-02-25 02:48:31.991450]
2023-02-25T02:48:37.3499360Z 
2023-02-25T02:48:37.3500031Z Expand the folded group to see the log file of test_jit_cuda_fuser
2023-02-25T02:48:37.3501697Z ##[group]PRINTING LOG FILE of test_jit_cuda_fuser (/var/lib/jenkins/workspace/test/test-reports/test_jit_cuda_fuser_ycnl55tm.log)
2023-02-25T02:48:37.3502029Z 
2023-02-25T02:48:37.3502133Z Running tests...
2023-02-25T02:48:37.3502672Z ----------------------------------------------------------------------
2023-02-25T02:48:37.3502932Z 
2023-02-25T02:48:37.3503176Z ----------------------------------------------------------------------
2023-02-25T02:48:37.3503682Z Ran 0 tests in 0.000s
2023-02-25T02:48:37.3503947Z 
2023-02-25T02:48:37.3504048Z OK
2023-02-25T02:48:37.3504180Z 
2023-02-25T02:48:37.3504302Z Generating XML reports...
2023-02-25T02:48:37.3504763Z Test results will be stored in test-reports/python-unittest/test_jit_cuda_fuser
2023-02-25T02:48:37.3505018Z 
2023-02-25T02:48:37.3505323Z ##[endgroup]
2023-02-25T02:48:37.3505869Z FINISHED PRINTING LOG FILE of test_jit_cuda_fuser (/var/lib/jenkins/workspace/test/test-reports/test_jit_cuda_fuser_ycnl55tm.log)
```

**Comment by jjsjann123** [comment]
But we would want to figure out how to properly update this in the long run. Especially after we switch to submodule, we don't want to have duplicated tests in different repo.

**Comment by jjsjann123** [comment]
ah... it's finally running here: https://github.com/pytorch/pytorch/actions/runs/4296986481/jobs/7489806473

**Review by davidberard98 — APPROVED** [review]
Awesome, thanks a lot for figuring out how to fix that!!

**Comment by jjsjann123** [comment]
> Awesome, thanks a lot for figuring out how to fix that!!

I'm happy to see CI in action again. :crossed_fingers:

**Pull request closed without merging**
