### PR TITLE
Add prepend argument to nn.Module hooks

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #87664
* #87580
* __->__ #87370

cc @ezyang @gchanan

### CODE REVIEW

**Comment by albanD** [comment]
What is the exact use case for which you want this?
This is not very reliable in general as the next preprend hook you add will make your not the first one anymore.

cc @soulitzer related to hook ordering questions we were asking.

**Comment by mrshenli** [comment]
> What is the exact use case for which you want this?

We are working on converting some distributed features to hook-based solutions, so that we won't mess up FQNs as module wrapper did. To maintain the similar behavior as today DDP/FSDP, we plan to split their forward into top and bottom halves and install those as pre and post forward hooks. And the pre hook needs to be called before any existing hooks on the local module. 

> This is not very reliable in general as the next preprend hook you add will make your not the first one anymore.

This should be OK for now, as we expect DDP logic is added after local model preparations.

**Comment by albanD** [comment]
> This should be OK for now, as we expect DDP logic is added after local model preparations.

Sure, but I'm not sure how to convey that to the end user of this flag in the doc :p (btw docs need updating).
Like we don't have a strict guarantee on the order of the backward hooks right now (which we want to figure out with @soulitzer  btw). So I'm not sure what we're going to say here...

**Comment by soulitzer** [comment]
For hooks in general it feels like provide guarantees about ordering is something we'd want to do as long as it doesn't complicate the implementation, so the idea sounds OK.

For this case in particular though, communicating to the user about what "prepend" does can be tricky because hooks registered globally will still execute before those prepend, and I'm not sure we even document that anywhere currently?

**Comment by mrshenli** [comment]
Hey @albanD @soulitzer, thanks a lot for the comments! 

> For this case in particular though, communicating to the user about what "prepend" does can be tricky because hooks registered globally will still execute before those prepend, 

Would I be correct that global hooks are mainly for debugging/profiling purposes. Or have we seen cases where program relies on global hooks to produce correct results?

> and I'm not sure we even document that anywhere currently?

Any suggestions on which of the following might be better?

1. Add an underscore (i.e., `_prepend`) to make it private.
2. Add arg docstrings to make it official.

**Comment by mrshenli** [comment]
Screen Shot 2022-10-21 at 7 23 13 PM
Screen Shot 2022-10-21 at 7 24 23 PM
Screen Shot 2022-10-21 at 7 24 47 PM
Screen Shot 2022-10-21 at 7 25 27 PM

**Comment by soulitzer** [comment]
Thanks for the updated documentation, looks great.

> Add arg docstrings to make it official and fully explain the ordering of hooks

To explain the ordering of hooks fully, we may also want to think about the interaction of full_backward_pre_hooks with hooks registered to module outputs (but that might be out of the scope of this PR)
- FWIW the interaction seems to be: pre_hooks registered to the grad_fn of module outputs execute BEFORE prepended full_backward_pre_hooks, and post_hooks registered will execute AFTER.  Not sure if it is problematic/relevant to your use case.

We might want to have some documentation regarding module hooks in general now, but that can be done in a follow up.

**Review by soulitzer — APPROVED** [review]

**Pull request closed without merging**
