### PR TITLE
Analysing time taken by gradgrad checks for Spectral Functions

### PR DESCRIPTION
**Pull request by krshrimali**
**Description:** `SpectralFuncInfo` defines decorator mentioning: "gradgrad is quite slow". This PR re-analyses that statement since things have changed with gradient tests.

**Test times:** https://github.com/pytorch/pytorch/pull/60435#issuecomment-865658177

**Follow-up** of https://github.com/pytorch/pytorch/pull/57802

cc: @mruberry

### CODE REVIEW

**Comment by krshrimali** [comment]
**Note:** Times are in seconds.

| Function Name  | Time Taken (`complex128`) | Time Taken (`float64`) |
| :--- | :---: | :---: |
| `fft.fft` | 0.562 | 0.251 |
| `fft.fftn`  | 0.647 | 0.267 |
| `fft.hfft` | 0.521 | 0.224 |
| `fft.ifft` | 0.579 | 0.260 |
| `fft.ifftn` | 0.659 | 0.270 |
| `fft.ihfft` | - | 0.264 |
| `fft.irfft` | 0.521 | 0.234 |
| `fft.irfftn` | 0.594 | 0.238 |
| `fft.rfft` |  - | 0.234 |
| `fft.rfftn` | - | 0.249 |

**Test Log:** (CI Link: https://app.circleci.com/pipelines/github/pytorch/pytorch/339893/workflows/5b2b5f3f-c2c9-45d8-b325-7a1b7d3b39b4/jobs/14291550)

```
 Jun 22 06:23:13   test_fn_gradgrad_fft_fft_cuda_complex128 (__main__.TestGradientsCUDA) ... ok (0.562s)
 Jun 22 06:23:13   test_fn_gradgrad_fft_fft_cuda_float64 (__main__.TestGradientsCUDA) ... ok (0.251s)
 Jun 22 06:23:14   test_fn_gradgrad_fft_fftn_cuda_complex128 (__main__.TestGradientsCUDA) ... ok (0.647s)
 Jun 22 06:23:14   test_fn_gradgrad_fft_fftn_cuda_float64 (__main__.TestGradientsCUDA) ... ok (0.267s)
 Jun 22 06:23:15   test_fn_gradgrad_fft_hfft_cuda_complex128 (__main__.TestGradientsCUDA) ... ok (0.521s)
 Jun 22 06:23:15   test_fn_gradgrad_fft_hfft_cuda_float64 (__main__.TestGradientsCUDA) ... ok (0.224s)
 Jun 22 06:23:15   test_fn_gradgrad_fft_ifft_cuda_complex128 (__main__.TestGradientsCUDA) ... ok (0.579s)
 Jun 22 06:23:16   test_fn_gradgrad_fft_ifft_cuda_float64 (__main__.TestGradientsCUDA) ... ok (0.260s)
 Jun 22 06:23:16   test_fn_gradgrad_fft_ifftn_cuda_complex128 (__main__.TestGradientsCUDA) ... ok (0.659s)
 Jun 22 06:23:17   test_fn_gradgrad_fft_ifftn_cuda_float64 (__main__.TestGradientsCUDA) ... ok (0.270s)
 Jun 22 06:23:17   test_fn_gradgrad_fft_ihfft_cuda_float64 (__main__.TestGradientsCUDA) ... ok (0.264s)
 Jun 22 06:23:17   test_fn_gradgrad_fft_irfft_cuda_complex128 (__main__.TestGradientsCUDA) ... ok (0.521s)
 Jun 22 06:23:18   test_fn_gradgrad_fft_irfft_cuda_float64 (__main__.TestGradientsCUDA) ... ok (0.234s)
 Jun 22 06:23:18   test_fn_gradgrad_fft_irfftn_cuda_complex128 (__main__.TestGradientsCUDA) ... ok (0.594s)
 Jun 22 06:23:19   test_fn_gradgrad_fft_irfftn_cuda_float64 (__main__.TestGradientsCUDA) ... ok (0.238s)
 Jun 22 06:23:19   test_fn_gradgrad_fft_rfft_cuda_float64 (__main__.TestGradientsCUDA) ... ok (0.234s)
 Jun 22 06:23:19   test_fn_gradgrad_fft_rfftn_cuda_float64 (__main__.TestGradientsCUDA) ... ok (0.249s)
```

Looks like it's reasonable to delete the decorator from `SpectralFuncInfo`, all the tests take < 0.7 seconds on the CI. What do you think? @mruberry

**Comment by mruberry** [comment]
I agree these all seem faster enough that we can run them. @albanD what do you think?

**Comment by albanD** [comment]
Yes looks good! More testing that takes no time is always betterr!!

**Comment by krshrimali** [comment]
Gentle ping @mruberry - please take a look whenever you find time. :)

**Review by mruberry — APPROVED** [review]
Cool, thanks @krshrimali!

**Pull request closed without merging**
