### PR TITLE
update merge failed msg

### PR DESCRIPTION
**Pull request by kshitij12345**
Message seemed a bit incorrect to read
Ref: https://github.com/pytorch/pytorch/pull/82955#issuecomment-1215523319

Before PR:
```
Merge failed due to This PR is too stale; the last push date was more than 3 days ago. Please rebase and try again.
Raised by https://github.com/pytorch/pytorch/actions/runs/2862480424
```

After PR
```
Merge failed
Reason: This PR is too stale; the last push date was more than 3 days ago. Please rebase and try again.
Raised by https://github.com/pytorch/pytorch/actions/runs/2862480424
```

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
this is a good idea! thanks for the PR. linking @zengk95 to ensure this format fits our other potential errors too.

**Comment by zengk95** [comment]
this lgtm. All of our other RuntimeErrors usually have a reason as their message so looks good. May want to update the messaging on those later on as well though since they aren't all super descriptive.

**Comment by kshitij12345** [comment]
@zengk95 @janeyx99 Can you please approve the PR if all is good (Have marked it as ready-for-review). Thanks :)

**Review by janeyx99 — APPROVED** [review]

**Review by ZainRizvi — APPROVED** [review]

**Pull request closed without merging**
