### PR TITLE
[ONNX] Export masked_select and masked_scatter in opset 11

### PR DESCRIPTION
**Pull request by BowenBao**
- masked_select is exported as ONNX::GatherND
- masked_scatter is exported as ONNX::ScatterND

### CODE REVIEW

**Comment by dashesy** [comment]
Related issue [here](https://github.com/pytorch/pytorch/issues/26034). How about masked_fill?

**Comment by BowenBao** [comment]
> Related issue [here](https://github.com/pytorch/pytorch/issues/26034). How about masked_fill?

masked_fill support was added two month ago, PyTorch version >= 1.2 should have it. Do you have a repro of issues with exporting masked_fill?

https://github.com/pytorch/pytorch/blob/c79a13b7b6cd352ae88b14e209c0c42bdaa206d1/torch/onnx/symbolic_opset9.py#L1788

**Comment by dashesy** [comment]
No I actually wanted to use masked_select

**Review by houseroad — CHANGES_REQUESTED** [review]
I would put this on hold until we get a good to test it. (wondering how far we will add it to ort)

Before end to end, how about test_operators?

**Comment by houseroad** [comment]
Oct 09 21:51:50 test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset11::test_avgpool FAILED [ 43%]
Oct 09 21:51:51 test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset11::test_avgpool_1d_ceil FAILED [ 43%]
Oct 09 21:51:51 test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset11::test_avgpool_2d_ceil FAILED [ 43%]
Oct 09 21:51:52 test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset11::test_avgpool_3d_ceil FAILED [ 43%]

**Comment by BowenBao** [comment]
> Oct 09 21:51:50 test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset11::test_avgpool FAILED [ 43%]
> Oct 09 21:51:51 test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset11::test_avgpool_1d_ceil FAILED [ 43%]
> Oct 09 21:51:51 test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset11::test_avgpool_2d_ceil FAILED [ 43%]
> Oct 09 21:51:52 test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset11::test_avgpool_3d_ceil FAILED [ 43%]

Thanks Lu. This is due to that onnx::Pad is updated in opset 11, while the exporter is not updated for that yet. I will create a separate PR bumping ORT CI version.

**Review by houseroad — APPROVED** [review]
Looks good.

**Comment by houseroad** [comment]
rebase to retrigger the ci?

**Pull request closed without merging**
