### PR TITLE
[build] Update gtest and remove the macro guide on gtest from #11321

### PR DESCRIPTION
**Pull request by Yangqing**
Last PR seems to have test failures, re-issuing.

### CODE REVIEW

**Comment by Yangqing** [comment]
Turns out 1.8.1 is having a bunch of errors and 1.8.0 is 2 years ago, so we'll just keep the cmake hack.

**Comment by Yangqing** [comment]
(reopening because 1.8.1 seems to be needed for parallel build for Windows)

**Comment by Yangqing** [comment]
Note: pr/caffe2-py2-cuda9.1-cudnn7-ubuntu16.04-test is manually rerun in https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-cuda9.1-cudnn7-ubuntu16.04-test/10234/ and passes. rocm is known to fail.

**Review by orionr — APPROVED** [review]
Much appreciated!

**Pull request closed without merging**
