### PR TITLE
[indcutor] add one triton config for reduction

### PR DESCRIPTION
**Pull request by shunting314**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #106925

This config found by coordinate descent tuning improves kernel https://gist.github.com/shunting314/189a8ef69f90db9d614a823385147a72 from 
- 10.008ms    5.993GB    598.83GB/s
to
- 6.170ms    5.993GB    971.28GB/s .

It should only affect reduction with hint ReductionHint.DEFAULT or when max autotune is enabled.

(It's funny that before I upgrade my triton version, the improvement is from 9.076ms -> 5.692ms )

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by eellison — COMMENTED** [review]
Any perf run of additional compilation time vs perf benefits ?

**Comment by shunting314** [comment]
yea, [link](https://hud.pytorch.org/benchmark/compilers?startTime=Thu%2C%2003%20Aug%202023%2017%3A40%3A49%20GMT&stopTime=Thu%2C%2010%20Aug%202023%2017%3A40%3A49%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=shunting-add-reduction-config&lCommit=ce336bde8b2603c1eb5586935670868d454beb68&rBranch=main&rCommit=f8817d8ac836204535f81e973e6fddc94ca1859f) .

TBH, I was not expecting noticeable perf win but this shows TB improve from 1.74x -> 1.78x with the price of increased compilation time. Also there are a few model fails due to 'infra_error'. The root cause should be the cv2 BC broken issue that Ed solved.

I'll do the perf run again and provide more accurate numbers.

**Comment by eellison** [comment]
@shunting314 the perf numbers will get pretty distorted by the failures, as you're aware.

**Review by jansel — APPROVED** [review]

**Comment by shunting314** [comment]
Redo the perf run [here](https://hud.pytorch.org/benchmark/compilers?startTime=Fri%2C%2004%20Aug%202023%2017%3A05%3A46%20GMT&stopTime=Fri%2C%2011%20Aug%202023%2017%3A05%3A46%20GMT&granularity=hour&suite=torchbench&mode=training&dtype=amp&lBranch=shunting-add-reduction-config-3&lCommit=7f1a744e59394805770897d84b3b8b96cb18723e&rBranch=main&rCommit=2b560d3c3a9b34cd11fc9ff9e3a0be6a81d47968) . Metrics are overall neutral. More spefically we don't see noticeable compilation time increase.

**Pull request closed without merging**
