### PR TITLE
[PyTorch] Remove device check from a few indexing methods

### PR DESCRIPTION
**Pull request by wenleix**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#58800 [PyTorch] Remove device check from a few indexing methods**

These methods leverages TensorIterator which will handle
(or skip) device check.

Differential Revision: [D28622626](https://our.internmc.facebook.com/intern/diff/D28622626/)

### CODE REVIEW

**Comment by wenleix** [comment]
See discussions in https://github.com/pytorch/vision/pull/3869

**Review by ngimel — APPROVED** [review]

**Comment by datumbox** [comment]
@wenleix I was hoping that after landing this PR in the nightly we would be able to revert some mitigations we had to do on TorchVision that brought indexes to the same device. Today I tried reverting the mitigation but apparently it's still needed. See https://github.com/pytorch/vision/pull/3903 for more info.

**Comment by wenleix** [comment]
@datumbox According to https://github.com/pytorch/vision/pull/3903#issuecomment-848354986, the issue is fixed right? :)

**Comment by datumbox** [comment]
@wenleix Yes indeed! It took an extra date for the change to land on the nightly but then we confirmed it was fixed. Thanks for checking.

**Pull request closed without merging**
