### PR TITLE
Remove conj kernels for real dtypes

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #80374

`conj_physical_stub` is currently implemented for all dtypes despite
it just being a plain copy for real dtypes. So, instead we should
defer to the existing copy kernel in these cases.

On my build for one CUDA architecture, I see a 2.2 MB decrease in
`libtorch_cuda.so` size.

### CODE REVIEW

**Comment by peterbell10** [comment]
@ngimel ping

**Review by ngimel — APPROVED** [review]
Awesome, thanks!

**Comment by atalman** [comment]
Please note this broke the internal build, full error is:
```
2/aten/src/ATen/Dispatch.h:346:3: note: expanded from macro 'AT_DISPATCH_CASE_INTEGRAL_TYPES'
[CONTEXT]   AT_DISPATCH_CASE(at::ScalarType::Char, __VA_ARGS__) \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:83:46: note: expanded from macro 'AT_DISPATCH_CASE'
[CONTEXT]   AT_PRIVATE_CASE_TYPE_USING_HINT(enum_type, scalar_t, __VA_ARGS__)
[CONTEXT]                                              ^
buck-out/gen/ee8c4ff0/fbandroid/apps/aloha/app/ntidemo/ntidemo_comp_xzso_alohadpi_x86_release_debug_keystore_pt_code_gen_lib_template_registration/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp:208:5: error: unused type alias 'scalar_t' [-Werror,-Wunused-local-typedef]
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:460:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES_AND3'
[CONTEXT]   AT_DISPATCH_CASE_ALL_TYPES(__VA_ARGS__)       \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:365:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES'
[CONTEXT]   AT_DISPATCH_CASE_INTEGRAL_TYPES(__VA_ARGS__) \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:347:3: note: expanded from macro 'AT_DISPATCH_CASE_INTEGRAL_TYPES'
[CONTEXT]   AT_DISPATCH_CASE(at::ScalarType::Int, __VA_ARGS__)  \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:83:46: note: expanded from macro 'AT_DISPATCH_CASE'
[CONTEXT]   AT_PRIVATE_CASE_TYPE_USING_HINT(enum_type, scalar_t, __VA_ARGS__)
[CONTEXT]                                              ^
buck-out/gen/ee8c4ff0/fbandroid/apps/aloha/app/ntidemo/ntidemo_comp_xzso_alohadpi_x86_release_debug_keystore_pt_code_gen_lib_template_registration/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp:208:5: error: unused type alias 'scalar_t' [-Werror,-Wunused-local-typedef]
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:460:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES_AND3'
[CONTEXT]   AT_DISPATCH_CASE_ALL_TYPES(__VA_ARGS__)       \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:365:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES'
[CONTEXT]   AT_DISPATCH_CASE_INTEGRAL_TYPES(__VA_ARGS__) \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:348:3: note: expanded from macro 'AT_DISPATCH_CASE_INTEGRAL_TYPES'
[CONTEXT]   AT_DISPATCH_CASE(at::ScalarType::Long, __VA_ARGS__) \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:83:46: note: expanded from macro 'AT_DISPATCH_CASE'
[CONTEXT]   AT_PRIVATE_CASE_TYPE_USING_HINT(enum_type, scalar_t, __VA_ARGS__)
[CONTEXT]                                              ^
buck-out/gen/ee8c4ff0/fbandroid/apps/aloha/app/ntidemo/ntidemo_comp_xzso_alohadpi_x86_release_debug_keystore_pt_code_gen_lib_template_registration/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp:208:5: error: unused type alias 'scalar_t' [-Werror,-Wunused-local-typedef]
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:460:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES_AND3'
[CONTEXT]   AT_DISPATCH_CASE_ALL_TYPES(__VA_ARGS__)       \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:365:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES'
[CONTEXT]   AT_DISPATCH_CASE_INTEGRAL_TYPES(__VA_ARGS__) \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:349:3: note: expanded from macro 'AT_DISPATCH_CASE_INTEGRAL_TYPES'
[CONTEXT]   AT_DISPATCH_CASE(at::ScalarType::Short, __VA_ARGS__)
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:83:46: note: expanded from macro 'AT_DISPATCH_CASE'
[CONTEXT]   AT_PRIVATE_CASE_TYPE_USING_HINT(enum_type, scalar_t, __VA_ARGS__)
[CONTEXT]                                              ^
buck-out/gen/ee8c4ff0/fbandroid/apps/aloha/app/ntidemo/ntidemo_comp_xzso_alohadpi_x86_release_debug_keystore_pt_code_gen_lib_template_registration/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp:208:5: error: unused type alias 'scalar_t' [-Werror,-Wunused-local-typedef]
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:460:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES_AND3'
[CONTEXT]   AT_DISPATCH_CASE_ALL_TYPES(__VA_ARGS__)       \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:366:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES'
[CONTEXT]   AT_DISPATCH_CASE_FLOATING_TYPES(__VA_ARGS__)
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:242:3: note: expanded from macro 'AT_DISPATCH_CASE_FLOATING_TYPES'
[CONTEXT]   AT_DISPATCH_CASE(at::ScalarType::Double, __VA_ARGS__) \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:83:46: note: expanded from macro 'AT_DISPATCH_CASE'
[CONTEXT]   AT_PRIVATE_CASE_TYPE_USING_HINT(enum_type, scalar_t, __VA_ARGS__)
[CONTEXT]                                              ^
buck-out/gen/ee8c4ff0/fbandroid/apps/aloha/app/ntidemo/ntidemo_comp_xzso_alohadpi_x86_release_debug_keystore_pt_code_gen_lib_template_registration/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp:208:5: error: unused type alias 'scalar_t' [-Werror,-Wunused-local-typedef]
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:460:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES_AND3'
[CONTEXT]   AT_DISPATCH_CASE_ALL_TYPES(__VA_ARGS__)       \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:366:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES'
[CONTEXT]   AT_DISPATCH_CASE_FLOATING_TYPES(__VA_ARGS__)
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:243:3: note: expanded from macro 'AT_DISPATCH_CASE_FLOATING_TYPES'
[CONTEXT]   AT_DISPATCH_CASE(at::ScalarType::Float, __VA_ARGS__)
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:83:46: note: expanded from macro 'AT_DISPATCH_CASE'
[CONTEXT]   AT_PRIVATE_CASE_TYPE_USING_HINT(enum_type, scalar_t, __VA_ARGS__)
[CONTEXT]                                              ^
buck-out/gen/ee8c4ff0/fbandroid/apps/aloha/app/ntidemo/ntidemo_comp_xzso_alohadpi_x86_release_debug_keystore_pt_code_gen_lib_template_registration/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp:208:5: error: unused type alias 'scalar_t' [-Werror,-Wunused-local-typedef]
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:461:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES_AND3'
[CONTEXT]   AT_DISPATCH_CASE(SCALARTYPE1, __VA_ARGS__)    \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:83:46: note: expanded from macro 'AT_DISPATCH_CASE'
[CONTEXT]   AT_PRIVATE_CASE_TYPE_USING_HINT(enum_type, scalar_t, __VA_ARGS__)
[CONTEXT]                                              ^
buck-out/gen/ee8c4ff0/fbandroid/apps/aloha/app/ntidemo/ntidemo_comp_xzso_alohadpi_x86_release_debug_keystore_pt_code_gen_lib_template_registration/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp:208:5: error: unused type alias 'scalar_t' [-Werror,-Wunused-local-typedef]
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:462:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES_AND3'
[CONTEXT]   AT_DISPATCH_CASE(SCALARTYPE2, __VA_ARGS__)    \
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:83:46: note: expanded from macro 'AT_DISPATCH_CASE'
[CONTEXT]   AT_PRIVATE_CASE_TYPE_USING_HINT(enum_type, scalar_t, __VA_ARGS__)
[CONTEXT]                                              ^
buck-out/gen/ee8c4ff0/fbandroid/apps/aloha/app/ntidemo/ntidemo_comp_xzso_alohadpi_x86_release_debug_keystore_pt_code_gen_lib_template_registration/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp:208:5: error: unused type alias 'scalar_t' [-Werror,-Wunused-local-typedef]
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:463:3: note: expanded from macro 'AT_DISPATCH_CASE_ALL_TYPES_AND3'
[CONTEXT]   AT_DISPATCH_CASE(SCALARTYPE3, __VA_ARGS__)
[CONTEXT]   ^
[CONTEXT] xplat/caffe2/aten/src/ATen/Dispatch.h:83:46: note: expanded from macro 'AT_DISPATCH_CASE'
[CONTEXT]   AT_PRIVATE_CASE_TYPE_USING_HINT(enum_type, scalar_t, __VA_ARGS__)
[CONTEXT]                                              ^
[CONTEXT] 10 errors generated.
[CONTEXT]     When running <c++ preprocess_and_compile>.
[CONTEXT]     When building rule //fbandroid/apps/aloha/app/ntidemo:ntidemo_comp_xzso_alohadpi_x86_release_debug_keystore_pt_code_gen_libAndroid#android-x86,compile-pic-UnaryOpsKernel.cpp.oc1b8d32e (//tools/build_defs/config/platform/android:portal)..
[CONTEXT] Not all rules succeeded.
```

**Comment by peterbell10** [comment]
@atalman ping

**Review by atalman — APPROVED** [review]
LGTM

**Pull request closed without merging**
