### PR TITLE
compile time benchmarks for AOTDispatcher (partitioner)

### PR DESCRIPTION
**Pull request by bdhirsh**
compile time benchmark for the min cut partitioner. I'm hoping that this is a reasonable benchmark because:

(1) it consists of a single input + many weights that are used sequentially
(2) contains a mix of recompute vs non-recomputed ops (matmul + sin)
(3) it is relatively simple

from running locally:
```
collecting compile time instruction count for aotdispatcher_partitioner_cpu
compile time instruction count for iteration 0 is 21764219181
compile time instruction count for iteration 1 is 12475020009
compile time instruction count for iteration 2 is 12463710140
compile time instruction count for iteration 3 is 12455676489
compile time instruction count for iteration 4 is 12451344330
```

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #136670
* __->__ #136760
* #136759

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
@laithsakka Now that we're getting a lot of benchmarks, I kind of feel the boilerplate is too much. Specifically, I don't think we should have to write so much code in `_prepare` nor in `main`.

**Comment by laithsakka** [comment]
> @laithsakka Now that we're getting a lot of benchmarks, I kind of feel the boilerplate is too much. Specifically, I don't think we should have to write so much code in `_prepare` nor in `main`.

we can probably move all the compile time benchmarks to a single program

**Pull request closed without merging**
