### PR TITLE
Bump up the producer version in ONNX exporter

### PR DESCRIPTION
**Pull request by houseroad**

### CODE REVIEW

**Comment by spandantiwari** [comment]
Great! Looks good.

**Review by spandantiwari — APPROVED** [review]
Looks good.

**Review by zrphercule — APPROVED** [review]
Dont know we are still using version 0.4....
Great work!

**Comment by spandantiwari** [comment]
Closing issue https://github.com/pytorch/pytorch/pull/17410 since this is approved.

**Pull request closed without merging**
