### PR TITLE
Removed whitelist reference from torch/quantization/quantize.py, torch/quantization/_numeric_suite.py, torch/quantization/default_mappings.py

### LINKED ISSUE #41762: Replace blacklist/whitelist in torch/quantization/_numeric_suite.py
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `torch/quantization/_numeric_suite.py`. See issue #41443 for more information.

### LINKED ISSUE #41763: Replace blacklist/whitelist in torch/quantization/default_mappings.py
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `torch/quantization/default_mappings.py`. See issue #41443 for more information.

### LINKED ISSUE #41764: Replace blacklist/whitelist in torch/quantization/quantize.py
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `torch/quantization/quantize.py`. See issue #41443 for more information.

### PR DESCRIPTION
**Pull request by casillano**
Fixes #41764. Fixes #41763. Fixes #41762. 

Removed whitelist references.

### CODE REVIEW

**Comment by SplitInfinity** [comment]
Ping @z-a-f

**Comment by SplitInfinity** [comment]
Ping @z-a-f 

Also @casillano please rebase and fix the conflicting files.

**Comment by casillano** [comment]
I have rebased and fixed conflicts

**Review by SplitInfinity — CHANGES_REQUESTED** [review]
It seems that there are some CI test errors, some of which are directly related to your changes. Please examine them and update the PR as needed.

**Comment by z-a-f** [comment]
It's LGTM -- will leave to @SplitInfinity for landing. @casillano, although it looks OK to me, please, search in the codebase where the variables are changed and replace them there as well. That should take care of the failing tests. Thank you!

**Pull request closed without merging**
