### PR TITLE
Added FPGA DispatchKey, DeviceType, Backend

### PR DESCRIPTION
**Pull request by dylanbespalko**
@ezyang,

I have added the changes to DispatchKey, DeviceType, Backend to support the out-of-tree FPGA.

cc. @tataetae

### CODE REVIEW

**Comment by ezyang** [comment]
Remind me again why we're going with the FPGA naming here as opposed to OpenCL?

**Comment by dylanbespalko** [comment]
@ezyang,

Sorry for the confusion. The problem is OpenCL doesn't have an equivalent of `cudaStream` which was the basis for your `c10::Stream` class. Fortunately, Xilinx has implemented a Xilinx specific OpenCL extension documented [here](https://github.com/Xilinx/XRT/blob/48fb1ae22a50b002906dfad7ffecd8c95166292d/src/runtime_src/doc/toc/streaming_data_support.rst).

This `clStream` class allows me to assign a tensor to a **device** instead of a **kernel** so that I do not transfer data between the CPU and the FPGA every time I call a kernel.

P.S. The `clStream` class is very new and is not supported on many Xilinx FPGAs (which is a problem). I might try to implement this myself (using only OpenCL commands). Right now, I don't know enough about it.

**Comment by ezyang** [comment]
@dylanbespalko it might be a little premature to be worrying about streams at this point. It is always sound to just no-op all stream commands (running everything on the "default" stream), streams are purely a way of running multiple things on your GPU at once. So it might still be appropriate to call this OpenCL.

BTW, if you want to stop bikeshedding and just land *something* so you can unblock, I'm happy to do this too. But I am thinking of @wickedfoo and other people who are also interested in OpenCL, and it will be easier for them later if we work out what the right thing is to do today.

**Comment by dylanbespalko** [comment]
@ezyang, @wickedfoo

My plan is as follows:
1.  Register under `FPGA` to allow Xilinx FPGA developers to split the problem into separate math kernels instead of blowing up the API with aggregated functions.
2. Figure out how to do the Xilinx specific code using generic OpenCL commands.
3. Re-register under OpenCL.

Additional problems:
 - The current Xilinx solution doesn't support embedded devices.
 - There is an incomplete tutorial online that suggests embedded devices can be supported soon.
 - I'm going be working with a bunch of people that only use Xilinx FPGAs very soon.
 - This stuff is very recent (mid-2019) and is going to be complicated for a little while.
 - There isn't much documentation.

**I'd appreciate if you could accept this solution because I don't think I could make a generic OpenCL version for at least 6 months.**

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
Note to self: if we're going to super-specialize for Xilinx maybe should just call it Xilinx not FPGA. Doesn't matter too much right now, I think.

**Comment by dylanbespalko** [comment]
@ezyang,

> maybe should just call it Xilinx not FPGA

Agreed. Let me discuss it with my co-workers and come back to this in 3-4 weeks.

**Pull request closed without merging**
