### PR TITLE
print clang tidy output to stderr

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#24052 print clang tidy output to stderr**

This will make things show up in the azure pipelines output

Differential Revision: [D16723846](https://our.internmc.facebook.com/intern/diff/D16723846)

### CODE REVIEW

**Review by ZolotukhinM — APPROVED** [review]
Looks good except it doesnt work with Python2. Are we officially over it already (if so, we should remove it from our testing)?

**Comment by suo** [comment]
I've added a `__future__` import that should fix this issue. I will wait to verify in CI that it works.

**Review by ezyang — APPROVED** [review]
Thank you!! I've been meaning to do this and hadn't gotten around to it. Wanna fix our other stuff too? :)

**Comment by suo** [comment]
@ezyang sure :) I'll take a look tongiht

**Pull request closed without merging**
