### PR TITLE
Removed special case for reshape on the IPU

### PR DESCRIPTION
**Pull request by Anstow**
This is no longer needed by the IPU.

### CODE REVIEW

**Comment by Anstow** [comment]
I don't think that failure is anything to do with this PR. Should I rebase and try again?

**Comment by colesbury** [comment]
I re-ran the failing builds. They looked unrelated.

**Comment by colesbury** [comment]
cc @AnthonyBarbier @ Graphcore

**Comment by AnthonyBarbier** [comment]
> cc @AnthonyBarbier @ Graphcore

Yes, happy with that change. Thanks for checking :+1:

**Review by AnthonyBarbier — APPROVED** [review]

**Review by bdhirsh — APPROVED** [review]

**Pull request closed without merging**
