### PR TITLE
add XLA backend into tensor type strings

### PR DESCRIPTION
**Pull request by holimion**
add XLA backend into tensor type strings

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
TBH I think we want to kill `c10::Backend` eventually (it's a legacy concept that can be fully represented by device types / dispatch keys), but nobody's staffed for it. SGTM!

**Comment by bdhirsh** [comment]
@holimion, you'll need to sign the CLA for me to merge.

**Comment by holimion** [comment]
i changed my local git user name and email address to match the configuration of github. it seems to trigger ci again...

**Comment by holimion** [comment]
@bdhirsh it seems the test failure is not triggered by my commit, and i cannot reproduce it locally. can we retrigger the CI?

**Pull request closed without merging**
