### PR TITLE
FunctionalTensor: dispatch metadata directly to inner tensor

### PR DESCRIPTION
**Pull request by bdhirsh**
Fixes https://github.com/pytorch/pytorch/issues/127374

The error in the linked repro is:
```
AssertionError: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.sym_storage_offset.default(_to_functional_tensor(FakeTensor(..., device='cuda:0', size=(16, 4), dtype=torch.uint8),
       device='cuda:0'))
```

Where we hit FakeTensor.__torch_dispatch__, but our input is a C++ `FunctionalTensorWrapper`.

What should actually have happened is that the call to `aten.sym_storage_offset` hits the `Functionalize` dispatch key, which should remove the `FunctionalTensorWrapper`  and redispatch. I spent some time debugging and haven't actually figured out why this isn't happening. Instead, this PR just skips that step completely, and asks `FunctionalTensor` to directly unwrap the C++ `FunctionalTensorWrapper` when querying tensor metadata.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #127347
* #128331
* #128045
* #128570
* __->__ #127927

### CODE REVIEW

**Review by tugsbayasgalan — APPROVED** [review]

**Comment by melvinebenezer** [comment]
@ bdhirsh may I know when this would be merged ?

**Comment by bdhirsh** [comment]
@melvinebenezer working on it (round-robining between this and a few other things) - I'll hopefully try to land in the next few days.

**Comment by melvinebenezer** [comment]
@bdhirsh thanks a lot for the fix

**Pull request closed without merging**
