### PR TITLE
[TorchTidy] Adding support for storing scalar values in profiling

### PR DESCRIPTION
**Pull request by Gamrix**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #82787
* __->__ #81843

Differential Revision: [D38412482](https://our.internmc.facebook.com/intern/diff/D38412482)

### CODE REVIEW

**Review by robieta — APPROVED** [review]
This is awesome. Have you measured the overhead? Although it's mostly just out of curiosity; I can't imagine that another approach would be faster (or even as fast) as what you have here.

**Comment by Gamrix** [comment]
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38412482).

**Comment by Gamrix** [comment]
Overhead information: 
Worse than I would've expected :/

[D38412482](https://www.internalfb.com/diff/D38412482)
https://our.internmc.facebook.com/intern/aibench/details/1216719728 
https://our.internmc.facebook.com/intern/aibench/details/2852921225 
https://our.internmc.facebook.com/intern/aibench/details/308408276 
https://our.internmc.facebook.com/intern/aibench/details/3785164820 
https://our.internmc.facebook.com/intern/aibench/details/1536294584

P10 P50 P90	
1.2249 1.2278 1.2366
1.2244 1.2297 1.2459	
1.2216 1.2269 1.2405


base of [D38412482](https://www.internalfb.com/diff/D38412482)
https://our.internmc.facebook.com/intern/aibench/details/3415091160 
https://our.internmc.facebook.com/intern/aibench/details/3382452677 
https://our.internmc.facebook.com/intern/aibench/details/2669142924 

P10 P50 P90
1.1141 1.1193 1.1369
1.1451 1.1490 1.1603
1.1221 1.1263 1.1345

**Comment by robieta** [comment]
> Overhead information: Worse than I would've expected :/
> 
> [D38412482](https://www.internalfb.com/diff/D38412482) https://our.internmc.facebook.com/intern/aibench/details/1216719728 https://our.internmc.facebook.com/intern/aibench/details/2852921225 https://our.internmc.facebook.com/intern/aibench/details/308408276 https://our.internmc.facebook.com/intern/aibench/details/3785164820 https://our.internmc.facebook.com/intern/aibench/details/1536294584
> 
> P10 P50 P90 1.2249 1.2278 1.2366 1.2244 1.2297 1.2459 1.2216 1.2269 1.2405
> 
> base of [D38412482](https://www.internalfb.com/diff/D38412482) https://our.internmc.facebook.com/intern/aibench/details/3415091160 https://our.internmc.facebook.com/intern/aibench/details/3382452677 https://our.internmc.facebook.com/intern/aibench/details/2669142924
> 
> P10 P50 P90 1.1141 1.1193 1.1369 1.1451 1.1490 1.1603 1.1221 1.1263 1.1345

That's unfortunate. How does that compare to just storing a `c10::Scalar`? It's not ideal, but hopefully will give us some baseline for the cost to store a simpler (albeit larger) type.

**Comment by Gamrix** [comment]
The overhead is the same for Scalar, which is not surprising as you make the copy trivial, but on the other hand, you have to call `ivalue.toScalar()` to convert it.

https://our.internmc.facebook.com/intern/aibench/details/4076738461 
https://our.internmc.facebook.com/intern/aibench/details/1092748111
https://our.internmc.facebook.com/intern/aibench/details/4144779513 
1.2236 1.2272 1.2597
1.2157 1.2221 1.2310
1.1976 1.2160 1.2219

**Comment by Gamrix** [comment]
@gamrix has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38412482).

**Pull request closed without merging**
