### PR TITLE
[Checkpoint][2D][5/N] Add checkpoint_utils for distributed checkpoint to testing/_internal/distributed/

### PR DESCRIPTION
**Pull request by wz337**
Moving checkpoint_utils from Tau: https://github.com/wz337/PiPPy/blob/6acf4054cfd10c8377d65fa1e4f18230d6711edd/spmd/testing/checkpoint_utils.py 

Checkpoint_utils: add a wrapper to initialize a temp directory for checkpoint testing.

### CODE REVIEW

**Review by XilunWu — APPROVED** [review]
lgtm. adding new util func.

**Review by awgu — APPROVED** [review]

**Review by fduwjj — APPROVED** [review]
LGTM

**Pull request closed without merging**
