### PR TITLE
Enable `dim=None` for `torch.var`

### PR DESCRIPTION
**Pull request by kurtamohler**
### Description
Add support for `dim=None` in `torch.var`

### Issue
Part of #29137

### Testing
N/A

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM
These PRs are getting smaller and smaller :p

**Comment by kurtamohler** [comment]
@albanD, maybe it would be better if I start doing several ops together instead. That would make XLA coordination way easier. wdyt?

**Comment by albanD** [comment]
I feel like we have a good grasp on the change on our end and their implication. So yes I'm happy for these PR to grow bigger (as long as it is for ops that are not "problematic").

**Comment by kurtamohler** [comment]
Also worth noting, some of these ops, like `var`, don't need XLA changes because they already have `OptionalIntArrayRef` in the XLA signature.

**Pull request closed without merging**
