### PR TITLE
[tensorboard] Remove duplicated _optimize_trace

### PR DESCRIPTION
**Pull request by lanpa**
The duplicated code of `_optimize_trace` in _pytorch_graph.py is used to bypass some optimization step which causes missing scope.

It seems that most of the problematic steps have been fixed recently. Standard models implemented in torchvision are visually inspected before the commit. However, the `+=` in https://github.com/pytorch/vision/blob/50d54a82d1479ffb6dd7469ed05fccdf290a1d84/torchvision/models/resnet.py#L63 will let https://github.com/pytorch/pytorch/blob/f4d9bfaa4dd983288518a310bb900756ee3c6046/torch/onnx/utils.py#L159 produce a bad result. It can be fixed by replacing it with `out += identity`. This also implies that `+=` has non-intuitive behavior.

cc @orionr @ezyang

### CODE REVIEW

**Comment by suo** [comment]
What do you mean by the pass produces a "bad result"? Can you provide a before and after graph to help clarify things

**Comment by orionr** [comment]
Thank you for this! Let's see if we can get an equivalent of visual inspection in the tests. Talking with people about this.

**Comment by lanpa** [comment]
The traced result is different.
A small code to reproduce:

```python
import torch
import torch.nn as nn
import torchvision
from torch.onnx import _optimize_trace
from torch.onnx.utils import OperatorExportTypes
dummy_input = torch.zeros(1, 3, 224, 224)

class MyClass(nn.Module):
    def __init__(self):
            super(MyClass, self).__init__()
            self.l = nn.ReLU()

    def forward(self, x):
            x+=self.l(x)  # x =x+self.l(x) is OK
            return x

model = MyClass()
trace, _ = torch.jit.get_trace_graph(model, dummy_input)
print(trace.graph())
_optimize_trace(trace,getattr(OperatorExportTypes, "ONNX"))
print(trace.graph())
```


```
graph(%input : Float(1, 3, 224, 224)):
  %1 : Float(1, 3, 224, 224) = aten::clone(%input)
  %2 : Float(1, 3, 224, 224) = aten::relu(%input), scope: MyClass/ReLU[l]
  %3 : int = prim::Constant[value=1](), scope: MyClass
  %4 : Float(1, 3, 224, 224) = aten::add_(%input, %2, %3), scope: MyClass
  return (%4)

graph(%input : Float(1, 3, 224, 224)):
  %1 : Float(1, 3, 224, 224) = onnx::Relu(%input), scope: MyClass/ReLU[l]
  %2 : Float(1, 3, 224, 224) = onnx::Add(%input, %1)   <---------missing scope
  return (%2)
```

**Comment by orionr** [comment]
@suo, is there an alternate method that @lanpa should be using here to get a cleaner / optimized output without using ONNX? Looks like the clone and const ops in the non-ONNX version are what @lanpa is hoping to not have.

**Comment by lanpa** [comment]
@orionr 
How can I optimize the graph of trace.graph_for(dummy_input)? Or is that an already optimized result?

result of `graph_for`:
```
graph(%input : Tensor):
  %2 : int = prim::Constant[value=1](), scope: MyClass
  %1 : Tensor = aten::relu(%input), scope: MyClass/ReLU[l]
  %3 : Tensor = aten::add_(%input, %1, %2), scope: MyClass
  return (%3)
```
@suo 
My point is that the code path for `tensor += x` and `tensor = tensor + x` might be different at a low level so that they have different optimization result.

**Comment by suo** [comment]
@lanpa `graph_for` gives you the already-optimized result (specialized for the dummy input).

The in-place thing is a quirk of the ONNX export. ONNX does not support in-place operations, so the in-place add is rewritten into an out-of-place add and a warning is emitted if we detect that this may change the result of the program.

The JIT itself supports in-place ops, so the resulting graph will correctly preserve the user's code.

**Comment by lanpa** [comment]
@suo
"so the in-place add is rewritten into an out-of-place add"
Got it, I guess this is why the scope of the new `add` operation is missing.

**Comment by suo** [comment]
Correct. There are two action items here:
1. In the short term: that pass (RemoveInplaceOps) should copy the scope over when it creates the replacement node. Pretty simple change, happy to review a PR for that :)
2. In the long term: we should visualize the JIT graph directly (using graph_for()) instead exporting to ONNX

**Review by orionr — APPROVED** [review]
Excellent! @suo does this look good to you?

**Comment by suo** [comment]
lgtm

**Pull request closed without merging**
