### PR TITLE
grammatically update index.rst

### PR DESCRIPTION
**Pull request by belphegor-s**
This is a following up PR for #45652 which has a problem to rebase.

### CODE REVIEW

**Comment by glaringlee** [comment]
This is a following up PR for #45652 which is not able to be rebased correctly, so the contributor created a new one.

**Review by glaringlee — APPROVED** [review]
LGTM now, thanks for correct this.

**Comment by belphegor-s** [comment]
is this PR merged correctly..I am seeing a message that it is closed without merging my commits.

**Comment by fmassa** [comment]
@belphegor-s this is how PyTorch commits are merged. A bot merges it for us, see https://github.com/pytorch/pytorch/commit/162717e527f3f3572a27cd599519db89fa29661f for the merged commit in master

**Comment by belphegor-s** [comment]
> @belphegor-s this is how PyTorch commits are merged. A bot merges it for us, see https://github.com/pytorch/pytorch/commit/162717e527f3f3572a27cd599519db89fa29661f for the merged commit in master

Oh I see, thanks for the reply, happy to give my first contribution to pytorch repo.. will continue to give more contributions in future.

**Pull request closed without merging**
