### PR TITLE
[EASY] Document load_inline

### PR DESCRIPTION
**Pull request by goldsborough**
Documentation for `load_inline` in C++ extensions @apaszke @soumith

### CODE REVIEW

**Comment by fmassa** [comment]
This looks great! But can we also copy-paste the test cases in the documentation? I think it will be even simpler for the users. What do you think?

**Comment by goldsborough** [comment]
I don't know about copy pasting, maybe link to them instead?

**Comment by fmassa** [comment]
It would look like an example, right?

**Comment by goldsborough** [comment]
I think that would make the documentation very long. I've put the link at the very top

**Review by apaszke — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Pull request merged**
