### PR TITLE
[Inductor][Quant] Add UT to combine dynamo export and inductor constant folding

### PR DESCRIPTION
**Pull request by leslie-fang-intel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #98826
* #104075
* __->__ #104245

**Summary**
As we report in [Issue-103582](https://github.com/pytorch/pytorch/issues/103582), previous `constant folding` failed to work after `dynamo export`. With latest PyTorch main branch, we can't reproduce this error. Adding UT in this PR to cover this use case. 

**Test Plan**
```
python -m pytest test_inductor_freezing.py -k test_functional_constant_folding_after_dynamo_export
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Comment by leslie-fang-intel** [comment]
Hi @jansel @eellison, could you kindly help to take a look of this PR?

**Review by eellison — APPROVED** [review]

**Pull request closed without merging**
