### PR TITLE
reland D28645531: .github: Add Windows GPU workflow

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#59678 reland D28645531: .github: Add Windows GPU workflow**

This reverts commit 2956bbaf2388d424ef986c22fac8287f7c345978.

Reland of https://github.com/pytorch/pytorch/pull/58782

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

Differential Revision: [D28981443](https://our.internmc.facebook.com/intern/diff/D28981443)

### CODE REVIEW

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28981443).

**Comment by samestep** [comment]
What's the diff between this and #58782?

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28981443).

**Comment by seemethere** [comment]
> What's the diff between this and #58782?

This is a reland

**Review by samestep — APPROVED** [review]

**Pull request closed without merging**
