### PR TITLE
[jiterator] De-template launch_jitted_reduce_kernel

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #80138
* #80103

As with `jitted_gpu_kernel_impl`, this
1. Hoists static variables out and into a parent funciton
2. Moves template arguments into the `jit::KernelDescriptor` struct,
   as well as changing `vt0` to just be a runtime argument
3. Changes the types of pass-through arguments to `void*`

On my build I see a 0.5 MB decrease in binary size for `libtorch_cuda.so`.

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by b0noI** [comment]
@pytorchmergebot revert -m "internal breakage" -c nosignal

```
caffe2/aten/src/ATen/native/cuda/jit_utils.h:71:41: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
  TORCH_INTERNAL_ASSERT(pointers.size() == 1 + desc.nInputs);
                        ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~
caffe2/aten/src/ATen/native/cuda/jit_utils.h:71:41: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
  TORCH_INTERNAL_ASSERT(pointers.size() == 1 + desc.nInputs);
                        ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~
caffe2/aten/src/ATen/native/cuda/jit_utils.h:71:41: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
  TORCH_INTERNAL_ASSERT(pointers.size() == 1 + desc.nInputs);
                        ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~
```

**Comment by peterbell10** [comment]
@pytorch merge -g

**Comment by mehtanirav** [comment]
@pytorchmergebot revert -m "internal breakage" -c nosignal

```
c:\cygwin\data\sandcastle\boxes\trunk-hg-full-fbsource\xplat\caffe2\aten\src\aten\native\cuda\cudajitloops.cuh(63): error C2100: illegal indirection
```

**Comment by mehtanirav** [comment]
@peterbell10  Sorry to revert this PR again due to internal breakages. I can help you with verifying this PR does not cause internal breakages before we merge it again.

**Pull request closed without merging**
