### PR TITLE
Ports THCNumerics to ATen

### PR DESCRIPTION
**Pull request by mruberry**
This PR ports THCNumerics to ATen with the following changes:

- Creates ATen/cuda/CUDANumerics.cuh
- Stubs THCNumerics to use CUDANumerics
- Incorporates host-side fp32<->fp16 conversions into ATen/Half and ScalarConvert, removing ATen/Half.cpp's TH dependency, and updates CUDANumerics to use scalar_cast for these conversions
- Updates TH and THC to use the ATen conversions
- Removes unused THCHalf.cu

Two things it does not do are:

- Make THCGeneral.cpp use scalar_cast; this would require it importing CUDANumerics.cuh for two legacy functions, which seems excessive
- Update or unify THCHalfAutoNumerics.cuh and ATen/Half-inl.h

### CODE REVIEW

**Comment by mruberry** [comment]
CUDA 8 failure is real; working on a fix.

**Comment by colesbury** [comment]
@mruberry what are you trying to do? I've been trying to avoid further uses of THCNumerics and `scalar_cast` in ATen.

**Comment by mruberry** [comment]
I was looking to reduce ATen's dependence on TH* and move a heavily depended on part of THC to ATen to support additional refactoring.

What alternative were you thinking of? Maybe we can incorporate it?

**Comment by mruberry** [comment]
@colesbury and I reviewed offline and developed an alternative plan to what this PR proposed. Instead of porting THCNumerics, we will:

- Use at::Half for implicit conversions and "catch-all" versions of functions like pow (vs powf) where possible.
- Create CUDANumerics for when this is not possible (min() and max(), for example).
- Align THCNumerics with the intended "catch-all" behavior.
- Remove the unused CUDA_HALF_INSTRUCTIONS from THCNumerics.
- Document the preferred pattern of using at::Half and CUDANumerics (only when necessary), effectively deprecating THCNumerics.
- Refactor the handling of halfs in TH* to respect these updates and the desire to use at::Half going forward.

This should clarify the best practice for developers and remove some legacy code.

**Pull request closed without merging**
