### PR TITLE
[ci] do not continue through error on trunk

### PR DESCRIPTION
**Pull request by suo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#65503 [ci] do not continue through error on trunk**

There are two reasons for this change:
- I don't think trunk jobs should have different behavior than their PR equivalents.
- Continuing through error makes it challenging to figure out what is
actually failing, especially given the poor UX of GitHub Actions when it
comes to reading logs

Example: https://github.com/pytorch/pytorch/runs/3680114581. Here, there
is a failure but the rendered test results tell me everything is
successful. I have no idea how to quickly tell what failed; the log is so long
and terms like "error", "failure", etc. are common enough that searching
it is very difficult.

Differential Revision: [D31130478](https://our.internmc.facebook.com/intern/diff/D31130478)

### CODE REVIEW

**Comment by suo** [comment]
@suo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31130478).

**Comment by suo** [comment]
@suo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31130478).

**Review by janeyx99 — APPROVED** [review]
I agree with the point that this is affecting test reporting and that may outweigh the benefits so it'd be good to turn this off temporarily, but would like to hear the opinions of others on this.

**Comment by suo** [comment]
alright, I'm going to land this PR today, so get your commentary in before it's too late!

**Pull request closed without merging**
