### PR TITLE
[WIP] Improvement in derivative computations and change return variable from `destination` to `result` for certain ops

### LINKED ISSUE #4402: Some computational efficiency improvements in derivatives
I was going through the `derivatives.yaml` for the derivative of existing functions in `torch`, and feel like some of them are a bit inefficient. Some of them are listed below:

- `reciprocal` : From `grad / -(self * self)` to `- grad * result * result`
- `sqrt`: From `grad * self.pow(-0.5) / 2` to `grad * self.rsqrt() * 0.5` or `grad / (2 * result)`
- `acos`: From `grad * -((-self * self + 1).sqrt().reciprocal())` to `grad * -(self.rsqrt(self * self + 1))` and similarly for `asin`
- `div(Tensor self, Tensor other)`: Modify `other`'s derivative from `-grad * self / (other * other)` to `-grad * result / other`
- `tan`: From `grad / self.cos().pow(2)` to `grad * (1 + result.pow(2))`
- `atan`: From `grad * (self * self + 1).reciprocal()` to `grad / (self * self + 1)`
- `std`: From `grad * (2 * result).reciprocal()` to `grad / (2 * result)`
- `addcdiv`: From `-grad * value * tensor1 / (tensor2 * tensor2)` to `grad * (self - result) / tensor2`

Here I am assuming that a divide operation is costlier than a multiply operation.

Let me know your views about these ops, and I will issue a PR if required. 

- [x] `reciprocal`
- [x] `sqrt`
- [x] `acos`
- [x] `asin`
- [ ] `div`
- [x] `tan`
- [x] `atan`
- [x] `std`
- [ ] `addcdiv`

### PR DESCRIPTION
**Pull request by vishwakftw**
This will close https://github.com/pytorch/pytorch/issues/4402.

### CODE REVIEW

**Review by apaszke — APPROVED** [review]

**Comment by vishwakftw** [comment]
`reciprocal` does not have a `result`, like some other functions do. Hence the builds failed.

**Comment by apaszke** [comment]
Uh I think a better fix would be to fix `Declarations.yaml`. It should be consistent across definitions

**Comment by vishwakftw** [comment]
That will require changing `Functions.h`, `Tensor.h` and a few more files. Shall I do it?

**Comment by apaszke** [comment]
I see. I'm ok with changing this everywhere. Let me know if you want to do this, or just want to get this in as is

**Comment by vishwakftw** [comment]
I could do it and commit the changes in this PR itself. Thanks!!

**Comment by vishwakftw** [comment]
I have changed the names in the last commit. 

cc: @apaszke

**Comment by vishwakftw** [comment]
If there are no improvements suggested further than those mentioned in the issue, I could remove the WIP tag. 

cc: @apaszke @colesbury

**Review by apaszke — CHANGES_REQUESTED** [review]
It seems that you've incorrectly synced up with master (some `torch.distributions` changes are reverted). Also, please remove the changes in `aten/doc`. These are auto-generated files that shouldn't be touched

**Comment by apaszke** [comment]
Can you also please add the fix for `div`?

**Comment by vishwakftw** [comment]
This branch has become extremely dirty. I will close this, and reopen a new PR.

**Pull request closed without merging**
