### PR TITLE
[Caffe2] Additional -setup- build path + better code layout of build.sh

### PR DESCRIPTION
**Pull request by pjh5**

### CODE REVIEW

**Comment by pjh5** [comment]
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-setup-ubuntu16.04-trigger-test/1 to test the new -setup- path

**Comment by pjh5** [comment]
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-setup-ubuntu16.04-build/3 worked

**Comment by pjh5** [comment]
Retries
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py3.6-clang3.8-rocm1.7.1-ubuntu16.04-build/762
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-cuda9.0-cudnn7-aten-ubuntu16.04-test/551

**Review by orionr — APPROVED** [review]

**Comment by pjh5** [comment]
Retry of failed test https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-gcc4.8-ubuntu14.04-build/5578/

**Pull request merged**
