### PR TITLE
Fix typos in torch/fx/_compatibility.py

### PR DESCRIPTION
**Pull request by fakeYan**
Fixes #ISSUE_NUMBER
Modify the _compatibility.py file global variable name and modify its test file simultaneously.

cc @ezyang @SherlockNoMad @soumith @EikanWang @jgong5 @wenzhe-nrv

### CODE REVIEW

**Comment by janeyx99** [comment]
@SherlockNoMad  could you take a look?

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
