### PR TITLE
[typing] added to torch._C._nn hints

### PR DESCRIPTION
**Pull request by emmett-bicker**
Works on #141828

This commit adds to `tools/pyi/gen_pyi.py` to generate more type hints in `_nn.pyi`. I mainly created the hints by looking at the corresponding .h file in build/atn/src/Aten/ops, but there were often inconsistencies in the header files (such as excluding an out parameter or naming the first input "self" when in python it's "input") so I made tests to validate my hints that I didn't include in the commit. An example of one of these tests is attached at the bottom of the pr.

I made a significant amount of progress, but there's still more to be done. Adding more stubs would be great, and some of the existing type stubs need to be fixed as I tested a few and they were missing an out parameter in their stub or the first input parameter was named "self" in the stub but the actual function's was "input".

I added the hints for cross_entropy_loss, binary_cross_entropy, l1_loss, smooth_l1_loss, max_pool2d_with_indices, max_pool3d_with_indices, huber_loss, mse_loss, multilabel_margin_loss, soft_margin_loss, multi_margin_loss, upsample_nearest1d, upsample_nearest2d, upsample_nearest3d, _upsample_nearest_exact1d, _upsample_nearest_exact2d, and _upsample_nearest_exact3d,

but 

max_unpool3d, adaptive_avg_pool2d, adaptive_avg_pool3d, glu, relu6_, relu6, elu, hardsigmoid_, silu_, silu, mish_, mish, hardswish_, hardswish, nll_loss_nd, upsample_linear1d, _upsample_bilinear2d_aa, upsample_bilinear2d, upsample_trilinear3d, _upsample_bicubic2d_aa, upsample_bicubic2d, im2col, col2im

all still need hints.

Here's an example of the tests I didn't include:
```python
def  test_cross_entropy_loss():
    """
    cross_entropy_loss": [
        "def cross_entropy_loss({}) -> Tensor: ...".
        format(
            ", ".join(
                [
                    "input: Tensor",
                    "target: Tensor",
                    "weight: Optional[Tensor] = None",
                    "reduction: int = 1",
                    "ignore_index: int = -100",
                    "label_smoothing: float = 0.0",
                ]
            )
        )
    """
    try:
        torch._C._nn.cross_entropy_loss(InvalidType(), InvalidType())
        raise Exception # these make sure the above code raises an error
    except Exception as e:
        assert e.__str__() == "cross_entropy_loss(): argument 'input' (position 1) must be Tensor, not InvalidType", e.__str__()

    try:
        torch._C._nn.cross_entropy_loss(t, InvalidType())
        raise Exception
    except Exception as e:
        assert e.__str__() == "cross_entropy_loss(): argument 'target' (position 2) must be Tensor, not InvalidType", e.__str__()

    try:
        torch._C._nn.cross_entropy_loss(t, t, InvalidType())
        raise Exception
    except Exception as e:
        assert e.__str__() == "cross_entropy_loss(): argument 'weight' (position 3) must be Tensor, not InvalidType", e.__str__()

    try:
        torch._C._nn.cross_entropy_loss(t, t, t, InvalidType())
        raise Exception
    except Exception as e:
        assert e.__str__() == "cross_entropy_loss(): argument 'reduction' (position 4) must be int, not InvalidType", e.__str__()

    try:
        torch._C._nn.cross_entropy_loss(t, t, t, i, InvalidType())
        raise Exception
    except Exception as e:
        assert e.__str__() == "cross_entropy_loss(): argument 'ignore_index' (position 5) must be int, not InvalidType", e.__str__()

    try:
        torch._C._nn.cross_entropy_loss(t, t, t, i, i, InvalidType())
        raise Exception
    except Exception as e:
        assert e.__str__() == "cross_entropy_loss(): argument 'label_smoothing' (position 6) must be float, not InvalidType", e.__str__()

    try:
        torch._C._nn.cross_entropy_loss(t, t, t, i, i, f)
        raise Exception
    except Exception as e:
        assert e.__str__() == "ignore_index is not supported for floating point target", e.__str__() # means it ran the code

    try:
        torch._C._nn.cross_entropy_loss(t, t, t, i, i, f, out=InvalidType())
        raise Exception
    except Exception as e:
        assert e.__str__() == "cross_entropy_loss() got an unexpected keyword argument 'out'", e.__str__() 

```

### CODE REVIEW

**Comment by ezyang** [comment]
I will probably accept this as is as it is in the prevailing style, but I do wonder why we are not automatically generating these (and instead enumerating the signatures one by one)

**Review by ezyang — APPROVED** [review]

**Comment by EmmettBicker** [comment]
@ezyang I'd love to work on auto generating the stubs in another pr! If you have the time I would love to ask for some clarification on how to go about this.

I found that functions are bound to torch._C._nn in the tools/autograd/gen_python_function.py which maps it to its corresponding binding in torch/csrc/autograd/generated/python_nn_functions.cpp, and the python methods are in the py_methods variable in gen_python_function.py's create_python_bindings method and these methods do contain the method headers which I can likely automatically translate into Python.

I think I can achieve autogenerating these stubs by parsing the data in py_methods! 

Is there anything else I should know about the binding generation? And would the proper place to place an automatic stub generater be in tools/autograd/gen_type_stubs.py?

**Comment by ezyang** [comment]
looks like gotta fix some type errors in pyi

**Comment by ezyang** [comment]
> I found that functions are bound to torch._C._nn in the tools/autograd/gen_python_function.py which maps it to its corresponding binding in torch/csrc/autograd/generated/python_nn_functions.cpp, and the python methods are in the py_methods variable in gen_python_function.py's create_python_bindings method and these methods do contain the method headers which I can likely automatically translate into Python.

You could do it this way. But the way that we're doing non nn is to directly generate the Python signatures off of what is parsed out of native_functions.yaml (there's torchgen data structures for it). I'd look at the existing code first.

**Comment by EmmettBicker** [comment]
Ok sounds good! Thank you for letting me know both things :)

**Comment by EmmettBicker** [comment]
The issue was that I left out an optional; sorry for taking up your time!

**Comment by EmmettBicker** [comment]
I'm going to mark this PR as draft until I add the automated typing generation because I don't think it should be merged just for me to overwrite it a day or two later

**Comment by EmmettBicker** [comment]
Hi! @ezyang I added in the automated typing. I'm quite happy with it and it seems quite robust. I tested its generations on the following paritions
    - 'self' input param/no 'self' input param
    - no out param/only out param/out param and not out param
    - no overload = 1 result, overload with out param = 1 result, distinct overloads =  2 results
    - returns Tensor, returns other

    Other tests
    - all functions found with the nn module must have at least 1 definition

It passed all of these tests. I don't know if I should include documentation tests so I didn't include it, but let me know if you'd like me to add it in. Here's what it generated:

```py
# @generated from ..\torch\_C/_nn.pyi
from numbers import Number
from typing import Generator, List, Optional, overload, Sequence, Tuple, Union

from torch import Tensor
from torch.types import _bool, _int, _float, _size, _complex, SymInt

# Defined in tools/autograd/templates/python_nn_functions.cpp

def _conv_depthwise2d(input: Tensor, weight: Tensor, kernel_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], bias: Optional[Tensor], stride: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], dilation: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], *, out: Optional[Tensor] = None) -> Tensor: ...
def _pad_circular(input: Tensor, pad: Sequence[Union[_int, SymInt]]) -> Tensor: ...
def _pad_enum(input: Tensor, pad: Sequence[Union[_int, SymInt]], mode: _int, value: Optional[_float] = None) -> Tensor: ...
@overload
def _test_ambiguous_defaults(dummy: Tensor, a: _int = 1, b: _int = 1) -> Tensor: ...
@overload
def _test_ambiguous_defaults(dummy: Tensor, a: _int = 2, b: str = "2") -> Tensor: ...
def _test_optional_filled_intlist(values: Tensor, addends: Optional[Union[_int, _size]]) -> Tensor: ...
def _test_optional_floatlist(values: Tensor, addends: Optional[Sequence[_float]]) -> Tensor: ...
def _test_optional_intlist(values: Tensor, addends: Optional[_size]) -> Tensor: ...
def _test_string_default(dummy: Tensor, a: str = "\"'\\", b: str = "\"'\\") -> Tensor: ...
def _test_warn_in_autograd(input: Tensor) -> Tensor: ...
@overload
def _upsample_bicubic2d_aa(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], align_corners: _bool, scales_h: Optional[_float] = None, scales_w: Optional[_float] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
@overload
def _upsample_bicubic2d_aa(input: Tensor, output_size: Optional[Sequence[Union[_int, SymInt]]], align_corners: _bool, scale_factors: Optional[Sequence[_float]]) -> Tensor: ...
@overload
def _upsample_bilinear2d_aa(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], align_corners: _bool, scales_h: Optional[_float] = None, scales_w: Optional[_float] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
@overload
def _upsample_bilinear2d_aa(input: Tensor, output_size: Optional[Sequence[Union[_int, SymInt]]], align_corners: _bool, scale_factors: Optional[Sequence[_float]]) -> Tensor: ...
@overload
def _upsample_nearest_exact1d(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], scales: Optional[_float] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
@overload
def _upsample_nearest_exact1d(input: Tensor, output_size: Optional[Sequence[Union[_int, SymInt]]], scale_factors: Optional[Sequence[_float]]) -> Tensor: ...
@overload
def _upsample_nearest_exact2d(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], scales_h: Optional[_float] = None, scales_w: Optional[_float] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
@overload
def _upsample_nearest_exact2d(input: Tensor, output_size: Optional[Sequence[Union[_int, SymInt]]], scale_factors: Optional[Sequence[_float]]) -> Tensor: ...
@overload
def _upsample_nearest_exact3d(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], scales_d: Optional[_float] = None, scales_h: Optional[_float] = None, scales_w: Optional[_float] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
@overload
def _upsample_nearest_exact3d(input: Tensor, output_size: Optional[Sequence[Union[_int, SymInt]]], scale_factors: Optional[Sequence[_float]]) -> Tensor: ...
def adaptive_avg_pool2d(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], *, out: Optional[Tensor] = None) -> Tensor: ...
def adaptive_avg_pool3d(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], *, out: Optional[Tensor] = None) -> Tensor: ...
def adaptive_max_pool2d(input: Tensor, output_size: Union[_int, _size], *, out: Union[Tensor, Tuple[Tensor, ...], List[Tensor], None] = None) -> Tuple[Tensor, Tensor]: ...
def adaptive_max_pool3d(input: Tensor, output_size: Union[_int, _size], *, out: Union[Tensor, Tuple[Tensor, ...], List[Tensor], None] = None) -> Tuple[Tensor, Tensor]: ...
def avg_pool2d(input: Tensor, kernel_size: Union[_int, _size], stride: Union[_int, _size] = (), padding: Union[_int, _size] = 0, ceil_mode: _bool = False, count_include_pad: _bool = True, divisor_override: Optional[_int] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
def avg_pool3d(input: Tensor, kernel_size: Union[_int, _size], stride: Union[_int, _size] = (), padding: Union[_int, _size] = 0, ceil_mode: _bool = False, count_include_pad: _bool = True, divisor_override: Optional[_int] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
def binary_cross_entropy(input: Tensor, target: Tensor, weight: Optional[Tensor] = None, reduction: _int = 1, *, out: Optional[Tensor] = None) -> Tensor: ...
def col2im(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], kernel_size: Union[_int, _size], dilation: Union[_int, _size], padding: Union[_int, _size], stride: Union[_int, _size], *, out: Optional[Tensor] = None) -> Tensor: ...
def conv_depthwise3d(input: Tensor, weight: Tensor, kernel_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], bias: Optional[Tensor], stride: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], dilation: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]]) -> Tensor: ...
def cross_entropy_loss(input: Tensor, target: Tensor, weight: Optional[Tensor] = None, reduction: _int = 1, ignore_index: Union[_int, SymInt] = -100, label_smoothing: _float = 0.0) -> Tensor: ...
def elu(input: Tensor, alpha: Union[Number, _complex] = 1, scale: Union[Number, _complex] = 1, input_scale: Union[Number, _complex] = 1, *, out: Optional[Tensor] = None) -> Tensor: ...
def elu_(input: Tensor, alpha: Union[Number, _complex] = 1, scale: Union[Number, _complex] = 1, input_scale: Union[Number, _complex] = 1) -> Tensor: ...
def flatten_dense_tensors(tensors: Union[Tuple[Tensor, ...], List[Tensor]]) -> Tensor: ...
def fractional_max_pool2d(input: Tensor, kernel_size: Union[_int, _size], output_size: Union[_int, _size], random_samples: Tensor, *, out: Union[Tensor, Tuple[Tensor, ...], List[Tensor], None] = None) -> Tuple[Tensor, Tensor]: ...
def fractional_max_pool3d(input: Tensor, kernel_size: Union[_int, _size], output_size: Union[_int, _size], random_samples: Tensor, *, out: Union[Tensor, Tuple[Tensor, ...], List[Tensor], None] = None) -> Tuple[Tensor, Tensor]: ...
def gelu(input: Tensor, *, approximate: str = "none", out: Optional[Tensor] = None) -> Tensor: ...
def gelu_(input: Tensor, *, approximate: str = "none") -> Tensor: ...
def glu(input: Tensor, dim: _int = -1, *, out: Optional[Tensor] = None) -> Tensor: ...
def hardsigmoid(input: Tensor, *, out: Optional[Tensor] = None) -> Tensor: ...
def hardsigmoid_(input: Tensor) -> Tensor: ...
def hardswish(input: Tensor, *, out: Optional[Tensor] = None) -> Tensor: ...
def hardswish_(input: Tensor) -> Tensor: ...
def hardtanh(input: Tensor, min_val: Union[Number, _complex] = -1, max_val: Union[Number, _complex] = 1, *, out: Optional[Tensor] = None) -> Tensor: ...
def hardtanh_(input: Tensor, min_val: Union[Number, _complex] = -1, max_val: Union[Number, _complex] = 1) -> Tensor: ...
def huber_loss(input: Tensor, target: Tensor, reduction: _int = 1, delta: _float = 1.0, *, out: Optional[Tensor] = None) -> Tensor: ...
def im2col(input: Tensor, kernel_size: Union[_int, _size], dilation: Union[_int, _size], padding: Union[_int, _size], stride: Union[_int, _size], *, out: Optional[Tensor] = None) -> Tensor: ...
def l1_loss(input: Tensor, target: Tensor, reduction: _int = 1) -> Tensor: ...
def leaky_relu(input: Tensor, negative_slope: Union[Number, _complex] = 0.01, *, out: Optional[Tensor] = None) -> Tensor: ...
def leaky_relu_(input: Tensor, negative_slope: Union[Number, _complex] = 0.01) -> Tensor: ...
def linear(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
def log_sigmoid(input: Tensor, *, out: Optional[Tensor] = None) -> Tensor: ...
def max_pool2d_with_indices(input: Tensor, kernel_size: Union[_int, _size], stride: Union[_int, _size] = (), padding: Union[_int, _size] = 0, dilation: Union[_int, _size] = 1, ceil_mode: _bool = False, *, out: Union[Tensor, Tuple[Tensor, ...], List[Tensor], None] = None) -> Tuple[Tensor, Tensor]: ...
def max_pool3d_with_indices(input: Tensor, kernel_size: Union[_int, _size], stride: Union[_int, _size] = (), padding: Union[_int, _size] = 0, dilation: Union[_int, _size] = 1, ceil_mode: _bool = False, *, out: Union[Tensor, Tuple[Tensor, ...], List[Tensor], None] = None) -> Tuple[Tensor, Tensor]: ...
def max_unpool2d(input: Tensor, indices: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], *, out: Optional[Tensor] = None) -> Tensor: ...
def max_unpool3d(input: Tensor, indices: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], stride: Union[_int, _size], padding: Union[_int, _size], *, out: Optional[Tensor] = None) -> Tensor: ...
def mish(input: Tensor, *, out: Optional[Tensor] = None) -> Tensor: ...
def mish_(input: Tensor) -> Tensor: ...
def mkldnn_linear(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None) -> Tensor: ...
def mkldnn_reorder_conv2d_weight(input: Tensor, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 0, stride: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1, dilation: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1, groups: Union[_int, SymInt] = 1, input_size: Optional[Sequence[Union[_int, SymInt]]] = None) -> Tensor: ...
def mkldnn_reorder_conv3d_weight(input: Tensor, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 0, stride: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1, dilation: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1, groups: Union[_int, SymInt] = 1, input_size: Optional[Sequence[Union[_int, SymInt]]] = None) -> Tensor: ...
def mse_loss(input: Tensor, target: Tensor, reduction: _int = 1, *, out: Optional[Tensor] = None) -> Tensor: ...
def multi_margin_loss(input: Tensor, target: Tensor, p: Union[Number, _complex] = 1, margin: Union[Number, _complex] = 1, weight: Optional[Tensor] = None, reduction: _int = 1, *, out: Optional[Tensor] = None) -> Tensor: ...
def multilabel_margin_loss(input: Tensor, target: Tensor, reduction: _int = 1, *, out: Optional[Tensor] = None) -> Tensor: ...
def nll_loss(input: Tensor, target: Tensor, weight: Optional[Tensor] = None, reduction: _int = 1, ignore_index: Union[_int, SymInt] = -100, *, out: Optional[Tensor] = None) -> Tensor: ...
def nll_loss2d(input: Tensor, target: Tensor, weight: Optional[Tensor] = None, reduction: _int = 1, ignore_index: Union[_int, SymInt] = -100, *, out: Optional[Tensor] = None) -> Tensor: ...
def nll_loss_nd(input: Tensor, target: Tensor, weight: Optional[Tensor] = None, reduction: _int = 1, ignore_index: Union[_int, SymInt] = -100) -> Tensor: ...
def one_hot(input: Tensor, num_classes: _int = -1) -> Tensor: ...
def pad(input: Tensor, pad: Sequence[Union[_int, SymInt]], mode: str = "constant", value: Optional[_float] = None) -> Tensor: ...
def pad_sequence(sequences: Union[Tuple[Tensor, ...], List[Tensor]], batch_first: _bool = False, padding_value: _float = 0.0, padding_side: str = "right") -> Tensor: ...
def reflection_pad1d(input: Tensor, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], *, out: Optional[Tensor] = None) -> Tensor: ...
def reflection_pad2d(input: Tensor, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], *, out: Optional[Tensor] = None) -> Tensor: ...
def reflection_pad3d(input: Tensor, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], *, out: Optional[Tensor] = None) -> Tensor: ...
def relu6(input: Tensor) -> Tensor: ...
def relu6_(input: Tensor) -> Tensor: ...
def replication_pad1d(input: Tensor, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], *, out: Optional[Tensor] = None) -> Tensor: ...
def replication_pad2d(input: Tensor, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], *, out: Optional[Tensor] = None) -> Tensor: ...
def replication_pad3d(input: Tensor, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], *, out: Optional[Tensor] = None) -> Tensor: ...
def rrelu_with_noise(input: Tensor, noise: Tensor, lower: Union[Number, _complex] = 0.125, upper: Union[Number, _complex] = ..., training: _bool = False, generator: Optional[Generator] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
def rrelu_with_noise_(input: Tensor, noise: Tensor, lower: Union[Number, _complex] = 0.125, upper: Union[Number, _complex] = ..., training: _bool = False, generator: Optional[Generator] = None) -> Tensor: ...
def scaled_dot_product_attention(query: Tensor, key: Tensor, value: Tensor, attn_mask: Optional[Tensor] = None, dropout_p: _float = 0.0, is_causal: _bool = False, *, scale: Optional[_float] = None, enable_gqa: _bool = False) -> Tensor: ...
def silu(input: Tensor, *, out: Optional[Tensor] = None) -> Tensor: ...
def silu_(input: Tensor) -> Tensor: ...
def slow_conv3d(input: Tensor, weight: Tensor, kernel_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], bias: Optional[Tensor] = None, stride: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 0, *, out: Optional[Tensor] = None) -> Tensor: ...
def slow_conv_dilated2d(input: Tensor, weight: Tensor, kernel_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], bias: Optional[Tensor] = None, stride: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 0, dilation: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1) -> Tensor: ...
def slow_conv_dilated3d(input: Tensor, weight: Tensor, kernel_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], bias: Optional[Tensor] = None, stride: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 0, dilation: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1) -> Tensor: ...
def slow_conv_transpose2d(input: Tensor, weight: Tensor, kernel_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], bias: Optional[Tensor] = None, stride: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 0, output_padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 0, dilation: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1, *, out: Optional[Tensor] = None) -> Tensor: ...
def slow_conv_transpose3d(input: Tensor, weight: Tensor, kernel_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], bias: Optional[Tensor] = None, stride: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 0, output_padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 0, dilation: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1, *, out: Optional[Tensor] = None) -> Tensor: ...
def smooth_l1_loss(input: Tensor, target: Tensor, reduction: _int = 1, beta: _float = 1.0, *, out: Optional[Tensor] = None) -> Tensor: ...
def soft_margin_loss(input: Tensor, target: Tensor, reduction: _int = 1, *, out: Optional[Tensor] = None) -> Tensor: ...
def softplus(input: Tensor, beta: Union[Number, _complex] = 1, threshold: Union[Number, _complex] = 20, *, out: Optional[Tensor] = None) -> Tensor: ...
def softshrink(input: Tensor, lambd: Union[Number, _complex] = 0.5, *, out: Optional[Tensor] = None) -> Tensor: ...
def thnn_conv2d(input: Tensor, weight: Tensor, kernel_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], bias: Optional[Tensor] = None, stride: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 1, padding: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]] = 0, *, out: Optional[Tensor] = None) -> Tensor: ...
def unflatten_dense_tensors(flat: Tensor, tensors: Union[Tuple[Tensor, ...], List[Tensor]]) -> Tuple[Tensor, ...]: ...
@overload
def upsample_bicubic2d(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], align_corners: _bool, scales_h: Optional[_float] = None, scales_w: Optional[_float] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
@overload
def upsample_bicubic2d(input: Tensor, output_size: Optional[Sequence[Union[_int, SymInt]]], align_corners: _bool, scale_factors: Optional[Sequence[_float]]) -> Tensor: ...
@overload
def upsample_bilinear2d(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], align_corners: _bool, scales_h: Optional[_float] = None, scales_w: Optional[_float] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
@overload
def upsample_bilinear2d(input: Tensor, output_size: Optional[Sequence[Union[_int, SymInt]]], align_corners: _bool, scale_factors: Optional[Sequence[_float]]) -> Tensor: ...
@overload
def upsample_linear1d(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], align_corners: _bool, scales: Optional[_float] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
@overload
def upsample_linear1d(input: Tensor, output_size: Optional[Sequence[Union[_int, SymInt]]], align_corners: _bool, scale_factors: Optional[Sequence[_float]]) -> Tensor: ...
@overload
def upsample_nearest1d(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], scales: Optional[_float] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
@overload
def upsample_nearest1d(input: Tensor, output_size: Optional[Sequence[Union[_int, SymInt]]], scale_factors: Optional[Sequence[_float]]) -> Tensor: ...
@overload
def upsample_nearest2d(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], scales_h: Optional[_float] = None, scales_w: Optional[_float] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
@overload
def upsample_nearest2d(input: Tensor, output_size: Optional[Sequence[Union[_int, SymInt]]], scale_factors: Optional[Sequence[_float]]) -> Tensor: ...
@overload
def upsample_nearest3d(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], scales_d: Optional[_float] = None, scales_h: Optional[_float] = None, scales_w: Optional[_float] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
@overload
def upsample_nearest3d(input: Tensor, output_size: Optional[Sequence[Union[_int, SymInt]]], scale_factors: Optional[Sequence[_float]]) -> Tensor: ...
@overload
def upsample_trilinear3d(input: Tensor, output_size: Union[Union[_int, SymInt], Sequence[Union[_int, SymInt]]], align_corners: _bool, scales_d: Optional[_float] = None, scales_h: Optional[_float] = None, scales_w: Optional[_float] = None, *, out: Optional[Tensor] = None) -> Tensor: ...
@overload
def upsample_trilinear3d(input: Tensor, output_size: Optional[Sequence[Union[_int, SymInt]]], align_corners: _bool, scale_factors: Optional[Sequence[_float]]) -> Tensor: ...
```

Please let me know if you'd like me to filter the exposed functions. This is also my first PR that calls on other code in PyTorch so please let me know if I need to change anything else :).

**Comment by ezyang** [comment]
I still need to review but go ahead and delete the dead stubs

**Comment by EmmettBicker** [comment]
Done! Removed `gen_nn_functional` and `get_max_pool_dispatch`. `get_max_pool_dispatch` was only called in gen_nn_functional.

**Comment by EmmettBicker** [comment]
I also was reviewing the manual additions in the _nn.pyi.in file that I deleted and _parse_to and mkldnn_prelu were not included in the automatic generation. I couldn't find these two methods in native_functions.yaml tags.yaml or deprecated.yaml, and while I could find _parse_to in python_nn_functions.cpp, mkldnn_prelu is not there. I tried to torch._C._nn.mkldnn_prelu but I got an error so I removed it from the generated code. I'd be curious to know where _parse_to came from though

**Comment by EmmettBicker** [comment]
I'm going to draft-ify this one and come back later! I just don't know why these errors are occurring and I'm currently focusing on a different PR chain.

**Pull request closed without merging**
