### PR TITLE
Add backward() to Tensor and Variable

### PR DESCRIPTION
**Pull request by goldsborough**
Reposting #7750 because it got reverted due to some Windows issues. The code has already been reviewed and approved. Waiting for Windows tests to pass.

### CODE REVIEW

**Comment by goldsborough** [comment]
This Windows issue is complete bs. It's complaining about `OptionalBase<T>` not being a base class of `optional`, even though `optional` inherits from `OptionalBase<T>`. It's invoking this constructor https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/optional.h#L344 

@peterjc123 could you poke around to see what might be the issue here?

**Comment by peterjc123** [comment]
@goldsborough Hi, I just skimmed the code and the build log and thought that there should some reasons that the errors only occur on the CUDA source files in ATen. My guess is that something else called `OptionalBase` get used in the build phase of the CUDA files of ATen. So there may be two probable fix:
1. Protect `OptionalBase` with a namespace.
2. Detect the other `OptionalBase` and `undef` it.

**Comment by ezyang** [comment]
@cpuhrsch or @yf225  was it you that noticed that on Windows, our implementation of `optional` isn't always understood correctly by MSVC? We are pretty sure MSVC (or maybe MSVC + CUDA?) has a compiler bug that causes it to not handle optional correctly in some cases.

**Comment by peterjc123** [comment]
@ezyang But even there is really a bug, there is so few options that we can choose. The first one is to update the MSVC compiler, but CUDA 9 only works well with v19.11. That is to say, there's only one version we can try (Build Tools 19.11.25547, VS 15.4.5). The second one is to count the problem on the CUDA side. But I don't think it's a good idea to throw away support for CUDA 9.

**Review by apaszke — APPROVED** [review]

**Pull request merged**
