### PR TITLE
Add prims.clone

### PR DESCRIPTION
**Pull request by IvanYashchuk**
This simple PR adds `clone` as a primitive.
Current implementation of `clone` is not supported with nvFuser executor because of `empty_like` + `copy_to`.

### CODE REVIEW

**Comment by IvanYashchuk** [comment]
Is it okay to make `clone` a primitive?

**Review by mruberry — APPROVED** [review]
Making clone a prim makes sense, we should probably target the prims to being functional

Are the test failures related?

**Comment by IvanYashchuk** [comment]
```
=================================== FAILURES ===================================
_____ TestFakeTensorCUDA.test_fake_crossref_backward_amp_roll_cuda_float32 _____
Unexpected success
```
```
ERROR [0.169s]: test_make_fx_symbolic_exhaustive_matmul_cpu_float32 (__main__.TestProxyTensorOpInfoCPU)
ValueError: Cannot view a tensor with shape torch.Size([t1.size(0), t1.size(0), t0.size(0)]) and strides (t1.stride(0), 1, t1.size(0)) as a tensor with shape (t1.size(0)**2, t0.size(0))!
```

**Pull request closed without merging**
