### PR TITLE
[PyTorch] Bypass dispatch for narrow() calls within split_with_sizes

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #83213

This can add up to a lot of dispatcher overhead if there are a lot of splits. split_with_sizes already has an autograd formula so this should Just Work?

Differential Revision: [D38600576](https://our.internmc.facebook.com/intern/diff/D38600576/)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM
Any benchmark on the impact of this change?

**Comment by swolchok** [comment]
> Any benchmark on the impact of this change?

nope, don't have one; I'm not set up to re-run the profile I was shown where this appeared to be an issue

**Comment by drisspg** [comment]
@albanD this pr broke: https://github.com/pytorch/pytorch/pull/83736 since by avoiding the dispatcher we can no longer call slice_nested. If we can update #83736 to also do the manual dispatch

**Pull request closed without merging**
