### PR TITLE
All zero sparse tensors are always coalesced

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #82085

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by nikitaved — APPROVED** [review]
Makes sense!

**Comment by nikitaved** [comment]
We have similar issue with empty sparse tensors:

```python
In [1]: import torch

In [2]: torch.rand(2, 0, 3).to_sparse().is_coalesced()
Out[2]: False

```

**Comment by vadimkantorov** [comment]
zero uncoalesced is (5) from https://github.com/pytorch/pytorch/issues/73479. will this PR solve it?

also empty uncoalesced is also discussed in that issue

**Comment by nikitaved** [comment]
@vadimkantorov , I think it should resolve that. We do not have a unified framework to handle empty/zero-likes for ops that support sparse inputs yet. There might be other ops suffering from it, but it sure will get better :)

**Comment by ezyang** [comment]
I think most of the non-serialization related issues in Vadim's issue are easy to fix, someone should fix them

**Review by cpuhrsch — APPROVED** [review]

**Comment by vadimkantorov** [comment]
@ezyang Could you please try my testcases for zeros / zeros_like from that issue?

**Comment by ezyang** [comment]
Looks like only B is fixed.

**Pull request closed without merging**
