### PR TITLE
[BE] Update cutlass with NVIDIA upstream changes to 3.1

### PR DESCRIPTION
**Pull request by Skylion007**
Updates cutlass with some more upstream changes that went into the 3.1 rc. We already merged in 3.1 so best to get these performance and other fixes into master as well. Follow up to #94188

### CODE REVIEW

**Comment by Skylion007** [comment]
Current failures seem unrelated to this change.

**Review by ezyang — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
