### PR TITLE
support optional comparisons with different but comparable types

### LINKED ISSUE #62565: support comparisons between `c10::optional<T>` and types `U` where `T` is comparable to `U`
## 🚀 Feature
Support comparisons between `c10::optional<T>` and `U` if `T` is comparable to `U`.

## Motivation

A very common use-case for this is:
```
c10::optional<std::string> opt = ...;
if (opt == "blah") ...
```

Note that this is supported by `std::optional`. See https://en.cppreference.com/w/cpp/utility/optional/operator_cmp
under

> Compare an optional object with a value

## Pitch

Add support and testing for these additional overloads. These are expected to just replace the operators that look like:
```
template <typename T>
bool operator==(std::optional<T> const& opt, T const& val);
```
with
```
template <typename T, typename U>
bool operator==(std::optional<T> const& opt, U const& val);
```

## Alternatives

This makes the library more expressive. The alternative with existing functionality is `if (opt && *opt == "blah") ...`.

## Additional context

This is not expected to be a significant amount of work (< one day).

### PR DESCRIPTION
**Pull request by dagitses**
Fixes #62565

### CODE REVIEW

**Comment by mruberry** [comment]
@ezyang would you review or recommend a reviewer for this PR?

**Comment by ezyang** [comment]
For reference gcc implementations of these methods:

```


template<typename _Tp, typename _Up>
--
constexpr auto
operator==(const optional<_Tp>& __lhs, const optional<_Up>& __rhs)
-> __optional_relop_t<decltype(declval<_Tp>() == declval<_Up>())>
{
return static_cast<bool>(__lhs) == static_cast<bool>(__rhs)
&& (!__lhs \|\| *__lhs == *__rhs);
}
 
template<typename _Tp, typename _Up>
constexpr auto
operator!=(const optional<_Tp>& __lhs, const optional<_Up>& __rhs)
-> __optional_relop_t<decltype(declval<_Tp>() != declval<_Up>())>
{
return static_cast<bool>(__lhs) != static_cast<bool>(__rhs)
\|\| (static_cast<bool>(__lhs) && *__lhs != *__rhs);
}
 
template<typename _Tp, typename _Up>
constexpr auto
operator<(const optional<_Tp>& __lhs, const optional<_Up>& __rhs)
-> __optional_relop_t<decltype(declval<_Tp>() < declval<_Up>())>
{
return static_cast<bool>(__rhs) && (!__lhs \|\| *__lhs < *__rhs);
}
 
template<typename _Tp, typename _Up>
constexpr auto
operator>(const optional<_Tp>& __lhs, const optional<_Up>& __rhs)
-> __optional_relop_t<decltype(declval<_Tp>() > declval<_Up>())>
{
return static_cast<bool>(__lhs) && (!__rhs \|\| *__lhs > *__rhs);
}
 
template<typename _Tp, typename _Up>
constexpr auto
operator<=(const optional<_Tp>& __lhs, const optional<_Up>& __rhs)
-> __optional_relop_t<decltype(declval<_Tp>() <= declval<_Up>())>
{
return !__lhs \|\| (static_cast<bool>(__rhs) && *__lhs <= *__rhs);
}
 
template<typename _Tp, typename _Up>
constexpr auto
operator>=(const optional<_Tp>& __lhs, const optional<_Up>& __rhs)
-> __optional_relop_t<decltype(declval<_Tp>() >= declval<_Up>())>
{
return !__rhs \|\| (static_cast<bool>(__lhs) && *__lhs >= *__rhs);
}


```

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
@dagitses you should consider using ghstack, this will take care of managing stacks of PRs, and will also enable use of ghimport, which will allow you to actually import these PRs to fbcode (as they are currently written, you will have to import the PRs one by one after the parents get merged)

**Comment by dagitses** [comment]
> @dagitses you should consider using ghstack, this will take care of managing stacks of PRs, and will also enable use of ghimport, which will allow you to actually import these PRs to fbcode (as they are currently written, you will have to import the PRs one by one after the parents get merged)

definitely. i tried that as part of onboarding (it's a task to do!) but I wanted to try by hand for comparison. I much prefer ghstack now that I've compared.

**Pull request closed without merging**
