### PR TITLE
[Clang-tidy header][15/N] Enable clang-tidy on headers in c10/cuda and c10/mobile

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by jeanschmidt** [comment]
I am investigating the breakage of `pull / linux-focal-cuda12.1-py3.10-gcc9-sm86 / test` on main. I suspect that the origin is not the PR itself, but instead how tests are grouped in chunks. Reaching out to the respective team.

**Pull request closed without merging**
