### PR TITLE
Print system info as part of EC2 info step

### PR DESCRIPTION
**Pull request by malfet**
Makes it easier to debug regressions reported in https://github.com/pytorch/pytorch/issues/71878

### CODE REVIEW

**Review by seemethere — APPROVED** [review]

**Comment by malfet** [comment]
> Merge failed due to Command '['git', '-C', '/home/runner/work/pytorch/pytorch', 'push', 'origin', 'master']' returned non-zero exit status 1.

Hmm, this one is yet another `fatal error in commit_ref`, see https://github.com/pytorch/pytorch/runs/4959231121?check_suite_focus=true

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
