### PR TITLE
Launch bounds on ctc loss backward

### PR DESCRIPTION
**Pull request by csarofeen**
CTC loss backwards kernel is running out of resources on the GPU for L0. This adds launch bounds to guarantee that at least one block of max size can fit on an SM.

### CODE REVIEW

**Comment by t-vi** [comment]
@csarofeen Thank you! If you excuse my ignorance, do you have a pointer on the relation between limiting the threads in the call and adding the launch bounds? Thanks!

**Comment by csarofeen** [comment]
What do you mean for limiting the threads?
The max number of threads were set here https://github.com/pytorch/pytorch/blob/8333f474a6a5258d5373c8e0c5abe9f17794326e/aten/src/ATen/native/cuda/LossCTC.cu#L511

So all we're doing is letting launch bounds know when compiling the kernel to expect that we need to run either 896 or 1024 threads (depending on template specialization) and that we need to be able to run at least 1 block on an SM. This will limit the number of registers available during compilation so that when we call the kernel we know it will be able to run.

**Comment by t-vi** [comment]
Ah, OK, so what happened is that I checked how many registers the compiler took and adjusted the number of threads. Now the launch bounds actually cause the compiler to "keep my promise" that this number of threads fit by limiting its register use?

**Comment by csarofeen** [comment]
Yes, your understanding is correct.
I didn't look too carefully through the kernel but any idea why it is taking so many registers? I was a bit surprised it didn't fit.

**Comment by t-vi** [comment]
Well the double version doesn't fit, I'm not terribly concerned about that except for gradcheck, but maybe I was too generous in caching things...

**Pull request closed without merging**
