### PR TITLE
Added more descriptive error message for index out of range

### PR DESCRIPTION
**Pull request by Chillee**
https://github.com/pytorch/pytorch/issues/21535

### CODE REVIEW

**Review by jamesr66a — APPROVED** [review]
Thanks!

**Review by jamesr66a — CHANGES_REQUESTED** [review]
Actually, can we change the wording a bit? Since you can specify an arbitrary dimension via `dim`, I think it would be confusing to use the term "rows" here.

**Comment by Chillee** [comment]
`dim` does need to be 0: https://github.com/pytorch/pytorch/pull/21758/files#diff-3ce65206bdc603e1ff340bf3bf6c7514L209

**Review by jamesr66a — APPROVED** [review]
okie dokie

**Pull request closed without merging**
