### PR TITLE
Enable mypy check in torch/_inductor/config.py

### PR DESCRIPTION
**Pull request by fffrog**
Fixes #105230

```shell
$ lintrunner init && lintrunner -a torch/_inductor/config.py
...
ok No lint issues.
Successfully applied all patches.
```

```shell
$ mypy torch/_inductor/config.py
Success: no issues found in 1 source file
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by FFFrog** [comment]
> needs more work

Thank you for your comment.
I will first submit a new PR to fix the `compile_fx.py`, it has blocked the merging of several other PRs.

**Pull request closed without merging**
