### PR TITLE
DO NOT MERGE: try grad_check for pdist

### PR DESCRIPTION
**Pull request by ptrblck**
Try grad check on unmodified pdist to isolate CI failures.

### CODE REVIEW

**Comment by ptrblck** [comment]
@ngimel I've added print statements to debug the failing test for rocm for #31593 and the same error is raised on current master for the backward test:
```
04:51:00 shape (4, 5), device cuda:0, p inf, trans torch.float64
04:51:00 grad.abs().max(): 1.7263168023512692
04:51:00 ok
04:51:00 
04:51:00 ======================================================================
04:51:00 FAIL: test_pdist_norm_cuda (__main__.TestTorchDeviceTypeCUDA)
04:51:00 ----------------------------------------------------------------------
04:51:00 Traceback (most recent call last):
04:51:00   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 681, in wrapper
04:51:00     method(*args, **kwargs)
04:51:00   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 180, in instantiated_test
04:51:00     return test(self, device_arg)
04:51:00   File "test_torch.py", line 10976, in test_pdist_norm
04:51:00     test_pdist_single(shape, device, p, dtype, trans, grad_check=grad_check)
04:51:00   File "test_torch.py", line 10969, in test_pdist_single
04:51:00     self.assertTrue(torch.allclose(x.grad, y.grad))
04:51:00 AssertionError: False is not true
```

Should I skip the test for rocm in #31593 for now and open a new issue?

**Comment by ezyang** [comment]
@ptrblck btw, you can ssh into the circleci machines (click "Rerun with ssh") and directly debug that way

**Comment by ngimel** [comment]
@ezyang rocm builds are on Jenkins, not CircleCI.

**Comment by ngimel** [comment]
cc @iotamudelta for rocm failures existing on master (the added test just tests what should have been working)

**Comment by iotamudelta** [comment]
Couple of questions: 1) will this ever get invoked with launch bounds > 256? This would need to be annotated for ROCm. 2) are any of the parameters depended on warp/wave front size? If so, they would need to be adjusted for ROCm (64) vs CUDA (32).

**Comment by ngimel** [comment]
We should take discussion to #33128

**Pull request closed without merging**
