### PR TITLE
Accelerate ISA detection

### PR DESCRIPTION
**Pull request by EikanWang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #124366

cc @voznesenskym @penguinwu @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by xuhancn** [comment]
@EikanWang Please wait for my PR land: https://github.com/pytorch/pytorch/pull/124045

**Review by jgong5 — APPROVED** [review]
@xuhancn if we use the cpuinfo library, is the ISA detection speed still a concern?

**Comment by xuhancn** [comment]
> @xuhancn if we use the cpuinfo library, is the ISA detection speed still a concern?

The reason of slow is dry-compile, I plan to codecache binary to avoid always dry-compile.

**Comment by xuhancn** [comment]
> > @xuhancn if we use the cpuinfo library, is the ISA detection speed still a concern?
> 
> The reason of slow is dry-compile, I plan to codecache binary to avoid always dry-compile.

dry-compile optimize is here: https://github.com/pytorch/pytorch/pull/124602

**Pull request closed without merging**
