### PR TITLE
[distributions] Fix Independent.rsample() and add more tests

### PR DESCRIPTION
**Pull request by fritzo**
This fixes a typo in `Independent.rsample()` reported by @stepelu. It also adds regression tests and fixes a couple shape bugs surfaced in the new tests.

### CODE REVIEW

**Comment by fritzo** [comment]
cc @apaszke @stepelu

**Review by apaszke — APPROVED** [review]

**Comment by apaszke** [comment]
@gchanan @soumith any chance we can get this into 0.4?

**Comment by fritzo** [comment]
apologies for the last minute bug fix!

**Comment by soumith** [comment]
@apazke if you push it to v0.4.0 branch, sure

**Comment by fritzo** [comment]
Thanks, @apaszke!

**Pull request merged**
