### PR TITLE
torch.unique with dim: NumPy compatible sorting

### PR DESCRIPTION
**Pull request by nikitaved**
Fixes https://github.com/pytorch/pytorch/issues/101681. The change `transpose -> moveaxis` was sufficient.
Not only does it make the output similar to NumPy, it also preserves lexicographical sorting order along selected dimensions.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #101693

cc @ezyang @gchanan

### CODE REVIEW

**Comment by nikitaved** [comment]
@rgommers , @lezcano mentioned that you might be interested in this one to be fixed. Are you aware of more NumPy incompat issues we could have a look at?

**Comment by lezcano** [comment]
You have https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen++label%3A%22module%3A+python+array+api%22+, but they are fairly low prio as it stands.

**Comment by rgommers** [comment]
Thanks for asking! This kind of PR is great. My understanding is indeed that a lot of the remaining incompatibilities are low-prio because they're either niche functionality or too much effort right now. I'll have a look at the list to see if there's things that would have a good return-on-effort-invested ratio - will post them on a more appropriate tracking issue.

**Comment by ngimel** [comment]
Needs a bc-breaking note?

**Review by ngimel — APPROVED** [review]

**Comment by nikitaved** [comment]
@ngimel , is it safe to merge? Any extra steps?

**Comment by ngimel** [comment]
I think we can try merging, yes

**Pull request closed without merging**
