### PR TITLE
Add c10::optional to type syntax

### LINKED ISSUE #9513: [jit] support at::optional
Currently we can't use `at::optional` in input argument of a native function. I am aware of some on-going work for this which plans to trace `None` numeric types as `nan`. IMO, this isn't ideal because:
1. `nan` is a perfect valid input, and we can't differentiate python input `None` from `math.nan`.
2. `nan` doesn't make sense for integral types.
3. what about other types like `at::optional<std::string>`?

### PR DESCRIPTION
**Pull request by wanchaol**
This PR adds optional type to ATen native, autograd, JIT schema and Python Arg parser, closes #9513. It allows us to use optional default values (including None) for function signature and implementations like clamp, etc., and also let us remove the python_default_init hack. 

Follow up: 

remove python_default_init completely.

### CODE REVIEW

**Review by zdevito — APPROVED** [review]
Looks good! I have only minor nits.

**Review by goldsborough — APPROVED** [review]
Looks good

**Pull request closed without merging**
