### PR TITLE
[functorch] test for compiling functorch transforms

### PR DESCRIPTION
**Pull request by kshitij12345**
Add a basic test to make sure functorch-torch.compile works as expected.

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]

**Comment by kshitij12345** [comment]
@atalman do you have more context around the failure. Thanks!

**Comment by zou3519** [comment]
So two things happened:
1. we needed to update the internal build system because common_utils was not set up correctly
2. the new tests trigger UBSAN failures internally. It is likely that nothing is actually wrong and we just need to skip the new tests with IS_FBCODE.

I can handle the re-land of this PR

**Comment by kshitij12345** [comment]
Thanks @zou3519 !

**Pull request closed without merging**
