### PR TITLE
[PyTorch] Add tests for empty tensors w/storage null data_ptr

### PR DESCRIPTION
**Pull request by swolchok**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #101426

Further investigation seems to show that changing this behavior (making empty tensors sometimes have non-null data_ptr) was the real problem with #98090 . Adding tests to lock down this behavior so we don't change it by accident again.

Differential Revision: [D45873002](https://our.internmc.facebook.com/intern/diff/D45873002/)

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]
This SGTM as a stop-gap test for what is going on in the sev, but in the long term we probably want to think about if the existing behavior makes sense.

I personally would have expected the data-ptr of a zero-dim slice of a Tensor to be non-zero (which is what happened after we landed https://github.com/pytorch/pytorch/pull/98090)

**Comment by swolchok** [comment]
> This SGTM as a stop-gap test for what is going on in the sev, but in the long term we probably want to think about if the existing behavior makes sense.

IMO there isn't a lot of value in exposing a raw pointer to Python as an integer so I'd be curious to know why Tensor.data_ptr even exists. Given that it does exist, I don't see how we can change the behavior -- it is what it is, the entire world could depend on it, and so it would be bc-breaking to change.

**Pull request closed without merging**
