### PR TITLE
[pytorch] generate op dependency graph as python code

### PR DESCRIPTION
**Pull request by ljk53**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#30866 [pytorch] generate op dependency graph as python code**
* #30937 [pytorch] integrate op dependency analysis process into CI
* #31215 [pytorch][ci] add LLVM-dev package to android docker image

Summary:
Add support to print op dependence as python code so that both custom
build script and BUCK can import it without yaml parser.

Test Plan:
- generate the file:
```
ANALYZE_TORCH=1 FORMAT=py DEPLOY=1 tools/code_analyzer/build.sh -closure=false
```

- load the file in python:
```
python
>>> from build_code_analyzer.torch_deps import TORCH_DEPS
>>> print(TORCH_DEPS)
```

Differential Revision: [D18894639](https://our.internmc.facebook.com/intern/diff/D18894639)

### CODE REVIEW

**Comment by ezyang** [comment]
Is the reason this is inconvenient to directly build in CI because of the LLVM dependency?

**Comment by ljk53** [comment]
> Is the reason this is inconvenient to directly build in CI because of the LLVM dependency?

- About CI integration:
I started integrating op dependency analysis to CI with #30937. I tried existing docker images, none of them have llvm-*-dev package. Seems we introduced the "LLVMDEV" flag to install the dev version of LLVM when building the docker. I will add it to one of the images and can probably use your help to create the new image :>
The current workaround on that PR is to install on-the-fly - I saw XLA builds are doing similar thing...
I'm not sure how stable this is going to be - is there a way to mark it as experimental / flaky so people won't be blocked by its failure?

- About check-in the generated file:
The output of the analysis will be used to control codegen and then we will do another round of 'real' build to produce target binaries (for android/iOS). I thought about it - maybe it's possible to merge the two rounds into one as Android NDK/iOS both have clang/llvm but it's nontrivial additional effort. If we do them in serial it will double build time.
Checking in generated file will also make things much easier for internal build and external users.

- How should we update the generated file?
I discussed with @dreiss - there is some internal tool to generate diff automatically based on code change and we can have mobile on-call regularly accept/land these diffs (and synced to OSS repo). Do you know if there is better way to do this differently with OSS CI?

**Comment by ezyang** [comment]
> I discussed with @dreiss - there is some internal tool to generate diff automatically based on code change and we can have mobile on-call regularly accept/land these diffs (and synced to OSS repo). Do you know if there is better way to do this differently with OSS CI?

The alternative is to force every developer to keep things up to date (which is what would happen if you made the CI job fail if the checked in copy and the generated copy didn't line up). This might be the right thing to do, but then it needs to be easy for developers to generate the correct version, which means there needs to be clear instructions for how to generate the op dependency graph.

You could also store the generated graph out of band (i.e., not in source control) and just regularly update it as part of master job. This would also alleviate some of my concerns about checking in a big generated file; we've had bad experiences with this in the past as it generates a lot of merge conflicts, especially if you ever want to change the format of the generated file.

**Comment by ljk53** [comment]
> > I discussed with @dreiss - there is some internal tool to generate diff automatically based on code change and we can have mobile on-call regularly accept/land these diffs (and synced to OSS repo). Do you know if there is better way to do this differently with OSS CI?
> 
> The alternative is to force every developer to keep things up to date (which is what would happen if you made the CI job fail if the checked in copy and the generated copy didn't line up). This might be the right thing to do, but then it needs to be easy for developers to generate the correct version, which means there needs to be clear instructions for how to generate the op dependency graph.
> 
> You could also store the generated graph out of band (i.e., not in source control) and just regularly update it as part of master job. This would also alleviate some of my concerns about checking in a big generated file; we've had bad experiences with this in the past as it generates a lot of merge conflicts, especially if you ever want to change the format of the generated file.

I feel that Asking every developer to update the graph is probably too much overhead. And synchronously updating it with each PR will likely cause the merge conflicts issue as you pointed out. Having a single source to asynchronously update the generated file can avoid merge conflicts - the downside is master and generated file might be out-of-sync within a short time window.

For internal BUCK build the generated file is better checked-in. For OSS we can put it to nightly/release build package. So alternatively I could upload generated file as separate artifacts for OSS, and we can have a separate job to check in the artifacts to internal source tree for BUCK build. Does this sound like a better alternative?

**Comment by dreiss** [comment]
Sounds fine to me.

**Comment by ezyang** [comment]
yes seems reasonable

**Comment by ljk53** [comment]
@ezyang I've removed generated file from this PR - can you please help review again?

**Review by ezyang — APPROVED** [review]

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit bb1c948a:


**None of the build failures appear to be your fault**.

* **1/1** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=ed5cd0d7429651fd534edc04567d890cfb5eec0d&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base ed5cd0d7 since Jan 02
  <details>
  <summary>
  You may want to rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch origin viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=bb1c948ac28d6518b9afdf608ace0a5292ee70ce).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [pytorch_macos_10_13_py3_test](https://dr.pytorch.org/build-details.html?build_id=79543821) from Jan 02



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Pull request closed without merging**
