### PR TITLE
[Intel GPU] format XPU oneDNN integration codes

### PR DESCRIPTION
**Pull request by ZhiweiYan-96**
# Motivation
This PR add XPU oneDNN integration codes into lintrunner config `.lintrunner.toml`, which would format cpp source and cpp headers codes at `aten/src/ATen/native/mkldnn/xpu/` and `aten/src/ATen/native/mkldnn/xpu/detail/`

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #139578
* #133080
* #139580
* __->__ #139721

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by guangyey — APPROVED** [review]

**Comment by cyyever** [comment]
Lots of formatting are required.

**Comment by guangyey** [comment]
> Lots of formatting are required.

Thanks, I will re-request your review when this PR is done.

**Review by cyyever — APPROVED** [review]

**Review by EikanWang — APPROVED** [review]

**Comment by EikanWang** [comment]
By the way, @guangyey , pls. add all Intel GPU runtime related code to the lint runner.

**Review by Skylion007 — APPROVED** [review]

**Comment by EikanWang** [comment]
Pls. ensure the ci signal is green

**Comment by ZhiweiYan-96** [comment]
@etaf  is handling this CI issue. I would rebase the PR once the issue fixed.

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
