### PR TITLE
integrate the new event with pytorch

### PR DESCRIPTION
**Pull request by fenypatel99**
Test Plan: This is a no-op diff

Differential Revision: D45698169

### CODE REVIEW

**Comment by openrichardfb** [comment]
As the first diff you go github Pytorch, you might need one of the reviewers (e.g., @albanD ) to help you with triggering the CI jobs to run. So maybe request Alban in internal chat to request him do a review please?

**Review by aaronenyeshi — APPROVED** [review]
LGTM!

**Pull request closed without merging**
