### PR TITLE
[fixing reduction kernel launch]

### PR DESCRIPTION
**Pull request by jjsjann123**
1. Fix out of range memory access for reduction on all dimensions for non-packed
tensor.

2. Enabling launch config that maps block width to reduction on fastest striding
dimension. This mapping was previously only active when reducing on fastest
striding dimension of packed tensor, which is not necessary.

### CODE REVIEW

**Comment by jjsjann123** [comment]
cc @zdevito @ngimel

**Comment by jerryzh168** [comment]
@jjsjann123 feel free to request review

**Comment by jjsjann123** [comment]
Looks like bunch of tests failed here.
Let me get a clean rebuild and run the test locally to see if I can get some better hint.

**Review by zdevito — APPROVED** [review]
Looks good. Ill land when the tests pass.

**Comment by jjsjann123** [comment]
I don't have a local repro on circleci failure `RuntimeError: NCCL error in: /var/lib/jenkins/workspace/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled system error`

build failure looks strange as well. I don't think I have messed up history :/

**Comment by zhangguanheng66** [comment]
@zdevito Could you land this PR? Thanks.

**Pull request closed without merging**
