### PR TITLE
[NNC] support aten::_convolution when it is 2D conv

### PR DESCRIPTION
**Pull request by chunyuan-w**
## Motivation
Currently, only `aten::conv2d` has been supported in NNC. When using `torch.jit.trace`, the node on the graph will be `aten::_convolution`. This PR adds support of `aten::_convolution` node when it corresponds to a 2D convolution.

## Pitch
Support `aten::_convolution` in NNC when we can infer from the parameters that it is a 2D convolution to support models obtained from `torch.jit.trace`.

### CODE REVIEW

**Review by huiguoo — APPROVED** [review]
LGTM!

**Comment by chunyuan-w** [comment]
@huiguoo I've rebased the code to the recent master.

**Pull request closed without merging**
