### PR TITLE
[cuDNN][cuDNN-frontend] Bump cuDNN version in tandem with cudnn-frontend

### PR DESCRIPTION
**Pull request by eqy**
CC @Skylion007 

Checking if this seems to calm things down..,

cc @csarofeen @ptrblck @xwang233

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]
LGTM assuming tests pass.

**Comment by eqy** [comment]
hmm, looks like we probably want to bump the CUDA 11 cuDNN version as wel...

**Comment by eqy** [comment]
Interestingly it looks like the issue may only surface on certain devices (e.g., A10G) in the original PR, as it doesn't seem to be rerproducing on SM80...

**Comment by johnnynunez** [comment]
> CC @Skylion007
> 
> Checking if this seems to calm things down..,
> 
> cc @csarofeen @ptrblck @xwang233

cudnn 9.0 is out and compatible with cuda 12
image

**Review by malfet — APPROVED** [review]
LGTM, but don't you have to do the corresponding update for conda builds (where cudnn is still not available).

Also, please make sure to update versions pypi depends on https://github.com/pytorch/pytorch/blob/c0e5cca4f8be382bc30c5c5a8199ddc12fed85a3/.github/scripts/generate_binary_build_matrix.py#L39

**Comment by malfet** [comment]
@atalman do you mind importing it internally and make sure it will work?
cc: @drisspg who did some cudnn_frontend updates recently

**Comment by drisspg** [comment]
The cudnn-frontend update to 1.0.3 just landed internally yesterday and I am still letting it bake to see if anything comes up, what version does this bump it to?

**Comment by Skylion007** [comment]
> The cudnn-frontend update to 1.0.3 just landed internally yesterday and I am still letting it bake to see if anything comes up, what version does this bump it to?

1.1.0

**Comment by johnnynunez** [comment]
https://github.com/NVIDIA/cudnn-frontend/releases/tag/v1.1.0

**Comment by eqy** [comment]
Closing as we've merged 1.1.1

**Pull request closed without merging**
