### PR TITLE
Nvfuser code removal

### PR DESCRIPTION
**Pull request by jjsjann123**
Removes the existing integration code & build of nvfuser in TorchScript.

Note that I intentionally left the part where we wipe out `third_party/nvfuser` repo. I'll do that in a separate PR.

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Comment by jjsjann123** [comment]
I don't see anything in the failing ROCM CI. I'm guessing it's just noise there.

**Comment by jjsjann123** [comment]
So I think this one is good to go. tagging @davidberard98  :bow:

**Comment by davidberard98** [comment]
@malfet @albanD do we need to do the 2-release-cycle wait before removing nvfuser as a deprecated feature?

**Comment by jjsjann123** [comment]
> @malfet @albanD do we need to do the 2-release-cycle wait before removing nvfuser as a deprecated feature?

Wondering if there's any update on the timeline.
Meanwhile, we are not removing APIs, so it shouldn't break any user code (except the part where we are asserting on some flags, but we can relax that to be just throwing another warning). We can wait for another release-cycle before removing those.

**Comment by albanD** [comment]
I don't think we need to do a full 2-release cycle here no. We can remove it since there are alternatives.

**Review by albanD — APPROVED** [review]
Thanks for taking the time to do this. Looks great!

**Comment by jjsjann123** [comment]
:cry:

**Comment by jjsjann123** [comment]
surprised to see internal build breaking. Is there a separate buck config file that's not in bazel?
Is bazel build still tested on public CI?

**Comment by davidberard98** [comment]
I'll take a look

**Comment by davidberard98** [comment]
@jjsjann123 can you reopen the PR (or create a new one?)

**Comment by jjsjann123** [comment]
> @jjsjann123 can you reopen the PR (or create a new one?)

opened #111604

**Pull request closed without merging**
