### PR TITLE
Enable XLA CI tests

### PR DESCRIPTION
**Pull request by wonjoo-wj**
XLA CI tests has been disabled of https://github.com/pytorch/pytorch/pull/74472.

The faulty PR has been reverted on XLA's end, so we were enabling the XLI tests again.

### CODE REVIEW

**Review by suo — APPROVED** [review]

**Comment by suo** [comment]
Looks like master was broken by this. @pytorchbot revert this

**Comment by suo** [comment]
@pytorchbit revert this

**Comment by suo** [comment]
Cc @malfet would be convenient to have commands work inline so I can comment on revert reason at the same time as reverting.

**Comment by JackCaoG** [comment]
Eh.. master is broken because some offending pytorch pr merged while the xla test is disabled... Let me see if I can quickly fix this.

**Comment by JackCaoG** [comment]
I want to reland this one since I fixed the failure on pt/xla front. @suo Should I just reopen this pr or open a new one.

**Comment by JackCaoG** [comment]
@suo XLA test is passing, can we reland this pr?

**Comment by JackCaoG** [comment]
Close this one in favor of https://github.com/pytorch/pytorch/pull/74756/files

**Pull request closed without merging**
