### PR TITLE
[JIT] Allow cooperative structured objects to be passed modules in tracing

### PR DESCRIPTION
**Pull request by t-vi**
Before this patch, the JIT does not allow Module's forward to take
structured objects.
This patch allows cooperative objects to do so.
Cooperative means:
- It has a method self._jit_unwrap() that returns (a list/tuple of)
  tensors. These are then used in _iter_tensors.
- It has a method self._jit_wrap(flattened_input) that takes
  (a list/tuple?) the flattened_unput (potentially more than it needs)
  and returns itself (updated) and the unconsumed flattened_inputs.
  This is then used in the _unflatten mechanism.

This is all it takes to permit maskrcnn-benchmark to use
its structured BoxList/ImageList types and trace it without calling
the .forward directly.
I'll push a model working with this patch in
https://github.com/facebookresearch/maskrcnn-benchmark/pull/138

I must admit I haven't fully checked whether there are ONNX changes needed before it, too, can profit, but I would be hopeful that anything currently usable remains so.

@fmassa @zdevito 

So the main downside that I'm aware of is that people will later want to use more elaborate mechanisms, but I think this could be done by just amending what wrap/unwrap are returning / consuming.

### CODE REVIEW

**Comment by t-vi** [comment]
So the build-failures are pyflake (I have a commit that fixes that), a timeout during testing and a failure during setup.

**Comment by ezyang** [comment]
I restarted the jobs for you

**Review by zdevito — APPROVED** [review]
Nice! Eventually we will want more first class support (e.g. ability to trace something with custom types and get a wrapper function that takes and returns those types). But for now this will unblock using custom objects at all.

**Comment by soumith** [comment]
rocm test failure is unrelated. landing!

**Pull request closed without merging**
