### PR TITLE
[BE] Make ActivationWrapper an abstract class

### LINKED ISSUE #95481: [BE] Make ActivationWrapper an abstract class
### 🚀 The feature, motivation and pitch

As mentioned in the comments for `ActivationWrapper` in torch.distributed's activation checkpoint code, it is not meant to be instantiated directly, so we should just prevent this via using an abstract class.

### Alternatives

_No response_

### Additional context

_No response_

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

### PR DESCRIPTION
**Pull request by jovianjaison**
Fixes #95481 

Test Plan:
Unit tested checkpoint_wrapper.py by instantizing ActivationWrapper and got TypeError as expected. 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @chauhang @d4l3k

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by awgu** [comment]
> Test Plan:
Unit tested checkpoint_wrapper.py by instantizing ActivationWrapper and got TypeError as expected.

I am okay with the PR, but the test plan in the description does not match the PR (there is no unit test added in this PR).

**Comment by jovianjaison** [comment]
> > Test Plan:
> > Unit tested checkpoint_wrapper.py by instantizing ActivationWrapper and got TypeError as expected.
> 
> I am okay with the PR, but the test plan in the description does not match the PR (there is no unit test added in this PR).

Oh sorry for the ambiguity in the description. What I meant was I added this piece of code in checkpoint_wrapper.py locally, to test my changes and it worked as intended:
try:
    aw = ActivationWrapper(torch.nn.Linear(2, 2))
except TypeError as e:
    print(f"Instantiation failed: {e}")
else:
    print("Instantiation succeeded")

I removed it before pushing the PR since having it here didn't make sense imo.

**Pull request closed without merging**
