### PR TITLE
Fix usage of TORCH_INTERNAL_ASSERT with message 

### PR DESCRIPTION
**Pull request by Flamefire**
Using only a string as the argument for TORCH_INTERNAL_ASSERT will never trigger a failure as a string is always a truethy value.
This hides actual bugs and makes users and devs think all worked while it did not.
Change to use `TORCH_INTERNAL_ASSERT(false, "msg")`

I found this because on PPC (where there is no XNNPACK) one of the tests failed:

```
FAIL: test_preserve_bundled_inputs_methods (__main__.TestOptimizer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mobile_optimizer.py", line 328, in test_preserve_bundled_inputs_methods
    self.assertFalse(hasattr(incomplete_bi_module_optim, 'get_all_bundled_inputs'))
AssertionError: True is not false
```

This happens because the assertion is not fired and the module is returned unchanged: https://github.com/pytorch/pytorch/compare/master...Flamefire:assert_fix?expand=1#diff-5d18cdc66f45034594ef1f12d8ed1e9e21c21ae75fb55eb88713f26e49f8eb74R266

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

### CODE REVIEW

**Review by wanchaol — COMMENTED** [review]
looks good to me, can you rebase and see if those CI failures disappears? thanks

**Comment by Flamefire** [comment]
Rebased

**Comment by wanchaol** [comment]
The failures looks legit though https://app.circleci.com/pipelines/github/pytorch/pytorch/325910/workflows/668c9bc9-f008-4acf-a09c-ddab9aa3fce5/jobs/13647428

**Comment by Flamefire** [comment]
Well in this case assuming that those assertions itself are correct I'd say: It discovered existing bugs which were hidden by the bug fixed here.

I'm not sure how to proceed here as I don't know if that assertion is correct, i.e. that the "training" attribute must exist here.
Can you find the code owner and have them take a look here?

**Comment by kshitij12345** [comment]
@Flamefire Looks like these were fixed in https://github.com/pytorch/pytorch/pull/71711 . There are a couple left as tracked in https://github.com/pytorch/pytorch/issues/71848.

Can you please build from the latest master and check if these tests still fail?

Thank you!

**Pull request closed without merging**
