### PR TITLE
Fixes doc errors in `Tensor.triu()`, `Tensor.tril()`, `Tensor.ravel()`.

### LINKED ISSUE #70972: Error in `Tensor.triu` and `Tensor.tril` documentation
### 📚 The doc issue

In the [documentation](https://pytorch.org/docs/stable/generated/torch.Tensor.triu.html?highlight=triu#torch.Tensor.triu) of `Tensor.triu`, the signature of it is `Tensor.triu(k=0)`. However, when I call this API

```python
import torch
a = torch.rand([2, 2])
a.triu(diagonal = 1)
# succeed
a.triu(k = 1)
# TypeError: triu() got an unexpected keyword argument 'k'
```

So it should be `diagonal` instead of `k`.

`Tensor.tril` has the same problem.

### Suggest a potential alternative/fix

_No response_

### PR DESCRIPTION
**Pull request by khushi-411**
Hi, PyTorch Team!
I am very much interested in starting up my contribution to PyTorch. I made several contributions in NumPy and CuPy, but this is my first PR towards PyTorch. I aim to contribute more in the upcoming future.

The PR fixes #70972  #70975.

#### Aim of PR
The functions like `Tensor.ravel`, `Tensor.tril`, `Tensor.tril_`, `Tensor.triu`, and `Tensor.triu_` had a couple of typos in docs. The PR aims to resolve that.

I'm looking forward to your viewpoints. Thanks!

cc: @kshitij12345 @vadimkantorov @Lezcano @TestSomething22

cc @brianjo @mruberry

### CODE REVIEW

**Review by lezcano — APPROVED** [review]
This is great, thanks!

Related to this, I wrote a small script sometime ago indending to address this issue at amore global level https://github.com/pytorch/pytorch/issues/54881

I never followed through with it, but I still think it'd make for a great project that would fix plenty of these problems in one go. Feel free to have a look at it and take over if you're interested. If you're interested, I'd be happy to help in whichever way I can :)

**Comment by khushi-411** [comment]
Hi, @Lezcano!
Thanks a lot for reviewing the PR and sharing the ongoing issue.

> Related to this, I wrote a small script sometime ago indending to address this issue at amore global level #54881
>
> I never followed through with it, but I still think it'd make for a great project that would fix plenty of these problems in one go. Feel free to have a look at it and take over if you're interested. If you're interested, I'd be happy to help in whichever way I can :)

This is a really fascinating issue. I would love to work on it (: 
Currently, I took a look at a glance will go through it briefly and ping you soon. Thanks (:

**Review by mruberry — APPROVED** [review]
Hey @khushi-411! Welcome to the team. Please let me know if you have any questions and thanks for the fixes.

**Comment by khushi-411** [comment]
Hi, @mruberry! Thank you for welcoming (: Sure, I will ping you. Thank you so much.

**Pull request closed without merging**
