### PR TITLE
Update triton pin to 513f38c4

### PR DESCRIPTION
**Pull request by atalman**
Pinning Triton to 513f38c4 as a candidate for PyTorch release 2.4

### CODE REVIEW

**Comment by amjames** [comment]
#126195 Should resolve the issue with `test_triton_kernel_constants` 

I am working through a fix for the crash related to flex attention. That is real, there is a bug in triton's dematerialization pass that is generating invalid loops.

**Comment by atalman** [comment]
sounds good @amjames  let me know, I can close this PR in favor of your stack, please try to use this pin however in your PR: 513f38c4

**Comment by amjames** [comment]
The fix will have to be landed upstream so I will have to move the pin again anyway.

**Comment by atalman** [comment]
closing this PR in favor of https://github.com/pytorch/pytorch/pull/126098

**Pull request closed without merging**
