### PR TITLE
Remove breakpad dependency

### PR DESCRIPTION
**Pull request by malfet**
This functionality does not seem to be used
and there are some requests to update dependency.

Add `third_party` to torch_cpu include directories if compiling with
Caffe2 support, as `caffe2/quantization/server/conv_dnnlowp_op.cc` depends on `third_party/fbgemm/src/RefImplementations.h`

### CODE REVIEW

**Comment by janeyx99** [comment]
oh hm this seems to be backwards incompatible for workflows (cuz the checkout will try to checkout breakpad)

**Comment by janeyx99** [comment]
lint errors seem legit

**Review by janeyx99 — COMMENTED** [review]
How have you confirmed this functionality isn't used?

**Comment by malfet** [comment]
> How have you confirmed this functionality isn't used?

Functionality were never exposed via a stable API and not a single issue report with a crash contained minidump

**Review by janeyx99 — COMMENTED** [review]
fix lint before landing tho :p

**Review by janeyx99 — APPROVED** [review]

**Review by seemethere — APPROVED** [review]

**Comment by malfet** [comment]
> fix lint before landing tho :p

I'm not sure it's possible, it produces false negatives for deleted files

**Comment by acxz** [comment]
@malfet can you confirm that this PR closes #70298? and if so can you close #70298?

**Pull request closed without merging**
