### PR TITLE
Migrate THCState to ATen

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #66766
* __->__ #66765

This guts `THCState` to simply be an empty struct, as well as:
- moving `THCState_getPeerToPeerAccess` and its cache into `ATen`.
- cleaning up dead code in `THCGeneral.cpp`
- moving `THCudaInit` and `THCMagma_init` into `CUDAHooks::initCUDA`

Differential Revision: [D31721648](https://our.internmc.facebook.com/intern/diff/D31721648)

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
I'm getting the same error in internal builds 
```
c10::Error: detail::magma_init_fnINTERNAL ASSERT FAILED at "caffe2/aten/src/ATen/cuda/detail/CUDAHooks.cpp":75, please report a bug to PyTorch. Cannot initilaize magma, init routine not set
Exception raised from initCUDA at caffe2/aten/src/ATen/cuda/detail/CUDAHooks.cpp:75 (most recent call first):
# 0  c10::get_backtrace[abi:cxx11](unsigned long, unsigned long, bool)
# 1  std::_Function_handler<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (), c10::(anonymous namespace)::GetFetchStackTrace()::$_0>::_M_invoke(std::_Any_data const&)
# 2  c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
# 3  c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
# 4  c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, char const*)
# 5  at::cuda::detail::CUDAHooks::initCUDA() const
# 6  at::Context::lazyInitCUDA()::{lambda()#1}::operator()() const
# 7  __pthread_once_slow
# 8  void std::call_once<at::Context::lazyInitCUDA()::{lambda()#1}>(std::once_flag&, at::Context::lazyInitCUDA()::{lambda()#1}&&)
# 9  at::Context::lazyInitCUDA()
# 10 at::(anonymous namespace)::(anonymous namespace)::wrapper__empty_strided(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)
```
any advice why that would happen?

**Comment by peterbell10** [comment]
That means `AT_MAGMA_ENABLED()` is true but `magma_init_fn` hasn't been set. That must mean the initializer in `cuda/BatchLinearAlgebra.cpp` hasn't run yet. I'm not sure how that could happen though.

The old code just ignored it if this happened, so it's possible this was happening silently before.

**Comment by ngimel** [comment]
I've added prints to verify that initializer in cuda/BatchLinearAlgebra.cpp has run before the initialization is performed in CUDAHooks, and the function is correctly set in the initializer and can be called, but yet in CUDAHooks somehow it is unset again? 
I didn't check if it was properly set before this PR.

**Pull request closed without merging**
