### PR TITLE
If CUDA is not found and USE_CUDA!=0, report error and ask user to set USE_CUDA=0

### PR DESCRIPTION
**Pull request by xuhdev**
Currently we emit a warning and set USE_CUDA=0 in our script by ourselves. Instead, we should report an error and let user do this explicitly, as whether CUDA is used or not would affect so much of PyTorch.

Best viewed with "hide whitespace changes".

Per request by @jithunnair-amd at https://github.com/pytorch/pytorch/pull/23884#discussion_r315944670

### CODE REVIEW

**Comment by ezyang** [comment]
cc @soumith @gchanan

**Comment by gchanan** [comment]
I don't have an opinion on this change, but I don't actually see anyone requesting this.  The request linked, as I understand it, is about having a canonical variable that defines whether we are _actually_ building with CUDA or not.

**Comment by ezyang** [comment]
@gchanan To be clear, this PR is to unblock the AMD patch which doesn't work because the cmake variable is not set appropriately early enough. So there is a use case, but not from end users.

**Comment by xuhdev** [comment]
Since https://github.com/pytorch/builder/pull/345 is resolved, any idea when that will take effect so we can run a retest?

**Comment by gchanan** [comment]
@ezyang I understand, I believe that issue could be resolved in a different way.

**Comment by xuhdev** [comment]
The alternative I can think of would be to run all CUDA detection code before depending options are defined. Given the current status of the CUDA detection code, this might be difficult.

**Comment by jithunnair-amd** [comment]
@gchanan I sense an impasse. Can you please provide some direction, so the RCCL upstreaming PR can move forward (it's waiting on this)?

**Comment by gchanan** [comment]
idk, that seems like a plausible choice.

**Comment by xuhdev** [comment]
Closing now

**Pull request closed without merging**
