### PR TITLE
Migrate Inductor scheduler, dependencies, ir, and codegen/common to use OrderedSet

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #130004

Python's set is non deterministic. There is an internal failure which we recently ran into which did not consistently fail. 

See, repro here: P1453035092.

Now, with these changes, it does consistently fail. In follow ups we could also consider adding a lintrule for uses of either set() or set literals.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by oulgen — APPROVED** [review]

**Comment by oulgen** [comment]
Can you run a nightly perf benchmark to make sure this does not regress compile times

**Comment by eellison** [comment]
Stable on inference and training except for slight timm regression which we should fix wtih algorithmic changes - i'm going to fix tests and land

image

**Pull request closed without merging**
