### PR TITLE
Implement dim_arange operator

### PR DESCRIPTION
**Pull request by jamesr66a**
This is needed to unblock the MT use case. I wanted to call it 'arange_like' but that was getting blocked by a regex in gen_python_functions.py

### CODE REVIEW

**Review by apaszke — DISMISSED** [review]
Can we please make it private? I’m ok with adding temporary hacks like this one, but they shouldn’t affect the public API

**Comment by jamesr66a** [comment]
@apaszke this is meant to be used like `torch.dim_arange(x, dim=0)`. I don't see how making this private is feasible

**Comment by soumith** [comment]
with` _dim_arange`

**Review by ezyang — APPROVED** [review]
@jamesr66a I added a comment explaining the hack. Please confirm that it's accurate and merge at your leisure.

**Review by apaszke — APPROVED** [review]

**Pull request merged**
