### PR TITLE
Prefixing DeviceType with c10 namespace to avoid name collisions

### LINKED ISSUE #91338: Use c10 namespace in public headers for classes like DeviceType (and Device ?)
### 🚀 The feature, motivation and pitch

We have an existing DeviceType class all over the place in our code base, and it conflicts with the one that is used in torch. Thankfully the pytorch DeciceType enum class is under the c10 namespace.

```
In file included from /xxx/build/_deps/torch-src/../../aten/src/ATen/ops/view.h:5:
/xxx/_deps/torch-src/aten/src/ATen/Context.h:265:14: error: reference to 'DeviceType' is ambiguous
    if (p == DeviceType::HIP) {
             ^
/xxx/include/Common_types.h:178:8: note: candidate found by name lookup is 'DeviceType'
struct DeviceType {
       ^
/xxx/build/_deps/torch-src/c10/../c10/core/DeviceType.h:32:12: note: candidate found by name lookup is 'c10::DeviceType'
enum class DeviceType : int8_t {
```

### Alternatives

_No response_

### Additional context

_No response_

cc @jbschlosser @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

### PR DESCRIPTION
**Pull request by anthonyalayo**
Fixes #91338

Follow up from https://github.com/pytorch/pytorch/pull/91342

> 🚀 The feature, motivation and pitch
> We have an existing DeviceType class all over the place in our code base, and it conflicts with the one that is used in torch. > Thankfully the pytorch DeciceType enum class is under the c10 namespace.

```
In file included from /xxx/build/_deps/torch-src/../../aten/src/ATen/ops/view.h:5:
/xxx/_deps/torch-src/aten/src/ATen/Context.h:265:14: error: reference to 'DeviceType' is ambiguous
    if (p == DeviceType::HIP) {
             ^
/xxx/include/Common_types.h:178:8: note: candidate found by name lookup is 'DeviceType'
struct DeviceType {
       ^
/xxx/build/_deps/torch-src/c10/../c10/core/DeviceType.h:32:12: note: candidate found by name lookup is 'c10::DeviceType'
enum class DeviceType : int8_t {
```

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

### CODE REVIEW

**Comment by anthonyalayo** [comment]
@albanD 

> Sounds good. Could you also add a lint entry for this to make sure we don't add new ones. It can be similar to the one below I think:
> 
> https://github.com/pytorch/pytorch/blob/dfb651452a8365a1010c63e7ace01af554ab0358/.lintrunner.toml#L766-L785

**As far as I can tell, a regex isn't possible here.**

1. We want to match on DeviceType, but not match on c10::DeviceType
2. The current grep engine behind the linter doesn't support negative look-behinds
3. I attempted to do it with negative look-aheads,`(?:\s|^)(?!c10::)(DeviceType)`, but this is also not working with the current grep engine.
4. If we want to add support for -p (Perl Compatible Regular Expressions / PCRE), that'll affect the linting of all files and will also most likely break windows and macOS integrations.

https://github.com/pytorch/pytorch/blob/main/tools/linter/adapters/grep_linter.py#L76

The reason why the lint rule `ONCE_FLAG` worked is because we were grep-ing for `std::once_flag` and replacing that with `c10::once_flag`. It has a prefix already, so no complicated regex needed.

**My ask: Can we drop the linting requirement?**

**Comment by anthonyalayo** [comment]
@albanD polite bump, wanted to see if I can move this along.

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

**Comment by anthonyalayo** [comment]
@albanD polite bump here in case this gets missed

**Comment by anthonyalayo** [comment]
@albanD hoping this doesn't go stale, mind chiming in?

**Comment by anthonyalayo** [comment]
@albanD let me know if there's a better medium to reach you with. Hoping to keep this PR from getting stale.

**Review by albanD — COMMENTED** [review]
Hey!
Sorry I was on PTO for the long week end. If it's not possible to do regex, I guess it is fine not to have it.
We can reconvene if we see this breaking too often for you.

**Comment by albanD** [comment]
The lint rule can be removed to make CI green!

Sorry for the delay here!

**Review by albanD — APPROVED** [review]
Thanks!

**Comment by anthonyalayo** [comment]
Thanks a lot, checking out these CI errors

**Comment by anthonyalayo** [comment]
All fixed @albanD , ready for another merge attempt

**Comment by anthonyalayo** [comment]
@albanD mind running your bot merge again?

**Comment by anthonyalayo** [comment]
@albanD agreed, its failing to find gmock in the build. Are you seeing this happening on any other PRs?

**Comment by anthonyalayo** [comment]
@albanD all the other checks finished successfully, what can we do to get it past the finish line?

**Pull request closed without merging**
