### PR TITLE
use OpInfo to verify that LTC report correct shapes (shape formulas) …

### PR DESCRIPTION
**Pull request by Krovatkin**
…before eval

Fixes #{issue number}

### CODE REVIEW

**Comment by wconstab** [comment]
is this going to test all ops?

I am not surprised if there are discrepancies of dtype using the manual IR/bindings.  It's bad that there are segfaults obviously, so that's worth tracking down.  But otoh, we should probably only expect the test to pass consistently for ops in our 'full_codegen' list, since those are the only ops we've sanitized, and all bets are off for the other ones.  I'm guessing the segfault comes from fallback logic?

**Comment by Krovatkin** [comment]
> is this going to test all ops?

OpInfo infra only supports 300+ unique ops 😿  I removed other devices but CPU (`skipped=718`) since it shouldn't matter much for comparing sizes()

```
Ran 1077 tests in 21.116s

OK (skipped=718)

```


>  I'm guessing the segfault comes from fallback logic?

Yes, so far. I didn't disable that test yet to see if there could be more.

> But otoh, we should probably only expect the test to pass consistently for ops in our 'full_codegen' list, since those are the only ops we've sanitized, and all bets are off for the other ones. 

Agreed, although, the fallback path should probably be tested as well.

**Comment by wconstab** [comment]
you may have missed my point.  i agree about testing the fallback path.  but there are 3 categories of ops for the purpose of this test
1) full_codegen - should pass
2) supported - may fail due to xla-specific dtype logic but should not segfault
3) fallback - should pass

**Comment by Krovatkin** [comment]
@wconstab 

Looks like what you were saying is that we don't care about the ops in category 2

> supported - may fail due to xla-specific dtype logic but should not segfault

If so, I totally agree 😺

**Pull request closed without merging**
