### PR TITLE
quantization docstring only formatting changes

### PR DESCRIPTION
**Pull request by gottbrath**
docstring only formatting changes in the quantize.py and fake_quantization.py files to render better in HTML.

### CODE REVIEW

**Comment by gottbrath** [comment]
added a change to observer.py (same kind of docstring indentation issue). 

This fixes  #26834, and helps fix #27428, and #26470, and #26469

**Comment by soumith** [comment]
@gottbrath unfortunately your PR has merge conflicts after I merged https://github.com/pytorch/pytorch/pull/27303

**Comment by gottbrath** [comment]
@soumith  .. i was worried that might happen. Will try to reproduce and resolve.

**Comment by gottbrath** [comment]
ok I am going to close this and replace it with one that won't cause a conflict. thanks for flagging this!

**Pull request closed without merging**
