### PR TITLE
Fix test_init_pg_and_rpc_with_same_socket by retrying on addr in use error

### LINKED ISSUE #66983: DISABLED test_init_pg_and_rpc_with_same_socket (__main__.TCPStoreTest)
Example flaky failure on trunk: https://github.com/pytorch/pytorch/runs/3954935266

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

### PR DESCRIPTION
**Pull request by H-Huang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#67638 Fix test_init_pg_and_rpc_with_same_socket by retrying on addr in use error**

Fixes #66983

There is a possibility that the port retrieved from `find_free_port()` becomes unavailable in the between the time that it is retrieved and used by `init_process_group` and `init_rpc`. Example flaky test failure, https://github.com/pytorch/pytorch/runs/3954935266. Added the `retry_on_connect_failures` (https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_utils.py#L2241-L2266) decorator to retry the function on the `Address already in use` error.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

Differential Revision: [D32074698](https://our.internmc.facebook.com/intern/diff/D32074698)

### CODE REVIEW

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32074698).

**Review by mrshenli — APPROVED** [review]
Do we need `retry_on_connect_failures` for other tests as well?

**Comment by H-Huang** [comment]
Looking into other tests that use `find_free_port()` and will add it if necessary

**Comment by H-Huang** [comment]
@H-Huang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32074698).

**Pull request closed without merging**
