### PR TITLE
[frontend] Fix tensor list alias annotation 

### PR DESCRIPTION
**Pull request by larryliu0820**
For issue https://github.com/pytorch/pytorch/issues/77920 and a retry of https://github.com/pytorch/pytorch/pull/83921

The current logic checks alias info before `[]` and after. If no alias info exists after `[]`, we overwrite the alias info before. This logic failed on argument like `Tensor(a!)[]`, dropping the alias info before `[]` on the floor. This PR adds a new alias info if it's missing after `[]`. This way we can keep the alias info before `[]`.

### CODE REVIEW

**Review by cccclai — APPROVED** [review]
Stamp as it's a retry.

**Review by bdhirsh — APPROVED** [review]

**Pull request closed without merging**
