### PR TITLE
remove import torchvision when testing torch.hub

### PR DESCRIPTION
**Pull request by ailzhang**
This should pass once https://github.com/pytorch/vision/pull/971 is merged. 
To remove torchvision as baseline, we just compare to sum of all param.sum() in pretrained resnet18 model, which means we need to manually update the number only when that pretrained weights are changed, which is generally rare.

### CODE REVIEW

**Review by soumith — APPROVED** [review]

**Comment by ailzhang** [comment]
Lint test failure unrelated. Landing since it only failed windows test in my previous commit and now it passed

**Comment by SsnL** [comment]
Any reason why this reverts https://github.com/pytorch/pytorch/pull/19606? The hub test now again prints like 40% lines of CI log.

**Comment by ailzhang** [comment]
@SsnL  I removed it since the line it tried to suppress was removed. Maybe it's a different place not flushes huge logs? (I know there're some logs in python27 case but that's expected). Would you mind sharing an example?

**Comment by SsnL** [comment]
@ailzhang I have an example in https://github.com/pytorch/pytorch/pull/22043 :)

**Pull request closed without merging**
