### PR TITLE
Add loss operators to fp32 cast policy of AutocastCPU

### PR DESCRIPTION
**Pull request by CaoE**
### Description
Add loss operators to fp32 cast policy of AutocastCPU to improve accuracy of BFloat16 training. There will be no performance impact on fp32, only a slight impact on bf16 training.

#### Remove _convolution
This is because conv transpose does not fully support bf16 before, and it will be replaced to _convolution in graph mode. If _convolution is in lower precision cast policy it will throw dtype related errors.
conv transpose does not fully support bf16 yet, so _convolution still needs to be removed.

### CODE REVIEW

**Comment by malfet** [comment]
please add an explanation to PR description why _convolution is missing here

**Review by malfet — APPROVED** [review]

**Comment by CaoE** [comment]
> please add an explanation to PR description why _convolution is missing here

This is because conv transpose does not fully support bf16 before, and it will be replaced to _convolution in graph mode. If _convolution is in lower precision cast policy it will throw dtype related errors.

**Comment by CaoE** [comment]
> I will check if conv transpose fully supports bf16 now, and if conv transpose fully supports bf16 _convolution will be kept.

conv transpose does not fully support bf16 yet,  so _convolution still needs to be removed.

**Pull request closed without merging**
