### PR TITLE
fix process shutdown crashes with cublas_handle_stream_to_workspace

### PR DESCRIPTION
**Pull request by dagitses**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #85400
* __->__ #85399

Summary:
This was causing crashes in the cuda tests inside Meta.

Test Plan: Already verified this works inside Meta. Rely on OSS CI.

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Review by ngimel — APPROVED** [review]
I didn't like that static from the beginning, but hoped it would be ok

**Comment by eqy** [comment]
Timely. I think this might also fix an issue I was seeing when testing with `CudaMallocAsync`. Is the intent to effectively leak the workspaces at shutdown to avoid crashes when a cleanup is attempted, if so then I believe it would also address the issue I was seeing.

**Comment by eqy** [comment]
I'm not familiar with `ghstack` and its usage with reverted PRs; do I still need to resubmit?

**Comment by ngimel** [comment]
Yes, since the previous PR was reverted, you'd need to resubmit with this fix

**Comment by eqy** [comment]
(referencing #85447 which includes the fixes)

**Pull request closed without merging**
