### PR TITLE
Allow PyTorch to be built without NCCL

### LINKED ISSUE #17274: building pytorch 1 without nccl2
Hi,

I work on two systems that have a glibc 2.11 and 2.12, respectively, it is therefore incompatible with nccl2 which requires 2.19 or greater. Is there a way to install pytorch without nccl2? I have asked something similar on the forums: https://discuss.pytorch.org/t/the-problem-of-installing-pytorch-on-tx2/28762/2?u=zeneofa 

I have tried to build it using: `USE_NCCL=OFF python setup.py install`, also trying `USE_NCCL=0` and `USE_NCCL=False`, neither of which worked. On these systems I do not have sudo, and I am using a locally installed anaconda environment. Any help would be greatly appreciated, thanks in advance.

### PR DESCRIPTION
**Pull request by t-vi**
With this patch you can use USE_DISTRIBUTED=OFF (possibly in combination with USE_NCCL=OFF (?))

The significance is partly because the NCCL doesn't build with CUDA 8.
This is written under the assumption that NCCL is required for distributed if not, the USE_DISTRIBUTED check in nccl.py should be replaced by a check for the USE_NCCL environment variable.

Fixes: #17274

### CODE REVIEW

**Review by soumith — CHANGES_REQUESTED** [review]
NCCL is used for single machine multi-GPU settings as well (for example `nn.DataParallel`).
So, disabling NCCL in the case of no DISTRIBUTED is wrong.

Alternatively, we can sunset CUDA8 support.

**Comment by t-vi** [comment]
Thanks @soumith !
I don't have much of an opinion on CUDA 8 support (well, the I'm suffering from the old thrust from CUDA 8 for my other PR), but it seems that at least NCCL can't be built with it.
I'll update to use USE_NCCL instead. Does distributed work without NCCL or do I need to turn off distributed when I don't have that.

**Comment by soumith** [comment]
distributed does not work without NCCL afaik.

**Comment by t-vi** [comment]
Given that this is a corner case already and that there also is RCCL that might one day be used, I'd have a tendency not enforce `USE_DISTRIBUTED=OFF` (either by setting it automatically when `USE_NCCL=OFF` or by raising an exception).
That said, I don't really have an opinion and will gladly adapt if anyone else has.

**Review by ezyang — APPROVED** [review]
Well, this doesn't seem harmful. Save improvements for later patches, I suppose.

**Comment by pietern** [comment]
@soumith Distributed/c10d can be compiled without NCCL. Setting `USE_NCCL=0` is honored there.

**Pull request closed without merging**
