### PR TITLE
add BFloat16 operators on CPU: histc, atan2

### PR DESCRIPTION
**Pull request by jiayisunx**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by VitalyFedyunin — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
Hi! Code looks good, but jit test failure looks a bit suspicious, can you please rebase to master to check it.

**Comment by jiayisunx** [comment]
@VitalyFedyunin , I have rebased it.

**Comment by jiayisunx** [comment]
@VitalyFedyunin

**Comment by jiayisunx** [comment]
@VitalyFedyunin

**Review by frank-wei — APPROVED** [review]
@pytorchbot merge this

**Pull request closed without merging**
