### PR TITLE
[Documentation] Change version name from 'master' to 'main'

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #100201

### CODE REVIEW

**Comment by svekars** [comment]
This is already in covered in this PR: https://github.com/pytorch/pytorch/pull/100176

**Comment by albanD** [comment]
@malfet who is most aware of the core doc build system on your end?

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Please do not merge until one validates that doc links are correct.

**Comment by NivekT** [comment]
Closing because it is covered by https://github.com/pytorch/pytorch/pull/100176

**Pull request closed without merging**
