### PR TITLE
doc: `torch.nn.utils.rnn.pad_sequence`: improve the example description

### PR DESCRIPTION
**Pull request by kuraga**
doc: `torch.nn.utils.rnn.pad_sequence`: improve the example description.

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

### CODE REVIEW

**Review by mikaylagawarecki — APPROVED** [review]
Thanks

**Comment by kuraga** [comment]
@mikaylagawarecki , help, please.

https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.pack_padded_sequence.html :

> `input` can be of size `T x B x *` where `T` is the length of the longest sequence (equal to `lengths[0]`)

It should be `L x B x *` ("`L_i x B x *`"), no? `T` (the length of the longest sequence) is about the output.

**Pull request closed without merging**
