### PR TITLE
Update torch-xpu-ops pin (ATen XPU implementation)

### PR DESCRIPTION
**Pull request by ZhiweiYan-96**
188 new ATen operators/variants are added in the pin update, involving eager and torch.compile usage on HuggingFace, TIMM and TorchBench models. 16 new unit tests ported to enhance functionality coverage. Aligned source file directory structure with ATen native. Fixed corner case failures in aten::resize, aten::index_add and aten::index_put.

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #129353

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @gujinghui @EikanWang @fengyuan14 @guangyey

### CODE REVIEW

**Review by EikanWang — APPROVED** [review]

**Comment by fengyuan14** [comment]
Irrelevant failure,
image

**Pull request closed without merging**
