### PR TITLE
[ci] Move sm86 from trunk to pull

### PR DESCRIPTION
**Pull request by clee2000**
Experiment on capacity

### CODE REVIEW

**Review by malfet — APPROVED** [review]
👻👻👻

**Review by huydhn — APPROVED** [review]
LGTM!  IMO, g5.4xlarge seems to have the highest demand v.s. capacity at the moment besides Windows, ROCm, and MacOS M1.  So if this holds, the rest of Linux runners can also be moved I think

**Review by ZainRizvi — APPROVED** [review]
cc @seemethere fyi

**Pull request closed without merging**
