### PR TITLE
[3/n] Consolidate `replicate` and `DDP`: update `replicate` to reuse functions in `DDP`

### PR DESCRIPTION
**Pull request by yhcharles**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #96660

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Do replicate() and DDP have the same signature and support all the same features now?

**Comment by yhcharles** [comment]
> Do replicate() and DDP have the same signature and support all the same features now?

I think so :)

**Pull request closed without merging**
