### PR TITLE
Fixed the size of the workspace array in functions calling MAGMA

### LINKED ISSUE #53976: test_lstsq in test_linalg.py is flaky on ROCm
Example failure snippet:

```
20:32:54 ======================================================================
20:32:54 ERROR [0.053s]: test_linalg_lstsq_cuda_float32 (__main__.TestLinalgCUDA)
20:32:54 ----------------------------------------------------------------------
20:32:54 Traceback (most recent call last):
20:32:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 899, in wrapper
20:32:54     method(*args, **kwargs)
20:32:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
20:32:54     raise rte
20:32:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 287, in instantiated_test
20:32:54     result = test_fn(self, *args)
20:32:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 572, in dep_fn
20:32:54     return fn(slf, device, *args, **kwargs)
20:32:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 572, in dep_fn
20:32:54     return fn(slf, device, *args, **kwargs)
20:32:54   File "test_linalg.py", line 210, in test_linalg_lstsq
20:32:54     a = random_well_conditioned_matrix(*shape, dtype=dtype, device=device)
20:32:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1601, in random_well_conditioned_matrix
20:32:54     u, _, v = x.svd()
20:32:54 RuntimeError: magma: The value of work_size(-9223372036854775808) is too large to fit into a magma_int_t (4 bytes)
```

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @jeffdaily @sunway513 @ROCmSupport @VitalyFedyunin

### PR DESCRIPTION
**Pull request by IvanYashchuk**
The size of the workspace arrays should not be less than 1. This PR fixes lstsq calls to LAPACK and MAGMA. Also `max(1, ...)` guards were added to a few other functions (symeig, svd).
ROCm testing is enabled for lstsq, pinv, pinverse.

Fixes https://github.com/pytorch/pytorch/issues/53976

### CODE REVIEW

**Review by mruberry — APPROVED** [review]
Cool!

cc @jeffdaily

**Comment by IvanYashchuk** [comment]
@mruberry @jeffdaily can we merge this?

**Comment by mruberry** [comment]
> @mruberry @jeffdaily can we merge this?

Thanks for the ping.

**Comment by mruberry** [comment]
This is being unlanded per request.

**Pull request closed without merging**
