### PR TITLE
Enable typechecking of `collect_env.py` during CI

### PR DESCRIPTION
**Pull request by malfet**
No type annotations can be added to the script, as it still have to be Python-2 compliant.
 Make changes to avoid variable type redefinition.

### CODE REVIEW

**Comment by zou3519** [comment]
> No type annotations can be added to the script, as it still have to be Python-2 compliant.

Does adding python 2 style type annotations work? https://mypy.readthedocs.io/en/stable/python2.html
I'm not sure if running mypy (python 3) on Python 2 style annotations actually does anything or not.

**Review by zou3519 — APPROVED** [review]

**Comment by zou3519** [comment]
> No type annotations can be added to the script, as it still have to be Python-2 compliant.

Does adding python 2 style type annotations work? https://mypy.readthedocs.io/en/stable/python2.html
I'm not sure if running mypy (python 3) on Python 2 style annotations actually does anything or not.

**Comment by rgommers** [comment]
@malfet these changes are already in gh-42711, which is about to land.

**Comment by malfet** [comment]
@rgommers thank you for the ping, will chat with Ed in a few about it.

**Pull request closed without merging**
