### PR TITLE
[C++ API] Added missing nearest-exact mode and anti-alias flag

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:

Following https://github.com/pytorch/pytorch/pull/65142#issuecomment-981995692 adding missing nearest-exact mode and anti-alias flag to C++ frontend.

- https://github.com/pytorch/pytorch/pull/65142
- https://github.com/pytorch/pytorch/pull/64501

- added tests in pytorch/test/cpp/api/functional.cpp

### CODE REVIEW

**Comment by cpuhrsch** [comment]
Adding @jbschlosser as the reviewer since he was also the reviewer for the interpolate PR you reference here.

**Review by jbschlosser — COMMENTED** [review]
Functional changes look good - please also add tests in `test/cpp/api/functional.cpp` if you don't mind :)

**Comment by vfdev-5** [comment]
@jbschlosser I added the tests and failing test seems unrelated. Could you please review the PR. Thanks

**Review by jbschlosser — APPROVED** [review]
LGTM thanks for the update!

**Comment by spiegelball** [comment]
Is it possible this change forgot to implement the anti-alias path for bicubic implementation?

**Comment by vfdev-5** [comment]
@spiegelball yes, as bicubic op was portes later, probably I forgot about C++ api. Thanks for catching that!

**Pull request closed without merging**
