### PR TITLE
Unconditionally record when FakeTensorMode is allocated and report it on inconsistency

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105927

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
I guess we gather so many tracebacks on tracing that one more is not going to change anything? :D

**Comment by ezyang** [comment]
In this case, FakeTensorMode is allocated once per compilation so I think the memory cost should be marginal

**Pull request closed without merging**
