### PR TITLE
Add instance methods tensor.isnan(), tensor.isinf(), tensor.isfinite()

### LINKED ISSUE #37736: [discussion] Add convenience instance methods tensor.isnan(), tensor.isinf(), tensor.isfinite()
Currently they are only available as `torch.isnan(x)`, `torch.isinf(x)`, `torch.isfinite(x)`

### PR DESCRIPTION
**Pull request by ShawnZhong**
Fix #37736

### CODE REVIEW

**Comment by choidongyeon** [comment]
Hey @ShawnZhong, could you help me understand how this PR fixes the issue? Just curious 😄

**Comment by ShawnZhong** [comment]
@choidongyeon 
 https://github.com/pytorch/pytorch/blob/681c6fb60f490336a899ffe91543730c05078c5c/aten/src/ATen/native/README.md#L197-L220

**Comment by ShawnZhong** [comment]
Since this PR has been around for a while, is there anyone who'd like to review this PR? 

@gchanan @soumith

**Review by soumith — APPROVED** [review]
lgtm

**Pull request closed without merging**
