### PR TITLE
[dtensor] move pad/unpad_tensor to separate utils

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #124879
* #124872
* __->__ #124871

as titled, 1. pad/unpad is a general util not specific to the Shard
placement, 2. for the propose of the next PR, move these two out of Shard
placement itself, and give additional pad_dim argument

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k

### CODE REVIEW

**Review by awgu — APPROVED** [review]

**Comment by awgu** [comment]
Looks like need to migrate `test_dtensor.py`
```
shard_placement._unpad_tensor(tensor, pad_sizes[i])
```

**Review by wz337 — APPROVED** [review]
LGTM

**Review by XilunWu — APPROVED** [review]

**Pull request closed without merging**
