### PR TITLE
Fix broadcasting to implicit leading dimensions in `torch.where` on MPS

### LINKED ISSUE #86239: `torch.where` on MPS fails to broadcast identically to other backends / numpy
### 🐛 Describe the bug

```
import torch as t

t.where(t.ones(10, 10).to("mps").bool(), t.ones(2, 10, 10).to("mps"), t.ones(10, 10).to("mps"))
```

this succeeds on CPU and fails with

> RuntimeError: 0'th index 2 of x tensor does not match the other tensors

on MPS

I believe I have a fix which I will link immediately after creating this issue.

### Versions

(composition) alex@Alexs-MacBook-Pro-2 mlscratchpad % python ../pytorch/torch/utils/collect_env.py
Collecting environment information...
PyTorch version: 1.13.0.dev20221004
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.201)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.13.0.dev20221004
[pip3] torchaudio==0.13.0.dev20221004
[pip3] torchvision==0.15.0.dev20221004
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] numpy-base                1.23.1          py310h742c864_0
[conda] torch                     1.13.0.dev20221004          pypi_0    pypi
[conda] torchaudio                0.13.0.dev20221004          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221004          pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

### PR DESCRIPTION
**Pull request by aslvrstn**
Fixes #86239

### CODE REVIEW

**Comment by aslvrstn** [comment]
FWIW I see that this was very very recently modified (https://github.com/pytorch/pytorch/pull/85946) and I think it fixed _some_ of these issues, but AFAICT these new tests are exercising new logic, and also do in fact line up with other backends, but please let me know if I'm misunderstanding!

**Review by kulinseth — APPROVED** [review]
Looks good, thanks.

**Comment by kulinseth** [comment]
> FWIW I see that this was very very recently modified (#85946) and I think it fixed _some_ of these issues, but AFAICT these new tests are exercising new logic, and also do in fact line up with other backends, but please let me know if I'm misunderstanding!

@aslvrstn correct, it was fixed in https://github.com/pytorch/pytorch/pull/85946/files. It added where tests in TestConsistency. Please make sure they are working fine.

**Comment by kulinseth** [comment]
There were few workflows which needed approval to run . Kicked them off . @aslvrstn after it looks green I will merge it

**Pull request closed without merging**
