### PR TITLE
implement __dir__ for dynamo

### LINKED ISSUE #94478: @torch.compile has problems accessing compiled model vars
### 🐛 Describe the bug

I have a Stable Diffusion model(sdm)    # Type is LatentDiffusion
It has a var named 'xxx'.  NOTE: Python dir(obj) returns vars of a class
```
'xxx' in dir(sdm)   # is True
sdm = torch.compile(sdm)          # Type is now OptimizedModule
'xxx' in dir(sdm)   # is NOW False
sdm.xxx     # Still is accessable
```
Did compile() make OptimizedModule a subclass of the original LatentDiffusion class?
Later when a function, is compiled using @torch.compile, has a reference to sdm.xxx, it fails with an InternalTorchDynamoError caused by the failure to find sdm.xxx here:
```
torch/_dynamo/variables/nn_module.py:var_getattr(tx, name)
    subobj = inspect.getattr_static(base, name)    # inspect is from /usr/lib/python3.10/inspect.py
```
This failure to find sdm.xxx raises AttributeError(attr) leading to the Internal Error(stack at the end).
See this note from inspect.getattr_static():
```
   Note: this function may not be able to retrieve all attributes
   that getattr can fetch (like dynamically created attributes)
   ...
```
'xxx' is a valid attribute of my 'sdm' model.  But either due to a short coming of inspect or the usage of inspect, it can't find it.

Internal error stack:
`Traceback (most recent call last):
  File "~/a1/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "~/a1/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "~/a1/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "~/a1/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "~/a1/modules/processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "~/a1/modules/processing.py", line 840, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn 
    return fn(*args, **kwargs)
  File "~/a1/modules/sd_samplers_kdiffusion.py", line 326, in sample
    extra_params_kwargs = self.initialize(p)
  File "~/a1/modules/sd_samplers_kdiffusion.py", line 336, in <graph break in sample> 
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "~/a1/modules/sd_samplers_kdiffusion.py", line 233, in launch_sampling
    return func()
  File "~/a1/modules/sd_samplers_kdiffusion.py", line 336, in <lambda> 
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "~/a1/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context 
    return func(*args, **kwargs)
  File "~/a1/repositories/k-diffusion/k_diffusion/sampling.py", line 144, in sample_euler_ancestral
    for i in trange(len(sigmas) - 1, disable=disable):
  File "~/a1/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in <graph break in sample_euler_ancestral>
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "~/a1/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/a1/modules/sd_samplers_kdiffusion.py", line 91, in forward
    print("******************************************")
  File "~/a1/modules/sd_samplers_kdiffusion.py", line 92, in <graph break in forward>
    print("Where the bug will appear")
  File "~/a1/modules/sd_samplers_kdiffusion.py", line 93, in <graph break in forward>
    print("Where the bug will appear")
  File "~/a1/modules/sd_samplers_kdiffusion.py", line 94, in <graph break in forward>
    print("Where the bug will appear")
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 330, in catch_errors
    return callback(frame, cache_size, hooks)
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 394, in _compile
    raise InternalTorchDynamoError() from e
  File "~/a1/modules/sd_samplers_kdiffusion.py", line 92, in <graph break in forward>
    print("Where the bug will appear")
  File "~/a1/modules/sd_samplers_kdiffusion.py", line 93, in <graph break in forward>
    print("Where the bug will appear")
  File "~/a1/modules/sd_samplers_kdiffusion.py", line 94, in <graph break in forward>
    print("Where the bug will appear")
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 330, in catch_errors
    return callback(frame, cache_size, hooks)
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "~/a1/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 394, in _compile
    raise InternalTorchDynamoError() from e
torch._dynamo.exc.InternalTorchDynamoError
`

### Error logs

torch._dynamo.exc.InternalTorchDynamoError

### Minified repro

_No response_

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.17.0-1019-oem-x86_64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 525.85.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn.so.8.7.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.7.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.7.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.7.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.7.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.7.0
/usr/local/cuda-12.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          32
On-line CPU(s) list:             0-31
Vendor ID:                       GenuineIntel
Model name:                      13th Gen Intel(R) Core(TM) i9-13900K
CPU family:                      6
Model:                           183
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       1
Stepping:                        1
CPU max MHz:                     4342.1250
CPU min MHz:                     800.0000
BogoMIPS:                        5990.40
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       896 KiB (24 instances)
L1i cache:                       1.3 MiB (24 instances)
L2 cache:                        32 MiB (12 instances)
L3 cache:                        36 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.1
[pip3] pytorch-lightning==1.9.0
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torchmetrics==0.11.1
[conda] Could not collect

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### PR DESCRIPTION
**Pull request by alimoezzi**
Fixes #94478 modules' attributes are not included in when `__dir__` is called on the optimized module.

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

### CODE REVIEW

**Comment by msaroufim** [comment]
LGTM, Only thing that needs to fixed is the lint so please try this https://github.com/pytorch/pytorch/wiki/lintrunner and we can merge

**Review by msaroufim — APPROVED** [review]

**Comment by alimoezzi** [comment]
Thanks @msaroufim, linting is done.

**Comment by davidberard98** [comment]
Hi @alimoezzi, I am planning to revert this in #102766.

The reason is that there are a few internal use cases that do something like this:

```python
mod = torch.compile(mod)
mod.is_compiled = True
assert "is_compiled" in dir(mod)
```

After the change in this PR, this started failing because "is_compiled" wasn't in `dir(mod)`.

**Comment by gchanan** [comment]
That is a real bug, __dir__ should be consistent with __getattr__ right?

**Comment by davidberard98** [comment]
@gchanan to clarify are you saying we should or shouldn't revert this?

**Comment by alimoezzi** [comment]
@davidberard98 to compensate for this I can improve this by first looking at the attributes of compiled model and if not found then look inside `_orig_mod`. 

If this is good enough for this use case I can open another PR or update this one.
cc: @gchanan

**Comment by alimoezzi** [comment]
If there's other internal use cases like this, I'm happy to create test case for them. @davidberard98 @gchanan 
Please let me know.

**Comment by davidberard98** [comment]
@alimoezzi , I think your plan sounds reasonable. You can add me as a reviewer if you open another PR and I can verify whether it affects any internal use cases.

**Comment by alimoezzi** [comment]
Great @davidberard98. I don't have access to add you as a reviewer.
Can you add yourself to reviewers?

**Pull request closed without merging**
