### PR TITLE
[inductor] Improve error messages

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #95558
* #95556
* __->__ #95567

Example error message before/after (710 to 131 lines):
https://gist.github.com/jansel/6fecad057738089fa95bf08c3de9fc8a

cc @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Review by mlazos — APPROVED** [review]

**Comment by drisspg** [comment]
Nanogpt [train.py](https://github.com/karpathy/nanoGPT/blob/master/train.py) is failing with:

``` Bash
  File "/scratch/drisspg/work/pytorch/torch/_inductor/ir.py", line 365, in __str__
    self.inner_fn_str(max_lines=config.debug_max_lines),
torch._dynamo.exc.BackendCompilerFailed: backend='debug_wrapper' raised:
TypeError: wrapper() got an unexpected keyword argument 'max_lines'
```

**Pull request closed without merging**
