### PR TITLE
Fuzzing benchmark for FFT operators

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#47872 Fuzzing benchmark for FFT operators**
* #47871 Fix complex tensors and missing data in benchmark utility

Differential Revision: [D25237499](https://our.internmc.facebook.com/intern/diff/D25237499)

### CODE REVIEW

**Comment by mruberry** [comment]
Hey @peterbell10!

I've asked @ngimel to suggest a reviewer for this and #47871 since she's more familiar with benchmarking.

**Comment by robieta** [comment]
At a high level this looks good. I would suggest moving `SpectralOpFuzzer` to `torch/utils/benchmark/op_fuzzers` and moving the benchmark script itself to `torch/utils/benchmark/examples`. I have a TODO to extend the op microbenchmarks to use more fuzzed values so having a canned fuzzer for spectral ops would be quite helpful. (As well as just generally good to have.)

The one question I have on the fuzzer is that you are restricting shapes to those that factor nicely; do you think it makes sense to also test some more pathological shapes? (Albeit a small fraction of the time.)

**Comment by peterbell10** [comment]
>moving the benchmark script itself to `torch/utils/benchmark/examples`

Shouldn't it be somewhere in the `benchmarks/` folder, or is that being phased out?

>The one question I have on the fuzzer is that you are restricting shapes to those that factor nicely; do you think it makes sense to also test some more pathological shapes? (Albeit a small fraction of the time.)

In general when comparing two FFT libraries this is definitely worth doing. But in my case I want to benchmark the pytorch interface code and  how it calls the underlying FFT library, not necessarily the FFT library itself. For my purposes, using non-regular sizes just increases the benchmark runtime. 

Perhaps it could still be useful as a parameter to the `SpectralOpFuzzer`. e.g. `probability_regular=0.8` similar to `FuzzedTensor`'s `probability_contiguous`.

**Comment by robieta** [comment]
> Shouldn't it be somewhere in the benchmarks/ folder, or is that being phased out?

I think the main thing is not having ad-hoc code in the operator benchmarks folder. @ngimel It seems like a lot of these one-off scripts have popped up recently. Any strong preferences for where they should live?

> Perhaps it could still be useful as a parameter to the SpectralOpFuzzer. e.g. probability_regular=0.8 similar to FuzzedTensor's probability_contiguous.

SGTM.

**Comment by peterbell10** [comment]
@ngimel, @robieta any new thoughts on where to put the benchmark files, or is examples the best place for now?

**Comment by mruberry** [comment]
> @ngimel, @robieta any new thoughts on where to put the benchmark files, or is examples the best place for now?

Just fyi that the team is on holiday this week, so it may take a few (working) days to get a response.

**Comment by ngimel** [comment]
I don't have a strong preference, we can leave the code in `examples`.

**Review by robieta — APPROVED** [review]
LGTM. I'll start merging the stack. Thanks for your patience.

**Pull request closed without merging**
