### PR TITLE
[PyTorch-RPC] In process_group_agent, avoid read-after-free

### PR DESCRIPTION
**Pull request by jjlilley**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#35252 [PyTorch-RPC] In process_group_agent, avoid read-after-free**

The torch::from_blob() syntax without a deleter syntax is relatively
dangerous and explicitly assumes that the caller will correctly persist
the tensor bits for as long as necessary.

We were at one point correctly persisting the send tensor bits in
process_group_agent, but with the early-return codepaths are not
doing so any longer.

This change switches to a more robust approach where we instead just use
the torch::from_blob-with-deleter syntax, and use std::move to avoid
a copy. There's an extra malloc, but that's effectively free compared with
the rest of the work involved here. And it means we don't have to worry
about the Tensor memory vanishing from underneath the send anymore.

The initial motivation here was dist_autograd_node_failure flakiness.

While the motivating case is handleSend(), we also fix handlePendingMessage().

Differential Revision: [D20607028](https://our.internmc.facebook.com/intern/diff/D20607028/)

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Reasoning looks good from what I can tell, @jjlilley , do you mind describing a bit in what early-exit codepath the underlying tensor bits could be freed? 

@mrshenli @pritamdamania87 would be good if you can take a look at this as well.

**Comment by jjlilley** [comment]
> Reasoning looks good from what I can tell, @jjlilley , do you mind describing a bit in what early-exit codepath the underlying tensor bits could be freed?
> 
> @mrshenli @pritamdamania87 would be good if you can take a look at this as well.

Sure, consider the following:

    if (!rpcRunning_.load() || !pendingSend->wait()) {
      // Send was interrupted or RPC is not running.
     return;
   }

If we hit either !rpcRunning.load() case or !pendingSend->wait() on the first tensor vector, we were almost guaranteed to read-after-free in the original code.

Switching to the deleter syntax just makes the code more RAII-ish and more robust to cases like this.

**Comment by jjlilley** [comment]
re: tests-
 - clang-tidy was existing and not avoidable here (const_cast)
 - py3.6-clang7-rocmdeb-ubuntu16.04 was unrelated failure in test_quantization  
- pytorch_macos_10_13_py3_test  also unrelated

**Comment by rohan-varma** [comment]
@jjlilley I think if the failure is expected, we generally add `//NOLINT` to indicate so. See https://github.com/pytorch/pytorch/pull/33225/files#diff-78653e2c61fcda663d8f91f4f950719dR7 for an example

**Pull request closed without merging**
