### PR TITLE
Add *_only and all/any pytree utilities

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #83330
* __->__ #83316
* #83312

With a sample usage in proxy tensor to show how they can shorten
your code dramatically.

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
SGTM
maybe some test in `test/test_pytree.py`?

**Comment by ezyang** [comment]
added

**Review by zou3519 — APPROVED** [review]
cool!

**Review by albanD — APPROVED** [review]
Thanks

**Review by bdhirsh — APPROVED** [review]

**Pull request closed without merging**
