### PR TITLE
Bugfix for add_hparams #32651

### PR DESCRIPTION
**Pull request by Rob-Fletcher**
Removed a bit of code that appends the current time to the directory for the SummaryWriter and changed the add_summary function to operate directly on self._get_file_writer() instead of creating a new SummaryWriter. The result is hyperparameters logged in the same record file where add_scalar() also logs.

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 293f71c1:


**None of the build failures appear to be your fault**.

* **1/1** [broken upstream](https://dr.pytorch.org/master-timeline.html?count=1&sha1=957a07ffbd13d8a805f4d718e0282efc5d2bff85&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&max_columns_suppress_successful=35) at merge base 957a07ff since Jan 27
  <details>
  <summary>
  Please rebase on the <code>viable/strict</code> branch (expand for instructions)
  </summary>
  
  If your commit is newer than `viable/strict`, you can try basing on an older, stable commit:
  ```
  git fetch origin viable/strict
  git rebase --onto viable/strict $(git merge-base origin/master HEAD)
  ```
  If your commit is older than `viable/strict`:
  ```
  git fetch origin viable/strict
  git rebase viable/strict
  ```
  Check out the [recency history](https://dr.pytorch.org/master-viable-commits.html) of this "viable master" tracking branch.
  
  </details>
  


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=293f71c1089d61178f4802e071f1e4d837b0d906).

### :construction: 1 upstream failure recognized by patterns:
These builds matched patterns, but were probably **caused by upstream breakages**:
* [pytorch_macos_10_13_py3_test](https://dr.pytorch.org/build-details.html?build_id=91432372) from Jan 27 until Jan 27



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by Rob-Fletcher** [comment]
Sorry WIP

**Comment by Rob-Fletcher** [comment]
Failures seem to be on flaky tests not related to this commit.

**Comment by lanpa** [comment]
@Rob-Fletcher I have tried your fix, but I only see one row of parameters in tensorboard even if multiple h-parameters is passed.

**Comment by Rob-Fletcher** [comment]
@lanpa is that desired behavior? I thought you would only want one set of hparams per experiment/record. I will take a look again and see if I can get that behavior without creating subdirs.

**Comment by lanpa** [comment]
The expected behavior is that all parameter combinations and their corresponding performance can be displayed on a single page so that you can compare against them.

**Comment by lanpa** [comment]
@Rob-Fletcher You might run and check out the last cell in the notebook below.
https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/hyperparameter_tuning_with_hparams.ipynb

**Pull request closed without merging**
