### PR TITLE
[reland] Add int1 to int7 dtypes

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137928

Summary:
Similar to https://github.com/pytorch/pytorch/pull/117208, we want to add int1 to int7 for edge use cases
for weight quantization

Test Plan:
python test/test_quantization.py -k test_uint4_int4_dtype

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D64344944](https://our.internmc.facebook.com/intern/diff/D64344944)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64344944).

**Comment by vadimkantorov** [comment]
Are these to represent signed dtypes? (trying to understand the semantic difference between uint1 and int1 - or maybe it's just for simplicity in coding to have also "signed" dtypes?)

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64344944).

**Comment by jerryzh168** [comment]
> Are these to represent signed dtypes? (trying to understand the semantic difference between uint1 and int1 - or maybe it's just for simplicity in coding to have also "signed" dtypes?)

yes, these are for signed dtypes

**Review by malfet — APPROVED** [review]
Sure, though please consider dropping Int1, not a very useful type imo

**Comment by jerryzh168** [comment]
> Sure, though please consider dropping Int1, not a very useful type imo

yeah I thought about this as well, seems like edge wants to add it still, cc @metascroy and @kimishpatel

**Comment by kimishpatel** [comment]
> > Sure, though please consider dropping Int1, not a very useful type imo
> 
> yeah I thought about this as well, seems like edge wants to add it still, cc @metascroy and @kimishpatel

Unless int1 significantly adds maintenance burden, I think we should have it for completeness given we have uint1 as well.

**Comment by jerryzh168** [comment]
cc @malfet I will need to resolve the errors in the diff before landing btw, still fixing some of these

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64344944).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D64344944).

**Pull request closed without merging**
