### PR TITLE
[aotinductor] Rename if name is prefixed with integer

### LINKED ISSUE #109894: functorch_maml_omniglot, lennard_jones, maml_omniglot: SyntaxError: invalid decimal literal
Repro:
```
python benchmarks/dynamo/torchbench.py --bfloat16 --accuracy --inference --device cuda  --export-aot-inductor  --only maml_omniglot
```
Error:
```
ERROR:common:Failed to import /tmp/torchinductor_binbao/wo/cwoge4zbwzqkowbbsqzaan3arjoeelurzsuc3xovel6jvdk2it2x.py
SyntaxError: invalid decimal literal (cwoge4zbwzqkowbbsqzaan3arjoeelurzsuc3xovel6jvdk2it2x.py, line 316)
Traceback (most recent call last):
  File "/home/binbao/pytorch/torch/_inductor/codecache.py", line 1294, in load_by_key_path
    code = compile(f.read(), path, "exec")
  File "/tmp/torchinductor_binbao/wo/cwoge4zbwzqkowbbsqzaan3arjoeelurzsuc3xovel6jvdk2it2x.py", line 316
    buf0 = extern_kernels.convolution(arg23_1, 0_weight, stride=(1, 1), padding=(0, 0), dilation=(1, 1), transposed=False, output_padding=(0, 0), groups=1, bias=None)
```

If you look at the input fx_graph, it has the attributed named with a number prefix, which is causing troubles downstream, so this is an export issue.
```
class GraphModule(torch.nn.Module):
    def forward(self, arg23_1: bf16[5, 1, 28, 28]):
        # File: /home/binbao/pytorch/torch/nn/modules/container.py:215, code: input = module(input)
        _0_weight_1: bf16[64, 1, 3, 3] = getattr(self, "0_weight")
        _0_bias_1: bf16[64] = getattr(self, "0_bias")
        _1_weight_1: bf16[64] = getattr(self, "1_weight")
        _1_bias_1: bf16[64] = getattr(self, "1_bias")
        _4_weight_1: bf16[64, 64, 3, 3] = getattr(self, "4_weight")
        _4_bias_1: bf16[64] = getattr(self, "4_bias")
        _5_weight_1: bf16[64] = getattr(self, "5_weight")
        _5_bias_1: bf16[64] = getattr(self, "5_bias")
        _8_weight_1: bf16[64, 64, 3, 3] = getattr(self, "8_weight")
        _8_bias_1: bf16[64] = getattr(self, "8_bias")
        _9_weight_1: bf16[64] = getattr(self, "9_weight")
        _9_bias_1: bf16[64] = getattr(self, "9_bias")
        _13_weight_1: bf16[5, 64] = getattr(self, "13_weight")
        _13_bias_1: bf16[5] = getattr(self, "13_bias")
        _1_running_mean_1: bf16[64] = getattr(self, "1_running_mean")
        _1_running_var_1: bf16[64] = getattr(self, "1_running_var")
        _5_running_mean_1: bf16[64] = getattr(self, "5_running_mean")
        _5_running_var_1: bf16[64] = getattr(self, "5_running_var")
        _9_running_mean_1: bf16[64] = getattr(self, "9_running_mean")
        _9_running_var_1: bf16[64] = getattr(self, "9_running_var")
        arg23_2 = arg23_1
        convolution: bf16[5, 64, 26, 26] = torch.ops.aten.convolution.default(arg23_2, _0_weight_1, _0_bias_1, [1, 1], [0, 0], [1, 1], False, [0, 0], 1);  arg23_2 = _0_weight_1 = _0_bias_1 = None
 
```

### PR DESCRIPTION
**Pull request by angelayi**
Fixes https://github.com/pytorch/pytorch/issues/109894.
Since in c++ we cannot have variables that start with an integer, we can do some additional handling in inductor to not produce constant tensors with names starting with integers.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by desertfire — COMMENTED** [review]
This works, but generating an attribute with a number prefix seems strange to me in the first place. Do we know where it is generated?

**Comment by angelayi** [comment]
> This works, but generating an attribute with a number prefix seems strange to me in the first place. Do we know where it is generated?

Yup, basically:
1. The module being exported is a torch.nn.Sequential object, with its parameters having the name 0.weight, 0.bias representing the params from the 0th module, 1.weight, 1.bias representing params from the 1st module, and so on. I added an example in the test file.
2. When we export, we set the state dict, node targets, and node names to be this name "0_weight", "0_bias". 
3. When passed to inductor, it creates the variable names based on the target, "0_weight", in the code I'm modifying.

**Comment by desertfire** [comment]
> > This works, but generating an attribute with a number prefix seems strange to me in the first place. Do we know where it is generated?
> 
> Yup, basically:
> 
> 1. The module being exported is a torch.nn.Sequential object, with its parameters having the name "0.weight"/"0.bias" representing the params from the 0th module, "1.weight"/"1.bias" representing params from the 1st module, and so on. I added an example in the test file.
> 2. When we export, we set the state dict, node targets, and node names to be this name "0_weight"/"0_bias".
> 3. When passed to inductor, it creates the variable names based on the target, "0_weight", in the code I'm modifying.

Can we change `0.weight` to something like `module_0.weight` in step 1?

**Comment by angelayi** [comment]
> Can we change 0.weight to something like module_0.weight in step 1?

I can try -- this is changing torch.nn.Module behavior though, so I was worried it might break a lot of things

**Comment by desertfire** [comment]
> > Can we change 0.weight to something like module_0.weight in step 1?
> 
> I can try -- this is changing torch.nn.Module behavior though, so I was worried it might break a lot of things

Looks like the idea doesn't work. I will approve your original implementation.

**Review by desertfire — APPROVED** [review]

**Pull request closed without merging**
