### PR TITLE
Set up automated hash pinning for triton

### PR DESCRIPTION
**Pull request by clee2000**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!  Let's hear from folks who have update this manually @ngimel @weiwangmeta

**Comment by ngimel** [comment]
Looks great! Can we also setup something to send notifications to inductor team? Likely the tests would fail...
In the meantime I'm trying to update manually #97278

**Comment by clee2000** [comment]
> Looks great! Can we also setup something to send notifications to inductor team? Likely the tests would fail... In the meantime I'm trying to update manually #97278

Would adding people from the inductor team to be codeowners for the file be sufficient?

**Comment by ngimel** [comment]
Yes, thanks!

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
