### PR TITLE
[AOT Refactor] alias runtime wrappers

### PR DESCRIPTION
**Pull request by jon-chuang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #114643
* #114564
* #114563
* __->__ #114562
* #114561
* #114559
* #114558
* #114557
* #114556
* #114555
* #114554
* #114553
* #114552
* #114551
* #114550
---

Part _ of https://github.com/pytorch/pytorch/issues/114548

### CODE REVIEW

**Comment by bdhirsh** [comment]
I know the # of LOC is pretty long, but I would prefer to put these in the `runtime_wrappers.py` file instead of having a separate `alias_runtime_wrappers.py` file. That way they're all in one place, and you can easily see what all the various runtime transformations are.

**Comment by jon-chuang** [comment]
Ok, I'll keep the stacked PR structure just move it to that file

**Review by bdhirsh — APPROVED** [review]

**Pull request closed without merging**
