### PR TITLE
Revert "[dynamo] guarded config (#111299)"

### PR DESCRIPTION
**Pull request by davidberard98**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #115386
* #115385
* #115401
* #115384

This reverts commit 5927e9cbf2ac18aaaaecaab02258b7a35ac10969.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

Differential Revision: [D51959266](https://our.internmc.facebook.com/intern/diff/D51959266)

### CODE REVIEW

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51959266).

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51959266).

**Review by yanboliang — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by davidberard98** [comment]
There's one failure (marked as flaky) - hf_T5_base OOM on dynamic_aot_eager. This also appears to happen on trunk. So I am planning to merge via fbcode.

**Comment by davidberard98** [comment]
@davidberard98 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D51959266).

**Pull request closed without merging**
