### PR TITLE
Export libtorch_cuda.so to be public

### PR DESCRIPTION
**Pull request by guangyey**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137693
* #136974

# Motivation
fix https://github.com/pytorch/pytorch/issues/137694, `libtroch_cuda.so` is missing in `TORCH_LIBRARIES` and `TORCH_CUDA_LIBRARIES` in PyTorch CMake

If build flag `BUILD_SHARED_LIBS` is disabled, `libtorch_cuda.so` will be added into `TORCH_LIBRARIES` [here](https://github.com/pytorch/pytorch/blob/084657e012047f8bf54a81c737f0726da82b7fa8/cmake/TorchConfig.cmake.in#L76)
If build flag `BUILD_SHARED_LIBS` is enabled, `libtorch_cuda,so` is missing [here](https://github.com/pytorch/pytorch/blob/084657e012047f8bf54a81c737f0726da82b7fa8/cmake/TorchConfig.cmake.in#L138)

# Additional Context
`find_library(TORCH_CUDA_LIBRARY` intends to export `libtorch_cuda.so` to `TORCH_LIBRARIES`.

Why do we prefer `find_library(TORCH_CUDA_LIBRARY` instead of `append_torchlib_if_found`?
`append_torchlib_if_found` doesn't update `TORCH_CUDA_LIBRARIES`. And we expect `libtorch_cuda.so` to be added to both `TORCH_CUDA_LIBRARIES` and `TORCH_LIBRARIES` to facilitate user experience.

cc @malfet @seemethere @ptrblck @msaroufim

### CODE REVIEW

**Comment by guangyey** [comment]
@malfet could you help review this PR?

**Comment by guangyey** [comment]
@malfet Sorry for this. Just a reminder in case this series PR is ignored.

**Comment by guangyey** [comment]
@malfet May I know if this code change is reasonable to you?

**Comment by malfet** [comment]
> @malfet May I know if this code change is reasonable to you?

I still don't understand, what problem this PR is trying to solve? Can you please add a regression test or something? TORCH_LIBRARY should only contain reference to libtorch, which is a proxy library for both `torch_cpu` and `torch_cuda`. Why one needs to add explicit dependency to `libtorch_cuda.so`? When depending on `libtorch.so` is not enough?

**Comment by guangyey** [comment]
I go through the CMake code again. In my understanding, these pieces of code seem to find all libs related to torch such as `torch_cpu`, `torch_cuda`, `c10`, `c10_cuda`, and `torch` to **TORCH_LIBRARY**, and even `nnpack`, `mkldnn`, `kineto` these libs PyTorch depends on. In most situations, `libtorch.so`, a proxy lib, is enough to find the dependency, but sometimes might be over-enough.
This PR intends to add `torch_cuda` to **TORCH_LIBRARY** in BUILD_SHARED_LIBS mode to flexibly facilitate the user experience in the situation where the user only wants to link `torch_cuda`. I could take only link `torch_cpu` as an example: ipex CPU code only would like to link `libtorch_cpu` rather than `libtorch_cpu` and `libtorch_cuda`.
If this PR code change is not reasonable to you, I would like to close it.

**Comment by malfet** [comment]
>  If this PR code change is not reasonable to you, I would like to close it.

There are two use-cases in my mind:
 - C++ API users, who should never link with anything directly against libtorch_cuda or c10 or kineto, as implementation of all methods decorated with `TORCH_API` should be in `libtorch_cpu.so`
 - Extension developers who might need to link to `kineto`, `c10_cuda`, `cudnn` etc should write their scripts in a way to explicitly search for those dependencies, as pytorch might change the underlying structure any time, but if they need something from the 3rd party libraries, they should not assume they'll be available thru PyTorch

**Comment by guangyey** [comment]
Do you mean if C++ user would like to use some APIs provided by `libtorch_cuda.so` such as [getCUDADeviceAllocator](https://github.com/pytorch/pytorch/blob/4715b7700131618be5f439a8ad6b5ae94a201915/aten/src/ATen/cuda/CUDAContextLight.h#L82). It is enough to link against `libtorch.so` rather than `libtorch_cuda.so`. If yes, I think you are right.

**Pull request closed without merging**
