### PR TITLE
Enable UFMT format on test/typing files

### PR DESCRIPTION
**Pull request by zeshengzong**
Fixes some files in #123062

Run lintrunner on files:
test/typing/**/*

```
$ lintrunner -a --take UFMT --all-files
ok No lint issues.
Successfully applied all patches.
```

### CODE REVIEW

**Review by shink — APPROVED** [review]

**Comment by ezyang** [comment]
fix ci please, is clean

**Comment by ezyang** [comment]
ci fail is legit

**Review by ezyang — APPROVED** [review]

**Comment by hippocookie** [comment]
Checked CI message, the latest fail seems not cause by UFMT changes, is there anything I need to do to fix it? Thanks @ezyang

**Pull request closed without merging**
