### PR TITLE
Nvfuser moving python tests and files under nvfuser

### PR DESCRIPTION
**Pull request by jjsjann123**
1. Moving `test_jit_cuda_fuser.py` `test_nvfuser_dynamo.py` `test_nvfuser_frontend.py` under `third_party/nvfuser/python_tests/`.
2. Moving `nvfuser/__init__.py` to `third_party/nvfuser/python/`.
3. Leaving dummy test scripts under `./test/` for CI.
4. Patching `torch/_prims/nvfuser_prims.py` for view/reshape renaming in nvfuser
5. Installing `third_party/nvfuser/python` and `third_party/nvfuser/python_tests` to pytorch root/test directy.

### CODE REVIEW

**Review by davidberard98 — APPROVED** [review]
LGTM!

**Comment by jjsjann123** [comment]
Thx for reviewing this. Sorry about the large number on LOC, git isn't very smart about renaming file and leaving a few lines in the old file :)

I'll put that explicitly in the commit message.

**Comment by davidberard98** [comment]
@jjsjann123 I think this one should probably be fine to merge with the `@ mergebot merge` command, considering that it's mostly just renaming files, as you said.

**Pull request closed without merging**
