### PR TITLE
[CUDA] Switch to `at::empty_like` in `adaptive_avg_pool3d_backward_cuda`

### PR DESCRIPTION
**Pull request by eqy**
Same as #100138, `gradInput` is already zero'd out. Also clean up includes after #100138.

CC @ngimel @ptrblck 

cc @ngimel

### CODE REVIEW

**Comment by eqy** [comment]
(looked through the remaining Pooling files in `aten/src/ATen/native/cuda/` and this seemed to be the only obvious one with the same issue

**Review by ngimel — APPROVED** [review]

**Comment by eqy** [comment]
Interesting that `empty_like` with `MemoryFormat::Preserve` doesn't work but `empty` with `input.options()` does

**Pull request closed without merging**
