### PR TITLE
Logging documentation updates

### PR DESCRIPTION
**Pull request by mlazos**
Updated the logging.rst with info about the env var.

### CODE REVIEW

**Review by msaroufim — APPROVED** [review]
This feels PT 2.0 specific, is the intent to keep it seperate because eventually this will be the log standard for all pytorch? Just wanna mention that `docs/source/compile` exists for pt2 specific stuff

**Comment by mlazos** [comment]
> This feels PT 2.0 specific, is the intent to keep it seperate because eventually this will be the log standard for all pytorch? Just wanna mention that `docs/source/compile` exists for pt2 specific stuff

Yeah it's only PT 2.0 specific because we haven't added other loggable entities from elsewhere yet. The interface will be the same no matter where you use it.

**Review by lezcano — APPROVED** [review]
If every artefact is connected to a component, we should add that to the docs. Otherwise it LGTM

**Comment by mlazos** [comment]
> If every artefact is connected to a component, we should add that to the docs. Otherwise it LGTM

Good point, I'll update

**Pull request closed without merging**
