### PR TITLE
[MPS] Handle 1D inputs for NLL

### PR DESCRIPTION
**Pull request by kulinseth**
* Add test for NLL 1d
* Fix forward NLL for 1D case
* Handle NLL backward for 1d

### CODE REVIEW

**Review by razarmehr — APPROVED** [review]
Looks good

**Comment by kulinseth** [comment]
The failure is not related to this:
```
test_to_padded_tensor_simple_cuda_float16 (__main__.TestNestedTensorDeviceTypeCUDA) ... Memory exception on virtual address 0x7f9c023b7000, node id 4 : Page not present
[78029](https://github.com/pytorch/pytorch/runs/7307362222?check_suite_focus=true#step:7:78030)
Address does not belong to a known buffer
[78030](https://github.com/pytorch/pytorch/runs/7307362222?check_suite_focus=true#step:7:78031)
Memory access fault by GPU node-4 (Agent handle: 0x561f40ae6510) on address 0x7f9c023b7000. Reason: Page not present or supervisor privilege.
[78031](https://github.com/pytorch/pytorch/runs/7307362222?check_suite_focus=true#step:7:78032)
Traceback (most recent call last):
[78032](https://github.com/pytorch/pytorch/runs/7307362222?check_suite_focus=true#step:7:78033)
  File "test/run_test.py", line 940, in <module>
[78033](https://github.com/pytorch/pytorch/runs/7307362222?check_suite_focus=true#step:7:78034)
    main()
[78034](https://github.com/pytorch/pytorch/runs/7307362222?check_suite_focus=true#step:7:78035)
  File "test/run_test.py", line 918, in main
[78035](https://github.com/pytorch/pytorch/runs/7307362222?check_suite_focus=true#step:7:78036)
    raise RuntimeError(err_message)
[78036](https://github.com/pytorch/pytorch/runs/7307362222?check_suite_focus=true#step:7:78037)
RuntimeError: test_nestedtensor failed! Received signal: SIGIOT
[78037](https://github.com/pytorch/pytorch/runs/7307362222?check_suite_focus=true#step:7:78038)
```

**Pull request closed without merging**
