### PR TITLE
[ONNX] Enclose package info for modules exported as local functions

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #107654
* #107653
* __->__ #107409
* #107408

Enclose source package of modules that are exported as onnx local function in exported onnx model. GPT2 model example:

image

### CODE REVIEW

**Comment by titaiwangms** [comment]
I think something is off on ONNX docker image

**Comment by BowenBao** [comment]
Looks like bumping onnxscript fixed a few xfails.

**Comment by justinchuby** [comment]
The domain needs to be

> A reverse-DNS name to indicate the model namespace or domain, for example, 'org.onnx'

Does it make sense to use

org.pytorch or pkg.torch / pkg.transformers

?

Then move the version number to opset version?

the version can be 2.1.0 -> 2100000 / 4.31.0 -> 4310000

otherwise we can also do org.pytorch.2.1.0 or something like that?

**Review by justinchuby — APPROVED** [review]

**Comment by BowenBao** [comment]
Adjusted to `pkg[.{package_name}][.{version}][.{hash}]`

**Pull request closed without merging**
