### PR TITLE
init lr=1e-3 for torch.optim.SGD

### PR DESCRIPTION
**Pull request by Roffild**
All optimizers are set to `lr` by default.

### CODE REVIEW

**Comment by Roffild** [comment]
Why isn't this patch merged?

**Review by iramazanli — COMMENTED** [review]
Hey ! thank you for this PR. I do have the question of choice of default parameter. Keras chose the value to be 0.01, and i was curious if there is other library or academic paper that stands for 0.001 so we would prefer this number ?

**Comment by Roffild** [comment]
> Hey ! thank you for this PR. I do have the question of choice of default parameter. Keras chose the value to be 0.01, and i was curious if there is other library or academic paper that stands for 0.001 so we would prefer this number ?

In PyTorch optimizers, it is more often 1e-3. I like the result with 1e-3 better. It's like an argument about the number of Spaces in a Tab.

**Comment by Roffild** [comment]
The patch is ready. A year has passed. Maybe it's time to merge?

**Comment by albanD** [comment]
As discussed above, there is no good argument for this particular value so not sure if we really want this?
The reason we're especially careful here is that once we make this a default, we cannot really remove it anymore for BC reasons.

**Comment by Roffild** [comment]
Oh, no, no, no... This patch is alive!

**Pull request closed without merging**
