### PR TITLE
Update xla.txt to fix missing commit

### PR DESCRIPTION
**Pull request by JackCaoG**

### CODE REVIEW

**Comment by JackCaoG** [comment]
https://github.com/pytorch/pytorch/pull/117434 is in the process of merging, I think that pr will also update the XLA pin and that one should fix the issue. @huydhn is it OK to give that pr another 20 minutes?

**Comment by JackCaoG** [comment]
If things still break I will rebase this pr to fix XLA CI and investigate why my branch at XLA got deleted.

**Review by masnesral — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Comment by lezcano** [comment]
I reverted the SGD PR as it was breaking the CI. I think the errors it was hitting are unrelated to XLA

**Comment by JackCaoG** [comment]
Ok Let me merge this one then.

**Pull request closed without merging**
