### PR TITLE
Fix symbolic shape function for `flatten`

### PR DESCRIPTION
**Pull request by silvasean**
Python `range` is (start,end) not (start, length). Sot it should be `for i in range(start_dim, end_dim + 1):` instead of `for i in range(start_dim, end_dim - start_dim + 1):`.

### CODE REVIEW

**Comment by makslevental** [comment]
good catch

**Review by makslevental — APPROVED** [review]

**Review by eellison — COMMENTED** [review]
Nice!! Do you remind removing the OpInfo skip for `flatten` ? Tests did (belatedly) catch this, which I’m just now realizing..

**Comment by eellison** [comment]
https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_methods_invocations.py#L13164

**Comment by makslevental** [comment]
@eellison I accepted and pushed up https://github.com/pytorch/pytorch/pull/71762 for the opinfo

**Pull request closed without merging**
