### PR TITLE
Remove skips for passing tests

### PR DESCRIPTION
**Pull request by oulgen**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #118041
* __->__ #118000

These tests were already passing

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Comment by zou3519** [comment]
There might be a flaky test somewhere?

**Comment by oulgen** [comment]
@zou3519 it was passing with PYTORCH_TEST_WITH_DYNAMO but failing with PYTORCH_TEST_WITH_INDUCTOR however CI did not run it with inductor on the PR.

**Pull request closed without merging**
