### PR TITLE
Fix copied optimizer

### PR DESCRIPTION
**Pull request by barrh**
Add the defaults field to the copied object.
Prior to this patch, optimizer.__getattr__ has excluded the defaults
attribute of optimizer source object, required by some LR schedulers. (e.g. CyclicLR with momentum)

### CODE REVIEW

**Review by soumith — APPROVED** [review]
thanks for the fix and test

**Comment by soumith** [comment]
@barrh there are legitimate test failures:

```
Apr 16 14:33:05 ======================================================================
Apr 16 14:33:05 FAIL: test_lbfgs (__main__.TestOptim)
Apr 16 14:33:05 ----------------------------------------------------------------------
Apr 16 14:33:05 Traceback (most recent call last):
Apr 16 14:33:05   File "test_optim.py", line 439, in test_lbfgs
Apr 16 14:33:05     ignore_multidevice=True
Apr 16 14:33:05   File "test_optim.py", line 194, in _test_basic_cases
Apr 16 14:33:05     constructor
Apr 16 14:33:05   File "test_optim.py", line 184, in _test_state_dict
Apr 16 14:33:05     self.assertEqual(set(optimizer.__dict__), set(deepcopy(optimizer).__dict__))
Apr 16 14:33:05   File "/var/lib/jenkins/workspace/test/common_utils.py", line 467, in assertEqual
Apr 16 14:33:05     super(TestCase, self).assertEqual(x, y, message)
Apr 16 14:33:05 AssertionError: Items in the first set but not the second:
Apr 16 14:33:05 '_params'
Apr 16 14:33:05 '_numel_cache' : 
Apr 16 14:33:05 
```

**Comment by barrh** [comment]
@soumith I doubt current failure is my fault, and 3 tests are still pending after 10 hours.
Is there a way for me to (re-)invoke tests?

**Comment by soumith** [comment]
@barrh I restarted the tests for you. I'm pretty sure the test failures are related to this PR. It might just be side-effects of your PR

**Comment by barrh** [comment]
@soumith thanks. everything is successful now.

**Pull request closed without merging**
