### PR TITLE
Replace internal error to TORCH_CHECK

### LINKED ISSUE #87672: INTERNAL ASSERT FAILED source.dtype() == self.dtype()
### 🐛 Describe the bug

RuntimeError: source.dtype() == self.dtype() INTERNAL ASSERT FAILED , please report a bug to PyTorch. 

```
"""
Task 1: import PyTorch
Task 2: Generate input
Task 3: Call the API torch.Tensor.set_
"""
import torch

input_ = [
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]
    ]
]

input_ = torch.tensor(input_, dtype=torch.float32)

input_.set_(torch.tensor(
    [
        [
            [21, 22, 23],
            [24, 25, 26],
            [27, 28, 29]
        ],
        [
            [31, 32, 33],
            [34, 35, 36],
            [37, 38, 39]
        ]
    ]))

print(input_)
```
```
RuntimeError: source.dtype() == self.dtype() INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1659484806139/work/torch/csrc/autograd/generated/python_variable_methods.cpp":16766, please report a bug to PyTorch. 
```

### Versions

PyTorch 1.12.1

### PR DESCRIPTION
**Pull request by PanosAntoniadis**
Fixes #87672

### CODE REVIEW

**Review by ezyang — CHANGES_REQUESTED** [review]
Not correct, you cannot check in the generated code, you have to find where it is generated and edit that

**Comment by PanosAntoniadis** [comment]
@ezyang Sorry I didn't understand this at first. I updated now in the correct part of the code.

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
need cla

**Comment by PanosAntoniadis** [comment]
Done! I signed the cla!

**Comment by PanosAntoniadis** [comment]
Ok, I fixed it and made the commits in another PR (https://github.com/pytorch/pytorch/pull/88804) that passes the EasyCLA check now. So, please close this PR and check the new one. @ezyang

**Pull request closed without merging**
