### PR TITLE
woof

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #89010

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Differential Revision: [D41276175](https://our.internmc.facebook.com/intern/diff/D41276175)

### CODE REVIEW

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41276175).

**Review by bigfootjon — APPROVED** [review]

**Pull request closed without merging**
