### PR TITLE
Remove functorch dispatch keys in `legacyExtractDispatchKey`

### PR DESCRIPTION
**Pull request by guilhermeleobas**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #133018

cc @zou3519 @Chillee @samdow @kshitij12345 @janeyx99

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
Fixes https://github.com/pytorch/pytorch/issues/120554

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
