### PR TITLE
Enable Scatter/Gather ORT Test for opset 11

### PR DESCRIPTION
**Pull request by lara-hdr**
Enable ONNX Runtime Test for scatter in opset 11

### CODE REVIEW

**Comment by neginraoof** [comment]
Thanks Lara, could you please enable test_scatter_add?

**Comment by lara-hdr** [comment]
@houseroad can we merge this?

**Review by houseroad — APPROVED** [review]
LGTM

**Comment by houseroad** [comment]
Don't forget to put it to the list :-)

**Pull request closed without merging**
