### PR TITLE
Format tensor

### PR DESCRIPTION
**Pull request by Dmovic**
Align tensor display

### CODE REVIEW

**Review by janeyx99 — COMMENTED** [review]
It already looks fine on main?
https://pytorch.org/docs/main/generated/torch.nn.MaxUnpool2d.html#maxunpool2d

**Comment by Dmovic** [comment]
> It already looks fine on main? https://pytorch.org/docs/main/generated/torch.nn.MaxUnpool2d.html#maxunpool2d

Yeah, It's just a little different in tensor format and no big deal.

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
