### PR TITLE
Rename AT_ASSERT to TORCH_INTERNAL_ASSERT; other macro updates

### PR DESCRIPTION
**Pull request by ezyang**
Stack:
&nbsp;&nbsp;&nbsp;&nbsp;:white_circle:&nbsp; #20435 Replace AT_CHECK with TORCH_CHECK [shard 9/10]&nbsp;&nbsp;[:yellow_heart:](https://our.internmc.facebook.com/intern/diff/D15318877/)
&nbsp;&nbsp;&nbsp;&nbsp;:black_circle:&nbsp; **#20321 Rename AT_ASSERT to TORCH_INTERNAL_ASSERT; other macro updates**&nbsp;&nbsp;[:green_heart:](https://our.internmc.facebook.com/intern/diff/D15278439/)

First part of https://github.com/pytorch/pytorch/issues/20287

- Rename `AT_ASSERT` to `TORCH_INTERNAL_ASSERT`
- Make `TORCH_INTERNAL_ASSERT` work with variadic inputs
- Deprecated `AT_ASSERT` and `AT_ASSERTM`
- Rename `AT_CHECK` to `TORCH_CHECK`
- Make `TORCH_CHECK` give a better error message when no arguments are
  provided
- Deprecate `AT_ERROR` in favor of `TORCH_CHECK(false, ...)`
- Deprecate `AT_INDEX_ERROR` in favor of `TORCH_CHECK_INDEX(false, ...)`
- Rename `AT_WARN` to `TORCH_WARN`

No use sites are changed; I'll work on that in follow up patches
(or disable the deprecation, if necessary.)

Differential Revision: [D15278439](https://our.internmc.facebook.com/intern/diff/D15278439/)

### CODE REVIEW

**Comment by ezyang** [comment]
Right. Good thing we have builds checking for use of deprecations. I'll amend this diff to not deprecate, have some diffs to fix use sites, and then turn on the deprecations for real.

**Review by gchanan — APPROVED** [review]

**Review by zdevito — APPROVED** [review]
Code good. Hot take: if we are about to rename the world of asserts, maybe we should reconsider the prefix and use `TORCH_` or `TH_`. Especially for new people the `AT_` prefix is rare and this check really is used across the entire project.

**Comment by ezyang** [comment]
@gchanan brought up a similar concern. I'm willing to be convinced here. My current reservations:

* `TH` is the legacy library name, so the identifier name is a bit poisoned; if I see a macro with TH in front I'll assume it's legacy
* `TORCH` is long

But hey, we don't type `AT_CHECK` that much, so maybe `TORCH_CHECK` isn't so bad.

**Comment by gchanan** [comment]
`TORCH_CHECK` or `PT_CHECK` work for me.

**Comment by ezyang** [comment]
OK, let's do `TORCH_CHECK`.

**Comment by suo** [comment]
This looks good to me! My minor complaint is that TORCH_INTERNAL_ASSERT is long enough that I'm concerned people won't use it. (PT|TORCH)_CHECK is good

**Comment by ezyang** [comment]
> My minor complaint is that TORCH_INTERNAL_ASSERT is long enough that I'm concerned people won't use it.

Knowing how to use asserts correctly requires training. :) So, I guess, I don't mind if less people use it; that's kind of the point of this PR :)

**Comment by dzhulgakov** [comment]
Thanks! Minor comment, maybe it's just me, but I find TORCH_ERROR or TORCH_CHECK_FAIL more idiomatic than TORCH_CHECK(false, ...)

**Comment by ezyang** [comment]
Me too!  But one of the complaints about the old set of macros were that there were too many macros. By eliminating `AT_ERROR`, there's only two you have to remember. @zdevito, @suo, did I misunderstand your concern here?

**Comment by suo** [comment]
Yes, and I think the secondary concern was that "error" is ambiguous (user error? internal error?). TORHC_INTERNAL_ASSERT makes the intended usage clear.

**Comment by dzhulgakov** [comment]
How about TORCH_CHECK_FAIL(msg) and TORCH_INTERNAL_ASSERT_FAIL(msg). But I'm not-picking at this point

**Comment by ezyang** [comment]
If either Michael or Zach signs off on this I can make it happen.

**Pull request closed without merging**
