### PR TITLE
cmake: auto-detect ccache to speed up developer builds

### PR DESCRIPTION
**Pull request by leezu**
https://ccache.dev/ is a compiler cache that speeds up subsequent builds. Auto-detecting ccache ensures that it is used on systems where it is available, greatly improving build times for developers. There is no risk in enabling ccache in practice. Please refer to https://ccache.dev/ for a short summary / motivation

### CODE REVIEW

**Comment by leezu** [comment]
Ping @malfet

**Review by malfet — APPROVED** [review]

**Comment by leezu** [comment]
@malfet how to fix the missing CI status? Looks like the CI status reporting is a bit buggy

**Comment by leezu** [comment]
@mrshenli @malfet please merge

**Comment by ezyang** [comment]
@malfet Don't we have to update the developer instructions now? There is no need to  manually setup gcc symlinks for ccache anymore with this change.

**Comment by leezu** [comment]
@ezyang the old instructions continue to work. But of course autodetection is easier.

I also noticed that PyTorch uses the deprecated FindCUDA module instead of cmake's native cuda support. Thus the `CMAKE_CUDA_COMPILER_LAUNCHER` introduced in this PR doesn't have any effect currently and the old symlink approach + `CUDA_NVCC_EXECUTABLE=/ccache/symlink/nvcc` is still required for caching nvcc

**Pull request closed without merging**
