### PR TITLE
[DataLoader] Refactor dataloader.py

### PR DESCRIPTION
**Pull request by ssnl**
As I am working on tasks in https://github.com/pytorch/pytorch/issues/13023, I realized how unreadable the code is because all functions to be run in multiprocessing must be at top global level. Adding more functionalities to `dataloader.py` will only make things worse. 

So in this PR, I refactor `dataloader.py` and move much of it into `data._utils`. E.g., the `_worker_loop` and related methods are now in `data._utils.worker`, signal handling code in `data._utils.signal_handling`, collating code in `data._utils.collate`, etc. This split, IMHO, makes code much clearer. I will base my future changes to DataLoader on top of this.

No functionality is changed, except that  I added `torch._six.queue`.

### CODE REVIEW

**Comment by SsnL** [comment]
Requesting a review from any of @apaszke @soumith @colesbury @ezyang . This PR only does refactoring.

**Review by soumith — APPROVED** [review]

**Comment by ailzhang** [comment]
Btw this diff is landing more than 12hrs... Not sure if it's normal. cc: @yf225  @soumith

**Comment by ezyang** [comment]
Check on the Phab diff; it probably failed land for some silly reason (like lint failure) and you'll have to click ship it inside.

**Comment by ailzhang** [comment]
@SsnL Unfortunately I got pinged for some internal tests failure on this diff. Have to revert it for now to unblock, I can send you more details on the test failure tomorrow.

**Comment by SsnL** [comment]
will open a new one.

**Pull request closed without merging**
