### PR TITLE
Optional arg fixes 

### LINKED ISSUE #17210: optional arg is not optional in torch.cuda.get_device_name, torch.cuda.get_device_capability
`torch.cuda.get_device_name`, `torch.cuda.get_device_capability` require an argument that according to docs should be optional:

```
$ python -c 'import torch; print(torch.cuda.get_device_name(), torch.cuda.get_device_capability());'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: get_device_name() missing 1 required positional argument: 'device'
```
which shouldn't be the case, since the docs say the argument is option and not required.

This works:
```
$ python -c 'import torch; print(torch.cuda.get_device_name(None), torch.cuda.get_device_capability(None));'
GeForce GTX 1070 Ti (6, 1)
```
The [docs](https://pytorch.org/docs/stable/cuda.html) go:

Parameters: | device (torch.device or int, **optional**)

So either the docs or the code is wrong.

I think it's just these 2 functions. The other requiring `device` aren't optional.

Thank you.

torch=1.0.1.post2

### PR DESCRIPTION
**Pull request by surgan12**
fixes #17210.
cc : @ezyang

### CODE REVIEW

**Comment by soumith** [comment]
lgtm, can you add a test so that we dont regress in the future.

**Comment by surgan12** [comment]
@soumith Sure !! will do that !

**Comment by surgan12** [comment]
@soumith Tests added !!

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
thanks!

**Pull request closed without merging**
