### PR TITLE
Repair the path to jni.h for libtorch windows build

### LINKED ISSUE #86536: pytorch_jni.dll and pytorch_jni.lib missing from LibTorch Windows zip archives after 1.10.2
### 🐛 Describe the bug

`pytorch_jni.dll` and `pytorch_jni.lib` are missing from the `lib` directory in the LibTorch bundles for Windows after 1.10.2

See for example:-
[1.12.1 CUDA 11.6 Archive](https://download.pytorch.org/libtorch/cu116/libtorch-win-shared-with-deps-1.12.1%2Bcu116.zip) _et al._ and, as of writing, current nightly

See also:-

#78483
#46464

This breaks the Java TorchScript bindings unfortunately 

### Versions

LibTorch > 1.10.2

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

### PR DESCRIPTION
**Pull request by cristianPanaite**
Fixes #86536

It seems like the file is not found when the environment is populate, so the BUILD_JNI flag is false.

To mark it as true, I had to add a `/pytorch/` when adding paths in `POSSIBLE_JAVA_HOMES`. This way, it seems like the file is found and the flag it's true.

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @seemethere @malfet @pytorch/pytorch-dev-infra

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Feels a bit weird, but sure, why not

**Review by Blackhex — APPROVED** [review]
The produced libtorch artifacts now contains pytorch\_jni.dll. The code change seems OK.

**Comment by cristianPanaite** [comment]
@malfet I see that there are some failures but I think they are not related to my changes. Is anything I can do?

**Pull request closed without merging**
