### PR TITLE
[Reland] Add atan2 isfinite isinf isnan isneginf isposinf isreal to nvfuser and its frontend

### PR DESCRIPTION
**Pull request by zasdfgbnm**
This reverts commit 4bb59441339074515a4257704acca6ebd80826cc.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
CUDA 10.2 failure should be fixed. cc @csarofeen

**Comment by zasdfgbnm** [comment]
ping @mruberry

**Comment by mruberry** [comment]
> ping @mruberry

Should we have someone from nvFuser approve this before landing it, @zasdfgbnm?

**Review by csarofeen — APPROVED** [review]
LGTM

**Comment by csarofeen** [comment]
Cross referencing with
https://github.com/csarofeen/pytorch/issues/1632
https://github.com/pytorch/pytorch/pull/76598

**Review by mruberry — APPROVED** [review]
Stamped

**Pull request closed without merging**
