### PR TITLE
Enable mkldnn on windows

### LINKED ISSUE #15982: [Caffe2] Enable Windows build with MKL-DNN
## Bug

In MKLDNN cmake, MSVS build are disabled explicitly.
https://github.com/pytorch/pytorch/blob/12e0ed55b4327d41052651ddbae58506c5957ab8/cmake/Modules/FindMKLDNN.cmake#L16-L19

I think this is no longer the case as we can build mkldnn directly with Visual Studio 2017 and MKLDNN's official cmake doesn't complain about that
https://github.com/intel/mkl-dnn/blob/4bdffc2cb1c3d47df9604d35d2c7e5e47a13f1a6/cmake/OpenMP.cmake#L78-L81

But, after commenting out the `RETURN()`, the issue I'm encountering is about ideep.

```
pytorch\third_party\ideep\include\ideep\allocators.hpp(151): error C2039: 'posix_memalign': is not a member of '`global namespace''
pytorch\third_party\ideep\include\ideep\allocators.hpp(151): error C3861: 'posix_memalign': identifier not found
```

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Win10
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake + ninja
 - Python version: 3.7.2
 - CUDA/cuDNN version: 10.0/7
 - GPU models and configuration: 1080Ti

### PR DESCRIPTION
**Pull request by XiaobingSuper**
Fixes https://github.com/pytorch/pytorch/issues/15982.

### CODE REVIEW

**Comment by kostmo** [comment]
## CircleCI build failures summary
As of commit 0652f0a:
* **1/1** failures introduced in this PR



## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=0652f0ad0f4567559757e16172bdf471b3e3997b).

### 1 new failure recognized by patterns
The following build failures don't appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/3976385) pytorch_windows_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=75773364) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=75773364))
<details>
<summary>
<code>FAILED: third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/utils.cpp.obj</code>
</summary>

```
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28107 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9025 : overriding '/w' with '/W4'
cl : Command line warning D9025 : overriding '/W4' with '/w'
GPU Computing Toolkit\CUDA\v10.1\include" /DWIN32 /D_WINDOWS /GR  /w /EHa /MP /bigobj -openmp:experimental  /MP    /wd4800 /wd4068 /wd4305 /wd4551  /MD /O2 /Ob2  /w /EHa /MP /bigobj   /Qpar /openmp -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -Wno-tautological-compare /showIncludes /Fothird_party\ideep\mkl-dnn\src\CMakeFiles\mkldnn.dir\common\verbose.cpp.obj /Fdthird_party\ideep\mkl-dnn\src\CMakeFiles\mkldnn.dir\mkldnn.pdb /FS -c ..\third_party\ideep\mkl-dnn\src\common\verbose.cpp 
FAILED: third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/verbose.cpp.obj  
GPU Computing Toolkit\CUDA\v10.1\include" /DWIN32 /D_WINDOWS /GR  /w /EHa /MP /bigobj -openmp:experimental  /MP    /wd4800 /wd4068 /wd4305 /wd4551  /MD /O2 /Ob2  /w /EHa /MP /bigobj   /Qpar /openmp -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -Wno-tautological-compare /showIncludes /Fothird_party\ideep\mkl-dnn\src\CMakeFiles\mkldnn.dir\common\verbose.cpp.obj /Fdthird_party\ideep\mkl-dnn\src\CMakeFiles\mkldnn.dir\mkldnn.pdb /FS -c ..\third_party\ideep\mkl-dnn\src\common\verbose.cpp 
cl : Command line error D8021 : invalid numeric argument '/Wno-tautological-compare'
DIA GPU Computing Toolkit\CUDA\v10.1\include" /DWIN32 /D_WINDOWS /GR  /w /EHa /MP /bigobj -openmp:experimental  /MP    /wd4800 /wd4068 /wd4305 /wd4551  /MD /O2 /Ob2  /w /EHa /MP /bigobj   /Qpar /openmp -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -Wno-tautological-compare /showIncludes /Fothird_party\ideep\mkl-dnn\src\CMakeFiles\mkldnn.dir\common\utils.cpp.obj /Fdthird_party\ideep\mkl-dnn\src\CMakeFiles\mkldnn.dir\mkldnn.pdb /FS -c ..\third_party\ideep\mkl-dnn\src\common\utils.cpp 
FAILED: third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/utils.cpp.obj  
DIA GPU Computing Toolkit\CUDA\v10.1\include" /DWIN32 /D_WINDOWS /GR  /w /EHa /MP /bigobj -openmp:experimental  /MP    /wd4800 /wd4068 /wd4305 /wd4551  /MD /O2 /Ob2  /w /EHa /MP /bigobj   /Qpar /openmp -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -Wno-tautological-compare /showIncludes /Fothird_party\ideep\mkl-dnn\src\CMakeFiles\mkldnn.dir\common\utils.cpp.obj /Fdthird_party\ideep\mkl-dnn\src\CMakeFiles\mkldnn.dir\mkldnn.pdb /FS -c ..\third_party\ideep\mkl-dnn\src\common\utils.cpp 
cl : Command line error D8021 : invalid numeric argument '/Wno-tautological-compare'
c\..\include -I..\cmake\..\third_party\googletest\googlemock\include -I..\cmake\..\third_party\googletest\googletest\include -I..\third_party\protobuf\src -Iwin_tmp\mkl\include /DWIN32 /D_WINDOWS /GR  /w /EHa /MP /bigobj /W4 /MD /O2 /Ob2 /DNDEBUG /w /EHa /MP /bigobj   -std:c++14 /showIncludes /Fothird_party\benchmark\src\CMakeFiles\benchmark.dir\benchmark_register.cc.obj /Fdthird_party\benchmark\src\CMakeFiles\benchmark.dir\benchmark.pdb /FS -c ..\third_party\benchmark\src\benchmark_register.cc 
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28107 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9025 : overriding '/w' with '/W4'
cl : Command line warning D9025 : overriding '/W4' with '/w'
benchmark\src\..\include -I..\cmake\..\third_party\googletest\googlemock\include -I..\cmake\..\third_party\googletest\googletest\include -I..\third_party\protobuf\src -Iwin_tmp\mkl\include /DWIN32 /D_WINDOWS /GR  /w /EHa /MP /bigobj /W4 /MD /O2 /Ob2 /DNDEBUG /w /EHa /MP /bigobj   -std:c++14 /showIncludes /Fothird_party\benchmark\src\CMakeFiles\benchmark.dir\csv_reporter.cc.obj /Fdthird_party\benchmark\src\CMakeFiles\benchmark.dir\benchmark.pdb /FS -c ..\third_party\benchmark\src\csv_reporter.cc 
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28107 for x64
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by xsacha** [comment]
@XiaobingSuper thanks for looking in to this. Not sure why it has always been disabled on Windows but I suppose there's lots of these sort of issues that have gone unnoticed now.

https://github.com/pytorch/pytorch/blob/0652f0ad0f4567559757e16172bdf471b3e3997b/cmake/Modules/FindMKLDNN.cmake#L97

**Comment by peterjc123** [comment]
@XiaobingSuper Thanks for fixing this!

**Comment by XiaobingSuper** [comment]
@jgong5, @gujinghui , @CaoZhongZ

**Comment by peterjc123** [comment]
Would you please try out adding `# include <ctime>` in  `include/ideep/utils.hpp`? I think that it should fix the build failure in CI.

**Comment by XiaobingSuper** [comment]
> Would you please try out adding `# include <ctime>` in `include/ideep/utils.hpp`? I think that it should fix the build failure in CI.

Yes, I will add it, but for VS professional 1.0.1, there has no this error.

**Comment by peterjc123** [comment]
> VS professional 1.0.1

What is VS 1.0.1? You mean VS 2015 / 2017 / 2019?

**Comment by XiaobingSuper** [comment]
> > VS professional 1.0.1
> 
> What is VS 1.0.1? You mean VS 2015 / 2017 / 2019?

Sorry, it is my fault, I used VS professional 2019(version 16.4.1).

**Comment by XiaobingSuper** [comment]
@VitalyFedyunin, @bddppq

**Review by peterjc123 — APPROVED** [review]
LGTM. Are there any tests that we need to enable here?

**Comment by peterjc123** [comment]
Hi, would you please rebase this master on master? I guess I'll need to test this one locally first.

**Comment by XiaobingSuper** [comment]
@peterjc123, rebased.

**Review by peterjc123 — CHANGES_REQUESTED** [review]
I tried to run the tests in `test/test_mkldnn.py`, but some of them cause the program to crash like `test_autograd_from_mkldnn`, `test_autograd_to_mkldnn`, `test_batchnorm_2d` and `test_conv2d`. You may need to deal with it first and then we will continue to land this.

**Comment by XiaobingSuper** [comment]
I will see it, but why the CI not report those failed cases?

**Comment by peterjc123** [comment]
The tests on Windows CI are disabled by mistake, but we have problem turning it on.

**Comment by peterjc123** [comment]
The Windows CI tests are enabled now. You'll be able to see the results if you rebase your PR on master.

**Comment by peterjc123** [comment]
From https://github.com/XiaobingSuper/pytorch/tree/mkldnn_windows, I saw the following message: "This branch is 2 commits ahead, 76 commits behind pytorch:master".

**Comment by peterjc123** [comment]
Let me rebase for you.

**Comment by XiaobingSuper** [comment]
@peterjc123, I will rebase it after solve ideep error on windows.

**Comment by peterjc123** [comment]
@XiaobingSuper Okay, feel free to ask when you meet with problems.

**Review by peterjc123 — APPROVED** [review]
Tests passed. Thanks for your great effort.

**Comment by Coderx7** [comment]
@peterjc123 upon being merged with  master, are we going to have this backported to 1.4? or will there be an updated release version specific to windows? as it has huge performance implications on the cpu!

**Comment by soumith** [comment]
@Coderx7 it will be part of 1.5, and part of nightlies. We wont be looking to backport it to 1.4

**Comment by Coderx7** [comment]
Can someone kindly indicate whether this is merged in the nightly version so we can start experimenting with it?

**Comment by xsacha** [comment]
Nothing changed yet in PyTorch/builder so I don't think so..

**Comment by Coderx7** [comment]
@xsacha : thanks a lot, 
@soumith by any chance is it known in advance when this feature gets merged into the nightly build? as the addition of MKLDNN support goes a long way. it seems becasue of this, the quantization is also not supported on windows which was/is a big deal for 1.3 and specially 1.4. 
Thanks in advance.

**Comment by peterjc123** [comment]
Once this PR is merged into master, it will be avaiable in the next day's nightly package. BTW, there is nothing to do at the builder scripts because it is automatically enabled and doesn't need any external dependencies.

**Comment by xsacha** [comment]
Thanks for the update @peterjc123 didn't realise MKLDNN was on by default.
Looking forward to this as it really helps when running tests on CPU servers!

**Comment by peterjc123** [comment]
@ezyang Are there any difficulties in landing the PR?

**Comment by ezyang** [comment]
No, it's just that the force push interrupted the land :)

**Pull request closed without merging**
