### PR TITLE
[primTorch] Add rsub reference

### PR DESCRIPTION
**Pull request by rdspring1**
Add Reference:
- rsub

### CODE REVIEW

**Review by mruberry — APPROVED** [review]
Sorry for the delay, @rdspring1! If you don't get a response in a couple business days feel free to ping us -- sometimes we lose a notification

This looks great; it'll just need a rebase

**Comment by IvanYashchuk** [comment]
@rdspring1 could you please merge `viable/strict` branch into this PR and then ask pytorchbot to merge on green (@ pytorchbot merge -g)?

**Pull request closed without merging**
