### PR TITLE
[ROCm] enable more unit tests

### PR DESCRIPTION
**Pull request by iotamudelta**
This enables the distributions and utils test sets for ROCm.
Individual tests are enabled that now pass due to fixes in HIP/HCC/libraries versions in white rabbit.

For attention: @bddppq @ezyang

### CODE REVIEW

**Comment by bddppq** [comment]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger/3718/

**Review by bddppq — DISMISSED** [review]

**Comment by bddppq** [comment]
There is test failure:
```
05:03:00 test_Conv1d_groups (__main__.TestNN) ... Traceback (most recent call last):
05:03:05   File "test/run_test.py", line 394, in <module>
05:03:05     main()
05:03:05   File "test/run_test.py", line 386, in main
05:03:05     raise RuntimeError(message)
05:03:05 RuntimeError: test_nn failed! Received signal: SIGSEGV
```

**Comment by bddppq** [comment]
@iotamudelta Re-triggered here https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger/3723

**Comment by bddppq** [comment]
@iotamudelta Ok could you trigger a test run? Thanks

**Comment by iotamudelta** [comment]
@bddppq I think we need to wait for #13341 to land?

**Comment by bddppq** [comment]
@iotamudelta oh right, I will land it once it passed the CI

**Comment by bddppq** [comment]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger/4212/

**Comment by bddppq** [comment]
@iotamudelta 
```
01:22:06 ======================================================================
01:22:06 ERROR: test_to_dense (__main__.TestCudaSparse)
01:22:06 ----------------------------------------------------------------------
01:22:06 Traceback (most recent call last):
01:22:06   File "test_sparse.py", line 247, in test_to_dense
01:22:06     test_tensor(x, res)
01:22:06   File "test_sparse.py", line 210, in test_tensor
01:22:06     x.to_dense()  # Tests triple to_dense for memory corruption
01:22:06 RuntimeError: cuda runtime error (1011) : hipErrorInvalidValue at /var/lib/jenkins/workspace/aten/src/THC/generic/THCTensorMath.cu:25
01:22:06 
01:22:06 ======================================================================
01:22:06 ERROR: test_to_dense_hybrid (__main__.TestCudaSparse)
01:22:06 ----------------------------------------------------------------------
01:22:06 Traceback (most recent call last):
01:22:06   File "test_sparse.py", line 320, in test_to_dense_hybrid
01:22:06     test_tensor(x, res)
01:22:06   File "test_sparse.py", line 285, in test_tensor
01:22:06     x.to_dense()  # Tests double to_dense for memory corruption
01:22:06 RuntimeError: cuda runtime error (1011) : hipErrorInvalidValue at /var/lib/jenkins/workspace/aten/src/THC/generic/THCTensorMath.cu:25
01:22:06 
01:22:06 ======================================================================
01:22:06 ERROR: test_to_dense (__main__.TestCudaUncoalescedSparse)
01:22:06 ----------------------------------------------------------------------
01:22:06 Traceback (most recent call last):
01:22:06   File "test_sparse.py", line 247, in test_to_dense
01:22:06     test_tensor(x, res)
01:22:06   File "test_sparse.py", line 210, in test_tensor
01:22:06     x.to_dense()  # Tests triple to_dense for memory corruption
01:22:06 RuntimeError: cuda runtime error (1011) : hipErrorInvalidValue at /var/lib/jenkins/workspace/aten/src/THC/generic/THCTensorMath.cu:25
01:22:06 
01:22:06 ======================================================================
01:22:06 ERROR: test_to_dense_hybrid (__main__.TestCudaUncoalescedSparse)
01:22:06 ----------------------------------------------------------------------
01:22:06 Traceback (most recent call last):
01:22:06   File "test_sparse.py", line 320, in test_to_dense_hybrid
01:22:06     test_tensor(x, res)
01:22:06   File "test_sparse.py", line 285, in test_tensor
01:22:06     x.to_dense()  # Tests double to_dense for memory corruption
01:22:06 RuntimeError: cuda runtime error (1011) : hipErrorInvalidValue at /var/lib/jenkins/workspace/aten/src/THC/generic/THCTensorMath.cu:25
01:22:06 
01:22:06 ----------------------------------------------------------------------
01:22:06 Ran 230 tests in 12.643s
01:22:06 
01:22:06 FAILED (errors=4, skipped=138)
01:22:07 Traceback (most recent call last):
01:22:07   File "test/run_test.py", line 394, in <module>
01:22:07     main()
01:22:07   File "test/run_test.py", line 386, in main
01:22:07     raise RuntimeError(message)
01:22:07 RuntimeError: test_sparse failed!
01:22:07 + cleanup
01:22:07 + retcode=1
01:22:07 + set +x
```

**Comment by iotamudelta** [comment]
@bddppq I thought they were skipped already by another PR. Added skips for them - this is the memset issue, most likely. Will be resolved in 1.9.2

**Comment by bddppq** [comment]
@iotamudelta trigger trigger trigger :-)

**Comment by iotamudelta** [comment]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-trigger/4623/

**Comment by iotamudelta** [comment]
@bddppq it is interesting that these tests seem so flaky for ROCm. Maybe revert for now until we have 1.9.2 which, among other things, should bring improved group convolutions?

**Comment by bddppq** [comment]
According to git blame, this test (`test_Conv2d_groups_thnn`) was added long time ago https://github.com/pytorch/pytorch/commit/00410c4496c3aaa5782f0e5f249bb3b0b2f3d94a

I just reran the test and it's still failing https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test/1538/

**Comment by iotamudelta** [comment]
@bddppq has something changed in the CI images? these tests have started failing in our fork as well.

**Comment by bddppq** [comment]
@iotamudelta No the docker image has been staying at version 213 since 3 weeks ago.

**Comment by bddppq** [comment]
```

**Comment by bddppq** [comment]
```
23:59:56 test_Conv2d_strided (__main__.TestNN) ... Traceback (most recent call last):
00:00:05   File "test/run_test.py", line 424, in <module>
00:00:05     main()
00:00:05   File "test/run_test.py", line 416, in main
00:00:05     raise RuntimeError(message)
00:00:05 RuntimeError: test_nn failed! Received signal: SIGSEGV
00:00:06 + cleanup
00:00:06 + retcode=1
00:00:06 + set +x
```

**Pull request closed without merging**
