### PR TITLE
[Easy] add quotes to shell activation commands

### PR DESCRIPTION
**Pull request by XuehaiPan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #143262
* __->__ #143902

### CODE REVIEW

**Review by Skylion007 — CHANGES_REQUESTED** [review]
This isn't the right way to add quotes here, you should use 'shlex.quote' for quoting arguments to CLI.

**Comment by XuehaiPan** [comment]
> This isn't the right way to add quotes here, you should use 'shlex.quote' for quoting arguments to CLI.

The content is a path. A valid fs name should not contain characters such as `"`, `'`, `!`. So `shlex.quote` will just add double quotes for the path.

**Comment by Skylion007** [comment]
@XuehaiPan Yeah, but it's generally more secure to do that/ it prevents path injections / properly handles filenames that have quotes in their filepaths.

**Comment by XuehaiPan** [comment]
> it prevents path injections

Sounds reasonable to me. I have updated the patch.

> This isn't the right way to add quotes here, you should use 'shlex.quote' for quoting arguments to CLI.

`shlex.quote` may not work correctly for PowerShell.

**Review by Skylion007 — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
