### PR TITLE
[BE][FSDP] Sort `common_fsdp.py` imports

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #80915 [BE][FSDP] Subtest prefetching in `test_mixed_precision_e2e_full_shard()`
* #80908 [BE][FSDP] Subtest prefetching in `test_fsdp_core.py`
* #80873 [BE][FSDP] Introduce `FSDPTestModel` interface
* #80871 [BE][FSDP] Retire `_get_full_detached_param()`
* **#80870 [BE][FSDP] Sort `common_fsdp.py` imports**
* #80869 [BE][FSDP] Fix that MP config not being passed to FSDP
* #80868 [BE][FSDP] Remove unneeded `torch.cuda.synchronize()`

This was part of my initial attempt to make the PRs smaller, but evidently, I failed 😅 .

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
Does the automatic linter we have (`lintrunner`) have import sorting? If so, it might be worth it to run it over all FSDP files in one go.

**Comment by awgu** [comment]
> Does the automatic linter we have (`lintrunner`) have import sorting? If so, it might be worth it to run it over all FSDP files in one go.

`lintrunner f` says it applied patches, but when I check, nothing happened. I need to follow-up on this.

**Pull request closed without merging**
