### PR TITLE
ci: Migrate vulkan builds to GHA

### PR DESCRIPTION
**Pull request by seemethere**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #66044

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

Differential Revision: [D31370889](https://our.internmc.facebook.com/intern/diff/D31370889)

### CODE REVIEW

**Comment by seemethere** [comment]
pytorchbot ciflow rerun -l ciflow/vulkan

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31370889).

**Comment by seemethere** [comment]
Interestingly enough it doesn't actually seem like the vulkan tests actually run anything (either in CircleCI or GHA).

This PR isn't really here to fix vulkan tests though so I'm just going to ignore this for now and file an issue later on about the tests

**Review by malfet — APPROVED** [review]

**Comment by seemethere** [comment]
@seemethere has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31370889).

**Pull request closed without merging**
