### PR TITLE
[Intel Triton] Update Intel Triton to resolve installation issue on manylinux.

### PR DESCRIPTION
**Pull request by etaf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #129847
* #129782

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by gujinghui — APPROVED** [review]

**Comment by etaf** [comment]
Confirmed that failed jobs are unreleated failure.
@pytorchbot  merge -i

**Comment by chuanqi129** [comment]
Confirmed that failed jobs are unreleated failure.
@pytorchbot merge -i

**Review by atalman — APPROVED** [review]

**Pull request closed without merging**
