### PR TITLE
Directly allocate eye to correct size

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #82115

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by lezcano — COMMENTED** [review]
What's the reason for this change? In `linalg` we very often use the pattern of creating something of size zero and then resizing it. I believe this is the way it's done in structured kernels as well.

**Comment by ezyang** [comment]
> What's the reason for this change? In linalg we very often use the pattern of creating something of size zero and then resizing it.

This PR doesn't really matter, but since the output size looks obvious here it also didn't seem like it caused any harm.

The reason this came to mind was https://github.com/pytorch/pytorch/issues/82088 after patching in CompositeImplicitAutograd Python key. This would technically fix that problem, although I'm looking into a more structural fix.

> I believe this is the way it's done in structured kernels as well.

No, in structured kernels we always directly allocate to the correct size.

**Review by lezcano — APPROVED** [review]

**Comment by ezyang** [comment]
lol abandoning this

**Pull request closed without merging**
