### PR TITLE
[1/2] Remove caffe2 db and distributed from build system

### PR DESCRIPTION
**Pull request by cyyever**
This PR tries to decompose https://github.com/pytorch/pytorch/pull/122527 into a smaller one. Caffe2 db, distributed build scripts and some binaries have been removed.
To be noted, this was inspired and is co-dev with @r-barnes.

cc @malfet @seemethere @ezyang @gchanan @albanD

### CODE REVIEW

**Comment by cyyever** [comment]
> @cyyever - how's this one going?

It's better to delete python first.

**Comment by cyyever** [comment]
@r-barnes Now I think we can also merge it before the python PR.

**Review by malfet — APPROVED** [review]
Deleted code is tested code

**Comment by cyyever** [comment]
> Deleted code is tested code

Do you mean deleted code in torch/binaries or other locations?

**Comment by cyyever** [comment]
@r-barnes Help merge it once you are ready?

**Pull request closed without merging**
