### PR TITLE
add Half support for multinomial on CPU

### PR DESCRIPTION
**Pull request by CaoE**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104178

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @Xia-Weiwen @ngimel

### CODE REVIEW

**Review by jgong5 — APPROVED** [review]

**Comment by CaoE** [comment]
@kulinseth Could you please review this PR ? Thanks.

**Comment by CaoE** [comment]
@kulinseth Could you please review this PR ? Thanks.

**Review by kulinseth — APPROVED** [review]

**Comment by CaoE** [comment]
@cpuhrsch Could you please review this PR ? Thank you.

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
