### PR TITLE
Intrusive_ptr implementation slower than shared_ptr

### PR DESCRIPTION
**Pull request by Yangqing**
It was a random coding exercise so I wasn't putting much effort into it; but, I was like "hey is the current intrusive_ptr implementation optimized enough?" so I compared it with shared_ptr (using std::shared_from_this).

My benchmark result shows that intrusive_ptr is actually slower. On my macbook the speed is:

```
---------------------------------------------------------------
Benchmark                        Time           CPU Iterations
---------------------------------------------------------------
BM_IntrusivePtrCtorDtor         14 ns         14 ns   52541902
BM_SharedPtrCtorDtor            10 ns         10 ns   71898849
BM_IntrusivePtrArray         14285 ns      14112 ns      49775
BM_SharedPtrArray            13821 ns      13384 ns      51602
```

Wanted to share the results so someone could probably take a look if interested.

### CODE REVIEW

**Review by bddppq — APPROVED** [review]
cc @smessmer re. the unexpected perf gap

But regardless I think it's good to have a benchmark setup.

**Comment by bddppq** [comment]
Observed similar perf gap on CI machine
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py3.6-devtoolset7-rocmrpm-centos7-test/1966/console
```
10:01:08 Running /var/lib/jenkins/.local/lib/python3.6/site-packages/torch/test/c10_intrusive_ptr_benchmark
10:01:08 Run on (64 X 2200 MHz CPU s)
10:01:08 CPU Caches:
10:01:08   L1 Data 32K (x32)
10:01:08   L1 Instruction 64K (x32)
10:01:08   L2 Unified 512K (x32)
10:01:08   L3 Unified 8192K (x8)
10:01:08 ***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
10:01:09 -----------------------------------------------------------------
10:01:09 Benchmark                          Time           CPU Iterations
10:01:09 -----------------------------------------------------------------
10:01:09 BM_IntrusivePtrCtorDtor           16 ns         16 ns   42760839
10:01:10 BM_SharedPtrCtorDtor              13 ns         13 ns   56027374
10:01:11 BM_IntrusivePtrArray/16          270 ns        270 ns    2594257
10:01:11 BM_IntrusivePtrArray/32          537 ns        537 ns    1319162
10:01:12 BM_IntrusivePtrArray/64         1060 ns       1060 ns     650673
10:01:13 BM_IntrusivePtrArray/128        2118 ns       2118 ns     330602
10:01:14 BM_IntrusivePtrArray/256        4232 ns       4231 ns     165301
10:01:15 BM_IntrusivePtrArray/512        8449 ns       8448 ns      82866
10:01:16 BM_IntrusivePtrArray/1024      16889 ns      16886 ns      41453
10:01:17 BM_IntrusivePtrArray/2048      33769 ns      33764 ns      20731
10:01:18 BM_IntrusivePtrArray/4096      67562 ns      67552 ns      10302
10:01:19 BM_SharedPtrArray/16             210 ns        210 ns    3347548
10:01:20 BM_SharedPtrArray/32             427 ns        427 ns    1657929
10:01:21 BM_SharedPtrArray/64             846 ns        846 ns     827252
10:01:22 BM_SharedPtrArray/128           1700 ns       1699 ns     414024
10:01:23 BM_SharedPtrArray/256           3397 ns       3396 ns     206705
10:01:24 BM_SharedPtrArray/512           6754 ns       6752 ns     103855
10:01:24 BM_SharedPtrArray/1024         13484 ns      13482 ns      51923
10:01:25 BM_SharedPtrArray/2048         26982 ns      26978 ns      24936
10:01:26 BM_SharedPtrArray/4096         53949 ns      53939 ns      12990
```

**Review by yinghai — APPROVED** [review]

**Comment by jonmorton** [comment]
@ezyang @smessmer @soumith any thoughts?

**Comment by ezyang** [comment]
Based on the performance work in #30709 I'd be willing to bet money that the performance difference is nearly entirely due to asserts in the implementation (which are ALWAYS run, even in Release builds).

**Comment by Yangqing** [comment]
Well, there is a standard practice for such mode (in debug and not in release). It's called DCHECK @ezyang @jonmorton .

**Comment by suo** [comment]
cc @ngimel

**Comment by smessmer** [comment]
Another potential source is that we're using sequential consistency for the atomic refcounter. `std::shared_ptr` allows more memory reorderings by using explicit acquire/release semantics.

We did perf tests in the past changing all our `intrusive_ptr` refcounts to `relaxed` and didn't see a perf difference in common PyTorch models, so we didn't land it, but for a test that just tests `intrusive_ptr` directly, this might actually make a difference.

**Comment by qizzzh** [comment]
@smessmer  I think you are referring to my experiment. Most of the shared_ptr implementation uses relaxed for incref, acq/rel for decref and acquire for reading counter. This doesn't make a perf difference on x86. However it may be helpful on other platforms, e.g. arm.

**Pull request closed without merging**
