### PR TITLE
Don't graph break on patched module methods or aliased methods

### PR DESCRIPTION
**Pull request by williamwen42**
See added tests for the cases that were fixed.

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by Morgan77523 — APPROVED** [review]
[]([]()

**Review by anijain2305 — APPROVED** [review]

**Comment by kit1980** [comment]
@williamwen42 Does this PR has memory implications?

After this PR was merged, inductor / cuda11.6-py3.10-gcc7-sm86 / test fails on trunk every time with CUDA out of memory during OPTForCausalLM.

**Comment by williamwen42** [comment]
There shouldn't be an obvious memory implication.

**Comment by kit1980** [comment]
I see the same OPTForCausalLM on this PR. Reverting because I don't see the issue anywhere before this and I see the failure every time after.

**Review by mlazos — APPROVED** [review]

**Comment by williamwen42** [comment]
Split into separate PRs https://github.com/pytorch/pytorch/pull/93309 and https://github.com/pytorch/pytorch/pull/93115.

**Pull request closed without merging**
