### PR TITLE
[quant][fx] Add RNN reference module

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #73555
* #73527
* #73436
* __->__ #73386

Summary:
This PR adds support for RNN reference module, following https://github.com/pytorch/rfcs/blob/master/RFC-0019-Extending-PyTorch-Quantization-to-Custom-Backends.md
This includes: RNNCell, LSTMCell, GRUCell, LSTM
* copied the module definitions from nn/modules/rnn.py, and added weight parameters for the modules, and modifies the weight access code from things like `self.weight_ih` to `self.get_weight_ih()` and the latter would generate the quant/dequant pattern
* TODO: to reduce duplicated code, we can refactor the original rnn.py implementations and have a inner method that takes weight as input, so that we can customize the weight, similar to _conv_forward in conv.py: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py

Test Plan:
python test/test_quantization.py TestReferenceQuantizedModule.test_rnn_cell
python test/test_quantization.py TestReferenceQuantizedModule.test_rnn
Integration test with the flow will be done later

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D34469445](https://our.internmc.facebook.com/intern/diff/D34469445)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34469445).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34469445).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34469445).

**Review by vkuzo — COMMENTED** [review]
should we have test coverage to ensure the reference modules are numerically correct?

**Comment by jerryzh168** [comment]
oh are you talking about module level test? yeah I think we can do that. I can add a test at the module level for this PR and the next one

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34469445).

**Review by vkuzo — APPROVED** [review]

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34469445).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34469445).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34469445).

**Pull request closed without merging**
