### PR TITLE
[dynamo] Remove VariableTracker.propagate

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #112961
* #112962
* __->__ #111726
* #111725
* #111415
* #111306

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by zhxchen17** [comment]
@zhxchen17 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/).

**Comment by zhxchen17** [comment]
@jansel I just imported this entire stack to fbcode and test it the internal model I'm working on.
It shows a promising tracing time reduction from 20 min down to 4 min.
Do you have a timeline on when this will be landed? We are trying to unblock some model in 1 or 2 weeks.

**Comment by jansel** [comment]
@zhxchen17 great to hear that!  I plan to land this as soon as the test failures are fixed, which hopefully will be soon.

This other stack might help trace times too:
https://github.com/pytorch/pytorch/pull/112921

**Review by voznesenskym — APPROVED** [review]

**Pull request closed without merging**
