### PR TITLE
Modules note v2

### PR DESCRIPTION
**Pull request by jbschlosser**
This PR expands the [note on modules](https://pytorch.org/docs/stable/notes/modules.html) with additional info for 1.10.

It adds the following:
* Examples of using hooks
* Examples of using apply()
* Examples for ParameterList / ParameterDict
* register_parameter() / register_buffer() usage
* Discussion of train() / eval() modes
* Distributed training overview / links
* TorchScript overview / links
* Quantization overview / links
* FX overview / links
* Parametrization overview / link to tutorial

### CODE REVIEW

**Review by mruberry — APPROVED** [review]
Overall looks really good! I made a few inline suggestions and left hooks for @albanD.

**Review by albanD — COMMENTED** [review]
I would love to see the Module structure for skip_init and device placement!

**Review by albanD — COMMENTED** [review]
I only have comments around the device placement/skip initialization part. Everything else looks good.
I am happy to continue this discussion in a follow up PR if you think this is one is big enough already as well.

**Review by albanD — APPROVED** [review]
LGTM thanks for the update!

**Pull request closed without merging**
