### PR TITLE
make __lookup_backend return None when cache misses

### LINKED ISSUE #114674: Dynamo guards key error for `guarded_backend_cache.cached_backends`
### 🐛 Describe the bug

I'm observing an interesting behavior when a torch-compiled function is called from `torch.autograd.Function.backward` (which is a different thread than a forward pass) I hit an error inside Dynamo's guards code.

There's an attempt to access `torch._dynamo.eval_frame.guarded_backend_cache.cached_backends` with a key of the backend from the forward thread and this dictionary is a thread-local object.
For some reason, the guard code for the compiled function is generated in the forward thread and it's not regenerated when called from the backward thread.
This is the code that's being called only from the forward thread:
https://github.com/pytorch/pytorch/blob/00412e6dfacdec5a8508c841b3ea0846388dc872/torch/_dynamo/guards.py#L595-L604
here the `backend_id` from the forward thread is used to access `torch._dynamo.eval_frame.guarded_backend_cache.cached_backends` in the backward thread.

I couldn't come up with a minimal reproducer though.

The current workaround I'm using is to set `torch._dynamo.eval_frame.guarded_backend_cache.skip_backend_check_for_run_only_mode = True`.

@jansel, do you know what's going on and how to fix this?

### Error logs

```py
../pytorch/main/torch/_dynamo/eval_frame.py:489: in _fn
    return fn(*args, **kwargs)
<string>:30: in guard
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

backend_obj_id = 140350781241904

>           lambda backend_obj_id: torch._dynamo.eval_frame.guarded_backend_cache.cached_backends[
                backend_obj_id
            ]
        ),
        "___skip_backend_check": (
            lambda: torch._dynamo.eval_frame.guarded_backend_cache.skip_backend_check_for_run_only_mode
        ),
        "___compile_config_hash": (
            lambda: torch._dynamo.eval_frame.get_saved_else_current_config_hash().hex()
        ),
        "___needs_nopython": (lambda: torch._dynamo.eval_frame.config_cache.nopython),
        "___odict_getitem": collections.OrderedDict.__getitem__,
        "___dict_param_key_ids": dict_param_key_ids,
        "___dict_const_keys": dict_const_keys,
        "___dict_version": dict_version,
        "___dict_contains": lambda a, b: a in b,
        "___tuple_iterator_len": tuple_iterator_len,
        "___tuple_iterator_getitem": tuple_iterator_getitem,
        "__math_isnan": math.isnan,
        "inf": float("inf"),
        "__load_module": importlib.import_module,
        "utils_device": torch.utils._device,
        "device": torch.device,
        "___from_numpy":
        # If not numpy array, piggy back on e.g. tensor guards to check type
        (lambda a: torch.as_tensor(a) if isinstance(a, (np.generic, np.ndarray)) else a),
        "torch": torch,
    }
E   KeyError: 140350781241904

../pytorch/main/torch/_dynamo/guards.py:114: KeyError

```

### Minified repro

_No response_

### Versions

Latest `main`.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### PR DESCRIPTION
**Pull request by ydwu4**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #114766

Fixes #114674. The error is because cached_backends is a thread-local object, when it's accessed from the other thread, we'll have a cache miss. The naive fix is to just return None and re-compiles when cache misses. This could also be related to making dynamo more thread-safe but I'm not sure if there an on-going effort or not.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Review by IvanYashchuk — APPROVED** [review]
I also thought about the same fix!

The problem I was seeing is now gone.

**Review by Neilblaze — APPROVED** [review]

**Review by jansel — COMMENTED** [review]
A recompile seems bad, though this is better than throwing an error.

**Comment by jansel** [comment]
Why is cached_backends is a thread-local object?  Dict lookups are atomic in python.  Can we just make it not thread local?

**Comment by jon-chuang** [comment]
I've PRed a fix here: https://github.com/pytorch/pytorch/pull/114839

**Review by jansel — APPROVED** [review]

**Pull request closed without merging**
