### PR TITLE
Enable sparse function in topology optimization.

### PR DESCRIPTION
**Pull request by wuhuikx**
There are some sparse structures in some models (Resnet50 V1.0 for example). These sparse structures result in some redundant computations for some feature map pixels which will never use. This patch aims to reduce the sparsity by pulling some large stride values in convolution up to its previously satisfied op so that useless pixels will not be generated.
The test cases show an example of sparse model module.

### CODE REVIEW

**Comment by wuhuikx** [comment]
@jgong5 @gujinghui @Jianhui-Li

**Comment by wuhuikx** [comment]
image

I show a case to illustrate the principle of the sparsity patch.
     1. check the node from the tail of the graph, so we first check conv6.
     2. if conv6 is a sparsity node (conv op with kernel =1 and stride > 1)， check if its large stride value can be pulled up to its previous node (conv4_sum_fusion).
     3.  since the conv4_sum_fusion output is obtained from conv1 output + conv4 output, the sparse stride value will influence the conv1 stride and conv4 stride. So we can see conv1 and conv4 as conv6's previous node.
     4.  check conv4 stride can be enlarged or not. If all the consumers (conv5 and conv6) of the conv4_sum_fusion are the sparse nodes and the sparse stride value is the same, set the conv4 stride=sparse stride value (2 in this case).
     5. check conv1 stride can be enlarged or not. The consumers of conv1 are conv4_sum_fusion (actually the conv5 and conv6) and conv2. The conv4_sum_fusion (actually the conv5 and conv6) is the sparse node while the conv2 is not sparse. So conv1 stride cannot be enlarged. To make the sum op in conv4_sum_fusion has same input shape, we insert max_pool (kernel=1, stride=2) between conv1 and conv4_sum_fusion node.
     6 set conv5 and conv6 stride=1, then we finish the first round of reducing sparsity and obtained the "reduce sparsity middle result".
      7. next time, we check the node from the graph tail again and find out conv4 in conv4_sum_fusion node is the sparse node.
      8, the previous node of conv4 is conv3, we check all the consumers of conv3 (conv3 only has one consumer conv4). All the consumers of conv3 are the sparse node with same sparse stride, thus we can pull up the sparse stride value in conv4 to its previous node conv3.
      9. we set conv4 stride=1 and conv3 stride=2, then we get the "reduce sparsity final result".

**Comment by wuhuikx** [comment]
Hi, @ezyang , the failure seems not caused by my revision. Could you please help check it and review the code? Thank you very much.

**Comment by jgong5** [comment]
@yinghai

**Comment by ezyang** [comment]
Hi @wuhuikx, sorry, but I'm not qualified to review this patch. Maybe Yinghai can help.

**Comment by yinghai** [comment]
@wuhuikx  Could you provide a problem formulation and high level ideas of proposed solution first? Thanks.

**Pull request closed without merging**
