### PR TITLE
Make mergebot message clearer when starting a new merge

### PR DESCRIPTION
**Pull request by ZainRizvi**
Modifying how the merge started message appears to make it more readable. 
Also removing some deprecated v1 land checks messages

Old:
image

New:
image

### CODE REVIEW

**Review by malfet — CHANGES_REQUESTED** [review]
You are deleting `get_land_check_troubleshooting_message` that is still referenced from trymerge.py

**Comment by malfet** [comment]
This PR makes much more than changing this message. Have no objections to doing it and perhaps other changes can go into another PR. Also, is this a top priority right now?

**Comment by ZainRizvi** [comment]
> This PR makes much more than changing this message. Have no objections to doing it and perhaps other changes can go into another PR. Also, is this a top priority right now?

Not a top priority, but something that kept irking me every time I saw it. This contributes to my mental sanity :P

**Review by malfet — APPROVED** [review]

**Review by huydhn — APPROVED** [review]

**Comment by ZainRizvi** [comment]
`@pytorchbot rebase`

**Pull request closed without merging**
