### PR TITLE
Make l1_loss composite

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #79381
* #77975
* __->__ #79804

Reland of https://github.com/pytorch/pytorch/pull/78257

Differential Revision: [D37281956](https://our.internmc.facebook.com/intern/diff/D37281956)

### CODE REVIEW

**Comment by zou3519** [comment]
Cool I am working on getting this merged

**Review by zou3519 — APPROVED** [review]

**Comment by zou3519** [comment]
@zou3519 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37281956).

**Review by malfet — APPROVED** [review]
LGTM, just checking that XLA pin update is intended.
Also, please note, that it could be landed via GitHub first as internal copy of functorch has been updated recently

**Pull request closed without merging**
