### PR TITLE
[cuSPARSE] Add ability to query `CUSPARSELT_MATMUL_ALG_CONFIG_MAX_ID` for a given workload

### PR DESCRIPTION
**Pull request by eqy**
Also use this value in tests instead of the previous hardcoded value of `4`

CC @syed-ahmed 

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jcaip @ptrblck @msaroufim @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @rec

### CODE REVIEW

**Review by syed-ahmed — APPROVED** [review]
LGTM (given CI failures are addressed).

**Review by malfet — COMMENTED** [review]
It would be nice to have a more in-depth explanation of what this PR is trying to achieve. If it's something about queuing what is possible and changing some settings, that I wonder if context manager like interface would be nice

**Comment by jcaip** [comment]
cc @malfet 

cuSPARSELt has some matul alg attributes, which I've observed can have a significant impact on performance, especially for the case of FP8. We don't currently have a good way to set this automatically. This PR attempts to solve this problem

With optimal ALG_ID:

Screenshot 2024-09-21 at 6 55 03 PM

With default ALG_ID:

Screenshot 2024-09-24 at 10 34 49 AM

cc @eqy I would agree with @syed-ahmed suggestion to have `_cslt_matmul_search` return all of the matmul attributes for us to cache. We can store them in the subclass and then add an inductor template to cache these during `torch.compile` since we'll now the matmul shapes ahead of time then.

I don't think adding a new private op is a good idea, it seems inefficient to grab each of these attributes individually. If we modify search to return all the matmul attributes we'll only need to run once.

**Pull request closed without merging**
