### PR TITLE
 Add file and line to CUDA_CHECK and CUDNN_CHECK

### PR DESCRIPTION
**Pull request by bstriner**
Add file and line to messages from `CUDA_CHECK` and `CUDNN_CHECK`. Renamed original functions to `cudaCheck` and `cudnnCheck` and made macros with the original names. Should make debugging slightly friendlier.

Also ran clang-format on the file.

Cheers

### CODE REVIEW

**Comment by bstriner** [comment]
Worth noting that CUDA_CHECK is now a macro not a function, so potentially redefines CUDA_CHECK from caffe2 if you include both headers at the same time.

Could potentially rename something like `AT_CUDA_CHECK` and `AT_CUDNN_CHECK`.

**Comment by soumith** [comment]
> Could potentially rename something like AT_CUDA_CHECK and AT_CUDNN_CHECK.

Yes please :)

**Comment by SsnL** [comment]
It might be better to just change those functions to use `AT_ERROR`.

Is this custom `cudnn_exception` necessary, @ezyang ?

**Comment by ezyang** [comment]
No, I don't think it is.

**Comment by bstriner** [comment]
Ok. If that's the case, I'll rewrite both of those checks as just defines that utilize `AT_ERROR` and rename with `AT_` prefixes. Will try to test that out tomorrow.

I like that AT_ERROR includes the function name in the error report as well. That is missing, for example, in TORCH_CUDA_CHECK. https://github.com/pytorch/pytorch/blob/master/torch/csrc/cuda/cuda_check.h

**Comment by bstriner** [comment]
@SsnL Great idea! AT_ERROR prints way better error messages than Exceptions.h was printing. Has function name, line, c stack and everything.

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
looks great, thanks Ben!

**Pull request merged**
