### PR TITLE
[C10D] Flight Recorder- TORCH_NCCL_DUMP_ON_TIMEOUT default to true

### PR DESCRIPTION
**Pull request by wconstab**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #114615
* #114817

Also defaults TORCH_NCCL_TRACE_BUFFER_SIZE to nonzero to enable the
feature

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @yf225 @kiukchung @lucasllc

### CODE REVIEW

**Comment by zdevito** [comment]
For testing, can we set the timeout very low,  then have a python driven test that intentionally times out by having a rank not issue the collective? Then check after the subprocesses exit that the dumps were created and can be unpicked.

**Review by fduwjj — COMMENTED** [review]
I am ok with turning it on by default, but do we want to a gradual roll out or we just do this directly?

**Review by fduwjj — APPROVED** [review]
Maybe we can increase the monitor timeout to longer time like 5 min?

**Comment by wconstab** [comment]
> Maybe we can increase the monitor timeout to longer time like 5 min?

ok but why? (i mean, is it related to turning on dumping, or is it just a generally good idea bc we're afraid its too short and killing jobs that shouldn't be killed?)

**Pull request closed without merging**
