### PR TITLE
Retire unsafe sparse tensor constructors in Python API

### PR DESCRIPTION
**Pull request by pearu**
This PR removes sparse tensor constructor functions `torch._sparse_coo/csr/csc/bsr/bsc/compressed_tensor_unsafe(...)` as unneeded. The equivalent functionality is provided via `torch.sparse_coo/csr/csc/bsr/bsc/compressed_tensor(..., check_invariants=False)`

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #91331

cc @alexsamardzic @nikitaved @cpuhrsch @amjames @bhosmer

### CODE REVIEW

**Comment by amjames** [comment]
Do we have any way to know how popular the unsafe constructors are/were with users? Although they are undocumented private methods, they did serve as an optimized path and users may have used them in production. It might be a courteous move to formally deprecate them with a warning + redirect.

**Comment by pearu** [comment]
Using `https://github.com/search?q=_sparse_coo_tensor_unsafe+language%3APython&type=code&l=Python` I found few users of `_sparse_coo_tensor_unsafe` (excluding pytorch itself):
- https://github.com/dmlc/dgl/issues/278 (from year 2018)
- https://github.com/tryingsomestuff/Minic/blob/759667773d17493beb65ddc31946fba6237795e2/Train/nnue_dataset.py#L43
- https://github.com/mlleon/Torch_Code/blob/af1c10b44c16d4d377597b5ee4a0492b78821fd3/dataParallel.py#L181
- https://github.com/BarclayII/dgl/blob/27e0e547dd9cb14f952ee1a2b490e64762ba2ff3/python/dgl/backend/pytorch/tensor.py#L40

For `_sparse_csr_tensor_unsafe`, I could not find any external users.

So, retiring `_sparse_coo_tensor_unsafe` with a deprecation step makes sense.
For compressed sparse layots, the deprecation step might be an overkill though, ihmo.

**Review by amjames — APPROVED** [review]
LGTM!

**Review by cpuhrsch — APPROVED** [review]

**Pull request closed without merging**
