### PR TITLE
Correct definition of nodes that work with Autograd

### PR DESCRIPTION
**Pull request by ilia-cher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#30683 Correct definition of nodes that work with Autograd**

Summary:
Assume that a node can work with autograd only if it is not a fusion
group and in prim or aten namespaces.

Test Plan: CI

Differential Revision: [D18795171](https://our.internmc.facebook.com/intern/diff/D18795171)

### CODE REVIEW

**Comment by lly-zero-one** [comment]
Fix the Linter error and also double check the failed tests?

**Comment by ilia-cher** [comment]
checking whether tests are related..

**Comment by ilia-cher** [comment]
Linter failure is an CI infra failure

**Comment by ilia-cher** [comment]
There're some CI infra issues in non-linter checks as well

**Comment by ezyang** [comment]
Rebase to master. Also is there a test you can add for this fix?

**Review by zdevito — COMMENTED** [review]
This is likely fine but it can use a test that it works, and an explanation for why the extra check is added as a comment in the code. I vaguely remember discussing this but I've forget why it's needed.

**Comment by ilia-cher** [comment]
will update addressing comments; it is needed because we inline some of the autodiff nodes back into the original torchscript, we run non-differentiable optimizations inside autodiff nodes and may accidentally introduce (e.g. custom, user-defined) nodes that are not aware of autograd

**Comment by ilia-cher** [comment]
added test, rebased, CI looks good

**Review by lly-zero-one — APPROVED** [review]
LGTM

**Pull request closed without merging**
