### PR TITLE
optimize transpose copy for float32 and bfloat16 on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #61015
* #58297
* __->__ #56904
* #66927
* #66929
* #56903
* #56902

Differential Revision: [D28836795](https://our.internmc.facebook.com/intern/diff/D28836795)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836795).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836795).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836795).

**Comment by mingfeima** [comment]
TODO: add benchmark numbers.

**Comment by mingfeima** [comment]
TODO: add AVX512 transpose kernel, since #61903 has been landed.

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836795).

**Comment by mingfeima** [comment]
TODO:
- [ ] use fbgemm

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28836795).

**Comment by VitalyFedyunin** [comment]
Hi, can you please attach benchmark numbers for avx2 and non avx processors

**Comment by mingfeima** [comment]
@VitalyFedyunin i was considering of dropping this one and hide the transpose optimizations in fbgemm (fbgemm already have fp32 and int8 optimized but lack bf16), which would be more decent.

**Comment by VitalyFedyunin** [comment]
It will break entire stack, lets land everything below first.

**Pull request closed without merging**
