### PR TITLE
Zero sized tensor support for repeat_interleave

### LINKED ISSUE #22753: repeat_interleave throws IndexError on repeating size-zero dimension
## 🐛 Bug

`torch.repeat_interleave(input, repeats, dim)` throws `IndexError` when `input.size(dim) == 0`. The corresponding `numpy.repeat` handles the size-zero case gracefully.

## To Reproduce

```
import torch
x = torch.zeros((5, 0))
y = torch.repeat_interleave(x, repeats=3, dim=1)
assert (y.shape == (5, 0))
>> IndexError: select(): index -1 out of range for tensor of size [0] at dimension 0
```

## Expected behavior

```
import numpy
x = numpy.zeros((5, 0))
y = numpy.repeat(x, repeats=3, axis=1)
assert (y.shape == (5, 0))
```

## Environment

PyTorch version: 1.1.0
CUDA used to build PyTorch: 9.0.176
OS: Ubuntu 16.04.4 LTS
Python version: 3.7
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4

(I have also tried on torch nightly version 1.2.0.dev20190711 and it has not been fixed.)

## Additional context

I think it would be more consistent and intuitive if `output.size(dim) == 0` whenever `input.size(dim) * repeats == 0`. The output size should be determined by the product of the input size in the appropriate dimension and the repeats (broadcasted). This is how the numpy version is designed.

For context, the converse works fine since the zero-dim does not participate:
```
import torch
x = torch.zeros((5, 0))
y = torch.repeat_interleave(x, repeats=3, dim=0)
assert (y.shape == (15, 0))
```

This one throws IndexError but is supported in numpy:
```
import torch
x = torch.tensor([], dtype=torch.int64)
y = torch.repeat_interleave(x, x)
>> IndexError: select(): index -1 out of range for tensor of size [0] at dimension 0
```
I think it makes sense for "repeating empty by empty" to vacuously yield empty (of same size as input).

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fixes https://github.com/pytorch/pytorch/issues/22753

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Test failure is unrelated

**Review by mrshenli — APPROVED** [review]
Thanks for the fix!

**Comment by gchanan** [comment]
@zasdfgbnm is there a reason that this function (repeat(Tensor)) is exposed at all?  It's not documented and it looks like an implementation detail.

**Comment by zasdfgbnm** [comment]
@gchanan It is actually documented
image

It is part of an implementation detail, but I feel it useful and it would be good to expose this as a shorter and faster way of doing `torch.arange(n).repeat_interleave(repeats)` when I originally implement `torch.repeat_interleave`.

My personal use case for this is:
I have a packed sequence `s = tensor([x1, x2, ..., xn, y1, y2, ..., ym, ....])` and a tensor storing the size of each sequence `counts = tensor([n, m, ...])`, and I want to have a tensor of the sequence  id for each element in `s`. In this case, I would do a `torch.repeat_interleave(counts)`.

**Pull request closed without merging**
