### PR TITLE
optimize channels last for BatchNorm2d on CPU

### PR DESCRIPTION
**Pull request by mingfeima**
replacement of #48919
optimize channels last performance for BatchNorm2 on CPU.

### CODE REVIEW

**Comment by mingfeima** [comment]
@VitalyFedyunin please check this one together with #58725, thanks!

**Review by VitalyFedyunin — APPROVED** [review]
Approve as copy of the existing PR

**Comment by VitalyFedyunin** [comment]
Upstream AvgPool PR has been merged, please rebase this one.

**Comment by mingfeima** [comment]
@VitalyFedyunin, rebased!

**Comment by VitalyFedyunin** [comment]
Hi @mingfeima looks like this PR led to regression #63224, can you please take a look.

**Pull request closed without merging**
