### PR TITLE
Trigger specialization when you call size()/stride() from C++

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #111935

This should be the last of the "it used to work with static shapes but
it doesn't work with dynamic shapes" hard errors.  Now we will just
specialize if you hit it from C++.

The strategy here is a bit clever.  We shunt the size() call to Python
binding if an error would have occurred.  Importantly, we already have
logic to make sure the newly allocated ints stay live for the duration
of the ArrayRef access.

storage_offset is intentionally omitted because there are some problems
with it.  I will fix them next.

This should let us get rid of the aotautograd_static test configuration.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by zou3519 — APPROVED** [review]
awesome!

**Comment by Chillee** [comment]
Is this actually a good idea 🤔

**Comment by ezyang** [comment]
We have plenty of tooling for detect when you overspecialize, so we've been moving in this direction (convert error into specialization) for some time now.

**Pull request closed without merging**
