### PR TITLE
Implement demangle in Windows

### PR DESCRIPTION
**Pull request by peterjc123**
A missing feature recorded in #4092.

### CODE REVIEW

**Comment by soumith** [comment]
thanks!

**Comment by zhouzq-thu** [comment]
Hello, @peterjc123 and @soumith.

We need
```python
import re
```
at the top of this file.

**Comment by peterjc123** [comment]
@zhouzq-thu Yes, thanks for reminding me. A new PR is on this.

**Comment by Stonesjtu** [comment]
I include the import in PR #4519

**Pull request merged**
