### PR TITLE
Fix docstring errors in torch.nn.utils - prune.py/parametrizations.py/weight_norm.py

### LINKED ISSUE #112631: Fix docstring errors in weight_norm.py, parametrizations.py, prune.py
Please fix the following issues. To test locally, run: 
 ```
pydocstyle path-to-file --count
```
Run this command before and after fixing the errors. This command prints out the number of errors at the end of the output. Paste the output to your PR description with the number before and after. 
- **File**: `torch/nn/utils/prune.py`, **Entity**: ``, **Line**: 1, **Description**: One-line docstring should fit on one line with quotes (found 3)
- **File**: `torch/nn/utils/prune.py`, **Entity**: ``, **Line**: 1, **Description**: First line should end with a period (not 's')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `BasePruningMethod`, **Line**: 13, **Description**: 1 blank line required after class docstring (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `__call__`, **Line**: 21, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `__call__`, **Line**: 21, **Description**: First line should end with a period (not ')')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `compute_mask`, **Line**: 34, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `compute_mask`, **Line**: 34, **Description**: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply_mask`, **Line**: 53, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply_mask`, **Line**: 53, **Description**: First line should end with a period (not 'g')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 76, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 76, **Description**: First line should end with a period (not 'd')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 76, **Description**: First line should be in imperative mood (perhaps 'Add', not 'Adds')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `prune`, **Line**: 207, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `prune`, **Line**: 207, **Description**: First line should end with a period (not '`')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `prune`, **Line**: 207, **Description**: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `remove`, **Line**: 236, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `remove`, **Line**: 236, **Description**: First line should end with a period (not 'd')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `remove`, **Line**: 236, **Description**: First line should be in imperative mood (perhaps 'Remove', not 'Removes')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `PruningContainer`, **Line**: 266, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `add_pruning_method`, **Line**: 287, **Description**: First line should be in imperative mood (perhaps 'Add', not 'Adds')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `compute_mask`, **Line**: 319, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `compute_mask`, **Line**: 319, **Description**: First line should end with a period (not 's')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `compute_mask`, **Line**: 319, **Description**: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_combine_masks`, **Line**: 347, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_combine_masks`, **Line**: 347, **Description**: First line should end with a period (not '
- **File**: `torch/nn/utils/prune.py`, **Entity**: `Identity`, **Line**: 418, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `Identity`, **Line**: 418, **Description**: First line should end with a period (not 'e')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 430, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 430, **Description**: First line should end with a period (not 'd')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 430, **Description**: First line should be in imperative mood (perhaps 'Add', not 'Adds')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 483, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 483, **Description**: First line should end with a period (not 'd')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 483, **Description**: First line should be in imperative mood (perhaps 'Add', not 'Adds')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `L1Unstructured`, **Line**: 500, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `L1Unstructured`, **Line**: 500, **Description**: First line should end with a period (not 's')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 541, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 541, **Description**: First line should end with a period (not 'd')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 541, **Description**: First line should be in imperative mood (perhaps 'Add', not 'Adds')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `compute_mask`, **Line**: 585, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `compute_mask`, **Line**: 585, **Description**: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 648, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 648, **Description**: First line should end with a period (not 'd')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 648, **Description**: First line should be in imperative mood (perhaps 'Add', not 'Adds')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `LnStructured`, **Line**: 667, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `LnStructured`, **Line**: 667, **Description**: First line should end with a period (not 'r')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `compute_mask`, **Line**: 691, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `compute_mask`, **Line**: 691, **Description**: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 761, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 761, **Description**: First line should end with a period (not 'd')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 761, **Description**: First line should be in imperative mood (perhaps 'Add', not 'Adds')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 807, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 807, **Description**: First line should end with a period (not 'd')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `apply`, **Line**: 807, **Description**: First line should be in imperative mood (perhaps 'Add', not 'Adds')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `identity`, **Line**: 820, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `identity`, **Line**: 820, **Description**: First line should end with a period (not 'e')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `identity`, **Line**: 820, **Description**: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `random_unstructured`, **Line**: 853, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `random_unstructured`, **Line**: 853, **Description**: First line should end with a period (not '`')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `l1_unstructured`, **Line**: 888, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `l1_unstructured`, **Line**: 888, **Description**: First line should end with a period (not '`')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `random_structured`, **Line**: 930, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `random_structured`, **Line**: 930, **Description**: First line should end with a period (not '`')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `ln_structured`, **Line**: 969, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `ln_structured`, **Line**: 969, **Description**: First line should end with a period (not '`')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `global_unstructured`, **Line**: 1014, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `global_unstructured`, **Line**: 1014, **Description**: First line should end with a period (not '`')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `custom_from_mask`, **Line**: 1136, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `custom_from_mask`, **Line**: 1136, **Description**: First line should end with a period (not '`')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `remove`, **Line**: 1170, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `remove`, **Line**: 1170, **Description**: First line should end with a period (not 'e')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `remove`, **Line**: 1170, **Description**: First line should be in imperative mood (perhaps 'Remove', not 'Removes')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `is_pruned`, **Line**: 1201, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `is_pruned`, **Line**: 1201, **Description**: First line should end with a period (not 'r')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_validate_pruning_amount_init`, **Line**: 1228, **Description**: First line should be in imperative mood (perhaps 'Validate', not 'Validation')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_validate_pruning_amount`, **Line**: 1262, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_validate_pruning_amount`, **Line**: 1262, **Description**: First line should end with a period (not 'e')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_validate_pruning_amount`, **Line**: 1262, **Description**: First line should be in imperative mood (perhaps 'Validate', not 'Validation')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_validate_structured_pruning`, **Line**: 1285, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_validate_structured_pruning`, **Line**: 1285, **Description**: First line should end with a period (not '-')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_validate_structured_pruning`, **Line**: 1285, **Description**: First line should be in imperative mood (perhaps 'Validate', not 'Validation')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_compute_nparams_toprune`, **Line**: 1304, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_compute_nparams_toprune`, **Line**: 1304, **Description**: First line should end with a period (not 'a')
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_validate_pruning_dim`, **Line**: 1328, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_validate_pruning_dim`, **Line**: 1328, **Description**: First line should end with a period (not '
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_compute_norm`, **Line**: 1338, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/prune.py`, **Entity**: `_compute_norm`, **Line**: 1338, **Description**: First line should end with a period (not 'n')
- **File**: `torch/nn/utils/parametrizations.py`, **Entity**: `_make_orthogonal`, **Line**: 23, **Description**: 1 blank line required between summary line and description (found 0)
- **File**: `torch/nn/utils/parametrizations.py`, **Entity**: `_make_orthogonal`, **Line**: 23, **Description**: No whitespaces allowed surrounding docstring text
- **File**: `torch/nn/utils/parametrizations.py`, **Entity**: `orthogonal`, **Line**: 178, **Description**: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
- **File**: `torch/nn/utils/parametrizations.py`, **Entity**: `weight_norm`, **Line**: 309, **Description**: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
- **File**: `torch/nn/utils/parametrizations.py`, **Entity**: `spectral_norm`, **Line**: 483, **Description**: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
- **File**: `torch/nn/utils/weight_norm.py`, **Entity**: ``, **Line**: 1, **Description**: One-line docstring should fit on one line with quotes (found 3)
- **File**: `torch/nn/utils/weight_norm.py`, **Entity**: ``, **Line**: 1, **Description**: First line should end with a period (not '8')
- **File**: `torch/nn/utils/weight_norm.py`, **Entity**: `weight_norm`, **Line**: 74, **Description**: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
- **File**: `torch/nn/utils/weight_norm.py`, **Entity**: `remove_weight_norm`, **Line**: 138, **Description**: First line should be in imperative mood (perhaps 'Remove', not 'Removes')

cc @carljparker

### PR DESCRIPTION
**Pull request by Senthi1Kumar**
Fixes #112631 

- torch/nn/utils/prune.py
**Before - 100**
```
torch\nn\utils\prune.py:1 at module level:
        D200: One-line docstring should fit on one line with quotes (found 3)
torch\nn\utils\prune.py:1 at module level:
        D400: First line should end with a period (not 's')
torch\nn\utils\prune.py:13 in public class `BasePruningMethod`:
        D204: 1 blank line required after class docstring (found 0)
torch\nn\utils\prune.py:21 in public method `__call__`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:21 in public method `__call__`:
        D400: First line should end with a period (not ')')
torch\nn\utils\prune.py:34 in public method `compute_mask`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:34 in public method `compute_mask`:
        D401: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
torch\nn\utils\prune.py:53 in public method `apply_mask`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:53 in public method `apply_mask`:
        D400: First line should end with a period (not 'g')
torch\nn\utils\prune.py:74 in public method `apply`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:74 in public method `apply`:
        D400: First line should end with a period (not 'd')
torch\nn\utils\prune.py:74 in public method `apply`:
        D401: First line should be in imperative mood (perhaps 'Add', not 'Adds')
torch\nn\utils\prune.py:200 in public method `prune`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:200 in public method `prune`:
        D400: First line should end with a period (not '`')
torch\nn\utils\prune.py:200 in public method `prune`:
        D401: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
torch\nn\utils\prune.py:229 in public method `remove`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:229 in public method `remove`:
        D400: First line should end with a period (not 'd')
torch\nn\utils\prune.py:229 in public method `remove`:
        D401: First line should be in imperative mood (perhaps 'Remove', not 'Removes')
torch\nn\utils\prune.py:256 in public class `PruningContainer`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:264 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\prune.py:277 in public method `add_pruning_method`:
        D401: First line should be in imperative mood (perhaps 'Add', not 'Adds')
torch\nn\utils\prune.py:297 in public method `__len__`:
        D105: Missing docstring in magic method
torch\nn\utils\prune.py:300 in public method `__iter__`:
        D105: Missing docstring in magic method
torch\nn\utils\prune.py:303 in public method `__getitem__`:
        D105: Missing docstring in magic method
torch\nn\utils\prune.py:307 in public method `compute_mask`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:307 in public method `compute_mask`:
        D400: First line should end with a period (not 's')
torch\nn\utils\prune.py:307 in public method `compute_mask`:
        D401: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
torch\nn\utils\prune.py:335 in private nested function `_combine_masks`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:335 in private nested function `_combine_masks`:
        D400: First line should end with a period (not ':')
torch\nn\utils\prune.py:404 in public class `Identity`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:404 in public class `Identity`:
        D400: First line should end with a period (not 'e')
torch\nn\utils\prune.py:410 in public method `compute_mask`:
        D102: Missing docstring in public method
torch\nn\utils\prune.py:416 in public method `apply`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:416 in public method `apply`:
        D400: First line should end with a period (not 'd')
torch\nn\utils\prune.py:416 in public method `apply`:
        D401: First line should be in imperative mood (perhaps 'Add', not 'Adds')
torch\nn\utils\prune.py:442 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\prune.py:447 in public method `compute_mask`:
        D102: Missing docstring in public method
torch\nn\utils\prune.py:469 in public method `apply`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:469 in public method `apply`:
        D400: First line should end with a period (not 'd')
torch\nn\utils\prune.py:469 in public method `apply`:
        D401: First line should be in imperative mood (perhaps 'Add', not 'Adds')
torch\nn\utils\prune.py:486 in public class `L1Unstructured`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:486 in public class `L1Unstructured`:
        D400: First line should end with a period (not 's')
torch\nn\utils\prune.py:498 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\prune.py:503 in public method `compute_mask`:
        D102: Missing docstring in public method
torch\nn\utils\prune.py:527 in public method `apply`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:527 in public method `apply`:
        D400: First line should end with a period (not 'd')
torch\nn\utils\prune.py:527 in public method `apply`:
        D401: First line should be in imperative mood (perhaps 'Add', not 'Adds')
torch\nn\utils\prune.py:564 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\prune.py:571 in public method `compute_mask`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:571 in public method `compute_mask`:
        D401: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
torch\nn\utils\prune.py:634 in public method `apply`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:634 in public method `apply`:
        D400: First line should end with a period (not 'd')
torch\nn\utils\prune.py:634 in public method `apply`:
        D401: First line should be in imperative mood (perhaps 'Add', not 'Adds')
torch\nn\utils\prune.py:653 in public class `LnStructured`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:653 in public class `LnStructured`:
        D400: First line should end with a period (not 'r')
torch\nn\utils\prune.py:669 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\prune.py:677 in public method `compute_mask`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:677 in public method `compute_mask`:
        D401: First line should be in imperative mood (perhaps 'Compute', not 'Computes')
torch\nn\utils\prune.py:747 in public method `apply`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:747 in public method `apply`:
        D400: First line should end with a period (not 'd')
torch\nn\utils\prune.py:747 in public method `apply`:
        D401: First line should be in imperative mood (perhaps 'Add', not 'Adds')
torch\nn\utils\prune.py:779 in public class `CustomFromMask`:
        D101: Missing docstring in public class
torch\nn\utils\prune.py:783 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\prune.py:786 in public method `compute_mask`:
        D102: Missing docstring in public method
torch\nn\utils\prune.py:793 in public method `apply`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:793 in public method `apply`:
        D400: First line should end with a period (not 'd')
torch\nn\utils\prune.py:793 in public method `apply`:
        D401: First line should be in imperative mood (perhaps 'Add', not 'Adds')
torch\nn\utils\prune.py:806 in public function `identity`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:806 in public function `identity`:
        D400: First line should end with a period (not 'e')
torch\nn\utils\prune.py:806 in public function `identity`:
        D401: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
torch\nn\utils\prune.py:839 in public function `random_unstructured`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:839 in public function `random_unstructured`:
        D400: First line should end with a period (not '`')
torch\nn\utils\prune.py:874 in public function `l1_unstructured`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:874 in public function `l1_unstructured`:
        D400: First line should end with a period (not '`')
torch\nn\utils\prune.py:916 in public function `random_structured`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:916 in public function `random_structured`:
        D400: First line should end with a period (not '`')
torch\nn\utils\prune.py:955 in public function `ln_structured`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:955 in public function `ln_structured`:
        D400: First line should end with a period (not '`')
torch\nn\utils\prune.py:1000 in public function `global_unstructured`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:1000 in public function `global_unstructured`:
        D400: First line should end with a period (not '`')
torch\nn\utils\prune.py:1120 in public function `custom_from_mask`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:1120 in public function `custom_from_mask`:
        D400: First line should end with a period (not '`')
torch\nn\utils\prune.py:1154 in public function `remove`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:1154 in public function `remove`:
        D400: First line should end with a period (not 'e')
torch\nn\utils\prune.py:1154 in public function `remove`:
        D401: First line should be in imperative mood (perhaps 'Remove', not 'Removes')
torch\nn\utils\prune.py:1184 in public function `is_pruned`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:1184 in public function `is_pruned`:
        D400: First line should end with a period (not 'r')
torch\nn\utils\prune.py:1211 in private function `_validate_pruning_amount_init`:
        D401: First line should be in imperative mood (perhaps 'Validate', not 'Validation')
torch\nn\utils\prune.py:1243 in private function `_validate_pruning_amount`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:1243 in private function `_validate_pruning_amount`:
        D400: First line should end with a period (not 'e')
torch\nn\utils\prune.py:1243 in private function `_validate_pruning_amount`:
        D401: First line should be in imperative mood (perhaps 'Validate', not 'Validation')
torch\nn\utils\prune.py:1265 in private function `_validate_structured_pruning`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:1265 in private function `_validate_structured_pruning`:
        D400: First line should end with a period (not '-')
torch\nn\utils\prune.py:1265 in private function `_validate_structured_pruning`:
        D401: First line should be in imperative mood (perhaps 'Validate', not 'Validation')
torch\nn\utils\prune.py:1284 in private function `_compute_nparams_toprune`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:1284 in private function `_compute_nparams_toprune`:
        D400: First line should end with a period (not 'a')
torch\nn\utils\prune.py:1308 in private function `_validate_pruning_dim`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:1308 in private function `_validate_pruning_dim`:
        D400: First line should end with a period (not ':')
torch\nn\utils\prune.py:1318 in private function `_compute_norm`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\prune.py:1318 in private function `_compute_norm`:
        D400: First line should end with a period (not 'n')
100
```
**After - 14**
```
torch\nn\utils\prune.py:260 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\prune.py:293 in public method `__len__`:
        D105: Missing docstring in magic method
torch\nn\utils\prune.py:296 in public method `__iter__`:
        D105: Missing docstring in magic method
torch\nn\utils\prune.py:299 in public method `__getitem__`:
        D105: Missing docstring in magic method
torch\nn\utils\prune.py:406 in public method `compute_mask`:
        D102: Missing docstring in public method
torch\nn\utils\prune.py:436 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\prune.py:441 in public method `compute_mask`:
        D102: Missing docstring in public method
torch\nn\utils\prune.py:489 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\prune.py:494 in public method `compute_mask`:
        D102: Missing docstring in public method
torch\nn\utils\prune.py:553 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\prune.py:656 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\prune.py:765 in public class `CustomFromMask`:
        D101: Missing docstring in public class
torch\nn\utils\prune.py:769 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\prune.py:772 in public method `compute_mask`:
        D102: Missing docstring in public method
14
```
- torch/nn/utils/parametrizations.py
**Before - 6**
```
torch\nn\utils\parametrizations.py:1 at module level:
        D100: Missing docstring in public module
torch\nn\utils\parametrizations.py:23 in private function `_make_orthogonal`:
        D205: 1 blank line required between summary line and description (found 0)
torch\nn\utils\parametrizations.py:23 in private function `_make_orthogonal`:
        D210: No whitespaces allowed surrounding docstring text
torch\nn\utils\parametrizations.py:178 in public function `orthogonal`:
        D401: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
torch\nn\utils\parametrizations.py:309 in public function `weight_norm`:
        D401: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
torch\nn\utils\parametrizations.py:483 in public function `spectral_norm`:
        D401: First line should be in imperative mood (perhaps 'Apply', not 'Applies')
6
```
**After - 1**
```
torch\nn\utils\parametrizations.py:1 at module level:
        D100: Missing docstring in public module
1
```
- torch/nn/utils/weight_norm.py
**Before - 10**
```
torch\nn\utils\weight_norm.py:1 at module level:
        D200: One-line docstring should fit on one line with quotes (found 3)
torch\nn\utils\weight_norm.py:1 at module level:
        D400: First line should end with a period (not '8')
torch\nn\utils\weight_norm.py:12 in public class `WeightNorm`:
        D101: Missing docstring in public class
torch\nn\utils\weight_norm.py:16 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\weight_norm.py:23 in public method `compute_weight`:       
        D102: Missing docstring in public method
torch\nn\utils\weight_norm.py:29 in public method `apply`:
        D102: Missing docstring in public method
torch\nn\utils\weight_norm.py:59 in public method `remove`:
        D102: Missing docstring in public method
torch\nn\utils\weight_norm.py:66 in public method `__call__`:
        D102: Missing docstring in public method
torch\nn\utils\weight_norm.py:73 in public function `weight_norm`:        
        D401: First line should be in imperative mood (perhaps 'Apply', not 'Applies')   
torch\nn\utils\weight_norm.py:137 in public function `remove_weight_norm`:
        D401: First line should be in imperative mood (perhaps 'Remove', not 'Removes')  
10
```
**After - 6**
```
torch\nn\utils\weight_norm.py:10 in public class `WeightNorm`:
        D101: Missing docstring in public class
torch\nn\utils\weight_norm.py:14 in public method `__init__`:
        D107: Missing docstring in __init__
torch\nn\utils\weight_norm.py:21 in public method `compute_weight`:
        D102: Missing docstring in public method
torch\nn\utils\weight_norm.py:27 in public method `apply`:
        D102: Missing docstring in public method
torch\nn\utils\weight_norm.py:57 in public method `remove`:
        D102: Missing docstring in public method
torch\nn\utils\weight_norm.py:64 in public method `__call__`:
        D102: Missing docstring in public method
6
```

cc @svekars @carljparker

### CODE REVIEW

**Comment by IamSenthilKumar** [comment]
cc @svekars

**Review by lezcano — APPROVED** [review]

**Comment by lezcano** [comment]
What happened to this PR?

**Comment by IamSenthilKumar** [comment]
> What happened to this PR?

Hi @lezcano, I tried to fix the lint errors, but the `lintrunner -a` accidentally  changed some files, so I closed this PR and will create a new one

**Comment by IamSenthilKumar** [comment]
Hey @lezcano, could you clarify me this, running `lintrunner -a` on the root repo will modify files or not, now I am running it each time in a particular folder, but it seems `flake8` and `mypy` always fails.

**Pull request closed without merging**
