### PR TITLE
Allow `tuple` of `Tensor` to be passed to `autograd.Function`

### PR DESCRIPTION
**Pull request by emcastillo**
This is a controversial change that may not be welcomed but let's discuss it here.

When calling a Function with a tuple of tensors, the tuple contents are not examined and the tensors are not marked as differentiable, so they are ignored. 
To support this one would say, use `*args` and then it works fine. The problem with this is that when supporting multiple inputs, then the input order can become difficult to follow since `autograd.Function` does not allow keyword arguments.
Due to this, it may be difficult to support cases such as creating functions to make `torch.distributed.*_multgpu` differentiable as I am doing in #40762, where I need to pass several attributes such as `src`, `group`, and the list of tensors with each of them living in a different GPU.

This is a very stupid snippet to show the behavior

```python
class TestFunc(Function):
    @staticmethod
    def forward(ctx, tensors):
        return tensors

    @staticmethod
    def backward(ctx, *grad_outputs):
        print(grad_outputs)
        tensors = [t + 1 for t in grad_outputs]
        return (tuple(tensors),)


tensors = (torch.ones(1, 5), torch.ones(1, 5), torch.ones(1, 5))

tensors[0].requires_grad = True
tensors[1].requires_grad = True
tensors[2].requires_grad = True

a, b, c = TestFunc.apply(tensors)

a = torch.sin(a) + 1
b = torch.cos(b) + 2
c = torch.tan(c) + 20

x = a.sum() + b.sum() + c.sum()
x.backward()
print(tensors[0].grad)
print(tensors[1].grad)
print(tensors[2].grad)
```

If you guys agree to merge this, I will add tests.

### CODE REVIEW

**Comment by albanD** [comment]
Hey!
Thanks for opening the discussion on this.

I do agree that this can be useful in some cases, we I am not sure if this is a good semantic to have.
In general in pytorch, we never unpack list/dict (both in autograd and torch.nn) and doing so here might be surprising.
Also having it working for tuple, but not list or other sequences, as well as just having the first level of nesting working and not others can be surprising.
Even more so when you know that, for the output, python is automatically unpacking one level of tuples. So you actually now support two levels of nesting for the return statement but just one for the input.

The problem I see from handling the more general case is then performance and the general fact that python objects can be very badly behaved (a list can point into itself). And so that's why we chose not to support it.

There is also a small BC-breaking issue that we need to handle if we want to go forward with this as well as the c++ equivalent.


What do you think about this?
Also cc @ezyang who might have an idea here.

**Comment by emcastillo** [comment]
Yeah, I agree with all that you say. I don't even feel very comfortable with this myself, it's just that I couldn't come up with a clean way to express args for #40762 when having to pass a list of tensors to the `autograd.Function` with other arbitrary arguments. Maybe making `autograd.Function.apply` support kwargs would be a better approach?
If so, do you have any idea to support such use case, (sequence of tensors mixed with other arguments) without doing this?

Thanks a lot!

**Comment by albanD** [comment]
> Maybe making autograd.Function.apply support kwargs would be a better approach?

You mean in a differentiable manner?
I think the main reason why we don't have it right now is because the semantic of the return of the `backward()` is not super clear. And wouldn't look as natural whatever we come up with.
Also it wouldn't fix the issue of passing multiple sequences of Tensors right?

>  If so, do you have any idea to support such use case, (sequence of tensors mixed with other arguments) without doing this?

This is not as seemless, but if you know that you only need to unpack one level of tuple, I would use some utility functions like:
```python

# Flatten arguments to give to custom Function
# only one level of tuples will be flattened
def flatten_args(*args):
    sizes = []
    res = []
    for arg in args:
        # You can handle other things than tuples
        # if needed
        if isinstance(arg, tuple):
            for el in arg:
                res.append(el)
            sizes.append(len(arg))
        else:
            res.append(arg)
            sizes.append(-1)

    return res + [sizes,]

# Unflatten arguments that was flattened above
def unflatten_args(*args):
    sizes = args[-1]
    args = args[:-1]
    res = []
    curr_idx = 0
    for size in sizes:
        if size == -1:
            res.append(args[curr_idx])
            curr_idx += 1
        else:
            res.append(tuple(args[curr_idx:curr_idx+size]))
            curr_idx += size

    return res


args = (1, 2, (3, 4), 5, 6)
print(args)
new_args = flatten_args(*args)
print(new_args)
recovered_args = unflatten_args(*new_args)
print(recovered_args)

```

**Comment by emcastillo** [comment]
I decided to go and make the `autograd.Function` functions module private and provide proxy functions for this with the args correctly lined up. 
I should have gone this way from the very beginning 😅
Thanks for the feedback!
I think we can close this PR if you guys think it goes against the codebase style.

**Pull request closed without merging**
