### PR TITLE
Do not import transformers when import torch._dynamo

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #124624
* __->__ #124634
* #124343

Fixes https://github.com/pytorch/pytorch/issues/123954

### CODE REVIEW

**Review by thiagocrepaldi — APPROVED** [review]

**Review by Chillee — APPROVED** [review]

**Comment by xuzhao9** [comment]
https://github.com/huggingface/safetensors/pull/318 has been merged, maybe this check can be skipped at all?

**Comment by ezyang** [comment]
please submit cherry pick to 2.3 branch

**Pull request closed without merging**
