### PR TITLE
Split set_default_tensor_type(dtype) into set_default_dtype(dtype).

### PR DESCRIPTION
**Pull request by gchanan**

### CODE REVIEW

**Comment by apaszke** [comment]
What's the difference between this one and `set_default_tensor_type`?

**Comment by gchanan** [comment]
It only sets the scalar type.

**Comment by apaszke** [comment]
Meaning... it changes the default tensor type but only to one with a different scalar type, but within the same device?

**Comment by apaszke** [comment]
Right, thanks for the explanation. Do we plan to deprecate the other function? Doesn't having two of those complicate the contract a bit (since one is type + device kind, other is only type)?

**Comment by gchanan** [comment]
I think we do eventually want to deprecate `set_default_tensor_type`; the issue is how to do that in a sensible and backwards compatible way.  E.g. the most straightforward addition would be `set_default_device` or `set_default_device_type`, (default of 'cpu'), but this has strange semantics, e.g.:

Today:
```
with torch.cuda.device(1):
   torch.randn((5,5)).type()
'torch.FloatTensor'
```

So, do I have to set the default device type to cuda before my cuda device ctx managers work?  Maybe the correct thing to do at the moment is to add `torch.device_ctx_manager` and `torch.device_of` managers and those manage the default tensor type and (if necessary) the current cuda device.  We still have more bits mapping to fewer bits, but we can recommend using these instead of the `cuda` equivalents and `default_tensor_types`, and they can eventually control something other than `default_tensor_type`.  Thoughts?

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
I agree; to me it seems a cuda device context manager should imply that we operate on cuda. It is totally unclear why you would ever want the other behavior.

**Comment by apaszke** [comment]
So does this imply that you get CPU arrays, unless you're in a `with device(0)` when factories return CUDA tensors by default? That's a breaking change.

**Comment by gchanan** [comment]
I don't know, I was just exploring the API space :).  We could add a `set_default_device_type` I guess.

**Pull request merged**
