### PR TITLE
Add F8 BLAS  data types conversion

### PR DESCRIPTION
**Pull request by malfet**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #106844
* #106842
* __->__ #106843

### <samp>🤖 Generated by Copilot at 54e843d</samp>

> _`Float8` types added_
> _to switch on `ScalarType` -_
> _CUDA version checked._

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by vkuzo** [comment]
i.e. if someone does `torch.randn(4, 4).cuda().to(torch.float8_e4m3fn)`, will the casts be hardware accelerated or go through the bit shifting path?

**Comment by malfet** [comment]
> to clarify, does this bind the unsaturated casts?

No, this is a no-op that simple adds BLAS dtypes, let me change the title to clarify what it does a bit better

**Pull request closed without merging**
