### PR TITLE
[just testing] perfkernel compilation in Windows

### PR DESCRIPTION
**Pull request by jspark1105**
Differential Revision: D13649029

### CODE REVIEW

**Comment by peterjc123** [comment]
There is some similar work in https://github.com/pytorch/pytorch/pull/15753 provided by @xkszltl.

**Comment by jspark1105** [comment]
@peterjc123 thanks for flagging. Yes I know. I'm trying to see the issues reported there and if there's a simpler way.

**Comment by xkszltl** [comment]
@jspark1105 I think the challenge is that, as I mentioned in https://github.com/pytorch/pytorch/pull/15753#issuecomment-451659002, MSVC mangles the local declaration into global namespace as `?adagrad_update_prefetch__avx_f16c@@YAXHPEBM0000PEAM111MM@Z` instead of under `caffe2` namespace.

But if you can get it work somehow, definitely let me know.

**Comment by jspark1105** [comment]
@xkszltl I'm basically trying to reproduce what you've seen to my own education. I'm using CI because I don't have an access to MSVC and Windows :) I think the issue is from MSVC bug also discussed in https://stackoverflow.com/questions/34559689/forward-declaring-a-function-in-a-namespace-inside-another-function-in-that-name

**Comment by jspark1105** [comment]
Closing because this was only for testing.

**Pull request closed without merging**
