### PR TITLE
Fix separate in process bisector cache, cleanup on exit

### PR DESCRIPTION
**Pull request by eellison**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #143662
* __->__ #143661
* #143657

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Review by ezyang — CHANGES_REQUESTED** [review]
This doesn't feel like it fixes the root cause? Concretely this will still cause separate processes to unpredictably affect each other if one is bisecting

**Comment by eellison** [comment]
Um, this doesn't work with threading (neither does torch.compile) but it does work with separate processes.

**Comment by ezyang** [comment]
Oh did you change that? The old code used the cache dir, which is shared across processes

**Review by ezyang — APPROVED** [review]
Ok I see it now. I still think this is overly complicated but yes I agree it is strict improvement (mostly due to the use of dedicated temp dir now)

**Pull request closed without merging**
