### PR TITLE
add type annotation to distributions.kl_divergence

### LINKED ISSUE #78431: [typing] distributions.kl_divergence return type is Tensor but not annotated
### 🐛 Describe the bug

Should add annotation.

### Versions

all versions

cc @fritzo @neerajprad @alicanb @nikitaved

### PR DESCRIPTION
**Pull request by ssnl**
Fixes #78431

### CODE REVIEW

**Review by fritzo — APPROVED** [review]
LGTM.  Could a Meta employee merge this please?

**Comment by SsnL** [comment]
@ejguan can you or someone help merging this?

**Review by ejguan — APPROVED** [review]

**Pull request closed without merging**
