### PR TITLE
Added complex types to get_all_dtypes and turned on masked_fill for complex

### LINKED ISSUE #36322: masked_fill not implemented for complex
>>> import torch
>>> x=torch.zeros(2,3, dtype=torch.cfloat)
>>> mask =torch.zeros(2,3,dtype=torch.long)
>>> mask[0][1]=1
>>> x.masked_fill(mask, 2+3j)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "masked_fill" not implemented for 'ComplexFloat'

cc @ezyang @anjali411 @dylanbespalko

### PR DESCRIPTION
**Pull request by anjali411**
1. Added complex dtypes to get_all_dtypes to unify testing for complex dtypes with other dtypes so that they don't get out of sync with behavior supported for other dtypes.
2. resolves https://github.com/pytorch/pytorch/issues/36322, https://github.com/pytorch/pytorch/issues/36327

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Review by pbelevich — APPROVED** [review]

**Comment by mruberry** [comment]
Unlanding. See error:

```
Apr 12 23:23:48 ======================================================================
Apr 12 23:23:48 ERROR [0.083s]: test_triu_tril_cuda (__main__.TestTorchDeviceTypeCUDA)
Apr 12 23:23:48 ----------------------------------------------------------------------
Apr 12 23:23:48 Traceback (most recent call last):
Apr 12 23:23:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 704, in wrapper
Apr 12 23:23:48     method(*args, **kwargs)
Apr 12 23:23:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 704, in wrapper
Apr 12 23:23:48     method(*args, **kwargs)
Apr 12 23:23:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 209, in instantiated_test
Apr 12 23:23:48     return test(self, device_arg)
Apr 12 23:23:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 404, in wrapper
Apr 12 23:23:48     fn(*args, **kwargs)
Apr 12 23:23:48   File "test_torch.py", line 9322, in test_triu_tril
Apr 12 23:23:48     run_test(s, device, d, dtype)
Apr 12 23:23:48   File "test_torch.py", line 9263, in run_test
Apr 12 23:23:48     res1 = torch_tri_func(x, diagonal=diagonal)
Apr 12 23:23:48 RuntimeError: name not implemented for 'ComplexFloat'
```

occurring on pytorch_linux_xenial_cuda10_1_cudnn7_py3_slow_test

**Comment by gchanan** [comment]
I'm wondering if this is the right change to make -- in Dispatch.h, complex numbers are not included in "all types", i.e. you have to use "_AND_COMPLEX_TYPES" or something. But here, they are included in "all types."  Independent of which is the correct choice, having one definition of "all types" seems preferable.

**Comment by anjali411** [comment]
> I'm wondering if this is the right change to make -- in Dispatch.h, complex numbers are not included in "all types", i.e. you have to use "_AND_COMPLEX_TYPES" or something. But here, they are included in "all types." Independent of which is the correct choice, having one definition of "all types" seems preferable.

yeah but a similar argument can also be made for bfloat16 and half dtypes which are not included in "all types" in Dispatch.h but are returned by all types in the method used in tests.

@gchanan The reason why I would like to add complex types to get_all_dtypes is so that complex dtypes are tested with other dtypes and don't get out of sync with the behavior expected for other dtypes. Including them in all types dispatch doesn't seem like a good idea since a lot of functions supported for float and int types are either not currently supported for complex or don't make sense for complex

**Comment by gchanan** [comment]
@anjali411 that seems orthogonal.  Like, here you are going in and skipping all the tests that don't actually work when you add complex to the list.  You could also replace all the instances with "...and_complex" and do the same thing.

**Comment by ezyang** [comment]
To me, it makes more sense for the terminal state to be "all dtypes includes complex". We had `ALL_TYPES_AND_COMPLEX` previously because the majority of operations did not support complex. As complex works proceeds, this will flip around, and we should update the macro naming.

I'm less sure about the intermediate state, but I'd personally not be *that* surprised if I saw that the dispatch macros and some Python testing enumeration disagree. But I might be special here :)

**Comment by gchanan** [comment]
@ezyang I think we agree about the terminal state, although it will take some effort because we consider the dispatch macros to require BC.  But I don't really see the argument that they should differ in the intermediate state -- as you said, most functions either support complex or they don't in implementation and that can determine whether complex is included by default or not.  But the same argument _must_ apply to the tests or something is wrong.

**Pull request closed without merging**
