### PR TITLE
[ROCm] Enable dist sharded_tensor test suites

### PR DESCRIPTION
**Pull request by jagadish-amd**
Following test suites are enabled on ROCm
test_sharded_tensor
test_sharded_tensor_reshard
test_sharding_plan

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd

### CODE REVIEW

**Comment by jaglinux** [comment]
The 3 test suites enabled passed on ROCm CI.
distributed/_shard/sharded_tensor/test_sharded_tensor_reshard 1/1 was successful
distributed/_shard/sharded_tensor/test_sharded_tensor 1/1 was successful
distributed/_shard/sharding_plan/test_sharding_plan 1/1 was successful

**Comment by jagadish-amd** [comment]
The 3 test suites enabled passed on ROCm CI.
distributed/_shard/sharded_tensor/test_sharded_tensor_reshard 1/1 was successful
distributed/_shard/sharded_tensor/test_sharded_tensor 1/1 was successful
distributed/_shard/sharding_plan/test_sharding_plan 1/1 was successful

**Review by jithunnair-amd — APPROVED** [review]

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
@malfet ,
Can you please review this PR.

**Review by malfet — APPROVED** [review]
More testing always sounds good

**Pull request closed without merging**
