### PR TITLE
Bump Gloo

### PR DESCRIPTION
**Pull request by petrex**
Feature includes

- Log message if bind(2) fail
- Make collective work with single process context
- Use hipStreamCreateWithFlags instead of hipStreamCreateWithPriority
- Add RCCl support

### CODE REVIEW

**Comment by colesbury** [comment]
@pietern anything to be aware of when upgrading gloo?

**Comment by pietern** [comment]
@colesbury Thanks for flagging. In general there isn't, as long as all builds are green. In this case, a few changes concerning ROCm and RCCL were merged, so especially the ROCm builds need to be green.

It looks like those are the only ones that are red though. @petrex can you investigate?

**Comment by petrex** [comment]
thanks @pietern. Pls refer to this [PR](https://github.com/facebookincubator/gloo/pull/193).

**Comment by pietern** [comment]
Thanks, @petrex. The Gloo PR is merged so this one can be updated.

**Comment by petrex** [comment]
The error is irreverent to this PR. @bddppq any feedback?

> 16:58:52 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHReduceApplyUtils.hip.o
16:58:52 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHBlas.hip.o
16:58:52 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHSleep.hip.o
16:58:52 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHStorage.hip.o
16:58:53 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHStorageCopy.hip.o
16:58:53 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensor.hip.o
16:58:54 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensorCopy.hip.o
16:58:54 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensorMath.hip.o
16:58:55 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensorMathBlas.hip.o
16:58:55 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensorMathMagma.hip.o
16:58:55 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensorMathPairwise.hip.o
16:58:55 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensorMathReduce.hip.o
16:58:56 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensorMathScan.hip.o
16:58:56 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensorIndex.hip.o
16:58:56 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensorRandom.hip.o
16:58:57 [ 42%] Building HIPCC object caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensorScatterGather.hip.o
16:58:57 In file included from /var/lib/jenkins/workspace/aten/src/THH/THHTensorRandom.hip:7:
16:58:57 In file included from /var/lib/jenkins/workspace/aten/src/THH/THHTensorRandom.cuh:9:
16:58:57 In file included from /opt/rocm/hiprand/include/hiprand_kernel.h:29:
16:58:57 In file included from /opt/rocm/hiprand/include/hiprand.h:55:
16:58:57 /opt/rocm/hiprand/include/hiprand_hcc.h:24:10: fatal error: 'rocrand.h' file not found
16:58:57 #include <rocrand.h>
16:58:57          ^~~~~~~~~~~
16:58:57 1 error generated.
16:58:57 In file included from /var/lib/jenkins/workspace/aten/src/THH/THHTensorRandom.hip:7:
16:58:57 In file included from /var/lib/jenkins/workspace/aten/src/THH/THHTensorRandom.cuh:9:
16:58:57 In file included from /opt/rocm/hiprand/include/hiprand_kernel.h:29:
16:58:57 In file included from /opt/rocm/hiprand/include/hiprand.h:55:
16:58:57 /opt/rocm/hiprand/include/hiprand_hcc.h:24:10: fatal error: 'rocrand.h' file not found
16:58:57 #include <rocrand.h>
16:58:57          ^~~~~~~~~~~
16:58:57 1 error generated.
16:58:57 CMake Error at /opt/rocm/hip/cmake/FindHIP/run_make2cmake.cmake:18 (file):
16:58:57   file failed to open for reading (No such file or directory):
16:58:57 
16:58:57     /var/lib/jenkins/workspace/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensorRandom.hip.o.depend.pre
16:58:57 
16:58:57 
16:58:57 CMake Error at torch_generated_THHTensorRandom.hip.o.cmake:134 (message):
16:58:57   Error generating
16:58:57   /var/lib/jenkins/workspace/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THH/./torch_generated_THHTensorRandom.hip.o
16:58:57 
16:58:57 
16:58:57 make[2]: *** [caffe2/CMakeFiles/torch.dir/__/aten/src/THH/torch_generated_THHTensorRandom.hip.o] Error 1
16:58:57 make[2]: *** Waiting for unfinished jobs....

**Comment by petrex** [comment]
The build error is most likely due to this [line](https://github.com/pytorch/pytorch/pull/23527/files#diff-af5515bdecc2d3a5260d6c2d7fe36cbdL135) in #23527 .

CI pass for #23527 because rocrand path is also set in Gloo project at the time being.

The rocrand path is **removed** from Gloo in this [PR](https://github.com/facebookincubator/gloo/pull/185/files#diff-ab764aae40e598c6aeadb935984e38c0L119), since Gloo is not using rocrand at all.

**Comment by petrex** [comment]
Fix to ci failure in this [PR](https://github.com/facebookincubator/gloo/pull/194)
Confirm CI pass in #23677

**Comment by pietern** [comment]
Gloo PR is being merged. When that is done, this PR can be updated, and we expect CI to pass.

**Comment by petrex** [comment]
PR updated and CI pass. The azure lint failure is not relevant here.

**Review by bddppq — APPROVED** [review]
LGTM

**Pull request closed without merging**
