### PR TITLE
Pass optional by reference

### PR DESCRIPTION
**Pull request by smessmer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#46598 Pass optional by reference**
* #46092 Make empty c10-full

This fixes perf issues due to optional<T> not being trivially relocatable even if T is trivially relocatable. We had seen a 4% regression because of that in #46092 and this PR here is stacked on top and improves perf by 6%, so both together improve perf by 2% (measured by callgrind instruction counts). 

See for details: https://fb.workplace.com/groups/pytorch.dev/permalink/768545893723893/
Benchmark: https://www.internalfb.com/intern/paste/P146297481/

Differential Revision: [D24425836](https://our.internmc.facebook.com/intern/diff/D24425836/)

### CODE REVIEW

**Review by bhosmer — APPROVED** [review]

**Comment by bhosmer** [comment]
At least some test failures look real though

**Comment by ezyang** [comment]
Probably bc breaking for backend implementers (I see xla failing, at the very least)

**Comment by swolchok** [comment]
https://github.com/pytorch/pytorch/pull/47015 is an alternative to this change.

**Comment by smessmer** [comment]
We decided to not land this because the benefit is much smaller after @swolchok's fixes to c10::optional (only 1.2% improvement now) and since passing by value is better code style.

**Pull request closed without merging**
