### PR TITLE
Add env variable to bypass CUDACachingAllocator for debugging

### PR DESCRIPTION
**Pull request by bertmaher**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#45294 Add env variable to bypass CUDACachingAllocator for debugging**

Summary: While tracking down a recent memory corruption bug we found that
cuda-memcheck wasn't finding the bad accesses, and @ngimel pointed out that
it's because we use a caching allocator so a lot of "out of bounds" accesses
land in a valid slab.

This PR adds a runtime knob (`PYTORCH_CUDA_DEBUG_MEMORY`) that, when set,
bypasses the caching allocator's caching logic so that allocations go straight
to cudaMalloc.  This way, cuda-memcheck will actually work.

Test Plan: Insert some memory errors and run a test under cuda-memcheck;
observe that cuda-memcheck flags an error where expected.

Specifically I removed the output-masking logic here:
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/tensorexpr/cuda_codegen.cpp#L819-L826

And ran:
```
PYTORCH_CUDA_DEBUG_MEMORY=1 cuda-memcheck pytest -k test_superslomo test_jit_fuser_te.py
```

Differential Revision: [D23964734](https://our.internmc.facebook.com/intern/diff/D23964734)

### CODE REVIEW

**Comment by bertmaher** [comment]
So this is a pretty minimal debug path for the cuda allocator; I'd love some advice on whether this is a reasonable approach, and whether there's anything else I should be doing here.  Also, suggestions for perf testing would be great -- I think we have an operator overhead bench that I'll try out, anything else?  It seems like a perf-sensitive path so with any luck it doesn't slow that down.

**Review by dzhulgakov — APPROVED** [review]
Looks good. Maybe call it `PYTORCH_NO_CUDA_MEMORY_CACHING` or something like that? 'debugging' implies some fancy tool/report

**Comment by ezyang** [comment]
Yeah, this looks fine, but agreed with Dmytro on env var renaming. You should also think about where to document this option.

**Comment by ngimel** [comment]
This section https://pytorch.org/docs/master/cuda.html#memory-management looks like a reasonable place for documentation

**Pull request closed without merging**
