### PR TITLE
[DataPipe] Unifying API - removing options to have fn_args and fn_kwargs from MapDataPipes

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #69561
* #69560

Differential Revision: [D32952099](https://our.internmc.facebook.com/intern/diff/D32952099)

cc @VitalyFedyunin @ejguan @NivekT

### CODE REVIEW

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32952099).

**Review by ejguan — APPROVED** [review]
LGTM. Could you please also remove the in-line doc?

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32952099).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32952099).

**Pull request closed without merging**
