### PR TITLE
Symintify `broadcast_to`

### PR DESCRIPTION
**Pull request by nkaretnikov**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #88776

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
The test changes are shocking lol, but I can believe it I guess?

**Comment by nkaretnikov** [comment]
Note: the test that failed seems flaky. I couldn't reproduce locally on M1/Linux. Added a skip.

**Comment by ezyang** [comment]
We should investigate the flakiness, but this is fine for now. Can you file a bug on it

**Pull request closed without merging**
