### PR TITLE
Lazier CUDA initialization

### LINKED ISSUE #2517: CUDA error (3): initialization error (multiprocessing)
**Summary by @ezyang.** If you are using multiprocessing code, and are in Python 3, you can work around this problem by adding `mp.set_start_method('spawn')` to your script. Otherwise, to work around, you need to make sure there are no CUDA calls prior to starting your subprocesses; `torch.cuda.is_available()` and `torch.manual_seed` both count as a CUDA calls in PyTorch 0.2.0.

----

 Run <https://github.com/ikostrikov/pytorch-a3c> using pytorch 0.2.0, python 2.7 with error

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDA error (3): initialization error
```

occur on this those lines:
<https://github.com/ikostrikov/pytorch-a3c/blob/842ec4da82df3d2dda02943d881c6b577f078ab9/train.py#L105-L111>

while using pytorch 0.12.0 works fine

### PR DESCRIPTION
**Pull request by ezyang**
Make CUDA seeding/RNG state functions even lazier

Instead of initializing CUDA immediately and executing them,
we wait until we actually initialize CUDA before executing.
    
Fixes #2517

### CODE REVIEW

**Comment by ezyang** [comment]
Unfortunately, this patch, while doing what it says on the tin, isn't "good enough", because `torch.cuda.is_available` still initializes the CUDA driver (because it calls `getDeviceCount`)

**Comment by ezyang** [comment]
(I don't think this patch does any harm, but it probably doesn't actually fix the report in #2517)

**Comment by ezyang** [comment]
The current patch does several things:

1. It fixes @floringogianu's example, because manual_seed no longer calls `is_available`, and the CUDA seeding functions are now lazy, so the driver won't get initialized

2. It improves the error message when the CUDA driver was initialized, but we didn't notice it from PyTorch

I think this should be "good enough" for most people.

**Review by soumith — APPROVED** [review]

**Comment by soumith** [comment]
thanks Ed!

**Comment by Amir-Arsalan** [comment]
@ezyang Has there been any updates on this? I do not even do `import torch` before I call `multiprocessing.Process` process via the `.start()` function but I get the following error:

 ```
File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (3) : initialization error at /pytorch/aten/src/THC/THCGeneral.cpp:51
```

So basically: 1) I run the process 2) do `import torch` inside of the `fork`ed process 3) convert a Numpy tensor to a PyTorch tensor 4) transfer the PyTorch tensor to GPU via the `.cuda()` function. 5) The above error is thrown

**Comment by Amir-Arsalan** [comment]
@soumith Has there been any changes to lazy CUDA initialization in the past 2-3 months? I used to run multiple processes and would initialize CUDA within each of them, but it looks like using any version of PyTorch since 2-3 months ago I cannot do this anymore and I get the following error:

`THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=51 error=3 : initialization error`

When I use the older versions of PyTorch things seem to be working fine.

**Comment by soumith** [comment]
@Amir-Arsalan we had a regression, but if I remember it was fixed on master. @ezyang  do you remember?

**Pull request merged**
