### PR TITLE
Add CUTLASS-based support for mixed dtypes matrix multiplication

### PR DESCRIPTION
**Pull request by alexsamardzic**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #110934

cc @ptrblck @albanD

Differential Revision: [D50140556](https://our.internmc.facebook.com/intern/diff/D50140556)

### CODE REVIEW

**Comment by alexsamardzic** [comment]
This PR is just PRs #107782 and #109712 squashed.

The size of `libtorch_cuda.so` gets increased for about 0.35% by this PR.

**Comment by alexsamardzic** [comment]
<details>
 <summary>Benchmarking script (vs. cuBLAS)</summary>

```Python
import random
import torch
import torch.utils.benchmark as benchmark

from itertools import product
from torch.testing import make_tensor

import torch._inductor.config as inductor_config

device = "cuda"
dtype = torch.float16

torch.set_printoptions(
    precision=3,
    threshold=None,
    edgeitems=4,
    linewidth=460,
    profile=None,
    sci_mode=False,
)


if __name__ == "__main__":
    shapes = [
        # (8, 16, 16),
        # distilbert shapes
        (768, 3072, 768),
        (3072, 768, 3072),
        # jiecao shapes
        (1024, 1536, 2048),
        (1024, 9408, 2048),
        (1024, 3200, 2048),
        (1024, 256, 9472),
        (1024, 10240, 256),
        (1024, 256, 12608),
        (1024, 2560, 1024),
        (1024, 512, 10240),
        (1024, 10240, 512),
        (1024, 2048, 1024),
        (1024, 512, 512),
        (1024, 1024, 1024),
        (1024, 2048, 2048),
        (2048, 1536, 2048),
        (2048, 9408, 2048),
        (2048, 3200, 2048),
        (2048, 256, 9472),
        (2048, 10240, 256),
        (2048, 256, 12608),
        (2048, 2560, 1024),
        (2048, 512, 10240),
        (2048, 10240, 512),
        (2048, 2048, 1024),
        (2048, 512, 512),
        (2048, 1024, 1024),
        (2048, 2048, 2048),
    ]
    batch_sizes = [1, 4]
    dtypeqs = [torch.int8] ### FIXME: add this: , torch.quint4x2]

    for dtypeq in dtypeqs:
        results = []
        for (m, k, n), batch_size in product(shapes, batch_sizes):
            print(f"m = {m:5d}, k = {k:5d}, n = {n:5d}, batch_size = {batch_size:1d}")
            # label and sub_label are the rows
            # description is the column
            try:
                label = "cuBLAS vs. CUTLASS"
                label += f" ({dtype} x {dtypeq} mixed GEMM)"
                sub_label = (
                    f"m:{m:5d} | k:{k:5d} | n:{n:5d} | batch_size: {batch_size:4d}"
                )

                val_lo, val_hi = 0.1, 1
                valq_lo, valq_hi = 1, 3
                input = make_tensor(
                    batch_size,
                    m,
                    k,
                    low=val_lo,
                    high=val_hi,
                    dtype=torch.float16,
                    device=device,
                )
                weight = make_tensor(
                    k, n, low=valq_lo, high=valq_hi, dtype=torch.int8, device=device
                )

                input_cublas = input.reshape(-1, input.shape[-1])
                weight_cublas = weight.to(input.dtype)
                output_cublas = torch.mm(
                    input_cublas, weight_cublas
                ).reshape(*input.shape[:-1], n)

                weight_cutlass =  weight.t().contiguous().t()
                output_cutlass = torch.ops.aten._mixed_dtypes_mm(
                    input, weight_cutlass
                )
                torch.testing.assert_close(
                    output_cutlass, output_cublas, rtol=1e-3, atol=0
                )

                measurement = benchmark.Timer(
                    stmt="mm(input, weight)",
                    globals={
                        "mm": torch.mm,
                        "input": input_cublas,
                        "weight": weight_cublas,
                    },
                    label=label,
                    sub_label=sub_label,
                    description="cuBLAS latency",
                ).blocked_autorange()
                results.append(measurement)

                measurement = benchmark.Timer(
                    stmt="mm(input, weight)",
                    globals={
                        "mm": torch.ops.aten._mixed_dtypes_mm,
                        "input": input,
                        "weight": weight_cutlass,
                    },
                    label=label,
                    sub_label=sub_label,
                    description="CUTLASS latency",
                ).blocked_autorange()
                results.append(measurement)

            except Exception:
                continue

        compare = benchmark.Compare(results)
        compare.colorize(rowwise=True)
        compare.print()
```
</details>

**Comment by cpuhrsch** [comment]
@albanD - This PR is large, because it includes a lot of custom CUTLASS code for this particular kind of kernel. However future versions of CUTLASS will include support for this pattern, which means we'll be able to remove this code (again). So it's the same story as last time.

**Comment by alexsamardzic** [comment]
Merged as #110981.

**Pull request closed without merging**
