### PR TITLE
[reland][dynamo] Better support for nn.Module

### PR DESCRIPTION
**Pull request by anijain2305**
Relanding https://github.com/pytorch/pytorch/pull/88629

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

### CODE REVIEW

**Review by msaroufim — APPROVED** [review]

**Comment by malfet** [comment]
> @pytorchbot merge -f "CI passed earlier, trunk failing with unrelated errors"

@anijain2305 why do you think the failure was unrelated? It broke exactly the test it also broke in trunk, see https://hud.pytorch.org/minihud?name_filter=trunk%20/%20cuda11.6-py3.10-gcc7-sm86%20/%20test%20(default,%202,%204,%20linux.g5.4xlarge.nvidia.gpu)

**Comment by anijain2305** [comment]
@malfet thanks for noticing this. The CI passed fully just 2 hours ago, and I ignored the trunk tests. I  will be more careful next time

**Comment by malfet** [comment]
@anijain2305 do you still have a link by any chance? (I.e. it sounds like you are telling this is a land race and I'm curious what might have caused it)

**Pull request closed without merging**
