### PR TITLE
Fix parameterlist dir func error (#74404)

### PR DESCRIPTION
**Pull request by wukong1992**
Fixes #[74404](https://github.com/pytorch/pytorch/issues/74404)

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Could you give more details on why this is needed and what does it fix?

**Comment by wukong1992** [comment]
@albanD Sorry, I copy the wrong issue url. I had updated it.

**Review by albanD — APPROVED** [review]
Thanks for sharing the issue. Definitely an oversight when updating the code. Thanks for the fix.

**Comment by yueyericardo** [comment]
Thanks for the fix! 
Could we land this soon? 
We need this for our peoject.

**Comment by albanD** [comment]
@wukong1992 I force pushed your branch to rebase on master and make sure CI runs. If you need to use it locally, you can `git fetch` and `git reset --hard wukong1992/fix-paraeterlist-dir` to get the updated version.

**Pull request closed without merging**
