### PR TITLE
docs: fix formatting for embedding_bag

### LINKED ISSUE #43499: Format issue in `torch.nn.functional.embedding_bag`  documentation parameter section
#### Link

https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html#torch.nn.MultiheadAttention

#### API

`torch.nn.functional.embedding_bag`

#### Issue

In the "Parameters" section, there is an input :

**last element is the size of the input, or the ending index position of the last bag** (*The*) –

which should be part of the description for input argument `include_last_offset`

image

cc @jlin27

### PR DESCRIPTION
**Pull request by jeffydc**
fixes https://github.com/pytorch/pytorch/issues/43499

### CODE REVIEW

**Review by jbschlosser — COMMENTED** [review]
Thanks for the contribution! Since this is a pretty minor fix, would you mind fixing the formatting for the EmbeddingBag module docs as well?
Screen Shot 2021-03-25 at 9 19 47 AM

**Comment by ydcjeff** [comment]
@jbschlosser Sure, btw what does `offsets` in `EmbeddingBag` mean as I need to fix for module docs ?

**Comment by jbschlosser** [comment]
@ydcjeff EmbeddingBag optionally accepts a 1D input with bags of different sizes. In this case, `offsets` represents the starting index positions of each bag in `input` (i.e. it's used to delineate bag boundaries within the 1D input).

**Comment by ydcjeff** [comment]
Copied notes about `input` and `offset` to `forward` method

**Review by jbschlosser — APPROVED** [review]
lgtm! Thanks for taking care of this :)

**Comment by jbschlosser** [comment]
@ydcjeff When you get a chance, could you please do a rebase? There's some conflicts holding up the merge

**Pull request closed without merging**
