### PR TITLE
[cuda9] Fix deprecated CUDA wrap-level primitives

### PR DESCRIPTION
**Pull request by xw285cornell**
Update the deprecated CUDA wrap-level primitives to CUDA 9:

__shfl --> __shfl_sync
__ballot --> __ballot_sync
__any --> __any_sync

### CODE REVIEW

**Comment by xw285cornell** [comment]
/private/var/lib/jenkins/workspace/****-builds/py2-ios-macos10.13-build/ci_scripts/run_script.sh: line 37: scripts/build_ios.sh: No such file or directory

Some issues with the ios build system?

**Comment by soumith** [comment]
cc: @ngimel for review

**Comment by ngimel** [comment]
#8400 gets rid of deprecated primitives with more efficient kernels.

**Comment by xw285cornell** [comment]
Great certainly a much better solution!

**Pull request closed without merging**
