### PR TITLE
[SPMD] Allow IterGraph support a more general subgraph movement

### PR DESCRIPTION
**Pull request by fegin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #98285
* #98284
* #98182
* __->__ #97809

The original assumption of IterGraph is very restrictive and only allow users to move a subgraph that only one node has the input from external nodes. This PR fixes the limitation.

Differential Revision: [D44444398](https://our.internmc.facebook.com/intern/diff/D44444398/)

@diff-train-skip-merge

### CODE REVIEW

**Review by lessw2020 — APPROVED** [review]
lgtm!  (already reviewed internally and also worked with this code directly).

**Comment by weiwangmeta** [comment]
When its backout diff [D44679791](https://www.internalfb.com/diff/D44679791) lands internally, we will close this without merge.

**Comment by weiwangmeta** [comment]
The diff was backed out, closing this comment. Sorry about this. Maybe we should have considered resolving the conflict. Next time!

**Pull request closed without merging**
