### PR TITLE
Don't restore saved context for backwards

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105915

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
why not?

**Comment by ezyang** [comment]
https://fb.workplace.com/groups/1075192433118967/posts/836509424334290 but I'm still trying to better understand what exactly has gone wrong here

**Comment by ezyang** [comment]
Weird, this seems to pass tests...

**Comment by ezyang** [comment]
obsoluted by https://github.com/pytorch/pytorch/pull/105942#pullrequestreview-1546042291

**Pull request closed without merging**
