### PR TITLE
Simplify host_softmax

### PR DESCRIPTION
**Pull request by cyyever**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Do we just no use lofsoftmax or unmasked anymore? Or they're implemented with a different kernel now?

**Comment by cyyever** [comment]
> Do we just no use lofsoftmax or unmasked anymore? Or they're implemented with a different kernel now?

Not used after searching the code base.

**Review by albanD — APPROVED** [review]
Ok!
Thanks for the cleanup!

**Pull request closed without merging**
