### PR TITLE
FlexAttention Benchmark

### PR DESCRIPTION
**Pull request by joydddd**
1. Add alibi, sliding window, tahn softcap, prefixLM, and document_mask from attn_gym to benchmark. 

2. Add comparison to different SDPA backends & FAv2, FAv3, FAKV.

Dependent on https://github.com/pytorch/pytorch/pull/139639

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by joydddd** [comment]
This is the workflow used to generate results in FlexAttention paper. 

## Training: q_len = kv_len, forward & backward.

### Performance sweep for causal mask. 

```
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python -W ignore::UserWarning: benchmarks/transformer/score_mod.py -dtype bfloat16 -s 1024 4096 16384 65536 131072 --kv-size 256 --backend cudnn efficient math fav2 fav3 -mods causal -d 64 --calculate-bwd --throughput
```

###  performance sweep for different masks.
```
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python -W ignore::UserWarning: benchmarks/transformer/score_mod.py -dtype bfloat16 -s 16384 --kv-size 256 --backend cudnn efficient math fav2 fav3 -mods noop causal alibi sliding_window document_mask prefix_lm softcap -d 64 --calculate-bwd --throughput
```

## Decoding
### Performance Sweep for noop mask.
```
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python -W ignore::UserWarning: benchmarks/transformer/score_mod.py -dtype bfloat16 -s 1024 4096 16384 65536 131072  --kv-size 256 --backend cudnn efficient math fakv -mods noop -d 64 --throughput --decoding
```

### Performance on different masks. 
```
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python -W ignore::UserWarning: benchmarks/transformer/score_mod.py -dtype bfloat16 -s 65536 --kv-size 256 --backend cudnn efficient math fakv -mods noop causal alibi softcap -d 64 --decoding --throughput
```

**Review by drisspg — APPROVED** [review]
I think land the other then we can land this one

**Pull request closed without merging**
