### PR TITLE
Add optional coalesce argument to values(), indices(), and to a new method nse()

### PR DESCRIPTION
**Pull request by pearu**
This PR is a follow-up to the discussion in https://github.com/pytorch/pytorch/pull/45400#discussion_r497050628: 
- [x] `indices(coalesce=True)` - return the indices of coalesced tensor, `indices(False)` is identical to `_indices()`.
- [x] `values(coalesce=True)` - return the values of coalesced tensor, `values(False)` is identical to `_values()`.
- [x] `nse(coalesce=True)` - return the number of specified elements of a coalesced tensor. `nse(False)` is identical to `_nnz()`.
- [x] document `coalesce` argument in `indices`, `values`, `nse` docstrings.
- [x] Replace `_indices()` with `indices(False)` everywhere in Python code.
- [x] Replace `_values()` with `values(False)` everywhere in Python code.
- [x] Replace `_nnz()` with `nse(False)` everywhere in Python code.
- [x] Deprecate the usage of `_indices`, `_values`, `_nse`: trigger a deprecation warning when users call these from Python.
- [ ] Create an issue for removing the deprecate method `_nnz` starting from PyTorch version 1.9:
- [x] Update torch.sparse documentation page: remove all occurrences of `_indices`, `_values`, `_nnz`; explain `coalesce=False` in uncoalesce COO tensor section; add a note that `coalesce` is not a cheap operation and suggest `coalesce` before processing the outputs of `indices/values/nse`.
- [x] Rename `nnz` to `nse` everywhere in Python/C++ code, update comments

At the C++ level, we'll continue using the underscore prefixed functions as unsafe API functions.

### Summary

The public Python API contains the following methods:
- `torch.Tensor.nse(coalesce=True)`
- `torch.Tensor.indices(coalesce=True)`
- `torch.Tensor.values(coalesce=True)`
that represent the COO storage format interface of PyTorch tensors with COO layout.

The usage of unsafe Python API methods, `torch.Tensor._nse()`, `torch.Tensor._indices()`, `torch.Tensor._values()`, is deprecated. However, the methods remain to exist in the Python API.

The public C++ API contains the following methods:
- `Tensor.nse(coalesce=true)`
- `Tensor.indices(coalesce=true)`
- `Tensor.values(coalesce=true)`

The unsafe C++ API contains the following methods:
- `Tensor._nse()` that is equivalent to `Tensor.nse(false)`
- `Tensor._indices()` that is equivalent to `Tensor.indices(false)`
- `Tensor._values()` that is equivalent to `Tensor.values(false)`

As a rule, C++ algorithms on tensors with COO layout use the unsafe C++ API.

The private Python/C++ API contains `torch.Tensor._values_coalesce()` (or `Tensor._values_coalesce()` in C++) method that usage is deprecated both in Python and C++ (except in calling it from `Tensor.values(coalesce)` implementation). The method was introduced to ensure that expression `values(True)` is differentiable while `values(False)` is not.

Out of all the above methods, only the expression `torch.Tensor.values(True)` (or `Tensor.values(true)` in C++) is differentiable.

The usage of `torch.Tensor._nnz()` (or `Tensor._nnz()` in C++) is deprecated and these methods will be removed in the future PyTorch release.

### CODE REVIEW

**Comment by pearu** [comment]
@mruberry, please review.

**Comment by mruberry** [comment]
@pearu let's give this a moment while we hash out the fundamental design issues. One of the things we talked about (briefly) was not exposing coalescing to users. I don't think that's likely to change but no need to rush this, right?

**Comment by pearu** [comment]
@mruberry, no hurry, we can revisit this PR once the fundamental design discussions are settled down.

**Comment by pearu** [comment]
> @pearu - do we still want to pursue this?

This PR implements no new functionality but introduces a few API changes in order to
1. get rid of internal methods `_values()` and `_indices()` that are exposed to users as public methods in sparse docs.
2. rename `_nnz()` to `nse()` as `_nnz()` functionality does not correspond to what the acronym "nnz" stands for.

Both make sense to me to improve exposing sparse tensors support to end-users but there appears to be no consensus on the importance nor acceptance of these items.

**Pull request closed without merging**
