### PR TITLE
Additions to functorch_scan

### PR DESCRIPTION
**Pull request by bohnstingl**
This PR will contain additions to the `functorch_scan` functionality initially created with the PR https://github.com/pytorch/pytorch/pull/104442

The initial changes contain:

1. Scan being moved to higher_order_ops
2. Docstring being added for scan/scan_impl
3. A testcase to torch/testing/_internal/control_flow_opinfo_db.py

The next step would be to enable inductor lowering for scan.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @websterbei @zou3519 @vadimkantorov @ydwu4

### CODE REVIEW

**Comment by bohnstingl** [comment]
By now, I introduced a few fixes to the scan functionality and made it more generic. Correspondingly, new test cases have been added as well.

Currently, I am working on the inductor lowering of the scan function. I tried to stick to the approach from https://github.com/pytorch/pytorch/pull/109132 and the FX graph looks okay to me.

User-code:
```
@torch.compile(backend='inductor', fullgraph=True)
def f(carry, x):
    return carry+1, x+carry

init = torch.rand(1, 2, device=torch.device('cuda'))
xs = torch.rand(10, 1, 2, device=torch.device('cuda'))
scan_comp = torch.compile(scan, backend='inductor', fullgraph=True)
carry_out, ys = scan_comp(fc, init, xs)
```

Graph:
```
graph():
    %arg0_1 : [#users=1] = placeholder[target=arg0_1]
    %arg1_1 : [#users=1] = placeholder[target=arg1_1]
    %arg2_1 : [#users=0] = placeholder[target=arg2_1]
    %arg3_1 : [#users=1] = placeholder[target=arg3_1]
    %body_graph_0 : [#users=1] = get_attr[target=body_graph_0]
    %scan_impl : [#users=2] = call_function[target=torch.ops.scan_impl](args = (%body_graph_0, (%arg0_1,), (%arg1_1,)), kwargs = {reverse: False})
    %getitem : [#users=1] = call_function[target=operator.getitem](args = (%scan_impl, 0), kwargs = {})
    %getitem_1 : [#users=1] = call_function[target=operator.getitem](args = (%getitem, 0), kwargs = {})
    %getitem_2 : [#users=1] = call_function[target=operator.getitem](args = (%scan_impl, 1), kwargs = {})
    %getitem_3 : [#users=1] = call_function[target=operator.getitem](args = (%getitem_2, 0), kwargs = {})
    %unbind : [#users=1] = call_function[target=torch.ops.aten.unbind.int](args = (%getitem_1,), kwargs = {})
    %getitem_4 : [#users=1] = call_function[target=operator.getitem](args = (%unbind, 0), kwargs = {})
    return (getitem_4, getitem_3, arg3_1)
```

However, the `getitem` calls after the `scan` call are giving me trouble. This is because the scan function returns a TensorBox and the getitem calls cannot handle them. Thus, the graph execution fails. I wanted to ask whether somebody could please have a look at this and help me out? To reproduce the current status, you can run 
`python test/dynamo/test_higher_order_ops.py -k HigherOrderOpTests.test_scan`
@peterbell10 or @ydwu4 could you advice me how to resolve this and how to proceed from here?

**Comment by bohnstingl** [comment]
I have implemented preliminary steps to enable the lowering of the scan functionality. However, I am stuck and would need some help. In particular, currently the lowering takes the functionalized function `f` and places it as a "helper" function, here named `_triton_helper_fn0`,  in the triton code. The triton lowering of the scan then repetitively calls this function in a loop and collects the results.
This approach is suboptimal because the function `f` is itself not lowered, which may result in poor performance. For example, if the function is more complex, e.g., involving matrix multiplications, lowering the function itself might give a significant performance improvement, I think? So my problems in particular are:

1.) How to first lower the function `f` and then call it from the scan lowering?
2.) How to more efficiently return two TensorBoxes rather than using two Pointwise nodes? https://github.com/pytorch/pytorch/blob/2d25cf799a85d09e77d1b9a72aa29ba4e38b15e9/torch/_inductor/lowering.py#L692

Currently, the inductor graph looks OK to me:
```
Graph
graph():
    %arg0_1 : [#users=1] = placeholder[target=arg0_1]
    %arg1_1 : [#users=1] = placeholder[target=arg1_1]
    %body_graph_0 : [#users=1] = get_attr[target=body_graph_0]
    %scan_impl : [#users=2] = call_function[target=torch.ops.scan_impl](args = (%body_graph_0, (%arg0_1,), (%arg1_1,)), kwargs = {reverse: False})
    %getitem : [#users=1] = call_function[target=operator.getitem](args = (%scan_impl, 0), kwargs = {})
    %getitem_1 : [#users=1] = call_function[target=operator.getitem](args = (%getitem, 0), kwargs = {})
    %getitem_2 : [#users=1] = call_function[target=operator.getitem](args = (%scan_impl, 1), kwargs = {})
    %getitem_3 : [#users=1] = call_function[target=operator.getitem](args = (%getitem_2, 0), kwargs = {})
    %select_1 : [#users=1] = call_function[target=torch.ops.aten.select.int](args = (%getitem_1, 0, -1), kwargs = {})
    %slice_4 : [#users=1] = call_function[target=torch.ops.aten.slice.Tensor](args = (%select_1, 0, 0, 9223372036854775807), kwargs = {})
    return (slice_4, getitem_3)
```
and the current triton lowering leads to something like:
```
import triton
import triton.language as tl
from torch._inductor.ir import ReductionHint
from torch._inductor.ir import TileHint
from torch._inductor.triton_heuristics import pointwise
from torch._inductor.utils import instance_descriptor
from torch._inductor import triton_helpers

@triton.jit
def _triton_helper_fn0(arg0, arg1):
    return ('arg0', 'arg1')

@pointwise(size_hints=[32], filename=__file__, meta={'signature': {0: '*fp32', 1: '*fp32', 2: '*fp32', 3: 'i32'}, 'device': 0, 'constants': {}, 'mutated_arg_names': [], 'configs': [instance_descriptor(divisible_by_16=(0, 1, 2), equal_to_1=())]})
def KERNEL_NAME(in_ptr0, in_ptr1, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 20
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset  + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (2))
    tmp1 = tl.broadcast_to(tmp0, [XBLOCK])
    tmp2 = tl.load(in_ptr1 + (22))
    tmp3 = tl.broadcast_to(tmp2, [XBLOCK])
    tmp4 = tl.full([32], 1, tl.float32)
    tmp5 = tl.load(in_ptr1 + tl.arange(0, 2))
    o_loop = forward(tmp1, tmp5)
    tmp6 = tl.load(in_ptr1 + tl.arange(2, 4))
    o_loop = forward(tmp1, tmp6)
    [...]
    tl.store(out_ptr0 + (x0), tmp6, xmask)
```
To reproduce, one can run `python test/inductor/test_torchinductor.py -k test_scan_simple`

@peterbell10 could you please help me out with my issues? I would be more than happy if we can setup a discussion. I also tried to integrate this non-associative scan functionality in your effort under https://github.com/pytorch/pytorch/pull/109132 and I have a separate branch for this https://github.com/bohnstingl/pytorch/tree/gh/bohnstingl/1/base

**Comment by bohnstingl** [comment]
I made some baby steps towards the resolution of the problem that I mentioned above. In particular, I first manually `torch.compiled` the function `f` and then passed it as a string argument to the scan lowering. Then in the scan-part of `triton.py` I repeatedly call this pre-compiled function. For simplicity I worked with 

```
def f(carry, x):
    return carry+1, x+1
```
which for both the new `carry` and the new `output` compiles to 
```
@triton.jit
def forward(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (x0), xmask)
    tmp1 = 1.0
    tmp2 = tmp0 + tmp1
    tl.store(out_ptr0 + (x0), tmp2, xmask)
```

Using this pre-compiled function, the result is the snippet below which works. (Apart from maybe some inefficiencies in the autotuning.) 

```
@triton.jit
def forward(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (x0), xmask)
    tmp1 = 1.0
    tmp2 = tmp0 + tmp1
    tl.store(out_ptr0 + (x0), tmp2, xmask)

@pointwise(
    size_hints=[8], 
    filename=__file__,
    triton_meta={'signature': {0: '*fp32', 1: '*fp32', 2: '*fp32', 3: 'i32'}, 'device': 0, 'device_type': 'cuda', 'constants': {}, 'configs': [instance_descriptor(divisible_by_16=(0, 1, 2), equal_to_1=(), ids_of_folded_args=(), divisible_by_8=())]},
    inductor_meta={'autotune_hints': set(), 'kernel_name': 'Placeholder.DESCRIPTIVE_NAME', 'mutated_arg_names': []},
    min_elem_per_thread=0
)
@triton.jit
def Placeholder.KERNEL_NAME(in_ptr0, in_ptr1, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 6
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (2))
    tmp1 = tl.broadcast_to(tmp0, [XBLOCK])
    tmp2 = tl.load(in_ptr1 + (8))
    tmp3 = tl.broadcast_to(tmp2, [XBLOCK])
    tmp4 = tl.full((3, 1, 2), 1, tl.float32)
    tmp5 = tl.load(in_ptr1 + (0))
    forward(in_ptr1 + (0), out_ptr0 + (0), 2, 2)
    tmp6 = tl.load(in_ptr1 + (2))
    forward(in_ptr1 + (2), out_ptr0 + (2), 2, 2)
    tmp7 = tl.load(in_ptr1 + (4))
    forward(in_ptr1 + (4), out_ptr0 + (4), 2, 2)
```

My main question is still how to obtain the `triton.jit` compiled code of the function `f` before the code for the scan operation gets generated in `triton.py`? Is there some pre-hook that I could use in order to get the function `f` compiled before the scan operation is lowered? If this is the case, then the scan operation on the triton level could just repetitively invoke this pre-compiled function `f` and the scan operation would be very close.

@ezyang @peterbell10 @ydwu4 any help on this is greatly appreciated!

**Comment by ezyang** [comment]
If you're willing to spelunk in inductor, you want something similar to how we do epilogue fusion (where there's a fragment of code and you compile it into a string that gets interpolated into the template.) @peterbell10 and @Chillee really are the experts here though.

**Pull request closed without merging**
