### PR TITLE
Use python3 -m to fix tools not being found

### PR DESCRIPTION
**Pull request by janeyx99**
Uploading test stats have not been doing great due to this error
https://github.com/pytorch/pytorch/runs/6866279385?check_suite_focus=true

In the past, using python3 -m has fixed this

### CODE REVIEW

**Review by suo — APPROVED** [review]
make sure to remove the submodule changes

**Comment by janeyx99** [comment]
@pytorchbot merge -f

Lint passes, we good

**Comment by malfet** [comment]
I like module based invocation better, but just curious, how did it work before?

**Comment by suo** [comment]
Previously it was a self-contained script; when we went from uploading one thing to two I pulled out common utilities

**Pull request closed without merging**
