### PR TITLE
Clarify how to get extra link flags when building CUDA/C++ extension

### PR DESCRIPTION
**Pull request by XapaJIaMnu-at-meta**
Make it a bit more explicit how one parse linker arguments to the build and point to the superclass documentation.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
need CLA

**Comment by XapaJIaMnu-at-meta** [comment]
> need CLA

I am a Meta employee, I have applied for CLA, but not sure how long that would take/if I did it with the right person.

**Comment by ezyang** [comment]
Hmm, you should have been auto approved CLA then...

**Comment by ezyang** [comment]
@kit1980 says "The person needs to add [nbogoych@meta.com](mailto:nbogoych@meta.com) to the github profile and comment /easycla"

**Comment by XapaJIaMnu-at-meta** [comment]
Ok seems to work now. Ready to merge.

**Pull request closed without merging**
