### PR TITLE
Update cuda_to_hip_mappings.py

### PR DESCRIPTION
**Pull request by amoskvic**
Added one datatype mapping (cuda_bf16.h), and a number of cub/hipcub mappings. Note: the missing mappings were discovered when hipifying the Mamba model's (https://github.com/state-spaces/mamba) forward kernel.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]
LGTM, @amoskvic please sign individual CLA

**Comment by amoskvic** [comment]
@jithunnair-amd done!

**Review by Skylion007 — APPROVED** [review]

**Comment by amoskvic** [comment]
Hi @jithunnair-amd @Skylion007 @jeffdaily! It looks like one of the checks (pull / linux-jammy-py3.8-gcc11 / build) has failed due to some AWS credentials issues. Would this delay the merge? Is there anything I could do to fix this? Please let me know. :)

**Comment by amoskvic** [comment]
@jeffdaily Hi Jeff, thanks for adding the "not user facing" label. Sorry to bug you again, but it looks like the merge bot was not triggered after the label was added.

**Pull request closed without merging**
