### PR TITLE
[dynamo] Add run_inductor_tests entrypoint

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #113278

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler

### CODE REVIEW

**Review by yanboliang — APPROVED** [review]

**Comment by huydhn** [comment]
@pytorchbot revert -m 'Sorry for reverting your stack, but it is failing to list test internally with buck2' -c ghfirst

The error https://www.internalfb.com/sandcastle/workflow/2476979795055236508 is as follows:

```
==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
../buck-out/v2/gen/fbcode/6081734815403318/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/caffe2/test/dynamo/test_dynamic_shapes.py:10: in <module>
    test_aot_autograd = load_test_module(__file__, "dynamo.test_aot_autograd")
../buck-out/v2/gen/fbcode/6081734815403318/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/torch/_dynamo/testing.py:399: in load_test_module
    return SourceFileLoader(wanted_module, str(target)).load_module()
<frozen importlib._bootstrap_external>:462: in _check_name_wrapper
    ???
<frozen importlib._bootstrap_external>:962: in load_module
    ???
<frozen importlib._bootstrap_external>:787: in load_module
    ???
<frozen importlib._bootstrap>:265: in _load_module_shim
    ???
<frozen importlib._bootstrap>:702: in _load
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:783: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
../buck-out/v2/gen/fbcode/6081734815403318/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/caffe2/test/dynamo/test_aot_autograd.py:28: in <module>
    lib = torch.library.Library("custom", "DEF")
../buck-out/v2/gen/fbcode/6081734815403318/caffe2/test/dynamo/__test_dynamo__/test_dynamo#link-tree/torch/library.py:62: in __init__
    self.m: Optional[Any] = torch._C._dispatch_library(kind, ns, dispatch_key, filename, lineno)
E   RuntimeError: Only a single TORCH_LIBRARY can be used to register the namespace custom; please put all of your definitions in a single TORCH_LIBRARY block.  If you were trying to specify implementations, consider using TORCH_LIBRARY_IMPL (which can be duplicated).  If you really intended to define operators for a single namespace in a distributed way, you can use TORCH_LIBRARY_FRAGMENT to explicitly indicate this.  Previous registration of TORCH_LIBRARY was registered at /dev/null:168; latest registration was registered at /dev/null:219
```

**Pull request closed without merging**
