### PR TITLE
Fix creation_meta for multi view outputs in NoGradMode/InferenceMode.

### PR DESCRIPTION
**Pull request by ailzhang**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#57842 Fix creation_meta for multi view outputs in NoGradMode/InferenceMode.**

Differential Revision: [D28295649](https://our.internmc.facebook.com/intern/diff/D28295649)

### CODE REVIEW

**Comment by ailzhang** [comment]
@ailzhang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28295649).

**Comment by ailzhang** [comment]
@ailzhang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28295649).

**Review by albanD — APPROVED** [review]
LGTM thanks for the update

**Comment by ailzhang** [comment]
@ailzhang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28295649).

**Pull request closed without merging**
