### PR TITLE
Delete unnecessary manual dispatch table for empty.SymInt

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #83628
* __->__ #83592

The fastpath here handled the situation when Python unconditionally
dispatched to SymInt overloads.  Now that Python doesn't do that, it
is less important for this to be fastpath-ed.  (The only reason you
might still want to fastpath is to optimize calls to this function
from composite kernels which are written only once with SymInt, but
I think it's not worth it for this case.)

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by bdhirsh** [comment]
> The fastpath here handled the situation when Python unconditionally
dispatched to SymInt overloads. Now that Python doesn't do that, it
is less important for this to be fastpath-ed.

What I'm wondering is whether you think that this is the long-term state that we want: committing to making sure that SymInt overloads are *never* hit, when you're not actually using SymInts.

Since for example today, even though PythonArgParser is smart enough to make that happen when you call from python, I don't think we've fully committed to making sure that we never have int overloads that call into symint overloads (maybe we should?). The only example I know if is Horace's recent PR: `aten::trapezoid()` will call into `empty.SymInt`: https://github.com/pytorch/pytorch/blob/dcda907693e9e7661c099c3b9ed25fadaed273f8/aten/src/ATen/native/Integration.cpp#L40


Can we actually commit to doing that, without having two implementations of every decomp floating around?

**Review by albanD — APPROVED** [review]
Nice!

**Comment by ezyang** [comment]
@bdhirsh Yeah, I think you're right, I can't guarantee we won't call into symint from non-symint.

That being said, I still think that manually writing all of the direct dispatches is the wrong call. For one, although we can't guarantee the call doesn't happen, it happens rarely (only when you hit a composite kernel). Second, it is not *that* expensive to do the redispatch, esp if you're not doing it over and over in a loop, and definitely not if you have PT2. Third, if the perf really matters, we should generate the forwarding stubs automatically. So I think this change is still worth it on balance.

**Review by bdhirsh — APPROVED** [review]
sgtm!

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
