### PR TITLE
[SPMD] Disable all SPMD tests

### PR DESCRIPTION
**Pull request by fegin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #104784

SPMD is not actively developed and is out-of-sync with the PyTorch compiler code.  Disable the tests for now.

Differential Revision: [D47296840](https://our.internmc.facebook.com/intern/diff/D47296840/)

### CODE REVIEW

**Review by fduwjj — APPROVED** [review]
LGTM

**Comment by janeyx99** [comment]
Is there anything stopping us from just removing the whole spmd folder? / Is that a next step?

**Comment by fegin** [comment]
> Is there anything stopping us from just removing the whole spmd folder? / Is that a next step?

Some people are still looking into the code (not actually using though). So I prefer to temporarily disable them atm.

**Comment by janeyx99** [comment]
Thanks for getting the functional change in! I have some thoughts on next steps. If we want to use this code as a reference, we should document that the code is no longer tested and is there as a reference only. I'd still prefer removing the dead code for cleanliness and pointing people to the PR if they're curious what the _spmd folder contained. Otherwise, people may have the wrong expectation that the code will still work even though the codebase will move forward and break the invariants.

**Pull request closed without merging**
