### PR TITLE
Fix placeholder tensor is empty for relu in mps

### LINKED ISSUE #118845: Placeholder tensor is empty!
### 🐛 Describe the bug

Relu activation is not working with empty tensor on Apple M1 GPU.
```python
import torch.nn as nn

device = torch.device("mps")

class SingleLabelNNDecoder(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):

        super().__init__()
        self.input_size = input_size
        self.hidden = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.output = nn.Linear(hidden_size, output_size)
        self.softmax = nn.LogSoftmax(dim = 2)
        # self.softmax = nn.LogSoftmax(dim=2) # dim=2 performance worse than dim=0

    def forward(self, x):
        x = self.hidden(x)
        x = self.relu(x)
        x = self.output(x)
        x = self.softmax(x)

        return x
```

---------------------------------------------------------------------------
```
Traceback (most recent call last):
  File "/Users/yunchengyuan/Documents/ProgrammingProject/master-thesis/NNDecoder_Training.py", line 312, in <module>
    main()
  File "/Users/yunchengyuan/Documents/ProgrammingProject/master-thesis/NNDecoder_Training.py", line 301, in main
    SLNN_training(SLNN_snr, nr_codeword, epochs, learning_rate, batch_size, SLNN_hidden_size[i], SLNN_model_path, SLNN_patience, delta, device)
  File "/Users/yunchengyuan/Documents/ProgrammingProject/master-thesis/NNDecoder_Training.py", line 55, in SLNN_training
    outputs = model(inputs).squeeze(1)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/thesis/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/thesis/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/yunchengyuan/Documents/ProgrammingProject/master-thesis/Decoder/NNDecoder.py", line 17, in forward
    x = self.relu(x)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/thesis/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/thesis/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/thesis/lib/python3.9/site-packages/torch/nn/modules/activation.py", line 101, in forward
    return F.relu(input, inplace=self.inplace)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/thesis/lib/python3.9/site-packages/torch/nn/functional.py", line 1471, in relu
    result = torch.relu(input)
RuntimeError: [srcBuf length] > 0 INTERNAL ASSERT FAILED at "/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1699448801785/work/aten/src/ATen/native/mps/OperationUtils.mm":327, please report a bug to PyTorch. Placeholder tensor is empty!
```

### Versions

PyTorch version: 2.1.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.3 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.28.1
Libc version: N/A

Python version: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:53:08)  [Clang 15.0.7 ] (64-bit runtime)
Python platform: macOS-14.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] snntorch==0.6.4
[pip3] torch==2.1.1
[pip3] torchaudio==2.1.1
[pip3] torchvision==0.16.1
[conda] numpy                     1.26.0           py39hc348b60_0    conda-forge
[conda] pytorch                   2.1.1                   py3.9_0    pytorch
[conda] snntorch                  0.6.4              pyhd8ed1ab_0    conda-forge
[conda] torchaudio                2.1.1                  py39_cpu    pytorch
[conda] torchvision               0.16.1                 py39_cpu    pytorch

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

### PR DESCRIPTION
**Pull request by lancerts**
Fixes #118845

### CODE REVIEW

**Review by malfet — APPROVED** [review]
Thank you for the fix, do you mind adding a test for it?

**Comment by lancerts** [comment]
> Thank you for the fix, do you mind adding a test for it?

@malfet added a small test with empty tensor in test_mps.

**Comment by qqaatw** [comment]
Returning self when `self.numel() == 0` in out-of-place `relu` is not the right fix. Please see: #133182.

I don't know why the CI passed, the added test fails on my side.

**Pull request closed without merging**
