### PR TITLE
Port `addcdiv` to structured kernels.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#62319 Port `addcdiv` to structured kernels.**
* #62318 Port `addcmul` kernels to structured kernels.

Tracking issue: #55070

Differential Revision: [D29961996](https://our.internmc.facebook.com/intern/diff/D29961996)

### CODE REVIEW

**Review by bdhirsh — APPROVED** [review]
You'll also have to add a skipMeta() in the foreach tests to appease CI

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29961996).

**Comment by bdhirsh** [comment]
@bdhirsh has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D29961996).

**Comment by ysiraichi** [comment]
The CI failure does not seem to be related to this PR (not sure about Facebook internal tests, though).

**Pull request closed without merging**
