### PR TITLE
[FSDP] ufmt `flat_param.py`, `flatten_params_wrapper.py`

### PR DESCRIPTION
**Pull request by awgu**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #83664
* #83663

I think we can move FSDP code to start using ufmt (https://ufmt.omnilib.dev/en/stable/) to unify formatting across developers. ufmt is the recommended formatter for PyTorch's Python code. If we have consensus, I can ufmt all of the FSDP code in follow-ups.

### CODE REVIEW

**Review by rohan-varma — APPROVED** [review]
How will we maintain the ufmt formatting? Will developers be expected to format the code before commits, or can this be automated?

`lintrunner` is typically the PT wide tool for formatting, if we use that, will it auto lint to this for us?

**Comment by awgu** [comment]
> How will we maintain the ufmt formatting? Will developers be expected to format the code before commits, or can this be automated?
> 
> `lintrunner` is typically the PT wide tool for formatting, if we use that, will it auto lint to this for us?

I agree that having to manually remember to ufmt every time may be unsustainable. Let us see if we can get a commit hook or something along those lines. We can investigate this more deeply when we have more bandwidth and also ufmt the rest of the FSDP code.

**Pull request closed without merging**
