### PR TITLE
Updated gen's file comparison to compare without looking at line endings

### PR DESCRIPTION
**Pull request by davidbrownellWork**

### CODE REVIEW

**Comment by ezyang** [comment]
I'm not sure how I feel about this. It seems like a lot more complicated code for not much benefit.

To add insult to injury, as written this patch is not 100% correct, because it will incorrectly conclude trailing whitespace change is not substantive, as far as diffing is concerned.

**Comment by ezyang** [comment]
cc @gchanan

**Comment by davidbrownellMS** [comment]
@ezyang I was motivated to write this as a quick and dirty work around because without the change (or something similar), builds fail based on local git settings (which is an unexpected dependency). I found this by digging into why builds failed locally but passed on our CI server.

**Comment by fmassa** [comment]
@gchanan what's your take on this?

**Comment by gchanan** [comment]
I'm okay with this but as @ezyang points out the implementation isn't correct.

I think if you open the files with 'U' you'll get universal encodings so you don't have to `rstrip`.

**Pull request closed without merging**
