### PR TITLE
[ONNX] Fix bug using std::copy_if

### PR DESCRIPTION
**Pull request by BowenBao**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #80999

`std::copy_if` requires pre-allocated destination. Hence `scopes` needs to either be pre allocated, or use `std::inserter` for copy. Ref: https://en.cppreference.com/w/cpp/algorithm/copy

### CODE REVIEW

**Comment by justinchuby** [comment]
Curious what the bug was? (Helpful to include in the PR description)

**Review by titaiwangms — APPROVED** [review]

**Comment by BowenBao** [comment]
cc @garymm for approval

**Review by garymm — APPROVED** [review]
@pytorchbot merge

**Pull request closed without merging**
