### PR TITLE
empty_strided: Factor out generic implementation

### PR DESCRIPTION
**Pull request by peterbell10**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #70618
* #70617
* #70616
* #70615
* __->__ #70614
* #70613
* #70612

This creates an `empty_strided_generic` function which, similar to
`empty_generic`, is a device-independent tensor constructor. This also
adds `at::detail::empty_strided_cpu` to complement
`at::detail::empty_cpu`.

Differential Revision: [D33623679](https://our.internmc.facebook.com/intern/diff/D33623679)

### CODE REVIEW

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33623679).

**Comment by ngimel** [comment]
Can you please check that it doesn't regress `at::empty_strided` and `at::native::empty_strided_cpu` perf? (instruction counts are probably the way to go, timing will be too noisy)

**Comment by peterbell10** [comment]
Here are the total instruction counts collected with `Timer.collect_callgrind` for `at::empty_strided({10, 10, 10}, {1, 100, 10})` and `at::native::empty_strided_cpu({10, 10, 10}, {1, 100, 10})`:

| Callgrind counts                | Master | This PR |
|---------------------------------|-------:|--------:|
| `at::native::empty_strided_cpu` |  90208 |   82498 |
| `at::empty_strided`             | 100761 |   98691 |

So actually a small improvement.

**Comment by ngimel** [comment]
Awesome!

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
@ngimel has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33623679).

**Pull request closed without merging**
