### PR TITLE
[JIT] Initialize CUDA context before launching fused kernel

### LINKED ISSUE #65073: Invalid cuda context when running nvfuser with LTC
Error msg:
```
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                          
  File "bias_gelu.py", line 54, in <module>                                                                                                                                                                                                                                                                                                                                                 
    ltm.mark_step()                                                                                                                                                                                                                                                                                                                                                                         
  File "/opt/pytorch/pytorch/lazy_tensor_core/lazy_tensor_core/core/lazy_model.py", line 727, in mark_step                                                                                                                                                                                                                                                                                  
    lazy_tensor_core._LAZYC._ltc_step_marker(                                                                                                                                                                                                                                                                                                                                               
RuntimeError: The following operation failed in the TorchScript interpreter.                                                                                                                                                                                                                                                                                                                
Traceback of TorchScript (most recent call last):                                                                                                                                                                                                                                                                                                                                           
RuntimeError: CUDA driver error: invalid device context
```

Test code:
```
import torch
from torch.nn import Module
import torch.nn.functional as F
import lazy_tensor_core.core.lazy_model as ltm

import lazy_tensor_core
lazy_tensor_core._LAZYC._ltc_init_ts_backend()

# Enable NVFuser
torch._C._jit_set_nvfuser_enabled(True)
torch._C._jit_set_texpr_fuser_enabled(False)
torch._C._jit_set_profiling_executor(True)
torch._C._jit_set_profiling_mode(True)
torch._C._jit_override_can_fuse_on_cpu(False)
torch._C._jit_override_can_fuse_on_gpu(False)
torch._C._jit_set_bailout_depth(20)

class FusionConfig :
    def __init__(self) :
        self.hidden_size = 4096 
        self.num_attention_heads = 16
        self.hidden_dropout_prob = 0.1
        self.attention_probs_dropout_prob = 0.1
        self.num_layers = 10

class Fusion(Module):
    def __init__(self, config):
        super(Fusion, self).__init__()
        self.bias = torch.nn.Parameter(torch.zeros(config.hidden_size))

    def forward(self, inputs):
        out1 = inputs + self.bias
        out2 = F.relu(out1)
        return out2

if __name__ == "__main__" :
    device = 'lazy'
    inputs = torch.randn(8, 512, 4096, device=device, dtype=torch.float, requires_grad=True)
    grads = torch.randn(8, 512, 4096, device=device, dtype=torch.float, requires_grad=False)

    model = Fusion(FusionConfig())
    model.to(device=device)

    #jit_model = torch.jit.script(model)
    jit_model = model

    for idx in range(10) :
        out = jit_model.forward(inputs)
        out.backward(grads)
        ltm.mark_step()
```

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #65064

Summary: The problem appears when nvfuser is triggered from LazyTensor.
Because LT maintains its own thread pool, the thread used for the first-time
compilation does CUDA context initialization properly, but later
cached execution may use a different thread which does not have
a proper CUDA context.

Differential Revision: [D31269691](https://our.internmc.facebook.com/intern/diff/D31269691)

### CODE REVIEW

**Review by jjsjann123 — APPROVED** [review]
LGTM thanks for the fix.

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31269691).

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31269691).

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31269691).

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31269691).

**Pull request closed without merging**
