### PR TITLE
Upgrade submodule pybind to 2.12.0

### LINKED ISSUE #122056: Error "module compiled against ABI version" when using a device on MacBook Pro M2 with MacOS Sonoma 14.4
### 🐛 Describe the bug

- I created a brand new virtual environment and Python script containing the following code.
- I installed the beta / nightly version of Pytorch, using the [directions on Apple's website for MPS (M2) support](https://developer.apple.com/metal/pytorch/).

```
pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu
```

```python
import torch
mps = torch.device("mps")
```

When I run the code, I get this error:

```

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0b1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled against NumPy 2.0.

If you are a user of the module, the easiest solution will be to
either downgrade NumPy or update the failing module (if available).

Traceback (most recent call last):  File "/Users/trevor.sullivan/git/pytorch-audio-classifier/main.py", line 7, in <module>
    mps = torch.device("cpu")
/Users/trevor.sullivan/git/pytorch-audio-classifier/main.py:7: DeprecationWarning: numpy.core._multiarray_umath is deprecated and has been renamed to numpy._core._multiarray_umath. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core._multiarray_umath._ARRAY_API.
  mps = torch.device("cpu")
/Users/trevor.sullivan/git/pytorch-audio-classifier/main.py:7: UserWarning: Failed to initialize NumPy: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000 (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  mps = torch.device("cpu")
```

How can I go about resolving this?

### Versions

```
PyTorch version: 2.4.0.dev20240317
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] (64-bit runtime)
Python platform: macOS-14.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] numpy==2.0.0b1
[pip3] torch==2.4.0.dev20240317
[pip3] torchaudio==2.2.0.dev20240317
[pip3] torchvision==0.18.0.dev20240317
[conda] Could not collect
```

cc @seemethere @malfet @osalpekar @atalman @mruberry @rgommers @kulinseth @albanD @DenisVieriu97 @razarmehr

### PR DESCRIPTION
**Pull request by albanD**
To fix https://github.com/pytorch/pytorch/issues/122056

Building with NP 2.0 allows me to run locally with both NP 2.0 and 1.26.
Any other test we should run @rgommers  ?

FYI @Skylion007 @atalman

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Comment by rgommers** [comment]
> Building with NP 2.0 allows me to run locally with both NP 2.0 and 1.26. Any other test we should run @rgommers ?

The test suite is pretty comprehensive, so no need to run anything else I'd say. Also, the `pybind11` fix went through Google-internal testing, and that probably included PyTorch (and certainly a bunch of more esoteric usage of NumPy's C API than what PyTorch uses) - and that all passed.

**Comment by Skylion007** [comment]
@rgommers Can confirm internal tests covered PyTorch through Google's import suite.

**Comment by malfet** [comment]
@albanD please note, that we've already been running the full test suite against numpy-2.0 after https://github.com/pytorch/pytorch/pull/122157 so I believe PyBind update wasn't strictly speaking necessary (as PyTorch does not integrate with NumPy via pybind)

**Pull request closed without merging**
