### PR TITLE
[JIT] Warn if shape propagation by running occurs.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Review by apaszke — COMMENTED** [review]
We do this on some cheap viewing ops like reshape because shape inference rules for them are complicated and can easily get out of sync. This shouldn’t raise a warning

**Review by apaszke — CHANGES_REQUESTED** [review]
.

**Comment by ezyang** [comment]
So, the point of this patch is to help avoid hapless end users who start using the shape propagation pass thinking that it is "fast" but are accidentally running CPU convolutions on big inputs when this happens (and they wonder why the shape propagator is slow...) I hate perf cliffs like that, because you spend a lot of time trying to figure out what's going on unless you actually read the shape propagator source code.

Re your specific example, (1) reshape isn't necessarily cheap if you're dealing with big shapes (because you had to allocate the tensor in the first place) and (2) I'm fine with special casing to suppress the warning in this case.

**Comment by apaszke** [comment]
Meh, I just don't like unconditionally printing to stderr, because it usually ends up polluting all of my output that I care about. Perhaps we could guard that with an env variable (`JIT_DEBUG`), and maybe we can discuss the scope of shape prop in the next meeting? Pretty much all our current difficulty comes from the need to infer strides in the same way ops change them, but those rules are pretty complex. Maybe we should limit certain parts to shape inference only, and allow having `TensorType`s without stride info?

**Comment by yf225** [comment]
@ezyang What should be our next step for this PR?

**Comment by ezyang** [comment]
Abandoned.

**Pull request closed without merging**
