### PR TITLE
Disable AT_ASSERTM everywhere except those files that are using it

### PR DESCRIPTION
**Pull request by xuhdev**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #41876 Remove all AT_ASSERTM under ATen CPU kernels.
* **#41875 Disable AT_ASSERTM everywhere except those files that are using it**

Since there are too many AT_ASSERTM, this will give us some leeway to
gradually remove all AT_ASSERTM.

Also move ASSERTM out of the header guard to make sure that the macro
OBSOLETE_AT_ASSERTM will always take effects.

### CODE REVIEW

**Comment by ezyang** [comment]
It is almost certainly not right to define the `OBSOLETE_ASSERTM` inside headers. Also, if this is going to be a new macro, it should get a TORCH prefix

**Review by ezyang — CHANGES_REQUESTED** [review]
remove the defines from headers

**Comment by xuhdev** [comment]
If the `define`s are removed from the headers, how do we add exemption for those headers that have used the obsolete macro?

**Comment by ezyang** [comment]
If it is not too many, it might be better to just port them immediately before landing this.

**Comment by xuhdev** [comment]
@ezyang There are 95 occurrences.

I can spend one afternoon to hunt down all these occurrences, but there are some files that I'm not quite familiar with and they may require some back and forth in deciding whether to use `TORCH_INTERNAL_ASSERT` or `TORCH_CHECK`. Meanwhile, a lot of conflict can occur in other places. I'm not sure how we should proceed.

**Comment by ezyang** [comment]
Another possibility is to refactor the code so that the macro usage no longer occurs in headers; commonly error checking in headers indicates an antipattern of some sort. I don't know if this is better or worse than motoring through the sites.

If you can post all the sites here, I can give you a hand in looking over them too?

**Comment by xuhdev** [comment]
@ezyang How about this: I'll just go ahead and make PRs to remove these occurrences for 1 round. Then, in the final cleanup round, I'll remove the macro definition. Does this sound good to you?

**Comment by ezyang** [comment]
works for me

**Pull request closed without merging**
