### PR TITLE
[Intel GPU] Support getStreamFromExternel for XPU.

### PR DESCRIPTION
**Pull request by etaf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #140686
* #140664
* #140269
* __->__ #140268

In AOT inductor scenario, the GPU Stream can be created outside of the pool of `XPUStream`, and we need to create a `XPUStream` which refers to this stream for the the common logic of AOTI, for example a stream guard is a guard for `XPUStream`.  So we add the getStreamFromExternel following the design of CUDAStream.

### CODE REVIEW

**Comment by EikanWang** [comment]
@etaf , pls. provide informative description to elaborate on why you need to do such changes.

**Comment by etaf** [comment]
> @etaf , pls. provide informative description to elaborate on why you need to do such changes.

resolved.

**Review by desertfire — APPROVED** [review]

**Review by guangyey — COMMENTED** [review]
I am preparing an PR https://github.com/pytorch/pytorch/pull/141114 to support external XPUStream. And some details are still in discussing. Could you close this PR?

**Comment by etaf** [comment]
> I am preparing an PR #141114 to support external XPUStream. And some details are still in discussing. Could you close this PR?

May I know what's the problem with my implementation?

**Comment by guangyey** [comment]
> May I know what's the problem with my implementation?
For your implementation: two different `sycl::queue*` will construct two `XPUStream` that are not equal. But in fact, if two different `sycl::queue*` point to the same underlying `sycl::queue`, these two XPUStream should be equivalent. In addition, it is difficult for us to ensure that the pointer provided by the user remains valid, and it is also challenging for the user to do so. If the `sycl::queue` goes out of scope, its dereference will be invalid. The corresponding pointer will be dangling.

**Comment by etaf** [comment]
> > May I know what's the problem with my implementation?
> 
> For your implementation: two different `sycl::queue*` will construct two `XPUStream` that are not equal. But in fact, if two different `sycl::queue*` point to the same underlying `sycl::queue`, these two XPUStream should be equivalent. In addition, it is difficult for us to ensure that the pointer provided by the user remains valid, and it is also challenging for the user to do so. If the `sycl::queue` goes out of scope, its dereference will be invalid. The corresponding pointer will be dangling.

Hi, @guangyey my understand for 
> if two different `sycl::queue*` point to the same underlying `sycl::queue`, 

A `sycl::queue` is created with an memory address, which is the value of the `sycl::queue*`, and in my implementation, the value of the `sycl::queue*` is the stream id the the external stream. So if there are two `sycl::queue*` point to the same underlying `sycl::queue`, there value is the same, the created two `XPUStream` have the same stream id and are equal according to the compare funcition:
```
  bool operator==(const Stream& other) const noexcept {
    return this->device_ == other.device_ && this->id_ == other.id_;
  }
```

**Comment by guangyey** [comment]
> Hi, @guangyey my understand for
> 
> > if two different `sycl::queue*` point to the same underlying `sycl::queue`,
> 
> A `sycl::queue` is created with an memory address, which is the value of the `sycl::queue*`, and in my implementation, the value of the `sycl::queue*` is the stream id the the external stream. So if there are two `sycl::queue*` point to the same underlying `sycl::queue`, there value is the same, the created two `XPUStream` have the same stream id and are equal according to the compare funcition:
> 
> ```
>   bool operator==(const Stream& other) const noexcept {
>     return this->device_ == other.device_ && this->id_ == other.id_;
>   }
> ```

For example, q1 and q2 are the same sycl queue. But they has different sycl::queue* pointer.
```cpp
int main() {
    sycl::queue q1 = sycl::queue();
    sycl::queue q2 = q1;
    std::cout << &q1 << std::endl;
    std::cout << &q2 << std::endl;
}
```

**Review by jansel — APPROVED** [review]

**Review by jansel — APPROVED** [review]

**Review by EikanWang — APPROVED** [review]

**Pull request closed without merging**
