### PR TITLE
Add `tensor._base` as a tracked fake for `ShapeEnv` guards.

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #141680
* #140013
* #139555
* __->__ #139554

This PR fixes the issue where AOTAutograd would produce a guard that used a symbolic value
that came from one of the input's base.

```python
@torch.compile(backend="aot_eager", dynamic=True)
def f(a, b):
    a.add_(1)
    b.add_(1)
    return a

x = torch.ones(10)
f(x[1:], x[1:])
```

In the example above, AOTAutograd functionalizes the mutation by making use of
`as_strided_scatter` operation, which produces the guard: `s0 >= s1 + 1`, where:

- `s0`: corresponds to `x.size()[0]`
- `s1`: corresponds to `a.size()[0]`

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames

### CODE REVIEW

**Comment by ezyang** [comment]
I'm impressed that no tests failed. @bdhirsh can we actually do this? Do we have to feed the base tensor into AOTAutograd when something is a view now?

**Comment by ysiraichi** [comment]
Here's the error I get without this PR:

```python
Traceback (most recent call last):
  File "examples/repr.py", line 70, in inplace
    f(x[1:], x[1:])
  File "torch/_dynamo/eval_frame.py", line 550, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 1364, in __call__
    return self._torchdynamo_orig_callable(
  File "torch/_dynamo/convert_frame.py", line 1155, in __call__
    result = self._inner_convert(
  File "torch/_dynamo/convert_frame.py", line 544, in __call__
    return _compile(
  File "torch/_dynamo/convert_frame.py", line 964, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "torch/_dynamo/convert_frame.py", line 695, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 825, in _compile_inner
    check_fn = CheckFunctionManager(
  File "torch/_dynamo/guards.py", line 2300, in __init__
    guard.create(builder)
  File "torch/_guards.py", line 298, in create
    return self.create_fn(builder, self)
  File "torch/_dynamo/guards.py", line 1873, in SHAPE_ENV
    code_parts, verbose_code_parts = output_graph.shape_env.produce_guards_verbose(
  File "torch/fx/experimental/symbolic_shapes.py", line 4936, in produce_guards_verbose
    issue_guard(guard)
  File "torch/fx/experimental/symbolic_shapes.py", line 4894, in issue_guard
    guard_expr = ShapeGuardPrinter(
  File "/lib/python3.9/site-packages/sympy/printing/printer.py", line 292, in doprint
    return self._str(self._print(expr))
  File "/lib/python3.9/site-packages/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "/lib/python3.9/site-packages/sympy/printing/str.py", line 778, in _print_Relational
    return '%s %s %s' % (self.parenthesize(expr.lhs, precedence(expr)),
  File "/lib/python3.9/site-packages/sympy/printing/str.py", line 38, in parenthesize
    return self._print(item)
  File "/lib/python3.9/site-packages/sympy/printing/printer.py", line 331, in _print
    return printmethod(expr, **kwargs)
  File "torch/fx/experimental/symbolic_shapes.py", line 2092, in _print_Symbol
    assert self.symbol_to_source.get(expr), (
AssertionError: s0 (could be from ["L['x']._base.size()[0]"]) not in {s1: ["L['x'].size()[0]", "L['y'].size()[0]"], s0: []}.  If this assert is failing, it could be due to the issue described in https://github.com/pytorch/pytorch/pull/90665
```

**Comment by ezyang** [comment]
No I understand that this solves a real problem, I am just not sure AOTAutograd is ready for having both a view and a base as input haha

**Comment by bdhirsh** [comment]
Unconditionally lifting differentiable bases as inputs seems like something that would cause problems (if previously the view was the only graph input, then we used to have no aliasing but now we will have aliasing across graph inputs).

But does this PR actually lift `._base` fields as extra graph inputs? When I patch the changes in this PR locally and run the example above, the graph that I get from dynamo looks unchanged:
```
 ===== __compiled_fn_1 =====
 /home/hirsheybar/local/b/pytorch/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
    def forward(self, s1: "Sym(s1)", L_a_: "f32[s1][1]cpu", L_b_: "f32[s1][1]cpu"):
        l_a_ = L_a_
        l_b_ = L_b_

         # File: /home/hirsheybar/local/b/pytorch/tmp8.py:5 in f, code: a.add_(1)
        add_: "f32[s1][1]cpu" = l_a_.add_(1);  add_ = None

         # File: /home/hirsheybar/local/b/pytorch/tmp8.py:6 in f, code: b.add_(1)
        add__1: "f32[s1][1]cpu" = l_b_.add_(1);  l_b_ = add__1 = None
        return (l_a_,)
```

If `wrap_to_fake_tensor_and_record(value._base)` is also adding the base tensor as an extra graph input then there is probably more work to do - although I don't remember exactly what `wrap_to_fake_tensor_and_record(x)` (is it doing more beyond just exposing the base's symbols to our dynamic shape guard infra?)

**Comment by ysiraichi** [comment]
I don't think it's creating a new graph input. As far as I understand it, it's just fakefying the tensor (creating a symbolic context), and adding it to the `tracked_fakes` list. I think we might have to add this line to other points in the code that, similarly to this one, creates new graph inputs. I will leave it for the future, though.

**Review by bdhirsh — APPROVED** [review]
I think this seems ok, given that we are not actually changing the graph

**Pull request closed without merging**
