### PR TITLE
Add BFloat16 support for smooth_l1_loss on CPU

### PR DESCRIPTION
**Pull request by CaoE**
Add BFloat16 support for smooth_l1_loss on CPU.

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
Hi! Can you please clarify why we can't use https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec/vec256/vec256_bfloat16.h#L154 here?

**Comment by CaoE** [comment]
@VitalyFedyunin Hi! This is because Vectorized<BFloat16> is casted to Vectorized<float> at the beginning, which will reduce the type conversion overhead of intermediate operations.

**Comment by VitalyFedyunin** [comment]
Overall looks good, I would like to see benchmark numbers for different input sizes.

**Comment by CaoE** [comment]
Single core performance is tested on Xeon(R) Platinum 8180 @2.5 Ghz (AVX2).
```
input: 1x3x1x6: 
    Using Vecterized<BFloat16> directly:      forward: 0.185ms,  backward: 0.179ms  
    Casted to Vecterized<float> at beginning: forward: 0.183ms,  backward: 0.175ms 

input: 1x3x1x128: 
    Using Vecterized<BFloat16> directly:       forward: 0.198ms,  backward: 0.194ms   
    Casted to Vecterized<float> at beginning: forward: 0.201ms,  backward: 0.197ms    

input: 1x3x128x128: 
    Using Vecterized<BFloat16> directly:       forward: 2.118ms,  backward: 2.453ms   
    Casted to Vecterized<float> at beginning: forward: 2.004ms,  backward: 2.992ms    
```
Rounding error (the greatest difference compared with float) is tested on Intel(R) Core(TM) i7-10700K CPU (AVX512).
```
input: 1x3x1x6: 
    Using Vecterized<BFloat16> directly:        forward: 0.0029454827308654785,  backward: 0.000244140625  
    Casted to Vecterized<float> at beginning: forward: 0.0009607672691345215,  backward: 0.00010850653052330017 

input: 1x3x1x128: 
    Using Vecterized<BFloat16> directly:        forward: 0.0005249381065368652,  backward: 1.52587890625e-05   
    Casted to Vecterized<float> at beginning: forward: 0.0005249381065368652,  backward: 7.62939453125e-06    

input: 1x3x128x128: 
    Using Vecterized<BFloat16> directly:        forward: 0.002125561237335205,  backward: 1.1920928955078125e-07 
    Casted to Vecterized<float> at beginning: forward: 0.002125561237335205,  backward: 5.960464477539063e-08  
```
In the case, there is no advantage to cast Vecterized\<BFloat16\> to Vecterized\<float\> at beginning, but it will reduce rounding errors.

**Comment by CaoE** [comment]
Rebased @VitalyFedyunin

**Comment by CaoE** [comment]
Hi @VitalyFedyunin, could you please review it ? Thank you.

**Review by frank-wei — APPROVED** [review]
The bf16 is casted to float to reduce rounding error and perf looks good.

**Pull request closed without merging**
