### PR TITLE
Fixes ROCM_HOME detection in case no hipcc is found in path

### LINKED ISSUE #95633: "from torch.utils.cpp_extension import ROCM_HOME" returns empty string if hipcc not in path
### 🐛 Describe the bug

if no ROCM_HOME environment variable is set,
and hipcc is not in path,
the function should traverse to #guess3 returning hardcoded '/opt/rocm'.

instead it returns an empty string.

+ this breaks detection of ROCM in some torch depending packages

eg.:[ https://github.com/microsoft/DeepSpeed/blob/b5750b64497cacbaf469f02db9cd76d9eda495c9/op_builder/builder.py#L203](https://github.com/microsoft/DeepSpeed/blob/b5750b64497cacbaf469f02db9cd76d9eda495c9/op_builder/builder.py#L203)

+ reproduction
```python
from torch.utils.cpp_extension import ROCM_HOME
print("ROCM_HOME:'{}', type(ROCM_HOME): '{}'".format(ROCM_HOME, type(ROCM_HOME)))
```

+ actual results with no env "ROCM_HOME" not set and hipcc not in path
```
ROCM_HOME:'', type(ROCM_HOME): '<class 'str'>'
```

+ expected results
```
ROCM_HOME:'/opt/rocm', type(ROCM_HOME): '<class 'str'>'
```

+ corresponding code lines that cause the bug
    + https://github.com/pytorch/pytorch/blob/4930ae7f82cfee22b2c70778f5c2625379444332/torch/utils/cpp_extension.py#L127
```
# Guess #2
try:
    pipe_hipcc = subprocess.Popen(
        ["which hipcc | xargs readlink -f"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
    hipcc, _ = pipe_hipcc.communicate()
    # this will be either <ROCM_HOME>/hip/bin/hipcc or <ROCM_HOME>/bin/hipcc
    rocm_home = os.path.dirname(os.path.dirname(hipcc.decode(*SUBPROCESS_DECODE_ARGS).rstrip('\r\n')))
    if os.path.basename(rocm_home) == 'hip':
        rocm_home = os.path.dirname(rocm_home)
except Exception:
    # Guess #3
```

### Versions

```sh
Collecting environment information...
/usr/lib/python3.10/site-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.4.22804-

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 12.2.1 20230201
Clang version: 15.0.7
CMake version: version 3.25.2
Libc version: glibc-2.37

Python version: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] (64-bit runtime)
Python platform: Linux-6.1.12-1-MANJARO-x86_64-with-glibc2.37
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Radeon Pro W6800
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.4.22804
MIOpen runtime version: 2.19.0
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 PRO 5750G with Radeon Graphics
CPU family:                      25
Model:                           80
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        0
Frequency boost:                 enabled
CPU(s) scaling MHz:              76%
CPU max MHz:                     4672.0698
CPU min MHz:                     1400.0000
BogoMIPS:                        7588.48
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                  AMD-V
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        16 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy==1.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pylsp-mypy==0.5.7
[pip3] torch==1.13.1
[pip3] torchvision==0.14.1a0
[conda] Could not collect
```

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### PR DESCRIPTION
**Pull request by wuxxin**
if ROCM_HOME is not set as environment variable,
it tries to find hipcc in the path,
but fails with an empty string instead of an exception,
returning an empty string instead of harcoded '/opt/rocm' as third case

Fixes #95633

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo

### CODE REVIEW

**Comment by wuxxin** [comment]
the issue is still present, this should fix it, is there something to help out ?

**Comment by dllehr-amd** [comment]
I took a look through the code, and @wuxxin  is correct.  The `hipcc.decode(*SUBPROCESS_DECODE_ARGS).rstrip('\r\n')` line, generates `''` instead of `None` which doesn't trigger the `TypeError` from `os.path.dirname` 

This fix, while including an additional module, appears more elegant, as `shutil.which` will generate the `None` type if we can't find the command.

**Comment by jithunnair-amd** [comment]
Thanks for taking a look, @dllehr-amd!

@wuxxin Will you be fixing the lint issues?

**Review by jithunnair-amd — APPROVED** [review]

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
needs lint fix

**Comment by wuxxin** [comment]
i tried to to be minimal invasive while changing the code.
there are two directions to rectify the lint warnings:
.) Rewrite with more new lines and proper handling of return values
.) apply type casting to it, eg.
```python
from typing import casting, Optional
rocm_home=cast(Optional[str], os.path.dirname(os.path.dirname(
    os.path.realpath(os.path.abspath(shutil.which("hipcc"))))))
```
Which would be the preferred way to go ?

**Comment by ezyang** [comment]
ok to spend more diff lines to deal with this

**Comment by wuxxin** [comment]
ack to broader diff, i will change it at beginning of next week, as now its Friday 22:30 in my timezone.

**Comment by jeffdaily** [comment]
Current test failure does not seem related to this PR?

**Comment by wuxxin** [comment]
i don't think its related. 
- i tested the 3 cases of the function in ipython, it worked.
- the [failed test](https://github.com/pytorch/pytorch/actions/runs/5391459789/jobs/9790642085?pr=95634) prints something unrelated about:
```traceback
Traceback (most recent call last):
  File "test/run_test.py", line 1293, in <module>
    def get_selected_tests(options) -> List[ShardedTest]:
NameError: name 'ShardedTest' is not defined
```

**Comment by jeffdaily** [comment]
> i don't think its related.
> 
> * i tested the 3 cases of the function in ipython, it worked.
> * the [failed test](https://github.com/pytorch/pytorch/actions/runs/5391459789/jobs/9790642085?pr=95634) prints something unrelated about:
> 
> ```
> Traceback (most recent call last):
>   File "test/run_test.py", line 1293, in <module>
>     def get_selected_tests(options) -> List[ShardedTest]:
> NameError: name 'ShardedTest' is not defined
> ```

So are we okay to force merge then?

**Comment by wuxxin** [comment]
i am confident the code works and the lint error displayed is unrelated to the change and will go away, once the test is repaired. i have no knowledge and opinion on the merge strategy.

**Pull request closed without merging**
