### PR TITLE
Fix for transposed convolution shape functions

### PR DESCRIPTION
**Pull request by gpetters94**
This fixes an issue with #80860 when in channels and out channels are different.

### CODE REVIEW

**Comment by vivekkhandelwal1** [comment]
@Chillee can we merge this PR?

**Review by Gamrix — CHANGES_REQUESTED** [review]
Could you run the script to regenerate the file, as noted on the top of the `_shape_functions.py` file? Otherwise it looks good.

**Comment by gpetters94** [comment]
> Could you run the script to regenerate the file, as noted on the top of the `_shape_functions.py` file? Otherwise it looks good.

Strange, I did that earlier and it didn't actually write a file. I've updated it.

**Comment by gpetters94** [comment]
Okay @Gamrix it's ready to go.

**Review by Gamrix — APPROVED** [review]
Looks good!

**Pull request closed without merging**
