### PR TITLE
Fix primTorch compute_elementwise_output_strides

### PR DESCRIPTION
**Pull request by SherlockNoMad**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #88175

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Awesome, thanks!

**Comment by SherlockNoMad** [comment]
reland in https://github.com/pytorch/pytorch/pull/88525

**Pull request closed without merging**
