### PR TITLE
Skip timm_vision_transformer in Inductor torchbench smoketest

### PR DESCRIPTION
**Pull request by yanboliang**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by yanboliang** [comment]
```timm_efficientdet``` has been skipping in benchmark trainning run:
https://github.com/pytorch/pytorch/blob/db46d9dc49bbc91ed9260422d0f5a443be8083bb/benchmarks/dynamo/torchbench.py#L95-L96
Shall we skip it as well or replace it with ```timm_efficientnet```?

**Comment by desertfire** [comment]
> ```timm_efficientdet``` has been skipping in benchmark trainning run:
> 
> https://github.com/pytorch/pytorch/blob/db46d9dc49bbc91ed9260422d0f5a443be8083bb/benchmarks/dynamo/torchbench.py#L95-L96
> 
> Shall we skip it as well or replace it with ```timm_efficientnet```?

But is the CI failure a recent recession? If yes, we should bisect it.

**Comment by yanboliang** [comment]
It's not a recent regression, it was added almost two months ago. https://github.com/pytorch/pytorch/pull/95685

**Comment by yanboliang** [comment]
Actually ```timm_efficientdet``` training passed locally, I started #99787 to re-enable it, let's see what CI will say.

**Review by desertfire — APPROVED** [review]

**Comment by desertfire** [comment]
I think the problem is from the timm_vision_transformer test after timm_efficientdet. I am ok with skipping it for now as it runs ok on the dashboard.

**Pull request closed without merging**
