### PR TITLE
[quant][fx] Only do reference moduel swapping for floating point fused modules

### PR DESCRIPTION
**Pull request by jerryzh168**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #74365
* #74364
* __->__ #74231

Summary:
Add a check to make sure the weighted modules we swap is actually a float fused module,
since the reference fused module like reference version of linear - relu would have the same
fused type as the floating point linear - relu (and the linear submodule will have different types)

Test Plan:
phabricator diff for now, can add a test case after we know exactly what the problem is
Facebook:
see if this fixes the cogwheel test https://www.internalfb.com/diff/D34778506?dst_version_fbid=303538185178175&transaction_fbid=1332625957206219

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D34888290](https://our.internmc.facebook.com/intern/diff/D34888290)

### CODE REVIEW

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34888290).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34888290).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34888290).

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34888290).

**Review by andrewor14 — APPROVED** [review]

**Comment by jerryzh168** [comment]
@jerryzh168 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34888290).

**Pull request closed without merging**
