### PR TITLE
[shard] make ShardedTensor a torch.Tensor subclass

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #78027

This is the reland of PR https://github.com/pytorch/pytorch/pull/74695, which was reverted due to some internal failures.

It also removes the ShardedTensorInterface change, we will delay that
change later if we found there's a need to do that.

Differential Revision: [D36569064](https://our.internmc.facebook.com/intern/diff/D36569064)

### CODE REVIEW

**Comment by wanchaol** [comment]
@wanchaol has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36569064).

**Comment by wanchaol** [comment]
@wanchaol has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36569064).

**Review by pritamdamania87 — APPROVED** [review]

**Review by fduwjj — APPROVED** [review]

**Comment by wanchaol** [comment]
The Ci failure is not related to this PR, landing it.

**Pull request closed without merging**
