### PR TITLE
MPS: add exponential op

### PR DESCRIPTION
**Pull request by kulinseth**
Add exponential distribution

Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by kulinseth** [comment]
This is failing with :

```
======================================================================
[225](https://github.com/pytorch/pytorch/runs/6807769871?check_suite_focus=true#step:6:226)
ERROR: test_exponential_kstest (__main__.TestNLLLoss)
[226](https://github.com/pytorch/pytorch/runs/6807769871?check_suite_focus=true#step:6:227)
----------------------------------------------------------------------
[227](https://github.com/pytorch/pytorch/runs/6807769871?check_suite_focus=true#step:6:228)
Traceback (most recent call last):
[228](https://github.com/pytorch/pytorch/runs/6807769871?check_suite_focus=true#step:6:229)
  File "test_mps.py", line 3961, in test_exponential_kstest
[229](https://github.com/pytorch/pytorch/runs/6807769871?check_suite_focus=true#step:6:230)
    from scipy import stats
[230](https://github.com/pytorch/pytorch/runs/6807769871?check_suite_focus=true#step:6:231)
ModuleNotFoundError: No module named 'scipy'
```

Trying to find an alternative package.

**Review by razarmehr — APPROVED** [review]
Looks good.

**Review by albanD — APPROVED** [review]
SGTM

**Comment by albanD** [comment]
@kulinseth you weren't able to merge as this PR touches native_functions on top of mps files

**Pull request closed without merging**
