### PR TITLE
Use a Python wrapper for C++ tests

### PR DESCRIPTION
**Pull request by driazati**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#65514**

This adds a Python-based wrapper for running C++ tests intended to be run in CI as part of #64067. Eventually this should replace all manual invocations of running a C++ test in CI. For local development running the binaries manually is still the best UX since you have full control of gtest flags and can avoid Python's startup time. 

For simple tests that can just be run out-of-the-box, add them to the [allowlist](https://github.com/pytorch/pytorch/pull/65514/files#diff-c9f1a162beb062b5905b0b8ae2a7d39ba453b1a821b62094687dbb8ce67763dbR39). This PR has an example of a more complicated invocation for `test_jit` as well which can be implemented in Python with some custom logic.

Differential Revision: [D31296508](https://our.internmc.facebook.com/intern/diff/D31296508)

### CODE REVIEW

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31296508).

**Review by seemethere — APPROVED** [review]

**Review by seemethere — APPROVED** [review]
Should we also update the bat files for windows as well?

**Review by malfet — APPROVED** [review]

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31296508).

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31296508).

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31296508).

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31296508).

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31296508).

**Comment by driazati** [comment]
@driazati has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31296508).

**Pull request closed without merging**
