### PR TITLE
OIDC for update_pytorch_labels

### PR DESCRIPTION
**Pull request by clee2000**
Companion: https://github.com/pytorch-labs/pytorch-gha-infra/pull/339

### CODE REVIEW

**Review by huydhn — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Thank you! Any way we can test it before landing?

**Comment by clee2000** [comment]
> Thank you! Any way we can test it before landing?

I put a branch restriction in the role so not unless I change the role

**Comment by clee2000** [comment]
@pytorch merge -f "lint succeeded, testing in prod oops"

**Comment by clee2000** [comment]
Recent run https://github.com/pytorch/pytorch/actions/runs/7589218381/job/20673402560 was successful

**Pull request closed without merging**
