### PR TITLE
[CI] Catch more exception types when running eager in PT2 tests

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #117120

Summary: https://github.com/pytorch/pytorch/actions/runs/7467073391/job/20320251143#step:16:1332 shows a case where model loading fails with KeyError but the error is not logged in the report csv file, which can cause an eager model failure silently ignored in the PT2 integration test.

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

### CODE REVIEW

**Comment by desertfire** [comment]
This PR by itself should hit an error in `phi_1_5`, but after TorchBench https://github.com/pytorch/pytorch/pull/117073, the error should go away, since `phi_1_5` goes away in the new TorchBench version.

**Review by huydhn — APPROVED** [review]
LGTM!  Let me update and land https://github.com/pytorch/pytorch/pull/117073 first to unblock this change.

**Pull request closed without merging**
