### PR TITLE
fix lint

### PR DESCRIPTION
**Pull request by PaliC**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105675

Forward fix of the lint issues introduced by https://github.com/pytorch/pytorch/pull/104242
We are forward fixing as this PR contains Meta internal changes that would be tricky to revert smoothly.

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]

**Comment by seemethere** [comment]
Can we link the PR where the lint failures started?

**Review by albanD — APPROVED** [review]
Thanks!

**Review by atalman — APPROVED** [review]

**Pull request closed without merging**
