### PR TITLE
[BE] Migrate pull.yml to use S3 pytorch-ci-artifacts bucket for linux-jammy-py3_8-gcc11 and docs builds/tests

### PR DESCRIPTION
**Pull request by jeanschmidt**
Switch to use LF S3 bucket for pull on linux-jammy-py3_9-gcc and docs jobs. This is required to migrate to ARC and move to use LF resources.

Depends on https://github.com/pytorch/pytorch/pull/121907
Follow up issue https://github.com/pytorch/pytorch/issues/121919

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM, though do you know the perf implications? Also, would it still render correctly on HUD?

**Comment by jeanschmidt** [comment]
Perf implications: S3 operations are all internal to AWS when called from any AWS account as long as they are from the same region. So there are none.

I believe they would render correctly on hud. As the implied changes only impact buckets for caching. Tests results should still be uploaded to hud s3 bucket.

**Comment by jeanschmidt** [comment]
During a try merge, a issue with token session duration was identified.

This needs to be fixed on another repository, so, will do that and then merge it back.

**Pull request closed without merging**
