### PR TITLE
Compile BatchLinearAlgebra without nvcc

### PR DESCRIPTION
**Pull request by peterbell10**
These files only use cuda libraries interfaces, so don't actually need to be compiled with nvcc.

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by Lezcano** [comment]
Might very well be fine, but asking as I don't know. Is it fine to do this even though we are calling MAGMA in this file?
https://github.com/pytorch/pytorch/blob/d788b7f5deecae714774b75b11c4903d8040d49e/aten/src/ATen/native/cuda/BatchLinearAlgebra.cpp#L1279-L1304

**Comment by Lezcano** [comment]
I see that you are doing the same thing for `BatchLinearAlgebraLib.cpp` which consists almost exclusively of calls to cuSOLVE, so I guess this is fine.

**Comment by IvanYashchuk** [comment]
>Is it fine to do this even though we are calling MAGMA in this file?

Yes, it's fine to do and should be done. It's often the case that `.cpp` files are compiled faster than `.cu` ones. I think `.cu` should be used only if CUDA kernels are present in the file.

**Review by IvanYashchuk — APPROVED** [review]

**Comment by ngimel** [comment]
@peterbell10 now that this file is compiled with a cpu compiler, there are quite a few unused variable warnings-turned-errors internally 
```
Summary: 
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:148:8: error: unused variable 'A_mat_stride' [-Werror,-Wunused-variable]
  auto A_mat_stride = matrixStride(A);
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:149:8: error: unused variable 'B_mat_stride' [-Werror,-Wunused-variable]
  auto B_mat_stride = matrixStride(B);
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:332:13: error: unused variable 'batch_size' [-Werror,-Wunused-variable]
  const int batch_size = cuda_int_cast(batchCount(result), "batchCount");
            ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:438:8: error: unused variable 'self_stride' [-Werror,-Wunused-variable]
  auto self_stride = matrixStride(self);
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:439:8: error: unused variable 'U_stride' [-Werror,-Wunused-variable]
  auto U_stride = matrixStride(U);
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:440:8: error: unused variable 'S_stride' [-Werror,-Wunused-variable]
  auto S_stride = S.size(-1);
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:441:8: error: unused variable 'VT_stride' [-Werror,-Wunused-variable]
  auto VT_stride = matrixStride(VT);
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:484:17: error: unused variable 'k' [-Werror,-Wunused-variable]
  const int64_t k = std::min(m, n);
                ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:689:17: error: unused variable 'self_matrix_stride' [-Werror,-Wunused-variable]
  const int64_t self_matrix_stride = matrixStride(self_working_copy);
                ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:693:17: error: unused variable 'A_matrix_stride' [-Werror,-Wunused-variable]
  const int64_t A_matrix_stride = matrixStride(A_column_major_copy);
                ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:146:8: error: unused variable 'A_data' [-Werror,-Wunused-variable]
  auto A_data = A.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:147:8: error: unused variable 'B_data' [-Werror,-Wunused-variable]
  auto B_data = B.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:146:8: error: unused variable 'A_data' [-Werror,-Wunused-variable]
  auto A_data = A.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:147:8: error: unused variable 'B_data' [-Werror,-Wunused-variable]
  auto B_data = B.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:146:8: error: unused variable 'A_data' [-Werror,-Wunused-variable]
  auto A_data = A.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:147:8: error: unused variable 'B_data' [-Werror,-Wunused-variable]
  auto B_data = B.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:146:8: error: unused variable 'A_data' [-Werror,-Wunused-variable]
  auto A_data = A.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:147:8: error: unused variable 'B_data' [-Werror,-Wunused-variable]
  auto B_data = B.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:690:13: error: unused variable 'self_working_copy_ptr' [-Werror,-Wunused-variable]
  scalar_t* self_working_copy_ptr = self_working_copy.data_ptr<scalar_t>();
            ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebra.cpp:2675:11: error: unused variable 'k' [-Werror,-Wunused-variable]
  int64_t k = std::min(m, n);
          ^
stderr: caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:148:8: error: unused variable 'A_mat_stride' [-Werror,-Wunused-variable]
  auto A_mat_stride = matrixStride(A);
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:149:8: error: unused variable 'B_mat_stride' [-Werror,-Wunused-variable]
  auto B_mat_stride = matrixStride(B);
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:332:13: error: unused variable 'batch_size' [-Werror,-Wunused-variable]
  const int batch_size = cuda_int_cast(batchCount(result), "batchCount");
            ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:438:8: error: unused variable 'self_stride' [-Werror,-Wunused-variable]
  auto self_stride = matrixStride(self);
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:439:8: error: unused variable 'U_stride' [-Werror,-Wunused-variable]
  auto U_stride = matrixStride(U);
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:440:8: error: unused variable 'S_stride' [-Werror,-Wunused-variable]
  auto S_stride = S.size(-1);
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:441:8: error: unused variable 'VT_stride' [-Werror,-Wunused-variable]
  auto VT_stride = matrixStride(VT);
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:484:17: error: unused variable 'k' [-Werror,-Wunused-variable]
  const int64_t k = std::min(m, n);
                ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:689:17: error: unused variable 'self_matrix_stride' [-Werror,-Wunused-variable]
  const int64_t self_matrix_stride = matrixStride(self_working_copy);
                ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:693:17: error: unused variable 'A_matrix_stride' [-Werror,-Wunused-variable]
  const int64_t A_matrix_stride = matrixStride(A_column_major_copy);
                ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:146:8: error: unused variable 'A_data' [-Werror,-Wunused-variable]
  auto A_data = A.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:147:8: error: unused variable 'B_data' [-Werror,-Wunused-variable]
  auto B_data = B.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:146:8: error: unused variable 'A_data' [-Werror,-Wunused-variable]
  auto A_data = A.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:147:8: error: unused variable 'B_data' [-Werror,-Wunused-variable]
  auto B_data = B.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:146:8: error: unused variable 'A_data' [-Werror,-Wunused-variable]
  auto A_data = A.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:147:8: error: unused variable 'B_data' [-Werror,-Wunused-variable]
  auto B_data = B.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:146:8: error: unused variable 'A_data' [-Werror,-Wunused-variable]
  auto A_data = A.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:147:8: error: unused variable 'B_data' [-Werror,-Wunused-variable]
  auto B_data = B.data_ptr<scalar_t>();
       ^
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebraLib.cpp:690:13: error: unused variable 'self_working_copy_ptr' [-Werror,-Wunused-variable]
  scalar_t* self_working_copy_ptr = self_working_copy.data_ptr<scalar_t>();
```

**Comment by ngimel** [comment]
There's also a bunch of unused vars around line 680, and probably further below too (at that point the compilation was cancelled due to too many errors)

**Comment by peterbell10** [comment]
@ngimel ah, right. Should be clear now I think?

**Comment by ngimel** [comment]
Let me try importing :-) 
There's an issue to enable -Werror in OSS CI #56085, if you have suggestions what to start with, feel free to comment there or submit a PR. `-Werror -Wunused_variable` is probably ok to add to cpp files (or internal builds would be broken always)

**Comment by ngimel** [comment]
Sorry, one more
```
Summary: 
caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebra.cpp:2675:11: error: unused variable 'k' [-Werror,-Wunused-variable]
  int64_t k = std::min(m, n);
          ^
stderr: caffe2/aten/src/ATen/native/cuda/BatchLinearAlgebra.cpp:2675:11: error: unused variable 'k' [-Werror,-Wunused-variable]
  int64_t k = std::min(m, n);
```
and looks like after you remove it `n` becomes an unused variable too

**Comment by ngimel** [comment]
Looks fine now :-)

**Pull request closed without merging**
