### PR TITLE
Update HF version to commit hash (6c26faa)

### PR DESCRIPTION
**Pull request by angelayi**
Some [errors](https://ossci-raw-job-status.s3.amazonaws.com/log/15968424899) in the [torchinductor hf benchmarks](https://hud.pytorch.org/benchmark/huggingface/inductor_aot_inductor?startTime=Thu,%2010%20Aug%202023%2018:05:47%20GMT&stopTime=Thu,%2017%20Aug%202023%2018:05:47%20GMT&granularity=hour&mode=inference&dtype=bfloat16&lBranch=main&lCommit=384e0d104fd077d31efafc564129660e9b7a0f25&rBranch=main&rCommit=03414081ff7ee011e17ee10f9ddb2584811bf965) should be fixed in the most recent release (for example, this [line](https://github.com/huggingface/transformers/blame/c036c814f427415db15d37fca98540d55abea492/src/transformers/models/opt/modeling_opt.py#L688) no longer exists). Additionally, I landed a [commit (6c26faa)](https://github.com/huggingface/transformers/commit/6c26faa159b79a42d7fa46cb66e2d21523351987) to the HF transformers repro to fix one of the graph breaks. This PR results in [76% pass rate for the export + aot inductor HF benchmark!](https://hud.pytorch.org/benchmark/compilers?startTime=Thu%2C%2010%20Aug%202023%2022%3A45%3A09%20GMT&stopTime=Thu%2C%2017%20Aug%202023%2022%3A45%3A09%20GMT&granularity=hour&suite=torchbench&mode=inference&dtype=bfloat16&lBranch=angelayi/hf_version&lCommit=0accaaca2fa70ca2f78c1a587dd4b6750448dd90&rBranch=main&rCommit=03414081ff7ee011e17ee10f9ddb2584811bf965)

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @anijain2305

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by desertfire** [comment]
TestMultiProc::test_hf_bert_ddp_inductor failure looks real. I wonder how large accuracy difference it is.

**Review by desertfire — APPROVED** [review]

**Comment by desertfire** [comment]
> TestMultiProc::test_hf_bert_ddp_inductor failure looks real. I wonder how large accuracy difference it is.

@wconstab , can we mark this test as xfail and then have someone to look into the problem?

**Review by malfet — APPROVED** [review]

**Comment by wconstab** [comment]
if there is some urgency around unblocking the HF upgrade then sure, but ideally fix before land rather than xfail.

**Comment by voznesenskym** [comment]
There's a lot of new graph breaks as shown in https://github.com/pytorch/pytorch/pull/109148 :( Why do we need this bump right now?

**Comment by voznesenskym** [comment]
I am going to kick off 2 runs, with and without this PR.

**Pull request closed without merging**
