### PR TITLE
[ONNX] Add warning in ONNX export when constant folding is on in training-amenable mode

### PR DESCRIPTION
**Pull request by spandantiwari**
This PR introduces a warning when user tries to export the model to ONNX in training-amenable mode while constant folding is turned on. We want to warn against any unintentional use because constant folding may fold some parameters that may be intended to be trainable in the exported model.

### CODE REVIEW

**Comment by spandantiwari** [comment]
Updated one more call site to fix test failures.

**Comment by spandantiwari** [comment]
The build failures seem unrelated. All tests are passing.

**Comment by spandantiwari** [comment]
@houseroad - could you please take a look when you get a chance. Thanks.

**Review by houseroad — APPROVED** [review]
Looks good, thanks!

**Pull request closed without merging**
