### PR TITLE
[ONNX] Remove torch dependencies in _beartype

### LINKED ISSUE #98959: [ONNX] Circular dependency on ONNX exporter's beartype module
### 🐛 Describe the bug

```bash
(base) root@a2a0de8921a0:/opt/pytorch# git diff
diff --git a/torch/onnx/__init__.py b/torch/onnx/__init__.py
index 3b1130f3668..1a8e76e42d9 100644
--- a/torch/onnx/__init__.py
+++ b/torch/onnx/__init__.py
@@ -8,6 +8,7 @@ from torch._C._onnx import (
     TensorProtoDataType,
     TrainingMode,
 )
+from torch.onnx._internal.fx import function_dispatcher
 
 from . import (  # usort:skip. Keep the order instead of sorting lexicographically
     _deprecation,
(base) root@a2a0de8921a0:/opt/pytorch# python -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/pytorch/torch/__init__.py", line 1389, in <module>
    from torch import onnx as onnx
  File "/opt/pytorch/torch/onnx/__init__.py", line 11, in <module>
    from torch.onnx._internal.fx import function_dispatcher
  File "/opt/pytorch/torch/onnx/_internal/fx/__init__.py", line 2, in <module>
    from .serialization import save_model_with_external_data
  File "/opt/pytorch/torch/onnx/_internal/fx/serialization.py", line 9, in <module>
    from torch.onnx._internal import _beartype
  File "/opt/pytorch/torch/onnx/_internal/_beartype.py", line 11, in <module>
    from torch.onnx import _exporter_states, errors
  File "/opt/pytorch/torch/onnx/errors.py", line 9, in <module>
    from torch.onnx._internal import diagnostics
  File "/opt/pytorch/torch/onnx/_internal/diagnostics/__init__.py", line 1, in <module>
    from ._diagnostic import (
  File "/opt/pytorch/torch/onnx/_internal/diagnostics/_diagnostic.py", line 10, in <module>
    from torch.onnx._internal.diagnostics import infra
  File "/opt/pytorch/torch/onnx/_internal/diagnostics/infra/__init__.py", line 1, in <module>
    from ._infra import (
  File "/opt/pytorch/torch/onnx/_internal/diagnostics/infra/_infra.py", line 10, in <module>
    from torch.onnx._internal.diagnostics.infra import formatter, sarif
  File "/opt/pytorch/torch/onnx/_internal/diagnostics/infra/formatter.py", line 20, in <module>
    @_beartype.beartype
AttributeError: partially initialized module 'torch.onnx._internal._beartype' has no attribute 'beartype' (most likely due to a circular import)
```

### Versions

latest master branch

### PR DESCRIPTION
**Pull request by justinchuby**
Fix circular dependencies

Fixes #98959

### CODE REVIEW

**Review by BowenBao — APPROVED** [review]
🚢

**Comment by thiagocrepaldi** [comment]
can you try moving `_ONNX_FRIENDLY_DECOMPOSITION_TABLE = _create_onnx_friendly_decomposition_table()` from torch/onnx/_internal/fx/function_dispatcher.py to torch/onnx/__init__.py and see if that works with your changes?

**Review by thiagocrepaldi — APPROVED** [review]

**Comment by justinchuby** [comment]
@BowenBao `test/onnx/test_fx_to_onnx_with_onnxruntime.py::TestFxToOnnxWithOnnxRuntime_op_level_debug_True_dynamic_shapes_False::test_large_scale_exporter_with_tiny_gpt2 - AssertionError: Mixing fake modes NYI`

Was this known?

**Pull request closed without merging**
