### PR TITLE
Add a record scope around autograd::engine::evaluate_function

### PR DESCRIPTION
**Pull request by rohan-varma**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #63619

Adds a RECORD_FUNCTION with the function that is being valuate as part
of backwards execution. This has been useful in picking up some operations
in the backwards pass that otherwise would not show up, for example custom cpp
functions that use custom C++ code.

Differential Revision: [D30439492](https://our.internmc.facebook.com/intern/diff/D30439492/)

### CODE REVIEW

**Comment by albanD** [comment]
Can you do a small benchmark with instruction count Timer to see how it actually impacts runtime?

**Comment by rohan-varma** [comment]
@albanD I used the following benchmark:

```
import torch
import torch.utils.benchmark as benchmark


def time_backward(loss):
    loss.backward()


if __name__ == "__main__":
    a = torch.randn((10, 10), requires_grad=True)
    b = torch.randn((10, 10), requires_grad=True)
    loss = torch.add(a, b).sum()
    t0 = benchmark.Timer(
        stmt="time_backward(loss)",
        setup="from __main__ import time_backward",
        globals={"loss": loss},
    )

print(t0.timeit(10000))
```

and before/after seems to be pretty consistently 120-140 us on my machine, i.e. any difference in before/after seems to be within the variance between the individual runs. So it appears that there isn't a big overhead by adding record_function here.

**Comment by albanD** [comment]
That sounds ok.
To measure very small time differences, you cal use `https://pytorch.org/docs/stable/benchmark_utils.html?highlight=callgrind#torch.utils.benchmark.Timer.collect_callgrind` on the timer class. That gives you deterministic differences.

**Comment by rohan-varma** [comment]
@albanD Using `collect_callgrind`, I got the following results:

Without this diff:
```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
<torch.utils.benchmark.utils.valgrind_wrapper.timer_interface.CallgrindStats object at 0x7f9508f2e640>
torch.add(torch.randn((10,10),requires_grad=True), torch.randn((10,10), requires_grad=True)).sum().backward()
                           All          Noisy symbols removed
    Instructions:     76948941                   76795485
    Baseline:             3433                       3295
100 runs per measurement, 1 thread
Warning: PyTorch was not built with debug symbols.
         Source information may be limited. Rebuild with
         REL_WITH_DEB_INFO=1 for more detailed results.
```

With this diff:
```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
<torch.utils.benchmark.utils.valgrind_wrapper.timer_interface.CallgrindStats object at 0x7fc45530ca60>
torch.add(torch.randn((10,10),requires_grad=True), torch.randn    ((10,10), requires_grad=True)).sum().backward()
                           All          Noisy symbols removed
    Instructions:     77212452                   77057976
    Baseline:             3393                       3295
100 runs per measurement, 1 thread
Warning: PyTorch was not built with debug symbols.
         Source information may be limited. Rebuild with
         REL_WITH_DEB_INFO=1 for more detailed results.
```

So looks like it increases instructions by ~0.3%, which shouldn't be too significant?

**Comment by albanD** [comment]
I think that is ok as long as we're sure that it's all the tracking you will need.
But from our earlier discussion this is giving you all the info you need right?

**Comment by rohan-varma** [comment]
> I think that is ok as long as we're sure that it's all the tracking you will need.
> 
> But from our earlier discussion this is giving you all the info you need right?

Yep, we're able to get all the ranges which are useful with this PR. The main idea was to profile expensive backward autograd functions and this enables exactly that.

**Review by albanD — APPROVED** [review]
Ok

**Pull request closed without merging**
