### PR TITLE
Non-blocking SyncBatchNorm update

### PR DESCRIPTION
**Pull request by winggan**
As shown in #36452 , SyncBatchNorm can block host thread due the ``MemcpyDtoH`` and ``MemcpyHtoD`` when dealing with argument ``counts`` for native function ``batch_norm_gather_stats_with_counts``. 

- This fix change signiture of ``batch_norm_gather_stats_with_counts`` to
```c++
std::tuple<Tensor, Tensor> batch_norm_gather_stats_with_counts_cuda(const Tensor& self, const Tensor& mean, const Tensor& invstd, const Tensor& running_mean, const Tensor& running_var, double momentum, double epsilon, const Tensor& counts)
```
so it can directly receive "counts" in a ``CUDATensor`` rather than ``IntArrayRef`` whose data is in host memory. 

- This fix also improve implementation of ``SyncBatchNorm`` function so the construction of ``counts`` tensor will not cause additional ``MemcpyHtoD``, which will block host thread, too.

### CODE REVIEW

**Comment by gzygzy9211** [comment]
@apaszke Hello
need a quick answer. 

- Should I  add a new ``batch_norm_gather_stats_with_counts_tensor`` instead of change the signiture of the original for backward compability?

- I do not understand what is wrong with the "pytorch_bazel_test", could you please help?

**Review by jjsjann123 — APPROVED** [review]
LGTM.

I don't see too big of a problem breaking BC but I don't really know if any user would be affected by that, @ngimel probably knows better.
If we just want to make CI go away, you need to update the whitelist here: https://github.com/pytorch/pytorch/blob/13391cebe2bbc7109e50e1da517409e37e68c3bb/test/backward_compatibility/check_backward_compatibility.py#L19

**Comment by ngimel** [comment]
+ @houseroad for backwards compatibility https://github.com/pytorch/pytorch/pull/36659/files#diff-f1e4b2c15de770d978d0eb77b53a4077R2154. backwards compatibility test is legitimately broken, but batch_norm_gather_stats_with_counts_cuda should not be used in any production models, should we just black list it for the backward compatibility test?

**Review by houseroad — COMMENTED** [review]
@ngimel correct, this PR should not affect any inference model in prod.

**Comment by ngimel** [comment]
@gzygzy9211 please update the whitelist for backwards compatibility test, as @jjsjann123 suggests.

**Comment by gzygzy9211** [comment]
@ngimel the whitelist has been updated, please review.

And ``pytorch_bazel_build`` is still failing due to 
image
Don't know how to resolve..

**Comment by ngimel** [comment]
Github was down probably, not your fault.

**Comment by gzygzy9211** [comment]
Seems to be ok to merge?

**Comment by ngimel** [comment]
It has a conflict in check_backward_compatibility now, can you please fix it?

**Comment by gzygzy9211** [comment]
> It has a conflict in check_backward_compatibility now, can you please fix it?

Done. Seems to be a change that just happened. Let's merge this PR if there is not any other problem, shall we? ``master`` branch is moving forward....

**Pull request closed without merging**
