### PR TITLE
[testing] clamp: test with either min or max

### PR DESCRIPTION
**Pull request by kshitij12345**
Follow-up from https://github.com/pytorch/pytorch/pull/52194 based on comment https://github.com/pytorch/pytorch/pull/52194#issuecomment-808861162

### CODE REVIEW

**Comment by mruberry** [comment]
This is cool but I'm wondering if we should treat clamp as a unary op since @peterbell10 is working on adding support min and max tensors, see here: https://github.com/pytorch/pytorch/pull/52695.

Seems like it will still need special handling, after all.

**Comment by peterbell10** [comment]
In my PR I keep the existing `UnaryUfuncInfo` and add a new `OpInfo` for the multi-tensor variants.

**Comment by mruberry** [comment]
Sorry @kshitij12345, looks like this slipped through the cracks. With @peterbell10's answer and updates to common_method_invocations.py, are there parts of this PR we still want? If so, let's update it and get it landed quickly!

**Comment by mruberry** [comment]
Ping on this older PR, too, @kshitij12345 -- is there something here we should update and land or should we close this?

**Comment by kshitij12345** [comment]
NOTE to self : Verify if the changes are still relevant.

**Pull request closed without merging**
