### PR TITLE
Improve numeric stability for LayerNorm on CUDA

### PR DESCRIPTION
**Pull request by xiaomengy**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#40308 Improve numeric stability for LayerNorm on CUDA**
* #40307 Improve numeric stability for LayerNorm on CPU

Improve numeric stability for LayerNorm on CUDA.

This diff will slightly decrease the performance of LayerNorm but increase the numerical stability especially when the variance is small.

Example.
M = 1024, N = 32768
input =  torch.randn(M, N, dtype=torch.float, device="cuda") * 0.01 + 100.0

Previously in this case, the computed variance is
[0.      , 0.000977, 0.      , ..., 0.      , 0.      , 0.      ]

After this diff, the variance will be
[1.002436e-04, 9.923753e-05, 1.014664e-04, ..., 1.015593e-04, 1.000437e-04, 1.009089e-04]

This is is close to 1e-4 as we expected. The max relative difference compare to double result is 5.69883169e-05.

The average running time for F.layer_norm with input size [4096, 32768] on one devgpu before this PR is about 5.18ms, and after this PR is about 5.35ms. So the influence on performance should be limited.

Differential Revision: [D21993664](https://our.internmc.facebook.com/intern/diff/D21993664/)

### CODE REVIEW

**Comment by BIT-silence** [comment]
link https://github.com/pytorch/pytorch/issues/40302

**Comment by ngimel** [comment]
Can you please profile performance with sizes from this script? I'm concerned about using int64 for computation, it might slow down the kernels considerably.

**Comment by BIT-silence** [comment]
> Can you please profile performance with sizes from this script? I'm concerned about using int64 for computation, it might slow down the kernels considerably.

I tried both int32 and int64 for the index summation, I didn't see great difference between them. On a V100 machine, the input size is [4096, 65536], the average time over 1000 runs between int32 and int64 is 2.334ms vs 2.337ms.

**Comment by BIT-silence** [comment]
> Can you please profile performance with sizes from this script? I'm concerned about using int64 for computation, it might slow down the kernels considerably.

I tried to change the index summation to int32 type, but I didn't see great difference. On one V100 machine with input size [4096, 65536], the average running time of int32 and int64 is 4.375ms vs 4.384ms.

**Comment by xiaomengy** [comment]
https://github.com/pytorch/pytorch/pull/59987 should fix the issue.

**Pull request closed without merging**
