### PR TITLE
Use tensor overload for quantize_per_tensor in Quantize module

### PR DESCRIPTION
**Pull request by dreiss**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#77772**
* #77771

Summary:
quantize_per_tensor has supported tensor arguments since
a95207dad4c6b970.  Use this overload to avoid a warning about casting
tensor to float during tracing.

Test Plan:
Added unit test that no longer throws a warning.

Reviewers:

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]

**Comment by dreiss** [comment]
@BowenBao or @garymm , I think the ONNX failures here are legit.  Do you think this is a reasonable change?  Can we fix ONNX to handle this new argument format?  If there are any forward-compatibility concerns, I'm happy to hold off landing this for a while.

**Comment by garymm** [comment]
@justinchuby can you see if we can change something in the torch.onnx code to avoid these test failures?

https://github.com/pytorch/pytorch/runs/6495409678?check_suite_focus=true

**Comment by justinchuby** [comment]
Could you merge from master? With a brief test it seems the latest master does not produce the errors.

**Comment by justinchuby** [comment]
Sorry for the delay. We are hoping to take this on soon

**Pull request closed without merging**
