### PR TITLE
Upgrade triton pin

### PR DESCRIPTION
**Pull request by ezyang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105463

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

### CODE REVIEW

**Review by albanD — APPROVED** [review]
SGTM

**Comment by eellison** [comment]
Perf run looks fine

**Comment by bertmaher** [comment]
I haven't had a chance to test this inside FB yet; will hopefully get it done by end of this week (but it's a more onerous process).  Hopefully we aren't landing anything too dramatic depending on this immediately?

**Comment by ezyang** [comment]
Nope, going slow

**Pull request closed without merging**
