### PR TITLE
Add optional "squared" argument to pairwise_distance

### PR DESCRIPTION
**Pull request by johny-c**
In many cases one only needs to use squared distances and can avoid taking the square roots (e.g. in k-means, nearest neighbors). This PR adds a boolean argument "squared" to `pairwise_distance` to be used only in combination with `p` = 2 if the user only needs to compute squared distances.

### CODE REVIEW

**Comment by ezyang** [comment]
I temporarily cancelled the Travis build, that does not mean that the build failed.

**Comment by johny-c** [comment]
Ok @ezyang , is there something wrong with Travis? Seems like the build does not start now either.

**Comment by apaszke** [comment]
I don't think this falls into the scope of the core library. Euclidian distance is a trivial one linear so you can easily write it out yourself, and it's a bit awkward to have flags that only work for some input configurations. Please open issues before you spend time on writing the code so we can discuss that. Thanks for the PR!

**Comment by johny-c** [comment]
Ok, no problem, I should have opened an issue first.

**Pull request closed without merging**
