### PR TITLE
[BE]: Apply PYI autofixes to various types

### PR DESCRIPTION
**Pull request by Skylion007**
Applies some autofixes from the ruff PYI rules to improve the typing of PyTorch. I haven't enabled most of these ruff rules yet as they do not have autofixes.

cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @chenyang78 @aakhundov

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by Skylion007** [comment]
Found a bug in ruff and flagged it upstream: https://github.com/astral-sh/ruff/issues/6695

**Comment by justinchuby** [comment]
Curious why `Any` -> `object`? Just for my learning

**Comment by Skylion007** [comment]
@justinchuby https://beta.ruff.rs/docs/rules/bad-exit-annotation/

**Pull request closed without merging**
