### PR TITLE
Use `packaging.version` instead of `distutils.version`

### PR DESCRIPTION
**Pull request by asi1024**
This PR fixes to use `pkg_resources.packaging.version` instead of `distutils.version`.

distutils deprecated version classes from setuptools 59.6.0 (https://github.com/pypa/distutils/pull/75), and PyTorch raises an error: `AttributeError: module 'distutils' has no attribute 'version'` when importing `torch.utils.tensorboard`.

The comparsion rule of ``distutils.version.LooseVersion`` and ``packaging.version.Version`` a little differnt in a case of comparison of pre-release versions. `LooseVersion` just split the string up into a tuple of integer and string components, and compares with a simple tuple comparison rule.　For example, `LooseVersion('1.0.0rc1') > LooseVersion('1.0.0')` is evaluated to `True` in spite of `packaging.version.Version('1.0.0rc1') > packaging.version.Version('1.0.0')` is evaluated to `False`.

So this PR replaces `LooseVersion(v) >= "X.Y.Z"` with `packaging.version.parse(v).release >= (X, Y, Z)`.

### CODE REVIEW

**Comment by keskival** [comment]
Issue for this PR: https://github.com/pytorch/pytorch/issues/69894

**Review by malfet — APPROVED** [review]
Thank you for the PR. Can you please update PR description that compares `distuils.version.LooseVersion` vs `packaging.version.Version` parsing and comparison rules.

Also, `packaging` is not part of default Python runtime, please make sure to mention it as dependency of `setup.py` (though it will be present on any system that has pip tool installed)

**Review by seemethere — APPROVED** [review]

**Comment by asi1024** [comment]
@malfet Fixed to compared with `packaging.version.Version.release` for the behavior compatibility and updated the PR description!

**Review by seemethere — APPROVED** [review]

**Comment by cloudlakecho** [comment]
I may late in the discussion.

I am aware these lines at  "/torch/utils/tensorboard/__init__.py" file:
```
from setuptools import distutils
LooseVersion = distutils.version.LooseVersion
```
giving an error. 

It looks like `from distutils.version import LooseVersion`, work at the file file: 
```
 if not hasattr(tensorboard, '__version__') or LooseVersion(tensorboard.__version__) < LooseVersion('1.15'):
```

Is this could be another solution? 

Runtime Environment
&nbsp;&nbsp; distutils 3.6.9
&nbsp;&nbsp; protobuf 3.19.4
&nbsp;&nbsp; torch 1.10.2+cu113
&nbsp;&nbsp; torchaudio 0.10.2+cu113
&nbsp;&nbsp; torchvision 0.11.3+cu113

**Comment by adamjstewart** [comment]
We should revive this and prevent it from being closed as stale. Distutils will be removed in Python 3.12, so we want to try to be futureproof and avoid using distutils ASAP.

**Comment by asi1024** [comment]
Resolved conflicts.

**Review by atalman — APPROVED** [review]

**Comment by rgommers** [comment]
@malfet could you try to land this again?

**Pull request closed without merging**
