### PR TITLE
DataLoader: add error detection for worker_init_fn

### PR DESCRIPTION
**Pull request by ssnl**
This is an attempt to isolate unrelated changes from #19228 for easier review.

### CODE REVIEW

**Comment by ezyang** [comment]
@apaszke Do you plan to review this or should I find someone else?

**Comment by SsnL** [comment]
@ezyang I separated the `test_proper_exit` printing part to #20166 . That should be merge-able.

**Review by apaszke — APPROVED** [review]
This looks good, but here's an idea: instead of guarding every single place where an error might be raised inside the worker function, wrap it in another one and have a catch-all for any errors that might get thrown. The code used to transmit exceptions to the master process can get isolated and called from both places to avoid duplication.

**Comment by SsnL** [comment]
@apaszke Thanks for the suggestion. I've given your proposal some thought. It is a nice idea, but for implementation we seem to have to try-catch in initialization or specialize the first iteration. I don't think it is worthwhile since we only need to cover this particular worker loop pattern. If in future we need to have another similar loop, we should definitely make this more general.  :)

**Pull request closed without merging**
