### PR TITLE
[12/N] Apply clang-tidy and fix warnings in headers of torch/csrc

### PR DESCRIPTION
**Pull request by cyyever**
This PR follows #116751.

### CODE REVIEW

**Review by albanD — COMMENTED** [review]
Looks good!
Enable lint?

**Comment by cyyever** [comment]
@albanD Not ready, we still have more to fix until we can cover torch/csrc/**/*.h

**Review by albanD — DISMISSED** [review]
Ok!

**Review by albanD — APPROVED** [review]

**Pull request closed without merging**
