### PR TITLE
[ROCm] add 3.10 docker image

### PR DESCRIPTION
**Pull request by jeffdaily**
Add a ROCm 3.10 docker image for CI.  Keep the 3.9 image and remove the 3.8 image.  Plan is to keep two ROCm versions at a time.

### CODE REVIEW

**Comment by jeffdaily** [comment]
We intentionally keep current version (3.10) and one prior version (3.9).

**Comment by walterddr** [comment]
looks good. can you add description and is there a related PR on builder as well? (remember there used to be some script changes needed for each rocm version, curious if it is needed this time)

**Comment by jeffdaily** [comment]
Added description.  This is for the CI image only.  The corresponding PR to the ossci-job-dsl repo to migrate our Jenkins CI to the new image will happen some time next week after our CI hosts have had their ROCm dkms kernel upgraded over the weekend.  I will submit a PR for nightly wheels separately.

**Comment by walterddr** [comment]
cool. +1

if i remember correctly, docker rocm3.10 push will fail if changes on ossci-job-dsl repo doesn't happen. 
if that's the case, we will merge it afterwards. otherwise looks good

**Comment by jeffdaily** [comment]
CI will fail if the image has no ECR entry to be pushed to, but last time we went through this we went and had a bunch of AWS ECR repos created in anticipation of new ROCm releases.

**Review by walterddr — APPROVED** [review]

**Review by janeyx99 — APPROVED** [review]

**Pull request closed without merging**
