### PR TITLE
Support gpu triangle solve

### PR DESCRIPTION
**Pull request by fehiepsi**
While implementing Gaussian Process module in Pyro, I have to use triangular solver a lot. Currently, `trtrs` is only available on cpu (issue #3073) and for triangular solver on gpu, we have to use `torch.inverse()`. So I made a step to implement it.

I don't have much knowledge to write c/cuda code so there might be some mistakes which I didn't notice. It is helpful to me to diagnostic errors if someone can point out where is cuda test for pytorch functions (especially for `gesv`). This has just been tested for some examples by installing pytorch and comparing results of cpu and gpu versions.

Here is some information which I observed during the implementation:
+ There is no `trtrs` function in MAGMA, so I have to use [trsm](http://icl.cs.utk.edu/projectsfiles/magma/doxygen/group__magma__trsm.html) instead. Indeed, LAPACK `trtrs` is just a wrapper of BLAS `trsm` with additional checks for singularities.
+ In the docs of [magma_dtrsm](http://icl.cs.utk.edu/projectsfiles/magma/doxygen/group__magma__trsm.html#ga36b2b66d52f384db19cf256cc5e8a4c2), there is an argument `queue` which belongs to `magma_queue_t` type. When I created a queue and installed, I kept getting the error "too many arguments" at `maga_dtrsm` calls. When removed it, the installation run well. So I guess there are some changes with different versions of MAGMA.

cc @SsnL @fritzo

### CODE REVIEW

**Comment by fehiepsi** [comment]
I run test_case of `trtrs` for gpu here: https://gist.github.com/fehiepsi/f0ccc0f40091ee15b35e756c4091ac8e

**Comment by SsnL** [comment]
Cool. Can you add tests for this in `test_cuda` please?

**Comment by fehiepsi** [comment]
@SsnL I have ported cpu test to gpu.

**Review by apaszke — APPROVED** [review]

**Comment by apaszke** [comment]
Thanks @fehiepsi!

**Pull request merged**
