### PR TITLE
Cache some ValueRanges

### PR DESCRIPTION
**Pull request by isuruf**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #137438

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @amjames @rec

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
functools.cache is 3.9 which we can't use yet

**Comment by ezyang** [comment]
lmk if you need help resolving conflicts

**Comment by ezyang** [comment]
just update the csv

**Comment by laithsakka** [comment]
@isuruf 
Thanks for the compile time wins
This seems to move basic_modules_ListOfLinears_inductor by 1.3% which is less than 1.5% so it did not fail it, but we probably need to update the expected_value data for that one as well.

2024-10-12T04:47:34.1221114Z PASS: benchmark ('basic_modules_ListOfLinears_inductor', 'compile_time_instruction_count') pass, actual result 18830023930 -1.31% is within expected 19080000000 ±1.50%

**Pull request closed without merging**
