### PR TITLE
[jit] fix anynonzero op

### PR DESCRIPTION
**Pull request by wanchaol**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#29423 [jit] fix anynonzero op**

Summary:

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D18820523](https://our.internmc.facebook.com/intern/diff/D18820523)

### CODE REVIEW

**Comment by Krovatkin** [comment]
@wanchaol looks reasonable, but can we wait until this https://github.com/pytorch/pytorch/pull/29230/files goes in?
it will also test our simple and profiling executors alongside with the original one.

**Comment by Krovatkin** [comment]
@wanchaol I remember there were some issues with `-> bool` vs `-> int`, but I can't recall the details :-( which is another reason why I want https://github.com/pytorch/pytorch/pull/29230/ to go in first :-)

**Comment by wanchaol** [comment]
> @wanchaol I remember there were some issues with `-> bool` vs `-> int`, but I can't recall the details :-( which is another reason why I want #29230 to go in first :-)

sounds good, i will wait for https://github.com/pytorch/pytorch/pull/29230 merged.

**Review by Krovatkin — APPROVED** [review]
:shipit:

**Pull request closed without merging**
