### PR TITLE
Add dtypes support in opinfo for Intel Gaudi

### PR DESCRIPTION
**Pull request by ankurneog**
## Motivation
This is following up on changes introduced in https://github.com/pytorch/pytorch/pull/128584
we are adding the dtype information to be picked up while executing the UTs for Intel Gaudi/HPU

cc @frank-wei @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by ankurneog** [comment]
@albanD  : can you please help with the review, thanks

**Comment by ankurneog** [comment]
@albanD : can you please help with the review and approval. thanks

**Comment by ankurneog** [comment]
@albanD : can you please help with the review and approval. thanks

**Comment by ankurneog** [comment]
@albanD  : gentle reminder, can you please help with the review and approval. thanks

**Review by albanD — APPROVED** [review]
Sorry long todo list.
Sounds good!

**Comment by ankurneog** [comment]
@albanD  : Could you help with this, is anything missing ? I am not able to merge these changes.

**Comment by ankurneog** [comment]
@pytochbot merge

**Pull request closed without merging**
