### PR TITLE
Switch to using Python nested int

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #141842
* #141840
* #141841
* #141839
* __->__ #141166

Doesn't seem to noticeably slow down eager - TestNestedTensorSubclass tests with and without the PR finished in similar amounts of time (around 57s, 58s)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
So you gonna delete the C++ ones?

**Comment by soulitzer** [comment]
> So you gonna delete the C++ ones?

To unify the backward formulas between cpp nested tensor/python nested tensor/eager I still want to be able to return a .size(), and for that I need a purely cpp nested int (unless we require cpp nested tensor users to be running Python).

**Pull request closed without merging**
