### PR TITLE
Assimilate activation images to PyTorch brand color (#51008)

### PR DESCRIPTION
**Pull request by ghost**
Please refer to #51008 .

### CODE REVIEW

**Comment by heitorschueroff** [comment]
@mruberry Who would be the right person to review this?

**Comment by mruberry** [comment]
@brianjo and @jlin27 are the right people to determine if (1) we should make this change (2) this is the correct implementation of the change.

**Comment by brianjo** [comment]
@simaki Could you add a couple of screenshots of how this looks before and after the change? Thanks!

**Comment by simaki** [comment]
@brianjo Here are screenshots. Thank you so much for reviewing!

before
after

**Comment by simaki** [comment]
@mruberry @brianjo @mattip
This is a kind reminder. I appreciate it if you could review this request. Thank you!

**Comment by brianjo** [comment]
Thanks for the suggestion @simak. I'm going to close this one as I don't think it's worth setting up custom colors on the graphics in the documents.

**Pull request closed without merging**
