### PR TITLE
[Quant][BE] Fix PT2E test paths broken after refactor

### PR DESCRIPTION
**Pull request by andrewor14**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #99400

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]

**Comment by jerryzh168** [comment]
Hi @andrewor14, actually let me fix it in my PR, I think it probably takes too long to merge it in github and then sync to phabricator

**Comment by jerryzh168** [comment]
oh actually I saw it is already landed: https://github.com/pytorch/pytorch/pull/99402/files

**Comment by andrewor14** [comment]
Ok, let me close it

**Pull request closed without merging**
