### PR TITLE
[ROCm] backward compatible type enums

### PR DESCRIPTION
**Pull request by jeffdaily**
Fixes builds of pytorch using unreleased ROCm packages that are missing type enums introduced in ROCm 6.0 release.

cc @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

### CODE REVIEW

**Review by houseroad — COMMENTED** [review]
Do we have the machines in CI to trigger both path separately?

**Comment by anupambhatnagar** [comment]
> Do we have the machines in CI to trigger both path separately?

I am not sure about it. I tested it manually by cloning the source repo and building from source. It works if the correct LD_LIBRARY_PATH is set.

**Comment by anupambhatnagar** [comment]
@jeffdaily could you please test this PR on your end by building from source on MI300? Thanks!

**Review by xw285cornell — APPROVED** [review]
Looks the broken rocm tests are not related? Verified can unblock build. Let's land this?

**Review by anupambhatnagar — APPROVED** [review]

**Comment by xw285cornell** [comment]
> Do we have the machines in CI to trigger both path separately?

I don't think so. The introduction of this FP8 data type in hip runtime is quite new and not in any of the hip release branch: https://github.com/ROCm/HIP/blame/e445a95fe9fb61f745535b008f9e0684e9f51cd6/include/hip/library_types.h#L62. We'll need this new hip change to get deployed before removing this.

**Pull request closed without merging**
