### PR TITLE
Update CMakeLists.txt since MacOS linker doesn't support whole-archive

### PR DESCRIPTION
**Pull request by TachikakaMin**
--whole-archive is a linker option(notice, that flag is passed as -Wl,--whole-archive), and -force_load is indeed available on MacOS platform (below is the quote from man ld):

 -force_load path_to_archive
        Loads all members of the specified static archive library.  Note:
        -all_load forces all members of all archives to be loaded.  This
        option allows you to target a specific archive.

Quote from malfet

### CODE REVIEW

**Comment by TachikakaMin** [comment]
@larryliu0820  could you check this PR? Thanks.

**Review by larryliu0820 — COMMENTED** [review]
So line 59 should handle Mac? I tested it on my Mac Pro. If it doesn’t work, maybe merge your change with line 59 to avoid duplicates?

**Comment by TachikakaMin** [comment]
> So line 59 should handle Mac? I tested it on my Mac Pro. If it doesn’t work, maybe merge your change with line 59 to avoid duplicates?

Because AppleClang and Clang are different compilers. In macOS, they can exist together.

**Review by larryliu0820 — APPROVED** [review]
Looks good, thanks!

**Comment by TachikakaMin** [comment]
@larryliu0820   Could we merge it? Thanks!

**Comment by larryliu0820** [comment]
Can you fix the failed job? Seems related.

**Comment by TachikakaMin** [comment]
> Can you fix the failed job? Seems related.

No idea about this failure. It caused by 

`subprocess.CalledProcessError: Command '['/Users/runner/work/_temp/conda_environment_3859154511/bin/cmake', '--version']' died with <Signals.SIGABRT: 6>.`

Maybe we should rerun it?

**Pull request closed without merging**
