### PR TITLE
[Inductor][FX]support nn.Linear nn.ConvTransposeNd for efficient_conv_bn_eval

### PR DESCRIPTION
**Pull request by youkaichao**
Using the `functional_call` API, we can deal with nn.Linear and nn.ConvTransposeNd, just like normal conv.

Thanks for @albanD pointing out the API in https://github.com/pytorch/pytorch/issues/109596 .

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @jansel

### CODE REVIEW

**Review by jansel — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@pragupta Can you please take a look at this PR? It's failing on ROCm CI. Please suggest a workaround if the root-causing or fix might take longer.

**Comment by jithunnair-amd** [comment]
Looks like this test (and other similar tests) is disabled via issue https://github.com/pytorch/pytorch/issues/109864, retriggering CI to pick up the skips 

@pytorchbot rebase

**Pull request closed without merging**
