### PR TITLE
Update unary_ufuncs groupings to include primtorch types.

### LINKED ISSUE #107335: Update generic operator tests to run for primtorch ops
## Issue description

Currently most of the operator groupings in [common_method_invocations](https://github.com/pytorch/pytorch/blob/8507b22fea9ef819452655aa6dd1c42752a4e74a/torch/testing/_internal/common_methods_invocations.py#L20638-L20651) don't include the reference operators and this could lead to unintended mismatch in operator functionality between eager ops and primtorch ops slipping through. Some cases have already been seen of this while creating https://github.com/pytorch/pytorch/pull/104489.  This is issue is being created in order to track and breakdown the changes to multiple pull requests for more manageable pieces for review. The `sparse_*` groupings cannot be currently updated as it seems that sparse tensor support for primtorch is is not yet complete.

https://github.com/pytorch/pytorch/blob/8507b22fea9ef819452655aa6dd1c42752a4e74a/torch/testing/_internal/common_methods_invocations.py#L20638-L20651
- [ ] Update `unary_ufuncs` groupings
- [ ] Update `binary_ufuncs` groupings
- [ ] Update `spectral_funcs` groupings
- [ ] Update `sparse_unary_ufuncs` groupings
- [ ] Update `sparse_csr_unary_ufuncs` groupings
- [ ] Update `sparse_reduction_ops` groupings
- [ ] Update `shape_funcs` groupings
- [ ] Update `reduction_ops` groupings

cc @ezyang @mruberry @Lezcano @peterbell10

### PR DESCRIPTION
**Pull request by ekamiti**
Fixes #107335. The skips were updated for the _ref ops to match those for eager mode where necessary. Part of breakdown of https://github.com/pytorch/pytorch/pull/104489.

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel @EikanWang @voznesenskym @penguinwu @Guobing-Chen @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @anijain2305

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by ekamiti** [comment]
Sorry to all the extra folks that got added to the review, it was due to the merge history getting messed up which I have now rectified.

**Pull request closed without merging**
