### PR TITLE
Fix a numerical issue of CUDA channels-last SyncBatchNorm

### PR DESCRIPTION
**Pull request by xwang233**
Fix a numerical issue of CUDA channels-last SyncBatchNorm

The added test is a repro for the numerical issue. Thanks for the help from @jjsjann123 who identified the root cause. Since pytorch SBN channels-last code was migrated from [nvidia/apex](https://github.com/nvidia/apex), apex SBN channels-last also has this issue. We will submit a fix there soon.

### CODE REVIEW

**Review by jjsjann123 — APPROVED** [review]
nitpicking: this is not a numerical issue but a bug in launch config.

**Comment by xwang233** [comment]
@ngimel any comments?

**Comment by ngimel** [comment]
Can you comment on what's the issue and why this is the fix?

**Comment by xwang233** [comment]
The issue is that, if you run the repro script in the test, the output tensor only has first 64 channels being correct with the rest channels being zero. As mentioned by @jjsjann123 , this is a cuda launch configuration issue, where the `lastPow2` shouldn't be there.

**Review by ngimel — APPROVED** [review]

**Pull request closed without merging**
