### PR TITLE
Make make_dual also return namedtuple when level less than zero

### PR DESCRIPTION
**Pull request by soulitzer**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #68631
* #68629
* #68630
* __->__ #68628

Differential Revision: [D32899681](https://our.internmc.facebook.com/intern/diff/D32899681)

### CODE REVIEW

**Review by albanD — APPROVED** [review]
Good catch

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32899681).

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32899681).

**Comment by soulitzer** [comment]
@soulitzer has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32899681).

**Pull request closed without merging**
