### PR TITLE
Clarify the searched string is displayed in the error message

### PR DESCRIPTION
**Pull request by xuhdev**

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 8c321b86:


* **2/2** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=8c321b86bc6d010b5a3b57ee6d748a4fea9c0120).

### :detective: 2 new failures recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4374257) pytorch_linux_xenial_py3_6_gcc5_4_ge_config_simple_test (1/2)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=92834706) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=92834706))
<details>
<summary>
<code>Jan 29 23:05:42 RuntimeError: test_jit_simple failed!</code>
</summary>

```
Jan 29 23:05:42 Ran 2369 tests in 85.913s 
Jan 29 23:05:42  
Jan 29 23:05:42 FAILED (failures=1, skipped=79, expected failures=1) 
Jan 29 23:05:42  
Jan 29 23:05:42 Generating XML reports... 
Jan 29 23:05:42 Traceback (most recent call last): 
Jan 29 23:05:42   File "test/run_test.py", line 457, in <module> 
Jan 29 23:05:42     main() 
Jan 29 23:05:42   File "test/run_test.py", line 450, in main 
Jan 29 23:05:42     raise RuntimeError(message) 
Jan 29 23:05:42 RuntimeError: test_jit_simple failed! 
Jan 29 23:05:42 + cleanup 
Jan 29 23:05:42 + retcode=1 
Jan 29 23:05:42 + set +x 
Jan 29 23:05:42 =================== sccache compilation log =================== 
Jan 29 23:05:42 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 29 23:05:42 Compile requests                 2 
Jan 29 23:05:42 Compile requests executed        0 
Jan 29 23:05:42 Cache hits                       0 
Jan 29 23:05:42 Cache misses                     0 
Jan 29 23:05:42 Cache timeouts                   0 
```

</details>

#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4374256) pytorch_linux_xenial_py3_6_gcc5_4_ge_config_legacy_test (2/2)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=92835125) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=92835125))
<details>
<summary>
<code>Jan 29 23:06:11 RuntimeError: test_jit_legacy failed!</code>
</summary>

```
Jan 29 23:06:11 Ran 2369 tests in 131.283s 
Jan 29 23:06:11  
Jan 29 23:06:11 FAILED (failures=1, skipped=63, expected failures=1) 
Jan 29 23:06:11  
Jan 29 23:06:11 Generating XML reports... 
Jan 29 23:06:11 Traceback (most recent call last): 
Jan 29 23:06:11   File "test/run_test.py", line 457, in <module> 
Jan 29 23:06:11     main() 
Jan 29 23:06:11   File "test/run_test.py", line 450, in main 
Jan 29 23:06:11     raise RuntimeError(message) 
Jan 29 23:06:11 RuntimeError: test_jit_legacy failed! 
Jan 29 23:06:11 + cleanup 
Jan 29 23:06:11 + retcode=1 
Jan 29 23:06:11 + set +x 
Jan 29 23:06:11 =================== sccache compilation log =================== 
Jan 29 23:06:11 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Jan 29 23:06:11 Compile requests               250 
Jan 29 23:06:11 Compile requests executed        0 
Jan 29 23:06:11 Cache hits                       0 
Jan 29 23:06:11 Cache misses                     0 
Jan 29 23:06:11 Cache timeouts                   0 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by suo** [comment]
mind pasting a quick before/after so I can see what it would look like?

**Comment by xuhdev** [comment]
@suo please see my update

**Comment by suo** [comment]
The output seems repetitive to me? Seems like the same range is being printed twice; you are basically doing what `found_range.highlight` does but manually, no?

**Comment by xuhdev** [comment]
@suo Hmm, I guess I was confused by the output. Probably clarifying the output a bit should be sufficient. I've updated the PR.

**Review by suo — APPROVED** [review]
lgtm! thanks for this

**Pull request closed without merging**
