### PR TITLE
Remove redundant device guard in Resize.h

### PR DESCRIPTION
**Pull request by kevint324**
In https://github.com/pytorch/pytorch/pull/113386 a device guard was [inserted](https://github.com/pytorch/pytorch/pull/113386/files#diff-2691af3a999b3a8f4a0f635aabcd8edf0ffeda501edfa9366648e8a89de12a90R30).

The new inserted device guarded has a clear and more confined guarded scope.
And it's hard to tell the exact purpose and scope of the  [old device guard](https://github.com/kurtamohler/pytorch/blob/78ffe49a3fcd3ddc4f9f98500ccd3cbdee22a029/aten/src/ATen/native/cuda/Resize.h#L41).

Removing the guard has negligible positive performance impact and make the code more understandable.

Thanks

### CODE REVIEW

**Review by eqy — APPROVED** [review]

**Comment by eqy** [comment]
CC @Skylion007 for stamp

**Comment by kevint324** [comment]
Hi @Skylion007 @mruberry 

Could you please take a look. Thanks

Cheers

**Comment by kevint324** [comment]
hi  @Skylion007 @eqy

Could you please take a look please.

Thanks

**Comment by kevint324** [comment]
Hi @mruberry  @lezcano  @ngimel  @peterbell10 

I still can't reach the maintainer. Could you please take a look please?
Or should I submit a issue to discuss it first?

Thanks a lot

**Review by lezcano — APPROVED** [review]
eqy approved

**Pull request closed without merging**
