### PR TITLE
Remove Windows compilation dependencies installation from CI/CD scripts

### PR DESCRIPTION
**Pull request by Blackhex**
They should be already installed in the runner VM.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

### CODE REVIEW

**Comment by Blackhex** [comment]
The Windows pipelines failures seems to be an unrelated issue #89996.

**Review by huydhn — APPROVED** [review]
LGTM once the Windows CI pass.  Windows nightly CPU builds fail, but they look unrelated https://hud.pytorch.org/pr/89909

**Comment by Blackhex** [comment]
Now all but one Linux unrelated workflows pass.

**Pull request closed without merging**
