### PR TITLE
Updates NCCL to 2.17.1

### LINKED ISSUE #750: NCCL Hang with CUDA_LAUNCH_BLOCKING=1
It seems to be a regression in v2.13 (2.10 should work) that when I run a simple MLP model (with all reduce) will hang when CUDA_LAUNCH_BLOCKING is present. The hang happens on all ranks with 100% GPU spinning on something. The backstack from gdb is this. It looks this ncclStrongStreamLaunchKernel is new in v2.13, so wondering if this is a new regression

#0  0x00007fec9b630c50 in ?? () from lib/libcuda.so.1
#1  0x00007fec9b49dcf7 in ?? () from lib/libcuda.so.1
#2  0x00007fec9b3f8b9f in ?? () from lib/libcuda.so.1
#3  0x00007fec9b3fa1b8 in ?? () from lib/libcuda.so.1
#4  0x00007fec9b3e301f in ?? () from /lib/libcuda.so.1
#5  0x00007fec9b636830 in ?? () from lib/libcuda.so.1
#6  0x00007fec9b370bd6 in ?? () from lib/libcuda.so.1
#7  0x00007fec9b372bc2 in ?? () from libcuda.so.1
#8  0x00007fec9b40d4d5 in ?? () from lib/libcuda.so.1
#9  0x00007fec9ae1405c in ?? () from /lib/libcudart.so.11.4.108
#10 0x00007fec9ae67f06 in cudaLaunchKernel () from /lib/libcudart.so.11.4.108
#11 0x00007fecdf7d6cf9 in ncclStrongStreamLaunchKernel(ncclCudaGraph, ncclStrongStream*, void*, dim3, dim3, void**, unsigned long) ()
#12 0x00007fecdf7a56c8 in ncclLaunchKernel(ncclComm*, ncclKernelPlan*) () 
#13 0x00007fecdf7c494d in ncclGroupEndInternal() () 
#14 0x00007fecdf7c5301 in ncclGroupEnd () from 
#15 0x00007fecdf794f4c in torch::cuda::nccl::AutoNcclGroup::~AutoNcclGroup() () 
#16 0x00007fecdf725655 in c10d::ProcessGroupNCCL::allgather(std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > >&, std::vector<at::Tensor, std::allocator<at::Tensor> >&, c10d::AllgatherOptions const&) ()
#17 0x00007feccf159640 in c10d::(anonymous namespace)::allgather_(std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, long) () 
#18 0x00007feccf163e8c in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<std::tuple<std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > >, c10::intrusive_ptr<c10d::Work, c10::detail::intrusive_target_default_null_type<c10d::Work> > > (*)(std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, long), std::tuple<std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > >, c10::intrusive_ptr<c10d::Work, c10::detail::intrusive_target_default_null_type<c10d::Work> > >, c10::guts::typelist::typelist<std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, long> >, std::tuple<std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > >, c10::intrusive_ptr<c10d::Work, c10::detail::intrusive_target_default_null_type<c10d::Work> > > (std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, long)>::call(c10::OperatorKernel*, c10::DispatchKeySet, std::vector<std::vector<at::Tensor, std::allocator<at::Tensor> >, std::allocator<std::vector<at::Tensor, std::allocator<at::Tensor> > > > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::intrusive_ptr<c10d::ProcessGroup, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroup> > const&, long) ()

### PR DESCRIPTION
**Pull request by syed-ahmed**
This PR updates NCCL submodule to 2.17.1.
Closes https://github.com/NVIDIA/nccl/issues/750

cc: @ptrblck @crcrpar

### CODE REVIEW

**Comment by kwen2501** [comment]
Thanks much for creating the PR!

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
@weiwangmeta should we also update internally?

**Comment by weiwangmeta** [comment]
> @weiwangmeta should we also update internally?

Thanks for tagging! I will check internal version and align with this PR via 3rd party update process.

**Comment by weiwangmeta** [comment]
> @weiwangmeta should we also update internally?

@ngimel fyi that the other internal team will take care of NCCL submodule updates according to their roadmap.  Merging of this PR can be independent of internal NCCL submodule update.

**Review by ptrblck — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
> @pytorchbot revert -m "looks like it broke inductor distributed tests https://hud.pytorch.org/pytorch/pytorch/commit/b113a09ef90decbc703722bfdc2064fc5eb54a19#12344853677" -c nosignal

@clee2000 I don't think no signal is right description here: I've issued `merge -r` and it proceeded with the merge despite the failures reported in https://hud.pytorch.org/pr/97407

Also, why there is `ciflow/periodic` tag despite the lack of label?

**Comment by clee2000** [comment]
> > @pytorchbot revert -m "looks like it broke inductor distributed tests https://hud.pytorch.org/pytorch/pytorch/commit/b113a09ef90decbc703722bfdc2064fc5eb54a19#12344853677" -c nosignal
> 
> @clee2000 I don't think no signal is right description here: I've issued `merge -r` and it proceeded with the merge despite the failures reported in https://hud.pytorch.org/pr/97407
> 
> Also, why there is `ciflow/periodic` tag despite the lack of label?

The newly opened PR uses the same commit and got tagged with ciflow/periodic, so the periodic jobs show up on hud for this PR as well.  The periodic jobs I see on hud finished at 9pm, which is after I reverted this PR

**Pull request closed without merging**
