### PR TITLE
Fix SDPA for SAM

### PR DESCRIPTION
**Pull request by jbschlosser**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #115192
* #115191
* __->__ #115636

Addresses the regression for Segment Anything Fast in https://github.com/pytorch-labs/segment-anything-fast/issues/99

### CODE REVIEW

**Review by soulitzer — APPROVED** [review]
Nice!

**Review by ani300 — APPROVED** [review]
Lgtm! Do we also want to support this for strided NT at all? Or at least add some docs mentioning this kind of input is also valid for SDPA+NT, as it breaks the current expected inputs for the SDPA api

**Comment by jbschlosser** [comment]
> Lgtm! Do we also want to support this for strided NT at all?

Hm, I think it might be a good idea eventually but it's a bit more involved to do that since SDPA has notions of nested-ness baked in throughout with hard-coded assumptions. It was easy for jagged since we can bypass these via the dense buffers.

> Or at least add some docs mentioning this kind of input is also valid for SDPA+NT, as it breaks the current expected inputs for the SDPA api

Good point. FWIW I see this as matching the original SDPA signature conceptually: `(B0, B1, ..., BN, S, D)` with the detail that B1 in this case is ragged. I think it's a good idea to update the docs to mention this, yeah.

**Pull request closed without merging**
