### PR TITLE
fix infinite loop when get_max_threads is nonzero but num_threads is 1

### PR DESCRIPTION
**Pull request by umanwizard**

### CODE REVIEW

**Comment by umanwizard** [comment]
The issue here is that we will skip this "serial" branch every time (since get_max_threads is > 1 but in_parallel_region is false), then go into the other branch, which calls at::parallel_for, which just calls back into it with the same begin/end bounds.

**Review by colesbury — APPROVED** [review]

**Comment by avmgithub** [comment]
For some reason unknown yet this change has caused ppc64le test_torch.TestTorch.test_std_dim test to go into an infinite loop.  The memory used keeps growing until system memory is exhausted or process is killed because it hits it ulimit.

**Comment by avmgithub** [comment]
@ezyang I can put some debug statements if that is what you mean.  I was able to do it with ./build/bin/tbb_init_test.  Let me know what you want me to do.

**Comment by umanwizard** [comment]
@avmgithub yes adding debug statements to show the values of `at::get_num_threads` and `at::get_max_threads` would be useful.

Alternatively if you have any way to give me access to a Power machine I can try to debug.

**Comment by avmgithub** [comment]
@umanwizard fyi , the issue ppc64le was having went away after @ezyang put this back in #15315.  So I'm not really sure how all is connected. But for now ppc64le is building/testing fine.

**Comment by umanwizard** [comment]
@avmgithub Ok, thanks for the update.

It's still a bit worrying that this was broken and we don't understand why...

Anyway, if you start seeing it again in the future, please let me know.

**Pull request closed without merging**
