### PR TITLE
Update Triton

### PR DESCRIPTION
**Pull request by bhack**
Fix pytorch nightly compilation for cuda linking

Fixes #ISSUE_NUMBER

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Comment by bhack** [comment]
More details at:
https://github.com/openai/triton/pull/3053

Why have we not detected this with the tests on our side last time we have updated the pin?

**Review by Skylion007 — DISMISSED** [review]

**Comment by bhack** [comment]
Can we wait for this before we cut the next nightly?

**Comment by bhack** [comment]
Do I need to do something specific for:
https://github.com/pytorch/pytorch/actions/runs/7832512037/job/21371840351 or it was already failing?

**Comment by bhack** [comment]
It seems it was just an http failure right?

**Comment by shunting314** [comment]
There seems to be some real failure caused by interface change of AttrsDescriptor.

Bert also wants to try out the OSS triton pin update process. So cc @bertmaher

**Comment by bhack** [comment]
@shunting314 Can we run again the tests?

**Comment by bhack** [comment]
Green lights here :traffic_light:

**Comment by shunting314** [comment]
Is the change backward-compatible here? Also we need run some perf test

**Comment by bhack** [comment]
> Is the change backward-compatible here? 

How we need to test this?

**Comment by shunting314** [comment]
> How we need to test this?
I usually run the PR against the old version of triton before pin update and make sure it still works.

**Comment by bhack** [comment]
Also I don't see any other conditional branch based on runtime triton version in the pytorch code. Can you point me on one of these cases? 
I suppose instead that Pytorch is working only on our specific trition packaged version/wheel.

**Comment by shunting314** [comment]
> I don't have the resources to allocate a local full compilation with all the tests.

Oh, you could split the PR into
- the first PR with all changes except the pin update
- the second PR with just the pin update.

Then the CI for the first PR will run against the old version of triton.


Here is an example in inductor that handles backward compatibility: https://github.com/pytorch/pytorch/blob/34f7dc9eba16bc96eb7277af0e11e6d4d49c80f2/torch/_inductor/triton_heuristics.py#L376-L391

**Comment by bhack** [comment]
> Oh, you could split the PR into
What I meant is that developing with only the CI is really, really slow as every iteration it is currently so laggy 

in any case
https://github.com/pytorch/pytorch/pull/119636

**Comment by bhack** [comment]
See also my comment at https://github.com/pytorch/pytorch/pull/119636#issuecomment-1936980408.
I don't think this approach is scalable if the CI is not explicitly and regularly testing all the Trition versions we want to cover against regression.

**Comment by shunting314** [comment]
> What I meant is that developing with only the CI is really, really slow as every iteration it is currently so laggy 

You could also run some tests with PT2 benchmark scripts against an old triton version to capture any obvious issues earlier. Here is an example:
```
python benchmarks/dynamo/huggingface.py --backend inductor --amp --performance --only BertForMaskedLM --training
```

**Comment by shunting314** [comment]
> I don't think this approach is scalable if the CI is not explicitly and regularly testing all the Trition versions we want to cover against regression.

We don't have the resource to test against all previous triton pins used in inductor. Right now our process is best effort and guarantees that both the current and new pin works for each pin upgrade. Hopefully with that guarantee, earlier pins would also work - but there are chances that it doesn't in theory.

**Comment by bhack** [comment]
As we are packaging and versioning our own Triton version isn't better to enforce just the version we have tested on the CI without complicating too much the interfaces as the Triton API doesn't seems to be super stable.

**Review by bertmaher — CHANGES_REQUESTED** [review]
Please don't update the Triton pin yet.  Updating it is pretty fragile and we have a battery of Meta-internal tests that need to pass before that happens.

**Comment by bhack** [comment]
@bertmaher isn:t pytorch nighty compile broken on your side cause https://github.com/openai/triton/pull/3053?

**Comment by bhack** [comment]
@shunting314 I've changed this after https://github.com/pytorch/pytorch/pull/119636 merge to just change the pin.
@bertmaher Can you trigger the internal tests/checks?

**Comment by bhack** [comment]
The single failure is just a http timeout.

**Comment by lezcano** [comment]
@bertmaher what's the state of this one? We would like to push the pin to be able to land https://github.com/pytorch/pytorch/pull/120429/, which is a prerequisite to support mamba.

**Comment by lezcano** [comment]
Actually, could this PR push the pin to one that includes https://github.com/openai/triton/pull/3111?

**Comment by bertmaher** [comment]
Hi @lezcano!  It's taking a bit longer to move the Meta-internal pin than planned, and I'd really like to not get this out of sync, since we'll start suffering from version skew -- I've made some progress on it but there was significant refactoring in how "third party" backends are handled in Triton's cmake build that need some porting to the internal buck/bazel build.

ETA is probably early next week to sort those out and make the pin bump happen

**Comment by lezcano** [comment]
That sounds good. Let's land this update when it's ready and then we'll have another round to push the pin slightly further. Thank you!

**Comment by bertmaher** [comment]
@lezcano @bhack so actually, I didn't pay enough attention, and I've been preparing to bump the internal version to 20038f90ffbab26c62e5fcbeec40b609c9ab4c45.  Any objection to trying that here?

**Comment by lezcano** [comment]
Wow, even better! We'll need to keep bumping the version fairly frequently to add some work from @peterbell10 and I, so yeah, the further we push the pin the better!

**Comment by bhack** [comment]
Ok

**Comment by bertmaher** [comment]
So, change-of-change of plans, that commit breaks various stuff, and I don't want to hold this bump any longer.  Let's go ahead and land this Monday morning, and we'll follow up with another version bump soon thereafter.

**Review by bertmaher — DISMISSED** [review]

**Comment by oulgen** [comment]
`make triton` is no longer working after this PR
```
ERROR: Could not find a version that satisfies the requirement pytorch-triton==3.0.0+a9bc1a3647 (from versions: 2.0.0+0d7e753227, 2.0.0+3aa3d7024e, 2.0.0+af76c989eb, 2.0.0+b8b470bc59, 2.0.0+c8bfe3f548, 2.0.0+d54c04abe2, 2.1.0, 2.1.0+2c32f43999, 2.1.0+3c400e7818, 2.1.0+440fd1bf20, 2.1.0+46672772b4, 2.1.0+6e4932cda8, 2.1.0+7d1a95b046, 2.1.0+9820899b38, 2.1.0+9e3e10c5ed, 2.1.0+bcad9dabe1, 2.1.0+e6216047b8, 2.1.0+e650d3708b, 2.2.0+e28a256d71, 3.0.0+901819d2b6)
ERROR: No matching distribution found for pytorch-triton==3.0.0+a9bc1a3647
```

**Comment by bhack** [comment]
@oulgen Is it related to https://github.com/pytorch/pytorch/pull/121169?

**Comment by oulgen** [comment]
> @oulgen Is it related to #121169?

yes

**Comment by bertmaher** [comment]
Are these new tests, or what happened here?

**Comment by oulgen** [comment]
@aakhundov  ^

**Comment by shunting314** [comment]
In even newer triton, `divisibility_by_8` is gone: https://github.com/openai/triton/blob/0f74acc4d92ea506105d25b2724439df85133b19/python/triton/compiler/compiler.py#L21-L22 . Not sure if this is what @aakhundov  mean

**Comment by bhack** [comment]
@shunting314 is it still used here?
https://github.com/pytorch/pytorch/blob/3381f282c35b61ca991eb84c0e938667244cbc7a/test/inductor/test_metrics.py#L20

**Comment by aakhundov** [comment]
@bertmaher @bhack re. broken `test_triton_kernel_equal_to_1_arg`, yeah, so `ids_of_folded_args` seems to be gone in the Triton version this PR updates to (can't find it if grep [jit.py](https://github.com/openai/triton/blob/a9bc1a36470eefafe0e2ab2503b8698f1e89e7e3/python/triton/runtime/jit.py)). An easy fix would be removing the lines 1002 and 1005 from the unit test below:

https://github.com/pytorch/pytorch/blob/3381f282c35b61ca991eb84c0e938667244cbc7a/test/inductor/test_triton_kernels.py#L998-L1005

I'm wondering why we didn't catch this error, though. Was the PR not rebased before landing? I've added the test mid-last week.

**Comment by aakhundov** [comment]
> In even newer triton, divisible_by_8 is gone:

In the Triton version that this PR updates to, `divisible_by_8` is still in: https://github.com/openai/triton/blob/a9bc1a36470eefafe0e2ab2503b8698f1e89e7e3/python/triton/runtime/jit.py#L227-L231

**Comment by bhack** [comment]
When I've adapted the interface `divisible_by_8` was still available https://github.com/pytorch/pytorch/pull/119636. It was only removed `"ids_of_folded_args` are we talking about different triton shas?

**Comment by aakhundov** [comment]
> When I've adapted the interface divisible_by_8 was still available https://github.com/pytorch/pytorch/pull/119636. It was only removed ids_of_folded_args. Are we talking about different triton shas?

@bhack yeah, it's just ids_of_folded_args. Here's a forward fix for this test: https://github.com/pytorch/pytorch/pull/121192

**Review by lezcano — APPROVED** [review]

**Comment by lezcano** [comment]
Given the revert, it needs a manual rebase. Oh well.

**Pull request closed without merging**
