### PR TITLE
[RPC tests] Fix test_init_(rpc|pg)_then_(rpc|pg) not shutting down RPC

### PR DESCRIPTION
**Pull request by lw**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#41558 [RPC tests] Fix test_init_(rpc|pg)_then_(rpc|pg) not shutting down RPC**

The problem was due to non-deterministic destruction order of two global static variables: the mutexes used by glog and the RPC agent (which was still set because we didn't call `rpc.shutdown()`). When the TensorPipe RPC agent shuts down some callbacks may fire with an error and thus attempt to log something. If the mutexes have already been destroyed this causes a SIGABRT.

Fixes https://github.com/pytorch/pytorch/issues/41474

Differential Revision: [D22582779](https://our.internmc.facebook.com/intern/diff/D22582779/)

Differential Revision: [D22582779](https://our.internmc.facebook.com/intern/diff/D22582779)

### CODE REVIEW

**Review by mrshenli — APPROVED** [review]
Thanks for the catch!

**Comment by mrshenli** [comment]
Do we also need to add the shutdown call to other tests, e.g., `test_register_rpc_backend_and_set_and_start_rpc_backend` and `test_duplicate_name`?

**Comment by lw** [comment]
Added it to `test_register_rpc_backend_and_set_and_start_rpc_backend` (that required adding a dummy `shutdown` method to the stub agent, and do an ungraceful shutdown to avoid having to support `_wait_all_workers()`). I didn't add it to `test_duplicate_name` because in that test the creation of the agent is supposed to throw and thus the agent is never even set (which would then cause `rpc.shutdown()` to fail).

**Comment by lw** [comment]
Actually, `test_register_rpc_backend_and_set_and_start_rpc_backend` doesn't need `rpc.shutdown()` either because it mocks `_set_and_start_rpc_agent` so it doesn't actually set the global agent.

**Pull request closed without merging**
