### PR TITLE
Do not import sympy within torch._prims_common

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #112034

This is the first of a few PRs that avoid importing SymPy at import time.
The pitch here is that we (almost!) do not have SymPy on our API, so
this should be feasible.

This should speed-up torch imports by a good 15% as per
https://dev-discuss.pytorch.org/t/delving-into-what-happens-when-you-import-torch/1589

In this PR we just move a few global imports into local imports.

### CODE REVIEW

**Comment by lezcano** [comment]
@malfet @ezyang This may may need some minor tweaking, but as it stands, it works and we get a hefty 15% speed-up on import times.
What do you guys think about this? All of it was done via a few local imports, a TYPE_CHECK and two PRs that do some code movement.

**Comment by ezyang** [comment]
I'm not fundamentally opposed to this, but I don't see how we're going to manage to keep enforcing it, it's very easy to mess this up.

**Comment by lezcano** [comment]
I add a test in the last PR of this stack, have a look

**Review by ezyang — APPROVED** [review]

**Comment by mthrok** [comment]
> I'm not fundamentally opposed to this, but I don't see how we're going to manage to keep enforcing it, it's very easy to mess this up.

I found TensorFlow's LazyLoader an elegant implementation of lazy import. It uses `types.ModuleType` and defining `__getattr__`, then updating `self.__dict__`. Perhaps something similar can be used as a standard way to access the module.

https://github.com/tensorflow/tensorflow/blob/51b601fa6bb7e801c0b6ae73c25580e40a8b5745/tensorflow/python/util/lazy_loader.py#L24

**Pull request closed without merging**
