### PR TITLE
use UBSAN on some tests

### PR DESCRIPTION
**Pull request by cyyever**
Fixes #ISSUE_NUMBER

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

### CODE REVIEW

**Comment by zou3519** [comment]
This PR doesn't actually enable ubsan, right? it just adds some skips for it?

**Comment by cyyever** [comment]
@zou3519 It just remove previous skips on some tests.

**Review by kshitij12345 — APPROVED** [review]
Given green CI, LGTM! Thanks @cyyever

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
