### PR TITLE
Add cudnn install 8.7.0.84 for CUDA 11.8 

### PR DESCRIPTION
**Pull request by atalman**
Add cudnn install 8.7.0.84 for CUDA 11.8 .

Same as: https://github.com/pytorch/pytorch/pull/84964
Related to https://github.com/pytorch/builder/pull/1271
Test PR: https://github.com/pytorch/pytorch/pull/92971

### CODE REVIEW

**Comment by atalman** [comment]
Related to https://github.com/pytorch/builder/pull/1271

**Review by kit1980 — APPROVED** [review]

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
@atalman can you please elaborate, why you though that signal from 11.8 tests is unrelated to PR that makes changes to  11.8 config? Also, you've forgot to add `ciflow/trunk` which now contains majority of 11.8 testing, isn't it?
See https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=cuda11.8

**Comment by atalman** [comment]
Reason of initial failure  failing cudnn build since cudnn was missing from s3:
https://github.com/pytorch/pytorch/actions/runs/4026548941/jobs/6921196025#step:5:18599

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
