### PR TITLE
Exempt `_foreach_norm` from autograd_not_implemented_fallback check

### LINKED ISSUE #93940: Foreach op don't follow aten level debug asserts
Since https://github.com/pytorch/pytorch/pull/91846 has moved to make torch.nn.utils.clip_grad_norm_() use foreach ops, it throws the error message:
*** RuntimeError: t.storage().use_count() == 1 INTERNAL ASSERT FAILED at "caffe2/torch/csrc/autograd/autograd_not_implemented_fallback.cpp":189, please report a bug to PyTorch.

when PyTorch is built with debug asserts.

Given the assert, the error is that this foreach op should be returning a brand new Tensor but it is actually returning a Tensor that shares storage with at least another one.
- If this is done on purpose for a good reason, we should remove this assert
- If that is not expected, then it can be a bug in the implementation where it returns a view where it should not.

cc @ezyang @gchanan @zou3519 @crcrpar @mcarilli @ngimel

### PR DESCRIPTION
**Pull request by crcrpar**
Fixes #93940

### CODE REVIEW

**Review by ngimel — APPROVED** [review]

**Comment by ngimel** [comment]
Can you leave a comment about why you are exempting foreach_norm?

**Review by albanD — COMMENTED** [review]
Thanks!
Did you test it locally?

**Comment by crcrpar** [comment]
I ran 
```
$ DEBUG=1 python setup.py develop --cmake
$ python test/test_foreach.py TestForeachCUDA -k test_reduce_op
```
as a test

**Review by albanD — APPROVED** [review]
Awesome!

**Comment by albanD** [comment]
@pytorchbot merge

Thanks for the quick fix on this!

**Pull request closed without merging**
