### PR TITLE
[DeviceMesh] Fix __getitem__ docstring typo 

### PR DESCRIPTION
**Pull request by wz337**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Review by rohan-varma — COMMENTED** [review]
Will this be cherry-picked into 2.1?

**Review by wanchaol — APPROVED** [review]
lgtm, I think we should submit a patch to 2.1 release branch soon as @rohan-varma mentioned

**Comment by wz337** [comment]
> lgtm, I think we should submit a patch to 2.1 release branch soon as @rohan-varma mentioned

Noob question: do I simply create the same PR and submit it to 2.1 release branch?

**Comment by wanchaol** [comment]
> > lgtm, I think we should submit a patch to 2.1 release branch soon as @rohan-varma mentioned
> 
> Noob question: do I simply create the same PR and submit it to 2.1 release branch?

@wz337 see instructions in this issue https://github.com/pytorch/pytorch/issues/108055

**Pull request closed without merging**
