### PR TITLE
Pass all arguments when quantizing embedding bag from float

### PR DESCRIPTION
**Pull request by annop-w**
cc @malfet @snadampal @milpuz01

### CODE REVIEW

**Comment by annop-w** [comment]
[@pytorchbot](https://github.com/pytorchbot) label "module: arm"

**Comment by annop-w** [comment]
@malfet Could I please get a review ? Thank you.

**Comment by ZainRizvi** [comment]
(commenting here with just `@pytorchmergebot rebase` will do it for you)

**Comment by snadampal** [comment]
Hi @annop-w , please fix the linter failure.

~~~
 Warning (PYFMT) format
    Run `lintrunner -a` to apply this patch.

    You can run `lintrunner -a` to apply this patch.

    383  383 | 
    384  384 |         # Create quantized EmbeddingBag module and pass in the quantized weight
    385  385 |         qembedding_bag = EmbeddingBag(
    385      |-            mod.num_embeddings,mod.embedding_dim,max_norm=mod.max_norm,norm_type=mod.norm_type,
    386      |-            scale_grad_by_freq=mod.scale_grad_by_freq,mode=mod.mode,sparse=mod.sparse,
    387      |-            include_last_offset=mod.include_last_offset, dtype=dtype
         386 |+            mod.num_embeddings,
         387 |+mod.embedding_dim,
         388 |+max_norm=mod.max_norm,
         389 |+norm_type=mod.norm_type,
         390 |+            scale_grad_by_freq=mod.scale_grad_by_freq,
         391 |+mode=mod.mode,
         392 |+sparse=mod.sparse,
         393 |+            include_last_offset=mod.include_last_offset,
         394 |+            dtype=dtype,
    389  395 |         )
    390  396 |         qembedding_bag.set_weight(qweight)
    391  397 |         return qembedding_bag
~~~

**Comment by annop-w** [comment]
@snadampal Done.

**Review by snadampal — APPROVED** [review]

**Review by jerryzh168 — APPROVED** [review]

**Comment by annop-w** [comment]
@malfet @digantdesai Could this now be merged ? Thank you.

**Pull request closed without merging**
