### PR TITLE
Actually deprecate __torch_function__ as plain methods

### PR DESCRIPTION
**Pull request by albanD**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #65145
* __->__ #64843
* #64842
* #64841

Fix for https://github.com/pytorch/pytorch/issues/63767

Differential Revision: [D30991425](https://our.internmc.facebook.com/intern/diff/D30991425)

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Test?

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30991425).

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30991425).

**Comment by albanD** [comment]
@albanD has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D30991425).

**Pull request closed without merging**
