### PR TITLE
Format DTensor dispatch.py and _meta_registrations.py

### PR DESCRIPTION
**Pull request by mrshenli**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #98113
* __->__ #98114

Format-only changes with black and lintrunner to prepare for the commit on top.

Differential Revision: [D44603809](https://our.internmc.facebook.com/intern/diff/D44603809)

### CODE REVIEW

**Comment by mrshenli** [comment]
@mrshenli has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D44603809).

**Comment by mrshenli** [comment]
Test failure is irrelevant

```
2023-04-01T03:18:33.7513744Z test_jit_fuser_te.py::TestTEFuserDynamic::test_profiler Command took >20min, returning 124
2023-04-01T03:18:33.7514249Z FINISHED PRINTING LOG FILE of test_jit_fuser_te 1/4 (/var/lib/jenkins/workspace/test/test-reports/test_jit_fuser_te_dyw8wl8s.log)
2023-04-01T03:18:33.7514486Z 
2023-04-01T03:18:33.7514573Z test_jit_fuser_te 1/4 failed!
2023-04-01T03:18:33.7840516Z Traceback (most recent call last):
2023-04-01T03:18:33.7840818Z   File "/var/lib/jenkins/workspace/test/run_test.py", line 1398, in <module>
2023-04-01T03:18:33.7843956Z     main()
2023-04-01T03:18:33.7844186Z   File "/var/lib/jenkins/workspace/test/run_test.py", line 1356, in main
2023-04-01T03:18:33.7847546Z     raise RuntimeError(
2023-04-01T03:18:33.7847778Z RuntimeError: test_jit_fuser_te 1/4 failed!
```

**Review by yifuwang — APPROVED** [review]

**Review by fegin — APPROVED** [review]
LGTM

**Comment by awgu** [comment]
Do you want to add the two files changed to `.lintrunner.toml` to enforce the formatting changes for the future?
https://github.com/pytorch/pytorch/blob/64077ce511f9e77b439ec3d8b7e19b2ba92dd258/.lintrunner.toml#L826-L829

**Comment by mrshenli** [comment]
> Do you want to add the two files changed to .lintrunner.toml to enforce the formatting changes for the future?

Good point! let me add this on top of the stack.

**Pull request closed without merging**
