### PR TITLE
Fix NaN handling in torch.mv.

### PR DESCRIPTION
**Pull request by gchanan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #33570 Minimize the cases where we have to cpu_zero.
* **#31666 Fix NaN handling in torch.mv.**

List of changes:
1) Fix a case where torch.mv was not handling NaNs correctly.  In particular, with a transposed tensor and expanded vector, NaNs in the output are kept, even if beta = 0.
This is handled in the `out=` case by zero-ing out the passed-in Tensor, but this can happen just the same with the non-out variant if the allocated tensor happens to have a NaN.
Also adds tests for this case.
NOTE: we zero out the output tensor in all cases for mv and mm, even though this is probably overkill.  I didn't find another case where this would be a problem, but the old code at least
attempted to do this for all mv and mm calls and I didn't add comprehensive testing to be sure that it's not a problem.

2) on CPU: move mv, mv_out, mm, mm_out to be direct wrappers on _th_addmv, _th_addmm, rather than having their own wrappers in Declarations.cwrap.
Ths is to remove the magic around cpu_zero from the codegen, which simplifies the codegen and makes testing this easier.

Differential Revision: [D19239953](https://our.internmc.facebook.com/intern/diff/D19239953)

### CODE REVIEW

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 361bf075:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=361bf075f3260f096ba57360024babf03fa0fefd).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4078455) pytorch_xla_linux_xenial_py3_6_clang7_test (1/1)
**Step:** "Test" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=78732993) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=78732993))
<details>
<summary>
<code>Dec 28 00:11:30 ....s.s...ssssss.s.ssssssssssss.sssss.ss..s....ssss....ss.s../test/run_tests.sh: line 64:   187 Segmentation fault      (core dumped) python3 "$CDIR/../../test/test_torch.py" "$@" -v TestTorchDeviceTypeXLA 2>&1</code>
</summary>

```
Dec 28 00:10:19 	PyEval_EvalCode 
Dec 28 00:10:19 	 
Dec 28 00:10:19 	PyRun_FileExFlags 
Dec 28 00:10:19 	PyRun_SimpleFileExFlags 
Dec 28 00:10:19 	Py_Main 
Dec 28 00:10:19 	main 
Dec 28 00:10:19 	__libc_start_main 
Dec 28 00:10:19 	 
Dec 28 00:10:19 *** End stack trace *** 
Dec 28 00:10:19 Negation, the `-` operator, on a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead. 
Dec 28 00:11:30 ....s.s...ssssss.s.ssssssssssss.sssss.ss..s....ssss....ss.s../test/run_tests.sh: line 64:   187 Segmentation fault      (core dumped) python3 "$CDIR/../../test/test_torch.py" "$@" -v TestTorchDeviceTypeXLA 2>&1 
Dec 28 00:11:30        188 Done                    | tee $LOGFILE 
Dec 28 00:11:30 + cleanup 
Dec 28 00:11:30 + retcode=139 
Dec 28 00:11:30 + set +x 
Dec 28 00:11:30 =================== sccache compilation log =================== 
Dec 28 00:11:30 =========== If your build fails, please take a look at the log above for possible reasons =========== 
Dec 28 00:11:30 Compile requests                  7 
Dec 28 00:11:30 Compile requests executed         6 
Dec 28 00:11:30 Cache hits                        0 
Dec 28 00:11:30 Cache misses                      6 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by gchanan** [comment]
Fixes: https://github.com/pytorch/pytorch/issues/31663

**Comment by gchanan** [comment]
Had a brief discussion with @ngimel:
1) Will need to turn off CUDA for this; I guess cublas doesn't handle this case
2) (Follow-on PR) for performance reasons will minimize the cases that where we zero the output.  We probably don't need to zero it in `torch.mm` (I think all codepaths can be verified by inspection), and we probably only need to zero in `torch.mv` if `beta` == 0 and we would have called sscal_ (or the equivalent for other types).  I'd prefer to do that in a follow-on PR because I'm not 100% sure removing the zeros is safe (there's no comment about why we do it); I only found a single case where we need it and I'd like to be able to bisect to a trivial PR if removing them is a problem.

**Comment by gchanan** [comment]
I turned off the CUDA tests, other changes to come in the a new commit in the stack.

**Review by ngimel — APPROVED** [review]
LGTM, when the tests pass.

**Pull request closed without merging**
