### PR TITLE
[BE][Easy] replace `import pathlib` with `from pathlib import Path`

### PR DESCRIPTION
**Pull request by XuehaiPan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #129409
* #129374
* __->__ #129426

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

### CODE REVIEW

**Comment by justinchuby** [comment]
In torch/onnx we prefer importing modules only: https://google.github.io/styleguide/pyguide.html#22-imports

**Comment by XuehaiPan** [comment]
> In torch/onnx we prefer importing modules only: [google.github.io/styleguide/pyguide.html#22-imports](https://google.github.io/styleguide/pyguide.html#22-imports)

Reverted.

**Review by malfet — APPROVED** [review]

**Review by malfet — APPROVED** [review]
Looks good to me, but please avoid making changes unrelated to the PR subject (lots of formatting changes to test_serialization are obviously a no-op, but have nothing to do with pathlib import being changed, are they?

**Pull request closed without merging**
