### PR TITLE
[ROCm][Inductor][CK] Enable scaled mm with bias in gemm max autotune with CK backend

### PR DESCRIPTION
**Pull request by tenpercent**
## Testing
```
pytest test/inductor/test_ck_backend.py -k scaled_mm
```
cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @zjing14

### CODE REVIEW

**Review by chenyang78 — APPROVED** [review]
LGTM. Thanks!

**Comment by tenpercent** [comment]
Link #125453

**Pull request closed without merging**
