### PR TITLE
Document debugability features in torch.distributed

### PR DESCRIPTION
**Pull request by rohan-varma**
Adds comprehensive documentation around debugability features added to `torch.distributed` recently, including the `monitored_barrier` and TORCH_DISTRIBUTED_DEBUG env variable.

dist_one
dist_two

### CODE REVIEW

**Review by H-Huang — APPROVED** [review]
Great addition to the docs!

**Review by zhaojuanmao — APPROVED** [review]
looks great.

'TORCH_DISTRIBUTED_DEBUG' will be useful to other packages that use c10d collective calls, right?  e.g., FSDP uses all_gather and reducer_scatter, sync_batch_norm uses all_gather. 
if users set 'TORCH_DISTRIBUTED_DEBUG' to detail, other packages like FSDP and syncBatchNorm will automatically get desync related debug info, right? do you want to add those info in the documentation?

**Comment by rohan-varma** [comment]
@zhaojuanmao Yes, this is the case as long as they use pytorch c10d APIs and process groups created with new_group and init_process_group (which are the only APIs for proper process group creation in pytorch). will add this to the doc

**Review by wayi1 — APPROVED** [review]
Looks great!

**Pull request closed without merging**
