### PR TITLE
Torch module state dictionary loading should not use getattr. It should use dict.get

### PR DESCRIPTION
**Pull request by junesg**
Summary:
Pytorch Moule loading should not use getattr, given that the state-dictionary is defined as OrderedDict

Quick example to demonstrate:
```
from collections import OrderedDict
state = OrderedDict( {"state0": 1, "state1": 1, "_metadata": {"meta0":0, "meta1":1}})
print (state)
try:
    print(getattr(state,"_mdetadata"))
except:
    print("Can not getattr state._mdetadata.")
print(state.get("_metadata", None))

```

Output:

```
OrderedDict([('state0', 1), ('state1', 1), ('_metadata', {'meta0': 0, 'meta1': 1})])
Can not getattr state._mdetadata.
{'meta0': 0, 'meta1': 1}
```

Test Plan: TBD

Differential Revision: D30757263

### CODE REVIEW

**Comment by albanD** [comment]
Hi,
Thanks for sending a PR.
Could you give more context on why you want to remove the getattr? This would be BC-breaking I think.
Also the extra del doesn't look right. Could you explain why you want to do that here?

**Comment by junesg** [comment]
Happy to elaborate 

> Could you give more context on why you want to remove the getattr? This would be BC-breaking I think.

According to pytorch documentation, state_dict is a ordered dictionary, not a tensor. https://pytorch.org/tutorials/beginner/saving_loading_models.html#what-is-a-state-dict
Also from "load_state_dict" function, we specify state_dict as OrderedDict.  Therefore the changes in this diff is reasonable.

In fairseq, we load models from model.state_dict(), which is a ordered dictionary. I noticed that module loading has consistently failed to load metadata due to ``` metadata = getattr(state_dict, '_metadata', None)```  being None.  But i fyou use ``` metadata = state_dict.get('_metadata', None) ``` it is not None. In order I believe following the pytorch tutorial and documentation, we should use dict.get instead of getattr on dictionary. 


Pls advice how to avoid test failures?

**Comment by junesg** [comment]
> Also the extra del doesn't look right. Could you explain why you want to do that here?

During model loading time, metadata is extracted from the state_dict and fed into ``` _load_from_state_dict ``` as ``` local_metadata ```. I noticed that if we do not ``` del state_dict['_metadata'] ```, the model loading in fairseq throws a bug for unexpected keys (i.e. _metadata) in the state. 

Pls advice if there are other ways to fix. thank you very much.

**Comment by albanD** [comment]
From offline discussion, the behavior for vanilla Modules is correct but the `_metadata` handling is indeed surprising.
In particular it is not stored as an entry in the dict but an attribute (and so it doesn't appear when you print/do .get()).
So if manually reconstructing it, you need to be careful to keep that behavior.

**Comment by junesg** [comment]
I'd like to abandon this pull but I echo @albanD  on what I observed on the fairseq level: 
Module.load_state_dict only works on the following assumptions with regards to state_dict: 
1. state_dict is an OrderedDict
2. state_dict DOES NOT have key "_metadata". i.e. state_dict["_metadata"] should not exist. Otherwise the strict version of module state loading will throw the error that "unexpected key \"_metadata\" was found"
3. state_dict has attribute state_dict._metadata.

The behavior above is undesirable because _metadata is not stored during print, and hard to get during .get(). I'd recommend more investigation into an alternative design.

**Pull request closed without merging**
