### PR TITLE
[Draft][PowerSGD] Custom orthogonalization kernel

### PR DESCRIPTION
**Pull request by younik**
Since the orthogonalization method of PowerSGD can be a major bottleneck, I wrote a custom kernel for that. 
Compared to `torch.linalg.qr` it can achieve ~2x speedup for the sizes that matter for PowerSGD. It isn't faster in general, thus I  didn't make it available as a public API, but it can be called with `torch.ops.distributed.orthogonalize`.

Since `torch.linalg.qr` is called many times in powerSGD_hook, this improvement can reduce considerably powerSGD_hook time.

This is a draft PR to gather feedback on this.

## Times of a powerSGD_hook call with different ranks
The followings times are gather on a single node, thus without communication time.
timings

## Times of orthogonalize kernel with different sizes
```
shape		custom (us)	torch.qr (us)	speedup
(2, 256):	 36.2 	 	 88.2 		 2.44x
(2, 512):	 39.0 	 	 85.0 		 2.18x
(2, 1024):	 35.8 	 	 88.2 		 2.46x
(2, 2048):	 52.7 	 	 118.2 		 2.24x
(2, 4096):	 50.9 	 	 115.5 		 2.27x
(4, 256):	 52.5 	 	 111.8 		 2.13x
(4, 512):	 51.5 	 	 109.7 		 2.13x
(4, 1024):	 54.1 	 	 109.5 		 2.02x
(4, 2048):	 51.5 	 	 117.3 		 2.28x
(4, 4096):	 51.8 	 	 116.1 		 2.24x
(8, 256):	 51.6 	 	 110.8 		 2.15x
(8, 512):	 56.2 	 	 116.3 		 2.07x
(8, 1024):	 51.5 	 	 118.1 		 2.29x
(8, 2048):	 62.1 	 	 110.9 		 1.79x
(8, 4096):	 78.2 	 	 121.9 		 1.56x
(16, 256):	 67.1 	 	 113.8 		 1.69x
(16, 512):	 73.5 	 	 124.9 		 1.70x
(16, 1024):	 89.2 	 	 122.1 		 1.37x
(16, 2048):	 113.7 	 	 144.8 		 1.27x
(16, 4096):	 144.7 	 	 195.6 		 1.35x
(32, 256):	 123.5 	 	 162.5 		 1.32x
(32, 512):	 135.5 	 	 162.7 		 1.20x
(32, 1024):	 167.0 	 	 165.0 		 0.99x
(32, 2048):	 216.5 	 	 167.2 		 0.77x
(32, 4096):	 278.4 	 	 177.3 		 0.64x
(64, 256):	 234.9 	 	 310.4 		 1.32x
(64, 512):	 259.1 	 	 326.3 		 1.26x
(64, 1024):	 322.7 	 	 349.2 		 1.08x
(64, 2048):	 429.7 	 	 399.6 		 0.93x
(64, 4096):	 562.4 	 	 501.4 		 0.89x
(128, 256):	 460.8 	 	 698.0 		 1.51x
(128, 512):	 517.2 	 	 736.5 		 1.42x
(128, 1024):	 673.2 	 	 813.7 		 1.21x
(128, 2048):	 911.8 	 	 963.3 		 1.06x
(128, 4096):	 1262.6 	 1268.6 	 1.00x
```

## TODO
 - [ ] Support batch of matrices
 - [ ] Add tests
 - [ ] Implement cpu version (?)

Anything else?

### CODE REVIEW

**Comment by vadimkantorov** [comment]
should it be promoted directly to torch.linalg namespace?

**Comment by vadimkantorov** [comment]
maybe could be integrated into `qr` under some `algo`/`method` option?

**Comment by Lezcano** [comment]
How stable is the implemented algorithm? Wouldn't it be better to submit a PR of this sort to one of the backends, say, magma. Their experts on linear algebra could be better suited to review the numerical characteristics of the implementation.

**Comment by younik** [comment]
> How stable is the implemented algorithm? Wouldn't it be better to submit a PR of this sort to one of the backends, say, magma. Their experts on linear algebra could be better suited to review the numerical characteristics of the implementation.

Thanks for pointing this out; I pushed an updated version that bounds the minimum norm of the reflection vector during normalization. In this way, the `epsilon` argument is not needed anymore. I tried comparing my kernel and `torch.linalg.qr` with matrices with zero determinant and the results are the same and stable (e.g. with a zero matrix the output is the identity matrix).

Since this operation is specifically for PowerSGD, I don't think it is interesting for magma or other backends.

**Comment by vadimkantorov** [comment]
> maybe could be integrated into `qr` under some `algo`/`method` option?

Also, a temporary solution could be to still replicate qr interface even if it lives in another namespace for time being

**Comment by nikitaved** [comment]
@younik , if you just interested in computing an orthonormal basis for your vector subspace, check out https://pytorch.org/docs/stable/generated/torch.linalg.householder_product.html?highlight=householder#torch.linalg.householder_product.

**Comment by vadimkantorov** [comment]
also, somehow householder_product docs do not mention the input matrix A in the explanation of its function (maybe there's quirk on V and A)

**Comment by nikitaved** [comment]
@vadimkantorov , have a loot at the note and connection to `torch.geqrf`.

**Comment by nikitaved** [comment]
@younik , how crucial is differentiation for you? `torch.linalg.qr` is only differentiable for full-rank tall matrices afair.

**Comment by younik** [comment]
> @younik , how crucial is differentiation for you? `torch.linalg.qr` is only differentiable for full-rank tall matrices afair, while `householder_product` is always differentiable if the input comes from `torch.geqrf`.

For PowerSGD differentiation of the orthogonalization is not needed

**Pull request closed without merging**
