### PR TITLE
Make inductor scheduler graph extension configurable

### PR DESCRIPTION
**Pull request by AlexDenisov**
This patch makes the inductor scheduler graph extension configurable.
It enables ease of debugging by changing the graph format (dot, png, etc.).

Particularly, it's very convenient to work with the graph interactively using tools like https://github.com/tintinweb/vscode-interactive-graphviz

### CODE REVIEW

**Comment by colesbury** [comment]
@Chillee - would you please review this PR?

**Review by Chillee — CHANGES_REQUESTED** [review]
Please put a config option in `torch._functorch.config` and name it something like `TORCH_COMPILE_GRAPH_FORMAT`. This isn't only used for Inductor scheduler graphs.

**Comment by AlexDenisov** [comment]
> Please put a config option in `torch._functorch.config` and name it something like `TORCH_COMPILE_GRAPH_FORMAT`. This isn't only used for Inductor scheduler graphs.

Done, thank you for the suggestion, @Chillee.

Please, let me know if I should update the docs elsewhere (some places still refer to svg, but it's a default value, so perhaps it's fine as is?).

**Comment by AlexDenisov** [comment]
@Chillee gentle ping 😃

**Review by Chillee — APPROVED** [review]
Thanks!

**Pull request closed without merging**
