### PR TITLE
Reland: Value range refinement using multi-variate expressions

### PR DESCRIPTION
**Pull request by ysiraichi**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #105491

Trying to re-land: #97964.

Test strategy:

```
buck2 test '@fbcode//mode/dev-nosan' fbcode//pye/model_inventory/inside_out_tracking_model:inside_out_tracking_model_test -- --exact 'pye/model_inventory/inside_out_tracking_model:inside_out_tracking_model_test - test_executorch_e2e_output_consistency_aten (pye.model_inventory.inside_out_tracking_model.InsideOutTrackingModelTest.InsideOutTrackingModelTest)'
```

### CODE REVIEW

**Comment by ysiraichi** [comment]
@ezyang could you try running the failing internal tests on this branch? It's a rebased version of #97964

**Comment by ezyang** [comment]
This passed!

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
