### PR TITLE
Do not use `<filesystem>` on Linux

### PR DESCRIPTION
**Pull request by malfet**
Because right now it leads to symbol conflict from binary builds. 
Use of `std::filesystem::file_exists` was introduced by https://github.com/pytorch/pytorch/pull/126601 and in this PR it is replaced with a very straightforward implementation that calls `stat` on the given path, which is a classic C-way of checking for the file existence.

This PR should be reverted once one figures out how to keep `std::filesystem` methods linked into the binary private

Fixes symptoms of https://github.com/pytorch/pytorch/issues/133437

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

### CODE REVIEW

**Review by atalman — APPROVED** [review]
lgtm

**Review by d4l3k — APPROVED** [review]
LGTM

**Comment by malfet** [comment]
There is one more use case, in aoti_runner...

**Comment by malfet** [comment]
@atalman thank you for the merge, but I've tried downloading other builds and still seeing some symbols there....

**Comment by atalman** [comment]
@malfet confirmed - it works with cuda binary as well. ``torch-2.5.0.dev20240827+cu121-cp311-cp311-linux_x86_64.whl``

**Pull request closed without merging**
