### PR TITLE
Fix typo on Contribution Guide

### LINKED ISSUE #119427: Typo (or joke?) in the Contribution Guide
### 📚 The doc issue

There is a typo on the [Contribution Guide](https://pytorch.org/docs/stable/community/contribution_guide.html), in the Frequently Asked Questions.

It says:

> CI tests failed, what does it mean? Maybe your PR is based off a broken main bracnh?

Is that mean to be a joke (broken branch), or an actual typo?

If it is meant to be a joke, please ignore this issue.

### Suggest a potential alternative/fix

I will be submitting a PR with the fix for the typo.

### PR DESCRIPTION
**Pull request by mdevino**
Fixes #119427

### CODE REVIEW

**Review by awgu — APPROVED** [review]
Thanks! This looks like a legit typo.

**Comment by mdevino** [comment]
Hi @awgu,

thanks for reviewing my PR. Was python_frontend the right label to add?
I chose this one based on a similar contribution I've made (#119214).

**Review by kit1980 — APPROVED** [review]

**Pull request closed without merging**
