### PR TITLE
[BE][Easy] Fix `PYI001`: unprefixed-type-param in `torch/utils/data/datapipes`

### PR DESCRIPTION
**Pull request by XuehaiPan**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #129887
* #129884
* #129873
* #129886
* #129872
* #129420
* #129870
* __->__ #129885

cc @ezyang @gchanan @malfet @xuzhao9 @gramster

### CODE REVIEW

**Review by ezyang — APPROVED** [review]

**Comment by kit1980** [comment]
This was reverted internally for breaking stateful dataloader, but that was already fixed in https://github.com/pytorch/data/pull/1282

I will look on Friday how to proceed best, I'd prefer not reverting this PR and re-land it internally.

cc @gokulavasan

**Comment by kit1980** [comment]
Internal breakages are being fixed internally.
But strictly speaking removal of `T_co` is backward compatibility breaking, should be marked as such, and we need to be careful with such changes.

**Pull request closed without merging**
