### PR TITLE
re-enable jacrev/jacfwd/hessian after #128028 landed

### PR DESCRIPTION
**Pull request by guilhermeleobas**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #128622

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
Failure doesn't seem to be related

**Review by zou3519 — APPROVED** [review]

**Pull request closed without merging**
