### PR TITLE
[export] don't set complex replacements on hybrid symints

### PR DESCRIPTION
**Pull request by pianpwk**
Currently, Hybrid SymInts can lead to symbols being replaced with nonlinear expressions of other symbols. For example, the following reshape + add emits a guard `s0*s1 == s2`, which replaces `s2` with `s0*s1`:
```
def forward(self, x, y):
    # x: [s0, s1]; y: [s2]
    return x.flatten() + y
```
The exported program then looks like this, with `s0*s1` containing its own ValueRange:
```
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, w: "f32[s0, s1]", x: "f32[s0*s1]"):
            view: "f32[s0*s1]" = torch.ops.aten.view.default(w, [-1]);  w = None
            add: "f32[s0*s1]" = torch.ops.aten.add.Tensor(view, x);  view = x = None
            return (add,)

Range constraints: {s0: VR[0, int_oo], s1: VR[0, int_oo], s0*s1: VR[0, int_oo]}
```

We can't really do anything useful with this expression, so it's better to just keep the symbol as `s2`, and generate a runtime assert checking `s0*s1 = s2` in the graph. This PR does that, and extends a test case where this assert now shows up.

### CODE REVIEW

**Comment by ezyang** [comment]
I'm not sure what the problem this PR is trying to solve is. In particular, in eager mode graph would have exactly these sizes on the input, no problem. Is the problem specifically that export lets people specify value ranges on arbitrary inputs, and so if an input is actually inferred to be dependent on other sizes, the value range on that input can't be respected? But why don't you just tell the user that and make them set VRs on the values that it's derived from?

**Comment by avikchaudhuri** [comment]
@pianpwk I'd prefer not to muck around with replacements, but instead do adjustments late in the export process. E.g., would it not be possible to do these checks on inputs when the exported module is called, by using our unification logic? So unify s0, s1 to concrete values and check that the one marked s0*s1 indeed is so for concrete values?

**Comment by pianpwk** [comment]
> I'm not sure what the problem this PR is trying to solve is. In particular, in eager mode graph would have exactly these sizes on the input, no problem. Is the problem specifically that export lets people specify value ranges on arbitrary inputs, and so if an input is actually inferred to be dependent on other sizes, the value range on that input can't be respected? But why don't you just tell the user that and make them set VRs on the values that it's derived from?

Ahh, I think the problem is more of a completeness issue for runtime asserts. If the placeholder shapes look like `w: "f32[s0, s1]", x: "f32[s0*s1]"`, then we have an assert `s0*s1 = s2` lying around in the ShapeEnv that we can't reify, so the program just fails at the offending op if input shapes are wrong.


> @pianpwk I'd prefer not to muck around with replacements, but instead do adjustments late in the export process. E.g., would it not be possible to do these checks on inputs when the exported module is called, by using our unification logic? So unify s0, s1 to concrete values and check that the one marked s0*s1 indeed is so for concrete values?

We could definitely do that, but I feel that's basically the same process as what runtime asserts go through (track symbol values from placeholders, compute & check the expression). Runtime asserts in the graph I feel also survive lowering better than if we build this in as a forward hook for the ExportedProgram.


I guess this PR is kind of a decision on whether or not to add runtime asserts into the graph, for these "true or fail" guards that Hybrid SymInts help generate. If we add them they fail at the assert, if not they'll just fail at the op.

**Comment by ezyang** [comment]
> Ahh, I think the problem is more of a completeness issue for runtime asserts. If the placeholder shapes look like w: "f32[s0, s1]", x: "f32[s0*s1]", then we have an assert s0*s1 = s2 lying around in the ShapeEnv that we can't reify, so the program just fails at the offending op if input shapes are wrong.

So, we have an analogous problem when we do guard generation, but we don't have this problem because we always reify guards that say that x.size(0) equals whatever symbolic expression was assigned to it. If this is the only situation you're worried about, this is how I suggest you do the reification.

I absolutely support adding these runtime asserts to the graph, I just think you should make sure to replicate the guard codegen process for them.

**Pull request closed without merging**
