### PR TITLE
Use round-to-negative division when computing output sizes for convolutions involving striding and dilation.

### PR DESCRIPTION
**Pull request by resistor**
#9592

### CODE REVIEW

**Comment by SsnL** [comment]
Thanks! This is great! Do you want to fix the `im2col`, `col2im`, `vol2col` and `col2vol` ones as well? e.g., https://github.com/pytorch/pytorch/blob/master/aten/src/THNN/generic/Im2Col.c#L30-L31

**Comment by fmassa** [comment]
I think we also want to apply a similar patch to `THCUNN`, and also handle it somewhere in CUDNN, as the error message is not great there.
```python
In [1]: import torch

In [2]: conv = torch.nn.Conv2d(1, 1, kernel_size=3, dilation=2, stride=2).cuda()

In [3]: tensor = torch.empty(1, 1, 4, 4).cuda()

In [4]: conv(tensor).shape
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-c6df65b7b5a7> in <module>()
----> 1 conv(tensor).shape

~/github/pytorch/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/github/pytorch/torch/nn/modules/conv.py in forward(self, input)
    299     def forward(self, input):
    300         return F.conv2d(input, self.weight, self.bias, self.stride,
--> 301                         self.padding, self.dilation, self.groups)
    302
    303

RuntimeError: CuDNN error: CUDNN_STATUS_BAD_PARAM

In [5]: torch.backends.cudnn.enabled = False

In [6]: conv(tensor).shape
Out[6]: torch.Size([1, 1, 1, 1])
```

**Comment by resistor** [comment]
@SsnL col2vol and vol2col don't have shape checks at all currently, but I can make the change to im2col and col2im.

**Comment by soumith** [comment]
@resistor pytorchbot retest this please

**Comment by SsnL** [comment]
Awesome. Could you add a test in `test_nn` for this?

**Comment by fmassa** [comment]
Are making the same changes for THCUNN as well? The same bevahior happen in cuda tensors

**Comment by resistor** [comment]
@fmassa I would prefer to address those in a separate change, as I am not currently setup to test CUDA.

**Comment by fmassa** [comment]
@resistor sounds good to me, but I think it is also very important to have consistent behavior between CPU and CUDA.

**Comment by resistor** [comment]
@fmassa CUDA changes incorporated.

**Comment by pjh5** [comment]
Retrying failing test https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-cuda9.0-cudnn7-aten-ubuntu16.04-trigger-test/7301/

**Review by ssnl — APPROVED** [review]
Looks great!

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
