### PR TITLE
[TEST ONLY] [DON'T REVIEW] Use docker image for Windows CI

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by peterjc123** [comment]
Looks like we may use Windows Container to speed up CI build. But I have no idea how to cache the docker image. Any thoughts, @ezyang?

**Comment by ezyang** [comment]
cc @malfet

**Comment by ezyang** [comment]
@peterjc123 can we push it to ECR? If so, we could add its build process alongside our normal Docker build process for LInux

**Comment by peterjc123** [comment]
> @peterjc123 can we push it to ECR? If so, we could add its build process alongside our normal Docker build process for LInux

Let me try.

**Comment by peterjc123** [comment]
Looks like it is taking up too much space on disk.

**Comment by ezyang** [comment]
@peterjc123 maybe file a bug to circleci and see if they have any advice.

**Comment by peterjc123** [comment]
> @peterjc123 maybe file a bug to circleci and see if they have any advice.

How to do that?

**Comment by ezyang** [comment]
https://support.circleci.com/hc/en-us

**Comment by ezyang** [comment]
we pay them money so if you put pytorch repo you should get a response

**Pull request closed without merging**
