### PR TITLE
Properly import Parameter and DataParallel in torch/nn/__init__.py

### LINKED ISSUE #80433: Fix the import of `Parameter` in `torch.nn.__init__.py`
### 🐛 Describe the bug

The "bug" with `nn.Parameter` (same for `UninitializedParameter`, `UninitializedBuffer`, `DataParallel`) is not in the sense of correctness, but in how the public access to this item is defined.

- namely, it leads to issues like this: https://github.com/microsoft/pylance-release/issues/2953
- the explanation: https://github.com/microsoft/pylance-release/issues/2953#issuecomment-1168408943

The explanation above mentions one possible fix:

```python
from .parameter import Parameter as Parameter
```

I confirm that it works. In addition to that, what also works is creating the `__all__` variable and adding there:
- `torch.nn.modules.__all__`
- imported items that are supposed to be public (such as `Parameter`).

P.S. To bring some analogy, let's consider this example:

```python
# my_module.py
import math

def my_sqrt(x):
    return math.sqrt(x)
```

`math` can be accessed as `my_module.math`, but the "true" value of the module is only the `my_sqrt` function. Seems like VSCode performs its analysis in a similar way.

### Versions

- macOS: 11.6
- VSCode: 1.68.1
- Pylance: v2022.6.20
- torch: 1.7.1 (in fact, the issue is there for all recent versions)

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

### PR DESCRIPTION
**Pull request by Yura52**
Fixes #80433

### CODE REVIEW

**Comment by jbschlosser** [comment]
Hey @Yura52, do you mind signing the CLA? Once that happens, we can get this merged :)

**Review by jbschlosser — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by Yura52** [comment]
> Hey @Yura52, do you mind signing the CLA? Once that happens, we can get this merged :)

Hey @jbschlosser  I have just signed it :)

**Pull request closed without merging**
