### PR TITLE
removed unused code

### PR DESCRIPTION
**Pull request by geraldRobin**

### CODE REVIEW

**Review by soumith — CHANGES_REQUESTED** [review]
the submodule deletion of thirdparty/googletest needs to be reverted

**Comment by geraldRobin** [comment]
soumith: the incorrect deletion of the folder is now reverted

**Review by soumith — APPROVED** [review]

**Comment by gchanan** [comment]
The build looks broken -- most likely some code is still trying to call the old cat or the old catArray.

**Review by gchanan — APPROVED** [review]

**Comment by ezyang** [comment]
What happened to this diff?

**Pull request closed without merging**
