### PR TITLE
[inductor] run all kernel benchmarks individually in a compiled module

### PR DESCRIPTION
**Pull request by shunting314**
This is a follow up for PR #95506 to run all the triton kernels in a compiled module individually as suggested by Horace.

Here are the steps:
1. Run the model as usual with a benchmark script and with TORCHINDUCTOR_BENCHMARK_KERNEL enabled. e.g.
```
TORCHINDUCTOR_BENCHMARK_KERNEL=1 python benchmarks/dynamo/torchbench.py --backend inductor --amp --performance --dashboard --only resnet18 --disable-cudagraphs --training
```
2. From the output we will see 3 lines like
```
Compiled module path: /tmp/torchinductor_shunting/rs/crsuc6zrt3y6lktz33jjqgpkuahya56xj6sentyiz7iv4pjud43j.py
```
That's because we have one graph module for fwd/bwd/optitimizer respectively. Each graph module will have one such output corresponding to the compiled module.

3. We can run the compiled module directly. Without any extra arguments, we just maintain the previous behavior to run the call function -- which just does what the original graph module does but in a more efficient way. But if we add the '-k' argument, we will run benchmark for each individual kernels in the file.

```
python /tmp/torchinductor_shunting/rs/crsuc6zrt3y6lktz33jjqgpkuahya56xj6sentyiz7iv4pjud43j.py -k
```

Example output:
Screenshot 2023-03-01 at 4 51 06 PM

Note: I use the first 10 characters of the hash to identify each kernel since
1. hash is easier to get in the code :)
2. name like `triton__3` only makes sense within a compiled module, but a hash can make sense even without specifying the compiled module (assuming we have enough bytes for the hash)

If we found a triton kernel with hash like c226iuf2wi having poor performance, we can look it up in the original compiled module file. It works since we comment each compiled triton kernel with the full hash.

cc @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

### CODE REVIEW

**Comment by Chillee** [comment]
How would you use this to collect all the kernels from say, torchbench?

**Comment by shunting314** [comment]
> How would you use this to collect all the kernels from say, torchbench?

Good question. I would do something like this:
```
for mod in $(TORCHINDUCTOR_BENCHMARK_KERNEL=1 run_all_models_in_torchbench 2>&1 | grep 'Compiled module path' | awk -F ':' '{print $2}'); do
  python mod
done
```
This will print all the kernels and its perf (latency, bandwidth).

Given a kernel printed, we can grep the printed hash in the cache dir to find it's corresponding module. But there is no way to figure out the benchmark name so far. I think it's not hard to add the benchmark name before the kernel hash in the output though.  I can add that if it's helpful.

**Comment by Chillee** [comment]
I think the point is that we want to be able to benchmark all the kernels without running through torchbench again. Usually torchbench seems to take upwards of an hour to run completely, and that's a pretty slow iteration speed.

**Comment by shunting314** [comment]
> I think the point is that we want to be able to benchmark all the kernels without running through torchbench again. Usually torchbench seems to take upwards of an hour to run completely, and that's a pretty slow iteration speed.

I see. We can do something like
```
TORCHINDUCTOR_BENCHMARK_KERNEL=1 run_all_models_in_torchbench 2>&1 | grep 'Compiled module path' | awk -F ':' '{print $2}' > torch_bench_mod_list
```
to store the compiled module list somewhere. And then run:
```
for mod in `cat torch_bench_mod_list`; do
  python mod
done
```

(basically split the previous command I commented)

As long as we know the generated code is not changed (or we don't care as long as it's not significantly changed), we can keep *reusing* the cached module list.

**Comment by Chillee** [comment]
@shunting314 Would be good to verify that works, at least for a couple models :)

**Comment by shunting314** [comment]
Here are the steps to benchmark triton kernels for *multiple* models:
1. run the model with inductor backend and with TORCHINDUCTOR_BENCHMARK_KERNEL enabled. (*We can do this once and reuse its output multiple times*)
```
TORCHINDUCTOR_BENCHMARK_KERNEL=1 python benchmarks/dynamo/torchbench.py --backend inductor --amp --performance --dashboard --disable-cudagraphs --training 2>&1 | tee /tmp/inductor.log
```

2. Do some simple text processing to grab compiled module list from inductor log:
```
cat /tmp/inductor.log  | grep 'Compiled module path:' | awk -F ':' '{print $2}' | tee /tmp/torchbench_mod_list
```
3. benchmark triton kernels in all the compiled modules collected:

```
for mod in `cat /tmp/torchbench_mod_list`; do python $mod -k; done
```

Outputs like:
Screenshot 2023-03-02 at 12 05 48 PM

**Review by Chillee — APPROVED** [review]

**Pull request closed without merging**
