### PR TITLE
Fix memory usage increase reported in #38568

### PR DESCRIPTION
**Pull request by jjsjann123**
update to in-place version for bias add in convolution, this saves unnecessary memory allocation.

### CODE REVIEW

**Comment by jjsjann123** [comment]
cc'ing @ptrblck

**Review by zasdfgbnm — APPROVED** [review]

**Review by ngimel — APPROVED** [review]

**Comment by SsnL** [comment]
should this be in 1.5.1?

**Comment by ngimel** [comment]
@ssnl good idea, I'll put a milestone.

**Comment by ShawnZhong** [comment]
A quick search with `(?<var>\b\S+) = \k<var>\b \+` shows me several matches of the this pattern. Does it worth to update other occurrences with the in-place version?

**Comment by SsnL** [comment]
@ShawnZhong only if the variable is an intermediate result

**Pull request closed without merging**
