### PR TITLE
[Draft] FX-to-ONNX exporter prorotype and some tests

### PR DESCRIPTION
**Pull request by wschin**
As FX graph becomes the de facto IR in all new PyTorch compiler features, we want to make sure FX and ONNX can work well together. This PR is an experimental attemp to export GraphModule into ONNX. To reuse existing exporters in `symbolic_opset*.py` files, this prototype still heavily depends on TorchScript. I do want to remove TorchScript dependency, as long as people get time to re-write all exporters.

### CODE REVIEW

**Comment by SherlockNoMad** [comment]
You want to use FX graph with ATen IR 
https://gist.github.com/SherlockNoMad/dabc5694567bff3d2eb6f559c21f537e

**Comment by wschin** [comment]
> You want to use FX graph with ATen IR https://gist.github.com/SherlockNoMad/dabc5694567bff3d2eb6f559c21f537e

Indeed, `aten_graph=True`. lol.
```python
def _export_module(module: torch.nn.Module, *args, use_binary_format: bool = True):
    # args will be converted to symbolic tensor.
    args = copy.deepcopy(args)
    # Convert nn.Module to FX graph
    # TODO(wechi): There are several symbolic tracing mechanisms to convert
    # nn.Module to FX graph. We should choose the right one after they are
    # matured.
    graph_module, graph_guard = torch._dynamo.export(module, *args, aten_graph=True)
    # Export FX graph to ONNX ModelProto.
    return _export(
        graph_module,
        *args,
        decomposition_table=_onnx_friendly_decomposition_table,
        use_binary_format=use_binary_format,
    )
```

**Comment by thiagocrepaldi** [comment]
Is this meant to be merged or just discussed?

**Review by thiagocrepaldi — COMMENTED** [review]
Is this meant to be merged or just discussed?

If merge is the intention, I would create an experimental folder and add more intuitive names so that several pocs could live there and easily identifiable. `_fx.py` is very vague as probably all pocs will use FX IR

**Comment by wschin** [comment]
> Is this meant to be merged or just discussed?
> 
> If merge is the intention, I would create an experimental folder and add more intuitive names so that several pocs could live there and easily identifiable. `_fx.py` is very vague as probably all pocs will use FX IR

I'd like to use this for discussion and better development transprancy first. It could gradually become a formal PR after hacks are removed. I agree a lot of naming and doc can be improved; changes are on the way!

**Pull request closed without merging**
