### PR TITLE
ns for fx: fix issue with shadowing nodes of unknown dtype

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #75511 ns for fx: reenable tests disabled by #62608
* #75472 ns for fx: fix bug to enable again on torchvision models
* **#75471 ns for fx: fix issue with shadowing nodes of unknown dtype**

Summary:

In https://github.com/pytorch/pytorch/pull/61687, a couple of FX Numeric Suite
tests were disabled.

This PR reenables one of these tests. We update the dtype inference logic
of NS to always return a specific type instead of sometimes returning
"fp32 or int8". When the type cannot be deduced by the current logic,
we do not shadow the node.

As a better version of dtype inference becomes available in FX Graph Mode Quantization,
we could migrate this code to use it.

Future PRs in the stack will unbreak other things to enable NS for FX to
work on torchvision again.

Test plan:

```
python test/test_quantization.py -k NumericSuite
```

Differential Revision: [D35484707](https://our.internmc.facebook.com/intern/diff/D35484707)

### CODE REVIEW

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35484707).

**Comment by jerryzh168** [comment]
could you also briefly explain why the previous test was broken and how does the PR fixes it?

**Review by jerryzh168 — APPROVED** [review]

**Comment by vkuzo** [comment]
before this PR, the "fp32 or int8" dtype cast was set as "Identity".  This only worked sometimes, and the broken test was a case when this failed.  The breakage was related to trying to pass an int8 tensor through an observer.

**Comment by vkuzo** [comment]
@vkuzo has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35484707).

**Pull request closed without merging**
