### PR TITLE
Fix strict default value in StateDictOptions

### LINKED ISSUE #125992: StateDictOptions claims default `strict` is False, but it's actually True
### 📚 The doc issue

https://pytorch.org/docs/stable/distributed.checkpoint.html#torch.distributed.checkpoint.state_dict.StateDictOptions

`The default value is False.`

`strict: bool = True`

### Suggest a potential alternative/fix

I don't know which one is better. @fegin can pick.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @LucasLLC

### PR DESCRIPTION
**Pull request by shink**
Fixes #125992

The default value of the parameter `strict` should be `True`.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @LucasLLC

### CODE REVIEW

**Comment by ad8e** [comment]
If the default value should be True, the doc line might as well be removed, since the function interface already says it's True.

**Comment by shink** [comment]
@ad8e Thanks for your review. The doc line has been removed as you said.

**Review by fegin — APPROVED** [review]
Thanks for the fix.

**Pull request closed without merging**
