### PR TITLE
Perform value range analysis with rationals when possible

### PR DESCRIPTION
**Pull request by lezcano**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #105139
* #105138
* __->__ #105137

This is particularly useful for guards to avoid rounding errors, as most
guards (all?) are rational functions.

Fixes https://github.com/pytorch/pytorch/issues/105097

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8

### CODE REVIEW

**Comment by ezyang** [comment]
I'm pushing a commit to expunge the is_constant calls

**Review by ezyang — APPROVED** [review]

**Comment by lehung-dez** [comment]
good

**Pull request closed without merging**
