### PR TITLE
[DTensor] Fix DeviceMesh.__repr__ to output valid Python syntax

### PR DESCRIPTION
**Pull request by joshlk**
Fix `DeviceMesh.__repr__` to output valid Python syntax

cc: @wanchaol

### CODE REVIEW

**Review by wanchaol — APPROVED** [review]

**Comment by wanchaol** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/29311126/65600975/112401/#/?version=2)
> 
> * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/29311126/65600975/112401/#/?version=2) - login: @joshlk / name: Josh Levy-Kramer . The commit ([a1ba4fd](https://github.com/pytorch/pytorch/commit/a1ba4fd02e6a884baf2a48ea7cb7f184c3701ab9)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/29311126/65600975/112401/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

@joshlk you would need to sign the cla mentioned here to land I think

**Review by fduwjj — APPROVED** [review]
Actually just to confirm, the reason to change the string representation returned by __repr__ is make it adheres to the convention of being able to recreate the object when passed to the eval() function, if possible, right?

If so, might be worth adding a unit test.

**Comment by joshlk** [comment]
> Actually just to confirm, the reason to change the string representation returned by repr is make it adheres to the convention of being able to recreate the object when passed to the eval() function, if possible, right?

Yes, kind of. The convention is that it is usually Python syntax and should look like something that would recreate the object. This is only sometimes possible though and sometimes it is just an indication.

I think adding a unit test would be overkill. But I am happy to do that if you would like

**Comment by fduwjj** [comment]
@joshlk no strong opinion here, will leave the decision to you.

**Comment by fduwjj** [comment]
Just FYI, @joshlk anyone can do @pytorchbot merge once the PR gets approved.

**Pull request closed without merging**
