### PR TITLE
[inductor] Enable coordinate descent tuning with max-autotune

### PR DESCRIPTION
**Pull request by jansel**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #136867

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang

### CODE REVIEW

**Review by Chillee — APPROVED** [review]
I'm for it :P

I'd worry about folks complaining about compile-time regressions internally though - I'm sure you're aware.

**Review by eellison — COMMENTED** [review]
Would this be a good opportunity to add opt_level as a kwarg ? We just had reports internally for a model that doubled compilation time with coordinate descent tuning.

I think we could also roll this out by default in max-autotune by only targeting the relatively more expensive kernels.

**Comment by jansel** [comment]
In my testing the added compile time was small compared to matmuls.  I think we should embrace the "max" in "max-autotune".

**Pull request closed without merging**
