### PR TITLE
Fix onnx.symbolic.upsample_bilinear2d not considering align_corners

### LINKED ISSUE #6900: Pytorch - ONNX graph creation error (in SummaryWriter add_graph) when using Upsampling bilinear mode
- PyTorch
- OS: Ubuntu 14.04
- PyTorch version: (0.4) nightly build 2018.04.18 from conda
- CUDA/cuDNN version: CUDA 8, CUDNN 7
- GPU models and configuration: GTX 1080 Ti
- Versions of any other relevant libraries: tensorboardx 1.0

@SsnL, @soumith while we are discussing Upsampling, I would like to describe the following error that I get when I try to write an ONNX graph using SummaryWriter's add_graph() function. 'nearest' Upsampling has no issue, but 'bilinear' Upsampling causes this issue.

/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/nn/functional.py:1762: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
"See the documentation of nn.Upsample for details.".format(mode))
=> Train Epoch [1/300]: 2%|\u258f | 1/62 [00:20<20:41, 20.36s/it, DataTime=7.515 (Avg:7.515), LR=0.001, Loss=11.365 (Avg:11.365), Output=0.014 (Avg:0.014)(mIoU)]/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/utils.py:365: UserWarning: ONNX export failed on ATen operator hardtanh because torch.onnx.symbolic.hardtanh does not exist
.format(op_name, op_name))
Traceback (most recent call last):
File "train_segmentation.py", line 93, in 
main_segmentation.main(cmd)
File "../modules/tools/main_segmentation.py", line 192, in main
train_loss, train_metric, metric_name = train(args, train_dataset, train_loader, model, optimizer, epoch, train_writer, scheduler.get_lr()[0])
File "../modules/tools/main_segmentation.py", line 295, in train
train_writer.add_graph(model, input_zero)
File "/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/tensorboardX/writer.py", line 400, in add_graph
self.file_writer.add_graph(graph(model, input_to_model, verbose))
File "/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/tensorboardX/graph.py", line 48, in graph
torch.onnx._optimize_trace(trace, False)
File "/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/init.py", line 30, in _optimize_trace
trace.set_graph(utils._optimize_graph(trace.graph(), aten))
File "/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/utils.py", line 95, in _optimize_graph
graph = torch._C._jit_pass_onnx(graph, aten)
File "/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/init.py", line 40, in _run_symbolic_function
return utils._run_symbolic_function(*args, **kwargs)
File "/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/utils.py", line 368, in _run_symbolic_function
return fn(g, *inputs, **attrs)
TypeError: upsample_bilinear2d() got an unexpected keyword argument 'align_corners' (occurred when translating upsample_bilinear2d)

### PR DESCRIPTION
**Pull request by ssnl**
Fixes https://github.com/pytorch/pytorch/issues/6900.

### CODE REVIEW

**Review by houseroad — APPROVED** [review]
LGTM

**Comment by SsnL** [comment]
macos CI's `collect_env` test got an interesting mismatch:
```
23:15:05   Versions of relevant libraries:
23:15:05   [pip] numpy (1.14.X)
23:15:05 - [pip] torch (0.5.0a0
23:15:05 + [pip] torch (0.5.0a0)
```

What should I do here? @zou3519

**Comment by zou3519** [comment]
That's bizarre. Taking a look.

**Comment by SsnL** [comment]
No rush. This can wait @zou3519

**Comment by zou3519** [comment]
Looks like the rebase got rid of it. I'm not quite sure what was wrong, will keep an eye out

**Review by ezyang — APPROVED** [review]

**Pull request merged**
