### PR TITLE
Tighten type hints for tensor arithmetic

### LINKED ISSUE #124015: Typinghints on tensor arithmetic operations (other:Any) cause incompatibilities
### 🐛 Describe the bug

The typehints on some Tensor-functions are wider than the respective functions are, this causes issues for us:

Take for for example,` Tensor.__mul__(self, other:Any) -> Tensor`:
This tells mypy that for all types of other, the multiplication will always be a Tensor.
But if the multiplication fails, python will try `other._rmul__`.

For example:
```python
import torch
class not_a_tensor:
   def __rmul__(self, other:Tensor) -> Self:

a=torch.tensor(1)
b=not_a_tensor()
c=a*b
```

This results at runtime in c being a `not_a_tensor`, but the typehints tell mypy that it should be a tensor.

Can we tighten  the hints for these operations to the actually supported types?

### Versions

mypy 1.9.0
torch 2.2.1

cc @ezyang @malfet @xuzhao9 @gramster

### PR DESCRIPTION
**Pull request by fzimmermann89**
Fixes #124015

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov

### CODE REVIEW

**Comment by Skylion007** [comment]
@fzimmermann89 Looks like these narrow type hints broke a bunch of tests.

**Comment by fzimmermann89** [comment]
I will take a look tomorrow l. It seems some of the mypy errors should be fixed at the call site..

**Comment by fzimmermann89** [comment]
is there a way for non-meta employees to run the github workflows -- or could anybody start them for me?
(local lintrunner only finds issues in unrelated files)

**Comment by ezyang** [comment]
Unfortunately I still have to manually approve them

**Review by ezyang — DISMISSED** [review]
the new hints are probably too restrictive but to figure out the completely precise one probably have to carefully read the python binding code

**Comment by ezyang** [comment]
looks like mypy not happy

**Comment by fzimmermann89** [comment]
Some of the workflows for checks need an extra approval or am I misinterpreting the message?

**Comment by fzimmermann89** [comment]
Yeah... so, I dont really understand the error:
```
Cannot determine type of "__pow__"
2024-11-04T22:30:36.7177297Z 
2024-11-04T22:30:36.7177787Z          2059  |    def __rfloordiv__(self, other: Union[Tensor, Number, _complex]) -> Tensor: ...
2024-11-04T22:30:36.7178793Z          2060  |    def __rmul__(self, other: Union[Tensor, Number, _complex]) -> Tensor: ...
2024-11-04T22:30:36.7179785Z          2061  |    def __ror__(self, other: Union[Tensor, _bool]) -> Tensor: ...
2024-11-04T22:30:36.7180753Z     >>>  2062  |    def __rpow__(self, other: Union[Tensor, Number, _complex]) -> Tensor: ...
2024-11-04T22:30:36.7181487Z          2063  |    @overload
2024-11-04T22:30:36.7182106Z          2064  |    def __rshift__(self, other: Tensor) -> Tensor: ...
2024-11-04T22:30:36.7182689Z          2065  |    @overload

```
and cannot reproduce it locally, neither by using lintrunner nor by trying different python and mypy versions.

if anybody has an idea what is going on and how to fix it...

**Comment by ezyang** [comment]
it suuuuure seems like you define it already though lol

**Comment by ezyang** [comment]
I too cannot reproduce. What about just slapping a `# type: ignore[has-type]` on that line when you codegen?

**Comment by fzimmermann89** [comment]
Now it seems to pass mypy in ci, or am not mistaken?
No idea what is going on there, some bug in mypy or in the ci environment?

The distributed failure is unrelated

**Review by ezyang — DISMISSED** [review]

**Comment by ZainRizvi** [comment]
@pytorchbot revert -c ghfirst -m "Sorry but this is breaking internally. See D65641103 for more details"

@ezyang can you please help get these issues resolved?

Errors look like:
```
Unsupported operand [58]: `*` is not supported for operand types `Optional[float]` and `torch._tensor.Tensor`.
Unsupported operand [58]: `<` is not supported for operand types `torch._tensor.Tensor` and `Optional[int]`.
```

**Comment by fzimmermann89** [comment]
> @pytorchbot revert -c ghfirst -m "Sorry but this is breaking internally. See D65641103 for more details"
> 
> @ezyang can you please help get these issues resolved?
> 
> Errors look like:
> ```
> Unsupported operand [58]: `*` is not supported for operand types `Optional[float]` and `torch._tensor.Tensor`.
> Unsupported operand [58]: `<` is not supported for operand types `torch._tensor.Tensor` and `Optional[int]`.
> ```

This seems to be an issue with the typing in the caller, as None*Tensor is not defined... ?

If you can't fix the internal code, we could add overloads that pretend that arithmetic between Tensor and None was possible. But part of the motivation behind this patch was to make mypy detect exactly this kind of error..

**Comment by ezyang** [comment]
I'm working on the internal fixes

**Review by ezyang — APPROVED** [review]

**Pull request closed without merging**
