### PR TITLE
[ROCm] restore jit tests

### PR DESCRIPTION
**Pull request by jeffdaily**
Remove `skipIfRocm` from most jit tests and enable `RUN_CUDA_HALF` tests for ROCm.

These changes passed more than three rounds of CI testing against the ROCm CI.

CC @ezyang @xw285cornell @sunway513

### CODE REVIEW

**Comment by xw285cornell** [comment]
Nice! Let's wait a bit and see if the check passes.

**Comment by xw285cornell** [comment]
There is merge conflict, @jeffdaily can you rebase to the most recent master?

**Review by auvipy — APPROVED** [review]

**Comment by xw285cornell** [comment]
@jeffdaily  this one has merge conflict so that we're not able to land (test_cpp_extensions_jit.py). Could you rebase to the recent master?

**Comment by jeffdaily** [comment]
Rebased.  Let's see how CI does this time.

**Review by xw285cornell — APPROVED** [review]
OSS all green. There are some weird issues in internal system that prevents this to land. Looking.

**Pull request closed without merging**
