### PR TITLE
Set NDEBUG correctly when building in release mode

### PR DESCRIPTION
**Pull request by yf225**
We should use `CMAKE_BUILD_TYPE` to control whether we pass `-DNDEBUG` to cmake command.

### CODE REVIEW

**Review by orionr — APPROVED** [review]
Does this fix the issue? If so, let's do it.

That being said, I'm surprised this has been a problem for so long - looks like the code is from when I originally merged Caffe2 and ATen libs. It might have somehow been revealed when @zdevito removed the `.sh` and `.bat` scripts or maybe when @peterjc123 supported Windows in https://github.com/pytorch/pytorch/commit/f7733526aa84af9001fe024117cc66221f9df85e ?

In any case, if it fixes things please go for it. Thank you!

**Comment by peterjc123** [comment]
Should we add a test on this? And what will happen if CMake Build Type is unset?

**Comment by yf225** [comment]
@peterjc123 I'll add a test to ATen for this. Also curious would there be cases where `CMAKE_BUILD_TYPE` is not set? And what's the behavior of multiple-build-type generators (such as VS) look like (do they have multiple build types specified in `CMAKE_BUILD_TYPE`)?

**Comment by yf225** [comment]
According to https://en.cppreference.com/w/c/error/assert, `assert()` doesn't work if `NDEBUG` is defined as macro name. We likely want to define `DEBUG` instead of `NDEBUG`, and we shouldn't define `NDEBUG` even if we are in release mode (so that `assert()` will still work in release mode)

**Comment by peterjc123** [comment]
@yf225 If one user do `cmake <torch_dir>` directly, then the cmake build type is unset. And from my experience, the debug configuration will get chosen (when using ninja). As for the multiple-build-type generators, cmake build type is useless during configuration. Although, there will only one selected at build time. (e.g. msbuild /p configuration=Release). The default value of `CMAKE_BUILD_TYPE` of this type of generator is typically `Debug;Release;RelWithDebInfo`, which contains all the configurations that are available for the user to select.

**Pull request closed without merging**
