### PR TITLE
[CI] Disable rocm distributed tests

### PR DESCRIPTION
**Pull request by malfet**
As they has been broken since Dec 16th
See https://github.com/pytorch/pytorch/issues/91630

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

### CODE REVIEW

**Review by atalman — APPROVED** [review]

**Review by albanD — APPROVED** [review]

**Comment by jaglinux** [comment]
Reproduced the issue internally, Reporting the findings here.
We started seeing the hang after the PR https://github.com/pytorch/pytorch/pull/88330
The hang is due to AttributeError: 'torch._C._distributed_c10d.ProcessGroup' object has no attribute '_set_backend' when running the tests under distributed/test_c10d_spawn_gloo.py
When we ignore the attribute errors, the test cases (test_shared_broadcast_gloo, test_shared_allreduce_gloo, test_shared_allgather_gloo, test_shared_allgather_chunk_gloo) passes and the distributed tests runs successfully. 

On Cuda CI jobs. these tests are either skipped or not run. 
Its skipped citing " At least 2 CUDA GPUS needed". 

The skip tests are skipped on "distributed, 1, 2, linux.2xlarge" 
https://ossci-raw-job-status.s3.amazonaws.com/log/10790147515 
Tests not showing up 
https://ossci-raw-job-status.s3.amazonaws.com/log/10790279874 
https://ossci-raw-job-status.s3.amazonaws.com/log/10790288126

**Comment by jaglinux** [comment]
I have a PR https://github.com/pytorch/pytorch/pull/92932 to verify if the distributed tests works fine if we ignore the attribute error '_set_backend not found'

cc @jeffdaily @jithunnair-amd

**Comment by jaglinux** [comment]
CUDA distributed tests are run with Python3.10 and hence the tests are not run.
https://github.com/pytorch/pytorch/issues/51619

ROCm distributed tests are run with Python3.8 and hence the tests failed due to "attribute error"

**Pull request closed without merging**
