### PR TITLE
add CUDA 12.6 to conda docker image

### LINKED ISSUE #138440: Enable CUDA 12.6.2
### 🚀 The feature, motivation and pitch

Filing issue for enabling CUDA 12.6.2 due to an observed performance gap in PyTorch's Eager mode for plain matrix multiplications.
Confirmed that upgrading PyTorch to CTK 12.6.2 with CUBLAS 12.6.3.3 will boost the performance. 

Issue can be used to track related PRs.

cc @ptrblck @msaroufim @syed-ahmed @nWEIdia @atalman @malfet 

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tinglvv**
Adds cuda 12.6 to common installation script.
Adds cuda 12.6 to conda docker image build matrix.

related to #138440

cc @atalman @ptrblck @nWEIdia

### CODE REVIEW

**Review by cyyever — APPROVED** [review]

**Review by nWEIdia — CHANGES_REQUESTED** [review]
We should try removing install_121 in install_cuda.sh

**Comment by tinglvv** [comment]
> We should try removing install_121 in install_cuda.sh

good point, let's do that in a separate deprecation PR.

**Review by atalman — APPROVED** [review]
Thank you very much

**Pull request closed without merging**
