### PR TITLE
`hardsigmoid`: port to structured

### PR DESCRIPTION
**Pull request by Freey0**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #58050 Port silu to structured
* #57623 Port softshrink to structured
* **#57622 Port hardsigmoid to structured**
* #57621 Port leaky_relu to structured
* #57620 Port softplus to structured
* #57619 Port elu to structured

For the vulkan_api_test test, I tried something like the following, but it didn't work. The linker says it can't find the symbol. Possibly related (#56563)

In the aten/src/ATen/test/vulkan_api_test.cpp file
```
#include <ATen/CPUFunctions.h>

TEST(VulkanAPITest, hardsigmoid_) {
  if (!at::is_vulkan_available()) {
    return;
  }

  auto cpu = at::rand({17, 197, 302, 5}, at::device(at::kCPU).dtype(at::kFloat))*12 - 6;
  auto vulkan = cpu.vulkan();

  at::cpu::hardsigmoid_(cpu);        //<----- HERE    //at::native::hardsigmoid_(cpu); 
  at::hardsigmoid_(vulkan);

  const auto check = almostEqual(cpu, vulkan.cpu());
  if (!check) {
    showRtol(cpu, vulkan.cpu());
  }

  ASSERT_TRUE(check);
}
```

```
May 12 12:41:47 CMakeFiles/vulkan_api_test.dir/__/aten/src/ATen/test/vulkan_api_test.cpp.o: In function `(anonymous namespace)::VulkanAPITest_hardsigmoid__Test::TestBody()':
May 12 12:41:47 vulkan_api_test.cpp:(.text+0x138c0): undefined reference to `at::cpu::hardsigmoid_(at::Tensor&)'
May 12 12:41:48 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Differential Revision: [D28224704](https://our.internmc.facebook.com/intern/diff/D28224704)

### CODE REVIEW

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28224704).

**Review by ezyang — APPROVED** [review]

**Comment by ezyang** [comment]
```

May 11 15:41:44 [ 88%] Building CXX object caffe2/CMakeFiles/half_float_ops_test.dir/operators/half_float_ops_test.cc.o
May 11 15:41:44 [1m/var/lib/jenkins/workspace/aten/src/ATen/test/vulkan_api_test.cpp:928:7: [0m[0;1;31merror: [0m[1m'cpu' is not a class, namespace, or enumeration[0m
May 11 15:41:44   at::cpu::hardsigmoid_(cpu);
May 11 15:41:44 [0;1;32m      ^
```

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28224704).

**Comment by Freey0** [comment]
```
ln: failed to create symbolic link 'build/bin/libc10.so': File exists
```
I don't have any thoughts about the test failure. Can you tell me this test failure related? Any advice would be appreciated!

**Comment by ezyang** [comment]
pretty sure this one is not your fault either. @samestep do you know what's up with the new GHA jobs

**Comment by walterddr** [comment]
The way GHA downloads build artifact and unzip them back out the test phase makes it unnecessary to symlink those site-package binary back into the repo pytorch/build/bin folder. 

However I wonder why this wasn't causing any issue until now :-/

**Comment by ezyang** [comment]
@ezyang has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D28224704).

**Pull request closed without merging**
