### PR TITLE
Add __getitem__() to nn.Module

### LINKED ISSUE #16181: [Feature Request] Add `__getitem__()` to `nn.Module`
## 🚀 Feature

Enable to call each layer in nn.Module like python dict.

`self.__getattr__(layer_name)` or `getattr(self, layer_name)`
-> `self[layer_name]`

## How

Add bellow function to `nn.Module` .
- reference: [chainer.Chain](https://github.com/chainer/chainer/blob/v5.1.0/chainer/link.py#L871-L873)

```python
    def __getitem__(self, name):
        """Equivalent to getattr."""
        return getattr(self, name)
```

## Motivation

Access each layer in network easily (Especially for beginners).

#### old

```python
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        ...

    def forward(self, x):
        ...
        # Apply each conv<number>_1, conv<number>_2
        for i in range(10, 11 + 1):
            output_tmp = outputs[-1]
            output_tmp = F.relu(getattr(self, f'conv{i:d}_1')(output_tmp))
            output_tmp = F.relu(getattr(self, f'conv{i:d}_2')(output_tmp))
            outputs.append(output_tmp)
        return outputs
```

#### new

```python
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        ...

    def forward(self, x):
        ...
        # Apply each conv<number>_1, conv<number>_2
        for i in range(10, 11 + 1):
            output_tmp = outputs[-1]
            output_tmp = F.relu(self[f'conv{i:d}_1'](output_tmp))
            output_tmp = F.relu(self[f'conv{i:d}_2'](output_tmp))
            outputs.append(output_tmp)
        return outputs
```

Maybe this is different from the concept of PyTorch?

### PR DESCRIPTION
**Pull request by hikjik**
fixes [#16181](https://github.com/pytorch/pytorch/issues/16181)

### CODE REVIEW

**Comment by SsnL** [comment]
tests are needed

**Review by apaszke — CHANGES_REQUESTED** [review]
Uhhh why? It's not standard Python semantics.

**Comment by apaszke** [comment]
Also, this leads to clashes with the semantics of e.g. `ModuleDict` I think.

**Comment by SsnL** [comment]
@apaszke This is a legit request.  I'm not saying that `__getitem__` is the best way to do this (I think it's not a bad way actually), but something of this form is needed.  Our current API is asymmetrical.  We support things like `add_module('4x4_conv', child)`, but then ask users to use `getattr(self, '4x4_conv')` to get the module.

**Comment by apaszke** [comment]
@SsnL sorry but I can't see the asymmetry. Both are functions that let you perform lookups based on a dynamic string

**Comment by soumith** [comment]
I'd agree with Adam here. nn.Module is a class, and it's not normal or expected to have a `__getitem__` like a dict. If you generally want a dict, you'd stick it in a nn.ModuleDict, if not you're better off simply using `getattr`

**Comment by soumith** [comment]
I really apologize for changing our mind @hikjik , because in the original issue we declared "we dont mind, send a PR"

**Pull request closed without merging**
