### PR TITLE
qat graph mode: make `_forward` of per channel observers scriptable

### PR DESCRIPTION
**Pull request by vkuzo**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #39828 [wip] qat graph mode: add combine_conv_bn pass
* #39837 eager qat: refactor conv-bn to make conv with scaled weights a func
* **#39840 qat graph mode: make `_forward` of per channel observers scriptable**
* #39796 qat graph mode: initial scaffolding for prepare_qat_script

Summary:

These will be needed in a scripted form for testing QAT graph
mode.  Added them to the test case and fixed the resulting errors.

Test Plan:

```
python test/test_quantization.py TestObserver.test_observer_scriptable
```

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D21998752](https://our.internmc.facebook.com/intern/diff/D21998752)

### CODE REVIEW

**Review by jerryzh168 — APPROVED** [review]

**Comment by jerryzh168** [comment]
I think it should be scriptable already, isn't it?

**Comment by vkuzo** [comment]
doesn't seem to be scriptable before this diff, the changes to observer.py in this diff fix it.

**Comment by jerryzh168** [comment]
> doesn't seem to be scriptable before this diff, the changes to observer.py in this diff fix it.

really? we are using it in the test already: https://github.com/pytorch/pytorch/blob/master/test/quantization/test_quantize_script.py#L854

**Comment by vkuzo** [comment]
> > doesn't seem to be scriptable before this diff, the changes to observer.py in this diff fix it.
> 
> really? we are using it in the test already: https://github.com/pytorch/pytorch/blob/master/test/quantization/test_quantize_script.py#L854

sg, i'll check it out when I get back to this PR, thanks for the context

**Comment by vkuzo** [comment]
> > doesn't seem to be scriptable before this diff, the changes to observer.py in this diff fix it.
> 
> really? we are using it in the test already: https://github.com/pytorch/pytorch/blob/master/test/quantization/test_quantize_script.py#L854

checked this on master:
* these observers are already scriptable, as in `torch.jit.script` works on them
* adding them to `test_observer_scriptable` exposes an error with torch.jit.save(scripted, buf) because `_forward` has @torch.jit.ignore
* removing the @torch.jit.ignore in turn exposes the issues fixed by this diff

so, a better title would be "make the `_forward`" method of per channel observers scriptable

**Pull request closed without merging**
