### PR TITLE
[ROCm] Hipify trie re-engineering and adding unit tests

### PR DESCRIPTION
**Pull request by hongxiayang**
Fixes #[117504](https://github.com/pytorch/pytorch/issues/117504)

Re-engineering Hipify Trie:
(1) Re-engineering Trie.
(2) More documentation or comments for easier understanding
(3) Created a set of unit test (class `TestHipifyTrie`) to test the Trie data structure and APIs.

Test:
```
root@xxx:/development/pytorch# pytest test/test_utils.py -k TestHipifyTrie
==================================================================================================== test session starts ====================================================================================================
platform linux -- Python 3.9.18, pytest-7.3.2, pluggy-1.3.0
rootdir: /dockerx/development/pytorch
configfile: pytest.ini
plugins: flakefinder-1.1.0, rerunfailures-13.0, xdist-3.3.1, xdoctest-1.1.0, cpp-2.3.0, shard-0.1.2, hypothesis-5.35.1
collected 11453 items / 11445 deselected / 8 selected                                                                                                                                                                       
Running 8 items in this shard

test/test_utils.py ........                                                                                                                                                                                           [100%]

============================================================================================ 8 passed, 11445 deselected in 3.84s ============================================================================================
root@xxx:/development/pytorch# 
```
Also performed diff on modified and generated contents by this tool with the original code and the new code of the hipify_python.py script. Verified no difference.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo

### CODE REVIEW

**Review by malfet — APPROVED** [review]
LGTM, though I wonder if test should move the test to tools/ folder (as it needs to be run only once rather than thru the entirety of CI)

**Comment by hongxiayang** [comment]
> LGTM, though I wonder if test should move the test to tools/ folder (as it needs to be run only once rather than thru the entirety of CI)

Thank you for your review. I will check to move it next.

**Review by jeffdaily — APPROVED** [review]

**Pull request closed without merging**
