### PR TITLE
[build] Update googletest

### PR DESCRIPTION
**Pull request by rohan-varma**
updates googletest submodule to the latest release, which is 1.10.0. Done by going to `third_party/googletest` and checking out out the commit corresponding to the release, which is seen here: https://github.com/google/googletest/releases.

We want to use this so we can use new features such as `GTEST_SKIP()` to skip tests when writing our unit tests. See https://github.com/pytorch/pytorch/pull/28393 for more context and discussion.

### CODE REVIEW

**Comment by rohan-varma** [comment]
hmm, CI is failing with

```
Oct 22 18:05:02 clang: error: argument unused during compilation: '-pie' [-Werror,-Wunused-command-line-argument]
Oct 22 18:05:02 third_party/googletest/googletest/CMakeFiles/gtest.dir/build.make:62: recipe for target 'third_party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o' failed
Oct 22 18:05:02 make[2]: *** [third_party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
Oct 22 18:05:02 CMakeFiles/Makefile2:888: recipe for target 'third_party/googletest/googletest/CMakeFiles/gtest.dir/all' failed
```

**Comment by pietern** [comment]
The release notes mention `TEST_CASE` is replaced by `TEST_SUITE`. Please check that the compilation logs are not overrun with deprecation messages (I recall seeing those in a separate project after upgrading gtest).

**Comment by rohan-varma** [comment]
@pietern I inspected some of the logs that run C++ tests and ran C++ tests locally, it does not look like these warnings are there. Are there any particular logs that we should check?

**Comment by pietern** [comment]
I guess they will show up if you build any of the C++ tests locally.

But more importantly, there is the clang build failure. Any idea what's causing it?

**Comment by rohan-varma** [comment]
It looks like there are compiler warnings, and then these warnings are treated as errors due to the compiler flags. one example:

```
Oct 28 20:52:28 /var/lib/jenkins/workspace/third_party/protobuf/src/google/protobuf/util/internal/proto_writer.h:113:24: warning: 'RenderBytes' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
Oct 28 20:52:28   virtual ProtoWriter* RenderBytes(StringPiece name, StringPiece value) 
```

**Comment by pietern** [comment]
Those appear to be fixed (or at least some subset) in https://github.com/google/googletest/issues/2493. Can you see if bumping the submodule beyond the release commit fixes the issue? It's not great if we pin to a non-release commit, but if it fixes this issue and unblocks the upgrade then I'm for it...

**Comment by pritamdamania87** [comment]
Looks like there are still a bunch of CI failures here. Would be nice to get this in if it's not too much effort to fix the failures.

**Comment by kostmo** [comment]
## :pill: CircleCI build failures summary and remediations
As of commit 8790c3fc:


* **1/1** failures introduced in this PR


## Detailed failure analysis

One may explore the probable reasons each build failed interactively [on the Dr. CI website](https://dr.pytorch.org/commit-details.html?sha1=8790c3fc725913e85164bd2b3dab79762015ae2e).

### :detective: 1 new failure recognized by patterns
The following build failures do not appear to be due to upstream breakage:
#### [See CircleCI build](https://circleci.com/gh/pytorch/pytorch/4317449) pytorch_linux_xenial_py3_clang5_asan_build (1/1)
**Step:** "Build" ([full log](https://dr.pytorch.org/api/view-log-full?build_id=89491505) | [pattern match details](https://dr.pytorch.org/build-details.html?build_id=89491505))
<details>
<summary>
<code>Jan 22 19:29:29 caused by: Connection refused (os error 111)</code>
</summary>

```
Jan 22 19:29:29 +++ eval 'extract_trap_cmd ' 
Jan 22 19:29:29 ++++ extract_trap_cmd 
Jan 22 19:29:29 ++++ printf '%s\n' '' 
Jan 22 19:29:29 +++ printf '%s\n' cleanup 
Jan 22 19:29:29 ++ trap -- ' 
Jan 22 19:29:29 cleanup' EXIT 
Jan 22 19:29:29 ++ which sccache 
Jan 22 19:29:29 ++ sccache --stop-server 
Jan 22 19:29:29 Stopping sccache server... 
Jan 22 19:29:29 error: couldn't connect to server 
Jan 22 19:29:29 caused by: Connection refused (os error 111) 
Jan 22 19:29:29 ++ true 
Jan 22 19:29:29 ++ rm /var/lib/jenkins/sccache_error.log 
Jan 22 19:29:29 rm: cannot remove '/var/lib/jenkins/sccache_error.log': No such file or directory 
Jan 22 19:29:29 ++ true 
Jan 22 19:29:29 ++ SCCACHE_ERROR_LOG=/var/lib/jenkins/sccache_error.log 
Jan 22 19:29:29 ++ SCCACHE_IDLE_TIMEOUT=1200 
Jan 22 19:29:29 ++ RUST_LOG=sccache::server=error 
Jan 22 19:29:29 ++ sccache --start-server 
Jan 22 19:29:29 Starting sccache server... 
Jan 22 19:29:29 ++ sccache --zero-stats 
```

</details>



---

<details><summary>This comment was automatically generated by <a href="https://github.com/kostmo/circleci-failure-tracker/tree/master/docs/from-pull-request-comment">Dr. CI</a> (expand for details).</summary>Follow <a href="https://dr.pytorch.org/admin/comments-opt-out.html">this link to opt-out</a> of these comments for your Pull Requests.

Please report bugs/suggestions on the <a href="https://github.com/kostmo/circleci-failure-tracker/issues">GitHub issue tracker</a>.
</details>

**Comment by rohan-varma** [comment]
@pritamdamania87, it looks like the CI failure is coming from an unused compiler flag warning being treated as an error:
```
Jan 22 19:29:52 [  0%] Building CXX object third_party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
Jan 22 19:29:52 clang: error: argument unused during compilation: '-pie' [-Werror,-Wunused-command-line-argument]
Jan 22 19:29:52 third_party/googletest/googletest/CMakeFiles/gtest.dir/build.make:62: recipe for target 'third_party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o' failed
Jan 22 19:29:52 make[2]: *** [third_party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
Jan 22 19:29:52 make[1]: *** [third_party/googletest/googletest/CMakeFiles/gtest.dir/all] Error 2
```
(https://circleci.com/api/v1.1/project/github/pytorch/pytorch/4317449/output/106/0?file=true&allocation-id=5e28a167a0354c4ab135faff-0-build%2F4D978AE2)

I can't tell if this is an issue coming from building gtest or a clang issue, but is there anyway to bypass these warnings when compiling third party modules? Other than that, I'm not sure if I see a way around this.

**Comment by pritamdamania87** [comment]
@rohan-varma Looking around, it seems like the issue might be that `-pie` needs to be passed as a flag during linkage and not during compilation and thats probably why we see that error. Are you able to build locally and is the issue only on CI? You can try tracking down where we specify that flag to see whether its a gtest issue or some build script on our end.

**Comment by rohan-varma** [comment]
@pritamdamania87 It builds locally. Will continue to try to figure out where that flag is being passed

**Pull request closed without merging**
