### PR TITLE
[Inductor][ROCm][CK] Enable lowering conv2d instances in CK Inductor backend

### PR DESCRIPTION
**Pull request by tenpercent**
Set PYTORCH_MIOPEN_SUGGEST_NHWC environment variable to force output layout to channels-last.

This way, the channels-last CK instances will be added to benchmark choices in max autotune

# Testing
```
pytest test/inductor/test_ck_backend.py -k conv2d
```

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang @naromero77amd @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @chauhang @aakhundov @zjing14

### CODE REVIEW

**Review by chenyang78 — APPROVED** [review]

**Comment by tenpercent** [comment]
Link #125453

**Comment by wdvr** [comment]
@pytorchmergebot revert -m "reverting due to a large number of internal failures, see below" -c nosignal

Most errors have:
ModuleNotFoundError: No module named 'ck4inductor.grouped_conv_fwd'

cc @chenyang78

**Comment by tenpercent** [comment]
Looks like I'll have to wait until meta-internal CK has this PR https://github.com/ROCm/composable_kernel/pull/1585

**Pull request closed without merging**
