### PR TITLE
Turn on mkldnn in most builds except rocm

### PR DESCRIPTION
**Pull request by bddppq**

### CODE REVIEW

**Comment by soumith** [comment]
can we leave some builds out. ROCm build often is in flaky state, and we want to make sure non-MKL-DNN path is also always working.

**Comment by bddppq** [comment]
@soumith Which build variants do you suggest we to leave them out? 
(note this is already not turned on in conda CI builds)

**Comment by soumith** [comment]
just pick one or two, your choice.

**Review by gchanan — APPROVED** [review]
approved once one or two builds are left out :).

**Comment by bddppq** [comment]
#17748

**Pull request closed without merging**
