### PR TITLE
[MPS] Enable some tests

### PR DESCRIPTION
**Pull request by qqaatw**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by kulinseth** [comment]
@qqaatw , lets wait for this PR to be https://github.com/pytorch/pytorch/pull/95045 to be merged. As I am planning to move all the tests into categories of "ALLOWLIST", "UNDEFINED_BEHAVIOR" and "EXPECTED_FAILURES"...

**Comment by qqaatw** [comment]
> @qqaatw , lets wait for this PR to be #95045 to be merged. As I am planning to move all the tests into categories of "ALLOWLIST", "UNDEFINED_BEHAVIOR" and "EXPECTED_FAILURES"...

The PR was merged. Should we wait for your new PR with those new categories to be merged, or we can merge this one first?

**Comment by kulinseth** [comment]
> > @qqaatw , lets wait for this PR to be #95045 to be merged. As I am planning to move all the tests into categories of "ALLOWLIST", "UNDEFINED_BEHAVIOR" and "EXPECTED_FAILURES"...
> 
> The PR was merged. Should we wait for your new PR with those new categories to be merged, or we can merge this one first?

I think we are moving away from ALLOWLIST to just having a XFAILLIST. So these new tests will be automatically added to that PR.

**Comment by qqaatw** [comment]
> > > @qqaatw , lets wait for this PR to be #95045 to be merged. As I am planning to move all the tests into categories of "ALLOWLIST", "UNDEFINED_BEHAVIOR" and "EXPECTED_FAILURES"...
> 
> > 
> 
> > The PR was merged. Should we wait for your new PR with those new categories to be merged, or we can merge this one first?
> 
> 
> 
> I think we are moving away from ALLOWLIST to just having a XFAILLIST. So these new tests will be automatically added to that PR.

I see.

**Pull request closed without merging**
