### PR TITLE
fix torch.set_float32_matmul_precision doc 

### LINKED ISSUE #119606: `torch.set_float32_matmul_precision` doc issue wrt floating point formats
### 📚 The doc issue

There seems to be an documentation error on the [`torch.set_float32_matmul_precision`](https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html) page. For float16, bfloat16 and float32, the implicit mantissa bit seems to be included, e.g. float32 only has 23 explicitly stored mantissa bits, but the page says 24. [^1]

For TF32, 10 mantissa bits are mentioned, but for consistency it should be 11 (or the other values should be reduced to their explicitly stored bits). [^2]

[^1]: https://en.wikipedia.org/wiki/Single-precision_floating-point_format
[^2]: https://blogs.nvidia.com/blog/tensorfloat-32-precision-format/

### Suggest a potential alternative/fix

_No response_

cc @svekars @brycebortree

### PR DESCRIPTION
**Pull request by lancerts**
Fixes #119606, clearify the explictly stored number of bits in doc

### CODE REVIEW

**Review by eqy — APPROVED** [review]

**Comment by lancerts** [comment]
> ## Merge failed
> **Reason**: Approvers from one of the following sets are needed:
> 
> * functorch (kshitij12345, srossross, chillee, zou3519)
> * superuser (pytorch/metamates)
> * Core Reviewers (mruberry, lezcano, Skylion007, ngimel, peterbell10)
> * Core Maintainers (soumith, gchanan, ezyang, dzhulgakov, malfet)
> 
> Details for Dev Infra team

@malfet please check and lmk if things look good, thanks

**Review by malfet — APPROVED** [review]

**Pull request closed without merging**
