### PR TITLE
Use Manylinux2_28 for wheel builds

### LINKED ISSUE #123649: [RFC] PyTorch next wheel build platform: manylinux-2.28
### 🚀 The feature, motivation and pitch

CentOS EOL is scheduled for the summer: https://www.redhat.com/en/blog/fastest-road-centos-linux-red-hat-enterprise-linux

With official manylinux has moved to almalinux: https://github.com/pypa/manylinux/blob/main/docker/Dockerfile#L2

manylinux_2_28 (AlmaLinux 8 based)
Toolchain: GCC 12
x86_64 image: quay.io/pypa/manylinux_2_28_x86_64
aarch64 image: quay.io/pypa/manylinux_2_28_aarch64
ppc64le image: quay.io/pypa/manylinux_2_28_ppc64le
s390x image: quay.io/pypa/manylinux_2_28_s390x

Almalinux:
https://almalinux.org/

Opening this issue to gather feedback, decide on the timeline for migration of the wheel build images

Work Completed:

- [x] Create Docker Manylinx 2.28 builds
- [x] PyTorch Wheel Switch to Manylinux 2.28 https://github.com/pytorch/pytorch/pull/138732
- [x] Test-Infra Nova Workflows Switch to Manylinx 2.28 https://github.com/pytorch/test-infra/pull/5909
- [x] Triton Update https://github.com/pytorch/pytorch/pull/141704
- [x] Use Manylinux 2.28 on pytorch pytorch for all the architectures https://github.com/pytorch/pytorch/pull/143423

RFC: Discussion issue https://github.com/pytorch/pytorch/issues/126551

cc @seemethere @malfet @osalpekar @pytorch/pytorch-dev-infra @ptrblck

### PR DESCRIPTION
**Pull request by atalman**
Fixes https://github.com/pytorch/pytorch/issues/123649
Use Manylinux 2_28 Docker builds for PyTorch Nightly builds

This moves the wheels to a Docker image that uses : ``quay.io/pypa/manylinux_2_28_x86_64`` as a base rather then ``centos:7`` which is EOL on June 30, 2024.

Information:
https://github.com/pypa/manylinux#manylinux_2_28-almalinux-8-based

manylinux_2_28 (AlmaLinux 8 based)
Toolchain: GCC 13
Built wheels are also expected to be compatible with other distros using glibc 2.28 or later, including:
Debian 10+
Ubuntu 18.10+
Fedora 29+
CentOS/RHEL 8+

This migration should enable us to migrate to latest CUDNN version, and land this PR: https://github.com/pytorch/pytorch/pull/137978

### CODE REVIEW

**Review by Skylion007 — APPROVED** [review]

**Review by malfet — APPROVED** [review]
LGTM

**Comment by jondea** [comment]
I think https://github.com/pytorch/pytorch/pull/137696 is necessary when building for AArch64 using Manylinux2_28

**Review by huydhn — APPROVED** [review]

**Pull request closed without merging**
